### ISSUE TITLE
The promo watermark isn't FLOSS

### ISSUE THREAD

**Issue by Kekun** [darktable-org/darktable#10002]
I noticed Darktable uses the non-free `CC-BY-NC-3.0` license ([here](https://github.com/darktable-org/darktable/blob/master/data/darktable.appdata.xml.in#L10
)), making de facto the project as a whole non-free. After searching, it seems to be caused by the `data/watermarks/promo.svg` file, which contains mentions of using that license ([here](https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/data/watermarks/promo.svg?short_path=d8e98d2#L292) and [here](https://github.com/darktable-org/darktable/blob/e8cb2cb1d9a2b34a4bbe27278247dae0ff09c3c8/data/watermarks/promo.svg?short_path=d8e98d2#L301)).

Maybe it's worth changing the license of that file to a free one so the application as a whole can still be considered FLOSS? Or replacing the file if that's impossible.

**Comment by MRIG** [comment]
yeah, that was a long time ago, adding that file, as the author en creator  I would vote for delete my file, else changing the license, so feel free to do so

**Comment by johnny-bit** [comment]
@MRIG - would you mind doing a PR to change the file's licence? As the author you have the best claim to do that :)
