### ISSUE TITLE
lut3d module missing with OpenCL and on nvidia machine. Working on others.

### ISSUE THREAD

**Issue by ait-jorismak** [darktable-org/darktable#10007]
* darktable version : 3.7.0+977_gcf99bbb0e-win64
* OS                : Windows 10 x64
* Graphics card     : Issue is with Nvidia GTX 1060, issue not present with Intel HD 620.
* Graphics driver   : 471.96

Probably related / the same as #9389.
I got a thread at https://discuss.pixls.us/t/lut3d-missing-under-windows-with-opencl-enabled-nvidia-gtx1060/26801

I tried the build from the 'Darktable insider builds'. It's a (weekly?) recurring Windows builds on the latest master, over on discuss.pixls.us.

On a laptop with Windows 10 x64 and only an integrated Intel HD 620, the lut3d module is visible with that build. Even when I enable OpenCL by ignoring the blacklist, the module is available and seems to work fine.

Running `darktable-cltest -d opencl` (and ignoring the blacklist) shows this in the output:

```
25.582978 [opencl_init] compiling program `lut3d.cl' ..
25.589105 [opencl_fopen_stat] could not open file `C:\Users\Joris\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_IntelRUHDGraphics620_3001009805\lut3d.cl.bin.aabc4477eb6083be791a4d23a01c70ab'!
25.604388 [opencl_load_program] could not load cached binary program, trying to compile source
25.610002 [opencl_load_program] successfully loaded program from 'C:\Program Files\darktable\share\darktable\kernels\lut3d.cl' MD5: 'aabc4477eb6083be791a4d23a01c70ab'
26.278944 [opencl_build_program] successfully built program
26.284176 [opencl_build_program] BUILD STATUS: 0
26.288561 BUILD LOG:
26.290779
26.292476 [opencl_build_program] saving binary

...

32.989790 [opencl_create_kernel] successfully loaded kernel `lut3d_tetrahedral' (226) for device 0
32.994448 [opencl_create_kernel] successfully loaded kernel `lut3d_trilinear' (227) for device 0
32.999348 [opencl_create_kernel] successfully loaded kernel `lut3d_pyramid' (228) for device 0
33.002711 [opencl_create_kernel] successfully loaded kernel `lut3d_none' (229) for device 0
```

Darktable works fine, and the lut3d module is visible and usable.

_**BUT**_, when I try the exact same build on another Windows 10 x64 desktop with a GTX 1060, I get ...

```
2.893794 [opencl_create_kernel] successfully loaded kernel `lowpass_mix' (225) for device 0
[iop_load_module] failed to open `lut3d': 'C:\Program Files\darktable\lib\darktable/plugins\liblut3d.dll': The specified procedure could not be found.
2.910136 [opencl_create_kernel] successfully loaded kernel `monochrome_filter' (226) for device 0
```

...at the end of the same `darktable-cltest -d opencl` command. (No blacklisting of drivers here).
All other OpenCL modules seem fine, and report no errors. Darktable also starts fine and works OK. But lut3d module is missing.

If I start Darktable with the `--disable-opencl` flag, then lut3d is visible and works on this machine! (But of course OpenCL is completely disabled).

So, the build seems to OK. No gmic dependency problems, because it works fine on both machines with OpenCL disabled. But only on the desktop (Nvidia) machine is lut3d not working _with_ OpenCL.

It almost looks like the lut3d OpenCL 'program' calls a function that is not available with the Nvidia OpenCL implementation? Nvidia claims at least OpenCL 3.0 'conformity' since around April 2021.

I've seen that `failed to open 'lut3d': 'C:\Program Files\darktable\lib\darktable/plugins\liblut3d.dll': The specified procedure could not be found.` error before in other issues, but they always focus on dependency problems in the build or a 'too new' OpenCV version during compilation.

I know the build isn't my own, but it seems to work fine for a lot of people, and it's working fine on another Windows machine right here. Also, some remarks think the path is wrong, because of the backslash and forward slash combination. But often this works fine on msys2 systems, and - repeating myself - it works fine on another computer, so it can't be related to that.

Since on discuss.pixls.us people can't seem to help me further, I thought I try this. I know Windows problems are hard to debug in a mostly Linux-focused developer team, but I can try :).

**Comment by phweyland** [comment]
Thanks for this detailed report.
> BUT, when I try the exact same build on another Windows 10 x64 desktop with a GTX 1060, I get ...

Seen the timestamp in the following trace it seems we are in a case of reload of dt, i.e. not the first time that open cl module are built.

Could you have the same trace as the first one but with GTX 1060 ?
For that you have to clean up the cache to force to rebuild open cl modules.

**Comment by ait-jorismak** [comment]
Yeah I tried a few times so I copy & pasted from another run.

I cleared the opencl-cache (%localappdata%\microsoft\windows\inetcache\darktable) and run `darktable-cltest -d opencl` again on the Nvidia machine:

```
4.972834 [opencl_init] compiling program `lut3d.cl' ..
4.980647 [opencl_fopen_stat] could not open file `C:\Users\Joris\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_NVIDIAGeForceGTX10606GB_47196\lut3d.cl.bin.4d10d2e559c090e86370806038d4724c'!
4.990924 [opencl_load_program] could not load cached binary program, trying to compile source
4.995184 [opencl_load_program] successfully loaded program from 'C:\Program Files\darktable\share\darktable\kernels\lut3d.cl' MD5: '4d10d2e559c090e86370806038d4724c'
5.051002 [opencl_build_program] successfully built program
5.053672 [opencl_build_program] BUILD STATUS: 0
5.055976 BUILD LOG:
5.057143

5.058214 [opencl_build_program] saving binary

...

8.401407 [opencl_create_kernel] successfully loaded kernel `warp_kernel' (223) for device 0
8.418174 [opencl_create_kernel] successfully loaded kernel `lowlight' (224) for device 0
8.435452 [opencl_create_kernel] successfully loaded kernel `lowpass_mix' (225) for device 0
[iop_load_module] failed to open `lut3d': 'C:\Program Files\darktable\lib\darktable/plugins\liblut3d.dll': The specified procedure could not be found.
8.669742 [opencl_create_kernel] successfully loaded kernel `monochrome_filter' (226) for device 0
8.673910 [opencl_create_kernel] successfully loaded kernel `monochrome' (227) for device 0
8.691385 [opencl_create_kernel] successfully loaded kernel `negadoctor' (228) for device 0
8.708377 [opencl_create_kernel] successfully loaded kernel `nlmeans_init' (229) for device 0
8.712450 [opencl_create_kernel] successfully loaded kernel `nlmeans_dist' (230) for device 0
```

If you want to full output or another way to get debug info, please let me know!

**Comment by phweyland** [comment]
Thanks, the opencl module compiles properly, the problem is not there.

Please share the full output (as an attached file). No much hope but we need to check.

**Comment by ait-jorismak** [comment]
[darktable-cltest-log.txt](https://github.com/darktable-org/darktable/files/7173616/darktable-cltest-log.txt)

**Comment by phweyland** [comment]
Just built dt on windows 10 (1809) with GTX 1050 nvidia driver 27.21.14.5671
I've completely reinstalled msys2 and followed the windows build.md instructions.
opencl and Lut 3d do work here.

I see your driver version has another numbering. How do you get it ?

**Comment by ait-jorismak** [comment]
> I see your driver version has another numbering. How do you get it ?

By looking at the number on the Nvidia site and in the Nvidia control panel :).
Your number 27.xx is clearly not the number the rest of the internet is using to identify the driver version.

OpenCL 3.0 support is available from 'R465 onwards' for example.
The Debian / Ubuntu apt-store has them labeled as '304', '367', '384', etc...

If you google for 'Nvidia driver issues' you find posts labeled liked 'driver 417.22 issues', 'issue with latest driver (451.48)'.

So, I'm curious. Where do _you_ get that version number of yours? :)

**Comment by phweyland** [comment]
![image](https://user-images.githubusercontent.com/23012047/134144389-a16af130-777e-4e8e-a8e2-0d5c209165d0.png)

and the nvidia control panel gives the version 456.71

**Comment by ait-jorismak** [comment]
Ah... that's the .sys / .dll of the core of it. But a graphics driver consists of sooo many components that it's only a small part of it, and something that might not even change that much.

Anyway, you got a setup that works on at least something of the same generation. So that means: Thanks, let's try 456.71 then!

**Comment by ait-jorismak** [comment]
@phweyland Did you try to run darktable-cltest.exe? Is OpenCL enabled and working on your build?

**Comment by ait-jorismak** [comment]
Hey!!I never wanted to build darktable because I was afraid it would conflict with the gtk-develop chain I had to use for my work.

But I made a backup and took the plunge, and since my gtk-chain is completely through MSVC and in the normal Windows world, it seems to be nicely separated from the MSYS2 world and gcc.

Anyway, did my first Darktable build for Windows. Went smooth without a single hickup (congrats!).
And, _**lut3d opencl kernel is working now**_. 

I didn't touch my Nvidia drivers yet.

So it _**was**_ the build after all, but still it only affects Nvidia-opencl implementation ?!

I have yet to test the installer that came from the build, but running `/opt/darktable/bin/darktable-cltest -d opencl` now just seems to work fine.

```
...
14.664300 [opencl_create_kernel] successfully loaded kernel `lowlight' (224) for device 0
14.670239 [opencl_create_kernel] successfully loaded kernel `lowpass_mix' (225) for device 0
14.934402 [opencl_create_kernel] successfully loaded kernel `lut3d_tetrahedral' (226) for device 0
14.936400 [opencl_create_kernel] successfully loaded kernel `lut3d_trilinear' (227) for device 0
14.938216 [opencl_create_kernel] successfully loaded kernel `lut3d_pyramid' (228) for device 0
14.940062 [opencl_create_kernel] successfully loaded kernel `lut3d_none' (229) for device 0
14.945207 [opencl_create_kernel] successfully loaded kernel `monochrome_filter' (230) for device 0
14.947014 [opencl_create_kernel] successfully loaded kernel `monochrome' (231) for device 0
...
```

Any clue on what might be going wrong in the original build?

**Comment by phweyland** [comment]
> Running from the installed-location but from the msys2 prompt works fine!

There is long time I haven't used dt on window, but that's something I did see in the past. msys2 prompt doesn't always work as windows cli.
Confusing indeed. But you have made progress ! :smile:

**Comment by ait-jorismak** [comment]
Yeah, but msys2 prompt just starts the .exe file. It's not as if it's a completely different runtime or anything.
So what could be possible is that some environment variables are not set on stock windows CMD that _are_ set on msys2 and those make a difference... for one module on one machine ?! :).

It works now from the windows CMD as well, after restarting.

It appears 'installing msys2 and building darktable' actually fixed the problem, even if I now start other builds. So I still suspect a change in things like PATH, other environment vars or a dll that is not copied from msys2 to the darktable-bin folder...

... but it's working now, so I'm happy. And I've built DT myself, so that makes testing and bug reports better down the line, since I can actually give info about the build :s.

**Comment by phweyland** [comment]
Excellent!
