### ISSUE TITLE
2021-09-12 build still will not recognize Win64 backslash

### ISSUE THREAD

**Issue by 520kaymann** [darktable-org/darktable#10000]
**Did you buy darktable from an application store ?**
No
**Describe the bug/issue**
When the settings for import use proper Win backslash to delineate folders darktable deletes them and creates a massive folder:
Example of import settings for base directory naming pattern: D:\Users\User1\PictureFolder\Folder1
Actual import: D:\UsersUser1PictureFolderFolder1

Example sub directory naming pattern:  $(EXIF_YEAR)\$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)
Actual sub directory naming pattern: $(EXIF_YEAR)$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY) Literally exactly like this

Import begins and creates an error message for ever photo: 
"error loading file 'D:UsersUser1PicturefolderFolder1\2021$(EXIF_YEAR)$(EXIF_YEAR)-09-11-11-12-32-0377.CR2'

A folder is created 'D:\UsersUser1PictureFolderFolder1\2021$(EXIF YEART)-09-11

Inside that folder the naming structure is correct.

darktable then flashes '## photos imported'

Because the actual folder does not match the settings folder the collection does not exist and is not shown.

**To Reproduce**
_Please provide detailed steps to reproduce the behavior, for example:_
1. Go to 'settings'
2. Click on 'import'
3. Scroll down to 'base directory naming pattern use a backslash instead of a double backslash'

**Expected behavior**
D:\Users\User1\PictureFolder\Folder1\2021\2021-09-13\

**Which commit introduced the error**
Since the beginning of time... :)

darktable version : 3.7.0+1046~g79fb97ced
* OS                :  Win 10 21H02
* Memory            : 32 GB
* Graphics card     : RTX 2060
* Graphics driver   : latest
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with ALL versions**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? No
  
![Screenshot 2021-09-13 161507](https://user-images.githubusercontent.com/57155093/133171176-2b5f7011-0d2c-43a0-a921-1b30a94cb3eb.png)
![Screenshot 2021-09-13 161739](https://user-images.githubusercontent.com/57155093/133171189-1a1de5dc-d29a-4089-857a-d035097eee42.png)

**Comment by Mark-64** [comment]
Sorry, but this is by design.
DT is a FOSS cross-platform SW and the vast majority of its dev community uses Linux as a primary OS.
In Linux, backslash can be part of a regular file name.
Moreover in many programming languages, including C and C++ which are the main ones used in DT, a backslash works as an escape character in string literals. As such, it needs to be escaped itself with another backslash. 
So you need to use a double backslash in the string to actually get a single backslash for a path.
Trying to change this might be possible, but we would most likely run into all sort of weird issues with C/C++ compilers, especially for old versions. I don't believe it is worth the effort.
So please use a double backslash or a single forward slash, as Windows accepts that as well.

**Comment by parafin** [comment]
Yes, this is invalid, \ is an escape character in some contexts including this. For example it allows the result you get - folder named literally ${EXIF_YEAR}. which would be impossible if escaping didn't exist.

**Comment by 520kaymann** [comment]
Ok I run both Linux and Win and C so I get it but just to clarify if the single slash breaks the collection module so the only real option is the double backslash which works for me. I will need to remember to tell people I refer to dt about that... :) As most everybody I refer is a current Win 10 user. Thank you for the quick replies and all the work that is done on dt!!!!

**Comment by 520kaymann** [comment]
Mark-64 I cannot thank you enough for bringing this incredible software to Windows users.

YOU are deeply appreciated!
