### ISSUE TITLE
opencl support not available in DT 3.6 (Manjaro/opencl-amd)

### ISSUE THREAD

**Issue by printausgabe** [darktable-org/darktable#10015]
With DT 3.6.0-3 and opencl-amd (21.30.1290604-1) with an AMD RX 6600XT i can't get the GPU support to work properly (fresh Manjaro 21.2.2 installation with KDE). Below you can find the output of clinfo etc. 

After installing darktable-cr3-git 3.7.0-2 it works but here I have issues with strong highlights so I can't use this version. I've also tried to downgrade the opencl-amd version but this leads to segfaults when using clinfo or darktable-cltest. So I suppose either there is a bug in opencl-amd or in DT 3.6 but I have no idea how to proceed and I haven't found another workaround for it yet. 

Thanks!

`system:    Kernel: 5.13.15-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 
           parameters: BOOT_IMAGE=/@/boot/vmlinuz-5.13-x86_64 root=UUID=5f866a68-332d-49a2-aca4-cf9c2c30e908 rw 
           rootflags=subvol=@ quiet apparmor=1 security=apparmor resume=UUID=9aeb3831-32c8-49de-95ed-775cb2d7dd97 
           udev.log_priority=3 

Desktop: KDE Plasma 5.22.5 tk: Qt 5.15.2 wm: kwin_x11 vt: 1 dm: SDDM Distro: Manjaro Linux base: Arch Linux 
`

**Output of clinfo:**
`Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (3314.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx1032
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 2.0 
  Driver Version                                  3314.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         Navi 23 [Radeon RX 6600/6600 XT/6600M]
  Device PCI-e ID (AMD)                           0x73ff
  Device Topology (AMD)                           PCI-E, 0000:0c:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               16
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                32
  SIMD instruction width (AMD)                    1
  Max clock frequency                             2900MHz
  Graphics IP (AMD)                               10.3
  Device Partition                                (core)
    Max number of sub-devices                     16
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple (kernel)     32
  Wavefront width (AMD)                           32
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              8573157376 (7.984GiB)
  Global free memory (AMD)                        8372224 (7.984GiB) 8372224 (7.984GiB)
  Global memory channels (AMD)                    4
  Global memory banks per channel (AMD)           4
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           7287183768 (6.787GiB)
  Unified memory for Host and Device              No
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    7287183768 (6.787GiB)
  Preferred total size of global vars             8573157376 (7.984GiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             29695
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 8192 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             16384x16384x8192 pixels
    Max number of read image args                 128
    Max number of write image args                8
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    16
  Max pipe packet size                            2992216472 (2.787GiB)
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Local memory size per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        7287183768 (6.787GiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                262144 (256KiB)
    Max size                                      8388608 (8MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Number of P2P devices (AMD)                     0
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        0ns (Thu Jan  1 01:00:00 1970)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    Number of async queues (AMD)                  8
    Max real-time compute queues (AMD)            8
    Max real-time compute units (AMD)             16
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
  clCreateContext(NULL, ...) [default]            Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx1032
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx1032
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   gfx1032

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.3.1
  ICD loader Profile                              OpenCL 3.0
`

**Output of darktable-cltest:**
`.013833 [opencl_init] opencl related configuration options:
0.013840 [opencl_init] 
0.013842 [opencl_init] opencl: 1
0.013843 [opencl_init] opencl_scheduling_profile: 'very fast GPU'
0.013844 [opencl_init] opencl_library: ''
0.013845 [opencl_init] opencl_memory_requirement: 768
0.013847 [opencl_init] opencl_memory_headroom: 400
0.013848 [opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
0.013850 [opencl_init] opencl_mandatory_timeout: 200
0.013851 [opencl_init] opencl_size_roundup: 16
0.013852 [opencl_init] opencl_async_pixelpipe: 0
0.013853 [opencl_init] opencl_synch_cache: active module
0.013854 [opencl_init] opencl_number_event_handles: 25
0.013855 [opencl_init] opencl_micro_nap: 1000
0.013856 [opencl_init] opencl_use_pinned_memory: 0
0.013856 [opencl_init] opencl_use_cpu_devices: 0
0.013857 [opencl_init] opencl_avoid_atomics: 0
0.013858 [opencl_init] 
0.013990 [opencl_init] found opencl runtime library 'libOpenCL'
0.014005 [opencl_init] opencl library 'libOpenCL' found on your system and loaded
0.060205 [opencl_init] found 1 platform
0.060215 [opencl_init] found 1 device
0.060226 [opencl_init] device 0 `gfx1032' supports image sizes of 16384 x 16384
0.060227 [opencl_init] device 0 `gfx1032' allows GPU memory allocations of up to 6949MB
[opencl_init] device 0: gfx1032 
     GLOBAL_MEM_SIZE:          8176MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 1024 ]
     DRIVER_VERSION:           3314.0 (HSA1.1,LC)
     DEVICE_VERSION:           OpenCL 2.0 
0.213381 [opencl_init] options for OpenCL compiler: -w -cl-fast-relaxed-math  -DAMD=1 -I"/usr/share/darktable/kernels"
0.213586 [opencl_init] compiling program `demosaic_ppg.cl' ..
0.213822 [opencl_load_program] loaded cached binary program from file '/home/items/.cache/darktable/cached_kernels_for_gfx1032_33140HSA11LC/demosaic_ppg.cl.bin' MD5: '53f37f8e2f8d9ed925d67971b1af1c97' 
0.213830 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/demosaic_ppg.cl' MD5: '53f37f8e2f8d9ed925d67971b1af1c97'
0.214516 [opencl_build_program] successfully built program
0.214524 [opencl_build_program] BUILD STATUS: 0
0.214527 BUILD LOG:
0.214528 
0.214535 [opencl_init] compiling program `atrous.cl' ..
0.214610 [opencl_load_program] loaded cached binary program from file '/home/items/.cache/darktable/cached_kernels_for_gfx1032_33140HSA11LC/atrous.cl.bin' MD5: 'cbd62f93ddfb7705b96f63f2090ea33b' 
0.214619 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/atrous.cl' MD5: 'cbd62f93ddfb7705b96f63f2090ea33b'
0.214847 [opencl_build_program] successfully built program
0.214855 [opencl_build_program] BUILD STATUS: 0
0.214857 BUILD LOG:
0.214858 
0.214864 [opencl_init] compiling program `basic.cl' ..
0.215768 [opencl_load_program] loaded cached binary program from file '/home/items/.cache/darktable/cached_kernels_for_gfx1032_33140HSA11LC/basic.cl.bin' MD5: '7ec6758cb7f3a77d3e726473a825fdce' 
0.215776 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/basic.cl' MD5: '7ec6758cb7f3a77d3e726473a825fdce'
0.219483 [opencl_build_program] successfully built program
0.219492 [opencl_build_program] BUILD STATUS: 0
0.219495 BUILD LOG:
0.219497 
0.219504 [opencl_init] compiling program `blendop.cl' ..
0.219668 [opencl_fopen_stat] could not open file `/home/items/.cache/darktable/cached_kernels_for_gfx1032_33140HSA11LC/blendop.cl.bin'!
0.219676 [opencl_load_program] could not load cached binary program, trying to compile source
0.219685 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/blendop.cl' MD5: '659a4e8d7cb0972344d959dcb4ff251d'
0.901947 [opencl_build_program] could not build program: -11
0.901959 [opencl_build_program] BUILD STATUS: -2
0.901961 BUILD LOG:
0.901961 lld: error: undefined hidden symbol: rgb_to_JzCzhz
>>> referenced by /tmp/comgr-6ab5c7/input/linked.bc.o:(blendop_display_channel)
>>> referenced by /tmp/comgr-6ab5c7/input/linked.bc.o:(blendop_display_channel)
>>> referenced by /tmp/comgr-6ab5c7/input/linked.bc.o:(blendop_display_channel)
>>> referenced 9 more times

lld: error: undefined hidden symbol: get_rgb_matrix_luminance
>>> referenced by /tmp/comgr-6ab5c7/input/linked.bc.o:(blendop_display_channel)
>>> referenced by /tmp/comgr-6ab5c7/input/linked.bc.o:(blendop_display_channel)
>>> referenced by /tmp/comgr-6ab5c7/input/linked.bc.o:(blendop_display_channel)
>>> referenced 1 more times
Error: Creating the executable from LLVM IRs failed.

0.901966 [opencl_init] failed to compile program `blendop.cl'!
0.901971 [opencl_init] no suitable devices found.
0.901972 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.901973 [opencl_init] initial status of opencl enabled flag is OFF.
`

**Outpout of lsmod|grep amd:**
`amdgpu               7053312  59
edac_mce_amd           32768  0
gpu_sched              45056  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
drm_ttm_helper         16384  1 amdgpu
ttm                    77824  2 amdgpu,drm_ttm_helper
drm_kms_helper        294912  1 amdgpu
pinctrl_amd            32768  0
drm                   585728  22 gpu_sched,drm_kms_helper,amdgpu,drm_ttm_helper,ttm
`

**Comment by johnny-bit** [comment]
Looks like this might be a duplicate of #8831 which is fixed and will be part of 3.8 release. please check if workarounds mentioned in the issue and PR fixing the issue fix the problems for you as well.

**Comment by printausgabe** [comment]
Not sure if it is a duplicate and I was not able to downgrade opencl-amd. Maybe because of the 6600XT, which is pretty new in the market so that a very recent driver is necessary. 
So I ended up with the 3.7 CR git and the highlight problems only occur if I import images, that have been already heavy developed with n masks etc. If I duplicate the original image and start new, everything works fine. This wouldn't be acceptable for a professional but I'm fine with that and I suppose it is maybe either because of my change from a nvidia card to an AMD card or it is maybe caused by the new opencl-amd version together with DT 3.6. But anyway.... it works now, is pretty fast and there are just a very few images with very strong and sometimes blown highlights (against the sun etc.) where it occurs. 

Thanks a lot for your help!
