### ISSUE TITLE
Failure to import files whose path contains a special character (for example 'ä')

### ISSUE THREAD

**Issue by StruffelProductions** [darktable-org/darktable#10028]
**Did you buy darktable from an application store ?**

No, downloaded it from darktable.org

**Describe the bug/issue**
Darktable cannot import files if their file path contains a special character like ä, ö, ü, é or è (those are the ones I tested).
When importing the software displays the toast message "Imported X images", but none of the images actually show up. It's as if I had never imported them.

**To Reproduce**
Create a new folder whose name contains a special character on the desktop and put a RAW file into it (I used .NEF). I have prepared such a folder on [Google Drive](https://drive.google.com/drive/folders/11gDIn5jULKjg8pUKcZhXxuRBSZV-Oky_?usp=sharing), simply extract it after downloading.
Then try to import the image contained in that folder by simply opening the software and clicking "Import...".
The small import message reads "1 image imported", but the image does not show up in the list.

**Expected behavior**
I expect the image to be imported like any other, even if it's parent folder has an 'ä' in its name.
Alternatively, I expect at least a clear error message stating that this the file path is unsupported.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0.1 (installer: darktable-3.6.0.1-win64.exe)
* OS                : Windows 10 Version 21H1 (Build 19043.1237)
* Memory            :  64GB @ 3000Mhz
* Graphics card     : NVIDIA GTX 1080 Ti
* Graphics driver   :  30.0.14.7111

**Additional context**
_Please provide any additional information you think may be useful, for example:_

- I tried removing all user data by deleting the darktable folder in AppData\Local, no changes.
- I tried a fresh install, no changes.
- I encountered this issue both while using an SMB share and my local disk.

**Comment by Mark-64** [comment]
This has been fixed already, please install 3.6.1
