### ISSUE TITLE
Text Captions (expansion of Watermark feature)

### ISSUE THREAD

**Issue by qystan** [darktable-org/darktable#10025]
**Describe the solution you'd like**
Allowing text captions.  

I do bird photography and I include a text caption for the name of the bird, location and date so that it is helpful information for myself and viewers.

**Alternatives**
Using an external bitmap editor to do the caption works but it is not a smooth process.  

Using the Watermark feature.  
While it works, it is limited to only 1 line of text.  

**Additional context**

Expanding the Watermark feature to accept multi-lines will be great.  

To minimise changes and work, allow the user to type CTRL-ENTER or ALT-ENTER character to indicate next line in the $WATERMARK_TEXT input field.

**Comment by ralfbrown** [comment]
I've looked at embedding newlines in the WATERMARK_TEXT input field, and it doesn't work because the SVG renderer ignores them....
(that's by design, since the input field just becomes the content between `<text>` and `</text>` tags)

I'd like not only multi-line text, but also the option of having a fixed font size instead of one which scales with the content.

**Comment by SoupyGit** [comment]
Just adding my voice of support to watermark module allowing multiple lines of text.
Another great feature would be choosing their alignment with each other (eg. left align, center, right align)

Is currently possible to achieve with multiple instances of the module, but more of a pain.

**Comment by dterrahe** [comment]
Are those here aware that it is possible to provide custom svg files to the watermark module? Use Inkscape to for example open share/darktable/watermarks/metadata-template.svg
You can customise and put in your own configuration directory in a subdirectory "watermarks", press the refresh button next to the list dropdown in the module.

**Comment by ralfbrown** [comment]
True, but that requires a new SVG file each time you want to use different text.

**Comment by dterrahe** [comment]
The OP seems to want to use it for metadata and tags, so additional freeform/multiline text may not be needed there.

**Comment by dterrahe** [comment]
Could you put the species in a tag and use the tag in the svg? I think I read somewhere that people wanted a $(variable) that showed the location (GPS) information in descriptive format (place name) but I'm not sure what the status of that is. The capture date can definitely be included as a variable in the svg, so wouldn't require amending the file.

**Comment by qystan** [comment]
I'll have to figure out the SVG and tag thing, any chance you have links to this subject?  Not familiar as I have not explored Darktable in any depth because of this limitation.

Not optimistic about location in descriptive format based on GPS data but if tags work, perhaps it can be another tag for this.

**Comment by dterrahe** [comment]
Like I said, have a look at share/darktable/watermarks/metadata-template.svg and remove what you don't want. The available variables are here https://darktable-org.github.io/dtdocs/en/special-topics/variables/
There doesn't seem to be a descriptive location variable, so you may need to put that in a tag (or you could use the metadata fields description or title).

There is a special variable $(WATERMARK_TEXT) that presumably you can only use in this module and svg file. With all these options, I would think you should be able to do what you want. If not, there might be a genuine need to expand functionality here, so please report back your findings.

**Comment by qystan** [comment]
It worked.  Used "$(WATERMARK_TEXT)" for the first and "$(TAGS)" for the second.  

The SVG file contents ( ignore the double quotes, the displayed text was quirky without them):

"$(WATERMARK_TEXT)"
"$(TAGS)"
"$(EXIF.DAY)" "$(EXIF.MONTH)" "$(EXIF.YEAR)"

Managed this result.  
![Capture](https://user-images.githubusercontent.com/63985586/200349808-c0011aac-8b63-4cee-9228-3c0cba1fcc86.PNG)

**Comment by qystan** [comment]
For benefit of others who may be facing the same constraints.

The following constraints were noted using TAGS and WATERMARK_TEXT.  
1. TAGS will print all tags in one line, it prevents you from using tags for other purposes.
2. WATERMARK_TEXT allows only 1 text string and need to be entered each time.   

Alternative is to use categories.  It allows quick tagging by clicking from a list (same tag window in lighttable) instead of having to type each watermark, this is useful for data re-use consistency like bird types which will repeat and locations which will have repetitions.  This method gives unlimited labels.

For my purpose, I have 2 categories, "places" and "birds" and tags (bird names and place names) under each.  The variables reference CATEGORY0 (zero) means to take the first data parameter from thee category "birds" or "places". The (birds) and (places) indicate which category to use. The new SVG file (again, ignore the double quotes and note the 0(zero) after CATEGORY):

"$(CATEGORY0(birds))"
"$(CATEGORY0(places))"
"$(EXIF.DAY)" "$(EXIF.MONTH)" "$(EXIF.YEAR)"

To create the nodes, use the "|" separator per the help documentation or create the categories followed by  each tag and drag and drop them into the desired category.  By having a second level, I can do sub-groupings.
https://docs.darktable.org/usermanual/4.0/en/module-reference/utility-modules/shared/tagging/

Hope this is useful for anyone else facing the same issues.

The "tagging" window in lighttable is attached for illustration.

![Capture](https://user-images.githubusercontent.com/63985586/200461730-20960265-0c84-4b52-9678-ec9ef65729ee.PNG)
