### ISSUE TITLE
UI broken when launching from batch file, WIN10

### ISSUE THREAD

**Issue by peltsippi** [darktable-org/darktable#10029]
So I am building this kind of Onedrive synced photo library so I can switch machines on the fly.

Launching darktable from batch file messes up the UI
see [photo](https://i.imgur.com/4JuLvQo.png)
Stars are not clickable, selections are not visible.

When I run exactly same command from command line by cding to executable directory and run darkroom.exe with same flags all work just fine, see [photo](https://i.imgur.com/GG6d6Ko.png)

Executable location is picked from following registy key and method:
for /f "usebackq tokens=3*" %%a in (`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\darktable.exe" /s`) do (
  set _darktable_path=%%a %%b

Path esolves to C:\Program Files\darktable\bin>darktable.exe

Everything else seems to work just fine. Just the UI is different.

**Comment by Mark-64** [comment]
for some reason DT doesn't find the .css theme.
in Windows, themes are in C.\Program Files\darktable\share\darktable\themes\

**Comment by peltsippi** [comment]
Yeah tested and changing theme does nothing when UI is messed up. So it probably involves something within my batch file. So I'll close this bug and figure out different way for launching the program correctly.

**Comment by peltsippi** [comment]
Actually got probably to the root of with with debugging output and it might also be something with the code that gets off with some (rare?) edge case. So I'll reopen this just in case.

This is the error I found:

`dt_gui_load_theme: error parsing combined CSS: <data>:1:77Failed to import: Error opening file \Program Files\darktable\share\darktable\themes\darktable.css: No such file or directory`

Path `C:\Program Files\darktable\share\darktable\themes` on this pc contains all css files just as it is supposed to. 

And my batch file executes the program in following way:
`START "" "C:\Program Files\darktable\bin\darktable.exe" --library !polku! --configdir !_settings_path!`

**Comment by wpferguson** [comment]
Does your script work if you change directory to C:\Program Files\darktable before you start darktable?

**Comment by peltsippi** [comment]
Switching drive letter to C: did the trick!

This was hard to reproduce. My desk pc had the css issue 100% of the time and laptop somewhere around 10-80% of the time. All with same batch file that did not change. But when I added CD /D C: everything seems to work just fine now.

Thanks a lot!
