### ISSUE TITLE
tone equalizer: eigf does not tolerate adding contrast to the mask

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#10034]
During my tests for developing #10027, I stumbled upon what I believe is an issue of the eigf default TE algorithm, and in particular of its surface blur. I will illustrate here how to reproduce with an example.

Start with an edit and roughly adjust exposure, filmic etc.

![1](https://user-images.githubusercontent.com/43290988/133965506-0f8ff091-4eea-4406-87ab-9b82c7413c08.jpg)

The pic is a bit hazy, so say I want to deepen shadows with TE. I dial some negative exp compensation to roughly center the mask

![1start](https://user-images.githubusercontent.com/43290988/133966213-6927b643-2bdd-4a28-93fd-9560130cc7d1.jpg)

![1startmask](https://user-images.githubusercontent.com/43290988/133966243-fd08e972-8826-40fe-be19-5ac38dc9b80e.jpg)

histogram looks quite compressed, I need to add some contrast to set apart shadows from the rest of the image.
I dial in some contrast, making sure I get no orange warnings in the grey bar

![1end](https://user-images.githubusercontent.com/43290988/133966418-9ae83ac2-833f-4684-ac2d-2d4e9d1e2121.jpg)

![1endmask](https://user-images.githubusercontent.com/43290988/133966434-d81eb98a-8a50-4a1c-8812-213cd6a735af.jpg)

but now look how in the mask there no surface blur anymore in shadows and most of them went pitch black.
If I now try to lower shadows:

![1histbad3](https://user-images.githubusercontent.com/43290988/133966601-25035a5e-2ce0-492e-b0f7-d8f9b2062be6.jpg)

I get artifacts

![1bad3](https://user-images.githubusercontent.com/43290988/133966670-31d98aba-ef7e-42d0-84fa-e606e564c51f.jpg)

because there is no longer detail preservation.

Note that the guided filter algorithm does not show that problem, I can actually apply way more contrast to the mask without adverse effects

**Comment by Mark-64** [comment]
@aurelienpierre 
I believe this has a lot to do with how constrast is applied. 
Current linear contrast is prone to this issue, while a plain log contrast behave much better for the shadows (and a bit less so for highlights).
See also my comments in my old PR #10014, now closed.

**Comment by aurelienpierre** [comment]
You simply need to reduce the contrast here…

**Comment by aurelienpierre** [comment]
> Note that the guided filter algorithm does not show that problem, I can actually apply way more contrast to the mask without adverse effects

Of course, because the vanilla GF is not exposure-invariant and therefore blurs the shadows more heavily than the highlights.

**Comment by Mark-64** [comment]
In `eigf.h`, the function 

```
void eigf_blending_no_mask(float *const restrict image,
                  const float *const restrict av, const size_t Ndim,
                  const dt_iop_guided_filter_blending_t filter,
                  const float feathering)
{

#ifdef _OPENMP
#pragma omp parallel for simd default(none) \
  dt_omp_firstprivate(image, av, Ndim, feathering, filter) \
  schedule(simd:static) aligned(image, av:64)
#endif

  for(size_t k = 0; k < Ndim; k++)
  {
    const float avg_g = av[k * 2];
    const float var_g = av[k * 2 + 1];
    const float norm_g = fmaxf(avg_g * image[k], 1E-6);
    const float normalized_var_guide = var_g / norm_g;
    const float a = normalized_var_guide / (normalized_var_guide + feathering);
    const float b = avg_g - a * avg_g;
    if(filter == DT_GF_BLENDING_LINEAR)
    {
      image[k] = fmaxf(image[k] * a + b, MIN_FLOAT);
    }
    else
    {
      // filter == DT_GF_BLENDING_GEOMEAN
      image[k] *= fmaxf(image[k] * a + b, MIN_FLOAT);
      image[k] = sqrtf(image[k]);
    }
  }
}
```
IMO `norm_g` can go down too low for deep shadows that are created by the linear contrast when pushed a bit.
As a consequence `normalized_var_guide` can easily be 200+, `a` becomes very close to 1 irrespective of `feathering`, `b` becomes very close to 0. Therefore 
`
image[k] = fmaxf(image[k] * a + b, MIN_FLOAT);`

becomes equal to itself, there is no blending and no blur at all. So vanilla gf blurs shadows too much, but eigf too little.
I found that replacing `1E-6` with `1E-3` as a minimum value keeps some small blur for deep shadows and performs much better when contrast is increased. see the previous example where I increased contrast even more, the histogram spans overs almost the full range and yet no artifacts in shadows.

![image](https://user-images.githubusercontent.com/43290988/134406854-71b1800b-588d-466f-be63-02b6a866e998.png)

![image](https://user-images.githubusercontent.com/43290988/134407268-ee0dc5a9-157d-4a94-91dc-030c8de82507.png)

![image](https://user-images.githubusercontent.com/43290988/134407349-7540d8df-a69b-417a-bf1a-68d0358c69e0.png)

@aurelienpierre if you are interested I can provide a test I have done with synthetic images that demonstrates current eigf applies no blur at all in deep shadows and the proposed modification improves a lot

**Comment by Mark-64** [comment]
By the way in the documentation comments at the top of eigf.h, it says

```
* we use a ratio:
 * variance / (pixel_value)^2
 * we tried also the following ratios:
 * - variance / average^2
 * - variance / (pixel_value * average)
 * we kept variance / (pixel_value)^2 as it seemed to behave a bit better than
 * the other (dividing by average^2 smoothed too much dark details surrounded
 * by bright pixels).
```

but the code implements  variance / (pixel_value * average) instead.

**Comment by aurelienpierre** [comment]
I don't understand the goal here.

Nobody said that any filter was immune to bad contrast values. Instead, the contrast correction is meant to make the mask more manageable. So the contrast **has** to be set such that the filter behaves, it's not for the filter to accommodate insane contrast settings.
