### ISSUE TITLE
shortcuts: wrong tree expanded

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10039]
In 3.7.0+1077~g3f81d9547.

Open the preferences dialog, select the "shortcuts" tab and then attempt to expand either the "other views" or the "fallbacks" tree. Instead, the "active view" tree is expanded.

This is not usually an issue when reaching this dialog via the "define shortcuts" button, since the appropriate tree is usually expanded when entering this dialog.

@dterrahe I seem to recall a similar issue with the "actions" tab but I don't remember what you did to fix it.

**Comment by elstoc** [comment]
N.B. This only happens when I click on the expander icon to expand the tree - clicking on the label expands the selection correction. If I click on the expander icon for the "other views" tree, it expands and then immediately collapses.

**Comment by dterrahe** [comment]
Thanks for the detail. I'll work on a fix and this helps testing a lot!
