### ISSUE TITLE
Lens correction for Canon EOS 80D not working without running lensfun-update-data

### ISSUE THREAD

**Issue by arntanguy** [darktable-org/darktable#10037]
## Problem

Attempting to use the `lens correction module` with CR2 files acquired from a Canon EOS 80D results in "camera/lens not found - please select manually" (Ubuntu 20.04, darktable master). The lens is correctly found, but the camera is not, and does not seem to be in the list. 

![Screenshot from 2021-09-20 19-25-12](https://user-images.githubusercontent.com/67139/134047265-c37ee006-4e62-48f5-9ed2-f0fa22a6eb63.png)

## Solution

It'd been bugging me, but I hadn't taken the time to look up the solution, and simply assumed the darktable support for this particular camera was maybe incomplete. However while thinking about opening this issue, I found the solution in a related issue: https://github.com/darktable-org/darktable/issues/9562, that is the ubuntu package for `lensfun` does not have up-to-date data and this needs to be updated using `lensfun-update-data`.

```
sudo apt install liblensfun-bin
lensfun-update-data
```

Now looking in the [documentation of the lens correction module](https://docs.darktable.org/usermanual/3.6/module-reference/processing-modules/lens-correction/), I realize the solution was briefly mentioned there:

> If you can’t find your lens, check if it is in the list of currently supported lenses, and try running the lensfun-update-data tool.

## Suggestion

I think it'd be more user-friendly if the error message from the `lens correction` module provided hints towards potential solutions, instead of the bland `"camera/lens not found - please select manually"`. Especially considering that the camera seems to be fully supported everywhere else except in that particular module, and that the `lensfun` dependency is not immediately clear to the user here. Or better yet, checking whether `lensfun-update-data` is present, and providing the option to run it from within the lens correction module directly.

**Comment by elstoc** [comment]
> I think it'd be more user-friendly if the error message from the lens correction module provided hints towards potential solutions, instead of the bland "camera/lens not found - please select manually".

IMO the user manual is the place for that sort of information and, as you have seen, this is already documented.

> Or better yet, checking whether lensfun-update-data is present, and providing the option to run it from within the lens correction module directly.

This is a duplicate of #4180

**Comment by arntanguy** [comment]
> IMO the user manual is the place for that sort of information and, as you have seen, this is already documented.

Yes it is. But I also believe that whenever possible it's also the role of the software to simplify the user experience and ensure that things "just work", especially when there is a known fix to a common issue ;)

I'll close this issue since it's already being discussed in #4180.
