### ISSUE TITLE
Darktable crashes on import TIFF-image

### ISSUE THREAD

**Issue by maxmeyer** [darktable-org/darktable#10045]
**Describe the bug/issue**

Darktable crashes with core dump, when it tries to import a certain TIFF-image. 

```
tiff_open] error: MissingRequired: TIFF directory is missing required "StripOffsets" field
Magick: TIFF directory is missing required "StripOffsets" field. (MissingRequired).
[GraphicsMagick_open] image `BatchTool-KB2991.digikamtempfile.tif' not found
darktable: magick/error.c:1025: ThrowLoggedException: Assertion `exception->signature == MagickSignature' failed.
[1]    418888 abort (core dumped)  darktable -d all > /tmp/darktable.log
```
[example-image-2.zip](https://github.com/darktable-org/darktable/files/7200829/example-image-2.zip)

During that time period (2016) I used digikam to download images from my SD cards. Digikam uses temporary files, `BatchTool-KB2991.digikamtempfile.tif`, before setting the correct filename.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Run darktable
2. Import and add to library

**Expected behavior**

No core dump, but a proper error message.

**Platform**

```
darktable --version
this is darktable 3.6.0
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

* darktable version : see above 
* OS                : `Linux 5.14.3-arch1-1 #1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000 x86_64 GNU/Linux`
* Linux - Distro    : Arch Linux
* Memory            : 64 GiB
* Graphics card     : AMD Radeon™ RX Vega 7 Graphics (AMD Ryzen 7 4800H) 
* Graphics driver   : amdgpu
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              :  1.20.13-2 
* Desktop           : i3
* GTK+              : unknown
* gcc               : gcc version 11.1.0 (GCC)
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? no

Using a different directory and try to import the file, I get these messages.

  ```
  [tiff_open] warning: TIFFReadDirectory: Unknown field with tag 50898 (0xc6d2) encountered
  [tiff_open] warning: TIFFReadDirectory: Unknown field with tag 50899 (0xc6d3) encountered
  [tiff_open] warning: TIFFFetchNormalTag: Incorrect value for "RichTIFFIPTC"; tag ignored
  [tiff_open] warning: TIFFReadDirectory: Unknown field with tag 50898 (0xc6d2) encountered
  [tiff_open] warning: TIFFReadDirectory: Unknown field with tag 50899 (0xc6d3) encountered
  [tiff_open] warning: TIFFFetchNormalTag: Incorrect value for "RichTIFFIPTC"; tag ignored
  validation check failed in _iop_validate_params for type "float", field: aspect
  validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
  ```

 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? no
 - Do you use lua scripts? no

**Comment by maxmeyer** [comment]
#9625 might have the same root cause.

**Comment by kmilos** [comment]
Not sure why this ends up with the GraphicsMagick delegate at all, is it because reading w/ libtiff initially fails?

`tiff_open] error: MissingRequired: TIFF directory is missing required "StripOffsets" field`

This really does indicate a corrupt TIFF file.

**Comment by maxmeyer** [comment]
@kmilos  Please see my comment below "Additional context". Placing the file in a different directory solves the problem as well, so this might be related to some entry in my dt database.
