### ISSUE TITLE
Tethering with Nikon D3200

### ISSUE THREAD

**Issue by llmvangaal** [darktable-org/darktable#10049]
![error-0](https://user-images.githubusercontent.com/90129317/134158494-cd1a6ac1-272f-4dd6-b503-24001abbd64d.jpg)
![error-3](https://user-images.githubusercontent.com/90129317/134158498-221ce600-0b33-46ad-87e6-df085f37ea28.jpg)

Tethering with my Nikon D3200 gives a bad result.

I have installed zadig 2.5 and exectuted it. Now I can connect my camera and enable liveview (printscreen in file error-0).

But:
If I make a picture the result is that a file is stored but there are no pixels in it. (file error-3)

Does anyone have an idea how to solve this?

**Comment by llmvangaal** [comment]
Hubert, 

This issue is about writing a (corrupt) file to a disk when capture a picture, and the other issue was about reading a corrupt file in lightroom.

Therefore it's not a duplicate (but a better explanation of the fact that I cann't tether (on windows) with my Nikon D3200. I hope this is helpful to the developer

**Comment by llmvangaal** [comment]
![1-external drive](https://user-images.githubusercontent.com/90129317/134768089-875848b4-3b1a-4dc6-ac3f-4d4b01a3b98d.jpg)
![2-nikon-drivers](https://user-images.githubusercontent.com/90129317/134768091-5f1dc0ad-6cfe-466b-ab34-95ab762bed45.jpg)
![3-failed-to-initialize](https://user-images.githubusercontent.com/90129317/134768092-1183d7be-ac1f-4691-822a-ada1afa3a63e.jpg)
![4-digicamontrol](https://user-images.githubusercontent.com/90129317/134768095-7011d7a1-c08f-454d-b6f9-3c562b7c668f.jpg)

The driver for the Nikon D3200-camera, doesn't work for darktable but works for digicamcontrol. If it's helpful I can upload the files of the Nikon D3200-camera. After executing zadig 2.6 live view is available in darktable but the images captured are corrupt.

**Comment by llmvangaal** [comment]
I don’t know how to close it😢

Groet,
Leo

**Comment by TurboGit** [comment]
Closed.
