### ISSUE TITLE
Input NG: Default actions seem to show a blank effect

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10046]
When assigning simple shortcuts to widgets, the default action appears to show an element but without an effect in the shortcuts pane of the setup window.

For example, if I assign the `#` key to a processing module, the default action shows as a blank effect on the show element (should show "toggle"?):

![Screenshot_2021-09-21_08-27-48](https://user-images.githubusercontent.com/9555491/134129441-80f7fca5-9b2d-4dc1-b667-baf7c84b026f.png)

Similarly, if I assign the `#` key to a slider, the default action shows as a blank effect on the value element (should show "edit"?):

![Screenshot_2021-09-21_08-29-13](https://user-images.githubusercontent.com/9555491/134129649-5ac0bd82-6ed0-4f4a-a263-7336f20e75ee.png)

**Comment by dterrahe** [comment]
This indicates that fallbacks exist that might change the effect.

**Comment by elstoc** [comment]
But the default should be obvious. An "element" without an "effect" doesn't make sense. It's more obvious for the module (what else could "show" really apply to?) but for the slider there are many different effects on the "value" element. The default needs to be explicitly listed.

**Comment by Nilvus** [comment]
In CSS, there's already padding and selected effect present. You can see that in delete all images of a filmroll/folder confirmation dialog box (see following screenshot), so there's probably something to improve in Gtk code to use existing CSS settings like in other similar boxes.

![image](https://user-images.githubusercontent.com/45535283/134206735-0d10091f-8d33-4ded-b425-ba8faf64d7bc.png)
