### ISSUE TITLE
Input NG: Consider swapping the shortcuts and actions panes

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10040]
In the shortcuts setup window, clicking on the lower (actions) pane causes the contents of the upper (shortcuts) pane to update. This feels slightly unnatural to me and that the panes should be swapped around.

@dterrahe what was the reason these were put this way around? Perhaps I'm missing something important.

**Comment by dterrahe** [comment]
Will do. It was already part of the failed PR that reshuffled the buttons/search boxes. I'm working on other fixes and will submit all together in one PR soonish.

Initially I envisioned the actions pane to be a sort of type selection/filtering dropdown, which in file-open style dialogs is often positioned underneath the file list. It makes much less sense now (although a new user might still be interested in the existing shortcuts first and if you call up the details for widget, for example to adjust speed, having them on top is not too illogical). I'll follow user feedback here.

**Comment by dterrahe** [comment]
@Nilvus how is it useful to assign an issue to me that I already submitted a PR that resolved it for? This just means I get spam emails.

**Comment by Nilvus** [comment]
> @Nilvus how is it useful to assign an issue to me that I already submitted a PR that resolved it for? This just means I get spam emails.

Oups, sorry

**Comment by dterrahe** [comment]
3x
