### ISSUE TITLE
Input NG: styling of popup confirmation boxes

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10047]
When you attempt to assign an action to a shortcut that is already used, a message box appears asking if you want to remove the existing shortcut. The selected option (no by default) should be shown highlighted so that people know what the default is as it's not currently clear what will happen if you just press Enter:

![Screenshot_2021-09-21_08-37-46](https://user-images.githubusercontent.com/9555491/134130885-44b5e8cb-0edc-4af8-8089-07ea544a5998.png)

Similarly with removing shortcuts:

![Screenshot_2021-09-21_08-36-57](https://user-images.githubusercontent.com/9555491/134130765-e35d9ff3-fe56-4a91-b6ec-70519e87dd6a.png)

Also, these boxes need some padding as the text rubs right against the edge of the messagebox.

**Comment by dterrahe** [comment]
Funny how you are picking off my todo list of little niggles.

I am using the existing `dt_gui_show_standalone_yes_no_dialog` which needs love but is used in irregularly used (and therefore harder to test) database maintenance. So I'll see if this is easily fixable without likely breakage.

**Comment by johnny-bit** [comment]
Well... standalone yes_no dialog is supposeed to be used when we can possibly not have main window... But using it should make no problems other than styling issues.

**Comment by Nilvus** [comment]
In CSS, there's already padding and selected effect present. You can see that in delete all images of a filmroll/folder confirmation dialog box (see following screenshot), so there's probably something to improve in Gtk code to use existing CSS settings like in other similar boxes.

![image](https://user-images.githubusercontent.com/45535283/134206735-0d10091f-8d33-4ded-b425-ba8faf64d7bc.png)

Edit: there's a little more top padding in this dialog windows (it's just the screenshot cut!).
