### ISSUE TITLE
Compress History Stack

### ISSUE THREAD

**Issue by 520kaymann** [darktable-org/darktable#10052]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Compress History Stack is if number of edits to extensive and the thumbnail row is turned visible

**To Reproduce**
1. Go to 'darkroom'
2. Make edits
3. Try to scroll down to 'compress history stack '

**Expected behavior**

**Screenshots**

![Screenshot 2021-09-21 154834](https://user-images.githubusercontent.com/57155093/134257771-9f50ef9d-2db5-4272-8f22-3f876f07657a.png)

**Which commit introduced the error**
Unknown

**Platform**

* darktable version : 3.7.0+1046~g79fb97ced
* OS                : Win 10 64
* * Memory         :  32 GB
* Graphics card     : RX 2060
* Graphics driver   : Latest

**Additional context**
Moving the strip around can expose it eventually (SHIFT-CNTRL b)

**Comment by wpferguson** [comment]
Can't you just move your mouse over the scroll bar and scroll the window up until the 'compress history stack' button is visible?

**Comment by ptilopteri** [comment]
or <ctrl><alt><scroll> with mouse over left menu stack

**Comment by elstoc** [comment]
we could just move the button to the top of the module

**Comment by 520kaymann** [comment]
No the scroll bar will not expose the button and minimizing maximizing the entire DT window does not expose it either. I tried all of this in 3.6.1 and the problem exist there as well. The only solution seems to be to get rid of the thumbnail row compress and then I can bring back the thumbnails. The thumbnails seem to have some always on top property the the compress button is not recognizing....

**Comment by ptilopteri** [comment]
with the left menu column visible and the film strip visible, it is possible
to scroll the menu column by holding the <ctrl> and <alt> buttons down
and rotating the scroll wheel.

there is no need to move the "button".

**Comment by elstoc** [comment]
Yes it's possible but is it necessary to do that? I often want to compress history but I rarely want to go back to view the really early steps in that history. So having scrolling content is fine but I would honestly prefer compress at the top.

**Comment by 520kaymann** [comment]
Please look at my photo and you will see the scroll bar is scrolled all the way to the bottom.  No amount of scrolling is able pull the history up above the film roll... Compare the 2 screenshots . The only difference is the filmroll
![Screenshot 2021-09-22 075612](https://user-images.githubusercontent.com/57155093/134368227-ad866bf4-c43a-4ad4-b6a6-5d8ddc48c9c2.png)
![Screenshot 2021-09-22 075538](https://user-images.githubusercontent.com/57155093/134368253-e6b1dd4a-8bb9-48c9-919e-93203fa43442.png)

![Screenshot 2021-09-22 075538](https://user-images.githubusercontent.com/57155093/134368288-20647efb-4521-48c7-a049-ab890a455397.png)

**Comment by wpferguson** [comment]
Use the scrollbar on the left, which scrolls the entire left panel

**Comment by wpferguson** [comment]
Look at the bright side, you learned something new today  :)

**Comment by elstoc** [comment]
Ah should have tried actually running dt before commenting. The button is not part of the scrollable content.
