### ISSUE TITLE
Guide lines over the white frame of the color assessment conditions.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10060]
**Describe the bug/issue**
In the darkroom if guide lines are active and user activate the color assessment conditions the guides are on top of the white frame and over the gray at 18% background when images are zoom in at 100 or 200% 
Occasionally guides fill a part of the white frame at left or right. But always over the white frame.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to darkroom 
2. Activate the guide lines icon
3. Activate the color assessment conditions  icon
4. Zoom the image up to 50, 52% or 100 and 200%

**Expected behavior**
The guide lines must be under the white frame of the color assessment conditions and the gray at 18% background at any size or zoom.

**Screenshots**

At full size it is ok.
![Screenshot-20210922124534-3004x1897](https://user-images.githubusercontent.com/67672868/134387470-1959b97a-3ddd-450e-a826-20597f728c81.png)

Zoom at 52%
![Screenshot-20210922133131-3157x2106](https://user-images.githubusercontent.com/67672868/134393048-a26f0088-b67a-4684-b6e8-efbd63dfcded.png)

Zoom in with the scroll mouse button up to 100%.
![Screenshot-20210922124440-3251x2067](https://user-images.githubusercontent.com/67672868/134387576-c56ee7b0-7313-4992-989e-8f37f213e820.png)

At 200%
![Screenshot-20210922124509-3264x2087](https://user-images.githubusercontent.com/67672868/134387725-c167fe2e-7d8d-4a55-be81-4a6af58264f0.png)

**Platform**
darktable version : 3.7.0~git1090.cefba2ca81-6575.1
Linux - Kernel: 5.12.17-300.fc34.x86_64 Fedora 34
OS: Fedora 34 (Workstation Edition) x86_64
Host: Z390 AORUS MASTER
Kernel: 5.12.17-300.fc34.x86_64
Uptime: 35 mins
Packages: 2052 (rpm), 11 (flatpak), 3 (snap)
Shell: bash 5.8
Resolution: 3840x2160
DE: GNOME 40.4
WM: Mutter
WM Theme: Materia-dark-compact
Theme: Mojave-dark [GTK2/3]
Icons: Os-Catalina-icons-master [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 2219MiB / 32037MiB
Graphics driver : 460.73.01
OpenCL installed : yes
OpenCL activated : yes

**Comment by AlicVB** [comment]
confirmed. this is also present in 3.6... read : that's not my fault ;)
Note that this is also present without the color assessment, just less visible !

I'll have a look
