### ISSUE TITLE
Changing language makes Darktable freezing when restarting

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#10065]
I'm runing Darktable on MacOS 10.15.7 and build Darktable myself.
Current DT version is 3.7.0+1090~gcefba2ca8-dirty

I use Darktable in french and sometimes I need to set language to english.
I did it yesterday but Darktable freezes when restarting to apply changes.
it is the same with `ca`, `es`, `it`, `pt_PT`, `sk`, `sr`, `el`, `ru`, and `ja` languages.

I have noticed the value of ~/.config/darktable/ui_last/darktablerc `ui_last/gui_language` is set to `C` when setting it to English.

Here is the log [https://pastebin.com/79VaQu59](url)

**Comment by Nilvus** [comment]
Just tested and works great on my side (I'm also using french) with 3.7.0+1104~gab7f6e784. Update master and test again to see and report here if it solves your issue or issue still there on your side. As I use Linux, if issue still there with same master version, that could means or an OS issue related to darktable on MacOS or an issue related to your config.

**Comment by Jiyone** [comment]
I just tested with 3.7.0+1122~g362a952f6 and it's still not working.

**Comment by parafin** [comment]
Can it be reproduced with 3.6.1 package? I couldn't on macOS 10.14.

When exactly does darktable freeze for you? It's not totally clear if it's during shutdown or when starting. How do you recover from the freeze?

**Comment by Jiyone** [comment]
_Can it be reproduced with 3.6.1 package? I couldn't on macOS 10.14._
It is working fine with 3.6.1.6.

_When exactly does darktable freeze for you? It's not totally clear if it's during shutdown or when starting. How do you recover from the freeze?_
It is freezing when restarting, at start of Darktable, it shows the little grey window with arrows and nothing more.
I recover by editing  ~/.config/darktable/darktablerc `ui_last/gui_language` value back to `fr` for example.

**Comment by parafin** [comment]
Fix merged, please retry.

**Comment by TurboGit** [comment]
No answer, let's close this for now.
