### ISSUE TITLE
Collections: support selection of multiple values

### ISSUE THREAD

**Issue by arntanguy** [darktable-org/darktable#10068]
**Is your feature request related to a problem? Please describe.**

Currently, the collection module filters all accept only one selected element, or in case of numerical values a combination of operator and value (number range `[X;Y]`, `>= X`, etc). For each filter, a list/tree view of elements is shown (great). However, it is generally not possible to select multiple distinct elements from this list.

Examples:
- Selecting for multiples tags `x`, `y` and `z` requires adding three filters, each selecting for a single tag
  - `tag: x`
  - `tag: y`
  - `tag: z`
- Same goes for film rolls, folders, etc
- Selecting a bunch of specific apertures `x`, `y` `z` would also require 3 filters. In that case it is possible to select a contiguous range (e.g `[x;z]`), but not specifically x, y and z (feels inconsistent from an UI point of view: the user would intuitively expect to be able to select multiple values).
- Same goes for all numerical filters

**Describe the solution you'd like**

I think it'd be both quicker and more consistent to handle selection of multiple distinct elements for a single filter where it makes sense. For example:
- Having a `tags` filter that accepts `x;y;z` as a criteria (with each individual element `x`, `y` and `z` selectable from the list view).
- Having numerical filters handle `x;y;z` values
  - For example, suppose you're filtering by aperture, but would only like f5.6 and f11, you'd input `5.6;11` (or Ctrl+click on these elements in the list view).

This is of course a very minor suggestion, and it would complicate a bit the implementation. In most cases that'd resume to using `expression IN ( x, y, z, ...)` in SQL queries, and slightly complicate the list/tree view selection and filtering code. I'm not 100% sure if it's really worth it as everything is already achievable as-is (albeit with a bit of GUI fiddling involved to add all the desired filters) doesn't happen all that often), and creating new collections doesn't happen all that often. If people like the idea, I could see about implementing it.

### Visual example based on my open PR #10030 

Selecting the non-contiguous range of ratings `-1;1;3;4` currently requires to do some combination of filters. Either select the whole range `[-1;4]` and then narrow it down by rejecting `<> 0` and `<> 2`; or adding an individual filter for `-1`, `1`, `3` `4`.
![Screenshot from 2021-09-23 19-21-00](https://user-images.githubusercontent.com/67139/134554566-e731ec1a-811f-499d-b1f5-9537819b1e0e.png)

Instead we could Ctrl-click on the rating entries in the list and generate the filter `-1;1;3;4` in just 4 clicks (I haven't drawn the selected state here, but -1, 1, 3 and 4 rows would be selected).
![Screenshot from 2021-09-23 19-21-42](https://user-images.githubusercontent.com/67139/134554970-e44d3171-5b92-4c6d-9a95-9555c6b1feab.png)

**Comment by quovadit** [comment]
It would be great to have multi-select for all collection-criteria.

For numerical values, the benefit for me would be limited, because range-selection makes sense most of the time.
(why would I want to select rating 1 + 3 without 2?)

BUT: 
For non-numerical values there is no quick way at the moment to select more than one entry.
This could be tags, but also creator, camera, folder, ...

I'm not sure, if semicolon (;) is the best choice to separate the list of distinct entries, because that's the current separator for ranges.
