### ISSUE TITLE
A new icon for TE former pickers

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#10063]
With #10027, in TE the picker icons have been with non-toggle buttons.
For the moment the "auto-levels" icon from retouch has been recycled, but it's not nice

![image](https://user-images.githubusercontent.com/43290988/134474160-f2e19d70-d911-4a68-a5a7-786841b0781c.png)

I would like to design a new icon in replacement. A few proposals here:

1) An "auto" sign
![Screenshot from 2021-09-23 08-59-32](https://user-images.githubusercontent.com/43290988/134474370-e1997f81-51c6-4531-ab16-9723d28d51ed.png)

![Screenshot from 2021-09-23 09-03-43](https://user-images.githubusercontent.com/43290988/134474600-89b88167-12d2-4cb5-b6b5-1f640a139be2.png)

2) A magic wand

![Screenshot from 2021-09-23 09-10-51](https://user-images.githubusercontent.com/43290988/134474444-88280e23-7ccf-461d-93c4-030e9af0c2d5.png)

3) A "target" sign

![Screenshot from 2021-09-23 10-05-40](https://user-images.githubusercontent.com/43290988/134474489-cb56d2a0-d252-48e0-ab81-32075998eb4b.png)

![Screenshot from 2021-09-23 10-06-26](https://user-images.githubusercontent.com/43290988/134474505-5681129a-e6cf-4f8e-9c0f-b9b5ed0bba1a.png)

Opinions ?

**Comment by difrkaguilar** [comment]
Just a proposal
![autolevels_01](https://user-images.githubusercontent.com/67672868/134483116-019820f9-ec62-48c7-88cf-02a9ae2fbfbf.png)

![autolevels_02](https://user-images.githubusercontent.com/67672868/134483147-b6470931-ead3-4193-80dd-2225ffbc6b24.png)

autolevels_icon_16x16.svg file
[autolevels_icon_16x16.zip](https://github.com/darktable-org/darktable/files/7216335/autolevels_icon_16x16.zip)

**Comment by elstoc** [comment]
Of those options, I think I prefer the wand.

**Comment by TurboGit** [comment]
> Of those options, I think I prefer the wand.

I also prefer this magic wand.

**Comment by TurboGit** [comment]
> Edit: ok maybe now I prefer @difrkaguilar's suggestion.

This seems more tailored to the actual two usage in `tone equalizer`, but maybe less generic and not really reusable in other contexts.

**Comment by Mark-64** [comment]
so here is the magic wand, it's a bit thick but if I do it slimmer it will be almost invisible on small screens.
If you like it I can do a PR

![image](https://user-images.githubusercontent.com/43290988/134648052-44112003-2cfa-4d87-9968-2b681abc8dca.png)

**Comment by elstoc** [comment]
shouldn't it be black with a white end? :)

**Comment by Mark-64** [comment]
> shouldn't it be black with a white end? :)

On a dark background the logic is reversed, no? 
I can try to see if it is better, but the problem of these super small icons is that you need to "fill the box" with something or it will look inconspicuous.

**Comment by elstoc** [comment]
I really don't mind - it was kind of tongue-in-cheek. I think the icon looks good.
