### ISSUE TITLE
Editing Issues: Photos Become Pixelated In Lighttable When Adjusting Images

### ISSUE THREAD

**Issue by mcdonaldms** [darktable-org/darktable#10079]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
No, downloaded off of Darktable's website. 

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**
The issue I continue having with the latest version is whatever I try adjusting the image bugs out. For example: if I begin adjusting the brightness, the image become s pixelated either in certain areas or the entire image. So far it seems that anything I adjust may affects the image; tried restarting the adjustment and readjusting, sometimes it worked but the bug would continue. Darktable also exports the image while it is pixelated, and will provide an example photo as well! (If the image doesn't appear here, contact me at: mcdonaldms@me.com, and will send an image through there!)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
Click on : "Contrast, Brightness, Saturation"
Move the adjuster bar for "Brightness" feature (also occurs with any other adjustment feature, for myself at least)

**Expected behavior**
Image will begin to bug out, or pixelate.

**Screenshots**
_(if applicable)_
![IMG_2878_01](https://user-images.githubusercontent.com/91358479/134756869-ec6dd924-bc51-4ed2-a9ca-45aaa36d7b7b.jpg)

**Screencast**
_(if applicable)_
[](url)
**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0
* OS                : Win10 (Patchlevel)
* Memory            : 1 Tb. 
* Graphics card     : NVidia Geforce RTX 2070 Super

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nilvus** [comment]
Are you sure you use last master version? Or do you forget to precise it? 3.5.0 is a quite old master version. We are actually on 3.7.0 and more than 1100 commits for 3.7.0, so version at least 3.7.0+11xx...

Thus, your screenshot lets think of some clipped highlights. It would be good to be sure that you use last version. So please help by cleaning your issue (remove all not necessary information and comments provided in template issue (edit your post) then update to last master version and post version you use (or update version if you forget to). Thanks.
