### ISSUE TITLE
[map - dragging] unexpected behaviour when dragging 

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10076]
current master, and in 3.6.0 and 3.6.1

In map view, begin dragging an image already on map putting the mouse in the thumbnail: when the thumbnail begins moving according to the drag movement, the thubnail is suddenly moved right-up so that the bottom-left tip is now in the position of the mouse.

This is very annoying:
- you expect that the thumbnail is dragged with the mouse pointer the user put inside the thumbnail.
- if you want to move very slightly the image to the right, and you begin dragging toward the right, you are obliged to go back to the left :-(
- if you grab the image in the upper right corner of the thumbnail, even a very little dragging will move the image to a further distance

Darktable should leave the thumbnail in the position (relative to the mouse pointer) where the user begun dragging: this way the correct final position of the image in the map will be achieved in a easier easier way.

**Comment by Nilvus** [comment]
Not sure but I remember some long time ago similar discussion about that and that was some Gtk related issue. But maybe my memory is bad here. @phweyland or @johnny-bit: as you work on map part and osm-gps-map one, maybe you will be more precise here.

**Comment by phweyland** [comment]
The second point is the normal behavior. There is a threshold to start a drag. If not you will always move the thumbnail clicking on it. Then for a thumbnail move less than the threshold you have to move the thumbnail a bit further the threshold and come back. Of course the value of the threshold can be revisited.

Today the dragging hotspot is the arrow end, wherever the user clicks on the thumbnail, to keep it simple I suppose. To get the best experience the user has to init the drag movement as close as possible of the arrow end.

I agree that's not an optimal behavior. There should be a way to make it work as you describe, I'll look at it. Thanks.

**Comment by paolobenve** [comment]
@phweyland works perfectly, thank you!
