### ISSUE TITLE
No grouping of JPEG and RAW after "Copy and Import"

### ISSUE THREAD

**Issue by emanuele** [darktable-org/darktable#10085]
In Darktable v3.6.1 (at least on Ubuntu 20.04), after executing "copy & import..." on pictures which with double file, i.e., JPEG + RAW, the "collapse grouped images" function in the Lighttable does not work anymore, meaning that corresponding JPEGs and RAWs are not grouped anymore.

I guess that the reason of this issue is that on "copy & import...", each original file gets a different name with a progressive number, so corresponding JPEGs and RAWs get different filenames, losing the property to refer to the same picture. Example: if the original files are A.JPEG and A.RAW, then "copy & import..." will turn them into 0001.JPG and 0002.RAW

Notice that, if I just "add to library..." the pictures (so no copying and renaming), then the automatic grouping of the corresponding JPEGs and RAWs works as expected and each shot appears once in the lighttable.

Is the behavior of no grouping after "copy & import..." intended to be like that?

Best,

Emanuele

**Comment by phweyland** [comment]
> Is the behavior of no grouping after "copy & import..." intended to be like that?

No, you are right, it should work as with [add to library ...]. I'll look at this. Thanks.

**Comment by emanuele** [comment]
Excellent, thank you.

**Comment by phweyland** [comment]
Do you have the possibility to check if [import from camera...] has the same behavior as [copy & import...} ?

**Comment by quovadit** [comment]
same problem with [import from camera...] using 3.6.0

**Comment by phweyland** [comment]
@wpferguson, to solve this I have to sort the list of images to be sure to have the jpeg next to the raw. This is something you already do for lua in _control_import_job_run().
I see you sort using only the basename (instead of the full path). What is the reason for that ?
If I do it for for every import, I'll remove the lua counter part, ok ?

**Comment by wpferguson** [comment]
I'm not sure why they only sorted on basename.  Less characters, so a faster sort.  I believe the intent of the function was to implement the raw/jpeg import filters that exist in lua, so moving the sort out of _apply_lua_filter() and putting it into _control_import_job_run() makes sense.

**Comment by phweyland** [comment]
@wpferguson, I've proposed a fix for this issue. You may want to have a look on it. TIA.
