### ISSUE TITLE
Leica Digilux 3

### ISSUE THREAD

**Issue by rhurlin** [darktable-org/darktable#10088]
> Before filing any support requests, please do make sure that you have already
> contributed the whole raw sample set for your camera under CC0 license to
> https://raw.pixls.us/ !

Done. The raw sample file is named `L1050624.RAW`.

> #### Important note: to make sure that darktable can keep on supporting the raw
> file format for your camera, *please* read
> [this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
> how/what raw samples you can contribute to ensure that we have the *full* raw
> sample set for your camera under CC0 license!

Please integrate the **Leica Digilux 3** in the list of supported cameras. The mounted lens on the camera was a "`Leica D Vario-Elmarit 1:2.8-3.5/14-50 Asph. E72`".

Please let me know if I have to give more info and/or other shots ;)

Thanks for your work!

**Comment by kmilos** [comment]
Copy job of [Lumix DMC-L1](https://en.wikipedia.org/wiki/Leica_Digilux_3)?

How about a DNG sample as well, as it adds that mode over the L1?

**Comment by rhurlin** [comment]
Hi @kmilos,
Thanks for your response.

As far as I can say, copying the job of the L1 would be fine for the Digilux 3. Both seem to have `Panasonic Raw version 2.1` and `Panasonic RAW 4 compression`.

I am pretty sure that there is no DNG format with this camera, only the Panasonic Raw format.

What I am missing in both applications, darktable and rawtherapee, is **some information about the used lens type** (like _Leica D Vario-Elmarit 1:2.8-3.5/14-50 Asph._). But this is more a problem of `lensfun`, isn't it?

**Comment by kmilos** [comment]
> What I am missing in both applications, darktable and rawtherapee, is **some information about the used lens type** (like _Leica D Vario-Elmarit 1:2.8-3.5/14-50 Asph._). But this is more a problem of `lensfun`, isn't it?

Sadly it looks like nether exiftool nor exiv2 manage to decode the proprietary information about the attached lens in this Panasonic raw format (if it exists that is) to pass on to lensfun...

**Comment by kmilos** [comment]
Btw, [we have adobe_coeffs for both cameras for a while](https://github.com/darktable-org/darktable/blob/4f002be678ad91f96f535ee461808d1477c7f0d3/src/external/adobe_coeff.c#L529-L530), but it seems more recent ADC versions slightly tweaked the color matrix (at least for the DMC-L1, Digilux 3 is not up on RPU yet to compare):

`8054,-1886,-1025,-8348,16367,2040,-2805,3542,7630`

**Comment by rhurlin** [comment]
Thanks for both pieces of information and sorry for the delay. I have been very busy today.

That the adobe_coeffs for the Digilux 3 are already integrated is really interesting :)

**Comment by kmilos** [comment]
> That the adobe_coeffs for the Digilux 3 are already integrated is really interesting :)

Not really ;) I think these coeffs were inherited from dcraw since they are "older" cameras, and it was already known back then they're "equivalent"...

**Comment by kmilos** [comment]
With the sample now up on RPU, I have confirmed there is no difference between the DNG metadata (apart from WB presets but those do not affect raw parsing), so it should be safe to copy the DMC-L1.

**Comment by rhurlin** [comment]
Many thanks for the commit! Really appreciated  \o/
