### ISSUE TITLE
[export -> preferences] inconsistencies

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10086]
3.6.1 and master

The general settings in export -> preferences have some inconsistencies, at least looking at the ui:
![exportPreferences](https://user-images.githubusercontent.com/1417508/134789495-ea167618-13cf-451e-a5aa-e2f5f69c51fe.png)

- the "hierarchical tags"  and the "geo tags" preferences should belong to the group "tags", like "private tags" and "synonyms"
- all the options are interpreted by the user as "include this group of information", but "omit hierarchy" is inconsistent with that assumption and leaves the user confused; it should be recognized as something different
- unselecting the "tags" preference should blur the preferences in its group, and selecting it should unblur them

This is what the user expects, according to the way the ui has been though, I think. In this case, the title above could be happily changed from "general settings" to "include", and "omit hierarchy" could be in the bottom of the window, separated from the "include" options.

Or the meaning was intended to be different? if the meaning is different, IMHO the design of those preferences should be changed.

**Comment by phweyland** [comment]
I've read the doc again. I don't find any inconsistency.

**Comment by paolobenve** [comment]
I'd say that the label `tag` (the one after `geo tags`) is quite poor, and lets the user which hasn't read the manual with a misunderstanding, because _per se_ the dialog transmit the information that all the other some-level labels that use the word _tag_ are a subset of it.

Reading https://docs.darktable.org/usermanual/3.6/module-reference/utility-modules/shared/export/ I'd suggest to use something must specific, as "user created tags", "custom tags", "user tags"

Anyway, with reference to the sub-labels of the _tag_ label, an option hierarchy is clearly suggested graphically: the user expects that "private tags", "synonyms" and "omit hierarchy" are subsets of "tags", and then should be dimmed and made unchangeable when "tags" is cleared.

If the option hierarchy suggested graphically doesn't correspond to the behaviour of the code, the UI should be changed so as not to deceive the user. 

About the "omit hierarchy" label, I keep saying that it has a logical behaviour different from "private tags" and "synonyms", which are parallel to it, and it would be better that the behaviour were of the same kind; for example a label like "hierarchy" which when clicked works as the contrary of "omit hierarchy".

This is what I'd say reading the docs and looking at the dialog.

Or might it be that the docs need to explain better something that now is rather obscure?

**Comment by phweyland** [comment]
> Anyway, with reference to the sub-labels of the tag label, an option hierarchy is clearly suggested graphically: the user expects that "private tags", "synonyms" and "omit hierarchy" are subsets of "tags", and then should be dimmed and made unchangeable when "tags" is cleared.

I gladly grant you this point.
