### ISSUE TITLE
Custom crop settings aspect "remove duplicates"-feature

### ISSUE THREAD

**Issue by pahlers** [darktable-org/darktable#10091]
I was adding an extra "crop aspect" for Instagram (4:5 and 1.91:1) according the manual.

> If you want to add an aspect ratio to the pre-defined drop-down list you can do this by including a line of the form “plugins/darkroom/clipping/extra_aspect_ratios/foo=x:y” in darktable’s configuration file $HOME/.config/darktable/darktablerc. Here “foo” defines the name of the new aspect ratio and “x” and “y” the corresponding numerical values (x and y must be integers). 

So I added: `plugins/darkroom/clipping/extra_aspect_ratios/instagram=4:5`. But it didn't work! I didn't saw my aspect ration in the list regardless of my efforts. No extra ratio, but also no error. Not in the console or application. Strange isn't it?

It turns out the code is has an undocumented "feature" called "remove duplicates from the aspect ratio list" (https://github.com/darktable-org/darktable/blob/release-3.6.1/src/iop/clipping.c#L2263-L2285). This code prevents double aspect ratios, which makes sense if it would cause performance issues.

It is very hard for a common user to understand this feature and I would like to suggest a change for this feature.

My suggestion would be one of the following options:
1. **Remove the "remove duplicates from the aspect ratio list"-code.** It would be a handy feature that a user can add ratios using his own labels. **And** there will be 22 lines less code, yeah! :raised_hands:. Kill your darlings @houz :wink:. (bonus points when you can edit the list within the application);
2. **Expand the existing label with the custom label.** The user can still customise and the list stays short (and fast);
3. **Throw an error when the custom ratio is deleted.** This way the user can learn and call himself stupid;
4. ~~**Update the documentation with a description of this "feature".** This would be also an option.~~ Done by @elstoc :+1: 

Fix this "feature", please.

**Comment by pahlers** [comment]
Hey! Don't let me down. I did my best to descibe this bug. At least a response like "Nop, not going to fix" would be appropriate.

**Comment by elstoc** [comment]
Someone will look at it if and when someone looks at it. This is a volunteer project and if someone comes across your FR and decides to code it, then it will be coded. If not, then not.
