### ISSUE TITLE
documentation:  Web site - https://www.darktable.org/about/features/

### ISSUE THREAD

**Issue by wubwubwubwubwubwubwubwub** [darktable-org/darktable#10092]
I'm not sure how to report this, but this seems like a reasonable place.
The Features page has some broken links to blogs, I think these are the correct links:

Ulrich's post (shadows and highlights):  https://www.darktable.org/2012/02/shadow-recovery-revisited/

Ulrich's post (tone curve): https://www.darktable.org/2012/02/mastering-color-with-lab-tone-curves/

Johannes' post (color correction): https://www.darktable.org/2012/03/color-correction/

Henrik's post (vibrance):  https://www.darktable.org/2011/10/different-kind-of-saturation/

"this post" (color LUT): https://www.darktable.org/2016/05/colour-manipulation-with-the-colour-checker-lut-module/

liquify post:  https://www.darktable.org/2016/04/liquify-liquify/

perspective correction:  https://www.darktable.org/2016/03/a-new-module-for-automatic-perspective-correction/

profiled denoise:  https://www.darktable.org/2012/12/profiling-sensor-and-photon-noise/

Ulrich's post (lowpass):  https://www.darktable.org/2012/02/using-lowpass-filter-to-recover-shadows/

**Comment by elstoc** [comment]
documentation requests should be raised against darktable-org/dtdocs

website changes should be raised against darktable-org/dtorg

**Comment by johnny-bit** [comment]
Raise issues about documentation here: https://github.com/darktable-org/dtdocs/issues/new/choose
Raise issues about website here: https://github.com/darktable-org/dtorg/issues/new/choose

Closing here since it's invalid place
