### ISSUE TITLE
Mask feathering: blocky artefacts

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#10090]
**To Reproduce**

1. Download
  - http://tech.kovacs-telekes.org/files/2021-09-26-darktable-mask-feathering/2021-09-12_10-17-50_P1060698.RW2 and http://tech.kovacs-telekes.org/files/2021-09-26-darktable-mask-feathering/2021-09-12_10-17-50_P1060698.RW2.xmp
  - or https://tech.kovacs-telekes.org/files/2021-09-26-darktable-mask-feathering/P1050166.RW2 and https://tech.kovacs-telekes.org/files/2021-09-26-darktable-mask-feathering/P1050166.RW2.xmp

2. Go to darkroom
3. Open step 20 is history (_diffuse or sharpen_ module, instance _sharpen strong_)
4. Display the mask
5. Use the scroll wheel to alter feathering radius
6. Blocky artefacts visible at several radius values

**Expected behavior**
No artefacts

**Screencast**
![mask](https://user-images.githubusercontent.com/3177739/134817011-223fb68d-dd18-4df7-bb37-afd7e23748b8.gif)

**Platform**

* darktable version : 3.7.0+1111~g2a83a6389
OS : Linux - kernel 5.11.0-31
Linux - Distro : Ubuntu 21.04
Memory : 64 GB
Graphics card : NVidia 1060/6GB
Graphics driver : 460.91.03-0ubuntu0.21.04.1
OpenCL installed : yes
OpenCL activated : YES and also when NO
Xorg : 1:7.7+22ubuntu1
Desktop : KDE 5.80.0-0ubuntu1
GTK+ : 3.24.25-1ubuntu4.1
gcc : 10.3.0
cflags : none
CMAKE_BUILD_TYPE : RelWithDebInfo

**Comment by jade-nl** [comment]
Did you link yo the correct image and/or sidecar?

![2021-09-11_18-51-05_P1060668](https://user-images.githubusercontent.com/56407344/134876977-73ee4c32-4be8-4c6e-a424-04450c71e524.png)

Doesn't look like your example above and it only has one mask which isn't part of step 20.

**Comment by kofa73** [comment]
Sorry. Uploaded the correct files and modified the links.

**Comment by jade-nl** [comment]
_Uploaded the correct files and modified the links._

I don't think so. Both link to your, Drupal, home page

Why not just drop the files right here instead of linking to an outside source. Much easier for us and instantly checkable by you.

**Comment by kofa73** [comment]
Fixed for good. I tried dragging-dropping them here, didn't work.

**Comment by jade-nl** [comment]
- I'm able to reproduce this with the provided RAW+sidecar.
- I'm not able to reproduce this with any other RAW. Also not when using the provided sidecar on another RAW.

> I tried dragging-dropping them here, didn't work.
Zip it (not you, the files).

**Comment by kofa73** [comment]
Still present with 3.9.0+17~gb66b27832 (but I understand it's almost impossible to reproduce, I've also never seen it with any of my other photos).

**Comment by kofa73** [comment]
I've added another sample (P1050166.RW2 and its sidecar), maybe it helps with the investigation.

![image](https://user-images.githubusercontent.com/3177739/147849592-627093b1-d812-4d56-9231-f0d024a46b2a.png)

**Comment by kofa73** [comment]
I've found that even if masking parameters are unchanged, disabling and re-enabling mask visibility alters the shown mask:
![image](https://user-images.githubusercontent.com/3177739/147849725-489d4c75-f12c-4779-9b68-5944d9cd30d1.png)
![image](https://user-images.githubusercontent.com/3177739/147849727-9a1fda3e-768d-4cb5-8215-6d1ebd1c117b.png)
