### ISSUE TITLE
rotation and perspective: remember auto-crop setting (or default to "largest area")

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10103]
I suspect most people will use the rotation/perspective module with similar settings each time. For example, I will probably want automatic cropping to always be set to "largest area". 

Could we set this to always default to the last user-chosen value, or to "largest area".

I believe auto-crop is set to "yes" by default in crop & rotate.

**Comment by AlicVB** [comment]
afaik, there's no way to "remember" last state for default module parameters. User need to use default presets for that... @TurboGit : can you confirm ?

In this case, effectively, if we want to micmic c&r default, we need to set the default crop to "largest area"

**Comment by elstoc** [comment]
You can set a config preference when the user manually chooses an auto-fit mechanism and then set the combobox using that saved value in the `reload_defaults()` function. Filmic rgb does something similar using the workflow preference.

I'm happy with either option though, but having to set the choosebox manually every time would be tiresome.
