### ISSUE TITLE
Color Zones can't create curve

### ISSUE THREAD

**Issue by xenonsailor** [darktable-org/darktable#10109]
**Introduction**
I cannot create a curve or pick a color using the eyedroppers in Color Zones - darktable 3.7 Windows 10 all releases so far.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
No, downloaded from github.

**Describe the bug/issue**
When trying to create a selection set in CZ with the sys droppers , say to increate saturation on a color range, no range is created.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
Open a DNG (or CR3 - I know this is still in development) file in darkroom
Select Color Zones
Select "create curve based on area" eyedropper
Select area in image
No result appears in the CZ pane.

**Expected behavior**
A range of color saturation or lightness is selected and highlighted in the CZ pane.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
Versions tested - 3.7.0+1144~g1500868f3 and previous Wondows build.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.7.0+1144~g1500868f3
* OS                : Win10 build 10.0.19041
* Memory            :  16GB
* Graphics card     :  nvidia nvs 5200m
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no** Current and previous Windows builds - see above.
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?  Yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? No

**Comment by Mark-64** [comment]
Confirmed in git master.
git bisect gives the following:
```
45484aba426178034e1ceec5ff324707d2524565 is the first bad commit
commit 45484aba426178034e1ceec5ff324707d2524565
Author: Dan Torop <dant@pnym.net>
Date:   Wed Aug 18 13:47:26 2021 -0400

    color picker: straighten out point/box picker proxy transitions
    
    Don't rely on primary colorpicker for any knowledge of anything except
    the current picker area (whether point or box). The colorpicker proxy
    is the one which remembers state of the area(s) associated with the
    current colorpicker widget.
    
    Side effect of this is that switching between point and box picker in
    an iop now remembers both pickers, rather than resetting the other
    picker. This should be an improvement.

 src/gui/color_picker_proxy.c | 51 ++++++++++++++++++++++++--------------------
 src/libs/colorpicker.c       |  1 -
 2 files changed, 28 insertions(+), 24 deletions(-)
```
@dtorop can you take a look?

**Comment by TurboGit** [comment]
I cannot reproduce with current master on GNU/Linux. Can you try again? TIA.

**Comment by TurboGit** [comment]
I can reproduce with current master on GNU/Linux.

**Comment by TurboGit** [comment]
@dtorop : Do you think you'll have time to look at this before the release? TIA.

**Comment by dtorop** [comment]
@TurboGit: Will take a look! Apologies for missing this, I've had too much day job work. Catching up now...
