### ISSUE TITLE
Filesystem timestamp not preserved when moving images with Darktable

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#10115]
**Describe the solution you'd like**
Preserve all timestamps when moving images with Darktable

Equivalent to: 
```
cp -a files
```

**Additional context**
Currently, the timestamp is not retained, which disrupts all cloud servers (as they will see the image as a "new" image, because they aren't using EXIF timestamp data)

e.g. Google Drive, OneDrive, Google Photos

**Comment by phweyland** [comment]
Same behavior with [copy & import]. Cannot check if [import from camera] preserves the file timestamp or not.

For these three types of copy I would vote to preserve the file timestamp (if possible of course). 

Any thoughts from others ?

**Comment by naisanzaa** [comment]
keep-alive.
