### ISSUE TITLE
[FR] Grid arrange with icon preview in darktable import window.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10110]
**Is your feature request related to a problem? Please describe.**
At this moment darktable can show all the files to import in list with the option of preview some in particular or all of them.
is it suitable to have a grid arrange with icon preview too in darktable import window?
The inconvenience of a list arrange is that there are a lot of images if the preview is off, but less images to show if preview is on. (images 1 & 2)

**Describe the solution you'd like**
A grid arrange with icon preview too in darktable import window.

**Additional context**
image 1
![Screenshot-20210928013422-1591x1141](https://user-images.githubusercontent.com/67672868/135036219-28878e88-1a4b-4b60-893b-f7fab76f2523.png)

image 2
![Screenshot-20210928024108-1590x1145](https://user-images.githubusercontent.com/67672868/135036246-1d3e444b-24ca-4886-8304-c7e1d6fef79c.png)

Mock up Proposal (theme: darktable-elegant-gray)
![importWindow_01](https://user-images.githubusercontent.com/67672868/135033344-aeada7e4-9aa1-4751-be70-de2a625e125a.png)

Mock up Proposal (theme: darktable-elegant-darker)
![importWindow_02](https://user-images.githubusercontent.com/67672868/135033364-9b4fd9bc-766f-4cdd-8fd7-500f7deca9c1.png)

**Comment by elstoc** [comment]
I don't use the previews myself but it seems like a good idea to me.

**Comment by Nilvus** [comment]
I like this idea too.

**Comment by wpferguson** [comment]
Depending on the number of images, and the hardware, that could take a while to populate...

**Comment by elstoc** [comment]
...It's no different to making all thumbnails visible in the current code.

**Comment by difrkaguilar** [comment]
Many times from the very moment of taking the photograph, I check and tentatively select from the camera (Fujifilm) with a star the possible photographs that I think may be the ones that I am going to develop later. But at the moment of importing them to darktable, it does not recognize this previous classification made with the camera in the import window, it only sees them after having imported all the photos. I don't know if with some LUA script I can add this previous reading so that if I have 50 photos already classified in camera, I don't have to import 700 and then select the 50 I want and delete the rest.

I think this functionality would be well received by a few users like me who make a previous selection in camera.

**Comment by difrkaguilar** [comment]
An update to this FR will com soon. I'm working in a mock up with some other features included.
