### ISSUE TITLE
GoPro 10: Failed to read camera white balance information

### ISSUE THREAD

**Issue by arbasel** [darktable-org/darktable#10112]
When I import my RAW photos from my GoPro 10 Black, they display as purple and a message appears saying 'Failed to read camera white balance information.

A sample file can be found here: [https://www.dropbox.com/s/i5rh6xlc4cnqr06/GOPR0004.GPR?dl=0](https://www.dropbox.com/s/i5rh6xlc4cnqr06/GOPR0004.GPR?dl=0)

**Comment by MStraeten** [comment]
see: https://github.com/darktable-org/darktable/wiki/Camera-support

**Comment by arbasel** [comment]
Thanks, I will work on this over the next two days.

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/10072
