### ISSUE TITLE
Canon Powershot SX530 HS DNG CHDK

### ISSUE THREAD

**Issue by GustavoBal** [darktable-org/darktable#10121]
Hola Informo que he cargado algunas Imagenes DNG para la Cámara Canon Powershot Sx530, generadas a través de CHDK. Esta cámara no se encuentra en la lista de cámaras para corrección de Lente en Darktable. Existen modelos similares como la SX510 o la SX50 pero no corresponden exactamente a lente de dicho modelo

**Comment by kmilos** [comment]
Should be working since dt 4.4
