### ISSUE TITLE
Sony A1 lossless ARW cannot be opened in Darkroom of DT-3.6.0.1, though lightroom is presented.

### ISSUE THREAD

**Issue by nk8020** [darktable-org/darktable#10124]
My Issue (trouble I cannot resolve),

Sony A1 lossless ARW cannot be opened in Darkroom of DT-3.6.0.1, though Lightroom is presented.
It says that the files are damaged, but I recently "culled" them in CaptureOneExpress, so I can post-produce the remaining ones with DT.

Updating the DT versiob to the current (3.6.0.1) did not seem to help.

The files are ~ 65MB on average, and I don't know if this is a factor, or how to overcome it.

Any help will be much appreciated.

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/8523
