### ISSUE TITLE
Enhanced dehazing algorithm (with new code)

### ISSUE THREAD

**Issue by weltyj** [darktable-org/darktable#10127]
First I'll pre-apologize for not being GIT trained enough to do this myself.

I have a little write up of an enhanced version of the haze removal tool (attached).

I simply overwrote the previous src/iop/hazeremoval.c with my changes, which is attached.  But I think you'd want a whole new module name if you think it's worthy and I have no idea how to do it.   I don't have opencl versions of the algorithm, and am probably not the person to attempt it.

I've been using this over a year now and am pretty happy with it, but it is in need of some help from someone who knows darktable coding protocols well (which is not me).

I'll be happy to help in any way my skill set will allow :-D

Cheers,
Jeff Welty
[An updated algorithm for haze removal.pdf](https://github.com/darktable-org/darktable/files/7261734/An.updated.algorithm.for.haze.removal.pdf)

[hazeremoval.c.txt](https://github.com/darktable-org/darktable/files/7312329/hazeremoval.c.txt)
[MoreDehazeExamples.pdf](https://github.com/darktable-org/darktable/files/7312332/MoreDehazeExamples.pdf)
[Screenshots_ehanced_module.pdf](https://github.com/darktable-org/darktable/files/7312333/Screenshots_ehanced_module.pdf)

**Comment by TurboGit** [comment]
Can you post some screenshots of the difference on real pictures with current module ?

**Comment by weltyj** [comment]
I'll get some screenshots.   It's a little tricky for me because all my .xmp's now have more parameters for haze removal, and darktable will detect the change of parameter count and reset parameters for haze removal in my .xmp's even in lighttable mode as I recall.   But I think I can just create a new linux account, recompile for the current module and run a few images there so my current account darktable database won't get altered and there will be copies of the .xmp's in the new account.   The example in the PDF does use the old algorithm for determining haze color (I just modified the code for that one shot and did a quick recompile and did the screen capture.).
