### ISSUE TITLE
Noise profile for Leica M10

### ISSUE THREAD

**Issue by mathiasuk** [darktable-org/darktable#10122]
Noise profile for Leica M10 over the entire range of ISO 100-50000. I had some issues with the script complaining that the images where not overexposed, even though they were in all channels as far as I can tell. But I got it to work in the end.

[darktable-noiseprofile-20210929.tar.gz](https://github.com/darktable-org/darktable/files/7255353/darktable-noiseprofile-20210929.tar.gz)

Example thumbnail
![L1008611-thumb](https://user-images.githubusercontent.com/818222/135356428-0651a3a1-6a70-438f-bd66-1afbc1df0bab.jpg)
:

**Comment by Nilvus** [comment]
@rawfiner: should be for you!

**Comment by TurboGit** [comment]
The name will need to be updated with next rawspeed update.

**Comment by TurboGit** [comment]
This has been fixed/merged. Closing.
