### ISSUE TITLE
Tags get attached to seemingly random non-selected photos

### ISSUE THREAD

**Issue by peltsippi** [darktable-org/darktable#10120]
I am having weird issue with tags being attached to extra photos.

Windows 10, version 3.6.0

Steps: 

1. Deselect all images (UI says 0 images of xx selected)
2. Create new tag
3. Tag has now ~10-1000 photos assigned to it

or

1. Select single image (UI says 1 images of xx selected)
2. Create new tag
3. Tag has now ~10-1000 photos assigned to it

Created 5 tags, first had 105 photos, second 47, third 446, 4th 3 and 5th 17 photos. There might be some relation through film roll.

No difference in functionality if used from right side of the screen or with ctrl + T.

First I thought there were some issues with my selections and I've just accidentally tagged 10000 photos with a tag but repeating the steps seem to be pretty repeatable for me.

**Comment by peltsippi** [comment]
Tested further and it seems, that tag is added to selected photo plus to completely random film roll and there is no link through dates, filenames nor tags.

**Comment by phweyland** [comment]
I cannot reproduce this with the current master.
If you start with a clean database, do you still have the issue ?

**Comment by peltsippi** [comment]
Tested with new database and imported limited amount of photos. No issue. I'll try to reimport all photos to empty database bit later and test if I can repeat this or is the database just corrupted somehow or similar.

**Comment by peltsippi** [comment]
It seems, that tags are also added to some sidecar files (I have _write sidecar file for each image_ enabled).

> Created 5 tags, first had 105 photos, second 47, third 446, 4th 3 and 5th 17 photos. There might be some relation through film roll.

With sidecar file metadata imported to empty database stats are following: 
1: 1 photo , 2: 22 photos , 3: 34 photos , 4: 3 photos , 5: 6 photos. 4th is the one that matches.


But starting from fresh, >25 000 dngs imported and now everything seems to tag normally. If nothing is selected, nothing is tagged and only selected photos get tagged. So I'll close this bug now because issue is resolved completely.

I'll keep the old database file just in case, feel free to request it if similar issues resurface later on and it could be useful.

**Comment by peltsippi** [comment]
This occurred again and I figured out one probable mechanism:

OneDrive sync seems to affect xmp file writing and xmp files fall out of sync compared to database but database tags are being written ok. This is only my speculation. And something involving this makes tags jump to photos not intended to, both with xmps and in database but with different scope.

Starting with empty catalog over again and importin photos using xmps ends up with less miss-tagged photos. Now I am testing with pausing OneDrive sync during any operations involving large amount of xmps and similar. For now all seems to work well.
