### ISSUE TITLE
Please add Lensfun directory to global preferences

### ISSUE THREAD

**Issue by andre-fuchs** [darktable-org/darktable#10143]
**I cannot get custom Lensfun profiles working with both the Flatpak and binary packages**
I was following multiple guides how to get the complete Lensfun library working with darktable. I am using darktable 3.6 on Pop!_OS 21.04 (Ubuntu). The lensfun library is placed in `~/.local/share/lensfun/`. I tried all possible locations for the .xml profiles like the mentioned directory and its subdirctories like `update/` and `update/version_1/`. This should work for the binary packages of darktable at least. But I cannot get these profiles to show up in the lens correction module.

**The solution I'd like: A custom lens profile directory setting**
How about choosing a custom directory for custom lens profiles via the preferences? This would work with all kinds of installations, either binary or Flatpak. Parsing a bunch of .xml profiles on startup should not slow down darktable significantly. Or just put them in the database and add an "Update" button, like Davinci Resolve does with their LUTs directory setting.

**Alternatives**
In addition the manual could see an update on this issue. I guess many people are missing lens profiles for less common lenses and would be consulting the manual. With the directory setting above, this section of the manual could be simplified to a line of text. I would also appreciate a slider in this module for basic geometric distortion correction.

**Context**
If the current behavior via the system wide Lensfun installation/library is based on the desire to motivate people to contribute to this library, I guess that a more direct/transparent setup described above would possible motivate people even more, because of the ease of use.
I really like these Flatpak installations, to be honest. From what I have read, you cannot update the lens correction profiles at all for the darktable Flatpak. The proposed directory setting would solve this for all kinds of systems/set-ups.

**Comment by wpferguson** [comment]
darktable doesn't read the lens correction database files, it calls lensfun to do that and gets the information from lensfun.

**Comment by andre-fuchs** [comment]
How can I debug this if it doesn’t work on my machines? Lensfun works. I used the `lensfun-update-data` command successfully.

**Comment by wpferguson** [comment]
Let's address Flatpaks first.  They run in a sandbox isolated from the system.  Unless the flatpak is built with lensfun included, you won't have lensfun.

Now for the binary version of darktable.  What lense and what camera?  Can you manually select the lense in the lens correction module?  Is the lens supported by lensfun?

**Comment by andre-fuchs** [comment]
I am using a SMC PENTAX-K 28mm f/3.5 lens on a Sony A7III body. 
I just discovered that I have to change the camera first, to see more lenses! If I select a Pentax K camera I can select the Pentax lenses as well – including a "smc Pentax-M 28mm 1:3.5", which fits ok (still some pincushion distortion at the sides). With the Sony A7III I only see two Takumar lenses in the Pentax category only. I think this solves it for now. I will try to create my own profile which is more accurate.
