### ISSUE TITLE
Dji mini 2

### ISSUE THREAD

**Issue by fran6t** [darktable-org/darktable#10149]
Hello
I sent a raw file to the raw.pixls.us site named DJI_0765.DNG at the end it is asked to open an issue for the taking into account

Capteur is CMOS 1/2,3" Pixels effective : 12 MP
Objective :
FOV : 83°
Format équivalent  35 mm : 24 mm
Aperture : f/2,8
Focus : 1 m to ∞

ISO
100-3200 (Auto)
100-3200 (Manuel) 

I am at your disposal if you need other information or other things to do
cordially

![DJI_0765](https://user-images.githubusercontent.com/4406087/135765826-950ed840-b8c1-4e3e-9707-21ad38507e16.JPG)

**Comment by kmilos** [comment]
Duplicate, see #9566 and #9941

**Comment by Nilvus** [comment]
As it seems that it is already supported and fixed, see link by @kmilos, I close this issue. You could add more infos or what is missing after reading 2 links posted by @kmilos if something remaining. Thanks.
