### ISSUE TITLE
some option keep with the white circle even if reset to default value

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10141]
master

Preferences -> processing: the white circle that indicates a changed preference is not reset when you double-click the following option
- 3D lut root folder
- memory in megabyte to use for thumbnail cache

**Comment by Nilvus** [comment]
I don't use 3D lut root folder but tested in memory option and I can reproduce on master. I supposed you use master too as you don't precise darktable version.

**Comment by Mark-64** [comment]
For 3D LUT root folder, I stumbled upon the same issue when developing #9991, default value cannot be an empty string for a path, must use a special value.
@Nilvus You can assign this issue to me
