### ISSUE TITLE
Input NG: Always default to preferred instance

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10148]
The behaviour of the visual shortcut mapping seems to differ based on whether there are multiple instances of a module.

- If there's only one instance, the shortcut is applied to the "preferred" instance
- If there are multiple instance, the shortcut seems to be applied to the first instance if I point to the first instance, the second if I point to the second, and the "preferred" if I point to the last

IMO this is not desirable behaviour. Shortcuts should always be applied to the preferred instance by default and the user should have to go into the "advanced" shortcuts window to change that. I don't personally see a use case for applying shortcuts to specific numbered instances but I suspect if it is used it's much more rarely needed than the "preferred" one.

Edit: looking at the code it seems to be setting it to the preferred instance if the one I assign it to happens to be the currently-preferred instance, and to a specific instance number otherwise. Either way I'd prefer it not to do this.

**Comment by ptilopteri** [comment]
I strongly agree

**Comment by TurboGit** [comment]
I tend to agree with that too. @dterrahe : Is that ok with you too?
