### ISSUE TITLE
[exiv2 read_exif_tag] Invalid key `Exif.NikonLd4.LensID'

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#10157]
**Describe the bug/issue**

importing images, [import from camera] from my mobile phone, dng and jpg, I get the following console message for each of them:
`[exiv2 read_exif_tag] Invalid key 'Exif.NikonLd4.LensID'`

Debian sid
Current master.

**Comment by kmilos** [comment]
Harmless warning due to older exiv2 version... If this is really annoying, we could [guard it by testing for exiv2 >= 0.27.4](https://github.com/darktable-org/darktable/blob/a422bfd966af56a15c5fe0b8304dca94abad4977/src/common/exif.cc#L1059)

**Comment by kmilos** [comment]
Ah, precedence problem that was there all along :/

**Comment by phweyland** [comment]
> Harmless warning due to older exiv2 version... If this is really annoying, we could guard it by testing for exiv2 >= 0.27.4

You are right, this seems to be the right thing to do (like in or together with line 1194)

**Comment by kmilos** [comment]
I actually found quite a few places where the parenthesis were leading to wrong associativity and precedence!

**Comment by phweyland** [comment]
> I actually found quite a few places where the parenthesis were leading to wrong associativity and precedence!

OK. Will that work also for exiv2 0.27.3 ?

**Comment by kmilos** [comment]
No, actually, I got that wrong... :( I'll create the fix w/ guard...
