### ISSUE TITLE
[Enhancement] Map: do not download tiles not needed any more

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10150]
I have a **slow connection**, and I'm suggesting a feature/enhancement for a situation which affects heavily my user experience.

On the map, if I raise rapidly the zoom level, e.g. from 5 to 9, darktable subsequently downloads all the needed tiles for zoom 6, then all those for zoom 7, then those for zoom 8, then those for zoom 9.

I'd say that the same thing happens when downsizining the zoom level, and when moving the map.

A big amount of data is downloaded without a real need.

My proposal is: if the zoom level changes while downloading a set of tiles, cancel the download of the zoom level not any more needed.

More generally: _If a tile isn't needed any more, for changing the zoom level or for remaining outside the visible map window, stop downloading it._

**Comment by phweyland** [comment]
If I'm not mistaken that's open-gps-map which manages the tiles cache.

**Comment by johnny-bit** [comment]
The downloading is managed by https://github.com/nzjrs/osm-gps-map/ internally so fix should go there (as well as issue report).

**Comment by paolobenve** [comment]
opened https://github.com/nzjrs/osm-gps-map/issues/90

**Comment by johnny-bit** [comment]
Thanks!
