### ISSUE TITLE
Crash in _lib_histogram_process_waveform due munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by wgoetz** [darktable-org/darktable#10160]
``
gdb session:
break _lib_histogram_process_waveform
run
(in darkroom: select waveform) 
next (until line 219)
... (histogram.c line 212 setting of num_tones = ... is not present in binary!
print num_tones: <optimized out>  and d->waveform_tones: 160
``
[dt-waveform-crash.txt](https://github.com/darktable-org/darktable/files/7278968/dt-waveform-crash.txt)

release-3.7.0-1211-ga422bfd96 with unchanged build.sh

``
gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.3.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-S4I5Pr/gcc-10-10.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-S4I5Pr/gcc-10-10.3.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04) 
``

looks like an optimizer bug. num_tones is used several times inside this function and should not vanish

**Comment by ralfbrown** [comment]
<optimized out> means it's either stored in a register whose lifetime does not extend to the crash location or rolled into some other computation.  It does not by itself indicate an optimizer bug.

**Comment by wgoetz** [comment]
thx.. i renamed the Issue 
oh yes.. debugging optimized programs.. #-)

what i have tried:
- crash using gcc 10 and 9 in default build
- no crash in Debug build!

- crashline: histogram.c 291 dt_free_align(partial_binned);

``
munmap_chunk(): invalid pointer
--Type <RET> for more, q to quit, c to continue without paging--

Thread 11 "worker res 1" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffc7fff700 (LWP 8025)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) set pagination off
(gdb) set logging file gdb.txt
(gdb) set logging on
Copying output to gdb.txt.
Copying debug output to gdb.txt.
(gdb) thread apply all bt full
``

[gdb.txt](https://github.com/darktable-org/darktable/files/7291482/gdb.txt)
.
