### ISSUE TITLE
ENHANCEMENT: reduce mouse actions for changing options in modules

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10166]
When I use darktable I'm quite annoyed when I have to change a module option with two values, e.g. in perspective correction module: guides on/off, lens model generic/specific. The annoying issue is that, for changing from _on_ to _off_ I must:

- click on the _on_ option
- move down the cursor to the _off_ one
- click on _off_ option

It often becomes even more annoying when, because of hurry or  tiredness, the mouse moves too little or too much, and so the option isn't changed and more clicks are needed.

I understand that the reason why a binary option isn't implemented as an on/off little cursor, or as a checkbox, is for sake of _consistency_ with options carrying 3 or more values. And that could be correct, beauty is important too.

However, I'm proposing a solution which improves usability without sacrifying beauty:

**Add a little button after the option meny, which, when clicked, changes the option to the next value**. The extra button could have the symbol of a forward arrow, or anything else.

The user still would have the possibility to open the menu, if he/she prefer, but the expert user could much more easily change a binary and even a ternary or quaternary option which he/she knows well, simply with one ore more clicks to the same button.

**Comment by AlicVB** [comment]
we can't really add an icon next to the combobox, because some combobox already use this place for a specific button.

Maybe what can be done is that for 2 states combobox, a click on the label directly switch to the other value, while a click on the value show regular submenu. For multiple states combobox, we would keep the actual behavior.

**Comment by paolobenve** [comment]
> Maybe what can be done is that for 2 states combobox, a click on the label directly switch to the other value, while a click on the value show regular submenu.

That seems good to me!

> For multiple states combobox, we would keep the actual behavior.

The click on the label could change to the next value, going back to the first when on the last. This way it would be perfect!

**Comment by TurboGit** [comment]
> Maybe what can be done is that for 2 states combobox, a click on the label directly switch to the other value, while a click on the value show regular submenu. For multiple states combobox, we would keep the actual behavior.

Using a simple mouse scroll on the combo also change the values. Isn't that sufficient ?

**Comment by paolobenve** [comment]
> Using a simple mouse scroll on the combo also change the values. Isn't that sufficient ?

only if I don't use the mouse wheel to scroll the modules side panel.

When that option is _on_ another way is needed.

**Comment by paolobenve** [comment]
> Hold Alt while scrolling

Thank you for pointing this out.

Ctl-scroll is even better, because on my linux desktop alt-scroll enlarges the screen

**Comment by paolobenve** [comment]
.... although I find that having to put the other hand on the keyboard to hold ctrl or alt when I'm using the mouse obliges me to put my eyes on the keyboard, and that reduces easyness of work.

On the contrary, if everything could be done only with the mouse it would be much better in terms of user experience.
