### ISSUE TITLE
Improve XMP/DB conflict resolution window

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#10164]
When the "check updated XMP at start-up" option is enabled, a window pops up with list of conflicting editing histories between DB and XMP. 

What it does :
1. Show both timestamps,
1. Allow to sync DB -> XMP or XMP -> DB.

Missing features to make it workable :

1. ability to select a range of files (with the usual Shift + Click) – right now you need to click on each and every file one by one,
2. ability to select all files from a particular directory in a single step,
2. ability to sync older -> newer and newer -> older (we have the timestamps), regardless of which one is XMP or DB.

Missing features to make it great : 

1. show a diff,
2. ability to merge individually conflicting modules.

**Comment by phweyland** [comment]
related to #9748. NAS repository accessed from different machines.
In particular the case where some duplicates' xmp (but not all) have changed or disappeared.
