### ISSUE TITLE
I would like to see the color zones module be updated and adapted to work as part of the scene-referred work flow

### ISSUE THREAD

**Issue by Matty6868** [darktable-org/darktable#10179]
**Is your feature request related to a problem? Please describe.**

The color zones module  does not show up as part of the scene referred work flow group. I assume this is for good reason given that after going through the modules masking system and a few other things, I realized that they did not match the other scene referred modules and the code appears to be slightly antiquated.  With the understanding that Darktable tends to be moving in the direction of scene referred work flow, as an infrared photographer, I am hopeful that a version of this module will be made in the correct color space as I use it for many of my infrared tweeks.

**Describe the solution you'd like**

I would like the current color zone module to be maintained for those who prefer the display referred work flow but I would like a new version to be developed that is specifically designed for a scene referred work flow.

**Alternatives**

One universal module that does both

**Additional context**

**Comment by elstoc** [comment]
The recommendation for a scene-referred workflow is that you use the color balance rgb module with parametric masks to select pixels by hue/saturation/lightness.

**Comment by ramestica** [comment]
I very much support the request proposed here.

After installing 3.6.1, for some of my photos it just takes to enable the color zones module (at default values) to produce artifacts on the image. Artifacts that are real in the sense that after exporting to tiff, they are certainly there.

I have also had mixed results trying to use the color balance module to reproduce what I would have quickly done with color zones. My personal appreciation here is that as important as the algorithm within the module, usability is at the same level of importance.

It is discouraging to assume that with every new release of darktable one should be prepared to change one's  own workflow. Design decision should take this into account. I say this with a positive stance and from behind my high appreciation for the development effort of many around the darktable software.

**Comment by Matty6868** [comment]
this is a big issue for me

**Comment by halojenproductions** [comment]
I am in the same boat here. Also an IR photographer which means that Colour Zones is the most important module to me.
Unfortunately Colour Balance Rgb + masks doesn't come close to replicating what Colour Zones does (at least not for how I use it). 
The histogram+curve arrangement of Colour Zones is very powerful so I'm surprised there don't appear to be plans to bring it into the scene-referred realm despite us IR photographers being in the minority of users.

**Comment by Matty6868** [comment]
yah I agree this is a critical module for visible photography too
especially for creating fx or even analyzing certain data like false color
sem images
in addition there are lots of instances especially up north were days are
cloudy and color cast is horrible that it easily fixes
and if your interested in surrealism it can be a vital tool
also if you do photography as pure art  sometimes you want to change the
color of things in the scene to reflect your artistic vision and build
unearthly worlds of vibrant colors
i know i love to use this method on macro photos a lot
as well as photos of rocks and minerals
