### ISSUE TITLE
Make Lighttable view filterable by file type

### ISSUE THREAD

**Issue by mame98** [darktable-org/darktable#10172]
**Is your feature request related to a problem? Please describe.**

Most of the time, I import both, the RAW and JPEG version of images into Darktable. However, when reviewing/categorizing them I usually just look at the RAW files but keep the JPEGs as reference. The issue is that now, I always see two identical images next to each other and I have to make sure to only tag/rate the RAW image.

**Describe the solution you'd like**

A simple dropdown, similar to the star-rating filter on top of the Lighttable view that should list all file Types and all all Option:

```
All
-------
RW2
JPEG
...
```

**Comment by dterrahe** [comment]
This was also implemented in the collection filters
![image](https://user-images.githubusercontent.com/1549490/200188831-1a40120d-efb1-474f-a66b-6976a3416792.png)
