### ISSUE TITLE
Can't start darktable

### ISSUE THREAD

**Issue by eoskari** [darktable-org/darktable#10184]
**Describe the bug/issue**
I can't start Darktable on my computer (Windows 10 Pro, v. 21H1).
When I try to open the application, I get an error message saying an "unhandled exception occured" and that there will be written a backtrace to a folder on my computer. However, I cannot find this bactrace file, in fact the folder path doesnt excist.
I have tried to uninstall and reinstall darktable, but the same issue persists.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Start Darktable

**Screenshots**
![image](https://user-images.githubusercontent.com/92247390/136688064-f5f3e1ac-4371-4858-9204-bb7d5aadd9df.png)

**Platform**

* darktable version : 3.6.1-win64
* OS                : Win10 Pro (10.0.19043) (21H1), 64-bit
* Memory            : 8 GB RAM
* Graphics card     : Intel HD Graphics 520 (1GB RAM)
* Graphics driver   : 26.20.100.7812
* OpenCL installed  : unknown
* OpenCL activated  : onknown
* Xorg              : unknown
* Desktop           : unknown
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Comment by Mark-64** [comment]
Very strange that path folder does not exist, are you sure?
Please note that AppData in your user folder is hidden by default, you have to set an option in windows explorer menu to show it:

![immagine](https://user-images.githubusercontent.com/43290988/136691593-4f709f93-8147-4b8f-b850-d6dc36caf507.png)

**Comment by eoskari** [comment]
Thanks! I was able to open darktable using command "start darktable.exe --disable-opencl" in cmd, but do I need to open darktable that way every time? Or is it possible to disable OpenCL as a default, so that I can open it as usual? (Maybe a workaround could be to make a shortcut for that exact command prompt...)?

**Comment by Nilvus** [comment]
I you could disable opencl in darktable main preferences, process tab.

You could also add --disable-opencl in darktable shortcut properties. Right-click in shortcut you use to launch darktable then properties. In dialog window opening, search where darktable.exe is prompted.

**Comment by eoskari** [comment]
Thanks, Nilvus, I'm learning a lot today!

The shortcut-trick worked, so I'm good.
However, if you need for any future reference, it's not possible to change OpenCL-preferences within darktable. Process-tab doesnt say anything about OpenCL, and the otions in cpu/memory-tab are "not available" as shown in this screenshot: 
![image](https://user-images.githubusercontent.com/92247390/136712769-5c4511f1-f191-485e-8488-03d0c4dea7ae.png)

Anyway, big thanks for very quick and great help!
