### ISSUE TITLE
color blindness makes it difficult to rate images in Darktable

### ISSUE THREAD

**Issue by 4e868df3** [darktable-org/darktable#10187]
I suffer from red-green color blindness. Usually it is very subtle, so when it does limit me, it can be very annoying.

Darktable's rating system is one of those things. Photos can be starred 1-5, and the good contrast in these stars are easy to work with. However, there is an additional rating, "X" (or "mark for deletion"). When toggled on, the X in darktable's UI is colored red. When toggled off, the X is colored black. This effect can be observed in both lighttable and darkroom views.

I struggle to see when that X is red or black. At first I thought that the software was broken each time I marked an image for deletion, because I didn't notice that the X turned color. I can see that subtle red only when looking closely.

Red-green is the most common form of color blindness, and it affects 1 in 12 men, suggesting that I am not the only darktable user affected by this. A subtle or simple change to the default UI would be very helpful. More contrast, or bolding- there is room for creativity on how it is implemented.

I actually like the current design, but I can't see it.

**Comment by AlicVB** [comment]
I have a good news for you : the color can be changed very easily with css :)
in the css window located in the preference, "just" add something like : 
```
/* Set red reject icon when visible */
.dt_overlays_hover #thumb_main:hover #thumb_reject:active,
.dt_overlays_hover_extended #thumb_main:hover #thumb_reject:active,
.dt_overlays_always #thumb_reject:active,
.dt_overlays_always #thumb_main:hover #thumb_reject:active,
.dt_overlays_always #thumb_main:selected #thumb_reject:active,
.dt_overlays_always_extended #thumb_reject:active,
.dt_overlays_always_extended #thumb_main:hover #thumb_reject:active,
.dt_overlays_always_extended #thumb_main:selected #thumb_reject:active,
.dt_overlays_mixed #thumb_reject:active,
.dt_overlays_mixed #thumb_main:hover #thumb_reject:active,
.dt_overlays_mixed #thumb_main:selected #thumb_reject:active,
.dt_overlays_hover_block #thumb_image:hover #thumb_reject:active
{
  color: rgb(0,0,255);
}
```
adjust `rgb(0,0,255)` to your needs...
you can also create a new theme if you prefer

think about closing the issue if it solve it for you. Thanks !

**Comment by 4e868df3** [comment]
Thanks, that got the job done.
