### ISSUE TITLE
floating pallets/menus

### ISSUE THREAD

**Issue by joneween** [darktable-org/darktable#10185]
Hi there,
I’m new to the forum and to Darktable, but loving both. 

I was wondering if there are any efforts being made to create unyoked, floating pallets/menus? this would be very helpful on multiscreen rigs like mine where one could use one full screen for the image and put the pallets/menus on another.

cheers

jon

**Comment by quovadit** [comment]
There is an option to show a second darkroom window ![image](https://user-images.githubusercontent.com/5677563/136702141-06d7a637-df3f-4665-8780-684463748aad.png) at the bottom left.

**Comment by joneween** [comment]
Hey, thx for the info. Second window doesn't really do it since you cannot manipulate on it. So you are still stuck with the one window to work in and not optimizing the image workspace on a second monitor. Oh, well, I understand the coding issues with implementation, but figured I'd ask. Still a great tool! Cheers
