### ISSUE TITLE
iPhone 13 Pro

### ISSUE THREAD

**Issue by bicknrown** [darktable-org/darktable#10203]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

Raw photos from every camera element have been uploaded.

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by kmilos** [comment]
Probably duplicate of https://github.com/darktable-org/darktable/issues/7578

**Comment by bicknrown** [comment]
gotcha, it doesn't *seem* like apple changed anything for the 13's, their website is still showing 12's as the Pro RAW example.

Because that thread has not had traction in a while, ill leave it up to someone with more authority on the issue than i to close this if they think its more of a hinderance than a help.

if i'm missing something in what you said about a potential fix, please do let me know.

**Comment by Wlanfr3ak** [comment]
I have uploaded 9 examples from the iPhone 13 Pro with all 3 Lens and Dimensions today.

**Comment by mdegans** [comment]
I have uploaded some samples and a photo of a color target as well. Seems something has changed if iPhone 12 "ProRaw" is supposed to be supported.

I'm using the snap version of Darktable (`darktable 3.2.1`) and it says "please check image (use exiv2 or exiftool) for corrupted data." The image previews fine in "lighttable" but not in the "darkroom"

**Comment by teenjuna** [comment]
Hi @bicknrown! Is there something that can be done here? I'm using `3.8.1` and it still can't open `.DNG`s produced by 13 Pro. I would like to help with samples, but it looks like people have already uploaded some.

**Comment by kmilos** [comment]
You can try to test [this temporary rawspeed patch](https://discuss.pixls.us/t/support-for-apple-proraw-dng/28400/12?u=kmilos).

**Comment by teenjuna** [comment]
Can you please give instructions on how to do this?

**Comment by kmilos** [comment]
Here's the high level directions:

1. Clone the darktable source (e.g. 3.8.1 tag)
2. Patch src/external/rawspeed according to that pull request (you can even [create a patch file from it](https://patch-diff.githubusercontent.com/raw/darktable-org/rawspeed/pull/334.diff))
3. Build

**Comment by dssrtfx** [comment]
If there has been no movement on this, I am willing to help finish up iPhone 13 Pro DNG support. Does the aforementioned patch from kmilos still need to be tested, do more samples need to be uploaded, etc.?

**Comment by Subnet-Masked** [comment]
Just chiming in that this is the error received when opening a DNG from my iPhone 13 Pro:
`virtual void rawspeed::LJpegDecompressor::decodeScan(), line 96: Unsupported predictor mode: 7`
