### ISSUE TITLE
Multi-resolution export

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#10204]
When you need the same image at different resolutions, as of now, you need to manually re-export the image at each resolution, meaning recomputing a full pipeline for each resolution. 

It would me more efficient to compute only the max resolution or full resolution pipeline (depending on settings), then downsample for each of the smaller resolutions from the same high-res image buffer.

**Comment by clavinet** [comment]
Great suggestion, I was just about to post something similar.

I mostly use two export presets - one high quality PNG for archival, one lower quality and lower resolution JPEG for web.
It would save a lot of time if you could export both at the same time.

**Comment by AyushGupta10** [comment]
What if we can have something similar to what ON1 Photo RAW 2022 does.
We can already create a presets for exports, the missing functionality is to be able to select multiple presets during export.

This [video](https://www.youtube.com/watch?v=xcWqI_iiF7Q) shows ON1's implementation in action.

Not saying we should copy their features or UI. But I think having some way to select presets for exports and computing the pipeline once would be awesome.

**Comment by mdrmike** [comment]
If implementing this, it'd also be great to be able to "slice" to create "tiles" (or cut, or crop .. whatever the proper verbiage).  

For example, slicing is useful for automatically cropping into thirds or ninths for multiple instagram/blog/social media posts... etc
