### ISSUE TITLE
Crawler doesn't work on Windows

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#10212]
Hello

Crawler doesn't work on Windows because _dt_util_normalize_path_ returns **utf8** but **not locale** encoding.

When I replace 
` 	  gchar *xmp_path_locale = dt_util_normalize_path(xmp_path);
`
with 
`	  gchar *xmp_path_locale = g_locale_from_utf8(xmp_path, -1, NULL, NULL, NULL);
`
 it works fine.

Darktable Version: master
OS: Windows 7

**Comment by johnny-bit** [comment]
I'm out of loop due to barely having time to think about anything. No need to ping anybody, just file a normal issue, maybe tag with windows support tag etc.

But I think it used to work and got working well in current master due to windows insider program...
