### ISSUE TITLE
Unable to use styles with darktable-cli on Linux

### ISSUE THREAD

**Issue by trouaux** [darktable-org/darktable#10229]
**Introduction**

I have been trying to convert some .CR2 files from the darktable-cli on Linux, I read we can provide custom styles when running the command.
First I tried on Windows and everything worked as expected. But when moving to linux, I copied my styles to the correct path but it looks like darktable is unable to find them

---------------------------------------------------------------

**Describe the bug/issue**
[imageio_storage_disk] error

**To Reproduce**
On Ubuntu 20.04 try execution darktable-cli while specifying a style for the conversion

you can beforehand open darktable UI and create a random style

darktable-cli input.CR2 output.jpg --style style --style-overwrite

**Expected behavior**
conversion successful, file is present 

**Platform**

* darktable version : 3.6.1
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04

**Additional context**
Here is some of the debug output maybe it can help
```
0.690531 [sql] /darktable-3.6.1/src/common/styles.c:1545, function dt_styles_get_id_by_name(): prepare "SELECT id FROM data.styles WHERE name=?1 ORDER BY id DESC LIMIT 1"
[imageio_storage_disk] could not export to file: `o_01.jpg'!
0.701305 [pwstorage_new] Destroying context 0x555a02200290
```

**Comment by agusit7** [comment]
Is there a way to import the styles through the command line?
