### ISSUE TITLE
[FR] Paint brush mask quick menu.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10228]
**Is your feature request related to a problem? Please describe.**
Sometimes when I am creating a mask with the brush I would like to have access to a quick menu where I can modify the brush values without having to constantly press Ctrl, Shift and scroll.

In this quick menu I'll like to have several options like sizing the brush, changing hardness and transparency, as well as viewing, inverting the mask I'm creating, keeping the handles visible and saving the brush parameters as default for later use.

**Describe the solution you'd like**
This is a proposal to use a floating menu to modify the values of the paint brush mask, although I know that some developers don't like floating menus very much.

Using the right click with the mouse a menu would appear where users can modify the brush values, activate the mask display, invert the mask, keep the mask handles visible and if desired, save the brush with these values as default for later use. This would be another way besides using Ctrl or Shift and scroll.

**Alternatives**
Another option could be that when activating the brush, both in the modules and in the mask manager, below the mask manager, this menu is created with these options.

I leave this proposal for your consideration.

**Additional context**

Floating menu with right click.
![Brush_settings_00](https://user-images.githubusercontent.com/67672868/137812439-6bd68027-44b2-4eda-8a77-c57e790d98d1.png)

Other option with menu below the mask manager.
![Brush_settings_00a](https://user-images.githubusercontent.com/67672868/137812566-1f00c9fd-607d-49dc-bc48-3099dfcdb00e.png)

Option with active icons of view handles, invert and display mask.
![Brush_settings_00b](https://user-images.githubusercontent.com/67672868/137926552-8c8e4877-12cc-467a-8ee4-78bf3ea62dc8.png)

Theme darktable-icons-darker.
![Brush_settings_01](https://user-images.githubusercontent.com/67672868/137812688-5a77590a-250a-4604-b406-40aa614aceb5.png)

Theme darktable-elegant-grey.
![Brush_settings_02](https://user-images.githubusercontent.com/67672868/137812709-1cc4ec9c-1fb2-4dd7-adc7-7580b8ad3fe3.png)

Floating menu.
![Brush_settings_03](https://user-images.githubusercontent.com/67672868/137812728-b3c5cfc7-b5d1-43ca-ac8a-0c1356858571.png)

**Comment by difrkaguilar** [comment]
> fyi, @aurelienpierre has the project to implement a drawn masks toolbar which should address this FR. I've already done some core work to make this possible, but as always, days only contains 24 hours...

Yes I saw some similar request in the #6622 and the add masks toolbar #9015 of @aurelienpierre

**Comment by elstoc** [comment]
> But anyway to remove the masks (shapes) can be done using the "Del" key of the keyboard created long time ago and always known by the users.

Can it? The only way I can see to permanently delete a shape is to right-click on the shape in the mask manager and delete it from the menu.

**Comment by TurboGit** [comment]
> But anyway to remove the masks (shapes) can be done using the "Del" key of the keyboard created long time ago and always known by the users.

Some kind of Lr reminiscence :) ?

**Comment by difrkaguilar** [comment]
> I would prefer not to have a popup that overlays the image as it could interfere with visibility of the mask. Controls in one of the existing panels (in addition to the existing shortcuts) would be ok.

> Another option could be that when activating the brush, both in the modules and in the mask manager, below the mask manager this menu is created with these options.

That's why I put an alternative design with the options panel below the mask manager.
