### ISSUE TITLE
Darktable not demosaicing DNG files

### ISSUE THREAD

**Issue by zephyrprime** [darktable-org/darktable#10226]
**Introduction**

Darktable does not apply the Demosaic module automatically to DNG files nor does it allow the module to be applied manually.

---------------------------------------------------------------

**Describe the bug/issue**
I am processing Sony raw files and I tried using the Adobe DNG converter.  DNG files do not get the demosaic module applied to them.  This happens with every dng file I tried.  It is especially noticeable in high iso images.

**To Reproduce**
1. Use Sony ARW files from a A7iii.
2. Convert to Adobe DNG using either version 12.4 or 13.2.  You can use lossy compression or not - the bug happens with either.
3. Import into Darktable.
4. Click on any dng file and you will see the demosaic filter has not been applied and you cannot apply it manually either.

**Expected behavior**
Demosaic filter should apply automatically to DNG files.

**Screenshots**
Raw file: https://1drv.ms/u/s!AjmxE0LYXCjTg6lbfAclLeCoFOhGBA?e=IrK3O0
DNG File: https://1drv.ms/u/s!AjmxE0LYXCjTg6lcSx_uKckqAu55uA?e=YDFFXo

source files: https://1drv.ms/u/s!AjmxE0LYXCjTg6lcSx_uKckqAu55uA?e=1fACQo

**Which commit introduced the error**
do not know.

**Platform**

* darktable version : 3.6.0
* OS                : Win10 
* Memory            : 32gb
* Graphics card     : nvidia 1080

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/rawspeed/issues/215
