### ISSUE TITLE
Unexpected Deletion of Presets in export module

### ISSUE THREAD

**Issue by n1xim** [darktable-org/darktable#10230]
**Describe the bug/issue**
When applying some presets I had created for the `Export` module that I had not used yet since upgrading to the 3.6.x version family Darktable reported "Deleting Preset for Deprecated Module" or something to that order (sorry, I can't remember my own phone number either). To me, as somebody who is generally just a user of this software that message means one of two things:
(1) The **WHOLE** `Export` module is deprecated and slated for removal, which makes me scream like a crazy person; or
(2) There's some poorly documented cleanup behavior going on that is making me scream like a crazy person and loose work for no good reason.

Once I come to my senses and realize that Darktable actually makes periodic backups of the configuration DB I'm able to restore things, replicate the behavior, and decide that maybe it is just a bug....????

**To Reproduce**
1. In either the `Darkroom` or `Lighttable` view expand the `Export` module
2. Activate a preset that hasn't been used in a while, preferably since before the instance of the program on your machine got updated from 2.x to 3.6.x.
3. See "toast" message indicating the preset you just applied has been deleted without giving you a chance to update it
4. Scream and swear incomprehensibly in multiple natural languages

(Last step optional.)

**Expected behavior**
  - The preset gets applied and does NOT get deleted.
  - If the preset can be applied, but should be updated, the user gets prompted to store the updated preset (similar to when applying a preset, applying a change, and then attempting to save that change back to the preset).

**Screenshots**
(Sorry, I'm not that fast on the PrintScreen key.)

**Screencast**
I didn't capture one, but perhaps I can if somebody really needs it. I'll mute the audio.

**Which commit introduced the error**
I'd love to help here, but I'm lacking the headspace today. If there's something it would help for me to check, please let me know and I can attempt to compile it (probably not before the weekend however).

**Platform**

* darktable version : `3.6.1-1.1` via OBS
* OS                : `Linux ... 5.13.0-7614-generic #14~1631647151~20.04~930e87c~dev-Ubuntu SMP Thu Sep 16 19:26:07  x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 20.04
* Memory            : 16GiB
* Graphics card     : NVIDIA GeForce GTX 760
* Graphics driver   : NVIDIA binary, `470.63.01-1pop0~1631198057~20.04~5c55171~dev`
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : "1:7.7+19ubuntu14" (whatever that means)
* Desktop           : KDE (with Gnome installed but inactive)
* GTK+              : GTK+2.0 (2.24.32-4ubuntu4) and GTK+3.0 (3.24.20-0ubuntu1)
* gcc               :  I can check if needed, but I didn't build the binaries.
* cflags            : I can check if needed, but I didn't build the binaries.
* CMAKE_BUILD_TYPE  :  I can check if needed, but I didn't build the binaries.

**Additional context**
I did upgrade my desktop from Ubuntu 18.04 to 20.04 a couple months back, in part to get Darktable 3.x working. I'm going to refrain from saying much about the new defaults in 3.x, other than that they completely blew up my workflow until I figured out how to go back to something compatible with people who actually know how to properly use a camera (because we've been doing it for over 20 years). Needless to say, this is the latest frustration that has made me **STRONGLY** consider forking the project (despite the annoyance I know that would cause me). I really feel like there's been a lot of changes lately that are good for a very particular niche group of people and that they've been detrimental to those of us who can write and debug code but would prefer to just be using our cameras in a way that makes sense and isn't hitched to the latest "trendy" way to do things. (Please keep the flames to direct messaging, and not the ticket. I'm not that hard to find.)

**Comment by n1xim** [comment]
@Nilvus So unceremonious deletion of user data is a good idea? I think not.
Should it be left in a bad state (not updated to current standards)? Absolutely not.

The presets did load, without error. I was watching stderr the whole time. We can do better, so we should do better. And doing better in this case means notifying the user of the re-saving of preferences.

Additionally, this is long after my first start of 3.6.x, which did in fact notify me that it was converting the "data.db" to the new schema and saved a properly labeled backup file. If there was a time for brute-force interventions that was it.

**Comment by Nilvus** [comment]
> @Nilvus So unceremonious deletion of user data is a good idea? I think not. Should it be left in a bad state (not updated to current standards)? Absolutely not.

That's not what I say...
