### ISSUE TITLE
File export: new conflict resolution option: overwrite if newer

### ISSUE THREAD

**Issue by derkork** [darktable-org/darktable#10240]
**Is your feature request related to a problem? Please describe.**

I regularly want to export all files I have marked with a tag or a label using an export preset to my NAS, so I can show them to clients. Exporting can take quite a while because my edits need to be applied and then the file is converted to JPEG and saved on the NAS. The first export of a  batch is working fine. However I usually have subsequent edits of these same images after the client has seen the edits and requests changes. Now to save time it would be nice if I don't have to re-export files that I didn't actually modify. So right now I can only select to `skip` all files that are already there, but then my new edits wouldn't be exported because they have been exported earlier and are therefore skipped. Or I can select `overwrite` but then I need to wait for the full batch to export even if I just changed a few images. Finally I can have `create unique filename` but then I would end up with duplicated pictures.

![image](https://user-images.githubusercontent.com/327257/138277539-3216500a-505c-466e-a29d-4b77d4ef1122.png)

**Describe the solution you'd like**

Ideally a new conflict resolution option `overwrite if newer` would help. So the export would compare the last modification date of the file on disk and the last change date of the picture in the database. If the change date is newer, it would overwrite the file, otherwise the export would skip exporting this picture.

**Alternatives**

Currently I narrow this down by filtering my pictures to only include pictures modified since the last export (e.g. i note down when I did the last export and then only filter images that have the marker and are modified since the last export date). This works but is somewhat cumbersome.

**Comment by elstoc** [comment]
Just thought I'd mention my FR (#3816) here as well.
