### ISSUE TITLE
remove histogram (scopes) module header

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10271]
#9640 added the ability to choose which panel the histogram module should be displayed on. However, in doing so it added a header/expander and presets menu to the module. I much preferred the UI without the header - there is no need to be able to expand/collapse, the header takes up more vertical space, and it takes a few clicks to change the setting anyway.

Additionally (a separate issue really) the module defaults to being collapsed on upgrade which is not ideal.

I would prefer one of the following solutions to facilitate removal of the header:

- Change the preference via the existing show/hide histogram shortcut, which could toggle between left/right/none. This might not be possible due to the fact that you need to exit the view for it to take effect.
- Right-click the histogram to change sides. Similar problem to above and possibly less discoverable?
- Add a "settings" button to the on-module buttonbox that can be used to load the dialog - we could also include any future additional settings here to avoid the need for further buttons
- Move the preference to the global preferences dialog and simply indicate that a restart is required for the setting to take effect

Personally, I prefer the last option, at least for now.

**Comment by aurelienpierre** [comment]
I just found out about this, it's not ok. The reason for the header bar is to enable multi-instanciation and preferences soon. This issue and associated PR cancels that.

**Comment by elstoc** [comment]
I still think that, for the histogram module, we need to find another way to do it. The module header looks ugly on the histogram.

**Comment by aurelienpierre** [comment]
I think we have reached the limit of the number of overlays we can possibly add without making the underlying graph unlegible. Adding a new line is the only way.

**Comment by elstoc** [comment]
Given that we won't be implementing the new features until after 3.8 please can we leave it as is for the time being and discuss alternatives when we come to need them. Once 3.8 is out we'll have time to give it some more thought (though I acknowledge we may well still fall back to a header as the only viable solution).

**Comment by aurelienpierre** [comment]
I kind of need instanciable histograms ASAP because I have series of pictures I'm unable to even, color-wise, and those series are paid work.

**Comment by elstoc** [comment]
Given that the buttons only appear when you hover over the histogram, I really don't think another button for settings would hurt.

**Comment by aurelienpierre** [comment]
Also, I have already restarted 2 or 3 times the refactoring of the histogram code, to make the API cleaner and prep for instanciation, each time a PR got merged before I had the time to finish and voided my work, so waiting is not really an option since devs seems to love this module and its code has gone completely spaghetti.

**Comment by elstoc** [comment]
Surely none of that is going to be merged before 3.8 though?

**Comment by aurelienpierre** [comment]
> Given that the buttons only appear when you hover over the histogram, I really don't think another button for settings would hurt.

Buttons should be to control the view frame, not the widget. Widget-wise controls at widget level are not something unheard of.

**Comment by aurelienpierre** [comment]
> Surely none of that is going to be merged before 3.8 though?

It's not about merging, it's about having code working ASAP and not having to redo the whole thing later.
