### ISSUE TITLE
Film roll bulk delete

### ISSUE THREAD

**Issue by lrkwz** [darktable-org/darktable#10276]
When you have many 'film roll' references to delete you cannot use multiple selection so you must delete one by one. 

Allowing multiple selection would be a good solution (ctrl right cick seems to be free as a valid key combination)

Fixing  #10275 would at least make the delete process less cumbersome. 

Ver 3.6.1
Ubuntu 20.4

**Comment by johans3** [comment]
+1

> I know Digital asset management isn't DT favorite topic, but this aspect is important as well. 
Adding some more flexibility for File handling doesn't involve complicated calculations. 

Therfore, i agree with the OP, It should be possible to delete multiple rolls at once

**Comment by credfeto** [comment]
+1

Removing something you didn't intend to import (like old lightroom previews folder with thousands of subfolders is a right pain)
