### ISSUE TITLE
KDE freezes/crashes when closing darktable

### ISSUE THREAD

**Issue by sbradl** [darktable-org/darktable#10281]
Almost always when I close darktable my desktop freezes for several seconds and most of the time it crashes completely.
By crashing I mean the screen goes blank then back again but nothing is clickable (like it is just a picture of the desktop).
Switching to a terminal with the keyboard works. I never have any crashes in any other application, it absolutely only happens with darktable.

On rare occasions it also happens while using darktable.

Are there any logs I could look at for errors? 

**Platform**
* darktable version: 3.6.1
* OS                : Linux 5.12.3
* Linux - Distro    : Manjaro
* Memory            : 16GB (more than enough free memory when the crashes happen)
* Graphics card     : AMD Radeon Vega 8 (Ryzen 7 5800U)
* Graphics driver   : free mesa drivers (21.2.3)
* OpenCL installed  : yes
* OpenCL activated  : no
* Desktop           : KDE 5.22.5

**Comment by kellyling80** [comment]
I am experiencing the same issue. Whenever I close Darktable, my KDE freezes and blacks-out, before gaining back control. Then the database lock error pops up the next time I launch Darktable. Also similar to OP, it freezes and blanks out occasionally whilst using/editing. 
All settings are default, and I've even removed all photos from my album and re-add from scratch.

Platform

    Darktable version: 3.6.1
    OS : Arch Linux / 5.14.15 (also crashes on 5.10.76-1 LTS)
    Memory : 32GB
    Graphics card : AMD Radeon Vega 7 (Ryzen Pro 7 4750)
    Graphics driver : free mesa drivers (21.2.3)
    OpenCL installed : yes
    OpenCL activated : no
    Desktop : KDE Plasma 5.32.2 Wayland
    Type of files used in Darktable: mostly RAW CR2 / RAF /NEF (avg. 20-40 MB in size each)
