### ISSUE TITLE
Crashes with certain images and random crashes. 

### ISSUE THREAD

**Issue by nathancrabtree** [darktable-org/darktable#10285]
With some images from different cameras DT will crash every time I try to edit in darkroom, the same images will crash it every time when doing this, the program just closes. The ones that will load up to edit, some work fine but with some I get random crashes that happen at different points in the edit when this happens I get the waiting text stuck for a moment and then it just closes. I’ve followed Aurélien’s video on creating the presets for colour and one of the pictures of the chart will make DT crash every time I touch the black level in the exposure module but with other images the same will be fine.

Starting from the terminal I get:
❯ darktable
Gtk-Message: 01:16:20.604: Failed to load module "appmenu-gtk-module"

(darktable:25505): libsecret-CRITICAL **: 01:16:20.640: secret_service_load_collections_sync: assertion 'paths != NULL' failed
[pwstorage_libsecret] error retrieving password: The name org.freedesktop.secrets was not provided by any .service files

And:
zsh: bus error (core dumped)  darktable
as it crashes. That's with trying to edit in darkroom with one of the images that crashes every time.

Debugging is not something I've done before, tried looking into it a bit to provide more but it's a bit over my head but I'll try to help if you need anything else. I've been building using yay mostly, not sure if I can add options for debugging with that? I can edit PKGBUILD with pamac but not sure what to add and what to do after this? 

Which commit introduced the error.

It's been the last few builds where I've noticed this issue 3.7.0+1336~g7bd5ad2c5f is where it started for me but I'd not built for a while so not sure about the ones immediately prior to this.  

Platform

darktable version : 3.7.0+1340~g30a90f4f8d
OS                :  Linux -5.14.14-arch1-1
Linux - Distro    : Arch
Memory            : 23941MiB
Graphics card     : AMD ATI Radeon RX 470/480/570/570X/580/580X/590
OpenCL installed  : Yes
OpenCL activated : Yes
Desktop           : KDE
It's an Imac 27" 2017 if that helps.

**Comment by Nilvus** [comment]
Could you post a RAW and XMP that cause your crashes. Maybe files are corrupted. I use master (Debian Sid Linux) and never had such crashes.

Did you try without OpenCL activated? Sometimes crashes are caused by some OpenCL drivers.

Could you also post which Gtk version you have?

**Comment by nathancrabtree** [comment]
It does the same without OpenCL. 

GTK version: 3.24.30

Here's some files that are making it crash, the high ISO Sony files are sample files from a review site, these I tried taking removing from DT and deleting the XMP files because that worked with one of my files but they still make it crash every time. The Nikon file makes it crash every time. The other images are recent test shots of mine, 528-530 crash but 531 doesn't and edits fine. https://drive.google.com/drive/folders/13T8RdWkkXlXNuTWF77aTIZQ91XY1Jk4q?usp=sharing

**Comment by ptilopteri** [comment]
you have something amiss.  I downloaded the NEF and loaded it into 
master, 3.7.0-1354-g70862d835, on openSUSE Tumbleweed.  No crash.

see http://wahoo.no-ip.org/~paka/Screenshot_20211030_212227.png

**Comment by nathancrabtree** [comment]
I've figured it out, there's something corrupted in my config. If move the config to create a new one no more crashes. Sorry I should have thought of this.

**Comment by nathancrabtree** [comment]
Got to reopen this because that wasn't it and I doubt it's a problem with my computer with what's causing it. The crashes only happen when the histogram is changed to either waveform or rgb parade, it's fine on vectorscope and histogram which it defaults to obviously with a new config so that's why it appeared to have fixed the issue. 

Here's an image and XMP that's crashing when on these modes, just toggling from histogram to waveform when the XMP is loaded should make it crash if not try turning off the white balance module, that seems to do it every time whatever the image when in these modes. I’ve followed Aurélien’s video on creating the presets for colour which is why the settings on the image are what they are. https://drive.google.com/drive/folders/1nrBTo-0ZoWXfVGkm0CJwnY2zIPvv_Z31?usp=sharing
