### ISSUE TITLE
Wrap-around for hue sliders

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#10299]
**Describe the solution you'd like**

For hue sliders (such as in Color balance rgb) it would be nice if the slider wrapped around from the edge. E.g. if you're looking for a hue near red, it would be neat to continuously scroll or drag near the red hues in the left and right of the slider. In other words, if the hue is 0 and you drag to lower the valua, it would jump to 360 in the other end of the slider.

By nature, the hue value is cyclic and often represented as a ring in GUIs. I do like a slider instead of a ring and appreciate the usability with a mouse - however the usability would be increased with the wraparound.

This feature could be configurable and probably opt-in, off by default.

This would matter the most for creative modules. In my opinion the current behaviour is ok for mask hue ranges (those would likely become more complex with the wraparound and require more thought).

**Comment by difrkaguilar** [comment]
This will be a great idea to keep in mind.

**Comment by dterrahe** [comment]
This was implemented in #12561

It works for any 360 degree slider when scrolling (except when hovering over the left or right 10% of the slider, which is the "force" zone where you can push through any soft limits) or using arrow keys. It also works when you drag using a modifier key (ctrl for slow speed, shift for high speed and alt for dragging without repositioning on first click).

Please close this issue if that resolves it for you.
