### ISSUE TITLE
3.6.1 Negative adjustments in modules using masks have nearly no effect 

### ISSUE THREAD

**Issue by frli8848** [darktable-org/darktable#10291]
**Describe the bug/issue**

Negative adjustments in new instance of, for example, the exposure module using a mask has almost no effect.

**To Reproduce**

Example using the exposure module:

1. Open an image in Darkroom
2. Go to the exposure module
3. Adjust the exposure a bit, say 0.5 EV.
4. Go to the Mask manager and create a new shape, for example a circle.
5. Go to the exposure module and create a new instance.
6. Click on the pen icon in the new exposure instance and add the circle to the "drawn mask" popup menu.
7. Try to pull down the exposure as much as possible (-3 EV)

This has nearly no effect. The global exposure compensation works fine but the one in the second exposure instance using the circle mask does almost nothing when I try negative adjustments. 

I see a similar behavior in other modules too. Add a mask to for example a new instance of the color zones module and then pull down the whole curve has also almost no effect.

Furthermore, if I open a new file, edited with an earlier version of DT, and add new mask then the new mask "gets" this bug but if there was a previously generated mask then that mask seems to work as it should. That is, I get one buggy and one non-buggy mask in the file!?

**Expected behavior**

The part of the image inside the mask should become significantly darker when adjusting the exposure by -3 EV.

**Screenshots**
![mask_0_ev](https://user-images.githubusercontent.com/36279125/139436388-809a561a-1efe-46f6-8615-6569a51f6e63.png)

![mask_minus_3_ev](https://user-images.githubusercontent.com/36279125/139436409-31108834-76a5-4770-8c8d-23602ddcb585.png)

**Platform**

* darktable version : 3.6.1
* OS                : Linux - kernel  5.12.19-gentoo
* Linux - Distro    : Gentoo
* Memory            : 64 GB
* Graphics card     : 3080 Ti
* Graphics driver   : Nvidia
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              :  1.20.11
* Desktop           : KDE
* GTK+              : 3.24.29
* gcc               :  clang version 13.0.0
* CMAKE  : cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_LINKER=ld.ldd -DCMAKE_C_FLAGS="-O3 -march=native" -DCMAKE_CXX_FLAGS="-O3 -march=native" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CURVE_TOOLS=no -DBUILD_NOISE_TOOLS=no -DBUILD_PRINT=yes -DCUSTOM_CFLAGS=ON -DDONT_USE_INTERNAL_LUA=OFF -DRAWSPEED_ENABLE_LTO=no -DTESTBUILD_OPENCL_PROGRAMS=OFF -DUSE_AVIF=no -DUSE_CAMERA_SUPPORT=yes -DUSE_COLORD=yes -DUSE_FLICKR=no -DUSE_GMIC=no -DUSE_GRAPHICSMAGICK=yes -DUSE_KWALLET=yes -DUSE_LIBSECRET=no -DUSE_LUA=yes -DUSE_MAP=yes -DUSE_NLS=yes -DUSE_OPENCL=yes -DUSE_OPENEXR=yes -DUSE_OPENJPEG=yes -DUSE_OPENMP=yes -DUSE_WEBP=yes -DWANT_JSON_VALIDATION=no -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..

**Comment by elstoc** [comment]
@ralfbrown is referring to the opacity of the _shape_ and **not** the opacity beneath the _blend mode_ control or the opacity in the _mask refinement_ section (I admit all these opacities can be confusing for first-time users). 

The opacity of the _shape_ is not shown in the right-hand panel at all. You need to hover over the shape with your mouse and the opacity is shown as a hint in the top panel as follows:

![Screenshot_2021-10-29_21-04-15](https://user-images.githubusercontent.com/9555491/139495395-af661033-fce9-4145-8761-71828e97ec1a.png).

**Comment by frli8848** [comment]
Yeah, three different opacities associated with masks is confusing even for non-first time users.

And, it took me a while to figure out that you ment hover over the shape in the _image_ and not hover over the shape in the _mask manager_.  Hovering in the mask manager just shows the group. But I also found out that the opacity is actually shown in the mask manager (when the opacity is not at 100%) if one expands the corresponding group :

![mask_mgr](https://user-images.githubusercontent.com/36279125/139527197-af9ecaea-8402-477d-a558-020561fac792.png)

**Comment by TurboGit** [comment]
So if solve, please close.
