### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by errolsap** [darktable-org/darktable#10296]

**Comment by errolsap** [comment]
I have a major problem in Darktable in Linux. The "import" module doesn't exist in the settings so I cannot import photos. I have reinstalled Darkroom after totally removing it but cannot get the import module. When going to "setings" "import" the only available menu is "session options" and not "import" as it used to be. Any ideas on how to solve this?

**Comment by Nilvus** [comment]
Please complete all infos asked in issue template like which Linux (distrib, release...), darktable version you use, how you install darktable, etc. With so few infos it will not be possible to help.

Not having a darktable part like could probably be related to wrong darktable package (error on compile with some library missing, like gphoto2). I so close this issue and please provide a new one if you want with all infos asked.
