### ISSUE TITLE
Color missmatch

### ISSUE THREAD

**Issue by RJGhugo** [darktable-org/darktable#10303]
**Describe the bug/issue**
Importing a picture from the from the GFX 50s gives nice color in the standardsettings not with the GFX 100s.

**To Reproduce**
1. Go to [raw.pixls.us](https://raw.pixls.us/l)
2. Get image [GFX 50s uncompressed](https://raw.pixls.us/getfile.php/1436/nice/Fujifilm%20-%20GFX%2050S%20-%2014bit%20uncompressed%20(3:2).RAF) image.
3. Get image [GFX 100s uncompressed](https://raw.pixls.us/getfile.php/4493/nice/Fujifilm%20-%20GFX100S%20-%2016bit%20uncompressed%20(4:3).RAF) image.
4. Compare colors in darktable (the GFX 100s has somehow missmatched/grayed colors)...

**Platform**

* darktable-2:3.6.1-2
* 5.14.14-arch1-1

**Comment by Nilvus** [comment]
GFX100s is actually not officially supported by darktable, that probably explains what you pointed here. Maybe it's quite near as the GFX 100 which is supported. And we already have an issue about GFX100s support. As it is related, I will close this issue and suggest you to continue discussion about that in GFX100s issue to add real support: #10278

To see if a camera is really/completely supported, you could check here: https://www.darktable.org/resources/camera-support/
