### ISSUE TITLE
Add dci p3 linear working space profile

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#10302]
Is it possible to add  the dci p3 linear profile in the working space profiles?

**Comment by MStraeten** [comment]
what's the benefit of a limited color space as a working color space? Working color space should be as large as possible - thats why it’s rec2020 by default

**Comment by TurboGit** [comment]
Trivial to add, but indeed is it worth or even a good enhancement?

**Comment by abnormally-distributed** [comment]
You know you can add any working space you want as an icc profile right?
