### ISSUE TITLE
[FR] Allow to edit presets names and it's properties in the darktable preferences presets tab.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10300]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to edit names or properties of presets that I created in a previous moment, the difficult thing is that I have to do it from the module, deploying the menu, apply the preset and then go to "edit this preset" to be able to change the name or properties. (image 01)
In that case, using the modules, users have to apply presets first and then edit them.

This could be done from the darktable configuration window, in the presets tab, that by clicking on it you can edit the preset name and it's properties, and then continue editing the others in sequence without having to do all these steps in the modules. At this moment the edition it's not allowed, the pop-up window says edit at the top, but only allow export or delete. I made a mock up with the edit button and the parameters (image 02 and 03).

It must be taken into account that there is an issue #9956 (darktable preferences/presets - modules collapse after action) that I reflected previously related to the edition of the presets that collapse after editing them.

**Describe the solution you'd like**
Allow to edit preset names and it's properties in the darktable preferences presets tab.

**Additional context**

**image 01**
![Screenshot-20211031105633-407x861](https://user-images.githubusercontent.com/67672868/139589495-8b201cdf-22ce-4dc3-ae94-462a6b800258.png)

**image 02**
![Screenshot-20211030124759-1439x1166](https://user-images.githubusercontent.com/67672868/139589390-d63f28b4-43c3-4f95-9f2c-7d6440cf6f28.png)

**image 03**
![Screenshot-20211030124722-1457x1179](https://user-images.githubusercontent.com/67672868/139589085-926badb0-16e9-437b-a6c1-9214fa5b5ec9.png)

**Comment by dterrahe** [comment]
Was this fixed for you by #11905? If so, please close this issue. Otherwise provide further information. Thanks!

**Comment by difrkaguilar** [comment]
Perfect, thank you very much to all
