### ISSUE TITLE
Import problem info

### ISSUE THREAD

**Issue by errolsap** [darktable-org/darktable#10304]
Thanks to Nicolas for pointing to to me what was missing in my post. I hope this addition is enough to show me what to do. I would like to attach a screenshot but don't know if this is possible.
I have a major problem in Darktable in Linux on my desktop computer. The "import" module doesn't exist in the settings so I cannot import photos. I have reinstalled Darkroom after totally removing it but cannot get the import module. When going to "setings" "import" the only available menu is "session options" and not "import" as it used to be. Any ideas on how to solve this?
I installed Darktable 3.6 in two different distros of Linux. One in Kubuntu 21.10 and also in MX 21.10.with the same results. Both distros are KDE. I installed Darktable using Flatpak in both distros. In Kubuntu I uninstalled Darkroom completely after one installation and reinstalled using Discover in Kubuntu. I got the same result described above no matter what I tried.
I also tried installing Darktable 3.6.1-win64 on my Windows laptop with  the same problem. That makes me sure that the problem is with me and not the program. As I said above attaching a screenshot would best explain and if there is any more info to provide I certainly will.
TIA
Errol

**Comment by errolsap** [comment]
https://user-images.githubusercontent.com/93417962/139570652-3038e901-28c7-4d5a-b402-a0562ab32d08.png

I think I was able to upload a screenshot. As you can see there are no "Import" possibilities available in the "import" view in "settings". I' hope there is a way to restore this. It was there before these new installations

**Comment by MStraeten** [comment]
you're aware that you don't import stuff using the import section of preferences dialog? 
If you want to import files you need to use the import section upper left side of the main window in lighttable mode
![image](https://user-images.githubusercontent.com/39386816/139576300-111bb8af-a4ac-4679-9fb3-a16df8ba5e75.png)
have a look at https://youtu.be/qvi_clcVkuk?t=119

**Comment by errolsap** [comment]
I know that but because I don't have access to the import dialogue box I cannot "tell" Darktable where my photos are stored. The import stuff directs me to my /home folder and won't allow me to choose the real folder where my photos are. Therefore I need the "import" dialogue.

**Comment by Nilvus** [comment]
> I know that but because I don't have access to the import dialogue box I cannot "tell" Darktable where my photos are stored. The import stuff directs me to my /home folder and won't allow me to choose the real folder where my photos are. Therefore I need the "import" dialogue.

What do you mean by you can't access import dialog box? Did you expand import module in the left main window (clicking on the arrow like you can see in @MStraeten screenshot? Then click on one of the buttons (depending on the type of import you want to do) to open the dialog import box?

**Comment by errolsap** [comment]
https://user-images.githubusercontent.com/93417962/139583548-57c9d917-7af3-4714-804e-4e684252682b.png

I will try and explain it better. In my screenshot there are two "import" possibilities. The left one should allow me to go to my photographs but as my photographs are on an different drive from my /home drive, the drive with my photos is not visible in the import.
The import (om the right) in the settings used to have a title " import" above the "session options". There I was able to see all the drives on my computer and make a path to the correct folder which would then be read by the "import" on the left. This is no longer possible for me. The "import" optin in the settings is nowhere to be fond.
I hope I have explained myself correctly.

**Comment by MStraeten** [comment]
If you click on the left import, a file selection dialog opens. If your desired folder isn’t visible the simply click on the little + icon next to places to add the folder.
The settings in preferences are used to specify the target directory and naming scheme for copy&import.

**Comment by errolsap** [comment]
That isn't what happens to me. All I see is /home and am unable to see any other folder. I have one called "photographs" which is on another hard drive in my computer. I used to go to "import" on the right side and map that hard drive and folder. After that all was well. I now cannot map the other hard drive because it isn't visible to Darktable.
Martin and Nicolas thank you meanwhile for your efforts.

**Comment by errolsap** [comment]
[Darktable.3.4.docx](https://github.com/darktable-org/darktable/files/7449028/Darktable.3.4.docx)
I have tried something radical which worked. I installed Darktable 3.4 in windows. I attached a screen capture of the import file as it came up in 3.4. This is what is missing in my 3.6 and I cannot import files. I hope the problem is now better explained.

**Comment by MStraeten** [comment]
you really should read release notes (https://www.darktable.org/2021/07/darktable-3-6/)  ;)
here: _Some preferences have been moved out of the global preferences menu and into new options within module “presets” menus._
an thats the top section in your screenshot thats now in the import module parameters section:
<img width="352" alt="Bildschirmfoto 2021-10-31 um 15 50 23" src="https://user-images.githubusercontent.com/39386816/139589294-5f349e5f-1ff2-4a92-bee7-e1c55bf59d47.png">

but that doesn't solve the issue you aren't finding your import directory. It must be properly mounted, and then you should add the mountpoint to your places (https://docs.darktable.org/usermanual/3.6/module-reference/utility-modules/lighttable/import/#import-dialog)

**Comment by errolsap** [comment]
Thank you Martin. I have just arrived home and tomorrow I will try out your suggestions.

**Comment by errolsap** [comment]
Thank you Martin and Nicolas. The final instructions of Martin after me succeeding in explaining the problem certainly did the trick. I found the place that "import" was changed to and everything now works.

**Comment by Nilvus** [comment]
Good. So I close this issue. For next time, think about closing your issues (you could do that with a button below comment field input for issues you opened).
