### ISSUE TITLE
Color picker in colorbalancergb produces opposite color

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#10307]
**Describe the bug/issue**
Using the color picker in the 4-ways tab produces a hue that is the complement of hue selected by the user. For example, in my image, placing the color picker over orange (HSL: 19.89, 58.88, 41.66) sets the hue slider to a light blue (201.87 degrees)

**To Reproduce**
1. Go to darktable->colorbalancergb->4 ways
2. Click a colorpicker (all four of them seem to produce nearly the same result)
3. Select a color
Selecting a warm color produces the opposite effect (setting the slider to the complementary cool color). Every color I've tried so far has set the slider to the "opposite" color.

**Expected behavior**
When clicking on a color using the color picker, I expect the colorbalancergb sliders to be set to the color that was selected by the colorpicker.

**Screenshots**
![original](https://user-images.githubusercontent.com/10678620/139601886-eea5daa5-b693-47af-8ad2-5293c4d0122a.png)
![o2b](https://user-images.githubusercontent.com/10678620/139601888-a6d88939-cf15-496f-852c-9c1967b15397.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

```
this is darktable 3.7.0+1357~g7acd55130b-dirty
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0-dev
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```
* Linux - Distro: archlinux
* Memory: 16GB
* Graphics card: Intel 530
* OpenCL installed: Intel NEO 
* Desktop: KDE
* gcc: 11.1.0

**Comment by groutr** [comment]
https://github.com/darktable-org/darktable/blob/master/src/iop/colorbalancergb.c#L1119

It seems like this is intentional. Perhaps it should be explained in the tooltip, that these color pickers are different than regular color pickers.. I expected the color picker to behave similar to how the color pickers in other parts of darktable behaved.

**Comment by MStraeten** [comment]
works as designed - have a look at he manual https://docs.darktable.org/usermanual/3.6/module-reference/processing-modules/color-balance-rgb/#4-ways-tab

**Comment by Nilvus** [comment]
I so close as this is not an issue.
