### ISSUE TITLE
multiple parametric masks

### ISSUE THREAD

**Issue by tpapp** [darktable-org/darktable#10326]
**Is your feature request related to a problem? Please describe.**

Occasionally one would like to select a union of various properties that can be described by parametric masks (eg skin color and blue for eyes, nothing else).

**Describe the solution you'd like**

Multiple parametric masks in a module instance, to be combined under the same [rules](https://docs.darktable.org/usermanual/3.6/darkroom/masking-and-blending/masks/drawn-and-parametric/) as drawn elements and parametric masks.

**Alternatives**

For some transformations, it is possible to work around this problem by using multiple module instances with the parametric mask elements that would form the union above. However, that becomes tedious when information would be lost by a transformation (eg desaturate some colors), or the transformations are nonlinear.

For example, to desaturate everything but skin tones and blue, one would currently desaturate from red to skin tones, then from skin tones to blue, then from blue onwards. This requires 3 module instances, but all that changes is the mask.

Naturally, drawn masks can be a workaround too and are very powerful, but address a different problem.

**Additional context**

[Discussion](https://discuss.pixls.us/t/combine-parametric-masks/27711).

**Comment by TurboGit** [comment]
If I understand your request I fear that this will make the parametric masks UI even more complex. I think we have reached some complexity bound at the moment. All in all, don't hold your breath on this :)

**Comment by Nilvus** [comment]
I fear too that this would add too much complexity.

**Comment by Dannny1** [comment]
Just an idea. Maybe separating all masks to mask manager and enabling mask centric workflow/view instead of/with module centric would make some edits faster and make less clutter. 
E.g. when selecting a mask it would show related modules in special module group....

**Comment by tpapp** [comment]
Yes, making masks first class would help solve this. Specifically, all this would require is making a mask from existing masks and then using it.

**Comment by tpapp** [comment]
I figured out a workaround with raster masks.

1. Pick a module that (a) has a no-op mode and (b) comes earlier in the pipeline than the change you want to make (eg exposure with zero correction). Create **one instance for each parametric mask** you need.

2. Use each mask in subsequent corresponding instance of the module you want to apply **as a raster mask**.

**Comment by s7habo** [comment]
I will also welcome this functionality. 
Perhaps another option would be - if customizing the masks is too complex - to have a module similar to color zones or color look up table that are adapted to scene-reffered workflow.

**Comment by yaitskov** [comment]
Today I realized too that I need a parametric mask manager.
Single parametric mask cannot tackle blond died hair overlapping with skin body and model is behind a dark rock - died hair are skin looks the same and non died hair are rock merge and they both interleave so hand drawn mask doesn't help a lot.
