### ISSUE TITLE
darktable 3.6.1 and ColorCalibrater 1.3.6

### ISSUE THREAD

**Issue by CityscapePhoto** [darktable-org/darktable#10328]
Running Windows 10 with the latest update. darktable will not load but has installed properly. I've attempted to run the application as administrator without any success. I have the latest version of ColorCalibrater installed but the issue with darlktable predates the installation of that application. I'm trying to find where the debug folder is so I can forward it to you. Any suggestions as where to look?

**Comment by MStraeten** [comment]
ColorCalibrator is commercial software not sold or provided by the darktable team - so if you have issues you should contact the vendor since you paid for their support ;)

**Comment by CityscapePhoto** [comment]
The issue isn’t with ColorCalibrater but with darktable. It stopped loading before the installation of ColorCalibrater. I was thinking of an outside chance that ColorCalibrater might have a file that could have been deleted when I removed another application. That wasn’t the case.

Where can I find the debug file so I can send it to you?


/vr/
Jeffrey S Austin ASMP Allied AIA
Architectural Photographer
Jeffrey S Austin LLC
757.981.6440
https://dealbhan.com<dealbhan.com>

**Comment by MStraeten** [comment]
since here no one exactly knows what Colorcalibrater changes in darktable directories there's just one reccomendation:
delete the whole darktable installaton directory (usually C:\Program Files\darktable) the whole config directory (usually <user>\AppData\Local\darktable - don't forget to backup first) and also cache directories (e.g <user>\AppData\Local\Microsoft\Windows\INetCache\darktable)
Then you can install a pure darktable package provided by darktable. That should run on your Win10 machine as it does on several win10 machines.

**Comment by CityscapePhoto** [comment]
Is there another application that will do what ColorCalibrater does? I dumped everything from Adobe and while I haven’t gone 100% back to RedHat, too many of my business applications will only run on Micro$oft, I am a fan of open source.


/vr/
Jeffrey S Austin ASMP Allied AIA
Architectural Photographer
Jeffrey S Austin LLC
757.981.6440
https://dealbhan.com<dealbhan.com>

**Comment by MStraeten** [comment]
Have a look at https://docs.darktable.org/usermanual/3.6/module-reference/processing-modules/color-calibration/#extracting-settings-using-a-color-checker

**Comment by Nilvus** [comment]
Seems that this should be closed? @CityscapePhoto?

**Comment by CityscapePhoto** [comment]
Still doing battle.


/vr/
Jeffrey S Austin ASMP Allied AIA
Architectural Photographer
Jeffrey S Austin LLC
757.981.6440
https://dealbhan.com<dealbhan.com>

**Comment by CityscapePhoto** [comment]
I hope this message finds you well. My name is Mitchell Bauer, and I’m
reaching out to introduce *Bauer Marketing*, where we provide tailored
digital marketing solutions designed to help businesses like yours expand
their online presence, attract more customers, and achieve measurable
growth through results-driven strategies.

Our core services include:

   -

   *Meta Ads Management:* We create and optimize high-performing Meta
   campaigns that reach targeted audiences, increase engagement, and drive
   conversions.
   -

   *Search Engine Optimization (SEO):* With customized SEO strategies, we
   help your business rank higher on search engines, boosting visibility and
   organic traffic.
   -

   *Content Marketing:* Our team produces compelling, audience-focused
   content that enhances your brand voice and increases customer trust.
   -

   *Email Marketing:* We design and manage personalized email campaigns
   that boost engagement, retention, and ROI.
   -

   *Social Media Growth:* Leveraging platforms like TikTok and Instagram
   Reels, we develop engaging content strategies to grow and sustain your
   social media presence.

We’d love the opportunity to learn more about your business goals and
explore how we can help support your growth. Please feel free to visit our
website or LinkedIn page below to learn more about our work:
🔗 Bauer Marketing Website <https://bauermarketing.digital/>
🔗 LinkedIn – Bauer Marketing
<https://www.linkedin.com/company/bauer-marketing/posts/?feedView=all>

Let me know a convenient time to connect, or feel free to reach out with
any questions. I look forward to the opportunity to work together.

Best regards,
-- 
Mitchell Bauer
Bauer Marketing
(505)-249-1491 | ***@***.***

**Comment by CityscapePhoto** [comment]
Thank you for the information and good luck. We advertise our solicitations
through Bonfire, MSA website, and the State of Maryland website known as
eMaryland Marketplace.

Good luck!

On Mon, Apr 7, 2025 at 3:49 PM Mitchell Bauer ***@***.***>
wrote:

> I hope this message finds you well. My name is Mitchell Bauer, and I’m
> reaching out to introduce *Bauer Marketing*, where we provide tailored
> digital marketing solutions designed to help businesses like yours expand
> their online presence, attract more customers, and achieve measurable
> growth through results-driven strategies.
>
> Our core services include:
>
>    -
>
>    *Meta Ads Management:* We create and optimize high-performing Meta
>    campaigns that reach targeted audiences, increase engagement, and drive
>    conversions.
>    -
>
>    *Search Engine Optimization (SEO):* With customized SEO strategies, we
>    help your business rank higher on search engines, boosting visibility and
>    organic traffic.
>    -
>
>    *Content Marketing:* Our team produces compelling, audience-focused
>    content that enhances your brand voice and increases customer trust.
>    -
>
>    *Email Marketing:* We design and manage personalized email campaigns
>    that boost engagement, retention, and ROI.
>    -
>
>    *Social Media Growth:* Leveraging platforms like TikTok and Instagram
>    Reels, we develop engaging content strategies to grow and sustain your
>    social media presence.
>
> We’d love the opportunity to learn more about your business goals and
> explore how we can help support your growth. Please feel free to visit our
> website or LinkedIn page below to learn more about our work:
> 🔗 Bauer Marketing Website <https://bauermarketing.digital/>
> 🔗 LinkedIn – Bauer Marketing
> <https://www.linkedin.com/company/bauer-marketing/posts/?feedView=all>
>
> Let me know a convenient time to connect, or feel free to reach out with
> any questions. I look forward to the opportunity to work together.
>
> Best regards,
> --
> Mitchell Bauer
> Bauer Marketing
> (505)-249-1491 | ***@***.***
>
>

-- 
*Sandra Fox*

*Maryland Stadium Authority*
*Procurement*

*O: 410-223-4130*
*E: ***@***.*** ***@***.***>*

*The Warehouse at Camden Yards*
*333 West Camden Street, Suite 500*
*Baltimore, MD 21201*
*W: www.mdstad.com <http://www.mdstad.com>*

Maryland is Open for Business.  If you are an eMaryland Marketplace
vendor, CLICK
HERE <https://www.surveymonkey.com/r/Maryland_eMMA> to complete preliminary
registration for "*eMMA*" Maryland's new eProcurement platform launching in
mid-July, or send questions to ***@***.***

-- 
Customer Service Survey 
<https://www.doit.state.md.us/selectsurvey/TakeSurvey.aspx?agencycode=STAD&SurveyID=86M2956#>


IMPORTANT NOTICE: This electronic transmission is intended only for the 
use of the individual or entity to which it is addressed and may contain 
information that is non-public, proprietary, privileged, confidential and 
exempt from disclosure under applicable law or may constitute personal work 
product. If you are not the intended recipient, please delete this message 
immediately from your system without copying or forwarding it and notify 
the sender. Any unauthorized copying, disclosure or distribution of the 
material in this e-mail is strictly forbidden.

**Comment by CityscapePhoto** [comment]
Dear Mitchell,

 

The first step in participating in the Federal contracting arena is to maintain a profile in the System for Award Management ( <http://www.SAM.gov> www.SAM.gov).  The SAM registration process is FREE, but SAM requires companies to re-certify their information once a year.  For assistance in registering on SAM or updating an expired profile, locating Federal opportunities or marketing your company’s capabilities, recommend contacting a local Procurement Technical Assistance Center (PTAC:    <http://www.aptac-us.org> http://www.aptac-us.org  & select your state on the map). These centers are now called APEX Accelerator (formerly Procurement Technical Assistance Center) located in your area at  <https://www.apexaccelerators.us/#/> https://www.apexaccelerators.us/#/  or use the map from the Association of Procurement Technical Assistance Centers (APTAC)  <https://www.aptac-us.org/> https://www.aptac-us.org/ for more information and assistance in both contracting and subcontracting possibilities. 

 

These centers are located in most states and partially funded by DOD to provide small business concerns with information on how to do business with the DOD. They provide training and counseling on marketing, financial, and contracting issues at minimal or no cost. 

 

Regards,

 

ROSITA CAROSELLA

DLA, Associate Director of Small Business Programs, DCSO

700 Robbins Avenue. Bldg 6 South

Philadelphia, PA 19111

               

PHONE: (445) 737-5810

E-MAIL: ***@***.*** ***@***.***> 

 <http://www.dla.mil/smallbusiness> www.dla.mil/smallbusiness

 <https://www.dla.mil/Small-Business/Contact/> https://www.dla.mil/Small-Business/Contact/

 

 

 

 

From: Mitchell Bauer ***@***.***> 
Sent: Monday, April 7, 2025 3:50 PM
To: ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; Jeffrey S Austin ***@***.***>; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; Jones, Alandra R CIV DLA SMALL BUSINESS PROG (USA) ***@***.***>; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; Powell Industries Inc. ***@***.***>; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; HQ Small Business Programs, DCSO ***@***.***>; DSCC Multimedia Scheduler ***@***.***>; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***; ***@***.***
Subject: [Non-DoD Source] Elevate Your Digital Presence with Bauer Marketing

 

I hope this message finds you well. My name is Mitchell Bauer, and I’m reaching out to introduce Bauer Marketing, where we provide tailored digital marketing solutions designed to help businesses like yours expand their online presence, attract more customers, and achieve measurable growth through results-driven strategies.

Our core services include:

*  Meta Ads Management: We create and optimize high-performing Meta campaigns that reach targeted audiences, increase engagement, and drive conversions.

*  Search Engine Optimization (SEO): With customized SEO strategies, we help your business rank higher on search engines, boosting visibility and organic traffic.

*  Content Marketing: Our team produces compelling, audience-focused content that enhances your brand voice and increases customer trust.

*  Email Marketing: We design and manage personalized email campaigns that boost engagement, retention, and ROI.

*  Social Media Growth: Leveraging platforms like TikTok and Instagram Reels, we develop engaging content strategies to grow and sustain your social media presence.

We’d love the opportunity to learn more about your business goals and explore how we can help support your growth. Please feel free to visit our website or LinkedIn page below to learn more about our work:
🔗 Bauer Marketing Website <https://bauermarketing.digital/> 
🔗 LinkedIn – Bauer Marketing <https://www.linkedin.com/company/bauer-marketing/posts/?feedView=all> 

Let me know a convenient time to connect, or feel free to reach out with any questions. I look forward to the opportunity to work together.

Best regards,

-- 

Mitchell Bauer

Bauer Marketing 

(505)-249-1491 | ***@***.*** ***@***.***>

**Comment by victoryforce** [comment]
I don't know how this happens (I've never commented via email), but it seems that some spam emails are forwarded here via CityscapePhoto's email and accepted by GitHub as comments. I deleted this spam and locked the conversation.
