### ISSUE TITLE
Export JPG  up to a particular size

### ISSUE THREAD

**Issue by Brunnian** [darktable-org/darktable#10320]
**Is your feature request related to a problem? Please describe.**
I submit my finished photos as JPG to a web site called geograph.org.uk (have a look, it's impressive.  7 Million geolocated photos of the UK, free to use under the CC2 licence).  Darktable is very good for perspective correction, adding positions, correcting exposure even (don't tell them) cloning out lens spots in the sky.   But the web site has an upper file size limit of 8Mb regardless of pixel count, and I tend to export at several JPG % settings to get as close to that as possible.  I don't like jpeg artifacts in the skyline or grasses.  

**Describe the solution you'd like**
I would like the ability to set a maximum file size for exporting and have the system set the best possible compression setting to achieve it.

I can do this in Irfanview, loading full size images and saving them with a maximum file size.  It would be very useful to do this in Darktable.

**Alternatives**
I can't think of one.

**Additional context**
No screen shots seem appropriate, so let me give you one of my images to look at - Geographs make great desktop wallpaper
https://www.geograph.org.uk/photo/6989275

**Comment by ralfbrown** [comment]
**Alternatives**

Export to lossless format like TIFF, then
1. run batch conversion with IrfanView
2. use ImageMagick: `convert FOO.tif -define jpeg:extent=8192kb FOO.jpg`

Or export as JPEG with really high quality, then run `jpegoptim -S8192 FOO.jpg`

The second and third options could probably be automated with a Lua script.

**Comment by Brunnian** [comment]
Thanks, Ralf
I will look into those too
Stay safe
Bob
