### ISSUE TITLE
A menu would help quite a bit

### ISSUE THREAD

**Issue by peterjonwhite** [darktable-org/darktable#10339]
Is there a reason Darktable for Mac doesn't use a menu, like other Mac applications? It would make it so much easier for us new users.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by Nilvus** [comment]
darktable is not a Mac application. It's first developed under Linux and it's then had been ported in Mac OS. Thus, darktable doesn't use menus at all, even in Linux (or Windows). darktable is made to have all needed options, access inside app. I don't see any use that would need such menu (and it will be hard to do as Mac menu like doesn't exist in Windows and not on all desktop environment in Linux). And as we have so few developers in Mac, do not expect that.

**Comment by TurboGit** [comment]
Yep, and when @Nilvus says so few it is an euphemism, mostly a single dev on MacOS ! So many users, so many requests and no MacOS devs????

**Comment by parafin** [comment]
darktable doesn’t have a menu, so closing.

**Comment by peterjonwhite** [comment]
Very good.

I’ll tell those silly gimp developers to get rid of the menu on their Mac version.

**Comment by TurboGit** [comment]
@peterjonwhite : GIMP devs are not silly they have made a different design decision. If you don't like this just don't use dt.

**Comment by parafin** [comment]
GIMP has menu on other OSes too. This has nothing to do with macOS at all.
