### ISSUE TITLE
DT crash

### ISSUE THREAD

**Issue by pahervin** [darktable-org/darktable#10333]
**Describe the bug/issue**
DT crashes in the darkroom when browsing the filmstrip.
Redo many times

**To Reproduce**
1. Open the darkroom
2. Process a photo
2. Browse the filmstrip to another photo hesitating the one to select
3. DT crashes while browing

**Backtrace**
[darktable_bt_13A8B1.txt](https://github.com/darktable-org/darktable/files/7478279/darktable_bt_13A8B1.txt)

**Platform**
* darktable version : 3.6.1
* OS                : Win10 (21H1)
* Memory            : 8GB
* Graphics card     : Intel UHD Graphics 620 and Radeon 520
* Graphics driver   : 
* OpenCL installed  :  no

**Additional context**
 - Can you reproduce with another darktable version(s)? no
 - Do you use lua scripts? no

**Comment by pahervin** [comment]
A system restart stops the crashes.
The issues seems comes from a copy of a photo with the selected image(s) module.

**Comment by Nilvus** [comment]
So seems to not be something to fix in darktable. If it's related to some images and with a bunch of photos only, this is so probably more because of some corrupted images or an issue in your system, than something related to darktable. So closing.
