### ISSUE TITLE
top panel alignment

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10348]
The buttons and dropdowns in the top panel should all be aligned to one another but they are not. In addition, the reverse-sort icon should be larger to distinguish it from the arrows on the dropdown lists.

![Screenshot_2021-11-07_11-35-05](https://user-images.githubusercontent.com/9555491/140643268-25146cb5-ee27-4df6-b3d5-2605b49ac04f.png)

@Nilvus I've assigned this to you but I'm not entirely sure if it can be done with just CSS.

**Comment by Nilvus** [comment]
Will check. It was not this way quite recently as far as I remember. But would be hard to find when this had changed.

**Comment by Nilvus** [comment]
@elstoc: fix is here (and a little more!)
