### ISSUE TITLE
[FR] copy historic module settings to top of history stack

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10344]
If I have made a number of changes to a module over time and later decide I want to revert back to an earlier set of module parameters, it would be great to be able to do this without reverting the whole of my history back to that point in my edit process (potentially reverting some other unrelated module changes).

It would be nice, therefore, to be able to Ctrl+click (or something) on a particular step in the history stack to copy that module to the top of the stack with the settings as they were at that point in the history.

**Comment by difrkaguilar** [comment]
> It would be nice, therefore, to be able to Ctrl+click (or something) on a particular step in the history stack to copy that module to the top of the stack with the settings as they were at that point in the history.

Ctrl+Shift+drag as in the side panel when you want to arrange the modules up or down, thus maintaining consistency between the functions. That would be a good feature to add to the history.

**Comment by elstoc** [comment]
I'm not sure about that. I can't really see a use case for dropping it anywhere apart from the top of the stack, in which case drag+drop seems a bit much.

**Comment by TurboGit** [comment]
> I'm not sure about that. I can't really see a use case for dropping it anywhere apart from the top of the stack, in which case drag+drop seems a bit much.

I fully agree !

**Comment by difrkaguilar** [comment]
Ok, Ctrl+c (copy) will be the best option then to copy the parameters :-)

**Comment by elstoc** [comment]
Still prefer Ctrl+click.

**Comment by TurboGit** [comment]
Me too. ctrl+c is often (always?) intended to be used before a ctrl-v (paste). Here we want to duplicate a module state. And we already use similar shortcuts to move a module in the pipe for example.

**Comment by difrkaguilar** [comment]
Ctrl+click then. Because as I saw Shift+click has almost the same behavior of the FR #10003 I post before. By the way as it had almost the same behavior I'm going to close the #10003  [FR]
