### ISSUE TITLE
[FR] modulegroups - add new "in history" group

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10343]
I often find myself experimenting with a number of modules to get the result I want and I'm forever switching modules on and off as part of my experiments. I know that the "active" module group retains switched-off modules until it is next refreshed but I still find myself having to search or click through tabs to re-enable modules that I temporarily disabled a few steps ago.

I would therefore like to be able to replace the "active" module group with a new "in history" module group that displays all modules that are present in my history stack, regardless of whether or not they are currently enabled.

For maximum flexibility this should be offered "as well as" or "instead of" the active modules group, perhaps selectable in a combobox.

@AlicVB what do you think?

**Comment by elstoc** [comment]
An alternative (or addition) might be if one could Shift+click (or something) a module in the history stack to show/expand that module in the module panel.

**Comment by AlicVB** [comment]
if I understand well, you want the active module group to always show all modules present in the history stack, whatever its state. right ?
Why not... tbh the actual behavior is not really good either imho, as the presence of the disabled modules in the active group is not consistent across sessions. The main risk here is to finish with too many modules in the active group...

I'll have a look. hopefully it should not be too hard or too intrusive :)

for your second proposal, that would be great too, but I fear that it would imply way more change...

**Comment by elstoc** [comment]
> you want the active module group to always show all modules present in the history stack, whatever its state. right ?

That's what I would like, but I know there are others who prefer modules to disappear from the active group when disabled, so we'd definitely need to be able to retain the old behaviour too. The existing behaviour, where a module disappears only after you refresh the active group (by searching or switching between groups) is also preferred by some (to allow very temporary disabling of modules) so we should keep that behaviour. I think I tried to "fix" it in an earlier PR and was asked to put it back again.

> for your second proposal, that would be great too, but I fear that it would imply way more change...

That's what I thought.
