### ISSUE TITLE
Segfaults and slowness (also freezing) while using the retouch module

### ISSUE THREAD

**Issue by szymonlipinski** [darktable-org/darktable#10342]
**Introduction**

I was trying to retouch a photo today. I wanted to do some complicated stuff to remove many spots from a wall. I noticed a couple of things:

* sometimes when I was using a couple of shapes, darktable started to be quite slow
* sometimes it was not slow, but unresponsive
* sometimes I could add over one hundred of shapes and all was fine
* when I restarted a slow darktable, no shape was saved

Then I got the sources and compiled the program on my own. After fighting with the lensfun (yea, lots of fun) I managed to run it, but it didn't help and the situation repeated.

** Files **

Here are two files that Darktable created in my /tmp/ dir. I noticed them a couple of hours after they were made, so I'm not sure which action caused the segfaults.

[darktable_bt_HA3SC1.txt](https://github.com/darktable-org/darktable/files/7491159/darktable_bt_HA3SC1.txt)
[darktable_bt_VWOEC1.txt](https://github.com/darktable-org/darktable/files/7491160/darktable_bt_VWOEC1.txt)
 

**To Reproduce**

1. Get any image.
2. Start adding lots of shapes in the retouch model. The size and type seems to have no influence.
3. The errors are:
   - slowness
   - freezing
   - segfaults

**Platform**

* darktable version : 3.6.1
* OS                : Linux 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Linux - Distro    : Ubuntu 20.04
* Memory            : 32GB
* Graphics card     : GeForce GTX 965M
* Graphics driver   : NVIDIA 460.91.03
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 1.20.11  11.0
* Desktop           : KDE Plasma
* GTK+              : 3.24.20-0ubuntu1
* gcc               : gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by AlicVB** [comment]
@szymonlipinski : seems that you have skipped many points of the issue template... and especially in your case, some will be important to track down the root cause...
For example :
- can you precise the exact dt version you have ? (run `darktable --version`) you explain that you compile from source, but I'm not sure if it's master or not (and even in this case, the version is useful as the issue may be re-read by someone later)
- can you also precise the amount of memory you have ?

Thanks !

**Comment by szymonlipinski** [comment]
@AlicVB Yea, thanks. I've updated the information.

**Comment by Nilvus** [comment]
I don't have OpenCL and never had such issues with retouch. @szymonlipinski: is it possible for you to test with actual master (and test 3.6.1 and master ideally) with OpenCL deactivated? 

Other thing, could you post here (with a screenshot for example) your settings in process tab (cpu/gpu/memory part) in main preferences?

**Comment by szymonlipinski** [comment]
I have checked 3.6.1 and $HEAD versions. There is no difference in the speed.

This a sample picture with about 50 shapes. It's quite slow on both. Even when moving the picture, I wait 5-6 seconds to refresh the view with the retouched shapes.

I cannot see any difference between the OpenCL being switched on and off.



![Screenshot_20211107_113720](https://user-images.githubusercontent.com/292609/140641786-deaf51af-4ec1-48e1-b8c3-375ee2f3fc1b.png)

** Settings for 3.6.1: **

![Screenshot_20211107_113758](https://user-images.githubusercontent.com/292609/140641797-0f28f62e-a236-48bc-a160-f327d5bdd4d3.png)

** Settings for $HEAD *
![Screenshot_20211107_114147](https://user-images.githubusercontent.com/292609/140641806-11d72e4f-b617-4a4f-901a-c5a5681d7271.png)
*

When DT stars, it shows this:

```[defaults] found a 64-bit system with 32835332 kb ram and 8 cores (0 atom based)
[defaults] setting ultra high quality defaults
```
I'm building the $HEAD with with:

```
./build.sh --prefix /opt/darktable --build-type Release --enable-colord --enable-flickr
```

configuration shows:

```


-- The following features have been enabled:

 * OpenMP-based threading, used for parallelization of the library
 * XML reading, used for loading of data/cameras.xml
 * Lossy JPEG decoding, used for DNG Lossy JPEG compression decoding
 * ZLIB decoding, used for DNG Deflate compression decoding

-- The following OPTIONAL packages have been found:

 * LLVM (required version >= 10)
 * Gettext
 * XMLLINT, command line XML tool, <http://xmlsoft.org/>
   Used for validation of data/cameras.xml
 * LibSoup2
 * Gphoto2
 * OpenEXR
 * WebP (required version >= 0.3.0)
 * LensFun
 * OpenJPEG
 * IsoCodes (required version >= 3.66)
 * Libsecret
 * GraphicsMagick
 * ICU
 * OSMGpsMap
 * Colord
 * ColordGTK
 * Cups
 * X11

-- The following REQUIRED packages have been found:

 * Threads
 * OpenMP (required version >= 4.5), Open Multi-Processing, <https://www.openmp.org/>
   Used for parallelization of the library
 * GTK3 (required version >= 3.22)
 * Sqlite3 (required version >= 3.15)
 * GIO
 * GThread
 * GModule
 * PangoCairo
 * Rsvg2
 * LibXml2
 * ZLIB, software library used for data compression
   Used for decoding DNG Deflate compression
 * PNG
 * JPEG, free library for handling the JPEG image data format, implements a JPEG codec
   Used for decoding DNG Lossy JPEG compression
 * TIFF
 * LCMS2
 * JsonGlib
 * Exiv2 (required version >= 0.24)
 * Pugixml (required version >= 1.2), Light-weight, simple and fast XML parser, <http://pugixml.org/>
   Used for loading of data/cameras.xml
 * CURL (required version >= 7.56)
 * Glib

-- The following OPTIONAL packages have not been found:

 * libavif (required version >= 0.8.2)
 * libheif (required version >= 1.9.0)
 * GMIC
 * Lua54 (required version >= 5.4)
 * SDL2

```


Installed with:

```
sudo cmake --build "/home/szymon/Documents/projects/darktable/build" --target install -- -j8
```


Darktable data have been removed with: `rm -rf ~/.cache/darktable/ ~/.config/darktable/`


## 3.6.1

```$ darktable --version
this is darktable 3.6.1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```
## $HEAD version
```
this is darktable 604725a
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Comment by Nilvus** [comment]
Ok, I let now if a developer want/could answer that. Really precise feedback, thanks; Just a thing not related to this issue but flickr support had been removed some time ago (due to so frequent API changes by Flickr and difficulty to follow that for an open source software like darktable). So you could forget to use "--enable-flickr" in build command.

**Comment by szymonlipinski** [comment]
OK, thanks.
