### ISSUE TITLE
Flip options below type (setup guide lines) in modules with global guide overlay settings.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10352]
**Is your feature request related to a problem? Please describe.**
Modules that show the global configuration of the guide overlay (framing, crop, retouch, rotate and perspective, lens correction), the flip guides should be listed below the type (setup guide lines). If the flip option was a main modification for all other guide lines, then it would be perfect, because affects all guide lines, but this option is not general for all guide lines, in that case, the flip option should be listed under the type (setup guide lines).

For example: harmonic triangles can have the option to flip the guide lines as none, horizontally, vertically or both as all other guide lines, but this option only affects harmonic triangles. If users select the golden spiral, then the flipping options are different. In that case, for better layout and hierarchy, the flip options should be below the type (setup guide lines).

**Describe the solution you'd like**
User must set first the type of guide line to work with and then the flip options for this specific guide line type.

**Additional context**

![Screenshot from 2021-11-07 08-30-59](https://user-images.githubusercontent.com/67672868/140647192-c16441a2-e4dd-49dd-ad60-633e7ea348bf.png)

![Screenshot from 2021-11-07 08-30-31](https://user-images.githubusercontent.com/67672868/140647202-fa5f0a16-8f7d-4b0c-b04a-1f756c49a157.png)

**Comment by elstoc** [comment]
@AlicVB can you look at this please

**Comment by AlicVB** [comment]
in fact, this have been done on purpose (and you can see that other guides options are shown on top too) :
The idea is that when you change the guide, the guides combobox need to stay at the same place, otherwise you will have strange and unwanted effect, not too speak about the gui jumping feeling...
I agree that it's not ideal, but it's the best compromise we have found...

**Comment by difrkaguilar** [comment]
> I agree that it's not ideal, but it's the best compromise we have found...

Ok, if there isn't other way, I close this issue. I saw that in fact it is difficult to got an ideal solution.
