### ISSUE TITLE
Segfault when using -t 20

### ISSUE THREAD

**Issue by szymonlipinski** [darktable-org/darktable#10350]
I always get segfault when I run `darktable -t 20`. Changing the number doesn't help. Only small values up to 5 are fine.

The problem appears in lighttable when showing a miniature of a picture with 20 retouch shapes. Other pictures are fine.

Platform

    darktable version : $HEAD
    OS : Linux 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    Linux - Distro : Ubuntu 20.04
    Memory : 32GB
    Graphics card : GeForce GTX 965M
    Graphics driver : NVIDIA 460.91.03
    OpenCL installed : yes
    OpenCL activated : no
    Xorg : 1.20.11 11.0
    Desktop : KDE Plasma
    GTK+ : 3.24.20-0ubuntu1
    gcc : gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
    

```
$ /opt/darktable/bin/darktable --version
this is darktable 604725a
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support disabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

Built with:

```
./build.sh --prefix /opt/darktable --build-type Release --enable-colord -disable-opencl
```

**Comment by ralfbrown** [comment]
How many cores/threads does your CPU have?  I don't have any problems with -t 32 or even -t 64 on a 32C/64T ThreadRipper.
Please provide a backtrace (/tmp/darktable_bt_*.txt) and a sidecar .xmp file which causes a crash.  Even better if you can also share the image.
