### ISSUE TITLE
Rawspeed generates Wfatal-errors 

### ISSUE THREAD

**Issue by 01McAc** [darktable-org/darktable#10354]
commit:  6d4ebebf95b11001812f3c3488dbae9f99513c2d
Distribution: Fedora
During the compilation rawspeed throws an error with the following error message:
[ 14%] Built target rawspeed
[ 14%] Building CXX object bin/CMakeFiles/lib_darktable_imageio_rawspeed.dir/common/imageio_rawspeed.cc.o
/home/det/darktable/src/common/imageio_rawspeed.cc: In Funktion »dt_imageio_retval_t dt_imageio_open_rawspeed(dt_image_t*, const char*, dt_mipmap_buffer_t*)«:
/home/det/darktable/src/common/imageio_rawspeed.cc:25:36: Fehler: »F32« ist kein Element von »rawspeed::RawImageType«
   25 | #define TYPE_FLOAT32 RawImageType::F32
      |                                    ^~~
/home/det/darktable/src/common/imageio_rawspeed.cc:238:28: Anmerkung: bei Substitution des Makros »TYPE_FLOAT32«
  238 |     if(r->getDataType() == TYPE_FLOAT32)
      |                            ^~~~~~~~~~~~
Kompilierung wegen »-Wfatal-errors« beendet.
make[2]: *** [bin/CMakeFiles/lib_darktable_imageio_rawspeed.dir/build.make:76: bin/CMakeFiles/lib_darktable_imageio_rawspeed.dir/common/imageio_rawspeed.cc.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:2400: bin/CMakeFiles/lib_darktable_imageio_rawspeed.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2

**Comment by Nilvus** [comment]
Did you clean your build before building again? There was a rawspeed update with error and fixed now (before commit you posted). I compiled same commit correctly. Please remove build folder before each compile (and also destination folder) to be sure all is clean.

**Comment by TurboGit** [comment]
You need to update the rawspeed submodule.

**Comment by TurboGit** [comment]
Also better to send output in English.
