### ISSUE TITLE
[FR] Save custom sort order of images

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#10368]
**Problem**
I love the feature "images order aware tags" (#5134)

My problem is, that the manually defined order gets lost quite easily:
- rename the tag with lua-script "rename-tags" (because in fact it generates a new tagid)
- reinstall darktable (because the position is only saved in library.db)

**Solution**
- migrate the existing sort-order in the lua-script "rename-tags"
- save sort order in xmp-file

**Alternative**
export + import sort order (analog to export tags to .txt)

**Comment by phweyland** [comment]
>  rename the tag with lua-script "rename-tags" (because in fact it generates a new tagid)

I don't know enough lua to be sure, but this should be relatively easy to fix. Instead of deleting the tag and creating it again with the new name, it should be possible to just change its name (and keep the tagid). 

> reinstall darktable (because the position is only saved in library.db)
> save sort order in xmp-file

I think this cannot work  as an xmp file knows only the corresponding image (and nothing else).

> export + import sort order (analog to export tags to .txt)

This sounds better but it remains some constraints to identify the images, this feature being based on an ordered list of images associated to a given tag. Their path may not be enough. Duplicates may be an issue too.
Not easy. Activate the sha1sum and use it to identify the images wherever they are stored ? May be time consuming and doesn't solve the duplicates point.

**Comment by quovadit** [comment]
I don't think, that the xmp file has to know anything about other images.
It should just include tagid and position (as in library.db - tagged_images)

**Comment by phweyland** [comment]
> It should just include tagid and position (as in library.db - tagged_images)

That's even worse. That turns the xmp not sharable with others. And in case of db rebuild it won't work neither.

**Comment by quovadit** [comment]
ok, understood.

So for export/import: wouldn't it enough to export tag-name, path+filename and sequence?
If the user changes tag/filename, he has to export the sequence again

**Comment by phweyland** [comment]
Seems to be a good start.

The tag keeps the type of order and in case of custom order, tagged_images keeps the position. This position could not be not usable for export/import as is, because it is db dependent. But I may be wrong on this.

Saving the version number could help to solve the case of duplicates.

**Comment by phweyland** [comment]
@wpferguson 
Looking at one part of this issue (rename-tags actually deletes and recreates the tag, loosing the tag's properties) we should add the darktable lua api darktable.tags.rename. This should be done in lua/tags.c. 

In dt_lua_init_tags() some routines are declared twice (delete, attach and detach). Could you tell me why ?
Is there another place, apart lua/tags.c) where I should modify something to make it work ?
In parallel, the lua script rename-tags.lua should be updated to use the new api.

**Comment by wpferguson** [comment]
> we should add the darktable lua api darktable.tags.rename

Agree.  I actually thought I already had, but I must have dreamed it.

> In dt_lua_init_tags() some routines are declared twice (delete, attach and detach). Could you tell me why ?

There are functions you can preform on tags, but there is also tag as an object that has properties and functions attached.  That's from a quick look at the code.  I need to play with it a little bit and make sure that is correct.  I think that all my additions to the tag api have been just applied to the object.  I may need to go back and look at it to see if any should also be applied to tags as a whole.

>  Is there another place, apart lua/tags.c) where I should modify something to make it work ?

No, lua/tags.c is the correct place.

> In parallel, the lua script rename-tags.lua should be updated to use the new api.

Agree

**Comment by phweyland** [comment]
> ename the tag with lua-script "rename-tags" (because in fact it generates a new tagid)

Could you explain why you prefer to use the script than the core rename (edit) feature ?

**Comment by quovadit** [comment]
> Could you explain why you prefer to use the script than the core rename (edit) feature ?

using lua I can rename the complete path at once, the core rename feature only renames one hierarchy-element after the other, with lots of images every step takes quite long...

**Comment by phweyland** [comment]
> using lua I can rename the complete path at once

Can you give an example ?

**Comment by quovadit** [comment]
I had images tagged with Notiz|sonstiges and changed it to Memo|misc

So instead of editing Notiz and then editing sonstiges, I just entered:
old tag: Notiz|sonstiges
new tag: Memo|misc

**Comment by phweyland** [comment]
Can't you do the same with:
![image](https://user-images.githubusercontent.com/23012047/147288567-31ac0864-50e7-4d01-8511-71cba00ce644.png)
?

**Comment by quovadit** [comment]
oh, sh,,,, you're right, I'm soo sorry

**Comment by phweyland** [comment]
Don't worry. I wanted to be sure before cancelling my changes for contrib/rename-tags (some work, and duplicated code, to treat properly the different cases).
Thanks.
