### ISSUE TITLE
Compiler crash in exif.cc when compiling against exiv2 0.27.5

### ISSUE THREAD

**Issue by BodoHobbit** [darktable-org/darktable#10369]
**Introduction**
Having Exiv2 0.27.5 installed on my system,building of darktable crashes.

**Describe the bug/issue**
When having Exiv2 0.27.5 installed on my system, building of darktable crashes when compiling common/exif.cc

Error occurs in line 3790: xmpPacket.assign(reinterpret_cast<char *>(buf.pData_), buf.size_);

With Exiv2 0.27.5 "pData_" and "size_" are private members of DataBuf.

**To Reproduce**
Install Exiv 0.27.5 on your system, get darktable from github and start building.

**Expected behavior**
No crassh while building against latest Exiv2 lib.

**Which commit introduced the error**
To be honest, issue is not introduced by a darktable commit, but related to a change in the implementation of the Exiv2 library.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

When compiling against Exiv2 0.27.4 issue does not occur and this is the output I got from my system:

bodo@debian:~/Packages/darktable/build/bin$ ./darktable --version
this is darktable 604725a-dirty
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

* darktable version : 604725a-dirty
* OS                : Linux debian 5.10.0-9-amd64
* Linux - Distro    : Debian GNU/Linux 11 (bullseye)
* Memory            : 16GB

Build started according to instruction under github:
mkdir build/
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable/ ..
make
sudo make install

**Additional context**
Used rawspeed from branch canon_cr3 in order to enable Canon CR support.

**Comment by piratenpanda** [comment]
works fine on arch
