### ISSUE TITLE
Graphic Interference while editing 

### ISSUE THREAD

**Issue by Sackem2** [darktable-org/darktable#10372]
I just recently downloaded dark table for a school project, however I am also planning on using it to begin my own photography journey. However, I am getting this weird Graphic bug when I try to edit my images. When I change a value using a slider, I get this interference over my images at random points in the range of the value. For example, if I set exposure to 0.63 EV the interference is there, but as soon as I bump it up to 0.68 It returns. If I move the slider again, even back down to 0.63 EV, the interference is gone. If I use a different slider to alter a different value, Let's say the interference is there and exposure is at 0.63 EV, as soon as I change a different value, let's say I change the black leve correction, it then will go away. If I grab any slider and move it it's full range the interference comes and goes over seemingly random intervals. 
I have tried to delete and reinstall the program multiple times
I am using an ROG Zephyrus Gaming Laptop with a Ryzen 7, a GTX 1660, and 16 gig ram so I know its not a processing power issue. 
If the interference is shown in Darktable, but I export the image anyway, the image is stored in my pc as I have edited it and without the interference so I know its simply a UI issue. 
I have looked in settings and couldn't find anything. 
I am stumped and I really need to get this working for my project. I had my instructor help with troubleshooting but we weren't able to solve it. 
Screenshot attached of interference. 
![Dark Table Glitch ](https://user-images.githubusercontent.com/94024543/141030172-7244061b-4ed1-4c4e-983f-e78f511b9a83.png)
Any advice would be helpfull.

**Comment by parafin** [comment]
Looks like OpenCL issue. Try disabling it in preferences and/or updating your graphics drivers.

**Comment by dterrahe** [comment]
Did the suggestions help at all to solve this problem? If it is no longer an issue, please consider closing this so the devs can easier find things that do need work.
