### ISSUE TITLE
Scroll shortcuts don't work with touchpad scroll

### ISSUE THREAD

**Issue by robMate** [darktable-org/darktable#10385]
**Description**
Shortcuts with scrolling don't work on my laptop touchpad, like e+scroll.
I added the shortcut e+scroll to the exposure slider, and it works fine with my mouse scroll wheel but not when I scroll with the  touchpad (two fingers vertical slide up or down). I defined the shortcut with the mouse scroll wheel, but it is also not possible to define the shortcut with a touchpad scroll 

**To Reproduce**
1. Inside the darkroom click on "define shortcut"
    ![Bildschirmfoto vom 2021-11-10 23-18-24](https://user-images.githubusercontent.com/5657121/141203715-28c98fdd-ae3c-4f96-aa10-3afcb723d3d1.png)
2. Hover over the exposure slider inside a exposure module and press e and scroll with the mouse wheel to set a shortcut.
3. Hover with the mouse courser over an opened image in the darkroom view press e and scroll with the mouse wheel. The exposure should change
4. Now press e again and scroll with the touchpad (two fingers vertical swipe up or down) -> nothing happens 

**Expected behavior**
The configured shortcut should change the exposure 

**Platform**

* darktable version : 3.7.0+1412~g6a22928a9
* OS                : 5.13.19-2-MANJARO
* Linux - Distro    : Manjaro
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              :  Wayland 1.19
* Desktop           :  Gnome 40.4
* GTK+              :  4
* build options?  : ./build.sh --prefix /opt/darktable --build-type Release --install --sudo

**Additional context**
I also tested the behavior with the option "mouse wheel scrolls modules side panel by default" but this changed nothing.
Everywhere else in darktable a touchpad scroll works fine, like zooming & scrolling.

**Comment by dterrahe** [comment]
It seems (from a quick google search) that maybe Manjaro, in its default setup,  disables the touchpad while typing (to avoid accidental clicks). This could cause the behavior you are describing.

Please let us know if the suggested remedy below works for you:
https://forum.manjaro.org/t/howto-enable-touchpad-while-typing-in-manjaro-xfce/70925

**Comment by robMate** [comment]
Yes you're right, this was the problem. I should have checked that first.
In Gnome Settings exists the option "Mouse and Touchpad -> Disable while typing" which solved the "issue".

Thanks for taking the time.
Best Regards

**Comment by dterrahe** [comment]
@elstoc this issue and solution could be useful to mention as a footnote in the documentation?

**Comment by elstoc** [comment]
done: https://github.com/darktable-org/dtdocs/commit/e841b10cfec887dac510214d154f0c0a250696a0
