### ISSUE TITLE
go to main "film roll" from lighttable

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#10382]
**Is your feature request related to a problem? Please describe.**
No a problem per se, but when I select a criteria on the collect module I have some images displayed. When I found one interesting I often want to go to the actual film roll it belongs too. Why? Because I have not found the image I wanted but I know that it is part of the series.

**Describe the solution you'd like**
Have a way from thumbnail to "jump" to the film-roll containing the picture.

**Comment by elstoc** [comment]
You can already do this. Double-click on the film roll in the image information module.

**Comment by TurboGit** [comment]
@elstoc : I completely missed that! Shame on me, I should consider reading the doc again :)

Anyway, sorry for the noise!

**Comment by elstoc** [comment]
I only noticed it after seeing your suggestion. I was thinking "where would I put this feature if I were to build it... oh there it is"
