### ISSUE TITLE
Problem with export "Subject Distance" exif tag

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#10399]
Hello.

My RAWs have a "Focus Distance" tag

```
~/temp$ exiftool 20211016__DSC5125.NEF | grep Distance
Focus Distance                  : 3.16 m
```
![image_src](https://user-images.githubusercontent.com/15331117/141645952-e6277883-a365-42e8-9db0-07ed246ee894.png)

I am trying to use it as a value for  "Subject Distance" exported exif tag.
![pref1](https://user-images.githubusercontent.com/15331117/141646284-1f4a0b09-c3e0-46da-9d80-1b5293c22da8.png)

There is no value in the resulting jpeg
```
~/temp$ exiftool 20211016__DSC5125.jpg | grep Subject
Subject Distance                :  m
Subject Distance Range          : Unknown

~/temp$ exiftool 20211016__DSC5125.jpg | grep 'Lens Model'
Lens Model                      : Tamron SP AF 150-600mm F/5-6.3 VC USD G2
```

If I specify variable _$(EXIF_FOCUS_DISTANCE)_ as the value for "Lens Model" exif tag
![pref2](https://user-images.githubusercontent.com/15331117/141646547-b15dc869-6e21-4977-bd68-584cacc432ca.png)

then it is exported to this tag.
```
~/temp$ exiftool 20211016__DSC5125_01.jpg | grep 'Lens Model'
Lens Model                      : 3.16

~/temp$ exiftool 20211016__DSC5125_01.jpg | grep Subject
Subject Distance                :  m
Subject Distance Range          : Unknown

```

darktable version: master
OS:  Debian 11 /  Windows 7

**Comment by phweyland** [comment]
Could you try to use exiv2 instead of exiftool please?
Something like:
`exiv2 -PEX | grep Distance <file>`

**Comment by esq4** [comment]
The result is the same.

**Comment by phweyland** [comment]
Thanks

**Comment by kmilos** [comment]
Need to check, but could be because a RATIONAL is expected for this tag, not sure if exiv2 can set it directly... Can you e.g. set other RATIONAL tags like FNumber or Exposure time via a float value?

**Comment by phweyland** [comment]
> Need to check, but could be because a RATIONAL is expected for this tag,

That's the issue, you are right.

**Comment by esq4** [comment]
I set the value manually (888/10) and the export was successful.
