### ISSUE TITLE
culling independent zoom broken

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#10396]
**Describe the bug/issue**

In culling mode the synchronized zoom works (ctrl+scroll) but the independent zoom does not ctrl+shift+scroll.  

(found during a teaching session, I can give more info if needed later)

**Comment by TurboGit** [comment]
Documented here: https://docs.darktable.org/usermanual/3.6/lighttable/lighttable-modes/culling/#controls

**Comment by TurboGit** [comment]
@dterrahe @AlicVB maybe one of you can have a look? I suspect maybe an issue with InputNG.

**Comment by dterrahe** [comment]
@TurboGit Was this working for you in 3.6.1? For me, in both 3.6.1 and 3.7, shift+drag _does_ work on just one image, but shift+(ctrl+scroll) does _not_ zoom one image but instead acts like a normal scroll, i.e. scrolls through the image collection.

If this is correct, the bug predates inputng (or might instead need a slight documentation clarification).

**Comment by TurboGit** [comment]
@dterrahe : You're correct this also happens in 3.6.1 ! So not an InputNG regression. Maybe @AlicVB will shed some light on this.

**Comment by AlicVB** [comment]
yes, I can reproduce, and I know where it comes from... just need 5 minutes of free and quiet time to do the PR ;) (certainly before the evening)
