### ISSUE TITLE
Histogram Bleeding out of area

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#10391]
The attached image illustrates the problem:
The histogram does not appear to be fully contained withing the outline box.
I have tried to make the box larger (Ctrl + Scroll) but it appears that I am at a maximum size (even though it is not so large).
The problem may be caused by my use of a '4K.' screen. I did not see this problem with an earlier lower res display.
dt == 3.7.0+1227~g3362b98e75
Manjaro/Arch .. XFCE ... OpenCL is active .... all updated currently.

![Histogram](https://user-images.githubusercontent.com/6267270/141407562-2990b9dd-76e5-437d-93c8-b239d859e0ca.jpg)

**Comment by MStraeten** [comment]
what's your histogram color space? it seems the image content makes use of colors exceeding your histogram color space

**Comment by davidvj** [comment]
It was set at AdobeRGB .... I have now retset it to sRGB ans see if that 
makes a difference. I question whether is should be set for the typical 
output or for the REC-2020 processing.

The problem is not seen on all RAW images and I start to wonder if some 
combination of processing is the cause.

**Comment by aurelienpierre** [comment]
Histogram takes the image in display space (typically sRGB, or custom if you calibrate your monitor) and converts it to "histogram space". Meaning that if gamut clipping happens in display space, the clipping will also be shown in the histogram, but maybe not at the bounds. The safest space for histogram profile is the same as display for this reason.

**Comment by davidvj** [comment]
Have not seen this problem again
