### ISSUE TITLE
[FR] Do we need to get rid of the unix time limitations ?

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#10398]
**Is your feature request related to a problem? Please describe.**

Geotagging, as discussed  in [darktable-dev](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06481.html) and fixed with PR #10395, can now work with every datetime between the years 0001 and 9999.

Remains that importing image exif time is still limited by unix epoch 0 system time. In other words, if the image exif time is before 1970 something gets wrong.
Date based variables (like $(EXIF_YEAR), ...) suffer the same limitation. So even if one can set an image date before 1970, I doubt that $(EXIF_YEAR) would be correct.

Changing this is probably a consistent piece of work. So it would be interesting to get some feedback from the community to better understand the PROs and CONs.

Not to make the work several times, it could be the opportunity for improving the time accuracy as well.
Moving from Unix tm structure and time_t to GDateTime and GTimeSpan not only enlarges the years domain but also increases the time accuracy from second to microsecond.

We may not need to manage microseconds but milliseconds would help to rename properly images taken in burst mode (through a variable as $(EXIF_MSEC)).

Thoughts ?

**Comment by phweyland** [comment]
I copy here part of the Peter's contribution on darktable-dev:

here are the results of the pending tests :

darkroom -> pattern for image information line :

$(EXIF_DAY).$(EXIF_MONTH).$(EXIF_YEAR)    •   $(EXIF_HOUR):$(EXIF_MINUTE):$(EXIF_SECOND)   •   $(FILE_NAME)   •   $(MAKER) $(MODEL)   •   $(LENS)   •   $(EXIF_EXPOSURE) s   •   f/$(EXIF_APERTURE)   •   $(EXIF_FOCAL_LENGTH) mm   •   ISO $(EXIF_ISO)   •   Sterne: $(RATING_ICONS)   •   Breite/Höhe: $(SENSOR_WIDTH) x $(SENSOR_HEIGHT) px   •   Crop: $(CROP_WIDTH) x $(CROP_HEIGHT) px   •   OpenCL : $(OPENCL_ACTIVATED)

gives the result shown in the attached screenshot.

ligthtable -> export to .../
$(EXIF_YEAR)/$(ROLL_NAME)/$(SEQUENCE)-$(FILE_NAME)
is working as expected, folder "1961" correctly created
checked exif information of exported jpeg : "DateTimeOriginal" is correct, modifications done with geotagging module correctly considered

so for me it looks like there are no more issues. I support your idea to introduce a variable $(EXIF_MSEC) for the use case of images taken in burst mode. I agree with you that considering microseconds is not necessary.

**Comment by johnny-bit** [comment]
Judging by  #3163 people would love SUBSEC or MSEC (me too) :)

**Comment by ptilopteri** [comment]
yes, please

**Comment by phweyland** [comment]
today dt `datetime` = exif `datetime` (without milliseconds).

I see two ways to manage milliseconds using g_date_time model
1. extends dt datetime to milliseconds.
  - breaks the correspondence with exif
  - breaks sscanf, strftime, ... 
  - compatible with GPX
  - uses the same variables/fields including in db as today
  - compatible with gpx files
  - one off change ?
  - a variation of this would be to keep internally a numerical value (GTimeSpan ?) instead of the datetime string.
 2. uses a msec extension as exif does
  - adds one field to manage msec, including in images table
  - could be implemented only where necessary: gpx files, images ordering,  $(EXIF_MSEC), ?, ...
  - keeps different datetime models inside dt
 
Thoughts ?

**Comment by johnny-bit** [comment]
It's a feature that would be GREAT to have, but it does seem that much of a problem so... whichever solution is "better" :)

**Comment by phweyland** [comment]
As a first step I'll try to encapsulate all accesses to datetime, inside common/datetime.c file.
Once this done, if happens, it should be easier to add msec where needed.
