### ISSUE TITLE
denoise (profiled) module posterizes image

### ISSUE THREAD

**Issue by dmitryash** [darktable-org/darktable#10405]
**Describe the bug/issue**

Looks like profiled denoise with default parameters breaks image on export. 

Example of sky without denoise:

![no-denoise](https://user-images.githubusercontent.com/1093437/141654713-7ad3a57e-72d8-4e1a-a502-e54347e3b2d3.png)

Example of sky with denoise module enabled:

![with-denoise](https://user-images.githubusercontent.com/1093437/141654721-e0f5a81f-fa35-4e8d-899e-1e68fec7f58c.png)

I didn't see such effect for previous darktable version (maybe it was 3.2). Also I cannot see this issue in darktable darkroom, only after export. It may be related to "preserve shadows" parameter because if its value is lowered much then issue disappears.

**To Reproduce**

1. Use image with blue sky
2. Enable profiled denoise module
3. Export image with 100% quality
4. See posterization effect (it may be difficult to see, but other modules may make the issue visible)

**Expected behavior**

No posterization effect if it is a bug. If it is not the bug (why I can't see the issue in darkroom?) then it may worth tweaking a default for "preserve shadows" parameter.

**Platform**

this is darktable 3.6.1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled (but explicitly disabled in options)
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

Distro: openSuSE 15.3, updated darktable from graphics:darktable repository

**Comment by rawfiner** [comment]
What happens if you enable dithering?

**Comment by aurelienpierre** [comment]
Posterization cannot happen __inside__ darktable's pipeline since it's 32 bits floating point. It may happen on smooth surfaces during export and encoding to 8 bits, possibly with a JPEG quality set too low. The culprit is simply a very smooth surface, which means denoising did its job properly.

You may use higher JPEG quality at encoding and the dithering module to alleviate this.

**Comment by dmitryash** [comment]
let me play with it a bit
