### ISSUE TITLE
details threshold available for drawn masks

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10423]
Something I've only just noticed - it appears that the details threshold slider is available (and functional) when selecting only "drawn mask". Since this is a parametric slider, it really should only be available when selecting "parametric" or "drawn and parametric".

Or is there a technical reason it was developed this way?

**Comment by jenshannoschwalm** [comment]
Not a technical reason, I just did it this way as I wanted it to be available for drawn too.

**Comment by elstoc** [comment]
Shouldn't that be done by selecting "drawn and parametric"?

**Comment by jenshannoschwalm** [comment]
Maybe I don't understand you correctly but imho this is another  "mask refinement" so it can and should be enabled for **all** kinds of masks. I personally use it with simple  drawn masks quite a lot.

**Comment by elstoc** [comment]
I suppose it's a question of terminology. I quite often "refine" a drawn mask with a luminosity mask but really (in darktable terminology) that's the superposition (union) of two different types of mask, a "drawn" (based on a shape) mask and a "parametric" (based on some properties of the pixels) mask. 

I just would have expected the details threshold to fit into the latter category and sit with the parametric controls rather than the refinement controls, which are generally are used to modify the existing (drawn and/or parametric) mask in other non-trivial ways (to make the mask follow features in the image or blur, for example).

It's not a massive deal tbh but it just surprised me when I saw it when selecting drawn mask.

**Comment by elstoc** [comment]
Since nobody seems to have an issue with this, I'll close
