### ISSUE TITLE
Retouch module: unexpected result when template area falls outside of cropped area

### ISSUE THREAD

**Issue by RobOo-Github** [darktable-org/darktable#10421]
Darktable 3.6.1-1 Debian

Issue: 

Select an area to be retouched. Drag the template for retouching into a corner of the image, and see the retouch magic at work (in this case a roof section that is removed).  (1.png)
![1](https://user-images.githubusercontent.com/65445647/141797530-0aeeedf1-007c-4b86-9f0d-4de98052c4a8.png)

Now crop the image in such a way that the template area falls outside of the cropped area. The retouching disappears (the roof is back). (2.png)

![2](https://user-images.githubusercontent.com/65445647/141797710-df242879-b1da-4766-8a41-914cd2f332e3.png)

I believe this is not correct. The retouching should stay effective.

If I remember correctly,  this same bug happened in an earlier version of Darktable too, but I cannot find that bug report again.

**Comment by RobOo-Github** [comment]
Thanks for that comment, elstoc. I see what you mean, and what you suggest is perfectly workable.

**Comment by elstoc** [comment]
So this can be closed?

**Comment by RobOo-Github** [comment]
I'm good with that.
Looking forward to the 3.8 Christmas present already !
