### ISSUE TITLE
FR: Magic Lasso selection, like Gimp

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#10439]
**Is your feature request related to a problem? Please describe.**

I often want to increase separation between a subject and the background.
The filters are excellent! But the hard part is limiting the filter to the subject.
Drawn masks are very labour-intensive and not always accurate; parametric masks are brilliant but very, very technical:  It is not always obvious which channel yields the best results.  My masks often leave open pixels or blotches.

**Describe the solution you'd like**

I would like a lasso tool, like Gimp has.  When you click somewhere, all pixels that are somewhat similar in color are added to the selection. 
It is very easy to see which parts have not been added; and CTRL-click to add those as well.
Growing and shrinking the selected area by 1 pixel is the cherry on the cake.
I would still like to keep the fuzzy border please! 

**Alternatives**

I use a combination of parametric and drawn masks, I accept the imperfections, I use a large fuzzy border... but often I give up.

**Additional context**

I refer to Gimp here which in turn is ispired by Photoshop.
I know Darktable is not a photoshop program but in 99% of all cases (Retouch is my no. 1!!)  it has everything I need - I have little need to go to other programs.

**Comment by MStraeten** [comment]
combination of drawn and parametric mask ist excatly the solution for this - and in combination with the control sliders this often gives dramatically better results then magic lasso in gimp.
You‘d better use a combination of parameters if hue is not enough - and depending on your edit you can also use the result to finetune the affected parts of the image.

**Comment by rekcodocker** [comment]
> 

I thought about this for a while, as I do really think that my opinion is just as a user. 

Let me suggest an analogy.   
Suppose that DT would allow a selection by selecting single pixels (and even an alpha-level per pixel).  This is the ultimate control - you can not get more control over the selection than by individual pixels. 
You would get 100% perfect results.

However, the problem then becomes usability. Total control leads to a completely unusable interface and no-one would use it. 

/end of analogy. 

These choices (by developers) are often based on unspoken assumptions: The assumption that users need perfect results or maximum control, for instance. 
Or perhaps: The selection should be perfect with a minimum number of clicks. Or: It should be right the first time.
Those are assumptions and they are personal - they need not be universal.

Personally, I find the lasso tool incredibly powerful: if it selects too much, I tune it down a little. If it selects too little, I can add parts to the selection, or grow the selection by a few pixels.   Obviously, it is also based on parametrics, but it shields the user from controlling the smallest details. 
Yes, it does sometimes not select everything in a single click. But because the UI is so fast and smooth and interactive, I can very quickly build up to the selection that I need.   
More finegrained control is not always the best answer - see the analogy with single pixel control which no sane person would want.
The fast userfriendly interface compensates for the imperfections of the algorithms - it's a different balance, and a very powerful solution.

I'd love to have the option.

**Comment by MStraeten** [comment]
did you check the combination of drawn masks and parametric masks? And that in combination with mask refining controls?
I doubt that this doesn't give better control ...

Otherwise you need to specify the behaviour of lasso in detail ("like gimp" is no specification)

**Comment by rickprice** [comment]
I would like this feature as well, I believe the parametric mask affects the entire selection, not just the edges. This makes it extremely difficult to fix windows that you would select with a line mask and refine with parametrics, because the window frame can be similar (in brightness and hue) to what is in the Window when the frames are white.

I use this to reduce exposure on windows so they don't get blown out compared to the inside of a room in architectural photos 

I'm a programmer, I would be happy to implement the feature if given help.

I don't want to use Gimp, I want to keep all my editing inside DarkTable.

**Comment by rickprice** [comment]
I think the feathering feature can get you a long way towards where you need to go as well.

**Comment by MStraeten** [comment]
First think about a specification since darktable isn’t designed to deal with pixel based masks …
So it’s not just implementing a feature …
