### ISSUE TITLE
Vectorscope: small glitch

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#10433]
**Describe the bug/issue**

Working on PR #9904 / #9847 using an RGB image reference ([here](https://github.com/darktable-org/darktable/issues/9847#issuecomment-903315980)),

the different scopes were the followings:
JzAzBz:
![image](https://user-images.githubusercontent.com/23012047/142262582-e1fd26da-98aa-4592-a890-0c997a497f81.png)
RYB:
![image](https://user-images.githubusercontent.com/23012047/142262819-f7d2afe5-bda8-4f3e-abf6-944e3a3131d1.png)

And now we have:

JzAzBz:
![image](https://user-images.githubusercontent.com/23012047/142263095-1a982e3e-d472-4568-9178-f79a7f39693a.png)
RYB:
![image](https://user-images.githubusercontent.com/23012047/142263170-6ea17daf-2e9b-40b0-aefb-130bca5fe805.png)
CIELuv:
![image](https://user-images.githubusercontent.com/23012047/142263572-391b5451-a5b8-41d7-a3e9-fc16972828d8.png)

Note the black zone on the upper right border of the graph.

**To Reproduce**
Use the image given by @dtorop [here](https://github.com/darktable-org/darktable/issues/9847#issuecomment-903315980):

**Platform**

* darktable version : 3.7.0+1502~g68c8e3a8f
* OS                :  Debian sid
* OpenCL activated  : With and without

EDIT: Tried to bisect but I get a compilation error on imageio_rawspeed.cc

**Comment by dtorop** [comment]
This seems to depend on the histogram profile. If it's sRGB or linear Rec709 RGB, everything is fine. Any other of the built-in profiles shows this bug.

Weirder still, if I go into colorin iop and change the input profile (based on the test image above) from "embedded ICC" to "Lab", then to "sRGB", things go really awry. The center view image looks OK, but the preview is very strange:

![image](https://user-images.githubusercontent.com/2311860/143669573-e3af0ce2-c567-4f17-9493-19a8484f073e.png)

As (presumably correspondingly) is the vectorscope:

![image](https://user-images.githubusercontent.com/2311860/143669640-d9cfc258-f79f-49d5-964e-527113dd588f.png)

Restarting darktable returns things to a more normal state.

I haven't done any bisect work on this.

**Comment by phweyland** [comment]
> This seems to depend on the histogram profile. If it's sRGB or linear Rec709 RGB, everything is fine. 

Interesting, I don't get the same symptoms. The test image, covering an sRGB profile, should fulfill the sRGB circle in histogram, while it will cover only a part of the rec2020 histogram, if I'm not mistaken... 

sRGB:
![image](https://user-images.githubusercontent.com/23012047/143677672-8123d7e2-50fa-47bf-9ccc-f3daf7ff19a8.png)
linear Rec709 RGB:
![image](https://user-images.githubusercontent.com/23012047/143677643-d77cbbbc-8098-4520-b6f9-0be23205e2a4.png)
linear Rec2020 RGB:
![image](https://user-images.githubusercontent.com/23012047/143678188-cf23f330-f08c-49b1-be42-db69980b02f8.png)

NB1 activating soft proofing makes the histogram switch to soft proofing profile. Is that expected ?
NB2 I don't succeed in reproducing the input profile issue you describe.

**Comment by dtorop** [comment]
Hmm...

> activating soft proofing makes the histogram switch to soft proofing profile (EDIT idem for gamut check). Is that expected ?

This is. Operative code is here:

https://github.com/darktable-org/darktable/blob/aa8d21483df7556127602c84c3cbfa3baac83f33/src/common/iop_profile.c#L1032-L1037

I've never been sure it's the right behavior, but it is long-standing (at least since 575823d56763ac55aa9f039140df5a2287b009fb).

> I don't succeed in reproducing the input profile issue you describe.

I got this initially by flipping around histogram profile and colorin input profile, but steps I wrote above now can reproduce it reliably. It doesn't matter if vectorscope is in CIELub, JzAZBz or RYB. I'm wondering if it's something weird (overflow?) handling out of bounds Lab values which only occurs in the preview pixelpipe.

> I don't get the same symptoms.

Probably worth bisecting at this point -- or otherwise generally spending a bit more time on it. I'll write if I get anywhere.

I'm also seeing other weird things over here -- reds in images suddenly looking over-saturated with known good image histories. I don't see any recent commits which should have caused any of this.

**Comment by phweyland** [comment]
> I'm wondering if it's something weird (overflow?) handling out of bounds Lab values which only occurs in the preview pixelpipe.

Not sure this can be related but lgtm warns some possible overflow operations [here](https://lgtm.com/projects/g/darktable-org/darktable?mode=tree&ruleFocus=2157860313).

**Comment by phweyland** [comment]
dt 3.6.1 already has the issue (new db, just imported your test image):
![image](https://user-images.githubusercontent.com/23012047/143689967-b6b280da-508f-41f9-8dd1-325079831e5f.png)

I don't know why I did not see that when I've worked on RYB...

**Comment by dtorop** [comment]
> I don't know why I did not see that when I've worked on RYB...

Yes, this is a mystery. Hard to imagine I wouldn't have noticed this when working on CIELuv or JzAzBz.

Here's another test. I took a test image with the RGB primaries/secondaries and black and white in sRGB. Each of them is sampled. The results look ok, yes?

![image](https://user-images.githubusercontent.com/2311860/143730328-069b500e-f309-4bda-836e-66d3b5c83b28.png)

Here is the test image:

![primaries secondaries black white 600x300](https://user-images.githubusercontent.com/2311860/143730295-5959bfea-869f-454e-b6b4-201f80bc28d9.png)

**Comment by dtorop** [comment]
Just to add in a few more pieces. If the histogram profile isn't sRGB (e.g. Adobe RGB):

![image](https://user-images.githubusercontent.com/2311860/143730602-448ec202-47a0-4309-aa9c-f28cf38bc840.png)

Without plugging the numbers into a CIE color calculator, this still seems plausible, that this is where sRGB primaries/secondaries sit in Adobe RGB. As per what you wrote:

> The test image, covering an sRGB profile, should fulfill the sRGB circle in histogram, while it will cover only a part of the rec2020 histogram, if I'm not mistaken

Yes, I was being dull...

If I look at a gradient test image and try to find the most saturated values, I don't always find 100%. But the results visually still look OK in RYB:

![image](https://user-images.githubusercontent.com/2311860/143730843-55f615e3-2706-4a71-844d-eb54d3b629b9.png)

I tried sampling the sample image via GIMP's colorpicker, and also never quite found 100% for, say, green. It may just be that the interpolation loses 100% values?

I'm muddled as to whether I'm no longer able to replicate this problem, or am just simply muddled here.

**Comment by phweyland** [comment]
Looks like the color picker makes the difference ...

![image](https://user-images.githubusercontent.com/23012047/143771562-aa21e076-d018-481d-a30a-be68666714d5.png)

**Comment by phweyland** [comment]
I get the same results with a fresh install (empty darktable folder).

**Comment by phweyland** [comment]
I start to see changes when I change the screen calibration...

![image](https://user-images.githubusercontent.com/23012047/143771990-1a4e2f59-61fc-422c-8566-d215a4435230.png)

Above screenshot with the old calibration file.
![image](https://user-images.githubusercontent.com/23012047/143772028-f57ed598-d37d-4bba-a6fd-7b84cbb365bc.png)

Images measurements should depend on the display, shouldn't they ?

**Comment by dtorop** [comment]
> Images measurements should not depend on the display, should they ? EDIT unless specified ...

Ah, _shouldn't_ depend on the display. But they do... As the path of the data is via the preview pipe, going:

`... -> work profile -> colorout -> display profile`

At which point, for both scopes and pickers:

` -> histogram profile -> measurement`

So there are two cases where the display profile will particularly mess things up:

- if the display profile is bounded (CLUT) with a smaller gamut than the histogram profile
- the rendering intent of the display profile is perceptual, and the display profile is gamut mapped to a space smaller than the histogram profile

What happens if in "display profile" in darktable you change the profile from "system display profile" to something much wider gamut and nicely behaved, such as linear Rec2020 RGB?

**Comment by phweyland** [comment]
linear Rec2020 RGB as display profile:
![image](https://user-images.githubusercontent.com/23012047/143779828-770026ef-a48e-40b8-95c0-56653dc5a83d.png)

See RGB values.

**Comment by dtorop** [comment]
That is good news, yes? It could just be the display profile messing up the data? Though of course it's (known) bad news -- that the current pipeline setup allows for display profile to mess up the data.

**Comment by phweyland** [comment]
The glitch is explained. Thanks for your help (and your test file again).
I better understand how this works now.

> the current pipeline setup allows for display profile to mess up the data.

This looks like a bug ...
The histogram profile should connect just before color out. This way the user choose in which profile the histogram should work. He can even choose his display profile (at least he knows what is going on).

**Comment by dtorop** [comment]
> This looks like a bug ... The histogram profile should connect just before color out.

Yes! There's been a lot of back-and-forth about how to do this, e.g. #8051, #8634, etc. It may just be that when the new dt version is out, that it makes sense to simply make this change, and then deal with what else breaks as a result!

> The glitch is explained.

I hope so! I think I saw something funny here matching what you saw above, with an "ok" display profile...

**Comment by phweyland** [comment]
OK, thanks gain. I'm closing this one then.

**Comment by phweyland** [comment]
Same effect on calibrated notebook screen:

![image](https://user-images.githubusercontent.com/23012047/143782073-76d10dbc-dda2-4451-aad5-c7bfa2306ed4.png)

**Comment by dtorop** [comment]
Yes! I guess it is a nice way to preview display gamut clipping. But better that this actually be in the scope! This was an original idea for vectorscope which I'd still like to work on.

https://github.com/darktable-org/darktable/blob/959cde5b8364c844535ee9fd09918327b625a5e2/src/libs/histogram.c#L1023-L1027

There could be another set of dotted lines to show the display primaries, to give a sense of the constraints of the current display and its profile in rendering the image.

I'm still a bit mystified why this is only showing up now as a problem, rather than during RYB development... Maybe due to a change in display profile?

**Comment by phweyland** [comment]
> I'm still a bit mystified why this is only showing up now as a problem, rather than during RYB development... 

My screen is not high quality and recently, after having working RYB, I had the opportunity to calibrate it.
As long as you don't calibrate, the display profile is assumed to be pure sRGB.
With an high quality screen, the correction may be so small that you cannot see this effect.

**Comment by dtorop** [comment]
> My screen is not high quality and recently, after having worked on RYB, I had the opportunity to calibrate it.
> As long as you don't calibrate, the display profile is assumed to be pure sRGB.
> With an high quality screen, the correction may be so small that you cannot see this effect.

That explains it! I'm using a fancy display which pretends to be Rec.2020 to the computer. It makes things much easier, but also means that I don't get to see cases like this unless I work with output settings...

**Comment by phweyland** [comment]
> I'm using a fancy display which pretends to be Rec.2020

What a lucky guy you are ! :)

**Comment by dtorop** [comment]
> What a lucky guy you are ! :)

OK, not to brag. All the fancy displays don't help unless the images are worth looking at...

**Comment by phweyland** [comment]
Sure !

> There could be another set of dotted lines to show the display primaries, to give a sense of the constraints of the current display and its profile in rendering the image.

Sounds interesting.
I understand with the current configuration, where the display profile is in the middle of the histogram chain. We could see the potential distortion due to display compared to the target.

Once we can choose the profile without side effect, how that would work ? Should we have to select 2 histogram profiles (a target and the real one) ?

**Comment by dtorop** [comment]
> Once we can choose the profile without side effect, how that would work ? Should we have to select 2 histogram profiles (a target and the real one) ?

I'm not sure I understand the target/real distinction?

I think the histogram profile is actually a workaround for the need to convert from display profile to _something_. If the scope/picker measurement happened before colorout, it could always just leave the data in work profile, with an overlay to give a sense of input/export/display profiles...

This would speed up processing, and remove a potentially confusing choice from the UI.

Though I do understand that one may want to, say, work on the image in Rec2020 linear, but still see it in the scope with the Adobe RGB or sRGB gamma function.

**Comment by phweyland** [comment]
I quite agree with what you have written.

> I'm not sure I understand the target/real distinction?

I was thinking at this: one works on a given equipment (real) but may want to check what would be the result in different conditions (target).
