### ISSUE TITLE
Sony ILCE-7M3

### ISSUE THREAD

**Issue by advancingu** [darktable-org/darktable#10445]
There appear to be RAW samples of this camera on https://raw.pixls.us already as of early 2018 but it is not included in Darktable yet, therefore this request issue.

I cannot tell if this camera was simply never requested yet or if the samples are insufficient. If needed, I can try to submit additional samples.

---

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by m-p-y** [comment]
What do you mean with "is not included in Darktable yet"? Any specific function?
I use RAW files out of my Sony a7 III (ILCE-7M3) without problems for more than 1.5 years with darktable. I can also open all ARW files from the linked raw.pixls.us site w/o issues in my current build (3.7.0+1513).

**Comment by advancingu** [comment]
You're right about RAW files. These are opened without issues. I wasn't even thinking about that as a possibility.

Instead I found that this camera is missing in the lens correction menu (see screenshot) and from that assumed that it is not included at all. What can be done about that to get it included?

![image](https://user-images.githubusercontent.com/130207/143092323-22b0c7fa-5d3b-4841-b4f5-f67738f21e76.png)

**Comment by MStraeten** [comment]
you might update your lensfun database - ilce-7m3 is supported since jan 29 2019

**Comment by m-p-y** [comment]
I also think your lensfun database is outdated (use `lensfun-update-data` on the command line); here is a screenshot from my machine, even the alpha 1 is included already:

![image](https://user-images.githubusercontent.com/3230061/143135512-0ce93437-4801-4d79-b114-83671850a25f.png)

**Comment by advancingu** [comment]
Running `lensfun-update-data` fixed it, thanks.

**Comment by sesselastronaut** [comment]
The accompanying package to be able to run the command `lensfun-update-data` is `liblensfun-bin`
