### ISSUE TITLE
[FR] able to add darktable version in the export metadata

### ISSUE THREAD

**Issue by Yvan-56** [darktable-org/darktable#10440]
**Is your feature request related to a problem? Please describe.**

When exporting, I have highly reduced the number of information I would like to let people see in metadata:
- copyright
- who has created the picture
- ...
- for creatorTool, I would like to put "darkable" + <version>
because so many information are shared I do not want to let in the export metadata.
But it is not proposed to get the darktable version as a variable for export as I can see in the manual, while you allow so many possibilities ...
If I need/want to export again the picture and see differences with the current one, it will be difficult to understand why.
And, I want to let people see what is possible to get with darktable by keeping this in metadata.
**Describe the solution you'd like**

Proposing a variable to expose the current darktable version would be helpful.

**Alternatives**

Exposing the darktable version with an export variable.

**Additional context**

thank you,
regards,
Yvan Radenac

**Comment by difrkaguilar** [comment]
In that case I created a template in the watermark module to export all related info, included the darktable version right in the image. With $(DARKTABLE.NAME) v$(DARKTABLE.VERSION) you can get this info.

Maybe this can be a solution, or then create an export variable.
 
**Sample image**
![Screenshot from 2021-11-20 20-29-50](https://user-images.githubusercontent.com/67672868/142745798-e9caa101-3686-4d72-b706-fa7e6ca24aec.png)

**Comment by Yvan-56** [comment]
Hi everyone,
First of all, thank you very much for the fix to #10441 : it works very well now.
Hi Franklin, thank you for highlighting the variables available for watermark, having $(DARKTABLE.NAME) and $(DARKTABLE.VERSION) available for metadata would be great.
darktable version could help in troubleshooting the results we may get when re-exporting later with another darktable version.
In the meantime, I put Xmp.xmp.CreatorTool = darktable.
Many thanks,
Regards,
Yvan Radenac

**Comment by Yvan-56** [comment]
Hi Philippe,
Many thanks for the attention you paid to this request.
Best regards,
Yvan Radenac
