### ISSUE TITLE
darktable logo cropped with hidpi-screen

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#10449]
**Describe the bug/issue**

The darktable logo in the top-left corner is too big and therefor cropped (see screenshot)

**To Reproduce**
1. hidpi-screen (screen resolution 3840x2160)
2. scale factor 200%
3. start darktable 3.7.x
4. see cropped logo

**Expected behavior**
Adjust logo size according to the rest of the screen

**Screenshots**
![image](https://user-images.githubusercontent.com/5677563/142780242-a67c8079-19fa-4579-842f-87e233d0f3e0.png)

**Which commit introduced the error**
I tried bisecting but could not find a version without the issue

**Platform**
* darktable version : 3.7.0+1503~gae523b769
* OS                : Linux - kernel 5.10.70
* Linux - Distro    : Manjaro, Gnome 40.4.0, X11
* screen resolution 3840x2160
* scale factor 200%

**Additional context**
No issue with 3.7.0 and scale factor 100%
No issue with 3.6.1 and scale factor 200%
I've seen the cropped logo in two youtube-videos using 3.7

**Comment by piratenpanda** [comment]
I guess it needs a dynamic solution here: [utility.c:424](https://github.com/darktable-org/darktable/blob/9203ea3e14404ccb1774ec6262cfcc392de590fc/src/common/utility.c#L424)

**Comment by Nilvus** [comment]
@Mark-64: as I know you have an HiDPi screen and works on icons and some UI things in darktable, maybe you could have a look on that. A minor one but would be good to fix for 3.8. Unfortunately, I don't have HiDPi screen by now. Or maybe you could fix that @quovadit?

**Comment by Mark-64** [comment]
The problem is I can't reproduce the issue on Windows. Will try tonight on Ubuntu

**Comment by MStraeten** [comment]
seems to be introduced with libsrvg 2.52.0; librsvg 2.50.7 is fine
