### ISSUE TITLE
[FR] $(EXIF_EXPOSURE) returning the expected result

### ISSUE THREAD

**Issue by Yvan-56** [darktable-org/darktable#10441]
**Is your feature request related to a problem? Please describe.**

I have tried to refine the export metadata to the minimum:
- copyright
- creator
- exposure
- aperture
- focal length
- creatorTool = darktable + version (another issue raised for that)
But, when putting this
Exif.Image.ExposureTime $(EXIF_EXPOSURE)
it is not giving the expected value, the result is 1.
I have tried to read a exported picture with Eye of Gnome, exiftool with same result.
I am using the latest darktable version 3.7.0 - git 1502 from OBS under GNU/Linux Debian unstable.
**Describe the solution you'd like**

$(EXIF_EXPOSURE) giving the expected result.

**Alternatives**

thank you,
Yvan Radenac

**Additional context**

For instance, an exposure of 1/200s shows in metadata 1s.

**Comment by phweyland** [comment]
As Exif.Image.ExposureTime is a rational type tag, that should be solved with #10404.

**Comment by Yvan-56** [comment]
Hi Philippe,
Thank you very much for your reply.
So, I have installed the latest dev darktable version to be sure to have the fix you mention:  darktable_3.7.0~git1510.c2a18632ec, with the latest commit as available today.
I untick all options except metadata.
Then, I fill in with these attributes:
Exif.Image.Artist = $(CREATOR)
....
Exif.Image.ExposureTime = $(EXIF_EXPOSURE)
...
Exif.Photo.ExposuteTime = $(EXIF_EXPOSURE)
...
Xmp.exif.ExposureTime = $(EXIF_EXPOSURE)
Screenshot to illustrate the preferences: https://drive.google.com/file/d/1DQJuVvWiW3u4q9WhPOqcob9kik7UrbM5/view?usp=sharing
And the RAW file I have tried to export, exposure time 1/60 s: https://drive.google.com/file/d/1KZ-9ZyNRjngeFa7M0Ms2B1BSesV_Ah1x/view?usp=sharing.
Same result with a RAW from Nikon AW1 or Canon EOS 300D.

exiftool on the RAW gives the right value
```
exiftool -a -u -g1 _DSC9772.NEF |grep "xposure Time"
Exposure Time                   : 1/60

```
while the exported jpg gives 1:
```
exiftool -a -u -g1 _DSC9772.jpg |grep "xposure Time"
Exposure Time                   : 1
Exposure Time                   : 1
Exposure Time                   : 1
```

Please, let me know if I do not use correctly the export preferences.

Many thanks for your help.
Best regards,
Yvan Radenac

**Comment by Yvan-56** [comment]
Hi again,
I have tried with a exposure higher than 1s, like 1.3s, then it is working fine.
When it is fractional, like 1/60s , then the issue is occuring with a resulting exposure of 1 in exported jpg.
Hope this may give better understanding of the issue.
Regards,
Yvan Radenac

**Comment by phweyland** [comment]
Thanks. Got it! I'll look at it.

**Comment by phweyland** [comment]
I get this which seems to be correct:
```
$ exiv2 -PE 20210513_Ipoema_104.jpg | grep Exposure
Exif.Photo.ExposureTime                      Rational    1  1/350 s
```

**Comment by phweyland** [comment]
Hi Yvan, hopefully the PR above should fix your issue. It would great if you could check if that work for you. Thanks in advance.
