### ISSUE TITLE
[FR] Keep previous collections folder view when changing back from darkroom to lighttable

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#10446]
**Is your feature request related to a problem? Please describe.**
I am using the folder view in the lighttable module all the time (darktable `3.5.0+4118~gc2a18632e` @ Ubuntu 20.04)
When going back from darkroom to lighttable the folder view within the "Collections" panel jumps back to the top of the list showing the latest folders, but not to the folder which I'm currently browsing in the middle panel showing the image thumbnails.

https://user-images.githubusercontent.com/810285/142777719-93ca59c3-c433-4729-83e5-dbede6a971dd.mp4

**Describe the solution you'd like**
If I jump from darkroom to lighttable I don't want to the collections panel to be changed back to the top, I want to be exactly at the point where I went from lighttable to darkroom, with the folder I'm currently browsing selected.

**Comment by difrkaguilar** [comment]
I don't know, but maybe you are in 3.6.1 version. In the 3.7.0 master branch this issue is already fixed. It is important for developers know all possible info about operative system, openCL and darktable version among others.

**Comment by Nilvus** [comment]
As it is fixed in actual master, so future 3.8 which will be out in a month, I close this issue. @da-phil: next time, please think about providing all infos asked in template issue, like OS, darktable version you used, etc. Thanks.

**Comment by da-phil** [comment]
Wait a second guys, I'm using the current master (`3.5.0+4118~gc2a18632e`), freshly built yesterday night.
Can you explain me how to enable the behavior I specified in my first post?

**Comment by difrkaguilar** [comment]
From here you can install The darktable master branch. Last update is 3.7.0~git1510.c2a18632ec6815.2

https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

**Comment by Nilvus** [comment]
> Wait a second guys, I'm using the current master (`3.5.0+4118~gc2a18632e`), freshly built yesterday night. Sorry for not putting it in the ticket in the first place. @Nilvus / @difrkaguilar Can you explain me how to enable the behavior I specified in my first post?

To complete @difrkaguilar: if you have such version number, you have not the real master but a sort of combined one as actual master begin by 3.7.0. After Christmas, master will become 3.9.0...

**Comment by da-phil** [comment]
Now the question is: why do I get this version number (3.5) although I'm building from master which contains all the new goods such as the "diffuse and sharpen" module etc.
I followed the README to build darktable and used the build script.  Do you know where and how is the version number derived?

**Comment by da-phil** [comment]
Okay, I just found out that `git describe --tags --dirty` is producing the version string.
And the reason why it is still giving me this version is: I didn't fetch all the more resent git tags, the latest one was still `release-3.5.0`.
After a `git fetch --all --tags` the command gives me the correct version string: `release-3.7.0-1511-gdf356c0c1`

I'll open a PR to fix the script which produces the version string in the meantime.

**Comment by da-phil** [comment]
@Nilvus getting back to the problem, I recorded a short video to show the problem:

https://user-images.githubusercontent.com/810285/142777719-93ca59c3-c433-4729-83e5-dbede6a971dd.mp4

As you told me it is fixed already, can you please tell me how to configure dt to not jump to the latest folder in the lighttable whenever I switch back from darkroom to lighttable?

**Comment by AlicVB** [comment]
I can reproduce with current master too.
This seems to happen only when there is subfolders *and* they are included (when we have '*' at the end of the folder name) which may explain why some of us don't reproduce...

**Comment by da-phil** [comment]
Indeed! It only happens with * at the end, if I go down into the respective subfolder and open the image into the darkroom, I get right back in this folder when I change back to lighttable. Seems like a bug, doesn't it?

**Comment by AlicVB** [comment]
> Seems like a bug, doesn't it?

yes it is. Sadly I'm really not sure to have enough free time next week to have a look...
