### ISSUE TITLE
shortcuts: double-click bottom pane should replace

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10451]
When amending shortcuts via the preferences window, if I want to _replace_ an existing shortcut with another, this is currently a two-step process: I first have to add a new shortcut and then remember to also delete the existing shortcut. When I tried this myself I was initially confused because the old shortcut was still there, so I thought it hadn't worked (until I saw the new entry at the bottom of the screen).

In my opinion this is probably ok when you double-click the _top_ panel (and probably also if you visually assign) but if you explicitly double-click an entry in the bottom panel the default should be to replace rather than add a new shortcut, since you have chosen to select the existing shortcut.

I think assigning multiple shortcuts to a single action is a fairly niche requirement (probably more for those using midi devices in addition to keyboard/mouse) and, on that basis, I'm also wondering whether replace should be default throughout, or perhaps with a prompt so that if an existing shortcut already exists the user is asked "do you want to _replace_ or _create an additional_ shortcut?".

**Comment by parafin** [comment]
Maybe replace by default if the same input device is used and add a new one of different (e.g. keyboard and MIDI device). Though I guess boundaries get hazy when complex shortcuts are defined, with modifiers and such...

**Comment by elstoc** [comment]
Predictable is better than clever IMO. I didn't notice it before because I expected it to work how it used to, and I was mostly testing by creating new shortcuts rather than by replacing existing ones.

**Comment by elstoc** [comment]
#10452 means that whatever we do we can't automatically replace default shortcuts because they'll just get re-added when darktable restarts. So, while this is a separate issue, we can't have one fix without the other.

**Comment by elstoc** [comment]
How about a new option "only allow one shortcut per-device for each action" (per-device to take @parafin's suggestion into account)? If you attempt to allocate a new shortcut with this selected, it deletes the previous one. Similarly, if this option is selected when shortcutsrc is loaded, remove any previously-allocated device shortcuts for the same action (i.e. those loaded by default). When creating replacement shortcuts manually, a dialog should probably appear saying something like "replace existing shortcut (description) with new shortcut (description)?"

**Comment by elstoc** [comment]
@dterrahe what do you think?

**Comment by dterrahe** [comment]
Short answer: for your benefit, that people who want as few shortcuts as possible don't end up with duplicates or save a few delete key presses, i see the drawback that others don't discover that you can have multiple shortcuts for different elements or with different effects or speeds.

**Comment by elstoc** [comment]
> you can have multiple shortcuts for different elements or with different effects or speeds

Indeed I hadn't thought of that

**Comment by dterrahe** [comment]
What do you say; can this be closed?
