### ISSUE TITLE
"Clear text" x appears in "search module" when no text in text field.

### ISSUE THREAD

**Issue by cldershem** [darktable-org/darktable#10468]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Red "clear text" x in "search module" text field will not go away. There is no text in the search bar and it persists restarts (both darktable and computer).

**To Reproduce**
Unclear how to reproduce on a machine that isn't mine.

**Expected behavior**
There should be no "x" if there is no text.

**Screenshots**
![DarktableClearText](https://user-images.githubusercontent.com/201608/143132825-7ef43764-f840-4b42-9d50-3d88e4461cfa.png)

**Platform**
* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.13.0-21-generic
* Linux - Distro    : e.g. Ubuntu 21.10
* Memory            :  
* Graphics card     : Mesa Intel® UHD Graphics (CML GT2)
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  : yes (still occurs when deactivated also)
* Xorg              : wayland
* Desktop           : gnome 40.4.0
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

│❯ darktable --version
this is darktable 3.6.1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by dterrahe** [comment]
This will be fixed in the dt 3.8 release.

**Comment by Nilvus** [comment]
I so close. Thanks both of you. @cldershem: darktable 3.8 will be released for Christmas.
