### ISSUE TITLE
Hasselblad 'X1D II 50C': Not supported, could not be exported using darktable-cli

### ISSUE THREAD

**Issue by ManudattaG** [darktable-org/darktable#10465]
**Describe the bug/issue**
_I could currently see that few Hasselblad camera modes are not supported by darktable for example: 'Hasselblad' 'X1D II 50C'. When used with darktable-cli binary for images to be exported, I see below mentioned errors._

**To Reproduce**

_1. Go to [Hasselblad website](https://www.hasselblad.com/learn/sample-images/x-system/)
2. Download RAW images for X1D II 50C
3. Start `darktable-cli` binary command line interface which allows images to be exported_

**Expected behavior**
_Darktable should export the image successfully without any errors_

**Screenshots**
![image](https://user-images.githubusercontent.com/8463344/143060430-1c20f370-6258-4b6f-946c-e994790123e4.png)

**Error trace**

> RawSpeed:Unable to find camera in database: 'Hasselblad' 'X1D II 50C' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (x1d-II-sample-06.3FR) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData *, const std::__1::string &, const std::__1::string &, const std::__1::string &), line 169: Camera 'Hasselblad' 'X1D II 50C', mode '' not supported, and not allowed to guess. Sorry.
[dt_imageio_export_with_flags] mipmap allocation for '/Users/Downloads/interim.jpg' failed
[imageio_storage_disk] could not export to file: '/Users/Downloads/interim.jpg'!

**Platform**

* darktable version : 3.6.0+3~g4287791fe
* OS : macOS Big Sur
* Memory : 16 GB

**Additional context**

 - Can you reproduce with another darktable version(s)? yes
 - Can you reproduce with a RAW or Jpeg or both? yes with RAW 'Hasselblad' 'X1D II 50C' 3FR
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes, in the actual scenario the darktable starts with /tmp directory
 `[dt_imageio_export_with_flags] mipmap allocation for '/tmp/tmpfh6zzsau/intermediate.jpg' failed`
 `[imageio_storage_disk] could not export to file: '/tmp/tmpfh6zzsau/intermediate.jpg'!`

**Comment by rexbron** [comment]
You should file a camera support bug request and upload samples that can be licensed under a Creative Commons Zero license as outlined in the camera support bug report template.
