### ISSUE TITLE
3 Suggestions to improve the Color Calibration module

### ISSUE THREAD

**Issue by pedrorrodriguez** [darktable-org/darktable#10473]
Hi all,

In no particular order:

**1. CAT tab:** If chromatic adaptation deals with white balance, as far as we, users are concerned, would it be a bad idea to rename the CAT tab WB? Inside the tab, there is already a dropdown menu to choose between various models. Perhaps that won't be as accurate a name, but I'd say that most people with a camera would know what WB will do to their images, while not as many will understand what CAT stands for. I know I didn't.

**2. R, G, and B tabs:** Since they are the same tool for each of the three channels, a channel mixer, wouldn't it make sense to group them into one tab, and call that tab something like "mixer"? Similar to this:

![mixer](https://user-images.githubusercontent.com/64545422/143266911-a4eae781-ee5b-4fcb-93d0-35ad3d34c7e7.png)

**3. hue tab:** We have a colorfulness and a brightness tab in this module, that lets you control the colorfulness and the brightness of each of the individual channels. Would it be a ridiculous idea to create a hue tab, that lets you control the hue on a channel basis? Something like lightroom's camera calibration tab. I've done this single channel hue rotation via the color balance RGB module changing the blending mode to an RGB channel mode, but the hue slider is way too sensitive. I am also not sure this would be the right way to do it, and usability-wise is cumbersome. Here's a mockup:

![hue](https://user-images.githubusercontent.com/64545422/143266825-f28b9488-05e5-4c6d-9924-34763cabaee5.png)

Thanks for the attention and keep up the good work!

**Comment by MStraeten** [comment]
1. If the term CAT is an issue then the user better stays with lightroom since they will be completely confused if they don’t see the temperature and hue sliders;) So theres already a need to get what’s happening here - and the term CAT indicates that there’s something they don’t expect ;)

2. I really don’t like endless columns of sliders resulting in a need to scroll a lot while using a module with parametric masking on limited display space (colorbalancergb is an example for that)

3. Isn’t it better to do this using multiple instances of this module with parametric masks instead of overloading the gui?

**Comment by pedrorrodriguez** [comment]
> 1. If the term CAT is an issue then the user better stays with lightroom since they will be completely confused if they don’t see the temperature and hue sliders;) So theres already a need to get what’s happening here - and the term CAT indicates that there’s something they don’t expect ;)

I agree with you that users asking devs for features to make Darktable work like Lightroom is a waste of time and effort playing catch-up, and they should stick with Lightroom. Just because an application does something in a particular way, no matter how big the userbase or the company behind it, doesn't mean that it's the best solution to a particular problem. After watching Aurelien's videos on the Color calibration module, I can see how the temperature/tint model is flawed.

However, what I hope we can agree on is that this is a challenging topic when it comes to naming things. We have a new way of doing things in Darktable, which seems to be a kind of White balance on steroids, but in order to do so we need two modules in the pipeline: White balance (which happens early in the pipe and should not be touched unless you created a profile for your camera), and Color calibration. I am not against learning a new tool or process, but it took me some reading, and watching Aurelien's videos to actually realise not only how, but where I should be white balancing my photos.

Perhaps what I suggested was not the right solution, but I believe there has to be an easier way to name these two steps, so that it's clearer for new users. For myself is not a problem anymore. Once I figured it out, I know where things are.

> 2. I really don’t like endless columns of sliders resulting in a need to scroll a lot while using a module with parametric masking on limited display space (colorbalancergb is an example for that)

Agreed, vertical real estate is precious. Perhaps my mockup should be fine tuned to make things more compact. The reasoning behind this suggestion was that the R, G and B tabs seem to belong to a lower organizational level than CAT, colorfulness, brightness and grey. Each of the other tabs does one very distinct thing, while R, G and B do the same, only for each of the channels. However, the way I put it together, there's no need for any scrolling, since everything fits vertically. Perhaps I didn't quite understand you.

> 3. Isn’t it better to do this using multiple instances of this module with parametric masks instead of overloading the gui?

This I didn't understand. Multiple instances of which module? Color balance RGB? If so, the hue slider is extremely sensitive, and it's very hard to produce good results. The hue shift I was talking about would be subtle, changing the colors slightly, but not going from blue to orange, for example.

Thanks!

**Comment by MStraeten** [comment]
you can have multiple instances of color calibration module in combination with parametric masks if there's need to do different hue changes on some channels (as well as dealing with different illuminated parts of the image)

**Comment by pedrorrodriguez** [comment]
> you can have multiple instances of color calibration module in combination with parametric masks if there's need to do different hue changes on some channels (as well as dealing with different illuminated parts of the image)

I have the feeling that we are talking about two different things. I didn't mean to shift the hue of the illuminant and apply it only on one of the channels. I was talking about a global hue rotation, like the one in the color balance rgb module, but applied on a channel basis instead of the whole image. Like so:

**Original image:**

![Screenshot_20211125_153758](https://user-images.githubusercontent.com/64545422/143462816-67202d5e-b2e2-43e7-b764-bdc61d5c6b6f.png)

**-30º shifted red channel:**

![Screenshot_20211125_154416](https://user-images.githubusercontent.com/64545422/143463014-109b0c28-7812-4697-9610-36c8769ed39d.png)

This can already be done, as I just showed, rotating the hue in color balance RGB applied on a single channel. I believe something similar to this is what Lightroom does with its camera calibration tab. However, bringing this feature over to the color calibration module could make sense. Here are the pros and cons I could think of right off the bat:

Cons:
- This could be used "artistically", and the nature of the color calibration module is correction, not grading.

Pros:
- This could be used carefully to correct the colors of an image, if we didn't/couldn't use a color checker. It could also be used as an artistic tool, adding a second instance of Color calibration, once our image is properly white balanced.
- Consistency: the current tools that affect the RGB channels individually are in the Color calibration module (CAT, channel mixer, brightness, colorfulness, and grey). Adding hue to that list would be consistent with that.
- Discoverability: I believe this is a powerful tool at our disposal to correct/grade our images. Even though it is currently possible to use, it's not straightforward without giving it some thought, and I believe users would find it helpful.
- This is more of a question than a pro or a con, but since I believe @aurelienpierre says in some his videos that Color calibration and Color balance RGB deal with color differently internally, is Color balance RGB better suited for this kind of operation? Or rather Color calibration?

Thanks!

**Comment by aurelienpierre** [comment]
1. CAT is not WB. WB is a shitty partial CAT, basically it reweighs RGB coeffs in whatever RGB space. CAT goes to a cone response space to do so.
2. If we merge the content of 3 tabs into one, all the people with small displays will complain that the module doesn't fit entirely in their screen. Been there, done that, won't do it again.
3. Cone response space doesn't have a reliable hue. That is, when you increase or decrease chroma, hue is not 1:1 preserved because of the Abney effect:
![image](https://user-images.githubusercontent.com/2779157/143786060-eefd6d32-ca94-4aa4-a35c-aeface079a90.png)
The central dot is white, and chroma navigates in a radial direction from that white. The curves have constant perceptual hue. Meaning that a hue-preserving chroma, here, should actually follow those lines when increasing/decreasing, not a radial direction.

**Comment by pedrorrodriguez** [comment]
> 1. CAT is not WB. WB is a shitty partial CAT, basically it reweighs RGB coeffs in whatever RGB space. CAT goes to a cone response space to do so.

In the end, it's a choice between accuracy in naming or possibly making it slightly easier for beginners. You favor the first one, and I can understand why. In the long run you are probably right. From a user's point of view, familiarity is key, so reading the manual and watching your videos are a must. No big deal.
 
>     2. If we merge the content of 3 tabs into one, all the people with small displays will complain that the module doesn't fit entirely in their screen. Been there, done that, won't do it again.

Here I don't agree with your logic (for what it's worth, since it's not my call to make). I would understand if all darktable modules had a certain aspect ratio, and tried to be as vertically compact as possible, separating things into many tabs and subtabs. However, I'd say my "mixer" suggestion wouldn't take more vertical space than say the filmic module, definitely not color balance RGB, or any module with a drawn/parametric mask. On the other hand, it would make the module more coherent: each of the tabs in color calibration would have one function, CAT, Channel mixer, brightness, colorfulness and grey. Another option would be to have subtabs, but in my opinion that makes the UI unnecessarily complex.

>     3. Cone response space doesn't have a reliable hue. That is, when you increase or decrease chroma, hue is not 1:1 preserved because of the Abney effect:
>        ![image](https://user-images.githubusercontent.com/2779157/143786060-eefd6d32-ca94-4aa4-a35c-aeface079a90.png)
>        The central dot is white, and chroma navigates in a radial direction from that white. The curves have constant perceptual hue. Meaning that a hue-preserving chroma, here, should actually follow those lines when increasing/decreasing, not a radial direction. But we have no close-form, algebraic, equations for those hues in cone space.

I wasn't aware of that. Thanks for the explanation. I can always rotate the hue in color balance RGB on one channel, then.

**Comment by MStraeten** [comment]
> However, I'd say my "mixer" suggestion wouldn't take more vertical space than say the filmic module, definitely not color balance RGB, or any module with a drawn/parametric mask.

don't forget - color calibration is a module with drawn/parametric mask. And thats very important since this makes it usable for mixed illumination situations.

**Comment by pedrorrodriguez** [comment]
@aurelienpierre @MStraeten given that we now have the ability to move the scopes to the left panel, are you still against consolidating the channel mixer into one tab? I'm just asking so I can close this issue. Thanks!

**Comment by MStraeten** [comment]
moving scopes to the left side isn't a proper solution to get room for wasting space on the right panel - it just replaces lack of space on the right side with lack of space on the left side. 
I prefer having scopes on the right side - since i already have to scroll a lot on left side when dealing with maskmanager ;)

**Comment by pedrorrodriguez** [comment]
> moving scopes to the left side isn't a proper solution to get room for wasting space on the right panel - it just replaces lack of space on the right side with lack of space on the left side. 

I think it is safe to assume that my intention was not to waste vertical space anywhere. It is true, though, if you take something from the right and put it on the left, you have more space on the right and less on the left. This is what I understood from the conversation so far:

- The channel mixer is spread across three tabs inside the color calibration module.
- This is so for fear of complaints of people with small screens (which is a valid concern).
- I pointed out that I don't follow the logic: Firstly, are small screens the main target? If so, there are many other modules that don't follow this design philosophy (colorbalance rgb, filmic, diffuse or sharpen), and that seems to be fine. Why is that? In those modules, sliders are grouped in tabs because of their function, because it makes sense to have them all in the same tab. The color mixer is different. Why is it different?
- If small screens are not the main target, and it seems like this design constraint in the channel mixer is arbitrary, it might be wise to change it. Naturally, it will require (some will say waste) more vertical space.
- I believe @aurelienpierre has said several times that, unless we are Kodak and can get a large enough sample of people, and money to conduct the research, "because I like it" or "I prefer it this way" is not a good enough criterion for development.
- In the end, you are the devs, and you get to be arbitrary in your decisions if you want. I benefit from your work and appreciate your efforts. In the end, this is not a big deal. I just think it would make sense.

> I prefer having scopes on the right side - since i already have to scroll a lot on left side when dealing with maskmanager ;)

That is a valid concern, and we now have the option to choose what works best for each of us.

I'll give this a few days, and if you still don't agree with me, I won't waste anyone's time and close this issue. Thanks anyways.

**Comment by elstoc** [comment]
> I pointed out that I don't follow the logic: Firstly, are small screens the main target? If so, there are many other modules that don't follow this design philosophy 

IMO it's better, in a multi-tabbed module, to have the tabs of equal or similar height, since the module itself will expand to fit the size of the largest tab. If the R,G,B tabs were to be combined, the module would be much taller for everyone, even if they weren't interested in the "channel mixer" tabs. The other tabs would be full of empty space.

**Comment by pedrorrodriguez** [comment]
> > I pointed out that I don't follow the logic: Firstly, are small screens the main target? If so, there are many other modules that don't follow this design philosophy
> 
> IMO it's better, in a multi-tabbed module, to have the tabs of equal or similar height, since the module itself will expand to fit the size of the largest tab. If the R,G,B tabs were to be combined, the module would be much taller for everyone, even if they weren't interested in the "channel mixer" tabs. The other tabs would be full of empty space.

That is a valid concern. It is a matter of choosing the more advantageous one (or the lesser evil). We seem to be keeping people with small screens that don't use the channel mixer in mind. What about the people that do use it? We need to go back and forth between tabs which adds clicks. Is scrolling worse than clicks? For the record, I often use darktable on my microsoft surface's small screen.

**Comment by elstoc** [comment]
It's not just people with small screens, but some people also like to be able to have multiple modules open at once as well. It's just a way of saying "we need to consider module height as part of any design decision". The matching tool only grows the height of the module when expanded. Since it's an optional and occasional-use section, it will be collapsed for most people, so does not increase the height of the module. That's a harder thing to do for things that are already in a separate tab.

**Comment by pedrorrodriguez** [comment]
> It's not just people with small screens, but some people also like to be able to have multiple modules open at once as well. It's just a way of saying "we need to consider module height as part of any design decision". 

What you say makes sense to me, and believe me, I understand. However this rule doesn't seem to apply to other modules with the same or taller height. Particularly when we are talking about just one tool. It seems to me that splitting the channel mixer would be equivalent to splitting the four ways tab of the color balance rgb module. It is essentially the same tool. Why is one thing right for one module but not for the other? 

Consider the following case. If I want to add orange to the red channel with the channel mixer the process goes like this: click on the R tab - add red to the red channel - click on the blue tab remove blue from the red channel - oops! perhaps too much, I might want to add a bit more red - click on the R tab - adjust red - etc. With my proposal, everything is at your fingertips in the same tab, at the expense of vertical space.

> The matching tool only grows the height of the module when expanded. Since it's an optional and occasional-use section, it will be collapsed for most people, so does not increase the height of the module. 

Ah, I see. I wasn't aware of that.

> That's a harder thing to do for things that are already in a separate tab.

Yeah, I can't imagine a working collapsible interface for the channel mixer.

**Comment by Nilvus** [comment]
Given answers here, this do not need to remains open. I so close.
