### ISSUE TITLE
Existing IPTC (string-r) fields in original image duplicated on export

### ISSUE THREAD

**Issue by lhietal** [darktable-org/darktable#10483]
**Describe the bug/issue**
When imported image already contains IPTC(IIM) fields those are duplicated on export. This only happens with tags that have type `String-R`. 

**To Reproduce**
1. Import image containing IPTC(IIM) metadata eg. ([https://iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2021.1.jpg](https://iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2021.1.jpg))
2. In metadata export options add formula that adds the same values eg. (Tag: `Iptc.Application2.Keywords` Formula:`$(TAGS)`)
3. Export image
4. Inspect exported image metadata (exiftool, exiv2)

**Expected behavior**
Tags in original image are not present in exported image if changed in darktable.

**Platform**
* darktable version : 3.7.0+1548~g27ab43af5
* OS                : macOS 10.14.6
* exiv2            : 0.27.5

**Additional context**
After following change export seems to work as expected.

```
diff --git a/src/common/exif.cc b/src/common/exif.cc
index 66d4fe286..78fcd195f 100644
--- a/src/common/exif.cc
+++ b/src/common/exif.cc
@@ -4017,6 +4017,22 @@ int dt_exif_xmp_attach_export(const int imgid, const char *filename, void *metad
                   // FIXME if an element of the list contains a ", " it is not correctly expeorted
                   Exiv2::IptcKey key(tagname);
                   Exiv2::Iptcdatum id(key);
+                  Exiv2::IptcData::iterator iptcPos;
+
+                  // remove existing values so they are not added twice
+                  iptcData.sortByKey();
+                  if((iptcPos = iptcData.findKey(key)) != iptcData.end())
+                  {
+                    while(iptcPos != iptcData.end())
+                    {
+                      std::string keyName = iptcPos->key();
+                      const char *ckey = keyName.c_str();
+                      size_t len = keyName.size();
+                      if(!(g_str_has_prefix(ckey, key.key().c_str()) && (ckey[len] == '[' || ckey[len] == '\0'))) break;
+                      iptcPos = iptcData.erase(iptcPos);
+                    }
+                  }
+
                   gchar **values = g_strsplit(result, ", ", 0);
                   if(values)
                   {
```

After this change it is not possible to add values to existing keys unless the key is also available on import. I think that not having unexpected tags is nicer behaviour but some people might be relying on the ability to add values to otherwise unavailable tags.

Ideally it should be possible to map exiv2 tags to darktable metadata also on import. Similar functionality as with export. That would allow darktable to be used more flexibly as a part of metadata workflows.

**Comment by phweyland** [comment]
If I export the imported image without any change I get the same metadata plus some others which have been derived from iptc inputs. That's ok so far.

In your example, you export the tags again. As there is no way to distinguish an iptc keywords from another, the current behavior sounds ok to me.

> Ideally it should be possible to map exiv2 tags to darktable metadata also on import. Similar functionality as with export. That would allow darktable to be used more flexibly as a part of metadata workflows.

I can agree at first glance, but metadata world is such a mess that I would keep dt safe (DAM is not its first goal), just making sure we can control accurately the metadata we export.

Saying that, I see your example pinpoints a need: to be able not to export original iptc (as we do for exif for example) if necessary, keeping the possibility to recreate some of them through the formulas.

**Comment by phweyland** [comment]
BTW, thanks for sharing the metadata image. Interesting indeed !

**Comment by lhietal** [comment]
My main motivation for changing the behaviour is to prevent IPTC and XMP from getting out of sync. Now it looks like by default IPTC is copied from original file on export. I think it is good pass unknown metadata so that possibly important information is not lost. However if there are any changes (eg. adding new keywords) IPTC is not updated and gets out of sync. Then if I set eg. (Tag: `Iptc.Application2.Keywords` Formula:`$(TAGS)`) to try update it I get duplicates.

> >After this change it is not possible to add values to existing keys unless the key is also available on import.

>I may have misinterpreted this. What do you mean ?

There is no way to get original value in the `Formula` field. You can only set values from darktable keys `$(*)`. I was considering the possibility of current functionality being used to work around this limitation.

> Your piece of code is not yet clear for me, but I would agree to remove the iptc keys (Iptc.Application2.Keywords in our case) if there is a formula for it.

The code only removes existing `Iptcdatum` if there is a new value being written and shouldn't remove them otherwise. Loops through all `Iptcdatum` that have the same key and removes them. I'm not very familiar with this part of darktable but testing the functionality seems to work.

> DAM is not its first goal

I would agree that darktable development is more focused on the raw development. I would however like to see similar innovation on the DAM side also. The website even has workflow mentioned first which I thought refered to DAM features. "darktable is an open source photography workflow application and raw developer" I haven't seen any larger discussion about the goals of the project so this might also be a misunderstanding.

Metadata handling is difficult and I hope I can help with that at some point.

**Comment by phweyland** [comment]
> The code only removes existing Iptcdatum if there is a new value being written and shouldn't remove them otherwise.

Agreed. Hopefully the fix above does the same.

> There is no way to get original value in the Formula field. You can only set values from darktable keys $(*). I was considering the possibility of current functionality being used to work around this limitation.

I agree this could be a great improvement to be able to use metadata keys (like Iptc.Application2.Keywords) inside the formula (beside the dt variables).

> Metadata handling is difficult and I hope I can help with that at some point.

Welcome ! And thanks for reporting this.
