### ISSUE TITLE
watermark: adding simple text (svg) is broken with librsvg 2.52.x

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#10489]
when adding a watermark "simple text (svg)" the rendering is fine if darktable is built with librsvg 2.50.7 but broken with librsvg 2.52.4

seems to be a sibbling to #10449 

**Screenshots**
rendering with librsvg 2.52.4:
![image](https://user-images.githubusercontent.com/39386816/143601907-74d23542-de4b-413a-93a3-37d4f43aff87.png)

**Which commit introduced the error**
no darktable change introduced this, just updating librsvg from 2.50 to 2.52

**Platform**
* darktable version : darktable 3.7.0+1550~g0a3aab0cc-dirty
* OS                : OSx

Workaround:
build packages using librsvg 2.50.x (at least for win or osx builds)

**Comment by piratenpanda** [comment]
On arch this makes darktable completely unusable. All UI elements go black after you select simple text. Restarting darktable is the only option

**Comment by parafin** [comment]
Note that while #10449 is only present on HiDPI displays, this bug is present regardless of screen scale settings.
