### ISSUE TITLE
mouse move shortcuts triggered too easily

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10481]
I use "E+scroll" to change the exposure in the exposure module and I frequently hold down E, scroll a bit, look at the image (while holding E), scroll a bit more, etc...

While I am doing this, unless I keep the mouse absolutely stationary, the exposure change toast messages are frequently replaced with messages like "e, horizontal, down not assigned", "e, skew, down not assigned", which can be distracting. This can be triggered with very small movements of the mouse.

I previously had "E+horizontal movement" assigned to exposure/black level correction but because it's really hard to avoid triggering it unintentionally while using "E+scroll", I disabled it. 

Ultimately, the excessive ease of triggering movement shortcuts makes them basically unuseable for me with a mouse, though they are ok when I'm using my touchpad (which is how I originally tested). Even when disabled the messages distract.

A couple of options:

- Increase the amount of mouse movement required to trigger a shortcut (and/or make it configurable). Once the threshold has been reached, ignore that threshold for future movements until the initiating key/button has been raised.
- Once an extended shortcut has been initiated (i.e. a key/move combination has been successfully matched to an action), ignore any other types of movement until the initiating key/button has been raised. For example, once I've pressed E+scroll, ignore any other movements (apart from scroll) until I raise the E key.

midi controls can probably be ignored for this, since I assume it's hard to trigger one by mistake.

**Comment by elstoc** [comment]
@dterrahe

**Comment by dterrahe** [comment]
Thank you for the feedback!

I assumed from the start that some configurability might be required here (good chance that Macs have differing behavior, for example) but wanted to wait until the requirements became more clear when people started using it. Which might now be only after the release.

One design objective I had was that one could use a quite complicated shortcut to select a group of sliders and then, without having to repeat it, use the six different mouse moves to manipulate each off the sliders. As a silly over the top example, triple press ctrl-shift-C + left&right button triple click could select the crop sliders, and then horizontal could crop left, vertical crop top, diagonal crop bottom and skew crop right. And scroll could rotate. This gives (more than) enough shortcut combinations to assign all frequently used sliders.

Having to lift your shortcut button to switch from one slider to another defeats this approach.

How about a combination of your suggestions; once a particular mouse move (including scroll) has been used with the currently active shortcut, switching to another requires reaching a threshold of twice the normal minimum move. Wouldn't apply to midi (which is a separate hand) and maybe scroll (I'd think? Or do you accidentally trigger that as well?). The advantage of this would be that starting a mouse move shortcut doesn't feel unresponsive the first time.

This is implemented in #10485. Please test!

**Comment by elstoc** [comment]
> One design objective I had was that one could use a quite complicated shortcut to select a group of sliders and then, without having to repeat it, use the six different mouse moves to manipulate each off the sliders. 

That sounds very niche. I wouldn't be surprised if you were the only audience for that one.

> maybe scroll (I'd think? Or do you accidentally trigger that as well?)

No. Accidentally scrolling during a move is pretty hard.

I still think it would be nice / useful to be able to set the movement threshold but your PR keeps me happy enough for now :)
