### ISSUE TITLE
load Exif data from HEIF images

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#10505]
**Is your feature request related to a problem? Please describe.**
Currently, camera-provided metadata is not imported, with exception of color profile data. Hence much of the "image information" module is not filled in for HEIF files. It is therefore not possible to sort images by capture time. Nor is it possible to filter images in the collect module via useful attributes such as "date taken" or "camera".

**Describe the solution you'd like**
In `dt_imageio_open_heif()`, it would be nice to simply call `dt_exif_read()` to read the metadata.

The Exiv2 changelog seems to suggest that there's HEIF support in [v0.27.4](https://github.com/Exiv2/exiv2/releases/tag/v0.27.4).

**Alternatives**
Unfortunately, using command line exiv2 on a sample HEIF image produces no metadata. I do see metadata via exiftool, but it's hard to imagine hooking a Perl program into dt.

It appears to be possible to use libheif directly. Some references:

https://github.com/strukturag/libheif/blob/561abfc6b8c014499d42df5246cf2f6510fc196f/README.md?plain=1#L21

https://github.com/strukturag/libheif/blob/561abfc6b8c014499d42df5246cf2f6510fc196f/libheif/heif.h#L500-L503

https://github.com/strukturag/libheif/blob/561abfc6b8c014499d42df5246cf2f6510fc196f/libheif/heif.h#L662-L701

**Additional context**
HEIF support was added in #8800.

**Comment by parafin** [comment]
I think HEIF support has to be explicitly enabled in exiv2 (that’s the same container as CR3, right?), so maybe your exiv2 is built without this feature?

**Comment by kmilos** [comment]
Yes, Exif data is read by exif.cc for any image in a separate pass using exiv2 (which must support the format), not by individual format readers like imageio_heif.c and others.

**Comment by dtorop** [comment]
> I think HEIF support has to be explicitly enabled in exiv2 (that’s the same container as CR3, right?), so maybe your exiv2 is built without this feature?

Worse yet... I'm using Debian's exiv2 which is at 0.27.3 (https://tracker.debian.org/pkg/exiv2). Hence presumably reading this metadata isn't even an option, so long as I stay with the distribution's package.

Does this mean that darktable users who have the latest exiv2 (compiled with BMFF) are seeing HEIF metadata showing up? And that (with apologies for the noise), I should mark this FR as closed?

A further question: Looking at dt source, I see `dt_exif_read()` both in `_image_import_internal()`

https://github.com/darktable-org/darktable/blob/959cde5b8364c844535ee9fd09918327b625a5e2/src/common/image.c#L1624

and in the various `dt_imageio_open_*()` routines, behind a conditional, e.g.

https://github.com/darktable-org/darktable/blob/959cde5b8364c844535ee9fd09918327b625a5e2/src/common/imageio_jpeg.c#L732

But I don't see this in `dt_imageio_open_heif()` (though it does have the relevant include)

https://github.com/darktable-org/darktable/blob/959cde5b8364c844535ee9fd09918327b625a5e2/src/common/imageio_heif.c#L33

Should `dt_imageio_open_heif()` be trying to read the exif? Or does current code reliably call dt_exif_read() already, and are all these extra calls to `dt_exif_read()` vestigial?

**Comment by kmilos** [comment]
> Does this mean that darktable users who have the latest exiv2 (compiled with BMFF) are seeing HEIF metadata showing up? And that (with apologies for the noise), I should mark this FR as closed?

Yes please.

**Comment by dtorop** [comment]
> Yes please.

Done! Thanks...
