### ISSUE TITLE
FR: make the selected images counter available when only showing the filter bar

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#10518]
Darktable's Lighttable enables you to customize the top bar display :
DIsplay all
![image](https://user-images.githubusercontent.com/3989573/143932217-161e816f-86b4-44d2-a3df-d9f23398b379.png)
Hide the "filterbar"
![image](https://user-images.githubusercontent.com/3989573/143932269-ffc91b84-0958-47a2-bd28-a3d92b4207c8.png)
Hide all
![image](https://user-images.githubusercontent.com/3989573/143932314-f4b14a23-736c-407b-98dd-cfc8be0964d3.png)
Only show the "filterbar"
![image](https://user-images.githubusercontent.com/3989573/143932350-bbdabe91-3b8b-4b4a-854e-2848e3a3da4c.png)

To have as much useful screen estate as possible, I use the last on : only the filter bar is displayed.
But when doing so, in lighttable, the user has no way to know how many images have been selected.
That is because the selection counter is hidden !
![image](https://user-images.githubusercontent.com/3989573/143933619-72bea886-f17d-49e5-b357-7cf49683fcbe.png)
This counter is available is other setups (see top screenshots)

Could it be possible to put it in the "filterbar" so that the count of selected images is available whatever your topbar (except in "hide all" mode, of course) ?

Thanks a lot
GLLM

**Comment by ralfbrown** [comment]
That's likely to be tricky to implement.  OTOH, the image counter uses the "hinter" mechanism which shows usage tips for various tools in darkroom view, and having them visible with partially-collapsed top bar would be desirable as well (though dealing with two-line hints will be problematic).

**Comment by AlicVB** [comment]
I agree that this would be handy, but as @ralfbrown says, that's not so trivial and need to be done not only for lighttable, but for darkroom too.
I've some ideas for that, esp. something similar as what we are doing for the image info line... I'll try to give it a try !

**Comment by difrkaguilar** [comment]
Thank you @GLLM for your request. Nice to have this feature request on the lighttable, I made a similar request in #8453 but to be present in the darkroom.
Thanks @dterrahe and @TurboGit for making it happen.
