### ISSUE TITLE
thumbnail (lighttable) and darkroom views differ

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10519]
Looks like something I've introduced with my own change (79fe65d) but I don't know what the fix is.

darkroom view:
![darkroom](https://user-images.githubusercontent.com/9555491/143946440-cf011786-9d8f-4002-8b60-c73a7f3ffea9.png)

lighttable thumbnail:
![thumbnail](https://user-images.githubusercontent.com/9555491/143946477-3e3f5a0b-f3cc-4925-884f-de306db38530.png)

I think the issue might be that `reload_defaults` in color calibration is being run before the white balance module calculates its temperature coefficients in `commit_params` (`reload_defaults` needs accurate coeffs) but I don't know the best way to resolve it.

**Comment by TurboGit** [comment]
How do you reproduce that? I tried but was not able.

**Comment by elstoc** [comment]
I'm not sure. I applied custom wb and color calibration settings and then exited darkroom. It's possible there was some leftover rubbish from an old edit (before my fix) because I can't reproduce it again now.

**Comment by elstoc** [comment]
Ok I have a consistent reproducer (after discarding history in the lighttable or darkroom). If I apply my custom white balance and color calibration settings, and then use the color picker in the color calibration module to select a neutral area of the image that seems to do it. Another example:

darkroom:
![Screenshot_2021-11-29_22-11-11](https://user-images.githubusercontent.com/9555491/143950929-9da70da2-d636-4327-b062-8af527d0b266.png)

lighttable:
![Screenshot_2021-11-29_22-11-27](https://user-images.githubusercontent.com/9555491/143950960-987a5138-83f5-4d56-8ccc-ebafacca0659.png)

**Comment by elstoc** [comment]
Raw file: https://www.dropbox.com/s/b4y2lj0v1x53psj/2021-11-08-13.37.58.0.cr2?dl=0

Style containing wb customisations: https://www.dropbox.com/s/hu0ru74lyb6obmz/Better%20WB%20attempt%204.dtstyle?dl=0

**Comment by elstoc** [comment]
I get the same thing if I disable color calibration so this looks to be solely a white balance issue. In fact it looks just like selecting D65 in the white balance module.
