### ISSUE TITLE
HDR alignment

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#10523]
Create HDR in Lighttable is quite nice, it allows me to merge .NEF images and straight work on them in the Darkroom, however, I have a hard time getting images that are alligned SOOC. Is Darktable going to support alignment? It would greatly help as I did not find any other working tool on Linux that would export to raw or at least have satisfactory results as a jpg or a tiff.

**Comment by ralfbrown** [comment]
Have you looked at hugin?  It's not just for stitching panoramas, it also does HDR merging with image alignment and focus stacking.  dt has a Lua script to integrate it.

**Comment by Pizzacutter-at-tty3** [comment]
I remember doing something with hugin, but later, until now I couldn't get it to do anything but panoramas

**Comment by moy** [comment]
Proper image alignment is a non-trivial thing, and dt is unlikely to ever be as good as Hugin with that. The HDR feature of dt is a simple-to-implement one (IIRC, merge is done before demosaic, only very simple per-pixel maths involved) and can't just be "improved" to support alignment, one would need a totally different algorithm.

IOW, either use a tripod or use Hugin ;-) (possibly using the lua script https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/contrib/hugin/).

**Comment by Pizzacutter-at-tty3** [comment]
> Proper image alignment is a non-trivial thing, and dt is unlikely to ever be as good as Hugin with that. The HDR feature of dt is a simple-to-implement one (IIRC, merge is done before demosaic, only very simple per-pixel maths involved) and can't just be "improved" to support alignment, one would need a totally different algorithm.
> 
> IOW, either use a tripod or use Hugin ;-) (possibly using the lua script https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/contrib/hugin/).

Seems to be a nice idea, but for me it does not work almost at all. If I set DRI/DFF in export module, it let me set export location _(there were 3 lines to select location, quite confusing)_, but not anymore. Can I find it somewhere? Also, align_stack_image fails so it is no help for me.

**Comment by Pizzacutter-at-tty3** [comment]
It took me a while, but I eventually figured it out. It works very well :smile: That enfuse in export module (DRI/DFF thing) is quite confusing though. Speaking of that, could the whole enfuse script be a part of Darktable by default? Maybe with some tutorial for new users... So it's a bit easier to get it going

**Comment by HansBull** [comment]
[`hdrmerge`](https://jcelaya.github.io/hdrmerge/) can already compensate small disalignments, so this should not be too hard to implement.

**Comment by AyushGupta10** [comment]
@aurelienpierre had written a post about creating HDR/ Panorama using hugin and darktable. 
Here is the link:
https://discuss.pixls.us/t/hugin-pano-hdr-darktable-in-scene-referred/27087
