### ISSUE TITLE
crop / rotate and perspective don't prioritise GPU

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10538]
I've recently noticed a slowdown using both the _crop_ and the _rotate and perspective_ modules and it seems that these modules are processing the full and preview pixelpipes with the wrong priority.

I have my OpenCL setting set to "very fast GPU" so I would expect both pipes to be processed on the GPU and for neither to use my CPU. However, I often (not always) see the following instead, and note an asociated slowdown in processing

```
13.526286 [pixelpipe_process] [preview/fast] using device 0
13.526317 [pixelpipe_process] [full] using device -1
[lens correction] camera/lens not found
14.531432 [pixelpipe_process] [preview/fast] using device 0
14.531497 [pixelpipe_process] [full] using device -1
```

Once I close the offending module it appears to go back to using device 0 for both pipes again. Shouldn't these modules either use device 0 for both pipes or prioritise 0 for the full pipe?

**Comment by elstoc** [comment]
@AlicVB I'm tentatively pinging you here but only because you last worked on the modules in question.

**Comment by elstoc** [comment]
Also very noticeable because I'm using diffuse/sharpen in my workflow and when that goes to the CPU I might as well go and get a coffee.

**Comment by AlicVB** [comment]
> @AlicVB I'm tentatively pinging you here (more spam) but only because you last worked on the modules in question.

nice try, but I know your are laughing in secret ;)

more seriously, I'll have a look (and try to reproduce first), but I don't know anything about all this part of dt...

**Comment by elstoc** [comment]
crop & rotate too

**Comment by elstoc** [comment]
One thing those modules all have in common: "IOP_FLAGS_ALLOW_FAST_PIPE"

**Comment by AlicVB** [comment]
ok, so I manage to reproduce, and yes, it seems to be related to that flag... @TurboGit : maybe you'll have some ideas, as git blames points to you here... thanks !

**Comment by elstoc** [comment]
I've put the 3.8 milestone on this because people will be using diffuse in 3.8 (since it's a new toy) and this is really noticeable when that module is active.
