### ISSUE TITLE
Getting Unhhandled exception and thus cannot start Darktable since updating to 3.6.1

### ISSUE THREAD

**Issue by Bergylta** [darktable-org/darktable#10537]
**Introduction**
So, i have updated darktable to 3,6,1, but since update, i keep getting "Unhandled exception occurred" and thus cannot start darktable.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. I click on the icon for darktable
2. black window quickly appears and disappears

**Expected behavior**

This is what the traceback says:
this is darktable 3.6.1 reporting an exception:

-------------------

Error occurred on Wednesday, December 1, 2021 at 21:14:48.

darktable.exe caused an Unknown [0xC06D007E] Exception at location 000007FEFD41A06D in module KERNELBASE.dll.

AddrPC           Params
000007FEFD41A06D FFFFFFFFFFFFFFFE 0000000000000000 00000000038BC200  KERNELBASE.dll!RaiseException
000007FED1512439 00000000038BC100 000000000024DB90 0000000000000000  intelocl.dll!clGetDeviceIDsFromDX9INTEL
000007FED1512264 0000000000000000 00000010004D0010 00000000038BC1D0  intelocl.dll!clGetDeviceIDsFromDX9INTEL
000007FED14DD89A 000007FED1543B68 00000000038BA860 0000000000000001  intelocl.dll!clGetDeviceIDsFromDX9INTEL
000007FED14DDA8D 000007FED1543B68 00000000038BA860 000007FED15BA4E0  intelocl.dll!clGetDeviceIDsFromDX9INTEL
000007FED14D3711 000007FED15BA4E0 000007FED15BA0C0 0000000002BF7F70  intelocl.dll!clGetPlatformIDs
000007FED159823F 000000000024EBE0 0000000000000000 0000000000000000  IntelOpenCL64.dll!clGetExtensionFunctionAddressForPlatform
000007FED15817CB 000007FED1581780 0000000000000005 0000000000000005  IntelOpenCL64.dll!clGetPlatformIDs
000007FED15D107D 0000000000000000 000000000000007F 0000000000000000  OpenCL.dll!0x7fe0000107d
000007FED15D38F7 0000000005E7CF40 0000000000000014 000000000420C761  OpenCL.dll!clSetUserEventStatus
000007FED15D125F 0000000000000300 0000000005E7CF40 000000000420C840  OpenCL.dll!clGetPlatformIDs
000007FEE7095D16 000000000024F740 0000000005E55C40 0000000000000000  libdarktable.dll!dt_opencl_init
000007FEE6FF290C 000007FE00000001 0000000000548450 0000000000000001  libdarktable.dll!dt_init
000000013F492A39 0000000000548430 00009FC000000001 0000000000000000  darktable.exe!0x100002a39
000000013F4915B5 000000000000005A 0000000000000000 000000013F497050  darktable.exe!0x1000015b5
000000013F4913D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x1000013d4
000000013F491506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x100001506
00000000773359CD 0000000000000000 0000000000000000 0000000000000000  kernel32.dll!BaseThreadInitThunk
000000007756A561 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.6.1.0
ntdll.dll   	6.1.7601.23915
aswhook.dll 	21.9.6698.0
kernel32.dll	6.1.7601.23915
KERNELBASE.dll	6.1.7601.23915
msvcrt.dll  	7.0.7601.17744
libintl-8.dll	0.19.8.0
ADVAPI32.dll	6.1.7601.23915
sechost.dll 	6.1.7601.18869
RPCRT4.dll  	6.1.7601.23915
libiconv-2.dll	1.16.0.0
libglib-2.0-0.dll	2.68.3.0
ole32.dll   	6.1.7601.23889
GDI32.dll   	6.1.7601.23914
USER32.dll  	6.1.7601.23594
LPK.dll     	6.1.7601.23930
USP10.dll   	1.626.7601.23894
libwinpthread-1.dll	1.0.0.0
SHELL32.dll 	6.1.7601.23893
SHLWAPI.dll 	6.1.7601.17514
WS2_32.dll  	6.1.7601.23451
NSI.dll     	6.1.7601.23889
libpcre-1.dll
libdarktable.dll
PSAPI.DLL   	6.1.7600.16385
libgcc_s_seh-1.dll
libstdc++-6.dll
libcairo-2.dll
MSIMG32.dll 	6.1.7600.16385
libfontconfig-1.dll
libexpat-1.dll
libfreetype-6.dll	2.10.4.0
libbz2-1.dll
libbrotlidec.dll
libbrotlicommon.dll
libharfbuzz-0.dll
libgraphite2.dll
libpng16-16.dll
zlib1.dll
libpixman-1-0.dll
exchndl.dll 	0.9.2.0
mgwhelp.dll 	0.9.2.0
dbghelp.dll 	6.1.7601.17514
VERSION.dll 	6.1.7600.16385
libgdk-3-0.dll	3.24.29.0
dwmapi.dll  	6.1.7601.18917
IMM32.dll   	6.1.7600.16385
MSCTF.dll   	6.1.7601.23915
SETUPAPI.dll	6.1.7601.17514
CFGMGR32.dll	6.1.7601.17514
OLEAUT32.dll	6.1.7601.23775
DEVOBJ.dll  	6.1.7600.16385
WINMM.dll   	6.1.7600.16385
libcairo-gobject-2.dll
libgobject-2.0-0.dll	2.68.3.0
libffi-7.dll
libepoxy-0.dll
libfribidi-0.dll
libgdk_pixbuf-2.0-0.dll	2.42.4.0
gdiplus.dll 	6.1.7601.23894
libgio-2.0-0.dll	2.68.3.0
DNSAPI.dll  	6.1.7601.17570
IPHLPAPI.DLL	6.1.7601.17514
WINNSI.DLL  	6.1.7601.23889
libgmodule-2.0-0.dll	2.68.3.0
libpango-1.0-0.dll	1.48.5.0
libthai-0.dll
libdatrie-1.dll
libpangocairo-1.0-0.dll	1.48.5.0
libpangoft2-1.0-0.dll	1.48.5.0
libpangowin32-1.0-0.dll	1.48.5.0
libgtk-3-0.dll	3.24.29.0
COMCTL32.dll	6.10.7601.18837
comdlg32.dll	6.1.7601.17514
WINSPOOL.DRV	6.1.7601.17514
libatk-1.0-0.dll	2.36.0.0
lua53.dll
libgomp-1.dll
libavif.dll
libaom.dll
libdav1d.dll	5.1.0.0
rav1e.dll
USERENV.dll 	6.1.7601.17514
profapi.dll 	6.1.7600.16385
libcurl-4.dll
CRYPT32.dll 	6.1.7601.23769
MSASN1.dll  	6.1.7601.17514
WLDAP32.dll 	6.1.7601.23889
libcrypto-1_1-x64.dll	1.1.1.11
libidn2-0.dll
libunistring-2.dll	0.9.10.0
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.11
libzstd.dll
libexiv2.dll
libgphoto2-6.dll
libgphoto2_port-12.dll
libltdl-7.dll
libsystre-0.dll
libtre-5.dll
libexif-12.dll
libGraphicsMagick-3.dll
liblcms2-2.dll
libicuin68.dll
libicuuc68.dll
libicudt68.dll
libIlmImf-2_5.dll
libHalf-2_5.dll
libIex-2_5.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
libopenjp2-7.dll
libpugixml.dll	1.11.0.0
librsvg-2-2.dll
libxml2-2.dll
liblzma-5.dll	5.2.5.0
libsecret-1-0.dll
libgcrypt-20.dll	1.9.2.0
libgpg-error-0.dll	1.42.0.0
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libdeflate.dll
libjbig-0.dll
libwebp-7.dll
nvinitx.dll 	10.18.13.5445
detoured.dll
nvd3d9wrapx.dll	10.18.13.5445
nvdxgiwrapx.dll	10.18.13.5445
CRYPTSP.dll 	6.1.7601.23471
rsaenh.dll  	6.1.7600.16385
CRYPTBASE.dll	6.1.7601.23915
uxtheme.dll 	6.1.7600.16385
CLBCatQ.DLL 	2001.12.8530.16385
propsys.dll 	7.0.7601.17514
ntmarta.dll 	6.1.7600.16385
apphelp.dll 	6.1.7601.19050
mswsock.dll 	6.1.7601.23451
wship6.dll  	6.1.7600.16385
WINTRUST.dll	6.1.7601.23769
Wintab32.dll	1.0.5.8
WTSAPI32.dll	6.1.7600.16385
Wacom_Tablet.dll	6.3.9.5
Pen_Tablet.dll	5.3.5.3
IconCodecService.dll	6.1.7600.16385
WindowsCodecs.dll	6.2.9200.21830
winhttp.dll 	6.1.7601.23451
webio.dll   	6.1.7601.23375
SspiCli.dll 	6.1.7601.23915
credssp.dll 	6.1.7601.23915
OpenCL.dll  	1.2.1.0
IntelOpenCL64.dll	1.1.0.1003
intelocl.dll	2.0.0.31360
MSVCP90.dll 	9.0.30729.6161
MSVCR90.dll 	9.0.30729.6161
OPENGL32.dll	6.1.7600.16385
GLU32.dll   	6.1.7600.16385
DDRAW.dll   	6.1.7600.16385
DCIMAN32.dll	6.1.7601.23930

Windows 6.1.7601
DrMingw 0.9.2

-------------------

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.6.1
* OS                : Windows 7 (64 bit)

* Memory            : 8 gb RAM
* Graphics card     : Intel R HD graphics 4000
* Graphics driver   : 10.18.13.5445
* OpenCL installed  : Unknown
* OpenCL activated  : Unknown
* Xorg              : Unknown
* Desktop           : Unknown
* GTK+              : Unknown
* gcc               : Unknown
* cflags            : Unknown
* CMAKE_BUILD_TYPE  : Unknown

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by dterrahe** [comment]
You are not providing a lot of detail, but from the backtrace it seems like the intel video driver may be causing the issue. I would suggest updating it; the version you are using looks around 6 years old. The "current" one is version 15.33.53.5161 (https://www.intel.com/content/www/us/en/support/products/81499/graphics/graphics-for-3rd-generation-intel-processors/intel-hd-graphics-4000.html#drivers-software)
