### ISSUE TITLE
rotate and perspective: drawn lines slightly off

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10532]
When attempting to define perspective lines with the _rotate and perspective_ module, the placement of the lines on the image doesn't quite match where my cursor is. See the following video:

https://user-images.githubusercontent.com/9555491/144247714-a938fe7d-c86a-43bc-99c5-f269b6238e82.mp4

darktable 3.7.0+1585~g5cfdd4c50 on ArchLinux (xfce)

**Comment by elstoc** [comment]
@AlicVB would you mind taking a look at this please.

**Comment by elstoc** [comment]
This one also seems related to the reduced preview resolution setting. It occurs if I set it to 1/2 but not if I set it to "original" (which was how I originally tested). It's worse the lower I set it to.

**Comment by AlicVB** [comment]
OK, got this one :) (also reproducible with "normal" preview res, but zoom at 400%) "just" a stupid mistake in rounding... I'll look at the other to put all fixes in the same PR...

but be careful, you are currently suspected of a massive spam attack :D

**Comment by elstoc** [comment]
Also worth noting that when I changed between preview resolution settings and restarted the saved lines weren't in the same place.
