### ISSUE TITLE
Darktable windows invisible on Fedora 35/Gnome/Wayland

### ISSUE THREAD

**Issue by shlyakpavel** [darktable-org/darktable#10531]
**Describe the bug/issue**
Darktable window is invisible on wayland (the whole windows is kind of transparent). It also scares me with terminal messages

**To Reproduce**
1. Install Fedora 35 on Pinebook Pro
2. Install darktable either as rpm or as flatpack
3. Login into wayland session
4. Try to launch darktable 

**Expected behavior**
Darktable launches on both X11 and Wayland

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                :  Linux - kernel 5.14.13 
* Linux - Distro    : Fedora Workstation 35
* Memory            :  4gb ram
* Graphics card     :  mali T860
* Graphics driver   :  panfrost
* OpenCL installed  :  unknown
* OpenCL activated  :  unknown
* Xorg              :  no
* Desktop           :  Gnome
* GTK+              :  unknown
* gcc               :  unknown
* cflags            :  unknown
* CMAKE_BUILD_TYPE  : unknown 

**Additional context**
On both X11 and Wayland terminal output is as follows:
```
[dt_detect_cpu_features] Not implemented for this architecture.
[dt_detect_cpu_features] Please contribute a patch.
[dt_init] SSE2 instruction set is unavailable.
[dt_init] expect a LOT of functionality to be broken. you have been warned.
[defaults] found a 64-bit system with 3954716 kb ram and 6 cores (0 atom based)
[defaults] setting high quality defaults
[dt_detect_cpu_features] Not implemented for this architecture.
[dt_detect_cpu_features] Please contribute a patch.
[dt_codepaths_init] will be using HIGHLY EXPERIMENTAL plain OpenMP SIMD codepath.
[dt_codepaths_init] SSE2-optimized codepath is disabled or unavailable.
[dt_codepaths_init] expect a LOT of functionality to be broken. you have been warned.
```
Feels creepy
Also I want to mention I previously installed darktable on Manjaro on the same laptop and it worked fine (KDE/Wayland)

**Comment by shlyakpavel** [comment]
![изображение](https://user-images.githubusercontent.com/19782228/144231434-e90e1595-b0ad-4a1d-9f1a-9f8774b888f3.png)
![изображение](https://user-images.githubusercontent.com/19782228/144231533-a40af64e-7ef6-487f-9a8a-6afbbc3d8bf9.png)

**Comment by Nilvus** [comment]
Which darktable version you really use? darktable 3.5.0+250 is a quite old one. Official actual release is darktable 3.6.1 and actual master is 3.7.0.

Wayland is not officially supported by darktable and wayland is actually not recommanded for image edition (color management is not totally implemented.

You could see more answers about that here: https://github.com/darktable-org/darktable/issues/7784 and here : https://www.collabora.com/news-and-blog/blog/2020/11/19/developing-wayland-color-management-and-high-dynamic-range/

Last article is one year ago but it's still true.You could see that his is WIP for Wayland: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14

Said that, there will probably no official support for darktable for a long time and without proper color management in Wayland. I let this open anyway quite few days in case someone else will add something here.

I so recommend you to use X11 instead.

**Comment by shlyakpavel** [comment]
> Which darktable version you really use? darktable 3.5.0+250 is a quite old one. Official actual release is darktable 3.6.1 and actual master is 3.7.0+1597~g655e790a5.

It is my fault: I forgot to edit the issue template. Version is 3.6.1

**Comment by shlyakpavel** [comment]
What about `[dt_init] expect a LOT of functionality to be broken. you have been warned.`?

**Comment by Nilvus** [comment]
I don't know but it could be related to wayland so please test before with X11. If you have same thing with X11, that would probably mean something else, not directly related to wayland and so to your system. darktable 3.6.1 works really great on X11. Begin to test that.

**Comment by shlyakpavel** [comment]
Check the original message. I tested it on x11. It works, but writes these scary things to terminal output

**Comment by dterrahe** [comment]
I'm curious how much testing dt gets on the combination of ARM and Wayland. Are any developers using this?

**Comment by shlyakpavel** [comment]
For your information: darktable runs on Wayland if I manually set GDK_BACKEND=wayland
The problem was somehow related to xwayland

**Comment by HansBull** [comment]
So this can be closed, since the problem is upstream? Btw, nice to see that darktable is used on ARM hardware, too.

**Comment by jzbor** [comment]
I am pretty sure this is an upstream problem with the T860 GPU. I also have one and xwayland on GNOME just does not seem to work.
