### ISSUE TITLE
rotate and perspective: cannot modify very short lines

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10535]
When using line drawing mode in the rotate and perspective module, if I accidentally draw a line that's short enough to only show the two nodes (with no line separating them) it is not possible to delete the line with right-click or to click-and-drag on the nodes to lengthen them. For example:

![Screenshot_2021-12-01_14-15-31](https://user-images.githubusercontent.com/9555491/144250132-17893860-9598-4694-80ed-fad96677a0d2.png)

If I disable and then re-enable drawing mode only a single node is shown:

![Screenshot_2021-12-01_14-15-47](https://user-images.githubusercontent.com/9555491/144250153-c7c20611-cf05-4966-9a36-69951539c4a5.png)

darktable 3.7.0+1585~g5cfdd4c50 on ArchLinux

**Comment by MStraeten** [comment]
do you have a reduced preview resolution set via preferences?

**Comment by elstoc** [comment]
yes I have it set to 1/2
