### ISSUE TITLE
some mask manager issues

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10548]
Sorry I didn't quite get around to testing the mask changes yesterday but I've noticed a few minor issues as part of investigating for the documentation.

I first create a set of circles to form a mask on the exposure module. If I right-click on that group in the mask manager, options to "duplicate this shape" and "delete this shape" appear in the pop-up menu. These names don't really make sense as this is not a "shape" but a "group" of shapes.

If I create some additional shapes that aren't part of the group, and then I click on the "add existing shape" option in the right-click menu, the sub-menu is empty but a list of the additional shapes (here, "copy of..." shapes) appears in the initial menu. This looks like an error (the "copy of" shapes should appear in the sub-menu).

![Screenshot_2021-12-03_08-07-38](https://user-images.githubusercontent.com/9555491/144567676-0500178c-8c84-4371-92da-481785ef09ce.png)

If there are no ungrouped shapes, the "add existing shape" option still appears. Ideally this sub-menu would be context-sensitive and wouldn't appear if there weren't any additional shapes.

The ability to select multiple shapes in the mask manager implies the ability to act on those shapes at the same time. I wonder if it might be better, when multiple shapes are selected, to be able to use shortcuts (opacity, feathering, etc.) on one shape and have them apply to all selected shapes. Or is this just intended so that you can see all the shapes at the same time?

I'm not sure how much of this is intentional functionality and how much is worth targeting for 4.0.

**Comment by TurboGit** [comment]
At least for 3.8 fix empty sub-menu & duplicate/delete entry on group. Those are plain bugs to me.

**Comment by elstoc** [comment]
Agreed
