### ISSUE TITLE
libraw vs rawspeed

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#10545]
It seems there may be cameras, i noticed "Fujifilm GFX50S II" which are supported by libraw but not in rawspeed.
As result darktable doesn't load it. 
Just fyi. Maybe allowing libraw for unsupported cameras may be beneficial without much effort.

**Comment by Nilvus** [comment]
You don't precise which darktable release you use as asked in template issue!
Libraw had just been added to actual darktable master (so future 3.8) for Canon CR3 Raw. That should answer your issue. Think about closing this issue if you.

**Comment by Dannny1** [comment]
Hello @Nilvus , i think you misunderstood.
This wasn't about canon or cr3. Just seems there may be other supported cameras like the mentioned Fuji supported by libraw.
Just a heads-up.... it may make your live easier with the camera support.

**Comment by TurboGit** [comment]
> This wasn't about canon or cr3. Just seems there may be other supported cameras like the mentioned Fuji supported by libraw.

We may do that in the future but for now it was a rush to integrate LibRAW to get CR3 support and we don't want to introduce more just before the release.

**Comment by Dannny1** [comment]
I see, thanks for the clarification.

**Comment by kmilos** [comment]
> i noticed "Fujifilm GFX50S II"

If you have the camera, please consider [uploading the sampe(s) and opening a formal camera support request.](https://github.com/darktable-org/darktable/wiki/Camera-support)

**Comment by Dannny1** [comment]
No i don't have it, i was just playing with some sample files. So i added few new cameras to my darktable build. 
Then i realized that the support is already in libraw.
