### ISSUE TITLE
[FR] Rearrange LUA modules in lighttable

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#10540]
**Is your feature request related to a problem? Please describe.**
Generally I have a set of active LUA modules to start at the beginning of the darktable, I use those modules but some of them like "rename images" or "transfer hierarchy" are interposed in the right panel to the order that brings the program by default as is the "history stack" that its use is quite crucial in the lighttable. 

**Describe the solution you'd like**
It would be nice to have the possibility to rearrange the position of the modules or to pass LUA modules under the default darktable ones.

**Additional context**
![Screenshot from 2021-12-01 16-51-53](https://user-images.githubusercontent.com/67672868/144324839-b29e1d0f-8859-4363-a0d1-5d014aef3da0.png)

**Comment by Nilvus** [comment]
@wpferguson

**Comment by wpferguson** [comment]
The placement of rename_images and transfer_hierarchy is based on them being image operations, so they are placed with the rest of the image operations (select and selected images).

You could modify the code by changing the location in the [darktable.register_lib](https://docs.darktable.org/lua/stable/lua.api.manual/darktable/darktable.register_lib/).

It is possible that I could modify script_manager (and all the affected scripts) to give control over where a module is placed, but I'm currently buried by real life and probably wont get to it for 6 - 9 months.

This FR should be in the [Lua-Scripts issues](https://github.com/darktable-org/lua-scripts/issues)

**Comment by difrkaguilar** [comment]
@wpferguson Thanks a lot for the information about the placement of LUA modules with the rest of the image operation in select and selected images, Then there is not need to change their position. So I'm going to close this FR now.

> but I'm currently buried by real life

So do I, but hopefully in 4 months I'll end one of my biggest projects. :-)
