### ISSUE TITLE
FR: Change value range of the contrast compensation slider of the Tone Equalizer

### ISSUE THREAD

**Issue by pedrorrodriguez** [darktable-org/darktable#10552]
Since the settings in the masking tab of the Tone Equalizer generally reduce the contrast of the mask, negative values in the contrast compensation slider (reducing contrast of the mask) don't seem to be useful. I suggest the values of the slider go from 0EV to +4EV, so we can have more granular control over that particularly sensitive slider.

**Comment by Mark-64** [comment]
Negative contrast compensation values are not so uncommon, but yeah, positive values are more frequent.
I suggest a soft eange of -1EV to +2EV (+4EV is way too much, it never happens).
