### ISSUE TITLE
Sony Alpha 7 IV (ILCE-7M4)

### ISSUE THREAD

**Issue by noboevbo** [darktable-org/darktable#10556]
I just uploaded the following samples from my Sony Alpha 7 IV (ICLE-7M4) to raw.pixls.us. I hope this samples help to add support for this camera to darktable. If you miss something, please let me know:

- 12bit-compressed
- 12bit-uncompressed
- 12bit-lossless-compressed
- 14bit-compressed
- 14bit-uncompressed
- 14bit-lossless-compressed

**Comment by LebedevRI** [comment]
Thank you for the samples.
Out of the 12-bit ones, only the compressed was actually 12-bit.

**Comment by cryptomilk** [comment]
I wondered how to get 12-bit images. A video I just watched about Sony camers says you get 12bit if you shoot in blub mode. I can try that tomorrow.

**Comment by noboevbo** [comment]
Ahh I thought uncompressed raw in series mode would be 12bit as well, but @cryptomilk  is right, I think it might behave like the 7R4 and produce 12bit only in bulb mode (https://www.sony.de/electronics/support/articles/00229990). I will create two bulb ones for the two missing uncompressed raw modes.

**Comment by cryptomilk** [comment]
@LebedevRI Could we point to https://www.sony.com/electronics/support/articles/00229990 on raw.pixls.us?

**Comment by noboevbo** [comment]
Just a little catch-up: I did a little more research on the bit depth, as I was not able to produce 12bit raw/lossless samples. As so often, the answer can be found in the manual :-)
It states:
RAW images recorded with this camera have a resolution of 14 bits per pixel. However, resolution is limited to 12 bits in the following shooting modes:
    [Cont. Shooting] when [RAW File Type] is set to [Compressed]
Source: https://helpguide.sony.net/ilc/2110/v1/en/contents/TP0003057048.html

So they are able to produce 14bit raws in all modes except compressed cont. shooting. Thus, the provided raws should cover all producable files.
