### ISSUE TITLE
Tried the darktable windows insider program 11/28. Crashed hard!

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#10554]
I have tried the other Windows insider program since 3.6.1 and they have worked for me.
However the 11/28 crashes hard with an Unhandled exception occurring.

[darktable_bt_G6Y0D1.txt](https://github.com/darktable-org/darktable/files/7652439/darktable_bt_G6Y0D1.txt)

**Comment by MStraeten** [comment]
you need to give some more details:
See https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by bengtfalke** [comment]
When I try to start DT it never opens,  just shows a sign with Unhandled exception occured. I could go back to the previous version. See the attached file on the original post.

darktable version : 3.70 + 1572
OS : Win10 19042.1288
Memory : 32 GB
Graphics card : Gigabyte GeForce RTX 2070 SUPER OC 3X
Graphics driver : 30.0.14.9613
OpenCL installed : yes
OpenCL activated : yes
M2 SSD disks

**Comment by wpferguson** [comment]
Just built tonights update and tested on win10.  Runs without problems, in my brief test.

**Comment by Dannny1** [comment]
Workaround for me was to delete/rename libportmidi.dll
It happens on start for me with last 2 builds (1572,1637) on W8.1. After deleting it starts fine.

**Comment by wpferguson** [comment]
Did libportmidi.dll come with the darktable build or was it part windows?

**Comment by bengtfalke** [comment]
I Have AMD Ryzen 9 3900 processor if that can be of any importance?

**Comment by Dannny1** [comment]
It seems to come with these newer builds.
Default location...Program Files\darktable\bin

**Comment by bengtfalke** [comment]
Hmmm odd! I cant find that dll in that location or anywhere on my system?

**Comment by bengtfalke** [comment]
I can go back to version 1514 and that works fine but version 1572 and 1637 crashes on starting.....

**Comment by Dannny1** [comment]
Really odd, your trace also shows this file:
"darktable.exe caused an Access Violation at location 0000000070C41812 in module libportmidi.dll..."

**Comment by bengtfalke** [comment]
Mystery solved...   lol
It seems it is a new file in version 1572 and 1637 so when I reinstalled version 1514 it was deleted during the install. Tehn I installed version 1637 and renamed that file it all seems to work.... how odd.
So the problem on mine and your system seems to be libportmidi.dll... where it comes form?

**Comment by wpferguson** [comment]
What version of windows are you running?  I'm away from my computer right now so I can't check the portmidi lib.  I did test the latest build on win 10 and it worked for me, but I'm not sure what version of win 10 I have.

**Comment by bengtfalke** [comment]
My windows version: Windows 10 Home, version 20H2, OS version: 19042.1348

**Comment by wpferguson** [comment]
My Win10 is Pro, 21H2, OS version 19043.1348.  

I'm not having crash problems.  Tried on Win11, works fine there too.

libportmidi.dll is included with darktable to provide support for midi input devices.  If you're not using midi devices then yes, it's probably ok to rename it.  The real answer is try it and see what happens.

Are any of you running any midi devices?  Are any of you running any midi applications?

**Comment by wpferguson** [comment]
What language are you using?  There is a somewhat similar problem on MacOS for users of french and a few other languages

**Comment by dterrahe** [comment]
Do we know which version of portmidi is included in the windows insider build? There was a recent update that resolved a crash that happened when darktable was started with any midi device connected.

In this case, @bengtfalke do you have a midi device connected at all? Maybe a software device? (I assume not, otherwise libportmidi probably would ring a bell, but worth asking anyway.)

**Comment by wpferguson** [comment]
The windows insider build was built with mingw-w64-x86_64-libportmidi-217-2.  Looking in git there is a new version, 234-1, but it seems to be just a packaging change (libportmidi is now part of portmedia).  I did try updating with pacman but it said that 2170-2 was still the current version

**Comment by kmilos** [comment]
> I did try updating with pacman but it said that 2170-2 was still the current version

Need to run `pacman -Sy` first?

And I think it was more than a packaging change [according to this comment](https://github.com/darktable-org/darktable/pull/10463#issuecomment-976453432).

**Comment by kmilos** [comment]
Btw, have you tried the [nightly builds](https://github.com/darktable-org/darktable/actions/workflows/nightly.yml)? Those are working ok for me so far on Windows 10 20H2 19042.1348...

**Comment by bengtfalke** [comment]
This Pc is in my music studio and have both midi controllers (mostly connected via USB midi) and midi programs on it. But I do not run them at the same time as DT. The sound interface is on all the time and is connected to the computer vi USB and has both audio and midi over USB. It is Maudio air 192/14.
I use DT in English and my Windows Pc is in Swedish.
Are the nightly builds compiled? If so I can of course try them out if you point me to them? I have set up a compile environment a while ago so if necessary I can have a go at that..... ;o)

**Comment by bengtfalke** [comment]
It seems to be fixed now... I downloaded and installed the  Nightly PKG #399: with version 3340c62-dirty. It also installed the new version of libportmidi.dll that is now 35 kB instead of the old version being 39 kB. Now all worked as expected!
Thank you!

**Comment by dterrahe** [comment]
Thanks for reporting and testing!

The air 192/14 looks like an interesting machine. Does it send note and cc messages via USB? Then dt should respond to turning the knobs and you might be able to map them to sliders.

**Comment by bengtfalke** [comment]
No, I do not think the air 192/14 sends cc over midi but I have another controller that I think would be more suitable and that is the Novation Launchcontrol XL mk 2. It is cheap and have lots of sliders and knobs. I use it as a midi mixer but it can be used in many ways to control plugins etc. I also have a Novation Launchpad pro mk 3 that just have 64 pressure sensitive buttons that can be used as sliders and buttons in ways you self define... but that is a bit more expensive but very versatile.

**Comment by dterrahe** [comment]
> Novation Launchcontrol / Launchpad XL / pro mk 2 / 3 

Would be interesting to hear how well you can make those work with the dt midi interface.

The drawback of the Launchcontrol would be that neither the sliders nor the knobs are motorized or limitless (they have hard min/max stops), so when you change from one image to the next, they won't reflect the correct slider settings and you will have to move it first to make it match the actual setting before you can change it. This also limits the precision (to the number of different positions the knobs/sliders can send, probably <= 127). Whereas something like the x-touch mini or beatstep have virtually limitless precision (and adjustable using the shift or ctrl modifier).

But the Launchpad (and the buttons of the Launchcontrol) could still be useful to toggle options and modules. Possibly their lights could (be made to) indicate the current state of those toggles and modules. Although the latter will have to wait until after #10520 gets merged.

If you have any tips on any custom configuration required for these devices to make them work well, please consider contributing to https://github.com/darktable-org/dtdocs/blob/master/content/special-topics/midi-device-support.md

**Comment by wpferguson** [comment]
Upgraded mingw-w64-x86_64-portmidi to 234-1.  This is the most current and same version that the nightly build is using.

**Comment by dterrahe** [comment]
Is it OK to close this bug now?

**Comment by wpferguson** [comment]
I think so.  If it shows up again we can reopen.
