### ISSUE TITLE
FR: Always display Tone EQ's guided filter mask in normal blend mode and full opacity

### ISSUE THREAD

**Issue by pedrorrodriguez** [darktable-org/darktable#10560]
When changing the opacity or the blend mode of the Tone EQ, the mask is also displayed with decreased opacity and in the new blend mode. It would be more useful if the mask would always be displayed in full opacity and normal blend mode. We only care about opacity and blend mode in the final result, and when also applied to the mask, it becomes more difficult to evaluate the quality of the mask you are creating. 

Thanks!

**Comment by aurelienpierre** [comment]
Tone EQ does not have opacity mask, it is a luminance mask. Therefore there is no blending needed or even possible, it's just a grey map.

**Comment by pedrorrodriguez** [comment]
> Tone EQ does not have opacity mask, it is a luminance mask. Therefore there is no blending needed or even possible, it's just a grey map.

I probably didn't explain myself well. It is understood that the tone EQ's mask is a luminance mask. Look what happens when you change opacity or blend mode, though:
Normal
![tone eq mask normal](https://user-images.githubusercontent.com/64545422/159456656-e666dfe9-c321-4763-b91f-a8df33e35b4c.png)

50% opacity
![tone eq mask normal half opacity](https://user-images.githubusercontent.com/64545422/159456725-4885cee7-6885-427f-acf0-b373675e4370.png)

blend mode set to red channel
![tone eq mask red channel](https://user-images.githubusercontent.com/64545422/159456774-2c96cbf2-1473-4cd1-be6f-539d72bae225.png)

In these type of cases, I can't really tell what the mask is doing. My suggestion was to always display the luminance mask like in normal mode, not let it be affected by opacity or blend mode.
