### ISSUE TITLE
Fuji X-T4 RAF lossless compressed not work

### ISSUE THREAD

**Issue by Hubhubhurra** [darktable-org/darktable#10566]
Fuji X-T4 RAF lossless compressed only show "can not open"

**To Reproduce**
1. Go to "copy & import"
2. Select RAF-file with lossless compression
3. import
4. See no image-thumbnail
![grafik](https://user-images.githubusercontent.com/47603473/144759770-cd6c0758-5abb-4d8e-97ca-247848a4a56d.png)

**Platform**

* darktable version : 3.4.1-5 (from stable) and also 3.6.1-1.1 (from http://download.opensuse.org/repositories/graphics:/darktable/Debian_11)
* OS                : linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
* Linux - Distro    : debian bullseye (aka 11)

As example two files:
https://acadfs1.arch.tu-dresden.de/DSCF0064.RAF
https://acadfs1.arch.tu-dresden.de/DSCF0069.RAF

It must be shown that
https://acadfs1.arch.tu-dresden.de/DSCF0064.JPG
https://acadfs1.arch.tu-dresden.de/DSCF0069.JPG

**Comment by kmilos** [comment]
These RAF files seem to be corrupted during transfer from camera in some way, there is some crucial header info (148 bytes) missing at the start compared to the X-T4/X-S10/ samples on [RPU](https://raw.pixls.us/)...

**Comment by Hubhubhurra** [comment]
Hallo kmilos,
yes the files with extensions .JPG are JPEGs. I posted this links only to demonstrate the picture. But the files with extensions .RAF should be compresed RAF-files - and you are rigth: The error is in my camera. If I use compressed RAF the JPEG saved twice - once with extension RAF and once with extension JPG. This is a bug since last firmware-upgrade 1.25 from 2021/11/30. 
Thank you for support!
