### ISSUE TITLE
color picker: live picker is no longer live

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#10567]
in 3.6.1 the live mode in colorpicker changed picker values in selected areas even if the color picker itself is not active (highlighted)
With current master these values aren't updated if the picker isn't active.

**To Reproduce**
1. pick some colors and add them to live samples
2. keep picker activated
3. change exposure - see live samples values changing
4. deactivate picker
5. change exposure 
6. Error: live samples aren't changing

**Expected behavior**
live samples are live ;)

**Which commit introduced the error**
need to have a look at older builds ..

**Platform**
* darktable version :  darktable 3.7.0+1641~g2861a322b-dirty
* OS                : OSx

**Comment by paolodepetrillo** [comment]
The most recent commit where this worked is e5040232.
