### ISSUE TITLE
no picker area in rgb curve (and probably other graphs)

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#10573]
**Describe the bug/issue**

When using the color picker with the "`RGB curve`" module active the selected color or selected color area must be displayed on the graph of the "`RGB curve`" module. 

**To Reproduce**
1. Go to darkroom
2. Open `rgb curve` module 
3. Go to color picker module
4. Click on picker and select a point on the image (or ctrl-click the picker and select an area)
5. See, no corresponding area display on the graph of the `rgb curve` module.

**Expected behavior**

Area should be displayed.

**Comment by TurboGit** [comment]
@dtorop or @paolodepetrillo : Can one of you have a look?

**Comment by TurboGit** [comment]
Looks like this has been broken since a long time as it was not working on 3.6.

**Comment by elstoc** [comment]
I thought this was only supposed to work with the in-module color picker, not the global color picker module.

**Comment by TurboGit** [comment]
@elstoc : Hum... how embarrassing :) You're plain right, I was doing some testing on color picker to see if all was working fine but it seems I was too zealous :) Sorry for the noise.
