### ISSUE TITLE
Apply white balance to masks

### ISSUE THREAD

**Issue by echarlie** [darktable-org/darktable#10578]
**Is your feature request related to a problem? Please describe.**

Frequently in low-light photography (e.g. cave photography), I'll be using several light sources, often with different beam patterns or aimed at different locations, which may not have matched colour temperatures. White balance in darktable is only applied globably to an image; as a consequence, I may have a foreground that is too warm (3000K light) or background that is too cold (5600K light). If I split the difference, everything looks off.

**Describe the solution you'd like**

I would like to be able to duplicate white balance filter instances and apply them with drawn masks, like e.g. sharpening filters, rather than only being able to apply them globally.

**Alternatives**

None apparent (other than me getting gear with matched colour temperatures).

**Comment by pedrorrodriguez** [comment]
This feature is in the color calibration module. The white balance module should be left on camera reference, and fine tune WB in the CAT tab of color calibration (which can be duplicated and applied only to a certain area)

**Comment by echarlie** [comment]
I do see this in the documentation now. Its use is subtle.

**Comment by johnny-bit** [comment]
Actually color calibration was created to solve such issues (among others) and I use it that way for similar purposes. If you have 2 light sources "easy" way to mask would be to create mask for one and then apply inverse raster mask to another - that way you don't have even slight fringing. In situation with multiuple light sources... well you have to play with it unfortunately.
