### ISSUE TITLE
tagging match not working

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#10587]
**Describe the bug/issue**

The completion in the tagging lib used to match any known tag in the database. This was quite handy. Now it seems that after one char is entered into the entry the match is mostly working (matching sub-string in the tag db) but as soon as I enter a second char the completion seems to be done only on tag prefix. And when I enter a third chars there is no completion at all even though I know that there is tags to be matched. 

**To Reproduce**
1. Go to 'tagging'
2. Start entering some text
3. Completion is empty most of the case after entering more than 2 chars

**Expected behavior**

Partial matching of tags in the database.

**Comment by TurboGit** [comment]
@phweyland : Can you have a look? The current behavior make it very hard to find tags already present in the db and so to assign proper tag to new images.

**Comment by phweyland** [comment]
Yes I'll do.

**Comment by phweyland** [comment]
Setting for  "disable entry completion" Off,
Dictionary view on list:
![image](https://user-images.githubusercontent.com/23012047/145201107-a7243d60-0290-4552-9c6d-f4e28c13fc79.png)

In tree view (no completion but filtering of tags):
![image](https://user-images.githubusercontent.com/23012047/145200618-8eef30bf-cde1-4641-8084-9b8b912240e5.png)
 
If that last case your issue ?
If not, can you be more accurate on the description of the failing case please ?

**Comment by TurboGit** [comment]
> PS2: make sure you exit the "suggestions" list.

That was it! I didn't remembered this option, and indeed it makes sense now. When this option is selected I have only part of the tags and this explained why I was not able to find some! So this report is all noise, closing.

**Comment by phweyland** [comment]
Good! 
I was wondering if we should not remove it. This is not the first time someone is tricked. And its logic is so weak that I doubt it serves anybody...
