### ISSUE TITLE
DT crashes in Darkroom with assertion failure around Pango (Mac)

### ISSUE THREAD

**Issue by jonastr** [darktable-org/darktable#10588]
**Did you buy darktable from an application store ?**
no

**Describe the bug/issue**
I've compiled DT from current master. It frequently crashes with the following assertion error when in Darkroom. 

```
**
Pango:ERROR:../pango/pango-layout.c:3717:shape_run: assertion failed: (state->last_tab.glyphs->num_glyphs == 1)
Bail out! Pango:ERROR:../pango/pango-layout.c:3717:shape_run: assertion failed: (state->last_tab.glyphs->num_glyphs == 1)
```

**To Reproduce**
1. Select picture to edit in darkroom
2. Navigate cursor around, no need to click anything
3. It crashes with the assertion as shown above

So far, I was not yet able to nail it down more precisely. In the moment it crashes, I am not doing anything specifically, other than moving the mouse. So, I suspect it's somehow related to hovering over some UI element.

I can't consistently reproduce it, but I've seen it happening quite frequently recently.
**Expected behavior**
No crash

**Which commit introduced the error**
I am not aware of this happening on older commits from master (say 1 month ago). My current build is `3.7.0+1643~g19c6a5011` and this issue was also present in `3.7.0+1546~g9295771f4`

I did not yet have time to do a bisect and it would be tricky to do as I don't know exactly how to reproduce it, so I would not be able to tell which commit is green until it eventually crashes. If that's the only thing that will help, I can try to do it, though.

**Platform**
* darktable version : `3.7.0+1643~g19c6a5011`
* OS                : OSx Big Sur
* Memory            : 16 GB
* Graphics card     : M1 integrated
* Graphics driver   : OSX integrated
* OpenCL installed  : n/a
* OpenCL activated  : n/a
* gcc               :
```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
* cflags            : not aware of any
* CMAKE_BUILD_TYPE  : Release

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version 3.7.0+1546~g9295771f4**
 - Can you reproduce with a RAW or Jpeg or both? **Not sure, I only use DT for RAW files**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **haven't tried, don't think it's related so far**
 - Do you use lua scripts? **no**

**Comment by MStraeten** [comment]
not reproducible with my macports based build with 
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
using  pango @1.48.10_0+quartz

**Comment by jonastr** [comment]
@MStraeten thanks for the feedback!

might be related to pango, also. i am running pango 1.50.0 through homebrew.

**Comment by jonastr** [comment]
i've downgraded pango to 1.48.10 to rule this out.

**Comment by ptilopteri** [comment]
did that solve the issue?

**Comment by apfelkraut** [comment]
reproducible with my homebrew based build with
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
using pango 1.50.0 via homebrew

**Comment by jonastr** [comment]
@ptilopteri 
> did that solve the issue?

i'm not 100% sure yet -- as it's not happening every time but rather "quite frequently", i guess i'll have to observe it for a bit longer. i've edited a few images since then - so far no crash. 🤷🏻 

will post back here when i've used DT some more.

**Comment by apfelkraut** [comment]
not reproducible with my homebrew based build with
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
using pango 1.48.10 via homebrew

darktable 3.7.0+1649~g010cdcdf0 crashed within seconds when I went into darkroom and moved the mouse around.

**Comment by paolodepetrillo** [comment]
It is a known issue in pango 1.50.0, was reported for Linux in #10557. There has not been a new release of Pango since the bug was fixed a couple days ago.

**Comment by jonastr** [comment]
@apfelkraut yeah, also for me stable since downgrade.

@paolodepetrillo great, thx for pointing to that! didn't find it when searching through open tickets 😬 so i will close this one for now.

i guess until the fix lands, it's best to pin pango to version 1.48.10 in your package manager of choice. :)
