### ISSUE TITLE
Testing new colorchecker modifications....exposure compenstation not updating...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#10580]
@aurelienpierre   I just build a new WIndows version tonight to test out your changes to the colorchecker in CC module...

The initial computation after setting the grid seems fine and a value for exposure compensation is computed... However making the adjustment in exposure and returning and recalculating does not change the value...does not seem to reflect that you have applied the normalization?? You can keep adding exposure and the value does not change...

Seems like it is working for the check delta E button and recomputing as you would suspect to zero when you add the requested compensation value....just the recompute profile one is not updating after you make the correction...

**Comment by elstoc** [comment]
The exposure computation is absolute now, rather than relative, so this is expected.

**Comment by todd-prior** [comment]
So you set it to the value its not an offset??  But then should it not update to zero still??

**Comment by elstoc** [comment]
Yes just key the values as-is into the exposure module. If the values are absolute I wouldn't expect them to update to zero.

**Comment by todd-prior** [comment]
So I suspect this is what the as-is wording is intended to convey?? I think that is a bit terse for something that now works differently from the previous version. I would suggest a small note that this has changed from the previous version maybe in brackets as part of this sentence might be useful.

**Comment by elstoc** [comment]
You're talking about the user manual? We can't change that now, we're in string freeze.

**Comment by xfh** [comment]
I just run into this as well. Maybe removing the `+` sign from the normalization values would help? https://github.com/darktable-org/darktable/pull/10565#issuecomment-988213656

**Comment by todd-prior** [comment]
Np just suggesting and its confusing as the compute output profile works the old way making it seem like the other one should work that way as well….

**Comment by aurelienpierre** [comment]
> I just run into this as well. Maybe removing the + sign from the normalization values would help? #10565 (comment)

There will still be a - sign when needed, so…

**Comment by xfh** [comment]
> There will still be a - sign when needed, so…

My argument is that darktable usually omits the `+` sign of positive values. Take for instance any slider in color balance rgb, color calibration or exposure. They only show the negative sign, even though the slider ranges are supporting real numbers.

I realise though, that the user interface is not consistent regarding signs. In diffuse or sharpen, the percentage sliders always show a sign -  with the exception of `sharpness`. Certainly, there will be more inconsistencies in other modules. 

I am not really bothered if there is a sign or not. Feel free to close.

**Comment by todd-prior** [comment]
I'll close it ...it just seems funny that the profile evaluation button works the old way....ie calculates the delta E of the current profile ...providing exposure and black level comp values and if you enter those and recalc it goes to zero...so it seems to behave the old way. But the profile generator using the colorchecker is now a fixed value... I felt like that was what was intended but I was confused since each button seemed to work differently as to which was correct......I'll see if there is any further comment and then close later tonight.....
