### ISSUE TITLE
Metadata Editor: Wrap Long Fields

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10582]
When using the metadata editor in the lighttable it is possible to increase the vertical size of the data entry fields. However, when entering long text, the box often instead increases _horizontal_ size until the labels are ellipsized to nothing and then continues to increase until the right-hand-side of the right-hand panel starts disappearing off the edge of the screen. 

![Screenshot_2021-12-07_14-14-21](https://user-images.githubusercontent.com/9555491/145045130-4fc8d59b-61de-4c82-b653-b1c2a63081c0.png)

As soon as I mouse over another image the screen refreshes and the text appears correctly.

![Screenshot_2021-12-07_14-15-58](https://user-images.githubusercontent.com/9555491/145045239-8a575cc8-af80-46a4-aaf1-4da5f0dbab73.png)

**Comment by elstoc** [comment]
@phweyland please could you take a look at this.

**Comment by phweyland** [comment]
I'll do.
