### ISSUE TITLE
DT crashes when opening a photo in Darkroom on Windows10

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#10593]
New unhandled exeption error.
darktable version : Nightly build:
darktable.19c6a5011202ce8c5cad8ca5da1c1a6e839461c6.win64.zip
3.70 + 19c6a50-dirty-win64
OS : Win10 19042.1288
AMD Ryzen 9 3900 processor
Memory : 32 GB
Graphics card : Gigabyte GeForce RTX 2070 SUPER OC 3X
Graphics driver : 30.0.14.9613
OpenCL installed : yes
OpenCL activated : yes
M2 SSD disks
 
Located an old  Cannon CR2 raw photo in Lighttable clicked on it to go to Darkroom and after a few seconds a hard crash with
Unhandled exeption error…

[darktable_bt_A9ZNE1.txt](https://github.com/darktable-org/darktable/files/7684531/darktable_bt_A9ZNE1.txt)

**Comment by dterrahe** [comment]
Does this happen with all photos or just this specific one?

From the crash log it seems the exception is triggered deep within gtk while it is trying to show a tooltip. This usually happens when the mouse is over a particular area/widget of the screen. Can you reproduce for any position of the mouse or is there a particular location/widget that causes problems. Does hiding all panels (with Tab) "solve" the bug, for example?

Does it happen with the dt standard theme without CSS tweaks? What font size/screen resolution? Language?

**Comment by Dannny1** [comment]
I have same issue with nightly builds. Insider builds seems ok in this case.
Env.: W8.1, opencl on/off, 2k resolution, custom profile present or not doesn't matter.
I can't isolate it, happens somewhat randomly after few modules used. Usually when i click on the module header to close it. Often with local contrast module.

**Comment by kmilos** [comment]
pango (again?)

Seems to be updated in MSYS2 repo to 1.50.0 a couple of days ago...

**Comment by kmilos** [comment]
You could try confirm this by replacing the pango dll in your darktable/bin folder with the one from the [previous version archive](https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-pango-1.48.9-2-any.pkg.tar.zst).

**Comment by kmilos** [comment]
It is a bit annoying that you can't pin package versions down w/ MSYS2 (it's a rolling release much like Arch). I guess the strategy of having nighties to catch stuff like this (in addition to bugs in dt code itself) and @wpferguson not updating his build environment not so frequently is a good one!

**Comment by Dannny1** [comment]
Thanks. Seems to be the issue, after replacing pango libs, it didn't crash yet.

**Comment by kmilos** [comment]
FYI, [patched by the MSYS pango maintainer](https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-pango), we should see the benefit in a day or two.

**Comment by bengtfalke** [comment]
There are a few pango.dll:s should I replace all to test this?

**Comment by bengtfalke** [comment]
I replaced all 4 of them and now all seems to be ok.... thank you for your hard and dedicated work!

**Comment by kmilos** [comment]
Update landed in MSYS2 repo, and pango 1.50.1 is released as well.

@bengtfalke I think you can close this issue now,  no?

**Comment by garrett** [comment]
I'm hitting a pango related crash on a build from master on Linux (Fedora 35). I'm not sure if it's related to this issue, so I opened it as a separate bug. (It wouldn't be patched in a Windows build of Pango for sure. :wink:)

**Comment by bengtfalke** [comment]
> Update landed in MSYS2 repo, and pango 1.50.1 is released as well.
> 
> @bengtfalke I think you can close this issue now, no?

Yes I) agree... how do I do that?

**Comment by bengtfalke** [comment]
Thanks for the great work! I love DT and the people creating it!
