### ISSUE TITLE
metadata: scroll bars always active

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10594]
Pull request #10584 implements "always active" scroll bars for each of the GtkTextView widgets in the metadata module. This was done in order to work around bug #10582 and an additional issue mentioned in #10589. It has been settled on as the "least bad" alternative but is far from the ideal solution.

An issue has been raised with Gtk (https://gitlab.gnome.org/GNOME/gtk/-/issues/4042) but I thought it worth raising a new darktable issue just in case anyone has a better solution/workaround and the upstream issue is not addressed.

**Comment by dterrahe** [comment]
I believe this was resolved a few weeks back. Please reopen if I'm mistaken.
