### ISSUE TITLE
crash in pango-layout on Linux (Fedora 35), built from master branch

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#10597]
**Describe the bug/issue**

When working in darktable from git master, it now crashes. Previous nightly builds seemed fine, although I switched between the packaged version and built from source.

**To Reproduce**

1. Compile darktable from git master
2. Edit a raw file (perhaps JPEG too)
3. darktable eventually crashes (unknown exactly why)

**Expected behavior**

darktable shouldn't crash when editing images.

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

I'll try to run a bisect and see if I can narrow it down. As it seems to be somewhat random, but tied to the profile (at least "output color profile" is the last module that is run in the debug before the crash, but who knows what's actually triggering this... as Pango should be related to text layout in the UI)

**Platform**

* darktable version : 3.7.0+1654~ga76f60d26 / a76f60d2664f6c3c491f37e8bc2b30ef9c61307b
* OS                : Linux 5.15.6-200.fc35.x86_64
* Linux - Distro    : Fedora 35
* Memory            : 16 GB
* Graphics card     : Intel Corporation HD Graphics 620 (rev 02)
* Graphics driver   : OpenCL Neo
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : XWayland
* Desktop           : GNOME
* GTK+              : gtk3-3.24.30-4.fc35.x86_64
* gcc               : gcc (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)
* CMAKE_BUILD_TYPE  : Relase & Debug

```
$ darktable --version
this is darktable 3.7.0+1654~ga76f60d26
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  debug build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)?

No. I tried switching back to the nightly build in the RPM and hit the same issue.

 - Can you reproduce with a RAW or Jpeg or both? 

At least raw; unsure about JPEG. This looks like it's a UI update issue related to text, as the error is in Pango.

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? 

Yes.

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? 

Yes

 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

Yes, normally... but it happens without Lua scripts, with an empty config.

This seems very similar to the recent crash on Windows, even though I'm using Linux:
- https://github.com/darktable-org/darktable/issues/10593

The above issue also links to:
- https://github.com/darktable-org/darktable/issues/10588
- https://github.com/darktable-org/darktable/issues/10557

**Comment by AlicVB** [comment]
I would say it's a duplicate of #7092 
can you check your pango version ? there's a bug in the 1.5 version which is fixed now upstream... TIA

**Comment by garrett** [comment]
Ah, so it's the same bug? Here's the upstream issue: https://gitlab.gnome.org/GNOME/pango/-/issues/634

I guess I have to wait for a new Pango. I hope Fedora packages it quickly. Meanwhile, I've downgraded with `sudo dnf downgrade pango\* pango.i686` (which skipped a few versions and brought me down to 1.49.1).

Thanks for letting me know it's fixed upstream! And thanks for your work on darktable too!

(I'll close this bug as it's not darktable specific.)
