### ISSUE TITLE
darkroom tab not highlighted while in darkroom

### ISSUE THREAD

**Issue by dnlyko** [darktable-org/darktable#10598]
windows insider program 12/5

**Comment by dnlyko** [comment]
under further investigation, it seems that the 'darkroom' tab font is indeed highlighted, but the 'lighttable' tab font continues to be highlighted once in 'darkroom' mode.
the 'other' tab clearly is not highlighted.  it seems that there are 3 different degrees of brightness on these tabs.
2 different degrees of brightness would be easier, dim font: inactive, bright font: active.

**Comment by dnlyko** [comment]
i just downloaded the windows insider copy and that is the 1st thing i noticed

**Comment by dnlyko** [comment]
been using now for a couple of hours and have found numerous issues.  just wondering is it proper to post a new issue for each of to just make a list of all my findings and post one issue listing everything

**Comment by ptilopteri** [comment]
separate issues so dev's can track

**Comment by Nilvus** [comment]
@dnlyko: you're right and it's the same in other way. Will check if it's CSS related or not. And if yes, will fix it.

**Comment by Nilvus** [comment]
Indeed, a selected state or not is here and nothing set correctly with CSS. For other issues, yes as @ptilopteri said, better to post separate issues. Just consider that 3.8 code freeze is in 2 days (the 15th).

**Comment by Nilvus** [comment]
@dnlyko: #10616 fix that issue. You could quickly test it by adding those lines in CSS editor in main darktable settings:

```
#darktable_label,
#view_label,
#view_dropdown
{
  color: @button_checked_bg;
}

#view_dropdown label:selected,
#view_label:selected
{
  color: @button_fg;
}
```
