### ISSUE TITLE
Incorrect cropping area repositioning on orientation change if the image is flipped

### ISSUE THREAD

**Issue by e-asphyx** [darktable-org/darktable#10605]
**Describe the bug/issue**
Rotation by *orientation* module causes *crop and rotate* module to incorrectly realign the cropping area if the image was flipped before using *crop and rotate* module. Also *orientation* works in reverse in this case. It's a very common scenario when working with film negatives.

**To Reproduce**
1. Open an image
2. Go to *crop and rotate*
3. Choose flip: horizontal
4. Define the cropping area
5. Go to *orientation*
6. Rotate the image 90º clockwise (it will actually rotate it counterclockwise)
7. See the cropping area positioned incorrectly

**Platform**
* darktable version: 3.6.0+3~g4287791fe
* OS: MacOS

**Comment by AlicVB** [comment]
In current master (which will becomes 3.8 in few days) there has been quite some changes in this area : 
- crop and rotate is deprecated (impossible to maintain)
- new crop module
- flip is moved inside the orientation module
- rotation and keystone is handled by perspective module which is renamed "rotations and perspective"

I've just tested and the second issue seems to be fixed (point 6)
For the other one, it's still here, and in fact this is a limitation of the current design : crop module is placed after orientation in the pipe so than any change in orientation will have some effect on the input image of the crop module...
