### ISSUE TITLE
Canon 5DsR lens correction

### ISSUE THREAD

**Issue by offlinehoster** [darktable-org/darktable#10600]
I just saw, that there is no option to choose the Canon 5DsR at the lens correction/profile filter module. I am able to see my lens, the Irix 11 f4, but my cam the 5DsR is not available. I already uploaded a picture to this https://raw.pixls.us/?thankyou webservice.

Cheers
Christian

**Comment by LebedevRI** [comment]
Lens correction is [lensfun](https://lensfun.github.io/)'s job

**Comment by MStraeten** [comment]
Canon 5DSR is supported by lensfun:
slr-canon.xml:
```
    <camera>
        <maker>Canon</maker>
        <model>Canon EOS 5DS R</model>
        <model lang="en">EOS 5DS R</model>
        <mount>Canon EF</mount>
        <cropfactor>1</cropfactor>
    </camera>

```

**Comment by offlinehoster** [comment]
Thanks @MStraeten 

Well, I did the lensfun-update-data and can now find the 5DS R on the list.

How can I add a lens? For example the Irix 11mm f/4, darktable shows that lens, but is this lens listed on any database of "lensfun" ? Or is this not part of lensfun?

**Comment by MStraeten** [comment]
I checked the lensfun database misc.xml - theres just the irix 15mm. So you might do the profiling yourself and then contribute the result at lensfun: https://pixls.us/articles/create-lens-calibration-data-for-lensfun/
