### ISSUE TITLE
FUJIFILM GFX50S II

### ISSUE THREAD

**Issue by AndyMcGarty** [darktable-org/darktable#10608]
I've uploaded four files titled GFX50SII uncompressed.

I've included two garden shots and a colour chart outdoors and under flash.

Thanks

**Comment by LebedevRI** [comment]
Does that camera not have 'compressed' mode?

**Comment by AndyMcGarty** [comment]
It does. Do you want some compressed too?

**Comment by LebedevRI** [comment]
It is stated on https://raw.pixls.us/ what samples are wanted.
The camera can produce 3 types: uncompressed, compressed, compressed lossless.
We want one of each, ideally each one should have the same contents.
(Color target shots aren't really useful)

**Comment by AndyMcGarty** [comment]
Will get this shot tonight and uploaded.

If I load the uncompressed raw into darktable its cropping the right hand side of the image off once I go into darkroom.  Crops to 7534x6210.  Its showing these values as the export width/height?

**Comment by LebedevRI** [comment]
Thanks!

**Comment by LebedevRI** [comment]
Thank you.
FWIW, i would **very** much prefer the *NOT* color chart shots as those are useless.

**Comment by AndyMcGarty** [comment]
I can take more outside tomorrow if it helps.  Bit dark at the moment :)

**Comment by AndyMcGarty** [comment]
I've added six more files, 2 of each in uncompressed, lossless compressed and compressed.
These were taken outdoors.
Please shout if you need anything else or specific subjects taken.

**Comment by LebedevRI** [comment]
@kmilos can you please pr the cameras.xml stub from dngmeta.sh?

**Comment by kmilos** [comment]
@LebedevRI Done, but needs to be checked over for completeness.

**Comment by AndyMcGarty** [comment]
Thank you.  Really appreciate this.
