### ISSUE TITLE
Star filter hides images it should not hide (current master & existing as well as fresh config)

### ISSUE THREAD

**Issue by jonastr** [darktable-org/darktable#10602]
**Describe the bug/issue**

Certain filter settings hide images even though they match the filter criteria.

**To Reproduce**

1. Clear any filters from the "collections" tab
2. Rate images with 1 star and 3 stars
3. Select star filter to be "greater than 2 stars" 
4. `=>` Images rated 3 stars are visible
5. Select star filter to be "greater than 1 stars" 
6. `=>` Certain images with 3 star rating (as shown in step 3) disappear.
7. Select filter to show "all" images
8. `=>` Certain images shown in step 3 also do disappear

Interestingly enough, it works correctly when selecting one film roll in the collections tab As soon as I clear it again, the bug appears. Other images from the same film roll aren't affected by this and show up correctly according to their star rating.

For more details, see attached screenshots.

**Current behavior**

Images are hidden even though the match the filter criteria

**Expected behavior**

Any images rated more than 1 star or more should always be visible in the steps described above.

**Screenshots**

`>= 2 stars` - image present:
<img width="1152" alt="pic present" src="https://user-images.githubusercontent.com/1243894/145711807-ac835951-dae9-415d-a3ce-6f5fa4719696.png">

`>= 1 star` - image missing
<img width="1150" alt="pic missing" src="https://user-images.githubusercontent.com/1243894/145711819-c42bca7e-8c65-44f9-b22c-9b6327f6c94f.png">

`no filter` - image missing
<img width="1141" alt="pic missing2" src="https://user-images.githubusercontent.com/1243894/145711828-a11c503b-2148-4585-afe6-543a836782c8.png">

**Which commit introduced the error**
Didn't bisect, yet. If anyone else can reproduce the error, can still go down this route.

**Platform**

* darktable version : `3.7.0+1656~gb9fecd246`
* OS                : MacOS
* Memory            : 16 GB
* Graphics card     : M1 integrated
* Graphics driver   : MacOS integrated
* OpenCL installed  : n/a
* OpenCL activated  : n/a
* gcc               : 
```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
* cflags            : n/a
* CMAKE_BUILD_TYPE  : Release

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version `3.7.0+1546~g9295771f4`**
 - Can you reproduce with a RAW or Jpeg or both? **I use DT only for RAWs**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

 - Do you use lua scripts? **no**

**Comment by AlicVB** [comment]
I can't reproduce...

Just to be absolutely sure, if I read the image names correctly and you images names names are in the order of the capture time, then the missing image (MB280027.DNG) will not be placed at you red mark but later, on another line. Can you confirm it's not the case ? Thanks !

**Comment by jonastr** [comment]
@AlicVB oh holy ... yeah, you are right. I absolutely got myself confused and it's way down the list. Apologies for the confusion and thanks for checking. Will close the ticket.
