### ISSUE TITLE
Segfault when refining mask on gaussian blur retouch

### ISSUE THREAD

**Issue by LinuxMercedes** [darktable-org/darktable#10609]
**To Reproduce**
1. Open the Retouch module
2. Select "Gaussian Blur"
3. Pick a shape (verified with circle and ellipse)
3. Place the shape partially off the image
4. Click on the "Parametric mask" button
5. Drag the "details threshold" slider

At this point, darktable segfaults.

**Expected behavior**
Gaussian blur is applied only to parts of the image as constrained by the detail threshold

**Platform**

* darktable version : 3.6.1-1
* OS                : Linux, kernel 5.15.0-2-amd64 
* Linux - Distro    : Debian testing
* Memory            : 16 GB 
* Graphics card     : Intel Corporation UHD Graphics 620 (rev 07)
* Graphics driver   : i915
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              : 1:7.7+23
* Desktop           : xmonad
* GTK+              : 4.4.1+ds1-3
* gcc               : 11.2.0-12

compile options:
```
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **darktable doesn't show the 'detail threshold' slider on jpegs**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **no**
 - Do you use lua scripts? **no**

Backtrace:
[darktable_bt_SSWIE1.txt](https://github.com/darktable-org/darktable/files/7699958/darktable_bt_SSWIE1.txt)

darktablerc: (personal info redacted with `XXX`)
[darktablerc.txt](https://github.com/darktable-org/darktable/files/7699988/darktablerc.txt)

**Comment by jenshannoschwalm** [comment]
Haven't seen this but I almost never use this module.

Will check and fix if reproduced.

**Comment by jenshannoschwalm** [comment]
Tested and confirmed on linux current master both CL activated or not.

Although, i can only trigger if resizing the displayed part in darkroom mode. Looking into retouch code (first time ever), there seems to be some tricky ROI changing, that might not be correctly handled when calculating the details mask in rawprepare.

Will take care asap

**Comment by MStraeten** [comment]
i can reproduce this scenario on win10 just in combination with new crop module cropping through the shape
seems similar to https://github.com/darktable-org/darktable/issues/10422

**Comment by jenshannoschwalm** [comment]
Mmh. Only evident if used with details mask and threshold set to != 0 ?

**Comment by MStraeten** [comment]
reproducible just when using details mask != 0.
in combination with new crop module cropping through teh shape it's also reproducible with healing and circle.

#10422 - that scenario is independent from using detail masks - but not reproducible in any case (seems to be very dependent on the shape and mask settings) but reproducible in any case with detail mask !=0

**Comment by jenshannoschwalm** [comment]
Martin, if i understand all your comments here and the other issue correctly
1. You can sometimes trigger a crash while using retouch module with any shape depending on the position.
2. when using details mask with a threshold of != 0 this happens always.
3. the order of *crop* and *retouch* modules in the pipe is important.

So there seems to be a problem in mask distortion.

**Comment by MStraeten** [comment]
tried this scenario on osx with lldb:

retouch: healing circle + detail maks
crop: frame cuts circle (default pixelpipe order)

crash:
```
* thread #84, stop reason = EXC_BAD_ACCESS (code=1, address=0x12d8fb000)
    frame #0: 0x00000001008a8b65 libdarktable.dylib`.omp_outlined..34 [inlined] .omp_outlined._debug__.33(.global_tid.=<unavailable>, .bound_tid.=<unavailable>, msize=275850, mask=<unavailable>, warp_mask=<unavailable>) at blend.c:788:29 [opt]
   785 	 #endif
   786 	  for(int idx = 0; idx < msize; idx++)
   787 	  {
-> 788 	    mask[idx] = mask[idx] * warp_mask[idx];
   789 	  }
   790 	  dt_free_align(warp_mask);
   791 	  return;
Target 0: (darktable) stopped.
```

**Comment by MStraeten** [comment]
did a test on all combinations:
heal fails for all shapes even the source is not affected by crop:
```
VM Region Info: 0x7f928ae8e000 is not in any region.  Bytes after previous region: 1  Bytes before following region: 528384
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_LARGE             7f928a139000-7f928ae8e000 [ 13.3M] rw-/rwx SM=PRV  
--->  GAP OF 0x81000 BYTES
      MALLOC_LARGE             7f928af0f000-7f928bce9000 [ 13.9M] rw-/rwx SM=PRV  
```
copy mode fails for all shapes if the source is also affected from crop
fill mode is fine for all shapes
blur mode fails for circle, ova and path but not for stroke

**Comment by jenshannoschwalm** [comment]
Martin, i can confirm the crash is indeed happening in the blending loop. Somehow the dimensions don't match - (still working to find out why this happens.)

@TurboGit i concider this to be a bug that must be fixed for 3.8, please assign me, i will take care (hopefully this week)

**Comment by TurboGit** [comment]
@jenshannoschwalm : The full freeze is tomorrow night Paris's time (to let some days for the packagers). Do you think you'll have time before this deadline?

**Comment by jenshannoschwalm** [comment]
I'll do my best

**Comment by jenshannoschwalm** [comment]
@LinuxMercedes could you also test please?

**Comment by LinuxMercedes** [comment]
Happy to do so! I'll take a look this evening once I'm off work.

**Comment by LinuxMercedes** [comment]
@jenshannoschwalm it works! thank you so much for the quick fix, and sorry for surprising you with it at the last minute!

**Comment by LinuxMercedes** [comment]
(as an aside, in addition to the build deps, i needed to install `python3-jsonschema`; not sure if that's a new dependency that `apt build-dep darktable` won't pull in yet or a bug in debian's packaging?)
