### ISSUE TITLE
Import filter for unknown/unsopported file formates

### ISSUE THREAD

**Issue by kamik2** [darktable-org/darktable#10601]
At the moment, when importing image files, all formats are included. 
In my case that includes (not yet) supported *.cr3 files.
As the import is "useless" I need to erase them from my film roles manually every time.

A check box next to "ignore JPEG files", called "ignore unknown/unsupported files" would solve this.

![Screenshot 2021-12-12 113416](https://user-images.githubusercontent.com/35273125/145709072-f71c72a2-2c40-467d-8dba-65452bb85913.png)

**Comment by elstoc** [comment]
cr3 will be supported in the next release

**Comment by kamik2** [comment]
that's great. but besides that, I think this would be a useful option anyway.

**Comment by ptilopteri** [comment]
or one could craft a lua script to ignore cr3 files, or alter the
lua script, import_filters or import_filter_manager, without adding
code directly to the darktable base.  the request is somewhat of a
"corner" case as presented.
