### ISSUE TITLE
Detecting RAW images in Lua script doesn't seem to work with Sony alpha 6000

### ISSUE THREAD

**Issue by codecrusher64** [darktable-org/darktable#10610]
I want to detect RAW images in my Lua script using `dt_lua_image_t.is_raw`, but this always returns `false` for all my images. I have a Sony ILCE-6000 (alpha 6000). RAW images are stored as *.ARW files.

Any ideas?
How does this function detect RAW images?
Are there known problems with some camera vendors maybe?

* darktable version : 3.6.0
* Linux - Distro : Ubuntu 21.10

**Comment by Mark-64** [comment]
If nothing has changed with recent versions, `dt_lua_image_t.is_raw` test image flags, therefore only works when image is opened in darkroom, not when imported.
See [here](dt_lua_image_t.is_raw)

**Comment by codecrusher64** [comment]
Sorry, the URL `https://github.com/darktable-org/darktable/issues/dt_lua_image_t.is_raw` doesn't seem to work

**Comment by Mark-64** [comment]
[here](https://github.com/darktable-org/darktable/issues/4086) is the correct link, sorry

**Comment by codecrusher64** [comment]
Ok, this explains the observed behavior. I read `dt_lua_image_t.is_raw` during image import.

From #4101 I can see, that a corresponding warning has been added to the Lua API documentation. But I can not see this warning in the online documentation referenced [here](https://www.darktable.org/resources/). The [HTML link](https://www.darktable.org/lua-api/) leads to a "404 Not Found" error page on my computer. And the [PDF documentation](https://github.com/darktable-org/darktable/releases/download/release-2.0.0/darktable-lua-api.pdf) is for API version 3.0.0, which is outdated.

Is the broken HTML link only an issue on my computer? And if not, is this problem already reported anywhere? I can't find any issue.
