### ISSUE TITLE
Can't import style settings (dtstyle)

### ISSUE THREAD

**Issue by leadenhead** [darktable-org/darktable#10624]
I have an old working style setting (.dtstyle) created on an old version of darktable (2.6.x) updated to 3.x on Windows OS. I copied the .dtstyle files to path ~/.config/darktable/styles/ on the Arch Linux. Darktable doesn't see them. At the same time, it creates new ones in the same directory. I compared the format of these files and found differences.

**Old style:**
<blendop_version> 8 </blendop_version>
**New style:**
Has a <iop_list> tag.
The <op_params> and <blendop_params> tags contain more characters.
<blendop_version> 11 </blendop_version>

**How do I import the style settings?**

**Comment by darkelectron** [comment]
> How do I import the style settings?

Importing styles can be done in the `styles` module in lighttable.

**Comment by leadenhead** [comment]
It works, thanks! Probably earlier I did something wrong.

**Comment by leadenhead** [comment]
It works, thanks! Probably earlier I did something wrong.

**Comment by ptilopteri** [comment]
if this is not an issue anymore, please consider closing it.
