### ISSUE TITLE
Histogram Background

### ISSUE THREAD

**Issue by dnlyko** [darktable-org/darktable#10627]
Not really a bug but the I would like to see the histogram (scopes) background black.  The light grey is a challenge on a 4K display.
Windows  Insider edition

**Comment by kmilos** [comment]
Perhaps try https://docs.darktable.org/usermanual/3.6/preferences-settings/general/#css-theme-modifications ?

**Comment by Nilvus** [comment]
Could you precise on which theme? Consider too that background is a choice to let infos visible as well as good contrasted and well balanced with other outside.
