### ISSUE TITLE
Center Area White

### ISSUE THREAD

**Issue by dnlyko** [darktable-org/darktable#10631]
I would like to see an option to turn the center area background white.
On a 40"+ 4K monitor there is ample real-estate and this would allow editing while there is always a white frame.
Here is how it looks in SilkyPix, NXstudio and DXO
![3SilkyPix](https://user-images.githubusercontent.com/38403574/146038451-4a7b16e5-ffb5-44b5-82c0-44e075e8f9d0.jpg)
![1NXstudio](https://user-images.githubusercontent.com/38403574/146038455-9045e509-00a7-4bd9-8a6d-119536fc4bf5.jpg)
![2DXO](https://user-images.githubusercontent.com/38403574/146038456-28c902f2-f568-4aaa-a7f9-e828f67af549.jpg)

**Comment by kmilos** [comment]
Perhaps try https://docs.darktable.org/usermanual/3.6/preferences-settings/general/#css-theme-modifications ?

**Comment by dnlyko** [comment]
Thanks,
I'm only up to 'dtdocs/en/darkroom/masking-and-blending/overview/' in the user manual.
Long way to go.

**Comment by johnny-bit** [comment]
What you actually need IMO is [color assesment mode](https://docs.darktable.org/usermanual/3.8/en/module-reference/utility-modules/darkroom/color-assessment/) which follows ISO 12646:2008 recommended viewing conditions.
