### ISSUE TITLE
Support Google Takeout JSON Location Data

### ISSUE THREAD

**Issue by rickprice** [darktable-org/darktable#10634]
**Is your feature request related to a problem? Please describe.**

Because I use a Canon T7i, my photographs don't have embedded location data from where they were taken. Currently I use Google Takeout to download my location data (I have Location History enabled), and then I use exiftool to add the location data to my RAW files using a shell script.

It seems though, that I can no longer get the KML data from my location history, but can get the JSON formatted data.

This means more work to get my photos GeoLocated, and its a pain already.

**Describe the solution you'd like**

What I would really like, is to have DarkTable natively understand the Google Location History JSON format, and be able to use that as well as the current GPX functionality if desired.

If changes are needed, it might be a good time to also add hooks to support other GPS formats at the same time.

**Alternatives**

Many people run a GPS logger on their phone to get GPX data, but I already have my Google location tracking turned on, I would rather not have to use another application to get my location data, and use up more battery life, when Google is already handling this for me. As well, ensuring that I run another logger before I take photographs is one more thing that can go wrong.

**Additional context**

I am more than happy to work on adding this functionality.

**Comment by johnny-bit** [comment]
GPX is a standard in GPS data. Google json format is not. Quick browsing around landed me things like https://github.com/iboates/android_location_converter and https://gist.github.com/juliushaertl/743704745b953fb54f9fca27ed124078 

A format of interest MIGHT be KML(and zipped KMZ)
