### ISSUE TITLE
documentation: website should mention information about the microsoft store version

### ISSUE THREAD

**Issue by nmat** [darktable-org/darktable#10655]
This request is more to make sure people understand what the microsoft store version of darktable is about.

Some might think that the version on the store is donating money to the project and so should be informed if it does not or what the deal is.

**Comment by elstoc** [comment]
I wouldn't specifically mention that version but say something more generic like "darktable is available free from ... Any paid versions listed on app stores are not endorsed by the darktable project and are downloaded at your own risk". I'm not sure whether this sort of thing is best on the github readme or darktable.org.

**Comment by kmilos** [comment]
> not endorsed

+ no support provided ;)

**Comment by MStraeten** [comment]
why mention something thats not supported? No need to make that stuff better ranked by googles algorithms by referencing that ;)

**Comment by nmat** [comment]
I would think that information on the download page on darktable.org should be enough.
