### ISSUE TITLE
Crash on copy and import

### ISSUE THREAD

**Issue by ChristianBirzer** [darktable-org/darktable#10654]
**Describe the bug/issue**
My darktable crashes when I use the copy&import function. I've built it from the current master on Windows but I could also reproduce the bug in a 3.7 bulid (b9fecd246)

**To Reproduce**
1. Click on "copy&import"
2. Add the DCIM folder of the SD card to places (not sure if this is needed to reproduce)
3. Select picture folder on SD card
4. Set import job name
3. select target base directory with file system dialog
4. klick copy&import

**Expected behavior**
The target folder is created and the images from the SD card are copied into that

**Actual behavior**
The folder was created but still empty.
The application crashed in import_session.c:351 on a g_free(new_path). Seems the new_path is somehow invalid.

**Screenshots**
Screenshot of the import dialog
![Screenshot 2021-12-19 172430](https://user-images.githubusercontent.com/96134139/146682556-526a00ae-36b2-4005-bc10-b982e3a5efa2.png)

Screenshot of the crash location
![Screenshot 2021-12-19 174033](https://user-images.githubusercontent.com/96134139/146683085-73603ffa-5653-4fe8-9f22-957a9a1a5d7d.png)

**Which commit introduced the error**
Not sure which commit it introduced. Currently I built c6e8ed5 on the master.

**Platform**

* darktable version : e.g. 3.9.0+6~gc6e8ed544
* OS                : Win10 Pro 21H1 19043.1415
* Memory            :  64GB
* Graphics card     : Nvidia GForce GTX 1660 Super
* Graphics driver   : unknown
* OpenCL installed  : unknown
* OpenCL activated  : unknown
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : debug

**Additional context**
I'm not sure how urgent this bug is or if it is reproducable on other systems at all. I won't have the time to debug further during the next few days. If the issue is still open in a week or so, I'll do some more investigations to track it down. In the meantime, maybe someone else can verify the problem.

**Comment by ChristianBirzer** [comment]
Ah, here's some more info and a clue:

In my case, the target folder is not writable (in fact, windows folder protection jumped in...) 
In that case, the _import_session_path() (in import_session.c:318) decides, that the self->current_path is not ok (currentok=0), but the check for "did the sessionpath change" in line 341 was true (means, it did not change). In that case, the new_path is freed but since currentok is 0, it is not returned but used to initialize a new filmroll which will free it a second time...

So its at least a border case where the target ist not writable. But with Windows folder protection this could happen to others too. Maybe a error message instead of a crash would be helpful here.

_As soon as I find out how to handle errors in a smart way, I could propose a patch 😉 But I'm a beginner in dt 🤣_

**Comment by ChristianBirzer** [comment]
I tried to reproduce this problem today but with no luck. Tried with windows folder protection, writing to a non-mounted device, writing to an invalid path, writing to a full usb stick. Everything works without a crash. Only thing I get is "0 images imported", which is ok (even if it could state a error cause...)
Therefore I'll close the issue until it happens again...

**Comment by ChristianBirzer** [comment]
Testing the brand new 3.8.0 release and got the crash again with my first import.
Did some more testing and realized, my assumption about the windows folder protection was wrong.
Reason for the crash is the Umlaut in the target directory (see my session name in the screenshot above). Using oe instead of ö works fine.
Looks like the _stati64 in dt_util_test_writable_dir returns nonzero in case the path contains an Umlaut which leads to the double free meantioned above. Both not fine. 
I don't see why the umlaut doesn't work. Maybe we also have to use the _wstati64 here. On the other hand, this case should be handled better than crash.
I'll take a look at this.

**Comment by johnny-bit** [comment]
Fixed by #10697
