### ISSUE TITLE
Mask Manager fold/unfold all groups when clicking the arrow on a processing module

### ISSUE THREAD

**Issue by blonchkman** [darktable-org/darktable#10656]
v.3.8 -- I have noticed a behavior that might contrast with the outstanding progress made in the mask management module.

**Description**
If several groups of drawn masks corresponding to as many processing modules are present in the mask management list, all the groups are unfolded/folded when clicking on the arrow of the drawn masks in one of the involved processing modules.

**Always reproducible**

**Expected behavior**
The user might expect the unfolding/folding of only the group affected by the click in the processing module. 

I can imagine that there might be arguments for the current behavior and my intent is not to point out "The Bug", but rather to ask if this is the expected behavior and if it should be mentioned in the doc.

Kindest regards.

**Comment by MStraeten** [comment]
not reproducible with my osx build 
scenario: one mask in 3 groups - expanding one group just expands this group

**Comment by blonchkman** [comment]
@MStraeten  expanding a group by clic on the arrow from inside the corresponding processing module unfold/fold all groups on debian/sid.. This has been confirmed to me 2 days ago. Can't recompile at yet, but i can live with it ;-)
