### ISSUE TITLE
Small UI request for bigger arrows.

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#10659]
The triangular arrow icons are of different size in the UI and one of the most used one is very tiny compared to the other ones in the surrounding UI. This makes it unnecessary hard for us with bad eyesight to use the interface.

I suggest to increase the size of the arrow indicated in the screenshot below or maybe make the arrow sizes be an option in the settings.

![arrows_small](https://user-images.githubusercontent.com/78697169/146940273-461669e6-3382-4c4d-ba25-7efe86ad1fe2.png)

**Comment by Nilvus** [comment]
Absolutely not to add another option for such minor thing in settings. darktable have a lot of options and we already talk multiples times here between us to not add to much. But I agree, those arrows could be bigger.

Unfortunately, at this time, it's not easily possible (not possible on CSS as far as I know ; and I have develop a lot of thing in CSS code and tested lot of things here to improve that). Those combobox (like sliders) are specific "custom-widgets" based on Gtk toolkit, developed some years ago in darktable. They are just a nightmare to customize. Some issues had been posted and work in progress had began, thanks to @dterrahe. But I can't say by now where this will go.

So, it's a small UI request indeed but an easy one (so not a small way to fix that).

See:

 #2077
#6255

And the work in progress by @dterrahe (on those combobox, so maybe this could be included in the WIP): #10527

**Comment by Nilvus** [comment]
This should be better, is it ok for you ?

![image](https://user-images.githubusercontent.com/45535283/151716380-bb9270ad-e75e-4810-aeb8-3797de412066.png)

**Comment by Nilvus** [comment]
Wrong one deleted, this is the good one. Is it ok for you with such arrow now?

![image](https://user-images.githubusercontent.com/45535283/151716465-8c1d4626-f635-4168-b981-f39f24bd72e7.png)

**Comment by bengtfalke** [comment]
Yes, It is a better alternative. But it could be even bigger.

**Comment by Nilvus** [comment]
Sorry, but no. I've tried and it become too big. This need to be balanced wiht elements around and bigger would be too big regarding other things around. This is well-balanced and better than it is by now in darktable. I so think it's the better compromise.

Anyway, thanks for your issue, this was needed to improve that!

**Comment by Nilvus** [comment]
Oh, and don't forget that this is just a screenshot (and small one). Size will be emphasize regarding screen size.

**Comment by bengtfalke** [comment]
I totally agree with you regarding tha balance of the graphical elements.

**Comment by Nilvus** [comment]
Good to read. It's sometimes hard to find the good compromise between readability, balance and eyes of some users ;-)!

Said that, it's all those combobox that need to be rewritten and it's a hard job for which I'm far to have skills for that. And seems to be a big work regarding on feedback I had for some developers that know better that part of code. As with slider, that are specific widgets written quite few years agos that we could bauhaus widgets. If you read links I posted about those on my first comment here, you will understand what I mean!
