### ISSUE TITLE
Mouse hover does not reset when leaving filemanager downwards

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#10663]
**Describe the bug/issue**
Mouse hover usually resets when leaving the filemanager table. But on master, if you move the mouse downwards and leave the filemanager into the time table, the mouse hover sticks to the last image Instead of disappearing. To reset it, hover it again and leave the table in some other direction (up, left,right).

Interesting note:
Zoomable filemanager behaves the same IF you used the static filemanager first. If you used culling last, it behaves fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/2805109/146969187-fe5d03d3-2817-4970-b613-5f668beab0e0.png)

**Comment by Nilvus** [comment]
As always, please precise darktable version on your issues, at least. Master could be any commit these last weeks (or months). Just click on darktable icon in top left of the UI to open the about dialog and copy/paste exact master you use. Thanks.

Tested on my side in 3.9.0+5~g026a23394. I don't find abnormal as it works this way only in images not completely visible at the bottom like in your screenshot.

I let @AlicVB see that as he works on that part.

**Comment by AlicVB** [comment]
I can reproduce, and yes, that's a bug. Note that this also happen for top thumbnails if they are not fully shown (use of the scrollbar or in zoomable mode) but interinstingly, this never happen on left/right side, even if the thumbnail is not fully shown (zoomable)

I'll have a look
