### ISSUE TITLE
Darktable support of Apples ProRaw

### ISSUE THREAD

**Issue by Szajda78** [darktable-org/darktable#10661]
I have notice that darktable 3.6.1 on my Manjaro 21.2 dose not support Apples ProRaw!! Because I can't even import them on my Manjaro 21.2
The folder is empty after import of apples ProRaw folder!

Byt the same software 3.6.1 on Windows 11 does support Apple ProRaw and i can import and read the ProRaw files and edit them!!

The question is why and does Darktable 3.6.1 support Apple ProRAW on linux!!

Any suggestions or answer would be very helpful 

Best regards 
Peter

**Comment by kmilos** [comment]
> Byt the same software 3.6.1 on Windows 11 does support Apple ProRaw and i can import and read the ProRaw files and edit them!!

This sounds a little strange, as it should not work (currently) on any OS... Can you confirm w/ [this sample please](https://raw.pixls.us/getfile.php/4264/nice/Apple%20-%20iPhone%2012%20Pro%20-%208bit%20(4:3).DNG)?
