### ISSUE TITLE
style definitions containing blanks and/or linefeed between <darktable_style version="1.0"> and <info> tags can't be imported

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#10664]
see https://discuss.pixls.us/t/dt-import-a-style-how-hard-can-it-be/28387/32

styles provided by https://github.com/jade-nl/dt.styles/releases/tag/v1.7 contains linefeeds and blanks between <darktable_style version="1.0">and <info> tag - so importing them results in
`22,676848 [styles] file /tmp/dt.styles-master/Fuji/XTrans III Velvia.dtstyle is malformed style file`
removing \n and following blanks results in an importable style file.

<darktable_style version="1.0"><info> must be written without linefeed or blank in between.
linfeeds or blanks later 

**To Reproduce**
1. Download a style from that source or save an own style and insert a blank or linefeed between <darktable_style version="1.0"> and <info> in the resulting file.
2. import style from lighttable style import dialog
3. See error - nothing happens

**Expected behavior**
linefeeds and blanks shouldn’t matter in xml files outside elements

**Platform**
* darktable version : darktable 3.9.0+44~gb2e504e76
* OS                :  OSx

**Comment by jade-nl** [comment]
Confirmed.

darktable: 3.9.0+6~gc6e8ed544
OS: Linux (Debian)
