### ISSUE TITLE
Can't uncheck Recursive mode until it finished recursing  - 3.6.1+6~g4bc866924 

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#10668]
**Describe the bug/issue**
Recursive import is pretty disabling when importing from the cloud. 

And is made worse, when you click `Import` and it's on a root folder in your cloud storage. 

You're stuck waiting for it to recurse through you're entire cloud, list those files, before you can do anything else with Darktable. 

E.g. 

* Enabling recursive import on a folder with 40k images
* takes several minutes to list, before you can begin importing 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open
2. Import 
3. Select recursive 

**Expected behavior**
Don't enumerate the list of files recursively (it's too slow)  

**Platform**

* darktable version : 3.6.1+6~g4bc866924
* OS                : OSx (installed via brew cask, https://github.com/TheShellLand/antsable/tree/master/playbooks/roles/darktable)
* Memory            :  16GB

**Comment by naisanzaa** [comment]
related. https://github.com/darktable-org/darktable/issues/10666

**Comment by phweyland** [comment]
> Don't enumerate the list of files recursively (it's too slow)

That's what is expected when `recursive` is set, anyway... even with the previous version.

**Comment by Nilvus** [comment]
No need to create 2 issues for same related thing. It's not helping here.

**Comment by naisanzaa** [comment]
> That's what is expected when `recursive` is set, anyway... even with the previous version.

Not in one of the previous versions. Before this new function was added. 

You could browse to the folder, and it would just list the folder like a normal file browser.

When you select `recursive`, it's just a toggle. 

With the new import browser, it wants to check if a picture has already been imported. Which I guess is nice. 

But if that's to improve the import process by reducing the number of files to import. All of that speed gained is neglected by the amount of time it's taking just to enumerate the files to import.

**Comment by phweyland** [comment]
I understand what you mean.
With the old version, you selected a folder, not seeing any images list. And yes you could freely toggle the recursive flag. But once you had clicked on import button there was no way to toggle back the flag. So globally the full import time is more or less the same.

With the new version, when you click on a folder, the used has to wait for the full of images.

Again, I agree that for a blind import, the previous version was better.
