### ISSUE TITLE
The Ru-Language is missing

### ISSUE THREAD

**Issue by EvgMakaev** [darktable-org/darktable#10676]
**Is your feature request related to a problem? Please describe.**

In darktable 3.6.1 there was a cool ru-transation, but there is not in 3.8.0. 

**Describe the solution you'd like**

Can be ru-language also supported in 3.8.0?

**Alternatives**

**Additional context**

**Comment by EvgMakaev** [comment]
I hope, that there was not a politic problem, but simple it was forgot.

**Comment by TurboGit** [comment]
There is no politician on dt :) the simple ranswer is that nobody stepped in to do the work to update the Russian translation for 3.8. it was then removed because too many strings were not translated. So simply a technical issue.

**Comment by EvgMakaev** [comment]
Thank You and Merry christmas. In 3.6.1 it was preatty ok. Was changed the format for translation files? Can I add it manually in a ex: *.cfg?

**Comment by johnny-bit** [comment]
You can help by translating darktable and maintaining translation. See https://github.com/darktable-org/darktable/wiki/Translations

**Comment by PeterWem** [comment]
It is easy to edit with Poedit. Download darktable master from Github, navigate to po folder and open ru.po in poedit. Start to translate. When you are finished for the day, save the file as darktable.mo and put it in C:\Program Files\darktable\share\locale\ru\LC_MESSAGES or /usr/share/locale/ru/LC_MESSAGES

**Comment by whiv77** [comment]
[ru.mo.zip](https://github.com/darktable-org/darktable/files/8002037/ru.mo.zip)
Перевел в быстром режиме, пользуйтесь кому надо. Если есть неточности исправляйте.

**Comment by TurboGit** [comment]
Sorry do not read Russian, but I do know that we need a `.po` file and not a `.mo`! TIA.

**Comment by whiv77** [comment]
[ru.zip](https://github.com/darktable-org/darktable/files/8002134/ru.zip)

**Comment by TurboGit** [comment]
Now integrated. Thanks. Please in the future do open new issues as adding stuff in a closed one may well get unnoticed. TIA.

**Comment by TurboGit** [comment]
For the record, this translation is missing 7 strings and is having more that 100 fuzzy translation so it won't be part of darktable 3.8.1. Hopefully you'll be able to update it for 4.0 due in June 2022.

**Comment by EvgMakaev** [comment]
Thanks. I try to find a translator. 
I have build with this change and my opinion is, that it is ok. 80/20 is reached.
![grafik](https://user-images.githubusercontent.com/58916275/152677958-0a784b1d-d06f-4efb-80a6-f225c9f86062.png)

**Comment by EvgMakaev** [comment]
But Thanks. The Darktable is a great project
