### ISSUE TITLE
sliders in darkroom

### ISSUE THREAD

**Issue by landsharks67** [darktable-org/darktable#10677]
---------------------------------------------------------------

**Did you buy darktable from an application store ?**  NO

_

**Describe the bug/issue**

The sliders in the darkroom module move automatically when the cursor is over them instead of having to grab the slider with the mouse and move it manually.  This just started happening today.  I was on 3.6.1 and just downloaded 3.8 to see if that improved things.  It did not.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open darktable.
2. Import or select an image from the lightroom mod.
3. click on the darkroom button.
4. select any of the editing modules with sliders.

**Expected behavior**

S;iders do not move unless I left click on them

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / YES.  This happened in 3.6.1 and 3.8
 - Can you reproduce with a RAW or Jpeg or both? I only use RAW files
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? Yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? No
   -

**Comment by paperdigits** [comment]
sliders will move when the cursor is hovered and the middle mouse wheel is moved. Could this be the case?

**Comment by MaxHofheinz** [comment]
How did to fix this issue which really makes darktable unusable?

**Comment by landsharks67** [comment]
Remove and reinstall worked for me.

⁣
Joel A. Lasky
***@***.***
480.270.4036

Get BlueMail for Android ​
