### ISSUE TITLE
Projects with low Build Activity - Survey

### ISSUE THREAD

**Issue by jadsonjs** [darktable-org/darktable#10675]
Dear Developers of project **darktable-org/darktable**,

We are conducting a study on CI metrics and we noticed that in your project, something peculiar happened.

During the period you are using Travis CI, the project passed by a long period of inactivity.
We noticed that the TravisCI configuration file (.travis.yml) was committed to your project on the date of **2013-09-18**.
But there is only a build history in TravisCI for a very short period, between **2020-10-16** and **2020-10-28**, in which were performed suddenly **165** builds.

Please, we would like you to answer this short survey with just 4 questions to help us identify the cause of this behavior.

https://forms.gle/UkkFrxpi7MNscYmV7

**Comment by elstoc** [comment]
We used to use TravisCI and now we don't - we have migrated our CI to gh-actions. I certainly won't be clicking a random link to answer questions but perhaps you could paste your questions into the issue instead?

**Comment by pubkey** [comment]
This guy is just spamming random projects with his "survey".
