### ISSUE TITLE
crash reading this nikon z7 nef image

### ISSUE THREAD

**Issue by armedad** [darktable-org/darktable#10670]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

got a crash reading a z7 image.  others work fine, but for some reason this one crashes.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to '...' light table, open the attached image
2. Click on '...'  open the image in dark table
3. See error
dump here: https://drive.google.com/file/d/1Y0xvzE2yaIIfM25rFWYQhOUc-13yKsap/view?usp=sharing
original .nef picture here: https://drive.google.com/file/d/1vyFHG5AtSTV94zHVTVXBRj0uQOQogKno/view?usp=sharing

**Expected behavior**

**Screenshots**

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.6.1
* OS                :  windows 10
* Memory            :  16g
* Graphics card     :  nvidia

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nilvus** [comment]
If it's just one image that cause a crash, that just mean that the image the issue, not darktable. So if other images are ok, that mean that your image is corrupted, at least partially. So we can't do anything.

And please, make an effort when completing the issue. Your issue is quite hard to read. A template issue doesn't mean to let all the template but is here to know which infos are useful to complete depending on issue. After completing and before that, it's good to clean and remove all unuseful infos. That help to read. Next time, the issue could be closed without warning if it's the same.

For those 2 reasons, I close this issue.
