### ISSUE TITLE
No GSettings schemas are installed on the system

### ISSUE THREAD

**Issue by LeoWelter** [darktable-org/darktable#10673]
**Introduction**
Installing and running github master branch on Macboot (M1) crashes when tyring to ad a non-defail place to to importer.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
no
**Describe the bug/issue**
Downloaded the latest master version as of 21 december 2020)
after installing a gazillion things with brew
darktable crashes on my M1 with the following error: No GSettings schemas are installed on the system

Any idea how to fix this? 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to import-->copy & import
2. Click on 'places +'
3. See error after crash
4. No GSettings schemas are installed on the system

**Expected behavior**
open finder

**Screencast**
_(if applicable)_

**Which commit introduced the error**
c6e8ed5

**Comment by parafin** [comment]
No idea how you install dependencies, build darktable or run it… But if you look at packaging/macosx/BUILD.txt you will find a way to start darktable avoiding the gsettings error, there’s an environment variable to be set.

**Comment by apfelkraut** [comment]
@LeoWelter, assuming your gazillions things you installed with homebrew includes also glib, you could try to set `GSETTINGS_SCHEMA_DIR=/usr/local/opt/glib/share/glib-2.0/schemas/ `, I guess this is the one that @parafin refers to.

Note that the path given within [packaging/macosx/BUILD.txt](https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt) is slightly different, as it is based on macports which is currently the only officially supported way to build darktable on macOS.

**Comment by zzkt** [comment]
if glib is installed correctly you may also need to `export GSETTINGS_SCHEMA_DIR=/opt/homebrew/share/glib-2.0/schemas/`

**Comment by acmpo6ou** [comment]
Thank you! This helped me ❤️ I don't even know what this project is about, but this helped me fix _my_ project.
