### ISSUE TITLE
Deadlock when opening any file from command line

### ISSUE THREAD

**Issue by milasudril** [darktable-org/darktable#10672]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
```bash
rm -rf ~/.config/darktable
darktable foo.cr2
# Close darktable
darktable foo.cr2
```
Now darktable deadlocks with the following bt
```
#0  0x00007ffff7b083bf in __GI___clock_nanosleep
    (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffffff5970, rem=0x7fffffff5980)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
#1  0x00007ffff7b0e047 in __GI___nanosleep (requested_time=<optimized out>, remaining=<optimized out>)
    at nanosleep.c:27
#2  0x00007ffff77c8547 in g_usleep () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7cafcd8 in dt_cache_get_with_caller
    (cache=0x55555738db20, key=1, mode=mode@entry=114 'r', file=file@entry=0x7ffff7f2fcd8 "/build/darktable-TmduYN/darktable-3.0.1/src/common/image_cache.c", line=line@entry=190) at ./src/common/cache.c:176
#4  0x00007ffff7d0b351 in dt_image_cache_get (cache=<optimized out>, imgid=<optimized out>, mode=mode@entry=114 'r')
    at ./src/common/image_cache.c:190
#5  0x00007fffa005455b in _metadata_view_update_values (self=0x555557ed4430) at ./src/libs/metadata_view.c:247
#6  0x00007ffff6ab8802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff6acc814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff6ad6a57 in g_signal_emitv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7d7409e in _signal_raise (user_data=0x5555581ac960) at ./src/control/signal.c:179
#10 0x00007ffff779e315 in g_main_context_invoke_full () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7d7466a in dt_control_signal_raise
    (ctlsig=<optimized out>, signal=signal@entry=DT_SIGNAL_MOUSE_OVER_IMAGE_CHANGE) at ./src/control/signal.c:261
#12 0x00007ffff7d38bc5 in dt_metadata_set
    (imgid=<optimized out>, key=key@entry=0x7ffff7f00000 "Xmp.dc.creator", value=<optimized out>, undo_on=undo_on@entry=0, group_on=group_on@entry=0) at ./src/common/metadata.c:621
#13 0x00007ffff7cdcba1 in dt_exif_read_xmp_data(dt_image_t*, Exiv2::XmpData&, int, bool)
    (img=0x555558185c00, xmpData=..., version=<optimized out>, use_default_rating=<optimized out>)
    at ./src/common/exif.cc:439
#14 0x00007ffff7cdeb4f in dt_exif_xmp_read(dt_image_t*, char const*, int)
    (img=img@entry=0x555558185c00, filename=filename@entry=0x5555581a42f0 "/dev/shm/IMG_1594.CR2.xmp", history_only=history_only@entry=0) at ./src/common/exif.cc:2736
#15 0x00007ffff7d04c2b in dt_image_read_duplicates
    (id=1, filename=filename@entry=0x555557ecf000 "/dev/shm/IMG_1594.CR2") at ./src/common/image.c:1067
#16 0x00007ffff7d0a2b9 in dt_image_import_internal
    (film_id=film_id@entry=1, filename=filename@entry=0x5555581850f0 "/dev/shm/IMG_1594.CR2", override_ignore_jpegs=override_ignore_jpegs@entry=1, lua_locking=lua_locking@entry=1) at ./src/common/image.c:1133
#17 0x00007ffff7d0a8ce in dt_image_import
    (film_id=film_id@entry=1, filename=filename@entry=0x5555581850f0 "/dev/shm/IMG_1594.CR2", override_ignore_jpegs=override_ignore_jpegs@entry=1) at ./src/common/image.c:1353
#18 0x00007ffff7cc502f in dt_load_from_string
    (input=0x7fffffffe42a "/dev/shm/IMG_1594.CR2", open_image_in_dr=0, single_image=0x7fffffff9eb4)
    at ./src/common/darktable.c:257
#19 0x00007ffff7cc76e3 in dt_init (argc=<optimized out>, argv=<optimized out>, init_gui=1, load_data=1, L=0x0)
    at ./src/common/darktable.c:1059
#20 0x00005555555550bc in main (argc=<optimized out>, argv=<optimized out>) at ./src/main.c:92
```

**Expected behavior**
Darktable should start without deadlock.

**Which commit introduced the error**
Have not bisected, but error is present on 3.0.1. It could be similar to  #5840, but I have no reference to lua in may logs. Also, the suggestion to modify lua configurations does not help in my case.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 
this is darktable 3.0.1
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

* OS                : `Linux 5.4.0-91-lowlatency #102-Ubuntu SMP PREEMPT Fri Nov 5 18:18:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

* Linux - Distro    : e.g. Ubuntu Ubuntu 20.04.3 LTS
* Memory            : 32 GB
* Graphics card     :  NVIDIA GTX 1050 ti
* Graphics driver   :  470.63.01
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           :  XFCE
* GTK+              :  3.24
* gcc               :  gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **no**
 - Do you use lua scripts? Not what I know of
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by piratenpanda** [comment]
3.0.1 is quite old. Does it happen with 3.6.1 as well?

**Comment by milasudril** [comment]
The problem seems to disappear after installing Darktable 3.6.1 from repository linked from Darktable homepage.

**Comment by ptilopteri** [comment]
if it is no longer a problem, please consider closing this issue.  tks
