### ISSUE TITLE
3.8 install crash due to data.db

### ISSUE THREAD

**Issue by vector457** [darktable-org/darktable#10686]
Merry xmas and thanks for your support.
I installed 3.8 using OBS latest release (over a current 3.6.1) Ubuntu studio 20.04
it crashed after the performance yes no message.

I Removed ./config/darktable _emulating a clean install_
re ran and it launches ok.
After much messing around and moving backup files one by one. The problem is pointing towards the data.db file.
library.db seems ok and I can see my photos and collections etc. But with a new data.db I have lost a considerable tag hierarchy. ie no tags.

If I replace the new data.db with my old one. dt fails to launch.
I ran dt from the cli with it crashing and it produced this file(attached) in /tmp/
Not sure if that helps.

I have 3.6.1 on another machine so I moved the data.db file over to it and it launched fine, all tags are visible etc.
So it looks very much like an incompatibility for 3.8 to read the 3.6.1 data.db?

I have also uploaded the compressed data.db.

Note: Whilst I have been using dt for a number of years it was only a few months back I began sorting thru, streamlining and creating a proper tag hierarchy (it was a an add hoc mess) so it may indeed look messy and segmented (needs a defrag:). I do hope we can restore these tags back somehow.

[darktable_bt_IET5E1.txt](https://github.com/darktable-org/darktable/files/7775565/darktable_bt_IET5E1.txt)
[data.db.tar.gz](https://github.com/darktable-org/darktable/files/7775575/data.db.tar.gz)

**Comment by vector457** [comment]
Further info:
In an effort to rebuild the db from importing my images along with their (XMPs).
The only drawback so far is that synonyms don't come over. I'm going to have to add these manually?

**Comment by johnny-bit** [comment]
Hi!

I've managed to reproduce your problem and it comes from darktable accell path handing unfortunately.

Wile we could fix and/or prevent that, a quick workaround for you would be to simply rename style id `41` to something that doesn't have `/` in name :) here's your data.db altered to match that:

[data.zip](https://github.com/darktable-org/darktable/files/7790423/data.zip)

**Comment by vector457** [comment]
Many thanks for that. Its always the little things :)
I have in the meantime rebuilt/streamlined the tags and presets/Styles So hopefully the "deep clean" will be better all round.
