### ISSUE TITLE
Screenshots on the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [darktable-org/darktable#10684]
Would it be possible to add a few images to see how darktable looks like? Does not matter
in which context, just to get an early impression. I found it via reddit links where people
spoke about but right now I don't know what it is really.

**Comment by MStraeten** [comment]
Better have a look at: https://youtu.be/qvi_clcVkuk

**Comment by Nilvus** [comment]
Why not 2 or 3 screenshots in main README, but not more. That's could be a good overview indeed but not the purpose for more. For more, [user manual](https://github.com/darktable-org/dtdocs) is here for that or [website](https://github.com/darktable-org/dtorg). Will check if README could be improved but not now. Probably in january.

**Comment by Nilvus** [comment]
I add only one screenshot, same as on darktable.org website. More would overload Github page. More could be added in user manual and/or website. For that, see links I posted in my previous comment.
