### ISSUE TITLE
Crashing in Filmic RGB with RAW & JPEG Images

### ISSUE THREAD

**Issue by dnlyko** [darktable-org/darktable#10683]
1. DarkRoom/Active Modules/Filmic RGB/Scene/Look Only
2. Right click 'white relative exposure' and press a number key.   Select 0 on the num key pad and press enter:  CRASH
3. The first time it crashed was with the 3 num key but I tried it several times but won't crash with 3, just 0 now.
* darktable version : 3.8 release version
* OS                :  Win10
* Memory            : 32
* Graphics card     : GTX1060
* Graphics driver   : latest
* OpenCL installed  : yes
* OpenCL activated  : yes
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes
 - Do you use lua scripts? no

**Comment by ralfbrown** [comment]
Unable to reproduce in Linux with current master.  Entering "0" for white relative exposure sets it to 0.1 which yields a strange-looking curve and almost one-bit-per-pixel image, but no crash.
