### ISSUE TITLE
retouch: allow full image to be viewed with crop marks

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10689]
For an efficient workflow, I usually do not wish to retouch parts of the image outside of my cropped area and, for this reason, usually crop before retouching. However, I do sometimes want to take replacement source patches from outside of the cropped area and this can be a pain when I can't see those parts of the image. I could temporarily disable crop, but then I'm relying on remembering where the crop ends, and my visual memory sucks. 

It might be easier to achieve this sort of workflow if it were possible to view the full image while retouching, but with an overlay showing an outline of the cropped area. I can see that this might not always be desirable so it might be best if this option was behind a toggle button or preference.

**Comment by AlicVB** [comment]
Good idea !

Showing the full "uncropped" image is not hard. we already have that for some modules, r&p for example. It's just a flag to add to retouch module so crop module is ignored when the first as the focus. (not sure it's actually possible to do that on the fly)

What will be hard, though, is to show the overlay with the cropped area, as that would basically means some communication between the modules, which is quite difficult to implement... or we can go with another flag that would not disable crop module entirely but draw the crop area instead...

I add that to my todo !

**Comment by elstoc** [comment]
While retouch is active it will be the current gui module so you could probably have crop use that along with a flag in develop or a config parameter to have crop draw the overlay? We could maybe use a pipe flag, like FAST_PIPE?

**Comment by elstoc** [comment]
I'd still like this

**Comment by jenshannoschwalm** [comment]
Would like this too. We have to fix some blending code before getting into this.

I am not sure how/if we can visualize the crop here, would it be good to avoid the cropping at all if we have retouch module expanded?

**Comment by elstoc** [comment]
> would it be good to avoid the cropping at all if we have retouch module expanded?

Being able to view the crop within the retouch module would be the most useful to me but I understand it might be hard because the crop occurs later in the pipe. The idea behind leaving the crop marks would be to know which bits of the image need retouching so as not to have to keep moving back-and-forth to the crop module or accidentally retouching cropped portions of the image.

**Comment by jenshannoschwalm** [comment]
Chris, I have this running here and am thinking about the UI.

To avoid more preferences I would suggest to show full uncropped image either a) always if active and expanded or b) by adding a checkbox

What would be better in your opinion?

**Comment by elstoc** [comment]
Generally I think we use "active and focused" for this sort of thing and I would personally prefer that it always show the full uncropped image. Are you able to get the crop marks showing? If so I guess the "show guides" button should be used to toggle the crop marks and the guides should show within the crop box.

Yell if I've suggested something that's not possible...

**Comment by jenshannoschwalm** [comment]
That's a short demo of what i have here atm. Unfortunately the mouse is not visible - i was hovering over the crop borders to demonstrate the "grab-corners" are not visible and cant be grabbed
[Bildschirmaufzeichnung vom 2023-07-20, 19-54-35.webm](https://github.com/darktable-org/darktable/assets/50982232/98e96626-9ee1-4d60-b027-3e77e0ef5ff8)

Far "less hacky" than i thought :-)

**Comment by elstoc** [comment]
Looks good. One thing I would say is that we probably want to avoid the uncropped area being greyed out or at least grey it out less than in the crop UI, so it's easier to see if you want to take source areas from it.

**Comment by jenshannoschwalm** [comment]
Agreed, personally would like just the borders? But I'm not a gui guy so would take what you/others suggest.

**Comment by elstoc** [comment]
Agreed
