### ISSUE TITLE
Behavior of 'omit hierarchy' export option changed

### ISSUE THREAD

**Issue by guille2306** [darktable-org/darktable#10696]
**Describe the bug/issue**

Something changed in the way the '_omit hierarchy_' export option is applied on 3.8 vs 3.6.1:

- on 3.6.1, when _omit hierarchy_ was **not selected** in the export preferences, _category tags_ where not exported and normal tags were exported. **Selecting** the option exported only the tags at the tip of the hierarchy. This was consistent with the tooltip of the option, that says “_only the last part of the hierarchical tags is included. can be useful if categories are not used_”.

- on 3.8, when _omit hierarchy_ is **not selected** in the export preferences, _category tags_ in the hierarchy are exported along the normal tags, irrespective of their attachment status. **Selecting** the option exports only the _non-category tags_, mimicking the non-selected behavior of 3.6.1. Is not possible to recover the selected behavior of 3.6.1.

There are three problems with this:

- category tags in the hierarchy are exported even if not attached to the image when the option is not selected
- the change breaks the presets for the export module, as the option does now a different thing
- the logic of the option changed, but the name of the option and the tooltip didn't and are not consistent anymore

**To Reproduce**

1. generate a hierarchy of tags:
    _cat1_|_cat2_|**tag1**|**tag2**
2. attach **tag1** and **tag2** to an image

3. in the preferences for the export module verify that the _omit hierarchy_ option is **not selected**
4. export the image as jpg
5. the exported image has _cat1_, _cat2_, **tag1** and **tag2** included

3. in the preferences for the export module verify that the _omit hierarchy_ option is **selected**
4. export the image as jpg
5. the exported image has only **tag1** and **tag2** included

**Expected behavior**

To avoid breaking 3.6.1 and before presets, it should follow the 3.6.1 behavior:

- When _omit hierarchy_ is **not selected**, only **tag1** and **tag2** should be included in the jpg
- When _omit hierarchy_ is **selected**, only **tag2** should be included in the jpg

Although it may be interesting to have this 'buggy' behavior as an option (on 3.6.1 it was impossible to export category tags), it should use a new option and not take over the _omit hierarchy_ option (and of course only export attached tags)

**Which commit introduced the error**

I don't know, but maybe it has to do with the fix for [this issue](https://github.com/darktable-org/darktable/issues/9949)

**Platform**

* darktable version : 3.8.0 (from OBS)
* OS : Linux, kernel 5.13.0-22
* Linux - Distro : Kubuntu 21.10, with KDE backports repo
* Memory : 16GB
* Graphics card : NVidia 960M
* Graphics driver : NVidia 470.86
* OpenCL installed : Yes
* OpenCL activated : Yes

**Additional context**

 - Can you reproduce with another darktable version(s)? **Version 3.6.1 didn't have the bug**
 - Can you reproduce with a RAW or Jpeg or both? **Both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **Yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **Yes**
 - Do you use lua scripts? **No**

**Comment by phweyland** [comment]
Are cat1 and cat2 tags set as category, or just free nodes ?
In the second case, the described behavior is correct.

**Comment by guille2306** [comment]
> Are cat1 and cat2 tags set as category, or just free nodes ?

Sorry, I forgot to clarify: _cat1_ and _cat2_ are defined as category tags, **tag1** and **tag2** are just tags without any special property

> In the second case, the described behavior is correct. EDIT Omit hierarchy is an old setting, ... when category wasn't existing yet.

It may be one posible desired behavior (as I said above), but it's not consistent with 3.6.1 and before. This change breaks old presets. It may be better to leave the logic of the option as before and add a new option related to category tags. If the option is old and not needed anymore, it would be better to just hide it from the GUI (_deprecated_).

Even then, non-attached category options should never be exported as single tags.

**Comment by phweyland** [comment]
> I forgot to clarify: cat1 and cat2 are defined as category tags, tag1 and tag2 are just tags without any special property

So this is a bug. I'll look at it.
