### ISSUE TITLE
version is not updated to 3.8

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10692]
I compiled darktable from master, in the top left corner and in the about dialog it still says 3.7.0+1708~ge5186e003

**Comment by MStraeten** [comment]
try `git fetch --tags`

**Comment by TurboGit** [comment]
Or better, use the darkatble provided with the release.

https://github.com/darktable-org/darktable/releases/tag/release-3.8.0

**Comment by paolobenve** [comment]
I cannot see any release-3.8.0 tag
