### ISSUE TITLE
Canon 90D noise profile

### ISSUE THREAD

**Issue by electroCutie** [darktable-org/darktable#10691]
Here is the noise profile for a Canon 90D
This is my first one and I'm not entirely sure how to interpret the results, so let me know if there is anything wrong with this and what to look out for.
That being said Looks good to me and I did some testing with the results.

[darktable-noiseprofile-20211225.tar.gz](https://github.com/darktable-org/darktable/files/7776379/darktable-noiseprofile-20211225.tar.gz)

**Comment by TurboGit** [comment]
@rawfiner : Just a ping to be sure you didn't missed this one. Let me know if you don't have time to handle this. TIA.
