### ISSUE TITLE
0 values for $(MAX_WIDTH)  $(MAX_HEIGHT)

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10695]
3.8.x

I inserted $(MAX_WIDTH) and $(MAX_HEIGHT) in a preference, and they give 0, as in this screenshot:
![maxwidth](https://user-images.githubusercontent.com/1417508/147416576-7686cf5c-254a-4649-b9d6-ddbdfc6556dc.png)

**Comment by ralfbrown** [comment]
Not all variables have valid values in all contexts.  IIRC, MAX_WIDTH/MAX_HEIGHT are only valid when exporting, since they read the max-size fields from the export module.

**Comment by elstoc** [comment]
I think that is correct, and this is therefore not a bug.

**Comment by paolobenve** [comment]
Ok, then the explication in https://www.darktable.org/2021/12/darktable-3.8.0-released/ isn't perfect:

> Substitution variables have been added for image dimensions as follows: $(SENSOR_HEIGHT) and $(SENSOR_WIDTH) for the absolute pixel dimensions of the sensor; **$(MAX_HEIGHT) and $(MAX_WIDTH) for the raw image size;** and $(EXPORT_HEIGHT) and $(EXPORT_WIDTH) for the post-cropping final image size.

instead of "_for the raw image size_" it should say: "for the maximum output width/height limit, as set in the export module".

**Comment by elstoc** [comment]
Original PR is #9877. I can change the darktable news post if needed. @Mark-64 this is your change and I haven't examined the code in any detail. Are you ok with changing this as per the above suggestion?

**Comment by paolobenve** [comment]
similarly, I got 0 values for CROP_WIDTH/HEIGHT with a dng image: 
![max](https://user-images.githubusercontent.com/1417508/147420443-637e5925-e7d8-4573-8fce-18c7e1f9b2b5.png)

Weirdly, it doesn't happen with cr3 images

**Comment by paolobenve** [comment]
It seems that the CROP_HEIGHT/WIDTH value in the bottom is not updated when the crop module values are changed. Instead, it's updated if I move to the next image and go back to the previous

**Comment by paolobenve** [comment]
I'm going to open a new issue for the crop

**Comment by paolobenve** [comment]
reopening: https://www.darktable.org/2021/12/darktable-3.8.0-released/ needs to be fixed

**Comment by Mark-64** [comment]
I will have a look in the coming days
