### ISSUE TITLE
print view: units muddled for inches

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#10708]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
When print settings units are set to inches, the numerical overlay on the center view is inaccurate.

**To Reproduce**
1. Select image in lighttable
2. Go to print view
3. Expand "print settings" module in right panel
3. Mouse over center view
4. Note that overlay should be accurate with the default "mm" units: `(17.00 17.00) -> (577.08 403.16) | (560.08 x 386.16)` (these and subsequent values are from a clean install, A2 paper size, 4:3 aspect ratio landscape image)
5. Change units to "cm" and mouse over center view
6. Note that overlay is accurate: `(0.17 0.17) -> (5.77 4.03) | (5.60 x 3.86)`
7. Change units to "in" and mouse over center view
8. Note that the overlay is inaccurate: `(0.03 0.03) -> (0.89 0.62) | (0.87 x 0.60)`
9. Click on a drag handle at the corner of the image area
10. Note that the overlay updates to accurate values: `(0.67 0.67) -> (22.72 15.87) | (22.05 x 15.20)`

**Expected behavior**
Overlay when units are inches should always be accurate.

**Which commit introduced the error**
This came about with the new "image layout" feature to printing.

**Platform**

* darktable version : 3.9.0+9~gba922e8ed4
* OS                : Linux - kernel 5.15.0
* Linux - Distro    : Debian testing
* Memory            : 32GB
* Graphics card     : Nvidia GP104GLM [Quadro P4000 Mobile]
* Graphics driver   : Nvidia 470.86
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 7.7
* Desktop           : Gnome
* GTK+              : 3.24.30
* gcc               : gcc 11.2.0
* cflags            : default
* CMAKE_BUILD_TYPE  : Release

**Additional context**
- Can reproduce with clean install
- Do use lua scripts, none are active

I started taking a look at the units problem, and am happy to work on this, though I also know that @TurboGit has been keeping the print view running, and knows the code best.

If I were to look at it, I'd also like to run down some other oddities. For example:
- the numerical overlay in the center view is useful, but could be nicer if it showed units or otherwise gave a clearer sense of what the numbers meant
- the image width/height in "image layout" doesn't always update, and indeed initially display as "width x height" without values
- the drawing of image and paper size in the center view is not always accurate, especially on fresh install
- sometimes the image layout ends up with values which make the image extend outside of the paper size
- the "units" setting in the "page" section of "print settings" doesn't have a label (it should be "units")
- the printer name setting in the "printer" section of the "print settings" also doesn't have a label (though this and no units label may be self-explanatory/intentional?)

Some other UI things (probably should be a separate feature request):
- The ellipses in the "profile" dropdown will cut off the right side of long profile names, which often is a key differentiator between profiles.
- The paper size dropdown in the "page" section can be very long and hard to navigate (at least for Epson printers). Search shortcuts help here, but it's not easy for new users.

I've also been wondering a few other broad picture things (almost certainly should be in a separate feature request):
- Has the "print settings" module gotten too full (and libs/print_settings.c too complicated), now that there is a layout section? Should there be a separate expandable "layout" module on the right panel (with its own libs/print_layout.c code)?
- While we're at this, there could also be a "color" module to handle that aspect of the work. A question would be what parts of print settings do people set-and-forget, and what part do people adjust/verify before printing each image?
- The "print settings" section at the bottom of "print settings" is confusing, and I think not necessary now that much of the pixelpipe workflow is in RGB. Instead should it default to "work profile" such that the colorspace conversion from colorout is generally a NOP? Then the profile conversion under the "printer" section at the module top would determine a single step color conversion to printer colorspace.

**Comment by TurboGit** [comment]
> 11\. Note that the overlay updates to accurate values: `(0.67 0.67) -> (22.72 15.87) | (22.05 x 15.20)`

Hum... The accurate values should be : `(0.06 0.06) -> (2.27 1.58) | (2.20 1.51)` So even this is not good.

**Comment by TurboGit** [comment]
> * the printer name setting in the "printer" section of the "print settings" also doesn't have a label (though this and no units label may be self-explanatory/intentional?)

Yes, that's the point. I didn't want to get the UI more clobbered for nothing.

**Comment by dtorop** [comment]
@TurboGit Thanks for comments!

> Hum... The accurate values should be : `(0.06 0.06) -> (2.27 1.58) | (2.20 1.51)` So even this is not good.

Oh no! I didn't even bother to check... I'll take a look at this and see what's going on.

> Yes, that's the point. I didn't want to get the UI more clobbered for nothing.

Makes sense. It's never something I wondered about until I started to look at this carefully today. Probably a sign of good design?

> Sure, but do not hesitate to propose PR for each individual issues.

Makes sense.

One other little thing I noticed when looking at the code is that the colorimetric intent for image export seems to revert to "perceptual" on dt restart. I think because it doesn't have an entry in darktableconfig.xml.in, and config now resets by default in that case. So there may be a lot of little things.

> I've been the only one to work on the print module up to now and this is not good for the long term maintenance of darktable anyway.

Indeed. Also seems to be good to have some geographic spread -- so that non-metric bugs show up!

I'm really appreciative of all your print module work. I know for many people these days that their images never leave the screen, but printing has been core to how I work with darktable.

**Comment by dtorop** [comment]
> > * the printer name setting in the "printer" section of the "print settings" also doesn't have a label (though this and no units label may be self-explanatory/intentional?)
> 
> Yes, that's the point. I didn't want to get the UI more clobbered for nothing.

One side effect of this -- it looks like any UI element without a label doesn't show up as a potential action/accelerator target. Though probably not the worst thing if there's no "units" or "printer" keyboard shortcut...

**Comment by TurboGit** [comment]
> One side effect of this -- it looks like any UI element without a label doesn't show up as a potential action/accelerator target. Though probably not the worst thing if there's no "units" or "printer" keyboard shortcut...

Right, not big deal I would say.
