### ISSUE TITLE
ACES

### ISSUE THREAD

**Issue by maximoremedios** [darktable-org/darktable#10709]
May I suggest an ACES color managed workflow? Camera's Input color space, input gamma to Intermediate/working color space ACES to output color space ? Also a color space transform tool to change color space and gamma would be great. Many thanks.

**Comment by MStraeten** [comment]
Whats the benefit over the current implementation?

**Comment by parafin** [comment]
I think you need to elaborate what exactly is missing. Just two sentences doesn't explain anything. dt is already scene-referred and there is a way to add another working color space without changing anything.

**Comment by maximoremedios** [comment]
Thanks for your replies. I work in the field of film post-production. ACES has become a standard, a common color space for 2D & 3D artists in post-production facilities. ACES is a requirement for Netflix deliverables. It's future proof, it's free and open source. There is a lot of development on ACES, Darktable would benefit from these developments, all it would take is to upgrade to the latest version of ACES. I'm in favor of ACES because I'm familiar with it but what you guys have developed is great as well and maybe ACES wouldn't bring anything? It's another option with an existing open source community. 
Check out ACES central: https://acescentral.com/ 
Or this guy who does free film print emulation for ACES:
https://github.com/baldavenger/DCTLs
Glad to hear, there is a way to add another working color space without changing anything, how do I do this? Sorry, I am new to DT.
As to the color space transform tool I mentioned, I'm talking about a tool that allows you to change color space and gamma and do some tone mapping and saturation mapping at the same time. It's commonly available in color grading softwares.  
Thanks

**Comment by Tylius** [comment]
Hi,
I also us DT in the VFX industry, The handeling of OCIO color config to work in the ACES ecosystem would be gorgeous.
My target is to do RAW to ACESgc for 3D department.
Thanks.

**Comment by UsernameDaniel** [comment]
Will have to request a +1 for that earlier comment. "Glad to hear, there is a way to add another working color space without changing anything, how do I do this? Sorry, I am new to DT."

Looking for guidence for adding a ACES colorspace to darktable. Currently have animation frames as .exrs in ACEScg colorspace. Can't open this colorspace in darktable at all, and really prefer the workflow of darktable over divinci resolve for simple overall color adjustments (my post workflow isn't that complicated). Also bare with me regarding color understanding, I have a working knowledge but not the whole gammut.

**Comment by crepererum** [comment]
A concrete place where ACES would be helpful is the 3D LUT module which currently only supports sRGB, Adobe RGB, gamma/linear REC709, and linear rec2020.

For reference: I've got a ACES LUT from [here](https://freelut.cullenkellycolor.com/). From reading the [Wikipedia article](https://en.wikipedia.org/wiki/Academy_Color_Encoding_System#ACES_Color_Spaces) and looking at the filename (`2383_ACEScct_to_ACEScct_v2.cube`), it seems that the LUT uses the ACEScct color space. However the wiki article mentions another color space (ACEScc) for that purpose, so I think at least these two should be added to claim "ACES support" for that particular module.

It's a bit of a pity that `.cube` files don't contain machine-readable metadata about the color space.

**Comment by UsernameDaniel** [comment]
> A concrete place where ACES would be helpful is the 3D LUT module which currently only supports sRGB, Adobe RGB, gamma/linear REC709, and linear rec2020.
> 
> For reference: I've got a ACES LUT from [here](https://freelut.cullenkellycolor.com/). From reading the [Wikipedia article](https://en.wikipedia.org/wiki/Academy_Color_Encoding_System#ACES_Color_Spaces) and looking at the filename (`2383_ACEScct_to_ACEScct_v2.cube`), it seems that the LUT uses the ACEScct color space. However the wiki article mentions another color space (ACEScc) for that purpose, so I think at least these two should be added to claim "ACES support" for that particular module.
> 
> It's a bit of a pity that `.cube` files don't contain machine-readable metadata about the color space.

Huge thanks Crepererum. Have been giving myself a headache trying to get consistant color grading. What you said sounds right about the ACEScc option. What I was able to glean from what I could find online is the workflow is outputting ACEScg, then when you bring it into comp you use the ACEScc.

Thanks for that, will give it a go!

**Comment by kmilos** [comment]
@parafin @MStraeten @johnny-bit  I guess this can now be reformulated as: support user-defined colorspaces in LUT3D module (e.g. the same way custom input/output/working are supported via external ICC profiles)?

**Comment by maximoremedios** [comment]
@kmilos Can I rather suggest formulating as such: addition of the ACES color managed workflow into DarkTable? Again, there is a lot of development on ACES, Darktable would benefit from these developments. ACES is a solid color management pipeline availaible in Resolve, Nuke, Fusion, Photoshop and many others.

**Comment by parafin** [comment]
This is still far from definition of the task. You basically ask for someone to do a research about how ACES fits into darktable pipeline. It doesn’t seem that any of developers are interested in this. So some other interested party has to do some preliminary work first - specifically explain what is needed exactly on the technical side (list of tasks, longer than one “implement ACES), and what benefits will that bring. Good start would be to write down the use-case you have in mind - which part of ACES exactly darktable will implement.

**Comment by kmilos** [comment]
Ok, I'm going to kick this off w/ some simple I/O support improvements as the basis to build on:

1. [Missing D60 to D65 chromatic adaptation when importing an ACES Image Container EXR](https://github.com/darktable-org/darktable/blob/a5fa576a7a3422d7771044f95e80431658473baa/src/common/imageio_exr.cc#L155-L182) (can be currently worked around by adding and manually selecting an ACES2065-1 ICC in profile, [like the one from Elle](https://github.com/ellelstone/elles_icc_profiles))

2. Enable exporting of ACES Image Container compliant EXRs: [currently the stored EXR primaries are D50 (ICC PCS) adapted](https://github.com/darktable-org/darktable/blob/a5fa576a7a3422d7771044f95e80431658473baa/src/imageio/format/exr.cc#L198-L206) when ACES2065-1 out profile is selected (w/ ICC PCS D50 white point also stored), which is not incorrect and should still be perfectly usable, just not "compliant" (D60 white point and unadapted primaries are expected)

Again, as there is a workaround, these are only nice-to-have in order to improve the import/export/interchange OOTB experience.

**Comment by crepererum** [comment]
So these are 3 concrete points now that can be worked on and fixed separately. I think we should close this issue here, file separate issues for the 3 points, and maybe add a label (e.g. "ACES") for easier tracking.

**Comment by UsernameDaniel** [comment]
Massive thanks for the followup guys.

Been playing around with color adjustment programs and in comparison Darktable is brilliant.

Hugely greatful!

**Comment by aurelienpierre** [comment]
ACES is designed by and for cinema, where different firms working with different software have to interconnect with each other and share color transforms in a portable way. This has nothing to do with darktable.

**Comment by eltitano** [comment]
@aurelienpierre Because Darktable should not be used in such an environment or why?

**Comment by vfxwiki** [comment]
@aurelienpierre ACES is designed by and for cinema. Cinema and VFX uses still images extensively.. Here is why i think ACES/OCIO is advantageous. Please decide if it is advantageous to this community.
* It's OpenSource and along with OCIO and openEXR represents high value projects from the tv/cinema industry that could be taken advantage of elsewhere.
* Along with OCIO it allows 'safe' color profile transforming of gamuts that are far wider than what is all-ready in darktable. 
* ACES (ap0) is future proofed as an archive specification that is now used extensively in preserving libraries of moving image academically & professionally. Darktable cannot read these correctly without ACES implementation.
* The use of extracting still-images from moving cameras is now common for still image-artists. ACES and OCIO would allow Darktable to correctly import images that were still encoded with that cameras log & gamut. As the majority of the moving-image cameras are defined in OCIO this brings value by opening many different camera frames colourspaces.
* Creating HDR images from raw images is required for every scene that has VFX. Being able to export to ACEScg (ap1) would be one less step, and simplify/minimize the risk of any gamut clamping.
* in the VFX industry the backgrounds (matte paintings) and textures (on all CG) are produced from static images. Photoshop is still cursed on the daily by DMP and texture artists for not being able to function i.e. in a wide gamut & linear, & while needing proof luts to get it to match everyone elses monitor.
At the bare minimum implementing ACES(ap0), ACEScg(ap1) and ACEScct (used by colorists) would allow Darktable to seamlessly integrate into an industry that is eager to adapt software into it's UNIX based pipelines.

**Comment by MStraeten** [comment]
necroposting doesn’t help. Also it doesn’t help to argue why something might be important because ist‘s not about something makes sense or not but to convince a developer, why he should focus on stuff that wasn’t relevant for him for several years.
So if it’s important for you, then step in, do the coding an file a pull request and maybe ask darktable developers for assistance …

**Comment by vfxwiki** [comment]
@MStraeten 
I downloaded Darktable this week, it's amazing, I will be communicating to my industry by writing an article about it, I wish I was more than a hack and I could contribute by coding, however, i can test/feedback and as a feature film supe I get a medium amount of reach to spread the word about this application. I wish i found this application earlier so I could of been part of this original discussion and provide information that i see as excluded in this conversation. And I did not want to start yet another post about this.. Not heard the term 'necropost' before. sounds nasty.
>Whats the benefit over the current implementation?
> btw have a look at the discussion in https://github.com/darktable-org/darktable/issues/8061
@kmilos
What has changed substantially now is ACES 1.3 . And how it now prevents gamut clipping of bight blues at 16bit, and it's updated RRTs. FYI: Those links are might be outdated luts with 1.3?! and to be sure that the icc profiles are compatible (and provide more choice) i would [generate them again with OCIO. ](https://opencolorio.readthedocs.io/en/latest/tutorials/baking_luts.html#icc-profiles-photoshop) - 

I am not requesting a response or debate here, especially if you see this convo as a waste of energy. 
Darktable is an exceptional application, and I am grateful for it.

**Comment by victoryforce** [comment]
@vfxwiki First of all, thank you for the kind words!

> Not heard the term 'necropost' before. sounds nasty.

https://en.wiktionary.org/wiki/necropost

Nothing offensive, just internet slang.

> I will be communicating to my industry by writing an article about it, I wish I was more than a hack and I could contribute by coding, however, i can test/feedback and as a feature film pro I get a medium amount of reach to spread the word about this application

It would be great if you could reach out to coders in your industry and encourage them to contribute to darktable.

> I am not requesting a response or debate here, especially if you see this convo as a waste of energy.

This is not a debate in any way. I also don't see much energy being wasted in politely responding to polite comments. I just want to emphasize that <ins>anyone can contribute</ins>. People who know your industry and understand what darktable improvements would be useful to them can contribute the code.

Well, you could try to convince current contributors to study your industry's needs and do it for you. But something tells me that this is unlikely to yield the results you want.

**Comment by eltitano** [comment]
> ACES is designed by and for cinema, where different firms working with different software have to interconnect with each other and share color transforms in a portable way. This has nothing to do with darktable.

just because I'm curious: Darktable has nothing to do with VFX workflows, wants nothing to do with it or should have nothing to do with it in the sense that it is not a common practice to export raw footage with basic grading to OpenEXR as a first step?
