### ISSUE TITLE
Hasselblad L2D-20c (Mavic 3 drone camera)

### ISSUE THREAD

**Issue by i-trusina** [darktable-org/darktable#10706]
Darktable fails to open Hasselblad L2D-20c DNG file in Darkroom. Lighttable is showing preview correctly.

**Comment by PeterWem** [comment]
Have you uploaded raw samples to raw.pixls.us?

**Comment by kmilos** [comment]
Please search before opening new issues, that s is duplicate of https://github.com/darktable-org/darktable/issues/10852
