### ISSUE TITLE
information line is not updated: it needs update when the crop size variables are used

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10705]
3.8.x

(from #10695)

I'm using CROP_HEIGHT and CROP_WIDTH in the "pattern for information line".

When a new image is loaded, 0 and 0 is shown.

Cropping or rotating doesn't update the values in the info line according to current values of those two variables.

The information line must be updated when loading the image the first time (0 and 0 are shown) and when some module changes the crop data:
- crop
- rotate and perspective
- lens correction
- ....
- maybe some deprecated module

**Comment by Mark-64** [comment]
I had a look into this.
As it has been said, not all variables work in all contexts, that's just the way it is now.
AFAIK there simply isn't a common infrastructure allowing access to all variables anywhere in the pipeline.
For example `$(CROP_HEIGHT)` and `$(CROP_WIDTH)` work in the watermark module, but not in the info line

![immagine](https://user-images.githubusercontent.com/43290988/147699783-5b69ec0a-cdc7-48fc-b1ce-6acf3d0470bb.png)

So to me this issue is a feature request, rather than a bug.

**Comment by paolobenve** [comment]
> $(CROP_HEIGHT) and $(CROP_WIDTH) work in the watermark module, but not in the info line

That's not true:
- open an image and crop it -> the info line remain unchanged
- close and reopen it -> the info line is now correct

I haven't checked the code, but I suppose that calling the function that updates the info line after a change to crop (and possibly others) module would be enough

**Comment by paolobenve** [comment]
calling again the _lib_imageinfo_update_message is enough?

**Comment by paolobenve** [comment]
trying to fix....

https://github.com/darktable-org/darktable/compare/master...paolobenve:update_info_line?expand=1 compiles but darktable doesn't run:

```
$ darktable-test
/opt/darktable-test/bin/darktable: symbol lookup error: /opt/darktable-test/lib/darktable/plugins/lighttable/libhistory.so: undefined symbol: _lib_imageinfo_update_message
```

I need help, could someone tell me what is wrong?

**Comment by johnny-bit** [comment]
`_lib_imageinfo_update_message` is internal function so it's not in `.h` file and as such isn't exported and can't be used...

Correct way would be imho for line to be updated via signal.

**Comment by paolobenve** [comment]
I compiled current master.

`$(CROP_WIDTH) x $(CROP_HEIGHT)` is `0 x 0` the first time a new image is shown in darkroom mode. Subsequently,  when I show that image in darkroom mode that value isn't any more `0 x 0`, but is the value of the uncropped image

cropping the image, that value doesn't change.

**Comment by dterrahe** [comment]
Apologies, I got confused between CROP_WIDTH and EXPORT_WIDTH. This is probably still valid although currently _export_ width in the _image information_ module gets updated every time (it seems that is _final_width_?) whereas maybe that should only happen after an actual export? But in the information line, both crop and export only get updated after image change?

I guess as @johnny-bit pointed out this probably needs a 
`  DT_DEBUG_CONTROL_SIGNAL_CONNECT(darktable.signals, DT_SIGNAL_METADATA_UPDATE,`
somewhere

**Comment by paolobenve** [comment]
#10979 seems to work now
