### ISSUE TITLE
RAWs from NIkon D3s cannot be opened.

### ISSUE THREAD

**Issue by tomascapek** [darktable-org/darktable#10717]
**Describe the bug/issue**
All RAWs from my Nikon D3s cannot be opened in Darkroom or exported. Previously, this worked for several years.

**To Reproduce**
1. Download RAW from my D3s camera here: https://drive.google.com/drive/folders/17P8c0UefoC2p3F1wXokcMkfAda8N72gQ?usp=sharing
2. Import it
3. Find it in Lightroom and switch to Darkroom.
4. See error.

Terminal log: 
```
[rawspeed] (DSC_2214.NEF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 177: Camera not supported (explicit). Sorry.
[temperature] failed to read camera white balance information from `DSC_2214.NEF'!
[temperature] `NIKON CORPORATION NIKON D3S' color matrix not found for image
[temperature] failed to read camera white balance information from `DSC_2214.NEF'!
[temperature] failed to read camera white balance information from `DSC_2214.NEF'!
[colorin] could not find requested profile `standard color matrix'!
```

**Screenshots**
[screen shot](https://imgur.com/yjGPqZc)

**Platform**

* darktable version : 3.8.0
* OS                :  Linux 5.15.11-arch2-1
* Linux - Distro    : Arch Linux
* Memory            : 16 GB
* Graphics card     : NVidia GeForce GTX 1070
* Graphics driver   : 495.46
* OpenCL installed  :  AFAIK not

**Additional context**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by MStraeten** [comment]
see release notes, section suspended support.

**Comment by kmilos** [comment]
Please contribute samples to raw.pixls.us if you would like to see support restored.

**Comment by tomascapek** [comment]
Thanks for a quick reply! I will try to contribute. But for now, I have downgraded to older version of Darktable.

**Comment by TurboGit** [comment]
> Thanks for a quick reply! I will try to contribute. But for now, I have downgraded to older version of Darktable.

I understand the immediate action to downgrade to continue using dt, but this means that you are still using poor and non validated data for the D3s. Be sure to contribute as soon as possible some sample if you want D3s to be supported in 3.8.1 which could come in a month or so (and yes we need quite some time before integration in rawspeed testing and having this landed in darktable).

**Comment by tomascapek** [comment]
Will do!
