### ISSUE TITLE
Leica M9

### ISSUE THREAD

**Issue by boojumsnark** [darktable-org/darktable#10710]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Added DNG uncompressed Leica M9 file for addition to Darktable database

**Comment by johnny-bit** [comment]
Please follow https://github.com/darktable-org/darktable/wiki/Camera-support#raw-format-support and open camera support request following template https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E

That way it's easier for us

**Comment by kmilos** [comment]
Support has been improved in the upcoming dt 4.2.1.

Please close @johnny-bit @Nilvus
