### ISSUE TITLE
Relative preset (at least for collect module)

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#10718]
Thinking about some arguments on #6675 and #10694. For both, but for stars filter as well, we want to filter quickly the "current" collection.
Saying that discards the collect module because of its complexity, including using its presets (as they may not include combinations of the current collection).
Here comes the idea of a relative preset, i.e. a preset which doesn't replace the current module settings, but which is added to the current setting.
This way, the user can define some stars and colors filters supporting his particular workflows and apply them quickly on top of the current collection. 
That would be applicable for the text filter as well. Then one has just to type in the searched string and that's done.

I don't know how easy that would be to implement such a relative preset ...

Thoughts ? Suggestions ?

**Comment by AlicVB** [comment]
I'm currently playing a little with the collect module, and I've encountered the exactly same need...
What I've in mind to "solve" that is to allow to : 
- save only parts of the preset (here only some rules)
- allow to append preset

That 2 points are specific to collect, thought, and can easily be handle directly in collect code, without too much global changes. So I'm not sure it's worth the pain to do something more global...
Do you have other modules in mind ?

(not sure if you have closed this on purpose...)

**Comment by phweyland** [comment]
> (not sure if you have closed this on purpose...)

sorry

**Comment by phweyland** [comment]
> Do you have other modules in mind ?

Not particularly today but I think that could be useful in some other circumstances, even in darkroom. For example for some complex module, you may want to preset only one or two parameters instead of all. 
Another common development usage of this is a relative correction of some parameters (+ or - 1EV for example).

If specific to the filter topic, why not having presets on quick filters ? May be far simpler to code.

**Comment by ralfbrown** [comment]
In the case of processing module presets, a straightforward way to allow a preset to affect only a subset of the module's parameters is to add a bitmask that specifies which fields in the blob should be copied to the module's parameters structure.  The trickiest part of such an approach would be the UI for selecting which subset of parameters to include.  Such a separation between values and whether or not to apply them would also allow the preset-editing dialog to give the option of toggling whether a particular value is included.

Having the ability for a preset to change only part of a processing module's state is something I'd definitely like to see, especially for the newer modules with a dozen or more settings.

**Comment by johnny-bit** [comment]
In addition to @ralfbrown's comment - processing modules would also benefit from presets threating separately masks and settings as requested in https://github.com/darktable-org/darktable/issues/7586 :)

**Comment by ralfbrown** [comment]
7586 can be handled with the same bitmask of to-be-applied parameters, which would even permit applying only some of the parametric settings (though the UI for that could be quite tricky...).

**Comment by dterrahe** [comment]
> a straightforward way to allow a preset to affect only a subset of the module's parameters is to add a bitmask that specifies which fields in the blob should be copied to the module's parameters structure.

From a developers perspective I go "hey! we could use introspection for that! great!" (although libs, currently, don't have introspection, only iops).

> The trickiest part of such an approach would be the UI

Exactly. If we present this in an inconsistent way (let's just bolt it on somewhere; it will gets fixed later) we add similar user acceptance (and developer disenchantment) problems that we've had quite a few of lately. Let's not just think "what could be built" but also "what should be built".

Also; consistency of parameters is currently enforced in the ui only. Just allowing any combination to be selected may lead to conflicts with the totally unrelated active settings that are only partly being overwritten. So some granularity restrictions or non-trivial logic needs to be developed and we don't want to do that on a module-by-module basis without having some structure to it.
