### ISSUE TITLE
Indicate presence or count of presets in hamburger menu

### ISSUE THREAD

**Issue by krid** [darktable-org/darktable#10713]
I was unaware that there were "factory" presets for some of the modules until I read about them in the manual and went looking.

It would improve discoverability if there was some indication that a given module has available presets.  As it stands you have to click on the hamburger to see the list of presets.

- Ideally I'd like to see a small number overlaid on the hamburger.  However, that might get messy if there are more than 9 presets.  I suppose you could display something like `9+` in that case?
- It might work to have a small dot indicating "presets available".
- You could switch from the hamburger to a different icon for which two phases/presentations would be more natural.

No matter what is done with the icon, the hover help should show the count of available presets.  It would be good to experiment with a single data point: `$N presets available`, versus two: `$F factory presets and $U user presets`.

**Comment by MStraeten** [comment]
??? darktable should change the gui just because some users are too lazy to even crossread the manual?
keep the ui simple...
Those using darktable actively will know where there're presets relevant for them ...

**Comment by krid** [comment]
> ??? darktable should change the gui just because some users are too lazy to even crossread the manual? keep the ui simple... Those using darktable actively will know where there're presets relevant for them ...

This is a disappointingly dismissive and hostile response to a well-meaning, polite, and clear feature request.  If this is how you treat people who are interested in your software it will be very difficult to expand the developer community.

Discoverability is an important UI concept.  Even if I had read enough to know that factory presets was a concept, it would still be valuable to have some indication that an unfamilar module had available presets.  Expecting every user to completely read and memorize the (very large and comprehensive) manual is unrealistic.

**Comment by TurboGit** [comment]
The tooltip proposal is ok. The others proposal are way too different to what is currently in darktable to me.

**Comment by johnny-bit** [comment]
Cons: 

> It would improve discoverability if there was some indication that a given module has available presets.

All processing modules can have presets. And user is expected to make own presets...

> Ideally I'd like to see a small number overlaid on the hamburger.

Oh no, please no! I see that as visual clutter.

> It might work to have a small dot indicating "presets available".

Same as above. I really hate when websites/apps do that. it's clutter.

> You could switch from the hamburger to a different icon

Well, that's the icon for "menu" and that's exactly what it does. If the module doesn't have presets it still has an option to create one.

>  Even if I had read enough to know that factory presets was a concept, it would still be valuable to have some indication that an unfamilar module had available presets.

Roughly half or 1/3rd of modules have "factory presets" afaik so... Even clicking around on fesh install one should be able to spot at least couple ;)

> Expecting every user to completely read and memorize the (very large and comprehensive) manual is unrealistic.

Nobody expects users to memorize the manual, but reading it is expected. It is comprehensive and gives answers to bunch of questions that one should know before starting to work on 1st image so it imo is not unrealistic.

Pros:

> the hover help should show the count of available presets

That's... not too bad actually. It could have also the selected preset :)

So yeah... tooltip idea is OK, others not so much.

**Comment by krid** [comment]
Thanks for considering my proposal.  Your `cons` are entirely reasonable, and I'd be happy to see the tooltip as a compromise.

**Comment by krid** [comment]
I looked through the code to see if I might be able to contribute a PR for this, but when I got to `_gui_presets_popup_menu_show_internal()` I realized it was going to require more knowledge of the Darktable guts than I'm willing to acquire right now.  "Count of presets" doesn't appear to be a simple property on `module`.

**Comment by Nilvus** [comment]
I'm ok too for a tooltip but no more. I totally agree with @johnny-bit. And @krid, I agree with @MStraeten, even if the way to answer was not the best, @johnny-bit explain it better: an hamburger icon is a classic one for a menu and in a software like darktable, presets are a basic. And even if I can understand that the manual is not entirely read, knowing basics of a software is... a basic to do! Like driving a car means knowing some basics about a car.
