### ISSUE TITLE
Crop tool not committing on double clock

### ISSUE THREAD

**Issue by MGA1970** [darktable-org/darktable#10721]
Windows 10, Darktable build 3.8 (as released).
Crop tool not committing to crop on double click, only when you leave the module.

**Comment by elstoc** [comment]
This was removed on purpose so is technically a "feature" and not a bug

**Comment by MGA1970** [comment]
> This was removed on purpose so is technically a "feature" and not a bug

But the on-screen directions/display state "double click to commit". That needs to be removed?

**Comment by elstoc** [comment]
Already done - see #10681

**Comment by MGA1970** [comment]
Excellent 👌

**Comment by elstoc** [comment]
So this can be closed?
