### ISSUE TITLE
Darktable doesn't create nor use $HOME/.config/darktable

### ISSUE THREAD

**Issue by tosho** [darktable-org/darktable#10725]
Darktable doesn't create nor use $HOME/.config/darktable when installed with Flatpak from the Ubuntu Software Center instead it is using  $HOME/.var/app/org.darktable.Darktable/config/darktable/ how I can replace it with $HOME/.config/darktable ?

**Platform**
* darktable version : 3.8.0 from Flatpak
* OS                :  Linux - kernel 5.11.0-43-generic
* Linux - Distro    : Ubuntu 20.04

**Comment by parafin** [comment]
We don’t maintain flatpak darktable package and don’t provide support for general flatpak questions. As far as I understand this is an intended “feature” of flatpak.
