### ISSUE TITLE
DT 3.8.0: Printing scaling is not correct when image export setting is set to "by scale (for file)"

### ISSUE THREAD

**Issue by nbnba** [darktable-org/darktable#10724]
**To Reproduce**

1. Go to ''lighttable->export" and under global settings "set size" to "by scale (for file)"
2. Go to "print" add images to the canvas
3. Click on ''print"
4. --> The output does not scale correctly on the print
![image](https://user-images.githubusercontent.com/21216185/147585188-4986fa4e-0bdc-49b3-8809-4ea09ec25eb2.png)

**Expected behavior**
1. Go to ''lighttable->export" and under global settings "set size" to e.g. "in pixels (for file)"
2. Go to "print" add images to the canvas
3. Click on ''print"
4. --> The output does scale correctly on the print
![image](https://user-images.githubusercontent.com/21216185/147585279-0f56dd5d-f4ed-4369-b561-61b9557c95a6.png)

**Platform**
* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : Linux 5.11.0-402110311031-generic x86_64
* Linux - Distro    : Ubuntu 20.04
* Memory            : 16GB
* Graphics card     : NVIDIA Geforce GTX 1050 mobile
* Graphics driver   :  nvidia-driver-460
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
 - Can you reproduce with another darktable version(s)? NA
 - Can you reproduce with a RAW or Jpeg or both? Both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

**Comment by TurboGit** [comment]
Confirmed! What an awful bug :( I'll fix that.
