### ISSUE TITLE
Unable to export edited images - darktable.exe caused an Access Violation in module libdarktable.dll

### ISSUE THREAD

**Issue by Lucki** [darktable-org/darktable#10736]
**Did you buy darktable from an application store ?**

No.

**Describe the bug/issue**
Updated to 3.8.0 and now it's no longer possible to export edited images.
There's slightly popping a toast message with something like: "demosaic" failed - Output may be faulty.
At the same time there are 4 little backtrace windows popping up and clicking OK on either of these closes darktable with all other windows.

It's possible to go back in the history stack to a point where the export doesn't crash darktable. But this isn't really helpful because it's either exporting correctly without the full history or when trying to recreate the history above the failing history stack entry it's failing again. I can't really pinpoint the specific history stack entry because it's shifting.

Darktable now also crashes on images that exported successfully in 3.6.1.

A search for the error shows up some opencl related issues but exporting still fails with disabled opencl.

~~~
darktable.exe caused an Access Violation at location 00007FFBD048FD58 in module libdarktable.dll Writing to location 000001CB8E10ABA0.
~~~

Example set 1:
[darktable_bt_49A7E1.txt](https://github.com/darktable-org/darktable/files/7789142/darktable_bt_49A7E1.txt)
[darktable_bt_59A7E1.txt](https://github.com/darktable-org/darktable/files/7789143/darktable_bt_59A7E1.txt)
[darktable_bt_69A7E1.txt](https://github.com/darktable-org/darktable/files/7789144/darktable_bt_69A7E1.txt)
[darktable_bt_79A7E1.txt](https://github.com/darktable-org/darktable/files/7789145/darktable_bt_79A7E1.txt)

Example set 2:
[darktable_bt_UPR7E1.txt](https://github.com/darktable-org/darktable/files/7789147/darktable_bt_UPR7E1.txt)
[darktable_bt_VPR7E1.txt](https://github.com/darktable-org/darktable/files/7789148/darktable_bt_VPR7E1.txt)
[darktable_bt_WPR7E1.txt](https://github.com/darktable-org/darktable/files/7789149/darktable_bt_WPR7E1.txt)
[darktable_bt_XPR7E1.txt](https://github.com/darktable-org/darktable/files/7789150/darktable_bt_XPR7E1.txt)

<details>
<summary>Example history stack</summary>

<img width="235" alt="Screenshot 2021-12-29 151534" src="https://user-images.githubusercontent.com/1408843/147671819-a85133fc-7a6e-47d5-9ce0-c46ac215ca63.png">
<img width="232" alt="Screenshot 2021-12-29 151602" src="https://user-images.githubusercontent.com/1408843/147671821-a3a66d62-6a8a-4b25-b751-32649823d1c4.png">

</details>

**To Reproduce**
1. Start darktable
2. Click on a heavily edited image
3. Click on export

**Expected behavior**
Edited images export correctly.

**Platform**
* darktable version : 3.8.0
* OS                : Win10 (unknown)
* Memory            : 32
* Graphics card     : Nvidia ~710 + AMD Vega 8
* Graphics driver   : unknown
* OpenCL installed  : yes
* OpenCL activated  : yes
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
 - Can you reproduce with another darktable version(s)? **Started occuring after updating to 3.8.0**
 - Can you reproduce with a RAW or Jpeg or both? **Input and output doesn't matter**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **no**

**Comment by wpferguson** [comment]
> There's slightly popping a toast message with something like: "demosaic" failed - Output may be faulty.
Which demosaic did you use?  

> Click on a heavily edited image
Please provide a copy (screenshot) of the history stack so that we can understand what a heavily edited image is.

**Comment by Lucki** [comment]
I was told a few minutes ago that the crash is now gone. Apparently there's a scale option in the export dialog which consists of _two_ entries in the last version but only _one_ in this version. After there putting in a new value it is now working.

Sadly I don't know by myself how the dialog was before or what values there were in that entry before or now. For me it looks like an unclean transition between these two scale input entry variants. I'll try to verify this in the upcoming days.

> Please provide a copy (screenshot) of the history stack so that we can understand what a heavily edited image is.

It's actually in my original post behind the spoiler.

> EDIT: I opened an image, edited and exported. I did get a warning message about a tiling problem with diffuse and sharpen, but the image exported successfully and appears correct.

Thanks for verifying. It seems the original issue is fixed now by resetting the value in the scale entry.

**Comment by Lucki** [comment]
The export "Size" field changed from "in Pixel" to "Scale", don't know why. It had the same value as before in the entry (1920 or similar) which caused the crash.

**Comment by johnny-bit** [comment]
Generally - the export field issue might be fixed by https://github.com/darktable-org/darktable/pull/10810 in 3.8.1
