### ISSUE TITLE
"Copy & Import" fails in Windows when Pictures Library is not in default location (C: drive).

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#10731]
**Introduction**
---------------------------------------------------------------
It is possible to set the location of the Libraries in Windows (such as 'Documents, 'Pictures', 'Music', 'Camera Roll' etc) to a drive other than the default - C:

**Describe the bug/issue**
When the Windows Pictures Library is located on another drive, for example D:, in version 3.6 of darktable the "Copy and Import" option for image import will place imported images in the expected location, even though the base directory naming pattern, in preferences, is set to "$(PICTURES_FOLDER)/user folder". 

In version 3.8 of darktable, with a modified Pictures Library location and with the above base directory naming pattern, this mode of import fails. An error message is briefly posted: "requested session path not available; device not mounted?", presumably because darktable is attempting to write to a non-existent folder on the C: drive. This is followed by the information message: "0 images imported".

In version 3.8 of darktable, with a modified Pictures Library location,  this mode of import works as expected only when the base directory naming pattern is set manually, by clicking on the icon to the right of that field (in the 'naming rules' section of the 'copy & import' panel) and then explicitly selecting the desired 'copy to' folder location.

**To Reproduce**
1. In Windows, modify the default Pictures Library location to a drive other than C:
2. Using the facility of 'places' and 'folders' in the 'copy & import' panel, browse to and select images to be imported
3. In darktable 3.8 set the base directory naming pattern to "$(PICTURES_FOLDER)/user folder" in either preferences or in the 'naming rules' section of the 'copy & import' panel.
4. Click on the 'copy & import' button at the foot of the panel.
5. Observe error message temporarily displayed along with information message. No image is imported
6. Repeat the 'browse to and select images to be imported' step
7. Click on the 'select directory' icon at the right-hand end of the 'base directory naming pattern' data entry field
8. Browse to and explicitly selected the desired 'import to' folder in the Pictures Library on the relevant drive.
9. Click on the 'copy & import' button at the foot of the panel.
10. Observe images are now correctly imported

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.8.0
* OS               Win10 Build 19043.1415
* Memory            :  32GB
* Graphics card     : nVidia GTX 1050 (2 GB)
* Graphics driver   : 472.12
* OpenCL installed  : 3.0.1.0 (OpenCL.dll)
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
1. Ensure the image(s) to be imported do not already exist in the desired 'import to' location.
2. The import option 'add to library' does not exhibit this problem, because the $(PICTURES_FOLDER) is not referenced and the image location exists (obviously).

**Comment by Mark-64** [comment]
Confirmed.
It is an unwanted side effect of #10246, I will try to fix it asap.

**Comment by Mark-64** [comment]
@LateJunction can you test the linked PR?

**Comment by LateJunction** [comment]
Sorry, I do not understand how I could test a 'PR' as I have no idea of
what this object is. I'm happy  to test a build of darktable for Windows
which contains a fix for the problem I experienced with import. I will need
a pointer to some advice/documentation on
1. How and where to get it.
2. How to install a second version of darktable on my 'experimental'
Windows desk top - so that I can continue using the 3.8.0 version. That
allows me to swap images and XMPs with my main Windows computer.

Regards
A.A.Hamilton
