### ISSUE TITLE
darktable 3.8.0 Newly defined shortcuts not retained between sessions

### ISSUE THREAD

**Issue by russ-arnold** [darktable-org/darktable#10743]
Linux Mint Uma 20.2 Newly defined simple shortcuts, eg. Alt-W, work fine in the session where they are defined but no longer exist on restarting darktable. Testing to date shows that $HOME/.config/darktable/shortcutsrc is being overwritten when starting dt. To determine this I exported session defined shortcuts to a file and noted the file size. While dt was closed copied the saved exported file over shortcutsrc in the config directory and restarted dt. The shortscutsrc file in config directory was reduced in file size after the restart and contained only defaults.

**Comment by dterrahe** [comment]
At each startup, shortcutsrc gets merged with (possibly new) default shortcuts and written back to disk, so that's normal and expected. The previous one gets stored to shortcutsrc.backup (but is overwritten at next startup). So the problem you are having is that shortcutsrc is not read correctly at all. Could you please provide your shortcutsrc (either the "default", or one that has extra shortcuts added)?

Would you also be able to provide the debug output after starting with `-d input`?
What (system) language settings do you use?

**Comment by russ-arnold** [comment]
Thanks for that info. Shortcuts and debug output are attached.
[shortcutsrc.tar.gz](https://github.com/darktable-org/darktable/files/7795256/shortcutsrc.tar.gz)
[dtdebug.txt.tar.gz](https://github.com/darktable-org/darktable/files/7795257/dtdebug.txt.tar.gz)
.

Language settings are:-
language, interface: English, Australia
Region: English, Australia
Time format: English, Australia.

Some additional information. If I import the additional shortcuts into dt, shutdown, and then launch dt from the command line I get the following error messages:

[dt_action_locate] action 'preset' doesn't exist
[dt_shortcuts_load] action path 'lib/collect/preset/Flickr all' not found
[dt_action_locate] action 'preset' doesn't exist
[dt_shortcuts_load] action path 'lib/collect/preset/Unprocessed' not found
[dt_action_locate] action 'preset' doesn't exist
[dt_shortcuts_load] action path 'lib/collect/preset/WIP' not found

**Comment by russ-arnold** [comment]
Some further info. It seems that the issue is limited to shortcuts that refer to a preset. If I define a new shortcut to a built in action (eg. Preferences) it is retained between program invocations.

**Comment by dterrahe** [comment]
Lib presets only get initialised _after_ shortcuts are loaded (when the lighttable view is opened). I'll have to look at reversing that order, but carefully because it could trip up other dependencies. Will try to fix before 3.8.1.

**Comment by russ-arnold** [comment]
Thanks guys.
