### ISSUE TITLE
Windows: weird workflow to change "camera time zone" 

### ISSUE THREAD

**Issue by pass712** [darktable-org/darktable#10747]
**Description:** 
Changing the value of "geotagging->camera time zone" only possible with workaround 

**To Reproduce:**
1. Go to lighttable, open dialog "geotagging"
2. camera time zone contains: **UTC**, no asterisk shown on the right

![scr1](https://user-images.githubusercontent.com/57034675/147775126-b1d6b153-c36c-464c-9b76-b6e9e4ce4906.png)

3. Click into "camera time zone"
4. Complete the string to e.g. **UTC+01:00**
5. Several strings are shown in a list, an asterisk is shown on the right. 
6. Select the string **(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien**

![scr2](https://user-images.githubusercontent.com/57034675/147775150-8bd12de8-e762-49a4-bd1d-f6f89c89198a.png)

7. Press **< Enter >** or **< TAB >**
8. camera time zone contains: **UTC** again, asterisk on the right is gone

![scr1](https://user-images.githubusercontent.com/57034675/147775185-1936f458-6f69-4664-9225-b0d7064016da.png)

To accept the value in "geotagging->camera time zone" one has to click somewhere else in the dialog box (see green ellipse) in step 7.

![scr3](https://user-images.githubusercontent.com/57034675/147775226-9978fc30-bd99-4073-b967-139d3c9a4c86.png)

**Expected behavior:**
The selected timezone should be accepted after typing **< Enter >** or  **< TAB >**

**Additional information**
* darktable version : 3.8.0
* OS                :  Win10.0.19044

**Comment by phweyland** [comment]
I cannot reproduce the case on Linux you describe.
First I cannot refine the time zone list by offsets relative to UTC, just cities.
Then I select an item in the list, it goes to the text entry, and Enter key accepts the item.

**Comment by pass712** [comment]
-> First I cannot refine the time zone list by offsets relative to UTC, just cities.
<- Makes no difference under Windows how you get the list. Entering Cities or completing the time-zone.

-> Then I select an item in the list, it goes to the text entry, and Enter key accepts the item.
<- This is different under Windows. Pressing Enter doesn't accept the entry in the text field. Looks as if you have to change the focus by clicking in specific regions outside the text field.
