### ISSUE TITLE
[darktble 3.9.0] detail treshold mask is not displayed correctly by smaller tumbnails in lighttable

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#10742]
**Describe the bug/issue**
I use here _diffuse or sharpen_ module to soften the texture of the photo (bloom):

![dt1](https://user-images.githubusercontent.com/38165484/147733735-c443a16d-4df9-4c32-8144-6068b49df83f.jpg)

Using _detail threshold_ mask, I want to limit this effect only to the detailed areas of the photo:

![dt2](https://user-images.githubusercontent.com/38165484/147733885-b28f227a-1f53-43ac-b535-f454bfd250ff.jpg)

In the small monitor on the right, the changes are displayed correctly:

![dt6](https://user-images.githubusercontent.com/38165484/147734057-0431bd59-2cf8-486d-b370-55a986f6e2db.jpg)

In lighttable, when using smaller thumbnails, these changes are not displayed correctly. They are "ignored":

![dt3](https://user-images.githubusercontent.com/38165484/147734264-6984f72f-1960-4aff-98e7-c502374e6eb2.jpg)

![dt4](https://user-images.githubusercontent.com/38165484/147734285-1f771267-3873-44f2-9e5f-27bc50ff7260.jpg)

If the thumbnails have a certain size, the use of the mask will be displayed correctly:

![dt5](https://user-images.githubusercontent.com/38165484/147734450-8401d5ff-850e-4735-b7ab-3487565d61f0.jpg)

This behavior could be reproduced also with other modules (e.g. with contrast equalizer)

**Expected behavior**

The effect of the mask should be displayed correctly in the thumbnails in lighttable regardless of the size of the thumbnails.

**Platform**

* darktable version : 3.9.0~git38.180852a072-1
* OS                : Linux
* Linux - Distro    : Kubuntu Linux 20.04
* Memory            : 31,3 GiB
* Graphics card     : GeForce GTX 1070
* Graphics driver   : Nvidia 460.91.03
* OpenCL installed  : yes
* OpenCL activated  : yes
* KDE-Plasma-Version: 5.18.5
* KDE-Frameworks-Version: 5.68.0
* Qt-Version: 5.12.8
* Kernel-Version: 5.4.0-91-lowlatency
* CPU: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz

**Comment by jenshannoschwalm** [comment]
Just from memory, isn't this due to fast path for small preview? If so, it should be this way.
