### ISSUE TITLE
White balance applied twice after update to 3.8

### ISSUE THREAD

**Issue by MiniMaxR** [darktable-org/darktable#10752]
After updating from Darktable 3.6 to 3.8 the white balance module is no longer loaded correctly. With 3.6 the module was always set to "camera reference" which worked perfectly with color calibration. With the update to version 3.8 no image can be loaded correctly. The white balance module is now set to "user modified" and the message "white balance applied twice" is displayed. But the image looks correct, see screenshot.
![Screenshot_20211231_094623](https://user-images.githubusercontent.com/96906840/147814235-9876879b-8799-4660-9215-9b6d1f96c885.png)

If you set the module back to "camera reference", the message is gone, but the white balance is not correct anymore. See screenshot:
![Screenshot_20211231_094725](https://user-images.githubusercontent.com/96906840/147814243-971f0138-941c-4c0c-b5f7-1b79ece37469.png)

Attached the corresponding XMP file.
[XT3S8613.RAF.xmp.gz](https://github.com/darktable-org/darktable/files/7795753/XT3S8613.RAF.xmp.gz)

Looks to me like a behavior change in the white balance module. Or is there something that needs to be adjusted after the update to 3.8? 

* darktable version : 3.8.0
* OS                : Linux 5.4.0-91 64bit
* Linux - Distro    : Ubuntu 18.04.6 
* Memory            : 32GB
* Graphics card     : Radeon RX 580
* compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by TurboGit** [comment]
> If you set the module back to "camera reference", the message is gone, but the white balance is not correct anymore.

You then need to do the WB in the "color calibration" module. This hasn't changed since 3.6 so I'm a bit confused about the report. I suppose you are in scene-referred mode?

**Comment by MiniMaxR** [comment]
Since version 3.6 I use the scene-referred mode with white balance in "camera reference" mode and the color calibration module. This works great and I am totally satisfied and enthusiastic about it. 
After updating to 3.8, the above messages appear for all developed images. If I change the white balance module manually back to "camera reference" (as I had set it before in 3.6), the white balance is no longer correct. I.e. all images have to be recalibrated in color calibration which I would like to avoid.

**Comment by TurboGit** [comment]
@MiniMaxR : I understand this I suppose, but I don't see what goes wrong in your side as I don't have this issue nor others that are using the scene-referred workflow. Can you describe a step-by-step procedure to trigger the issue?

**Comment by MiniMaxR** [comment]
> I understand this I suppose, but I don't see what goes wrong in your side as I don't have this issue nor others that are using the scene-referred workflow.

That's what I don't understand either. For me all images are really affected. I was hoping that it could be traced through the XMP file. Attached again two times the same image (different from above), once as it was developed in 3.6 and after I set the white balance module back to "camera reference" in 3.8. 
[XT3S8045.zip](https://github.com/darktable-org/darktable/files/7795857/XT3S8045.zip)
The image then had a red cast again. 

In version 3.6 (only roughly from memory):
- White Balance Module set to "camera reference
- White balance corrected in color calibration

In version 3.8:
- Images look ok in lighttable
- Change to darktable: 
  - Image still looks ok
  - "white balance applied twice" is displayed in color calibration and white balance module
  - white balance module is set to "user defined"
    - temperature: 6552K, tint: 1.094, red: 1.702, green: 1.000, blue: 1.343
  - set white balance module to "camera reference"
    - "white balance applied twice" messages disappear
    - Image has a red tint
    - temperature: 6502K, tint: 1.000, red: 2.076, green: 1.000, blue: 1.471
  - White balance module is set to "user defined"
    - temperature: 6552K, tint: 1.094, red: 1.702, green: 1.000, blue: 1.343
    - Image looks ok again
    - "white balance applied twice" messages are back again

Just as an idea: could it be that "camera reference" reads the values from the RAW file and if they differ from those in the XMP file, the module is automatically set to "user defined" with the old values? Then it could be that the RAW files in 3.6 provide different values and the problem comes from there.

**Comment by TurboGit** [comment]
> * "white balance applied twice" is displayed in color calibration and white balance module

That's not possible or the step-by-step is wrong. Is this image already edited? Or maybe you have an auto-applied WB module? 

Can you reproduce with newly imported images? If so, what editing steps are you doing,

**Comment by jenshannoschwalm** [comment]
Any style or special preset for a camera?

**Comment by MiniMaxR** [comment]
> Any style or special preset for a camera?

Yes, presets exist for lens, denoiseprofile, atrous, filmicrgb, colorbalancergb and flip. But not for the modules color calibration or white balance.

Checked this in the DB of 3.6 (thanks for the backup) and 3.8.


> > "white balance applied twice" is displayed in color calibration and white balance module

> That's not possible or the step-by-step is wrong. Is this image already edited? 

I have now tried a lot around. I have found out the following points:
- In Darktable 3.8 I do not get the problem reproduced when the images are re-imported.
- Only images imported and processed in 3.6 and earlier are affected.
- X-S10 images are not affected (at least I could not find any)
- Images of the X-T3 are partially affected:
  - for unprocessed images (only imported) the white balance module is set to camera reference 
  - for processed images the white balance module is set to user defined
- With the affected images I noticed:
  - If you switch in the history to before white balance, white balance is active and set to camera reference (see screenshots). ![Screenshot_20211231_124747](https://user-images.githubusercontent.com/96906840/147821974-4701df04-3219-4db6-aa90-8ab64158590d.png)

  - If you switch to white balance in the history, white balance is active and set to user defined (see screenshots).
![Screenshot_20211231_124806](https://user-images.githubusercontent.com/96906840/147821981-04009a36-cb7b-482e-9180-2c9af2e3c1a4.png)

> Or maybe you have an auto-applied WB module?

Not sure, but I don't know that I would have set anything in this regard. In any case, there is no preset. These should still be the default settings. 

> Can you reproduce with newly imported images? If so, what editing steps are you doing,

No, I don't get it reproduced when importing the images again in 3.8. I'm starting to fear that it's a bug in 3.6 that will only take effect in 3.8. :-(

**Comment by MStraeten** [comment]
maybe a result of https://github.com/darktable-org/darktable/commit/e0e857747c1833eee32af019d0a8f0f16d690e37#diff-619f0ccc873a89b01a0c3ab842860f6dc5cad878eb68a2a30751ca57442d071b

your combination of whitebalance and colorcalibration was right for the old camera reference, but since that was changed, no longer for the new. The old setting is kept as 'user modified'

**Comment by MiniMaxR** [comment]
Right, that should pretty much be the problem. If I see it correctly, then any changes to existing entries should always lead to this problem. The problem probably only exists since the white balance and color calibration modules check each other's settings. 

Maybe the entries should be versioned, so that the WB module continues to use the old entries for "old" configurations of "camera reference" and the new entries for new files. But then it is open what happens with the current version. In a patch 3.8.1 it would not be recognizable whether the configuration originates from a 3.8.0 or from a 3.6.x (or earlier). If the versioning is really an option, I would suggest that one always assumes a version before 3.8.0. That way there are certainly less files affected and therefore less effort for a manual correction.

But maybe there are better ideas.

**Comment by MStraeten** [comment]
I don't think, thats a problem since dt doesn’t mess up existing edits by handling them as user modified. In general, if something i changed in whitebalance module color calibration must be adapted too. So if you need to change something, then there’s no value in using historic values replaced because these were not correct ;)
You might deactivate the warning icon in preferences since that's an intended case.
