### ISSUE TITLE
[Feature Request] Easier font selection in the preferences panel

### ISSUE THREAD

**Issue by shinoryo1216** [darktable-org/darktable#10751]
Darktable is using OS system fonts or raster fonts for some non-western languages such as Japanese and Chinese with Linux. But they are not only ugly looking as some users say but also cause some practical problems on the interface.

A possible solution is a simpler font selection in the preferences panel like that of RawTherapee which is quite easier to use for general users.

See https://discuss.pixls.us/t/feature-request-for-changing-fonts/28549 for details, where the issue has been reported.

**Comment by johnny-bit** [comment]
I preffer the solution you proposed in #10758 - that seems better overall.
