### ISSUE TITLE
Alt+click on filmstrip

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#10759]
A simple Alt-click on filmstrip doesn't select the image in filmstrip (on map for example).
It must be confirmed either by Ctrl+click or by Shift+click to be effective.
This is not an issue when one wants to select several images, but it is weird to select a single image.
I think this has changed compared to the past. 

Do I miss something ?  Is that intentional ? Any work around ?

Debian SID
dt 3.9.0+47~g32c831351

**Comment by dterrahe** [comment]
I may be confused, but simply selecting an image should work with a single click, not Alt-click? It may have been that in the past the "alt" was ignored (and interpreted as an alt-less click) and over time that has been tightened up so it may well be that now the whole alt+click gets discarded. Is this still an issue for you?

**Comment by phweyland** [comment]
When some images are already selected, a simple click doesn't do anything.

**Comment by dterrahe** [comment]
In map view specifically, even when I have multiple images selected, if I click on a single image, it gets centered on the map. (also a huge number of OsmGpsMap warning and critical errors are generated, but that's a separate issue).

**Comment by phweyland** [comment]
The issue is about filmstrip, not the map itself.
