### ISSUE TITLE
Fujifilm X-T30 II

### ISSUE THREAD

**Issue by Schleichmichl** [darktable-org/darktable#10755]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

Please support the new X-T30 II.

**Comment by Schleichmichl** [comment]
All 3 possible RAF formats are uploaded to https://raw.pixls.us
compressed, lossless compressed & uncompressed

**Comment by kmilos** [comment]
I guess even with the two PRs merged, the lossless mode will still be missing, just like for the T4, E4, S10...

**Comment by d7rk** [comment]
Sorry,  but what do you mean?
Does you mean darktabke will never support the camera (or that nobody is currently working on it)? That it does not work now but that somebody is working on it (thank you!)?
That the lossy raw mode will never be supported but the rest will?
Thank you,

**Comment by vanitasvitae** [comment]
Any news on support for X-T30 II RAFs?

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/commit/839124827363b2a9233a7adfafd7a8908b469437

**Comment by vanitasvitae** [comment]
Awesome! Thank you so much!
