### ISSUE TITLE
Installing darktable in M1

### ISSUE THREAD

**Issue by LeoWelter** [darktable-org/darktable#10754]
I'm trying to compile darktable on an M1. Even though I installed gtk+3 using brew install gtk+3 I still get the message below:
Does anyone have an idea how to solve this?

```
--   No package 'gtk+-3.0' found
CMake Error at /opt/homebrew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GTK3 (missing: GTK3_INCLUDE_DIRS GTK3_LIBRARIES) (Required
  is at least version "3.22")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindGTK3.cmake:58 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:299 (find_package)
```

**Comment by MStraeten** [comment]
you might check https://github.com/darktable-org/darktable/issues/7564

**Comment by parafin** [comment]
Closing this as duplicate.

**Comment by Jiyone** [comment]
Hi!
I'm having the same issue since yesterday, But I'm not using a M1 mac but intel with MacOS 10.15.7 

Here is my console log https://pastebin.com/AqubwRRa .

I tried to reinstall libraries with macport following BUILD.txt but that have not corrected the issue.
