### ISSUE TITLE
3.8.0 Mask manager move up / down swapped

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#10766]
When you want to change the order of the masks in mask manager the moving action is working in reverse logic.

Select a grouped mask in mask manager and select the up entry from the right-click menu: the mask goes down. Select down and the mask goes up.

darktable version : 3.8.0
OS : Linux - 5.4.0-91-generic
Linux - Distro : Linux Mint 20.2 Cinnamon

**Comment by elstoc** [comment]
Confirmed on ArchLinux
