### ISSUE TITLE
Microsoft Arc Mouse scroll does not work for  controlling the mask size, hardness or opacity

### ISSUE THREAD

**Issue by alexander-stepanenko** [darktable-org/darktable#10761]
**To Reproduce**

1. Open an image in the Darkroom view
2. Open any module supporting masks, e.g. Retouch
3. Try use any tool to draw the mask (path or brush, whatever)
4. Try to use mouse scroll to change either tool size (scroll) or hardness (shift+scroll) or opacity(ctrl+scroll)
5. Tool size (or hardness or opacity) does not change

**Expected behavior**

Tool size (hardness, opacity) has to be changed with the mouse scroll

**Platform**

* darktable version : 3.8.0
* OS                :  Windows 11 Home 21H2 Build 22000.376 Windows Feature Experience Pack 1000.22000.376.0 
* Memory            :  16GB
* Graphics card     :  Built-in Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   2.00 GHz

**Additional context**

- It worked perfectly well with all previous version up to 3.6.1 inclusively, so I suppose it may relate to the brand new shortcur system
- Another thing - it works perfectly well in 3.8.0 if scroll using the touchpad (I use Dell XPS 13 9360)
- Mouse scroll is captured perfectly well in 3.8.0 to scroll on modules panel - it does not work for the mouse scroll to chaged the tool parameters only

**Comment by dterrahe** [comment]
Could you please confirm if this problem still exists in 4.0.1 and _only_ occurs with mask tools or with any scroll actions on the center screen (zooming, tone equalizer, graduated density)? The "new" shortcut system does nothing with mouse actions that are not combined with key presses, but there have been a lot of activities in the area of mouse support and mask shape manipulation as well over the last few and coming versions.
