### ISSUE TITLE
Darktable 3.8 does not install on my PC Windows 10

### ISSUE THREAD

**Issue by pdussarte** [darktable-org/darktable#10760]
Sir, 

If I try to install 3.8 on a PC running Windows 10, I get an error message  "A referral has been issue by the server"

Same message for a Darktable 3.8 install.exe downloaded from darktable.org or from Github.

Possibly a security issue, but how to fix it ?

Regards, Philippe Dussart

**Comment by ptilopteri** [comment]
google says:
  https://thegeekpage.com/a-referral-was-returned-from-the-server/
perhaps ???

**Comment by pdussarte** [comment]
Dear, 

 

I works with option 2.

 

Great stuff. 

 

Regards, Philippe

**Comment by ptilopteri** [comment]
the in the future, consider looking for the solution yourself.

also consider closing this issue as solved and not a problem 
attributed to darktable.

**Comment by pdussarte** [comment]
Dear, 

 

I am not technical and have tried to find a solution without success. 

 

Thanks. 

 

I will go on Gitub and close

 

Regrads

**Comment by johnny-bit** [comment]
Seeing this - looks like signing of install binaries would be beneficial here, but that has to be checked.
