### ISSUE TITLE
3.8 retouch before Rotate&Perspective

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#10764]
Hi all.
Not sure if this is bug, or just something that users need to be aware of....
I was revisiting an old image, and decided to do some retouch work very early in my workflow.
I then activate the new Rotate and Perspective module to straighten the horizon.
And doing THAT threw all of the retouch brush strokes out of alignment!
All the debris in the water (that I had cloned out using retouch) were now visible again.
My solution was simply to move Retouch to immediately prior to the R&P module.
The other solution is to do R&P before activating Retouch.

darktable version : 3.8.0+8~gfb39ffd86
OS                       : 5.4.0-91-generic
Distro                   : Linux mint 20, Cinnamon 4.6.7

**Comment by TurboGit** [comment]
That's a feature. That's also why the new crop module has been moved after retouch.

**Comment by parafin** [comment]
Wasn’t this supposed to be fixed by #8676? There was a long discussion about how all this is supposed to work and I don’t remember how exactly it ended… But definitely wouldn’t call this a feature… It’s either a bug or a shortcoming…

**Comment by parafin** [comment]
And it’s not exactly why it was moved, it’s about available pixels to clone from, not their position.

**Comment by TurboGit** [comment]
No, as you can see the #8676 was to properly distort the forms. The other recent fix was the new crop module moved after retouch. But the perspective correction is not immune to this and only a moderate issue as distortion is cropping only "small" part on the side of image not as bad as cropping.

Looking at the current IOP order we have:

- retouch
- liquify
- orientation
- rotation & perspective

I suppose we can move retouch & liquify below the two others. But that means that all masks from retouch & liquify need to be distorted to be applied on the right area. Not sure the modules are ready for that and even if ready won't this introduces some discrepancies?

**Comment by TurboGit** [comment]
Just tested moving the IOP and to my surprise all seems to work perfectly. So the only question to me is that a safe transformation in terms of quality? It's a balance between usability and quality I suppose.

**Comment by TurboGit** [comment]
See #10772

**Comment by AlicVB** [comment]
as said in @TurboGit PR, I fear that we'll have issues with textures and such, then. see this comment for example https://github.com/darktable-org/darktable/issues/8675#issuecomment-819807932 
for the issue #8676, indeed it was to fix another independent issue, found during the discussion mentioned above

**Comment by parafin** [comment]
OK, so retouch takes coordinates at its input and doesn’t translate them to RAW coordinate space, got it. I understand the compromise. Is this documented somewhere?

**Comment by TurboGit** [comment]
> OK, so retouch takes coordinates at its input and doesn’t translate them to RAW coordinate space, got it.

No, it does and all seems to work correctly to me. The source and target area are properly going through all the transform & backtransform routines.

**Comment by parafin** [comment]
If it’s raw coordinates, then this bug shouldn’t happen or am I missing smth? I mean iop order shouldn’t matter then.
