### ISSUE TITLE
mask manager: wrong set operators

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10770]
When setting up a group of shapes, for example, in a module mask, the first shape is set up without a "mode" (union/intersection/difference/exclusion) and all other subsequent shapes have a default "mode" of "union".

However, it is possible, in the mask manager, to adjust these such that the first shape _is_ assigned a mode (either by assigning it in the drop-down menu or by reordering subsequent shapes) or that subsequent shapes _do not_ have a mode (by swapping the first and second shapes).

I assume the expected behaviour should be something like:
- when right-clicking on the first shape in a group, mode options should be unavailable in the popup menu
- when moving the first shape down (or the second shape up), the new first shape should no longer have a mode associated with it, and the new second shape should have a default mode of "union"

The alternative, when swapping shapes, might be to keep the mode unchanged but just change the shape. Not sure that would be particularly intuitive though.

**Comment by victoryforce** [comment]
@TurboGit It looks like this issue is fixed by #14019 and should be closed?
