### ISSUE TITLE
Panasonic GH5-M2 - Darktable 3.8 doesn't support raw2 from this camera

### ISSUE THREAD

**Issue by thomasboots** [darktable-org/darktable#10775]
Good evening dear developers, and I wish you a happy new year!

I have just bought a new Panasonic GH5-M2, but sadly Darktable 3.8 doesn't support the raw2 files created by the camera. 

I have just uploaded the raw2 files on https://raw.pixls.us/, with the 4 formats of the camera: 4:3, 3:2; 16:9 et 1:1. So if I understood well the post of discuss.pixls.us, you have the full sample for this camera now.
Do I have to upload the files somewhere else? 
If I can do something else, let me know...

I hope I didn't miss something, so sorry if so. 

And thank you so much for this wonderful software!
Thomas

**Comment by kmilos** [comment]
Thanks for contributing the full set of samples.

This is already tracked as https://github.com/darktable-org/darktable/issues/9370

**Comment by Nilvus** [comment]
As it is a duplicate, I so close it. Thanks for your samples.
