### ISSUE TITLE
Automated upload of images to Pixelfed

### ISSUE THREAD

**Issue by Lukas2112** [darktable-org/darktable#10774]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
My thought would have been to enable a direct upload from Darktable to Pixelfed to establish a workflow for photographers that could be very exciting.

**Alternatives**
Manual upload.

**Additional context**

**Comment by johnny-bit** [comment]
New export target is a job for https://github.com/darktable-org/lua-scripts since pixelfed is external upload.

**Comment by TurboGit** [comment]
Well we have export for Piwigo. We may want to also support PixelFed as it is an Open Source project. Now we need a volunteer to add support for it.

**Comment by Lukas2112** [comment]
Then it would certainly be very useful to declare this issue with "Good first issue" or similar, like "needed help" or so, to let software developers who want to contribute to this OSS project know where you can help, @TurboGit & @johnny-bit ?
