### ISSUE TITLE
Scripts not working on Ubuntu 20.04.2 and DT 3.8.0

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#10773]
**Describe the bug/issue**
Scripts submenu in Lightable view is missing. It may be related to my OS, not Darktable, but I haven't found anything useful about this on the internet..

**To Reproduce**
Launch DT on Ubuntu 20.04.2

**Expected behavior**
Manage, enable and use scripts (I use Hugin stuff) 

**Platform**
* darktable version : 3.8.0
* OS                : 5.11.0-43-generic
* Distro    : 20.04.2-Ubuntu
* Memory            : 16GB
* Graphics card     : Iris Xe

**Comment by Nilvus** [comment]
Lua 5.4 is required. You probably have Lua 5.3. Check your system for that and check on Opensuse repository if there's deb lua 5.4 packages for your distrib. If ok, think about closing this issue. Thanks.

**Comment by Nilvus** [comment]
Oh and try to reinstall darktable 3.8 from last Opensuse repository package. Seems that lua support were forgotten in first package. See this thread: https://discuss.pixls.us/t/lua-script-option-disappear-after-updating-to-3-8/28727/10

**Comment by Pizzacutter-at-tty3** [comment]
Why would I install darktable from Opensuse repo if I'm using Ubuntu? As it appears, all I need now is enable lua support in DT, as I got lua 5.4 now.

**Comment by Nilvus** [comment]
> Why would I install darktable from Opensuse repo if I'm using Ubuntu? I install DT from apt repo, so I can't tell which exact version I have installed right now (maybe it is somewhere). As it appears, all I need now is enable lua support in DT, as I got lua 5.4 now, is there some file where to change that?

Opensuse is also a repository, by their Open Build System. Check here to access this repository: https://www.darktable.org/install/

**Comment by Pizzacutter-at-tty3** [comment]
Yes, I see, but how do I enable lua in DT? In darktable --version I see that it's disabled

**Comment by Nilvus** [comment]
> Yes, I see, but how do I enable lua in DT? In terminal, _darktable --version_ says that it's disabled

Just read better my comments here. I explained it.
