### ISSUE TITLE
[v3.8] "Filmic mid-tone saturation" mislabeled in quick-access panel

### ISSUE THREAD

**Issue by mbaz** [darktable-org/darktable#10777]
In darktable 3.8, filmic's mid-tone saturation slider is mislabeled as "extreme luminance saturation" in the quick access panel.

Reference: https://discuss.pixls.us/t/filmic-mid-tone-saturation-missing-from-quick-access-panel/28593/4

**Comment by TurboGit** [comment]
Closing: See https://github.com/darktable-org/darktable/issues/10956#issuecomment-1019561301
