### ISSUE TITLE
Scene-referred alternatives to Vignetting, Color Zones

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#10783]
**Is your feature request related to a problem? Please describe.**
1. Recently, I have learned about what scene- and display-referred workflows are and found out (as probably many others did), that most of my favorite modules are not scene-referred. I have found and got used to the alternatives for other modules, but not yet for Vignetting and Color Zones.

**Describe the solution you'd like**
- _Vignetting_ could have a scene-referred alternative, or be changed to scene-referred, as Graduated Density is not quite enough to apply darkening to all edges. Perhaps Vignetting could have a brightness control for the _center_ area? I often want to darken the edges and brighten up the center.
- _Color Zones_ is a module where I cannot tell if it is possible to be scene-referred, but it would be cool.

**Alternatives**
- Maybe just add the center brightness (and for consistency sake also saturation) control for Vignetting.

**Comment by MStraeten** [comment]
to replace vignetting you can use exposure in combination with a drawn mask and feathering to achieve that effect. 
In your case you might have two instances of exposure using the same mask (define it in the first instance and reuse as inverted pixel mask in second) to brighten up the center and darken the edges

Color zones can be replaced with a couple of masked colorbalance instances - but as long as you don't overdo color zones is fine

**Comment by wilecoyote2015** [comment]
I agree with @Pizzacutter-at-tty3 and second the request.
In the past, I have faced numerous situations where I missed Vignetting and (especially) Color Zones modules compatible with the scene-referred workflow.
The current implementation of Color Zones breaks the image's color quite quickly, unfortunately.

**Comment by shinoryo1216** [comment]
> to replace vignetting you can use exposure in combination with a drawn mask and feathering to achieve that effect. In your case you might have two instances of exposure using the same mask (define it in the first instance and reuse as inverted pixel mask in second) to brighten up the center and darken the edges
> 
You can use the scene referred Vignetting for lens correction when your lens is not supported by lensfun. I don't like your method for this purpose, because drawn mask can not be stored by preset.

**Comment by spaceChRiS** [comment]
> to replace vignetting you can use exposure in combination with a drawn mask and feathering to achieve that effect.

Unfortunately, the regular drawn marks are not very suitable for vignetting, as e.g. the drawn circle cannot become large enough to allow the required shadowing at the borders. Maybe my technique is wrong, so I would be happy too learn a better method here. If not, a combination of the vignetting module's mask gui in combination with the exposure module's math would be extraordinarily helpful.

As a new module, a place just before filmic in the pipeline may be best, to include all local modifications in the vignette. As a masking addition to the regular exposure module, it would be the user's responsibility to shift it into the correct position.
