### ISSUE TITLE
[v3.8] Panasonic DMC-G2 RW2 format support broken

### ISSUE THREAD

**Issue by chris4git** [darktable-org/darktable#10787]
Since 3.8.0 upgrade I can't open my Panasonic raw RW2 images. An error message saying DT is unable to load image, back to lighttable, is displayed instead.

Hope this will be fixed very soon...

**Comment by kmilos** [comment]
What camera?

**Comment by chris4git** [comment]
Panasonic DMC-G2

**Comment by kmilos** [comment]
See ["Suspended Support" section of the dt 3.8 release notes](https://www.darktable.org/2021/12/darktable-3.8.0-released/).

Please contribute your camera samples to [raw.pixls.us](https://raw.pixls.us/) if you would like to see the support resorted in future versions.

**Comment by chris4git** [comment]
I don't understand: I have been using DT for at least 8 years and have always used it to process my RW2 images!
Why would the support have been removed?

**Comment by kmilos** [comment]
https://github.com/darktable-org/darktable/issues/10717#issuecomment-1002137121

The old data was never validated in the usual rawspeed/dt procedure, and a call for missing samples was out for years.

**Comment by chris4git** [comment]
I've uploaded 4 samples on raw.pixls.us but don't see them in the repository

**Comment by johnny-bit** [comment]
You have to wait - the process of reviewing data is done manually

**Comment by PeterWem** [comment]
Now when you have uploaded the samples you can edit the file cameras.xml and remove _supported="no-samples"_

**Comment by chris4git** [comment]
that's what I've already done as a workaround.
Thanks
