### ISSUE TITLE
Minimal window width too wide for low-resolution screens 

### ISSUE THREAD

**Issue by nicorikken** [darktable-org/darktable#10792]
**Describe the bug/issue**

In Darktable 3.8.0 the minimal window width is about 1652 pixels, which is wider than my small screen with a lower-resolution. As a result the window cannot full-screen either, and stuff is falling off the screen. It renders Darktable practically unusable.

I use a small Acer Aspire C720p chromebook flashed with Ubuntu as a handy little portable computer. It has a screen with an 1366x768 resolution. Until yesterday I used [Darktable 3.0.1-0ubuntu1](https://packages.ubuntu.com/focal/darktable) package on Ubuntu 20.04 LTS. That worked fine on the small screen, even with the Ubuntu Dock on the side. Then I updated to the latest and greatest Darktable 3.8.0 by installing from Flathub. Now the window is wider than the screen resolution. So it cannot full-screen, and I have to manually drag out the window to fit the screen a bit. For example in Lighttable mode I first have to drag the window to the right to import images, and later drag the window to the left to be able to access the export options. I tried hiding side-panes and changing the number of thumbnails in preview, but that didn't matter.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open Darktable
2. Try to make the window smaller in width
4. See that it cannot go down to the 1366 pixels of my screen resolution 

**Expected behavior**
Have the ability to shrink the width of Darktable down to about 1300 pixels, as was possible in the past.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.8.0
* OS                : e.g. Ubuntu
* Linux - Distro    : e.g. Ubuntu 20.04
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **I'd have to check, it was fine in 3.0.1**

**Considerations for resolution**
I'd like to add that I understand I have an edge-case here, as most users will have a full-HD resolution screen or even larger setup. And I do have that as well on other laptops, but I greatly enjoy the portability of this small laptop and would like to keep using Darktable on it. I don't know the involved technicalities in detail. If it would be difficult to reduce the minimal width, I can certainly understand a 'won't fix', but at least I wanted to make you aware of the issue and how it can impact users.

**Praise**
Thank all of you for working on Darktable! ♥

**Comment by Nilvus** [comment]
Processing image in such small resolution is not recommended. Such resolution let too less place for the image. Minimum recommended resolution is full HD (1920x1080) and this had already been discussed here and will not change. So unfortunately, we know that issue but this will be a won't fix and for good reasons: let place for the image.

Anyway, it's possible to use darktable in your small resolution: just reduce both left and right panels width and you will then be able to reduce window size. And darktable will save last size when you close it.

I let this open 1 or 2 days but if my last info works on your side, please close this issue. Thanks.

**Comment by parafin** [comment]
I have MacBook Air 13" with screen resolution of 1440x900 and darktable window fits and usable. Minimum width is probably affected by font size. Maybe if you post a screenshot it would be more apparent why it's so wide for you.

**Comment by nicorikken** [comment]
@Nilvus I agree with the resolution being small for serious editing, but a lot can be done by hiding all panes. Also I use that laptop mainly for more simple Darktable tasks like tagging, cropping and exporting.

@parafin Thanks, I unchecked the 'use system font size' box in the 'general' section of the preferences, and set it to 9.0 font size. Now it works well for me. The text may be small but large enough for me.

So won't fix is the right resolution for me, let's not dwell on this.
