### ISSUE TITLE
Fujifilm Finepix HS50EXR

### ISSUE THREAD

**Issue by apinheirofilho** [darktable-org/darktable#10797]
Darktable 3.8.0 do process raw file  .raf.

**Comment by victoryforce** [comment]
See ["Suspended Support" section of the dt 3.8 release notes](https://www.darktable.org/2021/12/darktable-3.8.0-released/).

Please contribute your camera samples to [raw.pixls.us](https://raw.pixls.us/) if you would like to see the support restored in future versions.
