### ISSUE TITLE
Sony A7IV raw files not supported as indicated with version 3.8 of Darktable on my Windows 10 laptop.

### ISSUE THREAD

**Issue by Dtinit2** [darktable-org/darktable#10802]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by MStraeten** [comment]
since you didn't provide any relevant info (The template isn't just for fun) i checked this with an arbitrary downloaded A7 IV raw file on my mac - and it loads fine.
So if someone should be able to help provide more information...

**Comment by kmilos** [comment]
The new lossless compression mode is the only one not supported unfortunately, just like with the A1...

**Comment by Dtinit2** [comment]
Thank you both. Sorry for my lack of information, I am new to GitHub. These particular images are probably the new Sony lossless format. Thank you again...

**Comment by kmilos** [comment]
@TurboGit This exception was unfortunately removed from the release notes in https://github.com/darktable-org/darktable/commit/cca3d49d40ce51ea8c70451c182c81481509febc by the automatic generator...

**Comment by johnny-bit** [comment]
Judging by content - closing in favour of #8523. If the closing was incorrect just comment and I'll reopen.

**Comment by Dtinit2** [comment]
Thank you for your help. Darktable does not work with Sony lossless compressed files, uncompressed works.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Hubert Kowalski ***@***.***> Date: 1/8/22  3:09 PM  (GMT-06:00) To: darktable-org/darktable ***@***.***> Cc: Dtinit2 ***@***.***>, Author ***@***.***> Subject: Re: [darktable-org/darktable] Sony A7IV raw files not supported as
  indicated with version 3.8 of Darktable on my Windows 10 laptop. (Issue
  #10802) 
Judging by content - closing in favour of #8523. If the closing was incorrect just comment and I'll reopen.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/darktable-org/darktable/issues/10802#issuecomment-1008154440",
"url": "https://github.com/darktable-org/darktable/issues/10802#issuecomment-1008154440",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
