### ISSUE TITLE
3.8.0 isn't completely wide enough in mac os

### ISSUE THREAD

**Issue by Lilja** [darktable-org/darktable#10804]
I fullscreened darktable on my 13inch macbook pro. It seems a some settings are not shown here, like the rest of the exposure bar. Reset module thing, etc.

<img width="1280" alt="bild" src="https://user-images.githubusercontent.com/6134511/148201383-ccf419c3-c8f9-4f8c-a52a-9485cf854130.png">

```
lilja in ~ λ uname -a
Darwin Eriks-MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```
<img width="583" alt="Screenshot 2022-01-05 at 11 23 50" src="https://user-images.githubusercontent.com/6134511/148202026-0ec381ba-a29e-4406-ab98-ac01a0d83e1c.png">

**Comment by parafin** [comment]
Probably window is too wide. Try making sidebars smaller or/and decreasing font size.

**Comment by parafin** [comment]
Try the other way around, drag the other way.

**Comment by Lilja** [comment]
I went to download OBS to record this problem, and when I visited it it was wide enough for all of the content. Very weird. Closing this issue.

**Comment by rosulek** [comment]
I had the same issue. When darktable was a normal window, it could not be resized horizontally (not smaller than some limit, and that limit was smaller than my screen size). When darktable was full-screen / maximized, things were cut off on the right. 

I was finally able to fix it by doing the following:

HOW TO FIX DARKTABLE WINDOW TOO WIDE ON MAC: 
* ensure that darktable is **not maximized** / fullscreen
* resize darktable's **left panel** -- i.e., make it narrower
* only now can you reduce the width of the overall darktable application window
* when the non-fullscreen darktable window is narrow enough to fit in your screen, then you can maximize/fullscreen it

Resizing the right panel did not work. Resizing the left panel while darktable is maximized did not work.

In the process I discovered some weird behavior (which I now report as a bug):

* maximize darktable (in MacOS, I'm using 12.1)
* increase the width of the left panel
* eventually you will see important things "fall off" the right side of the screen
* decrease the width of the left panel back to where you started

Expected result: things are back where they started
Actual result: important stuff remains "fallen off" the right side of the screen, and can only be restored by doing what I described above
