### ISSUE TITLE
Migration of source code located on GitHub to Codeberg

### ISSUE THREAD

**Issue by Lukas2112** [darktable-org/darktable#10803]
**Is your feature request related to a problem? Please describe.**
Yes, basically: There has been an (in)direct dependency on the Microsoft group, which bought out Github, since 2018.

**Describe the solution you'd like**
My question would be whether it would be possible to migrate the source code to Codeberg[1], which is based on Gitea, without massively changing workflows.

**Alternatives**
Migrate to GitLab.

**Additional context**
[1]: https://codeberg.org

**Comment by MStraeten** [comment]
whats the benefit of this beside ideology?

**Comment by Lukas2112** [comment]
Ensuring compliance with European data protection standards (GDPR) is guaranteed. The regulations are very strict and Microsoft is unfortunately known for not observing them.  

Well, from my point of view, I think it could help the project to become more independent from big companies, like Microsoft, because Codeberg is run by a non-profit association from Germany, Codeberg e. V., and not by a for-profit company, as is the case with GitHub (since 2018).

**Comment by MStraeten** [comment]
ok, just ideology ;)

**Comment by Lukas2112** [comment]
Well, I wouldn't call it ideology because I think it has a very negative connotation. 

Maybe I would call it a kind of "philosophy"?

**Comment by TurboGit** [comment]
Certainly I would love to quit GitHub... But with such project all the issues and PR plus the habits of all devs it would be a big earthquake that for now I don't see a big incentive. And if I would move I would certainly look for GitLab.

**Comment by Lukas2112** [comment]
Okay, you're right - I'll close the issue.
