### ISSUE TITLE
tone equalizer presets default to display referred blending mode 

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#10800]
**To Reproduce**

If I start fresh on an image, enabling tone equalizer with a preset leads to switching the previously selected "scene referred" blending mode to the old "display referred blending mode.
More-over: if the module was untouched before the masking settings get lost too.

https://user-images.githubusercontent.com/810285/148137499-e0a921ce-48f4-42c4-a4dc-59aab74951aa.mp4

If I however configured the tone equalizer already and then switch to a preset, I'm not going to lose the masking settings, but the blending mode is still changed back to "display referred" mode.

https://user-images.githubusercontent.com/810285/148137594-271c3c4c-95f9-49e1-83cd-c0a048d99c31.mp4

As you can see in my settings I've activated "scene referred" workflow by default:

![Screenshot from 2022-01-05 00-31-39](https://user-images.githubusercontent.com/810285/148138007-b3a52251-c3fd-4448-90a4-3f8f6bdeaede.png)

**Expected behavior**

1. Tone equalizer blending modes shall not default to "display referred" if I configured DT to use the "scene referred" workflow
2. Masking settings should remain configured if a preset has been selected, as the preset is not overwriting the masking settings (e.g. parametric mask)

**Platform**
* darktable version : 3.7.0+1757~ga3a12e54a-dirty
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04
* Memory            :  32 GB
* Graphics card     :  AMD RX5800XT
* Graphics driver   : amdgpu-pro
* OpenCL installed  : yes
* OpenCL activated  : yes
* CMAKE_BUILD_TYPE  : release

**Comment by difrkaguilar** [comment]
This issue is more less similar to #10080 RGB (scene) by default in masks blending options if scene-referred is the default workflow.

**Comment by da-phil** [comment]
I think I could address the issue in https://github.com/darktable-org/darktable/pull/10822 
What do you guys think? Maybe @aurelienpierre?
