### ISSUE TITLE
Add ability to propagate Rejected flag (and similar flags) to grouped images

### ISSUE THREAD

**Issue by europlatus** [darktable-org/darktable#10809]
**Is your feature request related to a problem? Please describe.**
With the current grouped image system, setting the Rejected flag applies to grouped images when "collapse grouped images" is enabled. However, when grouped images are expanded, setting the Rejected flag only applies to the image you manually reject. I'm assuming this is by design. If you have left grouped images expanded and reject only the raw files, for example, it can be time consuming and laborious to then reject all the corresponding JPEGs.

**Describe the solution you'd like**
It would be good to have the ability to quickly propagate the Rejected status (or other flags) to grouped images. This could be a dedicated button or a setting in preferences. The dedicated button would be useful for when you have forgotten to collapse grouped images when culling or if you change your mind at a later date.

**Alternatives**
A setting in the preferences could provide the option to change the default behaviour so that setting the Rejected flag (or similar flags) always applies to grouped images, whether they are collapsed or expanded.

**Comment by Solarer** [comment]
So you also want this feature for color labels and star rating?
How should darktable behave if images have multiple (and/or conflicting) flags?

**Comment by europlatus** [comment]
My main interest is in the rejected flag, so I haven't given any thought to other flags. Just thinking off the top of my head, a setting in preferences could simply ask whether flags on the RAW file should also apply to the JPEG. If enabled, the user would only set flags and ratings on the raw and everything will automatically apply to the grouped JPEG. If not enabled, the two types of files are handled separately.
If there is an option to propagate flags and ratings after the fact, it depends how complicated we want it to be. There could be multiple checkboxes for copying rejected, stars and colors and the user can decide which to copy over. Or a simpler feature would just be to ask for confirmation that all flags and ratings on the JPEG would be overwritten by the operation. As darktable is a raw editor, my assumption here is that users are generally working on the RAW files and that the operation is just RAW > JPEG rather than the other way round. But maybe there's an argument for being able to do the operation in reverse if there is a use case for it.

**Comment by Solarer** [comment]
I believe if you duplicate an image they are also grouped. So you could end up with groups of multiple raws or multiple jpegs.
You can also group images manually, creating mixed groups.

**Comment by phweyland** [comment]
> With the current grouped image system, setting the Rejected flag applies to grouped images when "collapse grouped images" is enabled. However, when grouped images are expanded, setting the Rejected flag only applies to the image you manually reject. I'm assuming this is by design.

Right, that's the purpose: you have then the choice to apply or not the action to duplicates.
To fix a small number of mistakes you can use selected `image[s]/metadata/copy-paste`.

A lua script may be the way to go...
