### ISSUE TITLE
Assign name of preset to module instance

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#10817]
**Is your feature request related to a problem? Please describe.**
Not a problem, rather an inconvenience. darktable ships with many modules that offer useful presets. Sometimes one may employ several instances (e.g., _color calibration_ could be used for white balance/adaptation, as a channel mixer, for film simulation; _diffuse or sharpen_ to reduce noise, apply local contrast, inpaint highlights etc.). In such cases, the order is usually important, and to set up / verify the order, the name is helpful.

**Describe the solution you'd like**
I suggest automatically assigning the name of the preset as the name of the module instance, if the module instance is created using a name, with perhaps a numeric suffix (as it is done currently) to ensure uniqueness.

**Alternatives**
Renaming manually is already possible.

**Comment by ralfbrown** [comment]
You can also do this with styles, which doesn't limit you to names the same as the preset -- if a style contains a module instance with a name that isn't yet instantiated in the image's history, a new instance with that name is created.

But yes, auto-renaming can be useful in many cases.

**Comment by elstoc** [comment]
What if you select a preset as a starting point and then manually alter the parameters? I can maybe see the utility of it but I wouldn't want it happening all the time.

**Comment by difrkaguilar** [comment]
The idea is not bad, but as @elstoc says, if the parameters are changed later, then what happens? the name of the preset already created in the module header is automatically removed and the corresponding numerical sequence is put, e.g. 1, 2, 3, and so on?

**Comment by kofa73** [comment]
I thought that the assigned name would stay. Say, I add two instances of _diffuse or sharpen_: one created using the _add local contrast_ preset, one with _lens deblur: soft_. Then maybe I tweak the parameters to make the effect stronger or more subtle, but it's unlikely that I tweak one of them to do denoising, for example. Same with _color calibration_: if I add a _basic channel mixer_, I definitely *will* tweak its parameters; but still, the intent is that of channel mixing.

As for using presets:
- it's laborious and I hate duplication
- if the defaults of the preset change, the preset would not. I look at built-in presets as recommended values set by experts of the given module. I have a few of my own, but find the built-in ones valuable, and if they are updated, I'd like to follow the changes for new edits.

**Comment by elstoc** [comment]
Also depends a bit on how the presets are named (for example I have a few presets called "default" or "starting point" and these make no sense as a module name. Anyway I don't object to the feature but it must be optional if implemented because it will annoy as much as it will please.

**Comment by jade-nl** [comment]
My reaction when reading the original post: _No! Please don't implement this..._

So I fully agree with @elstoc's remark about implementing this and making it optional (turned off by default?).

Just my 2c.

**Comment by kofa73** [comment]
What about an alternative: when creating a new instance, the name is immediately editable, without having to go again to _multiple instances_ and clicking _rename_? I find the current names (module name + number) are pretty much useless. I'm surprised by the strong negative feedback to using the preset name, but I accept it.

**Comment by elstoc** [comment]
@kofa73 that's already implemented in preferences > darkroom > modules > prompt for name on addition of new instance

**Comment by kofa73** [comment]
Oh, I was looking for it but didn't find it. Thanks! Closing the issue.

**Comment by kofa73** [comment]
Even if _prompt for name on addition of new instance_ is enabled, when I right-click a preset to create a new instance initialised with those settings, there is no prompt, only when _multiple instance actions -> new instance_ is used.

**Comment by elstoc** [comment]
Sounds like a bug

**Comment by kofa73** [comment]
https://github.com/darktable-org/darktable/issues/10830
