### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Crapaud1988** [darktable-org/darktable#10813]
darktable crashes randomly when I switch between modules or between lighttable and darkroom.

**To Reproduce**
It seems random to me.

**Platform**
* darktable version : 3.8.0
* OS                : Win10 (19042.1415)
* Memory            : 16Go
* Graphics card     : GTX970
* Graphics driver   : 497.2
[darktable_bt_N19BF1.txt](https://github.com/darktable-org/darktable/files/7817530/darktable_bt_N19BF1.txt)
[darktable_bt_S1LBF1.txt](https://github.com/darktable-org/darktable/files/7817531/darktable_bt_S1LBF1.txt)
[darktable_bt_UWOQF1.txt](https://github.com/darktable-org/darktable/files/7817532/darktable_bt_UWOQF1.txt)
[darktable_bt_Y417E1.txt](https://github.com/darktable-org/darktable/files/7817533/darktable_bt_Y417E1.txt)
[darktable_bt_4C1CF1.txt](https://github.com/darktable-org/darktable/files/7817592/darktable_bt_4C1CF1.txt)

**Comment by victoryforce** [comment]
I see the buggy version of libpango (1.50.0) in your backtraces. This version known to cause crashes in darktable (see #10557, #10588, #10593). Did you compile dt 3.8.0 yourself?

**Comment by Crapaud1988** [comment]
Ok thank you for your answer.
No, I downloaded it from either https://www.darktable.org/install/ or https://darktable.fr/ and then https://github.com/darktable-org/darktable/releases, but I didn't compile it myself.

**Comment by victoryforce** [comment]
@Crapaud1988 After a second look at your backtraces I'd say that my first guess likely was wrong. Overall pattern of calls looks different and, most importantly, there are no libpango calls in those traces.
