### ISSUE TITLE
Add PPI option to JPG export

### ISSUE THREAD

**Issue by bubberson** [darktable-org/darktable#10820]
It often makes it easier to compress jpg files if you reduce the amount of pixels per inch to a number less than the default 300. I usually do 150ppi for images that are not intended to be printed, only shared or posted online. Is there a way to implement this?

**Comment by ptilopteri** [comment]
crop

**Comment by elstoc** [comment]
The export module allows you to specify the maximum width/height in pixels. Alternatively you can define it in cm/inches, for which you also need to define PPI. I'm not sure what you're asking for here.

**Comment by TurboGit** [comment]
> It often makes it easier to compress jpg files if you reduce the amount of pixels per inch to a number less than the default 300.

This makes no sense to me. An image exported with 1920x1080 will always have the same number of pixels and do not depend on the DPI. Not that DPI means Dot Per Inch and an image has no inch or cm or whatever. The DPI is only meaningful if you send you image to a physical devices (paper, screen...). And as @elstoc noted, we have an option in the export module with dpi/inch or dpi/cm.

**Comment by TurboGit** [comment]
And yes I know that Photoshop has such option... They should fix this and stop confusing people.
