### ISSUE TITLE
diffuse or sharpen - incorrect tooltip on 2nd order speed ?

### ISSUE THREAD

**Issue by phil20099** [darktable-org/darktable#10829]
**Describe the bug/issue**
For diffuse or sharpen the manual entry says the 1st and 2nd order speed are _low_ frequency and the 3rd and 4th are _high_ frequency.

https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/diffuse/

In darkroom the tooltip against the 2nd order speed says "smoothing or sharpening of _sharp_ details" and I'm assuming it should show as _smooth_ details ?  This assumes the manual is correct.

Essentially the 2nd and 3rd order speed have the identical tooltip.

In Ubuntu running v3.8.0 from OBS.

**Screenshots**
edit : source below is from the master, not v3.8.

![image](https://user-images.githubusercontent.com/60315272/148639103-04e7ef04-cdd3-496e-8ae3-39ac2306f208.png)

**Comment by phil20099** [comment]
Having just checked the diffuse.c source code in v3.9 this is still an issue.

**Comment by quovadit** [comment]
I tried to change the tooltips in #10432 but "the discussion is not over yet"

**Comment by quovadit** [comment]
#14032 is merged now, so it will be part of dt 4.0

**Comment by phil20099** [comment]
Fixed in v4.0, thank you.
