### ISSUE TITLE
Shortcut for 100% zoom causes 200% zoom

### ISSUE THREAD

**Issue by geni1105** [darktable-org/darktable#10839]
**Describe the bug/issue**

If the defined key shortcut (alt+1) is used for 100% zooming in darkroom view, it goes to 200% instead of 100%.
Selecting 100% from the popup menu in the navigation panel works correctly. 

**To Reproduce**

Use shortcut for 100% zoom.

**Expected behavior**

Display image at 100% zoom.

**Platform**

* darktable version : 3.8.0
* OS                : macOS 11.6.2 Big Sur
* Memory            : 16 GB
* Graphics card     :  iMac (Retina 5K, 27-inch, Late 2014) // AMD Radeon R9 M290X 2 GB
* OpenCL installed  : y
* OpenCL activated  : y

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by Nilvus** [comment]
Strange, I go to 100% when using Alt+1. Actually in master but I doubt something had changed on that since 3.8.0.

**Comment by Nilvus** [comment]
If I press a second time Alt+1, I so go to 200%, as expected. Maybe your keyboard is set to sensitive or something like that. Check if needed also what you have in shortcuts dialog window.

**Comment by geni1105** [comment]
I tried with two different keyboards (the wireless one that came with the iMac, and a normal USB keyboard) - same behavior. Repeated pressing of alt+1 toggles between 200% and 400%.

BTW, I had installed a second shortcut cmd+1 (being used to this combination from Photoshop), but deleting that one again does not change the behavior.

**Comment by geni1105** [comment]
Restored shortcuts to standards (with deleting all new shortcuts): still directly goes to 200% and toggles between 200 and 400% for repeated key presses.

Seems to be an issue with interpreting 1:1 presentation (1 monitor pixel = 1 image pixel) on Retina screens: when I change darktable's properties to "Open in Low Resolution" in macOS, then alt+1 correctly toggles between 100% and 200%,  indicated in the navigation panel. Of course that setting is not really usable, as all fonts are blurry and actually 4 monitor pixels are used to display 1 image pixel in that "100%" zoom.

**Comment by Nilvus** [comment]
So that's normal. To have same same similar view for processing image in 4k, you need to zoom 2x more, so 200%. I don't have 4k resolution. It is so as designed and no issue. Don't see % but what you have with your eyes. With 4k, it's so better to go to 200% and 100% in standard screens.

**Comment by Nilvus** [comment]
Just to complete my answer, it's all about scaling.

**Comment by geni1105** [comment]
Probably I have not expressed the issue clearly enough: clearly for the similar view than with a "normal" monitor (say 1920 x 1080) we need to zoom in like 2x more with a 4k display - but that's not the point. 
When I zoom to 100% per the shortcut, I want to end up with 100% and a 1:1 correspondence of monitor to image pixels, not with 200% and 4:1 correspondence. I am aware that this enlarges the image area compared to a lowDPI monitor, but that's what HighDPI displays are for ...

darktable is able to display "real" 100% when I select 100% in the navigation panel, so why not use that scale factor when the keyboard shortcut is used?

**Comment by Nilvus** [comment]
@dterrahe

**Comment by dterrahe** [comment]
Is this a regression in 3.8.0? I.e. did the equivalent shortcut in 3.6 work correctly?

**Comment by geni1105** [comment]
Same behavior with 3.6.1 on the Windows 10 partition on the same iMac - so seems to be related to the screen resolution rather than to the OS.

**Comment by dterrahe** [comment]
@Nilvus doesn't sound like this was caused by inputng then.

**Comment by Nilvus** [comment]
> @Nilvus doesn't sound like this was caused by inputng then.

Thanks for your reply. Noted. I let someone else see that so. Can't help more here.

**Comment by jenshannoschwalm** [comment]
The way we understand 100% zoom has been debated several times before and as i understand it, it's now exactly as is "should be".

To get a starting point into earlier discussions, see #8870

**Comment by jenshannoschwalm** [comment]
@geni1105 i don't think this **is** an issue, could you maybe read the above suggested discussion and concider closing this issue?

**Comment by geni1105** [comment]
In English, the alt+1 shortcut is described as „zoom close-up“, in German as „Zoom auf 100%“.
So the behavior probably is ok considering the English description, as what „close-up“ means is up to interpretation …
However, I would still appreciate to have a shortcut for a 100% zoom, where an image pixel corresponds to a screen pixel (irrespective of the screen resolution). Selecting 100% in the navigator drop-down does precisely this, so it should be easy to implement.  Unfortunately I could not find out where in the source code I could enable such an action - any hint appreciated …

**Comment by jenshannoschwalm** [comment]
> any hint appreciated

See pr #8870 :-)
