### ISSUE TITLE
Watermark panic

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#10840]
**Describe the bug/issue**

Trying to export an image with watermark:

![image](https://user-images.githubusercontent.com/23012047/148685715-e7ec14dd-df13-4d3f-96c7-1ceccca7a23a.png)
![image](https://user-images.githubusercontent.com/23012047/148685784-ef193604-e4a4-4a46-b388-ed3a24c6409e.png)

dt crashes:

```
(darktable:92259): Pango-WARNING **: 11:05:29.811: failed to create cairo scaled font, expect ugly output. the offending font is 'aakar Medium 105473.810546875'

(darktable:92259): Pango-WARNING **: 11:05:29.812: font_face status is: error occurred in libfreetype

(darktable:92259): Pango-WARNING **: 11:05:29.812: scaled_font status is: error occurred in libfreetype
thread '<unnamed>' panicked at 'Cairo error "error occurred in libfreetype"', /build/librsvg-M4axLs/librsvg-2.50.7+dfsg/vendor/cairo-rs/src/enums.rs:274:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted
```

I've tried several fonts with the same result.
Decreasing the scale to 50% escapes the issue.

**Platform**
* darktable version : 3.9.0+69~gb72c7d7ba
* Linux - Distro    : debian sid

**Comment by ralfbrown** [comment]
What is the pixel resolution of your image?  I suspect that Pango or Freetype is hitting some internal limits on font size.

(darktable works with reduced resolutions in darkroom view, so the issue would not occur while editing)

**Comment by phweyland** [comment]
> What is the pixel resolution of your image?

6032x4032.

**Comment by alpinekid** [comment]
I also have this problem.
	(darktable:7798): Pango-WARNING **: 10:00:52.070: failed to create cairo scaled font, expect ugly output. the offending font is 'DejaVu Sans 72397.96875'
	
	(darktable:7798): Pango-WARNING **: 10:00:52.070: font_face status is: error occurred in libfreetype
	
	(darktable:7798): Pango-WARNING **: 10:00:52.070: scaled_font status is: error occurred in libfreetype
	thread '<unnamed>' panicked at 'Cairo error "error occurred in libfreetype"', /build/librsvg-RSSQuy/librsvg-2.48.9/vendor/cairo-rs/src/enums.rs:274:13
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
	fatal runtime error: failed to initiate panic, error 5


I have also reduced the scale and it goes away. Not sure if 50% is the magic or not; I went down to 34 to get my text to fit.
enviroment;
darktable 3.8.1
linux ubuntu 20.4 with latest updates.

**Comment by asdkant** [comment]
I'm also having this issue. I get this output in the terminal:
```
(darktable:27985): Pango-WARNING **: 19:14:26.104: failed to create cairo scaled font, expect ugly output. the offending font is 'DejaVu Sans 544016.572265625'
(darktable:27985): Pango-WARNING **: 19:14:26.104: font_face status is: error occurred in libfreetype
(darktable:27985): Pango-WARNING **: 19:14:26.105: scaled_font status is: error occurred in libfreetype
(darktable:27985): Pango-CRITICAL **: 19:14:26.180: pango_font_description_set_size: assertion 'size >= 0' failed
(darktable:27985): Pango-WARNING **: 19:14:26.180: failed to create cairo scaled font, expect ugly output. the offending font is 'DejaVu Sans'
(darktable:27985): Pango-WARNING **: 19:14:26.180: font_face status is: error occurred in libfreetype
(darktable:27985): Pango-WARNING **: 19:14:26.180: scaled_font status is: error occurred in libfreetype
```

when trying to use this SVG with the text `2` (the number 2), all other options in their defaults
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg"
     x="0"
     y="0">

  <text x="0" y="7px" text-anchor="start"
        fill="$(WATERMARK_COLOR)"
        font-family="$(WATERMARK_FONT_FAMILY)"
        font-style="$(WATERMARK_FONT_STYLE)"
        font-weight="$(WATERMARK_FONT_WEIGHT)"
        font-size="10px"
        letter-spacing="2px"
        >$(WATERMARK_TEXT)</text>
</svg>
```
