### ISSUE TITLE
Hasselblad L2D-20c  DJI Mavic 3 main camera

### ISSUE THREAD

**Issue by JooB1** [darktable-org/darktable#10852]
Import of files from hd fails in dt 3.8.0 windows 10: can't load file... check if camera model is supported...
No preview, just the skull.
Files are imported and displayed in Luminance etc. without problems.
Raw samples are uploaded to https://raw.pixls.us/.
Thanks for your work!

**Comment by kmilos** [comment]
I see this error in the log on another sample:

`void rawspeed::UncompressedDecompressor::sanityCheck(const uint32_t*, int) const, line 60: Image truncated, only 3885 of 3956 lines found`

**Comment by kmilos** [comment]
Indeed, someone should let DJI know they are producing borked DNG files:

```
ImageWidth                      : 5376
ImageHeight                     : 3956
BitsPerSample                   : 16
SamplesPerPixel                 : 1
RowsPerStrip                    : 3956
StripByteCounts                 : 41775360
```

3956*5376*2 = 42534912

What they put in `StripByteCounts` is assuming width of 5280:

```
DefaultCropOrigin               : 0 0
DefaultCropSize                 : 5280 3956
ActiveArea                      : 0 0 3956 5280
```

**Comment by JooB1** [comment]
Thanks for the quick response!
I just opened a ticket at DJI quoting your results and hope they will fix it quick.
Just wondering why dt has this problem and products like Luminance not, I thought I learned both use the same raw import libraries...

**Comment by JooB1** [comment]
They really improved the batteries!!!   
Ok, next ticket...

**Comment by kmilos** [comment]
> Just wondering why dt has this problem and products like Luminance not, I thought I learned both use the same raw import libraries...

Obviously not... dt uses RawSpeed.

**Comment by JooB1** [comment]
I can confirm changing StripByteCounts to the correct value solves the import problem. Too bad you have to use a hex editor to change this value.
I close the ticket, thanks for your help!!!

**Comment by kmilos** [comment]
Yes, exiftool wouldn't let me modify it (tag is write protected), I haven't tried if exiv2 can do it...
