### ISSUE TITLE
show system display profile name(s) somewhere

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10856]
Setting up color management can be a hard thing to do and knowing that you've got it right, especially if you aren't using colord, is also hard -  without colord `darktable-cmstest` shows that the profiles are different but doesn't necessarily confirm to the user that darktable is using the right thing. 

You can tell darktable to force-use xatom in this case but all that ever shows in the display profile popovers are the words "system display profile". That text doesn't confirm what darktable has actually loaded (or even that it's loaded anything at all), though you can run `darktable -d all` and the loaded profile is there hiding amongst all the other logs.

It would be great if we could display the actual names of the loaded profile(s) in the UI (preferably in the popovers where the profiles are set) just to give people the warm feeling inside that their efforts have been fruitful.

**Comment by parafin** [comment]
A problem with this FR is that if you have multiple monitors, then "system display profile" doesn't actually refer to some single profile. Changing its name when moving the window is probably possible, but isn't that straightforward. Maybe instead a better idea is to move/copy darktable-cmstest functionality into preferences dialog of darktable UI.

**Comment by elstoc** [comment]
The popover (when you right-click the display profile button) has selectable profiles for the primary and secondary monitor:

![Screenshot_2022-01-11_10-54-11](https://user-images.githubusercontent.com/9555491/148929942-f47f9324-69c9-4b45-bdac-57f9791e33c8.png)

If a named profile will be used when you select "system display profile" could the dropdown be amended to say "system display profile (\<name\>)"? Though that might get a bit verbose for "system display profile (second window) (\<name\>)".

**Comment by parafin** [comment]
> > Maybe instead a better idea is to move/copy darktable-cmstest functionality into preferences dialog of darktable UI.
> 
> Perhaps but the problem is that darktable-cmstest is also unclear as to what profile(s) darktable will actually use.

Well, functionality can be enhanced while at it.
