### ISSUE TITLE
Modify how/when tag hierarchy is collapsed or expanded

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#10854]
**Is your feature request related to a problem? Please describe.**

In darktable I am catching up on correctly tagging a large portfolio of images which I have migrated from LightRoom, where keywording had become a mess. I use hierarchical tags - a lot of them - some nested to 6 layers deep. As a result my tag dictionary is long. I am most frequently updating the sequence starting with the category 'Places" but, while attaching, detaching, editing or creating tags I frequently find that the 'Places' hierarchy has been collapsed. II have to click on up to 6 tag levels and do multiple scrolling actions to get to the tag I want to apply or edit. I have tried for some time to determine exactly what action of mine it is that causes dt to collapse a hierarchy, but am unable to say definitely what it is.

Currently, when dragging a tag to reposition it in the dictionary, dt opens any 'nested' tags that the cursor traverses over in its journey to a target tag within which a selected tag is to be repositioned. This is not only confusing but frequently results in the tag dictionary no longer scrolling. At this point the 'dragged' tag has to be dropped in an inappropriate place, then re-dragged again to its intended destination -  once the mouse button has been released and the two scroll bars have been adjusted as necessary

**Describe the solution you'd like**

Once the user has expanded, partially or completely, a tag hierarchy, do not collapse it, even across a shutdown/start-up cycle. If the user partially collapses a hierarchy, maintain the partial status - do not fully close or fully open the hierarchy.

After a child tag has been created within a parent tag, reposition the cursor back on the parent, rather than on the newly created child tag, so that another child tag can be created without further cursor positioning.

Do not expand 'nested' tag hierarchies that the cursor is dragged over. These should only be expanded after the cursor has hovered over a tested tag for an agronomically appropriate time.

**Alternatives**

**Additional context**

**Comment by phweyland** [comment]
> Once the user has expanded, partially or completely, a tag hierarchy, do not collapse it, even across a shutdown/start-up cycle. If the user partially collapses a hierarchy, maintain the partial status - do not fully close or fully open the hierarchy.

I understand the request, I can agree with it, but it will only happen when the code is able to handle the display all types of operation on tags. While it cannot, the tree is displayed again from scratch.
Across sessions... would be necessary to save also the display.
Note: I've just seen that a command is missing (regression of mine probably). Shift-click on a tag should expand all the hierarchy of this tag. I'll fix that.

> After a child tag has been created within a parent tag, reposition the cursor back on the parent, rather than on the newly created child tag, so that another child tag can be created without further cursor positioning.

I like the idea. I'll check it's not in conflict with #10784.

> Currently, when dragging a tag to reposition it in the dictionary, dt opens any 'nested' tags that the cursor traverses over in its journey to a target tag within which a selected tag is to be repositioned. This is not only confusing 

Can you explain how that's confusing ?

> but frequently results in the tag dictionary no longer scrolling

This a bug. I cannot reproduce it so far. Could you give more information to reproduce it ?

> Do not expand 'nested' tag hierarchies that the cursor is dragged over. These should only be expanded after the cursor has hovered over a tested tag for an agronomically appropriate time.

?? I don't understand. Can you elaborate a bit more ?

**Comment by LateJunction** [comment]
Apologies if this reply is sent to an inappropriate address - I have no
experience of handling darktable development suggestions.

I will try to address your requests for clarification tomorrow, if I can,
between other commitments.

**Comment by LateJunction** [comment]
Hi,
This email is to try to reply to your questions with more information:

1. About apparent missing 'Shift-Click' command: this command does work,
partially,  on my Windows and Linux installs of 3.8 but provides no
additional function to clicking on the triangle (if there is one) to the
left of the tag name. It does not, as you say, fully expand the hierarchy
and I notice that there is no reference to this command option in the
'pop-up' contextual help information.
2. Concerning 'opening up of nested tags': I have purposely invoked this
behaviour again this morning and find that now I understand what is
happening, and am prepared for it, I find the action is not confusing. But
I do find an associated characteristic that I feel is a 'human-factors'
issue: my tag dictionary is now quite long; even with all hierarchies
collapsed the list is longer than will fit in the 'window', even after that
windows has been re-sized to the maximum using ctrl-wheelscroll. Now, when
hierarchies have been expended, while dragging a tag, the expanded tag
dictionary list has to be scrolled past the window. This happens
automatically, but too slowly. On my dictionary list - which is probably at
about 20% of its final size - scrolling from top to bottom takes 10's of
seconds. (I have a 9th gen. Intel i7 with 32 GB RAM). Can this automatic
scrolling be made faster?
3. This 'locking' of the dictionary window is, as you have found, difficult
to reproduce. It very much depends on four factors: (1) the relative
position of the two scroll bars - the inner (left) one controlling
scrolling of the tag dictionary in its window, (2) the outer (right) one
controlling the position of the tagging module in the right-hand pane, (3)
the amount of automatic expanding of hierarchies that takes place during
the drag operation, (4) the initial and final locations of the tag to be
dragged. I am in the process of rationalising, extending and correctly
allocating tags to one of 5 Lightroom catalogs which I have transferred to
dt. The last time I did serious 'keywording' in Lightroom was 2010, since
then that catalog tripled in size to 2019 (xfer to dt) and has grown by 30%
since the move to dt. So, I have a lot of tag editing to do. This means
that I have been frequently dragging tags around, quite often between the
extreme top and bottom of the dictionary. Because the tag dictionary window
is fully resized, I position the tagging module (using the outer scroll
bar) so that the module 'title' ("tagging") is just off the top of my
screen. in the past 4 or 5 days, I have experienced about 20 times when the
scrolling of the tag dictionary window has frozen part way through dragging
a tag (usually downwards) to its intended destination. Then there is no way
to cancel the drag; the tag has to be deposited somewhere under the cursor
and dragged a second time to its intended destination - sometimes after a
bit of a search to find out where it had been 'dropped' (including
remembering what the tag name was!). Sorry, I can't describe it much better
than this.
4. I think I see and understand the benefit of automatically expanding a
nest of tags - it is obviously necessary when I reach my destination of the
drag to be able to see exactly where the dragged tag should deposited. But,
on the way, I would like other 'nests', which are not at all a relevant
'destination', to remain collapsed as I drag over them. Of course, dt had
no way of knowing what is or is not relevant. But I can convey that
information (which I alone know) by stopping the drag and hovering over the
top level name of a nest of tags. After a certain period of hover - say
between 500 and 1000 milliseconds (a time which is clearly longer than the
rime spent while dragging over an irrelevant nested tag name, but not so
long as to interrupt workflow and thinking) - then the nest should be
expanded, one level at a time, as I then continue to drag within the
expanded nest. Is that description of my suggestion understandable?

**Comment by phweyland** [comment]
>  Can this automatic scrolling be made faster?

I think so. But if we go too fast the risk to go too and loose stability.

> It very much depends on four factors: 

I understand. As long as I don't reproduce myself the issue, I cannot fix anything unfortunately.

> Is that description of my suggestion understandable?

Sorry, that remains a bit confused for me.
Trying to reproduce a move from one side to the other of a long list (2000 tags) I see the following.
- starting from a collapsed dictionary the list is not as long.
- dragging over it opens the first level of all hovered tags, but not all levels
- this said the length starts to be large
- to go faster I can drag outside of the tags window to reach the last visible one, but yes, that may not be the end of the list
- when the list is expanded it starts to be boring to go back and forth.
- a "collapse all tags" is missing (Shift+left arrow ?)

The main point which comes up to my mind now is to have the ability to to go from one point to another of the list without expanding the tags, and only when I'm close to the desired place, expand them. I'll see if with modifier (Ctrl or Shift) I can control this during the dragging.

**Comment by phweyland** [comment]
Here is a proposal which seems to work.
Dragging a tag or an image over the tag names behaves as today.
Dragging a tag or an image over the selection markers (on the left of the view), doesn't expand but collapses the expanded tags.
Timeout to react set as 200ms instead of 500ms.
How does that sound ?

**Comment by LateJunction** [comment]
> selection markers (on the left of the view),

Could I be clear on where these markers are? Are you referring to what the manual names 'indicator symbols' (check mark, minus sign or none) or the symbol (triangle) between these indicator symbols and the tag name? Either way, with a long list of tags (which is my case), there is a possibility that the cursor will wander of the intended vertical path (there is not much 'play' room) and cause unintended  expansions of nested tags. Or am I just running away from shadows?

**Comment by phweyland** [comment]
over the column where the signs minus stand.
![image](https://user-images.githubusercontent.com/23012047/149181969-ef691db0-4e8c-4e5f-a7b0-be6d0c0ed26b.png)

**Comment by LateJunction** [comment]
> over the column where the signs minus stand.

OK; thanks for the clarification. Now I can comment more fully :

The 'field' in which the cursor must be placed for the current "tag name 'expand' action  while dragging" works is the whole width of the tag dictionary window - that is, the 'expand' action happens with the dragged cursor over the column of 'minuses', or the column of triangles or the column of tag name strings. You are proposing now to make this single area into 2 columnar areas with distinctly different behaviours: a narrow left hand column, covering the 'minuses' (plus some pixels) and a wider, right hand area covering the remainder of the tag dictionary window. This will need some careful description and explanation in the user manual (which, as I am sure you know, I regard as too terse anyway for somebody of limited understanding, like me). The propensity for the cursor to move out of this narrow left hand column into the wider right hand column, during the process of vertical dragging, resulting in quite different behaviour of nested tag expansion/contraction, will become frustrating if that left hand column is too narrow and/or if the cursor drag requires scrolling of the tag dictionary window. So the alignment of the current three columns will need some redesign.

On the matter of timing, yes, I suspect that a shorter time of 200 millisecs will be required to cause collapsing of a tag branch but without being too long to cause other actions. But this begs the question of what will happen if the cursor is dragged very quickly over the top of an expanded tag 'branch' - will the collapsing of that branch be ignored? And what will happen if the drag moves the cursor outside the tag dictionary window, into the image display area?

Other than these comments, this proposal seems to deliver the behaviour I would like.

**Comment by LateJunction** [comment]
> As long as I don't reproduce myself the issue, I cannot fix anything unfortunately.

I few minutes ago I had another example of the scrolling of the tag dictionary window 'freezing' while I was dragging a tag, resulting in me having to 'drop' the tag I was dragging somewhere - there was nothing else I could do. Here is what I did to create this situation:

In the data entry field, at the extreme top of the tag dictionary window, I entered the name of a new tag I wished to create and clicked 'new'. The whole of my tag dictionary was fully collapsed, with the first tag name (in the alphabetic sort sequence) aligned with the top of the tag dictionary window (immediately below the data entry line), but the last tag name positioned off the bottom of that window (because of the number of tags I have). 

It so happened that the newly created tag was placed 'off the page', towards the bottom of the list, based on its first letter, but not in the correct position within a nested tag. That tag was much further 'up' the page. I was able to scroll down and 'grab' the newly created tag with the mouse and start a vertical drag upwards towards its desired location. I overshot the target, moving the cursor over a nested tag which immediately expanded. This displayed a long list which, logically, extended off the page, at the bottom. 

At this point  I was unable to drag the newly created tag back down the page to its correct position: I reached the bottom of the tag dictionary window, but not even to the bottom of the tag list which I had unintentionally expanded; scrolling did not work. I had to 'drop' the newly created tag. 

This problem would not arise if the automatic expansion of nested tags was delayed for a sufficient time for me to correctly position the newly-dragged tag over its correct 'parent' tag, hover the cursor there for a while, until the 'parent' tag expanded (by 1 level), then drag again to the appropriate 'sub-parent' tag and hover there - and so on until I had reached the correct level where I could drop the newly created tag.

I trust you will be able to recreate this scenario.

**Comment by phweyland** [comment]
Freezing remains a bug, no doubt.

But, please try to use the right features of the module. 
There are 2 ways to create a new tag at the right place, both using the contextual menu:
- copy to entry: you select the father tag and select that option. The entry gets initialized and you just have to complete the new tag name.
- create...: you select the father tag and select that option. ...

> This problem would not arise if the automatic expansion of nested tags was delayed for a sufficient time for me to correctly position 

You cannot request to shorten the delay to scroll faster and at the same time increase the same to avoid your overshoot...
If the mouse is difficult for you to use, please avoid to use drag and drop.

This said, your critics about the slowness of dragging over long lists are valid and I hope that the PR #10874 will help keeping a short list and to navigate faster.

**Comment by LateJunction** [comment]
> But, please try to use the right features of the module.

Your guidance is really helpful; I never saw this method described anywhere else. I mostly followed what the user manual said:
![create-new-1](https://user-images.githubusercontent.com/78297934/149215285-03a969a0-2334-4e78-bfbe-4a6e7e7d5b79.JPG)

But in futre I'll follow your recommendation.

**Comment by phweyland** [comment]
I think there are other lines in the docs ... :smile:
