### ISSUE TITLE
Allow multiple tags to be applied in one action

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#10855]
**Is your feature request related to a problem? Please describe.**

Currently tags can be applied to selected image(s) one at a time only. In the circumstance where I am catching up on applying the correct tags to a large portfolio of images and with my philosophy of tagging, most of my images require tagging  and many of them require between 3 and 5 tags, making the tagging process quite repetitive and burdensome.

**Describe the solution you'd like**

Provide a 'check box' - or conceptually equivalent feature - against each tag in the dictionary that allows the ability to select (or deselect) as many tags as necessary from the dictionary and apply them all to one or more selected images in one application. Leave the 'check boxes' selected after the application in case a similar (or even identical) selection of tags is needed for the next selection of images. Maintain this state across a shutdown/startup cycle. Selecting or deselecting a 'parent' tag automatically selects or deselects all 'child' tags, but not vice-versa. Selecting a 'parent' tag should result in the hierarchy below being expanded. Deselecting should cause it to collapse. These actions are independent of the ability to expand a hierarchy in order to then right-click on a tag to attach or detach it from one or more selected images. Provide a 'button', or equivalent, to reset/deselect all the selected 'check boxes' in one hit.  

Allow the selection of tags to be saved as a 'preset'.

**Alternatives**

**Additional context**

**Comment by ptilopteri** [comment]
already possible
select tagging
select multiple images
apply tagging

please consider closing if this satisfies your request.

**Comment by LateJunction** [comment]
I don't think it is possible: I cannot select more than one tag at a time to apply - can I?

**Comment by ptilopteri** [comment]
the menu title is "tagging addon"
if that is not present, it may be an lua script that is provided

**Comment by phweyland** [comment]
The way to do that is to use presets.

**Comment by LateJunction** [comment]
> the menu title is "tagging addon"

Nope, that doesn't do what I want: that function allows me to copy multiple tags from one set of  selected images to a different set of images; some of the copied tags may not be appropriate. What I want to do is select  only appropriate tags from the dictionary and paste them  to selected images only, so that all those images will at least each have all of those tags..

**Comment by LateJunction** [comment]
> The way to do that is to use presets.

Could you explain in more detail, please ?
