### ISSUE TITLE
cropping

### ISSUE THREAD

**Issue by brucew38** [darktable-org/darktable#10860]
One should be able to set a cropping ratio: e.g., I want to use 8.5x11 paper with a margin; right now I would like a 1/4" margin, but maybe later I'd want 5/8 or 3/4. You don't want hundreds of ratios, so I should be able to set one.

**Comment by elstoc** [comment]
You can create your own custom aspect ratios. See the instructions under the _aspect_ control [here](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/crop/#crop-settings)

**Comment by brucew38** [comment]
Thank you!

**Comment by elstoc** [comment]
So this can be closed?

**Comment by elstoc** [comment]
I'm gonna assume this can be closed then.
