### ISSUE TITLE
the effect of white balance on the raw over exposed indication

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#10862]
Is it correct that white balance affects the raw over exposure indication?

How to repeat:
take any RAW;
turn on raw over exposure indication;
turn on the WB;
by changing the channel coefficients, to observe the change in the indication of underexposed/overexposed areas.

darktable version: master
OS: Debian 11 / Windows 7

**Comment by parafin** [comment]
It does, not sure if it’s “correct” or not, depends. See #6596 for details. Closing as duplicate.
