### ISSUE TITLE
JPEG XL Support

### ISSUE THREAD

**Issue by xplosionmind** [darktable-org/darktable#10866]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great and extremely useful if [JPEG XL](https://jpeg.org/jpegxl/ 'JPEG XL on jpeg.org') (jxl) could be supported by Darktable. It it the future of image formats, it has a ton of features and it appears to be extremely powerful.

**Alternatives**
Using [GIMP 2.99.8](https://www.gimp.org/news/2021/10/20/gimp-2-99-8-released/#improved-file-formats-support-jpeg-xl-psdpsb-and-more 'Release note')

**Additional context**

- [Image reference implementation](https://github.com/libjxl/libjxl 'libjxl on GitHub')

**Comment by TurboGit** [comment]
See #10044

**Comment by xplosionmind** [comment]
Oops! I only looked in the issues and not in the PRs. Thanks a lot!

**Comment by TurboGit** [comment]
Let's keep this open for others to see that an issue request for Jpeg XL has already been issued. This will be closed when the corresponding PR will be merged.

**Comment by kmilos** [comment]
Let's perhaps keep this open until read support is added? @victoryforce

**Comment by victoryforce** [comment]
> Let's perhaps keep this open until read support is added? @victoryforce

Read support is at the very top of my list. And the corresponding PR will definitely be added this week (well, provided that Ukraine will still have electrical power and Russia doesn't detonate a nuke sooner). So I don't think keeping this open would even make sense for such a short time as information for a user who might want to leave the relevant FR.

**Comment by kmilos** [comment]
Fingers crossed!
