### ISSUE TITLE
Jpg eport corruption for Markestijn 3-pass

### ISSUE THREAD

**Issue by gerben61** [darktable-org/darktable#10869]
Tried several exports on my RAW files from my X-T2 and X-E3 and only Markestijn 3-pass seems to corrupt the exported Jpg.
Settings are: Jpeg 8-bit, quality 90, size 2000 width. dt 3.8.0.

**Comment by jenshannoschwalm** [comment]
We certainly need all the information you were asked for in the issue template. Computer system, graphics card, ram ... All that stuff is required to track such an issue. Please report!

**Comment by gerben61** [comment]
My excuses. New here. darktable not crashing just jpg not displaying properly. But Switching off OpenCL fixes this issue.

1. On Windows 10. no backtrace
2. Windows 10, version 21H1 (OS Build 19043.1415).
3. i5 4690K, gigabyte Z97P-D3, 24Gb RAM,
4. Switching off OpenCL fixes this issue.
5. Exporting

A few more pointers where to find stuff on Windows would help. Cheers, Gerben

**Comment by jenshannoschwalm** [comment]
And the graphics driver and architecture please 😀

**Comment by jenshannoschwalm** [comment]
To reproduce maybe also the raw and xmp file.

**Comment by TurboGit** [comment]
> 4\. Switching off OpenCL fixes this issue.

Ok, Windows + Intel driver I suppose which is an infamous combo to make everything crash.

**Comment by gerben61** [comment]
Radeon HD6950, installed AMD drivers. Same thing. Issue only when OpenCL is on.
![2022-01-12 17_38_01-Window](https://user-images.githubusercontent.com/10281079/149192728-d3903740-8c95-4238-9b6c-9b6ea31b9669.jpg)
Tried several RAW files with the same results. Here's one attached
![DSCF1852-2000_05](https://user-images.githubusercontent.com/10281079/149193010-f8dcfe6b-fc94-450f-aa52-1828cf49f685.jpg)
Let me know if you need more info.

**Comment by TurboGit** [comment]
With AMD driver we had some reports about issues but not that bad ! Is that triggered by a specific module or whatever is used you get the same problem?

**Comment by jenshannoschwalm** [comment]
@gerben61
1. do i understand this correctly; the issue you are descibing happens with **and** without the AMD graphics card installed if you enable OpenCL?
2. Please make the raw file plus xmp file for that image available.

**Comment by gerben61** [comment]
It happened before and after I installed the AMD driver. In both cases the issue is solved when I disable OpenCL. Removed existing sidecar files and re-created. See attached RAW and XMP
[2021-04-16 - Beamish X-E3 Iena.zip](https://github.com/darktable-org/darktable/files/7863100/2021-04-16.-.Beamish.X-E3.Iena.zip)
.

**Comment by jenshannoschwalm** [comment]
Ok, can reproduce with error message "tiling failed for module finalscale" on current master, fedora linux and nvidia opencl.

BUT: The crash happens with all demosaicers, also if all possible modules disabled.

Switch off "allow upscaling" seems to fix the issue.

**Comment by gerben61** [comment]
For me "allow upscaling" set to yes fixed the issue. Odd.

**Comment by jenshannoschwalm** [comment]
Due to a stupid error on my side - i used set-size-by-scale - i had dt crashing, after doing a fix for that problem i can't reproduce at all. So let's try on your problem again :-)

**Comment by piratenpanda** [comment]
No issues on Arch, AMD Polaris and OpenCL on. Might be Windows plus old driver.

**Comment by jenshannoschwalm** [comment]
Could you run darktable -d all and post the logfile?

**Comment by gerben61** [comment]
Sure. Here it is
[darktable-log.txt](https://github.com/darktable-org/darktable/files/7896372/darktable-log.txt)
.

**Comment by jenshannoschwalm** [comment]
@gerben61 i have an idea for the issue, are you able to compile darktable yourself?

**Comment by jenshannoschwalm** [comment]
@piratenpanda could you please check again with --enforce-tiling ?

**Comment by piratenpanda** [comment]
Should there be something in the terminal when running it with that?

**Comment by jenshannoschwalm** [comment]
Maybe debug options for open CL and params.
I suspect the orientation module so tiling info for that would be interesting.

Just trying if you get garbled output if you AMD card has problem if forced to tile as was reported...

**Comment by piratenpanda** [comment]
No chance to produce anything as OP reported

**Comment by jenshannoschwalm** [comment]
@gerben61 today there has been a fix for xtrans sensors doing tiling. It could be your issue is related. Could you do me a favour a re-test the issue?

please use -d tiling -d opencl as command line options...
