### ISSUE TITLE
Some Kodak DCR files fail loading in 3.8 on Ubuntu 20.04

### ISSUE THREAD

**Issue by pchambre** [darktable-org/darktable#10865]
When editing files from my Kodak SLR/n, I have found that there are occasional files that fail to load. The attached images are very similar, taken within minutes of each other, of the same scene, with the same lens. GD6J6997.DCR loads fine, but GD6J6998.DCR shows the 8-bit skull graphic. Both files load fine with Lightroom 6 and also with RawTherapee.

Besides not loading, neither file shows the correct ISO in preview hover (they both show 0 ISO, while the other tools show 160). Also, when you open one of the files that could be previewed, darktable warns that it was unable to read the camera's white balance.

These files were created with the latest Alexey Danilchenko (5.4.10) firmware. However, I also have some DCRs created using the last Kodak official firmware, and those show the same behavior regarding 0 ISO and can't read white balance.

Please let me know if there's anything else that I could provide that would be helpful in addressing this issue.

Thanks,
Paul

For some reason, github says " is not included in the list" when I try to attach a zip. So, instead, here's a Drive link to the files mentioned: https://drive.google.com/drive/folders/1pv5XTp05GAK9BIlecXes0_fWBTJAI0th?usp=sharing

Edit/update: I am seeing the same behavior with Kodak DCR files from my DCS760 as well, so this really looks like something not quite right in darktable's DCR support. I am adding one good and one bad DCS760 file to the Drive folder as well (8P7X0278.DCR = good, 8P7X0279.DCR = bad).

**Comment by Alexey-Danilchenko** [comment]
RAWSpeed should really use the copy of LibRaw/dcraw decoder for Kodak files - that was tested over the years and works on all those files just fine. The differences in above samples are all in raw encoded data so something is not right in RAWSpeed DcrDecoder class

**Comment by pchambre** [comment]
One other point that's mostly relevant to this ticket: Kodak had two variants of their last-generation 14MP full frame DSLR - the SLR/n and the SLR/c. These used the same sensor and electronics, but the SLR/n was based on a Nikon F80 body, using Nikon F mount, while the SLR/c was based on a Sigma SA9 and used Canon EF mount. 

Net net is that RAW files from the two cameras are the same except for metadata stating SLR/n or SLR/c.

I don't have an SLR/c, but there are reports that none of the SLR/c raws can be opened in darktable, even though most of the SLR/n files can be.

**Comment by PeterWem** [comment]
Do you have a raw sample from SLR/c?

**Comment by pchambre** [comment]
I do not.

The OP from this thread should:
https://www.dpreview.com/forums/thread/4612124

Cheers,
Paul

**Comment by PeterWem** [comment]
I see.

**Comment by kansalliskala** [comment]
here is one
https://www.dropbox.com/s/s5rh6yah53p0v9b/F3G93631.DCR?dl=0
I am amazed that dropbox can show preview

**Comment by PeterWem** [comment]
> here is one https://www.dropbox.com/s/s5rh6yah53p0v9b/F3G93631.DCR?dl=0 I am amazed that dropbox can show preview

![Skärmbild från 2022-01-28 20-10-27](https://user-images.githubusercontent.com/34200649/151607385-5d4ee56a-09de-445f-9daf-7db502fd8883.png)
I copied from SLR/n to SLR/c. I suggest you upload the raw file at https://raw.pixls.us and after that start a new issue here about camera support for SLR/c. I am just a darktable user and not developer.

**Comment by kansalliskala** [comment]
I do not even use Darktable, someone just asked for a file :-)

 TP Aaltonen
 
-----Original Message-----

**Comment by PeterWem** [comment]
No need to, but uploading a raw sample to raw.pixls.us is not only for the sake of darktable.

**Comment by kansalliskala** [comment]
feel free to upload it theremy original post was how to use photodesk on wine
TP Aaltonen
 
 
 
-----Original Message-----

**Comment by PeterWem** [comment]
Thanks
You know it will be a CC0 license for that raw file? https://creativecommons.org/share-your-work/public-domain/cc0/

**Comment by kmilos** [comment]
Which why the owner of the image should really be doing the upload and accepting the relinqunshing of the copyright.

**Comment by kansalliskala** [comment]
ok, I uploaded itit was easier than I thought
have a nice Sunday allTPA
 
 
 
-----Original Message-----
