### ISSUE TITLE
Problems by loading NEF RAW from Nikon Z-fc

### ISSUE THREAD

**Issue by laborfuzi** [darktable-org/darktable#10868]
Wenn ich das NEF RAW Bild zu Bearbeitung öffnen will bekomme ich den Hinweis, dass das Kameramodell nicht unterstützt wird.
If I tried to open the NEF-RAW picture I got the hint that this camera model (NIKON Z fc) is not supported.

**Comment by kmilos** [comment]
I think maybe not all NEF modes might be supported... Did you try uncompressed?

**Comment by laborfuzi** [comment]
Des tue Files Wege Not compressed.

Miloš Komarčević ***@***.***> schrieb am Mi., 12. Jan. 2022,
11:55:

**Comment by kmilos** [comment]
Sorry, my first reply was too quick, and maybe not the part of the problem.

Please provide the information requested.

**Comment by laborfuzi** [comment]
Sorry! The auto correction was switched to German. So it changed my message
in a way that the text became nonsense. I wrote that the files were not
compressed.

Miloš Komarčević ***@***.***> schrieb am Mi., 12. Jan. 2022,
14:27:

**Comment by kmilos** [comment]
I got that...

Still, I have updated my response above, and will ask you to supply the information in the issue template one last time.
