### ISSUE TITLE
Reference image (dust)

### ISSUE THREAD

**Issue by outdoorbits** [darktable-org/darktable#10864]
**Is your feature request related to a problem? Please describe.**
Dust on the sensor can be hard work to remove on images.

**Describe the solution you'd like**
Nikon-cameras like my Z6 can take a "Reference image (dust)" to calculate dust out of images. But this needs Nikons software Capture NX-D. Is it thinkable to integrate such a function into darktable?

... and thank you for darktable 3.8, it's great!

**Comment by MStraeten** [comment]
if you provide the algorithm it’s thinkable ;)

**Comment by maxammann** [comment]
Is there public/reverse-engineered documentation about the NDF data format?
