### ISSUE TITLE
darktable 3.8.0 no longer recognizes embedded color matrix for DNGs produced by Kalpanika X3F -> DNG converter

### ISSUE THREAD

**Issue by geni1105** [darktable-org/darktable#10873]
**Describe the bug/issue**

darktable 3.8.0 reports a missing color matrix in DNGs produced from Sigma X3F raw files by the X3F Tools (Kalpanika).
With 3.6.1, such DNGs could still be opened and processed with reasonable colors.

**To Reproduce**

Convert a Sigma X3F to DNG with x3f_extract (Kalpanika, https://github.com/Kalpanika/x3f/releases).
Import and open resulting DNG in darktable. Error message notifies about missing color matrix, colors are way off.

**Expected behavior**

No error message, reasonable colors.

**Platform**

* darktable version : 3.8.0
* OS                : OSX 11.6.2 Big Sur 
* OpenCL installed  :  y
* OpenCL activated  : y

**Additional context**
The color matrices are actually present in the DNG (Color Matrix 1, Forward Matrix 1, Camera Calibration 1) but the Calibration Illuminant 1 is set to 0 (Unknown). If the Calibration Illuminant is set to e.g. D55 using exiftool, the file can be opened without error message and with usuable colors.
See screenshot of darktable thumbnails below (left: DNG with CalibrationIlluminant1 = unknown, right: set to D55 using exiftool)

![grafik](https://user-images.githubusercontent.com/25555406/149200976-2dde4735-6c80-48d8-abdc-31085259f458.png)

**Comment by kmilos** [comment]
FWIW, I _think_ from the Kalpanika code that the ColorMatrix1 is for D65...
