### ISSUE TITLE
Style on export does not work as expected

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#10875]
I created a style with only sharpen module included which I want to use for exporting.

But when I select this style in the export-dialog the resulting image looks completely different compared to the image which is created w/o this style.

screenshots:

![Bild1](https://user-images.githubusercontent.com/57685590/149222119-72f07b1c-6dfd-4278-895b-22fa0e110894.jpg)

![Bild2](https://user-images.githubusercontent.com/57685590/149222136-68921bc0-29a4-420d-8515-21eb48ccc84a.jpg)

![Bild3](https://user-images.githubusercontent.com/57685590/149222153-b2d67149-ee7a-4bad-8890-87df970399ee.jpg)

In this example the framing and watermark edits are lost. Left pic = no export style, right pic = export style used.

**Comment by TurboGit** [comment]
Expected since you are using the "replace history" instead of "append".
