### ISSUE TITLE
Putting style name in the queue

### ISSUE THREAD

**Issue by RobyClick66** [darktable-org/darktable#10883]
When I apply a style to my photo, I don't remeber which of theme I have choose! (poor brain memory ;-))

Insert a line in the queue (pixelpipe - coda di sviluppo) with e.g. "*** Style name - start" and a line at the end e.g. "*** Style name - end", so I know which style I have applyed and if I want it switch off I know which actions select whitout damage other actions in queue. In this way if more styles are applied, one after one, their actions are simply to identify and remove/disable.

Take me a block-notes!

Thanks for help and forgive my poor english and my poor knowledge of DT (I'm a newbie)

![Coda](https://user-images.githubusercontent.com/97698387/149396392-75e77e4e-37c6-4cc2-8e05-5ad051fd8ec7.png)

**Comment by MStraeten** [comment]
you can rename the instances of a module so you can identify them in the history stack and also in the module stack in right panel.

**Comment by RobyClick66** [comment]
Thanks for the ready replay.
I'll try asap.

Have a nice day!

Il giorno ven 14 gen 2022 alle ore 07:27 Martin Straeten <
***@***.***> ha scritto:
