### ISSUE TITLE
Rotate and perspective doesn't mantaining aspect ration from quick access panel

### ISSUE THREAD

**Issue by zamorim-br** [darktable-org/darktable#10890]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
When rotating an image from rotate and perspective module added at quick access panel, the image aspect ratio was not mantained, even with automatic cropping seted as original format. 

The same operation done with full rotate and perspective module opened works fine.

**To Reproduce**
1. Add to quick access panel rotate and perspective/on-off, rotate and perspective/rotation, rotate and perspective/automatic cropping
2. Open an image on darkroom
3. Select original format on automatic cropping setting
4. Change rotation slider to extrems
5. Observe that original aspect ratio was not mantained

**Expected behavior**
The original image aspect ratio need to be mantained.

**Platform**
* darktable 3.8.0
* OS : Linux - kernel 5.4.0-94-generic
* Linux - Distro : e.g. Ubuntu 20.04.3
* Memory : 24Gb
* Graphics card : NVIDIA GeForce GTX 1650
* Graphics driver : 
* OpenCL installed : yes
* OpenCL activated  : yes
* Xorg : 2:1.20.13-1ubuntu1~20.04.2
* Desktop : gnome
* GTK+ : unknown
* gcc : n/a 
* cflags : n/a
* CMAKE_BUILD_TYPE : n/a

Darktable installed from http://ppa.launchpad.net/ubuntuhandbook1/darktable/ubuntu

**Additional context**
The same behavior happens with JPEG or RAW images and even with cleared history.

**yes/no**
- Do you use lua scripts? no
- What lua scripts start automatically? n/a
- What lua scripts were running when the bug occurred? n/a

**Comment by elstoc** [comment]
I can't reproduce this on current master or the 3.8.x branch. I've tested "original", "largest area", and "off" and all look fine.
