### ISSUE TITLE
Preview window artefacts due to low quality resampling

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#10899]
**Is your feature request related to a problem? Please describe.**
darkroom processing is done at lower quality (matching what is done when image is exported with _high quality resampling: no_). I understand this is done to make the editor more responsive; however, this can introduce artefacts that will not be present in the final output.

Performance/scaling related config:
prefer performance over quality: unchecked (default)
demosaicing for zoomed out darkroom mode: full (possibly slow)
reduce resolution of preview image: original
pixel interpolator (warp): bicubic (default)
pixel interpolator (scaling): lanczos3 (default)

**Describe the solution you'd like**
I'd like to be able to get a realistic preview that matches the output. I would like an option to enable 'high-quality preview' permanently, or a button in the darkroom to force one-time generation of a high-quality preview so I can make sure there will be no artefacts in the output.

**Alternatives**
It is possible to export the current image from the darkroom and inspect it in another software, e.g. an image viewer.

**Additional context**
Please see https://discuss.pixls.us/t/darktable-zoom-artefacts-in-darkroom/28897 for an example. I think #8016 is related.

**Comment by elstoc** [comment]
wouldn't that mean that, when you're viewing the entire image in zoomed-out mode, you're basically running an export-quality pixelpipe each time you change a parameter and then downscaling it to your screen pixels? Sounds sloooow.

**Comment by kofa73** [comment]
I thought modules' outputs were cached, so it wouldn't be a full run. But you're right, it could be slow. I can always zoom in to 100% to check this particular issue.
Maybe what should be done instead is to always use bilinear or at most bicubic for the zoomed-out preview (as they are less prone to artefacts with the preview pipeline), and use _pixel interpolator (scaling)_ for export only.

**Comment by elstoc** [comment]
> I can always zoom in to 100% to check this particular issue.

That's what I do
