### ISSUE TITLE
Crashes 3.8 Windows 10

### ISSUE THREAD

**Issue by jeff-intrinsica** [darktable-org/darktable#10903]
Hi, I've had two crashes  recently with 3.8 on Windows 10. The most recent occurred when I was adding a Gradient to the exposure module (darktable_bt_5YF5F1.txt), this looks like a null pointer or similar.
I can't remember what causes the first (sorry), but it happened during general editing.

[darktable_bt_5YF5F1.txt](https://github.com/darktable-org/darktable/files/7881140/darktable_bt_5YF5F1.txt)
[darktable_bt_YNL7F1.txt](https://github.com/darktable-org/darktable/files/7881141/darktable_bt_YNL7F1.txt)

Sorry I can't be more precise, keep up the good work
Jeff

**Comment by johnny-bit** [comment]
The darktable_bt_5YF5F1.txt has some good info. The 2nd one is weird...

**Comment by dterrahe** [comment]
It would be good to have a git bisect for one of these. Quite a few crashes showing dt_gui_quit_callback.

**Comment by johnny-bit** [comment]
Yeah. Another one is in #10902 

Can we here focus on reading from null in dt_lightroom_import which is somehow callwed from dt_masks_events_button_pressed (darktable_bt_5YF5F1.txt) and have dt_gui_quit_callback dealth with in say #10902  or other which mentions "random crash"?
