### ISSUE TITLE
Unhandled Exception: recreatable after a new instance of "diffuse and sharpen" with drawn mask

### ISSUE THREAD

**Issue by ahmun824** [darktable-org/darktable#10902]
[darktable_bt_4OJHG1.txt](https://github.com/darktable-org/darktable/files/7880935/darktable_bt_4OJHG1.txt)
[darktable_bt_94Z6F1.txt](https://github.com/darktable-org/darktable/files/7880936/darktable_bt_94Z6F1.txt)
[darktable_bt_2CN9F1.txt](https://github.com/darktable-org/darktable/files/7880937/darktable_bt_2CN9F1.txt)

The same issue has happened before and now three times in an hour.
Workflow immediately before this issue:
1. editted one photo with diffuse and sharpen (no new instance)
2. copy and pasted the entire history stack to another selection of photo
3. open first photo and create new instance of diffuse and sharpen with drawn mask (to soften face)
4. when finished and quit darkroom and return to lightroom or switch to another photo, unhandled error and the application quit upon pressing OK.
5. return to darktable and the full edit is there
6. edit the next photo and do the same as step 3
7. same thing happens as step 4.

**Comment by ptilopteri** [comment]
seems you have neglected to provide the information requested on the 
initial screen.  please do so so the developers have information necessary
to trouble shoot the problem you describe, else they use valuable time 
eliciting already requested information you decided not to provide.

it is necessary.
