### ISSUE TITLE
Automatic Orientation - Failing on Vertical Orientation

### ISSUE THREAD

**Issue by jaystile** [darktable-org/darktable#10906]
**Did you buy darktable from an application store ?** No.

**Describe the bug/issue**
In previous shoots the orientation was captured fine in my Sony Alpha 7 - IV when I imported the files into lighttable. Something changed, but I'm not sure what. On my last import, the orientation is incorrect for pictures taken in a vertical orientation. [I posted on reddit if you would like to see how an image was imported.](https://www.reddit.com/r/DarkTable/comments/s6i0a0/help_vertical_oriented_images_not_displaying/)

When I compared the EXIF tags there does seems to be some difference:
*Successful vertical EXIF tags: `0..l...ap....j`
*Failed vertical EXIF tags `0....h.ap....h`

Any thoughts on what I may have changed in darktable or in my Camera would be appreciated.

exiftool reported that the Rotation is 270 degrees. In Camera the rotation displays correct in the preview

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Download the sample RAW HEIF file: https://drive.google.com/file/d/1Cogyq_8X1nWrN0WONO5W47At4aW29OJs/view?usp=sharing
2. Go to import => add to library
3. View the bad orientation in lighttable

**Interesting**
* Enabling the preview 'eyeball' before import displays the correct orientation.
* Installed darktable into my Ubuntu 20 VM and experienced the same result with the incorrect orientation and replication of another chunk of the image.

**Expected behavior**
Expected the image to be vertically oriented and not horizontally oriented with duplicated sections.

**Screenshots**
https://www.reddit.com/r/DarkTable/comments/s6i0a0/help_vertical_oriented_images_not_displaying/

**Which commit introduced the error**
UNKNOWN

**Platform**
* darktable version: 3.8.0
* Operating system and its version: Windows 10, build 1305

 - Can you reproduce with another darktable version(s)? UNKNOWN
 - Can you reproduce with a RAW or Jpeg or both? RAW
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? No.

**Comment by jaystile** [comment]
I was analyzing the EXIF data with exiftools. I noticed a couple of interesting things. The EXIF data in one of my files had these tags: `Camera Orientation 270 CS`, `Rotation 90`. These appear to be Sony specific tags.

| Name | Type| Description |
| --- | --- | --- |
|CameraOrientation | int8u | [val >> 4 & 0x3]   0 = Horizontal (normal)   1 = Rotate 90 CW   2 = Rotate 270 CW   3 = Rotate 180|
|Rotation | int16u | 0 = Horizontal (normal)   1 = Rotate 90 CW   2 = Rotate 270 CW|

**Comment by jaystile** [comment]
# Workaround
Using [exiftool](https://github.com/exiftool/exiftool) modify the EXIFDATA. This removes the rotation and then darktable 'orientation' module can be used to properly orient it.
```
/exiftool -QuickTime:Rotation=0 DSC00367.HIF
```

**Comment by ptilopteri** [comment]
but now your raw images have been changed and may
become corrupted.

better a script or another solution which does not change your
raw images.

**Comment by RomainQuidet** [comment]
Same issue here with my iphone HEIC images! All imported vertical images in DT 3.8 are incorrectly oriented with tag 1....h.ap....h.
Never used DT before so I don't know which commit did introduce this bug. If I deactivate the orientation module in edit view, the orientation come back to the correct one...

**Comment by jaystile** [comment]
Bump. Still an issue for me.

**Comment by benjcmin** [comment]
Still an issue with HEIC images in DT4 , so guess this is still open. (same photos show correct orrientation in e.g. digikam)

**Comment by tussock** [comment]
This is still an issue. All vertical photos are wrong.

**Comment by victoryforce** [comment]
> This is still an issue. All vertical HEIC photos are wrong in DT4, when imported from an iPhone.

@tussock @benjcmin 
Recently, changes were made to the handling of orientation in HEIF images. I would appreciate it if you could check if the current dt build has fixed your problem.

**Comment by jaystile** [comment]
@victoryforce , I ran through my original test images with Darktable version 4.2.0 and it worked! The images are not auto rotated by default (which is just fine by me). If @tussock or @benjcmin give the thumbs up, I'll close out the ticket. Thank you!

**Comment by Nilvus** [comment]
Better to close that now (we could have feedback or not by them). @tussock or @benjcmin: this should work now with 4.2.0. If not, ping me to reopen it.
