### ISSUE TITLE
Rotate and perpective module: ctl-z should better undo image alignement without removing the lines

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10905]
- actvate the rotate and perspective module
- click on the button on the right that detects the lines
- apply the transform according to horizontal or vertical or both perspectives -> you get the image transformed
- you are not satisfied, you issue ctl-z -> the image get untransformed and the lines desappear

I think that it would be better that ctl-z only untransform the image, without making the lines desappear. Another ctl-z could make the lines desappear.

Why am I suggesting this? because if the user works with the lines, unactivating some of them, or possibly unactvating all of them and reactivating only some of them, a big amount of work is lost

**Comment by elstoc** [comment]
I've tried this and I can't see anything being lost. All ctrl+z does is revert the correction and deselect the lines button. You can press the lines button to show the previously-drawn lines again.

**Comment by paolobenve** [comment]
It's not as simpe as you say:

- activate the module
- press the lines button -> all the lines are show
- manually deselect some line
- ctl-z -> the module keeps activated, the lines desappear
- press the lines button
- "data pending - please repeat" #10904
- press again -> nothing happens
- press again -> all the lines are show

or:

- activate the module
- press the lines button -> all the lines are show
- manually deselect some line
- ctl-z -> the module keeps activated, the lines desappear
- activate another module
- go back to rotate and perspective
- press the lines button
- "data pending - please repeat" #10904
- press again -> nothing happens
- press again -> all the lines are show

Trying to avoid #10904:
- activate the module
- press the lines button -> all the lines are show
- manually deselect some line
- ctl-z -> the module keeps activated, the lines desappear
- move to another image
- go back to the previous one
- press the lines button -> all the lines are show
