### ISSUE TITLE
DT 3.8 Print Module (on a Mac)

### ISSUE THREAD

**Issue by loriscr** [darktable-org/darktable#10917]
On DT 3.8, I cannot use the printing module, which worked flawlessly in 3.6. The image seems to upload (the image information is available) but on the central panel there is a grey square whose size changes according to the chosen size of the paper. Is anybody experiencing a similar problem?
Thank you very much for any comments/suggestions

**Comment by TurboGit** [comment]
Have you tried to drag&drop an image from the filmstrip to the gray square?

**Comment by loriscr** [comment]
Hi Pascal,
Thank you for the suggestion, 
but unfortunately (the upgrades in 3.8 are important) it does not work.

Loris

**Comment by loriscr** [comment]
Any other suggestions how to possibly solve the problem?

Thank you in advance!

**Comment by TurboGit** [comment]
No, seems like MacOS related as we have not seen other reports about this. Sorry, but I'm not a MacOS users & dev at all and we really miss devs this platforms so it may take some times to fix.

**Comment by loriscr** [comment]
Thank you for your attention anyhow
Loris

**Comment by ralfbrown** [comment]
There hasn't been any further activity on this issue in nearly two years (four feature releases), so I'll close it.  If this is still an issue, feel free to re-open or open a new issue.
