### ISSUE TITLE
rotate and perspective doesn't delete the last structure line

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#10916]
In "rotate and perspective" it is not possible to delete all the manually drawn structure lines.
To reproduce:
- open an image in darkroom
- select the "pencil" tab in "rotate and perspective"
- draw few lines
- remove **all** the lines with right-click
- select the "square" tab
- select again the "pencil" tab: the last deleted line magically reappears.

dt: 3.9.0~git133.81ed3a94ad
os: openSUSE tumbleweed

**Comment by TurboGit** [comment]
Should be fixed in master.

**Comment by TurboGit** [comment]
Corresponding fix merged in master and darktable-3.8.x branch.
