### ISSUE TITLE
documentation: contradictory advice in diffuse or sharpen module

### ISSUE THREAD

**Issue by mbaz** [darktable-org/darktable#10915]
The diffuse or sharpen module docs (https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/diffuse/) has the following advice in different paragraphs:

* Introduction: undo effect of anti-alias filter with a preset and placing the module before input color profile.
* General advice: D&S should come after chromatic aberration, noise correction, black level correction and color calibration.
* Using multiple instances for image reconstruction: suggest an order placing sensor and demosaic correction at the end.

I suggest placing all discussion about module ordering in a single section, suggesting a single ordering, and maybe discussing when and why to deviate from it.

References: https://discuss.pixls.us/t/recover-ooc-jpeg-detail-sharpness-from-raw-with-darktable/28911/56

**Comment by elstoc** [comment]
User manual issues/suggestions should be raised in the [dtdocs](https://github.com/darktable-org/dtdocs) repo

**Comment by mbaz** [comment]
Thanks, and sorry for the misfiling.
