### ISSUE TITLE
dt 3.8.0 produces banding in dark areas when export in PNG.

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#10919]
dt spoils gradients in dark areas when exporting in PNG: 16-bit PNG output looks worse than JPEG on higher qualities, producing severe banding and color blotches.
The complete story is [here](https://discuss.pixls.us/t/solved-cant-get-smooth-gradients-in-blacks/28957). The illustration is in the first post, RAW file to play can be found in post 10 The bottomline is in post 12. Long story short, it eventually appeared to be a combination of two issues: flawed input profile that provoked the banding somehow and broken png export. Changing input profile got me clean JPEG output and still flawed PNGs. Maybe it's a bug in a library, because I got similar results in RT, GIMP and Krita trying to get smooth look in the final image assuming that 16-bit output must give me smoother output than 8-bit.

**To Reproduce**
1. Edit file with smooth gradients in dark areas. Retouch with blending tool will do. The original image still has some texture in the dark areas, which seemingly prevents png export from failing. Smoothing the area provokes the artifacts.
2. Export in png.
4. See banding and color blotches instead of smooth transitions.

**Platform**
* darktable version : 3.8.0
* OS                :  Linux - kernel 5.11.0-pf8
* Linux - Distro    : Gentoo
* OpenCL activated  :  The same with OpenCL on/off

**Comment by kanyck** [comment]
Can't upload PEF here... Please see post 22 for the original, XMP and resulted images. Sorry for the inconvenience.

**Comment by ptilopteri** [comment]
change the extension or better add ".txt"
as:    imageXX.PEF.txt

**Comment by kmilos** [comment]
Copying my comment from the forum here:

> I have exported some random raw file from dt 3.9 to 16-bit PNG and verified the histogram: there are no gaps in the values (i.e. all bits seem to be used), so I _think_ the export operation is correct.
> 
> One thing to note here: most viewers will just chop off the lower bits for 16-bit inputs and keep the 8 most significant bits only (i.e. not go through conversion to float, nor dither/round), so maybe that’s what you’re seeing here? Is the banding there if you import back into dt?

**Comment by kanyck** [comment]
Now I'm quite sure it was a false alarm: it's viewers who lie to me when opening PNGs. 
Closing, please tag this issue _invalid_. Sorry about that.
