### ISSUE TITLE
Nikon D3S

### ISSUE THREAD

**Issue by dweebler999** [darktable-org/darktable#10920]
Hi, turns out the D3s needs samples to work in 3.8, at any rate that is the explanation I was given, just workign my way through uploading the set at pixls.us

Can you let me know if that has given you enough to fix the problem and I can try re-installing 3.8?

**Comment by dweebler999** [comment]
Should be all with you, let me know if you need any more.

**Comment by PeterWem** [comment]
Now when you have uploaded raw samples you can either wait for 3.8.1 or open the file cameras.xml and remove  **supported="no-samples"** from D3s.

**Comment by mir07** [comment]
Hi @dweebler999,
I have today uploaded the full set (14bit compressed, 14bit compressed-lossy, 14bit uncompressed, 12bit compressed, 12bit compressed-lossy, 12bit uncompressed) so all required format is there. I am also able to work in DT with my images and removing the 'supported="no-samples"' from every instance of D3s elements in darktable/share/darktable/rawspeed/cameras.xml gets rid of the warnings in DT.

**Comment by dweebler999** [comment]
You are a superstar. Thanks very much indeed.

**Comment by tomascapek** [comment]
What is status on this please? 

In any case, I just uploaded my sample pictures, which features standard calibration table! Hope this helps.
