### ISSUE TITLE
can't select areas in color picker

### ISSUE THREAD

**Issue by tpapp** [darktable-org/darktable#10929]
**Describe the bug/issue**

Can't select areas in the color picker (with eg <kbd>Ctrl-click</kbd>). Spot selection works fine.

**To Reproduce**

1. activate the color picker module.
2. click on the picker symbol.
3. hold down <kbd>Ctrl</kbd> and try to select an area with the left mouse button.
4. Problem: still spot selection.

**Expected behavior**

Rectangle selection.

**Which commit introduced the error**

I tried to bisect going back to 3.4.1.1 but still get this, which is puzzling. Maybe some interference from the WM? If I could get help to display what Darktable perceives as clicks and kbd presses I would be happy to recompile with that.

(I of course tried with a fresh config, suspecting it was some shortcut change).

**Platform**

* darktable version : e.g. `3.8.0~git59.e758e1366c-1` from the official binary PPA, `master` (`8e94cae089`)
* OS                : `Linux 5.13.0-25-generic #26-Ubuntu SMP `
* Linux - Distro    : Ubuntu 21.10
* Memory            : 16GB
* Graphics card     : Intel Corporation UHD Graphics 620 (rev 07)
* Graphics driver   : xserver-xorg-video-intel
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 1:7.7+22ubuntu2
* Desktop           : XFCE
* GTK+              : 
* gcc               : gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
* cflags, CMAKE_BUILD_TYPE  : just ./build.sh

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? yes, going back to 3.4.1.1 and 3.6
 - Can you reproduce with a RAW or Jpeg or both? both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) NA
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? no
   - What lua scripts start automatically? no
   - What lua scripts were running when the bug occurred? NA

**Comment by TurboGit** [comment]
You need to `ctrl+click` on the picker icon.
