### ISSUE TITLE
retouch: issue selecting shape after exiting continuous creation

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10927]
When using the retouch module it is possible to place a circle shape by clicking the canvas (to define the target shape) and then dragging (to position the source shape). When doing this using continuous shape creation (ctrl+click on the circle icon) I can place a number of source/target shapes without issue. When I exit creation mode (by right-clicking), if my mouse is still hovering over a shape, I cannot click the shape to move it - instead (if I am zoomed) click+drag pans the zoomed area:

https://user-images.githubusercontent.com/9555491/150234247-5530a4ab-19e8-4370-9d37-2e9f7bbc462a.mp4

Tested on 3.8.0+109~g85592cd37 but issue also known to appear on latest master.

**Comment by TurboGit** [comment]
Yes, basically the same issue than #10923. That is when you leave the continuous creation there is no shape selected so we end up with pan&zoom. If you move the mouse a bit, the selection will happen and the source shape will be moved properly. In #10923 it was easy to fix by ensuring that the source-mode selection was set as the last form was still active. With continuous that's not possible to use the same trick as at the time we leave the continuous mode (right-click) there is no more selected form as we are ready to create a new one. As I said really not easy in this case...
