### ISSUE TITLE
lighttable: metadata editor fails to refresh

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#10925]
**Did you buy darktable from an application store ?**
no, self-compiled

**Describe the bug/issue**
When using keyboard shortcuts Alt-{arrow} to move to another image while one of the text fields in Metadata Editor has keyboard focus, the M.E. fails to update its display.  The display is correctly updated if the focus is elsewhere, e.g. in the text box for Tagging.

**To Reproduce**
1. Start dt with a fresh config dir and import a folder with enough images to show multiple rows of thumbnails in lighttable.
2. Click on an image to select, then open Metadata Editor and enter a unique value for "title"; press Enter or click Apply to store.
3. Click in the "title" text box to give it keyboard focus
4. Press Alt-Right or Alt-Down to move the "hovered" image
5. Observe that the display remains unchanged
6. Mouse over an image to move the "hover" indicator
7. Observe that the display updates
8. Click on the original image to re-select it
9. Press Alt-Right or Alt-Down and observe that Metadata Editor updates now that its text field no longer has keyboard focus
10. Click on the original image again
11. Open Tagging and click in its text box to give it focus
12. Add a unique tag to the image
13. Press Alt-Right or Alt-Down to move the "hovered" image
14. Observe that both Tagging and Metadata Editor update

**Expected behavior**
The fields in the metadata editor should refresh to show the values for the newly-activated image, just as they do when moving the mouse pointer to another image or when changing images with keyboard focus somewhere else.

**Which commit introduced the error**
This has been around at least since InputNG was merged last summer, although I don't think Alt-{arrow} was active by default at the time -- I remember specifically defining those shortcuts to test a mouse-free metadata editing workflow.

**Platform**
* darktable version : 3.9.0+4\~gc367c24b5 and current master (3.9.0+136\~g6e3023383)
* OS                : Linux - kernel 5.10.45
* Linux - Distro    : Mageia 8
* Memory            : 64GB
* Window Manager: KDE
* OpenCL installed  : no
* OpenCL activated  : no
* gcc               :  10.3.0
* CMAKE_BUILD_TYPE  : Release

**Additional context**
 - Do you use lua scripts?  no

**Comment by phweyland** [comment]
If I understand properly the case this is normal.

For metadata, you start to edit a field, but the the content is not yet saved. The module knows that and it tries to avoid you to loose your data.
However, when the value is saved, hovering other images update the metadata fields.
For tagging, the entry is mainly a filter and doesn't show any images' tags. Then for that field there is no 'edition' protection.

**Comment by ralfbrown** [comment]
But that leaves us with no possibility of mouseless entry of distinct metadata for multiple images - at a minimum, you need to  move the mouse, click "apply" and then move the mouse again to click into a text box after using a shortcut to activate another image.  (Moving the mouse all the way over to the next image and back is even slower.)  I just tried assigning Alt-Return to the "apply" button but that doesn't work either.

I guess we need a flag for whether the user has changed anything in any of the text boxes, which gets reset on Enter or clicking "apply".

**Comment by phweyland** [comment]
> I guess we need a flag for whether the user has changed anything in any of the text boxes, which gets reset on Enter or clicking "apply"

This what happens. Having done that, the mouse movements update the fields with hovered images but not the keys Alt-arrows ... The key-pressed may disturb the game...

**Comment by phweyland** [comment]
The fix starts the edition mode with a limited set of keys.
This way Alt-arrows don't interact with edition any more.
But Alt-arrows are not completely equivalent to mouse hovering.
- The first Alt-arrow stroke starts at the beginning of the collection, not at the selected image
- The last Alt-arrow stroke lets an image hovered, while when the mouse quits the center there is no hovered image any more. Then you have to hover back the selected image to continue the metadata work.
  - The case of multiple selected images doesn't work, because only the last hovered image is modified

What do you think ?

**Comment by ralfbrown** [comment]
This looks pretty good.  You need to Shift-Tab to get back to the desired field even when editing only a single field per image, but with the PR one can e.g. enter a bunch of titles by
- Click first image
- Click in title box
- Type title
- Tab/Enter to commit
- Alt-Right to switch to next
- Shift-Tab to get back to title box
- Type title
- etc.

If the "apply" button were to keep the same field active, then a shortcut to it would allow one to
- type value for field
- press Alt-Enter (for example) to commit, then Alt-RIght
- type field for next image
- Alt-Enter/Alt-Right
- etc.
-
