### ISSUE TITLE
Graphs in both tone curve and tone equalizer modules remains hardcoded and not set by CSS

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#10926]
All graphs are set by define graphs lines in darktable.css themes. This works on all graphs, histogram, filmic, tone equalizer... But this don't work in tone curve and tone curve rvb modules. This had been noticed by @difrkaguilar here: https://discuss.pixls.us/t/my-personal-darktable-theme/28942/12?u=nilvus

I confirmed this by checking with Gtk Inspector tool and nothing is defined nor can be defined with CSS. If someone know and could remove hard-coded things and set those 2 graphs same way as all other graphs, it would be good. Thanks!

Tested on last master at this day but should be here since a time, probably since the beginning.

**Comment by EC1000** [comment]
According to @difrkaguilar screenshot, it's also contrast equalizer graph, isn't it?

**Comment by difrkaguilar** [comment]
Yes, contrast equalizer too.

![Screenshot-20220118194816-670x2160_01](https://user-images.githubusercontent.com/67672868/150663866-56b25fae-d038-496e-b988-e56b1e4b3f93.png)

**Comment by Nilvus** [comment]
Indeed, thanks for completing

**Comment by dterrahe** [comment]
Quick glance at contrast equalizer suggests that it uses two colors from CSS: `selected_bg_color` and `really_dark_bg_color`. Only the first one has different values depending on theme (but never black).

For tone curve, please check if #10972 fixes the issue.

**Comment by Nilvus** [comment]
A copy/paste (useful for this issue) posted in #10972 

I just check and see that all old modules are affected (seems normal finally):

    tonecurve
    tonecurve rvb
    basecurve
    contrast equalizer
    denoise module (profile) on wavelet mode

I probably forgot some.

**Comment by dterrahe** [comment]
Ah, the list of css nodes that should be taken into account would have been useful here. Since quite a few modules use the generic gtk background color (via `gtk_render_background`; you can search for it in the code), more, actually, than use the newer (?) graph_bg, I assumed that was the desired behavior.

If that's not the case, then this is a larger project that probably should be undertaken by somebody who knows what they are aiming for...
