### ISSUE TITLE
[performance] scale up performance to 2021 reality - Part 2

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#10922]
Performance increases to DT to use more of the available memory were introduced in this Pull request, https://github.com/darktable-org/darktable/pull/9764

The logic of the PR around the number of cores limits the system updating to use more of the available memory. The end results is that for most users, the system will default to a Host Memory of 1500 after performing the performance increase.

**Describe the bug/issue**
Some of the new modules in 3.8 (eg. Diffuse) can use a lot of memory to store all of the data. While users do have more available memory in their computers, the host_memory_limit remains at 1500 after the optimization from the PR #9764. 

The current logic in darktable.c

https://github.com/darktable-org/darktable/blob/dc687a2497e73af9c90800b3d014e49b627a5915/src/common/darktable.c#L1594
https://github.com/darktable-org/darktable/blob/dc687a2497e73af9c90800b3d014e49b627a5915/src/common/darktable.c#L1607

ties the memory increase to the available CPU cores. But a system with 4 cores or less (very common), does not meet those two if statements, and it defaults to a host_memory_limit of 1500, even if they have more memory available.

https://github.com/darktable-org/darktable/blob/dc687a2497e73af9c90800b3d014e49b627a5915/src/common/darktable.c#L1621-L1627

**Expected behavior**
If the system has more than 2Gb, DT should allow the host_memory_limit to use it regardless of the number of CPU cores. If less, then use the 1500 default.

A quick way to address this is to change:

https://github.com/darktable-org/darktable/blob/dc687a2497e73af9c90800b3d014e49b627a5915/src/common/darktable.c#L1607
to
else if(mem >= (8lu << 20) && threads >= 2 && atom_cores == 0) 

and 

https://github.com/darktable-org/darktable/blob/dc687a2497e73af9c90800b3d014e49b627a5915/src/common/darktable.h#L160

to 3

**Platform**

* darktable version : 3.8
* OS                : Windows 11, but it should apply to any
* Memory            :  16Gb
* Graphics card     :  Nvidia 3060 12Gb
* Graphics driver   : 511.23
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
A very long discussion here:
https://discuss.pixls.us/t/slideshow-and-tiling-on-a-mac-diffuse-and-sharpen-extremely-slow/28906/64

**Comment by kofa73** [comment]
I'd actually go and separate the memory config from the core count. I understand that it does not make sense to enable CPU-intensive quality settings with few / weak cores (via `plugins/darkroom/demosaic/quality` and `ui/performance`), but why limit memory usage, even for an Atom CPU?

**Comment by gi-man** [comment]
Or why not just default the host_memory_limit to 0 in all cases. 0 means no limit.

**Comment by ralfbrown** [comment]
Not a good default, as then you can have a sudden large allocation (e.g. from diffuse-sharpen) cause swapping, after which the entire system basically freezes until the OOMKiller can terminate dt and what got swapped out gets swapped back in.  I've seen that take several minutes....

**Comment by jenshannoschwalm** [comment]
CPU type (like being an atom) and core count are both wild guesses for cpu cache size and ram access speed. In general data locality has a big impact on performance for modules reading/writing I/O data more than a few times. So it is not such a bad idea to use tiling (some modules code uses internal tiling for optimized performance btw) and current method seems to be good as long as the tile borders are small compared to tilesize.

diffuse&shapen is a tricky beast as the "borders are small compared to tilesize" rule is not met.

**Comment by gi-man** [comment]
Therefore it is correct to limit the use of available memory (8GB) to 1500 on systems with 4 cores or less?

**Comment by johnny-bit** [comment]
Rules needs recomputing for current systems i guess... Leaving enough headroom is necessary for both system and dt so the system won't get into swapping crawl of a state with oomkiller looming over every process and user off to boil a tea over cpu/ram.

**Comment by gi-man** [comment]
See PR #11065
