### ISSUE TITLE
Export using piwigo

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#10928]
**Describe the bug/issue**
Images uploaded via the piwigo export function do get uploaded but is not placed in the chosen album. As can be seen on the last attached image the linked album information is empty.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to storage option and choose piwigo and fill in the required host, user, and password
2. Click on login and choose album or create new album for that matter. Makes no difference.
3. Click on export
4. Image can be found under recent photos instead of the chosen album
![before](https://user-images.githubusercontent.com/2576455/150246503-240e8e07-c457-4cfe-9064-5dc5ed7cf9c7.png)
![after](https://user-images.githubusercontent.com/2576455/150246502-cb4f8a3d-3b01-460a-81eb-223e230a158c.png)
This is where exported images ends up in piwigo:
![place_in_piwigo](https://user-images.githubusercontent.com/2576455/150252526-283055c2-f4be-4568-9ed1-574579cc1e61.png)

**Expected behavior**
The marked image(s) is placed in the chosen album

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0
* OS                :  Linux 5.15.0-2-amd64
* Linux - Distro    : Debian Sid (Unstable)
* Memory            : 32 GB
* Graphics card     :  Nvidia GeForce GTX 1050 Ti
* Graphics driver   :  nvidia-470.94
* OpenCL installed  : OpenCL 3.0
* OpenCL activated  : OpenCL 3.0
* Xorg              : Version: 1:7.7+23
* Desktop           : Cinnamon-5.0.6
* GTK+              : 3.24.31
* gcc               : gcc version 11.2.0 (Debian 11.2.0-14)
* cflags            : 
* CMAKE_BUILD_TYPE  : 
* Piwigo version: 12.2.0

**Comment by TurboGit** [comment]
I can reproduce and seems like a regression due to the recent upgrade of Piwigo. The actual album in which the picture should be uploaded is properly set by darktable (category). Looking at the API call all seems fine.

**Comment by TurboGit** [comment]
I confirm that it is a Piwigo bug, using a Perl script on Piwigo I have the same issue:

```
#!/usr/bin/perl

use LWP::UserAgent;

my %conf = (
    base_url => 'https://<YOUR-PIWIGO-ID>.piwigo.com',
);

my $ua = LWP::UserAgent->new;
$ua->cookie_jar({});

$ua->post(
    $conf{base_url}.'/ws.php',
    {
        method => 'pwg.session.login',
        username => '<NAME>',
        password => '<PWD>',
    }
);

$ua->post(
    $conf{base_url}.'/ws.php',
    {
        method => 'pwg.images.addSimple',
        image => ['/home/obry/Images/studio.jpg'],
        category => 79,
        tags => 'tag1, tag2, another tag',
        name => 'A nice title',
        comment => 'A longer description',
        author => 'Me',
        level => 2,
    },
    'Content_Type' => 'form-data',
    );
```

**Comment by TurboGit** [comment]
For reference, upstream report: https://fr.piwigo.org/forum/viewtopic.php?id=29561

**Comment by mir07** [comment]
I have spend some time looking at the API code in piwigo. To me it seems to be a missing forced cache refresh or a missing event trigger that there are some new images waiting in the upload folder in the API code because after some time (up to an hour) the uploaded images suddenly gets assigned the correct category, tags etc

**Comment by TurboGit** [comment]
Really puzzling then... Is there a cache refresh API? Or is that a default behavior?

**Comment by mir07** [comment]
From my log:
[2022-01-20 10:42:33]   [DEBUG] [i.php] 
  src_path: '20220120104233-06c1fc59.jpg'
  derivative_path: '20220120104233-06c1fc59-me.jpg'
  o_size: '1182 787 930234'
  d_size: '792 527 417384'
  mem_usage: 0.5
  timing: array(
    'load' => 57,
    'rotate' => '',
    'crop' => '',
    'scale' => 94,
    'sharpen' => '',
    'watermark' => '',
    'save' => 21,
    'send' => 0,
    'total' => 174,
  )
[2022-01-20 10:42:42]   [DEBUG] [i.php] 
  src_path: '20220120104233-06c1fc59-me.jpg'
  derivative_path: '20220120104233-06c1fc59-sq.jpg'
  o_size: '792 527 417384'
  d_size: '120 120 14400'
  mem_usage: 0.4
  timing: array(
    'load' => 47,
    'rotate' => '',
    'crop' => 1,
    'scale' => 14,
    'sharpen' => '',
    'watermark' => '',
    'save' => 1,
    'send' => 0,
    'total' => 65,
  )
images not visible since they are not added to any album yet.
[2022-01-20 11:12:57]   [DEBUG] empty_lounge, exec=MKYj, begins
[2022-01-20 11:12:57]   [DEBUG] empty_lounge, exec=MKYj wins the race and gets the token!
[2022-01-20 11:12:57]   [DEBUG] empty_lounge, exec=MKYj, ends

The two images was added to the correct album after empty_lounge was executed so apparently images uploaded via addSimple(...) ends in the lounge which prevents this peace of code to be executed:
 if (!$conf['lounge_active'])
 {
   invalidate_user_cache();
 }

Why and how you control whether an images ends in lounge or not is not known to me.

**Comment by phweyland** [comment]
In UpdateAlbom piwigo plugin I've fixed very recently a similar regression:
https://github.com/phweyland/UpdateAlbum-Piwigo/commit/8504d222658f4ad8ca1e182417fe0b9f16f075a7
to flush the cache.

**Comment by TurboGit** [comment]
I got a response from the devs, the photo is waiting in a temp loudge and we need to wait 5 minutes or explicitly call pwg.images.uploadCompleted. I'll experiment with the later.

**Comment by mir07** [comment]
It is lot easier this way:
$response = $ua->post(
    $conf{base_url}.'/ws.php',
    {
        method => 'pwg.images.emptyLounge',
    }
    );

if ($response->is_success) {
        print $response->decoded_content . "\n";
} else {
        die $response->status_line . "\n";
}

**Comment by TurboGit** [comment]
@mir07 : Well I have taken the hardest path : https://github.com/darktable-org/darktable/pull/10931

But getting the `pwd_token` is good as we may need it for other routines in the API anyway.
