### ISSUE TITLE
retouch: wrong shape selected

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10923]
When using the retouch module it is possible to place a circle shape by clicking the canvas (to define the target shape) and then dragging (to position the source shape). Once the mouse button is released I expect to be able to immediately click-and-drag the source shape to reposition (because that's where my mouse is) it but instead the target shape moves. I have to move my mouse away from the source shape and back onto it for the click+drag to work.

https://user-images.githubusercontent.com/9555491/150207119-810aa078-f7ce-458e-a11b-49073e6319fc.mp4

darktable 3.9.0+141~gb9aa2b5b8 on ArchLinux

**Comment by TurboGit** [comment]
Merged on master and on darktable-3.8.x branch.

**Comment by TurboGit** [comment]
Note that we have the same issue with the continuous creation, but this case is far harder to fix. Feel free to open another ticket to remember this. TIA.

**Comment by elstoc** [comment]
It's a different problem with continuous creation, though it could be the same cause. In this case click+drag moves the canvas. I'll raise another issue.
