### ISSUE TITLE
retouch: drawn path misalignment

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10924]
When drawing source and target shapes using the path tool in the retouch modules I have to place the source shape in a slightly different place on the canvas than the placement of the target shape would suggest. This _seems_ (to my eyes) to be ok when using the circle tool but not with the path tool. 

For instance with the circle tool the shapes seem to align pretty well (I've positioned source and target for the best looking retouch here):

![Screenshot_2022-01-19_20-18-24](https://user-images.githubusercontent.com/9555491/150207992-58c43ca1-51da-495d-ab90-1e293f0fa90c.png)

However, with the path tool the source shape looks to be in a slightly different position to where the actual replacement pixels are taken. I've made one of the control points a sharp corner so that it's more obvious:

![Screenshot_2022-01-19_20-19-49](https://user-images.githubusercontent.com/9555491/150208272-788557d4-f35c-47b0-9e57-3319548b8e1d.png)

and

![Screenshot_2022-01-19_20-31-05](https://user-images.githubusercontent.com/9555491/150209119-62b84c42-cfe8-4294-9494-3b4d4e26fba2.png)

Essentially the issue is that the _contents_ of the source shape do not match the contents of the target shape, as drawn.

This seems to happen without any distorting modules such as lens correction or rotation and I've seen this to a greater or lesser extent on a number of images in both master (3.9.0+141~gb9aa2b5b8) and 3.8.x branches.

**Comment by elstoc** [comment]
Another example. On this issue I used the orientation module to rotate the image by 90 degrees and the rotate & perspective module to correct the rotation. Here I'm trying to use retouch to cover some of the black area created by the rotation so that I can extend the crop a little.

![Screenshot_2022-01-27_22-29-13](https://user-images.githubusercontent.com/9555491/151454453-7374a90d-15b8-4656-87c6-7f7e16df1c05.png)

Here the offset of source vs target is particularly noticeable

**Comment by elstoc** [comment]
@AlicVB since you've done some work in this area, would you mind taking a look please?

**Comment by TurboGit** [comment]
Some investigation on this, I also see that the displacement is OK if a square path is used. My thinking is that the actual area points chosen for computing the source is wrong for path by taking some random points instead of the actual enclosing box area.

**Comment by TurboGit** [comment]
Also when dragging the form using points or segments the source is moving around not following at all the actual target area. All this feel really wrong. @AlicVB : I'm investigating this at the moment, if you have any hint to do hesitate, I feel this is going to be quite hard to fix.

**Comment by AlicVB** [comment]
I reproduce too... For me the issue is more on the "delta" between target and source at compute time. as the forms themselves seems ok... iirc we "just" translate the target pixels to get the source ones. So I would say that we need to verify the translate delta computation

**Comment by elstoc** [comment]
Presumably any fix here will need a version bump because people will have "misplaced" forms that nevertheless they have fiddled with until the retouch looks good, so we'll have to replicate the fault for old edits.

**Comment by TurboGit** [comment]
Found it !!!! YES, it was very hard as the wrong node was used as reference because a specific order was expected but it was wrong. You could read that hundred of times without noticing it!
