### ISSUE TITLE
Liquify Modul is hard to use

### ISSUE THREAD

**Issue by popanz** [darktable-org/darktable#10936]
The help text of the Liquify Modul runs over a few lines so each time you want to select a point the picture gets resized to give these lines the space they need. This makes it quite hard to click the point you want to select because with the new size the cursor is now differently located.

See also on pixls.us:
https://discuss.pixls.us/t/liquify-modul-drives-my-crazy/28998/1

**Comment by TurboGit** [comment]
The help text should be on 2 lines (and no more IIRC). This was also said in pixls. This is not core dt issue but translation.

On which language is that?

**Comment by jade-nl** [comment]
I did not check all the languages available, but the **German** (4 lines) and **Polish** (3 lines) show this behaviour.

I did  check: English, Dutch, Afrikaans, Italian, Czech and French. These are all OK.
