### ISSUE TITLE
New crop module incompatible with old one

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10932]
3.8.

If you work again on a photo which uses the deprecated crop an rotate module, you expect that using the new crop module be the same thing as the old one, i.e. you expect that you can widen the area.

However, you cannot: the cropped out area is lost.

The workaround would be to disable the old module and to apply cropping and rotation with the new modules.

**Comment by TurboGit** [comment]
Yes, and that's not a workaround that the feature there is no way around that. The old crop has reduce the size and up in the pipe there is no information about what was outside of the crop. That's how dt work. Nothing to do so closing.
