### ISSUE TITLE
crop module commits to history stack without parameter changes

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10938]
If I make a crop early in my processing, perform some more steps, and then expand and collapse (or focus/defocus) the crop module again _without changing parameters_ a new entry appears in the history stack. When I hover the history stack entry it shows `bottom 0.9942 -> 0.9942` indicating a parameter that has not changed. Sometimes it lists other unchanged parameters as well.

If no parameters have been changed, there should be no new entry in the history stack.

Tested on `3.8.0+109~g85592cd37` and `3.9.0+141~gb9aa2b5b8`.

**Comment by ralfbrown** [comment]
Same thing happens with the old crop&rotate, and has for years....

**Comment by elstoc** [comment]
indeed

**Comment by elstoc** [comment]
I had assumed something like that. Presumably we could detect _intentional_ change and set a flag so that we don't update if, for example, the user hasn't clicked-and-dragged the bounds of the crop box.

**Comment by jenshannoschwalm** [comment]
I just had a look at the code and it looks like _commit_box is the bad boy always adding a history entry. So probably only need to check for changes there ... Do you have spare time or would you want me to take care?

**Comment by elstoc** [comment]
I'm happy if you want to take a look at it.

**Comment by jenshannoschwalm** [comment]
will do
