### ISSUE TITLE
Add possibility to display photos on the side

### ISSUE THREAD

**Issue by BorisBrock** [darktable-org/darktable#10942]
**The Problem**
Widescreen monitors are getting more and more popular. Mine has an aspect ratio of 32:9. That means that there is a lot (and I mean a LOT) of space to the sides. The height is rather limited though.
When editing photos in darktable, the photo overview is always shown on the bottom of the screen. Thus it takes away precious vertical space, while I have huge empty areas left and right of the photo I'm currently working on.

**The Solution**
I would really like to have the option to show all the photo thumbnails on the left/right side (vertically) instead of the bottom of my screen (horizontally). This would make much more efficient use of a widescreen monitor's screen space.

Of course for non-widescreen monitors it might make more sense to show the thumbnails on the bottom. Thus an option to switch between these modes would be best.

**Comment by Nilvus** [comment]
It's call culling mode and you have an icon at the bottom of thumbnails in lighttable view. To complete my answer of other issue I answer, I so really suggest you to read the manual. You will discover a lot of powerful features. It's always good before asking for existing features. Thanks. And please, think about closing this issue then.

Link to the manual: https://www.darktable.org/resources/

**Comment by VanKurt** [comment]
Hey, thanks for your reply. But I'm note sure if culling mode is what I was looking for. In the manual it is described as:

_Culling mode allows you to display images side by side for easy comparison._

Also it seems to be only available in the lightable view, right?
What I wanted to suggest was to allow moving all thumbnails from the bottom of the screen to the sides in darkroom-mode.

To make it clearer what I mean here's a screenshot of CaptureOne, where the image selection can be moved to the side:
![Capture-One-Pro-mac](https://user-images.githubusercontent.com/5222025/150533765-e958e4d2-fca2-41dd-b05c-da7ba328b186.jpg)

**Comment by elstoc** [comment]
You are talking about being able to relocate the filmstrip to a side panel. That might be hard to do.

**Comment by VanKurt** [comment]
> You are talking about being able to relocate the filmstrip to a side panel.

Exactly. Of course a docking system for all GUI panels would be the most flexible solution. But having two fixed options ("bottom" or "side") would suffice.

**Comment by Nilvus** [comment]
I should be quite tired as it's second time in 2 days that I read badly an issue. Sorry. Anyway, your second comment is clearer.

Allowing what you want would also mean hide (or move elsewhere but where?) already existing left or right panel. Just that make it harder to do.

**Comment by elstoc** [comment]
> Allowing what you want would also mean hide (or move elsewhere but where?) already existing left or right panel.

I suppose the solution would be an _extra_ left/right panel but I'm not entirely convinced it's a good idea. I suppose it might make sense for people with ultrawide monitors.

**Comment by Nilvus** [comment]
> I suppose the solution would be an _extra_ left/right panel but I'm not entirely convinced it's a good idea. I suppose it might make sense for people with ultrawide monitors.

A bad idea I think, that would overload the UI. It's better to think about a floating one or a way to choose which panel to show on left or right.

**Comment by dterrahe** [comment]
> the solution would be an _extra_ left/right panel

Or allow putting the filmstrip in a separate window? Would also be useful for multimonitor.

Probably causes all kinds of fun issues. And it would need to support vertical orientation (but it might already sort of be able to do that because I think the filemanager and filmstrip are the same component?)

Somebody needs to loop in @AlicVB

**Comment by AlicVB** [comment]
from thumbtable pov, that will not require much work I think, it's even simpler than filmstrip : it's "just" a display exactly like lighttable "classic" mode.

Now I agree that the "tricky" part is more "how and where to show it"... another side panel can be an option (again, that shouldn't be too hard to implement)... personally I would prefer a floating window as it would cover the multimonitor situations. But I suppose that colormanaging will be challenging then (not sure ...)
Or we can let the choice (bottom/left/right/floating)

@Nilvus : of course we'll need a clear separation between the actual darkroom part (center + actual side panels) and the eventual "lighttable" side-panel so lighttable doesn't interfere too much visually on the editing part.

**Comment by dterrahe** [comment]
> bottom/left/right/floating

the left/right cases might be covered by floating. I mean, if it is floating, then the window manager can take care of positioning. Presumably if your horizontal real estate is generous, you don't care about auto hiding so much either (or at least the reallocation of the space when it is hidden).

So maybe we just have the current case and floating (colormanaging on other displays to be dealt with at some point, similar to second window).

@Nilvus, would putting the filmstrip into a separate toplevel window cause big issues with CSS do you think? Are there many assumptions that it fits within the current 4 side panel layout hiearchy?

**Comment by Nilvus** [comment]
I'm really not for adding a panel on the left or right of actual darkroom view. Or is it possible to choose which panels we want to display and where/when, or we do it another way. But I don't like the idea to have 2 panels same side. This will just clutter the UI.

What you suggest @dterrahe is much better. And yes floating window can be deal easily with CSS. It's just needed to think about set a specific id to the window, to allow CSS to deal with it independently.

And floating window is already there for me: the 2nd window. Why not add this thumbnails view to the second window. For what @VanKurt want, he will just need to click on 2nd window button and then show/hide thumbnails. It could be good to let the user set if we want this panel visible or not and where (top, bottom, left or right).

What we need to deal with with such way is the idea to let only the image visible by default AND make easy for a user to discover that it's possible to show such panel where he want around. My first idea would be to have a menu option when right-clicking or long click (and with a little top right arrow on 2nd window button.

Or we got to the way to make all panels movable. We could show which panel we want on which side we want.

**Comment by ralfbrown** [comment]
If you put the thumbnails in the second window, you should also add an option to hide the main image in the second window, so the user can choose whether the UI will become less responsive due to the need to run a third pixelpipe for that additional image display.

**Comment by dterrahe** [comment]
> Why not add this thumbnails view to the second window

That's a great idea. Hopefully that will reduce the amount of work to get color management to work correctly...

> It's just needed to think about set a specific id to the window, to allow CSS to deal with it independently.

Actually, I'd hope that no separate CSS work would be needed, i.e. that any tweaking needed for the filmstrip in the main window would automatically get picked up in the second window. Otherwise we'll end up having double the CSS, double the testing and (since that won't happen) double the number of bugs.

> you should also add an option to hide the main image in the second window

Or toggle between filmstrip and full window image (but not both). 

If there really _is_ a need to both have a second window and a floating filmstrip, then I think we should implement them as separate windows, because that would give the user most flexibility in positioning (triple monitors etc) without us pretending that we can foresee and manage all exotic use cases.

**Comment by Nilvus** [comment]
> If you put the thumbnails in the second window, you should also add an option to hide the main image in the second window, so the user can choose whether the UI will become less responsive due to the need to run a third pixelpipe for that additional image display.

Good catch!

> Or toggle between filmstrip and full window image (but not both).

So a 2nd window to display or the image (as actually) or a floating thumbnail view that the user could move where he wants (on the left or right of main window, or even in a second monitor. Just great!

> If there really _is_ a need to both have a second window and a floating filmstrip, then I think we should implement them as separate windows, because that would give the user most flexibility in positioning (triple monitors etc) without us pretending that we can foresee and manage all exotic use cases.

You're right. I suggest to let that for later if more users ask for something like that. If that need to add new color management for this third window, maybe it is too much work and time for not so many users by now. Having the second window more powerful as discussed is a good start.

@VanKurt: as it is your feature request, what's your view on that (by taking care of all comments here and arguments about choices).

**Comment by VanKurt** [comment]
I've been following your discussion with very much interest :-)

In general, I'm not a big fan of floating windows. They tend to get in the way and overlap other GUI elements. Also, when the main window is pulled larger/smaller, maximized or moved, they often don't behave as desired. Thus, I prefer docking systems where the panels can be docked to one side of the screen or another panel. These usually scale correctly.

So for me the best solution would be to have a flexible docking system, where I can pull out panels to make them float (good for multi monitor setups) or I can scale, arrange and dock them any way I like.
A good example would be MS Visual Studio, which is very flexible in this regard.

But of course I realize that such a system might be very complex to implement, depending on the GUI libraries used.

**Comment by AlicVB** [comment]
Just a quick note if someone try to implement it : 
- that should pose too much issues with css. Should be quite straightforward
- this is not the filmstrip mode that should be used, but a "clone" of "classic" thumbtable as filmstrip as some specificity to deal with the "1 line only" part, which will not be the case here. I speak about a "clone" as it will need some different settings as the lighttable view (zoom, ...) and maybe some specificity too (indicator of the current image, ...)

or we can extend filmstrip for a multiple lines display, that would be able in "classic" filmstrip too...

for the floating vs side panel, I think that floating is way more flexible (and if with need to choose one, that's the one to choose, imho), but it has other drawbacks, mainly when it comes to how VM deals with window...

**Comment by difrkaguilar** [comment]
This is almost the same implementation that I had put in post #10110 where the thumbnails of the collections could be viewed in group, this is also a floating window, BTW the idea of a floating window is not bad at all, as long as it is apart from the secondary fullscreen view window, because it must be extremely complicated to make it toggle between the fullscreen image view and another one that simulates the filmstrip and it would be duplicating the lightable/darkroom function but without the side panels and that is not the idea.

This are two screenshots of two instances of dt to have a better idea. Maybe it would be better to add another icon to keep apart the secondary preview window and the "filmstrip(lighttable)" window.

![Screenshot-20220502003001-3840x2160](https://user-images.githubusercontent.com/67672868/166184986-4a743352-6a3d-4226-b37e-d83d0464b51e.png)

![Screenshot-20220502003035-3840x2160](https://user-images.githubusercontent.com/67672868/166185029-ccaa5d74-bc17-442c-945e-c6be2d08c9ba.png)
