### ISSUE TITLE
Shorcut for color calibration color picker

### ISSUE THREAD

**Issue by nachordez** [darktable-org/darktable#10945]
Hi all, and thanks for your work!

There is a little problem with one shortcut that I feel could be MUCH usable and is not available now, in the new 3.8 shorcut system, and I can't imagine why. Perhaps there is a technical question that I'm skipping, or perhaps is something that has mistankenly been disabled.

I refers to the color calibraton module. To the color picker placed besides the color of the current illuminant (see image:)

![Selección_001](https://user-images.githubusercontent.com/10760732/150550860-16507899-a4ed-4049-824c-6304da7a4194.png)

There is no possibility to add a shortcut for that (cross when used the visual way, no entry for it in the manual way). And, for people like me, that shoot usually fast, and not being able to adjust white balance on camera, to have this automatic adjustment in one shortcut, without need to open the Color Calibration module (can't be placed in the fast favourites tab, either), would be something soooo useful. Really, absolutely a time saver!

Could it be make available as a shortcut in next releases? I hope so... The new shorcut system is soooo powerful and there are so many possibilities to improve workflow, that something like this feels (for me) as a big pitty.

Thanks anyway!!

**Comment by dterrahe** [comment]
> Could it be make available as a shortcut in next releases? I hope so...

Definitely. This was just an oversight and requires a one line fix.

Have you come across any other missing shortcuts? Would you be willing to search for them? Could try to fix all at the same time. Little paper cuts like this all come down to somebody putting the time in to test and report. So, many thanks for letting us know!

**Comment by nachordez** [comment]
So happy to be helpful! And to have this shortcut available! :-)

Of curse, I'll try to check for other missing shortcuts that seem not to have reason for be so when I get some time. I've just finished translating new documentation to Spanish and need to get some other free time to be used in future, since next two weeks seem to be too bussy. But I'll do it when I have the time!
