### ISSUE TITLE
Enable dt to support multiple 'sand-boxed' configurations (libraries and databases

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#10941]
**Is your feature request related to a problem? Please describe.**
Currently the tagging module allows the creation of a single tag dictionary only.  In the hands of the average or less-than-expert user this can result in a hierarchical tag dictionary structure which requires a lot of scrolling in the tagging module and makes the complete tagging of an existing portfolio of images a larger task. 

There are also environments in which there is a requirement to keep portfolios of images, and their associated tag dictionaries, quite separate - for personal preference, technical, content/subject matter or legal reasons.

Having the ability to invoke dt on a chosen portfolio of images, in a manner which is analogous to switching catalogs in Adobe LightRoom, would solve these issues.

**Describe the solution you'd like**
Instead of a single configuration in $HOME/.config/darktable/. (for Linux) provide multiple configuration locations, each with their own data.db, library.db etc files. At start up of dt, make the selection of the specific configuration to be used via a small pop-up windows, with radio buttons assigned to each existing configuration and the ability to define a new configuration or delete an existing one (with suitable safeguards). Hide as far as possible the need for the user to edit anything within $HOME/.config/darktable in the same way that the current design does. Provide a similar robust solution for the Windows and MAC environments.

**Comment by dterrahe** [comment]
You are aware of the `--configdir` parameter? Is what you are suggesting just a GUI interface on top of this at program startup, or are you thinking of something totally different?

**Comment by TurboGit** [comment]
Yes, but `--configdir` is not good to use alone. You also need to set `--cachedir`. Furthermore, this is quite low level (command line). I was also thinking that at this stage dt should be able to support multiple "accounts" and be able to propose a simple way to select the one we want when starting.

**Comment by dterrahe** [comment]
Definitely. I just wanted to make sure that this issue is mainly about a startup GUI on top of existing functionality, rather than completely new infrastructure that could cause breakage in many places. The issue title and labels could reflect this.
