### ISSUE TITLE
rotate and perspective : grid lines not in cropped area

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#10949]
**Describe the bug/issue**

The grid is not in the cropped area which is really not very useful :)

**To Reproduce**

1. Go to 'darkroom'
2. Select module 'rotate and perspective'
3. Enter 0.3 in lens shift (vertical)
4. Select 'original format' in automatic cropping
5. Select "rule of thirds" if not already done
6. See that the grids separating the pictures in thirds are on the non cropped area

**Expected behavior**

The grid should be in the cop section as for the crop module. That's the only way to actually properly compose the image.

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/150610614-07bae549-7156-4b5f-a5cf-e572a8c0f1e8.png)

**Platform**

* darktable version : master
* OS                : linux
* Linux - Distro    : debian

**Comment by jenshannoschwalm** [comment]
Likely I will find time tomorrow to fix this...
