### ISSUE TITLE
Add a quick way to compare the current edit to the original state

### ISSUE THREAD

**Issue by VanKurt** [darktable-org/darktable#10943]
**The Problem**
Coming from CaptureOne there is one feature that I miss very much in Darktable:
C1 has a comparison mode, which allows me to compare the current edit of my photo to its original state. This feature is directly available via one click in the GUI. It adds a sperator to the photo that I can drag left and right. Left of the separator the original image is shown, right of the separator the current edit is shown.
This feature is very handy to quickly check if my edit is going in the right direction.

**The Solution**
It would be great to have something similar in darktable. I know that I can jump around in the history stack to compare the current and the initial state of my photo, but this feels rather like a workaround than a tightly integrated feature. Also it requires a few more clicks and is not that obvious to new users.

**Comment by Nilvus** [comment]
It's already possible, with just one step more (that allow more possibilities and it's called snapshots). It's always good to check the manual. Just select which step in history you want to compare (the "before"), create a snapshot then click on last step (on any other step you want to compare for the "after". If you want to know more about that, I suggest you to go read the manual on snapshots part (you could also go it directly by clicking on "?" icon on top of darktable view then click on snapshot with the "?" cursor you will have.

And what I explain is not a workaround. Indeed, it's not a direct one click but it's just more powerful (you could choose processing steps you want to compare. Feature you ask for, just allow to compare original and last step.

Consider closing the issue if this answer anyway what you want.

**Comment by elstoc** [comment]
Define "original state". You mean the undemosaiced raw file? Or after the mandatory automatic modules have been applied? Or after _your personal_ automatic modules have been applied? As @Nilvus says, you can already select any point in the history stack for comparison using the snapshots module.

**Comment by VanKurt** [comment]
Okay, that's a little less convenient (requires more clicks), but much more powerful. IMHO a good tradeoff.
