### ISSUE TITLE
Add more icons for module groups

### ISSUE THREAD

**Issue by BorisBrock** [darktable-org/darktable#10944]
**The Problem**
I want to create my own layout preset. When adding module groups I can choose between various icons for those groups. But the number of available icons is very limited and they do not match my use cases.

**The solution**
It would be nice to have more different icons to choose from. E.g.

- Heart
- Magnifying glas
- Lightbulb
- etc.

This would allow me to choose better matching icons for my groups.

**Comment by dterrahe** [comment]
The icons are created by short cairo programs like here https://github.com/darktable-org/darktable/blob/19825f35cd6f3967c0104740f428ea05286df8c7/src/dtgtk/paint.c#L2455
and need to be added in three places in modulegroups.c (search for dtgtk_cairo_paint_modulegroup_active for an example).

Not sure if this is really a "good first contribution", but would be nice if someone tried!
