### ISSUE TITLE
Can't load Samsung raw files files in darkroom anymore

### ISSUE THREAD

**Issue by Athanos86** [darktable-org/darktable#10951]
I can't open any of my Samsung 2000 raw files (*.srw) anymore.

---------------------------------------------------------------
**Describe the bug/issue**

I can import the files, and darktable is able to read the meta information (Camera model, lens and so on). I get both a lot of previews and "skulls" (I think, I get previews of files that I had open in darkroom in the past, but that's only speculated)
But when I load any srw file into darkroom, I get th error "darktable could not load *.srw into darkroom, switching to lightroom, check if camera is supported etc" 

I provide you with a image and its sidecar file, along with two screenshots (lighttable with the skulls and darkroom with the error)

**Screenshots**
_(if applicable)_
![lighttable](https://user-images.githubusercontent.com/98193331/150613079-e637bab6-8ca9-4cf3-b2f8-ba5d3dff8c20.jpg)
![darkroom](https://user-images.githubusercontent.com/98193331/150613196-a9bb6c2c-ac6a-42b2-9e3e-b935ee96d2c2.jpg)

**Screencast**
[SRWwouldnotload.zip](https://github.com/darktable-org/darktable/files/7917140/SRWwouldnotload.zip)

**Which commit introduced the error**
unknown

**Platform**

* darktable version : 3.8.0
* OS                : Win11
* Memory            : 16GB DDR4
* Graphics card     :  Nvidia Geforce MX 350
* Graphics driver   :  Nvidia Geforce MX 350 30.0.14.7118
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : unknown
* Desktop           : unknown
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
 
 - Can you reproduce with a RAW or Jpeg or both? 
           RAW-file-format only
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? 
           Yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? 
           Unknown
 - Do you use lua scripts?
           No
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by MStraeten** [comment]
according to release notes support was suspended.
Have a look at https://github.com/darktable-org/darktable/wiki/Camera-support to help to reenable support for your cam

**Comment by pn2new** [comment]
Why are new files needed to re-enable something that did work perfectly in the past?
I am in the same situation, having used darktable with .SRW files for years in the past, but not I am no longer able to edit these!

**Comment by MStraeten** [comment]
read this comment: https://github.com/darktable-org/darktable/issues/10951#issuecomment-1019100162

**Comment by Athanos86** [comment]
I'm have the situation, that my camera is converted to full spectrum and therefore I'm not able to provide the requested files, since my camera would lead to strange results for anyone else using .srw files. I convert my files to dng using Adobe converter and that's okay for my purposes.

**Comment by AlicVB** [comment]
But you certainly have some RAW file from *before* your conversion, right ?
Just upload one of them, or multiple if you can get back some with different bit depth, compression, ...
