### ISSUE TITLE
2D color selections

### ISSUE THREAD

**Issue by Thomas-Do** [darktable-org/darktable#10958]
**Is your feature request related to a problem? Please describe.**

darktable is very powerful allowing the usage of parametric (and drawn) masks in nearly ever module. However, parametric masks are now limited to linear selections although two or more of these selections can be combined. 

**Describe the solution you'd like**

To allow  more precise and creative selections, vector scope like diagrams could be used for 2D selections (e.g. path, circle, ellipse, brush) of colors. In addition to classical vector scopes (chroma/hue) diagrams, other 2D diagrams like lightness vs. hue could also be introduced.
Mockup:
![2D_selection](https://user-images.githubusercontent.com/1398286/150645083-6b940fa6-e912-4b1d-b81b-8e08c97bb276.png)

**Alternatives**

**Additional context**

**Comment by MStraeten** [comment]
since the vectorscope just show the result of the whole pixpelpipe a selection made there doesn’t have any relevance to the input or output data of an arbitrary module within the pixelpipe. E.g. a red pixel represented in the vectorscope might have been blue in an earlier module…

**Comment by Thomas-Do** [comment]
I do not suggest to use the existing darktable vector scopes to select colors but vector scope like diagrams inside individual modules. The idea comes from the technique of flow cytometry used in life science. This is used to analyze cells according to different properties that are selected in 2D plots ( https://en.wikipedia.org/wiki/Flow_cytometry [section gating]). In flow cytometry these 2D selections can even be sequentially combined to result in higher order multidimensional selections (example: https://www.nature.com/articles/s41598-020-58678-0/figures/1). To pick colors using 2D plots in contrast to linear ranges allows for a more precise and flexible selection.
For example, at the moment it is  possible to use a combination of  1D parametric masks for hue and chroma. This would result in a color selection as shown in the top image in the example below. A selection by path in a 2D diagram would allow for a more customizable color selection as shown in the bottom image. This could even be combined with further 2D selections  (e.g. hue/lightness) which would raise color selection to a new level in darktable.
![2D_gate_compare](https://user-images.githubusercontent.com/1398286/150694769-b12655bb-7035-4bfd-b745-61f80bd8eaef.png)

I am aware that the implementation would be relatively complex but this kind of parametric masks could allow many new possibilities of image processing that might be rather beneficial.
