### ISSUE TITLE
history-reset should delete instance-names

### ISSUE THREAD

**Issue by wwwFrank** [darktable-org/darktable#10969]
DT-Version: 3.8.0 
OS: Ubuntu Linux 20.04
Darkroom
In the multiple instance actions given a module-instance a name.
For example: "contrast equaliser" using preset "clarity" and than naming this instance "clarity".
Then "history: reset" to start new.
The settings of the module are deleted. The name of the module is still set but is not fitting the values any more.
"History reset" should reset the name too.

**Comment by Nilvus** [comment]
Yes, that could be useful if we admit that when cleaning history means that we want to start from scratch again. And so no, as it's probably not always the case and we could reset history by wanting to keep some modules instances (for example, to just adjust some settings but keeping other and the name set.

So, I think it's a bad idea. The only way I see to deal with those 2 cases is a popup, when clicking on history reset, to ask for reset whole modules panel to actual module groups preset set in module-groups manager.

But, so we need a way to not show each time that popup for those who don't want to reset modules at all. That means so a setting more (and darktable already have a lot of settings, and we agree, with darktable developers to be careful not add too much (that clutter a software!).

**Comment by wwwFrank** [comment]
**Reset, not compress.**
This second case is: marking one step in the history and press the button "_compress history stack_" in the bottom of the module.
I think about a (totally) "_reset_" to the import-defaults triggered with the little reset-icon in the top of the module.

But in the case of "_compress_" it can also be usefull to clear the name. The rule may be: If a module is above the marked step and set back to its defaults, then the name has no more meaning.

**Comment by Nilvus** [comment]
I understood that you talk about reset and not compress. That doesn't change my answer. I let now that if someone want to comment too and/or a developer want to work on that (or not).

**Comment by TurboGit** [comment]
Well, there is arguments in the two sides.

In my case if I name a module "sky" to deal with some sky adjustments, if I reset it to start over the sky adjustments it doesn't mean that I'm ok to reset the name. Of course, one would propose to add an hard-reset to reset the value and the name. Is that really worth the extra complexity?

**Comment by elstoc** [comment]
IMO the big problem is when you compress history. If I have three instances of the diffuse&sharpen module and I select a history step before any of those instances, then compress, two of the instances are removed and the earliest one in the pipe remains, but with its name intact. Whether the name should be removed when you reset using the button is another question (on balance I would argue not) but history should respect name changes.

**Comment by wwwFrank** [comment]
My point of view is: The name should show, what the instance does.
After **reset** the instance does nothing or something else. So the name is **misleading**.

Example: modul "_contrast equalizer_" instance No. 1, preset "_clarity_" (at this point the choosen preset is still bold and checked).
Too heavy? Mask uniformly with opacity 50% (preset is not bold any more).
Second instance coarse 30%.
On the next day optimizing the mask-opacity: Which instance does clarity and which the coarse? I can't see it without names, therefore I name the instances.
After full reset one instance is left, neither "claryty" nor "coarse" but one of these names is alive - **misleading**.

**Comment by Nilvus** [comment]
> My point of view is: The name should show, what the instance does.

And I agree with that.

But if I reset history, I could use again a module instance already use and just change a setting but for same way. For taking your example, I have a preset "clarity" in contrast equalizer, I could use it after resetting history to add carity again (with same settings or even by changing a little clarity). Lost time to set back again module and instance name.

Your workflow and what you want is ok. It could be a good idea to be able to reset all things in one button but consider that other workflows could be useful too. And it's not so easy to take care of all workflows. There's probably different workflow for each different user.
