### ISSUE TITLE
Hard System Crash on Full Screen

### ISSUE THREAD

**Issue by jhod0** [darktable-org/darktable#10960]
When I press `w` or tab to full-screen an image, my entire system crashes. Not just darktable crashing: the screen cuts straight to black and even the power button on my laptop shuts off abruptly. The first time it happened I almost had a heart attack.

I understand that this isn't a darktable bug, and probably have a graphics driver problem, but I am hoping someone here can help me.

System info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

Graphics:

GeForce MX250
Using Ubuntu installed driver `nvidia-driver-470`

```
$ darktable --version
this is darktable 3.8.0
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Comment by parafin** [comment]
Given that it powers off it might be a power supply issue. Does it happen when running on battery or when plugged in? Try both options and ideally try with another power adapter.

**Comment by jenshannoschwalm** [comment]
I would say: the typical symptom of a faulty power supply. (I had the same symptoms twice over the last 25yrs)

**Comment by jhod0** [comment]
Well I switched from the nvidia graphics driver to the open-source nouveau, and the problem stopped. I'll take it as a graphics driver issue

**Comment by parafin** [comment]
You probably just lowered the amount of energy GPU consumes by removing OpenCL support. But in any case I’m closing this issue.
