### ISSUE TITLE
darktable-chart does not work in 3.8.0

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#10974]
**Introduction**
darktable-chart 3.8.0 (darktable LUT tool) displays colors incorrectly after loading a .pfm file.
After loading the cht-file it crashes.

With version 3.6.0 everything works fine.

**To Reproduce**
1.
* create a pfm-file as described on many location in the web.
    - enable lab in darktable
    - switch off not needed modules
    - export as pfm with lab profile
(sorry, i can not deliver the pfm-file, because it is >200MB.
But the error happens also with other pfm-files. I have tried files created from Fuji X-H1 and Nikon D5100 RAWs)
* load the pfm-file into 
-> it displays wrong colors (see screenshot)

2.
* load the ColorCheckerPassport.cht
-> darktable-chart crashes with:
 error parsing CHT file, (parse_cht:482)
free(): double free detected in tcache 2
Abgebrochen (Speicherabzug geschrieben)

**Expected behavior**
Like in darktable-chart shipped with Version 3.6.0. 
It works with the same pfm-file exported with darktable 3.8.0.

But the generated styles can not be imported into darktable 3.8.0.
Workaround: Importing in darktable 3.6.0 -> exporting to new file -> importing to darktable 3.8.0.

**Screenshots**
_(if applicable)_
![darktable LUT tool_001](https://user-images.githubusercontent.com/57417616/150697637-27425571-c54b-4a91-acb0-bb2473584ac9.jpg)
![darktable LUT tool_002](https://user-images.githubusercontent.com/57417616/150697760-f25d1348-75ac-46a5-9464-a820d0c1affb.jpg)

**Platform**
* darktable version 
darktable 3.8.0

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support disabled

* OS
Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.0.4LTS

- Can you reproduce with another darktable version(s)? 
Yes same version, but OS is Windows 10.

**Comment by MStraeten** [comment]
duplicate to https://github.com/darktable-org/darktable/issues/10550

**Comment by herbert-50** [comment]
Ok,
but #10550 only describes error on loading the cht-file not the wrong colors.

**Comment by aradzie** [comment]
Bump.
I am encountering the same issue.

**Comment by obana48** [comment]
Same problem here for DT 4.0.1. Darktable-chart doesn't work properly anymore. PFM files is shown deep dark. CHT files do not load and darktable-chart crashes during importing the file. 

In my case everything worked Ok in Darktable 2.4x.

**Comment by Nilvus** [comment]
That PR is merged but that issue was not linked on your PR @m-p-y, If I understood correctly, your PR fix that so this issue could be closed. I close it, if I'm wrong, just ask me to reopen.

**Comment by m-p-y** [comment]
My bad, sorry @Nilvus. I mentioned the issue numbers in the PR text, but now I understand that I also need to include keywords to properly link to the issues. Next time I try to make it correct. Thanks for manually closing both issues.

**Comment by Nilvus** [comment]
No problem. Most important thing is that they are closed. For next PR, that link explains how to link issues: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
