### ISSUE TITLE
darktable-gen-noiseprofile doesn't know its version

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10977]
darktable-gen-noiseprofile hasn't a command option to know what its version is, please add it

**Comment by da-phil** [comment]
Is there any big benefit from having that? If you have installed darktable with your operating system installer or with the build system (`cmake --build --target install ....`) all files which get installed belong to the same release/version, hence you can just run darktable (`darktable_dev --version`) to get that information.

**Comment by paolobenve** [comment]
I filed the bug because this was the situation on my disk:
- self compiled darktable 3.8.x in /opt/darktable
- self compiled darktable master in /opt/darktable-test
- ubuntu package installed

Trying with the various executables, I got a terrible confusion in my mind: what am I executing?

**Comment by da-phil** [comment]
Sounds like a not very desirable setup anyway :smile: 
But I guess it should be doable to get the version output in this tool, I'll look into it.

**Comment by da-phil** [comment]
> Trying with the various executables, I got a terrible confusion in my mind: what am I executing?

Actually there is a pretty simple method to find the path to the binary, which gets executed, try it with `which <program>`, and then your shell is going to tell you which binary was picked (according to how your environment variable `PATH` is set up). This should give you at least the path to your various installations.

**Comment by paolobenve** [comment]
> which <program>

yes, but sometimes I compile wrongly, and the path doesn't help me...
