### ISSUE TITLE
Wrong message when exporting with no image selected (trivial)

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10971]
3.8

In lighttable view, with no image selected, or no image at all in darktable, hit the export button or ctl-e: "Exporting 0 images..." message appears and remains there.

A better message woud be "No image to export" or something similar.

**Comment by TurboGit** [comment]
> In lighttable view, with no image selected, or no image at all in darktable, hit the export button or ctl-e: "Exporting 0 images..." message appears and remains there.

This is now merged, but I'm curious on how this is possible at all? When no image are selected the `[export] `button is disabled! Any precise scenario to trigger this?

**Comment by paolobenve** [comment]
it triggers with the shortcut ctl-e

**Comment by paolobenve** [comment]
and the export button is enabled when there is no image in the lighttable
