### ISSUE TITLE
rotate and perspective inhibits guide lines display

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#10980]
Guide lines are not displayed when rotate and perspective is expanded, regardless whether it's enabled or not.
To reproduce:
- open an image in darkroom
- expand "rotate and perspective"
- click the guide line toggle: nothing happens!
- expand any other module: guide lines appear!

dt: 3.9.0~git164.d7bb4ff39a
os: openSUSE tumbleweed

**Comment by jenshannoschwalm** [comment]
#10961 made the guide lines available in cropping mode scaled to the crop region, otherwise they are not shown.
Is this wrong for you?

**Comment by lbilli** [comment]
I see what you mean.

Usually I keep automatic cropping off and sometimes I find myself adjusting some of the parameters (_e.g.:_ rotation) manually, using the guide lines as rough reference.
So I was surprised not to see them anymore.
I guess the same task could also be accomplished, maybe even better, using the perspective helpers instead.

Still, I would see no harm in having the guide lines displayed also when automatic cropping is off, using the whole uncropped frame as reference.

Finally, in the current state, the guide lines disappear every time rotate and perspective is selected/expanded even if it is **not** used/enabled.
From a user experience perspective, it feels a bit weird when you click on a toggle and nothing happens.

**Comment by TurboGit** [comment]
@lbilli : Can you test #10983? Is that what you expected?

**Comment by lbilli** [comment]
Well, not completely. After #10983 I observe the following, depending on whether the module is switched on/off and expanded/collapsed:
- when "r & p" is switched **on**: guide lines are drawn for all automatic cropping settings, as expected. 
(On a side note: when the module is also **expanded**, the picture area background becomes a darker grey; not sure if it's expected)

- when "r & p" is switched **off**: guide lines still disappear every time the module is **expanded** 
(the background doesn't get darker).

**Comment by TurboGit** [comment]
> * darker main area background when r&p is on and expanded

Yes, expected. This is also done for crop module. The cropped area is darker.

> * no guide lines when r&p is off and expanded

I would say this is fine as only when the module is enabled we have the cropping & possible perspective correction done. Displaying the guides without the image transformation makes no sense.

**Comment by lbilli** [comment]
> > * darker main area background when r&p is on and expanded
> 
> Yes, expected. This is also done for crop module. The cropped area is darker.

Sorry for nitpicking. I don't want to drag this for too long.
Just a quick observation: the crop module darkens only the part of the picture outside the cropped area and not the grey area around the picture itself. 
r&p darkens uniformly the part of the picture outside the cropped area as well as the grey background around the picture.

**Comment by TurboGit** [comment]
@ibilli: I see now, indeed. No big deal but I'll see if I can fix that. Little details are important, thanks!
