### ISSUE TITLE
InterColorProfile EXIF tag is copied from input to output

### ISSUE THREAD

**Issue by luhk** [darktable-org/darktable#10985]
When importing a TIFF file and exporting as JPEG, the input color profile, which is given via the *InterColorProfile* EXIF tag, is copied to the output file. Additionally, the correct output profile is stored in the JPEG APP2 section. This is problematic when the input profile does not match the output profile (e.g., a panorama created by Hugin in Rec2020 space which is exported to sRGB).
It seems to me that darktable should either not write *InterColorProfile* at all or update it with the correct output profile.

**Comment by kmilos** [comment]
Seems like a bug indeed, thanks for reporting.

Just to be clear, the ICC tag is not part of the [Exif spec](https://www.cipa.jp/std/documents/download_e.html?DC-008-Translation-2019-E), it is and independent/[private](https://www.loc.gov/preservation/digital/formats/content/tiff_tags.shtml) tag of [TIFF/EP](http://www.barrypearson.co.uk/top2009/downloads/TAG2000-22_DIS12234-2.pdf), so should indeed be omitted for other export formats.

**Comment by TurboGit** [comment]
Merged in master and darktable-3.8.x.
