### ISSUE TITLE
Darktable crashes when I try to open a new file

### ISSUE THREAD

**Issue by mel-happygolucky** [darktable-org/darktable#10986]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to darktable
2. In lighttable click on Image
3. Click on file to choose
4. Click on open
5. See error

**Expected behavior**
Expect chosen file to open

**Screenshots**
![image](https://user-images.githubusercontent.com/98381235/150930622-ab63a315-2aaf-455a-8b30-ba2b55f34d70.png)

**Screencast**
[darktable_bt_WWOFG1.txt](https://github.com/darktable-org/darktable/files/7931440/darktable_bt_WWOFG1.txt)

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 2.6.2
* OS                :  AMD FX(tm)-6300 / Windows 10 Pro N/64-bit
* Memory            : 8GB
* Graphics card     : NVIDIA
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
 - Can you reproduce with another darktable version(s)? **not tried, but has occurred multiple times when I try to import a file from other than the folder that it is currently pointing to**
 - Can you reproduce when tryingto upload a RAW or Jpeg or both? **both**

**Comment by elstoc** [comment]
darktable 2.6.2 is ancient and is no longer supported. Please upgrade to the latest version (3.8).

**Comment by johnny-bit** [comment]
Since 2.6.2 there were following releases: 2.6.3, 3.0.0, 3.0.1, 3.0.2, 3.2.1, 3.4.0, 3.4.1, 3.4.1.1, 3.6.0, 3.6.1, 3.8.0

So 2.6.2 is like... 12 releases behind and 3 years old. There were over 11 thousand commits since then (and that's like 1/3rd of all commits to darktable).

Closing since it's hardly possible for any dev to trace the error on such old release.
Please use the latest version.
