### ISSUE TITLE
crop: constrain to "visible" area

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10988]
Now that we've separated crop from perspective correction I quite often want perform perspective correction _and crop_ while still making the most of the available image area. The available crop methods within the rotate & perspective module don't always allow me to do this and so I often find myself switching off automatic cropping within r&p and then manually cropping the image in crop.

However, this takes some care in order to avoid including the "black" parts of the image. It would be useful to be able to constrain the crop module to ignore this area.

To take a somewhat contrived example, the following illustrates the "largest area" mode of r&p:

![Screenshot_2022-01-25_09-51-06](https://user-images.githubusercontent.com/9555491/150953705-457a9691-f011-4832-9102-0a363db20966.png)

The following is what I would do if I wanted a wide crop towards the top of the image (more width is available if I leave the cropping until later) but with the corners very close to the edge of the image, it can be easy to unintentionally leave some of the black area:

![Screenshot_2022-01-25_09-51-57](https://user-images.githubusercontent.com/9555491/150953843-74223dbc-2059-4415-bb02-91606cddd1f0.png)

I don't know if there's a really good way to achieve this, since I have also occasionally used retouch to extend the available area (so I wouldn't want to pass data from r&p up the pipe), like the following crude example, which could be used to extend the "corner" of the croppable area:

![Screenshot_2022-01-25_09-59-18](https://user-images.githubusercontent.com/9555491/150954958-ac6d9fc7-30e4-47d7-8db9-48b030ee1925.png)

Also, those extra pixels being black, they can potentially be brightened or otherwise altered by modules further up the pipe.

**Comment by TurboGit** [comment]
I'm really not sure if this is possible at all. On crop we have zero information about the perspective correction and the black pixels could well be real on the image.

**Comment by elstoc** [comment]
I think you might be right but I'll leave open just in case someone gets any inspiration.

**Comment by AlicVB** [comment]
I've also wanted to do that when I was working on r&p. That should be doable, I think, but not trivial at all : 
We can use (back)transform routines to know if a point in the output image is part of the original image or not, so we may be able to have an algorithm to determine a crop area that exclude black parts (that comes from outside the image)
The only "little" thing we need is to find the algorithm :D

**Comment by TurboGit** [comment]
@AlicVB : Do you think we could get the box information by introspection?

**Comment by AlicVB** [comment]
I don't really know introspection, but maybe...
that should also work by implementing a new (optional) fct for iop... or by some proxy fct (not sure)...
We have to keep in mind that idealy we should do something more generic than just for r&p, as we may have other iop that auto-crop too (lens for example)
