### ISSUE TITLE
Organize lighttable file manager view by related photographs

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#10996]
**Is your feature request related to a problem? Please describe.**

After importing new images or selecting a date range, the file manager view can be overwhelming with the amount of pictures shown. In particular, for people that do not organize their photos by event but by date.

**Describe the solution you'd like**

It would be great to have an option to add “dividers” similar to paragraphs in a text to the file manager view, and thereby group the images in a reasonable way. I could imagine that e.g. adding one split a day at the longest distance between two pictures would e.g. make sense. An example use would be the holiday photos around christmas. If there is a party on 24th, 25th and 26th, it may be reasonable to group all photos that belong to one of the 3 parties. However, the split is not at midnight, but probably between 8 am and 3 pm.

Besides this trivial example, a manual distance entry could be used for splits (split after one hour etc.), or a smart heuristic could deliver automatically reasonable breaks.

UI wise I would split the images by adding a little distance between subsequent groups. This could look like
```
[XX] [XX] [XX] [XX] [XX]
[XX] [XX] [XX] 

[XX] [XX] [XX] [XX] [XX]
[XX] [XX] [XX] [XX] [XX]
[XX] [XX] [XX] [XX] [XX]
[XX] [XX] [XX] [XX] [XX]

[XX] [XX]

[XX] [XX] [XX] [XX] [XX]
[XX] [XX] [XX] [XX]
```
(the distances are a bit exaggerated here as i am bound by the line height for this little ascii “art” …)

**Alternatives**

I suggested a similar feature for rapid photo downloader a couple of years ago, which was implemented to easily assign jobcodes to image ranges. This could be used to apply tags beforehand and then sort by them. However, it would still not be possible to browse a bigger amount of images split by the jobcode, therefore it is not really an alternative workflow.

**Additional context**
n/a

**Comment by spaceChRiS** [comment]
The script is grouping images as … groups. There is no optical separation of groups besides the orange outline when hovering. So I would guess it's the same topic, but a totally different approach/result.

I had this idea while I imported last year's December pictures (I had a broken computer and therefore was not able to work on my pictures during most of December and January) and I started tagging them. But the sheer amount of pictures that showed up made me stop after tagging roughly a dozen. Then I wondered why I am so overwhelmed by the picture flood, and I came to the solution outlined above. In particular, I am typically not overwhelmed by the thousands of words in a book, and it is at least partially because they are organized in paragraphs. A similar organization of pictures in lighttable may also make sense. I thought, others may find this idea interesting, therefore I added it here …

To make such a feature really work well, a smooth scrolling mode in file manager view in lighttable would probably be required. But maybe it's already there and I missed the respective switch for the last couple of years!?

**Comment by spaceChRiS** [comment]
Reading my issue again, some interesting aspect came to my mind. Besides an automatic split of the images, it would be extremely useful to be able to add manual “line breaks” in combination with the albums feature (sort order bound to tag, see e.g. [here](https://github.com/darktable-org/darktable/pull/5134)). This could e.g. be used in preparation of a book, by splitting the sorted images per spread. I could also use it in preparation for my annual calendars where I distribute 12+1 photos per calendar.

**Comment by nicorikken** [comment]
I like this idea. I import pictures from my smartphone only once in a while so I end up with a lot of events stacked together. Grouping then takes mental effort, like: this landscape was taken outside of the venue we had the party, so they are related. Having some separation would highlight most groupings and make it easier to go through the pictures.

Besides splitting overnight I can also think of splitting when a certain time has passed (>4hrs?).

**Comment by spaceChRiS** [comment]
Thinking more about this topic, I came to the following conclusion: Such a separator would be beneficial in different ways, depending on the sorting mode:
* Sort by any date/time (there are several): A dynamic “grouping” as described above would be great, maybe with some flexibility in the settings to e.g. change the time intervals considered etc.
* Sort by file name, title, description and similar: Only for large collections, a separator per first letter of the name would be beneficial.
* Rating: The separator should be where the number of stars changes.
* ID: I don't know if there is a separator needed.
* Color tag: Grouping by color.
* Aspect ratio: Either 3 groups: portrait, square and landscape, or 5 groups with a panorama threshold on both sides.
* User defined sort order: In this mode, a possibility to manually set the “paragraph”/“carriage return” would IMO be best for this mode.
