### ISSUE TITLE
Sorting by file type and show rating in Darkroom view

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#11019]
I use a GoPro Hero for underwater photography. If I use Raw format the camera also save a JPG file. I know I can eliminate the jpg:s in the import dialogue but I think it would be very useful to be able to sort the photos according to file type in the LT view. 

I also think it would be very useful to be able to see the rating in Darkroom view, maybe in the information row at the bottom or as a mouse over.

**Comment by Nilvus** [comment]
What is DT view? DT is mean as darktable, and darktable have quite some views. Do you mean darkroom view?

@phweyland: as you add some filters recently, what do you think about the idea to add file type one?

**Comment by bengtfalke** [comment]
Sorry for my mistake.... for DT I meant DR  as in Darkroom.....

**Comment by Nilvus** [comment]
> Sorry for my mistake.... for DT I meant DR as in Darkroom.....

It's better to avoid such acronyms as it could go to misunderstanding. Using complete term is better!

**Comment by ralfbrown** [comment]
For showing stars in darkroom view, all you need to do is go to preferences (gear icon top right of main image) and add $(RATING_ICONS) to the "pattern for the information line" string on the darkroom tab.

Note that there's currently a bug where it shows blank (zero stars) for rejected images.

**Comment by phweyland** [comment]
> it would be very useful to be able to sort the photos according to file type in the LT view.

You may already know that you can filter in collect module:
![image](https://user-images.githubusercontent.com/23012047/151667604-fe5c5f34-1996-4229-806e-4013afc1719b.png)


In quick filters I think that can make sense once the user can choose the ones we want, because not all users shot in RAW+JPG.


> I also think it would be very useful to be able to see the rating in DT view

![image](https://user-images.githubusercontent.com/23012047/151667248-afbdbed9-8590-4f6c-bf51-76f9ca31f45d.png)

Could be better. Another mode for $(STARS) would be welcome to display ★★ instead of 2★.

**Comment by ralfbrown** [comment]
> Could be better. Another mode for $(STARS) would be welcome to display ★★ instead of 2★.

$(RATING_ICONS) does that, though with the bug noted above and fixed in my PR.

**Comment by bengtfalke** [comment]
Thank you Ralfbrown for that info...

**Comment by phweyland** [comment]
BTW $(RATING ICONS) is found in variables.c but not in gtkentry.c. Could be fixed at the same time.

**Comment by phweyland** [comment]
Rejected image with $(STARS):

![image](https://user-images.githubusercontent.com/23012047/151667950-3fc1243f-4fb9-4614-a337-43ec1088728d.png)

**Comment by todd-prior** [comment]
> I use a GoPro Hero for underwater photography. If I use Raw format the camera also save a JPG file. I know I can eliminate the jpg:s in the import dialogue but I think it would be very useful to be able to sort the photos according to file type in the LT view.

You can do this ..there is a default tag  under darktable that can be used to filter files...it will display all the file types in a folder or film roll and you can choose...you could likely leverage this also maybe with a preset??

![image](https://user-images.githubusercontent.com/44409419/151678106-4bbed90a-c414-4d2d-b254-b4a3fecb8dbf.png)

**Comment by bengtfalke** [comment]
I can live with that filter solution for now....as I can solve my problem with that... thank you all
