### ISSUE TITLE
Pentax K200D .pef file not recognized

### ISSUE THREAD

**Issue by bw35** [darktable-org/darktable#11012]
Hi,

Using Darktable 3.8.0, opening a PEF file produced by a Pentax K200D fails with message "<filename> has unknown format".

Console output says camera isn't supported:

```
[rawspeed] (IMGP9948.PEF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 177: Camera not supported (explicit). Sorry.
```

Relevant entry from rawspeed.xml mentions no-samples as reason:

```
<Camera make="PENTAX Corporation" model="PENTAX K200D" supported="no-samples">
		<ID make="Pentax" model="K200D">Pentax K200D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="0" y="0" width="3880" height="2604"/>
		<Sensor black="0" white="4095"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">9186 -2678 -907</ColorMatrixRow>
				<ColorMatrixRow plane="1">-8693 16517 2260</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1129 1094 8524</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
```

A zipped sample PEF file is attached.
[IMGP9948.zip](https://github.com/darktable-org/darktable/files/7953743/IMGP9948.zip)

I'm happy to provide more samples if needed. What are the requirements for sample images?

Peter

**Comment by kmilos** [comment]
Please provide samples at https://raw.pixls.us, the instructions should be there.

**Comment by bw35** [comment]
PEF and DNG sample image of Color Checker target uploaded to https://raw.pixls.us/

**Comment by bw35** [comment]
I don't see the uploaded samples in the repo too. I don't know if someone needs to approve them first before they show up. Anyway I've just uploaded two more color checker shots (PEF and DNG), this time shot with a tripod with no movement between the shots.

**Comment by leahneukirchen** [comment]
Bumping this, what's missing here?

**Comment by rsutherlandii** [comment]
Pentax K100D Super, PEF files...would be great if you'd support them. uploaded samples at raw.pixls.us; thanks

**Comment by kmilos** [comment]
> Pentax K100D Super, PEF files...would be great if you'd support them.

Works just fine w/ dt 4.0

**Comment by rsutherlandii** [comment]
> 
I go to import, navigate to the folder with the pef files but no files are displayed for import. I'm new to the program, so I might be doing something wrong. I downloaded version 4.0.0 win 64

**Comment by ptilopteri** [comment]
consider closing the issue if it is no longer a problem.

**Comment by kmilos** [comment]
Should be closed by https://github.com/darktable-org/rawspeed/commit/4a64fcc47213182f27ac390b9ca15e05b8988db0
