### ISSUE TITLE
Copy paste bug in `colorspace.h`

### ISSUE THREAD

**Issue by qarmin** [darktable-org/darktable#11025]
https://github.com/darktable-org/darktable/blob/5c3444e43eae55f02f5ea36cfe669f04870d1296/data/kernels/colorspace.h#L598-L613

w is assigned to self
```
xyY.w = xyY.w; 
```

**Comment by TurboGit** [comment]
@aurelienpierre : The line in question should probably be:

`xyY.w = uvY.w;`

?

My main question is would this make some difference and where?

**Comment by aurelienpierre** [comment]
Yup, it's an error. Did you see any effect on masks display ?

**Comment by TurboGit** [comment]
> Yup, it's an error. Did you see any effect on masks display ?

There is nothing buggy on mask display at the moment. I'll try with the fix and will commit if all goes well. Thanks.

**Comment by TurboGit** [comment]
I didn't notice something wrong.
