### ISSUE TITLE
A switch button in "Tagging" messes up Darktable very badly

### ISSUE THREAD

**Issue by Knuterich** [darktable-org/darktable#11024]
The bug is located in the "Verschlagwortung - Tagging"-section. When clicking the button on its lower right corner "Wechsel zwischen Listen- / Baumansicht" (as shown in the attached PDF), the tag-list turns into a long list of strange characters. But that's not the big deal.

The far bigger problem is the fact, that from that second on Darktable is getting very slow. In often takes a minute and even more til it is resonding to any further click. First I thought Darktable hat frozen and killed its process. But starting Darktable takes minutes until it is ready to take the first chlick. After this click it taks often another minute or more to show a reaction for that click.

When one is patient enough (which I wasn't for weeks) an waits until Darktable respond to clicks again, anohter click on that mentioned button brings the list of tags back and Darktable returns to normal behavior. It also starts swiflty again.

To Reproduce
1. Go to 'Verschlagwortung - Tagging'
2. Click on the button on its lower right corner 'Wechsel zwischen Listen- / Baumansicht.' (see attached PDF)
3. The Tags in the window disappear, it shows now those strange characters.
4. Darktable gets very slow now, as descibed.

Screenshot
[Tagging_issue_the_troublemaker.pdf](https://github.com/darktable-org/darktable/files/7965226/Tagging_issue_the_troublemaker.pdf)

Platform

- darktable version : 3.8.0 (Error showed up also on 3.9.0 which I have removed before updating to 15.3)
- OS                : Linux 
- Linux - Distro    : Opensuse 15.3 and also 15.2
- Memory            : 64GB
- Graphics card     : AMD Radeon Pro W5500 (but happend also with an old AMD Radeon R7)
- Graphics driver   : AMDGPU-PRO 21.04
- OpenCL installed  : Yes
- OpenCL activated  : Yes, but the issue shows also up also with deaktivated openCL
- Xorg              : unknown
- Desktop           : KDE
- GTK+              : unknown
- gcc               : unknown
- cflags            : unknown
- CMAKE_BUILD_TYPE  : unknown

Additional context

 - Can you reproduce with another darktable version(s)? yes with version 3-9-0
 - Can you reproduce with a RAW or Jpeg or both? RAW and Jpe and TIFF
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes/
 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? unknown
 - Do you use lua scripts? No
 
This is the first time ever that I have sent a bug report and also my first visit to Github. so Please excuse the humble quality of this report.

**Comment by phweyland** [comment]
I cannot reproduce this. Would that be an issue with the tags themselves ?
Would you mind to share your tag dictionary, the data.db file ?
If that's an issue you can also try to export the tag dictionary (text file) and check it, searching for undesirable characters ...
