### ISSUE TITLE
"add circle" blend shortcut doesn't work on collapsed instances

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11034]
Assigned the shortcut `ctrl+shift+c` to `processing modules/blending/shapes/add circle` and attempted to apply to a module that had gui focus but wasn't expanded. Toast message appeared stating "shapes / add circle: off" instead of activating the shortcut. If I expand the module the shortcut applies correctly. This should work based on the last focused module whether or not it is currently expanded / focused. I suspect this issue may also apply to other blending shortcuts but have not tested.

darktable 3.9.0+192~gd535db9d8 on ArchLinux

**Comment by dterrahe** [comment]
Also, blending shortcuts will be assigned to (the preferred instance of) the last module with blending widgets that had its `dt_iop_connect_accels_multi` called. Which may have only been expanded or enabled rather than focused. Needs to be made consistent.
