### ISSUE TITLE
constant inapplicable import message

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#11046]
openSUSE Tumbleweed 20220201
NVIDIA GF106 [GeForce GTS 450], 390.147
darktable 3.9.0+200~g31c94f187
bit depth is 64 bit
normal build
SSE2 optimized codepath enabled
OpenMP support enabled
OpenCL support enabled
Lua support enabled, API version 6.1.0
Colord support enabled
gPhoto2 support enabled
GraphicsMagick support enabled
ImageMagick support disabled
OpenEXR support enabled
OpenCL on
i7 12-core 36GB
kernel 5.16.2-1-default

when importing new D850 nef's, I get following msg for every image:
  [exif] did not find a supported dng illuminant and color matrix pair

system response is much slower than normal
got coredump when expanding display of imge <mouse-wheel up>
coredump:  http://wahoo.no-ip/org/~paka/core.darktable.0202a.zst

**Comment by ptilopteri** [comment]
parafin says following pr is cause of msg:
  https://github.com/darktable-org/darktable/pull/11015

**Comment by ptilopteri** [comment]
coredump is repeatable

**Comment by TurboGit** [comment]
@kmilos : Can you have a look? This is quite important as the #11015 PR has been merged into 3.8.1.

**Comment by kmilos** [comment]
Will do. How does a NEF trigger DNG code path?! Can we have a sample link please?

**Comment by ptilopteri** [comment]
http://wahoo.no-ip.org/~paka/220202_105742_aaa_7801.nef
can provide 28 more from same series if needed.

**Comment by ptilopteri** [comment]
I have always used lossless compressed and this camera and lens combination was recognized.  and I do not know about uncompressed or lossy as I have never shot that way.

**Comment by kmilos** [comment]
So far not able to reproduce, that NEF loads just fine here (3.8.1 branch though on Windows)...

@TurboGit I will put a condition on that error message, it gets printed for all non-DNG raws now

**Comment by TurboGit** [comment]
@kmilos : I can reproduce on GNU/Linux using **master** branch and I also have this message when using darktable-3.8.x branch.

What is strange is that the NEF that @ptilopteri provided does not get imported most of the time. That is, I get the message "1 image imported" and nothing in the lighttable and the new collection does not appears in the collection module.

**Comment by TurboGit** [comment]
> @TurboGit I will put a condition on that error message, it gets printed for all non-DNG raws now

Right, maybe just remove this else part with the `fprintf()` altogether.

**Comment by TurboGit** [comment]
> What is strange is that the NEF that @ptilopteri provided does not get imported most of the time.

Forget about this part, the file I had imported was corrupted... Not sure why, but that's not dt issue.

**Comment by kmilos** [comment]
The message should be removed now, but I still don't see a correlation to the core dump...

**Comment by ptilopteri** [comment]
indeed it is.  tks much
