### ISSUE TITLE
Tab state in main preferences is not saved in another language than english

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#11040]
**Describe the bug/issue**

When you open main darktable preferences in english, preferences are open in related tab of the view. If you're in lighttable view, so preferences are opened in lighttable tab, if in darkroom view, so in darkroom tab. Anyway, when I'm using darktable in french, main preferences always open in first tab (general one).

This issue is for a bug fix AND a feature request.

**To Reproduce**
1. be sure to be in english
2. be in lighttable view
3. launch main preferences
4. they are opened in lighttable tab
5. set language to french (tested with espanol and italiano languages and same issue)
6. repeat 1 to 4 steps above and see that preferences are opened in general tab

**Expected behavior**

The behavior should be the same in all languages. This is probably some translation not defined in that behavior.

Here, I understand the idea to open related tab of used view and it's a good thing. Anyway, I rarely change tabs but I really often use general tab, so english behavior is annoying for me as I should always click on general tab.

I so propose to fix that issue for all languages with the default english behavior. AND add an option, I would say on misc tab, to allow the user to change which behavior when opening main preferences between related tab to the current view or general one (or why not define which tab).

So that could be an option by just checking a checkbox (or unchecking them) to define related tab or general tab (by default related tab of the view).

Or have a dropdown menu with, on first option (and the default one): "open related tab of the current view" and the list of all tabs to allow the user to set which one he want.

**Platform**

* darktable version :  actual master

**Comment by elstoc** [comment]
#11041 should fix this behaviour so that all languages work the same as English.

The other question is whether or not this is good behaviour. In that regard I'm not bothered either way. It seemed fine when I did it but I can see why it might be annoying to some. I'd rather choose a "best" default behaviour though - this is definitely not something we need another preference for.

**Comment by Nilvus** [comment]
> #11041 should fix this behaviour so that all languages work the same as English.
> 
> The other question is whether or not this is good behaviour. In that regard I'm not bothered either way. It seemed fine when I did it but I can see why it might be annoying to some. I'd rather choose a "best" default behaviour though - this is definitely not something we need another preference for.

On what I see, and it's logical, this behavior is so, for only lighttable and darkroom views. So is it worth  needed behavior? Maybe just let preferences opened in general tab (or last opened tab when closing preferences).

Anyway, thanks for the very quick fix proposal! Fast!

**Comment by elstoc** [comment]
> Anyway, thanks for the very quick fix proposal! Fast!

No problem. I just happened to know where the code was when I saw the issue so it didn't take long.

I suspect I edited my previous post (I do try not to do that all the time) while you were writing your reply so I suggested the same options as you.

**Comment by elstoc** [comment]
@Nilvus: Since the "bug" is now fixed, could we either relabel this as a feature request (if you still want to change how it works) or close this and open a new one.

**Comment by Nilvus** [comment]
You're right, it's better to close that one. I'm not sure by now if it's needed to change that even if it could be annoying, but especially for me when I'm working on CSS. I rarely change settings (they are now great for my needs), so my only frequent use is CSS editor. But it's a specific case and probably opening related tab of the current view is a good thing for most users. Consistency between language was the most important.
