### ISSUE TITLE
$(PICTURE_FOLDER) not resolved on `copy & import`

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#11051]
**Describe the bug/issue**
Trying to use _copy & import_ fails (at least on Windows 10, will try to confirm later on Linux). No images are imported and the following is logged:

    failed to create session path $(pictures_folder)\darktable\20220203_no_name.
    [import_session] Failed to get session path.

$(PICTURE_FOLDER) is display correctly if added to lighttable tooltips and overlay. Note that in the error message it is all lower-case (I don't know if that is relevant, or just darktable-style, lower-case formatting).

**To Reproduce**
1. Click _import & copy..._ on the lighttable.
2. Select images.
3. Start the import.
4. See error: 0 images imported.
5. Check the logs.

**Expected behavior**
Images are imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/3177739/152384711-2a48a62e-61f4-4980-bac0-32a5e97721eb.png)

Adding to lightable tooltip/overlay:
![image](https://user-images.githubusercontent.com/3177739/152384867-e48458e0-85f0-4805-bb51-8d42729a8162.png)

Text displayed on lighttable with mouse hover:
![image](https://user-images.githubusercontent.com/3177739/152385001-50e57fd3-c38d-4dc9-ad28-8d7ba3924825.png)

**Platform**

* darktable version : 3.8.0 (official build from darktable.org)
* OS                : Windows 10
* Memory            : 16 GB
* Graphics card     : N/A
* Graphics driver   : N/A
* OpenCL installed  : N/A
* OpenCL activated  : N/A
* Xorg              : N/A
* Desktop           : Windows
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
Environment variables (domain etc. removed):
```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\istvan_kovacs\AppData\Roaming
CAMLIBS=C:\Program Files\darktable\lib\libgphoto2\2.5.27
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\istvan_kovacs
IOLIBS=C:\Program Files\darktable\lib\libgphoto2_port\0.12.0
LOCALAPPDATA=C:\Users\istvan_kovacs\AppData\Local
MAGICK_HOME=C:\Program Files\darktable\lib\GraphicsMagick-1.3.36\modules-Q8\coders
NUMBER_OF_PROCESSORS=8
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0c
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\ISTVAN~1\AppData\Local\Temp
TMP=C:\Users\ISTVAN~1\AppData\Local\Temp
USERNAME=Istvan_Kovacs
USERPROFILE=C:\Users\istvan_kovacs
windir=C:\WINDOWS
```

**Comment by kmilos** [comment]
Indeed seems like a duplicate of https://github.com/darktable-org/darktable/issues/10934

**Comment by kofa73** [comment]
I'm not sure. The year was resolved fine, see 2022 in the error message:
`failed to create session path $(pictures_folder)\darktable\20220203_no_name`

**Comment by kmilos** [comment]
It is about the first variable, not what it is.

**Comment by kofa73** [comment]
Sorry. Re-opening: replacing $(PICTURES_FOLDER) with a concrete path works, the import is performed.

**Comment by kmilos** [comment]
Ok, thanks for checking.

**Comment by kmilos** [comment]
Hm, seems to work for me on master, I'll also try to build the 3.8.1 branch later... Can you also try a more recent build, like the "Windows insider" ones?

**Comment by kofa73** [comment]
Tried with **'Windows Insider' 3.9.0+192~gd535db9d8** (with a library and configdir separate from 3.8.0), and it **works fine** with that version. Also tried 3.8.0 with a pristine environment, does not work.

**Comment by kofa73** [comment]
Already fixed (see above)
