### ISSUE TITLE
pixelpipe: module helper histograms not updated if data read from cache

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#11069]
The helper histograms inside the modules are not updated if data are read from pipeline cache. (You can do whatever changes visible output like switching on/off the highlights reconstruction module offering a nice purple cast - the main histo is changed always, the modules histo is **not**) This is easy to understand, as in ```dt_dev_pixelpipe_process_rec``` we immediately go to ```post_process_collect_info```, where we only update the main histo but do not check/update inside the modules. (This can and should probably be fixed there)

_Originally posted by @jenshannoschwalm in https://github.com/darktable-org/darktable/issues/11003#issuecomment-1028001429_

**Comment by dtorop** [comment]
Test case:

- Open exposure module, drag up exposure slider
- Create, activate, and expand RGB curve module so that its background histogram is visible
- Click on/off the exposure module

The background histogram on RGB curve should change, but doesn't with current code.

I've been looking into this a bit. I've tried a couple solutions:

1. Don't use cache for any iop which is preceded in the pixelpipe by an active/expanded iop which requires a histogram. This check goes at start of `dt_dev_pixelpipe_process_rec` in section 1, "if cached buffer is still available, return data". There is already code there to skip the cache for gamma iop in preview pixelpipe, in order to make sure that gamma input is available to update the final scope/pickers.
2. Same as 1, but do this work in `dt_dev_pixelpipe_cache_basichash`. Make the iop hash include the pipe timestamp (hence be unique) if one of its predecessors iops needs to show a histogram. While at it, do the same for preview gamma, removing the corresponding check from `dt_dev_pixelpipe_process_rec`. This does move a bit of GUI-ish logic into the pixelpipe cache, but there is already similar logic there to handle colorpickers. This plan simplifies `dt_dev_pixelpipe_process_rec`, and means that we don't have to scan predecessor iops twice (as the cache code already runs this scan).

I've coded both of these, and they seem to work. Things are still wrong with per-iop colorpickers (they don't update when a prior iop changes input of an iop with an active picker). I'll look into this.

The downside of either of these solutions is that we don't get to use the cache much in preview pixelpipe if an iop is showing a histogram. This is probably OK as the preview pipe is relatively quick, and its updates lag the full pixelpipe and center view.

Another scheme that I haven't tried, to keep some more benefit of the cache: Do two passes in the preview pixelpipe. One will caclulate output, using cache if possible. Where possible it updates scope/pickers, and flags when it has done this. Then there is a second pass on the pipe where it finds places where scope/pickers still need updates. It will then run the pipe as necessary (ideally retrieving data from cache) to figure out input/out for relevant iops and update scopes/pickers.

I can't figure out if this is a good idea (will execute faster by using the cache in many cases) or is a terrible idea as it'll make yet another code path and require a bunch of flags. It may also require tuning -- should it do the scope/picker pass as a second pass afterward, or whenever the pipe is using the cache to skip iops which have scopes/pickers?

The root problem here is that the pixelpipe cache can store output of each iop -- and it's often possible to figure out an iop's input via the cached output of its predecessor. But scope and picker data is not cached for each iop, and hence is not updated when the cache is used. It probably _would_ be possible to create a cache for this data as well...

My thinking is to get 1) or 2) above into shape as PR to fix this bug and make things "correct". Then consider a more complicated fix as a potential later optimization.

There's also more problems, e.g. if you turn off rgb curve but keep it expanded, the background histogram of it no longer is drawn. This is probably right. Unfortunately, the iop doesn't update to erase the histogram until there is a mouseover event in the module widget.

**Comment by jenshannoschwalm** [comment]
Thanks for the analysis and the first pr :-)

I don't know the details of 1) and 2) solutions, but what about `dt_dev_pixelpipe_synch()` keeping track of an expanded module requiring a histogramm leaving a flag in the pipe struct and in that case "don't read from cache"? I think a "missing cache hits solution if histo-requiring module is expanded" is not a big issue

**Comment by dtorop** [comment]
> what about `dt_dev_pixelpipe_synch()` keeping track of an expanded module requiring a histogramm leaving a flag in the pipe struct and in that case "don't read from cache"?

I wish I understood `dt_dev_pixelpipe_synch()` enough to know how to do this! The 2) fix is pretty trivial, a minimal version is:

```diff
modified   src/develop/pixelpipe_cache.c
@@ -120,6 +120,12 @@ uint64_t dt_dev_pixelpipe_cache_basichash(int imgid, struct dt_dev_pixelpipe_t *
         }
       }
     }
+
+    // can't cache if preceded by a module which shows a histogram --
+    // histogram won't update when that module is skipped via cache
+    if(piece->module->expanded && (piece->request_histogram & DT_REQUEST_ON))
+      hash = ((hash << 5) + hash) ^ pipe->input_timestamp;
+
     pieces = g_list_next(pieces);
   }
   return hash;
```

> I think a "missing cache hits solution if histo-requiring module is expanded" is not a big issue

Yes agreed.

The worst thing I've found so far is handling when an iop with a background histogram is disabled. Right now the histogram is only supposed to be drawn when the iop is enabled, but it doesn't actually disappear when the iop is disabled until a mouseover event. And until then it's visible but not updated.

Worse yet, the iop API doesn't seem to offer a good way to get a signal/callback on a module being disabled, except for some horrible hacks, e.g. catching `DT_SIGNAL_DEVELOP_HISTORY_CHANGE` and checking if the module is disabled.

The better route seems to be to always update the background histogram, even for disabled modules. This requires yet more code in the pixelpipe, yet another subtle variation of extant codepaths. But the result is fast enough and looks good.

Other problems so far:

- Color zones background histogram seems wrong.
- I haven't even begun to understand how this relates to per-iop colorpickers.

**Comment by jenshannoschwalm** [comment]
My `dt_dev_pixelpipe_synch()` was mainly about the time you know about "module history to be updated"

From what i remember it checks **all** module in the **complete** history **before** processing the pipeline so you would know at least in advance. Like 
```
   if((strcmp(piece->module->op, "demosaic") == 0) || (strcmp(piece->module->op, "rawprepare") == 0))
```

**Comment by dtorop** [comment]
> From what i remember it checks **all** module in the **complete** history **before** processing the pipeline so you would know at least in advance.

That makes sense. `dt_dev_pixelpipe_cache_basichash` also iterates through all the modules (though mid-pipe). Or more accurately for each module in the pipe, it iterates through all modules before that module -- which is useful to determine if one of those has a histogram to update. Using `dt_dev_pixelpipe_synch` and flags might make this logic clearer, but probably the same effect.

There's a version of the fix at https://github.com/darktable-org/darktable/compare/master...dtorop:pixelpipe-update-iop-histogram-picker?expand=1. It _seems_ to work, but I haven't tested it well, and the commit history is a mess and needs a clean-up. There also may be some questionable decisions in it (e.g. it does work in cache, not synch). Though it looks like a large PR, ignoring whitespace changes reveals that it is (a bit) smaller than it looks.

The biggest change is that iops with background histograms show an (up-to-date) histogram even when disabled. I can't tell if this is a performance problem. I do like that if I expand an iop such as rgbcurve or colorzones that the background histogram now immediately appears, rather than (with a lag) once I enable the module or make the first point on the curve.

Working on this makes me think that grafting per-iop histograms and colorpickers onto the pixelpipe is a bit of a leaky abstraction. This is particular so due to the caching and CPU/GPU paths. Hence fixes to corner cases (such as this) risk really spinning out of control...

**Comment by jenshannoschwalm** [comment]
> Using `dt_dev_pixelpipe_synch` and flags might make this logic clearer, but probably the same effect.

Agreed.

> Working on this makes me think that grafting per-iop histograms and colorpickers onto the pixelpipe is a bit of a leaky abstraction. This is particular so due to the caching and CPU/GPU paths. Hence fixes to corner cases (such as this) risk really spinning out of control

I didn't test your code so far, just read through the diff. I am also not sure if the possible maintenance burden here outweighs the "correctness" of the local histo. Personally i don't care a lot ...

**Comment by dtorop** [comment]
> just read through the diff.

Much appreciated.

> I am also not sure if the possible maintenance burden here outweighs the "correctness" of the local histo

Yes! It turns out there's a better way: The GUI can detect when a scope is disabled and redraw it if it has a histogram.

Also, this code is currently written on top of #11060, so it's smaller than it looks: https://github.com/dtorop/darktable/compare/scopes-cache-tidy...dtorop:pixelpipe-update-iop-histogram-picker?expand=1

I still do need to do some more cleanup, though...

**Comment by jenshannoschwalm** [comment]
Since latest pixel pipe  cache work we should have cached data for all expanded modules in preview pixel pipe. Any idea what to do on this issue?
