### ISSUE TITLE
Canon R3

### ISSUE THREAD

**Issue by oguruma1218** [darktable-org/darktable#11075]
Just uploaded a full R3 sample set.

**Comment by oguruma1218** [comment]
I don't use Github. Apparently I assigned @LebedevRI ??? Is that something I accidentally did? Or did somebody do it on my behalf?

**Comment by kmilos** [comment]
Should be supported by upcoming dt 4.2 - please test and close if ok.

**Comment by kmilos** [comment]
Confirmed working in 4.2.

@Nilvus Please close.
