### ISSUE TITLE
Fujifilm GFX 100 support issues

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#11071]
Tested with an uncompressed RAF from dpreview:

- The white point in raw/black white point is probably wrong and should be around 32500 instead of 16383.
- The colors are IMHO better if you take the values ​​of the GFX50 in the standard color matrix (source: adobe_coeff.c).
- Compressed RAFs are not yet supported.

**Comment by kmilos** [comment]
> The white point in raw/black white point is probably wrong and should be around 32500 instead of 16383.

Indeed, looks like both black and white points need to be different between 14-bit and 16-bit modes which rawspeed currently doesn't seem to distinguish @LebedevRI 

```
Exif.SubImage1.BlackLevel                     15872/256 15872/256 16128/256 16128/256
Exif.SubImage1.WhiteLevel                     16383
```
vs
```
Exif.SubImage1.BlackLevel                     65536/256 65536/256 65536/256 65536/256
Exif.SubImage1.WhiteLevel                     65535
```

> The colors are IMHO better if you take the values ​​of the GFX50 in the standard color matrix (source: adobe_coeff.c)

The coeffs come from the Adobe DNG converter for all cameras, and I don't think we should be doing anything different here (I just double-checked there was no error in pasting the values). Perhaps the wrong black point was part of the problem as well. You can finally of course [do your own calibration](https://pixls.us/articles/profiling-a-camera-with-darktable-chart/).

> Compressed RAFs are not yet supported

[Known issue.](https://github.com/darktable-org/rawspeed/issues/228)

**Comment by jas01** [comment]
I have the same issue with the GFX 100S 16 bits uncompress file. It's indeed open with darktable, but it's mostly unusable because the image are always way too bright. 
I just like to understand where are the problem, is it in some profiles (maybe I can help by providing some file/test/etc.) or in the core of darktable (no way I can help)

**Comment by LebedevRI** [comment]
9cde436e011c70c696f362409f3593e1f17ebca8
