### ISSUE TITLE
Slightshow - high CPU load

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#11082]
Starting the slightshow (key: S) often leads to a high CPU load. Even after finishing the slightshow the load remains high until darktable is closed.

version: 2.8.0
OS: windows 10 64 bit
CPU: intel core i7

![Bild1](https://user-images.githubusercontent.com/57685590/152816268-eef8ee3b-818c-4a3c-8eea-369c18cf4c56.jpg)

**Comment by dterrahe** [comment]
Correct spelling helps find relevant issues and duplicates.
