### ISSUE TITLE
windows 11 handling problem - crash on load

### ISSUE THREAD

**Issue by jawinbn** [darktable-org/darktable#11097]
3.6 was working fine on this machine. installed windows 11, DT 3.8 about the same time and havent had successful DT start. Ubuntu dual boots on the same machine and DT works fine there.. Here is the error report file.
Thanks.

[darktable_bt_MN0GH1.txt](https://github.com/darktable-org/darktable/files/8036742/darktable_bt_MN0GH1.txt)

**Comment by MStraeten** [comment]
Seems to be a duplicate to https://github.com/darktable-org/darktable/issues/10767
Since such issues are files frequently with exactly the same granularity of information it’s worth to mention that there‘s a search function in GitHub ;)
