### ISSUE TITLE
an unhandled exception when accessing a folder in an unremovable library place

### ISSUE THREAD

**Issue by PontiacCZ** [darktable-org/darktable#11092]
**Did you buy darktable from an application store ?**
No.

**Describe the bug/issue**
The Darktable 3.8.0 crashes when I open a folder that I was not able to remove from import places. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. I right-click a place "2021-08-10 Hoštice s Verčou" to remove it
2. I get "you can't delete the selected place" error (but no reason why I can't) - see the screenshot: 
(BTW the folder still exists)

![image](https://user-images.githubusercontent.com/9153595/153190243-c5e04ea7-5509-45b4-af12-6aa2e7765b10.png)

3. Then I click on the folder and that's when it crashes:

![image](https://user-images.githubusercontent.com/9153595/153191088-ec967a88-80d5-432c-8d51-0616bf6d50f1.png)

4. I am attaching the backtrace: [darktable_bt_XSSIH1.txt](https://github.com/darktable-org/darktable/files/8032201/darktable_bt_XSSIH1.txt)

**Platform**

* darktable version : 3.8.0
* OS                : Windows 10 64 bit 21H1
* Memory            :  16 GB
* Graphics card     :  AMD Radeon Vega 8 Graphics

**Comment by phweyland** [comment]
1. you cannot remove the selected place. First select another one.
2. What is the actual path / filename ?

**Comment by PontiacCZ** [comment]
1. oh, I see now. I managed to delete the place when not selected.
Anyway, this issue is about the exception when entering the specified folder.

2. "actual path" - where do I see it in Darktable?

**Comment by phweyland** [comment]
> 2\. actual path" - where do I see it in Darktable?

In your browser, like `c:/user/philippe/Documents/Images/Photos` ...

**Comment by PontiacCZ** [comment]
From the example I'd say you mean file manager - well, in my Total Commander it is "C:\temp2" (the other pane "c:\Users\Paja\AppData\Local\Temp\".

**Comment by phweyland** [comment]
What I would like to know is what is the actual path of your "places", in particular the one which fails.

**Comment by PontiacCZ** [comment]
It crashed on "c:\_k_archivaci\foto, video\2021\2021-08-10 Hoštice s Verčou\"

**Comment by phweyland** [comment]
> "c:_k_archivaci\foto, video\2021\2021-08-10 Hoštice s Verčou"

Great ! Thanks.
Comma in the name. See #11089.
