### ISSUE TITLE
An unhandled exception occured.

### ISSUE THREAD

**Issue by Regenskind** [darktable-org/darktable#11094]
Hi,
I just installed Darktable 3.8.0. on windows 10 - 64. I click on the icon and get this error message.

![IMG_20220209_181242](https://user-images.githubusercontent.com/99353535/153257775-c02fce0b-a129-4c15-86ac-2e61f78e0140.jpg)

**Comment by Nilvus** [comment]
We provide a template and asked for many informations. You provide so few here and as written on your dialog window, you have a txt report file that you don't post here. It's also good to search existing (and closed) issues here and you will see some similar issues. And they are most of the times related not to darktable (which is here just a symptom) but OpenCL issue. I let you search existing similar issues (just with your title!) and try to fix it with what you will find. You could also find useful infos on pixl.us forums. And this place is for issues related to darktable code.

With so few infos, nobody can help you here. I will so close it.
