### ISSUE TITLE
memory sizing for >= 16 GB

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#11100]
The `>> 11` shift in the memory calculation implies a halving (shift by 10 to convert kB -> MB, shift by 1 to halve):

https://github.com/darktable-org/darktable/blob/2665a897f049f46b861b073914c40da90c727650/src/common/darktable.c#L1599-L1600

Probably copied over from this, where halving is explicitly mentioned:
https://github.com/darktable-org/darktable/blob/2665a897f049f46b861b073914c40da90c727650/src/common/darktable.c#L1613-L1614

@aurelienpierre says this is supposed to be per-thread: https://youtu.be/ImX0wr2z1S4?t=1232, so either the thread count should be used as a divisor (otherwise we'll overwhelm the machines by using this), OR we are overly cautious by subtracting 4 GB and then halving the result.

**Comment by kofa73** [comment]
@johnny-bit

**Comment by johnny-bit** [comment]
TBH i interpreted the value as "global" mem limit since on 8gb machine it's half and honestly 8gb machine can and does have more than 2 threads so...
Given than - the halving might be mishap on my part. I don't remember exactly but I meant to leave 4GB headroom

**Comment by johnny-bit** [comment]
Then my intention for general members limit for machines with 16gb ram or
more is full ram minus 4gb headroom so we probably don't hit swap or cause
swapping

pt., 11 lut 2022, 23:15 użytkownik Hanno Schwalm ***@***.***>
napisał:
