### ISSUE TITLE
OSX packaging: libusb patch doesnt match current libusb @1.0.25_0

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#11101]
the patch
/[packaging](https://github.com/darktable-org/darktable/tree/master/packaging)/[macosx](https://github.com/darktable-org/darktable/tree/master/packaging/macosx)/libusb-no-clock_gettime.diff
doesn't fit macports recently updated libusb @1.0.25_0

**Comment by parafin** [comment]
Was just looking into this when you reported it:) That patch was merged into 1.0.25 release, but they introduced another bug with exactly the same consequences. I've updated the patch to fix this new problem.
