### ISSUE TITLE
Ctrl + Alt doesn't change modules side panel scroll behavior 

### ISSUE THREAD

**Issue by yujiberra** [darktable-org/darktable#11104]
**Describe the bug/issue**

Holding down Ctrl+Alt while using the scroll wheel on the modules side panel has no effect on the behavior.

In other words, if "mouse wheel scrolls module side panel by default" is enabled, then the side panel is scrolled regardless of whether Ctrl+Alt is held down, and if the option is disabled, then the scroll wheel affects slider values regardless of whether Ctrl+Alt is held down.

**To Reproduce**

1. Disable "mouse wheel scrolls modules side panel by default"
2. Go to darkroom
3. Hold Ctrl+Alt
4. Rotate the scroll wheel when the mouse cursor is in the modules side panel

**Expected behavior**

The side panel should scroll up or down

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0-1.1
* OS                : Linux 5.4.0-97-generic x86_64
* Linux - Distro    :  Linux Mint 20.2
* Memory            :  32GB
* Graphics card     : RTX 3070
* Graphics driver   : 495.46-0ubuntu0.20.04.1 
* OpenCL installed  : No
* Xorg              : 1:7.7+19ubuntu14 
* Desktop           : Cinammon(GNOME)
* GTK+              : 3.24.20-

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? no

I've only just started using Darktable, so I haven't changed any of the global preferences or done any configuration to speak of.

**Comment by dterrahe** [comment]
It works as intended/expected for me in master on Debian. Do modifier keys otherwise work as they should for you (for example when manipulating masks or in shortcuts)? Does shift+scroll or ctrl+scroll over a slider increase or decrease the speed?

**Comment by dterrahe** [comment]
Does anyone else have this problem? And can we then determine what they have in common with @yujiberra ?

I just installed cinnamon (on Debian) to see if that causes the problem, but it still works fine for me. Trying to find a way to reproduce this, because otherwise it will be hard to fix...

**Comment by dterrahe** [comment]
@TurboGit could we have a "reproduce: help needed" label or is there a better way to mark this?

**Comment by yujiberra** [comment]
@dterrahe 
Shoot, sorry, I investigated this further and discovered that it was due to imwheel, which I set up a long time ago and had forgotten about completely.

I'll add another comment once I've had a chance to figure out why it was only affecting certain mouse wheel combinations, but I'd say it's safe to close this. Thanks again for investigating!

**Comment by yujiberra** [comment]
In case anyone encountering the same problem looks at this, my `.imwheelrc` was set up like this in order to increase the mouse wheel speed:

```
".*"
None, Up, Button4, 2
None, Down, Button5, 2
```

but that breaks modifier combinations. I actually already had the following lines in order to make Alt + scroll and Shift + scroll work:

```
Shift_L, Up, Shift_L|Button4
Shift_L, Down, Shift_L|Button5
Alt_L,     Up,   Alt_L|Button4
Alt_L,     Down, Alt_L|Button5
```

In order to make the Ctrl+Alt + scroll combination mentioned in this issue work, the following needed to be added:

```
Alt_L|Control_L, Up, Alt_L|Control_L|Button4
Alt_L|Control_L, Down, Alt_L|Control_L|Button5
```

**Comment by dterrahe** [comment]
Thanks for coming back with the additional information. It is really much appreciated!
