### ISSUE TITLE
Renamed exports from 3.8.0 are missing some EXIF info

### ISSUE THREAD

**Issue by lphilpot** [darktable-org/darktable#11102]
See https://discuss.pixls.us/t/reduced-exif-in-renamed-export-images/29380

darktable 3.8.0 on Windows 11 

Auto-renamed exported images don't include all EXIF. For example:

```
exiftool IMG_3382.tif | wc -l
295

exiftool IMG_3382_01.tif | wc -l
64
```
...or...
```
exiftool IMG_3382.tif | findstr "Aperture"
Aperture Value                  : 12.9
Max Aperture                    : 3.4
Min Aperture                    : 25
Target Aperture                 : 13
Aperture                        : 13.0

exiftool IMG_3382_01.tif | findstr "Aperture"`

```
If the existing file is first renamed, the export then has full EXIF info.

Thanks.

**Comment by phweyland** [comment]
I cannot reproduce this so far.
I've tried with both nef and dng source files and I get the same exif data for the automatically created files (exported as jpg and tiff as well).
Darktable 3.9.0+416~g74ee19c3a on Dedian sid.

If you could you share the source file and both exif text files (created with exiv2 -PE imagefile please) I'll test further. TIA.

**Comment by lphilpot** [comment]
This is getting weird. I'm now running darktable 3.8.1, which I don't think had an metadata related changes. But when I convert the same CR3* twice, I now get metadata twice:

```
Z:\len\data\images\Our-photos\20220210_Beauregard_sunset\exported>exiv2 -PE IMG_3382.tif | wc -l
226

Z:\len\data\images\Our-photos\20220210_Beauregard_sunset\exported>exiv2 -PE IMG_3382_01.tif | wc -l
226
```
*After testing the other day I deleted superfluous files so I re-ran the tests just now. However, I also got an interesting post-conversion message from darktable both times (with the respective TIF file name each time): 

`could not export to file 'Z:\len\data\images\Our-photos\20220210_Beauregard_sunset/exported/IMG_3382.tif`

_(Z: is mapped to a Synology NAS and FWIW, it contained back **and** forward slashes as shown.)_

But both times the TIF exported successfully, by all appearances. 

Anyway, I'll attach the exiv2 output. I tried to attach the CR3 and sidecar, but they're not allowed by github. If needed you can get them (IMG_3382.CR3*) from https://drive.google.com/drive/folders/1G91_VpLsZHQarNSJS4Yf7Vn9PMYqXaPm?usp=sharing

**_But here's something else in case it's relevant._** Just last night I had issues with GIMP JPG exports not (always) containing EXIF:
https://discuss.pixls.us/t/exported-jpgs-are-missing-exif/29446
https://gitlab.gnome.org/GNOME/gimp/-/issues/7869

I mention this just on the unlikely chance there's something on my system causing this. It's a brand new Windows 11 laptop and I can't imagine what it could be, but... ? I've installed exiftool and exiv2, but nothing else EXIF related. There's darktable, GIMP, RawTherapee, SiriL, etc., etc., but nothing I can imagine that would interfere. 

_Maybe_ it's my system?? I don't want to kill troubleshooting but I also don't want to send anyone on a wild goose chase.

Any ideas ???

Thanks.

[IMG_3382_01_EXIF.txt](https://github.com/darktable-org/darktable/files/8074240/IMG_3382_01_EXIF.txt)
[IMG_3382_EXIF.txt](https://github.com/darktable-org/darktable/files/8074241/IMG_3382_EXIF.txt)

**Comment by Nilvus** [comment]
We've had some updates since so this is probably fixed. I so close. If you reproduce with last release (wait march as 4.2.1 will be out probably in a week or 2), ping me with new infos to reopen.
