### ISSUE TITLE
Edit EXIF (Image Information) data

### ISSUE THREAD

**Issue by jrickards** [darktable-org/darktable#11111]
**Is your feature request related to a problem? Please describe.**

I now split my photography between analog (Bronica GS-1, medium format film) and digital (Olympus). The EXIF data is automatic when I use my Olympus but I'd like to store EXIF data in the digital images created from scanned negatives. Yes, the exiftools commandline tool, I run Linux Mint, is an option but not an easy one to use so, in addition to viewing Image Information data, I'd like to be able to add it for my scanned negative files.

**Describe the solution you'd like**

Perhaps an Edit function for the Image Information panel would be sufficient

**Alternatives**

I've tried the exiftools commandline tool but it is cumbersome and even though I've added Aperture to the script, it doesn't show up in darktable's Image Information panel.

**Additional context**

**Comment by elstoc** [comment]
One of the basic principles of darktable is that it does not edit your raw files. I seem to recall this being discussed before and I don't think it's likely to happen.

**Comment by jrickards** [comment]
Understood but this information can be stored in the XML then passed on to
the exported file.

**Comment by every-good-name-is-already-taken** [comment]
I think something like LensTagger for Lightroom would be great. 
https://www.lenstagger.com/#primary

It also would be nice if you can select the lens at the import dialog.

**Comment by every-good-name-is-already-taken** [comment]
Thank you for your suggestion but this does not work for the collection.
I can use the tag but not the capture details / lens search function

**Comment by jrickards** [comment]
Through the new module, Negadoctor, there is now support for film photography but no support for creating EXIF data for the film negatives.

Please reconsider my request to enable EXIF editing. There can certainly be constraints such as: only able to edit blank "fields" so if Date has been populated, it can't be edited but if "Lens" has not been populated, it can be populated after which, it can't be changed.

**Comment by wpferguson** [comment]
This can be done with a Lua script.  Opening an issue there.
