### ISSUE TITLE
"show photos in subfolders' on/off in lighttable collections/folder

### ISSUE THREAD

**Issue by MaciekP123** [darktable-org/darktable#11126]
Hi,
I have my photos collected by year and then event and then some subdirs (raw, export, hdr, etc). When I click collections/folder and select any dir - it shows all the photos in that dir and all the others from all the subdirs. This is very hard to see/work on photos as they are sorted by dir already but are shown all at once.

I would like lighttable collections to work like any other regular file manager, so when I click a dir - it shows contents of that dir at -1 level, not all the files in all the subdirs.

In Lightroom its available as 'show photos in subfolders'
https://youtu.be/5LZSqvXBwBw?t=52

Ive read about searches, narrowing them down but it seems i would need to create each narrow per subfolder which is veeeery painful. Just working as regular file manager would be heaven :)

**Comment by MaciekP123** [comment]
Bloody hell. I wasnt expecting it to be so simple.
Reviewing manual earlier but somehow missed that. My fault, sorry for bothering.

Anyway - is there a way to invert it so by default it would work as 'shift-click'?

**Comment by elstoc** [comment]
IIRC that's how it used to work and it was changed for version 3.8.0

**Comment by MaciekP123** [comment]
It seems both ways are needed then.
Toggle switch in options would satisfy both worlds :)

**Comment by MaciekP123** [comment]
Is there a way to file RFE, so it could be considered 'officially'?
