### ISSUE TITLE
FR: Performance_Configuration

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11138]
**Is your feature request related to a problem? Please describe.**

Once the performance_configuration gets activated and a popup appears, you only have the choice between *no* and *yes*
1) If you chose "yes" you barely notice, what has been changed (I know..... backup)
2) if you chose "no" you will never beeing asked again unless new attempt by dt
3) if you chose "no" in darktablerc the "performance_configuration_version_completed=" getting incremented/updated anyway

**Describe the solution you'd like**

To 1) have an auto-backup like "cp darktable dartable_`date -I`"
To 2) like you can find on many other softwares "ask me later" (maybe with a desired time or amount of starts of dt)
To 3) should not be, because it is somehow not _really_ true...

 @johnny-bit may I ping you here?

**Comment by AxelG-DE** [comment]
@jenshannoschwalm as you are working on performance issues, I donno this might be interesting for you or not...

**Comment by jenshannoschwalm** [comment]
After #11167 the performance_config stuff gets less important and it might very well be we can rid of it at all.

**Comment by jenshannoschwalm** [comment]
@AxelG-DE i think this issue has been fixed. Closing here ???

**Comment by AxelG-DE** [comment]
Seems you are right :)
