### ISSUE TITLE
Nikon D3s

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#11131]
Hi devs,

I have just uploaded the 6 required raw files to raw.pixls.us. Should I upload the files to this issue as well?

Regards Michael.

**Comment by Nilvus** [comment]
Thanks for posting samples on raw.pixl.us. That's the good place and no need to post them here.

But think about searching here before posting. There's already an issue opened here (with exact same title!). See: #10920

As it is so a duplicate, I close this one. Just note that adding camera support could take some times. Few people spent time on that and darktable is a free software made by people in their free time.
