### ISSUE TITLE
cache_memory set to huge value, based on available disk space

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#11139]
`cache_memory` is set based on available **disk** space, without taking available **RAM** into account (with a few hundred GB free disk space, this would require **hundreds of GB of RAM**, too):

https://github.com/darktable-org/darktable/blob/a3875bd56efda803b864b88686023eb0853e3687/src/common/darktable.c#L1656-L1658

See, for example:
https://discuss.pixls.us/t/run-performance-configuration/29427/12

**Comment by kofa73** [comment]
Maybe if we can agree on a way to fix it (e.g. impose a limit of 10% of available memory, or something like that), it could be included in #11119 ?
`DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION` may need to be incremented again.

**Comment by jenshannoschwalm** [comment]
Indeed the current stuff is wrong.
Will fix that too in #11167

**Comment by jenshannoschwalm** [comment]
@kofa73 you might want to test #11167 :-)

**Comment by jenshannoschwalm** [comment]
@kofa closing this?
