### ISSUE TITLE
Some Fuji Film GFX100S images do not load

### ISSUE THREAD

**Issue by SteveLamont** [darktable-org/darktable#11145]
**Did you buy darktable from an application store ?**

No.

**Describe the bug/issue**

Some Fuji Film GFX100S images do not load. Filed per instructions at PIXLS.US.

I note that there is a difference in the flags field on images which load and those which do not:

flags: 1...r..ap...r  load

flags: 1......ap....  does not load

**To Reproduce**

I have uploaded an example of an image which does not load to PIXLS.US.

**Expected behavior**

It should obviously load.

**Screenshots**

N/A

**Screencast**

N/A

**Which commit introduced the error**=

3.6.0

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc

1:3.6.0-0build1~ubuntu20.10

darktable --version
this is darktable 3.6.0
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 7.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx

uname -a
Linux george 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* Linux - Distro    : e.g. Ubuntu 18.4

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish

* Memory            : 

cat /proc/meminfo 
MemTotal:       131574536 kB

* Graphics card     : 
* 
* sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: GA102 [GeForce RTX 3090]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:21:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:417 memory:e0000000-e0ffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:6000(size=128) memory:e1000000-e107ffff

* Graphics driver   : 

See above.

* OpenCL installed  : 

Yes

* OpenCL activated  : 

Yes

* Xorg              : 

vendor string:    The X.Org Foundation
vendor release number:    12013000
X.Org version: 1.20.13

* Desktop           : 

xfce4

* GTK+              :

 libgtk-3-0:amd64  3.24.30-1ubuntu1 amd64 

* gcc               : 
 
gcc --version
gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0

* cflags            : 

N/A

* CMAKE_BUILD_TYPE  : 

N/A

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**

N/A

 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 
Fails to read some RAF files but not others.

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 
N/A

 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 
N/A

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 
N/A

 - Do you use lua scripts?
 
No.

   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Compressed RAFs are not yet supported.

See also https://github.com/darktable-org/darktable/issues/11071
