### ISSUE TITLE
GLib-GIO-CRITICAL errors when opening import dialog windows

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#11144]
**Describe the bug/issue**

Some Glib critical error when opening import dialog window

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. launch darktable from Terminal
1. In import module, click on buttons to import photos (add to library or copy & import) or even launch it with shorcuts
2. Just see on Terminal those following lines appear:

```
(darktable:183558): GLib-GIO-CRITICAL **: 19:25:01.253: g_file_enumerator_next_file: assertion 'G_IS_FILE_ENUMERATOR (enumerator)' failed

(darktable:183558): GLib-GIO-CRITICAL **: 19:25:01.358: g_file_enumerator_next_file: assertion 'G_IS_FILE_ENUMERATOR (enumerator)' failed
```

**Expected behavior**

No error. Seems to not be critical for darktable use but maybe some improvement needed to darktable code to avoid those errors and maybe prevent other issues on some specific cases.

Or could be not related directly to darktable but Glib. If so and can't be fixed here, I will close this issue. @phweyland: as you worked on that PR, what do you think about that issue?

**Platform**

* darktable version : actual master
* Linux - Distro    : Debian Sid

**Comment by phweyland** [comment]
Could you list the places and their path, please ?

**Comment by TurboGit** [comment]
I have seen that, wanted to reproduce and was not able... @Nilvus by all mean if you can reproduce systematically let's get all needed information.

**Comment by HansBull** [comment]
Probably we need to check that dir_files != NULL before import.c@690

**Comment by phweyland** [comment]
> Probably we need to check that dir_files != NULL before import.c@690 and 937

Yes, doesn't hurt.

**Comment by Nilvus** [comment]
My places were simple and with only default ones and my LUMIX cards (I connect my camera with USB). I think those lines appears when my camera is connected. I do not test that but @HansBull PR fix that issue. No more errors lines, with same places. Thanks @HansBull for your fix.

**Comment by TurboGit** [comment]
@Nilvus : Good to see this fixed on your side indeed.
