### ISSUE TITLE
Import: COMMIT issue

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#11152]
**Describe the bug/issue**
Importing images (add to library) the console shows recursively this message:
```
sqlite3 error: /home/philippe/git/darktable/src/common/image.c:1652, function _image_import_internal(), query "COMMIT": cannot commit - no transaction is active
sqlite3 error: /home/philippe/git/darktable/src/common/image.c:1652, function _image_import_internal(), query "COMMIT": cannot commit - no transaction is active
```

**Which commit introduced the error**
Probably related to PR #11136

**Platform**

* darktable version : 3.9.0+416~g74ee19c3a
* Linux - Distro    : Debian sid

**Comment by HansBull** [comment]
Can't reproduce (sqlite 3.22, Ubuntu 18.04, kernel 5.8.13, master).
Anyone else?

**Comment by elstoc** [comment]
I see the same. It only happens when importing new images, not if the imported images are already in the db.

**Comment by TurboGit** [comment]
I have just push a fix, don't really know why using dt debug routines was not working. But well... don't have time to dig further.

**Comment by TurboGit** [comment]
Hum... embarrassing I just have removed the error message :)

**Comment by TurboGit** [comment]
Ok, understood this is because between the new added transaction we have tow other transactions in exif.cc. I don't think SQLITE3 supports nested transactions.

**Comment by TurboGit** [comment]
See #11155.
