### ISSUE TITLE
Export from Tiff missing metadata

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#11150]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Edited a 16bit tiff file in darkroom, exported jpeg, only to find the metadata which was input in darktable (title, description, creator, tags) missing from the jpeg. In export module preferences the only two boxes I have checked are 'metadata' and 'tags'. There are numerous redefined tags, but I have used those in exporting images before, both raw and tiffs, without problem.

I can't share the tiff file, but I can share the xmp:
[exportissue_05.tif.xmp.txt](https://github.com/darktable-org/darktable/files/8080608/exportissue_05.tif.xmp.txt)

(Not sure if its related to the problem and there is an issue with the metadata module, but when I duplicated the image (v0), changed the input text in metadata module on duplicated image (v5), duplicated the original again, then loaded the sidecar from the duplicate in overwrite mode (v5), the text in metadata did not change to match that of the loaded v5 side car, but stayed the same as per the v0 sidecar).

**Expected behavior**

jpeg exports with metadata and tags, when those boxes are checked in export module preferences.

**Platform**

* darktable version : e.g. 3.8.0~git59.e758e1366c-1
* OS                : e.g. Linux - kernel 5.13.0-27-generic
* Linux - Distro    : e.g. Mint 20.2 Cinammon 5.0.7
* Memory            : 32gb
* Graphics card     : rtx 2060
* OpenCL installed  : y
* OpenCL activated  : y

 - Can you reproduce with another darktable version(s)? yes with 3.8.0~git9.3034322bbd-1 before i updated.
 - Can you reproduce with a RAW or Jpeg or both? Has only happened on tiff, and even then, not on every tiff.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? I duplicated original, discard history, and exported jpeg with same settings. Issue remained.
 - Do you use lua scripts? no

**Comment by phweyland** [comment]
I've tried to export a nef file (with current master), with some metadata and some tags and your export settings. I get them in the exported file.

> only to find the metadata which was input in darktable (title, description, creator, tags) missing from the jpeg

Just to be sure. You mean that you don't get the expected metadata in the exported jpeg, right ?

Is that valid for all kinds of raw, only for a tiff one, only for this particular tiff ?
Is the exported image a duplicate ?
Is it automatically renamed by the export module ?

**Comment by SoupyGit** [comment]
Thanks for your reply. Yes I don't get expected metadata (title, description, creator, tags), which were added in darktable, in exported jpeg.

Doesn't happen with raw, only with tiff, and not every tiff. If it is something wrong with the tiff file, I Wonder what I can look for to check?

It happens whether the export is original image or duplicate.

Yes export module automatically renames it to the title given in metadata module, and this works correctly.

**Comment by phweyland** [comment]
Thanks for the answers.
> If it is something wrong with the tiff file, I Wonder what I can look for to check?

If you could check with another file type than tiff... nef, cr2, ...

**Comment by SoupyGit** [comment]
"If you could check with another file type than tiff... nef, cr2, ..."

Have tried it on many nefs, it works fine.

Further troubleshooting:

Test 1)
Import 3 other tiffs from same folder into darktable. A few tags, and metadata are added in import module. Export using same settings as previous example (which includes title change based on metadata). Same result. Metadata and tags not exported in jpeg.

Test 2)
On same 3 tiffs I select a different preset in export module (again with just ‘metadata’ and ‘tags’ selected in preferences, one that does not change the file name. Eg. It just saves /$(FILE_NAME). Same result. Metadata and tags not exported in jpeg.

This seems to rule out name change as the problem.

Test 3)
I import another tiff from a different folder, using the same preset as Test 1. It works. Metadata and tags export as expect.

This seems to suggest the problem occurs only on certain tiff files.

Test 4)
I open a problematic tiff file in Krita, change nothing, export as tiff, then open this new version in darktable. Do the same as per Test 1, and it works! Metadata and tags export as expected.

As a workaround, this solves the problem for me personally, however does not fix whatever issue darktable had with exporting metadata to the original tiff. If you know of an online image host that allows storage of 50mb tiff files in a free account, I can share a problematic tiff with you.

**Comment by phweyland** [comment]
Great search ! Thanks

In failing cases, do you see the automatic metadata & tags in the respective modules ? In other words, are they really set at import time ?

Could share the results of `exiv2 -PEXI filename > log` for both a failing and not failing tiff ?

**Comment by SoupyGit** [comment]
"In failing cases, do you see the automatic metadata & tags in the respective modules ? In other words, are they really set at import time ?"

Yes, I see them, that works fine.

"Could you share the results of exiv2 -PEXI filename > log for both a failing and not failing tiff ?"

Hm might need a little help here. That command returns nothing. I guess I have to specify the path before typing exiv2? But I don't know where exiv2 is located. Any idea? Mint 20.2

**Comment by knoedelsalat** [comment]
Just came across this issue while editing some high-res medium format scans in DT 5.0.1

When I export to JPG, tags are not being attached reliably. Funny enough it works on some of the files, although I have not been able to figure out why.

Test files are here:
https://drive.google.com/drive/folders/1YOYDx8EodSLD6qGs5TnsSNm0NtYNvu2G

Using the same export settings the image ending on ...0003 exports nicely with tags attached, the one ending on ...0007 gets exported without tags and without rating.

Sorry for reopening & hope this helps!
