### ISSUE TITLE
D.T. 3.8.1 Missing feature on Mac Version: export window missing a button for creating a new folder

### ISSUE THREAD

**Issue by hausio** [darktable-org/darktable#11170]
A comfortable way to export new files by creating a new folder in the export window dialogue is missing in D.T. 3.8.1. for Mac. The same version 3.8.1 on Linux still has this feature. (a small icon in the upper right section of the export window.)

It would be nice to have that feature back on all platforms.

And you do a really great job! Thank you guys!

hp

**Comment by MStraeten** [comment]
simply type shift+cmd+n to create a new folder
