### ISSUE TITLE
FR: Remove integer primary key on tags

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11171]
The separation between the `data.db` and `library.db` databases is somewhat problematic for image tags. While I can see the use case for storing the tag dictionary independently of the image library, the fact that the `data.tags` and `library.tagged_images` tables are connected by an integer (with the tag name only available from `data.db`) is not ideal.

Since the tag name is also a unique identifier in `data.tags` I would propose storing the tag name in `library.tagged_images` instead of the integer id. This would allow us to create some views within library.db that might make SQL a little less verbose within darktable itself and it would also allow us to recreate a tag dictionary from a library database in the case of `data.db` becoming corrupt.

As far as I'm aware it is not possible to write internal database views that connect two separate sqlite databases, especially when the location of the library database can be changed on-the-fly (with the `--library` option).

**Comment by phweyland** [comment]
>  While I can see the use case for storing the tag dictionary independently of the image library

Could you describe this a bit more ?

> I would propose storing the tag name in library.tagged_images instead of the integer id.

Moving the tagname from the `data.tags` table where they are unique to `library.tagged_images` implies they will be duplicated as many times as the tags are attached. I'm not comfortable with that but I may wrong.
Then I'm not sure that a string index would be as performant as an integer one.

I don't know why we have two separated db. I've seen some arguments for better performance but haven't seen any measurement. 
If the creation of view is the goal, it could be worth to try to move the `tags` table back to `library`.

**Comment by elstoc** [comment]
> Could you describe this a bit more?

> I don't know why we have two separated db

> it could be worth to try to move the tags table back to library

Some people like to use multiple library databases or not use a library db at all (`:memory:`), so having an independent list of all used tags would be useful in this scenario. Regardless of the library database, the same data.db is always used (there is no option to run darktable with a different data.db unless you use a whole new configuration dir).

I agree that an alternative would be to combine the two databases, or to move the tags table. These are both valid solutions as well but for the above use case,  and I think removing the independent tag dictionary might be a big issue for some people.

> they will be duplicated as many times as the tags are attached

> Then I'm not sure that a string index would be as performant

My thought was to keep an (essentially independent) tag dictionary in data.db and, yes, have the strings repeated in `tagged_images` for each image they're attached to. It may well be less performant but it's really not great practice to have foreign key constraints span multiple databases, since that means they can't be enforced.

**Comment by phweyland** [comment]
> it's really not great practice to have foreign key constraints span multiple databases

Sure !

> Some people like to use multiple library databases or not use a library db at all (:memory:), so having an independent list of all used tags would be useful in this scenario. 

The :memory: users should not use any tag, but for multiple library.db that makes sense.
I got the idea. Thanks.

**Comment by elstoc** [comment]
> The :memory: users should not use any tag

Really? Are tags not stored in XMP files?

**Comment by phweyland** [comment]
The idea of having an independent tag dictionary is appealing. I've even seen some request to have several dictionaries ...
Thinking about your proposal some difficulties come up.
- what about tag renaming ?
- lua API is tagid based
- the tag collection images order is stored in tagged_images table but the type of order is in flags field of tags table.

Deriving a bit your suggestion we may split the tags table, to keep a numerical index inside `library` and interface `data.tags` with `tagname` instead of `tagid`. 
Not yet quite reassured about tag renaming but that may help a bit ...

**Comment by elstoc** [comment]
> split the tags table, to keep a numerical index inside library and interface data.tags with tagname instead of tagid

I'm not sure I fully understand your proposal. Are you suggesting having an indexed tags table in library.db (to interface with tagged_images) and then a tag_dictionary (or something) in data.db without a numeric index?

**Comment by phweyland** [comment]
> Are you suggesting having an indexed tags table in library.db (to interface with tagged_images) and then a tag_dictionary (or something) in data.db without a numeric index?

Yes. Keeping images related information in library and tags only related information in data.

**Comment by reitger** [comment]
Why not make data.db movable with library.db if the user wants it. Default is to keep data.db in the default place which offers as intented to have one tag list enven for different library.dbs if you use all librarys on the same computer. If you use library.db with different computes or accounts  - and only then - it would cause the problem and in that case you can avoid that by keeping data.db in the same location as library.db?
