### ISSUE TITLE
Import changes case of path which leads to duplicate directory entries in collection (Win 10)

### ISSUE THREAD

**Issue by ChristianBirzer** [darktable-org/darktable#11188]
**Describe the bug/issue**
I managed to get multiple entries for the same directory in the collection module by importing, copy&import and searching filmroll directory. It seems that (not 100% sure)
- search filmroll takes the upper/lower case from the file dialog
- copy & import converts the path to all lowercase

**To Reproduce**
Copy some file to a directory with a mixed case name
import them from that directory
search the filmroll in that directory
Copy & import a bunch of photos from an other location into that same directory

**Expected behavior**
In the collections module, set to "directory view" you have only one directory (preferable with the mixed case naming)

**Actual behaviour**
There are multiple entries with different case for one directory

**Screenshots**
![grafik](https://user-images.githubusercontent.com/96134139/154848412-7c861e23-6206-4d68-b9c9-490540d88bfd.png)

For the copy&import I used the following pattern:
![grafik](https://user-images.githubusercontent.com/96134139/154848906-f350cbac-f3cc-43a1-ba8c-1ac04fe668ef.png)

**Which commit introduced the error**
Noticed this behavior with the official 3.8.1 and could reproduce it with the 3.9.0 6d18168b1
At least the convert to lowercase came with 6f072ee

**Platform**

* darktable version : 3.9.0 6d18168b1
* OS                : Windows 10 21H1

**Additional context**
When I find some time I'll do more research about this problem. If someone has some hints where to look please let me know 😉

**Comment by phweyland** [comment]
Have windows became case sensitive? 
Are the upper case names coming from a previous version of dt? 
In any case import should follow the case chosen by the user, if possible.

**Comment by ChristianBirzer** [comment]
> Have windows became case sensitive?
> Are the upper case names coming from a previous version of dt?

No, windows does still not really care about the case but it will pass the case to the application. (I think) the problem here is that the path is converted to lower case in some parts an kept as it is in others. The dt database seems to be case sensitive (what makes totally sense when thinking about a linux env)

To reproduce:

- I'll start with a completely empty database.
- I have a folder structure `F:\Temp\Bilder zum Testen\2020` 
![grafik](https://user-images.githubusercontent.com/96134139/155563383-92f9a276-b2d9-4129-a094-94fd491ae3c6.png)
- _add to library_ from a folder inside
![grafik](https://user-images.githubusercontent.com/96134139/155563460-9e53147c-12b3-4c12-ad66-996e00426d0a.png)
- the resulting film roll (and directory) will have the exact case like it is on my disk
![grafik](https://user-images.githubusercontent.com/96134139/155563579-780e20ca-b199-4038-bb8b-975edff517f3.png)
- Then I'll add some more pictures with the copy&import function to this directory or at least one in the same folder structure (the base directory has the same upper/lower case like the directories on disk:
![grafik](https://user-images.githubusercontent.com/96134139/155563847-ee4506d7-aa7c-4ccf-9bcd-3c880d8bebce.png)
- but this time, the path is converted to lower case:
![grafik](https://user-images.githubusercontent.com/96134139/155564056-f6a0780e-44c1-47b7-a60c-da2513b77959.png)
- In the folder view of the collections panel this leads to two "different" folders that are in fact the same
![grafik](https://user-images.githubusercontent.com/96134139/155564222-331e48d9-89c8-4275-a816-20c23d666fa7.png)

BTW: I prefer the one with the original case because it is better readable than the lower case one.

**Comment by phweyland** [comment]
Thanks for the detailled description. I'll try to fix this.

**Comment by Yardlongbean** [comment]
I too can confirm that I also found that any new folder names are all converted to lower case on copy and import in Windows 10.
![image](https://user-images.githubusercontent.com/41417273/156731256-fd81ceb8-c655-4a30-ab0c-302524ec40d2.png)
When I do this, any new folders within existing folders will all be lower case. File names still seems to respect any capitalisation
This will generate a folder
F:\Raw photos\2022\brandon woods evening feb
not
F:\Raw photos\2022\Brandon Woods Evening Feb
as expected
(The folder Raw photos already exists so is not changed)

This behaviour appeared  in version 3.8.1. 
In version 3.8 the folder names were named as expected.

**Comment by Yardlongbean** [comment]
+1 
I also observe this behaviour in Windows 10. 
First noticed in 3.8.1
3.8 worked fine.
Thanks for all your work!

**Comment by TurboGit** [comment]
@ChristianBirzer : Can you test PR #11270? TIA.

**Comment by ChristianBirzer** [comment]
Regarding the lower case issue, it seems to be fixed.

But there is a new strange behavior with the placeholders like $(YEAR) etc. (not by this PR, it's also in the commit before)
These seem to be discarded (or replaced by an empty string).
Was there something changed in the names of these variables?
![grafik](https://user-images.githubusercontent.com/96134139/156931335-d0b4d617-161b-41e1-a456-0191f8283969.png)
![grafik](https://user-images.githubusercontent.com/96134139/156931345-6035d28c-c3e2-461f-9ac2-8d0b4b9fce07.png)
Notice the "--" in the directory name
The variables $(EXIF.YEAR), $(EXIF.MONTH) and $(EXIF.DAY) work fine (just tested these three so far)
