### ISSUE TITLE
Exported files are missing all camera exif tags

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#11181]
**Describe the bug/issue**

Since 3.8.1 darktable exports JPEG files without original exif tags.

**To Reproduce**

Export:
- File format: JPEG 8 bit
- global options: resize 0x0, hq resampling, intent: image settings, style: none, profile: sRGB.

**Expected behavior**

Because the original raw file had all this information, the exported JPEG should have exif tags such as lens, camera, aperture, shutter speed, ISO. 

Applies to all raw sorts of raw files that I have. DNG, RW2, RAF.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.8.1
* OS                :  linux
* Linux - Distro    : gentoo
* Memory            : 24
* Graphics card     : nvidia
* Graphics driver   : blob
* OpenCL installed  : y
* OpenCL activated  : y
* Xorg              : y
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

Darktable is reading this metadata just fine, it shows in the "Image information" module for instance and in the filmstrip and the other usual places.

**Comment by Nilvus** [comment]
It's an option. Just check your export settings in the module and you can set what infos to export or not. Read export section in the manual is also a goood thing to do.

Think about closing this issue after.

**Comment by progo** [comment]
> It's an option. Just check your export settings in the module and you can set what infos to export or not. Read export section in the manual is also a goood thing to do.

Ok, so it seems. It was unexpected to see such a "breaking" change going from  3.8.0 to 3.8.1. The export settings, after I found them finally (also a bit obscured but that's another matter), had the exif tags disabled.

Closing this nonissue with a "RTFM" label.

**Comment by Nilvus** [comment]
> > It's an option. Just check your export settings in the module and you can set what infos to export or not. Read export section in the manual is also a goood thing to do.
> 
> Ok, so it seems. It was unexpected to see such a "breaking" change going from 3.8.0 to 3.8.1. The export settings, after I found them finally (also a bit obscured but that's another matter), had the exif tags disabled.
> 
> Closing this nonissue with a "RTFM" label.

Nothing had changed on that part between 3.8.0 and 3.8.1

**Comment by progo** [comment]
> Nothing had changed on that part between 3.8.0 and 3.8.1

Okay, makes sense. It must have been something with the distribution package then. The exif data suddenly stopped exporting some time within the last 7 days and I've been using the 3.8 since Christmas.
