### ISSUE TITLE
[Feature Request] Contrast Equalizer (+optional curve) for masks

### ISSUE THREAD

**Issue by ScissorHill** [darktable-org/darktable#11187]
**Is your feature request related to a problem? Please describe.**

In principle, it should be possible to use the _details threshold_ slider to generate a mask, that maps to image depth (distance to camera). The further away from focal plane, the less detail an area of the image should have, and vice versa. For example, used with say _blurs_ or _retouch_ , this should allow for creation of an enhanced bokeh effect, similar to the reduced depth of field that comes from a faster lens.

In practice, the details-depth mapping is often too noisy to be useful. Variance of detail at the same depth be more than variance of detail at different depths. For example, a leaf in the focal plane can have some areas with less detail than another leaf way behind the focal plane.

Tweaking _details threshold_ + _feathering_ + _mask contrast_ +_mask opacity_  helps, but blotchy artefacts quite often cannot be eliminated.  

There's a tradeoff between two extremes:

- Low-contrast mask, very homogeneous, almost all-or-none. So no blotchiness, but everything outside the focal plane has the same mask value, so depth information is lost. 
- High-contrast mask, retains depth information, but has blotchy artefacts, i.e. objects in the same plane have huge contrast variation in the mask.

Both of these make any downstream effects look unnatural, and unlike what you'd see from a faster lens.

**Describe the solution you'd like**

- **Mask contrast equalizer.** Basically a replacement for the mask contrast slider. This would enable increasing contrast at coarse resolution while removing contrast at fine resolution.  So you can have high mask contrast between two objects at different depths, but less contrast within each object. 
- (Optional) A curve that can be applied to the output of the above equalizer. Because focus is unlikely to have a linear relationship with depth. This would make the effect of downstream modules such as Blurs more realistic.

**Alternatives**

Have multiple dedicated mask pixelpipes! Which can be brought into the main pixelpipe at different places. This would be a far more powerful solution, but its more of a long-term solution, obviously.

**Additional context**

Example:

Original image:
![image](https://user-images.githubusercontent.com/26180991/154837328-3fad87d2-83e9-4f36-92cf-d62917af375e.png)

Contrast too low - less blotchy, but foreground/background poorly separated:
![image](https://user-images.githubusercontent.com/26180991/154837405-28b074eb-5fc8-4f6c-a451-2d89b7e3ec8e.png)

Contrast too high - foreground/ background well separated, but background is too blotchy:
![image](https://user-images.githubusercontent.com/26180991/154837524-fd9f2d4b-776e-4692-88f3-aac49f7a9669.png)

The details threshold feature is, even in its current state, quite useful. Dealing with busy background is a every bird photographer's dream! It's a very common use case, and since DT 3.8, this feature has now become central to my workflow.

And yet it could be so, so much better. In the above example, note how the blotchy artefacts are at a fine scale, relative to the bird and the bushes. A contrast equalizer would help eliminate those artefacts, and give clear separation between foreground and background. Ideally even have the intermediate bushes show up as another zone as well.

**Comment by jenshannoschwalm** [comment]
I implemented the details mask in dt, what we currently do is calculating detail via a scharr operator (very good but only using a 3x3 area to calculate).

How valuable would a selectable radius for detail detection be for your workflow?

**Comment by ScissorHill** [comment]
> How valuable would a selectable radius for detail detection be for your workflow?

Sounds quite intriguing, and I'd be happy to test it out. 

That being said, wavelet decomposition on masks intuitively seems like a flexible and powerful idea - hope to see it implemented in the near future!

Meanwhile, selectable radius for detail is more of a low-hanging fruit, which we should definitely give a shot, IMHO.

**Comment by AxelG-DE** [comment]
@ScissorHill #7628 kind of initiated it. I wanted to limit ContrastEQ to the real sharp part, but also want to simulate faster lenses, e.g. for my MFT cams

**Comment by aurelienpierre** [comment]
> In principle, it should be possible to use the details threshold slider to generate a mask, that maps to image depth (distance to camera).

Theory says no. The magnitude of the laplacian only gives a rough estimation of distance relatively to focusing distance, not relatively to camera. And this metric will always return "sharp" for contrasty edges like ground and sky.

> Mask contrast equalizer. Basically a replacement for the mask contrast slider. This would enable increasing contrast at coarse resolution while removing contrast at fine resolution. So you can have high mask contrast between two objects at different depths, but less contrast within each object.

I'm opposed to that on the ground that the masking options are already too crowded and messy UI.

> Dealing with busy background is a every bird photographer's dream! It's a very common use case, and since DT 3.8, this feature has now become central to my workflow.

Use drawn masks to isolate the foreground from the background.

**Comment by ScissorHill** [comment]
I've noticed that aggressively applying raw denoise does wonders for the details mask. Notice how the mask now correlates fairly well to distance from focal plane, as compared to before:
![4](https://user-images.githubusercontent.com/26180991/155445104-bf7b3994-f8d7-4bb3-94fd-4cc16119eb5c.png)
![5](https://user-images.githubusercontent.com/26180991/155445116-ef35630d-c0bb-4cc8-8991-4f954e65aa7a.png)

So it looks like just a matter of denoising before details mask. I would be very happy with this result in itself. My only concern is that I may have paid a heavy price in terms of loss of detail. 

If we could have an instance of raw denoise - that only affects details mask but not the pixelpipe - that would be ideal! Even better than contrast EQ on the mask.

Or is it possible that optimising raw denoise for details mask would automatically optimise for image quality as well?
