### ISSUE TITLE
combobox too small in the collections panel

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11183]
**Describe the bug/issue**
I'm not sure what commit introduce this issue but now the combobox in the collections panel it is too small.
Previous version of dt had the combobox fine.

**Screenshots**
![Screenshot-20220219112124-356x286](https://user-images.githubusercontent.com/67672868/154809561-85ea609a-659d-4a50-8d7a-2b290fea5f95.png)

![Screenshot-20220219113123-354x280](https://user-images.githubusercontent.com/67672868/154809687-049eb3d2-c70a-421e-8a6d-8f562a252a8a.png)

**Platform**

darktable version : 3.9.0~git439.a3525ed597-7332.1
OS: Fedora Linux 35 (Workstation Edition) x86_64
OS Type: 64-bit
Host: Gigabyte Technology Co., Ltd. Z390 AORUS MASTER
Kernel: 5.12.17-300.fc34.x86_64
Uptime: 3 hours, 31 mins 
Packages: 3032 (rpm), 25 (flatpak)
Shell: zsh 5.8.1
Resolution: 3840x2160
DE: GNOME 41.4
WM: Mutter
WM Theme: Materia-dark-compact
Theme: Mc-OS-Transparent-1.3 [GTK2/3]
Icons: Os-Catalina-icons-master [GTK2/3]
Terminal: gnome-terminal
CPU: Intel® Core™ i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Nvidia Driver Version: 465.19.01
Memory: 4194MiB / 32036MiB
OpenCL installed: yes
OpenCL activated: yes

**Comment by AlicVB** [comment]
yep. I fear it's due to the bauhaus size computing. but not sure it's worth the pain to fix this specific now, considering that there will be change in this area soon...

**Comment by Nilvus** [comment]
> yep. I fear it's due to the bauhaus size computing. but not sure it's worth the pain to fix this specific now, considering that there will be change in this area soon...

I hate bauhaus widget. So much issues on them...

**Comment by da-phil** [comment]
I was about to write about the same issue, it has become really hard to use those fields for filtering without enlarging the whole panel substantially :/

**Comment by TurboGit** [comment]
And I kindly remind that any user of the master branch must be prepared for this kind of issues. It can also happen that we broke edits, it has happened one time so that's not theory. We do our best to have a master working but we certainly cannot guarantee more than that.

**Comment by da-phil** [comment]
No worries @TurboGit, I'm fully aware of that and by constantly using master I try my best to be a good beta-tester ;)

**Comment by difrkaguilar** [comment]
> No worries @TurboGit, I'm fully aware of that and by constantly using master I try my best to be a good beta-tester ;)

So do I ;)

**Comment by Nilvus** [comment]
@AlicVB PR #11066 fix this issue.
