### ISSUE TITLE
Windows log file location issue

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#11191]
On windows the debug output ( -d option) is written to the cache directory:

C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt

But when changing the cache directory with option --cachedir the file is still written in the old directory.

Version: 3.8.1
Windows 10

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I'm closing it because it's a very minor issue.

**Comment by kmilos** [comment]
I think cachedir is for thumbnails only.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
And also for storing the **opencl** kernels.
A better location for the log file is IMHO the %TEMP% directory.
