### ISSUE TITLE
It is possible to set tags in the darktable namespace, but not to remove them

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#11193]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

As the title says. Background: I am experimenting with ignoring jpeg decompression errors for particular pictures, and I tried to use a tag in the “darktable” tag namespace to control darktable's error handling. It is possible to set a tag, e.g. “darktable|test”, by using the shortcut ctrl-t. However, it does not seem possible to remove this tag from the pictures, as it does not show up in the tagging module.

**To Reproduce**

1. Select a picture in the lighttable
2. Press ctrl-t
3. Write “darktable|test”
4. The tag appears in the collections module under “tagging”, but not in the tagging module.

**Expected behavior**

There are two possibilities, either adding tags in the “darktable” namespace should be prohibited (the solution I favour less), or there should be an option to show “hidden” tags in the tagging module. I did not find such an option, neither in the config, nor in the module itself. This solution would be preferred by me. However, it seems the tags in this namespace are purely dynamical, such that it probably makes more sense to define a different namespace for “real” tags that control darktable behavior, and only prohibit to add tags to the “darktable” namespace.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/16524534/154937798-d80419b2-4e39-411c-82a2-be66b72e2546.png)

**Which commit introduced the error**

Not sure if this behavior ever changed.

**Platform**

* darktable version : 2.7.0+11769~g771d6f352
* OS                : Linux kernel 5.13.0-27-generic
* Linux - Distro    : Ubuntu 21.10
* Memory            : 8 GB
* Graphics card     : n/a
* Graphics driver   : n/a
* OpenCL installed  : n/a
* OpenCL activated  : no
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by gi-man** [comment]
Did you try to press the checkmark button to the right of Detach (entfernen)?

**Comment by spaceChRiS** [comment]
You are correct, I can see them. A classical case of RTFM. However, I still cannot remove these tags as I cannot select them.

**Comment by phweyland** [comment]
darktable|XXXX tags are not free user tags.
The bug here is to let the user create one...
They are not managed as the user tags. So I don't think it's a good idea to open this.

**Comment by phweyland** [comment]
> Should I close this and add a new issue or is this issue enough to track this topic?

I think the way to go is to prevent the direct creation of darktable tags by the user.
If no protest about this I can do it. And this issue is enough to follow up.

**Comment by phweyland** [comment]
@TurboGit Pascal, Nobody has protested. Do you think I can I forbid manual creation of darktable tags ?
