### ISSUE TITLE
FR: make $(MAKER) and $(MODEL) available at import time.

### ISSUE THREAD

**Issue by badkernel** [darktable-org/darktable#11209]
Hello

Came across this minor issue with darktable 3.8 variables on MacOS 12.2.1 when importing images where $(MAKER) and $(MODEL) and not assigned.

I'm using following variables when importing images to external SSD:
**$(EXIF_DAY)-$(EXIF_HOUR)$(EXIF_MINUTE)$(EXIF_SECOND)-$(EXIF_MONTH)-$(EXIF_YEAR)-$(MAKER)-$(MODEL).$(FILE_EXTENSION)** 

File name result looks like this: 
17-.21_53_51-02-2022--.JPG (nothing between last two hyphen)

Expected result:
17-.21_53_51-02-2022-Fujifilm-X-pro1.JPG

I can see details in image information module but they are "skipped" when importing
[darktable_imagemodule_screenshot](https://freeimage.host/i/1ndwOv)

**Comment by phweyland** [comment]
As far as I know only date time are the only exif information available at import time.
This said this is a feature which could be added.

**Comment by phweyland** [comment]
> how do I go about requesting this to be added in next version of Darktable ?

Change the title of the issue to FR: make xxx available at import time.


> In manual for Darktable 3.8 there are variables that I mentioned in my question so I assumed that these can be used when importing.

See the [import](https://docs.darktable.org/usermanual/3.8/en/preferences-settings/import/) doc.
