### ISSUE TITLE
FR: history stack can be re-ordered

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11202]
First of all: this inquiry might increase the confusion between history stack and pixelpipe, especially the order/re-order of the latter one. Please do not _kill_ "it" just because of this potential confusion :)

**Is your feature request related to a problem? Please describe.**

What I do....
- several modules I have auto-applied
- sometimes it happens, I crop later during edit (rather than right away at the beginning) or I re-crop
- finally I want to compare (snapshot) to original version which is up to module "orientation" (so the "always-on-modules") but **WITH the crop**

**Describe the solution you'd like**

I would like to: 
- move the crop down in the history stack
- above orientation with either ctrl. or shift click (just like I would have done it in that sequence), 
- so there I could place the history-focus, snapshot and click back to the top-most of history...

It would be very o.k., if an implemented solution does not offer to go below the "always-on-modules", those with the circle indicator

Today's work-around:
- copy that image, copy the crop and then copy the rest (unpleasant)
-  (one can do similar with switching of in "active modules" group)

**Alternatives**

- instead of re-ordering the history stack, an easy on/off toggling (maybe extended by the function "all but this", to give it a one-click-appeal) might work as well (again w/o the "always-on-modules")

**Comment by TurboGit** [comment]
I fear that this will open a can of worms for not big gain.

**Comment by Nilvus** [comment]
Yes, I fear too. And I fear too that this will complicate the UI for some users. What you state at as a confusion is just not wanted, so a no go for me.

About your alternative way, it's more acceptable. But, It's just one click less than going to active tab on modules panel, to do same thing. And this way just lack the "all but this"

**Comment by paperdigits** [comment]
Is it really history if you can just rewrite it? ;P

**Comment by AxelG-DE** [comment]
Valid statement @mica.I'm fine to convert this FR to something (almost) one-click solution for"Deactivate all modules but this" (filmic/exposure would the need to be set to default and back, if it got altered and back acc to history) Von meinem Mobiltelefon gesendet-------- Ursprüngliche Nachricht --------Von: Mica ***@***.***>Datum: Sa., 12. März 2022, 02:40An: darktable-org/darktable ***@***.***>Cc: AxelG-DE ***@***.***>, Author ***@***.***>Betreff: Re: [darktable-org/darktable] FR: history stack can be re-ordered (Issue #11202)
Is it really history if you can just rewrite it? ;P

**Comment by elstoc** [comment]
> Is it really history if you can just rewrite it?

You already can, with compress. I guess this FR is somewhat similar to mine #10344.

**Comment by ptilopteri** [comment]
but "compress" does not re-write the history stack, but merely combines
duplicate entries and removes entries that were inactive.  It maintains
the correct order.

**Comment by elstoc** [comment]
A question of semantics I suppose. I would call that a rewrite.

**Comment by ptilopteri** [comment]
it only changes the appearance of the history stack, not the operational
order nor any processing.  *only* the appearance.  no operational order
is changed.

**Comment by elstoc** [comment]
> not the operational order nor any processing

I would have called that the "pipe", with the "stack" being a representation of the order you did things. That order is altered by a compress. The history stack is all about "appearance" and I don't dispute that the actual processing is unaffected. Also, inactive entries are not removed from this representation when compressed, which is one of the things I would like to be changed.

**Comment by rekcodocker** [comment]
A bit of a fringe use but I do see the point.  You want to be able to go back in time as if you applied the operations in a different order. It does not change the processing.  
Actually the only reason it _can_ work is because the history stack is different from the pipeline.

**Comment by quovadit** [comment]
Wouldn't it be better to always use the same crop for snapshots automatically?

I absolutely agree, that comparing 2 snapshots with different crops is awkward, but it's even more confusing to fake history just for this usecase.

**Comment by Nilvus** [comment]
> Wouldn't it be better to always use the same crop for snapshots automatically?
> 
> I absolutely agree, that comparing 2 snapshots with different crops is awkward, but it's even more confusing to fake history just for this usecase.

Easy to say, hard to do. See #2784
