### ISSUE TITLE
PR #11210 for 20d7cd526 breaks the build

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11212]
**Describe the bug/issue**
PR #11210 for 20d7cd526 does not build, at least for three users on IRC.

see the build log attached.
[dt.build.2022.02.23.1725.log](https://github.com/darktable-org/darktable/files/8126173/dt.build.2022.02.23.1725.log)
**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
Try to build latest master 20d7cd526

**Expected behavior**
build succesfully

**Which commit introduced the error**
20d7cd526

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _
* darktable version : 3.9.0+xxx latest master as above
* OS                : Linux - kernel 5.16.10-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-510.54
* OpenCL installed  : Yes (opencl-headers-2021.06.30)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.3
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.30
* gcc               : x86_64-pc-linux-gnu-11.2.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

**Comment by jade-nl** [comment]
Confirmed.

```
/home/jade/.local/git/darktable/po/pt_BR.po:1108: format specifications in 'msgid' and 'msgstr' for argument 1 are not the same
[  4%] Building pt_PT locale
/usr/bin/msgfmt: found 1 fatal error
4418 translated messages, 4 fuzzy translations.
make[2]: *** [po/CMakeFiles/locale_pt_BR.dir/build.make:61: share/locale/pt_BR/LC_MESSAGES/darktable.mo] Error 1
make[2]: *** Deleting file 'share/locale/pt_BR/LC_MESSAGES/darktable.mo'
make[1]: *** [CMakeFiles/Makefile2:1540: po/CMakeFiles/locale_pt_BR.dir/all] Error 2
```


* darktable 3.9.0+504~g431b38f8a
*  Linux (kernel 5.9.15-1)
* Debian Buster (rel. 10.11)
* nvidia (460.39)

**Comment by AxelG-DE** [comment]
fixed already, thanks @TurboGit
