### ISSUE TITLE
dt crashed whilst using rotate and perspective module

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11218]
Ubuntu 20.04.4     dt 3.9.0+226~gc746d3952     No GPU/opencl
Dump file attached
[darktable_bt_BZQUH1.txt](https://github.com/darktable-org/darktable/files/8132210/darktable_bt_BZQUH1.txt)

I was using the above module.  I changed the angle of rotation and whilst it was processing clicked the module header to collapse it, and dt crashed.

**Comment by dterrahe** [comment]
Is this still reproducible in 4.0.1 or master?

**Comment by RawConvert** [comment]
I was just trying this on 4.1.0+722~g338acbffa.
I can't get it to crash.
I guess this issue should be closed, will close.
