### ISSUE TITLE
macOS filesystem metadata files included on import

### ISSUE THREAD

**Issue by maartenbrakkee** [darktable-org/darktable#11225]
**Update 25-02-2022 15:22:**

**Describe the bug/issue**
MacOS filesystem metadata files are included on import. These files start with `._`. Because the files end with the original file's extension, Darktable sees them as images and imports them. However, in Darktable they can't be opened and give an error.

---
**Original report:**

**Describe the bug/issue**
TIF files created by Epson Stylus SX420W/SX425 cannot be displayed in Darktable. Photos do work in macOS file explorer. 

```
Magick: Not a TIFF or MDI file, bad magic number 1280 (0x500). (/Volumes/Elements_02/Foto/2000 Divers/._00 Divers 062.tif).
[GraphicsMagick_open] image `._00 Divers 062.tif' not found
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[rawspeed] (._00 Divers 062.tif) virtual std::unique_ptr<RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData *), line 91: No decoder found. Sorry.
```

**To Reproduce**
Import the attached image.

**Expected behavior**
Show the image.

**Screenshots**
<img width="1440" alt="Schermafbeelding 2022-02-25 om 12 23 43" src="https://user-images.githubusercontent.com/1454803/155707649-5ba098af-7ce8-4654-90dc-b83c0fa89b3c.png">

**Platform**
* darktable version : 3.8.1
* MacBook Pro (15, retina, 2015) 
* OS                : MacOS Monetery 12.1 
* Memory            : 16GB
* Graphics card     : Intel Iris Pro 1536 MB

**Additional context**
Example image that can't be shown: [00 Divers 062.tif.zip](https://github.com/darktable-org/darktable/files/8140745/00.Divers.062.tif.zip)

**Comment by kmilos** [comment]
Weird, it's trying to open `._00 Divers 062.tif` (some macOS temporary artifact?) instead of the real `00 Divers 062.tif`...

Can you try copying the actual file and importing from another folder?

**Comment by maartenbrakkee** [comment]
It seems that you are correct. The `._`-files [seem to be](https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them) related to the macOS file explorer. On my first import, I didn't see the files as I imported a lot of images recursively.

<img width="801" alt="Schermafbeelding 2022-02-25 om 15 04 56" src="https://user-images.githubusercontent.com/1454803/155728638-e5fdc7f5-5182-49bf-a33a-8fd37966e7f2.png">

However, importing the `._` files is still unwanted. Anything that can be done about it? I'm importing a lot of folders, importing them one by one and deselecting the `._`-files would take a lot of time.

**Comment by kmilos** [comment]
Dunno, not a Mac user/developer...

In any case, now you can and should change the title of the issue to be more accurate so it can hopefully attract appropriate attention.

**Comment by spaceChRiS** [comment]
The import filter lua framework is meant to deal with such issues, see https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/official/import_filter_manager/.

**Comment by walznet** [comment]
I have the same problem in v4.2.0!
