### ISSUE TITLE
Panasonic DMC-FZ330

### ISSUE THREAD

**Issue by ultrajej** [darktable-org/darktable#11230]
Hello,

The DMC-FZ330 **is the same camera** as the DMC-FZ300. This is its name in the United Kingdom. **What is true for the FZ300 is also true for the FZ330.**
I would like to have these 2 cameras getting the same support in Darktable.
### The first easy fix is the noiseprofile.json
These line need to be added:
```
{
          "comment": "dmc-fz330 is the same as the dmc-fz300 contributed by thoren",
          "model": "DMC-FZ330",
          "profiles": [
            {"name": "DMC-FZ330 iso 100", "iso": 100, "a": [1.85543767794374e-05, 1.57600379842119e-05, 5.96528274779261e-05], "b": [8.60753365702234e-08, 3.72546214445458e-08, 5.68369441388337e-08]},
            {"name": "DMC-FZ330 iso 200", "iso": 200, "a": [3.57885249706098e-05, 2.99360457403727e-05, 0.000115267624621835], "b": [1.95576399918717e-07, 1.1396014646257e-07, 1.39945459100679e-07]},
            {"name": "DMC-FZ330 iso 400", "iso": 400, "a": [7.06877799945824e-05, 5.87828711135341e-05, 0.000227976720990628], "b": [4.53441865184594e-07, 2.87134893058008e-07, 2.78991843078341e-07]},
            {"name": "DMC-FZ330 iso 800", "iso": 800, "a": [0.000142135307280803, 0.000117902519143604, 0.000457212087097052], "b": [1.07382476566784e-06, 7.61250557142076e-07, 5.36209980805227e-07]},
            {"name": "DMC-FZ330 iso 1600", "iso": 1600, "a": [0.000287707123150274, 0.000237927656354823, 0.000912820705756715], "b": [2.66068038189175e-06, 2.12605952265336e-06, 1.02429021935989e-06]},
            {"name": "DMC-FZ330 iso 3200", "iso": 3200, "a": [0.000618784085672603, 0.000515923518678974, 0.00176829947171467], "b": [7.2366103716028e-06, 5.58873443714946e-06, 2.34639956670261e-06]},
            {"name": "DMC-FZ330 iso 6400", "iso": 6400, "a": [0.000699844253930234, 0.000592142307371188, 0.00170234413263587], "b": [5.18523310010263e-06, 3.91291260483886e-06, 2.25261406894116e-06]}
          ]
        },
```

### Other areas        
Can you update this file for the next release and look at other area where the FZ330 should be added beside the FZ300?
Lens Profile: [#2515](https://github.com/darktable-org/darktable/issues/2515)
Aspect ratio:  [#1261](https://github.com/darktable-org/darktable/pull/1261)
White balance: [#1697](https://github.com/darktable-org/darktable/pull/1697)
...Any other related category

Thank you for your help.
Yours sincerely
J

**Comment by kmilos** [comment]
If it really is the same camera (any links to support this?), the easiest fix is to add an alias in cameras.xml (or convert it to one) instead of what you suggest.

**Comment by kmilos** [comment]
Btw, there is currently an entry in cameras.xml for both, the only difference being the black level (143 for FZ300 vs 142 for FZ330).

ADC 14.2 still confirms the difference, but he RPU samples also have different firmware (v2.2 for FZ300 vs V2.0 for FZ330).

The WB presets also seem to differ between the two models/firmware...

So are they the same or not?

Curiously, the ADC 14.2 converted DNG for FZ330 also has this:

```
UniqueCameraModel               : Panasonic DMC-FZ300
LocalizedCameraModel            : Panasonic DMC-FZ330
```

@ultrajej Do you perhaps have a sample w/ the same 2.2 firmware on FZ330?

**Comment by ultrajej** [comment]
I've got the firmware 2.1

I discovered that it is a 2.2 available!
https://av.jpn.support.panasonic.com/support/global/cs/dsc/download/FZ300_FZ330/index.html

**Comment by ultrajej** [comment]
The size seems to be the same for both version
### For Windows:
DMC-FZ300:         FZ300V22.exe / 73,190,504 bytes (After self-extract, FZ300V22.bin)         DMC-FZ330:         FZ330V22.exe / 73,190,504 bytes (After self-extract, FZ330V22.bin)
### For Macintosh:
DMC-FZ300:         FZ300V22.zip / 72,912,716 bytes (After self-extract, FZ300V22.bin)         DMC-FZ330:         FZ330V22.zip / 72,912,716 bytes (After self-extract, FZ330V22.bin)

**Comment by kmilos** [comment]
Please share a sample w/ 2.2 firmware.

**Comment by ultrajej** [comment]
All my check says that the FZ330 and FZ300 are the same. The manual of my camera does not show any difference between both.

Can you send me the link with instructions to send samples?
What sample do you need?

**Comment by kmilos** [comment]
https://raw.pixls.us/

Please share there and through some cloud service here as well.

**Comment by ultrajej** [comment]
Hi,

Sorry for the delay. I uploaded photos to https://raw.pixls.us/

There are also available here for few months
https://acloud4.zaclys.com/index.php/s/LtQsLRazAKzpzzz

**Comment by kmilos** [comment]
> There are also available here for few months

Please remove the password protection.

**Comment by ultrajej** [comment]
Sorry for that. It should not be password on this share (opt-in setting that I missed)

**Comment by kmilos** [comment]
Thanks for those - indeed, the black level w/ the 2.2 firmware is identical for the FZ330 and F300, so I agree this is likely the same sensor and, therefore, noise profile.

However, the white balance presets still differ, I guess because of geographical/cultural preferences in color rendition. Need to check if those can still be handled separately if FZ330 is converted to an alias of F300...

**Comment by ultrajej** [comment]
In few days, I should be able to take more photos using different white balance settings if needed. I will double check for a custom settings too.

**Comment by kmilos** [comment]
> However, the white balance presets still differ, I guess because of geographical/cultural preferences in color rendition. Need to check if those can still be handled separately

Unfortunately not w/ the current code...

@TurboGit @johnny-bit @rawfiner Do you have a preferred way forward when it comes to handling camera model aliases? For noise profiles it might not be necessary (i.e. should be ok to look up by base model only), but for WB presets (and even custom color matrices) they might actually differ as in this case? Do we want to support that, either through a) no aliases, i.e. keeping as separate models in rawspeed cameras.xml (thus forcing duplication in noise profiles), or somehow include alias lookup of wb presets? Or we say we just support the base model WB presets/color matrix?

**Comment by TurboGit** [comment]
> or somehow include alias lookup of wb presets? 

I would lean toward this solution. That is, adding maybe a function in wb_presets.c to list aliases.

But I would first do a refactoring. Today all the "mess" is done in iop/temperature.c by just importing the big table in external/wb_presets.c. That is not an ideal solution and will add lot more complexity into temperature to handle aliases.

So I'll make wb_presets.c a first class citizen even moving it into src/common/ add routine to access the different values in the bif table and an iterator. This last routine will also send back the aliases and temperature will display them if needed. My goal is to add all this from iop/temperature.c.

How does that sound to you?

**Comment by TurboGit** [comment]
@kmilos : And of course at the end we will be able to move all definitions to an external JSON file like it is done for the noise profiles in `./data/noiseprofiles.json`.
