### ISSUE TITLE
Canon M6 weird Color Matrix in white balance module

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#11236]
while in white balance camera reference color temperature is shown is 6502K for 3.8.1 it's 25000 in current master.
also there's no valid tint value displayed
 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/39386816/155881159-f127c837-593b-4d4a-a7af-f14b26818a0d.png">

**Platform**
* darktable version : darktable-3.9.0+556~g70f65c0ff
* OS                : OSx

**Comment by TurboGit** [comment]
Thanks for reporting, should be fixed now.
