### ISSUE TITLE
local copy icon status and culling / full view 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11247]
**Describe the bug/issue**

The local status icon gets displayed when in culling or full view on the top-left corner of the image area.

**To Reproduce**
1. Go to 'lighttable'
2. Select an image
3. Click on 'copy locally'
4. Click on x for culling - see wrong local copy status icon displayed
5. Click on w for full view - see wrong local copy status icon displayed

**Expected behavior**

I believe the local status icon should be skipped on those views. But to be discussed.

**Screenshots**

Full-view:

![Capture d’écran de 2022-03-01 18-56-16](https://user-images.githubusercontent.com/467069/156223045-6407123d-401b-4190-af05-42691c27232a.png)

Culling:

![Capture d’écran de 2022-03-01 18-56-32](https://user-images.githubusercontent.com/467069/156223077-8db3f40d-8cbf-4e74-9980-db857d7cf0c4.png)

**Comment by TurboGit** [comment]
@AlicVB : What do you think?

**Comment by AlicVB** [comment]
I'm not really using local copy, I would say that : 
- either we hide it with the "block" overlay used in culling/preview (but potentially big zooming too)
- either we include it inside the block overlay

just say what is the best option from your pov, and I will fix it :)

**Comment by TurboGit** [comment]
If possible thé second option. TIA.
