### ISSUE TITLE
[FR] Open the item(s) location after export option in export module.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11246]
**Is your feature request related to a problem? Please describe.**
Some users (like me) like to check the exported files after the process, so if the files are stored in specific locations "/home/username/Photos/export/2022/02/" or Mac and Windows locations users have to navigate to the specific export folder every time to check the exported images (or have the folder open all the time). This can be avoided to more quickly open this location after the export process is finished.

**Describe the solution you'd like**
It may seem trivial, but it would be great to include an option to open the item(s) location after export process finished when the target storage is set to "file on disk" in the export module.

**Alternatives**
As alternative users have to navigate to the specific export folder.

**Additional context**
This is a mockup of how will look a feature like this:

![Screenshot-20220301111557-405x574](https://user-images.githubusercontent.com/67672868/156208734-d14f67eb-c9b9-49df-835c-de4f89840d25.png)

**Comment by dterrahe** [comment]
Google suggest 
```GError *error = NULL;
if (!g_app_info_launch_default_for_uri ("file:///", NULL, &error)) {
    g_warning ("Failed to open uri: %s", error->message);}
```
for opening a location with the default file browser, but I wouldn't be surprised if this introduced all kinds of portability issues and complaints.
