### ISSUE TITLE
History module/selective copy

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#11242]
Would it be possible to make it so that when I go to the history module and select "selective copy...", the default could be to have none of the entries selected?
I find that 99% of the time, I only want one or two history entries copied, so I always have to hit the "select none" button first.
This would be a small but significant time-saver!
Cheers.

**Comment by piratenpanda** [comment]
I'd also love this

**Comment by dterrahe** [comment]
Would it not make even more sense to retain the previously used selection (while removing modules not used in the current image)? Not sure what the current default is based on.
