### ISSUE TITLE
Failure to build git

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#11245]
Updating today's git build ... the following occurred.

Building darktable-git...
==> Making package: darktable-git 3.9.0.r574.g034910f414-1 (Mon 28 Feb 2022 01:13:15 PM)
.............................................

[100%] Building C object share/darktable/tools/basecurve/CMakeFiles/darktable-curve-tool.dir/darktable-curve-tool.c.o
In file included from /var/tmp/pamac-build-david/darktable-git/src/darktable/tools/basecurve/darktable-curve-tool.c:47:
/var/tmp/pamac-build-david/darktable-git/src/darktable/tools/basecurve/../../src/common/curve_tools.c:22:10: fatal error: common/darktable.h: No such file or directory
   22 | #include "common/darktable.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [share/darktable/tools/basecurve/CMakeFiles/darktable-curve-tool.dir/build.make:76: share/darktable/tools/basecurve/CMakeFiles/darktable-curve-tool.dir/darktable-curve-tool.c.o] Error 1
make[2]: Leaving directory '/var/tmp/pamac-build-david/darktable-git/src/darktable/build'
make[1]: *** [CMakeFiles/Makefile2:8272: share/darktable/tools/basecurve/CMakeFiles/darktable-curve-tool.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/pamac-build-david/darktable-git/src/darktable/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/var/tmp/pamac-build-david/darktable-git/src/darktable/build'
==> ERROR: A failure occurred in build().
    Aborting...

My system:  Manjaro/Arch/XFCE I have made no other system changes since the last build.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by TurboGit** [comment]
Already being handled.

**Comment by davidvj** [comment]
Closing duplicate
