### ISSUE TITLE
Darktable 3.8.1 does not open on Fedora 35, installed using dnf command line tool.

### ISSUE THREAD

**Issue by priyanshus1** [darktable-org/darktable#11241]
**Introduction**
Darktable 3.8.1 does not start on Fedora 35
It throws following error when started from terminal. 

`darktable: symbol lookup error: /usr/bin/../lib64/darktable/libdarktable.so: undefined symbol: rsvg_handle_get_intrinsic_size_in_pixels`

---------------------------------------------------------------

**Did you buy darktable from an application store ?**
Yes I have tried two installation methods.
1. Installed using fedora 35 software store.
2. Installed using dnf command line tool.

**Describe the bug/issue**
Darktable 3.8.1 does not start on Fedora 35
It throws following error when started from terminal. 

`darktable: symbol lookup error: /usr/bin/../lib64/darktable/libdarktable.so: undefined symbol: rsvg_handle_get_intrinsic_size_in_pixels`

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Install darktable using either methods as decribed in application/store version needs to be 3.8.1
2. Click on Darktable icon or use it via terminal command.
3.`darktable: symbol lookup error: /usr/bin/../lib64/darktable/libdarktable.so: undefined symbol: rsvg_handle_get_intrinsic_size_in_pixels`

**Expected behavior**
It should run...

**Screenshots**

**Platform**

* darktable version :   3.8.1-1.fc35 
* OS                :  Linux 5.14.10-300.fc35.x86_64
* Linux - Distro    : Fedora 35
* Memory            :  16GiB
* Graphics card     : NA
* Graphics driver   :  NA

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **No all the other version works fine**

**Comment by parafin** [comment]
Not a darktable bug, but mismatch of librsvg version used for building vs installed librsvg version (so wrong dependencies). Report to the provider of said package.

**Comment by priyanshus1** [comment]
@parafin How to find which librsvg version is correct ?

**Comment by parafin** [comment]
Your version is built against 2.52 or newer.
