### ISSUE TITLE
quick text filter breaks the grouping

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11254]
**Describe the bug/issue**

After using the quick text filter the grouping does not work.

**To Reproduce**
1. Select a collection with a least 2 images
2. Select two image
3. Click 'group' in 'selected image[s]' module
4. Enter 3 letters in quick text filter
5. Click on the 'erase' button to clear the text filter entry
6. Activate the grouping of thumbs (icon next to the start top-right of lighttable)
7. See error, the grouped images are both visible 

**Expected behavior**

The grouped images should have been group and only the image leader should be displayed. This works just before step 4 above.

**Platform**

* darktable version : master
* OS                : GNU/Linux
* Linux - Distro    : GNU/Debian - sid

**Comment by TurboGit** [comment]
One for you Philippe. TIA.

**Comment by phweyland** [comment]
I'll look at it

**Comment by TurboGit** [comment]
Reopen as the PR was only a partial fix.
