### ISSUE TITLE
History Stack don't copy Lens correction module.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11265]
**Describe the bug/issue**
When batch processing images the use of the history stack is excellent for transferring the parameters from one picture to another. But in the specific case of lens correction, the history stack don´t copy the module (active or inactive).

When processing an image in the darkroom and then exiting to the lighttable keeping the processed image selected and copying all the parameters of this image to the history stack module with the "copy" button, it is supposed to copy all the history, and then paste the same history in all the other photographs. This does not happen, the lens correction module is not copied in its active or inactive state. Therefore the lens correction has to be activated manually for each picture.

**To Reproduce**
1. Go to lighttable, select an image and click the darkroom icon or use "D" shortcut to past to go the darkroom.
2. Activate the Lens correction module in the correct tab.
3. Go to the lighttable and select the developed image and copy all parameters using the copy button in the history stack.
4. Select all the other images and paste the parameters using the paste button in the history stack.
5. Open any of the images in the darkroom and see the error... the lens correction module it's not active.

**Expected behavior**
When copying the history with the copy button, it is supposed to copy all the parameters (active or inactive) that are in the history of the selected image and paste them in the same way in the other images to which this history is applied.

**Screencast**
https://user-images.githubusercontent.com/67672868/156863777-1e9edf6d-6a19-4456-8b4b-dfb888a5b5ab.mp4

**Platform**
darktable version : 3.9.0~git644.e281b9bd49-7408.1
OS: Fedora Linux 35 (Workstation Edition) x86_64
OS Type: 64-bit
Host: Gigabyte Technology Co., Ltd. Z390 AORUS MASTER
Kernel: 5.12.17-300.fc34.x86_64
Uptime: 8 hours, 48 mins
Packages: 3054 (rpm), 26 (flatpak)
Shell: zsh 5.8.1
Resolution: 3840x2160
DE: GNOME 41.4
WM: Mutter
WM Theme: Materia-dark-compact
Theme: Mc-OS-Transparent-1.3 [GTK2/3]
Icons: Os-Catalina-icons-master [GTK2/3]
Terminal: gnome-terminal
CPU: Intel® Core™ i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Nvidia Driver Version: 465.19.01
Memory: 4194MiB / 32036MiB
OpenCL installed: yes
OpenCL activated: yes

**Comment by difrkaguilar** [comment]
As I have checked, although the copy button should copy the entire history, it does not do so when pasting it into another image. 

However, when the selective copy button is activated, the lens correction module is not selected by default. You have to activate it, only in this way you can copy it and apply it to the other images.

**Comment by Nilvus** [comment]
That's not an issue. This had been made on purpose (and it's not recent, as I remember that was for 3.6 or maybe even for 3.4). Some modules are not selected by default on copy options like lens correction, white balance, etc.

That was made due to other issues like copy development from an image with a lens/camera different to the paste one. That avoid some issues. So you need to select it. See for example a controversial related PR for white balance: #11018

**Comment by difrkaguilar** [comment]
**copy**
Copy the **complete history stack** from the selected image. If more than one image is selected, the history stack is taken from the image that was selected first.
Information relating to internal display encoding and mask management is considered unsafe to automatically copy to other images and will therefore not be copied when using this button.

The following modules are excluded from the copy operation:

[orientation](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/orientation/)
[lens correction](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/lens-correction/)
[raw black/white point](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/raw-black-white-point/)
[rotate pixels](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/rotate-pixels/)
[scale pixels](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/scale-pixels/)
[white balance](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/white-balance/)
deprecated modules
You can override all of these exclusions by using “selective paste…” and choosing which modules to paste to the target image(s).

In that case the copy button is invalid, because really don't **"copy"** all the history stack but part of it.
So users must have to use selective copy.

> That was made due to other issues like copy development from an image with a lens/camera different to the paste one.

Weeding photographers mostly use two lenses with two bodies, with each one of them takes a lot of photos, in a weeding some take up to 5000 photos of course after a image selection process but at least they have many photos.
Almost the same happen with sport or real state photographers. Of course then they'll use the **"selective copy"** as main option.

So, it's is a bit confusing for users to develop an image, and after take a copy of "all the history stack" and paste to other image, to later check that **copy** it's not a real complete copy but a self selective copy auto created by the software.

Default must be that copy button make a copy of the entire history stack, not part of it, if users like to copy some modules from the history stack, then selective copy is the best.

**Comment by MStraeten** [comment]
copy doesn't mean copy all whats there, it's implemented as a safe copy that excludes modules, that in general will mess up stuff if copied (https://docs.darktable.org/usermanual/3.8/en/module-reference/utility-modules/lighttable/history-stack/).
So it's better user experience to help him to avoid shooting himself in the foot.

general advice to darktable users: RTFM - at least it darktable isn't doing what you expect (or are used from other tools)
It explains why darktable behaves it's way

**Comment by difrkaguilar** [comment]
> general advice to darktable users: RTFM

I RTFM as I put part of it in my post. But then it's not ok to set in the manual "Copy the **complete history stack** from the selected image...." But copy some parts and avoid problematic ones.

**Comment by Nilvus** [comment]
> In that case the copy button is invalid, because really don't **"copy"** all the history stack but part of it.
> So users must have to use selective copy.

It's explains that button copy complete history stack but with some modules excluded. If it's how it's written in the manual that annoying you here, better post an issue in dtdocs repository and propose a better way to explain that copy button copy all modules except listed one actually.

> Weeding photographers mostly use two lenses with two bodies, with each one of them takes a lot of photos, in a weeding some takes up to 5000 photos of course after they have to make an image selection process but at least they have many photos with the same lighting condition.

Maybe but not all photographers, so not all users.

> So, it's is a bit confusing for users to develop an image, and after take a copy of "all the history stack" and paste to other image, to later check that **copy** it's not a real complete copy but a self selective copy auto created by the software.

I don't find that confusing when reading correctly manual. It's clear that some modules are excluded.

> Default must be that copy button makes an exact copy of the entire history stack, not part of it, if users wish to copy some modules from the history stack, then selective copy is the best.

That was a previous default and as I explain in my previous comment, this had been changed due to others issues. Quite some users copy without knowing/understanding what they will have and come with issues on their images due to wrong lens correction modules (or white balances, or rotation/scale) copied in new images and not adapted for. So, again it's not an issue.

I understand that it would also be good to propose a quick way to copy all modules. I even myself would like that but I understand why this had been changed.

So I suggest to close this issue as it's not one. AND, as what you ask for is also needed, think about a way to deal with why this is actually as it is (and so avoid most users to copy all modules and have issues) and let users who really know what they do, really copy all modules. And by finding a good way to deal with both, propose a FR. Or not.

**Comment by ZoomRmc** [comment]
It makes sense to not ignore a module that's already automatically adjusts itself in most cases. At least this should be an option.

**Comment by wpferguson** [comment]
It copies the settings of the module for that particular image.  It doesn't auto adjust when applied.  It applies the settings from the image that it was copied from.
