### ISSUE TITLE
UI - changing the color label icons in filter

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11273]
**Is your feature request related to a problem? Please describe.**

I find the current color label icons in the top filter a bit confusing.

**Describe the solution you'd like**

I'd like to invert the icons. Have all of them deactivated when only the circumference is displayed:

![image](https://user-images.githubusercontent.com/467069/156898906-1eef1f25-bab5-4015-b767-5ff6cf4001f8.png)

(possibly with a lighter border size)

And have them full filled circle when selected, here only the yellow would be selected:

![image](https://user-images.githubusercontent.com/467069/156898934-b553200c-7690-43de-89a3-ca3fdd3d12c7.png)

The grey icon should probably be a circle too and filled when hovering it and clicking on it.

**Comment by elstoc** [comment]
Agreed. This design confused me as well.

**Comment by phweyland** [comment]
Let's try this.

**Comment by Nilvus** [comment]
I so let you improve that @phweyland. Ping me when your PR is posted.
I'm wondering if grey icon should be near grey icon I update at bottom toolbar (maybe use bar or not depending on state?). not sure  which would be the better choice though. Just an idea.

**Comment by difrkaguilar** [comment]
Can be this an option?
using a difference between active/inactive by size and tint and not filled or outlined. The only with outline must be the dot to select all, outline for no selected colors and filled all colors selected.
![rect28712](https://user-images.githubusercontent.com/67672868/157271484-a1bb85f5-7d28-438e-b4f6-3a792f185d86.png)

As in lighttable the color dots representation looks filled and not with outline color.
![Screenshot-20220308102836-320x319](https://user-images.githubusercontent.com/67672868/157272457-ebfdf40b-0c3f-4917-98a8-b223934b2736.png)

**Comment by TurboGit** [comment]
I prefer the outline vs full circle.

**Comment by elstoc** [comment]
> +1 Great

I just read that as @TurboGit preferring the changes in the new PR to your suggestion. Or did I read that wrong.

**Comment by difrkaguilar** [comment]
> I just read that as @TurboGit preferring the changes in the new PR to your suggestion. Or did I read that wrong?

IMHO in many design solutions, the active mode of the icons is highlighted by color and even the size is accentuated. In other cases, to mark the icons deactivated, the saturation is lowered to gray. But in this case, as it is about activating colored dots, they cannot be grayscaled, but the active dots can be emphasized by resizing and highlighting the color.

The outline in such small icons also with the colors red, yellow, green, blue and magenta, is more difficult to see, unless you increase the line thickness, and they must be contrasted against the backgrounds of the predefined themes. The one that contrasts best is gray. Many users work the program on laptop, but others use it on 2 and 4K monitors.

But this is just my opinion.

**Comment by TurboGit** [comment]
> I just read that as @TurboGit preferring the changes in the new PR to your suggestion. Or did I read that wrong?

No, it was exactly that. The PR is now merged BTW.

@difrkaguilar :
> As in lighttable the color dots representation looks filled and not with outline color.

Yes, and that's the case now. When it is filled it selects the corresponding color label. The outline means not selected and is clearly distinguishable from the full circle. Also, we have a outline with cross (missing in your proposal) to reject all images with the corresponding color label. All in all, the new UI is great to me.
