### ISSUE TITLE
Tethering tab - Random crash on Jobcode creation and erroneous date in folder

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#11276]
**::Did you buy darktable from an application store ?** : **NO!!**

**::Describe the bug/issue::**

When I want to create a jobcode in tethering tab, Darktable crashes almost everytime.
this is what shows the log at crashtime :
```
**
GLib:ERROR:../glib-2.64.6/glib/gdatetime.c:2194:g_date_time_get_ymd: assertion failed: (0 <= remaining_days)
Bail out! GLib:ERROR:../glib-2.64.6/glib/gdatetime.c:2194:g_date_time_get_ymd: assertion failed: (0 <= remaining_days)
Magick: abort due to signal 6 (SIGABRT) "Abort"...
Abort trap: 6
```

Also, when Darktable doesn't crashe, it creates folder with erroneous year, month and day in its name.

My sub directory pattern is `$(YEAR)/$(YEAR).$(MONTH).$(DAY) $(JOBCODE)`

**::To Reproduce::**

1. Plug the camera to the computer by usb
2. Start Darktable. `Mount camera` button appear in lightable. Click on it, then click on `Tethered shoot`
4. Tethering tab appears, the jobcode name field is filled with the last jobcode name and a message `New session initiated`followed by the current jobcode name appears.
5. set a new jobcode (or keep the current one).
6. Click on `Create`  button, Darktable crashes or create directories with wrong date (ex: `90/90.2.68 myjobcode`)

In the case where the jobcode directory already exist and contained pictures, if I click `create` without modifying jobcode and if it doesn't crash, pictures disappear because it create that jobcode folder with a wrong date.

**::Expected behavior::**

When clicking on "create" Darktable must not crash and show the message `New session initiated`followed by the current jobcode name.
Today working session in thethering tab with Jobcode name `Flower` should be created in directory `2022/2022.03.06 Flower` 

**::Screenshots::**

![Capture d’écran 2022-03-06 à 02 53 35](https://user-images.githubusercontent.com/75432524/156905874-0a127922-441c-4414-80c7-4cfa28c7fa01.png)

**::Which commit introduced the error::**
I did bisection and it seems commit ffe43d197fbea987dc320067b551a0ba2fe5b4bc is the first bad one.
__*edit:__ it seems after a second bisection search that 76ac08e might be the culprit .

It's also working fine on 3.8.1 , 3.8.0 and 3.6

**::Platform::**

* darktable version : 3.9.0+656~g4b71974d9-dirty
* OS                : MacOS 10.15.7
* Memory            :  16 Gb
* Graphics card     :  AMD Radeon RX 580 8Gb
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional context**
 - Can you reproduce with another darktable version(s)? **Tried 3.6.1, 3.8.0, 3.8.1 and I can't reproduce**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **Yes**
 - Do you use lua scripts? **No**

**Comment by jade-nl** [comment]
I'm not able to reproduce this on a Linux box.

* darktable 3.9.0+656~g4b71974d9
* gphoto2 : 2.5.20
* libgphoto2 : 2.5.22
* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.11)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Comment by Jiyone** [comment]
I can reproduce on the last MacOS Build from @MStraeten.

@jade-nl it sometimes doesn't happen quickly, try to change some parameters and "create" the jobcode again.

**Comment by jade-nl** [comment]
@Jiyone

I just tried a few different things and every so often it indeed crashes. Can't put my finger on what actually does, though.

It does not happen when creating the session on my side of things, though, I need to actually shoot.

What I do see is that it never happens when triggering the camera remote (via *live view + camera settings*). If it happens it is when you use the camera itself to shoot. 

This is one of the only things I see:

> failed to create session path (null).
> [import_session] Failed to get session path.
> 
> (darktable:20545): GLib-CRITICAL **: 16:28:32.169: g_date_time_unref: assertion 'datetime->ref_count > 0' failed

No backtraces or any other messages.

The directories that are created are not as expected:

> drwxr-xr-x 2 jade jd 4096 mrt  6 16:28 2947462.01.02Tst

The string is:

_$(YEAR)/$(YEAR).$(MONTH).$(DAY)$(JOBCODE)_

And the Jobcode is:

_Tst_

**Comment by Jiyone** [comment]
I made a new bisection search, I found out it's 76ac08e1d4010982fcd806ce7625983bdc00e9fd actually

**Comment by phweyland** [comment]
> Can you have a look?

I will. I have no possibility to test however. Hoping you will help. TIA.

**Comment by Jiyone** [comment]
> Hoping you will help.

Sure :)

**Comment by Jiyone** [comment]
@phweyland some information about the last commit:
1. Darktable doesn't crash anymore 🎉
2. When I clic on "create" jobcode, Darktable creates a folder with correct date. (for example `2020/2020.03.07 somejobcode`)
3. when taking a picture, darktable saves the file in an other directory without date (which I cannot find on my computer ...) and in lightable, collection shows the directory adress without date.
![Capture d’écran 2022-03-07 à 21 11 09](https://user-images.githubusercontent.com/75432524/157110456-11c85346-5115-4b63-9c6d-012f782990b3.png)

**Comment by phweyland** [comment]
Thanks for following up. I'm working on this but I haven't found yet all the issues.
I see the same behavior as the ones you see. For one file imported the path is calculated 3 times. The first time it"s ok, but not the 2 others ... Probably still several errors to be discovered. I've already fixed another one [there](https://github.com/darktable-org/darktable/pull/11270/commits/4676ed36400963bfa4cae12fda7eb42b8a9ec28a).
A bit of patience.
