### ISSUE TITLE
sort in lighttable's top filter tool bar not visible when overing decending order

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11272]
**Describe the bug/issue**

In lighttable, select descending order filter and over with mouse. The icon is then non visible.

**To Reproduce**
1. Go to 'lighttable'
2. Select decending order
3. Fly over with mouse
4. See error, no icon visible

**Expected behavior**

Icon should be visible as when the ascending order is selected.

**Screenshots**

(mouse non visible when taking screenshot)

![Capture d’écran de 2022-03-05 21-19-02](https://user-images.githubusercontent.com/467069/156898774-13d3e40e-7d6e-42ec-a2b8-fd2b06bbdd16.png)

**Comment by Nilvus** [comment]
Fixed in #11281
