### ISSUE TITLE
[FR] save filter to collections as preset.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11283]
**Is your feature request related to a problem? Please describe.**
First of all thanks @Nilvus and everyone else involved for this new addition to dt. The ability to filter all collections using the top bar with all those filter options makes dt more powerful day by day. 

**Describe the solution you'd like**
I really don't know what other features you are planning to incorporate, but I have a suggestion. It would be great to have the opportunity to save (store) these filters as a new preset in the collections presets.
That way it would be faster to select those presets. Of course, I don't know how to create a naming convention for them, maybe the only way is by editing the preset.

**Additional context**
This is a Mockup with a button to save (storage) as preset.
![Screenshot-20220306231604-1218x133](https://user-images.githubusercontent.com/67672868/156968127-9f3e6e74-8af3-4144-bf08-03c5aed2383b.png)

In that case if I search for all the photos of laura with the green color label, I can save this filter as a preset in the collections presets.

![Screenshot from 2022-03-06 23-45-47](https://user-images.githubusercontent.com/67672868/156969845-f1106080-4b60-4ff4-8382-963374d8450c.png)

**Comment by Nilvus** [comment]
It's not me but @phweyland. I was even against that at first.
The button you propose is way too big. Anyway, there should be new features on that part this year. What you see is just a first and @phweyland and @AlicVB have some ideas to add.
But there's some other work on their todo list before

**Comment by difrkaguilar** [comment]
> It's not me but @phweyland. I was even against that at first.

Well thanks to @phweyland @AlicVB and thank you too for changing your mind ;-)

Glad to hear all those things. Thumbs up.

**Comment by Nilvus** [comment]
@difrkaguilar: you can now do that with new filters module. Even if actually, not all filters are there, main ones are and other will be added by @AlicVB in the future. 2 more should come really soon. So, maybe this FR could be closed now?

**Comment by AlicVB** [comment]
yes, it's now implemented, with even more filter than what we had at the moment you open this FR...

**Comment by difrkaguilar** [comment]
Thanks to all you guys for your amazing work to improve this excellent software. 👍👍👍👍👍
