### ISSUE TITLE
Metadata export bug - star rating of JPG exports does not match database value

### ISSUE THREAD

**Issue by Avikrr** [darktable-org/darktable#11282]
**Describe the bug/issue**
Export of 1 and 2 star rated pictures results in 3 stars written in metadata of exported JPG.
0, 3, 4 and 5 star rated pics are exported with correct ratings.

DT internal database rating -> vs Export rating
0 -> 0
1 -> 2
2 -> 3
3 -> 3
4 -> 4
5 -> 5

**To Reproduce**
1. Go to 'Lighttable'
2. Click on 'Import'
3. select folder containing 6 JPG files
4. Click on 'Import'
5. rate first picture with no star. Second with 1 star, Third with two stars. Fourth with three stars and so on...
 Do so by moving mouse over thumbnail and clicking on the lay over menu (don't know propper terminus for that kind of pop up, sry)
6. hit "control+a" on keyboard to select all 6 images
7. click export
8. navigate to export folder
9. See error: the images rated with 1 and 2 stars do end up in 2 and 3 stars ratings. All others are correct.

**Expected behavior**
all 6 pictures should be exported with correct star ratings according to database

**Platform**
* darktable version : e.g. 3.8.1
* OS                :  Win10 Pro 64bit (Version 21H2 build 19044.1526)
* Memory            : 8 GB
* Graphics card     : Intel HD graphics 4400
* Graphics driver   : Intel Corporation - date 29.10.2018
* CPU                   :   i7-4600U
* OpenCL installed  : if I don't know what that is... i guess not
* OpenCL activated  : don't think so

**Additional context**
Steps I tried to solve the issue:
1. issue was recognized 2 weeks ago, when I still ran on DT 3.4.1.1
2. checked files that I exported with same installed version a few months earlier -> issue was also present before, I just did not recognize it
3. tried to update to 3.8.1 -> same behaviour
4. made backup of darktable database folder -> uninstalled DT and deleted darktable folder -> reinstalled DT 3.8.1 -> with blank and fresh DT tried to reproduce -> same behaviour
5. changed default value of 1 star rating at import to 0 -> same behaviour

XMP file: [20220222_165417.txt](https://github.com/darktable-org/darktable/files/8193633/20220222_165417.txt)

 - Can you reproduce with another darktable version(s)? **yes with version 3.4.1.1**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **don't know how to do that, would need detailled instruction how to do so**
 - Do you use lua scripts? **no**

**Comment by gi-man** [comment]
I'm on windows 11 with 3.9.0+219~g06ad12bae. I can confirm that there is an issue, but I think it is with windows. I exported a file  with 1 star and windows displays it with 2 star. When I open the file in XnView MP it shows as 1 star and the Exiftool within XnView shows it as 1 star.

**Comment by gi-man** [comment]
I did more investigation into this issue and I think I discover the issue. The EXIF has two parameters, the rating and the rating percentage. When Darktable export the file it is assigning these values:

0 - 0%
1 - 20%
2 - 40%
3 - 60%
4 - 80%
5 - 100%

I'm assuming the percent is just based on a linear plot of the 0-5 values.

But when windows finds a rating and a rating percent, the rating percent takes precedence. And of course windows being special they are using these ranges when reading (per https://exiftool.org/forum/index.php?PHPSESSID=c290493972f9f06d7fc142b77f0452e0&topic=6591.msg32875#msg32875): 

1 - 12 % = 1
13 - 37 % = 2
38 - 62 % = 3
63 - 87 % = 4
88 - 100% = 5

It seems they tried to center the results around 50% with 12% steps from that center. I'm not sure I follow their logic. I still need to do more research to see if there is a standard around this. 

In my opinion, I would like for DT not to populate the rating percentage at all (leave it blank if possible). Why? 1) it avoids the issue with windows and any other software and 2) we are only rating the images in 0-5 scale, so lets only export our inputs.

**Comment by gi-man** [comment]
I did more research. I cant find a standard and I dont think there is one. I tested Digikam and it only does the 1-5 rating (no rating percent). XnView MP does apply a rating percent based on the 1-5 rating, but it follows this scheme:

1 = 1 %
2 = 25 %
3 = 50 %
4 = 75 %
5 = 100 %

That scale would align with the windows one. I searched the DT Issues or PR and I cant find anything related to the rating percent and how the DT scale was developed. The DT scale is here: https://github.com/darktable-org/darktable/blob/e95c5e090f041f544fa706d4913cb835f714c26c/src/common/exif.cc#L1940

Conclusion: I dont think this is a upstream bug. I think DT should not populate the rating percent. If there is a desire to populate it, then it should use the .01, .25, .50, .75, 1 scale.

**Comment by Avikrr** [comment]
Hi gi-man,
thanks for your research and good explanation.

I double checked  by use of exif-tool  and can confirm that also my exported image has correct metadata of 1 star in the ´rating´ field. As you mentioned, there is also additional value ´20´ in the field ´rating percent´ which correlates in Win scale with 2 stars according to provided table.
To verify your thesis I now took exiftool and deleted the data in ‚rating percent’ -> and yes, as a result WIN does now show correct star rating in explorer.

I do also agree to your proposed and preferred solution to not write any value in ´rating percent‘ if there is no special other use for it.
If there is a reason why this data field should still be written, as alternative also the alignment of DT rating percent table to WIN table could also work. But in this case I do see risk to just move the interpretation problem to other possibly used software.

**Comment by gi-man** [comment]
I checked with the some files I had processed in lightroom 5.7. It only uses the rating and not the rating percent.

I read the documentation from Photo Mechanic and it seems to me to also use only the rating. 

I read thru the code and does seem simple to remove the ratingpercent, but I dont feel comfortable enough to do the PR.

**Comment by gi-man** [comment]
I researched this and I forgot to propose a PR for this issue. The exif.cc uses the ratingpercent in 3 lines of code. My knowledge of C is limited, but I'm forcing myself to learn.

1. One is to read the rating percent and establish the star value on image import, if 1) there is no star value and 2) if there is a ratingpercent. I think this would be rare, but I dont think we should remove this part.
2.  In this line it reads like we are just empting the fields so darktable can write to them. https://github.com/darktable-org/darktable/blob/97c6dbdc9ed0527ffe3ba3baece12801d9e88084/src/common/exif.cc#L1886 but maybe I'm wrong in my understanding. 
3. Lastly, this is the line that determines the ratingpercent based on the darktable star value. I think this is all we need to remove in the PR. https://github.com/darktable-org/darktable/blob/97c6dbdc9ed0527ffe3ba3baece12801d9e88084/src/common/exif.cc#L1941

Is my assessment correct?

**Comment by phweyland** [comment]
1. read exif
if my memory is correct, ratingpercent is read after percent. If yes, it should be the opposite (if present rating should overwrite ratingpercent)
2. write exif
Yes, as this formula is related to windows world, and creates an issue in the same windows world, it could be removed.

**Comment by victoryforce** [comment]
> if my memory is correct, ratingpercent is read after percent. If yes, it should be the opposite (if present rating should overwrite ratingpercent)

You obviously meant "after rating" (Exif.Image.Rating)? Not exactly. Ratingpercent is read after Rating only if Rating could not be read, that is if not found in the EXIF data. So, this is correct behavior.

As after #11445 everything is fine, this issue can be closed.

**Comment by Avikrr** [comment]
Thank you so much guys for fixing this issue in 4.0.0. Just tried it out and it works as expected!
Wondering a bit why I can't find any way how to donate to show, respect and appreciation for your non profit work.
If there is any possibility, please do let me know!  
Thanks so much and congrats again to this masterpiece of software!!!
