### ISSUE TITLE
GLib-CRITICAL assertion during export

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11284]
**Describe the bug/issue**

(darktable:592530): GLib-CRITICAL **: 09:24:39.949: g_date_time_unref: assertion 'datetime->ref_count > 0' failed
[export_job] exported to `/home/obry/Images/Darktable/export/Tag Signatureeditsco DSC09443.jpg'

(darktable:592530): GLib-CRITICAL **: 09:24:40.776: g_date_time_unref: assertion 'datetime->ref_count > 0' failed
[export_job] exported to `/home/obry/Images/Darktable/export/S_Y01387.jpg'

**To Reproduce**
1. Go to 'lighttable'
2. Select two pictures
3. Click on 'export' (or ctrl+e)
5. See error on the console

**Expected behavior**

No critical glib error.

**Comment by phweyland** [comment]
Reproduced. I look at it.
