### ISSUE TITLE
Library compatibility with windows and linux paths (for multi-boot system)

### ISSUE THREAD

**Issue by 2dann** [darktable-org/darktable#11297]
I am running a multi-boot system with windows and linux and would like to use the same darktable library with both operating systems.

**Problem:**
Windows and linux use different ways to describe the path to the image files:
Windows:	D:\[...]
Linux:		/media/images/[...]

As a result, the images have to be re-imported every time you change the operating system.
It would be very useful if a solution could be found for this problem.

**Ideas for solution:**
- Ability to enable relative paths in library settings and set the "home directory" of the images for each operating system
- In the library, a path for Windows and a path for Linux are stored independently for each image file

**Comment by ralfbrown** [comment]
dt can update paths from the GUI, and if your entire library is under one common base directory, it takes just a few clicks: in the Collections module, select folder view.  Right click on the base directory and select "search filmroll", then set the new path.

**Comment by 2dann** [comment]
Many thanks for the quick response.

I basically know the way you described.
If, like me, you have multiple drives for the collections, you have to repeat the process several times.
Technically, the path (required for the other operating system) must be overwritten each time.
In addition, this is required again every time you change the operating system.
In my opinion, this is a bit laborious and more of a workaround.

I am very satisfied that darktable is a cross-platform application.
Therefore it would be very enjoyable if the library could also be used completely independently of the platform.
