### ISSUE TITLE
FR: Negative chroma values in Colorbalance RGB 

### ISSUE THREAD

**Issue by pedrorrodriguez** [darktable-org/darktable#11295]
Related to https://github.com/darktable-org/darktable/issues/10551 but perhaps easier to achieve. 

At the moment the chroma slider in the 4 ways tab of colorbalance RGB only accepts positive values, thus _adding_ a color to a certain luminance range.

![Screenshot_20220308_094225](https://user-images.githubusercontent.com/64545422/157202654-4df0d05f-2e28-43c4-9853-061d3ef3d24a.jpg)

Would negative chroma values be possible? The results produced would be different. It's not the same to add cyan, than to remove red:
![image](https://user-images.githubusercontent.com/64545422/157202854-2a30e5b6-60da-4ba9-b48f-acbb439a2462.png)

Currently, colorbalance RGB is able to produce similar results to the image on the right, but not the one on the left.

Thanks!

**Comment by Jiyone** [comment]
Well I think I'm quite close :

![export_0001_11](https://user-images.githubusercontent.com/75432524/159354430-cd8ad7bd-83a1-48d2-8b92-9bb7185bbd0b.jpg)

![Capture d’écran de 2022-03-21 21-03-51](https://user-images.githubusercontent.com/75432524/159354841-f1e6b11b-7c1e-4ca2-9e4d-414eaf825fab.png)
![Capture d’écran de 2022-03-21 21-03-06](https://user-images.githubusercontent.com/75432524/159354858-43b4a854-c03e-4553-8a85-e42f04a9e05d.png)
![Capture d’écran de 2022-03-21 21-04-08](https://user-images.githubusercontent.com/75432524/159355004-460ef986-16b2-432c-8af2-329f2c8ff7a8.png)

**Comment by aurelienpierre** [comment]
> At the moment the chroma slider in the 4 ways tab of colorbalance RGB only accepts positive values, thus adding a color to a certain luminance range.

No no no. Chroma is distance to white, a distance cannot be negative. It is only a GUI parameter though, and it gets translated to RGB values because the algo is in RGB. Negative chroma does not exist.
