### ISSUE TITLE
Missing Sidecar File

### ISSUE THREAD

**Issue by Enoch247** [darktable-org/darktable#11318]
**Describe the bug/issue**

I noticed one of my files was missing its sidecar file. I attempted to write the sidecar file again. DT gave no error in the GUI, but the file was still not written.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. launch darktable from a console
1. Select image of interest in lighttable
1. Click on "write sidecar file" button in history stack module
1. observe no indication that writing the file failed or succeed in GUI
1. observe that no sidecar file exists
1. observe the following error on the console:
``` shell
(darktable:446651): Gtk-CRITICAL **: 15:58:56.448: gtk_text_buffer_emit_insert: assertion 'g_utf8_validate (text, len, NULL)' failed
[dt_exif_xmp_write] /home/josh/pictures/2021/2021-11-12_Lucas_school_pictures/YPX62GHZ-29188_original.JPG.xmp: caught exiv2 exception '[xmp_write] failed to serialize xmp data'
```

**Expected behavior**
GUI should indicate error. Sidecar should be written.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.1
* OS                : Linux 5.11.0-41-generic
* Linux - Distro    : Ubuntu 20.04.4 LTS
* Memory            : 4GB
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_
I'm happy to provide the image that causes the issue to developers, but I'd rather not post it in the bug report as it is my son's school picture. Thanks!

**Comment by Enoch247** [comment]
Another interesting hint is that DT is showing the date the picture was taken as a date that is neither the one embedded in the JPEG nor the date the filesystem reports.

**Comment by ptilopteri** [comment]
care to provide the file

and examine the library.db to find where the library believes the raw file resides
compare that location with where you have the raw file

**Comment by phweyland** [comment]
Is the development particularly complex ? Have you compressed the history ?

**Comment by Enoch247** [comment]
> care to provide the file

<http://tmp.mechbits.com/YPX62GHZ-29188_original.JPG>

> and examine the library.db to find where the library believes the raw file resides
compare that location with where you have the raw file

I checked the image path in the image information module of the light table. It appears correct to me. Was this what you meant?

> Is the development particularly complex ? Have you compressed the history ?

No. I haven't done anything with the JPEG beyond import it into DT.

**Comment by ptilopteri** [comment]
do you have the config option 
  "write sidecar file for each image"
set?

config -> storage -> xmp

does dt have permission to write to the directory?

**Comment by Enoch247** [comment]
> do you have the config option
> "write sidecar file for each image"
> set?

It is set to "on import"

> does dt have permission to write to the directory?

yes
