### ISSUE TITLE
Noise profiles for sony a7 iv (ilce-7m4)

### ISSUE THREAD

**Issue by koolfy** [darktable-org/darktable#11319]
[darktable-noiseprofile-20220312.tar.gz](https://github.com/darktable-org/darktable/files/8238565/darktable-noiseprofile-20220312.tar.gz)

I hope this is usable :)

I ran into issues for ISO 102400 128000 160000 and 204800, I believe at such crazy high ISO levels, a full pinky veil appears on the darktable-interpreted raw files (jpegs from the camera don't have this), which means a total loss of any pure black on the picture or anything close.
The noise profile script thus complains that those pictures are not under-exposed enough.

Maybe the data produced for those profiles should be discarded, or maybe something is wrong in my methodology and I should re-do those. Don't hesitate to give me pointers :)

It was produced with darktable 3.9.0~git716.e00836f030-1, maybe I should have used a stable version? I can re-generate if you feel it's safer :)

Next I'll probably do wb extraction for this camera

**Comment by rawfiner** [comment]
Profile looks ok for me.
Could you regenerate it once https://github.com/darktable-org/rawspeed/pull/349 is accepted? (by manually updating rawspeed)
I guess the values of the profile may change a bit due to that

**Comment by koolfy** [comment]
I will, allow me a few days to find the time to go for the proper fix over at rawspeed#349

**Comment by starsforeveryone** [comment]
Just here for a question: Has the custom noise profile for the ILCE-7M4 been implemented yet? If not, could it still be done in time for this year's christmas release? Thanks very much~

**Comment by starsforeveryone** [comment]
> At this point I think it is too late for this year's release unfortunately...

That's sad! The A7 IV is probably one of the best-selling cameras this christmas. 🥲

**Comment by TurboGit** [comment]
@kmilos : From what I understand this won't be in 4.2.1, right?

**Comment by kmilos** [comment]
I think @rawfiner still expects someone will redo the capture w/ the RawSpeed fixes included in dt 4.2, as the currently supplied data might be invalid...

**Comment by TurboGit** [comment]
I see, missed this... Thanks. Indeed very little time...

**Comment by axeleroy** [comment]
Hello,

As I understand, the previous noise profiles are invalid and new ones should be created using Darktable 4.2.1, so I did so and hope those are valid:
[darktable-noiseprofile-20230318.tar.gz](https://github.com/darktable-org/darktable/files/11010677/darktable-noiseprofile-20230318.tar.gz)

**Comment by TurboGit** [comment]
Closing, see #13969.
