### ISSUE TITLE
calculator_solve: limit case ?

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#11310]
**Introduction**
Testing #11303, some int values are not restored properly from darktablerc (dt_conf_get_int)

**Describe the bug/issue**
In conf.c line 162:
  float new_value = dt_calculator_solve(1, str);
The string `-2147483646` is calculated as `-2147483648.00`
 
**Expected behavior**
Get the same value.

**Platform**
* darktable version : 3.9, current master.
* OS                :  debian sid

**Comment by TurboGit** [comment]
Maybe the calculator should be using double and not float to avoid such error?

**Comment by ralfbrown** [comment]
Type 'float' can't represent every integer except within the range of approximately +/- 8 million (2^23).  'double' is good up to 2^53.

**Comment by phweyland** [comment]
Right. All this is normal then.
