### ISSUE TITLE
Darktable Crashing when selecting next image to edit.

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#11320]
DT 3.9.0+715~gfa42d8601 Windows 11 Pro
Windows crashing after using for approx 30 min give or take When selecting  a next image to edit either via mouse selection in film strip or spacebar I get unhandled exception and crash.
Likely my system but just wondering if there are any clues in the back trace
12th Gen Intel 12600K 32GB Ram
[darktable_bt_ZYTXI1.txt](https://github.com/darktable-org/darktable/files/8238864/darktable_bt_ZYTXI1.txt)

**Comment by Nilvus** [comment]
Could you confirm if you still have that issue in darktable master now or no more? If no more, think about closing this issue. Thanks
