### ISSUE TITLE
errors in darktable-gen-noiseprofile

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11328]
master

I'm trying to follow `https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/` in order to generate a noise profile, but I'm getting 2 errors:

```
$ LC_ALL=C /home/paolo/git/darktable/tools/noise/darktable-gen-noiseprofile -d .
===> Check for required tools
--> Check for images handling tools availability
--> Check for images export tools availability
--> Check for profiling tools availability
--> Check for tethering tools availability
--> Check for pdf tools availability

===> Check profiling directory

===> List profiling input RAW images
--> Found ISO 125 image: ./G5Xm2_125.CR3

The script will use existing input RAW images for the profiling. No more
shot will be taken.

===> Checking profiling RAW images correctness + Jpeg export
--> ISO 125:
    ./G5Xm2_125.CR3
"./G5Xm2_125.CR3" not sufficiently over-exposed (0 / 80) 
/home/paolo/git/darktable/tools/noise/subr.sh: line 496: [: 31658.5: integer expression expected

The following ISO settings have incorrect images:
    o  125 ISO

Please read the error messages associated with each file above, check
your subject and re-do the shots.
```

The first error is that the [image](https://github.com/darktable-org/darktable/files/8241369/G5Xm2_125.zip) is correctly over-exposed, but the script keeps reporting that it's not

The second error is properly a bash bug: the "integer expression expected" output

Besides that, if more that one image is in the directory, and various produce error, only the last image producing error is reported when it says "The following ISO settings have incorrect images:"

**Comment by da-phil** [comment]
Well, I was working on the script only recently and will have a look, however without being able to reproduce it locally, it is going to be really hard for me. So I'd at least need one image which is causing this problem. Can you please share it, or find other images online, which cause the issue?

**Comment by paolobenve** [comment]
https://github.com/darktable-org/darktable/files/8241369/G5Xm2_125.zip

**Comment by paolobenve** [comment]
I'm wondering if it would be possible to get under/over-expose information running a lua command via darktable-cli --core --luacmd ...

**Comment by da-phil** [comment]
I tried your image and there is nothing wrong with the check, there is simply not enough overexposed pixels, see screenshot of processed JPG (produced by the script)
![Screenshot from 2022-03-15 22-05-37](https://user-images.githubusercontent.com/810285/158472670-682257da-6796-466d-8a63-23abf8fcb943.png)
In this example I'm checking the brightest 5% pixels (see explanation in the earlier issue: https://github.com/darktable-org/darktable/issues/7651#issuecomment-1032911519), the check itself is even stricter and only assesses 0.12% of the brightest pixels. So out of 20M pixels there is 0 pixels falling into the brightest 5% pixel values.

I don't want to defend the check criterion, as I don't fully understand the subject matter of the calibration process, 
so I'd suggest you to bypass the checks by adding `-C` to the script invocation.

As for the failed check:
`/home/paolo/git/darktable/tools/noise/subr.sh: line 496: [: 31658.5: integer expression expected`
I think I forgot to add the cast to integer in my last PR, imagemagick returns a float here and I mainly tested with graphicsmagick, hence I'm going to create a PR to fix it in a minute.

**Comment by paolobenve** [comment]
> https://github.com/darktable-org/darktable/files/8241369/G5Xm2_125.zip

@da-phil darktable shows a big over-exposed region in the raw image. I'm wondering if the convertion-to-jpg process needs some trimming... it looks weird that the raw is over exposed and the jpg isn't

**Comment by da-phil** [comment]
> > https://github.com/darktable-org/darktable/files/8241369/G5Xm2_125.zip
> 
> @da-phil darktable shows a big over-exposed region in the raw image. I'm wondering if the convertion-to-jpg process needs some trimming... it looks weird that the raw is over exposed and the jpg isn't

yes, the "highlight reconstruction" module moves the overexposed pixels into a valid RGB range. maybe this module should be turned off for the purpose of judging whether the image is usable for noise calibration :thinking:

**Comment by paolobenve** [comment]
> the "highlight reconstruction" module moves the overexposed pixels into a valid RGB range. maybe this module should be turned off for the purpose of judging whether the image is usable for noise calibration thinking

Isn't there a way to convert to jpg without applying any module?
