### ISSUE TITLE
FR: Use stars icons instead of spinbutton to set initial rating in import module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#11336]
**Is your feature request related to a problem? Please describe.**
No, we set rating by clicking on star icons and we will soon have new filters with same way to filter.

**Describe the solution you'd like**
I so suggest for better consistency and visual thing, to use 5 star icons instead of actual spinbutton and text field:

![image](https://user-images.githubusercontent.com/45535283/158253702-dc3f56f6-0da0-4eb7-9864-631897d79124.png)

To set 0, or with a right-click to remove stars selected or just add on the left of 5 stars icons, the undo rating icon I made in this commit: https://github.com/darktable-org/darktable/pull/10967/commits/0dd3ba9df383466b576c7721813a07aa78fb7e59

@phweyland: as you work on that module, what do you think of that proposal? If you like, I would hope you could work on that. I think it will be too hard for me to do!

**Comment by difrkaguilar** [comment]
In one of my previous FR #8485  I proposed something similar to your FR. It's better for maintain consistency with all the others uses of star ratings.


![](https://user-images.githubusercontent.com/67672868/111436837-cfa9c600-86d8-11eb-8318-9be850aae560.png)

**Comment by Nilvus** [comment]
Yes, I didn't forgot your FR.
