### ISSUE TITLE
Inconsistent saturation/brightness during editing

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#11338]
**Description**

When editing, the image sometimes suddenly changes saturation/brightness.
One image, when I (for example) click back in history list, the image is suddenly over-saturated, usually by clicking around (re-activating modules, undo/redo, changing values, ...) the saturation returns to normal. The same for brightness on one other image. Just by zooming in, the image becomes overexposed, but just clicking exposure verification ("o" shortcut) it's fine.
Tested for .NEF and .tiff images.

**How to reproduce**

If I notice the problem appear during editing (It doesn't seem to be a problem on every image):
1. Click back and forth in history between two entries, say, 74 and 75, where 75 is activating the vignetting module
2. The preview shows the vignetting appear/disappear
3. But then, the image becomes over-saturated. The vignetting still appears/disappears, but the saturation is different.
4. After a few clicks in history, the saturation is back to normal.

**Expected behavior**

Just show the preview consistently.

**Platform**
* darktable version : 3.8.1, downloaded .deb file
* OS                : Linux 5.13.0
* Linux - Distro    : Ubuntu 20.04
* Memory            : 16 GB
* Graphics card     : Iris Xe 
* Graphics driver   : i915
* Xorg              : 11
* Desktop           : GNOME

### >> EDIT << 
Just found out that enabling Chromatic Aberrations module and steadily increasing intensity makes highlights jump back and forth by a random amount, same for White Balance.

**Comment by todd-prior** [comment]
Sounds like your processing is lagging or something...also are you using OpenCL with an integrated graphics card...try disbiling if you are and see if the behaviour goes away...if there are weird processing issues you always need to check  OpenCL

**Comment by travnick** [comment]
@Pizzacutter-at-tty3 does it behave the same way as #11201 ?

**Comment by Pizzacutter-at-tty3** [comment]
> @Pizzacutter-at-tty3 does it behave the same way as #11201 ?

No, the difference is not as huge, but large enough to clip areas, that are close to critical values. (I think it's no more than 0.5 EV of difference.)

**Comment by Pizzacutter-at-tty3** [comment]
> Sounds like your processing is lagging or something...also are you using OpenCL with an integrated graphics card...try disabling if you are and see if the behaviour goes away...if there are weird processing issues you always need to check OpenCL

I don't think so, as OpenCL is marked as "not available" in darktable processing options (it's grayed out). I remember that I couldn't activate it in LibreOffice either.
