### ISSUE TITLE
Need help to rewrite some menuitem (remove margin/padding hardcoded in Gtk code)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#11335]
I needed to set different CSS margin/padding for all menuitem displayed in darktable. That's not wanted. Mainly all do not have by default (without CSS) margin or padding. And that's wanted and good.

But menuitem displayed when clicking on both icons in bottom toolbar in darkroom (to apply presets and styles) have by default (without CSS) a big left margin. That would be good to remove that in Gtk code to avoid setting a margin-left with negative value and so specific margin here.

I check Gtk code for that part and didn't understand why they have such left margin. So need help to fix that and remove my CSS workaround to use same settings for all menuitem. To better understand, see discussion about that, starting here: https://github.com/darktable-org/darktable/pull/11281#issuecomment-1067129234

**Comment by dterrahe** [comment]
Without reading into this too deeply, might
`  gtk_menu_set_reserve_toggle_size(menu, FALSE);`
solve this problem for you? For example after this line
https://github.com/darktable-org/darktable/blob/e99ae37510abbdaa485a837e4fc686d6c251d806/src/gui/presets.c#L1352
The Gtk manual suggests this space should be reserved everywhere for consistency, so it is the default. Which means if you want to remove it everywhere you'll have to hunt through the code to find all menus...

**Comment by Nilvus** [comment]
I don't know Gtk coding, except few things learned to work on the UI, so can't understand by now. I will check in few days. Thanks for your suggestion.

**Comment by Nilvus** [comment]
Your proposal unfortunately do not solve the problem here. I think this would need a more important rewrite which I can't do. Ideally, the goal would we to use same CSS margin/padding in both combobox and menus. That's not possible actually. Not a big deal, just would be better and allow popup menus to be more consistent. But should probably some code to rewrite. No urgency on that one.

**Comment by mohitparmar1** [comment]
please assign this issue to me
