### ISSUE TITLE
Canon g5xm2 noise profiles

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11348]
[darktable-noiseprofile-20220316.tar.gz](https://github.com/darktable-org/darktable/files/8266945/darktable-noiseprofile-20220316.tar.gz)

**Comment by rawfiner** [comment]
Profile looks ok for me.
I'll try to integrate it in the next few days/weeks, but I have limited time unfortunately these days, so if anyone want to do the PR to integrate the profile faster, don't hesitate to do so!

**Comment by rawfiner** [comment]
Thank you @TurboGit !
