### ISSUE TITLE
FR: adapt initial exposure to embedded jpg

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#11346]
**Is your feature request related to a problem? Please describe.**
In discussions about darktables initial processing there are a lot of complaints about the image being too dark, don’t respect exposure compensation, far away from the embedded jpg…

**Describe the solution you'd like**
with https://github.com/darktable-org/darktable/pull/11142 darktable got the ability to match exposures between images of a series. 
maybe that’s a solution to provide an option to match initial exposure to the exposure of the embedded jpg.
Since that’s just one way to get a proper initial exposure this behaviour could be controlled by a preference setting.

**Comment by elstoc** [comment]
The recent change to do exposure matching between images, by default, sets average image exposure to 50% lightness when you click the colour picker. You could map the picker to a shortcut.

**Comment by MStraeten** [comment]
> You could map the picker to a shortcut.

Thats a misunderstanding of the requested feature - just follow some endless discussions on usage of exposure compensation - so having an option to match initial exposure to the embedded jpg is quite a different thing that setting something by manual using pickers. 

The FR is based on the assumption: an exposure compensation can be made with 2 different goals: 
1. scene referred mindset: get the optimum raw file as a starting point for postprocessing
2. display referred mindset: get a proper exposed jpg file
For the 1st goal the scene referred default (with enabled compensation for exposure compensation) is fine, for the 2nd goal a pre-applied exposure mapping can be used.
