### ISSUE TITLE
Accumulating Parametric Data

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#11358]
When using parametric data I find that initial (boxed) selection does not fully/completely cover the target area. This results in having to 'massage' individual ranges to improve coverage.
Some years ago (working with satellite data) we had a process that allowed us to add similar areas and thus easily expand across the entire target range.
Would such an accumulation be practical with dt?

**Comment by todd-prior** [comment]
Sorry I don't exactly understand what you are trying to describe??

**Comment by davidvj** [comment]
If I select an area for parametric processing ... my selection box may not necessarily be representative of the 'entire' area that I wish to cover. I currently then need to adjust individual range sliders in order to get a better data fit.
If I was able to add areas to the initial selection this would/could be a more simple solution and would simplify my selection.
Is this a little more clear?

**Comment by davidvj** [comment]
A common example: The sky is broken in the image into 2 areas; one dark and the other light.. I box measure the dark side but the mask now only indicates that one area is included. Currently I must now mess with the sliders to add the lighter area. 
It would be nice if I could simply add to the initial selection to achieve that goal.

**Comment by Nilvus** [comment]
It's already possible. This need or parametric settings ajustements (you have multiples tabs to set your parametric mask) and you could also combine draw and parametric mask. And multiples ones. I suggest you to read masks parts of the manual.

What you describe, on what I understand, is not an issue but learning how to better use masks. Masks allow nearly all selections you want and can also be combined with multiple instances of same module.

**Comment by davidvj** [comment]
Thanks
