### ISSUE TITLE
Coolpix P7700

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#11356]
Please add support for P7700. NRW RAW samples uploaded to raw.pixls.us.
Thanks

**Comment by phweyland** [comment]
@TurboGit Pascal is there any hope to have this solved ?
It is marked as suspended in the release notes.

**Comment by TurboGit** [comment]
I've just checked raw.pixl.us and I see only a single sample for P7700 (12bit compressed). I suppose some formats are missing and a camera support needs all formats to be available.

**Comment by phweyland** [comment]
I haven't the coolpix with me but I'm quite sure there is only one raw format:
![image](https://user-images.githubusercontent.com/23012047/172485166-19e6675b-3a92-467b-add3-770b172c43d3.png)

**Comment by phweyland** [comment]
In addition I don't know if the NRW format is compressed or not (and I don't find any specif about it).
The exif data gives this (compressed but ratio 1...):
```
Exif.Image.Compression                       Short       1  JPEG (old-style)
Exif.SubImage1.Compression                   Short       1  JPEG (old-style)
Exif.SubImage2.Compression                   Short       1  Nikon NEF Compressed
Exif.Photo.Flash                             Short       1  No, compulsory
Exif.NikonPreview.Compression                Short       1  JPEG (old-style)
```

**Comment by TurboGit** [comment]
Ok, this is rawspeed stuff, maybe @kmilos may have some hints?

**Comment by victoryforce** [comment]
> I've just checked raw.pixl.us and I see only a single sample for P7700 (12bit compressed). I suppose some formats are missing and a camera support needs all formats to be available.

There is no information on the Internet about any other formats or options (compression type, bit depth, aspect ratio). So we really just need to remove `supported="no-samples"` from this camera node in `cameras.xml`.

**Comment by TurboGit** [comment]
@phweyland : So worth raising this to rawspeed project.

**Comment by phweyland** [comment]
> So worth raising this to rawspeed project.

Thanks! Done [here](https://github.com/darktable-org/rawspeed/issues/373).
