### ISSUE TITLE
Rotate and perspective - Rotation in wrong direction if image is flipped

### ISSUE THREAD

**Issue by buckket** [darktable-org/darktable#11360]
Similar to #7149, when drawing a line with the Rotate and perspective module I expect the image to be rotated in such a way that the line I drew is perfectly horizontal or vertical.

This does not work if the image has been flipped horizontally with the Orientation module beforehand. The rotation then is applied in the wrong direction, i.e. the rotation angle has the wrong sign.

---------------------------------------------------------------

**Describe the bug/issue**

**To Reproduce**
1. Flip any image horizontally using Orientation module
2. Try to rotate the image using Rotate and perspective by drawing a straight line with right-click tool

**Platform**
* darktable version : 3.8.1
* OS                : Linux
* Linux - Distro    : Arch Linux

**Comment by elstoc** [comment]
Yep, reproduced on 3.9.0+764~g98660416b.

**Comment by TurboGit** [comment]
Fixed in master.
