### ISSUE TITLE
Crop recompute is triggered too often which makes it unresponsive

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#11367]
**Describe the bug/issue**
When I activate the 'crop' module, Darktable displays 'working'.
Whenever I resize, it displays 'working'. 
Every action triggers a few seconds delay.

It's probably my lack of understanding but as I see it, it knows all the pixels already. They are not going to be different.
This 'working' seems to be the entire pipeline which recomputes the entire image.

The problem is that the crop module becomes very unresponsive until it's done 'working'.  One issue I face very often is that it fails to switch from 'move' to 'resize' mode because it was 'working' when I moved the cursor. 

**To Reproduce**
Just crop a picture 

**Expected behavior**
I would like it to resize quickly and respond quickly to small adjustments and mouse movements.

**Comment by ralfbrown** [comment]
Which version of dt, operating system, etc.?  We had such an issue in the old crop&rotate module (which was fixed long ago), but I've never noticed any lack of responsiveness in the new crop module.  I checked just now with a recent master, and while it does fire off unnecessary recomputations of the downstream portion of the pipe due to changing module parameters (which would be worth fixing), the actual crop-box UI runs smoothly for me even while 'working' is displayed.

**Comment by elstoc** [comment]
What other modules do you have running? I find issues when I have something long-running like diffuse/sharpen in the pipe, and I have to wait until the pipe has finished computing before I commit.

**Comment by elstoc** [comment]
I think mostly the issue I have is when initially focusing the module, because it changes to displaying the full image and so recomputes. If I remove focus before the pipe is finished the crop sometimes changes in an unexpected way. I do see "working" every time I change the crop though, and it stays on the screen about as long as it does when I commit the crop.

**Comment by elstoc** [comment]
I've checked with `-d perf` and changing the crop lines definitely triggers a pipe run. Similar issues with drawing perspective lines on the image in the rotate and perspective module (should only recompute when clicking one of the distort buttons). I wouldn't be surprised if there are others.

**Comment by rekcodocker** [comment]
> Which version of dt, operating system, etc.? We had such an issue in the old crop&rotate module (which was fixed long ago), but I've never noticed any lack of responsiveness in the new crop module. I checked just now with a recent master, and while it does fire off unnecessary recomputations of the downstream portion of the pipe due to changing module parameters (which would be worth fixing), the actual crop-box UI runs smoothly for me even while 'working' is displayed.

Thanks for the replies so far. 
This is a Linux Ubuntu 2021 operating system.  This is the latest stable build, 3.8.1.     Pretty sure my issue is not an OS issue.
My computer is a 4th generation Intel Core , 16GB Ram and no OpenCL accelleration.  Perhaps the problem is more pronounced because my computer was not bought last week.

I have looked more closely and it is most annoying when I start the Crop module. 
It easily takes 10 seconds before it becomes responsive to input.  
About 50% of the time, the resize-box simply does not respond when I try to drag the edge or corner.  Some times it moves instead of resizes.

When it is running and it has accepted that my dragging&drawing the edges should actually do something, it is responsive.  It does show 'working' but it remains responsive.
It's when the module starts, that is when I see the problem.

I just tried to reproduce it, and now it is totally fine and responsive even immediately after opening. 
Perhaps this happens after a long editing session.  I will watch this.

**Comment by rekcodocker** [comment]
Response on two observations in this thread: 

Crop seems to trigger the entire pipeline each time you touch it.  When I deactivate most other modules, the 'working' message is much faster. 

Most annoying:  When I open the crop, I have to wait 5 seconds for it to complete processing.  If I don't do this and crop right away, it resets the crop after it is done processing.

I really don't understand why it needs to run the pipeline so often.  A user is just drawing a crop and an aspect ratio on the screen. The result of the previous modules in the pipeline is not going to be different no matter how often they are run. 

Preferred behaviour:
- I open the crop modude
- I immediately draw a crop
- the crop is not reset after 5 seconds
- it doesn't show 'processing' ever.

**Comment by dterrahe** [comment]
Did https://github.com/darktable-org/darktable/pull/13274 solve this issue? If so, please close it. If not, please provide more detail about the specific remaining problems.

**Comment by jenshannoschwalm** [comment]
Issue has been solved for master ...
