### ISSUE TITLE
bring back drag'n'drop import on Windows

### ISSUE THREAD

**Issue by PontiacCZ** [darktable-org/darktable#11369]
It used to be possible to import files to Darktable on Windows by dragging to the Darktable window. About two years ago it worked the last time.

It was very convenient. Is it possible to enable it again?

I have Darktable 3.8.1 on Windows 10 21H2 64-bit, it does not work on this configuration.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Works for me. DT 3.8.1 on Win-10 64bit.

**Comment by PontiacCZ** [comment]
Oh, my bad. For whatever reason I kept dragging the raw files to the "Collections" section, they did nothing there. Once I dropped them to the main (center) section they appeared there. 🤦 (yep, that is facepalm)

Thank you for mentioning it worked for you. That gave me the right momentum for trying again and a different way.  😃
 
Closing this issue.
