### ISSUE TITLE
Support for Panasonic Lumix DC/S5 input color profile

### ISSUE THREAD

**Issue by ntsarb** [darktable-org/darktable#11373]
Hello,
Is it possible to add input color profiles for the Panasonic DC-S5 (S5) camera? 

VLog would be needed and, ideally all other modes, if possible.

I am happy to provide any photos required, if there is some guidance.

Thank you

**Comment by Nilvus** [comment]
Hi,
This need some samples first to provide raw in raw.pixls.us
See https://www.darktable.org/resources/camera-support/ for more infos how to add camera support

Then create a new issue with camera request template. I close this one and let you create a new one when you provide raw.

**Comment by kmilos** [comment]
See also https://discuss.pixls.us/t/converting-s1h-raw-files-to-v-log-gamma/24368 for related info

**Comment by ntsarb** [comment]
Darktable defines "Input Profile" [here](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/input-color-profile/) as "The profile or color matrix to apply. " and Panasonic defines the Gamut Conversion matrices in page 6 of [this document](https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/support/pdf/VARICAM_V-Log_V-Gamut.pdf).

I'm new to DarkTable and my current understanding is that there should be a way to create an input profile for use in DarkTable, using the information provided by Panasonic. However, I currently don't know how to achieve this.

**Comment by ntsarb** [comment]
> Hi, This need some samples first to provide raw in raw.pixls.us See https://www.darktable.org/resources/camera-support/ for more infos how to add camera support
> 
> Then create a new issue with camera request template. I close this one and let you create a new one when you provide raw.

I have submitted some raw (RW2) images in raw.pixls.us.

**Comment by kmilos** [comment]
> Panasonic defines the Gamut Conversion matrices in page 6 of [this document](https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/support/pdf/VARICAM_V-Log_V-Gamut.pdf).

> I have submitted some raw (RW2) images in raw.pixls.us

Let's see when they/if they show up at RPU, but I somehow doubt that the Adobe DNG Converter will produce different color matrices for different shooting modes - raw is raw (simple measurement of photons by the sensor before any processing). V-Log profile has nothing to w/ raw data (apart from probably different ISO and exposure compensation/dynamic range management by the camera). It is used for intermediate encoding and storage, and can be used as input profile for non-raw files (feel free to find or create a V-Log ICC profile and [add it to dt as input/working/output profile , it's easy](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/input-color-profile/)), but **it is not a camera/sensor input profile**.

There is of course a possibility that Panasonic no longer stores raw data in this mode, but let's see when those samples show up.

**Comment by ntsarb** [comment]
I suppose you are right, in which case what I need is to create a base curve for the camera. In any case, here's a shared folder with a raw file produced by the camera, while it's in V-Log mode. Please confirm once you've downloaded it.
https://drive.google.com/drive/folders/13tQRNIMfMFIRv1hIbolIT5NM9bSnkCiN?usp=sharing
