### ISSUE TITLE
Collection selection not shown

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#11374]
**Describe the bug/issue**
The selection is not shown (eg. folders, film roll). If I click on the pull down it shows the list, but once selected it is not shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/97920861/159200988-62dbbdd3-b057-44bf-8747-6583c5760cf8.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.9.0+798~g8152dd9d6
* OS                :  Win11
* Memory            :  16Gb
* Graphics card     :  Nvidia 3060 12gb
* Graphics driver   :  511
* OpenCL installed  :  yes
* OpenCL activated  :  yes

It was not an issue in: 3.9.0+219~g06ad12bae

**Comment by Nilvus** [comment]
Already pointed to @AlicVB in private. This issue comes from his last great pull request. Should be fixed quickly. Thanks for noticing it.

**Comment by gi-man** [comment]
I noticed a few PR around the combobox and others, so I figured it was small bug with those changes.

I'm troubleshooting an issue with the white balance module since going from 3.9.0+219~g06ad12bae to 3.9.0+798~g8152dd9d6. I will start a new Issue once I get more details.
