### ISSUE TITLE
Rotate and perspective amount

### ISSUE THREAD

**Issue by pedrorrodriguez** [darktable-org/darktable#11383]
Often I try to correct distorsion with this module, and, even though it works brilliantly, the results tend to look a bit artificial (perfect) to me, so I end up disabling the module altogether. On other occasions it crops more than I would like out of my image (which is not the module's fault per se, it's just working as it should).

I understand that this module doesn't allow masking, but it would be very useful if there was an "amount" parameter that we could adjust. That way we could improve the distorsion, but not get rid of it completely if we don't want to.

**Comment by ralfbrown** [comment]
Just adjust the sliders under "manual perspective" after using the automatic detection.  I tend to cut the shift parameter in half.

**Comment by pedrorrodriguez** [comment]
> Just adjust the sliders under "manual perspective" after using the automatic detection. I tend to cut the shift parameter in half.

Oh, duh! Thank you. A global slider would be nice, but this works fine for me
