### ISSUE TITLE
image information: custom order interferes with height alteration

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11389]
Normally ctrl+scrolling over the image information module correctly adjusts the height of the module by a single line at a time.

However, the following custom information order (taken from my darktablerc in my working version 3.8.1 and then applied manually to master) seems to break this. With this line in my darktablerc file, ctrl+scrolling sets the default height to "1000" and each scroll seems to change the height by pixels rather than lines.

```
plugins/lighttable/metadata_view/visible=title,maker,model,lens,ISO,aperture,focal length,focus distance,filmroll,image id,|group id,filename,version,|full path,|local copy,import timestamp,change timestamp,|export timestamp,|print timestamp,|flags,exposure,exposure bias,datetime,width,height,|export width,|export height,|description,|creator,|publisher,|rights,|notes,version name,|latitude,|longitude,|elevation,|tags,|categories
``` 

Resetting the module parameters fixes it again.

Affects 3.9.0+812~g55c24a5b1 and 3.8.1

**Comment by elstoc** [comment]
I can reproduce this in master just by going into the image info preferences window and deselecting the last entry (categories)

**Comment by phweyland** [comment]
> I can reproduce this in master just by going into the image info preferences window and deselecting the last entry (categories) and then restarting dt

I can reproduce this, but only with the last entry and restarting dt.

> With this line in my darktablerc file, ctrl+scrolling sets the default height to "1000"

**Comment by elstoc** [comment]
> I can reproduce this in master just by going into the image info preferences window and deselecting the last entry (categories) and then restarting dt

I still reproduce this on a fresh build of master (3.9.0+1568~gca7a55940) and a clean config. It only happens after restarting darktable (after deselecting the categories field).
