### ISSUE TITLE
lighttable: manually dragging scrollbar causes misalignment

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11390]
If you scroll up and down the lighttable (file manager) view using the mouse scroll button or by pressing the arrow keys, the view scrolls by a single image at a time, such that the top row always contains a row of complete images. However, if you click-and-drag the scrollbar this does not happen, leading to a gap at the top when you scroll back up again. See the following example...

https://user-images.githubusercontent.com/9555491/159715593-8c7d2a01-1414-4032-98ea-1af8e7810fc1.mp4
 
darktable 3.9.0+812~g55c24a5b1

**Comment by elstoc** [comment]
This issue was introduced by #8408 and IMO should be reverted.

**Comment by AlicVB** [comment]
oh yes, I can reproduce (I haven't noticed as I never really use the scrollbars).
I'm not sure we have to revert all #8408, but we certainly have to ensure that : 
- we can go back to the top with the scrollbar
- we never get top gap

I'll have a look asap

**Comment by elstoc** [comment]
Thanks @AlicVB
