### ISSUE TITLE
Blue color label hard to spot compared to other colors

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#11396]
**Is your feature request related to a problem? Please describe.**
With the introduction of the new quick filter by color label in the top menu bar I noticed that the blue color label is really hard to spot against the dark background in the standard darktable theme.

While visibility is still somewhat ok when the circle is completely filled:
![image](https://user-images.githubusercontent.com/2805109/160011265-2f11eb6c-ddeb-42e9-a5f4-d1aba24776d8.png)

It is very hard to see when there is only an outline
![image](https://user-images.githubusercontent.com/2805109/160011349-45ad055a-ba93-4516-b1c6-ea43f58d61b7.png)

And when adding the cross, it almost disappears into the background compared to the green and magenta which show a very nice contrast. 
![image](https://user-images.githubusercontent.com/2805109/160011492-bc49911d-fc78-40a8-8a1d-88af4932ad05.png)

Can we change the color to a more light blue or cyan tint that falls more in line with the apparent luminosity of the other colors?

<img src="https://user-images.githubusercontent.com/2805109/160012006-32b0a7ac-c146-48e7-8969-fb2849988d45.png" width="150" >

**Comment by Nilvus** [comment]
I can update that but not with colors you propose. Colors had been used since a long time by users and we can't change that with such difference.

**Comment by Solarer** [comment]
ok, looking forward to what you are allowed to do :)

**Comment by MStraeten** [comment]
It's better to use the ...grey or ...dark themes for serious image processing - the blue icon is quite ok there. ;) 
It's harder to get an appropriate perception of (color)contrast in the darker themes.

**Comment by Nilvus** [comment]
I improve it in related PR here. @Solarer: note that your colors proposal would be unreadable on dark and grey theme. With such colors, this issue would be completely fixed but we would add this issue for both grey and dark theme. Unfortunately, we can't set specific blue depending on theme, so all is about compromise.
