### ISSUE TITLE
Fallback to File Creation time if Capture time metadata is not present

### ISSUE THREAD

**Issue by rexbron** [darktable-org/darktable#11399]
**Is your feature request related to a problem? Please describe.**
I use a local lab to develop and scan film, I like to use darktable to have a virtual contact sheet to evaluate which images to re-scan for enlargements. 

The files provided by the lab don't have complete metadata attached. In particular, capture time. 

Darktable falls back to the current time as the value for capture time. This changes every time darktable is started results in a rather chaotic lighttable. 

**Describe the solution you'd like**
If capture time metadata isn't present in the file, fall back to the file creation time, rather than using the current time. 

**Alternatives**
Possible to write a script to add capture time metadata at import. 

![image](https://user-images.githubusercontent.com/587341/160087710-d1070f9f-9e7f-4d4f-aaae-b815f66dcb5d.png)

**Comment by phweyland** [comment]
> If capture time metadata isn't present in the file, fall back to the file creation time, rather than using the current time.

Agreed.

**Comment by rexbron** [comment]
Thanks @phweyland!
