### ISSUE TITLE
InputNG: allow multiple assigments for exclusive controls

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#11405]
depending illumination source color calibration enables different controls.
e.g. chrominance for custom illumination or temperature for daylight or planckian. 
These settings are exclusive, so it's impossible to change temperature if custom illumination is active or vice versa. 
if an accel is set for one of this it indicates 'not active' when using it.

**Describe the solution you'd like**
allow an accel to be assigned to multiple exclusive controls, so the accel just change the active control

**Comment by dterrahe** [comment]
@MStraeten this _should_ be fairly easy to achieve using a lua script with `dt.gui.mimic` (https://github.com/darktable-org/darktable/pull/13579). If you are still interested in this, it would be good to receive some feedback on whether it indeed can serve your purpose.

**Comment by MStraeten** [comment]
Thanks for the hint. It seems I have to spend some time to investigate the capabilities of that lua stuff

**Comment by dterrahe** [comment]
Have a look here for a complex example https://github.com/darktable-org/lua-scripts/pull/409/files

In your case, you probably just want to check the value of 
`dt.gui.action("iop/channelmixerrgb/illuminant")`
and depending on that 
`return dt.gui.action("iop/channelmixerrgb/temperature", element, effect, size)`
or
`return dt.gui.action("iop/channelmixerrgb/chroma", element, effect, size)`

Or even simply try the first one and if the return value is na (0/0 in lua), signifying that it is disabled, try the other one.

**Comment by dterrahe** [comment]
This works:

```
local dt = require "darktable"
local du = require "lib/dtutils"

du.check_min_api_version("9.1.0", "multi-sliders")

dt.gui.mimic("slider", "calibration temp or chroma", 
  function(action, element, effect, size)
    value = dt.gui.action("iop/channelmixerrgb/temperature", element, effect, size)
    if value ~= value then
      value = dt.gui.action("iop/channelmixerrgb/chroma", element, effect, size)
    end
    return value
  end)
```

`value ~= value` is the lua way of checking for NaN, apparently :-)

Put it in your config directory under lua/examples as multi-sliders.lua and start it from the script manager. Then you'll get a new fake slider in the shortcuts dialog under _lua scripts_ / _multi-sliders_ called _calibration temp or chroma_

You can map a shortcut or midi-encoder to this as normal. The drawback is that you'll have to do the mapping in the dialog and will not get the shortcut mentioned in the tooltip.

If this is a useful option then there may be more similar situations and the script file could contain a collection for distribution.

BTW the same method can be used to affect multiple widgets with one shortcut. For example to toggle a set of buttons in the bottom-right toolbox. You can define a `dt.gui.mimic("toggle", ` for that case.
