### ISSUE TITLE
[FR] auto-sync exports / connected library (DAM)

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#11400]
**Problem**

Currently I export my photos from dt to piwigo, but the main drawbacks of this export workflow are:

1. Files get out of sync
Whenever I update a tag of one image in dt, I would have to re-export the whole image to piwigo.

2. Information does not get centralized back into the library
Ratings and comments made in piwigo are not visible in dt.

**Solution**

I would love to have 'connected libraries', as Peter Krogh calls it in 'The DAM Book 3.0'

1. sync dt -> piwigo
This could be an option when exporting, to (auto-)sync the exported images whenever they are changed in dt.
Only data which has been changed should be updated.

2. sync piwigo -> dt
Another export option, whether to sync back defined attributes (rating, comments, no edits!)
These crowd-data could be stored in hierarchical tags within dt.

**Alternatives**
Maybe the 'connected library' could be a separate module, different from 'export'

**Additional context**
There already has been a FR some years ago which was closed because most of the online-exporters were removed (#3842)

**Comment by phweyland** [comment]
I used to use LR + piwigo + paid plugin interface between both.
Each LR main version  was followed by a new, paid, version of the interface. Very boring.
So I've abandoned the interface, exported to files and created this small [UpdateAlbum](https://piwigo.org/ext/extension_view.php?eid=861) piwigo extension, which can update the metadata of the images already in piwigo from files on your computer or whatever other devices, beside importing new images.
Agreed, the dt piwigo interface is a bit basic and I still use my small piwigo extension. :)
