### ISSUE TITLE
Can't use OpenCL with AMD APU due to 256 MB detected (and possibly 217.6 MB per allocation limit)

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#11401]
I cannot run darktable with opencl on my AMD Ryzen 2500U w/ Vega 8 APU (and rocm-based opencl-amd 21.50.2.50002.1384495), because the maximum memory allocation is 217.6 MB and the base memory is 256 MB. However, I can allocate many times that and there is practically no limit I'm aware of (tested by running 13 instances of `memtestCL 200 10000`, each using 200 MB simultaneously). 

Darktable gives out the following message: `[opencl_init] discarding device 1 gfx902:xnack+ due to insufficient global memory (256MB).`

I believe the 256 MB limit is only the base allocation and that the APU will allocate more memory dynamically (as tested). I don't know if the 217.6 MB allocation limit is problematic.

Could these APUs be used by allocating multiple chunks of memory that are <= 217.6 MB ?

<details>
<summary>
The output of clinfo is as follow:
</summary>
[trougnouf@uryzen:~]$ clinfo                                                                                                                                                                                                    (03-26 01:58)
Number of platforms                               2
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 21.3.7
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.2 AMD-APP (3406.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD
  Platform Host timer resolution                  1ns

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     AMD Radeon Vega 8 Graphics (RAVEN, DRM 3.44.0, 5.16.16-arch1-1, LLVM 13.0.1)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 21.3.7
  Device Numeric Version                          0x401000 (1.1.0)
  Driver Version                                  21.3.7
  Device OpenCL C Version                         OpenCL C 1.1 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Max compute units                               8
  Max clock frequency                             1100MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple (kernel)     64
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 0        (n/a)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              3221225472 (3GiB)
  Error Correction support                        No
  Max memory allocation                           2254857830 (2.1GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       32768 bits (4096 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     16
  Max constant buffer size                        67108864 (64MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    ILs with version                              (n/a)
  Built-in kernels with version                   (n/a)
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64 cl_khr_extended_versioning
  Device Extensions with Version                  cl_khr_byte_addressable_store                                    0x400000 (1.0.0)
                                                  cl_khr_global_int32_base_atomics                                 0x400000 (1.0.0)
                                                  cl_khr_global_int32_extended_atomics                             0x400000 (1.0.0)
                                                  cl_khr_local_int32_base_atomics                                  0x400000 (1.0.0)
                                                  cl_khr_local_int32_extended_atomics                              0x400000 (1.0.0)
                                                  cl_khr_int64_base_atomics                                        0x400000 (1.0.0)
                                                  cl_khr_int64_extended_atomics                                    0x400000 (1.0.0)
                                                  cl_khr_fp64                                                      0x400000 (1.0.0)
                                                  cl_khr_extended_versioning                                       0x400000 (1.0.0)

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx902:xnack+
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 2.0 
  Driver Version                                  3406.0 (HSA1.1,LC)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         AMD Radeon Vega 8 Graphics
  Device PCI-e ID (AMD)                           0x15dd
  Device Topology (AMD)                           PCI-E, 0000:03:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               8
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1100MHz
  Graphics IP (AMD)                               9.0
  Device Partition                                (core)
    Max number of sub-devices                     8
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple (kernel)     64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              268435456 (256MiB)
  Global free memory (AMD)                        262144 (256MiB) 262144 (256MiB)
  Global memory channels (AMD)                    4
  Global memory banks per channel (AMD)           4
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           228170136 (217.6MiB)
  Unified memory for Host and Device              No
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    228170136 (217.6MiB)
  Preferred total size of global vars             268435456 (256MiB)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             5597
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 8192 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             16384x16384x8192 pixels
    Max number of read image args                 128
    Max number of write image args                8
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    16
  Max pipe packet size                            228170136 (217.6MiB)
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Local memory size per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        228170136 (217.6MiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                262144 (256KiB)
    Max size                                      8388608 (8MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Number of P2P devices (AMD)                     0
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        0ns (Thu Jan  1 01:00:00 1970)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  No
    Number of async queues (AMD)                  8
    Max real-time compute queues (AMD)            8
    Max real-time compute units (AMD)             8
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD Radeon Vega 8 Graphics (RAVEN, DRM 3.44.0, 5.16.16-arch1-1, LLVM 13.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD Radeon Vega 8 Graphics (RAVEN, DRM 3.44.0, 5.16.16-arch1-1, LLVM 13.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   AMD Radeon Vega 8 Graphics (RAVEN, DRM 3.44.0, 5.16.16-arch1-1, LLVM 13.0.1)
</details>

**Comment by jenshannoschwalm** [comment]
Indeed, while looking at clinfo output
```
Max memory allocation 2254857830 (2.1GiB)
```
seems to be ok. Could you run
`darktable -d opencl`
and report back output?

**Comment by trougnouf** [comment]
Yes, below is the output of
<details>
<summary>
darktable -d opencl
</summary>
[trougnouf@uryzen:~]$ darktable -d opencl                         (03-26 10:48)
31.376682 [opencl_init] opencl related configuration options:
31.376700 [opencl_init] 
31.376703 [opencl_init] opencl: 0
31.376708 [opencl_init] opencl_scheduling_profile: 'default'
31.376712 [opencl_init] opencl_library: ''
31.376715 [opencl_init] opencl_memory_requirement: 768
31.376722 [opencl_init] opencl_device_priority: '*/*/*/*/*'
31.376727 [opencl_init] opencl_mandatory_timeout: 200
31.376730 [opencl_init] opencl_size_roundup: 16
31.376733 [opencl_init] opencl_async_pixelpipe: 0
31.376736 [opencl_init] opencl_synch_cache: active module
31.376739 [opencl_init] opencl_number_event_handles: 25
31.376743 [opencl_init] opencl_micro_nap: 1000
31.376746 [opencl_init] opencl_use_pinned_memory: 0
31.376749 [opencl_init] opencl_use_cpu_devices: 0
31.376751 [opencl_init] opencl_avoid_atomics: 0
31.376756 [opencl_init] 
31.378483 [opencl_init] found opencl runtime library 'libOpenCL'
31.378525 [opencl_init] opencl library 'libOpenCL' found on your system and loaded
32.308597 [opencl_init] found 2 platforms
32.308634 [opencl_init] found 2 devices
32.308663 [opencl_init] discarding device 0 `AMD Radeon Vega 8 Graphics (RAVEN, DRM 3.44.0, 5.16.16-arch1-1, LLVM 13.0.1)' - The OpenCL driver doesn't provide image support. See also 'clinfo' output.
32.308675 [opencl_init] discarding device 1 `gfx902:xnack+' due to insufficient global memory (256MB).
32.308679 [opencl_init] no suitable devices found.
32.308681 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
32.308683 [opencl_init] initial status of opencl enabled flag is OFF.

</details>

Note that the 2.1 GB reported seems to be for the mesa driver which has no image support. The rocm provided opencl driver is the one limited to 217.6 MB per allocation (and I haven't reached an upper limit for the total number of allocations, I ran 13 instances of 200 MB last night).

**Comment by jenshannoschwalm** [comment]
1. Yes, you are right about the mesa driver not supporting image so non-functional.
2. Unfortunately the driver reports the low value when correctly asking for CL_DEVICE_GLOBAL_MEM_SIZE. I don't know how you tested for available memory - all i can tell you it's not that easy as i had to find out the hard way - but dt can't do anything here. We simply trust and have to rely on what the drivers reports.

So - either

1. your card can do otherwise and that would mean an upstream amd driver error
2. your test was wrong
3. you have to configure the driver otherwise

**Comment by trougnouf** [comment]
Indeed it should be fixed on AMD's side.

I think a darktablerc option that allows overwriting the auto-detected value might be helpful in the meantime, but someone should ensure that it works first.

I tried replacing every instance of *->dev[dev].max_global_mem with 2147483648 (=2GB) in opencl.c and my graphical interface quickly becomes completely unstable. I don't know if it's a buggy driver or I have a buggy CPU though; it's never been particularly stable on this laptop.

**Comment by jenshannoschwalm** [comment]
> I think a darktablerc option that allows overwriting the auto-detected value might be helpful in the meantime, but someone should ensure that it works first.

I don't think that's a good idea. We **have** to take what the driver tells us. What you could do though is to manually lower the conf value of "opencl_memory_requirement" to 200 (for 200MB) that might work but i think it's without benefit as most modules would go into cl tiling very early.

**Comment by trougnouf** [comment]
> > I think a darktablerc option that allows overwriting the auto-detected value might be helpful in the meantime, but someone should ensure that it works first.
> 
> I don't think that's a good idea. We **have** to take what the driver tells us. What you could do though is to manually lower the conf value of "opencl_memory_requirement" to 200 (for 200MB) that might work but i think it's without benefit as most modules would go into cl tiling very early.

Indeed I tried that first and it was even slower than CPU (and also unstable).
