### ISSUE TITLE
Print margins can not be negative

### ISSUE THREAD

**Issue by bdemaistre** [darktable-org/darktable#11414]
**Describe the bug/issue**
the print setting should allow negative margin (as it seems this was the case in some previous darktable versions by judging the few discussions on that subject on the web).
Otherwise there is no way to be really borderless and no way to adapt an image with different proportions than the paper 

**To Reproduce**

1. Go to 'print module'
2. Click on any margin '-' button until it reach '0' value
3. The '-' button is now greyed out 
4. and you can not input a negative number

**Expected behavior**
nagative numbers allowed in print margins

**Screenshots**
![image](https://user-images.githubusercontent.com/81259846/160292393-46242d82-d762-432b-bf36-49081131c7d9.png)

**Which commit introduced the error**
Sorry I never tested myself before, it is just discussions on internet that make me think that negative margins where allowed before
https://darktable-users.narkive.com/ELmyM7p3/print-module

**Platform**
* darktable version : 3.9.0~git841.d87348f94d-1
* OS                : Linux
* Linux - Distro    : Ubuntu 21.10

**Additional context**
tried with 2 printer, one with turboprint driver for a canon printer and the other with automatic cups driver for epson

**Comment by bdemaistre** [comment]
The issue #6634 is giving an exemple of negative margin

**Comment by TurboGit** [comment]
The min of 0 is a code that is in dt since 2015. So I'm surprised that it was possible to have negative margins.
