### ISSUE TITLE
Collections not filtered in photo list (lighttable center panel)

### ISSUE THREAD

**Issue by mrghosti3** [darktable-org/darktable#11419]
**Did you buy darktable from an application store ?**

No, compiled and installed it myself using your instructions.

**Describe the bug/issue**

In center panel of Lighttable images are not being filtered by selected collection.

**To Reproduce**
1. Open Darktable application
2. Select a collection
3. Check whether all images belong to selected collection (in my case nothing changes no matter which collection I select)

**Expected behavior**

Images being filtered by selected collection in the center panel of Lighttable.

**Platform**

* darktable version : release 3.8.1
* OS                       : Linux - kernel 5.13.0-37-generic
* Linux - Distro       : Linux Mint 20.3
* Memory               : 16 GB
* Graphics card     : Nvidia GeForce GTX 1660 Ti Mobile
* Graphics driver   : nvidia
* OpenCL installed  : unknown
* OpenCL activated  : unknown
* Xorg              : 1.20.13
* Desktop           : Cinnamon
* GTK+              : mint-y-dark
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**

 - Can you reproduce with another darktable version(s)? 
   Yes, this happened in Darktable Release 3.8.0 version to.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?
   Unknown
 - Do you use lua scripts?
   No

**Comment by elstoc** [comment]
How are you selecting? If you have `preferences>lighttable>use single-click in the collections module` selected, you can select collections with single-click, else you need to use double-click.

All works as expected for me in 3.8.1

**Comment by mrghosti3** [comment]
Tried both ways:
- Double-clicking
- Single-clicking while having that preference enabled

**Comment by elstoc** [comment]
If you start darktable from the command line, do you get any errors in the console?

**Comment by mrghosti3** [comment]
No errors while running. Just this when exiting:
```bash
(darktable:64031): Gtk-CRITICAL **: 13:32:15.815: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(darktable:64031): Gtk-CRITICAL **: 13:32:15.819: gtk_notebook_get_tab_label: assertion 'list != NULL' failed
```

**Comment by elstoc** [comment]
and no errors when selecting a collection?

**Comment by mrghosti3** [comment]
Weirdly, collection started working after selecting one of the presets and then reseting back to default.

**Comment by elstoc** [comment]
Odd. If you can't reproduce we might just have to assume it got into an odd state and close the issue. I certainly haven't had any issues on either 3.8.1 or master.

**Comment by mrghosti3** [comment]
Aggreed. Well then thanks for consulting on this temporary issue.
Issue resolved.
