### ISSUE TITLE
processing modules presets do not auto-apply after export/import on another installation

### ISSUE THREAD

**Issue by rainerrol** [darktable-org/darktable#11415]
**Describe the bug/issue**
Trying to export/import all my module presets to another computer with dt installed. After the import process the presets are all visible but all “auto apply” configurations do not work anymore. It seems that some parts of the preset configurations get lost - i.e. the maximum ISO, focal length etc. which is the visible difference. 
And they do not get auto-applied anymore even though the checkbox “auto apply…” of the imported presets is ticked.

(btw. this is the second time I encountered this issue, last time I exchanged presets between an Ubuntu and a Windows installation of dt and it was still 3.7... so I was unsure wether this was the root cause… but now I'm on 3.8 stable and both are Ubuntu based dt installations)

Other users confirmed the issue - see:
https://discuss.pixls.us/t/problems-on-export-import-of-auto-applied-presets/30088

**To Reproduce**
1. export presets in global preferences menu / presets / export (ideally including an "auto-apply" preset)
2. on second computer import them
3. check if they are complete and "auto apply" presets are auto applied on second computer

**Expected behavior**
presets should be completely export/imported (including auto-apply feature) but they are not. Even though the checkbox "auto apply" is checked it doesn't work
Additionally some parameters are missing in the imported preset! i.e. the maximum ISO, focal length etc.

**Which commit introduced the error**
no special commit, seems to be like this since pre-3.8 releases and is still like this in 3.8 stable

**Platform**
seems to be a general problem on all dt versions, platforms and OS's
* darktable version : 3.8 and previous versions
* OS                : Windows and Ubuntu; Ubuntu and Ubuntu

**Comment by oleastre** [comment]
I can confirm a similar problem with DT 3.9.0+1081.
I exported all my presets, and imported them after cleaning my darktable folder. 
The presets are working if activated manualy, but the auto-apply feature not.
It's even more weird, it looks like the preset has been applied, but then reset to the original module values because if I go to the preset menu of the module, it proposes me to update my preset.

**Comment by Ultra2D** [comment]
I'm seeing similar behavior (auto apply not applying), even though I did not do an export/import. Not sure if it is the same issue, but perhaps export/import is just one way to corrupt the presets.

**Comment by oleastre** [comment]
Tested again today, on a build of darktable version 4.1.0-1 (first commit after the release branch was created).
Problem is still there: presets are imported, but not the auto-apply information. And worse, even if I try to activate the auto-apply on an imported preset, it never triggers.

**Comment by oleastre** [comment]
Problem seems to still be there with latest 4.0.1 as reported on Pixls.us:
https://discuss.pixls.us/t/imported-presets-will-not-auto-apply/32705
