### ISSUE TITLE
Support for multiframe raws

### ISSUE THREAD

**Issue by maruncz** [darktable-org/darktable#11418]
Hi, i whould like to be able to process Pentax PixelShift images in darktable.

I implemented support into rawspeed here [https://github.com/darktable-org/rawspeed/pull/350](PR)
My idea is to pass all frames into demosaic module and merge it here.
Demosaic module would have new algorithm called PixelShift wich will open new options:
- show separate frames
- some sort of motion correction

We could get inspiration from RawTherapee GUI options.

I already looked into Darktable code, but it is quite complicated and i don't know if somethink like this is even possible.

I would like to hear your opinion on this.

**Comment by jenshannoschwalm** [comment]
Your idea has no "easy chance" at all because of the way the pipeline works (currently) And the pipeline is a hard&tricky beast :-) I think @hanatos and i pointed to this in pixls.us already.

The only module i can imagine to handle this would be rawprepare as i has access to the original data in some way (you would have to extend the functionality a lot.

To access the original data the first place to look at would be `imageio_rawspeed.cc` it is "presenting" raw data to the pipeline further on ...

**Comment by maruncz** [comment]
> I think @hanatos and i pointed to this in pixls.us already.

yes, but i thought this is better place to discus this.

> The only module i can imagine to handle this would be rawprepare as i has access to the original data in some way (you would have to extend the functionality a lot.

i don't think rawprepare would work, this assumes that i have perfect data, so i can then bypass demosaicing, but this is not usually the case.

> To access the original data the first place to look at would be `imageio_rawspeed.cc` it is "presenting" raw data to the pipeline further on ...

I already looked there, i have to extend mipmap_cache probably, and more

btw, why there is image_cache and mipmap_cache? i found that mipmap_cache store images (and downsampled versions), but i don't see what is stored in image_cache, it seems that it interact with database.

**Comment by tduell** [comment]
For help on how pixelshift can be done, have a look at dcrawps, that code implements pixelshift for all or most of the Pentax bodies that have that capability, and works quite well.

**Comment by maruncz** [comment]
I looked into libRAW, and stacking algorithm is quite easy, just overlay images with offset, but you need some motion correction algorithm as well

**Comment by maruncz** [comment]
Hi while i'm implementing this i found issue, no output buffer gets assigned for rawprepare module and i can't find place where it is supposed to get allocated. Can somebody help?
