### ISSUE TITLE
print: landscape images offset off edge of page

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#11416]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

When printing an image, the image origin is offset such that it is not entirely on the page.

**To Reproduce**
1. Import a landscape format image and switch to print view
2. Choose a connected printer
3. Set paper size to "letter" (optional, as that is the paper I have -- if you leave this setting on A4 the image is still offset)
4. Leave rest of settings on default (17mm margins, single image auto-positioned fullpage)
5. Click print
6. The image is printed offset: The right and top margins are too wide. Hence the image is cropped and falls off of the top/left sides of the page.

For my test image, I see a right margin of approx 46mm, bottom margin approx. 56mm, no margins on top or left. The image size is as specified.

**Expected behavior**

The image is printed with the margins as chosen, and the layout matches the preview in the center view.

**Which commit introduced the error**
Did not yet bisect.

**Platform**

* darktable version : 3.9.0+843~g9dd0b9d1ae
* OS                : Linux - kernel 5.16.14
* Linux - Distro    : Debian testing
* Memory            : 32 GiB
* Graphics card     : GA104M [GeForce RTX 3070 Mobile / Max-Q]
* Graphics driver   : Nvidia proprietary 510.60.02
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 7.7
* Desktop           : KDE
* GTK+              : 3.24.33
* gcc               : gcc 11.2.0
* cflags            : standard
* CMAKE_BUILD_TYPE  : Release
* CUPS : 2.4.1

**Additional context**

I'm using a new laptop & fairly fresh Debian install. Hence this could be a setup problem here, or a change in external software (e.g. CUPS) since I last printed.

There is a trivial fix for this:

```diff
modified   src/common/cups_print.c
@@ -556,6 +556,8 @@ void dt_print_file(const int32_t imgid, const char *filename, const char *job_ti
       num_options = cupsAddOption("Borderless", "true", num_options, &options);
     }
 
+    num_options = cupsAddOption("fit-to-page", "true", num_options, &options);
+
     num_options = cupsAddOption("landscape", pinfo->page.landscape ? "true" : "false", num_options, &options);
   }
 ```

I'm not sure if this has other repercussions, e.g. breaking a case where an image bounding box extends off of the page or a case of negative margins.

Here is an excerpt from a PDF produced by darktable which manifests this bug when printed:

```postscript
3 0 obj
<<
/Type /XObject
/Subtype /Image
/Name /Im0
/Filter [ /FlateDecode ]
/Width 3506
/Height 2338
/ColorSpace /DeviceRGB
/BitsPerComponent 8
/Intent /Perceptual
/Length 4 0 R
>>
```

...

```postscript
5 0 obj
<<
/Type /Page
/Parent 2 0 R
/Resources <<
/XObject <</Im0 3 0 R
>>
/ProcSet [ /PDF /Text /ImageC ] >>
/MediaBox [0 0 792 612]
/Contents 6 0 R
>>
endobj
6 0 obj
<<
/Length 7 0 R
>>
stream
q
1 0 0 1 45.400001525878906 72.200004577636719 cm
701.20001220703125 0 0 467.60000610351562 0 0 cm
/Im0 Do
Q
endstream
endobj
```

When I load the PDF via okular or evince, the image appears with proper margins. Okular does warn "Some errors were found in the  document." If I print the image via okular (which defaults to setting "fit-to-page" to "true") the margins are correct.

 - Can you reproduce with a RAW or Jpeg or both? both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? yes
   - What lua scripts start automatically? none
   - What lua scripts were running when the bug occurred? none

**Comment by dtorop** [comment]
Also, to clarify: This is using CUPS (`Epson Stylus Pro 3880 - CUPS+Gutenprint v5.3.3 (color)`), not TurboPrint.

**Comment by TurboGit** [comment]
Could this be because of wrong hardware margins reported?

> ```diff
> num_options = cupsAddOption("fit-to-page", "true", num_options, &options);
> ```

This is not ok to me. We don't want any resizing of the image done by the driver. The dt internal has (or should have) done everything (getting hardware margins, handling user's margins, places all the images on the page properly...).

> Also, to clarify: This is using CUPS (`Epson Stylus Pro 3880 - CUPS+Gutenprint v5.3.3 (color)`), not TurboPrint.

I have been using the same printer for years without issues, but with TurboPrint.

Maybe a bug introduced recently with the multi-page support. Something not properly initialized maybe...

If after the point 2 (Choose a connected printer) you press the reset button does it fixes the issue?

**Comment by dtorop** [comment]
It looks like this results from a CUPS version change.

I downgraded CUPS to the version in Debian stable (2.3.3op2-3+deb11u1). With that version, I can no longer replicate this problem.

My machine upgraded from Debian's 2.3.3op2-7 -> 2.4.1op1-1 on 2022-02-22. That's nearly a year's change to CUPS.

More notes:

> Could this be because of wrong hardware margins reported?

The printer reports hardware margins of `0.000 0.000 0.000 0.000` (with either CUPS 2.3.3 or 2.4.1). (Hence it always defaults to borderless mode.) I think the reported margins are correct for the 3880 (it _can_ print borderless.)

> > ```diff
> > num_options = cupsAddOption("fit-to-page", "true", num_options, &options);
> > ```
> 
> This is not ok to me. We don't want any resizing of the image done by the driver. The dt internal has (or should have) done everything (getting hardware margins, handling user's margins, places all the images on the page properly...).

Yes, that makes sense. It's a hack and obscures the underlying problem.

> > Also, to clarify: This is using CUPS (`Epson Stylus Pro 3880 - CUPS+Gutenprint v5.3.3 (color)`), not TurboPrint.
> 
> I have been using the same printer for years without issues, but with TurboPrint.

It's a good printer!

> Maybe a bug introduced recently with the multi-page support. Something not properly initialized maybe...

I can replicate the bug with release-3.8.0 and release-3.6.0. I believe that I've printed without problems as recently as mid-February, with dt > v3.8.0 (but CUPS 2.3.3).

> If after the point 2 (Choose a connected printer) you press the reset button does it fixes the issue?

Resetting doesn't fix this.

**Comment by TurboGit** [comment]
So if I read correctly that's a CUPS issue. Very unfortunate, probably worth reporting upstream as we cannot work around that in darktable without breaking other drivers I suppose.

**Comment by dtorop** [comment]
> So if I read correctly that's a CUPS issue. Very unfortunate, probably worth reporting upstream as we cannot work around that in darktable without breaking other drivers I suppose.

I think so. Unless darktable is producing non-compliant PDFs or CUPS options which CUPS >= 2.4 no longer allows...

Probably the right way forward would be to bisect CUPS and figure out what change caused this. For now I'll make a bug report to https://github.com/OpenPrinting/cups so at least this is documented -- and maybe it's a way to find more clues via CUPS developers...

**Comment by TurboGit** [comment]
Just curious, do you have the same issue if printed on the CUPS-PDF virtual printer?

**Comment by dtorop** [comment]
> do you have the same issue if printed on the CUPS-PDF virtual printer?

CUPS-PDF generates this PDF, which looks correct:

[Test_2100x980_px_rgb.png__g_non-Linux-generated_files-job_66.pdf](https://github.com/darktable-org/darktable/files/8365698/Test_2100x980_px_rgb.png__g_non-Linux-generated_files-job_66.pdf)

It appears that CUPS-PDF uses ghostscript to take the landscape image and render it in portrait orientation.

For reference, here is the test image which darktable used to produce the PDF above and the one in https://github.com/darktable-org/darktable/issues/11416#issuecomment-1080915281:

![Test 2100x980 px rgb](https://user-images.githubusercontent.com/2311860/160472611-f42bc056-d952-4c99-bfc2-509be735c6e8.png)

Certainly another hack to fix this, as it only affects landscape orientation, would be to have the dt print code do the 90 degree rotation when rendering the PDF, rather than relying on CUPS for this.

**Comment by TurboGit** [comment]
> would be to have the dt print code do the 90 degree rotation when rendering the PDF, rather than relying on CUPS for this.

Well it means that we also need to rotate the image.

**Comment by TurboGit** [comment]
> CUPS-PDF generates this PDF, which looks correct:
> 
> [](https://github.com/darktable-org/darktable/files/8365698/Test_2100x980_px_rgb.png__g_non-Linux-generated_files-job_66.pdf)

Even the latest version of CUPS? So it means that this issue only affect the Epson when using with new CUPS?

**Comment by dtorop** [comment]
> > CUPS-PDF generates this PDF, which looks correct:
> 
> Even the latest version of CUPS? So it means that this issue only affect the Epson when using with new CUPS?

Wait,I was wrong! I was running CUPS 2.3.3 when I did the CUPS-PDF test above. When using CUPS 2.4.1 the image is offset, just as when it is sent to the printer:

[Test_2100x980_px_rgb.png__g_non-Linux-generated_files-job_71.pdf](https://github.com/darktable-org/darktable/files/8365980/Test_2100x980_px_rgb.png__g_non-Linux-generated_files-job_71.pdf)

Hence this isn't only an Epson problem...

Also, looking a bit more at the PDF file generated by CUPS-PDF, it looks like both Ghostscript and Cairo have a hand in that work.

**Comment by TurboGit** [comment]
> Hence this isn't only an Epson problem...

Would be easier to test as you won't have to loose precious ink and papers!

**Comment by dtorop** [comment]
> Would be easier to test as you won't have to loose precious ink and papers!

Yes!

> Well it means that we also need to rotate the image. Today we just record the needed rotation IIRC.

One way to debug could be to catch the PDF output of a similar document from another application which works with CUPS 2.4.1. Then to modify the dt PDF generation as needed until it works the same way (whether this means pre-rotating, or altering the PDF format/objects).

I could spend a moment on that as time allows...

**Comment by TurboGit** [comment]
> One way to debug could be to catch the PDF output of a similar document from another application which works with CUPS 2.4.1. Then to modify the dt PDF generation as needed until it works the same way (whether this means pre-rotating, or altering the PDF format/objects).

Could works yes !

**Comment by dtorop** [comment]
For the purposes of making a PDF to print, could the handwritten PDF creation code in src/common/pdf.c be replaced via simply using a Cairo PDF surface? This might produce more reliable output (and use a PDF spec > v1.3).

The problem is that the PDF creation code is also used by the PDF export format, which requires a bit more flexibility (e.g. to embed ICC profiles) which Cairo doesn't seem to offer (unless the Cairo output is piped through ghostscript!?).

**Comment by dtorop** [comment]
It's not actually necessary to specify whether the PDF is landscape/portrait in CUPS options. The [pdf2pdf filter](https://wiki.debian.org/CUPSPdfToPdf) will, at least on this system, auto-rotate the file. Specifying `landscape` as an option actually causes the offset/cropped output. (Indeed, if I take a landscape-orientation PDF exported by LibreOffice and use CUPS option `landscape=true`, I see the same behavior.)

Hence a trivial fix for CUPS 2.4.1:

```diff
modified   src/common/cups_print.c
@@ -555,8 +555,6 @@ void dt_print_file(const int32_t imgid, const char *filename, const char *job_ti
       num_options = cupsAddOption("STP_FullBleed", "true", num_options, &options);
       num_options = cupsAddOption("Borderless", "true", num_options, &options);
     }
-
-    num_options = cupsAddOption("landscape", pinfo->page.landscape ? "true" : "false", num_options, &options);
   }
 
   // print lp options
```

I haven't tested this on older versions of CUPS, though.

Also, the "startxref" section of the darktable-generated PDF has the wrong offset. CUPS is able to fix this, but it results in an annoying "Attempting to reconstruct cross-reference table" in the CUPS logs.

**Comment by dtorop** [comment]
So the problem isn't a change in CUPS 2.4. It's an update to the [CUPS filters](https://github.com/OpenPrinting/cups-filters) somewhere between v1.28.7 and v1.28.12.

Removing the `landscape=true` option produces the right results with CUPS 2.3.3 or 2.4.1. It also works with cups-filters v1.28.7 or 1.28.12. It does rely on a bit of magic in the pdftopdf filter.

As the autorotate feature appears to have been in cups-filters since at least 1.0.25 (e.g. for about a decade), it seems safe to expect that it is present. Though are there cases in which darktable wouldn't trust the autorotate to do the right?

It may be a cups-filter regression that manual rotation via cups options no longer works.

Here is [documentation](https://github.com/OpenPrinting/cups-filters/blob/8bf3f5c232f1d3d85703cdbf35a737e21a2ae0f4/README#L821-L848) of auto rotation:

```
2) Page autorotate

pdftopdf automatically rotates pages to the same orientation,
instead of (e.g. fitplot) scaling them down unrotated.
This behavier can be controlled by

  pdfAutorotate / nopdfAutorotate

Specifically, if a PDF file contains pages with page width greater than
page height (a landscape page), such pages are automatically rotated
anticlockwise by 90 degrees, unless the PPD file specifies
"*LandscapeOrientation: Minus90". In this case, clockwise rotation is used.
To turn off the feature on a job-by-job basis use

  lp -d <print_queue_name> -o nopdfAutorotate <document>

On a per-queue basis use

  -o nopdfAutorotate-default

as an option to lpadmin.

When the 'landscape' or 'orientation-requested=4' (or =5) option of CUPS is
given, the pdfAutorotate processing will adjust and accordingly rotate the
non-landscape pages are rotated instead.

Note: Some pages might end up 180 degree rotated (instead of 0 degree).
Those should probably be rotated manually before binding the pages together.
```

**Comment by TurboGit** [comment]
I can reproduce with PDF printer BTW. Given my last print done, I think the update on my machine is:

```
Start-Date: 2022-02-22  07:50:34
Commandline: apt upgrade
Requested-By: obry (1000)
Upgrade: cups-filters:amd64 (1.28.11-2, 1.28.12-1), 
....
End-Date: 2022-02-22  07:50:55
```

So the bug has probably been introduced in 1.28.12 as before February I have done some print which where ok.

I'll test on a real printer with your proposed PR to remove auto rotation, if OK on my side and that you can confirm that it is OK too for you on real printer I'll merge the PR.
