### ISSUE TITLE
dt Sigmoid crashes on importing raws

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11426]
N.B. applies to Sigmoid build, not dev/Master    FAO Jakob
Ubuntu 20.04   dt 3.9.0+577~g78f301c14 built from sigmoid code
On importing new raws, there was a seg. fault, dump attached.
[darktable_bt_UE73J1.txt](https://github.com/darktable-org/darktable/files/8371531/darktable_bt_UE73J1.txt)

**Comment by phweyland** [comment]
I've the same issue with DNG file but I've imported (in place) NEF and EXR files properly.

**Comment by elstoc** [comment]
IMO this should probably be raised on @jandren's repository since there's not even an active PR for sigmoid on this repo

**Comment by RawConvert** [comment]
I've asked Jakob about reporting Sigmoid issues.

**Comment by elstoc** [comment]
Ideally, if it is still @jandren's intention to get this merged, we'd have an active PR and you should comment there. We don't usually have issues on this repo for anything apart from current master and stable releases.
