### ISSUE TITLE
TAB key not doing anything in Export tool

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11425]
Ubuntu 20.04 dt 3.9.0+846~gab4f9caaf built today
You "set size" the X value, press tab, but focus does not move to Y size.
See also #9459

**Comment by Nilvus** [comment]
Works great on my side. Debian Sid and dt 3.9.0+866~g91de3c063 (also tested, just before compiling again few minutes ago master, on 3.9.0+845, so just commit before yours). You probably have issue on your side, maybe by setting a shortcut with tab shortcut that override this use.

**Comment by elstoc** [comment]
Same here. Can't reproduce on Arch Linux / current master 3.9.0+866~g91de3c063.

**Comment by RawConvert** [comment]
I see what's happening.  Yes, focus is moving from X to Y, but with the elegant grey theme which I use, it's hard to see the Y field go highlighted.  And there's no cursor either.  So it looks like focus hasn't moved.   So perhaps highlighting tone should depend on theme?

**Comment by RawConvert** [comment]
thumbs up
