### ISSUE TITLE
Style panel has strange selection of modules

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11422]
Ubuntu 20.04    dt 3.9.0+846~gab4f9caaf  built today
You create a style by clicking the icon next to "compress history stack" and the resulting panel has a selection of modules ticked which don't make sense to me, see attached.
![style-shot](https://user-images.githubusercontent.com/16868433/160604114-3d906feb-4b3d-4dd8-b0b1-ad5aff0df2ed.jpg)

**Comment by Nilvus** [comment]
This is not a help forum here but a place to post issue. Not understanding a thing is not an issue for a github tracking system. Creating style is quite the same logic as choosing which modules to selectively copy/paste. Here, you just check which module to include on the style or not. You could find infos on manual here (or ask for more precisions in pixls.us forum.

**Comment by RawConvert** [comment]
I am posting an issue, namely that the modules ticked make little or no sense, and by implication, it could be a good idea to improve this.  I can't see in the manual where it explains which are initially ticked.  It might be better to start off with all ticked and let the user untick as required (or clear all).  If you can justify the current behaviour then fine, otherwise I think you should re-open this Issue.

**Comment by Nilvus** [comment]
Firsy, be more precise and respect template issue so. If such detailed issue, it's for good reasons.
You describe no issue on your first post. More on second.
And even with that, it's not an issue and wanted to have not all modules, for safe reasons as some modules settings depends on camera/lens and applying them by default on a style could cause issues. I will not explain more. As I said, it's same logic as copy/paste behavior and this has already been explain. It's not help forum here.

**Comment by RawConvert** [comment]
The random ticks just look silly, but ok, not a big problem.
Styles may be implemented with similar logic to copy/paste but I don't think that's relevant.
I appreciate the point about camera dependency, so how about display the panel with no ticks, let the user add them, and put a warning comment in the manual about camera dependency.
Or display with no ticks, let the user add, and show a warning message if they add a cam. dep. module.
