### ISSUE TITLE
Minor: Chromatic Abberation module collapses Histogram and preview (no actual end result effect) 

### ISSUE THREAD

**Issue by spyfish** [darktable-org/darktable#11434]
**Introduction**
One a specific raw file, enabling Chromatic Aberrations module seem to collapse the Histogram and preview. No effect on main view and exported file. And only saw on this file so far. 

**Strangely it DOES NOT happen in debug mode** 
"C:\Program Files\darktable\bin\darktable.exe" -d all
[darktable-log.txt](https://github.com/darktable-org/darktable/files/8388481/darktable-log.txt)

Darktable for windows built today: 
darktable-3.9.0+873~g730ee22ff-win64

Before:
![image](https://user-images.githubusercontent.com/5610400/161033990-1b1a9696-0865-4d5a-9cfc-ec699f0e795d.png)
After:
![image](https://user-images.githubusercontent.com/5610400/161034164-6dc51062-ea02-42af-9573-e0cc63f1a360.png)

---------------------------------------------------------------

**To Reproduce**
[raw+xmp.zip](https://github.com/darktable-org/darktable/files/8388451/raw%2Bxmp.zip)

1. Import raw file and XMP
2. Enable Chromatic aberration module

* darktable version : darktable-3.9.0+873~g730ee22ff
* OS                : Win 10 21H2
* Memory            : 32
* Graphics card     : rtx 1080
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by gi-man** [comment]
I tried this file in my win 11 system with 3.9.0+798~g8152dd9d6. I could  not get your xmp to open and it is likely due to the different builds.

I turned on the chromatic aberration and I could not recreate. 

I looked at your log file. The first thing odd is the system finds NVIDIA GeForce RTX 2070 but you stated you have RTX 1080. Can you confirm? 

The main view is processed on the GPU while the thumbnail is on CPU, but you stated the error did not happen in -d all. To further troubleshoot, I think you should try with OpenCL off and also with forcing to only use OpenCL. 

Lastly, did you remove the microsoft OpenCL compatibility pack from your apps?

**Comment by spyfish** [comment]
> The first thing odd is the system finds NVIDIA GeForce RTX 2070 but you stated you have RTX 1080. Can you confirm?

Yes sorry, 2070 indeed. 

> Lastly, did you remove the microsoft OpenCL compatibility pack from your apps?

Its a newly reinstalled/reformatted win 10 install. But i don't think Ive ever had that installed. 

I tinkered a bit with performance settings. Set it to Unrestricted resources, Very fast GPU, and enabled OpenCL > Unable to reproduce. 

Then i turned off OpenCL support, and could reproduce almost every time. This time with debug enabled:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/8390530/darktable-log.txt)

I noticed allot of Pango errors in the log. Please note I downgraded Pango due to https://github.com/darktable-org/darktable/issues/11407 

So perhaps its related to the apparently buggy pango-1.50.5-1 ? 

In any case, its not a big deal for me, but id be happy to test more if needed.

**Comment by gi-man** [comment]
The OpenCL is installed automatically sometimes. You have to go into app and search for it to remove. But that's not the issue with this issue.

The Pango stuff is just a nuisance message due to some fonts with windows. There is a Issue for it but I dont think we have root cause. You can ignore it or change the theme to elegant so it doesnt happen. 

Since it is not happening on GPU, then it must be an issue with the CPU path. The -d all has too much information that makes it hard to read. Maybe posting the -d perf -d memory might be better. With OpenCL off, does it happen on the main view and the thumbnail or only in the thumbnail. What CPU processor you have?

**Comment by spyfish** [comment]
I did a new build on my laptop today, also with a Ryzen CPU and RTX 3080 card. 
3.9.0+882~gea3c8ce81
I can still reproduce on the laptop as well. So i can reproduce it on two different win 10 PCs. Though both with Ryzen CPU and Nvidia RTX cards.  And with this build its horribly sloooooooow. (Also slow with opencl) Bills build seem much faster

Yes, just the thumbnail in top left and the Histogram affected, main view does not change visually. (Nor the exported file) 

Sometimes the hisytogram goes black, other times truncated like this. Amnd it doesnt happen every time, but most times i enable the module:
![image](https://user-images.githubusercontent.com/5610400/161243148-7e269825-6b01-4d3e-8f6f-ed6ee0dfe85c.png)
![image](https://user-images.githubusercontent.com/5610400/161243190-bad8c504-daa0-425c-8116-639d61a3df63.png)


-d perf -d memory: 
[darktable-log.txt](https://github.com/darktable-org/darktable/files/8396680/darktable-log.txt)


I'm not gonna be running this build very long :) Any more testing you want me to do? 
[msinfo32.txt](https://github.com/darktable-org/darktable/files/8396696/msinfo32.txt)

**Comment by gi-man** [comment]
There is something odd going on. I see that the chromatic module takes longer to execute when it creates the preview than the full. I would think that should be the opposite. 

64.024267 [dev_pixelpipe] took 0.878 secs (13.359 CPU) processed `chromatic aberrations' on CPU, blended on CPU [preview]
66.136581 [dev_pixelpipe] took 0.624 secs (8.625 CPU) processed `chromatic aberrations' on CPU, blended on CPU [full]

**Comment by gi-man** [comment]
To add to the mystery, we have similar systems (AMD Ryzen 5700G CPU + Nvidia 3060 on Win11). I'm Bill 798 compile and I'm not seeing the same problem.

**Comment by spyfish** [comment]
yeah I just downgraded back to Bill 798 as i encountered another issue (Retouch look good in main view, but gets distorted in export.) 

But in the process I lost ALL my edits. Seems like the XMP files are not backwards compatible. This hurts badly. Hours and hours of work lost. I think i will stop experimenting with the newer builds.

**Comment by spyfish** [comment]
Ok i was able to recover by re-upgrading and restore the library file. Sorry to be off topic, but any way i can get the XMP files to work on bills 798? I tried deleting the library file to import again with the XMPs, but it doesn't recognize them :( 

I'll report the new issue with retouch

**Comment by gi-man** [comment]
First, let's deal with your original issue. Now with 798, do you still have the issue with CA module and blank preview screen?

Most xmp changes are not forward compatible. You might be able to manually edit the xmp, but it is better to start over. In the future, keep your important edits separate from the your test environment.

**Comment by spyfish** [comment]
No, im not able to reproduce with 798. But not sure that's helpful as the sidecar isn't working. 

I tried fresh with blank config directory, imported the file without sidecar present. And for some reason its not writing a sidecar. I was hoping to edit in the history in 798 sidecar file. 

DT is set to write sidecar on import. If i can find or get a sidecar generated with 798, and edit in the history from previous test, maybe it could be comparable.

**Comment by spyfish** [comment]
Ive done some more testing: 

Ive narrowed it down to Local Contrast in Multiply mode + Chromatic abberation. Without Local contrast in Multiply mode, im unable to reproduce. 

I can reproduce on these builds: 
3.9.0+925~g911f71370 (Todds portable build)
darktable-3.9.0+873~g730ee22ff (My Build) 

I can NOT reproduce on bills 798 build. So it appear its something new. (Perhaps post DB upgrade?) 
 
As ive mentioned, its really not a big problem for me. Just wanted to report it in case its useful in development. I would be curious though if someone else can also reproduce on these builds. And if not, just close it out. Thanks
