### ISSUE TITLE
RFC: Handle OpenCL default settings nowadays

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#11444]
**Is your request for comments related to a problem? Please describe.**
There have been a number of changes to the OpenCL subsystem targeted for better default performance and easy setup for users. There a a number of remaining "issues" i would like to get commented as a) i might not oversee all problems and b) only have access to intel & nvidia hardware on linux myself.

**Problem 1: handling on-cpu devices**
Per default we disabled on-cpu devices a long time ago due to performance and stability problems. From last years reading pixls and issues here this does seem to be the case any longer. So:
1. Shall we enable on-cpu devices per default?
2. Shall we even remove the check as not necessary any more?
3. At least allow on-cpu for AMD?
4. Any CPU & driver & OS combination that should be blacklisted as notoriously begging for problems?

**Problem 2: number of event handles**
We use a list of 25 cl events per default, this is much less than used while developing a typical image (>60) and thus slightly reduces performance. A larger number had not been suggested as a) opencl internals might not be sufficient and b) using more sys memory. The number is pretty arbitrary, for on-device we can assume at least 1024 since opencl 2.0 and for on host this is limited by sys mem.
1. shall we hard-code this to something sensible or use a new default like 256? (Should be enough for almost all use-cases without having any perf drop)

**Problem 3: using "opencl_disable_drivers_blacklist"**
1. If we think a driver should be blacklisted, should we really care to allow enabling?

**Problem 4: windows users reporting OpenCL crashes**
Can we do anything here?

**Comment by jenshannoschwalm** [comment]
There is a bug in pinned_memory stuff i am tracking down atm so closing for now

**Comment by MStraeten** [comment]
Better don’t hard code settings if you can’t be sure there’s a system configuration around in which different settings might be better.
So for problem 1-3 being able to use custom preferences should be preferred  (I run darktable sometimes on a windows notebook with enabled opencl also on a system with blacklisted driver without having issues and it’s quite slower if opencl isn’t used…)
At least on my MacBooks i had to tweak opencl settings to achieve a stable behaviour (e.g. i had to increase numbers of event handles some years ago to avoid crashes https://github.com/darktable-org/darktable/issues/2384)
Problem 4: opencl kernels are built system specific so it‘s not easy to reproduce system specific stuff - and if it’s not reproducible it’s almost impossible to fix …

**Comment by jenshannoschwalm** [comment]
@MStraeten thanks. Especially for pointing at #2384, i missed that. I will have (again) a look at that code section managing/reallocation the event handle buffer.

Which is the blacklisted driver in use, pocl?

**Comment by MStraeten** [comment]
It must be an intel driver, never checked it since it was fine after tweaking darktablerc - will check …
