### ISSUE TITLE
Missing any EXIF Tags regarding shot date in exported jpg

### ISSUE THREAD

**Issue by ylz** [darktable-org/darktable#11455]
Darktable version: 3.8.1 stable
Environment: Linux Ubuntu 21.10
Camera: Canon EOS M6ii (tested with RAW and jpg)

In any in DT exported jpg image, all EXIF tags regarding image creation are missing.

Tags found in original image:
```
dani@leopard:~/Documents/Fotos/22w13/exp$ exiftool ../IMG_9643.CR3 | grep -i date
File Modification Date/Time     : 2022:03:27 16:30:50+02:00
File Access Date/Time           : 2022:04:03 13:47:45+02:00
File Inode Change Date/Time     : 2022:03:27 17:49:04+02:00
Date/Time Original              : 2022:03:27 14:30:47
Create Date                     : 2022:03:27 15:30:47+02:00
Modify Date                     : 2022:03:27 15:30:47+02:00
Track Create Date               : 2022:03:27 15:30:47+02:00
Track Modify Date               : 2022:03:27 15:30:47+02:00
Media Create Date               : 2022:03:27 15:30:47+02:00
Media Modify Date               : 2022:03:27 15:30:47+02:00
Create Date                     : 2022:03:27 14:30:47.09+01:00
Date/Time Original              : 2022:03:27 14:30:47.09+01:00
Modify Date                     : 2022:03:27 14:30:47.09+01:00
```

Tags found in exported image:
```
dani@leopard:~/Documents/Fotos/22w13/exp$ exiftool 22w13\ nussbaum.jpg | grep -i date
File Modification Date/Time     : 2022:04:03 13:50:28+02:00
File Access Date/Time           : 2022:04:03 13:52:41+02:00
File Inode Change Date/Time     : 2022:04:03 13:52:36+02:00
Profile Date Time               : 2022:04:03 11:27:56
```

**Comment by gi-man** [comment]
What are your export parameters in the export module for exif data?

**Comment by Nilvus** [comment]
As this is probably just a wrong setting in export module, as pointed by @gi-man, I close this one. You have all things in link reported by him here. By default, darktable do not set many things to export (for privacy reasons mainly). You have to set what datas you want to export with the image.

**Comment by ylz** [comment]
@gi-man @Nilvus thanks for your fast answers. Somehow these settings were changed after the upgrade from 3.6.x to 3.8.x in my case. Problem solved, thanks again.
