### ISSUE TITLE
Unsupported Compression 7

### ISSUE THREAD

**Issue by ngoldack** [darktable-org/darktable#11459]
Hello. When i try to use darktable with a raw image from a Sony Alpha 7 IV (Sony ILCE-7M4) I get the following error message:
`
level=warning msg="index: failed converting 20220325_181951_26B3E63A.arw to jpeg ([rawspeed] (20220325_181951_26B3E63A.arw) virtual rawspeed::RawImage rawspeed::ArwDecoder::decodeRawInternal(), line 147: Unsupported compression 7\n[dt_imageio_export_with_flags] mipmap allocation for /photoprism/storage/sidecar/2022/03/20220325_181951_26B3E63A.arw.jpg' failed\n[imageio_storage_disk] could not export to file: /photoprism/storage/sidecar/2022/03/20220325_181951_26B3E63A.arw.jpg'!\n)
`

Is there a way to fix this? Thanks in advance.

**Comment by ptilopteri** [comment]
Your camera is not in the supported list.  Please follow the instructions
at https://www.darktable.org/resources/camera-support/

**Comment by Darkdriver84** [comment]
Hopefully the lossless compression will be supported soon. the workaround with conversion to DNG is not a perfect solution.
