### ISSUE TITLE
Access Violation at location 00007FFB35DE96E6 in module libdarktable.dll

### ISSUE THREAD

**Issue by CobusBeukes** [darktable-org/darktable#11456]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?** 
No

**Describe the bug/issue**
Darktable fails to process and export tif file

**To Reproduce**
1. Run darktable.cli.exe (see batch file in .zip below)
2. Run at least one QT Ver 5.15 application
3. C:\Config>"C:\Program Files\Darktable\bin\darktable-cli" 1_99_40274_369_180.0_2.500_9.0_6_8_4.tif 24.xmp 1_99_40274_369_180.0_2.500_9.0_6_8_4_XMP24.tif
output file already exists, it will get renamed

(darktable-cli:9488): Gtk-WARNING **: 16:10:56.556: gtk_disable_setlocale() must be called before gtk_init()
[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace_cl] error on copy image for color transformation
[dt_ioppr_transform_image_colorspace_cl] error on copy image for color transformation
[contrast equalizer] unable to allocate working memory
[local laplacian cl] failed: -4

**Expected behavior**
C:\Config>"C:\Program Files\Darktable\bin\darktable-cli" 1_99_40274_369_180.0_2.500_9.0_6_8_4.tif 24.xmp 1_99_40274_369_180.0_2.500_9.0_6_8_4_XMP24.tif
output file already exists, it will get renamed

(darktable-cli:9344): Gtk-WARNING **: 16:13:14.003: gtk_disable_setlocale() must be called before gtk_init()
[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[export_job] exported to `1_99_40274_369_180.0_2.500_9.0_6_8_4_XMP24_94.tif'

**Platform**

* darktable version : 3.6.1 and 3.8.1
OS Name:                   Microsoft Windows 10 Enterprise LTSC
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Admin
Registered Organization:
Product ID:                00424-80002-25962-AAOEM
Original Install Date:     2020-07-24, 15:05:28
System Boot Time:          2022-04-03, 14:17:39
System Manufacturer:       CINCOZE
System Model:              GM-1000
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~3192 Mhz
BIOS Version:              American Megatrends Inc. 5.13, 2020-03-23
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+02:00) Harare, Pretoria
Total Physical Memory:     8,091 MB
Available Physical Memory: 4,077 MB
Virtual Memory: Max Size:  8,091 MB
Virtual Memory: Available: 1,683 MB
Virtual Memory: In Use:    6,408 MB
Page File Location(s):     N/A
Domain:                    XRAY
Logon Server:              \\XXXX
Hotfix(s):                 20 Hotfix(s) Installed.
                           [01]: KB5009472
                           [02]: KB4470788
                           [03]: KB4487038
                           [04]: KB4535680
                           [05]: KB4558997
                           [06]: KB4566424
                           [07]: KB4570332
                           [08]: KB4577586
                           [09]: KB4577667
                           [10]: KB4587735
                           [11]: KB4589208
                           [12]: KB4598480
                           [13]: KB4601393
                           [14]: KB5000859
                           [15]: KB5001404
                           [16]: KB5005112
                           [17]: KB5011503
                           [18]: KB5008287
                           [19]: KB5009642
                           [20]: KB5005701
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) I210 Gigabit Network Connection
                                 Connection Name: External
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.0.220
                                 [02]: fe80::8d53:b531:38fc:d0e0
                           [02]: Intel(R) Ethernet Connection (7) I219-LM
                                 Connection Name: Internal
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.0.3.105
                           [03]: VMware Virtual Ethernet Adapter for VMnet1
                                 Connection Name: VMware Network Adapter VMnet1
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.98.254
                                 IP address(es)
                                 [01]: 192.168.98.1
                                 [02]: fe80::19d6:204b:1cfb:7e50
                           [04]: VMware Virtual Ethernet Adapter for VMnet8
                                 Connection Name: VMware Network Adapter VMnet8
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.86.254
                                 IP address(es)
                                 [01]: 192.168.86.1
                                 [02]: fe80::dd02:62cd:c04:61cf
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
* Graphics card     :  NVIDIA Quadro T1000
* Graphics driver   :  27.21.14.5206
NVIDIA System Information report created on: 04/03/2022 16:41:07
System name: XXXX

[Display]
Operating System:	Windows 10 Enterprise LTSC 2019, 64-bit
DirectX version:	12.0 
GPU processor:		Quadro T1000
Driver version:		452.06
Driver Type:		DCH
Direct3D API version:	12
Direct3D feature level:	12_1
CUDA Cores:		896 
Core clock:		1650 MHz 
Memory data rate:	12.00 Gbps
Memory interface:	128-bit 
Memory bandwidth:	192.03 GB/s
Total available graphics memory:	8141 MB
Dedicated video memory:	4096 MB GDDR6
System video memory:	0 MB
Shared system memory:	4045 MB
Video BIOS version:	90.17.46.00.FE
IRQ:			Not used
Bus:			PCI Express x16 Gen3
Device Id:		10DE 1FF9 4400144A
Part Number:		4904 0010

[Components]

nvui.dll		8.17.14.5206		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.14.5206		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.14.5206		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.14.5206		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.14.5206		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		27.21.14.5206		NVIDIA Workstation Server
nvWSS.dll		27.21.14.5206		NVIDIA Workstation Server
nvViTvSR.dll		27.21.14.5206		NVIDIA Video Server
nvViTvS.dll		27.21.14.5206		NVIDIA Video Server
nvLicensingS.dll		6.14.14.5206		NVIDIA Licensing Server
nvDevToolSR.dll		27.21.14.5206		NVIDIA Licensing Server
nvDevToolS.dll		27.21.14.5206		NVIDIA 3D Settings Server
nvDispSR.dll		27.21.14.5206		NVIDIA Display Server
nvDispS.dll		27.21.14.5206		NVIDIA Display Server
NVCUDA64.DLL		27.21.14.5206		NVIDIA CUDA 11.0.228 driver
nvGameSR.dll		27.21.14.5206		NVIDIA 3D Settings Server
nvGameS.dll		27.21.14.5206		NVIDIA 3D Settings Server

* CMAKE_BUILD_TYPE  :  Std, download, unchanged

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with version 3.6.1
 - Can you reproduce with a RAW or Jpeg or both? **TIF**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **NA**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?
[Access Violation.zip](https://github.com/darktable-org/darktable/files/8404780/Access.Violation.zip)
Please download and unzip Access.Violation.zip, rename 24.txt to 24.xmp, then run t24.bat

**Comment by wpferguson** [comment]
You only have 4GB of memory and you are running out.  Just running darktable by itself is enough to use all of your memory.

**Comment by CobusBeukes** [comment]
Dear wpferguson, you are correct!
I did not realize that UWF removed the pagefile behind my back!
A BIG THANK YOU!
