### ISSUE TITLE
Saving edited metadata in the JPEG exif on export

### ISSUE THREAD

**Issue by axettone** [darktable-org/darktable#11466]
Feature request: I spend so much time editing metadata in my photographs, but I can't see anything (other then CAMERA metadata) in the exported JPEG's EXIF.

If I edit "title", "author" (...) fields in metadata, I'd like to see them in the exif in the exported JPEG

**Comment by kmilos** [comment]
And I meant check the export settings.

**Comment by axettone** [comment]
> And I meant check the export settings.

Thank you! It was not so easy to find. I think it would be better to put a checkbox like "export metadata" in the "Export" panel with a "Advanced option" button (IMHO).

**Comment by Nilvus** [comment]
> > And I meant check the export settings.
> 
> Thank you! It was not so easy to find. I think it would be better to put a checkbox like "export metadata" in the "Export" panel with a "Advanced option" button (IMHO).

That's not same thing and it's had been done on purpose to not set them by default and let them in export setting. Metadata could be some private datas and, for example, publishing images on the web could show not wanted datas. It's done for privacy reasons.

Putting a checkbox like what you propose would not help as this will not answer on which datas to set by default or not? All, I'm quite sure many will not like or be agree with that. Which ones would suit most people (I'm quite sure this will be hard to define)?

**Comment by axettone** [comment]
> That's not same thing and it's had been done on purpose to not set them by default and let them in export setting. Metadata could be some private datas and, for example, publishing images on the web could show not wanted datas. It's done for privacy reasons.
> 
> Putting a checkbox like what you propose would not help as this will not answer on which datas to set by default or not? All, I'm quite sure many will not like or be agree with that. Which ones would suit most people (I'm quite sure this will be hard to define)?

I totally agree about your concerns about privacy. I know how much useful information you can gather from metadata. More: how much bad companies can use this data against people. Metadata should be set off by default. Let's forget the checkbox... what about a simple button "Metadata settings..." in the export panel? Expert users know about metadata, but I believe the current way of reaching these settings is not intuitive. I believe that this button should be placed in the "format options" subpanel, so to speak. Of course, mine is only an opinion. Anyway thanks for the help, now I know how.

**Comment by axettone** [comment]
I think this button would work even as an effective "reminder", increasing the privacy level. If I set some metadata to be exported today, a button would remind me to set them off tomorrow. The "preferences" menu item does not work well this way.

**Comment by phweyland** [comment]
At the beginning it was a gear wheel button next to the export one. I moved it to the module's preferences when working on other modules' preferences.
There is no issue for me to go back to the original configuration. @elstoc if my memory is not too bad you were not so happy with that change. What's your view now ? 
Any other opinion ?

**Comment by elstoc** [comment]
I felt that the preferences item in the presets menu often just hid useful settings away and made them harder to find. IMO virtually all of them would have been better as an in-module button or just being left in the global preferences (especially now that we're talking about some sort of "expert mode" that will expose more preferences).

**Comment by Nilvus** [comment]
At least, we could add a message to explain possibility/need to set metadata, on tooltip when hovering export button. I plan to propose something for that.

About where preferences are on the module, as a gear button or in an hamburger menu, it's the same. Actual settings on preferences of the module are better related to the module than inside main preferences for me.

**Comment by phweyland** [comment]
Set back the metadata preferences button.
BTW don't forget metadata preferences are embedded in presets (each preset can have its own metadata preferences).
