### ISSUE TITLE
revert altered slider click behaviour (#10499)

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11462]
The current slider behaviour in darktable 3.8.1 is that _wherever_ you click (and optionally drag) on a slider (including its name and current value labels), that click is used to change the slider's value (the triangle on the slider moves to the same horizontal position as your mouse and continues to move when you drag it). Similarly, double-click anywhere resets the value.

This behaviour was changed in #10499 so that clicking on the label/upper-left-hand-side of the slider grabs focus without changing anything and clicking on the value/upper-right-hand-side pops up the edit box. Unfortunately this means that any "value-change" clicks/drags need to be much more precise - the clickable area has roughly halved (I think).

I've used this for a while now and I'm afraid I just can't get used to it - I keep missing the clickable area. Because my habit is to click the slider and only move my mouse once I've moved my eyes back to the image, I often drag without actually affecting the value and it's annoying.

IMO the new functionality does not add anything useful. It's already possible to bring up the edit box with right-click and focusing could equally be done with Ctrl+click without impacting the more useful behaviour. The same (Ctrl+click) could also be applied to parametric mask sliders.

This has already been discussed in the original PR and under a separate issue but I'm raising this with a more complete description for visibility.

**Comment by RawConvert** [comment]
I also think the new behaviour should be reversed.

**Comment by TurboGit** [comment]
@dterrahe : As you had envisioned this change is changing habit and probably beyond the limits :) Are you ok for a revert of this behavior or have you something in mind to avoid the issue to actually grab the sliders? TIA.

**Comment by todd-prior** [comment]
Thanks for explaining this. I thought it was part of the recent adjustments to dialogue boxes. I don't know if it is muscle memory or what but I don't enjoy it so I would vote to revert it.

**Comment by elstoc** [comment]
> focusing could equally be done with Ctrl+click

This would also be consistent with the shortcut to give focus to a module (ctrl+click on the on/off button).
