### ISSUE TITLE
Skin hue line in color vectorscope

### ISSUE THREAD

**Issue by axettone** [darktable-org/darktable#11467]
Feature request: the skin hue line in the color vectorscope.

I'd like to have this reference, as other popular, industry-standard tools have. I know it's something more perceptive than mathematical, but I think it's useful anyway.

Alternative: make this as a default-off, optional feature.

**Comment by MStraeten** [comment]
which skin line? caucasian? asian? inuit? ...?
Is there really one size fits it all?

**Comment by axettone** [comment]
> which skin line? caucasian? asian? inuit? ...? Is there really one size fits it all?

Apparently yes. Check this out: https://helpx.adobe.com/it/premiere-pro/how-to/correct-skin-tones.html

"This skin tone line appears for all people regardless of their skin color. "

**Comment by MStraeten** [comment]
have look at https://www.sciencedirect.com/science/article/pii/S0022202X92903477 (and that’s just European ethnicity)
And then you might define which value the line should represent for ‚all‘ people ;)
In difference to movies where consistency of skin tones over a couple of scenes is more important then an exact reproduction in photography the real skin tone is essential.

**Comment by axettone** [comment]
Ok guys, your arguments seem convincing to me. @todd-prior  I'll give a try with color match! Thank you!

**Comment by todd-prior** [comment]
> Ok guys, your arguments seem convincing to me. @todd-prior I'll give a try with color match! Thank you!

Ha....I wasn't trying to convince you...just suggest a few options  :)
