### ISSUE TITLE
Sidecar files created for jpegs on import with "write sidecar...after edit" set

### ISSUE THREAD

**Issue by amxj9** [darktable-org/darktable#11477]
Setting "write sidecar file for each image" to  "after edit"  imports raw files without writing sidecar files as expected.  However, when I import a folder of raw (orf) + jpeg images, an xmp sidecar file is still written for the jpeg. It works as expected for both if set to "on import" or "never".

**To Reproduce**

1. Go to settings->storage->xmp
2. Set "write sidecar file for each image" to  "after edit"
3. import a folder of raw + jpeg images
4. Imported folder has new .jpg.xmp files

**Expected behavior**
No .jpg.xmp files created on import.

**Platform**

* darktable version : e.g. 3.8.1
* OS                : Linux - kernel 5.16.11
* Linux - Distro    : NixOS
* Memory            : 8GB
* Graphics card     : Intel
* Graphics driver   : Intel
* Desktop           : Sway

**Additional context**

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

**Comment by gi-man** [comment]
On import, do you apply any metadata (eg. copyright)?

**Comment by amxj9** [comment]
No metadata applied at all.  Parameters: "ignore exif data" and "apply metadata" are unchecked, "initial rating" is default (1), and all the other fields are blank.

**Comment by jenshannoschwalm** [comment]
> Only if they are raw+jpeg i.e. same base filename.

Because they get auto-grouped.

**Comment by amxj9** [comment]
> > Only if they are raw+jpeg i.e. same base filename.
> 
> Because they get auto-grouped.

That's true, but surely this doesn't need a sidecar to be created for the jpg?  I can't see anything in the xmp file that indicates grouping:

```
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2020:03:29 17:20:39"
   xmp:Rating="1"
   xmpMM:DerivedFrom="20200329_172039.jpg"
   darktable:import_timestamp="1649391664"
   darktable:change_timestamp="-1"
   darktable:export_timestamp="-1"
   darktable:print_timestamp="-1"
   darktable:xmp_version="4"
   darktable:raw_params="0"
   darktable:auto_presets_applied="0"
   darktable:history_end="0"
   darktable:iop_order_version="2">
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq/>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
```

**Comment by lfptmsm** [comment]
I have the same issue with migration from Lightroom. It is a challenge to get ratings transferred to DT. Instead they are set to default (1). Lightroom seems to be capable to create XMP sidecar files (and customize metadata in Library Metadata section) also for JPGs but it seems like DT is not prepared to this.

**Comment by indy07cz** [comment]
I have the same issue with DT4.2 and Olympus RAW+JPEG files.

**Comment by jenshannoschwalm** [comment]
Fixed in master

**Comment by dortusermac** [comment]
I have the same issue in darktable 4.0 running on macos Catalina. Is there any solution?
