### ISSUE TITLE
Rotate and perspective : Straighten with Right click + drag doesn't work

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#11476]
**Did you buy darktable from an application store ?** no

**Describe the bug/issue**

I'm using a trackpad on ubuntu (Apple's magic trackpad) and Right clic + drag to straighten a picture does nothing. 
Right clic works fine when I want to delete a mask or if I right clic on a slider to enter the desired value.
It also works fine in the perspective part of the module, if I draw a line I can delete it with right click. But I can draw a line with right clic + drag too! 

**To Reproduce**
You may have a trackpad to reproduce
1. open a picture and activate and/or roll out the **rotate and perspective** module
2. right clic and drag in the picture, no line appears
3. release trackpad button, the picture doesn't rotate.

**Expected behavior**

A line should appear between the cursor and the starting right-cliked point in the picture.
When the button are released, the picture should rotate depending of the angle of the line.

**Platform**

* darktable version : 3.9.0+924~g4a6ba5063
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04  
* Graphics card     :  Radeon RX 580
* Graphics driver   :  amdgpu pro
* OpenCL installed  : Yes 
* OpenCL activated  :  Yes 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**

The trackpad is wireless, connected with bluetooth and set up in ubuntu's preferences.

 - Can you reproduce with another darktable version(s)? **yes**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by hqhoang** [comment]
the line does appear for me, but looks like it multiplies the current angle by 2 before adding/subtracting the new angle (3.9.0+955~gb860f4a0c-dirty)

**Comment by hqhoang** [comment]
Not sure what changed, but I don't have the problem on master anymore. Perhaps we can close this issue.
