### ISSUE TITLE
FR: Side by side snapshot view 

### ISSUE THREAD

**Issue by pedrorrodriguez** [darktable-org/darktable#11471]
I am thinking something like the culling mode in the lighttable, but for snapshots inside the darkroom. Basically two full images next to each other. One being static (snapshot), and the other editable. 

This is useful when working with reference images. You could have a snapshot of any image right next to the one one you are editing, and make changes accordingly. This can be useful to unify a set of images, or to try to replicate a particular look. 

The current implementation of snapshots is useful for before/after comparison of the same image. 

Would this be possible?

**Comment by TurboGit** [comment]
> Would this be possible?

It is already possible. Do a snapshot, move to next image and select the snapshot. A snapshot is global and not restricted to one image. Would that work?

**Comment by Nilvus** [comment]
To complete @TurboGit, the only thing that could improve that (I think) would be to have snapshots adjustable (when opening or closing panels for example). But seems quite hard to do. See my old issue about that:  #2784

**Comment by pedrorrodriguez** [comment]
Thank you @TurboGit and @Nilvus for your responses. 

Actually I was referring to something else. I am aware that snapshots are global and not restricted to a particular image, hence why I thought my suggestion would be doable. 

We currently have two ways of previewing snapshots: a vertical and a horizontal overlay that we can slide from side to side. I am suggesting to add a third view mode, and that is side by side. The way the snapshot would behave as it does now, not zoomable, not editable, but right next to it we would have the full image we are working on, which we could adjust according to our reference. At the moment we can edit and zoom in and out while the snapshot is active, but we aren't able to view either the full snapshot or the full image at the same time.
 
Sorry to include a screenshot of Lightroom, but they have a feature like this:
![imaxe](https://user-images.githubusercontent.com/64545422/162176568-69687bbd-935c-44eb-8ee2-4948264a60e8.png)

**Comment by TurboGit** [comment]
The Lr screen shot is what culling mode is about. You can have 2 (or more) pictures side-by-side. See documentation. The culling mode is on lighttable (and not darkroom) which is equivalent to Lr library view as shown in your screenshot.

**Comment by difrkaguilar** [comment]
That is an excellent idea, to have the reference image on one side while the other is developed on the other and thus make the respective comparisons and adjustments without having to go to the lighttable. 

There might even be the possibility of marking a certain image to be seen in the second display screen and keep the development in the darkroom as the main screen for those who have the possibility of viewing on two monitors. But I think that as @nilvus raises, it does not seem to me that it is possible at this time because of the level of complexity involved in doing this type of programming.

I am not a programmer but I know how complex it can be.

**Comment by pedrorrodriguez** [comment]
I think @Nilvus was referring to a different issue, but I also don't know how hard this would be to implement

**Comment by Nilvus** [comment]
> I think @Nilvus was referring to a different issue, but I also don't know how hard this would be to implement

This is will probably be same complexity... And powerful computer when some modules are used

**Comment by pedrorrodriguez** [comment]
About the complexity, as I said, I have no idea. However, the powerful computer part leaves me wondering if my point came across. This shouldn't be more taxing than regular snapshots. Right now you can enable a snapshot and simultaneously edit your picture without a performance hit. You can't view both pictures completely, but you csn make those changes. 

I believe lightroom is able to look at two raw files, sort of like darktable's culling mode. That's not what I'm proposing, though. 

Since snapshots are global, I could import a reference jpeg or png and take a snapshot of it. Then I would move to the image I want to work on and activate that snapshot in this side by side view I'm advocating for, so that I can make changes based on my reference. The reference would still be a snapshot, just the way this snapshot is presented would not be an overlay.
