### ISSUE TITLE
Darktable 3.8.1 crashes after launch

### ISSUE THREAD

**Issue by clavinet** [darktable-org/darktable#11488]
Steps to reproduce: launch program
[darktable_bt_OI4WK1.txt](https://github.com/darktable-org/darktable/files/8457359/darktable_bt_OI4WK1.txt)

* darktable version : 3.8.1
* OS                : openSUSE Tumbleweed 20220403
* Memory            : 32 GiB
* Graphics card     : AMD RX 570
* Graphics driver   : amdgpu (OSS)
* OpenCL installed  : ROCm 3.4.1
* OpenCL activated  : no
* Xorg              : 21.1.3
* Desktop           : Plasma 5.24.4
* GTK+              : 3.24.33
* gcc               : 11-6.1
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
unavailable

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
No, darktable starts fine without config 

- Do you use lua scripts?
 No

backtrace attached

**Comment by ptilopteri** [comment]
amd gpu's are known to have opencl issues.  does it crash if
you disable opencl?

**Comment by clavinet** [comment]
I just noticed that when I stop another OpenCL render program, darktable launches fine with my config.

Even though OpenCL was disabled in my configuration, darktable seems to probe it on launch and fails to start if it's in use by another program.

I tried enabling it and now darktable can't start even if nothing else is using OpenCL.

**Comment by ptilopteri** [comment]
note that I am not an expert, but
with dt not running, you might edit ~/.config/darktable/darktablerc
and make sure that
  opencl=FALSE

then try

**Comment by clavinet** [comment]
Now darktable needs OpenCL to be running on the GPU already to not crash...

I think I'll just remove ROCm, what a horrible piece of software.

**Comment by ptilopteri** [comment]
one more shot, remove ~/.config/darktable/darktablerc

dt will regenerate it

**Comment by victoryforce** [comment]
> I think I'll just remove ROCm, what a horrible piece of software.

You don't have to remove it. You should just run `darktable --disable-opencl`.

**Comment by clavinet** [comment]
I removed my old darktablerc now and it starts fine.
