### ISSUE TITLE
regressions tonight

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11492]
For the record tonight we had many regressions, so an issue with merged done last 24h.

The wrong commit is between: 3c751d693..797080c4e

Total test 90
Errors     23
   - 0004-masks
   - 0005-orientation-minus-90
   - 0006-orientation-plus-90
   - 0007-orientation-180
   - 0008-flip-h
   - 0009-flip-v
   - 0010-flip-hv
   - 0011-gdnd-90
   - 0012-gdnd-45
   - 0013-denoiseprofile-wavelets
   - 0014-filmic-rgb
   - 0015-shadhi-bilateral
   - 0016-lowpass-bilateral
   - 0018-perspective-corr
   - 0019-color-mapping
   - 0020-denoise-nlmeans
   - 0021-retouch-wavelets
   - 0024-contrast-equalizer
   - 0026-haze-removal
   - 0027-denoiseprofile-nlmeans
   - 0033-blending-modes-uniform
   - 0034-blending-modes-parametric
   - 0075-retouch-heal
see test-20220410-062200.log

**Comment by TurboGit** [comment]
I've not looked at this but may be the new highlight reconstructions model being a bit more invasive that thought at first as the other commits seems less probable (the GPU is not used for the nightly regression suite).

**Comment by jenshannoschwalm** [comment]
Can't test here but
1. the corrected temp stuff via exif?
2. we can now do without cpu tiling?

**Comment by jenshannoschwalm** [comment]
I think i got it, when setting the default for highlights reconstruction the clipping threshold this is now 0.995 instead of 1.0 ???

**Comment by TurboGit** [comment]
@jenshannoschwalm : Thanks, I'm back with some time, I'll look at this right away.

**Comment by TurboGit** [comment]
@jenshannoschwalm : I confirm reverting clip to 1.0 as default fixes issues (at least most of them, not sure I have tested all of them manually). Thanks a lot for the hint !
