### ISSUE TITLE
Map view: non-exact dropping of position on the map when only displaying count

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11508]
Darktable 3.8.x

In map view, select some image in the bottom filmstrip and drag-n-drop them on the map: the position will be slightly at the right of the position where the marker was at the moment of releasing the mouse bottom.

The right shift has the same pixels amount whatever the map zoom.

**Comment by pbb72** [comment]
I can not reproduce this with Darktable 3.8.1. Both when dragged from the bottom filmstrip and when dragging images that are on the map already, images are placed at exactly the same location on the map as where they were dropped.

I did not check if the lat/long coordinates are correct, but the report seemed to be concerning placement on the map.

**Comment by paolobenve** [comment]
@pbb72 thank you for checking

The displacement is visible only at maximum map zoom, did you check it in these conditions?

**Comment by pbb72** [comment]
If I see right, the maximum zoom is depending on the map source. I tried with "Public Transport", which seems to have the highest zoom. I did not notice any shift when dropping an image:
![ezgif-1-692e6f3b3d](https://user-images.githubusercontent.com/1436366/175987071-50aea949-3b8a-4daf-9c34-89c9fce8a753.gif)

**Comment by paolobenve** [comment]
I could check that the displacement is related to screen pixels, not to the map itself, because it happens at all zoom levels with the same graphical amount.

https://user-images.githubusercontent.com/1417508/176621511-8c60d737-dba0-4472-8cc0-38cdeb6d48fa.mp4

**Comment by pbb72** [comment]
Operating system might also be an important factor here. What OS are you using?

**Comment by paolobenve** [comment]
ubuntu linux
