### ISSUE TITLE
MSYS2 build errors

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#11515]
**Describe the bug/issue**
MSYS2 is failing to compile build in the nightly executions or when I build my on my PC

**To Reproduce**
Follow the Build.md on master

**Which commit introduced the error**
It is likely an upstream issue. I'm raising this issue so someone doesnt spend hours trying to figure out what is going on like I just did.

**Platform**
Windows problems and upstream

**Additional context**
The JSONSCHEMA package was recently updated in MSYS2. Using the new package, the validation of the noiseprofile fails and the build stops. The validation is part of CMakelist to make sure the structure of the JSON file with the noiseprofile data is correct.

https://packages.msys2.org/package/mingw-w64-x86_64-python-jsonschema

This is the extent of what I was able to research. I noticed that @kmilos did some changes to that package, but this validation is still failing. I will start a bug report in that package tomorrow (too tired right now).

Workaround:
I edited the CMakelist to remove the if statement to check for JSON validation and it successfully compiled. 
Another workaround, dont use windows. :-)

**Comment by kmilos** [comment]
No need for additional bug reports, the fix for the python-jsonschema package is already in the queue, just need to wait for it to show up in the updates...

**Comment by ait-jorismak** [comment]
I downloaded the older 3.x package and installed it with pacman, and the build went fine.

As stated, the 4.x package for jsonschema is already fixed in mingw64/msys2 so a newer version should appear (if not already there ).

**Comment by kmilos** [comment]
You can also just uninstall python-jsonschema and CMake will just skip the validation (i.e. it is optional).

**Comment by gi-man** [comment]
> You can also just uninstall python-jsonschema and CMake will just skip the validation (i.e. it is optional).

I uninstalled and it did not skip the validation. The new update is waiting for a dependency.

I installed 3.x package and it built fine this morning.
