### ISSUE TITLE
color calibration module is changing the histogram even when set to bypass

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11516]
dt Master 3.9.0+941~g0617db125      Ubuntu 20.04      not sigmoid

To reproduce -
1. Load the raw from here https://discuss.pixls.us/t/color-calibration-module-am-i-doing-something-wrong/30362/4
2. Apply the attached XMP which is a skeleton edit with few modules used.
3. Toggle color calibration on and off and see the histogram change a little, especially the darker blue part.  Surely with bypass set and all the other settings at default, there should be no change?

[_DSC4665-jorismak-calibration.ARW----xmp-renamed-to-TXT.txt](https://github.com/darktable-org/darktable/files/8482256/_DSC4665-jorismak-calibration.ARW----xmp-renamed-to-TXT.txt)

![Screenshot from 2022-04-13 15-26-56](https://user-images.githubusercontent.com/16868433/163203342-f5f30692-6038-4098-afb9-0a30dac14c29.png)

**Comment by gi-man** [comment]
First, you should follow the Issue template to properly document the issue. This post is not clear around what the issue is, what is your expected behavior, etc. 

It seems to me that you are reporting that turning a module on and off changes the histogram view. Are you expecting no changes to the histogram view from turning the processing modules on and off?

**Comment by RawConvert** [comment]
Correct, I'm expecting no changes to the histogram because the color calibration module is set up to do nothing in this case, therefore I'd expect the histogram to stay the same whether the module is on or off.

**Comment by elstoc** [comment]
"bypass" isn't the same as "do nothing", it just means "do no adaptation". At default settings, the "gamut compression" slider is set to 1 and the "clip negative RGB from gamut" is ticked. Both of these controls are able to change the colours in the image.

I would expect that if you set "gamut compression" to 0 and untick "clip" you should get what you expect.

**Comment by RawConvert** [comment]
Thanks, you're right of course.  I thought gamut comp. 1 was neutral but I can see now it isn't.
I'll close this.
