### ISSUE TITLE
extract_wb.py for Windows - Presets for Panasonic Lumix DC-S5 camera

### ISSUE THREAD

**Issue by ntsarb** [darktable-org/darktable#11510]
**Is your feature request related to a problem? Please describe.**

I attempted to run extract_wb.py from Windows and got an error message. I looked into the code and realised it is written in a way that only works in Linux. 

**Describe the solution you'd like**

Update extract_wb.py to work on both Linux and Windows.

**Alternatives**

Write a separate version of extract_wb.py intended for each OS.

**Additional context**
Traceback (most recent call last):
  File "E:\ntsarb\Backups\Software Backup\Editors - Image\DarkTable\extract_wb.py", line 113, in <module>
    proc = subprocess.check_output(command, universal_newlines=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kmilos** [comment]
It works, you just need exiftool on the path as well.

**Comment by ntsarb** [comment]
> It works, you just need exiftool on the path as well.

I have it in the same folder as the python script. Does it need to be in the "path" defined in the environment variables?

**Comment by ptilopteri** [comment]
yes, or you need to alter the scripts to call it from the location on your system.

**Comment by ntsarb** [comment]
Thanks. It worked.

The Lumix DC-S5 has the following white balance modes:
Auto White Balance, Auto White Balance Cool, Auto White Balance Warm, Daylight, Cloudy, Shade, Incandescent, Flash, White Set 1-4, Color Temperature 1-4.

I shot at the following non-automatic and non user-configurable presets and for each value (-9 to +9) on the magenta-green axis, resulting into 95 permutations:
Daylight, Cloudy, Shade, Incandescent, Flash.

The outputs are attached.
[Panasonic DC-S5 White Balance Presents.txt](https://github.com/darktable-org/darktable/files/8483361/Panasonic.DC-S5.White.Balance.Presents.txt)

Is there any additional information that I need to submit for these presets to be included in the DarkTable project?

**Comment by kmilos** [comment]
> on the magenta-green axis

Er, that should have been [amber-blue](https://github.com/darktable-org/darktable/wiki/White-balance-presets#finetuned-properly) :(

**Comment by ntsarb** [comment]
> > on the magenta-green axis
> 
> Er, that should have been [amber-blue](https://github.com/darktable-org/darktable/wiki/White-balance-presets#finetuned-properly) :(

They were on the Amber-Blue axis; the error was in my comment, not in the photos. Updated my comment accordingly.

**Comment by kmilos** [comment]
Phew 😉
