### ISSUE TITLE
cmake warning

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#11524]
cmake warns about compatible libheif package configuration
requiring > 1.9.0
and 1.12.0 is installed

openSUSE Tumbleweed 20220412
NVIDIA GF106 [GeForce GTS 450], 390.147
darktable 3.9.0+1063~g3d95725cc
bit depth is 64 bit
normal build
SSE2 optimized codepath enabled
OpenMP support enabled
OpenCL support enabled
Lua support enabled, API version 6.1.0
Colord support enabled
gPhoto2 support enabled
GraphicsMagick support enabled
ImageMagick support disabled
OpenEXR support enabled
OpenCL on
i7 12-core 970
ram 36GB
5.17.1-1-default

installed:  libheif-devel-1.12.0-3.26.x86_64
                libheif1-32bit-1.12.0-3.26.x86_641
                libheif1-1.12.0-3.26.x86_64

CMake Warning at src/CMakeLists.txt:367 (find_package):
Could not find a configuration file for package "libheif" that is
compatible with requested version "1.9.0".

The following configuration files were considered but not accepted:

/usr/lib64/cmake/libheif/libheif-config.cmake, version: 1.12.0.0
/lib64/cmake/libheif/libheif-config.cmake, version: 1.12.0.0

**Comment by kmilos** [comment]
This was discussed already, can't find a link now...

Not a big deal: the find_package() fails in the "CONFIG" mode (looks for exact version), and then succeeds in the regular mode...

See find_package() CMake docs.

**Comment by kmilos** [comment]
It was on the forum: https://discuss.pixls.us/t/darktable-windows-insider-program-12-12/28263/23

**Comment by ptilopteri** [comment]
tks, closed
