### ISSUE TITLE
Defish for DX 10.5mm on Nikon FX camera (Lens correction support)

### ISSUE THREAD

**Issue by pengowray** [darktable-org/darktable#11527]
![image](https://user-images.githubusercontent.com/800133/163496656-5272e305-9a8c-438a-83be-cfeaab1744fc.png)

Hi, 

I'd like to be able to lens correct or otherwise defish my lens/camera combo in Darktable. Is there anything I can do to help get my lens/camera combo supported by the lens correction filter for defishing?

I have a Nikkor DX 10.5mm fisheye lens (see above image for details) which is made for cropped frame sensors. I've shaved off the built-in lens hood and use it with a Nikon D800 (full frame). I'm guessing it's the sensor size mismatch which is why it's not available in darktable?

Is there anything I can do to help get it supported? I tried picking another lens (in the lens correction filter) and fiddled with the settings. I could get something roughly undistorted/defished, but couldn't get it quite right.

Years ago I would use a propriety defishing filter in Photoshop which defishes the above like this: (probably should have picked a colour example)

![DSC_3647bw](https://user-images.githubusercontent.com/800133/163497633-bfcffdaa-29c5-4cf9-ab2a-8c8b45dabfd8.jpg)

It's not perfectly linear but getting close.

Getting back into photography and I miss using my old fisheye. I no longer have access to either Photoshop or the filter, and have been using Darktable and would love if I could use it for defishing this lens too.

I've uploaded the raw file to raw.pixls.us as `DSC_3647_UTS_in_Sydney_by_Pengowray.NEF` in case that helps.

Is there any way I can get this lens natively supported for FX cameras? Anything I can do to help?

**Comment by MStraeten** [comment]
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/
maybe that’s a solution…

**Comment by Nilvus** [comment]
As this is issue is related to lensfun library and not directly darktable (darktable use lensfun library for camera/lens support), I close this one.
