### ISSUE TITLE
missing refresh from filmstrip in darkroom

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11536]
**Describe the bug/issue**

In darkroom, if you reject a image in "all but rejected" filter" from filmstrip, the image is removed from filmstrip, the next image is selected on the filmstrip but it won't appear in the darkroom until you click on the thumb.

**To Reproduce**

0. Select "all but rejected" from lighttable filter
1. Go to 'darkroom'
2. Click on 'reject' icon on filmstrip
3. See image is removed but the next one is not displayed

**Expected behavior**

The selected image on the filmstrip should be the one displayed on the darkroom.

**Comment by ralfbrown** [comment]
Same behavior if you are filtering >= 3 stars and change the current image's rating from 3 to 2.

I actually prefer the current behavior of not automatically changing the image in center view, because there have been quite a few times in the past when I've accidentally changed rating when I meant to type a value for an IOP and then had the image disappear on me....

**Comment by TurboGit** [comment]
Ok, but then we have two options:
- do not select the next image
- or select it and refresh the center view

Having a selected image on filmstrip which is not displayed is weird to me, and I consider this a bug. Do you agree?

**Comment by AlicVB** [comment]
For the record, I've raised this when I have rewritten lighttable/filmstrip. And the current behavior, even if not perfect was the best compromise...
Moreover, the main problematic case was : 
- you have "all but reject filter"
- in darkroom, you reject the current image

What should happen ? 
1. changing the current image
2. keeping an unsynchronized filmstrip with all the issues that may cause
3. current behavior (synchronize the filmstrip by removing the current image from it but keeping the current image)

**Comment by TurboGit** [comment]
Ok, but then I would not select the next image in the filmstrip. It gets highlighted and so seems strange that this image is not shown. That's my main complaint.

**Comment by AlicVB** [comment]
hmm, then either we don't speak about the same thing either I can't reproduce : 
Here when I reject the current image, it is removed from filmstrip, but the next one is not selected and doesn't have the "top triangle" that indicate the current image...

**Comment by Nilvus** [comment]
@TurboGit: just tested and same as @AlicVB. The next image is not highlighted/selected.

**Comment by TurboGit** [comment]
Right, that was a confusion on my side. The mouse is over the next thumb and seems selected... But it is not.
