### ISSUE TITLE
Panasonic Lumix G2 support (please remove if this is in the wrong place - I am new here - TIA)

### ISSUE THREAD

**Issue by kucksy** [darktable-org/darktable#11534]
Hi Darktable development team - thanks for such an awesome tool.  I received a message in program to say that you required some sample RAW images from my Panasonic Lumix G2 for it to continue to be supported in future versions / editions of your software - have uploaded a few photos taken with my G2 under CC to the address specified. Just wanted to let you know.  Hope they help with the continued camera support for the Panasonic Lumix G2.  Thanks so much from Troy

**Comment by kmilos** [comment]
Thanks for taking the time to share your samples in order to keep dt supporting your camera.

This is a known issue already tracked at https://github.com/darktable-org/darktable/issues/11534 (please search before opening new issues).
