### ISSUE TITLE
Some collections filters don't combine with "date taken" filter

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#11539]
The work of collections filters have changed for the worse.

On Windows 7.
Before change. Commit https://github.com/darktable-org/darktable/commit/50349bd7edca9a0a6d4b65677a49dad7c270ab29

https://user-images.githubusercontent.com/15331117/163682393-5a47b96d-e95e-4bd7-b7e6-619268935f39.mp4

When it changed. Commit https://github.com/darktable-org/darktable/commit/2ee3589a67cfb10af0732d6940135b5cb5c61c6d

https://user-images.githubusercontent.com/15331117/163682431-8bfbf7ce-ac47-43ab-b5a8-5c9e69bf1da9.mp4

That is, I select a filter (eg "film roll") and get a list of all collections. I add (AND) the "date taken" filter, choose a period and the collections list is empty.

The problem still persists.

On Debian 11 is better. Only there is no highlighting of the periods to which the found collections belong. Like there:

![50349bd7edca9a0a6d4b65677a49dad7c270ab29 avi_timeline](https://user-images.githubusercontent.com/15331117/163682752-277bb234-6167-4104-90a2-48cf1ee36956.jpg)

**Comment by Nilvus** [comment]
Something for you @phweyland or @AlicVB, probably.

**Comment by esq4** [comment]
And if my memory serves me, once upon a time it was not required to click the mouse in the field of main filter (in my example "film roll") after selecting the period for the "date taken" filter.

**Comment by phweyland** [comment]
Starting to look at this and to understand the issue(s).
You are on windows and may suffer the bug #11582.

However, on linux I can see the following which corresponds somehow to your description.
With `date taken` alone in collection, if I make a selection on filmstrip, the collection's entry ([...;...]) and the images are correctly updated, but the list of dates in collection is not.
With` film roll` and `date taken` alone in collection, I see the same behavior.
If I change manually the entry values, the collection dates list is not updated either.

The collection list should be updated (and list only the included date) when 
- one changes the selection in filmstrip
- one changes the entry
- one selects `date taken` after having looked at `film roll` in collection

Do I understand the issue ?

**Comment by phweyland** [comment]
@AlicVB Probably a stupid question, sorry. For collection which supports a range, I can select one value (double-click) and see the corresponding images, for example aperture. Shift-click allows to highlight several values but not to filter the corresponding images. Is there a way to filter them (or to set the entry) ?

**Comment by AlicVB** [comment]
@phweyland : no, it's an issue with the "click" event routine... I have done a fix for that for the other issue with dates you have just fixed... Let me five minute to push a PR :)
otherwise if you are out of patience, you can set "single click" in prefs too ;)

**Comment by AlicVB** [comment]
@phweyland : see #11636

**Comment by phweyland** [comment]
Thanks, the single click lets me make more tests.

There is a bit of mess here.
On flat list there are 2 treatments of range:
- when limits are existing values => range_select() => still displays the full list
- when limits do not exist in the value set => list_match_string()

On the tree list there is only one treatment of range:
- when limits are existing values => range_select() but doesn't work if timeline select dates which are not in the list
- tree_match_string() doesn't treat the range.

I think we should have only one algo. I'll try to make work the range_select() in all cases.

**Comment by esq4** [comment]
> The collection list should be updated (and list only the included dates) when
> 
> * one changes the selection in filmstrip
> * one changes the entry
> * one selects `date taken` after having looked at `film roll` in collection
> 
> Do I understand the issue ?
> 
Yes, this is similar to the previous behavior.


I built master for Windows (commit be0149c9adfa02537a427af78c64cff5468ddca3 ). Behavior became like before change (on commit https://github.com/darktable-org/darktable/commit/50349bd7edca9a0a6d4b65677a49dad7c270ab29 ). But there is no highlighting of the periods to which the found collections belong.

**Comment by phweyland** [comment]
> But there is no highlighting of the periods to which the found collections belong.

OK. Working on this.

**Comment by esq4** [comment]
> The collection list should be updated (and list only the included dates) when
> 
> * one changes the selection in filmstrip
> * one changes the entry
> * one selects `date taken` after having looked at `film roll` in collection

I built master for Windows.
Unfortunately, it still doesn't work. To get a list of collections, you still need to click the mouse in the field of main filter ("film roll") after selecting the period for the "date taken" filter.
