### ISSUE TITLE
darktable reports "unknown version"

### ISSUE THREAD

**Issue by phrrk** [darktable-org/darktable#11542]
**Did you buy darktable from an application store ?**
no
**Describe the bug/issue**
Since at least version 3.9.0-1048-g0c0494edf darktable reports "unknown version" in the about window opened when clicking in top left corner.  Also databases are saved as data.db-pre- and library.db-pre- .  Note first reported by others on mailing list, but I can confirm still exists with version 3.9.0-1210-g2e62721be

**Platform**

* darktable version : 3.9.0-1048-g0c0494edf and later (possibly also a little earlier)
* OS                : linux
* Linux - Distro    : Ubuntu 20.04

**Comment by elstoc** [comment]
I've just built latest master on ArchLinux and the version is reported as "3.9.0+1210~g2e62721be" when clicking on the top-left icon.

**Comment by Nilvus** [comment]
This is not darktable issue but an issue on your system. Nothing had changed recently, as far as I know, about that and I often (few times a week) and develop on master. I always have darktable version.

You didn't precise how you install darktable? Did you compile? If yes, did you remove build folder (inside your git clone folder) and destination (install) folder before compiling again?

Or did you install master from a package? And if yes, which one?

**Comment by dtteufel** [comment]
I can confirm the issue with the following setup:
Linux Mint 20.3 Cinnamon
Ubuntu 20.04
git version  1:2.25.1-1ubuntu3.3

HOWEVER:
the following  error message appears when running the build script
1%] Built target locale_sq
fatal: unsafe repository ('/home/rlch/darktable' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/rlch/darktable
[  1%] Built target locale_hu
fatal: unsafe repository ('/home/rlch/darktable' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/rlch/darktable


WHY?
Seems to be an issue with 'locale files'
Compile completes without other errors.
This a new error and only recently occurred, .


pulling a clean copy form darktable git with:
git clone --recurse-submodules --depth 1 https://github.com/darktable-org/darktable.git
My normal compile script which has worked for 12 months or more without issues is as follows ... 

git checkout master
git pull #update from git
git config submodule.src/tests/integration.update none
git submodule init
git submodule update
# delete existing build directory to to clear any conflicts!
rm -rf build
./build.sh --prefix /opt/dtgit --build-type Release
cd build
# delete existing installation to to clear any conflicts!
sudo rm -rf /opt/dtgit
#udo git config --global --add safe.directory /home/rlch/darktable
sudo cmake --build "/home/rlch/darktable/build" --target install -- -j12```
```
Results in a working install -presumably of 3.9.xx
But About box shows 'unknown - version'


and yes I always delete existing build and destination directories.

**Comment by phrrk** [comment]
After a little more testing I find that if I build on Ubuntu 20.04 with
```
cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH
=TRUE    ..
cmake --build .
```
there are no build errors and if I run darktable in place it reports the correct version. If I then build and install with

`sudo cmake --build "/home/jim/App_sources/darktable/build" --target install -- -`

I get this error during the build
```
fatal: unsafe repository ('/home/jim/App_sources/darktable' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/jim/App_sources/darktable
fatal: unsafe repository ('/home/jim/App_sources/darktable' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /home/jim/App_sources/darktable
Version string: unknown-version
```
the build runs to the end but darktable (from installed location) reports unknown version.  This is a relatively recent problem.

**Comment by phrrk** [comment]
Maybe solved.  It looks like this follows on from a security update of git. See https://github.blog/2022-04-12-git-security-vulnerability-announced/ and can be overcome by (in my case) issuing the command:

`sudo git config --global --add safe.directory /home/jim/App_sources/darktable`

I guess the problem will become more widespread as security updates are installed.

**Comment by Nilvus** [comment]
So good to closed this issue as it's not darktable one. Thanks for posting solution. I also link answer on pixls.us forum as it's more detailed:
https://discuss.pixls.us/t/dt-unknown-version-solved-sort-of/30376/16

**Comment by mikaelstaldal** [comment]
I would say this is still a Darktable issue, since Darktable should work even with the new Git default configuration. So the Darktable install process ought to be fixed, although the workaround makes it non-urgent.
