### ISSUE TITLE
ILCE-7SM3 noise profile

### ISSUE THREAD

**Issue by frozenemitt** [darktable-org/darktable#11548]
I generated a noise profile for the Sony ILCE-7SM3. I found the same issue of pink hue reported in #11319 , so will need to deal with that once https://github.com/darktable-org/rawspeed/pull/349 is accepted. I hope this data is useful to others!

Archive is spit in 2, due to 25 MB file size limit for attachments.

[darktable-noiseprofile-20220417-1.zip](https://github.com/darktable-org/darktable/files/8501992/darktable-noiseprofile-20220417-1.zip)

[darktable-noiseprofile-20220417-2.zip](https://github.com/darktable-org/darktable/files/8501993/darktable-noiseprofile-20220417-2.zip)

**Comment by rawfiner** [comment]
Please ping me once https://github.com/darktable-org/rawspeed/pull/349 is accepted and you created the profile with it so that I review it

**Comment by TurboGit** [comment]
https://github.com/darktable-org/rawspeed/pull/388 (merged in develop not yet in stable branch).

**Comment by kmilos** [comment]
https://github.com/darktable-org/rawspeed/pull/385 is actually in rawspeed stable, so available from dt 4.2 already...

**Comment by frozenemitt** [comment]
@rawfiner , thanks for the nudge. I've recomputed  the noise profiles with darktable 4.2, and the pink hue is eliminated.
[darktable-noiseprofile-20230201.tar.gz](https://github.com/darktable-org/darktable/files/10556566/darktable-noiseprofile-20230201.tar.gz)

**Comment by rawfiner** [comment]
That's perfect thank you @frozenemitt
