### ISSUE TITLE
filters for collections: very slow filename filter 

### ISSUE THREAD

**Issue by xfh** [darktable-org/darktable#11543]
Hi

I am using darktable master, 3.9.0+1205~g0d20418b5-dirty on Gentoo, and just built with the new collect filter widgets from @AlicVB.

I've noticed that the filename filter is super slow even when it's not activated.

**To Reproduce**
1. Go to lighttable
2. Reset ` filters for collections`  (clear all rules)
3. Press `new rule` 
4. Select `filename` (no need to add any filtering constraint, can even deactivate the filter)
![image](https://user-images.githubusercontent.com/9366771/163709736-d0eb73dd-1dba-4188-aefc-95172c49c789.png)

5. Open a small collection
6. Reset the `collections` module to show all images
7. Notice how slow lighttable refreshes

**Expected behavior**
The reset of the collections module should open lighttable instantly (compare how fast it is without the filename filter). Especially when the filter is not even activated.

In my collection there are 16031 images when no filter is active. I am assuming the effect is worse the larger the collection.

**Comment by AlicVB** [comment]
@xfh : PR #11550 fix it. Thanks for the report !
