### ISSUE TITLE
drawn masks are created with offset from cursor (related to dt_configure_runtime_performance)

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#11553]
**Describe the bug/issue**
When "configuration information" is displayed in darkroom on startup, then paths are created with offset. Also to move a node it's needed then to click not on node but left-up a bit.

**To Reproduce**
1. make sure that in darktablerc is this variable set to following value: performance_configuration_version_completed=5
    (to show the info window again)
2. open darktable with image name argument, or via right click from some file manager (do go directly to darkroom)
3. open color balance rgb and add drawn mask with "add path"
4. see the mask with offset

**Platform**

* darktable version : OBS build   master , 3.9.0~git 1214 , 3.9.0~git1057
* OS                : Linux
* Linux - Distro    : Ubuntu 21.10
* with nvidia opencl on and also off

**Comment by Dannny1** [comment]
Windows nightly build seems to have same issue.

**Comment by CSymes** [comment]
Also experiencing this issue with 4.0.1 on Windows 10 — haven't so much noticed issues with selecting a node, but definitely with the displayed position.
Mainly an issue with the retouch module where it's difficult to tell where it's actually sampling from in the heal mode.
