### ISSUE TITLE
Canon EOS Rebel SL3

### ISSUE THREAD

**Issue by FPS-Lightning** [darktable-org/darktable#11566]
Just uploaded a raw sample

**Comment by Nilvus** [comment]
@kmilos: is your #11570 PR fix that completely or just partially?

**Comment by kmilos** [comment]
Should be all, would be good if the OP confirmed.

**Comment by Nilvus** [comment]
Ok, I let it open few days so. Will close it if no answer.

**Comment by kmilos** [comment]
@Nilvus I think you can close now.
