### ISSUE TITLE
White balance change after setting to cloudy - Windows

### ISSUE THREAD

**Issue by noxan-dev** [darktable-org/darktable#11564]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behavior, for example:_
1. Go to 'White balance module
2. Set setting to 'Cloudy'
3. Compress the history stack, change to another picture, or go to lighttable
4. See setting change from cloudy to direct sunlight, 9 mired

**Expected behavior**
The setting to stay as I set it when compressing or exiting

**Platform**
* darktable version : 3.8.1
* OS                : Win 10 21H2
* Graphics card     : AMD 580
* Graphics driver   : AMD Adrenalin 22.3.1
* OpenCL activated  : Yes

**Comment by victoryforce** [comment]
@noxan-dev  Well, sometimes raised issues remain unanswered and get lost. It sometimes happens that most developers are busy with other things at that time, or a temporary burst of bug reports distracts attention to something else.

I noticed the bot auto-close message and would like to ask if you can reproduce your problem on the latest darktable release? I tried but I couldn't reproduce this problem.

If you confirm that the problem no longer exists, it is likely that during this time some changes in the code removed the bug. If you have a problem with the latest version, it means that it somehow depends on the environment (for example, on the specifics of the configuration), or it appears only with certain images.

**Comment by noxan-dev** [comment]
I am on the latest version, 4.2.1, and it's happening. If you set cloudy to more than +1 mired, it stays.

https://user-images.githubusercontent.com/59417659/232260609-cb0ee4ee-9dda-40e7-9d7c-cb75ab791fc2.mp4
