### ISSUE TITLE
Sometimes created duplicates vanish from lighttable. Can be seen in duplicate manager though

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#11565]
I don't know exactly when this happens or why yet, but sometimes when I create duplicates, they show in the lighttable and just right now after creating another duplicate the first duplicate, from another image, just disappeared from the lighttable. The duplicates show just fine in the duplicate manager though. This is latest git, might have happened with 3.8 as well, but I'm not sure. Any pointers on how to gather more information? Debug log doesn't show anything in my opinion. When restarting darktable, both duplicates vanished from lighttable.

**Comment by elstoc** [comment]
you don't have grouping enabled in the lighttable view do you?

**Comment by piratenpanda** [comment]
ah and I thought it only groups jpgs and raws
