### ISSUE TITLE
[FR] add shortcuts to the new filtering module

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#11562]
The new filtering module has just land into master.
One point that remains to do is to allow some shortcuts to be set. I've not touch this part at all in order to propose something coherent from the start.
Shortcuts for the "add rule/sort/history" buttons will be straightforward... but what will be difficult here is for the filters themselves, as we can't know in advance which filters will be present or not...

@dterrahe : what is your view on this ?

**Comment by AlicVB** [comment]
Thanks for your answer :)
I will have to read it again and try to understand... but just for information, there's something that can (?) help us here : all the "range" widgets have a context menu with the value present in the collection (like for the collect module) but more interesting here, there's also "predefined" ranges. For example in rating, you will find all the most interesting range directly (the one previously present in the topbar filter). Maybe we can use them somehow ?

Last, would you be ready to help me here ? That's completely new for new and reading your answer, we even need to tweak your inputNG code...

**Comment by dterrahe** [comment]
> Maybe we can use them somehow

That would mean shortcuts could _only_ be set up to those pre-defined ranges?

> Last, would you be ready to help me here ?

For 4.0 it would be good to not have regressions, in the sense that sorting and rating filtering could still be done via shortcuts. But looking at the code I'm afraid I may not understand a lot of your design decisions so my impulse to bring things more in line with the action system could end up being destructive.

For example, since it seems you only support exactly one sort dropdown in the top toolbox, why does it need to be removed and reinserted each time in `_sort_gui_update`? Why does the "sort by" label need to be a separate widget? Both these choices make it not trivial to reinstate the shortcuts.

**Comment by AlicVB** [comment]
> That would mean shortcuts could _only_ be set up to those pre-defined ranges?

I didn't have "only" in mind... Just that we can use that feature... among other ;)



> For 4.0 it would be good to not have regressions

Agreed ! That should be the first goal.



> why does it need to be removed and reinserted each time in `_sort_gui_update`?

I will fix that. Same for filters.



> Why does the "sort by" label need to be a separate widget?

It's more a ui design decision here, taken with @Nilvus. But I have a fix in mind, for that too.

More generally, when I asked for help, that was not to let you do all the work ;) Where I need you is more to know "blocking" points (you mention some) and what would be the best way to implement shortcuts.

**Comment by AlicVB** [comment]
@dterrahe : 
in PR #11611 I've implement a way to hide the label for bauhaus combobox. This solve the issue for sorting here, but also for some other cases (including the "alignment" issue you have pointed)
I've also used that to implement shortcuts for the sort order and the sort direction. In fact, that was easy as the widgets are not removed and reinserted each time : if the widget already exists, it's just updated to the right values ;)

Don't hesitate to correct me or propose some better code ;)

**Comment by AlicVB** [comment]
So I've think a little more about the shortcuts for range widgets. The minimum that I would like to propose is something like we have for bauhaus combobox : 
- by default show the context-menu
- also propose "special" effects for "predefined" entry of that context-menu (not for "normal values that may change) predefined values are set for example in the rating widget or the aspect-ratio.

Do you think we can start with that and eventually add more complex action after ? or do you prefer to do everything in one pass ?
I've looked at the "actions" code in bauhaus combobox, but tbh, I'm not sure to understand everything... I'll try to understand that the "hard" way with copy-paste, printf and tests :) But I fear I'll have some questions soon !

**Comment by dterrahe** [comment]
> designing + explaining + correcting is often more work than just implementing.

If you let me know when you're (mostly) done with your changes to the widgets, I'll look at it and implement shortcuts on top.

**Comment by AlicVB** [comment]
@dterrahe : for me, I'm done with the widgets changes (it's mostly bugfix now). So go ahead... and ask me if I can explain or help you in any way !
 For me the only remaining changes are : 
- #11572 which doesn't touch global widgets, just how the filter is "computed" internally
- #11611 which implement all the shortcuts for the sorting part (that was the easy part !)
