### ISSUE TITLE
Increase min size of sliders

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#11577]
**Is your feature request related to a problem? Please describe.**
The slider icon automatically shrinks the more elements are displayed. This goes to a point where the slider becomes very small compared to the mouse cursor - making it very hard to select. 

I found that this has the most impact on the file manager layout and the import module but others might be impacted as well.:

![image](https://user-images.githubusercontent.com/2805109/164251471-21f97733-36e6-4169-8708-85f6d4e1be84.png)
![image](https://user-images.githubusercontent.com/2805109/164251615-90432d1e-3f38-430f-9909-bc47fea5c793.png)

**Describe the solution you'd like**
Increase the min slider size to something more reasonable.

![image](https://user-images.githubusercontent.com/2805109/164252111-defd1a87-9d52-4d74-89be-de91f5e94dc2.png)

**Comment by Nilvus** [comment]
They are all set in same place/way. I am actually working on CSS. Could you test that code:

```
scrollbar slider
{
  min-height: 0.75em;
}
```

0.75em seems good for me.

**Comment by Nilvus** [comment]
You could of course test bigger height but 1em should be the max. Slider height is also an indicator of the list height.

Maybe 0.84em (double of width which is 0.42em;) is better than 0.75, so something between 0.84em and 1em to be agree with.

**Comment by Solarer** [comment]
cool,
1em is the min that feels ok for me. 1.75 is comfortable (same size as my mouse cursor on my screen). 0.84 is not much better than before.

Is it necessary to keep it that small? The sensitivity of the slider is proportional to the distance the slider can be moved. Even if you pick a big value such as 3em there is still a lot of room to move the slider and sensitivity is good.

This CSS setting does not affect the size of the slider in the copy&import module.

**Comment by Solarer** [comment]
3em
![image](https://user-images.githubusercontent.com/2805109/164265181-e5893ec7-7927-4908-b5bc-45cad673a7b1.png)

1.75em
![image](https://user-images.githubusercontent.com/2805109/164265328-50f7ec3c-4852-43d7-a562-0548568e8e7b.png)

0.84em
![image](https://user-images.githubusercontent.com/2805109/164265432-f8026a90-92f6-43db-82d5-3ea0d1bc8c5d.png)

**Comment by Nilvus** [comment]
> cool, 1em is the min that feels ok for me. 1.75 is comfortable (same size as my mouse cursor on my screen). 0.84 is not much better than before.

0.84em is just the double as before!

> Is it necessary to keep it that small? The sensitivity of the slider is proportional to the distance the slider can be moved. Even if you pick a big value such as 3em there is still a lot of room to move the slider and sensitivity is good.

As I said, slider size is also an indicator of list height. The more you increase the size, the more you distort the impression of the length of the list. So this need a good compromise. And this size is here since a very long time, and you're the first (and only actually) to not like that.
I'm so ok to put 1em in height. Note that you could keep CSS code I posted here and keep what's ok for you, in preferences.

> This CSS setting does not affect the size of the slider in the copy&import module.

Thanks, I didn't check. Will be easy to fix. I will integrate that change in my opened PR.

**Comment by Nilvus** [comment]
On my side, this code works on copy&import module. Did you correctly set CSS and reopen dialog window?

With actual setting in master (0.42em in min-height):

![image](https://user-images.githubusercontent.com/45535283/164268488-197ed787-50fd-4ac7-84c2-403b29cd0ee1.png)

And with min-height to 1em:

![image](https://user-images.githubusercontent.com/45535283/164268731-23e27b8b-ba30-495d-9320-5dbf1a603b74.png)

**Comment by Solarer** [comment]
no, sorry I cannot confirm. 
CSS has been applied and is working in lighttable but is not working in import / copy&import. I closed DT to be sure but it did not change anything.
I just build version list+2777~gfe1008608 from master using a clean config dir /tmp/dt-test/

**Comment by Solarer** [comment]
I am ok with 1em as a new default :+1:

**Comment by Nilvus** [comment]
@Solarer: could you test #11559 PR where I add the fix. I tested 1em with this PR and it's ok on copy & import window. Maybe on master, there's some CSS that override it. I will not check on master as I am on simplifying a lot Gtk/Css code.

**Comment by Nilvus** [comment]
Just an update: this will work correctly with my PR. In master we have both dialog scrollbar slider and scrollbar slider set, so with my CSS setting above, this will not work indeed in master. But as it's not necessary to have dialog scrollbar slider line (scrollbar slider will work on all parts if alone), I remove it on my PR. That's why CSS I posted here works correctly in copy & import (which is a dialog window) and not on your side.

**Comment by Solarer** [comment]
ok, I will not check it then.
Looking forward to your merge!

Btw I noticed that this slider gets overlapped by the front UI when moving it to the very right. Is that also related to CSS and can be fixed by you?
![image](https://user-images.githubusercontent.com/2805109/164699635-72c1ef9d-ffa8-4c4b-af81-d5b24893a927.png)

**Comment by Nilvus** [comment]
> Btw I noticed that this slider gets overlapped by the front UI when moving it to the very right. Is that also related to CSS and can be fixed by you? ![image](https://user-images.githubusercontent.com/2805109/164699635-72c1ef9d-ffa8-4c4b-af81-d5b24893a927.png)

Thanks for your feedback and notice it. A missing line in CSS. Fixed on my side. Will be added in my PR in my next commit ASAP.
