### ISSUE TITLE
[FR] add very basic support for video files?

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#11576]
My goal is not to to add video playback capabilities to DT but I would like to be able to import video files using the copy and import module and have a very basic representation of a video file in a collection (a thumbnail image or just a thumb saying "mov").

I sometimes create short video clips from family gatherings and when I import all images using the copy & import flow, I have to copy the movies manually. Sometimes I even forget them completely and they get deleted when I format the SD card. 

A minimal requirement for me would be to get some visual feedback or reminder that X movie files are located in the image folder.

**Comment by Solarer** [comment]
Can this be tackled at the same time with #11195?

**Comment by jeugregg** [comment]
So, videos are still not supported? Just to import and export copy into same pictures folder?
