### ISSUE TITLE
[FR] Hue shift slider in color gradations in the master tab of the color balance rgb.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11580]
It would be nice to have the hue shift slider in color gradations in the color balance rgb module (master tab) as in the 4 ways tab.

I really don't know if this feature affects the goal of this tab, as it would be different than the other sliders on the same tab, but since the slider is in the middle (0 degrees) and goes to positive or negative, not like the other sliders on the 4 ways tab (positive only) it would be nice to visualize the color gradation.

![Screenshot-20220421005419-414x195](https://user-images.githubusercontent.com/67672868/164481601-f80b4da9-692d-431c-8948-3b4ef0ed7a7e.png)

**Comment by Nilvus** [comment]
@aurelienpierre?

**Comment by MStraeten** [comment]
Unfortunately such gradation is only be correct for a plain red image ;)
It’s a relative change, so the Color gradation is completely meaningless.

**Comment by difrkaguilar** [comment]
> Unfortunately such gradation is only be correct for a plain red image ;)

The image is a mockup.

By the darktable manual. This is the definition:

> hue shift
> Rotate all colors in the image by an angle over the chromaticity plane, at constant luminance and chroma. You can use this control to remove spilled colored light on a subject or to quickly change the color of some object. This setting is usually best applied locally, using masks.

I'm not as smart as many of you guys, but it seems to me that if you have a hue shift slider to change the colors of an image, and it scrolls back and forth from the center, you should have a visual indication of where it scrolls to, and users will see that with the colors in the slider as several applications do. By that I don't mean that darktable copies the others, but, if it is as it states that "It's a relative change, so the Color gradation is completely meaningless." Then we are still doing the adjustment blindly.

**Comment by aurelienpierre** [comment]
Not possible. The rotation is relative to the original color, each input pixel will have an output hue based on its original hue, no matter what it is.
