### ISSUE TITLE
FR: Systematic user feedback / survey

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#11585]
**Is your feature request related to a problem? Please describe.**
We mostly have feedback via issue tracker or threads in pixls.us, there is though no systematic thing.

**Describe the solution you'd like**
Maybe we could have some sort of systematic request for feedback.
Per dt version we would show a hint & link to a survey site, (like the one we have for configure version update).
This hint could be shown when starting dt maybe every first of month at least after 4 weeks of using dt?

For V4.0 i personally would be interested in
1. How is your experience with the new highlights algo?
2. How is filmicrgb V6 working out of the box? Do you use special presets?
3. How is d&s working?
4. How is OpenCL out of the box working?
5. Any unexpected crashes?
6. Anything you had to do after installing ...

How does this sound? Any ideas about this? 
Unfortunately i don't have the slightest idea of how to do such a survey site or if it's possible on github.

**Comment by piratenpanda** [comment]
https://nextcloud.com/blog/nextcloud-forms-is-here-to-take-on-gafam/ nextcloud for example has a forms app when you want to self host the questionnaire.

**Comment by gi-man** [comment]
My only fear is that having free type text fields will lead for people to use it as another place to report issues. It will then need someone to read and maintain that list outside of this list. 

I do like the idea of somehow the user sending their OpenCL device/settings/performance data once a month to a database. It could be used to see trends (percent with OpenCL on, average GPU physical memory, OpenCL version). If we can turn the information into something actionable, then it makes sense to me.
