### ISSUE TITLE
metadata applied to incorrect image if the mouse wanders

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11589]
I noticed this while looking at writing the documentation for #10965...

1. Select an image and type into a field in the metadata editor
2. Move the mouse slightly so that it's over a different image
3. Press Enter

The metadata gets (incorrectly) applied to the hovered image instead of the originally-selected one, but the UI updates aren't consistent. The metadata of the originally-selected images is retained in the module, but only the changed metadata is updated in the hovered image. It's hard to describe so see the following video.

https://user-images.githubusercontent.com/9555491/164553367-371250a5-dd89-473b-92d3-d09d577b3b90.mp4

I'm not sure the best solution here. Three possible options:

- Revert back to the previous functionality where, if the selection changed, the metadata module was immediately updated. I found this frustrating as sometimes I had to alt-tab to another application to copy/paste an image title and if my mouse was over the wrong thumbnail when alt-tabbing back, I had to start again.
- Lock the image selection until enter is pressed or the user physically clicks another image
- As suggested in #6025 and elsewhere, stop using mouse hover as a way to select images - it's just annoying

**Comment by elstoc** [comment]
@phweyland please can you take a look at this

**Comment by gi-man** [comment]
, stop using mouse hover as a way to select images - it's just annoying

+1 this. I don't like selecting an image to see the tags but seeing the tags of the last hovered image.

**Comment by phweyland** [comment]
> @phweyland please can you take a look at this

One thing more on my todo list, but I currently I miss time.
Another preference to disable applying change while hovering ? Then hovering would only show hovered image information (except for current editing module).
