### ISSUE TITLE
custom input profile has generic name

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#11596]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
I have two custom icc profiles in /home/user/.config/darktable/color/in/

These are called:
nikon_d3300_matrix-dcamprof-lut-gamutcompressed-adobergbstrong.icc
nikon_d3300_matrix-dcamprof-lut-gamutcompressed.icc

Both profiles appear in drop down menu of input color profile module, however both only have the generic name 'Unknown Camera', meaning I cannot distinguish between the two. Screenshots below:

![input profile 1](https://user-images.githubusercontent.com/69561443/164702927-4e6d495b-d750-42b8-aa68-60e3e2651b51.png)

![input profile 2](https://user-images.githubusercontent.com/69561443/164702778-df3116da-9b6d-4720-9b1f-793aa0628241.png)

**Expected behavior**
The input color profile module should display the file name of custom profiles, not the generic 'Unknown camera'.

* darktable version : 3.8.0~git59.e758e1366c-1
* OS                : Linux 5.13.0-27-generic
* Linux - Distro    : Linux Mint 20.2 Cinnamon
* Memory            : 32gb
* Graphics card     : GeForce RTX 2060
* OpenCL installed  : y
* OpenCL activated  : y
* Xorg              : y

**Comment by todd-prior** [comment]
You need to edit them...DT goes by the description tag in the icc not the file name...During the creation you can usually specify a "name"...this is not the file name but the name used by software to identify the profile.....

**Comment by todd-prior** [comment]
I have a few packages in Win that can do this but I don't know about linux...one thing might be dcamprof... It has a command to dump and icc to json file where your could insert your description and then json2icc to add those edits back to the icc.... I have not used this method and likely there is a more elegant solution that a linux user will present you..

![image](https://user-images.githubusercontent.com/44409419/164750060-b1a00a7c-2a41-4b27-8fd4-bf5a4beb9168.png)

I think this is a similar approach as well with ICCXML...out to xml  ....edit and then back to ICC....

**Comment by SoupyGit** [comment]
Thanks a lot @todd-prior that worked!
These profiles were made by ggbutcher. I dual boot so could follow the method given at dpreview to alter the description in Windows.
