### ISSUE TITLE
Fujifilm X-S10

### ISSUE THREAD

**Issue by Barbara3065** [darktable-org/darktable#11597]
I get following error message:

<img width="579" alt="Fuji_Darktable" src="https://user-images.githubusercontent.com/104193145/164736896-840297b5-0be7-4509-aed8-144da8467145.PNG">

Thanks for your reply
Barbara

**Comment by ptilopteri** [comment]
https://www.darktable.org/resources/camera-support/

**Comment by Nilvus** [comment]
Please provide more infos and use correctly issue template provided. Questions asked are not there just for the fun. Thanks. And avoid as much as possible not english messages (it's easy to change darktable UI to english. That will help us to understand issue. If it's about tethering, darktable use an external library for that, called gphoto2. A quick search on it precise that only Liveview is supported and not image capture. So darktable team can't do anything for that. See http://gphoto.org/proj/libgphoto2/support.php

If it's that, think about closing issue and confirm here. Thanks.

**Comment by Barbara3065** [comment]
I will habe have a closer look by tomorrow and home back to you. It is not easy for someone not understanding much of ICT and not beeing english speaking...what you talk about and want me to do or not...I am a bit frustrated about the help, I am not asking this for FUN!!!!!
Barbara
-- 
Barbara Vogt
Sonnhalde 45
3065 Bolligen

++41 31 381 00 63
***@***.***

23.04.2022 10:09:00 Nicolas Auffray ***@***.***>:

**Comment by Nilvus** [comment]
> I will habe have a closer look by tomorrow and home back to you. It is not easy for someone not understanding much of ICT and not beeing english speaking...what you talk about and want me to do or not...I am a bit frustrated about the help, I am not asking this for FUN!!!!!

I just remember you some things and can't know how is your english level, especially with your short issue. We try to explain (and help) as well as we can and what we understood about an issue. If you're not completely at ease with englsih, I so think Deepl translator could help (it's the best one I think): https://www.deepl.com/translator

**Comment by jenshannoschwalm** [comment]
@Barbara3065 Die Info reicht so wirklich nicht, sorry. Vermutlich versuchten Sie einen import von der Kamera und das Betriebssystem hat das Gerät als schon benutzt gemeldet. Aber wie sollen wir helfen, wenn wirklich absolute Minimalinformationen fehlen? MfG

**Comment by Barbara3065** [comment]
OK, habe aber einfach nicht mehr Info. Die Fehlermeldung lässt sich nicht anklicken im darktable...
Barbara Vogt
Sonnhalde 45
3065 Bolligen

031 381 00 63 / 079 554 2725
***@***.***

28.04.2022 07:16:43 Hanno Schwalm ***@***.***>:

**Comment by jenshannoschwalm** [comment]
Was soll ich dazu sagen, noch nicht einmal eine Information zum Betriebssystem? Beim Eröffnen der Fehlermeldung gibt es ein template (also eine Vorlage) wie soll hier einer der Entwickler ahnen was los ist? Ansonsten käme in Frage, das deutsche Handbuch zu lesen ...

https://darktable-org.github.io/dtdocs/de/overview/workflow/import-review/

**Comment by Barbara3065** [comment]
Tut mir leid, hatte keine Vorlage... Ich glaub die Frustration ist auf beiden Seiten so gross, dass wir es lassen. Sie können das Ticket schliessen oder mir die Vorlage senden bzw den Link, dann kann ich es auch entsprechend erfassen...
Barbara Vogt
Sonnhalde 45
3065 Bolligen

031 381 00 63 / 079 554 2725
***@***.***

28.04.2022 14:56:20 Hanno Schwalm ***@***.***>:

**Comment by Barbara3065** [comment]
Habe übrigens gestern zum Geburtstag ein Handbuch darktable erhalten, hoffe nun so weiter zu kommen, weil ich eigentlich vom Produkt sehr überzeugt bin.
Barbara Vogt
Sonnhalde 45
3065 Bolligen

031 381 00 63 / 079 554 2725
***@***.***

28.04.2022 14:56:20 Hanno Schwalm ***@***.***>:

**Comment by jenshannoschwalm** [comment]
Das deutsche online manual ist ziemlich gut :-) Ob dt auf windows oder linux läuft -> macht nen Riesenunterschied für uns Entwickler... Oder auch welche DT Version ... 

Das template  - das kommt automatisch: New Issue -> bug report ->

**Comment by Barbara3065** [comment]
OK, ja verstehe ich! wurde intern bei euch weitergeleitet, deshalb kein template... Wäre Windows, latest Dr Version - habe Update gemacht, da ich gelesen habe, dass erst mit neuer Version Fuji x s10 supportet wird (hab ich geschrieben)
Barbara Vogt
Sonnhalde 45
3065 Bolligen

031 381 00 63 / 079 554 2725
***@***.***

28.04.2022 15:38:13 Hanno Schwalm ***@***.***>:
