### ISSUE TITLE
Darktable hangs if you double-click on the histogram

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#11598]
**Describe the bug/issue**
Darktable hangs if you double-click on the histogram

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'darkroom'
2. Double click on the histogram
3. Software hangs

**Expected behavior**
Reset histogram curve

**Screenshots**
not applicable

**Screencast**
not applicable

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : 5.13.0-41-generic  # 46-Ubuntu SMP Thu Apr 14 20:06:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Linux - Distro    : Ubuntu 21.10
* Memory            : 16 G
* Graphics card     : NVidia GM107M - Geforce GTX 960M
* Graphics driver   : Nvidia 470
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Comment by ptilopteri** [comment]
confirmed on 3.9.0+1258~g527c48892
openSUSE Tumbleweed 20220420

after double-click on histogram, dt hangs 

-d all displays nothing after double-click on histogram

**Comment by jenshannoschwalm** [comment]
confirmed here too.

**Comment by da-phil** [comment]
Can confirm too
* current master (3.9.0+1274~gd6456c1a6)
* Ubuntu 20.04.4
* OpenCL active

**Comment by domosbg** [comment]
Can confirm it on Ubuntu 22.04, DT 3.9.0+1273 (without OpenCL).

But on windows 11, DT 3.8.1, there is no problem. Works as expected on my system.
