### ISSUE TITLE
Performance drop current master vs. 3.8.1 stable (gentoo repo)

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11606]
**Did you buy darktable from an application store ?**
No, I build master from git and stable is in my gentoo repo

**Describe the bug/issue**
I see a certain performance drop, when I compare exports done with: 
- dt-stable (3.8.1 from gentoo repo) 
and 
- current master, which is today 3.9.0+12+1271~gdfeea3e9d but I have this already since some time

**To Reproduce**
- I have a little benchmark script (attached), which exports the test pics from Phoronix. All started [here](https://discuss.pixls.us/t/darktable-speed-in-general-and-when-using-two-monitors/12002)
- As Phoronix pics are display-referred and chromatic adaptation legacy, I have added two versions of [this picture](https://discuss.pixls.us/t/the-station-at-night/29240)
- both edited by me with filmic V5 and "modern" chromatic adaptation
- one version with insane iterations, to load the GPU (xmp attached)
- one version with a more "normal" edit (xmp attached, pls copy NEF with respective naming so the benchmark script runs well)
- my darktablerc, filtered to opencl is attached
- my settings in darktable master say OpenCL scheduling profile default (so the device priorities are obeyed)
- tune OpenCL performance memory size and transfer
- also I have exported my own aforementioned edit with darktable-cli --core -d perf -d opencl and amend both txt files
- I did a comparison in LibreOffice, this will be attached as well and screenshot will be added here for convenience
- All exports always running on same GPU and using plenty of the GPU memory, no complains about this atm (checked nvidia-smi)
- I will further amend two epxorts with --verbose --core -d memory separate, as I don't want to repeat the aforementioned calculations :-)
- I will pack all amendments in a zip-file [Amendments.zip](https://github.com/darktable-org/darktable/files/8547328/Amendments.zip)

**Expected behavior**
same or better performance than 3.8.1

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49004103/164896752-d0ef42e2-0e35-408b-829d-a8b543889a1d.png)

![grafik](https://user-images.githubusercontent.com/49004103/164895493-718ac939-d1b6-4a4f-8d99-83f5f06f1c9c.png)

--> not bisected yet...

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.9.0+1271~gdfeea3e9d
* OS                : Linux - kernel 5.17.3-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-510.60.02
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.3-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.31
* gcc               : x86_64-pc-linux-gnu-11.2.1
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

- I am running two discrete GPU
- nvidia-smi sees the 1060 as device 0 and the 2070s as device 1. **darktable sees the devices opposite**
- luckily all my other things are running on the 1060, while I do export on the 2070
![grafik](https://user-images.githubusercontent.com/49004103/164896265-e4807e4e-d7c6-4e6d-92ad-45a3644e6029.png)

@jenshannoschwalm I am not saying your recent work is responsible for this, just I have the feeling, currently you are the deepest in opencl, so I hope you don't mind I ping you.

@wpferguson as discussed on IRC :)

@ClaesGitHub you might be interested?

**Comment by wpferguson** [comment]
Piggybacking on this...  I see errors where guided_filter falls back to the CPU implementation due to insufficient memory (I only have 3GB).  Does it not tile?  Also, there doesn't seem to be an opencl implementation for chromatic aberrations.

I've been testing with a 10 image export since the changes started.  Each time there's a change, I update, clean out everything, recompile, and test.  When I started I used my hand tuned configuration and averaged 24.3 seconds per image on export.  With the latest changes, I'm seeing 27.2-27.3 sec/image.

**Comment by jenshannoschwalm** [comment]
> so I hope you don't mind I ping you

@AxelG-DE absolutely and definitely i hoped you would ping me in case of regressions :-)

About current master regressions there are a few thing coming to my mind
1. There were many fixes related to tiling too, in many modules we detected wrong or undefined tiling parameters. In former dt versions that *could* have resulted in an execution of untiled cl code - not respecting the dt cl mem limits. That might have either failed while executing cl kernels resulting in a cpu fallback or - if you have been lucky because it fitted into the graphics card - to a better performance.
2. There is the dt docs about pinned transfer. It mentiones something like good for AMD but not necessary for NVIDIA. In short, the story is not as easy, on my rtx4000 for example there is a measurable benefit for pinned transfer. So for now you can set that either for all devices via the "transfer" setting or per device later.
3. There is definitely a performance issue about the strategy we test for fitting image and buffers. #11618 fixing this for the vast majority of cases.
4. You didn't have any special compiler options in use?
5. About the "order of devices", that part of the code has not changed in dt. Anyway i would be very interested in your `-d opencl` output report, the logs in amendments.zip don't show the device_init information ???

**Comment by AxelG-DE** [comment]
@jenshannoschwalm 
> @AxelG-DE absolutely and definitely i hoped you would ping me in case of regressions :-)

Thanks, I will :)
Sometimes when frustration is raising tone could be complaining (indeed shouldn't) which is then frustrating to the other(s). I always want to be better in communication (yet I fail sometimes)
 

1. I see
2. That means I have to test the other versions as well
3. happy to see it merged and test it by than (currently still busy in the house for unboxing the housemovingboxes)
4. definitely no, even only -O2
5. Weird. I did not check that carefully. So is it o.k., I amend darktable-cltest [here as cltest.txt](https://github.com/darktable-org/darktable/files/8549182/cltest.txt)?
6. o.k..... I still need to get more deeper into it. I haven't fiddled around yet with the geek mode (read somewhere, no tuning and one can again fine tune by hand, but I donno how atm)

**Comment by jenshannoschwalm** [comment]
I see your -d opencl logs.
If you want to tune your system for current master just very quick suggestions

1. I would certainly disable the intel device as the perf test agrees on being slow **and** you definitely have faster devices. That certainly would slow down the "multiple gpu" thing. In your per device key this would mean to set the last number before the float to 1
2. Many people complained about micro_nap, that would be changing the 250 for the nvidia devices to 0.
3. On both your nvidia cards the number of event handles is pretty safe with much larger numbers >= 1024 (default is 128)

**Comment by AxelG-DE** [comment]
Yeah I tried the intelGPU for second preview monitor, where I thought, it would be be better than CPU (and keep the 2070 free from that)

Currently I do not use it (acc. to Prio), how can it slow down the "multiple gpu" thing? Even on multiple gpu, I did not observe, the iGPU was used, anyhow I use default :)

 > In your per device key this would mean to set the last number before the float to 1

Sorry, I don't get it right now. What would I need to do where? Maybe I will really completely disable it, as my CPU is as beefy, the iGPU didn't do anything good (but I will try one more time, after I updated my script acc. to your comment No 6 above (I will also export the set of pics in one run all together, -not working yet)

Actually I would like to have the micro_nap much smaller than 250. Especially my 2070 is not driving the monitors, they are connected to the 1060 and smaller mnap makes dt snappier. The micro_nap 70 worked even with my 1060 when it was alone

I ran event_handles 300 in my darktablerc, need to learn how to do it now with the new system

**Comment by jenshannoschwalm** [comment]
I was somewhat reluctant to "publish" specs for how-to-tune dt OpenCL as the per-device opencl settings and tiling stuff was really heavy work and required a number of version changes, i wanted something stable.

```
Quick DT 4.0 OpenCL tuning reference

In Preferences - all settings are valid without a restart

darktable resouces:
 - choose large if mainly using dt in your desktop session or for export
tune OpenCL performance:
 - memory size: calculate available OpenCL memory for every device once per dt session
 - memory transfer: use pinned transfer while tiling, might improve performance depending on device
   but uses more memory
 
In darktablerc there is a conf key automatically generated for every found OpenCL device holding all
per-device settings, most of them were global thus prohibiting a per-device tuning.

You may edit this conf key, it looks like
cldevice_v4_quadrortx4000=0 250 0 16 16 1024 0 0 0.017853 or in general

cldevive_version_canonicalname=a b c d e f g h x.xxxx

 a) avoid_atomics:  (1) avoiding or (0) use atomics (Only very old devices require an avoid.
 b) micro_nap:      default 250. If using multiple devices the non-desktop device could be set to 0
 c) pinned memory:  (0) select mode by gui. (1) enforce pinned transfer. (2) disable pinned transfer
 d) clroundup wd:   both roundups have 16 as default.
 e) clroundup ht:
 f) event_handles:  safe up to 1024, (0) to disable CL events (might not report errors but faster)
 g) async mode:     if (1) device uses asnchronous dt mode, this uses more events and might be
                    unstable on old&small devices with heavy tiling and pinned transfer.
 h) disabled:       (0) enable or (1) disable device. Bad devices are marked as disabled by dt
 i) benchmark:      DO NOT edit except maybe set to 0 to enfore a CL re-benchmarking

Please note, bad device keys force a rewrite to defaults.

Note for nerds, there is another per-device key defining CL compiler options
cldevive_version_canonicalname_building=compiler options as you define

```

**Comment by jenshannoschwalm** [comment]
@wpferguson 

> Also, there doesn't seem to be an opencl implementation for chromatic aberrations.

Yes, both CA corrections (raw and rgb) don't have an OpenCL path

> I see errors where guided_filter falls back to the CPU implementation due to insufficient memory

Ok, i checked the code and indeed there is a test for CL memory that is not good and might lead to fallback without good reason. Thanks for making me aware of this, will fix.



> When I started I used my hand tuned configuration and averaged 24.3 seconds per image on export. With the latest changes, I'm seeing 27.2-27.3 sec/image.

dt master just got a fix that should improve things significantly.

**Comment by jenshannoschwalm** [comment]
Good you confirm fixing performance regressions in #11618 and #11625 .

As i don't use IRC at all, are there any other issues reported related to OpenCL or tiling?

**Comment by AxelG-DE** [comment]
Ooops, sorry, I oversaw this feedback, as my eMail inbox is flooded....
I will ask on IRC, resp. will point Chris to have a look here :)

**Comment by jenshannoschwalm** [comment]
@AxelG-DE i think there should not be any drawbacks exept accepting some penalty for tuning memory. I will likely be able to do a bit more for 4.0

ATM i would like **any** report here showing a penalty on current master with -d opencl -d tiling.

**Comment by ClaesGitHub** [comment]
Abends, @jenshannoschwalm 

I am testing a new distro & compilation (3.9.0+1356~gea33d3f1f3)
[memTuningOn.txt](https://github.com/darktable-org/darktable/files/8593043/memTuningOn.txt)
MfG
Claes

**Comment by MStraeten** [comment]
darktable 3.9.0+1364~g972bb9186
OSX 12.3.1, target release for build: 10.15

[darktable-d_opencl.txt](https://github.com/darktable-org/darktable/files/8596797/darktable-d_opencl.txt)

```
cldevice_v4_amdradeonpro5500mcomputeengine=0 250 0 16 16 128 0 0 0.057842
cldevice_v4_amdradeonpro5500mcomputeengine_building=-cl-fast-relaxed-math
cldevice_v4_intelrcoretmi99880hcpu230ghz=0 1000 0 16 16 128 0 1 0.000000
cldevice_v4_intelruhdgraphics630=0 250 0 16 16 128 0 0 0.102719
cldevice_v4_intelruhdgraphics630_building=-cl-fast-relaxed-math

opencl=TRUE
opencl_checksum=3785393615
opencl_device_priority=1,0,*/!1,0,*/1,0,*/1,0,*/*
opencl_library=
opencl_mandatory_timeout=400
opencl_scheduling_profile=default
opencl_synch_cache=active module
opencl_tuning_mode=memory size

resource_default=512 8 128 700
resource_large=700 16 128 900
resource_small=128 4 64 400
resource_unrestricted=16384 1024 128 900
resourcelevel=default

```

**Comment by AxelG-DE** [comment]
@jenshannoschwalm 
currently I have big headaches with intel driver. 
darktable crashes after yesterdays update :-(
http://dpaste.com/B996MJUXM (but this is OT here)

so at the moment I cannot support for intel devices...

**Comment by jenshannoschwalm** [comment]
Thanks @MStraeten 
```
22,374400 [dt_opencl_get_unused_device_mem] took 0,6698 secs on `AMD Radeon Pro 5500M Compute Engine` id=1, 4048MB available, 31MB of 4080MB already used
22,374424 [dt_opencl_get_device_available] use 3675MB (tunemem=ON, cpudevice=no) as available on device `AMD Radeon Pro 5500M Compute Engine' id=1
24,569759 [pixelpipe_process] [preview] using device 0
24,982384 [dt_opencl_get_unused_device_mem] took 0,4090 secs on `Intel(R) UHD Graphics 630` id=0, 1512MB available, 24MB of 1536MB already used
```

the above lines are very interesting showing a vastly worse result for AMD and Intel drivers in "check available", here on nvidia it's ~20ms. Will see what i can do about that.

**Comment by jenshannoschwalm** [comment]
@AxelG-DE could you do me the favour and recheck performance using todays master?

@MStraeten could also recheck. I would be especially interested about the timing of checking for available graphics mem (As a reminder use "tuning for memory" and open in image in darkroom - or another way to start a pipeline - using -d opencl. You reported values of 400/600ms for intel and AMD, hopefully this has changed a bit.

**Comment by MStraeten** [comment]
my latest build to check performance 2 days ago with integrated #11717 wasn't significantly slower or faster  then 3.8.1 with an arbitrary set of images. 
- definitely worse due to tiling if no tuning was given
- sometimes slightly better, sometimes slightly worse, sometimes quite equal for memory or memory+transfer tuning option

will do some more systematic checks with a clean initial ./config/darktable later with current master ...

**Comment by AxelG-DE** [comment]
> @AxelG-DE could you do me the favour and recheck performance using todays master?

@jenshannoschwalm your wish is my order :-)

left is my hand-optimized , right is `cldevice_v4` as standard

![image](https://user-images.githubusercontent.com/49004103/167152545-8184b1d5-73e8-4352-95f6-1d3288905eb2.png)

**Comment by MStraeten** [comment]
current master darktable 3.9.0+1426~g49bfe7749
```
12,348539 [pixelpipe_process] [full] using device 1
12,888518 [_opencl_get_unused_device_mem] took 0,5399 secs on `AMD Radeon Pro 5500M Compute Engine` id=1, 3854MB available, 225MB of 4080MB reserved
12,888537 [dt_opencl_check_device_available] use 3637MB (tunemem=ON, pinning=OFF) on device `AMD Radeon Pro 5500M Compute Engine' id=1
[Farbkalibrierung] double CAT applied
[Farbkalibrierung] double CAT applied
[Farbkalibrierung] double CAT applied
15,078691 [pixelpipe_process] [preview] using device 0
15,346564 [_opencl_get_unused_device_mem] took 0,2678 secs on `Intel(R) UHD Graphics 630` id=0, 1313MB available, 223MB of 1536MB reserved
```

**Comment by jenshannoschwalm** [comment]
OK, partially solved, the calculations are correct for all platforms.

This leaves us with a penalty when running the first pipeline an a amd or Intel device (benchmarks or single image cli exports will be impaired)

Don't know how to solve this atm, will try to find some mentioning about buffer handling in amd dev guides.

**Comment by MStraeten** [comment]
here a measurement for an arbitrary set of images with different edits (custom build 3.8.1 and 3.9 with same macports config via `/opt/local/share darktable-cli ./ ./ --core  -d perf  -d opencl`) and export forced to use AMD GPU
3.9 with `opencl_tuning_mode=memory size`
values taken from `[dev_process_export] pixel pipeline processing took 4,704 secs (26,934 CPU) ` lines
  | GPU | CPU |   |   | GPU | CPU
-- | -- | -- | -- | -- | -- | --
3.8.1 | 2,819 | 3,037 |   | 3.9 | 4,704 | 26,934
3.8.1 | 1,536 | 7,642 |   | 3.9 | 1,467 | 6,955
3.8.1 | 1,527 | 8,372 |   | 3.9 | 1,454 | 8,092
3.8.1 | 8,54 | 24,933 |   | 3.9 | 10,056 | 24,496
3.8.1 | 2,947 | 20,599 |   | 3.9 | 2,976 | 20,331
3.8.1 | 2,383 | 20,18 |   | 3.9 | 2,805 | 23,502
3.8.1 | 4,278 | 19,634 |   | 3.9 | 4,38 | 18,197
3.8.1 | 5,473 | 36,035 |   | 3.9 | 5,502 | 34,925
3.8.1 | 0,869 | 6,701 |   | 3.9 | 0,872 | 6,896
3.8.1 | 5,214 | 13,565 |   | 3.9 | 5,012 | 12,522
3.8.1 | 7,245 | 32,772 |   | 3.9 | 7,596 | 28,157
3.8.1 | 4,553 | 19,514 |   | 3.9 | 4,872 | 19,17
3.8.1 | 2,615 | 11,102 |   | 3.9 | 2,621 | 10,079
3.8.1 | 3,002 | 17,089 |   | 3.9 | 2,621 | 16,059
3.8.1 | 2,08 | 11,244 |   | 3.9 | 2,037 | 10,946
3.8.1 | 2,521 | 9,651 |   | 3.9 | 2,538 | 9,076
3.8.1 | 4,608 | 14,176 |   | 3.9 | 4,582 | 13,52
3.8.1 | 3,737 | 15,416 |   | 3.9 | 3,716 | 15,064
3.8.1 | 2,744 | 12,019 |   | 3.9 | 2,782 | 11,668
3.8.1 | 5,051 | 41,802 |   | 3.9 | 5,185 | 39,338
sum  | 73,742 | 345,483 |   |   | 77,778 | 355,927

**Comment by jenshannoschwalm** [comment]
Thanks for those details. Your resourcelevel has been for 3.9 ? (Especially for CPU mode you should use large ...)

There seems to be something fundamentally wrong with your first example. Would it be possible to share raw and xmp? (just for testing, won't share and will delete "immediately")

**Comment by MStraeten** [comment]
there was an issue with first xmp - after using an older version that can be processed also with 3.8.1 the time are quite more comparable - some processing steps were skipped with 3.8.1 
i corrected the values in the table

**Comment by AxelG-DE** [comment]
I did test today with fresh darktablerc and deleted cached-kernels...
The results are good but not yet at the level of 3.8.1...

If I got that right, there was/are drawbacks of current solution, @jenshannoschwalm want(ed) to address after 4.0.0 release. Donno this is still the case or we have to live with the given scenario...

![grafik](https://user-images.githubusercontent.com/49004103/178544550-baeb3a59-ad48-4471-81b4-c717b669551c.png)

**Comment by AxelG-DE** [comment]
Hand-optimized does not look really faster, bat a bit more eaqual...
![grafik](https://user-images.githubusercontent.com/49004103/178548176-1a649bbc-1971-4d9d-98ef-d1d743a1d660.png)
