### ISSUE TITLE
FR:Visual indication that color calibration module is set other than 50% LUMA 0%HUE 0% CHROMA

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#11601]
I am not sure if this has happened to anyone but recently while investigating some posts on pixls.us and testing some playraw submissions I have a couple of times used the picker in CC for a WB and obtained strange results....

This comes from the fact that the color matching tab is by default collapsed and the values are persistent. So if you work on an image and adjust those settings they stay and will affect subsequent images. 

The way you invoke the color matching correction is the same way that you apply a spot wb correction.

This can lead to issues especially if you don't catch it...

I propose there should be a visual indication when the values are not sitting on 50:0:0 that is normal for spot wb or perhaps if they are modified that the module opens with that tab expanded rather than collapsed so that the user can see this....

I don't think I will be the only one stung by this but maybe and I think there are reasons for the settings to be persistent but also this can screw things up if that is not your intension....

Just my 2 cents....

**Comment by kofa73** [comment]
Resetting the module or applying any preset does not affect the matching functionality. I think a reset ought to remove any previous measurement.
Currently, one needs to remove the following settings from darktablerc:
```
darkroom/modules/channelmixerrgb/chroma=11.83570384979248
darkroom/modules/channelmixerrgb/hue=56.16925048828125
darkroom/modules/channelmixerrgb/lightness=31.824714660644531
```

**Comment by elstoc** [comment]
On the original PR I suggested a separate color picker for color matching, and to leave the existing color picker so that it always selects 'grey'.

**Comment by todd-prior** [comment]
I only suggested the warning or the expanded tab as options as I thought it might be easier to add than a new or separate picker. But I don't know that for a fact...

**Comment by aurelienpierre** [comment]
> On the original PR (or was it on IRC) I suggested a separate color picker for color matching, and to leave the existing color picker so that it always selects 'grey'.

Matching against grey is already color matching. As it turns out, it's entirely arbitrary and equally wrong since color-checker grey is not perfectly neutral either. And no picture is perfectly neutral in average either.

The current behaviour is designed for batch processing, where you set the target color at the beginning of the batch, and keep the same setting as long as you don't manually reset. 

It's less work to reset once per batch than having to fiddle in subsubsubmenus and uncollapse and shit for each picture.

**Comment by todd-prior** [comment]
@aurelienpierre I see why it is as it is for the batch function and I see it being persistent to serve that task but could there be an indicator that it is not at the expected default or could a reset of the module do just that reset everything. I usually use separate instances of CC when doing these sorts of things ie using the color tab or brightness  so I can turn them off and on to guage the effect. If you do this also with color matching I guess you would be okay but if you do it in the main instance and it is persistent I think it will bite a lot of people. So no need or vote from me for a second picker but some indication that color matching is in effect ie at some value outside 50:0:0 or barring that making the module reset also reset this property. I think that does seem logical and is the intent of that action in every module?? Ust my thoughts

**Comment by elstoc** [comment]
> and uncollapse and shit for each picture

Ah. This is where the issue is. Just make the collapsible section remember its expanded state between images. All other collapsible sections do this and so should the one in color calibration.
