### ISSUE TITLE
[FR] opencl_device_priority should be obeyed also on other scheduling_profile than only default, [issue with performance_configuration_version_completed]

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11607]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
- I run two discrete GPUs
- `opencl_device_priority` is only obeyed in in `opencl_scheduling_profile=default`
- up to now no big issue, I left `opencl_scheduling_profile=default`, as it is for me more performant than multiple GPU (which swaps the devices in use, in an unpleasant way (watch nvidia-smi), which costs time=peroformance
 
Lately it is getting annoying:
- when ever `performance_configuration_version_completed` gets iterated, it changes `opencl_scheduling_profile=default` to `multiple GPU`
- might be reasonable for many cases, but
- it keeps me busy setting it back to default

**Expected behavior**
**Ideally** `opencl_device_priority` is obeyed in any `opencl_scheduling_profile` mode
**Alternatively** on user-request (setting) `performance_configuration_version_completed` does **not change** the desired `opencl_scheduling_profile` mode

**Platform**

* darktable version : 3.9.0+1271~gdfeea3e9d
* OS                : Linux - kernel 5.17.3-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-510.60.02
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.3-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.31
* gcc               : x86_64-pc-linux-gnu-11.2.1
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"

**Comment by jenshannoschwalm** [comment]
> **Ideally** `opencl_device_priority` is obeyed in any `opencl_scheduling_profile` mode

Another point i'll check after 4.0

**Comment by AxelG-DE** [comment]
@jenshannoschwalm thank you for all your hard work! Much appreciated.
