### ISSUE TITLE
Turning clipping indicator and gamut check on simultaneously leads to unexpected indication behaviour

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#11609]
**Describe the bug/issue**

Turning the clipping indicator and gamut check on simultaneous leads to an unexpected indication result.
See screencast:

https://user-images.githubusercontent.com/810285/164912899-0841990c-5661-4b65-85be-15d7cdd56b39.mp4

**Expected behavior**

Turning on both indicators should result in a union of clipping and out-of-gamut indications, not in an indication which is not present when only either indicator is active. 

**Platform**

* darktable version : 3.9.0+1274~gd6456c1a6 (latest master)
* OS                 : Linux - 5.11.0-42-generic
* Linux - Distro : Ubuntu 20.04.4 LTS
* Memory          : 32 GB
* Graphics card : AMD Radeon RX 5700 XT
* Graphics driver : amdgpu 13.0.50002
* OpenCL installed  : yes
* OpenCL activated  : yes
* CMAKE_BUILD_TYPE : release

**Additional context**

 - Can you reproduce with another darktable version(s)? **I don't have another version to compare**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Comment by AxelG-DE** [comment]
- Would you mind to amend the "additional context" part from the template?
- In a quickcheck I see similar behaviour on 3.8.1

**Comment by da-phil** [comment]
> * Would you mind to amend the "additional context" part from the template?
> 
>     * In a quickcheck I see similar behaviour on 3.8.1

I did so, thanks for trying to reproduce with version 3.8.1.

**Comment by AxelG-DE** [comment]
new configdir and no more issue, that is interesting...
how about --disable-opencl?

**Comment by da-phil** [comment]
> new configdir and no more issue, that is interesting... 

Ups, that was a lie, I corrected it :smile: 

> how about --disable-opencl?

Also tried that, same issue.

**Comment by da-phil** [comment]
Would be great if anybody could confirm whether this is intended behavior or a bug?

**Comment by da-phil** [comment]
seems that this issue has been fixed in the meantime, as of master from 2023-02-18  (version 4.3.0+669~g25ff4c044f-dirty).
