### ISSUE TITLE
Cannot change language to something else than English

### ISSUE THREAD

**Issue by jibedoubleve** [darktable-org/darktable#11616]
## Describe the bug/issue

I cannot change the language to "fr".

## To Reproduce
1. Set the language to French
![image](https://user-images.githubusercontent.com/2678545/164945264-2f2df0cf-4968-4a4d-987e-e18fcb715aeb.png)
2.  Restart the application
3. This is still in English while I'm expecting it in french

## Platform

* darktable version : 3.8.1
* OS                : Windows 10 21H2 (OS Build 19044.1645)
* Regional settings 
![image](https://user-images.githubusercontent.com/2678545/164945407-4178ca85-70de-4ad7-b8ec-8e55f7f29770.png)

## Additional context

I tried
* Removing directory `C:\Users\[username]\AppData\Local\darktable`
* Uninstalling, reinstalling the app
* Editing the file `C:\Users\[username]\AppData\Local\darktable\darktablerc` and set `ui_last/gui_language=fr`

**Comment by Jiyone** [comment]
> Editing the file C:\Users\[username]\AppData\Local\darktable\darktablerc and set ui_last/gui_language=fr
Does it reset `ui_last/gui_language` to `en` ?

**Comment by jibedoubleve** [comment]
In the file it is:ˋui_last/gui_language=fr` while the UI remains in english.

**Comment by Nilvus** [comment]
Could you precise from where you download darktable?
And could you test by changing your regional settings on Windows to french language. As you post here, you're in english on Windows.

**Comment by jibedoubleve** [comment]
* I downloaded on Github, version 3.8.1: [darktable-3.8.1-win64.exe](https://github.com/darktable-org/darktable/releases/download/release-3.8.1/darktable-3.8.1-win64.exe)
* When I  change Windows language to French I have darktable in French.

**Comment by Nilvus** [comment]
>     * When I  change Windows language to French I have darktable in French.

So that confirm that the issue is related to Windows and seems that language is not correctly set depending on language used by Windows. I can't help more now. You know how to have darktable in french by now. To have french when Windows is not in french language, you will have to wait that a Windows developer see that issue and take time to answer/develop a fix (note that we have too few Windows developers).

**Comment by Mark-64** [comment]
I can't reproduce in windows on current master. Switching language works as expected
