### ISSUE TITLE
Picture from Camera Panasonic DMC-FZ100 couldn't be read

### ISSUE THREAD

**Issue by matbol** [darktable-org/darktable#11623]
**Describe the bug/issue**
I am using the raw-mode of my Panasonic DMC-FZ100 and darktable 3.8.1 directed me to make an issue, cause auf not supported rw2 format. But i could find my camera model at: [Supported Models]( https://www.darktable.org/resources/camera-support/)

![grafik](https://user-images.githubusercontent.com/48551028/164985306-3a0ec53f-0449-490f-a385-c05a1e7b6792.png)

I could not upload the picture, recently shot in my holidays in format .rw2. 

**Platform**

* darktable version : 3.8.1
* OS                : Win 10 Home
* Memory            :  8 GB RAM
* Graphics card     : NVIDIA GeForce 940M
* Graphics driver   : NVIDIA GeForce 940M
* OpenCL installed  : Unknown
* OpenCL activated  : Unknown
* Xorg              :  Unknown
* Desktop           :  Unknown
* GTK+              :  Unknown
* gcc               : Unknown
* cflags            : Unknown
* CMAKE_BUILD_TYPE  : Unknown

**Additional context**

Jpeg from this camera model just works fine additionaly, the metadata from rw2 format also has been read right.

**Comment by victoryforce** [comment]
What is the aspect ratio of the image the program complained about?

**Comment by kmilos** [comment]
The support probably got suspended temporarily because of missing samples:

![image](https://user-images.githubusercontent.com/4973094/165054210-a237c5bb-5b3c-4a4b-add2-3d8da3e1723e.png)


Please provide the required samples at https://raw.pixls.us/ if you'd like to see support for this camera restored in the future.

**Comment by kmilos** [comment]
Thanks. Have you uploaded **all aspect ratios**  (4:3, 3:2, 16:9, 1:1) as requested?

What about the question @victoryforce asked?

**Comment by kmilos** [comment]
Can you perhaps confirm that a 4:3 sample works at the moment?

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/commit/2600f777e1c1d28158c93484ab9eef4f9b61d973
