### ISSUE TITLE
selection filters : custom-sort no longer possible

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#11628]
**Did you buy darktable from an application store ?**
no, self build from current git master

**Describe the bug/issue**
In collections filter for example selecting "capture time" or "filename" works as expected. Selecting "custom-sort" does not work anymore.

**To Reproduce**
Go to lighttable
Goto "selection filters" module
Select "capture time" -> images are shown in correct order
Select "filename" ->  images are shown in new correct order
Select "custom-sort" and try to reorder images by dragging/dropping them. Reordering is no longer possible.

**Expected behavior**
In mode "custom-sort" it should be possible to reorder images as the user wants.

**Which commit introduced the error**
possibly https://github.com/darktable-org/darktable/pull/11622

**Platform**
darktable version : 3.9.0+1285-gab83b180b
OS : Linux 5.4.0-109-generic / Ubuntu 20.04.4 LTS
Memory : MemTotal:       65780936 kB                                                                                 
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060                                  
Graphics Card : Driver Version                            : 470.103.01                                               
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2                                    
OpenCL activated : yes                                                                                               
Xorg : Version: 1:7.7+19ubuntu14                                                                                     
Desktop : LXQt                                                                                                       
GTK+ : 3.24.20                                                                                                       
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0                                                                            
CMAKE_BUILD_TYPE : release

 - Can you reproduce with another darktable version(s)? **did not try**
 - Can you reproduce with a RAW or Jpeg or both? **both**

**Comment by Nilvus** [comment]
@AlicVB: another one for you I fear

**Comment by pehar1** [comment]
Just left the application, relauched, and now I'm no longer able to reproduce the issue. Actually I have no idea what happened. Could reproduce the issue before for more than half an hour with many different collections. Maybe a false alarm !

**Comment by pehar1** [comment]
Did some further tests in the meantime. After selecting any **leaf** node of any tree in collections module -> metadata -> tag, which unexpected switches the sort order to "filename" (step 3 and 4) in step 6 not only "custum-sort" is broken as described above, but also several other sort orders. Other sort orders can be selected from the pulldown menu (and are correctly shown as selected in the pulldown menu) but for many (not all) sort orders the thumbnails shown on lighttable are **not** reorderd according to the setting.

One has to quit the application, then relaunch, to get back normal behaviour.

**Comment by pehar1** [comment]
Update and further specification : 
now using 3.9.0-1362-ga1de270c4

- the issue not beeing able to "_custom sort_" at point 6 is **related to the usage of the new "_history_" pulldown menu of the _collections_ module**. Only if this menu is used to switch back (point 5), the sort order remains at "filename" and most sort orders do not work anymore as described above.

If one switches back by using the upper left pulldown menu ("_film roll_", "_metadata_", "_times_"...) the sort order correctly switches back to "_custom sort_" and all sort orders work as expected.

**Comment by AlicVB** [comment]
ok, I can reproduce. This is indeed the use of the history that cause this. You'll note that the issue also exists in 3.8.1 version (but "history" should be select in the "recent collection" module)
I'll have a look asap !

**Comment by AlicVB** [comment]
PR #11701 should fix it. Thanks for the report !

**Comment by TurboGit** [comment]
Can one of you give a clear step by step procedure to reproduce? I have tried the standard drop downs, the new history sub-menu.. switching between multiple sort and when I do to custom sort it always work on my side.

I cannot reproduce, so it will be hard to double check whether the fix is ok or not.

**Comment by AlicVB** [comment]
@TurboGit : here is how I have reproduce (this @pehar1 step by step with some change added in bold)

1. **Remove your darktablerc**
2. Go to collection module, select a collection ("film roll")
3. Go to collection filters, select "custom-sort" -> reorder some images -> reordering is possible
4. Go to collections module, select metadata -> tag
5. Select any leaf tag -> see that sort order unexpected changes to "filename" **(this IS expected as each tag collection save its own sort order)**
6. Go to collection module, **select previous "film roll" with the history menu**
7. Change order back to "custom-sort" -> nothing happens, reordering by dragging/dropping is no longer possible

Are you able to reproduce now ?

**Comment by TurboGit** [comment]
@AlicVB : Yes I can reproduce now, thanks!
