### ISSUE TITLE
Have 'retouch' use source from a different image

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#11630]
**Is your feature request related to a problem? Please describe.**
When removing something/someone from a picture it can help a lot if you could access a source from a reference picture, where you photographed the same scene without distractions.

**Describe the solution you'd like**
I understand this is a big one.
But I may have a hack.
I would like it if you could make the reference from a second picture.
Maybe it is possible to generate a kind of 'virtual' photo which has both photos side by side. Then, to all the modules, it will simply look like a very wide picture.  You can then easily reference material from 2 different versions of the photo.
Only the 'export' module should still only export the original picture.

**Comment by MStraeten** [comment]
darktable doesn’t touch the raw file so the source can‘t be copied from somewhere else since there’s no way to persist the source in a reliable way.
if you need such hack, you might export both images after applying basic modules and merge that stuff in an image editor and continue on the merged stuff.

**Comment by rekcodocker** [comment]
Thanks for the reply. Good point. 
I'd want to keep this as easy as possible. No changing the raw!
I know it is already a difficult one, bordering on unreasonable. 

However, there is a precedent:  When you copy a raw + xmp with a Lut-operation to another computer which doesn't have the same Lut file, that operation will fail. 

I'm not looking into a discussion why this is OK for Lut files. I understand.
I would be perfectly happy for this feature to break if the referenced file is not in the same directory as the edited file.
After all, this would be pretty advanced editing so I'd be 100% ok with 'Don't delete the file or suffer the consequences.'
