### ISSUE TITLE
html tags in module name

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#11635]
Probably a side effect of 409331dd2ba64664044b54937e9138e853e9d55a, duplicate module names are displayed as:

![ss](https://user-images.githubusercontent.com/12815378/165152032-82b7e363-fd92-4428-a75d-6d80bd39fcd7.png)

dt: 3.9.0~git1290.e466ca37c1

**Comment by TurboGit** [comment]
I'll fix that tomorrow.

**Comment by TurboGit** [comment]
Has been fixed.
