### ISSUE TITLE
Lagging of lighttable UI on current master branch in case of large image DB 

### ISSUE THREAD

**Issue by apfelkraut** [darktable-org/darktable#11642]
**Describe the bug/issue**
The UI, at least within the lighttable view, is experiencing some significant lagging (> 1 sec.) when one's database includes a larger number of images (>50.000 images).

**To Reproduce**
1. Make sure that your darktable database includes many and not just a few dozens of images
1. Go to lightable to view a specific collection or all images
2. Verify that permanent overlays are activated
3. Open an image in "full preview" e.g. by pressing key F
4. E.g. set the rating by pressing 1-5 or R
5. Observe the time until the rating change is displayed within the UI widget/overlay

**Expected behavior**
The rating is instantly applied and displayed without any delay. 

**Which commit introduced the error**
This must have happened somewhen after the 3.8.1 release ...

**Platform**
* darktable version : [darktable-3.9.0+1273\~ga900d8c3e](https://discuss.pixls.us/t/current-osx-build/13213/438) (build for Intel), [darktable-3.9.0+1092\~g596d7bdf3-arm64](https://github.com/darktable-org/darktable/issues/7564#issuecomment-1102120236) (build for arm64/M1)
* OS                : macOS 12.3.1 
* OpenCL  : no difference if active/deactivated
* GTK+              : 3.24.33 (in darktable-3.9.0+1092\~g596d7bdf3-arm64)

**Additional context**
The lagging cannot be observed when using the official [darktable-3.8.1.dmg](https://github.com/darktable-org/darktable/releases/download/release-3.8.1/darktable-3.8.1.dmg) or [building the 3.8.1 sources for arm64/M1](https://github.com/darktable-org/darktable/issues/7564#issuecomment-1108906878).

**Comment by apfelkraut** [comment]
@wpferguson thanks a lot for looking into this!

I just built today's master (f4767440d11dd06f353b71e3a2f537b6b74dea5f to be precise). Same behaviour, might point to a mac-specific problem. 

Still worth to note that in case I delete the `data.db` and `library.db`, so start in my understanding with an empty database, and then import just a few images (ca. 500), I do not observe any lagging when rating images with the exact same build.

Not sure if it is of any help, but please find attached the debug output [(darktable_debug.log)](https://github.com/darktable-org/darktable/files/8575746/darktable_debug.log). I opened darktable, selected another image, pressed key F for "full preview" and changed the rating of that image. Afterwards closed the "full preview" and exited darktable.

**Comment by ralfbrown** [comment]
Can confirm on Linux with current master (4.1.0+19).  But it requires the current collection to have tens of thousands of images, not just the library.  With 342k images in library, a collection with a few hundred images is instantaneous, one with 14k images adds perhaps 0.1 seconds of lag, and a collection with all 342k images adds 1-2 seconds of lag when changing star ratings while in full-screen (F) view.

**Comment by apfelkraut** [comment]
Closing issue as it cannot be reproduced any longer on https://github.com/darktable-org/darktable/tree/release-4.0.0

Same database that was used to report this issue works fine without any lagging in darktable 4.0
