### ISSUE TITLE
Updated dutch translation file nl.po

### ISSUE THREAD

**Issue by stephanh73** [darktable-org/darktable#11646]
Here is an update of the dutch translation file nl.po

[nl.zip](https://github.com/darktable-org/darktable/files/8565473/nl.zip)

**Comment by TurboGit** [comment]
Thanks! This is now integrated. Note that we are close to a release and so the translation must be done before mid-june. For the record the current status is:

`4119 translated messages, 252 fuzzy translations, 139 untranslated messages.`
