### ISSUE TITLE
Pickers invisible for filmicrgb black and white levels

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#11652]
3.9.0+1319~gc969328d1
![image](https://user-images.githubusercontent.com/3177739/165388824-d1655331-d5dc-4a47-9661-b2bffcbd56d0.png)
The pickers are still there and clickable, working fine, even though they are not shown on the UI.
Might come from @Nilvus's CSS changes?

**Comment by Nilvus** [comment]
Really strange, I remember see them with my PR. But you're right, it's from my work. Will check.

**Comment by kofa73** [comment]
The one to diagnose the problem was @elstoc. :) He also told me to open an issue for this. Thanks!

**Comment by Nilvus** [comment]
Ok, thanks to @elstoc (and you for opening this). Fix just pushed on #11653. Was just too much cleanup...
