### ISSUE TITLE
Darktable does not generate an internal thumbnail in Jpeg files

### ISSUE THREAD

**Issue by aexpi** [darktable-org/darktable#11662]
Darktable 3.8.1 does not generate an internal thumbnail when creating jpeg files from .raf, which should be in Exif and used by Windows Explorer and other programs to display files faster

Add this feature in settings

**Comment by Nilvus** [comment]
Please detail your issue. It will be hard to answer to you with so few infos. We provide an issue template for good reasons. You avoid nearly all infos (OS, darktable release, etc.). And a precise step-by-step? What do you means also by "converted jpg"? From darktable, from you camera? Another software?

**Comment by aexpi** [comment]
Good day! Change description

ср, 27 апр. 2022 г., 23:04 Nicolas Auffray ***@***.***>:

**Comment by ptilopteri** [comment]
a jpg file is created to save space.  why would one want to increase
that space by including a thumbnail which *most* systems create themselves
anyway?

plus more code for dubious purpose.

**Comment by aexpi** [comment]
The built-in Thumbnail has a size of about 1% of the entire file.
Thumbnails helps Windows and other programs make their own cache with
Thumbnails.
Secondly, all editors make them except Darktable and this is disappointing

чт, 28 апр. 2022 г., 1:47 ptilopteri ***@***.***>:

**Comment by jorismak** [comment]
> Secondly, all editors make them except Darktable and this is disappointing

I don't know or any other editor that writes a jpg in a jpg.
It's just as quick to just open the original jpg in most cases so i also don't really see a reason ?
