### ISSUE TITLE
When cropping two consecutive images, switching from the second image back to the first massively amplifies the crop

### ISSUE THREAD

**Issue by tamius-han** [darktable-org/darktable#11668]
**Describe the bug/issue**
If you crop two images in a row, switching back to the previous image results in an incorrect crop. This is order-dependant: editing or merely viewing a third image seems to not result in the bug.

**To Reproduce**
0. Put some images (RAW) into the lightroom
1. Crop the first image
2. Crop the second image
3. Switch back to the first image
4. The first image is now cropped much more than it used to be

**Expected behavior**
The first image should retain the crop.

**Screencast**
https://gfycat.com/ifr/SparseFloweryJapanesebeetle

**Platform**

* OS: Windows 10 (will get it once I boot it back up); Linux 5.17.1-3-MANJARO 
* darktable version: 3.8.1; 3.8.1 (official community repo)
* Linux - Distro    : Manjaro
* Memory            : 32 GiB
* Graphics card     :  nVidia 2080 Ti
* Graphics driver (Win):  (will be added later, but I keep my drivers rather up to date)
* Graphics driver (Linux): Proprietary, NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6 
* OpenCL installed  : ?
* OpenCL activated  : ?
* Xorg              :  Yes
* Desktop           : KDE/Plasma 5
* GTK+              :  ?
* gcc               :  ?
* cflags            :  ?
* CMAKE_BUILD_TYPE  : ?

**Additional context**

 - Can you reproduce with another darktable version(s)? _Didn't try._
 - Can you reproduce with a RAW or Jpeg or both? _Only tried RAW._
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? _yes_
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? _do I still have to do this if it's literally a fresh install on Linux?_
 - Do you use lua scripts? _no_

**Comment by emko** [comment]
i can also reproduce this

**Comment by Jiyone** [comment]
Same effect as #11615 🤔

**Comment by AlicVB** [comment]
ok, I finally manage to reproduce. The key seems to be that the crop module need to be not active when returning to the first image... I'll have a look !

**Comment by AlicVB** [comment]
I think PR #11686 should fix it...
