### ISSUE TITLE
New update dutch translation nl.po

### ISSUE THREAD

**Issue by stephanh73** [darktable-org/darktable#11679]
Here is a new update of the Dutch translation file nl.po

[nl_29042022.zip](https://github.com/darktable-org/darktable/files/8588585/nl_29042022.zip)

**Comment by TurboGit** [comment]
Thanks, translation 100% done. Note that until the string freeze there will be some more string changes (probably not a lot). But please do monitor the darktable.pot change to update the nl.po if needed. TIA.
