### ISSUE TITLE
<Enter your camera name here>Olympus OM-1

### ISSUE THREAD

**Issue by Chasverizon** [darktable-org/darktable#11677]
I submitted the raw file image of the color card of the x-rite Color Checker Passport Photo. When I tried to upload the image for the black and white color card from x-rite it said it was already loaded. I am not sure if I made an error or if both raw images were sent. Thank you for your help.

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by Nilvus** [comment]
So closing

**Comment by Chasverizon** [comment]
Thank you for your time. Darktable is great. Looking forward to using Darktable to edit raw images taken with my new Olympus OM-1 camera on my Linux computer.
