### ISSUE TITLE
[enhancement] Documentation: specify variable scope

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11675]
https://docs.darktable.org/usermanual/3.8/en/special-topics/variables/ says:

> darktable supports variable substitution in a number of modules and preference settings. For example: etc

Actually giving some example of variable scope is poor documentation.

It would be nice if the variable table below could specify the scope in which each variable is available.

**Comment by Nilvus** [comment]
Good place now to post issue about the doc is on dt docs repository: https://github.com/darktable-org/dtdocs
Please so post there your issue.
