### ISSUE TITLE
crawler claims xmp and library db out of sync

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11683]
**Describe the bug/issue**

Since some weeks Sporadically I get the crawler synchronisation window, claiming updated sidecar files found.
- I did _not touch_ those pictures, neither from dt, nor some other weirdo stuffs. 
- The xmp files are actually updated to the date, which is listed in that box, just I donno how
- Sometimes it comes again and again, even though I just selected "keep db edit"

**Expected behavior**
There should be no non-synchronous xmp vs. db when those pics are not even touched via gui or otherwise

**Screenshots**
![Screenshot_20220429_173020](https://user-images.githubusercontent.com/49004103/165979209-609bb4fc-9a76-4aa9-83b5-d42bb99ae207.png)

**Platform**
* darktable version : 3.9.0+1354~gb0258dade
* OS                : Linux - kernel 5.17.5-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-510.68.02
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.3-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.31
* gcc               : x86_64-pc-linux-gnu-11.2.1
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by ptilopteri** [comment]
shot in the dark,
do you have a date/time issue on your work machine?

**Comment by AxelG-DE** [comment]
open-ntp is activated and time appears synced

**Comment by AxelG-DE** [comment]
![Screenshot_20220430_165834](https://user-images.githubusercontent.com/49004103/166110882-b0309edc-f8f0-4b21-8bc5-615661fc76ef.png)
Particularly the marked ones, I didn't even go close to them, so WTF

The xmp even does not have the claimed timestamp on fs-level (just one example):
```
$ ls -la /home/gerber/Bilder/D750/2016/20160806_Ffm_Goetheturm_D750/AG7_4939.NEF.xmp
-rw-r--r-- 1 gerber users 13879 28. Apr 16:50 /home/gerber/Bilder/D750/2016/20160806_Ffm_Goetheturm_D750/AG7_4939.NEF.xmp
```

**Comment by AxelG-DE** [comment]
$ stat /home/gerber/Bilder/D750/2016/20160806_Ffm_Goetheturm_D750/AG7_4939.NEF.xmp
```
  File: /home/gerber/Bilder/D750/2016/20160806_Ffm_Goetheturm_D750/AG7_4939.NEF.xmp
  Size: 13879           Blocks: 32         IO Block: 4096   regular file
Device: fd0fh/64783d    Inode: 48562234    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  gerber)   Gid: (  100/   users)
Access: 2022-04-29 03:56:11.925905867 +0200
Modify: 2022-04-28 16:50:52.317231332 +0200
Change: 2022-04-28 16:50:52.317231332 +0200
 Birth: 2020-04-25 01:33:56.912997941 +0200
```
