### ISSUE TITLE
selected color pickers invisible in dark mode

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11680]
Using the dark mode, the color pickers in exposure, filmic (white / black relative exposure), color look up table, color balance rgb (and possibly others) are not visible anymore.

@Nilvus : this one is for you :)

**Comment by Nilvus** [comment]
I didn't touch them on my last work. Or is it the same issue as grey theme. But when I fix it, I have check others themes and seen them. I don't understand but will see why...

**Comment by Nilvus** [comment]
@TurboGit: could you share a screenshot and on which commit you are?

On my side? I have them visible in dark mode:

![image](https://user-images.githubusercontent.com/45535283/165935634-0baba302-2ea9-4f20-96a4-6917a7c6fe9b.png)

Tested on 3.9.0+1330~gf4767440d

**Comment by Nilvus** [comment]
Last thing, could you test by adding that line and check what you have? You will need to change theme (or restart darktable) to see effect if you apply it on preferences CSS part.

`@define-color bauhaus_fg @fg_color;`

I removed that line as it is just repeat fg_color line (that's the setting applied on color pickers) and it works on my side, without that line.

**Comment by TurboGit** [comment]
Note that they are not visible when you click on it (when they are active). The strange thing is that the auto-tune levels (last on your screenshot is fine).

**Comment by Nilvus** [comment]
It's not strange, they are not same widgets. auto tune ones is set as a button now. Other are inside bauhaus-slider
So if it's in active state, it's so probably because of my code changes on bauhaus and not really on color picker (sort of bad side effect).

**Comment by TurboGit** [comment]
And yes adding:
@define-color bauhaus_fg @fg_color;

Fixes the issue. Note that BTW while testing I found that we have the same issue on the darkter theme (your fix is ok for both dark & darkter) mode.

**Comment by Nilvus** [comment]
Ok, that's strange that I don't have the issue on my side. It's normal that that line have effect from both themes. That line is set on main theme and darker theme inherit from it.

Ok, I will so add it back even if I really don't understand why this is necessary as all items should inherit by default from @fg_color define line...

I will so revert back that line in the PR I'm actually preparing (with some fresh new icons and some minor fix). I should post today or tomorrow.
