### ISSUE TITLE
collections module, narrow down to "lense",  list always jumps to top entry

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#11684]
**Describe the bug/issue**
I want to narrow down my pictures selection by the lens I used. This is not possible, because when I scroll down, the list jumps to first entry by it self. Even worse when using mouse scroll wheel.

@AlicVB could be this one for you?

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
See screencast

**Expected behavior**
List should not "jump" but stay where selected

**Screencast**
_(if applicable)_

https://user-images.githubusercontent.com/49004103/165980341-8adc2d4e-f316-4bd1-b69c-2edbd8d65159.mp4

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _
* darktable version : 3.9.0+1354~gb0258dade
* OS                : Linux - kernel 5.17.5-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-510.68.02
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.3-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.31
* gcc               : x86_64-pc-linux-gnu-11.2.1
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by AlicVB** [comment]
hmmm... I can't reproduce...
- Does it happen only with lens, or with other property too ?
- does it happen if you use only one rule (with lens property) ?
- I can't see on the screencast, but do you click on the item to have the list "jump" or it's just by moving the mouse ?

**Comment by AxelG-DE** [comment]
@AlicVB 

- that you can't reproduce, that means, you "narrow down search" to something, where the next list is larger than the "window" and you can scroll down the list and it will stay there until you did your selection?????
- I just tried with ISO and aperture and get the same mis-behaviour
- it looks a bit slow in my screencast, because I dragged the scroll bar on the side of the module. Usually I take the scroll-wheel on mouse. And *no*, I didn't click or do anything. The list just jumps up to the top row by it self, faster than you could do your selection. It is as severe, it is totally not useable.
- Just tested, 3.8.1 does not have that behaviour. Bisecting will be hard, because db has changed in between several times, which means new imports are necessary every time

**Comment by AlicVB** [comment]
> * that means, you "narrow down search" to something, where the next list is larger than the "window" and you can scroll down the list and it will stay there until you did your selection

exactly. I've tested that multiple time and I confirm that I can't reproduce, whatever the nb of items (tested with aperture which produce a big amount of different values for exemple)

What I find strange is that this seems so critical that it's strange nobody else report something already... Hence the question : Do someone else reproduce ???
That would help us to track down the root cause ! Because for instance I've absolutely no idea what can cause that...

**Comment by pehar1** [comment]
dt 3.9.0+1347-gf5b3a754b, Ubuntu 20.04
Not able to reproduce. Tried with all entries from _collections -> capture details_, all are working as expected. Also tried with only one condition, and with two conditions (_film roll -> narrow down search -> lens_ ...) like shown in the screencast.

**Comment by jade-nl** [comment]
I already reported this to Axel on #darktable but I'll also put it down here to make it a bit more official:

I'm not able to reproduce this either. Tried this on small and big sets of images, trying different categories (lens, ISO etc) and single/double selections. Also tried using the scroll wheel and the slider.

This was done using 3.9.0+1354~gb0258dade on Debian 10.12/Buster

**Comment by AxelG-DE** [comment]
I did test yesterday evening and afterwards I closed dt (no worries, I close it regularly :-) )
This morning I cannot reproduce my self either. The only thing I did in between, I disabled intel GPU driver

Currently my laptop crashes on the intel-GPU (as my PC did hence I deactivated for PC), so as soon I can run my laptop again, I will check whether or not this is an intel-GPU thingie

I am at 3.9.0+1354~gb0258dade

**Comment by AxelG-DE** [comment]
> What I find strange is that this seems so critical that it's strange nobody else report something already... Hence the question : Do someone else reproduce ??? That would help us to track down the root cause ! Because for instance I've absolutely no idea what can cause that...

@AlicVB 
- yesterday I updated my gentoo and llvm13 got merged, causing my intel driver not to work anymore for iGPU (I remember, one of the related drivers does not compile well towards llvm13, but forgot the details....
- I was anyway planing to disable the iGPU on my PC, hence I used that moment to do so
- I assume it was related to this, so even I cannot reproduce anymore
- for my laptop, as I said above, I still cannot make intel iGPU work (laptop only has the HD5500). I try today if I can re-activate and if also there I cannot reproduce I will close here
- I will ask on #darktable if anyone with intel-iGPU can try one more time

**Comment by dterrahe** [comment]
@AxelG-DE if you can't reproduce this at the moment (?) maybe you could close this issue? You can always reopen later if it comes back.

**Comment by AxelG-DE** [comment]
Sorry for late reaction. I close for time being, as I cannot reproduce on my own atm.
