### ISSUE TITLE
[export] file format should better be independent in the various storages

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11690]
Now if you change the file format, the change reflects in all (or almost all) the storage types.

This is not the optimal behaviour, because I easily want to use a format for saving on disk, a different one for sending by email, a different one for hugin panorama, etc.

So the file format shouldn't be the same for all the formats, each target storage should keep memory of its preferred format.

**Comment by wpferguson** [comment]
You can do what you want just using presets

**Comment by paolobenve** [comment]
> You can do what you want just using presets

In theory, yes. I'm a IT-skilled person, but not a darktable-skilled one, I hardly understand how presets are set.

For darktble-newby persons, I consider this enhancement very useful.

**Comment by wpferguson** [comment]
So if I understand correctly you want to change the way darktable works because you don't want to read the manual?

**Comment by paolobenve** [comment]
no, you don't understand correctly :-)

Presets are a very good thing!

I simply want the export module to remember the state of each storage, at least in the export format.

If a user (which possibly stores some preset for this module) modifies the format of a storage without saving it in a preset, when he goes back to that storage finds the format he had left there.

I think it's an enhancement that - when correctly implemented - makes user experience better :-)
