### ISSUE TITLE
Darktable doesn't know the maximum webp size of 16383 pixels

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11704]
3.8.x

I have a big image 20,000 x 5,000 pixels.

Darktable exports it to jpg wihout any problem.

Trying to export to webp, exporting ends up saying: "could not export to file '/my/dir/myfile.webp'", and the webp file has 0 bytes length.

Here is the image: [20000x5000.zip](https://github.com/darktable-org/darktable/files/8599760/20000x5000.zip)

I could verify that exporting to webp works with not-big images (normal raw, 5,000 x 4,000 pixels).

**Comment by paolobenve** [comment]
Actually it should depend on the maximum webp size:16383 x 16383, see https://developers.google.com/speed/webp/faq

Then, darktable should **warn the user that the image size exceeds the maximum allowed webp size**.

**Comment by paolobenve** [comment]
I suppose that the same issue appears with exceeding sizes and other formats. Here are the maximum sizes:

avif: 3,840 x 2,160
png: 2,147,483,647 x 2,147,483,647  
jpeg: 65,535 x 65,535
heic: 8,192 x 4,320
jpegxl: 1,073,741,823 x 1,073,741,824

"HEIC and AVIF can handle larger images but not directly in a single code stream. You must decompose the image into a grid of independently encoded tiles, which could cause discontinuities at the grid boundaries".

(from https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs)

**Comment by kmilos** [comment]
FYI: we do still miss the ICC embedding for WebP export, so only assumed sRGB works correct for now.

**Comment by paolobenve** [comment]
I checked #12101, the patch actually reduces the maximum dimension, in the case: with the 20000 x 5000 test image, webp exported image is 16383 × 4096

Shouldn't the user be warn of it?
