### ISSUE TITLE
showing wrong image selected when using arrow keys to navigate film strip in darkroom

### ISSUE THREAD

**Issue by emko** [darktable-org/darktable#11709]
To Reproduce
bind arrow left and right to image back and image forward in darkroom

as there is no way to scroll film strip in db i have to set the arrow keys when using a wacom pen, issue is that when navigating back and forth you can't be sure what image is selected as sometimes it will show you the wrong image as being selected and when your dealing with similar images you won't even notice.

Screencast
https://streamable.com/f5b23r

    darktable version : 3.8.1
    OS : Fedora 36
    Memory : 32gb
    Graphics card : 970
    Graphics driver : Nvidia

    Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes

**Comment by AlicVB** [comment]
hmm... I can't reproduce...
I'm not sure, but I remember to have fixed something in this area recently... By any chance, can you try with current master ? (backup everything first) TIA

**Comment by emko** [comment]
> hmm... I can't reproduce... I'm not sure, but I remember to have fixed something in this area recently... By any chance, can you try with current master ? (backup everything first) TIA

**Comment by emko** [comment]
https://i.imgur.com/YkZ8WHP.png

just tested latest master, i still get the same result as you can see its showing different image then what it is shown as selected
