### ISSUE TITLE
[FR] global guide overlay settings

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11707]
I closed the  #10367 post in favor of this one.

With the addition of contrast to guides in the global guide overlay settings (great! BTW) I was thinking the possibility to add some features to the outside area present globally and in crop, retouch, rotate and perspective  and lens correction modules.

Maybe will be fine to change the name "global guide overlay settings" to "global correction overlay settings" or "global overlay settings" to have the ability to control all the overlay settings of the correction modules.

**Is your feature request related to a problem? Please describe.**
Sometimes perform a correction module to an image does not always look good when the module is active either because of too much contrast or lack of it of the overlay outside area and don't looks fine, intense colors outside the area tends to be annoying too.

**Describe the solution you'd like**
It would be good to integrate to correction modules the ability to control the overlay outside area (black, grey and white) similar to how change the color of the guides, the opacity (0% to 100%) and the saturation (0 to 1.000), desaturation would be to avoid the distraction that colors can cause. because in all images it does not look nice and affects the decision of the area to correct.

**Additional context**
This are two mockup with themes grey and darker (modified).

![global guide overlay settings_00](https://user-images.githubusercontent.com/67672868/166308153-7a42e342-8e8c-4b50-b4ce-1f1b035bbc03.png)

![global guide overlay settings_01](https://user-images.githubusercontent.com/67672868/166308171-73e125ce-2867-4848-a70f-9d2b9789b68a.png)

**Some situations with the same image.**

Grey overlay outside area:
![crop_01_grey](https://user-images.githubusercontent.com/67672868/166289337-5a0db72b-9b7f-4f23-a0ef-394bef207e65.jpg)

White overlay outside area:
![crop_03_white](https://user-images.githubusercontent.com/67672868/166289435-37ae52b7-f658-4136-9edf-f2ece512d397.jpg)

Black overlay outside area:
![crop_02_black](https://user-images.githubusercontent.com/67672868/166289480-b5229a0e-5943-4a00-9952-d988b9347675.jpg)

Desaturated overlay outside area:
![crop_04_desaturate](https://user-images.githubusercontent.com/67672868/166289545-0c1e426a-8b12-4f0b-87bb-8feb2aa50f94.jpg)

**Comment by MStraeten** [comment]
What’s the ‚outside‘ area in guides in general? It might be an interpretation of rule of thirds or golden rule but what about the other guides?
If you need such framing, why not enhance the crop module to get a further mode showing the crop that way even the crop module is left

**Comment by difrkaguilar** [comment]
It seems that my explanation has not been totally enlightening, maybe because I do not know how to express myself since my English is not good enough and I use the translator, the interpretation "outside area" is the area that is outside the frame, no matter what kind of guides are shown.

Each program makes an interpretation of this area as its developers have planned. Here I leave examples of GIMP, Capture One, even Photoshop customized this area even more, allowing the user to use a certain color of his choice. In the case of this FR I only put the option to switch between gray and black white with their respective opacities and the possibility of desaturating the background.

**Additional video and screenshots**

GIMP sample:
https://user-images.githubusercontent.com/67672868/166395391-48fab9f7-8391-424e-b2a6-7af78254254f.mp4

Capture One 21 sample:
<img width="1440" alt="Captura de Pantalla 2022-05-02 a la(s) 9 12 50 p  m" src="https://user-images.githubusercontent.com/67672868/166395469-d3f733d9-ce41-4801-862f-00b60ce32fd4.png">

Photoshop sample:
<img width="1440" alt="Captura de Pantalla 2022-05-02 a la(s) 10 26 34 p  m" src="https://user-images.githubusercontent.com/67672868/166396494-df4fd683-37e1-4128-b9f7-701951504fad.png">

Maybe the mockups aren't the best choice but an idea.

**Comment by difrkaguilar** [comment]
> What’s the ‚outside‘ area in guides in general? It might be an interpretation of rule of thirds or golden rule but what about the other guides? If you need such framing, why not enhance the crop module to get a further mode showing the crop that way even the crop module is left

I'm not talking about hide or show any guide in particular but the background area.

This is another screenshot of the #10367 FR recently closed.

![140848883-1dec17fc-a91c-4e67-bbc7-ad4f9f788431](https://user-images.githubusercontent.com/67672868/166400320-bcc1f819-e28c-437a-94fa-e15fb7157abc.png)

**Comment by difrkaguilar** [comment]
Pin! ;-)
