### ISSUE TITLE
[filmicrgb] error message exporting (but exporting seems to work)

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#11705]
3.8.x

I have a big tiff panorama, 660 MB.

Darktable exports it to jpg wihout any problem.

But enabling the filmicrgb modul with an eliptic shape, during export a message appears, saying "tiling failed for module 'filmicrgb'. output may be garbled". However, I can see the exported jpg (with gthumb, actually).

My sidecar file: [Santa Clara hugin.tif.zip](https://github.com/darktable-org/darktable/files/8599634/Santa.Clara.hugin.tif.zip)

**Comment by jenshannoschwalm** [comment]
That's just a warning about dt resources are small for that specific image. Just a reminder for you, not an issue.

**Comment by paolobenve** [comment]
well, the user that sees this message remains with the doubts:

- will the exported image has filmicrgb module correctly applied?
- ok, the image hasn't any error, but does it have all the modules applied?

**Comment by jenshannoschwalm** [comment]
Don't know how to handle this problem the best way.

There are no problems to be expected but we can't be absolutely sure as your operating system might support swapping gracefully or not. (For linux this depends on config data and kernel) So filmic tries do do it correctly here, you just can't be sure if everything went right so there is a warning "... may be garbled" which seems to be correct for my understanding.

Do you have a better wording/text suggestion?

**Comment by jenshannoschwalm** [comment]
@paolobenve i checked the tiling code and indeed the message is misleading for what the code does here. I will fix that as i am already working on tiling stuff a lot.

**Comment by paolobenve** [comment]
@jenshannoschwalm thank you

**Comment by jenshannoschwalm** [comment]
Yet i don't know a good "wording".
The fact is: there has been a problem within the tiling code which is most likely related to missing ram (the other reasons are more obscure) so the system had to run a specific module possibly using all resources of your system including swapping. So that **might** be a problem but dt can't know for sure. At least we want to make the user aware of a `possible` problem.

What would be your proposal?

**Comment by paolobenve** [comment]
> What would be your proposal?

- the warning appears, quite little, and desappears after 2/3 seconds, the user perhaps sees it, but it vanishes, and the user remains with the doubt: I may have missed some important info about the exported image... Make a more visible, non-vanishing alert?
- explaining better - with more words - the issue? maybe a link to a page that gives the necessary info
- when the user loads a big image, warn him that darktable could be short in resources, and that the system can hung (?)

The swap: I'm not an absolute expert, but I'd say that in linux:
- if there is enough swap space the apps should keep working, with the only issue of slowering the process
- if there isn't enough swap space the system hungs

Am I correct?

**Comment by jenshannoschwalm** [comment]
About your proposal
 - yes i agree about the short time and remaining in doubt
 - yes again about better explaining. Although i would prefer to avoid too technical stuff.

maybe that would mean to open like a checkbox although i fear other users might be complaining they have to click :-)

Swapping used to be as you describe. I am not sure all users have spapspace active, even less for virtual machines or linux booted from sticks or so.

I will think about it but why don't you do it yourself? You have done other prs :-)

**Comment by myriadbeings** [comment]
I am having this issue with an image that isn't particularly large, and I have plenty of processing speed and ram, with no other applications going.  The only difference is that in my case the jpeg or png is not being successfully created.

**Comment by jenshannoschwalm** [comment]
> I am having this issue with an image that isn't particularly large,

1. Please give a note about your system :-) Ram, OS, graphics card? 
2. could you share a log ?
3. maybe even raw and xmp?

Otherwise there is no chance to understand your issue

**Comment by victoryforce** [comment]
> Do you have a better wording/text suggestion?

How do you feel about `output most likely will be OK, but you may want to check this` or something like that instead of current text about the output?
