### ISSUE TITLE
Export size value in cm changes after darktable restart

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#11716]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**

If I set for example 12.34 x 56.78 as export size in cm, it will show 12.35 x 56.79 at the next run of darktable like adding +0.01 .

**To Reproduce**
1. In Export module, set a size in cm.
2. Quit darktable
3. Run darktable and see that value are incremented of 0.01

**Expected behavior**
It is expected that darktable keeps the same value as before.

**Which commit introduced the error**
Current 3.9 build

**Comment by jenshannoschwalm** [comment]
That's just rounding, also related to dpi if i remember correctly

**Comment by Jiyone** [comment]
In this case, refreshing the rounded value live could be better ?

**Comment by jenshannoschwalm** [comment]
> round the dpi value instead

you can't round dots :-)

**Comment by Jiyone** [comment]
okay :neutral_face: so what ?
