### ISSUE TITLE
DJI Mavic Pro noise profile

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#11713]
For noise profiles, please also attach the entire archive with `.pdf` plots.
Link to noise profile for DJI Mavic Pro. 
I had to change maker from Dji to DJI to get darktable to detect the noise profile.
https://drive.google.com/file/d/1xJZms09dhJu2T0MAyeIjygaENmCmp6Et/view?usp=sharing

**Comment by kmilos** [comment]
> I had to change maker from Dji to DJI to get darktable to detect the noise profile.

I guess there is something in the tool that converts to Normal case like we do NIKON->Nikon etc. so probably an exception is needed...

Probably need to add "DJI" to maker list in `data/noiseprofiles.schema` as well, or validation during building will fail.
