### ISSUE TITLE
GUI: still wrong layout for the [new rule] list

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11719]
When selecting [new rule] in the new collection filter module the labels in the pop-up are all centered.

![image](https://user-images.githubusercontent.com/467069/166653516-929e5b42-70bd-41a0-95b2-d30d2725436a.png)

**Comment by TurboGit** [comment]
Same issue for the pop-up when clicking on the rule filter label for non pinned rules.

**Comment by TurboGit** [comment]
The rule labels right, but see the collection menu:

![image](https://user-images.githubusercontent.com/467069/166661108-60ab924b-1594-4187-b2a7-bd9dc35c7c5d.png)

The values are all right-aligned as for all others pop-up.

**Comment by AlicVB** [comment]
imho we have to distinguish 2 types of popups : 
1. the "real" popups (context-menus, preferred presets menu, etc...) which are all *left* align. The popup doesn't overlap the "source" widget.
2. the bauhaus combobox popups. The popup is drawn on top of the source widget so the selected value exactly overlap the source one (not sure to be clear). Their alignment is so dependent of the alignment of the source widget.

If we follow that, we have to change the collection property popup alignment which a combobox (the one in your last msg), as well as the "new rule" one which is a "classic popup". Would that be ok for you ?

**Comment by AlicVB** [comment]
@TurboGit : hope you won't mind if I reopen this issue : 
We still have this to "solve : 
- fix alignment for collect combobox (#10400)
- decide what to do with the "classic" popup when you click to add a new rule...

**Comment by Nilvus** [comment]
I unassign me here.
About what remains to solve:
- I think collections menu should be same as actual rule (this issue so). I really think center way is better than right alignment, except when bauhaus combobox is aligned right with title label inside especially. So, here collections module could be centered (I answer with my memory as I can't open darktable now since 3 days!)
- for second point, I can't answer here. I don't remember what you mean @AlicVB. Maybe a screenshot to help...
That will be hard 2 weeks without my computer...

**Comment by AlicVB** [comment]
@Nilvus : no problem (except for you)...
You already the 3 screenshot in this thread : 
1. for the module collection. This is a combobox popup popup with text aligned on the left. So imho the popup should follow that so the text in the popup exactly superposed the one in the combobox This is #10400
2. for the "property" of a filter in the filtering module. This is a combobox, the popup is aligned like the combobox itself, so all good imho
3. when you click on the "new rule" button in the filter module : here we have a "classic" popup menu that don't superpose anything, so question is : do we want to mimic the combobox popup of the filter property (current) or do we want to align it on the left like all other popup menus

**Comment by Nilvus** [comment]
> @Nilvus : no problem (except for you)... You already the 3 screenshot in this thread :
> 
>     1. for the module collection. This is a combobox popup popup with text aligned on the left. So imho the popup should follow that so the text in the popup exactly superposed the one in the combobox This is [in collections combo swap entries/sections alignment to avoid jump #10400](https://github.com/darktable-org/darktable/pull/10400)

Yes, I see screenshot. For that one, I really think we need to do it same way as rule one, so let aligned on left label sections (files, metadata, etc...) and center filters, except having them on right. I'm not fond by #10400 proposal.

>     2. for the "property" of a filter in the filtering module. This is a combobox, the popup is aligned like the combobox itself (centered), so all good imho

Yes, and this is needed (I tested when working on bauhaus alignment, other possibilities and it was clearly a no-go. Actual state is the good one.

>     3. when you click on the "new rule" button in the filter module : here we have a "classic" popup menu that don't superpose anything, so question is : do we want to mimic the combobox popup of the filter property (current) or do we want to align it on the left like all other popup menus

Hmm, that for this one that a screenshot would help to be sure what I would suggest, especially what we have inside.

**Comment by Nilvus** [comment]
@AlicVB: or maybe for third point, I don't understand which one you talk about. I see 2 screenshots on this issue (3 are posted but 2 are same one). So, for your third point, if you talk about that screenshot:

![166656313-f3d7598e-b938-41c5-ba81-ab1a4cdfc621](https://user-images.githubusercontent.com/45535283/166734692-ff85022b-6dc7-4d78-be78-8ea7bf40e275.png)

I so think it's good as it is. And collections one should have same alignment.

**Comment by AlicVB** [comment]
> Hmm, that for this one that a screenshot would help to be sure what I would suggest, especially what we have inside.

Sorry, I was wrong : the screenshot for this one is the first one in the top of this thread...
- screenshot 1 : popup menu for "new rule" in filtering module
- screenshot 2 : combo popup for rule property in the filtering module
- screenshot 3 : combo popup in the collection module
