### ISSUE TITLE
retouch mask opacity slider jumping around 

### ISSUE THREAD

**Issue by emko** [darktable-org/darktable#11724]
To Reproduce
open a image in darkroom add a retouch module then place a retouch shape 

when you hold down the slider and try to slide around it will jump in different directions and also when your holding it on a value it will continuously show "working.." on the image

also ctrl+scroll does the same slider jumps all over the place as your scroll

Screencast
https://streamable.com/s9rjm6

    darktable version : 3.8.1
    OS : Fedora 36
    Memory : 32gb
    Graphics card : 970
    Graphics driver : Nvidia

    Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes

**Comment by ralfbrown** [comment]
Unable to reproduce with current master, except that when the opacity gets dragged or scrolled below 5% it jumps back up to 5%.

"working" does show continuously for as long as the slider is actively being modified, which makes sense since further changes to the slider get processed immediately after the previous pixpipe run completes.  But just holding down the mouse button while on the slider without moving the mouse does not cause continuous "working".

**Comment by emko** [comment]
https://streamable.com/n2rf5z

tested on master same result

**Comment by pehar1** [comment]
I can reproduce on 3.9.0+1389~gf0039d1b7, Ubuntu 20.04
For me the slider works as expected

- using the mouse scroll wheel (also CRTL scroll wheel and SHIFT scroll wheel)
- left clicking on the slider
- changing the value by right clicking and entering a value with keyboard.

The issue only occurs if one grabs and drags the slider.

**Comment by ralfbrown** [comment]
I now get the continuous "Working" by just keeping the mouse button pressed while on the slider (4.3.0+975).

**Comment by ralfbrown** [comment]
Rechecked, and after #14380, I only get "working" when the opacity slider is actually changed, not from merely holding down the mouse button.  The jump back up to 5% opacity only happens occasionally, but not from 0% - if scrolling down slowly, one step at a time, I will see 7% 6% 5% 5% 4% 3%....  If scrolling faster, I might get down to 3% or 2% then jump to 5% and continue normally to 0%.  But in neither case do I get stuck at 5%.

@emko Do you still have any issues beyond what I described here?

**Comment by emko** [comment]
> Rechecked, and after #14380, I only get "working" when the opacity slider is actually changed, not from merely holding down the mouse button. The jump back up to 5% opacity only happens occasionally, but not from 0% - if scrolling down slowly, one step at a time, I will see 7% 6% 5% 5% 4% 3%.... If scrolling faster, I might get down to 3% or 2% then jump to 5% and continue normally to 0%. But in neither case do I get stuck at 5%.
> 
> @emko Do you still have any issues beyond what I described here?

no  i don't thanks
