### ISSUE TITLE
mac os | gamma shift in the image when exporting

### ISSUE THREAD

**Issue by estaf1001** [darktable-org/darktable#11736]
When I load any image into a program and save such an image in any of the graphic formats, in any other viewer the image looks with stronger contrast when compared to the picture in darktable.

1. Download dmg image of app from https://www.darktable.org/install/
2. Open dmg file and copy darktable app to Application folder.
3. I open the system settings of the operating system and make sure that the monitor profile I created is correct.
4. I don't open the conditional file in darktable yet (for the time being), but in programs such as Adobe Photoshop, Capture One and 3dlut creator. I save the file in tiff format from these programs. I compare the resulting image in the Preview.app program (the program comes out of the box for mac os). When comparing the open image in these different programs, I see no difference. The display is identical in any of its.
5. rm -rf ~/.config/darktable (For the purity of the experiment)
6. open Darktable app
7. I load the same file into darktable and save it as a tiff, without doing any additional manual manipulation of the image.
8. I open the saved image from the program in the same preview program and see that in the preview.app it looks more contrasty. This point is clearly visible in the shadows - they simply fail.

A screen of problem here: https://discuss.pixls.us/t/darktable-on-macos-are-there-bugs-with-icc-profiles/28930/28

* darktable version : 3.8.1
* OS                : MacOS Big Sur 11.6.5
* Memory            :  32 GB ddr3/non ecc.
* Graphics card     :  AMD HD 7970 (Tahiti)
* Graphics driver   :  don't know.
* OpenCL installed  :  yes (Tested under Davinci Resolve)
* OpenCL activated  :  yes (Tested under Davinci Resolve)
* Xorg              :  none 
* Desktop           :  native Finder environment
* GTK+              :  don't know (install from binary one - static one)
* gcc               :  don't know (install from binary one - static one)
* cflags            :  don't know (install from binary one - static one)

**Comment by parafin** [comment]
Can't reproduce.

Does the image look already wrong when imported to darktable, before exporting?

Is the problem reproducible if you choose sRGB as monitor color profile in system settings?

In what format is the input image? Is it JPEG/TIFF or some RAW format? Maybe you could upload somewhere an example image.

**Comment by estaf1001** [comment]
> Can't reproduce.
> 
> Does the image look already wrong when imported to darktable, before exporting?
yes. By the way the same problem!

> Is the problem reproducible if you choose sRGB as monitor color profile in system settings?
yes - the same story.

> In what format is the input image? Is it JPEG/TIFF or some RAW format? Maybe you could upload somewhere an example image.
I had loaded either raw (dng from my canon) or any other file. The situation repeats itself.

<a href="https://ibb.co/SRZZDfd"><img src="https://i.ibb.co/m6PPrNX/86d48da4f8c7f771aa99eee30d278a1956db2116.jpg" alt="86d48da4f8c7f771aa99eee30d278a1956db2116" border="0"></a>

raw one https://drive.google.com/file/d/1-pCyZW96gfU8ttA22XZ2bHbL65TP9VSs/view?usp=sharing

**Comment by kofa73** [comment]
darktable 3.9.0+1228~gcfb6a8cbf on Windows 10, showing DNG vs re-imported TIFF:
![image](https://user-images.githubusercontent.com/3177739/167133925-b2e1762c-0db4-44ec-811f-63034fcd3b3d.png)

The TIFF file was exported as sRGB. Note the patter on the arm/shoulder of the dress.
Exporting at full size does not matter. When scaling down, the 'high-quality resampling' setting does not matter. The setting 'always use LittleCMS2 to apply output profile' does not matter.

I cannot decide if this is the same issue or not, though.

XMP (sorry, crazy settings!) attached as TXT to satisfy GitHub.
[_MG_6068.dng.xmp.txt](https://github.com/darktable-org/darktable/files/8640105/_MG_6068.dng.xmp.txt)

**Comment by parafin** [comment]
Please create a new bug report.

**Comment by kofa73** [comment]
Why is a new report needed? If I understand correctly, @estaf1001 was complaining about the same thing: the _exported_ TIFF is different from the darkroom view:

> 8. I load the same file into darktable and save it as a tiff, without doing any additional manual manipulation of the image.
> 9. I open the saved image from the program in the same preview program and see that in the preview.app it looks more contrasty. 

When he did the same comparison in Adobe Photoshop, Capture One (viewing the raw in those and viewing the corresponding TIFF export in the preview app), there was no difference. @estaf1001 , please confirm if my interpretation is correct.

**Comment by parafin** [comment]
No, this report was about viewing and exporting raw image from darktable, not tiff

**Comment by estaf1001** [comment]
> No, this report was about viewing and exporting raw image from darktable, not tiff

https://github.com/darktable-org/darktable/issues/11736#issue-1227578599
"When I load any image into a program and save such an image in any of the graphic formats, in any other viewer the image looks with stronger contrast when compared to the picture in darktable."

"When I load any image..."

"..any image".

**Comment by parafin** [comment]
read next comments. this is my last reply at this closed bug report, please create a new one with clear reproduction steps. raw and tiff/jpeg are very different cases, choose one specific.

**Comment by estaf1001** [comment]
> read next comments. this is my last reply at this closed bug report, please create a new one with clear reproduction steps. raw and tiff/jpeg are very different cases, choose one specific.

Got it. Okay.
