### ISSUE TITLE
[filtering | crash] darktable with new collection filters crashes on Windows in focal length filter

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#11737]
**Describe the bug/issue**

Platform-dependent (only Windows, not happens with Linux build, not tested on mac OS) crash while trying to use focal length filter from new collection filters module.

**To Reproduce**
1. Build latest master on Windows
2. Open darktable
3. Add new filtering rule that works on focal length
4. Hover your mouse over widget of this new rule
5. darktable will crash immediately without even producing backtrace file

**Expected behavior**

darktable should work as expected without crashing.

**Which commit introduced the error**

Probably this bug existed from the first commits that introduced new collection filters. At least I had the opportunity to check it out on the build 3.9.0+1228 and this new filters feature was not changed too much between merging and commit of that build.

**Platform**
* darktable version : from at least 3.9.0+1228 to current master, 3.9.0+1407
* OS  : Windows 10 21H2 (OS Build 19044.1645)
* OpenCL : should not be relevant as filtering code clearly does not use it (and yes, tested that darktable crashes with --disable-opencl)

* CMAKE_BUILD_TYPE  :  RelWithDebInfo

**Additional context**

The crash is not data dependent as it also appears when used an empty/new config-dir.
I did not use Lua scripts.

**Comment by AlicVB** [comment]
Sadly, I can't test on windows... and as you, I can't reproduce on linux...
Some questions : 
1. does it happen with other filters ?
2. can you confirm that it doesn't happen on linux with the *same* images ?
3. if you launch darktable in english, does it change anything ?

Thanks in advance

**Comment by gi-man** [comment]
I can replicate on windows 11 on English language. I tried ISO, exposure, aperture and aspect ratio. It only crashes on focal lenght.

 3.9.0+1422~gca21d2cce

**Comment by AlicVB** [comment]
So... we need a windows dev here...
tbh, I have no idea of the root cause :(

**Comment by gi-man** [comment]
I've been testing it more. I can add the rule and not get it to crash until the mouse touches the lighter gray box.

This one:
![image](https://user-images.githubusercontent.com/97920861/167197607-17ae0916-a0bb-4802-81d8-d51f46c89ed0.png)

**Comment by victoryforce** [comment]
> So... we need a windows dev here... tbh, I have no idea of the root cause :(

I would not call myself a Windows developer, but I will try to fix this bug.

**Comment by AlicVB** [comment]
At first sight, I would say that the issue may comes from the current value "tooltip" show.
After a "blind" pass in the code, There's maybe an issue in `src/libs/filter/focal_length.c` around line 70 where we are use printf directly without ensuring the locale...
I would put something like : 
```
gchar *locale = strdup(setlocale(LC_ALL, NULL));
  setlocale(LC_NUMERIC, "C");
  gchar *txt = g_strdup_printf("%.0lf", value);
  setlocale(LC_NUMERIC, locale);
```
instead... maybe you can start by testing that (but I doubt that it will fix the issue, as you can reproduce with english language...

one other place to look at can be `src/dtgtk/range.c` around line 190 (it's the routine used to translate the values from text to numeric)
