### ISSUE TITLE
Darkroom view of processed raw image looks different from that of exported image

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#11741]
**Describe the bug/issue**

The exported image, when re-imported to darktable, looks different from what the raw file looked in the darkroom before exporting. Highlights are affected most.

**To Reproduce**
1. Open the raw from https://drive.google.com/file/d/1-pCyZW96gfU8ttA22XZ2bHbL65TP9VSs/view?usp=sharing - applying the attached sidecar (remove the .txt suffix)
2. Make a snapshot
3. Export (I used JPG, but TIFF works the same way)
4. Reimport
5. Compare snapshots -> there is a visible difference in highlights.

[_MG_6068_02.dng.xmp.txt](https://github.com/darktable-org/darktable/files/8644747/_MG_6068_02.dng.xmp.txt)

**Expected behavior**
Reimported file looks (almost) the same as the snapshot created from the processed raw file.

**Screenshots**
![image](https://user-images.githubusercontent.com/3177739/167245571-53210c96-f1a8-4ae7-8c91-e789ae2eb1c3.png)

**Platform**
I used Linux and the indicated darktable version for this post, but had the same result on Windows 10 and the build from https://discuss.pixls.us/t/darktable-winidows-insider-program-5-1/30641

** Additional info**
Scaling algorithms (bicubic vs lanczos3), full size vs scaled-down export, the choice of high-quality resampling on/off (when exporting a scaled-down file) have no effect.

* darktable version : 3.9.0+1427~g41decf1a8
* OS                : `Linux eagle 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 22.04 / Windows 10
* Memory            : 64 GB (Linux) / 16 GB (Windows)
* Graphics card     : NVidia 1060/6GB (Linux) / ??? laptop (Windows)
* Graphics driver   : 470.103 Linux / ??? (Windows)
* OpenCL installed  : yes (Linux), no (Windows)
* OpenCL activated  : yes (Linux) / no (Windows)
* Xorg              : 7.7+23ubuntu2 
* Desktop           : KDE
* GTK+              : 3.24.33-1ubuntu1 
* gcc               : 11.2.0-19ubuntu1
* cflags            : ---
* CMAKE_BUILD_TYPE  : Release

**Comment by m-p-y** [comment]
I cannot reproduce the described behaviour, the snapshot looks to me identical to the reimported TIF export:
![image](https://user-images.githubusercontent.com/3230061/170560420-1b29435b-7d1d-4fe2-8135-8b3bcaee9997.png)

- dt version: 3.9.0+1611~g0086b0c1d
- OS: Arch LInux / 5.16.14
- Graphic: nvidia Quadro M2000M / 510.60.02
- OpenCL: active

**Comment by kofa73** [comment]
Still reproducible here with 3.9.0+1767~g020d1bd6f (Ubuntu 22.04), OpenCL on or off does not matter. Export module reset to defaults, no additional style applied by export. Exported at full size. darktable cache cleared after each export.
I have now tried renaming my darktable config directory to start with a clean config and DB, and the result is still the same.
Exporting to JPG or 32-bit TIFF makes no difference; neither does exporting from darkroom or lighttable. I'm uploading the smallest JPG:
![_MG_6068_02](https://user-images.githubusercontent.com/3177739/174451212-27cec997-c6f6-42e5-94d5-31d5c9e8fd13.jpg)
I'll now test on a Windows laptop I have access to.

**Comment by kofa73** [comment]
Still present (4.1.0+215~gab7e37433):
![image](https://user-images.githubusercontent.com/3177739/185782795-c9dc160a-1281-410e-9657-2baa348cb145.png)
