### ISSUE TITLE
Smart copy-pasting of history stack getting in the way

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#11745]
When copy-pasting editing history from one picture to another, some items are disabled by default based on undisclosed assumptions.

The only time when I'm copy-pasting is between pictures shot in the same setup under the same lighting. In this case, I don't want the app to second-guess my "copy all" instruction. I want it to copy everything including pipeline order.

Unfortunately, it does second-guess it and so I always have to use the "copy some" tool and select all manually modules, which is annoying and makes the "copy all" option ultimately useless.

I propose the global "copy" and "paste" just do what they are asked, without being clever about it.

**Comment by elstoc** [comment]
Or an option in preferences/security: "enable safe copy/paste"

**Comment by ralfbrown** [comment]
I'd go with the preferences option, because the reason `copy` disables some things by default is the number of complaints from users that colors  were weird after pasting to a different camera (raw black/white point and WB coefficients being different).

**Comment by aurelienpierre** [comment]
But why would you copy history stacks between cameras and expect things to automagically work ? That's non-sensical.

**Comment by Nilvus** [comment]
> But why would you copy history stacks between cameras and expect things to automagically work ? That's non-sensical.

I don't know, maybe someone that do that will answer...

**Comment by parafin** [comment]
Things like black and white levels can differ for different ISO settings of the same camera. So copying rawprepare is not safe even when doing it in the scope of one shoot (e.g. if camera is in auto ISO mode). So it’s not that simple.

**Comment by aurelienpierre** [comment]
Ok, then, everything but raw black/white if you want.

**Comment by jenshannoschwalm** [comment]
We also had issues with modules copied from raw to jpgs that just don't work.

I certainly like the current way, it allows you to do what you want with a missing 'tick' as a reminder : are you sure?

**Comment by aurelienpierre** [comment]
> I certainly like the current way, it allows you to do what you want with a missing 'tick' as a reminder : are you sure?

The current way is basically that the "copy all" feature can only be accessed through the "copy some" then "select all" options. Not only does it not do what it says, but it actually defeats the whole purpose of having a one-click "copy all" AND a fine-grained "copy some".

> I'd go with the preferences option, because the reason copy disables some things by default is the number of complaints from users that colors were weird after pasting to a different camera (raw black/white point and WB coefficients being different).

Complaints about a "copy all" feature that actually copies everything are not valid. 

Another preference for this is more bloat.

**Comment by aurelienpierre** [comment]
Also, if copying color calibration but not WB, then the result is wrong whether the WB coeffs are right or wrong for the destination file.

Also, if you have a default preset on WB and copy an history stack in "overwrite" mode where WB doesn't get copied, then what you will get as a result is unpredictable.
