### ISSUE TITLE
Current mast does not build due to latest diffuse&sharpen tooltips

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#11742]
There are clearly residules from #10432 master rebasing not completely done ...

@TurboGit and @quovadit

**Comment by Nilvus** [comment]
Yes, conflict had not been fixed correctly as @kofa73 and me pointed.

**Comment by quovadit** [comment]
I'm very sorry :-(

The quickest solution would be to revert my PR

I try to fix my mistake, but I don't want to mess everything up again, so it won't be finished within the next minutes...

**Comment by TurboGit** [comment]
@quovadit : I have reverted, we all make mistake and I should have been more careful before merging.

**Comment by Nilvus** [comment]
I so close as master could be compiled now.
