### ISSUE TITLE
UI - make some change to the filter for clarity

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11749]
I'd like to raise some minor issues that will be nice to fix for the upcoming 4.0 release.

1. [new sort] - for consistency with [new rules] why not center the items there?
2. I understand that the math signs for and / or / and not where a bit obscure for some people, but the current reading of the history is hard:

![image](https://user-images.githubusercontent.com/467069/167264362-242b14b8-91b3-4bfd-bbc9-fe5b09b064f3.png)

Here the `et` are just part of the sentence and it makes it very hard to see what the actual rule is about.

Solutions?
1. Use the maths characters as it is in the collections module: 
![image](https://user-images.githubusercontent.com/467069/167264411-251dfd0f-3f2e-475d-8225-7a6b434001ef.png)
![image](https://user-images.githubusercontent.com/467069/167264414-a78477a7-fe1e-41d5-91c2-d671cde37578.png)
![image](https://user-images.githubusercontent.com/467069/167264421-a9149a96-6113-423b-bf67-c5b190db2b69.png)
2. make the and / or / and not in bold
3. any better solution....

**Comment by Nilvus** [comment]
Absolutely not 1). Of course, it's short and could help readability, for us, developers and people at ease with maths. But not for all people. That was one of the main reasons to do new filters. See that issue: #9664

2) bold is a good way.

I don't have any other ideas actually and I never use history or old recent collections. So I do not have real ideas if this should remains on the left or centered. But wait for another issue opened today against that work to see what could be updated.

**Comment by AlicVB** [comment]
let's see what we can do with markup...

**Comment by difrkaguilar** [comment]
Maybe not for 4.0 but other release will be nice to have a way to clear filters history too. Or define how many filters history "presets" can be storaged. I see 10 now.

**Comment by victoryforce** [comment]
Maybe bold and uppercase to stand out even more? If it's too much, then uppercase is better, as for me, it's easier to distinguish.

**Comment by AlicVB** [comment]
here is a first draft :
![Capture d’écran_2022-05-07_20-07-12](https://user-images.githubusercontent.com/1818223/167266537-e7a0771d-7838-4ad3-a96d-4a50e6d61541.png)
 what is done : 
- more space around operators
- operators in uppercase and italic (so they *don't* stand out too much
- property names in bold (because this is the main info users may look for, imho)

**Comment by victoryforce** [comment]
It's much better for perception, IMHO. I vote for it.

**Comment by TurboGit** [comment]
@AlicVB : much better and quite readable now.
