### ISSUE TITLE
Canon EOS 20D recognized, but not able to tether 

### ISSUE THREAD

**Issue by Elaniobro** [darktable-org/darktable#11758]
**Describe the bug/issue**
I am able to open the Canon EOS 20D in tether mode, but I am unable to capture any pictures.

**Expected behavior**
While in tether mode, be able to take pictures.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : `edit` 3.8.1 
<img width="136" alt="Screen Shot 2022-05-08 at 3 33 23 PM" src="https://user-images.githubusercontent.com/710847/167312743-8e9b2a68-92a4-41a9-a395-7e8c866f9056.png">

* OS                :  MacOS 11.5.2
* Model Name:	MacBook Air
* Model Identifier:	MacBookAir8,1
* Processor Name:	Dual-Core Intel Core i5
* Processor Speed:	1.6 GHz
* Number of Processors:	1
* Total Number of Cores:	2
* L2 Cache (per Core):	256 KB
* L3 Cache:	4 MB
* Hyper-Threading Technology:	Enabled
* Memory:	8 GB
* System Firmware Version:	1554.140.20.0.0 (iBridge: 18.16.14759.0.1,0)
 

Edit: I updated  the list with proper formatting and added proper  darktable version.

**Comment by Nilvus** [comment]
Could you precise which darktable version you use? Thanks

**Comment by jenshannoschwalm** [comment]
You mentioned Version 3.5, please use at least 3.8,

**Comment by jenshannoschwalm** [comment]
You mentioned Version 3.5, please use at least 3.8,

**Comment by Nilvus** [comment]
> You mentioned Version 3.5, please use at least 3.8,

It's the version provided in bug report template that is mentioned.

**Comment by Elaniobro** [comment]
@jenshannoschwalm & @Nilvus apologies, that line was from the template. I am using 3.8.1
<img width="136" alt="Screen Shot 2022-05-08 at 3 33 23 PM" src="https://user-images.githubusercontent.com/710847/167312718-89645d30-a42c-4286-8330-c4d0d68bc9ee.png">

Is there an error log I may share? If so, where might I find it on a macOS?

**Comment by Nilvus** [comment]
@Elaniobro: I don't use tether so can't help a lot more here. I just the dirty job: filtering!
Just a thing, tether is supported by gphoto2 library. On support page, we can read that tether is supported only on "normal mode" and not "ptp mode" (if I understand correctly the empty line). But to be sure, did you test/try with "normal mode" on your camera and not "ptp mode". See your manual if needed, I don't use Canon cameras. If you never try "normal mode" and if this fix your issue, of course think about closing this issue.
If not, I fear you will have to wait or try elsewhere (pixls.us forum maybe) if nobody else goes here to help you.
