### ISSUE TITLE
Error opening Fuji X-T30 II raw files in darkroom (Darktable 3.8.1)

### ISSUE THREAD

**Issue by alvarezprado** [darktable-org/darktable#11750]
**Describe the bug/issue**

Opening raw files from Fujifilm X-T30 II in darkroom does not work in Darktable 3.8.1. Images can be previewed in lightroom, but when clicking to open them in darkroom, Darktable gives an error (see screenshot below). 

Error captured from executing Darktable in terminal:

```
RawSpeed:Unable to find camera in database: 'FUJIFILM' 'X-T30 II' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (DSCF0139.RAF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 170: Camera 'FUJIFILM' 'X-T30 II', mode '' not supported, and not allowed to guess. Sorry.
```

**To Reproduce**

1. Import raw files from Fuji X-T30 II in Darktable.
2. Click in one image in the lightroom to open it in the darkroom.

**Expected behavior**
Image opens in darkroom.

**Screenshots**
https://imgur.com/a/PdUT60t

**Platform**

* darktable version : 3.8.1-2+b1
* OS                :  Linux, kernel 5.17.0-1-amd64 #1 SMP PREEMPT Debian 5.17.3-1 (2022-04-18) x86_64 GNU/Linux
* Linux - Distro    : Debian testing
* Memory            :  8Gb
* Graphics card     :  Integrated, Intel HD Graphics 520 (Skylake GT2)
* Graphics driver   :  intel-media-va-driver 22.2.1
* OpenCL installed  :  No
* Xorg              :  No
* Desktop           :  None (sway on wayland)
* GTK+              :  GTK3.0

Thank you!

**Comment by Nilvus** [comment]
This camera is unfortunately not supported by now. List of supported cameras is here: https://www.darktable.org/resources/camera-support/

And an existing issue is already opened about that (think about searching before posting): #10755

I so close as it's a duplicate.

**Comment by alvarezprado** [comment]
My bad, I was assuming it was supported because the raw images were already uploaded to RPU and the camera is pretty much the same than the X-T30 (which is supported) in terms of hardware.

My apologies!
