### ISSUE TITLE
selecting images without a color label

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11759]
I can't seem to find a way to select images having no color labels using the new filter widget.

I've tried selecting no labels and switching the n/u icon (it doesn't work when none are selected), and I've tried the same after selecting all labels. Neither seems to work, and it's not initially obvious to me how it's _supposed_ to work. Am I missing something?

It's also a bit strange that by default selecting all star ratings shows all images, while selecting all color labels (usually) shows no images.

**Comment by elstoc** [comment]
It seems it can be resolved by changing from "and" to "and not" in the collection filters module. If the top bar filters are going to be dependent on these combinatory options, they need to be displayed in the top bar in between the pinned filters.

**Comment by AxelG-DE** [comment]
That is exactly what made the filter fail for me yesterday. I selected "not tag Timelapse" plus "and tag Panorama". That moment the filter line obove selection reacted differently and showed wrong results.

IMHO the filter should not react on the collection module at all but being cumulative. Maybe another issue?

**Comment by Nilvus** [comment]
First color labels is not a work related to new filters. It was done previously by a work from @phweyland (I ping him to have his answer on that issue so). See PR that adds that: #10694

> I can't seem to find a way to select images having no color labels using the new filter widget.

I never tested that so just searched and yes not easy.

> It's also a bit strange that by default selecting all star ratings shows all images, while selecting all color labels (usually) shows no images.

For that, probably because on star ratings, we have no stars selected. So all images are shown. That's not the case for color labels. I had ask for grey label color to be changed and I had back a good reason to let it as it is (but can't remember what was that reason).

> It seems it can be resolved by changing from "and" to "and not" in the collection filters module. If the top bar filters are going to be dependent on these combinatory options, they need to be displayed in the top bar in between the pinned filters.

Maybe default need to be changed.

**Comment by AlicVB** [comment]
After a quick test, I confirm. Normally selecting all images with no color labels is "just" a matter of a ctrl-click on the grey icon (or ctrl-click on each color which is the same)... I'll have a look !

for the "selection" I agree that this doesn't work like rating or the other "range" properties, but I would say that this is not the same type of property either... I would even compare that to "text" properties like search or filename, where no value set means "all images".
That said, if someone has a better idea ;)



> It seems it can be resolved by changing from "and" to "and not" in the collection filters module. If the top bar filters are going to be dependent on these combinatory options, they need to be displayed in the top bar in between the pinned filters.

colorlabels filter is special in this case because it has a specific "and/or" for himself, in order to define how each individual color should interact with the others. This is the last icon of the widget.
Of course for our case setting the "main" filter operator or setting the "colorlabel" one is the same because we are speaking to exclude *all* label...

**Comment by elstoc** [comment]
The problem is that the star and color label selections are adjacent to each other on the top bar and having the two work and look different isn't good. I suspect the way to manage this is to 

1. Add another icon for "no label" - perhaps a circle with a cross through it
2. Default so that all labels are selected and the rule is "at least one of the selected color labels".

**Comment by AlicVB** [comment]
> 1. Add another icon for "no label" - perhaps a circle with a cross through it

I fear that this would be confusing with the last grey icon and the "exclude" icon state which already use the cross...

imho what is blocking us here is that we need to be able to do the following, quite common, filters : 
- select all image with red AND blue labels, whatever the other labels
- select all image with red OR blue labels, whatever the other labels

That implies : 
- we need 3 states per colors (whatever, present, not present)
- we need the colorlabels specific operator

Maybe... we can do it this way (disclaimer : I'm not sure it's better) : 
- cycle between the 3 state only by click (whatever -> present -> not present)
- remap ctrl-click to "act on all colors" => that would make the last grey round unnecessary
- add the grey round at first, eventually with a single cross like what we have in the bottom bar ("present" state should be ok to represent, "not present" should be harder, to distinguish with the "whatever")

- The "no color" first icon will allow to have a "select all" initial state and will avoid current specific case on operator for such situation.
- as said, it might be challenging to represent the 3 states for this icon
- more clicks to switch between "whatever" -> "not present" or "present" -> "whatever"
- the above point imply that collection will be recomputed 2 times for this cases

**Comment by elstoc** [comment]
I'm not sure this can all be done in a simple and easy-to-understand way using a single gui widget. It's already fairly confusing as it is.

IMO the better way is to simplify the filter so that it can _only_ be used with OR (select all images that have one or more of the selected labels), with options for each colored label as well as "no label". I think this is probably the most common use case and if someone wants to do something more complex they can do so by combining multiple color label filters with appropriate "and", "or", "and not" combinations. IMO these and/or/andnot options do need to be pinned to the header as well or it will be hard to understand.

**Comment by Nilvus** [comment]
> IMO the better way is to simplify the filter widget so that it can _only_ be used with OR (select all images that have one or more of the selected labels), with options for each colored label as well as "no label". I think this is probably the most common use case and if someone wants to do something more complex they can do so by combining multiple color label filters with appropriate "and", "or", "and not" combinations. IMO these and/or/andnot options do need to be pinned to the header as well or it will be hard to understand.

I completely agree with your proposal. Make it simple for main cases and use condition for other.

**Comment by elstoc** [comment]
The top-level description (unable to select images without a label) is a bug but IMO the desire to get all possible combinations into a single UI widget has resulted in something overcomplex and confusing and this functionality should be simplified.

**Comment by AlicVB** [comment]
@phweyland : I wonder if have not screw something when porting your widget... If you find a minute to look at it ;) TIA

**Comment by phweyland** [comment]
Logically we should have the non labeled images with the "and" + grey cross (all crosses) . I'll look at it.

**Comment by phweyland** [comment]
![image](https://user-images.githubusercontent.com/23012047/168707274-f255a8d3-0905-4322-91fd-830dc891c5bd.png)
Without Red OR without green:
![image](https://user-images.githubusercontent.com/23012047/168707395-03143989-ba41-4309-9b03-ef61fb14c78f.png)
Without Red AND without green:
![image](https://user-images.githubusercontent.com/23012047/168707585-92385adb-d34c-4b56-83de-5d717df870f2.png)
Without any color:
![image](https://user-images.githubusercontent.com/23012047/168707491-7a7b2cba-91b5-4b32-9cdb-91392ca7410f.png)

Seems OK to me... What do I miss ?

**Comment by phweyland** [comment]
I find also the all highlighted ratings by default strange. All ratings as the default state is better: no filter.
All highlighted remains a valid case though. We haavd the same case with the color labels :

**Comment by elstoc** [comment]
> Seems OK to me... What do I miss ?

Agreed. I only found the Ctrl+click functionality by accident. I think my complaint is more general now: that the widget is very complex with functionality hidden behind modifier keys. When combined with the and/or selector I find it virtually impossible to see at-a-glance what it does. It seems my opinion about the over-engineered nature of these widgets is not shared by sufficient people though.

**Comment by ptilopteri** [comment]
please consider reopening

**Comment by elstoc** [comment]
Perhaps better as a new issue around the complexity of the widget but I'm not convincing the people who make the decisions here so I don't know that I see the point.
