### ISSUE TITLE
[FR] more easy to use collection history

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#11754]
Let's try to have a little more constructive discussion ;)

@aurelienpierre has raise an issue with the recent change in collection module about the history, which was before in a separate module and has been integrated inside the collection module.

**Why has it been done :** 
1. with the new filtering module, we have now 3 history : 

- the one in collections
- the one for filters
- the one for sort orders

letting one history in a separate module will just add confusion.

2. except in the case of an unique rule (not date-time), each line is very likely to be way larger than the panel width.

**What is the issue ?**
quoting @aurelienpierre 
> have recent collections always one click away

I understand... really... (even if for my part, I don't consider that as a real issue)

What I can propose is to put the history, like it was previously in the recent collect module, but inside the collection module, under a collapsible section, with a way (right-click ?) to have that in a popup menu too.
That way : 
- history can still be reached in 1 click (remember that collapsible section state is saved)
- we still can hide it for those who want that
- we also still can have the full line shown in a popup
- we are keeping it inside the collection module and so avoid the confusion with other history

... but we are loosing some consistency with filtering module...

I'm ready to do it. should not be too difficult. But I want other opinion before esp. @aurelienpierre, @AxelG-DE  and @elstoc

**Comment by AxelG-DE** [comment]
I have had several inconsistency issues, where clickin or dragging on stars didn't produce the correct outcome. It seems related to the selections I do in collect module, where I filter out tagged pics for Timelapse and panorama...

Actually from how I iteratively do culling/editing, starting at 0* to 2*, then edit, edited pics are 3*, further culling to 4* and 5* (with refined edit), I don't need that ranging functionality to show e.g. 2*-4*.
I'd appreciate to see a dropdown filter for >/>=/=/</<= again, which I can see from a wink of my eye, what I have selected. The stars itself don't need to be dropdown.

...

**Comment by AlicVB** [comment]
@AxelG-DE : PLEASE stay in the discussion ! I have already close the other issue for that very reason.
If you have an issue with stars, no problem. But open a new issue ! the situation is hard enough to handle !

**Comment by elstoc** [comment]
I only use the "recently used collections" module to revert to my previous collection after I've copied or moved an image to another folder and a one-click way to do that would be best for me. However, if the collection didn't change after a copy/move operation I might not have a use for the history functionality at all.

**Comment by TurboGit** [comment]
Just to say thanks @AlicVB for this constructive message. If it was me I would have not been so fast after all the harsh messages received today.

**Comment by aurelienpierre** [comment]
I see no point in this. You still get one step closer to Microsoft Office: hiding stuff under sub-stuff.

**Comment by jenshannoschwalm** [comment]
Just my cents, i have been pretty busy with other stuff so i did not follow the work of @AlicVB while developing it so i was also somewhat surprised when i was "confronted" - first idea "what is this supposed to be"? (So - a newbie for this part of the gui).
At least everything was very intuitive for me, no manual reading, everything was easy to use after a short time.

So, what **is** the real problem? Will most users will be satisfied? I guess yes - it's all in one place. That would be more relevant for me as a rationale pro/con than personal preference.

**Comment by aurelienpierre** [comment]
The real problem is to have :

1. more unnecessary clutter in UI, but I guess now it's too late anyway,
2. frequently-used features hidden further away.

**Comment by AxelG-DE** [comment]
> @AxelG-DE : PLEASE stay in the discussion ! I have already close the other issue for that very reason. If you have an issue with stars, no problem. But open a new issue ! the situation is hard enough to handle !

My apologies. With tired eyes I oversaw, this was merely about history. I just wanted to be constructive, no aggressions, so no need for yelling :-) but I see, mood got further hot, after I went to sleep...

**Comment by aurelienpierre** [comment]
Hiding history in a collapsible section means that you have to expand both the top-level module AND the nested collapsible section. We rarely need both open at the same time, and it takes up too much space. The point of having them separated is to open only one at a time.

**Comment by ralfbrown** [comment]
> I only use the "recently used collections" module to revert to my previous collection after I've copied or moved an image to another folder and a one-click way to do that would be best for me. 

We do have the Ctrl-K shortcut to jump to the second item in the history, i.e. the previous collection.  Hitting Ctrl-K repeatedly will toggle between the two most recent collections.

**Comment by ralfbrown** [comment]
> Hiding history in a collapsible section means that you have to expand both the top-level module AND the nested collapsible section. We rarely need both open at the same time, and it takes up too much space. The point of having them separated is to open only one at a time.

What about having both the selection rules and the history in (separate) collapsible sections?  The collapsed/expanded state does get saved, so you can have (depending on your use case) the rules visible, history visible, or both.

**Comment by AlicVB** [comment]
@aurelienpierre : as said directly to you in french, your last arguments were not obvious to me. I understand now your usecase. Thanks for the clarification !

@ralfbrown : yes that can be a solution... another one can be to have a "set of images" history module, that would include everything : 
- the collection
- the filters
- the sort order

**Comment by Nilvus** [comment]
> @ralfbrown : yes that can be a solution... another one can be to have a "set of images" history module, that would include everything :
> 
>     * the collection
> 
>     * the filters
> 
>     * the sort order

So the "old" recent collections ones, but with all that. Why not. That would make more sense than 3 separate history buttons and will please all people probably. If we do that, I see 2 ways (without different advantages/disadvantages):

1) show collections results by default (so as it was) and then filters and sort order, separated by their titles (using dt_section_label class). The issue I see is that for users who intensively use it, the list could become huge but all visible and accessible in one click. Maybe in that case, we need to limit the number visible by default.

2) show collections results by default and use collapsible sections only for filters and sort order. That will solve the limit of first proposal (the risk to have a quite long list) but for filters and sort order, will need one more click to access them.

I have no opinion on what choice to confirm here. I do not use them, just my 2 cents to advance here. I let people who use history/recent collections complete or propose something else.

**Comment by aurelienpierre** [comment]
>      What about having both the selection rules and the history in (separate) collapsible sections? The collapsed/expanded state does get saved, so you can have (depending on your use case) the rules visible, history visible, or both.

I'm against any collapsible section, fair and square. Stop hiding stuff under sub-stuff, we are not Microsoft.

I spend 10h/day on a computer, I suffer repetitive strain injuries since the age of 23 (the "click disease"), any more click is a pain.

**Comment by TurboGit** [comment]
> I spend 10h/day on a computer, I suffer repetitive strain injuries since the age of 23 (the "click disease"), any more click is a pain.

We are speaking about 1 click one time and then the section will be kept open forever which will then be somehow what we had before. The recent collection lib was closed at start and when unfolded it was kept as-is.

**Comment by jenshannoschwalm** [comment]
Collapsibles are just one way to visualize structuring ideas, data or  concepts. As tabs, chapters...
No evil inherited. And - we collapse/expand modules all the time

**Comment by aurelienpierre** [comment]
> And - we collapse/expand modules all the time

That's not true and certainly not something to look forward to. Also, nested collapsibles inherit twice the padding of top-level modules, so that's even more real estate lost.

**Comment by paperdigits** [comment]
I also find this to be a regression in terms of use:

- for the `Collection Filters` module, please realize that vertical space is extremely premium. This new module adds a lot of vertical height, reducing the usability of other modules in the left hand side.
- selecting stars is really hard to use. how do I select, for instance, 3 and above, etc.
- multiple history buttons, I get what each does, but it is clunky
- the click and drag to select action is not very discoverable 
- how does one pin a module?
- if I remove a pin from the module, it also disappears from the widget at the top of lighttable (?)

**Comment by paperdigits** [comment]
> I agree. would that solution solve this for you ? https://github.com/darktable-org/darktable/issues/11754#issuecomment-1120449210

Not really. I guess I just don't like the UX, and prefer the old way. 

> you"ll see that this situation can't happen... try it ;) and if you manage to do so, that's clearly an issue to fix :)


I mean I am seeing this, and I find it quite strange: 

https://user-images.githubusercontent.com/71795/167988566-104f373c-0ac9-44a1-90e6-83261390b58c.mp4

**Comment by TurboGit** [comment]
@paperdigits : What is strange ? If you pin a filter it is then put on top. That's a feature so you can select the filters you want to get access easily even if the collect filters is collapse. Or maybe I failed to see what is wrong from your small screencast!

**Comment by emko** [comment]
> @paperdigits : What is strange ? If you pin a filter it is then put on top. That's a feature so you can select the filters you want to get access easily even if the collect filters is collapse. Or maybe I failed to see what is wrong from your small screencast!

not sure but for me the pin makes no sense i still don't understand when i click the pin it vanishes and then there is no way to repin? it says ctrl+click to unpin?  i would think clicking the pin would pin it not remove it? 

not sure maybe its just me :disappointed:

**Comment by paperdigits** [comment]
It redundant! Why does it need to be pinned both places? That is such a waste of screen space. And very confusing. Why are they linked? That makes no sense at all.

On May 11, 2022 10:16:12 PM PDT, Pascal Obry ***@***.***> wrote:
***@***.*** : What is strange ? If you pin a filter it is then put on top. That's a feature so you can select the filters you want to get access easily even if the collect filters is collapse. Or maybe I failed to see what is wrong from your small screencast!
