### ISSUE TITLE
Dutch translation update  nl.po.

### ISSUE THREAD

**Issue by stephanh73** [darktable-org/darktable#11779]
Dutch translation update  nl.po.

[nl_10052022.zip](https://github.com/darktable-org/darktable/files/8663060/nl_10052022.zip)

**Comment by TurboGit** [comment]
Integrated, thanks!

**Comment by stephanh73** [comment]
That's quick. Thanks.

Op di 10 mei 2022 om 18:21 schreef Pascal Obry ***@***.***>:
