### ISSUE TITLE
collection filters: how does OR work and can it be controlled?

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11776]
I think the tooltip in the `[and | or | and not]` dropdown (or even the module UI) could perhaps be clearer as I'm not entirely sure how OR is supposed to work in complex combinations. Currently it says "define how this rule should interact with the previous one", which is somewhat ambiguous.

For example if the module has "a and not b or c and d" where do the brackets fall - how does the general user understand how the corresponding set of filtered images is constructed? Is it possible/easy for a user to change how this bracketing works or is there a defined operator precedence? Based on the tooltip the brackets could look like this... `(a and not [b) or (c] and d)` -- I've used a combination of parentheses and square brackets to illustrate the confusion.

IMO the wording in the collections module of `[narrow down search | add more images | exclude images]` made the functionality much clearer, and suggested that each subsequent rule acted on the set selected by all of the previous rules combined.

**Comment by AlicVB** [comment]
> IMO the wording in the collections module of `[narrow down search | add more images | exclude images]` made the functionality much clearer, and suggested that each subsequent rule acted on the set selected by all of the previous rules combined.

That works exactly like collection. So you're right, no bracket anywhere... Technically collection and filter "just" put the constructed "WHERE" clause with the operator "AND"/"OR"/... before.

Main issue here is that we can't really put `[narrow down search | add more images | exclude images]` as the selected text. But what can be done (this will imply to have another sort of widget, but that's not a big issue) is to show "and/or/and not" as the selected text, and to put more information in the popup like `[AND (narrow down search) | OR (add more images) | AND NOT (exclude images)]`
That would be a little like what we have actually in the collection module, but with text instead of mathematical symbols...

A more simple but way less obvious solution can be just to adjust the tooltips

**Comment by elstoc** [comment]
So the way it works is that each rule "combines with the image set selected by all the previous rules" or words to that effect. I'm still not convinced the word OR works. Also AND and AND NOT both (potentially) exclude images and narrow down the search.

**Comment by AlicVB** [comment]
Well, in french ("et" "ou"), I personally don't find that too confusing, but keep in mind that I have a mathematical background and I'm far from specialist in english...

And now the question : how can we enhance that ? currently in collection, we have opted for the mathematical symbols, but that's worse imho, esp. considering the number of bugs and FR related to that specific point... (we have to keep in mind that collection and filters works the same way in that regard and that's good).
If we want to be really clear, I fear that we can't avoid the full sentence... which would require another line :(

For the long term, there's the long waiting request to add the possibility of "brackets" (or "rule grouping" or whatever you call it). @TurboGit and someone else have done some quite interesting mockups in that regard. But that's certainly not a work for now ;)

**Comment by AlicVB** [comment]
the rules are very naïvely concatenated together and the final query looks like : 
`SELECT imgid, filename, ..... FROM images_database WHERE filmroll = xxxx AND rating >= 2 OR colorlabels contains red ....`
(of course that's not the real syntax, but I hope you understand ;))

In fact, we don't need to use the logical word... just word that means something as clear as possible... but stay small enough.
iiuc what you propose would be to replace "and" by "refine", "or" by "add", and to remove "and not", right ?
Visually, that would be : 
```
ADD rating >= 3
REFINE iso <= 400
```
Although I find the "add" quite clear, "refine" sound strange... what about "with only" ? I'll let you decide here, you know my english level ;)

**Comment by elstoc** [comment]
Ok so this does use operator precedence which means that `a and b or c and not d and e` will be treated as `(a and b) or (c and [not d] and e)`, which is different to what I thought when I made those suggestions. I don't know how best to illustrate/explain that well.
