### ISSUE TITLE
ICC intents/Gamut mapping broken at output profile

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#11777]
## Context

![Screenshot_20220510_140018](https://user-images.githubusercontent.com/2779157/167623529-b38648ad-97a1-44de-beb5-68382aefde2b.png)

Out-of-gamut colors typically happen when the target RGB space does not have coordinates in [0; 100] % able to represent a particular color. Typically, this is because the color is requesting a chroma that is too high its luminance. We have 2 cases for out-of-gamut:

1. case 1 occurs when at least one RGB value is > 100%,
2. case 2 occurs when at least one RGB value is < 0%.

There might be a third case where we have at the same time one value > 100% and one < 0%, but I have never seen that happen in practice.

The ICC colorimetric intents define various strategies to deal with that:

* perceptual relies on AtoB/BtoA look-up tables (see https://www.argyllcms.com/doc/iccgamutmapping.html) that contain vendor heuristics dealing with gamut mapping implicitely, and usually compressing the whole range of colors,
* relative colorimetric states that "colors should be clipped to the boundary of the gamut". For the longest time, I thought this implied "chroma-clipped at constant hue", but I actually didn't find anything clearly saying that.

## What is supposed to happen in dt

Little CMS2, when enabled, should take care of the intent and gamut mapping. 

## What really happens in dt

First, we don't define the AtoB/BtoA look-up tables, so the perceptual intent actually falls back to something close to relative colorimetric. 

Good candidate pictures to test this are sunset pictures, because those bright and saturated reds are guaranteed to be out of pretty much any display gamut. If you cycle between perceptual and relative colorimetric in these pictures, you should see a difference. There is none.

Then, the relative colorimetric does not clip at constant hue. Actually, exporting without Little CMS2 enabled or with it yields to the same result, which means both simply clip RGB harshly, in a way that makes saturated red turn to yellow. The reason lies in the gamut shape, here at 90 % lightness:

![sRGB-gamut-lightness-slice-at-90](https://user-images.githubusercontent.com/2779157/167626920-2f02c903-971e-4dbc-b836-dd06f9d0af24.png)

see how the only high-chroma/high-saturation color at 90% is yellow, so anything very bright and very colorful will degrade to yellow if you don't force a constant hue. But forcing a constant hue may desature quite a lot.

## How to test it

This is a test picture exported in Adobe RGB space through filmic v6, which has gamut-mapping at constant hue:

![test-2](https://user-images.githubusercontent.com/2779157/167627331-d19cb3b3-2ab2-4fde-8422-c812b3cce16a.jpg)

Now, this is the same picture exported in sRGB space, again trough filmic v6, which does the gamut-mapping against a smaller space:

![test](https://user-images.githubusercontent.com/2779157/167627482-0099b538-3801-4050-a9e5-41aeb451f8f8.jpg)

Both this exports were made with Little CMS2 disabled. If your display is able to show Adobe RGB (mine covers approximately 92% of Adobe RGB), those images should not look the same but the sRGB one should have highlights desaturated to fit within sRGB, which is smaller than Adobe RGB. 

But if I re-open the Adobe RGB JPEG above, and re-export it to sRGB with Little CMS2, here is what I get:
![test-LCMS2](https://user-images.githubusercontent.com/2779157/167627930-aa761e3c-d469-4681-84d5-b6283b96ea4a.jpg)

No desaturation, but additionaly, we get the infamous rat-piss yellow shift.

## Who is right ?

In a conflict between Little CMS2 and filmic v6 output, we might be tempted to wonder where the error lies. I'm fairly confident in my gamut-mapping code because it does an actual test-conversion to output RGB, and simply checks if the result is outside [0; 1]. Then, @flannelhead and I have designed a chroma-clipping at constant hue and luminance that finds the max chroma available at current hue. The method is simple and straightforward in a way that leaves little room for mistakes.

Then, it is not clear whether the mistake comes from Little CMS2 itself, or from the way dt implements it, as it is customary with third-party libs.

## What to do from there ?

My belief is gamut-mapping is very much a part of tone-mapping if we want to preserve hue through the whole process. My second belief is that any change done to hue should be a deliberate artistic choice and never a by-product of an image transform, because hues hold meaning (when your skin suddenly turns yellow, you rush to your doctor for liver disease; when your skin turns red, it's time to start drinking water).

So I don't think it's worth the trouble to try and fix what happens at output color profile, also people may be happy with colourful sunsets, even if that implies messed-up hue. But that's probably something we want to be clear about toward users.

**Comment by Jiyone** [comment]
I have a 110% AdobeRGB monitor and yes the sRGB picture looks a lot desaturated in HL and the last picture looks yellow in HL.

**Comment by xfh** [comment]
Reading https://github.com/mm2/Little-CMS/issues/221#issuecomment-646492821 gives some insights: it seems to depend on the profile that is used for the conversion. Maybe worth to experiment setting the output profile to `sRGB v4 Preference`.

**Comment by aurelienpierre** [comment]
@xfh much useful, thanks !

I will make a dt.org blog post about that.

**Comment by kofa73** [comment]
A comparison: let me know if I screwed up. If I didn't, then it seems intents and v2 vs v4 don't make any difference at all. There is a difference between LCMS vs Argyll (or darktable); but in general, we get dumb clipping at > 100% and < 0%.
https://discuss.pixls.us/t/colour-management-intents/31812
