### ISSUE TITLE
Windows 7 unhandled exception up on starting

### ISSUE THREAD

**Issue by TwiggyWan** [darktable-org/darktable#11783]
**Introduction**

---------------------------------------------------------------
Hello.

**Did you buy darktable from an application store ?**
No, got it from https://github.com/darktable-org/darktable/releases/download/release-3.8.1/darktable-3.8.1-win64.exe

**Describe the bug/issue**
Program does not start.

**To Reproduce**
Install darktable 3.8.1 from https://github.com/darktable-org/darktable/releases/download/release-3.8.1/darktable-3.8.1-win64.exe
on latest windows 7 with patches

**Expected behavior**
Program starts

**Screenshots**

![darktable_pKzWEUnQvn](https://user-images.githubusercontent.com/5596799/167733016-7e7b9ccf-7723-4c78-933b-829884196091.png)
![mmc_IzNq1f6OPj](https://user-images.githubusercontent.com/5596799/167734392-5e0e082e-5367-4422-9c04-1f56184d3772.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable-3.8.1-win64.exe
* OS                :  Windows 7 ultimate SP1 x64
* Memory            : 16 GB
* Graphics card     : nvidia GTX 1060
* Graphics driver   :  nvidia 472.12
* OpenCL installed  :  yes, see screenshot
* OpenCL activated  :  I don't know how to check

**Additional context**
backtrace:  
[darktable_bt_0DY3L1.txt](https://github.com/darktable-org/darktable/files/8665425/darktable_bt_0DY3L1.txt)

I do not know if windows 7 is supported or not.
I read from https://github.com/darktable-org/darktable/releases?expanded=true&page=1&q=windows and it's not mentioned.
Furthermore installer did not complain, if my OS is not supported, I'd expect an error message immediately.

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 yes with 3.8.0
with 2.4.4, program does not start and I do not even have the window 'unhandled exception' popping.

 - Do you use lua scripts?
No

**Comment by gi-man** [comment]
I dont think anyone test for windows 7 builds. I'm afraid that you are on your own with a OS that is that old. You can try to build it in your system via MSYS2. OR maybe dual boot with a linux OS.

**Comment by wpferguson** [comment]
Actually I build the weekly snapshots and the releases on windows 7 to maintain compatibility with windows 7.  @TwiggyWan can you try the windows insider build from this post, https://discuss.pixls.us/t/darktable-windows-insider-program-5-8/30747

**Comment by parafin** [comment]
Seems like an issue with Intel OpenCL drivers. So either remove them or disable OpenCL in darktable with --disable-opencl command line option.

**Comment by TwiggyWan** [comment]
Hello @wpferguson , I tried your build out of the box and got following bt : 
[darktable_bt_94FLM1.txt](https://github.com/darktable-org/darktable/files/8701078/darktable_bt_94FLM1.txt)


@parafin : using --disable-opencl did the trick. It's still a mystery how to enable/disable openCL through nvidia control panel so I'll leave it at that.

Thank you

**Comment by Nilvus** [comment]
Thanks @TwiggyWan. That should help people with same issue.

**Comment by TwiggyWan** [comment]
>Well, it’s Intel OpenCL drivers, so NVIDIA has nothing to do with that. 

I thought, because OpenCL.dll showed in the display driver files, that it had to do with the display driver.

>You probably can find that Intel package to uninstall in >usual Windows place in control panel.

Yep, it's there alright. Probably some game had installed that for me.

>As for disabling OpenCL after a crash - it is an interesting idea, but not very straightforward to implement and hides the real problem in other software.

[The documentation says](https://docs.darktable.org/usermanual/3.8/en/special-topics/opencl/activate-opencl/) darktable will detect if openCL is there and attempt to use it if so. But in the case of several reported openCL bugs, there is something going wrong with that.

Do you have a test program that I could run to make use of intel OpenCL, and see if the issue lies in the openCL driver or in the way darktable handles it?
