### ISSUE TITLE
Provide deb packages on OBS for Ubuntu 22.04

### ISSUE THREAD

**Issue by julian-alarcon** [darktable-org/darktable#11780]
**Describe the solution you'd like**
Provide Packages for Ubuntu 22.04 as it's a LTS release and is already in Production
https://download.opensuse.org/repositories/graphics:/darktable/
https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

**Alternatives**
For now, I'm using packages for 21.10, but this is not a good recommendation.

**Additional context**

https://discuss.pixls.us/t/darktable-obs-build-on-ubuntu-22-04/30528

**Comment by paperdigits** [comment]
The darktable project does not maintain the OBS repo. It is maintained by the community and updated when the community has time to do so. It seems like its updated when darktable has an update, not so much when a distro is updated.

The latest stable is also in the 22.04 repo, so you can install from there.
