### ISSUE TITLE
manual vs. code inconsistency: raw denoise in scene-referred workflow?

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/darktable#11782]
**Introduction**
There is an inconsistency between the 3.81 manual [scene-referred module order] and actual/code. 

**Describe the bug/issue**
The manual includes [raw denoise] but it is not available when I select [workflow: scene-referred].

**To Reproduce**
1. See 3.8.1 manual which contains number (7 raw denoise) [https://docs.darktable.org/usermanual/3.8/en/special-topics/module-order/#scene-referred-module-order]
2. Select (workflow: scene-referred)
3. Check list of available modules and (raw denoise) is not included.

**Expected behavior**
I assume the code is correct and the manual needs to be updated, but not sure? [raw denoise] is not described as deprecated or discouraged for scene-referred. I’m brand new to dt, so I'll defer to someone with more background, I'm not sure which is intended.

**Screenshots**

**Screencast**

**Which commit introduced the error**

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.1
* OS                : OSx
* Linux - Distro    : 
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by paperdigits** [comment]
> Check list of available modules and (raw denoise) is not included.

Can you clarify this? I think maybe the module is just missing from that particular group of modules. 

I also think most users are using Denoise Profiled rather than Raw Denoise.

**Comment by TiredOfGuessing** [comment]
Yes I forgot the module is still available if I choose (modules: all) it is just not in the collection of (modules: scene-referred).

**Comment by ptilopteri** [comment]
you can make your own "group" of modules and place it there.

**Comment by aurelienpierre** [comment]
The presets of module dispositions include only the most useful modules to provide a minimal set of tools.

Raw denoise belongs to the scene-referred **part** of the pipeline, regardless of the workflow used. However, it has many shortcomings that got it out of the module dispositions presets.
