### ISSUE TITLE
Noise profiles for OM System OM-1 camera

### ISSUE THREAD

**Issue by sarunasb** [darktable-org/darktable#11791]
Please add noise profiles for OM System OM-1 camera (attached).

[darktable-noiseprofile-20220407.tar.gz](https://github.com/darktable-org/darktable/files/8681551/darktable-noiseprofile-20220407.tar.gz)

**Comment by kmilos** [comment]
Caveat: do not merge until rawspeed support is merged.

**Comment by algreen05** [comment]
What can we do to get OM-1 RAW and Noise profiles added?

**Comment by sarunasb** [comment]
Just get the darn thing merged, please...

**Comment by kmilos** [comment]
> Just get the darn thing merged, please...

Again: should not be merged until base support is sorted out first.

**Comment by TurboGit** [comment]
Will not be in 4.0.1, re-scheduled for 4.2.

**Comment by sarunasb** [comment]
Having this in 4.2 would be highly appreciated!

Thank you!

**Comment by TurboGit** [comment]
@kmilos : I lost track of how to list supported cameras in rawspeed! Do you have a script to extract the list? TIA.

**Comment by victoryforce** [comment]
@TurboGit The list of supported cameras is created by the tools/check_camera_support script.

You should call it something like this:
./tools/check_camera_support --verbose --matrix _~/RPU/_

(where "~/RPU/" is the root of the local copy of the collection of raw files from  raw.pixls.us)

**Comment by kmilos** [comment]
While we're on the subject, it would good to add a "caveat emptor" to the relnotes that these compression modes are not currently supported:

Fujifilm "non-lossless"/lossy
Nikon HE
Sony lossless

**Comment by TurboGit** [comment]
> While we're on the subject, it would good to add a "caveat emptor" to the relnotes that these compression modes are not currently supported:

Added.

**Comment by TurboGit** [comment]
> ./tools/check_camera_support --verbose --matrix _~/RPU/_
> 
> (where "~/RPU/" is the root of the local copy of the collection of raw files from raw.pixls.us)

Noted, thanks!

**Comment by TurboGit** [comment]
> ./tools/check_camera_support --verbose --matrix _~/RPU/_

I have rsync the collection of RAW and got this:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/usr/lib/ruby/3.0.0/json/common.rb:216:in `parse': 809: unexpected token at '' (JSON::ParserError)
        from /usr/lib/ruby/3.0.0/json/common.rb:216:in `parse'
        from /home/pascal/dev/git/darktable/tools/check_camera_support:158:in `process_files'
        from /home/pascal/dev/git/darktable/tools/check_camera_support:25:in `initialize'
        from /home/pascal/dev/git/darktable/tools/check_camera_support:350:in `new'
        from /home/pascal/dev/git/darktable/tools/check_camera_support:350:in `<main>'
```

Looks like the script is expecting a Git repository? I did that as document in the Web site:

`$ rsync -avL rsync://raw.pixls.us/data/ raw-pixls-us-data/`

Any idea?

**Comment by victoryforce** [comment]
> Looks like the script is expecting a Git repository?

Yes. I don't write in ruby, but it's clear from the script's source code that it calls git commands. I ran this script from the root of the darktable repository

**Comment by sarunasb** [comment]
Is this still on track for 4.2?

Would you like me to make a PR with data/noiseprofiles.json instead?

**Comment by TurboGit** [comment]
Have you checked that the support is now in rawspeed?

**Comment by kmilos** [comment]
Unfortunately not: https://github.com/darktable-org/rawspeed/pull/406#issuecomment-1323641683

**Comment by Nilvus** [comment]
@rawfiner: rawspeed support just added few hours ago. So ready to go on master when you have time.
I remove milestone, not sure if this will be for 4.2.1 or 4.4

**Comment by rawfiner** [comment]
@kmilos do the change in rawspeed require to recompute the noise profile?
If not, I'll do the PR, the noise profile curves look perfect.

**Comment by rawfiner** [comment]
Perfect thanks!

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/commit/928115e76f6d9864762dd606696e414d27c22524
