### ISSUE TITLE
Lumix G100/G100 is not supported in the lens correction module

### ISSUE THREAD

**Issue by kadykov** [darktable-org/darktable#11798]
**Describe the bug/issue**

The base support for Lumix G100/G110 was added in Darktable 3.6.0, but there is no dedicated profile in the lens correction module.

**To Reproduce**

1. Import a raw file from Lumix G100/G110.
2. Switch to darkroom mode.
3. Try to apply lens correction.

**Expected behavior**

The lens correction module finds the correct profile and applies all the corrections.

**Platform**

* darktable version : 3.8.1
* OS                : Win10 x64 Version 10.0.19043.1706

**Comment by MStraeten** [comment]
for lens correction definitions check https://github.com/lensfun/lensfun

**Comment by kadykov** [comment]
> for lens correction definitions check https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ and https://github.com/lensfun/lensfun

Thank you for your reply and the links.
But the problem is that the camera profile is missing, not a lens profile.
All supported lenses are successfully recognized by darktable and the lens correction module.

The EXIF information is also correctly recognized as:
* maker: Panasonic
* model: DC-G100

**Comment by MStraeten** [comment]
what exactly is the issue? is the camera not recognized in lens correction module?  
if the exif information is correctly recognized, then it's all about a matching dataset in lensfun calibration data containing camera as well as lens correction parameters.
If the camera is missing there, you can add it in your local lensfun database but don’t forget to report that at lensfun so it get's included

**Comment by PeterWem** [comment]
You will need to open an issue at Lensfun, but before you do that you will need to find out the full name of the camera model. 
Easiest is if you just upload a raw sample here and I can take a look.

**Comment by kmilos** [comment]
Panasonic DC-G100 samples are already present on [RPU](https://raw.pixls.us/), and indeed not included in the lensfun data, so this is not a dt/rawspeed issue.

**Comment by kadykov** [comment]
Thank you all for your help. I have made a pull request to lensfun
