### ISSUE TITLE
Olympus OM-D E-10 Mk IIIs

### ISSUE THREAD

**Issue by laptou** [darktable-org/darktable#11803]
I have the Olympus OM-D E-10 Mk IIIs, and the ORF files that it produces are apparently not supported in darktable. However, this camera is identical to the Olympus OM-D E-10 Mk III except for that it has a silent shutter mode, and a sample is already available on raw.pixls.us, so I suspect that it might be trivial to add support. Is there any way that I can do it myself?

**Comment by kmilos** [comment]
> Is there any way that I can do it myself?

You can edit your cameras.xml as in the linked PR.

You might need to remove any existing xmp sidecars, or if you run into funny behaviour, even start w/ a clean dt database/configuration folder...

**Comment by sauber-oly** [comment]
I have same problem.
I try to add to /usr/share/darktable/rawspeed/cameras.xml   </Camera>
        <Camera make="OLYMPUS CORPORATION" model="E-M10 Mark IIIs">
                <ID make="Olympus" model="E-M10 Mark IIIs">Olympus E-M10 Mark IIIs</ID>
                <Crop x="0" y="0" width="0" height="0"/>
                <Sensor black="254" white="4000"/>
                <ColorMatrices>
                        <ColorMatrix planes="3">
                                <ColorMatrixRow plane="0">8380 -2630 -639</ColorMatrixRow>
                                <ColorMatrixRow plane="1">-2887 10725 2496</ColorMatrixRow>
                                <ColorMatrixRow plane="2">-627 1427 5438</ColorMatrixRow>
                        </ColorMatrix>
                </ColorMatrices>
        </Camera>
but i received following error: RawSpeed:Unable to find camera in database: 'OLYMPUS CORPORATION' 'E-M10MarkIIIS' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (P8160660.ORF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 170: Camera 'OLYMPUS CORPORATION' 'E-M10MarkIIIS', mode '' not supported, and not allowed to guess. Sorry.
[temperature] failed to read camera white balance information from `P8160660.ORF'!
[temperature] `OLYMPUS CORPORATION E-M10MarkIIIS' color matrix not found for image
[temperature] failed to read camera white balance information from `P8160660.ORF'!
[temperature] failed to read camera white balance information from `P8160660.ORF'!
[colorin] could not find requested profile `Standard matrix'!

**Comment by kmilos** [comment]
@dterrahe This was merged for 4.2 and can be closed.
