### ISSUE TITLE
Olympus PEN EP-7 ORF format

### ISSUE THREAD

**Issue by ddiazpinto** [darktable-org/darktable#11810]
I just submitted a sample of the resulting ORF file format of Olympus Pen EP-7 in https://raw.pixls.us/.

Thank you!

**Comment by LebedevRI** [comment]
Looks like the same didn't go through, perhaps it had people in it?
Please contribute another one!

**Comment by LebedevRI** [comment]
Actually, is this `Olympus E-P7`? There is a sample for that.
