### ISSUE TITLE
openjpg deprecates bpp field

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#11812]
`openjpg2` has deprecated the field `bpp` of `opj_image_cmptparm_t` in version 2.5.0. Darktable's build fails due to the deprecation warning when compiling against that version.

See https://github.com/uclouvain/openjpeg/pull/1383 for details.

**Comment by kmilos** [comment]
Thanks. So  much for the "No API/ABI break since..."

**Comment by parafin** [comment]
To be fair declaring smth obsolete is not yet an API break IMHO;) It's just that darktable treats warnings as errors.
