### ISSUE TITLE
collect: datetime tree not correctly displayed

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#11827]
**Describe the bug/issue**
![image](https://user-images.githubusercontent.com/23012047/168910583-5cff1a27-407d-45b4-ae76-bec6fb583564.png)

**Expected behavior**

The third line should be split.

**Platform**

* darktable version : unknown version (current master. Any tip to recover this number ?)
* OS                : debian sid

**Comment by AlicVB** [comment]
Confirmed. I'll have a look !

**Comment by phweyland** [comment]
The issue doesn't appear on 3.8.x
It's a regression due to the move the GTimeSpan datetime.

**Comment by phweyland** [comment]
I'll fix it.
