### ISSUE TITLE
Darktable does not find openjpeg.h on arch

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#11825]
I just tried compiling dt git again on my arch box and it seems darktable does not find usr/include/openjpeg-2.5/openjpeg.h even though cmake seems to find openjpeg which leads to a failure in compilation. This happens for a clean build as well.

**Comment by flannelhead** [comment]
I encountered that after the recent `openjpeg2` package update on Arch. It was resolved when I removed the `build` folder entirely and ran `build.sh` again.

**Comment by piratenpanda** [comment]
Thanks, will try that later
