### ISSUE TITLE
move wb_presets to an external json file

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11831]
The wb_presets.c is growing above a reasonable size (~ 1Mb) at this stage. I propose to move all the definitions into an external JSON file. It will also allow easier experiment of new values.

**Comment by kmilos** [comment]
Would also be good to [extract out and share the make/model schema](https://json-schema.org/understanding-json-schema/structuring.html#ref) w/ noiseprofiles...

**Comment by TurboGit** [comment]
I don't how to handle schema in JSON but this seems indeed a good point.

**Comment by aurelienpierre** [comment]
Then add another lib to extract info from the JSON ?

**Comment by TurboGit** [comment]
No, no new lib. The current wb_presets.c will remain but the data will be external and loaded once at startup.

**Comment by kmilos** [comment]
> Then add another lib to extract info from the JSON ?

We already keep and parse noise profiles from JSON, so no new lib.

**Comment by TurboGit** [comment]
This is done, so closing.
