### ISSUE TITLE
Ubuntu 20.04 LTS removed from binaries repo

### ISSUE THREAD

**Issue by sgofferj** [darktable-org/darktable#11839]
Ubuntu 20.04 has been removed from the binaries repo, however, it's officially supported (by Canonical at least) until 2025. 22.04.1 is not out yet, so there is no stable supported upgrade path to 22.04 yet.
Please kindly provide the binary packages for 20.04 until at least 22.04.1 is out, or better until EOS/EOL of 20.04.

**Comment by aurelienpierre** [comment]
We don't control repositories.

**Comment by sgofferj** [comment]
The OBS Repo is listed on the dark table.org website, so it appears to be the official source for binaries. The website also lists Ubuntu 20.04 als available. Please clarify.

**Comment by parafin** [comment]
We also list some youtube channels there too, so what?:) I suspect OBS repo has its own bugtracker or some other way to get into contact with maintainer. This is not the place. If you ask to amend information on the website, then again this is not the place, instead create an issue here: https://github.com/darktable-org/dtorg/issues
