### ISSUE TITLE
Export as pdf produces only white page

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#11846]
**Did you buy darktable from an application store ?**
No

Apparently, exporting as pdf doesn't work :thinking:
This produce a pdf file with the same number of pages as selected picture number but they are all white and contains no picture.
I don't know if it needs additional lib for that.
I have tried many settings and it's always the same.

**How to reproduce**
- In Lightable, select pictures and select PDF format in Export module
- Click export.
- Open the resulting PDF and see

Darktable version : current 3.9 
Os : Ubuntu 20.04

**Comment by Jiyone** [comment]
@gi-man updated

**Comment by pehar1** [comment]
3.9.0+1551~g79adc8034
Ubuntu 20.04
OpenCL enabled/disabled : no difference
Three 24 MP images selected in lighttable
Export parameters as shown in screenshot

![export-pdf](https://user-images.githubusercontent.com/104291381/169463470-3fe2dca9-575d-495a-bb4c-a8cdaf93696a.png)

Not able to reproduce, all (three) images exported into one pdf file as expected, one image per page. Please provide as much information as possible (issue template!). How many images did you try to export? Any error messages if you start darktable from commandline in debug mode?

**Comment by Jiyone** [comment]
> How many images did you try to export?

Any number, from 1 to n.

>  Any error messages if you start darktable from commandline in debug mode?

No error

Here is an example of what I get :
[_0011.pdf](https://github.com/darktable-org/darktable/files/8740580/_0011.pdf)

**Comment by pehar1** [comment]
Your pdf contains the empty boxes where your images should be shown (one box per page). What type of images did you try to export? Did you try with another image type? Can you work with this images in darkroom? Is it possible to export them if you processed them in darkroom?
If you don't supply information what exactly you have done (step-by-step instruction, possibly providing an example image file), it is impossible to help! **Please use the issue template and supply as much information as possible !!!** If no one is able to reproduce, no one will help.

**Comment by Jiyone** [comment]
I don't know what I can tell more than "any picture I export to pdf does this". 
**Any.**
jpg, NEF, CR2 ... edited or not, just any ...
They export well in other format.

**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**

Exporting picture to pdf produce only white page.


**To Reproduce**

-In Lightable, select pictures and select PDF format in Export module
-Click export.
-Open the resulting PDF and see

**Expected behavior**

PDF should contain my picture.


**Screenshots**
![Capture d’écran de 2022-05-21 13-28-50](https://user-images.githubusercontent.com/75432524/169649735-69292930-64fb-49bc-bead-b3d1fa40016d.png)

**Which commit introduced the error**
I don't know.

**Platform**

* darktable version : 3.9 last release
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04
* Memory            :  16Gb
* Graphics card     : Radeon RX 580
* Graphics driver   : amdgpu
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : I need to find out those one
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if : [0001.CR2.txt](https://github.com/darktable-org/darktable/files/8747511/0001.CR2.txt)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? no

**Comment by ptilopteri** [comment]
I also get no visible photo in an exported pdf, 
a4b2766f
openSUSE Tumbleweed
nvidia GTS 450

**Comment by ptilopteri** [comment]
example:  http://wahoo.no-ip.org/~paka/220517_212649_dsd_3877.pdf

**Comment by pehar1** [comment]
@Jiyone, I picked up your export settings from the screenshot. One point is noticable: you have set an output ICC profile
_**profile -> sRGB2014**_
AFAIK this profile is not integral part of the dt distribution, so I can not test with this profile (not available from the pulldown). Are you able to run a test with _sRGB (web-safe)_ or _Adobe RGB (compatible)_ instead of _sRGB2014_.
I exported with your set of parameters and the mentioned output profiles (**not** _sRGB2014_) without any problem. I'm still not able to reproduce the issue.

**Comment by Jiyone** [comment]
It does that with any profile too.
Is dt using a library to export to pdf ?

**Comment by TurboGit** [comment]
> It does that with any profile too. Is dt using a library to export to pdf ?

No, it is using a simple hand coded PDF writer.

**Comment by aurelienpierre** [comment]
Reproduced here. Also, if you try to export with compression set to "uncompressed", dt crashes without backtrace.

**Comment by aurelienpierre** [comment]
It works if you export in 16 bits.

**Comment by aurelienpierre** [comment]
The culprit is 534e066d53fc9c3737667bfd11d052720aa8c6e4. Reverting it solves the white PDF problem and the crash in uncompressed mode.

**Comment by TurboGit** [comment]
@dtorop : Do you have an idea about this ? Was the issue critical on CUPS side ? You said a "warning", if there is no more than this we should certainly revert this for the 4.0 release. Of course a better fix would be great, but so close from the release maybe reverting to a "safe" code that has been there for long time is maybe the best choice. Please, let me know. TIA.

**Comment by TurboGit** [comment]
@dtorop : Thanks a lot, so I'll revert only at the very last time if no proper fix is found.

**Comment by dtorop** [comment]
Strange results when testing: The first time I export a PDF with the defaults (8-bit deflate), the image stream is very brief, resulting in a blank image. For example:

```
stream
x\0\0\0\0
endstream
```

If I switch to 16-bit (keeping deflate), I get good output. The same upon then switching to 16-bit and uncompressed.

And then, switching back to 8-bit and deflate produces a correct PDF.

If I initially set export parameters to an 8-bit uncompressed PDF, darktable crashes. Or if I export an 8-bit deflate PDF, then switch to 8-bit uncompressed, then I also see a crash.

One difference between the export and the print code is that export (unlike print) calls `dt_pdf_add_icc_from_data()`. Perhaps this is a clue?

I'll keep looking...
