### ISSUE TITLE
Compilation fail : rawprepare.c:417:11: error: ‘d’ is predetermined ‘shared’ for ‘shared’ shared(d) schedule(static)

### ISSUE THREAD

**Issue by pierre04** [darktable-org/darktable#11856]
**Describe the bug/issue**

Buil stops with the following error : In file included from /home/pierre/darktable/build/lib/darktable/plugins/introspection_rawprepare.c:55:
/home/pierre/darktable/src/iop/rawprepare.c: In function ‘process’:
/home/pierre/darktable/src/iop/rawprepare.c:417:11: error: ‘d’ is predetermined ‘shared’ for ‘shared’
     shared(d) schedule(static)

**To Reproduce**

Follow instruction on the developper's wiki to compile Darktable.
./build.sh  
build stops at 73% with an error

**Expected behavior**

Compilation success.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.1
* OS                :    4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
* Linux - Distro    : Debian 10 (oldstable)
* Memory            :  32 Go
* Graphics card     : 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
(Main) +  01:00.0 VGA compatible controller: NVIDIA Corporation GK104 [GeForce GTX 770] (rev a1)
(openCL only, no screen plugged)
* Graphics driver   : kernel for Intel and Nvidia 418.211.00-1 
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              :  7.7+19
* Desktop           : Gnome 5.5.1-2
* GTK+              :  3.24.5
* gcc               :  8.3.0-6
* cflags            :  ?
* 
* CMAKE_BUILD_TYPE  :  ?

[build.log](https://github.com/darktable-org/darktable/files/8743616/build.log)

**Comment by ralfbrown** [comment]
That's a difference between OpenMP in GCC 7/8 and newer versions (also clang).  The declaration needs to use `dt_omp_sharedconst` instead of `shared`.

**Comment by pierre04** [comment]
Thank you for your answer. 
I assume that I have to wait for the patch to be incorporated into the stable branch ? (No hurry, I am using flatpak for now, but OpenCL is not reliable, that what I wanted to compile myself).
