### ISSUE TITLE
double click on new color labels filters do not reset 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#11854]
When double clicking on the color labels one expect the filter to be reset as it is the case for stars. But somehow this got broken recently and does not work on my side.

**Comment by AlicVB** [comment]
afaict that was not the case in previous versions either... But that would be consistent with how the other dt widgets works...
@phweyland : any thoughts ? (I can do it if you want)

**Comment by TurboGit** [comment]
@phweyland : I can have a look if you prefer, there is less review actually, so I can share the load.
