### ISSUE TITLE
Repository '~/xUbuntu20.04 Release' no longer has a Release file.

### ISSUE THREAD

**Issue by saxyomega90125** [darktable-org/darktable#11851]
**Did you buy darktable from an application store ?**
No. Manually installed via repository as specified on the website, using apt.

**Describe the bug/issue**
Upon running 'sudo apt update', I receive the following error lines regarding Darktable:
`Ign:6 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  InRelease
Err:7 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  Release
  404  Not Found [IP: 195.135.221.134 80]
Reading package lists... Done
E: The repository 'http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
apt update then aborts at that point.

**To Reproduce**
Install darktable via repository, run <apt update>.

**Expected behavior**
apt update completes... um... as expected?

**Platform**
* darktable version : 3.8.1
* OS                : Linux - Kubuntu 20.04
* CPU            : AMD 5600X @ stock clocks
* Memory            : 4x8GB Crucial Ballistix 3600 16-18-18-38 @ DOCP
* Graphics card     : NVIDIA 3070 FE @ stock clocks
* Graphics driver   : 470.103.01
* OpenCL installed  : idk
* OpenCL activated  : idk
* Xorg              : Server version 11.20 or server vendor version 1.20.13
* Desktop           : KDE Plasma
No idea on the rest of those points

**Additional info**
This has been occurring since yesterday. darktable has been working fine otherwise on this system for over a year and a half.

**Comment by ptilopteri** [comment]
the dev's here and the project does not package dt nor provide 
packages for install on different systems.

you need to contact the package maintainer for your version of linux.

**Comment by saxyomega90125** [comment]
Let me see if I am understanding this correctly. The OBS packages and installation instructions, which are linked to at [https://www.darktable.org/install/](https://www.darktable.org/install/) and listed as a recommended method of installation on Ubuntu and other systems, are not supported in any way by the developers of darktable?
