### ISSUE TITLE
Impossible to scroll the left side panel

### ISSUE THREAD

**Issue by juliohomus** [darktable-org/darktable#11868]
It seems impossible to scroll the right side panel as it is possible with the right side, at my current resolution (1920x1080) the bottom of the Export tab is hidden and the only way to see it all is by hiding the bottom panel.

**To Reproduce**
1. Open any image
2. Open Export tab with the bottom panel active 

**Expected behavior**
To be able to scroll this left side panel

**Screenshots**
![Captura de tela de 2022-05-21 20-26-57](https://user-images.githubusercontent.com/87508905/169672133-bea60b6c-edbf-4f51-a7e2-c95d25aa1c99.png)
![Captura de tela de 2022-05-21 20-27-15](https://user-images.githubusercontent.com/87508905/169672136-33388623-025b-4e7d-b2a2-a44d28065dde.png)

**Platform**
* darktable version : 3.8.1
* Linux - Distro    : vanilla Ubuntu 22.04 running on X.org
* Downloaded from snap store

**Comment by ptilopteri** [comment]
either place the cursor over the left scroll bar or 
hold <ctrl><alt> and use the scroll wheel

if this works, please consider closing this issue

**Comment by juliohomus** [comment]
Oh! Only now i noticed the scrollbar is at the opposite side, is this really how is it intended to be???
