### ISSUE TITLE
Not really a bug or feature...observation..Filmic RGB module dialog has a lot of wasted blank space

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#11865]
Just a quick observation as I was re-editing some pictures.

The filmic dialogue has a lot of blank space under the sliders. I was experimenting with some masking with filmic and every time I had to scroll down as the entire mask options are off screen without any good reason due to this padding......

![image](https://user-images.githubusercontent.com/44409419/169661024-ebc2167a-4c96-41e9-a6d8-e99d747c6a75.png)

I am using a recent build on window.... I suspect we could just adust the padding in there to save space??

**Comment by Nilvus** [comment]
See other tabs of this module. There's no padding set here. It's just that all tabs have same height on a module and not all tabs have same options.
Removing that space will make the module have strange behavior, seeing its height being reduced when opening that tab and being increased when going to another tab with more options. That's so done on purpose.

**Comment by todd-prior** [comment]
Okay ...np its just not user friendly by any means....

**Comment by Nilvus** [comment]
It's not ideal yes. If you have better idea to propose (by taking care about what I written, so why @aurelienpierre did that)...

**Comment by todd-prior** [comment]
I also see you meant the tabs within filmic...at first I thought you meant between modules.....I don't know that I could propose anything that would suit everyone. I do like the introduction of some of the collapsable sections with some new features. I am not sure it this or some other solution would work but I do think right now one of the weak points in DT is the expansive modules and the need for way too much scrolling....finding a way to manage that would be a really nice improvement but I am not sure what options are available and how they might impact processing and other aspects of the UI... I do like how ON1 photo does it but you can still have scrolling in some cases ...They use an icon at the top of the module much like we have to turn the mask off and on...this activates and exposes the mask controls and pushes the module sliders down if you still need them... I'm good I understand now what you were saying..... I know a lot of people have worked hard make the modules contents look good....
