### ISSUE TITLE
Using the list of collections with the main filter and "date taken" filter.

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#11867]
Starting to look at this and to understand the issue(s).
You are on windows and may suffer the bug #11582.

However, on linux I can see the following which corresponds somehow to your description.
With `date taken` alone in collection, if I make a selection on filmstrip, the collection's entry ([...;...]) and the images are correctly updated, but the list of dates in collection is not.
With` film roll` and `date taken` in collection, I see the same behavior.
If I change manually the entry values, the collection dates list is not updated either.

The collection list should be updated (and list only the included dates) when 
- one changes the selection in filmstrip
- one changes the entry
- one selects `date taken` after having looked at `film roll` in collection

Do I understand the issue ?

EDIT: But when the selection is not a range, ie. a single date, the 3 cases above are OK for me.
EDIT2: Currently the range is not handled by the collection tree view but it is on the list view. Were the dates in the flat list on some point of the time ?

_Originally posted by @phweyland in https://github.com/darktable-org/darktable/issues/11539#issuecomment-1108722083_

**Comment by esq4** [comment]
> The collection list should be updated (and list only the included dates) when
> 
> * one changes the selection in filmstrip
> * one changes the entry
> * one selects `date taken` after having looked at `film roll` in collection

I built master for Windows.
Unfortunately, it still doesn't work. To get a list of collections, you still need to click the mouse in the field of main filter ("film roll") after selecting the period for the "date taken" filter.

**Comment by phweyland** [comment]
List of collections? I don't get it. 
could you post some screenshots to describe the issue?

**Comment by esq4** [comment]
First video in https://github.com/darktable-org/darktable/issues/11539#issue-1206155417
List in collections module. Like this:
> 2012_09_06(4)
> 2012_09_07(29)

**Comment by phweyland** [comment]
I think I understand now. In fact you want collection filters the list of dates instead of highlighting them. Is that correct ?
Similar request as #11157 if I'm not mistaken.

There are 2 mechanisms in collection. 
The first one, associated to entry editing. In that case the filtering happens.
The second one, associated to manual selection in collection list or automatic entry set by other modules, like timeline or import. It is also applied after a darktable restart, even if the first case had been applied.

If I had to keep one, it would be the second one (I don't really see any advantage to the first one).

**Comment by esq4** [comment]
I guessed to install one of the previous releases. The video shows the behavior that I would like to return.

https://user-images.githubusercontent.com/15331117/169775221-11289ec2-fad4-422b-b231-6415c8ad48f2.mp4

**Comment by phweyland** [comment]
What I see on your example doesn't seem very consistent... you select one date only one appears in collection, you select the other one, the dates appear ...
Then, as you have only 2 dates, I may misunderstand what does happen.
Sorry, I still don't get what you would like.

With my last changes, on Linux, (I haven't tested on windows), when you select a date or a range of dates in timeline, this date or this range is set in collection entry, and the corresponding date items in collection list are highlighted.
Do you see the same on windows ?

**Comment by esq4** [comment]
Well.
I choose the main (first) filter "film roll", because I want to see a list of collections by name. Collections can contain pictures from different dates.
I want to **narrow down search** and I select the second additional (_and_) filter "capture date". Having defined its value (leaving it empty or setting a specific period), I have the right to expect that I will continue to see the list of collections **in the form corresponding to the main filter "film roll"**.
Instead, I see a list view matching the "capture date" filter ("shootings calendar").

i.e.  **narrow down search** doesn't work. It turns out just **replacing** the main filter with an additional one.

_Sorry for my Google-English._

**Comment by esq4** [comment]
> Got it. Narrowing down the search, the list of items follows (with the current version of darktable) the last level of filter (not only with timeline selection). You would like to keep the items list of the main filter. I don't know if it's a recent change or not. Pinging @AlicVB.

The fact is that _the last level of filter_ is **always** replaced by the _"capture date"_ when choosing a period.

**Comment by AlicVB** [comment]
> But if the filter is already there, why add it to the end (and now in fact replace the last one)? Why not change the value of an existing one?

not sure what you want here... you mean, if we already have a "datetime capture" rule, we need to update it ? even if not at the end of the rules list ? That seems doable... we just have to take care of the "or" case, which can potentially break the logic...
But I fear that this point is not your main issue, right ?

Note that the first point (rule replacing or adding) is here from the beginning of this feature.
The second point has appear in december 2021 to solve this : https://github.com/darktable-org/darktable/issues/10612 but I agree that the fix can be enhanced by storing the last active rule in prefs instead of returning always to the last one...

**Comment by esq4** [comment]
> not sure what you want here... you mean, if we already have a "datetime capture" rule, we need to update it ? even if not at the end of the rules list ? That seems doable... we just have to take care of the "or" case, which can potentially break the logic...

Yes, that's right.

As for the "or" case. I experimented with filter sets. It turned out it was not easy.
Task.
I have "_tag1_" (100 pcs) and "_tag2_" (200 pcs). At the same time, in May 2021 I have 1 pcs "_tag1_" and 2 pcs "_tag2_".
How can I build a filter to sort 1 pcs "_tag1_" and 2 pcs "_tag2_" in May 2021?

**Comment by AlicVB** [comment]
> I have "_tag1_" (100 pcs) and "_tag2_" (200 pcs). At the same time, in May 2021 I have 1 pcs "_tag1_" and 2 pcs "_tag2_".
> How can I build a filter to sort 1 pcs "_tag1_" and 2 pcs "_tag2_" in May 2021?

considering you have other pictures in may 2021 that you don't want to show, You need something like : 
- rule filmroll _tag1_
- OR rule filmroll _tag2_
- AND datetime 2022:05



> Yes, that's right.

again, even if that seems a valid issue to fix, I have the feeling that it's not your initial issue...
