### ISSUE TITLE
Toggle parametric channel polarity

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#11861]
The existing toggle polarity button (for all parametric channels) currently only has one action. It inverts all 7 channel polarity switches.
However, it is possible to have any combination of channels which are negative AND positive.
What I would like to see implemented is a 3 way switch that offers:
Toggle all polarities > set all to negative > set all to positive.
When using different combining modes, this would help to ensure all channels are set to the correct polarity.

**Comment by brucewilliamsphotography** [comment]
Martin, I just responded re: your assertion that I had positive polarity on Cz and Hz. That actually is not correct. If you watch closely when I switched to Inclusive mode, you can see that the polarity changes to negative.

**Comment by todd-prior** [comment]
@brucewilliamsphotography Coupled with this and just checking as I can't wrap my head around this one...if you have 7 parametric channels and the polarity is say +  and you set a mask on 2 of them and then switch to inclusive...only the 5 undefined ones switch to - the two that were defined stay... This may actually be the correct behaviour but its worth noting not the same as inverting all the channels as if would do if no mask had been defined yet in the parametric masking section....

**Comment by brucewilliamsphotography** [comment]
Oh crap.
I though that the  "invert all channel's polarity" button ONLY affected the parametric channels.
But it also affects the Drawn mask polarity as well.
OK, maybe we should close this FR, as I've clearly f***ed up.
Apologies to all.
