### ISSUE TITLE
set default intent of output icc profile to relative colorimetric

### ISSUE THREAD

**Issue by blitzgneisserin** [darktable-org/darktable#11875]
Hi,

My suggestion: we should set the default intent of the output icc profile to relative colorimetric. At the moment, the default setting is perceptual which causes trouble sometimes, especially if you share photos on social media - the colors are often changed since perceptual is a more unusual intent and some software apparently cannot deal with it. I think relative colorimetric is a safer choice for most users.
If you think this is wise, I think I know where this is in the code.

Thanks in advance

Anna

**Comment by aurelienpierre** [comment]
Do you have evidence of intents doing anything at all ? Because they should not, see https://github.com/darktable-org/darktable/issues/11777

**Comment by parafin** [comment]
AFAIK intent is not saved in the output file - it only defines how to get to the output colorspace for out-of-gamut colors. So I guess this is more about color profile or CMS issue. Example cases are required to understand the issue.

**Comment by blitzgneisserin** [comment]
ok. thanks for the feedback. I will upload some screenshots tomorrow.
Bottom line: social media such as Instagram or Pixelfed process the uploaded photos somehow and they change the colors if the they were edited with darktable with export rendering intent perceptual.
RawTherapee has rendering intent relative colorimetric as default and there is never an problem.
However, it might be worth an experiment to do some tests with other apps using perceptual.
@aurelienpierre you know perfectly what I mean.

**Comment by blitzgneisserin** [comment]
Well, I just had a very quick look at Aurélien's bug report.
Just want to add this: apparently there is no problem when the exported photos with intent perceptual are viewed directly with a properly color managed image viewer or even a browser such as Firefox. The problem is only when they are processed by Pixelfed or Instagram.

**Comment by aurelienpierre** [comment]
> The problem is only when they are processed by Pixelfed or Instagram.

>  @aurelienpierre you know perfectly what I mean.

Indeed, but using Chrome instead of Firefox fixes the color issues, so I doubt it has anything to do with the ICC tags in the file.

**Comment by blitzgneisserin** [comment]
I don't know, I could not reproduce this today, I uploaded 3 photos to pixelfed and Instagram and none of the colors were changed.
