### ISSUE TITLE
Tethering doesn't work with Nikon D5600

### ISSUE THREAD

**Issue by rafalkrupinski** [darktable-org/darktable#11878]
**Describe the bug/issue**
I'm on DT 3.8.1 and I have my Nikon connected,
Opening Tethering tab results with an error message:

> no camera with tethering support available for use...

The troubleshooting instructions (test with gphoto) pass successfully.

> $ darktable -d camctl
> 0.899299 [camera_control] creating new context 0x558a59b97ce0
> 0.905649 [camera_control] loaded 2562 camera drivers.
> 1.249384 [camera_control] loaded 11 port drivers.
> 1.260477 [camera_control] 1 cameras connected
> 1.260518 [camera_control] found new Nikon DSC D5600 on port usb:003,008

**Platform**

* darktable version : 3.8.1 installed from the official deb
* OS                : kernel 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
* Linux - Distro    :Debian bullseye
* Memory            : 16G
* Graphics card     : TigerLake GT2 [Iris Xe Graphics]
* Graphics driver   : i915
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : KDE

**Comment by Nilvus** [comment]
Sorry, forget my comment. This link in gphoto website seems to be quite outdated and gphoto team doesn't update it. Quite bad. See that your camera is listed with support in that link: http://gphoto.org/proj/libgphoto2/support.php

I so let if someone else could help you here.

**Comment by rafalkrupinski** [comment]
It worked before. Not sure which version, I've reinstalled the system since then

**Comment by aurelienpierre** [comment]
I have similar issues with Nikon D810. Used to work, doesn't anymore. The error is on GPhoto2 side…

**Comment by Nilvus** [comment]
I close this issue as the error is on Gphoto2 side. @rafalkrupinski: post an issue on Gphoto2 side if needed.

**Comment by rafalkrupinski** [comment]
> @rafalkrupinski: post an issue on Gphoto2 side if needed.

🤔 I'm not really a developer using GPhoto2 library, and the command line utility works for me 🤷🏻
