### ISSUE TITLE
Libavif issue on Debian Sid

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#11871]
**Describe the bug/issue**

On actual master and Debian Sid, there's now an issue with libavif. When trying to compiled with libavif-dev installed, compile failed. After uninstalling that library (I don't use avif format), darktable complains on launch with:

`[imageio_load_module_format] failed to open'avif' libavif.so.13: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type`

The issue was also related to same file when compiling. Indeed, on Debian Sid, there's no more libavif.so.13 but libavif.so.14. Probably something to update to take care of that as it's probably not only on Debian Sid or will not be in a near future. We need to link libavif to version 14 also.

**Platform**

* darktable version : last master (compiled today)
* Linux - Distro    : Debian Sid

@TurboGit: maybe you can test/fix that as I know you also use Debian Sid?

**Comment by TurboGit** [comment]
You probably want to rebuild from scratch. I'm not sure we can do something at build time about this.

**Comment by Nilvus** [comment]
My bad. I did it everytime when compiling master but not always when working on tweaking darktable with my branch. Indeed, rebuild from scratch works. Sorry for the noise.
