### ISSUE TITLE
Fill tool in Retouch Module: Color picker should be automatically switched off after the color has been selected.

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#11881]
If I want to select a color from the photo with the color picker in the fill tool in the retouch module, the following steps are necessary:

1. turn on the color picker (icon next to the color bar on the right). 
2. move the mouse cursor to the area where you want to select the color.
3. left click to select the color (cursor gets "target" shape). 
4. turn off the color selector by clicking on the icon on the right. 

The problem: If you don't do step 4 and select one of the shapes, the shape icon becomes active but you can't create the shape because the color picker is still active:

![fill_tool_color_picker](https://user-images.githubusercontent.com/38165484/169963372-cce256a8-b213-43e8-ad79-1a3a645781f5.jpg)

If you don't pay attention to this, and click somewhere on the photo, you will choose another color instead of creating the shape. 

Possible solution:

1. turn on the color picker (icon next to the color bar on the right). When you hover the mouse over the photo, mouse cursor gets "target" icon. 
2. with the left click color is selected and color picker is automatically turned off. Mouse cursor gets its original shape (arrow) again.

**Comment by elstoc** [comment]
It needs to be possible to adjust selection after clicking with the mouse, so I wouldn't be happy with automatically disabling the picker after picking. It does make sense to disable it when clicking a shape icon though and vice versa (disable the shape icon when picking a colour).

**Comment by s7habo** [comment]
> It does make sense to disable it when clicking a shape icon though and vice versa (disable the shape icon when picking a colour).

That would also be an elegant solution, yes. 

Actually it works that way when you select an area in a parametric mask with color picker. The moment you select one of the shapes for drawn masks the color picker of the parametric mask is switched off.
