### ISSUE TITLE
Improve generic range filters

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11887]
As with the star filters, the generic range filters have some readability issues (arguably more so) when pinned to the top bar. For example, I managed to pin the following filters (capture date, aperture, focal length) to the top bar. This is what it looks like:

![Screenshot_2022-05-25_07-55-23](https://user-images.githubusercontent.com/9555491/170199996-422005f2-07e4-439f-bc8b-83171ca4334f.png)

The _only_ way to read these filters is by hovering over and waiting for the tooltip to appear (though readability is better in the collection filters module).

I agree that these filters make _selecting_ things easier but they are virtually impossible to read so IMO they still only do half a job. I'm also not convinced that the histogram-like display is particularly useful without some axis labels (which obviously would make the widgets too high/complex). I kind of have similar feelings about the timeline view in the lighttable, but at least that has year indicators along the x axis.

**Comment by elstoc** [comment]
These filters still need improvement

**Comment by emko** [comment]
there is a good reason when dealing with dates everyone uses a calendar ... those other two should be drop downs you need to see the actual values, are we to remember some QR patterns instead of it saying 50mm or F1.8 ? this is crazy

**Comment by quovadit** [comment]
Maybe we should highlight and label the the most commonly used value.

This way it would be clear which pattern shows which criteria:
![image](https://user-images.githubusercontent.com/5677563/193474507-f6035bdc-ea17-4081-a995-8e2ad486302a.png)


If the drop-down-icon is used to open the list of values, then right-click could be used to change the graphical interface to a text-field entry: 

`focal length: >=50`

**Comment by elstoc** [comment]
Good that you're thinking of stuff, but IMO that's not any better, and potentially misleading if you're only showing a single value.

**Comment by quovadit** [comment]
that's true, so what about showing the selected range:
![image](https://user-images.githubusercontent.com/5677563/193510120-12721a3a-78fd-4f43-aee1-3e3f26b7e9f1.png)
