### ISSUE TITLE
Append Style Overwrites

### ISSUE THREAD

**Issue by clovervalleyapps** [darktable-org/darktable#11893]
Darktable 3.8.1 installed on Linux Pop!_OS 22.x

Replicate by:
In darkroom > Duplicate Manager
Duplicate or Original
Quick access style, apply with append selected and it will overwrite.

or

In Lighttable > Styles 
mode append
Apply style (with or without duplicate checked) and it overwrites instead of append.

That's it. Thx.

**Comment by pehar1** [comment]
3.9.0+1599~geef567d5d, Ubuntu 20.04
Works well for me, both in lighttable and darkroom, both overwrite and append (tried all combinations). Not able to reproduce your issue.

**Comment by jenshannoschwalm** [comment]
I think that has been fixed in master for 4.0

**Comment by TurboGit** [comment]
Yes this is #7352 I think.
