### ISSUE TITLE
Expired certificate for apt repository at OpenSUSE

### ISSUE THREAD

**Issue by aharisi** [darktable-org/darktable#11898]
The certificate for the apt repository for the Ubuntu/Debian Linux build of Darktable appears to have expired. I get the following error message when updating my repositories:

GPG error: http://download.opensuse.org/repositories/graphics:/darktable:/stable/xUbuntu_20.04  InRelease: The following 	signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>

Just so you know,

-- A.

**Comment by kmilos** [comment]
See https://github.com/darktable-org/darktable/issues/11851

**Comment by deric** [comment]
Again, the same issue. The key appears to be expired.

fetching "new" gpg key doesn't help
```
curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/xUbuntu_24.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics_darktable.gpg > /dev/null
```

expired on `2024-07-26`
```
gpg  --show-keys  /etc/apt/trusted.gpg.d/graphics_darktable.gpg
pub   rsa2048 2017-12-26 [SC] [expired: 2024-07-26]
      3247B7519EDBEAB422E900A3040524A84C70D8B5
uid                      graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>

```

**Comment by fri-K** [comment]
Same here

**Comment by l0f4r0** [comment]
Same here
