### ISSUE TITLE
darktable 3.8.1 - Installer issues about italian language

### ISSUE THREAD

**Issue by bovirus** [darktable-org/darktable#11891]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

---------------------------------------------------------------

**Describe the bug/issue**

Italian langauge strings for installer is not complete.
Uninstalelr messageis in english.
Module name and options are in english.
Icond escription in program group are in english.

**Expected behavior**

I can help with italian strings

**Screenshots**

![image](https://user-images.githubusercontent.com/1262554/170231383-91a75ada-8dfe-44b5-88d8-9ee9ac122a6c.png)

![image](https://user-images.githubusercontent.com/1262554/170231504-5f5f80df-6721-4adf-af33-fd62154679f5.png)

![image](https://user-images.githubusercontent.com/1262554/170231663-bf7d71dd-460c-4f21-90ce-cebd721797fe.png)

**Screencast**

**Which commit introduced the error**

**Platform**
Windows 11 64bit

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : Windows 11
* Memory            : 16GB
* Graphics card     : NViadia RTX30
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

**Comment by kmilos** [comment]
Looks like the NSIS installer already provides Italian translations: https://packages.msys2.org/package/mingw-w64-x86_64-nsis?repo=mingw64

No idea how to use/package those though...

**Comment by bovirus** [comment]
@kmilos

the NSIS contains only standard string for base NSIS.

If you create model, icon description, out of standard NSIS base language the developer should cvustomize it as multilanguage.

I beleieve that the problem is tehs ame for all language and then the darktable developr should fix tit.
](https://github.com/kmilos)

**Comment by bovirus** [comment]
@kmilos 

No news?

**Comment by bovirus** [comment]
It seems that no one of the devlopers are intersting to make the installer multilanguage.

**Comment by victoryforce** [comment]
> It seems that no one of the devlopers are intersting to make the installer multilanguage.

Here it is worth talking not about interest, but about having the necessary experience in the relevant field. Probably none of the current contributors have it. Anyone with NSIS experience can help.
