### ISSUE TITLE
Copy & import from camera and add to library windows doubts.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11907]
darktable 3.9.0~git1613.62a862d0-7830.1
Fedora 36

**Describe the bug/issue**
With the copy & import from camera and add to library windows I have two doubts. I don´t know if this was made on purpose or if this is an issue. Please clarify me if I am wrong. 

1. There are two buttons that seems to have the same function. "select only new pictures"(with a check mark) and "select new" at the bottom of the window. I post a video demonstration with it.

2. The select only new pictures have a check mark and as I've seen with other apps if users select the check mark, then every new picture selected must be with a check mark as indication, but in this case, the check marks in the list of images is an indication of the others pictures previously imported. Maybe this will not the best icon to show the pictures already imported and other icon must be used for the purpose to show the pictures already imported. On the other hand the new pictures to import don't have any indication beside the selection color.

I'm working in an idea to update this post #10110 and include a selection check mark for individual images too.

**Expected behavior**
To the first case, one of the two buttons will remains. Again, correct me if I'm wrong.

The second case, the expected behaviour must be that if the button "select only new pictures" the check mark is on, then all the new pictures to import must be selected with the check mark icon too as sign of new images to import.

**Video**
https://user-images.githubusercontent.com/67672868/170633312-3ac4119d-210c-4241-b09d-2a122c8d1c31.mp4

**Screenshot**
![IMPORT Screenshot](https://user-images.githubusercontent.com/67672868/170624603-1bcdf9a8-3555-4f3a-a47b-82116fc4c39d.png)

**Comment by elstoc** [comment]
> There are two buttons that seems to have the same function. "select only new pictures"

IIRC the button actively selects items and the checkbox acts as a default parameter for the next time images are imported.

**Comment by difrkaguilar** [comment]
> the checkbox acts as a default parameter for the next time images are imported.

Really I don't see any advantage in this function. Every time I'm going to import pictures I use select new "on the fly" so I don't use a default "on" check mark for the next time. I don't want the app decide for me if I like to select all new pictures or just one to import.
