### ISSUE TITLE
Change setting for 'look for updated xmp files on startup' in something like 'look for update when accessing folder/file' or do it after DT started

### ISSUE THREAD

**Issue by teeehhias** [darktable-org/darktable#11913]
**Is your feature request related to a problem? Please describe.**
Yes, this setting makes darktable incredibly slow to start, as it has to run through the whole library first it seems.

**Describe the solution you'd like**
Change setting for 'look for updated xmp files on startup' in something like 'look for update when accessing folder/file' or do it after darktable is already up and running.

**Alternatives**
Anything that won't slow down program startup that much and has the same effect, really. Maybe someone else even has a better idea than me.

**Additional context**
This would help usability a lot, especially when working in conjunction with other tools, for example like digikam.

**Comment by ptilopteri** [comment]
perhaps make it an action that is *only* available when selected, not on startup.

initiate the "action" and right now it searches for changed xmp files

**Comment by teeehhias** [comment]
> perhaps make it an action that is _only_ available when selected, not on startup.
> 
> initiate the "action" and right now it searches for changed xmp files

Sounds good to me too.
