### ISSUE TITLE
`$(ROLL_NAME)` is just first-level folder name

### ISSUE THREAD

**Issue by dogusAkaydin** [darktable-org/darktable#11929]
**Describe the bug/issue**

`$(ROLL_NAME)` is just first-level folder name, not the name of the film roll as displayed in the list under Collections. 
If the images are placed, for example, in `D:\photos\2022.12.01-New_Years\NEF` then `$(ROLL_NAME)` simply becomes `NEF`, not `2022.12.01-New_Years\NEF`, which is the name displayed in film rolls list with 2-level deep naming scheme. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Export' in Lighttable module. 
2. Select $(ROLL_NAME) as a parameter to define the export location. Eg. `D:\\darktable_exports\\$(ROLL_NAME)`
3. See that the images are exported to under first-level directory, i.e. `D:\darktable_exports\NEF`

**Expected behavior**
$(ROLL_NAME) should be the film roll name as displayed on the Collections, resulting in images being exported to `D:\darktable_exports\2022.12.01\NEF`, as per the example given.

(For the future, feature request: Be able to define roll names by truncating the path from the right as well. Eg. roll name for images under `D:\2022.12.01-New_Years\NEF` can be set to `2022.12.01-New_Years` by truncating the level-1 subdirectory name `NEF`.) 

**Platform**

* darktable version : 3.8.1 release
* OS                : Win10

**Comment by pehar1** [comment]
Did you try `$(FILE_FOLDER)` ?

**Comment by phweyland** [comment]
Not a bug. Like this since 2015.

**Comment by dogusAkaydin** [comment]
> Did you try `$(FILE_FOLDER)` ?

Yes, unfortunately `$(FILE_FOLDER)` is the full path and not usable to define new paths.
