### ISSUE TITLE
collections: "range rating" appears as a filter criteria

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11923]
Since "range rating" is a term associated only with a specific type of filter widget in the "collection filters" module, this term should not be referenced in the collections module and it should instead be named "rating".

![Screenshot_2022-05-28_19-01-45](https://user-images.githubusercontent.com/9555491/170837569-f0a50b64-2ad0-4aac-b620-246b1d089ba5.png)

**Comment by Nilvus** [comment]
I agree here. Better to use usual name here. Use is the same. I propose #11930 to fix that.
