### ISSUE TITLE
DNG files from DJI Mini 3 Pro drone cannot be opened.

### ISSUE THREAD

**Issue by mluckau** [darktable-org/darktable#11949]
**Describe the bug/issue**

Trying to open a DNG file from DJI Mini 3 Pro

**Expected behavior**

File opens and I can edit it

**Screenshots**
![sh_20220530_234618](https://user-images.githubusercontent.com/6820488/171062146-a5689a97-cfee-400d-b2a0-68b964637d73.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.1
* OS                : Linux Manjaro 5.17.9-1
* Linux - Distro    : Manjaro
* Memory            : 32 GB
* Graphics card     :  AMD RX 5700 XT
* Graphics driver   : 
* OpenCL installed  :  yes
* OpenCL activated  : 
* Xorg              : 
* Desktop           :  KDE Plasma
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by kmilos** [comment]
There are known issues w/ DJI files: https://github.com/darktable-org/darktable/issues/10852#issuecomment-1122503717

Please let DJI know.
