### ISSUE TITLE
Issues with mask manager icons

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11963]
While working on the updated documentation for darktable 4.0 I've been trying to get revised screenshots of the mask manager icons in the grey color scheme.

Unfortunately, these icons no longer seem to be particularly legible in this color scheme and, for some reason they all seem to be slightly offset and are no longer symmetrical. It's possible the asymmetry is a fairly long-standing issue since I see the old user manual screenshot has the same problem. I believe I copied the individual icon images from the pre-dtdocs user manual.

In the darktable theme they are pretty legible but you can see that they are offset:
![Screenshot_2022-06-03_00-34-21](https://user-images.githubusercontent.com/9555491/171756122-1fc31f6d-dafc-4d45-8ee0-588560a9275d.png)

In the darktable-elegant-grey theme, they're very difficult to distinguish from the background:
![Screenshot_2022-06-03_00-35-04](https://user-images.githubusercontent.com/9555491/171756269-1fc64ffc-ad19-4079-96c4-a0d4e34550db.png)

See [here](https://docs.darktable.org/usermanual/3.8/en/module-reference/utility-modules/darkroom/mask-manager/#set-operators) for how the icons _should_ look.

**Comment by elstoc** [comment]
This is a bit CSS and perhaps a bit icon design so might be ideal for @Nilvus to look at :)

**Comment by elstoc** [comment]
I decided to replace the icons in module groups with the mask manager icons so that I could see what they're supposed to look like, and it appears they've never really displayed correctly. The correct "look" of the icons is as follows:
![masks_difference](https://user-images.githubusercontent.com/9555491/171842871-89838221-0982-4d59-9670-ddcba6455b3b.png)
![masks_exclusion](https://user-images.githubusercontent.com/9555491/171842873-8da3c1e0-d2ba-459e-b01a-d6e76c142384.png)
![masks_intersection](https://user-images.githubusercontent.com/9555491/171842874-5d1b48f5-9ed8-49a8-a1f5-25cb574d9574.png)
![masks_union](https://user-images.githubusercontent.com/9555491/171842875-e7fb97d2-d982-463e-a0bd-15afd4c9c1c6.png)

**Comment by Nilvus** [comment]
Thanks for those infos, especially last screenshot. Will help. I will check that ASAP. Just to win time, you seems to have already find which lines of paint.c are used to display those icons. If possible for you to post them here (if it's quick of course. If not, I will find them myself). Thanks!

**Comment by elstoc** [comment]
I've had a play with the code myself and there's a lot of black magic involved in this - I can't figure out where the issue might be.

The icons are generated by some blocks of boilerplate code generated in `src/libs/masks.c` starting at line 1604. You can find the names of the `paint.c` functions in there as well.

**Comment by elstoc** [comment]
Looks like this code was written by @AlicVB in the first place (though nearly a decade ago now) so he might be able to advise.

**Comment by AlicVB** [comment]
Effectively, that code doesn't seems to be up to date with the actual dt standard ;) : fixed icon size, fixed color...
For me, we have 2 issues here : 
- the colors (need to be set by css)
- the size (we may want non square icon)

For the little story, that code is not really mine : at the time I've written the mask manager, I had not experience with icon drawing in cairo, and someone (don't remember who) has done a diff for me...

Anyway, I'll have a look...
