### ISSUE TITLE
darktable crash

### ISSUE THREAD

**Issue by shirt-less-guy** [darktable-org/darktable#11970]
**Describe the bug/issue**
Seems to occur after having applied a style, I go to edit the RAW photo in Darkroom. I am either using Filmic, diffuse or sharpen module, and then darktable will crash. It is not consistently crashing but did crash 5x today.

3.8.1

https://www.dropbox.com/scl/fi/dtyhwolidvta1ifb8lj9r/darktable-bug-report.docx?dl=0&rlkey=yzqn3laymyp2hus2xubdgw7o8 
Darktable bug report

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

odel: MacBookPro18,3, BootROM 7459.121.3, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Apr  6 2022 05:55:54 version 20.90.45.0.8.7.118 FWID 01-e7138ff2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no** Don't have another version
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both** Only using RAW
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no** I don't think so, but I have seen it crash when I am just starting fresh.
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no** I have not tried
 - Do you use lua scripts? No
   - What lua scripts start automatically? None
   - What lua scripts were running when the bug occurred? No

**Comment by MStraeten** [comment]
you need to provide at least the used style and maybe an affected image and it’s xmp sidecar file so someone can try to reproduce.

**Comment by shirt-less-guy** [comment]
It won't let me paste a NEF and xmp file... 
Here found a way to do it in Dropbox. 
https://www.dropbox.com/s/22hast3pb5h3lr7/DSC_0582.NEF?dl=0
https://www.dropbox.com/s/49dt6hhqhx7deqw/DSC_0582.NEF.xmp?dl=0

**Comment by shirt-less-guy** [comment]
I am also just getting crashes with just doing filmic RGB. Just doing initial corrections. Adjusted exposure. Turned off highlight reconstruction. Using the reconstruction tab of filmic, adjusting the threshold down and it crashes, consistently.

**Comment by dterrahe** [comment]
Does this still happen in 4.0.1 or current master?

**Comment by ralfbrown** [comment]
Closing as the original reporter has not responded in over six months and the report is for a version two (soon to be three) releases ago.
