### ISSUE TITLE
Can't import HEIC files

### ISSUE THREAD

**Issue by soswow** [darktable-org/darktable#11974]
**Introduction**
https://www.darktable.org/2021/12/darktable-3.8.0-released/ says HEIC support has been added. But I get a skull image instead.

**Did you buy darktable from an application store ?**
I don't think so.

**To Reproduce**
1. Get 3.8.0 version of app on Mac os 12.2.1
2. Try import provided HEIC file
3. It is not imported properly

**Screenshots**

**Screencast**
![image](https://user-images.githubusercontent.com/108065/171993476-8fa82292-a473-4ad9-b9f9-83cbaeeb6f51.png)

**Platform**
See screenshot.

[IMG_3730.HEIC.zip](https://github.com/darktable-org/darktable/files/8837372/IMG_3730.HEIC.zip)

**Comment by victoryforce** [comment]
The file you provided ia actually a JPEG file with the wrong .HEIC extension. If you change the extension to one that matches the file format, this image will be imported correctly.

**Comment by soswow** [comment]
oh wow. how the hell did that happened =( I've downloaded it from Google Images. I guess that's google's bug - my wife's iPhone uploaded HEIC, they converted it to JPEG, but left HEIC extension when you download. Feel free to close it.
