### ISSUE TITLE
Gamut escape in colorbalancergb slider backgrounds

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#11983]
**Describe the bug/issue**

Chroma sliders in the "4 ways" tab of colorbalancergb display have wrong hues / gamut escape in the slider background. This seems to happen especially for the shadows chroma slider when a blueish hue is selected, see screenshot:

![chroma_slider_gamut_escape](https://user-images.githubusercontent.com/5001906/172044681-3a886264-7c98-4a1a-944b-c1f1d9b688f7.png)

I'm halfway through fixing this – now that we have the `Yrg` gamut mapping code for filmic, it's easy enough to apply the same code for these slider backgrounds which also happen to be calculated in `Yrg`. It's very simple, just clip the chroma so that there are no negative RGB values.

I just need a little bit of help / information (probably from @aurelienpierre ) – in [`paint_chroma_slider()`](https://github.com/darktable-org/darktable/blob/9a5e3a0f4bc813355067607cdba7516443071804/src/iop/colorbalancergb.c#L1403), it seems that sRGB values are sent to bauhaus / GTK. Is that right, i.e. are the GUI widgets color managed? Are these sRGB values eventually converted to display profile before sending to display? I'm wonder if I should clip chroma against display profile, sRGB or both.

**Platform**

* darktable version : master / bd076699fbeb775f33df84a09982737c82299d2c
* OS                : Linux - kernel 5.18.1
* Linux - Distro    : Arch Linux
* Memory            : 16 GB
* Graphics card     : Intel HD Graphics 520
* Graphics driver   : mesa 22.1.1
* OpenCL installed  : yes
* OpenCL activated  : yes / no
* gcc               : 12.1.0
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Comment by aurelienpierre** [comment]
That's most likely the consequence of the white point change in Yrg, but it's weird since it's gamut-clipped like such:

```
    dt_aligned_pixel_t RGB = { 0.f };
    dt_aligned_pixel_t Ych = { 0.75f, x, h, 0.f };
    dt_aligned_pixel_t XYZ = { 0.f };
    Ych_to_XYZ(Ych, XYZ);
    dt_XYZ_to_Rec709_D65(XYZ, RGB);
    const float max_RGB = fmaxf(fmaxf(RGB[0], RGB[1]), RGB[2]);
    for(size_t c = 0; c < 3; c++) RGB[c] = powf(RGB[c] / max_RGB, 1.f / 2.2f);
    dt_bauhaus_slider_set_stop(w, stop, RGB[0], RGB[1], RGB[2]);
```

Indeed, like most of Gtk code in dt, it's not color-managed so it outputs sRGB no matter what. I have color-managed the color calibration sliders IIRC, so it's not terribly complicated to do, but you have to wait for the pipeline to be inited so you can grab the output profile.

**Comment by flannelhead** [comment]
> That's most likely the consequence of the white point change in Yrg, but it's weird since it's gamut-clipped like such

I think it's because the default max chroma 0.5 (for the shadows slider) is too high for some blue hues and causes negative RGB. The `powf` probably won't like negative base.

> I have color-managed the color calibration sliders

Thanks for the pointer, I'll look there.
