### ISSUE TITLE
CSS: headers are smaller than content

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#11988]
Looking at iop modules it appears that the module header and section headers use a smaller font than that used for the module controls. This doesn't look right to me. An example from diffuse/sharpen:

![Screenshot_2022-06-05_17-04-54](https://user-images.githubusercontent.com/9555491/172059574-96652f41-edaa-40a8-8564-a47d6b9e5710.png)

Similar on _some_ but not all of the lib modules. For example import doesn't look so bad:

![Screenshot_2022-06-05_17-08-12](https://user-images.githubusercontent.com/9555491/172059647-f7bc3d74-a585-4999-891d-53e3326d2a99.png)

**Comment by elstoc** [comment]
@Nilvus: Another one for you I'm afraid.

**Comment by Nilvus** [comment]
I've check but I fear the issue is not on CSS. Or to be more precise, the issue is about bauhaus here. See for example on filmic. You could see some text lighter than all sliders/combobox (first and last tab). Not so easy...

**Comment by elstoc** [comment]
Yes I see now there's a comment in `bauhaus/bauhaus.c`

```
  PangoFontDescription *font_desc =
    w->is_section && is_label
    ? pango_font_description_copy_static(darktable.bauhaus->pango_sec_font_desc)
    : pango_font_description_copy_static(darktable.bauhaus->pango_font_desc);

  // This should be able to update the font style for current text depending on :hover, :focused, etc.
  // CSS pseudo-classes, yet it defaults to system font.
  // FIXME: get that working so we can put :active text in bold, for example.
  //gtk_style_context_get(context, gtk_widget_get_state_flags(GTK_WIDGET(w)), "font", font_desc, NULL);
```

**Comment by Nilvus** [comment]
And it's quite old: https://github.com/darktable-org/darktable/commit/78938789194e47e1507a0fb21502702278fb81c3

**Comment by elstoc** [comment]
Looks like it might be a simple issue. If I change the quoted lines as follows it seems to work ok:

```
  PangoFontDescription *font_desc = 0;

  // This should be able to update the font style for current text depending on :hover, :focused, etc.
  // CSS pseudo-classes, yet it defaults to system font.
  // FIXME: get that working so we can put :active text in bold, for example.
  gtk_style_context_get(context, gtk_widget_get_state_flags(GTK_WIDGET(w)), "font", &font_desc, NULL);
```

**Comment by Nilvus** [comment]
@AlicVB made the fix (and I just add to his fix a little improvement on section label too). PR is coming.

**Comment by elstoc** [comment]
Yes it turns out that was all that was needed - my freezes were unrelated (a fresh config got rid of them)

**Comment by AlicVB** [comment]
@elstoc : funny that we have reach the same point at the same moment :)
but I've not see any freeze... where is the problem for you ?

**Comment by elstoc** [comment]
Sad to say I've just redone a bunch of screenshots for dtdocs, which I'll probably have to do again once this fix goes in :(

**Comment by AlicVB** [comment]
I don't who is the OP of this issue, but if I were you I would be mad at him :D

**Comment by Nilvus** [comment]
@elstoc: wait a little to update screenshots. I will post another UI update fix tomorrow (not related to this issue).

**Comment by elstoc** [comment]
Just checking since we both arrived at the solution together, but are you planning to PR this @AlicVB or expecting me to?

**Comment by Nilvus** [comment]
> Just checking since we both arrived at the solution together, but are you planning to PR this @AlicVB or expecting me to?

@AlicVB will do it (probably today) with a little CSS fix on mine for section_label too (especially for old default darktable theme and blending sections).
