### ISSUE TITLE
missing translation option in range selection 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#11981]
eve the term "now" is translated in the po file it's not translated in the GUI:
![image](https://user-images.githubusercontent.com/39386816/172039700-1da19eaf-0738-4341-9f4a-e5574f48b9a0.png)

translation properly used in date selection dialog:
![image](https://user-images.githubusercontent.com/39386816/172039780-d68cca52-554e-49b3-8cb6-1f66963b1e8e.png)

**Platform**
* darktable version : darktable-3.9.0+1690~g04eabd0e9
* OS                : OSx

**Comment by TurboGit** [comment]
Thanks, now fixed.
