### ISSUE TITLE
Font issue with "darktable-elegant" themes.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#12005]
**Describe the bug/issue**
When I open darktable with the "darktable-elegant-grey" theme, the fonts don´t looks fine, some anti aliasing issue. As I can see the font used is "Roboto Condensed". I'm not really sure if is from my side or if others have the same issue. I'm using a 4k 32 inches monitor with 3840x2160 resolution and the darktable preferences I set "use system font size. (12)
@Nilvus maybe you can bring some light to this post :-)

**Screenshots**
![Screenshot-20220607110754-1195x254](https://user-images.githubusercontent.com/67672868/172420473-6282d3f9-5ea6-49b3-8fff-1c85524f0f53.png)

![Screenshot-20220607110846-409x401](https://user-images.githubusercontent.com/67672868/172420512-c5e031df-e549-401c-80f8-fb1f95d3e27f.png)

**Other screnshots**
![Screenshot-20220607112731-1070x770](https://user-images.githubusercontent.com/67672868/172420676-cbb83d6b-2c96-4b0a-bbee-ab375da46d32.png)

![Screenshot-20220607112821-1177x953](https://user-images.githubusercontent.com/67672868/172420725-d702970a-b4dc-4299-be44-de814477176e.png)

**Which commit introduced the error**
Not sure.

**Platform**
darktable version : 3.9.0~git1720.5a42e341-7916.1
OS: Fedora release 36 (Thirty Six) x86_64
OS Type: 64-bit
Host: Host: Gigabyte Technology Co., Ltd. Z390 AORUS MASTER 
Kernel: 5.17.12-300.fc36.x86_64 
Uptime: 1 hour, 52 mins 
Packages: 3065 (rpm), 39 (flatpak) 
Shell: zsh 5.8.1 
Resolution: 3840x2160 
DE: GNOME 42.2 
WM: Mutter 
WM Theme: WhiteSur-dark-solid 
Theme: WhiteSur-dark-solid [GTK2/3] 
Icons: WhiteSur [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel® Core™ i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Nvidia Driver Version: 465.19.01
Memory: 4194MiB / 32036MiB
OpenCL installed: yes
OpenCL activated: yes
Xorg: X11
gcc (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)

**Additional context**
- Do you use lua scripts? Yes

**Comment by Nilvus** [comment]
I have same size screen and resolution as you. I also use Gnome 42.2 with exact same anti-aliasing settings. So what you have seems that you don't have all needed Roboto fonts installed. So be sure you have them all (you can check which ones are needed easily on darktable-elegant-darker.css theme.

darktable and darktable-icons themes use OS font size, so what you have shown here on Gnome tweaks tool.

To resume, when having such issues like you show here on grey theme, that had always been due to 2 things:
- anti-aliasing setting to adjust
- or missing Roboto font

**Comment by Nilvus** [comment]
Oh, last thing, if you test dark and darker themes (other elegant ones), you should have so same issue. Not only on grey theme. And as you don't have it on darktable classic themes, that show it's probably not anti-aliasing issue.

**Comment by Nilvus** [comment]
@difrkaguilar: any news for that one?

**Comment by difrkaguilar** [comment]
I checked in my fonts folders and as I suspect, the entire roboto fonts family was installed, even the compresed ones. Really I don't have a clue of where is the problem. I'm going to install everything again and check if the issue continues or not.

**Comment by Nilvus** [comment]
Something strange here. Do you test dark and darker themes? You should have same issue and so could you update your title to only link that to elegant theme and not grey one. Fonts for elegant themes are set in darker css file. If you check on Gnome tweaks and fonts tab, could you see all Roboto fonts needed?

**Comment by difrkaguilar** [comment]
I  checked the other themes and have the same issue.

> If you check on Gnome tweaks and fonts tab, could you see all Roboto fonts needed?

This is the font selector of Gnome tweaks.
![Screenshot-20220611212552-544x1516](https://user-images.githubusercontent.com/67672868/173210344-1144a592-ab76-4e4a-821c-6d51551e13af.png)

Those are my fonts folders with Roboto font family.
![Screenshot-20220607213130-1594x1088](https://user-images.githubusercontent.com/67672868/173209836-850c0c36-c8aa-4993-94c0-d77fd8b4a2fe.png)

![Screenshot-20220607213118-1594x1088](https://user-images.githubusercontent.com/67672868/173209840-9be0606a-1f45-4ad9-81c7-2bd7533d436f.png)

This is my "darktable-elegant-darker.css"
![Screenshot-20220611210929-1019x1270](https://user-images.githubusercontent.com/67672868/173210068-4f53850a-8421-48c8-8b3f-67fc4155936e.png)

darktable-elegant-grey theme
![Screenshot-20220611210435-351x311](https://user-images.githubusercontent.com/67672868/173210077-29b54f81-863e-49f6-a459-5d04b24e9b7b.png)

darktable-elegant-dark theme
![Screenshot-20220611210501-352x312](https://user-images.githubusercontent.com/67672868/173210089-7cce983d-ba96-472a-ba56-fe6037352b61.png)

darktable-elegant-darker theme
![Screenshot-20220611210521-353x311](https://user-images.githubusercontent.com/67672868/173210093-b804a110-c155-4463-b29c-cf3ace30d5b6.png)

**Comment by Nilvus** [comment]
I see the issue on font selector of Gnome tweaks for Roboto Condensed. Seems that it's only for this font on what I see on your screenshots. So clearly not, as I suspected, a darktable issue. I never see that but seems that this font is somewhat broken. I would suggest you to download Roboto Condensed from a font website (for example Google fonts) and erase actual one.

I close this issue as it's not darktable one but we could discuss here if needed. And especially if you succeed to fix that.

**Comment by difrkaguilar** [comment]
@Nilvus  Solved!!!!! Thanks a lot!!!!
After install the Roboto fonts family from Google fonts using the Font manager everything looks perfect.

![Screenshot-20220612111351-1174x850](https://user-images.githubusercontent.com/67672868/173240385-70c9d543-bfbe-473e-a4b2-bcd608e8d5e1.png)

![Screenshot-20220612112138-355x317](https://user-images.githubusercontent.com/67672868/173240393-120de040-438e-47a5-b61b-02c7e76febf0.png)

Thanks again.

**Comment by Nilvus** [comment]
@difrkaguilar: glad to read that.That so seems that Fedora have broken Roboto Condensed fonts. Quite surprising! Maybe an issue on their repo for Roboto packages would be good with a link on that issue.
