### ISSUE TITLE
Entering variables should be more user friendly

### ISSUE THREAD

**Issue by caigner** [darktable-org/darktable#12003]
When importing new images or moving them around in the file system via Lua script ("rename images") - variables are very useful.

Unfortunately building a migration path like 

`/mnt/backup2/pictures/$(JOBCODE)/$(EXIF_YEAR)/$(EXIF_MONTH)/$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)/$(FILE_NAME)`

means a lot of typing variable names from memory.

Therefore I suggest some sort of **path build tool**, which allows for a path to be selected from the file system AND darktable variables to be added by selecting them with a mouse click.

**Comment by elstoc** [comment]
How is this different from #11278 (which you also raised)?

**Comment by caigner** [comment]
It's just a different approach to the same problem. DT variables are a wonderful and very useful feature, just the UI could be made a bit more intuitive, especially when the input field is short and you see just part of the whole path. 

In the import module the input field is in fact long enough. But the export module or the lua script 'rename images' would definitely benefit from an extra input window to edit the path. Lets call it a path assembly tool window.

I am sure the developers will come up with an elegant solution to this problem.

**Comment by elstoc** [comment]
Let's stick to the one issue for this then please - just add some comments to #11278.

**Comment by caigner** [comment]
Done. Thanks!
