### ISSUE TITLE
darktable doesn't start on macOS

### ISSUE THREAD

**Issue by maestro4** [darktable-org/darktable#12008]
Hi,

I'm unable to start darktable on macOS (similar to #9966). After a cleanup and a fresh install, I get following:
```bash
(base) [13:47:00] user@Mac: ~/Applications/darktable.app/Contents/MacOS > ./darktable -d all
0.005677 application_directory: /Users/user/Applications/darktable.app/Contents/MacOS
0.006734 darktable.datadir: /Users/user/Applications/darktable.app/Contents/Resources/share/darktable
0.007513 darktable.plugindir: /Users/user/Applications/darktable.app/Contents/Resources/lib/darktable
0.008272 darktable.localedir: /Users/user/Applications/darktable.app/Contents/Resources/share/locale
0.010269 darktable.configdir: /Users/user/.config/darktable
0.011044 darktable.cachedir: /Users/user/.cache/darktable
0.011756 darktable.sharedir: /Users/user/Applications/darktable.app/Contents/Resources/share
0.012468 darktable.tmpdir: /private/var/folders/xc/96z7qww52cndjtlgv14c88840000gp/T
[memory] at startup
[memory] max address space (vmpeak):         unknown
[memory] cur address space (vmsize):     34609104 kB
[memory] max used memory   (vmhwm ):         unknown
[memory] cur used memory   (vmrss ):        13360 kB
0.012582 new_xdg_data_dirs: (null)
```

macOS version: 12.4 (MacBook Pro 15" 2019)
xcode version:
```bash
(base) [13:56:13] user@Mac: ~/Applications/darktable.app/Contents/MacOS > xcodebuild -version
Xcode 13.4
Build version 13F17a
```

darktable installed via homebrew:
```bash
(base) [13:52:27] user@Mac: ~/Applications/darktable.app/Contents/MacOS > brew list --versions |grep darktable
darktable 3.8.1
(base) [13:52:36] user@Mac: ~/Applications/darktable.app/Contents/MacOS > brew info darktable
darktable: 3.8.1
https://www.darktable.org/
/Users/user/software/homebrew/Caskroom/darktable/3.8.1 (136B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/darktable.rb
==> Name
darktable
==> Description
Photography workflow application and raw developer
==> Artifacts
darktable.app (App)
```

darktable version: 3.8.1
```bash
(base) [13:50:41] user@Mac: ~/Applications/darktable.app/Contents/MacOS > ./darktable --version
this is darktable 3.8.1
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Comment by parafin** [comment]
Please try setting ui_last/gui_language to C in ~/.config/darktable/darktablerc

If it doesn't help I don't really see any way to debug this, you will have to just wait for next release or try building darktable yourself.

**Comment by victoryforce** [comment]
You can launch darktable with `LC_ALL=C ./darktable -d all`. This will have the same effect as setting option in darktablerc file.

**Comment by maestro4** [comment]
This has no effect. It hangs at the same position. Do I need to install darktable as an admin user on Mac?

**Comment by apfelkraut** [comment]
@maestro4 what happens if you try to run darktable via Finder? Applications => darktable.app. First try double-click on the app icon. Second try right click on the app icon and select "open".

Did you try a `brew reinstall darktable`?

You normally do not have to install darktable as admin ...

**Comment by yskoono** [comment]
Try these.

`ls -la ~/Library/LaunchAgents`

I solved the problem by deleting `org.freedesktop.dbus-session.plist` in this directory, which I had completely forgotten I had created.

`rm ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist`

After this, darktable.app was successfully launched as if nothing had happened.

**Comment by maestro4** [comment]
> I solved the problem by deleting `org.freedesktop.dbus-session.plist` in this directory, which I had completely forgotten I had created.
> 
> `rm ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist`
> 

This works perfectly, as you said.
