### ISSUE TITLE
Opensuse master repo is not updated for debian or ubuntu

### ISSUE THREAD

**Issue by bdemaistre** [darktable-org/darktable#12014]
Opensuse master repo is not updated for debian or ubuntu 
last update in [http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_22.04/](http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_22.04/) is 30/05
Update are provided only for all other distributions 
for exemple  [http://download.opensuse.org/repositories/graphics:/darktable:/master/openSUSE_Tumbleweed/x86_64/](http://download.opensuse.org/repositories/graphics:/darktable:/master/openSUSE_Tumbleweed/x86_64/) was updated today

I did not found where to report this on the opensuse website but may be it has to come from the darktable team ?
Thank you for the great job

**Comment by Nilvus** [comment]
This repository is a third one (trusted) and we have many times said here and on pixls.us that this repository is not maintained (and so not directly related to darktable team and so Github one). You could ping @asn on pixls.us for that.
Note that darktable 4.0 will be released in about 3 weeks and we have actually only small bugfixes.

**Comment by Nilvus** [comment]
Oh, and usually, new distribs releases support are added with new darktable release. So 22.04 should be added when darktable 4.0 will be out.
