### ISSUE TITLE
color assessment mode - background flashes while zooming

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12010]
When using the color assessment mode, if you attempt to zoom in, the background flashes on each change to the zoom level:

https://user-images.githubusercontent.com/9555491/172725730-6852f688-833c-4efc-b205-5c418e8f0963.mp4

darktable 3.9.0+1729~gd7d49b8fb on ArchLinux

**Comment by elstoc** [comment]
Could this be a CSS issue @Nilvus?

**Comment by Nilvus** [comment]
Probably not. Background on that mode is hardcoded.

**Comment by elstoc** [comment]
You're right - it was a gtk fix
