### ISSUE TITLE
3.9.0 / lut 3D: files is NOT in naming order

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#12025]
The lutd 3D module is not listing the lut files in naming order - look likes random.
![Screenshot from 2022-06-11 16-02-05](https://user-images.githubusercontent.com/57588193/173191096-dbe69919-c988-4f6a-a966-008daaa8c7a0.png)

It was good in 3.8.0 and prev versions.

darktable 3.9.0~git1661.b5d5ad83-1
Ubuntu 22.04

**Comment by MStraeten** [comment]
duplicate to #11560
