### ISSUE TITLE
Shortcut export save dialog displayed behind shortcut editor window (3.8.1 macOS 12.4)

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/darktable#12021]
**Did you buy darktable from an application store ?**
No binaries downloaded from darktable.org, 3.8 (first/clean install) then 3.8.1 

**Describe the bug/issue**
When exporting shortcuts the file save dialog is displayed behind the shortcuts editor window on macOS 12.4. on macOS windowing system the file save dialog position is centered on the window that invokes it, so moving the shortcut window also moves the save dialog, so it can't be uncovered by moving the windows.

**To Reproduce**
1. Open the shortcut editor dialog
2. Click on export button. 
4. Click on export shortcuts dialog OK button
5. file save dialog is displayed behind shortcuts editor window

**Expected behavior**
display file save dialog in front of shortcuts editor window so file name can be edited and saved

**Screenshots**
red highlighted window is macOS save window

**Screencast**

**Which commit introduced the error**
sorry haven't learned or code/git yet. just getting started with dt.

_A bisect is much appreciated and can significantly simplify the developer's job._

**Platform**
* darktable version : 3.8.1 released binaries 
* OS                : OSx 12.4
* Memory            : 64G
* Graphics card     : M1
* Graphics driver   : macOS

**Additional context**
I do have a utility Default Folder X but disabled it and rebooted and was still able to reproduce the problem.

![dt-shortcut-export](https://user-images.githubusercontent.com/105315850/173166715-de7e4271-2c2e-42a6-8af7-dc8ccc0f3414.jpg)

**Comment by MStraeten** [comment]
don't use full screen mode. 
GTK and OSX aren’t best friends ...

**Comment by TiredOfGuessing** [comment]
Thx for the info, this is a trivial workaround, for a likely very difficult incompatibility.
The dialog tracking behavior is an OSX oddity.
