### ISSUE TITLE
Darktable crashes on startup with error message 

### ISSUE THREAD

**Issue by Lacanne** [darktable-org/darktable#12033]
**Did you buy darktable from an application store ?**
I got darktable from github

**Describe the bug/issue**
After downloading Darktable, I tried to open it, but it instantly crashed and an error message popped up. The textfile read:

this is darktable 3.6.1 reporting an exception:

-------------------

Error occurred on Monday, June 13, 2022 at 14:43:06.

darktable.exe caused an Integer division by zero at location 00007FF9BAFFDC39 in module igdrcl64.dll.

AddrPC           Params
00007FF9BAFFDC39 0000000000000000 0000000000000048 000001E3B9E6CBC0  igdrcl64.dll!GTPin_Init
00007FF9BB17AB0C 000001E3BA5287D0 000001E3FFFFFFFF 0000AB67055A75FB  igdrcl64.dll!clGetGLContextInfoKHR
00007FF9BB1062FE 000001E3B9D3DBE0 000001E3B9B9BF60 000001E3B9B9BF60  igdrcl64.dll!clGetGLContextInfoKHR
00007FF9BAFB3623 00000002B7190000 0000005C3A5FE579 0000000000000008  igdrcl64.dll!GTPin_Init
00007FF9BB106D1A 000001E3B8F6C1B0 000001E3B8F6C1B0 000001E3B7190530  igdrcl64.dll!clGetGLContextInfoKHR
00007FF9BB107137 0000000000000000 000001E3B9D3E098 00007FF9BAF70000  igdrcl64.dll!clGetGLContextInfoKHR
00007FF9BAFBDBAA 0000000000000000 0000000000000000 0000000000000000  igdrcl64.dll!GTPin_Init
00007FF9BAFD6F7F 00007FF9BAF70000 0000000000000000 000001E3B9D3DBE0  igdrcl64.dll!GTPin_Init
00007FF9BAFD6EA0 000001E3B9D3DBE0 0000000000000000 000001E3B9DBD680  igdrcl64.dll!GTPin_Init
00007FF9BAFD6BE3 000001E3B9D3DBE0 0000000000000000 0000000000000000  igdrcl64.dll!GTPin_Init
00007FF9BB14B19F 000001E3B9D3DBE0 000001E3B9D3DBE0 0000005C3A5FE789  igdrcl64.dll!clGetGLContextInfoKHR
00007FF9BAFF9C40 000001E3B9B17A30 0000000000000000 0000000000000000  igdrcl64.dll!GTPin_Init
00007FF9BAF87135 0000000000000001 000001E3B8EB3EE2 0000005C3A5FEAF0  igdrcl64.dll!clGetPlatformIDs
00007FF9BAF9B14E 000001E3B8EB3E90 000001E3B8EB3E90 000001E3B8EB3EE2  igdrcl64.dll!clEnqueueTask
00007FF9EF421195 000001E3B8EB3E90 00007FF900000001 00007FF9BAF70000  OpenCL.dll!0x7ff900001195
00007FF9EF423A09 00007FF9EF43DA58 0000000000000000 000001E3B959A230  OpenCL.dll!clWaitForEvents
00007FFA280338B0 000001E3BA04EEF0 0000000000000000 0000005C3A5FF044  ntdll.dll!RtlRunOnceExecuteOnce
00007FFA259FA70B 0000000000000000 0000000000000014 000001E3B95AACE1  KERNELBASE.dll!InitOnceExecuteOnce
00007FF9EF422EEC 0000000000000300 000001E3BA04EEF0 000001E3B956EF90  OpenCL.dll!clGetPlatformIDs
00007FF9DE475D16 0000005C3A5FF650 0000000000000000 0000000000000000  libdarktable.dll!dt_opencl_init
00007FF9DE3D290C 00007FFA00000001 000001E3B8A6FA40 00007FFA00000001  libdarktable.dll!dt_init
00007FF7988B2A39 00007FF7988B1660 0000000000000010 0000000000000000  darktable.exe!0x7ff700002a39
00007FF7988B15B5 000000000000005A 0000000000000000 00007FF7988B7090  darktable.exe!0x7ff7000015b5
00007FF7988B13D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff7000013d4
00007FF7988B1506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff700001506
00007FFA27B87034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFA28042651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.6.1.0
ntdll.dll   	10.0.19041.1741
KERNEL32.DLL	10.0.19041.1741
KERNELBASE.dll	10.0.19041.1741
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
libglib-2.0-0.dll	2.68.3.0
ADVAPI32.dll	10.0.19041.1682
sechost.dll 	10.0.19041.1586
RPCRT4.dll  	10.0.19041.1706
libdarktable.dll
GDI32.dll   	10.0.19041.1620
win32u.dll  	10.0.19041.1741
gdi32full.dll	10.0.19041.1706
msvcp_win.dll	10.0.19041.789
ucrtbase.dll	10.0.19041.789
USER32.dll  	10.0.19041.1503
ole32.dll   	10.0.19041.1202
PSAPI.DLL   	10.0.19041.546
SHELL32.dll 	10.0.19041.1741
combase.dll 	10.0.19041.1741
WS2_32.dll  	10.0.19041.546
libiconv-2.dll	1.16.0.0
libwinpthread-1.dll	1.0.0.0
libgcc_s_seh-1.dll
libstdc++-6.dll
libcairo-2.dll
exchndl.dll 	0.9.2.0
libgdk-3-0.dll	3.24.29.0
libgdk_pixbuf-2.0-0.dll	2.42.4.0
IMM32.dll   	10.0.19041.546
SETUPAPI.dll	10.0.19041.1741
cfgmgr32.dll	10.0.19041.1620
bcrypt.dll  	10.0.19041.1023
libgio-2.0-0.dll	2.68.3.0
SHLWAPI.dll 	10.0.19041.1706
libgobject-2.0-0.dll	2.68.3.0
libharfbuzz-0.dll
lua53.dll
libgtk-3-0.dll	3.24.29.0
comdlg32.dll	10.0.19041.1741
shcore.dll  	10.0.19041.1741
libpangocairo-1.0-0.dll	1.48.5.0
zlib1.dll
libgomp-1.dll
libavif.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.1320
WLDAP32.dll 	10.0.19041.1706
libexiv2.dll
libgmodule-2.0-0.dll	2.68.3.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libpango-1.0-0.dll	1.48.5.0
libGraphicsMagick-3.dll
libicuuc68.dll
libicuin68.dll
libIlmImf-2_5.dll
libpcre-1.dll
libjpeg-8.dll
liblcms2-2.dll
libjson-glib-1.0-0.dll
libopenjp2-7.dll
libpng16-16.dll
libpugixml.dll	1.11.0.0
libsecret-1-0.dll
libsoup-2.4-1.dll
libtiff-5.dll
librsvg-2-2.dll
libsqlite3-0.dll
libxml2-2.dll
libfontconfig-1.dll
MSIMG32.dll 	10.0.19041.1466
libfreetype-6.dll	2.10.4.0
libpixman-1-0.dll
VERSION.dll 	10.0.19041.546
mgwhelp.dll 	0.9.2.0
dwmapi.dll  	10.0.19041.746
gdiplus.dll 	10.0.19041.1706
WINMM.dll   	10.0.19041.546
libcairo-gobject-2.dll
libfribidi-0.dll
DNSAPI.dll  	10.0.19041.1620
libepoxy-0.dll
IPHLPAPI.DLL	10.0.19041.546
libpangowin32-1.0-0.dll	1.48.5.0
libffi-7.dll
USP10.dll   	10.0.19041.546
libgraphite2.dll
COMCTL32.dll	6.10.19041.1110
WINSPOOL.DRV	10.0.19041.1706
libatk-1.0-0.dll	2.36.0.0
libpangoft2-1.0-0.dll	1.48.5.0
libaom.dll
libdav1d.dll	5.1.0.0
rav1e.dll
libcrypto-1_1-x64.dll	1.1.1.11
libidn2-0.dll
libbrotlidec.dll
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libzstd.dll
libssl-1_1-x64.dll	1.1.1.11
libexpat-1.dll
libltdl-7.dll
libexif-12.dll
libbz2-1.dll
libsystre-0.dll
libicudt68.dll
libHalf-2_5.dll
libIlmThread-2_5.dll
libIex-2_5.dll
libImath-2_5.dll
libgcrypt-20.dll	1.9.2.0
libjbig-0.dll
libdeflate.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
USERENV.dll 	10.0.19041.572
dbghelp.dll 	10.0.19041.867
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libtre-5.dll
libthai-0.dll
libgpg-error-0.dll	1.42.0.0
libdatrie-1.dll
CRYPTBASE.DLL	10.0.19041.546
dbgcore.DLL 	10.0.19041.789
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1415
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1741
Wldp.dll    	10.0.19041.1682
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.1620
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1741
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
MSCTF.dll   	10.0.19041.1741
DEVOBJ.dll  	10.0.19041.1620
WINTRUST.dll	10.0.19041.1741
MSASN1.dll  	10.0.19041.546
OpenCL.dll  	2.2.6.0
amdocl64.dll	10.0.3240.6
OPENGL32.dll	10.0.19041.1741
GLU32.dll   	10.0.19041.1741
atiadlxx.dll	27.20.20904.1004
pdh.dll     	10.0.19041.1202
atig6txx.dll	27.20.20904.1004
AppXDeploymentClient.dll	10.0.19041.1620
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.1741
Windows.FileExplorer.Common.dll	10.0.19041.1741
iertutil.dll	11.0.19041.1741
mssprxy.dll 	7.0.19041.1741
amdocl12cl64.dll	0.8.0.0
amd_comgr.dll
igdrcl64.dll	23.20.100.7757
dxgi.dll    	10.0.19041.1741
igdgmm64.dll	26.20.100.7757
TextShaping.dll
textinputframework.dll	10.0.19041.1741
CoreUIComponents.dll	10.0.19041.546
CoreMessaging.dll	10.0.19041.746
ntmarta.dll 	10.0.19041.546
wintypes.dll	10.0.19041.1682
mrmcorer.dll	10.0.19041.1566
windows.staterepositorycore.dll	10.0.19041.1466
bcp47mrm.dll	10.0.19041.1503
Windows.UI.dll	10.0.19041.746
WindowManagementAPI.dll
InputHost.dll	10.0.19041.1741

Windows 10.0.19044
DrMingw 0.9.2

**Platform**

* darktable version :3.6.1
* OS : Windows 10
* Memory            : 117gb
* Graphics card     :  Intel inside i5
* Graphics driver   : Intel R hd graphics 5500 / AMD radeon r7 m260x
* OpenCL installed  : unknown 
* OpenCL activated  : unknown
* Xorg              : unknown
* Desktop           : Laptop
* GTK+              : uknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
I have tried several versions of darktable, but the issue remains.
I have used the program before on other laptops successfully. 

I do not know a lot about computers. Would be awesome if a smart guy could help me with how to solve this.

Cheers.

**Comment by Nilvus** [comment]
First try to install older version of intel graphics driver. Or update it if you don't last version.

To disable opencl, add --disable-opencl to darktable launcher (after darktable.exe command, with a space between).

If you need more infos, search disable-opencl here on issues page or darktable manual

**Comment by Lacanne** [comment]
Rolling back intel graphics didn't work. What about amd?

**Comment by ptilopteri** [comment]
turn off opencl as desctibed above
