### ISSUE TITLE
Tags don't show in the tree with matching tag

### ISSUE THREAD

**Issue by atomikdg** [darktable-org/darktable#12031]
When I want to search for a tag, like "wa%" and hit enter nothing shows in the tree below. (But the images in lighttable are the correct one)
See below screenshot + video

![image](https://user-images.githubusercontent.com/68707745/173248991-f4be2172-241c-4a01-9f1f-3a08f638ce58.png)
[The video](https://nx22856.your-storageshare.de/s/YkarAZ6WsHt3PMY)

Darktable version: darktable master at version 6e25214
OS: Linux opensuse Tumbleweed

**Comment by phweyland** [comment]
Idem for folder, geotags, ...
A doubt though. Is it better to expand every matching record or only the first one (faster) and let the user expand the others manually ?

**Comment by atomikdg** [comment]
> Idem for folder, geotags, ... A doubt though. Is it better to expand every matching record or only the first one (faster) and let the user expand the others manually ?

The patch you made correct the problem for me
