### ISSUE TITLE
After switch window-focus darktable stops responding to kbd-shortcuts

### ISSUE THREAD

**Issue by rand00** [darktable-org/darktable#12038]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
After switching focus between windows, darktable stops responding to kbd-shortcuts - e.g. 'f' for fullscreen

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

darktable version : 3.8.1
OS : Linux 5.18.3-arch1-1
Linux - Distro : Arch Linux
Memory : 16Gb
Graphics card : Geforce GTX 970
Graphics driver : nvidia 515.48.07-9

**Additional context**
I use a tiling window manager: StumpWM. This problem is unique to darktable, and it worked in earlier versions of darktable

**Comment by Nilvus** [comment]
Quite probably related to your other issue: #12037. Both are keyboard related and I fear that such issues will be hard to fix. It's not even sure it's completely related to darktable (or not directly at least, even if it works on 3.8.0 and not after). See what I answer and links on your first issue. I close this one and let you copy/paste on your first issue.

Note that this also could be related to darktable and how StumpWM works for keyboard shortcuts. And it's a quite unusual desktop environment. darktable works great, even for keyboard, on 3.8.1 and actual master, on all mains destktop environment (Gnome, KDE and XFCE at least, as far as I know).

**Comment by Nilvus** [comment]
@AlicVB: do you think I'm right saying that it could probably be related to select issues (i think about that because of keyboard shortcuts and so specific and rare issues they are)? If needed, I could reopen that one.
