### ISSUE TITLE
Unhandled exception error after exporting

### ISSUE THREAD

**Issue by loopybutter** [darktable-org/darktable#12043]
I've been having this issue for the past couple of weeks. It used to only do it after every couple of exports but now it is after every export. the backtrace is listed below. Any help or advice is appreciated :)

this is darktable 3.8.1 reporting an exception:

-------------------

Error occurred on Tuesday, June 14, 2022 at 19:02:59.

darktable.exe caused an Access Violation at location 00007FFE399E05CF in module libdarktable.dll Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00007FFE399E05CF 0000005A755FCEE0 00007FFE8BB138D7 0000000000000000  libdarktable.dll!dt_gui_quit_callback
00007FFE5FB0719E 000001E2ACCDFA20 00007FFEB57A99FD 00000000026D012F  libgobject-2.0-0.dll!g_closure_invoke
00007FFE5FB19208 000001E23BEE93F0 000001E200000493 000001E2524AA8E0  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFE5FB1EF44 000001E2524AA8E0 000001E2ACCD86D0 000001E200000493  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFE5FB1F3A8 0000000000000000 0000005A755FD238 0000005A755FD2B0  libgobject-2.0-0.dll!g_signal_emit
00007FFE5FB0B233 000001E2524AA850 0000000000000000 000001E2AC48A880  libgobject-2.0-0.dll!g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv
00007FFE29DC223A 0000000000000000 0000000000000039 0000000000000000  libgtk-3-0.dll!gtk_action_bar_new
00007FFE5FB0AA1A 0000000000000000 0000000000000000 0000005A755FD540  libgobject-2.0-0.dll!g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv
00007FFE5FB0D503 0000000000000000 0000000000000000 0000000000000000  libgobject-2.0-0.dll!g_object_thaw_notify
00007FFE29E2D6D3 000001E252783020 00007FFE5FB26E46 00000000FFFFFFFF  libgtk-3-0.dll!gtk_container_get_path_for_child
00007FFE29E3202A 0000005A755FD64C 000001E200000023 000001E200000036  libgtk-3-0.dll!gtk_style_properties_lookup_property
00007FFE2A04C153 000001E252315B60 0000000000000000 000001E252269B70  libgtk-3-0.dll!gtk_volume_button_new
00007FFE2A05A4AE 0000005A755FD71C 00007FFE2A05333A 00000000FFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE29F8AAA0 0000000000000000 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_scrolled_window_get_type
00007FFE29E2D6D3 000001E23DE9A7F0 00007FFE5FB26E46 0000000000000000  libgtk-3-0.dll!gtk_container_get_path_for_child
00007FFE29E3202A 0000005A00000036 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_style_properties_lookup_property
00007FFE29F86A1C 0000000000000004 00007FFE3F21C077 000000000000000C  libgtk-3-0.dll!gtk_scrollbar_new
00007FFE2A05A4AE 0000000000000000 0000005A755FDED0 00000000FFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE29DDAD56 000001E2523149E0 0000005A755FDD30 00000000FFFFFFFF  libgtk-3-0.dll!gtk_border_get_type
00007FFE29DDB02D 0000000000000000 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_border_get_type
00007FFE29E2D6D3 0000000000000000 0000000000000001 0000000000000001  libgtk-3-0.dll!gtk_container_get_path_for_child
00007FFE29E3202A 0000005A00000000 0000000000000900 0000005A755FDEBC  libgtk-3-0.dll!gtk_style_properties_lookup_property
00007FFE29DD9A29 0000005A755FE0C0 00007FFE3F21BEEF 0000005A755FDF70  libgtk-3-0.dll!gtk_border_get_type
00007FFE2A05A4AE 0000000000000004 00007FFE3F21C077 00000000FFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE29DD4E3E 000001E23BFED8B0 00007FFE3F267A76 0000000000000000  libgtk-3-0.dll!gtk_button_box_set_child_non_homogeneous
00007FFE29F31D0A 000001E2524A52B0 0000005A755FE370 000001E252309E40  libgtk-3-0.dll!gtk_orientable_set_orientation
00007FFE2A05A4AE 0000000000000576 0000000000000004 0000005AFFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE29EBD8D6 0000000000000000 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_grid_get_row_baseline_position
00007FFE29E2D6D3 0000000000000001 000001E2524A52B0 00000000FFFFFFFF  libgtk-3-0.dll!gtk_container_get_path_for_child
00007FFE29E3202A 0000005A755FE640 000001E2524A51C0 0000000000000F01  libgtk-3-0.dll!gtk_style_properties_lookup_property
00007FFE29EBB659 0000000000000004 00007FFE3F21C077 000000000000000C  libgtk-3-0.dll!gtk_gl_area_attach_buffers
00007FFE2A05A4AE 0000000000000000 0000005A755FEAE0 00000000FFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE29DDAD56 000001E2524A5140 0000005A755FE940 00007FFE3F3074D8  libgtk-3-0.dll!gtk_border_get_type
00007FFE29DDB02D 0000000000000000 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_border_get_type
00007FFE29E2D6D3 0000000000000000 0000000000000001 0000000000000001  libgtk-3-0.dll!gtk_container_get_path_for_child
00007FFE29E3202A 0000005A00000000 00007FFE5FB059A0 0000005A755FEAD0  libgtk-3-0.dll!gtk_style_properties_lookup_property
00007FFE29DD9A29 000001E2954DF560 00007FFE5FB26E46 0000005A755FEB00  libgtk-3-0.dll!gtk_border_get_type
00007FFE2A05A4AE 0000005A755FEC64 000001E2524A5140 00000000FFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE2A07106B 0000000000000000 0000000000000000 0000005A755FED78  libgtk-3-0.dll!gtk_window_reshow_with_initial_size
00007FFE5FB0719E 000001E2522BFCD0 00007FFE00000278 0000027800000278  libgobject-2.0-0.dll!g_closure_invoke
00007FFE5FB18EB2 000001E23E096D00 000001E200000000 000001E2522BFCD0  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFE5FB1EF44 000001E2522BFCD0 0000000000000F00 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFE5FB1F3A8 0000000000000A00 000001E2522BFA70 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00007FFE2A05A821 0000005A755FF110 0000000000000000 00000000FFFFFFFF  libgtk-3-0.dll!gtk_widget_size_allocate_with_baseline
00007FFE2A0719AC 0000005A755FF728 000001E25231A130 000000E8EDB413D8  libgtk-3-0.dll!gtk_window_propagate_key_event
00007FFE5FB073B3 0000000000000000 000001E2523158B0 000000E8EDB413D8  libgobject-2.0-0.dll!g_closure_invoke
00007FFE5FB1F251 000001E2522BFCD0 00007FFE29E263CC 0000005A00000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFE5FB1F3A8 0000000000000000 00000000000000FB 0000000000000002  libgobject-2.0-0.dll!g_signal_emit
00007FFE29E265C0 00000000000000FB 00007FFE5FB0BB1D 0000000000000000  libgtk-3-0.dll!gtk_container_check_resize
00007FFE5FB073B3 0000005A755FF570 0000000000000000 0000000000000000  libgobject-2.0-0.dll!g_closure_invoke
00007FFE5FB1F251 000001E23DEA1260 00007FFE3B547A2C 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFE5FB1F3A8 000001E29AF42280 0000000000000000 00007FFE3F27B4C0  libgobject-2.0-0.dll!g_signal_emit
00007FFE3B548A9A 000001E2959C2CE0 0000000000000006 00009531782D1DE0  libgdk-3-0.dll!gdk_frame_clock_get_refresh_info
00007FFE3B5333A2 000001E23BF79F80 00007FFE3F267A76 0000000000000002  libgdk-3-0.dll!gdk__private__
00007FFE3F20C995 000001E23BF6C140 00007FFE3F20BB20 0000000000000000  libglib-2.0-0.dll!g_source_get_time
00007FFE3F208D47 00007FFE00000002 0000005A755FF8D8 000001E23BF3D9D0  libglib-2.0-0.dll!g_clear_list
00007FFE3F20BEDE 0000005A755FFA30 00007FFE3F22BD06 0000000000000000  libglib-2.0-0.dll!g_main_context_check
00007FFE3F20C3FC 0000000000000000 0000000000000000 00007FFE39D1D0C0  libglib-2.0-0.dll!g_main_loop_run
00007FFE29F0082D 0000000000000000 00007FF7382A4030 000001E23BEF0D80  libgtk-3-0.dll!gtk_main
00007FFE399E2B2C 00007FFE00000001 000001E23BF3D9D0 000001E200000001  libdarktable.dll!dt_gui_gtk_run
00007FF7382A2B47 00007FF7382A1660 0000000000000010 0000000000000000  darktable.exe!0x7ff700002b47
00007FF7382A15B5 000000000000005A 0000000000000000 0000000000000000  darktable.exe!0x7ff7000015b5
00007FF7382A13D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff7000013d4
00007FF7382A1506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff700001506
00007FFEB37954E0 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFEB578485B 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.8.1.0
ntdll.dll   	10.0.22000.653
KERNEL32.DLL	10.0.22000.675
KERNELBASE.dll	10.0.22000.675
msvcrt.dll  	7.0.22000.1
libintl-8.dll	0.21.0.0
ADVAPI32.dll	10.0.22000.653
libglib-2.0-0.dll	2.70.3.0
sechost.dll 	10.0.22000.556
ole32.dll   	10.0.22000.120
libiconv-2.dll	1.16.0.0
RPCRT4.dll  	10.0.22000.675
msvcp_win.dll	10.0.22000.1
libdarktable.dll
ucrtbase.dll	10.0.22000.1
GDI32.dll   	10.0.22000.1
win32u.dll  	10.0.22000.675
USER32.dll  	10.0.22000.282
gdi32full.dll	10.0.22000.675
combase.dll 	10.0.22000.653
PSAPI.DLL   	10.0.22000.1
SHELL32.dll 	10.0.22000.593
WS2_32.dll  	10.0.22000.1
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libgcc_s_seh-1.dll
libcairo-2.dll
libstdc++-6.dll
exchndl.dll 	0.9.3.0
libgdk-3-0.dll	3.24.31.0
libgdk_pixbuf-2.0-0.dll	2.42.6.0
IMM32.dll   	10.0.22000.1
libgobject-2.0-0.dll	2.70.3.0
SETUPAPI.dll	10.0.22000.469
libgio-2.0-0.dll	2.70.3.0
SHLWAPI.dll 	10.0.22000.1
libpango-1.0-0.dll	1.50.3.0
lua54.dll
libpangocairo-1.0-0.dll	1.50.3.0
libgtk-3-0.dll	3.24.31.0
zlib1.dll
libgomp-1.dll
libavif.dll
libcurl-4.dll
CRYPT32.dll 	10.0.22000.348
libgmodule-2.0-0.dll	2.70.3.0
WLDAP32.dll 	10.0.22000.675
libexiv2.dll
comdlg32.dll	10.0.22000.527
shcore.dll  	10.0.22000.613
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libheif.dll
libicuuc69.dll
libIlmImf-2_5.dll
libicuin69.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
libopenjp2-7.dll
libpng16-16.dll
libpugixml.dll	1.11.0.0
librsvg-2-2.dll
libsecret-1-0.dll
libsoup-2.4-1.dll
libtiff-5.dll
libxml2-2.dll
libsqlite3-0.dll
libfreetype-6.dll	2.11.1.0
libfontconfig-1.dll
MSIMG32.dll 	10.0.22000.1
libpixman-1-0.dll
mgwhelp.dll 	0.9.3.0
VERSION.dll 	10.0.22000.1
HID.DLL     	10.0.22000.1
dwmapi.dll  	10.0.22000.41
gdiplus.dll 	10.0.22000.675
libffi-7.dll
WINMM.dll   	10.0.22000.1
libcairo-gobject-2.dll
libfribidi-0.dll
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.50.3.0
DNSAPI.dll  	10.0.22000.653
IPHLPAPI.DLL	10.0.22000.282
libthai-0.dll
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.50.3.0
libdav1d.dll	5.1.1.0
rav1e.dll
libaom.dll
COMCTL32.dll	6.10.22000.120
libbrotlidec.dll
libidn2-0.dll
libcrypto-1_1-x64.dll	1.1.1.13
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libexpat-1.dll
libssl-1_1-x64.dll	1.1.1.13
libzstd.dll
libltdl-7.dll
libexif-12.dll
WINSPOOL.DRV	10.0.22000.675
libatk-1.0-0.dll	2.36.0.0
libsystre-0.dll
libbz2-1.dll
libde265-0.dll
libHalf-2_5.dll
libIex-2_5.dll
libx265.dll 	3.4.0.31
libIlmThread-2_5.dll
libicudt69.dll
libImath-2_5.dll
bcrypt.dll  	10.0.22000.1
USERENV.dll 	10.0.22000.1
libgcrypt-20.dll	1.10.0.0
libdeflate.dll
libjbig-0.dll
libLerc.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
dbghelp.dll 	10.0.22000.1
libdatrie-1.dll
DWrite.dll  	10.0.22000.258
USP10.dll   	10.0.22000.1
libgraphite2.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libtre-5.dll
libgpg-error-0.dll	1.44.0.0
dbgcore.DLL 	10.0.22000.1
CRYPTBASE.DLL	10.0.22000.1
bcryptPrimitives.dll	10.0.22000.376
CRYPTSP.dll 	10.0.22000.1
rsaenh.dll  	10.0.22000.282
NSI.dll     	10.0.22000.1
windows.storage.dll	10.0.22000.675
wintypes.dll	10.0.22000.527
mswsock.dll 	10.0.22000.1
winhttp.dll 	10.0.22000.1
KBDUS.DLL   	10.0.22000.1
KBDJPN.DLL  	10.0.22000.1
uxtheme.dll 	10.0.22000.120
AudioDevProps2.dll	2.6.15.0
DEVOBJ.dll  	10.0.22000.1
cfgmgr32.dll	10.0.22000.1
MSCTF.dll   	10.0.22000.527
WINTRUST.dll	10.0.22000.653
MSASN1.dll  	10.0.22000.1
kernel.appcore.dll	10.0.22000.71
clbcatq.dll 	2001.12.10941.16384
OpenCL.dll  	3.0.1.0
dxcore.dll  	10.0.22000.653
AppXDeploymentClient.dll	10.0.22000.469
urlmon.dll  	11.0.22000.653
iertutil.dll	11.0.22000.653
netutils.dll	10.0.22000.434
srvcli.dll  	10.0.22000.613
nvopencl64.dll	30.0.14.7256
cryptnet.dll	10.0.22000.1
drvstore.dll	10.0.22000.120
wldp.dll    	10.0.22000.653
nvapi64.dll 	30.0.14.7256
nvcompiler64.dll	30.0.14.7256
Windows.ApplicationModel.dll	10.0.22000.593
OLEAUT32.dll	10.0.22000.1
propsys.dll 	7.0.22000.37
profapi.dll 	10.0.22000.1
mssprxy.dll 	7.0.22000.593
IconCodecService.dll	10.0.22000.1
WindowsCodecs.dll	10.0.22000.653
mrmcorer.dll	10.0.22000.120
windows.staterepositorycore.dll	10.0.22000.65
windows.staterepositoryclient.dll	10.0.22000.653
bcp47mrm.dll	10.0.22000.65
Windows.UI.dll	10.0.22000.1
libpixbufloader-png.dll
mscms.dll   	10.0.22000.469
icm32.dll   	10.0.22000.469
textinputframework.dll	10.0.22000.282
CoreMessaging.dll	10.0.22000.71
CoreUIComponents.dll	10.0.22000.132
uiautomationcore.dll	7.2.22000.653
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libavif.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libxcf.dll
libdisk.dll
libemail.dll
libgallery.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libblurs.dll
libborders.dll
libcacorrect.dll
libcacorrectrgb.dll
libcensorize.dll
libchannelmixer.dll
libchannelmixerrgb.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorbalancergb.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libcrop.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdiffuse.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libgmic.dll
libGraphicsMagick++-12.dll
libfftw3-3.dll
libopencv_videoio452.dll	4.5.2.0
libopencv_core452.dll	4.5.2.0
libopencv_imgcodecs452.dll	4.5.2.0
libopencv_imgproc452.dll	4.5.2.0
tbb.dll
OPENGL32.dll	10.0.22000.653
libopenblas.dll
GLU32.dll   	10.0.22000.653
libgfortran-5.dll
libquadmath-0.dll
libmask_manager.dll
libmonochrome.dll
libnegadoctor.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgamepad.dll
SDL2.dll    	2.0.20.0
dinput8.dll 	10.0.22000.1
inputhost.dll	10.0.22000.168
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
libioporder.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_locations.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmidi.dll
libportmidi.dll
winmmbase.dll	10.0.22000.1
MMDevAPI.DLL	10.0.22000.1
wdmaud.drv  	10.0.22000.1
ksuser.dll  	10.0.22000.1
AVRT.dll    	10.0.22000.675
AUDIOSES.DLL	10.0.22000.348
msacm32.drv 	10.0.22000.653
MSACM32.dll 	10.0.22000.1
midimap.dll 	10.0.22000.1
libmodulegroups.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
OLEACC.dll  	7.2.22000.1
ProductInfo.dll	1.9.8.0
ASM.Plugin.AudioDevProps2.dll	1.0.1.0
libpixbufloader-svg.dll
threadpoolwinrt.dll	10.0.22000.1
Ninput.dll  	10.0.22000.1
explorerframe.dll	10.0.22000.593
TextShaping.dll

Windows 10.0.22000
DrMingw 0.9.3

**Comment by phweyland** [comment]
A lot of windows issues are related to path/filename special characters...
What are the path/filenames of your raw files and exported ones ?

**Comment by loopybutter** [comment]
> 

I'm not super knowledgeable in terms of computer file stuff but from what I found online, my path/filenames for my exported files are C:\Users\sugar\OneDrive\Pictures\Photoshoots\edit DARKTABLE  and my path/filename for my raw files are C:\Users\sugar\OneDrive\Pictures\Photoshoots
I hope I did that right and if I didn't please let me know!

**Comment by victoryforce** [comment]
That is, judging by the name of the folder in your path, it looks like your image files are exported to the folder that has something to do with the OneDrive cloud and is probably under the control of this cloud's sync utility.

Is there still a problem if you export files to other folders not under C:\Users\sugar\OneDrive ?

**Comment by kmilos** [comment]
> > C:\Users\sugar\OneDrive\Pictures\Photoshoots\edit DARKTABLE

Avoid spaces in file and folder names as well whenever possible.
