### ISSUE TITLE
Update exposure default

### ISSUE THREAD

**Issue by Egocentrix** [darktable-org/darktable#12044]
In his fork @aurelienpierre has changed the defaults for the exposure and filmic modules:
https://github.com/aurelienpierre/R-Darktable/commit/60bbf83ac5de291344923861aaec464f29879209

Should they be changed in dt as well?

**Comment by MStraeten** [comment]
be patient, it‘ll find it’s way into master too - but since 4.0 is about to be finalised there’s no hurry for further changes yet…

**Comment by dterrahe** [comment]
This has now landed in master too https://github.com/darktable-org/darktable/commit/9a82b2f1584626684142e3b441a631ded2a9f467
