### ISSUE TITLE
darktable crashes when deleting styles

### ISSUE THREAD

**Issue by stephanh73** [darktable-org/darktable#12057]
When I import styles and want to delete them again before restarting darktable, darktable crashes. When I import a style I first have to restart darktable again before I can delete that style. I'm using the latest unstable release.

**Comment by TurboGit** [comment]
Should be fixed now. Thanks for reporting, just in time for 4.0.

**Comment by stephanh73** [comment]
It works great now. When will 4.0 be released?

**Comment by TurboGit** [comment]
Should be very early on July.
