### ISSUE TITLE
Rating filter in darkroom doesn't affect images in filmstrip

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#12051]
the filmstrip displayed in darkroom is populated according to the filter applied in lighttable.
changing the rating filter in darkroom doesn't have an effect on the filmstrip.

![image](https://user-images.githubusercontent.com/39386816/174064473-3a081a05-b808-4e5f-afe1-ba39c8a8df9e.png)
first 5 images are rated 1,2,3,4,5 stars 6th image is rejected

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. im lighttable rate a copule of images in a different way
2. filter for all images
3. switch to darkroom
4. change rating filter
5. nothing happens in filmstrip

**Platform**
* darktable version : darktable-3.9.0+1747~g6e2521410
* OS                : OSx

**Comment by gi-man** [comment]
I can reproduce. Even switching to the lighttable doesn't affect it until I change the rating filter again. 

Win11 3.9.0+1752~g2c67b60d9

**Comment by AlicVB** [comment]
should be fixed in PR #12053 Thanks for the report !
