### ISSUE TITLE
Automatic base curve not working

### ISSUE THREAD

**Issue by zygmund2000** [darktable-org/darktable#12060]
Hi

I have some question, how to disable automatic filmic rgb and exposure for avery new raw file and enable again custom base curve?
I have preset for my base curve for Sony A58 but it's not working automaticly.
![dt](https://user-images.githubusercontent.com/14185298/174426912-653bd6f5-e6dd-41a7-b2e7-e6d62fad15b4.png)

**Comment by pehar1** [comment]
https://darktable-org.github.io/dtdocs/en/preferences-settings/processing/, scene-referred workflow / display-referred workflow

**Comment by stephanh73** [comment]
When you go to preferences > processing and set "auto-apply pixel workflow defaults" to  display-referred, "auto-apply chromatic adaption  defaults" to legacy. Then check "auto-apply per camera basecurve presets. Now the filmic rgb module won't be set automatically and after importing a image your base curve will me loaded.

**Comment by Nilvus** [comment]
For help support, pixls.us forum is better. Here it's about bugs or feature request. Thanks.
