### ISSUE TITLE
script_manager.lua:427: attempt to concatenate a nil value (local 'category')

### ISSUE THREAD

**Issue by manu-p** [darktable-org/darktable#12070]
**Describe the bug/issue**

dt 3.8.1 / Ubuntu 20.04.4

Trying to install and enable script_manager as described [here](https://docs.darktable.org/lua/stable/lua.scripts.manual/installation/), I get the following error:
`script_manager.lua:427: attempt to concatenate a nil value (local 'category')`

**To Reproduce**

1. cd ~/.config/darktable/
2. git clone https://github.com/darktable-org/lua-scripts.git lua
3. echo 'require "tools/script_manager"' > ~/.config/darktable/luarc
4. /usr/bin/darktable -d lua
5. see error message: `5,114164 LUA ERROR : /home/manu/.config/darktable/lua/tools/script_manager.lua:427: attempt to concatenate a nil value (local 'category')`
6. dt is running fine, but without script manager

**Expected behavior**

No error message and script manager enabled in dt.

**Platform**

* darktable version : 3.8.1-1.1
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04.4 LTS
* Memory            : 14Go
* Graphics card     : nVidia GK107GLM [Quadro K1000M]
* Graphics driver   : 340
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Comment by wpferguson** [comment]
The easiest way to install the lua scripts is to let darktable do it.

Remove the ~/.config/darktable/luarc file and the ~/.config/darktable/lua directory, then restart darktable and use the lua-scripts installer at the bottom of the left panel in lighttable.

**Comment by manu-p** [comment]
Thanks @wpferguson, indeed, an old version of luarc and lua folder already existed...
