### ISSUE TITLE
separator between thumbs on filmstrip

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12071]
Maybe not really a bug, but something that I think we could really make visually better. I have always found that the separation on the filmstrip between the thumbs are not really easy to see:

![image](https://user-images.githubusercontent.com/467069/174476248-be20313d-9a37-483d-84a6-54f10d24dc32.png)

We have a very thin line between the thumbs, but I think it would be nice to have this separator a bit thicker.

**Comment by TurboGit** [comment]
@Nilvus : Do you think there is an easy and safe fix possible for 4.0 as it would be a nice adds to 4.0 polishing? If not it can wait for 4.0.1.

**Comment by Nilvus** [comment]
I will see that in following week. I update labels, it's indeed not a bug

**Comment by TurboGit** [comment]
I would say that the borders are OK now, more visible yet:

![image](https://user-images.githubusercontent.com/467069/175871051-a8272777-5f78-448e-a5cc-71566f35792e.png)

But as you can see the issue seems that when the thumbs are small the actual picture overlap with the border making it not well defined, see zoomed area:

![image](https://user-images.githubusercontent.com/467069/175871421-72216676-d712-4135-ba9a-cc10a2fc0fb2.png)

**Comment by Nilvus** [comment]
I've seen that last issue but will be hard to fix. It's only when thumbnails are small and it's padding related thing. But increasing this will be bad for bigger sizes. So, not something to fix actually (not for 4.0.1). Maybe, when I will work on thumbnails for 4.2, I will find something better.
