### ISSUE TITLE
color picker is reading RGB 280-280-280 on a black and white jpg

### ISSUE THREAD

**Issue by FernChaves** [darktable-org/darktable#12079]
Hello,

The color picker is reading RGB 280-280-280 on a black and white jpg photo. I get the same numbers, bigger  than 255, on tiff, dng, cr2 files in color and black white. Is this normal?
![color-picker-reading-280-on-jpg-pic](https://user-images.githubusercontent.com/107567557/174675038-3cc5a4d8-8b0f-4e35-b404-2086405a8e5d.jpg)

As I increase the exposure slider to, say, +0.50EV the RGB reading goes 358-358-358.

Best regards,
Fernando Chaves

**Comment by pehar1** [comment]
Please read the manual : https://darktable-org.github.io/dtdocs/en/special-topics/color-pipeline/
keywords : scene-referred workflow, unbounded pixel values

**Comment by ValZapod** [comment]
This is like Photoshop info panel, that gives underlying values before any color managment. If you want colors after color managment, that is in display space, use an external color picker.
