### ISSUE TITLE
darktable crashes on windows 10 after windows update

### ISSUE THREAD

**Issue by cerlienkus** [darktable-org/darktable#12073]
Hi,
I'm running darktable 3.8.1 on Windows 10. 
It was running perfectly after I performed a Windows update.
Now, after opening it reports an unhandled exception:

![Immagine 2022-06-19 125903](https://user-images.githubusercontent.com/69572937/174477985-b4b28359-badf-43c0-bce2-62d1e2f2e49e.png)

After clicking OK, darkatable closes.
I'm sending a backtrace file as suggested.

[darktable_bt_41OLN1.txt](https://github.com/darktable-org/darktable/files/8935240/darktable_bt_41OLN1.txt)

I'm running Windows 10, Home Edition
Version 21H2 (Build SO 19044.1766).

Is there a way to have dt working again without reverting to the previous version of Windows?
I've also tried reinstalling it!
Thanks in advance.

Maurizio Cerlienco

**Comment by MStraeten** [comment]
check if you have opencl compatibility package installed with that update.
if so you have to uninstall that or wait until microsoft fixes a well known issue. (more info in https://github.com/darktable-org/darktable/issues/10767)

**Comment by cerlienkus** [comment]
Hi and thanks,
I've checked and apparently it wasn't installed. I've installed as a try and the error described in issue #10767 was reproduced.
After uninstalling the package I've got back the issue reported in the backtrace file I've sent: 

"darktable.exe caused an Access Violation at location 00007FFBE3E643CF in module msvcrt.dll Reading from location 0000000000000000."

I believe it's another issue related to the update...

I think I'll revert to the disk image I've saved last sunday to get back working with dt...

Maurizio

**Comment by gi-man** [comment]
I dont think this is an OpenCL issue. The module that fails is: Visual C++ Redistributable for Visual Studio 

Do you have an antivirus running? What was the windows update that cause the issue?

**Comment by gi-man** [comment]
Try excluding darktable from the antivirus. You can also try the development branch of darktable. I'm not sure what is going on.

**Comment by cerlienkus** [comment]
Hello,
to temporarily fix the issue, I've reverted to the disk image I've saved last 12th of june, one week before the OS update.
No tweaking with the antivirus and darktable is working fine.

**Comment by TurboGit** [comment]
> to temporarily fix the issue, I've reverted to the disk image I've saved last 12th of june

The final fix is to move to GNU/Linux :)

**Comment by cerlienkus** [comment]
Hi!
I'm back with a new update for the bug.
Now I'm working with a pre windows update disk image.
Today I've downloaded a raw  image to practice a bit and copied it in a test folder with some other edited images and other new to be added to library.
When I tried to add the new images darktable crashed with the same messages and error I uploaded last Sunday.
I deleted the test folder with all images, opened darkatable (wich didn't crashed this i time), deleted every image and xmp file from that folder (the folder name was barred).
I created a new test folder with a new image and added it to library with no crash.
I'm wondering if darktable has encountered some discrepancies in its database, wich hasn't been able to resolve (generating the error) because it needed to be refreshed.
What can I try?
I hope I was clear in the description of the events.
Thanks in advance.

Maurzio

**Comment by gi-man** [comment]
I sure dont understand the events. You will need to post the darktable log to see if someone can help. Make sure you dont have spaces/weird characters in your image filenames and avoid using Library folders (use the real address: C:\...) 

The new version (to be release soon) of darktable did fix some issues with filenames and such. You are free to try the new version if you want to.

**Comment by cerlienkus** [comment]
> I sure dont understand the events. You will need to post the darktable log to see if someone can help. Make sure you dont have spaces/weird characters in your image filenames and avoid using Library folders (use the real address: C:...)
> 
> The new version (to be release soon) of darktable did fix some issues with filenames and such. You are free to try the new version if you want to.

Hi, it was unclear for me too.
I suppose the problem is related to a kind of database corruption.
I will try to obtain a log of events and provide it as soon as the issue occurs again.
Thanks.
