### ISSUE TITLE
Map view goes outside of map bounds

### ISSUE THREAD

**Issue by pbb72** [darktable-org/darktable#12089]
Darktable 3.8.1 on Windows 10, the problem is the same with all map sources.

The map module displays a map inside the coordinates between 85 N and 85 S vertically, and between 180 W and 180 E horizontally. However, the canvas on which the map is displayed, goes from 90 N to 90 S vertically, and seems to be unlimited horizontally. (I tested beyond 10.000 deg East, which is utter nonsense.)

This causes various problems with panning and zooming. I regularly "loose" the map, just being lost on a white canvas. Zooming behaves erratically here also, sometimes not allowing to zoom out further than 100m.

The map display should *not* allow to pan outside the map bounds. Panning should be restricted between 85N/85S/180W/180E.

**Comment by johnny-bit** [comment]
Patches to osm-gps-map welcome. I'm swamped at work but that limit might pose a challenge as we need to be able to see past 180deg boundary, especially useful for travellers.

**Comment by pbb72** [comment]
@johnny-bit I agree with your point. I think the map (and any markers on it) should be repeated when one goes beyond the 180deg boundary. And ideally, the longitude should flip between East and West, and count down, instead of just continuing counting up.

If I could write C, I could contribute with patches. Regrettably, bugreports is the only way I can contribute.

**Comment by Nilvus** [comment]
I close this as an upstream issue. If needed, you could post it on https://github.com/nzjrs/osm-gps-map/issues
