### ISSUE TITLE
"tune OpenCL performance" preference tooltip is incorrect

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12084]
The original intention of the "tune OpenCL performance" preference, when "memory size" is selected, was for dartkable to auto-detect available memory. Due to issues with recent Nvidia drivers, this option now instead implements a headroom of 400MB and does not do any auto-detection, by default.

However, the tooltip still states "tests for available graphics ram". I have corrected the user manual to reflect the actual functionality but raising this so that, if the underlying issue is not fixed for 4.0.1, at least the tooltip can be.

Note that we will not create a new version of the documentation for 4.0.1 (due to difficulty of providing translations in a separate branch) so if this functionality is changed for 4.0.1, the documentation will no longer be correct.

**Comment by TurboGit** [comment]
@jenshannoschwalm : Do you think this will be fixed for 4.0.1 or should we fix the tooltip? TIA.

**Comment by jenshannoschwalm** [comment]
I think we have to change the tool tip. Will work on this for 4.2

**Comment by TurboGit** [comment]
Thanks for the feedback, tooltip fixed.
