### ISSUE TITLE
Darktable stopping when ty try to export a picture.

### ISSUE THREAD

**Issue by cherob67** [darktable-org/darktable#12097]
I report a systematic shutdown of Darktable when I try to export a picture. I attach the xmp file of the picture, the information collected during the shutdown (redirection of information to a text file). Darkatble version is darktable 3.9.0~git1797.387e0553-1).

the xmp:
[_MG_9552_01.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/9017398/_MG_9552_01.CR2.xmp.txt)

information text file :
[darktable crw9552.txt](https://github.com/darktable-org/darktable/files/9017412/darktable.crw9552.txt)

**Comment by jenshannoschwalm** [comment]
Hi, there has been a template with required info we simply need to track this. Please think about opening a new issue or add all required information here :-) Also, if you provide an xmp file - very good - what about the raw?

**Comment by dterrahe** [comment]
Please reopen this issue and provide more information if this still happens to you in 4.0.1 or current master. Thanks!
