### ISSUE TITLE
Darktable Will Not Open Upon Install

### ISSUE THREAD

**Issue by felkild** [darktable-org/darktable#12093]
I have installed, uninstalled, and re-installed Darktable on my computer, and each time I try opening the application, I get this error message: 

![Darktable Error](https://user-images.githubusercontent.com/93313388/176083054-6ab5a882-011e-4cfb-aef4-28180cfc5c32.png)

Wondering what I can do to solve this issue? I had no problem using Darktable on my laptop with Windows 10; wondering if the Windows 11 on my PC is causing the issue? 

Let me know what can be done about this. 

Thanks!

**Backtrace:** 
[darktable_bt_HIMBO1.txt](https://github.com/darktable-org/darktable/files/8997340/darktable_bt_HIMBO1.txt)

**Comment by MStraeten** [comment]
have a look at https://github.com/darktable-org/darktable/issues?q=is%3Aissue+windows+crash

**Comment by victoryforce** [comment]
Your backtrace contains only the string "this is darktable 3.8.1 reporting an exception:" and nothing more. This happens sometimes.

Try running darktable from the CMD prompt (or Windows PowerShell, or Windows Terminal, whatever), with the command line option `--disable-opencl` added. If the program works fine in this case, check if you have installed __OpenCL and OpenGL Compatibility Pack__.

**Comment by felkild** [comment]
I will try doing this method later today or tomorrow and provide some updates. 

Got a more recent backtrace which has more information; not sure if this will help, but figured I would provide it. File attached below: 
[darktable_bt_UA99N1.txt](https://github.com/darktable-org/darktable/files/9014184/darktable_bt_UA99N1.txt)

Thanks for the help!

**Comment by felkild** [comment]
Running with the `--disable-opencl` command worked for me. 
For convenience, I created a .bat script on my desktop that will open darktable with the `--disable-opencl` argument: 

`"C:\Program Files\darktable\bin\darktable.exe" --disable-opencl`

Might be helpful for those who don't want to break out the CLI each time they launch. 

If there is another easier way to automate this argument please let me know, but for now my issue is solved. Thanks for the help!

**Comment by ptilopteri** [comment]
edit the application icon and add/alter the command execution line
to read "C:|Program Files\darktable\b\darktable.exe --disable-opencl"
and save.

note: I do not run windows and the line names, "command execution" 
are quite possibly different
