### ISSUE TITLE
Artifacts with lightness layer blending mode (rgb scene)

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#12092]
Very visible artifacts in the shadows
![Cattura1](https://user-images.githubusercontent.com/24456323/176014325-142ed2ca-addb-40d6-a8d6-9f466ebda67f.JPG)

Darktable 3.8.1
Raw+xmp files
[darktable issue.zip](https://github.com/darktable-org/darktable/files/8994809/darktable.issue.zip)

**Comment by pehar1** [comment]
Please use the template and describe what your issue is and what you want to achieve (realistic representation? artistic effect?). For me this does not look like an issue of the application. If you use extreme settings for a module you should be aware of extreme looks and artefacts of your result.

**Comment by MStraeten** [comment]
if you want to bring out the the dark areas without artifacts you'd better use the exposure tool.
So not selecting an appropriate tool is no software issue

**Comment by age1988** [comment]
> Please use the template and describe what your issue is and what you want to achieve (realistic representation? artistic effect?). For me this does not look like an issue of the application. If you use extreme settings for a module you should be aware of extreme looks and artefacts of your result.

It happens with lower settings too.


> And you have no base curve or filmic depending on display or scene-referred option choosed. 

And what? This xmp is for isolating the issue with just a few modules.


> . As it's not an issue, I close this.

This is an issue, most likely the rgb "scene" lightness could not be used due to probably negative values.

**Comment by Nilvus** [comment]
> > And you have no base curve or filmic depending on display or scene-referred option choosed.
> 
> And what? This xmp is for isolating the issue with just a few modules.
> 
> > . As it's not an issue, I close this.
> 
> This is an issue, most likely the rgb "scene" lightness could not be used due to probably negative values.

Wrong use cases are not issues. Here it's all about alogrithm limits of local contrast, no more. I will put again @pehar1 senctence: "If you use extreme settings for a module you should be aware of extreme looks and artefacts of your result."

Some artifacts could appear on some modules (especially historic old ones related to lab space, like local contrast) when using strong/extreme settings, like you do. Just use other settings or reduce setttings. For such modules, all is about compromise between what you want and modules limits. You could also use contrast equalizer and diffuse & sharpen modules for local (or even global) contrast. You could also use them all (mostly, 2 are better than all 3). diffuse & sharpen should not have such artefacts limits but is slower (needs more power!).

Base curve or filmic helps to set good white or black values.
