### ISSUE TITLE
Panasonic ZS200 missing custom noise profiles

### ISSUE THREAD

**Issue by jetlego** [darktable-org/darktable#12106]
**Describe the bug/issue**
My Panasonic DC-ZS200 does not have a noise profile in darktable, but its closely related DMC-TZ100 does. I decided to copy the noise profile from the DMC-TZ100 to a new file & rename all instances of DMC-TZ100 to DC-ZS200. 

However, when running darktable with the `--noiseprofiles noiseprofiles.json` option, the `denoise (profiled)` module does not  show the expected profiles when opening a ZS200 raw. I then attempted to open a FZ1000 raw, which did not have any profiles, as expected. As a sanity check, I changed the `model` field in noiseprofiles.json to DMC-FZ1000,  which then allowed the aforementioned FZ1000 raw to have noise profiles. 

I also tried compiling 3.8.1 from source, which also had the same issue.

**To Reproduce**
1. Open darktable (blank profile or otherwise) from the command line with the option `--noiseprofiles noiseprofiles.json` with the attached noiseprofiles.json
2. Go to lighttable and add a raw image from a Panasonic DC-ZS200
3. Open the `denoise (profiled)` module
4. Click the dropdown menu
5. Nothing besides generic poissonian appears 

**Expected behavior**
Darktable displays the custom noise profiles from noiseprofiles.json 

**Screenshots**
(for some reason darktable doesn't want to let me screenshot dropdowns)

ZS200 Raw missing profiles
![Screenshot_20220701_175550](https://user-images.githubusercontent.com/19333289/176975852-9c9dcad3-9669-499f-88e2-784edf579e70.png)
FZ1000 raw with profiles
![Screenshot_20220701_174219](https://user-images.githubusercontent.com/19333289/176975864-65107306-090f-4c6c-a586-9580e0e733c1.png)

**example affected image**
[PANA7108.zip](https://github.com/darktable-org/darktable/files/9031928/PANA7108.zip)

**FZ1000 raw that is not affected by this**
[FZ1000INBI25600.zip](https://github.com/darktable-org/darktable/files/9031931/FZ1000INBI25600.zip)

**noiseprofiles.json**
[noiseprofiles.txt](https://github.com/darktable-org/darktable/files/9031912/noiseprofiles.txt)

**Platform**

* darktable version : 3.8.1, installed from package manager
* OS                : Linux - kernel 5.13.0-51-generic
* Linux - Distro    : Ubuntu 20.04
* Memory            :  16GB
* OpenCL installed  : No
* OpenCL activated  : No
* Desktop           : KDE 

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with 3.8.1 compiled from source**
 - Can you reproduce with a RAW or Jpeg or both? **both from the same camera**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? No

**Comment by kmilos** [comment]
In cameras.xml, the DC-ZS200 is defined as an alias of DC-TZ202, so that's where the noise profile should go perhaps.

**Comment by jetlego** [comment]
That seems to have solved it. Thank you.
