### ISSUE TITLE
Fujifilm X-H2S

### ISSUE THREAD

**Issue by etrigan63** [darktable-org/darktable#12109]
Uncompressed and lossless compressed RAF files have been uploaded to raw.pixls.us

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/rawspeed/issues/374

**Comment by etrigan63** [comment]
> Duplicate of [darktable-org/rawspeed#374](https://github.com/darktable-org/rawspeed/issues/374)

Sorry about that. It asked that I open this ticket when I uploaded the file for the other one. Perhaps I misunderstood?
