### ISSUE TITLE
SONY ILCE-7RM4A lens correction

### ISSUE THREAD

**Issue by Kinzis85** [darktable-org/darktable#12105]
Hi,
since i changed my camara body from Sony ILCE-7 to ILCE-7RM4A, the lens correction with the FE 24-105mm f/4 G OSS does not work properly. The recognation of the lens is correct, the camara is not found. I always must manual select the Sony Alpha 7R IV (=ILCE-7RM4). 
The ILCE-7RM4**A** is the replacement for the ILCE-7RM4 with a better Display.

dt 3.8.1 on win11

Thanks, Kinzis85

**Comment by kmilos** [comment]
This is not up to darktable, please request 7RM4A support over at https://github.com/lensfun/lensfun

**Comment by Kinzis85** [comment]
thanks
