### ISSUE TITLE
Darktable crash on pinch-to-zoom

### ISSUE THREAD

**Issue by ltomes** [darktable-org/darktable#12118]
**Did you buy darktable from an application store ?**
No, installed from darktable.org

**Describe the bug/issue**
Darktable crashes when using pinch-to-zoom trackpad actions (two fingers on trackpad, moving away from each other)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Launch darktable
2. Do a pinch to zoom action on trackpad
3. See Error

**Expected behavior**
No crash on pinch to zoom.

**Screenshots**
![image](https://user-images.githubusercontent.com/4184677/177046585-706cd31f-69a7-4d23-b1ab-e9dd51f4e52d.png)

**Which commit introduced the error**
I don't have this information sorry, I can say its version 4.0.0/it has not yet been updated if there is an update.

**Platform**

* darktable version : `4.0.0`
* OS                : Win10, 10.0.19044 Build 19044
* Memory            : 16gb
* Graphics card     : 3050ti
* Graphics driver   :  512.95
* Laptop model: RZ09-0370AE23-R3U1

Logs:
[darktable_bt_X5S1O1.txt](https://github.com/darktable-org/darktable/files/9035049/darktable_bt_X5S1O1.txt)
[darktable_bt_Z0LWO1.txt](https://github.com/darktable-org/darktable/files/9035050/darktable_bt_Z0LWO1.txt)
[darktable_bt_K82QO1.txt](https://github.com/darktable-org/darktable/files/9035051/darktable_bt_K82QO1.txt)

Let me know if any other information is helpful and I can provide it.

**Comment by gi-man** [comment]
Pinch to zoom without an image? In Lighttable or dartable view? 3.5.0+250 or 4.0.0?

**Comment by ltomes** [comment]
> Pinch to zoom without an image?
That's correct

>In Lighttable or dartable view?
Immediately after starting the application (fresh install), so lighttable.

> 3.5.0+250 or 4.0.0?
`4.0.0`, I updated my report above

**Comment by gi-man** [comment]
Does it crash if you have an image? I'm not sure why try to zoom if there is nothing to zoom.

**Comment by victoryforce** [comment]
> I'm not sure why try to zoom if there is nothing to zoom.

For example, by accident. It doesn't matter whether this action makes sense, the point is that the program should not crash at all, even in unexpected situations.
