### ISSUE TITLE
D4s noiseprofile support

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#12115]
A bit late, I am afraid, but finally thanks to Peter I am able to provide them.
From iso 50 to 409k.
Best regards and greetings to the whole team.

For noise profiles, please also attach the entire archive with `.pdf` plots.
[darktable-noiseprofile-20220703.tar.gz](https://github.com/darktable-org/darktable/files/9034643/darktable-noiseprofile-20220703.tar.gz)

**Comment by rawfiner** [comment]
The profile looks great, thank you!
