### ISSUE TITLE
Canon EOS R7

### ISSUE THREAD

**Issue by Micha-Mo** [darktable-org/darktable#12127]
Please add the support for the Canon EOS R7. 
Full file set (RAW, cRAW, dual pixel RAW and dual pixel cRAW) is allready uploaded to raw.pixls.us.   
If you need further files or information feel free to ask.

**Comment by MidgePhoto** [comment]
Is there anything I can do to help?

I didn't see that files had already been uploaded, and I wonder if it would be helpful if it was easier to know that.
I uploaded some raw, craw but not dual pixel ones.

**Comment by kmilos** [comment]
> Is there anything I can do to help?

Keep testing https://github.com/darktable-org/darktable/pull/12124
