### ISSUE TITLE
GainMap and highlight reconstruction problem

### ISSUE THREAD

**Issue by paolodepetrillo** [darktable-org/darktable#12128]
When a GainMap (#10289) is applied in the rawprepare module, pixels which are bright but not clipped may have their values increased so that they are greater than the raw white point. Even though these pixels are valid and not really clipped, the highlight reconstruction module then clips them causing the color to be incorrect. The problem occurs in this smartphone dng image with DT 4.0:
[example.zip](https://github.com/darktable-org/darktable/files/9043107/example.zip)
The clouds are not clipped at all according to the raw overexposed indicator, but with flat field correction enabled in rawprepare and highlight reconstruction enabled, an artifact appears.

**Comment by jenshannoschwalm** [comment]
I had a short look into the gainmap handling code in rawprepare, i guess this is wrong

```
  for(int k = 0; k < 4; k++) piece->pipe->dsc.processed_maximum[k] = 1.0f;

```
It was right with scaling for white & black points but not any more.

**Comment by parafin** [comment]
I don't think this can be handled any other way, because white point is global value for the picture, not per-pixel value. If you raise it, then highlights will be left uncorrected for the central area with gain close to 1. The only solution I see is to split FFC correction from rawprepare and place it after highlight reconstruction module.

**Comment by kmilos** [comment]
Or you re-normalize the gain so it is not >1.0 (equivalent to pulling in the exposure for the max gain)...

**Comment by parafin** [comment]
No, it won't solve anything.

**Comment by parafin** [comment]
I would close this with "won't fix" - this issue is the compromise you get into with shitty lens.

**Comment by jenshannoschwalm** [comment]
> Increasing the clipping threshold seems to be the work around.

No. Just imagine the gainmap to correct for a vignetting, then you might have values of 1.0 in the centre as clipped and in the corners a clip would be a value of much more.

**Comment by jenshannoschwalm** [comment]
@paolodepetrillo it would be possible to defer gainmap calculation as a preprocessing step in demosaic though. There are other pre-demosaic modules that might be affceted, i think hotpixels would be one too.

**Comment by jenshannoschwalm** [comment]
> Now that it's released it has to remain implemented permanently in rawprepare for backwards compatibility?

I think you have two options:
1.  keep the UI setting in rawprepare but defer the processing to demosaic that would be just right. But as some demosaicers need an input range of 0->1 they need proper settings for "processed maximum"
2. no-fix

**Comment by parafin** [comment]
It's true that you can't just move processing to another module - if there are another modules in-between, then it's impossible to have the same result, so old history stacks will break (produce different result). So code will have to remain in rawprepare. What can be done is to obsolete that option and use it only for legacy edits and introduce the same correction in some other place in the pipe for new edits. Maybe it would have made sense to make it a separate iop, then it's just about moving it.
But I'll repeat my opinion - just close this as won't fix.
