### ISSUE TITLE
Segfault in darktrom when changing from image to image after exporting to jpeg

### ISSUE THREAD

**Issue by atomikdg** [darktable-org/darktable#12125]
I have a lot of crashes (segfault) when working on my photos. It happens when switching from the next image after exporting the previous one to jpeg. This bug is not always reproducible as it seems random...(I can work on 10 photos and then crash or it can be 2...).

May be related to #10384 ? (@TurboGit )
If you need more informations...don't hesitate, I will do my best. 

Darktable version: release-4.0.0-18-gc3147ecec
OS: Opensuse Tumbleweed 
Gcc 12.1.0

[darktable_bt_4VN3O1.txt](https://github.com/darktable-org/darktable/files/9040898/darktable_bt_4VN3O1.txt)

**Comment by atomikdg** [comment]
I've try to run with gdb and here is the output:

Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
0x00007ffff7af79e2 in _ui_panel_size_changed (adjustment=0x26fbc10 [GtkAdjustment], pspec=<optimized out>, user_data=<optimized out>) at /home/atomik/Downloads/Darktable_build/darktable/src/gui/gtk.c:1973
1973      if(GTK_IS_WIDGET(darktable.gui->scroll_to[side]))

**Comment by TurboGit** [comment]
Thanks, that's interesting... As you are able to reproduce can you print the value for side here?

A full backtrace you be nice too.

**Comment by atomikdg** [comment]
Here the full backtrace (if I read correctly the doc ;-) )
[gdb.txt](https://github.com/darktable-org/darktable/files/9041422/gdb.txt)

If you mean doing a "pint side" in the gdb console, it give me "1"

**Comment by TurboGit** [comment]
I've just pushed a possible fix. Can you test again?

**Comment by atomikdg** [comment]
Ping...I will try this this evening. I didn't forget 😀

Le mar. 5 juil. 2022, 17:58, Pascal Obry ***@***.***> a
écrit :

**Comment by atomikdg** [comment]
@TurboGit  I've been working on DT with your patch since 1 hour...and no crash...It seems to work. If it crashes , I will inform you here. Will you pull it to the branch 4.0.x ? 

Thanks !

**Comment by TurboGit** [comment]
Yes, sure! I'll wait a bit more and if all goes well on your side let me know and I'll merge in 4.0.x branch for 4.0.1.

**Comment by atomikdg** [comment]
Unfortunatly the crash happened again today... "Seems" more difficult to reproduce...

[gdb2.txt](https://github.com/darktable-org/darktable/files/9057564/gdb2.txt)
.

**Comment by TurboGit** [comment]
@atomikdg : Where does it crash into the last backtrace? I cannot find it. It would be better to have only the backtrace of the failing thread to avoid all noise. When it crash under gdb just issue the 'bt' command;

**Comment by TurboGit** [comment]
Ok, really no idea and despite all my attempts still no crash on my side. One idea, can you test this patch:

```
diff --git a/src/views/darkroom.c b/src/views/darkroom.c
index d754b2fc42..0170daecc7 100644
--- a/src/views/darkroom.c
+++ b/src/views/darkroom.c
@@ -837,6 +837,8 @@ static void _dev_change_image(dt_develop_t *dev, const int32_t imgid)
   dev->proxy.wb_is_D65 = TRUE;
   dev->proxy.wb_coeffs[0] = 0.f;
 
+  memset(darktable.gui->scroll_to, 0, sizeof(darktable.gui->scroll_to));
+
 #ifdef USE_LUA
```
 
That is, just adding one line at start of `_dev_change_image()` in `darkroom.c`.

**Comment by TurboGit** [comment]
@atomikdg : One question, do you really need to export a jpeg to get this crash. If you have any more information do not hesitate, I really fear that this bug is going to be hard to track down :(

**Comment by atomikdg** [comment]
Hello, I'm on holiday for now so I will try your patch at the end the week.
I think it happens one time when typing something in the modules text
input. But I have no backtrace...

One more info, when I used darktable opensuse binary I never had this kind
of crash (but it's a long time ago...). So it may be related to some
compiler options...? Architecture dependent ? I had the same behaviour with
Dt 3.8.x.
Or linked to libgtk ? ( ex: https://github.com/linuxmint/nemo/issues/1156 )

Thanks

Le lun. 11 juil. 2022, 15:51, Pascal Obry ***@***.***> a
écrit :

**Comment by atomikdg** [comment]
I'm trying your patch. I worked on my holidays photos today and still no crash...I will keep you in touch if this fail again.

**Comment by atomikdg** [comment]
> Ok, really no idea and despite all my attempts still no crash on my side. One idea, can you test this patch:
> 
> ```
> diff --git a/src/views/darkroom.c b/src/views/darkroom.c
> index d754b2fc42..0170daecc7 100644
> --- a/src/views/darkroom.c
> +++ b/src/views/darkroom.c
> @@ -837,6 +837,8 @@ static void _dev_change_image(dt_develop_t *dev, const int32_t imgid)
>    dev->proxy.wb_is_D65 = TRUE;
>    dev->proxy.wb_coeffs[0] = 0.f;
>  
> +  memset(darktable.gui->scroll_to, 0, sizeof(darktable.gui->scroll_to));
> +
>  #ifdef USE_LUA
> ```
> 
> That is, just adding one line at start of `_dev_change_image()` in `darkroom.c`.
@TurboGit 
This patch seems to work well. I worked on some photo during +/- 1h00 today and still no crash.
I tried (also today) without your patch (same sources), I can get it crash after 5 minutes...

**Comment by TurboGit** [comment]
Ok, I have merged this change. Thanks for all your testing!
