### ISSUE TITLE
After upgrade from dt 3.8 to dt 4.0, all images edited from dt 3.8 now have a "white balance applied twice" error

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#12134]
**Describe the bug/issue**
After upgrade from dt 3.8 to dt 4.0, all my images edited from dt 3.8 now have a "white balance applied twice" error.

**To Reproduce**
1. Use dt 3.8 with "scene-refered" pixel workflow + "modern" chromatic adaptation defaults
2. Edit an image. Keep white balance module with "camera reference " settings, so that it does not conflict with color calibration
3. Upgrade to dt 4.0
4. Open the same image in darkroom

**Expected behavior**
After upgrade to 4.0, white balance module kept with "camera reference " settings

**Observed behavior**
After upgrade to 4.0, white balance module is changed to  "user modified " settings, and  the "white balance applied twice" error is raised

**Screenshots**
![Capture d’écran du 2022-07-05 23-26-19](https://user-images.githubusercontent.com/22872204/177420015-0e63c091-c033-4b21-a27d-b8d57742c74e.png)

**Additional information**
Resetting the white balance module is solving the problem, but this operation has to be repeated to all images

**Platform**
* darktable version : 4.0~c3147ec
* OS : Linux
* Linux - Distro : Ubuntu 22.4

**Comment by MStraeten** [comment]
you can suppress those warnings by disabling warnings in preferences.
More infos on this issue at https://github.com/darktable-org/darktable/issues/11377

**Comment by leclercj** [comment]
Same issue as #11377 indeed.
But I'm not that happy to see it closed without possible fix. As other people I've several hundreds of images affected :(
Disabling warnings in preferences is not a good solution; I want to keep those warnings for new edits

**Comment by Nilvus** [comment]
It's annoying yes but this can't be fix unfortunately. It's a consequence of Adobe coeffs file removal. Coeffs had been moved to cameras file on rawspeed (if I understand correctly). The fix would have been to revert that but this move had been made for good reasons.
Note that your edits aren't really changed and it's just the warning and bulb that is no more selected.
There's no fix on darktable side. Some move are needed and have sometimes little downside.
It's easy to fix it: set back bulb on an image in white balance module. Then, in lighttable, copy selectively image development, select only white balance module. Then paste it on all affected images (be sure to be in append mode.
Before closing this issue, maybe @TurboGit, you can complete explanation if mine is not complete as it was you who explain to me that.

**Comment by TurboGit** [comment]
@leclercj : I understand the somewhat frustration. Note that this does not happen to all users but only the Adode coef for your camera was not in sync with the rawspeed ones. We knew there was possibly some synchronization issue and the move to use rawspeed directly instead was to avoid this.

Disabling warning is not a good idea indeed. But as @Nilvus said, you can:
- select all images from camera having the issue
- change white balance to use the camera reference to one image
- copy the white balance module
- paste on all images (for the same camera) selected

Should be not too cumbersome and will be needed only once.  How does that sound ?

**Comment by Fade78** [comment]
> [@leclercj](https://github.com/leclercj) : I understand the somewhat frustration. Note that this does not happen to all users but only the Adode coef for your camera was not in sync with the rawspeed ones. We knew there was possibly some synchronization issue and the move to use rawspeed directly instead was to avoid this.
> 
> Disabling warning is not a good idea indeed. But as [@Nilvus](https://github.com/Nilvus) said, you can:
> 
>     * select all images from camera having the issue
> 
>     * change white balance to use the camera reference to one image
> 
>     * copy the white balance module
> 
>     * paste on all images (for the same camera) selected
> 
> 
> Should be not too cumbersome and will be needed only once. How does that sound ?

I also have this issue. Fresh import from a Nikon Z6iii in Darktable 5 says that the white color is applied twice. It's true, if I reset the white balance module, the color changes. Reseting the white balance actually correct the problem but the copy/paste of the reseted white balance doesn't actually alter the pasted images.
