### ISSUE TITLE
lighttable: thumbnail extended overlay text not shown when thumbnails are big

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12136]
darktable 4.0 on xubuntu linux

I have the _thumbnail extended overlay text_ set, and it's not shown if the thumbnails are small, and that's ok, the text doesn't fit.

The bug is that the text isn't shown if the thumbnails are made big, say from 6/line upward on the whole width of my 1920 px screen.

In this case the text should be shown

**Comment by jade-nl** [comment]
This isn't a bug but something that can be set/adjusted in the preferences:

_preferences->lighttable->delimiters for size categories_

From dtdocs:


> delimiters for size categories
>     Size categories are used to allow different thumbnail overlays to be shown depending on the thumbnail size. A pipe delimited set of values defines at what image sizes the category changes. The default value of “120|400” means that there will be 3 categories of thumbnail: 0-120px, 120-400px and >400px.

The default is **120|400** Increase the second number to your liking.

If I set it to 500 overlays are shown for 4/line but not 3/line. 625 will show 3/line. Not sure if there is a relation between the screen size and the numbers, so YMMV.

**Comment by dterrahe** [comment]
@paolobenve if the answer @jade-nl provided doesn't sufficiently cover your requirements, please feel free to reopen this issue.
