### ISSUE TITLE
dt4.0 lighttable : Gtk-CRITICAL **: gtk_render_frame_gap: assertion 'xy1_gap <= width' failed

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#12135]
**Describe the bug/issue**

In dt 4.0, in lighttable, hovering the mouse over the new "star filter" zone is raising critical Gtk exception in the console

![Capture d’écran du 2022-07-05 23-57-27](https://user-images.githubusercontent.com/22872204/177424676-0ce45d65-d500-44df-8b02-c45ad7ba8f1b.png)

```
(darktable:163408): Gtk-CRITICAL **: 23:51:45.449: gtk_render_frame_gap: assertion 'xy1_gap <= width' failed
(darktable:163408): Gtk-CRITICAL **: 23:51:48.398: gtk_render_frame_gap: assertion 'xy1_gap <= width' failed
(darktable:163408): Gtk-CRITICAL **: 23:51:48.793: gtk_render_frame_gap: assertion 'xy1_gap <= width' failed
(darktable:163408): Gtk-CRITICAL **: 23:51:49.885: gtk_render_frame_gap: assertion 'xy1_gap <= width' failed
...
```
Seems 100% reproducible in my case

**Platform**
    darktable version : 4.0~c3147ec
    OS : Linux
    Linux - Distro : Ubuntu 22.4

**Comment by jenshannoschwalm** [comment]
I don't have that, some CSS special thing ?

**Comment by leclercj** [comment]
I don't have any specific CSS. I tried with different themes. I can reproduce 100% with all themes. Am I the only one, or somebody else is observing the same ?

**Comment by TurboGit** [comment]
I'm using French UI and don't have this issue... Something maybe related to a Gtk version. What is yours @leclercj?

**Comment by leclercj** [comment]
yes, I tried french or english. Same results
I'm running libgtk-3-0 Version 3.24.33-1ubuntu2

**Comment by leclercj** [comment]
I need to add one thing:  The Gtk assert occurs hovering the range rating as pinned on top toolbar, not hovering the range rating in collections filters section

**Comment by leclercj** [comment]
Also interesting:

The Gtk assert only occurs hovering the range rating as pinned on top toolbar when top toolbar is set to show the nb of images selected in current collection
![Capture d’écran du 2022-07-06 19-22-07](https://user-images.githubusercontent.com/22872204/177608554-a305f987-1972-4d00-8937-a5b94f8bafa7.png)

It does not occur when the top text line with nb of images selected in current collection is hidden
![Capture d’écran du 2022-07-06 19-22-41](https://user-images.githubusercontent.com/22872204/177608463-32115a27-ec7a-4cf8-b31c-2856570e31e0.png)

**Comment by TurboGit** [comment]
> I need to add one thing: The Gtk assert occurs hovering the range rating as pinned on top toolbar, not hovering the range rating in collections filters section

Tested that, no issue on my side.

I have also the nb of images on top displayed, and still no gtk issue.

Almost the same Gtk version on my side:

```
$ apt-cache policy libgtk-3-0
libgtk-3-0:
  Installed: 3.24.34-1
  Candidate: 3.24.34-1
```

What is your WM? GNOME, KDE, if GNOME is that Ubuntu one with the side bar on the left? I'm just trying to find a pattern...

**Comment by leclercj** [comment]
I'm using GNOME version 42.2 as currently released in Ubuntu 22.04 LTS. No sidebar on the left anymore

**Comment by TurboGit** [comment]
I'm also using GNOME 42.2 ! Let's keep looking at this issue and see if we can find what trigger this.

**Comment by leclercj** [comment]
I'm now observing that the problem is not specific to the range rating.

The following filters have same issue when pinned on top toolbar:
- range rating
- capture date
- import time
- modification time
- export time
- print time
- aperture
- exposure
- focal length
- ISO
- aspect ratio

The following filters are safe:
- color label
- search
- grouping
- local copy
- history
- module order

**Comment by leclercj** [comment]
Not reproduced anymore after upgrade to 4.0.1
