### ISSUE TITLE
Windows Access Violation

### ISSUE THREAD

**Issue by f-mcgraw** [darktable-org/darktable#12140]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Installed darktable v4.0.0 from the download file off the darktable website
Windows defender issued a warning for install as the publisher was unknown, but I proceeded anyway.
Installation was successful.
Upon running the application, a window briefly pops up and disappears, then an error popup appears indicating an unhandled exception occurred.
Error file is attached.

[darktable_bt_DQCQO1.txt](https://github.com/darktable-org/darktable/files/9057566/darktable_bt_DQCQO1.txt)

I uninstalled, re-downloaded and tried again, with the exact same results.
Please advise.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : Windows 4.0.0
* OS                : Windows 10 Home Version10.0.19044 Build 19044
* Memory            : 8GB
* Graphics:       Intel(R) UHD Graphics 620

**Comment by gi-man** [comment]
There seems to be an issue with the OpenCL (igdrclneo64.dll). Intel cards tend to give us problems.

First, try to update your graphics card driver
Second, ensure you uninstall OpenCL Compatibility stuff from windows. It is pre-installed in some systems. Go to Settings, Apps, Apps & Features and search for it there.
If that fails, then run from cmd darktable-cltest.exe and post the results.

Meanwhile, if you need to use darktable, you can start it disabling the opencl via darktable --disable-opencl
