### ISSUE TITLE
Snapshot does not resize

### ISSUE THREAD

**Issue by danjjl** [darktable-org/darktable#12144]
**Describe the bug/issue**

When hide the left or right panel when in snapshot comparison mode, only one of the two snapshots is resized.

**To Reproduce**
1. Take a snapshot
2. Click on it to enter snapshot comparison
3. Hide a previously visible side panel (left or right)
4. Only the snapshot on the right is resized.

**Expected behavior**

Both snapshots should be resized in similar fashion.

**Screenshots**
Before hiding right panel:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/747240/177726775-3a21495b-da87-4752-9b84-ea516bf8c5e7.png">

After hiding right panel:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/747240/177725566-fd98d50c-7633-426f-b264-d315c2a40de5.png">

**Platform**

* darktable version : 4.0.0+52~g5d1e49434-dirty
* OS                : macOS Monterey 12.4 (21F79)
* Memory            : 16GB
* Graphics card     : Apple M1 Pro

**Comment by jenshannoschwalm** [comment]
That's how snapshots work in dt for a long time :-)

**Comment by danjjl** [comment]
Thanks :), new to the software and this seemed like unexpected behaviour.
Is this a conscious design choice?

Intuitively, I was expecting both snapshots to resize in the same way.

**Comment by jenshannoschwalm** [comment]
> Is this a conscious design choice?

Sort of, i fact it's more like a working "hack" but there are more problems with snapshots that make it impractical to be improved a lot so none of the devs has been working on it for some time.

BTW one part of the screen is the snapshot, the other is the normal processed image :-)

**Comment by elstoc** [comment]
This has been raised and discussed many times (duplicate issue here: https://github.com/darktable-org/darktable/issues/2784) so I'll close this one. See the other discsussions about why this is hard (impossible?) to do.
