### ISSUE TITLE
Re-enable Sony DSLR-A560

### ISSUE THREAD

**Issue by awenocur** [darktable-org/darktable#12143]
I have submitted a few new ARW files to raw.pixls.us for the alpha 560, and noticed that one was already present from another contributor. Mine aren't displayed yet publicly.

**Comment by PeterWem** [comment]
Meanwhile waiting for official support you can re-enable it locally on your computer by just removing the marked part from the file cameras.xml

![Screenshot_20220708-222052](https://user-images.githubusercontent.com/34200649/178064959-6a38e868-997f-4a84-95f7-d5ccf1af50be.jpg)

**Comment by rjki** [comment]
Same with Sony A380!

**Comment by PeterWem** [comment]
> Same with Sony A380!

Upload all raw samples needed and fill a new issue here after that.
