### ISSUE TITLE
Crash when reaching a picture in library - new in 4.0.0

### ISSUE THREAD

**Issue by ThDo16** [darktable-org/darktable#12153]
During my first few minutes in 4.0.0, Darktable started to crash when reaching a specific picture in the library display.

[darktable_bt_SKFPO1.txt](https://github.com/darktable-org/darktable/files/9074307/darktable_bt_SKFPO1.txt)

**Comment by Nilvus** [comment]
There's an issue template, asking for many information. This template is provided for good reasons. Unfortunately, with so few information, we can't help. Thus, this is probably something related to your system and not directly darktable. Check if your antivirus and/or Windows defender (seems that you are on Windows when seeing txt file...) and try launching darktable. I close this issue. If those suggestions doesn't work, you could create a new one, but with all needed infos asked by template issue.
