### ISSUE TITLE
OpenCL not activated darktable 4.0

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#12154]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

Installed dt 4.1.0+22~gd39d5f6 from git build on 
i7 with GeForce RTX 3060 Ti 
darktablerc contained ""tuneopencl=FALSE"
config option in dt was grayed out

running darktable-clinfo reports opencl as not being available.

editing "tuneopencl" to TRUIE and immediately running
darktable-clinfo correctly reports opencl as being used and
the amount of memory available.

**Expected behavior**

the use and availability of opencl should not depend on 
setting tuneopencl in darktablerc, especially having to use
an editor to make the change.

**Platform**

* darktable version : 4.1.0+22~gd39d5f6
* OS                : Linux - kernel 5.18.9-1
* Linux - Distro    : openSUSE Tumbleweed 20220706
* Memory            : 32 GiB
* Graphics card     : NVIDIA GA104 [GeForce RTX 3060 Ti
* Graphics driver   : nvidia v: 515.57
* OpenCL installed  : yes
* OpenCL activated  : was not, is now
* Xorg              : 21.1.3
* Desktop           : KDE Plasma5
* GTK+              : gtk4 4.7.0
* gcc               : 12.1.0

**Comment by jenshannoschwalm** [comment]
I know you reported this, just to make sure, this is reproducible?

That setting to true simply can't enable opencl from what the code does.

**Comment by ptilopteri** [comment]
well, I no longer can but I did repeat it 4 or 5 times before
commenting, and I did not have opencl available until I edited
tuneopencl to TRUE.

but I no longer can and have no ideal what as changed. 

closing
