### ISSUE TITLE
image rotation angle is limited to [-10; 10] degree range

### ISSUE THREAD

**Issue by yaitskov** [darktable-org/darktable#12156]
I noticed that DT v4.0.0 image rotation angle is limited to the range between -10 and 10 degrees.

It looks like a feature, but [tutorial](https://www.youtube.com/watch?v=HWT_LWP0dkY) does not explain reasons causing the limitation. 
 
I would expect range at least between -45 and 45.  
I don't remember that GIMP has such limitation.

I installed from DT through nix-shell (master branch - fixed commit for reproducibility):

```
cat<<EOF > shell.nix
{ pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/98472c0467e56d143b2f97a669eddefb7cf99b19.tar.gz") {} }:
  pkgs.mkShell {
  nativeBuildInputs = [ pkgs.darktable ];
}
EOF
```

```
$ nix-shell
$ darktable
```

```
this is darktable 4.0.0
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

![dt-limited-rotation](https://user-images.githubusercontent.com/1292734/178128669-4cea53a6-4953-4455-871b-c88b3bb60475.jpg)

**Comment by ralfbrown** [comment]
Those are soft limits to allow reasonably accurate control when dragging the slider.  Right click on the slider and you can enter any value in -180...+180 (the hard limits).  The majority of sliders have soft limits and can be set to more extreme values this way.  There's mention of it in the manual for the profiled denoise module (at least that's what popped up in a quick search): https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/denoise-profiled/#module-controls

**Comment by victoryforce** [comment]
> It looks like a feature, but [tutorial](https://www.youtube.com/watch?v=HWT_LWP0dkY) does not explain reasons causing the limitation.

The reasons are very logical: when you soft-limit the slider to a smaller range, you increase the accuracy.

**Comment by yaitskov** [comment]
Thanks. It is working. I will try to extend tooltip. Such behavior was not obvious. I didn't work with other photo editors extensively and develop mostly backend, but I haven't seen such UI solution anywhere. Is it borrowed from somewhere? 

What do you think about expanding slider after the limit 10 with a few fixed positions 15 25 30 45.
Or expanding slider wider to the left (sort of css overflow) to keep slider resolution the same  while mouse hovers slider and then shrinking slider back on mouse out event?

Designer these days must have very wide screens, so DT can afford extra?

**Comment by yaitskov** [comment]
I rethought UI - horizontal expanding is not good, because it requires cursor relocation. 

Alternative is - once the slider hits the limit 10 then a subslider  (from 0 to 10) below drops down for second decimal digit positioned at 1 and original slider resets to 0. So there are 2 slider for every digit. If subslider is set to 0 then it disappears and main slider is set to 0.99. This is recursive an could be expanded to N digit values.

**Comment by renkam** [comment]
Maybe a better idea would be to allow to go past the limit when for example shift or ctrl keys are pressed?
Or add a checkbox to disable the soft-limit?
Imagine the situation when you have the need to rotate pictures for 20 to 40 degrees, it is very annoying to right click, enter value by keyboard (which requires to move hand from mouse to keyboard) then back to slider to adjust angle to required amount.

**Comment by dterrahe** [comment]
Only seeing this now (adding comments to an already closed issue will only bring them to the attention of people who subscribed or participated in it).

Yes, you can already ignore soft limits by holding ctrl _and_ shift together while scrolling, using arrow keys or dragging. Ctrl is for small movements, shift is for large movements.
