### ISSUE TITLE
Please add support CPU OpenCL and POCL

### ISSUE THREAD

**Issue by guglovich** [darktable-org/darktable#12150]
The application does not detect the OpenCL method on the CPU with the OpenCL driver from the POCL project.
https://github.com/pocl/pocl

![изображение](https://user-images.githubusercontent.com/54148165/178001484-71f1fa9d-1388-4dd9-9fcc-62b50ef322e0.png)

Platform:
* darktable version : 4.0.0
* OS                : Linux 5.18.9-1-ck
* Linux - Distro    : Arch
* Memory            :  16GB
* Graphics card     :  RX460 and Kaveri R7
* Graphics driver   :  Mesa 22.1.3
* OpenCL installed  :  Mesa 22.1.3 and Pocl 3.0
* OpenCL activated  :  Mesa OpenCL 1.1 and Pocl 3.0
* Xorg              :  21.1.3
* Desktop           :  Xfce 4.16
* GTK+              :  unknown
* gcc               :  12.1.0
* cflags            : -march=bdver3 -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
[clinfo.log](https://github.com/darktable-org/darktable/files/9072404/clinfo.log)

**Comment by guglovich** [comment]
> A CPU OpenCL driver will be slower than darktable's own CPU code, so that would at best be useful for debugging the OpenCL code paths when no supported GPU is available.

Roger that. But if the Darktable settings don't show the device and OpenCL settings, then your implementation doesn't work? Or does your implementation's OpenCL work, but it does not show up in the settings in any way?

**Comment by jenshannoschwalm** [comment]
That's what the manual is for :-)

> but it does not show up in the settings in any way?

Exactly :-)
You have to "force-enable" the device via the cldevice key as described here, cpu devices are disabled by default.

https://darktable-org.github.io/dtdocs/en/special-topics/mem-performance/
