### ISSUE TITLE
Darktable crashes adjusting parametric mask on OSX 12.4

### ISSUE THREAD

**Issue by ronstone2000** [darktable-org/darktable#12168]
**Describe the bug/issue**

On OSX 12.4 (Monterey), Darktable 4.0.0 crashes while setting parametric mask input after some amount of adjustment using the input slider. The example below uses Color Balance RGB but the crash has occurred in other modules. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Color Balance RGB'
2. Click on 'parametric mask'
3. Click on 'Hz'
4. Select an area in the image
5. Display mask
6. Adjust input sliders for some amount of time
7.  Darktable crashes.

**Expected behavior**
Mask input is set successfully. 

**Version**

I am using the stock pre-built DT 4.0.0 for Mac downloaded from the site:

```
/Applications/darktable.app/Contents/MacOS/darktable --version
this is darktable 4.0.0
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional Information**

Attached is the error as trapped by OSX.

[darktable_crash.txt](https://github.com/darktable-org/darktable/files/9092613/darktable_crash.txt)

**Comment by flowftw** [comment]
I experienced some crashes on Mac OS 12.5 using a Macbook Air M1 as well. For me the steps to reproduce are a bit different.

1. Open an image
2. Create a new instance of any module (tested with Exposure and Color Balance RGB)
3. Create parametric mask for new instance 
4. Adjust sliders
5. Enable and disable new instance
6. Switch to another picture in collection  

I installed Darktable using homebrew which should be the x86 binary executed via Rosetta 2.

```
> /Applications/darktable.app/Contents/MacOS/darktable --version
this is darktable 4.0.0
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

I am going to attach the error which Mac OS has shown as well.

[darktable-4.0.0-crash.txt](https://github.com/darktable-org/darktable/files/9219564/darktable-4.0.0-crash.txt)

**Comment by leanderhutton** [comment]
Does this still happen for either of you on Ventura and 4.2? I cannot duplicate it on my M2 Mac Book Pro with running those versions.

**Comment by ralfbrown** [comment]
No further reports in over a year, darktable has had two releases with lots of changes since.
If this should still be a problem, we can reopen the issue.
