### ISSUE TITLE
color balance rgb can make extreme highlights go black when using darktable UCS saturation formula

### ISSUE THREAD

**Issue by benp456** [darktable-org/darktable#12163]
I have observed this issue with darktable 4.0, both CPU and OpenCL.

Steps to reproduce:
Open an image and disable all non-mandatory modules
Enable color balance rgb and drag the highlights slider in the perceptual brilliance section to the right
Enable exposure and increase the exposure until there are severely overexposed regions in the image

The issue seems to occur only with moderate to large highlight boosts when there are already overexposed highlights.

Expected behaviour is the highlights clip at white, but at a certain point while increasing exposure they will go black or sometimes grey

If the source image contains sufficiently bright highlights then the exposure module is not needed to reproduce the bug

Please see attached image and xmp for a nonsynthetic example (excuse the poor photography but I was trying to see what kind of sunstars I could get with my new lens!)

With darktable UCS saturation formula
![image](https://user-images.githubusercontent.com/91010403/178337265-bccca562-a652-49dd-a827-04d598227df6.png)

With JzAzBz saturation formula
![image](https://user-images.githubusercontent.com/91010403/178337430-d0e9d503-4e28-4176-8196-ceece064c1d4.png)

Image and xmp below should show the issue but I think it's easy to reproduce on any image with bright highlights
[DSC_4844.zip](https://github.com/darktable-org/darktable/files/9086855/DSC_4844.zip)
[DSC_4844.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/9086829/DSC_4844.NEF.xmp.txt)

**Comment by aurelienpierre** [comment]
Did you set the `white fulcrum` slider in `mask` tab to the proper white value (using the color picker) ?

**Comment by benp456** [comment]
I had not tried that, but doing it now, the slider has only a minor effect on which pixels go black. Using the color picker and selecting the sun for example does not change the qualitative result.

**Comment by flannelhead** [comment]
@aurelienpierre : this patch

```diff
diff --git a/src/common/colorspaces_inline_conversions.h b/src/common/colorspaces_inline_conversions.h
index 102543a1a8..907f64278d 100644
--- a/src/common/colorspaces_inline_conversions.h
+++ b/src/common/colorspaces_inline_conversions.h
@@ -1376,7 +1376,7 @@ static inline void dt_UCS_JCH_to_xyY(const dt_aligned_pixel_t JCH, const float L
   */
 
   // should be L_star = powf(JCH[0], 1.f / cz) * L_white but we treat only the case where cz = 1
-  const float L_star = JCH[0] * L_white;
+  const float L_star = MIN(JCH[0] * L_white, 2.09888f);
   const float M = powf(JCH[1] * L_white / (15.932993652962535f * powf(L_star, 0.6523997524738018f)), 0.8322850678616855f);
 
   const float U_star_prime = M * cosf(JCH[2]);
```

is enough to make these black areas disappear. After all there's a hard limit to lightness in dt UCS, as commented in 
```c
static inline float dt_UCS_L_star_to_Y(const float L_star)
{
  // WARNING: L_star needs to be < 2.098883786377, meaning Y needs to be < 3.875766378407574e+19
  return powf((1.12426773749357f * L_star / (2.098883786377f - L_star)), 1.5831518565279648f);
}
```
Probably it's best to sanitize to honor that after making adjustments.

**Comment by aurelienpierre** [comment]
This fix has unexpected side effects that need investigation.

**Comment by ptilopteri** [comment]
since you apparently already know what the "unexpected side effects" are, would
it not follow that you would provide those small details?  tks,
