### ISSUE TITLE
Update main darktable screenshot in Github and the official website.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#12161]
**Describe the bug/issue**
Please. 

If it's not too much to ask, it would be nice if at least the main darktable image could be updated, both on Github and on the official site.

After this 4.0 version many things have changed both internally and in the UI, but you still keep the same screenshot of the old interface.
This is important, even more when the default theme has been defined as darktable-elegant-grey.

There are a few websites like dpreview referring to the new version of the program and its goodness, but the old image is shown.

Thanks.

**Screenshots**

Github:
![Screenshot-20220710223027-1318x1112](https://user-images.githubusercontent.com/67672868/178178535-74476af5-4a5b-4bbf-9763-16cd37f4c0bc.png)

darktable official website:
![Screenshot-20220710223056-1411x1126](https://user-images.githubusercontent.com/67672868/178178597-a95c2e0e-0162-490e-9fa8-297d28b63eb0.png)

dpreview:
![Screenshot-20220710224217-941x1327](https://user-images.githubusercontent.com/67672868/178179021-4b2b2238-0a5f-4c2e-ad39-418c7c7bbd30.png)

**Comment by elstoc** [comment]
Agreed, and there's already a request to update the website on the dtorg repository. The only reason I haven't done it so far is that the current screenshot is the lighttable view and replicating it requires me to have a lot of images that I don't mind being the public face of darktable (!). Perhaps an image of the darkroom view would be more representative though.

**Comment by Nilvus** [comment]
Actual old screenshot is mine. I agree that this need to be changed, with grey theme now. I could do it again but I think it would be good if owner is different.

**Comment by difrkaguilar** [comment]
> it requires me to have a lot of images that I don't mind being the public face of darktable (!).

Maybe if some of the pixls.us play raw Creative Commons images are collected with the new filter collection module and presented in the lighttable view can be a solution.

**Comment by difrkaguilar** [comment]
Glad to hear about it.

https://discuss.pixls.us/t/darktable-4-2-is-coming-simply-thank-you/34203/78
