### ISSUE TITLE
Crash during export

### ISSUE THREAD

**Issue by dcendal** [darktable-org/darktable#12165]
**Introduction**
Darktable crash during export

**Did you buy darktable from an application store ?**
No

**To Reproduce**
Export an image

**Which commit introduced the error**
git checkout e69389ef3777b2d0529d70b199d8f40dd7933c43 --> Fails
git checkout 488bcf615afc0964a1a536ed7a4c4c22b08c313f --> Works!

**Platform**
Linux 5.15.0-39-generic #42-Ubuntu 

* darktable version : Master
* Linux - Distro    : e.g. Ubuntu 22.04
* Graphics driver   : Nvidia 515
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              :  No, wayland
* 
**Additional context**
Attached the log file
[log.txt](https://github.com/darktable-org/darktable/files/9088055/log.txt)

**Comment by Nilvus** [comment]
@kmilos: failed commit posted here is yours. Could you check?

**Comment by kmilos** [comment]
Can do, but might be some time until I'm able to get to it.

Meanwhile, any additional details would be helpful: format, size...

I'm surprised the CI didn't fail is it exports to PNG as part of the test...

**Comment by kmilos** [comment]
Confirmed here as well when "allow upscaling" is enabled, [`ovoid` seems to be NULL here](https://github.com/darktable-org/darktable/blob/23d917bfbb9c5811c2ec06eb4faf931b662f7dd6/src/develop/tiling.c#L850).

I must admit I have no idea what "allow upscaling" is meant to do, nor how the tiling code works, nor why adding the dimension restrictions affected this, sorry.

**Comment by TurboGit** [comment]
But in the export dialog you have 0 x 0 for the size (cm). Seems wrong to me, no?

**Comment by kmilos** [comment]
> "allow upscaling" controls what is done if the specified export dimensions are larger than the image at the end of the pixelpipe.

Nothing is specified (i.e. 0x0) in this case. Strangely, `dt_imageio_export_with_flags()` seems to take license to assume this means ["export to max possible format dimensions"](https://github.com/darktable-org/darktable/blob/01c70939cefa48137bc15190077afbebe2d3865b/src/common/imageio.c#L893-#L894) instead of still preserving original image dimensions - I'm not sure this is correct/desirable...

In any case, it should still work, and tiling code should not crash, no?

**Comment by TurboGit** [comment]
A corner case... I don't think having upscale set with 0 x 0 dimensions has any meaning to me. We upscale on which basis???? So I propose in this case to set the width/height to the current image dimensions. Thoughts?

**Comment by kmilos** [comment]
True ;)

**Comment by TurboGit** [comment]
@kmilos : Ok with #12194 ?

**Comment by ralfbrown** [comment]
>  we still have a segfault also with a non-zero large output requested (e.g. set to 65535x49126) and "allow upscaling" enabled.

Presumably a missing null check on the buffer allocation.  Those dimensions require 9 GB at 24bpp and 48 GB for internal floating-point buffers.

**Comment by jenshannoschwalm** [comment]
Or an int overflow?

**Comment by ralfbrown** [comment]
Probably not.  I just tried an allow-upscaling export to 65535x49200 while running under GDB, saw memory use at 44 GB and then the program terminated on a SIGKILL (i.e. the OOMKiller took it down).

**Comment by jenshannoschwalm** [comment]
> /imageio.c:856, branch at src/common/imageio.c:980).

Yeah. that's absolutely right.
