### ISSUE TITLE
darktable generated DNG HDR file with "incorrect input profile" and weird color temperatur of 25000

### ISSUE THREAD

**Issue by st-binder** [darktable-org/darktable#12167]
merging five different exposed dng files (which can be processed with no problems) with the "create hdr" function, the result can not be processed. The HDR file has the wrong color temperature and an invalid input color profile.
The original files are from a Nikon Camera (NEF) and converted to DNG (with raw2dng). There were never problems with single files.

**Reproduce**
1. Exposure Stack of DNG Files
2. merge with "Create HDR"
3. open the new DNG HDR file

**Platform**
* darktable version : 4.0
* OS                :  Linux 5.18.10
* Linux - Distro    : Archlinux
* Memory            :  32GB
* Graphics card     :  AMD
* Graphics driver   :  amdgpu
* OpenCL installed  :  YES
* OpenCL activated  :  YES

**Comment by kmilos** [comment]
Possibly addressed by https://github.com/darktable-org/darktable/pull/12436

**Comment by st-binder** [comment]
Problem is fixed, it was related to the empty color matrix too. You are right with using NEF directly for HDR, but raw2dng is a common linux tool, that saves 20% of disk space for my raw files and retains all NEF metadata for darktable.
