### ISSUE TITLE
CROP module with only floating % sizes is my nightmare

### ISSUE THREAD

**Issue by sophisticatedDreamer** [darktable-org/darktable#12177]
**What' wrong**

It's a nightmare to fumble the CROP module's sliders (or the grid) to get an **exact pixel dimension** like eg. 1800 x 1200 px.

Not only that it is unnecessarily hard to _set the grid to a specific pixel dimension_. Even **worse:** when I finally managed to get the required exact pixel dimension (grid shows 1800 x 1200), after export that image, it's pixel dimension is **always** only 1799 x 1199 px.

But we still can increase the **worse** level to **the worst:**

I thought, I could now save the hard worked out 1800 x 1200 px as a preset for reuse with many different photos. This _does not work_, though, when the next photo's original size is _different_ from the one I saved the 1800 x 1200 px as a preset.

This is a clear sign, that only the percent (float numbers) are calculated and not the actual pixel dimension:

- 17% from 3400 pixels are much less than 17% from 5860 pixels.
- 1800 pixels are 1800 pixels, no matter whether cropped from 3400 or 5860 pixels

Should be obvious.
Thus, the CROP module and in particular the preset aving is useless and finally error prone in practical use when images of various sizes shall be cropped to (eg.) exactly 1800 x 1200 pixels.

**What we really, really need**

1. For God's sake give as an easy CROP option back where we can set a fixed pixel dimension so that numerous images of various original sizes  will show a crop grid of the exact pixel dimension needed, eg. 1800 x 1200 px.

2. This same pixel dimension should be also the exported image's pixel dimension – not a single pixel more or less on either sides (as it used to be in earlier version).

3. Additionally: When a grid of a precise pixel dimension is stored as a preset in the crop tool (eg. 1800 x 1200 px), when activating this preset on a different image, a crop grid of these exact pixel dimensions should be launched (eg. 1800 x1200 px).

**Alternatives**
I can not think of an alternative to a _fixed pixel dimension crop grid_ to finally receive cropped images from various sources (cameras) with the exact same pixel dimensions after export, eg. for a photo book, an only gallery and so on ...

**Additional context**
The current _percentage crop_ is a 'nice to have' option, IMHO, but makes working with images from different sources (cameras) a real pain. Es detailled above, even presets cannot be reused when sources differ in dimensions.

**Comment by Nilvus** [comment]
Old crop & rotate never had such feature too. Crop is to select (crop so) part of image, and had never been to set size. Raw is mainly to process visually the image. It's better to use only export module to set size of final output.

**Comment by jenshannoschwalm** [comment]
Unfortunately the code in 3.8 & 4.0 sometimes showed a wrong crop size due to rounding. That has been fixed in #12185 so you will now be able to see the exact & correct size of the cropped area.

@sophisticatedDreamer Otherwise i don't get what your problem is. 
A preset for this module could be used for example to crop to the central part of your image or alike. If you need image files with fixed size, well, go for export settings.

**Comment by sophisticatedDreamer** [comment]
Thank you very much for the fast fix!
