### ISSUE TITLE
Store fine tuned masks as a preset(?) for re-use

### ISSUE THREAD

**Issue by sophisticatedDreamer** [darktable-org/darktable#12178]
In one part of my Astrophotography I make full disk images of the Sun and the Moon. On a regular basis I thus need to manipulate the background (everything else but the Sun or Moon) and thus I make use of a circular mask.

Currently, I have to re-define the size and position of the circular mask again and again, eg. with the CONTRAST module. When I store the contrast module settings together with a well defined an placed circular mask, _everything but the mask_ gets stored in the preset.

So I have to move and re-place the mask manually every single time while the (eg.) the contrast setting are immediately applied in the expected way.

**Describe the solution you'd like**
Either the presets should also store a mask in place (maybe as an option to be checked when wanted). Or the mask manager should allow to store a well defined mask as a preset which seems not to be possible, currently.

**Alternatives**
I believe some way to **storing a mask** for future use (later **dt** session, other collections, different context ...)

**Comment by jenshannoschwalm** [comment]
Well maybe you should have a deeper look into the manual or maybe as in places like pixls.us .
Just a few hints, i don't do that sort photography

I i would want to isolate background from very bright objects i would probably use a parametric mask instead of painting circles in any of the modules. And you can save a preset in that module and that holds the mask ...

Please concider to close this issue ...

**Comment by sophisticatedDreamer** [comment]
Thanks for the hint – I know and use all kind of masks and also occasional mixes of _drawn_ and _parametric_ masks. The latter are very useful ... though not in the mentioned case: My astronomic Sun and Moon images have dark and even black features, so when using a color / lightness based parametric mask the important surface features would be affected by the parametric mask, also.

_This must not happen._

> save a preset in that module and that holds the mask

This is exactly what I asked for in my OP. Unfortunately storing a maks within a module preset does not happen as expected:

- When storing a module preset including a mask, it is fully accessible and available for the rest of the session.
- When re-opening the same(!) collection again next time, everything is still fine.
- **But:** After putting fresh RAW images into a fresh folder, and start **dt** from a shell (Linux terminal) within that folder, like `darktable . &disown` the new images to be processed open nicely as always. They also can use the previously stored module presets ... but there is **NO MASK** available. NO MASK at all in the previously well set up and stored module preset:

Thus my feature request.

NB: If that helps, I could create a screencast for demonstration purposes.

**Comment by sophisticatedDreamer** [comment]
Thanks for the hint – I know and use all kind of masks and also occasional mixes of _drawn_ and _parametric_ masks. The latter are very useful ... though not in the mentioned case: My astronomic Sun and Moon images have dark and even black features, so when using a color / lightness based parametric mask the important surface features would be affected by the parametric mask, also.

_This must not happen._

> save a preset in that module and that holds the mask

This is exactly what I asked for in my OP. Unfortunately storing a maks within a module preset does not happen as expected:

- When storing a module preset including a mask, it is fully accessible and available for the rest of the session.
- When re-opening the same(!) collection again next time, everything is still fine.
- **But:** After putting fresh RAW images into a fresh folder, and start **dt** from a shell (Linux terminal) within that folder, like `darktable . &disown` the new images to be processed open nicely as always. They also can use the previously stored module presets ... but there is **NO MASK** available. NO MASK at all in the previously well set up and stored module preset:

Thus my feature request.

NB: If that helps, I could create a screencast for demonstration purposes.

**Comment by sophisticatedDreamer** [comment]
> I never checked, you say that a preset is still available and can be selected but it doesn't hold the mask?

Exactly: Module settings are stored in a preset, well defined mask for that special use case are not stored: _"No mask"_ after having left **dt** and start it again next time with a set of _new_ (read: not yet processed) files.

> You know you save presets and Reimport BTW?
Sorry, I probably don't understand this question. By 'saving a preset' I simply mean, I use a module's option to store the currrently tuned parameter set for future use, giving that parameter set a meaningful name.

 
> You use a different database?
No. Default database only. I never touch(ed) it.

**Comment by jenshannoschwalm** [comment]
1. You save a preset for a module incluing a mask, **but** you can not use the mask and maybe modify its position after you apply that preset later. That's the current status.
2. The preset are maintained in preferences->presets. Might not help you though.

**Comment by sophisticatedDreamer** [comment]
I understand ... so it's not possible.

I had expected, at least the so called **'Mask Manager'** in the left side modules of **dt**'s darkroom could do this. Sorrily, its three bar menu (aka 'hamburger menu') is grayed out and thus without function. I had hoped for options to **manage** (read: _organize_) masks of all kind there as the name implies.

Seems, I have to live by that ...

**Comment by sophisticatedDreamer** [comment]
I investigated a bit more and found that all I want (including the detailed mask) is stored in the **XMP** sidecar file. So a trivial **workaround** for my needs is now this:

1. Applying my fine tuned preset to one of those images (Sun, Moon full disk astrophotography) – **once only**, no need to do it ever again – a _full functional_ preset.
2. Storing that **XMP** file as a default, eg. as 'SunMoonFullDiskMask.xmp'
3. In a new project's folder, loop copy that default **XMP** to _'newfile.cr2.xmp'_ while the _shellscript_ in the same loop also renames the **Derived From** tag line in the **XMP** to fit the currently copied file.
5. Done

When this folder's content is then opened with _'dt . &disown'_ all files are instantly processed with the settings of their artificially created **XMP**, in principle ready to get exported right away from the **lighttable** without further treatment.

That's very nice!

As *dt* obviously is capable to write **mask parameters** and details to the sidecar **XMP** file – which I shamelessly reuse for my purpose – I really wonder why I was told this **mask storing** was not _available_ and will not be.

I'll wait for another day or two in case of further feedback or comments and then will close this ticket.

Thanks for listening.

**Comment by TurboGit** [comment]
The story is:
- It is stored into XMP as we need to be able to reload a picture with all the history. We can so give to someone the RAW + XMP and the whole dev process is there. Also, this gives the opportunity to backup your work.
- It is not stored on preset on purpose as a preset is meant to be applied to different images and most (all?) of the time it is not a good idea to propagate the mask to some other images.

**Comment by sophisticatedDreamer** [comment]
> [...] a preset is meant to be applied to different images and most (all?) of the time it is **not a good idea to propagate the mask to some other images**.

This is a good example of where practical experiences and preferences differ: What you call _"not a good idea"_ is exactly what I requested as a feature. This would be a blessing, a big relief to have in my workflow  because I need this all the time, for hundreds of images – thus my feature request.

[All my Sun and Moon images (eg.) on AstroBin](https://www.astrobin.com/users/firstLight/) utilize the exact same set of modules' presets, saved as an easy accessible **style** for fast application to many images.

So, a **style** is a _user defined_ set of modules and respective parameters that _a specific user_ (eg. _me_) wants to apply to (many) images over and over again or even to many images at once. I for one need controlled treatment and appearance over time, to serve continuity.

Unfortunately, I still have to open each and every image in the darkroom to manually position and apply the simple though fine tuned circular mask individually.

It is completely okay if _you_ cannot think of this as being a useful feature to be implemented due to your familiar photographic preferences and image processing habits.

For _me_ (and probably others) optionally(!) being able to storing a mask together with a _module preset_ or at least as a preset in the so called _Mask Manager_ would be a appreciated benefit.

I'm closing this feature request – please think about it

**Comment by sophisticatedDreamer** [comment]
20220724-1700h CEST: closed

**Comment by TurboGit** [comment]
> [All my Sun and Moon images (eg.) on AstroBin](https://www.astrobin.com/users/firstLight/) utilize the exact same set of modules' presets, saved as an easy accessible **style** for fast application to many images.

What I do in such situation is that I apply the preset to the first image of a series. I then enter this image and edit the mask to fit properly the lightning/color conditions (for parametric mask) and I do create drawn masks if needed. When I'm happy this the result on this image leader I do copy the module edit and past to all other images. This should answer your need hopefully.
