### ISSUE TITLE
HDR output support in viewport (HDR monitor)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [darktable-org/darktable#12173]
At the moment, I have to blindly work with HDR without seeing the correct result.
Please add HDR10_ST2084 output for HDR monitors.
Platform: Windows 10.

**Comment by ValZapod** [comment]
Or just connect mpv to it. Best way to do it.

**Comment by 0x4E69676874466F78** [comment]
@ValZapod 
> Or just connect mpv to it. Best way to do it.
Ewww... How?

**Comment by ValZapod** [comment]
Well, e.g. see this post, the images in this comment trigger HDR in mpv, so just send a RGB plane in PQ and BT.2020 and here you go! https://github.com/mpv-player/mpv/issues/10247#issuecomment-1141058203

**Comment by 0x4E69676874466F78** [comment]
@ValZapod with the same success, I can write a script that will reopen the HDR viewer for me. 
But thanks for trying.

**Comment by ValZapod** [comment]
> the same success, I can write a script that will reopen the HDR viewer for me.

Yes, that is the point. Just write a script or use mpv as a library. Because you will never be able to write all Vulkan, OpenGL, Directx11 code to support HDR. That will take ages to write.

>suggest to do export all the time?

Well, it should be fast with OpenGL.
