### ISSUE TITLE
Detect duplicate images using a hash on import

### ISSUE THREAD

**Issue by jhaiduce** [darktable-org/darktable#12180]
**Is your feature request related to a problem? Please describe.**
When importing images, Darktable doesn't detect when imported images are already present in the library.

**Describe the solution you'd like**
Darktable should keep hashes of all images in the library.db file, and check imported images against these hashes. Users should be given the option to skip duplicate images when importing.

**Alternatives**
It's possible to check other properties such as filename, modified time, size, etc. However, without a hash, Darktable will miss duplicates in cases where the file is renamed but not modified otherwise.

**Additional context**
A "select only new pictures" option was added to the import dialog in #11016, but that PR only checks date, filename, and timestamp to detect duplicates. The author of that PR claimed that using hashes would be too slow. However, at least two other photo management programs (Lightroom and Shotwell) already use hashes in this way. I can't speak for Lightroom, but I can say from experience that the import process with Shotwell is reasonably performant. An option can be provided to not use hashes for users that find them too slow.

**Comment by Nilvus** [comment]
Which darktable release do you use? Always good to precise it. Detection already exists, it's a new feature of darktable 4.0. See that: https://github.com/darktable-org/darktable/pull/11016

This doesn't use hash but other settings and can't works with previously imported images (it's normal as this need to be written in library (like for hash and your suggestion). So for images imported before implementing such feature, it's always too late.

**Comment by Nilvus** [comment]
Oh, and it's a duplicate (except your "hash" suggestion) of #11195. So better to not have 2 issues/FR for same thing. I so suggest you to amend (if you think it's needed #11195 FR. I let this issue open one or 2 days.

**Comment by jhaiduce** [comment]
> Which darktable release do you use?

I’m using 3.8

> Detection already exists, it's a new feature of darktable 4.0. See that: #11016

Note that I mentioned #11016 already; I opened this because I think hashes should be added to the implementation.

> for images imported before implementing such feature, it's always too late.

Not necessarily. Darktable could check library.db on startup and compute hashes for any images that don’t already have one. It might take a while, but it would only have to be done once.

> Oh, and it's a duplicate (except your "hash" suggestion) of https://github.com/darktable-org/darktable/issues/11195.

I hadn’t found that one in my search. I’ll add my comments to that one and close this.

**Comment by bogardon** [comment]
Please implement duplicate detection with hashes.
