### ISSUE TITLE
signed integer overflow in thumbtable

### ISSUE THREAD

**Issue by maruncz** [darktable-org/darktable#12196]
commit: a3245360c8ed700fa579414153bc242b9f112297

`/home/martin/c/darktable/src/dtgtk/thumbtable.c:261:53: runtime error: signed integer overflow: -2147483408 - 2147483647 cannot be represented in type 'int'`

this happens, if for loop above doesn't run any iteration, line 261 will then try to do `INT_MIN  + (some small number) - INT_MAX`
line 262 has the same issue.

this error is there from 9a6144a79c when this code was written by @AlicVB

**Comment by TurboGit** [comment]
@maruncz : Question, how do you trigger this issue ?

**Comment by maruncz** [comment]
i started darktable with empty library into lightable

**Comment by jenshannoschwalm** [comment]
@TurboGit we have a hot summer and after lots of heavy work always improving dt's user interface @AlicVB might just be either firefighting or relaxing at a beautiful part of the french atlantic coast ... maybe @maruncz would do the fix or i could step in? Pretty sure he wouldn't have objections...

**Comment by TurboGit** [comment]
Thanks @jenshannoschwalm , I have proposed a fix see #12245. A bit of code on my side :)
