### ISSUE TITLE
[Filmic RGB] request for minor improvements

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12204]
4.0

- _options_ tab
  - _color science_ tooltip only explains v3 and v4, v5 and v6 are missing
  - _preserve crominance_ tooltip says almost nothing...
- _look_ tab: I see it as a complement of the _scene_ one: I'd better place at the 2nd place, not at the 3rd like now

**Comment by elstoc** [comment]
> look tab: I see it as a complement of the scene one: I'd better place at the 2nd place, not at the 3rd like now

My understanding is that the tabs are in workflow order - you should work through them from left-to-right when processing. Reordering would mess this up.
