### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [darktable-org/darktable#12201]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@7h3h4ckv157) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by TurboGit** [comment]
> which I would be eager to share with you.

So let's share, I don't see any need for any action on our side.

**Comment by JamieSlome** [comment]
@TurboGit - sure, the report can be found directly here:
https://huntr.dev/bounties/22388f57-9555-4577-ad6a-cc72dbceb941/

It is private and only accessible to maintainers with repository write permissions 👍
