### ISSUE TITLE
[haze removal] exposure compensation needed

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12229]
The module haze removal works quite well, the only thing is that is reduces the luminosity of the image.

This isn't a problem if all the image is involved, but when a mask is used it's quite annoying to compensate the luminosity change.

What about a control of luminosity/exposure in the module itself?

**Comment by pitbuster** [comment]
Maybe it would be nice to enable the blend fulcrum in normal blend mode.
