### ISSUE TITLE
RFC - rotation in quick access panel

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12222]
When the rotation slider is added into the quick access panel we get the slider and we can adjust the rotation but this does not activate the way to adjust using the right-click to draw the line on the canvas directly.

Would be nice to have this supported when the module is activated from the quick access panel.

**Comment by TurboGit** [comment]
Why I need that... Because now that rotation is not done anymore in crop module it is a pain to have to open the rotation&perspective to get access to this control. Or maybe some other idea to get access to this control for straitening a picture.

**Comment by todd-prior** [comment]
I just map a double r press to activate the module then I can right drag to level... its pretty quick

**Comment by ptilopteri** [comment]
I map two different keys to rotate 1/2° each direction which enables
rotation and <right><mouse-drag> is automagically available

**Comment by jenshannoschwalm** [comment]
Midi device 😀

**Comment by ptilopteri** [comment]
something *most* photographers will not possess

**Comment by TurboGit** [comment]
> I just map a double r press to activate the module then I can right drag to level... its pretty quick

Sounds like a good idea indeed!

**Comment by TurboGit** [comment]
> Midi device grinning

The best, but I don't have one at the moment :)

**Comment by AlicVB** [comment]
Maybe we can also allow an "focus iop" 2 states button in the QAP, That would be esp. useful for rotate and for crop...
Of course we can use shortcuts for that (and that's what I use) but that would maybe be more discoverable, esp. for crop.

@dterrahe : What's your view on that, as you have worked quite a lot in this area ?

**Comment by dterrahe** [comment]
I don't think we should have a separate module focus state for qap that is somehow separate from the focus state of the full list of modules in the background. Focus states are confusing enough.

However, if a module is focused in the background, and it has a header in the qap, then that header could indicate the focus state as well. And we could toggle focused state by clicking on the header. Or moving any of the sliders (the rot&pers module in the background does seem to get focused when the rotation slider is moved in the qap)

And then if a module has focus, the gui for it (crop borders or right-drag to adjust rotation or whatever) should be active independent of whether the qap is shown or not. This does not currently seem to be the case.

Pressing the "full version" button in the qap header is a reasonably discoverable way of getting the full functionality (and equivalent to the _show_ toggle shortcut @AlicVB and @todd-prior presumably are using?), but has the drawback that you have to click on the qap again afterwards to get back.
