### ISSUE TITLE
[Feature Request] Security option to ask for confirmation when re-rating large groups of images

### ISSUE THREAD

**Issue by prg318** [darktable-org/darktable#12225]
# Use case
User has a large group of previously rated images selected and accidentally presses 1,2,3,4,5 or r.  There is not a way to "undo" this in lighttable (that I am aware of).  In addition, writing all the sidecar information for a very large group of images (especially over a network share) can be very time consuming.

# Feature Request
Option in "security" to "ask before re-rating large groups of images" where "large group of images" variable is configurable (perhaps 20 would be a relatively sane initial value).

# Additional Info
This wouldn't need to be a default option, but it would be useful to prevent a) overriden ratings for users without backups and b) a potentially time consuming sidecar write operation that was unintentional.

Personally, I use git to manage my sidecar files but would still appreciate a feature like this to prevent me or others from accidentally doing this.  Let me know what others think about this idea and if I can provide any additional clarification.

**Comment by wilecoyote2015** [comment]
In principle, I strongly support this request, as this happened to me more than once.
But wouldn't it be a simpler (and more versatile) alternative to add rating actions to the undo stack? 
Then, ratings could simply be undone.

**Comment by prg318** [comment]
> In principle, I strongly support this request, as this happened to me more than once. But wouldn't it be a simpler (and more versatile) alternative to add rating actions to the undo stack? Then, ratings could simply be undone.

Adding rating actions to the undo stack would also be a welcomed feature (IMO).  But I still think some optional security around re-ranking large numbers of images should exist.

Another thing to consider is: re-ranking a large number of photos takes quite a while to write all the sidecar data.  Undoing, while an excellent feature to have, would also take quite a while to revert all the sidecar files as well. 

I would be very interesting in seeing darktable incorporate ratings into the undo stack, and while very related to this use case, it may be a larger discussion entirely (as I'm not sure very familiar with darktable internals).  I'd be happy to hear others' input on these ideas.

**Comment by TurboGit** [comment]
> User has a large group of previously rated images selected and accidentally presses 1,2,3,4,5 or r. There is not a way to "undo" this in lighttable (that I am aware of).

Yes there is, just press `ctrl-z` (undo action). So the security belt is already there.

> I would be very interesting in seeing darktable incorporate ratings into the undo stack

Why do you think it is no there?

https://docs.darktable.org/usermanual/4.0/en/lighttable/undo-redo/

(and this was already implemented in previous version since some time now).

**Comment by prg318** [comment]
> > User has a large group of previously rated images selected and accidentally presses 1,2,3,4,5 or r. There is not a way to "undo" this in lighttable (that I am aware of).
> 
> Yes there is, just press `ctrl-z` (undo action). So the security belt is already there.
> 
> > I would be very interesting in seeing darktable incorporate ratings into the undo stack
> 
> Why do you think it is not there?
> 
> https://docs.darktable.org/usermanual/4.0/en/lighttable/undo-redo/
> 
> (and this was already implemented in previous version since some time now).

Thanks for the heads up - I knew that the undo feature was available, but wasn't aware that it included ranking changes.  In my particular instance, I never noticed that I accidentally pressed "r" with a large selection until much later - I was mostly working in darkroom and must have quickly made a mistake with a large group selected in lightroom.  Apologies on not being aware that ratings are in the undo-stack - that's a great feature to have.

I still think it may be an improvement to optionally have a warning when reranking a large number of images.  This can prevent a lengthy disk write for the accidental ranking and a lengthy disk write for the undo.  On top of that, there are situations where the mistake can get "buried" in the undo stack if the user is not immediately aware of their mistake.

I would edit my previous posts to remove my comments about the undo-stack, but I don't want to make the conversation harder to follow.  I would love to hear other opinions on including an optional security option to prevent writing a bunch of sidecar files (even perhaps similar to the UI that appears when attempting to delete a tag that references a large number of photos, except optional)

**Comment by TurboGit** [comment]
> Thanks for the heads up - I knew that the undo feature was available, but wasn't aware that it included ranking changes.

Be sure to read the doc I pointed as it not only include ranking but practically everything that can be changed (even style and duplicating images).

**Comment by ptilopteri** [comment]
at some point, one must become aware of his actions and take 
necessary precautions such as backups, etc
the bloat necessary to undue/warn/correct every possible inadvertent 
action one might take would be unbelievable.  
enough is enough, care when editing is a necessary condition, we are adults.

**Comment by prg318** [comment]
> at some point, one must become aware of his actions and take necessary precautions such as backups, etc the bloat necessary to undue/warn/correct every possible inadvertent action one might take would be unbelievable. enough is enough, care when editing is a necessary condition, we are adults.

While I understand your concern, why even have the security preferences tab at all if every user is an adult that never makes any mistakes?

Like I had previously mentioned, this caused absolutely no hardship for me.  For what its worth, I am a careful adult and have been using git to track my sidecar files.  I just think it may be worthwhile to consider options like these, especially when darktable has an entire panel of options like these.  I wanted to offer my suggestion and would be happy to contribute a patch if there was a positive attitude from the developers towards this type of improvement.

As I also mentioned, I'm proposing the option to be disabled by default - so I fail to see how this adds any more "bloat" than any of the other options in the security preferences tab.  I fail to see how this issue tries to encompass "every possible inadvertent action one might take would be unbelievable.".  It can simply help prevent time consuming disk writes, reverts, and backups because a user may have pressed "r" in the wrong window.

**Comment by TurboGit** [comment]
We add security option for possibly destructive action having no way to recover. Here we have undo and we try to restrict at the minimum the number of options.

**Comment by prg318** [comment]
If a security option isn't palatable to the developers (which I do understand the reasoning), then I would alter this feature request to improve the user interface when updating a large number of sidecar files (as mentioned in a previous comment edit which I will repaste below) .  A user that has some feedback that a bulk metadata write is taking place is much more likely to catch a potential mistake and utilize the undo stack to correct it.

The import UI does an excellent job of displaying the import progress:  it shows the progress of the images being imported  (in what I believe is near the bottom right corner of the window)and the UI remains responsive while this is taking place.  When performing a bulk metadata change like this (especially on a slower disk), there is no UI indication of what is being done, and the window is not repainted until the operation has completed.  It would be great if the UI remained responsive during bulk sidecar writes and potentially displayed progress feedback (like how import does)

Here's an idea I mentioned earlier in the thread.

Aside 1 - when I accidentally rejected the ~8k photos in my lighttable, the darktable UI was hung until the operation was complete (on Linux anyway). I mistakenly assumed that my PC/GPU was having other issues during this time. It may also make sense to have UI showing the progress of the mass operation; similar to how the import UI works ("Rejecting photo 300/4000"; "One starring photo 350/4000"; "Modifying sidecar 400/4000"; etc). I likely would have noticed that I had made a mistake of the UI was responding during the period that darktable was very busy updating the sidecar files on my disk (FWIW: Definitely not shifting blame here - this was my mistake that I've rectified, but it has caused me to think about potential UI improvements for this awesome software).
Thanks again for everyone who has put in huge amounts of efforts on this outstanding software.

**Comment by ptilopteri** [comment]
so we would incorporate a windows standard, 
"Do you realllly want to perform this action"
and incorporate an extra operation into every action.
sorry, I am against any question of actions I decide to 
perform.  if I did it wrong, I am capable of making a 
correction.  if not, then I was careless and should 
have know better.  (and that has happened, but ... )

**Comment by prg318** [comment]
> so we would incorporate a windows standard, "Do you realllly want to perform this action" and incorporate an extra operation into every action. sorry, I am against any question of actions I decide to perform. if I did it wrong, I am capable of making a correction. if not, then I was careless and should have know better. (and that has happened, but ... )

You may want to considering reading this issue in its entity for full comprehension purposes.  I don't think anyone is suggesting Microsoft Windows behavior in this thread.  A suggestion was brought up for an additional security option, but as the discussion in this issue progresses, it seems like more responsive UI may help make these bulk actions more noticeably and improve the UX generally.

While I appreciate your enthusiasm and I totally understand the distaste for Microsoft Windows, user interface that threats the user like a child, and non-configurable options that get in the users way.  But at this point, those feelings aren't exactly relevant to the issue that is being discussed here, and they aren't being suggested for inclusion in darktable.

**Comment by ralfbrown** [comment]
The GUI seems to hang because the sidecars are written from the GUI thread.  The solution to that is to fire off a background job (which is what imports use).
See #8909 and #9724.
