### ISSUE TITLE
Setting for JPEG thumbnail in culling layout not working properly

### ISSUE THREAD

**Issue by 7osema** [darktable-org/darktable#12224]
**Introduction**
There is a feature in darktable where you can see the embedded JPEG from the RAW files. To activate it, you go to settings > lightable > thumbnails and set "use raw file instead of embedded JPEG from size" to "never".

After that, the embedded JPEG should be used for thumbnails, but that is not the case if the image is bigger than some threshold that I am not able to define. 

**Describe the bug/issue**

**To Reproduce**
1. Go to settings > lighttable > thumnails
2. Set "use raw file instead of embedded JPEG from size" to "never"
3. Use some not yet edited RAWs files in the lighttable
4. Activate culling layout in lighttable
5. Set number of visible images in culling layout to 2
6. Observe that the embedded JPEG is not used
7. Now set number of visible images in culling layout to 3 or 4 (the number may depend of the screen resolution)
8. Observe that when the image size gets over a threshold, the JPEG is being used.

**Expected behavior**
The JPEG should be used always for the culling mode when the setting is configured for that.

**Screenshots**
No embedded JPEG is shown:
![culling_no_embedded_jpeg](https://user-images.githubusercontent.com/203212/180606598-d70836d9-d89f-4d6f-a462-9a8de7a79ede.png)

Embedded JPEG is shown:
![culling_with_embedded_jpeg](https://user-images.githubusercontent.com/203212/180606607-404126c3-0ae9-4600-bc2b-a813754c81c6.png)

**Pixls.us thread**
https://discuss.pixls.us/t/jpeg-thumbnail-in-culling-layout-not-working-with-2-images/31243/3

**Platform**
I was able to reproduce this issue with fresh installations of darktable 4.0.0 on windows, macos and ubuntu studio.

**Comment by 7osema** [comment]
Hi @AlicVB ,

I finally created the issue here. I don't know how to assign it to you.

Thanks!

**Comment by jenshannoschwalm** [comment]
How do you know its not an enlarged version of the jpeg? Also many raws have multiple jpegs...

**Comment by 7osema** [comment]
Thanks for you comment @jenshannoschwalm .

If it were an enlarged version of the jpeg it should look like the smaller version, but that’s not the case. The larger version looks completely different as the small version. I thought it was clear in the screenshots above.

Did you asked because you cannot reproduce the issue?

I was also thinking that maybe the embedded JPEG of my camera it’s small and when a larger version of it should be displayed in culling mode, darktable fallbacks to an own rendering of the RAW file. 

But I don’t really know.

**Comment by jenshannoschwalm** [comment]
> Did you asked because you cannot reproduce the issue?

No :-) for me this is simply not an "issue" as i would say the embedded jpegs (both in raws or other formats) should only be taken as an approximated "thumbnail" without real significance. And **only** for performance reasons. In culling mode i would personally always expect a darktable-rendered image.

**Comment by 7osema** [comment]
Ok, then what is the purpose of the configuration setting that I mentioned in the issue? Maybe I did not understand what the configuration setting is for. Anyway @AlicVB already acknowledged this as an issue in the pixls forum.

**Comment by jenshannoschwalm** [comment]
For me the setting is about light room mode. (not culling) Taking the embedded jpeg instead of dt pipeline is  just for performance (by far faster)

At least that's how I understood the docs.

**Comment by 7osema** [comment]
I thought culling mode is somewhat a “view” of the light table mode. So that the settings under light table apply also to the culling functionality.

**Comment by TurboGit** [comment]
> For me the setting is about light room mode. (not culling) Taking the embedded jpeg instead of dt pipeline is just for performance (by far faster)

Yes, that's exactly that.

**Comment by 7osema** [comment]
@jenshannoschwalm @TurboGit it seems the setting applies also for the culling mode. The reason it is not working is the embedded JPEG in the camera that is too small.

Anyway, thank you for your input and your time. The issue can be closed.
