### ISSUE TITLE
proposal for retouch module in the darkroom.

### ISSUE THREAD

**Issue by cjose38** [darktable-org/darktable#12242]
hello, this is the first time that I connect on github and I browse on sight because it seems to me to be a very big factory.
I hope I'm in the right place to make a suggestion.

in the retouch module with the copy + path tool, the possibility of rotating the copy area (like an ellipse with Ctrl + mouse) would be a plus.

I take the example of a bird for which we want to make a branch disappear, its curve evolves and it is easy to make a point coincide with the plumage but the second is shifted. By "rotating" the source, the 2 points can be adjusted very quickly while ensuring the continuity of the silhouette.

I hope I was understandable.

best wishes.

jose

**Comment by Hpbirkeland** [comment]
This is something I have missed too. Especially when editing a series of images of one subject but switching between landscape and portrait format.

**Comment by ralfbrown** [comment]
Closing in favor of #14026.
