### ISSUE TITLE
Noise profile for Canon EOS T8i / 850D

### ISSUE THREAD

**Issue by lphilpot** [darktable-org/darktable#12247]
For noise profiles, please also attach the entire archive with `.pdf` plots.
[darktable-noiseprofile-20220729.tar.gz](https://github.com/darktable-org/darktable/files/9222625/darktable-noiseprofile-20220729.tar.gz)

**Comment by rawfiner** [comment]
The profile looks good, thank you!
I will integrate it in the coming weeks.

**Comment by lphilpot** [comment]
Dumb question, but once integrated and installed I can dispense with the "--noiseprofiles <path>" parameter I'm currently using, correct? Thanks.

**Comment by rawfiner** [comment]
Yes, you won't need the --noiseprofiles anymore. Sorry for the delay, I do not forget you, I am a bit busy these days...

**Comment by lphilpot** [comment]
No worries on the delay and thanks for the clarification. Appreciate your help.

**Comment by lphilpot** [comment]
**_One quick note..._** 

It may be a misunderstanding on my part (?) but just in case there's something wrong with the profile (although you said it looks good) I want to mention this before it's integrated. 

When I open an image in DT 4 / Windows 11 and activate denoise (profiled), the only profile I see is "generic poissonian". For example, the image is shot at ISO 320, I shot a profile image at ISO 320 and there's a line in the JSON file for ISO 320 (confirmed --noiseprofiles path is correct):

` {"name": "EOS Rebel T8i iso 320", "iso": 320, "a": [1.96612206489124e-05, 8.46086964099575e-06, 1.63375098828191e-05], "b": [2.55025577870898e-08, 1.8442672449966e-08, 2.6567861200103e-08]},`

So per the module ocs I would expect to see a profile named something like "EOS Rebel T8i iso 320" but I don't. My camera maker and model are recognized elsewhere in DT, lens correction lists it exactly as above.

If I need to open an issue on this I'll be glad to, but just wanted to mention it first.

Thanks.

**Comment by rawfiner** [comment]
This can happen when there is a difference between the name of the camera that the noiseprofile script detected and put in the json file, and the name darktable sees when you open a raw file. Can you check it is written exactly the same way in both cases?

**Comment by kmilos** [comment]
I would guess the profile would have to go under the "EOS 850D" name.

**Comment by lphilpot** [comment]
It appears to be correct.

_darktable image information module_
model: `EOS Rebel T8i`
maker: `Canon`
ISO: `320`

_lens correction module (for example)_
`Canon, EOS Rebel T8i`

_JSON file (excerpt)_
```
  "noiseprofiles": [
    {
      "maker": "Canon",
      "models": [
        {
          "comment": "eos rebel t8i contributed by len",
          "model": "EOS Rebel T8i",
          "profiles": [

            ...

            {"name": "EOS Rebel T8i iso 320", "iso": 320, "a": [1.96612206489124e-05, 8.46086964099575e-06, 1.63375098828191e-05], "b": [2.55025577870898e-08, 1.8442672449966e-08, 2.6567861200103e-08]},
```

_exiftool run against the RAW file, grepped out any references to name, maker, etc._
```
C:\data\images\Our-photos\_scratch>exiftool IMG_2550.CR3 | egrep -i "maker|model|Canon|T8i|850D"
MIME Type                       : image/x-canon-cr3
Major Brand                     : Canon Raw (.CRX)
Compressor Version              : CanonCR3_001/00.09.00/00.00.00
Make                            : Canon
Camera Model Name               : Canon EOS Rebel T8i
Canon Flash Mode                : Off
Canon Image Size                : n/a
Canon Exposure Mode             : Aperture-priority AE
Lens Type                       : Canon EF 28-80mm f/2.8-4L USM or Sigma Lens
Canon Image Type                : Canon EOS Rebel T8i
Canon Firmware Version          : Firmware Version 1.0.0
Canon Model ID                  : EOS Rebel T8i / 850D / X10i
Canon Image Width               : 6000
Canon Image Height              : 4000
Lens Model                      :
Color Data Version              : 19 (90D/850D/M6mkII/M200)
```

While the camera is named 850D outside the US (except in Japan), in this locale it's "T8i" so that looks right...

Thanks.

**Comment by lphilpot** [comment]
I can link to the raw file if desired.

**Comment by lphilpot** [comment]
Sorry for the multiple messages but just thought about this. I'm running Bill's nightly build 4.1.0+109~g4ea7e5d5c. I've not further upgraded due to several reports of issues with newer builds, although they're tapering off now.

**Comment by kmilos** [comment]
You'll have to dig into noise profile matching code to figure out if canonical name (850D) is used, or the alias (as read from exif).

**Comment by kmilos** [comment]
By the time we exchanged all these messages you could have tried the name change in the JSON file already...

**Comment by lphilpot** [comment]
I didn't realize it was simple as that. It matches on 850D and appears to work properly. The updated JSON is attached, if that works with the workflow here. If not, let me know where to send it.

Thanks.
[Canon_850D_noise_presets.zip](https://github.com/darktable-org/darktable/files/9435786/Canon_850D_noise_presets.zip)

**Comment by rawfiner** [comment]
> I can link to the raw file if desired.

Yes please. I will test and modify the json if needed when integrating. Thanks!

**Comment by lphilpot** [comment]
It's slightly too large to attache. Here's a zipfile of the raw file: https://drive.google.com/file/d/1nykvpblZR7hyKONIt-eRMs8GpwSaiZCT/view?usp=sharing

Please let me know after you download and I'll delete it from my Google Drive.

Thanks.

**Comment by rawfiner** [comment]
> I didn't realize it was simple as that. It matches on 850D and appears to work properly. The updated JSON is attached, if that works with the workflow here. If not, let me know where to send it.

Perfect thanks for the test!


> Please let me know after you download and I'll delete it from my Google Drive.

I downloaded it

**Comment by lphilpot** [comment]
Thank you.
