### ISSUE TITLE
Sorting criterion reset

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#12248]
**Describe the bug/issue**
After setting a sort criterion, in the top most center menu and selecting the collection to view, the criterion is reset to default.

**To Reproduce**
Enter the Lighttable mode
0. on the top menu, in _Sort by_ select for instance _Full path_ (_cf._ Step0.png)
1. go to the left panel and type a search criterion
2. double-click the result you want to work on
3. the selection made in step 0 is reset to its default (_cf._ Steps1to3.png).

**Expected behavior**
I think the setting in step 0 ought to be kept, avoiding to have to set it again after selecting each collection to work on.
At least, if this is not a bug, add the ability to lock it.

**Screenshots**
![Step0](https://user-images.githubusercontent.com/49912948/181828099-6b311c04-b935-4559-ae1f-0d056a11094b.png)
![Steps1to3](https://user-images.githubusercontent.com/49912948/181828102-7bff1bf1-ba8a-4490-9c9a-8316726419bc.png)

**Platform**

* darktable version : 4.0
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04

**Comment by dterrahe** [comment]
This does not seem to happen anymore on my side. Please reopen this issue if you still see the bug in 4.0.1 or current master.
