### ISSUE TITLE
Panasonic DMC-G2

### ISSUE THREAD

**Issue by chris4git** [darktable-org/darktable#12246]
Hi,

this is a new sample for the RW2 format from DMC-G2 as previous samples posted on raw.pixl.us months ago seem not have been taken into account.

**Comment by kmilos** [comment]
No need to open a new issue for this, please close as duplicate of https://github.com/darktable-org/darktable/issues/10787 @Nilvus

**Comment by Nilvus** [comment]
Closing so. @chris4git: thanks for providing samples. Just think about searching before posting.
