### ISSUE TITLE
[Crawler] repeatedly ask due to updated xmp-files, but that is NOT TRUE

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#12257]
**Describe the bug/issue**
As in the title, I get very annoyingly often the crawler message, that updated xmp-files have been found. I am struggling with this already since some time... (months).

Sometimes it stops for weeks and suddenly it comes back. 

I open dt. most of the time I chose the db version, sometimes I chose the xmp-version as I know I have not touched them. Close dt. open it and either asks for exactly the same files just new timestamps, sometimes other files

**To Reproduce**

See above.

**Expected behavior**
Crawler should only kick in, when really needed

**Screenshots**
I have not touched these files and at least some of them where not even in my lighttable view today
![Screenshot_20220731_143811](https://user-images.githubusercontent.com/49004103/182032200-6d524ffe-5be7-4ce7-83f2-5877acad9ada.png)

**Platform**
* darktable version : 4.1.0+109~g4ea7e5d5c
* OS                : Linux - kernel 5.18.15-gentoo
* Distro            : Gentoo Base System release 2.8
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-515.57
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.4
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.34
* gcc               : x86_64-pc-linux-gnu-11.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with versions ever since 3.9.x**
 - Can you reproduce with a RAW or Jpeg or both? **RAW and other (TIFF) files effected**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **n.a.**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **n.a.**
 - Do you use lua scripts? **no**

**Comment by AxelG-DE** [comment]
> Do you have Preferences > Storage > "look for updated xmp files on startup" ON ?

Indeed!
Function is wanted, switching off would be symptoms fighting only.

**Comment by AxelG-DE** [comment]
it really drives me nuts....

three or four times in a row I selected: "keep database edit", so maybe it is correct, that the xmp then getting updated today. 
But then db should now about that and not tell me next time, there is a diff between xmp and db....

so the only thing I did in those 37s was what I said above and close dt. Only when I now say "keep xmp edit", it keeps silent. So something is wrong either with my db or with the db functionality in dt

![Screenshot_20220815_094612](https://user-images.githubusercontent.com/49004103/184596584-64175db9-ec6b-4c9f-a350-be0b2f52eb13.png)

**Comment by AxelG-DE** [comment]
**[update 10th Oct. 2022]**

I think the prob is not alone the crawler, if at all. 

Today I experienced again. I chose "keep database edit" and get asked again and again, until I give up and chose "keep xmp-edit" (which indeed I wouldn't like to do in a first attempt).

The first attempt you could not see, where the time difference was ~78 days but I did not touch those pics, at least not w/o properly closing dt. So why the xmp's getting touched w/o the db notice it? Annoying to me and it is there already for long time and I donno what is different, when it leaves me alone for weeks :'-( (thanks for reproduce-ability)

I put a screenrecording here (thanks to @andabata for storing it, as it has 35MB)
https://shell.kees.nl/dt/Crawler_20221010-2022-10-10_19.28.05.mp4

- I recorded both screens, so one can see, what I did (not) do
- when dt disappears, I used alt+f4

@TurboGit do you have an idea, whom I could ping for that (sorry I am not familiar with _git blame_ or such)

**Comment by AxelG-DE** [comment]
yeah sorry, maybe it was not a smart idea to record both screens....
anyhow you wouldn't see as much, just it is always the same pics and the time is set to the moment you take the action...

I will do my best to provide the above mentioned DB value and xmp and hope @aurelienpierre might get a good idea by then.

Thanks for flagging

**Comment by AxelG-DE** [comment]
So it took me some time (as in between I had other things to do), but here we go:

$ echo "select * from images where id=237452" | sqlite3 ~/.config/darktable/library.db
`237452|102869|374|5504|3672|2018-05-01_162320_DSC02673.ARW|SONY|DSC-RX100||0.000500000023748726|1.79999995231628|125.0|10.3999996185303|0.0|63660788601000000|1604|4887|3257|2.69230771064758|0|||800|16620|||0|||||||0|1|2|1665434702|38|441127501037569|1.5||63689749584000000|63801031225844387||`

The corresponding .xmp is (txt is just renamed for acceptance):
[2018-05-01_162320_DSC02673_01.ARW.xmp.txt](https://github.com/darktable-org/darktable/files/9803196/2018-05-01_162320_DSC02673_01.ARW.xmp.txt)

$ echo "select * from images where id=237450" | sqlite3 ~/.config/darktable/library.db
`237450|104695|378|6032|4032|2018-05-04_172534_AG7_4687.NEF|NIKON CORPORATION|NIKON D750|Sigma 35mm F1.4 DG HSM|0.0020000000949949|11.0|100.0|35.0|6.6834397315979|63661051529000000|1605|5053|2526|1.0|0|||600|15520|||0|||||||0|3|3|1665432021|55|448965816352774|2.0||63689749709000000|63801028794754366||
`
And the corresponding .xmp (txt is just renamed for acceptance):
[2018-05-04_172534_AG7_4687.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/9803250/2018-05-04_172534_AG7_4687.NEF.xmp.txt)

@TurboGit the output does not mean anything to me, so did I do the things right? :)

**Comment by TurboGit** [comment]
@AxelG-DE : Do you have the corresponding screenshot of the dialog?

**Comment by TurboGit** [comment]
Fact is that the timestamps on the XMP and DB are equals. So I'd like to see the dialog to check who is right in the dialog it will help finding the wrong side and so the possible code doing wrong conversion. TIA.

**Comment by AxelG-DE** [comment]
The day above things happened, it looked like:
![Screenshot_20221012_174415](https://user-images.githubusercontent.com/49004103/196270989-32c1b031-8256-4dfc-a18e-aefd24482437.png)

after I created above report, I clicked once on "keep database edit" and now I get:
![Screenshot_20221017_215557](https://user-images.githubusercontent.com/49004103/196271057-f1947af5-7aa9-47bf-9586-072a4f6372aa.png)

If I would now click on "keep xmp-edit" it will keep silent (for a while)......

**Comment by TurboGit** [comment]
I've read the code for the crawler and to me it is really broken, so the best for now is to disable the checks.

A note about what is possibly happening:
- we check the write timestamp
- we get the internal DB write timestamp
- we use the last modified time as timestamp for the XMP
- if the DB is more recent than XMP, we write the XMP... creating a new xmp file with the current time

You guessed... Next time the DB is then older... Someone with free cycles should have a look to fix that.

**Comment by TurboGit** [comment]
@AxelG-DE : You may want to test the fix here : #13298.

**Comment by AxelG-DE** [comment]
Sorry for my late reply, very busy recently. I will test it. ATM crawler is off :-)

**Comment by TurboGit** [comment]
@AxelG-DE : No problem and there is no urgency. TIA.

**Comment by AxelG-DE** [comment]
I tested it and had the following obervations (all might be unrelated)
- first start I got a lot of photos with changed xmps. I accepted xmp version and writing to db took quite log
- afterwards, dt behaves sticky, e.g. after change the rating from 2* to 3* (where filter is set to =2) and then select another pic in darkroom's film strip
- also I got "ERROR in lualib, couldn't find a container for Selected Images path', this should never happen" but no other errors
- No I cleaned out that PR again and still dt is stalling from time to time.
- Even w/o that PR currently no crawler messages (but now deactivated again)
- I  might need to run with -d perf?

**Comment by TurboGit** [comment]
> * afterwards, dt behaves sticky, e.g. after change the rating from 2* to 3* (where filter is set to =2) and then select another pic in darkroom's film strip

Sorry I don't get this... maybe an English issue on my side. Can you clarify?

Yes, probably worth using `-d perf` to see what is done when dt stall. But right probably not related to the crawler has it is run only once when starting darktable. The lualib issue is certainly not related.

**Comment by AxelG-DE** [comment]
My English was bad, not yours, sorry.

Also I learned later, that I have had a severe LVM2 issue thanks to sensitive changes by the gentoo team (solved now).

I will test again later. Pitty is, even before that PR I had quiet times, so it is hard to say it works, only "no obvious problems" ;-)

**Comment by AxelG-DE** [comment]
So, I tested again. even provoked changes, where I touched a set of .xmp files and they got detected correctly. 
dt on and off several times with no issues...
Fine with me, as I can see it today :) (cover your ass phrase LoL)

**Comment by TurboGit** [comment]
@AxelG-DE : Thanks for checking, good to see this is better than current implementation. I'll record for 4.4 and we will see if more fixes are needed eventually.

**Comment by AxelG-DE** [comment]
@TurboGit you are always very welcome, particularly you were working on my headaches :)

As I am using [dt.bldr.sh](https://github.com/jade-nl/dt.bldr), I needed to eject ithis PR again, so I can follow master. Therefore I cannot easily provide a long term testing. But I will report anything I find after it is merged, indeed.
