### ISSUE TITLE
Fujifilm X-T4: failed to read white balance information from RAF file

### ISSUE THREAD

**Issue by fnino** [darktable-org/darktable#12263]
**Introduction**
_When opening a raw fujifilm RAF file from within darktable, I get the message "failed to read camera white balance information from 20220727_0018.RAF file".  And "please check the camera model is supported", etc._

---------------------------------------------------------------

**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

When opening a raw fujifilm RAF file from within darktable, I get the message "failed to read camera white balance information from 20220727_0018.RAF file".  And "please check the camera model is supported", etc.

**To Reproduce**

Import the RAF file  linked in my google drive and try to open it in darkroom.

https://drive.google.com/file/d/1nKVEnO5hCaotoBn_hzIgSdRn_azeawBZ/view?usp=sharing

**Expected behavior**

The photo is viewed in darktable

**Screenshots**

<img width="566" alt="Capture d’écran 2022-08-01 à 20 02 08" src="https://user-images.githubusercontent.com/8818267/182214091-114f8a40-a5c3-4853-a60c-8c53707875d1.png">

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.0 (downloaded from .dmg file in darktable.org)
* OS                :  OSx Monterrey on Macbook pro M1

**Comment by kmilos** [comment]
Is this perhaps a "non-lossless"/lossy compressed RAF file? If so, it is a [known issue](https://github.com/darktable-org/rawspeed/issues/232), so please close this one as a duplicate.

Uncompressed and lossless compressed should work fine.

**Comment by kmilos** [comment]
There was also an issue w/ some older firmware outputting JPEG instead of RAF: https://github.com/darktable-org/darktable/issues/10566

Please search before opening new issues: https://github.com/darktable-org/darktable/issues/7997

**Comment by Nilvus** [comment]
So closing. Thanks @kmilos

**Comment by fnino** [comment]
I confirm my camera output was in (not-lossless) compressed RAF format.  Thanks
