### ISSUE TITLE
Feature request: increased LUT3D flexibility

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#12261]
This is coming out of discussion in https://github.com/darktable-org/darktable/issues/10709 and https://github.com/darktable-org/darktable/pull/12260

The improved LUT3D module should:

- not assume input LUT profile = output LUT profile (i.e. separate the single LUT "application" profile to an input one and and output one); there are numerous LUTs that transfer from a wide gamut, log encoded space to a narrower/display one using some creative style...
- support input & output LUT profiles from ICC files (from user or system supplied `color/in` and/or `color/out`) and also use the existing built-in (working?) profile list, potentially deprecating the currently fixed and limited list (i.e. behave similar to working profiles list of the `colorin` module)
- optionally expose intent control for the working->lut_input and lut_output->working profile transforms

**Comment by aurelienpierre** [comment]
> not assume input LUT profile = output LUT profile (i.e. separate the single LUT "application" profile to an input one and and output one); there are numerous LUTs that transfer from a wide gamut, log encoded space to a narrower/display one using some creative style...

That makes no sense. Or, by "profile", you actually mean "color space" ? In any case, having LUTs do the color space conversion removes any color traceability and voids the guaranty. Moreover, those log-encoded RGB belong only to cinema.

> support input & output LUT profiles from ICC files (from user or system supplied color/in and/or color/out) and also use the existing built-in (working?) profile list, potentially deprecating the currently fixed and limited list (i.e. behave similar to working profiles list of the colorin module)

What problem is that supposed to solve ? Supporting stuff for the sake of supporting stuff is nonsensical, especially since ICC profiles are already supported where they should.

This FR sounds like someone woke up with grand ideas regarding features but no actual use case.

**Comment by phweyland** [comment]
LUT3D could be used for other use cases than color grading.
There is some room between raw data and colorin which fits with the limit [0,1] domain and would require to have different input and output color spaces. For lack of LOG raw image I've never checked this case.

**Comment by kmilos** [comment]
@parafin I wasn't really planning on working on https://github.com/darktable-org/darktable/pull/12265, so please feel free to take it over.

**Comment by parafin** [comment]
If there's noone working on this, I might add ProPhoto to the list, but I doubt I'll have enough motivation to tackle other points.
