### ISSUE TITLE
darktable-gen-noiseprofile incorrectly reads extended ISO settings from Z 6ii

### ISSUE THREAD

**Issue by TekCastPork** [darktable-org/darktable#12264]
**Introduction**

When trying to generate a noise profile for the Nikon Z 6ii, the `darktable-gen-noiseprofile` script uses incorrect ISO values for any images taken using the Lo and Hi extended ISO ranges. Everything else seems to work though, just the ISO is not the expected value for each image.

**To Reproduce**

1. Extract input images into a folder/directory
2. Run the `darktable-gen-noiseprofile` script on input images
3. Wait for script completion
4. Check noise results pdf and presets JSON file (the console output can also be used to check for reproduction when it detects the images)

[Input Images.zip](https://drive.google.com/file/d/1dXCMAwzh4NfpobgUIvb0gNEMadYvnqG6/view?usp=sharing) (970MB of raw .NEF images)

**Expected behavior**

ISO values for expected behaviour come from darktable itself as well as EXIF metadata when exiv2 is manually executed:

* DSC_5122 should have an ISO of 50 (Lo 1.0)
* DSC_5123 should have an ISO of 63 (Lo 0.7)
* DSC_5124 should have an ISO of 79 (Lo 0.3)
* DSC_5153 should have an ISO of 64508 (Hi 0.3)
* DSC_5154 should have an ISO of 81275 (Hi 0.7)
* DSC_5156 should have an ISO of 102400 (Hi 1.0)
* DSC_5157 should have an ISO of 204800 (Hi 2.0)

**Actual behavior**

Script PDF, presets.json, and console output report the following:

* DSC_5122 has an ISO of 48
* DSC_5123 has an ISO of 52
* DSC_5124 has an ISO of 56
* DSC_5153 has an ISO of 172
* DSC_5154 has an ISO of 176
* DSC_5156 has an ISO of 180
* DSC_5157 has an ISO of 192

**Platform**

* darktable version : 4.0.0 (built using [latest stable release source](https://github.com/darktable-org/darktable#latest-stable-release), no additional cmake flags)
* OS                : Linux - kernel 5.13.0-35-generic
* Linux - Distro    : Ubuntu 20.04 LTS
* Processor          : Intel Core i7-4500U
* Memory            : 7.5GiB
* Graphics card     : Intel HD Graphics 4400
* Graphics driver   : Unknown

**Additional Notes**

I did have to apply the fix to the script as described [here](https://discuss.pixls.us/t/how-to-create-camera-noise-profiles-for-darktable/7428/208) to get it to run, but otherwise it is the `darktable-gen-noiseprofile` script that gets built from the source.

Also, I am a big novice when it comes to Linux, as I am a primarily Windows user. My "on-the-go" laptop runs linux though and that is where I am trying to generate this noise data from as it seems the Windows installation does not come with the necessary scripts.

**Comment by miroslavfikar** [comment]
I tried to work on noise profiles of Z 6_2 yesterday and noticed the same behaviour, DT 4.2.1, ubuntu 22.04, compiled from sources. Actually, I also got segfault when calling darktable-cli during the run and the script did not finish correctly. I can provide more details if needed.

**Comment by kmilos** [comment]
Please run `exiv2 -pa -u foo.NEF` and `exiftool -a -u -s -g1 -w txt foo.NEF` and check if there are any tags/data that are a better match for Lo/Hi ISO?

This logic might need to be reverse engineered and updated for the newer Z firmware: https://github.com/darktable-org/darktable/blob/9627a6894608a21366eba45ad656f277629d3201/tools/noise/subr.sh#L289-L308

**Comment by kmilos** [comment]
> Actually, I also got segfault when calling darktable-cli during the run and the script did not finish correctly.

Probably a separate issue?

**Comment by miroslavfikar** [comment]
The segfault was resolved - profiles were treated using development version of DT but dt-cli was called from subr.sh using the production version. Once $PATH was modified, it run smoothly.

**Comment by miroslavfikar** [comment]
It seems to me that the wrong read of unusual ISO numbers lies in the command switches of exiv2 in subr.h at line 260:
https://github.com/darktable-org/darktable/blob/9627a6894608a21366eba45ad656f277629d3201/tools/noise/subr.sh#L260

I had better luck with translated print: exiv2 -K "$key" -Pt -b "$file" 2>/dev/null | sed 's/ *$//g' || :

This reads correct ISO values. But I did not check the whole procedure, something broke with my development DT. 

If needed, I can upload the NEF files somewhere.

**Comment by miroslavfikar** [comment]
I finished testing with changed subr.sh and switch -Pt. Everything works as expected. Please consider testing it with other camera models.
