### ISSUE TITLE
Export to Heif

### ISSUE THREAD

**Issue by jinzapper** [darktable-org/darktable#12268]
Requesting the export module to also export to .heif.

Heif has a smaller size compared to an equivalent jpeg.

**Comment by kmilos** [comment]
HEIF/HEIC is a patent encumbered format, so I don't think dt will support this.

You already have the AVIF option, and JXL is being worked on.

**Comment by AxelG-DE** [comment]
But there is #12218 or do I get something wrong???

**Comment by kmilos** [comment]
> But there is #12218 or do I get something wrong???

Indeed you are. Media type association is for opening files w/ double-click, "Open with..." right click menu etc.

**Comment by AxelG-DE** [comment]
yeah sorry, I was on the way to delete my comment here :), now I will leave it...
