### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by Yuanzhoulv7** [darktable-org/darktable#12276]
I'm using a darktable on an M1 Pro MacBook Pro but the slider feel laggy when adjusting them. I was wondering if it is related to that darktable does not natively running on Apple Silicon. If so, I wonder if it can support Apple Silicon in the future for better experience. Thank you.

**Comment by parafin** [comment]
Here you go: https://github.com/darktable-org/darktable/releases/download/release-4.0.0/darktable-4.0.0_arm64.dmg

**Comment by rgdyy** [comment]
Sorry to spam here. I understand darktable uses OpenCL for GPU acceleration. On Apple Silicon, does it also utilize the GPU in the Apple SoC?

Readme says
> A GPU is not mandatory but is strongly recommended for a smoother experience. Nvidia GPUs are recommended for safety because some AMD drivers behave unreliably with some modules (e.g. local contrast).

I guess all GPUs supporting OpenCL would work (albeit not perfectly except for non-Nvidia)?
