### ISSUE TITLE
Could export timestamp be added as a variable in Darktable

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#12275]
Could export timestamp be added as a variable in Darktable. While not a critical issue I would like to be able to add this information to the image information line in the darkroom. I appreciate I can alternatively see the export time in the image information module if this request is not possible or desired by the developers.

**Comment by todd-prior** [comment]
Confirmed...

C:\\Users\\xxxxxxx\\Desktop\\$(FILE_NAME)_$(DAY)-$(MONTH)-$(YEAR)

PXL_20220806_150503457_12-08-2022.jpg created......

**Comment by phweyland** [comment]
I think the doc is a bit confusing here. $(DAY) or whatever variable in the same family represents the current time. So it does represent import/export time at ... import/export time..., but doesn't represent the last import/export time of the image.
