### ISSUE TITLE
Denoise profile for NIKON Z 9

### ISSUE THREAD

**Issue by colin-adams** [darktable-org/darktable#12277]
For noise profiles, please also attach the entire archive with `.pdf` plots.
[darktable-noiseprofile-20220804.tar.gz](https://github.com/darktable-org/darktable/files/9257455/darktable-noiseprofile-20220804.tar.gz)

**Comment by kmilos** [comment]
Depends on https://github.com/darktable-org/rawspeed/pull/347

**Comment by rawfiner** [comment]
The profile looks very good.
I can't integrate it yet due to the dependency to rawspeed pull request. Please ping me when it can be done!

**Comment by freswa** [comment]
Blocking PR https://github.com/darktable-org/rawspeed/pull/347 has been merged. Ping @rawfiner :)

**Comment by TurboGit** [comment]
Indeed, ready.

**Comment by rawfiner** [comment]
Thanks for the ping @freswa . @kmilos , do you think the changes from the PR require to redo the noise profile?

**Comment by kmilos** [comment]
Don't think it should have an effect, feel free to go ahead.

**Comment by rawfiner** [comment]
Perfect thanks. I will do the PR asap (probably on sunday).
