### ISSUE TITLE
 Generation of a web gallery fails

### ISSUE THREAD

**Issue by DomAsw15** [darktable-org/darktable#12271]
In the light table, we want to generate a web gallery, Dartable closes. The index.html file is empty. 0 bytes.
1- selection of 2 images
2- Export module
3- storage options: target storage --> website gallery
4- file format: JPEG(8bits), global options: default

In Home/dartable_gallery:
- images are generated
- generated style and pswp directories
- **Index.html 0 bytes**

* darktable version : 4.0.0
* OS                : Gentoo Kernel 5.15.29 **and** Windows 10 **and** Windows 11

**Comment by victoryforce** [comment]
Indeed. Thank you for reporting. Will be fixed soon.
