### ISSUE TITLE
Darktable is sold in Windows Store for 4.99€ by "Alef_Soft"

### ISSUE THREAD

**Issue by santagraus** [darktable-org/darktable#12285]
![Darktable Windows Store](https://user-images.githubusercontent.com/61650720/183299527-76b37840-f458-4c71-91f5-8d421c925e6c.PNG)
Somebody is selling darktable via the Window Store (see attached picture). Since this is not a valid source listed on the darktable website I assume that "Alef-soft" is a scammer selling other peoples work.

**Comment by MStraeten** [comment]
already known - no issue. license of darktable allows that ;)
BTW: that’s not darktable, that’s a clone named ‚DarkTable LightRoom‘
So it’s up to adobe to protect their trademark ;)

**Comment by elstoc** [comment]
Agreed. We may not like it but it is permitted by darktable's license. There was a suggestion that such software would be against Microsoft's terms & conditions but I think Microsoft have rowed back that position now. Either way, not a darktable issue.
