### ISSUE TITLE
Insatallation on Linux Mint 21 fails (umet dependencies)

### ISSUE THREAD

**Issue by Hedaja** [darktable-org/darktable#12284]
**Describe the bug/issue**

Installation on Linux Mint 21 fails due to unsolvable dependencies.

**To Reproduce**

1. Use OBS and download for Ubuntu 21.10 (or use *.deb)
2. trying to install it shows the following error message:
`The following packages have unmet dependencies: 
 darktable : Depends: libicu67 (>= 67.1-1~) but it is not installable
             Depends: libwebp6 (>= 0.5.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
`

**Expected behavior**
Linux Mint 21 doesn't provide the older libicu67 and libwebp6 packages anymore. Instead it has libicu70 and libwebp7. It would be nice if those newer libraries could be used as well.

**Platform**

* darktable version : e.g. 4.0.0-1.1
* OS                : 5.15.0-43-
* Linux - Distro    : Linux Mint 21 Cinnamon
* Memory            :  15.5 GiB
* Graphics card     : GeForce GTX 1050 Ti Mobile / Intel UHD Graphics 630]
* Desktop           :  Cinnamon

**Comment by ArJo45** [comment]
Ubuntu 21.10 is not the correct version for Mint 21. Mint 21 is based on Ubuntu 22.04 which is the right version to download.

**Comment by Hedaja** [comment]
I'm really sorry
You are right of course and it works with the correct version.
Thank you

**Comment by Nilvus** [comment]
And OBS repository is not directly related to darktable developers team. So, here is not the place for all OBS issues
