### ISSUE TITLE
color wheel in color balance rgb

### ISSUE THREAD

**Issue by Yuanzhoulv7** [darktable-org/darktable#12286]
The 4 way tab in the color balance rgb module doesn't use color wheel to adjust and it feels unintuitive. Lots of professional softwares use color wheels for that purpose like resolve, ACR, Lightroom and even premier pro. So I think it's better to have a color wheel interface. And by the way the Chinese translation of that tab looks kind of odd, so I wonder how can I help it improve . Thank you.

**Comment by MStraeten** [comment]
4 colorwheels will require more space without giving more control. Video software often uses color wheels because they match the used hardware decks also containing wheels to control color. Most photo editors are just using keys or mouse - so dragging a slider is far from being uncommon. So what’s the benefit?
If you need wheels you can assign those controls to a midi controller ;)

**Comment by jandren** [comment]
There is one huge benefit, and that is that we get one 2D orthogonal controller instead of two 1D sliders which are dependent on each other (angle + magnitude). Shortcut and Midi users might also benefit from this by mapping two controllers to the x/y direction of the color wheel.

Graphically leaning users will probably also value the graphical control more than the cost of lost space (we can collapse the module after all). The tricky question to be answered if someone is to implement this is where would be but the toggle between the two input methods?

**Comment by Jiyone** [comment]
I suppose color wheels would means changing the way the module works.
Now it's angle and radius, a color wheel is x and y position (with sin and cos I presume).
So I believe converting x and y to angle and radius will be too slow or too much work so this have to be directly coded in the color core. :thinking:

**Comment by lemirep** [comment]
I've also been finding the slider unintuitive to work with when you want to visualize how highlights/midtones/shadows relate to one another. Doing things like split complimentary or adjacent colors requires you to compute angle values yourself with the sliders.
Scratching my own itch, I started adding a color wheel control  https://github.com/darktable-org/darktable/pull/12297
Anyone willing to give a try to and discuss improvements?

**Comment by emko** [comment]
> 4 colorwheels will require more space without giving more control. Video software often uses color wheels because they match the used hardware decks also containing wheels to control color. Most photo editors are just using keys or mouse - so dragging a slider is far from being uncommon. So what’s the benefit? If you need wheels you can assign those controls to a midi controller ;)

what? you think adding a midi controller equals the same as a color wheel you must be confused?, there is a big reason LR was  begged to add color wheels for years just like every other editing software has of course you can still use sliders but visually color wheel is way easier to use.

i would have a header button bar where you can select different ways to interact with the colors kind of like how the masking module works or like how LR has a icon for 3 circles then one for each and have it default to sliders if that's what it takes. Ideally color wheels should be a option for any module that has a slider for colors

![image](https://user-images.githubusercontent.com/1070310/184510045-48d03e9e-c055-4475-a16f-869a6c36d7ea.png)


![image](https://user-images.githubusercontent.com/1070310/184510078-b70598d9-bbf1-41be-8be6-d0c79bf30585.png)

**Comment by MStraeten** [comment]
are you sure you get more control with those colorwheels? What’s the problem you want to solve?
In the current solution you get exact numbers of your changes ( you need to add 3 number files to each wheel to get the same information (especially for subtile changes you don’t get much information in the LR solution) you can enter values manually (how to do  this with a widget representing 2 values).
Unfortunately all those suggestions just focus on the appearance but not on the way to use it… and how that affects workflows supported by the current slider solution

**Comment by Yuanzhoulv7** [comment]
> are you sure you get more control with those colorwheels? What’s the problem you want to solve?
> In the current solution you get exact numbers of your changes ( you need to add 3 number files to each wheel to get the same information (especially for subtile changes you don’t get much information in the LR solution) you can enter values manually (how to do this with a widget representing 2 values).
> Unfortunately all those suggestions just focus on the appearance but not on the way to use it… and how that affects workflows supported by the current slider solution

It’s not about the digits and accuracy the slider provides, it’s about the look the module eventually makes. Using numbers to color grade is literally a painful process. Besides color wheels are two dimensional they control hue and saturation at the same time while slider can only control one. It is a faster way to get the wanted result.

**Comment by MStraeten** [comment]
maybe for colorgrading but darktable is a raw processor, not intended for video production ;) for this changes the color correction module might be more appropriate…
To get colors right the ui must be able to support even subtle changes of colors - mostly in the centre of the color wheel…

**Comment by Yuanzhoulv7** [comment]
> maybe for colorgrading but darktable is a raw processor, not intended for video production ;) for this changes the color correction module might be more appropriate…
> To get colors right the ui must be able to support even subtle changes of colors - mostly in the centre of the color wheel…

Well I think I get what you’re saying. You mean darktable is not for art creativity but for reconstruct the true scene that human can see. Is that what you mean. That’s totally acceptable. But I would still like to have more creativity options because the filmic rgb module produces the better color than any other software I have ever used.

**Comment by MStraeten** [comment]
> You mean darktable is not for art creativity

bullshit

>But I would still like to have more creativity options

thats no contradiction - but don't mix up UI and UseCases: having colorwheel controls and the latest intention of lemirep are two different things.

if it's just about a color wheel control then there are ways to do this (see davinci - you don't lose detailed info in a different interface; all thats just UI not related to a Usecase):
<img width="672" alt="image" src="https://user-images.githubusercontent.com/39386816/184526354-4b79f349-8f99-490d-b9b8-0ce5bc82987f.png">
![image](https://user-images.githubusercontent.com/39386816/184526353-8c414c62-8b44-4a56-8275-0296112e6080.png)
You might even switch between HSL or RGB like in the legacy colorbalance module 

But if you want to visualize how shadows/midtones/highlights are related and be able to change this thats a different usecase requiring a different UI
You'd have a look at color correction module - currently it just display the relative change, maybe it's worth to improve it to better support that usecase;) 
Do the tasks at the proper place - there's no need to do everything in one module in darktable ...
 
In general all those color balance/correction/grading usecases needs a consistent UX concept - not just arbitrary patches just because some users are used to different software solution for just their personal usecase ;)

**Comment by Yuanzhoulv7** [comment]
> > You mean darktable is not for art creativity
> 
> bullshit
> 
> > But I would still like to have more creativity options
> 
> thats no contradiction - but don't mix up UI and UseCases: having colorwheel controls and the latest intention of lemirep are two different things.
> 
> if it's just about a color wheel control then there are ways to do this (see davinci - you don't lose detailed info in a different interface; all thats just UI not related to a Usecase): <img alt="image" width="672" src="https://user-images.githubusercontent.com/39386816/184526354-4b79f349-8f99-490d-b9b8-0ce5bc82987f.png"> ![image](https://user-images.githubusercontent.com/39386816/184526353-8c414c62-8b44-4a56-8275-0296112e6080.png) You might even switch between HSL or RGB like in the legacy colorbalance module
> 
> But if you want to visualize how shadows/midtones/highlights are related and be able to change this thats a different usecase requiring a different UI You'd have a look at color correction module - currently it just display the relative change, maybe it's worth to improve it to better support that usecase;) Do the tasks at the proper place - there's no need to do everything in one module in darktable ...
> 
> In general all those color balance/correction/grading usecases needs a consistent UX concept - not just arbitrary patches just because some users are used to different software solution for just their personal usecase ;)

So the solution you prefer is to add another modules that serves the right purpose? That’s also acceptable. But no color wheel is really frustrating and disappointing. It’s not just a preference problem. And why do you always talk about resolve? You know it’s not for raw photo editing. Why don’t you talk about capture one or Lightroom or adobe camera raw? They are all raw editing tools and they all have color wheel. Currently only darktable does not have color wheel. So there’s no preference it’s a situation where darktable is the left over one.

**Comment by MStraeten** [comment]
i gave the sample of davinci because it’s not about copying adobe UI but dealing with color in a reasonable way.
‚I want to it like capture one or adobe lightroom‘ isn’t the best argument for changes in darktable. Darktable is not intended to be a free lightroom clone.
And btw: I use davinci as a sample because I use it a lot but never c1 or adobe lightroom because I prefer the darktable way;)

**Comment by Yuanzhoulv7** [comment]
> i gave the sample of davinci because it’s not about copying adobe UI but dealing with color in a reasonable way.
> ‚I want to it like capture one or adobe lightroom‘ isn’t the best argument for changes in darktable. Darktable is not intended to be a free lightroom clone.
> And btw: I use davinci as a sample because I use it a lot but never c1 or adobe lightroom because I prefer the darktable way;)

So in the end it’s just your own preference isn’t it? I know it’s an open source software but go to the opposite way of the whole industry usually doesn’t turn out to be a good idea.

**Comment by Yuanzhoulv7** [comment]
And btw I don’t think your attitude is truly want to help photographers but satisfy your own need. No wonder why so many people choose Lightroom or other software. Because they are much more modernized and up to date. At least they don’t lag on a thousand dollar Mac

**Comment by Yuanzhoulv7** [comment]
傻逼开发者。建议大家别用这个软件了，卡得一批提点建议也不改。也不知道吃老本能吃到什么时候。简直就是有病，无理至极甚至感觉多少带点种族歧视。

**Comment by Yuanzhoulv7** [comment]
![Uploading 29EAD1B9-6324-42E4-B965-76495AB3CB56.jpeg…]()

**Comment by Yuanzhoulv7** [comment]
![7AB642C6-BA66-4D7A-9C75-3225ACA182AA](https://user-images.githubusercontent.com/52786509/184535729-dd7c33a0-e8a3-4c00-9ac1-c9518bf21d1b.jpeg)
![D7A09B85-7339-4D45-B360-255B1A6C9B3A](https://user-images.githubusercontent.com/52786509/184535730-784b2973-d5d9-4b0b-96cd-2d1c1bcda71f.jpeg)
![5654CDAD-4AF7-41BE-AA42-AC6A1C9C3AFB](https://user-images.githubusercontent.com/52786509/184535731-fe4c693e-9bd9-4582-aa2f-1e63660dfa45.jpeg)

**Comment by MStraeten** [comment]
being rude isn’t the best indication for a valuable request. 
even if you deleted the message after sending ist ;)
In foss you need to provide arguments and not scream for candy like a spoiled little child

**Comment by Yuanzhoulv7** [comment]
> being rude isn’t the best indication for a valuable request.
> In foss you need to provide arguments and not scream for candy like a spoiled little child

既然追求刺激，那就贯彻到底吧，反正我再也不会用这个软件就像我再也不会用windows一样。祝愿你们的项目尽快倒闭，祝愿你妈早日归西，祝愿你早日去见安倍晋三，祝愿你和肯尼迪一样离开。

**Comment by Yuanzhoulv7** [comment]
也不知道你家枇杷树开了几年了，生出你这崽种也是一表人材了。

**Comment by Yuanzhoulv7** [comment]
你觉得你很牛逼吗？牛逼有个屁用啊？用你们软件的人都没有人家的开发团队人多，给你们说点建议看狂的你。就你们写的牛逼呗？卡的要死要死的，他娘的脸腾讯的软件都不如，腾讯的软件都比你们流畅。

**Comment by Yuanzhoulv7** [comment]
就这种烂优化还配党程序员？你来中国早他妈被淘汰了，都不知道去哪个18线城市掏粪去了。

**Comment by MStraeten** [comment]
it seems you’re really a little spoiled child screaming for candy …

**Comment by Yuanzhoulv7** [comment]
> it seems you’re really a little spoiled child screaming for candy …

Find someone in the Chinese restaurant and let him translate for you. Chinese is not what you programmers and translating softwares can understand.

**Comment by MStraeten** [comment]
I do not want to shame them because of such compatriots

**Comment by Yuanzhoulv7** [comment]
> I do not want to shame them because of such compatriots

No they won’t. You just need to care about your own safety.

**Comment by Yuanzhoulv7** [comment]
> I do not want to shame them because of such compatriots

And I am so sorry about your existence in the whole programming community. You’re selfish and mean at the same time without a progressive eyesight, producing garbage sources codes that nobody would pay for them that’s why darktable is “open source” isn’t it? Keep rejecting users’ suggestions using unreasonable explanations and your own personal opinions is why you died.

**Comment by MStraeten** [comment]
is your playground closed?

**Comment by Yuanzhoulv7** [comment]
> is your playground closed?

Ancient man, what else can you say? Who plays in the playground these days. Do you know why everyone knows Tik tok? Because  it does way better programming works than you did and using the most advanced AI. Billions of billions of people using it every single day while you have little poor users standing your attitude and laggy interface you made.
