### ISSUE TITLE
NIKON Z( White Balance presets

### ISSUE THREAD

**Issue by colin-adams** [darktable-org/darktable#12282]
For noise profiles, please also attach the entire archive with `.pdf` plots.
[darktable-whitebalance-20220805.tar.gz](https://github.com/darktable-org/darktable/files/9268216/darktable-whitebalance-20220805.tar.gz)

**Comment by kmilos** [comment]
Hm, missing the fine tune tag (), must have moved somewhere else in the newest Nikon MakerNotes and the extract script doesn't know about it...

No biggie, I think I can fix those by hand for now, but it would be good to update the script at some point.

With the latest exiftool (12.44 today), can you please also attach here the file created by `exiftool -a -u -s -g1 -w txt` on a Z 9 NEF that has some fine tuning in it (i.e. not a zero value)? Need to check first if exiftool knows about it...

**Comment by kmilos** [comment]
I also might want to wait for #12184 before creating a PR...

**Comment by colin-adams** [comment]
> Hm, missing the fine tune tag (0x000b WhiteBalanceFineTune), must have moved somewhere else in the newest Nikon MakerNotes and the extract script doesn't know about it...
> 
> No biggie, I think I can fix those by hand for now, but it would be good to update the script at some point.
> 
> With the latest exiftool (12.44 today), can you please also attach here the file created by `exiftool -a -u -s -g1 -w txt` on a Z 9 NEF that has some fine tuning in it (i.e. not a zero value)? Need to check first if exiftool knows about it...

Attached 
[DSC_1093.txt](https://github.com/darktable-org/darktable/files/9268714/DSC_1093.txt)

**Comment by kmilos** [comment]
Thanks a lot. It looks like it could have moved to this unknown location:

`Nikon_0x003f                    : 6 0`

Could you please check it on a few more files just to make sure it correlates w/ the fine tune setting?

**Comment by colin-adams** [comment]
> 

Here are a few more files (all from the flash WB as the first one was):
[DSC_1088.txt](https://github.com/darktable-org/darktable/files/9268788/DSC_1088.txt)
[DSC_1089.txt](https://github.com/darktable-org/darktable/files/9268789/DSC_1089.txt)
[DSC_1090.txt](https://github.com/darktable-org/darktable/files/9268790/DSC_1090.txt)
[DSC_1091.txt](https://github.com/darktable-org/darktable/files/9268791/DSC_1091.txt)
[DSC_1092.txt](https://github.com/darktable-org/darktable/files/9268792/DSC_1092.txt)

**Comment by colin-adams** [comment]
and indeed it seems to correlate.

**Comment by kmilos** [comment]
Yep, thanks for that! Will upstream this to exiftool...

**Comment by colin-adams** [comment]
and I checked an amber one too, and saw -1.5. So you've found the correct
field. I guess the second figure (0) is the g<->m fine setting

**Comment by kmilos** [comment]
Attaching the corresponding JSON for testing in master. @Sturmflut 

[wb_Nikon_Z_9.zip](https://github.com/darktable-org/darktable/files/9556425/wb_Nikon_Z_9.zip)

**Comment by colin-adams** [comment]
Looking at the current darktable README.md, I see that all Z9 basic support
and denoise profiles have been added, white balance presets have not.
I hope that the effort I put into this is not going to be wasted.
