### ISSUE TITLE
[import] photos with same metadata are not imported with pattern that doesn't assure uniqueness

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12292]
dt 4.0

I've shot a burst of photos, they all have the same time (`h:m:s`). If I import them using as file naming pattern like `My subject $(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)--$(EXIF_HOUR).$(EXIF_MINUTE).$(EXIF_SECOND).$(FILE_EXTENSION)` or anything similar, when a photo would produce the same name as an existing imported photo, nothing is imported. A generic notification is made in the window, but I'd say that appears once even if many photos couldn't be imported.

Besides that, I'd say that darktable freezes, and the only solution is to kill it.

**Comment by ptilopteri** [comment]
maybe a local/system problem.  
works fine for me on openSUSE Tumbleweed 
dt 4.1.0+125~g9bf29b49f

you provide little information for one to provide help.
