### ISSUE TITLE
Name change work environments

### ISSUE THREAD

**Issue by mamvdwel** [darktable-org/darktable#12294]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem

**Describe the solution you'd like**
The name "lighttable' (organising section) should change into 'lightspace'
The name 'darkroom' (developing section) should change into 'darkspace'

**Alternatives**
No alternatives

**Additional context**
It's a small change but it will make for more consistency

P.s. my apology if this is not the first time this has been requested!

**Comment by victoryforce** [comment]
A [light table](https://en.wikipedia.org/wiki/Light_table) is a viewing device that is used to review photographic film.
A [darkroom](https://en.wikipedia.org/wiki/Darkroom) is used to process photographic film.
The names you suggest mean nothing.

**Comment by mamvdwel** [comment]
Hi Victor,

Thanks for you response. I agree with what you are saying if you want to use the exact names that have a reference to specific old fashion concepts like the once you mention. You can however choose to use a more loose connection to established concept (because they are not so important any more anyway) and that is how I came up with my proposal which has the following thought behind it: if you organise your photos and your workflow in the old days you normally did this in a room (which is a space) that is illuminated (light). If you develop your photos you do this in a room (again which is a space) that is dark. So you get darkspace and lightspace. So the question is what is more important: sticking to old fashioned concepts (that are loosing there relevancy) in a very precise way on the one hand or choosing for consistency in naming on the other. There is no best choice, all that matters is what you consider to be more important!

Best regards

**Comment by dterrahe** [comment]
"light" and "dark" still refer to "old fashioned concepts". We are not really arguing with you here; we are just gently letting you know that your suggestions have little chance of getting excepted. Nothing personal; anybody would have a hard time defending change for change's sake. It would lead to a lot of confusion in the discussion forums where the majority of the old guard would stick with the old terms either out of habit or stubbornness. New people would not be helped by this.

**Comment by mamvdwel** [comment]
Ok, I understand what you are saying. No problem it isn't that important. Please keep up the good work on this wonderful product!

Best regards

**Comment by Nilvus** [comment]
I understand yout suggestion but disagree to consistency aegument. As well explained here, actual names are here for good reasons and are all consistent. Naming is related to old analog photo processing. I don't think too that changing them is needed. And would also mean some work and so time for update (code, doc, website, etc.). Better to spent time on more useful updates.

**Comment by elstoc** [comment]
I think we have consensus that this probably isn't going to happen, so let's close it.
