### ISSUE TITLE
[import] and [export] progress indicator doesn't show any progress

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12291]
I'd say that the progress indicator doesn't show any progress, either when importing from camera or when exporting.

**Comment by ptilopteri** [comment]
maybe a local/system problem.  
works fine for me on openSUSE Tumbleweed
dt 4.1.0+125~g9bf29b49f

you provide little information for one to provide help.

**Comment by wpferguson** [comment]
Works fine for me
Ubuntu 20.04
dt4.1 up to date

**Comment by Nilvus** [comment]
@paolobenve: do you test again? And which darktable release and OS you use? Which theme? Think about providing more infos when you post issue (you always provide little infos, we propose a template issue for good reasons. Having more infos help understand the issue and so help us help you).

**Comment by paolobenve** [comment]
darktable 4.0 self compiled on xubuntu 22.04, theme `darktable`. It looks like a theme issue, because changing the theme the issue desappears

**Comment by Nilvus** [comment]
Thanks for infos @paolobenve. I can reproduce (CSS issue) and I just fix it. PR coming in few minutes.
