### ISSUE TITLE
darktable crash on Win10

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12307]
**Describe the bug/issue**
dt was rendering one thumbnail in lighttable (heavy with guided laplacians high light recovery) and I tried to select a group of images for exporting to JPEGs.

**To Reproduce**
Not possible, a random crash.

If the Windows dump doesn't give any hints, I understand this is impossible to debug.

**Which commit introduced the error**
–

**Platform**
* darktable version : 4.1.0+116~gc04e387fe
* OS                : Win10 Enterprise, 19044.1826
* Memory            :  32GB
* Graphics card     :  NVIDIA T500
* Graphics driver   : 
* OpenCL installed  : y
* OpenCL activated  : y
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
Windows crash dump
[darktable_bt_KUL1Q1.txt](https://github.com/darktable-org/darktable/files/9317023/darktable_bt_KUL1Q1.txt)

**Comment by ptilopteri** [comment]
you might try with opencl turned off
usually not a problem with nvidia but with
windows, all bets are off

**Comment by gi-man** [comment]
The issue occurred with libgtk-3-0.dll. Is this the first crash?

**Comment by lintujuh** [comment]
I have enabled my integrated Intel GPU for lighttable, and disabled NVIDIA for lighttable. So it can be an opencl issue with Intel.

This is my first crash in lighttable, I think there has been some random crashes also in darkroom, but I have not registered them.

**Comment by MStraeten** [comment]
random crashes can occur, if the system is running out of video ram.
If there’s no reproducible scenario, it’s almost impossible to find the exact source of the error.
but you are using a development version - did you build it yourself? Then you might run darktable in a debug session (gdb  is within the msys/mingw) to get more information if dt crashes.

**Comment by lintujuh** [comment]
Yes, I did it build myself. I can try to use gdb after the next crash, it will be the first time :)
