### ISSUE TITLE
Feature Request: Constrain crop aspect ratio if modifier key is held

### ISSUE THREAD

**Issue by bastibe** [darktable-org/darktable#12305]
**Is your feature request related to a problem? Please describe.**

I frequently crop my images. For some images a freehand crop is easiest, for others a fixed aspect ratio is beneficial. However, switching between free crop and aspect-ratio constrained crop is somewhat cumbersome.

**Describe the solution you'd like**

Other programs solve this by constraining the crop aspect ratio while a modifier key is held. Usually, holding shift keeps the current aspect ratio while dragging the crop handles.

**Alternatives**

- You can set a keyboard shortcut to activate crop module presets with fixed crop ratios. But this also resets the crop area.
- You can bind a keyboard shortcut to the crop ratio dropdown. But this menu contains many items that are somewhat slow to scan and select.

**Comment by elstoc** [comment]
I'm not entirely clear what you're asking for. When in freehand crop you can currently hold shift while dragging to keep the aspect ratio. You want something different here?

**Comment by bastibe** [comment]
Indeed. Somehow I must have tried Ctrl and Alt, but not Shift. Sorry about that.
