### ISSUE TITLE
Highlight reconstruction in filmic rob causing crashes

### ISSUE THREAD

**Issue by swsounds** [darktable-org/darktable#12300]
**Describe the bug/issue**
With DT 4.0 on Mac OS10.15.7 Mac Mini i7 quad core
In Filmic RGB if I start to use the Highlight reconstruction tab  then various moves cause complete crash

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to Lighttable and open an image in Darkroom. 
2. Click on Filmic RGB module to open and then click on the reconstruct tab.
3. Drag the gray-colorful details slider to the left. At some point to the left of the centre point  DT will crash and disappear. 
4. Please note if you just click at 100% gray it will not crash. If you then drag it back towards centre point it will also crash. 5. 
5. Please also note that if you set the gray colourful to -100% and then slide the threshold slider it will also crash. 6. 
6. After having it crash it can prove very difficult to reopen the particular image and DT will freeze for minutes. I had to force quit it at least once and even that was very difficult. On one occasion while trying to move the mouse while DT and whole machine frozen it shut down the Mac completely and rebooted. 
7. I  have also been having issues with some other images not loading in the Darkroom and virtually freezing the machine for 3 or 4 minutes. This happened first a day before the problem I am reporting. I have to force quit DT. 

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
I am using the standard install which is provided for Mac users. 
version 4.0.0

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version :4.0.0
* OS                : Mac OS 10.15.7

* Memory            : 8GB 1333 MHz DDR3
* Graphics card     : Intel HD Graphics 4000 1536 MB graphics
* Graphics driver   : 
* OpenCL installed  : No
* OpenCL activated  : No
Mac mini (Late 2012) 2.3 GHz Quad-Core Intel Core i7

**Additional context**
_Please provide any additional information you think may be useful, for example:_
I have attached the guilty file that is causing the crash issue along with it's xmp
 - Can you reproduce with another darktable version(s)?  no
 - Can you reproduce with a RAW or Jpeg or both? RAW-file-format/ .CR2
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? no
  
[IMG_1075.CR2.txt](https://github.com/darktable-org/darktable/files/9303857/IMG_1075.CR2.txt)
[IMG_1075.CR2.zip](https://github.com/darktable-org/darktable/files/9303867/IMG_1075.CR2.zip)

**Comment by pehar1** [comment]
Not able to reproduce with dt master 4.1.0-155-g77c4f0228, Ubuntu 20.04. Can drag and click (all) slider(s), fast or slow, image is recalculated correctly.
My first guess would be a memory problem on your side (only 8 GB RAM). To get debug information it might be helpful if you could try to launch darktable from terminal with option `-d all` and post the output here.

**Comment by swsounds** [comment]
Well, I think I have done what you asked. I dragged the EXEC file to the terminal window added -d all and then exported this text to the attached file. I hope this helps. 
[Terminal Saved Output.TXT](https://github.com/darktable-org/darktable/files/9325650/Terminal.Saved.Output.TXT)

**Comment by pehar1** [comment]
I had a very quick look at the log on a tablet, not at my pc at the moment. This log shows the startup of the application, but you did not force the error/crash of interest. This is necessary to get information regarding your issue.
The log reports an available memory of only 4 GB. In my experience, this can be problematic.

**Comment by swsounds** [comment]
Sorry so happy to have worked rest of it out I didn’t think that through. I’m out the rest of the day but can do that tomorrow. Thanks

**Comment by pehar1** [comment]
No problem, I don't think the log will bring any further insights. I am pretty sure the program crashes due to lack of memory. You need (much) more than 4 GB to run darktable stably and comfortably. And a (powerful) GPU is of very great advantage.

**Comment by MStraeten** [comment]
maybe provide the crash report.
Highlight reconstruction needs a lot of processing power, so it might be the reason for that  lagging behaviour.
Maybe you can enable OpenCL to speed up - but don’t expect a boost with your gpu device.

**Comment by swsounds** [comment]
[Darktable crash.TXT](https://github.com/darktable-org/darktable/files/9336852/Darktable.crash.TXT)
Hi 
I have 8GB of RAM so I'm not sure why it says 4GB. 
Here is the crash report (I think). The odd thing is the 1st image I was editing was the one that was regularly causing the crash and I couldn't get it to do it even after discarding history and trying again. So I moved onto a 2nd and it did it almost straight away. Hopefully this will help. 
Thanks
Steve

**Comment by pehar1** [comment]
The link to the crash report seems to be wrong or broken. Not able to view the content or download the text.

**Comment by swsounds** [comment]
Thanks for that I look forward to hearing back soon.

**Comment by KaiserRoll42069** [comment]
I appear to be having a rather similar issue with Darktable 4.4.1, I'll look into it more later - Also it probably isn't a OOM/ram issue because I have a full 16 GB of ram, twice the recommended 8gb

**Comment by MStraeten** [comment]
Without a recent bugtrace no one can investigate… maybe also run darktable from terminal with debug messages e.g. -d common

**Comment by KaiserRoll42069** [comment]
Okay, will do! Should I post my problem and the results under this issue or make a new post (since it's a different version & different system specs)?

Sorry I'm kind of a newb to GitHub and idk what the usual protocol is...

**Comment by KaiserRoll42069** [comment]
I tried running with -d all. Darktable crashes when:
- the threshold slider is moved to a negative value.
- the transition slider is moved to a large positive value.

No terminal output is generated on crash. The issue persists when run with --configdir "/tmp"
The strangest thing is that highlight reconstruction seems to have pretty much no effect on the resulting image. Am I just using it wrong or is it like broken or something?

My system specs:
Darktable 4.4.1
Windows 10 19045.3208
i7 2600k, 16 GB ram, AMD rx 5600xt 6gb, photos stored on HDD
AMD Software: Adrenalin Edition V. 2022.1130.1413.1936

**Comment by ralfbrown** [comment]
Unable to reproduce in 4.5.0+138 under Linux.  I tried the full range of both threshold and transition sliders on the "reconstruct" tab with an image containing large areas of sensor clipping.

Filmic highlight reconstruction is really highlight transition blending, particularly for large blown-out regions.
