### ISSUE TITLE
darktable 4.0  on Ubuntu Mate 20.04  Export problem

### ISSUE THREAD

**Issue by alfroland** [darktable-org/darktable#12301]
Hi, the first picture I exported without style. This one seems to be exported correctly.
In the other picture I add a style (watermark) with my name. In this picture my editing is gone.
Best Regards
Alf

![20220809T093305-00](https://user-images.githubusercontent.com/54813351/184154540-6a6d0321-5b17-4e8f-b0fd-32e6aad2a603.JPG)
![20220809T093305-00_01](https://user-images.githubusercontent.com/54813351/184154548-b07ef5eb-26bc-495e-ac90-292b9934c79e.JPG)

**Comment by elstoc** [comment]
If you applied the style using the styles module, did you use "overwrite" or "append" mode? If you applied the style as part of the export (within the export module), did you select "replace history" or "append history"?

**Comment by alfroland** [comment]
If I use the style mode the problem does'nt occur and I always use "overwrite". I used "replace history" which was the default setting. When I changed to "append history"  all becomes OK! Thank you!!!
![20220809T093305-00](https://user-images.githubusercontent.com/54813351/184293205-24538ad1-c614-4a68-8574-28d5719093d0.jpg)

**Comment by Nilvus** [comment]
@alfroland: think about closing issue when fix found. That will help us. I close it
