### ISSUE TITLE
OM-1

### ISSUE THREAD

**Issue by PJLC** [darktable-org/darktable#12325]
I would like that Darktable would also support Olympus OM-1 model raw files.
I have already contributed with a raw sample file from my camera (J2271341.ORF) to
https://raw.pixls.us/ !

Thanks!

**Comment by gi-man** [comment]
Repeat of https://github.com/darktable-org/darktable/issues/11258

There is a PR to add this support, but it is waiting on rawspeed. Rawspeed has no new commit since early June.

**Comment by Nilvus** [comment]
@PJLC: please search before posting issues. I close it as it is so a duplicate one.
