### ISSUE TITLE
Import of images edited in Corel Aftershot Pro 3 overwrites xmp sidecar files

### ISSUE THREAD

**Issue by jzinkweg** [darktable-org/darktable#12322]
**Describe the bug/issue**
When trying out darktable as a potential replacement for Corel Aftershot Pro 3 on Linux, the sidecar xmp files generated by Aftershort were overwritten during import in darktable.
Aftershot uses the same naming format as darktable: `<basename>.<extension>.xmp`.

**To Reproduce**
1. Use Corel Aftershot Pro 3 to edit / organize a photo
2. Open .xmp file and see Aftershot's metadata is present
3. Import photo in darktable
4. Open .xmp file and see Aftershot's metadata is missing

**Expected behavior**
Possible solutions could be to:
* warn the user sidecar metadata will be lost as it is not recognized
* merge the unsupported metadata with the darktable metadata during write\
 (this is done by Aftershot when re-writing metadata to an xmp file containing darktable elements)
* create a new _nn_ version when importing incompatible xmp files and leave the original intact

**Platform**
* darktable version : 4.0.0-1.1 from graphics:/darktable/xUbuntu_22.04
* OS                : Linux 5.15.0-43-generic
* Linux - Distro    : Ubuntu 22.04.1 LTS
* Desktop           : Gnome 42.2

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **clean install of darktable**

**Comment by ptilopteri** [comment]
there is an option to turn off or not generate xmp files on import.
guess you missed that.

**Comment by jzinkweg** [comment]
I found that option after losing 3000+ xmp files (single directory import) which I'm now restoring from backup.

It still means I can't make edits to files as that will still lose my previous metadata which is stored in different xml namespaces.

**Comment by ptilopteri** [comment]
correct, the xmp files are not generated the same between
darktable and bibble/corel

you can export tiff files from either and import into the other

**Comment by ptilopteri** [comment]
probably ought to alter the filenames on export, just in case :)

**Comment by saknopper** [comment]
I don't think this issue is about exporting/importing between different programs. But about darktable (silently) overwriting xmp files created by other programs and thus losing work in the process.

Although I don't have fully thought out solution for this, I do think the default behavior of darktable should be "safe" in this situation.

**Comment by ralfbrown** [comment]
The "correct" behavior would be to preserve any tags in non-dt namespaces.  That would require storing them in the database somehow on import (both initial when reloading the xmp) and writing them out along with dt's tags.

**Comment by gi-man** [comment]
@jzinkweg When you add the images to darktable, are you using Add to Library or Copy & Import? Is the xmp behavior different in Add to Library?
