### ISSUE TITLE
don't recompute pipe when just changing overlays

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12339]
The _crop_ module always displays the entire image on-screen while it is active, and changing the cropped area therefore does not change that image (just the drawn overlay lines). Ideally, the crop module should store its parameters in temporary variables until the crop is committed (module loses focus), at which point the internal module parameters should be updated, and the pipe can be recomputed.

Similarly, within the _rotate & perspective_ module, the displayed image only changes when moving one of the sliders or clicking one of the "fit" buttons. When drawing or auto-detecting structure lines, again, only the overlay is being altered, and not the displayed image. In this case, parameters should only be committed when the module loses focus, one or more sliders is changed, or a fit button pressed (also when changing rotation with right-click+drag).

**Comment by dterrahe** [comment]
Did https://github.com/darktable-org/darktable/pull/13274 solve this issue? If so, please close it. If not, please provide more detail about the specific remaining problems.
