### ISSUE TITLE
DT crashes with unhandled exception

### ISSUE THREAD

**Issue by GeSteu** [darktable-org/darktable#12335]
**Describe the bug/issue**
1) Opened Panoramafile in .hdr format (file size approx. 4,2 GB)
2) Worked on it all ok
3) When trying to export, DT crashes with "unhandled exception", 
tried different export file formats, all the same, tried different import file formats (exr, tif) and the export, crashes too.

Thank you for your great work.
Kind regards and God bless
Georg

P.S. triedt to edit the info, but dit not work out.(???)
**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_
[darktable_bt_P08ZQ1.txt](https://github.com/darktable-org/darktable/files/9358199/darktable_bt_P08ZQ1.txt)

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.0
* OS                :Windows 10 pro, 10.0.19044 Build 19044
* Linux - Distro    : n.a
* Memory            : 64 GB
* Graphics card     : Nvidia A3000 Notebook
* Graphics driver   : 31.0.15.1694
* OpenCL installed  : 3.0.1.0
* OpenCL activated  : 3.0.1.0
* Xorg              :  n.a
* Desktop           : n.a
* GTK+              : n.a
* gcc               : n.a
* cflags            : n.a
* CMAKE_BUILD_TYPE  : n.a

**Additional context**
_Please provide any additional information you think may be useful, for example:_
[darktable_bt_FGGRQ1.txt](https://github.com/darktable-org/darktable/files/9358224/darktable_bt_FGGRQ1.txt)

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by ptilopteri** [comment]
you need to provide the information requested below your text for anyone
to be able to help you, ie: darktable version, operating system, ...

**Comment by kmilos** [comment]
Yep, the template is not there for fun, somebody spent time making it to extract relevant information for bug reporters.

From the backtrace it looks like OpenMP related.

@wpferguson What GCC version are you using for your recent builds, is it `mingw-w64-ucrt-x86_64-gcc-libs 12.1.0-3`?

Too bad the nightlies stopped working so we can't compare to those... (@TurboGit please merge the CI fix when you can)

**Comment by kmilos** [comment]
Your 4.2GB .hdr RGBE image becomes a 16.8GB one internally for darktable. It might be that you're just running out of memory.

**Comment by GeSteu** [comment]
I am new to this, what does "closed this as not planned" mean? "not planed"?
Thank you and kind regards
Georg

**Comment by ptilopteri** [comment]
it is not a darktable problem but probably a problem
with your system and lack of memory.  also you did
not provide the requested information for anyone to 
more accurately assess your difficulties.  the information
requested in the template is there for a reason, not just to
take up space or be ignored.

before anyone can assist you, you must assist yourself.

**Comment by GeSteu** [comment]
Well i updated the info, sorry for not doing this at once, Newbee. 🙂 I do
not think it is the Hardware, my WS is 3 month old. 🤔

ptilopteri ***@***.***> schrieb am Sa., 20. Aug. 2022, 23:51:

**Comment by ptilopteri** [comment]
then, as the issue is still closed, you will need to re-open it.

**Comment by Nilvus** [comment]
Could be an opencl issue. Try by disabling Opencl and see if error occur again (before opening any new issue). If you don't have error when exporting, then it's probably your opencl driver. It happens sometimes on some drivers (could be a specific version that could be sometimes fixed by updating or downgrading graphic card).

**Comment by GeSteu** [comment]
Many Tanks for the info, will give it s try 🙂👏

Nicolas Auffray ***@***.***> schrieb am Mo., 22. Aug. 2022,
21:05:
