### ISSUE TITLE
'Unhandled exception' crash when making consecutive exposure adjustments

### ISSUE THREAD

**Issue by sg456** [darktable-org/darktable#12336]
OK, my first ever issue..... tell me if something's missing

I've been trying out the latest weekly Windows build, (posted on discuss.pixls.us by wpferguson) but have got a consistent crash with an "Unhandled exception". See backtrace below.

To reproduce:
1. Close dt if running.
2. Start dt
3. Open image in darkroom
4. make 2 consecutive adjustments to the exposure slider inthe 'quick access' panel.
5. dt crashes.

If, however, I do a single exposure adjustment, then something else, like color balance rgb saturation, then come back to exposure it works properly. If I then open a new image, it still works properly, right from the start. But the problem returns if dt is restarted.
I did have two other versions of dt installed, but uninstalling them made no difference.
 
apostle338 on the discuss.pixls.us forum is able to reproduce it, but only with OpenCL set to off or standard. The crash does not occur when OpenCL is set to 'very fast GPU'.

Not sure if it's related, but I have just reinstalled dt4.0, and now the weekly build won't run. A blank window opens briefly then disappears. I had this problem the other way around after installing the weekly build the first time, 4.0 wouldn't run. It did after uninstalling the weekly build, which I then reinstalled and ran using --configdir to set a separate db, and all seemed fine. Make of this what you will... I have not a clue!

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.1.0+177~g8e7e79817
* OS                : Windows 11
* Linux - Distro    :
* Memory            :  16GB
* CPU Intel i5-2400 @3.10GHz
* Graphics card     : embedded
* Graphics driver   : unknown
* OpenCL installed  : no
* OpenCL activated  :  no
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : unknown

 - Can you reproduce with another darktable version(s)? --- no
 - Can you reproduce with a RAW or Jpeg or both? ---Raw not sure about jpg.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? --- yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? ----yes
 - Do you use lua scripts? --- no
Here's the backtrace:
[darktable_bt_6GPOQ1.txt](https://github.com/darktable-org/darktable/files/9358769/darktable_bt_6GPOQ1.txt)

**Comment by kmilos** [comment]
From the backtrace it looks like OpenMP related.

@wpferguson What GCC version are you using for your recent builds, is it `mingw-w64-ucrt-x86_64-gcc-libs 12.1.0-3`?

Too bad the nightlies stopped working so we can't compare to those... (@TurboGit please merge the CI fix when you can)

**Comment by gi-man** [comment]
I was able to reproduce but: it needs the GPU to be off. 

4.1.0+187~ga279dc0c4

```
8.250133 8.250134 [dev] took 0.000 secs (0.000 CPU) to load the image.
[pixelpipe] pipeline state changing for [preview], flag 1
8.250170 [pixelpipe] synch top history module `exposure' for [preview]
8.250208 [params] commit for exposure in pipe 4 with hash 2531959754
8.250235 8.250237 [pixelpipe] pipeline state changing for [full], flag 1
[pixelpipe_process] [preview] using device -1
[memory] before pixelpipe process
8.250284 [memory] max address space (vmpeak):      2061812 kB
[memory] cur address space (vmsize):      1448312 kB
[memory] max used memory   (vmhwm ):      1409928 kB
[memory] cur used memory   (vmrss ):      1197568 Kb
[pixelpipe] synch top history module `exposure' for [full]
8.250355 8.250363 [params] commit for exposure in pipe 2 with hash 2531959754
[dt_dev_pixelpipe_process_rec] [preview], cache available for `ashift' with hash 1639590832
8.250393 [pixelpipe_process] [full] using device -1
[memory] before pixelpipe process
[memory] max address space (vmpeak):      2061812 kB
[memory] cur address space (vmsize):      1448312 kB
[memory] max used memory   (vmhwm ):      1409928 kB
[memory] cur used memory   (vmrss ):      1197052 Kb
8.250455 [dt_dev_pixelpipe_process_rec] [full], cache available for `ashift' with hash 1686867315
8.252107 [get_free_cachelines] removed 25, ->line 1, cachemem=125MB, limit=157MB
8.258251 [dev_pixelpipe] took 0.006 secs (0.172 CPU) processed `exposure' on CPU, blended on CPU [preview]
8.258251 [dev_pixelpipe] took 0.008 secs (0.172 CPU) processed `exposure' on CPU, blended on CPU [full]
[dev_pixelpipe] module `exposure' min: (0.006682; 0.000000; -0.002968) max: (5.274210; 4.830432; 4.696488) [preview]
8.270134 [get_free_cachelines] removed 25, ->line 1, cachemem=125MB, limit=157MB
Magick: caught exception 0xC0000005 "Access violation"...
```

I noticed this Magick issue yesterday and I was planning to start the bisect. I was thinking it was one of the recent PRs around magick, but his build is earlier than that PR.

**Comment by wpferguson** [comment]
> __What GCC/libgomp version are you using for your recent builds, is it mingw-w64-ucrt-x86_64-gcc-libs 12.1.0-3?

Yes

**Comment by wpferguson** [comment]
There is a possibility that I didn't build the snapshot with binary compatibility.  I tested the Sunday build on win 10 and got lots of crashes.  I did a pull from today, rebuilt ensuring binary compatibility, tested, and it ran fine for me.  Here's the link to the new build, https://drive.google.com/file/d/1OZnPac0_NxgsINH8xkBD4_zZ85jWv6x1/view?usp=sharing

**Comment by apostel338** [comment]
Your new one crashes without any message, also no event in the win-protocol.

https://user-images.githubusercontent.com/96216629/185191339-67b2eb47-1afb-4e52-bbd5-2042b7b3ec25.mp4

OpenCL GPU only seems still solid.

**Comment by gi-man** [comment]
I remember that I still have a few of the .exe files from my previous builds. Ive installed them in a clean directory to see when I can get it to reproduce. So far I've tested 4.1.0+19, +67, +109 and no issues. At +175, it did crash. I've been using UCRT since +67.

**Comment by wpferguson** [comment]
I managed to reproduce the Magick access violation with my new build on Win 10.  Tried again with the same image set and same edits and couldn't make it crash, so the bad news is that it's somewhat random (at least for me).

**Comment by gi-man** [comment]
I found the commit that starts the problem:

https://github.com/darktable-org/darktable/commit/fb955211923ab23d9a5fd9aaf412b5e3f867e04f

Bill, can you build and confirm? To reproduce, you need to turn off OpenCL and do multiple adjustments to the exposure.

**Comment by wpferguson** [comment]
If I go to the commit before and compile (+130) it runs without a crash.  If I add in https://github.com/darktable-org/darktable/commit/fb955211923ab23d9a5fd9aaf412b5e3f867e04f and compile (+137) I start getting unhandled exceptions.  Sometimes they occurred on just opening images.

**Comment by gi-man** [comment]
That commit is part of this PR https://github.com/darktable-org/darktable/pull/12169 by @jenshannoschwalm .  I read thru it and the referenced issues. It doesnt seem that I'm even close to the cache memory limits. I've reached my limit of troubleshooting capabilities/knowledge on this one.

**Comment by jenshannoschwalm** [comment]
I have no access to my computer for more than a week so I can't test. Some ideas here but I am a bit puzzled that only Windows systems seem to be affected.

**Comment by kmilos** [comment]
FYI, the [nightly build](https://github.com/darktable-org/darktable/actions/workflows/nightly.yml) is available again, but haven't checked it yet...

**Comment by apostel338** [comment]
Nightly build is crashing too.

Maybe helpful: I recognized some of my photos to be pretty crash resistant. Turns out that I used **_crop_** on them. In fact, I haven't yet been able to crash a cropped photo with the "exposure-method", although it crashed once _while_ cropping.

**Comment by gi-man** [comment]
I did some more troubleshooting. A few items of note:

- I can get it to crash in any build after the PR, on Windows. 
- I can make it happen in other modules too if I do very fast clicks on the slides.
- If I switch back to lighttable and return to darkroom, I can keep adjusting the exposure as long as I do only a single click. 
- The IOP cache seems to be a fixed value of 785MB. Changing the Resource Level does not seem to change it. With OpenCL on, the IOP cache value is not reported sometimes.

I will try on fedora again.

**Comment by Mark-64** [comment]
No crash in DT 4.0.0, Windows 11, with or without OpenCL

**Comment by gi-man** [comment]
@Mark-64 darktable 4.0.0 should not have this problem. The problem started last week when a pull request was introduced into master for darktable 4.2.

**Comment by gi-man** [comment]
I managed to get it to crash on fedora 36 X11 

```
[gman@fedora ~]$ darktable -d dev
0.000063 application_directory: /usr/bin
0.000500 darktable.datadir: /usr/share/darktable
0.000522 darktable.plugindir: /usr/lib64/darktable
0.000534 darktable.localedir: /usr/share/locale
0.000594 darktable.configdir: /home/gman/.config/darktable
0.000674 darktable.cachedir: /home/gman/.cache/darktable
0.000696 darktable.sharedir: /usr/share
0.000788 darktable.tmpdir: /tmp
0.000798 new_xdg_data_dirs: /usr/share:/home/gman/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
0.185590 [dt_worker_threads] using 4 worker threads
[dt_get_sysresource_level] switched to 0 as `small'
  total mem:       15323MB
  mipmap cache:    957MB
  available mem:   1915MB
  singlebuff:      59MB
  iop cache:       766MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
0.587077 [dt_worker_threads] using 4 worker threads
2.505484 [pixelpipe_process] [thumbnail] using device -1
2.567793 [dev_pixelpipe] [thumbnail] reserving high priority cacheline for `gamma' (4MB)
2.568493 [dt_dev_pixelpipe_process thumbnail] done, cachemem=742MB, limit=0MB, hitrate=0.00
5.637944 adding themes directory: /usr/share/darktable/themes
10.412064 [pixelpipe_process] [full] using device -1
10.675329 [dev_pixelpipe] [full] module colorin passing important hint to next module
10.675360 [dev_pixelpipe] [full] reserving high priority cacheline for `channelmixerrgb' (25MB)
10.776459 [dev_pixelpipe] [full] reserving high priority cacheline for `gamma' (25MB)
10.781078 [dt_dev_pixelpipe_process full] done, cachemem=454MB, limit=612MB, hitrate=0.00
10.841858 [pixelpipe_process] [preview] using device -1
10.858626 [dev_pixelpipe] [preview] module colorin passing important hint to next module
10.858650 [dev_pixelpipe] [preview] reserving high priority cacheline for `channelmixerrgb' (18MB)
10.911572 [dev_pixelpipe] [preview] reserving high priority cacheline for `colorout' (18MB)
11.007124 [dt_dev_pixelpipe_process preview] done, cachemem=143MB, limit=153MB, hitrate=0.00
11.829915 [pixelpipe_process] [full] using device -1
11.829950 [dt_dev_pixelpipe_process_rec] [full], cache available for `demosaic' with hash 17333103076763977030
11.838320 [dev_pixelpipe] [full] module colorin passing important hint to next module
11.838338 [dev_pixelpipe] [full] reserving high priority cacheline for `channelmixerrgb' (25MB)
11.885257 [pixelpipe_process] [preview] using device -1
11.885304 [dt_dev_pixelpipe_process_rec] [preview], cache available for `demosaic' with hash 6128028936457890517
11.885892 [get_free_cachelines] removed 24, ->line 2, cachemem=134MB, limit=153MB
11.890966 [get_free_cachelines] removed 1, ->line 7, cachemem=129MB, limit=153MB
11.895882 [dev_pixelpipe] [preview] module colorin passing important hint to next module
11.895892 [dev_pixelpipe] [preview] reserving high priority cacheline for `channelmixerrgb' (18MB)
11.970589 [dev_pixelpipe] [full] reserving high priority cacheline for `gamma' (25MB)
11.975430 [get_free_cachelines] removed 24, ->line 4, cachemem=129MB, limit=153MB
11.975456 [dev_pixelpipe] [preview] reserving high priority cacheline for `colorout' (18MB)
11.981591 [dt_dev_pixelpipe_process full] done, cachemem=605MB, limit=612MB, hitrate=0.06
11.985280 [get_free_cachelines] removed 1, ->line 1, cachemem=129MB, limit=153MB
12.002288 [dt_dev_pixelpipe_process preview] done, cachemem=148MB, limit=153MB, hitrate=0.06
12.318967 [pixelpipe_process] [full] using device -1
12.318981 [pixelpipe_process] [preview] using device -1
12.319010 12.319012 [dt_dev_pixelpipe_process_rec] [preview], cache available for `demosaic' with hash 6128028936457890517
[dt_dev_pixelpipe_process_rec] [full], cache available for `demosaic' with hash 17333103076763977030
12.319303 [get_free_cachelines] removed 25, ->line 0, cachemem=129MB, limit=153MB
12.327676 [get_free_cachelines] removed 49, ->line 1, cachemem=512MB, limit=612MB
12.333426 [get_free_cachelines] removed 25, ->line 0, cachemem=129MB, limit=153MB
Segmentation fault (core dumped)

```

But it is not very repeatable. Steps:

1) Turn OpenCL off.
2) Open an image, ideally without any previous edits.
3) Adjust the exposure twice fairly quick with the mouse/slider.
4) crash. 

But If I open darktable again after the crash and try to redo it, i could not get it to crash. I reboot fedora and then it will crash. And now it seems to crash more often, but not always.

**Comment by wpferguson** [comment]
@kmilos when you check the nightly build see if GMIC is included or not.  I'm getting missing dependencies for OpenCV.  It's installed so I think it's a cmake problem.  I looked at it and there's a note about a workaround for GMIC 2.9.3.  I tried a quick fix with no luck.

**Comment by kmilos** [comment]
@wpferguson Indeed, from the last two logs:

```
-- Performing Test GMIC_VERSION_OK
-- Performing Test GMIC_VERSION_OK - Success
-- missing GMIC dependencies OpenCV
-- GMIC dependencies not found

...

-- The following OPTIONAL packages have not been found:

 * GMIC
```

and the nightly installer is some 20MB smaller than usual (the gmic dll + opencv dlls). Both the gmic and opencv packages seem to have been installed in the previous step, so maybe something change wrt CMake detection, I'll check.

**Comment by kmilos** [comment]
Could be related to the new CMake 3.24 and the new registry find_library() mode, the first nightly that has the smaller installer was 13 days ago when the switch to 3.24 happened: https://github.com/darktable-org/darktable/actions/runs/2806944781

However, [it also states that if not specified, old behaviour should be used](https://cmake.org/cmake/help/latest/policy/CMP0134.html#policy:CMP0134), so I'm a bit lost I'm afraid...

**Comment by kmilos** [comment]
@wpferguson It still works on fftw3 above, so I tried without the "lib" prefix and it's ok then. Go figure.

**Comment by jenshannoschwalm** [comment]
I can only read code on cellphone atm but have an idea already what might go wrong with the new caching code. Also see #12364

Will work on this next week

**Comment by gi-man** [comment]
ahah! reading code on a cellphone while on vacation. Enjoy the time off.

**Comment by phweyland** [comment]
> Re removing all the extra workarounds because we're past 2.9.3 now - I have no clue what was the original problem and what to check for...

To take with a lot of salt as I've never been very comfortable with findxxxx.cmake...
If I'm not mistaken the issue was that for the previous version (before 2.9.3), GMIC presented an error about the libraries it needed.
As you know probably better than myself what you are doing there, feel free to make the needed changed !

**Comment by jenshannoschwalm** [comment]
I will take care of the cache problems, maybe and hopefully also can identify any hash problem. @aurelienpierre hinted to mask problems.

No idea about any gmic or windows related problems.

**Comment by kmilos** [comment]
> No idea about any gmic or windows related problems.

No need to worry about that, a PR has been submitted already.
