### ISSUE TITLE
some minor text and .pot errors

### ISSUE THREAD

**Issue by HSUfineprint** [darktable-org/darktable#12341]
found some errors while translation

**texts did not found in .pot file**
collection filters - notice when add new rules
"You can't have more than 10 rules"
"You can't have more than 10 sort orders"

**texts did not found in .pot file, could be translated by adding them manually**
negadoctor: slider "D max"
lua scripts installer: "lua scripts installer"
lua scripts installer: "select action"
lua scripts installer: "select action to perform"
lua scripts installer: "install scripts"
lua scripts installer: "remind me later"
lua scripts installer: "don't show again"
lua scripts installer: "execute"
preferences - lua options: "lua scripts installer dont show again"
preferences - lua options: "do not show scripts_installer if lua scripts are not instelled"

**mouse hover descriptions always use the same text with tab names, could not be translated**
color zones tabs: lightness, saturation, hue
filmic rgb tabs: scene, reconstruct, look, display, options
negadoctor tabs: film properties, corrections, print properties
tone equalizer tabs: simple, advanced, masking
raw denoise tabs: all, R, G, B

**others**
color zones: LCh-C should be "chroma", but the module uses "saturation"
color balance rgb: use the same module description "affect color, brightness and contrast" with color balance, rough and could not separate two modules
color calibration: description of spot color mapping "use a color checker target to autoset CAT and channels" should belong to "calibrate with a color checker". and this description shows all over on target, lightness, hue and chroma in spot color mapping
filmic rgb: description of "use custom middle-gray values" in .pot claims c-format, but use "18.45 %%", if it's a c-format description, should use "%d%%"? or, it's a normal text should use "18.45%"

**Comment by TurboGit** [comment]
You seem to have an old .pot file as "You can't have more than 10 rules" does not exists and many others are wrong too.

**Comment by HSUfineprint** [comment]
> You seem to have an old .pot file as "You can't have more than 10 rules" does not exists and many others are wrong too.

I downloaded the .pot file yesterday. It should be the newest version. I checked "D max", only few .po files contain that msgid. And the .pot file did not have that msgid.

Notice "You can't have more than 10 rules" does not exist in the .pot file. But it does show on screen when you trying to add 11th collection filter.
![filter notice](https://user-images.githubusercontent.com/109933528/185309814-90f65f13-75fb-4d46-9453-9e2868128c42.png)

**Comment by TurboGit** [comment]
> Notice "You can't have more than 10 rules" does not exist in the .pot file.

Found the issue. Thanks.

**Comment by HSUfineprint** [comment]
Thanks. Other strings are the same too. Texts were used in darktable but not in .pot file. Some could be added manually in .po file and works.

**Comment by Nilvus** [comment]
Lua strings can't be translated by now. It's not related to darktable code but lua one (probably except 2 lines in preferences settings but not sure). For lua strings, see: https://github.com/darktable-org/lua-scripts/pull/285

**Comment by HSUfineprint** [comment]
> Lua strings can't be translated by now. It's not related to darktable code but lua one (probably except 2 lines in preferences settings but not sure). For lua strings, see: [darktable-org/lua-scripts#285](https://github.com/darktable-org/lua-scripts/pull/285)

I've tried adding those lua strings to .po file manually. It works.

![lua options](https://user-images.githubusercontent.com/109933528/185380509-c8c795e4-14a4-4dd6-8d62-2ff2d58c1613.png)

![lua scripts module](https://user-images.githubusercontent.com/109933528/185380522-cdf958cd-d6d9-4bc5-9a0f-d390c25269a0.png)

Instead, preferences > lua options: "do not show scripts_installer if lua scripts are not instelled" did not work.

**Comment by HSUfineprint** [comment]
How about other minor errors/suggestions in first post?

Color balance rgb module uses the same module description "affect color, brightness and contrast" with color balance module. That will cause translators can't separate these two modules' description and give them different descriptions in-depth.

Color calibration module>spot color mapping function has a description "use a color checker target to autoset CAT and channels".  I thought that description should belong to "calibrate with a color checker" function in the same module but not "spot color mapping".

In filmic rgb module>options>use custom middle-gray values, description on mouse hover is:
"enable to input custom middle-gray values.\n"
"this is not recommended in general.\n"
"fix the global exposure in the exposure module instead.\n"
"disable to use standard **18.45 %%** middle gray."
And it marks c-format. But it should be a normal text, or use "%d%%" rather than "18.45 %%". Just like the other description in the same module>scene>middle gray luminance:
"adjust to match the average luminance of the image's subject.\n"
"the value entered here will then be remapped to **18.45%**.\n"
"decrease the value to increase the overall brightness."

**Comment by Nilvus** [comment]
> How about other minor errors/suggestions in first post?

Lua strings can't be added by now. Adding manually strings in pot file is not a good way. For those, we need to wait to see an automatic way, work in progress I linked.

About some tooltips for tabs on mouse hover that are the same as tab label, it's just normal. nothing to precise actually is needed. And so tooltip is the same (and translated correctly as I can see on actual master).

Some others things had been updated by @TurboGit in some commits yesterday, after you post this issue.

> Color balance rgb module uses the same module description "affect color, brightness and contrast" with color balance module. That will cause translators can't separate these two modules' description and give them different descriptions in-depth.

Both modules do same things. The main difference is that color balance rgb works in RGB space and color balance in Lab one. Color balance rgb is just more reliable and more powerful but functions here do the same. No need to have different descriptions for those texts.

> Color calibration module>spot color mapping function has a description "use a color checker target to autoset CAT and channels". I thought that description should belong to "calibrate with a color checker" function in the same module but not "spot color mapping" function.

Indeed, there's an issue here. Probably a wrong copy/paste made by the original developer. Will propose a fix for that.
That description is already used for color checker function. Just that this one is also set for mapping one (you could check in exposure module that same mapping function doesn't have tooltip).

For last filmic rgb "c-format", seems that this commit fix that: https://github.com/darktable-org/darktable/commit/5f04d36e5b6180cb0b6038c4af7ed37b706a86af

**Comment by victoryforce** [comment]
> The issue is tabs' name be translated correctly, but the tooltips which have exactly the same words still show English.

You are using darktable 4.0.0 as i can see from your screenshot. The issue you describe I fixed in #12078, the fix will be included in release 4.0.1.
