### ISSUE TITLE
Canon EOS 200D II / Kiss X10 / Rebel SL3 / 250D

### ISSUE THREAD

**Issue by Solemn-Wolf** [darktable-org/darktable#12344]
Hey I have a Canon EOS 200D mark II, and it's not supported in darktable's supported camera catalog. It's a really popular beginner camera and I hope it will be supported soon. Everytime, I try top open an image or edit my photos, a dialog box pops up **"Canon EOS 200D II color matrix not supported".**
Please add this camera soon. I don't have any other cameras and I really love darktable :(

**Comment by kmilos** [comment]
The 250D and Rebel SL3 are already supported, it's just the 200D II and Kiss X10 aliases missing unfortunately...

**Comment by kmilos** [comment]
Can you please send the output of `exiftool -s -Make -Model` or `exiv2 -Pkv -K Exif.Image.Make -K Exif.Image.Model` on one of your 200D II raw files please?

**Comment by Solemn-Wolf** [comment]
Ok this seems stupid, but how do I do that?

**Comment by Solemn-Wolf** [comment]
> The 250D and Rebel SL3 are already supported (see #11566 and #11570), it's just the 200D II and Kiss X10 aliases missing unfortunately...

That's sad... In my region the camera is called the 200D II. But as you said that's not present in the catalog. :(

**Comment by kmilos** [comment]
> That's sad...

darktable is an open source project relying on the community providing samples at https://raw.pixls.us/

No samples, no requests, no support.

**Comment by Solemn-Wolf** [comment]
Ok so I uploaded a RAW file. Now what?

**Comment by kmilos** [comment]
Now you either a) build darktable on your own with the patch linked above, or b) patiently wait until the next release.

**Comment by kmilos** [comment]
Note that there's still no Kiss X10 support added as there are no samples for it.

**Comment by Solemn-Wolf** [comment]
> 

a) I have no idea how I need to build darktable on my own from that patch.
b) How often are the releases?

**Comment by MStraeten** [comment]
a: depends on your system. If you're on win or osx you might check https://discuss.pixls.us/c/software/darktable/19 for weekly development builds. on linux see https://github.com/darktable-org/darktable#building
b: regular releases 2 times  year, bugfixreleases usually one inbetween
the pr regarding 200DII is also merged in the codebase for a bugfix release
