### ISSUE TITLE
Collection Dropdown

### ISSUE THREAD

**Issue by jdnumm** [darktable-org/darktable#12342]
**To Reproduce**
1. Click on collection dropdown (film roll)
2. Nothing happen. 

**Expected behavior**
Open dropdown to select other collection types.

**Platform**
Void Linux - Kernel 5.18.17_1, Sway (Wayland)

this is darktable 3.8.1
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by Nilvus** [comment]
Can't reproduce. Dropdown works great and had always worked on my side. Please began by updating darktable to 4.0 release and test again.

**Comment by jdnumm** [comment]
I build the 4.0 release. The Error appears on all dropdowns of this type (small arrow). But i found out that the problem is that the dropdown is there, but in a separate window under the main full-screen darktable window.

![2022-08-20_15-08-1661002767](https://user-images.githubusercontent.com/105176/185748963-069f7b45-a192-4ecb-924d-af46356987ec.jpg)

**Comment by ptilopteri** [comment]
I am using master on openSUSE Tumbleweed and plasma5/kde5
and the menu drop-down is not separated as you show.

may have something to do with "Sway" ???

**Comment by jdnumm** [comment]
It is handled as a separate floating window and because darktable use full-screen by default,   the dropdown window lays behind the main window. I am confident that there is a Sway configuration workaround, but for me (without any knowledge), it looks like the problem is how these dropdowns are implemented.

All other dropdowns with the filed arrow down are working. If I know why you use another method here and which, I will open a bug in sway as well.
