### ISSUE TITLE
won't select multiple images in lighttable 

### ISSUE THREAD

**Issue by emko** [darktable-org/darktable#12340]
For some reason i can't select multiple images in light table when i try drag to select multiple it seems to drag some black square around and does not select any images.

i am on DT 4 and on latest Fedora

https://streamable.com/rve369

**Comment by Nilvus** [comment]
On video you provide, it seems more related to window manager used than darktable issue. I use darktable since years on Gnome without such issues.
Thus, you provide really little infos. Which window manager do you use? Which Fedora release?

**Comment by emko** [comment]
> On video you provide, it seems more related to window manager used than darktable issue. I use darktable since years on Gnome without such issues. Thus, you provide really little infos. Which window manager do you use? Which Fedora release?

its Fedora Linux 36 (Workstation Edition)
Window System X11
OS Type 64bit
Gnome Version 42.3

**Comment by elstoc** [comment]
Could clicking+dragging _ever_ be used to select images in the lighttable?

**Comment by emko** [comment]
> Could clicking+dragging _ever_ be used to select images in the lighttable?

crap i just assumed its a bug because its such a common thing to be able to do but maybe its not possible in dt :(

**Comment by Nilvus** [comment]
Indeed, if it's about click and drag, it's not available. I close this one so as it's not an issue.
