### ISSUE TITLE
Updating metadata when using 'export -> File Format : copy'

### ISSUE THREAD

**Issue by rakta** [darktable-org/darktable#12352]
**Is your feature request related to a problem? Please describe.**
My 99% usecase is importing JPEG+RAW files, organizing them in DT and export the camera JPEGs them without modifying them [1]. In the export dialogue, i select _File Format: copy_. But the metadata of the original JPEGs is not updated to the metadata in DT. For example, when I change ratings or the timestamps, those changes are not written to the export.

Hint: In Metadata-Export-Settings, _Exif Data_ is activated.

[1] My camera produces good JPEGs and it's ressource intensive on an old laptop to compute many jpg's from RAW or JPEG. 

**Describe the solution you'd like**
An additional option called _copy and update Exif_ would be great for me.

**Alternatives**
Computing Export from Camera JPEG. 
It works to update the metadata as well. But it I don't edit the image, it is a wast of ressources.

**Comment by rakta** [comment]
I found a solution, which is _selected images_ -> _Metadata_ tab -> _update Exif_, before exporting.

Is there a way to update Exif automatically?

**Comment by Nilvus** [comment]
See preferences options of export module (click on hamburger menu of that module). By default, exporting metadata is not enabled (for privacy safety reasons). For more infos, see the manual. Github is not a help support.
