### ISSUE TITLE
After cropping, clipping indicators don't appear

### ISSUE THREAD

**Issue by MWP** [darktable-org/darktable#12359]
**Describe the bug/issue**

After some image operations (crop is the one ive most noticed), the clipping indicators don't function.

**To Reproduce**

1. over or under expose an image
2. turn on clipping indicators
3. crop the image
4. clipping indicators are not redawn
5. clipping indicators need to be cycled, or another operation like exposure needs to be be performed before they are re-shown

**Platform**

* darktable version : official release 4.0.0
* OS                : Windows 10 x64
* Memory            :  40GB
* Graphics card     :  GTX1060

**Comment by MWP** [comment]
Additional information...

This may only occur when ISO12646 viewing conditions are also enabled.

**Comment by Mark-64** [comment]
Confrmed on Windows 11, DT 4.0.0

**Comment by elstoc** [comment]
I can reproduce this on the 4.0.x branch on ArchLinux

**Comment by Mark-64** [comment]
By the way, the same happens with rotate & perspective
