### ISSUE TITLE
Windows build: gmic non found

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#12368]
On a freshly reinstalled and fully updated MSYS2 environment, Windows 11, following to the letter the current build instructions as in DT master, I get the following warning by Cmake at configuration time:

```
-- missing GMIC dependencies OpenCV
-- GMIC dependencies not found
```

and then

```
-- The following OPTIONAL packages have not been found:

 * GMIC
```

Please note that gmic is installed:

```
$ pacman -Q mingw-w64-ucrt-x86_64-gmic
mingw-w64-ucrt-x86_64-gmic 3.0.2-5
```

The first warning sounds suspicious, as gmic 3.0 should not depend on OpenCV anymore.

**Comment by kmilos** [comment]
Known issue, solved by https://github.com/darktable-org/darktable/pull/12349

**Comment by Mark-64** [comment]
Yes, I saw it too late, sorry.
Closing

**Comment by kmilos** [comment]
Would still be good to investigate whether the OpenCV dependency is real, both in terms of dt packaging but MSYS2 as well...
