### ISSUE TITLE
OOM kills probably due to "Improving pixelpipe cache"

### ISSUE THREAD

**Issue by tbilles** [darktable-org/darktable#12364]
I recently started having out of memory kills, after editing a few images (in the order of 5-10). I began to pay attention to my system's memory usage, and noticed that darktable uses more and more memory after every edited image. I even tried to set the "darktable resources" setting to "small" from "default", but it had no effect.

I bisected the issue down to a few commit. I can continue the bisect, but I thought this might be enough to start a discussion.
```
tbilles@serpens ~/sources/darktable> git bisect visualize --graph --oneline
* bec92e554 (refs/bisect/bad) Add two important cache importance hints - highlights because of possibly heavy processing, could be changed to runtime hints - colorin because that's very likely to stay stable while doing later processing
* b0e209644 Make the iop cache aware if importance hints
* 332facc82 (HEAD) Prepare imageop for cache hints
* 650d78a1a RFC Improving pixelpipe cache
```

The commits are related to #12169 

My machine has 12 Gb RAM, baseline system usage is 3-3.5Gb, no swap. While bisecting this issue, good commits after 2-3 image edits result in ~5 Gb memory usage (entire system), bad commits are more like ~7-8 Gb. OOM kill starts to happen above 10 Gb (or at least that is what I see on my memory usage widget).

Is this cache improvement supposed to increase memory usage by this much? Could there be a leak somewhere? (Memory usage doesn't go down when I switch back to lighttable or open an other image in darkroom.) Or is it just the cache filling up?

**Platform**
* OS                : Linux - kernel 5.17.5
* Linux - Distro    : Ubuntu 20.04
* Memory            :  12 Gb
* Graphics card     :  Integrated HD Graphics 4600
* Graphics driver   : Intel
* OpenCL installed  : -
* OpenCL activated  : -
* gcc               : gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Comment by jenshannoschwalm** [comment]
If you start dt with `-d dev` option it will show you the size of iop cache.

But yes, 1) the mem used for caching shouldn't grow above that and 2) cache lines should be cleared when changing from one image to another.

**Comment by tbilles** [comment]
I tried the `-d -dev` option:
```
7.464457 [dt_configure_runtime_performance] found a sufficient 64-bit system with 11895 Mb ram and 8 cores
[dt_get_sysresource_level] switched to 0 as `small'
  total mem:       11895MB
  mipmap cache:    743MB
  available mem:   1486MB
  singlebuff:      185MB
  iop cache:       594MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF

[...]

2233.166970 [pixelpipe_process] [full] using device -1
2233.747319 [dev_pixelpipe] [full] module colorin passing important hint to next module
2233.747348 [dev_pixelpipe] [full] reserving high priority cacheline for `channelmixerrgb' (14MB)
2233.855538 [dev_pixelpipe] [full] reserving high priority cacheline for `gamma' (14MB)
2233.863997 [dt_dev_pixelpipe_process full] done, cachemem=3634MB, limit=475MB, hitrate=0.18
2233.958178 [pixelpipe_process] [preview] using device -1
2233.992617 [dev_pixelpipe] [preview] module colorin passing important hint to next module
2233.992636 [dev_pixelpipe] [preview] reserving high priority cacheline for `channelmixerrgb' (18MB)
2234.117432 [dev_pixelpipe] [preview] reserving high priority cacheline for `colorout' (18MB)
2234.152112 [dt_dev_pixelpipe_process preview] done, cachemem=692MB, limit=118MB, hitrate=0.24
```
That 3634 + 692 = 4326 Mb sounds about right, and supports the idea the pixelpipe cache eats my memory. I watched it climb up with every image.
