### ISSUE TITLE
GoPro HERO10 Black

### ISSUE THREAD

**Issue by alkavan** [darktable-org/darktable#12372]
Hello!

I'm having an issue when connecting/mounting a GoPro HERO10 camera.
I'm not sure for what reason exactly.
By looking at system logs it looks like the cameras Ethernet connection (via USB) gets reset when I press mount button.
I tried to disable this connection, but it still won't mount.
I get the following message in the application:

> failed to initialize 'GoPro HERO10 Black' on port 'usb:003,003', likely causes are: locked by another application, no access to device etc 

I didn't find the camera on the [camera support](https://www.darktable.org/resources/camera-support/) page.
Using Darktable 3.8.1 on Fedora 36.

**Comment by kmilos** [comment]
Even if you manage to connect it, support is still work in progress: https://github.com/darktable-org/darktable/issues/10072

**Comment by Nilvus** [comment]
I so close as this camera is actually not supported, an issue exist for that and this place is not help support but bugs and feature request only.
