### ISSUE TITLE
Noise Profile - Canon EOS M50 Mark II

### ISSUE THREAD

**Issue by user46932** [darktable-org/darktable#12374]
[darktable-noiseprofile-20220822.tar.gz](https://github.com/darktable-org/darktable/files/9404170/darktable-noiseprofile-20220822.tar.gz)

Please note that the model object in the presets.json file must be updated to "EOS M50 Mark II" in order for darktable 4.0 to properly recognize the camera that this noise profile belongs to.

**Comment by rawfiner** [comment]
Looks good thanks!
