### ISSUE TITLE
[Exposure] wrong default for compensate camera exposure flag

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12376]
dt 4.0

The "compensate camera exposure" flag is set by default.

However, if I use an exposure compensation when I shoot, it's because the default exposure is a bad choice. So dt should respect my decision to under/over-expose the image.

For this reason I think that the flag should be unset by default.

**Comment by elstoc** [comment]
You can override defaults with a preset if you like (or set the default workflow to "none" to stop exposure and filmic being auto-applied). I think many people compensate to protect highlights, even when the scene (as measured by the camera) is on average still mid-grey.

**Comment by Nilvus** [comment]
> I expect we'd never find a single default to keep everyone happy.

I would also add that even with same camera, depending on different shot conditions, default best setting is different.

**Comment by Nilvus** [comment]
Same here, do we need to kept that FR opened? I fear that it will be impossible to have a good default setting for all users and all images.

**Comment by paolobenve** [comment]
I'd unset the flag, considering that the user that the user that doesn't "compensate to protect highlights" couldn't realize he must uncheck the flag when he compensate in the opposite direction

**Comment by Nilvus** [comment]
I don't understand your issue. I just tested and if I reset exposure module, default setting is 0.00 with "compensate camera exposure" is not checked. So default setting is already what you ask for.

**Comment by elstoc** [comment]
This is not the default setting for the module but it is the initial setting for scene-referred workflow.
