### ISSUE TITLE
darktable 4.0 English HTML user manual has Chinese content

### ISSUE THREAD

**Issue by lphilpot** [darktable-org/darktable#12384]
The online English HTML user manual at https://docs.darktable.org/usermanual/4.0/en/ includes content in Chinese. I assume that's not intentional.

It doesn't appear to affect the PDF but I didn't check the epub version. From a cursory scan it appears it's limited to these groups:

- Lighttable
- Darkroom
- Map
- Scripting with Lua
- Guides & tutorials
 
The text copy/paste below illustrates a sample:

```
Overview
Lighttable

    overview
    概述
    lighttable view layout
    映繪臺視角布局
    undo/redo
    取消/重做
    lighttable modes
    digital asset management

Darkroom

    overview
    概述
    darkroom view layout
    暗房視角布局
    the pixelpipe
    processing modules
    masking & blending
    organization
``` 

Thanks

**Comment by Nilvus** [comment]
This is not the good place. For docs issues, please post there: https://github.com/darktable-org/dtdocs
