### ISSUE TITLE
Spot exposure effective even the picker is de-activated

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12381]
**Describe the bug/issue**
Spot exposure mapping is effective even the picker is de-activated. When once activated, the target lightness impacts exposure correction even when the picker is no longer active.

**To Reproduce**
1. open an image
2. open exposure and activate the picker
3. de-activate the picker
4. change target lightness
5. exposure is changed

**Expected behavior**
I would expect that the changing the target lightness wouldn't impact the exposure setting once the picker is de-activated.

**Platform**
* darktable version : 4.1.0+188
* OS                : Win10
* OpenCL installed  :  yes
* OpenCL activated  :  yes

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with version 4.1.0+236 on Fedora with no OpenCL**
 - Same issue is also with color calibration and its picker

**Comment by AxelG-DE** [comment]
This is not a bug, it is **the feature**

I was stumbling over similar things in spot color mapping in color calibration.

It is needed to take the measured value over to another (set of) picture(s).

If you want to reset the measured mapping you need to manually reset all sliders in spot mapping. It ought not to reset by reset module for the same reason.

I also think there should be an very obvious reset button at the spot mapping section, but that would be another issue/FR
