### ISSUE TITLE
Color Pick And Luminance Mask

### ISSUE THREAD

**Issue by DakotaLukenbill** [darktable-org/darktable#12387]
The ability to make a mask from color picking or luminosity, similar to what's in Lightroom, would definitely speed up my workflow, allowing me to color pick objects instead of having to draw the mask, same with luminosity, just for shadows or highlights.

**Comment by ralfbrown** [comment]
You're looking for parametric masks: https://docs.darktable.org/usermanual/4.0/en/darkroom/masking-and-blending/masks/parametric/
Use the right-hand color picker on the parametric mask to set the limits for the active slider from a rectangle of the image.

**Comment by Nilvus** [comment]
So closing as this already exist since many years in darktable.
