### ISSUE TITLE
Add customized names/descriptions to labels

### ISSUE THREAD

**Issue by l0f4r0** [darktable-org/darktable#12383]
**Is your feature request related to a problem? Please describe.**
I need to specify a progress status for each of my pictures inside my collections (picture just imported, edited ok, rated ok, metadata ok...).
Labels help me but I would appreciate a place defining and reminding me what each label means to be sure I'm consistent, even months later.
NB: I'm using labels for progress status but it could be different for somebody else depending on his/her workflow.

**Describe the solution you'd like**
Add a setting to associate a name/description to each label.
Additionally, this name/description could be shown in info-tips then...

**Additional context**
I'm using darktable 4.0.0 on Debian 11. Please tell me if I've missed a setting somewhere ;)

**Comment by MStraeten** [comment]
why not using tags?

**Comment by gi-man** [comment]
Or the colors ? Yellow = in progress green= done, ...

**Comment by l0f4r0** [comment]
> why not using tags?

Indeed, this is a possibility.
However, I like the graphical aspect of colored labels on thumbnails. It's immediately identifiable without overloading the interface.

> Or the colors ? Yellow = in progress green= done, ...

Regarding progress status, you're right for red/yellow/green. Meaning of blue and purple is not so obvious in this case.
Moreover, we can imagine a workflow for somebody else (not a progress matter) where none of those 5 colors is meaningful and so would require a description...

**Comment by MStraeten** [comment]
there's no reference workflow how to use star rating or color marks - and i'm pretty sure there never will be a consent way to use that stuff. So why bother about a description :)

**Comment by l0f4r0** [comment]
> there's no reference workflow how to use star rating or color marks - and i'm pretty sure there never will be a consent way to use that stuff.

I totally agree with you on this.

> So why bother about a description :)

However, I'm not ok with your conclusion ;)
I think description could be interesting, especially as there is no standard/implicit way to use the label functionality.

**Comment by gi-man** [comment]
> I think description could be interesting

Your description would be different than mine or anyone else. Your workflow is different than mine. How  will a description help you? 

A description is your solution to a problem, but i fail to understand what is the problem you are trying to solve.

**Comment by MStraeten** [comment]
> I think description could be interesting, especially as there is no standard/implicit way to use the label functionality.

the darktable documentation is a reference documentation - so it gives information how the app works, but not for which usecases you can use all those functions.
the related chapters are: 
https://docs.darktable.org/usermanual/4.0/en/lighttable/digital-asset-management/star-color/
https://docs.darktable.org/usermanual/4.0/en/module-reference/utility-modules/shared/tagging/
but it's up to you how to use that stuff - if you want to use it for labeling, thats fine, if you want to use it for different purposes - also fine.
If you want to have a different solution to do labeling, then you need to specify what exactly you need and provide some convincing arguments why there should be a third way to mark images.

**Comment by Nilvus** [comment]
I also use color labels for progress status. Using green for images processed and I consider completely done. Yellow for images I have processed but not completely satisfied, etc. But I don't see/understand the need of a description. Remember use case (when it's always the same) of 5 colors is easy. I don't need to remember what I set myself for a color. I could understand that if using 15 or 20 colors for example but not for 5.

Think also that adding a feature take time and work, and always overload (even if it's a little) the UI. So adding features need to be REALLY useful and for a lot of people. I fear that what you want is not important, nor really worth the case.

**Comment by l0f4r0** [comment]
> Your description would be different than mine or anyone else. Your workflow is different than mine. How will a description help you?

To remember what each label is for.
Of course each user would have his/her own usage of labels, hence different names/descriptions.

> it's up to you how to use that stuff - if you want to use it for labeling, thats fine, if you want to use it for different purposes - also fine.

I want to use it for labeling indeed. No different purposes.

> I also use color labels for progress status. Using green for images processed and I consider completely done. Yellow for images I have processed but not completely satisfied, etc. But I don't see/understand the need of a description. Remember use case (when it's always the same) of 5 colors is easy. I don't need to remember what I set myself for a color. I could understand that if using 15 or 20 colors for example but not for 5.

Regarding progress status, red or green is OK, but there can be different kinds of in-progress statuses (keywords missing, metadata ko, editing not finished/satisfying...) so it could be worth trying to be clear. 
Sometimes, after several months/years, it's not so easy to remember what each label was for... Even more for different kinds of labels (other than for a progress matter...).

> Think also that adding a feature take time and work, and always overload (even if it's a little) the UI. So adding features need to be REALLY useful and for a lot of people. I fear that what you want is not important, nor really worth the case.

I don't think it's a killing feature here indeed. Lightroom offers that user-friendly choice (in my opinion) and I was just thinking why not darktable...

**Comment by Nilvus** [comment]
> I don't think it's a killing feature here indeed. Lightroom offers that user-friendly choice (in my opinion) and I was just thinking why not darktable...

Where I say that is a killing feature? Lightroom has paid developers, darktable developers do that in their free time. Just not the same. And if someone develop that and wants to add it, maybe that could go in... even if I personally think that remember five labels matching 5 colors do not need software assistance... and so that someone spent (lost?!) time to develop such thing.

**Comment by l0f4r0** [comment]
> Where I say that is a killing feature?

By "killing feature" I meant "essential feature" so I said (like you) that I don't think it is one here.

I just think it is a convenience feature but visibly not for everyone (according to the comments to date at least)...

Anyway, I've noticed your "controversial" tag. Let's wait and see if this suggestion gets any support/development, otherwise never mind!

**Comment by paperdigits** [comment]
Here is how I use color labels. I have no idea why I do it this way, it just make sense to me and I've been doing it forever.

red = edit started but needs a lot of work
red and yellow = maybe this is a good edit
red and yellow and green = I might be onto something here
yellow and green = is this a finalized edit? 
green = YES DONE!
red and green = I'm rethinking this edit
