### ISSUE TITLE
Sony ZVE-10

### ISSUE THREAD

**Issue by CentralPier9** [darktable-org/darktable#12380]
Have just submitted 1 sample of a compressed RAW file. What other variations should I upload or is that all is needed?

**Comment by kmilos** [comment]
Supported since dt 3.8 https://github.com/darktable-org/rawspeed/pull/293

Please close this issue.

**Comment by CentralPier9** [comment]
Apologies. I didn't see it in the supported list nor did my files seem to work, so I assumed it wasn't supported.

**Comment by ptilopteri** [comment]
check the version of darktable you employe
