### ISSUE TITLE
Discovery that Schrödinger's 3D mathematical description of colour is not accurate

### ISSUE THREAD

**Issue by Jan-Jan** [darktable-org/darktable#12392]
Apologies I don't know where else to ask this question.

I'm a huge fan of all the work the darktable team has invested in allowing users to change hue, luminance and saturation independently, and the work on filmic -- thank you very much!. 

My naive question is what are the implications of the recent discovery that the [3D mathematical description developed by Schrödinger is not accurate](https://discover.lanl.gov/news/0810-color-perception)? It is my layman's understand that this would impact how we map to/between the different color spaces, right? Can we make darktable better with this information, or is the RoI too small?

**Comment by Nilvus** [comment]
pixls.us forum is a better place to discuss related things. I suggest you to post there: https://discuss.pixls.us/c/software/darktable/19
This place is for issues related to darktable code and feature requests. Anyway, this will probably be a good discussion to follow.
