### ISSUE TITLE
[FLICKR] "Group rules" when joining the flickr group

### ISSUE THREAD

**Issue by yamila-moreno** [darktable-org/darktable#12391]
Hi there, I just joined the Flickr group and the disclaimer sent me to a Redmine that is currently down (https://redmine.darktable.org). Not sure if the redmine service should be up or the link in the disclaimer should be updated.
And also the information in the "home page" in flickr's group send the user to a (different) redmine which is now giving a 404 in the site.

**To Reproduce**
Go to flickr group. Try to join. Check the disclaimer. Check the homepage info.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/3340793/187048990-5e19c26b-6b9a-4b1b-8762-e2c6b4ec9396.png)
![imagen](https://user-images.githubusercontent.com/3340793/187049010-87af1139-9f70-4736-ad81-ae37820c1725.png)

**Comment by MStraeten** [comment]
the infos at Flickr aren’t up to date - you should contact the creator of the Flickr group if you can’t join. 
that’s not a darktable issue …
