### ISSUE TITLE
CANON EOS R10

### ISSUE THREAD

**Issue by jsepulvedaf** [darktable-org/darktable#12397]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

CR3  File form CANON EOS R10 IS NOT SUPPORTED BY DARKTABLE 4.0

**Comment by Nilvus** [comment]
Why posting another issue about same thing, especially when it was answer to you that R10 had been added in actual master (that means for next darktable version). We know that is not supported in darktable 4.0. On the web, using capitals means crying. No need for that here!

I so close your issues as supported is already added. Just wait next release: https://github.com/darktable-org/darktable/pull/12124

**Comment by cytrinox** [comment]
@jsepulvedaf Please upload a CR3 file shoot in **CRAW** mode as well. For now, there are only sample files available in **RAW** mode. You can change the mode in quality settings menu. Please ping back if your upload is done.
