### ISSUE TITLE
strange handling of bounded areas with segmentation based highlights correction

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#12399]
if clipped areas a properly bounded with non clipped areas, the default settings excludes that area:
before:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/39386816/187090370-39e2ac91-8b7b-4123-bd70-245ab8f337e6.png">
after (default: combine = 2):
<img width="720" alt="image" src="https://user-images.githubusercontent.com/39386816/187090380-d87bc4e1-25a7-4ea2-b076-0c39b2f80b2a.png">
need to set "combine" parameter to 6 to get a proper result:
 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/39386816/187090553-450c709f-c108-425e-b4c2-c728aab53a1c.png">

works as designed?

since there are people in the image i won't share the raw publically (@jenshannoschwalm: i can provide the image link per mail so you can reproduce it if necessary)

**Platform**
* darktable version :darktable 4.1.0+236~g78747838c
* OS                : OSx

**Comment by jenshannoschwalm** [comment]
That's exactly what the combining is for 😎

The reconstruction uses "candidates" for reconstruction, for a proper candidate we need a smooth gradient somewhere for each segment. The dark structures prohibit[]() that. So we have two ways to handle this
1. Set the candidates slider to very low or zero, this results in simple impainting, stable but not of best Quality.
2. Combine segments - this is often much better.

**Comment by jenshannoschwalm** [comment]
BTW, we have some examples of this problem in the highlights image test set that @Iain provided.

We are planning a video conference in a month or so to demonstrate highlight reconstruction problems and how to handle this in dt. Your photo looks like a good and typical example. Possible?

**Comment by MStraeten** [comment]
as long as it doesn't find its way into the public it's ok. 

so i close here

**Comment by jenshannoschwalm** [comment]
Would appreciate if you could email the file to hanno@schwalm-bremen.de

Will not distribute in any way and will delete the file after investigation and possibly a demo via video
