### ISSUE TITLE
Looking for business cooperation in the integrated development of intelligent transfer and color matching system

### ISSUE THREAD

**Issue by wellme99** [darktable-org/darktable#12402]
**Is your feature request related to a problem? Please describe.**

There is some deviation in the recognition and adjustment of shadow and highlight areas in the picture.

**Describe the solution you'd like**

At present, we are developing a set of intelligent shift color matching system. At present, we have encountered some problems in image processing. I find that your application meets our requirements, but there is a small defect, that is, there is a gap in the adjustment of shadows and highlights; Our idea is that we can conduct business cooperation. If you are interested, we can talk about it. My email is: 810778810@qq.com

**Alternatives**

**Additional context**

**Comment by TurboGit** [comment]
@wellme99 : We are not looking for business but cooperation on the Open Source darktable code. If you have anything to share or improve please post a PR with the modifications and we will examine it and merge it into dt code if it meets darktable quality goal. Thanks.
