### ISSUE TITLE
Fixed culling view doesn't reset last state

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#12406]
**Describe the bug/issue**

Some reset seems to be missing on fixed culling view as the last number of images shown in fixed culling view is kept. Probably an old issue. @AlicVB: should be a simple one for you and come back after your holidays!

**To Reproduce**
1. Select 2 images on lighttable and be sure that fixed culling view (third icon in bottom bar) is set to 2 images AND have no bars or panels showed
2. Click on third icon or use shortcut
3. Reject one of the 2 images shown and see that culling view only display one image. Just normal as it's a fixed selection.
4. Go back to lighttable main view
5. Select another set of 2 images then do again step 2
6. See that only one image is shown and that you could display both selected images if you make bottom bar appear with Shift+ctrl+b

**Expected behavior**
When selecting another set of images and go back to culling fixed view, selected images should appear.

**Platform**

* darktable version : last master
* OS                : Debian Sid

**Comment by AlicVB** [comment]
> 3\. Reject one of the 2 images shown and see that culling view only display one image. Just normal as it's a fixed selection.

That's where my test differs... In your case, when I reject one image, the next one in the list is shown instead, so I still have 2 images shown.
Internally, the above behavior is due to the fact that if the selection is the same as what is shown in culling, this is not considered as a "real" selection (to limit the culled image to this selection only) but as a "false" selection, like when the selection as just one image. But I admit that it's debatable and I wonder if it's ok here...

That said, for your issue : I can't reproduce !

**Comment by Nilvus** [comment]
> > 3. Reject one of the 2 images shown and see that culling view only display one image. Just normal as it's a fixed selection.
> 
> That's where my test differs... In your case, when I reject one image, the next one in the list is shown instead, so I still have 2 images shown. Internally, the above behavior is due to the fact that if the selection is the same as what is shown in culling, this is not considered as a "real" selection (to limit the culled image to this selection only) but as a "false" selection, like when the selection as just one image. But I admit that it's debatable and I wonder if it's ok here...

Did you test it in culling fixed mode? Such behavior (next image shown) is on dynamic mode, not fixed one. My issue is only when I select 2 images (and of course having images displayed on culling field (bottom bar) to 2 images only) AND go on fixed mode WITHOUT any panels around.

The issue don't appear in dynamic mode (I have behavior you describe here) and do not appear too when having panels around image in fixed culling mode.

**Comment by AlicVB** [comment]
ok, I finally manage to reproduce, but with 3 selected image at start and the rejection of 2 images.
PR #12434 should fix it
