### ISSUE TITLE
Darktable - Export to Piwigo - Unexpected change of filename

### ISSUE THREAD

**Issue by urhekryd1** [darktable-org/darktable#12401]
**Short description:**
Unwanted filename change at the end of darktable-piwigo-workflow.
For me, it seems to be a bug, but maybe, I do something wrong.

**Long description:** (I’m german, sorry for my not perfect english)
I use darktable in combination with piwigo, 
My equipment: Several Apple Computers, MacOs 12.01, Darktable v. 4.0.0, Latest Piwigo-Version [Version 12.3.0]

My workflow
I collect my raw and jpg photo files on my Macbook Pro in folders (finder) and rename them first
(Example filename: „2022-08-03_10492501_ury.dng“)

Settings Darktable: „Show global preferences - Import“: „keep original filename“: true

<img width="760" alt="Bildschirmfoto 2022-08-29 um 00 14 54" src="https://user-images.githubusercontent.com/76160578/187096642-6a818b70-a83e-4349-b673-7fa7420ee5cd.png">

Next step: Import folder with photos in darktable (in lighttable)
After import: DT „image information“ shows the correct filename, this is as expected:
„2022-08-03_10492501_ury.dng“

<img width="373" alt="Bildschirmfoto 2022-08-29 um 00 22 55" src="https://user-images.githubusercontent.com/76160578/187096905-8917e987-6a4b-4240-8901-a0c3d69b04c4.png">

DT Export - storage options - target storage: „piwigo“
„edit metadata exportation“:
EXIF data: √
metadata: √
only embedded: not checked

<img width="522" alt="Bildschirmfoto 2022-08-29 um 00 26 02" src="https://user-images.githubusercontent.com/76160578/187097003-c8c850c0-3f89-4f0b-938e-d011f92c2578.png">

Set Piwigo Server Settings and select Export-Folder
Set format and global options
Export photo to piwigo, ...that works perfectly √

<img width="405" alt="Bildschirmfoto 2022-08-29 um 00 29 59" src="https://user-images.githubusercontent.com/76160578/187097133-e5b0099f-578c-4b85-abdf-0bd25eddf6b1.png">

BUT:
The filename of the uploaded photo in piwigo has changed to: „darktable.PP96Q1.jpg“
This is unwanted. I want to maintain my self choosen filename

<img width="328" alt="Bildschirmfoto 2022-08-29 um 01 08 25" src="https://user-images.githubusercontent.com/76160578/187098385-4cb050a4-a4b4-4c0d-a907-228d783db66e.png">

**Now my question:**
Why is this? Why there is a new filename although I’ve choosen „keep original filename“?
Is there something in the settings, I missed?

* darktable version : 4.0.0
* OS                : MacOs 12.01
* piwigo: 12.3.0

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 
[2022-08-03_10492501_ury.dng.txt](https://github.com/darktable-org/darktable/files/9440596/2022-08-03_10492501_ury.dng.txt)

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **I don't know**
 - Do you use lua scripts? **no**
 
**Did you buy darktable from an application store ?**
no

**Comment by TurboGit** [comment]
> For me, it seems to be a bug, but maybe, I do something wrong.

You are not doing something wrong. The export filename cannot be changed and is following a pattern `darktable.XXXXXX.<ext>`.

**Comment by urhekryd1** [comment]
Ok, thank you for information, ...I understand.

For me, this fact seems to show an inconsistency in DT:

-> If you export a photo through "storage options" -> "file on disk"
you receive a file on disk, which have the **same filename like the one, you imported**, and also the **same filename like the one shown in DT** under "image information"

![Bildschirmfoto 2022-08-29 um 20 43 36](https://user-images.githubusercontent.com/76160578/187274773-212f6021-cd3b-4021-b682-4ee426fb60ef.png)

-> BUT if you export a photo through "storage options" -> "piwigo"
you receive a filename (in piwigo) following a pattern, which has **nothing to do with your original photo** (and there is no convenient way for you, to trace it back)

![Bildschirmfoto 2022-08-29 um 20 45 47](https://user-images.githubusercontent.com/76160578/187275108-3e5d88dc-5061-4c67-9484-d2f63d40ee28.png)

Do you know the reason for this divergence?

**Comment by ptilopteri** [comment]
piwigo set it's own filename for it's database and that is what
you see.  If you open the image in piwigo, you can see it's real 
filename in the information.

**Comment by urhekryd1** [comment]
Sorry, ...not true.

The more right is, like [TurboGit](https://github.com/TurboGit) commented:
_"The export filename cannot be changed and is following a pattern darktable.XXXXXX.<ext>."_

I made a test some minutes before. This is my download list from Firefox:
<img width="483" alt="Bildschirmfoto 2022-08-29 um 22 26 59" src="https://user-images.githubusercontent.com/76160578/187292847-90988e60-1569-495b-aad4-87732402aa41.png">

**Both files were downloaded from piwigo:**
- The lower file is a previous via DT uploaded file, note the changed filename "darktable.xxxxxx.jpg
- The upper file was previously uploaded from my Macbook **directly** to piwigo, it shows my original filename, which hasn't changed, ...and thus, this is perfect for a professional workflow.

So, the comment from [ptilopteri](https://github.com/ptilopteri):
_"...piwigo set it's own filename..."_
is definitely not right.

Does anybody see a chance, that someone is going to solve this?
I'm a pretty new user of darktable, and I can tell, **I appreciate it!** But I need beneath the capabilities of DT additionally a program, to share my photos.

DT has already an export option to piwigo, which works well (except change of filename). Piwigo is open source, like DT. For me, it complements DT perfectly, ...but I think, filenames shouldn't change at all, if the photographer doesn't want it. What is your opinion?

**Comment by gi-man** [comment]
darktable is using the piwigo api to upload the images. The darktable code generates a temporary filename for the upload. It looks like the file you uploaded might be using their website interface, so it might allow a different filename scheme.

I did a search thru the piwigo website and the current API might be able to handle a different approach, but it will need for someone to do the code and test it.

**Comment by urhekryd1** [comment]
[gi-man](https://github.com/gi-man) wrote:
> The darktable code generates a temporary filename for the upload.

Yes, that sounds right for me. And the problem is: This "temporary filename" ends up in piwigo then, and is not anymore "temporary" but permanent!

and:
> It looks like the file you uploaded might be using their website interface, ...

Yes, my test upload was performed via piwigo website, ...of course, no change of original filename here

and:
> I did a search thru the piwigo website and **the current API might be able to handle a different approach, ...**


Yes, I hope so, because it's like I said before:
" ... filenames shouldn't change at all, if the photographer doesn't want it."
If DT offers a possibility to export to another "system", it should work consistent and as expected, otherwise this option makes no sense.

finally [gi-man](https://github.com/gi-man) wrote:
> ..., but it will need for someone to do the code and test it.

Yes again!
I'm not able, to "do the code", but if possible I could help with testing. I think, there are good reasons to adjust this.
**Therefore my question: Is here somebody able to do it, ...and more important, convinced that it should be done?**

I would appreciate it. Thanks for now.

**Comment by quovadit** [comment]
@urhekryd1 : I already created a PR which uses a different upload-approach without renaming the files: #11696
Hopefully it will be part of 4.2
