### ISSUE TITLE
Clear broken links in database

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#12408]
**Is your feature request related to a problem? Please describe.**

I do not use Darktable to move files because of this bug https://github.com/darktable-org/darktable/issues/10115

**Describe the solution you'd like**

When I move files outside of Darktable, I retain all metadata and modification timestamps of the files. 

This, however, becomes an issue for Darktable, because the file link is now broken in the database. 

**Additional context**

The only solution is to delete the Darktable database and re-import all 40k files.

**Comment by Nilvus** [comment]
Broken links if you move files outside darktable is not an issue. How can darktable know where you move your images? If you move images, you have no other way to delete/import them to make darktable know new destination. If it's a whole folder, you could also right-click on folder in collections module to update link.

Timestamps is a known issue and you link it, so what the purpose of that issue?

**Comment by naisanzaa** [comment]
> How can darktable know where you move your images? 

Mostly because there is no thumbnail preview anymore. The thumbnail becomes a black box. 

I'm wondering if Darktable knows there is no thumbnail when it only displays a black box.

**Comment by ptilopteri** [comment]
darktable does not know where you move your images because you 
have not told it, nothing to do with the thumbnails.

as thumbnails match the corresponding image, and you have moved 
the image, no thumbnail can be displayed because there is no corresponding 
image.

you broke the file link.

darktable does not search your system for your images.  YOU must inform 
darktable when you move images or use darktable to move the images.

please close this issue as it is not a darktable problem.

**Comment by naisanzaa** [comment]
> no thumbnail can be displayed because there is no corresponding image.

Exactly this. 

Darktable knows when a thumbnail can or cannot be shown. 

This is what the logic would look like. 

1. Lightroom view 
2. Images populate
3. Thumbnails populate
4. Existing file, shows thumbnail
5. Else, show black icon

If 5 is True:
  deleted file

**Comment by Nilvus** [comment]
> If 5 is True:
>   remove from database 
> ```

Completely disagree here. How a user could know if he make a wrong move outside darktable? Just remember that sometimes, it's something not wanted (move of files, or removal). Having a way to know which images link are broken is good. If the removal is automatic, this is no more possible.

It's up to the user to be careful of what he does, not (to any) software to completely assist him.

**Comment by HansBull** [comment]
https://docs.darktable.org/usermanual/development/en/special-topics/program-invocation/purge_non_existing_images_sh/

**Comment by naisanzaa** [comment]
>  Having a way to know which images link are broken is good. 

Automated removal wasn't the goal. I was just saying there is logic here that Darktable knows if a link is broken or not.

Simply because the "non-thumbnail icon" is used. Otherwise Darktable wouldn't be using that asset. 

The literal use of that asset, is the logic. 

```
if "non-thumbnail icon" used:
    file is broken 
```

**Comment by naisanzaa** [comment]
> https://docs.darktable.org/usermanual/development/en/special-topics/program-invocation/purge_non_existing_images_sh/

I guess this, but in the UI.

**Comment by Nilvus** [comment]
> > https://docs.darktable.org/usermanual/development/en/special-topics/program-invocation/purge_non_existing_images_sh/
> 
> I guess this, but in the UI.

As this issue is not an issue, I close it (explanations are on our comments here. Creating a clear feature request about what you want about that would be better. Try to be clear of what you want and not what you don't find your way. That will help. Thanks.
