### ISSUE TITLE
Add shadow effect option to textual watermark

### ISSUE THREAD

**Issue by l0f4r0** [darktable-org/darktable#12414]
**Is your feature request related to a problem? Please describe.**
Sometimes, depending on the picture and the watermark text/font/color used, the watermark is not very visible.

**Describe the solution you'd like**
Add an optional shadow effect to the watermark text like in Lightroom (sub-options: opacity, offset, radius, angle) so the text stands out better.

**Comment by Mark-64** [comment]
This can be done in another program (GIMP or similar) and used in DT with a png watermark

**Comment by MStraeten** [comment]
or a copy of the instance with slightly modified size, x,y,position, color and opacity

**Comment by TurboGit** [comment]
Would be nice to have some kind of support for that for simple text watermark. In the mean time you can copy the SVG, modify it and use it in place of the default text SVG.

**Comment by TurboGit** [comment]
Not configurable, but maybe doing the job:

Place this into ~/.config/darktable/watermarks/simple-text-shadow.svg

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg"
     x="0"
     y="0">

  <text x="0.2px" y="5.2px" text-anchor="start"
        xml:space="preserve"
        fill="#222222"
        font-family="$(WATERMARK_FONT_FAMILY)"
        font-style="$(WATERMARK_FONT_STYLE)"
        font-weight="$(WATERMARK_FONT_WEIGHT)"
        font-size="10px">$(WATERMARK_TEXT)</text>
  <text x="0" y="5px" text-anchor="start"
        xml:space="preserve"
        fill="$(WATERMARK_COLOR)"
        font-family="$(WATERMARK_FONT_FAMILY)"
        font-style="$(WATERMARK_FONT_STYLE)"
        font-weight="$(WATERMARK_FONT_WEIGHT)"
        font-size="10px">$(WATERMARK_TEXT)</text>
</svg>
```

For a larger shadow just replace the .2 above with .3 or larger.

**Comment by TurboGit** [comment]
Maybe worth adding this into darktable?

**Comment by jenshannoschwalm** [comment]
I have only used watermarks very rarely - while testing & debugging mainly - so no strong opinion here but why not?

**Comment by l0f4r0** [comment]
I see this issue has been closed as completed.
Does someone confirrm that this enhancement has been added to darktable codebase indeed please?

**Comment by TurboGit** [comment]
@l0f4r0 : No not integrated, I was waiting for some feedback from you as you raised the issue. You did not even replied saying it was ok on your side.

**Comment by l0f4r0** [comment]
> @l0f4r0 : No not integrated, I was waiting for some feedback from you as you raised the issue. You did not even replied saying it was ok on your side.

Oops, you're right indeed!

Thank you for your contribution, it works :)

For me, personnally, it's ok now because I can tweak the svg file.
Some other people, as suggested previously in this issue, will duplicate and differenciate the watermark instance, or work under a graphical editor like Gimp...
...But maybe, ideally, it could worth adding some configuration settings inside the watermark module directly? I think it would be easier for less tech-savvy users (if a developper knows how to implement it inside darktable of course...)

**Comment by TurboGit** [comment]
Ok, I'll integrate my SVG for 4.2 then. Thanks.

**Comment by l0f4r0** [comment]
Thanks to you

**Comment by TurboGit** [comment]
Done. Will be in 4.2.

**Comment by wohler** [comment]
I see simple-text-shadow.svg in darktable 4.8.1. However, with my white text, the shadow doesn't work as well as I'd like on a light background. If anyone has a combination of offset and color that works well for them, please shout out.

In flatpak, would I drop the updated simple-text-shadow.svg in .var/app/org.darktable.Darktable/config/darktable/watermarks?

**Comment by wohler** [comment]
Yes, .var/app/org.darktable.Darktable/config/darktable/watermarks is the right directory.

I was able to improve (for me) the default with the following offset and color for the shadow. It could be better, but I don't have the chops to make it so.

  <text x="0.7px" y="5.7px" text-anchor="start"
        xml:space="preserve"
        fill="#000000"
