### ISSUE TITLE
In retouch the brush source is not fully copied to target

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12410]
**Describe the bug/issue**
The brush source is not fully copied to target. The retouch module only starts to copy from where the source start is projected to the target. See the picture below.
![image](https://user-images.githubusercontent.com/5797282/187358080-720b3bb6-d6a9-412f-a386-c0f3b38b3dc8.png) 
![image](https://user-images.githubusercontent.com/5797282/187358143-d2f2d330-f6d2-4a3a-ab8f-249e51b1759f.png)

**To Reproduce**
1. Open an image in darkroom
2. Open retouch module
3. Draw a brush line
4. Move the source so that the start of the source is clearly projected below the start of the target

**Expected behavior**
The source is copied to the target at full length

**Platform**
* darktable version : 4.1.0+236~g78747838c
* OS                : Win10
* Memory            : 32GB
* Graphics card     :  NVidia T500
* OpenCL installed  : yes
* OpenCL activated  : the bus is present both OpenCL activated and inactive

**Additional context**
 - Can you reproduce with another d
 - arktable version(s)? **yes with version 4.0, and with 4.1 on Linux**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 
[P6221669.zip](https://github.com/darktable-org/darktable/files/9449947/P6221669.zip)

**Comment by ralfbrown** [comment]
Confirmed with current 4.3.0 master, but only for brushes.  Circles, ellipses, and paths work correctly.  Brushes are either computing the position of the source patch incorrectly, or are incorrectly displaying the line representing the source patch.  There is a considerable offset in both the X and Y coordinates, such that the upper left end of the source line must be considerably below the top edge and quite a bit to the right of the left edge for the source patch to actually be entirely within the image.
