### ISSUE TITLE
Windows build: GMIC not detected in branch 4.0.x

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#12416]
Building branch 4.0.x in Windows, Cmake does not detect GMIC.
Maybe commit 287c111f65cf9c50ba4cb19d9751e04354c3a703 missing ?

EDIT: indeed merging that commit solves the issue

**Comment by Mark-64** [comment]
Or maybe it's because I am using the new UCRT build and I should use the old system in 4.0.x?

**Comment by kmilos** [comment]
Yep should backport that @TurboGit

**Comment by TurboGit** [comment]
Ok, commit `287c111f65cf9c50ba4cb19d9751e04354c3a703` back-ported to 4.0.x branch.
