### ISSUE TITLE
Question: Setting Up MIDI Controllers

### ISSUE THREAD

**Issue by b177y** [darktable-org/darktable#12421]
I'm trying to use the Behringer X touch mini with Darktable 4.0 on Linux. The device is connected successfully (shows up as `client 24: 'X-TOUCH MINI' [type=kernel,card=2]` with `aconnect -i`) and is detecting input (inputs show up with `aseqdump -p 24`).

Are there any example walkthroughs of setting up shortcuts with MIDI devices? I have seen https://docs.darktable.org/usermanual/4.0/en/special-topics/midi-device-support/ and https://docs.darktable.org/usermanual/3.8/en/preferences-settings/shortcuts/ but I'm not able to set up shortcuts.

When double clicking on an action in the shortcut section of preferences, Darktable only detects keystrokes from the qwerty keyboard but not button presses / knob turns from the MIDI keyboard. Not sure if this is a Linux setup issue or if I need to enable something in Darktable for it to work?

**Comment by MStraeten** [comment]
is the midi device properly detected if you start darktable from command line? Have a look for [midi_open_devices] in the output

**Comment by b177y** [comment]
Ah yes same issue as #12422 - on launch I get the error `[lib_load_module] failed to open `midi': libportmidi.so.1: cannot open shared object file: No such file or directory`, but after installing portmidi I get `[midi_open_devices] opened midi device 'X-TOUCH MINI MIDI 1' via 'ALSA' as midi0`

All working now, thank you 👍

**Comment by Nilvus** [comment]
@b177y: it's so good to close issue you open when fixed. I close it this time.
