### ISSUE TITLE
Panasonic Lumix DC-GH6

### ISSUE THREAD

**Issue by uvolfen** [darktable-org/darktable#12426]
Please add support for the Panasonic Lumix DC-GH6.
A uploaded a full set (all variants of crops) on raw.pixls.us with  Creative Commons Zero (CC0) license at August, 22nd.

Thanks a lot!

   Uwe

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/rawspeed/issues/367

**Comment by Nilvus** [comment]
So closing
