### ISSUE TITLE
Lens correction not applied correctly for mobile phone ultra wide lens

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12423]
**Describe the bug/issue**
I have created distortion correction data for OnePlus 10 Pro mobile phone's cameras. For the ultra wide lens, the correction parameters provide different results in Hugin than it does in darktable.

**To Reproduce**
1. Create the distortion correction parameters as instructed for lensfun db for OnePlus 10 Pro ultra wide lens
2. Verify the parameters in Hugin
![image](https://user-images.githubusercontent.com/5797282/188008943-bb242f73-e851-4361-8357-4d800960c447.png)
3. Create an .xml-file for the lens (with correct focal length 2.3mm)
4. Start darktable and apply the lens correction
![image](https://user-images.githubusercontent.com/5797282/188008623-9bb35161-66f5-4b79-9c28-b3ae9549a9d1.png)
5. Edit the lensfun .xml file for the camera, and change the focal length to 2.1mm (this value slightly over corrects, but shows the issue)
![image](https://user-images.githubusercontent.com/5797282/188011073-404e1eef-4b42-4fe6-9bc1-d35ab541943b.png)

**Expected behavior**
The correct focal length could be used in the lensfun database.

**Platform**
* darktable version : 4.0.0
* OS                :  Windows 10
* OpenCL installed  :  yes
* OpenCL activated  : both active and inactive

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with version 4.1.0**
 - lensfun defintions [oneplus.txt](https://github.com/darktable-org/darktable/files/9473432/oneplus.txt)
 - see also the discussion in [Pixls.us](https://discuss.pixls.us/t/how-to-enable-dt-recognize-the-correct-smartphone-lens/32168)

**Comment by MStraeten** [comment]
better report lensfun database issues at https://github.com/lensfun/lensfun ...
here no one can help.
