### ISSUE TITLE
Copy/Paste Issue

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#12435]
dt Ver:4.1.0+284~g818c3b48ce ... Manjaro/Arch/XFCE
Noticed on this and earlier versions that ^c to ^v is causing the program to freeze and then close.
When I have 2 similar images I often process the first and then copy my results to other images as a starting point.
I am doing this directly from the darkroom window.

**Comment by davidvj** [comment]
I think that I have isolated the problem.
First, I am working on am older laptop with a Nvidia Quadro K1000 graphics card. The system has 16Gb. memory. OpenGL is installed and appears to be working correctly.
The cut/Paste problem only occurs when I use 2 occurrences of diffuse&sharpen.
Now that I better understand the situation I will refrain from cut/paste with such images.
I have recently been using d&s for highlight enhancement ....this module apparently has a very wide range of uses.
Probably this issue should be now closed.

**Comment by davidvj** [comment]
I think that I have isolated the problem.
First, I am working on am older laptop with a Nvidia Quadro K1000 
graphics card. The system has 16Gb. memory. OpenGL is installed and 
appears to be working correctly.
The cut/Paste problem only occurs when I use 2 occurrences of 
diffuse&sharpen.
Now that I better understand the situation I will refrain from cut/paste 
with such images.
I have recently been using d&s for highlight enhancement ....this module 
apparently has a very wide range of uses.
Probably this issue should be now closed.

**Comment by ptilopteri** [comment]
You are able to close it!
