### ISSUE TITLE
FR: Multiple instances of highlight recovery

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12432]
**Describe the solution you'd like**
Different blown high lights may need different recovery strategies. It would be nice to use different algorithms for different parts of the images. E.g. for blown clouds/windows segmentation based and for lamps guided laplacian, Currently it's only possible to have one instance, but if, like most of the other modules, you could have several instances of the module, you could achieve this.

**Additional context**
See @jenshannoschwalm comment at [pixls.us](https://discuss.pixls.us/t/two-instances-of-high-light-recovery/32440/2).

**Comment by parafin** [comment]
I think there is a technical reason why multi-instance wasn’t enabled for highlight recovery. I’m pretty sure it’s possible to dig it up in comments on some github issue, but I suppose it’s along the lines that highlight recovery both uses and updates image white level values, which will break if it’s applied twice.

**Comment by jenshannoschwalm** [comment]
All 3 "new modes" don't update the white point any more so i think technically it would be `possible` but with a lot of possible issues and unpredictable results ...
