### ISSUE TITLE
3D Luts .cube Format

### ISSUE THREAD

**Issue by migltigl** [darktable-org/darktable#12441]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**
.cube LUTS wont work anymore since new Update 4.0.0.
I have used these LUTs before. Everytime I want to apply a LUT via the Module there comes an info that the .cube File is not valid
I have cheched my root destination folder for the luts

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'LUT 3D'
2. Apply  LUT (free download form ON1 (https://www.on1.com/free/luts/)
3. See error message 

**Expected behavior**
Application of LUT

**Screenshots**
![Screenshot 2022-09-08 174026](https://user-images.githubusercontent.com/113125209/189165636-058f3b57-950a-4c36-95b0-fdae3f4931b9.png)

_(if applicable)_
![Screenshot 2022-09-08 174202](https://user-images.githubusercontent.com/113125209/189165958-34f4acb3-71cd-45a4-8f8d-354559e7ca52.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.0
* OS                : Win11 
* Memory            : 32
* Graphics card     : RTX A4000
* Graphics driver   : Nvidia
* OpenCL installed  : No
* OpenCL activated  : No

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? no, not installed
 - Can you reproduce with a RAW or Jpeg or both? **RAW only tested
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")?  yes
 - Do you use lua scripts? NO
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by MStraeten** [comment]
please provide the lut that doesn't work to reproduce.
my used .cube luts works fine

**Comment by migltigl** [comment]
Hi Martin

 

Thank you very much for your quick answer. Really appreciate your work for Darktable.

I send you some example .cube that I want to use.

These are the free LUT’s from ON1 (if you want to download some for testing)

 

Thank you very much!

 

Kind regards

 

Mikael

 

Von: Martin Straeten ***@***.***> 
Gesendet: Donnerstag, 8. September 2022 18:07
An: darktable-org/darktable ***@***.***>
Cc: migltigl ***@***.***>; Author ***@***.***>
Betreff: Re: [darktable-org/darktable] 3D Luts .cube Format (Issue #12441)

 

please provide the lut that doesn't work to reproduce.
my used .cube luts works fine

**Comment by phweyland** [comment]
If I remember correctly the prefix "INVALID >>" means that this already known lut file is not accessible anymore with the current lut root folder (preferences).

**Comment by migltigl** [comment]
Hi Philippe

 

I’ve tried different approaches…. Selecting in preferences the very top folder or the very bottom folder directly linked with the luts and

I’m a little closer now but theres now an error…. (please find attached ) 

 

Now I can select the .cube via Dropdown but It calls for an error « cube LUT line 0 is not correct »

 

Thanks for your help

 

Kind regards

Mikael

 

 

Von: Philippe ***@***.***> 
Gesendet: Sonntag, 11. September 2022 00:04
An: darktable-org/darktable ***@***.***>
Cc: migltigl ***@***.***>; Author ***@***.***>
Betreff: Re: [darktable-org/darktable] 3D Luts .cube Format (Issue #12441)

 

If I remember correctly the prefix "INVALID >>" means that this already known lut file is not accessible anymore with the current lut root folder (preferences).
