### ISSUE TITLE
When configuring the metadata perferences, if the formula cell is active, the formula is not saved

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#12448]
**Describe the bug/issue**
When configuring the metadata perferences, if the formula cell is active, the formula is not saved (see video below).

**To Reproduce**

1. Open "Preferences" by clicking on the hamburger icon in the "export" module:

![Perf1](https://user-images.githubusercontent.com/38165484/189363075-6572b811-1456-4d07-94a1-e246bb3a89fd.jpg)

2. add an output meta tag by clicking on "+" icon:

![Perf2](https://user-images.githubusercontent.com/38165484/189363767-dfdae40a-315b-4347-a9ce-3d16c956be57.jpg)

3. Add a formula to the formula cell:

![Perf3](https://user-images.githubusercontent.com/38165484/189365123-1a9a35a0-82b3-4b54-a3b7-be2d0faa993d.jpg)

4. If you now press "save" and _formula cell is still active_, the formula _will not be saved_.
5. Only if you have "deactivated" the formula cell after entering the formula by clicking _somewhere outside the formula cell_, the formula is also saved when you click on "save".

**Expected behavior**

Regardless of _whether you are still in the formula cell after the entry or not_, the formula _should be saved_ when you click on "save". Otherwise is very confusing because there is no indication that the formula cell should not be active before clicking on "save" option. 

**Screencast**

https://user-images.githubusercontent.com/38165484/189370876-64761d70-175f-459f-8c0d-32b9bb7e77de.mp4

**Platform**

- darktable version : 4.1.0~git272.5a1a1845-1
- OS : Linux
- Linux - Distro : Ubuntu Studio 22.04
- Memory : 31,3 GiB
- Graphics card : NVIDIA GeForce GTX 1070/PCIe/SSE2
- Graphics driver : 470.141.03
- OpenCL installed : yes
- OpenCL activated : yes
- Desktop : KDE-Plasma-Version: 5.24.6

**Comment by phweyland** [comment]
If I remember correctly, formulas are associated to the metadata when hitting "Enter" and  the "Save" button saves all the data in the popup.
This said I agree that the "Save" button could re-enforce the association metadata - formula, which particularly true when one enters a single (new) formula.
