### ISSUE TITLE
Lens correction vignetting broken.

### ISSUE THREAD

**Issue by leftclick2win** [darktable-org/darktable#12461]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**
So im trying to remove vignetting from a image i took with sony A6300 and Sony E 70-350mm f4.5-6.3 G OSS by using lens correction, i have set it to correct all but it isnt removing any vignetting.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to'lens correction'
2. Click on 'enable'
3. Scroll down to '...'

**Expected behavior**
on other photos from other camera it has removed the vignetting.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by MStraeten** [comment]
did you check if your lens is supported by lensfun?

**Comment by ralfbrown** [comment]
and that your installation of lensfun has an up-to-date database (run `lensfun-update-data`).

It's also entirely possible for lensfun to have distortion correction but no vignetting correction for a particular lens.

**Comment by victoryforce** [comment]
> So im trying to remove vignetting from a image i took with sony A6300 and Sony E 70-350mm f4.5-6.3 G OSS by using lens correction, i have set it to correct all but it isnt removing any vignetting.

Please look at [Lensfun coverage](https://wilson.bronger.org/lensfun_coverage.html).
Find your lens on this page and you'll see that vignetting is not corrected for that lens by lensfun.

Since there's nothing darktable team can do about this consider closing this issue.

**Comment by jenshannoschwalm** [comment]
> Since there's nothing darktable team can do about this

Well - maybe can change the lens ui reporting about missing data?

**Comment by Nilvus** [comment]
I so close as it's lensfun related. And when posting an issue, think about removing unuseful infos. That will help to read and find useful infos.
