### ISSUE TITLE
$CATEGORY1(category) does not get replaced when used in export path

### ISSUE THREAD

**Issue by jerrac** [darktable-org/darktable#12467]
**Describe the bug/issue**
When exporting to a folder based on category tags, any index higher than 0 does not get replaced by the category tag name.

For `Album|category|subcategory`

`/path/to/TestExports/$(CATEGORY0(Album))/$CATEGORY1(Album)/$(FILE_NAME)` becomes `/path/to/TestExports/category/$CATEGORY1(Album)/file.jpg`.

This occurs when you don't manually set each level as a category tag, and when you do manually set each level as a category tag.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Add a hierarchical tag to an image like `Album|category|subcategory`.
2. Set your export path to `/path/to/TestExports/$(CATEGORY0(Album))/$CATEGORY1(Album)/$(FILE_NAME)` 
3. Export your image. 
4. It will end up at `/path/to/TestExports/category/$CATEGORY1(Album)/< your file name >`.

**Expected behavior**
The file should end up at `/path/to/TestExports/category/subcategory/< your file name >`.

**Platform**

* darktable version : 4.1 and 4.0
* OS                : For dt 4.1, PopOS 20.04. For dt4.0, Windows 10.
* Linux - Distro    : PopOS 20.04
* Memory            : N/A
* Graphics card     : N/A
* Graphics driver   : N/A
* OpenCL installed  : N/A
* OpenCL activated  : N/A
* Xorg              : N/A
* Desktop           : N/A
* GTK+              : N/A
* gcc               : N/A
* cflags            : N/A
* CMAKE_BUILD_TYPE  : N/A

**Additional context**

 - Can you reproduce with another darktable version(s)? I first ran into this on Windows 10 with version 4.0. Then reproduced it on my main Linux machine with a newly compiled/upgraded tags/release-4.1.0.
 - Can you reproduce with a RAW or Jpeg or both? Likely not something to do with RAW vs. Jpeg, but I only tested on jpeg files.
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? I had no edits on my images.
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Yes.
 - Do you use lua scripts? Nope

Edit: Er, so, ignore my 4.1 testing stuff, I messed up how I was updating my local copy of the git repo. I'm fixing that now.

Edit2: Ok, now I'm really on 4.1.0 on Linux. Yes, the bug still occurs.

**Comment by phweyland** [comment]
> /path/to/TestExports/$(CATEGORY0(Album))/$CATEGORY1(Album)/$(FILE_NAME)

What if you use `/path/to/TestExports/$(CATEGORY0(Album))/$(CATEGORY1(Album))/$(FILE_NAME)` instead ?

**Comment by jerrac** [comment]
:\ Er, wow, yes, it was the missing `()`'s. Thanks!
