### ISSUE TITLE
Image is getting "greenish" when switching demosaic method

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#12474]
When switching the demosaic in this order:
1) to passthrough
2) to photosite
3) to VNG or PPG 
the main image is getting "greenish", preview is OK however.

darktable : 4.0.0 and 4.1.0+338
OS: Win 10
opencl: deactivated

**Comment by ralfbrown** [comment]
Confirmed.  Switching to Passthrough and then to any of the color demosaic modes (RCD, PPG, VNG4, AMaZE, LMMSE) gives the green cast.   Changing the WB in the White Balance module restores proper colors.  My guess is that Passthrough is setting the channel multipliers to 1.0 in WB and then they aren't being reinitialized when switching out of Passthrough mode, however, the White Balance GUI is still showing the original coefficients.

**Comment by jenshannoschwalm** [comment]
Will take care
