### ISSUE TITLE
Segmentation based highlight reconstruction name inconsistent

### ISSUE THREAD

**Issue by HSUfineprint** [darktable-org/darktable#12477]
The name of new highlight reconstruction mode is inconsistent in .pot file and highlights.c. Seems it was called "recovery" but now "segmentation based". I think we need check the mode names in .pot file.

1. pot line 15256 msgid: "**highlights recovery**", but the reference in ../src/iop/highlights.c:2237 is "**segmentation based**"

2. ../src/iop/highlights.c:2330, pot line 15268: _"you might use this for tuning 'laplacian' or **'recovery'** modes,\n"_

Not sure are these msgid in .pot got involved.
3733  #: ../build/lib/darktable/plugins/introspection_highlights.c:176
3734  #: ../build/lib/darktable/plugins/introspection_highlights.c:265
3735  msgid "**recovery**"
3760  #: ../build/lib/darktable/plugins/introspection_highlights.c:287
3761  msgid "**segmentation based**"

**Comment by TurboGit** [comment]
Sure, this is because the POT file has not been regenerated yet. Will do today.

**Comment by HSUfineprint** [comment]
Thanks, @TurboGit.

The second one uses "recovery modes" not only in POT, as well as in highlights.c. Maybe highlights.c should be modified too.
