### ISSUE TITLE
Release notes for 4.0.1

### ISSUE THREAD

**Issue by l0f4r0** [darktable-org/darktable#12495]
I see darktable 4.0.1 has been released (at least on repo https://download.opensuse.org/repositories/graphics:/darktable/Debian_11). Thank you!

It could be great to offer release notes for this version.
I don't see them yet on GitHub and Debian package only redirects to https://www.darktable.org/2022/09/darktable-4.0.1-released/ which is 404 at the moment.

There is always a lot of effort / hard work put inside each release. Best to show it :)

**Comment by kmilos** [comment]
Wish, tough crowd here 😉

https://youtu.be/tf47teVn6ZI

**Comment by Nilvus** [comment]
I like your comment and link @kmilos. Make me smile.
@l0f4r0: 4.0.1 is not released. Team prepare it. Just wait a little.

**Comment by l0f4r0** [comment]
Oh, it makes sense now ;)

I just wonder why 4.0.1 is already available through OBS then but you have probably nothing to do with it...
It has confused me, sorry.

**Comment by Nilvus** [comment]
No release notes means no official release out. Seeing a package is OBS doesn't mean anything, except that some packages are done for the release.. but not all.
And yes, here we do not managed directly OBS.
