### ISSUE TITLE
Add webp import to darktable

### ISSUE THREAD

**Issue by HochMartinez** [darktable-org/darktable#12500]
Hi, 

I have a web project where we have to manage hundreds of webp images.

As you know, Webp is becoming a standard for web image display because files are smaller and therefore, load faster than jpeg ones, offering the same quality.

We would like to be able to browse, tag and score those images with DT. And also and very important, do bulk adjustments.

I saw that you are using graphicsmagick in DT. This library has built-in webp support. So, IMHO, it should be fairly easy to add webp import capabilities to DT.

I'm sure that it will be useful to lots of users that have downloaded webp images from the web or work in web development. 

Thanks and keep up the good work! :-)

**Comment by victoryforce** [comment]
Interestingly, this is exactly what I'm currently working on. Yes, it is quite simple to implement.

**Comment by kmilos** [comment]
Great, but keep in mind that the GraphicsMagick fallback might not easily give you all the metadata like the embedded color profile, so if you're already investing time and effort, can you please consider going straight with the native way, i.e a dedicated libwebp based ioimage_webpb method (using e.g. webpdemux)?

**Comment by victoryforce** [comment]
> Great, but keep in mind that the GraphicsMagick fallback might not easily give you all the metadata like the embedded color profile,

Why do you think so? Not at all, everything works great through this library.

> so if you're already investing time and effort, can you please consider going straight with the native way, i.e a dedicated libwebp based ioimage_webpb method (using e.g. webpdemux)?

My plan is as follows:
- propose implementation using GraphicsMagick library for early testing
- maybe in the next PR add alternative support via ImageMagick (it should be just as fast and simple)
- if I'll have time to continue working on webp (for now, I have a lot of other interesting tasks on the list), I will try to add support through the libwebp library

Each of these libraries is optional and darktable can be built without any of them, so _this approach maximizes the chances of webp support_.

**Comment by kmilos** [comment]
> Why do you think so?

AFAIK, both GM and IM will internally convert to sRGB, so there is risk of image quality loss.

> My plan is as follows

The tiered approach sounds good, as long as the last step is not forgotten. ;)

**Comment by kmilos** [comment]
Attaching a test WebP image in HLG Rec 2020 color space, exported from https://polyhaven.com/a/shanghai_bund (pulled -1.5 EV).

[shanghai_bund_1k_hlg2020.zip](https://github.com/darktable-org/darktable/files/9608604/shanghai_bund_1k_hlg2020.zip)
