### ISSUE TITLE
build 8a2dcec09 fails to compile

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#12519]
openSUSE Tumbleweed 
VERSION_ID="20220916"

/usr/bin/msgfmt: found 4 fatal errors
573 translated messages, 1141 fuzzy translations, 1341 untranslated
/messages.
gmake[2]: *** [po/CMakeFiles/locale_ro.dir/build.make:73:
/share/locale/ro/LC_MESSAGES/darktable.mo] Error 1
gmake[2]: *** Deleting file 'share/locale/ro/LC_MESSAGES/darktable.mo'
gmake[1]: *** [CMakeFiles/Makefile2:2041: po/CMakeFiles/locale_ro.dir/all]
Error 2
gmake[1]: *** Waiting for unfinished jobs....
/data/dt-build/darktable/po/pt_BR.po:6: warning: header field
/'Project-Id-Version' still has the initial default value
4613 translated messages.
4614 translated messages, 1 fuzzy translation.
4615 translated messages.
4394 translated messages.
3718 translated messages.
4607 translated messages.
3871 translated messages.
4615 translated messages.
4615 translated messages.
gmake: *** [Makefile:156: all] Error 2

failing on four similar machines

**Comment by Nilvus** [comment]
Thanks for posting. I reproduce. I'm currently testing fix and PR is coming
