### ISSUE TITLE
Google Pixel 6 Pro

### ISSUE THREAD

**Issue by spktkpkt** [darktable-org/darktable#12515]
RAW samples are submitted to https://raw.pixls.us/ under CC0 license.

**Comment by Minwol** [comment]
Awesome, hope a profile is created soon

**Comment by kmilos** [comment]
Right, this (and Pixel 7 Pro it seems) is one of those rare cases where the `CameraCalibration` matrix should actually be used. @LebedevRI @jenshannoschwalm 

From the DNG spec: `XYZtoCamera = AB * CC * CM` (where AB is the analog balance), and we currently assume AB and CC are identity, and in this case CC is not even close...

**Comment by jenshannoschwalm** [comment]
Right :-)

**Comment by kmilos** [comment]
FYI, here's the outcome of hacking the multiplied matrix values back into the DNG file on the two raw.pixls.us samples (import and thumbnail refresh only, no further processing):
 
![image](https://user-images.githubusercontent.com/4973094/215463210-fc3707c2-49df-4fc1-9aa2-5be7d2e6a87c.png)

Next, it needs to be figured out where/how to multiply those in the actual code... 😉
