### ISSUE TITLE
Geo Tagging: Creation date cannot be shifted by more than 99 days

### ISSUE THREAD

**Issue by tronta** [darktable-org/darktable#12516]
**Describe the bug/issue**
The date of my camera has been accidentally set to the init value of the year 2014. Now I want to shift the pictures date to the correct value.
But if the time delta is more than 99 days, the delta is displayed as "- : - :  -" and the lock does also not react.
![Bildschirmfoto vom 2022-09-18 11-12-13](https://user-images.githubusercontent.com/5135577/190894725-dc9c97cb-5ca3-4705-9507-43dc3f528d44.png)

**To Reproduce**
1. Go Light Table
2. Select one image
3. Change the creation time under "Geotagging"
4. If the delta is > 99 days it is displayed as "-".

**Expected behavior**
The correct number of days are calculated and the delta can be applied.

**Screencast**
[Bildschirmaufzeichnung vom 2022-09-18, 11-28-21.webm](https://user-images.githubusercontent.com/5135577/190895448-e58a634e-2c59-497d-ab82-928384095808.webm)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* OS                : Linux 
* Linux - Distro    : Fedora 36

**Comment by phweyland** [comment]
True. I don't remember what was the limitation, but at this time I have not been able to overcome it.
