### ISSUE TITLE
lighttable: overlays for raw over exposure, raw under exposure (clipping basically) 

### ISSUE THREAD

**Issue by ydyote** [darktable-org/darktable#12518]
**Is your feature request related to a problem? Please describe.**

It would be nice when using lighttable in normal mode and also in the ctrl+alt+w there would be an option to turn on indicators/overlays for showing clipped shadows and highlights for RAW and also the classic clipping indication (which works with "current image" not raw)

it would make going through different exposures easier because one could decide based on the raw clipping which one is the best for postprocessing - detail wise

and some algorithms for the overlays are probably already implemented, maybe except the RAW shadows detection

**Describe the solution you'd like**

4 new buttons with single button shortcuts and clear descriptions to turn on 
raw highlights clipping
raw shadows clipping
current image highlights clipping
current image shadows clipping

in the bottom right corner 
![image](https://user-images.githubusercontent.com/54998537/190900932-7c0408af-5449-4136-b4a6-45ea98a14c48.png)

or something similar

**Alternatives**
Probably going into darktable view and turn it on there but then you cannot do your basic stuff you do in lighttable easily

**Additional context**
I found this, which is kinda close enough but its not part of the darktable https://discuss.pixls.us/t/display-highlight-clippings-in-lighttable/12105

I have no idea how much effort it is, how the code is structured whether its just a matter of adding some buttons and doing similar routine as for the "focus peaking mode" button or its something way more complicated + I also have no idea how much computing power it would need

Thanks.

**Comment by Nilvus** [comment]
Unfirtunately, this will not possible. Would need to much resources and actual computers dot not needed power. See #2579

So sorry, but a duplicate and I close this one. And I would like too such feature. Maybe in few years.
