### ISSUE TITLE
Unable to enter text into LightTable search entry box.

### ISSUE THREAD

**Issue by MkStevo** [darktable-org/darktable#12524]
Unable to enter text into LightTable search entry box by typing. Copy and paste of text into search box works, and searches correctly.

**To Reproduce**
Click on (in) search box.
Attempt to type.
As key presses typed, shortcuts are activated instead.
Typing "Camera" initially displays 'c' not assigned, 'a' not assigned, then as 'm' pressed, Map view opens.

**Expected behavior**
Text to appear in search entry box.

**Platform**
darktable version : 4.0.1 (64bit)
OS                : Windows 10
Device name	YogaAIO7
Processor	AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
Installed RAM	16.0 GB (15.4 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Home
Version	21H2
Installed on	‎23/‎02/‎2021
OS build	19044.2006
Serial number	YJ016VPV
Experience	Windows Feature Experience Pack 120.2212.4180.0

 - Can you reproduce with another darktable version(s)? **yes** 
 - 4.0.0 (64bit) tried, same error. 
 - 3.8.1 tried but failed to start.

 - Do you use lua scripts?
None that I am aware of, fresh default install of DarkTable today (18, September 2022)

**Comment by Mark-64** [comment]
With "search box" in Lighttable you mean this?
![immagine](https://user-images.githubusercontent.com/43290988/190927291-cbae022b-cfd2-4b41-89af-a39e40862f2d.png)

**Comment by dterrahe** [comment]
This is working fine for me on Win10. Any further information you can give that might give a clue why it doesn't for you? Where did you download from or did you compile yourself? Any keyboard utilities running in the background? Do other entry fields (like in the "export" module) work correctly?
