### ISSUE TITLE
darktable current master (Mac OSX build) crashes when opening an image in darkroom. White balance issue ?

### ISSUE THREAD

**Issue by zurdo-10** [darktable-org/darktable#12527]
**Describe the bug/issue**
darktable opens and import an image (.nef file from Nikon) in lighttable and crashes when trying to open the image in darkroom.
lldb suggests an issue with white balance (temperature.c)
I have been using current master OSX builds from MStraeten

The last build that works fine is:  [darktable-4.1.0+236~g78747838c_x86_64.dmg](https://mega.nz/file/OWIGXI5Y#xcO_8v8bPSkMEuhX62j06j56ztSKLPDhFYMlXYoal7o)

The next one is the first that showed the issue:  [darktable-4.1.0+283~g5cca9d64b_x86_64.dmg](https://mega.nz/file/XPQWHB7I#ecADJh48CM9VDQgqfp6azLRMy9DtUXnLQhuYTCnLaX4)

And the following ones all showed the issue up to the last one Martin build: [darktable-4.1.0+385~gf2ebe6b26_x86_64.dmg](https://mega.nz/file/vDgkDB6Q#8QUlYYscPPGa_rVyDUHfP8olN1l6zlVSsLgfUYEe_Rs)

**To Reproduce**
Clean install darktable
Import an image with no previous .xmp
Open the image in darkroom
darktable crashes

**Expected behavior**
Open the image in darkroom

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
The last build that works fine is:  
[darktable-4.1.0+236~g78747838c_x86_64.dmg](https://mega.nz/file/OWIGXI5Y#xcO_8v8bPSkMEuhX62j06j56ztSKLPDhFYMlXYoal7o)

The next one is the first that showed the issue:  
[darktable-4.1.0+283~g5cca9d64b_x86_64.dmg](https://mega.nz/file/XPQWHB7I#ecADJh48CM9VDQgqfp6azLRMy9DtUXnLQhuYTCnLaX4)

And the following ones all showed the issue up to the last one Martin build:
 [darktable-4.1.0+385~gf2ebe6b26_x86_64.dmg](https://mega.nz/file/vDgkDB6Q#8QUlYYscPPGa_rVyDUHfP8olN1l6zlVSsLgfUYEe_Rs)

_A bisect is much appreciated and can significantly simplify the developer's job._

I run lldb, see attached file,  and it suggests (actually Martin Straeten review the file and suggested) an issue with white balance (temperature.c).

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable-4.1.0+283 and following builds
* OS                : MacOS Monterey 12.6
* Memory            : 64 GB
* Graphics card     : AMD Radeon Pro 5700 xt 16 GB
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  :  yes
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 
[Mas OSX darktable issue lldb results.txt](https://github.com/darktable-org/darktable/files/9597341/Mas.OSX.darktable.issue.lldb.results.txt)

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? yes , see above
 - Can you reproduce with a RAW or Jpeg or both? Issue with RAW, JPG opens fine (limited testing)
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file : file attached of an image that failed to open in darkroom: DSE_1016.NEF.txt
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? No
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?
[Mas OSX darktable issue lldb results.txt](https://github.com/darktable-org/darktable/files/9597344/Mas.OSX.darktable.issue.lldb.results.txt)
[DSE_1016.NEF.txt](https://github.com/darktable-org/darktable/files/9597490/DSE_1016.NEF.txt)

**Comment by jenshannoschwalm** [comment]
Could you check if its also an issue with opencl switched off?

**Comment by zurdo-10** [comment]
Yes, the issue is present with OpenCL on as well as off

**Comment by MStraeten** [comment]
i think i'm able to reproduce using two different builds (RelWithDebInfo and Release).
Minimum scenario using modern color adaptation:
run RelWithDebInfo version of darktable
delete history stack exit darktable
run again RelWithDebInfo version of darktable --> open image in darkromm --> its fine
run Release version --> open that image in darkroom --> crash
after this crash it also fails when reopening in the RelWithDebInfo version

running darktable -d params indicates it fails before output of `34,513771 [params] defaults reloaded for temperature`
from lldb:
(lldb) frame select
```
frame #1: 0x0000000119764454 libtemperature.so`generate_preset_combo(self=0x000000010b37a800) at temperature.c:684:11 [opt]
   681 	      if(presets_found >= 50) break;
   682
   683 	      const dt_wb_data *wbp = dt_wb_preset(i);
-> 684 	      if(!strcmp(wbp->make, self->dev->image_storage.camera_maker)
   685 	         && !strcmp(wbp->model, self->dev->image_storage.camera_model))
   686 	      {
   687 	        if(!wb_name) // This is first found preset for maker/model. add section.
(lldb) frame variable
(dt_iop_module_t *) self = 0x000000010b37a800
(dt_iop_temperature_gui_data_t *) g = <variable not available>

(const char *) wb_name = 0x0000600000116970 "flash"
(int) presets_found = 7
(int) i = 10050
(const dt_wb_data *) wbp = 0x0000000114a58080
```
now having a reproducible scenario i can try to bisect. But that portion of code was inserted with https://github.com/darktable-org/darktable/pull/12184 and isn't present in the 4.0.x branch. But in my build from Sept. 3rd which was mentioned above.

**Comment by TurboGit** [comment]
You may want to revert those two commits before bisecting, I would say there is great chance that those are the ones we are looking for :)

```
commit 964189b0d2666708f1cb279300aa46d2d7e635a4 (turbogit/po/wb-presets-json, po/wb-presets-json)
Author: Pascal Obry <pascal@obry.net>
Date:   Wed Aug 17 16:38:24 2022 +0200

    wb-presets: Use lower-case for preset names.

commit 7470ae68a8360f57008cbda7dc1fc00ac092272c
Author: Pascal Obry <pascal@obry.net>
Date:   Fri Sep 2 09:45:10 2022 +0200

    Move wb presets into an external JSON file (data/wb_presets.json).
    
    The JSON file is checked against a schema for validity. The only
    module using this is the module temperature which has been migrated
    to this new API.
    
    For #11831.
```

**Comment by TurboGit** [comment]
You may also want to try adding the following line in common/wb_presets.c in line 260:

`          memset((void *)&wb_presets[wb_presets_count], 0, sizeof(dt_wb_data) * 2000);`

The code should then look like this:

```
        if(wb_presets_count ==  wb_presets_size)
        {
          // increment for 2000 presets
          wb_presets_size +=2000;
          wb_presets = realloc(wb_presets, sizeof(dt_wb_data) * wb_presets_size);
          memset((void *)&wb_presets[wb_presets_count], 0, sizeof(dt_wb_data) * 2000);
        }
```

Just wild guessing...

**Comment by MStraeten** [comment]
well guessed ;) no longer reproducible with that line

**Comment by zurdo-10** [comment]
Hi, this is for me spectacular. I described an issue and in less than 12 hours you guys figured out the problem, solved, pushed a commit, and Martin did a new build that I downloaded and checked that is working properly.
Thank you very much to all of you for all the work and time that you guys put into darktable
