### ISSUE TITLE
dt crashes when right-clicking manually drawn perspective lines

### ISSUE THREAD

**Issue by bgodole** [darktable-org/darktable#12529]
**Describe the bug/issue**

I can consistently make darktable crash when using the "crop & rotate" module and the option "manually draw structure lines". The program quits without an error message and any changes made to the image are lost as a result.

I am using Windows 10 and the latest 4.0.1 version of darktable. FYI, in this older computer with an Intel i3-6100 (Skylake) and only the integrated graphics, I have to use dt with "--disable-opencl", otherwise it won't launch at all.

**To Reproduce**

1. Open a random image (mine was a random JPEG)
2. Click on the "rotate & perspective" module and then click on the pen to "manually draw structure lines"
3. Draw a line in the image
4. Right-click at least twice inside one of the 'circles' of that line
5. Draw another line

**Screencast**

https://user-images.githubusercontent.com/15838230/191051930-093f3ef8-785f-44d3-ab20-2486e2be5e62.mp4

* darktable version : 4.0.1
* OS                : Win10 (19044.2006)
* Memory            : 12 GB
* Graphics card     : Intel HD Graphics 530
* OpenCL activated  : no

**Comment by gi-man** [comment]
I switched to windows to reproduced this and I was able once I followed the instructions exactly as described. 

Tested on Win11, darktable 4.1.0+285 and was able to reproduce it.
I then build to current master (darktable 4.1.0+402) and also reproduced it with and without OpenCL

I checked with darktable -d all and I dont have a clue what's going on.

**Comment by gi-man** [comment]
I switch back to fedora 36, x11, 4.1.0~git401.f37405bc and was able to reproduce. It seems like the mouse pointer does not change back to the draw line symbol after the right click.

31.210924 [opencl_profiling] spent  0.0317 seconds totally in command queue (with 0 events missing)
31.211426 [pixelpipe_process] [full] done. used=242MB, limit=239MB, hitrate=0.14
31.211448 [dev_process_image] pixel pipeline processing took 0.306 secs (0.488 CPU)
31.211488 [run_job-] 00 373028573.579303 31.211491 develop process image | queue: 0 | priority: 031.211493 
free(): invalid next size (fast)
Aborted (core dumped)

**Comment by ralfbrown** [comment]
I didn't get an immediate crash with master (4.5.0+138), but was able to reproduce after drawing and removing a bunch of lines.  What I did see numerous times before the eventual crash due to `free` detecting memory corruption was that right-clicking on one of the line-end circles would often remove **two** lines.

**Comment by bgodole** [comment]
Thank you for confirming. This is not the most pressing issue in darktable but it certainly is in the list of them and I hope someone will find the time to fix it.
