### ISSUE TITLE
LUT 3D file selection order / module usability

### ISSUE THREAD

**Issue by asdkant** [darktable-org/darktable#12535]
**Describe the bug/issue**
When using the LUT 3D module, the combo box for selecting the LUT used to be in alphabetical order (showing all the LUTs in the same folder as the current one), but now they are not in alphabetical order

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. have the LUT 3D module set up with some LUTs
2. go to the darkroom for any picture
3. select the LUT 3D module
4. open the combo box for selecting the LUT file

**Expected behavior**
The list should be in alphabetical order, it is not

**Screenshots**
![image](https://user-images.githubusercontent.com/3915542/191275459-81931680-3dc4-4207-abd6-28c4477b1901.png)

**Which commit introduced the error**
I'm not sure when this started, I *think* it was with the jump from v3 to v4

**Platform**

* darktable version : e.g. 4.0.0
* OS                : e.g. Linux 5.19.9-zen1-1-zen
* Linux - Distro    : e.g. Arch Linux
* Desktop           : Plasma 5.25.5
* GTK+              : 3.24.34-1

**Additional context**

There's a greater usability issue regarding how one interacts with this module.

It'd be better if the search (right-click on the combo box + typing) was some kind of fuzzy search instead of a straight up matching the exact beginning of each filename (in the screenshot I'm using the HALDCLUT collection, it's evident why what I'm pointing is an issue).

It's not too bad for *me* right now because I already got to know the different LUTs in the collection I'm using, but it becomes *really* difficult to browse if the order while browsing is not deterministic (I can't really see a pattern in the order right now). If there was a better way to browse the different LUTs I'd welcome it, but I'd be happy with just going back to alphabetical order in the combo box.

**Comment by victoryforce** [comment]
Please upgrade to version 4.0.1 where this issue is resolved.

**Comment by asdkant** [comment]
I love it when when the solution is "we just released a new version that solves your problem" <3

I just built and installed the updated package and it works, happy to see the text is also left-aligned =)

I'll check if there's already a feature request for the fuzzy search, and if not I'll open a separate issue for that.
