### ISSUE TITLE
The color of the temperature color bar in the Color Calibration is upside down.

### ISSUE THREAD

**Issue by arturoisilvia** [darktable-org/darktable#12538]
Darktable 4.0.1
Windows 11

Module: Color Calibration
Illuminant: D(Daylight)

The color temperature bar is upside down: The blue color (cool) should be on the left and the orange or brown color (warm) on the right.

As it is now it confuses me.
(DeepL)

**Comment by MStraeten** [comment]
why do you expect it a different way?

**Comment by HSUfineprint** [comment]
It's a misunderstanding cause by many software. Not sure is that worth to add slider color change function just like "white balance" module. But the "effect emulation" colored slider is more intuitive on operation for some users.

**Comment by MStraeten** [comment]
did you check the manual? https://docs.darktable.org/usermanual/4.0/en/preferences-settings/darkroom/
There you can select if you need a different setting if that’s more intuitive to you

**Comment by HSUfineprint** [comment]
> did you check the manual? https://docs.darktable.org/usermanual/4.0/en/preferences-settings/darkroom/ There you can select if you need a different setting if that’s more intuitive to you

That's what I talking about. Users can switch slider color in white balance module, but not in color calibration module. But I'm not sure is that worth adding this feature to color calibration module.

BTW, you don't need to change the setting in preference (and it will be removed in the future), just left-click the "scene illuminant temp" to cycle layout in white balance module.

**Comment by arturoisilvia** [comment]
@MStraeten 
 I find it strange that if I move the slider to the left to the orange color, the image becomes cold

![Darktable Temperatura Fria](https://user-images.githubusercontent.com/55624244/191688772-8b3017c4-1685-4cdb-bdd0-1612b6cb96f2.jpg)

and if I move it to the right towards the blue color, it becomes warm.


![Darktable Temperatura Calida](https://user-images.githubusercontent.com/55624244/191688994-de9f7e36-97a8-4141-bc65-2f1a7eb7c865.jpg)


I propose to change the color of the temperature color bar as Captue One 21 Express for Fujifilm does:

![Capture One 21 Express Fujifilm Temperatura Fria](https://user-images.githubusercontent.com/55624244/191689156-02950024-89e3-4044-8280-765a46244236.JPG)
.

![Capture One 21 Express Fujifilm Temperatura Calida](https://user-images.githubusercontent.com/55624244/191689222-77d6a733-0f01-4cf1-b163-9ae3f56b0088.JPG)

But it is only a suggestion...

**Comment by MStraeten** [comment]
what about being consistent to the hue/chroma sliders in custom mode? It’s about illumination - and 7000k illumination isn’t orange at all …

**Comment by elstoc** [comment]
Indeed, the intention is to represent the colour of the illuminant. Doing as this request suggests would mean that the colour patch above the slider would be inconsistent with the colour displayed on the slider (and custom mode, as you say). I agree we should not change this.

**Comment by arturoisilvia** [comment]
I'm going to try this one last time to see if you see the problem, and if not, I'll close the topic. 
I have this image that I want to give a warmer tone:
![Normal](https://user-images.githubusercontent.com/55624244/191909159-e0b275fa-a775-4f89-a331-aa3b12b0821a.JPG)

I have this temperature color bar, which way should I move the slider: towards A or towards B?
![Barra color temperatura Darktable](https://user-images.githubusercontent.com/55624244/191909423-f8a12fac-651f-481e-8363-790a74035b7e.JPG)

I guess towards A

This is the result. And it is not what I expected:
![Al calido](https://user-images.githubusercontent.com/55624244/191909995-4e95c801-2ca0-4131-8f97-9982c9a48614.JPG)

**Comment by TurboGit** [comment]
Yes it is ok as already stated. There is multiple way to display this slider. The default one being "effect emulation". If you want the other way edit your `~/.config/darktable/darktablerc` and set:

`plugins/darkroom/temperature/colored_sliders=illuminant color`

You can also remove the coloring using "no color".

At least this works for the "white balance" module, not sure for the "color calibration".

**Comment by arturoisilvia** [comment]
Ok.
Thank you all. We leave it as is.

**Comment by elstoc** [comment]
>  There is multiple way to display this slider

@TurboGit as stated above, this preference only affects the white balance module. I think that's still fine though, since color calibration has a clear intention to use and display only the illuminant temp

**Comment by TurboGit** [comment]
@elstoc : Sorry I missed this... I didn't read everything :)

**Comment by MStraeten** [comment]
> I'm going to try this one last time to see if you see the problem, and if not, I'll close the topic. I have this image that I want to give a warmer tone:
> I have this temperature color bar, which way should I move the slider: towards A or towards B? 
> I guess towards A
> This is the result. And it is not what I expected:

You used the tool the way you think it should work but not the way it works ;)

The meaning of the slider isn't "i want warm" but "thats illuminated with warm light" - thats consistent with all other ways to set the illumination in that module

If you want to use darktable like an arbitrary other tool the you should stay with legacy chromatic adaptation so it's similar to them. New stuff needs learning new tools ...

**Comment by arturoisilvia** [comment]
> The meaning of the slider isn't "i want warm" but "thats illuminated with warm light"

Ah!, I'm starting to understand. Given a point on the slider you have to understand it as: I'm going to remove this quantity of tone.
I was understanding it backwards because that's not what I'm used to.

Thank you very much again.
