### ISSUE TITLE
diffuse & sharpen: luminance masking threshold creates artifacts

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#12537]
DT version: current master, as well as 4.0.1
OS: both Ubuntu 22.04 and Windows 11
with both OpenCL on or off

To reproduce
- start a fresh edit
- activate D&S module
- choose a preset, for example "add local contrast"
- slowly increase "luminance masking threshold"

See the artifacts

![image](https://user-images.githubusercontent.com/43290988/191351333-6df74480-3a34-40ab-88dc-cdef7071973a.png)

**Comment by MStraeten** [comment]
from the manual: https://docs.darktable.org/usermanual/4.0/en/module-reference/processing-modules/diffuse/#diffusion-spatiality
_This control is useful if you want to in-paint highlights.
...
Note that gaussian noise will be added in these regions to simulate particles and initialize the in-painting._
--> works as designed
