### ISSUE TITLE
Darktable can't run.

### ISSUE THREAD

**Issue by Avtroman** [darktable-org/darktable#12531]
Darktable 4.x can't run
Running, quick show cmd, and ended

* darktable version : 4.0.1
* OS                : Windows 10
* Memory            :  12 Gb
* Graphics card     :  nVidia    GeForce 610M, Intel HD Graphics 4000
* Graphics driver   :  
* OpenCL installed  :  not installed
* OpenCL activated  :  no
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by ptilopteri** [comment]
No one can solve your problem w/o you providing the requested information.
The request for information is not there just for window dressing.

**Comment by Avtroman** [comment]
> No one can solve your problem w/o you providing the requested information. The request for information is not there just for window dressing.

added

**Comment by gi-man** [comment]
OpenCL is likely installed in your system. Try starting darttable from cmd using this command: darktable --disable-opencl

**Comment by Avtroman** [comment]
> OpenCL is likely installed in your system. Try starting darttable from cmd using this command: darktable --disable-opencl

I make another. nVidia driver install nwOpenCL.dll in system32, I copy this dll to darktable\bin and RENAME to OpenCL.dll

All run OK

**Comment by gi-man** [comment]
I dont understand what you did, but it is running, can you close the issue?

**Comment by Avtroman** [comment]
> I dont understand what you did, but it is running, can you close the issue?

After installing nVidia driver, exists nvOpenCL.dll (from nVidia) in system32 and syswow64
Need to get nvOpenCL.dll from System32, rename it to OpenCL.dll, and copy to dartable\bin catalog
After this, darktable work OK
