### ISSUE TITLE
dt_action_process can't reliably or repeatedly distinguish between multiple module instances

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#12540]
**Describe the bug/issue**
When you create multiple instances of a module you can't reliably select the module instance by using the instance number.

**To Reproduce**

1. unzip the attached file and put the shortcutsrc file in ~/.config/darktable and the lua script in the lua scripts folder.
2. Import the Starting Point dtstyle
3. Open an image in darkroom mode
4. press alt+t which will turn on the multiple diffuse and sharpen modules pausing for 1 second between each.  Notice the the top instance of D&S is instance 0, the bottom instance is 1, the next up is 2, and the next up is 3.
5. Turn all the instances of D&S off. 
6. Press alt+f. This should turn on instances 0 and 3 of D&S.  What happens is the bottom module (1 in the test above) turns on and 3 turns on correctly.

**Expected behavior**
The same modules should respond to the same instance number between runs

**Suggestion**
Instead of  using instance to pick the module use the multi_name.  When the first instance of a module is created, it has an empty name.  The second instance gets the name "2".  The third "3" and so on.  The user can change them to what they like, but they are tied to that instance of the module and don't get randomly rearranged by the history processing.  The instance could just be a character field.  When an empty string or null is passed select the instance without a name otherwise select the instance that matches the name.

@dterrahe would this work?

**Comment by wpferguson** [comment]
Oops, forgot to attach the file

[multi_instance.zip](https://github.com/darktable-org/darktable/files/9621861/multi_instance.zip)

**Comment by dterrahe** [comment]
Instance 0 is the "preferred" instance and is intended to not be fixed, but depend on the current status of the modules and the settings in "shortcuts with multiple instances" on the "miscellaneous" tab in preferences. If you want a deterministic order, likely in scripting, you should only use 1,2,3,... or -1, -2, -3,...

**Comment by wpferguson** [comment]
@dterrahe that works, thanks

**Comment by wpferguson** [comment]
1,2,3,4 and -1,-2,-3,-4 work as long as you access them all in order.  But, when I try to turn on 4 then 3, 3 and 1 turn on.  If Itell it 4, 3, and 1, I get 3, 2, and 1.

**Comment by wpferguson** [comment]
Here's the updated script
[updated_script.zip](https://github.com/darktable-org/darktable/files/9621999/updated_script.zip)

**Comment by dterrahe** [comment]
Which routine in the updated script do you want me to test?

Your `enable(mod, instance)` _toggles_ the modules. Maybe that leads to confusion?

**Comment by wpferguson** [comment]
Added some debugging statements to _process_action and discovered what's going on.  When it looks for instance 4 it finds it, but instead of performing the action is starts searching for instance 1 and performs the action on it.

[instance.debug.txt](https://github.com/darktable-org/darktable/files/9626044/instance.debug.txt)

**Comment by wpferguson** [comment]
Apply the `Starting Point` style.  All the modules are off.  If you use my shortcutsrc file, then atl+f should turn on the `AA sharpen` and `local contrast` D&S modules.  Otherwise, assign a shortcut to `enable final modules 1`

**Comment by dterrahe** [comment]
Your debug log looks fine to me. Remember 1 is the bottom one (in the module list on the right; the first instance processed in the pipe), 4 is the top/last one (if there are 4), -1 is top one, -4 is the bottom one (if there are 4).

**Comment by wpferguson** [comment]
Except that I requested instance 4 be turned on and instance 1 got turned on.  I annotated the debug list...

[instance.debug.txt](https://github.com/darktable-org/darktable/files/9626300/instance.debug.txt)

**Comment by wpferguson** [comment]
Debugged even farther by adding a message to the script when I returned from the call.  After that I found the problem and it was in the script.

Bad news: I wasted some of your time.

Good news: I have a better understanding of how multiple instances work and how to manipulate them.  Thanks @dterrahe

**Comment by dterrahe** [comment]
A useful approach, when in doubt about some strange result, might be to test things quickly with keyboard shortcuts, which should work exactly the same except when using "set" for sliders or entries. Of course you can't test the return value that way.

**Comment by wpferguson** [comment]
There were a couple lessons learned in this one.  I was modifying the script and forgot to take out a for loop at the bottom that enabled the D&S modules.  In this case the toggling bit me, so now enable is set to `on` and disableis set to `off` instead of relying on the toggle behavior.
