### ISSUE TITLE
Corrupted RAW files cause DT to crash

### ISSUE THREAD

**Issue by afeldwinn** [darktable-org/darktable#12547]
<img width="360" alt="Screenshot 2022-09-24 104213" src="https://user-images.githubusercontent.com/70287809/192111546-a1d038d2-5a5d-4520-af9a-229e4e5d209e.png">

When there is a corrupted RAW file in a folder you open in darktable, it causes the program to crash.  This is true with DNGs as well.  I only discovered this after converting all my files to DNGs and the preview windows showed the corrupted file differently (example in screenshot - RAW on the left, DNG on the right).  Once I was able to locate and delete all the corrupted RAW or DNG files, darktable no longer crashed.

I am happy to send along the files if you would like to look at them.  But I can't upload then here as neither RAW nor DNG are allowed, and they are too big,

**Comment by ptilopteri** [comment]
does little good unless you take the time to provide the information
requested in the text you deleted.

**Comment by afeldwinn** [comment]
I didn't delete anything.  I'm not sure what you are talking about.  What information do you need?

**Comment by ptilopteri** [comment]
revisit:
  https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=

and you can see

**Comment by jenshannoschwalm** [comment]
If your dng files have plain wrong header data dt will sometimes crash. You should likely modify the way you create those DNGs.

Have you checked if other raw developers behave safe here?

First step would be to provide exif data via exiv2...

**Comment by jenshannoschwalm** [comment]
So your raw file is crippled Already.
Chances are pretty bad to detect all errors while decoding. Please provide the raw file only, well see what can be done

**Comment by afeldwinn** [comment]
Yes, that is correct, but in looking at the preview in Windows Explorer there was no way to know that.  Only after the conversion to the DNG was I able to see that something was wrong with the file.  That it was clues me in to deleting the bad RAW file and trying DT again.

**Comment by jenshannoschwalm** [comment]
Probably the embedded jpeg is OK so you saw it in the explorer.

What camera?

You can share the raw after zipping so it has a different extension btw. Some problems can be fixed 😊

**Comment by afeldwinn** [comment]
Canon 80D.  Same issue in Windows 10 and 11.  I tried zipping the RAW file but it was too large and got rejected.  What is your file size limit?

**Comment by jenshannoschwalm** [comment]
Or upload to somewhere safe and prove a link?

**Comment by afeldwinn** [comment]
Here you go: https://drive.google.com/file/d/1nVflQqteombt1a4Z_pGAYlbKmGFyYO6G/view?usp=sharing

**Comment by kmilos** [comment]
Possibly similar to https://github.com/darktable-org/darktable/issues/12428?
