### ISSUE TITLE
darktable 4.0.1 crash Access Violation in module libjpeg-8.dll

### ISSUE THREAD

**Issue by BePalm2022** [darktable-org/darktable#12541]
only happen after updating darktable from 3.x to 4.0 now also to 4.0.1 it crashes when i select another date collection of existing pictures
It start loading the pictures of any year, then after few pictures i crashes with the report below. 
always get 2 messages and always this module libjpeg-8.dll

darktable.exe caused an Access Violation at location 000007FCECF43749 in module libjpeg-8.dll Reading from location 000000838C177000

anything I can try to resolve?

from 4.0
[darktable_bt_3GZLS1.txt](https://github.com/darktable-org/darktable/files/9630432/darktable_bt_3GZLS1.txt)

from 4.0.1
[darktable_bt_O8DXS1.txt](https://github.com/darktable-org/darktable/files/9630433/darktable_bt_O8DXS1.txt)
[darktable_bt_PQVUS1.txt](https://github.com/darktable-org/darktable/files/9630434/darktable_bt_PQVUS1.txt)

**Comment by ptilopteri** [comment]
first step would be to provide the requested information as best you can.

**Comment by kmilos** [comment]
Possibly similar to https://github.com/darktable-org/darktable/issues/12438?

**Comment by BePalm2022** [comment]
using darktabel before update to 4.0 without issue
pictures on NAS
but as u see in log file on my old PC still running Win8/64bit. 
then after update darktable is crashing after a while when choosing another existing collection (capture date sorting)  it start loading the pictures this happen in lighttable. happen only when i choose different year
no issue to change in between the colletion from month to month, but once select another year it crash

**Comment by BePalm2022** [comment]
did comment in the other thread

**Comment by BePalm2022** [comment]
deleted corrupt picture files
