### ISSUE TITLE
Darktable locks out access to images stored on external drive

### ISSUE THREAD

**Issue by Nehemiah2** [darktable-org/darktable#12556]
I am new to DT and have imported a number of images which are stored on an external USB drive. While using tethered capture, the image that was processed in darkroom disappeared when lighttable was clicked. Also, all of the images on the external drive were not accessible in DT. They are still in the folders on the external drive. This problem occurred once before today, but I was able to add images to the DT collection the first time. 

My operating system is MAC Monterey 12.5.1 & DT 4.0.0

I would greatly appreciate knowing how to resolve the challenge as I love DT and have many more vintage photographs to digitize.

Thanks, Jim

**Did you buy darktable from an application store ? no

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? no
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nehemiah2** [comment]
Was able to restore images in DT since not all folders were showing under collections > folders, but the fact that the problem occurred suggests a bug may still be involved. Jim

**Comment by gi-man** [comment]
Your issue is not clear to me. You mentioned an external USB with images but then discussed 'While using tethered capture'. Tethering is intended for connecting your camera to the computer to capture the images as you take them. 

First, I think you should install the 4.0.1 version since it fixed some bugs. Second, can you describe the steps to reproduce the issue?  Try to provide details so someone that has a mac can do your steps to see if they get the same problem.

**Comment by Nehemiah2** [comment]
Thanks for the reply. To elaborate on the issue, a Nikon D80 was being used in the tethering mode to digitize old photos & letters. The file structure on the external drive is one parent folder with sub folders under it. The following procedure for scanning has worked more than a few times: capture an image using the tethering mode > rotate and crop as needed > click lighttable to clear the centering screen before capturing the next image > apply tags > export to the external drive. When clicking lightable the image disappeared and was no longer visible in lightable or any screen. In the lightable collections screen under folder, the nested folders containing photos were visible but no images were available in any folder or tag when clicked. Also, folders other than Photos under the primary parent folder were not visible at this point. Using Import > add to library finally resulted in restoring all images to DT. I am unsure exactly how this happened, but clicking one folder managed to restore all folders.
I will download the latest DT version, but have one additional comment. When using the tethering mode, being able to control the focus within DT was not functioning. Not sure it this is a function of an older camera, but it would be handy to be able to fine-tune the focus by using an enlarged view within DT. Also, periodically DT closes unexpectedly which is not particularly problematic, but slightly annoying.
Thanks to all of the devs and other contributors for the ongoing improvements. DT is great! Jim

**Comment by dterrahe** [comment]
@Nehemiah2 Can this issue still be reliably reproduced or was it a one of? There's not much (positive) value in leaving issues open that developers have no hope of fixing, so please consider closing this one.

Your issue with focusing in tethering mode is unlikely to be picked up here, so if you haven't got that to work yet (and haven't found any other, possibly closed, issues that give a reason why it shouldn't/won't work; #3899 suggests that some later models do) and you know there are other tethering tools that do support focusing with this model, you could open a separate issue for this.

**Comment by Nehemiah2** [comment]
Thanks, I will close the issue even though DT does periodically close unexpectedly and exported photos have to be again added to the library. The problem happens randomly without warning & is not due to any cause that can be reliably repeated.
