### ISSUE TITLE
lighttable: add crop and rotate functionality

### ISSUE THREAD

**Issue by ydyote** [darktable-org/darktable#12550]
**Is your feature request related to a problem? Please describe.**
It would be nice when using lighttable in the ctrl+alt+w mode to crop and also rotate images, this is really helpful when a lot of images have to be edited quick

**Describe the solution you'd like**
most likely just some button to activate the crop module or some lightweight version of it and similar for the rotate module

I understand this is probably too far out there because I doubt there is an easy way to make this work, either way it seems like a good idea for event photography and similar bulk editing / quick bulk editing

**Alternatives**
just go one by one within darktable and manually do it with the modules - quickest way would be to have crop and rotate somewhere accessible or bound to some keys and use space for going to the next image

**Comment by TurboGit** [comment]
This is not something that will be done. As @Nilvus said lighttable is not for that.
