### ISSUE TITLE
Purge non-existing images in the UI

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#12554]
**Is your feature request related to a problem? Please describe.**

Related: https://github.com/darktable-org/darktable/issues/12408

Accomplish this script in the UI, https://docs.darktable.org/usermanual/development/en/special-topics/program-invocation/purge_non_existing_images_sh/

**Describe the solution you'd like**
Purge non-existing images in the UI

- [ ] maybe port to python3 (supports sqlite3 natively)

**Comment by ptilopteri** [comment]
as you provide none of the requested information, I assume you are on windows and 
do not know about google search.  try: 
  https://discuss.pixls.us/t/script-for-purging-orphaned-thumbnails-using-in-windows/8274
found from:
  https://www.google.com/search?sxsrf=ALiCzsZCNGt1_YhgwL4-FcBPUoQ5H9GFDw:1664225858402&q=purge_non_existing_images.sh+for+%22windows%22&sa=X&ved=2ahUKEwinr_a4rLP6AhWQpIkEHfJjDHwQ5t4CegQIEBAB&biw=1208&bih=896&dpr=0.91

if this provides an answer to your question, pleas consider closing this issue.

**Comment by naisanzaa** [comment]
> as you provide none of the requested information

The feature request template didn't state what specifics

However, it was pretty specific.  

"Have this capability in the UI"


> do not know about google search

Don't be rude

**Comment by Nilvus** [comment]
@ptilopteri: this one is for me completely correct. It's a feature request to allow launching script from the UI, with a simple button and not by launching manually the script outside darktable. So for such feature request, OS or many other infos are not needed. We all know that purge of images is not possible from darktable app.
