### ISSUE TITLE
Canon R10 not recognized in lens correction module (DT 4.0.1) (windows10)

### ISSUE THREAD

**Issue by CptPotassium** [darktable-org/darktable#12568]
(Apologies in advance if this is a known/being worked on issue, I did some scouting but I couldn't find a clear answer)
I just got a brand new canon R10, unfortunately the lens correction module is not detecting it. I was previously running DT 4.0.0, and updated it to be able to use it with the new camera, I've read that the latest version supports it, so that's why I suspect it might be an issue with my system(?
- I have tried a variety of lenses
- I have tried using both RAW and cRAW formats.

I am willing to provide any files or info you might need, given enough patience since I'm not too tech savvy.

![darktable_9TulBrVPfT](https://user-images.githubusercontent.com/114697484/193132042-c29d04a8-755d-4e82-9396-337dbb6169c3.png)

Thank you to all the devs working on this project :)

**Comment by kmilos** [comment]
This is an issue for lensfun, which dt uses for lens corrections: https://github.com/lensfun/lensfun

**Comment by Nilvus** [comment]
darktable support is about reading raw and providing correct white balance and/or noise reduction profiles, not lenses. Lens correction si provided by an external library: lensfun. So not a darktable issue as it depends on lensfun: https://github.com/lensfun/lensfun

You could help by providing specified images to add lens support here: https://lensfun.github.io/calibration/

**Comment by CptPotassium** [comment]
In case anyone walks into this issue, it was solved at lensfun [in this thread]( https://github.com/lensfun/lensfun/issues/1904)
