### ISSUE TITLE
Darktable exceeds screen width when 200% scaling is enabled

### ISSUE THREAD

**Issue by realpixelcode** [darktable-org/darktable#12562]
I've enabled 200% scaling on my Ubuntu laptop, and after installing Darktable, the program exceeded the screen's width (it's 2560x1600px), rendering it useless for me as I don't want to change the scaling just for that one use case.

**Comment by MStraeten** [comment]
dt is designed with fullHD screen in mind. it’s reported it can be also used at 1366x768.
So 200% scaling won’t fit to your screen. You might try to play around with preferences -> GUI controls and text DPI.

**Comment by parafin** [comment]
Most likely there is a way to change scaling when starting a specific app, e.g. using environment variable GDK_SCALE or smth like that.
