### ISSUE TITLE
Add direction for map and image information 

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#12564]
With Canon GP-E2 and some camera models it is possible to record direction. For example a map with GPS direction here https://www.flickr.com/photos/bent-tranberg/7528169226

The exif tag GPSImgDirection is used for this. Below elevation would be a good place to have it.
![Skärmbild från 2022-09-29 11-08-05](https://user-images.githubusercontent.com/34200649/192990776-c1d51016-f1c2-49bf-b882-73031d0afead.png)

Because this feature is not common in cameras, it would be best to have it unchecked in the settings 
![Skärmbild från 2022-09-29 11-09-31](https://user-images.githubusercontent.com/34200649/192991185-8d3be92a-00e2-4d6d-ab43-6b273a98a154.png)
CC0 sample raw files https://drive.google.com/drive/folders/1jE_oZ6DYCYgK7vTteMxurhWp2uTo3rgq?usp=sharing

**Comment by douzzer** [comment]
@PeterWem this would be a nice tweak.  I reviewed the source code last night to estimate what it would involve.  It's certainly feasible, but it's nontrivial.  The biggest obstacle I saw was the need to add a column in the images table (sqlite).  I'm not a DT developer, but I'm sure the need to add columns has arisen many times over the years, so there must be an SOP around that.

I hope we can get some thoughts from a DT developer familiar with the process.
