### ISSUE TITLE
Issue with blue color channel since 4.0

### ISSUE THREAD

**Issue by mega-stoffel** [darktable-org/darktable#12575]
**Describe the bug/issue**
Dear Developers!
I'm using darktable for quite some time now. Since the update to 4.0.0 my picture from my Canon EOS-RP in RAW (cr3) look pretty strange in darktable. To me it looks like the red and green color channels are ok, but the blue channel might be handled a bit strange. If there is blue light, it turns to pitchblack instead of showing a bright blue light. It's hard to describe, so I attached a screenshot.
On the left there's the image from darktable, on the right it's the same one in IrfanView - and it looks pretty much the same as in IrfanView in my camera and in "real life" also.
![grafik](https://user-images.githubusercontent.com/25298441/193455469-a37a1262-b472-434a-90c3-6696676b68e3.png)

**To Reproduce**
It happens to all my pictures from my Canon camera. I don't know, if it's happening with other cameras, as well, since I don't have any available. Just by importing the pictures to my camera roll they're that "wrong".
It's the same behavior on windows and ubuntu.

I can bring (most of) the blue light back, if I turn the color temperature of the picture to a very high level or even the max of 25000. But that brings other disadvantages, unfortunately.

If I can support you somehow to find a solution to this bug, please let me know.

**Expected behavior**
I would like to see the pictures with the blue light as blue light - and not with these huge black areas.

**Which commit introduced the error**
Sorry, I can't help with this question. It must have been one for the 4.0 release, since it was working good in the previous 3.8.x version.

**Platform**

* darktable version : 4.0.0 (and also 4.0.1)
* OS                : Ubuntu 22.04 / Windows 10 Pro 21H2
* Linux - Distro    : e.g. Ubuntu 22.04
* Memory            :  Win: 8GB, Linux 16GB
* Graphics card     :  Win - no, Linux NVidia 1030

**Additional context**

 - Can you reproduce with another darktable version(s)? Yes, with 4.0.0 and 4.0.1
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**, haven't tried JPG, since I'm shooting in RAW.
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? No

**Did you buy darktable from an application store ?**

No, I'm using it with a direct download from your website for Windows and followed the installation instructions on your website for my ubuntu environment.

**Comment by gi-man** [comment]
I think we will need to see a raw + your xmp to see what workflow/modules you are using (eg. Reference WB?). If you want, you can use one of the pixls.us play raw images to see the workflow of other users.

**Comment by jenshannoschwalm** [comment]
You you please first check if that is related to filmic-> preserve chrominance setting? try setting it to no.

**Comment by mega-stoffel** [comment]
Hej @jenshannoschwalm!
Thanks a lot for this hint. 👍 When I switch off the Filmic RGB my pictures really look much better. I guess I need to learn, what this setting is and how I could make use of it in the future. But until then, I'll just switch it off. :-)
