### ISSUE TITLE
"Unicode Encoding Conflict" written in folder name on Copy & Import

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#12571]
**Did you buy darktable from an application store ?** No

**Describe the bug/issue**

When I want to copy & import pictures, darktable creates new folders wrongly and doesn't copy nor import anything.
My path is `$(YEAR)/$(YEAR).$(MONTH).$(DAY) $(JOBCODE)` since a very long time, but darktable creates a folder including ` (Unicode Encoding Conflict)` in the middle.

The terminal shows:
```
...
failed to create session path (null).
[import_session] Failed to get session path.
[import_session] Using filename _DSC0656.NEF.
failed to create session path (null).
[import_session] Failed to get session path.
[import_session] Using filename _DSC0657.NEF.
failed to create session path (null).
[import_session] Failed to get session path.
[import_session] Using filename _DSC0658.NEF.
...
```

It works fine with a new config folder.
Here is my config file, I tried to look at what's wrong but couldn't find anything strange 🤷🏻 
 [darktablerc.txt](https://github.com/darktable-org/darktable/files/9687807/darktablerc.txt) 

**To Reproduce**

1. clic `copy & import`
2. select some pictures
3. put a job name
4. clic import
5. see error.

**Expected behavior**
Darktable should create the folder name correctly. 

**Screenshots**

![Capture d’écran de 2022-09-30 23-02-21](https://user-images.githubusercontent.com/75432524/193357619-5c5a895b-d05c-4cea-9b40-74f96e307788.png)

**Platform**

* darktable version : 4.1.0+426~g3bb5fd2d5
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04.5 LTS
* Memory            :  15.6 GiB
* Graphics card     :  Radeon RX 580 Series
* Graphics driver   :  
* OpenCL installed  : Yes
* OpenCL activated  :  Yes

**Additional context**

 - Can you reproduce with another darktable version(s)? **Yes**
 - Can you reproduce with a RAW or Jpeg or both? **Any**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Comment by gi-man** [comment]
I cannot replicate. When you say it works fine on a new config, is it a local folder? It seems that you are using a Dropbox sync folder. I think this is a known Dropbox problem. It shows in a Google search for Unicode encoding conflict.

**Comment by Jiyone** [comment]
> When you say it works fine on a new config, is it a local folder?

I mean if I rename .config/darktable to something else and run Darktable on a fresh config.

**Comment by gi-man** [comment]
Try using a local folder

**Comment by Jiyone** [comment]
> It seems that you are using a Dropbox sync folder. I think this is a known Dropbox problem. It shows in a Google search for Unicode encoding conflict.

Yes apparently this issue is connected to dropbox, apparently this is because of 2 files  of the same name in the same folder… 👀

**Comment by gi-man** [comment]
Can you confirm it is a dropbox issue ? Can we close this issue?

**Comment by Jiyone** [comment]
I can't confirm because today I can't reproduce 🤔
I rebooted the computer 2 times yesterday and it was still doing the bug, excepted with a fresh darktable config folder 🤷🏻‍♂️.
Let's close it then ...
