### ISSUE TITLE
FR: copy exif metadata in lighttable and/or read/write OpenEXR metadata and/or read exif from xmp

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#12580]
I would like to import a raw image's metadata (capture settings s.a. ISO, aperture, ...) into its OpenEXR version (which has little metadata, almost none of which seems to be supported by darktable).
Copying metadata in the lighttable interface does not copy this information so it remains null everywhere in the OpenEXR image.

This would be useful because OpenEXR seems to be the best format to export images and reimport them without losing any data. Otherwise the data is not available at export time and the lens info needs to be entered manually to perform corrections.

Alternatively darktable could write and/or read those values directly to/from the OpenEXR file. This is currently done by exrstdattr (write shutter speed, ISO, aperture) and exiftool (read) but the data is not read by darktable.

Finally (maybe this should be reported as its own bug), darktable does not import exif data exported to the xmp file (with `exiftool -tagsfromfile imagefile.dng imagefile.xmp`). I've a sample xmp file containing (ignored) exif data.
[DSC03094.exr.denoised.exr.xmp.zip](https://github.com/darktable-org/darktable/files/9701302/DSC03094.exr.denoised.exr.xmp.zip)

**Comment by kmilos** [comment]
OpenEXR export and import already supports both Exif and XMP (might need dt 4.0 though). Check your export settings, as described in the manual.

IMHO, TIFF is probably a better archival format with much better support for metadata - you can export as 32-bit float with no loss, at the expense of storage space of course. If 16-bit float is of interest, please open a new feature request.

**Comment by kmilos** [comment]
Actually, we might have a bug in reading back that Exif data, which I'll fix shorty.

**Comment by TurboGit** [comment]
@kmilos : I really have no idea. This is original code from @hanatos back from 2011 !

After your comment I'll be tempted to say don't set exif_inited if the loader is EXRs, but you probably have not idea at this point what the loader is.

**Comment by kmilos** [comment]
> I'll be tempted to say don't set exif_inited if the loader is EXRs, but you probably have not idea at this point what the loader is

I pushed a simple workaround that clears exif_inited if fetching via exiv2 fails, so it can defers to any loader...

It works, but for import only as I mentioned, refreshing is not possible. I guess it's a limitation one has to live with with some formats (EXR so far, I think exiv2 supports everything else).
