### ISSUE TITLE
copy&import crashes with large folders

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#12581]
**To Reproduce**

1. open darktable with a collection of > 100.000 images
2. Click copy&import
3. select a folder with >500 files
4. wait 10 seconds
5. 'Darktable' is not responding (see screenshot)

**Expected behavior**
- no crash :-)

**Debug output**
`27,982678 [sql] /usr/src/debug/darktable-4.0.0/src/common/metadata.c:776, function dt_metadata_already_imported(): prepare "SELECT COUNT(*) FROM main.meta_data WHERE value=?1"`
(once for every image in the selected folder)

**Screenshots**
![image](https://user-images.githubusercontent.com/5677563/193687931-e72a55f7-10f8-4c62-a1e0-bfde197fbf06.png)

**Which commit introduced the error**
Occurs since 4.0.0

**Platform**
* darktable version : 4.0.0
* OS                : Manjaro Linux
* Memory            :  32 GB
* Graphics card     :  Mesa Intel® HD Graphics 630 (KBL GT2)
* Graphics driver   : video-linux
* OpenCL installed  :  no
* OpenCL activated  :  no
* Desktop           : Gnome 42.2

 - Can you reproduce with another darktable version(s)? **no**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **no**
   - the debug output is the same (one line per image), but it's super-fast with /tmp configdir
   - using my default-config I have > 100.000 images in my collection
 - Do you use lua scripts? yes
   - What lua scripts start automatically? CollectHelper, hugin, rename_images, delete_unused_tags
   - What lua scripts were running when the bug occurred? the same

**Comment by TurboGit** [comment]
> Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **no**
> 
>     * the debug output is the same (one line per image), but it's super-fast with /tmp configdir
> 
>     * using my default-config I have > 100.000 images in my collection

IIUC this means that the speed is relative to the number of already imported images into the database. Right?

Maybe it the process will have terminated but after a long period of time...

**Comment by TurboGit** [comment]
How many entries do you have in meta_data table?

`echo "select count(*) from meta_data" | sqlite3 ~/.config/darktable/library.db`

What is the output?

**Comment by TurboGit** [comment]
The SQL command you quoted is looking at value which has no index... Maybe the issue, hence my question about the number of entries...

**Comment by TurboGit** [comment]
If you can try this it would be helpful (**be sure to backup library.db**):

`echo "create index metadata_index_value on meta_data(value)" | sqlite3 ~/.config/darktable/library.db`

This will create a new index on meta_data value field. Then try importing again. TIA.

**Comment by quovadit** [comment]
> IIUC this means that the speed is relative to the number of already imported images into the database. Right?

yes, I think it's a combination of 'total images in collection' and 'images in selected folder'.

If I select a folder with only 100 or 200 images, it takes some seconds, but there is no error.

With the empty collection even 800 images in a folder are shown immediately.


.

> How many entries do you have in meta_data table?

321875

.

> If you can try this it would be helpful

Creating the index solves the issue, the files are shown instantly without any delay.

**Comment by TurboGit** [comment]
Thanks for testing, I'll add the index for 4.2.
