### ISSUE TITLE
no milliseconds in overlay, export + lua-rename

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#12583]
**Describe the bug/issue**

The new variable $(EXIF.MSEC) is not available in
- thumbnail overlay text +  tooltip
- export
- lua-script 'rename_images'

**To Reproduce**
1. Copy & import
2. use file naming pattern using $(EXIF.MSEC)
3. OK: milliseconds (e.g. .230) are part of the filename 
4. OK: milliseconds (e.g. .230) are shown in 'image information' if preference is set
5. NOK: .000 is shown in thumbnail overlay/tooltip
6. NOK: exported image name contains .000 instead of .230
7. NOK: lua-script 'rename_images' shows message "unable to do variable substitution, exiting..."

**Expected behavior**
- support exif.msec (and all other new variables) where variables can be used

**Screenshots**
![image](https://user-images.githubusercontent.com/5677563/193737473-e82fe03a-0042-43dd-8ab3-612e8baf9dd5.png)

**Which commit introduced the error**
#10844

Platform

    darktable version : 4.0.0
    OS : Manjaro Linux
    Memory : 32 GB
    Graphics card : Mesa Intel® HD Graphics 630 (KBL GT2)
    Graphics driver : video-linux
    OpenCL installed : no
    OpenCL activated : no
    Desktop : Gnome 42.2

**Comment by wpferguson** [comment]
I'll fix the lua part.  I have to expose the new variable to lua, then I'll update the script.

**Comment by quovadit** [comment]
@wpferguson : it would be great if you find time to update the lua-script - thanks in advance!
