### ISSUE TITLE
Focus Stacking

### ISSUE THREAD

**Issue by lonelyfootpad** [darktable-org/darktable#12582]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, just a feature request. I've been doing some macro photography and would like a way to focus stack images without having to leave darktable.

**Describe the solution you'd like**
I'd like a focus stacking solution built into Darktable. In the lighttable view, under selected images there is currently an option for create HDR which I haven't really used before. I'd love to see an option there for focus stacking, that can take the images I select, then align and focus stack those images to a final image. It seems similar to what the HDR one must do but instead of tonemapping it's focus stacking. This would help my workflow by being able to do focus stacking within Darktable and not having to jump out to other applications to do this.

**Additional context**
Focus stacking can be helpful for landscape photography as well as macro photography and even product photography. Some modern mirrorless systems have focus stacking features built in these days but many don't. It would be great to have this functionality in Darktable.

**Comment by Hpbirkeland** [comment]
You can use the LUA script EnfuseAdvanced to focus stack.

**Comment by lonelyfootpad** [comment]
> You can use the LUA script EnfuseAdvanced to focus stack.

I'll have a look at that. I've never looked at the lua scripts as I am using this as more of a non-technical user just looking for a tool to process raw files from my camera. I still think it would be ideal to have this capability natively without having to use lua scripts and that sort of thing. 
Hopefully this script will be able to do what I am looking for in the mean time once I learn how to use it. Thanks.

**Comment by yodatak** [comment]
Anyone interested ?

**Comment by ptilopteri** [comment]
I do some focus stacking, adjust one photo in dt to my liking, then apply to the entire stack and combine them using zerenestacker

**Comment by astronaute-nope** [comment]
Combined with tethered shooting it would be amazing!
