### ISSUE TITLE
initial notation at 2 * does not apply at import

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#12591]
**Introduction**
I see that issue occurs in 4.0.1 as it did in 3.8.1. I do not understand why despite the setting at import, it never applyes.

--------------------------------------------------------------

**Did you buy darktable from an application store ?**
NO instal from official site https://www.darktable.org/install/
**Describe the bug/issue**
I have set in import parameters, initial rating, 2. Afetr import of pictures, this rating is not applyed.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to Import=>parameters=>inital rating
2. Click on =>2
3. import pictures
4. See rating is not applyed
Path of pictures: C:\_Photo-video\photos\__RAW\Prestations\20221005Girardot

**Expected behavior**
the rating is applyed to pictures with 2 *

**Screenshots**
_(if applicable)_
![dt4 0 1-rating](https://user-images.githubusercontent.com/44755276/194054147-72c57bef-769f-45ef-afa5-d67434997b3f.jpg)

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* OS                :Win10 (Windows 10 Version 21H2)
* Linux - Distro    :N/A
* Memory            : 16,0 Go - Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
* Graphics card     : NVIDIA GEFORCE GTX 745
* Graphics driver   : 30.0.15.1295
* OpenCL installed  : y
* OpenCL activated  : y
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version 3.8.1**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)????
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? No
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nilvus** [comment]
Check first if inital rating works by tick checkbox of above setting (ignore EXIF rating). Your issue could just be because there's an EXIF rating on your images (0 is a rating!).

**Comment by andreilabato** [comment]
Issue solved. "inital rating works by tick checkbox of above setting (ignore EXIF rating). Your issue could just be because there's an EXIF rating on your images (0 is a rating!)."
