### ISSUE TITLE
Number ratings "not assigned" in default keyboard shortcuts

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#12596]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Lightroom mode
2. Select image
3. `f` fullscreen
4. `r` reject image works
5. `4` `3` `2` `1` `0` results in `# not assigned` message

**Expected behavior**
Expect rating to be rated 

**Screenshots**
![image](https://user-images.githubusercontent.com/58240560/194445679-0d316bbe-2b10-4d7d-95af-a2d3476b0e61.png)

**Platform**

* darktable version : 3.8.1
* OS                :  Edition	Windows 11 Pro
Version	22H2
Installed on	‎8/‎9/‎2022
OS build	22623.730
Experience	Windows Feature Experience Pack 1000.22636.1000.0

* Hardware
Processor	AMD Ryzen 9 6900HX with Radeon Graphics           3.30 GHz
Installed RAM	16.0 GB (15.3 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by ralfbrown** [comment]
This is a known problem which I believe has been corrected in newer releases.  Some systems distinguish between number pad digits and top-row number keys and it turns out that on those systems, the default assignments are for the number pad digits.

**Comment by pehar1** [comment]
dt 4.1.0+454~g9666e7f58, Ubuntu 22.04
Works as expected with the top-row number keys (not the number pad !), nothing changed in default settings. Fullscreen mode with F11.

**Comment by Nilvus** [comment]
darktable 3.8.1 is an old version now. Good to update to check if an issue is fixed before posting. As it's already fixed, just update darktable. I close this issue.
