### ISSUE TITLE
darktable-generate-cache throws error messages

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#12590]
**Did you buy darktable from an application store ?**
no, self build from master

**Describe the bug/issue**
`darktable-generate-cache` throws an error message `[webp_open] WebPGetInfo failed` for each image for which thumbnails are generated

**Expected behavior**
No error messages

**Which commit introduced the error**
Probably https://github.com/darktable-org/darktable/pull/12560
Not observed with 4.1.0-426-g3bb5fd2d5, observed with 4.1.0-450-ge83f7f7fb

**Platform**
* darktable version : 4.1.0-450-ge83f7f7fb
* OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
* Memory : MemTotal:       65773056 kB
* Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
* Graphics Card : Driver Version                            : 470.141.03
* OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2
* OpenCL activated : yes
* Xorg : Version: 1:7.7+23ubuntu2
* Desktop : LXQt
* GTK+ : 3.24.33
* gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
* CMAKE_BUILD_TYPE : release

 - Can you reproduce with another darktable version(s)? **no**
 - Do you use lua scripts? **no**

**Comment by victoryforce** [comment]
@pehar1 Thank you for noticing, will be fixed shortly. Failed call just means that the webp loader is trying to load an image which is not in webp format (this is how image reading works in dt, we go through the loaders until we find one that successfully reads the file). In this case we simply shouldn't issue an error message. The image loader just needs to finish the attempt.
