### ISSUE TITLE
4.0.1 - Folder filter no longer working as before

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#12603]
**Describe the bug/issue**

**To Reproduce**

1. Reset Collections
2. Select `folder`
3. Search for a folder name
4. Does not work

**Expected behavior**
Same behavior as 3.8.1 

**Screenshots**
![image](https://user-images.githubusercontent.com/58240560/194683921-5ade183e-52d8-4ac7-9300-e31d9d31c584.png)

**Additional**

![image](https://user-images.githubusercontent.com/58240560/194684329-198dc8f6-d18a-430f-b3e8-a38bca8d7ee0.png)

**Platform**

* darktable version : 4.0.1
* OS                :  Edition	Windows 11 Pro
Version	22H2
Installed on	‎8/‎9/‎2022
OS build	22623.730
Experience	Windows Feature Experience Pack 1000.22636.1000.0

* Hardware
Processor	AMD Ryzen 9 6900HX with Radeon Graphics           3.30 GHz
Installed RAM	16.0 GB (15.3 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by pehar1** [comment]
Use `%san diego`, and it works.
From the manual : https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/shared/collections/

> **folder**
>     The folder (**file path**) where the image file is located.

and the **path** does not start with `san diego`.

**Comment by naisanzaa** [comment]
wow.

**Comment by pcanning** [comment]
I'm just curious ... can someone explain the rational for using % as the wildcard character rather than using *, which seems more common?

**Comment by naisanzaa** [comment]
> I'm just curious ... can someone explain the rational for using % as the wildcard character rather than using *, which seems more common?

I think this is the code. 

https://github.com/darktable-org/darktable/blob/3bb5fd2d5ce5440cac3850bb07f5781ab75cecde/src/common/collection.c#L1344-L1374

**Comment by naisanzaa** [comment]
Seems like `%` is a wildcard  in SQL

> % and _ act as wildcard match characters


https://www.sisense.com/blog/sql-symbol-cheatsheet/

I think this is more of a classic example of engineers vs analysts. Engineers can engineer things not for practical use.

**Comment by pehar1** [comment]
@naisanzaa, just for curiosity: why did you rate my answer with "thumbs down"? I tried to give a fast, short and correct answer with an explanation why it works the way it works. What was wrong?
