### ISSUE TITLE
Remove geotag

### ISSUE THREAD

**Issue by IjhUDWzf** [darktable-org/darktable#12609]
**Is your feature request related to a problem? Please describe.**
Using the geotagging feature you can add GPS coordinates to a photo but there is no way (I am aware of) to easily remove them. The reason you may want to do this is that because of mismatch time you may end up geotagging photos for which you don't have GPS information and hence you can't correct the GPS by correcting the time and using the geotagging feature again.

**Describe the solution you'd like**
Add the possibility to delete GPS information from selected photos.

**Comment by ralfbrown** [comment]
In map view, you can drag a photo off the map to the filmstrip to delete its GPS info.
(If you just want to remove GPS from one image in a group at the identical position, you'll need to drag from filmstrip to an unused area of the map first, then drag back to the filmstrip.)

**Comment by IjhUDWzf** [comment]
@ralfbrown Ah! Thank you for the tip, I did not know that. I searched the "geotagging" part of documentation and had forgot about "map". Still, it might be just me, but it is not apparent you can do this and a simple button in the map view could help to make it clear.

**Comment by wpferguson** [comment]
There is also a lua script, `clear_GPS`, that adds a button to the selected images module.  You select the images you want to remove GPS information from, and click the button.

**Comment by phweyland** [comment]
![image](https://user-images.githubusercontent.com/23012047/201499681-d86baecc-7adf-4c2c-85ab-180fd8b805b6.png)
