### ISSUE TITLE
Select multiple gpx files at once

### ISSUE THREAD

**Issue by IjhUDWzf** [darktable-org/darktable#12610]
**Is your feature request related to a problem? Please describe.**
You may have many separate gpx files for a particular collection of photos, but each one has to be loaded separately.

**Describe the solution you'd like**
Allow for selecting multiple files when opening the gpx file.

**Comment by darkelectron** [comment]
This looks similar to: https://github.com/darktable-org/darktable/issues/9673

**Comment by IjhUDWzf** [comment]
@darkelectron Definitely is, I have overlooked the already open issue, thanks for pointing it.
