### ISSUE TITLE
Allow 'custom sort' based on current sorting

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#12612]
**Is your feature request related to a problem? Please describe.**
I would like to sort by 'capture time' first, and then apply a custom sort order based on this order.
But  chosing 'custom sort' in lighttable seems to reset the current sort order to 'filename'. 
So I can't only change the order of one image after sorting by 'capture date', but I have to manually reorder all images.

**Describe the solution you'd like**
Chosing 'custom sort' should not change the current sort order.

**Alternatives**
Always allow dragging of images, and automatically switch to 'custom sort'.

**Comment by engrzani** [comment]
I've created a fix for this issue,

[0001-lighttable-preserve-custom-sort-order.patch](https://github.com/user-attachments/files/24622792/0001-lighttable-preserve-custom-sort-order.patch)

**Comment by wpferguson** [comment]
Could you open it as a pull request please?
