### ISSUE TITLE
Multiple instance everywhere

### ISSUE THREAD

**Issue by IjhUDWzf** [darktable-org/darktable#12613]
**Describe the bug/issue**
I can see the icon for creating new instance of a module for every single module, even those for which it does not make sense and also does not work (like crop).

**To Reproduce**
1. Go to darkroom
2. Look at modules on the right side
3. Go e.g. to crop
4. See icon for multiple instance
5. Try to use it by right click

**Expected behavior**
Only show the icon for relevant modules.

**Which commit introduced the error**
I believe that in Darktable 3.8.x it was fine.

**Platform**
* darktable version : 4.0.0
* OS                : Linux - kernel 5.10.0
* Linux - Distro    : Debian 10

**Comment by ralfbrown** [comment]
Well, there's an entire menu on that icon when you left-click....  While the new/duplicate/delete options are grayed out for single-instance modules like Crop, you can still use the rename and move up/down options (for moving in the pipeline).

So the icon is relevant for **all** modules, but the tooltip should remove the reference to right-clicking for single-instance modules.
