### ISSUE TITLE
URGENT : Nightly regressions

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12639]
Tonight (Oct 15 ~ 7h CET) the nightly tests have returned lot of errors (GNU Linux/Debian):

Total test 94
Errors     23
   - 0004-masks
   - 0005-orientation-minus-90
   - 0006-orientation-plus-90
   - 0007-orientation-180
   - 0008-flip-h
   - 0009-flip-v
   - 0010-flip-hv
   - 0011-gdnd-90
   - 0012-gdnd-45
   - 0013-denoiseprofile-wavelets
   - 0014-filmic-rgb
   - 0015-shadhi-bilateral
   - 0016-lowpass-bilateral
   - 0017-monochrome
   - 0018-perspective-corr
   - 0019-color-mapping
   - 0020-denoise-nlmeans
   - 0021-retouch-wavelets
   - 0024-contrast-equalizer
   - 0026-haze-removal
   - 0027-denoiseprofile-nlmeans
   - 0033-blending-modes-uniform
   - 0034-blending-modes-parametric
  
So one of the merge yesterday has changed something.

I won't merge new PR until this is understood/solved. First I'll try to find the culprit.

**Comment by TurboGit** [comment]
@jenshannoschwalm the first bad commit is:

```
d3b6232c6de8f6d058729a77c563e7ccab5e65d5 is the first bad commit
commit d3b6232c6de8f6d058729a77c563e7ccab5e65d5
Author: hanno@schwalm-bremen.de <hanno@schwalm-bremen.de>
Date:   Wed Oct 12 06:42:37 2022 +0200

    Fix availability and order of reconstruction modes
    
    The construction of the menu simply didn't test for sraws, as the opposed
    mode is the new default it will be implemented for sraws too.
    
    The order of modes was discussed in #12606

 src/iop/highlights.c | 59 ++++++++++++++++++++++++++--------------------------
 1 file changed, 29 insertions(+), 30 deletions(-)
```

**Comment by TurboGit** [comment]
Ok, issue understood, all the listed failing test above does not have an highlights in the XMP listed, so now by default we enable the module with the `inpaint opposed` algorithm.

@jenshannoschwalm : I suppose we want to fix that by ensuring that if the highlights mode is off (not listed) for old edits we don't want to activate it otherwise it will be breaking old edits. Saying it another way, enabling the module by default must be done only for new edits.

**Comment by jenshannoschwalm** [comment]
Right now I am not sure how to do that. A module version bump will not help as if there is no xmp entry there is no version to check. Hmmh...

**Comment by TurboGit** [comment]
Not sure either how to deal with that !

**Comment by TurboGit** [comment]
All regressions are fixed now. Closing. I'll open a new issue for the default highlights algorithm later today.

**Comment by jenshannoschwalm** [comment]
I have that on my mind. Currently working hard on making inpaint opposed and segmentation mode behaving well with ROIs. Running well here so far but some further testing ...
