### ISSUE TITLE
Migrate JPG Ratings correctly from Lightroom

### ISSUE THREAD

**Issue by lfptmsm** [darktable-org/darktable#12648]
Migrating JPG photo collections with star ratings from Lightroom does not work correctly. Most of the photos just get simply 1 Star in Darktable, no matter what was the rating in Lightroom. (after saving metadata into the jpg files in Lightroom Classic)

The metadata situation and handling of files should to be assessed one more time in detail and implemented correctly. Lightroom Classic can also create XMP sidecar files for jpgs, which might be helpful if DT can read them.
This issue is important because a huge number of people is frustrated with the Adobes rip-off strategy charging monthly fees.

**Comment by MStraeten** [comment]
darktable can import from lightroom xmp files - if you want to migrate star ratings from lightroom not part of the exif data you need to go that way

if lightroom star rating overwrites exif data then you need to check the import options you used for the images, see: https://docs.darktable.org/usermanual/4.0/en/lighttable/digital-asset-management/star-color/#star-ratings
and: https://docs.darktable.org/usermanual/4.0/en/module-reference/utility-modules/lighttable/import/#module-parameters
btw:

**Comment by lfptmsm** [comment]
I have further examined this and I see that there is definitely a problem with reliability of importing meta data which should be improved. I wondered if there is an option to re-import metadata and ended up with removing all 25k photos from DT and importing them again (jpgs with exif and raws with sidecars from Ligthroom). As a result there has been clearly (again) a very large number of photos without the correct rating. However, picking a single one (a raw image in that case, with sidecar file), removing it and importing it again ends up with the correct metadata/correct rating in DT.

**Comment by MStraeten** [comment]
You need to be more precise about the source of the metadata darktable should import. If the source is a lightroom xmp, then provide a sample where this exactly doesn't work.
If the metadata is part of the exif data - the provide a sample where this doesn't work - not every exif metadata might be supported by the used libraries.
If those metadata are stored in a further way, then be precise, what exactly should be imported and also provide samples so someone not using lightroom is able to get an idea, how to solve that...

Unfortunately your report doesn't give any hints how to reproduce the issue (if it's really a reliability issue at darktable and not an issue originated in a misunderstanding of the capabilities of darktable)

**Comment by gi-man** [comment]
I think you are trying two scenarios. 1)Import Raw + xmp from lightroom (which i think you are saying it works) and 2) jpg (that has ratings within the jpg). I'm on holidays at the moment so i cant test, but i think it will not read the jpg rating info and will only look at the xmp. Can you export jpg + xmp from lightroom?
