### ISSUE TITLE
Additional variables for substitutions

### ISSUE THREAD

**Issue by HemiBob** [darktable-org/darktable#12641]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I would like to have access to the following as variable substitutions:
XMP	Location
XMP	City
XMP	Country
XMP	State
or
IPTC	City
IPTC	Sub-location
IPTC	Province-State
IPTC	Country-Primary Location Name
This is for use in the watermarks module

**Alternatives**

OR a means to mask the existing GPS coordinates to 3 decimal places in place of 6

**Additional context**

This would be a much more user-friendly solution to the present Lat/Long display as shown here
![2022-10-15_153054](https://user-images.githubusercontent.com/25841598/195992094-d397fa1e-a6e7-45a8-a9ba-d556e021967d.png)
Many thanks, Bob

**Comment by ralfbrown** [comment]
The alternative you mention is already possible, provided your GPS coordinates have a consistent number of decimal places and you want to remove a fixed number of them.  $(LATITUDE:0:-3) will be replaced with all but the last three characters of the latitude value.
