### ISSUE TITLE
Mac integration - tooltips pop up in other program windows

### ISSUE THREAD

**Issue by MStrecke** [darktable-org/darktable#12645]
It seems that Darktable does not noticed if it's no longer the foreground application.

Mac OSX: 12.6
Darktable: 4.0.1+1~ga59eoaf56 downloaded from www.darktable.org

Example: If I click Darktable into the background and run Firefox in the foreground the Darktable tooltips pop up if I bring the cursor over the appropriate locations.

This is most noticable with the thumbnail tooltips as the probability that you hit a "sensitive area" is quite high (see screenshots). But other tooltips do also "shine through".

![popup1](https://user-images.githubusercontent.com/5202211/196005271-bb1a2d79-8444-4ced-9972-89de84157c9e.jpg)
![popup2](https://user-images.githubusercontent.com/5202211/196005276-7c1c5f35-4575-4c41-8f36-20bfff1ad2dc.jpg)

**Comment by parafin** [comment]
There’s nothing we can do on darktable’s side (code) and I’ve seen the same bug with other applications, specifically opera, which, I strongly suspect, isn’t even gtk-based. So IMHO it’s macOS bug, its window manager has a really long history of sucking.
