### ISSUE TITLE
top view: rating filter overlaps the operator

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#12657]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
The rating filter on top of main view is crippled. The stars are overlapping the operator, such like = or >

If I chose language DE, the operator is even totally invisible...

**To Reproduce**
See screenshot "bad example"

**Expected behavior**
See screenshot "good example"

**Screenshots**
bad example:
![Screenshot_20221017_210429](https://user-images.githubusercontent.com/49004103/196265467-a6946c13-3a35-4cea-8711-9bf634b1a572.png)

good example:
![Screenshot_20221017_213222](https://user-images.githubusercontent.com/49004103/196266210-7d0e38de-f437-4712-b060-f05890758cd8.png)

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

Bisect gave me (I did two runs with same result):
```
$ git bisect bad
ec3992861d45555ab3da716574095c04102d4732 is the first bad commit
commit ec3992861d45555ab3da716574095c04102d4732
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Wed Sep 21 14:17:29 2022 -0400

    fix bauhaus natural width and add for sliders

 src/bauhaus/bauhaus.c | 42 ++++++++++++++++++++++++++++++++----------
 1 file changed, 32 insertions(+), 10 deletions(-)
```
@dterrahe  may I ping you here?

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.1.0+377~gec3992861
* OS                : Linux - kernel 5.19.12-gentoo
* Distro            : Gentoo Base System release 2.8
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-520.56.06
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.4
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.34-r1
* gcc               : x86_64-pc-linux-gnu-11.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by dterrahe** [comment]
Thanks for reporting!

I've got a fairly good idea what I forgot to take into account (a special flag was added for _just_ these combo's, so it's not easy to spot that it broke, especially when it is not used by default).
