### ISSUE TITLE
Mask manager : "cleanup unused shapes" doesn't work

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#12656]
**Did you buy darktable from an application store ?** NO

**bug/issue description**

in the **mask manager** module, right clic and select **"cleanup unused shapes"** doesn't remove unused shapes (it does nothing actually).

**To Reproduce**

1. go to darkroom and show the **mask manager** on the right panel.
2. create some masks from a module. You can see they appear in the list of the **mask manager** module.
3. delete the masks from the module by right-clic in the shape. You can see they are still in the list on the right.
4. in the **mask manager** module, right-clic on the list and select "cleanup unused shapes".
5. see that it doesn't work. 

**Expected behavior**

All unused shapes should be removed from the list.

**Platform**

* darktable version : 4.1.0+559~g6ef179448-dirty
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04.05 LTS
* Memory            : 15.6 Gib
* Graphics card     :  Radeon RX 580
* Graphics driver   :  AMDGPU
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              :  
* Desktop           : X11
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **no tested yet**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? NO

**Comment by jenshannoschwalm** [comment]
Did you do a "history compress" before? Some time ago we worked on this - while doing so the masks "loose the history entry owner" and become "owned" by the mask manager. That code is really tricky and we didn't find a proper way.

I looked it up again, i don't see a chance to fix this.

**Comment by Jiyone** [comment]
> Did you do a "history compress" before?

No I didn't. Just doing what I described in "To Reproduce" ...

> I looked it up again, i don't see a chance to fix this.

That's a very bad new.

**Comment by jenshannoschwalm** [comment]
I think i didn't comment good enough. (BTW there is a pending pr that solves the refreshing issue)

The "remove unused shapes" works **after** compressing history. That might be not so obvious but if you go through the history list you might want to have that mask to be used again. Thus it can only be fully removed after compressing history.

I just checked again ...

**Comment by Jiyone** [comment]
uuuuh ok 🤔 
But is it supposed to work like this ?
Because anyway, if you click "remove unused shapes" that means you don't need them anytime 🤷🏻‍♂️ 
If you do a shape and decide it's not good and redraw an other one, the first one will stay in the list until you may choose to remove it because it's unused ...

**Comment by jenshannoschwalm** [comment]
> But is it supposed to work like this ?

At least it always worked like this. And - from reading the code that would add a lot more complexity :-( Maybe a better naming would help here? "remove shapes not in history" ?

**Comment by Jiyone** [comment]
A better naming would help only to understand what it does, but ... really not a solution. It's strange and complicated.
The name should be "Remove unused shapes (after compressing history)".
But to me, this is not the solution, just a crutch. I hope someone will look at it soon and rework/tidy up the mask manager! 😢

**Comment by jenshannoschwalm** [comment]
> But to me, this is not the solution, just a crutch

I see your point, but for me the history list and going back to any point in it while developing is absolutely essential! What is an "unused shape" in this context? For me it would be a total surprise if some history items could not be selected any more or even worse are removed by something else than me (in this case the mask manager).

Yes - there are issues in the mask manager but this is none for me.

Maybe someone else sees this in a different way though ...

**Comment by Jiyone** [comment]
> What is an "unused shape" in this context?

It's a shape that is not used in any module.

**Comment by jenshannoschwalm** [comment]
> Also "Delete this shape" doesn't work.

Yes - that's one of the issues.

> It's a shape that is not used in any module.

For me it is still used if in history, so we disagree here.

**Comment by AlicVB** [comment]
I agree with @jenshannoschwalm here : we can't remove shapes linked to an history item, otherwise it's not a "real" history anymore : 
imagine you have done some work with masks, then for some reason decided to withdraw that work. if you finally want to go back to the history state where you have done the work with masks, you don't want to discover that masks have been trashed...
So we need to keep them in memory until they are not used *anywhere* !

Eventually we can try to *hide" them, thought...

**Comment by Jiyone** [comment]
So creating a mask then immediately deleting it right after is like being used?

why not add an entry to history when deleting / removing a mask from mask manager then ?

**Comment by TurboGit** [comment]
> So creating a mask then immediately deleting it right after is like being used?

It is there to be reused.

**Comment by Jiyone** [comment]
> It is there to be reused.

I understand that, but one can't remove it at this step.

**Comment by jenshannoschwalm** [comment]
Right button click?

**Comment by Jiyone** [comment]
@jenshannoschwalm yes and "delete this shape" does nothing ...

**Comment by darkbasic** [comment]
I was going to report this and I've made a video: https://www.youtube.com/watch?v=OJWqKkcsZEk

I think the main issue is that shapes deletion doesn't work at all.

**Comment by dterrahe** [comment]
> shapes deletion doesn't work at all.

It works _for me_, so somehow your situation must be different from mine. If you describe precisely how you got to the spot where shapes can't be deleted I can see again if I can reproduce.

**Comment by jenshannoschwalm** [comment]
@Jiyone don't know if you are still using dt. Could you recheck on master, from what i see here it should be fixed in 4.4...

**Comment by Jiyone** [comment]
It seems to work now 👍 thank you!
Shapes no longer appear in the Mask manager if they are deleted, by right clicking on the shape and right clicking on the label in the list of the Mask manager and select "Cleanup unused shapes".

Maybe the name "Cleanup unused shapes" could be renamed to "Delete" ?

**Comment by jenshannoschwalm** [comment]
> Maybe the name "Cleanup unused shapes" could be renamed to "Delete" ?

Indeed, or even "should" be renamed :-)
