### ISSUE TITLE
Failed installer Windows 10, ver 4.0.1

### ISSUE THREAD

**Issue by bsidneysmith** [darktable-org/darktable#12658]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

SEARCHED, DIDN'T FIND

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
NO, DOWNLOADED FROM https://www.darktable.org/install/

**Describe the bug/issue**
 INSTALLER FOR 4.0.1 ON WIN64 V10 FAILED. EVENT VIEWER SHOWS APPLICATION ERROR. SCREENSHOT BELOW.

**To Reproduce**
DOWNLOADED INSTALLER. DOUBLE CLICKED ON IT. NOTHING HAPPENED BUT A BRIEF BUSY CURSOR.

**Expected behavior**
EXPECTED INSTALLATION TO BEGIN.

**Screenshots**
_(if applicable)_
![image](https://user-images.githubusercontent.com/116032713/196267625-562137f5-f949-4bb3-9b77-0172f6df512b.png)

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._
I DON'T KNOW HOW TO DO THIS. THE DOWNLOAD WAS ON 22.10.17 AT 15:00 EST

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* 
* OS               
![image](https://user-images.githubusercontent.com/116032713/196267909-2a88f861-f5f8-4e96-9daa-2d1b7aff2d62.png)

**Additional context**
_Please provide any additional information you think may be useful, for example:_

I TURNED OFF WINDOWS APP & BROWSER CONTROL, DIDN'T HELP. I DON'T HAVE OTHER ANTIVIRUS SOFTWARE RUNNING.

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by gi-man** [comment]
The application that failed is not darktable.  I see a couple of Security events. I'm going to assume you have some sort of antivirus/software blocking the install. 

I don't have the ability to flag the issues, but this one should get unclear.

**Comment by poudi7** [comment]
Try opening properties on the installer and select the unlock option at the bottom of the window

**Comment by bsidneysmith** [comment]
That's amazing! Thank you so much!

Sid

********************
B. Sidney Smith

**Comment by Nilvus** [comment]
@bsidneysmith: regarding your last comment, seems your issue is fixed. I so closed it but think about closing it yourself next time. Thanks.

**Comment by bsidneysmith** [comment]
Will do, thanks.

Sid

********************
B. Sidney Smith
