### ISSUE TITLE
Seg fault trying to open RAW file in lighttable; JPG opens fine

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#12667]
Manjaro Ryzen 3900+ 32 gig RAM Nvidia proprietary

- Removed all traces of previous dt (/opt/darktable as well as .config/.cache).
- Fetched dt source from GitHub onto a new folder.
- Changed option(DONT_USE_INTERNAL_LUA "Never fall back to the intree copy of lua" OFF) in DefineOptions.cmake
- Created a new build directory, then cmake/make/make install as usual. No errors.
- Performed darktable-cmstest and darktable-cltest. No errors.
- Removed all old .xmp in Picture folder.
- Started darktable in terminal. No errors.
- Opened darktable. No errors.
- Imported Picture folder (contaning a few .RAF and .JPG). No errors.
- In lighttable, doubleclicked a JPG. No errors.
- Closed darktable. No errors.
- Opened darktable in terminal again.
- In lighttable, doubleclicked a RAF. Text: _Loading xxxx.RAF_. L-o-n-g wait. **Seg fault**.

Same RAF opened just fine yesterday (in darktable version compiled yesterday).

_Darktable version:_
[ver.txt](https://github.com/darktable-org/darktable/files/9808828/ver.txt)

_Terminal output:_
[urk.txt](https://github.com/darktable-org/darktable/files/9809001/urk.txt)

_**--- Addendum ---**_
I repeated all steps above, but this time I did _not_ change anything in DefineOptions.cmake.
Still segfault when I doubleclicked a RAF. 

_Darktable version:_
[ver2.txt](https://github.com/darktable-org/darktable/files/9809935/ver2.txt)

_Terminal output:_
[urk2.txt](https://github.com/darktable-org/darktable/files/9809937/urk2.txt)

**Comment by jenshannoschwalm** [comment]
The crash takes place in the zooming demosaicer, I didn't observe this here.

Probably has been introduced by late roi changes for opposed.

Can you please
1. Try to reproduce after setting als images highlight reconstruction to clip via history copy & paste. Issue should go
2. Could you share the raw file?

**Comment by jenshannoschwalm** [comment]
Thanks for the image, the good point is, it crashes here too so a good chance to fix quickly :-)
