### ISSUE TITLE
"Color Assessment Conditions" and "RAW overexposed indication" in Lighttable

### ISSUE THREAD

**Issue by wapitifass** [darktable-org/darktable#12660]
Hello, just two ideas that I think are useful.

It would be nice to have the two features "Color Assessment Conditions" and "RAW overexposed indication" from darkroom-mode also available in lighttable-mode.

Color Assessment Conditions allows you better then other views to check the composition of an image.

RAW overexposed indication is useful while rating or rejecting images in lighttable-mode

kind regards,

wapitifass

**Comment by luator** [comment]
I've just been looking for this as well.  At least the raw overexposed indicator is already covered here: #2579
Unfortunately, it seems that this is not as trivial as it may seem :(
