### ISSUE TITLE
shortcut for color balance rgb white fulcrum picker

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#12663]
**Is your feature request related to a problem? Please describe.**
For color balance rgb, it is possible to set a shortcut for white fulcrum (slider), but not white fulcrum (toggle) - the auto picker.

(The same is true in filmic rgb - it is possible to set shortcuts for white and black relative (slider), but not white and black relative (toggle). This problem is solved by being able to set a shortcut for auto tune levels, which does the same thing. However, a similar option is not available in shortcuts for color balance rgb).

**Describe the solution you'd like**
Ability to set a shortcut for the white fulcrum auto picker in color balance rgb.

**Additional context**
dt 4.0.1
linux mint 21 cinnamon

**Comment by dterrahe** [comment]
Have you tried [visual shortcut mapping](https://darktable-org.github.io/dtdocs/en/preferences-settings/shortcuts/#visual-shortcut-mapping)?

The color pickers next to sliders are part of the same action, with shortcut element "button". Visual mapping will set that up for you.

**Comment by SoupyGit** [comment]
That worked. Thanks!
