### ISSUE TITLE
Exported JPG different as darkroom view of processed raw

### ISSUE THREAD

**Issue by e-grasshopper** [darktable-org/darktable#12674]
**Introduction**
Exported JPG image is different as processed RAW in the Darktable view.

It looks, like some of processing steps are skipped by the export.
There are not visible effects from two modules:
- haze removal
- highlights reconstruction

The problem can also be related to other moduls like in previous bug:
https://github.com/darktable-org/darktable/issues/11741

**To Reproduce**
1. process RAW image and use
- haze removal
- highlights reconstruction
3. Export with image settings to JPG 97% compression.
4. Compare on the same monitor jpg with darkatble view - see screenshot

**Expected behavior**
Exported JPG must contain all efects from darktable view used in the same way.

**Screenshots**
![darktable_export_diff_view_20221020_03](https://user-images.githubusercontent.com/34043678/197022879-99d00e66-b2e6-4935-a245-e7f89ed50557.jpg)

**Platform**
* darktable version : 4.0.1
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04

**Additional context**
Export blocks me to use darktable as tool in my work.

**Comment by JDWarner** [comment]
I can confirm this issue and believe it has to do with the order of processing in the stack.  In my example case, the exported image matches the Darktable editor view *only when Haze Removal **PRECEDES** the Exposure module in the stack*.  However, this is not the default behavior and the "Compress Stack History" tool actually places them in the opposite order.

When Exposure happens before Haze Removal in the stack, the exported images look wildly different than they do in the editor, often with harshly overexposed areas.

**Comment by JDWarner** [comment]
Here is a very egregious example: everything is sRGB color mapping, you can see there's nothing even close to capped in the histogram and Darktable view but the output is way blown out.  It is actually this far off.
![image](https://user-images.githubusercontent.com/2184487/235336687-92ece93f-d0ab-4a1e-bd45-1cbccab7f7b1.png)

**Comment by JDWarner** [comment]
[aurora-darktable-bug.zip](https://github.com/darktable-org/darktable/files/11360622/aurora-darktable-bug.zip)
Here is a zip file with the original file and the current XMP sidecar which gives me the above result.

**Comment by rail02000** [comment]
I faced the same problem that the haze removal module seems not working when editing RAW.
With the same Reproduce.However, "Haze Removal PRECEDES the Exposure module" didn't works in my environment.

![Screenshot_20230527_224553](https://github.com/darktable-org/darktable/assets/111188018/f0e23a38-cad4-4d59-b5d2-c0f895b1a8b8)
↑haze removal OFF, exported JPEG looks similar to the preview in darktable

![Screenshot_20230527_224614](https://github.com/darktable-org/darktable/assets/111188018/eb301c6c-3da1-420d-9af0-3524f10ab0c1)
↑haze removal ON, no changes

![Screenshot_20230527_224708](https://github.com/darktable-org/darktable/assets/111188018/be9ce993-3378-46db-b2e3-090fd7a704c2)
↑exported JPEG
LEFT : haze removal OFF / RIGHT :  ON

**Platform**
    darktable version : 4.3.0~git2424.e8d03322-10119.1
    OS : Linux
    Linux - Distro : openSUSE Tumbleweed 20230525
    openCL : ON and OFF gets the same result.

**Comment by ralfbrown** [comment]
#15910 should fix this (at the cost of much slower processing).  Haze removal in particular uses a small radius to determine haziness at any point, and *does not scale* the radius with image resolution.  So when processing the reduced-resolution image interactively, you get a larger effective radius, which gives a stronger effect (but also one more prone to halos).

@JDWarner - the order shown in the history stack is **not** the order in which the modules are applied, only the order in which their settings were changed.  Compressing history removes all but the last change for each module.
