### ISSUE TITLE
Error on windows 11 22H2

### ISSUE THREAD

**Issue by cwl47** [darktable-org/darktable#12673]
Good morning,
Please find attached the dump created by darktable.
Windows 11 22H2
Ryzen 5500
Graphic card: nvidia GT730-SL-2GD5-BRK-E
DRAM 32 Gi
Cordialment
Joseph cwl

[darktable_bt_OTOEU1.txt](https://github.com/darktable-org/darktable/files/9831167/darktable_bt_OTOEU1.txt)
[darktable_bt_OTOEU1.txt](https://github.com/darktable-org/darktable/files/9831171/darktable_bt_OTOEU1.txt)

**Comment by gi-man** [comment]
You should use the issue template with the steps you used to reproduce. The info is incomplete to help you.

**Comment by Nilvus** [comment]
Without knowing what caused the crash (crash txt files do not precise that. And yours are just quite empty), nobody can't help you. I close this issue. You could open another but template issue is there for purpose. So please follow @gi-man advice.
