### ISSUE TITLE
Unhandled exception when opening DT 4.0.1 in Windows

### ISSUE THREAD

**Issue by AlessandroFlorio** [darktable-org/darktable#12678]
I downloaded Darktable for Windows from darktable website and it used to run normally, until one day (maybe, but not sure, after a Windows update) it started crashing at startup. First I encountered this issue with Darktable 4.0.0, then I tried installing the latest version, i.e. 4.0.1 but results were the same.
Reading the similar issue #11392 I specify that I do not have any game controller, and also starting Darktable from command line with the `--disable-opencl` option did not solve the issue. It doesn't even seem that any antivirus is blocking Darktable, I am using Avast and the .exe is in the list of the allowed apps.
I am aware that this crash is hard to reproduce, it must be something with my machine, since Darktable used to work, but I would be grateful if you could provide some hints to have my favourite photo editing software working again.

**To Reproduce**
1. Launch darktable.exe
2. The UI shows the message in the screenshot, and after clicking OK the program closes

**Expected behavior**
Programs starts normally

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/5528182/197119192-a43afdbf-7980-4591-a5c9-6cdde89a2318.png)

**Platform**
Windows

* darktable version : 4.0.1
* OS                : Win10

**Additional context**
Log file: [darktable_bt_HZTRT1.txt](https://github.com/darktable-org/darktable/files/9835928/darktable_bt_HZTRT1.txt)

**Comment by gi-man** [comment]
The crash happens immediately after startup? Do you get to move the mouse? 

We might need to execute from the command line to get darktable log file instead of the windows crash.

**Comment by TurboGit** [comment]
Be sure to remove any connected devices and restart dt.

**Comment by AlessandroFlorio** [comment]
@gi-man 
> The crash happens immediately after startup? Do you get to move the mouse?

When the main window shows up, also the popup in my previous screenshot is shown. I cannnot click on the main window, only on the OK button of the popup, and after that the application closes.

> We might need to execute from the command line to get darktable log file instead of the windows crash.

Executing darktable from the console doesn't print any string; if a log file is saved, where can I find it?

@TurboGit 
> Be sure to remove any connected devices and restart dt.

I do not have any connected devices, just a laptop which I restarted several time swith no luck.

**Comment by gi-man** [comment]
The log is in a hidden folder. You have to type the location.

From the darktable FAQ:

I read a lot of information in the manual to turn on some debug settings, but I cannot see any debug information. Where can I find those debug logs?¶
The Windows version of dt by default logs its debug information to the following places:

Windows 10: C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt

I think darktable -d all might be good for your case.

**Comment by AlessandroFlorio** [comment]
My bad, I didn't see it in the FAQ. The following is the log file generated by executing `darktable.exe -d all`:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/9841541/darktable-log.txt)

**Comment by gi-man** [comment]
I see that it loads for about 10secs. It tries to load files from a Dropbox folder and the folder might have a character that does not look to be ok with windows. I'm on the cellphone and i don't recall. I think you should try to start darktable with a memory/temp library database (not using your current library) to isolate the current library paths. I'm not sure what's going on.

**Comment by AlessandroFlorio** [comment]
I removed the whole darktable folder under AppData/Local so there is no database any more, and no call to folders with special characters, but darktable still crashes. Here is my new log with a clean library: [darktable-log.txt](https://github.com/darktable-org/darktable/files/9842290/darktable-log.txt)

**Comment by gi-man** [comment]
My plane is about to take off, so i cant help no more. It now stopped here:

9.353929 [camera_control] loaded 4 port drivers.

Can you check if there was a recent windows update to your webcam drivers?

**Comment by Jiyone** [comment]
I've installed darktable 4.0.1 on a friend's PC windows and there was the same error immediately when the main window opens
I uninstalled darktable 3.8 that was previously installed on that computer before installing 4.0.1
I tried with a fresh config folder but nothing better and I tried to `darktable -d all` but there was no error.

[darktable_bt_693IU1.txt](https://github.com/darktable-org/darktable/files/9843978/darktable_bt_693IU1.txt)

Windows 8.1
Intel Core i7-4500U 1.80Ghz 2.40Ghz
8Go RAM

**Comment by priyanshus1** [comment]
@Jiyone  It seems to me for your log file this is a NetworkAdapter driver issue. Do you have any wireless devices connected to your machine such as wireless mouse/keyboard or headset. Can you try to remove their dongle and restart the darktable again ?

**Comment by gi-man** [comment]
In both of the crash from @Jiyone and @AlessandroFlorio I noticed this in the windows crash report:

00007FF976A7CA87 0000012639FC1978 0000000000000000 0000000000000000  libdarktable.dll!dt_update_cameras_thread+0x147  [C:/msys64/home/bill/src/darktable-4.0.1/src/common/camera_control.c @ 775]

I'm not sure what's going on with the cameras. I need to restart the computer under windows to see if I could recreate, but I think my build does not include the libgphoto2.

**Comment by Jiyone** [comment]
@priyanshus1 I don't remember :/

**Comment by AlessandroFlorio** [comment]
> Can you check if there was a recent windows update to your webcam drivers?

It doesn't seem so.

**Comment by AlessandroFlorio** [comment]
After @Jiyone's comment I tried installing darktable 3.8.1 and this version opens and runs normally.

**Comment by deshudiosh** [comment]
@AlessandroFlorio Today I had the same problem after updating from 4.0.0 to 4.2.0.
Tried 4.0.1 too, was also crashing on startup, 4.0.0 runs fine.

In my case the problem was the translation to my system language.
Running darktable with forced english language **once** fixed the problem for me. Now it launches even with local lang.

Command to use:
`.\darktable.exe --conf ui_last/gui_language=C`
