### ISSUE TITLE
Resizing path-mask by mouse wheel not symmetric in XY

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/darktable#12684]
**Describe the bug/issue**
Resizing a path-mask by mouse wheel is not symmetric in Horizontal/X and Vertical/Y.

**To Reproduce**
1 load any image and select any adjustment
2 create path-mask with one node on each corner of the image
3 right click to finish
3 with the path-mask selected/active scroll the mouse wheel to reduce the mask size (blue arrow)
4 with a large enough size reduction the disparity between Horizontal/X and Vertical/Y should be apparent as in supplied image. (red arrow)

**Expected behavior**
Resize amount of the mask would be equal in both Horizontal/X and Vertical/Y, the same as the resize of feather size (green arrows ). Since the feather size works as expected I assume this is not somehow hardware/config specific?

**Screenshots**
![MouseWheel-MaskResize](https://user-images.githubusercontent.com/105315850/197272086-82e19a9f-1c30-4450-9507-d1854930c6dc.jpg)

**Which commit introduced the error**
Don't know. (just started using dt this year. still need to learn how to build, and bisect)

**Platform**
* darktable version : 4.1 (prebuilt ARM64)
* OS                : OSx 12.6
* Memory            : 64GB
* Graphics card     : M1
* Graphics driver   : M1
* OpenCL installed  : Y
* OpenCL activated  : Y
* Desktop           : OSx
* GTK+              : default 4.1

**Additional context**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Do you use lua scripts? NO

**Comment by ralfbrown** [comment]
I doubt that's a bug.  Unlike the feather zone, the shape itself is scaled equally in all dimensions, which means the longer dimension grows/shrinks more.  You wouldn't want your 2:1 rectangle to become a 4:3 rectangle when you double its size....

**Comment by AlicVB** [comment]
I confirm that this is done like that on purpose. This previous comment for the details.
