### ISSUE TITLE
Add a sharpen option to export module

### ISSUE THREAD

**Issue by MStrecke** [darktable-org/darktable#12693]
When an image is exported (e.g. for a web page) it is scaled down most of the time.

Even if Darktable has sharpened the picture before, scaling down will soften it again.
This requested option should apply a little bit of sharpening to the image with its final dimensions.
(Many other RAW development tools do).

To achieve the pipeline: "scale down - apply sharpening - converting to output file format" I currently have to:
- export the image with the final dimensions to a non-lossy format
- import it again
- sharpen it
- export it again (not changing its dimensions).

Forum users suggested the use of external image processing software on the exported image (imagemagic, GMic) to automate this.
There even is a lua script (RL_out_sharp) calling GMic with its (hopefully) programmable processing pipeline. However it does not run on a Mac.

But DT already knows how to do this.

So the request is for an option in the export module to apply a sharpening after the scaling and before storing the image in disc.

**Comment by TurboGit** [comment]
You could also add a style with sharpening during export. Much easier and pretty close to what this FR is about.

**Comment by jorismak** [comment]
There is a Lua output sharpen plugin . That exports the file and then uses gmic for a bit of rl-sharpening (so after resize ).

**Comment by MStrecke** [comment]
This FR is about sharpening **after** resizing for the reasons mentioned above.

@TurboGit: As I understand it - a style is applied **before** and not **after** resizing. 

@jorismak: I presume you mean the lua script `RL_out_sharp`. That's the one I mentioned in my original post. It does not run on a Mac.  And it seems odd to call an external program for a function DT can perform already.

I can't find a way to make DT sharpen an image **after** resizing except with the described `export - import - sharpen - export` sequence... hence this feature request

**Comment by dterrahe** [comment]
> As I understand it - a style is applied **before** and not **after** resizing.

So is this really a request for an additional "mode" for applying a style during export; "after resizing" (in addition to the current "replace history" and " append history"). Would that be sufficient or can we imagine situations where some parts of the style need to be before and some after the resize? (just advocating for the devil here).

We would usually go for the more generic approach (applying a style, which allows you to choose any module to use for sharpening and adjust its parameters) rather than a one size fits all "sharpen!" tick box that may not do exactly what you want.

**Comment by TurboGit** [comment]
> @TurboGit: As I understand it - a style is applied **before** and not **after** resizing.

Right, I was confused with the high quality resampling option. But indeed the whole pipe (with the style is processed) and if the final picture is bigger than the export size it is then resized.

**Comment by MStrecke** [comment]
An "additional style" to be applied after scaling is something I haven't dared asking for :)
There may be other "effects" that would benefit from it, I don't know...

But scaling a picture down will soften the content (even sharpened edges). It's the most "glaring" example for the need of _post_-processing. And the export module is the only place that does scaling - hence my humble request.

**Comment by mikeysan** [comment]
Hello,

I am using Darktable for the first time and ran into this problem, well, issue. Any plan to work on it?

I tried the suggested method of adding a style that only sharpens on export. The result was not promising. 
1. All previous edits are stripped or
2. Only one edit stack is applied to all photographs.

Of course, this is in addition to the limitation someone else pointed out earlier.

**Comment by TurboGit** [comment]
You need to use the **append** method for the style to not strip all previous edits.

**Comment by mikeysan** [comment]
> You need to use the **append** method for the style to not strip all previous edits.

Could you please explain how this would work during a batch export process? I am almost certain that most photographers don't edit and export one photograph at a time. I could be wrong, of course. 

**Background:**
In my case, and following an earlier suggestion, I was attempting to export several photographs at once. Some of the photographs have one style applied, while others have different styles; these styles are variations on previous ones saved to match different shots.

I'm happy to learn how the append workaround could help me here.
