### ISSUE TITLE
filmic default settings 

### ISSUE THREAD

**Issue by JacoTux** [darktable-org/darktable#12694]
With dt 4.1.0+620 but it seems to have been like that for some time. 
In the look tab the default value for the latitude is 0.01%.
![Capture d’écran_2022-10-22_21-31-50](https://user-images.githubusercontent.com/65790625/197360317-7b9dc481-dc97-41c7-a592-4afc6c9a2b32.png)

**Comment by MStraeten** [comment]
what's exactly the issue?

**Comment by JacoTux** [comment]
Ok for this change although this value of 0.01% does not seem relevant to me but Aurelien must have his reasons.
On the other hand, he raises the Fuji/Nikon exposure to +0.7 EV and that's great

**Comment by Nilvus** [comment]
I don't remember where but Aurélien explains why latitude was no more necessary. And by using those new settings, I find better results on my side. But this depends on personal preferences. @JacoTux: by knowing now the change, is your issue need to remains opened? If yes, why?

**Comment by JacoTux** [comment]
Yes, I took some time to open some undeveloped photos, you have a starting point with less desaturated highlights which is not bad. We are unconsciously resistant to change, following our cognitive biases is a poor method of analysis. There is no reason to leave this problem open anymore
