### ISSUE TITLE
Disable image mouse hover effect in lighttable

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#12706]
**Is your feature request related to a problem? Please describe.**
The image overlays in lighttable have recently been a minor annoyance. In my catalog of thousands of images, being able to quickly see which images have been edited or have been tagged with a certain color would be really nice. Currently, I have mouse over the image in order to see any color tags or see if the image has been edited.

**Describe the solution you'd like**
The ability to disable the mouse hover effect. I would really find it useful if the circled bits could be made persistent (ie present without have to hover the mouse over the image). I don't mind if it's a setting in darktablerc or something outside of the gui.
![Screenshot_20221024_230148dt](https://user-images.githubusercontent.com/10678620/197680440-1c073732-6b2e-45b0-8f57-734e20f66c23.png)

Is there a way to enable this behavior without having to change code?

**Comment by pehar1** [comment]
Select the star icon to change the type of the overlays (above lightable, right hand side) and select _"permanent extended overlays"_.

**Comment by groutr** [comment]
@pehar1 That's amazing. Thank you. I hadn't noticed those icons before.
