### ISSUE TITLE
camera profile missing in linux Ubuntu version 4.0.1

### ISSUE THREAD

**Issue by Yorunomegami** [darktable-org/darktable#12711]
I have Darktable 4.0.1 installed in a windows 10 environment and in a Ubuntu environment and the linux version is missing Canon D2000 profile.

**Comment by Nilvus** [comment]
It's not an issue. This camera is actually not supported by darktable. You can check it on this page: https://www.darktable.org/resources/camera-support/
To add camera support, darktable need RAW samples. Please follow instructions on that page if you want to help adding support: https://raw.pixls.us/. You can also have more infos about helping on camera support here: https://discuss.pixls.us/t/raw-samples-wanted/5420/154?u=lebedevri

Then you can create a camera support request here (think about completing all infos asked on templates).

I so close that issue. We need samples and the camera support request posted here after.

**Comment by Nilvus** [comment]
Just understand something else: if you have support on one OS and not the other, that means 2 things:

- first, you have on Windows partial support (that would soon be removed) because we lack RAW samples
- on Linux, is lenses support that you miss. And so not a darktable version but lensfun database that you need to update. See same issue: #8931

**Comment by victoryforce** [comment]
@Nilvus The mentioned camera is present in the supported models list. Canon has two different cameras with very similar names (Canon EOS 2000D and Canon EOS D2000C), so it's not uncommon for users to call them incorrectly, referring to a different model. But both are supported in darktable, so even if the author of the issue had a different model in mind, support is still there.

@Yorunomegami What do you mean by "camera profile"? Is this a camera noise profile?

**Comment by Yorunomegami** [comment]
I missed the lens correction. Linux is so brand new for me, I still need to get used to do some legwork to have what I need. Thank you all for the support. Updating lensfun solved it.

**Comment by Nilvus** [comment]
@victoryforce: I know that but this camera is not completely supported (no wb presets, no noise profiles). On raw.pixls.us I just forgot to test name in both terms.
