### ISSUE TITLE
Crash when using segmentation based hlr

### ISSUE THREAD

**Issue by apostel338** [darktable-org/darktable#12739]
**Introduction**

Hello.

**Describe the bug/issue**

Crash when using segmentation based hlr.

**To Reproduce**

Open photo with rather large area of blown out highlights. Like this one:
[DSC_2989.NEF](https://discuss.pixls.us/uploads/short-url/oE3AbUGrLOwzmueKbnSgduEFaO6.NEF) (26.2 MB)
Go to hightlight reconstruction
Set to segmentation based
→ mostly instant crash
If it does not immediatly crash, lower the threshold to get it crashing

**Expected behavior**

Not to crash

**Screencast**

https://user-images.githubusercontent.com/96216629/199095599-83395309-ef1e-416e-bfe8-8e7e3534b991.mp4

**Which commit introduced the error**

Windows insider build 565 from Bill was the last one which worked. All nightly builds after that crash.

**Platform**

Windows 11 22H2
AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Kern(e), 12 logische(r) Prozessor(en)
B450 I AORUS PRO WIFI-CF
(RAM)	32,0 GB
AMD Radeon RX 6600
[DxDiag.txt](https://github.com/darktable-org/darktable/files/9904626/DxDiag.txt)

**Additional context**

Tried all recent builds since 565 (the ones available as automated nightly builds), fresh AppData config, fresh photo folder, open CL on/off etc.

There's also some report on pixls: https://discuss.pixls.us/t/segmentation-based-recovery-crashing/33328

Crashlog with -d roi

[darktable-log.txt](https://github.com/darktable-org/darktable/files/9904601/darktable-log.txt)

It also crashes with photos containing smaller areas of hightlights. It just happens faster with larger areas.

**Comment by arturoisilvia** [comment]
It happens to me too when there are slightly large cropped areas and I move the candidating slider.
On windows 11 with Bill’s DT 4.1.0+681~g19825f35c
Crashlog with -d roi
With 2 crashes:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/9904764/darktable-log.txt)

Another image with great light clipping that fails when moving the candidating slider of segmentation based:
[https://discuss.pixls.us/t/dt-4-0-highlight-reconstruction-with-guided-laplacian/31970/11](https://discuss.pixls.us/t/dt-4-0-highlight-reconstruction-with-guided-laplacian/31970/11)

**Comment by jenshannoschwalm** [comment]
Will get into this in a few days. Just to let me know, can anyone on Linux or osx reproduce the issue maybe with a more informative crashlog?

**Comment by gi-man** [comment]
I just complied on my win11 using the OP image and I cant make it crash. I cant make it crash on fedora 36 either. 

I made sure to do a pacman -Syu to get UCRT up to date. I also noticed that we need to add mingw-w64-ucrt-x86_64-libjxl to the windows build instructions and likely CI.

**Comment by apostel338** [comment]
No crash on Tumbleweed with 4.1.0+686 from master so far.

**Comment by gi-man** [comment]
@apostel338 Can you try installing the nightly build? https://github.com/darktable-org/darktable/actions/workflows/nightly.yml

**Comment by apostel338** [comment]
Yes, it's crashing. I also built myself a 4.1.0+686 which is crashing too. I followed the instructions exactly.

Where would this mingw-w64-ucrt-x86_64-libjxl have to be added?

There is a `libjxl` in this step:

`pacman -S --needed mingw-w64-ucrt-x86_64-{exiv2,lcms2,lensfun,dbus-glib,openexr,sqlite3,libxslt,libsoup,libavif,libheif,libjxl,libwebp,libsecret,lua,graphicsmagick,openjpeg2,gtk3,pugixml,libexif,osm-gps-map,libgphoto2,drmingw,gettext,python3,iso-codes,python3-jsonschema,python3-setuptools}`

Do you mean something else? Be warned, I'm a complete clueless noob... But if you could provide a generic package or dare to tell me what to change at building, I would try to test.

**Comment by gi-man** [comment]
Sorry, forget about libjxl. That's not relevant to this conversation. The nightly and CI actually have it. 

I was just building a generic package to share with you. I will send you a link.

**Comment by apostel338** [comment]
Thanks. It's crashing.

**Comment by gi-man** [comment]
I was able to reproduce. I think it is a memory problem. To reproduce (on Windows because I havent switched to Fedora yet), which the resources to Small. Then I turned off the OpenCL (because I have a lot of memory on GPU too). Then adjust Seg Algo per the OP instructions.

-d memory output
[memory] before pixelpipe process
[memory] max address space (vmpeak):      4357040 kB
[memory] cur address space (vmsize):      3486864 kB
[memory] max used memory   (vmhwm ):      1331000 kB
[memory] cur used memory   (vmrss ):      1107344 Kb
[memory] max address space (vmpeak):      4357040 kB
[memory] cur address space (vmsize):      3486864 kB
[memory] max used memory   (vmhwm ):      1331000 kB
[memory] cur used memory   (vmrss ):      1107344 Kb
Magick: caught exception 0xC0000005 "Access violation"...

After being able to reproduced, I built darktable with PR (https://github.com/darktable-org/darktable/pull/12702). Using the same settings (small resources and openCL) I get no crash. 

@apostel338 I will share a build with the PR (aka dirty) to see if it fixes the problem for you.

**Comment by apostel338** [comment]
This seems to be it. No crash so far with various photos and settings.

**Comment by jenshannoschwalm** [comment]
Just a warning, the mentioned pr is not fully correct regarding masks because of a remaining roi issue.

**Comment by jenshannoschwalm** [comment]
#12770 should be a better fix ...

**Comment by apostel338** [comment]
https://github.com/darktable-org/darktable/pull/12770 fixes it for me. Thank you for your work.
