### ISSUE TITLE
max RGB v6 preserve chrominance setting in filmic RGB seems faulty

### ISSUE THREAD

**Issue by herrkami** [darktable-org/darktable#12742]
Below are three images with no preservation v6, max RGB v5, and max RGB v6. As you can see, max RGB preservation in v6 produces blue highlights where lights are obviously far from blue. Since max RGB v6 is set by default, the faulty setting appears on all images after import. Sometimes it stays unnoticed for a while and becomes only visible at later stages of the edit, making previous work obsolete. It can be particularly hard to spot in images of the sky (see the last two images below). At some point it might become obvious but it can stay quite unnoticed for a very long time. The bug is therefore highly annoying, at least for me. Having been not aware of it, I pretty much ruined hours of editing a large set of photos by trying to compensate this faulty clipping by using highlight reconstruction. [Some other users seem to experience the same problem.](https://discuss.pixls.us/t/darktable-4-0-preserve-chrominance-in-module-filmic-rgb/31941).

No preservation:
![no_preservation_v6_red](https://user-images.githubusercontent.com/4584045/199206961-ac3afe44-660c-430d-bb30-591ca25e6e0b.jpg)

max RGB v5:
![maxrgb_v5_red](https://user-images.githubusercontent.com/4584045/199206942-7261cd77-a778-4248-a956-1e1371631413.jpg)

max RGB v6:
![maxrgb_v6_red](https://user-images.githubusercontent.com/4584045/199206953-317e8316-1c25-447f-9b2a-83e022abf05e.jpg)

Egg-colored sunrise at max RGB v6:
![sunset_v6](https://user-images.githubusercontent.com/4584045/199211100-e049d2f3-f2b9-4625-8a04-474aee4d3f36.jpg)

Natural sunrise at max RGB v5:
![sunset_v5](https://user-images.githubusercontent.com/4584045/199211120-5b1d07c7-72dd-475a-acb1-1f899a0bacd0.jpg)

**Comment by todd-prior** [comment]
This has been discussed at length and I believe would not be considered a bug. Its an interaction with the new module and blown highlights. THis is now handled with the newer highlight recovery methods... Basically older filmic methods desaturated and hid this where as v6 does not and so using v6 with  the old default clip highlight mode with filmic v6 and blown highlights will produce this or sometimes salmon colors depending on what gets clipped and what gets amplified by the wb correction.... you just use v5 or you manage it in v6 with the way it works in v6.... altering white relative, using filmic reconstruction and the new inpaint and segmentation methods will usually correct it nicely... It is for sure weird until you get used to it....

**Comment by todd-prior** [comment]
By the way it is explained here...but at the time AP did not have access to the new modes that HLR modes and as I said you can use the suggestions in this video and also the new modes...just stop using clip highlights in your HLR module...this makes it the worst.... https://www.youtube.com/watch?v=F3CeJ1F4wV8

**Comment by herrkami** [comment]
Thanks @todd-prior for the explanation and apologies to all for not knowing about this. 

While I understand it is a design decision and while I can recognize the benefits of handling it like this, I'd still like to raise some concerns. Being somewhat familiar with machine learning and knowing what guided Laplacian means, it is my humble opinion that it should not be used as a default option. Below are a few reasons but tl;dr: 
It overcomplicates things and makes the entire editing more fragile for 99% of the users while providing an almost non-existing benefit for remaining 1%. 

- The method assumes that **the gradient around the overexposed region hints at the color composition** of the overexposed region. While this might hold true for neon lights and sometimes for clear skies, it most often doesn't. Much more frequently, it will result in completely wrong colors for clouds (blue instead of white), sunsets (orange instead of yellow/white), snow (blue or magenta instead of white), images of screens (whatever neighboring color is not overexposed instead of white), etc.. In most cases you therefore don't get better results but worse.
- **The damage** done to the pictures when not manually restoring highlights **is not graceful**: While the values were just clipping in v5 (giving you white highlights in the worst case) they now turn into guessed, obtrusive colors, that are neither part of the image, nor desired by the user. Although you might achieve better results when you want to restore your highlights, it completely ruins the picture if you don't. 
- The algorithm also **touches parts of the image that are almost healthy** and not fully overexposed (see sunset example from above).
- **Creating colors that are actually not part of the data** means that the user has to know what the colors actually were. In my sunset example, you might see the problem: where the clipping actually starts can be hard to tell, when you restore the highlights coming from the v6 interpretation.
- **Highlight reconstruction already worked pretty well below v6**. While the net benefit of this new method goes to zero (slightly better color restoration), the workflow became much more labor-intensive and prone to user errors. 

Therefore, it would be much better in my opinion to have this feature opt-in for those who know _exactly_ what they're doing, and switched off per default for everybody else. 

Whoever integrated this feature, please don't take it as a destructive criticism on your work. Having this method at hand is awesome and allows people to do amazing edits. However, from the perspective of someone, who wants to efficiently and robustly edit his photos, having this switched on by default is truly undesirable. (If it's just me, then please ignore this issue...)

**Comment by todd-prior** [comment]
Just dashing off but the current default in the master branch is a newer inpaint which is simple one slider and seems to handle things fairly well in the early days of testing... I have to dash but I will read you comments with the attension they deserve later...the dentist is calling..  :)

**Comment by todd-prior** [comment]
I think many would likely agree from their struggles to deal with these issues and hopefully the new options when fully refined will assist with this.... the current master HLR is inpaint which is the polar opposite of using GLHLR....

**Comment by gi-man** [comment]
@todd-prior I am not sure if we are all discussing the same thing. There is a highlight reconstruction module and there is highlight reconstruction within the filmic RGB module. I believe the one the OP is talking about is the one within filmic rgb. 

@herrkami Did you try to reduce to zero the iterations of high-quality reconstruction in the Options tab of Filmic RGB? You can also set the threshold of highlight clipping to +6EV in the Reconstruct tab of Filmic RGB. I think both of those settings will turn off what you described (if I understood you correctly).

**Comment by herrkami** [comment]
@gi-man @todd-prior Thanks for your reply! Yes, I'm only referring to the options tab in Filmic RGB. The number of iterations and the threshold have no impact on what I see, as long as I'm not reconstructing highlights. I.e., what you see in the images above also happens when the clipping slider is set to +6 EV. My issue concerns that blown highlights where just clipping to white in previous versions while now, they tend to become strongly saturated. 

This slider you are talking about @todd-prior sounds very interesting. Again, I think this feature is very nice to have, but I guess, you want something more forgiving or robust by default. Making it opt-in in the future would probably be better imho.

**Comment by herrkami** [comment]
In other words: until v5 you could leave filmic RGB at its default state and the results were fine. In the worst case there where problems around very bright or very dark regions but bright regions were never filled with weird colors. Since v6 this is not the case anymore. It can happen that bright areas which should appear in white appear in blue. The third picture above looks like this right after import. This shouldn't be imho.

**Comment by todd-prior** [comment]
Sorry for any confusion, my point was with v6 that anyone using the default clip highlights mode in that module will often see the blue...changing mode or disabling that will be less to fight with...but also now we have new tools this should not be as big a problem...
