### ISSUE TITLE
Fujifilm X S10, cannot read out white balance

### ISSUE THREAD

**Issue by LaYo27** [darktable-org/darktable#12741]
Pictures are on the lighttable but cannot edited in darkroom. Issue has already been in Dec 2020 - is ist solved so far?
this shows the terminal:
[rawspeed] (DSCF3328.RAF) rawspeed::FujiDecompressor::FujiDecompressor(const rawspeed::RawImage&, rawspeed::ByteStream), line 52: compressed RAF header check
[temperature] failed to read camera white balance information from `DSCF3328.RAF'!
[temperature] `Fujifilm X-S10' color matrix not found for image
[temperature] failed to read camera white balance information from `DSCF3328.RAF'!
[temperature] failed to read camera white balance information from `DSCF3328.RAF'!
[colorin] could not find requested profile `Standard-Farb-Matrix'!

As far as I found out, pictures are allready sent to raw.pixls.us.
Do you need further?

**Comment by kmilos** [comment]
Known issue, Fujifilm lossy compression mode is not supported yet: https://github.com/darktable-org/rawspeed/issues/255
