### ISSUE TITLE
Improve performance of navigation module drag while snapshot enabled

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12755]
When the new pannable/zoomable snapshot functionality is enabled it is possible to click-and-drag on the zoomed image rectangle within the navigation module. However, this operation stutters and lags. Panning with click+drag seems much smoother.

This seems to be an issue, to some extent, with openCL on or off.

**Comment by elstoc** [comment]
@TurboGit I guess this probably can be improved, given that click+drag seems to work better.

**Comment by TurboGit** [comment]
Should be fixed as part of #12753. I cannot do a separate PR as the code has been refactored a lot in the mentioned PR.
