### ISSUE TITLE
Misnamed shortcut action

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12754]
The name of the shortcut action `views/darkroom/allow to pan & zoom while editing masks` is incorrect. This shortcut is now also used by both the snapshots module and tone equalizer module (and perhaps others I haven't discovered).

It should be renamed, but I'm not entirely sure what it should be renamed _to_ yet.

**Comment by elstoc** [comment]
"force-enable pan & zoom with mouse"

**Comment by dterrahe** [comment]
Without the "-enable"?

**Comment by elstoc** [comment]
sure why not

**Comment by TurboGit** [comment]
Yes **"force pan & zoom with mouse"** seems clear.
