### ISSUE TITLE
scripting interface in lua or python without entering the GUI

### ISSUE THREAD

**Issue by James4Ever0** [darktable-org/darktable#12762]
**Is your feature request related to a problem? Please describe.**

Libraries like imagemagick can be automated by python using [wand](https://pypi.org/project/Wand/). Is it feasible to do the same to darktable, able to utilize powerful APIs from lua or python, without entering the main GUI?

**Describe the solution you'd like**

Either add command-line switches to darktable executable to parse scripts from file, or create some bindings in lua and python.

Also, add some code generation capabilities to GUI just like blender.

![blender_with_command](https://user-images.githubusercontent.com/103997068/199970180-1bfd169f-29e5-4dee-8726-f167e01d455a.png)

**Alternatives**

Looking into the command-line switches I don't seem to find any command switch related to this task.

**Additional context**

[darktable lua api doc](https://docs.darktable.org/lua/stable/)

current command-line switches:

```log
usage: darktable-cli [<input file or dir>] [<xmp file>] <output destination> [options] [--core <darktable options>]

options:
   --width <max width> default: 0 = full resolution
   --height <max height> default: 0 = full resolution
   --bpp <bpp>, unsupported
   --hq <0|1|false|true> default: true
   --upscale <0|1|false|true>, default: false
   --export_masks <0|1|false|true>, default: false
   --style <style name>
   --style-overwrite
   --apply-custom-presets <0|1|false|true>, default: true
                          disable for multiple instances
   --out-ext <extension>, default from output destination or '.jpg'
                          if specified, takes preference over output
   --import <file or dir> specify input file or dir, can be used'
                          multiple times instead of input file
   --icc-type <type> specify icc type, default to NONE
                     use --help icc-type for list of supported types
   --icc-file <file> specify icc filename, default to NONE
   --icc-intent <intent> specify icc intent, default to LAST
                     use --help icc-intent for list of supported intents
   --verbose
   --help,-h [option]
   --version
```

```log
usage: darktable [options] [IMG_1234.{RAW,..}|image_folder/]

options:

  --cachedir <user cache directory>
  --conf <key>=<value>
  --configdir <user config directory>
  -d {all,cache,camctl,camsupport,control,dev,fswatch,imageio,input,
      ioporder,lighttable,lua,masks,memory,nan,opencl,params,perf,demosaic
      pwstorage,print,signal,sql,undo,act_on,tiling,verbose}
  --d-signal <signal>
  --d-signal-act <all,raise,connect,disconnect,print-trace>
  --datadir <data directory>
  --disable-opencl
  -h, --help
  --library <library file>
  --localedir <locale directory>
  --luacmd <lua command>
  --moduledir <module directory>
  --noiseprofiles <noiseprofiles json file>
  -t <num openmp threads>
  --tmpdir <tmp directory>
  --version
```

**Comment by dterrahe** [comment]
https://fund.blender.org/

**Comment by HaukeRa** [comment]
I vote for this! This would allow to incorporate darktable into bigger processes (in my case a seamless day-night timelapse pipeline) where a lot is scripted and manual adaptations are just not feasable. There you would want to re-run the the script in case of improvements early in the pipeline.
