### ISSUE TITLE
display of new dynamic snapshots in top left quarter

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#12777]
on my macbook the dynamic snapshot ist displayed in the upper left quarter of the image
internal display as well as external 2K display

![image](https://user-images.githubusercontent.com/39386816/200107834-d034eb64-6e71-4b5f-9b07-8a12ec0e1c28.png)

**To Reproduce**
1. take snapshot
2. show snapshot
3. See error

**Platform**
* darktable version :darktable 4.1.0+828~g156903b8d-dirty
* OS                : OSx

**Comment by TurboGit** [comment]
Should be fixed in https://github.com/darktable-org/darktable/pull/12761

(I'll merge this soon, if you can test before it would be nice)

**Comment by MStraeten** [comment]
confirmed: #12761 fixes it

**Comment by TurboGit** [comment]
@MStraeten : Thanks for testing and reporting! I feared that I would have broken something in this delicate part and quite large rework, and I was correct :) The good news is that now the code being shared there is less distributed complexity in handling the displayed surface.
