### ISSUE TITLE
[RFC] Reduce the module layout preset options

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#12771]
Currently there are 6 module layout presets:

modules: all
modules: default
modules: deprecated
workflow: beginner
workflow: display-referred
workflow: scene-referred

Preferences:
Auto-apply chromatic adaptation: legacy

For the perspective of a new user, I think these could be too many options and could be confusing (eg. default vs beginner). I dont know the history behind these options. Is default = All - deprecated? 

Proposal:
modules: all
modules: deprecated
workflow: display-referred (legacy)
workflow: scene-referred (default)

Preferences :
Auto-apply chromatic adaptation: modern 

Please, try to keep the conversation around new users. We all have the option to create our own module layout with whatever modules we like to use. I'm just thinking of someone new, that maybe glanced quickly at the manual. I think we want set them up for success (eg. start with the scene-referred). 

**Alternatives**
Leave as it is.

ref: PR #12765

**Comment by gi-man** [comment]
Closing due to low interest.

**Comment by darkbasic** [comment]
New user here (sort of, old user using dt after several years) and I find the current defaults/presets **very** confusing.
I think this is a good proposal, maybe re-open?

**Comment by TurboGit** [comment]
No need to reopen, see #12917.
