### ISSUE TITLE
Applying a style during export to switch off a module does not work

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#12789]
**Did you buy darktable from an application store?**

No. Darktable 4.0.1 from OBS on Ubuntu.

**Describe the bug/issue**

I try to switch off the watermark module with a style at export time (export module, style append mode). The style contains only the switched off watermark module ([watermark_off.dtstyle](https://discuss.pixls.us/uploads/short-url/gxPK1GiuoIEipcDET7iNPVvD2hE.dtstyle)). Unfortunately it does not switch off the watermark. Directly applied with the styles module, the “switch off” style switches the watermark off, thus, the behavior differs between directly applied and applied in the watermark module. The counter test, switching on the watermark with a similar style, only watermark but switched on, works during export.

I wonder if somebody can reproduce, and if it is a bug or intended behavior (or a problem between display and chair).

**To Reproduce**

1. Install the style linked above (or make your own style that contains only a switched-off watermark module).
2. Apply it on an image with watermark in the export module in append mode.
3. Check if the exported image shows the watermark or not.

**Expected behavior**

Watermark does not show in exported image.

**Platform**

* darktable version : 4.0.1
* OS                : 5.15.0
* Linux - Distro    : Ubuntu 22.04.1
* Memory            : 32 GB
* Graphics card     : RTX 2070 mobile
* Graphics driver   : nvidia v515.76
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 1.21.1.3
* Desktop           : Gnome

**Additional context**

More information can be found [here](https://discuss.pixls.us/t/switching-module-off-with-export-style/33402).

**Comment by TurboGit** [comment]
@spaceChRiS : You can test PR #12797 if you are able to compile dt. TIA.

**Comment by spaceChRiS** [comment]
Yes, this change fixes the issue on my side as well. However, I found a new issue. Tried on current master + your PR. When I apply the style to the image in lighttable (not at export) multiple times, it toggles the watermark every time (also in the preview it toggles, but with the opposite state to the thumb of course). Is this intended?

**Comment by TurboGit** [comment]
> Yes, this change fixes the issue on my side as well. However, I found a new issue. Tried on current master + your PR. When I apply the style to the image in lighttable (not at export) multiple times, it toggles the watermark every time (also in the preview it toggles, but with the opposite state to the thumb of course). Is this intended?

Hum... intended, no... but this is already the case on master so not a regression of my PR.

**Comment by TurboGit** [comment]
Ok, I have a new PR #12800 with both fixes. If you can test again it would be wonderful! TIA.

**Comment by spaceChRiS** [comment]
This works indeed as expected. The only minor issue that remains is that the previews are not recomputed after the following sequence: enter darkroom --> switch on watermark --> enter lighttable --> preview is not updated (watermark not visible) --> change preview size to one that was not cached --> watermark appears. But this is independent to this issue and its fix, if you want I can file a new issue (or otherwise ignore this minor glitch :wink:).

**Comment by TurboGit** [comment]
Thanks for testing and yes please file a new issue.

**Comment by TurboGit** [comment]
@spaceChRiS : I cannot reproduce your later issue, strange.

**Comment by spaceChRiS** [comment]
Hm, maybe I described it in the wrong way. With preview I meant the lighttable thumbnails. It also does now work on 4.0.1. Anyway, thanks for the fix and support and everything! I'll file a new issue for the remaining issue.
