### ISSUE TITLE
enabling/disabling snapshot comparison alters 

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#12781]
**Describe the bug/issue**

When I turn snapshot comparison on or off, the modules displayed below the histogram jump to a module, _sharpen_, that I do not use, and do not even have in my presets.

**To Reproduce**
1. Open any image.
2. Take a snapshot.
3. Enable snapshot display.
4. Observe the module list change.

**Expected behavior**
Enabling/disabling snapshots does not change module display.

**Screenshots**
Initial view:
![image](https://user-images.githubusercontent.com/3177739/200114761-d952d2d0-ad80-407a-b2aa-da44afe4287b.png)

Snapshot created:
![image](https://user-images.githubusercontent.com/3177739/200114775-fbd7a38c-caf3-4f47-b12f-94d7421da259.png)

Snapshot activated:
![image](https://user-images.githubusercontent.com/3177739/200115013-83f5c544-b39c-46cb-b38c-6aea3c25e107.png)

Note that the sharpen module is *not* part of my 'core' module group. Switching to 'core' manually:
![image](https://user-images.githubusercontent.com/3177739/200115037-fb8ef681-20d4-4f1a-b450-b698fc579596.png)

![image](https://user-images.githubusercontent.com/3177739/200115056-f2fb550a-bdb2-4d65-a715-8fc8cd98f1f4.png)

**Which commit introduced the error**
38fe2d14379e3a5bc6a979d4b2437227e86b262a @TurboGit 

**Platform**
* darktable version : 4.1.0+828~g156903b8d
* OS                : `Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 22.04
* Memory, graphics, OpenCL: irrelevant
* Xorg              :  1:7.7+23ubuntu2   
* Desktop           : KDE 5.24.4
* GTK+              : 3.24.33
* gcc               : 11.3.0
* cflags            : N/A
* CMAKE_BUILD_TYPE  : Release

**Comment by TurboGit** [comment]
Should be fixed as part of #12761.

**Comment by kofa73** [comment]
It is, thanks.

**Comment by TurboGit** [comment]
Thanks for testing!
