### ISSUE TITLE
Module list changes unexpectedly when using duplicate manager

### ISSUE THREAD

**Issue by Hpbirkeland** [darktable-org/darktable#12782]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**
When I use the duplicate manager to either preview or go to another duplicate, the module list on the right hand side changes unexpectedly. When previewing with click-and-hold the list changes to the "technical" category and with only the defringe module displayed
When I use the duplicate manager to go to another duplicate (double click) the module list changes to "active modules", but with all modules displayed, not only the active ones.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'duplicate manager'
2. Make one or more duplicates
3. Click-and-hold og doubleclick another duplicate

**Expected behavior**
For preview I would expect the modules list not to change at all. When going to another duplicate I would expect the list to stay in the current category and only reflect the edit made on the new duplicate

**Screencast**
_(if applicable)_

**Which commit introduced the error**
Within the last few days, I get the daily updates on master from OBS. Currently on 4.1.0~git828.156903b8-1

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version :  4.1.0~git828.156903b8-1
* OS                : Linux - kernel 5.4.0-131-generic
* Linux - Distro : Linux Mint 20.3
* Memory            : 8 GB
* Graphics card     : Nvidia GTX 850M
* Graphics driver   : Nvidia driver 515
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : Yes
* Desktop           : Cinnamon 5.2.7
* GTK+              : 3.24.20

**Additional context**
_Please provide any additional information you think may be useful, for example:_

*I was using my own module list preset when I discovered this, but it also happens with the "modules: default" preset.

 Happens with OpenCL both on and off

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 Yes, but this time it was the old crop and rotate module that popped up when previewing.

**Comment by TurboGit** [comment]
Fixed in master. Was the same issue than #12781.
