### ISSUE TITLE
Color picker not selecting area

### ISSUE THREAD

**Issue by xenonsailor** [darktable-org/darktable#12793]
**Describe the bug/issue**
When using color picker (module in left hand menu bar) I can pick on spot using left mouse key. I am unable to select an area using either the right hand mouse key or holding control key.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'color picker'
2. Click on 'pipette symbol to turn on color picker'
3. 'hold down ctrl key on keyboard, use left hand mouse key to pick a starting point of an area'
4. cursor target moves as if ctrl key not pressed.
5.  move mouse to second point - cursor moves as if ctrl key not pressed
6.  drag cursor to second point - cursor moves as if ctrl key not pressed
7.  use right hand mouse button to select a point - nothing happens, cursor does not move

**Expected behavior**
When using ctrl key or right hand mouse button an area is selected

**Screenshots**
![image](https://user-images.githubusercontent.com/88908031/200165216-4e9fe215-11e8-4824-9e04-8104c9a30f4e.png)

**Platform**
 Canon .cr3, jpg and tiff files tested.

* darktable version : 4.0.1 as last stable release
* OS                : Windows 10 Pro ver 21H2
* Memory            :  16GB
* Graphics card     :  NVidia NVS5200M
* Graphics driver   : 
* OpenCL installed  :  yes
* OpenCL activated  :  no
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no** not tried - it used to work in last 3 series dt
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both** yes, both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no** yes, I cleared the history stack module by module down to input and output profiles, orientation and disply profile. No change to picker behaviour.
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no** yes
 - Do you use lua scripts? no
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?
[IMG_7498.zip](https://github.com/darktable-org/darktable/files/9945597/IMG_7498.zip)

**Comment by MStraeten** [comment]
you need to press ctrl key when enabling color picker

**Comment by xenonsailor** [comment]
It's so easy when you know how!
Thank you Martin, much obliged.

Best regards,
Andrew

**Comment by Nilvus** [comment]
So good to close @xenonsailor
