### ISSUE TITLE
JXL (required version >= 0.7.0)  Build fails with 4.1.0+875~gaa14affc8 -

### ISSUE THREAD

**Issue by dtteufel** [darktable-org/darktable#12806]
Build from current git fails if libjxl / libjxl-dev package is installed

* darktable version : 4.1.0+875~gaa14affc8
* OS                :  Linux Mint 21 Cinnamon
* Linux - Distro    : Ubuntu 22.04
* libjxl-dev Version 0.7.0

Error Messages:

/home/xxxx/dtgit/src/imageio/format/jxl.c: In function ‘write_image’:
/home/xxxx/dtgit/src/imageio/format/jxl.c:122:7: error: unknown type name ‘JxlEncoderError’; did you mean ‘JxlEncoder’?
  122 |       JxlEncoderError err = JxlEncoderGetError(encoder);                                                          \
      |       ^~~~~~~~~~~~~~~
/homexxxx/dtgit/src/imageio/format/jxl.c:122:7: note: in definition of macro ‘LIBJXL_ASSERT’
  122 |       JxlEncoderError err = JxlEncoderGetError(encoder);                                                          \
      |       ^~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [lib/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/build.make:76: lib/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/jxl.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6569: lib/darktable/plugins/imageio/format/CMakeFiles/jxl_format.dir/all] Error 2

**Comment by kmilos** [comment]
See [this and below](https://github.com/darktable-org/darktable/pull/10044#issuecomment-1290591052). You don't have the official 0.7.0 version.

**Comment by dtteufel** [comment]
As ever, enough said.
II will continue to compile without JXL support - clearly more trouble that its worth!
