### ISSUE TITLE
Lighttable thumbnail is not updated after solely switching on watermark module in darkroom

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#12803]
**Did you buy darktable from an application store ?**

No. Darktable 4.0.1 from OBS on Ubuntu, and current master built by myself.

**Describe the bug/issue**

As title says. A minor issue.

**To Reproduce**

Starting with an edit where the watermark was already applied but switched off.

The following sequence shows the issue:
* enter darkroom
* switch on watermark
* enter lighttable
* thumbnail is not updated (watermark not visible)
* change preview size to one that was not cached
* watermark appears

**Expected behavior**

Thumbnails should be invalidated at any change in darkroom and therefore recomputed.

**Which commit introduced the error**

Does not work in 4.0.1 and current master, so it's probably there for a while already …

**Platform**

* darktable version : 4.0.1
* OS : 5.15.0
* Linux - Distro : Ubuntu 22.04.1
* Memory : 32 GB
* Graphics card : RTX 2070 mobile
* Graphics driver : nvidia v515.76
* OpenCL installed : yes
* OpenCL activated : yes
* Xorg : 1.21.1.3
* Desktop : Gnome

**Comment by TurboGit** [comment]
I cannot reproduce this.

**Comment by spaceChRiS** [comment]
I tried with this [file](https://discuss.pixls.us/uploads/short-url/kcX7MDIwZ6um6GFVOGbJKJdvLf7.CR2) from pixls.us PlayRaw, this is the xcf: [IMG_0510.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/9955637/IMG_0510.CR2.xmp.txt). First I thought it is because of shared cache directory, but it also happens with

    darktable --configdir conf/ --tmpdir temp --cachedir cache
