### ISSUE TITLE
Improved user experience when images require exif metadata refreshing.

### ISSUE THREAD

**Issue by sgotti** [darktable-org/darktable#12804]
### Preamble
Features implemented in #10289 and #12714 relies on additional exif metadata not stored inside the db. Inside the db, when on image import additional required exif tags are detected, a flag `DT_IMAGE_HAS_ADDITIONAL_DNG_TAGS` is set. When such flag is set on image open (currently only in `imageio_rawspeed.c`) additional exif tags are read from the file (`dt_exif_img_check_additional_tags(img, filename);`).
So the above PRs reused an implementation used only for the DNG user crop but now expanded also to images that aren't dng (so also the flag name should be changed for consistency).

### Current state 
This means that if a user already imported images with a darktable version without these PRs merged the flag will be false and that features will not be available until it refresh the images with the "refresh exif metadata" button.
Additionally, this isn't something required only for darktable 4.2 but if new features that require new exif tags will be implemented in future, the refresh should be required again for images that until that point didn't required new exif tags.

**SIDE NOTE**: Additionally this "refresh exif metadata" could have a negative effect since it could also reset the "star rating" if user haven't explicitly flagged in the "import module" the `ignore EXIF rating` option (by default not visible since it's in the "parameters" sections closed by default) (perhaps this is another issue)

So this could cause some bad user experience and issues for users since it's not clear why these new features reported in the release notes doesn't work or why they work only for newly imported images.

### Proposed solution

I see two options:
1. Only document this in the manual/release notes and perhaps somewhere in the gui. But this will always require user interaction and a full library exif metadata refresh (and probably issues like the above side note).
2. Always call `dt_exif_img_check_additional_tags(img, filename);` in `imageio_rawspeed.c` regardless of the DT_IMAGE_HAS_ADDITIONAL_DNG_TAGS. This means that the image will be opened two times (one by rawspeed and one by exiv2 library) but not read two times since exiv2 will seek and only read the exif data. So I'm not sure if this will have a performance impact and how much.

Personally I'm totally in favor of option **2** (if the performance penalty will be negligible).

cc @paolodepetrillo

**Comment by paolodepetrillo** [comment]
I agree that it would be better to ignore the flag and read the tags unconditionally as long as the performance impact is not significant.
