### ISSUE TITLE
"White balance applied twice" error

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12801]
v4.0.1

when I begin working on an image, the white balance module is already applied to the image.

![wb1](https://user-images.githubusercontent.com/1417508/200221876-eddcdb91-4690-421c-bdd9-85cd935aa620.png)

If I open the white balance module, as soon as I change something in this module controls, an error notification is shown in the wb module - saying "white balance applied twice" - and in the color calibration one - saying "white balance module error".

![wb2](https://user-images.githubusercontent.com/1417508/200221892-2075b7bf-64ec-400c-896d-346b9ea55dc7.png)

I'm quite sure that in 3.8 the error message didn't appear.

I remain very confused:

- can I actually modify the controls? it seems so...
- how does it affect the color calibration module action?

**Comment by MStraeten** [comment]
If you’re using color calibration in the modern whitebalancing workflow then the whitebalance module needs to be set on camera default.
If you selected a custom whitebalance and use color calibration parameters based on that values, you can ignore the warning…
If that’s your usual workflow, you can also disable the warning.

**Comment by Nilvus** [comment]
Or click on the bulb icon in white balance. The warning will disappear as it's the mode compatible with color calibration white-balancing part.

**Comment by Nilvus** [comment]
Oh, and it's a duplicate of those issues (more infos on them if you want to understand why you have that and what to do with):
#12134 and #11377
