### ISSUE TITLE
Deleted presets in export module

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#12818]
**Did you buy darktable from an application store ?**
Master via OSB

**Describe the bug/issue**
I selected an export preset that I use for social media post. After selection, a warning said something along the lines: Deleting preset for obsolete (it disappears). The preset was deleted. 

**To Reproduce**
I selected another export preset I had and it did the same. I reproduced until I dont have more presets in the export module.

**Expected behavior**
Keep the preset or allow updating?

Workaround:
Recreated the presets

**Which commit introduced the error**
Maybe https://github.com/darktable-org/darktable/pull/12767 due to the removal of the bit depth?

**Platform**
* darktable version : 4.1.0~git894.9353771b via OSB
* Linux - Distro    : Fedora 36 KDE X11

**Comment by pehar1** [comment]
I observed the same behaviour yesterday with 4.1.0-870-gd0d0369f4. Loaded a preset from the list to make a modification, wanted to save the modified preset (with same name) and the (before selected) entry in the list was gone. I had to recreate the preset. Did not notice the warning @gi-man mentions, probably I was not attentive enough. The effect is reproducible.

**Comment by TurboGit** [comment]
Even if you create a new preset? You select it and it gets deleted?

**Comment by TurboGit** [comment]
@gi-man : What was the format for the presets having been deleted? AVIF? other?

**Comment by gi-man** [comment]
It was jpeg. I just checked, the ones from yesterday stayed (not deleted).

**Comment by TurboGit** [comment]
Really strange, the JPEG module has not been touched since Oct 9th. There must be something else...

**Comment by gi-man** [comment]
I have 4.1.0+632~ge2dc17290 in my test folder. It is not doing it there, but that build is old. 

In current master, other modules are not doing this. For my it was only on Export. I'm not 100% sure if I have selected another preset in the export module after 09OCT. 

It is strange, but not a huge deal. We will see if other notice a similar problem.

**Comment by Hpbirkeland** [comment]
I have noticed the same thing for the last week or so, including today, dt 4.1.0.~git.897.6bb53e25-1. The message says "deleting preset for obsolete module". Old presets for both jpg and tif. New presets created after the bug appeared don't get deleted.

**Comment by TurboGit** [comment]
Is someone still have some presets non deleted on the db or a data.db backup? If possible I'd like to get some broken preset to see what is going on. If you think you have I'll give you a command to retrieve the preset. TIA.

**Comment by pehar1** [comment]
I also have still two old (broken?) presets in my actual `data.db` aside with two newly created. And I have several backups of `data.db`. I could provide such a database as long as it does not contain personal, private data. I would have to check that beforehand. I have also installed a graphical frontend for sqlite, so I could also execute SQL commands on my `data.db` as you wish.

My presets all export `jpeg`. Unfortunately I have no old preset for other export formats.

I also tested with presets for modules _raw black/white point_, _negadoctor_, _crop_, _color balance rgb_. These presets are not affected.

**Comment by TurboGit** [comment]
Good, so can you export the presets using:

`echo ".dump presets" | sqlite3 ~/.config/darktable/data.db | grep \'export\' > export.txt`

If you know of a one preset that is broken you can edit export.txt and keep only the line for this export.

Each line looks like:

`INSERT INTO presets VALUES('<PRESET_NAME>','','export',7,X'8813000......`

And attach this file here? There is no personal information in there, only the name presets and all the data for the format & storage dt modules.

**Comment by pehar1** [comment]
[export.txt](https://github.com/darktable-org/darktable/files/9968392/export.txt)

Here you are, contains 4 presets, haven't touched _"Public Fullsize JPG 90"_ and _"Panorama"_ with current master, _"HD Christoph"_ and _"Private Fullsize JPG 95_" have been recreated yesterday after they had been removed by the current bug.

**Comment by TurboGit** [comment]
@pehar1 : Thanks!

There is 4 presets, can you confirm that this one is original:
- Public Fullsize JPG 90

The 3 others have been recreated already:
- Private Fullsize JPG 95
- Panorama
- HD Christoph

**Comment by pehar1** [comment]
I definitely recreated

- Private Fullsize JPG 95
- HD Christoph

I did not load

- Private Fullsize JPG 95

with 4.1.0-870-gd0d0369f4, and I am relatively sure that I also did **not** load

- Panorama

If it helps I can go bak to a previous (backup) data.db where I'm sure it has never seen current master.

**Comment by TurboGit** [comment]
@pehar1 : No, that's clear, the fix has been pushed. Of course this breaks the presets that you have recreated:

- Private Fullsize JPG 95
- HD Christoph

The Panorama has probably be recreated too or somehow changed has it is still broken after my fix.

But:
- Public Fullsize JPG 90

Is now working fine and no more removed from db. Thanks for helping tracking this issue.

**Comment by Hpbirkeland** [comment]
This is happening again for me, on 4.1~git1053.b7450099-1. I just used a preset that was created after the issue was fixed last time.

**Comment by pehar1** [comment]
Strange, same version 4.1.0+1053~gb74500996 just build from current master, and it works for me without any problems. I tested with new created presets, my old presets got deleted during verifying the issue.

**Comment by gi-man** [comment]
No issues on my end either. 4.1.0~git1059.222e7125 Fedora 36 KDE

**Comment by Hpbirkeland** [comment]
Strange. I have been unable to test more for about a week, and today everything is fine again (4.1.0~git1109).
