### ISSUE TITLE
dynamic snapshot: snapshots are lost on compressing history stack

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#12812]
Use Case 1: a snapshot is taken from an existing edit, then after a couple of changes the history stack is compressed, maybe on an arbitrary position of the stack to get rid of latest steps.
Use Case 2: a snapshot ist taken from image 1; the history stack of image 2 is compressed on fist stack position to get a default initial processing to be adapted to the snapshot

Unfortunately this is a side effect of the dynamic snapshot since after compressing the history stack the recalculation of the snapshot in Use Case1 isn't possible in any case. But at least for Use Case 2 this would be possible in general.

**To Reproduce**
1. create a snapshot of an arbitrary edit
2. Click on 'compress history stack'
3. --> snapshot is lost

**Expected behavior**
a static snapshot is kept as in former darktable versions as a backup if a dynamic snapshot can't be recalculated

**Platform**

* darktable version :  4.1.0+905~g9c16ba999
* OS                :  OSx

**Comment by TurboGit** [comment]
Duplicate : https://github.com/darktable-org/darktable/issues/12766

**Comment by TurboGit** [comment]
Ok, not a full duplicate we could indeed remove the snapshots only for the image from which the history is compressed.

**Comment by TurboGit** [comment]
@MStraeten : Can you check #12824? TIA.
