### ISSUE TITLE
Styles with multiple instances of disabled modules no longer work

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#12815]
**Introduction**

I create styles with computationally intensive modules (i.e.  diffuse or sharpen) turned off so that editing is responsive.  After I'm finished with the edits, I enable the rest of the modules and then make any final adjustments.
**Describe the bug/issue**

I use 4 instances of diffuse or sharpen.  Every image uses 2 instances and the other 2 instances may be enabled depending on the image.  Now when I apply the style, only 1 instance of diffuse or sharpen appears.

**To Reproduce**

1. Check out d0d0369f45d3f103d0c14c6b4c1278c70dd4a001 and build
2. Import the attached style
3. Apply the style to an image
4. In darkroom look at the modules list and notice the 4 instances of diffuse or sharpen and where they are in the pipeline.
5. Checkout 0a7af3ce51f3220ca1e341e21b507106f0441952 and build.
6. Apply the style to another image, then open in darkroom and notice only one instance of diffuse or sharpen and it's in the wrong place int the pipe.

**Expected behavior**

Step 4 above.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**

0a7af3ce51f3220ca1e341e21b507106f0441952

Here's the style to test with

[starting_point_dtstyle.zip](https://github.com/darktable-org/darktable/files/9955506/starting_point_dtstyle.zip)

**Comment by TurboGit** [comment]
Should be fixed, that's a really tricky part, I hope I didn't break something else. Thanks for testing!

**Comment by wpferguson** [comment]
Thanks for fixing
