### ISSUE TITLE
imageio_heif error message - Is your libheif compiled with HEVC support?

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#12827]
**Describe the bug/issue**
I've been shooting with a EOS R7 for the last couple of months and processing the images in darktable without any problems.  Today I noticed that every time I open an R7 image (CR3) I get an error message:

`[imageio_heif] Unsupported file: `/home/bill/Pictures/darktable41/2022/10/20221028-Football.Varsity.Linsly.vs.JM/103R7LR4_3J6A5441.cr3'! Is your libheif compiled with HEVC support?`

I checked to make sure my libheif was up to date.  It was 1.12, so I updated to 1.13 (latest) and still have the error message.

Checked with a play raw CR3 and found that it also displays the error message?

**To Reproduce**

1. Open darktable in a console window
2. Open a CR3 image in darkroom view
3. Check the console window for the error message

**Expected behavior**
I haven't seen it up to now, and I'm on the latest libheif and the hevc dependencies are also installed, so I believe that I shouldn't be seeing the error or else the libraries aren't compiled correctly.

**Which commit introduced the error**
7734741879edcfd82ff6b97b1cc52f97f28bcf1c

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.1.0+888~g773474187
* OS                : Linux
* Linux - Distro    : Ubuntu 20.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by kmilos** [comment]
@victoryforce I guess this is now a consequence of not checking the file extension any longer, and we should find a way to fail silently?

**Comment by victoryforce** [comment]
@wpferguson  Until now, the HEIF loader was called from the dt_imageio_open_hdr wrapper function and only if the file extension matched a specific list of HDR format extensions. The problem was that this wrapper always overwrites the flag detected by the loader to DT_IMAGE_HDR, preventing us from detecting LDR images. To resolve this, the dt_imageio_open_heif call was moved to the main loader queue. dt_imageio_open_heif can now try to load images without file extension restrictions, as most loaders do. However, such loaders exit silently when they determine that they cannot decode a file, and the heif loader was more chatty. I'll fix this when I decide which workaround to go for.

**Comment by victoryforce** [comment]
> @victoryforce I guess this is now a consequence of not checking the file extension any longer, 

Yes, that's right.

> and we should find a way to fail silently?

As an option, although the message seems to me to be quite informative (if it occurs when trying to read a really HEIF file) and I would not like to remove it completely. Maybe move it from stderr to DT_DEBUG_IMAGEIO? How do you feel about this solution?

**Comment by wpferguson** [comment]
I vote for the DT_DEBUG_IMAGEIO

**Comment by kmilos** [comment]
Is that what we do for JPEG XL and AVIF loaders beforehand as well?

**Comment by kmilos** [comment]
Btw, I'm also surprised libheif doesn't return a different error code and error message as CR3, although a ISOBMFF container, is not a HEIF file...

**Comment by kmilos** [comment]
@wpferguson You should have lots of "[avif_open] failed to parse ..." in the log for each CR3, as the AVIF loader uses DT_DEBUG_IMAGEIO already and not stderr? The JPEG XL loader has no reporting on parse failure (like the WebP one)...

I wonder if DT_DEBUG_IMAGEIO is the best route here: it'll fill the log with failure messages from many loaders for each file...

So we can a) be completely silent like JPEG XL and WebP (not ideal either) or b) only do DT_DEBUG_IMAGEIO if the file extension matches the loader expectation?

**Comment by kmilos** [comment]
> Btw, I'm also surprised libheif doesn't return a different error code and error message as CR3, although a ISOBMFF container, is not a HEIF file...

Ah, maybe it does, maybe we just need to be silent on `case heif_error_Unsupported_filetype:`?

**Comment by wpferguson** [comment]
> @wpferguson Can you plese test this:

No errors when opening CR3 files.  Tried with -d imageio and still no errors

> @wpferguson You should have lots of "[avif_open] failed to parse ..." 

Running with -d imageio in master I get

```
7.926870 [avif_open] failed to parse `/home/bill/Pictures/darktable41/Play.Raw/IMG_20220118_5216.CR3': Invalid ftyp
7.927050 Failed to read HEIF file [/home/bill/Pictures/darktable41/Play.Raw/IMG_20220118_5216.CR3]
[imageio_heif] Unsupported file: `/home/bill/Pictures/darktable41/Play.Raw/IMG_20220118_5216.CR3'! Is your libheif compiled with HEVC support?
```

I tested #12832 and it didn't spit out any errors either.

**Comment by kmilos** [comment]
Thanks for testing!
