### ISSUE TITLE
FR: please revert the sorting order of snapshots

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#12835]
Talking about current master, there is one thing I desperately dislike even though I see similar discussions elsewhere outside of dt-community...

I know in chatrooms, the newest is at the bottom, but any other place in my life, be it digital or real life, the newest is always on the top!

Therefore **_please_** revert the sorting order to what it was in the snapshots list, newest on top not at the bottom

@TurboGit forgive me when I challenge your baby, maybe :)

**Comment by TurboGit** [comment]
> elsewhere outside of dt-community...

I really really don't care, people talking without even taking time to come here and discuss with the devs!!!!

> Therefore please revert the sorting order to what it was in the snapshots list, newest on top not at the bottom

If you really want that :) I'll do.

**Comment by TurboGit** [comment]
Fixed !

**Comment by AxelG-DE** [comment]
Wow
That was fast, thank you!

**Comment by TurboGit** [comment]
It was quite simple change :)
