### ISSUE TITLE
Bug - Need Support - darktable.exe caused an Access Violation at location in module libdarktable.dll

### ISSUE THREAD

**Issue by blg39730** [darktable-org/darktable#12833]
**Introduction**

Hello, I am having an issue with darktable where after working on a file and then trying to export, the image will crash the application. After reopening darktable I can no longer access the file in darkroom or the application will crash. (See "Errors" in screenshots below) Below is the error I get with the attached log file. (See "Errors" in files below) If I delete the history stack I can access the image again. I have tried to include as much of the history stack as I can but since the application crashes when going to darkroom I cannot scroll down to get it all. (See "History Stack" in screenshots below)

**Did you buy darktable from an application store ?**
No, I downloaded darktable from the official website.

**To Reproduce**

    1) Start darktable
    2) Edit image with modules 
    3) Attempt to export
    4) Get Error
    5) Reopen darktable 
    6) Attempt to open image in darkroom
    7) Get error

**Expected behavior**
I should be able to export and access picture in darkroom after.

**Screenshots**
--Errors--
![image](https://user-images.githubusercontent.com/117835240/200875104-b823241f-2834-4a30-9aac-8420668434ca.png)

--History Stack--
![image](https://user-images.githubusercontent.com/117835240/200875372-1fdd85b6-ee98-445a-bcbe-d602938ba0f0.png)

**Files**
[BEN01580.ARW.xmp.zip](https://github.com/darktable-org/darktable/files/9972677/BEN01580.ARW.xmp.zip)
- Would not let me include the original ARW file even zip because it was over the 25MB limit. 

--Errors--
[darktable_bt_K3K0U1.txt](https://github.com/darktable-org/darktable/files/9972648/darktable_bt_K3K0U1.txt)
[darktable_bt_L3K0U1.txt](https://github.com/darktable-org/darktable/files/9972649/darktable_bt_L3K0U1.txt)
[darktable_bt_YOM0U1.txt](https://github.com/darktable-org/darktable/files/9972650/darktable_bt_YOM0U1.txt)

**Platform**

* darktable version : 4.0.1
* OS                : Windows 10 Home (Version: 21H1) (Build: 19043.2251)
* Memory            : 32GB (Only 8GB in use)
* Graphics card     : NVIDIA GeForce GTX 1050 TI
* Graphics driver   : 30.0.15.1215

**Comment by blg39730** [comment]
Any additional information I can provide to get assistance?

**Comment by ralfbrown** [comment]
If you are still having this problem, please try the most recent "Windows insider" build from https://discuss.pixls.us/c/software/darktable/19 or a daily build from here.

The only non-empty backtrace indicated a problem with the subpixel interpolation used to scale the image, and that particular code has recently had a substantial rewrite.  (On the other hand, the crash in that code could merely be a symptom of e.g. an insane resizing due to a bug elsewhere.)
