### ISSUE TITLE
Filmic defaults for dt 4.2

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#12847]
As of lately (since dt 4.0) there has been quite a bunch of confusion caused by filmic among the userbase. I think these are mainly due to two reasons:

1. Introduction of v6 color science which always preserves the chromaticity angle, even in the "no" preservation mode. It also removed the desaturation curve which might have hidden some issues with color shift to red in e.g. sunset images.
2. Default preservation mode was changed to max RGB. It magnifies issues with clipped highlights and causes color casts where things should be white. I've personally never quite liked the flattening effect on local contrast it causes, and I think others have found it two.

Number 1 is a tougher one to address. There are some possible tweaks:
* Allowing the user to relax the preservation of chromaticity angle, like the slider in sigmoid
* Changing the gamut mapping in the highlights a bit to preserve the original saturation a bit better.

However this would require introduction of a new color science mode. I have been experimenting with some things that would benefit filmic's output, but it would be more likely to introduce those early in the 4.3 dev cycle. I personally think it's a bit late to have them for 4.2.

Number 2 can be easily addressed by changing the default preservation mode to e.g. RGB power which has worked previously pretty well for people as far as I've seen. Defaults are kind of important as they give the first impression of the module, its capabilities and "look".

Also there's https://github.com/darktable-org/darktable/issues/12442 which would be pretty easy to address for now by changing the filmic highlights reconstruction parameters a bit (still need to test a bit if it holds up).

So my proposals for changes of defaults would be:

1. Preservation mode to RGB power
2. Highlight reconstruction threshold to 6 EV
3. Highlight reconstruction transition to 0.25 EV

For 2. and 3. I'd possibly also consider changing the minimum of the transition to 0 and changing the code such that 0 would entirely disable the reconstruction. Currently it is not possible to disable it entirely.

@TurboGit and others what do you think of this?

**Comment by jenshannoschwalm** [comment]
Personally I fully agree with your proposals, also with "extending" the allowed range. It would be a more reasonable default and tuning would not be different from what we have now.

**Comment by TurboGit** [comment]
I agree, for me:

1. RGB power has been better (for my taste) in most cases.
2. 6EV threshold is not a huge change compared to current 3EV which has always been disabling the reconstruction for me.
3. Fine too.

So all in all I agree with those new defaults.

**Comment by TurboGit** [comment]
I'm not so sure with 3 actually, it does creates some hard transitions in many places on sky with clouds.

**Comment by flannelhead** [comment]
Yes, that requires some further thought.

**Comment by gi-man** [comment]
Out of my trial and error approach, in the past months I've been using RGB power, 6EV threashold and 0.66EV transition as my default. Ive also defaulted the iterations of high quality reconstruction to 0, but I'm not sure I see a difference since using the 6EV threshold.

**Comment by SoupyGit** [comment]
An alternate solution:
Have a checkbox in 'reconstruct tab' labelled 'enable'. When ticked, reconstruction is applied. When not ticked, no reconstruction is applied. Default state is not ticked.

This way you could leave transition default at 3EV, and make threshold default 0EV (without need to expand the range to 6EV). Benefit of this is that when checkbox is enabled, user might not even have to adjust any sliders for a good result. That would be one click (checkbox), compared to one slider (threshold - current implementation), or two sliders (threshold & transition - proposed implementation).

As for defaults, I would also propose 0 noise in highlights as default, given noise is typically seen as an artifact.

**Comment by flannelhead** [comment]
> Have a checkbox in 'reconstruct tab' labelled 'enable'. When ticked, reconstruction is applied. When not ticked, no reconstruction is applied. Default state is not ticked.

That could work. Also, the checkbox could be automatically enabled when one moves any of the sliders in that tab.

> As for defaults, I would also propose 0 noise in highlights as default, given noise is typically seen as an artifact.

The noise is only applied on areas where the highlights reconstruction is applied, and it's done to "seed" the reconstructed areas with some texture. Thus I wouldn't turn it to 0 by default.

**Comment by pehar1** [comment]
In my opinion, the most unambiguous solution is a checkbox to disable highlight reconstruction. The need to move at least two sliders to disable hlr assumes that the user has fully understood the function of these settings. This does not always seem to be the case, especially with new users.

**Comment by Nilvus** [comment]
I agree with @SoupyGit proposal about a checkbox to enable or disabled highlight reconstruction. This could be a good add, with @flannelhead proposal to automatically enable it when moving any of the sliders in that tab.

About others proposal:
- about moving to RGB power is ok to me, even if the actual default is also ok to me. Difference between most of my images is subtle. It's only when I have blue sky in the image, than RGB power is better and most of the time, luminance setting is even better on my side, regarding my taste
- if we have the checkbox, changing treshold is not really needed I think. 3IL default is ok then. I so also agree with @SoupyGit
- for transition one, moving it to 0.25 or even 0 create too hard transitions. 3IL is also a good start (or why not a little less but no less than 2IL by default).

**Comment by flannelhead** [comment]
If the reconstruction disable/enable checkbox is implemented and disabled by default, then the changes to threshold and transition could be forgotten.

I'm still going to see if the https://github.com/darktable-org/darktable/issues/12442 issue with `colorbalancergb` brilliance can be properly fixed. At any rate, IMO still the toggle for reconstruction would be useful.

**Comment by AxelG-DE** [comment]
From being a user only, I am also fine with the proposals here except reconstruction off by default and transition 0. 

I would opt for reconstruction on but disable by checkbox, is fine and transition, leave it to three or a bit lower...

Besides astro, I often shoot directly to the light source, there is where my thoughts come from

**Comment by SoupyGit** [comment]
Reason for disabling it by default would be 
A) because highlight reconstruction module is enabled by default, and we don't need to double up on two reconstructions automatically enabled, and
B) to avoid artifacts like those mentioned when using brilliance in color balance rgb.

@flannelhead suggestion of auto enable upon slider move is good, as it means there are no extra clicks than current implementation, so workflow stays the same

**Comment by flannelhead** [comment]
I'm a bit torn about disabling the filmic highlights reconstruction by default. On one hand, disabling it makes people not hit https://github.com/darktable-org/darktable/issues/12442 by default. On the other hand, having it on by default would help smoothing some nasty highlights which are not entirely fixed by the highlights reconstruction module earlier in the pipe. :shrug:

**Comment by elstoc** [comment]
> I'm a bit torn about disabling the filmic highlights reconstruction by default.

But the current defaults are designed to be virtually equivalent to "off" anyway (with a threshold of +3EV I've never seen it actually affect the image by default). So I'm not sure I understand the problem. IIRC this was originally done to improve performance, especially for people without GPUs.

**Comment by jenshannoschwalm** [comment]
> On the other hand, having it on by default would help smoothing some nasty highlights which are not entirely fixed by the highlights reconstruction module earlier in the pipe

Would be interested in a specific example (raw, xmp and the location in the image).

**Comment by TurboGit** [comment]
Closing as PR merged.
