### ISSUE TITLE
Toggle button of selected module group no longer recognizable as selected

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#12842]
**Did you buy darktable from an application store ?**
no, self build from current master

**Describe the bug/issue**
The button of the selected module group in darkroom is no longer marked as selected (background looks the same as unselected groups). Only if the mouse is hovered over the button the correct background color appears. Using darktable-elegant-grey theme. In the screenshot below group _"correction"_ is selected.

**To Reproduce**
Goto darkroom
Select a module group

**Expected behavior**
Button of the selected module group should be highlighted (distinguishable from the non-selected buttons)

**Screenshots**
![module-groups](https://user-images.githubusercontent.com/104291381/201045432-6435e297-0590-4f24-8621-a8697d99ccab.png)

**Which commit introduced the error**
not sure, possibly https://github.com/darktable-org/darktable/pull/12794

**Platform**
* darktable version : 4.1.0+933~ged1b58cfb
* OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.141.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by TurboGit** [comment]
Should be fixed in release-4.1.0-934-gd3038b0aa (so you are missing latest commit)

**Comment by pehar1** [comment]
Thanks, you are just too fast at committing...  ;-)
