### ISSUE TITLE
darktable 4.1 fails to compile on Windows

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12848]
**Describe the bug/issue**
darktable 4.1 (git [f2b810f](https://github.com/darktable-org/darktable/commit/f2b810fdc637e05c69a2d8c81bd228d46f6963b5)) fails to compile on Windows

**To Reproduce**
1. start to compile target (`cmake --build . --target package`)
2. See error
`[15/848] Building CXX object bin/CMakeFiles/lib_darktable_imageio_rawspeed.dir/common/imageio_rawspeed.cc.obj
FAILED: bin/CMakeFiles/lib_darktable_imageio_rawspeed.dir/common/imageio_rawspeed.cc.obj
C:\msys64\ucrt64\bin\c++.exe ... -c C:/msys64/home/xxxx/darktable/src/common/imageio_rawspeed.cc
C:/msys64/home/xxxx/darktable/src/common/imageio_rawspeed.cc: In function 'dt_imageio_retval_t dt_imageio_open_rawspeed(dt_image_t*, const char*, dt_mipmap_buffer_t*)':
C:/msys64/home/xxxx/darktable/src/common/imageio_rawspeed.cc:391:33: error: 'class rawspeed::RawImageData' has no member named 'getByteDataAsUncroppedArray2DRef'; did you mean 'getU16DataAsUncroppedArray2DRef'?
  391 |       memcpy(buf, (char *)(&(r->getByteDataAsUncroppedArray2DRef()(0, 0))), bufSize_mipmap);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                 getU16DataAsUncroppedArray2DRef
compilation terminated due to -Wfatal-errors.
`

**Platform**
* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : WIn10 (UCRT build environment)
* CMAKE_BUILD_TYPE  :  package

**Additional context**
I cleaned my build directory, but that didn't help.

**Comment by TurboGit** [comment]
You want to update the rawspeed submodule.

**Comment by kmilos** [comment]
The CI is green: https://github.com/darktable-org/darktable/actions/runs/3439864956 so must be PEBCAC

**Comment by lintujuh** [comment]
My bad. Didn't think that.
