### ISSUE TITLE
FR: Multiple presets for a single module

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#12853]
**Is your feature request related to a problem? Please describe.**
Some modules like diffuse & sharpen have several use cases and the user will apply multiple instances of the same module. Currently you can store only one preset per module that will be auto-applied.

**Describe the solution you'd like**
User can store multiple presets with name (like named module instances) that can be auto-applied to an image.

If the preset would have a name, that could be used to differentiate between different conditions when the module is applied. Currently you cannot have same settings applied with different conditions. You have to also tweak the module parameters so that they are not 1 to 1 if the other presets.

**Alternatives**
Current workaround is to define multiple instances as styles.

**Comment by Nilvus** [comment]
A good feature but not for all modules. Actually, such feature should be limited to few modules. By now, I see:
- as you said, diffuse & sharpen
- noise reduction (profile)

**Comment by TurboGit** [comment]
Agreed, a good enhancement, probably not easy though as module duplication is needed to apply each preset.
