### ISSUE TITLE
include manual in program

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#12861]
**Is your feature request related to a problem? Please describe.**
New users might not know where to find the manual online, or have access to internet connection at all times.

**Describe the solution you'd like**
Manual can be included in darktable itself in top right corner, as an 'other' option, along with map, print, slideshow and tethering.

Further, as per mockup below, each module can have a "?" symbol. When users click this, it takes them to the relevant section in the manual. (Eg. clicking "?" beside filmic rgb will take them to a page with this information: https://docs.darktable.org/usermanual/4.0/en/module-reference/processing-modules/filmic-rgb/)

![manual-mockup](https://user-images.githubusercontent.com/69561443/201311094-d248a1a3-4303-4243-8471-32dca6bd5ad3.png)

This would make accessing the manual (and specific sections in the manual) as simple as possible, and might help avoid many of the same beginner questions.

**Comment by TurboGit** [comment]
For each section you already have a `?`, you click on it and go to the darktable section you want the doc on. So I don't see the distributed complexity having a `?` everywhere a good idea. It clutter the UI for no good reason.

**Comment by SoupyGit** [comment]
> For each section you already have a ?, you click on it and go to the darktable section you want the doc on.

You made me go searching. I see now there is a "?" near the settings icon in top bar, which if we click, presents us with an "x" or a "?" when hovered over a module. Clicking a module then takes us to the relevant section in docs. This is indeed a solution, but at least by my experiences is not very discoverable for new users - I've been using dt for over a year now and didn't know about it (maybe also because I hide that top bar while editing).

**Comment by MStraeten** [comment]
i doubt that a user that needs to be pointed to the manual in every corner of the app is what darktable is developed for. RTFM is the first recommendation made to beginners ...
to have a good UX it makes sense to get rid of any bloat - even well-intentioned bloat

**Comment by SoupyGit** [comment]
I can understand not wanting duplication of function. If one feels my solution is inferior to the current solution, that's a good reason reject it. 

But on the matter of "bloat" or "clutter", I do not see how this is any different to having a reset and preset button on every module. Nobody suggests that they are bloat. (And the provided solution there was indeed to put them on every module, not have one reset button for all in the top bar).

**Comment by MStraeten** [comment]
reset or selection of a preset are module specific operations and speeds up using the modules - reading the manual isn't part of the image processing workflow

**Comment by Nilvus** [comment]
As I work on the UI, cluttering is an important thing. And duplicate something like that, that most users will rarely use, is really not good. So, for me, it's a no go there. The ? icon is there since years and nobody before you here, complains about that. So, this time, I'm sorry but this will be a FR I will close.
Seeing this icon is not so difficult. Or if we go that way, as this icon is beside the settings one, maybe we should also add setting icon on each module too. Just a bad idea.

Of course, if you hide a bar with icons, you will not see them. The issue is not the icon or this feature, just the cause of hide the topbar. By default, that bar is displayed. No UI could take care of all users workflow and how they use/learn it. Of course, things could be improved but not all cases could be considered.

**Comment by SoupyGit** [comment]
> maybe we should also add setting icon on each module too. Just a bad idea.

That indeed would be a bad idea, because each module does not have a unique section in settings. That also makes it a completely invalid argument for this topic, because each module does have a unique section in the manual.

> Of course, if you hide a bar with icons, you will not see them. The issue is not the icon or this feature, just the cause of hide the topbar.

Well, the question is not whether a solution currently exists. It is whether the current solution is better than the proposed solution. If the idea is to make something easy for new users, and the current solution can be hidden, then that makes it not easy for new users. Proposed solution solves that.

But I didn't know about this feature even when it wasn't hidden (eg when I was in lighttable), so again, we must ask, is that just my experience, or is that common to all new users. If common to all new users, then current solution is not working.

Way to find out might be to ask new users, eg on pixls. 

> And duplicate something like that, that most users will rarely use, is really not good. 

1) it's not for most users. It's for ALL new users. You want them to read the manual right?
2) I am not proposing a duplicate. If this solution was superior, it would replace the existing solution.

> The ? icon is there since years and nobody before you here, complains about that. 

Maybe nobody complains about it, because like me, they didn't know about it. Or because unlike me, they didn't consider an alternate solution.

Keep in mind, I think that current solution is better than nothing, and great devs have already considered this point. So my proposal is not really a complaint. Just a search to see if something can be improved.
