### ISSUE TITLE
Allow to print to file (jpg, png, ...) in print module

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#12874]
**Is your feature request related to a problem? Please describe.**

The print module is great, but I hardly need to print these days. However, I often need to make compositions/collages of several images to use them as preview for a collection of images or because the images are related. Typically I am using inkscape or scribus for these, but most of the time, the print module would be much more appropriate for this task. Therefore I wonder if it would be possible to have a print to file option. For pdf, there are external solutions (“PDF printer driver”, but I was not able to find one that prints to jpg. Furthermore, having it inside darktable would have the additional benefit that the print module would become useful on OSs without cups.

**Describe the solution you'd like**

Option to print to <image format> in print module.

**Alternatives**

Continue using inkscape/scribus or finding a jpg printer driver for cups.

**Comment by dtorop** [comment]
Just noticing this now. This seems to me an interesting idea. When I come back out from being semi-swamped, I'd be curious to work on this. As it could be part of generally giving attention to the print view. And the more people without printers who use the print view, the more likely that the code will get more attention!

**Comment by TurboGit** [comment]
@dtorop : I've assigned this to you then.

**Comment by spaceChRiS** [comment]
@dtorop: That's great news! If there is something how I can support, please let me know (e.g. testing, some useful presets, …).

**Comment by dtorop** [comment]
Absolutely. It will be a bit though before I get to it!

**Comment by dtorop** [comment]
Yes! I'm getting back to looking at print view now, though I don't think this will be the first piece I get to...

**Comment by spaceChRiS** [comment]
@dtorop, many thanks anyway, however, the “activity” was rather meant for the bot than for you. Hope you did not feel offended.

**Comment by dtorop** [comment]
@spaceChRiS: Not at all! Happy that you still are interested in this work (as am I).
