### ISSUE TITLE
Sony A850/A900 RAW not correct

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12883]
RAW from Sony A900 can be opened but have broken demosaic (colors), very green:

![image](https://user-images.githubusercontent.com/467069/201493637-b79a5d17-fd67-4253-9a45-de83163d0369.png)

The sample can be taken from here:

https://www.photographyblog.com/pages/reviews/reviews_sony_a900_3.php

Found that just by chance when testing some PR.

I don't see this camera as being flagged as missing samples, so I would expect it to be supported.

**Comment by TurboGit** [comment]
Forgot one important point, this image was read correctly with darktable 4.0.1.

**Comment by TurboGit** [comment]
@kmilos : Can you help here? The first bad commit is the rawspeed update:

```
4989d63a1d63ad64de78b441e45eb98cb6f36cb9 is the first bad commit
commit 4989d63a1d63ad64de78b441e45eb98cb6f36cb9
Author: Roman Lebedev <lebedev.ri@gmail.com>
Date:   Tue Nov 8 14:40:31 2022 +0300

    RawSpeed submodule update
```

So something has broken this camera in rawspeed.

**Comment by LebedevRI** [comment]
I know what is going wrong.

**Comment by TurboGit** [comment]
Thanks Roman!

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/rawspeed/commit/7cc17db266c76474c3fdd51a3cea875dc8a30184

**Comment by TurboGit** [comment]
@LebedevRI : Thanks, tested and working on my side. You can merge in stable branch.

**Comment by LebedevRI** [comment]
@TurboGit for my reference, when is next rc planned? (i thought there was one already, but guess not)

**Comment by TurboGit** [comment]
@LebedevRI : There is no RC since years :) The next step is string freeze at end of month and full freeze mid-december.

**Comment by TurboGit** [comment]
To add a bit of context, the RC is not much useful now as we have nightly builds used by many users and also many others users are compiling from sources. So we do get feedback during all the developments phases.

**Comment by kmilos** [comment]
> as we have nightly builds

Windows only for now... However, there are also "unofficial" weekly macOS builds shared on discuss.pixls.us...

**Comment by TurboGit** [comment]
@LebedevRI : Do you have any plan for the merge? I think before the end of the month would be good.

**Comment by LebedevRI** [comment]
Yes, i know.

**Comment by LebedevRI** [comment]
Hopefully, everything should be good now.
https://github.com/darktable-org/darktable/commit/839124827363b2a9233a7adfafd7a8908b469437

**Comment by TurboGit** [comment]
Confirmed, all good on my side now. Thanks @LebedevRI!
