### ISSUE TITLE
collections module: shown part of list of film rolls not corresponding with position of vertical slider

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#12885]
**Did you buy darktable from an application store ?**
no, self build from current master

**Describe the bug/issue**
See title

**To Reproduce**

- have a list of dozens of film rolls
- scroll down to a film roll in the middle of the list
- select a film roll
- select an image from this film roll (screenshot 1)
- goto darkroom
- **select another image from the film strip in darkroom (important)**
- switch back to lighttable
- see that the vertical slider in collection module remains at it's correct position but the entries shown are now mistakenly from the top of the list. (screenshot 2)

**Expected behavior**
Shown part of the list should remain at the position of the selected film roll, should **not** jump to top of list.

**Screenshots**
![correct](https://user-images.githubusercontent.com/104291381/201516224-d7396195-b30e-444c-9919-df7e05bc8769.png)
screenshot 1 : correct part of list of film rolls shown

![wrong](https://user-images.githubusercontent.com/104291381/201516260-6cd8c97e-c788-46ae-8e8a-ef01d410ff4c.png)
screenshot 2 : top of list of film rolls shown after return from darkroom

**Which commit introduced the error**
unknown, possibly long ago

**Platform**

darktable 4.1.0+978-g88596f5e5
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.141.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by Nilvus** [comment]
Confirmed, I reproduce too and I think it's quite recent, probably few days only. I process a lot of images since a month and only notice that those days.

**Comment by Nilvus** [comment]
I'm even wondering if issue I posted recently could be related: #12713

They all have same origin: switching back from darkroom lost collections list size and position. @AlicVB: if you have time and ideas for this one.

**Comment by AlicVB** [comment]
Confirmed... and what is even more strange is that the scrollbar is at the right position...
I'll try to have a look without too much promise ;)

**Comment by pehar1** [comment]
Perhaps worth mentioning: if you are in the state of screenshot 2 (top of list shown)

-  hover the mouse over the scrollbar
-  scroll one tick up or down

and the shown part of the list gets correct again.
