### ISSUE TITLE
Export Geotag on Mac M1

### ISSUE THREAD

**Issue by gravagnani** [darktable-org/darktable#12897]
**Description**
I'm using Darktable on Mac M1.
The Geotag added with darktable is not exported in he final JPG file.

**To Reproduce**
1. Edit a RAW image
2. Open Map tab
3. Drag the image to a map location
4. Export the image

**Expected behavior**
The JPG result should have the Geotag in EXIF data, but it does not.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1.1
* OS                : Mac OS 13.0 (Apple M1)

**Comment by TurboGit** [comment]
What about the doc?

https://docs.darktable.org/usermanual/development/en/module-reference/utility-modules/shared/export/#metadata-preferences
