### ISSUE TITLE
4.0.1 release notes claims Nikon D3s is unsupported

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#12899]
Release notes for 4.0.1 states the following:
### Suspended Support

No samples on raw.pixls.us
......
- Nikon D3S
......

Which is incorrect since all required samples are present and has been since 2022-02-13.

BTW. Same state seems to be for D1H and D2H as well.

**Comment by kmilos** [comment]
Please search before opening new issues.

This will be handled in the upcoming 4.2 release.
