### ISSUE TITLE
Can darktable app patch/draw a region with its surrounding

### ISSUE THREAD

**Issue by abdulbadii** [darktable-org/darktable#12891]
**Is your feature request related to a problem? Please describe.**
Yes
The urgent need is to have OSS image editor that can patch a region with it surrounding

**Describe the solution you'd like**

It'd be so wonderful if darktable, an OSS application, have plugin that can perform draw/patch a region with surrounding

**Comment by MStraeten** [comment]
what exactly do you expect? If it’s about retouching then darktable offers a couple of options, see https://docs.darktable.org/usermanual/4.0/en/module-reference/processing-modules/retouch/ 
But it’s a raw processor, not a drawing tool,like gimp or krita

**Comment by abdulbadii** [comment]
That's it, thanks much!

**Comment by abdulbadii** [comment]
How to have it, do we must install the retouch module first, how to do?

**Comment by MStraeten** [comment]
Have you read the manual? did you check what retouch is capable of? what additional information you can give so it‘s worth to reopen the issue?
