### ISSUE TITLE
Right-click on quick access icon in darkroom make darktable crash

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#12898]
**Describe the bug/issue**

Thanks to #12890 issue, by testing to reproduce, I have found an issue introduced recently on quick access panel. It's no more possible to add settings in quick access panel. Trying to access menu make darktable crash. This issue had been introduced just few days ago.

**To Reproduce**
1. on darkroom, have quick access panel enabled
2. Right-click on quick access panel
3. darktable crash

**Expected behavior**

Of course, no crash and have menu to add settings

**Which commit introduced the error**

Git bisect point to commit: https://github.com/darktable-org/darktable/commit/822b120616a66d84e6d1dc4bdc5eaa9ffdbcb336

So @AlicVB: this one is for you I fear.

**Comment by dterrahe** [comment]
This could very well be due to #12829. Let me have a look first.

**Comment by Nilvus** [comment]
@dterrahe: thanks but git bisect point to commit I pointed and @AlicVB is already on that issue. When tested last commit in master related to your PR, I had no crash. But maybe I made an error on updating/testing as your PR has been merged just before @AlicVB PR.

**Comment by dterrahe** [comment]
bisect can give spurious results sometimes. I already got a fix; will submit in a little while.

**Comment by Nilvus** [comment]
> bisect can give spurious results sometimes. I already got a fix; will submit in a little while.

Indeed. And your PR is more related to QAP than @AlicVB one. Good to read you have a fix.

**Comment by AlicVB** [comment]
Great... a bug that assigned to me that is solved automagically during the night :)
Thanks a lot @dterrahe !

**Comment by dterrahe** [comment]
You were completely blameless!
