### ISSUE TITLE
crash when deleting a form in retouch module, section wavelet decompose

### ISSUE THREAD

**Issue by jpverrue** [darktable-org/darktable#12906]
**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'darkroom'
2. Click on 'retouch module'
3. Add a form in one merge level, a circle for example
4. Play with this form
5. Remove this form with right click
6. Darktable crash

* darktable version : 4.1.0+1007~g048b55b67
* OS                :  Linux - Kernel 6.0.8-1-default
* Linux - Distro    : openSUSE Tumbleweed 20221113
* Memory            :  16 Gb
* Graphics card     :  Intel 
* Graphics driver   :  NEO
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              : xorg-x11-server-21.1.4-5.1.x86_64
* Desktop           : kde plasma 5.26.3-1.1 
* GTK+              :  gtk3 3.2.1-1.1
* gcc               : 12-2.4
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **not tested**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? **yes**
 - What lua scripts start automatically? **OpenInExplorer**
 - What lua scripts were running when the bug occurred? **none**
[PXL_20221023_150901562_02.dng.xmp.txt](https://github.com/darktable-org/darktable/files/10011982/PXL_20221023_150901562_02.dng.xmp.txt)
[darktable_bt_WQPXV1.txt](https://github.com/darktable-org/darktable/files/10011993/darktable_bt_WQPXV1.txt)

**Comment by dterrahe** [comment]
Possibly linked to #12738

**Comment by jpverrue** [comment]
Thank you both for your quick response. This bug is perfectly solved.
