### ISSUE TITLE
Delay in disappearing between the overlay translucent box and the info in full screen and culling view.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#12902]
**Describe the bug/issue**
When I use the full screen view, or the culling view in the lighttable, the overlay box have an undesired effect. If I drag the mouse slowly out of the area to hide the overlay box, the translucent box disappears but the info remains some seconds, some kind of delay between the translucent box and the info. 

**To Reproduce**
1. Go to lighttable
2. Click on any image and use "f" key to view in full screen view
3. Go out slow of the area where the overlay box must disappears.

The same happens in culling window.

**Expected behavior**
The overlay box with the info must disappears at the same time.

**Screenshots**

Normal visualization of the overlay box with all the info in full screen.

![Screenshot from 2022-11-14 18-49-06](https://user-images.githubusercontent.com/67672868/201793805-1e335b81-8ee1-47cf-a1cd-03b4d704244b.png)

Visualization of the issue. The overlay translucent box disappears but the info remains visible in full screen.

![Screenshot from 2022-11-14 18-49-17](https://user-images.githubusercontent.com/67672868/201793872-f6de6140-0187-4246-95fc-dbff36972f3d.png)

The same happens in culling window

![Screenshot from 2022-11-14 18-52-03](https://user-images.githubusercontent.com/67672868/201794092-735d2916-d0d6-4819-a818-e1a1e341d24c.png)

**Which commit introduced the error**
Not sure.

**Platform**
Fedora 36

darktable version : 4.1.0~git997.49764adb-8576.1
OS: Fedora release 36 (Thirty Six) x86_64 
Host: Z390 AORUS MASTER 
Kernel: 6.0.8-200.fc36.x86_64 
Uptime: 2 hours, 34 mins 
Packages: 3431 (rpm), 42 (flatpak) 
Shell: zsh 5.8.1 
Resolution: 3840x2160 
DE: GNOME 42.6 
WM: Mutter 
WM Theme: WhiteSur-dark-solid 
Theme: WhiteSur-dark-solid [GTK2/3] 
Icons: WhiteSur [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA GeForce GTX 1070 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 5671MiB / 32028MiB
Graphics driver   : NVIDIA Driver Version 515.76
OpenCL installed  : Yes
OpenCL activated  : Yes

**Comment by difrkaguilar** [comment]
Confirmed in Mac OS X too 

OS version: 10.15.7
darktable build: 4.1.0+860~g64a61e52e

**Comment by gi-man** [comment]
At first I was not able to reproduce, but changing the overlays to the not permanent ones does reproduce it. 

Fedora 36, current master

**Comment by dterrahe** [comment]
Depending on the mouse position, the background is shown or not. So if you move the mouse further off screen, first the background disappears and then a little further also the text. If you stop moving the mouse, after a delay they time out and disappear as well. The "delay" in the issue title is in _distance_, not in _time_. (at least, that's what I am observing)

**Comment by TurboGit** [comment]
Please @AlicVB can you have a look. I've tried to understand what is going on, but failed lamentably :( All works fine expect if you move the mouse outside the image area on the top part of the image!

I found one thing suspicious but this does not seems to be the issue at hand.

You're using the same callback for enter/leave image and event-box:
```

    g_signal_connect(G_OBJECT(evt_image), "enter-notify-event", G_CALLBACK(_event_evt_enter_leave), thumb);
    g_signal_connect(G_OBJECT(evt_image), "leave-notify-event", G_CALLBACK(_event_evt_enter_leave), thumb);

    g_signal_connect(G_OBJECT(thumb->w_image), "enter-notify-event", G_CALLBACK(_event_image_enter_leave), thumb);
    g_signal_connect(G_OBJECT(thumb->w_image), "leave-notify-event", G_CALLBACK(_event_image_enter_leave), thumb);
```

But when you LEAVE the image you ENTER the event-box (and the other way around too).

And the callback is using the ENTER state to change the flags for prelight object:

```
static gboolean _event_image_enter_leave(GtkWidget *widget, GdkEventCrossing *event, gpointer user_data)
{
  dt_thumbnail_t *thumb = (dt_thumbnail_t *)user_data;
  _set_flag(thumb->w_image_box, GTK_STATE_FLAG_PRELIGHT, (event->type == GDK_ENTER_NOTIFY));
  return FALSE;
}
```

But again, this is not the issue at hand...
