### ISSUE TITLE
[RFC] : rework / simplify the workflows support

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12917]
In darktable we have multiple workflows possible. We want to clean-up the setup for those as it becomes confused especially since the introduction of the new Sigmoid module.

### Current settings:
- preferences: auto-apply pixel workflow defaults : **scene-referred** / **display-referred** / **none**
- preferences: auto-apply chromatic adaptation defaults : **modern** /  **legacy**
- module groups : **all** / **default** / **beginner** / **display-referred** / **scene-referred**

### What we really have:
- display transform : **filmic** / **sigmoid** / **base-curve**
- chromatic adaptation / wb : **color calibration** / **white-balance**

### Proposals:

For preferences (single entry):

workflow : 
- **scene-refrerred (filmic)**
- **scene-referred (sigmoid)**
- **display-referred (legacy)**
- **none** 

And we use : **color calibration** for both scene-referred workflow / **white-balance** for display-referred. This is implied and this is the only workflows darktable setup automatically. A user with different needs (so probably have a good technical background) can mix whatever he want by selecting **none** and adding auto-apply presets for whatever module he want to use.

For module groups:
- keep **all**
- remove default
- keep **scene-referred** (which is also the default)
- keep **display-referred**
- keep **beginner**

Thoughts?

**Comment by TurboGit** [comment]
@jandren : we have discussed that while reviewing the sigmoid code, so you probably want to discuss this.

**Comment by jenshannoschwalm** [comment]
What about the **exposure** module. Should be enabled for both scene workflows. Any need for a specific sigmoid preset?

**Comment by HSUfineprint** [comment]
Workflow in preferences, "display-referred **(legacy)**" might be a good mind link from chromatic adaptation defaults menu. So that will be:
scene-refrerred (filmic)
scene-referred (sigmoid)
display-referred (legacy)
none

And I really want to see sigmoid as default. This module is way more easy to use for beginners. As for experts or filmic lovers, it's just a single click. They definitely know how to change settings.

**Comment by TurboGit** [comment]
> display-referred (legacy)

Noted, indeed a good point.

**Comment by TurboGit** [comment]
> Any need for a specific sigmoid preset?

I see no need for a default preset as the default Sigmoid has been set to be good by default. @jandren will give a definite answer to this.

**Comment by TurboGit** [comment]
> What about the **exposure** module. Should be enabled for both scene workflows

I would say so. When I have tested Sigmoid I had never the need to change exposure which was set for Filmic.

**Comment by gi-man** [comment]
I agree with the workflow suggestions. I struggle to think how to select what belongs in the "beginner" module. I would suggest removing it too.

**Comment by TurboGit** [comment]
@gi-man : The "beginner" module set preset has a limited set of modules for beginners to avoid being overwhelmed by the set of module darktable propose. I'm not sure if this is a success and if the goal has been reached or not, but at least it was the intention for it.

**Comment by gi-man** [comment]
I get the goal, I just dont know if it was successful. I think it is impossible to know without some user feedback. 

Thinking more about it, the Quick Access is in essence providing a limited set of modules (or module settings) that you should make it easy for beginners.

**Comment by darkbasic** [comment]
> I'm not sure if this is a success and if the goal has been reached or not, but at least it was the intention for it.

I don't think it is useful at all. It will create even more confusion unless you will create two different modules: "beginner scene-referred" and "beginner display-referred". I suggest to remove it.

**Comment by jandren** [comment]
Sigmoid has the same expectation about exposure as filmic so no new preset is needed.

**Comment by TurboGit** [comment]
See #13234.

**Comment by TurboGit** [comment]
I've kept the beginner group for now, but I'm ok to remove it, I have no strong opinion so more feedback needed.
