### ISSUE TITLE
Can't delete history stack

### ISSUE THREAD

**Issue by C00gan** [darktable-org/darktable#12912]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

I switched from Xubuntu to MX Linux and can't delete the history stack neither in lighttable when hitting discard history nor in darkroom when hitting delete image history. When i press original in the history stack and make a change in any module it gets listed as a new number in the history stack above the pre-automated entries which are not deleted and not as number 1 above original as it should be. I've tried this in version 3.6 and 4.0..

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

Empty history stack

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0-1~mx21+1/4.0.0-0.1~mx21+1
* OS                : Linux - kernel 5.10.0-19-amd64
* Linux - Distro    : MX-21.2.1_x64 Wildflower
* Memory            : 8 GB
* Graphics card     : NVIDIA GT200GL
* Graphics driver   : nvidia v: 340.108
* OpenCL installed  : 340.108-11~mx21
* OpenCL activated  : yes
* Xorg              : 1.20.11
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version 4.0.0-0.1~mx21+1**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? no
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by Nilvus** [comment]
First, please think about removing unuseful informations. It will be easier to read.
Then, that's not an issue but wanted. Having some steps is necessary to have minimal correct display of the image. Clicking on original, then clicking on compress will do same thing (without the change of the module you do). And it's necessary. This won't change.

Empty history stack completely is not possible and not wanted. I suggest you to read manual about history: https://docs.darktable.org/usermanual/development/en/module-reference/utility-modules/darkroom/history-stack/.

All modules with full icon (![image](https://user-images.githubusercontent.com/45535283/202268882-07fa54f7-72d0-48b9-8700-0efa957fb826.png)) are necessary and can't be disabled. If you have presets to be applied automatically, they will (like a new import).

There's no issue. I close but of course, feel free to complete what you want if needed.
