### ISSUE TITLE
Can't hide navigation module

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12918]
Open the darkroom view. Hide the navigation module with Ctrl+Shift+n. Exit the darkroom view and re-enter. Navigation module reappears.

darktable 4.1.0+1017~g7856e99d0 on ArchLinux.

This was fine a couple of days ago (this was reported by another user on IRC and I tried it on a fairly recent build, couldn't reproduce, upgraded and found the bug) so some recent commit has broken it.

**Comment by dterrahe** [comment]
I probably broke that; let me have a look.

**Comment by TurboGit** [comment]
> Hide the navigation module with Ctrl+Shift+n

Good you're using this, I never do...
