### ISSUE TITLE
Slideshow completely freezes Darktable, must be killed

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#12924]
**Introduction**
Accidentily hitting the 's' key turns the screen black and freezes the computer at 100% cpu power.
It does not respond to any key. 
The process Darktable must be exited. 

Related: Obviously I never use Darktable in slideshow mode, as is completely freezes the computer.  

To reproduce: start the slideshow.

Workaround: Remove the 's' shortcut key reduces the risk of accidentily triggering the slideshow.

Preferred solution: Remove the entire slideshow. Darktable is a very fine raw-editor, it doesn't have to do unrelated things like slideshows. Other programs are much better at that; focus, reduce code, complexity and maintenance.

**Comment by TurboGit** [comment]
How long have you waited? This is working on my side, while the first image is rendered and depending on the number of heavy module in the history it may take sometime.

> Preferred solution: Remove the entire slideshow. 

Can people stop thinking that darktable is their tool!!!!! Can't you understand that we all have different needs and workflow?
