### ISSUE TITLE
Enable copy of a tag

### ISSUE THREAD

**Issue by wwwFrank** [darktable-org/darktable#12922]
Please enable the **copy of a tag** in _lighttable / tagging_ as text into the clipboard.
The only context (mouse right click) on a tag is "_detach tag_".
Sometimes I need the text of a tag from a picture for publication, for example the latin name of an insect. But it is not possible to copy the tag from the picture.

**Comment by Nilvus** [comment]
You have "copy to entry" when right-clicking on a tag. You will then have it on entry field just above. Check menu:

![image](https://user-images.githubusercontent.com/45535283/202269851-053b90b3-1265-4325-b68d-35f8c8dec53a.png)

**Comment by Nilvus** [comment]
And please precise infos asked on template, especially darktable release for such request.

**Comment by wwwFrank** [comment]
Sorry,
I use Darktable 4.0.1 from ppa.launchpadcontent.net/ubuntuhandbook1/darktable/ on Ubuntu Linux 22/04 LTS.
But this feature was not available in any version of DT until now.

**Comment by pehar1** [comment]
This function has been around for a long time. Please also use the manual: https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/shared/tagging/

> The pop-up menu entry “copy to entry” can be used to copy a selected tag to the text entry box. You can then edit this name and press Enter to create a new tag with that name, making it easy to create multiple tags with similar names.

And, of course, you can copy/paste the (hierarchical) tag from entry box.

**Comment by wwwFrank** [comment]
We are talking about different elements.
After export of a picture I need the tag of this picture for publication. 

![Bildschirmfoto vom 2022-11-17 09-47-12](https://user-images.githubusercontent.com/1278291/202405909-9536e6be-a49e-49e8-b89d-35095407b6ea.png)

What I mean:
1. Select a picture
2. Select a tag in the upper list of tagging-module
3. right-mouse-click to copy the text into the clipboard.

So it is **sure** to get a tag, that is **assigned to the selected picture**.

What you mean:
"_copy to entry_" is only possible in the second list of the tagging-module.
This list is **not** filled by selecting a picture but by **typing** in a part of a tag.
Steps:
1. select a picture
2. read the tag, keep it in memory
3. type a part of the tag in the entry to get a list in the second part of the tagging module
5. with long hierachical tags you can't see the complete tag in the first part because its longer then the width of the element
6. the part you type must lead to a **unique** tag
7. select a tag
8. right mouse click - "copy to entry"
9. select the text in the entry
10. right mouse click "copy" or Cntr.+c to copy the entry into the **clipboard**

This lasts much longer.
You can make mistakes and get a tag, **that is not assigned to the selected picture**.

Example, 2 Tags:
Tiere|Spinnentiere|Webspinnen|Baldachinspinnen (Linyphiidae)|Gartenbaldachinspinne (Linyphia hortensis)
Tiere|Spinnentiere|Webspinnen|Baldachinspinnen (Linyphiidae)|Gemeine Baldachinspinne (Linyphia triangularis)|Weibchen

English: Animals|Spider| ... |German Name (latin name)|female

You have to type "_triangularis_" to get a unique result.
By typing "Linyphia" (family) or "Baldachinspinne" (german name) you get more then one match.

**Comment by wpferguson** [comment]
Here's a lua-script that will satisfy this issue.  It adds a text window called `tag text`.  If an image is selected or moused over the attached tags are displayed.  If the image is selected, the text in the `tag text` module can be copied and used elsewhere.

[tag_text.zip](https://github.com/user-attachments/files/17336782/tag_text.zip)
