### ISSUE TITLE
Fujifilm GFX 50s

### ISSUE THREAD

**Issue by cntzr** [darktable-org/darktable#12925]
I'm using darktable 4.0.1 on Arch Linux. The RAW files from my Fujifilm GFX 50s get cropped on the right side by around 1.000 pixels. Looking for a solution I found a thread from last year on discuss.pixls.us asking for samples for this camera. I uploaded a set of samples today at raw.pixls.us. I'm afraid that I messed up the filenames and the compression and crop modes in the form. But the EXIF data and the previews should help to correct it.

Please send me a reply if the samples are useless or you need more of them. Since I can't use darktable very well with the current crop I will do my best to provide you with any samples to fix it.

**Comment by LebedevRI** [comment]
I believe this was fixed some time ago.
Please reopen if still reproducible in master.
