### ISSUE TITLE
Image Selection Feature (Culling Mode)

### ISSUE THREAD

**Issue by qystan** [darktable-org/darktable#12937]
**Is your feature request related to a problem? Please describe.**
Add/extend the Culling Mode to add an Image Selection Mode feature.

The Culling Feature is useful for culling bad images, however, it does not work for selecting the 'best" image from a series of shots.  

Although the Fixed Mode allows multiple pictures to be placed side by side, the images get smaller with more images.  Reducing the images displayed to lesser or 2 also does not work as all the images are scrolled and does not allow a choice reference to be kept stationery for comparison against the rest, especially needed when there are many similar images.

**Describe the solution you'd like**

1.  In the Image Selection mode, set the screen to a 2 image setting with the left pane as a non-scrolling image pane.
2.  The Star/Colour rating available to tag the left image to tag/identify the selected image.
3.  Allow the user to double click to 'Select' the preferred image and move that image to the left pane.  
4.  Right/Left arrow scrolls the images on the right pane for user selection per Step 3.

Alternative solution can be with the 2 panes selected via the Tab key.  The image in the non-selected pane is frozen and the selected pane is scrolled by the arrow keys (whichever is easier to implement).

**Alternatives**

Using the Culling Mode with 2 images but with limitations explained above.

**Additional context**

The feature is available in Adobe Photoshop Elements which I have found to be very useful.

**Comment by qystan** [comment]
Thanks for the quick reply.
The filmstrip doesn't always work as the images are quite small, especially when deciding on small subjects/details (like birds).  Omitted to mention that in Photoshop Elements, zoom in/out is supported while in the side-by-side view.

Here's a screenshot of the Photoshop Elements screen.

![Selection Mode](https://user-images.githubusercontent.com/63985586/202827769-6673de98-ea17-4274-a365-8df4b76bb04c.png)

**Comment by ralfbrown** [comment]
Ctrl-Scroll to zoom in/out while in culling mode.  When zoomed, dragging the mouse in one image moves all of them together.

**Comment by Nilvus** [comment]
Filmstrip size could be adjusted (just move cursor on top of filmstrip thumbnails). Thumbnails selected indicator is there, mving with let/right arrow too as well as zoom/pan...
All you ask for is already possible. I suggest you to read manual so.

**Comment by qystan** [comment]
Apologies, the request isn't well written.  

Re-submitted under  #12944.
