### ISSUE TITLE
Slideshow not transitioning to the next image automatically

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#12930]
**Did you buy darktable from an application store ?**

OSB Current Master

**Describe the bug/issue**

I was investigating an issue reported in Pixls.us and noticed that the slideshow is not moving to the next image automatically. 

**To Reproduce**
Select images in lighttable
Press S to start a slideshow
First image shows but it never cycles to the next image. I waited for more than 2 minutes.
Pressing arrow key does transition to the next image.

**Expected behavior**
After some time (per the preference settings), the next image in the group should be shown.

**Platform**
* darktable version : 4.1.0~git1029.5c7fab96
* Linux - Distro    :  Fedora 36 KDE
* Memory            :  16Gb
* Graphics card     : Nvidia 3060
* Graphics driver   :  5XX
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              :  X11

**Additional context**

I used -d perf and I noticed that 2 images are processed (out of ~10 in the selection). Both are using [export]. If I press the arrow key, the image changes to the next one and a new image is processed via [export].

OpenCL On or Off made no difference other that it takes longer to load the images (normal with Export). 

PS - Why use Export for slideshow instead of something less resource intensive like using Full Preview Layout (f)?

**Comment by TurboGit** [comment]
> First image shows but it never cycles to the next image. I waited for more than 2 minutes.

In the doc it is said:

```
spacebar             start and stop auto-advance mode which automatically switches
                     to the next images every five seconds by default.
```

And there is many more feature to be discovered in the manual:

https://darktable-org.github.io/dtdocs/en/slideshow/usage/

> PS - Why use Export for slideshow instead of something less resource intensive like using Full Preview Layout (f)?

The last proposed version (see PR #12932 ) do not use high quality export and have a double-buffer support displaying a preview and then the final image.
