### ISSUE TITLE
Culling Layout in Fixed Mode - Additional Feature

### ISSUE THREAD

**Issue by qystan** [darktable-org/darktable#12944]
**Is your feature request related to a problem? Please describe.**
Feature request was unclear in Issue #12937.  Re-stating the request.

The Culling Layout in Fixed Mode provides for side-by-side comparison of images, this mode is useful as images can be zoomed (if set at 4 or less images).  However, when images are scrolled, it scrolls the images in all the panes.

Scrolling all images loses side-by-side comparison of a choice image against the other to select a "best" from the lot. 

**Describe the solution you'd like**

1. Add feature to freeze one image pane and only scroll the image in the other panes.  This keeps the selected image static and images scrolled in the others to provide side-by-side comparison.

In use, the user selects/freezes the next better image, scrolls on the other panes and repeats until a "best" image is found where the user sets a rating star etc to mark/tag it.

(Would this be simpler to implement if the display images are limited to 2?)

![Untitled](https://user-images.githubusercontent.com/63985586/202876284-b538e720-8c06-4c52-a44f-662ee54de33c.png)

**Alternatives**
1.  Use existing Culling in Fixed Mode and select/tag one out of every set of images.
     - Filter and repeat for filtered images until final remaining.

 
**Additional context**

**Comment by Nilvus** [comment]
I'm not sure to understand (even though seems clearer than previous issue) but do you just mean that you would like a way to pin an image and just allow to change the other?

**Comment by qystan** [comment]
Yes.  

> I'm not sure to understand (even though seems clearer than previous issue) but do you just mean that you would like a way to pin an image and just allow to change the other?

**Comment by Nilvus** [comment]
@AlicVB: if in future weeks or months, you want to improve culling mode. For such thing, I would see the simple pin icon on top right of the image when hovering it (on left and right one) and if an image is pinned, the pin icon should remain visible even if the image is not hovered (to avoid forgetting it) and, of course, the image is automatically unpinned if the user exit culling mode.

@qystan: your feedback about this proposal is of course welcomed. Just think that such feature will be added only if a developer is ok to spent time on it (@AlicVB is pinged here only because he's the culling feature developer).

**Comment by qystan** [comment]
I have figured a work-around for this.  

While in culling mode, instead of the tagging the preferred image which will move it away from the filtered group and basically end further side-by-side comparison with it.  I use a reverse selection method which basically tags the unwanted/not-preferred image.  This moves the unwanted image away from the group and maintains the preferred image on the screen and the next image is pulled in for comparison.

The process:

1.  Promote all the images to 3-stars (as an example but it is not necessary).
2.  Invoke Culling Layout in Fixed Mode with 2 image panes.
3.  On the unwanted image, either tag as Reject or give it a star rating to identify it.  The tagged image will be moved away leaving preferred image on the left pane and the next image is scrolled in on the right.
4.  Repeat until the last of the image series, 
5.  Tag the preferred image with a higher star rating and down tag the other.
6.  The screen will now show the first 2 images of the next series of images.  Repeat as above.

Hope this is helpful for others and perhaps avoid having to work the suggestion.

**Comment by Solarer** [comment]
Although OP found a workaround that satisfied his requirements, is this view mode with 1 pinned image something that would be merged if someone where to develop it?

I am asking because I could see myself using this a lot and I grew familiar with the culling codebase. So could develop this once my current work is finished.

**Comment by wpferguson** [comment]
I wrote a script that pretty much did the same thing.  I froze the image on the left and kept changing the image on the right until I found a better one, then the image on the right got moved to the left and frozen.  After I had gone through all the images, whatever image that was on the left was selected when I returned to lighttable.

I did have a feature where you could open the left in darkroom and snapshot the right and overlay it to compare the differences.

The collection rewrite broke the script (that's how I was manipulating the images), and I just haven't got around to rewriting it.

So yes, if that feature was there I would use it.

**Comment by CarloDePieri** [comment]
I would also love to pin an image (the 'current pick'), say to the left, while the others keep moving on the right... and when a new candidate is found, pinning the new candidate would move it to the left and move the right one to the next image in the strip/selection.

This is how I was culling in Lightroom, so I imagine it's a fairly common workflow.
