### ISSUE TITLE
image information module : wrong reading for longitude if several images with different longitudes are selected

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#12947]
**Did you buy darktable from an application store ?**
no, self build from git master

**Describe the bug/issue**
Selecting several geotagged images with different values for _longitude_ the _image information_ module shows the value of the first selected image, not _various values_ as would be expected.

**To Reproduce**

1. Select several geotagged images with different values for _longitude_
2. See reading in _image information_ module

**Expected behavior**
reading shoud be _various values_

**Screenshots**
![wrong-longitude](https://user-images.githubusercontent.com/104291381/202895551-d48e5896-efd4-4273-8642-a46160b3cb43.png)

**Which commit introduced the error**
unknown, probably a long time ago

**Platform**
darktable 4.1.0+1018-gdc86ed33c
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.141.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

 - Can you reproduce with another darktable version(s)? **did not try**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Do you use lua scripts? **no**

**Comment by victoryforce** [comment]
I can't reproduce this on my geotagged images.

**Comment by pehar1** [comment]
I did some further tests :

- I also can **not** reproduce this issue (like @victoryforce) if I use images geotagged at shooting time by the camera
- I can reliable reproduce the issue if I shoot **without** geotagging (that means the raw file is **not** geotagged) and then use the _map_ view to subsequently add the geotags in darktable.
