### ISSUE TITLE
Print: Image will not scale to paper

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#12950]
Darktable 4.0.0

I use DT to print photo's.  

Mostly it goes without issues. 

This image will not scale to fill the paper. I can not get it any larger even though there is plenty of space on the right to enlarge it. 
No parameter on the screen will enlarge the image. 
The image is a 1:25 crop.

![Darktable Wont Scale](https://user-images.githubusercontent.com/16322196/202903485-6bbdd835-01ca-4e58-945e-db1932a4b682.png)

Expected behaviour: 
I expect DT scales the picture to the maximum size the paper will accept.

**Edit for extra info:**
I can confirm it is a bug. 
I did this:
- duplicate the image
- discard all history on the duplicate
- try to print the duplicate
After that, both the clean unedited duplicate as well as the version I tried to print will scale correctly to fill the page.

**Comment by TurboGit** [comment]
Maybe you can share the image having issue with the XMP?

**Comment by rekcodocker** [comment]
Here it is. 
Mind you, after the duplicate-and-retry, I can no longer reproduce the issue! 
However, the original edit history is still in the XMP.  I did quite the number of rotation and re-cropping. Perhaps it gives you a clue.

https://cloud.farside.nl/s/KLnH84g5Fj6Y4fG

This link is valid for a week.  Goes without saying that this is for debugging purposes only.

**Comment by TurboGit** [comment]
@rekcodocker : Sure, I understand that it is only for debugging purpose. I'll see if I can understand what is going on there. Thanks.

**Comment by TurboGit** [comment]
@rekcodocker : Sadly I cannot reproduce. I have imported the image and I have pressed 'P' directly to go to the print view and go the image properly centered on the page.

**Comment by rekcodocker** [comment]
I can not reproduce it anymore.  Probably a one time fluke.
Will raise issue again if it occurs.
