### ISSUE TITLE
FujiFilm X-T5

### ISSUE THREAD

**Issue by Bu4xyz** [darktable-org/darktable#12952]
Hi
Could you please add the FujiFilm X-T5 to the supported profiles? I have uploaded three files and hope they have the correct format.
(The X-H2 is the same sensor)

Thanks in advance

**Comment by LebedevRI** [comment]
Thanks for the samples!

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/commit/839124827363b2a9233a7adfafd7a8908b469437
