### ISSUE TITLE
scrolling over filter hamburger popup "new filter" menu adds filters

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#12956]
Presumably since #12849 

1. click on the "hamburger" menu left of "filter" in the top toolbar.
2. move the mouse down to hover over "new filter" line
3. click to open the menu of available filters (this step is not necessary, but that's how I found out; this looks like a combo popup, so the next step seemed logical to me)
4. use the scroll wheel to scroll through the available filters. The popup gets messed up; it looks like it scrolls up, but what actually happens is that one by one the filters get added to the top bar (and removed from the menu)

Expected; scrolling could move the menu up or down as with other popups. Alternatively, scrolling could do nothing. Scrolling should not add items to the top bar.

**Comment by AlicVB** [comment]
OK, in fact that's the "normal" behavior of a bauhaus combobox : scrolling change the selected value (and "validate" it).
So I see 2 options : 
- use a "standard" gtk combobox (but we loose some consistency in the UI, esp. for the colors, icons, ... of the widget)
- add another "option" to bauhaus combobox so scrolling doesn't change the selection
- use another type of widget... to be invented ;)

@dterrahe : what's your opinion on this ? (as you know pretty well bauhaus too)

**Comment by dterrahe** [comment]
- make each row in "shown filters" in the hamburger "menu" a bauhaus combo allowing to change the type of existing selection widgets in the top toolbar. Scrolling/selecting-in-popup both _change_ an existing filter widget, but don't _add_ one. And replace the last widget in the "menu" (which currently _is_ a bauhaus combo) with a simple "new filter" _button_. Which adds a filter widget to the top bar and a bauhaus combo to the menu that can be used to change its type.
