### ISSUE TITLE
Image is not available , CR2, canon eos 2000d

### ISSUE THREAD

**Issue by romanpastu** [darktable-org/darktable#12951]
**Introduction**
When importing a cr2 raw image from canon eos 2000d (supposedly supported per this https://github.com/darktable-org/darktable/issues/3994 ) , it gives an error that the image is not avaiable
Looking like this
![image](https://user-images.githubusercontent.com/43568511/202906107-33117b36-6f96-48c1-9c0d-b81c337910fb.png)

I receive the following error:
`
[rawspeed] (IMG_3666.CR2) virtual std::unique_ptr<rawspeed::RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData*), line 91: No decoder found. Sorry.

**Platform**

* darktable version : 3.8.1
* OS                : Linux
* Linux - Distro    : Fedora 36
* Memory            :  32gb
* Graphics card     :  3060ti
* Graphics driver   :  propietary nvidia
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              :  x11

**Test FIle**
https://www.dropbox.com/s/a1p4on93myrakey/IMG_3666.CR2?dl=0

**Comment by pehar1** [comment]
For me it looks like your image is damaged. The download only has a size of 3.8 MB for a 24 MPixel image, `exiftool` shows only few tags, several of them Apple related, nothing pointing to Canon...

**Comment by romanpastu** [comment]
@pehar1 you are right, the image was corrupted
