### ISSUE TITLE
Assigning a shortcut to scroll presets also scrolls the presets

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#12965]
Attempt to assign Q+scroll to changing the presets on the color calibration module by entering visual shortcut mapping and Q+scrolling on the presets button. If I scroll too much accidentally, then it also starts actually scrolling through the presets.

Subsequent testing reveals that similar happens on sliders and comboboxes.

I would expect the mouse scroll to continue to be captured (and the shortcut not mapped) until the user raises the associated key

**Comment by elstoc** [comment]
One for @dterrahe to investigate

**Comment by dterrahe** [comment]
No need to investigate; this has been the behavior from the beginning, the idea being that the user would get immediate feedback that the shortcut has "taken". Such choices can of course be revisited on the basis of user input, which was actively sought at the time and of which this is the first piece I recall on this aspect. For something higher impact like switching presets it may be less desirable than slightly modifying a slider that the user could well be working with anyway at the moment, hence wanting a shortcut. Either way, I'm loath to touch such central behavior (it would require actively ignoring new input for a while under certain conditions, which may have unintended/unexpected consequences) so close to a release when I can't guarantee availability to deal with bug reports (even if those _are_ filed). So I'm marking this _low priority_ which also creates an opportunity to collect more feedback.

**Comment by elstoc** [comment]
> For something higher impact like switching presets it may be less desirable

Yes it's just something I noticed recently because I was testing presets for dtdocs, and it was very obvious when it happened. I would personally prefer that all shortcuts be disabled while in mapping mode, but I understand others prefer it that way.
