### ISSUE TITLE
4.0 manual inconsistency

### ISSUE THREAD

**Issue by solitone** [darktable-org/darktable#12967]
The [take a well-exposed photograph](https://docs.darktable.org/usermanual/4.0/en/overview/workflow/process/#take-a-well-exposed-photograph) section of the manual (v. 4.0) states that:

_Where possible, you are advised to use **exposure to-the-right (ETTR)** techniques to maximize the amount of data available for processing. As a general rule of thumb, it is safe to **under-expose** all images by 0.5 to 1 EV (by reducing the ISO sensitivity if possible) even if the in-camera preview looks darker than expected (the preview is not the raw data)._

I don't get this. The two points seem contradictory to me. ETTR would imply over-exposure. Is the manual suggesting to over- or under-expose?

Looking at the `exposure module` and the default `compensate camera exposure (-0.3 EV)` selection, I think the manual should suggest to over-expose, but the way is written is not completely clear to me.

**Comment by parafin** [comment]
Manual has its own repository, please post bugs there: https://github.com/darktable-org/dtdocs/issues

But with high-dynamic range scenes ETTR would mean under-exposure, to avoid  clipping, so there is really no bug.

**Comment by solitone** [comment]
Ok, thanks. I posted it there, suggesting that your clarification would be helpful for an easier understanding.
