### ISSUE TITLE
lack of POT msgid of export module's JPEG XL options

### ISSUE THREAD

**Issue by HSUfineprint** [darktable-org/darktable#12978]
**darktable version : 4.1.0+1084~g243819821**

The new file format JPEG XL in export module has some exclusive options, but they and their tooltips did not have corresponding msgid in POT file. Translators couldn't do their works.

They are:
- encoding color profile
- encoding effort
- decoding speed

![JPEG XL export](https://user-images.githubusercontent.com/109933528/203708246-6d4df85b-143d-4eac-a139-6b280c7981b9.png)

**Comment by TurboGit** [comment]
Thanks for reporting. Should be fixed now.

**Comment by HSUfineprint** [comment]
Amazing speed! Thanks as always.

**Comment by HSUfineprint** [comment]
> Thanks for reporting. Should be fixed now.

A strange problem, only "encoding color profile's tooltip" didn't show proper translation. Other options and tooltips are okay.

![tooltip](https://user-images.githubusercontent.com/109933528/203743586-d8192a99-adb5-466c-a5d4-eb4c9713660b.png)

**Comment by TurboGit** [comment]
Should be fixed now.
