### ISSUE TITLE
 Trying to turn two consecutive sets of pictures into two groups produces one large group; unless the first one is collapsed 

### ISSUE THREAD

**Issue by koslowj** [darktable-org/darktable#12982]
Not sure whether this is a bug or a feature ;-)

When working with HDRs, I like to combine the source images and the result into a group. When I have grouped n pictures without closing the group and select  m other pictures in order to make a second group, I end up with one large group of n+m pictures, i.e., the newly selected images are appended to the first group rather than being put into a new group.  I only get the expected behavior (a new group with m images) when I first collapse the first group by clicking the icon on the top right twice, which first opens up all existing closed groups, and then closes all groups.

But when you have two or more groups open and select m other images, the grouping instruction now does produce a new group with m images, as darktable evidently does not know to which open group they should be appended.

OK, I can imagine use-cases where one wants to enlarge an existing group by appending images to it.    But I do find the behavior outlined above inconsistent.

**Comment by emko** [comment]
yea this is really confusing i couldn't figure  it out until i found this post
