### ISSUE TITLE
Sony ILCE-7RM5

### ISSUE THREAD

**Issue by deepbend** [darktable-org/darktable#12985]
This camera is not in the Darktable database therefore will not open the RAW (ARW) mage for editing. DT version 4.0.1.

**Comment by LebedevRI** [comment]
Please do what the placeholder text said to do.

**Comment by deepbend** [comment]
??????? That place holder text meant nothing to me. Can you please explain in simple terms what you are meant to do. The Sony is a new camera model so would not be in the Darktable database yet and so needs putting in by someone who understands this sort of stuff.

    On Thursday, 24 November 2022 at 18:22:58 GMT, Roman Lebedev ***@***.***> wrote:  
 
 


Please do what the placeholder text said to do.

**Comment by kmilos** [comment]
@deepbend You were kindly asked to upload samples to https://raw.pixls.us/, it is a straightforward procedure and nothing to shy away from. There can be no support implemented without available samples.
