### ISSUE TITLE
RFC - make tooltip text monospace (permit proper formatting)

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#12987]
We have in many cases hard time to properly display the tooltip information to be readable/formatted.

Making the font monospace:

```
tooltip label
{
   font-family: monospace;
}
```

Will make this possible for example:

before:
![image](https://user-images.githubusercontent.com/467069/203854505-cac8dc14-2853-45e7-806d-2e17afa44e90.png)

after:
![image](https://user-images.githubusercontent.com/467069/203853482-6040b1b8-8723-4d6c-9e85-d295c2be7361.png)

before:
![image](https://user-images.githubusercontent.com/467069/203853746-c3f33397-4915-4210-8bd8-e2073c559b8c.png)

after:
![image](https://user-images.githubusercontent.com/467069/203854565-d18d1266-823d-4e32-8792-6803c3bc97f7.png)

before:
![image](https://user-images.githubusercontent.com/467069/203854042-f1baac78-6936-4dae-8b6e-a3e71543b052.png)

after:
![image](https://user-images.githubusercontent.com/467069/203854767-a9798475-9cc6-4097-8d68-143b726de9e7.png)

**Comment by dterrahe** [comment]
I think the first example just needs `font-feature-settings: 'tnum'` which was discussed in an issue with @Nilvus and might become default. I think the other doesn't need/benefit from monospace, which is generally considered less attractive.

**Comment by Nilvus** [comment]
I agree with @dterrahe.
And @dterrahe, just as a reminder, I'm waiting your answer to push my fix for the issue you mention here (#12941).

**Comment by TurboGit** [comment]
You really don't find the **after** screenshots more readable??? Maybe just me then... Or wait for others to comment...

**Comment by Nilvus** [comment]
Before are readable for me. Even if after are more readable, using monospace is a no go for me on such parts.

**Comment by Nilvus** [comment]
More, on my side, your proposal do not have same result:

before

![image](https://user-images.githubusercontent.com/45535283/203863705-89272e3e-cebd-45a2-a3cc-090e38baa096.png)

after

![image](https://user-images.githubusercontent.com/45535283/203863671-36bdb26f-9127-4cb7-957f-73983854cdc1.png)

The result is probably different because of font size and/or screen resolution and place for tooltip. So, even if I agree that tooltips readability could be improved, your fix is not good.

Just a thing, where do you find your first tooltip?

**Comment by dterrahe** [comment]
> You really don't find the after screenshots more readable??? 

Oh yes, but you can use newlines and starting spaces without monospace

**Comment by TurboGit** [comment]
As I said, we _can achieve_ what I have put as after. For the screenshots I had hand-edited (fr.po) the tooltip text.

**Comment by TurboGit** [comment]
And those are only example, we also need to have somehow columned display and this cannot be done without a monospace font.

**Comment by dterrahe** [comment]
I can't remember if <tt> in markup is supported in tooltips (or what is required to make it work). If it is, that could maybe be used selectively to make tables rather than "uglifyin" _all_ tooltips...

**Comment by HSUfineprint** [comment]
I agree with @TurboGit, it's annoying for translators. I want to make tooltip more readable too. Fortunately, Chinese character is monospace, but numbers still cause problem. It's hard to align numbers in different lines.

**Comment by TurboGit** [comment]
Let's forget about this...
