### ISSUE TITLE
Directory-Files browser feature.

### ISSUE THREAD

**Issue by jknights** [darktable-org/darktable#12981]
**Is your feature request related to a problem? Please describe.**

Browsing images files is less easy than it could be.
Most computer users browser by /drive/directory/...files.
The interface does not show this as the Default view.
Instead it shows a historical view of directories.

**Describe the solution you'd like**

Allow a user preference to be set that choses the preferred display method...  Drive/directory/..., Historical directory/..., any other option identified as useful.

**Alternatives**

Put in an additional panel that provides a Windows Explorer view or Mac Finder view or Unix terminal command line.....

**Additional context**

Thank you for your consideration of this.

**Comment by deric** [comment]
Might be related to #12907

**Comment by gi-man** [comment]
Keeping the Folder sorting as a default view was added to master in September (https://github.com/darktable-org/darktable/pull/12514). This feature will be available in the 4.2 release in a couple of weeks.

**Comment by Nilvus** [comment]
This is not the goal of a RAW processor. Thus, there's already issue like the one linked by @deric here. It's good to search existing issues before posting. Thanks. I so close this one.
