### ISSUE TITLE
Snapshot - slow processing when select/unselect snapshot

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#12996]
**Describe the bug/issue**
Whenever I select a snapshot, darktable takes a sensitive amount of time to display it.
This behavior doesn't show on dt 4.0.1
For me the main issue with this is that when I use snapshots, I never scroll the ruller when I want to compare images, I just put it in the right and then keep selecting and unselecting the snapshot. For me, this way is more productive when I want to compare subtle changes.

**To Reproduce**
1. Open an image
2. Take a snapshot from an older history entry
3. Select the latest history entry
4. Select the snapshot

**Expected behavior**
It takes a sensitive amount of time to refresh the screen with the snapshot image

**Platform**

* darktable version : 4.1.0~git1088.8781b1fe-1
* OS                : Linux G15 5.15.0-53-generic 59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Linux - Distro    : Ubuntu 22.04.1
* Memory            : 16 GB
* Graphics card     : NVIDIA GeForce RTX 3060
* Graphics driver   : 520.56.06
* OpenCL installed  : OpenCL 3.0 CUDA, SM_20 SUPPORT
* OpenCL activated  :  YES
* Xorg              : X11
* Desktop           :  Gnome 42.5
* GTK+              :  3.24.33
* gcc               :  gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
* cflags            :  (opensuse repo)
* CMAKE_BUILD_TYPE  :   (opensuse repo)

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **no. in dt 4.0.1 the issue isn't present, and selecting/unselecting snapshots is immediate **
 - Can you reproduce with a RAW or Jpeg or both? **not tested**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

Follow logs from master (the one presenting the issue) and from stable (no issue).

[dt-master.txt](https://github.com/darktable-org/darktable/files/10094679/dt-master.txt)
In this log, the entry where dt finishes processing snapshot selecting is 211.390982

[dt-stable.txt](https://github.com/darktable-org/darktable/files/10094680/dt-stable.txt)
In this log, the entry where dt finishes processing snapshot selecting is 200.852064

**Comment by TurboGit** [comment]
> Whenever I select a snapshot, darktable takes a sensitive amount of time to display it.

Because the new snapshot feature is fully dynamic so you can pan&zoom. That's a side effect.
