### ISSUE TITLE
Unable to view CR2 files (Canon EOS 30D ca 2007) 

### ISSUE THREAD

**Issue by petedgr8** [darktable-org/darktable#12999]
Darktable v 4.0.1 
Ubuntu 22.10

Trying to view a CR2 file that was created by a Canon EOS 30D (ca 2007) reports

"failed to read camera white balance information from ..."

Other photo viewers (Shotwell, Image Viewer) on the same computer display the files without error.

**Comment by jenshannoschwalm** [comment]
Any chance to share an image?

**Comment by TurboGit** [comment]
I can open a CR2 from EOS 30D fine.

**Comment by petedgr8** [comment]
Sorry - I should have included this with the original issue...
[20221125_0307.CR2.gz](https://github.com/darktable-org/darktable/files/10096770/20221125_0307.CR2.gz)

**Comment by ptilopteri** [comment]
I also cannot open subject cr2 image.  exif shows "software picasa", wtf!

fwiw: rawtherappe cannot open the image
nor can krita or digikam

**Comment by victoryforce** [comment]
> Sorry - I should have included this with the original issue... [20221125_0307.CR2.gz](https://github.com/darktable-org/darktable/files/10096770/20221125_0307.CR2.gz)

@petedgr8 Your file is actually a JPEG that mistakenly has the CR2 file extension.

**Comment by petedgr8** [comment]
Thanks for looking. It's from an old archive - probably things got scrambled sometime along the way.
