### ISSUE TITLE
loading normal rgb image (like sRAW, linear DNG, EXR) causes Darktable to hang with inpaint-opposed enabled by default.

### ISSUE THREAD

**Issue by jorismak** [darktable-org/darktable#12993]
**Describe the bug/issue**

When loading an image that is _NOT_ bayer / xtrans data, Darktable CPU usage spikes to 100% (which means on all my 20 threads) and sits there, and the whole system becomes unresponsive.

This happens with linear DNG files that I was able to open before, but for example also with an EXR file that is exported from Darktable itself!

If I kill Darktable, and restart it again, it seems fine. But the moment I open the same picture again, everything goes slow again.
The 'darkroom' does eventually load, and the picture appears, and eventually the histogram appears.

If I click 'highlight reconstruction' (to disable it), and wait till Ï see it turned off, Darktable seems to get more responsive the moment it's disabled. But there is still a lot of CPU activity.

If I now kill Darktable again, start it again, open the same picture. Everything is fine! CPU is normal, Darktable is fast.

If I enable highlight-reconstruction again, it seems OK for the first few seconds. But zooming in and out is noticeable, a bit slower. CPU usage jumps up quite high (> 50%) but does settle back to 0% again. But the RAM usage for Darktable spiked to over 4.5gb now.

Disabling highlight-reconstruction, and zooming in and out, makes the RAM usage drop instantly to < 1gb.

If I close it and restart it again, and quickly set highlight reconstruction to 'clipped' (the only other option), everything stays fast, and the RAM usage stays < 1gb.

I helped @jenshannoschwalm to test inpaint-opposed when he made it work for sRAW files, on the same linear-DNG files as then. It was working fine then. So somewhere in the 4.1-dev cycle, this regressed. All the work on the pixelpipe-cache?

**Platform**

* darktable version : e.g. 4.1.0-106
* OS                : Windows 11

**Comment by jenshannoschwalm** [comment]
OK, this for sure due to the huge amount of data that has to be processed so the thumb rendering keeps dt busy after switching to light room.

I will have look and if there is no easy fix we might want to keep clip as default for linear raws. 

@TurboGit what do you think?

**Comment by jorismak** [comment]
@jenshannoschwalm problem is dat DT now just completely stalls / crashes / hangs, and memory usage goes through the roof.

Inpaint-oppossed is now unworkable on non-bayer / non-xtrans images... while it was working fine before.

**Comment by jorismak** [comment]
The issue was introduced by the merge of https://github.com/darktable-org/darktable/pull/12651.

**Comment by TurboGit** [comment]
> @TurboGit what do you think?

Agreed, last report from @jorismak seems to imply that we have a (large) memory leak for non bayer.

**Comment by jenshannoschwalm** [comment]
PR coming tomorrow.

**Comment by TurboGit** [comment]
Thanks @jenshannoschwalm you are doing quite a lot!
