### ISSUE TITLE
darktable-4.0.1 (win64 version) crashes at startup with log file=>library.db corrupted?

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#12990]
I use this version on Windows 10 since one month without problem.
It crashed this morning being inside the app (lightable), browsing pitcures filtering on left menu.
Then impossible to launch it again even after several attempts: such kind of error message appeared at each attempt:
![Image 3](https://user-images.githubusercontent.com/44755276/203933765-bb829961-912f-443d-9546-44a48624ed47.png)
[darktable_bt_JOOBW1.txt](https://github.com/darktable-org/darktable/files/10089816/darktable_bt_JOOBW1.txt)
[darktable_bt_54AFW1.txt](https://github.com/darktable-org/darktable/files/10089817/darktable_bt_54AFW1.txt)
[darktable_bt_BBZHW1.txt](https://github.com/darktable-org/darktable/files/10089818/darktable_bt_BBZHW1.txt)
[darktable_bt_CXD7V1.txt](https://github.com/darktable-org/darktable/files/10089819/darktable_bt_CXD7V1.txt)

**Comment by andreilabato** [comment]
No Darktable instance was present in Windows system.
After PC restart, same error message displayed see attachment.
[darktable_bt_3QY7V1.txt](https://github.com/darktable-org/darktable/files/10089885/darktable_bt_3QY7V1.txt)

**Comment by Nilvus** [comment]
So you found the issue. Your library.db file was corrupted. It's rare so nothing darktable team can do. And even if it's rare, you could find backups in your darktable config folder. That allow you to revert back the file to a previous state without having to reimport all your files or settings. See manual if needed. As I don't use Windows, I don't have in mind where the config folder is (manual should precise that).
