### ISSUE TITLE
Segfault renaming a style after importing it

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#13004]
Version: DT git master
OS: both Windows and Linux
build mode: both Debug and Release

To reproduce
1) Import a style
2) Immediately after, click edit button and change its name
3) Click save
4) See the segfault

No useful log, unfortunately

**Comment by Mark-64** [comment]
In styles.c, function `void dt_styles_update()`, line 414

```
if(g_strcmp0(name, newname))
  {
    dt_action_t *old = dt_action_locate(&darktable.control->actions_global,
                                        (gchar **)(const gchar *[]){"styles", name, NULL}, FALSE);
    dt_action_rename(old, newname);
  }
```

when renaming the style immediately after import, `dt_action_locate()` returns NULL, and `dt_action_rename()` segfaults.
We could check 
`if(old) dt_action_rename(old, newname);`
but I am not sure this is correct.
@dterrahe can you have a look?

**Comment by dterrahe** [comment]
@Mark-64 thanks for the report!

Your fix would be correct, but the original problem is that when importing styles, no "action" is created, so it is not immediately possible to set up a shortcut. Then when renaming, the non-existing action causes the crash. I'm looking into fixing both.

**Comment by Mark-64** [comment]
Tested #13006, it solves the issue.
