### ISSUE TITLE
Give 2 levels of 'sort by'

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#13016]
The 'sort by' has two levels already: It sorts by filename/time/rating and then on whatever the previous order was. 
Perhaps it's nice to make this explicit:  "Sort by" rating and "then by" filename.

**Comment by Nilvus** [comment]
This is precised on topbar, not by adding then but by order proposed. The choice had been done also to avoid using too much space (think also about translations and some languages where translated name are quite longer).
