### ISSUE TITLE
Culling is buggy. Applies rating/color to all 3 pictures at once.

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#13014]
Darktable 4.0.1 on Linux. 

In culling view, 3 pictures shown, DT sometimes applies the star rating to all three at once. 

I use the mouse wheel to scroll through the pictures.
I move the mouse cursor over the image I want to rate, and use the F1-F5 and 1-5 keys to apply a rating. 
There is a white frame around the image that I hover over. 

I don't click or otherwise select the image; sometimes I scroll, move the mouse cursor and apply a rating;  other times I scroll, don't move the mouse and apply the rating. 

I notice sometimes after scrolling, there is no white frame around the image under the mouse cursor.   
In that case the rating is applied to all three images at once.  When I wiggle the cursor, the thin white frame reappears and only the 'active' image gets a rating.

I hope this can get fixed. It really makes me stay away from culling mode.

**Edit**
It does not just only happen after scrolling and it is not always related to having an 'active' image. 
Sometimes the behaviour of applying the rating to all is just 'sticky'.  It seems to go away 9 out of 10 times when I move the mouse cursor.

Not sure if it helps but you can also see inconsistent behaviour when using the 'W' shortcut to examine an image.  Sometimes when you release it, you return to the culling view with no 'active' image.

Desired behaviour:
That the image under the mouse cursor is always the active image and that ratings and color labels are only applied to that one single active image - and not  'most times'. 

**Edit2** I have made a desktop recording where you can see the behaviour. 
Can I share it somehow?

**Comment by Nilvus** [comment]
It's not related to culling but how darktable actually handle the use of shortcuts. Your issue is related to that one (more larger one and actual behavior has its pros and cons. The change is needed but no consensus):  #6025

So no need to share recording, it's well known and unfortunately nothing moved since a time as you can see in linked issue. No need to have 2 issues for same thing so I close yours. Continue on linked issue above.

**Comment by airflow2010** [comment]
You have my sympathy and I can very well relate to your described problem. I described it recently myself here: https://discuss.pixls.us/t/frustration-with-culling-mode/33795

Unfortunately, it is not considered a bug, but instead "just the way selection works within darktable". I am afraid we cannot do anything about it until there is some consensus within the dev-community of darktable about how to handle image selection and to improve its behaviour.
