### ISSUE TITLE
Remove plugins/darkroom/masks/opacity from darktablerc

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#13037]
**Is your feature request related to a problem? Please describe.**
A recurring issue on discuss.pixls.us: plugins/darkroom/masks/opacity changes to a value other than 1, and all subsequent masks are created with that opacity. Users don't know why this happens, and how to restore the default value. It is not clear _when_ the default opacity is updated in `darktablerc`.

**Describe the solution you'd like**
 It would make sense to drop this value, and always start masks from 100% opacity (or from the last used value for the current image). Carrying the value from image to image, or session to session, is not intuitive.

**Alternatives**
- Keep the current way.
- Expose an option on the UI to reset to 100%.
- Make updating the value an explicit, user-requested operation.

**Additional context**
https://discuss.pixls.us/t/darktable-3-0-masking-inconsistencies-bugs/16217/11
https://discuss.pixls.us/t/resolved-masks-dont-mask-anymore/24512/8
https://discuss.pixls.us/t/issue-with-the-opacity-of-drawn-masks/33754/7

**Comment by todd-prior** [comment]
I agree

**Comment by elstoc** [comment]
I disagree. This is designed to allow you to set multiple shapes with the same opacity and I use it. It's fully documented in the user manual. See the note at the bottom of the [creating shapes](https://docs.darktable.org/usermanual/4.0/en/darkroom/masking-and-blending/masks/drawn/#creating-shapes) section

**Comment by todd-prior** [comment]
It should ethier reset after you go to a new image or leave your dt session…. IMO… I get this for working on one image using repeated shapes but it can cause the same issue that spot color matching produces in the CC module and people don’t notice and then wonder WTF is going on when I hit the auto picker thinking they are getting a WB…

To me it might even seem more normal to have that behaviour follow shape creation if you use the control modifier and so opacity stays the same. Then if you select an new shape it resets either to 100% or a selectable default that the user can set for new shapes…

But I’m sure this would not work for others…..

**Comment by TurboGit** [comment]
> Then if you select an new shape it resets either to 100% or a selectable default that the user can set for new shapes…

Not for me, when you work on an area in retouch for example and you place many shapes you need to get the same opacity. I don't think this is a setting that will fit everyone.

**Comment by todd-prior** [comment]
Ya on that account maybe but it should reset on a new image or at the very least coming back to DT ….it seems crazy that you go away for a few days come back and have to notice or remember that opacity is at something other than 100… But you will never please everyone on this….

**Comment by todd-prior** [comment]
> Not for me, when you work on an area in retouch for example and you place many shapes you need to get the same opacity. I don't think this is a setting that will fit everyone.

Just to clarify as this could be my lack of clarity... I suggested that if you use ctrl select to place multiple repeated object in one operation then that makes perfect sense. I was suggesting this thinking okay you make the opacity change and draw 5 paths... they of course you would want to be the same .. but now you go and change to a circle or you go to a new image then it would reset...  If not then at some other point that was not permanent.... You may have understood that so you can ignore this as noise...

**Comment by elstoc** [comment]
> I suggested that if you use ctrl select to place multiple repeated object in one operation then that makes perfect sense

I forget to use ctrl+click so often it hurts, and sometimes I come back again later because I noticed another spot that needed correcting. Resetting everything again each time would be painful.

**Comment by todd-prior** [comment]
Its funny and a small thing...but using the darktable theme which I did when I first started to use DT used bold in the popup for mask opacity and key reminders...but it made noticing the opacity value or a change in it more obvious....

![image](https://user-images.githubusercontent.com/44409419/204405421-b873befb-d17a-48fa-9389-36543655b0ac.png)

The elegant grey theme that I use now it all sort of blends in...not sure if this is a css thing that one could use to bring back the bold... I think it looks better  but again its likely just me.

![image](https://user-images.githubusercontent.com/44409419/204405673-7317b567-8528-424e-bbb4-b516822a0d0c.png)

**Comment by Dannny1** [comment]
The problem is imo, that changing the mask opacity after you create the shape isn't saved to darktablerc, it's saved only if you do it before or in retouch module also afterwards.

**Comment by Nilvus** [comment]
Thanks for noticing such difference between themes @ŧodd-prior but this is not what I have on my side. Bold is correctly shown in grey theme. Regarding the text on your grey theme screenshot, that clearly means that you don't have all Roboto fonts needed by all elegant themes (not only grey one) and you could probably see same issue on both elegant-darker and elegant-dark theme. Just install Roboto fonts needed and recommended for elegant themes and you will then see that display is the same as default darktable theme.

**Comment by elstoc** [comment]
> The problem is imo, that changing the mask opacity after you create the shape isn't saved to darktablerc, it's saved only if you do it before or in retouch module also afterwards.

The behaviour is that opacity is saved if you change it before placing the shape and not if you change it after placing the shape. This gives you a choice of behaviours. If you want to always keep the default, then always place the shape and then adjust. If you want to set the default , do so before placing the shape. What you're suggesting is reducing these options, which might be fine for you, but annoying for others (me).

> or in retouch module also afterwards

Are you suggesting that changing opacity after placement in retouch changes the default opacity? I don't reproduce this behaviour.

**Comment by todd-prior** [comment]
Interesting. I don’t feel like I have ever done it before placing and yet recently a couple of time this has happened… there is no way to inherit this from importing an xmp is there??

**Comment by todd-prior** [comment]
Thanks for the hint I was sure I had them. I will check… its funny it a small think but it catches your eye just enough to notice a change if one has been made…

**Comment by Dannny1** [comment]
> If you want to always keep the default, then always place the shape and then adjust. If you want to set the default , do so before placing the shape. What you're suggesting is reducing these options, which might be fine for you, but annoying for others (me).

No, i'm just suggesting to make it consistent, e.g. people who are used to make opacity adjustments afterwards and have 100% mask and also made adjustment in retouch may be stuck with different value without noticing. Then write on forums,fb... why is dt doing lower opacity masks by default.

>  Are you suggesting that changing opacity after placement in retouch changes the default opacity?

Yes, try to make path in retouch module, adjust afterwards opacity slider, close darktable.

**Comment by elstoc** [comment]
Ah I see. You're using the opacity slider and not Ctrl+scroll. That's a bug - it should not do that.
