### ISSUE TITLE
Removed collection reappears after restarting darktable

### ISSUE THREAD

**Issue by Jiyone** [darktable-org/darktable#13049]
**Did you buy darktable from an application store ?** NO

**bug/issue description**

Sometimes I load picture as test and I want to remove them some days later just by removing the collection entry. But they go back when I restart darktable.

**To Reproduce**

1. Go to lighttable and have a collection entry with pictures ready yo be removed.
2. Right-clic on the entry to remove and select `remove...`. The entry has been removed.
3. Quit darktable and restart it.
4. The removed collection is back!

**Expected behavior**

The collection should be removed forever.

**Platform**

* darktable version : 4.1.0+1150~g9de1419b5
* OS                : Linux
* Linux - Distro    : Ubuntu 20.04.05 LTS
* Memory            : 15.6 Gib
* Graphics card     :  Radeon RX 580
* Graphics driver   :  AMDGPU
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              :  
* Desktop           : X11
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

 - Can you reproduce with another darktable version(s)? **no tested yet**
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **not tested**
 - Do you use lua scripts? NO

**Comment by Jiyone** [comment]
@TurboGit I’m not home until tomorrow evening and I forgot to try with a new preference file.
I know that I show the previous folder at the beginning of each entry (as set in the module preferences) but I’m not sure what else is set.
Sorry to not being able to give information until tomorrow.

**Comment by TurboGit** [comment]
@Jiyone : No problem, don't be sorry there is no urgency.

**Comment by Jiyone** [comment]
@TurboGit  So I tried with a fresh new config folder and it doesn't work neither.
