### ISSUE TITLE
Hinter message on shape edit causes resize

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#13044]
When hovering over a shape in (for example) the retouch module, the top panel has to slightly change size to accommodate the hinter text, which slightly shifts the whole ui. This is on a 1440p monitor with font size 13 but if everything is measured in em that probably shouldn't make any difference.

https://user-images.githubusercontent.com/9555491/204641718-2ea8ded4-04dd-4cd2-99c4-f4e938b1a2a0.mp4

Probably one for @Nilvus  to look at

**Comment by Nilvus** [comment]
Not sure it is for me. Seems related to @dterrahe improvement allowing topbar infos to be shown in header one. @dterrahe: what's your view on that?
Of course, maybe some CSS could help but maybe there's something else before to check related to changed code on that part.

**Comment by Nilvus** [comment]
Oh, and I can't reproduce on my size, even when setting font size to 13. Tested on a 32" 1440p monitor.

**Comment by dterrahe** [comment]
> Seems related to @dterrahe improvement allowing topbar infos to be shown in header one.

What makes you think that? Seriously, I'm curious. It is nicer to be called in for expertise, like you were, than as a possible culprit.

> everything is measured in em

Except the logo and version number in the top left corner. And those are determining (together with the one line "lighttable|darktable|other" top right, which _does_ scale with a, slightly larger, font size) how much space the header bar gets. If it is not enough to fit two lines, it will jump when the hint gets that long.

Should be fixable by assigning an em based size to the header bar in css. 2em presumably would do it (with some padding?). 

A nicer solution might be to size the logo based on font size, but this would require code changes.

> Oh, and I can't reproduce on my size, even when setting font size to 13.

Reproducible here with font size 12. Probably depends on dpi setting (explicit or in X) as well.

What does the label "understood: clear" mean for you? It doesn't convey much additional information to me used this way (for me it would contradict "reproduce: random")

**Comment by Nilvus** [comment]
Just because you allow recently, if I remember correctly to display such text infos in header bar but maybe I make some confusion.
Label is just a selection error, nothing more...

The nicer solution seems better to me than adding CSS for that.

**Comment by dterrahe** [comment]
> maybe I make some confusion.

Yeah. My pr allowed some info to move the other way (to top bar, out of header bar, depending on how you use those terms exactly) and the type of information involved, number and selected items, is not causing issues here.

The potential problem with the "better" solution is that the size of the icon would have to depend on the font size used for the header label. The really "correct" solution might be to set the height of the label to 2em and to have the icon use all of the allocated vertical space. But the second part is really optional.

A dirty solution, if you really don't want to add CSS, that I haven't tried might be to always set two lines in the hinter (i.e. add an extra line feed or two of there's only one line or none). But that would prevent vertical centering.

**Comment by Nilvus** [comment]
Will check that and test CSS

**Comment by Nilvus** [comment]
@elstoc: could you test if such setting fix this issue:

```
window box grid
{
  padding: .1em;
}
```

Just note that it's for testing a fix. Such code could impact other not wanted part so it's not the final fix.

**Comment by elstoc** [comment]
Nope, same problem, no effect. I tried various values (up to 1em) and still the same

**Comment by Nilvus** [comment]
And if you add box after grid?
And if you add then label after?

**Comment by elstoc** [comment]
This seems to resolve it:

```
window box grid box
{
  padding: .1em;
}
```

**Comment by Nilvus** [comment]
Ok, so I had just not copied at first the good one on all my testings. Great. Thanks for feedback.
