### ISSUE TITLE
Retouch module crash if accidentally double click mouse (create add circle on top of each other)

### ISSUE THREAD

**Issue by talmholt** [darktable-org/darktable#13054]
**Introduction**
Retouch module crash if accidentally double click mouse (create add circle on top of each other). This happens only really when I use the "Ctlr-Click" option to have the "add circle" repeated and I am quickly fixing skin issues.

This has been ongoing in many version of darktable that I have compiled from main branch.

My current version is : 4.1.0+1136~gbaaf63809

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to retouch module 
2. Click on activate healing tool, click on "circle" shape
3. use Ctrl-Click to enable multi cirle add function, now add and input and output circle on top of each other by "double clicking" the mouse. 
4. darkroom will lock up and exit to lightroom. Last couple of edits will be lost, but nothing major happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/3262006/204945682-f4cdfcc8-cf6c-4fd2-85ab-4e2f38bd29e0.png)

![image](https://user-images.githubusercontent.com/3262006/204945817-47fbcb2c-6007-4ccc-a2a1-0bca922ce9f8.png)

**Which commit introduced the error**
This has been happening for a long time. My guess even since 3.8 and up.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.1.0+1136~gbaaf63809
* OS                : Ubuntu
* Linux - Distro    : Ubuntu 22.04.1 LTS
* Memory            :  16GB
* Graphics card     : Mesa Intel® HD Graphics 4000 (IVB GT2)
* Graphics driver   : ?
* OpenCL installed  : N/A
* OpenCL activated  : No
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by pehar1** [comment]
Not sure if I understand your issue, but double left-clicking in darkroom returns to lighttable by design (press h-key in darkroom, see first entry : _left double-click -> switch to lighttable_).

> Retouch module crash if accidentally double click mouse

As you describe it, darktable does not crash. It just leaves darkroom and is still responsive.

**Comment by gi-man** [comment]
I tried this in Fedora 36 KDE X11 with and without OpenCL and I cannot reproduce. 

OP, you might need to look at a backtrace. I noticed your screenshot shows 28 shapes, does it happen with just 1 shape?

**Comment by talmholt** [comment]
Sorry, it is a little hard to describe. It happens when I am adding circles to tell the retouch module what patch needs to be "fixed" and what to use as "reference" patch. If I happen to double click and the patch to "fix" becomes the same as reference "patch" then it "freezes for a while" and then reverts back to Lighttable. --- but let me play with it some more to see if is actually "expected behavior"

**Comment by dterrahe** [comment]
There was some discussion, in #12705 I believe, on whether double click should be disabled when working with or creating mask shapes, since experience with other programs may have created habits that make it counter intuitive to drop out of darkroom.

**Comment by talmholt** [comment]
I just tested it again and yes, if I "double click" it exits darkroom (after the last edit is committed). So I think this is expected behavior, however when doing many edits and doing them quickly, sometimes the GUI thinks it is a "double-click" event. 

I think it would make sense to disable the double click feature in the "multi shape" mode, because sometimes the user would be adding a lot of shapes and sometimes pretty quickly.

**Comment by pehar1** [comment]
It is also possible to adjust the double-click speed of your operating system. I did so and never had any problem by accidential double-clicking in darkroom.

**Comment by talmholt** [comment]
This issue can be closed. The behavior that I described is actually intentional and not a "crash". Sorry about not responding earlier.
