### ISSUE TITLE
Shortcuts: module reset "right-activate" is not explained

### ISSUE THREAD

**Issue by grothesque** [darktable-org/darktable#13051]
This applies to the current development version of darktable, but I assume that it applies to 4.0 and other versions just as well.

When defining a "reset" shortcut for a module, there are three possible choices for "effect":
- activate
- ctrl-activate
- right-activate

The first two possibilities are explained in https://docs.darktable.org/usermanual/4.0/en/preferences-settings/shortcuts/#utility-modules, but what does the third one do?  Is it equivalent to right-clicking on the reset button of the module?  But what does the latter do?  This is not explained in https://docs.darktable.org/usermanual/4.0/en/darkroom/processing-modules/module-header/.

Searching the entire documentation for "right-activate" or even "right" does not seem to yield an answer as well.

It seems to me that the documentation is incomplete in this regard.

**Comment by Nilvus** [comment]
This place is for issues about the software. For issues related to darktable docs, please post there: https://github.com/darktable-org/dtdocs

**Comment by grothesque** [comment]
very well...
