### ISSUE TITLE
Please add Chromebook installation instructions to the main installation page on the website (I wrote some)

### ISSUE THREAD

**Issue by mrjohnc** [darktable-org/darktable#13067]
**Is your feature request related to a problem? Please describe.**

I use Darktable on my Chromebook (works well) but I realised that [the main installation page on the website](https://www.darktable.org/install/) doesn't even tell people it works on Chromebooks. I think having instructions for Chromebook would be really helpful given the number of Chromebooks there are.

**Describe the solution you'd like**

I've written some basic instructions which should give people all the information they need, but I'm sure could be refined.

Step 1: Enable Linux support on your Chromebook by following [these instructions](https://support.google.com/chromebook/answer/9145439?hl=en), not all older Chromebooks are compatible.

Step 2: Once you have done this you can install through the [Linux Terminal](https://chromeos.dev/en/productivity/terminal) either through:

Option 1: use these commands to install and uninstall Darktable

Install: sudo apt install darktable
Uninstall: sudo apt remove darktable && sudo apt autoremove

Option 2: Install through Flatpak

Install FlatPak using [these instructions](https://www.flatpak.org/setup/Chrome%20OS)
Install Darktable using the command line instruction on [this page](https://flathub.org/apps/details/org.darktable.Darktable)

**Alternatives**

**Additional context**

**Comment by gi-man** [comment]
I have darktable in a chromebook that I could use when I'm traveling. The instructions on how to setup a chromebook to run linux (a version of debian if I recall correctly) are part of google and not unique to darktable. The instructions on how to install on debian are already available in darktable. I'm not sure what else we would be adding with this feature request.

**Comment by Nilvus** [comment]
I would also add that if you want website update, that means it's not the right place. For website, post here: https://github.com/darktable-org/dtorg
An so close this issue.

I suggest also to take care about @gi-man comment.

**Comment by mrjohnc** [comment]
> 

I'm requesting this because currently the website says nothing about ChromeOS compatibility, it makes it appear as though it is not installable on a Chromebook which is not true.

**Comment by mrjohnc** [comment]
> I would also add that if you want website update, that means it's not the right place. For website, post here: https://github.com/darktable-org/dtorg An so close this issue.
> 
> I suggest also to take care about @gi-man comment.

Thanks I'll post something there instead
