### ISSUE TITLE
[FR] Some features related to the filtering module and filtering top bar from a design point of view.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13065]
**Is your feature request related to a problem? Please describe.**

The imported file filtering module has a strong search, cataloging and collection organization component. I know that some developers are working hard on this module to make it a more powerful tool, so I would like to put at your disposal and appreciation some ideas related to this module from a design point of view.

**Describe the solution you'd like**

1. Allow the "sort by" option to be placed towards the beginning of the filtering options as it was in the versions before the filter bar existed, because the file organization should use the "sort by" first and then the different rules. I imagine that when importing photos to the lighttable, the first thing would be to sort by type, file name, capture date, etc and then do the sorting by star rating, rejected files, colors, etc.

2. It should be the same background color (898989) in the darktable-elegant-grey theme and (5e5e5e) in the darktable-elegant-dark theme for the top bar colors filters to avoid different perception of color circles, mainly with blue. This is related with #12983 

3. In the collection filters module should be collapsible panels to follow the same design of color calibration, import, mask manager, CAT, exposure and white balance modules. This option may be helpful for users working with laptops with lower screen resolution.

4. To make this module more compact there should be less space between the filtering rules.

5. The hamburger icon to add or remove filtering rules in the top filtering bar does not look good from a design point of view, as it is very close to the other two (import and collections modules) and has a different size than them. Anyway the filtering options of the module allow to add or remove rules of this top bar.

6. The visual alerts should follow the same design as the color calibration and white balance modules. An alternative option may be that the "new sort" and "new rule" are disabled if 10 sort orders or rules are reached. Other alternative can be if the visual alert are placed directly under the header of the module "collection filters" and will show the alert in every case "you can´t have more than 10 sort orders" or "you can´t have more than 10 rules". If I had to choose, I would select the option to disable the button when you reach 10 types of rules or sorting. This is an indication that you can no longer put more than 10 rules or sorting.

7. To maintain consistency with the overall design the icons must be located in the same place. If the pin option is not allowed in modification, export and print time, then the icon should be hidden, but the other two (remove rule and enable/disable) should not be moved to the right.

**Additional context**

![filtering_panel_01](https://user-images.githubusercontent.com/67672868/205420530-1f3009be-67d7-4392-88e6-721fa7f1435b.png)

![filtering_panel_02](https://user-images.githubusercontent.com/67672868/205420551-dcaa81eb-76e6-4fa7-aad8-f762b001c470.png)

![filtering_panel_03](https://user-images.githubusercontent.com/67672868/205452005-37c18905-a432-4663-88db-09ccae2ef9cb.png)

**Comment by Nilvus** [comment]
First, thanks for all your proposals.

>     1. Allow the "sort by" option to be placed towards the beginning of the filtering options as it was in the versions before the filter bar existed, because the file organization should use the "sort by" first and then the different rules. I imagine that when importing photos to the lighttable, the first thing would be to sort by type, file name, capture date, etc and then do the sorting by star rating, rejected files, colors, etc.

Why not! Both cases are good to me, at first or at the end. I mainly filters then sort by (most of the time, I use default sort by as it's good to me) but the other way would be good to.
 
>     2. It should be the same background color (898989) in the darktable-elegant-grey theme and (5e5e5e) in the darktable-elegant-dark theme for the top bar colors filters to avoid different perception of color circles, mainly with blue. This is related with [Dark blue label is hardly visible on a dark background #12983](https://github.com/darktable-org/darktable/pull/12983)

Yes and no. Of course, having same perception would be good but as color labels are shown in different places with different backgrounds, it will never be the case. Think also about bottom bar where we can set color labels and thumbnails. It's not wanted to add such background on all places. I've tested, following your proposal here and I don't like how filter bar become by having such background behind color labels. Yes, it's completely subjective. I'm not sure but by now, it's probably better to have different blue label (as less as possible of course) regarding theme to deal with that and all different places where color labels are shown. A proposal is coming. Of course, you could say that this will make blue color label different regarding theme and it is but all users probably use all the time just one theme.

>     3. In the collection filters module should be collapsible panels to follow the same design of color calibration, import, mask manager, CAT, exposure and white balance modules. This option may be helpful for users working with laptops with lower screen resolution.

Good idea to me. This had been proposed but some disagree because that will add one more click.
Said that, 

>     4. To make this module more compact there should be less space between the filtering rules.

I agree but too less on your screenshots.

>     5. The hamburger icon to add or remove filtering rules in the top filtering bar does not look good from a design point of view, as it is very close to the other two (import and collections modules) and has a different size than them. Anyway the filtering options of the module allow to add or remove rules of this top bar.

The hard one. You're right about that but I think this should stay at the left. My statement do not answer to what you point but by now I have no idea how to handle that.
 
>     6. The visual alerts should follow the same design as the color calibration and white balance modules. An alternative option may be that the "new sort" and "new rule" are disabled if 10 sort orders or rules are reached.

All visual alerts are not the same. Information ones, like that one, are shown in log message. Visual alerts with red color on header are for error that need a change, not information that are just temporary.

>     7. To maintain consistency with the overall design the icons must be located in the same place. If the pin option is not allowed in modification, export and print time, then the icon should be hidden, but the other two (remove rule and enable/disable) should not be moved to the right.

I agree.

**Comment by Nilvus** [comment]
@difrkaguilar: if you have other mockups idea, especially for one module that mix collections and collections filters modules, that would be great. An idea of workflow:

- choose some main first filter (like actually in collections modules), for example, film roll or folder.
- then filter (or sort by)
- then sort by (or filter depending on previous step)

**Comment by difrkaguilar** [comment]
Some changes to yours consideration. 
I make a different icon for the filtering options in the top bar. It's looks as a filter, but with the options. the stars looks great as @TurboGit proposed with the horizontal line.

I change to 4px he distance between rules in the collection filters modules and change the color too.

![filtering_panel_04](https://user-images.githubusercontent.com/67672868/205516313-2743e0ff-5e1a-403c-b7e4-90ac00e264da.png)

[filter_icon.zip](https://github.com/darktable-org/darktable/files/10149496/filter_icon.zip)



> * choose some main first filter (like actually in collections modules), for example, film roll or folder.
> 
> * then filter (or sort by)
> 
> * then sort by (or filter depending on previous step)

I'm going to work in that ASAP.

**Comment by Nilvus** [comment]
Thanks for feedback @difrkaguilar. For stars, would have been better on the PR. I like also @TurboGit proposal about the line, even if I prefer line I put in PR (just aesthetically ; both are great in terms of functionality).

Good idea for filtering option icon.

@AlicVB: what's your view on such icon? If ok, will remains to code it, would probably not be for 4.2. And about other proposals here?

About distance between rules, what I update on my PR is near (on standard font size (let say 12px). Main difference is that I set size with em, allowing to be dependent on font size.

Thanks again for the mockup (and one you will propose). I will not follow all things but that helps. And there really often good ideas.

**Comment by AlicVB** [comment]
lot of great idea and proposals, as usual... For what is worth, here is some comments : 

- the filtering option icon : I agree that the current one is far from ideal. Let's try to write your proposal in cairo now ;)
- the range-rating : I'll continue the discussion on the dedicated PR
- the "alert" message : I don't like it tbh... as @Nilvus says, this color is dedicated for errors, not limitations, which are actually handled with alert messages in the main view. In fact, code wise, the limitation is not really needed, so we even can ask us if we shouldn't remove it entirely...
- I'm not sure about the order of the filter/sorting... I'm not against, but intuitively (read "my habits dictate me") I would say that you sort after filtering...
- for the spaces, etc... I will let @Nilvus answer... he's our guru ;)

**Comment by Nilvus** [comment]
>     * the "alert" message : I don't like it tbh... as @Nilvus says, this color is dedicated for errors, not limitations, which are actually handled with alert messages in the main view. In fact, code wise, the limitation is not really needed, so we even can ask us if we shouldn't remove it entirely...

Or increasing the limit. Anyway, I don't see usecases where more than 10 filters (and collection modules + top bar filters possibilities) where more than 10 filters is needed. So I think it's great as it is.
The only case I see would have a user who want to add all filters and enable/disable them regarding what he needs. Why not, so the limit could be filters number (or a little more).

**Comment by difrkaguilar** [comment]
The real limitation is the number of rules to pin in the top bar depending the resolution of screen the users have :-)

**Comment by AlicVB** [comment]
@difrkaguilar : here is the "icon" part : #13081 I think that the icon is real close to your proposal...

**Comment by Nilvus** [comment]
Nearly all things you pointed here were answered and/or fixed. @difrkaguilar: regarding answers here and what had been done, is this could be closed? If not, what remained to discuss for you?

**Comment by difrkaguilar** [comment]
Yes, this FR can be close. Thanks once again. Greetings.
