### ISSUE TITLE
backtrace during upgrade from 3.6.x to 4.0.1

### ISSUE THREAD

**Issue by mdrie** [darktable-org/darktable#13074]
**Backtrace**

[darktable_bt_LK5RW1.txt](https://github.com/darktable-org/darktable/files/10149426/darktable_bt_LK5RW1.txt)

**Describe the bug/issue**

During database conversion a dialog appeared pointing to the above file. While I left the dialog open, everything seemed to work. I was able to navigate through my collections. When I closed the dialog, darktable stopped immediately. When I then opened it again, it would not show any window.

I am able to reproduce this behavior by restoring the database. The second time around, I was able to open darktable after it closed, but it showed the same error dialog. I could leave it open while working, but i am not sure it that is a good idea.

If there is anything I can do to analyze, let me know.

**Platform**

* darktable version : 4.0.1
* OS                : Win10 (21H2)
* Memory            : 16GB
* Graphics card     : internal
* Graphics driver   : 
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by dterrahe** [comment]
The log file seems to point to gphoto2 as the culprit. Normally that is used for tethering shooting with an attached camera. This may not be the cause for the crash here, but do you by any chance have a camera connected while starting dt? If so, have you tried disconnecting it?

**Comment by mdrie** [comment]
>  do you by any chance have a camera connected while starting dt?
Nope! And I never use tethering. I copy everything manually and then import into dt.

**Comment by ralfbrown** [comment]
@mdrie Is this still a problem with 4.2.1?

**Comment by ralfbrown** [comment]
No response from original reporter, and the original issue is now multiple releases ago.

**Comment by mdrie** [comment]
Sorry, still on the old version. Did not have the time to try the update, again. Thanks for the patience.

**Comment by ralfbrown** [comment]
If you do experience the problem again with an upgrade to the current version, please open a new issue.

**Comment by mdrie** [comment]
Wildo! Thanx!
