### ISSUE TITLE
OM Systems OM-5

### ISSUE THREAD

**Issue by jlgonzalezpeinado** [darktable-org/darktable#13079]
Hi, 
first of all, I want to thank you for the maintenance and development effort of DarkTable you are carrying out.
I recently changed my previous camera, an Olympus OM-D EM10 that has accompanied me for six years for the new OM Systems OM5.

I tried to process some of the first .ORF files that it generates with my version of DT, 4.0.1 for Ubuntu 24.01, and although it matters correctly by generating the corresponding sidecars DT cannot open them.

I have asked a friend who uses the same version but for windows 10 and the problem persists.

With Adobe DNGconvert, installed on a Windows virtual machine, I exported a photograph to .DNG and successfully processed it to DT. So this is not a matter of urgency, but it seemed to me that the best way to collaborate with you right now is this.

I send you at [pixl](https://discuss.pixls.us/t/raw-samples-wanted/)
the file: PC010023.ORF

carefully

josep lluis gonzález peinado
email: jgonzale@xtec.cat

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/rawspeed/pull/399

**Comment by Dysproz** [comment]
Same here for macOS Ventura 13.1. Darktable cannot open .ORF files

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/commit/928115e76f6d9864762dd606696e414d27c22524
