### ISSUE TITLE
JXL exporting all metadata

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#13077]
**Did you buy darktable from an application store ?**
No, self compile

**Describe the bug/issue**
I did a self compile to test JXL (adding the libjxl-devel dependency). Exporting worked, but the metadata was not showing in Geeqie. I used exiftool and the jxl image shows the metadata, so the issue is with Geeqie.

But looking at the exiftool I noticed the image had the hierarchical tags. I do not select that in my exports. I exported the same image in jpg format and the exiftool did not have the hierarchical tags. I then turned off all export metadata and exported jpg and jxl formats. The jxl had all the metadata information (develop, EXIF, author, tags), the jpg did not. 

**To Reproduce**
- In export preferences, turn off all metadata exports.
- Export an image in jxl and jpg.
- Evaluate the images using Exiftool

**Expected behavior**
Export metadata per the preference settings

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.1.0+1163~g788ffba4a
* OS                : Fedora 37 KDE X11
* Memory            : 16GB
* Graphics card     : Nvidia RTX 3060 12Gb
* Graphics driver   : 520.56.06
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional context**

I also noticed an issue with the jpg exporting metadata (when the box is unchecked and EXIF is checked). I will do a separate issue once I investigate it further.

**Comment by kmilos** [comment]
Unfortunately, it either this or no metadata ever for AVIF, JPEG XL, and EXR. This is because exiv2 dt usually leverages for other formats does not have write support for these, so their native embedded methods are used regardless of setting.

Not impossible to fix, but requires some work.

**Comment by victoryforce** [comment]
If this will not be fixed before the release, it should at least be described in the release notes. Metadata can contain sensitive and private information (such as geolocation), so this drawback is quite serious. dt may receive unfavorable user reactions if a warning about this feature is not published.

**Comment by kmilos** [comment]
Sure, a big warning is for sure warranted because of potential privacy issues. @TurboGit

**Comment by parafin** [comment]
Release notes is not a good place for such notice (well, as the only place). It has to be clearly indicated in the GUI. Or maybe disable metadata export until exiv2 gains support for these formats.

**Comment by parafin** [comment]
I think it's a good idea, because it will also help with discoverability of the metadata preferences dialog (a lot of people miss it completely).

**Comment by kmilos** [comment]
> For the formats not supported, we disable the ability to select per preferences.

[The current export code interface only has `ignore_exif` which is hard-coded to FALSE](https://github.com/darktable-org/darktable/blob/6c13deb2f6b1404f6b3e9e9046b35bbccc31109d/src/common/imageio.c#L712), so that could be maybe re-purposed. But we don't have a way to control XMP writing separately for these other formats, other than to say - if you disable Exif, you won't get XMP either (i.e. all in, or all out).

**Comment by gi-man** [comment]
@TurboGit any guidance on how to handle this? let it be for 4.2 with a Known Issue section to the release notes?

**Comment by TurboGit** [comment]
@kmilos : Do you think it is possible to disable all tags from being exported?

If not, I'll add a warning in the release notes for sure and we'll re-discuss this for 4.4.

**Comment by kmilos** [comment]
Sorry, it's not obvious to me right now, and unfortunately I don't have time to look into it.

**Comment by parafin** [comment]
> If not, I'll add a warning in the release notes for sure and we'll re-discuss this for 4.4.

I want to repeat my opinion, that release notes is not a place for such warning. It has to be clear from the GUI that privacy settings aren't being honored for these formats.

**Comment by victoryforce** [comment]
> I want to repeat my opinion, that release notes is not a place for such warning. It has to be clear from the GUI that privacy settings aren't being honored for these formats.

I second that. It would be much better for us if the user could not blame us for leaking their private information because we did not properly warn them.

**Comment by TurboGit** [comment]
> It has to be clear from the GUI that privacy settings aren't being honored for these formats.

Sadly too late for changing the GUI at this stage or it would have been to be super safe!

**Comment by parafin** [comment]
I'm sorry, but this is a very weak argument. There is a real problem and I'm not comfortable with making a release with such known flaw. The binaries I build for macOS are signed, meaning I bear some responsibility for them. I will consider either postponing the build of macOS DMG packages until this issue is properly fixed, or maybe disabling support for the affected formats in my builds.

**Comment by TurboGit** [comment]
> I'm sorry, but this is a very weak argument.

Ok, so next question who volunteer to do this change? I'm really short in time, full freeze in 7 days.

**Comment by parafin** [comment]
These dates are arbitrary and defined by you. If there is a major problem they must be flexible.

To answer your question - I don't volunteer, solution for me is to disable the export to these formats. BTW, would be very good to know which ones exactly are affected? Is it AVIF, JPEG XL, and EXR?

**Comment by dterrahe** [comment]
> There is a real problem and I'm not comfortable with making a release with such known flaw.

> These dates are arbitrary and defined by you. If there is a major problem they must be flexible.

From the discussion here, it is not clear to me if this is a _regression_? Arguably, if this issue existed in pre-4.2 versions, then getting out a release asap with a big warning in the release notes and soon after releasing 4.2.1 with a fix is better than letting people continue to use 4.0.1, which has this known flaw, without warning them. Packagers can decide, based on the release notes, to temporarily disable the affected formats in the mean time.

**Comment by dterrahe** [comment]
> Right way to go is to fix this problem one way or another and then do a release.

Even if that potentially means not warning people for a week or so more? ("Fixing" the problem could mean introducing regressions that cost more time to fix) That gives them enough time to post their leaky Xmas pics on social media.

I don't care one way or another; I already _know_ about the problem and don't use "released" versions.

**Comment by kmilos** [comment]
A temporary fix would be to just disable any Exif and XMP data writing to these formats for this release (e.g. with a macro) and look for a better way to do it for the next one, but that will lead to a bunch of new complaints (i.e. for removing functionality that was there).

**Comment by TurboGit** [comment]
> These dates are arbitrary and defined by you. If there is a major problem they must be flexible.

Not by me, that's the way we have done this since a long time and it would be a shame to not have a release for end of year as usual. I can be flexible, but if I do not do it around Dec 20 it will be in January. Mind you that I have also a life outside of dt :)

**Comment by dterrahe** [comment]
> doing a blog post on the website or some security vulnerability report here on GitHub

Apologies; I was simply responding to the suggestion to delay the release and had missed where you introduced these other solutions. Maybe you are right that news sites and those directly impacted are following such sources closer than release notes.

**Comment by parafin** [comment]
> > doing a blog post on the website or some security vulnerability report here on GitHub
> 
> Apologies; I was simply responding to the suggestion to delay the release and had missed where you introduced these other solutions. Maybe you are right that news sites and those directly impacted are following such sources closer than release notes.

Most likely not, but at least these channels are fit for this purpose. Release notes aren't meant for security bulletins, unless they include an actual fix. At least simply because we can't do a release at any random time.

Anyway, the release has to be delayed (in my opinion) only if fix can't be produced and properly tested until the target release date. And, as I said, as my personal decision, I will be delaying my macOS binary builds until this issue is addressed. If someone wants to take over official macOS packaging it might be a good opportunity to step up;) I would be happy to pass this role.

**Comment by gi-man** [comment]
I turned off all of the metadata preference settings and exported the same image in all the formats I have in my build. 

The only ones that have metadata are:
- EXR (not in the exiftool groups but it is there)
- JXL
- avif

https://pastebin.com/1AsLhnAH

**Comment by kmilos** [comment]
@gi-man Can we somehow try to get even more specific than that? What do you mean by "metadata"? For example, I see how XMP is disabled, but I don't see how some Exif can be disabled for any format?

**Comment by gi-man** [comment]
I see how this can be confusing. By metadata, I mean the fields in the module called metadata editor (eg. Creator, Rights...)

Here is the exiftool export of the same file in png. First file is with nothing selected in preferences, the second (_01) is only selecting _metadata_ in preferences and the third (_02) is selecting _Exif_ in preferences and the fourth (_03) is selecting both _EXIF_ and _metadata_.

Full Exiftool:
https://pastebin.com/UpP5XQQs

Exiftool -Rights 
======== IMG_4733_01.png  Rights : Creative Commons Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)
======== IMG_4733_02.png
======== IMG_4733_03.png  Rights : Creative Commons Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)
======== IMG_4733.png

Exiftool -Creator
======== IMG_4733_01.png Creator                         : Playraw
======== IMG_4733_02.png 
======== IMG_4733_03.png Creator                         : Playraw
======== IMG_4733.png

**Comment by kmilos** [comment]
Thanks. I have now poked some more, and it's messy:

First, all available Exif data is written to file indiscriminately by all format->write_image() methods (using either the native method API or via libexiv2).

Then, right after, dt_exif_xmp_attatch_export() actually re-writes both filtered Exif and XMP metadata according to export preferences, but only if the format supports writing via libexiv2 (currently JPEG, JPEG 2000, PNG, TIFF, and WebP).

As there is no easy way to control the first step, in this contorted scheme, we can only indiscrimately skip any metadata for other formats. The first step only potentially controls Exif, but unfortunately not XMP. Quite a bit of refactoring would be needed to fully fix this IMHO.

**Comment by kmilos** [comment]
I just pushed a potential minimal workaround (all in/all out):

If you deselect all metadata export boxes, there will be NO metadata added to AVIF/EXR/JPEG XL.

But as soon as you select one, ALL metadata (Exif, XMP) will be added.

So there is no fine grain control for these formats, but at least there is a way now to exclude any metadata if one is concerned about privacy.

**Comment by parafin** [comment]
Yeah..., that's not how it should work. Better logic would be if user deselects at least one metadata export box, then no metadata is exported. It's better to withhold more information than less for the privacy. Use-case to have in mind is simple:
1). User doesn't want to expose some private information, let's say location metadata.
2). He de-selects that type of metadata in the export preferences.
3). He expects that exported images don't contain geographic location.
4). If the that type of metadata is still there it's a breach of privacy.

**Comment by kmilos** [comment]
@parafin Feel free to propose the exact flag formula then at https://github.com/darktable-org/darktable/pull/13100/files#diff-87de7f037e0b9077b2b2185b65385f39f810970578e36a9c49db720af0eb719aR1111

**Comment by parafin** [comment]
Changing DT_META_NONE there to anything else will probably make this logic the same even for formats that do support fine-grained metadata export?
Otherwise I guess you could introduce DT_META_ALL to dt_metadata_id enum with a bitmask of all currently-existing flags and do a flags == DT_META_ALL comparison.

**Comment by kmilos** [comment]
> Changing DT_META_NONE there to anything else will probably make this logic the same even for formats that do support fine-grained metadata export?

Indeed, that will create a new problem.

**Comment by TurboGit** [comment]
Fixed.
