### ISSUE TITLE
darktable crash in lighttable full preview layout

### ISSUE THREAD

**Issue by 100102533** [darktable-org/darktable#13071]
**Did you buy darktable from an application store ?**
no

**Describe the bug/issue**
Some of my raw files cause a crash when opening them in full preview layout in the light table

**To Reproduce**
1. Import my RAW files
2. select light table, sort order: file name A ->Z
3. select the first raw file and type 'f' for full preview layout
4. scroll through all raw files or select one after the other
Sorry, but i can't upload my raw files (about 33 MByte per file), because of your upload limitation

**Expected behavior**
some of them cause an exception
backtrace:
[darktable_bt_X1R7V1.txt](https://github.com/darktable-org/darktable/files/10148502/darktable_bt_X1R7V1.txt)

**Screenshots**
![dt_exception](https://user-images.githubusercontent.com/112759793/205491333-6f23864d-d336-4c4a-ae53-bda5eeb00741.JPG)

**Screencast**
https://user-images.githubusercontent.com/112759793/205490143-94f26811-8866-4601-a454-4a8595a7ac42.mp4

**Platform**
* darktable version : 4.0.1
* OS                : Win10 22H2
* Memory            :  16 GB
* Graphics card     :  Nvidia GeForce GT 620
* Graphics driver   :  Version 23.21.13.8813 Date 27.10.2017
* OpenCL installed  :  unknown
* OpenCL activated  :  yes

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version 4.0.0**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Additional Tests**
Win10 22H2: Downgrade to version 3.8.1 - now there are no problems with the same RAW files
Ubuntu 22.04:  there are no problems in version 4.0.0 and 4.0.1 with the same RAW files

**Comment by gi-man** [comment]
It would be good to try it with current master. You can try it using the nightly windows build. Do a backup of your library/data.db or use the --configdir flag for safety.

https://github.com/darktable-org/darktable/actions/runs/3610844406

**Comment by 100102533** [comment]
Hi gi-man,

no errors occured with the nightly windows build. I've tested the build successfull in a Windows10-VM and now I have installed it on my original system. Perfect, now I can say "Goodbye LR", "Goodbye C1", "Welcome darktable".  thx :-) 

Best regards
Frank
