### ISSUE TITLE
lighttable displays colors differently in embedded jpgs vs regular jpg files

### ISSUE THREAD

**Issue by toddferrante** [darktable-org/darktable#13097]
**Describe the bug/issue**
I noticed this issue when experimenting with RAW+JPG workflows.  I shot multiple shoots in RAW+JPG mode in my camera.  When examining the images in an alternative image viewer, such as Irfanview, the embedded jpgs in the raw files and the full resolution jpg files appear to be identical, except for resolution.  When imported into Darktable, in lighttable it the embedded jpgs and the regular jpgs are displayed differently.  It appears that maybe one or the other are not being color managed properly, and are being displayed using different color spaces.

I made a series of videos describing various aspects of the RAW+JPG workflow in Darktable, and the issue shows up in all of them.  This video demonstrates the issue pretty clearly. https://youtu.be/l1UnPlRDHzc

**To Reproduce**
- Shoot pictures in RAW+JPG mode on a camera.
- Alternatively, use the sample files in this google drive folder: https://drive.google.com/drive/folders/1hBGUNs8IbW2_92AA8Nv36ASOGMIhOtAr?usp=share_link
- Observe that the embedded jpgs in the RAW files and the full resolution JPGs appear to be identical in a color managed viewer like Irfanview.
- Import the same files into Darktable.
- Observe that they look different from each other in Lighttable

**Expected behavior**
Embedded jpgs in raw files should display identical to the full resolution jpg files.

**Screencast**
See the linked video, above.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* OS                : Windows 10 and Window 11
Observed the same issue on Windows 10 desktop and Windows 11 laptop with completely different hardware configurations.

**Comment by Nilvus** [comment]
That's not darktable goal. See your other similar issues and answer by @AlicVB. Thus, you have an option on preferences (see lighttable tab) to display or embedded jpg files or view depending on processing (manual or automatic at first import) set on darktable.
darktable is raw processing software not a viewer like Irfanview.
