### ISSUE TITLE
Access Violation in module OpenCL.dll

### ISSUE THREAD

**Issue by SulfuricPeach** [darktable-org/darktable#13099]
**Did you buy darktable from an application store ?**

Downloaded directly from darktable.org

**Describe the bug/issue**

When attempting to launch application an unhandled exception occurs. "Access Violation" in "module OpenCL.dll". Full text pasted below.

Attempted uninsta;ll/reinstall. Attempted graphics driver update.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1
* OS                : Win10Pro Build 19045
* Memory            :  32gb PNY DDR4
* Graphics card     : RTX 3070
* Graphics driver   : Nvidia Display Driver v527.37
* OpenCL installed  : -included with graphics driver?-
* 
[darktable_bt_9LDCX1.txt](https://github.com/darktable-org/darktable/files/10178913/darktable_bt_9LDCX1.txt)

**Comment by gi-man** [comment]
Try to see if you have OpenCL compatibility pack installed on windows. Sometimes it gives problems.

https://github.com/darktable-org/darktable/issues/10767

**Comment by SulfuricPeach** [comment]
Ah, my mistake. I uninstalled again, restarted my system, still have the same issue.

**Comment by gi-man** [comment]
You likely can run darktable via darktable --disable-opencl in cmd. Getting the OpenCL to work will really speed up the processing.

Did you install the Nvidia driver from Nvidia? If not try that. I use their game ready version. You can also try posting the results of darktable-cltest

**Comment by SulfuricPeach** [comment]
That command did get the app to open.

Yes, I have tried both the Nvidia studio driver as well as the game ready driver. Also tried reinstalling Darktable on my c drive instead of my f drive where most of my apps are installed. No change.

I have pasted in a screentshot of the output of darktable-cltest below. Also confirmed that OpenCL.dll is in the system, also placed below.
![Capture](https://user-images.githubusercontent.com/120049128/206473318-956f4fd5-bc4d-47ee-a666-47d6e2fd5900.PNG)
![Capture2](https://user-images.githubusercontent.com/120049128/206473332-1e9ecb51-3c1d-4e03-9b25-f562d05a9ad6.PNG)

**Comment by parafin** [comment]
Does output end at "found 2 platforms" message? Given that it says 2, it means that some other OpenCL driver besides Nvidia is installed in the system, and it's most likely is the culprit. Maybe Intel?

**Comment by SulfuricPeach** [comment]
Yes, there are also Intel graphics drivers installed. I output from both the graphics card as well as the integrated motherboard graphics currently as a workaround. However, it appears that both are using the same OpenCL.dll
![Capture](https://user-images.githubusercontent.com/120049128/206476296-b0e5c207-7422-4985-95eb-09d898d05864.PNG)
me OpenCL.dll

**Comment by gi-man** [comment]
Try to update the drivers for the intel GPU to see if that resolves your issue.

I dont recall if in 4.0.1 you can disable the GPU card individually. In the current master you can (about to be released as 4.2 in a couple of weeks). I would disable the intel card and only use your nvidia one for darktable.  This is done via an edit in to the darktablerc file.

**Comment by SulfuricPeach** [comment]
Intel graphics drivers reinstalled, directly from Intel for the latest version. No change.

Glancing around in the settings I do not see it. I have darktablerc open and am glancing through it, not sure how to disable Intel graphics from here. I did try setting OpenCL to false in darktablerc, but that also made no change.

**Comment by gi-man** [comment]
I'm not sure what else to suggest than trying the current master. We do nightly builds for windows. It is very close to what will be released around Christmas. 

https://github.com/darktable-org/darktable/actions/runs/3644287833

**Comment by Nilvus** [comment]
Another test to do could also be to try downgrading graphic cards drivers. Sometimes, it's a regression on recent drivers.

**Comment by jenshannoschwalm** [comment]
This should be solved by lately OpenCL fixes.
