### ISSUE TITLE
Lighttable preview modes display processed RAW even when "use raw file" is set to "never"

### ISSUE THREAD

**Issue by toddferrante** [darktable-org/darktable#13095]
In the full preview layout, a processed RAW view is shown even if the "use raw file instead of embedded jog" option is set to "never".  This also happens in the filemanager layout when "tab" is pressed.  This issue seems to be triggered by the 1080 pixel tall embedded jpgs in the ARW files generated by the a7riii/a9 generation of Sony mirrorless cameras.  The newer generation of cameras, like the a7iv, use higher resolution embedded jpgs in their ARW files.  Darktable displays these embedded jpgs properly in the preview modes.

A full demonstration of the problem is shown in this video.
https://youtu.be/l1UnPlRDHzc

I created a google drive folder with RAW and JPG files from the Sony a7riii and a7iv cameras.  The a7riii raw files trigger the issue, and the a7iv raw files do not.
https://drive.google.com/drive/folders/1hBGUNs8IbW2_92AA8Nv36ASOGMIhOtAr?usp=share_link

**Expected behavior**
When the "use raw file instead of embedded jog" option is set to "never", lighttable should never use the raw file instead of the embedded jpg.

**Which commit introduced the error**
This issue was introduced when going from version 2 to version 3.  I have been using version 2 on my laptop for review sessions with clients, then editing with the latest version on my desktop.  I recently replaced my old laptop, and version 2 won't run on a Windows 11 laptop, so I've been forced to troubleshoot the root cause and look for workarounds.

**Platform**
* darktable version : 4.0.1
* OS                : Windows 10, Windows 11
* Multiple laptops and desktop computers.

**Comment by AlicVB** [comment]
The issue is effectively the size of the embedded preview image.
if the embedded preview is too small for the requested size, dt as no other solution than recreating it... from the RAW file.

What is surprising is that you says version 2 (whaou... that was a long time ago !) managed to extract a preview of the right size and not version 3-4...
I've just tested with your files, and I got this : 
```
...$ exiv2 -pp ./_DSC4800.ARW 
Preview 1: image/jpeg, 160x120 pixels, 8610 bytes
Preview 2: image/jpeg, 1616x1080 pixels, 454479 bytes
```
So exiv2 (the tool used to get infos) only see the 1080 preview...

**Comment by toddferrante** [comment]
If there is a 1080 tall embedded jpg available, and my computer screen is 1080p, should DT be using the embedded preview, since it would be smaller than 1080 on my screen?  That would be my preference.  In fact, with the "never use raw file" option selected, as a user I've indicated that I would prefer a scaled jpg rather than a processed raw file.  To borrow a phrase, "never" means "never". :)

**Comment by AlicVB** [comment]
> If there is a 1080 tall embedded jpg available, and my computer screen is 1080p, should DT be using the embedded preview, since it would be smaller than 1080 on my screen?

yes, it should... the reason why this is not the case is that dt use "steps" of sizes to cache images (size 1 = 0x0 -> 180x110; ...) and for your screen size it request a cached image of size 3 = 1440x900... so the embeded jpeg is not enough for the cache system.
So here, we face a limitation of our caching system... not sure how to solve it, that said...



> In fact, with the "never use raw file" option selected, as a user I've indicated that I would prefer a scaled jpg rather than a processed raw file. To borrow a phrase, "never" means "never". :)

I understand what you mean, but that's not the path we have chosen here : with your screen, if you have a RAW file with an embeded jpeg of size 600, you don't want to use it upscaled for full preview (that would make full preview useless)
We clearly give focus to the quality.
