### ISSUE TITLE
[FR] Make color assessment conditions icon active (optional) when switch between lighttable and darkroom. 

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13107]
**Is your feature request related to a problem? Please describe.**

Sometimes when I am editing a collection of images, if I am in the darkroom and I select the color assessment conditions and I don't want to use the filmstrip to move from one picture to another or I go to look for a specific picture in the collection. If I go to the lighttable to look for an example of the last picture, when I select it and enter the darkroom, the color assessment conditions is off and I have to activate it again.

I know that this does not happen when you are editing a picture and you go to another one with space bar, if the color assessment conditions is active the next picture will be seen with the same activated because the user don't switch between lighttable and darkroom, just switch from a picture to another one, but when the collection is very large and you do not follow a sequential editing one picture after another, but looking for one or another picture alternately, then it is more complicated to search in the filmstrip than to go out to look for the image in the lighttable.

**Describe the solution you'd like**

Have the possibility to optionally declare the color assessment conditions icon active when moving from one photo to another between the lighttable and the darkroom.

**Alternatives**

**Comment by difrkaguilar** [comment]
All icons have the same behavior, guide lines, gamma check, soft proofs, clipping indication, overexposure indication and focus, all of them keep the active state if the user jumps from the darkroom to the light table and selects random images from the collections. But the color evaluation conditions icon is the only one that does not have the same behavior. If it is activated and users go to the light table, select an image and return to the darkroom, the icon is deactivated and needs to be activated again. Selecting the 'icon again each time for each image being reviewed becomes a tedious process, and even more so when adjustments are being made between multiple images.

**Comment by difrkaguilar** [comment]
Pin! :-)

**Comment by difrkaguilar** [comment]
Now , navigating the Ansel fork I saw another user set the same issue for that fork https://github.com/aurelienpierreeng/ansel/issues/168

I love to edit my images of a same session going from lighttable to darkroom switching with the L and D shortcuts and changing to a photo in the collection, not in a sequence manner but in aleatory way, and don´t use the filmstrip because come of my collections are huge and filmstrip does not have a horizontal slider to drag and go fast to desires images (https://github.com/darktable-org/darktable/issues/9919). So, I check the color assessment condition for curating the images, but when I press L to go to the lighttable, select some image and press D to go back to the darkroom the color assessment condition is gone.

**Comment by difrkaguilar** [comment]
Ding!

**Comment by jenshannoschwalm** [comment]
I think this has been fixed in master ...
