### ISSUE TITLE
Mouse input not captured by context menus

### ISSUE THREAD

**Issue by K3RL** [darktable-org/darktable#13105]
Input of mouse is not captured in context menus, but keyboard interaction is possible.

**To Reproduce**
1. Go to lighttable
2. Right-click on star-ratings (filter) in the top row
3. mouseover -> not clickable, no highlighting of the options
4. keyboard input works

**Expected behavior**
capture of mouseover and input on context menus

**Screencast**
[Here](https://files.fm/u/chhhzqndk)

**Platform**
MacOS Ventura 13.0.1
Darktable 4.0.1.1

Thanks for developing and advancing this amazing tool!!!

**Comment by parafin** [comment]
Probably a duplicate of #12727

**Comment by K3RL** [comment]
> Probably a duplicate of #12727

Correct
