### ISSUE TITLE
Bug module Surface Blur on Darktable 4.1.0~git1190.39d46ffa-1

### ISSUE THREAD

**Issue by Christian-Bouhon** [darktable-org/darktable#13109]
Hello,

When I activate the "surface blur" module Darktable crashes when exporting to jpg
This bug occurs on linux without OpenCL and on Windows with OpenCL.

Here is a short video : [https://drive.google.com/file/d/1bRq_U_8FgKqhsWNtSj0zxiWTNuFEwLob/view?usp=share_link](url)

OS : Linuxmint 5 elsie & Windows 11
Kernel: x86_64 Linux 5.10.0-18-amd64
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @ 8x 2.1GHz
GPU: AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.40.0, 5.10.0-18-amd64, LLVM 11.0.1)
RAM: 1677MiB / 13940MiB

Thanking you for your help,
Greetings from Brussels,
Christian

**Comment by MStraeten** [comment]
any idea how to reproduce?
cannot reproduce it on my osx build with integration test image mire1.cr2 and surface blur enabled 
maybe add the backtrace ...

**Comment by pehar1** [comment]
Also not able to reproduce with these marginal specifications. Please provide a detailed step-by-step instuction how to reproduce.

darktable 4.1.0+1182-gf28dff585
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by Christian-Bouhon** [comment]
Hallo,

I have redone different tests.

1. On another computer (Intel I5 4G + Nvidia GPU)
- With the "surface blur" module Darktable did not crash but the processing is very long and consumes a lot of memory.

2. On the laptop AMD Ryzen 5 3500U with Radeon Vega Mobile 
- With smaller files (16 Mpx) from my Pentax K-5 : Ok with a higher memory consumption (11,3 gb)
- With files from my K-1 (36 Mpx) : Darktable crashes because of lack of memory. Here is the return of the command "darktable -d perf". [https://drive.google.com/file/d/1yiF-HTUUMAFRMLm7qoDRovaBgkYVUZq_/view?usp=share_link](url)

As a Darktable user, I think the problem comes from a bad management or too large use of memory by the "Surface Blur" module.
I use this module to fine tune the noise processing

Link to the video and 4 Raw files of my two Pentax. [https://drive.google.com/drive/folders/1bnFinHg2lUDEMoAK9P8zZ3tl9BUMqFG7?usp=share_link](url)

Greetings from Brussels,
Christian

**Comment by gi-man** [comment]
@Christian-Bouhon Can you explain this?

```
﻿cc@cc:~$ darktable -d perf
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
6.680847 [dev] took 0.473 secs (1.229 CPU) to load the image.
```

In the future, can you use Pastebin or similar to create an easier link than the google drive ones. 

All of those processes are using CPU instead of GPU and they dont seem to take too long. You might need to provide a backtrace. This is still unclear.

**Comment by jenshannoschwalm** [comment]
> As a Darktable user, I think the problem comes from a bad management or too large use of memory by the "Surface Blur" module.

What are your resources settings? Any special tuning?

**Comment by Christian-Bouhon** [comment]
Hello,
Hoping that my answer will be useful

@gi-man 
> Can you explain this?

Sorry, I can't tell you, I didn't compile DT, I install it every day via OBS repositories.

> You might need to provide a backtrace. This is still unclear.

Sorry, I can't find a " backtrace " file in the TEMP files, is there a procedure to follow ?
The /var/log/syslog file reports a memory problem
`Dec 10 09:40:18 cc kernel: [  606.646076] [   1835]  1000  1835  6800730  3395064 44322816  1966049             0 darktable
Dec 10 09:40:18 cc kernel: [  606.646078] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=darktable,pid=1835,uid=1000
Dec 10 09:40:18 cc kernel: [  606.646249] Out of memory: Killed process 1835 (darktable) total-vm:27202920kB, anon-rss:13570868kB, file-rss:0kB, shmem-rss:9388kB, UID:1000 pgtables:43284kB oom_score_adj:0
Dec 10 09:40:18 cc systemd[1]: session-1.scope: A process of this unit has been killed by the OOM killer.
Dec 10 09:40:50 cc dbus-daemon[639]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.69' (uid=0 pid=3110 comm="/usr/bin/gdbus call --system --dest org.freedeskto")
Dec 10 09:40:50 cc systemd[1]: Starting PackageKit Daemon...`
[syslog.txt](https://github.com/darktable-org/darktable/files/10199590/syslog.txt)


@jenshannoschwalm 
> What are your resources settings? Any special tuning?

Nothing special, the problem occurs with my Lenovo E595 laptop.
![Capture d’écran du 2022-12-10 10-37-08](https://user-images.githubusercontent.com/120166629/206844127-d0cfe09b-d2b4-4815-996a-6d30f97fffac.png)
![Capture d’écran du 2022-12-10 10-38-54](https://user-images.githubusercontent.com/120166629/206844132-28cc2066-855e-4d72-b80c-0d8fd64b0655.png)

I will do another test this afternoon by increasing the memory to 32gb and will get back to you with the results.

Greetings from Brussels,
Christian

**Comment by TurboGit** [comment]
@Christian-Bouhon : By resource setting the question was more about the value in darktable preferences:

See preferences -> processing -> darktable resource

**Comment by jenshannoschwalm** [comment]
> See preferences -> processing -> darktable resource

Exactly - sorry i wasn't more precise. With "Any special tuning?" i meant: did you modify the settings in the config file? I have seen a number of suggestions in pixls.us suggesting to use unlimited resources or manually tuning the conf entry resulting in a practically unlimited situation...

**Comment by Christian-Bouhon** [comment]
ok, the answer is there.
I had not touched it, the resources were well by default
![Capture d’écran du 2022-12-10 12-09-33](https://user-images.githubusercontent.com/120166629/206854020-36ccaac0-4073-41b2-8617-b4031ca76e87.png)
Here are the results of the different tests with the same photo that caused the problems.
1.  Darktable resources = default
- Surface blur modules activated = plant.
- Surface blur modules disabled = memory usage +/- 6.2 gb and 38'' of processing
2.  Darktable resources = small
- Surface blur modules activated =  memory usage +/- 7.2 gb and 1'54'' of processing.
- Surface blur modules disabled = memory usage +/- 4.6 gb and 50'' of processing
3. Laptop upgrade to 32gb ram & Darktable resources = default
- Surface blur modules activated = memory usage +/- 24.9 gb and 1'28'' of processing

Conclusion
- My problem is solved, many thanks for your help.
- With my configuration, the problem only occurred with the "surface blur" module.   
- Is it that the "Darktable resources = default" setting limits the available memory?

Greetings from Brussels
Christian

**Comment by ralfbrown** [comment]
Surface blur needs more memory the lower you set the radius/red/green/blue values, because it needs to more finely subdivide the five-D space of (x,y,r,g,b) values.  It's possible that the tiling code underestimated the memory requirements for the settings you used.

**Comment by jenshannoschwalm** [comment]
The module is missing a `tiling_callback()` so taking defaults and thus effectively disable tiling as not knowing the requirements.

**Comment by Christian-Bouhon** [comment]
Hello,

> The module is missing a `tiling_callback()` so taking defaults and thus effectively disable tiling as not knowing the requirements.

Sorry, but for me, it's semantics, I guess you can add the missing piece of code. ;-)

Greetings from Brussels
Christian

**Comment by ralfbrown** [comment]
> The module is missing a `tiling_callback()` so taking defaults and thus effectively disable tiling as not knowing the requirements.

The Surface Blur module does have a tiling callback.  Were you looking at the correct file (iop/bilateral.cc)?

**Comment by jenshannoschwalm** [comment]
> The Surface Blur module does have a tiling callback

No i didn't :-( So we have to look there if the data are correct :-) I don't know that code at all. Can you have a look?

**Comment by ralfbrown** [comment]
I'm actually the author of the current tiling_factor computation, and it seems that my worst-case hashtable size is not actually the worst case....
I'm afraid I won't have time to look at it in more detail until at least the 19th, and when I do I should try to make the computation take the current parameters into account to minimize tiling.
