### ISSUE TITLE
Selecting lossless for WebP export causes a SegFault

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#13113]
**Did you buy darktable from an application store ?**
OSB

**Describe the bug/issue**

I keep testing some of the new functionality for 4.2 trying to find bugs. I was testing an export of WebP using the lossless format. The default of Lossy works, but as soon as I select Lossless, darktable crashes.

**To Reproduce**
- Go to Export module
- Select WebP
- Change compression from Lossy to Lossless

**Expected behavior**
No crash and lossless works

Backtrace
```
Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
0x00007fffb3ff2493 in compression_changed (widget=<optimized out>, gui=0x0) at /home/gman/darktable/src/imageio/format/webp.c:357
357       gtk_widget_set_visible(gui->quality, comp_type != webp_lossless);
```

**Platform**

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : Fedora 37 KDE X11 16Gb Nvidia 3060 12Gb OpenCL Active

**Comment by Mark-64** [comment]
Confirmed in Windows 11

**Comment by TurboGit** [comment]
And fixed :) Thanks for reporting.
