### ISSUE TITLE
Segfaul-coredump when navigating between images in Darkroom. Seems reproducable.

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#13123]
I get a segmentation fault - core dumped.

I can reproduce it on my PC.  I use DT 4.0.1  (latest) on Kubuntu Linux, kernel 5.15.

I hope it can be reproduced. I have included 3 images, there are no privacy or copyright issues, I just shot these to test the hand held high res mode on my camera. 

I get a segfault when I do this:
- import the directory with these 3 images (to reproduce I don't need to re-import. It works every time).
- sorting order of images does not seem to matter
- open the 1st image
- zoom in on the number '26' at the center of the image
- zoom in beyond the max zoom level using CTRL+mousewheel. 
- navigate to the next picture using <Space>
- if DT has not crashed by now, navigate back to the 1st picture using <backspace>.

Notes:
It only crashes when I navigate between images when zoomed in beyond the max zoom.
There seems to be a relation with the hand held high res. These images are a mix between normal raws and hand held high res raws.  It does not happen on only-normal raws. 

I don't have a debug version of DT and I don't know where the dump went.
If I can help to get a core dump your way, please tell me where to find it.

Here is the link, it works until the 1s of jan. 
https://cloud.farside.nl/s/oe8irFT3jcAmmH4

**Comment by rekcodocker** [comment]
Only happens beyond the max zoom, when you start seeing pixels. Otherwise it does not happen. 
If there is anything I can do, like run a debug version or something, let me know.

**Comment by Mark-64** [comment]
> Only happens beyond the max zoom

Yes, I arrived up to 1600%


> If there is anything I can do, like run a debug version or something, let me know

You might build the current master, the problem might have been already solved. Or just wait few days, 4.2 is close.

**Comment by pehar1** [comment]
Could this have a similar cause as https://github.com/darktable-org/darktable/issues/13109 ?

**Comment by pehar1** [comment]
Tried to reproduce with your images by running _darktable_ under _gdb_ as a fresh install (empty `.config/darktable`). Tried for a quarter of an hour, with OpenCL enabled and disabled, panning around, zooming in and out, switching forth and back between images, but not able to reproduce.

darktable 4.1.0+1196-gd24700282
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : tried yes and no
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by rekcodocker** [comment]
Then best close it.  I'll check again on version 4.2.
Thanks for looking in to it y'all.
