### ISSUE TITLE
levels/rgb levels precision point adjustment by scroll wheel

### ISSUE THREAD

**Issue by douzzer** [darktable-org/darktable#13129]
There is currently a hardcoded interval for scroll wheel movement of the black, gray, and white points in `levels` and `rgb levels`.  Unlike in normal sliders, `_SHIFT_` is ignored, and `_CONTROL_` results in aspect ratio adjustments, not extra-fine interval.

I'm now using the below patch locally to get what I need.  It's not ideal, because there is still no user adjustability as there is for normal sliders, but it's an easy improvement.  Note that fine control is by shift+control, to preserve the incumbent behavior of `_CONTROL_` by itself (aspect ratio adjustment).

```
--- darktable-4.0.1/src/iop/rgblevels.c.dist	2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/rgblevels.c	2022-12-11 15:20:36.578086588 -0600
@@ -667,7 +667,14 @@ static gboolean _area_scroll_callback(Gt
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  float interval; // Distance moved for each scroll event
+  if (dt_modifier_is(event->state, GDK_SHIFT_MASK))
+    interval = 0.02;
+  else if (dt_modifier_is(event->state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
+    interval = 0.00005;
+  else
+    interval = 0.002;
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     const float new_position = p->levels[c->channel][c->handle_move] - interval * delta_y;
--- darktable-4.0.1/src/iop/levels.c.dist	2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/levels.c	2022-12-11 15:22:57.069980757 -0600
@@ -978,7 +978,14 @@ static gboolean dt_iop_levels_scroll(Gtk
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  float interval; // Distance moved for each scroll event
+  if (dt_modifier_is(event->state, GDK_SHIFT_MASK))
+    interval = 0.02;
+  else if (dt_modifier_is(event->state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
+    interval = 0.00005;
+  else
+    interval = 0.002;
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     float new_position = p->levels[c->handle_move] - interval * delta_y;
```

**Comment by dterrahe** [comment]
You might consider using dt_accel_get_speed_multiplier to get the same user configurable multipliers as are used for sliders. Search the code for examples. You'll want to strip out the GDK_SHIFT_MASK from the status when responding to shift+Ctrl. The fact that Ctrl was already taken was the exact reason I decided against applying this here, but feel free to suggest in a PR and see what people think.

**Comment by douzzer** [comment]
@dterrahe good advice.  I see two viable paths forward.

First (and to me preferred) path forward is to remap shift-control-scroll as the chord to adjust the aspect ratio, restoring normal mappings for ctrl and shift re `interval`.  I'm now running this locally and it makes sense to me:
```
--- darktable-4.0.1/src/iop/rgblevels.c.dist	2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/rgblevels.c	2022-12-14 13:07:47.002073951 -0600
@@ -647,7 +647,7 @@ static gboolean _area_scroll_callback(Gt
   int delta_y;
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
-    if(dt_modifier_is(event->state, GDK_CONTROL_MASK))
+    if(dt_modifier_is(event->state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
     {
       //adjust aspect
       const int aspect = dt_conf_get_int("plugins/darkroom/rgblevels/aspect_percent");
@@ -667,7 +667,9 @@ static gboolean _area_scroll_callback(Gt
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  const float multiplier = dt_accel_get_speed_multiplier(widget, event->state);
+  const float interval = 0.001 * multiplier; // Distance moved for each scroll event
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     const float new_position = p->levels[c->channel][c->handle_move] - interval * delta_y;
--- darktable-4.0.1/src/iop/levels.c.dist	2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/levels.c	2022-12-14 13:07:39.753936055 -0600
@@ -958,7 +958,7 @@ static gboolean dt_iop_levels_scroll(Gtk
   int delta_y;
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
-    if(dt_modifier_is(event->state, GDK_CONTROL_MASK))
+    if(dt_modifier_is(event->state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
     {
       //adjust aspect
       const int aspect = dt_conf_get_int("plugins/darkroom/levels/aspect_percent");
@@ -978,7 +978,9 @@ static gboolean dt_iop_levels_scroll(Gtk
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  const float multiplier = dt_accel_get_speed_multiplier(widget, event->state);
+  const float interval = 0.001 * multiplier; // Distance moved for each scroll event
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     float new_position = p->levels[c->handle_move] - interval * delta_y;
```

The other (I think disfavored) path forward is to special-case ctrl+shift for the fine multiplier:
```
--- darktable-4.0.1/src/iop/rgblevels.c.dist	2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/rgblevels.c	2022-12-11 15:20:36.578086588 -0600
@@ -667,7 +667,12 @@ static gboolean _area_scroll_callback(Gt
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  GdkModifierType masked_state = event->state;
+  if (dt_modifiers_include(masked_state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
+    masked_state &= ~GDK_SHIFT_MASK;
+  const float multiplier = dt_accel_get_speed_multiplier(widget, masked_state);
+  const float interval = .001 * multiplier; // Distance moved for each scroll event
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     const float new_position = p->levels[c->channel][c->handle_move] - interval * delta_y;
--- darktable-4.0.1/src/iop/levels.c.dist	2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/levels.c	2022-12-11 15:22:57.069980757 -0600
@@ -978,7 +978,12 @@ static gboolean dt_iop_levels_scroll(Gtk
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  GdkModifierType masked_state = event->state;
+  if (dt_modifiers_include(masked_state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
+    masked_state &= ~GDK_SHIFT_MASK;
+  const float multiplier = dt_accel_get_speed_multiplier(widget, masked_state);
+  const float interval = .001 * multiplier; // Distance moved for each scroll event
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     float new_position = p->levels[c->handle_move] - interval * delta_y;
```

**Comment by dterrahe** [comment]
Thing is, ctrl+scroll is the standard for resizing graphs. If you change it, people might get annoyed with you. Especially if, for consistency, you were to change it for _all_ graph/widget resizes (otherwise you would just trade one inconsistency for another).

ctrl+scroll for smaller changes wasn't implemented here, might not be discovered by anybody and maybe is little used even for sliders (most people seem to drag). So you won't get many thank yous.

I'm just being honest because I wouldn't want your _first_ contribution here to be a negative experience (unexpectedly).

Question: you are already halving the default value; do you really think you'll fiddle much with changes 10 times smaller? Just having _shift_ for larger moves might be sufficient most of the time and now and then a _ctrl+shift_ for when it _really_ matters somehow wouldn't be too much of a hassle? Or could even be left out completely. Now that you are using dt_accel_get_speed_multiplier you could even tailor the default speed for this widget so it is even more fine grained for you without bothering anybody else.

Question 2: any particular reason to not simply do the specific replacement you want, as in
```
if(dt_modifiers_is(masked_state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
  masked_state = GDK_CONTROL_MASK;
```

**Comment by douzzer** [comment]
Sounds like we need the second patch.

As for why I used the `&= ~GDK_SHIFT_MASK` construct, I didn't want to make any unnecessary assumptions about how `dt_accel_get_speed_multiplier()` interprets its 2nd arg, now or in the future.

**Comment by dterrahe** [comment]
> I didn't want to make any unnecessary assumptions

Fair enough, but I meant especially `dt_modifiers_include` vs `dt_modifiers_is`. Seems you are (unintentionally?) replacing _ctrl+shift+alt_ with _ctrl+alt_ as well, which probably nobody will notice but still is unnecessary/unwanted.

Now that you've made me mull it over a little more, I would go for the absolute minimum patch, just adding `* dt_accel_get_speed_multiplier(widget, event->state)` to the definition of interval, leaving the default at 0.002. Then for yourself you can still set a custom speed in the shortcuts dialog (double-click on the "levels" action and scroll up and type in an exact value if you don't want .1). This only works for rgblevels, since the old levels graphs has not been turned into a full shortcuttable action (I believe it is semi-deprecated? I may be wrong). You can also amend the _shift+ctrl_ fallback for `fallbacks/value`. By default it is set to *10, for consistency with sliders, where this combination is processed at the widget, not value, level to change the _element_ to _force_ with _speed_ *10 . But it is not _necessary_ anywhere. You can then for example set .001 for default and .5 for _shift+ctrl_ (which may be more useful then adjustments of 0.0001?)

**Comment by douzzer** [comment]
I'm trialing the below patch now -- it seems to strike the right balance, preserving all incumbent behaviors, but adding access to the `_speed_multiplier()`.  With base `interval` .002, the resulting default fine adjust (.0002) is a just hair above the threshold of perception in dark areas with `filmic` disabled.  Seems good to me.

This patch is just my earlier patch to map shift+control to fine, but fixed up as you suggested.  I agree we definitely don't want to globally change the mapping for graph aspect ratio adjust.

```
--- darktable-4.0.1/src/iop/rgblevels.c.dist    2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/rgblevels.c 2022-12-11 15:20:36.578086588 -0600
@@ -667,7 +667,12 @@ static gboolean _area_scroll_callback(Gt
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  GdkModifierType masked_state = event->state;
+  if (dt_modifier_is(masked_state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
+    masked_state &= ~GDK_SHIFT_MASK;
+  const float multiplier = dt_accel_get_speed_multiplier(widget, masked_state);
+  const float interval = .002 * multiplier; // Distance moved for each scroll event
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     const float new_position = p->levels[c->channel][c->handle_move] - interval * delta_y;
--- darktable-4.0.1/src/iop/levels.c.dist       2022-09-12 02:00:36.000000000 -0500
+++ darktable-4.0.1/src/iop/levels.c    2022-12-11 15:22:57.069980757 -0600
@@ -978,7 +978,12 @@ static gboolean dt_iop_levels_scroll(Gtk
 
   if(darktable.develop->gui_module != self) dt_iop_request_focus(self);
 
-  const float interval = 0.002; // Distance moved for each scroll event
+  GdkModifierType masked_state = event->state;
+  if (dt_modifier_is(masked_state, GDK_CONTROL_MASK | GDK_SHIFT_MASK))
+    masked_state &= ~GDK_SHIFT_MASK;
+  const float multiplier = dt_accel_get_speed_multiplier(widget, masked_state);
+  const float interval = .002 * multiplier; // Distance moved for each scroll event
+
   if(dt_gui_get_scroll_unit_deltas(event, NULL, &delta_y))
   {
     float new_position = p->levels[c->handle_move] - interval * delta_y;
```

**Comment by douzzer** [comment]
Oh and regarding your thought of keeping the dumbed-down scroll bindings (no chords) but just adding `* dt_accel_get_speed_multiplier(widget, event->state)`, no I don't think that's viable, and it certainly wouldn't result in the UX I'm looking for.  If chord-based varispeed scroll wheeling is useful on level sliders, and it is, then it's equally useful in graphs.

**Comment by dterrahe** [comment]
> dumbed-down scroll bindings (no chords)

?

To repeat what I said above, this would allow you to define the ctrl+shift multiplier as *.1 (or something else, in fallbacks/value), gives you the *10 shift multiplier by default and even allows you to set different multipliers for alt, alt+ctrl, alt+shift and ctrl+alt+shift if you want. The _only_ thing it doesn't do is force the same * .1 multiplier for ctrl+shift that you use for other values, so arguably it gives _more_ flexibility. But _by default_ it doesn't set up the *.1, that's true. It would require a one time action. If that's important to you, then go ahead; I was only suggesting what _I_ would do, if I cared about these modules.

**Comment by douzzer** [comment]
Ah sorry, I totally misread your explanation.

I haven't yet set up shortcuts in the way you described -- let me learn my way around that.  It sounds fit for purpose.

I don't like the sound of "the old levels graphs has not been turned into a full shortcuttable action" but we'll cross that bridge when we get to it.  If I understand correctly, the only missing piece would be that old levels wouldn't have access to a custom binding around shift+ctrl.  Given your strategy properly fixes it for rgblevels, perhaps it's too much sweating the details to try to make it perfect for old levels too.  And that missing piece certainly wouldn't impact my use case.

**Comment by dterrahe** [comment]
> I totally misread your explanation.

That was clear :-) No worries.

> only missing piece would be that old levels wouldn't have access to a custom binding around shift+ctrl.

No that would work fine. The missing pieces are being able to customise the _default_ speed (i.e. _without_ holding modifiers) and being able to add the widget to the quick access panel (both solveable with one call to `dt_action_define_iop` in `gui_init`) and being able to define shortcuts to manipulate the widget (this would require quite a bit of extra code and my guess is it would be used by exactly 0 people ever).
