### ISSUE TITLE
Masking: couldn't enqueue kernel! CL_INVALID_KERNEL_ARGS

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#13120]
**Describe the bug/issue**

    couldn't enqueue kernel! CL_INVALID_KERNEL_ARGS

when drawn masks are enabled, even if no shapes are used in the module.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Apply https://discuss.pixls.us/uploads/short-url/cctpu6nAO59WGE5xRHfZc6ARojr.xmp to any raw file.
2. Check `-d opencl` logs
3. See `couldn't enqueue kernel! CL_INVALID_KERNEL_ARGS`
4. Check _color balance rgb_: drawn masks, but no shape assigned.
![image](https://user-images.githubusercontent.com/3177739/206900522-250daad8-f942-4e4b-872f-e306cec009a7.png)
5. Switch to blending _off_, _uniformly_ (_parametric mask_ also shows the error).

**Expected behavior**
No error, image processed on GPU.

**Platform**

* darktable version : 4.1.0+1201~g839b7f063
* OS                : `Linux eagle 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 22.10
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 525.60.11-0ubuntu0.22.10.1, also 510.108.03 and 470.161.03-0ubuntu0.22.10.1
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 7.7+23ubuntu2   
* Desktop           : KDE
* GTK+              : 3.24.34-3ubuntu2
* gcc               : 12.2.0-3ubuntu1
* cflags            : N/A
* CMAKE_BUILD_TYPE  : Release

**Additional context**
See https://discuss.pixls.us/t/did-something-change-inside-the-nightly-build-of-diffuse-or-sharpen-module/34038/

Config from Aliks (who originally reported this on Pixls): Linux Mint 20.3 ; NVIDIA GeForce RTX 3060/PCIe/SSE2 v: 4.6.0 NVIDIA 510.108.03

**Comment by MStraeten** [comment]
not reproducible with osx, so maybe a system configuration specific issue. 
Maybe the result of darktable-cltest can give some hints ...

**Comment by kofa73** [comment]
Interesting. For me, it works literally on all raws I've tried (the original CR3, a NEF, an RW2). Linux, Release build.

**Comment by AndDiSa** [comment]
It's reproduceable from my side, too. Applying the provided sidecar file immediately leads to the error.

Darktable: darktable 4.1.0+1201~g839b7f063
OS: Linux ThinkBook 6.0.0-1007-oem #7-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 25 18:05:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux - Distro : Ubuntu 22.04
Memory : 32 GB
Graphics card : NVIDIA GeForce RTX 3060 Laptop GPU 6GB
Graphics driver : 525.60.11
OpenCL installed : yes
OpenCL activated : yes
CMAKE_BUILD_TYPE : Release

**Comment by jenshannoschwalm** [comment]
We had the big & important #12677, maybe here is an issue.

**Comment by kofa73** [comment]
@jenshannoschwalm : confirmed.
No problem with 4.1.0+667~gebaa525a0, which was before that merge.
4.1.0+677~ga4bd3cd7c exhibits the issue.

**Comment by kofa73** [comment]
@jenshannoschwalm : confirmed.
`4.1.0+677~ga4bd3cd7c` has the issue.
`4.1.0+667~gebaa525a0` does not.

**Comment by TurboGit** [comment]
Now fixed.

**Comment by kofa73** [comment]
Confirmed, thanks!
