### ISSUE TITLE
sqlite3 errors due to invalid SQL commands

### ISSUE THREAD

**Issue by AndDiSa** [darktable-org/darktable#13134]
**Describe the bug/issue**
SQL syntax errors thrown on startup, no image collections loaded

**To Reproduce**
start darktable

**Expected behavior**
No SQL errors

**Screenshots**
![image](https://user-images.githubusercontent.com/550244/207111846-92f062f2-de6d-417b-a735-7c722a1a70c4.png)

**Which commit introduced the error**
Author: Aldric Renaudin <alic.vb@gmail.com>
Date:   Sun Dec 11 20:12:43 2022 +0100

    collect : separate collect and filter in query

8856a4c585ddfb817a97f609abc65db28a55badb

**Platform**
Darktable: darktable 4.1.0+1220~g26ca75f22
OS: Linux ThinkBook 6.0.0-1007-oem https://github.com/darktable-org/darktable/pull/7-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 25 18:05:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux - Distro : Ubuntu 22.04
Memory : 32 GB
Graphics card : NVIDIA GeForce RTX 3060 Laptop GPU 6GB
Graphics driver : 525.60.11
OpenCL installed : yes
OpenCL activated : yes
CMAKE_BUILD_TYPE : Release

**Comment by TurboGit** [comment]
I had the same issue it was fixed after I had removed the filters and added them back.

**Comment by AndDiSa** [comment]
@TurboGit I'll try to do so ...

**Comment by MStraeten** [comment]
cannot reproduce on osx even after defining filters with an older build 
can you provide the filter setting that failed?

**Comment by AndDiSa** [comment]
@TurboGit you are right, resetting all filters leads to a working system again.

**Comment by AndDiSa** [comment]
@MStraeten nothing special, time range and stars

**Comment by parafin** [comment]
This should be resolved or a lot of users will have the same problem when they update to new release.

**Comment by AlicVB** [comment]
ok, I've reproduce the issue, which happen if the first filter is empty or disabled.
PR #13138 should fix it
