### ISSUE TITLE
Rotate doesn't recalculate "automatic cropping" when copying the operation

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#13135]
**Describe the bug/issue**
When copying a "rotate & perspective" from one image to another, the "automatic cropping" doesn't get recalculated correctly.

**To Reproduce**
1. import a RAW file, export as-is into a TIFF file
2. import the TIFF file
3. apply rotate to the RAW file, with "automatic cropping" sets to "largest area"
4. copy the rotate operation from RAW to TIFF, the "automatic cropping" is applied incorrectly in the TIFF

**Expected behavior**
The TIFF should have the same "automatic cropping" as the RAW. 

**Observation**
Making a change in the "rotate & perspective" of the TIFF, .e.g changing angle or automatic cropping setting would recalculate the correct cropping. Looks like that automatic cropping calculation just needs to be triggered when the operation get pasted/added to the destination (TIFF) file. Loading a sidecar file also has the same problem: the automatic cropping doesn't get calculated correctly.

**Screenshots**
![Screenshot from 2022-12-12 11-10-47](https://user-images.githubusercontent.com/1099071/207111252-a1a970ba-f738-42d8-b32f-f85be1d1933b.png)
![Screenshot from 2022-12-12 11-13-05](https://user-images.githubusercontent.com/1099071/207111259-8cf3082d-39dd-4c07-80ad-58b8ab241dd7.png)

**Platform**

* darktable version : 4.1.0+1201~g839b7f063-dirty
* OS                : Linux - kernel 5.15.0-56-generic
* Linux - Distro    : Ubuntu 22.04
* Memory            :  32GB
* Graphics card     :  GTX 3060
* Graphics driver   :  5.10
* OpenCL installed  :  yes
* OpenCL activated  :  yes

**Comment by ActarusLeGrand** [comment]
I have same thing here in windows. I copy a crop from an image, when I paste on another it's not the same size on the pasted picture.

**Comment by hqhoang** [comment]
Just found out that it is related to orientation. The RAW was in landscape, auto-rotated to portrait by orientation/flip (due to EXIF orientation info), thus the exported TIF is in portrait. The rotation op was copied as-is with auto-crop data, but applied incorrectly due to mismatch in image dimension (swapped width and height).

If I don't apply orientation/flip to the RAW before exporting to TIF, the TIF retains original landscape orientation/dimension as the RAW, and the auto-crop will apply correctly.

Closing this ticket as it's not a bug. Thanks.
