### ISSUE TITLE
Nikon D3s

### ISSUE THREAD

**Issue by superpooer** [darktable-org/darktable#13136]
I uploaded all the formats requested for the Nikon D3s on raw.pixls.us. I'd be happy to contribute more samples if necessary, especially regarding noise profiling, although I don't exactly know what goes into this.

**Comment by kmilos** [comment]
Duplicate and resolved, see all the related issues here: https://github.com/darktable-org/darktable/search?q=d3s&type=issues

As for noise profile, samples are not needed. See https://github.com/darktable-org/darktable/wiki/Camera-support

**Comment by Nilvus** [comment]
@superpooer: please search before opening an issue. There's already not only one issue posted before but 5!
