### ISSUE TITLE
sqlite3 error on "4.1.0+1219~ga01622bbb" build

### ISSUE THREAD

**Issue by kikoucalou** [darktable-org/darktable#13137]
On darktable 4.1.0+1219~ga01622bbb build from git src

When starting  , I get an sqlite3 error :

....  /darktable/src/common/collection.c:952, function _dt_collection_compute_count(): near "AND": syntax error  ....

I can see loading images message, but I cant see any images on lighttable screen

**Platform**
* ThinkStation-S30 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* darktable version : 4.1.0+1219~ga01622bbb
* DISTRIB_ID=LinuxMint
* DISTRIB_RELEASE=21
* DISTRIB_CODENAME=vanessa
* DISTRIB_DESCRIPTION="Linux Mint 21 Vanessa"
* CPU: 8-core Intel Xeon E5-2690 0 (-MT MCP-) speed/min/max: 1622/1200/3800 MHz
* Kernel: 5.15.0-46-generic x86_64 Up: 5h 20m Mem: 7939.4/32054.3 MiB (24.8%)

**Additional context**

Prior build darktable 4.1.0+1201~g839b7f063 works fine.

**Comment by MStraeten** [comment]
See https://github.com/darktable-org/darktable/issues/13134

**Comment by AlicVB** [comment]
PR #13138 should fix it
