### ISSUE TITLE
Linear rec2020 and Linear ProPhoto export produce different results to what is on screen

### ISSUE THREAD

**Issue by jorismak** [darktable-org/darktable#13141]
With certain colours (the problem colours, like bright saturated reds, or the yellows/orange of a bright sun most notably),
the export that Darktable produces has a shift in colour when compared to what is on screen.

This happens when exporting to linear-rec2020, but also to linear-prophoto. It does **_not_** happen when exporting to linear rec709. Also, setting the 'output color profile' to match the selected export profile seems to make no difference.

The raw file from this pixls thread is a good example: https://discuss.pixls.us/t/possible-case-of-filmics-preserve-chrominance-not-applied-in-exporting/34088

And this is the (zipped) xmp that I use for exporting
[_DSC8850.ARW.xmp.zip](https://github.com/darktable-org/darktable/files/10218426/_DSC8850.ARW.xmp.zip)

Export options used in testing:
![image](https://user-images.githubusercontent.com/47725838/207340090-ed7705bc-36ec-4669-9842-9ea9a47bd7c6.png)

Export one image in linear-rec2020, and one in linear rec709, and one in normal sRGB.
Open them in your favourite - colour managed - image viewer, and compare the differences. Now compare those images with what Darktable is showing on your screen while editing the image.

From my exerperience, this is a screenshot sized down from the Darktable window:

![dt-screengrab](https://user-images.githubusercontent.com/47725838/207341618-88c801aa-835e-4096-b003-295dc07cc932.jpg)

This is the export, exported at linear rec2020, and converted with imagemagick to Elle's sRGB-elle-V4-srgbtrc.icc:
![_DSC8850_dt](https://user-images.githubusercontent.com/47725838/207342193-1111698b-0071-4ff1-a964-d848b39b9ae4.jpg)

Flip between those two to see the differences in colour.

From comparing the export to what I see on screen, the sRGB / linear-rec709 seem to be 'the correct' ones. This is what I see during editing, so this is what I expect to see in the export.

Of course, exporting to a profile with a larger gamut can 'store stuff' my screen can't display. But when that file is converted to sRGB, I expect it to look the same as an export to sRGB. And on my 100% sRGB calibrated monitor, I expect the preview to be pretty much the same as the sRGB output, even when exported first to linear rec2020, right?

It just seems that somewhere there is an assumption for sRGB colour gamut made, or a step is skipped.
Aurelien had a whole part about 'color out is broken' and started ripping stuff out. Is this related / the same? Or is that just removing the 'output-color-space-module' ?

https://github.com/aurelienpierreeng/ansel/tree/remove-colorout
https://github.com/aurelienpierreeng/ansel/issues/25

**Which commit introduced the error**
> _If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

I've noticed this earlier, but **_thought_** I had it under control by matching the 'output color profile'-module with the output-profile selected in the export settings. I've had it on my own photos in bright orange skies, which became much more saturated on export (in linear rec2020) vs what I was seeing on screen.

* darktable version : 4.1.0-1124, custom mingw64 build, Windows 11

**Comment by todd-prior** [comment]
For me I think that this shows that things are working fine on my box but perhaps there is something going on worth investigating  https://discuss.pixls.us/t/possible-case-of-filmics-preserve-chrominance-not-applied-in-exporting/34088/20?u=priort

**Comment by jorismak** [comment]
@flannelhead explained that this might actually be by design , with filmic looking at the 'target' export in play and mapping gamut in its own way.

So by exporting to a wide linear profile , filmic has to do almost no gamut mapping. But export to a narrower profile and filmic kicks in do it's own gamut mapping. 

If this is true , then this ticket can be closed

**Comment by todd-prior** [comment]
> Just out of curiosity, does filmic respect the perceptual/relative/absolute output profile rendering intents, any change if you play with those?

I dont think these work with DT profiles... I took a color checker forced it out of gamut and then even more out of gamut and then exported with all intents and I put fixed markers on all the patches and the values were identical for all intents when I opened the exported files... maybe there is a flaw in my logic...

**Comment by jorismak** [comment]
> Just out of curiosity, does filmic respect the perceptual/relative/absolute output profile rendering intents, any change if you play with those?

I don't it looks at that, since it's doing its own thing. It's not converting to a colour space yet, remember that! It's just limiting the gamut that's in use.

After flimic, the image is still in the working profile. Filmic is managing the gamut since it has access to the full scene-referred data and can make better decisions compared to normal colour-space conversion. I'm guessing that's the idea at least.

So, don't confuse filmic v6's gamut mapping as a colour-profile conversion. It **_is_** looking at which profile you **intent** to use, and limits the gamut accordingly.

And this causes my confusion / problem. Since what I'm looking at on screen is filmic using sRGB (or my display profile, they are close) to do the gamut mapping, but when I export to linear rec2020 this changes quite a lot and suddenly filmic's gamut mapping doesn't do much at all (by design). But it does cause a stark difference in what I see on screen and what I output.

I can bypass it by not exporting to linear rec2020, but somewhere somehow I think it also should be possible to 'declare my intent' to use linear rec2020 as export and see _that_ on screen. (As in, let filmic use whatever is selected in the output-profile-module, so it uses that for gamut mapping... but then manage the output to be displayed on my sRGB / monitor profile... just as if converting the final output from linear-rec2020 to whatever the display profile is, with something like LCMS2).

**Comment by jorismak** [comment]
> Just out of curiosity, does filmic respect the perceptual/relative/absolute output profile rendering intents, any change if you play with those?

I'm pretty sure these aren't at all in play. This is a custom gamut mapping algorithm filmic does by looking at the target profile. Since you can't even select the intent in the normal output-profile-module, I find it hard to imagine filmic does anything with the option you select all the way in the export dialog.
