### ISSUE TITLE
Failed to build git/head  - (error: ‘private’ may be used uninitialized)

### ISSUE THREAD

**Issue by JeanLucCoulon** [darktable-org/darktable#13154]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Got a fresh copy of the git repository, with the submodules
2. Issue: ./build.sh from darktable directory
3. got the following
[ 60%] Linking C shared module libhistory.so
/usr/local/src/darktable/darktable-4.2.0/src/libs/tagging.c: In function '_pop_menu_dictionary_edit_tag':
/usr/local/src/darktable/darktable-4.2.0/src/libs/tagging.c:1936:24: error: 'private' may be used uninitialized [-Werror=maybe-uninitialized]
 1936 |                       (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(private)) ? DT_TF_PRIVATE : 0));
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
gmake[2]: *** [lib/darktable/plugins/lighttable/CMakeFiles/tagging.dir/build.make:76: lib/darktable/plugins/lighttable/CMakeFiles/tagging.dir/tagging.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:3075: lib/darktable/plugins/lighttable/CMakeFiles/tagging.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 60%] Built target backgroundjobs

**Platform**
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Memory, 16Go

darktable version : git, d1c663b667e942afb232ef90cd8f13e9fa0abacb
OS                : GNU Linux - kernel 6.1.0
Linux - Distro    : Debian sid
Graphics card     :  Integrated attachment, Intel HD Graphics 530

If I remove -Werror from the ./src/CMakeLists.txt, everything went fine.

Regards
Jean-Luc
[build.log](https://github.com/darktable-org/darktable/files/10248089/build.log)

**Comment by Nilvus** [comment]
I use darktable and can't reproduce (I always clean my darktable folder to be like a fresh copy of git repository, before compiling). Removing Werror do not seems a good idea as it's there to show build error. I use also Debian Sid. Probably something specific on your side and not on darktable. Code is frozen since 2 days now and we are some people to use it daily, without issue. Using build.sh only is not the optimal way to build darktable. I use a script to compile it, clean folder before each compiling and update submodules. See it below:

```
### Building manually

#!/bin/sh

cd /home/nilvus/Projets/darktable
rm -rf build /opt/darktable

# if it's a new folder source code, think about adding this line after a git submodule init: 'git config submodule.src/tests/integration.update none'

git pull
git submodule update
./build.sh --prefix /opt/darktable --build-type Release --install

exit 0
```

**Comment by dterrahe** [comment]
Could you try changing lines 1812-1813 to
```
  GtkWidget *private = NULL;
  GtkWidget *category = NULL;
```
i.e. add an explicit initialisation?

**Comment by JeanLucCoulon** [comment]
> Could you try changing lines 1812-1813 to
> 
> ```
>   GtkWidget *private = NULL;
>   GtkWidget *category = NULL;
> ```
> 
> i.e. add an explicit initialisation?

Hi,
I've just changed the 2 offending lines and rebuilt dt that way.
It works.

Regards
J-L

**Comment by Nilvus** [comment]
@dterrahe: is this could be closed or given your code changes suggestion, this need an update on master?
