### ISSUE TITLE
Canon EOS R7 noise profiles

### ISSUE THREAD

**Issue by mpetroff** [darktable-org/darktable#13152]
Here is a noise profiles tarball for the Canon EOS R7, for inclusion in Darktable:
[darktable-noiseprofile-20221215-canon-eos-r7.tar.gz](https://github.com/darktable-org/darktable/files/10240715/darktable-noiseprofile-20221215-canon-eos-r7.tar.gz)

Thanks.

**Comment by RomanSammer** [comment]
I also created a Noise Profile for the Canon EOS R7. Maybe you can use this for further development.
[darktable-noiseprofile-20221226.tar.gz](https://github.com/darktable-org/darktable/files/10303412/darktable-noiseprofile-20221226.tar.gz)

**Comment by rawfiner** [comment]
Sorry for the late review. Could you profile as well the extended ISO values? Thanks!

**Comment by mpetroff** [comment]
Here are the plots for ISO 51200 (the only extended ISO value that I'm aware of):
[darktable-noiseprofile-20230131-iso-51200.tar.gz](https://github.com/darktable-org/darktable/files/10550392/darktable-noiseprofile-20230131-iso-51200.tar.gz)

And the `presets.json` file with the new entry appended:
[presets.json.gz](https://github.com/darktable-org/darktable/files/10550406/presets.json.gz)

**Comment by rawfiner** [comment]
Perfect, thank you

**Comment by ecthiender** [comment]
Thank you so much for working on this. To both, the contributors who contributed the R7 noise profiles, and the developer(s) who incorporated it.

How do I know or how can I follow in which release this will be out?

PS: do let me know if more R7 noise profiles are required, I own one, and I can contribute.

**Comment by TurboGit** [comment]
It will be in next release (4.4) which is plan in June. See the release cycles plan here:
https://github.com/darktable-org/darktable/wiki/Releases-cycle

**Comment by kmilos** [comment]
@ecthiender Actually, this should be in dt 4.2.1 which is available already.

**Comment by ecthiender** [comment]
> It will be in next release (4.4) which is plan in June. See the release cycles plan here: https://github.com/darktable-org/darktable/wiki/Releases-cycle

> @ecthiender Actually, this should be in dt 4.2.1 which is available already.

I'm guessing the latter one is correct? @turbogit, @kmilos ? 

I'm running 4.2.0, I will upgrade and check it out!

Thanks a lot for the info!

**Comment by ecthiender** [comment]
Just for the record, if anyone seeing this later - it is indeed available from 4.2.1
