### ISSUE TITLE
Is it possible to add $(EXPORT_COLORSPACE) variable?

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#13157]
It would be nice to have such variable in order to have the opportunity to auto-mark output files with color space they were exported with.

**Describe the solution you'd like**
Adding such variable to output file name will help to distinguish between files exported into different color spaces. Otherwise marking those files manually is a boring routine prone to errors.

**Alternatives**
Let it be as is.

**Comment by gi-man** [comment]
I think it would be easier to create a preset that selects the  output color space (adobergb) and has a matching description in the filename string (eg _adobergb).

**Comment by kanyck** [comment]
@gi-man That's possible, but in this case `Ctrl/E`  becomes effectively ambiguous. In that case the extra dialog might be helpful: if there is more than one export option, the dialog window shall appear.
