### ISSUE TITLE
Color Calibration module, color chart reference custom values?

### ISSUE THREAD

**Issue by Cmonsta6** [darktable-org/darktable#13163]
**Is your feature request related to a problem? Please describe.**

Hi you lovely people, I would appreciate the ability to use the color calibration module's calibrate with a color checker tool with custom reference values.

**Describe the solution you'd like**

Ability to import a custom LAB or Spectral cie file to generate a LUT for color correction.

**Alternatives**

**Additional context**

**Comment by MStraeten** [comment]
that isn't enough - you need to provide also the geometrical info of that target. the module isn't designed to load custom values at run time yet, but you can add your own target in https://github.com/darktable-org/darktable/blob/master/src/common/colorchecker.h if you build darktable yourself.
