### ISSUE TITLE
Panasonic Lumix DMC-G2 raw sample set

### ISSUE THREAD

**Issue by AVHewitt** [darktable-org/darktable#13167]
I have contributed the raw sample set requested for Panasonic cameras to https://raw.pixls.us/. As is widely known, for this early model in the Lumix DMC-G* line the RAW files for formats other than the native 4:3 are cropped. All formats are readable with the current version of Darktable except that the 1:1 format has an artifact on the right side of the frame, origin unknown. I always leave the camera in the native 4:3 mode anyhow except for these tests.
Being new at this process, I'm slightly confused. I don't see any way that these files are associated with me on the raw.pixls.us site so they may be hard to find. The file names all have the format LumixG2wxh.RW2 (sorry that there's no underscore after the LumixG2). 
If it makes the process easier for you, I'll be happy to resubmit these or take some more. Of course, I have a good supply of RW2 files in the native 4:3 format that I can submit. 
It turns out that the firmware on my camera is out of date so I should probably update it and take new pictures anyhow. Let me know what I can do to help.

**Comment by Nilvus** [comment]
Please search existing issue before posting. A simple G2 word on search issue: https://github.com/darktable-org/darktable/issues?q=is%3Aissue+G2+is%3Aclosed
There's already some closed G2 issue. G2 support is coming from 4.2 release on wednesday. I so close this.
