### ISSUE TITLE
$(WIDTH.EXPORT) and $(HEIGHT.EXPORT)  are incorrect while used as export name suffix

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#13160]
**Describe the bug/issue**
`$(WIDTH.EXPORT)` and `$(HEIGHT.EXPORT)` when added in export file name produce weird numbers as in 
`20130623-DSC_2662_-2147483648x-2147483648.jpg`

**To Reproduce**
1. Set export file name as `/home/xxx/Pictures/$(YEAR)/dt/$(FILE_NAME)_$(WIDTH.EXPORT)x$(HEIGHT.EXPORT)`
2. Click "export" from lighttable
4. See erroneous file name

**Expected behavior**
Should produce name as `20130623-DSC_2662_1920x1281.jpg`

**Platform**
* darktable version : 4.0.1
* OS                :  Linux - kernel 6.0.0-pf5
* Linux - Distro    : Gentoo
* Memory            :  16G
* Graphics card     :  Radeon RX470
* Graphics driver   :  amdgpu
* OpenCL installed  : ROCm
* OpenCL activated  : yes

UPDATE:  it seems that if exported from darkroom, the numbers are correct. Seemingly uninitialized numbers appear if export right from lighttable, without going to darkroom. Will do more testing now.

**Comment by kanyck** [comment]
Well... it seems to work correctly now. I could not reproduce this error again, however in the first place it was perfectly reproducible. No idea what the difference is.

**Comment by Nilvus** [comment]
So better to close it. You could reopen it if you find a way to reproduce anytime. Maybe wait too 4.2 release just in few weeks.

**Comment by kanyck** [comment]
It looks much like a memory corruption to me, or something similar. I think I'll close it for now and will keep an eye on its behavior, then reopen if I see a pattern. Hopefully I won't.
