### ISSUE TITLE
cant install in windows 10

### ISSUE THREAD

**Issue by Sergiope** [darktable-org/darktable#13176]
Hello, I want to report that it has been impossible for me to install the program in Windows 10, I tried the compatibility tool, all the alternatives I could, also in administrative mode, etc., there is no case.

That's why I'm notifying this bug, for those of us who have Windows it's a problem, thanks!

**Comment by ptilopteri** [comment]
but you have provide none of the requested and necessary information to trouble shoot your problem.

**Comment by HSUfineprint** [comment]
I use windows 10 (OS Builds: 19045.2364) and darktable, no problem at all. darktable version from 3.8 to 4.2, and some nightly PKG. You should provide more information or error log.

**Comment by gi-man** [comment]
And make sure if you have an antivirus software that it is not blocking your install.

**Comment by TurboGit** [comment]
Another alternative is to migrate to GNU/Linux :)

**Comment by Sergiope** [comment]
Thanks for the answers:

1.- It's the only installer that doesn't work for me, that's why I'm notifying you.

2.-I don't have any antivirus that blocks any installation since I use a lot of foss software and I know what I'm talking about

3.-I use linux but on this computer I use windows, sorry but not everything can be done there

**Comment by ptilopteri** [comment]
you have provided none of the logs showing the failure.  how does one determine what is now working w/o any substantiating information?  you *only* said the install failed.

**Comment by gi-man** [comment]
There are plenty of users on windows 10 and 11. I use Windows 11 and Fedora 37. But you are not providing enough details to start to troubleshoot and find the root cause of the problem. Eg. The windows 10 is Home or Pro or S? What message/error are you getting during the install?  Please provide all the information in the template and any error logs/messages.

**Comment by victoryforce** [comment]
@Sergiope It is very unfortunate that you were not willing to provide us with more information. One can only guess that your case may be similar to this one: https://github.com/darktable-org/darktable/issues/10712
If so, then disabling ASLR may help you.
