### ISSUE TITLE
Scrolling leaves thumbnail overlay ghost image

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#13173]
**Describe the bug/issue**
Sometimes a ghost imprint of the thumbnail overlay can remain on screen when navigating through the file manager view.
![image](https://user-images.githubusercontent.com/2805109/208658761-edd594ed-54fd-425a-af32-ca3e13eb8e8d.png)

**To Reproduce**
1. Enter filemanager layout
2. Place your mouse in an active element of the thumbnail overlay such as the stars or the rejection button.
3. Scroll your view via mouse wheel or via arrow keys.
4. A ghost image will remain on the previous thumbnail until you refresh the thumbnail by moving your mouse there again. (Even multiple ghosts can appear if you keep repeating the process).

**Platform**
* darktable version : list+4559~g6556a0785
* Linux - Distro    : Manjaro

**Comment by Nilvus** [comment]
I can reproduce too. Indeed, probably some refresh missing. @AlicVB?
