### ISSUE TITLE
Return old snapshots to preferences

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#13178]
**Is your feature request related to a problem? Please describe.**
dt 4.2 introduced a new snapshots module which allows for panning and zooming. This can be very useful in certain scenarios, but comes with the drawback of being slower. For my use case - someone who rarely has use for panning and zooming snapshots, but does take snapshots CONSTANTLY, the drawback here significantly outweighs the gain. It only takes an extra second to load a snapshot, but doing this a hundred times an image adds up to a lot. (Why a hundred? Because using shortcuts, I love to tap the snapshot on and off a lot to compare before/after of each effect. It is both simpler, and easier on the fingers, to do this via shortcut than via constant mouse dragging.) 

**Describe the solution you'd like**
Ability to select either 'legacy' or 'modern' snapshots tool in preferences, where 'modern' is the version as implemented in 4.2, and 'legacy' is the version implemented in older releases.

**Comment by parafin** [comment]
I like to do on/off too and indeed it became too slow, though panning for me is a great addition. Maybe we could optimise somehow this specific use-case (on/off without panning/zooming in-between)? E.g. fallback to old method when possible?

**Comment by TurboGit** [comment]
`on/off` should be fast as it will use the cache and won't recompute the snapshot.

**Comment by parafin** [comment]
Well, it isn’t as fast as it was and it’s noticeable. Maybe some additional optimisation can be done - e.g. delay destroying the cairo surface (or whatever) when snapshot is turned off, so it’s ready if it’s turned on back without any changes.

**Comment by TurboGit** [comment]
I confirm, looks like the cache is broken somehow.

**Comment by jenshannoschwalm** [comment]
This is about internal caching, right?

**Comment by TurboGit** [comment]
See #13179.

**Comment by ig9000** [comment]
Having just tried 4.2, I had same reaction as OP, and dropped back to 4.0.1. I just wanted to add that I also noticed different cache behavior when toggling a single module on or off. It feels like the whole pipeline is now being recomputed every time. I suppose this may have been fixed already alongside the reported bug, but I'm pointing it out just in case. Thanks for the work!

**Comment by todd-prior** [comment]
> Edit to add: Another thing I noticed with new snapshots is that compressing the history stack can cause a snapshot to disappear from the list. I don't know if this is intended/necessary or not, but it was certainly a surprising new behavior for me. Maybe it should be mentioned in the release notes if it's not a bug?

Because they are dynamic and tied to a certain point in the history stack then compressing breaks this. So it should be clear that the history stack needs to be kept intact while using the snapshots or they will be lost...
