### ISSUE TITLE
Numbers 012345r appear vertically over any star in the lighttable.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13171]
**Describe the bug/issue**
I really don't know if this is a darktable bug, but it seems to me that you shouldn't see something like this.
This behavior only occurs when the darktable preferences window is displayed. If you place the mouse over any of the stars in the lighttable the numbers 012345r appear vertically over any star.

I don't know if this happens in the Mac or Windows versions.

I think that being the darktable preferences window over the lighttable, this toolltip should not appear, although I believe that this behavior is impossible to control.

**To Reproduce**
1. Go to lighttable
2. Click on darktable global preferences icon to open the window.
3. Place the mouse over any star

**Expected behavior**
The tooltip should not appear.

**Screenshots**

![Screenshot from 2022-12-19 19-36-08](https://user-images.githubusercontent.com/67672868/208554708-d433bef5-66c9-4f6a-8e92-2e3807ae5a98.png)

**Platform**
Fedora 37

darktable version : 4.1.0~git1240.d1c663b6-8756.3
OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.0.13-602.inttf.fc37.x86_64
Uptime: 1 hour, 25 mins
Packages: 3402 (rpm), 44 (flatpak)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.2
WM: Mutter
WM Theme: CustomAccentColors
Theme: WhiteSur-dark-solid [GTK2/3]
Icons: WhiteSur-dark [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 5671MiB / 32028MiB
Graphics driver : NVIDIA Driver Version 515.76
OpenCL installed : Yes
OpenCL activated : Yes

**Comment by elstoc** [comment]
I believe that is a list of all the keyboard shortcuts that can be applied to the widget you're hovering over

**Comment by difrkaguilar** [comment]
I think darktable global preferences is a modal window and the mouse should lose the focus of the main window, display its content, but not interact on it while this window is active.

**Comment by Mark-64** [comment]
> 

Indeed the preference dialog is modal
```

_preferences_dialog = gtk_dialog_new_with_buttons(_("darktable preferences"), win,
                                                    GTK_DIALOG_DESTROY_WITH_PARENT | GTK_DIALOG_MODAL,
                                                    NULL, NULL);
```
but still the mouse kind of interacts with other gui element, although only for showing tolltips.
Gtk bug, or maybe it is a feature...

**Comment by difrkaguilar** [comment]
It's a strange thing. However when the about darktable window comes up, then the behavior is different.

![Screenshot from 2022-12-27 21-12-46](https://user-images.githubusercontent.com/67672868/209746725-198c5867-dba2-463c-9f62-709136fb913f.png)

**Comment by Mark-64** [comment]
> when the about darktable window comes up, then the behavior is different.

That uses `gtk_about_dialog_new()`, a different gtk widget
