### ISSUE TITLE
missig tag

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#13186]
Hi all,

The git repo is missing the tag for release 4.2.0 however, there is a tag for release 4.3.0. Is this a naming error or is release-4.3.0 actually release-4.2.0?

**Comment by mir07** [comment]
$ git log
commit 3ce030bbb8883aeed604f84e3a5e6188de6328ed (HEAD -> master, origin/master, origin/HEAD)
Author: Nicolas Auffray <45535283+Nilvus@users.noreply.github.com>
Date:   Thu Dec 22 16:48:00 2022 +0000

    Update README to 4.2.0 release

commit 84c495b54d15558ac09f6fabdb1c1de313263e36
Author: Victor Forsiuk <vvforce@gmail.com>
Date:   Thu Dec 22 15:43:22 2022 +0200

    Update release info in darktable.appdata.xml.in

$ git tag | grep release-4
release-4.0.0
release-4.0.1
release-4.1.0
release-4.3.0

**Comment by TurboGit** [comment]
`$ git fetch --tags `
?

**Comment by mir07** [comment]
That did it. Thanks

$ git fetch --tags
remote: Enumerating objects: 37, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 4), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), 1.03 KiB | 264.00 KiB/s, done.
From https://github.com/darktable-org/darktable
 * [new tag]             release-4.2.0 -> release-4.2.0
