### ISSUE TITLE
Starting DT in Culling breaks timeline in Filemanager

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#13182]
**Describe the bug/issue**
When you start darktable while in culling and then switch to a filemanager layout, the timeline is not displayed.

**To Reproduce**
1. Enter Culling mode
2. Stop and start darktable
3. Go to Filemanager layout

--> The time line is not displayed correctly.

To fix, stay in file manager layout and restart darktable once more.

**Screenshots**
Broken
![image](https://user-images.githubusercontent.com/2805109/209157666-b32c5884-7f6c-41a0-9c4e-06445a0d5b07.png)

Working
![image](https://user-images.githubusercontent.com/2805109/209162097-eb9a9d9d-29db-40f4-9831-2e65b79fc8c9.png)

**Which commit introduced the error**
Ran a bisect. Looks like
7cbd8537190b0e5593113805abbfacc6155db754
is to blame

**Comment by Nilvus** [comment]
Can reproduce too. If bisect is good so it's for you @dterrahe

**Comment by gi-man** [comment]
I can reproduce too on Fedora 37 KDE X11. I never use the timeline view. :-)
