### ISSUE TITLE
Canon R3 noise profile

### ISSUE THREAD

**Issue by JackP-Z** [darktable-org/darktable#13190]
Doesn’t seem to be supported (I uploaded RAWs twice).

**Comment by MStraeten** [comment]
did you follow https://github.com/darktable-org/darktable/wiki/Camera-support#noise-profiles?
if not then be patient until a developer finds time to do the job - grass doesn't grow faster when you pull on it

**Comment by Nilvus** [comment]
There's already R3 issues. For opening noise profiles issue, this need noise profiles done. I so close this issue as it's a duplicate and will not help to have noise profiles. Noise profiles will be added if someone does them.
