### ISSUE TITLE
Canon EOS R10 white balance presets

### ISSUE THREAD

**Issue by quirin053** [darktable-org/darktable#13192]
Here are the results of **extract_wb_from_images.sh** with finetuned images.
[darktable-whitebalance-20221223.tar.gz](https://github.com/darktable-org/darktable/files/10297298/darktable-whitebalance-20221223.tar.gz)

**Comment by kmilos** [comment]
@quirin053 Unfortunately there is no usable data in these text files. Can you please try to run the script again on your raw files, but with an up to date version of exiftool?

**Comment by quirin053** [comment]
tried it again with exiftool version 12.57
[darktable-whitebalance-20230314.tar.gz](https://github.com/darktable-org/darktable/files/10967521/darktable-whitebalance-20230314.tar.gz)

**Comment by kmilos** [comment]
Thanks - better (i.e. there is now data), but it's still not right, there are multiple (but different) values for the "same" reported fine tuning setting (e.g. see "WB Shift AB" in the first couple of files, they should be unique), resulting in

```
Gaps detected in finetuning for Canon EOS R10 preset Daylight, dt will need to interpolate!
Gaps detected in finetuning for Canon EOS R10 preset Shade, dt will need to interpolate!
Gaps detected in finetuning for Canon EOS R10 preset Cloudy, dt will need to interpolate!
Gaps detected in finetuning for Canon EOS R10 preset Flash, dt will need to interpolate!
Gaps detected in finetuning for Canon EOS R10 preset Tungsten, dt will need to interpolate!
Gaps detected in finetuning for Canon EOS R10 preset Cool White Fluorescent, dt will need to i
nterpolate!
```

Curiously, there were no such problems w/ EOS R7 that was added recently as well....

Shall we add just the basic values w/o fine tuning for now?

**Comment by quirin053** [comment]
Thank you.
I think i used white balance bracketing to shoot three different settings at once, maybe that's what's causing this problem.

**Comment by kmilos** [comment]
Possibly. You could check a couple more manually to verify they match the PR...
