### ISSUE TITLE
Set display profile to export profile

### ISSUE THREAD

**Issue by ZeroEcks** [darktable-org/darktable#13201]
**Is your feature request related to a problem? Please describe.**
You should be able to set the display profile to the export profile. In my opinion this should even be the default?

**Describe the solution you'd like**
Adding export profile to the display profile dropdown like you can with the histogram.

**Alternatives**
I couldn't come up with any sorry

**Additional context**
I came to this conclusion in a forum thread on pixls after debugging why my colors were wrong, you can take a look here but it's not too exciting.

https://discuss.pixls.us/t/colour-profile-help/34263/3

**Comment by HSUfineprint** [comment]
> You should be able to set the display profile to the export profile. In my opinion this should even be the default?

No, It's not a appropriate way in most color management workflow. Your monitor ICC let CMS know how to display color on the monitor, it's not designed to embed in images.

**Comment by ZeroEcks** [comment]
Thanks, I have asked around on the IRC channel and had it explained to me. Thanks everyone, it's been enlightening to me :)
