### ISSUE TITLE
Collect module: empty list on first filter when adding a second filter

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13204]
**Describe the bug/issue**

When adding a second filter, there's nothing now on first filter in collection module. This wasn't quite recently.

**To Reproduce**
1. Be sure no other filter is set outside collect module
2. Set first filter on collect module to filmroll (issue is the same with all other choices)
3. Set a second filter (with AND boolean): I set blue label color, with a lot of images with blue label color and other with some other colors. This issue will work with any other filter that many images have
4. Click on empty field entry of first filter
5. About 2 weeks ago, that would display list of filmroll (or any other choice made on that first filter), now the list is empty

If on 3th step, I just set the filter but do not select one of the choice on the list, I can display list of first filter.

**Expected behavior**

List should display all first filters images that have both filters selected.

**Screenshot**

![image](https://user-images.githubusercontent.com/45535283/209572391-91692e13-b464-4498-9688-6eb985c64605.png)

**Which commit introduced the error**

Probably that PR #13138 (or maybe that one #13126); @AlicVB: this one for you I fear!

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master (and so 4.2.0)

**Comment by TurboGit** [comment]
Is that still true? On my side after emptied the first filter when I select it I have the list of filmrolls:

![image](https://user-images.githubusercontent.com/467069/210131146-59c3ed7d-46e0-4a55-ad31-beb4e797b621.png)

(not seen on the screenshot but I have the caret blinking on the filmroll entry).

**Comment by TurboGit** [comment]
I see, this happens only if the film roll entry is left empty before selecting a value for the second filter. And in this case I have:

`sqlite3 error: /home/obry/dev/builds/c-darktable/x86_64-linux-gnu-default/src/src/libs/collect.c:1997, function list_view(), query "SELECT folder, film_rolls_id, COUNT(*) AS count, status FROM main.images AS mi JOIN (SELECT fr.id AS film_rolls_id, folder, status       FROM main.film_rolls AS fr        JOIN memory.film_folder AS ff        ON ff.id = fr.id)   ON film_id = film_rolls_id  WHERE (1=1 (id NOT IN (SELECT DISTINCT imgid FROM main.tagged_images WHERE tagid NOT IN memory.darktable_tags))) GROUP BY folder ORDER BY film_rolls_id DESC": near "(": syntax error`

**Comment by Nilvus** [comment]
This issue is exactly that, when you left empty film roll entry, but not only. I can reproduce with nearly all filters as soon as I let it empty first.

**Comment by TurboGit** [comment]
@AlicVB : Can you help on this one? Looks like a regression recently introduced by b18155e33acea0c6fa6f952e4b429f47f83655a3.
