### ISSUE TITLE
Darkroom preview & lighttable view not consistent with middle darkroom view & exported image

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#13213]
On one particular image (MAC50261) the darkroom preview (extra window) and the small and large lighttable view (after striking key F) shows some ghost image when my settings of the denoise profiled module are as in the delivered xmp. But the middle darkroom view and the exported picture don’t show that problem. 
If I bring down the “search radius” in the “denoise (profiled) non-local means” from 30 to 20, the issue disappears. 
I know that search radius at 30 is extreme but my graphics card seems to manage this (I guess thanks to the opencl settings in darktablerc).
This isn’t really a big issue but consistency between darkroom view, the darkroom preview, the lighttable view and the exported picture should be strived for, hence this report.

* darktable version : 4.2.0 for Windows
* OS                        : Windows 10 Pro 
* Version                 : 10.0.19044 Build 19044
* Memory               : 32 GB
* Graphics card       : NVIDIA GeForce RTX 2080 with Max-Q Design
* Graphics driver     : NVIDIA Studio Driver 527.56
* OpenCL installed  : Yes
* OpenCL activated : Yes

**Additional context**
This issue did NOT exist under darktable 4.0

**Attached zip**
The attached zip contains 3 jpg’s named as such to illustrate the issue. Furthermore of course the raw and xmp files. (Sorry for the high jpg compression level of the export, MAC50261xDT, but otherwise my zip got too big.)
[darkroom preview ghost images.zip](https://github.com/darktable-org/darktable/files/10310701/darkroom.preview.ghost.images.zip)

**Comment by gi-man** [comment]
I think you should verify with -d perf from the cmd. Most likely the preview/thumbnail images are being processed via the CPU vs the Full/Export are going via the GPU and there could be a small difference between the paths. -d perf will show you which path the processing is taking. Further to test, you can disable OpenCL to force everything via the CPU path (but slower) _OR_  switch the OpenCL to Very Fast GPU which tries force everything possible via OpenCL.  See if that gives you some consistency.

**Comment by jenshannoschwalm** [comment]
I took me a while to see what you mean - indeed there is a "ghost"

This is due to how "thumbs" are processed, in some modules there is a faster path for thumbs accepting some quality drop for better performance. Nothing to do with OpenCL or CPU path.

**Comment by cabuy** [comment]
Hello Hanno, hello Gi-man,
thank you for your prompt feedback. I accept the compromise of less reliable thumbnail views in favour of response time. With the ever growing megapixel race it surely is important to keep an eye on response time of less important/critical views/renditions. I hope however that this reported issue is an exception. If it turns out to be repeatedly reported, then somewhere a warning should be communicated (like in the manual or in the comments when hovering, or so). 
And while I have the opportunity here to address some words to dt contributors: I highly appreciate what you're doing to continuously improve dt.
