### ISSUE TITLE
DT 4.2.0 (selective) copy and paste fails: kills all previous settings

### ISSUE THREAD

**Issue by asl5757** [darktable-org/darktable#13211]
Found in DT 4.2.0 as distributed for openSuse Leap 15.4 after update to the new version (from 4.0).
See at the bottom: the issue is probably a broken/incompatible config after update :-(

**To Reproduce**
(please observe: I use the German UI, so my translations may be a bit inaccurate)
1. Have a few images with some modules (more than just the defaults) applied
3. Go to Light Table and selectively copy one module from one of the images
4. Select another image and check its module stack (in Dark Room)
5. paste the selection
6. view the new module stack
7. The module is inserted but all previous actions (modules) are removed from the stack, except for some defaults.

**Expected behavior**
7. All previous selected modules should stay the same as before and the new, pasted module should be added on top

**Screenshots**
selectively copy:
![grafik](https://user-images.githubusercontent.com/4995338/209718067-8223e3ef-8ef2-49e7-bbf6-1d8005ae88f2.png)

before:
![grafik](https://user-images.githubusercontent.com/4995338/209718133-257d8a13-db1d-4d09-827f-b042a4fbaeff.png)

... paste ...
after:
![grafik](https://user-images.githubusercontent.com/4995338/209718161-5c1a9138-848a-46d4-9ad6-1ee98eca3932.png)

**Which commit introduced the error**
Cannot say, as I do not build DT myself - sorry.

**Platform**
* darktable version : 4.2.0-lp154.56.1 (repo:obs://build.opensuse.org/graphics:darktable)
* OS                :  Linux - kernel 5.14.21-150400.24.38-default 
* Linux - Distro    : openSuse Leap 15.4
* Memory            : 32 GB
* Graphics card     : integrated Intel
* Graphics driver   : ?
* OpenCL installed  : no
* OpenCL activated  : no
* Xorg              : 
* Desktop           : KDE Plasma 5.24.4
* GTK+              : 3.24.34
* gcc               : not used
* cflags            : not used
* CMAKE_BUILD_TYPE  : n.a.

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **do not have another**
 - Can you reproduce with a RAW or Jpeg or both? **use only RAW**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **no** 
   __Oh my, so my config is broken after the update to latest DT version__
  **How do I fix it without loosing all my presets?** 
 
- Do you use lua scripts? **No**
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by asl5757** [comment]
Addendum: 
When starting DT in the terminal (with my old config), the paste operation produces these error messages:

[_dev_auto_apply_presets] missing mandatory module rawprepare for image 16458
[_dev_auto_apply_presets] missing mandatory module temperature for image 16458
[_dev_auto_apply_presets] missing mandatory module flip for image 16458
[_dev_auto_apply_presets] missing mandatory module gamma for image 16458
[_dev_auto_apply_presets] missing mandatory module rawprepare for image 16458
[_dev_auto_apply_presets] missing mandatory module temperature for image 16458
[_dev_auto_apply_presets] missing mandatory module highlights for image 16458
[_dev_auto_apply_presets] missing mandatory module demosaic for image 16458
[_dev_auto_apply_presets] missing mandatory module flip for image 16458
[_dev_auto_apply_presets] missing mandatory module colorin for image 16458
[_dev_auto_apply_presets] missing mandatory module colorout for image 16458
[_dev_auto_apply_presets] missing mandatory module gamma for image 16458

After renaming darktablerc to darktablerc.old, the issue is gone (and my styles are still there) - **Hurray!!**

It seems that my darktablerc has accumulated a lot of cruft while updating across many revisions (I think, I started with one of the 2.x versions...)

### Solution:
Rename your old darktablerc (or remove it), to start with a clean slate.

----
For anybody interested in a post mortem, I attach the new and the old darktablerc (both renamed to *.txt)

[darktablerc.txt](https://github.com/darktable-org/darktable/files/10310686/darktablerc.txt)
[darktablerc.old.txt](https://github.com/darktable-org/darktable/files/10310687/darktablerc.old.txt)

**Comment by asl5757** [comment]
If any admin stumbles across this issue: "works for me (TM)"
So, for me personally it could be closed as I have a workaround.

However, maybe the update mechanism could be improved or the release info could include some hints.

**Comment by ptilopteri** [comment]
YOU *can* close it
