### ISSUE TITLE
add option to exclude file extension in XMP sidecar name 

### ISSUE THREAD

**Issue by leononame** [darktable-org/darktable#13224]
**Is your feature request related to a problem? Please describe.**

I use a third party tool called IMatch to manage most of my photo library. It has pretty good support for managing metadata, including storing said metadata in XMP sidecars. If my file is e.g. `DSCF1234.RAF`, the sidecar from IMatch is `DSCF1234.xmp`. Adobe does this as well as almost any other application I know of. Darktable uses the sidecar format `DSCF1234.RAF.xmp`, probably to avoid conflicts with files having the same name but a different extension. This makes files edited in darktable incompatible with a DAM, especially when trying to move or rename files, the DAM (in my case IMatch) is not able to identify the non-standard sidecar.

**Describe the solution you'd like**

I'd like to have an option to use the form `{FILENAME}.xmp` instead of `{FILENAME}.{EXT}.xmp` in darktable. This would be opt in and would allow me (and probably other users) to work with darktable in their workflow without breaking stuff for existing users. Having set this options means that two files with the same name and different extensions would have the same darktable modifications applied.

**Alternatives**

I have considered also trying to change those settings in IMatch (which is not possible - I contacted the developer as well). In the end, I believe conforming to the XMP Standard which specifies that the sidecar should follow my suggested naming pattern is a better option than trying to force all other tools into a non-standard format.

**Comment by parafin** [comment]
And how it's supposed to work when you import both raw and JPEG files (which have the same basename)?

Why it's not possible to implement in IMatch?

This request did already come up several times, and always the results was "won't fix".

**Comment by MStraeten** [comment]
do you have a solution how to handele different history stacks for e.g. a xyz.cr2, xyz.jpg? 
just ignoring such use cases isn’t darktables preferred way ;)

**Comment by leononame** [comment]
My suggestion is that both files would default to use the same history stack and darktable settings in this particular case. I understand this can be a bit cumbersome and that there isn't a clean solution that fits everyone. I'm also suggesting making this a new opt-in option - it would allow for displaying a warning about this particular edge case. 

> Why it's not possible to implement in IMatch?

I guess it's possible - but it's not only IMatch. I believe trying to be interoperable with other tools (such as IMatch, ACDSee, even Lightroom or CaptureOne) is a valid reason. And while I believe that the XMP standard is a bit off track by not including the extension in the filename, I do think having an option to conform to that standard would help in darktable being interoperable with other programs.

**Comment by parafin** [comment]
> My suggestion is that both files would default to use the same history stack and darktable settings in this particular case. I understand this can be a bit cumbersome and that there isn't a clean solution that fits everyone. I'm also suggesting making this a new opt-in option - it would allow for displaying a warning about this particular edge case.

This just can't work. JPEG and raw files can't have the same history stack - required processing steps differ much. And also it will break some assumptions in darktable code, which will result in subtle and not so subtle bugs. So in our case I would say it's really impossible to implement, meaning there are actual specific reasons for that.

**Comment by leononame** [comment]
Alright, I won't make a fuss about this :) it's your product and you know the direction you want to take with it. I am a very pleased user and hope you keep up with the quality work. 

I'd obviously urge you to reconsider this in the future - if the request came up a couple of times already it's probably because it's an actual pain point for some users. But it's absolutely your decision :)

**Comment by TurboGit** [comment]
> it's your product

No it's not our product, it is Open Source and can be tweaked, enhanced by anyone. But still, we cannot allow something that would break dt to be merged. So first we need to agree on the problem to solve and the solution collectively.
