### ISSUE TITLE
Panasonic DMC-GF2

### ISSUE THREAD

**Issue by ASmartGuy** [darktable-org/darktable#13226]
All the crops (1:1, 4:3, 3:2, 16:9) for Panasonic DMC-GF2 have been uploaded. Please add support for this camera.

**Comment by kmilos** [comment]
This camera should already be supported (going 8 years back)? Here's dt 4.2 w/ an raw.pixls.us sample:

![image](https://user-images.githubusercontent.com/4973094/212085915-2b9e84f7-d67b-425d-90bc-a017cf367465.png)

**Comment by LebedevRI** [comment]
Not sure what seems to be missing?
@kmilos i feel like you should've felt free to close this obvious kind of issue.
