### ISSUE TITLE
Export Preset will not store or change set size mode

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#13227]
Latest release. 4.2 on Win 11

Issue

If the set size mode is set to scale and you change the value and then attempt to save a preset it will only do so from default dialogue settings, ie reset the module. If you make another change to the scale the only option is to update the current one ie the preset that was just made and not make a new one. In every other set size mode making a value change will allow you to see the option to save that as a new preset.

Also even when you can create a preset with set size and a selected scale value when you apply it only the other settings change the current setting of the set size dialogue is unaffected, ie say by changing from pixels to scale or even to update the value if it is set at scale as the mode for sizing. Also other  presets created with different scaling ie by cm or inch or pixel will only change the value if the export dialogue is currently set  in the same  mode when the preset is applied... ie pixels for pixels cm for cm. So for example I can have a preset for scale by pixel for 2000 on the long side and one for 4000 on the long side with either the same or a mix of other settings and applying them back and forth will change things... if however the scaling is set to some other mode say in or scale factor. Then this is ignored and notthing changes.

I think expected behaviour would be that the module settings for all elements would be saved in the preset and loaded when the preset is applied....

I am not seeing this and from a quick search I didn't see this raised yet??

**Comment by tpinfold** [comment]
I raised a similar issue in February, not realising you had already made this request. I wonder how hard it would be to implement in the code? I can just see so many uses where people want to export to a specific size or scale. But it seems no developer is interested in this issue so I will just live with this small problem and remember to set it manually each time.
