### ISSUE TITLE
snapshots persist when switching images.

### ISSUE THREAD

**Issue by darix** [darktable-org/darktable#13225]
**To Reproduce**
1. open image 1
2. go to "original image" in history
3. "take snapshot"
4. go back to top of the stack and verify that you can view the before and after
5. switch image to another image
6. pull mouse left/right over the image
7.  it shows you the snapshot from image 1 and the edit version of image 2

**Expected behavior**

snapshot handling should be per image.

* darktable version : 4.3.0~git35.0707088c790
* Linux - Distro    : openSUSE Tumbleweed
* package: from https://build.opensuse.org/package/show/home:darix:darktable:master/darktable

**Comment by darix** [comment]
FTR: happened on the branch for 4.2.0 development as well. so not a post branch bug.

**Comment by parafin** [comment]
This is very useful feature, not a bug.

**Comment by TurboGit** [comment]
Indeed not a bug, it allows you to compare different (similar) images with different dev history.

**Comment by darix** [comment]
uhm.... and how to reset that if i dont want it?

especially as this preview thing interfered with moving around the crop box.

**Comment by TurboGit** [comment]
@darix : Not sure to understand what you want to do. But to reset the snapshots:

1. click on reset of the snapshot module to remove all of them
2. click on the currently selected snapshot to stop having it displayed

**Comment by Nilvus** [comment]
This is an old feature.
