### ISSUE TITLE
Show style preview when using keyboard arrows

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#13232]
**Is your feature request related to a problem? Please describe.**
When mouse is hovered over a style in the quick access menu, the style displays in the preview screen, however when one uses arrow keys to move up and down through the list, style preview does not display.

How it looks when using mouse (note: my screenshot tool does not capture mouse, but here it was hovered over the highlighted menu item 'LOOK TEST':

![with mouse](https://user-images.githubusercontent.com/69561443/210064670-57d3b484-cb6e-4821-b22e-d4711a089770.png)

How it looks when using arrow keys (in this example my mouse was off to the side):

![without mouse](https://user-images.githubusercontent.com/69561443/210064691-336d4eca-9d73-4e7f-b2a5-ae432d2986e0.png)

**Describe the solution you'd like**
Style preview to display when using arrow keys.

Linux Mint Cinnamon 21
nvidia rtx 2060
opencl on
darktable 4.2 from OBS repos

**Comment by TurboGit** [comment]
Well not only the preview but the whole tooltip (history stack, style name & description) is not displayed and this is expected as based on Gtk tooltip feature which triggered by mouse. I'm not sure we want to do something here and note that this is the case for all tooltip on the UI.
