### ISSUE TITLE
sigmoid : add OpenCL support

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13231]
All said in the title, this has been discussed and would be nice to have in 4.4 as many users are now using Sigmoid instead of Filmic. Even if this module is fast having some more CPU cycle saved would be nice.

**Comment by TurboGit** [comment]
@jandren : Hope this is still on your radar screen :)

**Comment by jandren** [comment]
Yes even though the selection of default display transform is higher on my priority list. Also won't complain if anyone else feels the inspiration to do it.
