### ISSUE TITLE
Noise Profile Fujifilm X-H2

### ISSUE THREAD

**Issue by laemplein** [darktable-org/darktable#13235]
I just created a noise profile for the X-H2, hope this finds its way in one of the next releases. Thanks for your work!

[darktable-noiseprofile-20221229.tar.gz](https://github.com/darktable-org/darktable/files/10324645/darktable-noiseprofile-20221229.tar.gz)

**Comment by rawfiner** [comment]
The noise profile looks very good, thank you @laemplein. PR is on his way.
