### ISSUE TITLE
Gtk4 anyone?

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#13236]
Just out of curiosity, how difficult would it be to migrate to Gtk4?
Would GPU accelerated gui be a game changer or not?

If this has been already discussed, feel free to close.

**Comment by MStraeten** [comment]
just scan through the code for gtk related stuff and think about the jobs to be done:
adapt the code and then verify it works as least as before on several platforms (multiple Linux distributions, windows, osx) - if not, implement platform specific workarounds…

**Comment by TurboGit** [comment]
The first step would be to know what are the diffs between Gtk-3 & Gtk-4 and what are the incompatibilities. And from there how many lines of code are affected in dt side.

**Comment by Mark-64** [comment]
From [here](https://docs.gtk.org/gtk4/migrating-3to4.html), we should perhaps start to count how many of those "do not use" we have in the codebase.

**Comment by ralfbrown** [comment]
Did a quick "git grep" for some of the functions and values which need to be replaced/rewritten.  Stopped when I got to 1000 instances.....

**Comment by dterrahe** [comment]
The mechanical replacement of one pattern with a new one isn't going to be the biggest challenge; "coding monkeys" can do that and some of it can be done while still using gtk3. Analysing workarounds that stop being "supported" and finding alternative or "correct" ways of implementing stuff is going to require more expertise/patience.

Projects like gimp and krita take 1+ years updating frameworks (deprioritising _all_ other changes during that time). What kind of resources with somewhat deep knowledge of gtk3 _and_ gtk4 does dt have to throw at the task?

**Comment by Mark-64** [comment]
Closed #15920

**Comment by Mark-64** [comment]
Closed #15920
