### ISSUE TITLE
Color harmonies guides in vectorscope?

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#13247]
I would like to see some help in DT when coming to "color harmonies". I remember we discussed this some months ago.
What I propose is the following:
- in RYB vectorscope (only), a menu to select the wanted color harmony from a predefined set, for example

![immagine](https://user-images.githubusercontent.com/43290988/210135853-21201bab-14f8-4867-b8fa-a537c775d789.png)

the menu would be activated by one of the unused button (hide green/blue channel), with new icon

- upon selection of a color harmony, guide lines would be drawn in the vectorcope, see the mockup below for a "complementary" harmony. The vectorscope samples outside the guide would be dim.

![immagine](https://user-images.githubusercontent.com/43290988/210135710-aa8bc6d2-e99e-457c-bd14-cae840472cdf.png)

- scrolling the mouse would have the effect of rotate the selected guidelines with a predefined angle, say 30° or so

I the idea get consensus, I can try to implement a prototype

**Comment by TurboGit** [comment]
That's a nice project. Yes we had discussed that, I remember having said that I'd love to see some helping tool for color harmony to be part of dt. Nice to see you trying to push this.

My first questions are:
- Do you think you can find where it was discussed?
- I've never used such tool but I've heard of them... Do you have experience on what is done on other software? What kind of help is provided? Only visualizing the zones as proposed here? Or going further?

To be sure we get this right in dt I want to be sure we know where we are going. TIA.

**Comment by Mark-64** [comment]
I have an initial prototype of the drawing part, gui automation not done yet
See for example a "split complementary" harmony with 240° rotation

![image](https://user-images.githubusercontent.com/43290988/210260662-18e3b5bc-aa8c-4311-9318-5db2ae4bfcba.png)





> * Do you think you can find where it was discussed?

Yes

> * I've never used such tool but I've heard of them... Do you have experience on what is done on other software? What kind of help is provided? Only visualizing the zones as proposed here? Or going further?

I am not aware of direct support to color harmonies in Lightroom. I have worked with Capture One for a while and it doesn't have it.
Johanna Kustra, in her videos that originated our discussion a while ago, uses Photoshop + Paletton
Same [here](https://www.captureone.com/blog/applying-color-harmonies-in-capture-one) for Capture One.

But I might be wrong, I hope someone here knows better.
The workflow I imagine is quite simple, have guidelines in the vectorscope (to choose from a catalogue) and just use color picker live samples in the key areas of the image + the DT's powerful color manipulation tools to fit inside the guidelines at best.
I believe this is pure psychology (or art), nothing too scientific.

**Comment by difrkaguilar** [comment]
Joanna Kustra full video regarding to Color grading in here:

https://www.youtube.com/watch?v=mC8ol2-V7Ck

**Comment by Mark-64** [comment]
> * Do you think you can find where it was discussed?

It was discussed in several places, for example [here](https://github.com/darktable-org/darktable/pull/9991)

**Comment by HSUfineprint** [comment]
It might be a good feature, but I didn't understand how it helps people in the workflow. Could users shift the color hue directly in the vectorscope? or it is just a overlay scope display as a guide? If direct change is possible, we also need a corresponding color harmony module, functions may like hue shift by range or already existing "color zones".

**Comment by Mark-64** [comment]
> I didn't understand how it helps people in the workflow

Providing some guides, just an overlay scope display, as you said. Think this as the gridlines you can overlay on the image, rule of thirds or similar, but in the color space.


> Could users shift the color hue directly in the vectorscope?

No, this is not the aim. DT is not short of color manipulation tools, I don't want to invent others. 
Here we are in the realm of artistic purposes, and I don't believe we can automate art. 
If you want to create a color harmony among the key focus areas of an image, only you can decide which are the key areas.
Look at the videos by Johanna Kustra, she is not using any specific tool to create color harmonies, only adjustment layers in Photoshop.

**Comment by TurboGit** [comment]
Just a thought, maybe it would be nice to be able to get parametric mask set according to some vectorscope area selected depending on the current color scheme. This would help shifting color in this area...We may need to be able to shift the selected colors left or right of the current area as the goal is to have those color in the area. Not sure if this makes sense, but it may be a way to help user changing colors to match the color scheme.

**Comment by Mark-64** [comment]
> it would be nice to be able to get parametric mask set according to some vectorscope area selected depending on the current color scheme

not sure... what you really want is to select key areas of the image (according to the artistic intent) which are outside of the color scheme you want to implement and move them inside. I can't imagine a way to automate this.

**Comment by MStraeten** [comment]
> ... to be able to get parametric mask set according to some vectorscope area selected depending on the current color scheme...

thats a use case of color equalizer - but it didn't appear yet, so i think some of the basic topics ensuring consistent color changes aren't that easy to deal with. 
so allowing more then just one hue range in paramteric masks seems to be a non trivial task ...

**Comment by TurboGit** [comment]
@MStraeten : Yes, you are certainly correct... It was just a wild guess.

**Comment by SoupyGit** [comment]
This is a great feature. A couple of thoughts:

Visually, I personally prefer the first example (where harmony guides reach all the way to the outer hue circle) better than the second (where they don't).

Also, although dimming outside the guides helps the harmony stand out more, I wonder if it is as preferable for workflow, where we want to clearly see the hue outside the guides - since that is what we will be trying to hue shift. Hard to form a strong opinion without testing it, but something to consider.

**Comment by HSUfineprint** [comment]
As a "guide hue" for users, maybe a highlighting display function will help. I'm thinking if I choose a harmony style, complementary orange-blue for example, an on/off button can show corresponding hue colors normally and desaturate other hue colors on the image. That will be better than dimming outside colors on scope. It's a direct visual guide on the image I'm editing.

**Comment by Mark-64** [comment]
@SoupyGit 
> Visually, I personally prefer the first example (where harmony guides reach all the way to the outer hue circle) better than the second (where they don't).

I am also wondering, so I made very easy to change this within the data structure. The purpose of having some of the sector "shorter" is to convey the message that there must be primary colors and secondary colors. To achieve a good visual balance, the secondary colors should be less prominent in the image, although lower saturation (shorter sector) is not the only way, they could also taking less space. Let's see what the consensus is


> dimming outside the guides

Easy to remove, although I struggled quite a bit with Cairo to make it... :-)

@HSUfineprint

> a highlighting display function

Yes maybe, but far from easy to implement, at least for me. I would need help from more experienced devs.

Anyway, the first draft is almost ready, I will send a PR for testing, along with some thoughts on the workflow for using the feature

**Comment by TurboGit** [comment]
> I am also wondering, so I made very easy to change this within the data structure. The purpose of having some of the sector "shorter" is to convey the message that there must be primary colors and secondary colors.

I agree with that, that's an important point of color harmony.

**Comment by TurboGit** [comment]
> Anyway, the first draft is almost ready, I will send a PR for testing, along with some thoughts on the workflow for using the feature

Great !

**Comment by SoupyGit** [comment]
Yes, consensus is good. The reasoning is sound, although I must say I had no idea that was the purpose just by looking at. Only if people read that in the manual would they understand, which as we know, is no given. One other potential issue with shorter secondary guides is if it is high saturation and falls outside the guide. I'm imagining an orange sunset over blue ocean, for instance. In that case, you don't necessarily want either the blur or orange to be less saturated.

**Comment by Jiyone** [comment]
I don't understand what's the purpose and how it helps. Are color zones that difficult to spot on the scope? 🤔

**Comment by difrkaguilar** [comment]
For what it's worth, here are some icons I made for the occasion

![color_harmony_icons](https://user-images.githubusercontent.com/67672868/210697724-26a7d17b-bbff-4fb5-aafc-275dfcbd96f3.png)

[color_harmony_icons.zip](https://github.com/darktable-org/darktable/files/10349149/color_harmony_icons.zip)

**Comment by HSUfineprint** [comment]
> I don't understand what's the purpose and how it helps.

Color harmony is a color match theory. It's useful for graphic and product design. Some photographers use it as color grading guide.

**Comment by MStraeten** [comment]
> I don't understand what's the purpose and how it helps. Are color zones that difficult to spot on the scope? 🤔

some seems to like editing by values. It’s something reasonable in video editing to speed up matching color mood of different footage. 
But as long as it can be disabled so it doesn’t consume performance - why not if there’s someone spending effort on it…

> It's useful for graphic and product design.

why not use krita or further tools for graphic design? It doesn’t improve performance to put everything useful somewhere in the graphic business into darktable.

maybe a further fork darktable + bells and whistle in addition to darktable - bloat might make sense 😉

**Comment by HSUfineprint** [comment]
> why not use krita or further tools for graphic design? It doesn’t improve performance to put everything useful somewhere in the graphic business into darktable.

I said "It's useful for graphic and product design." The "it" means "Color harmony", not darktable...

**Comment by Mark-64** [comment]
> some seems to like editing by values

I am partially color blind, like quite a few others, and numbers help me to avoid mistakes in editing.
Moreover "creative" color grading is not only applicable to video. Fashion photography makes large use of color harmonies.
I already mentioned one professional fashion photographer which I admire, see here another example: [Linday Adler](https://lindsayadlerphotography.com/). You will see that colors are completely unnatural in some of her picture, yet they work.
Now unfortunately having color harmony guide lines will not all of a sudden turn me into a photographer of that level, but at least I can study and learn.

**Comment by mediatechnologic** [comment]
My questions are hopefully not too silly:
- Why are the color harmonies only available in RYB? 
- Are the "real" harmonies not the opposite colors in CIELUV vectorscope?
- For example the Munsell color wheel does show this quite perfect.
 
See discussion at [https://discuss.pixls.us/t/color-harmony-with-ryb](https://discuss.pixls.us/t/color-harmony-with-ryb)
and the screenshots dated in post 2023-11-30 of DaVinci-Resolve and Darktable
<img width="629" alt="mtlc_vectorscope-munsell_v20231130" src="https://github.com/darktable-org/darktable/assets/20679721/1c30f44d-02d4-4a60-b51f-0c8133351964">

After some study of a lot of videos and papers from RYB supporters I meanwhile think, that RYB is wrong and outdated. May be RYB has to be kept in Darktable for the experienced but antiquated painters? And probably for a couple of colors RYB harmony does work and has worked historically (of course). I will try to contact David Briggs to get his opinion about this RYB vs RGB (CIELUV). May be you know other harmony experts who know more?

**Comment by HSUfineprint** [comment]
Color harmony is base on pigment subtractive color models. I think that's why it is available in RYB only. But using color harmony method in other modern color models is not a bad idea. Maybe you can open an issue to ask for this feature.
