### ISSUE TITLE
4.2.0 "add to library" -> "ignore JPEG images" no longer ignores previously exported webp images

### ISSUE THREAD

**Issue by fishy** [darktable-org/darktable#13252]
**Did you buy darktable from an application store ?**

No. Installed through debian's official apt repository.

**Describe the bug/issue**

This is a regression in 4.2.0 (worked fine in 4.0.x and before).

When choosing "add to library" and check "ignore JPEG images", it no longer ignores the exported (under `darktable_exported` subdirectory that's exported from Darktable previously) webp images.

**To Reproduce**
1. Select some images
2. Choose lighttable -> export -> format options -> file format change to WebP -> export
3. Click "add to library..."
4. Choose the directory of photo library
5. Check all 3 of:
  * select only new pictures
  * recursive directory
  * ignore JPEG images

**Expected behavior**

Exported webp images are auto ignored and not imported into library.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**

Somewhere between 4.2.0 and 4.0.x

**Platform**

* darktable version : 4.2.0
* OS                : e.g. Linux - kernel 5.10.142-19743-gd301e86c39f7
* Linux - Distro    : Debian testing (bookworm)
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **no with 4.0.x and before**
 - Can you reproduce with a RAW or Jpeg or both? **webp**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by parafin** [comment]
Well, webp isn’t jpeg. Maybe previous darktable version you used just wasn’t able to import webp images at all?

**Comment by fishy** [comment]
that's certainly possible (although I no longer have 4.0.0 to verify that), but my understanding is that here "JPEG images" is only a figure of speech meaning "non-raw images" or "exported images". it definitely makes more sense that way to provide an option to only import raw images (or to exclude non-raw images).

**Comment by parafin** [comment]
I suspect it's not the case. Intention was never to ignore exported images, but to ignore JPEGs when shooting in RAW+JPEG mode in camera (and it's always JPEG, not anything else). So to me this is not a regression, but rather an improvement (more supported formats). Maybe disabling recursive import could help with your case. But in general I guess it's better to export somewhere outside the raw images folder tree.

**Comment by fishy** [comment]
@parafin yea that makes sense, but let me provide my perspective.

if the intended use case is to avoid jpeg in camera's raw+jpeg output, then as long as it doesn't ignore raw it would still work as expected. so far as I understand it webp cannot be used as raw, so ignore webp will not break it.

with webp gaining popularity I think it's definitely possible that some camera manufacturer could start to use webp to replace the jpeg part in the camera in the future (e.g.  non-raw would output webp instead of jpeg, and raw+jpeg would be raw+webp instead). I'm not familiar with webp's roadmap but I would admit that there's a non-zero possibility that it would gain raw capability in the future so camera manufacturers _could_ use it to replace the raw part, but I would say that possibility is much lower than replacing the jpeg part and until that happens it would be mostly safe to treat it as non-raw format.

also back to your suggestions, I organize my photos in format of `~/Photos/Darktable/yyyy/mm/dd.description/`, when importing from camera I first manually copy the photos to the desired local directory, then just re-add the whole `~/Photos/Darktable/` directory again in darktable (with the 3 options checked). also in export module the default `target storage` option is `$(FILE_FOLDER)/darktable_exported/$(FILE_NAME)`. both means I don't need to change anything in every importing/exporting. your suggestion means I would need to change at least one of them every time (unless there's a way to write the `target storage` option so it can auto export to somewhere like `~/Photos/darktable_exported/yyyy/mm/dd.description/` that's following my original photo directories).

is there a way to write a lua script to auto skip webp files during importing?

**Comment by parafin** [comment]
Well, I agree it’s a valid feature request. But distinguishing raw from non-raw could get tricky to do in import dialog…

**Comment by fishy** [comment]
I can totally understand the concern regarding false-positive/false-negatives when trying to distinguish between raw and non-raw in import dialog.

1. what's the correct process to submit a feature request instead?
2. is there any workaround I can use right now to unbreak my workflow (for example, maybe use a lua script to skip certain files _when_ importing)?

(also I verified your theory that 4.0.0 cannot import webp files at all, despite that it does can export that format)

**Comment by fishy** [comment]
for the feature request part, if the concern is that the auto distinguishing can be unreliable, provide some configurations to allow users to configure certain rules/patterns would work. some random ideas:

1. a configurable exclusion pattern (so for my case I can configure it to something like `.*darktable_exported.*` or `.*\,webp`
2. some additional ui element in the import dialog to quickly select/unselect based on file extensions, etc. (currently there's already `select all`, `select none`, `select new`, so maybe just add an option `select by extension`)

**Comment by fishy** [comment]
Filed feature request as #13486, closing this bug as it's not really a bug.
