### ISSUE TITLE
[FR] RGB numbers in primary colors in the color picker module.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13253]
**Is your feature request related to a problem? Please describe.**
This is only a cosmetic feature. Since the color picker popup menu appears in RGB primary colors, the same colors should appear the same on both sides.

**Additional context**

![Screenshot from 2023-01-01 14-23-23](https://user-images.githubusercontent.com/67672868/210187801-61ef0351-e48f-4f41-a3b6-d72245113364.png)

![Screenshot from 2023-01-01 14-23-23_01](https://user-images.githubusercontent.com/67672868/210187808-0b082ed3-0d74-407d-a22e-fb619b48a0ef.png)

**Comment by TurboGit** [comment]
I don't think we want to do that as one goal in dt UI is to keep it without color (less distraction).

**Comment by Nilvus** [comment]
I agree, it's good in a popup but could be distracting on the UI. Apart of that important point, I understand your request. It's also not an important thing to have colors as RGB is quite significant to understand what values are.

**Comment by difrkaguilar** [comment]
Ok, I understand that the interface should not have anything distracting from the main image, especially if the program is running on laptop or low resolutions. Anyway in this medium, I assume that all of us who see a series of numbers 255 255 255 know that the layout in any language even if the letters change, is RGB by convention. Anyway this module in my case I always have it collapsed and only deploy it when I use it to select colors or areas in pa photography and for that case I see the colors in the floating menu in addition to the color information on skins (average Caucasian skin).

In that case I am going to close this FR.
Thanks a lot for your attention.
