### ISSUE TITLE
Double screen and selection in collection

### ISSUE THREAD

**Issue by manu-p** [darktable-org/darktable#13257]
**Describe the bug/issue**
With 4.2, I notice that when I want to change the selection in the light table collection, while I am working on a double screen and the dt window is maximized in screen 2 (the right one), the selection menu opens on screen 1 (the left one).
And it is no longer possible for me to choose another selection with the mouse: the menu disappears. 
However, I can use the keyboard arrows and Enter.

![image](https://user-images.githubusercontent.com/14906222/210267813-ce8d8695-b42e-48eb-a5b1-7b0a33aca3c1.png)

In this screen capture, the dt window is on the right screen, the menu on the left screen.
Of course, if I move the dt window to the left screen, the menu is displayed as usual on that same screen.
And when I shrink the dt window a bit in the right screen, the menu is displayed on the same screen. 

Wayland is disabled, X11 is running, GNOME is in 42.5 (ubuntu mode) and GTK 3.24.33

And what I describe did not happen with dt 4.0.

I have not found a 4.0 package of dt, but I have reinstalled 3.8.1 and I confirm that the anomaly does not recur, the menu is displayed on the screen containing the dt window.
![image](https://user-images.githubusercontent.com/14906222/210267961-6ca67c9f-1a59-491a-9073-fc8348175b57.png)
**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.2
* OS                : 5.15.0-56-generic #62-Ubuntu SMP
* Linux - Distro    : Ubuntu 22.04.1
* Memory            : 14GB
* Graphics card     : nVidia GK107GLM [Quadro K1000M]
* Graphics driver   : nVidia 390.157
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Comment by Nilvus** [comment]
To precise: the most important thing is that this happens only if darktable window is on the right screen of the double screen. I've discussed with manu-p on French forum and didn't reproduce (because I have darktable window on my left screen in my double screen setup) until testing (and so understand) darktable on right screen.

**Comment by dterrahe** [comment]
@manu-p would you be able to test https://github.com/darktable-org/darktable/pull/13261 ?

**Comment by manu-p** [comment]
Thanks @dterrahe for the suggestion, and since I don't compile dt (or any other s/w) I think I'll wait for the next release, expecting the fix #13261 is embedded in it.

**Comment by Nilvus** [comment]
I can test that but not before tomorrow

**Comment by dterrahe** [comment]
No hurry; I don't think 4.2.1 is imminent.
