### ISSUE TITLE
Use the fine user interface of 'Zone system' in Filmic

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#13251]
I get the filmic concept of mapping the input on a scale instead of hard values. 

I do really miss the interface of the zone system and I suggest that way of control is considered for Filmic.

Reasoning:  Sometimes you want to give more space for a specific portion of the dynamic range to recover details, and to sacrifice some range in order to increase the details elsewhere.
It was very visible how you could magically take some dynamic range from, say, the lighter part of the histogram and apply it to a very specific midtone.

The sliders in Filmic are a tiny little bit like that but it is like a fixed 3 zone system which you don't control with zones and the sliders are over multiple tabs.

The zone system was very straightforward in that regard.

Note I am not suggesting to bring back the deprecated module (although I would celebrate the occasion); but the interface worked really well.

**Comment by MStraeten** [comment]
filmic isn't zone system - so why trying to mimic something completely different? If you want to do tone adjustments then tone equalizer is the appropriate tool

**Comment by HSUfineprint** [comment]
You can change graph views by click the cycle button in filmic module. One is "dynamic range mapping", it looks like zone system mapping.

**Comment by rekcodocker** [comment]
> t zone system - so why trying to mimic something completely different? If you want to do tone adjustments then tone equalizer is the app

It does something similar - it maps an input range onto an output range and it can compress or expand the range to recover more detail, or to re-assign dynamic range somewhere else. 

> You can change graph views by click the cycle button in filmic module. One is "dynamic range mapping", it looks like zone system mapping.

I use that graph all the time. Point is, I can not drag the graph, I can only change two sliders which somewhat influence it.  In the zone system you could edit that graph directly. 
Indeed, that graph is exactly the similarity to the zone system.  The principle is there but the controls are very different (and limited).
