### ISSUE TITLE
left click on module name shall close respective module not others which are also open at the same time

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#13250]
**Describe the bug/issue**
when left clicking on modules name, that respective module shall open/close. However, if there are more than one module open. the first left click closes all other modules firstly and the next left click closes the respective module. 

This is unexpected to me, but not sure it is a feature, not a bug

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to Darkroom
2. Shift+Click on three modules to open them all
3. left click on the middle one or the top one

**Expected behavior**
left click shall close that particular module which is clicked on, not others

**Screencast**
_(if applicable)_

https://user-images.githubusercontent.com/49004103/210173054-06be79af-2d74-4e71-be38-115dbe5774ed.mp4

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* darktable version : 4.3.0+57~g4445885db
* OS                : Linux - kernel 6.1.1-gentoo
* Distro            : Gentoo Base System release 2.9
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-525.60.13
* OpenCL installed  : Yes (opencl-headers-2022.01.04)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.6
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.35
* gcc               : x86_64-pc-linux-gnu-11
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Comment by HSUfineprint** [comment]
Left click on module name will close opened module. Shift + click will close all other modules but the clicked module. It works fine on Win 10 and 4.2.0 released.

**Comment by AxelG-DE** [comment]
That means, my system behaves like shift+click, just I didn't press shift.... 🤔

**Comment by AxelG-DE** [comment]
@dterrahe by chance, you have an idea on it?

**Comment by dterrahe** [comment]
@HSUfineprint likely has "preferences/darkroom/expand one processing module at a time" switched off, whereas @AxelG-DE has it on.

I can see where you are coming from, @AxelG-DE, but I can also see how some people would say that you can achieve what you want by shift-clicking (which you already used to open multiple instances) and that they want "normal-"clicking to do something different-and-also-useful. Given that the preference above just reverses the shift/no-shift cases, I think for the setting you _don't_ use, the current behavior makes sense. So I'm not going to spend time and emotional energy on a PR that might attract a lot of discussion without any satisfactory conclusion. Sorry.

**Comment by HSUfineprint** [comment]
> @HSUfineprint likely has "preferences/darkroom/expand one processing module at a time" switched off

Yes, @dterrahe, you're right. I'm used to collapse modules by manual clicking.

**Comment by AxelG-DE** [comment]
@dterrahe
>  preferences/darkroom/expand one processing module at a time" switched off, whereas @AxelG-DE has it on.

you are right, and it says in tool tip "toggles shift+click", sorry I oversaw that

>  but I can also see how some people would say that you can achieve what you want by shift-clicking (which you already used to open multiple instances) and that they want "normal-"clicking to do something different-and-also-useful

are you saying, *if* you would change it, it would change on other places as well? In that case I fully agree on "don't touch it", or you change one flame war to another, then safe the efforts :-) (flame war is kidding)

Actually I did not shift+click to open them, but a shortcut which is activating a multiinstances-style (which I could have recorded  better, I assume)

TBH for my given case, I do not see a good reason for the habit, which we see in above screen recording. But we would circle here easily, so no argues :)


> Given that the preference above just reverses the shift/no-shift cases, I think for the setting you don't use, the current behavior makes sense

I have difficulties to get the meaning for the part "I think for the setting you don't use".... anyhow I toggled that setting now and see, whether I will be happy or not. Otherwise I will dare to ping you in IRC :)

> So I'm not going to spend time and emotional energy on a PR that might attract a lot of discussion without any satisfactory conclusion. Sorry.

where is the shy @dterrahe gone to, I remember from the early days. Now tough as AP, almost... LoL

**Comment by dterrahe** [comment]
> almost...

Just the opposite; I _don't_ want to fight everybody. It is tiresome and I don't get anything out of it. And I also believe you need more than one person to run a project like this and you won't always be right or agree. It is great that those who believe the opposite now have somewhere to go.
