### ISSUE TITLE
Feature request: Ability to rename snapshots

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#13262]
I appreciate this request will only occur if one of the developers sees value in investing time in implementing my requested feature. Thanks for considering this request. I believe it would be an improvement to Darktable if the snapshots could be renamed by the user. This option is now available when creating new instances of the editing modules and has proven very helpful to me. I would like this same capability with snapshots as I often use them to compare multiple processing options such as when I am denoising and want to find the best combination of settings to reduce the noise without sacrificing details. Again thanks to the developers for all their time creating such a great program.

**Comment by HSUfineprint** [comment]
This feature will also work for me. It could be help to identify multi snapshots.

**Comment by gi-man** [comment]
Have you consider using duplicate module since you end up doing multiple module edits and then evaluate the best one using culling?

**Comment by tpinfold** [comment]
Duplicate module would not suit my purpose. I often want to check subtle changes such as noise reduction settings and compare different settings or modules by swiping over the image with snapshots and determining the best one. It would be great if I could give each snapshot a meaningful name rather than remembering what each one was. I just hope since this option has been applied to new instances of processing modules that it is an easy to do option for snapshots. Thanks for your reply.

**Comment by MStraeten** [comment]
keeping mind the new dynamic snapshots are deleted if you go back in your history stack - so better rename the module instance since that persists in the stack…

**Comment by TurboGit** [comment]
And snapshots are anyway lost when leaving dt so I don't see the point of naming them.

**Comment by tpinfold** [comment]
Naming snapshots would be very useful for my workflow. It is certainly not a deal breaker as I can just use pen and paper to remember what each represents, however, I was really impressed with how I can rename and be prompted to rename new instances of modules. This made for an efficient way of knowing which module did which localized adjustments. So I figured the same approach with snapshots would be practical and hopefully easy to implement. Sadly I can't code so I can only hope a developer can see value in my suggestion. If not then it won't happen and I stick with pen and paper which will be quicker and more efficient for me than the suggestions offered here in good faith. Thanks for your replies. I just hope a developer will see value in this feature request.

**Comment by rekcodocker** [comment]
Snapshots are useful for comparing small changes in settings. 
But when you have more than one it is hard to recall which was which.

Best feature would be if the snapshot was automatically named after the last module used plus the last parameter changed. 
Like 'denoise strength 60%' or 'lens correction disabled'.

**Comment by tpinfold** [comment]
rekcodoctor is on the right track here, this is certainly why I want to have the renaming option. But I presume it would be easier for the developers to just give us the option to type in a new name. I note that you can name new instances of processing modules which is really helpful. I note that when you create a duplicate you can rename it as well. So I hope that my request is easy to implement and someone who can will put their valuable time into this. Thanks again to all the developers for such a great program.
