### ISSUE TITLE
Vectorscope RYB view is forgotten after a restart

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#13263]
This is a minor issue, still I think it's a regression of current `master` compared to previous behavior.
To reproduce:
- in darkroom set the histogram to vectorscope `RYB` view
- restart dt and go to darkroom
- the vectorscope view is now `u*v*` instead of `RYB`

This behavior is specific to the `RYB` view. If, for instance, `AzBz` view is selected, after a restart the same view is presented.

I checked `darktablerc` and it does contain the line:
```
plugins/darkroom/histogram/vectorscope=RYB
```
yet it seems to be ignored.

**Comment by Mark-64** [comment]
Confirmed in current master, while 4.2 works ok.
I am currently messing up with vectorscope, will have a look.

**Comment by Mark-64** [comment]
git bisect gives the following
```
82963e7051f7d1e3fbbf95243a10bcb0d83a17de is the first bad commit
commit 82963e7051f7d1e3fbbf95243a10bcb0d83a17de
Author: Pascal Obry <pascal@obry.net>
Date:   Sat Dec 31 12:26:23 2022 +0100

    Reorder the configuration loading.
    
    We must first load the confgen to ensure that we can sanitize the
    current values based on enum, min, max as described in the XML.

 src/common/darktable.c              |  7 ++++++-
 src/control/conf.c                  | 16 +---------------
 tools/generate_darktablerc_conf.xsl | 14 ++++++++++++++
 3 files changed, 21 insertions(+), 16 deletions(-)
```
@TurboGit this is for you

**Comment by lbilli** [comment]
Not sure if relevent but while browsing around I noticed that `RYB` is not listed among the options of [`plugins/darkroom/histogram/vectorscope`](https://github.com/darktable-org/darktable/blob/8549ebe840afee21e28c4e87d45b993c06738a8d/data/darktableconfig.xml.in#L2996).

**Comment by TurboGit** [comment]
Indeed, this is due to my change which is correct as it validates the values based on the XML, but the value is missing as hinted by @lbilli so when RYB was selected at restart the default for this enum (`u*v*`) was selected.

See #13268.
