### ISSUE TITLE
Half of the Darktable Impage is Pixelated

### ISSUE THREAD

**Issue by TheBlackShrike** [darktable-org/darktable#13264]
I upgraded from Darktable 4.0 to 4.2 and now have a problem in which half of a RAW image, when viewed in darktable, becomes pixelated when I start to edit modules.  This happens for all my RAW images. I have tried to reproduce the error by viewing a new image and turning the default modules off and on again.  There doesn't seem to be a specific module that causes the problem.  I used the modules show in the image below and turn them all on/off or some varied combination but it doesn't seem to matter the order.  The best I have found is that sometimes if I turn off everything and then turn on Highlight Reconstruction that the problem occurs.  Other times, everything else is on and highlight reconstruction OFF shows the problem. But another time, it might be Exposure that triggers it.

**Screenshots**
![darktable4 2error](https://user-images.githubusercontent.com/121836703/210288557-21aa16a1-0205-4a93-8ded-d5c1cb0c7b91.png)

* OS                :Windows Vista (stop laughing, it's been working great)

**Comment by paperdigits** [comment]
There is an issue template that you need to fill out in full when you open an issue. Please do that before anyone tries to diagnose what is going on.

**Comment by pehar1** [comment]
Windows Vista expired a very long time ago :
Mainstream End Date : Apr 10, 2012
Extended End Date : Apr 11, 2017

I don't think anyone will be willing and able to support darktable for such an outdated operating system. There is also no information about the hardware used.

**Comment by jenshannoschwalm** [comment]
Closing this as there is no change to verify or track down for any dev.
