### ISSUE TITLE
Export to collection fails under Windows 11

### ISSUE THREAD

**Issue by Juangg77** [darktable-org/darktable#13266]
**Did you buy darktable from an application store ?**

Darktable 4.2 downloaded directly from the official webpage.

**Describe the bug/issue**
On Windows 11, when I try to export a picture to the collection, Darktable sends an error message saying: 
"Error moving file C:\Users\(my username)\AppData\Local\Temp\(filename)"

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to the export module, it doesn't matter if it's in the lighttable or darkroom view. Set it to store in collection and choose whatever file format you want.
2. Click on export
3. Scroll down to '...'

**Expected behavior**
The file is created and added to the current collection. (It used to work like that in previous versions)

**Platform**
* darktable version : 4.2.0
* OS                :  Windows 11 Pro
* Memory            :  16 Gb
* Graphics card     :  Integrated AMD Vega Graphics
* Graphics driver   :  unkown

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? ** It used to work fine in the previous version.
 - Can you reproduce with a RAW or Jpeg or both? **The error happens no matter the file type
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

 - Do you use lua scripts? Yes
   - What lua scripts start automatically? Ext_editor
   - What lua scripts were running when the bug occurred? Ext_editor

**Comment by gi-man** [comment]
> 1. Set it to store in collection and choose whatever file format you want.

Can you explain this in more detail? Maybe a screenshot of your export module could help.

**Comment by Juangg77** [comment]
I've realised it's related to the lua script Ext_editor, since the possibility to export to collection isn't in the darktable default installation. So I don't know if this would be the right place to submit the bug.
![export module](https://user-images.githubusercontent.com/121881554/210395743-2012d844-c45c-4802-899f-2b13264a329c.png)

**Comment by gi-man** [comment]
You should post the issue in the lua repository and close this issue. https://github.com/darktable-org/lua-scripts/issues

**Comment by Juangg77** [comment]
Thanks. I'll do that. Thanks for your help.

**Comment by Mark-64** [comment]
I wrote that lua script and I use it currently in Windows 11.
Do you have write access to the folder `C:\Users\(username)\AppData\Local\Temp` ?
From explorer, try to copy a file in there

**Comment by Juangg77** [comment]
Hi Mark-64. Yes, I've got write access to the folder I've manually copied files to it and I could do it without any warning or permission request.
