### ISSUE TITLE
as discussed in a post on the darktable subreddit: Windows installer won't work

### ISSUE THREAD

**Issue by MIB4u** [darktable-org/darktable#13277]
my syspx: 32GB RAM, several HDDs and SDDs, gtx2060, ryzen 7 2700X ~3.7GHz, Win10 22H2

https://www.reddit.com/r/DarkTable/comments/vqxvk4/darktable_wont_install_on_windows/

**Comment by victoryforce** [comment]
You have to turn off Mandatory ASLR  in Windows Security.

**Comment by Nilvus** [comment]
Not a darktable issue, just a Windows Security. I close.

**Comment by MIB4u** [comment]
ok, thnx, and also thnx for the workaround
