### ISSUE TITLE
Turning off white balance gives black image when demosaicing is RCD+VNG4

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#13271]
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
When turning off white balance module, the image turns black. But only if RCD+VNG4 is active.
![Skärmbild från 2023-01-03 23-22-34](https://user-images.githubusercontent.com/34200649/210451109-f9b34e13-4894-4164-b3e4-9e98050d3fd4.png)

CC0 raw file with xmp from Canon EOS R6 [20230103_R6_9123.zip](https://github.com/darktable-org/darktable/files/10340203/20230103_R6_9123.zip)

**Platform**
Ubuntu 22.04

* darktable version : 4.2

**Comment by jenshannoschwalm** [comment]
Confirmed. Will fix for 4.2.1

**Comment by TurboGit** [comment]
When using display referred ? I can't reproduce with scene referred workflow.

**Comment by Jiyone** [comment]
I can't reproduce on Ubuntu 20.04, using  ARW nor NEF raw files.

**Comment by jenshannoschwalm** [comment]
Strange, reproduced on various raws using OpenCL and CPU (although the output is somewhat different).

Reason is clear, while calculating the dual demosaicer blending mask we take wb data (undefined or zero it seems without wb applied) as dividend. Same with Amaze/VNG

**Comment by PeterWem** [comment]
I had no issues with AMaZE+VNG4.

**Comment by TurboGit** [comment]
> Strange, reproduced on various raws using OpenCL and CPU (although the output is somewhat different).

Yes on my case I have some strange colors for sure, but not fully black.

**Comment by TurboGit** [comment]
@jenshannoschwalm : So this is not a bug but a feature to me, right?

**Comment by jenshannoschwalm** [comment]
For me it's a bug,OpenCL and CPU code give different results.

Not sure if we should init the wb coeffs as 1.0 or we should fix it in dual demosaicing code.
