### ISSUE TITLE
Feature request: Ability to keyboard shortcut to save updated xmp file during processing

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#13273]
Okay, sometimes my computer crashes when processing images in DT. Then my hard work goes down the drain. What I would like to be able to do is set up a keyboard short cut such as Ctrl+S to save the latest steps to the xmp files. This would save me from so much grief when doing long edits on an unreliable computer. Apologies if  there is already a way to do this. I have checked the manual and found no solution except going to another image and then returning to the original image so the xmp file is updated during the switch.

**Comment by gi-man** [comment]
You can create your own shortcuts via the preference menu. Look for the write xmp sidecar and map to a keyboard letter or letter combo. 

Trying to find why your darktable crashes might be more useful.

**Comment by dterrahe** [comment]
> Look for the write xmp sidecar

Is this available in the darkroom though?

Someone would have to write a brief command that calls `dt_dev_write_history` and `dt_image_synch_xmp`.

As a fun aside, the first one already gets called when the tooltip for the quick access styles is generated, so as a workaround, you could try if clicking that button (bottom left or soon you'll be able to set up a shortcut for that) and then hovering over one of the style names for a while works for you :-)

Or if you are fluent in lua, you could create a routine yourself that just calls `darktable.gui.views.darkroom.display_image` _without_ and image number, which just saves the data for the current image to the database (but does not create an xmp) https://docs.darktable.org/lua/stable/lua.api.manual/darktable/gui/views/darkroom/

**Comment by ralfbrown** [comment]
See also #14849

**Comment by ralfbrown** [comment]
This should now be moot with the sidecar autosave (10-second default) implemented for 4.6, which is being released in a couple of weeks.

**Comment by tpinfold** [comment]
Thanks to the DT team for once again improving DT. The autosave feature is a great idea and indeed makes my feature request moot because a superior solution has been implemented.
