### ISSUE TITLE
Flash EXIF tag missing in the Image Information Panel

### ISSUE THREAD

**Issue by Jean-PierreCatusse** [darktable-org/darktable#13285]
Hi,
the image information gives a great list of info on each image especially from EXIF tags. And this is great.
Nevertheless, one of them is not imported or shown : the Flash tag.
The Flash tag brings highly relevant info in many cases.
This is not specifically an issue nor a bug, but a lack from my point of view.
Could you please show it in the list in a future release?
Many thanks for your support and congratulations to all darktable contributors.

Note : using 4.0.1 rel on Windows.
Best regards

**Comment by manu-p** [comment]
Hi, this enhancement seems not to be implemented in latest stable release.

Some users on the French forum would like to see it implemented, rather than having to play: 
`exiv2 -pe filename.RAW | grep -i flash`

**Comment by ralfbrown** [comment]
Closed by #16461.
