### ISSUE TITLE
Settings made in custom storage provider widgets not saved to export presets

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#13284]
I followed https://docs.darktable.org/usermanual/4.0/en/lua/sharing-scripts/ to write a custom export storage provider with Lua. 
![grafik](https://user-images.githubusercontent.com/509535/210974252-6f1a952d-d9fa-4ede-90a6-ecd6c041101f.png)

I've used the same methods like the scp example from docs, but all my custom widgets (Account, sensitve content etc.) are not saved into a export preset. Is this *by design* or is it possible to register the widgets to store/load the settings from a choosen preset?

**Comment by wpferguson** [comment]
@cytrinox Sorry I didn't see this until now.  

Lua and presets don't play well together.  

@TurboGit another item on the Lua as a first class citizen list

**Comment by wpferguson** [comment]
@cytrinox you can implement your own preset management for a storage, in the script.  See https://github.com/wpferguson/extra-dt-lua-scripts/blob/master/postsharpen.lua
