### ISSUE TITLE
Zemana detects it as a threat

### ISSUE THREAD

**Issue by mtbboy1993** [darktable-org/darktable#13288]
I've reported it as a false positive.
First it gets blocked put in quarantine, then I run it after I've reported the installer as false positive then it gets detected as I run the installed.
So hopefully that Zemena will resolve this.
But I am just notifying about this issue and that I've reported it.

**Comment by Nilvus** [comment]
What can darktable team do for that? This need to be notify to Zemena, not here.

**Comment by gi-man** [comment]
There is an easy fix, uninstall zemena. I would just close this issue as not a darktable bug.

**Comment by mtbboy1993** [comment]
I guess nothing, I just notified.
