### ISSUE TITLE
Sony Alpha 7C ILCE-A7C: white balance presets

### ISSUE THREAD

**Issue by rmalbrecht** [darktable-org/darktable#13296]
Hi,

I took some pictures and extracted the white balance presets according to

https://github.com/darktable-org/darktable/wiki/White-balance-presets

Sony Alpha 7C Firmware 2.0 with the Sony SEL90M28G lens. DRO is off.

[darktable-whitebalance-20230108.tar.gz](https://github.com/darktable-org/darktable/files/10368838/darktable-whitebalance-20230108.tar.gz)

The daylight is done properly for the fine-tuning, the others are done lazy.

If you could please incorporate this into Darktable :-)

cu romal

**Comment by Nilvus** [comment]
@rmalbrecht: please update your title and add "white balance presets" on it. At first, I thought of a duplicate of your closed issue and old issues too. Seems not and on what I (quickly) check, seems that this camera do not have white balance presets. @kmilos: could you confirm?

**Comment by rmalbrecht** [comment]
According to this list:
https://www.darktable.org/resources/camera-support/
the presets are missing for the A7C.

**Comment by Nilvus** [comment]
The list is not up-to-date.

**Comment by kmilos** [comment]
Indeed, still not in wb_presets.json, so this is a valid request

**Comment by rmalbrecht** [comment]
If the list is not current: Is the noise profile for the A7C missing? 
In Darktable itself, it looks like there are profiles. The list says, the profile is missing.
If it's missing, I would create one.

**Comment by Nilvus** [comment]
You have a search field on issues to check history: https://github.com/darktable-org/darktable/issues?q=is%3Aissue+a7c+is%3Aclosed

**Comment by kmilos** [comment]
Check also https://github.com/darktable-org/darktable/blob/master/data/noiseprofiles.json

**Comment by rmalbrecht** [comment]
Thanks for the pointer. Yes, the Alpha 7C is in.

**Comment by TurboGit** [comment]
@kmilos @Nilvus : Just in case it may help I have added commands to list the maker & models out of wb_presets.c, see end of page here:

https://github.com/darktable-org/darktable/wiki/Developer's-portal

```
$  cat data/wb_presets.json | jq '. | .wb_presets[].maker'

$  cat data/wb_presets.json | jq '. | .wb_presets[].models[].model'
```
