### ISSUE TITLE
What Opencl performance tuning in darktablerc is still recommended for dt 4.2 ?

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#13293]
I wonder if it still is worthwhile to tune opencl_device_priority when “Opencl scheduling profile” is on “default”? In dt 4.0 (on Windows) I had tuned the opencl_device_priority in the darktablerc file to ensure that the middle darkroom view and the extra darkroom preview window were executed in the GPU by setting opencl_device_priority=+0,*/!0,*/*/+0,*/+0,*. 

This worked OK and with a far better response for the extra darkroom preview window.

I have the impression that in dt 4.2 (on Windows) the opencl_device_priority doesn't influence this anymore when “Opencl scheduling profile” is on “default”?. I have now set “Opencl scheduling profile” on “very fast GPU” to have good (actually excellent) response time.

So what Opencl performance tuning via darktablerc is recommended for dt 4.2 ?

No hurry if the manual needs to be updated for that, since I don’t complain here.

•	OS : Windows 10 Pro
•	Version : 10.0.19045 Build 19045
•	Memory : 32 GB
•	Graphics card : NVIDIA GeForce RTX 2080 with Max-Q Design
•	Graphics driver : NVIDIA Studio Driver 528.02
•	OpenCL installed : Yes
•	OpenCL activated : Yes

**Comment by jenshannoschwalm** [comment]
The OpenCL performance related stuff/settings did not change in a relevant way from 4.0 to 4.2 so the manual is still valid.

**Comment by MStraeten** [comment]
it depends - if "very fast GPU" gives better results for you, then it's obviously better to use this over manual tweaking. 
manual tweaking especially makes sense if you can make use of a proper integrated GPU in your processor to make sure no GPU needs to wait by prioritizing GPUs for different pipelines. but if no GPU is waiting, it doesn't make sense to direct pipelines to a specific GPU. but that depends on your use of your system - if you have several programs using gpu in parallel the tweaking needs to be different ...

**Comment by gi-man** [comment]
If you set the profile to default, then it will use the =0,!0... If you set it to Very Fast GPU, that's not used, and everything (Full, preview, ...) is pushed to GPU.

On my system, Very Fast GPU yields faster results, mainly when using D&S. Your mileage may vary depending on the GPU card and amount of video memory. Test it looking at -d perf to see what works best for your system.

**Comment by cabuy** [comment]
Hanno, Martin, Gi-man, 
I appreciate your prompt replies.  
I am using dt now for 2.5 years. Over the last 1.5 year, I experienced relevant performance improvements once I started tuning Opencl parameters in darktablerc by adapting eventhandles, async, resource_default-parameters.
Hence I have a further question, which I may need to ask in the regular users forum/maillist. Anyway here it is.
Do you know how I can capture under Windows output from "-d" command line parameters like "-d perf" ? 
Today, I am guessing the resources (GPU, CPU, memory) being used through a monitor which was delivered on my Windows laptop. 
I know one method how to start dt with command line parameters (in Windows), since I do this today through a shortcut with property : "C:\Program Files\darktable\bin\darktable.exe" --library <databasepath>. However I have no clue how/where to find output from the -d series of parameters.

**Comment by cabuy** [comment]
Sorry Hanno, Martin and Gi-man for my last question. I found the answer on darktable.org > faq and will try it. Thank you again. I close this issue.

**Comment by cabuy** [comment]
Sorry Hanno, Martin and Gi-man for my last question. I found the answer on darktable.org > faq and will try it. Thank you again. I close this issue.

**Comment by gi-man** [comment]
Go to windows run, cmd and type darktable.exe -d perf . The log file will be generated in the hidden path listed below.

- ```C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\darktable\``` for windows +10
**These is a Hidden folder in Windows, therefore copy and paste the link to find this.** - OpenCL kernel, thumbnail image cache and the logfile are stored in here. These are all safe to delete if needed.

**Comment by cabuy** [comment]
THANK YOU.  This works. Marc.

Op zo 8 jan. 2023 23:49 schreef gi-man ***@***.***>:
