### ISSUE TITLE
Sony Alpha 7C: ILCE-A7C

### ISSUE THREAD

**Issue by rmalbrecht** [darktable-org/darktable#13297]
Hi,

I'm not sure which data is needed, as there are several pages about the camera support:

According to:
https://www.darktable.org/2012/10/whats-involved-with-adding-support-for-new-cameras/

Black and White levels

➜  ILCE-A7C exiv2 -pt 2023-01-08-14-33-08.dng | grep BlackLevel
Exif.SubImage1.BlackLevelRepeatDim           Short       2  2 2
Exif.SubImage1.BlackLevel                    Rational    4  131072/256 131072/256 131072/256 131072/256
Exif.SubImage5.BlackLevel                    Rational    3  0/1 27/1 39/1
Exif.SubImage6.BlackLevel                    Rational    3  35/1 41/1 42/1
➜  ILCE-A7C exiv2 -pt 2023-01-08-14-33-08.dng | grep WhiteLevel
Exif.SubImage1.WhiteLevel                    Short       1  16383

Color Matrices

➜  ILCE-A7C exiv2 -pt 2023-01-08-14-33-08.dng  2>/dev/null | grep CalibrationIlluminant2
Exif.Image.CalibrationIlluminant2            Short       1  D65
➜  ILCE-A7C exiv2 -pt 2023-01-08-14-33-08.dng  2>/dev/null | grep ColorMatrix2
Exif.Image.ColorMatrix2                      SRational   9  7374/10000 -2389/10000 -551/10000 -5435/10000 13162/10000 2519/10000 -1006/10000 1795/10000 6552/10000

cu romal

**Comment by kmilos** [comment]
The 7C is already supported since dt 3.4, please close.
