### ISSUE TITLE
dt 4.2 for Windows: no output found when using -d all parameter at startup

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#13295]
Further to my closed issue #13293 for dt 4.2 on Windows, I have tried to run -d all (or -d opencl or -d perf) as parameter in the darktable startup as follows:
"C:\Program Files\darktable\bin\darktable.exe" -d all --library <databasepath>

The file C:\Users\<username>\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt is created but no output is there.

This is no urgent matter, but I had hoped to further finetune performance by analysing the output as suggested in a reaction to issue #13293.

• OS : Windows 10 Pro
• Version : 10.0.19045 Build 19045
• Memory : 32 GB
• Graphics card : NVIDIA GeForce RTX 2080 with Max-Q Design
• Graphics driver : NVIDIA Studio Driver 528.02
• OpenCL installed : Yes
• OpenCL activated : Yes

**Comment by gi-man** [comment]
Can you try to start darktable via cmd (navigate to the darktable/bin folder). I'm not sure how windows handles the -d all inside or outside the " "

**Comment by cabuy** [comment]
Thank you ! 
It works in the cmd interface without the quotes. (Btw: one cannot create a shortcut with the -d all within the quotes. You then get a message that the pathname is invalid.)
So I'll analyze performance tuning further. But no urgent need so far.
