### ISSUE TITLE
color picker: picked area in main view doesn't match corresponding resized preview on jpeg

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#13290]
if the preview size is reduced to achieve perfomance gain the (global) color picker picking area in main view doesn't match to the proper area in reduced preview if the image isn't a raw image.

example: 
1. original preview size: ![image](https://user-images.githubusercontent.com/39386816/211164400-206d2bf3-c309-4b56-9bf1-3da33dd6c1bf.png)
--> color picker:
![image](https://user-images.githubusercontent.com/39386816/211164453-e0c350ff-3ff2-4297-8543-e65038785edf.png)
2. 1/4 preview size: 
![image](https://user-images.githubusercontent.com/39386816/211164513-8c2ff590-ac6d-4f28-8a1a-7d5d26449b83.png)
--> color picker:
![image](https://user-images.githubusercontent.com/39386816/211164589-f27c3f0a-3d41-43c3-95ec-d8599d7da3a6.png)
but for the corresponding cr2 file:
![image](https://user-images.githubusercontent.com/39386816/211164566-70970a49-e6b9-416e-baf4-6f4bab251dc2.png)

the samples were made with an copped part from : 
![image](https://user-images.githubusercontent.com/39386816/211164967-709161fa-e33e-4b6e-ac23-79f307db232b.png)

**To Reproduce**
prerequisites:
raw file + derived jpegs imported in darktable

1. set preferences > darkroom > reduce resolution of preview image to original
2. pick an area with an isolated color of known value + add it to live samples (note the value)
3. switch between raw and jpg --> values have plausible variations (raw isn't jpg ;)) 
3. set preferences > darkroom > reduce resolution of preview image to 1/4
4. pick an area with an isolated color of known value (eg. determined with spot mode color picker or noted before) + add it to live samples
5. switch between raw and jpg --> values have not plausible variations

alternative reproduction of the issue - without reasoning on plausible values: 
1. take a colorchecker image (not full framed so reducing the size really gives a chance to pick more then one patch) 
2. in 1/4 preview size pick a  small area from center of a patch --> add to live sample
3. in 1/4 preview size pick the whole area from a patch --> add to live sample
![image](https://user-images.githubusercontent.com/39386816/211165909-ed5e0fa9-9042-4167-81cd-c953f0106a52.png)
--> the value should be equal or quite similar 

**Which commit introduced the error**
issue is reproducible with my oldest custom build darktable-3.8.0+16~gafe76d1cc (dec. 2021)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable 4.2.0+59~g95f76943b
* OS                : OSx

**Comment by dtorop** [comment]
@MStraeten I'll look at this once #13216 is done.

>  cleaning up the code first might make it easier to fix that issue once for both ;)

That makes sense. At this point I'm touching the global and per-module picker code (indeed coalescing them into one).

If I had a guess, it would be that the problem comes somewhere in code like this:

https://github.com/darktable-org/darktable/blob/2b697a2a37780de1664be3d628b39495106cbfbf/src/develop/pixelpipe_hb.c#L650-L651

That is, a special case for reducing resolution of preview image with JPEGs is missing or misapplied.

**Comment by dtorop** [comment]
Finally taking a look at this. So far I can't reproduce it, but I see a few other things that aren't right:

 - When switching between the JPEG and raw versions of the image, the live sample readouts/swatches are initialized to the wrong values. Enabing a colorpicker (whether global or per-iop) sets them to the right values. The wrong values are consistent for each image, but different depending on the image. This happens whether preview resolution is "original" or reduced to 1/4.
 - Mouseover of live samples highlighting the sample in the center view only works when a colorpicker is enabled. (It doesn't have to be global colorpicker, it could be a per-iop picker. This is contrary to what the tooltip says in all cases: "hover to highlight sample on canvas"
 - (And furthermore, shouldn't the tooltip say "hover to highlight sample _in center view_"?)

As @MStraeten appears to be sampling a detail of a larger image, I'm also wondering if this is related to #9920.

**Comment by dtorop** [comment]
Working on an image which is a very small crop of a larger image, as in the example above.

I do see that the samples are offset from the image, as in #9920:

![image](https://user-images.githubusercontent.com/2311860/216776238-33696cf3-32e3-41a3-a3e3-499a35c8d1f7.png)

And that this is much worse when preview resolution is reduced to 1/4:

![image](https://user-images.githubusercontent.com/2311860/216776136-54a2b924-b3a1-4a74-b0e6-20959868a16f.png)

(Note that the square in the sample area should be representative of the size of a pixel in the preview pipe that is being sampled. And of course that it is sampling a pixel up and to the left of the intended sample.)
 
Also more weird behavior: If one sets up some area live samples when the preview resolution is reduced to 1/4, such as:

![image](https://user-images.githubusercontent.com/2311860/216775981-68dfbd36-c490-4e32-b1cc-2460cec666ea.png)

Then change the preview resolultion to "original", the sample boxes are offset/resized:

![image](https://user-images.githubusercontent.com/2311860/216776012-b4bda7ea-6e3c-49c1-ab2e-dd5163ff6569.png)

I also see that the preview pipe sample is very low-res, as shown in the navigator:

![image](https://user-images.githubusercontent.com/2311860/216776065-074e1014-458f-4184-bb0f-5236b2a3622e.png)

as well as in the thumbnail of the working image in the filmstrip at the bottom of the screen:

![image](https://user-images.githubusercontent.com/2311860/216776091-9842b20d-66f0-4369-880d-f8ad7cb2668c.png)

And that the preview pipe rendering of the image is clearly offset compared to the full pixelpipe rendering which is shown in the center view:

![image](https://user-images.githubusercontent.com/2311860/216776323-9e0682f5-6d1b-4dd4-9e67-bb8f032fa47e.png)
