### ISSUE TITLE
Nikon D40 Image converts as all black

### ISSUE THREAD

**Issue by Sembiance** [darktable-org/darktable#13301]
With `darktable-cli 4.2.0` on Linux `5.18.8` attempting to convert the attached Nikon D40 image [DSC_0427.NEF.zip](https://github.com/darktable-org/darktable/files/10369455/DSC_0427.NEF.zip) with `darktable-cli DSC_0427.NEF out.png` produces just a black image. v4.0.1 also produces a black image. However, imagemagick converts it ok.

**Comment by jenshannoschwalm** [comment]
In the image the "camera compensate exposure" is set to 5.0 making it very dark by default in the exposure module :-)

**Comment by Sembiance** [comment]
> In the image the "camera compensate exposure" is set to 5.0 making it very dark by default in the exposure module :-)

Ah. So is this not a bug? Is there a reason convert (and some other programs) seem to convert it correctly at their default settings? Is there a way to instruct darktable-cli to auto-detect a 'better' exposure that doesn't result in a black image?

**Comment by jenshannoschwalm** [comment]
> Ah. So is this not a bug? Is there a reason convert (and some other programs) seem to convert it correctly at their default settings? Is there a way to instruct darktable-cli to auto-detect a 'better' exposure that doesn't result in a black image?

No bug as this is the desired photographic interpretation understood by dt. Other "converters" mostly don't respect exif data ...
