### ISSUE TITLE
darktable fails opening .tif file created in GIMP

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13307]
**Describe the bug/issue**
In previous version darktable was able to open these .tif files. Now I'm with the 4.3.0~git83.2b697a2a-8855.1 and darktable can't open .tif files created in GIMP

I provide two .tif to reproduce the issue

[Gradient_test.zip](https://github.com/darktable-org/darktable/files/10374065/Gradient_test.zip)
[20220102_1826.zip](https://github.com/darktable-org/darktable/files/10374073/20220102_1826.zip)

**To Reproduce**

1. In lightable go to add to library button in the lighttable and select the .tif file
2. Click on add to library button
3. See error

**Expected behavior**
The .tif files must be opened.

**Screenshots**
darkroom
![Screenshot-20230109091402-1000x352](https://user-images.githubusercontent.com/67672868/211332668-56f953a6-b281-44b6-b594-7e78b66cd21e.png)

lightable
![Screenshot-20230109091439-529x407](https://user-images.githubusercontent.com/67672868/211332827-e1001fda-2efe-404c-8b1e-22538af5f1f1.png)

**Which commit introduced the error**
Not sure

**Platform**

* darktable version : 4.3.0~git83.2b697a2a-8855.1
* OS: Fedora release 37 (Thirty Seven) x86_64 
* Host: Z390 AORUS MASTER 
* Kernel: 6.0.15-300.fc37.x86_64 
* Uptime: 31 mins 
* Packages: 3247 (rpm), 46 (flatpak) 
* Shell: zsh 5.9 
* Resolution: 3840x2160 
* DE: GNOME 43.2 
* WM: Mutter 
* WM Theme: CustomAccentColors 
* Theme: WhiteSur-dark-solid [GTK2/3] 
* Icons: WhiteSur-dark [GTK2/3] 
* Terminal: gnome-terminal 
* CPU: Intel i7-9700K (8) @ 4.900GHz 
* GPU: NVIDIA GeForce GTX 1070 
* GPU: NVIDIA GeForce GTX 1080 Ti 
* Memory: 7777MiB / 32028MiB 
* Graphics driver: 525.60.11
* OpenCL installed: Yes
* OpenCL activated: Yes
* Xorg:  X11
* GIMP version: 2.10.32

**Comment by kmilos** [comment]
This are BigTIFF files (why, they're not larger than 2GB, can you truen this off in GIMP?), and it all depends on how your system `libtiff` was built, or how the fallback GraphicsMagick/ImageMagick were build and enabled in the darktable build on your particular distribution...

Not much to do w/ darktable itself actually.

**Comment by difrkaguilar** [comment]
The strange thing is that in the previous version 4.0 of darktable it could open those files. The only thing I did was to upgrade to 4.2.
Anyway I will check the recommendations you give me.

**Comment by kmilos** [comment]
This should be fixed in GIMP 2.10.34, please close as unrelated to darktable. @Nilvus
