### ISSUE TITLE
darktable fails to compile on Fedora37 with the latest exiv2

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#13304]
#### **Describe the bug**
Compiling darktable on Fedora37 fails on error 'AnyError' doesn't have a type

#### **To Reproduce**
1. Build darktable with the standard build script with the latest exiv2 files
2. 
```
/home/LintuJuh/darktable/src/common/exif.cc: In function ‘void dt_exif_set_exiv2_taglist()’:
/home/LintuJuh/darktable/src/common/exif.cc:290:17: error: ‘AnyError’ in namespace ‘Exiv2’ does not name a type
  290 |   catch (Exiv2::AnyError& e)
      |                 ^~~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:460: bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o] Error 1
```

#### **Expected behavior**
Compile and build without errors

#### **Additional context**
* darktable version : latest from git with om-1 modifications by @sarunasb 
* OS                : Linux
* Linux - Distro    : Fedora 37
* CMAKE_BUILD_TYPE  : RELEASE
* exiv2: 1.0.0.9 (latest from git)

Issue also created in exiv2 (https://github.com/Exiv2/exiv2/issues/2459)

**Comment by kmilos** [comment]
exiv2 main branch is not meant to be used - i.e. all bets are off and you're on your own...

OM System support is back-ported to the 0.27-maintenance branch if that's what you're after.

**Comment by lintujuh** [comment]
Yes, that's what I'm after.

I checked out 0.27-nightly, I didn't find a branch 0.27-maintenance, and got another error. Did I checkout the right branch?

```
/home/LintuJuh/darktable/src/common/exif.cc: In function ‘char* dt_exif_xmp_read_string(int)’:
/home/LintuJuh/darktable/src/common/exif.cc:4063:53: error: ‘Exiv2::byte* Exiv2::DataBuf::pData_’ is private within this context
 4063 |       xmpPacket.assign(reinterpret_cast<char *>(buf.pData_), buf.size_);
      |                                                     ^~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:460: bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o] Error 1
```

**Comment by kmilos** [comment]
https://github.com/Exiv2/exiv2/branches

**Comment by kmilos** [comment]
Btw, I think you better take this over at discuss.pixls.us, as I don't believe there is neither a darktable, nor an exiv2 issue here...

**Comment by lintujuh** [comment]
My bad, I listed tags, not branches.
Thank you!
