### ISSUE TITLE
OSX: Compiling Darktable fails on Ventura

### ISSUE THREAD

**Issue by abulka** [darktable-org/darktable#13314]
I cannot compile Darktable on my M1 under OSX Ventura using the supplied instructions.

My question was rejected from StackOverflow 
https://stackoverflow.com/questions/75045253/building-darktable-4-2-on-mac-m1
 so am raising the issue here:

**To Reproduce**

I want to build Darktable 4.2 on my Mac M1 which once worked using the instructions https://github.com/darktable-org/darktable/issues/10583 which relies on brew packages. Those instructions seem now identical to the official instructions https://github.com/darktable-org/darktable#building viz:

```
git clone --recurse-submodules https://github.com/darktable-org/darktable.git
cd darktable
git submodule init
git submodule update

# 2. Make sure that homebrew is up-to-date
brew update
brew upgrade

# 3. Install dependencies via homebrew
brew install adwaita-icon-theme cmake desktop-file-utils exiv2 gettext git glib gmic gphoto2 graphicsmagick gtk+3 gtk-mac-integration icu4c intltool iso-codes json-glib lensfun libavif libheif librsvg libsecret libsoup@2 little-cms2 lua libomp ninja openexr openjpeg osm-gps-map portmidi pugixml sdl2 cmocka curl perl jpeg llvm po4a

# 4. Build darktable
./darktable/build.sh --install --build-type RelWithDebInfo --prefix ~/bin/darktable-dev
```

**Expected behavior**

successful compile

However I get the error

```
[ 20%] Linking CXX static library libraw.a
[ 20%] Built target raw
[ 20%] Linking CXX static library libraw_r.a
[ 20%] Built target raw_r
make: *** [all] Error 2
```

and don't know what to do next? I do get an earlier warning about python and `make[2]: *** [share/darktable/CMakeFiles/validate_noiseprofiles_json] Error 127` so maybe its something unique related to Python on my system?

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 4.2
* OS                : OSx Ventura 13.0.1
* Memory            :  16gb
* Graphics card     :  Apple Silicon
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

P.S. Ultimately I want to also build the 'speedier, simpler' fork https://github.com/aurelienpierreeng/ansel as the developer doesn't offer a Mac build of his project, apparently because he doesn't own a Mac.

**Comment by MStraeten** [comment]
did you check https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD_hb.txt ?

**Comment by abulka** [comment]
I wasn't aware of those scripts - thanks.  Did a fresh clone and tried the scripts but got the same error!
```
[ 18%] Building CXX object bin/external/LibRaw-cmake/CMakeFiles/raw.dir/__/LibRaw/src/write/tiff_writer.cpp.o
[ 18%] Building CXX object bin/external/LibRaw-cmake/CMakeFiles/raw.dir/__/LibRaw/src/x3f/x3f_parse_process.cpp.o
[ 18%] Linking CXX static library libraw_r.a
[ 18%] Building CXX object bin/external/LibRaw-cmake/CMakeFiles/raw.dir/__/LibRaw/src/x3f/x3f_utils_patched.cpp.o
[ 18%] Built target raw_r
[ 19%] Linking CXX static library libraw.a
[ 19%] Built target raw
make: *** [all] Error 2
./packaging/macosx/2_build_hb_darktable_default.sh{}:25: Error: command `../../build.sh --install --build-type Release --prefix "$scriptDir"` failed with exit code 2
```

A vague generic google about `libraw` reveals [a post](https://stackoverflow.com/questions/58989803/error-when-linking-libraw-to-shared-object) about a shared object compilation flag but I have no idea if that relates to this issue.

**Comment by apfelkraut** [comment]
@abulka I also ran into this issue once though I am currently not able to reproduce. Would normally recommend to start with a fresh clone, but you did so already. Could it be that your IDE is doing some auto-config and/or auto-build that works against on what you try to achieve in the command line?

Note that in https://github.com/darktable-org/darktable/pull/13345 (improvement) and https://github.com/darktable-org/darktable/pull/13344 (fix) some changes are coming to the original Homebrew build scrips. At least the fix is required to have a successful creation of the app bundle, but it is not related to your issue.

**Comment by abulka** [comment]
@apfelkraut I did all the compilation on the command line, so no IDE involved. Interesting that you cannot reproduce, presumably you have also upgraded to Ventura.

**Comment by cooljeanius** [comment]
Possibly related to [https://trac.macports.org/ticket/69035](https://trac.macports.org/ticket/69035) (which still happens)?
