### ISSUE TITLE
Sony A7iv default colours

### ISSUE THREAD

**Issue by nugecom** [darktable-org/darktable#13317]
* darktable version : 4.2.0
* OS                :  Linux Debian 11, Gnome X11

![DT v RT Sony colours - Jan 2023](https://user-images.githubusercontent.com/8116082/211539261-3ae014a3-8726-466e-ac60-134b1be92379.jpg)

Hi Team,

I've been happily using Darktable (DT) for a few years but a few months ago moved from a Nikon D750 to a Sony A7IV (ILCE-A74).

I reported DT's blown highlight colour inaccuracies in a previous [issue](https://github.com/darktable-org/darktable/issues/12508) post, and this was explained as a work in progress and I learned to correct it in Filmic RGB in the meantime. I also raised a concern that my colours overall didn't look quite right but nobody had any response to other known DT issues with Sony raw files in this regard.

I recently had the pleasure of visiting the Winslow Homer Exhibition at the National Gallery in London. His painting colours are amazing and they prompted me to test the colour accuracy of my Sony camera. The out of camera Sony JPEGs were accurate - and were matched by my Samsung phone JPEG colours.

However, the raw file colours in DT were way off - greens almost missing, reds very subdued. Using the Sony Base Curve option in DT did not improve things. Playing with DT White Balance didn't improve things.

When opening the raw files in Rawtherapee (RT) the colours were accurate - basically matching the out of camera JPEGs and my Samsung phone JPEGs. In other words, RT started with an accurate representation of the painting colours - which I could then edit if I wanted to... but DT did not. Maybe DT could get there with a lot of colour tweaking - but I'd then have to remember the accurate colours for every photograph I make.... which is obviously ridiculous.

This test has proved my suspicions that DT has an issue to fix with regards Sony A7IV colour accuracy  - and my mind has been put to rest that it is not a camera issue!

I prefer the overall capabilities of DT to RT but must now switch to RT for all my processing for the above reasons. I'd welcome your thoughts on this and when DT might be reliable for Sony users.

Regards,

John

**Comment by TurboGit** [comment]
I see nothing to fix since nothing is broken. The dt default is not trying to match the in camera jpeg (see numerous discussions here and in pixls.us). You need to adjust the setting to your taste starting from the RAW almost not touched by dt.

**Comment by gi-man** [comment]
@nugecom 

Please review this section of the manual that explains in more details. https://docs.darktable.org/usermanual/4.0/en/overview/workflow/process/#why-doesnt-the-raw-image-look-like-the-jpeg

**Comment by kmilos** [comment]
@nugecom It's like this: as far as known, dt is not treating Sony cameras any differently to any other camera vendor. So if **_you_** believe something is "wrong", **_you_** (or some other Sony vested user/developer) will have to actually dig in and find out what _**it**_ is, and then submit a meaningful bug report, or even better, a pull request with a fix. That's how open source works.

Until then, it's much more productive to keep at it at discuss.pixls.us as there have been similar opinions voiced over there already in the past, so perhaps keep sharing ideas and poking around will lead to something more meaningful...

> 'Our colours do not match what you are photographing but you can make them whatever you want!' is not a strap line the DT 'marketing department' should approve.

What marketing department? dt is an open source project, not a product.

> I'm coming at this from a position of love for DT, so don't shot the messenger.

"Hell is full of good meanings, but heaven is full of good works"

Nobody is shooting the messenger here, merely suggesting you [check your assumptions about open source in general](https://datasciencelearningcenter.substack.com/p/are-open-source-developers-burning).

**Comment by sg456** [comment]
@nugecom Have you tried using sigmoid instead of filmic? I find with my (admittedly older) Sony it makes a surprisingly good match.

**Comment by nugecom** [comment]
Thanks @sg456. I don't understand the relationship between the physics and the intended benefit but I had a play with the Sigmoid module. Compared to Filmic RGB I found the results were unnaturally contrasty - the white levels being more blown out... and there was no colour benefit. I'm not sure when Sigmoid should best be used TBH.

Despite my earlier comments, I gave up on Rawtherapee! Although initially giving more realistic colours in some images it had a tendency to give more garish colours more often than not. Its workflow and modules are also far inferior to Darktable - annoying examples being: no retained History stack; clunky cropping; and an inability to use masks in modules.

So, following a cold slice of humble pie and some further research (thanks for the links), I believe I've come across a solution to the Sony raw colour problem in DT. It's to use the preset:

'basic colourfulness: standard' in the 'color balance rgb' module. 

...this added a far more natural and realistic colour palette to my images - and skin tones in particular (shifting from grey/green to brown/red) :)

I had been using the 'color balance RGB' module manually by adjusting the 'linear chroma grading' (which worked well when needed for my Nikon D750). I'd understood changing chroma to be better at maintaining colour relationships than changing saturation. However, the above preset changes only the 'perceptual saturation grading' and it looks way better than my previous manual efforts.

My new learnings have updated my workflow (which may also work for other Sony A7IV users) as follows:

- Lens correction ('embedded metadata' seems good... my Tamron 28-75 G2 is not listed)
- Sharpen (default)
- Exposure
- Crop / Rotate and perspective
- Filmic RGB 'white relative exposure'
- Color Balance temperature
- Color balance RGB / basic colourfulness: standard preset
- Haze removal and/or Local Contrast
- Other modules, tweaks and re-tweaks!

@kmilos Given the above seems to have fixed my issue, this is somewhat moot but...

I wish I had the skills to create a technical pull request or help fix pull requests! I must rely on the skills and motivation of others to prioritise and work on my non-technical feedback. I would advocate that Sony is the global market leader in mirrorless camera sales but understand that even priority issues may lack available skills, resource or motivation.

I know DT does not have a 'marketing department'(!) but its market-leading product position is due to the talents and generosity of its core developers (the few) achieving a great product-market fit (for the many) - with a leading vision and, I imagine, 'customer' feedback response. I concede that, as an active advocate for both FOSS and marketing, using such marketing terms may be objectionable!

I'm sympathetic to the challenge of getting developer numbers to correlate with user growth in FOSS. How any maintainers / contributors does DT have? Has anyone estimated the number of users? 50k? 100k? I guess we need to encourage more developers to be raw photographers! A shrinking number I fear... but perhaps another 'marketing' challenge ;)

**Comment by kmilos** [comment]
Glad you persisted and getting results. There seem to be even more Sony workflow sharing going on over at https://discuss.pixls.us/t/best-practice-for-unexpected-white-balance-coefficients-in-darktable/34758
