### ISSUE TITLE
"Delete" button in Shortcuts

### ISSUE THREAD

**Issue by contoperitest** [darktable-org/darktable#13318]
It would be really nice if you could add a "Delete / Remove" button in Settings / Shortcuts so we could remove those shortcuts that we don't use on a daily basis and which create a big problem for those of us who accidentally press a key on the keyboard and something unexpected and often undesired happens.
![dt](https://user-images.githubusercontent.com/122364944/211550018-feb26ba7-310f-4328-bd85-1fbaa01b2e5c.jpg)

**Comment by dterrahe** [comment]
https://darktable-org.github.io/dtdocs/en/preferences-settings/shortcuts/#deleting-default-shortcuts

**Comment by contoperitest** [comment]
Thank you so much!

**Comment by TurboGit** [comment]
> Thank you so much!

Then please close this issue.
