### ISSUE TITLE
Translation suggestion

### ISSUE THREAD

**Issue by contoperitest** [darktable-org/darktable#13323]
Hi, how to contact with a Polish language translator in order to suggest him / her a better translation of some terms used in the program? I wasn't able to find a place on GitHub to do so.

**Comment by victoryforce** [comment]
I would write to the email listed in the Last-Translator field of the pl.po file.

**Comment by TurboGit** [comment]
You can find it here:
https://github.com/darktable-org/darktable/blob/master/po/pl.po

**Comment by contoperitest** [comment]
Excellent, thank you very much!
