### ISSUE TITLE
White point for Canon 5D Mk III at some ISOs incorrect

### ISSUE THREAD

**Issue by afranke** [darktable-org/darktable#13320]
I have some old shots that I never got to process and wanted to work on now. They are from a Canon 5D Mk III that I don’t own anymore. I looked at the set and everything looked fine until I stumbled upon a few pics where the highlights were very pink. I looked up existing reports and stumbled upon #6548, then looked back at my pics, and noticed that the ones with the weird hue are shot at ISO 160 (whereas those at e.g. ISO 100 look fine).

Unfortunately, as I don’t have the camera anymore, I can’t provide an array of pics at different ISOs. From reading the aforementioned report, I’m not sure if the “better solution” ever was implemented and if it should be working based on the value in the CR2.

Let me know if I can get and provide the white value from one of those old CR2 files I own. I have a fair number of them, so I could run some exiftool invocations to find the pics at various ISO that I do have, and eventually try to gather the missing data.

**Comment by afranke** [comment]
Out of curiosity I looked at what exiftool could tell me about one of these ISO 160 pics and noticed these two fields:
```
Normal White Level              : 11388
Specular White Level            : 11900
```
whereas the white point in DT is set to 13700. If I change it to one of the two values above, it looks alright. Can you confirm that one of them is what we’re after, and which one it is?

**Comment by kmilos** [comment]
I think the specular white... There's been related work to read more of this metadata in rawspeed (see e.g. https://github.com/darktable-org/rawspeed/pull/349#issuecomment-1277781235), so it would be great if you can help with a PR for Canon CR2s

**Comment by afranke** [comment]
For an ISO 100 pic, exiftool tells me
```
NormalWhiteLevel                : 14582
SpecularWhiteLevel              : 15094
```
while DT is set to 15200. Should this be corrected to 15094?

**Comment by kmilos** [comment]
> Should this be corrected to 15094?

Should what be corrected?

As mentioned, the end solution is that the specular white level is read from file's metadata in rawspeed, and not messing w/ per-model, per-ISO tables any longer.

**Comment by gi-man** [comment]
I think Issue should be in Rawspeed instead of darktable repo.

**Comment by afranke** [comment]
I agree that reading from the metadata would be ideal. I can *help* crafting the PR, but I don’t think I can write it myself. I found https://exiftool.org/TagNames/Canon.html#ColorData4 which has the info we need. I looked at https://github.com/darktable-org/rawspeed/pull/385 and I don’t even know where to start to write the equivalent for this case.

> I think Issue should be in Rawspeed instead of darktable repo.

Sure, can you move it?
