### ISSUE TITLE
Noise profile for Fujifilm X-H2s

### ISSUE THREAD

**Issue by allmyfavoriteusernamesaretaken** [darktable-org/darktable#13325]
Noise profile for Fujifilm X-H2s:
[darktable-noiseprofile-20230111.tar.gz](https://github.com/darktable-org/darktable/files/10395495/darktable-noiseprofile-20230111.tar.gz)

**Comment by Nilvus** [comment]
@allmyfavoriteusernamesaretaken: could you update your title and add noise profile on it like you does for your other issue about white balance presets? Thanks! I update assignement and labels regarding that.

**Comment by allmyfavoriteusernamesaretaken** [comment]
Sure, done.

**Comment by allmyfavoriteusernamesaretaken** [comment]
Here we go:

[darktable-noiseprofile-20230203.tar.gz](https://github.com/darktable-org/darktable/files/10581715/darktable-noiseprofile-20230203.tar.gz)

**Comment by rawfiner** [comment]
It looks perfect, thanks!
