### ISSUE TITLE
RFC Some export options

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#13324]
**Possibly reduce a few export options**
In the export dialog we have two options to be clicked i'd like to discuss.

1. **allow upscaling** whatever your size setting in the dialog is, you can only enlarge the image if upscaling is allowed. I think this is redundant as if the user selects a size that's what is wanted and should include a possibly required upscale. (It could be understood like an additional "confirmation: yes i want that" though)
2. **high quality resampling** If set to true the pipeline will work without downscaling after demosaic and do the scaling at the very end of the pixelpipe. From my understanding we now have a number of modules that either work better with full data or at least might differ in output)

**I would suggest** and wait for your positions on this before doing the code
1. Remove option (1) so upscaling is allowed whenever the requested size needs this
2. Remove option (2) so we always do hq exporting

**Additional context**
Two points worth mentioning:
1. Currently we can only upscale with given size, using scale doesn't work
2. We have a maximum upscale factor of 100 hard-coded right now, will try to change this so we can only upscale to a size supported by the system memory.

**Comment by spaceChRiS** [comment]
Please, don't remove “allow upscaling”. The use case is: I want all my images exported at 4096 px on the long side, unless the input data has less pixels, e.g. a tight crop or an image from a camera that has less resolution.

I also have a use case for switching off high quality resampling: Exporting previews. I was just last week exporting all images from a vacation at small size for the others to include some of them in a photo book draft, such that I only have to edit those that will actually be used when the draft is ready. For ~1300 pictures, it's a massive speed difference. But for these I am not too worried if the rendition of some modules is not accurate. Maybe high-q should be the default and the option should be called low-q though.

Something which I have absolutely no use case for is the upscaling. If I really need this, e.g. for large scale printing, I would search for an external solution, as the (AI) algorithms improve daily and the darktable upscaling will be less quality most probably. But maybe I am missing something.

**Comment by mbaz** [comment]
1. Unsure. I can conceive of a use case where images of different sizes (for example, taken with different cameras) are being exported. Large images should be downsized, but smaller images should not be upsized. I imagine this is not a common workflow, but it may be worth it to keep supporting it.
2. I vote to remove it. I don't see the point of using DT and then throwing out the result's quality when exporting.

**Comment by spaceChRiS** [comment]
> 2\. I don't see the point of using DT and then throwing out the result's quality when exporting.

I know I already made my point, but I'd like to add: Darktable is not only a raw editor, but also an asset manager. Some more detail on my example: For the preview images, I had an automatic preset applied that adds the text “low-quality preview” on the image and a red-yellow frame around, such that no preview slips through eventually. Yes, I could have exported over night, but it was very welcome to have the low-q option.

**Comment by MStraeten** [comment]
allow upscaling: might be not necessary for single image processing, but with batch processing of images with different crops it makes sense to disable upscaling in cases all images should be (down)scaled to a given maximum target size. Since upscaling affects image quality there should be a solution for both use cases:
- (up/down-)scale to a given size 
- downscale to a given size but don’t upscale to it.

**Comment by TurboGit** [comment]
> 2\. We have a maximum upscale factor of 100 hard-coded right now, will try to change this so we can only upscale to a size supported by the system memory.

This may be hard, but certainly a good goal.

**Comment by jenshannoschwalm** [comment]
Ok. Thanks for the feedback about your / possible workflows. (A clear vote to keep them both ...)
