### ISSUE TITLE
Color Calibration Presets can not be selected

### ISSUE THREAD

**Issue by AchimDittrich** [darktable-org/darktable#13336]
When I select the Color Calibration and want to use one of the Balck & White presets, I can either not even select one with the mouse or when I select one using the arrow keys an the keyboard, I can not set them using the <Enter> key.

darktable 4.2.0 on macOS Ventura 13.1 on an Apple M1 Pro MacBook.

<img width="1270" alt="Bildschirm­foto 2023-01-14 um 11 58 07" src="https://user-images.githubusercontent.com/121246256/212468766-f7fadacd-ff53-4886-b569-df817d8862f3.png">

**Comment by Nilvus** [comment]
A known issue on some menu. It's not a darktable issue but an upstream library one on Ventura. This should be fixed soon when Macports will be updated. Think about searching (there's already some issues about that) before posting. Thanks!

For example, just with Ventura keyword, closed issues: https://github.com/darktable-org/darktable/issues?q=is%3Aissue+ventura+is%3Aclosed

And opened first one with all explanations: #12727

**Comment by AchimDittrich** [comment]
Ok and fine but only theoretically. But how shall I know that it has something to do with Ventura?

 
 

Gesendet: Samstag, 14. Januar 2023 um 13:34 Uhr
Von: "Nicolas Auffray" ***@***.***>
An: "darktable-org/darktable" ***@***.***>
Cc: "AchimDittrich" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [darktable-org/darktable] Color Calibration Presets can not be selected (Issue #13336)


 

A known issue on some menu. It's not a darktable issue but an upstream library one on Ventura. This should be fixed soon when Macports will be updated. Think about searching (there's already some issues about that) before posting. Thanks!

For example, just with Ventura keyword, closed issues: https://github.com/darktable-org/darktable/issues?q=is%3Aissue+ventura+is%3Aclosed

And opened first one with all explanations: #12727

**Comment by Nilvus** [comment]
Presets and selected keywords should also work. Anyway, see also: https://discuss.pixls.us/t/current-osx-build/13213/591

**Comment by AchimDittrich** [comment]
Thanks for the notification, Nicolas!

 

I wait for the next stable macOS X / ARM version for my MacBook Pro then.


 

Homepage: achimdittrich.de / achimdittrich.com
Instagram: achimdittrich_photography

 
 

Gesendet: Sonntag, 15. Januar 2023 um 12:00 Uhr
Von: "Nicolas Auffray" ***@***.***>
An: "darktable-org/darktable" ***@***.***>
Cc: "AchimDittrich" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [darktable-org/darktable] Color Calibration Presets can not be selected (Issue #13336)


 

Presets and selected keywords should also work. Anyway, see also: https://discuss.pixls.us/t/current-osx-build/13213/591
