### ISSUE TITLE
Exclude filter seems to no work anymore on collections module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13334]
**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to collections module
2. Start with all images shown (for example starting by filmroll with all filmrolls)
3. click on arrow beside to exclude images
4. for example, choose module then a module to show images that do not have that module
5. See that images shown remains images that have the module ("except" condition seems to work same as and or or)

**Expected behavior**

Having except condition working as before, as except condition!

I see that because I've noticed some images without lens correction module activated and I would quickly found them. I have had that possibility before and no more now.

**Screenshots**
![image](https://user-images.githubusercontent.com/45535283/212383988-086095a5-5151-40fd-a673-cd4cdf9d45b5.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : actual master

**Comment by Nilvus** [comment]
Seems that some refresh issue had been introduced. With quite hard difficulty by moving between filters and lists, I can make the list updated but not easy.

**Comment by TurboGit** [comment]
@AlicVB : Probably for you as you master this part of dt.

**Comment by TurboGit** [comment]
I confirm, and this happens only when we have all filmrolls (or whatever empty condition first selecting all images). Then exclude does not exclude but select actually the images.
