### ISSUE TITLE
More powerful/flexible cropping (request)

### ISSUE THREAD

**Issue by spacebanana420** [darktable-org/darktable#13332]
The cropping operation is great since it allows for both freehand cropping and cropping with a locked aspect ratio. However, cropping with locked aspect ratio is only supported for the available aspect ratio presets, I can't specify my own if i wanted to.

I propose the addition of the ability to specify a custom aspect ratio and then being able to resize the cropped area from there. This would allow the user to specify any possible aspect ratio and no longer be limited to either freehand cropping or using the available aspect presets.

Another feature that would empower the crop operation would be to be able to manually input the value of the crop margins, instead of only using the slider, and to change the measurement of the cropping margins from percentage to pixels. Sometimes it's better to set the size manually in pixels than to use the slider or to crop visually.

**Comment by ralfbrown** [comment]
Already implemented.  See https://docs.darktable.org/usermanual/development/en/module-reference/processing-modules/crop/

**Comment by spacebanana420** [comment]
Thank you for letting me know. I had no idea that this was already implemented until reading the documentation/hovering the cursor on top of the aspects menu.
