### ISSUE TITLE
Spyder Checkr Photo support in color calibration module

### ISSUE THREAD

**Issue by kadykov** [darktable-org/darktable#13339]
**Spyder Checkr Photo does not fit well in the existing color patches pattern**
In the color calibration module, there is a possibility to calibrate a camera sensor by taking a shot of a color checker with a predefined pattern of color patches like Datacolor SpyderCheckr 48. One of these devices is [Spyder Checkr Photo](https://spyderx.datacolor.com/spyder-checkr-photo). One of the clear advantages of it is that it is small and easily fits into a pocket, encouraging you to take it everywhere you need accurate colors.

I have tried to calibrate my camera with it, but I faced the problem that the existing pattern from Datacolor SpyderCheckr 48 does not fit very well. As you can see in the screenshot below, the distance between the left and the right panels is slightly larger than in the Datacolor SpyderCheckr 48.
![Screenshot from 2023-01-14 16-22-52](https://user-images.githubusercontent.com/62546709/212480759-833ad07c-4d94-43c2-ba87-968181859e94.png)

**Creating a separate pattern of color patches**

It would be great to have a separate pattern of color patches for the Spyder Checkr Photo. Assuming the colors are the same as in Datacolor SpyderCheckr 48, it is sufficient to increase the distance between the left and right patch sets.

**Adjust left and right sides separately**
Another solution is to split the existing Datacolor SpyderCheckr 48 pattern into two sets and let the user adjust the position of the left and the right sides separately. The clear advantage of this solution is that it would be easier to adjust for any geometrical distortions, for instance, when the color checker is not fully open to 180 degrees. 

**Keep it as is**
It is possible to use the Spyder Checkr Photo even with the existing pattern from Datacolor SpyderCheckr 48, but the maximum patch scale should be less than 0.5 or 0.3 if you want to avoid any edge effects.
![Screenshot from 2023-01-14 16-21-02](https://user-images.githubusercontent.com/62546709/212480707-0b0a6cfc-b95b-47ac-a516-38c36f561af8.png)

You can find a sample image of the color checker [here](https://www.diyphotography.net/wp-content/uploads/2022/09/datacolor-spyder-checkr-colours.jpg)
![datacolor-spyder-checkr-colours](https://user-images.githubusercontent.com/62546709/212483137-6b8cef1b-c55a-4be3-a1d4-8a81d7ae766e.jpg)

**Comment by TurboGit** [comment]
See #13174, it is currently not supported as the patches are not yet validated by datacolor.

**Comment by kadykov** [comment]
Fixed by #13174
