### ISSUE TITLE
Olympus E-M10 Mark III S

### ISSUE THREAD

**Issue by dorpauli** [darktable-org/darktable#13340]
The problem is, that the E-M10 Mark III seems to be supported, but the S model is not. It is actually the same camera, just with silent shutter support as i am right. 

Since i use it, the lens correction module is time consuming, because i always have to manually select the camera. I have fixed this on lensfun side!

The main problem now is, that the new feature (see quote) is not working with the Olympus E-M10 Mark III S. I know from another software, that there is lens correction information inside the EXIF data.

> "Some cameras record lens correction information within the image EXIF metadata. The lens correction module has been enhanced so that it can extract this data and use it to correct lens distortions." 

If i can help, let me know.

**Comment by Nilvus** [comment]
You didn't precise your darktable version. I hope, regarding your quote, that you use 4.2. That feature had been added on 4.2. About selecting camera on lens correction module, this is a lensfun issue, not darktable one.

And please update your title and precision about lens correction inside EXIF issue. Your issue is not a camera support issue but a part of it. At first, I was thinking about another duplicate as this camera is already supported on darktable.

**Comment by kmilos** [comment]
Should have been handled in https://github.com/darktable-org/darktable/issues/11803 already and working OOTB in dt 4.2.

**Comment by kmilos** [comment]
Re the lens correction from Exif, only Sony and Fujifilm support has been implemented so far. See https://github.com/darktable-org/darktable/pull/12714 and continue discussion there.

**Comment by Nilvus** [comment]
Thanks @kmilos. That make me remind that there a pull request as WIP about that: #12760
As this is not an issue nor camera support to add and there's already that PR, I close.

**Comment by dorpauli** [comment]
First of all. yes I tried version 4.2. And here both the DEB package, and the Flatpak. 
Secondly, I already noticed that I fixed the problem with lens correction selection on Lensfun. There I have also created a PR. My issue shouldn't be about that. I shouldn't have mentioned that.

Sorry for this unnecessary  issue, but in the documentation (https://www.darktable.org/resources/camera-support/) the camera is not mentioned and as you can see in https://github.com/darktable-org/darktable/issues/11803 it is handled differently than the EM-10 Mark III. I was also aware of the discussion before, because I used the workaround there myself until the new version 4.2. I was just not aware that it is now considered officially supported.

I searched the Issues before, just didn't find https://github.com/darktable-org/darktable/pull/12714 unfortunately. This was the final hint I need. I assumed that with the new feature, all models were already supported. Sorry for the confusion.

So thanks for all the advice. I would be really happy about the feature, because it improves the workflow significantly. Have a nice Sunday!

**Comment by Nilvus** [comment]
Just a thing: camera support on darktable website is quite outdated. It's known issue you can see on dtorg repository.
