### ISSUE TITLE
Lens Correction: embedded metadata for Fujifilm X-Trans series 

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#13358]
Dear Developers,
I am very glad to see in dt 4.2 that for my Fujifilm X-T4 RAW files (extension RAF) the Lens Correction module can handle the embedded lens correction profile. Now while I can't test it, I assume this may work for other Fujifilm camera's with the same generation sensor: X-T3, X-T30, X-E4, X-S10, X-Pro3.
For earlier generation sensors the embedded lens correction profile does not seem to be recognized, as I tested this on the RAW files from the former generation sensors of Fujifilm X camera's: X-T2, X-E2, X-E1.
If you have plans to further include the handling of the embedded lens correction profile from the 3 former generation sensors of Fujifilm X camera's, I can offer RAW files, if that is helpful. Just give me a sign, including the method about how I can send those.
Kind regards,
Marc.

**Comment by kmilos** [comment]
At lest the X-T2 sample on raw.pixls.us seems to have a different number of correction parameters (23/31/23) than [what is currently supported (19/29/19)](https://github.com/darktable-org/darktable/blob/ab60408274b65b73498210b4a5bda6ee5a849dd8/src/common/exif.cc#L795) by https://github.com/darktable-org/darktable/pull/12714 @sgotti @FreddieWitherden

**Comment by FreddieWitherden** [comment]
When I wrote the original code I made it deliberately conservative in terms of what it would accept.  Namely, only what I was able to observe with my camera (an X-T3).  However, I strongly suspect that the model has not changed substantially between generations and so it should be relatively straightforward to add support.

Best case would be an image taken on an X-T2 and X-T3 with the latest firmware and the same lens (at the same settings).  This would make it possible to cross-check the correction and see if everything is compatible.  If so, it is an easy fix.

**Comment by cabuy** [comment]
Hello Freddie, hello Milos, I am prepared to help providing the RAW files you need (if not too complicated). I still have (at least) 1 camera from each of the previous Fujifilm X-Trans generations (X-T4, X-T2 & X-T20, X-E2, X-E1, all acquired as 2nd hand). So if you like and if you tell me what kind of picture you want on the RAW files, I can do that through the same lens with the same settings. My thought was to use the standard kitlens (18-55, I observed its cushion distortion at 55mm), at the long end and at the short end, taking pictures at the same settings (aperture wide open) of a wall in white rectangle bricks. I can provide that by somewhere 2nd half next week. Let me know if that would be helpful or if you think another lens may be better (like the 35mm F2, it has strong barrel distortion). And where would you like me to leave or send the files ?

**Comment by FreddieWitherden** [comment]
I do not know the best way to share the files, although the proposed sequence of shots should do the trick.

**Comment by SZim92** [comment]
If the Bayer Fuji files handle this differently, I can potentially grab a similar sample with an X-A1.

**Comment by cabuy** [comment]
Hello Freddie,

Herewith I am trying to provide you sample RAW and JPG files of the same scene (a detail from an Ikea cupboard ***) at the same settings with the same lens (35mmF2) on different Fujifilm camera’s:
X-T4 (RAW format assumed to be equivalent to X-T3, X-Pro3, X-T30, X-E4, X-S10, X-T30II)
X-T2 (RAW format assumed to be equivalent to X-H1, X-Pro2, X-T20, X-E3)
X-T20 (RAW format assumed to be equivalent to X-T2, and see above)
X-E2 (RAW format assumed to be equivalent to X-T1, X-T10, X-E2S)
X-E1 (RAW format assumed to be equivalent to X-Pro1, X-M1)
(Perhaps the lens correction profiles are also included in the fixed lens camera’s like the X100-series or X70.)

The JPG files should show the in-body corrected images at full resolution. Some of them seem to have over-corrected the barrel distortion into some pincushion distortion.

The images can be downloaded from this (WeTransfer) link until January 27th: [https://we.tl/t-ZYsTv75Cs5]

Let me know if this helps you further … or how if I can help you further.

And thanks for your contribution to darktable.

Marc.

*** PS  I don't have enough (daylight) time these days to provide images of a wall

**Comment by FreddieWitherden** [comment]
Yes, I have the files and will review them over the weekend to try and decode how the corrections are managed.

**Comment by cabuy** [comment]
OK, success. Thank you. Marc.

**Comment by sgotti** [comment]
I just made some quick tests on images from https://raw.pixls.us/ for Fuji XT-1, X-T2, X-T20 that have the same lens correction metadata format and it looks like they are quite similar to the currently implemented one for newer fuji camera.

Basically the number of knots of the spline is 11 instead of 9 and the CA metadata don't provide the center (first at 0) knot.

I'll need some more tests since it was just a 15 minutes effort but I wanted to keep this issue alive. 

If all goes well I'll open a PR in the next days.

**Comment by cabuy** [comment]
Thank you Simone. I am not a developer but an enthusiast dt user. Can I help with providing the files again that I provided on January 21st (see above comment of January 21st, if you don' have them yet) ?  Where can I leave these ?

**Comment by sgotti** [comment]
Created PR #14297 . It should cover all X-Trans I/II/III cameras (no bayer ones)

@cabuy I used the images available on https://raw.pixls.us/. If you want to upload you raw files somewhere where I can fetch them I'll try them (if some camera are missing you could also provide them on https://raw.pixls.us, read the policy in the home page). Thanks.

**Comment by cabuy** [comment]
Simone, I have resend the same images as I did before under this link: https://we.tl/t-HZ8qpSVTni  .
This link is available until april 29th. If you like, you can test.
These are RAW and JPG files of the same scene (a detail from an Ikea cupboard ***) at the same settings with the same lens (35mmF2) on different Fujifilm camera’s:
X-T4 (RAW format assumed to be equivalent to X-T3, X-Pro3, X-T30, X-E4, X-S10, X-T30II)
X-T2 (RAW format assumed to be equivalent to X-H1, X-Pro2, X-T20, X-E3)
X-T20 (RAW format assumed to be equivalent to X-T2, and see above)
X-E2 (RAW format assumed to be equivalent to X-T1, X-T10, X-E2S)
X-E1 (RAW format assumed to be equivalent to X-Pro1, X-M1).
(For uploading on raw.pixls.us, I need to review whether a camera is missing. I'll do that later.)

**Comment by sgotti** [comment]
@cabuy Thanks. I tested your images and comparing the ooc jpegs with the output from PR #14297 they looks very similar.

As a side node, lensfun correction for the xf 35 f2 (that I also own) is better (you can see it at straight lines at the sides) with but it could be tuned with the "distortion fine tune" option in metadata correction. But this isn't related to metadata correction algorithm since it's noticeable also in the ooc jpegs.

**Comment by cabuy** [comment]
Hey Simone, thank you.  
I noted some less adequate  correction before too (see above): "The JPG files should show the in-body corrected images at full resolution. Some of them seem to have over-corrected the barrel distortion into some pincushion distortion."
Looking forward to see this materialized in dt 4.4 . (I am a Windows user and assume that 4.3 builds are not available ?) Cheers;

**Comment by victoryforce** [comment]
> I am a Windows user and assume that 4.3 builds are not available ?

Windows nightly builds are available, actually. See https://github.com/darktable-org/darktable/actions/workflows/nightly.yml

**Comment by wpferguson** [comment]
weekly builds are also available at https://discuss.pixls.us
