### ISSUE TITLE
[filmicRGB] latitude is always 0%

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#13354]
I'm quite sure that in previous versions the latitude value in the look tab was always something > 20%.

Now (v4.2), it's always 0%, and I think that this value is not the better one in order to get a good image

**Comment by MStraeten** [comment]
it was changed intentionally

**Comment by Nilvus** [comment]
This had been changed by Aurélien on his fork about 7 months ago (https://github.com/aurelienpierreeng/ansel/commit/60bbf83ac5de291344923861aaec464f29879209)and added on darktable master about 3 months ago. Aurélien had explained (I can't remember where) why he does the change. So as this module is his work, this probably won''t change as he know what he does. You could change that on your side and create a preset.

I so close that.
