### ISSUE TITLE
On import, darktable cannot see the correct DateTimeOriginal in a JPG file

### ISSUE THREAD

**Issue by orthorhombic** [darktable-org/darktable#13355]
**Describe the bug/issue**
When importing old JPG files from a Canon camera, I'm seeing the same behavior as described in #12137 (fixed in #12158). The datetime within darktable I am seeing is show as `Mon 01/01/1 12:00:00 AM`. While I have not been able to dig into this too much, I suspect it might be related to the parsing of the timestamp? Exiv2 output from the file is below. I'm happy to provide a full dump of metadata or a sample file if it may prove useful.

```bash
$ exiv2 -pa Christmas-4383.JPG | grep Date
Warning: Directory Canon has an unexpected next pointer; ignored.
Exif.Image.DateTime                          Ascii      20  2005:12:25 21:52:48
Exif.Photo.DateTimeOriginal                  Ascii      20  2005:12:25 21:52:48
Exif.Photo.DateTimeDigitized                 Ascii      20  2005:12:25 21:52:48
Xmp.exif.DateTimeOriginal                    XmpText    25  2005-12-25T21:52:48-05:00
Xmp.exif.DateTimeDigitized                   XmpText    25  2005-12-25T21:52:48-05:00
Xmp.xmp.ModifyDate                           XmpText    25  2005-12-25T21:52:48-05:00
Xmp.xmp.CreateDate                           XmpText    25  2005-12-25T21:52:48-05:00
Xmp.xmp.MetadataDate                         XmpText    29  2009-05-19T23:47:46.656+04:00
```

**To Reproduce**
Import a problematic jpg file with or without a sidecar file.

**Expected behavior**
The datetime is correctly populated in the "image information" panel and in on hover over images

**Platform**

* darktable version : 4.2.0, installed via snap (https://snapcraft.io/darktable)
* OS                : Linux - kernel 5.19.0-28-generic
* Linux - Distro    :  Ubuntu 22.04 
* Memory            :  64gb
* Graphics card     :  Nidia A2000
* Graphics driver   :  NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7 
* OpenCL installed  :  
* OpenCL activated  :  
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
* Copies were added to darktable through the "add to library" button from either an NFS share or local storage. I've observed this with photos taken in 2005-2013 (so far) with the following cameras: Canon 20D, EOS Digital Rebel, or EOS 5D Mark II.
* Timestamps are seen correctly by other software (e.g. gthumb).
* The newly created xmp file has an empty date: `exif:DateTimeOriginal=""`

**Comment by orthorhombic** [comment]
This seems to happen with files from more cameras. I suspect this is as a result of these files having been touched by Lightroom.  Below is a sample image from a Casio EX-Z40. Any suggestions are welcome.

![Summer 05-1456](https://user-images.githubusercontent.com/34923517/213327275-a29a4751-eccb-4bc6-a67e-978227fcd62d.JPG)

**Comment by orthorhombic** [comment]
After exploring this further, I suspect it to be a problem with these two lines:
https://github.com/darktable-org/darktable/blob/a4e843ee012d64ba374a21e271837d4ddc921fb7/src/common/datetime.c#L76
https://github.com/darktable-org/darktable/blob/a4e843ee012d64ba374a21e271837d4ddc921fb7/src/common/datetime.c#L78


Maybe it is something funny with character encoding of the `-` or maybe we need some more parentheses in there to get the OR logic working. (I'm not really fluent in this programming language)

These will import with the date:
```
$ exiv2 -M"set Xmp.exif.DateTimeOriginal XmpText 2005-07-03T17:45:29+04:00" 213327275-a29a4751-eccb-4bc6-a67e-978227fcd62d.JPG
$ exiv2 -M"set Xmp.exif.DateTimeOriginal XmpText 2005-07-03T17:45:29+04" 213327275-a29a4751-eccb-4bc6-a67e-978227fcd62d.JPG
```

These will not import with the date:
```
$ exiv2 -M"set Xmp.exif.DateTimeOriginal XmpText 2005-07-03T17:45:29-04:00" 213327275-a29a4751-eccb-4bc6-a67e-978227fcd62d.JPG
$ exiv2 -M"set Xmp.exif.DateTimeOriginal XmpText 2005-07-03T17:45:29-04" 213327275-a29a4751-eccb-4bc6-a67e-978227fcd62d.JPG
```

**Comment by orthorhombic** [comment]
@victoryforce - Do you see anything in your code from #12158 that would make it work for `+` and not `-` for dropping the time zone? If not, could you by chance try reproducing the error I'm seeing from the comment above? With my limited understanding, your code looks good. Unfortunately I'm not set up to build darktable at the moment, or I'd try adding some extra parentheses to see if it helped.

**Comment by victoryforce** [comment]
Thanks for tagging me. I will look into it tomorrow.

**Comment by victoryforce** [comment]
@orthorhombic As it turns out, this bug has been in the code since the summer of 2021. Unfortunately, developers do not always have time and high-quality datasets to test the changes made. So thanks again for the bug report. I'll make the fix today and hope it still makes it into the 4.2.1 corrective release.

> @victoryforce - Do you see anything in your code from #12158 that would make it work for `+` and not `-` for dropping the time zone? If not, could you by chance try reproducing the error I'm seeing from the comment above? With my limited understanding, your code looks good.

Yes, my code you pointed out is good. There is no error in it. The problem was in the sanitization function, which, among other things, was meant to replace the `-` in the date record with a `:`. But at the same time, this code also replaced `-` before the time zone value, which made the date-time value incorrect and led to the "zero" date being entered in the database.

**Comment by orthorhombic** [comment]
@victoryforce - I'm a software developer too (just not in this language), so I totally get these things pop up! I'm also crossing my fingers it makes it into 4.2.1. 

Thank you again for taking the time to poke at this and find the underlying issue! I'm just getting started with darktable and hope to contribute more in the future.
