### ISSUE TITLE
Inpaint opposed highlight reconstruction OpenCL code 5x slower than CPU code

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#13362]
**Describe the bug/issue**

After the change in the following PR, I see a significant slow-down in the "inpaint opposed" OpenCL code: https://github.com/darktable-org/darktable/pull/13254

OpenCL turned off:
`[dev_process_image] pixel pipeline processing took 0,164 secs (1,021 CPU)`
see log [without_open_cl.txt](https://github.com/darktable-org/darktable/files/10439761/without_open_cl.txt)

With OpenCL:
`[dev_process_image] pixel pipeline processing took 0,953 secs (0,382 CPU)`
see log [with_open_cl.txt](https://github.com/darktable-org/darktable/files/10439760/with_open_cl.txt)

According to this log the culprit seems to be the function ``highlights_chroma``.

Can you maybe have a look @jenshannoschwalm?
At the same time I want to thank you for all your valuable contributions to the hlr code, this made DT so much better for dealing with blown highlights!

**To Reproduce**

* Make sure OpenCL is activated and used.
* Load random RAW image and turn on "inpaint opposed" method in the highlight reconstruction module.
* Zoom in and out to enforce pixel pipe to recompute image very often

Compare with darktable running with OpenCL turned off (add `` --disable-opencl`` to darktable command)

**Expected behavior**

Runtime equal or shorter as before change, as code changes were supposed to increase performance.

**Which commit introduced the error**

This PR introduced the change: https://github.com/darktable-org/darktable/pull/13254

**Platform**

* darktable version : latest master (4.3.0+244~g2131b15f6-dirty)
* OS                : Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 32 GB
* Graphics card     : AMD Radeon rx 5700 xt 
* Graphics driver : amdgpu 5.4
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by gi-man** [comment]
I'm not seeing the same. Fedora 37 KDE X11 Nvidia 525.78 4.3.0~git245.bf38c1a9

54.250932 [dev_pixelpipe] took 0.004 secs (0.006 CPU) [full] processed `highlight reconstruction Inpaint' on GPU, blended on GPU

70.252910 [dev_pixelpipe] took 0.056 secs (0.474 CPU) [full] processed `highlight reconstruction Inpaint' on CPU, blended on CPU

**Comment by da-phil** [comment]
> I'm not seeing the same. Fedora 37 KDE X11 Nvidia 525.78 4.3.0~git245.bf38c1a9
> 
> 54.250932 [dev_pixelpipe] took 0.004 secs (0.006 CPU) [full] processed `highlight reconstruction Inpaint' on GPU, blended on GPU
> 
> 70.252910 [dev_pixelpipe] took 0.056 secs (0.474 CPU) [full] processed `highlight reconstruction Inpaint' on CPU, blended on CPU

which GPU do you use?
I'm afraid this issue might be related to AMD GPUs...

**Comment by jenshannoschwalm** [comment]
Yes, could be related to performance of atomic instructions. Could you post your GPU device settings? Any opencl tuning?

**Comment by zisoft** [comment]
I can confirm this on my Mac with an AMD Radeon Pro 5500M 8 GB

**Comment by jenshannoschwalm** [comment]
Sure. The problem is, only Nvidia cards support proper atomic float adding... Will need to change the Algo.

**Comment by da-phil** [comment]
My Intel laptop GPU (Intel UHD Graphics 620) seems not to be affected, it's slow no matter whether it takes the CPU or GPU path :smile:

**Comment by da-phil** [comment]
I also tried your hotfix on my AMD GPU and it works as expected :+1:

**Comment by MStraeten** [comment]
issue reproducible on my intel mac+amd gpu (not just 5 times slower):
```
10,243603 [dev_pixelpipe] took 0,005 secs (0,008 CPU) [full] processed `Weißabgleich' on GPU, blended on GPU
27,642235 [dev_pixelpipe] took 17,399 secs (4,271 CPU) [full] processed `Spitzlicht-Rekonstruktion' on GPU, blended on GPU
```
cpu only:  
```
119,4421 [dev_pixelpipe] took 0,005 secs (0,008 CPU) [full] processed `Weißabgleich' on GPU, blended on GPU
119,5176 [dev_pixelpipe] took 0,075 secs (0,611 CPU) [full] processed `Spitzlicht-Rekonstruktion' on CPU, blended on CPU

```

**Comment by gi-man** [comment]
> 

Hannos, what about defaulting the AMD cards to avoid atomics using the device specific OpenCL config (eg. cldevice_version_canonicalname=a b c d e f g h i)?

**Comment by TurboGit** [comment]
@jenshannoschwalm : Given your last comment maybe we can just wait and not merge the quick&dirty fix. There is no urgency as breakage is to be expected on master. Something is urgent only if it could breaks edits. Let me know if it is fine with you.

**Comment by MStraeten** [comment]
> Hannos, what about defaulting the AMD cards to avoid atomics using the device specific OpenCL config (eg. cldevice_version_canonicalname=a b c d e f g h i)?

toggling the first digit according to https://docs.darktable.org/usermanual/4.0/en/special-topics/mem-performance/#device-specific-opencl-configuration from 0 to 1 doesn't change the performance on my mac with amd gpu

**Comment by jenshannoschwalm** [comment]
> toggling the first digit according to https://docs.darktable.org/usermanual/4.0/en/special-topics/mem-performance/#device-specific-opencl-configuration from 0 to 1 doesn't change the performance on my mac with amd gpu

I checked the relevant code and it just falls back to cpu for certain routines.

**Comment by jenshannoschwalm** [comment]
> @jenshannoschwalm : Given your last comment maybe we can just wait and not merge the quick&dirty fix. There is no urgency as breakage is to be expected on master. Something is urgent only if it could breaks edits. Let me know if it is fine with you.

Perfect. That was more meant like "if you need it **now** take it"

I have proper code already running here, pr follows later tonight or tomorrow ...

**Comment by MStraeten** [comment]
fix looks fine.
with #13385:
```
    22,4038 [dev_pixelpipe] took 0,002 secs (0,001 CPU) [preview] processed `Weißabgleich' on GPU, blended on GPU
    22,4110 [dev_pixelpipe] took 0,007 secs (0,005 CPU) [preview] processed `Spitzlicht-Rekonstruktion' on GPU, blended on GPU
```
--disable-opencl:
```
    10,1020 [dev_pixelpipe] took 0,025 secs (0,288 CPU) [full] processed `Raw-Schwarz-/Weißpunkt' on CPU, blended on CPU
    10,1310 [dev_pixelpipe] took 0,029 secs (0,072 CPU) [full] processed `Weißabgleich' on CPU, blended on CPU
```

**Comment by da-phil** [comment]
> --disable-opencl:
> 
> ```
>     10,1020 [dev_pixelpipe] took 0,025 secs (0,288 CPU) [full] processed `Raw-Schwarz-/Weißpunkt' on CPU, blended on CPU
>     10,1310 [dev_pixelpipe] took 0,029 secs (0,072 CPU) [full] processed `Weißabgleich' on CPU, blended on CPU
> ```

you're actually missing the interesting line ;)

the results with your 2nd PR for my Radeon RX 5700 XT on a 81 MP image are as follows:

with OpenCL:
``[dev_pixelpipe] took 0,001 secs (0,000 CPU) [full] processed `highlight reconstruction' on GPU, blended on GPU``
looks like it runs in <1ms, kudos to your runtime optimization skills  :partying_face:
 
w/o OpenCL:
``[dev_pixelpipe] took 0,000 secs (0,004 CPU) [full] processed `highlight reconstruction' on CPU, blended on CPU``


I however have a question, even though OpenCL is enabled, for most images the highlight reconstruction module is calculated on the CPU instead the GPU, I keep seeing the same perf line as for the ``--disable-opencl`` execution of DT.
Do you know how this is possible?

**Comment by jenshannoschwalm** [comment]
Could you share one of the images where there is an error for opencl?

I haven't observed such a problem btw.

You could try with -d pipe, it doesn't give perf values but might show why things go wrong.

**Comment by jenshannoschwalm** [comment]
And, could you share your dev specific settings?

**Comment by da-phil** [comment]
> Could you share one of the images where there is an error for opencl?
> 
> I haven't observed such a problem btw.
> 
> You could try with -d pipe, it doesn't give perf values but might show why things go wrong.

after pulling your changes from master I somehow can't reproduce the problem anymore..
but this is what I get with ``-d pipe``:
```

    68.1117 [modify roi OUT]             [full]         crop                 (   0/   0) 6048x4024 scale=1.0000 --> (   0/  17) 6048x3402 scale=1.0000 
    68.1130 [modify roi IN]              [full]         crop                 (1253/ 596) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.1130 [modify roi IN]              [full]         demosaic             (2402/1142) 2350x1951 scale=1.0000 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.1130 [modify roi IN]              [full]         highlights           (   0/   0) 6048x4024 scale=1.0000 --> (2402/1142) 2350x1951 scale=1.0000 
    68.1131 [pixelpipe_cache_get]        [full]         temperature           HIT important line  4, age  -51, hash   4725064683959544521, basic  11166778672413872438
    68.1244 [pixelpipe_process_CL]       [full]         highlights           (   0/   0) 6048x4024 scale=1.0000 --> (2402/1142) 2350x1951 scale=1.0000 
    68.1472 [pixelpipe_process_CL]       [full]         demosaic             (2402/1142) 2350x1951 scale=1.0000 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.1477 [clip_and_zoom_roi_cl]       [full]         demosaic             (2402/1142) 2350x1951 scale=1.0000 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.1585 [pixelpipe_process_CL]       [full]         exposure             (1253/ 596) 1226x1018 scale=0.5216 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.1634 [pixelpipe_process_on_CPU]   [full]         toneequal            (1253/ 596) 1226x1018 scale=0.5216 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.1676 [pixelpipe_process_on_CPU]   [full]         toneequal            (1253/ 596) 1226x1018 scale=0.5216 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.2210 [pixelpipe_process_on_CPU]   [full]         toneequal            (1253/ 596) 1226x1018 scale=0.5216 --> (1253/ 596) 1226x1018 scale=0.5216 
    68.2313 [pixelpipe_process_CL]       [full]         crop                 (1253/ 596) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2324 [pixelpipe_process_CL]       [full]         colorin              (1253/ 587) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2356 [pixelpipe_process_CL]       [full]         channelmixerrgb      (1253/ 587) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2387 [pixelpipe_process_CL]       [full]         colorbalancergb      (1253/ 587) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2408 [pixelpipe_process_CL]       [full]         filmicrgb            (1253/ 587) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2459 [pixelpipe_process_on_CPU]   [full]         colorout             (1253/ 587) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2640 [pixelpipe_process_on_CPU]   [full]         gamma                (1253/ 587) 1226x1018 scale=0.5216 --> (1253/ 587) 1226x1018 scale=0.5216 
    68.2662 [cache report]               [full]                               used=502MB, limit=500MB, hitrate=0.01
    68.2684 [modify roi OUT]             [full]         crop                 (   0/   0) 6048x4024 scale=1.0000 --> (   0/  17) 6048x3402 scale=1.0000 
    68.2685 [modify roi IN]              [full]         crop                 (1933/1056) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.2685 [modify roi IN]              [full]         demosaic             (2838/1550) 1800x1494 scale=1.0000 --> (1933/1056) 1226x1018 scale=0.6811 
    68.2685 [modify roi IN]              [full]         highlights           (   0/   0) 6048x4024 scale=1.0000 --> (2838/1550) 1800x1494 scale=1.0000 
    68.2685 [pixelpipe_cache_get]        [full]         temperature           HIT important line  4, age  -51, hash   4725064683959544521, basic  11166778672413872438
    68.2787 [pixelpipe_process_CL]       [full]         highlights           (   0/   0) 6048x4024 scale=1.0000 --> (2838/1550) 1800x1494 scale=1.0000 
    68.3008 [pixelpipe_process_CL]       [full]         demosaic             (2838/1550) 1800x1494 scale=1.0000 --> (1933/1056) 1226x1018 scale=0.6811 
    68.3012 [clip_and_zoom_roi_cl]       [full]         demosaic             (2838/1550) 1800x1494 scale=1.0000 --> (1933/1056) 1226x1018 scale=0.6811 
    68.3073 [pixelpipe_process_CL]       [full]         exposure             (1933/1056) 1226x1018 scale=0.6811 --> (1933/1056) 1226x1018 scale=0.6811 
    68.3100 [pixelpipe_process_on_CPU]   [full]         toneequal            (1933/1056) 1226x1018 scale=0.6811 --> (1933/1056) 1226x1018 scale=0.6811 
    68.3138 [pixelpipe_process_on_CPU]   [full]         toneequal            (1933/1056) 1226x1018 scale=0.6811 --> (1933/1056) 1226x1018 scale=0.6811 
    68.3665 [pixelpipe_process_on_CPU]   [full]         toneequal            (1933/1056) 1226x1018 scale=0.6811 --> (1933/1056) 1226x1018 scale=0.6811 
    68.3760 [pixelpipe_process_CL]       [full]         crop                 (1933/1056) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.3770 [pixelpipe_process_CL]       [full]         colorin              (1933/1045) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.3802 [pixelpipe_process_CL]       [full]         channelmixerrgb      (1933/1045) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.3834 [pixelpipe_process_CL]       [full]         colorbalancergb      (1933/1045) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.3857 [pixelpipe_process_CL]       [full]         filmicrgb            (1933/1045) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.3909 [pixelpipe_process_on_CPU]   [full]         colorout             (1933/1045) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.4097 [pixelpipe_process_on_CPU]   [full]         gamma                (1933/1045) 1226x1018 scale=0.6811 --> (1933/1045) 1226x1018 scale=0.6811 
    68.4114 [cache report]               [full]                               used=514MB, limit=500MB, hitrate=0.02

```


> And, could you share your dev specific settings?

I guess you mean those, right?
```
cldevice_v0_gfx1010xnack=0 1000 0 16 16 0.021993
cldevice_v0_intelrgen9hdgraphicsneo=0 1000 0 16 16 0.105167
cldevice_v2_intelrgen9hdgraphicsneo=0 250 0 16 16 128 0 0.108199
cldevice_v3_gfx1010xnack=0 250 0 16 16 128 0 0 0.020838
cldevice_v3_gfx1010xnack_building=
cldevice_v3_intelrgen9hdgraphicsneo=0 250 0 16 16 128 0 0 0.126417
cldevice_v3_intelrgen9hdgraphicsneo_building=
cldevice_v4_gfx1010xnack=0 250 0 16 16 128 0 0 0.018979 0.000
cldevice_v4_gfx1010xnack_building=-cl-fast-relaxed-math
cldevice_v4_gfx1010xnack_id0=400
cldevice_v4_intelrgen9hdgraphicsneo=0 250 0 16 16 128 0 0 0.078633 0.000
cldevice_v4_intelrgen9hdgraphicsneo_building=-cl-fast-relaxed-math
cldevice_v4_intelrgen9hdgraphicsneo_id0=400
```

looks like an interesting mix between the settings of my Radeon RX 5700 XT in my PC and the Intel GPU in my laptop :smile: 
I share the same DT settings and database between all my devices over my fileserver.
Shouldn't each openCL device have their own section, i.e. cldevice_v0, cldevice_v1, etc?
At least cldevice_v3 and cldevice_v4 seem to have AMD and Intel specific settings mixed, or is my interpretation wrong?

**Comment by jenshannoschwalm** [comment]
1. the new opposed code works on your cl device, good
2. your log looks fully ok (as expected) to me
3. from your config file only the `cldevice_v4_xxx` settings are still relevant, the others are residuals from dt 3.8 & 4.0 (not used any more) relevant are just these

```
cldevice_v4_gfx1010xnack=0 250 0 16 16 128 0 0 0.018979 0.000
cldevice_v4_gfx1010xnack_building=-cl-fast-relaxed-math
cldevice_v4_gfx1010xnack_id0=400
cldevice_v4_intelrgen9hdgraphicsneo=0 250 0 16 16 128 0 0 0.078633 0.000
cldevice_v4_intelrgen9hdgraphicsneo_building=-cl-fast-relaxed-math
cldevice_v4_intelrgen9hdgraphicsneo_id0=400
```
so a triplet for every device.
4. BTW On latest fedora the os and firefox use more graphics memory than before so if you are using "tune memory" you might see a decreased performance due to fallbacks :-)

**Comment by da-phil** [comment]
thanks for clarifying :+1:
