### ISSUE TITLE
Building darktable for portability

### ISSUE THREAD

**Issue by xMinerv** [darktable-org/darktable#13363]
Hello. I am attempting to build darktable 4.3.0 on a VM, then porting it to another computer also within the debian family of OS's. I'm not familiar with the process of building software to be used on other machines. The steps i have used to build are as follows:
cd darktable  
git submodule update --init  
mkdir build  
cd build  
cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable -DCMAKE_BUILD_TYPE=RelWithDebInfo ..  
make  
make install

The build works well, and runs fine on my build machine, but when i copy the folder defined in the prefix flag over to my destination computer and run, it immediately throws an 'illegal instruction' error. When i run darktable through gdb, i get:

Thread 1 "darktable" received signal SIGILL, Illegal instruction. 
0x00007ffff78dc9b2 in _create_lcms_profile (desc=desc@entry=0x7ffff7c2de8c "sRGB", dmdd=dmdd@entry=0x7ffff7c2de8c "sRGB", whitepoint=whitepoint@entry=0x7ffff7c2f050 <D65xyY>, primaries=primaries@entry=0x7ffff7c2efe0 <sRGB_Primaries>, trc=trc@entry=0x55555570cb00, v2=v2@entry=1) at /workdir/Darktable/darktable/src/common/colorspaces.c:303 
303	/workdir/Darktable/darktable/src/common/colorspaces.c: No such file or directory. 

It looks like some files from the source build are needed to be included, is there a way i can build this so everything can be packaged within a single folder?

How can i port this to another computer successfully? Thanks!

**Comment by parafin** [comment]
You need to add -DBINARY_PACKAGE_BUILD=ON option to cmake command.

**Comment by xMinerv** [comment]
@parafin Thank you! that was the fix, i really appreciate it!

**Comment by kmilos** [comment]
Please close your issue then @xMinerv
