### ISSUE TITLE
Long press to preview duplicate in duplicate manager not always working

### ISSUE THREAD

**Issue by europlatus** [darktable-org/darktable#13364]
**Describe the bug/issue**
When a duplicate is created via the duplicate manager, you can long press on the inactive duplicate to see a preview of that image overlaid on top of the active image. However, it is not always working. A long press on the inactive duplicate sometimes does nothing. To restore the functionality, double clicking on the inactive image to make it active should reactivate the preview function.

**To Reproduce**
1. With an image open in the darkroom, create a duplicate via the duplicate manager.
2. The duplicate image should now be active. Do an obvious edit to the new duplicate, such as increase exposure by a couple of stops.
3. Long press the inactive original image in the duplicate manager.
4. See if a preview of the inactive image is displayed. This does not work for me.
5. Double click inactive image.
6. Long press the other duplicate to see if a preview is displayed. This does work for me.

**Expected behavior**
A long press on the inactive image in the duplicate manager should display a preview of that image at any time. It is currently buggy and intermittently stops working. I can reproduce the issue but have not managed to work out if there's a consistent reason when the feature stops working.

**Screencast**
If no one else can reproduce, I can take a video.

**Which commit introduced the error**
Only noticed this since release 4.2.0. I never noticed the problem in earlier versions.

**Platform**
* darktable version : 4.2.0
* OS                : 
Edition	Windows 10 Home
Version	22H2
OS build	19045.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

* Memory            : 32 GB
* Graphics card     : AMD Radeon RX 6700 XT
* Graphics driver   : 22.20.29.07-221110a-385557E-AMD-Software-Adrenalin-Edition
* OpenCL installed  : Yes, 2.0
* OpenCL activated  : Yes

**Additional context**

 - Can you reproduce with another darktable version(s)? **not tried, but never noticed issue before**
 - Can you reproduce with a RAW or Jpeg or both? **RAW, long press preview doesn't seem to work at all with JPEG**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Do you use lua scripts? **No**

**Comment by pehar1** [comment]
Not able to reproduce. The first time "long clicking" the inactive version it takes about 2 seconds (on my system) until the inactive image is shown, after that the overlay appears almost immediately.

darktable 4.3.0-245-gbf38c1a9e
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by europlatus** [comment]
> Not able to reproduce. The first time "long clicking" the inactive version it takes about 2 seconds (on my system) until the inactive image is shown, after that the overlay appears almost immediately.

If you have the time, it would be great if you could keep trying after various edits and at random points in your workflow. I'm trying to find a 100% reproducible way of seeing this problem, but not sure I've found it yet. It seems to be intermittent,  but very frequent for me.
For the record, I have kept the long press down for up to 30 seconds to see if it's just a processing lag, but the preview still won't show. And my CPU/GPU are plenty fast enough. 
Of course, this could be an AMD Radeon issue...

**Comment by europlatus** [comment]
Video of the issue:

https://user-images.githubusercontent.com/89879133/213261631-7e265526-f53c-4bc9-bf0c-386c7e033bc3.mp4



Mouse clicks are audible if you have enough volume

**Comment by pehar1** [comment]
Still not reproduced.

> could be an AMD Radeon ... issue...

You can check if something changes disabling OpenCL in preferences.

> or Windows issue...

You could launch darktable from the command line with enabled debug output (https://darktable-org.github.io/dtdocs/en/special-topics/program-invocation/darktable/) and you can compare the outputs when it works and when it doesn't work. This can be a bit tedious....

**Comment by plougastel** [comment]
I can confirm the bug, which came with 4.2.0 and remains with 4.2.1, for tif pictures not raw ones for me, and not every time with the sames pictures (the duplicate manager was improved in 4.2.0).

Self compiled dt in Gnu/linux, without openCL, Intel video.

**Comment by europlatus** [comment]
I have been using darktable for a couple of days with openCL off and the bug still happens randomly, so likely not an openCL issue.

**Comment by Nilvus** [comment]
I can't reproduce on my side (using actual master).

**Comment by plougastel** [comment]
The same as @europlatus, intermittent problem, when this works it is rapidly, or not at all.
