### ISSUE TITLE
Darktable uses 95% CPU when exporting image with blur

### ISSUE THREAD

**Issue by AndyHit5687** [darktable-org/darktable#13367]
If I apply blur, (I did parametric mask), to an image it won't export. Says it is exporting 1 of 1 in bottom left of window but never finishes. No output file is created. I tried both JPG and PNG. Task Manager reports 96% CPU usage. Clicking the X in the exporting 1 of 1 message lower left reduces this to normal levels.
![IMG_0553](https://user-images.githubusercontent.com/77793667/213154280-6e5a01e0-4fc5-4dc9-8555-898b5462fbe5.jpg)

GIT wouldn't let me attach the XMP file so I cheated, The file below is a renamed copy.

![IMG_0553 jpg - Copy](https://user-images.githubusercontent.com/77793667/213154611-6f6fe93e-0658-43c1-a79a-3270ed52430f.PNG)

Darktable version 4.2.0

Device name	DESKTOP-7BC4VGB
Processor	Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz   2.71 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	902D48FE-EA8C-4D1E-AD8C-C9C82EF03EAD
Product ID	00330-50536-66923-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by ralfbrown** [comment]
How long did you wait?  It took about a minute and a half with 32 cores (44 min CPU time) and 10GB RAM to export a 12MP image with your sidecar.
You have a really large radius for the blur, and the larger the radius, the more time it takes, especially once tiling kicks in due to memory limits.

**Comment by AndyHit5687** [comment]
Ralf, only 3 mins, will give it another goSent from my iPhoneOn 18 Jan 2023, at 15:34, Ralf Brown ***@***.***> wrote:﻿
How long did you wait?  It took about a minute and a half with 32 cores (44 min CPU time) and 10GB RAM to export a 12MP image with your sidecar.
You have a really large radius for the blur, and the larger the radius, the more time it takes, especially once tiling kicks in due to memory limits.

**Comment by gi-man** [comment]
Please in the future use the Issue Template.

What OS? GPU? OpenCL?

**Comment by AndyHit5687** [comment]
Thanks Ralf, I left it running and it did finally complete. So sorry to report a false defect, I just didn't realise how long a blur export could take.
