### ISSUE TITLE
Building from source on Ubuntu 22.04 throws warnings

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#13365]
**Did you buy darktable from an application store ?**
no, building from source

**Describe the bug/issue**
Today, building 4.3.0-245-gbf38c1a9e from source, I got following warnings during build process :

```
CMake Warning at src/CMakeLists.txt:352 (find_package):
  Could not find a configuration file for package "OpenEXR" that is                              
  compatible with requested version "3.0".                                                       
                                                                                                 
  The following configuration files were considered but not accepted:                            
                                                                                                 
    /usr/lib/x86_64-linux-gnu/cmake/OpenEXR/OpenEXRConfig.cmake, version: 2.5.7                  
    /lib/x86_64-linux-gnu/cmake/OpenEXR/OpenEXRConfig.cmake, version: 2.5.7
```
and
```
CMake Warning at src/libs/CMakeLists.txt:95 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has                        
  asked CMake to find a package configuration file provided by "SDL2", but                       
  CMake did not find one.                                                                        
                                                                                                 
  Could not find a package configuration file provided by "SDL2" with any of                     
  the following names:                                                                           
                                                                                                 
    SDL2Config.cmake                                                                             
    sdl2-config.cmake                                                                            
                                                                                                 
  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set                              
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"                        
  provides a separate development package or SDK, be sure it has been                            
  installed.
```
Additionally I get `4.3.0-245-gbf38c1a9e-dirty` as version (displayed in dt), nevertheless not a single file was modified after the "pull".

The build finishes correctly, so far, i have not noticed any problems with the binary.

**Expected behavior**
Should build without warnings, should not show the "dirty"-flag if the unmodified code from git is used for build.

**Which commit introduced the error**
Not shure, but I did not notice the warnings with `4.3.0-76-g4f1a26c30`

**Platform**
darktable 4.3.0+245-gbf38c1a9e-dirty
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by Nilvus** [comment]
An update on Cmake about SDL2 had been merged after your issue. Could you update to last master commit and try again?
If this is fixed, think about closing that issue.

**Comment by pehar1** [comment]
Fresh build, now on 4.3.0-254-g3ac133189
Both warnings are still present, also the "dirty"-flag in version string :
```
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ph/darktable/master/build
[  0%] Building da locale
[  0%] Building cs locale
[  0%] Updating version string (git checkout)
[  0%] Building zh_TW locale
[  1%] Building af locale
[  1%] Building ca locale
[  1%] Building el locale
[  1%] Building de locale
[  1%] Building es locale
[  1%] Building fr locale
[  1%] Building eo locale
[  1%] Building fi locale
Version string: 4.3.0+254~g3ac133189-dirty
...
```
I can provide the full log if needed.

**Comment by kmilos** [comment]
The OpenEXR related warning is normal, it first looks for 3.0 (in CONFIG mode), then falls back to whatever it finds (in MODULE mode) - see the "Found" message right below from the CI running on 22.04:

```
CMake Warning at src/CMakeLists.txt:352 (find_package):
  Could not find a configuration file for package "OpenEXR" that is
  compatible with requested version "3.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/OpenEXR/OpenEXRConfig.cmake, version: 2.5.7
    /lib/x86_64-linux-gnu/cmake/OpenEXR/OpenEXRConfig.cmake, version: 2.5.7



-- Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so;/usr/lib/x86_64-linux-gnu/libImath.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so;/usr/lib/x86_64-linux-gnu/libHalf.so
```

See also https://github.com/darktable-org/darktable/issues/11524 

Don't know what's up with SDL2.

Re "dirty" flag, search also discuss.pixls.us

**Comment by pehar1** [comment]
Thank you @kmilos, the binary works fine, so no big deal. I will try to get rid of the "dirty" flag by cloning completely new and cleaning all related directories. Actually I always do...
