### ISSUE TITLE
translation of color harmony types not displayed

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#13375]
after translating the color harmony stuff the harmony type translations aren't shown
![image](https://user-images.githubusercontent.com/39386816/213302290-264b3448-65bf-41fd-b4f6-8714a769c377.png)

**To Reproduce**
activate a translation with new color harmony translation
 
**Platform**

* darktable version : darktable 4.3.0+254~ga6a38eca6-dirty (contains not yet merged german translation #13374)
* OS                : OSx

**Comment by dterrahe** [comment]
https://github.com/darktable-org/darktable/blob/2baa3b096ef9e33066fbeee52eeba93ff05b5ad8/src/libs/histogram.c#L1204

needs `_( )` around both `"%s\nrotation: %d°"` and `hm.name`

looks like line 1203 gets overwritten (probably leftover temporary)?

**Comment by Mark-64** [comment]
I will have a look
