### ISSUE TITLE
LUA and national characters (ą,ę,ń)

### ISSUE THREAD

**Issue by DarekGH** [darktable-org/darktable#13379]
When photos has pure english filenames lua scripts works well.
But when filenames has national charaters it goes wrong during moving/copying and running external programs with filename as parameter.
Try to run ext_editor script when source file has national letters.
It stops when moving file from temp location to source location.
Next - passes wrong file name to external editor - insted of Gdańsk.tif it passes Gda┼äsk.tif
Look here https://stackoverflow.com/questions/54118507/lua-how-to-make-os-rename-os-remove-work-with-filenames-containing-unicode-ch
and here https://gist.github.com/Egor-Skriptunoff/2458547aa3b9210a8b5f686ac08ecbf0#file-utf8_filenames-lua

Darek

**Comment by Nilvus** [comment]
If issue is only related to lua, please report this on lua repository (and close that issue): https://github.com/darktable-org/lua-scripts
Thanks.
