### ISSUE TITLE
Homebrew build fails on MacOS Ventura

### ISSUE THREAD

**Issue by K3RL** [darktable-org/darktable#13376]
When trying to package Darktable via packaging/macosx/2_build_hb_darktable_default.sh, it fails with the following error:

> CMake Error at /opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (Required is at least version "4.5")
> Call Stack (most recent call first):
/opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600
(_FPHSA_FAILURE_MESSAGE)
/opt/homebrew/Cellar/cmake/3.25.1/share/cmake/Modules/FindOpenMP.cmake:580 (find_package_handle_standard_args) CMakeLists.txt:94 (find_package)

Naturally, I ran 1_install_hb_dependencies.sh prior, reinstalled libomp via brew manually and ran
>  export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
>  export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"

but this did not change a thing.

Latest git clone and on MacOS Ventura 13.0.1, M1 Pro MBP.

**Expected behavior**

Successful build.

Thanks!

**Comment by shonjir** [comment]
Might be because libomp isn't linked.   You might try PR https://github.com/darktable-org/darktable/pull/13345 which tries to do a better job of installing brew dependencies.  PR https://github.com/darktable-org/darktable/pull/13344 fixes other issues in script 3 that result in broken builds.

**Comment by apfelkraut** [comment]
You need to run `brew link --force libomp` which is also part of the mentioned pull request.

**Comment by K3RL** [comment]
> You need to run `brew link --force libomp` which is also part of the mentioned pull request.

That made it build, thanks!

**Comment by cridemichel** [comment]
Hi,
I successfully built darktable with homebrew, but on launching the app I get a segfault with the following output:
```
(process:59086): GLib-GObject-CRITICAL **: 19:42:51.869: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(darktable:59086): GLib-GObject-WARNING **: 19:42:52.042: cannot register existing type 'GdkDisplayManager'

(darktable:59086): GLib-CRITICAL **: 19:42:52.042: g_once_init_leave: assertion 'result != 0' failed

(darktable:59086): GLib-GObject-CRITICAL **: 19:42:52.042: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
[1]    59086 segmentation fault  package/darktable.app/Contents/MacOS/darktable --configdir .config/darktable/
```
any guess?
best Cristiano

**Comment by zisoft** [comment]
@K3RL, @cridemichel : based on your comments I see that there are no more issues, so I close this.
