### ISSUE TITLE
Lower the ISO 12646 white border size

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#13386]
**Did you buy darktable from an application store ?**
Master

**Describe the bug/issue**
Turning on the ISO 12646 check now has a larger white border than 4.0. 

4.2
![image](https://user-images.githubusercontent.com/97920861/213547577-e3decb8b-f5f7-4189-ab0b-18e11c7c8f9b.png)

4.0 borders from the manual
![image](https://docs.darktable.org/usermanual/4.0/en/module-reference/utility-modules/darkroom/color-assessment/color-assessment-overview.png)

I tried to find any documentation around what the proper size should be. I cannot find any. This feature was introduced in https://github.com/darktable-org/darktable/issues/3686 and implemented in https://github.com/darktable-org/darktable/pull/3736.

There is a reference in color.org to 9mm here: https://www.color.org/resources/r8-13/CCA_test.xalter

Therefore, I dont know what the right answer is, but in my _opinion_ I think the white is too large in 4.2

**To Reproduce**
Turn on ISO12646
Look the the size of the white border

**Which commit introduced the change**
https://github.com/darktable-org/darktable/pull/12462

**Platform**
Current master

**Comment by elstoc** [comment]
I agree, it seems too large for me too. If the idea is to provide a broadly mid-grey editing environment, the color assessment mode makes the screen too bright for me.

**Comment by jenshannoschwalm** [comment]
I looked up docs and indeed there is no definite answer.

Recommendations for viewing multiple images are around 1cm white, also for printed output .

The size chosen here for evaluating a single image (1 inch) was recommended by some sites evaluating architectural and landscape  heritage on 27inch monitors. (Unfortunately can't find the reference ATM)

**Comment by Nilvus** [comment]
1 inch is about 2,54cm and some (as color site referenced here by @gi-man ; and was by Aurélien when he implement that feature) talks about 9mm with at least 18mm grey background outside. It's the least needed so, especially on some resolutions when with high frame size, grey around could be slightly reduced (even if that size could be increased in darktable preferences ; I talk here of course with default settings).

So probably better settings could be between previous settings with small size and actual seems to be too big.

I would suggest so at least twice white size for grey around (on color recommandations, it's 18mm of grey for 9mm white size) then white size around 1cm regarding comments here.

**Comment by gi-man** [comment]
I did a PR to reduce the size of the white border. The PR has images from my screen, but I'm interested on folks with smaller screen (eg. 14in laptop). If possible, build, test and provide feedback.

**Comment by Nilvus** [comment]
@gi-man: since this had been improved, this could be closed I think

**Comment by gi-man** [comment]
Yes. I'm closing it. I will update the manual too.
