### ISSUE TITLE
Different results in the final image CPU vs GPU

### ISSUE THREAD

**Issue by mfg92** [darktable-org/darktable#13394]
**Describe the bug/issue**

I get slightly different results in the final image when I use CPU-only or when I use OpenCl.

**To Reproduce**

I have followed the instructions from here https://math.dartmouth.edu/~sarunas/darktable_bench.html

1. Download the image +sidecar file from [here](https://math.dartmouth.edu/~sarunas/bench_raw/arecibo/)
2. Execute: `darktable-cli arecibo.orf arecibo.orf.xmp cpu.jpg --core --disable-opencl -d perf`
3. Execute: ` darktable-cli arecibo.orf arecibo.orf.xmp gpu.jpg --core -d perf -d opencl`
4. Compare the images: cpu.jpg vs gpu.jpg

**Expected behavior**
Same result whether the image pipeline is executed on the CPU or the GPU.

**Screenshots**
The difference is visualized here:
![diff](https://user-images.githubusercontent.com/11365250/213821131-04d6239a-877a-450a-b734-a19b65edbaa9.jpg)
(In the diff, the differences don't look that big, but when I compare the two images by switching quickly between them, the differences are easy to spot.)

**Platform**

* darktable version : e.g. 4.2.0
* OS                :  Win10
* Memory            :  32GB
* Graphics card     :  Radeon RX 480
* Graphics driver   :  22.11.2
* OpenCL installed  :  yes 
* OpenCL activated  :  yes and no

**Additional context**
Perhaps related to #8382

**Comment by TurboGit** [comment]
Can you please check which module is doing that. TIA.

**Comment by mfg92** [comment]
If I deactivate _contrast equalizer_ the GPU and CPU image look the same. So _contrast equalizer_ seems to have the issue.
