### ISSUE TITLE
Ask user where to store images on the first run

### ISSUE THREAD

**Issue by prokoudine** [darktable-org/darktable#13390]
Currently, darktable automatically assumes that the user is fine with `$(PICTURES_FOLDER)/Darktable` as the folder where all new photoshots are stored. That gives you three main scenarios:

- the user is fine with whatever is suggested to them
- the user starts looking where to change that immediately after running it for the first time
- the user doesn't think about it, imports a photoshoot, then discovers it's in a folder that needs to be elsewhere, starts moving files around, changing settings etc.

Instead, the first time darktable runs, it could ask the user where to create the catalog. The first group of users would simply agree with what is suggested to them, the second group would save a little time searching for that setting, and the third group would save even more time.

**Comment by MStraeten** [comment]
Copy & Import dialog contains fields to specify target directory to store imported images. Default values are just suggestions that can be changed also via preferences dialog

**Comment by gi-man** [comment]
I could see the point of adding the fields to the Add to Library path. 

Thinking out loud, maybe have one interface (Import) and then within Import have the option (eg checkbox) to Copy. This might avoid confusion for new users.

**Comment by prokoudine** [comment]
> Copy & Import dialog contains fields to specify target directory to store imported images. Default values are just suggestions that can be changed also via preferences dialog

I'm sorry, I do not understand what your argument is.

**Comment by prokoudine** [comment]
> what’s the difference between an annoying ask at first start and an editable entry field on first copy and import?

The difference between a question you only need to answer once and having to edit the location every time you import something _until_ you got to Preferences and find the relevant setting? Is that your question? Please clarify.

**Comment by MStraeten** [comment]
when i change a root directory for copy&import while using the import dialog it's the first time i need to think about it. If i change it this decision is persisted used until i explicitly change it again. Thats already implemented. 
If i think i have to set such directory before doing a copy & import, i can do it en passant while doing even more relevant initial settings in the preferences. Also already implemented. 
So what's really missing?

**Comment by parafin** [comment]
Not everyone is using copy&import, some people (like me) only ever use just plain import. So it doesn’t make sense to ask that question everybody. Maybe ask it the first time copy&import functionality is used, not on first dt start? It is quite frustrating when application doesn’t let you to get to working state before going through some hoops and loops…

**Comment by ptilopteri** [comment]
agreed.  I frequently import from command-line and use --library :memory: untill I finish
editing, then import into db

**Comment by jenshannoschwalm** [comment]
> Maybe ask it the first time copy&import functionality is used, not on first dt start?

I think maybe we should not set the conf to some valid path but to "" for a fresh rc file. So the test for copy&import would not work (a few tests there have to be modified) until something valid has been set in preferences? So a) user action only requested in copy&import and b) only until properly set

**Comment by MStraeten** [comment]
i don't think setting the default to an empty path is a good solution since the current default is a quite common solution - especially for those who doesn't care a lot where to save their images. Those who care will usually check the target before importing beacuse they don't think, the software has a clue on their demands ;)

**Comment by jenshannoschwalm** [comment]
> i don't think setting the default to an empty path is a good solution since the current default is a quite common solution - especially for those who doesn't care a lot where to save their images.

Well, whenever i have a new document in my text editor to be saved the app will require my "prompt" about the "where". So not an uncommon situation. Remember: this will be done just once as a confirmation "yes - do it there"
