### ISSUE TITLE
Haze Removal Module broken???

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#13395]
Running 4.3+ 104 on Windows... - values blur the image but pos  values on the slider do nothing.

I saw this reported on FB when I was at work...my machine there had 4.3 + 65 and dehaze seemed to work so something in between may have caused the issue...

If others confirm I can provide more information.

**Comment by Nilvus** [comment]
Could you please provide complete version (number after 65 or 104 here. I doubt someone will take time to count to find which commit those versions are.
Complete number like 4.3.0+261~g1c795a75b would be better. Thus, as you can see, your versions are quite outdated, we are now near 300 commits on master. So good to update and test again if you still have issue on last master.

**Comment by todd-prior** [comment]
It seemed to correct on a restart. I had left DT open for some time. Not sure what the issue was. It was reported also and confirmed by a few users on the FB forum but I think they were likely using 4.2. Im due to update so I will monitor after that for any sign of this issue resurfacing... Thanks for your comment and sorry I was slow to update things...had to attend a function...
