### ISSUE TITLE
Rotate and Perspective doesn't update display

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#13404]
Rotating an image by right clicking and drawing, or adjusting the rotation slider, isn't applied until the module is minimized.  When the module is opened again the rotation has been applied and the rectangle is displayed to adjust the portion of the image retained.

**To Reproduce**

1. Open an image in darkroom view
2. Open the rotate and perspective module
3. Right click on the image and draw a slanted line across the image.  Release the right mouse button.
4. Notice the image doesn't update.
5. Minimize the module.  Notice the image updates
6. Reopen the module.  Notice the rectangle is displayed and adjustable to select the portion of the image.

**Expected behavior**
Image should update as rotation parameters are adjusted.

**Which commit introduced the error**
I looked at the recent changes to ashift.c and @dterrahe made a recent change to not recalculate crop when the module is focused.  I wonder if that somehow interfered with the rotation updating.  I'll try and bisect later today.

**Platform**

* darktable version : 4.3.0+277~g5890e107f
* OS                : Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 32G
* Graphics card     : Nividia 3070
* Graphics driver   : Nvidia 525
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : yes
* Desktop           : gnome
* GTK+              : 3.24.5
* gcc               : 11
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)?  4.2 works correctly
 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

**Comment by wpferguson** [comment]
Commit 062f087b5258db3c70792356dafd173adc923262 introduced the change

**Comment by Nilvus** [comment]
I confirm: annoying change. @dterrahe: your PR was needed for some parts but previous behavior was better for that module. Quite harder to find correct rotate angle on an image when needed to minimize module then go back to fine-tune rotation, etc.

**Comment by AlicVB** [comment]
> @dterrahe: your PR was needed for some parts but previous behavior was better for that module

In fact that happens when the buffer is not ready... PR #13406 should fix it (plus an issue with module reset)

**Comment by wpferguson** [comment]
I'll test #13406 when I get home in a couple of hours.

**Comment by wpferguson** [comment]
Thanks everyone
