### ISSUE TITLE
Link between format images need to be improved (and be sure user understand if and when preset is auto-applied)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13410]
**Describe the bug/issue**

I have a preset to auto-apply color calibration (actually with as done with camera on illuminant) that is no more applied.
@TurboGit: I didn't do any bisect but given recent changes and this is an issue that appears on current master (so after 4.2 and I'm quite sure that appears this month ; I just do not import images since nearly a month), I'm quite sure this issue is related to your workflow rewrite.

I precise so that I use my own presets and no workflow activated. So, on process tab in preferences, auto-apply workflow by default is set to none.

**To Reproduce**
1. Have a preset with auto-applied checkbox activated to allow preset to be applied on any new image (when imported or when selected original then compress image)
2. Import new images (or compress when original is selected)
3. All my presets are correctly applied, except color calibration module that remains deactivated

Note that I removed also preset and recreate it. Issue still remains.

**Expected behavior**

Have color calibration preset correctly applied as before.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : last master

**Comment by Nilvus** [comment]
I've made more tests and found something strange and not obvious. That is the only preset with only raw checkbox selected on modify preset dialog window. If I select options below (HDR, color, monochrome), preset is applied. That make sense but that give me 2 questions:

- why this was working before and no more know (I didn't modify that presets since weeks (maybe months)
- I understand know that HDR, color, monochrome apply to RAW and not RAW below (or maybe only RAW?). That make sense but so that part is absolutely not obvious. This would need to be improved, maybe by indented and linked those options to RAW (and not RAW maybe) to understand they are linked. And unchecking parent should uncheck children like unchecking children of course do not uncheck parent. Classic behavior.

**Comment by TurboGit** [comment]
> * why this was working before and no more now (I didn't modify that presets since weeks (maybe months)?

Cannot answer this part.

Not clear indeed, what about having the following display

```
pas RAW             HDR
            and     monochrome
RAW                 couleur
```

And if possible ensure that the OK button is activated only when at least one item is selected in second column.

Thoughts?

**Comment by Nilvus** [comment]
I so understand (as I suspected) that HDR, monochrome and color) applies on both RAW and not RAW. So your proposal is good to me. I don't have other proposal to do better. And of course, with your proposal, if both parents are checked or unchecked, children should follow (but remember last setting, like reject/rating behavior).
