### ISSUE TITLE
Initial rating when importing only works for some camera brands/types.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#13412]
**Describe the bug/issue**

After setting an initial rating to be applied during import only some images are actually  rated.

This came up on Pixls: [This topic](https://discuss.pixls.us/t/imported-photos-automatically-have-2-star-rating-how-to-change/34877)

**To Reproduce**
1. Get a selection of RAWs from different cameras and types
2. Make sure your start with a clean database and no xmps are already present for the set you test with
3. Set the initial rating as described [here](https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/import/)
4. Import the selection.
5. As can be observed some are now rated and some are not.

**Expected behavior**

All imported images to be rated when importing

**Screenshots**
This is what I see after setting the initial rating to 3 stars importing these 23 RAWs:

![rating hit_miss](https://user-images.githubusercontent.com/56407344/213930470-f8cb0c9b-2fd5-4699-8723-d89676ed6134.png)

Did the test in 2 ways: All at once and in a few batches. Also did this with 3 diffrenet dt versions. Result is the same.

Note: look at the first 2, same camera (brand/type) the cr2 is ignored and the dng is rated. Seems to be an issue with the interpretation of the exif data.

**Which commit introduced the error**

I tested and this goes back a bit. Tested and confirmed on: 4.0.1, 4.2.0 and 4.3.0+275~g2d51f435b

**Platform**

Confirmed by 2 other people. Both Linux and Windows (see pixls topic I linked to above).

**Comment by Nilvus** [comment]
Maybe a duplicate of #13286. Do you know if RAW with no rating have rating inside RAW (that could be set directly on camera)?

And so, could you test if PR #13370 fix your issue?

**Comment by gi-man** [comment]
I can reproduce. Fedora 37 KDE, X11, 4.3.0~git277.5890e107

I used images from playraw and confirmed via exiftool that the cr2 does not have any rating information.

**Comment by jade-nl** [comment]
> Do you know if RAW with no rating have rating inside RAW

I just cleaned everything and had a look at the images without an auto added rating: They all have this in the exif data:

> xmp	
> Rating	0	

The ones that do get auto rated by darktable (after cleaning them) do not have any rating info. So, it looks like this might indeed be a duplicate.

@gi-man 
That image also has a rating:

![rating](https://user-images.githubusercontent.com/56407344/213933369-6ced9741-22b3-4b78-8808-0fa936371922.png)

@Nilvus 

Just merged and build the proposed fix (#13370) : Does not seem to work for me (with or without ticking the *ignore EXIF rating*).

**Comment by gi-man** [comment]
@jade-nl I'm using .cr2 from my canon camera. I know it doesnt have any rating and I checked with exiftool. It seems like the Initial Rating is ignored on the CR2 images.

**Comment by jade-nl** [comment]
@gi-man 

It is interesting that if XnView shows the RAW with the rating pre-set (as shown above) that RAW is ignored by darktable and if that line isn't present at all in XnView it is auto-rated by darktable.

Might be a nice puzzle for the developers to fix.

---

@Nilvus : Should I close this one as being a duplicate?

**Comment by Nilvus** [comment]
@jade-nl: seems remains a duplicate but if PR #13370 does not fix that, this need to remains opened. Could you share an affected RAW?

@zisoft: as you work on that part, what's your view about that issue (seems related to your PR but your PR seems to not fix it)?

**Comment by zisoft** [comment]
Please share a RAW file so I can have a look

**Comment by gi-man** [comment]
I think I see what's going on. The Rating is part of this group [XMP-xmp] and not part of EXIF group. My canon images do have that. And I also found a group called [Sony] with a Rating too.

I'm using: exiftool -G1 Rating *.* to see them now.

**Comment by jade-nl** [comment]
@Nilvus / @zisoft 

Here is an example: [canon.eos.1200d.01.cr2.zip](https://github.com/darktable-org/darktable/files/10475278/canon.eos.1200d.01.cr2.zip)

But any Z series Nikon will do (at least the ones I checked: Z6ii, Z7ii and Z9). All the Sony ILCE-6100 and ILCE-6400 also show this. And many more.

**Comment by andrewk8** [comment]
DT4.2 on Windows.  I think the issue for the a6400 goes back at least to 3.8.
I am seeing different rating-upon-import for 2 cameras.
Google Pixel 5: initial rating is applied
Sony a6400: initial rating is blank
No difference whether whether it's raw/DNG or JPEG.

@Nilvus, not a dupe of https://github.com/darktable-org/darktable/issues/13286. I have ignore EXIF rating FALSE.

![2023-01-22 09_16_23-darktable](https://user-images.githubusercontent.com/16465258/213937596-6730a522-ed3d-4c62-9789-373eba195f86.png)
[samples.zip](https://github.com/darktable-org/darktable/files/10475413/samples.zip)

**Comment by zisoft** [comment]
@jade-nl, @andrewk8: PR #13770 is to set the initial rating on import to the value provided in the import settings. I have tried this with all your provided samples and I get the rating correctly set.

So from my point of view  PR #13770 works as expected.

Please not that existing XMP files besides the image files have priority. If an XMP file is present, the rating is always read from there.

**Comment by jade-nl** [comment]
@zisoft  Thanks for checking!

This does mean, however, that the issue that @andrewk8 raised on pixels and which I tested and filed here is not the same as the one you fixed, although they might still have some overlap.

It is not possible to auto set a default rating for RAWs that have the rating set as part of the XMP-xmp group (see @gi-man previous reply) when cleanly importing RAWs. Cleanly as in: No copy already present in the database and no corresponding dt xmp present.

Ticking the *ignore EXIF rating* (which should make sure the rating set by the camera is ignored/overridden) does not change this behaviour.

**Comment by gi-man** [comment]
I tried to read thru the code to understand in more detail what's happening. 

In rows 521, reads for `Xmp.xmp.rating` (the value that some raw files have as 0 and others dont have anything). If it finds, then it writes the number to `dt_image_set_xmp_rating`, IF it doesnt, then it sets `dt_image_set_xmp_rating` to `-2`

Then in row 1298, if not set to ignore the Exif, it will try to read `Exif.Image.Rating` If found then it will write the value to `dt_image_set_xmp_rating`, if it doesnt (like the raws above), it will set `dt_image_set_xmp_rating` to `-2`

There was a recent change to 1298 via this PR https://github.com/darktable-org/darktable/pull/12744 to how the Ignore Exif is handled.  But, I've reached the depth of my understanding and I'm falling asleep. I still need to see how the Initial Rating is used and when.

**Comment by andrewk8** [comment]
@jade-nl, DSC08903.arw is mine.  Using exiftool, I do see that rating 0. This appears to be something Sony set in their a6400 firmware; AFAIK, I didn't add/change it in the camera. A conflict between Sony defaults, Google defaults and DT defaults had me confused. I have not tried setting ignore exif rating and initial rating 0 in DT, but maybe that will work for me.

Others have uncovered other inconsistencies, I think.

**Comment by zisoft** [comment]
Darktable uses exiv2 to read the metadata. By using exiv2 on the command line for the provided sample images I get:

    exiv2 -PEXI DSC08862.ARW | grep Rating
    Xmp.xmp.Rating                               XmpText     1  0

--> 0

    exiv2 -PEXI PXL_20230122_201314544.dng | grep Rating

--> no rating

    exiv2 -PEXI canon.eos.1200d.01.cr2 | grep Rating
    Xmp.xmp.Rating                               XmpText     1  0

--> 0

**Comment by zisoft** [comment]
When I import these 3 images into darktable with these settings:

<img width="308" alt="Bildschirm­foto 2023-01-23 um 17 20 27" src="https://user-images.githubusercontent.com/4083281/214092153-017b71ce-272b-4148-9379-8b3348a0ecab.png">

only the `PXL_20230122_201314544.dng` gets the rating of 1:

<img width="903" alt="Bildschirm­foto 2023-01-23 um 17 21 17" src="https://user-images.githubusercontent.com/4083281/214092380-461d49d4-df42-46f9-8a26-fd7856698f5b.png">

According to the exiv2 results above, this is correct as only this file has no rating.

**Comment by jade-nl** [comment]
@zisoft 

I just ran that command on all the RAWs I tested with (and a few more just to be sure) and this seems to be why this happens, or at least how it might be solved (I'm not a coder in any way). So you might have found the underlying issue.

All the RAWs that are correctly auto-rated show no rating when running the command you provided and all the RAWs that are incorrectly ignored show the  *Xmp.xmp.Rating                               XmpText     1  0* output.


Some camera types seem to set a default value of 0 as its rating. But they should be rated as set (*initial rating*) if the *ignore EXFI rating* is ticked. This is not the case.

Your example should rate all three as a one star (assuming you tick *ignore EXFI rating*).

**Comment by zisoft** [comment]
Next try with _ignore EXIF rating_ set:

<img width="309" alt="Bildschirm­foto 2023-01-23 um 17 23 23" src="https://user-images.githubusercontent.com/4083281/214092877-54680877-3d91-4572-a586-2e3c0231bda9.png">

All 3 images get the rating 3:

<img width="892" alt="Bildschirm­foto 2023-01-23 um 17 24 14" src="https://user-images.githubusercontent.com/4083281/214093103-810bc3d8-f21b-4915-8784-c44084d6fef0.png">

which is correct too because no xmp files exist at this time thus the rating from the import setting is applied.

**Comment by zisoft** [comment]
> Your example should rate all three as a one star (assuming you tick _ignore EXFI rating_).

This only works with PR #13770 which I have installed

**Comment by jade-nl** [comment]
OK, this seems to be fixed!

I decided to redo the merging of #13770, as half mentioned I had some issues yesterday.

It now works as expected with your code merged:

![Screenshot_2023-01-23_17-40-52](https://user-images.githubusercontent.com/56407344/214097327-f76faeb8-3c56-4c03-bf0c-e34411c8fde7.png)

Thanks for the time and effort you spend on this one!

---

I'll close this one once your PR gets merged.

**Comment by gi-man** [comment]
@zisoft The PR resolves the issue with raw values that the camera writes as zero being used as the rating instead of the initial rating. This means that in most cases we should default to Ignore EXIF/XMP rating so that the initial rating would then be applied. I fear this is not intuitive. All of this because of the zero values in Xmp.xmp.rating for some cameras.

Therefore, I suggest that we should treat Xmp.xmp.rating=0 as we do with null (set_xmp_rating=(img, -2)) and then let the initial rating apply the value (if set above 0). In all other scenarios (Xmp.xmp.rating>0) then we should follow the logic in your PR. 

Thoughts?

**Comment by TurboGit** [comment]
> Therefore, I suggest that we should treat Xmp.xmp.rating=0 as we do with null

But then users which such camera won't be able to set rating=0. Not sure it is better.

**Comment by gi-man** [comment]
> > Therefore, I suggest that we should treat Xmp.xmp.rating=0 as we do with null
> 
> But then users which such camera won't be able to set rating=0. Not sure it is better.

Like in rows 529-530, you set the `dt_image_set_xmp_rating=(img, -2)` also for case of  `Xmp.xmp.rating=0`, then the `Initial Rating` value you select is then applied to the image. They should be able get the end result of rating=0.

**Comment by zisoft** [comment]
The problem is, you cannot distinguish between a rating of 0 set by the camera or intentionally set by the user.

Imagine the following scenario:
I'm out in the fields to take some photos. While sitting in the train on my way back home I take my camera to make a first quick culling. I rate all images I want to process further with a 1. Images which are not so good I leave unrated, for those I will decide later on my computer.

Back home I import the images into darktable. Now the unrated images get the default rating of 1, ending up that all images are rated with a 1...

**Comment by andrewk8** [comment]
> The problem is, you cannot distinguish between a rating of 0 set by the camera or intentionally set by the user.
> 
> Imagine the following scenario: I'm out in the fields to take some photos. While sitting in the train on my way back home I take my camera to make a first quick culling. I rate all images I want to process further with a 1. Images which are not so good I leave unrated, for those I will decide later on my computer.
> 
> Back home I import the images into darktable. Now the unrated images get the default rating of 1, ending up that all images are rated with a 1...

For this scenario where you're conscientiously rating it in-camera, you'd want to un-check ignore exif ratings in DT before import so that it uses the ratings in-image.  This is a supported workflow.

**Comment by zisoft** [comment]
Yes, that's way it works now. But with the proposal of @gi-man above, the unrated images would get the initial rating from darktable as well:

> Therefore, I suggest that we should treat Xmp.xmp.rating=0 as we do with null (set_xmp_rating=(img, -2)) and then let the initial rating apply the value (if set above 0).

**Comment by gi-man** [comment]
> the unrated images would get the initial rating

The unrated images should always get the initial rating (xmp.xmp.rating not set by the camera) per the `else`in row 527 current code. In your PR, row 530 is based on the conditions of row 522. So it appears to me that nothing happens (no initial) to the images without xmp.xmp.rating values based on the Ignore Exif checkbox value. 

But for images rated as 0 (like default in some of the cameras), they were getting the 0 in the current code. This is not ideal since the user is not really setting the 0 (just a camera default).  With you PR will get the initial rating only if you select the Ignore EXIF. But if you select the Ignore, also the images rated in the camera as 1, will get the Initial Rating. Hence why I think we should treat the camera set 0 differently. 

I've been trying to type/investigate this more, but too many work meetings this week.

**Comment by zisoft** [comment]
> But for images rated as 0 (like default in some of the cameras), they were getting the 0 in the current code. This is not ideal since the user is not really setting the 0 (just a camera default). 

This is exactly what I tried to explain: It is impossible to distinguish between the camera set rating 0 / the user set rating 0. See my scenario above.

**Comment by zisoft** [comment]
> 1. If ignore exif rating is true use the DT Initial Rating.

yes

> 2. If ignore exif rating is false and the image contains a rating, then use the image rating.

yes

> 3. If ignore exif rating is false and the image does not contain a rating, then (use the DT Initial Rating setting or leave it blank/zero???)

the DT initial rating is set.

These 3 scenarios are exactly the result of PR [#13770](https://github.com/darktable-org/darktable/pull/13370)

And the problem here is that a rating of 0 which was set by the camera is also a valid rating.

**Comment by jade-nl** [comment]
PR #13770 was merged: Closing this one.
