### ISSUE TITLE
Color Calibration CCT picker selects wrong colour on M1 Mac

### ISSUE THREAD

**Issue by ZeroEcks** [darktable-org/darktable#13426]
**Did you buy darktable from an application store ?**

no

**Describe the bug/issue**

Selecting a mostly white surface leads to the color calibration selecting a very invalid colour (also dragging it sometimes leads to a crash as a note)

*Does not occur with empty database*

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Using an M1 Macbook Pro
2. Import the attached ORF file
3. Click the CCT picker in the Color Calibration module
4. Select the white wall
5. Image turns green (293.8 degrees, 77% chroma)

**Expected behavior**

Image turns vaguely the correct colours.

**Screenshots**
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1106524/214303705-83815f3c-2257-45b0-adb8-4452f07f3144.png">

**Which commit introduced the error**

I will try and bisect this later, but it was introduced in 4.2, it didn't have this issue in 4.1

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.2.0
* OS                : MacOS 12.4 (21F79)
* Memory            : 16GB
* Graphics card     : M1 Pro
* Graphics driver   : N/A
* OpenCL installed  : N/A
* OpenCL activated  : Yes
* Xorg              : N/A
* Desktop           : MacOS
* GTK+              : N/A
* gcc               : N/A
* cflags            : N/A
* CMAKE_BUILD_TYPE  : N/A

**Additional context**
Does not occur with fresh database

 - Can you reproduce with another darktable version(s)?
   - No
 - Can you reproduce with a RAW or Jpeg or both?
   - both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)?
   - yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
   - N/A
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")?
   - *no*
 - Do you use lua scripts?
   - no

**Comment by ZeroEcks** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1106524/214306265-f5144f0d-3072-468b-ad15-f87839d494a0.png">

example of it working when using a temporary database. i have also attached the raw here (temporarily... for my own sanity its CPL-Demo_0035... if anyone ever needs it and its not available please let me know)

https://drive.google.com/file/d/1ubu91Oc4w8VU8K1lPX-uqDw4qt6gv22I/view?usp=sharing

I will try and bisect... though I am not sure I can downgrade the database like that, I also assume it's a lot of commits and I have limited time (though I understand the developers may be unwilling to do that themselves, esp since they cannot reproduce it most likely)

**Comment by Nilvus** [comment]
Could you share your RAW? Could you also check what you have on spot color mapping. Be careful that if that part is not resetted, color picker so do a color mapping.
