### ISSUE TITLE
a preset that will auto initalize given the current picture

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13429]
It is has been reported again and again that one cannot create a preset for say lens correction module as the preset will contains all the data from the picture the preset has been created. So it cannot be applied to another picture without the same camera, lens.

An initial idea would be able to create a preset with a specific flag to not use the parameters but to compute them initially when applied. The semantic should be exactly as if the user has enabled the module.

**Comment by Nilvus** [comment]
I like the idea but I also see that way as quite tricky AND risky. I don't have any idea about that. We just need to be careful and take time on it.

**Comment by TurboGit** [comment]
@Nilvus : Finally not that difficult... See #13432.

**Comment by TurboGit** [comment]
Done.
