### ISSUE TITLE
Enable Color Calibration picker for quick access panel

### ISSUE THREAD

**Issue by Egocentrix** [darktable-org/darktable#13427]
For some modules (e.g. Exposure) adding a slider to the quick access panel also adds the associated color picker/eyedropper button. I would like to have the illuminant/CCT color picker there as well, but despite adding the illuminant temperature/hue/choma sliders to the QA panel, the color picker does not show up. Can this be added?

Or maybe this is already possible and I have missed a button, in which case please disregard this FR :)

**Comment by Nilvus** [comment]
Already possible, but not only that line and so not optimal way. On quick access panel, right-click on QA tab, then choose color calibration, then page line. If you already have a setting of color calibration, right-click on title then page. You will have all color calibration module. Not possible on what I check to add only color picker line (if added, would need to have not only that line as lines around are related).

**Comment by Egocentrix** [comment]
Yes, I figured out the 'page' option as well. But at that point you might as well add the full module to a favourites panel because all the controls are included in the 'page'. So yes it's a workaround, but I still think it could be a nice enhancement.
