### ISSUE TITLE
Ricoh Theta Z1

### ISSUE THREAD

**Issue by garpinc** [darktable-org/darktable#13434]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by Nilvus** [comment]
I don't see any raw for this camera on raw.pixls.us and you provide just no info. Please read templates wre provide and follow their instructions.
Without samples, nothing can be done, I so close.

**Comment by kmilos** [comment]
Furthermore, [the one sample we know about](https://discuss.pixls.us/t/raw-samples-wanted/5420/110) works just fine in dt 4.2:

![image](https://user-images.githubusercontent.com/4973094/214534961-75d54420-3bf4-46e9-aa23-0e83a8bb2da2.png)

If this is about something else, please submit a more detailed issue report.
