### ISSUE TITLE
seg fault a) without openCL, and b) with openCL

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#13430]
Self-compiled dt from git 4.3.0+302~g9b6faf9dd
Manjaro, Nvidia proprietary drivers.

My test script 
` /opt/darktable/bin/darktable-cli arecibo.orf arecibo.orf.xmp test.jpg --core --disable-opencl -d perf`
Now terminates at
```
3,1004 [dev_pixelpipe] took 0,067 secs (1,591 CPU) [export] processed `rotate and perspective' on CPU, blended on CPU
zsh: segmentation fault (core dumped)  /opt/darktable/bin/darktable-cli arecibo.orf arecibo.orf.xmp test.jpg --core

```

My test script 
`/opt/darktable/bin/darktable-cli arecibo.orf arecibo.orf.xmp test.jpg --core -d perf -d opencl`
Now terminates at 
```
2,5688 [dev_process_export] pixel pipeline processing took 1,588 secs (3,444 CPU)
munmap_chunk(): invalid pointer
zsh: IOT instruction (core dumped)  /opt/darktable/bin/darktable-cli arecibo.orf arecibo.orf.xmp test.jpg --core

```
These errors seem to have started yesterday.

**Comment by gi-man** [comment]
Likely related to https://github.com/darktable-org/darktable/issues/13421

Is the xmp doing a rescale?

**Comment by ralfbrown** [comment]
Both rotation and perspective correction are likely to result in an output larger than the input if the module is told not to crop the result.

**Comment by ClaesGitHub** [comment]
@gi-man it performs 
automatic cropping = largest area off

**Comment by dtorop** [comment]
@ClaesGitHub: Now that #13422 is merged, can you test with git master and see whether the segfault is fixed?

**Comment by dtorop** [comment]
Good news!
