### ISSUE TITLE
Unable to load compressed RAFs (Fujifilm X-H2) 

### ISSUE THREAD

**Issue by HerrWaffel** [darktable-org/darktable#13447]
**Describe the bug/issue**
When trying to load a compressed RAF photo in darkroom, it gives me the following warning:
'failed to read camera white balance information from (filename)'.  
After the warning, it changes to the lightroom window as normal.

This doesn't happen for the other raw recording modes. (uncompressed and lossless compressed)
According to the 4.2.0 release notes, Fujifilm X-H2 compressed should have base support.

**Platform**
* darktable version : 4.2.0
* OS                : Win10 21H2
* Memory            :  32 GB
* Graphics card     :  NVIDIA Geforce RTX 3070
* Graphics driver   : 528.24

**Comment by kmilos** [comment]
It is clearly stated in the dt 4.2 release notes that Fujifilm lossy compressed mode is currently not supported in a dedicated section.

Please close this issue as duplicate @Nilvus 

Fee free to search and keep an eye on existing Fujifilm issues about this mode, like e.g. https://github.com/darktable-org/rawspeed/issues/232

**Comment by TurboGit** [comment]
As I'm passing by... I'm closing.
