### ISSUE TITLE
Setting White balance question.

### ISSUE THREAD

**Issue by Jardiceeek** [darktable-org/darktable#13442]
I dont have bug report but please someone help:
I work on scene referred workflow and it automatically turns color calibration module and make colors look better, but if i want to adjust white balance in wb module i cant. Sure, i can turn color calibration to none but then colors arent that good like they were with cat 16 mode. Any help? Thanx

**Comment by Nilvus** [comment]
Sorry but this place is not help support but for issues or feature requests about how to improve/fix darktable code. For what you ask, you have pixls.us forum. But regarding your question, before posting, I suggest you to read manual. Directly on darktable, click on ? icon then modules you cite here and will have you explain.
