### ISSUE TITLE
"An unhandled exception occurred" when opening a specific image

### ISSUE THREAD

**Issue by jackyyyyy123** [darktable-org/darktable#13446]
this is darktable 4.0.1 reporting an exception:

-------------------

Error occurred on Thursday, January 26, 2023 at 13:51:17.

darktable.exe caused an Access Violation at location 00007FF90CFA5102 in module libdarktable.dll Reading from location 000002BD650F7004.

AddrPC           Params
00007FF90CFA5102 0000000000000000 00007FF92B752D18 0000000000000000  libdarktable.dll!dt_interpolation_resample_1c_plain._omp_fn.1+0x232  [C:/msys64/home/bill/src/darktable-4.0.1/src/common/interpolation.c @ 2122]
00007FF92948FCB8 000002BD4E0E0C98 0000000000000000 0000000000000000  libgomp-1.dll!omp_fulfill_event+0x728
00007FF92B754B4B 000002BD4E0E0C60 0000000000000000 0000000000000000  libwinpthread-1.dll!pthread_create_wrapper+0x9b
00007FF94F401BB2 0000000000000000 0000000000000000 0000000000000000  ucrtbase.dll!_configthreadlocale+0x92
00007FF94FBD7614 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk+0x14
00007FF9517E26A1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart+0x21

00007FF707750000-00007FF70776F000 darktable.exe	4.0.1.0
00007FF951790000-00007FF951988000 ntdll.dll   	10.0.19041.2130
00007FF913300000-00007FF913317000 aswhook.dll 	22.12.7758.0
00007FF94FBC0000-00007FF94FC7F000 KERNEL32.DLL	10.0.19041.2364
00007FF94EED0000-00007FF94F1A2000 KERNELBASE.dll	10.0.19041.2364
00007FF94F3E0000-00007FF94F4E0000 ucrtbase.dll	10.0.19041.789
00007FF928AA0000-00007FF928BEE000 libglib-2.0-0.dll	2.72.3.0
00007FF9331D0000-00007FF9331F5000 libintl-8.dll	0.21.0.0
00007FF950DA0000-00007FF950E4E000 ADVAPI32.dll	10.0.19041.2130
00007FF90CEF0000-00007FF90D526000 libdarktable.dll
00007FF950100000-00007FF95012B000 GDI32.dll   	10.0.19041.2130
00007FF9501A0000-00007FF95023E000 msvcrt.dll  	7.0.19041.546
00007FF928980000-00007FF928A98000 libiconv-2.dll	1.17.0.0
00007FF94F310000-00007FF94F332000 win32u.dll  	10.0.19041.2486
00007FF9515A0000-00007FF95163C000 sechost.dll 	10.0.19041.1865
00007FF94F550000-00007FF94F65F000 gdi32full.dll	10.0.19041.2364
00007FF94F820000-00007FF94F945000 RPCRT4.dll  	10.0.19041.2486
00007FF94F340000-00007FF94F3DD000 msvcp_win.dll	10.0.19041.789
00007FF92B610000-00007FF92B63C000 libavif.dll
00007FF94FC80000-00007FF94FDAA000 ole32.dll   	10.0.19041.1202
00007FF923DF0000-00007FF923F0C000 libcairo-2.dll
00007FF94FA10000-00007FF94FBB1000 USER32.dll  	10.0.19041.2486
00007FF950870000-00007FF950BC5000 combase.dll 	10.0.19041.2311
00007FF929380000-00007FF929430000 libcurl-4.dll
00007FF950E50000-00007FF951594000 SHELL32.dll 	10.0.19041.2486
00007FF94EEA0000-00007FF94EEC7000 bcrypt.dll  	10.0.19041.2486
00007FF950130000-00007FF95019B000 WS2_32.dll  	10.0.19041.546
00007FF94F1B0000-00007FF94F306000 CRYPT32.dll 	10.0.19041.2486
00007FF929D90000-00007FF929DD3000 exchndl.dll 	0.9.5.0
00007FF94F950000-00007FF94F958000 PSAPI.DLL   	10.0.19041.546
00007FF950030000-00007FF950086000 WLDAP32.dll 	10.0.19041.2006
00007FF90CBC0000-00007FF90CEE6000 libexiv2.dll
00007FF92B1B0000-00007FF92B1D2000 libgcc_s_seh-1.dll
00007FF8B4F60000-00007FF8B584F000 libaom.dll
00007FF8D4440000-00007FF8D462A000 libdav1d.dll	6.6.0.0
00007FF8EFCB0000-00007FF8F004E000 rav1e.dll
00007FF8B45C0000-00007FF8B4F5C000 libSvtAv1Enc.dll
00007FF91C7C0000-00007FF91C8B3000 libyuv.dll
00007FF92B040000-00007FF92B070000 libgdk_pixbuf-2.0-0.dll	2.42.9.0
00007FF945D20000-00007FF945D2F000 libgmodule-2.0-0.dll	2.72.3.0
00007FF8EFB70000-00007FF8EFCAE000 libgdk-3-0.dll	3.24.34.0
00007FF8C8F30000-00007FF8C90D4000 libgio-2.0-0.dll	2.72.3.0
00007FF928920000-00007FF928977000 libgobject-2.0-0.dll	2.72.3.0
00007FF9500B0000-00007FF9500E2000 IMM32.dll   	10.0.19041.2193
00007FF929480000-00007FF9294C8000 libgomp-1.dll
00007FF950C30000-00007FF950C85000 SHLWAPI.dll 	10.0.19041.2075
00007FF9502D0000-00007FF950738000 SETUPAPI.dll	10.0.19041.2193
00007FF90DA80000-00007FF90DB0F000 libgphoto2-6.dll
00007FF94EE50000-00007FF94EE9E000 cfgmgr32.dll	10.0.19041.1620
00007FF932890000-00007FF9328A8000 libgphoto2_port-12.dll
00007FF8D4300000-00007FF8D4439000 libGraphicsMagick-3.dll
00007FF8D2F00000-00007FF8D2FA2000 libheif.dll
00007FF8B42F0000-00007FF8B45B2000 libicuin71.dll
00007FF8BE130000-00007FF8BE1E1000 libjpeg-8.dll
00007FF8BE1F0000-00007FF8BE3AC000 libicuuc71.dll
00007FF92AF60000-00007FF92AF8C000 libjson-glib-1.0-0.dll
00007FF9288D0000-00007FF92891B000 lua54.dll
00007FF920D90000-00007FF920DFC000 liblcms2-2.dll
00007FF903F40000-00007FF903FB6000 libopenjp2-7.dll
00007FF8B3FF0000-00007FF8B42E2000 libOpenEXR-3_1.dll
00007FF8B8B90000-00007FF8B92AA000 libgtk-3-0.dll	3.24.34.0
00007FF91C750000-00007FF91C7B2000 libpango-1.0-0.dll	1.50.9.0
00007FF92B780000-00007FF92B798000 libpangocairo-1.0-0.dll	1.50.9.0
00007FF91AD30000-00007FF91AD71000 libpng16-16.dll
00007FF90C990000-00007FF90C9D3000 libpugixml.dll	1.12.0.0
00007FF92B750000-00007FF92B767000 libwinpthread-1.dll	1.0.0.0
00007FF9037E0000-00007FF903839000 libsecret-1-0.dll
00007FF933020000-00007FF933027000 MSIMG32.dll 	10.0.19041.1466
00007FF8EFB10000-00007FF8EFB63000 libfontconfig-1.dll
00007FF951640000-00007FF95171A000 comdlg32.dll	10.0.19041.1806
00007FF8BCEF0000-00007FF8BD0E3000 libstdc++-6.dll
00007FF950C90000-00007FF950D3D000 shcore.dll  	10.0.19041.1865
00007FF8B36D0000-00007FF8B3FF0000 librsvg-2-2.dll
00007FF8BCCE0000-00007FF8BCD9E000 libfreetype-6.dll	2.12.1.0
00007FF8CB530000-00007FF8CB5DE000 libpixman-1-0.dll
00007FF92AF20000-00007FF92AF3F000 zlib1.dll
00007FF929900000-00007FF929916000 libbrotlidec.dll
00007FF8B7860000-00007FF8B78F5000 libsoup-2.4-1.dll
00007FF8EF6D0000-00007FF8EF75A000 libtiff-5.dll
00007FF8B76E0000-00007FF8B7851000 libsqlite3-0.dll
00007FF8B3580000-00007FF8B36CE000 libxml2-2.dll
00007FF8D7B10000-00007FF8D7B51000 libidn2-0.dll
00007FF8F0DB0000-00007FF8F0DFD000 libpcre-1.dll
00007FF920D10000-00007FF920D45000 libnghttp2-14.dll
00007FF8B32D0000-00007FF8B3577000 libcrypto-1_1-x64.dll	1.1.1.17
00007FF929360000-00007FF92937F000 libpsl-5.dll
00007FF8D3CF0000-00007FF8D3D38000 libssh2-1.dll
00007FF8B3240000-00007FF8B32CA000 libssl-1_1-x64.dll	1.1.1.17
00007FF8B3190000-00007FF8B3240000 mgwhelp.dll 	0.9.5.0
00007FF943F20000-00007FF943F2A000 VERSION.dll 	10.0.19041.546
00007FF8B30C0000-00007FF8B318C000 libzstd.dll
00007FF91C440000-00007FF91C478000 libexpat-1.dll
00007FF94ED10000-00007FF94ED3E000 USERENV.dll 	10.0.19041.572
00007FF930520000-00007FF9306C5000 gdiplus.dll 	10.0.19041.2251
00007FF94C680000-00007FF94C6AF000 dwmapi.dll  	10.0.19041.746
00007FF93E650000-00007FF93E660000 libffi-8.dll
00007FF94E2F0000-00007FF94E3BA000 DNSAPI.dll  	10.0.19041.1865
00007FF94D5A0000-00007FF94D5AD000 HID.DLL     	10.0.19041.546
00007FF94E2B0000-00007FF94E2EB000 IPHLPAPI.DLL	10.0.19041.1865
00007FF923DD0000-00007FF923DE8000 libltdl-7.dll
00007FF8D3C30000-00007FF8D3C7A000 libexif-12.dll
00007FF933450000-00007FF93345D000 libsystre-0.dll
00007FF91CF40000-00007FF91CF51000 libcairo-gobject-2.dll
00007FF932D90000-00007FF932DB7000 WINMM.dll   	10.0.19041.546
00007FF91CE10000-00007FF91CE3C000 libfribidi-0.dll
00007FF8B2F10000-00007FF8B30BF000 libepoxy-0.dll
00007FF91BF40000-00007FF91BF5D000 libpangowin32-1.0-0.dll	1.50.9.0
00007FF91BE20000-00007FF91BE3A000 libbz2-1.dll
00007FF8B2E50000-00007FF8B2F0B000 libde265-0.dll
00007FF8A9DE0000-00007FF8ABAF0000 libicudt71.dll
00007FF8ABAF0000-00007FF8ACE42000 libx265.dll 	3.4.0.31
00007FF8D2E90000-00007FF8D2EF1000 libIex-3_1.dll
00007FF8B8B30000-00007FF8B8B8A000 libImath-3_1.dll
00007FF91BE00000-00007FF91BE17000 libthai-0.dll
00007FF8B2D20000-00007FF8B2E4C000 libharfbuzz-0.dll
00007FF9331C0000-00007FF9331CE000 libIlmThread-3_1.dll
00007FF91AD10000-00007FF91AD2C000 libpangoft2-1.0-0.dll	1.50.9.0
00007FF8B2BD0000-00007FF8B2D13000 libgcrypt-20.dll	1.10.1.0
00007FF93E910000-00007FF93EBAA000 COMCTL32.dll	6.10.19041.1110
00007FF916BC0000-00007FF916BED000 libatk-1.0-0.dll	2.38.0.0
00007FF9306D0000-00007FF930768000 WINSPOOL.DRV	10.0.19041.2311
00007FF90DA50000-00007FF90DA7D000 libbrotlicommon.dll
00007FF90C970000-00007FF90C98B000 libdeflate.dll
00007FF910BE0000-00007FF910BF7000 libjbig-0.dll
00007FF8B2B00000-00007FF8B2BC1000 libLerc.dll
00007FF90C870000-00007FF90C89D000 liblzma-5.dll	5.2.6.0
00007FF8B2A80000-00007FF8B2AFA000 libwebp-7.dll
00007FF8B28A0000-00007FF8B2A7F000 libunistring-2.dll	1.0.0.0
00007FF94CC10000-00007FF94CDF4000 dbghelp.dll 	10.0.19041.867
00007FF9037C0000-00007FF9037DE000 libtre-5.dll
00007FF932730000-00007FF932740000 libdatrie-1.dll
00007FF8F1170000-00007FF8F119D000 libgraphite2.dll
00007FF918CF0000-00007FF918D09000 USP10.dll   	10.0.19041.546
00007FF8F10C0000-00007FF8F10FA000 libgpg-error-0.dll	1.45.0.0
00007FF934BD0000-00007FF934C05000 dbgcore.DLL 	10.0.19041.2311
00007FF94E800000-00007FF94E818000 CRYPTSP.dll 	10.0.19041.546
00007FF94DEC0000-00007FF94DEF4000 rsaenh.dll  	10.0.19041.1052
00007FF94E820000-00007FF94E82C000 CRYPTBASE.dll	10.0.19041.546
00007FF94F710000-00007FF94F792000 bcryptPrimitives.dll	10.0.19041.2486
00007FF950740000-00007FF950748000 NSI.dll     	10.0.19041.610
00007FF94D6F0000-00007FF94D702000 kernel.appcore.dll	10.0.19041.546
00007FF94CE00000-00007FF94D592000 windows.storage.dll	10.0.19041.2311
00007FF94E8B0000-00007FF94E8E0000 Wldp.dll    	10.0.19041.2311
00007FF94E610000-00007FF94E67A000 mswsock.dll 	10.0.19041.546
00007FF941BB0000-00007FF941CBC000 winhttp.dll 	10.0.19041.2193
00007FF912FE0000-00007FF912FE9000 KBDUS.DLL   	10.0.19041.546
00007FF929D80000-00007FF929D85000 KBDUK.DLL   	10.0.19041.1
00007FF94C4A0000-00007FF94C53E000 uxtheme.dll 	10.0.19041.2193
00007FF950750000-00007FF950865000 MSCTF.dll   	10.0.19041.2193
00007FF94FDB0000-00007FF94FE7D000 OLEAUT32.dll	10.0.19041.985
00007FF94EC00000-00007FF94EC2C000 DEVOBJ.dll  	10.0.19041.1620
00007FF94F4E0000-00007FF94F549000 WINTRUST.dll	10.0.19041.2486
00007FF94EA40000-00007FF94EA52000 MSASN1.dll  	10.0.19041.2251
00007FF94F960000-00007FF94FA0F000 clbcatq.dll 	2001.12.10941.16384
00007FF8B2730000-00007FF8B2898000 OpenCL.dll  	3.0.1.0
00007FF944F80000-00007FF945077000 AppXDeploymentClient.dll	10.0.19041.2075
00007FF94D710000-00007FF94D803000 dxgi.dll    	10.0.19041.2311
00007FF8A8BA0000-00007FF8A9DDA000 nvopencl64.dll	30.0.15.1278
00007FF93FFD0000-00007FF940001000 cryptnet.dll	10.0.19041.906
00007FF936320000-00007FF936468000 drvstore.dll	10.0.19041.1949
00007FF934170000-00007FF9348D8000 nvapi64.dll 	30.0.15.1278
00007FF8B2200000-00007FF8B272F000 igdrcl64.dll	23.20.100.8681
00007FF939320000-00007FF93955F000 igdgmm64.dll	27.20.100.8681
00007FF9397E0000-00007FF93981B000 dxcore.dll  	10.0.19041.546
00007FF8B2100000-00007FF8B21F1000 igdfcl64.dll	27.20.100.8681
00007FF936500000-00007FF939162000 igc64.dll   	27.20.100.8681
00007FF8A5F70000-00007FF8A8B96000 nvcompiler64.dll	30.0.15.1278
00007FF943F30000-00007FF944016000 Windows.ApplicationModel.dll	10.0.19041.1806
00007FF943A90000-00007FF943C90000 twinapi.appcore.dll	10.0.19041.1865
00007FF94A600000-00007FF94A6F6000 propsys.dll 	7.0.19041.1741
00007FF94ED90000-00007FF94EDAF000 profapi.dll 	10.0.19041.844
00007FF9127C0000-00007FF9127E8000 mssprxy.dll 	7.0.19041.2193
00007FF9104F0000-00007FF9104F9000 IconCodecService.dll	10.0.19041.1
00007FF93D920000-00007FF93DAD4000 WindowsCodecs.dll	10.0.19041.1706
00007FF925610000-00007FF925620000 libpixbufloader-png.dll
00007FF946360000-00007FF94640E000 mscms.dll   	10.0.19041.746
00007FF9462A0000-00007FF9462B1000 ColorAdapterClient.dll	10.0.19041.546
00007FF8B7690000-00007FF8B76D3000 icm32.dll   	10.0.19041.546
00007FF93E130000-00007FF93E229000 textinputframework.dll	10.0.19041.2075
00007FF94C010000-00007FF94C102000 CoreMessaging.dll	10.0.19041.2193
00007FF94BCB0000-00007FF94C00E000 CoreUIComponents.dll	10.0.19041.546
00007FF94DFE0000-00007FF94E013000 ntmarta.dll 	10.0.19041.546
00007FF94A900000-00007FF94AA54000 wintypes.dll	10.0.19041.2311
00007FF9434A0000-00007FF9436FF000 msxml6.dll  	6.30.19041.1023
00007FF8F03C0000-00007FF8F03E7000 libdarkroom.dll
00007FF903780000-00007FF903795000 libknight.dll
00007FF8F1040000-00007FF8F1053000 liblighttable.dll
00007FF8EF630000-00007FF8EF64A000 libmap.dll
00007FF8D7AF0000-00007FF8D7B10000 libosmgpsmap-1.0-1.dll
00007FF923DC0000-00007FF923DD0000 libslideshow.dll
00007FF8D7630000-00007FF8D7642000 libtethering.dll
00007FF8D7610000-00007FF8D7621000 libavif.dll
00007FF920ED0000-00007FF920EDE000 libcopy.dll
00007FF8D42E0000-00007FF8D42F7000 libexr.dll
00007FF920150000-00007FF920160000 libj2k.dll
00007FF91CFD0000-00007FF91CFE0000 libjpeg.dll
00007FF8D40B0000-00007FF8D40C1000 libpdf.dll
00007FF91CF30000-00007FF91CF3E000 libpfm.dll
00007FF91AC30000-00007FF91AC40000 libpng.dll
00007FF91A340000-00007FF91A34E000 libppm.dll
00007FF8D3E00000-00007FF8D3E11000 libtiff.dll
00007FF919240000-00007FF91924F000 libwebp.dll
00007FF8D3DE0000-00007FF8D3DF5000 libxcf.dll
00007FF90DA40000-00007FF90DA50000 libdisk.dll
00007FF90CBB0000-00007FF90CBBE000 libemail.dll
00007FF8D3CD0000-00007FF8D3CE1000 libgallery.dll
00007FF903C20000-00007FF903C30000 liblatex.dll
00007FF8CC240000-00007FF8CC252000 libpiwigo.dll
00007FF8C8F00000-00007FF8C8F2B000 libashift.dll
00007FF8BE110000-00007FF8BE12A000 libatrous.dll
00007FF8B20D0000-00007FF8B20F1000 libbasecurve.dll
00007FF8BE0F0000-00007FF8BE107000 libbasicadj.dll
00007FF8F03B0000-00007FF8F03C0000 libbilat.dll
00007FF8BCED0000-00007FF8BCEE2000 libbilateral.dll
00007FF8EFB00000-00007FF8EFB0F000 libbloom.dll
00007FF8BCCC0000-00007FF8BCCD3000 libblurs.dll
00007FF8B8B10000-00007FF8B8B22000 libborders.dll
00007FF8B20B0000-00007FF8B20C8000 libcacorrect.dll
00007FF8B2090000-00007FF8B20A2000 libcacorrectrgb.dll
00007FF8EF620000-00007FF8EF62F000 libcensorize.dll
00007FF8B2070000-00007FF8B2082000 libchannelmixer.dll
00007FF8B2030000-00007FF8B2063000 libchannelmixerrgb.dll
00007FF8D7AE0000-00007FF8D7AEF000 libclahe.dll
00007FF8B2010000-00007FF8B202C000 libclipping.dll
00007FF8D7990000-00007FF8D79A0000 libcolisa.dll
00007FF8A5F50000-00007FF8A5F6C000 libcolorbalance.dll
00007FF8A5F30000-00007FF8A5F4E000 libcolorbalancergb.dll
00007FF8A5F10000-00007FF8A5F2C000 libcolorchecker.dll
00007FF8D4810000-00007FF8D481F000 libcolorcontrast.dll
00007FF8A5EF0000-00007FF8A5F01000 libcolorcorrection.dll
00007FF8A5ED0000-00007FF8A5EEA000 libcolorin.dll
00007FF8CEC30000-00007FF8CEC40000 libcolorize.dll
00007FF8A5EB0000-00007FF8A5EC4000 libcolormapping.dll
00007FF8A5E90000-00007FF8A5EA4000 libcolorout.dll
00007FF8A5E70000-00007FF8A5E84000 libcolorreconstruct.dll
00007FF8CC230000-00007FF8CC240000 libcolortransfer.dll
00007FF8A5E50000-00007FF8A5E6E000 libcolorzones.dll
00007FF8A5E30000-00007FF8A5E45000 libcrop.dll
00007FF8C8EF0000-00007FF8C8F00000 libdefringe.dll
00007FF8A5DD0000-00007FF8A5E21000 libdemosaic.dll
00007FF8A5DB0000-00007FF8A5DD0000 libdenoiseprofile.dll
00007FF8A5D90000-00007FF8A5DA6000 libdiffuse.dll
00007FF8A5D70000-00007FF8A5D83000 libdither.dll
00007FF8A5D50000-00007FF8A5D66000 libequalizer.dll
00007FF8A5D30000-00007FF8A5D44000 libexposure.dll
00007FF8A5D10000-00007FF8A5D28000 libfilmic.dll
00007FF8A5CE0000-00007FF8A5D0D000 libfilmicrgb.dll
00007FF8A5CD0000-00007FF8A5CDE000 libfinalscale.dll
00007FF8A5CC0000-00007FF8A5CD0000 libflip.dll
00007FF8A5CA0000-00007FF8A5CB3000 libgamma.dll
00007FF8A5C80000-00007FF8A5C92000 libglobaltonemap.dll
00007FF8A5C60000-00007FF8A5C73000 libgraduatednd.dll
00007FF8A5C50000-00007FF8A5C60000 libgrain.dll
00007FF8A5C30000-00007FF8A5C41000 libhazeremoval.dll
00007FF8A5C10000-00007FF8A5C2A000 libhighlights.dll
00007FF8A5C00000-00007FF8A5C0F000 libhighpass.dll
00007FF8A5BF0000-00007FF8A5C00000 libhotpixels.dll
00007FF8A5BD0000-00007FF8A5BE1000 libinvert.dll
00007FF8A5BA0000-00007FF8A5BC2000 liblens.dll
00007FF8A5B70000-00007FF8A5B97000 liblensfun.dll
00007FF8A5B50000-00007FF8A5B63000 liblevels.dll
00007FF8A5B30000-00007FF8A5B4C000 libliquify.dll
00007FF8A5B10000-00007FF8A5B23000 liblowlight.dll
00007FF8A5AF0000-00007FF8A5B02000 liblowpass.dll
00007FF8A5AC0000-00007FF8A5AE2000 liblut3d.dll
00007FF8A5020000-00007FF8A5ABA000 libgmic.dll
00007FF8A4C20000-00007FF8A501F000 libfftw3-3.dll
00007FF8A4BC0000-00007FF8A4C1A000 libGraphicsMagick++-12.dll
00007FF8A4790000-00007FF8A4BBD000 libopencv_core460.dll	4.6.0.0
00007FF8A4710000-00007FF8A478E000 libopencv_videoio460.dll	4.6.0.0
00007FF8A43D0000-00007FF8A4706000 tbb.dll
00007FF9124D0000-00007FF9125F5000 OPENGL32.dll	10.0.19041.2193
00007FF8A2550000-00007FF8A43CE000 libopenblas.dll
00007FF8A0F90000-00007FF8A11DF000 avformat-58.dll	58.76.100.0
00007FF8A0CC0000-00007FF8A0F82000 avutil-56.dll	56.70.100.0
00007FF8A11E0000-00007FF8A2549000 avcodec-58.dll	58.134.100.0
00007FF8A0C20000-00007FF8A0CBC000 swscale-5.dll	5.9.100.0
00007FF8A0BA0000-00007FF8A0C11000 libopencv_imgcodecs460.dll	4.6.0.0
00007FF8A0530000-00007FF8A0B98000 libopencv_imgproc460.dll	4.6.0.0
00007FF912460000-00007FF91248C000 GLU32.dll   	10.0.19041.2193
00007FF8A0220000-00007FF8A0524000 libgfortran-5.dll
00007FF8A01B0000-00007FF8A0212000 libbluray-2.dll
00007FF8A0150000-00007FF8A01A6000 libgme.dll
00007FF89FF50000-00007FF8A0143000 libgnutls-30.dll
00007FF89FE60000-00007FF89FF4B000 libmodplug-1.dll
00007FF89FE30000-00007FF89FE51000 libmfx-1.dll
00007FF89FE00000-00007FF89FE2F000 librtmp-1.dll
00007FF89FCA0000-00007FF89FD1C000 libssh.dll
00007FF89FD20000-00007FF89FDF3000 libsrt.dll
00007FF89FC20000-00007FF89FC9D000 libvulkan-1.dll	1.0.1111.2222
00007FF89FC00000-00007FF89FC17000 libgsm.dll
00007FF89FB70000-00007FF89FBF1000 libmp3lame-0.dll
00007FF89FB30000-00007FF89FB62000 libopencore-amrnb-0.dll
00007FF89FB10000-00007FF89FB30000 libopencore-amrwb-0.dll
00007FF945590000-00007FF94574C000 MFPlat.DLL  	10.0.19041.746
00007FF89FAA0000-00007FF89FB09000 libopus-0.dll
00007FF89FA70000-00007FF89FA99000 libspeex-1.dll
00007FF89FA50000-00007FF89FA6F000 libtheoradec-1.dll
00007FF89FA10000-00007FF89FA4E000 libtheoraenc-1.dll
00007FF89F9D0000-00007FF89FA03000 libvorbis-0.dll
00007FF89F930000-00007FF89F9C5000 libvorbisenc-2.dll
00007FF89F5F0000-00007FF89F928000 libvpx-1.dll
00007FF89F5D0000-00007FF89F5E9000 libwebpmux-3.dll
00007FF89F2F0000-00007FF89F5CE000 libx264-164.dll	0.164.3094.0
00007FF89F1D0000-00007FF89F2E9000 xvidcore.dll
00007FF89F1A0000-00007FF89F1C8000 swresample-3.dll	3.9.100.0
00007FF89F130000-00007FF89F194000 libquadmath-0.dll
00007FF89F080000-00007FF89F127000 libgmp-10.dll
00007FF89F030000-00007FF89F07B000 libhogweed-6.dll
00007FF89EFD0000-00007FF89F025000 libnettle-8.dll
00007FF94E920000-00007FF94E947000 ncrypt.dll  	10.0.19041.662
00007FF89EEA0000-00007FF89EEC0000 libtasn1-6.dll
00007FF89EEC0000-00007FF89EFCE000 libp11-kit-0.dll
00007FF92EAE0000-00007FF92EAE9000 WSOCK32.dll 	10.0.19041.1
00007FF89EE90000-00007FF89EE9D000 libssp-0.dll
00007FF89EE70000-00007FF89EE83000 libogg-0.dll
00007FF89EDE0000-00007FF89EE67000 libsoxr.dll
00007FF945480000-00007FF9454B4000 RTWorkQ.DLL 	10.0.19041.1741
00007FF94E8E0000-00007FF94E91B000 NTASN1.dll  	10.0.19041.546
00007FF89EDD0000-00007FF89EDDE000 libmask_manager.dll
00007FF89EDB0000-00007FF89EDC2000 libmonochrome.dll
00007FF89ED90000-00007FF89EDA4000 libnegadoctor.dll
00007FF89ED80000-00007FF89ED8F000 libnlmeans.dll
00007FF89ED60000-00007FF89ED71000 liboverexposed.dll
00007FF89ED40000-00007FF89ED52000 libprofile_gamma.dll
00007FF89ED20000-00007FF89ED34000 librawdenoise.dll
00007FF89ED10000-00007FF89ED1F000 librawoverexposed.dll
00007FF89ECF0000-00007FF89ED03000 librawprepare.dll
00007FF89ECE0000-00007FF89ECF0000 librelight.dll
00007FF89ECB0000-00007FF89ECD1000 libretouch.dll
00007FF89EC90000-00007FF89ECAC000 librgbcurve.dll
00007FF89EC70000-00007FF89EC86000 librgblevels.dll
00007FF89EC60000-00007FF89EC6F000 librotatepixels.dll
00007FF89EC50000-00007FF89EC5F000 libscalepixels.dll
00007FF89EC30000-00007FF89EC44000 libshadhi.dll
00007FF89EC10000-00007FF89EC21000 libsharpen.dll
00007FF89EC00000-00007FF89EC0F000 libsoften.dll
00007FF89EBE0000-00007FF89EBF1000 libsplittoning.dll
00007FF89EBC0000-00007FF89EBD2000 libspots.dll
00007FF89EAB0000-00007FF89EBBC000 libtemperature.dll
00007FF89EA90000-00007FF89EAAC000 libtonecurve.dll
00007FF89EA60000-00007FF89EA8A000 libtoneequal.dll
00007FF89EA40000-00007FF89EA51000 libtonemap.dll
00007FF89EA30000-00007FF89EA3F000 libvelvia.dll
00007FF89EA20000-00007FF89EA2E000 libvibrance.dll
00007FF89EA00000-00007FF89EA13000 libvignette.dll
00007FF89E9E0000-00007FF89E9F5000 libwatermark.dll
00007FF89E9C0000-00007FF89E9D4000 libzonesystem.dll
00007FF89E9B0000-00007FF89E9BF000 libbackgroundjobs.dll
00007FF89E990000-00007FF89E9A1000 libcamera.dll
00007FF89E960000-00007FF89E987000 libcollect.dll
00007FF89E950000-00007FF89E95E000 libcolorlabels.dll
00007FF89E930000-00007FF89E942000 libcolorpicker.dll
00007FF89E920000-00007FF89E930000 libcopy_history.dll
00007FF89E910000-00007FF89E920000 libdarktable_label.dll
00007FF89E8F0000-00007FF89E901000 libduplicate.dll
00007FF89E8D0000-00007FF89E8E9000 libexport.dll
00007FF89E8C0000-00007FF89E8CE000 libfilmstrip.dll
00007FF89E8B0000-00007FF89E8BE000 libfilter.dll
00007FF89E880000-00007FF89E8AD000 libfiltering.dll
00007FF89E870000-00007FF89E87F000 libgamepad.dll
00007FF89E680000-00007FF89E86F000 SDL2.dll    	2.24.0.0
00007FF89E630000-00007FF89E675000 dinput8.dll 	10.0.19041.1
00007FF93DD60000-00007FF93DEB2000 inputhost.dll	10.0.19041.1741
00007FF93C410000-00007FF93C4E3000 Windows.Gaming.Input.dll	10.0.19041.1566
00007FF89E610000-00007FF89E629000 libgeotagging.dll
00007FF89E5F0000-00007FF89E604000 libglobal_toolbox.dll
00007FF89E5E0000-00007FF89E5EE000 libhinter.dll
00007FF89E5C0000-00007FF89E5DA000 libhistogram.dll
00007FF89E5A0000-00007FF89E5B5000 libhistory.dll
00007FF89E580000-00007FF89E594000 libimage.dll
00007FF89E570000-00007FF89E57E000 libimage_infos.dll
00007FF89E550000-00007FF89E56A000 libimport.dll
00007FF89E540000-00007FF89E54E000 libioporder.dll
00007FF89E530000-00007FF89E540000 liblighttable_mode.dll
00007FF89E510000-00007FF89E521000 liblive_view.dll
00007FF89E500000-00007FF89E510000 liblocation.dll
00007FF89E4E0000-00007FF89E4F3000 libmap_locations.dll
00007FF89E4D0000-00007FF89E4DF000 libmap_settings.dll
00007FF89E4B0000-00007FF89E4C6000 libmasks.dll
00007FF89E490000-00007FF89E4A4000 libmetadata.dll
00007FF89E470000-00007FF89E485000 libmetadata_view.dll
00007FF89E450000-00007FF89E46A000 libmidi.dll
00007FF89E430000-00007FF89E441000 libportmidi.dll
00007FF927080000-00007FF9270A6000 winmmbase.dll	10.0.19041.1
00007FF944980000-00007FF944A05000 MMDevAPI.DLL	10.0.19041.1503
00007FF89E3E0000-00007FF89E426000 wdmaud.drv  	10.0.19041.1
00007FF945C40000-00007FF945C49000 ksuser.dll  	10.0.19041.1
00007FF9452E0000-00007FF9452EA000 AVRT.dll    	10.0.19041.546
00007FF944B20000-00007FF944CA2000 AUDIOSES.DLL	10.0.19041.2364
00007FF94E3C0000-00007FF94E40B000 powrprof.dll	10.0.19041.546
00007FF94E290000-00007FF94E2A2000 UMPDC.dll
00007FF89E3D0000-00007FF89E3DD000 msacm32.drv 	10.0.19041.488
00007FF89E3B0000-00007FF89E3CE000 MSACM32.dll 	10.0.19041.1
00007FF89E3A0000-00007FF89E3AB000 midimap.dll 	10.0.19041.488
00007FF89E370000-00007FF89E391000 libmodulegroups.dll
00007FF89E360000-00007FF89E36E000 libmodule_toolbox.dll
00007FF89E340000-00007FF89E351000 libnavigation.dll
00007FF89E330000-00007FF89E33F000 libratings.dll
00007FF89E310000-00007FF89E32A000 librecentcollect.dll
00007FF89E300000-00007FF89E310000 libselect.dll
00007FF89E2F0000-00007FF89E2FE000 libsession.dll
00007FF89E2D0000-00007FF89E2E1000 libsnapshots.dll
00007FF89E2B0000-00007FF89E2C2000 libstyles.dll
00007FF89E290000-00007FF89E2B0000 libtagging.dll
00007FF89E270000-00007FF89E285000 libtimeline.dll
00007FF89E260000-00007FF89E270000 libviewswitcher.dll
00007FF89E250000-00007FF89E25E000 libview_toolbox.dll
00007FF939560000-00007FF9397DF000 dwrite.dll  	10.0.19041.1566
00007FF89E240000-00007FF89E24D000 libpixbufloader-svg.dll
00007FF934EA0000-00007FF934F4C000 TextShaping.dll

Windows 10.0.19045
DrMingw 0.9.5

**Comment by Nilvus** [comment]
darktable 4.0.1 is an old release. We are on 4.2 actually. There's multiple bug fixes since. Please update.
If it's about a specific image, that could be a corrupted image. So we can't do anything. Check file image (or try by removing it from darktable) and update darktable. I close as we can't do anything here.
