### ISSUE TITLE
"Select untouched" : behaviour vs documentation mismatch ? 

### ISSUE THREAD

**Issue by homer3018** [darktable-org/darktable#13444]
**Describe the bug/issue**
I have a very small collection that I'm working on currently. Only 1 photo has been processed however when I use the "select untouched" button, it selects 2 pics only (which are indeed untouched) but it's missing a bunch of others.
To confirm these are indeed untouched, I tried the selective copy of the history stack which gives me "can't copy history out of unaltered image.
On another collection it selects none, where there were actually ALL untouched.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Try to pick a collection/folder where you have a mix of retouched and unaltered pictures
2. Click on 'select untouched'
3. Check that ALL the untouched pictures have been selected

**Expected behavior**
All the untouched picture should get selected.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.2.0
* OS                : macOS 13.1 (22C65)
* Memory            : 32g

**Comment by gi-man** [comment]
There is a symbol in the top right corner of the thumbnails )if you have the overlays on) that shows if the images `has changed`. There is an internal tag that darktable for this display and for the untouched selection. 

If you want to reset and image to be untouched, you can via `discard history` in `history stack` module or if you reset the history in the darkroom view.

**Comment by homer3018** [comment]
Exactly. So all images without that symbol should be untouched and therefore being selected upon clicking the "select untouched" button.

This is NOT what's happening.

**Comment by pehar1** [comment]
Not able to reproduce. Tried with two different folders simulating the situation you described. Tried also with folders with only untouched images and all images processed. Works for me as expected.

darktable 4.3.0+326-g026d64254
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by homer3018** [comment]
Let's see if anyone on MacOS can reproduce then.

**Comment by pehar1** [comment]
Do you observe the same behavior if you make the selection via _collections_ module?

![collections-history](https://user-images.githubusercontent.com/104291381/215028863-69065cb8-7753-43b8-ba19-cdd1492129dd.png)

**Comment by homer3018** [comment]
That's interesting...
I have this : 
![Screenshot 2023-01-27 at 08 41 44](https://user-images.githubusercontent.com/36423314/215033951-cf3bbc63-7524-47b8-a284-2676feb65bef.png)

And the *select untouched* is selecting the 2 that are *auto applied*. Instead of *basic* I suppose.
I'm not even sure what exactly has been auto applied anyway.

Ok I'm starting to understand something. As soon as I go to the darkroom with one new image, it goes *auto applied*. It does change the fact that the *select untouched is not behaving as it should though.

**Comment by TurboGit** [comment]
> Ok I'm starting to understand something. As soon as I go to the darkroom with one new image, it goes _auto applied_. In other words, the _basic_ images are images that I never opened in the darkroom yet.

Exactly, "auto applied" means that the default modules have been added (needed when entering darkroom) but nothing has been hand made in darkroom.

**Comment by homer3018** [comment]
Any hints as to why the *select untouched* is going for the *auto applied* tag rather than *basic* ? I'm guessing this is what's going on in the backend at least for me.

**Comment by pehar1** [comment]
I don't know the original intention behind this implementation. But I agree that it seems more logical to display the images with the flags _"basic"_ **and** _"auto applied"_ if _"lighttable -> select -> select untouched"_ is selected.

Or maybe only the images with the flag _"basic"_, because _"auto applied"_ means that the user has actively made changes to the _"basic"_ settings. Automatically, but changes.

I am not sure which would be the best solution. Personally I don't use _"lighttable -> select -> select untouched"_, I prefer the more specific selection via the collections module.

**Comment by Nilvus** [comment]
It's not the first time we had such feedback for that button. I never use it too and I agree its behavior is not obvious. Maybe we should:
- or remove it completely (and let user use more obvious filter on collections module like explains by @pehar1)
- or change it's behavior (also explains greatly by @pehar1)

As there's a filter on collection, I would be for 1st solution (remove it). But clearly, we can't let that button as it is actually. I wouldn't mind if it stays (I just ignore it) but seeing such feedback coming again, we need to change something.

**Comment by Nilvus** [comment]
@homer3018: I suggest, if you agree, to change your title issue. Something like: "Select untouched" behavior not clear, change it?

**Comment by AlicVB** [comment]
There has been change last year on this part for the filtering and the icon. I suspect that this changes have not been ported to the "select untouched" button...

**Comment by homer3018** [comment]
Thanks all for the comments and suggestion. 
I've just checked the documentation and it's pretty clear : 

> select untouched
> Select all images in the current collection that have not yet been developed.

Based on that, I'd think that the **basic** tag should be targeted. As mentioned before, the **auto-applied** tag represents some changes even though it's not from the hand of the user, it's still him who triggered to go to the darkroom. The *developed* word I think is the key here. As far as I understand the situation, **basic** is truly untouched.

I also agree that leaving things in this current state can be misleading, as it's been my case. I also agree that we could achieve the same goal using the collection filters (which is what I'm doing now thanks to your feedback). 

The logical conclusion I'm reaching would be to change its behaviour to target the **basic** tag instead of  **auto-applied** (or get rid of it, but that'd not be my preference).

Thanks again, keep up the great work !

**Comment by TurboGit** [comment]
@AlicVB : I did port the change as the whole button was indeed broken. Do you want to have a look at this?

**Comment by gi-man** [comment]
I never use this module. For select all and none I use the keyboard. The others buttons seem redundant with filters on collection.
