### ISSUE TITLE
Problem with the automatic selection when using copy&import

### ISSUE THREAD

**Issue by atomikdg** [darktable-org/darktable#13449]
When doing a copy&import on my SD Card, DT automatically select the files that were NOT imported before (see video file below) but...when I click on "copy&import" it imports all files on my SD.
In the video example, it selects 3 files (it is correct) and import a lot more...

Video link= [hhttps://nx22856.your-storageshare.de/s/gARTJxqE9bm53Rk](https://nx22856.your-storageshare.de/s/gARTJxqE9bm53Rk)

Darktable version:  4.2.x ( e8ad7f4df831a7e5e3927278b90f2fbd4e2e17bc )
OS: Linux OpenSuSE Tumbleweed

@TurboGit

**Comment by zisoft** [comment]
Strange, I cannot reproduce that.

**Comment by atomikdg** [comment]
Nobody else can reproduce my bug ? ;-)

**Comment by ptilopteri** [comment]
I cannot.
