### ISSUE TITLE
add harmony guides buttons - remove corresponding key shortcut (alt-scroll)

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13458]
I find (let's see if it is shared) that changing the color harmony guides using a key combination (alt+scroll) is not good.

My proposal would be to add a set of buttons to select one of the guide. Maybe vertically where the current harmony toggle is? Any other proposal? And then remove this `alt-scroll` support (we still have an action that can be used to map to any key) and the description in the tooltip.

Also after some use I also found the current color harmony icon hard to read on my big screen. I would certainly prefer:

![image](https://user-images.githubusercontent.com/467069/215254869-c356672c-d821-4358-8c5e-e9d0e7676018.png)

BTW, you mentioned also that you liked it.

**Comment by Mark-64** [comment]
Yes, both are on my to do list

**Comment by Mark-64** [comment]
... but for the color harmonies, I am evaluating options. A vertical line of buttons, or even better a grid, as suggested by @dterrahe.
However, I believe we should encapsulate those in a pop over, with modal behavior. So, selecting one harmony will require two clicks.
In fact, I have already tried and failed with mouse hover.
Unless someone has a better idea.

Another problem is 9 color harmonies + one off option = 10 different buttons and icons. They could become hard to distinguish.
Maybe regular text menu then?

**Comment by Nilvus** [comment]
I agree that #13456 add one more button and there's already quite a lot on histogram. We should avoid adding too much buttons (for performance reason AND more important avoid cluttered histogram UI). Having all options on one click is the best but that would need overloaded UI and we don't want that.

So probably a menu drop-down is the best solution, even if it adds one more click.

But we also need to be sure which options are REALLY needed. Even if it good be useful, I think that a brightness control is not really needed. Setting color harmonies is more important. We have to limits options to also avoid cluttered UI.

**Comment by Mark-64** [comment]
So, one possibility is this

![image](https://user-images.githubusercontent.com/43290988/215313061-3f3fbe6d-8809-4635-b0e1-aef672cb37ab.png)

The color harmony (toggle) button will trigger the pop over menu and it will stay active except if "none" is selected.
And yes, I will redesign the icon.

Now, I am not sure that putting 10 buttons instead of text is better. Icons would be difficult to distinguish from one another and we would have to rely on the tooltip text anyway.

If you like it, I can quickly send a PR.

**Comment by Mark-64** [comment]
With this (or whatever else menu type) we can eliminate ALT+SCROLL to change harmony type.
So we could rearrange as follows:

- scroll: to rotate
- shift+scroll: to slow rotate
- alt+scroll: to change width

@dterrahe could it be possible to define actions for the above, giving default values, but leaving the user free to override?
I see how to define default accel key combinations for everything, but how to include scroll?

**Comment by Nilvus** [comment]
Need to test your proposal @Mark-64 but on paper, seems great to me.

**Comment by Mark-64** [comment]
New icon

![image](https://user-images.githubusercontent.com/43290988/215343044-380426c8-30ba-4de7-82e5-b52f10523bcc.png)

**Comment by Mark-64** [comment]
Proposed a draft PR, let's continue the discussion there
