### ISSUE TITLE
Applying styles via keybind appends history regardless of append/overwrite setting

### ISSUE THREAD

**Issue by Clorix1** [darktable-org/darktable#13465]
**Describe the bug/issue**
I've just updated to v4.2.0 from v4.0.1.  In the new version, when I press a keybind to apply one of my style presets in darkroom view, the history steps are appended regardless of what setting I have selected in the history stack module.  I've also noticed that it appears that when using a keybind to apply a style while in the lighttable view, the style overwrites the selected image's history regardless of what I have selected.

**To Reproduce**
1.  In lighttable view, select "overwrite" for the history stack method.
2. While editing an image in darkroom view, press a keybind (or perhaps just apply a style?) and check the history stack.
3. Press another keybind to apply a different style.
4. See that the second style gets applied on top of the first style rather than overwriting it completely.

**Expected behavior**
When applying styles with "overwrite" set as the history stack method via keybinds, the history stack should be completely overwritten on subsequent style applications.  It worked fine in v4.0.1.

**Platform**
* darktable version : v4.2.0
* OS                : Windows 11 Pro 22H2
* Memory            : 32GB DDR4
* Graphics card     : Nvidia RTX 3060 Ti 8GB
* Graphics driver   : 528.02
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
 - Can you reproduce with another darktable version(s)? **no**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Comment by TurboGit** [comment]
This new behavior seems more appropriate because in darkroom you don't have access to the style mode (overwrite / append). With the behavior being append if you want to overwrite you still have access to the history. Just select the point at which you want to apply the style.
