### ISSUE TITLE
On a long history, cursor change on bottom steps to resize one

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13468]
**Describe the bug/issue**

When you have a long history and move history to bottom, you could see cursor changing to resize one.

**To Reproduce**
1. Go to darkroom with an image with a lot of steps on history (for example, on image I see that issue, I have more than 50 steps)
2. Move slider to bottom (no need to scroll down to first steps ; on an image with 56 steps, issue started between steps 22 and 23)
3. Move cursor above steps and see that at some steps at the bottom, cursor change to classic pointer from resize one but there's nothing to resize here.

**Expected behavior**

No resize cursor when nothing to resize!

**Screenshots**

![Capture d’écran du 2023-01-29 17-32-42](https://user-images.githubusercontent.com/45535283/215340448-261bd0c3-d827-426c-9716-c306278d57d2.png)

**Which commit introduced the error**
Should only be  #13418 from @dterrahe 

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : last master

**Comment by dterrahe** [comment]
I haven't seen this behavior myself. Have others seen this? (@TurboGit)

Are you saying that if you move the cursor from the bottom (where it is correctly the resize cursor) upwards you expect it to _immediately_ return to the normal pointer cursor but it takes a while for this to happen? Or it doesn't happen at all. Or are you saying that it is an arrow at history item 21 and then when you move it up to 22 it changes to a resize cursor?

Might be actually useful to fill out issue template so I have a better chance to reproduce.

**Comment by Nilvus** [comment]
I don't understand your last sentence, I filled out issue template.

I am saying that it is an arrow at history item 21 and then when you move it up to 22 it changes to a resize cursor? See screenshot. I can't resize but cursor change to resize one. This only happen when having a long history. It's not only on item 21 on my example. This happens on all items between original to 22 ones. I have tried to create a screencast with Gnome inside tool but it doesn't record cursor. I don't have any other item actually.

I'm wondering if line 905 on history.c file could be related to that issue:
`
gtk_box_pack_start(GTK_BOX(self->widget), dt_ui_resize_wrap(d->view, 100, "plugins/map/heightlocationwindow"), TRUE, TRUE, 0);`

Will try other settings on my side.

**Comment by Nilvus** [comment]
Ok, I think I better understand that issue. Resize cursor remains on items hidden.

So:
1.  Have an history with a scrollbar and so some items hidden at the bottom.

![image](https://user-images.githubusercontent.com/45535283/215346341-3bdc01c6-da00-401c-a1de-0e0675ed909c.png)

3. At this step, cursor resize appears only above compress history like screenshot below (normal and wanted behavior):

![image](https://user-images.githubusercontent.com/45535283/215346296-91af0e14-d37b-4ed3-b91b-3af21860234d.png)

On that history, resize cursor appears so between item 10 and compress history button as wanted.
4. Move scrollbar to bottom to show items below
5. Resize cursor remains on all previously hidden items, so on example here between item 10 and compress history as before:

![image](https://user-images.githubusercontent.com/45535283/215346235-f385a33a-eb96-469d-8a4b-84f235001819.png)
![image](https://user-images.githubusercontent.com/45535283/215346244-ae824bb6-0a85-4be4-ace3-d4316bdf2e9c.png)

Seems that cursor position is not updated or only related to bottom item shown on first step and not about compress history button position.

Hope that will help you understand that issue @dterrahe.

**Comment by dterrahe** [comment]
> Hope that will help you understand that issue

Many thanks! Yes, that helped me reproduce it.

**Comment by TurboGit** [comment]
A bit late... but yes I was able to reproduce...
