### ISSUE TITLE
[Lighttable] edit or store new preset is broken

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#13472]
**Describe the bug/issue**
When storing a new preset or edit a newly added preset, the o.k.-button is not lit and hence changes cannot be applied

**To Reproduce**
1. Go to 'Lighttable' 
2. Click on 'collections' module (others have the same issue)
3. makes some filterings and than click on hamburger manu "store new preset" or edit preset if there is one selected already

**Expected behavior**
o.k. button can be pressed

**Screenshots**
![Screenshot_20230129_210359](https://user-images.githubusercontent.com/49004103/215352820-50f995d7-86c5-428b-9de3-eb94f4054942.png)

**Platform**
* darktable version : 4.3.0+369~g8e00f52cd
* OS                : Linux - kernel 6.1.8-gentoo
* Distro            : Gentoo Base System release 2.9
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-525.85.05
* OpenCL installed  : Yes (opencl-headers-2022.09.30)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.6
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.35
* gcc               : x86_64-pc-linux-gnu-11
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by Nilvus** [comment]
@TurboGit: seems a regression for your work on presets.

**Comment by Nilvus** [comment]
And not only on lighttable. See: #13473

**Comment by TurboGit** [comment]
Yes a regression, the OK button is only accessible when the format has been selected... But this is only for IOP presets obviously. I'll fix.
