### ISSUE TITLE
print view: omnibus of potential features/changes

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#13474]
Print view is stable and effective, but hasn't had a lot of work done on it lately. There's been some mailing list discussion about possible improvements, and a feature request. Here's a list of possible nice features to add.

- [ ] Print to file, see #12874.
- [ ] Allow for opening >1 image in print view. Open them in a contact sheet style.
- [ ] Separate the "print settings" panel into multiple panels, e.g. move the layout features into a separate panel. Could also help with code comprehensibility, as libs/print_settings.c is currently 3,240 LOC!
- [ ] Scan available printers when switch to print view, or at regular intervals. Currently this scan only happens at startup, so darktable needs to be restarted when a new printer is turned on or connected.
- [ ] Image layout can be lost when switch out of print view. Can this be saved via conf? Can this be saved in a presets?
- [ ] Increase maximum # of images in print layout. Currently this may be 20, but some users are using multi-image layout for contact sheet style printouts, and would be helped by more.
- [ ] Have a more powerful multi-image layout setup. See a [dt lua example](https://multimedia4linux.de/index.php/bildbearbeitung/darktable/darktable-plugin-digitaler-kontaktabzug) which uses Imagemagick and a [separate project](https://github.com/rbreu/beeref/).
- [ ] Would it help print view to use the new develop pixelpipe interface (`dt_dev_image()` and `dt_view_paint_buffer()`? Or is the extant mipmap code more flexible/faster for showing the images in the center view?
- [ ] Dimensions marked in center view could also show the size of the current image within the layout box, not just the bounding box the image will fit into.
- [ ] Image dimensions as given on right panel don't always update as boxes in layout are selected/resized. (E.g. enter print view, then drag the image bounding box to decrease its size. The "image width/height" values don't update at the end of the drag.)
- [ ] Print view uses hardcoded RGB values. Use CSS instead, so can work with themes.
- [ ] Is the print view profile handling ideal? See #12240.
- [ ] In print settings panel, rename bottom section from "print settings" to "intermediate colorspace conversion" or such, to make it more clear what that controls.
- [ ] The "image layout" #'s for image width/height and entries for box x/y/width/height should update when dragging the box in the center view.

There probably are more, but this is a quick rundown. I'd be interested for comments on other feature requests or a sense of which are of great priority. In my mind, #12874 is a nice one to work on, as it opens up print view to users without printers, who can work with it as a nice multi-image layout tool.

In the near term, I can't take on any of this work, but would in the longer term.

**Comment by spaceChRiS** [comment]
One more thought about print to file, but not directly related to #12874: Most of the software installed on my system with printing feature has a print-to-pdf/ps/svg functionality, but this seems not to be provided by cups and therefore not available in darktable. I suspect this functionality comes from gtk and maybe some big software packages ship their own framework (e.g. firefox, libreoffice), but I am not entirely sure. It would be great, if a print-to-pdf/ps/svg functionality could be added either in #12874 as a native solution, or by adding such functionality if available from gtk. As I don't know which solution would be best, I added it here rather than in the feature request regarding print-to-image.

**Comment by dtorop** [comment]
> Most of the software installed on my system with printing feature has a print-to-pdf/ps/svg functionality, but this seems not to be provided by cups and therefore not available in darktable.

There is [CUPS-PDF](https://www.cups-pdf.de/) which can do this. It's packaged on Debian as printer-driver-cups-pdf. Presumably it's similarly present on other Linux variants as well. This is different than the "Save to PDF" function in Firefox or other similar tools. But #12874 would be a different implementation, as it would rasterize the print layout directly to a PNG/JPEG/TIFF/etc. Though a hacky implementation could be to take the PDF 1.3 file generated by dt's print code, and use an external tool or library to rasterize it then export the results.

**Comment by diefau** [comment]
Some ideas:
- The paper size should be selectable independently of a printer
  maybe to check before sending to a printer?
- The media should be selectable independently of a printer
- A zoomable view like in darkroom would be nice
- The 'display grid' should be more than 100 mm (for large paper sizes)
  the maximum is alway 100 independently of the unit, why?
- The 'snap to grid' should eventually be adjustable (for large paper sizes)?
- "Behind" the 'print' button should popup a dialog for output media (file or printer etc.)
  maybe a GTK print dialog (don't know the real name)?
- It would be very nice, if every picture (image area) could have selectable text line(s)
  like filename and all from metadata you want
- If this would be possible, a header (and footer) for every page (with selectable font-size)
  would be be nice too

**Comment by dtorop** [comment]
@diefau: Interesting/good suggestions! Though of course now I see that this extends beyond my various pet concerns and that there could be a tremendous amount of work here...

Particular notes:

> "Behind" the 'print' button should popup a dialog for output media (file or printer etc.). Maybe a GTK print dialog (don't know the real name)?

Interesting. On one hand, we wouldn't need to rescan for printers if we used a GTK print dialog. On the other hand, I think paper sizes are per-printer, so at that point much of the layout work would happen in a (small) tab of the print dialog (as in GIMP), which seems very un-darktable, as dt seems to eschew the modal. For better or worse, if the work happened in tabs of a print dialog, then dt's print view would become unnecessary, as the print dialog could just be triggered from lighttable view.

I really like the dt style of having a separate print view with a meaningful (if still not currently zoomable) center view, and I'd hate to GTK-ify this too much. OTOH, I understand that the GTK folks have spent a tremendous amount of thought and time crafting a [sound multi-platform print dialog ](https://docs.gtk.org/gtk3/class.PrintOperation.html).

> When resizing an image area with a picture in it, the picture is greyed "out" and the picture is only just resized (or moved) when the resizing of the image area is finished. Is it to C(G)PU-intensiv doing the resizing of the picture "always" (with every mouse event)?

This is something I'm interested in as well (along with updating the box/image dimensions in the right panel). My guess is that with modern computers it isn't too processor intensive, but the only way to find out is to try. My memory is that there's something about the current code which makes this difficult, but that's not insurmountable.

So long as the image is pulled in via the mipmap cache, if the image is dragged larger it may initially be lores, then become more detailed as the higher resolution image is either pulled from the cache or generated. That's probably not a huge concern though.

**Comment by TurboGit** [comment]
> * The paper size should be selectable independently of a printer.
>   Maybe check the size before sending to a printer?
> 
> * The media should be selectable independently of a printer.

If this is done we really want to make it clear to users that a specific media is not from the printer as one need a proper profile for each media (that's what Turboprint does).

**Comment by TurboGit** [comment]
@dtorop : Nice list, this is going to keep you busy for quite some time :)

**Comment by dtorop** [comment]
Remembering more: I think there's a good reason for dt's print using handcoded PDF rather than going the GTK PrintOperation route. And that this has to do with being very precise about the DPI of the output file in relation to the printer, as well as controlling color profiles. I'm not sure if this still applies, and it may take some examination of GTK code (and how GIMP does things?) to be sure.

And yes, it could be possible to still use the CUPS interface (if present) to scan for available paper sizes and media within dt, do the layout in the center view,  but still open up a print dialog (GTK's or Turboprint) to make the print. But then we do enter the realm of potential mismatches between what the user specifies in dt and what they specify in the print dialog. I forgot that there's already a Turboprint interface which presumably opens up a separate dialog to print.

> Nice list, this is going to keep you busy for quite some time :)

My gosh yes. Well, at least it'll give me something to look at when I do have some time...

**Comment by diefau** [comment]
Dan Torop ***@***.***> writes:

> Remembering more: I think there's a good reason for dt's print 
> using handcoded PDF rather than going the GTK PrintOperation 
> route. And that this has
> to do with being very precise about the DPI of the output file 
> in relation to the printer, as well as controlling color 
> profiles. I'm not sure if this still applies,
> and it may take some examination of GTK code (and how GIMP does 
> things?) to be sure.
GIMP has another possibility: use Gutenprint.-)

I tried the printer-driver-cups-pdf package and there I can select 
many, many paper sizes! That looks very good.

I think, I should remove this point (idea) with the GTK dialog.-)

**Comment by dtorop** [comment]
> GIMP has another possibility: use Gutenprint.-)

True... I forget that GIMP has two print options, GtkPrint and Gutenprint's print plugin. Though do both pass the resulting image to CUPS, which might pass the resulting image back to Gutenprint to print? Or does the Gutenprint plugin bypass CUPS for Gutenprint-supported printers?

>I tried the printer-driver-cups-pdf package and there I can select many, many paper sizes! That looks very good.

Great!

> I think, I should remove this point (idea) with the GTK dialog.-)

There's still some interest in it. For example, with current dt print, we don't have direct control over printer options, it just uses the default CUPS options for the given printer. So someone who has their printer set up to default to draft quality text will be frustrated when dt prints the photographs at that quality. (In my case the workaround is to create two CUPS printers, both connected to the same physical printer. One has photo-quality settings and no color correction as default, for use from dt. The other has, as default, text-quality settings. But this is hacky.) It would be nice to be able to configure CUPS options at print time, which is possible in the "Advanced" tab in GTK's print dialog.

Regardless, it's worth thinking this all through.

**Comment by TurboGit** [comment]
> True... I forget that GIMP has two print options, GtkPrint and Gutenprint's print plugin. Though do both pass the resulting image to CUPS, which might pass the resulting image back to Gutenprint to print? Or does the Gutenprint plugin bypass CUPS for Gutenprint-supported printers?

Fact is that CUPS was chosen as we are sure it does almost nothing. We really want to get full control of color profile and want to be sure than no layer will downscale/upscale or mess with the pixels somehow.

**Comment by dtorop** [comment]
> Fact is that CUPS was chosen as we are sure it does almost nothing. We really want to get full control of color profile and want to be sure than no layer will downscale/upscale or mess with the pixels somehow.

Very much makes sense.

**Comment by jenshannoschwalm** [comment]
I don't use the print module at all, just a few things come to my mind
1. print to file seems to be useful
2. Why print to pdf, we have that for export? Maybe we can add paper sizes there?

**Comment by dtorop** [comment]
>     2. Why print to pdf, we have that for export?

Print to PDF from the print view would give nice control of layout, whether this is controlling the margins of a single image, or of multiple images per page. And this would come "free" as the there is already an interface to do this in print view.

I find the various layout controls in PDF export to require a good bit of trial and error. And printing multiple images results in one per page (which can be good in many cases), but never something like 2-up or 4-up (which would be useful in other cases).

>  Maybe we can add paper sizes there?

True. The paper size list in export to PDF is pretty minimal.

---

Another thought to add to the omnibus: Right now we have at least three different ways to select rectangular areas in the center view:

 - area colorpicker
 - crop iop
 - image box in print layout

They all have different implementations and look slightly different in the interface. It would be nice to unify these. This could simplify be common code or some sort of GTK hack to make an overlaid widget which does this work. (Or, if dt ever moves to GTK 4, [GSK](https://www.bassi.io/articles/2016/08/10/gsk-demystified-2/) seems plausible for this sort of thing.)

**Comment by dtorop** [comment]
> this would come "free" as the there is already an interface to do this in print view

Thinking about this a bit more: Free was in scare quotes because there's always some surprise work in a retrofit like this. But as well, we (I?) should be wary of reusing print view as a PDF layout UI, just because it is relatively easy to do. Why/when do people actually generate PDFs from darktable? Do they want single-image-per-page as now? Do they want multi-image on the page layouts? Is that out of scope for darktable? Is it out of scope for print view? Should export view simply have more paper sizes (as suggested), and options for n-up display of images?

**Comment by spaceChRiS** [comment]
> Do they want single-image-per-page as now? Do they want multi-image on the page layouts?

I would have use cases for both. But anyway, the former is a special case of the latter.

Multi-page export would be another interesting use case for some automated export. E.g., for contact sheets, in combination with an additional export style that adds a frame and some metadata (watermark module) to each image.

Personally I think this may all be in scope for a photo workflow application, but ymmv. The benefit over export module multi-page export would be that at least some control over page size and layout would be given.

**Comment by rekcodocker** [comment]
The print module is the best way for me to get prints, and I have tried several different programs.
However, the print module is very, very complex. It can to a ton of things and I only need it to print a single picture.  
Sometimes when opening the module, it tries to put a dozen images on the canvas.  
It would be better if the print module did just one thing and was good at it. It does not need to make contact sheets or collages - there is other software for that.   DT is a single-image development system.  I think the Print module tries to do too much in the spirit of 'wouldn't it be nice if it could do this as well'. 
Focus = good.

**Comment by dtorop** [comment]
Adding to an omnibus list (and to add some activity):

What about GTK-ify the print view center area? By GTK-ifying, I mean that the code uses GTK widgets to show the image layout. (This _doesn't_ mean switching to using the GTK print dialog.)

Right now the bulk of the drawing happens via the "print settings" module in the right panel, through gui_post_expose(). As features have accumulated, this has led to a lot of varied code all dropped in there. The various UI actions which update layout all have to remember to update a range of internal state, plus other GUI elements, to keep things consistent. And the print view usually redraws the center view on every mouse move, which uses a lot of CPU. All this could be cleaned up if there were GTK widgets dealing with this.

This could open up a door to other improvements. For example, it could be possible to have appropriately positioned text-entry measurement boxes for width/height and margins appear when the mouse is over an image box in the center view, obviating using the right panel to enter these. This could simplify the right panel, and hide data until the user wants to change it.

And it could add chances for other sorts of interaction: What if, when there is a single image layout box, double-clicking the box would expand it to the page margins? And if there are multiple boxes, what if doubleclicking one made all the boxes be the same size and spaced evenly across the page?

**Comment by TurboGit** [comment]
> What about GTK-ify the print view center area? By GTK-ifying, I mean that the code uses GTK widgets to show the image layout. (This _doesn't_ mean switching to using the GTK print dialog.)

I know next to nothing about Gtk... But one point to keep in mind is that we will have to migrate to Gtk4 at some point and so less Gtk specific code may be a good goal or at least be sure that there is nothing deprecated on this part.

Apart from that I'll say that as long as we keep the same feature and proper printing why not. By proper I have in mind proper placement of images, proper size of each image to ensure that there is no downscale/upscale while sending to printer (and so no quality loss), proper use of the color profiles...

**Comment by dtorop** [comment]
> But one point to keep in mind is that we will have to migrate to Gtk4 at some point and so less Gtk specific code may be a good goal or at least be sure that there is nothing deprecated on this part.

This makes sense. I looked into using [GtkGesture](https://docs.gtk.org/gtk3/class.Gesture.html) for handling input, which seems to be Gtk4-preferred (vs. GDK events). I ran a quick test with gestures, which seem workable, and the code may even be more legible (there's some new boilerplate, but less old boilerplate), so this could be a good place to try this out.

I'm interested to see if is possible to display the images in the layout via the existing dtgtk/thumbnail widget. That code appears really well written and well tested, and presumably is so integral to dt that it would be a first step in a Gtk4 update. The downside would be if it introduced new use cases for that code which made it harder to maintain.

> Apart from that I'll say that as long as we keep the same feature and proper printing why not. By proper I have in mind proper placement of images, proper size of each image to ensure that there is no downscale/upscale while sending to printer (and so no quality loss), proper use of the color profiles...

This makes sense. I think any of this work would mostly be UI-touching, and the underlying data (image placement) would continue to be stable, and there'd be no change at all to the output-to-printer work (scaling, profiles...). The first goal would be to make something which looked just like the existing UI, then see what changes would benefit. The vision is akin to how #7922 opened a path to work such as #13435.

**Comment by dtorop** [comment]
To update on GTK-ifying work: I've been working this through. The goal is to help the print UI by: making it more responsive, making future changes/styling easier, increasing code legibility, and fixing some bugs/wishlist items above.

But it's a big overhaul. It requires moving the center area UI handling out of print_settings.c, and into a new widget-ized "dtgtk/print_layout.c". I'm looking at the thumbtable code as a model, and in fact using dtgtk/thumbnail.c to draw the images.

This should simplify lib/print_settings.c and common/printing.h, which at this point have their own hand-rolled UI toolkit (widget drawing, click detection, gesture/mouseover behavior, etc.!). There will be no more need for using `gui_post_expose()` to redraw the center view during every mouse move, nor will there even be any drawing in the `expose()` callback of views/print.c.

It'll still be a lot of work to get this together, but I think worth it. Some minor fixes/annoyances I hope will come along with this:

- Make the measurements in the print settings panel always be consistent with the center view.
- Show the image [instead of just a box](https://github.com/darktable-org/darktable/issues/13474#issuecomment-1407784078) when resizing/dragging it.
- Make image dimensions relative to page margin rather than page edges. This will keep the layout boxes in the printable area when changing margins or page size.
- Probably more...

Also, to add to the list of things to do:

- There is still code to be backwards-compatible with CUPS v1.5 ([released](https://www.cups.org/blog.html) in 2012!) and MacOS 10.7 (from 2011, no longer supported in dt). It would be good to set a minimum CUPS version we support (this could even be v1.6).
