### ISSUE TITLE
Canon Powershot G7 X II custom matrix

### ISSUE THREAD

**Issue by tpapp** [darktable-org/darktable#13479]
Please add support for a custom matrix (everything else is already supported). https://raw.pixls.us/ has samples, but I am happy to add more if necessary.

**Comment by tpapp** [comment]
Do you need a [shot of a color chart](https://pixls.us/articles/profiling-a-camera-with-darktable-chart/) for this? If yes, I can buy one and make it.

**Comment by victoryforce** [comment]
> Do you need a [shot of a color chart](https://pixls.us/articles/profiling-a-camera-with-darktable-chart/) for this? If yes, I can buy one and make it.

The https://raw.pixls.us/ page you linked to says the following:

We are looking for shots that are:

* Well-lit, pattern-full, scenery, low ISO. For example, a daylight landscape
* __`NOT a color target`__
* Lens mounted on the camera, cap off
* Image in focus and properly exposed
* Landscape orientation

We are NOT looking for:

* color targets
* Series of images with different ISO, aperture, shutter, wb, lighting, or different lenses
* DNG files created with Adobe DNG Converter
* Photographs of people, for legal reasons.

**Comment by kmilos** [comment]
@victoryforce Except that this is (or seems to be) about the custom profile, for which the color chart is indeed required.

Probably the issue doesn't belong in rawspeed support though, since base support is already there.

**Comment by tpapp** [comment]
@kmilos: thanks for the clarification. note that this issue is in the darktable repo, not rawspeed.

**Comment by kmilos** [comment]
> note that this issue is in the darktable repo, not rawspeed

Obviously, but at the same time you assigned Roman to the issue, who has nothing to w/ custom dt profiles ;)

**Comment by tpapp** [comment]
@kmilos, note that Roman was assigned by the [issue template](https://github.com/darktable-org/darktable/blob/master/.github/ISSUE_TEMPLATE/new_camera_support.md) automatically, not me (I don't have commit rights in this repo).

**Comment by kmilos** [comment]
@tpapp AFAICT nothing in https://github.com/darktable-org/darktable/wiki/Camera-support#profiling-a-camera nor https://pixls.us/articles/profiling-a-camera-with-darktable-chart/ suggests to use the "New Camera Support" issue template for custom profiles. As you already mentioned, this camera is already supported, it is not "new".

**Comment by Nilvus** [comment]
To complete, it's necessary to use "new camera support" only for new camera to add. For specific adds like that, feature request was better. But without camera profile done as explained on links provided by @kmilos, nothing will happen. An feature request for that is only useful by providing camera profile. And such thing can't be done by anyone else than a user of the camera that spent time to do it.

So, seems that there's not camera profile. @tpapp: are you able to do that? If yes, we can keep that opened, if not, will be better to close.

**Comment by tpapp** [comment]
@Nilvus: I can obtain a color chart and take pictures, but help beyond that would be appreciated.

Ok if I get the SpyderCheckr 24?

Also, just to clarify: I want to add just a color matrix, nothing else.

**Comment by kmilos** [comment]
@tpapp I think you'll get more people looking and available to help over at discuss.pixls.us for the profiling process itself.

**Comment by Nilvus** [comment]
@tpapp: darktable is made by people who spent their "free" time freely. So what you want could only be done if someone want to spent time on it. As you notice on pixls.us, such thing hadn't been made since years. I understand what you want, I just explain limits and how it works for such software like darktable (who isn't a commercial software made by paid people). As letting opened such issue will not help and Github place is for issues to fix or feature requests that could be done by some developer, I close that issue. Of course, with pixls.us discussion you started, if you find a way to have a custom matrix made. It will even be better to propose it as a pull request but if you don't know how to do that and can provide file for custom matrix, you could ping me with custom matrix linked, to reopen that issue.
