### ISSUE TITLE
A new Posterization module for DT for creative use

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#13470]
It would be nice to perform posterization in a flexible way using some of the colour spaces already used in DT.
E.g. posterize lightness, hue, the green channel...
Here is a PDF to expand on the idea.
[Posterize Reqs V6.pdf](https://github.com/darktable-org/darktable/files/10530575/Posterize.Reqs.V6.pdf)

**Comment by lintujuh** [comment]
There has been discussion in pixls.us about this, one started by you (https://discuss.pixls.us/t/idea-for-a-new-dt-module-posterize/27020), and one by on pure black&white images (https://discuss.pixls.us/t/pure-black-and-white/27052).

**Comment by RawConvert** [comment]
Yes indeed.  Over a year ago now, so I thought I'd see if there's any interest now among the dev community.  E.g. there may be devs who weren't around when it was first aired.
