### ISSUE TITLE
Filmic RGB Module Causing Black image in darkroom, lighttable and export.

### ISSUE THREAD

**Issue by pazloft** [darktable-org/darktable#13477]
This issues has only occurred after "Upgrading" my GPU from a Nvidia GTX 970 4GB to a Intel Arc A750 8Gb, 

When an image has filmic RGB module enabled on it the entire image changes to black.i assume there is an issue with Filmic RGB and the OpenCL handling of the GPU. 

Modified config
C:\Users\<USER>\AppData\Local\darktable\darktablerc
from:
opencl_disable_drivers_blacklist=
to:
opencl_disable_drivers_blacklist=true

Filetype .raw
Hardware: 13600k, arc a750, 
GPU Driver Version: 31.0.101.4032
OS Windows 11
Darktable 4.2.0

This isnt a big issue for me as i was moving from Filmic RGB to Sigmund which works fine with this. 

if you need any further testing, let me know and I'm more than happy to help. If this is not a bug please close this.

**Comment by todd-prior** [comment]
Is this a case where you might need to delete all the opencl kernels in the cache and then let them rebuild now that you have a new gpu... maybe this won't help?? Might be worth a try... FIlmic is still useful on many images that are not handled as well with Sigmoid so it would be nice to have access to both without your issue...

**Comment by pazloft** [comment]
Thanks for the prompt response Todd, any chance you could link me some documentation on how i can go about that on a Windows OS.

**Comment by todd-prior** [comment]
I redirect my config files to specific locations.... my opencl kernels are in a subfolder called...

![image](https://user-images.githubusercontent.com/44409419/216224245-ef5da83e-3655-4def-8771-69699c9308e5.png)

I suspect yours might be in C:\users\username\appdata\local\darktable if you use the standard config location....

**Comment by pazloft** [comment]
I reinstalled DT and the issue persisted, I also deleted the folder C:\users\username\appdata\local\darktable during the reinstall and had the same results.  I didnt find a cache folder but i assume it would have been covered by the reinstall. If not can you share some filenames in the cache folder and i will search for them on my system

**Comment by pazloft** [comment]
It appears the kernel directory can be found using the C:\Program Files\darktable\bin\darktable-cltest.exe is defined in the output:
KERNEL DIRECTORY:         C:\Program Files\darktable\share\darktable\kernels

**Comment by sg456** [comment]
I think this is the normal Windows location - it's where mine are anyway, as well as the log file
`C:\Users\"Username"\AppData\Local\Microsoft\Windows\INetCache\darktable`

**Comment by pazloft** [comment]
thanks for sending that through @sg456 i was able to locate both the kernels mentioned and the log file. I have captured some logs and it appears when OPENCL is activated the filmic module just doesn't even run. 

eg the logs below are for when OPENCL is Disabled. (NO GPU) and the image appears as expected:

image colorspace transform Lab-->RGB took 0.002 secs (0.000 CPU) [filmicrgb ]
image colorspace transform Lab-->RGB took 0.005 secs (0.031 CPU) [filmicrgb ]
image colorspace transform RGB-->Lab took 0.001 secs (0.016 CPU) [shadhi ]
image colorspace transform RGB-->Lab took 0.005 secs (0.000 CPU) [shadhi ]
image colorspace transform RGB-->RGB took 0.003 secs (0.000 CPU) [final histogram]


below are logs for when OPENCL is enable (using GPU):

image colorspace transform RGB-->RGB took 0.003 secs (0.000 CPU) [final histogram]

i compared the kernels between the old NVIDIA GPU and the Intel GPU and they are very different where NVIDIA kernels are in plaintext and readable, the Intel kernels have some readable text and a lot of random characters. sample top 10 lines for each intel and NVIDIA GPUs:

cached_kernels_for_IntelRArcTMA750Graphics_3101014091
below is the output of the colorspaces.cl.bin.fa0cf6646eb1c78670bb608f709e2751


ELF         ÿ                     @           @ 8   @                                                                        ÿ                €      Z                                 	  ÿ                à      ŒC                             %     ÿ                pE       U                                                   š      C                              -w -cl-fast-relaxed-math  -DINTEL=1 -I"C:\Program Files\darktable\share\darktable\kernels"      #      ø                            
          Ô  
 
 SPV_KHR_no_integer_wrap_decoration       OpenCL.std               Ò  colorspaces_transform_lab_to_rgb_matrix         Û  colorspaces_transform_rgb_matrix_to_lab         ä  colorspaces_transform_rgb_matrix_to_rgb      # ð  kernel_arg_type.colorspaces_transform_lab_to_rgb_matrix.image2d_t,image2d_t,int,int,dt_colorspaces_iccprofile_info_cl_t*,image2d_t,    ñ  kernel_arg_type_qual.colorspaces_transform_lab_to_rgb_matrix.,,,,const,,      # ò  kernel_arg_type.colorspaces_transform_rgb_matrix_to_lab.image2d_t,image2d_t,int,int,dt_colorspaces_iccprofile_info_cl_t*,image2d_t,    ó  kernel_arg_type_qual.colorspaces_transform_rgb_matrix_to_lab.,,,,const,,      1 ô  kernel_arg_type.colorspaces_transform_rgb_matrix_to_rgb.image2d_t,image2d_t,int,int,dt_colorspaces_iccprofile_info_cl_t*,image2d_t,dt_colorspaces_iccprofile_info_cl_t*,image2d_t,float*,      õ  kernel_arg_type_qual.colorspaces_transform_rgb_matrix_to_rgb.,,,,const,,const,,const,        pŽ      __spirv_BuiltInGlobalInvocationId    

cached_kernels_for_NVIDIAGeForceGTX970_52756
below is the output of the colorspaces.cl.bin.e45e300bfb613615d00abc37e8453e65

NVIDIA
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Unknown Toolkit Version
// Based on NVVM 7.0.1
//

.version 8.0
.target sm_52, texmode_independent

**Comment by jenshannoschwalm** [comment]
@pazloft it could be related to the intel driver. There has been some work in dt master, would be worth to try that. There should be weekly builds ...

**Comment by jenshannoschwalm** [comment]
Btw you know you are text reading binary files?

**Comment by pazloft** [comment]
@jenshannoschwalm  im not sure how to leverage the updated Master builds on a windows OS. im happy to test when the stable version comes out and report my results there.

**Comment by victoryforce** [comment]
@pazloft You can install one of the recent weekly builds like this: https://discuss.pixls.us/t/darktable-windows-insider-program-2-26/35597

**Comment by jenshannoschwalm** [comment]
Closing this for now ...
