### ISSUE TITLE
preference setting for correct hue angle of azbz and u* v*

### ISSUE THREAD

**Issue by HSUfineprint** [darktable-org/darktable#13478]
**Issue:**

The hue angle of azbz and u* v* in vectorscope were rotated 90° incorrectly.

**Description:**

Yellow hue is at the top in azbz chromaticity diagram, similar situation in CIELUV. But they are at the left in current scope view. It didn't match the represented color space.

**Expection:**

For correctness, the hue angle should be the same with corresponding color space.

**Solutions:**

The hue be placed like this is to conform CbCr coordinate. But it's wrong on color science. I can change darktablerc to correct it, but we should use the correct direction by default. And use an preference option to rotate it.

As for RYB color model, it has no specific primary color position requirements. Many color theory graphics place yellow on the top, Farbkreis Itten color wheel for example. So Y on the top by default is reasonable. It can keep RYB similar with correct azbz.

 Options menu
- color science (default): correct azbz and u* v*, RYB Y on the top
- video editing: counterclockwise 90° azbz and u* v*, RYB R on the top

**Comment by MStraeten** [comment]
maybe the theory places yellow at top but the more common usage is with red at the top - so where's the benefit of changing the current behaviour?
darktable is a tool for practitioners, not for theorists - they can change it via darktablerc ;)

**Comment by HSUfineprint** [comment]
Traditional vector scope (hardware monitor) using the hue angle because of YCbCr coordinate. X axis is Cb, so right side is blue. Y axis is Cr, so top is red. It obeys coordinate definition. Now we use jzazbz and CIELUV, we should obey the color space coordinate too.

The vector scope in darktable is actually the chromaticity diagram of specify color space. It is very clear, Jzazbz and L* u* v*. We should not change it by default, call it azbz but it's not the same with azbz. If a monitor manufatory show a rotated xy chromaticity diagram, everybody will say it's wrong. It's that simple.

Please note, not every photographer uses video editing software. And most user didn't touch darktablerc, even don't know it exists. Adding an option could keep the diagram correct, and some user could still choose a YUV mimic style.

**Comment by MStraeten** [comment]
then why not add a note into the manual how to change the rotation? So those few users requiring a theoretical orientation not really used elsewhere in image or video editing tools gets the info how to modify it. 
That seems to be a better solution than adding further option buttons for each edge case to the scope module.

**Comment by HSUfineprint** [comment]
Already explained the diagram is not correct, and it's not the best way to present it by default just because some user used to it. Traditional vector scope be placed like that because the YUV coordinate. That's exactly why we should keep the rotation of azbz and u* v* correct, the color space's coordinate.

I'm asking an option in preference setting, we already have some there. Stocking choices in a hiding file is not a better solution.
