### ISSUE TITLE
Presets dialog behaves oddly

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#13473]
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

In the print settings “store new preset” and “edit preset” dialogs, the “ok” and “delete” buttons stay inactive, no matter what changes in the dialog. However, leaving the dialog (e.g. with escape key) saves changes. 

**To Reproduce**

1. Go to print view
2. Make a print settings change
3. select “store new preset” from the burger menu
4. Try to klick ok

**Expected behavior**

ok and delete buttons should work.

**Screenshots**

![image](https://user-images.githubusercontent.com/16524534/215353478-f1e10f3b-c62b-4e34-88d6-27aa6cd55119.png)

**Which commit introduced the error**

It seems to work in 4.2.0. I can try a bisect later, e.g. next week, but maybe somebody could confirm the issue first such that it is clear that it is not on my side …

**Platform**

* darktable version : 4.3.0+369~g8e00f52cd-dirty
* OS                : 
* Linux - Distro    : Ubuntu 22.04.1
* Memory            : 32 GB
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : Ubuntu default
* GTK+              : 
* gcc               : 11.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by spaceChRiS** [comment]
I just discovered that this behavior is the case in all presets dialogs, therefore I changed the title.

**Comment by ptilopteri** [comment]
maybe dup of #13472   ???

**Comment by Nilvus** [comment]
Hmmm, same issue opened 20 minutes before yours (#13472). Good to amend it instead of opening a new one. I know #13472 talks about lighttable on title but remains same issue. I close that one.

**Comment by spaceChRiS** [comment]
Yes, sorry for the noise, I initially thought it is only about print …
