### ISSUE TITLE
Make Darktable OpenCL compatible/possible with AMD Mesa drivers

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#13485]
For long Darktable has been pretty strict the way OpenCL is supported. If you are using AMD OpenCL mesa drivers, you are for no luck - it's missing a certain feature and thus not supported by Darktable entirely.

My "feature request" would be to make Darktable utilize everything OpenCL Mesa AMD driver has to offer.

Something like "Standard" and "Advanced" support would be great, depending on the amounts of driver capability and usage, instead of dismissing it entirely.

The way it is, we have to use proprietary AMDGPU driver to have this support in Darktable, which is not only a closed variant, but also a hassle to compile, while Mesa one is working beautifully in any other shape or form.

**Comment by jenshannoschwalm** [comment]
> it's missing a certain feature

If i remember correctly that driver is not missing a feature but a "whole large bunch of functions" required for darktable's OpenCL kernels. (`CL_DEVICE_IMAGE_SUPPORT`)

Don't blame dt - ask AMD to add functionality provided by all other drivers i am aware of.

**Comment by Nilvus** [comment]
As this is a driver issue and not darktable one, I close that issue. Ask drivers developers to correctly support OpenCL. I'm sure that darktable whole team and many users would love having better drivers that will fix issue you pointed.
