### ISSUE TITLE
filter rating setting is reset when adding new images

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#13495]
dt 4.2.x, master, ubuntu 22.04

Filter rating (all, 1/2/3/4/5 stars, rejected only, all except rejected) is most times remembered. If I close and reopen darktable, it's remembered.

However, when new images are added to library, it's reset to "all". It should be remembered in this situation, too.

**Comment by Nilvus** [comment]
Please, as always, create more complete issues and especially darktable version you use. I'm quite it's not the first time we ask you that. There's a template provided on purpose.

**Comment by zisoft** [comment]
> However, when new images are added to library, it's reset to "all". It should be remembered in this situation, too.

I think this will lead to user confusion when newly imported images are not visible due to some forgotten filter settings.

**Comment by paolobenve** [comment]
> I think this will lead to user confusion when newly imported images are not visible due to some forgotten filter settings.

What about a dialog remembering that some image may not be visible? it would be shown only if the filter setting hide some of the newly imported images

**Comment by gi-man** [comment]
> Please, as always, create more complete issues and especially darktable version you use. I'm quite it's not the first time we ask you that. There's a template provided on purpose.

Off topic. Do you think the team will support updating the Issue template to be YAML? I could create one if there is interest. At least it forces some consistency. 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by Nilvus** [comment]
> Off topic. Do you think the team will support updating the Issue template to be YAML? I could create one if there is interest. At least it forces some consistency.
> 
> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

Absolutely not off topic here, when we repeat same things to same users, especially for simple things like version used, that are needed or better to help answer issues/FR.
Anyway, interesting if form fields could be used. Didn't know and would be good to me. I will support if you create them with some fields required.

About issue there, I follow @zisoft. A dialog will be also another click (I don't want it). When importing images, most of the times, we want to see them to filter them. So i'm to keep actual behavior.

**Comment by EC1000** [comment]
Not exactly the same issue, but it is related, so I add it to the discussion, I hope it's ok.  

When new images are added to library, all filters are reset, including any filter set to "and not". So after importing, no image is displayed (for example with an color label filter set to "and not"). 
I understand the idea of resetting values of the filter -- to show newly imported images -- but in this case, the result is quite the opposite!

I am not sure what would work better for different use cases though. For my personnal above example, I would rather like that the "and not" filter would stay unchanged when importing images.
