### ISSUE TITLE
Cannot Change Workflow on M1 Mac

### ISSUE THREAD

**Issue by dfregoe** [darktable-org/darktable#13502]
Want to change modules: default to workflow: scene referred or other workflows and it will not change. Running the latest software on the M1 Mac Mini. I left click on the hamburger menu and see a short list of modules and workflow. It is stuck on default. My Windows machine running Win 10 and Darktable 4.2 will let me change to a workflow from the default modules.

**Comment by MStraeten** [comment]
you're on ventura? then: https://github.com/darktable-org/darktable/issues/12727
possible solution: https://discuss.pixls.us/t/info-macos-13-breaks-darktable/33267/15 or https://discuss.pixls.us/t/current-osx-build/13213/610

**Comment by Nilvus** [comment]
As a duplicate, I close
