### ISSUE TITLE
RFC - preview on history stack - is that worth it?

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13516]
Would it be nice to have a preview if the picture displayed in the tooltip when flying over the history stack?

We currently have the changes in parameters. We could have below (displayed after a timeout) the preview of the corresponding rendering?

**Comment by Nilvus** [comment]
I'm not for that, this will use quite some CPU/GPU and more for some modules used. Not all users have a recent and powerful computer. So I'm against that.

**Comment by paperdigits** [comment]
I'd also say no, it will be slow and... should you have some idea of what your photo looked like in the history stack?

**Comment by TurboGit** [comment]
> I'd also say no, it will be slow

Depends on your hardware. And what I proposed was to have a timeout, that is the current data will be displayed as today and then if waiting a bit more on the history stack you'll get the preview. A bit like what is done for style. So actually that won't impact users with slow computers.

> should you have some idea of what your photo looked like in the history stack?

I think so, hence the RFC... But if that's only me I'll be happy to close this :)

**Comment by jenshannoschwalm** [comment]
I think that would only be useful with full image shown for evaluation.

**Comment by gi-man** [comment]
I dont think I will use this feature.

**Comment by MaTeng211** [comment]
I also think I would not use such a feature. Adding any CPU load and complexity... ...

**Comment by elstoc** [comment]
Also a no from me

**Comment by TurboGit** [comment]
Pretty clear then, I'll close.

Thanks all for the comments.

**Comment by spaceChRiS** [comment]
@TurboGit, I wonder if it would make sense to have a right-click option on a history entry instead to directly generate a snapshot, because the typical workaround (select history entry, make snapshot, go back to tip of history) is error-prone and always causes extra blood pressure (at least for me), because one wrong click may discard important parts of the history …
