### ISSUE TITLE
Dt 4.2 crash when exporting files and working in darkroom

### ISSUE THREAD

**Issue by kubrickfr** [darktable-org/darktable#13510]
when working in darkroom mode while exporting JPEGs, dartkable sometimes crashes, I managed to capture a backtrace, I don't know if this is sufficient information...

[dtcrash.txt](https://github.com/darktable-org/darktable/files/10571715/dtcrash.txt)

DT version is 4.2.0, on gnome 43, wayland, linux 6.1.9, OpenCL disabled.

**Comment by gi-man** [comment]
Do you get a crash if you use x11?

**Comment by ralfbrown** [comment]
@kubrickfr Are you still getting crashes in 4.2.1? (or better yet, current master, e.g. a nightly build)

**Comment by ralfbrown** [comment]
No response from issue originator since original report in February.

**Comment by jenshannoschwalm** [comment]
Closing this as no sufficient information provided.
