### ISSUE TITLE
Having issues building on Ubuntu 22.04

### ISSUE THREAD

**Issue by xMinerv** [darktable-org/darktable#13512]
Hiya there,
I'm having an issue building dt 4.3.0. I have compiled my own version of GraphicsMagick 1.3.40, if thats whats potentially causing an issue, im relatively new to the compiling software game.

cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBINARY_PACKAGE_BUILD=ON -DGraphicsMagick_INCLUDE_DIR=/opt/graphicsmagick-1.3.40/include/GraphicsMagick -DGraphicsMagick_LIBRARY=/opt/graphicsmagick-1.3.40/lib ..

...
[ 57%] Linking C executable darktable
[ 57%] Linking C shared module libslideshow.so
/usr/bin/ld: libdarktable.so: undefined reference to 'CloneImageInfo'  
/usr/bin/ld: libdarktable.so: undefined reference to 'DestroyImage'  
/usr/bin/ld: libdarktable.so: undefined reference to 'ReadImage'  
/usr/bin/ld: libdarktable.so: undefined reference to 'DestroyImageInfo'  
/usr/bin/ld: libdarktable.so: undefined reference to 'CatchException'  
/usr/bin/ld: libdarktable.so: undefined reference to 'BlobToImage'  
/usr/bin/ld: libdarktable.so: undefined reference to 'DispatchImage'  
/usr/bin/ld: libdarktable.so: undefined reference to 'InitializeMagickEx'  
/usr/bin/ld: libdarktable.so: undefined reference to 'DestroyExceptionInfo'  
/usr/bin/ld: libdarktable.so: undefined reference to 'GetImageProfile'  
/usr/bin/ld: libdarktable.so: undefined reference to 'DestroyMagick'  
/usr/bin/ld: libdarktable.so: undefined reference to 'GetExceptionInfo'  
collect2: error: ld returned 1 exit status
make[2]: *** [bin/CMakeFiles/darktable.dir/build.make:180: bin/darktable] Error 1
make[1]: *** [CMakeFiles/Makefile2:1971: bin/CMakeFiles/darktable.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 57%] Built target slideshow
[ 57%] Linking C shared module liblighttable.so
[ 57%] Built target lighttable
[ 57%] Linking C shared module libdarkroom.so
[ 57%] Built target darkroom
make: *** [Makefile:156: all] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE

Also, How can i find out all of the -D Options that i can pass to cmake?

Thank you for your time and advice.

**Comment by wpferguson** [comment]
Have you tried just building with `./build.sh --prefix /opt/darktable --build-type Release`?

Start building with a known, then venture off into the unknown.,
