### ISSUE TITLE
Critical issue after creating a new Piwigo preset

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13517]
**Describe the bug/issue**

First, I see that my Piwigo preset (on export module) lost account settings. I tried to update it but on darktable restart, account settings were lost again (so there's also an issue on that part).

But more critical, after removing my preset, I created another again. After that, I can't launch darktable again. Creating that preset broke data.db file.

@TurboGit: probably for you.

**To Reproduce**

1. Go to 'export module'
2. Set Piwigo account settings
3. Create a preset
4. Close darktable
5. Restart it, darktable try to launch but crash (with lock files remaining).

I've done those steps 2 times (after restoring last data.db file state) and had reproduced each time.

**Expected behavior**

Having Piwigo account settings kept after darktable restart and be able to launch darktable without error nor data.db file corrupted.

**Platform**

* darktable version : actual master

Below attached data.db broken after creating Piwigo preset and crash log file:

[data-broken.zip](https://github.com/darktable-org/darktable/files/10579824/data-broken.zip)
[crash.txt](https://github.com/darktable-org/darktable/files/10579844/crash.txt)

**Comment by TurboGit** [comment]
Yes probably me indeed, as expected if you've seen my message on dt's dev & user mailing-list. Fact is that lib presets should not have been impacted by my change at all... So I probably forgot a case somewhere...

**Comment by TurboGit** [comment]
@Nilvus : Should be fixed!

In your `data.db` you need to remove the presets for piwigo.

**Comment by Nilvus** [comment]
Presets for piwigo were removed just before that issue in darktable preferences.

**Comment by Nilvus** [comment]
@TurboGit: crash is fixed and saving preset is good. But related issue I pointed remains. I mean saving account settings. After your fix, I created a new preset by settings export module options to my piwigo account but restarting darktable and I lost my settings, even if I click again on Piwigo preset I saved. Thus, "account" combo menu just above remains empty. No account settings saved. Do you want me to create another issue or you could deal with that?

**Comment by TurboGit** [comment]
@Nilvus : I think you have the same behavior on 4.2, the account information is accessible using the accounts drop-down.

**Comment by TurboGit** [comment]
At least to me I don't see a change in behavior here. If you think so maybe I'm not looking at the right thing, please open a new issue with way to reproduce. TIA.

**Comment by Nilvus** [comment]
I have nothing on account drop-down, and never had as far as I remember, even if I set them and save preset (this one do not store anything). I can't remember when (I have not updated my Piwigo since months and I make a lot of updates actually) but last time (some months ago) I used it, I have my settings saved when clicking on my preset saved (on hamburger menu of export module).

I see a change: I can't store my settings and need to type them each time I restart darktable. If you have your settings saved, that will be hard to provide a way to reproduce.

**Comment by TurboGit** [comment]
What I don't understand is that the piwigo account (user / password) is stored into the GNU/Linux (GNOME) password manager (via Secrets services - no pun intended).

I have started dt on a clean env (as it was launched first time) and still have my account listed as recovered by the GNOME service.

**Comment by TurboGit** [comment]
@Nilvus : I think you should open a new issue, if some people have the same issue we may get more context/information.

**Comment by Nilvus** [comment]
@TurboGit: thanks for your replies, that helps. Issue was on my side. Your comment about password manager via Secrets services, made me find that I have no more libsecret on darktable preferences password manager menu. Seems that I have uninstalled sometimes ago libsecret-dev package, forgotten that this one was needed to compile darktable with that support. Issue fixed now after reinstalling that package and compile again darktable.

So all good now on my side.

**Comment by TurboGit** [comment]
Great, good to see this solved on your side.
