### ISSUE TITLE
darktable crash and close at the start

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13521]
**Describe the bug/issue**

I stated darktable in terminal and got this error.

> darktable -d all > darktableLog.txt
> [memory] at startup
> [memory] max address space (vmpeak):      143864 kB
> [memory] cur address space (vmsize):      143864 kB
> [memory] max used memory   (vmhwm ):       29964 kB
> [memory] cur used memory   (vmrss ):       29964 kB
> [dt_get_sysresource_level] switched to 2 as `large'
>   total mem:       32028MB
>   mipmap cache:    4003MB
>   available mem:   21894MB
>   singlebuff:      500MB
>   OpenCL tune mem: WANTED
>   OpenCL pinned:   WANTED
> 
> ^^^^^ modulegroups
> vvvvv
> [memory] after successful startup
> [memory] max address space (vmpeak):    19969668 kB
> [memory] cur address space (vmsize):    19969660 kB
> [memory] max used memory   (vmhwm ):      413172 kB
> [memory] cur used memory   (vmrss ):      413172 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    22866444 kB
> [memory] cur address space (vmsize):    22866444 kB
> [memory] max used memory   (vmhwm ):      742232 kB
> [memory] cur used memory   (vmrss ):      742232 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    22964744 kB
> [memory] cur address space (vmsize):    22932128 kB
> [memory] max used memory   (vmhwm ):      748440 kB
> [memory] cur used memory   (vmrss ):      701912 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    24967900 kB
> [memory] cur address space (vmsize):    24967900 kB
> [memory] max used memory   (vmhwm ):     1231408 kB
> [memory] cur used memory   (vmrss ):     1192564 kB
> [memory] max address space (vmpeak):    24967900 kB
> [memory] cur address space (vmsize):    24967900 kB
> [memory] max used memory   (vmhwm ):     1231408 kB
> [memory] cur used memory   (vmrss ):     1213936 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    25210764 kB
> [memory] cur address space (vmsize):    25178000 kB
> [memory] max used memory   (vmhwm ):     1660896 kB
> [memory] cur used memory   (vmrss ):     1621896 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    24964300 kB
> [memory] max used memory   (vmhwm ):     2356140 kB
> [memory] cur used memory   (vmrss ):     1797776 kB
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    24686992 kB
> [memory] max used memory   (vmhwm ):     2356140 kB
> [memory] cur used memory   (vmrss ):     1769468 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    25229688 kB
> [memory] max used memory   (vmhwm ):     2356140 kB
> [memory] cur used memory   (vmrss ):     1562792 kB
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    29330612 kB
> [memory] max used memory   (vmhwm ):     2356140 kB
> [memory] cur used memory   (vmrss ):     2101972 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    25458936 kB
> [memory] max used memory   (vmhwm ):     2356140 kB
> [memory] cur used memory   (vmrss ):     1888064 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    25718988 kB
> [memory] max used memory   (vmhwm ):     2392632 kB
> [memory] cur used memory   (vmrss ):     1975320 kB
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    25074064 kB
> [memory] max used memory   (vmhwm ):     2392632 kB
> [memory] cur used memory   (vmrss ):     1890184 kB
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> validation check failed in _iop_validate_params for type "float", field: g2
> validation check failed in _iop_validate_params for type "dt_iop_temperature_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    26137828 kB
> [memory] max used memory   (vmhwm ):     2698084 kB
> [memory] cur used memory   (vmrss ):     2608604 kB
> validation check failed in _iop_validate_params for type "float", field: aspect
> validation check failed in _iop_validate_params for type "dt_iop_borders_params_t"
> [memory] max address space (vmpeak):    31000476 kB
> [memory] cur address space (vmsize):    25812780 kB
> [memory] max used memory   (vmhwm ):     2698084 kB
> [memory] cur used memory   (vmrss ):     2505892 kB
> [1]    6923 segmentation fault (core dumped)  darktable -d all > darktableLog.txt

**Which commit introduced the error**
 not sure

**Platform**

* darktable version : 4.3.0~git450.f5a79a84-9040.1
* OS: Fedora release 37 (Thirty Seven) x86_64 
* Host: Z390 AORUS MASTER 
* Kernel: 6.0.15-300.fc37.x86_64 
* Uptime: 11 mins 
* Packages: 3284 (rpm), 50 (flatpak) 
* Shell: zsh 5.9 
* Resolution: 3840x2160 
* DE: GNOME 43.2 
* WM: Mutter 
* WM Theme: CustomAccentColors 
* Theme: WhiteSur-dark-solid [GTK2/3] 
* Icons: WhiteSur-dark [GTK2/3] 
* Terminal: gnome-terminal 
* CPU: Intel i7-9700K (8) @ 4.900GHz 
* GPU: NVIDIA GeForce GTX 1070 
* GPU: NVIDIA GeForce GTX 1080 Ti 
* Memory: 3300MiB / 32028MiB
* Graphics driver: 525.60.11
* OpenCL installed: yes
* OpenCL activated: yes
* Xorg:  yes

**Log file**
[darktableLog.zip](https://github.com/darktable-org/darktable/files/10583089/darktableLog.zip)

**Comment by TurboGit** [comment]
There is some errors on your log:

```
     7.0223 [opencl memory] device 1: 18446744073700715776 bytes (17592186044416.0 MB) in use
     7.0262 [opencl map buffer] could not map buffer on device 1: CL_OUT_OF_HOST_MEMORY
     7.0263 [default_process_tiling_cl_ptp] [thumbnail] could not map pinned input buffer to host memory for module 'denoiseprofile'
     7.0263 [default_process_tiling_cl_ptp] [thumbnail] tile (0,0) size 18446744073709550849x720 at origin [0,0]
     7.0263 [opencl alloc_device] could not alloc img buffer on device 1: CL_INVALID_IMAGE_SIZE
     7.0263 [opencl memory] device 1: 18446744073700715776 bytes (17592186044416.0 MB) in use
     7.0263 [opencl memory] device 1: 0 bytes (0.0 MB) in use
     7.0263 [default_process_tiling_opencl_ptp] [thumbnail] couldn't run process_cl() for module 'denoiseprofile' in tiling mode: pinning problem DT_OPENCL_DEFAULT_ERROR
     7.0263 [opencl_pixelpipe] [thumbnail] could not run module `denoiseprofile' on gpu. falling back to cpu path
     7.0263 [pixelpipe_process_on_CPU]   [thumbnail]    denoiseprofile       (   0/   0) -767x 720 scale=-0.3607 --> (   0/   0) -767x 720 scale=-0.3607 
     7.0264 [dev_pixelpipe] took 0.004 secs (0.027 CPU) [thumbnail] processed `denoise (profiled)' on CPU, blended on CPU
     7.0264 [dev_pixelpipe] module `denoise (profiled)' min: (340282346638528859811704183484516925440.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000) [thumbnail]
     7.0264 [opencl alloc_device] could not alloc img buffer on device 1: CL_INVALID_IMAGE_SIZE
     7.0264 [opencl memory] device 1: 0 bytes (0.0 MB) in use
     7.0264 [opencl_pixelpipe] [thumbnail] couldn't generate input buffer for module `flip'
     7.0267 [opencl_pixelpipe] [thumbnail] could not run module `flip' on gpu. falling back to cpu path
     7.0267 [pixelpipe_process_on_CPU]   [thumbnail]    flip                 (   0/   0) -767x 720 scale=-0.3607 --> (   0/   0)  720x-768 scale=-0.3607 
     7.0267 [dev_pixelpipe] took 0.000 secs (0.004 CPU) [thumbnail] processed `orientation' on CPU, blended on CPU
     7.0267 [dev_pixelpipe] module `orientation' min: (340282346638528859811704183484516925440.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000) [thumbnail]
     7.0271 [default_process_tiling_cl_ptp] [thumbnail] **** tiling module 'exposure' for image with size 720x-768 --> 720x-768
     7.0271 [default_process_tiling_cl_ptp] [thumbnail] (1x1) tiles with max dimensions 720x-768, pinned=ON, good 720x1 and overlap 0
     7.0271 [opencl memory] device 1: 18446744073700704256 bytes (17592186044416.0 MB) in use
     7.0337 [opencl map buffer] could not map buffer on device 1: CL_OUT_OF_HOST_MEMORY
     7.0338 [default_process_tiling_cl_ptp] [thumbnail] could not map pinned input buffer to host memory for module 'exposure'
     7.0338 [default_process_tiling_cl_ptp] [thumbnail] tile (0,0) size 720x18446744073709550848 at origin [0,0]
     7.0338 [opencl alloc_device] could not alloc img buffer on device 1: CL_INVALID_IMAGE_SIZE
```

The image size for a thumb is highly suspicious! Sadly I do not see the image-id on the log. Maybe with gdb?

**Comment by TurboGit** [comment]
Did you had a crash before?

**Comment by TurboGit** [comment]
As you are using current master... Do you remember you're last good version? Maybe you could bisect to find the culprit... I can only say that I have no crash on my side.

**Comment by jenshannoschwalm** [comment]
First suspicious thing is cl device memory.

**Comment by jenshannoschwalm** [comment]
Also a negative size and scale?

**Comment by difrkaguilar** [comment]
> Did you had a crash before?

I hat a crash before the last commit. Anyway I've to check again, It's an error from my side, I started as root and darktable works as a charm.

as root

![Screenshot from 2023-02-03 18-24-14](https://user-images.githubusercontent.com/67672868/216730785-f3f21c2a-8159-4ad8-936c-b68a50b4e693.png)

**Comment by difrkaguilar** [comment]
e4b2a98d0ccabdab224816e45c5953b4de261615

until this commit the app was working fine, but as I post I made an update last night and something had changed.

**Comment by jenshannoschwalm** [comment]
Some comments from my side
1. Are you sure your build was correct?
2. You have two large nvidia graphics cards, using pinned transfer will likely **degrade** performance as that mode uses much system memory too. (that's something i will fix)

**Comment by difrkaguilar** [comment]
> 1. Are you sure your build was correct?

I'm using the master in Fedora 37 from Suse repositories

https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

> 2\. You have two large nvidia graphics cards, using pinned transfer will likely **degrade** performance as that mode uses much system memory too. (that's something i will fix)

I'm tempted to remove one of my Nvidias :-)

> 3\. Any problems without opencl?

darktable --disable-opencl 

(darktable:38502): dbind-WARNING **: 19:04:31.028: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_1: Permission denied
[1]    38502 segmentation fault (core dumped)  darktable --disable-opencl

**Comment by gi-man** [comment]
For what is it worth, I'm on Fedora 37 KDE X11 with Nvidia 3060 and using master. I processed 19 images and exported without issues. I dont have the memory or transfer On.

**Comment by difrkaguilar** [comment]
The first error I got in the app was this.

> Could not find the attribute DigitalZoomRatio using the command: <exiftool -DigitalZoomRatio '/run/media/franklin/My Book/PHOTOGRAPHIC_DB/2023-02-01/_DSF7913.RAF'>

I was importing more than 3000 pictures JPG+RAW (RAF) dt imported all of them but later on the app started to crash.
Don't know if this is part of the same issue or not.

**Comment by gi-man** [comment]
Is it still crashing? I think you wrote it was resolved.

**Comment by difrkaguilar** [comment]
> Is it still crashing? I think you wrote it was resolved.

I made a backup and deleted the .config/darktable folder then dt start as new again. then put back the library.db and the darktablerc then deleted the last imported folder with all their files and I'm re-importing again, until now there isn't any crash, but the message importing those files still continue for every .RAF imported.

> Could not find the attribute DigitalZoomRatio using the command: <exiftool -DigitalZoomRatio '/run/media/franklin/My Book/PHOTOGRAPHIC_DB/2023-02-01/_DSF7913.RAF'>

I don't know any clean way to fix it, but I thing the issue was with the last imported files, after that dt crashed. Will check again after the import.

**Comment by difrkaguilar** [comment]
After the last things I made everything it's working fine, so I'm going to close this issue.
