### ISSUE TITLE
Tone equalizer is inverted if used after negadoctor

### ISSUE THREAD

**Issue by anvandaren** [darktable-org/darktable#13526]
**Introduction**
I scan film negatives with Vuescan as raw tif files, and use the Darktable module negadoctor to convert them to positives. After that I often use tone equalizer (especially on badly exposed or developed negatives). I've found that tone equalizer creates the mask and behaves as if the image was not yet inverted. So to darken an image I need to raise the curve, opposed to the expected. When the tone qualizer exposure mask i shown it is inverted, not as expected. Other modules such as levels do behave as expected.

**To Reproduce**
1. Import a raw scan of a negative.
2. Use the negadoctor module to invert the negative to a positive.
3. Select the tone equalizer module and raise the curve in the advanced tab.
4. The Image is darkened, not lightened as expected. 

**Expected behavior**
The tone equalizer should work on the image after inversion in negadoctor. This way the tone equalizer will behave as on other non inverted images even on raw scanned negatives.

**Screenshots**
Tone equalizer raised on a raw scanned negative:
![bild](https://user-images.githubusercontent.com/89592632/216762933-392780da-c861-4b6f-a31e-e80c8eda2d95.png)
Tone equalizer raised on the same negative but converted to positive by the scanning software:
![bild](https://user-images.githubusercontent.com/89592632/216762999-b466b9a0-a1ec-45b5-b2a1-ca0c96eeadea.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.2.0
* OS                : Linux - kernel 5.4.0-135-generic
* Linux - Distro    : Ubuntu 20.04
* Desktop           : I3

**Comment by TurboGit** [comment]
You may want to move tone equalizer above negadoctor module.

**Comment by anvandaren** [comment]
I was unable to upload the negative raw tif file. If you want me to convert it to another format for upload let me know.

**Comment by anvandaren** [comment]
@TurboGit  thank you for the quick reply!
The tone equalizer is above the negadoctor module. The workflow is:
1. Import raw tif.
2. Use negadoctor to invert.
3. Use tone equalizer for correction.

**Comment by TurboGit** [comment]
No, not by default, tone-equalizer come first:

![image](https://user-images.githubusercontent.com/467069/216763789-59e27812-ba0d-45d6-90ba-aebf65852c29.png)

You need to reorder the pipe to be:

![image](https://user-images.githubusercontent.com/467069/216763814-d99f1c71-01b0-4f05-bed4-0b29429d5730.png)

Or use the rgb-curve which is above.

**Comment by TurboGit** [comment]
See https://docs.darktable.org/usermanual/4.2/en/darkroom/pixelpipe/the-pixelpipe-and-module-order/#changing-module-order for more information.
