### ISSUE TITLE
Copy/paste of the history stack does not work on Windows

### ISSUE THREAD

**Issue by savchenko** [darktable-org/darktable#13531]
**To Reproduce**
1. Install latest release, v4.2.0 at the time of writing
2. Import several photos
3. Select a photo in the Lighttable view and press <kbd>Ctrl+c</kbd>
4. Darktable performs "zoom out" instead of "copy history.

**Expected behavior**
History is copied via <kbd>Ctrl+c</kbd> and pasted by <kbd>Ctrl+v</kbd> as per manual.

**Additional notes**
There were some suspicious shortcuts in settings. After removing them, pressing <kbd>Ctrl+c</kbd> yields this:
<img width="194" src="https://user-images.githubusercontent.com/300146/216795397-94610df1-aeed-4b0f-a65b-13bdd6ffab54.png">
I am using regular `en_AU.UTF-8` keyboard layout.

Trying to remap shortcuts manually, reveals that `ctrl+0xffffff` is triggered by _both_ <kbd>Ctrl+c</kbd> and <kbd>Ctrl+v</kbd>.

Additionally, tryiing to use this arguably broken key designation nets this:
<img width="214" src="https://user-images.githubusercontent.com/300146/216795684-e5a58a39-2c07-4dda-8342-b96ad45b1fec.png">

It's almost like all characters return `0xffffff` for no reason.

**Platform**

* darktable version : v4.2.0
* OS                : Windows 10 19044.2486
* Graphics card     : Radeon RX 6600 XT
* Graphics driver   : AMD v27.20.22016.2
* OpenCL installed  : Yes
* OpenCL activated  : Yes

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes, with v4.0.0.X**
 - Can you reproduce with a RAW or Jpeg or both? **RAW**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**

**Comment by parafin** [comment]
It’s not a bug, white balance isn’t copied by default, you must use selective copy-paste instead.
