### ISSUE TITLE
Color harmony discoverability issues

### ISSUE THREAD

**Issue by prokoudine** [darktable-org/darktable#13536]
Here is a discoverability issue I immediately stumbled upon when trying the color harmony GUI: I have the smallest height set for the entire histogram widget, I had no idea there are more modes until I saw the screenshot in the PR discussion :) So the user needs to know that they have to increase the height of the widget to gain access to all modes.

Overall, I'd expect to adjust the position of the guides by dragging them directly up/down/right/left by the outer part of the circular sector. If you embrace this approach (and I realize it's more complicated to implement), you gain the benefits of familiarity. Anyone proficient with graphics editors (bitmap and vector alike) is familiar with both rotating something in-place and Ctrl/Shift modifiers for rotation (enables 15° steps). The radii guides of the circular sector could be used to control the width.

That leaves the entire topic of being able to see all modes, I have no immediate suggestions for improving that, I'm afraid. Adding a button with a drop-down list (early implementation had a menu) sounds like an easy solution, but it doesn't account for the existing interaction complexity where you can keep harmony guides on at all times or only visible when hovering the widget.

**Comment by dterrahe** [comment]
#13523
https://github.com/darktable-org/darktable/pull/13507#issuecomment-1415872994

**Comment by dterrahe** [comment]
Now that https://github.com/darktable-org/darktable/pull/13523 has been merged and the tooltip should be visible over the whole vectorscope, please update your issue above or it could be confusing/easily dismissed. Thank you.

**Comment by prokoudine** [comment]
> Now that #13523 has been merged and the tooltip should be visible over the whole vectorscope, please update your issue above or it could be confusing/easily dismissed. Thank you.

Done
