### ISSUE TITLE
Black screen after Discard history

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#13543]
**Did you buy darktable from an application store ?**
OSB master

**Describe the bug/issue**
Using the Discard History from the lighttable yields a black image if:

1) denoise (profile) has an `auto apply preset` && `make preset auto set values depending on images`
2) if you discard history from the lighttable, then the image loads as a black image.
3) If you use the image history reset within darkroom, then the image shows correctly (denoise is applied)

**To Reproduce**
See above

**Expected behavior**
The image results should be the same if I reset via darkroom or lighttable discard history, correct?

**Screenshots**
![image](https://user-images.githubusercontent.com/97920861/216870426-76a18d8f-9f5d-45ce-8387-acd05534781d.png)

**Which commit introduced the error**
I'm assuming the recent po/auto-init

**Platform**
* darktable version : 4.3.0~git479.928115e7
* OS                : Fedora 37
* Linux - Distro    : Fedora 37 KDE X11 Nvidia 525.85.05

**Additional context**
It happens with and without OpenCL enabled

 - Can you reproduce with another darktable version(s)? Did not try
 - Can you reproduce with a RAW or Jpeg or both? Only tested Raw
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? See above
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? No

**Comment by jenshannoschwalm** [comment]
@gi-man please check again and possibly close, should be fixed on master

**Comment by gi-man** [comment]
It did not. Are you able to recreate? Should I be using both of the checkboxes above with this module?

I just noticed this when I use the Discard History:
![image](https://user-images.githubusercontent.com/97920861/218106855-6ffdb8de-40ab-42d7-a880-b9f64a9ebaf8.png)

When I reset via the darkroom history reset it changes to this:
![image](https://user-images.githubusercontent.com/97920861/218107265-2e41086d-d9d0-4da7-b0d0-1ce555bae8ad.png)


And I just discovered a new bug with displaying that info from the history. On some modules it now just shows: `shift+ctrl+scroll to change height`.  I will start a new Issue for this.

**Comment by gi-man** [comment]
@TurboGit Could this issue be a how the Auto Preset are being handled? It is the only way I can explain what I'm seeing. My desire is to turn on Denoise by default and for it to auto apply the settings per iso/camera. It does if I use the reset within darkroom, but not with the lightroom history discard or when I import new images.

**Comment by TurboGit** [comment]
@gi-man : Yes most probably due to my changes. Looks like the reload_defaults() in denoise profile is not setting the parameters in some cases.

**Comment by TurboGit** [comment]
As I thought, it was due to a wrong `reload_defaults() `implementation which was reloading only when GUI was present and not all parameters.

Please test fix #13662.

**Comment by gi-man** [comment]
The PR fixes this. Thanks.
