### ISSUE TITLE
OpenEXR Import/ Export with Layers in Darktable.

### ISSUE THREAD

**Issue by sventetzlaff** [darktable-org/darktable#13546]
Darktable currently only supports layer export with TIF and XCF. However, TIF is exported differently than XCF, sometimes as a pixel channel, sometimes as a real layer ... (In Gimp: Channel instead Layer with XCF. Layer (as Layer) with TIF.)

![Screenshot 2023-02-06 132342](https://user-images.githubusercontent.com/124562992/216922722-86618c2b-8fb7-447e-965f-dc80b59db622.jpg)
Channel instead Layer with XCF

![Screenshot 2023-02-06 141125](https://user-images.githubusercontent.com/124562992/216922581-9329790e-eb52-4deb-9688-6e637325cafa.jpg)
Layer (as Layer) with TIF

Actually, EXR has become the universal exchange format between Blender/ Gimp/ Davinci/ Affinity, unameit ... 

The advantages are obvious: Small file size (with the DWAA codec), 32bit float, layer AND channel, import and export to Davinci, Blender, Gimp, Darktable etc.pp.

I would be really pleased if there is a possibility in Darktable to output the masks as real layers in EXR. That would truly save a lot of work ...

thx!

**Comment by kmilos** [comment]
Do you perhaps have some more pointers, i.e. what actual feature of the OpenEXR format spec to use for the layers, a link to a sample EXR w/ layers, etc.?

**Comment by sventetzlaff** [comment]
Hello Milos. Yes, I can explain this in more detail. I suggest I make a short video (tomorrow morning) to explain where in the workflow this becomes important. Here is a video to give you the idea: https://youtu.be/-UjJqwwMJc8

DT already has layer exports via XCF (which is a dead end, just for Gimp) and via TIF, which is really outdated, clunky and not supported in Davinci, Unity and some other apps.

openEXR has many advantages over other file formats and is mainly used in the games, anime and film industries. In the field of images, it is used for HDR material. Channels and layers are the core functions of EXR.

What I would personally very much welcome would be the possibility to export the masks as layers (e.g. a white pixel layer) in EXR. Why actually? Layers in DT were used to modify "problematic" areas in some way. These areas are probably also important in further work steps. 

At the moment I have to paint the masks again and again ... Another point, I can bring the file back in DT slightly changed and use it again in Blender, Davinci, Unity - including all existing layers.

**Comment by kmilos** [comment]
Hi, the motivation is clear, so no need for the video. What I'm interested in is the technical nitty gritty - pointer in the OpenEXR spec or a sample from e.g. GIMP.

I'm also interested what works today (dt 4.2) already: in theory, the mask data is stored in the XMP, and you can include that in the EXR export (you'll need to check all the metadata boxes in the export preferences). Do they come back if you try to import the EXR w/ the XMP (but remove its sidecar first)?

Note that is in unlikely (i.e. not planned AFAIK) dt will support import of layers from other apps in any format in the near future.

**Comment by sventetzlaff** [comment]
Hello Milos, here some information about EXR.

DT exports EXR but without (mask) layers. This option is greyed out: 

> store masks
>     Store masks as layers in exported image. Only works for some image formats (currently TIFF and XCF).

https://docs.darktable.org/usermanual/development/en/module-reference/utility-modules/shared/export/

![Screenshot 2023-02-07 102932](https://user-images.githubusercontent.com/124562992/217229488-767890fa-e4ee-4b48-85a5-7b61b1afc735.jpg)

The openEXR-standard is by Industrial Light and Magic (ILM). OpenEXR is released under the BSD-3 license. Detailed infos here: https://github.com/AcademySoftwareFoundation/openexr

Here an EXR-layers example in Affinity (same in Gimp). The layer-name ~.RGBA means with alpha. You can also store without alpha, just ~.RGB

![affinity-Screenshot 2023-02-07 104210](https://user-images.githubusercontent.com/124562992/217232068-af17f2fc-0edf-4a8f-9f0c-4063c28edb00.jpg)

You can import this EXR in DaVinci (not TIF nor XCF). Each single layer is accessible. You can use those two layers and the background - just with one media_in.

![davinci-Screenshot 2023-02-07 104415](https://user-images.githubusercontent.com/124562992/217232466-caea6c81-d37c-42b3-8bd9-334b9d615b3b.jpg)

Please let me know whether I can provide any other information, files etc. to you? You can download the EXR-File here:  https://kathai.de/nextcloud/index.php/s/JaT48S7TWRLZN2c

bye Sven

**Comment by kmilos** [comment]
Thanks for the sample Sven, I'll take a look.

I am somewhat familiar w/ the OpenEXR format, but the layers are new. This gives me a clue though - I'll probably try to export dt masks as "dt_mask_foo.Y" (similar to TIFF, and limited to mono/luminance for start) when I get a chance... I hope you'll be able to build dt and test?

**Comment by sventetzlaff** [comment]
I run DT in Ubuntu(Laptop) and W11(Workstation). Not sure, but I guess I can build it on Ubuntu. If I successfully got a running version ... I'll test it _all night long_ 🤘

Thanks for your efforts!

**Comment by kmilos** [comment]
> Darktable currently only supports layer export with TIF and XCF. However, TIF is exported differently than XC

Btw, should we also change how XCF is exported, and use layers rather than channels for masks?

**Comment by 1div0** [comment]
@kmilos please check [tev](https://github.com/Tom94/tev).

Hvala.
