### ISSUE TITLE
histogram / preview image not fully prepared for translation

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#13553]
even the strings were translated the default text is displayed
![image](https://user-images.githubusercontent.com/39386816/217097120-9c7d2931-0976-441a-8caa-d0f34d109e42.png)

**To Reproduce**
1. Go to darkroom
2. mouseover preview image or histogram
3. See error

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.3.0+504~g6824a3d0b-dirty (contains updated german translation
* OS                : macOS

**Comment by dterrahe** [comment]
> even the strings were translated the default text is displayed

We don't normally split multi-line text blocks into individual lines for translation, so in the reorganisation of the tooltips they were merged back. If you feel strongly this should not have been done you can submit an amendment to #13523 to split them again; `dt_util_dstrcat` supports the printf syntax.

**Comment by victoryforce** [comment]
> even the strings were translated the default text is displayed

It looks like the darktable.pot to which you updated the translation was generated albeit later in time than the commits that made changes to the texts from the histogram module, but at an older state of the build tree.

Simply put, the reason is that this darktable.pot is outdated and when it is updated, there will be no problems with the translation not being displayed.

**Comment by dterrahe** [comment]
> Fact here those four strings could be found in some other context as generic and so reused. I'll do the change back.

Sorry for causing you more work. I _had_ checked and those texts were actually not _that_ generic (they don't seem to occur anywhere else) so I thought translating multiple separate strings would cause everybody more work than one combined one. Again apologies for getting that wrong.

**Comment by TurboGit** [comment]
> Again apologies for getting that wrong.

No need to apologies really.
