### ISSUE TITLE
Collections and capture date film strip in lighttable not working correctly

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#13552]
Simply put, choosing the capture date "columns" in the filmstrip does not display images from that period even when clicked.

If this isn't a bug, then the behaviour is extremely confusing as suddenly many images from my collection just vanish without any reason and do not appear when I select all columns in the film strip.

The only way for them to reappear is to click on "clear this role" in capture date.

Arch Lin
DT 4.2

**Comment by ptilopteri** [comment]
care to provide any of the requested information and description about
your system?  it is for you to provide information that will make it possible
for the developers to assist you, not to have to ask you for more information.

**Comment by maboleth** [comment]
Not sure what you mean but here is some basic ones

Ryzen 7 CPU, 32GB RAM
AMD 5500XT 8gb video card
OpenCL enabled AMDGPU official proprietary CL drivers
Mesa Radeon GPU drivers

Arch Linux, DT 4.2 newest release version.

**Comment by maboleth** [comment]
Alright I have managed to overcome this issue by deleting the film roll role. For some reason having a film roll and capture date together makes the film strip not working at all.

Still not sure if this a bug or not?

**Comment by AlicVB** [comment]
tbh, I'm absolutely not sure of what you mean here (columns ?, filmstrip ?, filmroll role ?) Maybe you can show us a labelled screenshot or something else ?

**Comment by maboleth** [comment]
Alright, 'columns' was confusing I didn't know how to name it properly, sorry.
![Untitled](https://user-images.githubusercontent.com/2467520/217236586-ea6e78aa-335c-4a4e-baff-b8631f8878d7.png)

I called "filmstrip" the bottom part with "columns" that are those date spikes.

"Filmroll role" is the name in Collections.

Steps to reproduce:

1. Have a Capture Date in Collections. - The date spikes are normal and working.
2. Add "Filmroll" role in collections.
3. Now Capture date is changed to Filmroll
4. If you pick any shown directory in the collections all is working.
5. But if you go to the "film strip - date spikes" and try so elect any date it's not working anymore
6. Notice it's all messed up and the way for it to work again is to "clear the role" of Filmroll and get back to Capture Date.

**Comment by ralfbrown** [comment]
Working as designed - clicking or swiping on the timeline **adds** a restriction rule to the current collection criteria.  If you look at the Collections module, you will see that there is now a line for both the film roll you had selected and a capture date.  The upside-down-U icon at the right of the filmroll line is an intersection operator - only images matching *both* criteria will be shown.

The filmstrip shows spikes for all images in your library, with those selected by the current collection rules highlighted with a different shade of gray (most noticeable when only some of the images for a month are in the current collection).  So if you swipe across spikes that don't have any highlighting, you are asking to show images from a date range which is not present in the currentr collection.
