### ISSUE TITLE
Mask manager module: right-click on a children of a group close it instead of displaying menu

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13551]
**Describe the bug/issue**

Right-click on a children of a group, close the group instead of display menu.

**To Reproduce**
1. Be sure to have at least one drawn forms inside a group in mask manager module on darkroom module, left panel
2. Open group by clicking on the arrow
3. Right-click on a children of the group to display menu
4. See that group is closed and no menu displayed

If you click again (do step 2 and 3) just after, group will not close and menu is displayed as expected, but never on first try. This issue only happen on forms inside a group.

**Expected behavior**

Having menu on first right-click of a children.

**Platform**

* darktable version : last master (but seems also on darktable 4.2.0)

**Comment by TurboGit** [comment]
Should be fixed now.
