### ISSUE TITLE
Make Darktable use no Title bar (borderless)

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#13555]
![Untitled](https://user-images.githubusercontent.com/2467520/217104145-d5a1b0cb-5c64-4645-8c96-dbebd81e5575.png)

This not only looks a bit dated, but also wastes rather limited height of the screen.

If not a permanent solution, there should be an option in Settings to make the Title optional, with a way to have the Title buttons incorporated in DT border.

Sort of what Siril already does by default:

![Untitled3](https://user-images.githubusercontent.com/2467520/217104840-e1de8b98-3958-481f-9eb1-0c9497458077.png)

I know there's a Full Screen mode, but that also hides the panel bar.

**Comment by dterrahe** [comment]
> with a way to have the Title buttons incorporated in DT border.

From what I've seen on the web, drawing window buttons yourself (client side decorations) opens a whole can of worms where every OS and WM requires different workarounds. Maybe I'm wrong about that so if someone with expertise in this area wants to tackle this, feel free. It is not something I feel strongly enough about to spend time on it. And we don't have enough people on the different platforms to sufficient testing as it is.

**Comment by TurboGit** [comment]
> This not only looks a bit dated, but also wastes rather limited height of the screen.

Just hit F11 and you have dt full-screen, no decoration no space wasted. To quit just press ctrl+q. As darktable does not have a menu bar, I don't see why we should do more than what is already possible.

**Comment by maboleth** [comment]
> > This not only looks a bit dated, but also wastes rather limited height of the screen.
> 
> Just hit F11 and you have dt full-screen, no decoration no space wasted. To quit just press ctrl+q. As darktable does not have a menu bar, I don't see why we should do more than what is already possible.

I do, but that also hides a panel bar (taskbar) and makes DT sort of one-and-only program on the screen.

**Comment by parafin** [comment]
Some WMs allow to hide decorations of any window, e.g. in openbox you can add a shortcut for that.

**Comment by dterrahe** [comment]
> Maybe a consultation with their devs and seeing their source code could help here as well?

Yes, thanks for offering! Please post a link to the commit that introduced the feature in Siril when you find out. If it is limited and generic and didn't lead to a host of follow up bugfixes, I might be willing to spend a minimum amount of time on this.

> As a compromise

It is great that you are willing to compromise on your original demand. Thanks again!

**Comment by maboleth** [comment]
> > Maybe a consultation with their devs and seeing their source code could help here as well?
> 
> Yes, thanks for offering! Please post a link to the commit that introduced the feature in Siril when you find out. If it is limited and generic and didn't lead to a host of follow up bugfixes, I might be willing to spend a minimum amount of time on this.
> 
> > As a compromise
> 
> It is great that you are willing to compromise on your original demand. Thanks again!

Did I notice a sarcastic tone in your words? I apologize if I was wrong.
But there should be none really. 
I'm no programmer. So obviously I cannot help you in this directly, but I pointed out the the open source program that I know - Siril. 

If it's impossible to do what I suggested, fine. You can say it nicely, or not say anything at all. I did try my best to ask for this feature or UI.

If anything, users should be encouraged to post bugs and features, or at least to discuss them here, right? They also invest their own time doing it, as is the spirit of the open source. Then please don't make this place look uninviting with a talk like that. Thank you.

**Comment by dterrahe** [comment]
> So obviously I cannot help you in this directly

What you seem to suggest is to reach out to the Siril project (which I know _nothing_ about) and ask them how they introduced a feature. This doesn't sound like a programming task to me. You may not be as helpless as you think you are. But if it is too much trouble, not a problem; there is a "close" button on this issue.

**Comment by maboleth** [comment]
Sorry if you're having a bad day, I will not comment further.

I asked what you suggested before you edited your last message and here's what Siril Dev told me.

_I'm trying to assist guys that make Darktable RAW converter to use no Title bar.
I've noticed Siril uses GTK3 and Title bar incorporates the buttons and menus, inline. Together with Min/Max/Close buttons.
Can you possibly point me out in the code where that part is, so I could show them? Thanks._

Hello.

We are using the GtkHeaderBar API: https://developer-old.gnome.org/gtk3/stable/GtkHeaderBar.html

I don't know whether you can or cannot use what he suggested, but I will remove myself out of this with that kind of attitude.

**Comment by dterrahe** [comment]
Thank you.

For others; `GtkHeaderBar` is a possible base for a replacement header (i.e. the area below the window title bar, with the hinter area in it) which can be toggled off. It could be easier for us to simply add a "close" button to what we have, but when it is hidden, the user would have to remember ctrl+Q.

The real magic happens in `gtk_window_set_titlebar`. A one line change in `_ui_init_panel_top` from
`gtk_grid_attach(GTK_GRID(container), widget, 1, 0, 3, 1);`
to
`gtk_window_set_titlebar(GTK_WINDOW(ui->main_window), ui->panels[DT_UI_PANEL_TOP]);`
switches off the normal window header and double-clicking on the hinter (if it is visible) will toggle _maximize_.
But since the top bar is now removed from the grid hierarchy, some of the CSS coding for it is broken and I sometimes noticed black instead of grey background.
Also, this call needs to happen _before_ the window gets realized, so it doesn't seem to be an option you can switch on and off at will (which the hierarchy problem I mentioned above would have complicated anyway). We'd have to switch for everybody (or have a command line switch).
```
static void _ui_init_panel_top(dt_ui_t *ui, GtkWidget *container)
{
  GtkWidget *widget;

  /* create the panel box */
  ui->panels[DT_UI_PANEL_TOP] = widget = gtk_header_bar_new();
  gtk_header_bar_set_show_close_button(GTK_HEADER_BAR(widget), TRUE);
  gtk_header_bar_set_decoration_layout(GTK_HEADER_BAR(widget),":minimize,maximize,close");
  gtk_window_set_titlebar(GTK_WINDOW(ui->main_window), ui->panels[DT_UI_PANEL_TOP]);
  gtk_widget_set_name(widget, "top-hinter");

  /* add container for top left */
  ui->containers[DT_UI_CONTAINER_PANEL_TOP_LEFT] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_header_bar_pack_start (GTK_HEADER_BAR(widget), ui->containers[DT_UI_CONTAINER_PANEL_TOP_LEFT]);

  /* add container for top center */
  ui->containers[DT_UI_CONTAINER_PANEL_TOP_CENTER] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_header_bar_pack_start(GTK_HEADER_BAR(widget), ui->containers[DT_UI_CONTAINER_PANEL_TOP_CENTER]);

  /* add container for top right */
  ui->containers[DT_UI_CONTAINER_PANEL_TOP_RIGHT] = gtk_box_new(GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_header_bar_pack_end(GTK_HEADER_BAR(widget), ui->containers[DT_UI_CONTAINER_PANEL_TOP_RIGHT]);
}
```
Gives the below on Debian KDE. Notice the alignment of the added buttons and the fact that I had to force them to appear there with `gtk_header_bar_set_decoration_layout` because otherwise a (second) darktable icon will be shown on the left. So if somebody instructed their wm to put the buttons somewhere else, this probably would not conform.
![image](https://user-images.githubusercontent.com/1549490/217281719-7af2bea2-1ee5-4b79-b43d-903a0e31552e.png)

**Comment by parafin** [comment]
Major point here would be to ensure it works as expected on macOS and Windows too.

**Comment by gi-man** [comment]
I really dont like the idea of moving this to the title bar. 

But, in the interest of saving vertical space, removing the current logo and navigation buttons does have some benefits. It will also start to make dt not look like Lightroom. 

Suggestion / thinking out loud (typing):
Create a module in the left hand side above Import with Logo and buttons for navigation (L, D, M, P, S, T). You can collapse or expand the module if you want. It uses the similar module IU in the rest of the system.

**Comment by dterrahe** [comment]
> ensure it works as expected on macOS and Windows too.

Quick test on Win10 shows just the same problems mentioned above. The min/max/close buttons are not just aligned wrong (probably fixable) but also look very different from the standard windows buttons. Suspect people will hate that, but I assume Siril has the same experience so they could be asked about their user complaints.

My main worry would be newbies pressing ctrl+h by mistake (maybe looking for just "h"), lose the header and now not being able to close the application. If you don't know ctrl+q or Alt+F4 you'll be stuck.

> removing the current logo and navigation buttons does have some benefits

You mean like Ctrl+H or something else?

> It uses the similar module IU in the rest of the system.

You mean with a non-removable module header?

**Comment by dterrahe** [comment]
> Quick test on Win10 shows just the same problems mentioned above.

Oh, I seem not to be able to grab the window edges anymore to resize it (when not maximized). This halts my experimentation for now.

**Comment by gi-man** [comment]
> You mean like Ctrl+H or something else?

Yes like Crtl+H or clicking on the top arrow. Today, you need to do the Ctrl+H and then click on the lighttable or darkroom or other and then do Ctrl+H again to hide it. OR you use keyboard L, or D.  

But something else... I think placing that content in a non removable module so it remains visible and you can navigate without using the keyboard (just using mouse clicks). I personally prefer not using the keyboard keys other than ctrl/shift/alt + mouse click/mouse scroll. I keep the left hand on those keys.

**Comment by wpferguson** [comment]
@maboleth most of the devs are not native english speakers, so don't read too much into their replys.

@gl-man a module  would be quick and easy to code up in lua, except for maybe the logo.

**Comment by dterrahe** [comment]
> Today, you need to do the Ctrl+H and then click on the lighttable or darkroom or other and then do Ctrl+H again to hide it. OR you use keyboard L, or D.

Or you use double-left-click (to switch between L&D)

**Comment by wpferguson** [comment]
They would just have to go to script_manager and turn it on.  But we could possibly just watch for an event when the title bar is hidden and turn it on autmoatically

**Comment by dterrahe** [comment]
> turn it on automatically

_and_ make it very easy to disable that potentially very annoying behaviour :-)

**Comment by gi-man** [comment]
I dont think lua is the right approach here. I was thinking on new users and how to avoid the gray area that takes vertical space in the monitor, while keeping it simple.

**Comment by dterrahe** [comment]
The gray area is the hinter? Which tries to provide useful information to the new user (especially when using masks; admittedly it is not used as often as it could(/should?) be).

**Comment by gi-man** [comment]
This gray area. Of course very different in a 27-32in monitor vs a 15in laptop.
![image](https://user-images.githubusercontent.com/97920861/217334209-567eb03c-6daa-4b27-9652-60d949ba731b.png)

**Comment by ptilopteri** [comment]
> This gray area. Of course very different in a 27-32in monitor vs a 15in laptop. ![image](https://user-images.githubusercontent.com/97920861/217334209-567eb03c-6daa-4b27-9652-60d949ba731b.png)

<ctrl><shift><t> will cycle thru hiding and displaying various parts of the "Title" area.  The area you describe 
may be completely hidden

will/can supply screen shot if necessary

**Comment by maboleth** [comment]
> Quick test on Win10 shows just the same problems mentioned above. The min/max/close buttons are not just aligned wrong (probably fixable) but also look very different from the standard windows buttons. Suspect people will hate that, but I assume Siril has the same experience so they could be asked about their user complaints.

Siril Dev further said:
Siril has same look and feel on the 3 main OSs. But it looks very different from the standard windows/macOS buttons.
And for me, this not an issue :).

And I can confirm, it looks like a GTK app on both Windows and Linux and like him, never found this to be an issue. Not to mention that various official Microsoft apps vary a lot in the look and windows style.

> My main worry would be newbies pressing ctrl+h by mistake (maybe looking for just "h"), lose the header and now not being able to close the application. If you don't know ctrl+q or Alt+F4 you'll be stuck.

I wouldn't remove the logo though, unless it's needed. But what you did IMO looks great, considering it's a sketch of what it would look like without a bar.

You shouldn't worry about users hitting CTRL-H or the arrow. Yes, they would lose min/max/close buttons, but so would lighttable/darkroom/other menu as well, in the same fashion. It's a conscious decision to save some space, thinking - there's no bar, I lost buttons and menus, but I saved some space. It wouldn't be like the three buttons somehow vanished out of the blue or anything like that.

**Comment by wpferguson** [comment]
> I wouldn't remove the logo though, unless it's needed. But what you did IMO looks great, considering it's a sketch of what it would look like without a bar.

The logo is also the about button and gives you the version number of darktable that you are running, which is needed if you're submitting an issue.

**Comment by MStraeten** [comment]
> it looks like a GTK app on both Windows and Linux and like him, never found this to be an issue. Not to mention that various official Microsoft apps vary a lot in the look and windows style.

but just because there’re tools around that doesn’t care a lot on appealing GUI there’s no reason why darktable should do the same. There was a lot of effort spend to implement a proper GUI so it definitely is an issue for those implementing that stuff for ‚their’ tool.
If the GUI isn’t important for you, feel free to use the commandline interface saving a lot of more space ;)

**Comment by maboleth** [comment]
> > it looks like a GTK app on both Windows and Linux and like him, never found this to be an issue. Not to mention that various official Microsoft apps vary a lot in the look and windows style.
> 
> but just because there’re tools around that doesn’t care a lot on appealing GUI there’s no reason why darktable should do the same. There was a lot of effort spend to implement a proper GUI so it definitely is an issue for those implementing that stuff for ‚their’ tool. If the GUI isn’t important for you, feel free to use the commandline interface saving a lot of more space ;)

Dterrahe specifically asked and commented whether Siril had user complaints about its different looks and to that I replied what their Dev said to me. 
But you know what, it doesn't matter.
