### ISSUE TITLE
Sony 11 - 18mm F/4.5-5.6 SAL1118 -- Lens correction profile

### ISSUE THREAD

**Issue by gibrate1** [darktable-org/darktable#13560]
**Is your feature request related to a problem? Please describe.**

Yes, this is a super wide lens and it would be much appreciated to have a one-click lens distortion fix

**Describe the solution you'd like**

I would like lens correction profiles added for the 'Sony 11 - 18mm F/4.5-5.6 SAL1118' Lens.

**Alternatives**

Can't think of any alternatives.

**Additional context**

Link to sample photos;
https://drive.google.com/drive/folders/1-tJ5W4CmCBvrSVRiFan3FNOKC6CgBFOh?usp=sharing

**Comment by kmilos** [comment]
Wrong address 😉 

Please head over to https://lensfun.github.io/ which darktable (and many other apps) uses for lens profiles.
