### ISSUE TITLE
Set size option not saved when creating export preset

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#13567]
I presume this is a bug and not a design feature, but when I create a preset for export module if I want to set the size by scale this information is not saved with the preset. Then when I select a preset the set size option remains the same as my last export rather than what I would have desired to be saved as part of the preset. I am using DT 4.3.0 +478 on a Windows computer. 

The ability to save the set size in the global options would be beneficial to many users who need to scale their output for specific uses such as web posting. Thanks for taking the time to consider this issue and the time to develop such a great program.

**Comment by Dakes** [comment]
+1 This is an issue for me as well. Would be awesome, if it would get fixed. 
I use version 4.2.1 on Linux.
