### ISSUE TITLE
copy/paste history doesn't respect custom module order

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#13564]
**Describe the bug/issue**

When a history stack with a custom order is copied from one image and pasted to another the module order is not respected.

Copied from:

![copied](https://user-images.githubusercontent.com/1634891/217371296-56369092-dc2b-4047-8883-dc7a8bc8df92.jpg)

Pasted result:

![pasted](https://user-images.githubusercontent.com/1634891/217371474-29e78dec-4e15-4c85-9917-4a4f1095ed92.jpg)

**To Reproduce**

1. Open a image in darkroom view
2. Create multiple instances of the diffuse and sharpen module
3. Move them to different positions in the module order
4. Copy the hisotry stack
5. Open another image in darkroom view
6. Paste the history stack
7. Compare the stacks

**Expected behavior**

Module order remains the same

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable 4.3.0+524~g27d91012c
* OS                : Linux 5.15.0-58-generic #64-Ubuntu SMP
* Linux - Distro    : Ubuntu 22.04
* Memory            :  32G
* Graphics card     : Nvidia 3070ti
* Graphics driver   : Nvidia 525.78
* OpenCL installed  :  Yes
* OpenCL activated  :  Yes
* Xorg              :  Yes
* Desktop           :  Gnome
* GTK+              : 3.24.33
* gcc               :  11.3.0
* cflags            : default
* CMAKE_BUILD_TYPE  : RelWithDebInfo

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version 4.2.0**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

**Comment by TurboGit** [comment]
> * Can you reproduce with another darktable version(s)? **yes with version 4.2.0**

So at least not a regression due to recent changes. I think this has never worked, don't remember all the details though.

**Comment by TurboGit** [comment]
Another question is that in _append_ or _overwrite_ mode. I think it is only supposed to work on _overwrite_ mode.

**Comment by wpferguson** [comment]
I don't really know.  I believe that it was in over write.  I did it using control-c to copy and control-v to paste.  If it takes the setting from the history stack module in lighttable, then it was in append mode.

**Comment by TurboGit** [comment]
Yes, it takes the setting from the lighttable.

**Comment by wpferguson** [comment]
I'll test after setting it to overwrite and see what happens :smiley:

**Comment by wpferguson** [comment]
overwrite mode respects order.  

Should there even be an append mode when copying from darkroom?  IMHO append mode only makes sense when you're pasting a partial history, i.e. you did a selective copy and/or a selective paste.

**Comment by TurboGit** [comment]
> overwrite mode respects order.

That's what I expected indeed.

> Should there even be an append mode when copying from darkroom? IMHO append mode only makes sense when you're pasting a partial history, i.e. you did a selective copy and/or a selective paste.

In fact the question is should we have an `append` mode when doing a full copy/paste and not only from darkroom.

**Comment by wpferguson** [comment]
I agree

**Comment by wpferguson** [comment]
Works in overwrite mode as it should, and the question of append mode is now in the above.
