### ISSUE TITLE
Noise profile for Fujifilm GFX100s

### ISSUE THREAD

**Issue by nwinspeare** [darktable-org/darktable#13573]
For noise profiles, please also attach the entire archive with `.pdf` plots.
Hello, here is a profile I made for the Fujifilm GFX100s. Tested it on some shots and it works fine.
Hope it is good enough for you,
Regards and thanks for all your work,
Nicolas Winspeare
[darktable-noiseprofile-20230208.tar.gz](https://github.com/darktable-org/darktable/files/10686848/darktable-noiseprofile-20230208.tar.gz)

**Comment by nwinspeare** [comment]
Sorry, I was in MS+ES and they didn't appear ! Issue corrected.
[darktable-noiseprofile-20230210.tar.gz](https://github.com/darktable-org/darktable/files/10708061/darktable-noiseprofile-20230210.tar.gz)
Here is a noise profile for the Fuji X-H2s
[darktable-noiseprofile-20230210.tar.gz](https://github.com/darktable-org/darktable/files/10708069/darktable-noiseprofile-20230210.tar.gz)

**Comment by rawfiner** [comment]
Thank you
We already have X-H2s: https://github.com/darktable-org/darktable/pull/13594
