### ISSUE TITLE
RFC: redesign the copy/paste of full history

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13578]
### Problem

When copy/paste a whole history and if the lighttable mode is set to **append** in `history stack` module the history stack is not preserving the proper module order.

There is no real solution around that, when merging the history into an already existing history stack it is not possible to ensure that modules will be at the right orders because some identical are anyway already on the destination history stack.

This comes from #13564.

### Question

Is copy/paste full history should be supported? Has this any meaning anyway?

### Proposed solution

When a full copy/paste is done **force the overwrite** mode.

As we also have now a way to copy/paste module with proper default based on actual images information (like lens, color-calibration...) we could certainly revisit the list of unsafe module that are not copied today.

The list of unsafe to copy module is:

- flip
- gamma
- lens
- mask_manager
- rawprepare
- rotatepixels
- scalepixels
- temperature

Among them I see the following that we can now copy:

- lens
- rawprepare
- temperature

And maybe also:

- flip

**Comment by wpferguson** [comment]
@TurboGit, you beat me to it :smiley:

**Comment by ralfbrown** [comment]
I'd be OK with forced overwrite mode when *both* copy and paste operations are non-selective, and left at current mode if either or both is selective.

I frequently will do a selective copy of just one or two modules, then a full paste of those settings as I move through the following photos (first deciding whether or not to apply them to each image).  Having to do a selective paste each time would be a definite drag.
