### ISSUE TITLE
dt 4.2.0 duplicate manager showing love to vignette module

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#13582]
Hi devs,
I was just going back through some really old photos, and reprocessing for the first time since I first started using darktable.
And those old edits quite often included the vignette module.
Rather than throw away my old edits, I'm now getting in the habit of creating a duplicate/original, and creating a new processed version (so I can see how my processing changes over time).
But, here's the issue. When I click on the 'original' button in Duplicate Manager, it creates a new version (as you'd expect), but the new version always includes the vignette module (even if the original processed version DID NOT include the vignette module).

Specs:
dt version 4.2.0
linux mint 21/cinnamon 5.4.12
AMD Ryzen 7 2700x
32GB RAM
GeForce GTX3070

**Comment by brucewilliamsphotography** [comment]
OK, I'll confess it's been a looooong time since I played with auto-applied presets.
How do I check that again?

**Comment by Nilvus** [comment]
On the menu of the module, you can see which presets you have. You could then choose it, then go back on the menu and you will have edit preset option for preset selected. You could also go on darktable preferences menu then presets tab.

**Comment by brucewilliamsphotography** [comment]
I checked my vignette module. I have one preset, but it is not set to
auto-apply to any images. When I look in preferences/presets/vignette, all
fields to the right of the preset name simply contain a % sign, but no
values. The icon in the left-most (unnamed) column shows an icon which
looks like a half-full battery. Not sure what that is meant to signify.

**Comment by TurboGit** [comment]
> When I look in preferences/presets/vignette, all fields to the right of the preset name simply contain a % sign, but no values.

And the last field on the far right "auto" is empty?



> The icon in the left-most (unnamed) column shows an icon which looks like a half-full battery. Not sure what that is meant to signify.
> [](#)

It's a lock meaning that this is a write-only presets that is built-in darktable and can't be removed.

So, are you saying that there is not a single preset for vignetting that has no lock?

That's becoming very puzzling... But we will sort this out :)

**Comment by brucewilliamsphotography** [comment]
Nope, no auto flag.
And no, that is the only preset for the vignette module.
