### ISSUE TITLE
RFC: Possibly improve inpaint opposed highlights reconstruction performance

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#13598]
**Topic** We have "inpaint opposed" as the new default for highlights reconstruction, it's performance is pretty good right now but could be further improved.

**Rationale**
In very short, processing the algo includes two major steps
1. calculate chroma correction data, this has to read all image data and includes some mophological operation
2. calculate corrected data at highlighted areas.

Both steps take roughly equally cpu/gpu cycles.

The data calculated in step 1 are **constant** for the image (not fully true), yet atm they are calculated every time we process the image.

**Option to discuss**
1. process the chroma correction just once - while in darkroom - to avoid recalculating it
2. keep the processed data in the parameter struct
3. Step 2 requires an **addition to history** 
4. have roughly double performance of the module since then

I have this running since a while, there would be two downsides to accept
1. The additional history entry, please understand this is just added **once** (or after changing temperature or rawprepare data)
2. bump module version once to keep the chroma correction data (4 floats, this is just mentioned here bot not relevant)

**Alternatives**
Accecept what we have

**Comment by ralfbrown** [comment]
If I understand correctly, the chroma correction data only changes if the data being sent to HLR changes, e.g. by changing parameters in an upstream module like legacy WB or raw white/black point?  In that case, you'd probably want to store the operations hash (as used by the pixpipe cache) to detect parameter changes to properly handle situations such as a user mass-pasting history to multiple images.

**Comment by jenshannoschwalm** [comment]
> If I understand correctly, the chroma correction data only changes if the data being sent to HLR changes, e.g. by changing parameters in an upstream module like legacy WB or raw white/black point? In that case, you'd probably want to store the operations hash (as used by the pixpipe cache) to detect parameter changes to properly handle situations such as a user mass-pasting history to multiple images.

Sure :-)

**Comment by dterrahe** [comment]
> * process the chroma correction just once - while in darkroom - to avoid recalculating it

I assume this also needs to be done when run from CLI (i.e. this is not a gui only thing)?

> * understand this is just added **once** (or after changing temperature or rawprepare data)

Will every change in the white balance module generate 2 history items? Will that make history explode quickly (normally changes within the same module are merged)?

How will this work when adding highlight reconstruction to a style or copy/paste? Would this use @TurboGit's recent auto-init work? (which, tbh, I haven't looked at enough to understand yet). If the user were required to select the "reset" button for this module, I'm not sure they would understand this would be needed (since no visible impact on module gui).

If the operations hash also stores a hash for the image, I imagine this would automatically trigger a recalc when copied to a new one. But would that hash be constant across reloads? Otherwise you might as well put this in a separate "chroma correction" cache (and not store it in the image history). That would still require 1 full calc after each load, but not after subsequent recalcs. I'm not sure if you're only trying to avoid the latter or also the former.

**Comment by jenshannoschwalm** [comment]
It's not as difficult to handle.

The struct has 4 floats in addition
1. 3 of them are possibly already calculated correction data
2. one is a "magic"

This "magic" is calculated from a) the clip threshold in hlr b) white&blackpoint from rawprepare and c) the 3 temperature coefficients.

The algorithms goes: do as we do now **or** use the precalculated data **only** if the magic is correct, this decision is taken at runtime



> Will every change in the white balance module generate 2 history items? Will that make history explode quickly (normally changes within the same module are merged)?

Yes, two history items if temperature or rawprepare white/black points are changed. That would exactly be the downside of this approach and thats the reason because i wanted your opinion before doing a pr.

**Comment by dterrahe** [comment]
You would generate a new history item in the pipe _while_ you are currently processing it? And this would then change the hash? So impact the cache? I'm just worried that this will break a lot of assumptions in the code.

And it would generate 50 new history items while you drag the temperature slider.

I could see you building a small local cache _within_ the module itself just for those 3 floats indexed by the magic. But of course that wouldn't carry across saves, so if your mean goal is to make initial load faster, this wouldn't help.

But I'm not an expert on the pipe and caching stuff (and that's phrasing it mildly) so my understanding may be way off. I'd just advice against implementing something small quickly and then spending months fixing stuff (and growing the complexity all the while). We do too much of that imho.

**Comment by jenshannoschwalm** [comment]
Thanks for discussing this.

As a almost never use the temperature module myself i just ignored the **amount** of history stack groth. Indeed a no go.

No problem, i used an internal cache for a while and that worked perfectly while in darkroom ... will go for that.
