### ISSUE TITLE
GUI glitch: histogram not correct when duplicating RGB-Curve module 

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#13595]
**Describe the bug/issue**

When duplicating an instance of RGB Curve which has "Compensate middle gray" activated, the histogram in the new instance is wrong until "Compensate middle gray" is unticked / ticked again.

**To Reproduce**
1. open "RGB curve"
2. Click on "Compensate middle gray"
3. Draw some curve
4. duplicate instance

**Screenshots**

![darktableglitch](https://user-images.githubusercontent.com/57685590/217945728-abea2e4d-8ba4-40a5-8d3e-0a03d82ec850.jpg)

**Platform**

* darktable version : 4.2.0
* OS                : Win 10 / 64
* Memory            : 16 gb 
* Graphics card     :  intel
* Graphics driver   : 
* OpenCL installed  :  yes
* OpenCL activated  :  no

**Comment by TurboGit** [comment]
I believe this has been fixed Jan 16 : f62c9b258a7403a8723808f209bd833a4202b97d

The fix will be part of 4.2.1.
