### ISSUE TITLE
RFC: minor inconsistency for focus detection

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13597]
There is a mode to view a preview with & without the "focus" area.

For preview we have a single shortcut with 2 "elements" to select with or without focus detection

For sticky we have two shortcuts:

- toggle preview mode
- toggle preview mode with focus detection

Maybe worth make this as the standard (non sticky) preview?

**Comment by TurboGit** [comment]
@dterrahe : You may want to comment on this? I've opened this has I have been looking for the non sticky preview with focus detection for some time and was even starting creating an issue about this. Then I found this sub-mode (elements) after starting darktable and a fresh config and seen that the shortcut was present. So confusing to me :)

**Comment by dterrahe** [comment]
Please have a look if #13606 is a move in the right direction...
