### ISSUE TITLE
Enable "not"-option in presets

### ISSUE THREAD

**Issue by wwwFrank** [darktable-org/darktable#13600]
In "**presets**" with "**auto apply**" it may be usefull to have the option to negate (invert, "**not**"-option) some filter-parameter (_model, maker, lens_) to catch all cases with a single preset.

Example: 
Use the "lens-correction" for all raw-Files but **NOT** for **lens** = "_Olympus M.Zuiko Digital ED 8mm F1.8 Fisheye Pro_".
A fisheye has to keep it's distortion to be a fisheye.

Actual I need two presets to catch this case:
Use lens-correction for 
1. focal length from 9 to 1000 mm 
and 
2. focal length = 8 mm and lens = "OLYMPUS M.8-25mm F4.0" (not an fisheye).

I use Darktable 4.2.0 from ppa.launchpadcontent.net/ubuntuhandbook1/darktable/ on Ubuntu Linux 22/04 LTS.

**Comment by Nilvus** [comment]
On actual master (so for 4.4 release), we already have preset that cuold be auto initialize depending on camera setting. It's not a "not" condition but it should fulfill what you ask for. See: https://github.com/darktable-org/darktable/pull/13432 by applying preset depending on the RAW.
