### ISSUE TITLE
Store applied style name(s) in XMP file

### ISSUE THREAD

**Issue by kanwarplaha** [darktable-org/darktable#13608]
**Is your feature request related to a problem? Please describe.**

I have several styles that I apply to the photos, often multiple. However, this information is lost when the same edited image is retrieved later. As of now, I have to remember and add the applied styles in metadata editor. This does not scale and it cumbersome. Same with tags.

**Describe the solution you'd like**

Applied styles be added/stored in XMP file to allow recall of what styles caused a particular look of an image from the past.

**Alternatives**

Metadata editor - works but does not scale
Tagging - same as metadata editor

**Additional context**

None.

**Comment by pehar1** [comment]
Tags are already saved in xmp sidecar files. Saving style names IMO is not a good idea. In most cases styles represent only the starting point for further modifications and many modules can be applied subsequently, so the look may be very different.

**Comment by kanwarplaha** [comment]
Thanks. Can we then have each style automatically saved as a tag as well,
either on import or when applied to an image? That will make it easier than
creating a new tag manually?

**Comment by pehar1** [comment]
The xmp sidecar file contains the full history (all modules with all settings). Adding style names means adding redundand information (best case) or inconsistent information (if module parameters have been changed afterwards). Also styles can be modified or even deleted after you applied them. In the latter case the stylename entry would point to something which does not exist.
