### ISSUE TITLE
Improvements for new "auto-init preset" option

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#13617]
A new option was recently added (in #13432) to allow presets to auto-set certain module parameters based on the image information. I see two issues here that need to be resolved.

- The option "make this preset auto set values depending on images" is rather clumsily named and seeing this for the first time it's hard to see what it's doing based on the description. Perhaps something like "auto-set module parameters from image Exif data" would be an improvement. Either way a more detailed tooltip will almost certainly be needed.
- This option applies (afact) to a very small number of modules but it is available generally in the preset screen for every processing module. Ideally it should be greyed out on every module for which it has no effect - this will go some way towards making its effect easier to understand, since users could be confused as to why the option is available on, for example, the "rgb curve" module

As an aside I will need some very detailed information about exactly what this affects for the purposes of documentation.

**Comment by TurboGit** [comment]
> * This option applies (afact) to a very small number of modules

In fact no, it applies to all module and is a way to reset a module to it's default value.

**Comment by TurboGit** [comment]
> * Perhaps something like "auto-set module parameters from image Exif data"

Or "reset parameters to default based on Exif data" ?

**Comment by parafin** [comment]
> > * This option applies (afact) to a very small number of modules
> 
> In fact no, it applies to all module and is a way to reset a module to it's default value.

I think @elstoc’s point was that for the most modules it’s indistinguishable from just plain old preset created from default parameters, since they usually don’t depend on EXIF data.

**Comment by elstoc** [comment]
Indeed. Generic code that covers lots of use cases is a great thing but IMO it should not be this generic from a user point-of-view and should at least _look_ like it was designed to solve specific understandable problems.

**Comment by parafin** [comment]
So maybe add an iop flag CONST_DEF_PARAMS, which will disable new auto-init GUI elements in preset dialog?

**Comment by TurboGit** [comment]
Yes it may be indistinguishable from just plain old preset created from default parameters but that's not the truth. Fact is that this is the default for the foreseeable future. That is even if a module change it's default setting then you'll get the new default. So I think it is an important to keep as is for all modules.

**Comment by elstoc** [comment]
Sorry I don't understand what that means

**Comment by parafin** [comment]
> Yes it may be indistinguishable from just plain old preset created from default parameters but that's not the truth. Fact is that this is the default for the foreseeable future. That is even if a module change it's default setting then you'll get the new default. So I think it is an important to keep as is for all modules.

I very much doubt the usefulness of such feature, for sure it’s not “important”. Rather it’s confusing to have a preset, which can change over time.

**Comment by elstoc** [comment]
So am I to understand that what this option actually does is "enable module with default parameters (i.e. explicitly ignore _anything_ the user has manually set)"?

**Comment by jenshannoschwalm** [comment]
It is a generic way for any module that changes details how it's working by default. So it hides complexity from the user.

The first example was lens - yes paraffin showed me the old way - but now trivial for everyone.

For me it seems likely, the dev of a module knows best what the defaults should be. Again an easy go.

**Comment by TurboGit** [comment]
It's also very important to me.

**Comment by elstoc** [comment]
> It's also very important to me

I get that, I'm just trying to work out why it is important for everyone else and if so how we can best make its functionality clear. IMO the current description does not describe how it works very well. I'm also thinking with my dtdocs hat on: how to explain it in a simple way.

**Comment by TurboGit** [comment]
The important point is that : "such preset reset the module as if the history was reset or the image just developed" The keywords are **reset**, **default** & **Exif**. That's why I have proposed:

**"reset parameters to default based on Exif data"**

And I cannot find something better for now.

**Comment by elstoc** [comment]
I'm not sure we need Exif here to be honest since it's actually more generic than that: "reset all module parameters to their default values" and then a tooltip with a more detailed explanation regarding auto-calculation and the like.

**Comment by elstoc** [comment]
Also, if I understand correctly, the only real use case for this is to auto-apply the module with default settings (there's not really any point manually selecting a preset to do this, since you could as easily set the reset button?). That being the case, it should probably only be shown if the user chooses "auto apply this preset to matching images".

> such preset reset the module as if the history was reset or the image just developed

I'm not sure it actually does achieve that. For example, if I reset history on a scene-referred edit, the exposure module comes with a default of +0.7EV exposure, -0.0002 black level and compensate ticked. If I create a new auto-apply preset using the new setting, it resets to 0.0EV exposure, 0.0 black level, and compensate un-ticked.

**Comment by TurboGit** [comment]
> If I create a new auto-apply preset using the new setting, it resets to 0.0EV exposure, 0.0 black level, and compensate un-ticked.

Indeed, this is because exposure is sadly a hack. The real default is 0.0EV, 0.0 black. But expose has a specific preset already named "scene-referred default" which is applied automatically (in develop.c) when the workflow is scene-referred.

We could probably rework this to avoid this hack and change reload_defaults to setup the real default for the module based on the workflow. Probably worth opening an issue for this and I can have a look, no promise as I'm not sure of all the implications about this hack.

**Comment by elstoc** [comment]
Yes I understand how it works, I was just pointing out that "reset the module" and "like you've reset the image" are not the same thing and we need to be clear what the expected result is when using this feature. A similar "hack" is in place in filmic, for which no reasonable preset can be applied (because it adjusts based on exposure compensation)

**Comment by TurboGit** [comment]
> A similar "hack" is in place in filmic, for which no reasonable preset can be applied (because it adjusts based on exposure compensation)

No, that's not the case as filmicrgb does properly set the new defaults in `reload_defaults()` by checking the exposure value via introspection.

**Comment by TurboGit** [comment]
@elstoc : The exposure (& basecure) are now fixed  in #13639. That is, doing a reset now properly reset has if the image was just developed, so using the proper default values based on workflow & camera maker (for basecurve). Also this now fix the copy as auto-init (or preset or style) for those two modules.

**Comment by TurboGit** [comment]
@elstoc : So for the text, I'll use your last proposal:

`"reset all module parameters to their default values"`

And for the tooltip I'm proposing:

`'the parameters will be reset to their default values. the default may depends on the actual image, for example the "lens correction" module using the EXIF data."`

How does that sound?

**Comment by elstoc** [comment]
"the actual image" sounds odd in English. I think image exif data or metadata would be better. Do we have anything that uses non-exif image data? Then there's no need for the example. So "the parameters will be reset to their default values, which may be automatically set based on image metadata"

**Comment by elstoc** [comment]
I'm not able to test any of this as I'm away from my computer for a few days, but please make sure that subsequent instances of exposure don't use the same defaults. They should default to all zeros except for the first instance. This was the original reason for the hack

**Comment by TurboGit** [comment]
> I'm not able to test any of this as I'm away from my computer for a few days, but please make sure that subsequent instances of exposure don't use the same defaults. They should default to all zeros except for the first instance. This was the original reason for the hack

Indeed, it is the case in the current PR. I have tested many different scenario.

**Comment by TurboGit** [comment]
BTW, I think this issue can be closed now.
