### ISSUE TITLE
4.2.0 version does not support Simplified Chinese

### ISSUE THREAD

**Issue by duocoding** [darktable-org/darktable#13622]
Why 4.2.0 does not support Simplified Chinese, but only TaiWan Chinese?

<img width="732" alt="image" src="https://user-images.githubusercontent.com/48700579/218299197-b6169114-566c-49e6-875f-c7da0c1f487d.png">

**Comment by MStraeten** [comment]
because no one completed the translation for simplified chinese. 

if you want to have a proper translation this is the way to get it: https://github.com/darktable-org/darktable/wiki/Translating-darktable

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/13620

Please search before opening new issues.

**Comment by duocoding** [comment]
thx😀

**Comment by HSUfineprint** [comment]
Actually, it's duplicate of #13315.
