### ISSUE TITLE
4.2.0 Chinese can't be used

### ISSUE THREAD

**Issue by Niehyi** [darktable-org/darktable#13620]
I install the darktable 4.2.0 on Windows10 and change the language to Chineses(TW) but the GUI is still in English.

**Comment by pehar1** [comment]
The chinese translation was incomplete when 4.2 has been published. You will have to wait for version 4.2.1 and hope that someone will complete translation.

**Comment by Niehyi** [comment]
I mean the traditional Chinese.... it shows on the languages lists.

**Comment by Nilvus** [comment]
Did you restart darktable after changing language?

**Comment by Niehyi** [comment]
I do.
Now install darktable on another computer (Window11) and it can show Chinese.

**Comment by Nilvus** [comment]
So seems to be an issue on your Windows 10 computer. I suggest you to uninstall and reinstall it. Try also launching darktable with a whole new configuration by removing config folder on that computer ; should be in your user/AppData folder. Don't know exactly where, I do not use Windows. Think about saving that config folder to put it back after test as this will of course removing all your settings (and link to your images inside darktable). If you can change language with a fresh config folder, that means there's an issue on a file inside that folder (could probably be darktablerc file).

As this place is not a help support but about things to be fixed/updated on darktable code, I close. If you need more help about that, pixls.us forum is there to help you.
