### ISSUE TITLE
Macro vs function call

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#13638]
As macros are extensively used, I was wondering if something like this:
```cpp
CLAMPF(f(x), 0, 1)
```
would result in `f(x)` being evaluated multiple times needlessly.
Replacing the macro with a function call might be more compiler friendly.

I'm not up-to-speed with recent C++ compiler advancements and something like that might already be handled by the preprocessors, still I thought to bring up the issue anyway.

Few examples:
- https://github.com/darktable-org/darktable/blob/84a2467d0d23e71123f0464144354295f99d2d3f/src/iop/filmicrgb.c#L1760
- https://github.com/darktable-org/darktable/blob/84a2467d0d23e71123f0464144354295f99d2d3f/src/iop/cacorrect.c#L1207

Feel free to close this if that is the intended behavior.

**Comment by ralfbrown** [comment]
The optimizer will (usually) take care of this, computing the value once and storing it in a register.  The only case where it will definitely evaluate multiple times is when calling a function defined in another module, where it can't tell that multiple calls with the same parameters will produce the same return value.
