### ISSUE TITLE
History stack tooltip not showing changes consistently 

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#13636]
**Did you buy darktable from an application store ?**
OSB master

**Describe the bug/issue**
When I hover to a history item, it sometimes shows the tooltip with the details of what changed, but sometimes it shows `shift+alt+scroll to change height`

**To Reproduce**
Move mouse to hover over different items from the history stack

**Screenshots**
![image](https://user-images.githubusercontent.com/97920861/218604298-870c0dee-2a89-4162-b11c-7efc3035991f.png)

![image](https://user-images.githubusercontent.com/97920861/218604451-a5d682de-0829-490f-b41f-47c111845ed9.png)

**Platform**

* darktable version : 4.3.0~git609.4be17949
* OS                : Fedora 37 X11 16gb Nvidia 525.85.05 

**Additional context**
I've tried to find a pattern, but nothing clear.

**Comment by dterrahe** [comment]
If there are no changes to the module parameters to show, the tooltip will fall back to the standard text for any resizable widget. This would be the case if the only change is that the module was toggled on or off.

**Comment by dterrahe** [comment]
Could you please respond if this explains what you are seeing (and then close the issue) or provide additional information if something else is going on? Many thanks.

**Comment by gi-man** [comment]
I'm going to close the issue. I think it is a side effect of the new auto module feature. In the past I used a style, so most modules had a change from default. Now there is no default, therefore no change.
