### ISSUE TITLE
Please Add the Calibrite Color Checkers for Camera Calibration

### ISSUE THREAD

**Issue by aries223** [darktable-org/darktable#13644]
**Is your feature request related to a problem? Please describe.**

The current versions of Darktable do not include the most modern Color Calabration Targets by Calibrite (who bought out XRite).
https://calibrite.com/

**Describe the solution you'd like**

Please include the current Calibrite Color Checker Products in the "Color Calibration" Module
https://calibrite.com/us/product/colorchecker-passport-photo-2
https://calibrite.com/us/product/colorchecker-classic-mini/
https://calibrite.com/us/product/colorchecker-passport-duo/
https://calibrite.com/us/product/colorchecker-classic/

**Comment by ralfbrown** [comment]
Have they done anything beside changing the branding?  That Passport Photo 2 looks identical to the Xrite-branded one I have.

If the color patches are still the same, the only thing that would need to be done is change the post-2014 name string to "Xrite/Calibrite ColorChecker".  Note that the existing ColorChecker24 covers the Classic, the Mini, the Classic target in the Duo package, and one half of the Passport Photo.

**Comment by MStraeten** [comment]
the new brand print on the color chekcer doesnt affect the patches - so if you use the post 2014 value everything is fine (at least for my cc mini - but just checked by eyes).
I won't reccomend changing the string since it already spreads over the width of the right panel.
If you have information on changed values of the patches please provide them so they can be included.

**Comment by aries223** [comment]
Here is a recently purchased Calibrite Color Checker Mini with the XRite Post 2014 value. Unless I'm doing something wrong I dont see how that works...

https://i.postimg.cc/xCX6zz97/calibrite-cc-mini.jpg

**Comment by MStraeten** [comment]
You need to drag the edges to the proper corners of the image - upper right to lower left and lower left to upper right so the patches matches the image
I own that classic mini too and it works fine

**Comment by aries223** [comment]
Ok I got it now.. Not intuitive, but I see it now.. Thanks.. Closing
