### ISSUE TITLE
[dt 4.3.0] Moving shapes up and down the list within the group does not work

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#13641]
Moving shapes up and down within the group does not work. But this is important for the use of boolean operators.

**To Reproduce**

1. In mask manager, if you have more than one shape in the group, click on one and with right mouse click select from the menu option "move up" or "move down". 
2. This option has no effect on the order of the shapes.

**Expected behavior**

With the option "move up" or "move down" the shape should be moved higher or lower in the list.

**Screencast**

![Shape_is_not_Moving](https://user-images.githubusercontent.com/38165484/218821404-f4fac28f-1229-47fb-9a0c-cc139374440f.gif)

**Platform**

darktable version : 4.3.0~git612.df71c33c-1+9143.1
Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-60-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

**Comment by pehar1** [comment]
I can confirm. Tried with four shapes, two circles, one path, one brush. Also observed that sometimes (not always) the group immediately collapses, when _"move up"_ or _"move down"_ is selected. So far, however, I have not been able to find a system for this collapsing.

darktable 4.3.0+547-gc6cb0c057
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by zisoft** [comment]
> Also observed that sometimes (not always) the group immediately collapses, when "move up" or "move down" is selected.

You need to first select the entry (left click) before applying from the menu. Then the group does not collapse.
But the move up/down doesn't work either, I'm investigating.
