### ISSUE TITLE
Programm crashes

### ISSUE THREAD

**Issue by robbyund** [darktable-org/darktable#13649]
Under windows 10 22H2 darktable 4.2.0  crashes in various modules.
I tried to get a failure report with darktable.exe -d perf, after I did this the program dindn´t crash anymore.

**Comment by victoryforce** [comment]
How can we help? You didn't provide any information, you just say that the program doesn't crash anymore.

**Comment by Nilvus** [comment]
So it's fixed and you didn't provide nearly all infos asked on template issue. I so close.
