### ISSUE TITLE
Unable to load a CR3 using darktable-cli

### ISSUE THREAD

**Issue by Rezrazi** [darktable-org/darktable#13658]
**Describe the bug/issue**
When trying to load a CR3 into darktable-cli on a Debian environment, it is unable to open the file with the following error:
```
dark-test@46f67f58e551:~# darktable-cli Y-JG-CANON-EOS-R7-0012.CR3 test.jpg
error: can't open file Y-JG-CANON-EOS-R7-0012.CR3
no images to export, aborting
```

I tested it with a sample CR3 from [this source](https://www.imaging-resource.com/PRODS/canon-eos-r7/canon-eos-r7GALLERY.HTM)

Tested on a fresh Dockerized environment running Debian 11

**To Reproduce**
1. Run a docker container running Debian:stable-slim (D11 at the time of writing) (You may use something like https://labs.play-with-docker.com/ for quick experimentation)
2. Install darktable-cli following this guide https://software.opensuse.org/download.html?project=graphics:darktable:stable&package=darktable
3. Check darktable-cli is installed using `darktable-cli --version` should return that darktable 4.2 is installed
4. Run the following command `darktable-cli Y-JG-CANON-EOS-R7-0012.CR3 test.jpg`

**Expected behavior**
Running the same command, under the same version (4.2) on my local Macos machine with darktable installed through brew, I'm able to produce a jpg file.

I am expecting this command to work on my docker container as well.

**Screenshots**
![CleanShot 2023-02-17 at 12 09 00](https://user-images.githubusercontent.com/2086576/219633889-a68c0633-86e3-4e05-9d0e-b48ec543d170.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : darktable-cli 4.2.0~git4.64041571-1+77.1
* OS                : Debian GNU/Linux 11 (bullseye)
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by MStraeten** [comment]
did you check you're having a proper exiv2 (at least 0.27.4) built with EXIV2_ENABLE_BMFF=O in your container?

**Comment by Rezrazi** [comment]
> did you check you're having a proper exiv2 (at least 0.27.4) built with EXIV2_ENABLE_BMFF=O in your container?

exiv2 was installed on the container using a regular install with `apt install exiv2`. 
Is it a requirement to have this flag (and exiv2) to be able to run darktable-cli ?

**Comment by Rezrazi** [comment]
> if it's not build with that option there's no support for cr3

I believe it could be perhaps beneficial to have a clearer error message for this, as I've been looking for way too long to understand the reason for this (I know I should've been more careful reading the readme 😄 )

**Comment by Rezrazi** [comment]
Hi @MStraeten sorry for reopening this issue

I've given it some time to ensure that exiv2 is built with the necessary flags, however I'm still not able to get darktable to read a CR3 file.

exiv2 built with the following flags `-DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_BMFF=ON -DBUILD_WITH_CCACHE=ON`

```
root@899bd13106ef:~# exiv2 --version
exiv2 0.27.6

root@899bd13106ef:~# exiv2 -pp raw.cr3 
Preview 1: image/jpeg, 160x120 pixels, 11678 bytes
Preview 2: image/jpeg, 1620x1080 pixels, 276344 bytes


root@899bd13106ef:~# darktable-cli raw.cr3 raw.jpg
[dt_detect_cpu_features] Not implemented for this architecture.
[dt_detect_cpu_features] Please contribute a patch.
[dt_init] SSE2 instruction set is unavailable.
[dt_init] expect a LOT of functionality to be broken. you have been warned.
[defaults] found a 64-bit system with 8040056 kb ram and 4 cores (0 atom based)
[defaults] setting high quality defaults
[dt_detect_cpu_features] Not implemented for this architecture.
[dt_detect_cpu_features] Please contribute a patch.
[dt_codepaths_init] will be using HIGHLY EXPERIMENTAL plain OpenMP SIMD codepath.
[dt_codepaths_init] SSE2-optimized codepath is disabled or unavailable.
[dt_codepaths_init] expect a LOT of functionality to be broken. you have been warned.
error: can't open file raw.cr3
no images to export, aborting
```

Is there some way to fully debug this and try to understand why darktable isn't yet able to read the file, --verbose doesn't add any further relevant information

---
> Please feel free to contribute.

I would love to, but my C/C++ skillset is very limited 😄

**Comment by parafin** [comment]
Did you rebuild darktable after building the correct version of exiv2? The check for CR3 support is compile-time in darktable.

**Comment by Rezrazi** [comment]
I understand, I'm currently trying to rebuild darktable inside the container. 

I don't know if I missed something, but with a build command that looks like this:

```Dockerfile
FROM debian:bullseye

RUN echo "deb-src http://deb.debian.org/debian bullseye main" >> /etc/apt/sources.list

RUN apt -y update
RUN apt build-dep darktable -y

RUN git clone --recurse-submodules --depth 1 -j8 https://github.com/darktable-org/darktable.git
RUN cd darktable && git fetch --tags && git checkout tags/release-4.2.1 && git submodule update --init
RUN ./darktable/build.sh --prefix /opt/darktable --build-type Release --install --sudo
```

Everything passes, but it fails at the darktable build step with the following error:
```
#14 79.91 [ 38%] Building C object bin/CMakeFiles/lib_darktable.dir/common/bilateral.c.o
#14 80.43 /darktable/src/common/bilateral.c:411:6: error: GCC does not currently support mixed size types for 'simd' functions [-Werror]
#14 80.43   411 | void dt_bilateral_slice_to_output(const dt_bilateral_t *const b, const float *const in, float *out,
#14 80.43       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
#14 80.43 compilation terminated due to -Wfatal-errors.
#14 80.43 cc1: all warnings being treated as errors
#14 80.43 gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:140: bin/CMakeFiles/lib_darktable.dir/common/bilateral.c.o] Error 1
#14 80.43 gmake[2]: *** Waiting for unfinished jobs....
#14 81.21 gmake[1]: *** [CMakeFiles/Makefile2:2125: bin/CMakeFiles/lib_darktable.dir/all] Error 2
#14 81.22 gmake: *** [Makefile:171: all] Error 2
------
executor failed running [/bin/sh -c ./darktable/build.sh --prefix /opt/darktable --build-type Release --install --sudo]: exit code: 2
```

- Docker 20.10.22
- macOS 13.1 (M1)

**Comment by parafin** [comment]
Which GCC version is that? It's printed somewhere in the beginning of build.sh script output by cmake.

**Comment by Rezrazi** [comment]
Here's a snippet of the output

```
#14 0.464 darktable build script
#14 0.464 
#14 0.464 Building directory:  /darktable/build
#14 0.464 Installation prefix: /opt/darktable
#14 0.464 Build type:          Release
#14 0.464 Build generator:     Unix Makefiles
#14 0.464 Build tasks:         4
#14 0.464 
#14 0.646 -- The CXX compiler identification is GNU 10.2.1
#14 0.727 -- The C compiler identification is GNU 10.2.1
#14 0.736 -- Detecting CXX compiler ABI info
#14 0.856 -- Detecting CXX compiler ABI info - done
#14 0.864 -- Check for working CXX compiler: /usr/bin/c++ - skipped
#14 0.864 -- Detecting CXX compile features
#14 0.864 -- Detecting CXX compile features - done
#14 0.867 -- Detecting C compiler ABI info
#14 0.939 -- Detecting C compiler ABI info - done
#14 0.946 -- Check for working C compiler: /usr/bin/cc - skipped
#14 0.946 -- Detecting C compile features
#14 0.947 -- Detecting C compile features - done
#14 1.234 -- Found OpenMP_C: -fopenmp (found suitable version "4.5", minimum required is "4.5") 
#14 1.315 -- Found OpenMP_CXX: -fopenmp (found suitable version "4.5", minimum required is "4.5") 
#14 1.316 -- Found OpenMP: TRUE (found suitable version "4.5", minimum required is "4.5")  
#14 1.317 -- Looking for pthread.h
#14 1.382 -- Looking for pthread.h - found
#14 1.382 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
#14 1.457 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
#14 1.457 -- Looking for pthread_create in pthreads
#14 1.531 -- Looking for pthread_create in pthreads - not found
#14 1.531 -- Looking for pthread_create in pthread
#14 1.593 -- Looking for pthread_create in pthread - found
#14 1.594 -- Found Threads: TRUE  
```

full output if required here https://gist.github.com/Rezrazi/d350a8abaf0b19abf1cb3d8da3e50d81

**Comment by Rezrazi** [comment]
@parafin looking back at the error log, would this be an issue with a major version of gcc, looking around to some issues that mention this kind of error, it is stated that it was just a warning, perhaps it was elevated to an error at some point ?

Here's the Dockerfile I'm using to build darktable with exvi2 having CR3 support enabled
https://gist.github.com/Rezrazi/96fcd419f53af4a4764cda6305ae9c08

Additionally, trying to run this from debian:buster (instead of bullseye) I'm met with the following error
```
#14 0.670 CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
#14 0.670   CMake 3.18 or higher is required.  You are running version 3.13.4
```

Under debian:bullseye:
```
proot@7819547b9a53:/# apt policy gcc
gcc:
  Installed: (none)
  Candidate: 4:10.2.1-1
  Version table:
     4:10.2.1-1 500
        500 http://deb.debian.org/debian bullseye/main arm64 Packages
```

**Comment by parafin** [comment]
Warnings are treated as errors by default if one is building from git repository. Strangely no one reported this problem and CI also passes, which I think also includes GCC 10 (but maybe not that specific minor version?). Someone else will have to take a look at this issue. But you could just download darktable-4.2.1.tar.gz tarball and compile darktable using it, then compiler warnings will be ignored.
As for cmake requirement - yes, cmake 3.18 is required, this is mentioned in release notes. You could probably install it using pip (python package manager).

**Comment by Rezrazi** [comment]
Downloading the tarball could have a handy work around, however it seems to rely on git submodules for the build.

```
CMake Error at src/external/CMakeLists.txt:2 (add_subdirectory):
#12 5.015   The source directory
#12 5.015
#12 5.015     /darktable/src/external/libxcf
#12 5.015
#12 5.015   does not contain a CMakeLists.txt file.
#12 5.015
#12 5.015
#12 5.015 CMake Error at src/external/CMakeLists.txt:20 (message):
#12 5.015   RawSpeed submodule not found.  You probably want to run:
#12 5.015
#12 5.015   $ git submodule init
#12 5.015
#12 5.015   and then
#12 5.015
#12 5.015   $ git submodule update
#12 5.015
#12 5.015
#12 5.016 -- Configuring incomplete, errors occurred!
```

Is there a way to manually add the submodules for the build. If that's not possible, is it possible to avoid warnings being elevated to errors when building with git ?

**Comment by parafin** [comment]
Most likely you downloaded the wrong file. Here's the direct link to the correct one:
https://github.com/darktable-org/darktable/releases/download/release-4.2.1/darktable-4.2.1.tar.xz

**Comment by Rezrazi** [comment]
Thank you @parafin I was about to brute force my way into disabling the -Werror flags and build from git

So, I was able to get darktable to correctly build, but it seems it's still unable to read a CR3 file

```
/opt/darktable/bin/darktable-cli: symbol lookup error: /opt/darktable/bin/../lib/darktable/libdarktable.so: undefined symbol: _ZN5Exiv210enableBMFFEb
```

perhaps linked to this check here https://github.com/darktable-org/darktable/blob/ede51437d4cb14132177003b47bc78d273e79580/src/CMakeLists.txt#L459 

exiv2 is able to read the cr3
```
root@fd0e60a980d4:~# exiv2 -pp raw.cr3
Preview 1: image/jpeg, 160x120 pixels, 11678 bytes
Preview 2: image/jpeg, 1620x1080 pixels, 276344 bytes
```

built with
```
ARG version=0.27.6

RUN mkdir src \
      && cd src \
      && curl -sL https://github.com/Exiv2/exiv2/archive/refs/tags/v${version}.tar.gz \
        | tar xzf - --strip-components 1 \
    && mkdir build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_CCACHE=ON -DEXIV2_ENABLE_BMFF=ON .. \
    && cmake --build . \
    && cmake --install . \
    \
    && cd .. \
    \
    && mkdir darktable \
           && cd darktable \
           && curl -SL https://github.com/darktable-org/darktable/releases/download/release-4.2.1/darktable-4.2.1.tar.xz \
               | tar Jxf - --strip-components 1 \
           && ./build.sh --prefix /opt/darktable --build-type Release --install
```

**Comment by parafin** [comment]
It's a question of how you installed exiv2. You built darktable with newer version of exiv2, but at runtime executable tries to load the old one. It can be solved for example by setting LD_LIBRARY_PATH to point to where libexiv2.so.* are located (the correct version).

**Comment by Rezrazi** [comment]
oh yes indeed, that seems to get it to work

thank you @parafin and @MStraeten (and the team)

I'll most likely write something up somewhere for people who would encounter the same issue
