### ISSUE TITLE
High CPU usage in darkroom when left panel is expanded

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#13664]
**Describe the bug/issue**
When in the darkroom module, darktable consumes about 60% CPU when idle if the left panel is expanded. This CPU usage continues even if darktable is not the foreground application.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open system monitor
2. Click on an image to enter darkroom
3. Ensure left panel is showing
4. Observe CPU usage in system monitor. On my system, it consumes about 60% consistently.
5. In darktable, hide the left panel
6. Observe CPU usage subside.

**Expected behavior**
Darkroom should not be consuming so much CPU when idle.

**Which commit introduced the error**
I'm not sure, but @jenshannoschwalm was able to reproduce here: https://github.com/darktable-org/darktable/pull/13654#issuecomment-1435323240

I can try bisecting once I can identify a good commit.

**Platform**
* darktable version : darktable 4.3.0+612~gdf71c33c7c
* Linux - Distro    : archlinux updated.
* Memory            : 16GB

**Additional context**
Reproduced with a clean darktable configuration. Reproduced with opencl enabled/disabled.

**Comment by ptilopteri** [comment]
platform 
darktable version
linux distro openSUSE Tumbleweed 20230216
memory 32GB

with the conditions stated:
 USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
paka     13676  2.0  5.3 18240100 1745812 pts/25 Sl+ 14:55   5:15  |           \_ /data1/software/build/darktable_repos/bin/darktable --library :memory:

**Comment by gi-man** [comment]
I cannot reproduce. Fedora 37 KDE X11 Nvidia Ryzen 5700G
4.3.0~git668.da867e97

**Comment by pehar1** [comment]
I can reproduce, but only related to one (of 12) cores.

Left panel open :
![left-panel-open](https://user-images.githubusercontent.com/104291381/219850529-4a745a95-b3ec-4b02-acbd-2dd11ec735c6.png)

Left panel closed
![left-panel-closed](https://user-images.githubusercontent.com/104291381/219850575-0d79ed2f-ff87-4efd-a83e-b594bf77b83d.png)

Related to all 12 cores, the CPU load is thus 3-4%, so no problem on my side.

darktable 4.3.0+640-g22c9eaf9d
OS : Linux 5.15.0-60-generic / Ubuntu 22.04.2 LTS
Memory : MemTotal:       65768488 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by jenshannoschwalm** [comment]
> I can reproduce, but only related to one (of 12) cores.

Same here. Might be some gtk stuff is idling?

**Comment by groutr** [comment]
I should have mentioned that i only have two cores, so it is a much more noticeable.

**Comment by pehar1** [comment]
Switching off navigation module (shift-ctrl-n) immediatly reduces CPU-load drastically. So navigation module in top left corner seems to be the "bad guy".

**Comment by gi-man** [comment]
I see it now if I look by cores. I have 16, so not very noticeable. Switching navigation module does reduce it.

**Comment by TurboGit** [comment]
Can one of you do a test after reverting 85f077594339e ?

$ git revert 85f077594339e940d71fc55062587876fbe347c3

Just a wild guess...

**Comment by dterrahe** [comment]
That particular commit does not seem to make a difference (for me), so I'll probably need to review all of #13507

**Comment by dterrahe** [comment]
I suspect it is this in `_lib_navigation_draw_callback`
https://github.com/darktable-org/darktable/blob/23b0c0abdb18cd2657e38786399b53697fe8969b/src/libs/navigation.c#L273
in combination with this
https://github.com/darktable-org/darktable/blob/23b0c0abdb18cd2657e38786399b53697fe8969b/src/bauhaus/bauhaus.c#L1453
that is triggering a refresh loop. I'll have to think of a different way to ensure that both the image and the zoom widget get properly refreshed.

Thanks for reporting this!
