### ISSUE TITLE
dt-master crashes on export

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#13668]
**Describe the bug/issue**
While exporting dt master crahes with empty bactrace.

**To Reproduce**
export NEF to PNG with the following settings:
![grafik](https://user-images.githubusercontent.com/49004103/219867355-e594375e-4aa9-440d-b26e-374dc422f4d9.png)
(actually also with this setting, where I started with:
![grafik](https://user-images.githubusercontent.com/49004103/219867395-a1fa720d-ffec-4100-9a66-7c7d2c51a386.png)

** backtraces **
[darktable_bt_76WW01.txt](https://github.com/darktable-org/darktable/files/10774289/darktable_bt_76WW01.txt)
[dt-crash_20230218a.txt](https://github.com/darktable-org/darktable/files/10774290/dt-crash_20230218a.txt)

I could not CMAKE_BUILD_TYPE="RelWithDebInfo" due to #13667 

**Expected behavior**
No Crash

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.3.0+674~gec0e357b6
* OS                : Linux - kernel 6.1.12-gentoo
* Distro            : Gentoo Base System release 2.9
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-525.89.02
* OpenCL installed  : Yes (opencl-headers-2022.09.30)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.35
* gcc               : x86_64-pc-linux-gnu-11
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by TurboGit** [comment]
And without "high quality resampling" option?

**Comment by AxelG-DE** [comment]
@TurboGit I will test next. But I did so last week just fine (I mean export with highQ-resampling".

At this very moment I am running with "--configdir /tmp" and first round w/o crash, so there is a chance, my db is messed. I will follow up

**Comment by AxelG-DE** [comment]
@TurboGit here are my observations/test-results:

1. switching high quality resampling to OFF helps. No crash (only one run)
2. 4.3.0-392-g98042600c-dirty --configdir /tmp highQ-Resampl=on --> **no crash**
3. 4.3.0-674-gec0e357b6 --configdir /tmp highQ-Resampl=on --> **crash**
4. 4.3.0-674-gec0e357b6 --configdir /tmp highQ-Resampl=off --> **no crash**
5. for No. 2 and No.3 "Adobe RGB (1998) was not available (confusing and I donno, whether I need to open another issue and how to report)
6. 4.3.0-674-gec0e357b6 highQ-Resampl=off --> still running, but runs already a while and **up to now, no crash**

**Comment by AxelG-DE** [comment]
would a bisect make sense between
- 4.3.0-392-g98042600c-dirty --configdir /tmp highQ-Resampl=on
- 4.3.0-674-gec0e357b6 --configdir /tmp highQ-Resampl=on
?

**Comment by AxelG-DE** [comment]
I am wondering, the things are related..... :'-(

after a no-crash-event, I would expect the timespamp in db is the same than the xmp, but crawler complains.....
![grafik](https://user-images.githubusercontent.com/49004103/219879052-033f26e9-e6f0-4a81-823f-63ef8a2c3224.png)

**Comment by TurboGit** [comment]
The next question is what is on the history stack when it crashes on HQ export? Is there diffuse&sharpen which is quite memory demanding... Looking for the next culprit in play...

**Comment by TurboGit** [comment]
> * 4.3.0-392-g98042600c-dirty --configdir /tmp highQ-Resampl=on
> 
> * 4.3.0-674-gec0e357b6 --configdir /tmp highQ-Resampl=on

Yes, would help for sure.

**Comment by AxelG-DE** [comment]
4.3.0+681~g4f3d27241 
- high quality resampling = off --> no crash
- high quality resampling = on --> crash
- RelWithDebInfo --> no backtrace

**Comment by AxelG-DE** [comment]
> The next question is what is on the history stack when it crashes on HQ export? Is there diffuse&sharpen which is quite memory demanding... Looking for the next culprit in play...

those are photos from 2018 and no difuse or sharpen there....

just now it crashed repeatedly on this pic (I know crop and rotate is outdated, but I guess nobody re-edits prior an export :-D ):
![grafik](https://user-images.githubusercontent.com/49004103/219880320-b4e314d6-5418-4bb3-b750-679cff9c2649.png)

**Comment by TurboGit** [comment]
> 4.3.0+681~g4f3d27241

Is that the bisect? Looks like an error if so as this commit is current master :)

**Comment by TurboGit** [comment]
> I know crop and rotate is outdated, but I guess nobody re-edits prior an export

Sure, in darktable no module should be misbehaving even if old as we ensure that old edits are kept.

**Comment by AxelG-DE** [comment]
> > * 4.3.0-392-g98042600c-dirty --configdir /tmp highQ-Resampl=on
> > * 4.3.0-674-gec0e357b6 --configdir /tmp highQ-Resampl=on
> 
> Yes, would help for sure.

on my way

**Comment by AxelG-DE** [comment]
> > 4.3.0+681~g4f3d27241
> 
> Is that the bisect? Looks like an error if so as this commit is current master :)

no, I am still bisecting
indeed I will then report what bisect shoots. maybe will not finish tonight as my wife needs my support and comfort (feels bad)

**Comment by AxelG-DE** [comment]
bisect failed for today as even 4.3.0-392-g98042600c crashes if highQ-res is on :-(
Darned....

**Comment by AxelG-DE** [comment]
only one thing changed on my hardware recently
I figured, that my ram setting in bios was reset from XMP back to auto. So I switched on XMP again and meanwhile compiled many packages of my gentoo flawlessly....

**Comment by AxelG-DE** [comment]
- That picture I show in above post is position 161/477 and it always crashes there.
- I was on the way to paste NEF and xmp here...
- but then I exported it singularly and in a set of three surrounding ones. --> no crash
- ....now I am a bit lost. what could I do to further investigate?

**Comment by AxelG-DE** [comment]
I am getting more and more confused.
just now I did several rounds of exporting (all in "skip") mode
using --configdir /tmp no crash (regardless which version of dt), using my genuine configdir it crashes again
all in highQ-res=on

in between I saw this:
`15.2871 [dt_interpolation_resample_cl] couldn't enqueue kernel! CL_INVALID_VALUE`

deleting the cached_kernels did not help, still crashes

**Comment by AxelG-DE** [comment]
just now upgraded from 4.3.0-674-gec0e357b6 to 4.3.0+685~g3b1863495
- native configdir
- high-quality-resampling=yes
no more crash 
(up to now, I will keep on testing), espcially I wanna have highQ resampling on and png with AdobeRGB1998)

**Comment by AxelG-DE** [comment]
crashed again :-(

**Comment by AxelG-DE** [comment]
I get the smell, it crashes easier when there are more exports waiting in the cue. Because I just restarted and export again with "skip" and the first folder (which typically crashed) passed well

I'm afraid, you devs will lose patience, when this behaviour is so inconsistent, more would speak for prob on my side :-/

**Comment by AxelG-DE** [comment]
new findings...
it seems dt crahes only when more than one export is in the cue.
I had 3 exports with each ~300-400 pic seperately, no problem
epxorting several sets and they are in a waiting line. BANG...

**Comment by AxelG-DE** [comment]
and here is the "log"
[dt.crash_20230219.log.zip](https://github.com/darktable-org/darktable/files/10777499/dt.crash_20230219.log.zip)

**Comment by TurboGit** [comment]
Something strange:
```

 14140.8003 [opencl memory] device 0: 1070125464 bytes (1020.6 MB) in use
 14140.8005 [opencl memory] device 0: 972841368 bytes (927.8 MB) in use
 14140.8024 [opencl memory] device 0: 875557272 bytes (835.0 MB) in use
 14140.8036 [opencl memory] device 0: 1264693656 bytes (1206.1 MB) in use
 14140.8075 [opencl memory] device 0: 1264693272 bytes (1206.1 MB) in use
 14140.8104 [opencl memory] device 0: 1167409176 bytes (1113.3 MB) in use
 14140.8106 [opencl memory] device 0: 778272792 bytes (742.2 MB) in use
 14140.8127 [opencl memory] device 0: 778272768 bytes (742.2 MB) in use
 14140.8138 [opencl memory] device 0: 389136384 bytes (371.1 MB) in use
 14140.8162 [dev_pixelpipe] took 1.035 secs (1.005 CPU) [export] processed `denoise (profiled) 1' on GPU, blended on GPU
 14141.1645 [dev_pixelpipe] module `denoise (profiled) 1' min: (0.002114; 0.000000; 0.000000) max: (0.168772; 0.175291; 0.170518) [export]
 14141.1645 [opencl memory] device 0: 778272768 bytes (742.2 MB) in use
 14141.1646 [pixelpipe_process_CL]       [export]       exposure             (   0/   0) 6032x4032 scale=1.0000 --> (   0/   0) 6032x4032 scale=1.0000 
 14141.1674 [opencl memory] device 0: 389136384 bytes (371.1 MB) in use
 14141.1678 [dev_pixelpipe] took 0.003 secs (0.003 CPU) [export] processed `exposure' on GPU, blended on GPU
 14141.5093 [dev_pixelpipe] module `exposure' min: (0.004884; 0.000000; 0.000000) max: (0.389892; 0.404952; 0.393927) [export]
 14141.5844 [opencl memory] device 0: 0 bytes (0.0 MB) in use
 14141.5850 [pixelpipe_process_on_CPU]   [export]       spots                (   0/   0) 6032x4032 scale=1.0000 --> (   0/   0) 6032x4033 scale=1.0000 
```

All `opencl_memory` lines looks ok at first... But the last one seems to be broken.

**Comment by TurboGit** [comment]
> epxorting several sets and they are in a waiting line. BANG...

Which is strange as they are handled one by one, some should be equivalent to have them started separately.

**Comment by AxelG-DE** [comment]
> > epxorting several sets and they are in a waiting line. BANG...
> 
> Which is strange as they are handled one by one, some should be equivalent to have them started separately.

Don't take that too much for granted. It is just my gut feeling and observation. I will do some "grep" on above log....

**Comment by AxelG-DE** [comment]
`cat dt.crash_20230219.log.txt | grep "opencl memory" | grep "(0.0 MB"
`
...shows. there are many...

**Comment by AxelG-DE** [comment]
I think I found something:
is seems it is always the spot removal, once it bangs...

[dt.crash_20230219_c.log.zip](https://github.com/darktable-org/darktable/files/10777672/dt.crash_20230219_c.log.zip)

yet again I had nice export running and it exploded once i added another export

**Comment by AxelG-DE** [comment]
[dt.crash_20230219_d.log.zip](https://github.com/darktable-org/darktable/files/10780233/dt.crash_20230219_d.log.zip)

IIRC that was a single export job... 
spot again

**Comment by AxelG-DE** [comment]
I am about to test with bios memory xmp-I instead of xmp-II
after starting the export I will leave the PC for today. So feedback may come Tuesday or Wednesday

**Comment by AxelG-DE** [comment]
the crash came right away after switched to xmp-I (which is very-slightly slower than xmp-II)

[dt.crash_20230220_a.log.zip](https://github.com/darktable-org/darktable/files/10787221/dt.crash_20230220_a.log.zip)

**Comment by jenshannoschwalm** [comment]
One thing comes to my mind, the crash in spot could be related to thats a module running on cpu so we would have to allocate cpu buffers and do the copy here. So it could be an oom situation.

This could be a systematic problem while calculating available memory for a pipe. While in darkroom we have at least all pixelpipe caches. Tried with system resources setting to small?

**Comment by jenshannoschwalm** [comment]
> 14141.5850 [pixelpipe_process_on_CPU]   [export]       spots                (   0/   0) 6032x4032 scale=1.0000 --> (   0/   0) 6032x4033 scale=1.0000

This also could hint at some range checking error as the roi_out is slightly larger than roi_in

**Comment by AxelG-DE** [comment]
> Tried with system resources setting to small?

@jenshannoschwalm which settings do you mean? Usually I do not seat tight values, as I have 32GB ram and particularly I didn't change them recently, but the weeks before this issue I exported a lot w/o issues

**Comment by jenshannoschwalm** [comment]
I meant darktable resources -->small/default ...

But my best guess to check would be the look for proper inside roi_in tests.

**Comment by jenshannoschwalm** [comment]
@TurboGit Had a look in the coffee break

https://github.com/darktable-org/darktable/blob/c175c8fc618935b43f5bc86ec568ae213f731f93/src/iop/spots.c#L527-L533

This is wrong, copies more data than available so out of data.

**Comment by TurboGit** [comment]
Not sure why this part is so convoluted, looks like this loop just copy the image from in -> out, so we could use `dt_iop_copy_image_roi`, right?

**Comment by TurboGit** [comment]
In fact no as it is also used for distort_mask.

**Comment by jenshannoschwalm** [comment]
Probably the roi_in calculation is wrong. It looks weird anyway as we use ints but calculate using floats.

**Comment by kmilos** [comment]
> Probably the roi_in calculation is wrong.

Is this why CI also unexpectedly failed for me here: https://github.com/darktable-org/darktable/actions/runs/4243470984/jobs/7376266348#step:6:47

**Comment by TurboGit** [comment]
> Probably the roi_in calculation is wrong. It looks weird anyway as we use ints but calculate using floats.

Hum... I don't see ints there... Maybe we are not looking at the same code. I have checked the loop and it seems correct to me after all.

**Comment by jenshannoschwalm** [comment]
https://github.com/darktable-org/darktable/blob/e4a7487a2858f3f15bffc2d1e19f74e655c82c40/src/iop/spots.c#L481-L487

I think the rounding with + 0.5 is wrong. The normal case for export and hq upscale would be scale=1 and we would end up with input range 1 larger than available.

**Comment by jenshannoschwalm** [comment]
Yeah, this was not noticed before we changed the upscaling stuff, in former versions we had the roi_in with a maximum of input_dimension-1 and did dirty tricks for the final dimension. Now this module "overexpands" No?
