### ISSUE TITLE
RFC: refine the module name vs instance name UI

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13660]
Following PR #13659 it is now possible to better display the module name vs instance name.

Rational:
Now that we have automatic naming of instances based on presets a better (more readable UI) would be nice.

Today we have the instance name just following the module name without separator:

![image](https://user-images.githubusercontent.com/467069/219682941-8da3d47c-9b49-4f97-aa66-e692c611f791.png)

Using CSS we can add a separator:

![image](https://user-images.githubusercontent.com/467069/219683138-92162173-cf27-4c70-9f0f-cd1af79e9e3c.png)

Or underline:

![image](https://user-images.githubusercontent.com/467069/219683522-c2bff23c-45b4-408b-8e8c-0470c7c387ca.png)

![image](https://user-images.githubusercontent.com/467069/219683673-0b95bbbe-ebdc-42ef-95ee-42f2baeb0960.png)

Any other idea welcomed!

**Comment by MStraeten** [comment]
the underline variants looks less distracting than the vertical separator - and also gives a noticeable separation between module name and instance name. The dotted lines even looks more harmonious

**Comment by TurboGit** [comment]
Thanks, some other proposals (character prefix):

1.
![image](https://user-images.githubusercontent.com/467069/219698588-2c4424df-82c8-4cc4-a066-17682fd6f07c.png)

2.
![image](https://user-images.githubusercontent.com/467069/219698897-1a1e7f6e-9104-40a7-84bb-edb1ef84b5cb.png)

3.
![image](https://user-images.githubusercontent.com/467069/219699302-0b7d9169-4fd5-491b-a5e1-404fdad2bdc8.png)

**Comment by TurboGit** [comment]
Again, that's only food for thought... Do not hesitate to propose something different.

**Comment by jenshannoschwalm** [comment]
I think 'some' separation is better indeed. I would go for the dot, not distracting at all but clearly a hint to be noticed.

There is one drawback of the "instance name" in general though, my personal habit is i have the right panel mostly visible and if the panel gets too narrow the original module name gets abbreviated but the "instance name" stays intact. I would prefer to have the original module name staying visible.

**Comment by TurboGit** [comment]
> I would prefer to have the original module name staying visible.

Hard to do. I have changed the ellipsis to be at the end of the module name.

@dterrahe : Do you know if we can have precedence between two consecutive labels for the ellipsis? That is first ellipsis the second one (here the instance name) and then the module name.

**Comment by TurboGit** [comment]
BTW, this discussion should happen here https://github.com/darktable-org/darktable/pull/13659.

**Comment by dterrahe** [comment]
If we are going wild, we could right-align the instance name. Which won't change the situation faced when one (or both) are ellipsized).

**Comment by Nilvus** [comment]
I agree with @jenshannoschwalm. Dot is the best way (or maybe test with right-align way as @dterrahe suggest.

Just a thing: why do you assign this to me @TurboGit?

**Comment by TurboGit** [comment]
> Just a thing: why do you assign this to me @TurboGit?

For reviewing as it is a UI thing.

**Comment by TurboGit** [comment]
I'm also preferring the dot. So probably the best move at this point.
