### ISSUE TITLE
dt-master breaks old edits 

### ISSUE THREAD

**Issue by andabata** [darktable-org/darktable#13671]
Whilst re-editing old images i noticed that old edits from 2018 break with the darktable 4.3.0+534~ga3b9ffb.

https://shell.kees.nl/dt/IMG_7437.CR2
https://shell.kees.nl/dt/IMG_7437.CR2.xmp

**Comment by TurboGit** [comment]
Breaks how? Can you please give more information.

**Comment by andabata** [comment]
Ha.. i might have been a bit short with information.
using '/opt/darktable/bin/darktable --library :memory:  .' to 'reimport' that dir for editing i get this result. I'm pretty sure this isn't they way i left them last time. I guess the interpretation of the .xmp isn't completly good. 

![dt-broken](https://user-images.githubusercontent.com/6125261/219934237-eb050a27-dae5-43ef-9bfe-ca74db850c98.png)

**Comment by andabata** [comment]
And the image + xmp is one of the images in this set.

**Comment by ralfbrown** [comment]
@andabata Is this still an issue with current master?  If so, please provide a sidecar .xmp file and if possible the image it belongs to so that we can investigate.

**Comment by ralfbrown** [comment]
No further response from issue originator in past month...
