### ISSUE TITLE
slideshow not working on mac osx and fedora

### ISSUE THREAD

**Issue by cridemichel** [darktable-org/darktable#13678]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
Slideshow is not working at all on mac osx. 
With both Darktable 4.2.0 and github version (compiled by homebrew) on mac osx 
Ventura 13.2.1 in the slidshow I obtain either "blurred/low definition" or corrupted images as follow ones:
<img width="1509" alt="Screenshot 2023-02-19 alle 10 59 14" src="https://user-images.githubusercontent.com/15322138/219941352-830b24c4-3c9e-40e7-a395-844b6f995d6f.png">
<img width="1521" alt="Screenshot 2023-02-19 alle 10 59 46" src="https://user-images.githubusercontent.com/15322138/219941356-b5ea5946-975c-48d3-990f-8a950924397d.png">
<img width="1522" alt="Screenshot 2023-02-19 alle 11 00 20" src="https://user-images.githubusercontent.com/15322138/219941363-fe9c0409-711e-4dde-b53b-ad12e49296d1.png">

I also tried to disable opencl but behavior is the same. Below you can also find output of darktable launched with "-d all" option from command line and configuration file (darktablerc)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_

open slideshow

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.3.0-661-g9e671636d-i386
* OS                :  mac osx ventura 13.2.1
* Memory            : 
* Graphics card     : AMD Radeon Pro 5500M 8 GB / Intel UHD Graphics 630 1536 MB
* Graphics driver   :  version 1.1
* OpenCL installed  :   OpenCL 1.2
* OpenCL activated  :  yes (but also without opencl behavior is identical)
* Xorg              :  XQuartz 2.8.5 (xorg-server 21.1.6)
* Desktop           :  mac osx
* GTK+              : gtk+ stable 2.24.33  gtk-mac-integration stable 3.0.1 (for compiled 4.3.0 version)  
* gcc               : Apple clang version 14.0.0 (clang-1400.0.29.202) Target: x86_64-apple-darwin22.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)?
yes both with stable and development version (from github)
 - Can you reproduce with a RAW or Jpeg or both?
 both
 - Are the steps above reproducible with a fresh edit (i.e. after discardring history)? 
 yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
NA
 - Is the issue still present using an empty/new config-dir
 yes
 - Do you use lua scripts?
 No
  
**OUTPUT OF DARKTABLE LAUNCHED WITH "-d all" option**
[output_debug.zip](https://github.com/darktable-org/darktable/files/10776607/output_debug.zip)

**OUTPUT OF DARKTABLE LAUNCHED WITH "-d all --disable-opencl" options**
[output_debug_noopencl.zip](https://github.com/darktable-org/darktable/files/10781575/output_debug_noopencl.zip)

 **CONFIG FILE**
[dt_config_file.zip](https://github.com/darktable-org/darktable/files/10776624/dt_config_file.zip)

**Comment by TurboGit** [comment]
Please try without OpenCL.

**Comment by cridemichel** [comment]
I did it is the same behavior…

Cristiano De Michele
***@***.***

**Comment by 7h0mas-R** [comment]
I have the same issue. 


* darktable version : 4.2.0
* OS                :  mac osx monterey 12.6
* Memory            :
* Graphics card     : Apple M1 GPU
* OpenCL installed  :   to my knowledge not (Metal)
* OpenCL activated  :  no 
* Xorg              :  XQuartz 2.7.11
* Desktop           :  mac osx
* CMAKE_BUILD_TYPE  : Release

* Can you reproduce with a RAW or Jpeg or both?
   both

**Comment by leanderhutton** [comment]
Confirm same problem 

- darktable 4.2.0
- MacOS Ventura 13.2
- Apple M2 Max
- OpenCL Activated and Deactivated

**Comment by leanderhutton** [comment]
Update: this seems to not be limited to macOS. I get the same thing on my Fedora 37 machine too. 

- darktable 4.2.0 (release compiled from source)
- Fedora Workstation 37
- Dell XPS 9720
- CPU: Intel Core i9-12900HK 
- GPU: nVidia RTX 3060 6GB
- Same behavior OpenCL on or off
- RAW and JPEG

![Screenshot from 2023-02-23 08-47-44](https://user-images.githubusercontent.com/120667157/220927085-c2d04cb2-bcf7-49d4-bb34-b535ab90472e.png)

**Comment by leanderhutton** [comment]
Side thought: both of these machines are HiDPi, I wonder if the problem is in the scaling? I have a regular DPI monitor at home I can test with when I get back.
