### ISSUE TITLE
timestamps are different between xmp and library.db, causes crawler to claim updated xmp

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#13679]
**Describe the bug/issue**
Subsequent to discussions in #13298 and #12257 there is still the issue, that after export the xmp gets updated, but the library.db not.

(no crash involved)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Export a set of photos, which have been edited time ago, to notice the time difference
2. Check xmp-date and timestamp on library.db

**Expected behavior**
same timestamp, so that crawler will not complain

@TurboGit SCNR

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49004103/219945432-b5f230fc-345f-497c-add6-56bc06142a6e.png)

**Platform**

* darktable version : 4.3.0+685~g3b1863495
* OS                : Linux - kernel 6.1.12-gentoo
* Distro            : Gentoo Base System release 2.9
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-525.85.05
* OpenCL installed  : Yes (opencl-headers-2022.09.30)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.35
* gcc               : 11.3.1_p20230120-r1
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version all recent versions >4.2**
 - Can you reproduce with a RAW or Jpeg or both? **also tiff**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **t.b.c.**
 - Do you use lua scripts? **no**

**Comment by TurboGit** [comment]
I have just pushed another missing XMP time-stamp modification time update. So the above could be fixed. A possible scenario is that you have done a oldest to newest sync and then later you got this message. Hopefully that's a plausible scenario for you and we have fixed another (last?) issue!

**Comment by AxelG-DE** [comment]
> A possible scenario is that you have done a oldest to newest sync and then later you got this message.

I do not fully get it. However, I will test and report (maybe no report today tho)

**Comment by jenshannoschwalm** [comment]
> However, I will test and report (maybe no report today tho)

Did you find time to test?

**Comment by jenshannoschwalm** [comment]
Axel, working through the "pending list", from my understanding it has been fixed in master. If there **are** issues still, please re-open :-)
