### ISSUE TITLE
Expose image orientation in lua struct dt_lua_image_t

### ISSUE THREAD

**Issue by rds13** [darktable-org/darktable#13686]
**Is your feature request related to a problem? Please describe.**
I am coding a lua exporter to create web album from darktable images.
While dealing with images in HTML I need to know the image orientation. This information is not available in dt_lua_image_t also it's available in dt_image_t.

**Describe the solution you'd like**
I would like the Lua object to be improved by exposing the orientation information.

**Comment by wpferguson** [comment]
This is what the dt_image_t orientation field has as values,

```
typedef enum dt_exif_image_orientation_t
{
  EXIF_ORIENTATION_NONE              = 1,
  EXIF_ORIENTATION_FLIP_HORIZONTALLY = 2,
  EXIF_ORIENTATION_FLIP_VERTICALLY   = 4,
  EXIF_ORIENTATION_ROTATE_180_DEG    = 3,
  EXIF_ORIENTATION_TRANSPOSE         = 5,
  EXIF_ORIENTATION_ROTATE_CCW_90_DEG = 8,
  EXIF_ORIENTATION_ROTATE_CW_90_DEG  = 6,
  EXIF_ORIENTATION_TRANSVERSE        = 7
} dt_exif_image_orientation_t;
```

I think what you want to know is if the image is in portrait or landscape orientation or is square.  So, aspect _ratio would probably better suit your needs.

For example:  I shoot an image in portrait orientation.  I apply a horizontal crop to it, so now it appears as landscape orientation.  `dt_image_t.orientation` will probably be a 6 or 8.  Aspect ratio will correctly indicate that the image is landscape.

**Comment by rds13** [comment]
I understand. You are right. But this flag is also not available in dt_lua_image_t.

**Comment by wpferguson** [comment]
Aspect ration > 1 is landscape, 1 = square, < 1 portrait. 

> But this flag is also not available in dt_lua_image_t.

Just making sure what to fix before I start fixing

**Comment by rds13** [comment]
Looking at the code, I tried to mimic what is necessary in this PR #13695 .

**Comment by rds13** [comment]
The PR is merged. We can close this issue.

**Comment by wpferguson** [comment]
The next time you do a PR to fix an issue, you can put Fixes #(number of issue) in the comments.  When the PR gets merged, the issue will get closed automatically.
