### ISSUE TITLE
[dt 4.2/4.3] LUT module crashes dt after loading LUT

### ISSUE THREAD

**Issue by mvrvelous** [darktable-org/darktable#13689]
Hi! When I try to load a LUT, dt will say "Working..." and crash after a few seconds. LUT type doesn't matter, .png or .cube both crash. Log file has no errors. Never had this problem before 4.2. Hoping someone has an idea, because dt is significantly faster now but I really need the LUT module!

I'm on Windows 10. Tried uninstalling, removing all (user) files and reinstalling, but to no avail. I have no idea where to look, especially without any errors in the log file. I just got myself a Canon R6 II so the older version do not support my photos. (Isn't it possible to update a few files that contain camera info? I forgot what it's called)

**UPDATE see my reply down here**

**Comment by mvrvelous** [comment]
> I cannot reproduce on GNU/Linux, I tried more than 20 Lut files in different format.

Thanks for checking. 

I've checked the Windows Event Viewer and it did report something:

Faulting application name: darktable.exe, version: 4.3.0.704, time stamp: 0x63f2fa56
Faulting module name: OpenCLOn12.dll, version: 0.0.0.0, time stamp: 0x63e2e678
Exception code: 0xc0000409
Fault offset: 0x00000000000f9345
Faulting process id: 0x7c90
Faulting application start time: 0x01d9458bac14a74e
Faulting application path: G:\Apps\darktable\bin\darktable.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.D3DMappingLayers_1.2302.1.0_x64__8wekyb3d8bbwe\x64\OpenCLOn12.dll
Report Id: 3b0311fe-1cad-47df-82b3-5802d91bf884
Faulting package full name: 
Faulting package-relative application ID:

**Comment by victoryforce** [comment]
Try uninstalling `OpenCL and OpenGL Compatibility Pack` and recheck if darktable works with OpenCL enabled.

**Comment by victoryforce** [comment]
@mvrvelous May I ask if my advice from the previous comment fixed the problem?  If dt is still crashing, please provide additional information. If you have no more crashes after that, please consider closing the issue, as there is not darktable's fault.
