### ISSUE TITLE
copy and import will copy and rename but not import

### ISSUE THREAD

**Issue by cspoeri** [darktable-org/darktable#13699]
I've got an issue with darktable 4.2.0 but I'm new to this as I'm trying to transition from Lightroom. I searched for similar issues but couldn't find my exact problem. 

I'm using darktable 4.2.0 on a Windows system with an AMD Ryzen 9 5900X, GeForce RTX 3080 Ti, 32 GB RAM. 
Photos are stored on a Synology NAS that's mounted as drive Z:\

When I'm trying to import files from my camera SD card through the USB-Cardreader the files are being importet onto my NAS. Darktable creates additional folders and renames files as set up in the importing options. However, afterwards I cannot find them in the collections. I could just import them from the "import" button but it's bugging me that "copy and import" only does half the trick and I'm wondering if I'm doing something wrong or if this is an acutal bug in darktable.

See attached screenshot for my importing options during copy and import.
![grafik](https://user-images.githubusercontent.com/125822347/220400974-dbeb1b7d-c018-4673-9c71-8c7a984608e7.png)

Thanks!

**Comment by TurboGit** [comment]
I cannot say why you don't find your collection. This works for me and many users as otherwise darktable will just be not usable at all. So we probably need more information. Maybe you have set some filters? Please try reset on the collection filter module.

**Comment by cspoeri** [comment]
Hi @TurboGit,
Thanks for your suggestion. Resetting the collection filter module didn't help. 
I tried to copy and import from my SD card again but I get this error for each image copied:
![grafik](https://user-images.githubusercontent.com/125822347/224330472-b9d60a75-dd67-4e5c-8815-af2ed7a2f08f.png)

Afterwards I can go to import and choose the directory the new images were copied to. Then importing them works.

**Comment by cspoeri** [comment]
Posting the solution to this issue as I just found the typo that was the root cause.
I had written a "\\" after the drive letter instead of a "/".

This way, copy and import works just fine:
![grafik](https://github.com/darktable-org/darktable/assets/125822347/e26b88b2-5000-4f68-aa0a-4e40cd6349d7)
