### ISSUE TITLE
exr files can not be recognised

### ISSUE THREAD

**Issue by DaemosOriginal** [darktable-org/darktable#13709]
I downloaded darktable via chocolatey. I use darktable 4.2.0 on windows 10.

I wanted to open / import an exr file. I have created this via Blender. The file was with zip compression. When darktable was opened, I saw that all my exr files that were previously recognised are now no longer recognised. It made sense at first, because these files were no longer in the folder. But the imported file did not work either. 

I have already reinstalled darktable and restarted my pc, but have not found a solution even by googling.

**Comment by kmilos** [comment]
Chocolatey probably built the package w/o OpenEXR support.

Check the output of `darktable --version`
