### ISSUE TITLE
east Asian font size is wrong in vector scope

### ISSUE THREAD

**Issue by HSUfineprint** [darktable-org/darktable#13703]
**Describe the bug**
Chinese font size is very big in vector scope. It only affects harmony style names and rotation angle.

**To Reproduce**
1. Change language to "zh_TW"
2. Go to 'darkroom'
3. Switch to 'vectorscope'
4. Choose 'RYB'
5. See error

**Expected behavior**
The font size should be consistent in different languages.

**Screenshots**
![螢幕擷取畫面 2023-02-22 105521](https://user-images.githubusercontent.com/109933528/220510433-81c9f12d-2306-4a2a-8b2b-5b4d20491c84.jpg)
![螢幕擷取畫面 2023-02-22 105517](https://user-images.githubusercontent.com/109933528/220510459-077d3353-990e-424b-a19d-9b85a4c65329.jpg)

**Platform**
* darktable version : 4.3.0+717~g7efb081ddb
* OS : Win10 professional 22H2 (19045.2604)

**Comment by HSUfineprint** [comment]
It also affects Japanese.

![螢幕擷取畫面 2023-02-22 163058](https://user-images.githubusercontent.com/109933528/220565123-fbbf12ed-2e6d-4898-b2dd-8b6a611a798e.jpg)

**Comment by Nilvus** [comment]
@Mark-64: I see on your code, that size for that part is set with Pango. If I'm not wrong starting line 1185 of histogram.c regarding your PR. I don't know how Pango deal with different fonts ("european ones", "asian ones"). Can you check that issue?

**Comment by Mark-64** [comment]
I will have a look
