### ISSUE TITLE
[4.2.1] is it true that "JPEG files are identified using magic bytes instead of file extension" as release notes say?

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#13711]
The release notes say that "JPEG files are identified using magic bytes instead of file extension", it correspondes to commit @d318993cabae7315b34482390c14a9f38a3faad3

Actually the code shows various lines like `if(!strcmp(ext, "jpg") || !strcmp(ext, "jpeg"))`. Apparently jpg files are still identified by the extension somewhere

**Comment by victoryforce** [comment]
> Actually the code shows various lines like `if(!strcmp(ext, "jpg") || !strcmp(ext, "jpeg"))`. Apparently jpg files are still identified by the extension somewhere

The code marked with what tag? Here is the code from release 4.2.1:

https://github.com/darktable-org/darktable/blob/release-4.2.1/src/common/imageio_jpeg.c#L744

**Comment by paolobenve** [comment]
image.c 1484:
```
if(override_ignore_jpegs == FALSE && (!strcmp(ext, "jpg") || !strcmp(ext, "jpeg"))
```

image.c 1577:
```
// in case we are not a jpg check if we need to change group representative
if(strcmp(ext, "jpg") != 0 && strcmp(ext, "jpeg") != 0)
```

image.c 1602:
```
// if the group representative is a jpg, change group representative to this new imported image
if(!strcmp(ext_lowercase, "jpg") || !strcmp(ext_lowercase, "jpeg"))
```

colorin.c 1810:
```
if(!strcmp(ext, "jpg") || !strcmp(ext, "jpeg"))
```

Besides that, a function is defined whose name is `dt_imageio_get_type_from_extension`: does it make sense, if the file type is identified using magic bytes?

**Comment by victoryforce** [comment]
Ah, I read it late at night and wasn't paying enough attention to the wording. Indeed, you write that the file extension check remains in other places. This is true. 4.2.1 included a fix for one specific issue, the inability to __import__ an image if it is actually a JPEG but the file has an inappropriate extension.
 
> Besides that, a function is defined whose name is `dt_imageio_get_type_from_extension`: does it make sense, if the file type is identified using magic bytes?

Yes of course that makes sense. There was no global change in format detection from checking file extensions to checking magic bytes.

**Comment by todd-prior** [comment]
I alway wonder why the module order doesn 't default to jpg when I open a new one.... I can make quite a difference in the look of the image depending on the modules and I suppose there is a good reason for this order but it doesn't get used in my hands anyway unless I assign it..... Am I missing something??

**Comment by paolobenve** [comment]
I, too, noted that the jpg module order is not automatically set when a jpg image is imported

**Comment by victoryforce** [comment]
If there is no problem with the wrong extension of the image file, then the exact type of filter at the beginning of the image loader does not affect further actions at all. So it's clear that the problem you describe has nothing to do with the method of checking for JPEG format.

> jpg module order is not automatically set when a jpg image is imported

If this is the case and there is no similar bug report on Github, please raise an issue, as this is an obvious bug.

**Comment by todd-prior** [comment]
> If this is the case and there is no similar bug report on Github, please raise an issue, as this is an obvious bug.

I have just gotten around to this... thx for the suggestion...

**Comment by victoryforce** [comment]
Since this issue was not a problem report or a feature request, but rather a question that received an explanation, I am closing it.
