### ISSUE TITLE
Windows: exporting gigapixel images kills darktable

### ISSUE THREAD

**Issue by bediicco** [darktable-org/darktable#13717]
Hello,

please help me to make a bug report. I do not know where to get alle the sys-logs etc.

I am working on Windows 10 Pro 64 bit on a Xeon E5 2695V3 (14/28 Core) with 128GB RAM, but this happens exactly the same way with 48GB and 64GB of RAM and different other setups in hardware.

When editing an up to 60.000 x 40.000 Pixel JPEG (standard JPEG) with around 180-550 MB filesize editing works fine.

But when exporting as JXL, as JPG, as TIFF, it is running some minutes (every time) consuming all my RAM up and down, my CPU up and down, ... - and then, darktable is closed without error message and no image is saved.

I tried this several times with several gigapixel images and several export of kind of JPG or TIFF, with different RAM sizes, working from SSD or NVME.

**Where can i get some logs what happens here?**

Today i will install Ubuntu and run it on Ubuntu to check it on Linux.

**Comment by bediicco** [comment]
By the way i changed the ressource consumption of darktable, too.

**Comment by gi-man** [comment]
Welcome. Can you provide the details from the Issue template? Mainly, what version of darktable, opencl, ...

The FAQ has a section explaining how to get the logs from windows.

**Comment by bediicco** [comment]
OpenCL is unchecked. As said, i am using my CPU.

I will give more infos asap

**Comment by ralfbrown** [comment]
I believe the operating system is simply killing the program because you're out of RAM.

Internally, dt represents images as 16 bytes per pixel, and every image operation needs at least two full-size buffers (the module's input and output).  Tiling can reduce the memory requirements for intermediate buffers needed by a module, but 32 bytes per pixel is the absolute minimum memory requirement when exporting at full size.

So 32 * 60,000 * 40,000 = 76,800,000,000 or about 75 GiB.  Remember, that's the absolute minimum.  In practice, you'll need closer to twice that if you're using some of the more complex modules.  My guess is that a 45,000x30,000 image should work fine on your 128GB machine, if rather slowly.  You can get that if you set the export size to that and *un*-check "high-quality resampling" so that the image is downsampled before it needs 32 bytes per pixel.

**Comment by bediicco** [comment]
> I believe the operating system is simply killing the program because you're out of RAM.

@ralfbrown Yes, it looks like. But the RAM usage is somewhere between 100% and less. But, wondering, the RAM usage overall is 100% half the time - and nothing happens for minutes (paired with 100% CPU). DT will be killed when RAM usage is less than that, say, 80%, and CPU is anywhere. Maybe, it asks for much more RAM this moment. I hope to find something like this in the log.

> In practice, you'll need closer to twice that if you're using some of the more complex modules. My guess is that a 45,000x30,000 image should work fine on your 128GB machine, if rather slowly. You can get that if you set the export size to that and un-check "high-quality resampling" so that the image is downsampled before it needs 32 bytes per pixel.

I will test this and have it in mind.

So, i have some questions:

1) if i have images of 3 or 5 or 20 Gigapixels, is it correct that DT needs tons of memory-modules? No `NVME\temp` usage instead? I cannot believe that i must have 256GB or 768GB or 1.5TB RAM?

2) what does `darktable resources` settings? Is there no difference between `small | default | large | unrestricted`?

3) is it better to have a 8GB or maybe 24GB **GPU** instead of 128GB RAM?

4) what is about `temp` usage? Does DT not use my NVME Flash drive?

Thank you for your help, i will have your message in mind when testing later!

**Comment by ralfbrown** [comment]
>     1. if i have images of 3 or 5 or 20 Gigapixels, is it correct that DT needs tons of memory-modules? No `NVME\temp` usage instead? I cannot believe that i must have 256GB or 768GB or 1.5TB RAM?

Unfortunately, that's the way it's implemented.  A less memory-hungry approach would be far slower.
 
>     2. what does `darktable resources` settings? Is there no difference between `small | default | large | unrestricted`?

I don't know this part well enough to answer in detail.  I do know that it adjusts how much memory dt thinks it can use as a percentage of installed RAM.  If lots of other programs are in memory at the same time,  it could ask for enough to either force use of swap/temp or get the program killed for lack of RAM.

>     3. is it better to have a 8GB or maybe 24GB **GPU** instead of 128GB RAM? Are those images restricted to 24GB GPU RAM, paying thousands of dollars for such tiny images?

I don't know whether the code does the tiling on the CPU and then transfers individual tiles to the GPU (much slower) or uses full-size input and output buffers on the GPU.  But yes, the bigger the image, the more GPU RAM you can expect to need.

>     4. what is about `temp` usage? Does DT not use my 32GB/s NVME PCIe Flash drive?

dt knows nothing about that and does not use temporary files; it's all up to the operating system to use it as swap space and pretend there is more RAM than actually installed.  And even NVMe swap will be 10 to 100 times slower than main memory.  (It's not just the throughput, there is also considerable overhead in actually moving the data back and forth on demand.)

>     5. This happens the same way with 48GB of RAM? Why is it not been killed in the first seconds of export?

The earliest  modules work with two or four bytes per pixel.  On such large images, it takes a while to do the decoding, white balancing, and demosaic.

**Comment by gi-man** [comment]
> 2\. what does `darktable resources` settings? Is there no difference between `small | default | large | unrestricted`?

https://docs.darktable.org/usermanual/4.2/en/special-topics/mem-performance/#darktable-resources

**Comment by gi-man** [comment]
Getting your log file with -d perf or tiling might help understand what is going on.

**Comment by bediicco** [comment]
Thank you, i will post the log in around 4 hours

**Comment by bediicco** [comment]
Sorry. I tried `darktable -d perf` different ways, but nowhere in `AppData` or on the flashdrive will `darktable-log.txt` be created.

![image](https://user-images.githubusercontent.com/126161988/221014511-34086041-3736-4eba-8b2f-a8c9cf6603fd.png)

There is no `INetCache` folder or logfile named `darktable-log.txt` on my disk.

``` batch
systeminfo
Microsoft Windows 10 Pro
10.0.19045 Nicht zutreffend Build 19045
```

**Comment by gi-man** [comment]
https://www.darktable.org/about/faq/#faq-windows-logs

> (This is a hidden folder in Windows, therefore copy and paste the link to windows explorer for access)`

**Comment by bediicco** [comment]
As you can see on the posted image above there are hidden folders visible like `IECompatCache` and `IECompatUaCache`

**Comment by gi-man** [comment]
You have to use the keyboard and type it. You can also change the folder settings to not Hide the Protected Operating System filess and folders. 
![image](https://user-images.githubusercontent.com/97920861/221042771-d656d756-0c7f-42e0-986f-9578d6648b0d.png)

**Comment by bediicco** [comment]
I tried but it gave just an empty file. But - now there is a log. I will just give the last lines:

```batch
[dt_imageio_export_with_flags] 
 denoiseprofile colorin diffuse atrous sharpen colorbalancergb filmicrgb bilat velvia colorout finalscale gamma (12)
129,551196 [modify roi OUT]       export   denoiseprofile.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551249 [modify roi OUT]       export          colorin.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551313 [modify roi OUT]       export          diffuse.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551376 [modify roi OUT]       export           atrous.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551420 [modify roi OUT]       export          sharpen.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551471 [modify roi OUT]       export  colorbalancergb.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551531 [modify roi OUT]       export        filmicrgb.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551589 [modify roi OUT]       export            bilat.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551640 [modify roi OUT]       export           velvia.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551682 [modify roi OUT]       export         colorout.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551725 [modify roi OUT]       export       finalscale.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551787 [modify roi OUT]       export            gamma.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080*39050 scale=1,00
129,551840 [export] creating pixelpipe took 0,259 secs (0,250 CPU)
129,551883 [dt_imageio_export] imgid 3, pipe 59080x39050, range 1073741823x1073741823 --> exact 1, upscale 0, hq 0, corrected 0, scale 1,0000000, corr 1,000000, size 59080x39050
129,551933 [pixelpipe_process] [export] using device -1. Cache: used=70406MB
[memory] before pixelpipe process
[memory] max address space (vmpeak):    112701472 kB
[memory] cur address space (vmsize):    112701468 kB
[memory] max used memory   (vmhwm ):     45276064 kB
[memory] cur used memory   (vmrss ):     36629476 Kb
129,552013 [modify roi IN]        export         colorout.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552084 [modify roi IN]        export           velvia.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552130 [modify roi IN]        export            bilat.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552194 [modify roi IN]        export        filmicrgb.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552240 [modify roi IN]        export  colorbalancergb.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552294 [modify roi IN]        export          sharpen.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552336 [modify roi IN]        export           atrous.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552390 [modify roi IN]        export          diffuse.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552441 [modify roi IN]        export          colorin.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552492 [modify roi IN]        export   denoiseprofile.    (   0/   0) 59080x39050 scale=1,00  --> (   0/   0) 59080x39050 scale=1,00
129,552550 [dev_pixelpipe] took 0,000 secs (0,000 CPU) initing base buffer [export]
129,552581 [process CPU]          export   denoiseprofile. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
[Entrauschen (Profil)] unable to allocate working memory
134,355702 [dev_pixelpipe] took 4,803 secs (9,906 CPU) [export] processed `Entrauschen (Profil)' on CPU, blended on CPU
[dev_pixelpipe] module `Entrauschen (Profil)' min: (0,000000; 0,000000; 0,000000) max: (1,000000; 1,000000; 1,000000) [export]
137,256300 [process CPU]          export          colorin. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
146,988850 [dev_pixelpipe] took 9,733 secs (239,172 CPU) [export] processed `Eingabefarbprofil' on CPU, blended on CPU
[dev_pixelpipe] module `Eingabefarbprofil' min: (0,475202; -33,096001; -78,781433) max: (99,999474; 56,046410; 80,131409) [export]
image colorspace transform Lab-->RGB took 2,524 secs (62,500 CPU) [diffuse ]
152,242209 [process CPU]          export          diffuse. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0

(darktable:1920): Gtk-WARNING **: 21:19:53.092: Failed to set text 'Diffusion & Schärfen konnte keinen Speicher reservieren, überprüfe die RAM-Einstellungen' from markup due to error parsing markup: Fehler in Zeile 1: Entität endete nicht mit einem Semikolon; wahrscheinlich haben Sie ein &-Zeichen benutzt, ohne eine Entität beginnen zu wollen – umschreiben Sie das »&« als &amp;
152,245900 [dev_pixelpipe] took 2,527 secs (62,500 CPU) [export] processed `Diffusion / Schärfe' on CPU, blended on CPU
[dev_pixelpipe] module `Diffusion / Schärfe' min: (0,000000; 0,000000; 0,000000) max: (1,000000; 1,000000; 1,000000) [export]
image colorspace transform RGB-->Lab took 1,997 secs (50,641 CPU) [atrous ]
157,145016 [process CPU]          export           atrous. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
[Kontrast-Equalizer] unable to allocate working memory
159,895061 [dev_pixelpipe] took 4,747 secs (61,484 CPU) [export] processed `Kontrast-Equalizer' on CPU, blended on CPU
[dev_pixelpipe] module `Kontrast-Equalizer' min: (12,406607; -68,877754; -81,816086) max: (99,999474; 72,279930; 111,285385) [export]
162,550189 [process CPU]          export          sharpen. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
174,328449 [dev_pixelpipe] took 11,778 secs (308,094 CPU) [export] processed `Schärfen' on CPU, blended on CPU
[dev_pixelpipe] module `Schärfen' min: (-5,052355; -68,877754; -81,816086) max: (105,852020; 72,279930; 111,285385) [export]
image colorspace transform Lab-->RGB took 2,198 secs (58,578 CPU) [colorbalancergb ]
179,058109 [process CPU]          export  colorbalancergb. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
429,607991 [dev_pixelpipe] took 252,748 secs (6963,203 CPU) [export] processed `Farbbalance RGB' on CPU, blended on CPU
[dev_pixelpipe] module `Farbbalance RGB' min: (0,000928; 0,000000; 0,000000) max: (1,179508; 1,176603; 1,182297) [export]
432,618301 [process CPU]          export        filmicrgb. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
478,615623 [dev_pixelpipe] took 45,997 secs (1251,672 CPU) [export] processed `Filmic RGB' on CPU, blended on CPU
[dev_pixelpipe] module `Filmic RGB' min: (0,001607; 0,000000; 0,000000) max: (0,872645; 0,874407; 0,892179) [export]
image colorspace transform RGB-->Lab took 1,801 secs (48,188 CPU) [bilat ]
483,323269 [process CPU]          export            bilat. IN (   0/   0) 59080x39050 scale=1,00. OUT (   0/   0) 59080x39050 scale=1,00, final 59080x39050, backbuf 0x0
Magick: caught exception 0xC0000005 "Access violation"...
```

The last one is `bilat`? So what ist bilat? To clear my desktop i have deleted all files. I will go further next evening.

I can not reproduce this filter setting because all files are deleted to clear my folders.

**Comment by gi-man** [comment]
Like Ralf mentioned, there is a problem with memory. The first issues shows up here (google translate from german):

`(darktable:1920): Gtk-WARNING **: 21:19:53.092: Failed to set text 'Diffusion & Sharpening could not allocate memory, check RAM settings' from markup due to error parsing markup: Error in line 1: Entity did not end with a semicolon; you probably used an & without wanting to start an entity - rewrite the "&" as &amp;`

then it continues with:
`[Kontrast-Equalizer] unable to allocate working memory`

bilat = surface blur

You never mentioned what version of darktable you are using. 4.2.1? As a test, what happens if you export the same image, but without D&S, contrast equalizer and suface blur off?

**Comment by ralfbrown** [comment]
bilat is local constrast.  bilateral is surface blur.  Yeah, confusing.

The first error is actually even earlier - denoise(profiled) also fails to allocate working memory and just passes the image through unchanged.

There's a missing check for failed allocation in src/iop/bilat.c.  From a quick look, I would guess that you are using local laplacian rather than bilateral mode, since bilateral will spit out an error message on allocation failure (but then die anyway because there's no null-pointer check).

**Comment by parafin** [comment]
> The first error is actually even earlier - denoise(profiled) also fails to allocate working memory and just passes the image through unchanged.

I wonder if it’s better to fail than to produce wrong output?..

**Comment by ralfbrown** [comment]
Better to skip a module than crash, but there should probably be some notification in the GUI in that case.  The modules which use dt_iop_alloc_image_buffers to obtain their working memory will set the module trouble flag, but that doesn't help in this case because the module GUI isn't active on exports.  It could be enhanced to pop up a notification when run for the export pipe.

**Comment by parafin** [comment]
There's also darktable-cli. I think it should fail, so this case could be caught in scripts.
