### ISSUE TITLE
Filter for camera model doesn't work

### ISSUE THREAD

**Issue by PulsarFX** [darktable-org/darktable#13712]
**Describe the bug/issue**
Using the quick filter text or the collection filter using the "search" field, does not bring up the images with a given camera model. 

**To Reproduce**
Here is a sample setup with images to filter.
For "model" it says "NIKON Z 50". No filter is present:
![grafik](https://user-images.githubusercontent.com/4960210/220762126-8a81b1ef-7681-497d-b14c-8a7771af1a99.png)

Then, enter NIKON Z 50 in the search text and get this result: 
![grafik](https://user-images.githubusercontent.com/4960210/220762345-bfee503c-b3cb-4e90-b669-849bed8e45f7.png)

this happens for any combo of NIKO, Niko, nikon, %nikon, ...

**Expected behavior**
I'd expect, that the model and lens information is treated as image metadata, too, like the tooltip says.
![grafik](https://user-images.githubusercontent.com/4960210/220762982-22eeb368-3913-4b3f-a004-4b3f2505d146.png)

 
**Platform**
* darktable version : 4.2.0 flatpak
* OS                : Linux Mint
* Linux - Distro    : Mint 21.1

**Additional context**
- Happens for my Nikon NEF files and plain jpg files from a Minolta camera.

**Comment by gi-man** [comment]
Use the collection module.

![image](https://user-images.githubusercontent.com/97920861/220804306-80bd1a90-b9c4-4202-8f94-f4781c7aeefe.png)

**Comment by PulsarFX** [comment]
Oh, that's great.
 So the search filter works as expected?

**Comment by kmilos** [comment]
Something is also a bit off here - the model should not be "NIKON Z 50" but just "Z 50", and maker not "NIKON CORPORATION" but "Nikon". Same for the D5500...

**Comment by kmilos** [comment]
And btw, the filter works for me if I use just "z 50" or "d5500"?

**Comment by PulsarFX** [comment]
May be from a firmware update of nikon? They released a new firmware for z50 recently.
If needed, I can provide sample files from my camera.

**Comment by kmilos** [comment]
> May be from a firmware update of nikon?

Nope, all Nikons (new and old) have "NIKON CORPORATION" + "NIKON D/Z..." since, like, forever (and kudos for them for at least being consistent w/ this unlike Ricoh, Olympus, and Leica to name some). Just like for other cameras, it is expected we simplify/sanitize this to just "Nikon" + "D/Z...".

**Comment by Nilvus** [comment]
Seems that this could be closed. @PulsarFX?

**Comment by PulsarFX** [comment]
If the "search" filter works as intended, by not looking at model or maker fields, then yes. 
Although, I'd expect that this particular filter would look in any available field there is in a file. 

Regarding the naming issues, I don't know.

**Comment by Nilvus** [comment]
Naming issues are not related to darktable. Those are set with Exiv2. But maybe, there's also some refresh issues (seems suggested by @kmilos. Correct me if I'm wrong @kmilos), so a different issue.

About search field, I agree with you that this could be improved with string like that. This would be more a feature request to improve it than issue like that one.

So regarding all that, maybe would be better to close that issue and open new ones: a feature request to improcve search field, and issue for name refresh issues (if there are really related to darktable code only).

**Comment by kmilos** [comment]
Make/model refresh is definitely in the scope of rawspeed and darktable, so we either rename this issue, or open a new one.

**Comment by PulsarFX** [comment]
I've created a new Feature Request for the search filter.

Regarding the camera naming, I'm not sure what to write. I don't know why these fields have to be changed by darktable or rawspeed. 
@kmilos , can you create a new bug for this?

For me it looks like this:
exiftool shows:
```
Make                            : NIKON CORPORATION
Camera Model Name               : NIKON Z 50
```
this is also shown in lighttable image information - until it was once opened in darkroom.
Then darktable shows:
```
maker: Nikon
model: Z 50
```

**Comment by victoryforce** [comment]
@kmilos Sorry, I just didn't see that you tagged me. I read some issues and PRs in email and do not open them on the site if the topics do not interest me. The problem with notifications from Github is that after editing a comment, it is not re-sent to the email. Therefore, tagging someone in the edited version of the comment is not the best option, it is better to write a new comment.

> @victoryforce I think this is because we no longer do the file extension check, so the lighttable loading succeeds for the NEF files in the TIFF loader already? So we either restore the extension check for TIFF only to avoid handling of TIFF-based raws (NEF, ARW, DNG...), or we move the rawspeed/libraw loaders before the TIFF one?

In fact, no changes were made to the way the TIFF loader determines the file format. And precisely for the reason that RAW files can be in a TIFF container. Therefore, checking for TIFF magic bytes does not guarantee that we are dealing with TIFF format, and not one of the RAW formats.

**Comment by kmilos** [comment]
Thanks for having a think @victoryforce, it looks like I'll just have to step through in debugger when I find some time. Still don't get why it works as expected for Pentax PEFs but not for Nikon NEFs, they're both TIFF based...
