### ISSUE TITLE
Bogus over-alignment on pointer types

### ISSUE THREAD

**Issue by jakubjelinek** [darktable-org/darktable#13729]
find -type f -print0 | xargs -0 grep '\*[^]]*DT_ALIGN'
./src/iop/highlights.c:  float *const DT_ALIGNED_ARRAY tempbuf = dt_alloc_perthread_float(4 * width, &padded_size); //TODO: alloc in caller
./src/iop/diffuse.c:  float *const DT_ALIGNED_ARRAY tempbuf = dt_alloc_perthread_float(4 * width, &padded_size); //TODO: alloc in caller
./src/iop/cacorrectrgb.c:  float *const restrict DT_ALIGNED_PIXEL in_out = dt_alloc_align_float(width * height * 4);
./src/common/color_picker.c:      float *const DT_ALIGNED_ARRAY tempbuf = dt_alloc_perthread_float(4 * roi->width, &padded_size); //TODO: alloc in caller
./src/common/bspline.h:inline static void decompose_2D_Bspline(const float *const DT_ALIGNED_PIXEL restrict in,
./src/common/bspline.h:                                        float *const DT_ALIGNED_PIXEL restrict HF,
./src/common/bspline.h:                                        float *const DT_ALIGNED_PIXEL restrict LF,
./src/common/bspline.h:    float *restrict DT_ALIGNED_ARRAY const temp = dt_get_perthread(tempbuf, padded_size);

shows a bunch of bogus uses of DT_ALIGNED_ARRAY nad DT_ALIGNED_PIXEL macros.  In all these cases, the
`__attribute__((aligned(64)))` or `__attribute__((aligned(16)))` attributes apply not to what a pointer points to, but rather to
the pointer type itself.  So basically asks that e.g. the tempbuf variable if placed into memory has 64 byte aligned address
and similar.  I don't see what this would be good for.  At least for GCC `__builtin_assume_aligned` is the way to tell the compiler
that a certain pointer has what it points to sufficiently aligned and after all, darktable already heavily uses it, I think all of dt_alloc_perthread_float, dt_alloc_align_float and dt_get_perthread already do use it, so adding anything further is not needed (and putting it on the pointer type wrong).
As for decompose_2D_Bspline arguments, you could use temporaries and __builtin_assume_aligned on them if needed, I guess declaring in/HF/LF as [] arrays with DT_ALIGNED_PIXEL float or DT_ALIGNED_PIXEL const float element types is undesirable because then you can't add restrict.

**Comment by TurboGit** [comment]
I'm not 100% clear about this. Your proposal is to remove DT_ALIGNED_PIXEL from above quoted lines? What could be happening with those lines? Just over alignment or something worst? Do you plan to provide a PR?
