### ISSUE TITLE
Lighttable sort by criteria lost when navigating collections in tag treeview

### ISSUE THREAD

**Issue by smartintec** [darktable-org/darktable#13731]
**Introduction**

---------------------------------------------------------------
I searched the wiki and open issues here but couldn't find what I'm looking for.

**Describe the bug/issue**

The sort criteria in the lighttable (top bar) gets reset to default "by filename" when I navigate through my collections down the treeview of tags.
This is unexpected and differs from the behaviour when I navigate through the top level tags.
Therefore I consider this an issue.

**To Reproduce**

Open DT with some images.
Create some tags with a hierarchy: eg. animals|dogs and landscapes|seaside.
Assign those to some images.
Set collection view to 'tagging' to see the expandable treeview.
Double click on "animals" and in the top bar of the lighttable set the "sort by" criteria from filename to datetime.
->Images will be sorted accordingly by datetime.
Now click on another TOPLEVEL tag like "landscapes" in the collection treview of tags. 
**-> the sortby criteria will remain on "datetime". [expected behaviour]**
Expand the treeview with the litte arrow to see the NEXT LEVEL tags.
Doubleclick on "dogs" or any other (like "seaside").
**-> the sortby criteria will change to "filename". [issue?!]**

**Expected behavior**
I was expecting the sort criteria to remain the same (see above).

As a user of multiple image filename conventions I set the sort criteria to datetime and the collection to 'tagging'. This works just fine as long as i stay in the top level tags (trunk). But when i open a tag branch the sort criteria needs to be configured everytime as it resets to the first item (filename), which is not, what i want.
Have i missed something here?
Can i make "datetime" the first item in the "sort by" list to get around this problem?

**Platform**

* darktable version : 4.2.0
* OS                : Win10

**Comment by TurboGit** [comment]
Seems like the filtering is reset when selecting the leaf of a hierarchical tag.

**Comment by TurboGit** [comment]
@AlicVB : Can you have a look? TIA.
