### ISSUE TITLE
Strange behavior of dt 4.2.1 for Rotate and Perspective module on older images

### ISSUE THREAD

**Issue by gpagnon** [darktable-org/darktable#13735]
**Describe the bug/issue**
When I open in dt 4.2.1 some files processed with an older dt version, when I open/close the Rotate and Perspective module a slight (but not at all negligible) rotation takes place.  In other words, if I make some changes in the module and then I close the module, an additional rotation is applied to the image.

**To Reproduce**
1. Open the attached image in dt 4.2.1
2. Click on the Rotate and Perspective Module to open it
3. Click again on the module to close it
4. You should notice a rotation taking place every time you close and open the module (with the module always active)

I did not notice this behavior with the previous dt version 

**Platform**
darktable version: 4.2.1 (standard dmg binary as provided on github)
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Processor 2 GHz Quad-Core Intel Core i5
Memory 16 GB 3733 MHz LPDDR4X
Graphics Intel Iris Plus Graphics 1536 MB
Mac OS version 12.6.3
Open CL activated
[Archive.zip](https://github.com/darktable-org/darktable/files/10830533/Archive.zip)

By the way, if I wipe the history from the image, the issue goes away.

**Comment by TurboGit** [comment]
I see and this is expected. Here is the why.

You have in the history "crop and rotate" with a little rotation -0.36°.

When you open "rotate and perspective" (which comes before in the pipe) all other crop and rotation are disabled. This is necessary to be able to do proper and accurate change in this module. When you close the module again, the other modules are activated and then they also apply their rotation.

Note that "crop and rotate" is now deprecated. But anyway you'll get the same behavior the the new crop module. If it is set to crop then when opening the "rotation and perspective" the crop will be temporary disabled for the same reasons.

I let you close this issue.

**Comment by gpagnon** [comment]
Great, thank you!
