### ISSUE TITLE
history stack is altered on opening an already edited image in darkroom

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#13737]
with my recent build of current master the history stack of images are altered when reopened in darkroom

sample:
[20230104-IMG_8622.CR3.a.xmp.txt](https://github.com/darktable-org/darktable/files/10830611/20230104-IMG_8622.CR3.a.xmp.txt)
[20230104-IMG_8622.CR3.xmp.txt](https://github.com/darktable-org/darktable/files/10830612/20230104-IMG_8622.CR3.xmp.txt)

the added history items can be identified via it's tooltip (thats shown for all history stack items you never touched - but thats a different issue ;)

![image](https://user-images.githubusercontent.com/39386816/221347904-ff770bc8-364b-4c38-bc8a-8ce9f268ace6.png)

**To Reproduce**
preparation: do an initial edit with an older build (my good build is darktable-4.3.0+732~g410cba678) - just open in darktable and close again, so the initial history stack is created
1. open that image with current master (my bad build is darktable-4.3.0+797~gd582e8bcd)
2. check history stack and find new items with instance names

**Which commit introduced the error**
need to bisect but based on my recent builds it was introduced between
darktable-4.3.0+732~g410cba678 and darktable-4.3.0+797~gd582e8bcd

**Platform**
* darktable version : darktable-4.3.0+797~gd582e8bcd
* OS                : OSx arm64

**Comment by TurboGit** [comment]
No need to bisect, that's 5f3d4c74ce1558ccfe96259ce2984d85e73d3102 (po/history-name-label). This is because the label is now "properly" set on the history stack. The image does not change as the history parameters are not changed at all. But the label is not updated on the history and so you may see some entries with the label.
