### ISSUE TITLE
Highlight reconstruction artifacts when using guided laplacians and opencl

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#13743]
**Introduction**
I get artifacts in darkroom rendering and exported jpg or tiff, when using guided laplacians and opencl. I use git master branch. 

The artifacts disappear when using git master when i start darktable with --disable-opencl. The issue does not exist in git release-4.2.0 tag code. Darktable 4.2.0 code works fine _with_ opencl on.

---------------------------------------------------------------

**Did you buy darktable from an application store ?**

NO, I build from git master source  on Linux Debian 11.6.

**Describe the bug/issue**
I get artifacts in darkroom rendering when using guided laplacians and opencl. I use git master branch. The artifacts disappear when i start darktable with --disable-opencl. The issue does not exist in git release-4.2.0 tag code.

**To Reproduce**
1. Download example raw (Canon CR2, Canon 5D mk IV): [0Y8A6794.CR2](https://drive.google.com/drive/folders/1C1BitifMPZ138gz94yBQ61kpHkZR1B44?usp=share_link) (I have the same issue in other raw files as well).
2. Import to darktable
3. Go to darkroom
4. Delete image history, then set `highlight reconstruction -> guided laplacians -> iterations = 30`, activate `sharpen module (defaults)`
5. Zoom to 100% as shown on pictures below. When using guided laplacians and opencl then some artifacts appear. They are highlighted in the red circles. Sometimes the rendering i slightly different, if I move around in 100% zoom, but some artifacts are always there.

Screenshot of darkroom window at 100% zoom git master opencl on (artifacts in red circles):
![Screenshot dt-opencl_on_master](https://user-images.githubusercontent.com/42386052/221364414-7fc2438c-6fa6-40b5-9fbe-069d6cd51e4c.jpg)

**Expected behavior**
Render without artifacts. 

There are two workarounds:

- In fact staying on git master but starting darktable with with opencl disabled `./darktable --disable-opencl` works. 

- Also checking out git release-4.2.0 tag code works, _with_ opencl active.

Screenshot of darkroom window at 100% zoom git master opencl off (no artifacts):
![Screenshot dt-opencl_off_master](https://user-images.githubusercontent.com/42386052/221365039-b29df4cd-7b86-496e-aad6-f9f74f8f4829.png)

Screenshot of darkroom window at 100% zoom git release-4.2.0 tag opencl on (no artifacts):
![Screenshot dt-opencl_on_420](https://user-images.githubusercontent.com/42386052/221365108-d3c95377-f093-4cdb-8efb-70bb3b6136cb.png)

**Which commit introduced the error**
The issue does not exist in git release-4.2.0 tag code.

**Platform**

* darktable version : darktable 4.3.0+801~g0f828f3f41

* OS                : Linux debian 5.10.0-21-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
* Linux - Distro    : Debian 11.6
* Memory            :  16 GB
* Graphics card     :  NVIDIA Corporation TU104GL [Quadro RTX 4000]
* Graphics driver   :  Nvidia Driver Version: 470.161.03
* OpenCL installed  : Yes, OpenCL 3.0 CUDA 11.4.309
* OpenCL activated  : Yes
* Xorg              : X11
* Desktop           :  Gnome 3.38.5
* GTK+              :  3.24.24
* gcc               :  gcc (Debian 10.2.1-6) 10.2.1 20210110
* cflags            : 
* CMAKE_BUILD_TYPE  :  not stated. default.

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **Introduced after 4.2.0.** 
 - Can you reproduce with a RAW or Jpeg or both? **RAW**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file 
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by jenshannoschwalm** [comment]
Issue reproduced. Will investigate ...

**Comment by KarlMagnusLarsson** [comment]
Thank you @jenshannoschwalm, for the feedback and confirmation. I will unfortunately be on a business trip 26-Feb -- 3-March, away from my computer. I will be back 4-March and can help with testing from that date.

**Comment by jenshannoschwalm** [comment]
Will take care of this next week

**Comment by jenshannoschwalm** [comment]
@KarlMagnusLarsson are you using a Nvidia device for OpenCl?

**Comment by KarlMagnusLarsson** [comment]
Hello @jenshannoschwalm,

 

> are you using a Nvidia device for OpenCl?

Yes, I am 

```
Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]

Graphics driver : Nvidia Driver Version: 470.161.03

OpenCL installed : Yes, OpenCL 3.0 CUDA 11.4.309
```

**Comment by jenshannoschwalm** [comment]
Anyone reproducing this on non-nvidia? 

@Mstraeten @piratenpanda ?

**Comment by piratenpanda** [comment]
Not reproducing the green dots nor the black pixels on my AMD RX 580 card and latest git 4.3.0+1326~g7db849dd2d

**Comment by MStraeten** [comment]
macOS m1 max with opencl:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/39386816/226465754-372814b7-6fe7-44f4-90e0-6892e1fb1a44.png">

**Comment by piratenpanda** [comment]
ok when zooming in I can see it now

![grafik](https://user-images.githubusercontent.com/920721/226696758-f984374d-213b-4b41-81ea-3cffb3e06174.png)

**Comment by jenshannoschwalm** [comment]
Yes the bug was introduced in the `interpolate_bilinear` OpenCL code. It's not only about "green dots", there are plenty of artefacts if you look carefully. Also a strong dependency on ROI

**Comment by Scorpion078** [comment]
Thanks for the fix. I just updated that code and it solved the problem. 

Dumb question, but how do you even find those bugs?

**Comment by jenshannoschwalm** [comment]
> Dumb question, but how do you even find those bugs?

I hate bugs and it's a pleasure for me to spot them. How? Reading the source :-)
Probably related to my way of thinking, i am a trained intensive care doc and to identify a problem is what i do all day...

**Comment by KarlMagnusLarsson** [comment]
Thank you for the fix, @jenshannoschwalm. It works for me.
