### ISSUE TITLE
Sony ILCE-6100 noise profile

### ISSUE THREAD

**Issue by vyhyb** [darktable-org/darktable#13752]
Hello, first of all, thanks for this great application. I've tried to make a noise profile for my ILCE-6100 based on [this](https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/) tutorial. Could someone please look at it if it seems to be ok? In case it's ok, feel free to include it in future versions..
[darktable-noiseprofile-20230226.tar.gz](https://github.com/darktable-org/darktable/files/10833276/darktable-noiseprofile-20230226.tar.gz)

**Comment by rawfiner** [comment]
The profile looks very good.
Are there any extended ISO value below ISO100 or higher than 51200? If so we need profiles for them as well.

**Comment by vyhyb** [comment]
Good to hear that. The range of [ISO values](https://www.sony.com/tz/electronics/interchangeable-lens-cameras/ilce-6100#product_details_default) should be complete.

**Comment by rawfiner** [comment]
Perfect thanks! I'll do the PR asap
