### ISSUE TITLE
Improve usability of the Tone Equalizer/Mask Tab

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#13753]
**Is your feature request related to a problem? Please describe.**
The tone equalizer solves certain problems with images in an excellent way. However, the procedure is unnecessarily complicated to achieve such a good solution:

1. the manual says:
> To avoid having to switch back and forth between the advanced and masking tabs, a gray bar under the “mask post processing” label displays a representation of the middle 80% of the histogram. By using the controls in this tab to center and spread out this gray bar, you can expect to have a nicely shaped histogram when you return to the “advanced” tab. If you see orange at either end of the gray bar, this means that part of the histogram is outside of the 9 EV range of the mask, and needs to be further adjusted.
https://docs.darktable.org/usermanual/4.2/en/module-reference/processing-modules/tone-equalizer/

1. Now I have e. g. a histogram of an image like this (before use of TE):
![Bildschirmfoto vom 2023-02-26 11-49-22](https://user-images.githubusercontent.com/46827407/221406002-892b9e51-1dd7-4d53-8ce9-e3219f5d1fff.png)
Note that there are no clipping highlights.

1. Masking tab adjustments like this:
![Bildschirmfoto vom 2023-02-26 11-52-32](https://user-images.githubusercontent.com/46827407/221406060-1ab6347d-6078-4e1a-8c34-07c3861412a8.png)

1. But when I switch to the advanced tab the mask histogram is clipped significantly in the highlights.
![Bildschirmfoto vom 2023-02-26 11-53-28](https://user-images.githubusercontent.com/46827407/221406216-14f7d357-a96d-4f67-ba24-dca55df43a7a.png)

I can't see any correlation between what the bar in the Masking tab shows and the histogram of the mask.
Specifically, I don't see an orange warning in the Mask tab as described in the manual.

**Describe the solution you'd like**
Since I often run into problems like this where I can't estimate what will happen to the mask, I find that I am forced to do exactly what the description in the manual precludes: I have to switch to the Advanced tab after each setting in the Mask tab to look at the histogram.

I would therefore like to see the mask histogram displayed in the Mask tab - this would then make it possible to work interactively very quickly.

**Comment by MStraeten** [comment]
there's no correlation between main histogram and histogram in tone equalizer.
The histogram in tone equalizer is based on the mask you're defining with mask setting on tab 3. 
you can toggle the mask view (bottom right icon) so you can see whats represented by the histogram in contrast equalizer and how your setting affects the mask. You need to optimize the mask to differentiate between image content you want to handle in an different way. then you don't need the histogram - you can interactively darken and lighten areas directly by pointing on them with the mouse + scolling

**Comment by bilddateien** [comment]
Hi Martin,
thanks for your reply. I understand (at least I believe so) the difference between main histogram and the mask histogram in TE. The first one I included only for the sole purpose to show that there is no clipping in the image data itself.

My problem is the "disconnect" between what I see in that bar graph in mask tab (2) and the mask histogram I see in the advanced tab (3).
Especially: The manual says:
> By using the controls in this tab to center and spread out this gray bar, you can expect to have a nicely shaped histogram when you return to the “advanced” tab. **If you see orange at either end of the gray bar,** this means that **part of the histogram is outside of the 9 EV range of the mask**, and needs to be further adjusted.
Exactly this does not work every now and then in working on my images - see above: bar mostly in the middle of the graph in pure grey - but mask histogram is clipped anyway.

My workflow is like this: I try to spread the mask histogramm over all of the dynamic range in the graph (0 ... -8) so that I can point to any part of the image and darken or lighten the corresponding area without having to worry that the image element is not covered by the mask.
The mask view shades of grey for my eyes do not give me the exact impression I see from the mask histogram in the advanced tab.

**Comment by todd-prior** [comment]
> I try to spread the mask histogramm over all of the dynamic range in the graph (0 ... -8) so that I can point to any part of the image and darken or lighten the corresponding area without having to worry that the image element is not covered by the mask.

I used to do this but often found that one adjustment  or another would break the image so instead and after watching Boris I usually use at least 2 instances often even shifting one off one end or the other of the graph and just addressing one part of the image. I find this helps to get a nice correction on the primary area of concern and not risk losing proper contrast globally.... most failures with the Tone eq are often from trying to get too much out of one instance IMO
