### ISSUE TITLE
Shapes can't be modified at creation time

### ISSUE THREAD

**Issue by plougastel** [darktable-org/darktable#13755]
**Description**

Beggining with 4.2.0, a shape can't be modified during it's creation in the mask manager. All shapes are concerned but not the path one. A gradient can't be directly oriented, a circle resized, etc.

For the modification to be possible:

* create another shape in the mask manager, leave it by selecting the first one, it is now modifiable;
* or use the shape in a module as a drawn mask, without making another one, it is also modifiable;
* or go to lightable and come back to the picture.

**To Reproduce**

1. Go to the mask manager
2. Create a shape which is not a path
3. Try to modify it

**Which commit introduced the error**

All was good before 4.2.0 & 4.2.1

**Platform**

* darktable version : self compiled from the .tar.xz archives, 4.2.0, 4.2.1
* OS                : Linux - various 6.1 kernels
* Linux - Distro    : Devuan/daedalus
* Memory            : 16 Go
* Graphics card     : Intel 4th Gen
* Graphics driver   : Linux one
* OpenCL installed  : no
* Xorg              : 1.21.1.7
* GTK+              : 3.24.36-4
* gcc               : 12.2.0-14
* cflags            : default ones
* CMAKE_BUILD_TYPE  : Release

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible after discarding history? **yes**
 - What lua scripts start automatically? **rename images**

**Comment by ralfbrown** [comment]
Confirmed for brush, circle, ellipse, path (got crash on gradient).  It appears that the newly-created shape isn't getting focus.
You don't need to select another shape, you can click an empty area in the mask manager to deselect the new shape and then click its name to select it, at which time it properly has focus.
The brush shape disappears from view on finalizing, then reappears after the deselect/reselect.

**Comment by TurboGit** [comment]
@dterrahe : Maybe related to some of your changes? Very wild guess :) If not let me know I can have a look.

**Comment by dterrahe** [comment]
It is possible. For me, this only seems to happen when a shape is created directly in the mask manager without a (module) group being selected. So that it only creates a stand alone shape. I don't tend to use the mask manager that way, so I don't know if it used to work before I started messing with it.

There's a bunch of other outstanding issues with mask manager, somewhat related to item selection/activation. I wasn't planning on diving into that module further, so I'd be happy if you were willing to pick this up.

**Comment by ralfbrown** [comment]
Seems fixed by 13792  I just checked and all shape types work for me now.
