### ISSUE TITLE
Presets name are not ellipsized: this could make panel size change on long ones

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13762]
**Describe the bug/issue**

1. Have a not too wide panel (it should be smaller that what is needed to display preset name)
2. Go to Tone equalizer module
3. Select preset with long name (those starting by compress)
4. See that panel size has changed to allow all preset name to appears.
5. Change a setting on tone equalizer, preset name disappear and panel is restored too previous smaller size.

This is probably related to PR #13149. So @TurboGit: should probably another one for you.

**Expected behavior**

Panel size should not changed and so preset name should be ellipsized.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master

**Comment by TurboGit** [comment]
@Nilvus : Please see #13772. TIA.
