### ISSUE TITLE
Need to be able to format date fields as yyyy/mm/dd

### ISSUE THREAD

**Issue by engamorra** [darktable-org/darktable#13769]
**Is your feature request related to a problem? Please describe.**
date field(s) in file description photograph exif etc. are confusing

**Describe the solution you'd like**
Preferably have the possibility to choose date format ( indipendent from locale)

**Alternatives**
Lock the format in standard european official yyyy/mm/dd

**Additional context**
windows 10

**Comment by ptilopteri** [comment]
probably just need to properly set locale within your local system.

**Comment by MStraeten** [comment]
There’s a reason for that feature request template - and not just a title field ;)

**Comment by elstoc** [comment]
Agreed. Please shorten the title of this issue and add the detail to the first post (or else close the issue and open a new one using the issue template).

**Comment by kmilos** [comment]
What language/locale, what operating system?

Please fill out the issue template, it's not there for fun.

**Comment by engamorra** [comment]
Sorry for not being used to this form. I confirm the problem is not ( or it does not seem to be ) related to locale setting. The date format of the information ( exif etc) in my opinion should be either settable in some 'options' field, or even locked to be in the so called european standard format (yyyy/mm/dd). The reason is that other formats can be mis-interpreted.

**Comment by kmilos** [comment]
darktable uses underlying locale setting for displaying date and time, as any other application.

**Comment by engamorra** [comment]
Dear mr. kmilos, sorry, I seem not to be able to solve it as you suggest. However, some other people seems to say that it is not so, that the dispalyed information also depends on something else. Please consider this possibility.

**Comment by TurboGit** [comment]
Who is "other people", "say what", "depends on something else" ?

As said using local should work. If not please describe what you did and what you expect. TIA.

**Comment by parafin** [comment]
Which OS at least? On macOS I saw some strange date formatting (like in some random language), not sure how it works.

**Comment by engamorra** [comment]
Dear mr. parafin, I do not understand completely the way to place an issue. I did specify the system is windows 10, may be this does not appear in the issue field, sorry. 
As for the answer to mr. TurboGit : i read the answer of mr. elstoc, who says : agreed. That was the 'other people I mentioned.
The locale in my system is already set to display the dates as I want them. But the darktable exif fields show them in 'united states format' (mm/dd/yyyy) , I am asking to have the exif fields formatted as yyyy/mm/dd .

**Comment by elstoc** [comment]
>  i read the answer of mr. elstoc, who says : agreed. That was the 'other people I mentioned.

I was agreeing that you needed to update your issue and remove the long title.

**Comment by ptilopteri** [comment]
I know not what locale you desire, but you can start dt from the command lineas follows changing <LC_ALL="en_US.UTF-8" > to that which you utilize on your system

LC_ALL="en_US.UTF-8" darktable

but I know not about windos

**Comment by engamorra** [comment]
Thank you all.
I apologize for not being able to explain better.
My system is windows 10.
Darktable version : 4.2.1 

The system locale setting gives the date format as follows : yyyy/mm/dd 
The time display of the system is 24 hour format

Darktable is NOT following the system date format, it is showing date as : (day of week) mm/dd/yyyy
Darktable is correctly showing the time in 24 hour format
The language setting of darktable is English
-----
I do want to keep the darktable language in english
I would like to see the date format used by darktable as yyyy/mm/dd 
-----
The reason of that is that the month-day-year convention of u.s.a. is not standard and may be a source of confusion
----
The best solution would be to allow for an overrun of the date format in the options window .

----
In the discussion I see that most people thinks that all is dependent from the locale setting.
However I see that mr. MStraeten says :
 > There’s a reason for that feature request template - and not just a title field ;)
I am not sure of what this means exactly, but may be that the 'locale setting' is not the complete answer to my problem ?

Thanks.

**Comment by ptilopteri** [comment]
you should try setting the locale, follow:
  https://stackoverflow.com/questions/73720111/how-to-temporarily-change-locale-from-command-prompt

substituting for "en_us"

**Comment by parafin** [comment]
Language setting of darktable might be the problem here, because english is most often corresponds to US version and darktable affects system locale settings in its language selection code.

**Comment by ptilopteri** [comment]
> Thank you all. I apologize for not being able to explain better. My system is windows 10. Darktable version : 4.2.1
> 
> The system locale setting gives the date format as follows : yyyy/mm/dd The time display of the system is 24 hour format
> 
> ## Darktable is NOT following the system date format, it is showing date as : (day of week) mm/dd/yyyy
> Darktable is correctly showing the time in 24 hour format
> The language setting of darktable is English
> ## I do want to keep the darktable language in english
> I would like to see the date format used by darktable as yyyy/mm/dd
> ## The reason of that is that the month-day-year convention of u.s.a. is not standard and may be a source of confusion
> The best solution would be to allow for an overrun of the date format in the options window .
> 
> In the discussion I see that most people thinks that all is dependent from the locale setting. However I see that mr. MStraeten says :
> 
> > There’s a reason for that feature request template - and not just a title field ;)
> > I am not sure of what this means exactly, but may be that the 'locale setting' is not the complete answer to my problem ?
> 
> Thanks.

"mr. MStraeten" is referring to you ignoring the text presented requesting pertinent information about your situation when you first start to report an issue.  it is there for a reason to allow others to help you help yourself.  you failed to provide it or apparently even read it.

many use dt but I have not seen anyone with your "issue" so something is probably uniqut to your system.

**Comment by engamorra** [comment]
Thank you for all. Sorry not understanding the way to submit issues. Apologize.

**Comment by ptilopteri** [comment]
reading comes first, especially when not knowing about procedure.

following instructions comes next.


and:
starting dt on linux command line as:

LC_ALL="en_GB.UTF-8" darktable

provides image date as:  Tue 25/10/22 12:15:42

w/o the LC, it appears:  Tue 10/25/2022 12:15:42 PM


if you do not attempt to follow the suggestions offered, you will have grave difficulty solving 
anything.

**Comment by engamorra** [comment]
> many use dt but I have not seen anyone with your "issue" so something is probably uniqut to your system.

I think that the problem is that the localization of the user interface is LOCKED somehow to 'standard' localization.
If I make the choice to use the italian language it automatically follows the Italian date format (dd/mm/yyyy) which is not what I want.
If I make the choice to use english language it follows the english date format (mm/dd/yyyy).

Apparently there is no way to get the european official standard (yyyy/mm/dd)

In my opinion it would be useful to have an option to set the date format <<independent>> from the language , and such option should allow for the format I am requesting.

I do not think this is unique to my system, rather it is a unique request, this may happen.

However, thanks for all of your interest in my writing. I did learn something anyway. Apologize for wasting your time.
Regards

**Comment by ptilopteri** [comment]
google is your friend

LC_ALL="en_CA.UTF-8"

provides english and the date format you wish.

google is your friend.

**Comment by ptilopteri** [comment]
and if this satisfies your "issue", please close the issue.

**Comment by engamorra** [comment]
Thank you

> LC_ALL="en_CA.UTF-8"

I will try to do this in windows, thanks
