### ISSUE TITLE
Confusing shapes renaming

### ISSUE THREAD

**Issue by plougastel** [darktable-org/darktable#13767]
**Description**

When renaming a shape in the mask manager, the new name is overlayed with the first one given by darktable. One can't see the new strings entered so it is difficult, but not impossible, to enter a new name.

For example, the problem is not present when changing the text added to a version name in the duplicate manager, and generally in others text boxes; so it is perhaps not a GTK issue.

**To Reproduce**

1. Go to the mask manager
2. Create a shape
3. Try to rename it

**Which commit introduced the error**

Always present since I use darktable, since 3.4.0

**Platform**

* darktable version : self compiled, 4.2.1
* OS                : Linux - various kernels
* Linux - Distro    : Devuan/daedalus
* Memory            : 16 Go
* Graphics card     : Intel 4th Gen
* Graphics driver   : Linux one (i915)
* OpenCL installed  : no
* Xorg              : 1.21.1.7
* GTK+              : 3.24.36-4
* gcc               : 12.2.0-14
* cflags            : default ones
* CMAKE_BUILD_TYPE  : Release

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible after discarding history? **yes**
 - What lua scripts start automatically? **none or rename images**

**Comment by TurboGit** [comment]
@Nilvus : Assigned to you, probably a CSS issue.

**Comment by Nilvus** [comment]
@TurboGit: I'm not sure it's a CSS issue. First name created is hard-coded and seems to not be "erased" when clicking on entry (it's a treeview there and text is a label widget). For example, if I create a circle, I have "Circle #1"). I check where it is set and if I go to src/develop/masks/circle.c, line 1358, I have:

```
static void _circle_set_form_name(struct dt_masks_form_t *const form, const size_t nb)
{
  snprintf(form->name, sizeof(form->name), _("circle #%d"), (int)nb);
}
```

I don't completely know such code but seems that text is printed, and is probably not removed until name is updated. Actually, mask manager have some issues and need some love to code developer. See how many issues we have about that part: https://github.com/darktable-org/darktable/issues?q=is%3Aissue+is%3Aopen+mask+manager+

And for such things, I don't have skills to fix that.

**Comment by Nilvus** [comment]
Another thing, I just quickly check other parts where we have name that can be changed and on Gtk treeview widget. Those are:
- tagging module
- presets dialog window (or tab on preferences)
- and same for shortcuts

None of them allow to change name like on mask manager. For all those, this need a double-click (on presets for changing preset name) and/or right-click then edit option like on tagging module for example.

So, the question is simple: is Gtk treeview allow correct renaming directly on them like on mask manager or is this possible only when not having text on it?
