### ISSUE TITLE
Release Flatpak development snapshots

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [darktable-org/darktable#13776]
**Is your feature request related to a problem? Please describe.**
Currently there are development snapshots for Linux, which is great, but those builds are not universal and may require specific dependencies to be installed and specifically managed, unlike Flatpaks

**Describe the solution you'd like**
Build Flatpaks alongside (or instead of) native packages

**Alternatives**
Make statically compiled builds for 500 distros?

**Additional context**
Flatpaks are easier to install and manage, which is important for snapshot builds. Also if you switch to Flatpak-only builds, it might be easier to maintain the project for you

**Comment by Nilvus** [comment]
Flatpak will probably not be the choice. AppImage is more on the go but remains to do. You could see discussion there: #3925

So this is sort of duplicate and as AppImage take time to be done (because of lack of people who want to spent time on it), I think Flatpak would probably not be done by actual team. I let you close or not that issue. But I think AppImage would fix it even if it's not Flatpak.

**Comment by victoryforce** [comment]
@yhm3ps1jfp76nkd I'm currently testing an AppImage build in Github Actions. AppImage is planned to be built in the Ubuntu 20.04 environment to increase the number of distribution releases with which compatibility will be ensured.

**Comment by yhm3ps1jfp76nkd** [comment]
AppImage is totally fine for me and I would even prefer it to normal builds for testing (since, again, it's very easy to install and remove the package without installing specific dependencies). However I would still ask to look into the Flatpak development since it seems to be a more modern and futureproof standard with many distros adopting it.

Closing

**Comment by victoryforce** [comment]
> AppImage is totally fine for me and I would even prefer it to normal builds for testing (since, again, it's very easy to install and remove the package without installing specific dependencies).

That's great. Regarding flatpak, your help would be much appreciated.
