### ISSUE TITLE
[FR] It would be nice to have a quick integration test for CI

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#13779]
It would be nice to have a single integration test as a CI step that won't run for too long, but will test as many modules as possible. This will not delay the completion of the entire CI, as we will run it in Linux and Linux CI runs complete much faster than others. In my opinion, this requires:

- Create a test that will include all modules for full coverage (the size of the image may be reduced for processing speed).
- Make changes to the run.sh script so that it returns an exit code according to the test result.

**Comment by ralfbrown** [comment]
There's already a sidecar file with nearly all modules (as of v3.8) in src/tests/benchmark.  One possibility would be to run darktable-bench with just a single iteration instead of the default five.

I'll make a note to self to update the sidecar with the newest modules (like sigmoid).

**Comment by ralfbrown** [comment]
See https://github.com/darktable-org/darktable-tests/pull/17 and #13813
