### ISSUE TITLE
A widget that can be trained to recognise and correct lens aberrations

### ISSUE THREAD

**Issue by FelixtheChat** [darktable-org/darktable#13789]
A lens distortion widget (similar to that present in either the HUGIN suite or Photoninja) that can be 'trained' to recognise and correct the aberrations present in cameras **where LCP's don't exist in either the Adobe or Lensfun databases for those cameras**. A tool that can build highly accurate correction profiles -  Each new profile saved and immediately applied when the camera/lens combination is recognised.

**Comment by MStraeten** [comment]
any idea how to implement that?

**Comment by geni1105** [comment]
> any idea how to implement that?

There‘s a description of the UI of Photoninja here https://picturecode.com/tutorials/distortion_tool.php 
The user manually places marks on what should be a straight line in the image, and the tool calculates distortion correction parameters from the displacements of the marks from a real straight line. You can use several such lines at the same time, and the tool seems to average over them.

I found this a neat idea and very useful functionality, when I used Photoninja many years ago.

**Comment by MStraeten** [comment]
relevant is not primarily the gui but the logic that needs to be implemented. The better your contribution the better the chance someone might spend time to implement it …

**Comment by TurboGit** [comment]
Doing that for all lens correction would be hard work... And does this really need to be done with darktable?
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by kmilos** [comment]
That's how lensfun works, so might as well create a profile.

**Comment by geni1105** [comment]
Well, with lensfun it's much less convenient than with Photoninja's approach. It involves command line, needs python and other things installed, needs hugin as a separate program, users need to manually edit configuration files etc. 
If non-command line users still dare to undertake the lensfun procedure, they probably would not risk to publish their profiles for general use. 
With Photoninja, you just move a few marks, press a button and new profile data are automatically added to your database, for a new lens, or just for additional parameters of an existing lens profile (zoom, distance, ...).

Anyway, I am not criticizing or arguing against lensfun, just pointing out the significant difference in usability between Photoninja and lenfuns, although the basic approach is the same. Of course also the goals are totally different - a general, public lens database for distortion, TCA and vignetting vs. a private distortion-only database. And Photoninja has unfortunately not seen a meaningful update in many years now.

**Comment by MStraeten** [comment]
if you can recommend a better library to deal with it, feel free. Currently there’s lensfun and using corrections based on embedded data. Collection of lens distortion etc. data to match a valuable number of lenses is better done with a broader user community so having a darktable specific private database will be disappointing over a very long time (even lensfun lacks several lenses due to missing contributions)

**Comment by geni1105** [comment]
I am fine with the current options, and I am not the OP requesting the feature.
I was just mentioning an alternative concept, that might be useful in some situations. For example when adapting vintage lenses, for which neither lensfun data nor embedded metadata are available.

**Comment by kmilos** [comment]
What alternative concept again? The procedure is still the same as with lensfun for any lens... The is no "alternative" maths 😉

**Comment by geni1105** [comment]
Right, there's no alternative maths. My comment just referred to an alternative idea to handle it, directly from within darktable instead through external scripts and tools. 

Anyway, since the issue creator @FelixtheChat does not engage in the discussion, his interest is probably not very serious and the issue should be closed.
