### ISSUE TITLE
Samsung Galaxy S23 Ultra

### ISSUE THREAD

**Issue by Pixel70a** [darktable-org/darktable#13782]
Hello,

I've just uploaded some sample RAW files from my S23 Ultra. Please use it to make the camera support.

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/rawspeed/issues/403

**Comment by jirislav** [comment]
FYI, I've also submitted DNF from Samsung Galaxy S23 (non-Ultra).

For reference, here's the `exiftool` output:
```
Make                            : samsung
Camera Model Name               : Galaxy S23
```

**Comment by PawelPatyk** [comment]
After two years it is still not possible to edit DNG files with Expert RAW...

**Comment by HeaderShoter** [comment]
> After two years it is still not possible to edit DNG files with Expert RAW...

Quite funny that you have the same problem at the same moment as I do. :-)

**Comment by ptilopteri** [comment]
darktable is FOSS, dev's donate their time and skills.

you can relieve your dissatisfaction in several ways, one:
  you can donate your time and do the coding and follow up debugging. 

or wait for someone else who has an itch.
