### ISSUE TITLE
about filmstrip thumbnails

### ISSUE THREAD

**Issue by cridemichel** [darktable-org/darktable#13786]
Hi all, 
first of all thank you very much for the great work you are doing with darktable, which by now is my preferred
image editing software

**Is your feature request related to a problem? Please describe.**

filmstrip thumbnails do not show any information. For example, it would be very useful in the darkroom to know whether
an image has been already edited or not.

**Describe the solution you'd like**

I think it would be very nice to have star rating, color label and modification status shown
in filmstrip thumbnails in the darkroom. In lightroom, for example, stars are shown, the thumbnail
is framed with the color assigned to the image and an icon appears if the image has been edited,
 
kind regards,
Cristiano

**Comment by pehar1** [comment]
Select star icon above image area in darkroom, select _"permanent overlays extended on mouse hover"_ for example. Overlays can be defined in _"preference -> lighttable -> thumbnails -> pattern..."_

**Comment by cridemichel** [comment]
thank you very much, I did not know it was already implemented,

best Cristiano

Cristiano De Michele
***@***.***
