### ISSUE TITLE
Sony ZV-E10 noise profile

### ISSUE THREAD

**Issue by hk-ng** [darktable-org/darktable#13791]
Hi, I would like to add noise profile for Sony ZV-E10.
I am not sure if it fit as the jpg thumb become green while it is fine in raw file.

[darktable-noiseprofile-20230302.tar.gz](https://github.com/darktable-org/darktable/files/10864306/darktable-noiseprofile-20230302.tar.gz)

**Comment by rawfiner** [comment]
The profile looks great thanks. I will do the PR in the coming days.

**Comment by EaryChow** [comment]
Hello, did the noise profile get added? I see in the [camera support list](https://www.darktable.org/resources/camera-support/) ZV-E10's noise profile support is still listed as No.
