### ISSUE TITLE
No scroll bars for long lists of images

### ISSUE THREAD

**Issue by electroCutie** [darktable-org/darktable#13790]
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**
this is darktable 4.0.0
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 8.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**
There are no scroll bars in the UI and no option to turn them on
When navigating about 1000 images from a convention it is a very difficult to understand where I'm at in the list and impossible to rapidly move between places in the list 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
I'd expect at least some scroll bars, even if they aren't the old fashioned full time ones (though that would be lovely as an option)
Something I can see and drag about

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by pehar1** [comment]
I suspect you mean https://darktable-org.github.io/dtdocs/en/preferences-settings/lighttable/ "show scrollbars for center view" ?
Or the list in collections module ? Please describe exactly what you mean. And please remove all the text from the template you do not need/use. It is very tedious to find the relevant information in your post.

**Comment by Nilvus** [comment]
Sorry but I close. It's just unreadable. And as @pehar1 explained, it's an option on preferences. Read the manual and please helps us help you by making effort on writing issues. As explained on template, it's guidelines and all unuseful text is good to remove.

**Comment by electroCutie** [comment]
> Sorry but I close. It's just unreadable. And as @pehar1 explained, it's an option on preferences. Read the manual and please helps us help you by making effort on writing issues. As explained on template, it's guidelines and all unuseful text is good to remove.

Apologies. I had a very high fever when I posted it and didn't realize how far out of it I was.

But there was still the issue I was having and ti wasn't mentioned in the manual

However after finding that ctrl+scroll can make scroll bars appear I tried it and it worked
So this may be some sort of state error where my darktable wasn't displaying them because I'd not resized my items in a long time, it seems.

A far more minor issue but if it is worth reopening then I leave that to you.

Is it cleaned up acceptably at least? So in case someone else tries looking for it and this is a problem its useful?

**Comment by Nilvus** [comment]
I don't see any issue. I always have scrollbars, since years on my side and by default. To display scrollbars, as explained by @pehar1, be sure to check option on lighttable tab in darktable main preferences. To apply that change, you need to restart darktable. You provide very few informations, no step by step as asked by template issue.

But more, you use a too old darktable release and we can't let an issue opened for such old release as many bugs have been fixed since. We had 3 new releases now following darktable 4.0. I remember that I have last year (not sure but probably after dakrtable 4.0 release), improve scrollbars visibility for example.

To have last one, if Ubuntu do not provide you the latest ones, you could add OBS repository (see install page on darktable.org).
