### ISSUE TITLE
mask manager: group collapse with right click on non selected row

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13803]
Create two shapes on an IOP module.

Do a right click on a non selected item in a group (under an IOP):

![image](https://user-images.githubusercontent.com/467069/222702578-8d871658-d7c9-4f8f-9b06-409a07beab30.png)

Say on `ellipse#1` above. See the group exposure will collapse:

![image](https://user-images.githubusercontent.com/467069/222702659-a026bb7a-c481-4edc-b3de-ea1e5bd46784.png)

If none are selected or a right-click is done on a selected item the group doesn't collapse.

**Comment by Nilvus** [comment]
Seems a duplicate or near an issue I posted about 2 weeks ago: #13551. @TurboGit: I can't actually test your fix for this issue, so could you check my issue? If it's fixed, feel free to close it.
