### ISSUE TITLE
Potential fix for computational mistake in laplacian normalization

### ISSUE THREAD

**Issue by saknopper** [darktable-org/darktable#13807]
I was browsing through the commits of Ansel looking for anything interesting that might benefit darktable too when I spotted this commit: https://github.com/aurelienpierreeng/ansel/commit/c44b0312197f4eaf9f96b427b2fef3ab7e3432ca

I can't say whether this actually fixes anything or not. But at the very least I want to bring this under your attention.

**Comment by ralfbrown** [comment]
The commit changes the scaling by a factor of sqrt(PI).  But AFAICT the function is never called by dt code.

**Comment by saknopper** [comment]
A quick grep seems to confirm that the function is never used. Hence I'm closing this issue.

Though I suppose I might as well create a PR to remove the function...
