### ISSUE TITLE
Preview in quick access menu for styles in darkroom not shown anymore

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#13815]
**Did you buy darktable from an application store ?**
self build from current master

**Describe the bug/issue**
Clicking the icon for the quick access menu opens the menu correctly, but hovering the mouse over the styles available does not show the preview anymore.

**To Reproduce**
1. Go to darkroom
2. Click on icon to open quick access menu for styles
3. Hover the mouse over a menu entry, wait a moment... (waited up to 10 seconds)
4. Nothing happens

**Expected behavior**
Hover over a style name with your mouse to show a preview of the current darkroom image with the selected style applied, as written in the manual. It worked this way for me until a few days (weeks?) ago.

**Which commit introduced the error**
Don't know, but not too long ago

**Platform**
darktable 4.3.0+939-g266136fb47
OS : Linux 5.15.0-67-generic / Ubuntu 22.04.2 LTS
Memory : MemTotal:       65768484 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Additional context**
Searched for a new preference setting which I may have missed. Searched the latest commits to see if this functionality may have been reverted. Found nothing...

 - Can you reproduce with another darktable version(s)? **at least 4.3.0-896-g4e4e7b65d7 and 4.3.0-873-g161d59d3fa**
 - Can you reproduce with a RAW or Jpeg or both? **only tried RAW**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by TurboGit** [comment]
If you have some time to bisect and report the bad commit it would help a lot. Thanks.

**Comment by pehar1** [comment]
Unfortunately I have not the time today to completely bisect... , but I did a fast search of the versions I have available on my system. I hope this is helpful.
Last version without bug : 4.3.0-732-g410cba6786 (build 2023-02-22)
First version with bug : 4.3.0+768-g0f1ebfba40 (build 2023-02-24)

**Comment by dterrahe** [comment]
Hm. I think that line was introduced in #13624? Tooltips for  shortcuts to presets are also broken. I'll have a look to see if there is an easy way to distinguish foreground "windows" that are just menus and not require those to be "active" in order to show tooltips. Otherwise we may just have to revert that PR and live with tooltips now and then popping up behind the preferences and other dialogs.
