### ISSUE TITLE
flag to identify exported files

### ISSUE THREAD

**Issue by salkalero** [darktable-org/darktable#13818]
**Is your feature request related to an issue? Please describe.**
In the light table, I have trouble finding the photos that have been exported

**Describe the solution you would like**
A flag that tells me that this file has already been exported and that it is displayed on the light table.

**Additional context**
 In the same way that there is a flag to indicate that a file has been edited, it would be nice to have another flag to identify the files that have been exported, I think it is important since editing and exporting are two fundamental steps .

**Comment by zisoft** [comment]
In the collection module you can select `tagging --> darktable --> exported` to get your exported photos selected.

They are not indicated as exported in the thumbnails though.

**Comment by salkalero** [comment]
thanks for answering. You can also filter by exported date, but I don't think it's the most comfortable solution, that's why I think an indication in the thumbnails that is automatically generated each time a file is exported is the best solution.
Imagine that you are working with a collection of photographs and between the edited and exported ones, it may be the case that you do not know which ones have been exported, since the edited ones do not have to be exported.

**Comment by wpferguson** [comment]
> you do not know which ones have been exported

In lighttable sort by export time.  The ones that haven't been exported will be at either end of the collection depending on whether the order is ascending or descending

**Comment by Nilvus** [comment]
> thanks for answering. You can also filter by exported date, but I don't think it's the most comfortable solution, that's why I think an indication in the thumbnails that is automatically generated each time a file is exported is the best solution. Imagine that you are working with a collection of photographs and between the edited and exported ones, it may be the case that you do not know which ones have been exported, since the edited ones do not have to be exported.

I understand your view but this would also override thumbnails. Adding such icon could also make some users wanted other infos, and have quite many icons. Thumbnails already have:

- extension name
- group icons for related ones
- altered ones
- stars
- color labels
- reject icon
- audio icon (probably rare, I even never understand the need of that)
- local copy

Of course, not all at same time but sometimes we could have nearly all and a lot of infos so on thumbnail, with images and metadata infos of course...
-
