### ISSUE TITLE
Infinite processing loop with lens correction module

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#13812]
As I was tinkering around trying to understand #13801 better, I uncovered an infinite processing loop using the lens correction module.

Steps to reproduce:
1. Load image without any lens correction in darktable and enter darkroom.
2. Enable lens correction (it's important that it has not been previously applied to the image)
3. Infinite processing loop (pegging my CPU to 100% until I exit darkroom)

_The special condition here is that the lens correction module does not recognize my camera/lens automatically_. When loading an image where camera/lens is recognized automatically, there is no infinite loop.

platform: archlinux
darktable version: 4.3.0+896~g4e4e7b65d7
OpenCL: enabled and disabled reproduces the issue on my machine.

**Comment by groutr** [comment]
To help narrow this down a bit more:
Last good build: 4.3.0.r768.g0f1ebfba40 (Feb 24)
First bad build: 4.3.0.r813.g34752ba032 (Feb 26)

**Comment by TurboGit** [comment]
> First bad build: 4.3.0.r813.g34752ba032 (Feb 26)

I doubt it is really this as this commit is:

```
commit 34752ba03252cc74e28d415209d43344a51ebfe9
Author: Victor Forsiuk <vvforce@gmail.com>
Date:   Sat Feb 25 15:36:34 2023 +0200

    Remove no longer used support for antiquated gcc versions

diff --git a/cmake/compiler-warnings.cmake b/cmake/compiler-warnings.cmake
index 94d421339e..9d6eeedeb1 100644
--- a/cmake/compiler-warnings.cmake
+++ b/cmake/compiler-warnings.cmake
@@ -12,13 +12,7 @@ else()
   CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wformat-security)
 endif()
 
-# cleanup this once we no longer need to support gcc-4.9
-if(NOT (CMAKE_C_COMPILER_ID STREQUAL "GNU" AND CMAKE_C_COMPILER_VERSION VERSION_LESS 5.0))
-  CHECK_C_COMPILER_FLAG_AND_ENABLE_IT(-Wshadow)
-endif()
-if(NOT (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.0))
-  CHECK_CXX_COMPILER_FLAG_AND_ENABLE_IT(-Wshadow)
-endif()
+CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wshadow)
 
 CHECK_COMPILER_FLAG_AND_ENABLE_IT(-Wtype-limits)
```

**Comment by TurboGit** [comment]
The culprit is:

```
commit fc54696e4f8a8fe28542c931e5ff350d182882b9
Author: Pascal Obry <pascal@obry.net>
Date:   Wed Feb 22 10:53:59 2023 +0100

    history: Update module label when it is changed.
    
    Also the label now use the same format as used in module header.
    
    Fixes #13702.

 src/develop/develop.c | 19 ++++++++++++++++---
 src/develop/imageop.c | 43 ++++++++++++++++++++++++++++++++++---------
 src/libs/history.c    | 21 ++++++++++++++++-----
 3 files changed, 66 insertions(+), 17 deletions(-)
```

**Comment by groutr** [comment]
@TurboGit, I apologize for my vague post. I did not do a git bisect, but rather looked thru my package cache and kept downgrading until I reached a build that didn't exhibit this issue. The bad commit was somewhere between r769 and r813. I did not mean that r813 was the bad commit. Sorry for the confusion.

**Comment by TurboGit** [comment]
@groutr : Anyway, now fixed.
