### ISSUE TITLE
Windows version 4.2.1 fails to open.

### ISSUE THREAD

**Issue by vasto7** [darktable-org/darktable#13811]
Windows version 4.2.1 does not open after double clicking the executable.

There is a quick flash of what appears to be the command prompt window, but then nothing follows.

Task manager shows nothing running.

However, the weekly Windows build of version 4.3 (darktable-4.3.0+833_gee15dec0e5-win64) available below, executes just fine.

https://discuss.pixls.us/t/darktable-windows-insider-program-2-19/35449

* darktable version : New stable windows release 4.2.1
* OS                : Windows 11
* Linux - Distro    : 
* Memory            : 32 GB
* Graphics card     : Radeon RX 5700
* Graphics driver   : 22.Q4
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by victoryforce** [comment]
It is most likely that you have already run weekly builds or some other builds from the development branch before and did it with the same default library. From time to time, new versions make changes to the library database schema. Since the older version cannot work with the updated base, it terminates immediately. Just make separate libraries for 4.2.1 and development.

**Comment by vasto7** [comment]
Thank you for the quick reply Victor.  That makes sense.  
I'm not entirely sure how to create a separate library.  Can you point me to instructions on that.
Regards.
    On Friday, March 3, 2023 at 02:23:40 PM EST, Victor Forsiuk ***@***.***> wrote:  
 
 


It is most likely that you have already run weekly builds or some other builds from the development branch before and did it with the same default library. From time to time, new versions make changes to the library database schema. Since the older version cannot work with the updated base, it terminates immediately. Just make separate libraries for 4.2.1 and development.

**Comment by pehar1** [comment]
Please read https://darktable-org.github.io/dtdocs/en/special-topics/program-invocation/darktable/
`--configdir` and `--datadir` may be useful for you, for example.

**Comment by Nilvus** [comment]
I so close that issue as this place is for issues or feature request to improve darktable code. For help, pixls.us forum is there.
