### ISSUE TITLE
tone equalizer mask display corruption

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#13826]
**Did you buy darktable from an application store ?**
Nope, self-built.

**Describe the bug/issue**
The tone equalizer mask gets corrupted when adjusting the contrast or exposure.

**To Reproduce**
1. Get the raw and sidecar from https://tech.kovacs-telekes.org/files/darktable-tone-eq-mask-2023-03-04
2. Open the image in darkroom
3. Open the tone equalizer
4. Enable mask display
5. Drag the exposure / contrast sliders wildly
6. After a while, the mask gets corrupted with scaled-down versions of the image. It's always at the top. Looks like the the corrupted area has the size of the thumbnail?
7. Turning the mask display off and on clears the error. Exporting, while the corrupted mask is still visible, does not cause artefacts in the exported image.

**Expected behavior**
No corruptions.

**Screenshots**
![image](https://user-images.githubusercontent.com/3177739/222924295-bfeaeb4d-f322-470f-8b90-9dfcca501560.png)

**Screencast**
![screencast](https://tech.kovacs-telekes.org/files/darktable-tone-eq-mask-2023-03-04/screencast.gif)
https://tech.kovacs-telekes.org/files/darktable-tone-eq-mask-2023-03-04/screencast.gif - in case it's not visible.

**Which commit introduced the error**
I think I've had it for a long time.

**Platform**

* darktable version : `4.3.0+973~g5435351522`
* OS                : `Linux 5.19.0-35-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 22.10
* Memory            : 64 GB
* Graphics card     : NVidia 1060/6GB
* Graphics driver   : 525.85.05-0ubuntu0.22.10.1 
* OpenCL installed  : yes
* OpenCL activated  : does not matter, occurs with it on/off
* Xorg              : 7.7+23ubuntu2
* Desktop           : KDE
* GTK+              : 3.24.34-3ubuntu2
* gcc               : 12.2.0-3ubuntu1
* cflags            : N/A
* CMAKE_BUILD_TYPE  : Release, also RelWithDebInfo (occurs with both)

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with a RAW or Jpeg or both? both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts? no

**Comment by pehar1** [comment]
I tried hard to reproduce the problem, both with your uploaded image and with several of my own images, without success. Even with extremely fast movements of the sliders, much faster (and longer) than shown in your screencast, the displayed mask remains intact for me. I use the module very often and could also never observe the described issue in the past.

darktable 4.3.0+974-gda6754ee35
OS : Linux 5.15.0-67-generic / Ubuntu 22.04.2 LTS
Memory : MemTotal:       65768492 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.161.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by jenshannoschwalm** [comment]
Is your issue also present without active duplicate manager?

**Comment by pehar1** [comment]
On my side it makes no difference whether the duplicate manager is open or not, whether I work with version 1 or version 0 of the image, for me the issue does _not_ occur.

**Comment by kofa73** [comment]
@jenshannoschwalm: Yes, I can reproduce it with the _duplicate manager_ collapsed. This image (one from a PlayRaw) has no duplicates, the module is collapsed.
![image](https://user-images.githubusercontent.com/3177739/222952894-939effee-5022-4c38-b443-be22b193a95c.png)

**Comment by kofa73** [comment]
I _cannot_ reproduce the problem _if_ the left-hand sidebar, the one with the navigation preview, is collapsed.

**Comment by kofa73** [comment]
I can also get corruption in the navigation thumbnail window; see here, just before the capture ends. Those are temporary, though, and I don't see them if I stop adjusting the module; the main view stays corrupted, but the navigation thumbnail is always fixed:
![navi preview corruption](https://tech.kovacs-telekes.org/files/darktable-tone-eq-mask-2023-03-04/preview-corruption.gif)
(The banding is due to GIF.)

**Comment by pehar1** [comment]
With this extended information, I was able to reproduce at large or maximum width of the left panel. Also the temporary corruption of the navigation thumbnail is visible, but only as a very short flashing, possibly because I use a newer (faster) graphics card.

**Comment by kofa73** [comment]
Note that the corruptions (both of the editor area and the thumbnail) are reproducible even with `--disable-opencl`.

**Comment by jenshannoschwalm** [comment]
I had not use the mask visualizing in this module before. I can't reproduce the artefacts here, just am very surprised that
1. the masks seem to be so "unstable"
2. There should be no visualizing in the overview on the left side at all - at least i would think so.

I haven't looked at the code before so no idea yet.

**Comment by kofa73** [comment]
What is visualised in the thumbnail is not the mask -- it's the effect of the stack. Note how the mask is B&W, while the thumbnail has colours.

**Comment by jenshannoschwalm** [comment]
> What is visualised in the thumbnail is not the mask -- it's the effect of the stack.

Sure. The caching of cairo data in the module might be a problem here, also your observation of dependency on preview image size might be relevant.

**Comment by TurboGit** [comment]
Just in case, if you can test this patch:

```
diff --git a/src/iop/toneequal.c b/src/iop/toneequal.c
index 1904e49719..32b058e49c 100644
--- a/src/iop/toneequal.c
+++ b/src/iop/toneequal.c
@@ -2216,6 +2216,7 @@ static void draw_exposure_cursor(cairo_t *cr, const double pointerx, const doubl
     double pointer_coord[2] = { pointerx, pointery };
     double span[2] = { radius_z, radius_z };
     cairo_draw_hatches(cr, pointer_coord, span, instances, DT_PIXEL_APPLY_DPI(1. / zoom_scale), 0.3);
+    cairo_stroke(cr);
   }
   cairo_restore(cr);
 }
```

But I have real doubt about this being a fix for this issue.

**Comment by TurboGit** [comment]
I think the issue is that `process()` is using `gui_data` which are changed while process is running. A race condition. If I'm not mistaken the `process()` routine must never access to the `gui_data`.

**Comment by kofa73** [comment]
I've tried the patch. Display updates are a *lot* slower, but the problem is still there.

**Comment by pehar1** [comment]
With patch and maximum width of left panel on 1920*1080 screen :

- display update (image with mask) is slower, but still acceptable
- the issue of the corrupted mask can still be forced
- the "flashing" of the preview thumbnail is only very rarely visible 
- toggling the _"display exposure mask"_ button off/on reproducibly "repairs" the mask view, but it can be corrupted again by moving the slider(s)

With a "normal" width of the left panel (just under 300 pixels) it is not possible to catch the issue on my system (with or without patch).

**Comment by TurboGit** [comment]
For those reproducing is that with all images? Portrait? Landscape? NEF? CR2? Do you see some patterns to reproduce... This will help a lot tracking this down...

**Comment by pehar1** [comment]
- all images : yes (tried with about 10 different)
- portrait and landcsape
- tried with NEF from OP and own Sony ARW
- pattern : always 4 rectangles at the top edge of the image, always overlayed by horizontal stripes (see examples from OP above)

**Comment by pehar1** [comment]
The rectangles look like reduced (and inverted ?) versions of the original mask view with size 1/4 width and 1/4 height, overlayed with horizontal stripes.

**Comment by kofa73** [comment]
Thanks for the checks, @pehar1. My experience is the same, though I only tested landscape shots. I used 16 MPx NEF, 10 MPx RW2 and also JPG as input.

**Comment by pehar1** [comment]
Some more observations :

- was able to reproduce also with a fresh install and **minimal** width of left panel. Contrary to the original assumption, the effect does **not** seem to depend on the width of the left panel.
- it is not necessary to move the slider(s) wildly and fast, also with continous slow moves it is possible to force the issue. Corruption usually occurs after 5 to 10 seconds of continous movements.
- the content of the rectangles seem to be reduced versions (factor see above) of the mask view (**not** inverted but much brighter), the _"stripes"_ are regions where the underlying _"undamaged"_ mask display is visible.
- moving the _mask contrast compensation_ slider changes the contrast of the "undamaged" region and also the contrast of the rectangles
- moving one of the tree "mask" sliders changes position and number of stripes

![toneequalizer](https://user-images.githubusercontent.com/104291381/223955244-edaae524-e681-4089-bbbc-15337a8c9a7a.png)
screenshot of the left of the four rectangles, the third stripe from the bottom shows the cloud in the underlying, undamaged mask display.

**Comment by TurboGit** [comment]
Still cannot reproduce... That's about to be a hard one! A question, do you reproduce with whatever history stack or is a specific module must be activated to reproduce?

**Comment by kofa73** [comment]
I can reproduce it with any image, without any specific module enabled (except for tone EQ, of course).

**Comment by pehar1** [comment]
To add some more confusion....
Tried to reproduce on a 12 years old system with only 4 GB of RAM and a very old Nvidia Graphics card :

darktable 4.3.0+1075-gb8c772f756
OS : Linux 5.15.0-67-generic / Ubuntu 22.04.2 LTS
Memory : MemTotal:        3999392 kB
Graphics Card :     Product Name                    : GeForce GT 435M
Graphics Card : Driver Version                      : 390.157
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.1 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

First series of attempts :
- image from OP **without** xmp
- fresh install
- empty config
- workflow none or workflow scene referred (filmic) + tone equalizer
- OpenCL on or off
- different width of left panel

Can **not** reproduce with this settings on this system ! 

Second series of attempts :
- image from OP **with** xmp from OP
- fresh install
- empty config
- OpenCL on or off
- different width of left panel

Can **not** reproduce regarding the main view, but get (from time to time) the same pattern of damages (in false colors) in the navigation thumbnail, even if the exposure mask is not shown in the main view. This damages of the navigation thumbnail are always repaired within some seconds when stopping moves of slider(s).

Maybe this pattern was also present on my (much faster) working system, but it was not recognizable, only as a fast flashing as already reported.

Reset history : no issues, neither with mask display nor with navigation thumbnail.

Conclusion :

- the issue seems strongly dependent on the system dt is running on
- the xmp from OP seems to contain something triggering the issue, or making it at least more probable. This is obviously also true for (all ?) my pictures I used for the tests
- In every case the issue can reliably be removed by toggling _"display exposure mask"_ off/on.

@TurboGit , if it is of interest I can run further systematic tests on my (fast) working system (possibly) tomorrow. But since there is a simple workaround I think you should not invest too much time. But i also understand if your ambition as a coder is challenged by such issues...

**Comment by kofa73** [comment]
I can also not reproduce it on the slow Windows laptop that I have access to.
I agree it's probably not worth pouring countless hours into what seems to be a mostly cosmetic issue. The display corruption suggested some wrongly shared memory to me, but there is no crash, so it's not that bad.

**Comment by TurboGit** [comment]
Yes I agree, I'll not spend more time on this. We'll let this dormant and maybe at some point we will be able to reproduce easily and restart tracking down this issue.

**Comment by jenshannoschwalm** [comment]
@kofa73 could you please recheck this with current master?

1. without any special flags
2. with --disable-pipecache

I hope i understand the problem now, If my hypothesis is correct you shouldn't have the issue with test_2

**Comment by kofa73** [comment]
I'm very tired and have little time. I'll be able to test on Friday, maybe even before.

**Comment by kofa73** [comment]
So, with your change, without flags, the screen can become completely black, even though the histogram looks fine:
![image](https://user-images.githubusercontent.com/3177739/230057221-02153d06-2b97-4eb3-aa00-a7247123287b.png)

Also, it's just inconsistent. See the tiny changes as I scroll the mouse wheel for exposure compensation:

-1.81 EV
![image](https://user-images.githubusercontent.com/3177739/230057416-5160e795-984b-48ea-80a2-1e2e9c4a6e21.png)

-1.86 EV
![image](https://user-images.githubusercontent.com/3177739/230057657-7e5fc393-3db5-44c1-8e19-2c9d8d7837c9.png)

-1.91 EV:
![image](https://user-images.githubusercontent.com/3177739/230057858-e58ba0da-44f2-4944-bfba-ffabc53d2645.png)

The preview and the mask display flicker. I don't see the martial corruption (stripes), though.

**Comment by kofa73** [comment]
With --disable-pipeline-cache, I sometimes get this weird corrupted mask:
![image](https://user-images.githubusercontent.com/3177739/230058502-da83b7c8-ef03-4f9e-bf85-452a89aa97dc.png)

Or
![image](https://user-images.githubusercontent.com/3177739/230058593-aade00b5-8e17-475b-bf09-e711814ffda2.png)

**Comment by kofa73** [comment]
Those are with

    kofa@eagle:~/darktable$ git rev-parse HEAD
    3ae0709177ae8777a586630ae3c6f867497ac359
    kofa@eagle:~/darktable$ git log
    commit 3ae0709177ae8777a586630ae3c6f867497ac359 (HEAD -> no_masking_caching)
    Author: Hanno Schwalm <hanno@schwalm-bremen.de>
    Date:   Tue Apr 4 19:31:55 2023 +0200
    
        Fix masking related pixelpipe issues
    
        - we make sure we don't get data from cache while in masking mode
        - checks for important are only done while in non-masking mode
        - simpler check for fast bypassing masks visualizing data
    
        - some debugging info also contains module name

**Comment by jenshannoschwalm** [comment]
@kofa73 could you retest with current master

**Comment by kofa73** [comment]
No longer reproducible with or without `--disable-pipecache`. Great work, thanks!
