### ISSUE TITLE
Avoid unintentional loss of data in metadata editor

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#13829]
**Is your feature request related to a problem? Please describe.**
I would like to suggest a change to the user interface of the metadata editor module in the lighttable mode of darktable. The suggestion removes the potential for user error which I frequently make when using this module on either new or existing images. The error is that I fail to click on the ‘apply’ button before clicking elsewhere in darktable – which I usually do because I have forgotten to select an image or which I might do to get more information from eslewhere, for instance. Failure to click the ‘apply’ button first results in all the data that has been added to this module in the current edit session being discarded. This is frustrating."

**Describe the solution you'd like**
What I  would prefer is that the ‘apply’ function is applied automatically as soon as the enter key is pressed or when the focus is moved (by whatever means) to another metadata editor field, or to another module, or to another mode (e.g. darkroom) such that the editor holds something equivalent to a history for this particular image. Make the ‘apply’ button function to apply all the changes (including none) then close the metadata editor module.

**Alternatives**

**Additional context**
I have tried using presets in the past. They are not an ideal solution to this scenario because I end up with a huge number of presets, whose specific content I can not longer remember, so selecting the appropriate preset became ‘trial and error’. My current work-around is to create and save a facsimile of the metadata editor interface in a text editor external to darktable – which will maintain my data across any ‘clicking’ outside the metadata editor, (or indeed, in some editors,  partially survive a failure of my PC) -  and then doing a copy/paste into darktable when I am satisfied with the data. This also gives me the option to apply a long meaningful descriptive name to what is, in effect, a preset when I save the file in the external editor. This is not designed to replace the very useful 'copy/paste metadata' lua script, which I also use.

**Comment by zisoft** [comment]
+1
I have struggled with that as well several times.

**Comment by KIRSJ** [comment]
I think the current loss of text - which occurs repeatedly even with normal handling by the user - is very frustrating and way under the level of Darktable's features in general.
All written data into the metadata editor should immediately be saved in the background and presented when the cursor returns to the image (thumbnail) for which was written.

**Comment by KIRSJ** [comment]
Does this mean that the problem is solved with the next release?

**Comment by zisoft** [comment]
@KIRSJ yes, problem solved. Coming in 4.4

**Comment by LateJunction** [comment]
This is most gratifying - to see that my suggestions/comments really do get
read and considered no matter how inexpertly they are written and to
realise that a complete technical 'non-event' like myself can make a (very
small) contribution to what is an impressive product.

**Comment by KIRSJ** [comment]
I am also very satisfied with this prospect. Great work and response. Thank you.
