### ISSUE TITLE
[FR] blurs module enhancement - make mask aware

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#13838]
**Is your feature request related to a problem? Please describe.**
The weak point of the module currently is that if mask is used, the out of mask region is blurred/leaks into the masked region.
Because the blurs is made first and is not aware of the mask.
As the manual says: "general masking will only partially work to isolate the foreground of an image, since it will still be blurred into the background"

**Describe the solution you'd like**
Probably it would be ok, if it worked like this:
- copy pixels from masked region into not masked, >= $radius of blur
- apply blur
- apply mask

**Comment by ralfbrown** [comment]
That would be quite difficult, because masking is effectively a separate multi-instance module (technically, the only difference is that it takes two inputs instead of one), and modules can't see into each other's internals.  Plus, the mask may depend on the blur module's output....
