### ISSUE TITLE
When styles with more than one instance of a module are applied, the duplicated modules are expanded

### ISSUE THREAD

**Issue by europlatus** [darktable-org/darktable#13833]
**Describe the bug/issue**

Bit hard to describe this issue so the steps to reproduce might be more useful.
This applies to styles created from an image with more than one instance of a module. When you apply the style to an image, the duplicated module instances are displayed expanded rather than collapsed. Furthermore, this contradicts the setting "expand a single processing module at a time" in settings because there should only be one module expanded at a time.

**To Reproduce**

1. Apply some edits to an image, using two instances of two modules, e.g. Exposure + Exposure 1, color balance RGB + color balance RGB 1
2. Create a new style from this image.
3. Open another image and apply the new style.
4. See that the exposure 1 and color balance rgb 1 modules are both expanded after the style is applied.

**Expected behavior**

All modules should be collapsed after a style is applied. If one module needs to be expanded, then only one should be expanded if you have "expand a single processing module at a time" turned on in settings.

**Platform**

* darktable version : 4.2.1
* OS                : e.g. Tested on Win10

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with a RAW or Jpeg or both? **Both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

**Comment by ralfbrown** [comment]
I see the equivalent for one of my styles under Linux, and it's still present in 4.4.2.
