### ISSUE TITLE
Freeze when starting if SSH is configured to use a passphrase

### ISSUE THREAD

**Issue by mbaz** [darktable-org/darktable#13845]
My SSH keys are protected by a passphrase:
```
[~/.config/darktable/lua] $ git pull --all
Enter passphrase for key '/home/mbaz/.ssh/id_rsa':
```
I normally use an SSH agent to enter the passphrase only once when I log in to my computer. However, when the agent is not running, darktable freezes upon start. The reason is that it wants to update the lua scripts, but git requires the passphrase. These are the related processes that are running:
```
[~] $ ps aux | grep dark
mbaz       699  1.3  0.9 2158220 316220 tty1   Tl   13:13   0:01 darktable
mbaz       741  0.0  0.0   7480  3584 tty1     T    13:13   0:00 sh -c cd /home/miguel/.config/darktable/lua;git pull --all;git branch --all
mbaz       744  0.0  0.0  15440  8448 tty1     T    13:13   0:00 /usr/bin/ssh -o SendEnv=GIT_PROTOCOL git@github.com git-upload-pack 'darktable-org/lua-scripts.git'
```
I think darktable should be able to recover from this and not freeze, either by asking for the passphrase itself, or declining to update the lua scripts.

Additionally, I think that automatically updating the scripts is a bad idea for security reasons. The user should opt-in to this behavior, with opt-out by default.

**To Reproduce**

1. Set up your github account to use SSH by default
2. Assign a passphrase to your SSH keys
3. Make sure no SSH agent is running
4. Start darktable
5. See darktable freeze

**Expected behavior**

Darktable should fail gracefully.

**Which commit introduced the error**

Not known -- I will work to provide one, but it may take some time.

**Platform**

* darktable version : 4.2.1
* OS                : Linux
* Linux - Distro    : Fully updated Arch
* Memory            :  32GB
* Graphics card     : Intel coffeelake
* Graphics driver   : Intel
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : yes
* Desktop           : OpenBox

**Comment by wpferguson** [comment]
I'll add an option to script_manager to not check for updates.
