### ISSUE TITLE
Magenta hue with filmic v6 and highlight reconstruction

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#13849]
First, I want to thank you, @jenshannoschwalm, for all the effort you put into resolving the opencl issues with intel and highlight reconstruction. The inpaint and segmentation algorithms have catapulted forward the capabilities of darktable and I am truly grateful for that.

I was editing a photo tonight and discovered some very faint color casts with using hlr and filmic together. I don't want to appear as nitpicking, but I feel these are important as I'm sure new users might stumble upon this and judge darktable prematurely.

We're back to the familiar duck-in-the-pond image. In this first image, notice a very faint magenta color cast in the highlight area. It is strongest on the transition from the blue sky to the blown out highlights. The only way I could figure out how to remove the magenta was to switch filmic to v5 and disable preserve chrominance.
![inpaint_magenta](https://user-images.githubusercontent.com/10678620/223330926-e34c3788-4d18-42da-a53f-a617ddd68bd2.png)
I'm not sure if this is a bug in inpaint opposed, filmic, or simply a strange interaction between the two. Using sigmoid does not seem to exhibit the issue.

Switching to segmentation, the magenta color cast disappeared, but then I noticed that there is a harsh boundary right above the cloud. This harsh transition coincides with a segment boundary.
![inpaint_seg](https://user-images.githubusercontent.com/10678620/223330946-fe5796cc-cc6e-4684-8939-9541dbd612af.png)

darktable version: 4.3.0+1008~g5f62d310ea
platform: archlinux
opencl: disabled via `--disable-opencl`

**Comment by jenshannoschwalm** [comment]
To evaluate anything with hlr you should switch-off filmic and sigmoid.

The hlr reconstruction is depending on correct white balance so on some images you'd better set that to as-shot.

**Comment by Nilvus** [comment]
I follow @ralfbrown. To me it's not an issue but how that preservation mode works and that mode is not suitable for blue skies most of the time. So for such image, change preservation mode.

**Comment by jenshannoschwalm** [comment]
A very simple explanation, a remaining magenta cast with opposed means: not enough blue&green recovered. This can't be controlled in all cases...

**Comment by groutr** [comment]
Thank you for the replies. I've been tinkering around some more with different settings. As I stated above, I was unsure if this was a bug in hlr, filmic, or if it was simply a strange interaction between the two modules. It appears to be the third possibility. It seems to just be the way filmic does the transform mapping.

On the second image with segmentation and the hard edge, would it make sense to want to feather the edge of the segment for smoother transition? Is there a way to do that?

**Comment by groutr** [comment]
> On the second image with segmentation and the hard edge, would it make sense to want to feather the edge of the segment for smoother transition? Is there a way to do that?

It appears that candidating seems to be the smoothing effect for the hard edge, so my question can probably be disregarded and this issue closed.
