### ISSUE TITLE
Crashes of dt 4.2.1 on Mac 11.7.3

### ISSUE THREAD

**Issue by JackP-Z** [darktable-org/darktable#13860]
Crashes occur when using various modules parametric masks & recently after start up. All are due to a memory leak.
![Screen Shot 2023-03-07 at 3 20 21 PM](https://user-images.githubusercontent.com/96837650/223561383-baa7ef29-9704-4c72-a1c1-4459e5eb371f.png)
Mac crash reports were rejected in this submission.

**Comment by JackP-Z** [comment]
dt is a wonderful tool and past releases were quite stable, but this one is unusable at the moment. Pls. fix it. Thanks.

**Comment by parafin** [comment]
Paste it as text or upload as txt file, without crash report there is nothing to do about your report. I will re-open once you provide the information.

**Comment by JackP-Z** [comment]
Done.  These crashes occur on both the Big Sur and Ubuntu 20.04 when the parametric or drawn masks are used.

[darktable_2023-02-25-185718_Jacks-Mac-Pro.crash.txt](https://github.com/darktable-org/darktable/files/10925845/darktable_2023-02-25-185718_Jacks-Mac-Pro.crash.txt)
[darktable_2023-03-06-210459_Jacks-Mac-Pro.crash.txt](https://github.com/darktable-org/darktable/files/10925846/darktable_2023-03-06-210459_Jacks-Mac-Pro.crash.txt)
[darktable_2023-03-07-152200_Jacks-Mac-Pro.txt](https://github.com/darktable-org/darktable/files/10925847/darktable_2023-03-07-152200_Jacks-Mac-Pro.txt)
[darktable_2023-03-07-152323_Jacks-Mac-Pro.txt](https://github.com/darktable-org/darktable/files/10925848/darktable_2023-03-07-152323_Jacks-Mac-Pro.txt)

**Comment by JackP-Z** [comment]
One more test today on Mac with Ubuntu. Using parametric masks in the Contrast Equalizer and Astrophoto  modules didn’t crash dt, but adding a param. mask in the Blurs module resulted in a crash. I repeated this twice and had 2 crashes. The dt did not ask if I want to send the crash report to developer.
So, dt crashes on two different Macs with two different OS. 

![Screenshot from 2023-03-10 17-54-28](https://user-images.githubusercontent.com/96837650/224446065-15f71c18-5973-4d2c-9180-e4d81973c331.jpg)

**Comment by MStraeten** [comment]
for step 3 you need to unhide hidden files or use the terminal eg `mv ~/.config/darktable ~/.config/darktable.old` .
I doubt sending the report to apple will help since they don’t bother about foss software ;)

**Comment by JackP-Z** [comment]
I've repeatable crashes in the diffuse&sharpen module after drawn mask is created and the sharpening sliders used. No idea if this is due to the same issue as reported earlier in the astrophoto module. Attached is one of the crash reports.
![Screen Shot 2023-04-30 at 3 54 42 PM](https://user-images.githubusercontent.com/96837650/235374129-24e01636-2cd5-4d76-8760-7facd57bdfd1.png)
[Untitled.txt](https://github.com/darktable-org/darktable/files/11362229/Untitled.txt)
