### ISSUE TITLE
Adaptive sharpening on export (based on resolution and crop)

### ISSUE THREAD

**Issue by cornergraf** [darktable-org/darktable#13908]
**Is your feature request related to a problem? Please describe.**
It is very cumbersome to apply the proper amount of sharpening to each individual image on export, because images that are cropped heavily or have different image resolutions (different cameras) need to be sharpened differently.

**Describe the solution you'd like**
The sharpening that is set on a given image should be scaled up or down based on output resolution and area crop. E.g. an image that is exported to half the original resolution should have sharpening doubled, but reduced if the image is cropped (by the appropriate amount). I.e. the sharpening that is set in the darkroom should be seen as a baseline for the full resolution image, and then scaled appropriately.

**Alternatives**
The only alternative is the cumbersome manual process, which sucks.

**Additional context**
N/A

**Comment by cornergraf** [comment]
> Which method are you using for sharpening? Some of the newer modules such as Diffuse and Sharpen _do_ scale the radius according to image scaling, which is necessary anyway to give a proper display on screen. 

I was not aware of this change, maybe nothing else is needed then. I will have to check when I get home.

>But they need to be put after the Output Scaling module, which was only recently made user-visible and user-movable, so you'll need to use current master. (The default position of Output Scaling depends on whether High Quality Resampling is turned on for export - if "on", it is only applied as the very last step, if "off" it happens very early in the pipe.)

Aha! But then you are not actually scaling the sharpening radius, you are simply applying the sharpening after resizing - which I disagree with. I am not an expert, but I believe you get better quality results if you first sharpen and then resize.

> Unfortunately, other than radius there is no simple way to map different strengths to different scaling, which is why darktable is far from the only editor which tells you to use 100% view to verify the effects of operations such as sharpening and denoising.

I believe scaling the radius alone would be fine, but even if not, scaling the strength value (maybe with some tweakable factor) should work well too.

**Comment by TurboGit** [comment]
> But they need to be put after the Output Scaling module, which was only recently made user-visible and user-movable, so you'll need to use current master.

No, in fact this was rejected as not a proper solution. See #13682 for our current plan.
