### ISSUE TITLE
Images not rendering correctly.

### ISSUE THREAD

**Issue by riley-martin** [darktable-org/darktable#13919]
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behavior, for example:_
1. Open image in portrait orientation in darkroom view
2. Zoom in on image until it horizontally fills the viewport
3. Drag image around (sometimes not needed)
4. Image renders incorrectly (see screenshots)

**Expected behavior**
Image renders correctly :)

**Screenshots**
Incorrect rendering CR2 file:
![20230313_19h41m31s_grim](https://user-images.githubusercontent.com/106552431/224858629-85620026-6bf1-4132-a4a8-b2b25e616743.png)  

Incorrect rendering JPG file:
![20230313_20h05m16s_grim](https://user-images.githubusercontent.com/106552431/224859548-7e37d6f8-6620-4ca6-98ea-7a2f869a2ce3.png)

Zoomed in one step further; renders correctly:
![20230313_19h41m43s_grim](https://user-images.githubusercontent.com/106552431/224858722-70101930-f72e-489d-b20e-70867b8e3c0e.png)

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**

* darktable version : 4.2.1
* OS                : Linux (kernel linux-6.2.2-artix1-1)
* Linux - Distro    : Artix Linux (similar to Arch)
* Memory            : 8GB
* Graphics card     : Intel TigerLake-LP GT2 (Intel Iris Xe integrated graphics)
* Graphics driver   : i915
* OpenCL installed  : yes
* OpenCL activated  : no
* Xorg              : no
* Desktop           : Hyprland
* GTK+              : unknown
* gcc               : 12.2.1
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
 - I have only managed to reproduce this with portrait images, not landscape.
 - Can you reproduce with a RAW or Jpeg or both? **both**, but slightly different for CR2 vs JPG (see screenshots)
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**, I noticed it on a fresh darktable install
 - Do you use lua scripts? **no**
 - What happens to the RAW images looks to me a lot like an indexing error

**Comment by TurboGit** [comment]
The most important information is not there! Which version of darktable? Is that a flatpak or native version?

**Comment by TurboGit** [comment]
> * Desktop           : Hyprland

Maybe this? I'm not sure we have many people using such desktop.

**Comment by Nilvus** [comment]
And it's Wayland related. Many issues related to Wayland were about Gtk support, not rendering. But in case, if you launch darktable with X11 backend instead of Wayland, in a terminal with that command:
`
GDK_BACKEND=x11 darktable`

Or try by using another desktop running on X11.

Did you see changes? Is this still there or solved?

**Comment by riley-martin** [comment]
> The most important information is not there! Which version of darktable? Is that a flatpak or native version?  

Sorry, I updated the question. It is a native version.

**Comment by riley-martin** [comment]
From further experimentation, it seems like this issue is present when OpenCL is disabled.
