### ISSUE TITLE
Lumix G9 RW2 HiRes: magenta pixels on the side of RAW image

### ISSUE THREAD

**Issue by jortam** [darktable-org/darktable#13926]
Hello,

when opening my `Panasonic Lumix G9 HiRes RAW images` on `Windows 10`, they all have "_magenta pixels on the right side_":

![image](https://user-images.githubusercontent.com/127892812/225119885-9c8c8a5b-1ce5-429f-bb71-0481494314f6.png)

It feels like i have seen this issue already but i have no idea how to name that and didn't find it again.

I have checked the images in several programs, like RawTherapee, Photoshop Express, Image Raw or anything else, i have never had this issue, but in DT it is in every `HiRes .RW2` image, but not in those JPEGs.

```
C:\Program Files\darktable\bin>darktable-cli --version
this is darktable-cli 4.2.1
copyright (c) 2012-2023 johannes hanika, tobias ellinghaus
```

It is visible in exported images.

**Comment by jortam** [comment]
This is a file zipped in 2 parts. You must rename it.

First: `_1003999.zip.001`

[_1003999.zip](https://github.com/darktable-org/darktable/files/10973452/_1003999.zip)

Second: `_1003999.zip.002`

[_1003999 (2).zip](https://github.com/darktable-org/darktable/files/10973463/_1003999.2.zip)

**Comment by Nilvus** [comment]
I can replicate too. I use G9 but never use Hi Res images. This do not happen on non Hi Res images.

With your image, I've found that if I active lens correction module, those magenta pixels are slightly reduce. Remains just few magenta pixels on top and bottom. Could you test on your side by activating that module?

**Comment by jortam** [comment]
@Nilvus 

Thank you for quick response.

Yes, i can confirm, applying lens correction does reduce heavily in the middle. To the top and to the bottom it then becomes more visible again, and again only on the right side. I have tested this now on several images and on the dark image shared above:

![image](https://user-images.githubusercontent.com/127892812/225148125-aaf095ec-759a-491e-878d-bb9f7c628f5a.png)

**Comment by jortam** [comment]
Ok, changing the `scale` from `1,006` to `1,008` seems to solve this, but why is this only in DT? Lensfun is used widely?

**Comment by TurboGit** [comment]
Maybe a rawprepare crop issue with this camera. @kmilos what do you think?

**Comment by jenshannoschwalm** [comment]
Yes a crop issue for rawprepare.

**Comment by kmilos** [comment]
Yep, need to crop 78 from the right in this mode (confirmed on RPU sample), instead of 58 given by rawspeed/data/cameras.xml for the normal mode. @LebedevRI

**Comment by kmilos** [comment]
In the meantime, you can change the line `plugins/darkroom/rawprepare/allow_editing_crop=false` in `%LOCALAPPDATA%\darktable\darktablerc` and adjust the rawprepare (raw black/white point) module crop manually...

**Comment by jortam** [comment]
By the way, the original crop size is given by Panasonic as `10368 x 7776`:

![image](https://user-images.githubusercontent.com/127892812/225411894-3ec278af-4b39-47b9-abcf-9f1b8cdc008f.png)

The actual (wrong) crop size is: 

![image](https://user-images.githubusercontent.com/127892812/225412777-cecbe386-57bc-45b4-9baa-a01cdca11b84.png)

So the differences are in landscape version:
- vertically -54 px
- horizontally -18 px

**Comment by kmilos** [comment]
We (RawSpeed) generally don't go by vendor crops, but try to establish the maximum data crop ourselves.

**Comment by bediicco** [comment]
> I did not find anything around rawprepare.

```cmd
C:\Program Files\darktable\share\darktable\rawspeed\cameras.xml
```

**Comment by kmilos** [comment]
> > I did not find anything around rawprepare.
> 
> ```batchfile
> C:\Program Files\darktable\share\darktable\rawspeed\cameras.xml
> ```

Nope.

**Comment by jsmucr** [comment]
https://github.com/darktable-org/rawspeed/pull/490
