### ISSUE TITLE
Red borders after applying Filmic RGB's reconstruct

### ISSUE THREAD

**Issue by DamLiew** [darktable-org/darktable#13924]
**Steps to reproduce**

1. Download darktable via Homebrew (leaving all settings at default)
2. Open RAW image
3. Apply Filmic RGB's reconstruct module

Relevant screenshots and the original RAW have been posted on [the discussion page](https://discuss.pixls.us/t/weird-edges-after-filmics-highlight-reconstruct/35714) on pixls.us. 

Activating OpenCL and increasing darktable's allocated resources to "large" solved the issue

Here's the .txt formatted xmp: [DSC00057.ARW.txt](https://github.com/darktable-org/darktable/files/10972002/DSC00057.ARW.txt)

**Additional context**

 - Can you reproduce with another darktable version(s)? **Not tested**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format (not tested with JPEG)**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **Yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **Yes**
 - Do you use lua scripts? **No**

**System**

* darktable version : 4.2.1
* OS: OSx 13.2.1
* Memory : 16GB
* Graphics card : 14-Core Integrated (M1 Pro CPU)
* Graphics driver : -
* OpenCL installed  : Yes
* OpenCL activated  : No (activating fixes bug)
* Xorg : -
* Desktop : -
* GTK+ : -
* gcc : -
* cflags : -
* CMAKE_BUILD_TYPE  : -

**Comment by jenshannoschwalm** [comment]
Fixed in master
