### ISSUE TITLE
CR3 & CR2 NOT WORKING FOR DETAIL THRESHOLD

### ISSUE THREAD

**Issue by mcalapico** [darktable-org/darktable#13923]
Trying to use CR3 (eosR7) & CR2 (EOS 7DII) files to create masks by using the details threshold slider, but is not working at all. However when using it with raw files from EOS 350D it works fine.

**Comment by mcalapico** [comment]
Sorry, its my first time posting here….which information should I add?

**Comment by ptilopteri** [comment]
all requested that you can provide.
