### ISSUE TITLE
Missing application icon after launching

### ISSUE THREAD

**Issue by bremner** [darktable-org/darktable#13946]
A Debian user reported (and I confirmed in a fresh Bookworm VM),
```
Under GNOME (43.3), the Darktable icon is visible when searching for the app,
but once the window is spawned, it is associated with a generic missing icon
(for example in Alt+Tab or the Activities overview).

The associated wmclass is "darktable", which seems fine. Not sure why the icon
disappears.
```
You can see the unknown icon(s) in two places, in the menu bar, and in the dock (?) activity-bar (?) on the bottom.

I'm not a Gnome user, so I don't have any sensible ideas what is going on here. It doesn't seem like something specific to Debian, but I guess you never know.

**Comment by Nilvus** [comment]
I use Gnome 43.3 (with Debian Sid) as well as, at least of main developer here, and never had such issue. I can see darktable icon on all parts of Gnome (menu bar, dock, activity, etc.) and use darktable and Gnome since some years now without any issue. Probably something broken on its side. As this is probably not directly darktable code issue, help would be better for him on discuss.pixls.us forum as this place is for things related to darktable code.

You didn't precise which darktable version and how he installed darktable. If darktable is from Debian repository, maybe it's a package issue and so should be seen with Debian package tracker. I use master and compile darktable myself, so don't have darktable package from Debian repository.

**Comment by kmilos** [comment]
Is this perhaps related to https://github.com/darktable-org/darktable/pull/13193?

**Comment by Nilvus** [comment]
I don't know. Did you test Open Build Service package, that darktable team propose on its install page, if you have same issue? It's a deb package too. See on install page, in darktable.org website to test it.

@TurboGit: any more idea on that one?

**Comment by Nilvus** [comment]
Just tested to install darktable 4.2.1-3 package from Debian Sid repository and I have the icon on my side. I even make sure on testing to:
- remove darktable config folder
- my darktable.desktop file on .local/share/applications folder
- and restart Gnome session
I still have darktable icon.

**Comment by bremner** [comment]
I wonder if there is some missing dependency (or files installed some other way), since I do see the missing icon problem installing in a fresh Debian bookworm VM. Another possibility might be some difference of library version between Bookworm (i.e. current testing) and Sid.

**Comment by TurboGit** [comment]
That's strange. I have the icon on my dev machine, but let's forget about this one... On another machine Debian/testing I'm installing using standard apt. The icon is there, and this is handled by the standard:

`/usr/share/applications/org.darktable.darktable.desktop`

Do you have this file installed?

You should have it as it is part of the main package:

```
$ apt-file search org.darktable.darktable.desktop
darktable: /usr/share/applications/org.darktable.darktable.desktop
```

Have you installed some flatpak on this machine? Maybe this has messed something....

**Comment by bremner** [comment]
@TurboGit Yes, I have the file `/usr/share/applications/org.darktable.darktable.desktop`. The machine is a freshly installed VM, with darktable the only thing installed on top of a basic gnome install.  The odd thing is that the icon does show up when searching in activities, just not anywhere else.

**Comment by bremner** [comment]
BTW, I noticed the problem only occurs in a Wayland, so that may explain why some of you don't see it.

**Comment by Nilvus** [comment]
Wayland issue indeed. I use X11, @TurboGit also.And we both have the icon.

**Comment by bremner** [comment]
@victoryforce It could also be the way darktable is using wayland. It's not like this happens for all applications in GNOME/wayland.

**Comment by victoryforce** [comment]
> @victoryforce It could also be the way darktable is using wayland. It's not like this happens for all applications in GNOME/wayland.

Would you be able to see what the wmclass is for the darktable window and see if adding this name to StartupWMClass= in the darktable desktop file solves the problem?

**Comment by bremner** [comment]
The wmclass is "darktable" and  adding StartupWMClass=darktable at the end of the .desktop file seems to fix it.

**Comment by victoryforce** [comment]
@bremner Thanks for checking! So I will add this fix to the darktable desktop file.
