### ISSUE TITLE
Master wont build on Ubuntu 22,04 LTS

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#13943]
System is Ubuntu 22.04 up to date as of today.

commit e2c8b233a72bcdbf884047c2cf4cc16cd1bf4730 ups GCC version to 12.  Ubuntu 22.04 is 11.3

Error during config 

```
CMake Error at cmake/compiler-versions.cmake:40 (message):
  GNU C compiler version 11.3.0 is too old and is unsupported.  Version 12+
  is required.
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)


CMake Error at cmake/compiler-versions.cmake:43 (message):
  GNU C++ compiler version 11.3.0 is too old and is unsupported.  Version 12+
  is required.
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)
```

**Comment by ralfbrown** [comment]
That's going to hit me too, as my distro's current release has GCC 10.4.  The beta of the next release just came out, so I'll have GCC 12 by summer but not right now unless I upgrade to the beta.

I saw the PR with the cmake change, but didn't realize it was being merged right away and would entirely prevent building.

**Comment by pehar1** [comment]
Same here with current master 4.3.0-1240-gf6a935b736 on Ubuntu 22.04 LTS

```
apt-cache policy gcc
gcc:
  Installiert:           4:11.2.0-1ubuntu1
  Installationskandidat: 4:11.2.0-1ubuntu1
  Versionstabelle:
 *** 4:11.2.0-1ubuntu1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by kmilos** [comment]
GCC 12 is available on Ubuntu 22.04, the CI uses it.

**Comment by pehar1** [comment]
Installed gcc-12 :
`sudo apt install gcc-12`

Made gcc-12 the default :
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
```

Checked :
```
sudo update-alternatives --config gcc
Es gibt 2 Auswahlmöglichkeiten für die Alternative gcc (welche /usr/bin/gcc bereitstellen).

  Auswahl      Pfad             Priorität Status
------------------------------------------------------------
* 0            /usr/bin/gcc-12   12        automatischer Modus
  1            /usr/bin/gcc-11   11        manueller Modus
  2            /usr/bin/gcc-12   12        manueller Modus
```

Checked :
```
gcc --version
gcc (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
```

but still get

```
CMake Error at cmake/compiler-versions.cmake:40 (message):
  GNU C compiler version 11.3.0 is too old and is unsupported.  Version 12+
  is required.
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)


CMake Error at cmake/compiler-versions.cmake:43 (message):
  GNU C++ compiler version 11.3.0 is too old and is unsupported.  Version 12+
  is required.
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)
```

**Comment by kmilos** [comment]
```
export CC=gcc-12
export CXX=g++-12
```

**Comment by pehar1** [comment]
> probably be better discussed in your distro support forums

In principle I agree, but I suspect not only Ubuntu users will be affected by this commit

```
export CC=gcc-12
export CXX=g++-12
```

Checked :
```
echo $CC
gcc-12
echo $CXX
g++-12
```
but still the same error...

**Comment by kmilos** [comment]
> Checked :

Probably need to clean the build folder (CMake cache) then.

The Ubuntu 22.04 CI works, so there is no issue as far as dt is concerned.

**Comment by pehar1** [comment]
@kmilos , thanks for the support.
`g++-12` was missing (stupid mistake on my part) and `make clean` was not enough, CMake cache had to be cleared manually. Successfully built.

**Comment by kmilos** [comment]
OTOH, maybe there is a case after all to relax this to at least 11.3: CentOS Stream 9 and LTS derivatives like RHEL9 will be around for a couple of more years (10 expected in 2024). @TurboGit @LebedevRI @victoryforce

**Comment by victoryforce** [comment]
> OTOH, maybe there is a case after all to relax this to at least 11.3: [CentOS Stream 9 and LTS derivatives like RHEL9 will be around for a couple of more years (10 expected only in 2024-2025).](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Version_history_and_timeline) @TurboGit @LebedevRI @victoryforce

I'd vote for relaxing. We can announce that we only officially support building with gcc 12+, but not block the ability to use gcc 11 for those who really need it.

If we really want to show the undesirability of gcc 11, we could, for example, make it possible to build only with a special option/define, but as long as the source code does not contain incompatibilities with that compiler, why not allow it?

**Comment by TurboGit** [comment]
> I'd vote for relaxing. We can announce that we only officially support building with gcc 12+, but not block the ability to use gcc 11 for those who really need it.

That's also ok by me. Let's give a chance to "old" compilers to still be used if possible. But we cannot guarantee that it will work in the future and we won't support it.

**Comment by ralfbrown** [comment]
> That's also ok by me. Let's give a chance to "old" compilers to still be used if possible. But we cannot guarantee that it will work in the future and we won't support it.

That's fine with me.  Master has been building and working without any problems using GCC 10.4.... (other than that one little bit of poor-quality code generation, but that wasn't an operational issue *per se*)

**Comment by wpferguson** [comment]
For 22.04 users you can do the following:

`sudo apt install gcc-12 g++-12
`
then

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

```
then 

`sudo update-alternatives --config gcc
`
and select the gcc compiler to use, and

`sudo update-alternatives --config g++
`
to select the version of g++ to use

**Comment by LebedevRI** [comment]
While it may seem really tempting to "we don't support that but oh wait we actually do",
we can't have it both ways. The whole point of requiring something, is providing guarantee
that we can rely that the version is supported. The whole point of CI is to catch things like that.
If it's not covered by the CI, something *will* break the GCC11 build, and then what?
Since it's not supported but not really not supported, how is that situation supposed to be dealt with?
Will it become truly unsupported the moment it no longer builds? Will such issues be closed as WONTFIX?

If someone wants to propose wording for the distro support, different from the current one,
please do feel free to do so. But either version $x is supported and is part of CI, or it is explicitly not supported.

**Comment by LebedevRI** [comment]
> OTOH, maybe there is a case after all to relax this to at least 11.3: [CentOS Stream 9 and LTS derivatives like RHEL9 will be around for a couple of more years (10 expected only in 2024-2025).](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Version_history_and_timeline)

They come with a **very** fresh, well-supported LLVM version though: https://centos.pkgs.org/9-stream/centos-appstream-x86_64/clang-15.0.1-2.el9.x86_64.rpm.html

**Comment by KarlMagnusLarsson** [comment]
What is the technical reason for forcing  GNU C compiler  Version 12+  to be required?

**Comment by LebedevRI** [comment]
(Note: this is the very same disscussion we are having over and over again every time.
This all has happened before during previous version bumps and will happen again in the future.)

Old compilers are old and don't provide newer features.
E.g. i'd like to move forward to C++20, and some bits of OpenMP5. Is that fully supported in GCC10?
The SSE codepaths have been dropped recently. Does GCC10 vectorize everything, or is DT now broken there?
etc etc

Now, can we have infinite number of CI jobs? No, there's a limit, and even beyond that,
only so many jobs can be run concurrently. So we *have to* set some limits on what we test in CI.

Then there's more practical question: there is a GCC release every 12 months, and a LLVM release every 6 months.
I can tell you from practice, if something is not being tested via CI, it **will** get immediately broken.
So if we don't verify that some compiler version can *at least* compile the code,
then said build will get broken in a blink of an eye.

If we must support GCC11, by all means let's do that, but let's be consistent about it,
not special-case it, like we did with XCode.

**Comment by KarlMagnusLarsson** [comment]
> I can tell you from practice, if something is not being tested via CI, it **will** get immediately broken.
> So if we don't verify that some compiler version can _at least_ compile the code,
> then said build will get broken in a blink of an eye.

It is fine to test GNU C compiler Version 12+ requirement in CI. There can be many CI tests for different compilers, settings and platforms.

> Old compilers are old and don't provide newer features.
> E.g. i'd like to move forward to C++20, and some bits of OpenMP5. Is that fully supported in GCC10?
> The SSE codepaths have been dropped recently. Does GCC10 vectorize everything, or is DT now broken there?
> etc etc

If I remove the  GNU C compiler Version 12+ requirement in https://github.com/darktable-org/darktable/commit/e2c8b233a72bcdbf884047c2cf4cc16cd1bf4730:
```
git clone --recurse-submodules https://github.com/darktable-org/darktable.git
git submodule update --init
git revert e2c8b23
```
Then, what is not working in darktable git master and why?

I get a working darktable, as far as I can see, after `git revert e2c8b23` and building on Debian stable 11.6 with gcc (Debian 10.2.1-6) 10.2.1 20210110. 

What is needed in git master branch from C++20 and OpenMP5?

**Comment by ralfbrown** [comment]
For the SSE I removed, GCC 10.4 vectorizes just fine (it's the version I'm pretty much stuck with until the next version of my distro is released in a few months).

Some of the SSE paths haven't yet been removed because GCC 10 vectorizes but does a poor job and yields slower code than the hand-written SSE.  In the one case where I recently added back a few lines conditionally compiled with SSE, using memory for intermediate values was the main cause of the major slowdown with GCC 10 versus the compiler used by the person who contributed the patch removing that particular code path -- but it still yielded correct results.

AFAIK, master doesn't use any C++20 or OpenMP5 features, but Roman would like to add them.

**Comment by jenshannoschwalm** [comment]
Ralf, yes, indeed i missed checking performance / vectorizing v10 (using v11, v12 here)

**Comment by LebedevRI** [comment]
> > I can tell you from practice, if something is not being tested via CI, it **will** get immediately broken.
> > So if we don't verify that some compiler version can _at least_ compile the code,
> > then said build will get broken in a blink of an eye.
> 
> It is fine to test GNU C compiler Version 12+ requirement in CI. There can be many CI tests for different compilers, settings and platforms.

Sure, but i think you may be missing the point. 

> > I can tell you from practice, if something is not being tested via CI, it **will** get immediately broken.
> > So if we don't verify that some compiler version can _at least_ compile the code,
> > then said build will get broken in a blink of an eye.
> 
> It is fine to test GNU C compiler Version 12+ requirement in CI. There can be many CI tests for different compilers, settings and platforms.
> 
> > Old compilers are old and don't provide newer features.
> > E.g. i'd like to move forward to C++20, and some bits of OpenMP5. Is that fully supported in GCC10?
> > The SSE codepaths have been dropped recently. Does GCC10 vectorize everything, or is DT now broken there?
> > etc etc
> 
> If I remove the GNU C compiler Version 12+ requirement in [e2c8b23](https://github.com/darktable-org/darktable/commit/e2c8b233a72bcdbf884047c2cf4cc16cd1bf4730):
> 
> ```
> git clone --recurse-submodules https://github.com/darktable-org/darktable.git
> git submodule update --init
> git revert e2c8b23
> ```
> 
> Then, what is not working in darktable git master and why?
> 
> I get a working darktable, as far as I can see, after `git revert e2c8b23` and building on Debian stable 11.6 with gcc (Debian 10.2.1-6) 10.2.1 20210110.

Of course it does, because no new code that depends on newer GCC version has been added yet.

> Debian stable use gcc 10.2.1.
> 
> > The SSE codepaths have been dropped recently. Does GCC10 vectorize everything, or is DT now broken there?
> > etc etc
> 
> Can @ralfbrown , or some other specialist comment on SSE Codepath removal/maintenance and GCC 10 compatibility?
> 
> What is needed in git master branch from C++20 and OpenMP5?



> AFAIK, master doesn't use any C++20 or OpenMP5 features, but Roman would like to add them.

Yup. That's the whole point. That is how this works.
With time, baseline compiler requirement can be bumped,
and that allows us to use features added in the now-required compiler versions.
And this is not even compiler-specific.

**Comment by KarlMagnusLarsson** [comment]
I have compiled, bootstrapped and tested gcc-12.2 from gcc source ftp://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.xz and installed it in my darktable sandbox on debian stable. It works for me when compiling darktable git master.

I am reluctant to move to debian testing (and their gcc 12) until I have tested color management on GTK4. It did not work for me in an earlier version of debian testing.

**Comment by LebedevRI** [comment]
Does anyone have any further thoughts here? Can we assume that, by now ,everyone who builds `master`,
would have already hit this and complained, and there aren't many complaints, so this is fine?

**Comment by ralfbrown** [comment]
What about packagers, who wouldn't necessarily be compiling anything besides the official releases?
It may be better to wait until 4.4 is out.

**Comment by kmilos** [comment]
> It may be better to wait until 4.4 is out.

I guess the expectation is that by the time 4.4 is released, the major LTS distros meeting these requirements will be supported: Ubuntu 23.04, openSUSE Leap 15.5, CentOS stream 9 (through AppStream LLVM only), and Debian 12 (the only one that doesn't have a committed release date yet though).

**Comment by LebedevRI** [comment]
> > It may be better to wait until 4.4 is out.
> 
> I guess the expectation is that by the time 4.4 is released, the major LTS distros meeting these requirements will be supported: Ubuntu 22.04, openSUSE Leap 15.5, CentOS stream 9 (through AppStream LLVM only), and Debian 12 (the only one that doesn't have a committed release date yet though).

Correct, that is literally what https://github.com/darktable-org/darktable/blob/e2c8b233a72bcdbf884047c2cf4cc16cd1bf4730/cmake/compiler-versions.cmake#L3-L10 says.

**Comment by TurboGit** [comment]
> and Debian 12 (the only one that doesn't have a committed release date yet though).

I doubt for Debian-12, no date but the releases are often later (around July or August) recent years. So I'm also in favor of relaxing the check for building. We using only GCC 12 in GitHub-CI though. We do not guarantee that it will work for older compilers but we do not block it yet.

This is also important for our current users testing darktable and reporting issues.

**Comment by LebedevRI** [comment]
It looks like my comments were not addressed.

**Comment by LebedevRI** [comment]
(should this be closed now?)

**Comment by wpferguson** [comment]
I think we can

**Comment by bilddateien** [comment]
This is all bad news for me.
Coming from https://github.com/darktable-org/darktable/pull/13995 to this discussion.
Just wanted to build the current master of today to start preparing for the release next month - looking at changes, doing screenshots and starting to draft an article for my german language readership (from the user point of view as I am not involved deep enough to draft those famous releas articles I used to translate in the past).

I am on latest Debian stable 11.7 and gcc12 is not available for me:
```
~# apt install gcc-12 g++-12 
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Paket g++-12 ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.

E: Paket gcc-12 kann nicht gefunden werden.
E: Für Paket »g++-12« existiert kein Installationskandidat.
```

**Comment by kmilos** [comment]
> Just wanted to build the current master of today to start preparing for the release next month

IMHO, a bit too early for that, dt features are not frozen yet. In any case, you have the LLVM option instead...

Btw, I saw Debian 12 is planned for June 10 now...

**Comment by LebedevRI** [comment]
> Changing the two lines checking GCC version in `cmake/compiler-versions.cmake` will let you build, though you may need to roll back rawspeed to mid-March. The older rawspeed plus today's master compiles just fine with GCC 10.4 if you change the version check.

At this point, a similar change in the same file in rawspeed should be enough.
Perhaps there should be a "warranty void"-style of a cmake escape hatch opt-in option to disable these checks.

**Comment by KarlMagnusLarsson** [comment]
I think we have a true bifurcation on git master. A simple make file patch does not work for me. I can get gcc 10.2.1-6 on Debian 11 to configure using cmake patch, but the make stage fails. If I use gcc 12.2 all is well. 

This change to `cmake/compiler-versions.cmake` and `/src/external/rawspeed/cmake/compiler-versions.cmake
`

```diff
-if(CMAKE_C_COMPILER_ID STREQUAL "GNU" AND CMAKE_C_COMPILER_VERSION VERSION_LESS 12)
+if(CMAKE_C_COMPILER_ID STREQUAL "GNU" AND CMAKE_C_COMPILER_VERSION VERSION_LESS 10)
   message(SEND_ERROR "GNU C compiler version ${CMAKE_C_COMPILER_VERSION} is too old and is unsupported. Version 12+ is required.")
 endif()
-if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12)
+if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 10)
   message(SEND_ERROR "GNU C++ compiler version ${CMAKE_CXX_COMPILER_VERSION} is too old and is unsupported. Version 12+ is required.")
 endif()

```
will allow `cmake` to cofigure fully, but `make` fails, for me on gcc (Debian 10.2.1-6) 10.2.1 20210110:
```c
[  4%] Building CXX object lib/darktable/rawspeed/CMakeFiles/rawspeed.dir/src/librawspeed/decompressors/AbstractDngDecompressor.cpp.o
In file included from /home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/PrefixCodeLookupDecoder.h:25,
                 from /home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/PrefixCodeLUTDecoder.h:26,
                 from /home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/PrefixCodeDecoder.h:25,
                 from /home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractLJpegDecoder.h:29,
                 from /home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/LJpegDecoder.h:23,
                 from /home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractDngDecompressor.cpp:31:
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h: In member function ‘void rawspeed::AbstractPrefixCodeDecoder<CodeTag>::verifyCodeValuesAsDiffLengths() const’:
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h:53:35: error: ‘Base’ has not been declared
   53 |     for (const auto cValue : code.Base::codeValues) {
      |                                   ^~~~
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h: In member function ‘size_t rawspeed::AbstractPrefixCodeDecoder<CodeTag>::maxCodePlusDiffLength() const’:
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h:72:54: error: ‘Base’ has not been declared
   72 |     return maxCodeLength() + *(std::max_element(code.Base::codeValues.cbegin(),
      |                                                      ^~~~
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h:73:54: error: ‘Base’ has not been declared
   73 |                                                 code.Base::codeValues.cend()));
      |                                                      ^~~~
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h: In member function ‘bool rawspeed::AbstractPrefixCodeDecoder<CodeTag>::operator==(const rawspeed::AbstractPrefixCodeDecoder<CodeTag>&) const’:
/home/magnus/camera2/test2/darktable-bisect/darktable/src/external/rawspeed/src/librawspeed/decompressors/AbstractPrefixCodeDecoder.h:96:17: error: ‘Base’ has not been declared
   96 |            code.Base::codeValues == other.codeValues;
      |                 ^~~~
make[2]: *** [lib/darktable/rawspeed/CMakeFiles/rawspeed.dir/build.make:407: lib/darktable/rawspeed/CMakeFiles/rawspeed.dir/src/librawspeed/decompressors/AbstractDngDecompressor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2795: lib/darktable/rawspeed/CMakeFiles/rawspeed.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

```
while gcc 12.2 is fine.

**Comment by ralfbrown** [comment]
I did say that you might need to roll back rawspeed....

Though I do wonder why GCC10 complains that an identifer is not declared where GCC12 thinks everything is fine.

**Comment by bilddateien** [comment]
> Btw, I saw Debian 12 is planned for June 10 now...

Just updated one of my machines - now I get 
```
$ cmake --build .
[  0%] Updating version string (git checkout)
/home/username/github/darktable-org/darktable/tools/create_version_c.sh: 13: ./tools/get_git_version_string.sh: Permission denied
gmake[2]: *** [CMakeFiles/create_version_gen.dir/build.make:71: CMakeFiles/create_version_gen] Fehler 126
gmake[1]: *** [CMakeFiles/Makefile2:1247: CMakeFiles/create_version_gen.dir/all] Fehler 2
gmake: *** [Makefile:156: all] Fehler 2
```
which leaves me lost ...

**Comment by wpferguson** [comment]
I'm on an up to date 22.04 LTS and darktable builds fine.  Try running the `./tools/get_git_version_string.sh` from a shell and see what it replies with.

**Comment by bilddateien** [comment]
strange ... had to set the "executable" flag for `get_git_version_string.sh` and also `get_last_commit_year.sh` manually. Never had to do this before ...

```
$ ./tools/get_git_version_string.sh
4.3.0+2515~g0c00997ffc-dirty
```

Now `make` seems to do something ...

**Comment by ralfbrown** [comment]
The compiler crash appears to be an error in the way debian 12 is building gcc: #14701

**Comment by KarlMagnusLarsson** [comment]
Hello, @bilddateien,

I have the same problem as you. A workaround is to install package clang and then do:
```
export CC=clang
export CXX=clang++
```
After this I can configure and build as usual:
```
git clone --recurse-submodules https://github.com/darktable-org/darktable.git
cd darktable
git submodule update --init
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="$HOME/darktable-debian12/install" -DCMAKE_BUILD_TYPE=Release ..
make 
```
And then `cd $HOME/darktable-debian12/install/bin` and execute `./darktable`

**Comment by KarlMagnusLarsson** [comment]
This Works for me.

1. Build gcc-12-2-0 from gnu/gcc code with `export CFLAGS="-march=native"` and `export CXXFLAGS="-march=native"` to avoid the BMI1 instruction pointed out by @LebedevRI. I bootstrapped local gcc from debian gcc 12.2.0.
2. Build ISL to get a local libisl to avoid the shlx instruction pointed out by @LebedevRI in libisl23.so from Debian. EDIT:same flags as for gcc or unset flags work. I did `./autogen.sh`, `configure`, `make`. I built libisl v0.26 with my local gcc compiler.

With my local gcc and local libisl I can build and run darktable.

**Comment by bilddateien** [comment]
Hello @KarlMagnusLarsson 
I tried what you told me in https://github.com/darktable-org/darktable/issues/13943#issuecomment-1588586243 but does not seem to work. 
Do I have to enter 
```
export CC=clang
export CXX=clang++
```
as root? If not ... from which folder?
(I don't run a `sudo` system but have root and user seperated accounts as it used to be in old times)

**Comment by bilddateien** [comment]
While cmake was running fine before I now get
```
$ cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable/ ..
-- The CXX compiler identification is Clang 14.0.6
-- The C compiler identification is Clang 14.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
  (Required is at least version "4.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindOpenMP.cmake:580 (find_package_handle_standard_args)
  CMakeLists.txt:90 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/benutzer/github/darktable-org/darktable/build/CMakeFiles/CMakeOutput.log".
See also "/home/benutzer/github/darktable-org/darktable/build/CMakeFiles/CMakeError.log".
```
after putting those `export` commands into the root shell :(

**Comment by victoryforce** [comment]
@bilddateien You should install developer package for the LLVM OpenMP runtime for the same version as the version of Clang you are using. So if you're using Clang 14, you should install something like libomp-14-dev.

**Comment by KarlMagnusLarsson** [comment]
Btw, if one stays on Debian and gcc 12.2.0 the error is confined to Debian 12 libisl only. Gcc was not involved.

> This Works for me, working around the bug in #14701.
> 
> 1. Build gcc-12-2-0 from gnu/gcc code with `export CFLAGS="-march=native"` and `export CXXFLAGS="-march=native"` to avoid the BMI1 instruction pointed out by @LebedevRI. I bootstrapped local gcc from debian gcc 12.2.0.
> 2. Build ISL to get a local libisl to avoid the shlx instruction pointed out by @LebedevRI in libisl23.so from Debian. EDIT:same flags as for gcc or unset flags work. I did `./autogen.sh`, `configure`, `make`. I built libisl v0.26 with my local gcc compiler.
> 
> With my local gcc and local libisl I can build and run darktable using Debian 12 Bookworm.

**Comment by bilddateien** [comment]
> @bilddateien You should install developer package for the LLVM OpenMP runtime for the same version as the version of Clang you are using. So if you're using Clang 14, you should install something like libomp-14-dev.

Thanks, will try as soon as time allows as I do not know much about all this.
Only reason I try building darktable I explained here https://github.com/darktable-org/darktable/issues/13943#issuecomment-1529827433 but now release is over for this time.
