### ISSUE TITLE
Ricoh GR-IIIx noise profiles

### ISSUE THREAD

**Issue by Donatzsky** [darktable-org/darktable#13953]
For noise profiles, please also attach the entire archive with `.pdf` plots.
[gr-iiix-darktable-noiseprofile-20230317.tar.gz](https://github.com/darktable-org/darktable/files/11006707/gr-iiix-darktable-noiseprofile-20230317.tar.gz)

**Comment by rawfiner** [comment]
The profile looks a bit strange (the "a" value should increase with ISO, here we have a few cases where it decreases), could you try to redo it with another set of images?
You can try to overexpose a little bit more, the histograms show that values are quite concentrated in the shadows and there is little midtones.
Thanks!

**Comment by Donatzsky** [comment]
Ah, bummer. Will have to borrow the camera again, then.

What do you mean by "a" value? Aperture?

Here's the generated file from the ISO 100 shot, to give you an idea of the exposure:
![R0004293_100-ISO_4-exp_3 5_f-thumb](https://user-images.githubusercontent.com/4938390/226394242-87dfb234-c212-4b65-a22c-7bb5e6aeda59.jpg)

Is it possible that the gradient isn't dense enough at the dark end?

**Comment by kmilos** [comment]
> What do you mean by "a" value? Aperture?

Nope, there are two parameters that make up the noise profile ("a" and "b") calculated for each ISO.

**Comment by rawfiner** [comment]
Indeed, "a" value in the json file. Thanks for the info @kmilos , the behaviour seems indeed different than usual. I would prefer to double check the behaviour with another set of images though.

**Comment by garrett** [comment]
Hi! I just got a Ricoh GR IIIx yesterday and saw that it didn't have noise profiles in darktable, so I wound up here.

As the GR IIIx is identical to the GR III except for the lens, would it be possible to re-use the GR III noise profiles for the IIIx?

**Comment by rawfiner** [comment]
@garrett even with identical sensors, cameras may have different noise characteristics depending on firmware: for instance a simple multiplication of all pixel values before encoding the raw changes the observed noise variance in the raw file. I agree that this is unlikely though, but for integration in master I prefer computed profiles.

**Comment by garrett** [comment]
I thought darktable would pick up new profiles if I dropped in a modified copy of the `noiseprofiles.json` file at `~/.config/darktable/noiseprofiles.json` — but it seems that I have to start from the command line with `darktable --noiseprofiles ~/.config/darktable/noiseprofiles.json` to test.

After starting darktable this way, I can confirm that duplicating the GR III and adding an `x` works.

I basically added a comma on the end of the GR III block and added this modified duplicate:

```json
        {
          "comment": "gr iii contributed by marc",
          "model": "GR IIIx",
          "profiles": [
            {"name": "GR IIIx iso 100", "iso": 100, "a": [1.00365826521454e-05, 3.44370802163817e-06, 7.25115016919667e-06], "b": [5.2503144108969e-09, 5.60554920063938e-09, 6.93686234701615e-09]},
            {"name": "GR IIIx iso 125", "iso": 125, "a": [1.26572362423301e-05, 4.33839557743223e-06, 9.18612632078128e-06], "b": [6.81361316023927e-09, 7.69265327867317e-09, 8.80517451239382e-09]},
            {"name": "GR IIIx iso 160", "iso": 160, "a": [1.476350214775e-05, 5.06961952246018e-06, 1.07689162840122e-05], "b": [9.31589475906916e-09, 8.93390762535347e-09, 1.04167295221723e-08]},
            {"name": "GR IIIx iso 200", "iso": 200, "a": [9.33929154304164e-06, 3.20605287980436e-06, 6.79865707853979e-06], "b": [4.19974471170685e-09, 3.6332818537055e-09, 4.71402939827544e-09]},
            {"name": "GR IIIx iso 250", "iso": 250, "a": [1.21033172826306e-05, 4.14823990344946e-06, 8.80858273346715e-06], "b": [5.47207651472969e-09, 5.30187275382553e-09, 6.54953787824239e-09]},
            {"name": "GR IIIx iso 320", "iso": 320, "a": [1.42225459607371e-05, 4.86953374464985e-06, 1.0380478327483e-05], "b": [6.41939111153071e-09, 6.12622427122392e-09, 7.09605129675327e-09]},
            {"name": "GR IIIx iso 400", "iso": 400, "a": [1.75991060073016e-05, 6.02794622555774e-06, 1.28443426770973e-05], "b": [6.68897222879418e-09, 5.70566146136863e-09, 7.32766795220263e-09]},
            {"name": "GR IIIx iso 500", "iso": 500, "a": [2.15096714256684e-05, 7.37250596502542e-06, 1.55909423695428e-05], "b": [8.26410275187522e-09, 6.50537047807452e-09, 9.03979949605015e-09]},
            {"name": "GR IIIx iso 640", "iso": 640, "a": [2.06424144695646e-05, 7.25442902723849e-06, 1.49744030613997e-05], "b": [8.12923750107438e-09, 6.8717203235717e-09, 8.64691393142723e-09]},
            {"name": "GR IIIx iso 800", "iso": 800, "a": [2.34674899130312e-05, 8.35231318398573e-06, 1.69750062786298e-05], "b": [1.11354831061855e-08, 9.42195012864972e-09, 1.1516912352801e-08]},
            {"name": "GR IIIx iso 1000", "iso": 1000, "a": [2.99963360803531e-05, 1.07597018394316e-05, 2.17112405558156e-05], "b": [1.52618790709833e-08, 1.33611803860921e-08, 1.57063872476368e-08]},
            {"name": "GR IIIx iso 1250", "iso": 1250, "a": [2.78516888757355e-05, 1.03107304810413e-05, 1.99613615713613e-05], "b": [1.55037438403576e-08, 1.45488263659681e-08, 1.53317224033671e-08]},
            {"name": "GR IIIx iso 1600", "iso": 1600, "a": [3.90083385662778e-05, 1.42729337859029e-05, 2.81818226449381e-05], "b": [1.91254109822458e-08, 1.74345335550164e-08, 1.95458695048355e-08]},
            {"name": "GR IIIx iso 2000", "iso": 2000, "a": [6.15616693903086e-05, 2.23066895047409e-05, 4.4718974877214e-05], "b": [3.67420709388835e-08, 3.36116044297251e-08, 3.75627016840069e-08]},
            {"name": "GR IIIx iso 2500", "iso": 2500, "a": [5.96876642653198e-05, 2.2246399853489e-05, 4.31588304818676e-05], "b": [3.65389986380307e-08, 3.80476915098169e-08, 3.72323802669692e-08]},
            {"name": "GR IIIx iso 3200", "iso": 3200, "a": [8.43566428553271e-05, 3.11112498670142e-05, 6.11106708217559e-05], "b": [4.51828721255831e-08, 4.57334719712886e-08, 4.73384942510665e-08]},
            {"name": "GR IIIx iso 4000", "iso": 4000, "a": [0.000123465226394369, 4.50224804879424e-05, 8.99518296121445e-05], "b": [6.90064238228634e-08, 6.28996039827954e-08, 7.0103654132744e-08]},
            {"name": "GR IIIx iso 5000", "iso": 5000, "a": [0.000120339122239635, 4.4975442707584e-05, 8.70836729390245e-05], "b": [6.09431393678933e-08, 6.11701688064235e-08, 6.48539294999563e-08]},
            {"name": "GR IIIx iso 6400", "iso": 6400, "a": [0.000161983858615992, 5.98433662723277e-05, 0.000117229375969465], "b": [7.79539265440534e-08, 7.06567989159552e-08, 8.48303350644667e-08]},
            {"name": "GR IIIx iso 8000", "iso": 8000, "a": [0.000271800082969965, 9.97718050249267e-05, 0.000199577896091019], "b": [1.58022565764176e-07, 1.45709582013362e-07, 1.70329147480048e-07]},
            {"name": "GR IIIx iso 10000", "iso": 10000, "a": [0.000256534654895696, 9.73809955750526e-05, 0.000187515489835229], "b": [1.37949427128634e-07, 1.26039759166209e-07, 1.43859701202582e-07]},
            {"name": "GR IIIx iso 12800", "iso": 12800, "a": [0.000369331099108578, 0.000139292069750655, 0.000271397313566927], "b": [2.1664314087006e-07, 1.89685902715031e-07, 2.18980140062726e-07]},
            {"name": "GR IIIx iso 16000", "iso": 16000, "a": [0.000537723006709373, 0.000200792042751034, 0.000396102399426917], "b": [3.54712813391088e-07, 3.3410510967676e-07, 3.96453654094303e-07]},
            {"name": "GR IIIx iso 20000", "iso": 20000, "a": [0.000502912696592536, 0.000193729029213632, 0.000369020193614489], "b": [1.98211891306135e-07, 1.83897331367848e-07, 2.30467218365761e-07]},
            {"name": "GR IIIx iso 25600", "iso": 25600, "a": [0.000637467072278069, 0.000241429173126825, 0.000465466823515056], "b": [3.88300778225257e-07, 4.30869737002231e-07, 5.09692381907661e-07]},
            {"name": "GR IIIx iso 32000", "iso": 32000, "a": [0.00130783749033689, 0.000484554756872053, 0.000951429344321198], "b": [2.96997789909366e-06, 3.92873948045137e-06, 4.0209519433373e-06]},
            {"name": "GR IIIx iso 40000", "iso": 40000, "a": [0.00106436427340426, 0.000399585686285841, 0.000775409891367539], "b": [1.58640114271559e-06, 1.89044706349496e-06, 2.26383483573673e-06]},
            {"name": "GR IIIx iso 51200", "iso": 51200, "a": [0.00141550871663792, 0.000515198796511832, 0.00103466480158499], "b": [7.62249373536607e-06, 8.26163534968433e-06, 9.28133914550195e-06]},
            {"name": "GR IIIx iso 64000", "iso": 64000, "a": [0.00211409585175354, 0.000752409629172512, 0.00155290314809324], "b": [2.1146549336849e-05, 2.41843253390198e-05, 2.48329410682401e-05]},
            {"name": "GR IIIx iso 80000", "iso": 80000, "a": [0.00217627970407667, 0.000812425153789776, 0.00160450996584972], "b": [9.87777779008667e-06, 1.21197008689993e-05, 1.28913629400788e-05]},
            {"name": "GR IIIx iso 102400", "iso": 102400, "a": [0.0033126924242406, 0.00121172764796411, 0.00245364006699033], "b": [3.38905262075178e-05, 4.18506762827909e-05, 4.22266543288332e-05]}
          ]
        }
```

It works as well as the noise profiles for my Fuji X-T2. (That is, it works really well at lower ISOs and still dramatically cleans up chroma noise while leaving some noise at high ISOs.)

**Comment by garrett** [comment]
It took 3 times...

1. First time: I forgot I had highlight priority metering on. :facepalm: (A feature definitely is a bug sometimes.)
2. Second time, I had several (but not all) that weren't overexposed enough.
3. Third time's the charm? Hopefully.

I did see some debug messages; not sure if these are OK:

```
(darktable-cli:200514): Gtk-WARNING **: 23:04:35.209: gtk_disable_setlocale() must be called before gtk_init()
[_dev_auto_apply_presets] missing mandatory module rawprepare for image 1
[_dev_auto_apply_presets] missing mandatory module demosaic for image 1
[_dev_auto_apply_presets] missing mandatory module flip for image 1
[_dev_auto_apply_presets] missing mandatory module gamma for image 1
```

(It happens for each photo.)

And then I got this at the end:

```
===> Prepare final tarball
tar: Substituting `.' for empty member name
tar: : Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

But it did seem to process everything:

[darktable-noiseprofile-20230331.tar.gz](https://github.com/darktable-org/darktable/files/11126933/darktable-noiseprofile-20230331.tar.gz)

[presets.json](https://github.com/darktable-org/darktable/files/11126934/presets.json.txt)

**Comment by garrett** [comment]
(I ran Fedora's packaged version, but inside of a toolbox container, since I'm on Silverblue. It's possible that I might be missing a dependency. But, as it generated those files and had a bunch of nice looking PDFs in the directory, I assume it worked? The generated JPGs are very green however. I guess that's due to sensors having more green photosites and it not doing white balance?)

**Comment by rawfiner** [comment]
> [darktable-noiseprofile-20230331.tar.gz](https://github.com/darktable-org/darktable/files/11126933/darktable-noiseprofile-20230331.tar.gz)

It looks ok for me, it has a more consistent behavior w.r.t. photonstophoto measurements. I will do the PR asap, thanks!

**Comment by garrett** [comment]
@rawfiner: Awesome! Thank you!

Looking forward to be able to use this in darktable directly (without having to specify it on the command line).
