### ISSUE TITLE
Darktable opens .NEF file but the image is all black.  

### ISSUE THREAD

**Issue by JGCerezo** [darktable-org/darktable#13956]
Hi !!
When I want to edit a Nikon .nef file, darktable shows the file but the image is all black.
With other products like Nikon Capture NX-D or Rawtherapee it shows them without problems, but I don't want to use those products.
I would appreciate if you can give me a solution. 
My camera is a bit old, Nikon D50, but it's curious that in other software it doesn't give any problems, but in the software I want to use I can't.

**Screenshots**
![image](https://user-images.githubusercontent.com/128196640/226074723-b86e3ae5-8816-4f88-ba3a-02e95850bb4e.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.2.0 win 64
* OS                :  Windows 11 Home
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by MStraeten** [comment]
Nikon D50 is supported
`<Camera make="NIKON CORPORATION" model="NIKON D50" mode="12bit-compressed">`
maybe you can prove a raw file so someone can try to reproduce it ...

**Comment by victoryforce** [comment]
> With other products like Nikon Capture NX-D or Rawtherapee it shows them without problems, but I don't want to use those products.
> I would appreciate if you can give me a solution.

Since you mentioned Nikon Capture NX-D, my advice (and I'm sure the solution to the problem) would be to not use that program. darktable supports the Nikon D50 and has no problems processing images from this camera (you can check this with a sample from raw.pixls.us). From this it can be concluded that your nef file is corrupted. This is a known issue with Nikon Capture NX-D: https://exiftool.org/forum/index.php?topic=6444.msg32081#msg32081

**Comment by kmilos** [comment]
I'll try master when I get a chance, could be covered by this already: https://discuss.pixls.us/t/very-different-initial-rendering-of-raw-file-possible-corrupt-file-but-renders-ok-in-rt/35297
