### ISSUE TITLE
Sony Alpha 7 IV (ILCE-7M4) noise profiles

### ISSUE THREAD

**Issue by axeleroy** [darktable-org/darktable#13968]
Hello,

I created noise profiles following [Pixl.us's How to create camera noise profiles for darktable](https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/) and I'm pretty happy about it:

[darktable-noiseprofile-20230318.tar.gz](https://github.com/darktable-org/darktable/files/11009807/darktable-noiseprofile-20230318.tar.gz)

**Comment by kmilos** [comment]
Please search before opening new issues, duplicate of https://github.com/darktable-org/darktable/issues/11319

**Comment by axeleroy** [comment]
@kmilos In the issue you linked you said @rawfiner expected someone to redo the noise profiles using Darktable 4.2.1, which I did. Should I have added my profiles to this issue instead of creating a new one?

**Comment by kmilos** [comment]
> Should I have added my profiles to this issue instead of creating a new one?

I think it would have been sensible to do, yes.

**Comment by axeleroy** [comment]
I added the profiles to the linked issue, sorry for the inconvenience.
