### ISSUE TITLE
Sony Lossless Compressed RAW files still not supported - although reported in 4.2.1 release note

### ISSUE THREAD

**Issue by AchimDittrich** [darktable-org/darktable#13973]
Despite the changes that were listed with the darktable 4.2.1 release note

....
Missing Compression Mode Support

    Fujifilm “non-lossless”/lossy
    Nikon high efficiency
    **Sony lossless**
.....

Lossless compressed (L) ARW files are still not supported.

**Comment by kmilos** [comment]
That is what the release notes say - it's missing.

Please stop opening new issues about this.

**Comment by AchimDittrich** [comment]
Sorry for that. I should have read the section in the release note properly but it's also silly to include there what is missing still.

**Comment by kmilos** [comment]
It is not silly. It is to show is a well known issue and to prevent exactly this constant bugging about it.
