### ISSUE TITLE
DB timestamp not updated when importing picture with XMP

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#13975]
Most probably introduced by https://github.com/darktable-org/darktable/pull/13958

To reproduce the regression:

- Ensure that you have "write sidecar file for each image" set to "after edit" & "look for updated XMP files on startup" activated.
- Take 2 images without XMP
- Import them
- Select one and go to darkroom, do an edit (change exposure)
- Quit darktable
- Restart it

And see that the DB timestamp has not been updated with the XMP timestamp.

![image](https://user-images.githubusercontent.com/467069/226189591-a22af4bf-e477-41fb-9ba8-53c1cfaaff76.png)

**Comment by jenshannoschwalm** [comment]
Should be fixed via #13984
