### ISSUE TITLE
[FR]  mask icon in the selective copy and paste windows of the history stack.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#13970]
**Is your feature request related to a problem? Please describe.**

When users spend hours developing a lot of photos, coping and pasting presets most of the time by choosing some of them like color balance rgb among others, have the mask icon too in the selective copy and paste windows will be a game changer.

(And the inclusion too of the dot to be as separator between the module name and the name of the preset).

The other reason would be, that the selective copy and selective paste windows are in the history stack, in the lighttable, if users are developing an image in the darkroom and switch to the lithtable, and the developed image have four or more modules containing masks. for instance four color balance rgb, two with masks and two without masks, it is better to check which one have mask.

**Describe the solution you'd like**

As we now have the amazing possibility to see the preset names in the modules and in the history and in the selective copy and paste windows, and the mask icon also in the modules, this same scheme should be maintained in the select copy and select paste windows of the history stack. Mainly at the point where some users process many images in groups, and are constantly creating masks and presets for all of them.

**screenshots**

![selective copy](https://user-images.githubusercontent.com/67672868/226197915-c13ae6c9-358c-4eee-a774-ac352f2029e2.png)

**Comment by difrkaguilar** [comment]
Mi mistake, in the mockup I gave the same size to the modules name and the presets.

**Comment by TurboGit** [comment]
See #13993 for the bullet.

**Comment by TurboGit** [comment]
@difrkaguilar : Now the PR is having also the mask status.
