### ISSUE TITLE
Remove the "bullet" between module and instance name

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#13989]
I've just started experimenting with current master after a brief hiatus and noticed that a dot/bullet has been introduced between processing module names and their instance name.

Personally I think that this clutters the interface and a space is sufficient to separate module/instance name (as in the current stable version). They are already different font sizes so it should be clear where the module name ends and the instance name begins.

![Screenshot_2023-03-20_20-13-59](https://user-images.githubusercontent.com/9555491/226455155-0fa9d3b2-8c55-4b08-ab4d-da485a03ec30.png)

If there really is massive support for this feature and I can't persuade anyone to revert it, there seems to be a vertical alignment problem with the module name (see above screenshot), which should be resolved (it should be aligned with the bottom of the text not the middle of the box).

darktable 4.3.0+1326~g7db849dd2d

**Comment by elstoc** [comment]
Yes I understood the reason, this has just never been an issue for me, and I prefer without.

**Comment by TurboGit** [comment]
It works probably OK for simple module name, but for `rotate and perspective` or `color balance rgb` it is getting hard to break between the name & label. And of course it all depends on the label, a simple 1 as in your screenshot could looks ok.

BTW, I don't have this alignment issue:

![image](https://user-images.githubusercontent.com/467069/226463627-29748ea7-3073-4003-9d05-895ac6a93331.png)

**Comment by elstoc** [comment]
I assume this change came about because of the auto-preset-renaming (which IMO often results in overly-long-and-complex module headers and I would also prefer to switch off). I've never had an issue with separating module names and instance names before, but then I usually use pretty short (mostly single-word) instance names.

**Comment by Jiyone** [comment]
I also find it better without the dot.
I don’t find the space being an issue at all 🤔

**Comment by difrkaguilar** [comment]
If the bullet/dot is going to be an standard to difference between the name of the module and the given preset name, then must be included in the selective copy and selective paste windows of the history stack too.
I wrote about it in the #13970

**Comment by pehar1** [comment]
I'm clearly voting to keep the bullet.

**Comment by jenshannoschwalm** [comment]
Also a definite vote pro "some sort of delimiter". Nothing better in mind than the bullet ...

**Comment by elstoc** [comment]
Looks like opinion is going against me here, so let's see what might be better (or for me less bad). If the alignment issues can be sorted out, I guess I'd prefer a hyphen or a dash. Perhaps the bullet might work with a bit of extra spacing either side of it.

**Comment by jenshannoschwalm** [comment]
> I guess I'd prefer a hyphen or a dash

1. don't you think a hyphen could be misinterpreted as a minus?
2. a dash might have different vertical alignments, no?

**Comment by TurboGit** [comment]
I had tried a dash or hyphen and found them less readable (the dash in small font is barely visible and not well aligned indeed).

**Comment by elstoc** [comment]
> don't you think a hyphen could be misinterpreted as a minus?

I've never interpreted a dash as a minus within text (only in an obvious equation)

> a dash might have different vertical alignments, no?

No idea, I haven't tested. I guess I'll take @TurboGit's word for it

**Comment by TurboGit** [comment]
I had also tested a vertical bar, and it was too "heavy", standing out too much and make the separation too visible.

**Comment by TurboGit** [comment]
Nothing left on this at this stage.

**Comment by AxelG-DE** [comment]
Sorry I come late to the "party" and I saw, this is deemed as controversial:
Please allow me to add my opinion (dangerous word, I know) as well.
- I am also not happy with that dot, esepecially it is too near to the main module name
- I actually liked the auto-rename as it was in the first incarnation, but now it got smaller, hard for me to read, so I switch off
- I am not so happy that suddenly always-on modules also got auto-renamed, such like "orientation". That renaming is useless
- I would also have liked, just more spacing and no dot, no hyphen no nothing else and the font size as it was

**Comment by pehar1** [comment]
Font size can easily be adjusted to personal taste, I do it via `user.css` (preferences -> general) :
```
#iop-module-name
{
  font-weight: normal;
  font-size: 1em;
  color: @grey_80;
}
```
