### ISSUE TITLE
Konnte Bild nicht laden und wechsel zurück zum Leuchttisch - Fuji XS-10

### ISSUE THREAD

**Issue by mabbi30** [darktable-org/darktable#14005]
Hallo,
ich habe heute Abend ein paar Nachtaufnahmen mit meiner XS-10 gemacht. Diese kann ich auch in Darktable importieren, aber ich kann sie nicht in der Dunkelkammer bearbeiten. 
Fehlermeldung: Konnte Weißabgleichsdaten der Kamera nicht aus xyz.RAF lesen.

Ich habe bei diesen Bildern den Weißabgleich auf 
     „tageshellen“ Neonlights 1 
eingestellt. Es ist das selbe Problem wenn ich "cloudy" wähle.

Grüße
Marc St.

[DSCF0983.zip](https://github.com/darktable-org/darktable/files/11055858/DSCF0983.zip)

**Comment by ralfbrown** [comment]
Diese Fehlermeldung bedeutes ueblicherweise, dass die Kamera nicht voll unterstuetzt ist, oder dass die Datei Fehler enthaelt.

For those who don't speak German, a Fuji X-S10 image is producing an error from rawspeed that the white balance info could not be read.  The camera's white balance is reported to have been set to either Daylight Flourescent or Custom using a daylight flourescent light as the white reference (not sure which way to parse the statement).

My attempt to open the sample image with master yields
```
     2.0459 [rawspeed] (DSCF0983.RAF) rawspeed::FujiDecompressor::FujiDecompressor(const rawspeed::RawImage&, rawspeed::ByteStream), line 72: compressed RAF header check
     2.0460 [libraw_open] extensions whitelist: `cr3'
    21.2030 [temperature] failed to read camera white balance information from `DSCF0983.RAF'!
    22.2224 [temperature] `Fujifilm X-S10' color matrix not found for image
    22.2224 [temperature] failed to read camera white balance information from `DSCF0983.RAF'!
    22.2227 [temperature] failed to read camera white balance information from `DSCF0983.RAF'!
    22.2543 [colorin] could not find requested profile `standard color matrix'!
```
There are entries for the X-S10 in cameras.xml, both compressed and uncompressed.
Exiftool seems to be reading the metadata just fine, including WB values.

**Comment by kmilos** [comment]
Is this perhaps a lossy compressed file? If so, that mode is currently not supported (as clearly listed on the release notes), please try lossless or uncompressed.

**Comment by mabbi30** [comment]
Oh thank you! I thought I'd changed the setting to lossless compression.
Thanks for the tip and the quick help.
