### ISSUE TITLE
JPG module order is not used by default when editing a JPG...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#14023]
When I open a new jpg the default module order is always raw not the jpg mode.

This has always been the case as far as I know...

I am not on the most recent build but fairly recent on windows... 4.3.0+1286~geb03c2eb62

I can find no way to set this via an auto preset as this dropdown does not have that option and the manual states that it is the default setting for non-raw images so I would expect that when you open a jpg that this would be the default module order??

I quote. 

"v3.0 JPEG
This is the default module order for JPEG development."

So a correction in the behaviour or the manual is needed to rectify this.

Unless I am missing something.... Sorry for the noise if this has been previously discussed

**Comment by TurboGit** [comment]
Fixed, closing.
