### ISSUE TITLE
Add option to keep XMP files in a special directory

### ISSUE THREAD

**Issue by vitonsky** [darktable-org/darktable#14022]
When i edit my raw files, darktable create a lot of XMP files (by one for each RAW file). I like that darktable remember my changes, but it's break my workflow with photos, because i have to remove XMP files after end of retouching. Due to this problem i try to avoid a use darktable for now.

It would be useful to introduce an option to save XMP files to a some subdirectory (like .DARKTABLE) or even in a home directory.

I've explore settings and i cannot find such option.

![image](https://user-images.githubusercontent.com/86191922/227741475-4bd8061a-23e4-43d4-9195-a2b09546e8de.png)

**Comment by ptilopteri** [comment]
hamburger (config) -> storage -> XMP
write side car for each image, choose 'NEVER'

if this satisfys, please close this issue

**Comment by vitonsky** [comment]
@ptilopteri did you seen my screenshot? I've choose this option there. It is not solve my problem, because it disable XMP files, so changes do not save for RAW files after close program.

I want to Darktable remember my changes for each file, but do not create XMP files beside a RAW files

**Comment by vitonsky** [comment]
@victoryforce if it works like that, my problem solved.

I suggest to add description what XMP files is in a related section

**Comment by EC1000** [comment]
https://docs.darktable.org/usermanual/4.2/en/overview/sidecar-files/sidecar/ and https://docs.darktable.org/usermanual/4.0/en/preferences-settings/storage/

**Comment by vitonsky** [comment]
@EC1000 i'm not about docs, i'm about UI. You can add description under section "XMP" in settings, you can add link to a docs.

My user feedback is: i don't understand what XMP is and how it works
It's very good that darktable have docs page, but it's not enough to solve my problem, because as user i will never read it to understand basic functional, it's because i no have time to read docs site for each program that i use.

Now, i'm understand how it works, thanks to @victoryforce for it. But another users will not, so you will receive a new issues like this and you will spend your time to explain us how your program works.

Don't wast your time and lifetime of your users - improve UI of your product, add short description (and maybe a link to docs) right on config window.

**Comment by ptilopteri** [comment]
remember that just because you were unfamiliar or just unable to understand the workings does not mean that others can not.  most should be able to if I could (very old and forgetful).  
:))

**Comment by vitonsky** [comment]
I'm the user, i give you my feedback to improve UX. If users feedback does not affect on product quality improvement, so why issues are opened then? It's shortsighted to ignore a feedback with assumption "it's probably ok for others users" by many reasons.

**Comment by gi-man** [comment]
To me XMP is not really the backup, the database is the backup. It is a side car and it is used by other software too (eg. Digikam). It could contain tags, rating, copyright info, and processing info.

I don't think the UI needs improvement. It allows you to turn the feature off, but it won't explain you every detail.

**Comment by vitonsky** [comment]
@gi-man 
> It allows you to turn the feature off, but it won't explain you every detail.

It is sad to see such reasoning about product quality. With such vision no have chances to make Darktable a mainstream application, it will never be used by people who seen quality software at least once in life.

Let's see what's decision will make a main contributors who invest their time to a develop product and would take they such perspectives

**Comment by Nilvus** [comment]
Keep cool guys. Maybe tooltip could be improved.

@vitonsky: you put your view on the UI and that part, consider that others users or developers have the same right, even if they disagree with you.

Improving an UI is not also adding this, sometimes it could be the opposite and it's always good to find something balanced between having infos (regarding how the options could be easily understood by users) and not having too much (this would overload the UI).
And that is hard to do. It's just impossible to please everybody. And remember that from some thing at least, improving is subjective.

But, do you point on the menu where you have "never" setting? You will see a tooltip. I think the best thing would be that you propose a way to improve it (i do not say to propose code, just propose the amended text here). Try to not add too much infos, finding something balanced with something clear but not too long. If your text is ok, I could spent time to add it.

**Comment by jenshannoschwalm** [comment]
I looked up the tooltip right now
![grafik](https://user-images.githubusercontent.com/50982232/227762336-9cb87908-ad39-4fd7-87aa-263c97c4d03f.png)

Please suggest what could be improved here.



> It would be useful to introduce an option to save XMP files to a some subdirectory (like .DARKTABLE) or even in a home directory.

This idea or similars have been asked a lot of times. For many reasons - technical and per software design - this will not be done because ofter a lot of workflow analysis it might help a few but will be really bad & unsafe for most users workflows. Just the main idea: By keeping the sidecar "close" to the raw file we can always remove and reimport images whenever we want to and can be sure our work is not lost.

**Comment by MStraeten** [comment]
> It is sad to see such reasoning about product quality. With such vision no have chances to make Darktable a mainstream application, it will never be used by people who seen quality software at least once in life.

how much did you pay to be able to use darktable? 
So why should darktable try to be an mainstream application - there are plenty of mainstream applications around so it doesn't need a further one.

> because as user i will never read it to understand basic functional

darktable adresses stuff most mainstream applications doesn't give you control to it. To be able to make use of that control you need to understand basic stuff. the community is also very helpful to help you understanding stuff. If you don't want to do it, you're wasting time using darktable ...

**Comment by vitonsky** [comment]
@Nilvus @jenshannoschwalm current text in a tooltip are confuse me, it is not clear how XMP files works, it looks that Darktable will not remember my changes after close program, if i will pick option "never". I suggest to explain that it is not that and darktable will keep changes in own DB even if i choose option "never".

If you have docs about it, you could add a link to a UI if you want.

**Comment by vitonsky** [comment]
@MStraeten if you don't want to contribute, don't do it, only you decide it.

Your reasoning are show me that you not a UX specialist and you are not ready to discuss to get known about principles of good and smooth UX. When you will be ready in next time - start discuss with no complaints as you did and do not continue with shame users for they don't know some specific of your product, instead try to get known how you can help users to use your software efficient.

**Comment by jenshannoschwalm** [comment]
@vitonsky just stay relaxed :-) no reason to get into close-to-insulting mode.

The points here are
1. "How much general information should be included in a tooltip" for users not willing to have a look into the manual? This is a very difficult problem - there is absolutely **no** software that can go without reading the f manual.
2. Can we improve UI by adding more links to online docs?

**Comment by vitonsky** [comment]
@jenshannoschwalm 

1. We have to mention that non destructive changes will saved even with no XMP files. It is important context for the option, it's key to understand how Darktable storage works.

I do not to suggest delete a manual, but a good UX mean a product must be self sufficient and explain terms in place.

You still may go users to a manuals to explain some concepts.

Look at example, this is a settings page of [Linguist browser extension](https://github.com/translate-tools/linguist)

![image](https://user-images.githubusercontent.com/86191922/227765690-61680f7e-276d-4372-9e26-d99f8e7acdb1.png)

Most important information with explaining are included, but also used links to docs to explain a big concepts.

2. It's probably question for maintainers of Darktable, but generally it looks that enough just a short mention about preserving changes even with disabled XMP files

**Comment by Nilvus** [comment]
> I do not to suggest delete a manual, but a good UX mean a product must be self sufficient and explain terms in place.

It's right and wrong. All software that brings a lot of features can't explain all things clearly and make it sufficient. Even Lightroom do not do it and that's why it have a manual, many books and magazines, tutorials and so on, to helps users.

> You still may go users to a manuals to explain some concepts.
> 
> Look at example, this is a settings page of [Linguist browser extension](https://github.com/translate-tools/linguist)

And your example add a text to after click on a button, to then add a text to link to the documentation. Not better to me!
A good UX, as I also said, is also about not overload UI.

Thus, you add a heart on my previous comment but I don't see anything about it on your 3 following comments. Be constructive, as I've explain, the best and more constructive way would be to propose here an amended tooltip on what now you know about that. All your comments here do not any useful and constructive comments to go forward.

Last thing, this setting is there since years and you're the first (as far as I know) that complains about that.

**Comment by vitonsky** [comment]
@Nilvus solution i suggested above:

comment https://github.com/darktable-org/darktable/issues/14022#issuecomment-1484038420
> We have to mention that non destructive changes will saved even with no XMP files

comment https://github.com/darktable-org/darktable/issues/14022#issuecomment-1484027658
> I suggest to explain that it is not that and darktable will keep changes in own DB even if i choose option "never".

You may add a mention to a exists tooltip or under "XMP" section as secondary text

---

To clarify how documentation works, you can read a https://documentation.divio.com/
The things you mentioned above is a "tutorials" and "how to guides", i told you about "explanation"

**Comment by Nilvus** [comment]
Is it hard to write the complete tooltip with amended text? I'm ok to help, no to do what you want when it's as simple as writing text (what I ask but you seem to not want to do it). Read again my comments. I will not go forward without that. Maybe I lost my time?!

**Comment by Nilvus** [comment]
> To clarify how documentation works, you can read a https://documentation.divio.com/
> The things you mentioned above is a "tutorials" and "how to guides", i told you about "explanation"

Oh, and I know the difference. But seems that you consider what you want...

**Comment by vitonsky** [comment]
If you want to i write text for tooltip, i can't because i don't know how it actually works.
You can call me to i review a texts variants

**Comment by TurboGit** [comment]
> If you want to i write text for tooltip, i can't because i don't know how it actually works.

You said that the tooltip is not OK and now that you don't actually know how it works.

The devs said that the tooltip is there and that it provides the needed information.

Don't you see the dead-end there?

**Comment by Nilvus** [comment]
> If you want to i write text for tooltip, i can't because i don't know how it actually works. You can call me to i review a texts variants

I post again what I suggested on my first comment the one you put an heart on (to try to be constructive and by considering that your probably not know darktable code...):

> **I think the best thing would be that you propose a way to improve it (i do not say to propose code, just propose the amended text here).**

It's not clear? You don't know how to write text **here**? Where I have ask you to change code? I've seen many comments from you and you don't know how to write the text of the tooltip **here**?

Please help us to help you (that"s the opposite you do by now by just arguing again and again). I hope to see now improved tooltip text you suggest to add **here**. If it's ok, I will add it, if it's not, we will see if it can easily be improved (or not).

I tried to be constructive and help here and all your comments were against that, absolutely not constructive and time lost. Especially regarding something as simple as writing a text in a comment. So if I do not see any tooltip on next comment, sorry but I will just close that issue.

**Comment by vitonsky** [comment]
@TurboGit i see that we have important UX problem that easy to fix, but some contributors just wast my time and bloat the discussion.

I see the problem:
> current text in a tooltip are confuse me, it is not clear how XMP files works, it looks that Darktable will not remember my changes after close program, if i will pick option "never"

I suggest solution:
> We have to mention that non destructive changes will saved even with no XMP files

Just go fix it. I can't write a text for a tooltip, because i don't know how Darktable works and what wording i should use for the text. I'm not in a context, let's some Darktable developer will suggest variants and we will review it.
