### ISSUE TITLE
Maker+model matching doesn't work for noise profile preset

### ISSUE THREAD

**Issue by patrikf** [darktable-org/darktable#14029]
The noise profile presets seem to typically not include the maker in the model name. When generating a noise profile for my `Canon EOS R6m2` with `darktable-gen-noiseprofile` (built from git master), I get:
```
  "noiseprofiles": [
    {
      "maker": "Canon",
      "models": [
        {
          "comment": "eos r6m2 contributed by patrikf",
          "model": "EOS R6m2",
          "profiles": [...]
        }
      ]
    }
```

I didn't seem to get `--noiseprofiles` to work, so I manually added the profile to `/opt/darktable/share/darktable/noiseprofiles.json`.

However, the noise profile never matches.

In EXIF data, the model is not `EOS R6m2`, but `Canon EOS R6m2`:
```
% exiftool ~/pics/230326\ Denoise/attempt2/IMG_3216.CR3 | egrep 'Make|Model'
Make                            : Canon
Camera Model Name               : Canon EOS R6m2
Canon Model ID                  : Unknown (0x80000481)
```

This is also what darktable sees as "model" -- I confirmed this with `darktable -d control` and by adding a log statement:
```
diff --git a/src/common/noiseprofiles.c b/src/common/noiseprofiles.c
index 71db1d2..5a81a93 100644
--- a/src/common/noiseprofiles.c
+++ b/src/common/noiseprofiles.c
@@ -264,6 +264,7 @@ GList *dt_noiseprofile_get_matching(const dt_image_t *cimg)
 
         json_reader_read_member(reader, "model");
 
+        dt_print(DT_DEBUG_CONTROL, "[noiseprofile] %s = %s?\n", cimg->camera_model, json_reader_get_string_value(reader));
         if(!g_strcmp0(cimg->camera_model, json_reader_get_string_value(reader)))
         {
           dt_print(DT_DEBUG_CONTROL, "[noiseprofile] found %s\n", cimg->camera_model);
```
```
     3.3540 [noiseprofile] found `Canon' as `Canon'
     3.3540 [noiseprofile] found 86 models
     3.3540 [noiseprofile] Canon EOS R6m2 = EOS R6m2?     <-- this should match!
     3.3540 [noiseprofile] Canon EOS R6m2 = EOS-1Ds?
     3.3540 [noiseprofile] Canon EOS R6m2 = PowerShot S100?
...
```

So it seems there is disagreement whether the maker is part of the model between the presets/preset generation, and darktable when trying to match the presets.

**Comment by patrikf** [comment]
I found `get_image_camera_model` in `tools/noise/subr.sh`, and some old commits:
* https://github.com/darktable-org/darktable/commit/f957f128591d91f0a497fa18977bfa0e8f105f95
* https://github.com/darktable-org/darktable/commit/8aae2406d14bccdcd797df05cb50e60f6441a1e5

I guess "known" cameras get remapped through https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml .

**Comment by kmilos** [comment]
Yeah, it's a known issue, with no obvious fix at the moment...

See also https://github.com/darktable-org/darktable

**Comment by patrikf** [comment]
As I understand `darktable-gen-noiseprofile` already uses `darktable-cli`. Maybe a simple fix would be for darktable(-cli) to dump what it thinks is the model/make of a RAW file, and use that instead of exiv2. Not sure if worth the effort.

The issue in itself is a smaller deal than how hard it was to find out what's wrong :)
