### ISSUE TITLE
regressions on the testsuite

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14030]
After merging some changes today the testsuite has many failures.

The culprit is.

```
commit 6c4020b9b5be44d91e03ec812f2fadfe7a26bb26
Author: hanno@schwalm-bremen.de <hanno@schwalm-bremen.de>
Date:   Sat Mar 25 17:31:13 2023 +0100

    Avoid possible Nans with ordinary clip highlights

 data/kernels/basic.cl |  3 ++-
 src/iop/highlights.c  | 29 ++++++-----------------------
 2 files changed, 8 insertions(+), 24 deletions(-)
```

Many tests are failing, all 013* for example and:
   - 0080-toneequal-eigf
   - 0081-mask-groups
   - 0084-cacorrect
   - 0087-blendif-and-or
   - 0088-blendif-diff-excl

The affected areas are mostly (always?) blacks.

The diff for 0130-toneeq-HSL-lightness is:

![diff](https://user-images.githubusercontent.com/467069/227795013-3b19f84b-3e00-4a28-b9bd-90e269b38fe3.png)

**Comment by jenshannoschwalm** [comment]
Will fix asap

**Comment by TurboGit** [comment]
For the record, the full list is:

   - 0000-nop
   - 0001-exposure
   - 0002-local-contrast
   - 0003-denoise-bilateral
   - 0004-masks
   - 0005-orientation-minus-90
   - 0006-orientation-plus-90
   - 0007-orientation-180
   - 0008-flip-h
   - 0009-flip-v
   - 0010-flip-hv
   - 0011-gdnd-90
   - 0012-gdnd-45
   - 0013-denoiseprofile-wavelets
   - 0014-filmic-rgb
   - 0015-shadhi-bilateral
   - 0016-lowpass-bilateral
   - 0018-perspective-corr
   - 0019-color-mapping
   - 0020-denoise-nlmeans
   - 0021-retouch-wavelets
   - 0022-color-zones
   - 0023-channelmixer
   - 0024-contrast-equalizer
   - 0025-exposure-guided-filter
   - 0026-haze-removal
   - 0027-denoiseprofile-nlmeans
   - 0028-highpass-overlay
   - 0029-color-correction
   - 0030-framing
   - 0031-globaltonemap-drago
   - 0032-watermark
   - 0033-blending-modes-uniform
   - 0034-blending-modes-parametric
   - 0035-multiple-modules
   - 0036-liquify
   - 0038-colorcontrast
   - 0040-fill-light
   - 0041-localtonemap
   - 0042-zonesystem
   - 0044-dithering-random
   - 0045-vignetting
   - 0046-demosaic-greens
   - 0047-demosaic-amaze
   - 0048-demosaic-vng
   - 0050-bloom
   - 0051-soften
   - 0052-color-reconstruction
   - 0053-levels
   - 0054-rgblevels-linked
   - 0055-rgblevels-indep
   - 0056-vibrance
   - 0058-defringe
   - 0059-grain
   - 0060-rgbcurve-indep
   - 0061-lowlight
   - 0062-splittoning
   - 0063-velvia
   - 0067-demosaic-fdc
   - 0069-tonecurve-rgb-linked
   - 0070-tonecurve-xyz-linked
   - 0071-tonecurve-lab-linked
   - 0072-tonecurve-lab-indep
   - 0073-spot-removal
   - 0074-retouch-clone
   - 0075-retouch-heal
   - 0076-retouch-blur-fill
   - 0077-croprotate-keystone
   - 0078-basecurve-fusion
   - 0079-toneequal-gf
   - 0080-toneequal-eigf
   - 0081-mask-groups
   - 0084-cacorrect
   - 0087-blendif-and-or
   - 0088-blendif-diff-excl
   - 0103-almost-all
   - 0104-legacy-filmic
   - 0110-perspective-bilinear
   - 0111-perspective-lanczos2
   - 0112-perspective-lanczos3
   - 0113-resample-bilinear
   - 0114-resample-bicubic
   - 0115-resample-lanczos2
   - 0116-blending-rgb-display-1
   - 0117-blending-rgb-display-2
   - 0118-blending-rgb-display-3
   - 0119-blending-rgb-scene-1
   - 0120-blending-rgb-scene-2
   - 0121-blending-rgb-scene-3
   - 0129-toneeq-RGB-average
   - 0130-toneeq-HSL-lightness
   - 0131-toneeq-RGB-max
   - 0132-toneeq-RGB-sum
   - 0133-toneeq-power
   - 0134-toneeq-geomean
   - 0135-negadoctor

**Comment by TurboGit** [comment]
Just to confirm that all the tests are OK now. Thanks for the quick fix @jenshannoschwalm.
