### ISSUE TITLE
Cannot force deletion from database if local copy is created

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#14043]
**Describe the bug/issue**
Unable to force deletion from the database if `copy locally` and original files moved. 

Error:
```
darktable cannot remove local copy when the original file is not accessible.
```

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Select all
2. Sync local
3. Delete original files
4. Delete images from database
5. See error

**Expected behavior**
Delete from database.

**Screenshots**
<img width="497" alt="image" src="https://user-images.githubusercontent.com/58240560/227984086-d485f547-c259-4bd5-a806-5389516ec94a.png">

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 4.2.1
* OS                : MacOS 13.2.1 (22D68)
* Linux - Distro    : e.g. Ubuntu 18.4

**Comment by TurboGit** [comment]
That's expected and a feature. What would you like dt to do?

**Comment by naisanzaa** [comment]
To clear out all references to those images from the database, clear it from any caches.
