### ISSUE TITLE
contrast equalizer makes dt 4.2.1 crashed

### ISSUE THREAD

**Issue by yandewish** [darktable-org/darktable#14040]
**Did you buy darktable from an application store ?**
download from darktable.org

**Describe the bug/issue**
When I export, dt crash!

**To Reproduce**
1. open a Canon EOS 70D raw image in darkroom.
2. enable contrast equalizer module.
3. all default settings, do nothing else! just click export and wait seconds, it crash!
I have tried times, Nikon D200 NEF and Pentax K-1 JPEG files all work well.

**Platform**
MacBook Pro (Retina, 15-inch, Mid 2015)
2.2 GHz, Quad-Core Intel Core i7, 16GB RAM
macOS Catalina 10.15.7
darktable version : 4.2.1

** other information **
system report : https://drive.google.com/file/d/1k2mpTZb7EXmTtMjGUd4BARHu6FUYtJ6H/view?usp=sharing
raw image: https://drive.google.com/file/d/1EtWbeUYcLLbGXklFwU9-lGS4KP3l86oF/view?usp=sharing
xmp file: https://drive.google.com/file/d/1DJj3IDEg55srgmZxx9ZdHtBKqFq0xsB-/view?usp=sharing

**Comment by ralfbrown** [comment]
@yandewish Is this still happening in 4.4.2?  Lots of code changes and fixes since 4.2.1....

**Comment by MStraeten** [comment]
> @yandewish Is this still happening in 4.4.2? Lots of code changes and fixes since 4.2.1....

4.4.2 doesn’t support macOS 10.15.7 officially (so there’s no release build here)
But there’s an unofficial one: https://discuss.pixls.us/t/macos-10-14-darktable-4-4-x-release-build/38316/3

**Comment by Nilvus** [comment]
As we don't have answer and it's probably fixed. I close. @yandewish: if you still have crash with last darktable version, you could ask to reopen.
