### ISSUE TITLE
Darkroom: Middle mouse button zoom level

### ISSUE THREAD

**Issue by jmoric** [darktable-org/darktable#14046]
First of all... Awesome program. Thanks devs.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated with the way the middle mouse button cycle through zoom levels.
First 100% then 200% and back to FIT. When zoomed out (< FIT screen)  it cycle through the 100% 200% thing again. 

I have changed the source code in my personal build to fit my needs but I would love to see an option to disable this behavior built in to only switch between 100% and FIT screen. If we need more than 100% zoom we can always use the ctrl key and the mouse wheel to do that.

I personally never want to zoom to more than 100% in darktable.

**Describe the solution you'd like**
I have this "dirty" hack in my personal build but you can of course implement it any way you see fit.

***FILE: darktable/src/views/darkroom.c:
FUNCTION: button_pressed(...)
LINE START: 3614***
```C
const gboolean cycle_zoom_200 = dt_conf_get_bool("darkroom/mouse/middle_button_cycle_zoom_to_200_percent");

if((tscale > 0.95f) && (tscale < 1.05f) && cycle_zoom_200) // we are at 100% and switch to 200%
{
  zoom = DT_ZOOM_1;
  scale = dt_dev_get_zoom_scale(dev, DT_ZOOM_1, 1.0, 0);
  if(low_ppd) closeup = 1;
}
else if(((tscale > 1.95f) && (tscale < 2.05f) && cycle_zoom_200) // Reset zoom switch to zoomfit
        || (zoom != DT_ZOOM_FIT && !cycle_zoom_200))
{
  zoom = DT_ZOOM_FIT;
  scale = dt_dev_get_zoom_scale(dev, DT_ZOOM_FIT, 1.0, 0);
}
else // other than 100 or 200% so zoom to 100 %
{
  if(low_ppd)
  {
      zoom = DT_ZOOM_1;
      scale = dt_dev_get_zoom_scale(dev, DT_ZOOM_1, 1.0, 0);
  }
  else
  {
    zoom = DT_ZOOM_FREE;
    scale = 1.0f / ppd;
  }
}
```
Happy coding from Denmark.

**Comment by TurboGit** [comment]
I have always been annoyed by this too so I'll certainly vote for something like this. I also need only FIT <-> 100% in most cases.

**Comment by dterrahe** [comment]
Counterargument; people don't like having to use two hands all the time to reach for the ctrl key. If I just want to switch between fit-100 with only the mouse, I can already do this with a quick flick up or down on the scroll wheel. However to get to something between 100-200, I can now press middle to get to 200 and then scroll back down. If you do this, could I suggest moving the upper limit for a scroll zoom from 100 to 200. I have never felt a warm and fuzzy feeling when "protected" from accidentally zooming too much and having to use the ctrl key (...or pressing the middle mouse button...)

So effectively what I'm suggesting is to move the "100%" protection from scroll to middle click. Everybody Happy!
(Of course I haven't experimented with this, so Everybody Miserable! is also a realistic outcome)

**Comment by wpferguson** [comment]
Personally I like the middle click zoom the way it is, and I use it a lot.  But, I would be okay with scrolling to 200% instead of just 100% zoom too.

**Comment by jmoric** [comment]
The code I posted above do support the default behavior as is in darktable now and the option to only zoom to 100%. That way we can decide ourself.  In my view the question is whether it should be a selectable option in the settings dialog or just an option in the configuration file.

@dterrahe @wpferguson 
The scroll wheel behavior is in another function. I haven't looked deeply into it, but on the surface the code looks a little bit messy and not that well documented. But that could just be me…

**Comment by jmoric** [comment]
I have looked into the scroll wheel zoom behavior when not using the ctrl key.

It looks like the behavior is controlled by the this line of code:

***FILE: src/views/darkroom.c
FUNCTION: scrolled(...)
LINE: 3709***
```C
const gboolean constrained = !dt_modifier_is(state, GDK_CONTROL_MASK);
```
By just looking at the code it should be fairly easy to change the scroll wheel behavior. 
The question is: Should the max zoom level be changed or should the use of the ctrl key be deleted.

**Comment by TurboGit** [comment]
@wpferguson : 

I'm proposing this:

- `middle click` **FIT** -> **100%**
- `ctrl + middle click` **100%** -> **200%**
- When at **100%** or **200%** a `middle click` goes to **FIT**

What I find good here is that since to have 200% you need to press ctrl, then you're ready to go further as ctrl is needed to go above 200%.

Maybe we can even remove the preference with this new behavior?

What do you think?

**Comment by jmoric** [comment]
Yes, that's sounds good to me and maybe also extend the zoom level to 200% and <100% for the `scroll wheel` without a modifier key `(ctrl+)`

That I think would be a nice interface interaction behavior.

**Comment by dterrahe** [comment]
> When at 100% or 200% a middle click goes to FIT

Do you mean middle and ctrl-middle?
That would exclude the possibility of toggling between 100 and 200? You haven't listed all possibilities, so not sure what would happen if at 50% and pressing either middle or ctrl-middle.

I would propose:
Middle; if 100% -> fit, otherwise 100%
Ctrl-middle; if 200% -> fit, otherwise 200%
So you can toggle 100% <-> 200% with middle, Ctrl-middle, middle etc

**Comment by wpferguson** [comment]
Last night I spent several hours editing portraits.  I clicked up to 200% 50 to 60 times to retouch skin, refine masks, etc.  I went up to 400% maybe 5 times.  So, for me the use of the control key is in the right place, being used to access a lesser used function (zoom 400%+).  

Restricting the middle click to `fit<->100` would require me to use both hands, a key press and a click to accomplish something that I now do with one hand and at most a double click.  I could live with letting the scroll go to 200% without requiring the control key, so I could still get to 200% zoom with one hand and just a little more finger movement.

**Comment by TurboGit** [comment]
@jmoric : I suppose that the behavior I have been describing should be only done when the preference is set. So we keep the preference and activated by default (no change with current master). When preference is not activated we do as proposed by @dterrahe which seems more versatile than my proposal.

**Comment by jmoric** [comment]
@TurboGit : Affirm. That's how I understand it too. I'm quite busy, so I'll look into it tomorrow.

**Comment by jmoric** [comment]
I have implemented the zoom behavior as @dterrahe proposed with one addition:
   * Middle: if < fit or > fit and < 100% then fit.
