### ISSUE TITLE
Image replaced for black using the sliders and channel data in masks

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#14058]
**Describe the bug/issue**
Image replaced for black using the sliders and channel data in masks (just tested in exposure and color balance rgb modules, but maybe in other modules it happens too).

**To Reproduce**
Select any image in the lighttable and jump to the darkroom.
1. Go to color balance rgb module.
2. Click on parametric mask or draw and parametric mask icons.
4. Click on "Cz" icon and press "c" to visualize the channel data. 
5. Move the sliders forward and backward.
6. See error.

**Expected behavior**
Using "c" as a shortcut to display the channel data and the sliders to adjust the masks should work fine as usual.

**Screenshots**
This are the processing parameters.

![Screenshot from 2023-03-28 21-09-32](https://user-images.githubusercontent.com/67672868/228400698-71ade539-bb38-40d5-9b47-f060c22b6e36.png)

**Screencast**

https://user-images.githubusercontent.com/67672868/228400449-8dd8b560-17de-4e6b-9835-43dbabdde706.mp4

**Which commit introduced the error**
No idea

**Platform**

darktable version : 4.3.0~git1471.0d4dca91-9596.1
OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.2.7-200.fc37.x86_64
Uptime: 12 hours, 56 mins
Packages: 2149 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.3
WM: Mutter
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark [GTK2/3]
Icons: Mkos-Big-Sur[GTK2/3]
Terminal: alacritty
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 6506MiB / 32016MiB
Graphics driver: 530.41.03
OpenCL installed: Yes
OpenCL activated: Yes
Xorg: Yes

**Additional context**
** Tested as root with a new install and saw the same issue**
 - Can you reproduce with a RAW or Jpeg or both?  **both**
 - Do you use lua scripts? **Yes**
 - What lua scripts start automatically? **Yes**

**Comment by ralfbrown** [comment]
Partially confirmed in current master (+1477).  The display doesn't turn black, it goes to an odd-looking grayscale instead of the magenta-scale usually used for the chroma channel display.

I'm guessing race condition, as it doesn't happen when moving the slider one click at a time, only when dragging it fast enough that the "working" message becomes continuous.

**Comment by jenshannoschwalm** [comment]
Should be fixed in master

**Comment by difrkaguilar** [comment]
Thanks a lot to all you for creating and improving this amazing software!!!!!!!
