### ISSUE TITLE
OpenCL issues /darktable does not start with latest AMD opencl drivers

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#14061]
This might be for @jenshannoschwalm Maybe you understand if this is something that can be fixed within darktable or is again AMD screwing the drivers. Debug output can be found here: https://pastebin.com/Ax3eBbaE

**Platform**

* darktable version : 4.3.0+1477~gc1951a4fee
* OS                :  6.2.8-arch1-1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux
* Linux - Distro    : Arch Linux
* Memory            : 32 GB
* Graphics card     :  Radeon RX 580
* Graphics driver   :  radeon
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : Wayland
* Desktop           : Gnome 
* GTK+              : 3.24.37
* gcc               : 10.3.0
* CMAKE_BUILD_TYPE  : Release

**Comment by pitbuster** [comment]
Maybe it is related to this: https://bbs.archlinux.org/viewtopic.php?id=284463

**Comment by piratenpanda** [comment]
intel-oneapi-compiler-shared-opencl-cpu is not installed on my system and the bug is directly related to which opencl-amd package I install. So unfortunately that's not the problem

**Comment by jenshannoschwalm** [comment]
@piratenpanda you know how much i love the amd opencl peculiarities ? :-)

Your log might indicate to a broken library pointer.

Did you try to remove all opencl kernels and start dt with `-d opencl -d verbose`? that should give you more clues ...

**Comment by piratenpanda** [comment]
Will try tonight. And it's always a pleasure to help you having fun ;)

**Comment by piratenpanda** [comment]
I deleted kernels in ~/.cache and ran with verbose: https://pastebin.com/5LZWgy2F

**Comment by jenshannoschwalm** [comment]
That looks like a library init error. Might be the installation

**Comment by jenshannoschwalm** [comment]
@piratenpanda right now some "stability" commits have been merged. Would appreciate if you could
1. test your system with `clinfo` and report the log
2. try with current master using `-d opencl -d -verbose`

**Comment by piratenpanda** [comment]
Will do on monday. Thanks for your effort!

**Comment by piratenpanda** [comment]
Output: https://pastebin.com/Wd2dM8vi

But I found another pkgbuild in the Arch AUR which seems to work. So maybe its a packaging issue after all

**Comment by jenshannoschwalm** [comment]
Does clinfo work using the "buggy" driver?

**Comment by piratenpanda** [comment]
It does

**Comment by jenshannoschwalm** [comment]
could you share the output ?

**Comment by piratenpanda** [comment]
Here you go https://pastebin.com/7tc4UW4e

**Comment by jenshannoschwalm** [comment]
Thanks - very interesting. On some reason the platform check crashes.

**Comment by jenshannoschwalm** [comment]
Could you test the PR ?

**Comment by piratenpanda** [comment]
Will test tonight

**Comment by piratenpanda** [comment]
Unfortunately still nope https://pastebin.com/L2t7DXKX

**Comment by jenshannoschwalm** [comment]
@piratenpanda there has been some work on cl related issues that could help here. Could you test on latest master ?

**Comment by piratenpanda** [comment]
No changes unfortunately. But I think the problem is not on the darktable side

**Comment by piratenpanda** [comment]
After installing the latest drivers and setting "sudo echo   'ROC_ENABLE_PRE_VEGA=1' >> /etc/environment" it works just fine

**Comment by jenshannoschwalm** [comment]
This AMD OpenCL driver stuff is really an annoying mess!

Do **YOU** see a chance to sum up your understanding of these issues and maybe write a summary for the manual?

**Comment by piratenpanda** [comment]
I could try

**Comment by piratenpanda** [comment]
I also had a new issue that the image showed this when zooming but now I can't reproduce. Also could not identify the module causing it:
![Eingefügtes Bild](https://github.com/darktable-org/darktable/assets/920721/70995f1d-614b-4117-8ca7-59edc99771e2)
