### ISSUE TITLE
[FR] An efficient method for making large changes to brush size

### ISSUE THREAD

**Issue by ig9000** [darktable-org/darktable#14079]
**Is your feature request related to a problem? Please describe.**

Recently I've been using the brush to paint masks more often, and especially in more cases where the brush size needs to be changed over a large range. There doesn't seem to be an efficient way to do this, necessitating a ridiculous amount of scroll-wheel actuation.

**Describe the solution you'd like**

For my purposes, it would be enough to be able to create a shortcut which directly changed the size in larger increments than the scroll-wheel. (I thought this might be possible already, but doesn't seem to be, unless I'm missing something). A "modifier" shortcut which increased the increment of the scroll-wheel itself would also solve the problem.

**Alternatives**

The most complete solution would be to add a slider for brush size to the drawn mask control set, which could then be accessed in all the currently available ways, but I can understand that adding another slider to an already busy set might not please everyone.

**Additional context**

IIRC before the shortcut system overhaul, when there were default shortcuts for brush size (square bracket keys), holding those keys would continuously change the size until released. Shortcuts created for this now don't have this behavior, but I'm not sure it was the best way to solve this problem, so I'm not specifically requesting that.

**Comment by dterrahe** [comment]
There's a collapsible/expandible section in the mask manager module with sliders for shape parameters.

**Comment by ig9000** [comment]
That's what I was missing, thanks! It didn't occur to me to look in that module in the shortcuts editor, either. Mapping keys to that size slider solves my problem, so I'll close this issue, Unfortunately, using a "show control" shortcut for this interacts awkwardly with the pointer when there's a brush activated, but I'm not sure how that could be improved.

**Comment by ig9000** [comment]
@dterrahe So, now using keybindings with the size slider in the mask manager, I'm able to increase the shortcut speed setting to get large increments, but unlike the increase/decrease brush size actions, the slider value changes linearly, which is much less useful  (increments are too large at small size, and vice versa). Wouldn't it make sense for this control to have the same logorithmic(?) behavior as the direct brush actions? It seems like this would make sense for masks generally. If not, is there a possibility for adding speed adjustment to the brush size actions?

**Comment by ig9000** [comment]
> I basically left them, rather than remapping the shortcuts to sliders up/down effects, because they don't directly translate; the old shortcuts were equivalent to (shift+)scroll actions and hence can change meaning depending on the active shape.

Yes, and also the fact that the brush shortcuts can be used *while painting with the brush*, while the slider shortcuts can't (at least, not in the current implementation). They're both useful. The workflow I've settled on is to map the same key that I use to activate the brush as a key+scroll shortcut for the slider. It's useful even now (linear), but will be more so after your update.

> With sliders (and their shortcuts, if fallbacks enabled) speed can be adjusted by holding shift or ctrl while scrolling, dragging or pressing left/right keys. You can also apply a default speed adjustment, set via the shortcut system, to each slider.

I do make use of these features, but also try to reduce "mousing around" from my workflow where I can. On that note, it doesn't seem to be currently possible to add the mask size slider to the quick access panel, would it make sense to enable that? The configurability of darktable's input system really is great, thanks for your work.

**Comment by ig9000** [comment]
> Keep in mind that if you have fallbacks enabled, moving the mouse while holding a slider shortcut key will move the slider (fast if moving up/down, slow if moving right/left). But if you then release the shortcut the brush will jump to the new mouse position. Midi rotors work well for adjusting size/hardness while drawing.

I'll have to watch out for that, I haven't encountered it so far. I don't need to change size while painting very often, so keyboard shortcuts for brush size generally work fine as long as the change isn't too big.

> It doesn't fit in the current "philosophy", where the QAP contains a collection of widgets from processing modules.

Understandable. I don't have any strong feelings about it, other than that I failed to discover them where they are now, but I don't interact with the mask manager much at all. Usually I can do what I need to from the masking section of the processing modules. Thanks again for working on this!

**Comment by dterrahe** [comment]
> Thanks again for working on this!

And you thanks for reporting issues and feedback; being aware of what needs fixing is a crucial step.
