### ISSUE TITLE
FujiFilm embedded lens correction with 70-300mm lens + 1.4x TC

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14071]
I've been happily using the "embedded metadata" option in the lens correction module with my new X-T4 and it appears to produce good results on all of my lenses except for the 70-300mm lens with the 1.4x teleconverter. The 70-300 works fine but with the teleconverter the lens correction module appears to only do TCA correction.

Looking at the image with exiftool, it appears to contain "Geometric Distortion Params", "Chromatic Aberration Params" and "Vignetting Params" so I assume it should work using these fields. Though looking at the numbers, perhaps only the TCA correction has anything useful in it.

```
Geometric Distortion Params     : 416.5555556 0.3535211268 0.5 0.6126760563 0.7070422535 0.7908450704 0.8661971831 0.9352112676 1 1.06056338 0 0 0 0 0 0 0 0 0
Chromatic Aberration Params     : 416.5555556 0.3535211268 0.5 0.6126760563 0.7070422535 0.7908450704 0.8661971831 0.9352112676 1 1.06056338 -0.0006103515625 -0.0006103515625 -0.0005798339844 -0.0005493164062 -0.0005187988281 -0.0004577636719 -0.0003967285156 -0.0003051757812 -0.0003051757812 -0.0008850097656 -0.0009155273438 -0.0009460449219 -0.001007080078 -0.001037597656 -0.001068115234 -0.001098632812 -0.001159667969 -0.001159667969 416.5555556
Vignetting Params               : 416.5555556 0.3535211268 0.5 0.6126760563 0.7070422535 0.7908450704 0.8661971831 0.9352112676 1 1.06056338 100 100 100 100 100 100 100 100 100
```

Happy to post a RAW somewhere if anyone thinks it's useful but I guess for now it's a more generic question as to whether anything can be done with this data for distortion/vignetting correction or not (I can't believe there _is_ no distortion or vignetting with this setup but maybe the appropriate data is just not being embedded in the image)

**Comment by jenshannoschwalm** [comment]
I guess the camera firmware recognizes the converter and only writes data it knows about :-)
