### ISSUE TITLE
Imported photos overwritten by second import 

### ISSUE THREAD

**Issue by firefrorefiddle** [darktable-org/darktable#14087]
**Did you buy darktable from an application store ?**

Installed current version with apt from opensuse repositories.

**Describe the bug/issue**

I imported photos from two cameras. The first camera had jpegs only, the second one was set to shoot raw and jpegs. Both were imported into the same film roll with a naming scheme like "20200401_001.{jpg,...}". Both imports had the images numbered starting from 1. The jpegs from the first import were overwritten by the images from the second import. 
In the lighttable view, these images (like ..._001.jpg) were still displayed with the preview image from the first import. In the darkroom view it became apparent that they were really the jpgs from the second import.
The only way not to lose the pictures from the first import is then to re-import. If they have been deleted on the first camera before the problem is realized, they are lost completely.

**To Reproduce**

0. Set camera 1 to shoot jpeg only.
1. Shoot photos on camera 1.
2. Set camera 2 to shoot jpeg+raw
3. Shoot photos on camera 2.
4. Set file naming pattern in import to "$(YEAR)$(MONTH)$(DAY)_$(SEQUENCE).$(FILE_EXTENSION)" (I think this is the default.)
5. Go to lighttable.
6. Connect camera 1
7. Click on copy and import.
8. Import desired photos from camera 1.
9. Connect camera 2
10. Click on copy and import
11. Import desired photos from camera 2.
12. Double-Click on first photo from camera 1.
13. Note that you are in darkroom and looking at a photo from camera 2. The original from camera 1 is lost.

Notes: 

- For me, camera 1 is Nikon D70, shooting JPEG only. Import with "copy and import" when the camera is directly connected with a USB cable and recognized as if it was a card reader.
- Camera 2 is Canon EOS 400d, shooting CR2+JPEG. Import with "mount camera (with PPTP)" and "copy and import from camera". 
- I haven't tested if the behavior is different when both or none are mounted with PPTP.

**Expected behavior**

I would expect the sequence of file name numbers for camera 2 not to start with 1, but with N+1, where N is the last number of the import from camera 2. In other words, the check for numbers should be independent from file extensions.

Note a related behavior, which is less problematic but still not nice: Suppose both cameras shoot raw only, but with different extension (i.e. they are from different manufacturers). The import start with "1" for both. This gives rise to file name conflicts on export, as both "..._001.cr2" and "..._001.nef" create jpegs called "...001.jpg". The conflict can be circumvented with the "create unique filename" option, but it's hard to argue why its there in the first place.

**Platform**

```
$ darktable --version
this is darktable 4.2.1
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support disabled
  libheif support disabled
  libjxl support disabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```

```
$ cat /etc/issue
Ubuntu 22.04.2 LTS \n \l
```

```
$ cat /etc/apt/sources.list.d/* |grep dark
deb http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04/ /
```

**Additional context**

 - Do you use lua scripts?
   - What lua scripts start automatically?
     - ext_editor
     - gimp
     - HDRMerge
     - hugin
     - image_stack
     - OpenInExplorer
     - photils
   - What lua scripts were running when the bug occurred? -- same as above

**Comment by firefrorefiddle** [comment]
This bug continues to bite me quite frequently and occurs in many forms. It's sufficient to shoot RAW+JPG in more than one RAW format. E.g. shoot RAW+JPEG on Pentax (DNG) and Olympus (ORF). Import both to the same film roll. In both sequences the filenames will start with "1" and JPGs will be overwritten.

First import creates:
- 20230505_0001.ORF
- 20230505_0001.JPG

Second import creates:
- 20230505_0001.DNG
- 20230505_0001.JPG

To make things worse, 20230505_0001.JPG will be displayed with EXIF data of the first import but the actual image of the second import.

Workaround: Tick "Keep original filenames" in preferences.

**Comment by gi-man** [comment]
I think you should edit your naming pattern to include the camera. I think `$(MODEL)`  or `$(MAKER)` or both. Something like:

`$(YEAR)$(MONTH)$(DAY)_$(MAKER)_$(SEQUENCE).$(FILE_EXTENSION)`

**Comment by firefrorefiddle** [comment]
Yes, that's one workaround, but wouldn't it make sense to check if a file with the same name already exists before creating it?
