### ISSUE TITLE
two different crops visible when using snapshots

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#14103]
**Did you buy darktable from an application store ?**
no

**Describe the bug/issue**
When comparing two different crops using snapshots, the former crop is still visible underneath the latter.

**To Reproduce**
1. Crop your image
2. Take a snapshot
3. Make a different crop of the image
4. Display the snapshot taken in step (2). 
5. See the two different crops visible at the same time.

**Expected behavior**
Only one image visible at a time.

**Screenshots**
![snapshot-crop-compare](https://user-images.githubusercontent.com/69561443/229413805-16050d90-0621-4a08-8b59-884c0cc983ab.png)

**Which commit introduced the error**
This issue wasn't present before the reworking of the snapshots module.

**Platform**
* darktable version : 4.2.1 (from OBS repos - stable)
* OS                : Linux 5.19.0-35-generic
* Linux - Distro    : Mint 21.1
* Memory            : 32gb
* Graphics card     : rtx 2060
* OpenCL installed  : y 
* OpenCL activated  : y
* Xorg              : y

**Comment by TurboGit** [comment]
Well clearly the snapshots are not to be compared with different crop. What would you like it displayed? Cropping which part? And after all for what usage?

**Comment by SoupyGit** [comment]
Why not? Snapshots are used to compare different edits. Sometimes that might be colour, others contrast, others crop. It is useful when doing on/off snapshotting, as opposed to dragging the slider across back and forth. Different crops can also be compared in history, so there is a workaround, but nonetheless, the way snapshot displays this now doesn't seem correct.

Another use case, comparing two different images. Eg. You take a photo of the same scene a minute or so apart. If the framing changes within that minute, it might call for a different crop. If you then snapshot the first image with a different crop and compare to the second, you run into this problem.

How it looks now:
![snapshot1](https://user-images.githubusercontent.com/69561443/229791303-520644e2-50f6-451d-9d95-738340679bcf.png)

How it should look:
![snapshot2](https://user-images.githubusercontent.com/69561443/229791326-f93458cb-3d4a-49c5-a87e-983cac322adc.png)

**Comment by Nilvus** [comment]
I agree with you @SoupyGit about why do that. But I also agree with @TurboGit about actual snapashots working.

Actual snapshots are comparing an image on a step above another one. So with different crops, what you have is just normal. You have one crop above another. Comparing them could of course, as you clearly explain, be done. I personally think (even if I understand the "how it should look" you post) that for comparing crops, a side by side would be better (that's my view). That is possible actually on lighttable as you probably know, but not on darkroom. Just my 2 cents!

But yes, maybe we could hide the other crop (on what I understand on your screenshots, I never compare different crops). on the other side of snapshot line.

**Comment by MStraeten** [comment]
but then it’s not just crop but all other geometrical transformations that could have been done after taking the snapshot. That might open a can of worms

**Comment by Nilvus** [comment]
> but then it’s not just crop but all other geometrical transformations that could have been done after taking the snapshot. That might open a can of worms

Of course. Nothing is simple!

**Comment by SoupyGit** [comment]
Yes it's possible to compare in lighttable and history, so workarounds exist. Snapshots are best though as they are a much faster workflow, especially just tapping them on/off with shortcuts.

Of course I don't know the complexity of the request, I just consider things from an ideal perspective. As far as I see new snapshots module is wonderful, better in all ways to the old one, except on this point.

**Comment by ralfbrown** [comment]
Current master only shows one crop even when the crops for the snapshot and currently-selected development step differ.
