### ISSUE TITLE
Black frame in darktable when color calibration is active

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#14100]
**Introduction**
I get a black frame in darkroom when color calibration is active for all my files: CR2, CR3, ARW if I go to a picture and reset history back to defaults (scene-referred filmic in my case) or if I reset the color calibration module using the reset button.

This was first pointed out by https://discuss.pixls.us/u/DerMartin in https://discuss.pixls.us/t/recent-master-lets-image-turn-black-when-color-calibration-set-to-iluminant-as-shot-in-camera/36396

---------------------------------------------------------------

**Describe the bug/issue**
I get a black frame in darkroom when color calibration is active for all my files: CR2, CR3, ARW if I go to a picture and reset history back to defaults (scene-referred filmic in my case) or if I reset the color calibration module using the reset button.

I build in Linux Debian 11, from git master. release-4.3.0-1529-gdff4b30a22

**To Reproduce**
1. Set scene-referred filmic as default processing to make sure color calibration is used by default.
2. Select raw file in lighttable and click to go to darkroom.
3. In darkroom select `reset history` or `color calibration reset parameters button`
4. The frame renders black in darkroom. Disable color calibration and the picture renders again (without color calibration).

**Expected behavior**
A frame rendered with color calibration defaults.

**Screenshots**
![Screenshot from 2023-04-02 21-30-24](https://user-images.githubusercontent.com/42386052/229374742-d6fe81d1-9e9a-442e-9fe1-953d9b995437.png)

**Which commit introduced the error**
If I compile source before https://github.com/darktable-org/darktable/commit/084bf73cc1b984fe2b584ab7f9c9f2e2dc25509a, then the picture is rendered normally.

**Platform**

* darktable version : release-4.3.0-1529-gdff4b30a22
* OS                : Linux debian 5.10.0-21-amd64 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
* Linux - Distro    : Debian 11
* Memory            :  16 GB
* Graphics card     :  NVIDIA Corporation TU104GL [Quadro RTX 4000]
* Graphics driver   : NVIDIA 470.161.03-1
* OpenCL installed  :  Yes OpenCL 3.0 CUDA, SM_20 SUPPORT
* OpenCL activated  : Yes
* Xorg              :  X11
* Desktop           :  Gnome3
* GTK+              :  3.38.5
* gcc               :  gcc (GCC) 12.2.0
* cflags            : 
* CMAKE_BUILD_TYPE  : Release

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes from commit https://github.com/darktable-org/darktable/commit/084bf73cc1b984fe2b584ab7f9c9f2e2dc25509a**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - Do you use lua scripts? **no**
 
Starting with `./darktable --disable-opencl` did not change anything. Still same error.

**Comment by ralfbrown** [comment]
Confirmed.  On reset, the illuminant seems to be set to black (it goes back to something reasonable after clicking the eyedropper), so there's probably a missing init.

**Comment by TurboGit** [comment]
@ralfbrown : One for you as a regression of your recent work. TIA.
