### ISSUE TITLE
taking a snapshot imposes minimum panel width

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14104]
Taking a snapshot in the darkroom view changes the width of the side panel -- this appears to be because the snapshot name has an enforced minimum width. This should not happen and the snapshot name should ellipsise as needed:

https://user-images.githubusercontent.com/9555491/229458268-33853ff5-7120-4fc1-874f-25441b8fb56e.mp4

darktable 4.3.0+1534~gb093bd6079 on ArchLinux

**Comment by TurboGit** [comment]
> Needs some trivial fixes; @TurboGit are you already working on this or do you want me to do the honors?

I'm on it. And not trivial in fact as we have two labels side-by-side and we don't want the module name to be ellipsised too much. A PR in a moment.

**Comment by TurboGit** [comment]
@dterrahe : See #14110.
