### ISSUE TITLE
[FR] Recognize additional sidecar files

### ISSUE THREAD

**Issue by mathesst** [darktable-org/darktable#14121]
**Is your feature request related to a problem? Please describe.**
I sometimes use external programs to work on my pictures. These programs create additional sidecar files, e.g. basefilename.arw.dop. Theses additional sidecars are not recognized by darktable for actions like delete or move. 

**Describe the solution you'd like**
A editable list of additional sidecar fileextensions that are then also recognized by darktable.

**Alternatives**
move or delete all files beginning with the same basefilename and not only the ones that have an xmp extionsion

**Additional context**
none

**Comment by mathesst** [comment]
But in your scenario you already have the same issue with the xmp files, or am I wrong? 

You would have "img.dng.xmp" and "img.dng.jpg.xmp" ? And that should be already handled by darktable. In my version you would have additionally "img.dng.dop" and "img.dng.jpg.dop" .

**Comment by parafin** [comment]
The question is whether img.dng.jpg sidecar for img.dng. With your proposed logic “everything that starts with img.dng” it is sidecar, but it’s going to be a problem if it’s imported also. Having dt behave differently depending on what’s imported or not is a bad idea. So you will have to end up with either a whitelist or blacklist of file extensions for sidecars.
