### ISSUE TITLE
xmp not saved

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#14125]
**Describe the bug/issue**
If I only open an image in darkroom, and only apply the automatically applied modules: scene referred defaults, modern color science, and custom auto-applied modules, and immediately close the image and return to lighttable, no xmp is saved.

**To Reproduce**
_Settings_
 - Database _:memory:_
 - Write sidecar file for each image _after edit_

_Detailed steps to reproduce the behaviour,_
1. Select and open a "fresh" image from lighttable into darkroom
2. See that all auto applied modules are applied
3. Return to lighttable
4. Check the image directory with a file manager and see .xmp file missing

**Expected behavior**
.xmp file is created with the auto applied modules.

**Platform**
* darktable version : 4.3.0+1577~g558f8cef94
* OS                : Win11 Enterprise 22H2
* CMAKE_BUILD_TYPE  : Release

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with version 4.0.1**
 - Can you reproduce with another OS **yes with Fedora Linux 37 (Workstation Edition)**

**Comment by TurboGit** [comment]
What about this preference:
![image](https://user-images.githubusercontent.com/467069/230194879-7c6c9f7d-18b5-4c77-b367-4c42fc69bca9.png)

**Comment by lintujuh** [comment]
Yes, I have that set exactly so. Isn't it editing, if I auto apply all the default modules and settings?

**Comment by TurboGit** [comment]
So set this at import and you'll get the xmp.

**Comment by lintujuh** [comment]
Okay, but I still disagree on the interpretation of _after edit_. If the database has the edits after auto apply, why they stored there, but not in the xmp?

**Comment by TurboGit** [comment]
You may disagree, but that's what has been documented and implemented.

https://docs.darktable.org/usermanual/4.2/en/preferences-settings/storage/#xmp
