### ISSUE TITLE
OpenEXR displaywindow is not respected

### ISSUE THREAD

**Issue by eoyilmaz** [darktable-org/darktable#14136]
### Checklist

- [X] I have checked [GitHub Issues](https://github.com/darktable-org/darktable/issues?q=is%3Aissue) and my problem is **not** described there.

### Describe the bug

Under MacOS with AppleSilicon, DisplayWindow of Hugin exported OpenEXR files are not respected as shown in the image.

### Steps to reproduce

1. Export a panorama as OpenEXR file from Hugin.
2. Import it to Darktable

### Expected behavior

displayWindow to be respected and no black part shown

### Logfile | Screenshot | Screencast

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1786804/230507511-63504081-b481-498a-aa59-2845c7d9259d.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1786804/230507345-2a6d8943-30a8-414d-af7f-b92cebe60d55.png">

### Where did you install darktable from?

darktable.org

### darktable version

4.2.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Ventura 13.3

### Describe your system?

Apple Silicon Macbook Pro 16 M1 Pro

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by pitbuster** [comment]
I always thought it was just me with those black borders on openEXR

**Comment by kmilos** [comment]
Please share a file and a detailed specification of what should be done.

dt generally tries to avoid/ignore cropping the image from file metadata in order to provide the maximum to work with and let the crop be part of the development process and creative choice.

Is there a way in EXRs to tell us what is valid data and what is "creative" crop?

This btw not restricted to EXRs, we have a similar approach in AVIFs and HEICs as well...

**Comment by eoyilmaz** [comment]
Here is the OpenEXR file:

https://www.dropbox.com/s/h10e3wdl4c695qq/_A7R7039-_A7R7041_4_hdr.exr?dl=0

Here, you can see Blender reading it properly:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1786804/230564902-ed459476-8be8-463a-9cdf-a26aff3e89a8.png">

and Darktable again:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1786804/230507345-2a6d8943-30a8-414d-af7f-b92cebe60d55.png">

I can't give any technical information, as I'm not very knowledgeable on OpenEXR parser. But as far as I know, OpenEXR holds different data for the image size and the data window, or display window and ~~apparently Darkatable just reads the image size where it should be also obbeying the displayWindow (or maybe some other window attribute).~~ Okay, I checked the code and apparently Darktable is using the displayWindow where it should probably use the dataWindow
https://github.com/darktable-org/darktable/blob/master/src/imageio/imageio_exr.cc#L169

This could be totally wrong. The file I uploaded should help.

**Comment by kmilos** [comment]
So, dt should ignore the _display window_ altogether?

https://openexr.com/en/latest/TechnicalIntroduction.html#overview-of-the-openexr-file-format

**Comment by kmilos** [comment]
Btw, are you able to also provide a sample where the display window is smaller than the data window please?

**Comment by eoyilmaz** [comment]
I checked Blender's code and they are using the dataWindow:

```
Box2i dw = data->ifile->header(0).dataWindow()
```

I think this line https://github.com/darktable-org/darktable/blob/master/src/imageio/imageio_exr.cc#L147

should also use the dataWindow instead of the displayWindow

```
dw = header.dataWindow();
```

**Comment by kmilos** [comment]
It's not that simple, I think there also needs to be some changes to the `setFrameBuffer` call that need to be carefully considered...

**Comment by eoyilmaz** [comment]
Oh I was able to build on my macbook, and I confirm @kmilos's change fixes the issue as seen in the following screen capture:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1786804/230675146-3b13e502-e472-40c9-936c-62fe4690ae91.png">
