### ISSUE TITLE
darktable: llvm::report_fatal_error():

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#14145]
### Describe the bug

Reporting a downstream darktable: llvm::report_fatal_error(): crashreport from a Fedora user.
For all details and logs see
https://bugzilla.redhat.com/show_bug.cgi?id=2185324

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

**Comment by ralfbrown** [comment]
That looks like a crash in the OpenCL driver code (line 28 of the backtrace and everything above is OpenCL or system code).

**Comment by parafin** [comment]
There were that type of errors reported before - basically it’s LLVM bug - it can’t handle being loaded twice (e.g. because two OpenCL drivers are loaded both using LLVM internally). In any case (be it LLVM or OpenCL driver fault) it’s not a dt bug.
