### ISSUE TITLE
Exif "Focal Length in 35mm Format"

### ISSUE THREAD

**Issue by pinetti99** [darktable-org/darktable#14155]
**Is your feature request related to a problem? Please describe.**
 It seems that Darktable does not import the EXIF variable "Focal Length in 35mm Format". I would find it very useful for cameras with non-full frame sensor.

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by pinetti99** [comment]
So it should not be that difficult to show it among the available EXIF fields... :)

**Comment by victoryforce** [comment]
> So it should not be that difficult to show it among the available EXIF fields... :)

You're right. It's not difficult. I'll prepare PR for this.

**Comment by kmilos** [comment]
Nice, but too bad it wasn't designed in from the start - it would've been nice if it were actually also in the database and not just displayed so one could e.g. also filter the collection by it...

**Comment by victoryforce** [comment]
> Nice, but too bad it wasn't designed in from the start - it would've been nice if it were actually also in the database and not just displayed so one could e.g. also filter the collection by it...

We have the real focal length and crop factor in the database. This is practically the same as having an equivalent focal length. There is no problem at all in filtering collections by these properties.
