### ISSUE TITLE
Issue importing images from camera.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#14159]
### Describe the bug

I don't know if this error is generated by one of the lua scripts that I have activated or if it is some other type of error. Unfortunately I haven't had the chance to try importing images from another camera, the one I use is a Fujifilm X-H1, although it doesn't seem to me that it is with this camera specifically.

I got this error message importing any image from camera:

"Could not find the attribute DigitalZoomRatio using the command: <exiftool -DigitalZoomRatio '/run/media/franklin/My Book/PHOTOGRAPHIC_DB/2023-04-08/_DSF1341.RAF'>"

### Steps to reproduce

1. Mount the camera
2. Go to copy and import
3. Select images to import from camera
4. See error message

(I'm afraid this issue isn't reported yet)

### Expected behavior

The image import should not have any error message.

### Logfile | Screenshot | Screencast

[error_list.zip](https://github.com/darktable-org/darktable/files/11185822/error_list.zip)

### Commit

Not sure.

### Where did you install darktable from?

From Suse repositories
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

### darktable version

4.3.0~git1656.c8e51520-9680.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Describe your system?

OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.2.7-200.fc37.x86_64
Uptime: 2 hours, 17 mins
Packages: 2175 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.4
WM: Mutter
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark-solid [GTK2/3]
Icons: Mkos-Big-Sur [GTK2/3]
Terminal: alacritty
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 5861MiB / 32012MiB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Driver Version: 530.41.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

If it's necessary I can supply some .raf files

LUA scripts
-------------------------

**contrib**
autocrop
change_group_leader
CollectHelper
color_profile_manager
copy_attach_detach_tags
display_in_darkroom
enfuseAdvanced
ext_editor
fujifilm_auto_settings
fujifilm_dynamic_range
fujifilm_ratings
gimp
harmonic_armature_guide
HDRMerge
hugin
image_stack
image_time
LabelsToTags
OpenInExplorer
photils
quicktag
rate_group
rename_images
RL_out_sharp
select_untagged
smart_styles
transfer_hierarchy

**examples**
api_version
InitialWorkflowModule

**official**
copy_paste_metadata
delete_long_tags
enfuse
image_path_in_ui
import_filter_manager
import_filters
save_selection
selection_to_pdf

**tools**
executable_manager

**wpferguson**
adjust_time
export2collection
postsharpen

**Comment by wpferguson** [comment]
When through the darktable source tree, lua-scripts source tree and my scripts source tree and found no mention or use of DigitalZoomRatio.  I also looked through the InitialWorkflowModule source and didn't see it there either.

**Comment by difrkaguilar** [comment]
> When through the darktable source tree, lua-scripts source tree and my scripts source tree and found no mention or use of DigitalZoomRatio. I also looked through the InitialWorkflowModule source and didn't see it there either.

Well, then it's other thing... I will continue my search.
