### ISSUE TITLE
Linked inverted masks for two module instances

### ISSUE THREAD

**Issue by asdkant** [darktable-org/darktable#14158]
# Is your feature request related to a problem? Please describe.
It often happens that I want to apply a given module in two distinct ways for two distinct regions of an image, and the delimitation of those two regions is defined by a fairly complex mask (usually drawn & parametric).

When I want to do this, the only way I have is to define the mask, work the module parameters for that first region, then duplicate the instance and rework the parameters. But... if I want to change the mask, then I have to re-do one of the instances all over again (or manually adjust the mask parameters with a GUI that is not really suited to fine-tuning, as per #6695 )

# Describe the solution you'd like
A mechanism that would let me create a second "linked" instance that gets an automatically updated inverse mask of the first instance. Whenever I change the mask in one of the instances, that should automatically update the other linked mask accordingly (maybe this could internally be a single master mask, and that can be affected by the GUI in either instance of the module). This would eliminate all that manual busywork.

I suppose having two or more non-inverted linked masks could also come in handy, if one wanted to stack effects on a given region of the image using parametric / drawn+parametric masks

**Comment by MStraeten** [comment]
at least for parametric masks its not trivial to create a true inverted mask in a later instance since the input data of both instances are different. 
you can go with a inverted raster mask defined in the first instance  - but you can edit that mask just in the instance where it was defined.

**Comment by dterrahe** [comment]
> you can go with a inverted raster mask defined in the first instance - but you can edit that mask just in the instance where it was defined.

It sounds like this is exactly what the OP is after? https://darktable-org.github.io/dtdocs/en/darkroom/masking-and-blending/masks/raster/

**Comment by TurboGit** [comment]
Just to be sure, this is supported for drawn masks. When you import a drawn mask group into another instance both are using the very same masks and if one edit a mask in any one of the instance it also changes the drawn mask in the other instance.

For parametric mask that's not really possible as already explained here, the best option is then a raster mask.

**Comment by dterrahe** [comment]
> the best option is then a raster mask.

Is there a drawback to using raster masks? It seems to me that they should have the advantage of only needing to be calculated once, rather than needing redrawing for each module that uses the same set of drawn shapes?

One way of partly addressing #14076 would be to have a mode when assigning a style to an image where all modules in the style except the first one in the pipe have a raster mask set pointing to that first one. Then if a mask was defined on that first one, it would immediately apply to the whole style. This would avoid having to select the mask _while_ applying the style (and having to update it everywhere afterwards if changed).

**Comment by dterrahe** [comment]
> having a self-updating raster copy of that one for the subsequent modules would do the trick (so long there's an option to use the inverted version).

To be clear, this describes existing functionality (referred to in the link to the manual I gave earlier).

@asdkant Have you tried using a raster mask in the second instance referring to the mask defined in the first instance and reversing polarity? Did it satisfy your requirements? If so, please close this issue. If not, please provide further clarification.

**Comment by asdkant** [comment]
@dterrahe I just checked, Yes, that's exactly what I wanted, thanks!
