### ISSUE TITLE
Incorrect image aspect ratio after "crop" and "rotate and perspective" modules have been applied

### ISSUE THREAD

**Issue by kartio** [darktable-org/darktable#14162]
### Describe the bug

Image aspect ratio changes when image is rotated with "rotate and perspective" module and cropped with "crop" module.

### Steps to reproduce

1. Open image
2. Crop image with any aspect ratio
3. Add rotation
4. Swith "rotate and perspective" module on/off to observe incorrect crop aspect ratio

**Comment by kartio** [comment]
@MStraeten It's impossible to crop an image before rotating it because Darktable doesn't allow reordering the "crop" module below the "rotation and perspective" module.

Best practices apply, but they are **not the solution** to this problem.

**Comment by ralfbrown** [comment]
Aspect ratio in the crop module is only a convenience to constrain the actual parameters, which are the percentage of image width/height to be removed from each edge.  Change the input dimensions and the same percentages will still be removed, but if the aspect ratio of the module's input changes, so will the aspect ratio of its output.

Enforcing a fixed aspect ratio in the output would require major re-architecting of the crop module, with no guarantees that the new crop after an input change would be one that the user desired....
