### ISSUE TITLE
<SAMSUNG NX20>

### ISSUE THREAD

**Issue by louilouilouiloui** [darktable-org/darktable#14167]
Hello friends!
I have the camera SAMSUNG NX20 and would like RAW file support for it.
I understand you need photos in RAW format.
I did upload an image today but it is an old image not taken for this purpose.
I understand you want landscape photographs so I will take landscape photographs and upload on a near daily basis until you have what you need. Just e-mail me if you want anything else than landscape photographs. 
See you tomorrow!
Thank you guys!

**Comment by kmilos** [comment]
The RPU sample opens fine for me w/ dt 4.4. Is there anything else missing? @louilouilouiloui

**Comment by victoryforce** [comment]
Samsung NX20 was supported long before this issue was raised, and in darktable 4.2, released on winter solstice 2022, the correctness of support was verified on samples from RPU. So, I am closing this issue.

**Comment by louilouilouiloui** [comment]
Ok I got an error message when I opened the file saying the camera was not supported and I was encouraged to report and help with raw images.
Thank you for work!

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________
