### ISSUE TITLE
Darktable stops accessing external drive

### ISSUE THREAD

**Issue by ColdCoffee101** [darktable-org/darktable#14178]
### Describe the bug

Hi,

New user here coming from lightroom - I have all my images stored on a USB sandisk 2tb drive connected to my M1 Macbook Pro MacOS 13.3

After "sleeping" or rebooting all my images are no longer available, see attached screen shot saying access denied?

I've given darktable full disk access via security, but this hasn't solved the issue and I can find nothing about access to external drives

Finder and all other apps have no issues with the external drive, which leads me to think user error or a bug!

![Screenshot 2023-04-11 at 14 48 24](https://user-images.githubusercontent.com/130070864/231184873-d9cecc31-249d-49cd-8341-ead457b3b544.jpg)

### Steps to reproduce

import folder of images from external USB drive (sandisk 2tb)

does not happen after every sleep or reboot, but whole drive denied access (see screen shot)

Re-selecting drive for import becomes sandisk1 and images are available again 

### Logfile | Screenshot | Screencast

![Screenshot 2023-04-11 at 14 48 24](https://user-images.githubusercontent.com/130070864/231185101-a64e7823-3bb6-46d7-9bc0-f713906be425.jpg)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Mac

### What is the version of your OS?

ventura 13.3

### Are you using OpenCL GPU in darktable?

No

**Comment by parafin** [comment]
Disk available under different name hints at volume being remounted at a new location (presumably because old one was busy?)…

**Comment by ColdCoffee101** [comment]
Hi Thanks for your reply MStraeten, I just upgraded my OS to 13.3.1 as it contains "bug fixes" and its just done it again on reboot. I've now checked files and folders section and it states darktable has full disk access?

Parafin - I confess to not knowing how to check/stop that, any help appreciated 

Shelton.

**Comment by zisoft** [comment]
As @MStraeten already mentioned: "Full disk access" is not sufficient/needed here. You need to grant darktable access to "files and folders --> removable volumes"

**Comment by ColdCoffee101** [comment]
Hi!

Just to confirm this is where you are talking about:

system settings > Privacy & Security > Files & Folders 

If so there is no removable volumes option in there?

Quitting makes no difference, once it states unavailable the only way to restore is to completely re-import the folder on the Ext SSD even after a reboot of the mac

![Screenshot 2023-04-11 at 21 17 12](https://user-images.githubusercontent.com/130070864/231278713-6c57a027-cb9d-43cf-9136-5cb5139ee815.jpg)

**Comment by jas01** [comment]
I got the same issue with linux (archlinux + darktable 4.2.1) a little different from the original problem. 

All my photos are on a external drive, I mount the drive manually with (sudo mount) when I launch darktable (currently with --disable-opencl) I can see my all photo, but I'm unable to import anything. When I use the import bottom, I can see the directory but no file.

Don't know if you want me to open a new issue.

darktable : 4.2.1
everything up2date on archlinux

**Comment by jas01** [comment]
> I got the same issue with linux (archlinux + darktable 4.2.1) a little different from the original problem.
> 
> All my photos are on a external drive, I mount the drive manually with (sudo mount) when I launch darktable (currently with --disable-opencl) I can see my all photo, but I'm unable to import anything. When I use the import bottom, I can see the directory but no file.
> 
> Don't know if you want me to open a new issue.
> 
> darktable : 4.2.1 everything up2date on archlinux

After upgrade to 4.4.x everything work again

**Comment by ralfbrown** [comment]
Closing since we've had two feature releases since the original report and the issue has been reported as resolved in 4.4.
If this occurs in 4.6 or higher, feel free to reopen the issue.
