### ISSUE TITLE
In exported TIFF the size has lost one pixel in width and height in the first picture of a group

### ISSUE THREAD

**Issue by wwwFrank** [darktable-org/darktable#14186]
### Describe the bug

Exporting a group of pictures as **TIFF**.
The first picture is **1 pixel** smaller in height and width as the other pictures and as shown in image information.

### Steps to reproduce

I have a **group** of pictures from a focus-stack-series. For stacking them in "Zerene Stacker" they must habe identical size and identical development.
I develop the first picture of the group, then copy the history stack of this picture and paste (overwrite) it to the rest of the group.
Module **"crop" is not used**, all pictures have the same size, the full size from the camera-sensor.
Image information show: width 5220, height: 3912 after starting Darktable.
Image information show: width **5208** (5220), height: **3912** when export (TIFF) had been used.

Then I export the group (here: **TIFF**, 16bit, deflate, **Size: 0 x 0 Pixel**) and import the TIFFs to zerene. Zerene could not stack them because of "different picture-size".

TIFF from No. 2 to the last of the group is exported in the correct size (5208 x 3912) from image information.
But the **first picture** is exported in the size **5207 x 3911 pixel**. 1 Pixel is lost from height and width.

I have to use the crop module or "set size" (> 0) in export module to get identical (full) size.

In exported JPG the size is correct. In exported TIFF (8bit) the pixel ist lost.

### Expected behavior

Darktable should export all pictures in the group in the same size

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2 LTS

### Describe your system?

Intel® Core™ i5-6600 CPU @ 3.30GHz × 4
16 GB
NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]

### Are you using OpenCL GPU in darktable?

Yes

**Comment by ralfbrown** [comment]
Sounds like something isn't properly initialized in the export code.  If you export a single image (not necessarily from the group) at size 0x0 and *then* export your group, does the first image have the correct size?

**Comment by wwwFrank** [comment]
Export of a single Picture, not cropped, as TIFF 16 bit, is 1x1 smaler then the image information shows.
Exporting it again is also 1x1 pixel too smal.
Exporting 2 not-grouped pictures: both smal.
Exporting 3 grouped images (not developed): all smal.
Exporting 3 grouped images **with copied history stack** (from first to the others): size is mixed, 1 smal, 2 OK.
It seems that only pictures are OK, that have got a "paste" of a history stack.

**Comment by ralfbrown** [comment]
Thanks.  That strongly indicates an uninitialized or improperly initialized variable.

**Comment by jenshannoschwalm** [comment]
The issue has already been fixed in master via #13329, there were quite a number of similar reports.
