### ISSUE TITLE
group masks label renamed

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14183]
Just for tracking the documentation change:

"grp %s" ->  "group `%s'"

https://docs.darktable.org/usermanual/development/fr/module-reference/utility-modules/darkroom/mask-manager/

**Comment by elstoc** [comment]
Thanks but I don't normally check issues for this tag - it might be better as an issue in the dtdocs repo if there's no associated PR. Also I'm not entirely sure what change you are asking for.

**Comment by TurboGit** [comment]
I've spotted under the link above:

`Groups of shapes forming a mask are displayed with a headline in the form “grp <module_name>” indicating`

So `grp` should now be `group`.

**Comment by victoryforce** [comment]
Since the corresponding PR in the documentation repo has already been created, this issue can be closed.
