### ISSUE TITLE
White balance support of Nikon Z6 ii

### ISSUE THREAD

**Issue by miroslavfikar** [darktable-org/darktable#14182]
Attached are finetuned (with step 1.0) white balance presets for Nikon Z 6_2 camera. 

[darktable-whitebalance-20230411.tar.gz](https://github.com/darktable-org/darktable/files/11204878/darktable-whitebalance-20230411.tar.gz)
For noise profiles, please also attach the entire archive with `.pdf` plots.

**Comment by kmilos** [comment]
Thanks for the data!

**Comment by miroslavfikar** [comment]
Just a question, how did you generate the wb_presets.json file? The documentation seems to be obsolete (https://github.com/darktable-org/darktable/wiki/White-balance-presets) and suggests to edit wb_presets.c. In addition, wb_extract.py generates a simple text file, not the json.

**Comment by kmilos** [comment]
Yeah, the wiki is out of date, feel free to try and edit it 😉 

I have updated the extract_wb.py to generate JSON, you might need to pull the master branch?
