### ISSUE TITLE
Can't open .rw2 from Panasonic GF8

### ISSUE THREAD

**Issue by TomeuMS** [darktable-org/darktable#14196]
### Describe the bug

I just bought a Panasonic GF7 and I can't open any of the raw files (.rw2).
Files show normally in "whitetable" but when clicking on them for openining with "darkroom" apears an errror "Error when reading white balance information"

### Steps to reproduce

1. Open file on "darkroom"
2. This error will appear "Error when reading white balance information"

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2 LTS

### Describe your system?

Procesor: AMD® Ryzen 7 5700u with radeon graphics × 16
RAM: 16,0 GiB 

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[P1190024.RW2.zip](https://github.com/darktable-org/darktable/files/11221251/P1190024.RW2.zip)

**Comment by kmilos** [comment]
No problem w/ the GF7 sample from https://raw.pixls.us/:

![image](https://user-images.githubusercontent.com/4973094/231743865-8083f291-15e0-4d3e-96cd-4f75a9e8723b.png)

Your model is actually a DMC-GF8, which is not yet supported. Please start w/ uploading the samples to RPU and following https://github.com/darktable-org/darktable/wiki/Camera-support

How is it different from GF7?

**Comment by kmilos** [comment]
> I will follow the steps and open a new Camera support request

Thanks. Maybe we don't need the new request, but the samples are a must, just ping here when you have uploaded them to RPU.

**Comment by TomeuMS** [comment]
Done, I just uploaded the 4 raw files. One for each crop (1:1, 4:3, 3:2, 16:9).

**Comment by kmilos** [comment]
Thanks. In the meantime, if you feel confident, you can make the suggested changes from the PR to your cameras.xml (just a copy and rename of the GF7 sections really).

**Comment by kmilos** [comment]
This is now merged and available on master, and can be closed.
