### ISSUE TITLE
mask editing - selection not shown 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14192]
### Describe the bug

When the arrow to edit the masks in the blend section is activated the masks are not shown. One need to collapse/expand the module for the masks to be displayed.

### Steps to reproduce

1. Open an image with a mask in darkroom
2. Open the module having the drawn mask
3. Click on the arrow to activate mask editing

See no mask are displayed.

### Expected behavior

masks should be displays and ready to edit

### Commit

Not checked but I suspect c7b155d92ee3169110d0f65a3beea847746b3b7d

### Where did you install darktable from?

darktable.org

### darktable version

current master

### What OS are you using?

Linux

### What is the version of your OS?

Debian/sid

### Are you using OpenCL GPU in darktable?

Yes

**Comment by TurboGit** [comment]
One for you I think :)

**Comment by dterrahe** [comment]
I'm trying to reproduce, but for me current master seems to work as expected. When you say

> See no mask are displayed.

You mean in the mask manager, right? For me the shapes group of the active module is expanded (and selected) as soon as I click on the "show and edit mask elements" arrow in the blend section. The shapes are also visible in the center view.

> One need to collapse/expand the module for the masks to be displayed.

The mean the mask manager? Not needed for me. Or the iop module? It works whether it was initially expanded or not when switching to darkroom.

**Comment by TurboGit** [comment]
> You mean in the mask manager, right?

No I mean the on-canvas forms in the center view.

I'll try again to reproduce.

**Comment by TurboGit** [comment]
@dterrahe : I found a reproducer, the important point is that when starting dt the module with the mask must be expanded and multiple instances are used.

1. delete history stack of an image
2. go to darkroom
3. select "rgb curve"
4. add a drawn mask (whatever, a simple circle will do)
5. create a new instance of "rgb curve" (named 1)
6. select drawn mask, add the groupe of form from the other "rgb curve" instance
7. quit dt
8. restart, the main "rgb curve" module is expanded
9. click on the arrow to go to mask edit mode
10. see no mask displayed
11. collapse/expand module and the mask is displayed

**Comment by TurboGit** [comment]
I've removed point 6 as not needed after further test.

**Comment by todd-prior** [comment]
Not sure if this is what you are talking about but if you have the have the selection to show mask elements set to on in a module and then you go in the mask manager if you select one of the mask this is disabled you have to go back and select the group to turn it on...maybe it has always been that way but I was just playing with the mask manager. I don't too often use it as basic drawn and parametric selecitons are usually enough for me..... So I wonder if a trip to the mask manager could create this depending on what you clicked on??

**Comment by todd-prior** [comment]
Let me know and i can open a separate issue... in the mask manager currently if you select a shape from the running list below the groups you lose the opacity slider in the MM module dialogue and you cannolt ctrl scroll to adjust and finally it reports the shape as having 0% opacity. If you move or adjust the size or feather on screen the focus jump to the entry for that shape in the module group... Opacity is still not available but if you click on the shape name it comes back. It seems odd that only opacity is effected so I think it might be a bug.. I made a video to show this if it is not clear what I am explaining and I can open a separate issue if you can reproduce... I am on WIn11 4.3.0+1765~g41f0f343e9    https://discuss.pixls.us/t/mask-manager-mask-properties/36713/3?u=priort

**Comment by TurboGit** [comment]
> Let me know and i can open a separate issue... in the mask manager currently if you select a shape from the running list below the groups you lose the opacity slider in the MM module dialogue and you cannolt ctrl scroll to adjust and finally it reports the shape as having 0% opacity.

Yes, a new issue please.
