### ISSUE TITLE
Ellipses in drawn masks don't register mouse in small spot in lower right corner

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#14204]
### Describe the bug

In drawn masks,  slightly rotated ellipses can have a small "dead" area where the mouse is not registered as being inside the ellipse. This can sometimes make it impossible to drag a control point or lead to accidental drags or zooms of the whole image when manipulating the shape.

It seems that the longer end needs to be tilted towards the bottom right and it seems to make a difference _which_ longer end; (rotating 180 degrees can cause the problem). There is a small segment where the mouse is not registered if it is within the shape. I tried to find the issue in the past, but gave up. Something with the the closing nodes of the ellipse not correctly overlapping with the opening nodes, at least for "inside" calculation.

### Steps to reproduce

1. Add a drawn mask to any module
2. Add an ellipse to the mask
3. Make it "big enough"
4. Rotate it slightly and stretch the lower right side so it is longest.
5. Move the mouse around within the shape near the lower right side control point.
6. See the shape changing between active and not active when the mouse is inside all the time.
7. If you don't see 6, rotate the shape 180 degrees and try again.

This is _very_ easy to trigger for me on all kinds of screens, zoom levels and operating systems, but maybe there's something specific that I always do that I've left out of the above as it seems to not happen for others.

[Follow up from #14199](https://github.com/darktable-org/darktable/pull/14199#issuecomment-1508397715)

### Expected behavior

Always register the mouse inside an ellipse when it is inside an ellipse.

### Logfile | Screenshot | Screencast

Using image from test set:
[mire1.cr2.xmp.zip](https://github.com/darktable-org/darktable/files/11232841/mire1.cr2.xmp.zip)
Good:
![image](https://user-images.githubusercontent.com/1549490/232046059-ff216188-27a5-4ccc-bfc7-81259fdf026c.png)
Not good:
![image](https://user-images.githubusercontent.com/1549490/232046162-f3c59c22-d0dc-43ed-ac28-24e7cba0f711.png)

A video:
https://user-images.githubusercontent.com/1549490/232055260-d09a4118-8241-431c-b590-debda18ed7a8.mp4

### Commit

This has been a longstanding small issue for me.

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+1741~gc024da6dac-dirty

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12

### Are you using OpenCL GPU in darktable?

No

**Comment by TurboGit** [comment]
I cannot reproduce... If you read this, can you test and report if you can or can't reproduce. TIA.

**Comment by dterrahe** [comment]
Maybe that _did_ fix it. I have recompiled and rebased a few more times since this morning and now it seems to have gone. Still same version number though, so I'm thoroughly confused (but very happy if it is solved! Thanks!!)

**Comment by dterrahe** [comment]
Oh, btw noticing that now that the "selected" shape is thicker to be easier to see, it is harder to discern the control points on it. Maybe just increase the `anchor_size` inside `dt_masks_draw_anchor()` by a smidge?

**Comment by TurboGit** [comment]
Yes, either increase anchor_size or decrease the selected shape a bit. I'll try to make proposal, now it is easy as all this is done for all shapes in a single routine.
