### ISSUE TITLE
DT 4.2.1 crash when starting

### ISSUE THREAD

**Issue by WYY367** [darktable-org/darktable#14205]
### Describe the bug

DT 4.2.1 crashes when starting, with or without opencl

CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz   2.70 GHz
GPU: NVIDIA GeForce 940MX

Refer to the debug log
[darktable-log.txt](https://github.com/darktable-org/darktable/files/11233571/darktable-log.txt)
Particularly, it notices the last line, `Magick: caught exception 0xC0000005 "Access violation"...`

Additional Info:
- I also tried the DT version 4.0 and 4.3, same issue
- If the .exe is opened with compatible mode in Win8, it works. However it is operated very slowly
- It works in the other laptop with similar configuration

### Steps to reproduce

1. open windows cmd, and redirect to the directory of DT
2. "darktable -d all"

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1 release

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 professional, version:	22H2, OS internal version: 19045.2846, Experience:	Windows Feature Experience Pack 120.2212.4190.0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce 940MX

**Comment by gi-man** [comment]
Did you had a previous version of darktable on this system?

**Comment by WYY367** [comment]
@gi-man
I think no, since I never open it normally before
I tried many times with different versions, and I also delete the .config or data folder then re-install, but it doesn't work

**Comment by gi-man** [comment]
There is no .config in Windows. Are you deleting the appdata folder `C:\Users\<username>\AppData\Local\darktable` ?  If yes, then you should have no images. Does it crash without any images?

**Comment by WYY367** [comment]
@gi-man Yes，what I mean .config folder is this: `C:\Users\<username>\AppData\Local\darktable`
It will crash without image
Particularly, it works when the .exe is opened with compatible mode in Win8, but it is operated very slowly, any ideas for this?

**Comment by lastsoulman** [comment]
Hi, I've the same problem, compatible mode in Win8 works but is very slow. Also tried the --disable-opencl but dt is still crashing. Using Win 10.0.19045 Build 19045, Nvidia Studio Driver 531.61.

**Comment by lastsoulman** [comment]
Log: Magick: caught exception 0xC0000005 "Access violation"...

**Comment by klaasmm** [comment]
Same problem here ,similar config.

- **CPU**: Intel(R) Core(TM) i7-12700K   3.60 GHz
- **GPU**: nvidia RTX 4080 - Studio Driver 531.61
- Windows 10 22H2 - 19045.2965
- Windows Feature Experience Pack 1000.19041.1000.0
- darktable 4.2.1

Crash right at start, no error, Logfile shows `Magick: caught exception 0xC0000005 "Access violation"...`
Tried with --disable-opencl
Deleted Temp and DB Directory

Problem remains.

**Comment by klaasmm** [comment]
Found the culprit - at least here: 

Darktable crashed when loading the gamepad drivers:

'1.522552 [lib_load_module] loading `gamepad' from c:\Program Files\darktable\lib\darktable/plugins/lighttable\libgamepad.dll
1.588281 [gamepad_open_devices] SDL initialized
Magick: caught exception 0xC0000005 "Access violation"...'

After deleting the libgamepad.dll, darktable was loading again. Seems to be some issue with my installed gamepads here, but as i don't need gamepad support anyways, i just deleted the dll.

**Comment by ptilopteri** [comment]
If no longer a problem, please consider closing the issue.

**Comment by WYY367** [comment]
It is still a problem by now

**Comment by halojenproductions** [comment]
This is happening to me as well.
- Windows 10
- CPU: 12th Gen Intel(R) Core(TM) i7-12700K   3.60 GHz
- GPU: Radeon RX 5500 XT
- Windows 10 22H2 - 19045.2965
- Windows Feature Experience Pack 1000.19041.1000.0
- darktable 4.2.1

AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt
```
========================================
version: darktable 4.2.1
start: 2023:05:29 19:26:31


(darktable.exe:40180): Gdk-WARNING **: 19:26:31.323: Could not open registry key 'SYSTEM\CurrentControlSet\Control\Keyboard Layouts\00001409'. Error code: 2
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
2.693978 [dev] took 0.116 secs (0.875 CPU) to load the image.
2.717312 [dev] took 0.134 secs (0.891 CPU) to load the image.
2.718743 [dev] took 0.135 secs (0.891 CPU) to load the image.
2.722079 [dev] took 0.140 secs (0.906 CPU) to load the image.
2.819667 [export] creating pixelpipe took 0.110 secs (0.500 CPU)
2.820187 [dev_pixelpipe] took 0.000 secs (0.000 CPU) initing base buffer [thumbnail]
2.825774 [dev_pixelpipe] took 0.006 secs (0.000 CPU) [thumbnail] processed `raw black/white point' on CPU, blended on CPU
2.831424 [dev_pixelpipe] took 0.006 secs (0.000 CPU) [thumbnail] processed `white balance' on CPU, blended on CPU
2.841367 [export] creating pixelpipe took 0.110 secs (0.500 CPU)
2.845409 [dev_pixelpipe] took 0.003 secs (0.000 CPU) initing base buffer [thumbnail]
2.854912 [dev_pixelpipe] took 0.009 secs (0.094 CPU) [thumbnail] processed `raw black/white point' on CPU, blended on CPU
2.855025 [export] creating pixelpipe took 0.111 secs (0.469 CPU)
2.862131 [export] creating pixelpipe took 0.106 secs (0.391 CPU)
2.862571 [dev_pixelpipe] took 0.008 secs (0.000 CPU) [thumbnail] processed `white balance' on CPU, blended on CPU
2.865156 [dev_pixelpipe] took 0.006 secs (0.266 CPU) initing base buffer [thumbnail]
2.871700 [dev_pixelpipe] took 0.009 secs (0.266 CPU) [thumbnail] processed `highlight reconstruction' on CPU, blended on CPU
2.877768 [dev_pixelpipe] took 0.012 secs (0.000 CPU) [thumbnail] processed `raw black/white point' on CPU, blended on CPU
2.877943 [dev_pixelpipe] took 0.006 secs (0.000 CPU) [thumbnail] processed `demosaic' on CPU, blended on CPU
2.884938 2.884945 [dev_pixelpipe] took 0.007 secs (0.250 CPU) [thumbnail] processed `white balance' on CPU, blended on CPU
[dev_pixelpipe] took 0.010 secs (0.250 CPU) initing base buffer [thumbnail]
2.886457 [dev_pixelpipe] took 0.055 secs (0.641 CPU) [thumbnail] processed `highlight reconstruction' on CPU, blended on CPU
2.898488 [dev_pixelpipe] took 0.013 secs (0.281 CPU) [thumbnail] processed `highlight reconstruction' on CPU, blended on CPU
2.899216 [dev_pixelpipe] took 0.013 secs (0.281 CPU) [thumbnail] processed `demosaic' on CPU, blended on CPU
2.900862 [dev_pixelpipe] took 0.016 secs (0.281 CPU) [thumbnail] processed `raw black/white point' on CPU, blended on CPU
2.907586 [dev_pixelpipe] took 0.009 secs (0.000 CPU) [thumbnail] processed `demosaic' on CPU, blended on CPU
2.913934 [dev_pixelpipe] took 0.013 secs (0.312 CPU) [thumbnail] processed `white balance' on CPU, blended on CPU
2.924656 [dev_pixelpipe] took 0.011 secs (0.000 CPU) [thumbnail] processed `highlight reconstruction' on CPU, blended on CPU
2.930678 [dev_pixelpipe] took 0.006 secs (0.281 CPU) [thumbnail] processed `demosaic' on CPU, blended on CPU
2.962673 [dev_pixelpipe] took 0.085 secs (1.703 CPU) [thumbnail] processed `denoise (profiled)' on CPU, blended on CPU
2.970339 [dev_pixelpipe] took 0.063 secs (1.172 CPU) [thumbnail] processed `denoise (profiled)' on CPU, blended on CPU
2.972320 [dev_pixelpipe] took 0.010 secs (0.000 CPU) [thumbnail] processed `lens correction' on CPU, blended on CPU
2.972916 [dev_pixelpipe] took 0.074 secs (1.172 CPU) [thumbnail] processed `denoise (profiled)' on CPU, blended on CPU
2.977229 [dev_pixelpipe] took 0.005 secs (0.297 CPU) [thumbnail] processed `exposure' on CPU, blended on CPU
2.981123 [dev_pixelpipe] took 0.011 secs (0.297 CPU) [thumbnail] processed `lens correction' on CPU, blended on CPU
2.981309 [dev_pixelpipe] took 0.051 secs (0.875 CPU) [thumbnail] processed `denoise (profiled)' on CPU, blended on CPU
2.981384 [dev_pixelpipe] took 0.000 secs (0.000 CPU) [thumbnail] processed `exposure' on CPU, blended on CPU
2.981590 [dev_pixelpipe] took 0.004 secs (0.000 CPU) [thumbnail] processed `input color profile' on CPU, blended on CPU
2.982497 [dev_pixelpipe] took 0.010 secs (0.297 CPU) [thumbnail] processed `lens correction' on CPU, blended on CPU
2.982843 [dev_pixelpipe] took 0.000 secs (0.000 CPU) [thumbnail] processed `exposure' on CPU, blended on CPU
2.982993 [dev_pixelpipe] took 0.001 secs (0.000 CPU) [thumbnail] processed `astrophoto denoise' on CPU, blended on CPU
image colorspace transform Lab-->RGB took 0.003 secs (0.000 CPU) [filmicrgb ]
2.989934 [dev_pixelpipe] took 0.009 secs (0.312 CPU) [thumbnail] processed `input color profile' on CPU, blended on CPU
2.990156 [dev_pixelpipe] took 0.007 secs (0.312 CPU) [thumbnail] processed `input color profile' on CPU, blended on CPU
Magick: caught exception 0xC0000005 "Access violation"...
```

**Comment by ralfbrown** [comment]
We've had two feature releases with many bugfixes since this report.  If this problem occurs in 4.6 or higher, feel free to reopen this issue or open a new one.

**Comment by charentejohn** [comment]
Reopening see this thread, still can't make it work with Win 11 and my setup, all details in link. 
https://discuss.pixls.us/t/opening-darktable-on-new-pc-just-immediately-starts-stops/41848/12
