### ISSUE TITLE
Dual demosaicing fails with old Canon Powershot G1

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#14201]
### Describe the bug

This camera doesn't have the normal RGGB CFA. Instead it has CYGM CFA.
![Skärmbild från 2023-04-14 11-40-14](https://user-images.githubusercontent.com/34200649/232008728-a03042c6-6e00-415d-8086-1e9e7112aec0.png)
![Skärmbild från 2023-04-14 11-39-59](https://user-images.githubusercontent.com/34200649/232008748-a9ec529a-b775-4372-88f4-8a366e71f992.png)

### Steps to reproduce

Change demosaicing method to AMaZE+VNG4 or RCD+VNG4. Zoom to 100%.
Raw sample https://raw.pixls.us/getfile.php/2073/nice/Canon%20-%20PowerShot%20G1%20-%20RAW%20(4:3).crw

### Where did you install darktable from?

OSB

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

64GB RAM, X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia RTX 2080 and GTX 1060

@jenshannoschwalm

**Comment by jenshannoschwalm** [comment]
Could you share a rawfile?

**Comment by PeterWem** [comment]
The link goes to raw.pixls.us.
