### ISSUE TITLE
RFC: clean-up the mask invertion support

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14213]
There is I think one confusing point.

### Context

I was asked about the difference about the toggle polarity (point 1 below) and invert mask (point 2 below) and I was not able to answer clearly.

### The situation

We can invert the masks:

1. Using `+/-` **toggle polarity** next to the selected masks:

![image](https://user-images.githubusercontent.com/467069/232200119-c5244c07-cb8b-42fb-852c-f1b886c1c1a6.png)

2. Using the combo when drawn masks is selected:

![image](https://user-images.githubusercontent.com/467069/232200167-06304def-2586-4b36-872c-eb50e16494d8.png)

But here is the confusing point.

For 1 it is documented (old 3.8 doc) that this is useful when parametric mask is used together with drawn mask:

> A polarity button (`+` and , `-` respectively) allows the user to toggle between the normal and the inverted state of the drawn mask, i.e. the opacity values get inverted – 100% becomes 0% and vice versa. You need this feature when combining drawn and parametric masks.

For 2 it is documented that this is to invert the drawn masks only:

> When “drawn mask” is selected there is an additional combobox to invert the mask by switching mask inversion “on” or “off”. 

And this is displayed only when drawn mask is selected. And when set to on, switching to drawn&parametric change the display as this feature is only for drawn masks. Confusing?

### Proposal

I think the tooltip must be updated to clearly say that the toogle polarity (point 1 above) is especially important when combining with parametric masks.

### Question

Is there a point keeping the invert drawn masks (point 2 above)?

### Refs

Ref: https://darktable.gitlab.io/doc/en/blending.html

**Comment by jenshannoschwalm** [comment]
> Is there a point keeping the invert drawn masks (point 2 above)?

I don't think so (too). This only  seems to **add** confusion to the masking interface.

**Comment by s7habo** [comment]
> Is there a point keeping the invert drawn masks (point 2 above)?

In combination with parametric masks, yes. 

Here is an example:

(1) Here I have selected everything that is red in the photo, with parametric mask. I have excluded the figure with the help of the drawn mask: 


![grafik](https://user-images.githubusercontent.com/38165484/232333440-297422c4-6336-4fdd-b005-90aca737ba11.png)


(2) When I _toggle the polarity of the drawn mask_, only the figure remains masked:

![grafik](https://user-images.githubusercontent.com/38165484/232333554-d97a5004-5b3d-4376-ad13-cd74721abd34.png)

(3) If I _additionally invert the drawn mask_ now, everything except the figure remains masked:

![grafik](https://user-images.githubusercontent.com/38165484/232333725-6e3e43f9-122b-4201-9530-41975b11b698.png)

(4) And if I now after the invert, reset the polarity of the drawn mask again, I get practically the inversion of the first masking (1).
![grafik](https://user-images.githubusercontent.com/38165484/232333849-7b297b7e-4e4a-4a0d-b4d6-516838fac70d.png)

**Comment by s7habo** [comment]
Just as an addition: 

If you only use the drawn mask, then it doesn't really matter whether you toggle the polarity of the mask or invert the mask. The result is the same. 

However, if you then decide to use the parametric mask to improve the masking, there is a difference between toggling the polarity and inversion.

**Comment by TurboGit** [comment]
> If you only use the drawn mask, then it doesn't really matter whether you toggle the polarity of the mask or invert the mask. The result is the same.

Yes, that's exactly the point. We are discussing the removal of "invert mask" in the drawn mask only UI (actually it is displayed only there). This will make the UI a bit lighter and will keep all current feature if I'm not mistaken. Hence the RFC here to be sure nothing is overlooked.

**Comment by s7habo** [comment]
> We are discussing the removal of "invert mask" in the drawn mask only UI (actually it is displayed only there). This will make the UI a bit lighter and will keep all current feature if I'm not mistaken.

Yes, that makes sense, but to make UI even simpler, I think it would be better not to have extra menus for drawn and parametric masks, since there is already a menu where both can be selected and combined as needed. 

There the inversion function makes more sense and is also integrated as an option for different combination possibilities between drawn and parametric masks:

![grafik](https://user-images.githubusercontent.com/38165484/232341253-42df89b6-86bc-43fd-b64f-ef33fec3b791.png)

**Comment by TurboGit** [comment]
> I think it would be better not to have extra menus for drawn and parametric masks, since there is already a menu where both can be selected and combined as needed.

I see, that's maybe another part we can simplify but I'm not sure of all the implication about this one yet. Maybe later...
