### ISSUE TITLE
Blocky mask artefacts

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#14215]
### Describe the bug

In the darkroom, masks sometimes exhibit blocky artefacts. This affects not only the mask preview, but the processed image (in darkroom).
May be related to https://github.com/darktable-org/darktable/issues/10090.
Requires OpenCL; is potentially influenced by screen resolution.

### Steps to reproduce

1. Get the raw and XMP from https://tech.kovacs-telekes.org/files/2023-04-15-blocky-masks
2. Open in darkroom
3. Artefacts appear
4. Change displayed items (top/bottom bars), resize the window -> the artefacts change.

### Expected behavior

No artefacting.

### Logfile | Screenshot | Screencast

Screencasts (gif, mp4) at https://tech.kovacs-telekes.org/files/2023-04-15-blocky-masks

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+1773~g7cb0b15617

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.10

### Describe your system?

KDE, XOrg

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6GB; 470.182.03-0ubuntu0.22.10.1 

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I can reproduce this by deleting darktablerc and adding the single line:

    darkroom/ui/0/header_visible=FALSE

Self-compiled (gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0), currently with RelWithDebugInfo, as I have been experiencing crashes (no result from that investigation, yet).

**Comment by jenshannoschwalm** [comment]
Immediately recognized and an issue also on other modules on fedora 37, also nvidia.
No idea yet ... never observed this before ... canT reproduce on other images so far ???

**Comment by kofa73** [comment]
You mean you're able to reproduce with this image, but not with others?
I can reproduce it with the both images uploaded for https://github.com/darktable-org/darktable/issues/10090. So this issue could be a duplicate -- and it also means a bisect is pretty much hopeless, we have had it for more than a year and a half, and I don't know if it ever worked.

**Comment by apostel338** [comment]
> also nvidia.

I can add Tumbleweed and AMD to the list. I also get heavy blocky artifacts with the rw2 and xmp from kofa. And I could reproduce it with other RAWs, e.g. with own ones from my Nikon Z50. Although by far not that strong. Look at the top of the head:

https://user-images.githubusercontent.com/96216629/232251540-8b7424d3-4194-4e78-8236-3f2aaf9a78e8.mp4

Seems like I need an photo with hard edges between dark and bright areas. In kofas sample it disappears when turning off `chromatic aberration` and `profiled denoise`. In my sample it's enough to turn off `chromatic aberration`.

Tuning up CA seems to strongly encrease the artifacts. Look at the area between the eyes:

https://user-images.githubusercontent.com/96216629/232251792-4b40637e-41d7-45f0-8218-d3c0c4470936.mp4

**Comment by kofa73** [comment]
It seems the CPU path is also affected. This is with --disable-opencl:
![image](https://user-images.githubusercontent.com/3177739/232253428-b0560321-82d3-4c1e-860c-f3ea130a86bb.png)

**Comment by jenshannoschwalm** [comment]
Further tests show you need much less modules/history to trigger the issue, i suggest to use this 
[KOFA73.RW2.xmp.txt](https://github.com/darktable-org/darktable/files/11241131/KOFA73.RW2.xmp.txt)

xmp file as it takes much less resources and thus might be easier to test.

My testing here: after disabling "chromatic aberration" there is no issue, can you confirm this?

**Comment by kofa73** [comment]
_chromatic aberrations_ on:
![image](https://user-images.githubusercontent.com/3177739/232278214-bf3cb307-8668-4183-85fe-74442adaf52a.png)

_chromatic aberrations_ off:
![image](https://user-images.githubusercontent.com/3177739/232278328-c55098cb-fdd9-4d51-9703-1fb7432488a4.png)

**Comment by kofa73** [comment]
With your simplified xmp, I get artefacts (depends on the zoom level, but reproducible).

**Comment by s7habo** [comment]
I can confirm it in Ubuntu Studio 22.04 with darktable 4.3.0+1872~gd2c7145fd.

For me the artifacts are visible/occur when _featering radius is turned on/increased_ in mask refinement:


without:

![grafik](https://user-images.githubusercontent.com/38165484/233768256-f04c7cc2-8718-44bc-8aaf-6f7066adea05.png)


with:

![grafik](https://user-images.githubusercontent.com/38165484/233768333-60c0e0fa-7077-4543-bafa-6adcfe4a1d43.png)

**Comment by jenshannoschwalm** [comment]
Yes, on the track already ...

**Comment by jchnkl** [comment]
Hi, I'm affected by this as well for quite some time know. If I recall correctly it started out at some 4.x release. Sorry that I didn't get around to file a bug report yet. Actually I was going to do it today, but I found this. To add some information:

Disabling the `raw / regular chromatic abberations` modules didn't help for my example image.
However, I experimented a bit by toggling the modules on / off and found the `highlight construction` module to be the culprit in my case.

I also went through the various modes:

* `inpaint opposed` => artifacts
* `reconstruct in LCh` => artifacts
* `clip highlights` => no artifacts
* `segmentation based` => artifacts
* `guided laplacians` => no artifacts

Hope this helps to narrow this down a bit more. I can provide my RAW + XMP as well, just give me a note. Thanks!

**Comment by jenshannoschwalm** [comment]
I looked into this somewhat deeper. The interesting thing is, i can reproduce some artefacts in **any** module doing "feather in". The likelyhood of such artefacts seems to depend on what input data we have for that module. It always takes place at sharp dark<->bright transitions. (This might be the basis why ca correction or highlights reconstruction both are related to such errors - but as said it can be reproduced with both modules off)

Best seen is the issue with the "mask visualizer button" toggled on to see the mask.

As this issue is only happening at sharp transitions is suspect there might be some sort of "stability problem" or even a bug in the guided filter used here. @rabauke do you have an opinion here as the author of that algo?

**Comment by kofa73** [comment]
I thought it'd be easier to reproduce and investigate using a synthetic black-and-white image. Had to rename the XMP.
This one immediately triggered it.
![bw](https://github.com/darktable-org/darktable/assets/3177739/490ad826-ea76-461c-8f62-831cc3834ae3)
[bw.png.xmp.txt](https://github.com/darktable-org/darktable/files/11561219/bw.png.xmp.txt)

**Comment by kofa73** [comment]
Interestingly, some combos seem to be immune. I just used squares.

[squares.zip](https://github.com/darktable-org/darktable/files/11571588/squares.zip)

**Comment by kofa73** [comment]
[more-squares.zip](https://github.com/darktable-org/darktable/files/11571723/more-squares.zip)
Updated XMPs for all, maybe more visible + red/green/blue agains black/white

**Comment by jenshannoschwalm** [comment]
About being immune. I think is related to the chosen "guide" while feathering. Something to look into for 4.6

**Comment by kofa73** [comment]
Among these, only red vs magenta seems to be immune. I did not try all combinations, of course.

Interestingly:
- solid white is also affected, screenshot:
![image](https://github.com/darktable-org/darktable/assets/3177739/1fddf6b9-e32a-4412-b308-fcce8ccbe36e)
- however, the exported file (without resizing, as the input was 1000x1000) is NOT!
![white](https://github.com/darktable-org/darktable/assets/3177739/7193c1b5-97e9-4bd6-b484-12f509f4803b)

![white](https://github.com/darktable-org/darktable/assets/3177739/5e6e64e0-c1df-4cfc-8373-74cd24202078)
[white.png.xmp.txt](https://github.com/darktable-org/darktable/files/11578757/white.png.xmp.txt)

**Comment by gi-man** [comment]
I experienced this issue yesterday. Fedora 38 KDE, Nvidia 535.54.03, current master 4.5.0~git151.4745a4f4.

Without any edits to the modules, turning off OpenCL in preferences removed the issue. Turn it back on returned it. Deleting .cache had no effect. Doing adjustments to the module mask had not effect (remains). 

I then reset the module (TE) and re did the mask without artifacts. I cannot reproduce it using a similar mask on the same image.

**Comment by jenshannoschwalm** [comment]
We know about the issue now and i can reproduce with and without CL. It's for sure related to the guided filter ... Didn't look deeper in the code yet.

**Comment by kofa73** [comment]
I can confirm that with white.png, adding +15 EV, then -18 EV in another instance, creating a random mask and applying feathering immediately reproduces the issue with and without OpenCL on 4.5.0+158~g9b0bf88e73.

**Comment by jenshannoschwalm** [comment]
As I see it, the strong gradient at some borders and a large feathering make the guided filter algo go somewhat out-of-bounds.

**Comment by ralfbrown** [comment]
I tried out the white.png and associated xmp.  Looks like either a race condition or uninitialized value to me, as the corruption doesn't always appear.

**Comment by jenshannoschwalm** [comment]
We always see some rectangle part gone wild, size and position depend on CPU vs gpu.

And - at least me - only to be seen at strong image gradients.

**Comment by ralfbrown** [comment]
The guided filter does internal tiling to keep memory requirements low (it needs 13 floats per pixel), hence the corruption in squares.  The size of the tiles depends in part on the filter radius, to ensure that the entire support for an  output pixel is present in the input tile.

**Comment by jenshannoschwalm** [comment]
> The guided filter does internal tiling to keep memory requirements low

Yes is saw that in the code but didn't _understand_ the implications and how a guide gradient might interfere here.

**Comment by jchnkl** [comment]
Is there some sort of workaround?

I tried downgrading to darktable-4.0 (via flatpak) but that didn't seem to help. I tried `--disable-opencl`, toyed around with removing feathering but darktable produces different output for different zoom levels and exported pictures don't match up the display either.

I'm hitting this bug with almost every picture I'm trying to edit. Darktable's currently close to unusable for me and at the very least extremely frustrating to work with. Would it help to offer a bounty to speed up the resolution of this issue?

**Comment by gi-man** [comment]
I think the only work around is to limit large feathering radius until a fix is found.

**Comment by jchnkl** [comment]
In my experience that doesn't help much. Out of curiosity I checked out 3.8.1 (the earliest flatpak'ed version) and tried that. Could be I'm hitting a different bug here because turning of masks entirely did not make a visible difference.

After playing around a bit more I think it's related to the `local contrast` module. Please take a look at the following screenshots. To the left the exported image (Full res TIF) displayed with Geeqie, to the right darktable's preview):

1) When zoomed in, the contrast differs notably, depending on zoom level:
![Screenshot from 2023-08-20 14-03-15](https://github.com/darktable-org/darktable/assets/1392715/a52c1805-7ae5-462b-a83b-00197b346078)

2) However, on certain zoom levels the pictures look almost the same
![Screenshot from 2023-08-20 14-04-18](https://github.com/darktable-org/darktable/assets/1392715/99bcbcc1-ac61-4e60-9798-f3e9f135755e)

3) All masks disabled, note that the pictures still differ in contrast
![Screenshot from 2023-08-20 14-08-44](https://github.com/darktable-org/darktable/assets/1392715/4f0d0185-30e1-4c67-8b9e-3f5392552c25)

4) After disabling `local contrast` the pictures look the same
![Screenshot from 2023-08-20 14-24-47](https://github.com/darktable-org/darktable/assets/1392715/82b670c0-b8ca-4cfa-b1aa-46a9b65db52b)

I use two instances of `local contrast`, one masked and one without:

![Screenshot from 2023-08-20 14-31-25](https://github.com/darktable-org/darktable/assets/1392715/21c678ac-eb0f-4fca-859d-e3814a7d7c78)

Turning off the mask does not make difference for the outcome described above! Hence I suspect this might be a different bug or a user error. In that case I'd be happy about some advice. I tried with 3.8.1 and 4.4.2 (latest flatpak version). There is _no_ difference. Both version generate the following OpenCL error for `local contrast`:

```
   48.3955 [dt_opencl_enqueue_kernel_2d] kernel 34 on device 0: CL_MEM_OBJECT_ALLOCATION_FAILURE
    48.3955 [local laplacian cl] couldn't enqueue kernel! CL_MEM_OBJECT_ALLOCATION_FAILURE
    48.6234 [pixelpipe_process_CL]       [export]       bilat                  (   0/   0) 4932x6533 scale=1.0000 --> (   0/   0) 4932x6533 scale=1.0000 couldn't run module on GPU, falling back to CPU
```

Thanks!

**Comment by kofa73** [comment]
Please continue the discussion on pixls.us, if it's not really relevant to this issue. Let's not hijack this discussion.

**Comment by jchnkl** [comment]
> @jchnkl: Please continue the discussion on pixls.us, if it's not really relevant to this issue. Let's not hijack this discussion.

Well, is it relevant? I don't know, I'm seeing inconsistent output from darktable which appears to be a bug. Nevertheless I think these issues are intertwined as I'm also seeing artifacts on sharp edges with the `sharpen` tool. I've openend #15092 15092

**Comment by Pizzacutter-at-tty3** [comment]
> Hi, I'm affected by this as well for quite some time know. If I recall correctly it started out at some 4.x release. Sorry that I didn't get around to file a bug report yet. Actually I was going to do it today, but I found this. To add some information:
> 
> Disabling the `raw / regular chromatic abberations` modules didn't help for my example image. However, I experimented a bit by toggling the modules on / off and found the `highlight construction` module to be the culprit in my case.
> 
> I also went through the various modes:
> 
> * `inpaint opposed` => artifacts
> * `reconstruct in LCh` => artifacts
> * `clip highlights` => no artifacts
> * `segmentation based` => artifacts
> * `guided laplacians` => no artifacts
> 
> Hope this helps to narrow this down a bit more. I can provide my RAW + XMP as well, just give me a note. Thanks!

I have the same issue and my preview has artifacts, but not the export:

![image](https://github.com/darktable-org/darktable/assets/30387161/ed4e33b1-6ef5-48a9-a4df-924d85a43861)
![image](https://github.com/darktable-org/darktable/assets/30387161/5b1e3487-2e1a-4ede-b1f2-7c6a68e6b10f)

It's an image with some heavy processing, mostly _'color balance rgb'_ with feathered masks.
It happens on many images, mostly in the low areas of the image, artifacts change with every action (zoom, pan, parameters, display mask, ...)

**Comment by kofa73** [comment]
Still reproducible with https://github.com/darktable-org/darktable/issues/14215#issuecomment-1562264485 if OpenCL is on (NVidia 1060/6 GB, driver 525.147.05, Ubuntu 23.10, 64 GB RAM).

**Comment by kofa73** [comment]
Shall I open a new one for the remaining OpenCL issues?

**Comment by TurboGit** [comment]
> Shall I open a new one for the remaining OpenCL issues?

Yes please!
