### ISSUE TITLE
RGB levels mismatched on reading DNG from Fujifilm PixelShift Combiner

### ISSUE THREAD

**Issue by lCardosoSantos** [darktable-org/darktable#14221]
### Describe the bug

Loading a DNG raw file from Fujifilm PixelShift Combiner results in a strange behavior, where the histograms of each RGB channel seem to be scaled and moved randomly. Windows codec for DNG files seems to render a picture that is more accurate to expected.

The following image is what windows10 Renders without any adjustment:
![DSCF0852HighRes+color](https://user-images.githubusercontent.com/11529026/232252378-661c1b54-db4b-4ac1-96e3-7b5fc760b64f.jpg)

The following image is what darktable renders without any adjustment:
![DSCF0852HighRes+color (Custom)](https://user-images.githubusercontent.com/11529026/232252547-d35e3b02-79d3-465c-8fb8-88b08217a93d.jpg)

This is what the levels look like:
![image](https://user-images.githubusercontent.com/11529026/232252589-b2e0d2be-58cc-4b44-a314-6568f5f07b47.png)

After applying auto-levels on the channels independently, I get a somewhat better curve, but I am inclined to believe it is not a best solution.
![DSCF0852HighRes+color_01 (Custom)](https://user-images.githubusercontent.com/11529026/232252680-d1028da0-1091-4e34-a355-073c6577ebf0.jpg)

### Steps to reproduce

1. Using a fujifilm X-T5 and the pixel shift option, take a picture and combine it using Ver.1.3.0. There is no difference from using the accurate color or highres+color options;
2. Import generated DNG on Darktable;
3. Image renders as previously described;

### Expected behavior

Darktable should produce a starting point similar to a straight out of the camera NEF file.

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro Version	22H2

### Describe your system?

*Device specs*
Processor	AMD Ryzen 9 7900X 12-Core Processor               4.70 GHz
Installed RAM	64.0 GB (63.1 GB usable)
GPU: RTX 4080

*Windows Specifications*
Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎24/‎2023
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This problem is a bit more than a 1GB worth of raw files, I am willing to share them, if you guys point me a proper place to upload that you can use.

**Comment by gi-man** [comment]
I dont think pixel shift is currently supported by dt. I tried to confirm, but I was not clear.

**Comment by kmilos** [comment]
Please share a sample, both here (via some cloud storage link), and on [RPU](https://raw.pixls.us/).

**Comment by lCardosoSantos** [comment]
@kmilos 
Output of the command you asked!

[DSCF0852HighRes+color.txt](https://github.com/darktable-org/darktable/files/11262753/DSCF0852HighRes%2Bcolor.txt)

Original File is downloadable here (I also uploaded to raw.pixls.us, but I am not sure how to lick back to them):
https://mega.nz/file/TI5nnT7I#dRiDNiCK0E6NhCeUEM0sutF1EWI_gvY41Vo8Rq4aD3s

Let me know if I can do anything else to help!

@gi-man , you might be correct, how do I test for it?


Sorry, new to collaborating on github, why is my comment closing the issue?

**Comment by kmilos** [comment]
It is also possible that dt is somehow prioritizing the normal X-T5 mode values `black="1020" white="16383"` instead of the DNG ones, so just try adjusting the raw black/white point module first to 4096 and 65535 instead...

**Comment by lCardosoSantos** [comment]
Manually setting the black levels does produce a very nice picture to use as start-point for the editing.

![image](https://user-images.githubusercontent.com/11529026/232819822-14e52277-0882-4b7b-85b9-6a704c9003f1.png)


So, is it that the raw pixelshifted file have RGB values for each pixels instead of the bayer (or Trans-something that Fuji uses)?

Let me try an alternate link for you: https://drive.google.com/file/d/1stznyEF1-Sd9yTR7W_ZWpThrvu6YtTp_/view?usp=sharing

Ideally, I would like to have a pixel-shift DNG file like this to start with the correct (?) black levels. I am curious, is there any philosofical reason for darktable to not behave like this? #

**Comment by kmilos** [comment]
> I would like to have a pixel-shift DNG file like this to start with the correct (?) black levels.

Great, now you can potentially save a preset (see manual) and keep using it.

> is there any philosofical reason for darktable to not behave like this?

Nope, it's a known issue as I linked to above.
