### ISSUE TITLE
Panasonic DMC-FZ330

### ISSUE THREAD

**Issue by dalee524** [darktable-org/darktable#14226]
My Panasonic camera is known in the UK as the DMC-FZ330 but in the US it is known as the DMC-FZ300. The lens correction module has the lens information in the database but only against the DMC-FZ300 camera identifier which therefore requires manual selection every time I use the module on a new photograph. Could the DMC-FZ330 please be added to the database as a copy of the DMC-FZ300 as they are exactly the same camera just using different identifiers in different regions (or should this request be sent to Lensfun instead?).

**Comment by Nilvus** [comment]
If it's about correction module, so it's for Lensfun. Think about closing that issue.

**Comment by dalee524** [comment]
Will submit to Lensfun

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/darktable/issues/2515 and https://github.com/darktable-org/darktable/issues/11230

Please search before opening new issues.

**Comment by kmilos** [comment]
Please also cross-reference your upstream reports, e.g. as https://github.com/lensfun/lensfun/issues/2022 so other users could find it. And you probably should have left it open until it actually gets implemented so others could benefit as well.

**Comment by dalee524** [comment]
Sorry, this is the first time filing an issue. I note that it has been
re-raised as #2023 so I presume I don't need to do anything further?

**Comment by kmilos** [comment]
You do not.

Please be careful with references as well - you just referenced (and created a link between) an unrelated _darktable_ issue 2023, while you were meaning to link to _lensfun_ 2023...
