### ISSUE TITLE
jpeg - scene referred - exposure

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14227]
### Describe the bug

The exposure is not properly set when reloading history.

### Steps to reproduce

0. Select the scene-referred workflow
1. go to darkroom with a jpeg
2. open the exposure module
3. reset history

See that exposure is properly set to 0.7 but that the displayed image does not have the exposure applied. To check:

4. On exposure module set exposure to 1
5. Set it back to 0.7 and see that the image is way lighter than on point 3 above.

### Expected behavior

honor the exposure setting

### Where did you install darktable from?

self compiled

### darktable version

current master : ccbd5131dddba654b961ad553bf1a7c9210e48c1

### What OS are you using?

Linux

### What is the version of your OS?

GNU/Debian sid

### Are you using OpenCL GPU in darktable?

Yes

**Comment by elstoc** [comment]
> See that exposure is properly set to 0.7

I don't think exposure should default to 0.7 for jpegs. That setting is related to reasonable raw defaults for filmic/scene-referred.

**Comment by TurboGit** [comment]
> > See that exposure is properly set to 0.7
> 
> I don't think exposure should default to 0.7 for jpegs. That setting is related to reasonable raw defaults for filmic/scene-referred.

That's not the point of this issue.

**Comment by TurboGit** [comment]
Closing, the module is not activated so that's why the exposure is not set. I missed that, probably a bit too tired :(
