### ISSUE TITLE
With  PR 10846 merged I cannot switch tag collections via double click.

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14231]
With this PR merged I cannot switch tag collections via double click.

With commit ccbd5131dddba654 prior to this everything works fine.

_Originally posted by @zisoft in https://github.com/darktable-org/darktable/issues/10846#issuecomment-1510449139_

**Comment by ralfbrown** [comment]
Commit 84967a2ea0 breaks things.  Quick fix is to revert it, and I'll take a closer look when I have time (possibly not until next weekend).

**Comment by ralfbrown** [comment]
The culprit appears to be this change:
```
--- a/src/common/collection.c
+++ b/src/common/collection.c
@@ -2395,8 +2395,8 @@ void dt_collection_update_query(const dt_collection_t *collection, dt_collection
                                  (dt_collection_get_filter_flags(collection) & ~COLLECTION_FILTER_FILM_ID));
 
   /* update query and at last the visual */
-  if(maybe_changed)
-    dt_collection_update(collection);
+  if(maybe_changed && collection->clone)
+    dt_collection_update(collection);  // originals get updated by signal handler in selection.c
 
   // remove from selected images where not in this query.
   sqlite3_stmt *stmt = NULL;
```

**Comment by TurboGit** [comment]
> Commit [84967a2](https://github.com/darktable-org/darktable/commit/84967a2ea0856c57244db093bf794c533b9fddc9) breaks things. Quick fix is to revert it, and I'll take a closer look when I have time (possibly not until next weekend).

Ok, I'll test the proposed fix and if still broken I'll revert. I cannot change collection at all on my side.

**Comment by TurboGit** [comment]
> The culprit appears to be this change:

Thanks, I have reverted this and it seems that collection is working ok now.

**Comment by TurboGit** [comment]
In fact I have now reverted the whole following commit too as there is other issues.

```
fd29a56eae564eb77e587adeaa05cfa5faa3f6a4 is the first bad commit
commit fd29a56eae564eb77e587adeaa05cfa5faa3f6a4
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Tue Jan 11 02:00:09 2022 -0500

    avoid calling dt_collection_update when changed property is not a criterion

 src/common/collection.c   |  8 +++++---
 src/common/selection.c    |  2 --
 src/dtgtk/thumbtable.c    |  6 +++---
 src/libs/collect.c        |  9 +++++----
 src/libs/copy_history.c   |  8 ++++----
 src/libs/tools/timeline.c | 12 ++++++------
 6 files changed, 23 insertions(+), 22 deletions(-)
```

- Go to collection with a set of image
- In the text search enter a value to select a single image
- See that it is display on the hinter message that a single image is selected
- ... But the central part sill display the whole collection

This issue makes dt unusable.
