### ISSUE TITLE
Reproduced with the Lua script. crash happens in `imageop.c:dt_iop_show_hide_header_buttons()`

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14233]
Ok, reproduced with the Lua script. The crash happens in `imageop.c:dt_iop_show_hide_header_buttons()` on the `gtk_widget_set_visible` call below:

```
  GList *button;
  for(button = g_list_last(children);
      button && GTK_IS_BUTTON(button->data);
      button = g_list_previous(button))
  {
    gtk_widget_set_no_show_all(GTK_WIDGET(button->data), TRUE);
    gtk_widget_set_visible(GTK_WIDGET(button->data), show_buttons && !always_hide && !disabled);
    gtk_widget_set_opacity(GTK_WIDGET(button->data), opacity);
  }
```

The strange thing is that if you add a shortcut for the same style in global actions under Styles section there is no problem.So looks like some bad interaction with Lua... Really no idea why :( 

So I'll merge this which at least avoid the crash.

_Originally posted by @TurboGit in https://github.com/darktable-org/darktable/issues/14216#issuecomment-1511004598_

**Comment by wpferguson** [comment]
I'll keep the script and the styles around just in case I come up with an idea later
