### ISSUE TITLE
Cannot parse dates from JPEG files, and may block import of some XMP sidecars

### ISSUE THREAD

**Issue by orthorhombic** [darktable-org/darktable#14244]
### Describe the bug

On some JPEG files, after importing, the time is shown as `Mon 01/01/1 12:00:00 AM`. For these files, changing the data in their respective FIlename.xmp sidecars (in contrast to, and in absence of Filename.jpg.xmp) does not seem to impact the import process. Therefore, this seems to indicate something in the JPEG's metadata is breaking, blocking, or overriding the XMP sidecar data from being processed. 

The expected result is Darktable should be able to import the JPEG with a correctly parsed date, and the XMP sidecar would override values stored in the JPEG.

This seems pretty similar to #13355 and so perhaps a fix to this may be found in the same upstream functions.

### Steps to reproduce

On the lighttable view, click add to library and select one of the problematic files with metadata as described below. Upon import, hover over the file to see the capture time showing 1-01-01 00:00:00. Even when the XMP sidecar is populated with data from a working file, it does not change the outcome. Samples below were mostly taken from adjacent pictures captured during the same shoot - so same camera, settings, subject, conditions, etc.

Admittedly, it's still a bit unclear to me what is causing this, but I suspect it may be the length of the date fields.

### Expected behavior

Darktable should be able to parse all of the above files

### Logfile | Screenshot | Screencast

Output was generated with the following command: `exiv2 -pa Filename.jpg | grep Date`

File 1 (Does not work):
```
Exif.Image.DateTime                          Ascii      20  2005:10:01 00:00:00
Exif.Photo.DateTimeOriginal                  Ascii      20  2005:10:01 00:00:00
Exif.Photo.DateTimeDigitized                 Ascii      20  2005:10:01 00:00:00
Xmp.xmp.ModifyDate                           XmpText    22  2005-10-01T06:12-04:00
Xmp.xmp.CreateDate                           XmpText    22  2005-10-01T06:12-04:00
Xmp.xmp.MetadataDate                         XmpText    29  2009-05-20T01:59:29.843+04:00
Xmp.exif.DateTimeOriginal                    XmpText    22  2005-10-01T06:12-04:00
Xmp.exif.DateTimeDigitized                   XmpText    22  2005-10-01T06:12-04:00
```

File 2 (Works):
```
Exif.Image.DateTime                          Ascii      20  2005:10:01 06:15:01
Exif.Photo.DateTimeOriginal                  Ascii      20  2005:10:01 06:15:01
Exif.Photo.DateTimeDigitized                 Ascii      20  2005:10:01 06:15:01
Xmp.xmp.ModifyDate                           XmpText    25  2005-10-01T06:15:01-04:00
Xmp.xmp.CreateDate                           XmpText    25  2005-10-01T06:15:01-04:00
Xmp.xmp.MetadataDate                         XmpText    29  2009-05-20T01:59:34.531+04:00
Xmp.exif.DateTimeOriginal                    XmpText    25  2005-10-01T06:15:01-04:00
Xmp.exif.DateTimeDigitized                   XmpText    25  2005-10-01T06:15:01-04:00
```

File 3 (Does not work):
```
Exif.Image.DateTime                          Ascii      20  2005:09:08 00:00:00
Exif.Photo.DateTimeOriginal                  Ascii      20  2005:09:08 00:00:00
Exif.Photo.DateTimeDigitized                 Ascii      20  2005:09:08 00:00:00
Xmp.xmp.ModifyDate                           XmpText    22  2005-09-08T18:46-04:00
Xmp.xmp.CreateDate                           XmpText    22  2005-09-08T18:46-04:00
Xmp.xmp.MetadataDate                         XmpText    29  2009-05-20T02:25:42.468+04:00
Xmp.exif.DateTimeOriginal                    XmpText    22  2005-09-08T18:46-04:00
Xmp.exif.DateTimeDigitized                   XmpText    22  2005-09-08T18:46-04:00
```

File 4 (Works):
```
Exif.Image.DateTime                          Ascii      20  2005:09:08 18:45:57
Exif.Photo.DateTimeOriginal                  Ascii      20  2005:09:08 18:45:57
Exif.Photo.DateTimeDigitized                 Ascii      20  2005:09:08 18:45:57
Xmp.xmp.ModifyDate                           XmpText    25  2005-09-08T18:45:57-04:00
Xmp.xmp.CreateDate                           XmpText    25  2005-09-08T18:45:57-04:00
Xmp.xmp.MetadataDate                         XmpText    29  2009-05-20T02:25:40.531+04:00
Xmp.exif.DateTimeOriginal                    XmpText    25  2005-09-08T18:45:57-04:00
Xmp.exif.DateTimeDigitized                   XmpText    25  2005-09-08T18:45:57-04:00
```

File 5 (Does not work):
```
Error: Directory Canon with 9472 entries considered invalid; not read.
Exif.Image.DateTime                          Ascii      20  2010:01:11 12:35:33
Exif.Photo.DateTimeOriginal                  Ascii      20  2010:01:11 11:39:41
Exif.Photo.DateTimeDigitized                 Ascii      20  2010:01:11 11:39:41
Xmp.xmp.ModifyDate                           XmpText    28  2010-01-11T12:35:33.58-05:00
Xmp.xmp.CreateDate                           XmpText    28  2010-01-11T11:39:41.58-05:00
Xmp.xmp.MetadataDate                         XmpText    29  2010-01-15T18:19:33.716+05:00
Xmp.exif.DateTimeOriginal                    XmpText    28  2010-01-11T11:39:41.58-05:00
Xmp.exif.DateTimeDigitized                   XmpText    28  2010-01-11T11:39:41.58-05:00
```

### Where did you install darktable from?

darktable installed via snap (https://snapcraft.io/darktable)

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

darktable installed via snap (https://snapcraft.io/darktable)
OS : Linux - kernel 5.19.0-40-generic
Linux - Distro : Ubuntu 22.04
Memory : 64gb
Graphics card : Nvidia A2000

### Are you using OpenCL GPU in darktable?

No

**Comment by gi-man** [comment]
What are you using to generate the initial xmp file?

The  `Xmp.` date fields are not consistent in your export.  Some have hh:mm, others have hh:mm:ss.##  The ones that you say works are the ones with hh:mm:ss format

**Comment by orthorhombic** [comment]
File 3 and File 4 above were taken 3 seconds apart. The difference with the EXIF time is also weird and I haven't been able to explain that.  Those metadata extracts are just a subset of pictures with issues. 

I think the XMP variation comes from these files having been touched by some old version of Lightroom. It seems like when the timestamp ended in `:00` it happened to truncate those in the XMP.

If folks have ideas on how I might narrow down where this is running into problems, I'm open to suggestions.

**Comment by kmilos** [comment]
> If folks have ideas on how I might narrow down where this is running into problems, I'm open to suggestions.

Somewhere in `src/common/exif.cc` 😉 

Sorry, no time to dig into this right now...

**Comment by victoryforce** [comment]
Wow, that's interesting.

Well, it's clearly a blunder of the sanitizer. So, @orthorhombic, you're right, this problem is similar to the one you mentioned.
Remembering this function, I can already say for sure what the error is. I'll fix it now.

**Comment by victoryforce** [comment]
Now, after a much closer look at this code (execution flows from reading timestamp strings to their parsing and conversion into an internal representation of time), I have a question: why was this sanitizer written at all? It does things that are either unnecessary or wrong (and the wrong ones are then fixed right before parsing). It's strange...
