### ISSUE TITLE
Missing modules in "select parts to copy" window.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#14245]
### Describe the bug

Editing some photos I saw that a module added in the darkroom as part of the develop, is missing in the "select parts to copy" window of the lighttable.

I created a second module of color calibration, and used with a preset B/W: ILFORD DELTA 1000 as you can see in the screenshots, placing the mouse over the icon in the lighttable, it's present as part of the develop. But when I press the selective copy... in the history stack, the module is missing.

### Steps to reproduce

1. go to the darkroom
2. create a second copy of the color calibration and select a preset
3. go to the lighttable
4. place the mouse over the icon to see the modules list
5. press the icon "selective copy..." in the history stack module
6. with the "select parts to copy" window open, see the error: the module is missing.

### Expected behavior

It's supposed that every module should be in this window to be selected.

### Logfile | Screenshot | Screencast

![Screenshot from 2023-04-18 01-11-08](https://user-images.githubusercontent.com/67672868/232681731-af5ab887-489d-4120-915a-60385d894df6.png)

![Screenshot from 2023-04-18 01-12-01](https://user-images.githubusercontent.com/67672868/232681907-179e22ca-aba1-4cde-98ff-13950ba18103.png)

![Screenshot from 2023-04-18 01-12-26](https://user-images.githubusercontent.com/67672868/232681931-ad02f729-e5df-4493-b112-1f64910419b5.png)

### Commit

----

### Where did you install darktable from?

From Suse repositories
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

### darktable version

4.3.0~git1824.a0a921db-9772.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Describe your system?

darktable version : 4.3.0~git1824.a0a921db-9772.1
OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.2.7-200.fc37.x86_64
Uptime: 2 days, 22 hours, 44 mins
Packages: 2239 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.4
WM: Mutter
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark-solid [GTK2/3]
Icons: Mkos-Big-Sur [GTK2/3]
Terminal: alacritty
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 6506MiB / 32016MiB
Graphics driver:
OpenCL installed: Yes
OpenCL activated: Yes
Xorg: Yes

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

530.41.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

**LUA scripts**
--------------------------------------------------------------------------------------------------
**contrib**
autocrop
change_group_leader
CollectHelper
color_profile_manager
copy_attach_detach_tags
display_in_darkroom
enfuseAdvanced
ext_editor
fujifilm_auto_settings
fujifilm_dynamic_range
fujifilm_ratings
gimp
harmonic_armature_guide
HDRMerge
hugin
image_stack
image_time
LabelsToTags
OpenInExplorer
photils
quicktag
rate_group
rename_images
RL_out_sharp
select_untagged
smart_styles
transfer_hierarchy

**examples**
api_version
InitialWorkflowModule

**official**
copy_paste_metadata
delete_long_tags
enfuse
image_path_in_ui
import_filter_manager
import_filters
save_selection
selection_to_pdf

**tools**
executable_manager

**wpferguson**
adjust_time
export2collection
postsharpen

**Comment by pehar1** [comment]
I was able to reproduce once in about 10 attempts with 4.3.0+1828~g2ac3425247 on Ubuntu 22.04. It happened for me once when the "selective copy" dialog was just completely filled with items (no space left on the bottom, no scroll bar). Now I can't reproduce anymore, even not if I add more instances (getting scroll bar in "selective copy" dialog), and removing these instances again to come back to the "dialog just completely filled" state.

**Comment by difrkaguilar** [comment]
After the last update I don't saw the issue again. So I'll going to close the report.
