### ISSUE TITLE
Canon EOS R6 Mk II

### ISSUE THREAD

**Issue by martinma64** [darktable-org/darktable#14243]
Hi,
I just uploaded a RAW Image to
https://raw.pixls.us/ !

**Comment by MStraeten** [comment]
for canon r6 mll support the camera must be also supported by libraw (https://www.libraw.org/)

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/pull/13684

Please search before opening new issues.

**Comment by mkubecek** [comment]
> Hi, I just uploaded a RAW Image to https://raw.pixls.us/ !

So did I, back in February (a full set of 8 files). Unfortunately the site still does not show them and as one does not provide contact for feedback, I have no idea why. And I couldn't find any contact so I cannot ask either. So let's hope you will be more lucky.

> for canon r6 mll support the camera must be also supported by libraw

Looked into this too; the libraw update policy is to only provide new camera support in major releases which come once in a year and a half to two years. As 0.21 was released in December 2022, the best we can hope for is June 2024.

**Comment by MStraeten** [comment]
or earlier since the dt team also includes snapshots if they included new cameras - so be patient ...
