### ISSUE TITLE
issue with the first module of the "select parts to copy" window 

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#14246]
### Describe the bug

Please check the video

### Steps to reproduce

1. go to the darkroom
2. create a base develop
3. go to the lighttable
4. press the icon "selectrive copy..." in the history stack module
5. with the "select parts to copy" window open, see the first module of the list, wile select the others and see how the first module change it's name with the name of the selected one.

### Logfile | Screenshot | Screencast

![Peek 2023-04-18 02-26](https://user-images.githubusercontent.com/67672868/232690523-fcef9f59-592d-42d4-a31e-033b96caeb1d.gif)

### Commit

--------------

### Where did you install darktable from?

From Suse repositories
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

### darktable version

4.3.0~git1828.2ac34252-9774.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Describe your system?

darktable version : 4.3.0~git1828.2ac34252-9774.1
OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.2.7-200.fc37.x86_64
Uptime: 2 days, 22 hours, 44 mins
Packages: 2239 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.4
WM: Mutter
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark-solid [GTK2/3]
Icons: Mkos-Big-Sur [GTK2/3]
Terminal: alacritty
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 6506MiB / 32016MiB
Graphics driver:
OpenCL installed: Yes
OpenCL activated: Yes
Xorg: Yes

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

530.41.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

**LUA scripts**
------------------------------------------------------------------------------------

**contrib**
autocrop
change_group_leader
CollectHelper
color_profile_manager
copy_attach_detach_tags
display_in_darkroom
enfuseAdvanced
ext_editor
fujifilm_auto_settings
fujifilm_dynamic_range
fujifilm_ratings
gimp
harmonic_armature_guide
HDRMerge
hugin
image_stack
image_time
LabelsToTags
OpenInExplorer
photils
quicktag
rate_group
rename_images
RL_out_sharp
select_untagged
smart_styles
transfer_hierarchy

**examples**
api_version
InitialWorkflowModule

**official**
copy_paste_metadata
delete_long_tags
enfuse
image_path_in_ui
import_filter_manager
import_filters
save_selection
selection_to_pdf

**tools**
executable_manager

**wpferguson**
adjust_time
export2collection
postsharpen

**Comment by pehar1** [comment]
Not able to reproduce with 4.3.0+1828~g2ac3425247 on Ubuntu 22.04.

**Comment by TurboGit** [comment]
What is that !!!! Good news is that I cannot reproduce with current master, it looked quite worrisome...

**Comment by difrkaguilar** [comment]
After the last update I don't saw the issue again. So I'll going to close the report.
