### ISSUE TITLE
DT 4.3.0 details treshold mask crashes darktable

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#14257]
### Describe the bug

If you apply details threshold mask, go to the lighttable, back to darkroom and then change the mask again darktable crashes.

This happens regardless of which module is used. The same happens when OpenCL is turned off.

### Steps to reproduce

1. open a raw file in darkroom, 
2. choose a module
3. set the details threshold mask, and make some change in the module
4. go to lighttable
5. open again the same raw file in darkroom
6. open same module with the details treshold mask and make some change in the mask
7. darktable crashes

### Expected behavior

darktable should not crash if you switch to lighttable after applying the details treshold make, go back to darkroom and change the values of the mask there

### Logfile | Screenshot | Screencast

Output of the terminal with "darktable -d all":

[darktable_crash_.txt](https://github.com/darktable-org/darktable/files/11275517/darktable_crash_.txt)

Short video:

https://user-images.githubusercontent.com/38165484/233144430-670d0a24-9403-47d5-8994-bdb4019b7a2e.mp4

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+1847~g02b06da8e

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-70-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070/PCIe/SSE2

**Comment by jenshannoschwalm** [comment]
Got the reason for the crash already ... will fix asap
