### ISSUE TITLE
Crash on startup (Fedora 38) LLVM ERROR

### ISSUE THREAD

**Issue by Tjill** [darktable-org/darktable#14268]
### Describe the bug

After upgrading from Fedora 37 to 38, Darktable instantly crashes when I launch it. This only happens with the RPM version of the software, the Flatpak version works fine. 

The terminal gives the following output: 

```
: CommandLine Error: Option 'use-dbg-addr' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Abandon (core dumped)
```

### Steps to reproduce

1. Launch Darktable (in command line: "darktable" or "amdgporun darktable")
2. Crash

### Logfile | Screenshot | Screencast

[Darktable_Log.txt](https://github.com/darktable-org/darktable/files/11283728/Darktable_Log.txt)

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

OS: Fedora Linux 38 (Workstation Edition) x86_64 
Host: MS-7C04 1.0 
Kernel: 6.2.11-300.fc38.x86_64 
Shell: bash 5.2.15 
Resolution: 2560x1440 
DE: GNOME 44.0 
WM: Mutter 
CPU: Intel i5-8600K (6) @ 4.300GHz 
GPU: AMD ATI Radeon RX Vega 64 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD ATI Radeon RX Vega 64 + AMDGPU-PRO OpenCL driver by GloriousEggRoll

**Comment by ralfbrown** [comment]
It's a known bug in F38's LLVM (see #14145).  Unfortunately, darktable can't do anything about it.
You might be able to work around the issue if you have multiple OpenCL drivers installed and can uninstall all but the one actually used.
