### ISSUE TITLE
Left lighttable panel flickering with the import module.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#14285]
### Describe the bug

When I use the lighttable import module with the "add to library", "copy & import..." or "copy & import from camera" buttons, and darktable start to import images, the left panel begins to flicker for every imported image.

Note. See the video.

It doesn't mater if I use the buttons to add to library or the others copy & import, the left panel start to flicker until the last image is imported.

### Steps to reproduce

1. go to lighttable import module.
2. use any of the import buttons.
3. select the path to the images.
4. start to import.
5. see the issue.

### Expected behavior

The left panel do not suppose to flicker

### Logfile | Screenshot | Screencast

https://user-images.githubusercontent.com/67672868/233684883-7a5d99e9-67d8-44dd-a72f-15c21c6cb01c.mp4

### Commit

--------------

### Where did you install darktable from?

From Suse repositories
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

### darktable version

4.3.0~git1908.18ccd0c7-9811.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Describe your system?

darktable version : 4.3.0~git1908.18ccd0c7-9811.1
OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.2.7-200.fc37.x86_64
Uptime: 2 days, 22 hours, 44 mins
Packages: 2239 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.4
WM: Mutter
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark [GTK2/3]
Icons: Mkos-Big-Sur [GTK2/3]
Terminal: alacritty
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 6506MiB / 32016MiB
Graphics driver:
OpenCL installed: Yes
OpenCL activated: Yes
Xorg: Yes

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

530.41.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

**LUA scripts**
------------------------------------------------------------------------------------

**contrib**
autocrop
change_group_leader
CollectHelper
color_profile_manager
copy_attach_detach_tags
display_in_darkroom
enfuseAdvanced
ext_editor
fujifilm_auto_settings
fujifilm_dynamic_range
fujifilm_ratings
gimp
harmonic_armature_guide
HDRMerge
hugin
image_stack
image_time
LabelsToTags
OpenInExplorer
photils
quicktag
rate_group
rename_images
RL_out_sharp
select_untagged
smart_styles
transfer_hierarchy

**examples**
api_version
InitialWorkflowModule

**official**
copy_paste_metadata
delete_long_tags
enfuse
image_path_in_ui
import_filter_manager
import_filters
save_selection
selection_to_pdf

**tools**
executable_manager

**wpferguson**
adjust_time
export2collection
postsharpen

**Comment by dterrahe** [comment]
BTW completely separate from this; I love the thoroughness of your bug reports; they are very helpful! One small idea would be, since you have a lot of lua scripts installed/active, to also/only report if the issue also exists if you are running _without_ any scripts. It would make the report shorter but, more importantly, if we can't reproduce your issue we won't be tempted to blame it on the scripts :-)

And if the problem _does_ go away if no scripts are running, _then_ it would useful to find out which one/several scripts trigger it...

**Comment by difrkaguilar** [comment]
Thanks to all you for the new template to do the reports, it's nice to fill the info.

> we won't be tempted to blame it on the scripts :-)

jjj don´t worry I'll go tho put more attention to details (I Just disabled the lua scripts using the button provided for this purpose, later I've to search how to activate it again).
