### ISSUE TITLE
Lens not detected on old edits - SOLVED: use "refresh EXIF"

### ISSUE THREAD

**Issue by JohannMaierhofer** [darktable-org/darktable#14280]
### Describe the bug

I have a Nikon lens (Nikon AF-P DX Nikkor 10-20mm f/4.5-5.6G VR) used at a Nikon D5500. Darktable lens correction module reports that it did not find the lens, just the camera is detected. The lens field lists the value 168.
I can then select the lens manually from the menu and then the corrections are applied.
The lens is included in the lensfun file slr-nikon.xml.
When I extraxt the exif data from the RAW file then it reports excactly the lens name as it appears in slr-nikon.xml.
The output of exiv2 is the following:
**exiv2 -p a DSC_1663.NEF  | grep Lens**
Exif.Nikon3.LensType                     Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  10-20mm F4.5-5.6
Exif.Nikon3.LensFStops                 Undefined   4  4.66667
Exif.NikonLd3.LensIDNumber      Byte        1  Nikon AF-P DX Nikkor 10-20mm f/4.5-5.6G VR
Exif.NikonLd3.LensFStops             Byte        1  F4.7
I do not know whether it is a Darktable issue or a lensfun issue.
For test purposes i remove the entry "        <model>Nikon AF-P DX Nikkor 10-20mm f/4.5-5.6G VR 168</model>" in slr-nikon.xml. This had no effect. teh lens field still shows the entry 168.

I also have the lens "Nikon AF-S DX Nikkor 18-140mm f/3.5-5.6G ED VR". This lens is correctly detected.
The output of exiv2 is the following:
**exiv2 -p a DSC_1661.NEF  | grep Lens**
Exif.Nikon3.LensType                         Byte        1  D G VR
Exif.Nikon3.Lens                             Rational    4  18-140mm F3.5-5.6
Exif.Nikon3.LensFStops                       Undefined   4  5.33333
Exif.NikonLd3.LensIDNumber                   Byte        1  Nikon AF-S DX Nikkor 18-140mm f/3.5-5.6G ED VR
Exif.NikonLd3.LensFStops                     Byte        1  F5.3

### Steps to reproduce

1. Open the Nikon RAW file (xxx.NEF) shot with the lens "Nikon AF-P DX Nikkor 10-20mm f/4.5-5.6G VR"
2. Enable the lens correction module
3. **Now the module reports the the lens is not found**
4. Right click in lens field
5. From menu select camera "Nikon"
6. From lens menu select "Nikkor AF-P 10-20mm f/4.5-5.6G DX VR"
7. Now the lens field displays "Nikon, Nikkor AF-P 10-20mm f/4.5-5.6G DX VR"
8. lens corrections are applied

### Expected behavior

Darktable should finds the lens automatically.

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1-4

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 23.04, also 22.10

### Describe your system?

Intel I5-13500 (same on previous CPU Intel I5-750), 32G Memory, X11window system

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel UHD Graphics 770, same on old PC Nvidia GTX 750TI

**Comment by JohannMaierhofer** [comment]
I think I found my problem but still do not know how I got into this situation. I is not just with one picture but with a lot. It is for pictures that I created in the year 2018 and they have been edited at that time. I just opened them again for some rework e.g. using the new workflow with filmic.
If I have a look into the image information window, I can see that the information shown for the lens is the integer 168. This is probably why darktable does not find the lens in the database.
I now deleted the picture in darktable lighttable view from the darktable database. That kept the .xmp file. Then I imported the picture again. Now the image information window reports the lens "Nikon AF-P DX Nikkor 10-20mm f/4.5-5.6G VR" and the lens gets automatically found by the lens correction module.

Thus my workaround is to delete the related images and import them again. Thanks that it keeps the done editing information by taking them from the kept .xmp file.

**Comment by kmilos** [comment]
It could be because the exiv2 library in 2018 was missing this lens...

You can also try force re-reading the metadata instead of removing/importing again... In lightroom view:

![image](https://user-images.githubusercontent.com/4973094/233616386-a2aa91c6-baaa-4dcb-8edd-6b24026b7ee4.png)

**Comment by JohannMaierhofer** [comment]
Thank for your information. Yes, the refresh of the EXIF data also solves the issue.

**Comment by kmilos** [comment]
Great. Please consider closing the issue then.
