### ISSUE TITLE
Color temperature of white balance and color calibration modules differ

### ISSUE THREAD

**Issue by JohannMaierhofer** [darktable-org/darktable#14295]
### Describe the bug

When color calibration module is disabled and just the white balance module is used, I can set the white balance to use camera settings. In the new work flow the white balance module is set to camera refernce point and in the color calibration module I also can select to use the camera settting.
In both cases the images look similar. I also extracted the embedded jpg from the RAW file and thy look as having the same white balance.
The strange thing is that the color calibration module reports a color temperature that is about 1000K less than what the white balance module reports. 
**Why is this difference? What temperature is correct?**
When I then do an automatic white balance in the color calibration module using the pipette then it select a higher temperature, more to what the camera reports. But now the image becomes more red what is expected to to the higher temperature.
**Is now the auto calculated temperature of the color calibration module ok but just diplayed wrongly?**
My camera is a Nikon D5500 with .NEF raw files.

### Steps to reproduce

1. I open the RAW file with default with the modern work flow.
2. White balance is set to camera reference point and color calibration module is set to use camera setting.
![Screenshot_1](https://user-images.githubusercontent.com/126261667/233775030-1dcac0a9-148f-4ba4-8ebe-6caeec58debf.png)
![Screenshot_2](https://user-images.githubusercontent.com/126261667/233775060-e2be02a7-e8bf-41a6-84a7-663b73140ab9.png)

3. Now I disable the color calibration module and change in the white balance module the setting to use camera setting
![Screenshot_3](https://user-images.githubusercontent.com/126261667/233775167-7a2a30b9-cbbe-4291-8109-1c72c151432f.png)
4. As can be seen, the color temperatures displayed are quite different but the images look the same. Thus they should have the same white balance.
5. Now I do an auto white balance in the color calibration module using the pipette.
![Screenshot_5](https://user-images.githubusercontent.com/126261667/233775272-769f246d-77cd-4b02-95b1-eed600b51d20.png)
6. Now the temperature gets higher but also the image more red.

I can repeat this also with other images with similar effect. Image shot at daylight

![Screenshot_14](https://user-images.githubusercontent.com/126261667/233775437-965aafdc-34a8-4689-beec-c1421be95215.png) Color calibration module
![Screenshot_13](https://user-images.githubusercontent.com/126261667/233775445-48b5b797-6afa-4ca5-9fed-12b94cd78b6a.png) White balance module with same look 
![Screenshot_15](https://user-images.githubusercontent.com/126261667/233775449-f1ffb4da-b8a0-4df5-b423-d2d2de60c2a0.png) Auto white balance in color calibration module - now with much more red color. The color temperature seems to match daylight but image is now too red

### Expected behavior

Solve discepancy in color temperature

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1-4

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 23.04

### Describe your system?

Gen Intel® Core™ i5-13500, 32Gb RAM, X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Mesa Intel® UHD Graphics 770

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I had the same observation on my older PC (Intel I5-750, 16Gb RAM, Linux, X11) and also already with previous Darktable versions.

**Comment by wpferguson** [comment]
The manual explains this, https://docs.darktable.org/usermanual/4.2/en/module-reference/processing-modules/color-calibration/

**Comment by JohannMaierhofer** [comment]
If this is by intention then I close the issue. Sorry for creating this.
