### ISSUE TITLE
color calibration auto-detect WB bad interaction with pixpipe cache

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#14291]
### Describe the bug

If selecting one of the "AI" auto-detect choices in the "illuminant" dropdown for color calibration, the module needs to run on the "full" pipe to compute the new white balance.  But with pixelpipe caching, it doesn't actually do so in many cases, so it either has no effect or produces a black image as in #12382.

### Steps to reproduce

For a black image:
1. open an image in darkroom and choose one of the "AI" auto-detect options in color calibration.
2. reset the module
3. switch to lighttable view and back to darkroom
4. choose the same auto-detect option again

### Expected behavior

The auto-detect code should be run and produce a valid white balance.

### Commit

This has probably been around since color calibration was first added, but the better caching now makes it more obvious.

### Where did you install darktable from?

self compiled

### darktable version

current master - 4.3.0+1909

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 8.1, GCC 10.4

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Invalidating the pixelpipe cache should fix this.  A faster (for the user) approach would be to have the auto-detect code run standalone, but that would require not just getting the module input from the cache but also running the pixelpipe up to that point in case of a miss.

**Comment by jenshannoschwalm** [comment]
Nice catch! We might want a function to invalidate all cachelines with a higher iop_order than the current module ...

**Comment by ralfbrown** [comment]
Yes, it occurred to me after posting that we don't need to invalidate the entire cache, just color calibration's output (to force it to run) and everything later.

**Comment by jenshannoschwalm** [comment]
This all seems to be fixed with #14291, maybe we can later revert the unclear fix done in #12382
