### ISSUE TITLE
Tag search does not work across tag hierarchy

### ISSUE THREAD

**Issue by nhrdl** [darktable-org/darktable#14301]
### Describe the bug

Tag images something like `park|california|yoesemite`. Now try to search for the tag yosemite in collections view. Does not work

### Steps to reproduce

Search for a tag with 2nd or more depth level. Example in the tag hierarchy 'park|california|yosmite|' try searching for yosemiite tag.

### Expected behavior

Show images with tag yosemite

### Where did you install darktable from?

OSB

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

**Comment by pehar1** [comment]
Use the wildcard `%yosemite` and it works.

**Comment by Nilvus** [comment]
It's not a bug but actual "wanted" behavior. I had already ask about changed that, but I fear this will not change until a time. See: #12471
I close that one as it's not a bug and so a duplicate. Feel free to amend and comment my feature request enhancement on #12471 to ask for update if you want. Thanks!
