### ISSUE TITLE
Add in the export button the name of the preset that is active.

### ISSUE THREAD

**Issue by arturoisilvia** [darktable-org/darktable#14319]
With darktable-4.3.0+1954~g80bfae38fd-win64.exe on windows 11

I have several presets in the export module.

Would it be useful to add in the export button the name of the active preset?

![Exportacion2](https://user-images.githubusercontent.com/55624244/234178601-2558a9fd-ecfb-40fc-8a25-6db99fb39ce1.jpg)

**Comment by Nilvus** [comment]
I also have several presets there. It's the user who need to know which one is selected. Adding that to the button is a bad way to me. It will made size of the button switched quite often (and could so have bad visual impacts). And why overload a button for a thing that is quick to check before exporting. I'm against that move.

**Comment by arturoisilvia** [comment]
Ok, we'll leave it as it is.
