### ISSUE TITLE
[FR] configuration option to disable gphoto2 tethering

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#14314]
Many/most dt users do not tether their cameras, yet we have a thread calling gphoto2 to scan for newly-connected cameras every ~3 seconds.  On some systems, this is reported to result in crashes due to the large number of shared/dynamic libraries that libgphoto loads and unloads during the scan (#13221).

The discussion for the above issue suggested adding a preference for whether to enable tethering or not, and Ansel has entirely removed tethering.

**Comment by jenshannoschwalm** [comment]
You are aware that disabling gphoto tethering would also disable importing from sd card? No problem for me btw.

**Comment by ralfbrown** [comment]
Yes, you'd have to mount the camera manually and navigate to the mount point in the copy&import dialog - assuming that your OS hasn't been set  up to auto-mount it.

**Comment by jenshannoschwalm** [comment]
I just can say that taking care about gphoto devices plugged in & out is an absolute mess. Many more issues than this one.
A button to mount or unmount was evaluated - we had that somehow - but if you miss to do so you are simply lost.

That's what the polling is for.

1. We might stop polling on an error ?
2. Disable whole gphoto stuff by a config option would be another option, what this FR is about.

**Comment by Nilvus** [comment]
I completely understand the purpose of that FR and I completely agree about the issue behind gphoto. I'm ok to point 1 and 2 but if point 2 is disabled by default, I think that we need to take care about users who import from SD card with not good software knowledge (so UI point).

I'm not sure about the way as I don't know how this works internally.

But as probably few users use tethering, could it possible to just automatically enable gphoto when opening copy&import dialog window (for those who import from SD card/camera, without having to know and go on darktable preferences) and disable it after import is done (and copy&import dialog window is closed).

For such proposal, of course, take care too about CPU/time to enable/disable it on such thing. i don't know what it requires.

**Comment by parafin** [comment]
Who and why uses import from SD card by gphoto baffles me. Don't most OSes mount SD cards when inserted?

And copy&import button is not related to gphoto. There is a separate "copy & import from camera" button.

**Comment by Nilvus** [comment]
Oh, miss that thing. I made confusion and forget that separate button (that I never see). So no issue on that, gphoto2 can be disable for that. Thanks @parafin for your comment. Sorry for the noise so!
