### ISSUE TITLE
Port filmic v7

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14320]
Filmic v7 was recently introduced into Ansel. This issue is to consider/discuss porting it to darktable.

**Comment by rawfiner** [comment]
A quick comment: I think maxrgb is not versatile enough. In challenging images (highlight reconstruction needed, or chromatic aberrations), luminance Y usually gives the best results. For this reason, I would like to keep the possibility to choose which norm to use if possible.
Note that I didn't have time to test yet though.

**Comment by TurboGit** [comment]
We probably to look more in the code but I think the goal of v7 was to move away specific color preservation algorithm. Indeed v7 is not the default upstream, it is us to decide if we want it to be the default or not. For that we well need more testing, and even maybe take the decision after the PR is merged to gain more field testing.

**Comment by elstoc** [comment]
>  Indeed v7 is not the default upstream, it is us to decide if we want it to be the default or not. For that we well need more testing

If you want v7 to be field tested, it should probably be made the default in master. We can always put it back to v6 before the release if it's really not received well.

**Comment by TurboGit** [comment]
> If you want v7 to be field tested, it should probably be made the default in master.

Good idea and done.
