### ISSUE TITLE
Unable to process  .3FR files from a Hasselblad X2D 100C

### ISSUE THREAD

**Issue by kkempter-getswift** [darktable-org/darktable#14345]
### Describe the bug

I am trying to upload a few raw samples from a Hasselblad X2S 100C
When I try to import the .3FR files into darktable today I get this message when I try to edit them:

darktable could not load ‘FILENAME’, switching to lighttable now.
please check that the camera model that produced the image is supported in darktable
(list of supported cameras is at [camera support | darktable](https://www.darktable.org/resources/camera-support/)).

This camera is not yet supported,

### Steps to reproduce

1. open darktable
2. select 'add to library' and navigate to the directory where the Hasselblad 3FR files live
3. double click an image in lighttable to enter darkroom

### Expected behavior

load the file

### Where did you install darktable from?

darktable.org

### darktable version

3.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 36

### Describe your system?

Fedora 36, Dell XPS17

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I uploaded 2 samples to here:

https://raw.pixls.us/?thankyou

could not upload here due to size limitations

**Comment by LebedevRI** [comment]
Thank you for the sample!

**Comment by kkempter-getswift** [comment]
Of course, let me know if you could use added samples

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/darktable/commit/2600f777e1c1d28158c93484ab9eef4f9b61d973
