### ISSUE TITLE
The collections window opens with the ability to change size with the double arrow - but gets locked later

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#14364]
### Describe the bug

The collections window in lighttable opens with a flexible size, i.e. it can be enlarged downwards with the double arrow.
After the first return from darkroom, the window is smaller vertically, and the double arrow has no effect in increasing the size downwards.

### Steps to reproduce

1. open darktable
2. open an image in darkroom
3. return from darkroom
4. the problem has occured in lighttable

### Expected behavior

The collections window should keep the original size, the vertical size should be adjustable.

### Logfile | Screenshot | Screencast

A sceen copy will not show the problem.

### Commit

Read above.

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+1944-g299ba908fc

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro, version 10.0.19045 Build 19045

### Describe your system?

This feature worked in 4.2.1. My system has good capacity and speed.

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

No OpenCL used, but the GPU is NVIDIA GeForce GTX 1650

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

File type is not relevant.
Rename images.

**Comment by dterrahe** [comment]
Please check if this is already fixed in current matter (after #14357).

**Comment by KIRSJ** [comment]
14357:
"looks fine:

    doesn't resize on switch between lighttable and darkroom and back
    resizes to place for 8 items if the to be displayed list contains less items
    resizes up to 20 items if a short list is expanded to more items (e.g. on expanding folders)
    size can be controlled manually if even more items are available"

- it looks like the issue I reported in 14364 has been fixed with the above behavior.

**Comment by dterrahe** [comment]
Thanks for checking and confirming. I'll close this issue.
