### ISSUE TITLE
Darktable XCF export is missing EXIF data

### ISSUE THREAD

**Issue by TimiSanchez** [darktable-org/darktable#14369]
### Describe the bug

By using the export to XCF option within lighttable and darktable the EXIF data of the original image is not stored, although the EXIF data checkbox is set within the "edit metadata exportation" window.

### Steps to reproduce

1. load any image format within darktable (tested with jpg and arw)
2. navigate to export within lighttable or darktable
3. select file format XCF
4. check that the EXIF checkbox is set within the export preferences
5. click export
6. open the XCF export with gimp and check metadata at "Image/Metadata/View Metadata"
7. everythin is empty and nothing was exported from darktable 

### Expected behavior

darktable should export all the selected metadata as configured within the export preferences

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

nothing

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
> 4\. check that the EXIF checkbox is set within the export preferences

Because there is no fine-grained control of metadata export for XCF, you have to check all the boxes (opt-in), not just Exif...

Btw, unfortunately this currently works for XCF only on master branch/upcoming 4.4 version.

**Comment by TimiSanchez** [comment]
thanks for the quick response!

I have checked now all the boxes (EXIF, metadata, geo tags, tags incl. all subs, hierarchical tags, develop history) and there is still nothing included.

Any further suggestions?

**Comment by ptilopteri** [comment]
from kmilos' reply:
   > Btw, unfortunately this currently works for XCF only on master branch/upcoming 4.4 version: #13425

you are not running "master".

**Comment by Nilvus** [comment]
As this is fixed on master and will be in 4.4, no need to let that opened. @TimiSanchez: 4.4 will be around in summer solstice.
