### ISSUE TITLE
Reset history stack uses defaults from module view preset, not from settings (documentation issue?)

### ISSUE THREAD

**Issue by janhieber** [darktable-org/darktable#14370]
The tutorial for scene-based editing tells one to:
1. Set _scene-referred_ in settings
2. Reset the history stack
3. Set _workflow: scene-referred_ in modules group

The reset of the history stack seems to use the defaults from the module group preset, not from darktable settings.

So when you follow the tutorial (overview > workflow > processing), the first time you do this the history is reset to whatever was set before in module group, the next time it will then use the correct setting from scene-referred preset.

Not sure how the reset is supposed to take it's defaults from. Either the documentation may be changed (order of instructions) or the reset history stack may be changed.

**Comment by MStraeten** [comment]
what exactly is the issue? how to reproduce?
A reset of the history stack causes it to be built up with the default modules defined by darktable preferences pixel workflow setting and then uses the modules default setting - or a setting the user defined as default based on defined conditions.
it doesn't change module group setting. 
What do you expect based on the documentation?

**Comment by janhieber** [comment]
Let's assume darktables preference pixel workflow is set to something other than _workflow: scene-referred_.
When you do the tutorial the 1st time, it instructs you to reset the history stack first and later to set the preference pixel workflow.

So the first time you do the tutorial (as with many beginners I think) it will use whatever darktable has set as default, in my case it was not _workflow: scene-referred_.

After editing many pics I imported new pics and noticed that the history stack is completely different after reset. So I discarded all edits and did them again with the (now) correct reset settings.

Other than that, let me thank you all for you wonderful development! It's a charm to work with darktable, I really enjoy it! And the manual is also awesome, even for beginners.

**Comment by MStraeten** [comment]
darktable doesn’t change the history stack after switching between default workflow settings. If you edit an image with display referred workflow, the history stack follows these workflow - ore more precise the initial module order - even if you change the default workflow later. Of course you can change the module order later, but that will break your edit. But that’s up to you, darktable won’t do this since it’s design philosophy to support  even edits done with old versions long before scene referred workflow was introduced.

the manual is quite precise:
_If you have previously viewed or edited the image in the darkroom view, start by discarding history (click the reset button in the [history stack](https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/darkroom/history-stack/)). This will reapply defaults using your new settings and provide a clean starting point for editing._
A clean starting point is a reset to default modules.

**Comment by janhieber** [comment]
Sorry I think that's not what I meant.

My point was: When starting darktable with default settings and importing images, later (with or without reset), they will have a history stack not from the screne-referred setting but something else (which was set before). When you are new to darktable you either miss that completely or you may notice much later.

So following the tutorial step by step gives you a much different default history stack on your first images compared to everythign you import/reset after you once selected _workflow: scene-referred_.

But it's just a small thing and maybe I'm getting something completely wrong here. So you may just close it.

**Comment by janhieber** [comment]
So I reconstructed with fresh Darktable user settings.

I import an image, as described in the tutorial and the history stack is this:
![a](https://user-images.githubusercontent.com/1897479/236156758-f4d4ad22-b637-4630-8bee-27de58a8a5e6.jpg)

So you follow the tutorial and set the module workflow to scene-referred.

Later when you import images or you reset the history, you will have this:
![b](https://user-images.githubusercontent.com/1897479/236157006-0e2c45c0-0edd-4095-a7e3-994a07778e98.jpg)

IMO we might want to suggest setting the module workflow before importing pictures, as this seems to affect the default history or we might want to suggest to do another reset of the history after setting the module workflow.

Otherwise it seems a bit nondeterministic what your first images will have as base history stack.

**Comment by janhieber** [comment]
I just realize that this is maybe completely not important because it only shows the order in which changes were made, but not the order in which modules are applied to the image. So I will close it... 

I'm sorry, got confused by this topic but it's highlighted in the documentation that it's important to understand it :)

Anyway, I really like darktable!
