### ISSUE TITLE
Fujifilm XH1

### ISSUE THREAD

**Issue by Bertl68** [darktable-org/darktable#14375]
DT 4.2.3 does not support my Fujifilm Cameras XH1 and X10. Until DT 3.9. they work both probably.
So, please integrate the Camera again. With --list-cameras, there is no Fujifilm Camera listed at all!
Thanks very much, also for a short reply.
Kind regards
Bertl

**Comment by LebedevRI** [comment]
I don't believe that camera was ever supported.

**Comment by LebedevRI** [comment]
Actually wait, how is it not supported? In which way?
It's supported since dt3.8 or so.

**Comment by elstoc** [comment]
> DT 4.2.3 does not support my Fujifilm Cameras

There are no darktable releases with that version number.

**Comment by victoryforce** [comment]
@Bertl68 There is no `--list-cameras` option in darktable, perhaps you meant the gphoto2 client, which does have such an option. So please clarify what you meant, support for processing of images from these cameras, or support for tethering. Also, please clarify what X10 is - is it old Finepix X10 or X-S10.

**Comment by difrkaguilar** [comment]
I've an X-H1 and it was supported since 3.8 more less. It's my main camera to work with dt.

**Comment by Bertl68** [comment]
@difrkaguilar, which DT version do you use currently? My Fuji X-H1 work with DT from 2018 till Mid March this year! But will not be recognized since my current version DT 4.2.1., updated automatically.
@victoryforce, a) fujifilm X10 is an older compact camera wich I also use in addition to my Fuji X-H1.
b) yes, you're right I meant the option with gphoto2. this advice was from the workaround on https://docs.darktable.org/usermanual/4.2/de/tethering/troubleshooting
@all, If i followed the instructions of the link above, USB is detected, but not my camera....
so, perhaps anyone have an advice for my problem?
Kind regards
Bertl

**Comment by Bertl68** [comment]
Dear All,
I don't know why and how, but I tried it just again and tatatata, DT works as I was used to.
Sorry for this trouble, but I've done nothing else than the last time, where both of my cameras wouldn't be recognized.
very kind regards
Bertl
