### ISSUE TITLE
Framing (borders.c): can't enter custom ratio in dropdown

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#14374]
### Describe the bug

The tooltip for the Aspect dropdown (not the Aspect ratio slider) says one can enter a custom ratio in the form w:h.  This is not actually possible.  While one *can* enter a text string instead of selecting a predefined entry, the text is not actually evaluated - it is displayed for the dropdown but the aspect ratio slider is not updated.

### Steps to reproduce

1. Open the Framing module on an image
2. Click (or right-click) on "aspect"
3. Type a value - decimal number, w:h, or w/h
4. See the typed text displayed when the dropdown collapses
5. Note that the aspect ratio slider has not changed

### Expected behavior

The behavior should match the tooltip, or custom text should be disabled for the dropdown and the tooltip for the aspect ratio slider updated.  A one-line change in common/calculator.c would permit the bauhaus to accept "7:6" as well as "7/6" for ratios.

### Where did you install darktable from?

self compiled

### darktable version

master 4.3.0+2056

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 8.1

### Are you using OpenCL GPU in darktable?

None

**Comment by dterrahe** [comment]
Fixed by #14461
