### ISSUE TITLE
Metadata Editor discarding changes without confirmation

### ISSUE THREAD

**Issue by Dakes** [darktable-org/darktable#14392]
### Describe the bug

When you have unsaved (unapplied) changed in the metadata editor (title, description etc.) and are adding or removing tags, using the tagging module, your changes will be discarded without asking for confirmation. 

### Steps to reproduce

1. Select any image
2. change any metadata field in "metadata editor"
3. don't press apply
4. add or remove a tag in the tagging module

### Expected behavior

Darktable should save/apply the changes or ask for confirmation, before discarding them. 

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
Dupicate of #13829.
