### ISSUE TITLE
Question: sRAW vs RAW when applying preset

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14403]
I found out that a preset for RAW is not applied to a DNG from EOS1200D as the DNG is sRAW.

This is because the presets are checking:

```
int dt_image_is_raw(const dt_image_t *img)
{
  return (img->flags & DT_IMAGE_RAW);
}
```

But this includes only DT_IMAGE_RAW and not DT_IMAGE_SRAW.

I think the routine should be:

```
int dt_image_is_raw(const dt_image_t *img)
{
  return (img->flags & (DT_IMAGE_RAW | DT_IMAGE_S_RAW));
}
```

@jenshannoschwalm  : Can you comment on this? Am I mistaken that this issue has been introduced when adding sRAW in commit 3f804be3832037a62ecb3457c951f409a957627c?

@kmilos : You may want to comment on this too.

**Comment by jenshannoschwalm** [comment]
Cant check on the computer but iirc there is a check for matrix supported? Which would include colored sraws but not monochromes.

**Comment by jenshannoschwalm** [comment]
Aah, the commit describes that already.

**Comment by TurboGit** [comment]
Hum... so the issue is the other way around... When applying a preset we use the FOR_RAW flags, in develop.c we have:

```
  int iformat = 0;
  if(dt_image_is_rawprepare_supported(image))
    iformat |= FOR_RAW;
  else
    iformat |= FOR_LDR;
```

So the above call should probably be only `dt_image_is_raw(image)` otherwise we apply a RAW presets for both sRAW & RAW. Does this make more sense?

**Comment by jenshannoschwalm** [comment]
Yes, i think so.

**Comment by kmilos** [comment]
@TurboGit Sorry, not that familiar with all the preset mechanisms and code paths...
