### ISSUE TITLE
git master : adding new filmic rgb default preset results in double filmic modules when history is reset 

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#14418]
### Describe the bug

If I create a new filmic rgb preset and set it to `auto apply this preset to matching images` with the intention to apply it to all matching images, then I get _two active_ filmic rgb module instances, when I reset history. The first instance is `filmic rgb scene-refered default` and the second one is my new preset `v6`, which is now applied. Having two filmic modules active is not my intention. I just want my new "v6" default to be active. 

![double-filmic](https://user-images.githubusercontent.com/42386052/236299905-af6fda79-d4fb-4318-a252-eb19ad9ac9d5.png)

### Steps to reproduce

1. Select a raw file and go to darkroom.
2. Execute `history reset`.
3. Select  `filmic rgb module` and create a new preset. In my case I create a "v6" preset by changing `options -> color science -> v6(2022)` and do `store new preset`, `name: v6`, `auto apply this preset to matching images`, `ok` to save preset.
4. Execute `history reset` again, to apply the new default "v6" filmic preset.
5. There are two `filmic rgb` module instances: one `filmic rgb scene-refered default` and one `v6`. This is shown in the picture above in the describe the bug section and also below in screenshot. I have `preferences -> processing -> auto apply -> scene-referred (filmic)` selected.

### Expected behavior

One active filmic rgb module called "v6".

### Logfile | Screenshot | Screencast

![double-filmic](https://user-images.githubusercontent.com/42386052/236302926-ef097e2e-c3c3-41f7-8cf2-c1bf1d226e91.png)

### Commit

The commit f91f511 from 2 May is fine. Running later commit 7c5d77f216 has the error. It is somwhere in between these two commits 2-4 May.

### Where did you install darktable from?

self compiled

### darktable version

I am using release-4.3.0-2129-g7c5d77f216. 

### What OS are you using?

Linux

### What is the version of your OS?

Debian 11.7

### Describe your system?

- OS : Linux debian 5.10.0-22-amd64 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
- Linux - Distro : Debian 11.7
- Memory : 16 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : Nvidia Driver Version: 470.182.03-1
- OpenCL installed : Yes, OpenCL 3.0 CUDA 11.4.364
- OpenCL activated : Yes
- Xorg : X11
- Desktop : Gnome 3.38.5
- GTK+ : 3.24.24
- gcc : gcc 12.2 
- cflags : 
- CMAKE_BUILD_TYPE : Release

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000], Nvidia Driver Version: 470.182.03-1

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- Can you reproduce with another darktable version(s)? **Introduced after commit f91f511 from 2 May**
- Can you reproduce with a RAW or Jpeg or both? **RAW**
- Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
- If the issue is with the output image, attach an XMP file
- Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
- Do you use lua scripts? no
        What lua scripts start automatically?
        What lua scripts were running when the bug occurred?

**Comment by KarlMagnusLarsson** [comment]
I get this issue at commit 6cd9d00, Rework the default modules for different workflows.

**Comment by TurboGit** [comment]
I suppose that's one for me :) Thanks for reporting.

**Comment by TurboGit** [comment]
@KarlMagnusLarsson : Can you test #14419 and report if all this ok on your side. TIA.

**Comment by KarlMagnusLarsson** [comment]
Thank you @TurboGit for https://github.com/darktable-org/darktable/pull/14419. It works for me.
