### ISSUE TITLE
darktable won't start without opencl disabled

### ISSUE THREAD

**Issue by jas01** [darktable-org/darktable#14425]
### Describe the bug

I'm unable to launch darktable without the "--disable-opencl" option. 

Even after I delete $HOME/.config/darktable and $HOME/.cache/darktable the darktable don't start at all. 

With the option -d all I don't get a lot of info, just 

```
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
```
then...nothing. 

With the option “--disable-opencl" it's seem that working

### Steps to reproduce

Just launch darktable 

### Expected behavior

well....;-)

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1-3

### What OS are you using?

Linux

### What is the version of your OS?

archlinux

### Describe your system?

HP EliteBook x360 1040 G8 Notebook PC

### Are you using OpenCL GPU in darktable?

I guess so.

### If yes, what is the GPU card and driver?

No idea

**Comment by gi-man** [comment]
Most likely you have a driver issue with your GPU. Can you try to see what GPU and what drivers you have? I'm not an arch user, so I can't help much. 

Darktable-cltest might give you more info.

**Comment by jas01** [comment]
Hi, thanks for the answer, but even darktable-cltest hang up after
```
[dt_get_sysresource_level] switched to 1 as `default'
  total mem:       31785MB
  mipmap cache:    3973MB
  available mem:   15892MB
  singlebuff:      248MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
```
I got no alert/warning/error of any kind in dmesg. 

The strange part is I'm using darktable on this computer since more than a year without any issue.

Do you think it's hardware problem ? 

I can run software like blender with no problem.

**Comment by gi-man** [comment]
I think it is a driver issue. I don't think blender uses opencl.

**Comment by jas01** [comment]
You're right. 

The problem come with blender, when installing blender (on archlinux) the pkg system also install intel-oneapi-* (no idea what's that), but that mess up some way with opencl. 

With those intel-oneapi-*  even the clinfo hangs.

So after uninstalled thoses packages darktable work again. 

I'm going to open a issue on archlinux

Thanks for everything
