### ISSUE TITLE
Histogram resets to 'histogram' mode after restart

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#14428]
### Describe the bug

1. Open darktable
2. Open an image in darkroom
3. Switch histogram to RGB parade
4. Switch to lighttable
5. Re-open the image -> histogram is still in RGB parade mode
6. Exit darktable
7. 
```bash
$ grep "plugins/darkroom/histogram/mode" darktablerc
plugins/darkroom/histogram/mode=RGB parade
```
8. Open darktable
9. Exit darktable
10.
```bash
$ grep "plugins/darkroom/histogram/mode" darktablerc
plugins/darkroom/histogram/mode=histogram
```

Self-built on Ubuntu, rev. c278d0634a6. This started not so long ago.

### Steps to reproduce

See above

### Expected behavior

Retain the last selected histogram mode

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+2168~gc278d0634a

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

None

**Comment by kofa73** [comment]
Bisect in progress, will update

**Comment by kofa73** [comment]
kofa@eagle:~/darktable$ git bisect bad
ea6e428e8adea3522525afb90ca541a2e963590d is the first bad commit
commit ea6e428e8adea3522525afb90ca541a2e963590d
Author: Victor Forsiuk <vvforce@gmail.com>
Date:   Wed May 3 14:22:09 2023 +0300

    RGB is an initialism and should be written in all caps

 src/imageio/format/avif.c | 38 +++++++++++++++++++-------------------
 src/imageio/format/tiff.c |  2 +-
 src/iop/sigmoid.c         |  3 ++-
 src/libs/histogram.c      |  3 ++-
 4 files changed, 24 insertions(+), 22 deletions(-)

@victoryforce

**Comment by dterrahe** [comment]
These random breakages were exactly why we went with en@truecase instead of "fixing" grammar all through the code base. I thought we'd point people who care about capital letters there. But I guess we're getting the best of both worlds.
