### ISSUE TITLE
IOP error spam in debug log

### ISSUE THREAD

**Issue by kkempter-getswift** [darktable-org/darktable#14439]
All
I reached out to the rawspeed project with a new camera request. I have uploaded image sampples and the related .fff files.

I compiled the latest development branch, and everything is working, Thank You!!!

I am however seeing these output errors on the command line:

80.4232 Trouble: [color calibration] white balance error (B0000020.3FR 17)
81.4348 Trouble: [color calibration] white balance error (B0000036.3FR 33)
81.4432 Trouble: [color calibration] white balance error (B0000036.3FR 33)
81.4571 Trouble: [white balance] double application of white balance (B0000036.3FR 33)
81.4821 Trouble: [color calibration] white balance error (B0000036.3FR 33)
84.2032 Trouble: [color calibration] white balance error (B0000036.3FR 33)
84.4754 Trouble: [color calibration] white balance error (B0000036.3FR 33)
84.4755 Trouble: [white balance] double application of white balance (B0000036.3FR 33)
84.4884 Trouble: [white balance] double application of white balance (B0000036.3FR 33)
84.5225 Trouble: [color calibration] white balance error (B0000036.3FR 33)
84.7614 Trouble: [color calibration] white balance error (B0000036.3FR 33)

**Comment by kkempter-getswift** [comment]
Just FYI I uplioaded these files (RAW and .fff samples) 3 days ago:


B0000079.3FR -> Job_0079.fff (16bit)

B0000080.3FR -> Job_0080.fff (14bit)

**Comment by ralfbrown** [comment]
Is the White Balance module set to camera reference (D65)?  If not, the messages are expected, and are warning you that you are not getting correct results with Color Calibration.
If the White Balance module *is* set to camera reference, then that means that the reference value changed between the time the sidecar was created and when you got the messages.  Or the reference value is missing, which would be the case for a new model with partial or no support.  (We had a few camera models where the reference values differed in different places in the code base, but that was fixed around 3.8 or 4.0 and should not be happening if the sidecars are recent.)

**Comment by ralfbrown** [comment]
Superceded by #14744
