### ISSUE TITLE
Crash on Export

### ISSUE THREAD

**Issue by cocker-cc** [darktable-org/darktable#14438]
### Describe the bug

Darktable crashes while exporting [this File](https://nextcloud.cocker.cc/s/sfcSTkMbxM3d9Di) (50 MB).  
I tried with `-d all`, but nothing special appears.  Terminal just sais: “killed”.  
I tried this with Darktable 4.2.1 on Linux Mint installed via `flatpak` on a HP-Laptop with AMD-Graphics, as well as on Linux Fedora installed via `dnf` on a Lenovo-Laptop with Intel-Graphics.  
Crash also happens with `--disable-opencl`.

Other (older) CR2-File from this and from other Canon-Cams can be exported without Problems.

### Steps to reproduce

Load specified File.  
Export  
Crash

### Expected behavior

export File to JPEG

### Where did you install darktable from?

flatpak

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38, Linux Mint 21.1

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment]
You might need to share an xmp of your export. How much ram do you have?

**Comment by ralfbrown** [comment]
dt got at SIGKILL from the operating system, which is usually the result of running out of memory.
We recently fixed a bug (maybe after 4.2.1) where the memory requirements for astro denoise were underestimated, leading to OOM.  You can also try reducing the resources in the preferences so that darktable doesn't try to use as much memory (the tradeoff is slower exports due to more tiling).  If you don't need a full-resolution export, you can also use "high quality export: no" to use less memory *and* less time.

Note that the memory requirements don't depend on the file size, but on the number of actual pixels processed by each module.

**Comment by cocker-cc** [comment]
> You might need to share an xmp of your export. How much ram do you have?

Find the XMP [here](https://nextcloud.cocker.cc/s/L73PMWBAw2NAW6q).

On the Fedora-Laptop:  
```
# free
               total        used        free      shared  buff/cache   available
Mem:         7993920     4755204      726924      908332     2511792     2027424
Swap:        7993340     3720800     4272540

# swapon -s
Filename                                Type            Size            Used            Priority
/dev/zram0                              partition       7993340         5988540         100
```

The LinuxMint-Laptop even has 16GB of RAM

> dt got at SIGKILL from the operating system, which is usually the result of running out of memory.

Log does not show this up:
```
# journalctl -S '2023-05-05' -u systemd-oomd
-- No entries --
```

>  If you don't need a full-resolution export, you can also use "high quality export: no" to use less memory and less time.

I tried that, but it did not help the Crash.  

[Here](https://nextcloud.cocker.cc/s/Azs9rarEHQFk9YH) a full Debug-Log while doing the Export:  
```
$ darktable -d all > darktable-d-all.$(date -Is) 2>&1
Killed
```

**Comment by cocker-cc** [comment]
> dt got at SIGKILL from the operating system, which is usually the result of running out of memory.

Additionally to the existing Swap (Fedora uses ZRAM by default), I added a Swapfile of several GB.  
That helped.
