### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by kuro68k** [darktable-org/darktable#14433]
### Describe the bug

Darktable crashes when I open it.

### Steps to reproduce

1. Open Darktable.

### Expected behavior

Open

### Logfile | Screenshot | Screencast

[darktable_bt_92XA41.txt](https://github.com/darktable-org/darktable/files/11412777/darktable_bt_92XA41.txt)

Log attached.

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1 x64

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro

### Describe your system?

I tried installing from the website and via Chocolatey.

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

FirePro W5000 graphics card, 2GB VRAM. Driver 27.20.21026.2006.

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Happens every time after a fresh install.

**Comment by ralfbrown** [comment]
The crash is happening while the UI library that darktable uses is initializing itself.  

It appears that Gtk is having problems interpreting your keyboard layout.  Are you using any custom layouts or keyboard drivers?  What langauge is Windows set to use?

I'm afraid there's not much darktable can do to fix this.  At best we can help you work around the problem by changing settings on your system to avoid triggering the crash.

**Comment by kuro68k** [comment]
Thanks, it is indeed due to my keyboard layout. If I switch to Japanese it opens fine. If I switch back to my modified Japanese/English layout it crashes immediately. So at least I can use darktable.

If this is a bug in Gtk I'll report it to them. Thanks for your help.
