### ISSUE TITLE
Thumbnails has disappeared when returning from Darkroom

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#14446]
### Describe the bug

In this case I work on a film roll containing 14 images (thumbnails). The file types are ARW, DNG, TIFF and JPG, and 8 of the files are ARWs.
Each time I open an ARW file in the editor, the number of thumbnails visible in Lighttable when returning is reduced, not always with the same number but in this case with typically 3 to 5 thumbnails, and never the opened ARW.
The number of thumbnails is not reduced when any other file type is opened and returned from Darkroom.

### Steps to reproduce

1. The number of thumbnails in a film roll is x.
2. I click on an ARW file with a double left mouse click, and it opens in Darkroom.
3. I return by clicking on Lighttable in the top menu (I can do some editing or return immediately - it doesn't matter in this case). 
4. The thumbnails in Lighttable is now reduced to x-y where y < x (I can't see any pattern for y relative to where the opened ARW file is positioned in the rows.)
5. Doing the same with any other of the mentioned file types return with x thumbnails.
6. Clicking on the film roll line in the left section will restore x thumbnails.

### Expected behavior

Darktable should always return to Lighttable with the original number of thumbnails.

### Logfile | Screenshot | Screencast

This is not followed by any error message.

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+1944-g299ba908fc

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro, version 10.0.19045 Build 19045

### Describe your system?

New pc, fast and with sufficient capacity.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1650

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

rename images

**Comment by AlicVB** [comment]
I don't reproduce the issue, and I'm not sure to see where that can come from...
What would be great is a small screencast of what happens, or at least a screenshot of the dt window before you enter darkroom and after you come back to lighttable.

Some other things to check : 
- is there some filter active ?
- is there grouped images (if this is the case, try to reproduce with grouped images collapsed and expanded)
- just to be sure : this is not a "scrolling" issue ? (try to scroll down to check...)
- last, as there's "just" 14 images involved, try to copy this images to another (temp) directory and import them : do you reproduce ?
- then you can try to remove images 1 by 1, and see if you reproduce...

Sorry to annoy you with all this tests, but that's the only way we have to try to solve the issue...

**Comment by KIRSJ** [comment]
Thank you for mentioning 'scrolling'. I have not tried the mouse wheel for scrolling in Lighttable - until now!
But in this case the upper most row disappears out of sight after a visit in Darkroom - and ... can be restored with the mouse wheel.

Sorry about that. 
The problem now seems to be minor - though big enough to fool a non-technical person...!

I tried with other film rolls, and the phenomenon appears with more than one row of thumbnails - but only when a thumbnail is chosen for editing from below the first row.
I don't think this is a new phenomenon, as far as I remember it has happened in 4.2.1 too, but for a long time I just clicked the film roll line - which has the same effect as scrolling to the top.

My sort criteria is 'color label', and I have stars combined with the color coding (if of any importance).
No grouping.

**Comment by AlicVB** [comment]
The correct behavior should be to ensure that the last edited image is visible when returning in lighttable, with the minimum page change (in your case, no change at all)
That was the initial intent, but this seems to have been lost at some point... I will try to have a look

**Comment by TurboGit** [comment]
> That was the initial intent, but this seems to have been lost at some point... I will try to have a look

Yes indeed, it seems that a regression has slipped somehow here.

**Comment by AlicVB** [comment]
See PR #14512 

This may be not exactly the fix you were waiting for, as it "just" avoid the page to scroll too far away, which might be confusing and let one think images as been "lost"

In fact the "active" image (the one shown in darkroom) need always to be the "offset" one, due to filmstrip... and it's here from the beginning ! Changing that would require to store and synchronize different offset depending of the thumbtable mode, which would require a really big change... not sure it's worth the pain...

**Comment by KIRSJ** [comment]
I see the problem, and now when I know the medicine, it's not a practical problem to me. 
But only because I know the value of Darktable's many extraordinary features. 
This case is an example of one of those anomalies that adds up in the mind of a new user and may cause him to leave Darkroom prematurely as an alternative to the safe world of Adobe, C1, On1, etc. Free software is always confronting the little nagging doubt - "Is this open and free software really a competitor to stuff that people are willing to pay for on a regular basis?", and the answer is often given in advance, not least due to the steep learning curve in the beginning.
 - So, even minor unexpected discrepancies can push potential users away - like not returning to the exact same constellation of thumbnails on the screen when Darkroom was called - with the current image highlighted. I think it's worth the pain, but it's free for me to say. This is just how I would prefer DT to work - if anybody asked me.
