### ISSUE TITLE
X-T5 lossless compressed raw sample

### ISSUE THREAD

**Issue by lCardosoSantos** [darktable-org/darktable#14444]
Lossless compressed RAW uploaded to raw.pixls.us. I hope it can be helpful in adding support to darktable. Uploaded as `DSCF2043.RAF`.

**Comment by cytrinox** [comment]
Lossless RAF for XT-5 should be already supported. It's just the lossy RAF that is not yet supported.

**Comment by lCardosoSantos** [comment]
> Lossless RAF for XT-5 should be already supported

Is this on the current release? I am on 4.2.1 here, and it errors when I try to open the raws. I just uploaded another picture, but this time with low ISO.

![image](https://user-images.githubusercontent.com/11529026/236689950-1dedfc29-1d94-4182-8b0a-b08c1cb4fd5e.png)

This is the error I get. I supposed it is user error then? Also, I am on the new Ubuntu release, if that's relevant.

**Comment by LebedevRI** [comment]
`DSCF2072.RAF` appears to be of the (new, unsupported) lossy raw variety.

**Comment by lCardosoSantos** [comment]
> the (new, unsupported) lossy raw variety.

And I appear as a fool of myself. Seems like I mistook "compressed" on the Fuji menu to mean another thing. Well, I hope the unsupported lossy raw samples I uploaded are still useful to someone. I will go ahead and close the issue.
