### ISSUE TITLE
Export: Preserve file name template on output directory change

### ISSUE THREAD

**Issue by bovender** [darktable-org/darktable#14441]
Not quite sure whether this is a missing feature or a bug, but whenever I change the output directory, the file name template is reset to `$(FILE_NAME)`.

I keep my template

    $(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)_$(EXIF_HOUR)$(EXIF_MINUTE)$(EXIF_SECOND) $(FILE_NAME)

in a separate text file and copy & paste it whenever I change the output directory (i.e., with every new film roll/event), but it would really be a nice feature if DT would just preserve the template, rather than resetting it.

This is with Darktable version 3.8.1.

**Comment by pehar1** [comment]
Version 3.8.1 is outdated, did you try with up-to-date version 4.2.1 ?

**Comment by pehar1** [comment]
OK, found a minute to ckeck at current master, and it behaves the same way.

> preserve the template

I don't think this is a good idea. Imagine a template like `/media/user/path/to/images/some-template` that contains the entire path. How should darktable decide what you want to keep : `some-template` or `/images/some-template` or something else?
You can create presets for all your preferred output paths to avoid the issue you have.

**Comment by Nilvus** [comment]
That's exactly why presets are there (to keep templates and export different choices). You can also set folders if they are on same paths and only related to film roll. There's a variable for that too ($(ROLL_NAME)) and many other variables.

**Comment by bovender** [comment]
Thanks for your responses, the points are all well taken.

In my workflow, I have my raw files in a folder structure that is determined by the camera (e.g., `140_0805`) and that I do not touch. I export the JPGs to another drive with folder structures such as `2023-05-08 friend's birthday`. The file name part (composed of variables) remains the same for each and every export, but the folder part changes for each event and cannot be automagically determined by variables.

But I see that this is a very particular, if not peculiar (?) workflow that cannot be generalized to other users. I'll keep copying and pasting ;-) Thanks again!
