### ISSUE TITLE
[FR] Move selected images from map view into film strip in darktable

### ISSUE THREAD

**Issue by mjmc1234** [darktable-org/darktable#14443]
**Is your feature request related to a problem? Please describe.**

Most of the time the images I select to process are based on their location not the folder I stored them in. But I'm finding I can only select an image in the map view by double clicking on it and going to darktable. In this situation the filmstrip doesn't change and can relate to a completely different folder of images. I therefore have to go back to the map view to find my next image.

**Describe the solution you'd like**

I value the map view, and would like to use it to select the group of images that I will process. This includes the groups the map view already displays, and potentially the ability to define a region in the map view for images. It would then be good to take this collection of images to darktable (or lighttable) and have them appear in the film strip, and the first selected image in map view already selected active in darktable. I.e. if I select a group of images in map view, then I can go to darktable and have the first of this group as the image I am editing and all the images I selected in the map view present in the film strip.

**Alternatives**

Alternatively, it would work to simple be able to override the film strip in darktable with the folder of the currently active image. That way I could select an image in map view, double click on it to bring it to darktable, and then perform the new feature to set the film strip to be the folder of that image. This wouldn't exactly meet my use case but would work for a lot of use cases.

**Additional context**

**Comment by ralfbrown** [comment]
The film strip shows the current collection (after any filtering such as by stars), and double-clicking on an image in the map doesn't change the collection.

However, you **can** define a collection based on a region in the map (circular, rectangular, or based on political boundaries) and make that your selection criterion, making all images geotagged within the region part of the active collection.  https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/map/locations/

You can also type Ctrl-J to jump to the film roll (folder) containing the active image, which will make that folder the current collection.

**Comment by mjmc1234** [comment]
These functions are perfect for me. Many thanks for this information and the very swift response. I'll close this request.
