### ISSUE TITLE
Import of preset results in wrong set auto-apply filter criteria

### ISSUE THREAD

**Issue by cabradaabra** [darktable-org/darktable#14457]
### Describe the bug

When importing a preset, the auto-apply filter criteria for upper "infinity" values are set wrong, ie. the filter for exposure is set to 0-0 and the one for aperture is set to f/0-f/0 so the preset is never auto-applied. iso-criteria seems also affected

### Steps to reproduce

1. Open darkroom, activate a module and store a new preset
2. Give a name and check "auto-apply this preset to matching images" and hit ok. Leave the rest untouched
3. Go to preferences, presets and export the presets
4. Go back to darktroom and delete the preset
5. Import it back in preferences, presets

### Expected behavior

the filter criteria should not be affected by import, ie. aperture should be f/0-f/+ and should show as % in preferences, presets

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Windows version is also affected

**Comment by TurboGit** [comment]
@cabradaabra : Thanks for reporting, fixed in #14459.
