### ISSUE TITLE
howto? stacking images; setting cache location

### ISSUE THREAD

**Issue by denm77** [darktable-org/darktable#14478]
Hi
I do not miss much using DT. Its already really great.

one thing could really help:  if we could Stack severals shots into a single high-res result . Not as a result of HDR but in case of stacking 10 or even 100 Takes ( or more ) , like for astronomie Photos.

Well, aswell if we could have the possibilitie to swap the " cache folder " to an  extra SDD, that might maybe speed up a bit the workflow.

Thanks  and GREETINGS ALL .-)

**Comment by ptilopteri** [comment]
you have available, hugin and zerenestacker
which do a great job.

**Comment by ralfbrown** [comment]
There is already a --cachedir flag to specify where to store thumbnails etc.  https://darktable-org.github.io/dtdocs/en/special-topics/program-invocation/darktable/

darktable itself doesn't have any way of processing multiple images into a single result, but there is a Lua script which will stack multiple shots (https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/contrib/image_stack/).  It's set up to do averaging for noise-removal, but may be adaptable for super-resolution blending.
