### ISSUE TITLE
cmd-, does not open preferences on Macosx

### ISSUE THREAD

**Issue by jmgurney** [darktable-org/darktable#14484]
### Describe the bug

When I press cmd-, the preferences dialog window should open

### Steps to reproduce

1. Launch darktable
2. When window is shown, press cmd-,

### Expected behavior

darktable should display the preferences dialog box

### Logfile | Screenshot | Screencast

Nothing happens when cmd-, is pressed, so no need for a screen shot/log file.

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.3

### Describe your system?

n/a

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by MStraeten** [comment]
did you define that shortcut?

**Comment by jmgurney** [comment]
Confirmed to still be a problem on 4.6.1.

**Comment by MStraeten** [comment]
did you define that shortcut? if not it's not an issue since that's not defined to do so by default ...
default behaviour is zoom out

**Comment by MStraeten** [comment]
since there's no hint that the user defined a non default behaviour this is "works as designed"
