### ISSUE TITLE
camera whitebalance reference value changed to 25000 K

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#14498]
### Describe the bug

the camera reference value changed from 6502 to 25000
current master:
<img width="293" alt="image" src="https://github.com/darktable-org/darktable/assets/39386816/3bdb1ab4-3575-47cf-ad06-23daca7ff4bd">
last build 6.5. (darktable-4.3.0+2172~ga4a48485bc): 
<img width="299" alt="image" src="https://github.com/darktable-org/darktable/assets/39386816/9671ee58-0ba0-41c3-8cc8-e9e17ed4b4b0">

### Steps to reproduce

1. expand whitebalance module 
2. check camera reference setting

### Commit

tbd: darktable-4.3.0+2172~ga4a48485bc (6.5.)

### Where did you install darktable from?

self compiled

### darktable version

darktable-4.3.0+2254~g09d99ce81f

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Ventura

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

not relevant

**Comment by Nilvus** [comment]
With 4.3.0+2236~g46414573f2, I still have 6502k on white balance. And commit just after is Rawspeed module update (last commit of may, 10th). I can't test by now commits after but maybe there's something about that, or something camera specific.

**Comment by kmilos** [comment]
AFAIRC, this is common on Sonys?

**Comment by gi-man** [comment]
I'm seeing the same. Olympus ORF, Fedora 37, 4.3.0~git2266.004b30d0

**Comment by Nilvus** [comment]
I can reproduce after updating from 4.3.0+2236~g46414573f2 to latest master. With 4.3.0+2236, I still have 6502K (I'm using a Panasonic G9) and now, with latest master, I also see 25000K. So there's an issue on a recent update (Rawspeed one?).

**Comment by Nilvus** [comment]
Just an add: seems to be a display infos issue. If I click on pen icon, I still have 25000k value but image become black. If I come back to bulb icon, 25000k is still displayed but image come back to correct and wanted display. So real value is probably still 6502K when on bulb icon but UI display 25000K).

**Comment by Nilvus** [comment]
I've done some bisect and seems that issue come from #14143 PR. @ralfbrown, as it's yours, do you have any idea about that issue?

**Comment by ralfbrown** [comment]
Not yet, other than that it seems something is not being initialized anymore - switching from camera ref to user-defined by clicking on the pencil icon gets 0/0/0 wb coefficients.

**Comment by sg456** [comment]
I noticed that it's not only the camera reference value that is affected, but all other wb presets as well. I use legacy WB often, so that was how I noticed it.

**Comment by ralfbrown** [comment]
Yes, there's something broken in how the slider values transfer among each other - changing the channel multipliers doesn't change the displayed temperature or tint and vice versa.

But once the display goes black after manually changing temp/tint, it can be restored by changing the values of all *three* channel coefficients, in either direction....

Commit 8df1fb1ae9 is definitely the culprit, but it  doesn't modify anything in src/iop/temperature.c, and most definitely not anything GUI-related.  So I will have to dig in to see what broke.
