### ISSUE TITLE
Git master : Lighttable empty when starting without any pictures, the note "There are no images in this collection" is gone.

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#14496]
### Describe the bug

If I start darkroom and there are no pictures imported at all,  or an active filter excludes all pictures, then a totally empty lighttable is shown. This is expected, but the notice. "There are no images in this collection", that no pictures are available is gone as well.

This is how git master from 13 May 2023 at commit 716365d looks like (the current commit has nothing to do with this error at all):

![Screenshot_empty](https://github.com/darktable-org/darktable/assets/42386052/83abb36c-ce54-47fa-a887-b94fc3b099ea)

It used to look like this, for instance 8 weeks ago, at commit  6cd89b61a8 .

![Screenshot with notice](https://github.com/darktable-org/darktable/assets/42386052/58f9c769-3854-4b85-91f2-87381d65261e)

This has been around, at least since 8 weeks ago.

### Steps to reproduce

1. Build darktable git master
2. Start from scratch, removing `.config` and `.cache`, to make sure darktable does not have any pictures to display.
3. Start darktable `./darktable`.
4. The lighttable is displayed with a totally empty window, like in **describe the bug** above. The old "There are no images in this collection" is gone.
5. Import some pictures.
6. Pick a filter which deliberately excludes all pictures.
7. The lighttable is again displayed with a totally empty window, like in **describe the bug** above. The old "There are no images in this collection" is gone.

If I build release-4.3.0-1319-g6cd89b61a8, from Mar 20, 8 weeks ago, then the "There are no images in this collection" is displayed. 

The error is introduced some time after release-4.3.0-1319-g6cd89b61a8.

### Expected behavior

Darktable should display notice "There are no images in this collection" and mention importing some pictures or relaxing filters.

### Logfile | Screenshot | Screencast

Look at screenshots in **describe the bug** section.

### Commit

The error exists in current master from 13 May 2023, commit 716365d, but the error is introduced sometime after release-4.3.0-1319-g6cd89b61a8, which is 8 weeks ago.

### Where did you install darktable from?

self compiled

### darktable version

13 May 2023, commit 716365d

### What OS are you using?

Linux

### What is the version of your OS?

Debian 11.7

### Describe your system?

- OS : Linux debian 5.10.0-22-amd64 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
- Linux - Distro : Debian 11.7
- Memory : 16 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : Nvidia Driver Version: 470.182.03-1
- OpenCL installed : Yes, OpenCL 3.0 CUDA 11.4.364
- OpenCL activated : Yes
- Xorg : X11
- Desktop : Gnome 3.38.5
- GTK+ : 3.24.24
- gcc : gcc 12.2 
- cflags : 
- CMAKE_BUILD_TYPE : Release

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000] : Nvidia Driver Version: 470.182.03-1

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- Can you reproduce with another darktable version(s)? **Introduced after commit 6cd89b61a8, 8 weeks ago**
- Can you reproduce with a RAW or Jpeg or both? **both**
- Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **Yes, but the error is not history related.**
- If the issue is with the output image, attach an XMP file
- Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **Yes**
- Do you use lua scripts? no
        What lua scripts start automatically?
        What lua scripts were running when the bug occurred?

**Comment by KarlMagnusLarsson** [comment]
The error is introduced at this commit 2b23c61095f7c8, defer counting images, refactor recount callbacks.

@ralfbrown, If I do `git revert 2b23c61095f7c886fe`, then I get the "There are no images in this collection" notice back.

**Comment by jenshannoschwalm** [comment]
@TurboGit and @ralfbrown i looked into the collection code and for me we have a mess with unsigned VS signed integers, also test an unsigned int for > - 1.

Something to "properly" fix in 4.4?

Should we use a signed int for count?

**Comment by TurboGit** [comment]
I would say yes, we want this for 4.4. If you have no time for this maybe @AlicVB may have a look?

**Comment by jenshannoschwalm** [comment]
I'll do
