### ISSUE TITLE
auto-apply preset creates second instance of single-instance module

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#14491]
### Describe the bug

If an auto-apply preset is defined for a module which does not support multiple instances, an new instance is created anyway, causing problems.

### Steps to reproduce

1. Create an auto-apply preset for Demosaic (the one which triggered it for me is conditional on camera and high ISO) with non-default values,e.g. VNG demosaicing
2. Import a photo which matches those criteria and open in it darkroom
3. Notice corrupted display and log messages on console:
>    324.0120 [_transform_matrix] invalid conversion from IOP_CS_RGB to IOP_CS_RAW
>    324.0120 [dt_ioppr_transform_image_colorspace] in \`demosaic', profile \`Linear Rec2020 RGB', invalid conversion from IOP_CS_RGB to IOP_CS_RAW
4. Switch tabs to Active modules tab and notice two instances of Demosaic
5. 

### Expected behavior

The preset should be applied to the existing instance of a single-instance module.

### Commit

presumably one of the auto/multiple preset PRs like #13149, #13432, or #13998

### Where did you install darktable from?

self compiled

### darktable version

master (today's, then I rolled back just a bit to 4.3.0+2244 since I hadn't seen the corrupted display in darkroom yesterday).  Not a problem in 4.3.0+12 (i.e 4.2.0) which I still have installed.

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 8

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
> Create an auto-apply preset for Demosaic (the one which triggered it for me is conditional on camera and high ISO) with non-default values,e.g. VNG demosaicing

I can reproduce only if I have two auto-applied presets for demosaic. Is that the case on your side?

**Comment by ralfbrown** [comment]
You're right, I do have two presets which match the camera model having trouble today.  I missed the other one because it has a '_' wildcard in the middle (to match both D7000 and D7200).

**Comment by TurboGit** [comment]
I have the fix, but I'll put a PR later tomorrow as I'm short on time now.
