### ISSUE TITLE
FilmicRGB still autoapplies though deactivated

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#14504]
### Describe the bug

FilmicRGB (abbr. Filmic) still applies upon history compress or new import though I deleted the preset I created for enabling it.
It only happens for that peculiar mocule. I tested sigmoid, it behaves correctly, ie. it applies so long as I create a preset and the conditions are met, and it does not apply if I remove the preset or the conditions are not met.
Filmic, OTOH, still does apply even if the preset is removed or if the conditions are not met.

### Steps to reproduce

1. set Filmic active
2. create a preset with conditions thaat will enable Filmic in certain conditions (FI. : pictures taken at ISO=200)
3. check "automatically apply ..." and save the preset
4. compress the history on a picture or import a new one and check that filmic appears in the history and is activated
5. return to the module and delete the preset
6. compress the history on a picture or import a new one : filmic ought not to appear in the history - which is not the case for me
7. return to the module and create a preset that you know any picture would never match (cf. attachment)
8. compress the history on a picture or import a new one : filmic ought not to appear in the history - which again is not the case for me

### Expected behavior

Filmic ought not apply when the previously created preset is deleted or if the conditions (brand, camera, lens, iso, aso.) do not match.

### Logfile | Screenshot | Screencast

With such a preset, Filmic ought not be activated upon history compression or at new import - but it does on my system !
![FilmicRGB unmatching conditions](https://github.com/darktable-org/darktable/assets/49912948/f7a1e51a-f716-4029-9747-ce7146cb785b)

### Where did you install darktable from?

self compiled

### darktable version

4.2.1 from github

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2 LTS 64 bits

### Describe your system?

Fujitsu Lifebook E557 / 32 GiB RAM / Intel Core i3-7100 @ 2.40 GHz x 4 / Mesa Intel HD Graphics 620 (KBL GT2)
Gnome 42.5
Wayland

### Are you using OpenCL GPU in darktable?

None

**Comment by dterrahe** [comment]
You may want to look in the preferences dialog on the processing tab under image processing at auto-apply pixel workflow defaults.

**Comment by TurboGit** [comment]
As @dterrahe said, FilmicRGB will always be applied if the workflow is set to scene-referred in 4.2.x. This has slightly changed in 4.3 as the workflow setting has been reworked to also be based on Sigmoid.

**Comment by FalCT60** [comment]
Yes, as I wrote on the list : I must have skipped this paragraph in the manual. But maybe when I built my workflow I did not need to pay attention to this, and when I fell into the problem I searched everywhere but the filmic related section.
From my point of view : dt is a intertellar spacecraft, and I only have a licence for flying a glider.
And, moreover, I just use it occasionally and often use the same few modules.
Thanks again for all.

**Comment by TurboGit** [comment]
> though I cannot understand why such a module would be mandatory.

You really want to read the manual then. There is very little cases where a module which prepare an image to be properly displayed (compressing the tonal range of the image to correspond to the tonal range of the display and giving the expected S curve to move away from a linear rendering which is not what our vision is expected).

Note: It somehow replaces the Base Curve used with the display-referred workflow.

So, yes please read the manual.
