### ISSUE TITLE
Some minor refresh issue on color calibration module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#14518]
### Describe the bug

Since #14498 is fixed, if I change a setting on white balance then revert back to default setting, color calibration module shows "error, on white balance module" with red warning. This should disappear when put back related white balance default and at least on opening module. This is no more the case. But error message disappear when quitting darkroom and go back to the image.

I think some refresh issue is missing after change regarding fix of #14498. @ralfbrown?

### Steps to reproduce

With an image with scene-referred workflow, so white balance on bulb icon (6502K value):
1) click on pencil icon on white balance module
2) click on bulb icon to revert to default settings
3) see error message appear on color calibration module.

Quit darkroom and go back to the image: the error message had disappear.

### Expected behavior

error message disappear as soon as white balance setting is again ok for color calibration module

### Where did you install darktable from?

darktable.org

### darktable version

last master at the time of writing that issue

### What OS are you using?

Linux

### What is the version of your OS?

Debian Sid

### Are you using OpenCL GPU in darktable?

None

**Comment by jenshannoschwalm** [comment]
@Nilvus i think the underlying problem is something else. The error messages are generated in some "tricky" way. The colorbalance warning is checked while _processing_ the module. Sounds good but in case of a cache hit we might (you changed temperature some times for example) have no processing of that module and so the warning stays ...

**Comment by Nilvus** [comment]
Probably. I don't know how this works on the code but on the UI, that's why I succeed to reproduce. It remains a minor bug as processing works as it should and error message could be disabled easily but would be good if this could be fixed.
