### ISSUE TITLE
Some text use system language instead of selected language

### ISSUE THREAD

**Issue by gdeban** [darktable-org/darktable#14513]
### Describe the bug

The parameters section in the import view is displayed using the system language (french in my case) instead of the language selected from the settings (english).

![image](https://github.com/darktable-org/darktable/assets/6939660/a9f803dc-975c-4aaa-8f86-aec530c66f9d)

### Steps to reproduce

1. Installed on french Windows 11 system.
2. Changed language settings to english in darktable settings
3. Restarted darktable

### Expected behavior

This sections should be displayed in the selected language (english in this case)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by Nilvus** [comment]
I can reproduce too on Linux and actual master.

**Comment by Nilvus** [comment]
@TurboGit: I checked and it's also on copy&import or add to library dialog windows for some strings. See for example:
![image](https://github.com/darktable-org/darktable/assets/45535283/5bc16021-0e0c-45ca-8818-c9a59341eafc)

This also affects tooltips when hovering those texts. What I see is that all those strings are generated when compiling with that file: ../build/bin/conf_gen.h

**Comment by Nilvus** [comment]
Just saw another affected string:

![image](https://github.com/darktable-org/darktable/assets/45535283/dd7d5562-e8d8-4b1a-9eb5-1a27c680aa6c)

Of course, this string is in french instead of english on each module

**Comment by TurboGit** [comment]
Hum... My first reaction would be... This is not possible... But I can reproduce, really strange.

**Comment by TurboGit** [comment]
Found the issue, fix coming...

**Comment by TurboGit** [comment]
See PR #14521
