### ISSUE TITLE
Ctrl+DoubleClick on sliders to reset them to the automatic preset value.

### ISSUE THREAD

**Issue by Michael2MacDonald** [darktable-org/darktable#14528]
**Is your feature request related to a problem? Please describe.**
You can Ctrl+Click the reset button on modules to reset them to the values of the automatic preset But you can't do this with each slider separately.

**Describe the solution you'd like**
Allow users to Ctrl+DoubleClick on sliders to reset them to the automatic preset value.

**Comment by dterrahe** [comment]
Implemented here https://github.com/dterrahe/darktable/commit/96ed020ebbb407540b555695af7cf9ad0cd38294 and included in https://github.com/dterrahe/darktable but unlikely to be included upstream due to lack of discoverability and usefulness to a small subset of dt users.
