### ISSUE TITLE
High dynamic range linear EXR exports.

### ISSUE THREAD

**Issue by kurono73** [darktable-org/darktable#14529]
**Is your feature request related to a problem? Please describe.**
Currently, "output" in the "output color profile" module is "non-linear", When exporting in EXR, even if the ICC profile is linear, it is clamped at 0-1, so overexposed values are retained and cannot be exported.
For example, if HDR-DNG data is exported in EXR after increasing the exposure by +8, the overexposed value cannot be restored even if the exposure is reduced after export because the data is clamped at 0-1.
If you want to use a linear ICC profile in EXR export, you need to lower the exposure so that it fits within the 0-1 range, and then use external software to increase the exposure after export.

**Describe the solution you'd like**
Since EXR is an HDR format, I would like to have the setting and ability to export in high dynamic range linear, not clamped at EXR.

**Comment by kmilos** [comment]
You have already two linear variants to choose from in the output color module (or export settings): linear Rec709 and linear Rec2020.

You can easily add more linear ICC profiles yourself, as per the documentation.

**Comment by kmilos** [comment]
This is not to say there is nothing to be done re HDR workflow in dt, but whatever _it_ is, it needs to be carefully distilled, and then some.

**Comment by kurono73** [comment]
I am using darktable-4.2.1-win64 and the data exported by EXR or Tiff32bit is clamped for linear values 1 and above and not exported as correct linear data.
The linear Rec709 and linear Rec2020. and other ICC profiles are linear, and the gamma values are indeed linear, but the high-luminance areas with increased exposure are clamped to 0-1 when exported, and can be said to be non-linear.

![image](https://github.com/darktable-org/darktable/assets/130467818/c35eafa3-2fb7-4a70-8e87-71f86cca31b7)

**Comment by kmilos** [comment]
Do not use absolute colorimetric intent, leave it at default value (perceptual).

**Comment by kmilos** [comment]
Btw, did you try importing float EXR or TIFF back into darktable? I get all my data back and can play w/ exposure all I want w/o any clipping (also 4.2.1 on Windows).

It might be that RawTherapee is clipping on input instead?

**Comment by kurono73** [comment]
Thank you very much. I just checked again,
The reason was that I had switched "input color profile>gamut clipping".
I changed it from "linear Rex2020" to "off" and that solved the problem.
The default setting is off, but it seemed to have been switched when the style was applied, which is why it took so long to notice.
Sorry for the trouble.
