### ISSUE TITLE
Please ARW files compressed for Sony ALPHA A 7 RV

### ISSUE THREAD

**Issue by baggerolli** [darktable-org/darktable#14538]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by baggerolli** [comment]
Darktable can nit open Sony A 7 RV RAW-files wether uncompressed nor compressed

**Comment by Nilvus** [comment]
This camera is actually not supported by darktable.
It's so not an issue. To add new camera, see: https://www.darktable.org/resources/camera-support/

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/12985, please search before opening new issues.

Uncompressed and lossy compressed are actually already supported in the development version. Lossless are still not.
