### ISSUE TITLE
Use English module names in logs

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#14542]
**Is your feature request related to a problem? Please describe.**
Using translated module names in logs makes log analysis harder. International users submitting logs means we see:

    88,908893 [dev_pixelpipe] took 0,005 secs (0,000 CPU) [full] processed `perfil de cor de saída' on GPU, blended on GPU
    88,910562 [histogram] took 0,001 secs (0,000 CPU) scope draw
    88,913684 [dev_pixelpipe] took 0,005 secs (0,000 CPU) [full] processed `codificação para tela' on CPU, blended on CPU

**Describe the solution you'd like**
Use the English names in logs.

**Alternatives**
During log analysis, use translation engines / search the source to translate the names back to English.

**Comment by jenshannoschwalm** [comment]
will do.

**Comment by gi-man** [comment]
I was thinking the same thing when I was reading that log. But then I noticed that when we have 2 modules of the same, the rename helps (eg. D&S 1, D&S 2). So I'm not sure if this will be an easy task.

**Comment by kofa73** [comment]
Maybe append the position in the pipeline, or the combine the English name with the instance name from the UI (could be very long).

**Comment by jenshannoschwalm** [comment]
We already do such for `-d pipe` in almost all cases ...

**Comment by jenshannoschwalm** [comment]
Fixed in master
