### ISSUE TITLE
Darkrable 4.2.1 HDR not working on canon CR2 (6D mkII)

### ISSUE THREAD

**Issue by kyoaku** [darktable-org/darktable#14546]
### Describe the bug

After importing raw CR2 files inside the lightTable interface, and select the 3 files, I clicked on "create HDR" and the following message appeared : 

"exposure bracketing only works on raw images"

the same message is dispayed with DNG files

### Steps to reproduce

1- Go to lightTable and import some CR2 or DNG files
2- select same files with different exposure
3- click on "create HDR" button
4-see the message : "exposure bracketing only works on raw images"

### Expected behavior

Darktable should create a merged raw file

### Logfile | Screenshot | Screencast

![Capture](https://github.com/darktable-org/darktable/assets/8832372/55b01692-0476-4cfe-bd24-037865bc6b71)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 pro

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
Those are presumably demosaiced Canon sRaws.

As the message says, dt HDR merging works only on genuine Bayer CFA raw inputs.
