### ISSUE TITLE
FIX PNG EXIF DATA LOSS

### ISSUE THREAD

**Issue by FranJNS** [darktable-org/darktable#14560]
### Describe the bug

Dear Darktable team,

For over a year now, I have been experiencing an issue with Darktable's export feature that seems to be unique to my situation. I need to develop and export photos in PNG format while preserving the EXIF data. However, when the images are exported, the EXIF data disappears. Strangely, this issue doesn't occur when exporting in TIFF format, as the EXIF data is retained.

I have the metadata preservation options enabled, so I'm unsure what could be causing this. I appreciate your attention to this matter. I am using Windows 10.

Thank you.

### Steps to reproduce

Import the photos.
Develop the photos.
Configure the export settings, including metadata preservation and PNG output.
The exported files do not have EXIF data.

### Where did you install darktable from?

darktable.org

### darktable version

4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro 22H2

### Describe your system?

Ryzen 9 3900x
RTX 2070 SUPER
64 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

**Comment by kmilos** [comment]
See https://github.com/darktable-org/darktable/pull/13428

In short, your Exif data is there, but some apps do not know how to read it.

The long-term fix is already in master, but requires Exiv2 0.28, which is not supported by darktable yet.
