### ISSUE TITLE
Lens correction: Manual selection of camera does not accept choice of camera

### ISSUE THREAD

**Issue by timokl-github** [darktable-org/darktable#14568]
### Describe the bug

I have a Leica D-Lux 7 camera, which is not supported by Lensfun, yet. But this camera is a variation of the Panasonic LX 100 II (same lens, same sensor etc. mostly built of the body and firmware is different) - so you should be able to select manually select the Panasonic camera.

However, when I select the camera pop up menu, it opens, but as soon as I move the mouse, the menu closes instantaneously.

This also happens with files from my other camera, Canon EOS 6D (which is supported by lensfun).

### Steps to reproduce

1. Open an image file in darkroom tab
2. Select Lens Correction module.
3. Click on dropdown menu for camera selection
4. Move the mouse and click on any camera manufacturer
5. Menu closes

### Expected behavior

Darktable should let me choose camera model and lens.

### Logfile | Screenshot | Screencast

`34,609287 [sql] ./src/common/film.c:525, function dt_film_set_folder_status(): prepare "DELETE FROM memory.film_folder"
34,609395 [sql] ./src/common/film.c:531, function dt_film_set_folder_status(): prepare "SELECT id, folder FROM main.film_rolls"
34,609457 [sql] ./src/common/film.c:536, function dt_film_set_folder_status(): prepare "INSERT INTO memory.film_folder (id, status) VALUES (?1, ?2)"
34,611001 [sql] ./src/libs/collect.c:1997, function list_view(): prepare "SELECT folder, film_rolls_id, COUNT(*) AS count, status FROM main.images AS mi JOIN (SELECT fr.id AS film_rolls_id, folder, status       FROM main.film_rolls AS fr        JOIN memory.film_folder AS ff        ON ff.id = fr.id)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC"
34,798103 [sql] ./src/common/film.c:525, function dt_film_set_folder_status(): prepare "DELETE FROM memory.film_folder"
34,798244 [sql] ./src/common/film.c:531, function dt_film_set_folder_status(): prepare "SELECT id, folder FROM main.film_rolls"
34,798346 [sql] ./src/common/film.c:536, function dt_film_set_folder_status(): prepare "INSERT INTO memory.film_folder (id, status) VALUES (?1, ?2)"
34,799635 [sql] ./src/libs/collect.c:1997, function list_view(): prepare "SELECT folder, film_rolls_id, COUNT(*) AS count, status FROM main.images AS mi JOIN (SELECT fr.id AS film_rolls_id, folder, status       FROM main.film_rolls AS fr        JOIN memory.film_folder AS ff        ON ff.id = fr.id)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC"
37,784344 [histogram] took 0,001 secs (0,001 CPU) scope draw
37,869539 [histogram] took 0,001 secs (0,001 CPU) scope draw
52,101931 [sql] ./src/common/image.c:285, function dt_image_film_roll(): prepare "SELECT folder FROM main.film_rolls WHERE id = ?1"
52,102478 [sql] ./src/common/image.c:356, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
52,103396 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,103687 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,103880 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,104064 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,104248 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,104387 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,104492 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
52,104626 [sql] ./src/common/tags.c:635, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (12454) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
52,105182 [sql] ./src/common/tags.c:635, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (12454) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
52,328631 [images to act on] new cache (visible) : 12454 
52,328685 [images to act on] new cache (all) : 12454 
52,328695 [sql] ./src/common/collection.c:976, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
52,328789 [images to act on] single image : 12454
52,328805 [sql] ./src/libs/image.c:240, function _update(): prepare "SELECT COUNT(id) FROM main.images WHERE group_id = ?1 AND id != ?2"
52,331693 [sql] ./src/common/tags.c:1268, function dt_selected_images_count(): prepare "SELECT count(*) FROM main.selected_images"
52,331786 [sql] ./src/common/tags.c:616, function dt_tag_get_attached(): prepare "SELECT COUNT(*) FROM (SELECT imgid FROM main.selected_images)"
52,331852 [sql] ./src/common/tags.c:635, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (SELECT imgid FROM main.selected_images) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
53,669102 [sql] ./src/common/image.c:285, function dt_image_film_roll(): prepare "SELECT folder FROM main.film_rolls WHERE id = ?1"
53,669430 [sql] ./src/common/image.c:356, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
53,670030 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670222 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670337 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670473 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670580 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670674 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670767 [sql] ./src/common/metadata.c:487, function dt_metadata_get(): prepare "SELECT value FROM main.meta_data WHERE id = ?1 AND key = ?2 ORDER BY value"
53,670903 [sql] ./src/common/tags.c:635, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (12454) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
53,671373 [sql] ./src/common/tags.c:635, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (12454) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
53,896227 [images to act on] new cache (visible) : 12454 
53,896282 [images to act on] new cache (all) : 12454 
53,896292 [sql] ./src/common/collection.c:976, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
53,896397 [images to act on] single image : 12454
53,896413 [sql] ./src/libs/image.c:240, function _update(): prepare "SELECT COUNT(id) FROM main.images WHERE group_id = ?1 AND id != ?2"
53,898021 [sql] ./src/common/tags.c:635, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (12454) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
71,855574 [histogram] took 0,001 secs (0,001 CPU) scope draw
71,905509 [histogram] took 0,001 secs (0,001 CPU) scope draw
`

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Describe your system?

RAM: 12 GB
Wayland
Gnome 44.0
Kernel 6.2.0.20 generic
GTK+ 3.24.37

### Are you using OpenCL GPU in darktable?

None

**Comment by sgotti** [comment]
It's probably the same as #13150

**Comment by Nilvus** [comment]
@timokl-github: try to launch darktable with X11. On Wayland, use 'GDK_BACKEND=x11'. This will fix that until 4.4 update that will fix that. 4.4 release is in 4 weeks. I close that issue, as a duplicate. If necessary, you can comment/answer here.
