### ISSUE TITLE
Conversion to reduced raw file option

### ISSUE THREAD

**Issue by mamvdwel** [darktable-org/darktable#14563]
**Is your feature request related to a problem? Please describe.**
No it isn't (at least not a problem in the product). However a broader problem could be solved by this request

**Describe the solution you'd like**
These days modern camera's have sensors that count more and more megapixels. This on the one end is nice (more details is welcome most of the time) but on the other hand there are downsides of which the most important one concerns storage. This means if you have a camera with a very detailed sensor (e.g. 80 or 100 mega pixels) the files will always have huge sizes when in many situations you don't need that resolution. It would be very cool if it would be possible (of course this has to be optional!!) to reduce the size of the raw file by means of reducing resolution to a quarter of the original size. This could be done by grouping 4 adjacent logical pixels (2 horizontal 2 vertical) in to one (the values of adjacent R's are averaged, the values of adjacent blues are averaged and the values of adjacent greens ar averaged in such a way that the bayer pattern will remain in the to be created raw file). The resulting raw file could then be stored as a png. The above should be optional by means of a button ("create reduced resolution image" or something like that) in the light table section within module 'selected image(s)'. This option should also be present (as a 'reduce resoltion?' checkbox that is off by default) when you create an HDR image or as a separate button 'create HDR with reduced resolution' or something like that). 

So the general idea is to make it possible to reduce raw files that have been created by means of a camera with a very high resolution bayer pattern sensor to a quarter of the original size (e.g. 100MP becomes 25MP) if the image does not require the highest resoltion. This has not only the advantage of reduced storage but also that of faster processing within darktable

P.s. maybe camera manufacturers are going to introduce reduced resolution features as well but I don't count on this

**Alternatives**
I have none. The camera's that I use do not provide this solution. It could be that there are third party products that could do this but I  prefer to use with as little solutions as possible and I think this should fit very nicely in Darktable!

**Additional context**
N.a. I hope the above is clear and hope you're going to implement it. But whatever happens thanks for the great work you're doing on this great product!

**Comment by jenshannoschwalm** [comment]
No chance. Darktable has a strict policy fully agreed on by all debs and users: never ever change the raw file!

Some manufacturers have support for such a feature.

**Comment by parafin** [comment]
Yeah, I think this job is for a separate tool which could produce a DNG file as output to be imported to darktable. Making it part of dt itself makes very little sense. Many cameras have support for sRAW files, which is exactly what is described, and dt aims to support these files. And final thought - maybe don't buy the cameras which don't fit your workflow?..
