### ISSUE TITLE
iop colorspace: code refactoring - clean-up

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14569]
Would be good to replace `int` by `dt_iop_colorspace_type_t` for `[default/input/ouput]_colorspace` in all IOPs and the `iop_api.h`. There is also probably some corresponding changes to do in structs.

**Comment by MStraeten** [comment]
also for blend_colorspace?

**Comment by MStraeten** [comment]
replaced all that stuff with find and sed 
but then iop_api.h needs to include imageop.h which itself includes iop_api.h and is included from history.h which causes an error:
```
in file included from /Users/xxx/src/darktable/src/views/view.h:23:
/Users/xxx/src/darktable/src/common/history.h:98:62: fatal error: declaration shadows a variable in the global scope [-Wshadow]
static inline gboolean dt_history_module_skip_copy(const int flags)
                                                             ^
/Users/xxx/src/darktable/src/iop/iop_api.h:76:14: note: previous declaration is here
DEFAULT(int, flags, void);
             ^
1 error generated. 
```
how to solve that?

**Comment by TurboGit** [comment]
Move `dt_iop_colorspace_type_t` def into `common/colorspaces.h`, should work.

**Comment by TurboGit** [comment]
> also for blend_colorspace?

Would be nice, yes!
