### ISSUE TITLE
macOS: redraw issue with gtk3 3.24.38

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#14579]
### Describe the bug

darktable seems to have redraw issues when using gtk3 3.24.38 instead of 3.24.37
maybe upstream issue ...

https://github.com/darktable-org/darktable/assets/39386816/ee46fab6-8275-464d-85f9-e8f7f5653238

### Steps to reproduce
arm64 macports build
activate gtk3 3.24.38
run darktable, scale app window - see gui elements disappering
further scaling can cause a proper redraw

activate gtk3 3.24.37
run darktable, scale app window - just a proper redraw

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+2400~g2ea3255d47

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Ventura

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

issue independend of gpu usage

**Comment by TurboGit** [comment]
Maybe an upsteam issue, but can't tell as I'm still using 3.24.37 on GNU/Debian (3.24.38 is still in experimental branch).

**Comment by MStraeten** [comment]
haven't seen this with my custom win build (also gtk 3.24.38) - so maybe just relevant for the upcoming macOS release builds

**Comment by zisoft** [comment]
I can reproduce with homebrew built

**Comment by MStraeten** [comment]
filed an issue upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/5853

**Comment by MStraeten** [comment]
unfortunately no changes upstream yet ...
