### ISSUE TITLE
Copy-pasting history stack does not paste white balance or orientation

### ISSUE THREAD

**Issue by jackhowes** [darktable-org/darktable#14587]
### Describe the bug

Copy history stack with a few edits including orientation and white balance.  Paste history stack to another image and although both are listed in what gets pasted, they were not actually pasted.  These two are both obvious edits.  Running version 4.2.0 under Windows 11.  This is reproducible every time.  I had been doing extensive copy paste edits on a previous project and manually had to add white balance to each image.  I did not spend the time to figure out what was happening during that project because I had to finish the project.

### Steps to reproduce

Make edits including orientation and white balance (selecting from pull down)
Copy history stack
Paste history stack to new image
White balance and orientation are not added to the new image.
But looking at the history stack for the image, these are listed as being performed.
But clearly orientation and white balance were not.

### Expected behavior

Actually paste the entire history stack to each new image.

### Where did you install darktable from?

distro packaging

### darktable version

4.2.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

Desktop running Windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
This is not an issue and by design. I suggest you to read manual. This is done to avoid some white balance or orientation paste on images that do not suit same settings. And it's not only those 2 modules. Copy/paste will also see changes to improve it on 4.4 release.

**Comment by Nilvus** [comment]
Oh, just a setting, you have a selective copy/paste option that allow you to select them. Manual could help you if needed (remember there's a help button on darktable UI. Just click on it then on option you want to read manual for.
