### ISSUE TITLE
Export Store Masks Segfaults

### ISSUE THREAD

**Issue by jdneumeyer77** [darktable-org/darktable#14591]
### Describe the bug

Exporting while store masks (tiff/ecf) is enabled causes a segfault.

### Steps to reproduce

Create a mask in a module (I had masks in exposure, tone eq) and export a tiff with store masks enabled. It exports an image, but without adding in the layer masks. However it segfaults while adding the layer masks to tiff/xcf file. I also tried 8/16/32 bit variants. 

### Expected behavior

Should export a tiff or xcf file with mask layers.

### Logfile | Screenshot | Screencast

Sorry to include -d all. The segfault is near the end.

[darktable_bt_CAPT51.txt](https://github.com/darktable-org/darktable/files/11580148/darktable_bt_CAPT51.txt)

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+2382~gd054351ec2

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Describe your system?

Manjaro
Linux 5.15.108-1-MANJARO
Nvidia 2060 GTI
64 GB of ram

/ Note a bit out of date. Will update and recompile latest to recheck. Opencl is also not working. So I didn't verify if it works correctly with OpenCL.

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I compiled master a couple weeks ago and exporting masks worked fine. I'll see if I can figure out the git version, but I was probably 4-8 weeks behind.

Other info:
Panasonic S5 raw

**Comment by TurboGit** [comment]
Should be fixed in master.

**Comment by jdneumeyer77** [comment]
Confirmed that fixed it. Thanks for the quick fix!
