### ISSUE TITLE
pic is black in the darrk room

### ISSUE THREAD

**Issue by jblmf** [darktable-org/darktable#14596]
<img width="1233" alt="Capture d’écran 2023-05-28 à 09 38 23" src="https://github.com/darktable-org/darktable/assets/134834535/11850bf9-6284-4124-a80a-fd2d0308d4f8">
<img width="1235" alt="Capture d’écran 2023-05-28 à 09 38 39" src="https://github.com/darktable-org/darktable/assets/134834535/417c1cde-6f23-4de6-a5b3-29b3604a7a04">

I can see all images correctly in the light room but once I want to visualize one in the darkroom it remains black... No matter which one is selected

**Comment by MStraeten** [comment]
ok, and based on which information someone can try to reproduce it?
you are aware of the issue template? https://github.com/darktable-org/darktable/issues/new?assignees=&labels=needs-triage&projects=&template=bug_report.yml

**Comment by jblmf** [comment]
thanks for your feedback, I have zero informatic knowledge but I'll do my best to provide as many details as possible using this template :)

**Comment by MStraeten** [comment]
no need for informatic knowledge, just follow the template and provide that info you can give from an users view. Best add the xmp thats created aside the raw file in its source directory as well as the image - usually that gives even more infos which modules were applied and so someone can try to reproduce with exactly your processing seetings
