### ISSUE TITLE
Module instances in older style not labelled with preset name due to raster mask index change

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#14590]
### Describe the bug

I have styles created earlier that when applied in b36676b6b no longer show module labels based on the presets, even though the styles contain module instances that were added simply using the preset. Such a style is attached.

[reimported-for-debugging.dtstyle.txt](https://github.com/darktable-org/darktable/files/11578568/reimported-for-debugging.dtstyle.txt)

### Steps to reproduce

1. Apply the attached style.
2. Check the active modules:
![image](https://github.com/darktable-org/darktable/assets/3177739/16522e5e-d7e2-495a-b1ea-7dd8d39fd245)
Notice that the two _diffuse or sharpen_ instances have no preset-based labels.
3. Set the bottom instance to _local contrast_, the top to _sharpen demosaicing: AA filter_.
The names are now shown, as expected:
![image](https://github.com/darktable-org/darktable/assets/3177739/7291e638-1c74-40e5-9cd5-c80d47e15826)
4. To prove that the settings were actually the same, hover over the modules in the history stack:
![image](https://github.com/darktable-org/darktable/assets/3177739/f6bdf513-19b9-49d2-ac23-75f5aa2a11e2)
![image](https://github.com/darktable-org/darktable/assets/3177739/d6848dcf-987b-4da0-83b5-0dcaefd55ebc)
The only difference is a darktable-internal change, the raster mask ID. Note that no raster mask is used.

### Expected behavior

The preset names should be used as labels.

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+2416~gb36676b6bf

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Describe your system?

Kubuntu. I don't think HW and SW details are important.

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
> I have styles created earlier that when applied

Probably the issue, can you check if you have the same issue after recreating the style? Lot of things has changed in the raster mask support (and id handling).

**Comment by ralfbrown** [comment]
Probably should be mentioned in the release notes.  Something along the lines of
> Due to internal changes, presets created with previous versions may not display the preset name in the history list unless recreated.

**Comment by kofa73** [comment]
> have the same issue after recreating the style

It was enough to update the style (re-assign the diffuse or sharpen presets to the two instances, then set them to _update_ in the style edit dialogue).

I'm just wondering if something like `update style_table set raster_mask_id = -1 where raster mask_id = 0` (did not check the table and column names) could not be made part of the DB migration from 4.2 to 4.4. I assume all styles are affected.

**Comment by TurboGit** [comment]
> could not be made part of the DB migration from 4.2 to 4.4.

No, what is needed here is a blend-op migration to replace the -1 with 0 (or the opposite, need to check).

**Comment by jenshannoschwalm** [comment]
> Just checked and we need to change the 0 to -1 (opposite). We need to do that only when raster_mask_source is not defined.

I think this is fully correct. If blendop is using a raster is should be `BLEND_RASTER_ID` otherwise `INVALID_MASKID`
