### ISSUE TITLE
Nikon Z8 support  lossless compressed 14bit

### ISSUE THREAD

**Issue by LViatour** [darktable-org/darktable#14593]
I sent a Nikon Z8 raw file in lossless compressed 14bit
Can you embed it for darktable?
The sensor is similar to the Nikon Z9

thanks in advance

**Comment by kmilos** [comment]
When the samples show up on RPU, I'll do the coeffs pretty quicky, maybe we make in time for the next release 😉

**Comment by kmilos** [comment]
> When the samples show up on RPU, I can do the coeffs pretty quickly, maybe we even make it in time for the next release 😉

P.S. Please upload the while set - even though he and he* are not supported yet, it's good to have in the database...

**Comment by LViatour** [comment]
I send the other versions at the end of next week.

I'm using darktable development version, so I'll get support quickly ;)

**Comment by kmilos** [comment]
> I send the other versions at the end of next week.

You'll have to resumvif lossless as well - ideally all outputs should come from same scene w/ same exposure and lens settings...

**Comment by kmilos** [comment]
> it would be good if I could already open my raw in darktable tomorrow;)

Just temporarily duplicate the section from Z 9 in cameras.xml and change it.

Also update the lensfun database, I added it there already 😉

**Comment by LViatour** [comment]
I duplicated the Z9 area in cameras.xml and renamed Z 8. Now darktable opens the raw but the image is black.....

**Comment by kmilos** [comment]
> Now darktable opens the raw but the image is black.....

Remove from library and import again.

**Comment by LViatour** [comment]
thanks it works!

**Comment by kmilos** [comment]
Hm, I just checked w/ the latest ADC 15.3.1 that added support for the Z 8, and the color matrix is not identical to the Z 9, so that duplicate might not produce accurate colors. The new coeffs are in the linked rawspeed PR.

**Comment by kmilos** [comment]
This is now merged into master and supported in nightly builds, so ok to close.
