### ISSUE TITLE
Fuji film X A7 not supported in Dark table

### ISSUE THREAD

**Issue by bimalmithran** [darktable-org/darktable#14599]
Could not open the RAW images from fuji film XA7 in the DarkTable Software

![image](https://github.com/darktable-org/darktable/assets/11942609/69a5da06-8e3f-49c5-83fe-a1cc96e4650e)

**Comment by kmilos** [comment]
Does this camera have more than one raw output mode? If so, uncompressed and lossless compressed are expected to work. Fujifilm lossy compression is not currently supported.

**Comment by kmilos** [comment]
It's actually not supported list, I'll take a closer look when I get a chance...

**Comment by kmilos** [comment]
@ralfbrown This is now merged into master and supported in nightly builds.
