### ISSUE TITLE
Switch crop between portrait and landscape orientation button crop to wrong size.

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/darktable#14604]
![2023-05-28_23-08-13](https://github.com/darktable-org/darktable/assets/54812718/1b689d3f-e729-4102-8dba-58ee7ac6eb3c)
### Describe the bug

In the crop module 
Pressing the Switch crop between portrait and landscape orientation button (circle with an arrow) crop to wrong size. 
It can be interesting the way it is right now. But this feature would be very important to add.

Eg: A 1309 x 1962 crop, pressing the switch crop button change it to 
to 1309 x 873 (on an Original image orientation aspect ratio)

It should change it to 1962 x 1309 instead.

![2023-05-28_23-08-13](https://github.com/darktable-org/darktable/assets/54812718/b7dd5e8d-1954-4a75-ae5f-943ee8300115)

### Steps to reproduce

In DarkRoom. On a portrait size picture.
In crop module.
Do a crop. 
Then press the button to switch the orientation.

### Expected behavior

Eg: A 1309 x 1962 crop, pressing the switch crop button change it to  to 1309 x 873 (on an Original image orientation aspect ratio)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

10 

### Describe your system?

16 gb ram. Asus mother board. 995 CPU.

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

Nvidia 9600GT

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Same behavior on linux version - Ubuntu.

**Comment by ActarusLeGrand** [comment]
It's not fixed.

**Comment by MStraeten** [comment]
it's no bug, it's a change request ;)

**Comment by ActarusLeGrand** [comment]
Where is the request section?
