### ISSUE TITLE
darktable forgets $(WIDTH.CROP) $(HEIGHT.CROP) from time to time.

### ISSUE THREAD

**Issue by oijn** [darktable-org/darktable#14609]
### Describe the bug

I use `$(WIDTH.CROP) $(HEIGHT.CROP)` in various places in darktable: watermark, image information line, thumbnail overlay text etc...   The reasoning - is to know what the original pixel dimensions were before exporting at different sizes.

When editing and processing an image from start-to-finish and crop module was used as part of the end-to-end editing.  The `$(WIDTH.CROP) $(HEIGHT.CROP)` are displayed correctly in the different locations where it is used at the end of the processing.

However, sometimes, for no real reason - maybe some days later - darktable forgets what the `$(WIDTH.CROP) $(HEIGHT.CROP)` values were and displays zero instead.  To get `$(WIDTH.CROP) $(HEIGHT.CROP)` displaying correctly again - the crop module has to be modified in some way.  Sliding and replacing the crop box or other activity.  Just turning on and off the crop module doesn't update `$(WIDTH.CROP) $(HEIGHT.CROP)`.

Also if processing history is copied and pasted via lighttable - the crop module is applied and the image is cropped correctly.  But `$(WIDTH.CROP) $(HEIGHT.CROP)` is not updated to show the actual values.  When processing history is applied via lighttable - `$(WIDTH.CROP) $(HEIGHT.CROP)` always displays zero.

Another instance is when duplicate images are created via lighttable and edited with darktable.  Even if the crop module is changed - only the last edited image displays `$(WIDTH.CROP) $(HEIGHT.CROP)` correctly - all the other duplicates only display zero.

### Steps to reproduce

1. edit & process an image start-to-finish and utilize the crop module.
2.  for example use a simple text watermark using `$(WIDTH.CROP) $(HEIGHT.CROP)`
3. the text `$(WIDTH.CROP) $(HEIGHT.CROP)` is displayed correctly
4. leave the image and return to lighttable.

5. copy the processing history from the edited image to a new image.
6. the text `$(WIDTH.CROP) $(HEIGHT.CROP)` will display zero instead incorrectly - despite the crop being correctly applied to the new image.
7. the only way to update `$(WIDTH.CROP) $(HEIGHT.CROP)` is to edit the image - go to crop module and change the crop box location or size or something to force the crop action to be rerun.
8. Then the `$(WIDTH.CROP) $(HEIGHT.CROP)` will be displayed correctly.

9. Then in lighttable create a duplicate of an image with the `$(WIDTH.CROP) $(HEIGHT.CROP)` watermark and that has been cropped.
10. The text `$(WIDTH.CROP) $(HEIGHT.CROP)` will display zero instead incorrectly - despite the crop being correctly applied.

11. Regarding when darktable forgets the `$(WIDTH.CROP) $(HEIGHT.CROP)` values after some time - I have not been able to identify a factor.  It just happens randomly - some images are affected - others are not.  The only way to get `$(WIDTH.CROP) $(HEIGHT.CROP)` to display correctly is to - go to crop module and change the crop box location or size or something to force the crop action to be rerun.

For completeness the full simple text watermark I use is : 
`$(FILE.NAME).$(FILE.EXTENSION) ($(ROLL.NAME)) | $(IMAGE.EXIF) $(EXIF.EXPOSURE.BIAS)EV | $(MODEL) | $(LENS) | ($(WIDTH.CROP)x$(HEIGHT.CROP))px | ($(EXIF.YEAR)-$(EXIF.MONTH)-$(EXIF.DAY) $(EXIF.HOUR):$(EXIF.MINUTE)) ©$(YEAR)-$(MONTH)-$(DAY)`

### Expected behavior

darktable should remember the `$(WIDTH.CROP) $(HEIGHT.CROP)` values no matter how the crop module is activated.  Via end-to-end editing or via application of processing history via lighttable and by creating duplicates.

### Where did you install darktable from?

flatpak

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

NEON latest updates.

### Are you using OpenCL GPU in darktable?

No

**Comment by oijn** [comment]
Seems github has interpreted '$' as font change.  For completeness my full simple text watermark is :
`$(FILE.NAME).$(FILE.EXTENSION) ($(ROLL.NAME)) | $(IMAGE.EXIF) $(EXIF.EXPOSURE.BIAS)EV | $(MODEL) | $(LENS) | ($(WIDTH.CROP)x$(HEIGHT.CROP))px | ($(EXIF.YEAR)-$(EXIF.MONTH)-$(EXIF.DAY) $(EXIF.HOUR):$(EXIF.MINUTE)) ©$(YEAR)-$(MONTH)-$(DAY)`

**Comment by MStraeten** [comment]
better edit this in your issue to have one place with all information in a proper way
