### ISSUE TITLE
Manual lens correction

### ISSUE THREAD

**Issue by eugenialoli** [darktable-org/darktable#14602]
Hi, my husband and I are usually shooting with vintage or modern manual lenses (e.g. 7/TT/Artisans), and sometimes we need to lens-correct. It would be great if there was a way to correct pinching/bulging manually, since the current lens correction module only works for modern powered lenses. Certainly, fixing pinching/bulging manually doesn't take into account all cases of lens problems, and it's just eyeballing, but it's a big, big start! Thank you!

**Comment by ralfbrown** [comment]
Duplicate of #1990.
