### ISSUE TITLE
rework the legacy support to ease maintenance

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14608]
This is good first contribution for whoever want to take it.

The problem:

For the blend mask (blend.c) we do the migration in one step. That is from whatever old version to the latest one. See for example `dt_develop_blend_legacy_params`, we have:

```
  if(old_version == 1 && new_version == 13)
  {
    /** blend legacy parameters version 1 */
    typedef struct dt_develop_blend_params1_t
    {
      uint32_t mode;
      float opacity;
      dt_mask_id_t mask_id;
    } dt_develop_blend_params1_t;

...

    return FALSE;
  }

  if(old_version == 2 && new_version == 13)
  {
    /** blend legacy parameters version 2 */
    typedef struct dt_develop_blend_params2_t
    {
      /** blending mode */
      uint32_t mode;
      /** mixing opacity */
      float opacity;
      /** id of mask in current pipeline */
      dt_mask_id_t mask_id;
      /** blendif mask */
      uint32_t blendif;
```

This is a maintenance nightmare. What would be good is to rewrite this routine to have incremental update, that is if old_version is 1 we only update to version 2. If old_version is 2 we only update to version 3... And the `dt_develop_blend_legacy_params` should be called in a loop as many time as needed until the last step has done the migration to the last version of the module given by:

`#define DEVELOP_BLEND_VERSION (13)`

This way, when a new version is introduced, it is not required to change all previous path (see my last change in commit c9442c207f3291a392a830d8a9355347c2b015ef) which is cumbersome and could introduce issues that it is almost impossible to test (we don't have a set of blend params in all version to ensure all are ok). Only a single path is changed to take the previous version and migrate it to the latest one.

More ambitious but in the same idea it would be good to do the same for the iop legacy_params. For an idea of what should be done only can look at the lib legacy_params which is working one version at a time. See in `lib.c` routine `_update_params`:

```
static void *_update_params(dt_lib_module_t *module,
                            const void *const old_params,
                            size_t old_params_size,
                            int old_version,
                            const int target_version,
                            size_t *new_size)
{
  // make a copy of the old params so we can free it in the loop
  void *params = malloc(old_params_size);
  if(params == NULL) return NULL;
  memcpy(params, old_params, old_params_size);
  while(old_version < target_version)
  {
    size_t size;
    int version;
    void *new_params = module->legacy_params(module, params, old_params_size,
                                             old_version, &version, &size);
    free(params);
    if(new_params == NULL) return NULL;
    params = new_params;
    old_version = version;
    old_params_size = size;
  }
  *new_size = old_params_size;
  return params;
}
```

**Comment by TurboGit** [comment]
After all maybe not so ambitious for the IOP legacy_params. We can keep current legacy_code in all IOP and adjust it a bit to be able to call it multiple times. For example, a module is migrated to version 9, the first migration as it is today from say version n to 8. The new version must be returned and if < 9 the loop continued with old_version to 8. The new code (in the same routine) will do the one step from 8 to 9.

We need to change legacy_params to return the new version which has been handled, so probably something like:

```
gboolean legacy_params(dt_iop_module_t *self,
                       const void *const old_params,
                       const int old_version,
                       void *new_params,
                       int *new_version)
```

And the conditional inside should not be based on new_version but should return the migrated version into new_version. Take for example exposure where new_version was 6.

```
  if(old_version == 2 && new_version == 6)
  {
   ...
    return 0;
  }
  if(old_version == 3 && new_version == 6)
  {
    ...
    return 0;
  }
  if(old_version == 4 && new_version == 6)
  {
    ...
  }
```

This should be now:

```
  if(old_version == 2)
  {
   ...
    *new_version = 6;
    return 0;
  }
  if(old_version == 3)
  {
    ...
    *new_version = 6;
    return 0;
  }
  if(old_version == 4)
  {
    ...
    *new_version = 6;
  }
```

Now adding a new version will just need a new conditional at the end:

```
  if(old_version == 6)
  {
    ...
    *new_version = 7;
  }
```

And so we don't need to mess with previous code at all.

**Comment by TurboGit** [comment]
If anyone want to work on this, do not hesitate to ask questions... I think I understand how all this could be done and it will be very helpful for the project. TIA.

**Comment by ralfbrown** [comment]
denoiseprofile.c already does incremental updates internal to `legacy_params` by employing recursive calls.  That might be a useful model for other iops.

**Comment by dterrahe** [comment]
Done?

**Comment by TurboGit** [comment]
Yes :)

As a side note I'm away from a computer most of the time for the next 15 days. So I'm not very active at the moment.

**Comment by dterrahe** [comment]
Doing something even funner, I hope? Have a good break!
