### ISSUE TITLE
Wrong order of auto-apply preset application

### ISSUE THREAD

**Issue by cabradaabra** [darktable-org/darktable#14617]
### Describe the bug

I created a preset for the white-balance module for my Olympus camera as it is suggested in the manual für the color calibration module and set it to auto-apply for that camera.

Unfortunately, when I open a new picture in darkroom, my preset is applied after the default preset (scene-referred-default) for the color calibration module, so that I always have to reset the color calibration module to take my camera-specific white-balance preset into account.

### Steps to reproduce

1. Create a white-balance preset for a specific camera and set it to auto-apply
2. open a new picture taken with this camera

### Expected behavior

darktable should apply white-balance auto-apply presets before color calibration presets (maybe follow pixel pipe order)

### Where did you install darktable from?

an online forum

### darktable version

4.3.0+2427~g8c49e89404

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10, also on Manjaro with dt 4.2.1

### Are you using OpenCL GPU in darktable?

None

**Comment by jenshannoschwalm** [comment]
Should be working in 4.4 :-)
