### ISSUE TITLE
Middle Mouse Click Scroll

### ISSUE THREAD

**Issue by MitchWoodin** [darktable-org/darktable#14636]
I find that often when trying to scroll to different sections of the app, instead of scrolling to the setting I'm trying to adjust I'll adjust a random slider. Also I frequently use a tablet while working so to be able to scroll the menus I either have to switch to a mouse or click+drag the scroll bar. 

I'd like to be able to middle mouse click+drag to scroll panels like the modules window. I'd like the behaviour to mimick the way Blender currently works. It's mainly a quality of life adjustment that could be made so is a fairly minor issue however I do think it would be a very welcome addition and would make editing more efficient in darktable.

**Comment by ActarusLeGrand** [comment]
Yes I agree with this one, it should be a default or at least an option in preference so people accustomed to the actually way can keep it and those who don't like it can change it too.
 I ended changing sliders without knowing it myself, and the sliders are way to think and hard to grab with the mouse.

**Comment by dterrahe** [comment]
For the first point, see https://darktable-org.github.io/dtdocs/en/preferences-settings/miscellaneous/
`mouse wheel scrolls modules side panel by default`
The "intended" way to scroll side panels is to have dt full screen and fling your mouse all the way to the right or left of the screen and then scroll, so it won't interfere with sliders unless specifically hovered. I found this not hard to get used to and then very convenient. Obviously this doesn't work well for everybody (tablet and multiscreen for example) hence the option to switch off slider scrolling.

For the second point; this could be implemented as long as no widget responds to a middle click (either intentionally or unintentionally; the module reset button being one of the latter that I noticed in very limited testing). The UI police will have to opine on whether this would be a _desirable_ feature.

**Comment by MitchWoodin** [comment]
I really like that preference option for mouse use. I still think it's leaving out tablet users not being able to scroll efficiently. (although I may very well be in the minority using a tablet). I am on windows and the functionality of middle mouse scrolling menus is very program specific. Browsers for instance tend to have it. Although I may be an edge case with using a tablet if there are no clashes with the middle mouse button I think it should be a fairly unintrusive change?

**Comment by ActarusLeGrand** [comment]
You could make the vertical slider wider, that would help everybody.
