### ISSUE TITLE
[Feature request] More "traditional" illuminant color selection

### ISSUE THREAD

**Issue by asdkant** [darktable-org/darktable#14639]
# Is your feature request related to a problem? Please describe.
For a while I've tried to stick with the scene-referred workflow because I understand the benefits, but color correction is always a pain point.

As I see it, what I do in that step is navigate the color space to select the color of the light in the scene... which is very similar to what I'd do with traditional white balance (select the color of "white" instead of "the light in the scene", but in practice it amounts to the same thing). The problem I have is not with the idea of what I'm doing, but with the tools I'm provided to navigate that color space.

In traditional white balance you get two sliders, one for the "blue-yellow" (b*) axis and one for the "green-magenta" (a*) axis in the L*a*b* color space, and that has proven useful and ergonomic to navigate the color space for this particular step. What I have now (in particular with custom illuminant) is sliders for hue and chroma, which I don't find ergonomic for the task at hand.

# Describe the solution you'd like
A way to switch to the more traditional a*/b* sliders instead of using hue/chrome ones.

# Alternatives
This could be a toggle for the custom illuminant, or a different illuminant with another name. I'm not aware of the finer details that would make one or the other options preferable.

# Additional context
I tried to look for an issue discussing this, but I could not find anything relevant to this particular point (there were a lot of bug reports, that are not exactly what I want to bring to the table here).

Let me stress that this is about UI/UX, ergonomics, and human interaction. It is **NOT** about the underlying process and how it works, I am not arguing against the scene-referred workflow and its benefits.

**Comment by wpferguson** [comment]
The easiest way to understand what the sliders are doing, is to use the color picker and and pick a (hopefully neutral) spot.  Adjust the hue and chroma sliders while observing the changes in the RGB values.

**Comment by asdkant** [comment]
> The easiest way to understand what the sliders are doing, is to use the color picker and and pick a (hopefully neutral) spot. Adjust the hue and chroma sliders while observing the changes in the RGB values.

I understand, in theory, what the sliders do. The problem is that it's not ergonomic (in **MY** experience) for the goal of doing color correction.

**Comment by paperdigits** [comment]
If you calibrate your camera to a D65 white balance, you'll get much better readouts from the color calibration module. 

The other option is to not use if it isn't working for you. You can entirely use the white balance if that is more ergonomic for you.

**Comment by MStraeten** [comment]
> The problem is that it's not ergonomic (in **MY** experience) for the goal of doing color correction.
Congratulations to your experience - I myself don’t have an absolute color temperature view so I can do a white balance just by a color temperature number …
