### ISSUE TITLE
Crop with hanker as the center of the image with holding ALT key.

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/darktable#14642]
It allow to crop and 4 sides crop toward or away from the center of the crop frame. The crop frame get bigger or smaller 4 sides at same time. It's useful and save clicking time. 

* Description *
In crop module, 
when you perform a crop, 
you can hold ALT and click and drag an edge or a corner 
and **4 sides moves at same time** **toward the center** or **away from the center** depending on wish direction you drag. And it change the crop area as hanker in the center.

**Alternatives**
I don't know.

**Additional context**

![Crop toward center 1](https://github.com/darktable-org/darktable/assets/54812718/6736f5e2-bc0a-4330-b5c7-b86159d47ed3)
![2023-06-04_22-05-03](https://github.com/darktable-org/darktable/assets/54812718/63765adc-5ec7-43c9-9722-bb9abc37c404)
![2023-06-04_22-16-13](https://github.com/darktable-org/darktable/assets/54812718/e0dd7707-e1e1-4e65-9853-192c31d97f0a)

**Comment by dterrahe** [comment]
For me even just holding _shift_ on an edge allows me to _enlarge_ the crop (_ctrl_ is not needed). I had not noticed because, indeed, _reducing_ the cropped area this way doesn't work which looks like a bug as you say.
