### ISSUE TITLE
Please bring back lens corrections for Nikon D5600

### ISSUE THREAD

**Issue by rafalkrupinski** [darktable-org/darktable#14655]
### Describe the bug

Trying to apply `lens correction` module to photos made with Nikon D5600. 
Plugins it complains about unknown camera - `camera/lens not found`. In the list of Nikon cameras, after D5500 there's D60.
It used to work sometime before 4.0.

### Steps to reproduce

- Open raw made with Nikon D5600 in darkroom
- Open and enable lens correction - error
- Open list of cameras, Nikons - D5600 is missing

### Expected behavior

Darktable should have Nikon D5600 profile

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian 11.7

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by rafalkrupinski** [comment]
Oh, and the error message doesn't disappear even after selecting another camera, like Nikon D5500

**Comment by MStraeten** [comment]
did you update your lensfun database?

**Comment by rafalkrupinski** [comment]
That helped. Thank you!

For future reference, on Debian I had to install `liblensfun-bin`
