### ISSUE TITLE
crash: LMMSE + WB "user modified"

### ISSUE THREAD

**Issue by apostel338** [darktable-org/darktable#14669]
### Describe the bug

When using the combination of LMMSE + white balance module set to "user modified", dt crashes.

When setting to "user modified", all channel coefficients are initially set to 0.000 which leads to a black image with all (edit: actually only tested a few) other demosaic methods, but crashes when LMMSE is used. Changing at least one channel to >0 prevents crashing.

### Steps to reproduce

Set demosaic to LMMSE
Set WB to "user modified"
-> Crash

or do so the other way around.

### Expected behavior

not crash

### Logfile | Screenshot | Screencast

[-d all.txt](https://github.com/darktable-org/darktable/files/11681720/-d.all.txt)

[bt.txt](https://github.com/darktable-org/darktable/files/11681794/bt.txt)

### Where did you install darktable from?

self compiled

### darktable version

self built 4.3.0+2484~g4fa455b9f / nightly+1.g68782ddc96 AppImage

### What OS are you using?

Linux

### What is the version of your OS?

Tumbleweed

### Describe your system?

Betriebssystem: openSUSE Tumbleweed 20230525
KDE-Plasma-Version: 5.27.5
KDE-Frameworks-Version: 5.106.0
Qt-Version: 5.15.9
Kernel-Version: 6.3.2-1-default (64-bit)
Grafik-Plattform: X11
Prozessoren: 12 × AMD Ryzen 5 3600 6-Core Processor
Speicher: 31,3 GiB Arbeitsspeicher
Grafikprozessor: AMD Radeon RX 6600
Hersteller: Gigabyte Technology Co., Ltd.
Produktname: B450 I AORUS PRO WIFI

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

amdgpu 23.0.0-1.2 / rocm 5.5.0.50500

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Tried with clean .config folder, fresh xmps, opencl on/off.

**Comment by ralfbrown** [comment]
Confirmed that clicking "user defined" sets coefficients to all zeros.  But I can no longer reproduce after manually changing one of the coefficients, shutting down dt, and restarting.  Looks like something isn't properly initialized in the darktablerc until manually changed, but unfortunately I didn't think to make a copy first to run a diff.

LMMSE shouldn't crash when fed zero coefficients, but it shouldn't be given them, either.

**Comment by jenshannoschwalm** [comment]
The problem "starts" with a fresh image history and setting to "user-defined" color, coeffs will be zero.

**Comment by apostel338** [comment]
Made a build with #14675 and #14676. Can confirm that both fixes work. Thank you.
