### ISSUE TITLE
Samsung Galaxy S22 (SM-S901U)

### ISSUE THREAD

**Issue by william-lohan** [darktable-org/darktable#14667]
Uploaded landscape raw that won't open in Darktable's darkroom to RPU

**Comment by LebedevRI** [comment]
Does that --camera-- device produce both kinds of RAW's?
If so, would be good to have both samples (of the same scene).

**Comment by kmilos** [comment]
Should also be resolved by https://github.com/darktable-org/darktable/commit/ad2feeb830e9d3a1b7c00959cdc30339fc7e091a
