### ISSUE TITLE
Crop rules disappear when in fullscreen mode

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#14678]
### Describe the bug

In darkroom mode, after CTRL-W to obtain a fullscreen view, if you start using the crop module, the rules doesn't appear.

### Steps to reproduce

1. Go in Darkroom 
2. press ctrl-w 
3. open crop module by pressing the related shortcut ('c' on my setup)
4. no crop rules are shown

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+2465~g5e38243984

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2 LTS

### Describe your system?

Dell Inc. XPS 15 9550
16.0 GiB
Intel® Core™ i7-6700HQ CPU @ 2.60GHz × 8
NVIDIA Corporation GM107M [GeForce GTX 960M] (XPS 15 9550) 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation GM107M

**Comment by dterrahe** [comment]
What you want is not the intended goal of the fullscreen _preview_ mode that is toggled with the `w` key.

If you want to _edit_ in full screen, you can switch to fullscreen mode using `F11` and then hide all panels with `TAB`. This will allow you to crop, color pick, draw masks, manipulate the tone equaliser by scrolling over an area, and all other modes of the center canvas, all via shortcuts.

**Comment by PaoloAst** [comment]
Dear dterrahe,

thank you for you answer. I think you're right, so I'm going to close the issue.
By the way it could be better to disable the "not usable" shortcuts in full screen mode

BR
