### ISSUE TITLE
GMIC not found/available through homebrew-based build

### ISSUE THREAD

**Issue by apfelkraut** [darktable-org/darktable#14670]
PREREQUISITE

- macOS 13.4 Ventura, probably as well valid for earlier versions
- m1 (arm), probably as well valid for Intel
- homebrew-based build environment

STEPS TO REPRODUCE

1. Build darktable from source using homebrew build instructions
2. Observe the output of the cmake configuration

CURRENT BEHAVIOUR

GMIC is not found and not integrated, though the build completes successfully.

```
[...]
-- GMIC not found
[...]

-- The following OPTIONAL packages have not been found:

 * GMIC
[...]
```

EXPECTED BEHAVIOUR

In an effort that the homebrew-based build has the same content/scope as the official MacPorts-based build, GMIC should be found and integrated during build.

STARTING POINTS

- Not sure for which functionality of darktable GMIC is required. According to the manual it is at least needed for lut 3D when working with compressed format .gmz: https://docs.darktable.org/usermanual/4.2/en/module-reference/processing-modules/lut-3d/ 
- This issue is supposedly not related to darktable and needs fixing upstream in homebrew to prepare the package properly as expected by the darktable build process
- This issue was already briefly discussed here: https://github.com/darktable-org/darktable/pull/13345#issuecomment-1399360560
- Homebrew formula: https://github.com/Homebrew/homebrew-core/blob/821f08d6439afae6ab7fe0e24622b57b532017f8/Formula/gmic.rb
- MacPorts portfile: https://github.com/macports/macports-ports/blob/master/science/gmic/Portfile

**Comment by fabiosirna** [comment]
I had to install it manually (brew install gmic). Also:
- libtiff is missing
- jsonschema is deprecated (but is in the hb script)

I wrote [some notes](https://fabiosirna.com/notes/darktable) and you can also find some M1 builds to test.

**Comment by zisoft** [comment]
Homebrew does not install a`libgmic.dylib`, only a `libgmic.a`

**Comment by kmilos** [comment]
> This issue is supposedly not related to darktable and needs fixing upstream in homebrew to prepare the package properly as expected by the darktable build process

If not reported already upstream, please do so. @apfelkraut

**Comment by kmilos** [comment]
> jsonschema is deprecated

This is not just on macOS, it would need to be updated in general for all platforms. Please submit a PR if you have a fix. @fabiosirna

**Comment by zisoft** [comment]
@fabiosirna: libtiff gets installed as a dependency of one of the other packages, i.e: graphicsmagick:

```
~ brew info graphicsmagick
==> graphicsmagick: stable 1.3.40 (bottled), HEAD
Image processing tools collection
http://www.graphicsmagick.org/
/usr/local/Cellar/graphicsmagick/1.3.40_2 (310 files, 11.5MB) *
  Built from source on 2023-04-26 at 22:17:05
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/graphicsmagick.rb
License: MIT
==> Dependencies
Build: pkg-config ✔
Required: freetype ✔, jasper ✔, jpeg-turbo ✔, jpeg-xl ✔, libpng ✔, libtiff ✔, libtool ✔, little-cms2 ✔, webp ✔
```

This gets resolved for dozens of other packages as well so there is no need to explicitly list it in the package list

**Comment by kmilos** [comment]
> libtiff gets installed as a dependency of one of the other packages

While this is true, I've also come to prefer listing the direct dependencies of draktable explicitly for Windows building/packaging (it's ok to skip the indirect ones). This let's me e.g. immediately see if dt needs to be rebuilt if a direct dependency had a majopr update w/ an API change etc...

**Comment by luzpaz** [comment]
any progress here ?

**Comment by justin-ashworth-research** [comment]
I got the latest source (4.7.something) to build with GMIC support in macOS 14.3. I built the GMIC source and then put all of the relevant .so and .h files where the darktable build was apparently looking for them (compile error messages reported where that is, fortunately).

Thereafter the darktable build reports finding GMIC, and will load CLUTs (but not cache them). So it is not 'fixed'

4.6.0 did behaved the same way--that macOS release seems to also have been built with [limited?] GMIC support

**Comment by zisoft** [comment]
After some analyzing I found that `libgmic.x.x.x.dylib` is correctly build during install via homebrew. It is just not installed/linked. Same is true for `gmic.h`.

Here is a method to get the missing files installed in the homebrew environment so that the darktable build process is able to find GMIC:

In the terminal enter`brew edit gmic`. This opens the gmic formula in the default editor.

Insert the following lines at position 65:

```
    Dir.chdir "src"
    ln_s "libgmic.#{version}.dylib", "libgmic.dylib"
    Dir.chdir ".."

    lib.install "src/libgmic.#{version}.dylib"
    lib.install "src/libgmic.dylib"
    include.install "src/gmic.h"
```

Now you need to reinstall gmic from source:

```
export HOMEBREW_NO_INSTALL_FROM_API=1
brew reinstall --build-from-source gmic`
```

Then recompile darktable.

**Comment by zisoft** [comment]
I have now opened a PR at [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/163735)

Let's see if it get merged.

**Comment by zisoft** [comment]
PR is merged, now the homebrew-core includes the necessary gmic.dylib.

So I close this issue.
