### ISSUE TITLE
.dng files from software will not open in darktable, i.e. Topaz Photo AI. This failure is preventing users from utilizing this AI program and other Topaz programs. Solution is to correct the inability to open software generated .dng files.

### ISSUE THREAD

**Issue by Ribble59** [darktable-org/darktable#14679]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by kmilos** [comment]
This is [already fixed on master](https://github.com/darktable-org/rawspeed/commit/9c5e0f97a1816d2b1538a1a508092b8dd7e53164) and will be working in the upcoming dt 4.4 version.

**Comment by Ribble59** [comment]
Thank you for your quick response. When will 4.4 be released?

**Comment by kmilos** [comment]
> When will 4.4 be released?

[Soon](https://github.com/darktable-org/darktable/wiki/Releases-cycle), hopefully.

**Comment by Ribble59** [comment]
I am new, as you can tell. Where do I find the "issue template" for future reference?

**Comment by kmilos** [comment]
> Where do I find the "issue template" for future reference?

You were confronted with it when you clicked "New issue". You decided to ignore it and not fill it in....

**Comment by Ribble59** [comment]
Got it. Thanks for your help. Deeply appreciated. Damn noobies!

**Comment by kmilos** [comment]
@jenshannoschwalm Tag w/ 4.4 please?
