### ISSUE TITLE
Dynamic Range Mapping view does not show shaded areas that highlight scene->disaply mapping

### ISSUE THREAD

**Issue by vyroc** [darktable-org/darktable#14688]
### Describe the bug

The "dynamic range mapping" view in the filmic RGB module is missing the "shaded area" that is supposed to indicate how the scene dynamic range is mapped into the display. The module still works, but you need to adjust the white relative exposure and black relative exposure largely blind.

See the screenshot below - there's no visible shaded area in the view.

`
 darktable --version
this is darktable 4.2.1
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled

$ apt-cache policy darktable
darktable:
  Installed: 4.2.1-3
  Candidate: 4.2.1-4
  Version table:
     4.2.1-4 500
        500 http://ftp.uk.debian.org/debian sid/main amd64 Packages
`

### Steps to reproduce

Open any image in the darkroom, open filmic rgb, switch view to the "dynamic range mapping".

### Expected behavior

show the display - > scene mapping in the UI

### Logfile | Screenshot | Screencast

![2023-06-10_01-28](https://github.com/darktable-org/darktable/assets/136134921/952154f0-80c0-4296-8455-a61359b74117)

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian unstable

### Describe your system?

Debian Linux , kernel 6.1.0, graphics AMD using the default X11 (open source) driver with opencl from the ROCM stack.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

   description: VGA compatible controller                       product: Navi 23 [Radeon RX 6650 XT / 6700S / 6800S]                       vendor: Advanced Micro Devices, Inc. [AMD/ATI]

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Happens constantly

**Comment by MStraeten** [comment]
are you talking about: 
<img width="256" alt="image" src="https://github.com/darktable-org/darktable/assets/39386816/d379d1e8-2898-44dd-a67e-1110df2c5016">
If so, then check your css settings.
Or what exactly you're missing?

**Comment by wpferguson** [comment]
The shaded area above shows the latitude setting.  Go to the look tab in filmic rgb and adjust the latitude to get the shaded area that you are looking for.

**Comment by vyroc** [comment]
Ah, that's the missing piece. I'd tried multiple themes in case it was CSS related, but I failed to realise that that range was controlled by the latitude setting. Thanks very much for the pointer.
