### ISSUE TITLE
Smart image pre loading

### ISSUE THREAD

**Issue by GonziHere** [darktable-org/darktable#14694]
Hello,
**Is your feature request related to a problem? Please describe.**
I open Darktable (lighttable mode) and go through the family photos to remove all needless duplicates (5 photos in a row of someone, quickly picking one or two best shots). I do this by having the app fullscreen on 4K 40" monitor. (Btw, why the image won't actually fill the view - see screenshot?)

The issue is, that when I go to the next photo, I have to wait (about a second) for it to load. My typical usecase now is to click say 5 times forward, then click 5 times back and then pick between those 5 loaded images that are in memory.

**Describe the solution you'd like**
Different thumbnail sizes, disable raw preview and so on didn't help. What would help would be pre-fetching the next image (or few) automatically. You clearly use cache for "last x images", so the only thing you could add is to automatically build the cache record even for image that's not visible yet, but very likely will be in near future. As in, user sees image 14, so let's make sure that the image 12,13,15,16 are also ready for viewing.

**Alternative**
I wouldn't mind a different view altogether for "1 image per page" zoom level. It could implement this feature and also automatically select viewed image (disabled selection of a different one). As DT differentiates between selected image, hovered image and none, it often happens that I see image 4, yet I still rate image 1. I do think that my current pain point is linked to a "misuse" of 1 file zoom, so to speak.

**Additional context**

![image](https://github.com/darktable-org/darktable/assets/8655073/56e78edc-1fd3-49b3-9118-a64eb3bf9d31)

**Comment by pitbuster** [comment]
Do you do your selection in darkroom or in lighttable? By your description, I guess you do the first, but I recommend you to do the second.

**Comment by ralfbrown** [comment]
If you want the preview to completely fill the screen, **don't** use filemanager or zoomable set to one image per row.  As you see,  those display the image inside a square tile.  You want to use the full preview layout by clicking on the right-most of the five icons at bottom center (before you hide all of the panels surrounding the center view) or typing 'f'.
https://darktable-org.github.io/dtdocs/en/lighttable/lighttable-modes/full-preview/

**Comment by GonziHere** [comment]
@ralfbrown I know that there are views that will fill whole screen. I don't know why the viewbox is limited when I also want to see the interface. Is there some good reason for that limitation?

@pitbuster I meant Darktable (app) with lightroom (mode). I didn't mention darkroom (mode) anywhere, but I've edited description to specify lighroom for clarity, thanks.

**Comment by ralfbrown** [comment]
Having a single image display differently than 2,3,...23 per row is equivalent to adding a new view mode, and will require considerable additional code.

**Comment by GonziHere** [comment]
@ralfbrown since you are a collaborator, I won't argue, but I'm surprised by it (I've assumed that it would basically be a copy of existing code).

Anyways, my biggest issue isn't the "limited viewbox" (which is broken for single image, but whatever)
![image](https://github.com/darktable-org/darktable/assets/8655073/cc5c80e4-8282-42a1-8e7f-b4d0746f0ab8)

My primary issue is that when i go to the next picture, I'm waiting for it's loading, even though lightable is able to cache images ( as shown by moving forward and back on visited photos without issues). So, the core issue is already solved in the code. The only thing missing is to fill said cache even for images that are "**just** off screen" (say next row). It would massively increase perceived performance of lighttable for (IMO) a small engineering effort.

**Comment by darkelectron** [comment]
> I don't know why the viewbox is limited when I also want to see the interface.

Which "interface" do you want to see here, because you can still toggle all the other panels in all the lighttable modes.

> I've edited description to specify lighroom for clarity, thanks.

I think you mean lighttable.

**Comment by GonziHere** [comment]
@darkelectron 
Ok, maybe I'm missing something - could you please provide a screenshot (and how to get there), where I'll see Darktable - lighttable interface and my photo without the red filler space as shown in the comment https://github.com/darktable-org/darktable/issues/14694#issuecomment-1586151022 ? I can either see interface and small photo, or a big photo without any interface.

**Comment by apostel338** [comment]
@GonziHere 

Press `f` and then toggle the panels with `Ctrl + Shift + l / r / t / b`.

![Screenshot_20230611_155402](https://github.com/darktable-org/darktable/assets/96216629/8714ce77-48bb-49d2-ad2c-ef8222e45881)

**Comment by GonziHere** [comment]
Ok, so my whole issue was that I didn't know that I could enable those panels for the _full preview layout_. Enabling panels there solved my small gripe with preview size. What's much more interesting for me is that this mode has always "no photo selected" (great!), every action (open darkroom, rate image, copy style, etc) happens on the image that's in view (great!) even though mouse doesn't hover over it (wonderful!).

The cherry on top is that with this mode, the next image is actually pre fetched, so clicking through them is a breeze, which was my main issue for this ticket.

I'm slightly frustrated that it's hidden like that (I didn't know that I could enable those panels in that view - and with them enabled, it also acts exactly as I think even the _file manager_ should work like with "zoom to one photo"). I was looking for it in menus, in the docs, etc. and also, I'm using DT for like last year or so without it. Ouch.

Thanks for your help @apostel338 , and apparently also @darkelectron (I didn't understand at first).

**Comment by GonziHere** [comment]
@ralfbrown https://github.com/darktable-org/darktable/issues/14694#issuecomment-1585995745 this won't help me, since this hides UI. However, I didn't know that I could simply enable it in that mode. It's not an obvious/expectable feature for me. Like at all. Could it, maybe, be added to the docs? Something like
_"While in this mode, you can still enable all panels (ctrl + shift + R,L,T,B), effectively making it a single image viewer. In this mode, all actions apply to the currently visible image."_ 
?

**Comment by ptilopteri** [comment]
since your request is available to you, consider closing this issue?
