### ISSUE TITLE
darktable won't start after accidental editing of base directory naming pattern

### ISSUE THREAD

**Issue by salmo6** [darktable-org/darktable#14699]
### Describe the bug

darktable was failing to launch, with the error `path lookup '/home/<user>/$(PICTURES_FOLDER/2023/06-11/<filename>' fails with: 'No such file or directory'.` 

Note the missing right parenthesis in the path lookup. In the previous darktable session, I had inadvertently deleted the right parenthesis from the base directory naming pattern in the copy and import dialog box. After doing so, darktable failed to copy images to the base directory, but more importantly, refused to start any subsequent sessions.

I was able to fix this by editing ~/.config/darktable/darktablerc and removing the `plugins/lighttable/collect/history` lines with the broken PICTURES_FOLDER entries. That allowed darktable to start, after which I could correct the value in darktable. But that's not a particularly user-friendly process.

### Steps to reproduce

1. Open copy & import.
2. In base directory naming pattern, change `$(PICTURES_FOLDER)/$(EXIF_YEAR)/$(EXIF_MONTH)-$(EXIF_DAY)` (my intended value) to `$(PICTURES_FOLDER/$(EXIF_YEAR)/$(EXIF_MONTH)-$(EXIF_DAY)`
3. Close darktable.
4. Try to open darktable again.

### Expected behavior

The error message should appear after darktable opens, instead of when darktable fails to open.

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by dterrahe** [comment]
Can you still reproduce in current master/upcoming 4.4? For me, it seems to just create a path containing the literal string "$(PICTURES_FOLDER" without complaining.

**Comment by salmo6** [comment]
Sorry for the delayed response. I just installed the darktable-4.4 RPM from the Fedora 37 graphics_darktable repository at https://download.opensuse.org/repositories/graphics:/darktable/Fedora_37/. I still encounter the same problem. I deleted the closing parenthesis in the base directory naming pattern `$(PICTURES_FOLDER/$(EXIF_YEAR)/$(EXIF_MONTH)-$(EXIF_DAY)` , after which darktable failed to launch. This time, though, I was not able to find a corresponding line to delete in the darktablerc file. I had to remove the entire library.db file in order to get darktable to start again.

**Comment by ptilopteri** [comment]
woud that not make you suspect that you had a corrupted database?

**Comment by ptilopteri** [comment]
you do know you can start dt w/o any database
darktabe --library :memory:

**Comment by salmo6** [comment]
> woud that not make you suspect that you had a corrupted database?

Not really. I use darktable daily, and the database has been fine, including 2 minutes before I made the change of intentionally mangling the base directory naming pattern. That's the only change I made.

**Comment by salmo6** [comment]
> you do know you can start dt w/o any database
> darktabe --library :memory:

I did not know that. Thank you.
