### ISSUE TITLE
Dark edges around some highlights when exporting in lower resolution

### ISSUE THREAD

**Issue by axiomgraph** [darktable-org/darktable#14690]
### Describe the bug

well the image look fine when you export it in original resolution or half resolution. but when you export it in lower resolutions there will be dark edges around highlights.
here are the images that exported in multiple resolutions. 
mostly these dark edges form around chromatic aberrations.

half size looks almost fine
![tag @signatureeditsco - free raws from signatureedits com IMG_5701](https://github.com/darktable-org/darktable/assets/68183694/65d4a409-57cc-42b3-91fa-3eec6d2d3bbc)
lower resolution dark edges can be seen (closely look at those hanging lights)
![raw](https://github.com/darktable-org/darktable/assets/68183694/50cd0257-f73e-497e-b244-28db54533a2d)

here is another same image but converted to jpg format before importing to darktable

lower resolution no dark edges around highlights

![nonraw](https://github.com/darktable-org/darktable/assets/68183694/7e3434bc-f129-46f3-9da4-466261a8ff0e)

here is a video

[Screencast from 2023-06-10 19-11-58.webm](https://github.com/darktable-org/darktable/assets/68183694/cda0ed86-447a-4efa-9f79-3bc6c70121b7)

as you can see the dark edges only happens with raw images. also you can see those dark edges in view port.

here is the xmp file
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:darktable="http://darktable.sf.net/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
   exif:DateTimeOriginal="2022:12:01 23:59:18.350"
   xmp:Rating="0"
   xmpMM:DerivedFrom="tag @signatureeditsco - free raws from signatureedits.com IMG_5701.CR2"
   darktable:import_timestamp="63822000517991935"
   darktable:change_timestamp="63822002341819089"
   darktable:export_timestamp="63822002275361737"
   darktable:print_timestamp="-1"
   darktable:xmp_version="5"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="15"
   darktable:iop_order_version="2"
   darktable:history_auto_hash="811cbd2cb5384b678c42d6c0c920c123"
   darktable:history_current_hash="d0095a8e28631811b1b0d27168f0309e">
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="4a000000280000000000000002000000ff07ff07010801082c33000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="1"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="0000000000000000000000000500000001000000cdcc4c3e"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="2"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="7"
      darktable:params="gz48eJzjZhgFowABWAbaAaNgwAEAOQAAEA=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="3"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="gz35eJxjZBgFo4CBAQAEEAAC"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="4"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="5"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0000e63f0000803f00c0eb3f0000c07f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="6"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="050000000000803f00000000000000000000803f000000000100000005000000cdcccc3e000000400000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz13eJxjYGBgYARiCQYYOOHEgAZY0QVwggZ7CB6pfNoAAFDAGQk="/>
     <rdf:li
      darktable:num="7"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz02eJybNXOy49kzXw60vp7owAAGDkD6hBMEQ8AsoBr9ZRU2IDG1yHQHruvKQHaDPUz+7BkfO2YgDcKMUDFGJDYMMEFpALwGFBc="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz10eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi08IAAB/xiOk"/>
     <rdf:li
      darktable:num="8"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="9"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="00000000000080b93333333f00004842000080c001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz10eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi08IAAB/xiOk"/>
     <rdf:li
      darktable:num="10"
      darktable:operation="defringe"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="000080400000a04100000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz13eJxjYGBgYAJiCQYYOOHEgAZY0QVwggZ7CB6pfNoAAFJgGQo="/>
     <rdf:li
      darktable:num="11"
      darktable:operation="cacorrectrgb"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="010000000000a0400000003f0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz10eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi08IAAB/xiOk"/>
     <rdf:li
      darktable:num="12"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="010000000000803f00000000000000000000803f000000000100000005000000cdcccc3e000000400000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz13eJxjYGBgYARiCQYYOOHEgAZY0QVwggZ7CB6pfNoAAFDAGQk="/>
     <rdf:li
      darktable:num="13"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="7"
      darktable:params="gz48eJxjZBgFowABWAbaAaNgwAEAEDgABg=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAZY0QVwggZ7CB6pfNoAAE8gGQg="/>
     <rdf:li
      darktable:num="14"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="00000000000000009e1a6f4000004842000080c001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="11"
      darktable:blendop_params="gz10eJxjYGBgYAFiCQYYOOHEgAZY0QVwggZ7CB6pfOygYtaVAyCMi08IAAB/xiOk"/>
    </rdf:Seq>
   </darktable:history>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>man_jose</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">ManJose</rdf:li>
    </rdf:Alt>
   </dc:rights>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>

My System
Arch Linux
Gnome 44.1
Wayland
Kernal Linux 6.3.5-arch1-1

### Steps to reproduce

1. Import this raw image https://drive.google.com/file/d/1S3GApiUxEZWzEmetfLq9ahi7MOJ8eEjR/view?usp=sharing
 into darktable
2. open the raw image in darkroom

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by jenshannoschwalm** [comment]
Not sure what exactly is your issue.
1. While darkroom zooming-in you will see a reduced-quality image (While there is the "working" message visible) That is desired this way for performance
2. For exporting we have improved the scaling algorithm leading to less artefacts. Also - what are your export settings? Did you check them?

I tested here on dt-master and could not observe anything bad.

**Comment by apostel338** [comment]
There are some parts in the jpegs that look like `high quality resampling` is not actvated. Indeed without it I get the black borders, activating it fixes them.

![grafik](https://github.com/darktable-org/darktable/assets/96216629/b0aaf0ab-91ff-490a-96cb-125232dc7e67)

**Comment by axiomgraph** [comment]
> Not sure what exactly is your issue.
> 
>     1. While darkroom zooming-in you will see a reduced-quality image (While there is the "working" message visible) That is desired this way for performance
> 
>     2. For exporting we have improved the scaling algorithm leading to less artefacts. Also - what are your export settings? Did you check them?
> 
> 
> I tested here on dt-master and could not observe anything bad.

try exporting the raw image in lower resolution.
set size by scale 0.1 which will export the raw image in 367 × 550 pixels

![raw_01marking](https://github.com/darktable-org/darktable/assets/68183694/1092ec47-1961-4a29-b85f-48369c839a04)

please take a look lights inside red circles. those dark edges are not suppose to be there.

thanks while typing I saw the last comment. and high quality resampling solved this issue.

**Comment by jenshannoschwalm** [comment]
Ok, you mean the "black ring"?

**Comment by jenshannoschwalm** [comment]
That's a scaling issue. Please note there is also the "pixel interpolator" in **preferences->processing**. Certainly the Lancosz variants are prone to such artefacts if the scale factor is > 2.0 or < 0.5

**Comment by axiomgraph** [comment]
> That's a scaling issue. Please note there is also the "pixel interpolator" in **preferences->processing**. Certainly the Lancosz variants are prone to such artefacts if the scale factor is > 2.0 or < 0.5

okey I change it. pixel interpolator scaling from lancosz to bilinear and it works. should I close this issue. I mean if this is happening with everyone then darktable should use bilinear option by default.
![Screenshot from 2023-06-10 22-23-57](https://github.com/darktable-org/darktable/assets/68183694/82946992-0d0d-47bc-83d3-221e9f83c756)

**Comment by jenshannoschwalm** [comment]
Don't know. Personally - yes for sure. But many prefer the strong edges ...

**Comment by axiomgraph** [comment]
thanks for the help!
