### ISSUE TITLE
Images are in Black and white, but histogram show colors

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#14703]
### Describe the bug

In the darkroom the images are in black and white, but the histogram show colors.

### Steps to reproduce

1. Go to darkroom
2. Apply some color to black and white in the color calibration module, gray tab. (I used B&W luminance based green channel).
3. look at the histogram and see the issue (histogram show colors)

### Expected behavior

The histogram should show the graph in black and white, as the image is processed.

### Logfile | Screenshot | Screencast

![Screenshot from 2023-06-11 17-55-08](https://github.com/darktable-org/darktable/assets/67672868/1ed9faea-3f03-4447-8b39-2c5b12aed9a5)

### Commit

not sure

### Where did you install darktable from?

From Suse repositories
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

### darktable version

4.3.0~git2518.ccb33108-10192.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Describe your system?

OS: Fedora release 37 (Thirty Seven) x86_64
Host: Z390 AORUS MASTER
Kernel: 6.2.7-200.fc37.x86_64
Uptime: 2 hours, 17 mins
Packages: 2175 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
DE: GNOME 43.4
WM: Mutter
WM Theme: WhiteSur-Dark
Theme: WhiteSur-Dark-solid [GTK2/3]
Icons: Mkos-Big-Sur [GTK2/3]
Terminal: alacritty
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Memory: 5861MiB / 32012MiB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

530.41.03

**Comment by jenshannoschwalm** [comment]
Can't reproduce here. Could you provide a sidecar plus raw?

**Comment by difrkaguilar** [comment]
Can´t upload here the RAF file (50mb) But the same happen with the .jpg so I uploaded the .jpg + .xmp

[_DSF2471.zip](https://github.com/darktable-org/darktable/files/11769108/_DSF2471.zip)
[_DSF2471.JPG.zip](https://github.com/darktable-org/darktable/files/11769116/_DSF2471.JPG.zip)

**Comment by jenshannoschwalm** [comment]
mmh. Can't reproduce with above files, tested the various scaling methods, opencl on/of.

Stuck with analysing atm, any more hints?

**Comment by difrkaguilar** [comment]
I'm going to test it once again to check the opencl among other things. TIA

**Comment by difrkaguilar** [comment]
Was an issue on my side. I deleted the darktablerc and dreated again. Sorry.
