### ISSUE TITLE
[RFC] Is there really a need to export to j2k?

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#14700]
Generally, it makes little sense to export processed images to a bare code stream instead of a containerized version of the image format. However, we do have an implementation of exporting to the codestream variant of the JPEG 2000 format, "j2k". I suspect this was done without any specific use case in mind, just "because we can".

So I have a proposal for discussion: remove the option to export to j2k, always writing only to standard jp2.

This issue has some connection with #14647, in the sense that the fix will be for one of them, the other will then simply be closed.

**Comment by MStraeten** [comment]
Why remove that? Does it really matter? Add complexity that affects maintainability? darktable is about having options - several of them are seen as ‚because we can‘ for somebody ;)

**Comment by victoryforce** [comment]
> Why remove that? Does it really matter? 

I'm sure it does.

> Add complexity that affects maintainability?

No, just the opposite, __remove complexity__! Even more, unnecessary complexity.

> darktable is about having options - several of them are seen as ‚because we can‘ for somebody ;)

I suspect that this is an option that no one needs. I just don't see a use for it. If you use the bare codestream (j2k) version instead of normal jp2 files for some purpose, please tell me why it might be needed. This is what the RFC was created for.

**Comment by Christian-Bouhon** [comment]
FYI.
As a user, I never use the j2k format. 
Greetings from Brussels,
Christian

**Comment by kmilos** [comment]
FYI, [libvips removed this recently](https://www.libvips.org/2022/12/22/What's-new-in-8.14.html) as well. Makes sense I guess...

**Comment by ralfbrown** [comment]
Resolved by #15045.
