### ISSUE TITLE
User manuals appear to be broken/missing

### ISSUE THREAD

**Issue by alexliew** [darktable-org/darktable#14704]
The html version of the darktable 4.2 user manual appears to be empty. There are only links to the other translations which appear to be equally empty. The PDFs have 4 mostly empty pages.
The user manuals up to darktable 3.6 appear to be broken

![image](https://github.com/darktable-org/darktable/assets/1654951/981b7e6f-0440-4636-82b3-1a658a654c4b)

**Comment by wpferguson** [comment]
It's broken right now but is being worked on...

**Comment by elstoc** [comment]
This is already covered by an issue on the dtdocs repository (https://github.com/darktable-org/dtdocs/issues/575)
