### ISSUE TITLE
Module order "for jpeg/non-raw input" not automatically used when opening jpeg images

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#14716]
### Describe the bug

Opening a jpeg image in the darktable, you expect that the module order is set to "v3.0 for JPEG/non-RAW input".

Actually "v3.0 for RAW input" is used.

### Steps to reproduce

import a jpeg image
open it in the darktable
got to module order and see what order is used

### Expected behavior

darktable should use the non-RAW module order

### Where did you install darktable from?

self compiled

### darktable version

4.2.0+113~ge8ad7f4df8

### What OS are you using?

Linux

### What is the version of your OS?

xubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
> 4.2.0+113~ge8ad7f4df8

I think this should be fixed on master: https://github.com/darktable-org/darktable/issues/14023

Please search before opening new issues.

**Comment by KarlMagnusLarsson** [comment]
yes, this works for me at tip of github master 4.5.0+2~g41cb1baa1d. This will be part of 4.4.0 release as pointed out by @kmilos.
