### ISSUE TITLE
[Windows] libdarktable.dll.a is not required to run darktable and should not be installed

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#14717]
The `.dll.a` files are called "import library". On the [Wikipedia page](https://en.wikipedia.org/wiki/Dynamic-link_library) it is clearly written about the import libraries that they are "used to link against a DLL at compile-time; it is not necessary for run-time linking". Therefore, there is no need to include them in the package and install them.

Tested by renaming/deleting libdarktable.dll.a file and successfully starting and running darkatble.

Excluding this file from the installation package will save approximately 4.5 MB of installation disk space.

**Comment by kmilos** [comment]
Not needed for runtime indeed, but I'm not sure how the drmingw JIT debugger works when it generates the crash report, could it perhaps need it?

**Comment by victoryforce** [comment]
I'm not sure either, though I doubt that the import libraries are the source of the debugging information. Fortunately, it's easy to check. After receiving a crash report, you should remove `libdarktable.dll.a` and re-crash the program. For ease of testing, you can add code to some execution path that is guaranteed to cause a crash...

**Comment by kmilos** [comment]
Another idea: we enable someone else building something using `libdarktable`? (In which case, we should probably be shipping the .dll.a in `lib/` though...)

For crash reporting, it's more likely using stuff in `.debug/libdarktable.dll.dbg`?

**Comment by victoryforce** [comment]
> Another idea: we enable someone else building something using `libdarktable`? (In which case, we should probably be shipping the .dll.a in `lib/` though...)
> 
> But then again, we don't provide an API nor a header file for it, right? So this is not the intention?

Exactly! It was just a file that was installed along with others unnecessarily and without intention and it went unnoticed.

> For crash reporting, it's more likely using stuff in `.debug/libdarktable.dll.dbg`?

I think so, .dll.a files are just regular static archives.
