### ISSUE TITLE
A bit more freedom when moving around the image canvas

### ISSUE THREAD

**Issue by asdkant** [darktable-org/darktable#14721]
# Is your feature request related to a problem? Please describe.
When I'm working on masks with control points near or outside the edges of the image, I'm bothered by not being able to move my view slightly outside of the shorter edge of the image because DT limits how far I can move.

# Describe the solution you'd like
I'd like the limits to be placed a bit outside the image. Say, 10% of the image length or width, I just need enough to work with mask control points.

**Comment by dterrahe** [comment]
I hear you. Having looked into this before, there are quite a few places where the fundamental assumption is made that there is no extra one-sided space around the image, so this would require very careful changes all over the places and most likely would introduce bugs. If somebody were to take this on, there would probably be significant opportunities for refactoring/simplification.

Having said that, there are two ugly "workarounds" that might be of a little help to you (if you are not already aware of them). Using ctrl+scroll you can scroll out further than "fit", so you'd have space all around the image (but not the accuracy to finely position control points). If you toggle on "color assessment" you'll get the white and grey borders that allow you to manipulate control points over the image edge.

You could also increase the "border around image in darkroom mode", but you'd always lose that space (even in full preview).

**Comment by asdkant** [comment]
> I hear you. Having looked into this before, there are quite a few places where the fundamental assumption is made that there is no extra one-sided space around the image, so this would require very careful changes all over the places and most likely would introduce bugs. If somebody were to take this on, there would probably be significant opportunities for refactoring/simplification.

I hope somebody does. I unfortunately have very little experience with C (I'm an infrastructure guy and mostly do Python/bash/powershell, plus a little bit of Rust as a hobby), and this sounds like it'd be all over the codebase. That said, do you have any suggestion on where to start the journey to someday be able to read something like the DT codebase and understand it / be able to work on it?

> Having said that, there are two ugly "workarounds" that might be of a little help to you (if you are not already aware of them). Using ctrl+scroll you can scroll out further than "fit", so you'd have space all around the image (but not the accuracy to finely position control points). If you toggle on "color assessment" you'll get the white and grey borders that allow you to manipulate control points over the image edge.

Already using the Ctrl+scroll thing and it helps a bit but it still has the drawbacks you pointed out 🙁

> You could also increase the "border around image in darkroom mode", but you'd always lose that space (even in full preview).

This could be a viable workaround for my particular use case, but I see where it could be limited... maybe a quick toggle for that border size could be useful for my situation.

For context, what I'm doing is coloring lightsabers on star wars cosplay photos. I ended up using the intersection of two gradients (plus other masks as needed) instead of my original take of doing a one or more path masks to cover the blade, which triggered the issue of not being able to go outside of the image borders, but I still think fixing the issue has value for other use cases.

**Comment by dterrahe** [comment]
Another workaround, that is easily switched off even by shortcut, is temporarily adding a border using the "framing" module. I wouldn't be surprised if extensive use of this module for this unintended purpose would uncover issues with distortion calculation when interacting with other modules (crop etc) in the pipe, but a quick test indicates it works for simple cases. Please report any bugs you may find.

> That said, do you have any suggestion on where to start the journey to someday be able to read something like the DT codebase and understand it / be able to work on it?

I think most people start with trying to figure out a fix for a bug they run into. Anything that affects many places at once would require understanding the unintended consequences (or intended "side effects"). Although sometimes extensive refactoring/simplification can be achieved without changing any functionality and then could make later changes easier to implement. So if you wanted to dive in the deep end, you could look at all uses of `dt_control_get_dev_zoom/_x/_y/_scale/_closeup` and find commonalities and exceptions that need to be supported.

But really now that we are blessed by a good manual, getting to _really_ know dt and all the features it already _has_ (and that somebody would be upset about if it got broken by some extensive changes) would be a very good place to start. By trying out everything you'll likely find bugs and reporting those will help improve dt as much as anything.

Unfortunately I can't offer shortcuts to getting to know the code base. It is not extensively documented so we all got comfortable with it the hard way (by going against unknown assumptions and breaking stuff, mostly). Use a good debugger to trace call chains. Multi-year project.
