### ISSUE TITLE
Alternative controls for gradient masks

### ISSUE THREAD

**Issue by asdkant** [darktable-org/darktable#14728]
# Is your feature request related to a problem? Please describe.
I've recently had to work on some star wars cosplay photos I took, and I ended up coloring the lightsabers with colorize masked with two intersected gradients (this two times, one for the colored glow at the sides of the blade and one for the whiter center).

The edit was doable, but... placing the gradients was a bit of a pain. Especially if I have a very long blade that spans a large part of the image so that I can't zoom in on both ends.

I can see how this same issue can happen with horizons, or other straight lines in pictures that sometimes can't be easily masked with parametric masks (my go-to way of masking modules for stuff that'd be a pain to draw)

# Describe the solution you'd like
An alternative way to control gradients, based on having two control points plus a "reverse" action instead of one and a directional arrow.

# Alternatives
Being able to modify the angle of the gradient masks with a slider widget, like you have in the graduated density module, would help a bit. Moving things with the cursor can be unwieldy if you're trying to do fine work, so having sliders or some other way to fine-tune things is a big help. But it still doesn't solve the "two ends of the line can't be zoomed in at the same time" issue.

**Comment by dterrahe** [comment]
> Being able to modify the angle of the gradient masks with a slider widget, like you have in the graduated density module, would help a bit.

There is a slider for the rotation in the "properties" collapsible section of the mask manager. Also #14157
