### ISSUE TITLE
'f' is no longer showing a large version of the selected image in Lighttable

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#14725]
### Describe the bug

This is relative to the previous version which showed an enlarged version of the selected image, when 'f' was pressed. 
'x' is still presenting two selected images for comparing.

(A second "bug" is that ? doesn't open the manual - as if the url is wrong.)

### Steps to reproduce

1. When Lighttable is showing one or more thumbnails - press 'f' (which should open the image in full size) - but nothing happens.

### Expected behavior

An enlarged version should show.

### Commit

I just installed the night build for Windows 64

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+2~g41cb1baa1d

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro, Processor	AMD Ryzen 7 5800X 8-Core Processor, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)

### Describe your system?

Desktop

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1650

**Comment by elstoc** [comment]
> This is relative to the previous version which showed an enlarged version of the selected image, when 'f' was pressed.

Works fine for me in the latest development version. Is this in Lighttable view? Have you checked preferences to ensure you haven't accidentally overridden the shortcut?

> (A second "bug" is that ? doesn't open the manual - as if the url is wrong.)

For future reference it's easier for us to manage issues if they're raised separately for each problem. However, this is already a known issue and it is under investigation.

**Comment by KIRSJ** [comment]
I haven't touched the shortcuts until now.
'f' says ... normal ... toggle
- and now I found the difference from earlier:
In my previous version an activated thumbnail would open with 'f' - now the
cursor has to point at it too to open.

Den søn. 18. jun. 2023 kl. 15.46 skrev Chris Elston <
***@***.***>:

**Comment by elstoc** [comment]
Ah yes I reproduce that now -- only works on mouse-over

**Comment by pehar1** [comment]
> the cursor has to point at it too to open.

If i'm not mistaken this is the oct-on feature, so expected behavior.

**Comment by KIRSJ** [comment]
This is not how it functioned earlier, and it isn't consistent with the 'x'
feature where you can open two active thumbnails without pointing at
anything.

Den man. 19. jun. 2023 kl. 09.00 skrev pehar1 ***@***.***>:

**Comment by elstoc** [comment]
> If i'm not mistaken this is the act-on feature, so expected behavior

The expected behaviour should be that it works on mouse over _or_ click-selection (i.e. mouse-over is treated as a selection). It shouldn't _only_ work on mouse-over (afaik)

**Comment by MStraeten** [comment]
expected behaviour:
1. it should behave like clicking the full preview icon (full prveiew of selected image or top left visible image in case of no selection)
2. it should handle mousever as selection as an additional function which is prioritized

**Comment by KIRSJ** [comment]
Using the preview icon fulfills the conditions in 1.
'f' always needs mouse over here on my Win version - but it didn't in the
previous version - an active thumbnail way sufficient.
So maybe the previous version was off?
Again - it feels more consistent with the 'x' key function if an active
thumbnail was sufficient - and mouse-over not needed.

Den man. 19. jun. 2023 kl. 13.24 skrev Martin Straeten <
***@***.***>:
