### ISSUE TITLE
Darktable crashes indeterministicly

### ISSUE THREAD

**Issue by gubihu** [darktable-org/darktable#14733]
### Describe the bug

During usage time to time Dakrtable crashes using functions that seems to work other times.
There seems to be no specific function, the crash occures totally random. 
Last time I tried to crop an image, and I had to restart Darktable several times to complete the task. I did everything the same way every time, and it crashed at various places.
The relevant part of the 

### Steps to reproduce

No specific way to reproduce, the crash can occur during virtually any task, but so frequnetly that Darktable is practically unusable

### Expected behavior

darktable should not crash that frequnently

### Logfile | Screenshot | Screencast

Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
Magick: caught exception 0xC0000005 "Access violation"...[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows11

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1660 Ti

**Comment by pehar1** [comment]
How many memory is available for darktable? Please check in task manager if the application is running out of memory.
OpenCL enabled or disabled? Please check your setting of preferences -> processing -> activate OpenCL support
https://darktable-org.github.io/dtdocs/en/preferences-settings/processing/

**Comment by gi-man** [comment]
4.4 should release this week. I think you should test it with 4.4.

**Comment by gubihu** [comment]
"activate OpenCL support" is checked. 

C:\Program Files\darktable\bin>darktable-cltest.exe
[dt_get_sysresource_level] switched to 1 as `default'
  total mem:       16291MB
  mipmap cache:    2036MB
  available mem:   8145MB
  singlebuff:      127MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'NVIDIA GeForce GTX 1660 Ti'
   CANONICAL NAME:           nvidiageforcegtx1660ti
   PLATFORM NAME & VENDOR:   NVIDIA CUDA, NVIDIA Corporation
   DRIVER VERSION:           517.00
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          6144 MB
   MAX MEM ALLOC:            1536 MB
   MAX IMAGE SIZE:           32768 x 32768
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              6.749
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         C:\Program Files\darktable\share\darktable\kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   KERNEL LOADING TIME:       0.0286 sec
[opencl_init] OpenCL successfully initialized.
[opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
[opencl_init]           0       'NVIDIA GeForce GTX 1660 Ti'
[opencl_init] FINALLY: opencl is AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is ON.
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       -1      0       0       -1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[opencl_synchronization_timeout] synchronization timeout set to 200
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       -1      0       0       -1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[opencl_synchronization_timeout] synchronization timeout set to 200

press any key to exit

**Comment by victoryforce** [comment]
@gubihu So, it seems that this issue has lost the attention of the developers... Please install the latest version of darktable, 4.4.2. If that doesn't fix your problem, disable OpenCL. If you don't see any crashes after that (which is quite likely), try updating the OpenCL driver for your Nvidia.

**Comment by gubihu** [comment]
I've upgraded to 4.4 right when it came out. Since that I have not experienced the problem. Definitely more testing is required, but it seems the situation got better. I haven't done anything to my Nvidia driver.

**Comment by victoryforce** [comment]
That is, it looks like the problem was fixed in the program itself. Great! Then I close this issue, as it is no longer relevant. If any problems arise, you can raise a new issue.
