### ISSUE TITLE
Please support Big-endian platforms

### ISSUE THREAD

**Issue by barracuda156** [darktable-org/darktable#14739]
It is also desirable to have 32-bit archs supported, but even having only 64-bit Big-endian will be good enough.

UPD. To be clear, support here implies support for _current_ platforms (*BSD, Linux).

**Comment by dterrahe** [comment]
It would be helpful to list the platforms you have in mind, because to "support" them it is not just necessary to find and fix code that doesn't correctly works on them, but also to _test_ it. Presumably we don't currently have any developers that have a personal interest in this, so new ones would have to commit to this effort.

**Comment by barracuda156** [comment]
@dterrahe Thank you for responding!

Literally any convenient platform can be used to test Big-endian specifics – among currently supported are FreeBSD and a number of versions of Linux.
32-bit archs are supported likewise; I believe, 32-bit (i386) Ubuntu can be set in GitHub CI.

Personally (and for Macports) I have macOS PowerPC in mind, but I do not expect anyone to test that for me or fix anything macOS-specific. That I can handle on my end.

**Comment by parafin** [comment]
32-bit was disabled some time ago due to virtual memory space fragmentation concerns (and general memory size limitation). I don't see why dt should go backwards here.

Big-endian is about porting processing code and could be a substantial task. Does rawspeed support big-endian platforms BTW? Anyway, it would require a new dt developer with such platform, interest to support it, and a lot of time on his/her hands.

**Comment by ralfbrown** [comment]
32-bit was dropped because running in 3GB of RAM or less (the absolute maximum available) is very limiting - you wouldn't be able to process images of more than about 16 megapixels unless you restricted which modules you used.

**Comment by barracuda156** [comment]
> 32-bit was dropped because running in 3GB of RAM or less (the absolute maximum available) is very limiting - you wouldn't be able to process images of more than about 16 megapixels unless you restricted which modules you used.

I think 4GB can be addressed (I may be wrong though), and that exclusive to the app, since OS can use other available RAM. Perhaps better a slowly working app than a broken one? :) 

Do you know if any breaking changes were made since then, or it is largely a matter of downgrading `#error` to `#warning` in configure checks of CMake?

**Comment by parafin** [comment]
> I think 4GB can be addressed (I may be wrong though), and that exclusive to the app, since OS can use other available RAM.

There is an option to have 4GB available to the app, but it's not a standard one (custom-built kernel is required).

> Perhaps better a slowly working app than a broken one? :)

Better for whom?

**Comment by parafin** [comment]
> Well, my point was – if the app is not incompatible with 32-bit, it makes a better sense to emit a warning, not err out. This does not seem to add any extra burden to developers.

It does, by generating additional bug reports from users on such platforms.

**Comment by barracuda156** [comment]
> > Well, my point was – if the app is not incompatible with 32-bit, it makes a better sense to emit a warning, not err out. This does not seem to add any extra burden to developers.
> 
> It does, by generating additional bug reports from users on such platforms.

@parafin Therefore, emit a warning that no active support for 32-bit is provided.

**Comment by LebedevRI** [comment]
> Big-endian is about porting processing code and could be a substantial task. Does rawspeed support big-endian platforms BTW?

If it does not, i would **REALLY** love to know about that.
I've been meaning to check that (via quemu), but didn't get to.
If someone has access to ppc64**be**, help welcomed.

On dt's side, you mainly need to rewrite all of sidecar handling -- who could've thought
that storing C structs as binary blobs is a bad idea?! Oh wait, everyone did,
but common sense was never so common in this project.

**Comment by barracuda156** [comment]
> _If_ it does not, i would **REALLY** love to know about that. I've been meaning to check that (via quemu), but didn't get to. If someone has access to ppc64**be**, help welcomed.

@LebedevRI I do.
Have to mention that it’s 10.5.8 in that case though – Apple removed ppc64 slices already in early developer builds of 10.6 :(

**Comment by LebedevRI** [comment]
Well, given that we don't support deploying to OSX older than 11.3, there's no hope for that.
Is this whole issue about apple specifically?

**Comment by barracuda156** [comment]
> Big-endian is about porting processing code and could be a substantial task. Does rawspeed support big-endian platforms BTW? Anyway, it would require a new dt developer with such platform, interest to support it, and a lot of time on his/her hands.

@parafin Sorry, missed this part of your reply.

So, it may or may not be a substantial task. Often endianness is a matter of sane defines in a single header, which are then used where needed. Not many – perhaps very few – software really require non-trivial changes to the code to accommodate bi-endianness.

**Comment by barracuda156** [comment]
> Well, given that we don't support deploying to OSX older than 11.3, there's no hope for that.

Well, I responded to your question re access. I am not asking for **any** kind of Mac-specific support.

> Is this whole issue about apple specifically?

No, it is not. PowerPC Big-endian exists with FreeBSD, Debian etc.

**Comment by kmilos** [comment]
FWIW, there also a few places all over imageio code that assume LE, related to e.g. TIFF/DNG, PNM/PFM...

**Comment by barracuda156** [comment]
I have got 4.4.1 to build on `ppc`, but it does not run correctly: X window starts, but without displaying anything, and then crashes. If I run via GDB, I get this:
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x0000022c
[Switching to process 9962 thread 0x4703]
0x072bff18 in Auto::Zone::register_thread ()
(gdb) bt
#0  0x072bff18 in Auto::Zone::register_thread ()
#1  0x001fdcd0 in darwin_event_thread_main ()
#2  0x0592c064 in _pthread_start ()
```

**Comment by LebedevRI** [comment]
As it has been mentioned ad nauseam in this thread,
unless the codebase is actually adjusted to support big-endian,
it is only natural that it does not work on non-little-endian.

**Comment by barracuda156** [comment]
@LebedevRI Yes, I know. This is just to report that the app itself is buildable. So fixing endianness is not pointless.

**Comment by barracuda156** [comment]
@LebedevRI This issue is actually unrelated to endianness. Same on x86:

![image](https://github.com/darktable-org/darktable/assets/92015510/21215ff5-a58a-4fd7-a6b9-a7fe169ac6bd)

**Comment by LebedevRI** [comment]
> @LebedevRI This issue is actually unrelated to endianness. Same on x86:

That's a rather unfortunate argument i'm afraid.

It is my understanding that only macOS 13 and newer is supported,
so if you have anything older than that, it's a warranty-void situation,
and you need to ask the person who provided you with that darktable package.

**Comment by victoryforce** [comment]
OK, no one is going to benefit from a multi-year issue that gets stale every now and then, and then gets de-stale a few months later by some comments... 

Deciding whether we _can_ support a platform shouldn't take years. Everything is simple here: if we talk about support, then support always implies the capability of testing/checking the correctness of the program's operation, as well as the capability of fixing bugs on supported platforms. Currently, only you, @barracuda156, can do it, other contributors to the project do not have the capability to support Big-endian platforms (starting with a lack of hardware, let alone a lack of personal interest). So it's really about whether _you_ want to be the team member who will ensure correct operation on Big-endian and will be able to fix bugs on these platforms.

If you are not ready to take it on, we can't really talk about real support, and talking about some implementation details here will not lead to the desired result.

**Comment by victoryforce** [comment]
Since I see no interest in contributing from big-endian people, I'm closing this issue.

**Comment by barracuda156** [comment]
Just for the record if someone bumps into this issue, while searching for the error message: similarly looking crash popped up with a completely different port now:
```
Process:         Python [4155]
Path:            /opt/local/Library/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python
Identifier:      Python
Version:         ??? (???)
Code Type:       PPC (Native)
Parent Process:  zsh [32782]

Date/Time:       2024-11-27 09:16:14.121 +0800
OS Version:      Mac OS X 10.6 (10A190)
Report Version:  6

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x000000000000022c
Crashed Thread:  8

Thread 8 Crashed:
0   libauto.dylib                 	0x00064f18 Auto::Zone::register_thread() + 28
1   libusb-1.0.dylib              	0x0ff74ccc darwin_event_thread_main + 48
2   libusb-1.0.dylib              	0x0ff74ccc darwin_event_thread_main + 48
3   libSystem.B.dylib             	0x00895060 _pthread_start + 320
```
