### ISSUE TITLE
Failing to process Nikon Z 7 II raw files

### ISSUE THREAD

**Issue by photopierre** [darktable-org/darktable#14748]
Good day
While Darktable (version 3.4.0) works fine to convert Raw data from my Nikon D700 (NEF 4256x2832 12 MegaPixels about 12 - 14 Mo) I have the following issue with Raw data from my Nikon Z 7 II (NEF8256x5504 45 MegaPixels about 50 - 55 Mo 

- when opening the Raw, I see a warning telling the file format is unknown (pic1). However, the thumbnail is displayed properly)
- Trying to edit the picture, I see a message telling darktable could not open the file. (pic2)
- Trying to export the file, get a message " impossible to export .... !" (pic3)

I m sure that the NEF files are not corrupted as they can be edited ansd exported with softwares like Irfanview or Photomatix pro.

I guess my hardware should match the requirements (pic4)

![pic1](https://github.com/darktable-org/darktable/assets/137417828/31abd4c1-0632-4fff-a102-f7e6620b417b)
![pic2](https://github.com/darktable-org/darktable/assets/137417828/5b0ae1d5-8d49-4fba-9c74-41fa3fa0834c)
![pic3](https://github.com/darktable-org/darktable/assets/137417828/17fc851e-5fa1-4bd5-9af7-181b0e0f796d)
![pic4](https://github.com/darktable-org/darktable/assets/137417828/f1488ba0-d65d-4909-9952-c904861e3139)

**Comment by kmilos** [comment]
The Nikon Z 7 II is supported only from dt 3.6.0.

**Comment by kmilos** [comment]
Duplicate of #7282, #8348 and #9809.

Please search before opening new issues.

**Comment by photopierre** [comment]
> Duplicate of #7282, #8348 and #9809.
> 
> Please search before opening new issues.

Search, I did. Find, I did not... Sorry for that.

However, Big Thanks to you, I downloaded  4.4.0 and everything looks fine ! You made my day
