### ISSUE TITLE
Darktable 4.4.0 broken on MacOS

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/darktable#14746]
### Describe the bug

Darktable 4.4.0 broken on MacOS arm64
Test device: Macbook Pro 14 M1, 
Os: MacOS Ventura 13.4 (22F66)

### Steps to reproduce

1. Install Darktable
2. Launch Darktable
3. Observe the popup error popup appearing

### Expected behavior

Darktable should launch

### Logfile | Screenshot | Screencast

<img width="281" alt="Screenshot 2023-06-22 at 13 09 20" src="https://github.com/darktable-org/darktable/assets/10299892/8647efd1-54c1-44a9-8460-9231a1125091">

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Mac

### What is the version of your OS?

13.4 (22F66)

### Describe your system?

Test device: Macbook Pro 14 M1, 2021

### Are you using OpenCL GPU in darktable?

None

**Comment by KristijanZic** [comment]
You're right, I should have red that bit before opening the issue. There should be a link to that information right next to the download link.

Closing the issue.

**Comment by kmilos** [comment]
> There should be a link to that information right next to the download link.

There is. 😉

**Comment by KristijanZic** [comment]
Oh my god... I was looking right at it and I missed it. Maybe it's just me then but since I see I'm not the only one filing issues about the MacOS installation I think some quick UI fix should be implemented. That link at the bottom not being emphasised just made my brain unconsciously think that link will lead to the build instructions.

Look at this, I even did this as to show what to do before I actually noticed the link at the bottom:
<img width="818" alt="Screenshot 2023-06-22 at 15 18 01" src="https://github.com/darktable-org/darktable/assets/10299892/910b4a6b-8050-408a-80d4-94af14c021a7">


But now I'm thinking it could be more like this:
<img width="798" alt="Screenshot 2023-06-22 at 15 19 30" src="https://github.com/darktable-org/darktable/assets/10299892/6ac51696-a3da-4818-a24e-8273b389bc08">

**Comment by kmilos** [comment]
Feel free to propose changes at https://github.com/darktable-org/dtorg

**Comment by redblobgames** [comment]
Thank you! I had downloaded it from https://github.com/darktable-org/darktable/releases/tag/release-4.4.0 where it's not as obvious.

**Comment by rschumm** [comment]
I am sorry, but it’s not the usual problem «not downloaded from App Store» described here, it’s a broken signature as described in #14763

**Comment by abulka** [comment]
I'm getting

    “darktable” is damaged and can’t be opened. You should move it to the Bin.

even when I r.click to open. On my Macbook Air M2 running Ventura. 

Downloaded it twice, file size of the `darktable-4.4.0-arm64.dmg` seems OK.

**Comment by suschizu** [comment]
the signature is still missing in both versions of 4.4.0 - the issue isn't solved yet:

code-signature: 'darktable' EXPECTED 'XIMEA s.r.o. (85Q3K4KQRY)' but FOUND ''

**Comment by KristijanZic** [comment]
For anyone experiencing this issue here is the workaround that is not really visible if you're downloading the package from github:

What to do with dialog saying “darktable” can’t be opened because it was not downloaded from the Mac App Store:

* Locate darktable in Applications folder (or wherever you installed it) using Finder
* Do “Open” via context menu
* You will be presented with similar-looking dialog, but this time there will be second button allowing you to run the application
* After that you will be able to start darktable without this trick (well, until you update it, then you will have to do above steps again)

you can prevent this from happening by running `xattr -d com.apple.quarantine ~/Downloads/darktable*.dmg` command before mounting the image (or `xattr -dr com.apple.quarantine /Applications/darktable.app` after installing).

**Comment by jcampbell05** [comment]
Can you put those instructions in the DMG. Thats a common pattern for software that is more involved in it's installation especially when Mac users aren't used to having to read any instructions to install a DMG

**Comment by jcampbell05** [comment]
> * Do “Open” via context menu

This no longer works for Ventura

**Comment by apjanke** [comment]
FWIW, I'm working on this same issue for Octave.app, and the `xattr -d` or `-c` workaround is the best I've been able to come up with too so far.

https://github.com/octave-app/octave-app/issues/244
