### ISSUE TITLE
Module header name/label misalignment

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14743]
There appears to be some misalignment between the module name and label in the darkroom view. I guess it's probably caused by the fact that the name and label are now separate widgets with different font sizes, which are both vertically-centre-aligned within the header. While both appear to actually be central, I would expect the bases of the letters to align with one another.

This seems to be more or less obvious depending on the font size selected (because sometimes the two fonts are closer in size depending on pixel-level-rounding), so in the following screenshots I've slightly altered the relative font sizes using CSS to make it clearer:

![Screenshot_2023-06-21_19-27-26](https://github.com/darktable-org/darktable/assets/9555491/5ccdd3e7-8b50-4dd1-ab95-5c1d4a6effc9)

In this case I would expect the bottom of the number 1 to be aligned with (for example) the bottom of the letter "e" at the end of the module name, and it clearly isn't.

Apart from combining the two strings back into one and using some built-in styling (which IIRC is what we did before) I'm not sure how best to resolve this, but it's really distracting for me.

issue seen on darktable 4.5.0+16~gf6fefd3af1 and 4.4.0

Probably caused by https://github.com/darktable-org/darktable/pull/13659

**Comment by elstoc** [comment]
At the moment I've hack-fixed it with CSS: `#iop-module-name { margin-bottom: -3px }`

**Comment by TurboGit** [comment]
> Apart from combining the two strings back into one and using some built-in styling

I've changed this for good reasons as it was a mess to handle with all in one string. Don't remember all the details.

I suppose with some CSS we should be able to get back the alignment, but this is very dependant on the font. I don't see such big miss alignment on my side.

**Comment by TurboGit** [comment]
> At the moment I've hack-fixed it with CSS

Our messages have crossed... The fix you are proposing will work only for your current font.

**Comment by elstoc** [comment]
> The fix you are proposing will work only for your current font.

Indeed, that's why I called it a "hack fix" - it stops me being distracted while we consider a better fix. Unless we can combine the two labels into one, I'm not sure there's a better option atm.

**Comment by dterrahe** [comment]
`GTK_ALIGN_BASELINE`
And, since one label is in an event box and the other outside, this seems to require some messing with `gtk_widget_set_vexpand`.

**Comment by elstoc** [comment]
> `GTK_ALIGN_BASELINE`

My google-fu is clearly not up to the task. I did actually go looking for something like this.

**Comment by TurboGit** [comment]
> `GTK_ALIGN_BASELINE` And, since one label is in an event box and the other outside, this seems to require some messing with `gtk_widget_set_vexpand`.

@dterrahe : Will you have a look at this Gtk issue? Remember I gave you the status of our Gtk expert :)

**Comment by jenshannoschwalm** [comment]
Isn't this fixed @elstoc

**Comment by elstoc** [comment]
It is indeed
