### ISSUE TITLE
segfault when turning monitors on again

### ISSUE THREAD

**Issue by mkubecek** [darktable-org/darktable#14754]
### Describe the bug

When I leave darktable running while I turn my monitors (see context note below) off, it segfaults (deterministically) when I turn them on again. I tried to look into the backtraces but it's not clear where does the segfault happen. Log file attached below, tried to open the core dump in gdb but it looks the same.

### Steps to reproduce

1. (Running darktable on Plasma 5 desktop with two DP attached monitors.)
2. Lock the session and turn both monitors off without quitting darktable.
3. Turn the monitors on and unlock the Plasma session.
4. Check that darktable segfaulted.

### Expected behavior

should not segfault

### Logfile | Screenshot | Screencast

[darktable_bt_7Z7161.txt](https://github.com/darktable-org/darktable/files/11846086/darktable_bt_7Z7161.txt)

### Where did you install darktable from?

OBS

### darktable version

4.2.1, 4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Leap 15.5

### Describe your system?

AMD Ryzen 5900X, 64 GB RAM, Radeon WX2100, two 27" monitors (2560x1440) via DisplayPort, running openSUSE Leap 15.5 with mainline kernel (6.4-rc6 at the moment but it also happens with standard releases).

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

Radeon WX2100, in-tree amdgpu driver

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Not sure if it is related but the monitors are attached via DisplayPort which, as I learned, means that while turned off, they behave as if disconnected. This results in broken ICC profiles after turning them off and on again:
```
DisplayPort-1   the X atom and colord returned the same profile
        X atom: _ICC_PROFILE (968500 bytes)
                description: EV2760 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX
        colord: "/home/mike/.local/share/icc/EV2760 2023-03-12 80cdm² D6000 2.2 M-S XYZLUT+MTX.icc"
                description: EV2760 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX

DisplayPort-2   the X atom and colord returned different profiles
        X atom: _ICC_PROFILE_1 (967452 bytes)
                description: EV2736W 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX
        colord: "(none)"
                description: (file not found)
```
(It does not always look exactly the same but there is always either no profile for one of the monitors, sometimes even profile for one monitor set for the other one.)

Restarting colord restores the correct setup:
```
DisplayPort-1   the X atom and colord returned the same profile
        X atom: _ICC_PROFILE (968500 bytes)
                description: EV2760 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX
        colord: "/home/mike/.local/share/icc/EV2760 2023-03-12 80cdm² D6000 2.2 M-S XYZLUT+MTX.icc"
                description: EV2760 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX

DisplayPort-2   the X atom and colord returned the same profile
        X atom: _ICC_PROFILE_1 (967452 bytes)
                description: EV2736W 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX
        colord: "/home/mike/.local/share/icc/EV2736W 2023-03-12 80cdm² D6000 2.2 M-S XYZLUT+MTX.icc"
                description: EV2736W 2023-03-12 80cdm2 D6000 2.2 M-S XYZLUT+MTX
```

(Both profiles in use are generated using DisplayCAL.)

**Comment by gi-man** [comment]
Wayland or X12?

**Comment by mkubecek** [comment]
X11

**Comment by ralfbrown** [comment]
Near as I can figure from the backtrace, dt is receiving a "DeviceChanged" signal on Dbus, whose handler is calling into libcolord, which in turn calls into libcolord-gtk, which then crashes.
All of this is happening inside the call to gtk_main, with no darktable code involved except for that call.

**Comment by mkubecek** [comment]
You are right, I overlooked frame 4 in the stacktrace when I was trying to understand where did the segfault happen. (And I also got confused by "signal" meaning something different in frames from 5 on.) With more debuginfo installed, the stack trace looks like this:

```
#0  0x00007f23f5cec62f in __GI___wait4 (pid=18312, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f23f5cec597 in __GI___waitpid (pid=18312, stat_loc=0x0, options=0) at waitpid.c:38
#2  0x00007f23f5f8d4c8 in _dt_sigsegv_handler (param=11) at /usr/src/debug/darktable-4.4.0-lp155.70.1.x86_64/src/common/system_signal_handling.c:101
#3  0x00007f23f5c55d00 in <signal handler called> () at /lib64/libc.so.6
#4  0x00007f23eec04344 in cd_window_device_changed_cb (device=0x4757960 [CdClient], window=0x429ccd0 [CdDevice]) at ../libcolord-gtk/cd-window.c:303
...
```

So libcolord-gtk is where I should look instead. Let's close this issue and reopen only if it turns out darktable is at fault (which doesn't seem likely at the moment).

**Comment by mkubecek** [comment]
For future reference: the issue was handled in [colord-gtk issue 22](https://github.com/hughsie/colord-gtk/issues/22) and is now fixed in project's git tree.
