### ISSUE TITLE
EXIF data regression in 4.4

### ISSUE THREAD

**Issue by etrigan63** [darktable-org/darktable#14750]
### Describe the bug

HEIF images have incorrect EXIF information shown. The bug is linked to exiv2 and was fixed in 0.2.7.7 and ported to 0.2.8.0-2. The previous version of dt (4.2.1) began showing the correct exif data when exiv2 was updated. This is no longer the case.

### Steps to reproduce

1. Import HEIF (.hif) images into darktable (I am using a Fuji X-T5).
2. Hover over any of the images and look at the exif info.
3. Data will show strange values. 

### Expected behavior

Report the metadata correctly as provided by exiftool.

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch latest rolling update LTS kernel

### Describe your system?

Bespoke SFF System
AMD Ryzen 9 5950X
64GB RAM
AMD XT6750RX GPU
Oodles of drive storage.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD XT6750RX with 12GB VRAM

**Comment by kmilos** [comment]
As discussed already in #14473, this is beyond the scope of darktable.

Btw, the fix has **_not_** been ported to 0.28.0-2 on Arch AFAICT.

**Comment by etrigan63** [comment]
Weird, it looked to my like it was fixed. Perhaps I was hallucinating.
