### ISSUE TITLE
Color calibration module: Temperature colors are backwards

### ISSUE THREAD

**Issue by salmo6** [darktable-org/darktable#14751]
### Describe the bug

In the color calibration module, if you select CAT with the illuminant setting for daylight, you get a temperature slider, which I often use for white balance adjustments. On that slider, the cool end of the spectrum is red and the warm end is blue. That should be the other way around.
![screenshot](https://github.com/darktable-org/darktable/assets/61993474/ed7583c1-6f33-4d9d-8a84-b330ff360835)

### Steps to reproduce

Go to color calibration module.
Select CAT from the top row of tabs.
Under illuminant, select Daylight.

### Expected behavior

The cool end of the spectrum would typically be blue and the warm end red.

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
The display is correct - lower color temperatures are redder, higher color temperatures are bluer.  In Color Calibration, you set the illuminant color, and the module then compensates for it to give you an adapted white.  So the bluer the illumination, the more red needs to be added to give a white-balanced image, and vice versa.

**Comment by salmo6** [comment]
> lower color temperatures are redder, higher color temperatures are bluer.

Hmm. This still seems backwards to me. For adjusting white balance, I've never seen a case where red=cool and blue=warm. Perhaps it's "correct", but I would say that it's counter-intuitive and confusing. When I use the slider to adjust white balance, I find that I need to tell myself to ignore the color bar and just look at the Kelvin values.

**Comment by ralfbrown** [comment]
Subjective "warm" and "cool" colors are the opposite of physical temperatures.....  When you raise the temperature of e.g. a bar of iron, it goes from dull red to bright red to orange to yellow to mostly white as it gets hotter (and would become blue-white if you could get it hot enough without vaporizing it).

**Comment by salmo6** [comment]
Yes, you are absolutely correct in the realm of physics: blue is hotter than red in a physical sense. But in the artistic/photographic realm that darktable users work in, it's more or less universally accepted that red colors are perceived as warm, and blue colors are perceived as cool. Think of red-skewed desert scenes that make the viewer perceive "hot" or blue-skewed ice-and-snow scenes that make the viewer feel "cold"; thinking of the opposite just doesn't work. It's not a battle I feel strongly enough about to fight over, but it would seem to make more sense to be consistent with accepted photographic and artistic conventions rather than physics, which in this case run counter to those conventions.

**Comment by parafin** [comment]
It was already said, that this slider is about temperature of the illuminant, meaning light. When you buy LED bulbs, do you expect higher Kelvin values to be bluer or reder? The slider is in K, it doesn’t say “artistic cold to warm”.

**Comment by salmo6** [comment]
Fair enough. But the consequence is that if I want my photo to be more red/warm, I slide the slider towards blue. That's the counter-intuitive part. Nothing I can't live with.

Unless there's another way I should be adjusting the white balance of my photos?

**Comment by MStraeten** [comment]
simply move the slider to that direction that gives the expected result.
if you can’t live with it, then don’t use color calibration - It‘s not worth sacrificing one's life for it ;)

**Comment by HSUfineprint** [comment]
White balance module has the display style @salmo6 asked,  the slider could be switched between no color, illuminant color, simulated. If color calibration has that feature too, that will meet both physical meaning and operation intuition requires.
