### ISSUE TITLE
Missing camera and picture information after export 

### ISSUE THREAD

**Issue by Nils-photo01** [darktable-org/darktable#14755]
### Describe the bug

After exporting the edited pictures, all the camera and picture information is lost. No Iso, shutter speed, camera model etc. Not even the daten when the picture was taken. In Darktable all the information is shown but the exportet jpg has nothing but the export date. 
I am using CR3 data. When using convertet DNG data the date when the picture was taken is in the export but the rest is missing as well. 

### Steps to reproduce

1. Import pictures (all data can be seen as picture information) 
2. Edit 
3. Export as jpg 
4. All the picture information is lost. The picture looks normal but the information is lost. 

### Expected behavior

Darktable should include all the information when exporting. This worked in previous versions already 

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 pro

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
Have you tried checking the metadata boxes in the export settings?

**Comment by Nils-photo01** [comment]
To be honest I am relatively basic editor. Which box do you mean or where do I find it? 
But thanks for the fast reply first of all! 
![1687522369614346863809951289171](https://github.com/darktable-org/darktable/assets/137493398/9e8cc56d-4bf5-438c-955a-8a0de6c98650)

**Comment by kmilos** [comment]
> Which box do you mean or where do I find it?

Hamburger menu of the export module, then "preferences":

![image](https://github.com/darktable-org/darktable/assets/4973094/29710048-9441-4734-b659-f4c2d8cae961)

**Comment by Nils-photo01** [comment]
Thank you so much. Thats it. Perfect

**Comment by kmilos** [comment]
Please consider closing the issue if resolved then, and also please search before opening new ones: https://github.com/darktable-org/darktable/issues/12394, https://github.com/darktable-org/darktable/issues/12352, https://github.com/darktable-org/darktable/issues/14303, etc.

**Comment by HB9HFJ** [comment]
Thanks kmilos for the tips. It works fine for me There are plenty of same request on the net with no solution. You got it !
