### ISSUE TITLE
Darktable arm version 4.4.0 doesn't contain version numbers 

### ISSUE THREAD

**Issue by AmnaSN** [darktable-org/darktable#14758]
### Describe the bug

The arm version 4.4.0 doesn't contain version numbers. svs empty and bv just contains a dot

### Steps to reproduce

Right click app, click on Get Info
I used Apparency as well.

### Expected behavior

Correct the version number

### Where did you install darktable from?

darktable.org

### darktable version

darktable-4.4.0-arm64

### What OS are you using?

Mac

### What is the version of your OS?

macOS Monterey

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

![Screenshot 2023-06-23 at 9 21 26 PM](https://github.com/darktable-org/darktable/assets/101668818/6812f061-b411-49ee-850d-03d04c4dac24)

**Comment by rschumm** [comment]
...same version is also crashing with: «„Darktable.app" is damaged and cannot be opened. ....» The Signature is not fitting, I suppose.

**Comment by kmilos** [comment]
> «„Darktable.app" is damaged and cannot be opened. ....» The Signature is not fitting, I suppose.

@rschumm That is a separate issue, see https://github.com/darktable-org/darktable/issues/14746.

**Comment by zisoft** [comment]
@MStraeten: The `CFBundleVersion` and `CFBundleShortVersionString` entries are empty in `Info.plist` of the macOS arm dmg.

**Comment by MStraeten** [comment]
the build was made using the official tar.gz source file.

**Comment by zisoft** [comment]
Fixed in 4.4.1
