### ISSUE TITLE
Issues editing ARW file from Sony A7IV (ILCE-7M4) in Darktable

### ISSUE THREAD

**Issue by redteamcafe** [darktable-org/darktable#14766]
I am trying to upload and edit images in Darktable that were shot on my Sony A7IV (ILCE-7M4). Referencing the camera support table on https://www.darktable.org/resources/camera-support/, appears to see that the hardware is supported. When I am trying to edit the images in Darktable, I get the following errors:

"failed to read camera white balance information from <filename>.ARW"
"darktable could no load <filename>.ARW. Switching to lighttable now"
"please check that the camera model that produced the image is supported in darktable (list of supported cameras is at https://darktable.org/resources/camera-support/). if you are sure the camera model is supported, please consider opening an issue at https://github.com/darktable-org/darktable"

Reference:
Image uploaded to https://raw.pixls.us/ as BACKyrd.ARW

**Comment by LebedevRI** [comment]
Which darktable version? Is that with the new lossless compressed RAW's?

**Comment by redteamcafe** [comment]
running "darktable --version" give me 4.2.1 It looks like the latest stable version released is 4.4.0. I am guessing that this might be the issue but I am not sure what release Sony A7IV support was added since its a relatively newer camera body.

**Comment by LebedevRI** [comment]
Yup, the support was added in some later dt version.

**Comment by tamkaho** [comment]
> Yup, the support was added in some later dt version.

still doesn't work for dt 4.8?

**Comment by tamkaho** [comment]
i downloaded some a7iv samples from dpreview to check the noise profile and how it compares to other camera. Now I suspect this might just be an issue with dpreview's files.
