### ISSUE TITLE
Missing code signature in MacOS v 4.4.0 intel & arm

### ISSUE THREAD

**Issue by suschizu** [darktable-org/darktable#14763]
### Describe the bug

The apps are not signed properly - code signature is missing: 

EXPECTED 'XIMEA s.r.o. (85Q3K4KQRY)' but FOUND ''

### Steps to reproduce

codesign -dv --verbose=4 /Path/To/Application.app

### Expected behavior

the app should open without warning

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Monterey

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

<img width="372" alt="Screen Shot 2023-06-23 at 21 42 44" src="https://github.com/darktable-org/darktable/assets/16004333/7fe3d3b8-a841-456e-aa75-cd2b5cbb8db9">

**Comment by kmilos** [comment]
Duplicate of #14746.

Please search before opening new issues.

**Comment by suschizu** [comment]
sorry - I was searching for code signature not for broken version
