### ISSUE TITLE
Liquify displays 3 quarter-circles of garbled pixels in grow and shrink mode

### ISSUE THREAD

**Issue by isagalaev** [darktable-org/darktable#14760]
### Describe the bug

In the new 4.4 Liquify displays three quarter-circles of garbled pixels when switched into a grow or shrink mode by ctrl+clicking on the arrow inside.

The linear mode is not affected.

![image](https://github.com/darktable-org/darktable/assets/99931/949c329a-3cf6-4075-ad9f-8ad6a527759d)

### Steps to reproduce

1. With any image, go into darkroom.
2. Open Liquify and put a circle somewhere — observe it working as expected with the default settings.
3. Ctrl+click on the end of an arrow inside the Liquify circle shape.
4. Observe three quarters of the Liquify circle become garbled.

### Expected behavior

Liquify should switch to the grow mode and smoothly enlarge the center of the circle.

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/99931/949c329a-3cf6-4075-ad9f-8ad6a527759d)

### Where did you install darktable from?

distro packaging

### darktable version

1:4.4.0-0build1~lunar (from https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/darktable)

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Thinkpad X1 Carbon with Intel GPU, running Wayland with fractional display scaling.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Skylake GT2 [HD Graphics 520], 256MB memory, i915 kernel driver

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- This only appeared in 4.4.
- Reproducible both in RAW and JPEG, on fresh history.
- Happens both under OpenCL and without it (although the garbled portions looks different, but still garbled.)

**Comment by isagalaev** [comment]
We may not be out of the woods yet. It looks like the fix revered the order of grow and shrink operations: 

"Grow" looks like this:

![Screenshot from 2023-06-26 17-11-46](https://github.com/darktable-org/darktable/assets/99931/f2741a45-efc9-47d3-8942-d6027fd74d9f)

"Shrink" looks like this:

![Uploading Screenshot from 2023-06-26 17-11-55.png…]()

Note that the direction of arrows is correct, while the rendering effect is reversed. Which also means that existing edit histories will be reversed on re-rendering as well.

**Comment by TurboGit** [comment]
@ralfbrown 
Yes, and a regression compared to 4.2.1. A grow in 4.2.1 will be rendered as a shrink in 4.4.0. This is to be fixed in 4.4.1 as quite important regression.

**Comment by TurboGit** [comment]
I'll add a test to ensure those modes are checked.

**Comment by TurboGit** [comment]
The issue has been introduced in:

```
commit f8ea624a5f85d3b06cbb84a84e5484bacbfaaa50
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Mon Apr 3 01:07:19 2023 -0400

    optimize liquify
    
    Combine computing the stamp and applying it to reduce memory traffic
    while building the distortion map.
    
    Reduce looping in apply_global_distortion_map.
```

**Comment by TurboGit** [comment]
@ralfbrown : see #14790.

**Comment by isagalaev** [comment]
Confirming working as expected!
