### ISSUE TITLE
Renaming an unnamed module defaults to 0

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14774]
Ctrl+click on an un-named module. The text box that appears to enter the name defaults to "0" even though the number "0" was not initially displayed in the module name. It should default to an empty module name for the first instance, as it used to prior to 4.4.

4.5.0+20~gf2af5f8271

**Comment by TurboGit** [comment]
Cannot reproduce this. Really strange, that's the second report that I cannot reproduce. On my side an unnamed module doesn't get a 0 in entry when I try to rename it. Maybe an old edit where there is a 0 with some spaces around? Can you share an XMP?

**Comment by elstoc** [comment]
> Maybe an old edit where there is a 0 with some spaces around?

Nope I always make sure I can reproduce with a fresh edit. This is after discarding history, and I don't have any automatic presets, so an XMP probably won't help
