### ISSUE TITLE
Impossible to remove the name from an auto-named module

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14775]
On a new edit, the label of the exposure module (for example) defaults to "scene-referred default" based on the auto-preset. If I Ctrl+click on the module name and try to clear the "scene-referred default" name it automatically reappears when I commit the name change.

Physically deleting the name should be treated as an intentional edit and the module name should not be subsequently updated.

4.5.0+20~gf2af5f8271

**Comment by TurboGit** [comment]
When you have auto-naming enabled? That's expected in this case as clearing the entry means that we can again recompute the default. That's needed after you have entered and hand-edited name.

**Comment by elstoc** [comment]
> When you have auto-naming enabled? That's expected

Yes. It might be expected by you but most people will think removing the name should remove the name. I doubt a regular user will think to set it to an empty space, and in that case you'd see a bullet and no text, which would look odd.

**Comment by tpinfold** [comment]
I just experimented in V4.4 and V4.5 and I noticed that if I renamed the exposure module, but then I decided to select another preset that it still retains the name I had given it. I see this as a minor issue, but was surprised this was the case. Maybe it is intended.

**Comment by elstoc** [comment]
@tpinfold: I think that is expected -- once you've physically renamed the module it should never be auto-updated again.

**Comment by tpinfold** [comment]
The ability to rename modules or have the modules named after the preset chosen is a step forward for darktable. Learning that I need to clear the name by deleting whatever name I have given it is just a small learning curve I need to remember. BTW, I love how the snapshots now remember the name of the current module in use. I found this helpful recently when comparing base curve, filmic and sigmoid on a specific image.
