### ISSUE TITLE
Retouch module issue when using bilateral filters on amd opencl

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#14778]
### Describe the bug

When using bliteral filters (in wavelet decomposition mode) amd opencl drivers are again causing problems when zooming. This goes to @jenshannoschwalm I guess to make you happy again :D

DEVICE:                   0: 'gfx803'
   PLATFORM NAME & VENDOR:   AMD Accelerated Parallel Processing, Advanced Micro Devices, Inc.
   CANONICAL NAME:           amdacceleratedparallelprocessinggfx803
   DRIVER VERSION:           3558.0 (HSA1.1,LC)
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          8192 MB
   MAX MEM ALLOC:            6963 MB
   MAX IMAGE SIZE:           16384 x 16384

### Steps to reproduce

Use retouch module and use bilateral softening (I am using it in the 5th decomposition scale) and zoom the image. Strange artifacts appear. This stops when disabling the retouch module

### Expected behavior

Not showing strange artifacts when zooming

### Logfile | Screenshot | Screencast

![Eingefügtes Bild 1](https://github.com/darktable-org/darktable/assets/920721/4c28ac18-d883-412c-9f4a-462d79994b8b)

### Where did you install darktable from?

Arch repos

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch Liux

### Describe your system?

Linux 6.3.9, Wayland, 64 GB Ram, Ryzen 7950X

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Polaris RX 580 GPU (all time favorite)

**Comment by jenshannoschwalm** [comment]
IIRC you did "some dirty tricks" by passing some kernel parameters to make the driver working?

**Comment by piratenpanda** [comment]
Polaris is not enabled by default in the latest drivers as AMD "dont test it regularly" that's why you need to put the pre vega enablement code in /etc/environment but except from that no changes

**Comment by jenshannoschwalm** [comment]
I am really sorry about this but i certainly don't feel like trying to fix this in dt at this point. No hardware here, non-vendor supported driver/hardware combination it seems to me...

**Comment by piratenpanda** [comment]
Totally understandable. It's time to move on for me I guess

**Comment by jenshannoschwalm** [comment]
I you really are going into this, let me know if you run into problems / things you don't understand, will try to assist as good as i can.

**Comment by piratenpanda** [comment]
fixed by upgrading to latest rocm version 5.6.0
