### ISSUE TITLE
Documentation issue  

### ISSUE THREAD

**Issue by Graycard** [darktable-org/darktable#14771]
On p. 61 of "The Fine Manual" for dt 4.4, it says, 
"You can add new widgets to the panel by
right-clicking on the “hamburger” icon at the top-left of the panel."  

I'm requesting that the verbiage be changed to read, 
"You can add new widgets to the panel by
right-clicking on the “slider” icon at the top-left of the panel" 
since all "hamburger" icons are in the top right corner as a standard convention, and to help those reading "The Fine Manual" make the distinction that the slider icon is not a hamburger.

**Comment by Nilvus** [comment]
So this is for dt docs repository. please post that issue on correct place: https://github.com/darktable-org/dtdocs
