### ISSUE TITLE
Crash: switch to lighttable while naming a module

### ISSUE THREAD

**Issue by apostel338** [darktable-org/darktable#14777]
### Describe the bug

Switching to lighttable while naming a module crashes dt.

### Steps to reproduce

1. Open photo in darktable
2. Ctrl + click to name a module
3. While text box is still open, switch back to lighttable
4. Crash

### Expected behavior

Not crash

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/96216629/d0351923-b7ac-408b-9fa7-41c39f983b0f

[darktable -d all.txt](https://github.com/darktable-org/darktable/files/11859815/darktable.-d.all.txt)
[darktable_bt_RGX061.txt](https://github.com/darktable-org/darktable/files/11859816/darktable_bt_RGX061.txt)

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+20~gf2af5f827

### What OS are you using?

Linux

### What is the version of your OS?

Tumbleweed

### Describe your system?

Operating System: openSUSE Tumbleweed 20230622
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.7-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B450 I AORUS PRO WIFI

### Are you using OpenCL GPU in darktable?

Yes

**Comment by jenshannoschwalm** [comment]
Can confirm if clicking the lighttable button as shown in video, not confirmed if return to lighttable via double-click.

**Comment by jenshannoschwalm** [comment]
@dterrahe do you have an idea how this can be fixed?

**Comment by dterrahe** [comment]
Adding `gtk_widget_grab_focus(widget);` at the end of `_dt_ctl_switch_mode_prepare` (in `control.c`) fixes it for me.

**Comment by jenshannoschwalm** [comment]
@dterrahe checked and can confirm, you do the pr?
