### ISSUE TITLE
4.4.x Module automatically disabled/reset when exiting darkroom view

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14773]
I'm running on the 4.4.x branch (with just a minor code tweak to remove the bullet in the module header) and I've just encountered an issue whereby, when exiting from the darkroom to lighttable view, the top module of the stack seems to be automatically turned off. On the example image below, I had this happen with both filmic rgb and with the exposure module. I've given an example of the latter in the attached video:

https://github.com/darktable-org/darktable/assets/9555491/a5ff6db9-fb61-4e11-8eda-a286bdaddb36

Interestingly it seems to happen for both filmic and exposure but not for "exposure 1". Also happens for color calibration but not diffuse or sharpen.

**Comment by elstoc** [comment]
Also reproduced on master (4.5.0+20~gf2af5f8271) and I can't reproduce it if I check "preferences > processing > automatically update module name".

@TurboGit looks like one for you

**Comment by elstoc** [comment]
Actually it doesn't just disable the module, it resets it as well

**Comment by TurboGit** [comment]
I doubt this is due to one of my changes, it looks like a missing commit-parameter when just enabling the module. I bet that if you also expand the module, change some settings and collapse it before leaving to lighttable it is ok. Can you test that?

**Comment by elstoc** [comment]
Nope, same error. As I say it doesn't happen if the module is renamed or if the auto-renaming functionality is turned on, which is why I concluded it was related to the module naming changes.

**Comment by TurboGit** [comment]
I cannot reproduce, with one or multiple instances of exposure. So probably some more context is needed for this to happen. Any idea? Do you have this on all your pictures? If not can you see what could trigger this behavior?

**Comment by elstoc** [comment]
This happens on _every_ image for me (or at least all those I've tested). Reproduction steps are...

1. Uncheck preferences>darkroom>automatically update module name
2. (optionally) restart darktable
3. Open an image in the darkroom
4. Reset history (by clicking the reset button in the history module)
5. Increase exposure (both to change the settings and put exposure on the top of the stack -- exposure should have an empty label
6. Double-click the image to exit to lighttable
7. Double-click the thumbnail to re-enter the darkroom
8. See that exposure is disabled/reset

I can also reproduce this after removing darktablerc

**Comment by apostel338** [comment]
I'm in on it too. As elstoc stated, only with `automatically update module name` deactivated. Please let me know if I can offer some specific testing or data.

https://github.com/darktable-org/darktable/assets/96216629/885f6941-4a34-4ac9-8682-1e762d2e2e0e




Operating System: openSUSE Tumbleweed 20230622
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10
Kernel Version: 6.3.7-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B450 I AORUS PRO WIFI

**Comment by TurboGit** [comment]
Ok I can reproduce with @elstoc details steps.

**Comment by TurboGit** [comment]
I confirm a missing parameter commit somewhere as even with the auto-module on I can have this issue if you exit the darkroom very fast (before the module renaming circuitry is called and the commit done).

**Comment by elstoc** [comment]
IMO this one is severe enough for a fairly quick 4.4.1 release and perhaps a 4.4.2 in a month or two.

**Comment by TurboGit** [comment]
The commit introducing the bug is:

```
commit 6cd9d000db1f64f5c92572ea82e3f594c7c9ab31
Author: Pascal Obry <pascal@obry.net>
Date:   Tue May 2 18:08:42 2023 +0200

    Rework the default modules for different workflows.
    
    Instead of hardcoding the module to load in develop each module now
    set a default presets based on the current workflow. This preset is
    auto-load and auto-init (using module's default). We so take
    advantage of the recent default preset rework to further simplify
    the code.
```

So really not the auto module naming, yet not sure what the issue.

**Comment by elstoc** [comment]
That commit changes all of the workflow-based automation to use presets so maybe the issue doesn't lie directly with that commit, but rather how the auto-apply presets functionality actually functions?
