### ISSUE TITLE
Lua property to identify last modified timestamp of an image

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#14782]
**Is your feature request related to a problem? Please describe.**

I want to write a script that can identify images based on the timestamp it was last modified so that I can manipulate them. For example, export all images edited after a certain timestmap. 

There is currently `dt_lua_image_t.exif_datetime_taken`, from EXIF, that indicates when a photo was taken. There is no timestamp that indicates when a photo was last modified.

**Describe the solution you'd like**

The type `dt_lua_image_t` should have a property indicating its last-modified timestamp.

**Alternatives**

The type `dt_lua_image_t` can also have its full history available via Lua along with when each operation was performed.

**Comment by wpferguson** [comment]
The import, change, export, and print timestamps could be added to dt_lua_image_t.
