### ISSUE TITLE
Activate the 'save' button with 'enter' key in src/libs/tagging.c

### ISSUE THREAD

**Issue by josephpaul0** [darktable-org/darktable#14787]
In Darktable GTK on Linux, some pop up windows like the 'edit tag' window do not activate the 'Yes/OK/Save' button by default. As a consequence, it is not possible to use the 'enter / return' key to activate/press the button and the mouse must be used to click on it.

A very simple solution would be to activate the default 'confirm/OK/save' button.

src/libs/tagging.c
 _pop_menu_dictionary_edit_tag(GtkWidget *menuitem, dt_lib_module_t *self)
[...]

  // Set 'Enter' key to activate the default button and make 'OK' button the default button
  gtk_dialog_set_activatable(dialog, TRUE);
  GtkWidget *ok_button = gtk_dialog_get_widget_for_response(dialog, Gtk.ResponseType.OK);
  gtk_button_set_can_default(ok_button, TRUE);
  gtk_button_grab_default(ok_button);

When editing lots of tags, it saves precious time.
What do you think ?

**Comment by dterrahe** [comment]
A simpler way of doing this is just
`gtk_dialog_set_default_response(GTK_DIALOG(dialog), GTK_RESPONSE_YES);`
and for the Entry field (which is focused by default)
`gtk_entry_set_activates_default(GTK_ENTRY(entry), TRUE);`
otherwise it would swallow the Enter press.

Similarly, for the TextView field, which uses Enter for newline, it would be useful to set
`gtk_text_view_set_accepts_tab(GTK_TEXT_VIEW(synonyms), FALSE);`
so that you can use the Tab key to leave that field and focus the buttons, where you can then press Enter to activate them.

It would be useful for somebody to go over all the dialogs and judiciously add this everywhere.

**Comment by rmknan** [comment]
Hello, I would like to help with this. Should I follow @dterrahe ? and how do I go over these dialogs as in where do I add these lines in the file?

**Comment by dterrahe** [comment]
@Nilvus currently focused buttons in dialog are not visually distinct from unfocused ones, so it is not clear, when pressing Tab to cycle through all the elements, which button would be activated when pressing Enter. Would this be fixable?

**Comment by rmknan** [comment]
Okay so for example,  
` GtkWidget *dialog = gtk_dialog_new_with_buttons(_("delete tag?"), GTK_WINDOW(win), GTK_DIALOG_DESTROY_WITH_PARENT,
                                  _("cancel"), GTK_RESPONSE_NONE, _("delete"), GTK_RESPONSE_YES, NULL);`
I add:
`gtk_dialog_set_default_response(GTK_DIALOG(dialog), GTK_RESPONSE_YES);`

and for:
`GtkWidget *entry = gtk_entry_new();`

I add:
`gtk_entry_set_activates_default(GTK_ENTRY(entry), TRUE);`

Is that correct?

**Comment by Nilvus** [comment]
This is possible. There is already a default  class for text-button to allow that. When I delete an image for example, "No" button is focused (contrast between unfocused one could be improved, I have few time for that actually). See screenshot below:
![image](https://github.com/darktable-org/darktable/assets/45535283/90cb738d-1e3f-4893-890d-e47c770bbcad)

**Comment by dterrahe** [comment]
> Is that correct?

A large part of the work involved in preparing (especially gtk related) PRs is experimentation and testing. Good luck!
I would also recommend installing the `devhelp` app for API information.

> This is possible.

I know! About every other (gtk) app does this, but it seems to go against dt styling.

**Comment by Nilvus** [comment]
> I know! About every other (gtk) app does this, but it seems to go against dt styling.

dt styling could change. Improving that part is a good thing I think. So I let @rmknan propose a PR for Gtk part and after that, I will propose better focus with CSS.

**Comment by rmknan** [comment]
> A large part of the work involved in preparing (especially gtk related) PRs is experimentation and testing. Good luck! I would also recommend installing the `devhelp` app for API information.

Could you tell me how do I test it once I change the file? I am still new to this.

Thank you, and could you assign me this issue?

**Comment by dterrahe** [comment]
https://github.com/darktable-org/darktable#building

**Comment by rmknan** [comment]
Which OS do you run tests in? In the readme file, it says windows is not stable enough.

**Comment by rmknan** [comment]
Could you please answer the previous doubt? @dterrahe @Nilvus

**Comment by victoryforce** [comment]
> Which OS do you run tests in? In the readme file, it says windows is not stable enough.

Do it with whatever OS you're most comfortable with. If it's Windows, no problem. The only thing is that macOS is the most problematic platform specifically in terms of GTK issues. The disclaimer you refer to in the readme is a general user disclaimer, nothing more.

> And can I verify the changes for some files first and then do them for the whole project? Will it work that way?

Of course it will.

> I edited some files containing these lines and made the changes but I haven't tested them yet.

There's nothing stopping you from making changes in one place, building the code and testing it, and then adding new changes (the code will be compiled incrementally, BTW).

**Comment by rmknan** [comment]
Hello, I have changed files under the libs folder as per the code above. I have installed the dependencies on Ubuntu 22.04. Now after that do run this in the terminal?
`./build.sh --prefix /opt/darktable --build-type Release --install --sudo`

**Comment by rmknan** [comment]
Hello, I am trying to compiler using the terminal but I run in to some issues. I have a few questions

> you have previously built darktable, don't forget to first completely remove (rm -R) the build and /opt/darktable directories to avoid conflicting files from different versions.

I understand removing the previous build and do that but what does " _**/opt/darktable directories"**_ mean?

2.) I have g++-12 installed and have removed g++ 11 but when building it says 11 is the version detected.

I have downloaded the stable release 4.4.2, Is that fine? and the below response is from doing `./build.sh`

````

Building directory:  /home/rmknan/Github/darktable/build
Installation prefix: /opt/darktable
Build type:          RelWithDebInfo
Build generator:     Unix Makefiles
Build tasks:         12

```
-- The CXX compiler identification is Clang 14.0.0
-- The C compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
  (Required is at least version "4.5")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindOpenMP.cmake:544 (find_package_handle_standard_args)
  CMakeLists.txt:90 (find_package)
`
```
```

**Comment by victoryforce** [comment]
> > you have previously built darktable, don't forget to first completely remove (rm -R) the build and /opt/darktable directories to avoid conflicting files from different versions.
> 
> I understand removing the previous build and do that but how to remove " _**/opt/darktable directories"**_ ?

BTW, you can run darktable for testing directly from the build tree without installing it to a target directory (such as `/opt/darktable`). If you still install darktable (that is, use `--install --sudo` in the build.sh command line), you can either simply delete this directory  (`rm -rf /opt/darktable`) before the next installation or use the `--clean-install` option.

> I have downloaded the stable release 4.4.2, Is that fine?

It is better to work on the current state of the git repo, because your changes will be applied to the current state of the code in the development branch (master), not to the previous release. Therefore, when working with older code, you run the risk that your changes will have a merge conflict.

So it would be better to fork the darktable repository on GitHub, then clone your fork locally and work with the master branch.

**Comment by rmknan** [comment]
> BTW, you can run darktable for testing directly from the build tree without installing it to a target directory (such as `/opt/darktable`).

How do I do that?

> ./build.sh --prefix /opt/darktable --build-type debug --install --sudo

I do not need to do this then?

**Comment by rmknan** [comment]
Okay, So I made the changes to the files under lib folder and build the repo using the command `/build.sh --prefix /opt/darktable --build-type debug `

It has built successfully without any errors, Now do I test it? if so how? Thank you.

**Comment by rmknan** [comment]
Do I have to Install to test the changes I made? Do i use this? .

`/build.sh --prefix /opt/darktable --build-type debug --install --sudo`

**Comment by rmknan** [comment]
While running in test mode,?How to toggle the specific dialog boxes? Thank you.

```
gtk_dialog_set_activatable(dialog, TRUE);
GtkWidget *ok_button = gtk_dialog_get_widget_for_response(dialog, Gtk.ResponseType.OK);
gtk_button_set_can_default(ok_button, TRUE);
gtk_button_grab_default(ok_button);
```
