### ISSUE TITLE
Export JPEG appears different to editor preview

### ISSUE THREAD

**Issue by RandomAccountt** [darktable-org/darktable#14784]
### Describe the bug

Once editing photo, the exported JPEG appears more saturated than the preview. 
![Screenshot 2023-06-26 131517](https://github.com/darktable-org/darktable/assets/30158779/c4161378-2d6a-4d62-9233-57430b8e2e6f)

### Steps to reproduce

1. Edit photo
2. Export to JPEG (8 bit) 
3. See images side by side

### Expected behavior

JPEG should look the same as the preview

### Where did you install darktable from?

darktable.org

### darktable version

4.2.0

### What OS are you using?

Windows

### What is the version of your OS?

Edition	Windows 11 Home Version	22H2 Installed on	‎23/‎10/‎2022 OS build	22621.1848 Experience	Windows Feature Experience Pack 1000.22642.1000.0

### Describe your system?

Device name	Personal-laptop
Processor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Installed RAM	8.00 GB (7.44 GB usable)
Device ID	3D966A40-0B0D-4D2D-9976-48472C31EF9F
Product ID	00325-81421-88999-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

GPU Nvidia GTX 1650

Main display is HDR however issues seems to persist on my non HDR display

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[DSCF5533.RAF.txt](https://github.com/darktable-org/darktable/files/11868782/DSCF5533.RAF.txt)
attached XMP file as .txt

**Comment by elstoc** [comment]
Unless darktable and the app you're using to view the photos are both colour managed it's hard to know if this is a real issue or not. How does the exported jpg look if you re-import it back into darktable?

**Comment by RandomAccountt** [comment]
Hi, thanks for replying. The JPEG looks more saturated in the lightable view, but then colours revert to looking to same as the edited RAW in the darktable view. I've attached screenshots to illustrate.
![lighttable](https://github.com/darktable-org/darktable/assets/30158779/6b9a8e35-fe0d-4ca4-8350-7d288b183532)
![darkroom](https://github.com/darktable-org/darktable/assets/30158779/56c4b962-61bc-4060-b19c-b0688cb2310d)

**Comment by RandomAccountt** [comment]
Noticed that the problem is resolved when changing my primary monitor from display 2 to display 1, opening Darktable, and then dragging it to display 2.

Could be related to #3619, wondering if there is any solution within Darktable that doesn't require changing monitor settings every time I open the application?

@elstoc

**Comment by elstoc** [comment]
No idea, I don't run windows

**Comment by gi-man** [comment]
@RandomAccountt Can you share the output of darktable-cmstest ??

In windows, the primary display is the laptop screen or the external monitor? I'm assuming that you are using the extended monitor mode, correct? If you set the external to be the only monitor, do you see the issue? If you set to

**Comment by RandomAccountt** [comment]
@gi-man where should I run darktable-cmstest? I'm not a computer guy hah.

My primary display is usually my external monitor, in extended monitor mode. The issue persists when set to external monitor only.

**Comment by RandomAccountt** [comment]
Also wanted to mention that I have an Nvidia GTX1650, as I had forgotten to include that originally

**Comment by gi-man** [comment]
You will need to start cmd via windows run. Then navigate to program files/darktable/bin and execute the darktable-cmstest from there.

**Comment by RandomAccountt** [comment]
Not recognised. Perhaps you meant darktable-cltest?

```
[dt_get_sysresource_level] switched to 1 as `default
  total mem:       7617MB
  mipmap cache:    952MB
  available mem:   3808MB
  singlebuff:      59MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
[opencl_init] found 2 platforms
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'NVIDIA GeForce GTX 1650'
   CANONICAL NAME:           nvidiageforcegtx1650
   PLATFORM NAME & VENDOR:   NVIDIA CUDA, NVIDIA Corporation
   DRIVER VERSION:           531.41
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          4096 MB
   MAX MEM ALLOC:            1024 MB
   MAX IMAGE SIZE:           32768 x 32768
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              1.306
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         B:\Programs\darktable\share\darktable\kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   KERNEL LOADING TIME:       1.9071 sec

[dt_opencl_device_init]
   DEVICE:                   1: 'gfx902'
   CANONICAL NAME:           gfx902
   PLATFORM NAME & VENDOR:   AMD Accelerated Parallel Processing, Advanced Micro Devices, Inc.
   DRIVER VERSION:           3276.6 (PAL,HSAIL)
   DEVICE VERSION:           OpenCL 2.0 AMD-APP (3276.6)
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          3176 MB
   MAX MEM ALLOC:            2264 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              2.885
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         B:\Programs\darktable\share\darktable\kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   KERNEL LOADING TIME:       0.3673 sec
[opencl_init] OpenCL successfully initialized.
[opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
[opencl_init]           0       'NVIDIA GeForce GTX 1650'
[opencl_init]           1       'gfx902'
[opencl_init] FINALLY: opencl is AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is ON.
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       1       0       0       1
[dt_opencl_update_priorities]           1       -1      1       1       -1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[opencl_synchronization_timeout] synchronization timeout set to 200
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       1       0       0       1
[dt_opencl_update_priorities]           1       -1      1       1       -1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[opencl_synchronization_timeout] synchronization timeout set to 200`

**Comment by victoryforce** [comment]
> Can you share the output of darktable-cmstest ??

There is no darktable-cmstest on the Windows platform.
