### ISSUE TITLE
Save drawn mask in style

### ISSUE THREAD

**Issue by webghostx** [darktable-org/darktable#14789]
I'm not sure if I'm missing something, but it seems to me that when saving a history stack as a style, drawn masks are just ignored. The modules are simply applied to the whole image.

Wouldn't it be useful to be able to store masks in styles? A simple application example would be a linear gradient mask for more contrast in the sky. Possibly other modules are using the same mask. At the moment, that would be the case for me for astro photos. It would be easier to have the mask saved, although you might have to adjust it a bit with each image. But still easier than redrawing and associate to each module individually.

The way I currently do it is to keep finding old images and copying their history stack

**Comment by ralfbrown** [comment]
See #17447.
