### ISSUE TITLE
Linear Rec2020 color space causes banding

### ISSUE THREAD

**Issue by aentwist** [darktable-org/darktable#14793]
### Describe the bug

Linear Rec2020 (and maybe others, from past experience) cause intense banding. I've seen linear and radial banding in several cases.

### Steps to reproduce

1. Export an image with a large gradient (i.e., the sky) in linear Rec2020

### Expected behavior

no banding

###### raw (Canon CR3) + sidecars

https://github.com/aentwist/darktable-rec2020-repro

###### sRGB

![IMG_7401-srgb](https://github.com/darktable-org/darktable/assets/46688047/fb3ca7db-fe1a-4c7e-8e58-ecb743c65e95)
![IMG_7413-srgb](https://github.com/darktable-org/darktable/assets/46688047/d2b3f879-d9a1-40a0-b09a-533a2e901234)

###### linear Rec2020

![IMG_7401-linear_rec2020](https://github.com/darktable-org/darktable/assets/46688047/69dc67a0-20cf-4cdb-9b63-afce5d04e35a)
![IMG_7413-linear_rec2020](https://github.com/darktable-org/darktable/assets/46688047/4074d665-4e7e-448c-bde8-98d56359e9c7)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Education

### Are you using OpenCL GPU in darktable?

None

**Comment by jenshannoschwalm** [comment]
Haven't seen this. But
1. update to 4.4 as none of the devs is likely to check on 3.8
2. Please provide the raw file!

**Comment by aentwist** [comment]
Yes sir - updated. Thanks for the direction. I can try on my Ubuntu 20 machine if this cannot be reproduced. Just lemme know.

**Comment by pitbuster** [comment]
I would say banding is expected if you are exporting to an 8 bit format, the colorspace is too big, so to go from one color step to the next you'd have a big difference, and hence the banding.

**Comment by aentwist** [comment]
Oooh interesting. I'll try JPEG 2000s! Maybe the extra 4 bits will prove it.

**Comment by TurboGit** [comment]
Rec2020 linear? I suppose that the issue. You can try non linear profile like ProPhoto, Rec2020 HLG. You should have the same issue with the "linear ProPhoto RVB" BTW.

**Comment by kmilos** [comment]
> I'll try JPEG 2000s! Maybe the extra 4 bits will prove it.

Why are you exporting a linear image to a lossy format in the first place? What are you trying to achieve? 12b will be pushing it for a linear profile as well. If you're archiving or interchanging, use a lossless format that's meant for that - 16b or float/half float TIFF, or float/half float EXR, or even 16b PNG.

**Comment by TurboGit** [comment]
@aentwist : Please close the issue if it is now clear on your side. TIA.

**Comment by aentwist** [comment]
<blockquote>
Why are you exporting a linear image to a lossy format in the first place? What are you trying to achieve? 12b will be pushing it for a linear profile as well. If you're archiving or interchanging, use a lossless format that's meant for that - 16b or float/half float TIFF, or float/half float EXR, or even 16b PNG.
<br><br>
[You need at least 10b even with a gamma transfer curve to be absolutely sure of no banding](https://daejeonchronicles.com/2023/01/25/is-the-barten-ramp-the-correct-threshold/) (so sRGB 8bit is kinda pushing it already, and breaks down if you try to show luminance greater than what it was meant for, i.e. 100-200nits). For linear scene referred encoding you need much, much more.
</blockquote>

Understood maybe 50% of this 😅

Would be storing RAW if archiving and TIFF if transferring. Common use case here. All I want is the Rec2020 gamut because [it is the widest available (Oklab is wider) without imaginary colors (ProPhoto)](https://developer.chrome.com/articles/high-definition-css-color-guide/). There are 3 space options that contain "rec2020". I picked the first one.

I cannot find information on what "linear" is. Otherwise, we have

> [Rec. 2020 defines a bit depth of either 10 bits per sample or 12 bits per sample.](https://en.wikipedia.org/wiki/Rec._2020#Digital_representation)

> [PQ is a non-linear [transfer function](https://en.wikipedia.org/wiki/Transfer_functions_in_imaging) based on the human visual perception of [banding](https://en.wikipedia.org/wiki/Colour_banding) and is able to produce no visible banding in 12 bits.](https://en.wikipedia.org/wiki/Perceptual_quantizer)

> [HLG is an [HDR format](https://en.wikipedia.org/wiki/HDR_formats_(for_displays)) that uses the HLG transfer function, [BT.2020](https://en.wikipedia.org/wiki/BT.2020) [color primaries](https://en.wikipedia.org/wiki/Primary_color) and a [bitdepth](https://en.wikipedia.org/wiki/Color_depth) of 10-bit.](https://en.wikipedia.org/wiki/Hybrid_log%E2%80%93gamma)

So maybe I wish incompatible options were not selectable because this is being unleashed on idiots like me. But I see it isn't so clear because you can "push it" if that for some reason made sense.

Not sure how, but the PQ transfer function looks ok on 8 bits. And linear on 12 looks kinda crazy but does not appear like the darktable preview at all (first image is wayyy darker, barely visible). This is tricky.

I guess JPEGs are limiting. But I want a widely supported lossy format for sure. Maybe I have to do more research. Thanks.
