### ISSUE TITLE
No default activation for filmic and exposure if preset  created

### ISSUE THREAD

**Issue by ctouz** [darktable-org/darktable#14799]
### Describe the bug

if there are no presets for film (or exposure) relative to a camera body, the auto mode relative to the scene opens the 2 modules at 'default' but as soon as one of the two modules is associated with a camera body, it no longer appears for another camera body (it should appear at default). you have to redo a preset for each camera body...

### Steps to reproduce

1. activate the scene-preferred (filmic) workflow
2.create a preset in filmic and/or an exposure for a body type
3.import raw data from another body
4.check the history to ensure that filmic and/or the default exposure are not activated...

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Describe your system?

Manjaro kernen 6.1
ram 16g
graphic card rtx3050

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

rtx 3050

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

with the scene-refered workflow setting (filmic) if I create a preset for a camera in filmic or exposure and then import raw from another camera filmic and exposure are disable

**Comment by TurboGit** [comment]
I'll have a look, I know what is going on. This behavior is due to recent workflow rework.

**Comment by TurboGit** [comment]
@ctouz : If you can compile dt, please can you check #14804. TIA.
