### ISSUE TITLE
Negadoctor seems to be partially broken in 4.4.0

### ISSUE THREAD

**Issue by trgFPV** [darktable-org/darktable#14794]
### Describe the bug

There seems to be a bug in the negadoctor module which causes the highlights to clip and introduce color shifts.
This only occurs if you try to use the whole histogram. Its most pronounced when adjusting the print exposure.

It affects  previous edits from previous darktable versions and new edits. 

I was able to reproduce it on both windows 11 and my arch linux machine.

### Steps to reproduce

1. Import a scanned non inverted color negative (or use the one I uploaded [here](https://drive.google.com/file/d/1PNXCi76aBpPzvf8ofjfDyxRHkEQrEkgq/view?usp=sharing) )
2. Enable the negadoctor module and set the parameters from top to bottom in each tab (left to right) as described in the manual for the negadoctor module
3. On the last tab (print properties) the highlights will start to clip in an ugly way when the virtual print exposure is adjusted  to the right. 

### Expected behavior

The highlights should not color shift when clipping

### Logfile | Screenshot | Screencast

![clipping highlights](https://github.com/darktable-org/darktable/assets/8902996/8d65fdbd-b6a7-4dab-92c2-cb7a2d4f716d)
This is the result if you try to extend the histogram to the right. On the histogram note the vertical bar on the very right

![no_clipping](https://github.com/darktable-org/darktable/assets/8902996/ba65531e-c676-4f9e-ad34-9ec25bec4454)
This is as far as I was able to push the print exposure adjustment.

The issue persists with the exported image.

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

Arch Linux, X11, 6GB of ram

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Can you reproduce with another darktable version(s)? **no, only with 4.4.0**
Can you reproduce with a RAW or Jpeg or both? **Was able to repoduce using tiff and rw2**
Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
If the issue is with the output image, attach an XMP file if (you'll have to change the extension to .txt)
Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
Do you use lua scripts? **no**

**Comment by TurboGit** [comment]
I cannot reproduce, when I adjust the virtual print exposure to the right I burn everything but no pink cast. Maybe due to another module activated?

**Comment by trgFPV** [comment]
@TurboGit 
I've had sharpen, orientation, local contrast enabled. 

I now disabled all of the other module leaving me with: 

- output color profile (default settings)
- negadoctor
- input color profile (default settings)


I've attached my .xmp file for this specific file and a export of darktable using this exact xmp.
[out-0560.tiff.xmp.txt](https://github.com/darktable-org/darktable/files/11891999/out-0560.tiff.xmp.txt)
![out-0560_0_Konica Pop Super, Ultramax](https://github.com/darktable-org/darktable/assets/8902996/34ed77c3-53b5-48d6-bacb-149ed479468f)

Screenshot from darktable
![Screenshot from 2023-06-28 10-33-55](https://github.com/darktable-org/darktable/assets/8902996/8b649c62-6b83-4485-8ea0-f5653bcf0915)

Can you reproduce my output?

**Comment by TurboGit** [comment]
Yes when I deactivate OpenCL I can reproduce. So this is a CPU code path issue only.

**Comment by TurboGit** [comment]
@ralfbrown : Another one for you, this regression is introduced by 2b8922ab144caa598713f11263c1d85bfd5b5f95. TIA.

**Comment by plougastel** [comment]
With a black & white picture, a scanned TIF negative, gradients in highlights are badly rendered for me when negadoctor is activated. This for 4.4.0 version, not before, GNU/Linux, without openCL.

Running darktable with "-d common" gives those lines for my picture:

<code>
[…]
18,7936 [iop_validate_params] `negadoctor' failed for type "float", field: Dmin[0]
18,7936 [iop_validate_params] `negadoctor' failed for type "float[]", for array element "3"
18,7936 [iop_validate_params] `negadoctor' failed for type "float[]", field: Dmin
18,7936 [iop_validate_params] `negadoctor' failed for type "float", field: wb_high[0]
18,7936 [iop_validate_params] `negadoctor' failed for type "float[]", for array element "3"
18,7936 [iop_validate_params] `negadoctor' failed for type "float[]", field: wb_high
18,7936 [iop_validate_params] `negadoctor' failed for type "float", field: wb_low[0]
18,7936 [iop_validate_params] `negadoctor' failed for type "float[]", for array element "3"
18,7937 [iop_validate_params] `negadoctor' failed for type "float[]", field: wb_low
18,7937 [iop_validate_params] `negadoctor' failed for type "dt_iop_negadoctor_params_t"
[…]
</code>

**Comment by ralfbrown** [comment]
@TurboGit will take a look tomorrow.
@plougastel array element 3 is the alpha channel, which isn't used in negadoctor so it should have no effect.  But I'll see about eliminating the warnings.
