### ISSUE TITLE
White balance and lens correction settings not copied

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#14795]
### Describe the bug

After I edit a picture in darkroom and change settings for the white balance and lens correction modules and copy its history stack in lighttable to other pictures the settings from both modules are not pasted into the others.
I have to go to "selective copy" and add both modules to copy them

### Steps to reproduce

1. open image in darkroom and change settings in the modules "white balance", "lens correction" and in other modules
2. go to lighttable and and copy the history stack using the "copy" button in the "history section" on the right
3. paste the history stack (overwrite mode) into another image and open it in darkroom 
4. settings of the modules "white balance" and "lens correction" are not pasted in the image, those from the other modules are there

### Expected behavior

darktable should include the modules "white balance" and "lens correction" for copy and paste

### Where did you install darktable from?

OBS

### darktable version

darktable 4.3.0~git1231.8d70e284-1+9458.1

### What OS are you using?

Linux

### What is the version of your OS?

Xubuntu 22.04

### Describe your system?

Xubuntu 22.04, 16 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GeForce GTX 1060 6GB, OpenCL 3.0 CUDA 11.7.102

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reproducable with and without OpenCL. When I choose "selective copy" both modules are inactive for copying.

**Comment by gi-man** [comment]
Can you try with a more recent build ? darktable 4.3.0~git1231.8d70e284-1+9458.1 is a few months old and I think we had a PR to fix this issue.

**Comment by ralfbrown** [comment]
There are several modules which are not copied by default (and must be explicitly selected with selective copy) because they have different effects on different cameras/lenses, so it is not safe to blindly copy their settings.  These include raw black/white point, white balance, orientation, and lens correction.

Copy & paste is working as designed.

**Comment by pphotography** [comment]
I tried it again after getting a never version from OBS, now I have darktable 4.5.0~git138.f3d841cd-1+10356.1
The behaviour is still the same. 

Copying white balance and les correction from one picture to another is not only safe, is a must-have when shooting in manual mode. Examples are multiple images for panorama stitching, model shootings in a studio or burst-shots in sports photography. All these images have to get the same settings including white balance and lens corrections.

**Comment by gi-man** [comment]
As Ralf explained, this is not a bug. This is the designed functionality for the Copy button. The manual explains the modules that are not copied: https://docs.darktable.org/usermanual/4.2/en/module-reference/utility-modules/lighttable/history-stack/#module-controls

**Comment by pphotography** [comment]
Every time I want to copy a history stack from one photo to another I have to click on "Selective Copy", then click on "White Balance" and "Lens correction". This is so frustrating and annoying. How can I change this behavior?

**Comment by gi-man** [comment]
To change this behavior, you can edit the code used to by the copy button. Clone the repo, make the edits in your repo and then build darktable with your changes.

**Comment by pphotography** [comment]
Where do I have to make these edits? I am not a programmer

**Comment by tepeko** [comment]
An easy solution is to create a style from the current history stack of an edited image in darkroom, then select photos in lighttable and apply the created style in the history stack tab.
