### ISSUE TITLE
Giving a 5-star rating to protected (read-only) images on import

### ISSUE THREAD

**Issue by andrewmackie** [darktable-org/darktable#14797]
Most cameras do not allow the photographer rate their images in EXIF data. Almost every camera, however, allows the photographer to protect images on the memory card, with the camera making them read-only files.

If a photographer protects one or more images on a memory card, it's logical to assume that the photographer considers these images to be their best, and therefore that they deserve a 5-star rating when imported into darktable.

Currently darktable has no option in the import tool which considers whether an image is read-only on the memory card. This means that the information provided by the photographer (when protecting images) is lost on import to darktable (although I see that the files are still marked read-only in the file system after import).

Can darktable please provide an option which allows read-only images to be imported as 5-star (perhaps also giving the photographer the choice of a different rating or a color label if they prefer)?

Would it also be appropriate for this feature to be on by default (with a 5-star rating) given that:
- darktable users might otherwise not discover this new feature, and
- it's easy for photographers to undo any unwanted rating after import, but quite difficult to create the lost information manually?

**Comment by Andrzej-Dziarnik-Mobica** [comment]
https://github.com/darktable-org/darktable/pull/15339
