### ISSUE TITLE
 Filmic V7 openCL disabled vs enabled- different output observed

### ISSUE THREAD

**Issue by bnpndxtr** [darktable-org/darktable#14791]
### Describe the bug

filmic V7 seems to produce different output with openCL enabled vs when openCL is disabled.

The effect is more noticeable when “highlights saturation mix” is adjusted to -50% (drag slider all the way to the left).

I’ve attached a simple test to illustrate what I’m seeing. I know that the filmic settings are not right (or needed) for a png image, but the point with this very simple example is to compare the results with openCL disabled to when it’s enabled. The results should be identical but they are not. The source file is a blue (0,0,1) rectangle against black.

I’ve attached the source file, xmp file, filmic v7 settings, and two output files (one for openCL disabled and one for openCL enabled).

I tried a similar check using filmic v6 and didn't see the same issue.

### Steps to reproduce

Add source file in DT using the attached XMP file (or adjust filmic using screenshots below).
disable openCL.
render jpg output file.
enable openCL.
render jpg output file.

source file:
![blue square on black](https://github.com/darktable-org/darktable/assets/137922346/a20177bd-2763-423d-a780-e3208e4ca5ef)

XMP file (renamed .txt):
[blue square on black.png.xmp.txt](https://github.com/darktable-org/darktable/files/11885466/blue.square.on.black.png.xmp.txt)

filmic v7 settings:
![filmic scene tab](https://github.com/darktable-org/darktable/assets/137922346/e29f4e49-df45-4332-a6e3-5d5363d30823)
![filmic look tab](https://github.com/darktable-org/darktable/assets/137922346/7185d4ee-1fca-4fed-92ea-eb475e9e2d7e)
![filmic options tab](https://github.com/darktable-org/darktable/assets/137922346/aafefa4b-fc06-4887-896f-6e3453ae345f)

Render with open CL disabled:
![blue square on black (no openCL)](https://github.com/darktable-org/darktable/assets/137922346/0b3cd74a-b8c9-4afb-9156-56012bc72f45)

Render with openCL enabled:
![blue square on black (openCL)](https://github.com/darktable-org/darktable/assets/137922346/2d4e76e2-9f39-4ff7-8054-da75fecb1c2c)

### Expected behavior

produce same results with openCL or no openCL.

### Where did you install darktable from?

self compiled

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21 Vanessa

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 3070 8GB GDDR6 PCI Express 4.0 Graphics Card

**Comment by jenshannoschwalm** [comment]
@ralfbrown could this be related to your performance and matrix improvements?

**Comment by TurboGit** [comment]
@bnpndxtr : Since it is self compiled can you check if you have the issue with commit 8f24448b5fa9edd36110d4d6038885e6d9d40895.

**Comment by ralfbrown** [comment]
@jenshannoschwalm Does seem like it, since I don't remember any other activity on the module during the 4.3 cycle.  The integration test should have caught a difference that large even when testing with the saturation mix at 0....
