### ISSUE TITLE
Raw black point not preserved on upgrade from 4.2.1 to 4.4.0

### ISSUE THREAD

**Issue by bgedzior** [darktable-org/darktable#14792]
### Describe the bug

After upgrade form 4.2.1 to 4.4.0 some of the older edits were completely destroyed, look like backwards compatibility was not preserved between versions. The edits are specifically panoramic DNG files generated by Lightroom. Edits for other raw files and HDR DNG files are correct.

In all versions of Darktable, panoramic dng files generated by Lightroom have strong pink tint that can be removed with 'Raw Black Point' module. After opening the edits in 4.4.0, there is a strong yellow tint. After adjusting 'Raw Black Point' once again, colours are appropriate, but the image lacks saturation and contrast. The problem is, that simple increasing contrast and saturation does help - more work is required to tune the look of the picture.

### Steps to reproduce

1. Create panoramic DNG file with Lightroom
2. Adjust Raw black point in Darktable 4.2.1
3. Upgrade Darktable to 4.4.0
4. Open the file in the darkroom view

### Expected behavior

The look of the image should be preserved between versions

### Logfile | Screenshot | Screencast

![01-DT4 2 1-after-import](https://github.com/darktable-org/darktable/assets/123125981/9db3f5b7-b5b8-4a0d-81ac-bc8ed19cce6b)
![02-DT4 2 1-raw-black-point](https://github.com/darktable-org/darktable/assets/123125981/90e4e446-f948-40ed-bc83-0994646c170b)
![02-DT4 4 0-raw-black-point](https://github.com/darktable-org/darktable/assets/123125981/94328ecf-a686-4001-8ef7-4c3cfab24e5b)

_No response_

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1~4.4.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RTX 2060 6GB

**Comment by MStraeten** [comment]
Please provide a sample - so it’s not possible to reproduce…

**Comment by bgedzior** [comment]
Thank you for the response. Files are to big for github. What is the preferred way to share?

**Comment by PeterWem** [comment]
Google Drive (don't forget to share), Dropbox, Sprend, WeTransfer.

**Comment by bgedzior** [comment]
Zip contains file and xmp:
https://drive.google.com/file/d/1KSyUlvbM7kuHY36r15ck7t5gUWnmxDAv/view?usp=sharing

**Comment by PeterWem** [comment]
Subimage 1 has black level 4194.
Subimage 4 has black level 35 11 41

4194 is correct for this file but isn't read by darktable.

**Comment by bgedzior** [comment]
As far as I understand, pictures must be demosaiced before stitching panoramic shots. I don't know about HDRs.

**Comment by bgedzior** [comment]
And the fact that these values are not read is one problem. But there is some difference between 4.4.0 and 4.2.1 that results in lack in backwards compatibility. This is quite important, at least for me, because I have quite a lot of panoramic DNGs edited in Darktable. I wuldn't want to reedit them again. For now, I reverted to 4.2.1.

**Comment by PeterWem** [comment]
Let's see what others say. Meanwhile you can create a preset with 4194 as black level .

**Comment by bgedzior** [comment]
What do you mean by 'a preset with 4194 as black level'? Black raw point has 4 sliders in DT 4.2.1 and 3 sliders on 4.4.0

**Comment by PeterWem** [comment]
You can create a preset from the hamburger menu to the right in the module. You can also try pressing Pass through in the same hamburger menu to see if you get four black levels and not three.

**Comment by bgedzior** [comment]
I know how to create a preset :) I don't know which value should I adjust. 'Black level 0', 'Black level 1', 'Black level 2' or 'Black level 3'? Btw, in DT 4.4.0 'Black level 3' is not anymore....

**Comment by PeterWem** [comment]
Adjust all black level values. I don't know why you have three and not four values why I asked you to click Pass through in the hamburger menu.

I still use 4.2.1 myself.

**Comment by kmilos** [comment]
From the release notes:

> Manual per-color black point adjustment is now possible for non-CFA (a.k.a. linear) raw images. Note that file-embedded levels might still not be set automatically on import.

From 4.4 you now set each color channel individually, hence the 3 sliders for demosaiced ("linear") DNGs. in 4.2.1 it would set the same level for all color channels from the average of 4 (it was expected you would set all 4 to the same value for such files). Since you had different values there to construct the average in some "weird" way, it now started having an effect.

**Comment by kmilos** [comment]
You can also try hitting the reset button on that module, should set it to file metadata values.

**Comment by bgedzior** [comment]
Great thanks for the response and suggested solutions, but this is not the main problem. Problem is lack of backwards compatibility between versions. Edits should never change between version, no matter what.

For now my best solution is to stay on DT 4.2.1. I migrated to Lightroom recently and I keep DT for older edits. Don't get me wrong, I don't think DT is bad, but I had my reasons for migration. I truly think DT it great piece of software, and I wish all the best to this project and all developers. I'm c++ developer myself, and I appreciate your work.

**Comment by jenshannoschwalm** [comment]
> You can also try hitting the reset button on that module, should set it to file metadata values:

There is some bug here, it doesn't work as it should but resets all three sliders to zero ann reports "passthrou" which is just wrong as subimage1 has blacklevels defined and those 1) must be set/respected if not set params.
 
```
Exif.SubImage1.BlackLevel                    Rational    3  4194/1 4194/1 4194/1
```

I guess @kmilos thats for you :-)

**Comment by jenshannoschwalm** [comment]
@LebedevRI may i ask for your assistance here?

I checked using the provided file and the raw blacklevels read in darktable `dt_imageio_open_rawspeed()` for this image are zero instead of what we get via exiv2 (4194).

**Comment by kmilos** [comment]
This is I guess https://github.com/darktable-org/rawspeed/issues/215

That's why the release notes already say "may not be read correctly".

**Comment by LebedevRI** [comment]
> @LebedevRI may i ask for your assistance here?
> 
> I checked using the provided file and the raw blacklevels read in darktable `dt_imageio_open_rawspeed()` for this image are zero instead of what we get via exiv2 (4194).

Yep, what @kmilos said.

**Comment by kmilos** [comment]
> resets all three sliders to zero ann reports "passthrou" which is just wrong

I think this might be some separate issue - it also sets it to "passthrough" on clean import (w/o the old xmp)...
