### ISSUE TITLE
Program hangs forever when trying to edit file from SMB

### ISSUE THREAD

**Issue by davidak** [darktable-org/darktable#14806]
### Describe the bug

When i try to edit a file from an SMB share, the program sometimes hangs forever.

### Steps to reproduce

1. double click on a photo to edit it (all pictures are on an SMB share)
2. program says "loading" but hangs forever

### Expected behavior

programs should not hang forever

### Logfile | Screenshot | Screencast

Demonstration: https://www.youtube.com/watch?v=QJdQZdU1z1A

Screenshot:

![Screenshot from 2023-06-29 19-57-04](https://github.com/darktable-org/darktable/assets/91113/8449b549-8b22-4dc0-b47f-e06b887ac92e)

Same issue 5 days ago
![Screenshot from 2023-06-24 09-33-50](https://github.com/darktable-org/darktable/assets/91113/61dd19cc-11ac-4135-a4cd-384d1bc20e9c)

### Where did you install darktable from?

distro packaging

### darktable version

4.0.0

### What OS are you using?

Linux

### What is the version of your OS?

NixOS 22.11.4588.93fddcf640c

### Describe your system?

Pantheon desktop ([Stack](https://elementary.io/open-source)) (Gtk, X11)

Intel i9-9900K processor with 3.6GHz
G.Skill Ripjaws 32 GB DDR4 RAM (3200 MHz)
Samsung 970 EVO Plus 1TB NVMe M.2 SSD
AMD Radeon RX 6600 XT graphics card with 8 GB VRAM
Gigabyte Z390 UD motherboard
Noctua NH-D15 cooler
be quiet! Straight Power 11 650 Watt power supply unit
Antec One Midi Tower case

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600 XT graphics card with 8 GB VRAM (amdgpu driver)

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Issue happened with Jpeg. Not tested with RAW.
Not reproducible when i try it. Only happens every few days.

Do you use lua scripts? no

Filesystem mounted with gvfsd-fuse

**Comment by pehar1** [comment]
Version 4.4 has been released last week. Please check if your issue persists after updating.

**Comment by ralfbrown** [comment]
This sounds like an OS-level problem.  darktable has no knowledge of where a file lives, it just uses operating system calls to open/read/write files.  So if e.g. the network drops a packet and the operating system keeps waiting for a response from the file server, the call won't return and darktable won't continue.

Your system likely has been configured with an excessively large (or even unlimited) timeout for SMB operations.  Reducing that to something reasonable like 5 seconds or so would help.

**Comment by davidak** [comment]
I can check that, but it would be good if the program works on all kind of systems.

Could darktable have a timeout for loading files and try again if it fails? And show an error instead of hanging completely.

**Comment by victoryforce** [comment]
@davidak Is your SMB mount soft or hard?

> Could darktable have a timeout for loading files and try again if it fails? And show an error instead of hanging completely.

Filesystems should not block I/O forever. It's just not right. Do not mount file systems this way. There is no point in complicating applications by forcing them to implement asynchronous I/O operations.

**Comment by paperdigits** [comment]
Hi fellow NixOS user. Can you please try and not use `gvfs-fuse` to mount the share, but rather mount it at the CLI using samba? I'm willing to be this is just gvfs being bad.

**Comment by davidak** [comment]
> Can you please try and not use `gvfs-fuse`

no. that's what my desktop uses. i would rather debug the issue more and fix it for everyone than ignore the issue and use something else. that's not a sustainable strategy

I did not get to debugging GVFS yet.

I noticed that the issue is reproducible when i have darktable open, suspend the system and resume it. When i try to edit a photo in darktable then, it hangs. I also had elementary Files (file browser) open and there i can open photos, so it does not have this issue.

I will investigate further.

**Comment by paperdigits** [comment]
That is quite rude.

Changing ocer to not gvfs would tell us whether gvfs-fuse has the issue or where if the issue is elsewhere.

**Comment by victoryforce** [comment]
> I noticed that the issue is reproducible when i have darktable open, suspend the system and resume it. When i try to edit a photo in darktable then, it hangs.

Is it true that you can't reproduce the hang without resuming from system suspension?

If the answer is yes, there will be another question: if you run darktable with the `--disable-opencl` CLI option, can you reproduce this hang?

**Comment by jenshannoschwalm** [comment]
> does that make any sense? does that option has anything to do with filesystem access??

Nope in a direct way. But there have been some issues with opencl drivers just "hanging" because of missing proper power management. The symptom would be the same, a standstill of dt. AMD has been notorious for such issues but we had such on nvidia too with some driver versions.

**Comment by davidak** [comment]
That kind of makes sense. I had issues with amdgpu driver where the system is unable to suspend or resume or the kernel is left in a tainted state, but generally working.

https://gitlab.freedesktop.org/drm/amd/-/issues/2223 a bugreport from me that was partly fixed
https://gitlab.freedesktop.org/drm/amd/-/issues/2635 a new issue

It makes sense that the program starts hanging when i try to edit an image, but not before.
So i assume nothing can be done here and such issues needs to be reported at the linked bugtracker.

**Comment by jenshannoschwalm** [comment]
@davidak  i am interested in your log with `-d opencl -d verbose` as commandline options after power suspend. Please clear your `.cache/darktable/cached_kernels` before doing so!

**Comment by davidak** [comment]
>i am interested in your log with `-d opencl -d verbose` as commandline options after power suspend.

after suspending and resuming, i got no terminal output. when i select a picture to edit in darkroom mode and then change crop, then go back to lighttable, it hangs again. terminal output:

```
349.405139 [pixelpipe_process] [full] using device 0
349.405149 [dt_opencl_check_device_available] use 5315MB (tunemem=OFF, pinning=OFF) on device `gfx1032' id=0
349.502463 [pixelpipe_process] [preview] using device -1
355.596724 [pixelpipe_process] [full] using device 0
355.596736 [dt_opencl_check_device_available] use 5315MB (tunemem=OFF, pinning=OFF) on device `gfx1032' id=0
355.622897 [pixelpipe_process] [preview] using device -1
357.205019 [pixelpipe_process] [preview/fast] using device -1
357.205043 [pixelpipe_process] [full] using device 0
357.205051 [dt_opencl_check_device_available] use 5315MB (tunemem=OFF, pinning=OFF) on device `gfx1032' id=0
358.352764 [pixelpipe_process] [preview/fast] using device -1
358.388927 [pixelpipe_process] [full] using device 0
358.388939 [dt_opencl_check_device_available] use 5315MB (tunemem=OFF, pinning=OFF) on device `gfx1032' id=0
```

I had the same lines before suspending while it worked. I did not see any errors in GVFS log.

![Screenshot from 2023-07-15 12-46-49](https://github.com/darktable-org/darktable/assets/91113/41a9775e-7f9a-47a1-86b5-da3fa23a8908)

Full output: https://gist.github.com/davidak/b59c422ff375702998678d92b35ee3b6

> Please clear your `.cache/darktable/cached_kernels` before doing so!

ok. i had these files in it
```
[davidak@gaming:~]$ ll .cache/darktable/
total 24
drwx------ 2 davidak users 4096 Apr 15  2022 cached_kernels_for_gfx1032_34060HSA11LC
drwx------ 2 davidak users 4096 May 19  2022 cached_kernels_for_gfx1032_34230HSA11LC
drwx------ 2 davidak users 4096 Jun 10 21:14 cached_kernels_for_gfx1032_34860HSA11LC
drwx------ 2 davidak users 4096 Mar 15  2022 cached_kernels_for_gfx803_33050HSA11LC
drwx------ 2 davidak users 4096 Feb 14  2022 cached_kernels_for_NVIDIAGeForceGTX1050Ti_49544
drwxr-x--- 8 davidak users 4096 Feb 14  2022 mipmaps-5d56da703d7670e9b1a8c2d158fe50d8d1ec615c.d

```

**Comment by jenshannoschwalm** [comment]
1. First thing surprising me is the calculated performance of your device. This can't be some hardware acceleration, you should certainly see something above 1.0 (i assume your card is faster than the cpu :-) That would hint at a mesa driver ???
2. could you repeat with `-d pipe -d opencl now` to see if (or where) your processing pipe hangs
