### ISSUE TITLE
darktable-4.4.0-arm64.dmg reported as damaged

### ISSUE THREAD

**Issue by tnargs** [darktable-org/darktable#14808]
### Describe the bug

[darktable-4.4.0-arm64.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.4.0/darktable-4.4.0-arm64.dmg) seems to install a darktable.app file that won't run and is reported as "damaged and can't be opened".

### Steps to reproduce

Download [darktable-4.4.0-arm64.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.4.0/darktable-4.4.0-arm64.dmg)
Run it. Select 'Replace' existing Darktable
Attempt to open the new darktable.app file.

Note that I have the xattr -d com.apple.quarantine ~/Downloads/darktable*.dmg command in place so Darktable apps will open when not purchased through the Apple Store. It is not that issue that I am having.

### Expected behavior

start

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.4

### Describe your system?

Basic Mac Mini M1 (silicon)

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
It's a broken error message from Ventura - it should be reporting an unsigned program (none of the devs have a signing key), not a damaged installatino file.
See https://www.darktable.org/install/#macos for instructions on getting past this.

**Comment by tnargs** [comment]
I am familiar with unsigned programs and their messages. 

This doesn't look like them.
<img width="270" alt="Screenshot 2023-06-30 at 10 03 38 am" src="https://github.com/darktable-org/darktable/assets/67847974/c666c389-0585-401c-ba93-94b54fcea1cb">

The instructions at the link didn't help either. The bit where they say, "You will be presented with similar-looking dialog, but this time there will be second button allowing you to run the application" doesn't happen. Instead I get the same image as above.

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/14746
