### ISSUE TITLE
GRIII input color profile inconsistent behaviour

### ISSUE THREAD

**Issue by maltmoose** [darktable-org/darktable#14814]
### Describe the bug

On the GRIII dng and possibly other cameras there is an issue with inconsistent input color profiles.
The issue appears to caused by having 2 .xmp files (one for the raw and one for the jpeg) in the same folder.
e.g 
GR12345.dng.xmp (for the raw)
GR12345.xmp (for the jpeg)

### Steps to reproduce

How to replicate the issue.

1. Load the dng file with both the dng and the jpeg .xmp files in the same directory.
2. Discard all the history stack from within the lighttable, the input color profile changes to **standard color matrix and linear req709.**
3. If you then reset the input color profile in the darkroom it changes to **embeded matrix and linear req2020.**
4. Discard all the history stack from within the lighttable, the input color profile changes to **standard color matrix and linear req709.**

The behaviour is inconsistent and caused by the jpegs .xmp file

Repeat the above steps but remove the jpeg xmp file and the behavior will be consistent and **embeded matrix and linear req2020.** will be used in both situations.

Link to a GRIII dng and the xmp that can cause the issue.

https://1drv.ms/f/s!AuwOgbxu0aclgZlolEP0cGIZhEGolw?e=24Lwpy

### Where did you install darktable from?

darktable.org

### darktable version

Latest 4.4

### What OS are you using?

Windows

### What is the version of your OS?

Edition	Windows 10 Home Version	22H2 Installed on	‎22/‎12/‎2021 OS build	19045.3086 Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Are you using OpenCL GPU in darktable?

Yes

**Comment by TurboGit** [comment]
> GR12345.xmp (for the jpeg)

This comes from another software most probably (Lr?) as darktable would have written `GR12345.jpg.xmp`.

**Comment by maltmoose** [comment]
Its possible GR12345.xmp (for the jpeg) is created from another software but not sure which, could be capture one, dxo, rawtherapee, ART. Its not Lr though as dont have it.
Still points to a bug in darktable though as the xmp shouldnt interfere with it.

**Comment by TurboGit** [comment]
@maltmoose : Should be fixed by #14815, an old regression introduced in 2016.
