### ISSUE TITLE
Using preset saved on a different ISO causes extreme color cast

### ISSUE THREAD

**Issue by 23foster** [darktable-org/darktable#14818]
### Describe the bug

If I open a 400 ISO image in lighttable without changing it, go back to darkroom, create a preset from it (using default options) and apply it to a 200 ISO image then the image goes completely green.  If I repeat the same process but starting with a 200 ISO image and apply it to a 400 ISO image it goes magenta.  If staying within the same ISO there is no issue.

Version is 4.4.0-0build3~jammy on Linux Mint 21.1 Cinnamon installed from ubuntuhandbook1/darktable PPA.

Raw files are .CR3 files from a Canon R5.

I've attached a -d common log and a saved dtstyle file.  I don't have a lot of experience filing bug reports so let me know if you need anything more.

[400 ISO Test.dtstyle.txt](https://github.com/darktable-org/darktable/files/11927187/400.ISO.Test.dtstyle.txt)

### Steps to reproduce

Open a 400 ISO image in darkroom, do not change anything
Go back to lighttable
Create a new preset from the image, keeping the default options
Apply preset to a 200 ISO image

### Expected behavior

color cast should not be changed

### Logfile | Screenshot | Screencast

[dt 4.4 preset bug.log](https://github.com/darktable-org/darktable/files/11927137/dt.4.4.preset.bug.log)

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.1 Cinnamon

### Are you using OpenCL GPU in darktable?

None

**Comment by 23foster** [comment]
I've managed to better narrow down the issue.  I went into the history stack and checked the image at each step.  I found that the item causing the color cast was the 'raw black/white point'.  It was the second last module applied and it was also the first one applied.  Editing the style and not including raw black/white point only leaves the original step 1 application and fixes the issue.

**Comment by gi-man** [comment]
Raw black and white points are ISO dependent in some cameras. Coping the values from one ISO to another can yield the issue you are seeing.

**Comment by MStraeten** [comment]
works as designed - the black point is iso specific for most canon EOS sensors, so the raw black/whitepoint module shouldn't be used in styles. libraw calculates the black point based on the image.
