### ISSUE TITLE
Premission to publish "Darktable" app in Umbrel App store

### ISSUE THREAD

**Issue by IMPranshu** [darktable-org/darktable#14810]
Hi team,

I need your team's permission to try and host this app on the Umbrel App Store. I would give appropriate credits and mention to your team and you will be the sole Developer of the App I am just publishing it to the Umbrel App Store for free as I have done with a lot of other OSS applications.

It would be great to have a go-ahead from your team before I go ahead and implement this.

Thanks,
Pranshu

**Comment by dterrahe** [comment]
> I need your team's permission to try and host this app on the Umbrel App Store.

No, you don't. Or rather, you have it, as long as you follow the conditions of the GPL https://github.com/darktable-org/darktable/blob/master/LICENSE

**Comment by IMPranshu** [comment]
@dterrahe Thanks. Just being extra cautious as this is a pre-step I do for before every PR
