### ISSUE TITLE
keep databases format frozen during minor releases

### ISSUE THREAD

**Issue by macsimski** [darktable-org/darktable#14819]
**Is your feature request related to a problem? Please describe.**

I am synchronizing multiple computers at my working place. home desktop, laptop, remote desktop using Unison. so basically they all have the same home directory. If i update a darktable version, say from 4.2.1 to 4.4.0, the newer darktable changes the databases format, so the minor older versions cannot be used anymore. this is quite frustrating when doing a sync at home and trying to start up darktable in the field, giving me a message that the database is newer than the version of darktable used. 

**Describe the solution you'd like**

In my opinion, minor updates are only bug related. major updates introduce new fundamental functionality. so please don't break a workflow by making changes to the databases in minor updates.

**Alternatives**

I have no clear alternative solution to this problem

**Additional context**

thanks for considering this.

Simon

**Comment by elstoc** [comment]
You are misunderstanding how we label our releases, based on a common naming convention that other projects use.

The upgrade from 4.2.x to 4.4.x is considered a major or feature release and will therefore frequently not be backward compatible with prior versions. We generally use the last number in the release name to denote fix-only releases, for example 4.4.1 is a fix release to 4.4.0. The next major feature release will be 4.6.0.

We are not able to guarantee database compatibility between major versions.

**Comment by macsimski** [comment]
Ah. thanks for explaining. good to know. thanks for the quick response.

**Comment by dterrahe** [comment]
From the release notes:

"When updating from the stable 4.2.x series, please bear in mind that your edits will be preserved during this process, but the new library and configuration will no longer be usable with 4.2.x.

You are strongly advised to take a backup first."

This seems clear to me but you are welcome to suggest alternative wording that could have helped you, and possibly others in future, avoid confusion.
