### ISSUE TITLE
Compiling dt 4.4.1 with LUA on Ubuntu 22.04

### ISSUE THREAD

**Issue by manu-p** [darktable-org/darktable#14820]
### Describe the bug

Darktable 4.4.1 compilation on Ubuntu 22.04 (the latest LTS as of today) does not include LUA option.
However, lua 5.3 is well installed:
```
root@8570w:~# lua -v
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
root@8570w:~# apt search lua5.3
En train de trier... Fait
Recherche en texte intégral... Fait
ipe/jammy 7.2.24+dfsg1-1build1 amd64
  éditeur de dessin pour la création de schémas dans les formats PDF ou PS

liblua5.3-0/jammy,now 5.3.6-1build1 amd64  [installé, automatique]
  interpréteur Lua version⋅5.3 –⋅bibliothèque partagée

liblua5.3-0-dbg/jammy 5.3.6-1build1 amd64
  symboles de débogage pour la bibliothèque partagée de l'interpréteur Lua

liblua5.3-dev/jammy,now 5.3.6-1build1 amd64  [installé]
  Development files for the Lua language version 5.3

lua5.3/jammy,now 5.3.6-1build1 amd64  [installé]
  Langage de programmation intégrable, simple et extensible
```

I've read somewhere here a package named lua5.3-dev (or -devel) should be installed, but it does not exist:
```
root@8570w:~# apt install lua5.3-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
E: Impossible de trouver le paquet lua5.3-dev
E: Impossible de trouver de paquet correspondant à l'expression rationnelle « lua5.3-dev »
root@8570w:~# apt install lua5.3-devel
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
E: Impossible de trouver le paquet lua5.3-devel
E: Impossible de trouver de paquet correspondant à l'expression rationnelle « lua5.3-devel »
```

### Steps to reproduce

Install dt 4.4.1 on Ubuntu 22.04 after installing gcc 12 and ++
Run dt 4.4.1
Find no LUA option

### Expected behavior

Compile with LUA option

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
darktable [requires lua version 5.4](https://github.com/darktable-org/darktable/blob/master/README.md?plain=1#L175), version 5.3 does not work. In this case, you can build darktable with the lua included in the darktable's source code tree. To do this, you need to specify `-DDONT_USE_INTERNAL_LUA=Off` when compiling. Specify this when calling cmake, or if you're using build.sh, in the way you can see in the [appimage-build-script.sh](https://github.com/darktable-org/darktable/blob/master/tools/appimage-build-script.sh) code.

**Comment by manu-p** [comment]
That was it, obviously. Thanks @victoryforce for pointing me to the solution.
