### ISSUE TITLE
Italian is missing after upgrate do 4.4.1 version

### ISSUE THREAD

**Issue by MauDarktable** [darktable-org/darktable#14825]
### Describe the bug

After the upgrade italian translation is missing.

### Steps to reproduce

1. Got to Settings
2. General
3. Interface language
4. I see de, en@truecase, en, es, fr, hu, pl, pt_BR, sq, sl, fi, ru, uk, he zh_TW, ja, zh_CN

### Expected behavior

italian should be available... I've used it in te lasts years

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Describe your system?

I have the same issue on two different Windows PCs with different hardware configurations. I suppose that the issue doesn't depends in them.

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
Right, Italian translation has been removed as missing quite a lot of strings. Maybe you could contribute?

See https://github.com/darktable-org/darktable/wiki/Translations

**Comment by MauDarktable** [comment]
I can try, of course. Please send me esistent translations, I'll try to integrate.

Thank you!
________________________________
