### ISSUE TITLE
Scroll stopped working in multiple modules (also in parametric mask module!) (Mac OS X)

### ISSUE THREAD

**Issue by davve2** [darktable-org/darktable#14822]
### Describe the bug

Since I upgraded to v4.4  (from version 4.2) I can no longer use several of the modules

Two examples
- color zones
- tone equalizer 

Most of them is possible to work around using other modules, but now I also found the same problem with the masking function which makes it almost impossible to do any more serious editing.

The reason they don't work is that I cannot modify the default setting. The link to the scroll action/trigger seem to have been broken. 

### Steps to reproduce

1. Go to an image
2. Click on color zones or "drawn mask"
3. Try to move the object of the the preset mask, or try to modify the line in the graph of the color zone module.
4. I tried scroll, touch, right click, left click + scroll, shift scroll, alt scroll, ctrl scroll etc no key combination allows me to change the size nor the position of the mask. For custom mask I can't even start drawing or painting the mask, it seems to be dead stuck in "origo" if that is located at the center of the image.
5. When trying to do it like before the upgrade it seems to zoom the centre field instead. Also using two fingers it auto start the rotation module and rotate the picture (unexpected behaviour).

### Expected behavior

Return the previous function of using the touchpad/scroll or at least clarify how to find some way of using the broken modules

### Logfile | Screenshot | Screencast

Unfortunately I cannot add any log file, I can not find it on the Mac and no documentation describing how to locate or create a log file. Hopefully it is possible to reproduce.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1-arm64.dmg

### What OS are you using?

Mac

### What is the version of your OS?

13.3.1 (a) (22E772610a) Mac OSX ventura

### Describe your system?

Swedish Apple M1 Pro keyboard

### Are you using OpenCL GPU in darktable?

No

**Comment by davve2** [comment]
After multiple reboots and restarts of darktable it is now working, but it was not the first time I started darktable so I'm afraid the problem may return. I leave the issue open until tomorrow in case other users seem to be able to replicated it or if I get new problems.

**Comment by zisoft** [comment]
@dave2: Is the issue still present or can it be closed?

**Comment by dave2** [comment]
> @dave2: Is the issue still present or can it be closed?

Looks like a typo, not my issue! :D

**Comment by zisoft** [comment]
ah, sorry.
--> @davve2

**Comment by davve2** [comment]
Sorry I´ve been on holiday. After an update I no longer have this issue! Thanks
