### ISSUE TITLE
No thumbnails on import from OM-System OM-1

### ISSUE THREAD

**Issue by wwwFrank** [darktable-org/darktable#14829]
### Describe the bug

Using "import" / "copy & import" on SD-Card Folder "OM System/DCIM/100OMSYS" the column "**show/hide thumbnails**" shows **no** thumbnails of the RAW picture (*.ORF) but only the darktable-**icon** for the camera-type "**OM-1**" from "OM-System".
On the same system it works for the older Camera OLYMPUS "E-M1 Mk. II" and some other cameras.

### Steps to reproduce

1. Module "import"
2. Button "copy & import"
3. SD-Card Folder "OM System/DCIM/100OMSYS"
4. Click on Symbol "Eye" in column "show/hide thumbnails"

### Expected behavior

Show thumbnail of the RAW-file

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2 LTS

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]

**Comment by kmilos** [comment]
Nothing to do w/ darktable per se, as already explained above, but with the Exiv2 version on your system darktable is using.

Ubuntu 22.04 seems to ship the older libexiv2-27 0.27.5-3ubuntu1, which does not support OM System cameras.

**Comment by Nilvus** [comment]
As it's not a darktable issue but Ubuntu update needed, I close. @wwwFrank: you can probably find a more up-to-date Exiv2 package on a PPA or on OBS darktable repository.
