### ISSUE TITLE
DT4.4 Documentation issue (RE Settings > Processing > auto-apply chromatic adaptation defaults)

### ISSUE THREAD

**Issue by arigit** [darktable-org/darktable#14824]
### Describe the bug

The option: "auto-apply chromatic adaptation defaults" is referred to in the current documentation here: https://darktable-org.github.io/dtdocs/en/preferences-settings/processing/

However that option is missing in DT4.4 and DT4.4.1

I believe the omission is by design, as discussed here, #12917, so the issue is that the documentation has not been updated to reflect this. 

Also, consistent with #12917, I am using a scene-referred workflow and I noticed the color-calibration module got auto-enabled.

I have to say though, coming from DT4.2 and now knowing about this change in white balance management, it took me a while to figure out that a) both White balance AND color calibration need to be enabled at the same time, and b) that white balance needs to be set to Camera Reference

### Steps to reproduce

Open preferences, navigate to Processing, and confirm that the option is actually missing.

### Where did you install darktable from?

flatpak

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia 1650

**Comment by TurboGit** [comment]
You should open an issue on dtorg project: https://github.com/darktable-org/dtorg/issues

As this is indeed not a dt issue. Note that the documentation is updated by a small team of volunteers so if you could provide a PR there it would be even better.

**Comment by arigit** [comment]
I created a pull request for this: https://github.com/darktable-org/dtdocs/pull/578
