### ISSUE TITLE
wrong instances order in Styles

### ISSUE THREAD

**Issue by bajdero** [darktable-org/darktable#14821]
### Describe the bug

When style is created based on image where are a few instances of module order follows the order of instance creation and not the order which modules where finally set by he user.

### Steps to reproduce

1) create color balance rgb instance named "1"
2) go to instance "1" and create instance "2"
3) go to instance "2" and create instance "3"
4) move instance "1" above "2" and instance "3" below "2" to achieve order 3, 2, 1 in pixel pipe
5) create style based on edited image
6) apply style to another image
7) observe the order 1, 2, 3 (order of module creation) instead of correct 3, 2, 1 order set by user

### Expected behavior

Style should apply instances in order set by the user in source image edit.

### Where did you install darktable from?

flatpak

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora Linux 38 6.3.8-200.fc38.x86_64

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RTX™ 3070 Laptop GPU, Driver Version: 530.41.03

**Comment by TurboGit** [comment]
Can you attach such a style here? TIA.

**Comment by TurboGit** [comment]
@bajdero : Also

> 7    observe the order 1, 2, 3 (order of module creation) instead of correct 3, 2, 1 order set by user

Where do you observe this?

**Comment by bajdero** [comment]
[instance order.zip](https://github.com/darktable-org/darktable/files/11948974/instance.order.zip)
On 3E0A1629.CR3 I created color banalnce rgb modules named "first created, second created, last created" on top of each other and then rearranged them in reverse order. 
Then created a style from default and 3 created color balace rgb modules.
Style applied on 3E0A1630.CR3 and modules are in order of creation, not the rearranged order.

**Comment by bajdero** [comment]
>> Where do you observe this?
Style creation image:
![Zrzut ekranu z 2023-07-04 13-59-58](https://github.com/darktable-org/darktable/assets/94252719/f7cfcf80-9a2e-4698-af74-40d1d70174a2)
second image after style applied:
![Zrzut ekranu z 2023-07-04 14-00-10](https://github.com/darktable-org/darktable/assets/94252719/52cece36-5994-4d5c-b248-787d5f338106)

**Comment by TurboGit** [comment]
@bajdero : That's expected, you need to select the module order in the dialog when you create your style otherwise the applied order is the one of the multi-instance.

**Comment by bajdero** [comment]
That's right. Sorry.
