### ISSUE TITLE
Turkish language not installed.

### ISSUE THREAD

**Issue by serkan-maker** [darktable-org/darktable#14837]
### Describe the bug

In darktable 4.4.1 version, Turkish language is not installed in windows 10 and ubuntu based distributions.

### Steps to reproduce

1. general preferences
2. general
3. interface language
4. 
[darktable.tar.gz](https://github.com/darktable-org/darktable/files/11946497/darktable.tar.gz)

### Expected behavior

Turkish language fully translated and up to date

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

win.10 and linux mint 21.1 cinnamon

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment]
Just complete translations are integrated into the release package.
Maybe you provide the missing translations…
See https://github.com/darktable-org/darktable/wiki/Translating-darktable

**Comment by serkan-maker** [comment]
I have been updating the Turkish translation of the project for about a year, and it is 100% translated.
When I move the .mo file to the usr/share/locale/tr folder, the application language is fully Turkish.

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________

**Comment by victoryforce** [comment]
> I have been updating the Turkish translation of the project for about a year, and it is 100% translated.

The last commit of your translation was on 13.05.2023. As I understand it, 100% was translated then. But the fact is that after that time there were string-changing commits in the codebase. Strings were frozen [only at the end of May](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06747.html).

At the time of the string freeze, the Turkish translation [had insufficient coverage](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06754.html) and was therefore [removed when the release was created](https://github.com/darktable-org/darktable/blob/master/tools/release/generate-translation.sh#L24-L25).

@serkan-maker I think you can close this issue as it was not a mistake in the release preparation process and there is actually no fixable bug here.

**Comment by serkan-maker** [comment]
I got it now. Thank you.
