### ISSUE TITLE
Darktable 4.4.1 for ubuntu 22.04 

### ISSUE THREAD

**Issue by zakfm** [darktable-org/darktable#14838]
Hello,
Do you think the darktable 4.4.1 version for Ubuntu 22.04 will be released soon ?
Sorry about my impatience...

**Comment by ptilopteri** [comment]
you should query the ubuntu packagers as they provide darktable for your distro.
or build it yourself.

**Comment by zakfm** [comment]
Thanks for your reply. It's usually provided for ubuntu. But here, it's only for 23.04.

**Comment by jenshannoschwalm** [comment]
Sorry but this is a darktable bug/issue tracker :-) You will find some information in forums like https://pixls.us/ on issues like this but this is a distribution issue. Running dt on Ubuntu 22.04 requires some tweaking ...

**Comment by zakfm** [comment]
Thank you very much! So we'll just have to wait and see
