### ISSUE TITLE
Get latest darktable stable in to Debian Unstable (sid)

### ISSUE THREAD

**Issue by luzpaz** [darktable-org/darktable#14833]
Is there anyone working on getting latest stable in to downstream Debian unstable (ATM named 'sid') ?  
ref: https://packages.debian.org/sid/source/darktable

Current version available is 4.2.1 (at the time of writing this ticket)

**Comment by gi-man** [comment]
You need to raise this issue with the distro maintainer. The link should be in the website you linked.

**Comment by luzpaz** [comment]
Ping @dbremner sorry just wondering if you are the David Bremner (debian maintainer of the Darktable package as it is listed in https://packages.debian.org/sid/source/darktable) ?

**Comment by dbremner** [comment]
> Ping @dbremner sorry just wondering if you are the David Bremner (debian maintainer of the Darktable package as it is listed in https://packages.debian.org/sid/source/darktable) ?  
  
Nope, that's someone else.
