### ISSUE TITLE
Masks with reconstruct in LCh

### ISSUE THREAD

**Issue by JohannMaierhofer** [darktable-org/darktable#14843]
### Describe the bug

It seems to me that mask handling in the highlight reconstruction module does not work as expected when using the reconstruct in LCh mode.
I have an image with clipped highlights. Highlight reconstruction in the Filmic RGB module is switched of. I want to do highlight reconstruction with the highlight reconstruction module using masks.

When I select the "inpaint opposed" mode the module behaves as expected. The clipping threshold is set to default 1 and the area matches the raw-overexposed warning. The module operates on the whole image. Now I select the drawn mask button. No change in the image happens so far. Now I draw a mask. The result is as expected. The effect is now applied just in the mask and the rest of the image shows the image as if the module is not applied.

If I repeat the same procedure whith the "reconstruct in LCh" mode the behaviour is different. Before setting the mask the module applies the reconstruction on the whole image as expected. But when I select the drawn mask button the image immediately changes in a way as if the module is switched off. The histogram changes similar to the switched off module. I now can place a mask but this does not change anything.

My opinion is that similar to the "inpaint opposed" mode, just selecting the drawn mask button should not change the image.

### Steps to reproduce

1. Set the highlight reconstruction module to default value via the default icon
2. Change method in in the highlight reconstruction module to "reconstruct in LCh" -> The method gets applied to the whole image
3. Select the drawn mask button -> The image changes in a way as if the module is switched off. See description above
4. Draw a mask -> No change in the image inside or outside the mask

### Expected behavior

Correct mask handling for reconstruct in LCh mode

### Logfile | Screenshot | Screencast

Figure with highlight reconstruction module disabled:
![Screenshot_20230705_114928](https://github.com/darktable-org/darktable/assets/126261667/c3767547-d199-4a01-8bc1-caab03a5e1b9)

Figure with highlight reconstruction module enabled and without mask enabled:
![Screenshot_20230705_114634](https://github.com/darktable-org/darktable/assets/126261667/4928acec-dff8-4ec8-b690-d81cba0126fa)

Figure with with highlight reconstruction module and mask enabled:
![Screenshot_20230705_114649](https://github.com/darktable-org/darktable/assets/126261667/2d28e4f2-40ba-4f21-a495-33ba83763c4a)

Figure with mask placed:
![Screenshot_20230705_114706](https://github.com/darktable-org/darktable/assets/126261667/9b107bdc-6808-4eda-bc51-03216cad34fd)

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1-4

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 23.04

### Describe your system?

I use X11 and Mesa Intel® UHD Graphics 770

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Mesa Intel® UHD Graphics 770

**Comment by JohannMaierhofer** [comment]
The same issue happens with "clip highlights"

**Comment by jenshannoschwalm** [comment]
A further note, only the OpenCL path seems to be affected ...

**Comment by jenshannoschwalm** [comment]
@JohannMaierhofer thanks for reporting!
