### ISSUE TITLE
Mouse cursor position unexpectedly changes selected image in lighttable

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#14840]
### Describe the bug

When exiting lighttable preview mode (`f`), the selected photo (last photo viewed in preview mode) unexpected changes to the photo under the mouse cursor. If mouse cursor is not hovering above a photo, then no unexpected change happens.

### Steps to reproduce

Reproduction:
* Open a library with a few photos
* Select a photo with mouse, then do not move cursor
* Hit `f` to go to preview
* Hit right arrow to go to next photo (or any other photo)
* Hit `f` again to exit preview

Behavior: The photo you viewed last should be selected, but because the mouse cursor is still at the first photo, you see the expected selected photo highlighted briefly, then selection returns to the first photo.

This behavior also happens when mouse cursor is on an image in lighttable, and you scroll the lighttable using a cursor keys.

### Expected behavior

If you select the first photo, then move the cursor out of the way (e.g. to window decorations), the selection does not change unexpectedly upon preview exit. I think this is expected behavior.

### Where did you install darktable from?

distro packaging

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 23.04

### Describe your system?

Lenovo Thinkpad X1 Carbon

### Are you using OpenCL GPU in darktable?

None

**Comment by elstoc** [comment]
I agree that selection-on-mouse-hover is not normal but it is the way darktable is designed to work and there are people who prefer it that way

**Comment by pozix604** [comment]
The "flashing" selection makes it look like unintended behavior. Especially when scrolling the lighttable with cursor keys. If you're not paying attention to where your mouse cursor is, it just looks like it's randomly selecting an image (which I thought was what it was doing at first).

I'm not sure what exactly is the behavior that people prefer. Is it that they can select the image under the cursor easily? Or that peope just keep tracking of their mouse cursor position very well (better than me) so they know which image should be selected? 

Could a better user experience be that the selection is at the last image, until the mouse cursor is moved?

**Comment by ralfbrown** [comment]
See #6025.  The hovering behavior has been around, and a source of disagreement, for a long time.

**Comment by jenshannoschwalm** [comment]
My feelings about "Image to act on" while just moving the mouse are a mixed bag too. Generally i like it the way we have as being very fast an easy-to-go way, so a pro vote.

Maybe we can find a way to have this working only after some mouse movement to get out of the way if some selection is done otherwise?

**Comment by ralfbrown** [comment]
Please post any further discussion in #16850.
