### ISSUE TITLE
Central panel shakes 

### ISSUE THREAD

**Issue by ctouz** [darktable-org/darktable#14845]
### Describe the bug

random/irregular bug
The central panel shakes and filmstrip is empty.
on restarting darktable the filmstrip in darkroom is empty.i have to change "plugins/darkroom/0/filmstrip_visible=FALSE" to TRUE in darktablerc to restore it.
seen with plasma and cinnamon
see attached video

### Steps to reproduce

1 can be 
process an image in the darkroom and then go to the lighttable

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/28384260/c94f7e78-0b9e-4f84-b37d-53af1c6362b2

[log.txt](https://github.com/darktable-org/darktable/files/11961536/log.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro linux

### Describe your system?

Manjaro linux
16 g ram
Cpu i7-7700

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

gtx3050

**Comment by gi-man** [comment]
Around 2 weeks ago I had the same issue with the filmstrip. I tried multiple combinations of keyboard and mouse clicks to restore it, but I was not able to. Editing the darktablerc restore it. I discussed it with a few folks in the darktable matrix/irc. I don't know what caused it and did not notice the shaking you mentioned. It was only once for me. Can you recreate? 

I was on fedora 37 kde X11 at the time on master from OBS. I am now in a clean install of fedora 38 ide X11 and self build master.

**Comment by ctouz** [comment]
I was able to reproduce today:
switching from darkroom to lighttable
shaking central screen
empty filmstrip
8 threads at 25% cpu
started Dt with darktable -d all > log.txt
I'm attaching the log file if it helps


[log.txt](https://github.com/darktable-org/darktable/files/11972178/log.txt)

**Comment by jenshannoschwalm** [comment]
This can happen if there are "size ratio conflicts" between thumb size, lighttable canvas size...
Has been reported several times iirc and we had some tries for a complete fix ...

If it happens just resize the dt main window or the left or right module area...

**Comment by ctouz** [comment]
I've created a new /.config/darktable folder and haven't reproduced it yet
