### ISSUE TITLE
Best alternative to contrast brightness saturation deprecated module

### ISSUE THREAD

**Issue by MauDarktable** [darktable-org/darktable#14841]
### Describe the bug

Dear all, after upgrade to 4.4.1 ver. I see that "contrast brightness saturation" module is deprecated.
I'm so sad for this because usually I use this module for simple adjustments on my pictures. This module is simple and fast...
I saw that in the suggested "Color Balance RGB" module I can change saturation and contrast but I'm unable to find the best alternative to the brightness cursor to adjust picture grightness globally. Can you please suggest the best alternative? Many thanks!

### Steps to reproduce

Please act on mentioned modules

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

None

**Comment by elstoc** [comment]
use "perceptual brilliance grading" or just increase the exposure in the "exposure" module

**Comment by MauDarktable** [comment]
> perceptual brilliance grading

Thank you!
