### ISSUE TITLE
macOS: menu boxes doesn't fit if using external display

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#14856]
### Describe the bug

when using an external display (resolution 2560x1440) the menu boxes is too small to show all entries

![image](https://github.com/darktable-org/darktable/assets/39386816/99eab4c2-7162-4877-8693-6db1241b5ea5)

system constellation: macbookpro with retina display using standard scaling (1728x1117) and external display 2560x1440

just reproducible on external screen; notebook display is fine

doesn't affect the dialogs for bottom right icon: 
![image](https://github.com/darktable-org/darktable/assets/39386816/407d8b6f-9f32-429e-82aa-c5d982467cab)

### Steps to reproduce

move darktable to external screen and open an hamburger menu

### darktable version

darktable 4.4.1+4~g833a4e4816-dirty

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Ventura 13.4.1

### Describe your system?

M1 max

### Are you using OpenCL GPU in darktable?

Yes

**Comment by MStraeten** [comment]
same behaviour as https://github.com/darktable-org/darktable/issues/14278
seems the issue survived some gtk updates …

**Comment by MStraeten** [comment]
a build using gtk3 3.24.38 doesn't show this behaviour - but has redrawing issues. Since the latter is just annoying and can be handled by additional scaling attempts (if it occurs) using gtk3 3.24.38 seems to be the better solution.
so here a 4.4.2 arm release build with gtk3 3.24.38
[darktable-4.4.2_arm64_gtk3.24.38.dmg](https://mega.nz/file/bOwnEaRK#VXAk3zXgcOjI2YOTNeppgMwddH9P5i5twjiXbz1gPqM)

so i close here ...

**Comment by Campano** [comment]
Hello! Following up on #10876, thank you, I will try the fixed build. Just out of curiosity, why isn't the 4.4.2 release for M1 built with gtk 3.24.38?

**Comment by MStraeten** [comment]
quite simple - due to the refresh issue https://github.com/darktable-org/darktable/issues/14579 ;) i didn't upgrade the release build enviroment with gtk3 3.24.38 for 4.4.2.
There aren't enough macOS users testing alternative solutions - so finding those takes time; especially if issues just occurs on macOS (unfortunately quite often with gtk stuff - the reported issue isn't touched since may there ... ;) )  
That alternative solution was found later - and so for the next release there is to prioritize: accept the refresh issue or the dual display issue. Since the refresh issue is just annoying - the prioritization will be quite simple - at least if i'm going to build the arm64 release then it will be on gtk3.24.38 regardless they fix it or not.

**Comment by Campano** [comment]
Feel free to register me as an OS X tester if you need help. Thanks for all the great work.

**Comment by MStraeten** [comment]
you'll find current master builds at: https://discuss.pixls.us/t/current-osx-build/13213/706
