### ISSUE TITLE
Fujifilm X-S20 camera support

### ISSUE THREAD

**Issue by frischnetz** [darktable-org/darktable#14858]
### Describe the bug

.RAF files from the new FUJIFILM X-S20 do not open in DT, because the camera is not recognized and DT complains that it cannot read the white balance data.

But the camera has the identical sensor as the predecessor, the X-S10 and the files can be processed the same way as this camera.

In fact, when I change the model name to X-S10 in the exif metadata, the file is opened and processed without error.
(I tried only lossless compressed RAF-files)

So until samples are provided for raw.pixls.us, I'd suggest to use the same processing as X-S10 as a workaround.

Checked version 4.4.0 (fedora rpm and flatpak) and 4.4.1 (flatpak)

### Steps to reproduce

Open a X-S20 .RAF-File (lossless compressed) in the darkroom. You get an error message and you will be redirected to the lightroom. 

### Expected behavior

darktable should process it exactly like a file from X-S10

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RTX 3060, 12GB, 535.54.03

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

log excerpt:

RawSpeed:Unable to find camera in database: 'FUJIFILM' 'X-S20' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
    19,6297 [rawspeed] (DSCF1870.RAF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'FUJIFILM' 'X-S20', mode '' not supported, and not allowed to guess. Sorry.
…
    20,0370 [temperature] `FUJIFILM X-S20' color matrix not found for image
    20,0370 [temperature] failed to read camera white balance information from `DSCF1870.RAF'!
    20,0372 [temperature] failed to read camera white balance information from `DSCF1870.RAF'!
    20,0373 [dt_iop_reload_defaults] defaults reloaded for temperature
    20,0396 [dt_iop_reload_defaults] defaults reloaded for invert
    20,0413 [dt_iop_reload_defaults] defaults reloaded for rawprepare
    20,0590 [colorin] could not find requested profile `standard color matrix'!
    32,1551 Session fullpipe cache report. hits/run=0,00, hits/test=0,000

**Comment by kmilos** [comment]
Please submit samples to https://raw.pixls.us/ as requested, as this is a new camera.

**Comment by frischnetz** [comment]
I have submitted samples.

Until they are processed and support is included in DT, I still suggest to treat X-S20-files as identical to X-S10-files.

As a private workaround I will batch-change the exif model name to X-S10 to process the files - which is not ideal.

**Comment by kmilos** [comment]
Thanks for the samples. Should be fixed by https://github.com/darktable-org/rawspeed/pull/479.

Please test it (specially the crop) and provide feedback there.

**Comment by kmilos** [comment]
> As a private workaround I will batch-change the exif model name

Please don't mess w/ your raw files. Changing the camares.xml is much less risky. ;)

**Comment by LebedevRI** [comment]
@frischnetz thank you for contributing the samples!

**Comment by frischnetz** [comment]
> > As a private workaround I will batch-change the exif model name
> 
> Please don't mess w/ your raw files. Changing the cameras.xml is much less risky. wink

Thanks, this was exactly the quick workaround that I was kinda looking for with my post! Copied the entries over from X-S10, works like a charm!

**Comment by kmilos** [comment]
> Copied the entries over from X-S10

It would be great if you can help test the linked PR instead of copying actually, thanks.

**Comment by frischnetz** [comment]
OK, now used the complete new cameras.xml from the linked PR with X-S20 files. The results look perfectly fine for me. Crop looks fine, too.

**Comment by paeony** [comment]
I believe the fix for this was committed to the 4.4.2 release, which I'm running on Mint. But when I try to bring a RAF file into darkroom I still get the please check the camera model error. Any suggestions? Thanks!

**Comment by LebedevRI** [comment]
I would guess you are trying to load lossless compressed `.RAF`'s, which are (still) unsupported.

**Comment by kmilos** [comment]
> you are trying to load lossless compressed `.RAF`'s

That would be lossy in Fujifilm case, lossless and uncompressed should be supported.

**Comment by kmilos** [comment]
@paeony This is not in DT 4.4.2, only in master branch. You can add support to 4.4.2 just by editing the cameras.xml as in the linked PR.

**Comment by paeony** [comment]
@kmilos I apologize for my mistake. Thanks for the clarification! However I did the following:
1. Open /var/lib/flatpak/app/org.darktable.Darktable/current/GUID/files/share/darktable/rawspeed/cameras.xml
2. Replace the content of that file with the content from https://raw.githubusercontent.com/darktable-org/rawspeed/169be18fb9cee5d06170dfe15f657be2592f5998/data/cameras.xml

Expected Result: Could edit X-S20 raw files

Actual Result: For both uncompressed and lossless uncompressed if I click on a RAF file I don't get the error anymore, but the "image" just seems to consist of nothing but black pixels. The EXIF data looks correct in image information but the exposure histogram is empty. Just for fun I exported it to JPEG and also only get black pixels.

Note that other file formats like JPEG, HEIC and DNG all continue to work as normal. It's just the RAF files from the X-S20 that have issues.

Can you please help me understand what mistake I made? Thanks!

**Comment by kmilos** [comment]
You need to first remove the old, failed imports from the database, and import them fresh again.

**Comment by paeony** [comment]
@kmilos - Thank you! I ended up doing two things to make it work. First, remove the film rolls. But second, manually delete all the side car files. But now it works! Again, thank you!
