### ISSUE TITLE
1px strip of wrong pixels on cropped photos after export

### ISSUE THREAD

**Issue by edison23** [darktable-org/darktable#14854]
### Describe the bug

When I crop my images and disable scaling on export (the only two conditions I was able to pinpoint), I get seemingly randomly shifted (just a guess) 1px-wide vertical strip on the right side of the image and black strip on the bottom side.

I doesn't happen with images I didn't crop, I also have in the batch one image which I cropped and still doesn't have the strip. Doesn't happen when the image is scaled on export, can be as little as 0.99 factor scaling. (But that's not a valid workaround because it blurs the image a little, obviously.)

The issue happens for both cameras I own (Canon 70D and Asus Zenfone 8, the former produces CR2, latter shoots to DNG)

I haven't been able to pinpoint any more conditions under which it happens (odd/even result dimensions or something). 

### Steps to reproduce

1. Crop a photo
2. Set export module to export without scaling (scale factor 1 or empty)
3. Export (format doesn't matter, tried JPG, WebP, TIFF)
4. The result contains the strips on right and botom sides

### Expected behavior

No artifacts in exported images

### Logfile | Screenshot | Screencast

https://edison23.net/_public/dt_log.txt

![image](https://github.com/darktable-org/darktable/assets/1723800/fdad6691-a48d-4dea-a5d8-f05ed88d2a39)

### Where did you install darktable from?

distro packaging

### darktable version

4.2.0~git4.64041571-1+77.1

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 22.04

### Describe your system?

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-46-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 7700X 8-Core Processor
Memory: 30,5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 3070 Ti, driver 525.125.06

**Comment by jenshannoschwalm** [comment]
Hi @edison23 , welcome here at the github issue tracker. Two things to say from my side:

1. Fortunately this issue has been fixed in darktable 4.4
2. Unfortunately you are still running 4.2, you'll have to wait for your distribution to update or find another way to use 4.4. Look here for open/closed issues or at the popular forum https://pixls.us/ for help to do so.

Closing this for now as solved, feel free to re-open if you find issues with 4.4, we would love to fix :-)
