### ISSUE TITLE
Filtering by date/time does not work (value always set to 1:01:01 00:21:46)

### ISSUE THREAD

**Issue by zaha** [darktable-org/darktable#14853]
### Describe the bug

I am unable to filter by date/time by either date picker or by entering a date and/or time, it's always setting the value to 1:01:01 00:21:46. The only way to filter by date is by using the timeline with the mouse, but I'm unable to enter any different values then.
Also I can't click on any day in the date picker, but maybe that's because the year always jumps to 0001?

### Steps to reproduce

1. Add a collection filter for capture time (or any other time-based rule)
2. Enter a date (e.g. 2023:01:01) and press enter
3. The set date is either "1:01:01 00:21:46" or it keeps the previous value (min/max)

### Expected behavior

Accept and display the entered date and time.

### Logfile | Screenshot | Screencast

![2023-07-06_darktable_KjgvpKu6SV](https://github.com/darktable-org/darktable/assets/1721211/eaa9ee00-a5e0-4d58-8f10-67529c6ec045)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Windows

### What is the version of your OS?

Win11 22H2 (22621.1848)

### Describe your system?

Also tried it on my Windows 10 machine, same issue occurs there.

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This looks similar to the following issue: #11582
Is this maybe a regression?

**Comment by pehar1** [comment]
4.5.0+18~ga568fa879d on Ubuntu 22.04
No part of the problem you describe is reproducible for me. Does the problem persist when you start darktable with an empty configuration, that is specifically without `darktablerc` ?

**Comment by zaha** [comment]
I renamed my current `darktablerc`, started the software and tried again: same issue happens.

As mentioned, I think this is related to #11582, which was a platform-specific bug on Windows.

**Comment by jan-glx** [comment]
I have the same issue. I think, I did not have it some weeks ago. I updated from 4.0.1 to 4.4.1 because of this issue, but it persist. I am on: 

> Edition	Windows 11 Pro
> Version	22H2
> Installed on	‎2023-‎03-‎11
> OS build	22621.1848
> Experience	Windows Feature Experience Pack 1000.22642.1000.0

**Comment by WolfBearGames** [comment]
The bug still exists and is very annoying...

**Comment by victoryforce** [comment]
@AlicVB sounds like this is for you. Do you have time to try to find a bug?

**Comment by AlicVB** [comment]
I can't reproduce...
if effectively it's the same bug as #11582 that would mean we have some wrong casting (long ??) somewhere in the date_range implementation...
range widget is a generic one which use double for the value. I assume that *even* in windows, int64 -> double is safe, right ?

I'll read the code once again to see if I spot something spurious...

**Comment by AlicVB** [comment]
I've spotted 2 places where we use long instead of int64...
If someone (that can reproduce the issue) can compile PR #15736 and confirm that it's fixing the issue that would be great !

**Comment by victoryforce** [comment]
@AlicVB  I confirm, the issue is fixed! Thanks!
