### ISSUE TITLE
Create New Style stuck

### ISSUE THREAD

**Issue by redteamcafe** [darktable-org/darktable#14864]
### Describe the bug

When I am in the Lighttable menu, selecting the option "create a new style" will bring up the style window, but whenever I create a new style, and click 'save' a new window appears. If I click 'select none' it reappears, same if I click the X button or 'cancel'. This window will not go away, it keeps just reappearing over and over and over again. 

### Steps to reproduce

Open Darktable
Go to the Lighttable menu
On the right, under 'Styles' select 'create'
Once the window pops up, either enter a name in the 'name' prompt and click 'save', or click X or 'cancel'.

### Expected behavior

the window should close

### Logfile | Screenshot | Screencast

There are no logs associated with this action

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora Design Suite 38

### Describe your system?

Dell XPS 15 9520

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
@redteamcafe: I can't reproduce too (on Debian Sid). Could you reproduce your issue with darktable 4.4.1 (or better with 4.4.2 released 2 days ago). And if you reproduce, could you remove (save it before) darktablerc file on your config folder? Do that with darktable close, then after removing it, launch darktable and test again.
