### ISSUE TITLE
[Windows][imageio] GraphicsMagick doesn't work in Windows darktable builds

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#14871]
darktable (latest release 4.4.1 and current master) installed on Windows cannot load formats handled by the GraphicsMagick loader. darktable at least 4.0.1 also has this issue, so it looks like a long-standing problem with the GraphicsMagick packaging (especially considering that the issue does not occur in a Linux build).

The following line appears in the log:

```
Magick: Unable to access configuration file (delegates.mgk) [No such file or directory].
```
after which attempts to read files lead to errors like:
```
Magick: No decode delegate for this image format (D:\Image format samples\bmp\greenland_grid_velo.bmp).
   177,0007 [GraphicsMagick_open] image `greenland_grid_velo.bmp' not found
```
darktable installed in MINGW (via `--build --target install`) also cannot read files via GraphicsMagick. But for some reason, this issue does not occur if we run darktable from the build tree!

**Comment by kmilos** [comment]
Didn't we go through this around the 4.2 release already? AFAIR it was working. I'll try to find references...

**Comment by kmilos** [comment]
Here's the confirmation IM was working for 4.2: https://github.com/darktable-org/darktable/pull/13203#issuecomment-1365788769

I'm think GM was working as well, I remember being able to load some .pam images....

**Comment by kmilos** [comment]
Ok, able to reproduce. Looks like we need to install all the `.la` files as well with the DLLs, just like in the IM case...

**Comment by victoryforce** [comment]
> I'm think GM was working as well, I remember being able to load some .pam images....

Maybe you remember being able to load .pam files because you were running from the build tree?

I recently checked on older releases up to 4.0.1, loading with GM didn't work. I didn't notice the problem before because I almost never ran installed versions of dt on Windows, and there are no problems when starting from the build tree (BTW, I still can't understand why).

There are no errors in the dt_imageio_open_gm loader code. This is a problem with the packaging of GM itself. Therefore, __IF__ everything worked once in the past, then either the delegate search code or the packaging or build of GM itself could have changed (for example, maybe the coders were not separated from the main DLL?). This is just a guess, I'm just thinking out loud, I haven't checked.

But it is possible that loading exotic formats never worked under Windows. The developers may not have noticed this, because they only tested in the build tree (if anyone tested this specifically under Windows!), and there were no bug reports from users, because only the most exotic formats remained for the GM loader, and the combination of these formats with the Windows platform had very few users.

**Comment by kmilos** [comment]
> Maybe you remember being able to load .pam files because you were running from the build tree?

Quite possible...

In any case, looks like those .la files are needed for dynamic loading of both GM and IM coder plugins...
