### ISSUE TITLE
Darktable 4.4.1 Nvidia OpenCL don't work

### ISSUE THREAD

**Issue by EmJotGeh** [darktable-org/darktable#14875]
### Describe the bug

Darktable does not run with OpenCL for some time now.

Running on Arch Linux:
- 6.4.3-arch1-1
- nvidia 535.54.03-8
- opencl-nvidia 535.54.03-1
- Xorg - X11
- darktable 4.4.1-1

```
darktable --version
this is darktable 4.4.1
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```
Currently I can only start Darktable with ```darktable --disable-opencl```.

I would be very grateful for any hints

### Steps to reproduce

n.a.

### Expected behavior

Start with openCL Support?

### Logfile | Screenshot | Screencast

No Log available

### Where did you install darktable from?

distro packaging

### darktable version

6.4.3-arch1-1

### What OS are you using?

Linux

### What is the version of your OS?

Arch

### Describe your system?

X11

### Are you using OpenCL GPU in darktable?

Yes

**Comment by jenshannoschwalm** [comment]
VERY minimal information so far. Please provide at least a log with `-d opencl` and output of `clinfo`

**Comment by EmJotGeh** [comment]
```
darktable -d opencl
     0,2214 [dt_get_sysresource_level] switched to 1 as `default'
     0,2214   total mem:       15993MB
     0,2214   mipmap cache:    1999MB
     0,2214   available mem:   7996MB
     0,2214   singlebuff:      124MB
     0,2214   OpenCL tune mem: OFF
     0,2214   OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'very fast GPU'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
^C
```
There are no informations available - I have to stop then... 
```
clinfo -a
^C

```
```
clinfo -v

clinfo version 3.0.21.02.21
```

**Comment by jenshannoschwalm** [comment]
If clinfo does not show your devices the OpenCL installation is just wrong. Likely you have only installed the Open**GL** stuff but are missing opencl. 

Your dt log doesn#t even show the platforms.

**Comment by EmJotGeh** [comment]
Darktable is working well for years - but since a few weeks just not. I think, everything what's needed is still installed.

```
pacman -Qi nvidia
Name                     : nvidia
Version                  : 535.54.03-8
Beschreibung             : NVIDIA drivers for linux
Architektur              : x86_64
URL                      : https://www.nvidia.com/
Lizenzen                 : custom
Gruppen                  : Nichts
Stellt bereit            : NVIDIA-MODULE
Hängt ab von             : linux  nvidia-utils=535.54.03  libglvnd
Optionale Abhängigkeiten : Nichts
Benötigt von             : Nichts
Optional für             : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : Nichts
Installationsgröße       : 43,55 MiB
Packer                   : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Erstellt am              : Di 11 Jul 2023 07:53:10 CEST
Installiert am           : Mi 12 Jul 2023 06:15:34 CEST
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Signatur
```

```
pacman -Qi opencl-nvidia
Name                     : opencl-nvidia
Version                  : 535.54.03-1
Beschreibung             : OpenCL implemention for NVIDIA
Architektur              : x86_64
URL                      : http://www.nvidia.com/
Lizenzen                 : custom
Gruppen                  : Nichts
Stellt bereit            : opencl-driver
Hängt ab von             : zlib
Optionale Abhängigkeiten : opencl-headers: headers necessary for OpenCL development [Installiert]
Benötigt von             : cuda  davinci-resolve  hcxkeys
Optional für             : nvidia-utils  ocl-icd
In Konflikt mit          : Nichts
Ersetzt                  : Nichts
Installationsgröße       : 22,84 MiB
Packer                   : Sven-Hendrik Haase <svenstaro@archlinux.org>
Erstellt am              : Mi 14 Jun 2023 16:56:31 CEST
Installiert am           : Do 15 Jun 2023 18:30:28 CEST
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Signatur
```

I would like to add that this problem has existed for a few weeks.

**Comment by jenshannoschwalm** [comment]
I see your frustration but if clinfo doesn't show drivers and device info there is something wrong. Don't knao anything about arch BTW.

You'll find help on pixels.us probably. There are user on that distro with Nvidia...

**Comment by Nilvus** [comment]
clinfo is outside darktable scope. If clinfo, as OpenCL info software on your system, doesn't show infos, that means it's your OpenCL system that have issue, not darktable. If your system do not have OpenCL correctly activated, darktable will not detect it. 

I let you go on pixls.us forum (it's actually down, a move on another server actually). So you will have to wait or find help on another forum, related to your distrib for example, to find why OpenCL is not correctly activated on your system.

As this place is for darktable issues, I so close.

**Comment by jenshannoschwalm** [comment]
@EmJotGeh i am interested in your log with `-d opencl -d verbose` as commandline options. Please clear your `.cache/darktable/cached_kernels` before doing so!

**Comment by EmJotGeh** [comment]
Hello @jenshannoschwalm 

i cleared the .cache Folder and try to start darktable with the given options - but with the same result. 
![Darktable_OpenCL](https://github.com/darktable-org/darktable/assets/16000642/89a1f122-9c99-41c0-bcc7-6c2b9979fc4f)

after that command nothing happend?!

However, I now have the suspicion that this problem is related to the opencl support (opencl-nvidia) because davinci, for example, is not starting at the moment either. And I already mentioned that clinfo doesn't output any output either.

**Comment by jenshannoschwalm** [comment]
1. For sure the installation of the cl driver is not complete.
2. Nevertheless we might try better to have darktable not "hanging dead".

**Comment by jenshannoschwalm** [comment]
1. If possible, could you compile dt yourself and check with above PR? Otherwise look for cuda stuff in your distribution packages.

Re-opening this to keep track of "darktable hanging due to incomplete cl driver installation"

**Comment by EmJotGeh** [comment]
Updating the following programs under Arch Linux finally solved the problem.

openblas blas lapack cblas lapacke -> from 3.08 to 3.11

Darktable starts again with opencl support as usual and an output of clinfo was now also possible again.
