### ISSUE TITLE
Crop with retouch not working correctly in darkroom view

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#14888]
Due to the position of crop and retouch in the pipe it should be possible to use cropped areas of the image as source spots for retouching. In this somewhat contrived example, I observe the following (see video below)

1. Reset the history for a clean image
2. Use the retouch module to clone a feature from the top of the image into a lower part of the image
3. Crop out the source feature
4. Retouch no longer works as expected (feature no longer present in lower part of the image)
5. Exit to the lighttable view
6. Retouch is applied correctly in the thumbnail (cloned feature is present)
7. Go back into the darkroom view
8. Retouch is again applied incorrectly (cloned feature not present)

I have tried exporting and the retouch module is again applied as expected, so this appears to be an issue in the darkroom view only.

See the following illustrative video:

https://github.com/darktable-org/darktable/assets/9555491/4d99c261-e007-4223-88d7-fe0985743e0b

I have observed the same issue in both master and the 4.4.1 stable release

**Comment by ralfbrown** [comment]
Confirmed.  Expanding the crop to include the source region and then reducing it again often restores the cloned target region in darkroom view, so it looks like an interaction of RoI and pixpipe cache.  Maybe the retouch module has a bug in `modify_roi_in`?

**Comment by jenshannoschwalm** [comment]
You can check pipe-cache problems with `--disable-pipecache`

**Comment by elstoc** [comment]
Seems ok when I run with `--disable-pipecache`

**Comment by jenshannoschwalm** [comment]
Do you have highlights opposed active? That would expand to full roi so likely rules out a roi problem in retouch.
With '-d pipe' you will see the used rois plus processed modules.
BTW, I couldn't reproduce here yet.

**Comment by elstoc** [comment]
> Do you have highlights opposed active?

Yes I reset history at the start so everything should be at default values

**Comment by elstoc** [comment]
Interestingly since I ran with `--disable-pipecache` I no longer reproduce. Is it possible something about that setting sticks around between sessions?

**Comment by jenshannoschwalm** [comment]
Nope

**Comment by elstoc** [comment]
I did find, when I noticed this originally, that with some messing around with modules / darktable restarts etc. the issue went away. I never worked out any consistent way to do this though

**Comment by elstoc** [comment]
Another reproducer, again with crop and retouch enabled -- if I try to move around the target shape in the retouch module the clone occasionally disappears:


https://github.com/darktable-org/darktable/assets/9555491/6e586bd2-a296-4901-ab4c-4138c968289d

**Comment by jenshannoschwalm** [comment]
I don't know this module well. Can you confirm by log that the issue is related to taking data from cache?

**Comment by elstoc** [comment]
I ran darktable with `-d all` and then tried to reproduce the issue. I quit darktable as soon as I reproduced it. Hope the log helps...

[darktable.log](https://github.com/darktable-org/darktable/files/12063896/darktable.log)

**Comment by jenshannoschwalm** [comment]
It does :-) Although - `-d all` is simply too much/verbose, `-d pipe` is good enough in cases we suspect pipeline processing issues or `-d common` most notably leaving all the clmemory and performance data.
But:
```


This seems to be right:
L6632
    10.3348 [pixelpipe starting CL]      [full]                                (   0/   0) 1889x 926 scale=0.3138 --> (   0/   0) 1889x 926 scale=0.3138 
    10.3348 [modify roi IN]              [full]         crop                   (   0/ 335) 1889x 926 scale=0.3138 --> (   0/   0) 1889x 926 scale=0.3138 
L6661
Hanno: retouch expands it's input
    10.3377 [modify roi IN]              [full]         retouch                (   0/  67) 1889x1194 scale=0.3138 --> (   0/ 335) 1889x 926 scale=0.3138 
    10.3377 [cache HIT]                  [full]         demosaic                IOP_CS_RGB, hash  12235885223163874676
    10.3377 [pixelpipe data: from cache] [full]         demosaic               (   0/  67) 1889x1194 scale=0.3138 --> (   0/  67) 1889x1194 scale=0.3138 
    10.3377 [opencl memory] device 0: 36087456 bytes (34.4 MB) in use
    10.3423 [opencl memory] device 0: 64074880 bytes (61.1 MB) in use
    10.3426 [pixelpipe_process_CL]       [full]         retouch                (   0/  67) 1889x1194 scale=0.3138 --> (   0/ 335) 1889x 926 scale=0.3138 IOP_CS_RGB

Hanno: here we process retouch and have larger area for input than for output
L6623
   10.3739 [pixelpipe_process_CL]       [full]         retouch                (   0/  67) 1889x1194 scale=0.3138 --> (   0/ 335) 1889x 926 scale=0.3138 cl input data to host
    10.3739 [opencl memory] device 0: 27987424 bytes (26.7 MB) in use
    10.3740 [dev_pixelpipe] took 0.036 secs (0.127 CPU) [full] processed `retouch' on GPU, blended on GPU
    10.3740 [importance hints]           [full]         retouch                (   0/  67) 1889x1194 scale=0.3138 --> (   0/ 335) 1889x 926 scale=0.3138 focus cldata


Issue run:
L7229
    11.8087 [pixelpipe starting CL]      [full]                                (   0/   0) 1889x 926 scale=0.3138 --> (   0/   0) 1889x 926 scale=0.3138 
    11.8087 [modify roi IN]              [full]         crop                   (   0/ 335) 1889x 926 scale=0.3138 --> (   0/   0) 1889x 926 scale=0.3138 
    11.8087 [modify roi IN]              [full]         demosaic               (   0/1066) 6020x2951 scale=1.0000 --> (   0/ 335) 1889x 926 scale=0.3138 
    11.8087 [modify roi IN]              [full]         highlights             (   0/   0) 6020x4024 scale=1.0000 --> (   0/1066) 6020x2951 scale=1.0000 
    11.8087 [modify roi IN]              [full]         rawprepare             (   0/   0) 6048x4024 scale=1.0000 --> (   0/   0) 6020x4024 scale=1.0000 
    11.8087 [pixelpipe data: full]       [full]                                (   0/   0) 6048x4024 scale=1.0000 --> (   0/   0) 6048x4024 scale=1.0000 
Hanno: note there is no roi_in modify notice; this means it has not changed!

L7291
    12.1286 [pixelpipe_process_CL]       [full]         demosaic               (   0/1066) 6020x2951 scale=1.0000 --> (   0/ 335) 1889x 926 scale=0.3138 IOP_CS_RAW -> IOP_CS_RGB
L7334
    12.2033 [pixelpipe_process_CL]       [full]         retouch                (   0/ 335) 1889x 926 scale=0.3138 --> (   0/ 335) 1889x 926 scale=0.3138 IOP_CS_RGB
Hanno: note the run does not include expanded roi_in data!
```

**Comment by elstoc** [comment]
>  `-d all` is simply too much/verbose

I did try to look through the options but I couldn't work out which would be best so I went with all

**Comment by jenshannoschwalm** [comment]
Ok watched the video and can reproduce here. And i can confirm here, that the roi_in is not changed in these cases.
1. modify roi_in code wrong ? 
2. commit_params is wrong ?
3. Could also trigger the issue with pipecache disabled

**Comment by gi-man** [comment]
It took some effort but I was also able to reproduce. It is easier to reproduce with opencl off (via parameters). Compressing the history stack fixes it.

I dont use the retouch module that often, but I noticed something I was not expecting. I had the crop module on with some crop. When I turned on the Retouch module, I would think we should show the entire image and not just the cropped area. Why? So we can sample from the cropped out areas. The rotate and perspective does show the entire image when activated. Not part of this issue, but an observation.

**Comment by elstoc** [comment]
> we should show the entire image and not just the cropped area

I've already raised https://github.com/darktable-org/darktable/issues/10689 to cover this.

**Comment by jenshannoschwalm** [comment]
More thoughts, it seems the algo is either doing everything just right or it **completely** fails. It's not some wrong roi correction, there seems to be none at all.

Is this a race condition (via a signal?) having no shape-source data at all?

**Comment by TurboGit** [comment]
I have moved this to 4.6 as 4.4.2 is planed very soon.

**Comment by jenshannoschwalm** [comment]
I guess you checked the code while formatting and also couldn't find anything obvious.

**Comment by TurboGit** [comment]
> I guess you checked the code while formatting and also couldn't find anything obvious.

Nothing obvious indeed.

**Comment by TurboGit** [comment]
@elstoc 
> Interestingly since I ran with `--disable-pipecache` I no longer reproduce.

Can you double check as with this option I can still reproduce. TIA.

**Comment by TurboGit** [comment]
@jenshannoschwalm : As you reported in your `-d pipe` analyze, we have a `[modify roi IN]` for **preview** pipe but not for the **full** run where the issue is seen. So to me it looks like a pipe issue more than a retouch module one.

**Comment by jenshannoschwalm** [comment]
That would not explain why the log does not show any roi_in change at all. These messages are shown if there is any change of roi structure data while calling the modify function.

**Comment by jenshannoschwalm** [comment]
Messages crossed. Yes I agree here.

**Comment by jenshannoschwalm** [comment]
We might have look through sinallling code.

**Comment by jenshannoschwalm** [comment]
Could it be, we don't have the form data avaible at that point? Like some temporary removal while repositionig?

**Comment by TurboGit** [comment]
> Could it be, we don't have the form data avaible at that point? Like some temporary removal while repositionig?

Could be, yes.

**Comment by TurboGit** [comment]
Not sure it is the best way, but this seems to fix the issue on my side:

```
diff --git a/src/iop/retouch.c b/src/iop/retouch.c
index 0fe1ffed21..709fc46532 100644
--- a/src/iop/retouch.c
+++ b/src/iop/retouch.c
@@ -788,6 +788,8 @@ static void rt_resynch_params(struct dt_iop_module_t *self)
   {
     p->rt_forms[i] = forms_d[i];
   }
+
+  dt_control_queue_redraw_center();
 }
```

Can you double check? TIA.

**Comment by TurboGit** [comment]
BTW, maybe this patch could be in 4.4.2 (planned in coming Wed) as a workaround waiting for a proper fix.

**Comment by elstoc** [comment]
> Can you double check as with this option I can still reproduce. TIA.

I've retried quite a few times both with and without `--disable-pipecache`. Although it's somewhat intermittent, I have yet to reproduce it with, and can always eventually reproduce it without.

**Comment by elstoc** [comment]
> Can you double check? TIA.

I can still reproduce the issue after applying this patch. Sometimes it takes longer to reproduce than others, and that unpredictability can often give a false-positive.

**Comment by jenshannoschwalm** [comment]
> BTW, maybe this patch could be in 4.4.2 (planned in coming Wed) as a workaround waiting for a proper fix.

I couldn't trigger a false positive yet but could see the issue at least once.

BTW - there is an issue remaining as mentioned in https://github.com/darktable-org/rawspeed/pull/479#issuecomment-1638932405 - give me a day to check that.

**Comment by TurboGit** [comment]
The issue was already present in dt 4.2. It seems to be due to a wrong blend params sync. The issue is because when trying to compute the roi in `retouch.c` the `bp->mask_id` line 2803 is 0. Adding the stupid following lines fixes the issue for me:

```
diff --git a/src/iop/retouch.c b/src/iop/retouch.c
index d1cd5c827e..d6a83f2fa4 100644
--- a/src/iop/retouch.c
+++ b/src/iop/retouch.c
@@ -2805,6 +2805,9 @@ static void rt_compute_roi_in(struct dt_iop_module_t *self,
 
   // We iterate through all forms
+  while(bp->mask_id == 0)
+    g_usleep(10);
+
```

And now I'm wondering if this is not why there the loop:

  while(roir != roir_prev
        || roib != roib_prev
        || roix != roix_prev
        || roiy != roiy_prev)
...

in `modify_roi_in` to cope with the same issue for the clone.

**Comment by jenshannoschwalm** [comment]
So there is some wrong mask_id creeping in? The loop - hinting to a race condition?

**Comment by TurboGit** [comment]
Yes, most probably a race condition. I'm still not sure where this `mask_id` is set.... Any idea? If we can find this, then we can probably fix by adding some proper lock.

**Comment by elstoc** [comment]
LTGM
