### ISSUE TITLE
The darktable.org site is down

### ISSUE THREAD

**Issue by 22h49** [darktable-org/darktable#14884]
### Describe the bug

I'm not quite sure if this is the right place for this problem, excuse me if it isn't and I'll close the issue right away, but both the forums and the contribution guidelines are not accessible so I'm not aware of a better place to post this.

The [site](http://darktable.org) is not responding.

### Steps to reproduce

Go to [http://darktable.org](http://darktable.org), or try to open a connection on port 80 with 135.181.1.149

### Expected behavior

The server should respond instead of dropping the connection

### Logfile | Screenshot | Screencast

```
❯ nc -vv darktable.org 80
nc: connect to darktable.org port 80 (tcp) failed: Connection refused
```

### Where did you install darktable from?

darktable.org

### darktable version

N/A

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

Firefox, internet access from the `Europe/Warsaw` region, but the issue does not seem to be on my end since the reports are corroborated and `135.181.1.149` responds to ICMP.

### Are you using OpenCL GPU in darktable?

No

**Comment by ptilopteri** [comment]
please close this issue.
the site suffered a hardware failure and is being rebuilt.
and is not maintained by the dt developers.
searching for the issue would have provided you answers to your question.
