### ISSUE TITLE
Incorrect tags when sharing library over network

### ISSUE THREAD

**Issue by kissenger** [darktable-org/darktable#14891]
### Describe the bug

I have my library file on a network drive, and two seperate windows computers accessing it. Both run Darktable 4.4.1.  On PC A, which originally imported the photos, the tagging is correct.  On PC B, loading the same library file, all the tags are mixed up.

### Steps to reproduce

1. Delete Library File
3. Open darktable on PC A with `"C:\Program Files\darktable\bin\darktable.exe" --library "K:\PathToLibrbayFile\library.db"` command
4. Import > Add to Library > Select photos 
5. Once imported, hover over imported files and check tags are correct in tagging module --> CORRECT TAGS SHOWN

6. Close Darktable
7. Run darktable on PC B using same command
8. Hover over files and check tags are correct in the tagging module --> INCORRECT TAGS SHOWN

### Expected behavior

Show the same tags on each photo independent of the accessing PC

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
Tags are kept in data.db.  You could run darktable with "C:\Program Files\darktable\bin\darktable.exe" --configdir "K:\PathToLibrbayFile\"

**Comment by ralfbrown** [comment]
Or `--datadir K:\PathToDataDB`

**Comment by MStraeten** [comment]
the latter is better since darktablerc contains system specific settings ...

**Comment by kissenger** [comment]
Thanks - got it to work with `--configdir`, but not with `--datadir` - just crashes on startup. Docs aren't detailed enough to help me understand what the difference between the two approaches are, or understand why it isnt wrking. But my issue is solved, so thanks
