### ISSUE TITLE
Darktable site offline?

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#14893]
It appears that darktable's download website is offline as is https://discuss.pixls.us/
This has been the case for a number of days for me and I am just wondering if it is only me. Sorry for posting to this site, but it has been a number of days and I did not know where else I could ask.

**Comment by elstoc** [comment]
Yes this is a known issue, which has already been raised (https://github.com/darktable-org/dtorg/issues/234). A fix is in progress.
