### ISSUE TITLE
HEIC support missing on latest PPA build

### ISSUE THREAD

**Issue by devosb** [darktable-org/darktable#14905]
### Describe the bug

HEIC files are not selected for import, nor are they displayed from previous (successful) imports.

### Steps to reproduce

I selected for import a folder with JPEG, PNG, and HEIC files, the HEIC files did not import. The other formats did. Browsing with Darktable to an already imported film roll, I could see the thumbnail images in the lighttable of HEIC files, but double clicking on image showed an error. Now in the lighttable I see the skull for this image.

So the HEIC was imported previously. I don't remember what version of Darktable I was using for the previous import, the version would have been what ever was in the PPA (I assume the PPA I am using, `deb http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04/ /`, is the same thing as OBS below) on 28 Dec 2022.

### Expected behavior

Darktable should select and display HEIC files.

### Logfile | Screenshot | Screencast

Error

![image](https://github.com/darktable-org/darktable/assets/12450072/da83c436-9e5d-4d20-a26b-9c7678a3366f)

Skull

![image](https://github.com/darktable-org/darktable/assets/12450072/74201686-a3af-4b39-8e66-b73659a35d98)

The error seems very similar to https://github.com/darktable-org/darktable/issues/14120

### Where did you install darktable from?

OBS

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04 Jammy on amd64

### Describe your system?

Using Wayland. Running `darktable --version` gives
```
this is darktable 4.2.1
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support disabled
  libheif support disabled
  libjxl support disabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```
Ah, libheif is disabled. But HEIC worked on this system in Dec 2022, and running `dpkg -l | grep heif` shows
```
ii  heif-gdk-pixbuf                                             1.12.0-2build1                              amd64        ISO/IEC 23008-12:2017 HEIF file format decoder - gdk-pixbuf loader
ii  libheif1:amd64                                              1.12.0-2build1                              amd64        ISO/IEC 23008-12:2017 HEIF file format decoder - shared library
```

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The issue still happens on import with `darktable --configdir /tmp`. I am not using any lua scripts that I know of.

While OpenCL support in compiled in (as seen above), running `darktable -d opencl` gives

```
[dt_get_sysresource_level] switched to 1 as `default'
  total mem:       31880MB
  mipmap cache:    3985MB
  available mem:   15940MB
  singlebuff:      249MB
  OpenCL tune mem: OFF
  OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
[opencl_init] could not get platforms: Unknown OpenCL error
[opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is OFF.
```

**Comment by ralfbrown** [comment]
The new executable was compiled without libheif -- "libheif support disabled" -- presumably because the build system couldn't find a compatible version. That's what provides the ability to load HEIC images.

**Comment by devosb** [comment]
Thanks for the information. So, would I contact the OBS maintainers [here](https://build.opensuse.org/project/requests/graphics:darktable:master) ?

I had not been used to reading about the releases on the GitHub page,
I usually went to the [darktable](https://www.darktable.org/) website, but it seems to be down for me.
