### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by InfoLibre** [darktable-org/darktable#14917]
### Describe the bug

Is https://darktable.org down or abandoned? The link on https://github.com/darktable-org/darktable is broken.

### Steps to reproduce

Go to https://github.com/darktable-org/darktable. Click on https://www.darktable.org.

### Expected behavior

Website should appear

### Where did you install darktable from?

darktable.org

### darktable version

all

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint Cinnamon 21.2

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
This place is for darktable software, not darktable website. There's a repository for that. darktable.org and pixls.us websites are on same server and a move is on its way to a new server.

**Comment by Nilvus** [comment]
See: https://github.com/darktable-org/dtorg/issues/234
