### ISSUE TITLE
Detail treshold on parametric mask causing immediate crash

### ISSUE THREAD

**Issue by Asanoth** [darktable-org/darktable#14920]
### Describe the bug

When applying a parametric mask and moving "detail treshold" slider right or left, darktable crashes when moving to another picture OR going to lighttable. Upon restart, crash is immediate once Darktable tries to load the image (lighttable or darktable).
Persists even when XMP file is deleted or rewritten to default. Deleting the RAW file (Nikon D600) prevents crashing. Position of other sliders does not seem to matter (even when the mask is blank). No log is created.
Discovered on Shadows and highlights module, also tested on Colors balance RGB and Local contrast.

Disabling OPEN CL GPU seems to fix the issue, but only tested briefly.

### Steps to reproduce

1. Open an image in darkroom.
2. Activate Shadow and highlights module and set parametric mask.
3. Move "Details treshold" slider.
4. Go to lighttable.

### Expected behavior

Darktable should not crash upon using "details treshold"

### Where did you install darktable from?

an online forum

### darktable version

4.4.1 (did not find anything else after clicking the logo)

### What OS are you using?

Windows

### What is the version of your OS?

10 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia Quadro M1000M, 30.0.15.1363

**Comment by jenshannoschwalm** [comment]
Please call with options '-d pipe -d opencl' and post the log file for more information to get an idea what goes  wrong.

**Comment by gi-man** [comment]
I think this is quite old, NVidia Quadro M1000M, 30.0.15.1363. Can you update your Nvidia drivers? Try to download from the nvidia website.

**Comment by jenshannoschwalm** [comment]
I asked for the log specifically because the cards memory is quite small (2GB), we don't have info about some cl settings and we would know if there is some cl memory request failing ...

No idea about what driver version that might be ... but request for latest driver is always good :-)

**Comment by Asanoth** [comment]
There is no new log file in NetCache, maybe there is another one elsewhere? Also I did not understand the "call" thing. 
Driver update did not solve the issue, but I can work without GPU.

**Comment by jenshannoschwalm** [comment]
"call" was meant as "start darktable on a console"

**Comment by gi-man** [comment]
@Asanoth Our website is down due to some server issues, but the content on how to start darktable with log on Windows is here: https://github.com/darktable-org/dtorg/blob/master/content/about/faq.md#windows

Understanding what is going on with the GPU might help you gain some speed and other too. Hence the interest in the log files.

Lastly, what online forum is the source of your darktable install files. Ideally you should only use the www.darktable.org but it is currently down.

**Comment by mcsanta** [comment]
Not sure if this is appropriate but wanted to share I noticed this behavior, too. I was using the sharpen module. Will try to produce some logs for you over the weekend. Best regards

**Comment by jenshannoschwalm** [comment]
Issue very likely related to OpenCL driver and resources currently worked on/fixed in master. Feel free to re-open if there is more data supporting other problems or at least a log file.
