### ISSUE TITLE
OpenCL crashes when processing (CL_OUT_OF_RESOURCES)

### ISSUE THREAD

**Issue by LimsDS** [darktable-org/darktable#14925]
### Describe the bug

Hi everybody, 
Darktable recognizes the GPU, but as soon as GPU should process in darkroom, it fails.

I tried the -d opencl debug and this is the log:

When I open darktable and I stop to lighttable:
-   [opencl_init] OpenCL successfully initialized. Internal numbers and names of available devices:
-   [opencl_init]		0	'NVIDIA CUDA NVIDIA GeForce 940MX'
-   [opencl_init] FINALLY: opencl is AVAILABLE and ENABLED.
-   [dt_opencl_update_priorities] these are your device priorities:
-   [dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
-   [dt_opencl_update_priorities]		0	-1	0	0	-1
-   [dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
-   [dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
-   [dt_opencl_update_priorities]		0	0	0	0	0
-   [opencl_synchronization_timeout] synchronization timeout set to 200
-   [dt_opencl_update_priorities] these are your device priorities:
-   [dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
-   [dt_opencl_update_priorities]		0	-1	0	0	-1
-   [dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
-   [dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
-   [dt_opencl_update_priorities]		0	0	0	0	0

When I open a picture (and go to darkroom):

- [opencl_synchronization_timeout] synchronization timeout set to 200
-     51,0489 [dt_opencl_check_tuning] use 1847MB (tunemem=ON, pinning=OFF) on device `NVIDIA CUDA NVIDIA GeForce 940MX' id=0
-     58,3246 [dt_opencl_enqueue_kernel_2d] kernel 123 on device 0: CL_OUT_OF_RESOURCES
-     58,7251 [opencl_demosaic] couldn't enqueue kernel! CL_OUT_OF_RESOURCES
-     59,1292 [opencl_demosaic] couldn't enqueue process_markesteijn_cl kernel! CL_SUCCESS
-     59,3306 [default_process_tiling_opencl_roi] [full] couldn't run process_cl() for module 'demosaic' in tiling mode: DT_OPENCL_PROCESS_CL

Then the same error occurs with any other module that darktable tries to start.

The setting on darktableerc is the following:
- cldevice_v5_nvidiacudanvidiageforce940mx=0 250 0 16 16 128 0 0 0.231574 0.000
- cldevice_v5_nvidiacudanvidiageforce940mx_building=-cl-fast-relaxed-math
- cldevice_v5_nvidiacudanvidiageforce940mx_id0=200

If I disable the GPU, darktable works.
It also works with the integrated GPU.
It just fails to use the Dedicated GPU.

Thanks in advance

### Steps to reproduce

1. Open Darktable
2. Open a picture in darkroom
3. The error occurs (demosaic fails, it can be seen in the histogram)

### Expected behavior

GPU should work with darktable

### Logfile | Screenshot | Screencast

[darktable-log_github.txt](https://github.com/darktable-org/darktable/files/12138434/darktable-log_github.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Home 10.0.19045

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce 940MX  driver: 536.67

**Comment by jenshannoschwalm** [comment]
You have set tuned-me to on and have defined the headroom to 200.

I would call this "begging for trouble" 😭 as your device will certainly have problems allocating memory and takes it from other apps or the system.

**Comment by LimsDS** [comment]
How can I set tuned-me to off? I can't find the option in darktableerc.

I tried to change the headroom when it started to fail. I also tried 1600 to check if that was the problem, but it didn't help.
I'll set it to the default value of 400.

**Comment by jenshannoschwalm** [comment]
> Do you mean the "opencl_tuning_mode"?

Yes. It doesn't make any sense at all on such a small card.

**Comment by LimsDS** [comment]
Thanks for the advice! I set it to "nothing".
I'll leave them like this (nothing / 400).

However, it didn't solve the problem. GPU still crashes when it tries to operate.

**Comment by jenshannoschwalm** [comment]
I forgot to mention, you should try with "darktable resources" as "default" or even "small" on such a small card.. I am aware of really bad "advice" on forums ... 

Ok, now log with `-d pipe -d opencl -d tiling` and post it please. Let's try to find out if there **is** a darktable issue :-)

**Comment by LimsDS** [comment]
Thanks!
I tried with small, but the result was the same

[darktable_log_github_2.txt](https://github.com/darktable-org/darktable/files/12138835/darktable_log_github_2.txt)

**Comment by jenshannoschwalm** [comment]
Thanks for the full log. The story gets somewhat more clear.

For some reason your graphics card has OpenCL memory in use when starting dt, this is pretty likely on current systems if your device is the "system device". At least dt correctly checks this and falls back to cpu code, that's exactly what it should do to avoid crashes. So - not a darktable issue at all - as i see it.

What can **you **do here? I don't know honestly as i am not a windows user at all. Another graphics card would be good but it seems to be built-in. I don't know how you set up windows graphics but
1. many apps take opencl memory to speed things up, firefox likes it as one example, also libreoffice or as i think also the windows office suite. If possible you might use the intel graphics as "system device" ???
2. There will be some nvidia app showing resources in use to check
3. On pixls.us - unfortunately currently down - there is a forum with many people on windows. They might help you out
4. Until you possible have fixed your settings it is very likely better to switch OpenCL off in darktable, this would increase performance as dt would not try to use it and would fall back.

Sorry about this, hope i could help you a bit, closing the issue as "not a darktable issue" :-) Good luck and i hope you like darktable and enjoy it.

**Comment by LimsDS** [comment]
Thanks a lot, at least I won't lose my mind anymore playing with dt parameters :D

I've been using dt for a year now, I really like it. Despite being a bit slow with this notebook, I still like to use it.

If I happen to solve this issue, I'll let you know. Maybe others have the same problem.

**Comment by LimsDS** [comment]
I found the problem. 
It's the demosaic algorithm. Since my camera has a x-trans sensor, the default algorithm is markesteijn 1pass. 
However, it seems too much to handle for my gpu.
If I switch demosaic to VNG I have no problem at all.

It occured to me when I tried to edit a CR3 raw file. It didn't give me any problem at all with RCD.

**Comment by jenshannoschwalm** [comment]
1. Certainly the markesteijn algorithm works fine on nvidia :-)
2. The amout of graphics ram taken by your system might well be more then 400MB (headroom)
3. Your integrated cpu has more memory available as shared.

**Comment by LimsDS** [comment]
I understand, thanks!
