### ISSUE TITLE
Problem with title of Lens correction module in dt 4.4.2

### ISSUE THREAD

**Issue by GEco417** [darktable-org/darktable#14928]
### Describe the bug

Importing CR2 images from a Canon 60D in darktable 4.4.1 or 4.4.2 uses a false preset in Lens correction module. It uses the right body and lens but displays another preset that I have (Fujifilm X100V)

### Steps to reproduce

1 - Import a CR2 image
2 - Automatic preset applies but show a wrong title

### Expected behavior

darktable should display a preset called Canon EF-S 17-55mm f2.8 IS USM

### Logfile | Screenshot | Screencast

![Correction_obj_default](https://github.com/darktable-org/darktable/assets/140324574/784bfa49-8c4f-45d7-87d5-538e17bfcd5f)

![Correction_obj_détail](https://github.com/darktable-org/darktable/assets/140324574/efb54dc4-525a-48b1-8922-6a8e3a15662a)

### Where did you install darktable from?

self compiled

### darktable version

4.4.2 (same thing with 4.4.1)

### What OS are you using?

Linux

### What is the version of your OS?

Mint 21.1

### Describe your system?

Intel Core i7-4790, 16G RAM, X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GP107 [GeForce GTX 1050 Ti], driver: nvidia v: 470.199.02

**Comment by MStraeten** [comment]
maybe add some infos on your preset - didi you change a something? If the default settings are matching a preset, then this is shown. (and checking "reset all module parameters to their default values" enforces that)

**Comment by GEco417** [comment]
Nothing has change in those preset, I only apply the lens corrections found in LensFun according to the type of lens

**Comment by TurboGit** [comment]
You probably have stored/changed a preset name at some point as the default (darktable built-in) preset which is auto-applied has no name. You may want to remove your preset named `Fujifilm X100V` which is actually using the default lens module parameters or rename it "auto" or whatever more generic.

**Comment by GEco417** [comment]
I think there's a problem other than a default preset that's been renamed. Here's my test today: I import an image taken by a Canon 6D Mk II + EF 70-200mm f/4 for which I normally have a dedicated preset. On import, no lens correction is applied by default (body and lens are well recognised). If I click on the 6D + 70/200 preset, a correction is applied but the title displayed in darktable is Fujifilm X100V. If I unfold the menu, I notice that I have 3 presets ticked.

![Correction_6D70-200](https://github.com/darktable-org/darktable/assets/140324574/17ea0e6d-f037-4eee-9adb-8d6ecff70619)
![Correction_6D70-200_détail](https://github.com/darktable-org/darktable/assets/140324574/c4b724c1-1c46-4c66-bdf1-9e3c2a8d989b)

**Comment by MStraeten** [comment]
if several presets are marked then they don't differ in their settings.
keep in mind that if you don't explicitly select a camera and lens before saving the preset the preset contains 'use the current cam and the current lens' for camera/lens selection.

you might add the presets (you can export them) so no one needs to guess ...

**Comment by GEco417** [comment]
For an image taken with the X100V: module title = FujifilmX100V. This is apparently correct.
But if you look at which presets are applied, there are two: FujifilmX100V and 6DMkII+EF24-105. Here are the contents of the presets, one of the cameras is Fujifilm, the other Canon. Why do both apply?
![Correction-sur-X100V](https://github.com/darktable-org/darktable/assets/140324574/f915eb54-c450-42d1-a0d2-bb4cf48f0986)
![Preset_Lens_FujifilmX100V](https://github.com/darktable-org/darktable/assets/140324574/496e2085-9ed5-4d13-9d35-c1c2e0151e0b)
![Preset_Lens_6DMkII_EF24-105](https://github.com/darktable-org/darktable/assets/140324574/bf792fe6-8731-4d74-bb69-15a581caa9fb)

**Comment by MStraeten** [comment]
The Fuji preset is applied but since it contains the same parameters as the canon preset, both are marked

**Comment by GEco417** [comment]
I don't understand why you say that the two presets have the same parameters: not the same manufacturer, not the same body, not the same lens. Only the Fuji preset should apply, right?

**Comment by MStraeten** [comment]
your screenshots doesn’t show the module parameters applied but the settings of rules to apply a preset.
darktable applies this preset.
But: darktable marks all presets, that are matching the module parameters currently applied. It doesn’t mark an applied preset. 

in your case: the Fuji preset is applied based on the settings of the autoapply rules - and since your picture contains Fujifilm … in the manufacturer setting etc. not the canon preset is applied. 
But since the fuji preset module parameters doesn’t differ from the canon preset module parameters (you can see the module parameters if you expand the module) both are marked.

I‘m pretty sure you defined your setting via applying lens correction for an image taken with your Fuji and the save as preset without changing something in the module settings and also with an image taken with a Canon…

You can test this by disabling the autoapply and the just enable the module with default settings - I’m pretty sure both presets are marked afterwards ;)

If you think there’s an issue with darktable then provide exports of the presets, so someone can inspect them…

**Comment by GEco417** [comment]
Thank you  @MStraeten, I will take a look this week-end

**Comment by GEco417** [comment]
MStraeten you are right, my presets apply the default correction in both cases (Fuji and Canon). 
I therefore understand that darktable marks both presets in this case, but I find it rather surprising that darktable doesn't just mark the preset applied, depending on the manufacturer in my case.
Even more confusing: I've changed the settings on the Canon module so that they're different from the Fuji module. When I submit an image taken with the Canon, the Canon preset is applied, but in the history the title displayed still mentions Fujifilm (see screenshots). 
I've attached the two preset exports, the problem seems to come from a "<multi_name>FujifilmX100V</multi_name>" line in the Canon preset but I can't see how to change it in the dt interface.
[lens_6D Mk II + EF 70-200mm.dtpreset.txt](https://github.com/darktable-org/darktable/files/12266955/lens_6D.Mk.II.%2B.EF.70-200mm.dtpreset.txt)
[lens_FujifilmX100V.dtpreset.txt](https://github.com/darktable-org/darktable/files/12266956/lens_FujifilmX100V.dtpreset.txt)

**Comment by GEco417** [comment]
I succeeded by editing the .dtpreset file for the Canon and correcting this line. But if you have an indication of how to do this from the dt interface, I'd be interested.

**Comment by MStraeten** [comment]
The instances menu has an option to rename an instance. You can select your preset, rename the instance and save the preset again

**Comment by GEco417** [comment]
OK than you
