### ISSUE TITLE
Automatic determination of quick access settings from JPEG preview

### ISSUE THREAD

**Issue by nowozin** [darktable-org/darktable#14922]
**Problem**: when adding a new RAW image to the library in Darktable 4.4.1, the initial quick access setting values are often quite far from a reasonable basic exposure.  In many cases I am quite happy with the SOOC JPEG exposure and would like to make minor adjustments from there.  The problem is that it takes me around 30 seconds to find suitable quick access settings that approximately match the SOOC JPEG, but sometimes it takes quite a bit longer.

**Solution**: the RAW file contains a low-resolution JPEG preview image that contains enough information to derive settings for the default quick access settings (160x120 pixels for my camera).  Ideally, in the quick access settings there would be a button "Match JPEG preview" that, when pressed, would automatically find quick access settings that approximately match the exposure/chroma/saturation/temperature of the low-res JPEG preview.

**Alternative 1**: if the default values can be automatically tuned to a good starting point without the information from the low-res RAW JPEG preview then this feature may not be necessary.

**Alternative 2**: if a JPEG+RAW pair is available, the high-resolution JPEG or a downsampled version of it that is still significantly larger than the JPEG preview contained in the RAW file could be used.

**Additional context**

A possible solution approach is to define a distance metric or divergence $D$ between two images:
1. $P$, the low-res RAW preview JPEG image; and
2. $O(w)$, a low-res Darktable pipeline rendering output _as a function of the quick access parameters_ $w$.

Obtaining good values of the parameters $w$ for a single image can then be cast as an optimization problem,
$$\textrm{argmin}_w \quad D(P,O(w))$$

As for the metric, it should be robust to image deformation (due to, say, a missing lens correction), but it should be sensitive to shifts in distribution.  I have some ideas for suitable metrics and am happy to elaborate if this is interesting.

The optimization can be carried out using bound-constrained derivative-free methods, which for small number of parameters would require a few hundred function evaluations.  The "quick access settings" have 8 continuous sliders.  (A suitable high-quality algorithm would be BOBYQA, [as implemented in the LGPL-licensed NLopt package](https://nlopt.readthedocs.io/en/latest/NLopt_Algorithms/#bobyqa).)

**Comment by jenshannoschwalm** [comment]
I guess there is none of the dt devs interested personally in such a feature so the chance to get it implemented is quite small.

If **you** would want to participate in dt and implement it yourself, we already have some code testing for B&W images in the preview found and leave some flag about it. This feature is optionally activated in preference and the default is `off`. Why - the reading of that preview (not including any processing) image is quite cpu-costly and slows down importing a lot.

At least - if want to participate - that would be the place to start :-)

**Comment by nowozin** [comment]
I had a look at the codebase and what a minimal prototype could look like.

Assuming one has a JPG+RAW pair (Alternative 2), I believe a minimal prototype would be an external script to take as input a default XMP and write an optimized XMP file.  This would use use `darktable-cli` to iteratively render candidate images, attempting to optimize "quick access" parameters in the XMP file to match the overall look of a JPG file.

But looking at the codebase the parsing/handling of XMP files seems a bit involved (gz+base64 encoding, C structs binary data).  I will maybe give the MVP idea a try in the next two weeks, depending on whether I succeed in reading/writing all "quick access panel" parameters from an XMP.

**Comment by jandren** [comment]
Maybe simplify the problem first before going full global minimization problem? Enough with matching the exposure? White balance should be matched already. Do you also need something else?

I for example find that it would be nice to have the initial exposure be about the same as the jpeg as that would make many images ok from the start without further changes. That should be doable to do on a per camera basis like the noise profiles, even using the same input data! The grey point of the jpeg is consistent and thus doesn't need to be found for every picture. I think this would be quite nice for new users and I might make a try on doing it at some point.

But for you right now. It is easy to figure out what exposure you need to match a jpeg, and then save that as a style which gets applied on every image from that camera. Problem essentially solved. darktable's auto applied styles are incredibly powerful.

Furthermore, say you also want to match the contrast/saturation of your jpegs. The same observation should apply, assuming you only use one picture profile / image style in camera. The operation will always the same and you may for example adjust the default settings of the sigmoid module such that you are close and save that as a style that is applied for images from that camera.

**Comment by pieqq** [comment]
As a RAW+Jpeg photographer, I would love such a feature, because I often find myself thinking "hm, this out-of-camera Jpeg is great, I would just like to edit the highlight and shadows a bit and call it a day", but I end up spending 30 minutes tinkering Darktable's options, and in the end the result is far from what I had seen in the OOC Jpeg...

That said, I'm not sure how to achieve this. I mean, there are many, **many** different ways of changing a pixel values to match a reference image. Maybe starting with a smaller scope, as @jandren suggests, and building up from there, would be a good start.

**Comment by ptilopteri** [comment]
Matching the out-of-camera jpg generated by proprietary and unknown processes has never  been the air
of darktable.  one is free to generate and/or share styles attempting to do this.  this is how free and open source software works, one has an itch an scratches it.  or pays someone else who is capable of satisfying their desires.

to make styles matching the ooc image from the many proprietary camera raw files would preclude the 
developers from ANY other software improvements, ie: there would be no darktable.
