### ISSUE TITLE
Pixii Camera (A2572)

### ISSUE THREAD

**Issue by garethwebber** [darktable-org/darktable#14938]
Please add the Pixii 2023. It provides DNGs by default (both colour and mono). Examples uploaded to http://raw.pixls.us today.

As DNGs are produced and can already be read by darktable, main thing is to add the colour profiles (attached).

https://www.pixii.fr

[profiles.zip](https://github.com/darktable-org/darktable/files/12146673/profiles.zip)

**Comment by kmilos** [comment]
dt doesn't support DCP profiles, it only uses the standard matrix from the DNG.

So, if the DNG loading works, there is nothing further required for the base support of this camera.

**Comment by garethwebber** [comment]
OK. Thanks.

**Comment by kmilos** [comment]
As I mentioned in the other ticket, it would still be interesting to check if all the other Pixii DNG modes work (in this basic sense) w dt, so please also test and contribute those samples!

**Comment by garethwebber** [comment]
The mono DNGs are read fine in darktable. Are there any tools I can use to check the DNP for bit depth?

**Comment by kmilos** [comment]
The feature list on the marketing page still lists:

12-14-16-bits programmable AD converter
Output: Digital Negative (DNG), Mono DNG, GPR (compressed)

No idea how you enable these in the menus...

You can inspect the resulting DNGs using e.g. `exiftool -a -u -s -g1`
