### ISSUE TITLE
Module name stuck after applying preset

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#14931]
### Describe the bug

Applying an old preset:
- sets the wrong name
- the name sticks; resetting the module, switching to another preset does not update it.

### Steps to reproduce

1. Start with a clean, empty config directory
2. Download the files from https://tech.kovacs-telekes.org/files/2023-07-23-dt-module-preset-name-stuck/
3. Import the preset
4. Import the raw
5. Go to _color balance rgb_, apply the imported _HL fringing_ preset:
![image](https://github.com/darktable-org/darktable/assets/3177739/050e39a3-575f-4d39-98e3-7d32f8cf2c2d)
6. The module instance will be assigned the name _purple hl_ (probably a name I used initially, but then I renamed the module). It's sourced from `<multi_name>purple hl</multi_name>`, not from `<name>HL fringing</name>`.
Module instance:
![image](https://github.com/darktable-org/darktable/assets/3177739/a8f8e1e8-19ba-4091-98c3-933f5007dbe7)
History:
![image](https://github.com/darktable-org/darktable/assets/3177739/31dc5ea2-ae47-433e-8695-883e447692a9)
7. Reset the module. The name stays:
![image](https://github.com/darktable-org/darktable/assets/3177739/073f405d-0a21-43b7-a6c3-35aea14ef42d)
8. Assign another preset, like _basic colorfulness: standard_. The module name stays:
![image](https://github.com/darktable-org/darktable/assets/3177739/3543efca-c2d6-493e-b400-85f428f2ad95)

### Expected behavior

The name should match the preset name shown in the preset selector; resetting/selecting another preset should clear/change it.

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+129~gf8de8d1555

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
That's expected, in the .dtpreset you have `<multi_name_hand_edited>1</multi_name_hand_edited>`, so this preset name has been hand-edited and so will never be rewritten.

**Comment by kofa73** [comment]
I'm sorry, but that sounds silly.
If I reset the module, or assign another preset, then it's no longer using _this_ preset.
If `multi_name_hand_edited` prevents renaming if I simply update parameters, that's fine. But on a **reset**, or **switching to another one preset**, why should a setting of **this** preset be relevant?

**Comment by kofa73** [comment]
I still don't think the argument 'the preset name has been edited manually' is valid.
Consider this:
- I use a module instance, and assign a name to it (either by loading one of my own presets, or simply by typing the name);
- resetting the module does not remove the name, but does set the settings to defaults/neutral;
- applying a different preset to the module still keeps the same name.

Why is there a difference between the following scenarios:
- I apply the built-in _basic colorfulness: standard_ preset to _color balance rgb_, then I reset the module: the name is removed, the parameters are back to default.
- I apply my own settings to the module, but don't rename it. I create a preset _for testing_. Later, I apply that preset to an image; the module instance is named _for testing_. When I reset the module, the name is cleared. This is consistent with the case above.
- I apply my own settings to the module, and name the instance _renamed instance_. I create a preset _renamed instance for testing_. When I now apply that _renamed instance for testing_ preset, the name of the module instance becomes not _renamed instance for testing_ (the name of the preset), but rather the name of the instance stored in the preset, _renamed instance_. Furthermore, resetting the module sets the parameters to default, but keeps the name. Applying another preset (such as a built-in preset, or a custom preset that does not have an instance name stored in it) also keeps the name, despite having completely different settings.

For a user, there is no way to tell which presets have an instance name stored inside them, but one will see 'applying preset X behaves a certain way; applying preset Y behaves differently'.
