### ISSUE TITLE
Enabling "mouse wheel scrolls modules side panel by default" disables keyboard adjustment of parameters

### ISSUE THREAD

**Issue by petrushy** [darktable-org/darktable#14935]
### Describe the bug

I prefer to have the mouse scroll wheel to scroll the panel rather than the slider value.

However enabling this option, does seem to disable the possibility to use keyboard arrows for adjusting slider parameters.

### Steps to reproduce

enable "mouse wheel scrolls modules side panel by default" under miscellaneous parameters in settings.

place cursor on a scroll bar, try arrow keys, nothing happens.

Disable setting above

try with keys, now it works.

### Expected behavior

it should be possible to use keyboard arrows regardless of side panel scroll preference.

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

PopOS 22.04 LTS

### Are you using OpenCL GPU in darktable?

Yes

**Comment by ralfbrown** [comment]
When that settting is enabled, hovering the mouse over a slider no longer focuses the slider (because then the scroll wheel would adjust the slider, not the panel).  You have to click on the slider to give it focus, then the arrow keys work.

**Comment by petrushy** [comment]
Many thanks for the explanation!
