### ISSUE TITLE
filmic: v6 and v7 color science output a black image with OpenCL (using mesa + rusticl with RX7900XTX GPU)

### ISSUE THREAD

**Issue by baudlord** [darktable-org/darktable#14937]
### Describe the bug

`filmic rgb`, with `color science` set to `v6 (2022)` or `v7 (2023)`, outputs a completely black image when OpenCL is enabled, using rusticl and Radeon RX7900XTX.

Module works correctly with `v5 (2021)` and OpenCL.

Both `v6 (2022)` and `v7 (2023)` work properly with OpenCL disabled.

### Steps to reproduce

1. Enable rusticl for AMD GPU defining a `RUSTICL_ENABLE=radeonsi` environment variable. 
2. Open a RAW image.
3. Enable the `filmic rgb` module, with default settings.
4. Ensure `color science` is set to `v7 (2023)` or `v6 (2022)`.

Using `v5 (2021)`, the image is correctly shown.

### Expected behavior

`v7 (2023)` or `v6 (2022)` should also output a valid image.

### Logfile | Screenshot | Screencast

Logs uploaded to this Gist: https://gist.github.com/baudlord/af84dc1f8d965351bdb4b15a640ad99f

- `clinfo` is the output of `clinfo` in my machine.
- `darktable-v5.log` is a partial log, showing the thumbnail and export logs with `filmic rgb` set to `v5 (2021)`. Notice the  `filmic rgb` line mentions `min: (0.000152; 0.000000; 0.000000) max: (0.701757; 0.691199; 0.588827)`.
- `darktable-v7.log` is a partial log, showing the thumbnail and export logs with `filmic rgb` set to `v7 (2023)`. Notice the `filmic rgb` line mentions `min: (0.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000)`.
- `darktable.log` is a complete log, from darktable start (with `-d opencl -d common -d nan`) to opening the preview of an image with `filmic rgb` set to `v7 (2023)`.

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+77~gf3d841cdf6

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux, latest updates as of 24/07/2023

### Describe your system?

- Arch Linux, with kernel 6.3.12
- AMD Ryzen 7 5800X3D CPU, with 32GiB RAM
- AMD Radeon RX 7900 XTX, with 24GiB RAM
- Mesa 23.3.0 with rusticl, from mesa-git repository.
- Wayland with sway version 1.9-dev-92244c87 and wlroots 0.17.0.r6490.214df8ed-1
- GTK 3.24.38-1

- Sony A7Rii camera, firmware 4.01, uncompressed RAW and large JPEG.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 7900 XTX, 24GiB, mesa 23.3.0_devel.174631.c2e39863264-1 with rusticl

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

 - Can reproduce with darktable-git 4.5.0 (AUR, master as of 24/07/2023) and darktable 4.4.2 (Arch Linux extra).
 - Can reproduce with both RAW and JPEG files.
 - Yes, steps are reproducible with a fresh edit.
 - Issue happens with the thumbnail, preview and output image modes. I can upload RAW and XMP if needed.
 - Yes, issue is present with an empty config-dir.
 - No Lua scripts are used.
 - Issue happens under Xwayland as well as native Wayland.

**Comment by trougnouf** [comment]
I have this issue with the `color balance rgb` module as well. (Also using a Radeon RX 7900 XTX.)

**Comment by Fr31Thibault** [comment]
Same issue here, with filmic and color balance rgb. ( Including the fact that color science v5 works and V6/V7 don't )

Platform : Ubuntu 2023.04 
Mesa from kisak-mesa repo
Darktable from repo :
  http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_23.04/
   Version: 4.5.0~git143.d5455e7c-1+10359.1

**Comment by jenshannoschwalm** [comment]
Please note this is a darktable issue tracker, nothing about how to install buggy CL drivers and/installations.

**Comment by Compizfox** [comment]
Relevant issue over at Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7746

**Comment by jenshannoschwalm** [comment]
As specific to RustiCL closing this for now
