### ISSUE TITLE
Failed nightly macOS build

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#14939]
@zisoft I guess that's for you.

Tonight's nightly build failed due to a graphicsmagick rebuild problem in the macOS job.
Since the log for this build will eventually expire, I quote the relevant excerpt below:

```
Run export HOMEBREW_NO_INSTALL_FROM_API=1
  export HOMEBREW_NO_INSTALL_FROM_API=1
  
  gm_formula=`brew edit --print-path graphicsmagick`
  cat $gm_formula | sed '/--with-modules/d' > gm_formula.tmp
  mv gm_formula.tmp $gm_formula
  
  brew reinstall --build-from-source graphicsmagick
  shell: /bin/bash -e {0}
  env:
    DEVELOPER_DIR: /Applications/Xcode_13.[2](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:2).1.app/Contents/Developer
    CC: cc
    CXX: c++
    MACOSX_DEPLOYMENT_TARGET: 11.[3](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:3)
    SRC_DIR: /Users/runner/work/darktable/darktable/src
    BUILD_DIR: /Users/runner/work/darktable/darktable/src/build
    INSTALL_PREFIX: /Users/runner/work/darktable/darktable/src/build/macosx
    ECO: -DBINARY_PACKAGE_BUILD=ON -DBUILD_CURVE_TOOLS=ON -DBUILD_NOISE_TOOLS=ON
    CMAKE_BUILD_TYPE: Release
    GENERATOR: Ninja
    TARGET: skiptest
Warning: edit is a developer command, so Homebrew's
developer mode has been automatically turned on.
To turn developer mode off, run:
  brew developer off

Warning: building from source is not supported!
You're on your own. Failures are expected so don't create any issues, please!
==> Fetching graphicsmagick
==> Downloading https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.[4](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:4)0/GraphicsMagick-1.3.40.tar.xz
==> Downloading from https://phoenixnap.dl.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.40/GraphicsMagick-1.3.40.tar.xz
==> Reinstalling graphicsmagick 
==> ./configure --prefix=/usr/local/Cellar/graphicsmagick/1.3.40_2 --disable-ope
==> make install
Last 1[5](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:5) lines from /Users/runner/Library/Logs/Homebrew/graphicsmagick/02.make:
    ~~~~~~~~~ ^
coders/jpeg.c:14[6](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:6)6:26: error: use of undeclared identifier 'JPROC_PROGRESSIVE'
    jpeg_info.process == JPROC_PROGRESSIVE ? LineInterlace : NoInterlace;
                         ^
coders/jpeg.c:146[7](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:7):32: error: no member named 'process' in 'struct jpeg_decompress_struct'
  image->compression=jpeg_info.process == JPROC_LOSSLESS ?
                     ~~~~~~~~~ ^
coders/jpeg.c:[14](https://github.com/darktable-org/darktable/actions/runs/5639374704/job/15274507014#step:4:14)67:43: error: use of undeclared identifier 'JPROC_LOSSLESS'
  image->compression=jpeg_info.process == JPROC_LOSSLESS ?
                                          ^
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -g -O2 -Wall -D_THREAD_SAFE -c coders/jxl.c  -fno-common -DPIC -o coders/.libs/magick_libGraphicsMagick_la-jxl.o
4 errors generated.
make[1]: *** [coders/magick_libGraphicsMagick_la-jpeg.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Error: Process completed with exit code 1.
```

**Comment by zisoft** [comment]
Will have a look

**Comment by zisoft** [comment]
[Upstream bug with GraphicsMagick and JPEG-Turbo 3.0.0](https://sourceforge.net/p/graphicsmagick/bugs/711/).
It is fixed in GraphicsMagick 1.4.0, we need to wait for Homebrew to update (currently still on 1.3.40)

**Comment by victoryforce** [comment]
> [Upstream bug with GraphicsMagick and JPEG-Turbo 3.0.0](https://sourceforge.net/p/graphicsmagick/bugs/711/). It is fixed in GraphicsMagick 1.4.0, we need to wait for Homebrew to update (currently still on 1.3.40)

Thanks! That is, as far as I can see, this WILL be fixed in GraphicsMagick 1.4.0. There is no formal release yet and Homebrew is unlikely to package the GraphicsMagick pre-release snapshot.

That is, we would have to wait when GraphicsMagick decides to release 1.4.0, and Homebrew packages this version. This is potentially a very long story.

But we need to restore nightly builds as soon as possible for at least other platforms, and if possible for macOS as well.

I see the following options:

- Just remove the macOS build temporarily (but maybe for a long time) and publish nightly builds for other platforms.

- Temporarily build macOS darktable without GraphicsMagick.

- Try replacing GraphicsMagick with ImageMagick. If the build with ImageMagick will not require such a rebuild of the library to ensure the correctness of the work, then perhaps it is worth keeping this version as the default?

What are your thoughts on this?

**Comment by zisoft** [comment]
> * Just remove the macOS build temporarily (but maybe for a long time) and publish nightly builds for other platforms.

Agreed. Just provided PR #14948 to have nightly builds working again

> * Temporarily build macOS darktable without GraphicsMagick.

I must admit that my skills are not deep enough to make any recommendations on this.

> * Try replacing GraphicsMagick with ImageMagick. If the build with ImageMagick will not require such a rebuild of the library to ensure the correctness of the work, then perhaps it is worth keeping this version as the default?

I am just investigating and testing on this. Will report later.

**Comment by kmilos** [comment]
IMHO it's still useful to have the nightly builds, even if it means temporarily disabling GM support (or even w/o IM if that's not an option either).

**Comment by MStraeten** [comment]
macports based build is fine with 1.3.40

**Comment by zisoft** [comment]
@MStraeten: the problem occurs when trying to compile GraphicsMagick from source with the new JPEG-Turbo 3.0.0

**Comment by MStraeten** [comment]
ok macports is on libjpeg-turbo 2.1.5.1 
there's an issue warning of an update since there are a whole bunch of dependents that might break ...
