### ISSUE TITLE
Dt 4.4.2 Windows build terminates while building a large number of thumbnails - reproducible in my installation

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#14947]
### Describe the bug

I have a new install of dt 4.4.2, replacing 4.4.1 on my Win 10 system.  Win 10 is at version  22H2; build 19045.3208 on an INtel i7 8700 CPU with 32 GB RAM.

In lighttable, browsing by capture date with a significant number of qualifying images - say greater than 500 - dt begins to build thumbnails. Depending on on hos many images per row I choose to view  - between say 4 and 18 - dt closes if I scroll the thumbnail display too quickly. It is almost immediate if I have a high number of images per row. If I do not scroll quickly, but allow each screen full to be fully populated with thumbnails, irrespective of size, then dt does not close.

### Steps to reproduce

1. in lighttable, select collections based on capture date
2.  specify a time period which would have the effect of selecting a large number of images - hundreds at least. In my case I typically suggest a year (2022  for example)
3. Using the controls immediately beneath the thumbnails display - either the slider bar or the numeric data entry field, set to a higher number of image thumbnails per row. I typically use 11 to 18
4.  While dt is building and displaying the thumbnails use the scroll bar to the right of the thumbnail display area, to scroll quickly to parts of the display area which have not yet been populated.
5.  Continue scrolling too far or too quickly cause dt to terminate.

### Expected behavior

Continue to build thumbnails as determined by  the controls beneath the thumbnail display, bearing in mind the settings in preferences/lighttable/thumbnails

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Home

### Describe your system?

Win 10 is at version  22H2; build 19045.3208 on an INtel i7 8700 CPU with 32 GB RAM.

GPU is nVidia GTX 1050 with 2 GB video RAM
Monitor is Benq 2700PT 4K, running 2560 x 1440

Windows install on 250 GB Crucial SSD; 'Users' directory is on this drive
Images and XML files are on a separate 500 GB Crucial SSD

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nVidia GTX 1050 M'soft driver version 31.0.15.3179, dated 25 April 2023

**Comment by ralfbrown** [comment]
Unable to reproduce on Linux/64GB with a folder containing 1680 images and using 14 images per row.  I kept scrolling all the way up and down until all thumbnails were populated.

**Comment by jenshannoschwalm** [comment]
I guess that's another windows opencl issue, again 2GB of video ram on windows. While preparing the log with `-d pipe -d opencl` you should try 
1. run dt without opencl
2. in preferences make sure your dt resources are set to default
3. Have a look into your nvidia tool (whatever that is called in windows) and check for used memory

an report back.

**Comment by LateJunction** [comment]
Since submitting my initial bug report I have restarted Windows (a number of times, for various reasons). following this I am unable to invoke a termination in dt by scrolling the lighttable window while thumbnails are being built. I have now built thumbnails at a number of sizes for my total image portfolio so I can't deliver a valid failure report/data.
