### ISSUE TITLE
Auto export with bracketed exposure

### ISSUE THREAD

**Issue by kkempter-getswift** [darktable-org/darktable#14952]
**Is your feature request related to a problem? Please describe.**

I often process an image and then when it is time to get it printed I create several images, changing the exposure value to brighten it and send these images to the printer as a test since I find that the prints are always darker than expected.

**Describe the solution you'd like**

It would be a great option to pick an image for export and be able to generate n number of output images with bracketed EV values for the exposure, say 2 darker and 7 lighter by .25 stops

**Alternatives**

I do it manually

**Additional context**

No

**Comment by jenshannoschwalm** [comment]
In short: no chance to get this in core dt functionality :-) Let me explain the darktable options :-)

1. DT is pretty good already in checking exposure correctly. You would have to use some sort of screen calibration or know you screen characteristics (sRGB or whatever) - all covered in dt manual or video tutorials
2. you could use `darktable-cli` and use bash scripts to achieve what you want
3. you could use darktable's lua extensions. There is a seperate issue tracker / feature request thing for this on this site. They might know if it even exists ...

Closing this here as not planned but .. have fun with your great camera and i hope you will get used to the dt way and "master this beast called dt"
