### ISSUE TITLE
softproof profile list does not drop down when clicked 

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/darktable#14958]
### Describe the bug

The softproof profile list does not drop down when clicked. I can see the transition from unhighlighted to highlighted when the cursor passes over the control. I just installed dt 4.4.2 for macOS from the web site. This worked with 4.4.1.

### Steps to reproduce

1. install dt 4.4.2 for macOS
2. start dt
3. enter darkroom
4. right-click softproof icon to bring up profile selection dialog
5. click on soft proof profile dropdown menu

### Expected behavior

Clicking on softproof dialog should drop down list of profiles. All other profiles work as expected so this is not a general profile issue.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

macOS Ventura 13.4.1

### Describe your system?

Since installed by production build DMG I believe that sufficiently describes the configuration. The hardware its a MacBook Pro with M1 and 64Gb.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1

**Comment by MStraeten** [comment]
Not reproducible on my machine (mbp m1max)
What’s your system configuration? one display? Two displays? Is the behaviour equal on both displays?
Does it also occurs with a fresh ~/.config/darktable/darktablerc?

**Comment by TiredOfGuessing** [comment]
Thanks for confirming so fast. I have a MBP M1 Max with a second monitor, which was connected at the time of the problem. 

Yesterday, I created a color test TIFF image in another app trying to sort out color on Macs with ColoSync. The first use after upgrading dt was loading this TIFF. Upon closer examination today loading a TIFF invokes the (v3.0 JPEG) pipeline, so I suspect it's related to that being the first usage post upgrade?

1. Today, testing on a regular photo/raw file (v3.0 RAW) pipeline the softproof profile list works fine.
2. After test 1 the TIFF (v3.0 JPEG) pipeline the softproof profile list also works fine. Aside from this test I have/do not use (v3.0 JPEG) pipeline so can't offer any insight.
3. I unfortunately do not have a darktablerc backup to see if something changed as a result of the upgrade, test 1 or 2.

**Comment by MStraeten** [comment]
maybe some display resolution dependent stuff (like https://github.com/darktable-org/darktable/issues/14856) 
on my second screen (WQHD) the drop-down list is a little bit too short formten displayed text (compared to the available space on the notebook display)
Unfortunately no known solution for it yet …

**Comment by MStraeten** [comment]
a build using gtk3 3.24.38 doesn't show this behaviour - but has redrawing issues. Since the latter is just annoying and can be handled by additional scaling attempts (if it occurs) using gtk3 3.24.38 seems to be the better solution.
so here a 4.4.2 arm release build with gtk3 3.24.38
[darktable-4.4.2_arm64_gtk3.24.38.dmg](https://mega.nz/file/bOwnEaRK#VXAk3zXgcOjI2YOTNeppgMwddH9P5i5twjiXbz1gPqM)
(not codesigned, so you might need to allow execution via terminal: " xattr -c <path/to/application.app> "
please confirm if that also solves your issue ...
