### ISSUE TITLE
Proposal for restructuring of blending and masking functionality of modules in the UI.

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#14955]
Motivated by discussion in this post #14622 and by the experience of everyday use of very sophisticated but also complex  masking functionality of modules, I have proposal for restructuring to facilitate usability. 

I would like to put this up for discussion.

All editing modules share three important functions: _Masking function, opacity and blend modes._

This functionality can be accessed via icons in the blending and masking bar:

![grafik](https://github.com/darktable-org/darktable/assets/38165484/a6647a1b-c075-4cd3-ac07-6bd7cc39468c)

This is well structured logically with an emphasis on different masking options, each of which can be accessed separately; _drawn masks, parametric masks, combination of the two_ and finally the _raster masks_. 

Other functions unrelated to masking (opacity and switching between blending color spaces) have their own icons, with opacity repeating itself as an additional sub-function for all others. The selection of different blend modes is also _repeated with other options as one of the sub-functions_. Here in the example for menu for drawn mask:

![grafik](https://github.com/darktable-org/darktable/assets/38165484/018a74cf-2bc2-4928-becf-9916817baa46)

Of course, this has the advantage that these additional functions are always accessible, regardless of the selected mask type.

- The first question that arises from this is _how often_ this _additional functionality_ in _combination with the masking_ is actually _used in practice_, so that there is a need to always be available?

- The second question relates to the logic of the functions themselves. Both the blend modes and the opacity _affect the module itself_ and have _no relation to the masking function_. Wouldn't it be better to separate them from the masking function?

The other questions of  usability  arise from the separation of different masking options. 

As mentioned above, in the bar we have the separation between different masking options. Drawn and parametric masks separately, their combination and as a special masking option the raster mask, which only becomes active if a mask has already been created by the three other options in the hierarchically lower module.

The advantage of this separation is that the respective menus are _much clearer_ because they are not "overloaded" with all other masking options. Depending on the task, for simple masking, this may make working more efficient.

The problem is - in my experience - that you don't always know if one masking type is sufficient to get the job done. Especially when using parametric masks, it is often the case that they either have to be limited or extended with the help of drawn masks.

This would be a typical case for the restriction of parametric mask:

![grafik](https://github.com/darktable-org/darktable/assets/38165484/94d8aac1-dfeb-4c90-b38d-a6d02fc2223a)

And vice versa - the drawn mask can also be refined very well with the help of parametric masks. In this case, the green grass was isolated with a parametric mask:

![grafik](https://github.com/darktable-org/darktable/assets/38165484/65fa740a-6668-4300-b0f8-fe9f64c9ef21)

So, in practice - as far as my work is concerned - it turned out that one type of masking _almost always_ serves as an "extension" of the other, so that I don't use the individual options offered in the bar at all, but go straight to the combination.

The masking has become a "unit" for me, so to speak, where I have an overview of all options and their combinations. While in some cases this refinement isn't necessary, I find it a great benefit to keep track of all the options that can serve that particular purpose. Like a kind of "toolbox" for masking.

I can imagine that even for new users this overview is lost if the masking functionality is "scattered" with an additional option to combine them, especially since the same bar also contains other functions that have nothing to do with masking.
The masking functionality loses the "entity" that serves that particular purpose.

Therefore my suggestion to separate the lower module bar according to functionality:

![Bar](https://github.com/darktable-org/darktable/assets/38165484/da1ab675-9494-4831-9e0f-cbdd5492145c)

So we would have the _masking function_, where all masks are listed and can be combined with each other if necessary:

![masks](https://github.com/darktable-org/darktable/assets/38165484/8b4dd94d-12f0-479e-a5be-82eeb8d5cce3)

Raster mask here is a special case: if there is no raster mask, this option remains greyed out. If there is one and it is also selected, other options should be grayed out.

_Opacity_ option where you can control the opacity of the module:

![Opacity](https://github.com/darktable-org/darktable/assets/38165484/0400c9ab-8d6b-4352-a827-c7966b7ca826)

And _blend modes_ option where you can choose the color space in addition to blended modes:

![Blend_mode](https://github.com/darktable-org/darktable/assets/38165484/5861aa3c-4891-427c-b21f-25cc96d3894b)

I would like to emphasize that this suggestion is based on my own experience working with darktable and not the result of observing other people's user behavior, and is accordingly very subjective.

I hope, however, that it will lead to a discussion that could then serve to improve usability.

**Comment by ralfbrown** [comment]
> The second question relates to the logic of the functions themselves. Both the blend
> modes and the opacity affect the module itself and have no relation to the masking
> function. Wouldn't it be better to separate them from the masking function?

That is not correct.  The masking function creates a per-pixel opacity mask, which is then multiplied by the (global) blend opacity, after which the resulting per-pixel opacity is used to compute the pixel-wise blending of the module's input and output.  So of all the masking function settings, "off" is the only one which is fundamentally different from the others - by skipping the blending entirely.

You can switch from drawn mask or parametric mask to drawn&parametric without losing anything, but the latter takes up more screen space and may lead to unnecessary scrolling if you only need one rather than both.  But it's entirely possible to just ignore those two and always pick d&p.

That said, I do like the look of some of your suggestions.  But you're also forcing a substantially wider minimum width than the current layout (looks like about 1.5x), which reduces the available screen space for the image being edited....

**Comment by jenshannoschwalm** [comment]
> That is not correct. The masking function creates a per-pixel opacity mask, which is then multiplied by the (global) blend opacity, after which the resulting per-pixel opacity is used to compute the pixel-wise blending of the module's input and output

Yes, that's the maths behind it. But the non-technical description could be "apply the mask below with a certain strength between 0 and 100%" which would be pretty correct. In this context i guess the global opacity would be best seen "as global" and be evenly associated with the module than the below mask.

**Comment by s7habo** [comment]
> In this context i guess the global opacity would be best seen "as global" and be evenly associated with the module than the below mask.

Exactly. And if I understand it correctly, the opacity also works like this. 

If I created/selected a mask in the "Mask" option in my suggestion above, the opacity only affects this masked area, because this area is "active" through the mask for the module. And because the other areas of the photo are "ignored" by the mask, they are not affected by the processing of the module and accordingly also by the opacity of the module. 

When the mask is turned off/deleted, the processing and the opacity of the module apply to the entire image.  So it is not necessary that every masking option has this control. 

One also have to take into account that the drawn masks have their own opacity regulation which makes things even more confusing if there is no separation between "global" and mask-related. 

> You can switch from drawn mask or parametric mask to drawn&parametric without losing anything, but the latter takes up more screen space and may lead to unnecessary scrolling if you only need one rather than both. But it's entirely possible to just ignore those two and always pick d&p.

If you remove opacity and blend modes sliders from the masking options, the mask menu will not be much larger than it is now in single mask options.

**Comment by s7habo** [comment]
>  But you're also forcing a substantially wider minimum width than the current layout (looks like about 1.5x), which reduces the available screen space for the image being edited....

This could indeed be problematic. That would be about the minimum width:

![mask2](https://github.com/darktable-org/darktable/assets/38165484/58883edd-747a-4973-a851-ef1dffda6b16)


In the bar I have used icons instead of words.  Nevertheless, if it becomes narrower, it quickly gets too dense and cluttered.

**Comment by s7habo** [comment]
It could be even tighter if one had a sub-menu for different selection options in drawn and parametric masks:

![mask3](https://github.com/darktable-org/darktable/assets/38165484/fd19b49d-d21d-4ac6-b9ec-c1c8933a1e63)

This way it also looks clearer but you have one click more.

**Comment by todd-prior** [comment]
I just made a couple of comments and added a small video clip in 14462... might be better for this thread but I don't know how to move it over and I didn't want to duplicate it.....  check them out if you are interested... basically it was a thought about being able to collape the masking panel/controls... etc right now if you activate one then everything opens at the bottom of the module adding greatly to the vertical space .... I just showed an alternate way that it is handled elsewhere for some discussion/inspiration... In the example also the opacity slider is at the top of the module...just another way to do it...ie pull it out from the middle of the masking options...
