### ISSUE TITLE
DT 4.4 crashing upon export

### ISSUE THREAD

**Issue by kkempter-getswift** [darktable-org/darktable#14951]
### Describe the bug

I grabbed the 4.4.2 tar.xz file, uncompressed it and ran:

./build.sh --prefix /opt/darktable-4.4.2 --build-type Release --install --sudo  

Then I did this:

1) rm -fr ~/.config/darktable

2) /opt/darktable-4.4.2/bin/darktable

3) In darktable I did Import -> add to library
   navigated to my directory of Hasselblad .3FR RAW images and clicked 'add to library'

4)  Edited an image  

4) in Lighttable I clicked export
   selected an output destination
   then left the size in pixels as 0 / 0 for full size and clicked export
   
5) after about 30seconds darktable crashes and even the terminal window I was running in goes away too

Can you point me to where DT logs info?

   
   

### Steps to reproduce

1) rm -fr ~/.config/darktable

2) /opt/darktable-4.4.2/bin/darktable

3) In darktable I did Import -> add to library
   navigated to my directory of Hasselblad .3FR RAW images and clicked 'add to library'

4)  Edited an image  

4) in Lighttable I clicked export
   selected an output destination
   then left the size in pixels as 0 / 0 for full size and clicked export
   
5) after about 30seconds darktable crashes and even the terminal window I was running in goes away too

### Expected behavior

DT should not crash and export the file

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

Fedora 38 running on an LG Gram 17 with 32G of RAM and 2 internal 1TB SSD drives

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by kkempter-getswift** [comment]
I have found that if I plug in 7200 x 0 in the size boxes then the export works, which creates a file that is 7200 x 5399 or 24 inches x 17.999 inches

**Comment by kkempter-getswift** [comment]
The file size for these images is 11656 x 8742

If I set the export size to 9000 x 0 it works
Setting it to 10000 x 0 works
but setting it to 11000 x 0 (or setting it to 0 x 0 for full size) results in a crash

**Comment by jenshannoschwalm** [comment]
Just two reminders :-)
1. we have a quite complete manual
2. we even have `darktable --help`

So `darktable -d pipe -d opencl -d imageio` will be your friend.

**Comment by kkempter-getswift** [comment]
Resolved, I installed the following packages on my laptop and now it works!

intel-opencl.x86_64
intel-opencl-clang-devel.x86_64

Thank you @jenshannoschwalm  for the debug flags, it was what I needed to see the issue.
