### ISSUE TITLE
Fields puzzled (again) in Metadata editor tab

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#14957]
### Describe the bug

Clicking on to the Metadata tab displays puzzled fields with garbage (see screenshot).
This also happens within Preferences / General tab, though it is less noticeable.
It did happen a few times ago, then seemed to have been fixed until 4.2.1 & 4.4.2.
I use laptops (one Fuji E557 and one Dell E5540 with their specific docking station in order to get decent display and comfortable keyboard and mouse), and only notice this when using the external display. No problem if I use the laptops alone, with no external display attached.

### Steps to reproduce

1. use a laptop with external display and start on that one only.
2. start dt and open the metadata tab
3. you should see something like on the attached screenshot - if not, I must be cursed !
![Capture d’écran du 2023-07-25 23-23-23](https://github.com/darktable-org/darktable/assets/49912948/f4f20833-1f7f-4f2e-9273-6a97db5b8b91)
4. of course, this prevents me from being able to fill those fields

### Expected behavior

I should be able to edit the fields as I need

### Where did you install darktable from?

self compiled

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.2 LTS 64 bits

### Describe your system?

Fujitsu Lifebook E557 / Dell Latitude E5540
RAM 32 Gio / 12 Gio
Proc Intel Core i3-7100U @ 2.40GHz x 4 / Intel Core i3-4030U @ 1.90 GHz x 4
Fuji docking station / Dell docking station
GC Mesa Intel HD Graphics 620 (KBL GT2) / Mesa Intel HD Graphics 4400 (HSW GT2)
HD 1 To SSD / 1 To
OS Ubuntu 22.04.2 LTS 64 bits, Gnome 42.9, X11

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
Can't reproduce on my side on darktable master (nearly 4.4.2) on Debian Sid. Probably a Gtk issue, which Gtk version do you have on your system?

**Comment by FalCT60** [comment]
It only happens with an external monitor attached - in my case, it is a HD TV.
And only in this peculiar tab and the Preferences / General one. Why ?
Here is the result of apt-cache policy libgtk+.
[GTKinst.txt](https://github.com/darktable-org/darktable/files/12175981/GTKinst.txt)

**Comment by gi-man** [comment]
Are you on Wayland?

**Comment by Nilvus** [comment]
I test that on an external monitor too, as you explained on your step-by-step. @gi-man: it's precised on his install, he use X11. It's Gtk 3 that is useful for darktable, so you have 3.24.33. I don't know if such issue (not a really old one could have such issue. Only thing is that I have a more recent version. @dterrahe: as a Gtk expert on darktable and you work actually on that part, do you have any ideas for that issue?

**Comment by dterrahe** [comment]
You could try if #14960 makes any difference, but I don't know why it should really and have no other ideas. Does this happen at all font sizes?

**Comment by FalCT60** [comment]
@gi-man: it makes no difference using wayland or X11.
BTW, I had to revert to X11 due to latency when editing values with wayland. It took a while before I could find that.
@dterrahe: last time it happened (I do not remember which version of dt, maybe pre-4.2 since it happened again in 4.2.1), using different font size or even another font did not change anything.
@Nilvus: GTK libraries are exactly the same on both machines.
:-(

**Comment by parafin** [comment]
This is IMHO a GPU driver issue. So maybe try different kernel, Xorg intel driver and MESA versions.

**Comment by FalCT60** [comment]
Ok, might be related to GPU, but not xorg as this happens with wayland too.
However, the GPU being part of CPU, I cannot see how I could change anything. I did not install anything particular, and this occurs and disappears with dt (and/or system ?) updates.
About updating the kernel : there was such an update yesterday, but it did not change anything.

**Comment by Nilvus** [comment]
> Ok, might be related to GPU, but not xorg as this happens with wayland too. However, the GPU being part of CPU, I cannot see how I could change anything. I did not install anything particular, and this occurs and disappears with dt (and/or system ?) updates. About updating the kernel : there was such an update yesterday, but it did not change anything.

Do you have OpenCL activated? If yes, on such old Intel graphics chipset it's better to not use it. In case, test with openCL deactivated.

You precise that you use docking station. I doubt it could be related but did you try to connect your external monitor directly to your laptop? Do you notice differences?

Your issue is quite probably related to your system, not directly darktable. I always use darktable with external monitor, since years, and never see such issue (and I'm not the only one for sure ;-)!)..

**Comment by Nilvus** [comment]
For OpenCl, you can check if it's activated or not on darktable main preferences, process tab.
Check also if you have beignet driver installed. If yes, uninstall it. This driver is quite bugged and not recommended to use.

And if it's just related to HD TV used, I doubt you will see a fix as probably none of our developers use such system.

**Comment by FalCT60** [comment]
OpenCL was not activated on my systems. And I did not even think my machines could support it, until I tried this afternoon.
To my surprize, I could find, install and activate the stuff so OpenCL would run.
I do not know whether it will improve significantly the processing, given the hardware itself, and maybe will I have to deactivate it in order to get decent performances.
Now, I am going to build a new install key and reinstall. Then I can tell if things have evolved the right way or not.
Please, let this issue open until I come back and report.
Rgrds,

**Comment by Nilvus** [comment]
It's highly not recommanded to activate OpenCL for such old Intel internal graphics card. You will have nearly nothing better in terms of performance but will surely have more bugs/issues. So revert back to what you have before installing OpenCL will be better for you.

For Intel graphics cards, it's only about 8th or 9th generation with Neo driver that OpenCL is good. Before it's unstable and not powerful.

**Comment by jmert** [comment]
I see the same rendering artifacts in text boxes (which seems to be "bleed through" of various bits of previously rendered UI elements).

I was able to fix the issue for myself by forcing use of the GDK wayland backend (while running a Wayland Gnome session) — i.e. launch from a terminal with `GDK_BACKEND=wayland darktable`

## Darktable Version
```
$ darktable --version
this is darktable 4.4.2
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```

## Gnome System Details

**Hardware Information:**
- **Hardware Model:**                              ASUS PRIME Z790-A WIFI
- **Memory:**                                      64.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i9-13900K × 32
- **Graphics:**                                    Intel® Arc™ A770 Graphics (DG2)
- **Disk Capacity:**                               2.0 TB

**Software Information:**
- **Firmware Version:**                            0812
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.0
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.7-arch1-1

**Comment by FalCT60** [comment]
Thanks.
I had to revert to X11 because of heavy latency  in dt, especially with field selection.
I had to click up to four of five times before the field would be accessible.
Since I reverted back to X11, one single click is enough.
I hope that what you describe should help devs.

**Comment by FalCT60** [comment]
Newly compiled 4.6.0 and the inconvenience remains on both laptops as soon as connected to a TV, either on docking station or directly from HDMI output.
