### ISSUE TITLE
RFC: mask blending question - issue ?

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#14967]
Maybe I'm missing something but while reviewing the masking I found something strange.

To reproduce:
- Reset an image history - use one image with a uniform area to better see the effect 
- On the Exposure module add 2 drawn masks (simple circle will do) - same size - same feathering
- Use default blend mode : UNION
- Make them over each other for the feathering part to be as seen on screenshot below
- Use a +2EV exposure

See  that the area where both feathering intersect have a rather dark line in the middle.

![image](https://github.com/darktable-org/darktable/assets/467069/e6991130-753b-49d7-899c-f0e8c1064a33)

![image](https://github.com/darktable-org/darktable/assets/467069/aa9d76f8-8361-4483-bcf0-e1f913b327a1)

How is that possible?

The UNION do an fmaxf() of the blend mask, so in the middle we should have more yellow. No?

In `_combine_mask_union` we have:

```
    for(int index = 0; index < npixels; index++)
    {
      const float mask = opacity * newmask[index];
      dest[index] = fmaxf(dest[index], mask);
    }
```

Is that a bug or something I'm missing? I have tried with 4.2.x and I have the same issue. We also have a regression tests for this since quite some time... So not a recent regression if a regression at all. I just saw that because I'm using a rather strong effect on Exposure...

@ralfbrown @jenshannoschwalm : Any idea?

**Comment by jenshannoschwalm** [comment]
Not sure from memory - just phone today - this is only with feathering? If so, iirc that is using the guided filter and there is another obscure bug related to that

**Comment by jenshannoschwalm** [comment]
#14215

**Comment by dterrahe** [comment]
I suspect that the "dark line" in the middle is somewhat of an optical illusion, because the eye does not expect the impact of the feather to immediately disappear as soon as the opposing feather is the stronger one. Rather, it probably expects something closer to a summation rather than a max. But with sufficient overlap you'd have a large area that gets capped at 1, which also looks strange.

**Comment by TurboGit** [comment]
> I suspect that the "dark line" in the middle is somewhat of an optical illusion

Yes, I came to the same conclusion. See #14971.
