### ISSUE TITLE
Duplicated version number created for existing image

### ISSUE THREAD

**Issue by Dusenberg** [darktable-org/darktable#14962]
### Describe the bug

_Background_
I always create a new version (duplicate) of a base RAW for a different edit so I can trace back any final output that may result. My filenaming system is '<filename>_<version number>' where filename is composed of '<YYYYMMDD_projectname_original camera filename>'.  I use th $VERSION variable in the dt export module to ensure any output image follows this format.  This provides unique identification of every image and its derivatives across my libraries, even when intermediate tiffs are involved in say, focus stacks.

_The issue_
1)  Raw file imported into darktable March 2020 (pre-dt3.4.0)  image-id=3574. Around that time seven duplicates were created for different edits. The versions and the original raw were made into a group (id=3574)

2)  24 July 2023: created new duplicate of the image (id 3574) in dt4.2.1, deleted history from the new version and edited in darkroom. On return to lightable saw that the version number of the new duplicate was '3' - which I knew already existed for that image.  On viewing list of duplicates in Duplicate Manager, there are two entries with version = 3.  I've checked and the new duplicate '3' has overwritten the existing xmp for the previous version 3. 

3)  I accessed backup copies of the dt database and listed info from the images table for the raw image and its versions, as follows:

_pre-dt3.4.0-library.db image table extract from backup archive 2020-12-14_
select id, group_id, film_id,filename,version,max_version from images where filename = "20200325_BonallyWoods_NIK_1413.NEF" order by id;

id    group_id    film_id    filename                        version    max_version
3574    3574    135    20200325_BonallyWoods_NIK_1413.NEF    0    7
3578    3574    135    20200325_BonallyWoods_NIK_1413.NEF    1    7
3582    3574    135    20200325_BonallyWoods_NIK_1413.NEF    2    7
3583    3574    135    20200325_BonallyWoods_NIK_1413.NEF    3    7
3789    3574    135    20200325_BonallyWoods_NIK_1413.NEF    4    7
3790    3574    135    20200325_BonallyWoods_NIK_1413.NEF    5    7
3791    3574    135    20200325_BonallyWoods_NIK_1413.NEF    6    7
3792    3574    135    20200325_BonallyWoods_NIK_1413.NEF    7    7

_library.db-snp-20230722155434 from backup archive BEFORE new duplicate created_
select id, group_id, film_id,filename,version,max_version from images where filename = "20200325_BonallyWoods_NIK_1413.NEF" order by id;

id    group_id    film_id    filename                    version    max_version
3574    3574    135    20200325_BonallyWoods_NIK_1413.NEF    0    7
3578    3574    135    20200325_BonallyWoods_NIK_1413.NEF    1    7
3582    3574    135    20200325_BonallyWoods_NIK_1413.NEF    2    7
3583    3574    135    20200325_BonallyWoods_NIK_1413.NEF    3    7
3789    3574    135    20200325_BonallyWoods_NIK_1413.NEF    4    7
3790    3574    135    20200325_BonallyWoods_NIK_1413.NEF    5    7
3791    3574    135    20200325_BonallyWoods_NIK_1413.NEF    6    7
3792    3574    135    20200325_BonallyWoods_NIK_1413.NEF    7    7

_library.db-snp-20230724163328 from current backup AFTER new duplicate created_
select id, group_id, film_id,filename,version,max_version from images where filename = "20200325_BonallyWoods_NIK_1413.NEF" order by id;

id    group_id    film_id    filename                    version    max_version
3574    3574    135    20200325_BonallyWoods_NIK_1413.NEF    0    0
3578    3574    135    20200325_BonallyWoods_NIK_1413.NEF    1    3
3582    3574    135    20200325_BonallyWoods_NIK_1413.NEF    2    3
3583    3574    135    20200325_BonallyWoods_NIK_1413.NEF    3    3   ****duplicate
3789    3574    135    20200325_BonallyWoods_NIK_1413.NEF    4    3
3790    3574    135    20200325_BonallyWoods_NIK_1413.NEF    5    3
3791    3574    135    20200325_BonallyWoods_NIK_1413.NEF    6    3
3792    3574    135    20200325_BonallyWoods_NIK_1413.NEF    7    3
9744    3574    135    20200325_BonallyWoods_NIK_1413.NEF    3    3    ****duplicate

The dt database has an index, "images_filename_index" ON "images" ( "filename", "version" );  which means that a 'duplicate' is related to a particular image filename. There are two implications from this which may be relevant to the issue:

a) The index is is not unique, it allows duplicates. Therefore the database allows (and cannot trap) insertion of a new image table row with a version number that already exists for the given filename value. The fact I have a duplicate version for a filename suggests the dt code also does not trap this.

b) This index assumes filenames are unique across the whole dt database, which probably is not realistic given how cameras from the same manufacturer can generate common filenames.

While a unique id is given to each imported image by the dt db to ensure images with the same filename are permitted and can be handled, it seems the 'duplicate image' functionality does not recognise this. 

### Steps to reproduce

1) import raw image file into dt
2) create seven duplicates of the raw image using 'Create Duplicate'
3) Edit the duplicates in darkroom
4) At some point in the future, after several dt version updates, create a new duplicate for the raw file in (1)
5) Discard the history from the new duplicate and edit it in darkroom
6) Return to lightable and version number of the new duplicate is 3, which is less than the number of existing duplicates for the image, and there is pre-existing duplicate with version = 3. The xmp file has been overwritten.

### Expected behavior

DT should always allocate a unique version number when creating duplicates of an image.

### Where did you install darktable from?

OBS

### darktable version

darktable 4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21,Ubuntu 22.04 jammy

### Are you using OpenCL GPU in darktable?

Yes

**Comment by Dusenberg** [comment]
Link to pixls.us post by Bill Martz with same/similar issue: [https://discuss.pixls.us/t/duplicated-version-number-created-for-existing-image/38550/6?u=dusenberg](url)

**Comment by Dusenberg** [comment]
I have checked the history table entries in the 3 backup databases (original issue post above) for the original version 3 of image-id 3574 and the newly created duplicate version 3.  In the two databases before the faulty 'create duplicate' was performed (pre-dt3.4.0-library.db and library.db-snp-20230722155434), the history table rows for the image version are the same.  In the latest database after the 'create duplicate' (library.db-snp-20230724163328), the history table rows for version 3 of image-id 3574 is not the same as the older databases, but are the same as the new duplicate image 9744 version 3.

The 4.2.1 'create duplicate' functionality has updated both version 3 image-ids; ie not just the newly image-id.

Note that 'max_version' after the 'create duplicate' is now showing 3 instead of 8

**Comment by ralfbrown** [comment]
I think that dt only checks the highest version number recorded in its database (library.db), so particularly if running with `--library :memory:` that won't match the sidecars on disk.  The fix would be to verify that the sidecar for a new duplicate *does not* exist, bumping the version number until you get to one for which there is not yet a sidecar.

**Comment by jenshannoschwalm** [comment]
@Dusenberg are you able to check with #15426 ? I could reproduce your issue and this should fix it

**Comment by Dusenberg** [comment]
Hanno

Apologies for not replying - I've been out of action for a while.

I looked at the new code fix and it should fix the problem  - do you
still want me to try and test? I'm not fluent the build process but if
you could point me at the correct sources to use, I'll have a go.

Thanks

**Comment by jenshannoschwalm** [comment]
> I looked at the new code fix and it should fix the problem  - do you still want me to try and test?

I think i'm fine without further testing on your side. How to build?

https://github.com/darktable-org/darktable#building

but you should also be "fluent" with git usage :-)

**Comment by Dusenberg** [comment]
Thanks to all the devs who responded so efficiently to this issue. Your
efforts in improving / maintaining darktable are making it an amazing
tool and are really appreciated - I'd be stuffed without it!
