### ISSUE TITLE
Photos not available on startup on SSD

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#14979]
### Describe the bug

I run Darktable 4.4.2 on Linux Mint 21.2 with decent hardware (see below) with the photos on a M2 SSD 2TB drive.
When I start DT and double click on a photo I get the message that the photo is currently not available. If I wait a minute or so they suddenly are available? I find this a bit odd and hope that somebody can provide a hint on how to solve this?

Hardware:
CPU: AMD Ryzen 9 3900 (24) @ 3.100GH
GPU: NVIDIA GeForce RTX 2070 SUPER
Memory: 4773MiB / 32025MiB
SSD1: WD: WDS100T3X0C-00SJG0 size: 931.51 GiB
SSD2: Intel: SSDPEKNW020T8 size: 1.86 TiB

### Steps to reproduce

1 Start DT
2 click on a photo thumbnail
Error message Currently not available

### Expected behavior

should show photo

### Where did you install darktable from?

flatpak

### darktable version

41.2.2

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.2

### Describe your system?

Hardware:
CPU: AMD Ryzen 9 3900 (24) @ 3.100GH
GPU: NVIDIA GeForce RTX 2070 SUPER
Memory: 4773MiB / 32025MiB
SSD1: WD: WDS100T3X0C-00SJG0 size: 931.51 GiB
SSD2: Intel: SSDPEKNW020T8 size: 1.86 TiB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 2070 SUPER

**Comment by Nilvus** [comment]
Your issue is probably Linux related to have your disk automounted before launching darktable. So better to close it here and continue help on pixls.us forum as you begin with.
I doubt there's something to change in darktable code for such issue and this is probably related to automount external disk in your system.

**Comment by bengtfalke** [comment]
I can see the photos on the SSD disk with Pix or the file browser. That implies to me that the disk is already mounted before starting DT. If so is must be a DT problem of some kind? Is the format of the disk of any importance to DT?

**Comment by Nilvus** [comment]
So could be some DT problem. What is the format your disk? I'm not sure but on what I know and see, I'm quite sure all formats supported on a system are supported by darktable. I've already use darktable with ext3, btrfs, fat32 formats. Maybe someone else will be more precise.

**Comment by bengtfalke** [comment]
If I restart my computer and start DT the first thin I do.... the photos are not available. If I then go to the SSD with the file browser the photos shows up in the browser and also in DT. My guess is that DT don not initiate the SSD the same way as the file browers or Pix, the built in photo program in Linux Mint.
The SSD disk is shared between the two dual boot systems on this computer, Linux Mint 21.2 and Windows 11 and is formatted as NTFS.

**Comment by ralfbrown** [comment]
That sounds like an automout issue.  The file browser is triggering the automatic mounting of the partition  (whether implicitly or with an explicit request, I can't say), while darktable doesn't because it simply asks to open the image file by its full path.

**Comment by victoryforce** [comment]
> My guess is that DT don not initiate the SSD the same way as the file browers

Knowing about the specifics of the automount implementation and initiating it in some special way is not the business of application programs. darktable simply opens the file with a pathname that is known after import. If for some reason the system did not ensure the availability of this file, it is not a problem of the application program.

**Comment by bengtfalke** [comment]
Yes, I see your point and I agree. However it can be useful information if others encounter the same problems.

**Comment by bengtfalke** [comment]
Yes, I see your point and I agree. However it can be useful information if others encounter the same problems. I found the solution on the Linux Mint forums.
This is for people who to enable a second drive to auto-mount at system start up WITHOUT editing a system file by hand.

1. Open the application 'Disks' from the Mint menu. (It's under 'Accessories.')
2. In the left hand part of the window, click on the disk which contains the partition you wish to mount.
3. The partition layout of the selected disk will appear in the right hand portion of the window.
4. Select the partition you wish to auto-mount by clicking on it. The selected partition will be highlighted.
5. Optional - If you wish to immediately mount the disk, you can do so by pressing the triangular 'play' button that appears to the left below the partition display. This will NOT cause it to auto-mount on next boot.
You may unmount the partition if you wish by pressing the square 'stop' button that appears where the play button was.
6. Click the cog icon <additional partition options> and select 'edit mount options.'
7. Switch 'automatic mount options' to OFF.
8. Check the 'mount at startup' box.
9. Optional - choose a custom mount point - in the 'Mount point' box, enter the mount point. I always choose something in the /mnt directory. e.g. '/mnt/Mydiscname'
10. Optional - give your disk a nice display name. This is the name it will appear as on the desktop. Enter your chosen name in the 'display name' field.
11. Hit OK and close the disks application. The disk should automount on next boot.
