### ISSUE TITLE
Set default black level correction to zero

### ISSUE THREAD

**Issue by jandren** [darktable-org/darktable#14987]
**Is your feature request related to a problem?**
I recently got myself a A7S iii and its high dynamic range made me more aware about the weird default _black level correction_ in the exposure module. Here is the result when using + 8ev and the default _black level correction_:

![A7S08843 defualt](https://github.com/darktable-org/darktable/assets/7957113/e7495144-3262-45b1-86d3-1a7d1576aa23)

And with _black level correction_ set to zero:

![A7S08843 zero](https://github.com/darktable-org/darktable/assets/7957113/f23f60b5-79d2-4c6b-8838-7b8335c65d21)

Zero offset is less washed out and the better option here. Both examples has _profiled denoise_ enable with the chroma only preset.

**Describe the solution you'd like**
Do as the tooltip says and do use zero as the default value here. This is at least the right thing to do when using the sigmoid module. filmic should really handle this in its own module if its needed for the log operation and not here.

**Additional context**
Reason for why this tiny offset was added to begin with (log computational stability?): https://github.com/darktable-org/darktable/commit/7ffecde96a2ae164fc5d60a4cd1c07456ad43f1f

Is the stability of the tone equalizer also dependent on this offset? If so, then handle the log(zero) case in that module instead.

**Comment by jandren** [comment]
Note. I can commit time to make a PR for this if others agree with the proposed change.

**Comment by glasl** [comment]
Wow, I was noticing  this issue about an hour ago.
Stumbled upon your report while checking out the code base.

The slider description states: "(...) this should be 0% except if you want a faded look"

**Comment by TurboGit** [comment]
> Reason for why this tiny offset was added to begin with (log computational stability?):

This has been done long ago, probably before I came to dt and if I remember correctly it is just to avoid some possible wrong black level and avoiding harsh shadows.

**Comment by TurboGit** [comment]
> The slider description states: "(...) this should be 0% except if you want a faded look"

Well -0.0002 is very close to zero :)

**Comment by glasl** [comment]
True.
The 0.0002 do make a noticeable difference though.

**Comment by TurboGit** [comment]
> The 0.0002 do make a noticeable difference though.

I have tried in many pictures CR3, NEF, DNG and I have yet to see a different between 0 -0.0002, I have even tested with the snapshot and looking with close zoom on darker areas. Maybe this makes a difference on some picture but not something common to my experiences.

**Comment by glasl** [comment]
The same default value is used by filmic rgb 

> Wow, I was noticing this issue about an hour ago. Stumbled upon your report while checking out the code base.
> 
> The slider description states: "(...) this should be 0% except if you want a faded look"
> 
> I'm using the A7 mark 1.

Sorry, I actually missed the topic of the **exposure** module:

By 'slider description' I was referring to the same default value beeing used by the **filmic rgb** module:
--> display --> target black luminance
where it also makes a slight difference.

This will add up to the default value in the exposure module i guess.

I'll gather some examples tomorrow.

**Comment by jandren** [comment]
Yes the difference is minimal in most cases.

Noticed my link to the original commit that introduced the change didn't get attached properly added it to the issue.
Its this commit from June 2020 by aurelien https://github.com/darktable-org/darktable/commit/7ffecde96a2ae164fc5d60a4cd1c07456ad43f1f

I'm so far unable to find any PR, issue or discussion about the change.

It strikes me as mostly a hack to solve the issue with complaints about crushed shadows in filmic back then.

**Comment by SoupyGit** [comment]
My memory is a bit hazy, but I seem to recall it was done to avoid black clipping before later modules (like input color profile, or perhaps filmic). If possible, perhaps an alternate option would be to set it at 0 by default and have an auto button beside it which automatically sets it to a value that avoids black clipping.

**Comment by todd-prior** [comment]
> Yes the difference is minimal in most cases. But It strikes me as mostly a hack to solve the issue with complaints about crushed shadows in filmic back then.
> 
> Noticed that my link to the original commit that introduced the change didn't get attached properly added it to the issue. Its this commit from June 2020 by aurelien [7ffecde](https://github.com/darktable-org/darktable/commit/7ffecde96a2ae164fc5d60a4cd1c07456ad43f1f) I'm so far unable to find any PR, issue or discussion about the change.

I actually have noticed that for me the optimal setting is one to a few scroll wheel clicks to a positive number.. There is some threshold that you hit and to me the display just become markedly sharper and vibrant. THis can happen without pushing the blacks to a warning level. I dont know if it is just something with my monitor and or my monitor profile but it can be like night and day in terms of a sort of instantaneous shift from a bit washed out to something resembling a really nice dehazing with very little correction ...

**Comment by jandren** [comment]
I have spent some time on looking closer at this since my original post last week. Trying to answer the following to questions:
1. What is my camera's actual black point?
2. Would this default bias help with avoiding negative RGB values -> out of camera gamut problems?

Here is what I have done to answer that. I first captured dark images (lens cap on and short shutter) on three cameras that I had access to, Canon 5D mark ii, Nikon D750, and Sony A7s iii. I then plotted the histogram per color channel for a set of common iso values, 200, 3200, and 12800. I finally added the black point provided by rawpy* as a grey vertical line and the resulting black level due to the default black level compensation in the exposure module as a purple vertical line.

*libraw python wrapper

![Canon iso 200](https://github.com/darktable-org/darktable/assets/7957113/e94bd9d0-38a0-4b29-a309-32e99fdbd601)
![Canon iso 3200](https://github.com/darktable-org/darktable/assets/7957113/09dad7d1-ac6f-4cb4-9acb-ceed194e6883)

![Nikon iso 200](https://github.com/darktable-org/darktable/assets/7957113/721143b4-2c2d-4341-946a-f8d8db2a73b0)
![Nikon iso 3200](https://github.com/darktable-org/darktable/assets/7957113/fd50c169-5e17-41b3-a06c-5b9df4aa658d)
![Nikon iso 12800](https://github.com/darktable-org/darktable/assets/7957113/758a2f02-6399-4dcd-bd65-4846ca53de7d)

![Sony iso 200](https://github.com/darktable-org/darktable/assets/7957113/9b189dfd-6f65-4186-b5e0-52183dcf0f49)
![Sony iso 3200](https://github.com/darktable-org/darktable/assets/7957113/0fe9ae80-42b5-440d-8d80-0125cf2c9ab2)
![Sony iso 12800](https://github.com/darktable-org/darktable/assets/7957113/7b7278b7-4333-4271-9bd0-eb596882c9c6)

Assuming the true black level is the peak of this distribution (this is what for example Siril estimates on a per pixel basis when you included dark frames in your deep sky stacking). Then my answers based on that data for the above questions are:
1. All three cameras are pretty close to the stated black level but fractional adjustments could be made for low iso images and a bit larger for the higher iso values. The default black level compensation will make the used black level estimate worse in all of the studied cases.
2. The applied bias will probably save users from clipping pixels when using low iso values on cameras with modern sensors but any picture taken at a bit higher iso or with a older will still be likely to have dark pixels go negative as the bias is much smaller than the observed black level variation. So this black level bias isn't really much of a general method to safe guard black clipping for later modules in the pipeline as far as I can tell.

@todd-prior would be interesting to analyze one of your raws as well and see how it looks from a signal perspective if you want to send me a black raw file or two.

**Comment by jandren** [comment]
> > The slider description states: "(...) this should be 0% except if you want a faded look"
> 
> Well -0.0002 is very close to zero :)

Note that it is

-0.0002 * 2^exposure

I.e it's a much more noticable

-0.0512 at +8 ev

**Comment by todd-prior** [comment]
> @todd-prior would be interesting to analyze one of your raws as well and see how it looks from a signal perspective if you want to send me a black raw file or two.

Sadly, I am working from a phone these days. I have been thinking about a new camera for some time. I looked with interest when the Nikon Z6 came out but never pulled the trigger then the Lumix S5II came out then Canon came with R7, now fuji with the X-S20 and Sony the 6700.... I don't really do any planned or targeted shooting so its really things that I see or am doing while out and around or on the bike and or hiking and the phone has been just too easy to carry compared to camera kit... Retirement is coming soonish so I need a hobby.... that will likely make me take the plunge.... THanks for the creative analysis....

**Comment by jandren** [comment]
@TurboGit and @SoupyGit you might be interested in the extra research I put into the topic.

**Comment by HSUfineprint** [comment]
I will vote for yes on this. I did find the black is not black sometimes, then it needed additional manual adjustment. It's annoying.
