### ISSUE TITLE
Export temporary style remains in history

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#14988]
### Describe the bug

I noticed this bug a few days ago but I could not replicate it until today. I use a style during export to temporary apply a watermark if desired. I use the append history. I've used this same style/approach for more than two years.  

The part that is confusing is that it only happens if you use the export from the lighttable and it does not happen if you use the export from the darkroom. I kept trying from the darkroom, but it only happens from the lighttable.

### Steps to reproduce

1. Create a style that only applies a watermark (or maybe anything else) but I only tested with watermark module.
2. Setup the export module to export using the style and in append mode.
3. Export from the lighttable view.
4. After export, go to the darkroom for the image.
5. Observe the watermark visible in the image plus in the history.

If you do the same steps but export from the darkroom, it works correctly.

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0~git199.ed1fe531

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38 KDE

### Describe your system?

X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA 3060 12GB 535.86.05

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

No Lua scripts.

**Comment by wpferguson** [comment]
git bisect returns 162c8e384220870abfbbdac7f7b9187d53b27a67

@jenshannoschwalm 

We should pause history autosave during export with a style.

**Comment by jenshannoschwalm** [comment]
Not sure what's happening here

**Comment by wpferguson** [comment]
Could it be the 10 sec autosave going off during the export when the style is applied?

**Comment by wpferguson** [comment]
If I set autosave to 0 in preferences, it doesn't happen

**Comment by jenshannoschwalm** [comment]
> Could it be the 10 sec autosave going off during the export when the style is applied?

Yes and sure. I confess i did't check this temporary history changing. It fires a database/history save while exporting but doesn't know & thus correct after that history change get's "reverted". Not sure though how to check for that. Only enable the auto-write in darkroom mode would be the first idea.

**Comment by TurboGit** [comment]
That's also a point I forgot when reviewing. Export with style do change history.

> Only enable the auto-write in darkroom mode would be the first idea.

You can still export from darkroom.

But those style's history do get removed after export, so it should be ok? There is a bad interaction that I'm still not sure to understand.

**Comment by gi-man** [comment]
I'm away from the computer until next week, but I'm very confident my exports take 1-2sec for each image. This is less than the 10 sec auto save default.

**Comment by gi-man** [comment]
PR merged this am. Closing.
