### ISSUE TITLE
Show Picture in Finder

### ISSUE THREAD

**Issue by 76mrmario** [darktable-org/darktable#14983]
I want see Picture in Finder or in Explorer for Options to send it per Mail or Airdrop on Mac.
Thanks!

**Comment by gi-man** [comment]
1) Please use the Issue Template
2) Your issue is invalid. You need to export the images from darktable for them to show up in the filemanager (eg. Finder). 

Please close this issue.

**Comment by 76mrmario** [comment]
use template
