### ISSUE TITLE
Can't compile master on last commit (but I can on previous commit)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#14980]
### Describe the bug

Can't compile darktable since last commit from @Solarer.

See error below:

```
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/dtgtk/thumbnail.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/dtgtk/thumbnail_btn.c.o
[ 52%] Building C object bin/CMakeFiles/lib_darktable.dir/dtgtk/thumbtable.c.o
/home/nilvus/Projets/darktable/src/dtgtk/culling.c: In function ‘_thumbs_compute_positions’:
/home/nilvus/Projets/darktable/src/dtgtk/culling.c:1692:26: error: ‘true’ undeclared (first use in this function)
 1692 |         create_new_row = true;
      |                          ^~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1594 : bin/CMakeFiles/lib_darktable.dir/dtgtk/culling.c.o] Erreur 1
gmake[2]: *** Attente des tâches non terminées....
gmake[1]: *** [CMakeFiles/Makefile2:2489 : bin/CMakeFiles/lib_darktable.dir/all] Erreur 2
gmake: *** [Makefile:156 : all] Erreur 2
```

### Steps to reproduce

Just compile darktable (I use since years same script below) and see error.

```
### Building manually

#!/bin/sh

cd /home/nilvus/Projets/darktable
rm -rf build /opt/darktable

# if it's a new folder source code, think about adding this line after a git submodule init: 'git config submodule.src/tests/integration.update none'

git pull
git submodule update
./build.sh --prefix /opt/darktable --build-type Release --install

exit 0
```

### Expected behavior

darktable should compile

### Commit

66d4bf2

### Where did you install darktable from?

darktable.org

### darktable version

Last master

### What OS are you using?

Linux

### What is the version of your OS?

Debian Sid

### Are you using OpenCL GPU in darktable?

None

**Comment by Solarer** [comment]
@Nilvus 
Sorry about that. I don't know why it is compiling fine on my machine using the same script. I also deleted the build folder.
Please try to build with my fix before accepting it. Just to be extra sure that there are no other issues!

**Comment by TurboGit** [comment]
Just see this now, issue already reported by @s7habo and fixed now.

**Comment by TurboGit** [comment]
@Solarer : For the record this was last remaining instance of using true (C++) instead of TRUE.

**Comment by Nilvus** [comment]
Thanks guys for the quick fix. This works now.
