### ISSUE TITLE
FR: lightroom sort by size

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#14986]
**Describe the solution you'd like**

It would be nice to be able to sort images by `file size`

**Comment by TurboGit** [comment]
Nice... not sure, what would be the value for a picture oriented software?

**Comment by naisanzaa** [comment]
> Nice... not sure, what would be the value for a picture oriented software?

because identical images will have the same file size, but ma be in different directories.

**Comment by TurboGit** [comment]
> because identical images will have the same file size, but may be in different directories.

I really doubt this to be stable rule!

**Comment by naisanzaa** [comment]
> > because identical images will have the same file size, but may be in different directories.
> 
> I really doubt this to be stable rule!

It's okay that it's not for you. You haven't had this use case multiple times to require it.

**Comment by jenshannoschwalm** [comment]
> You haven't had this use case multiple times to require it.

I would like to understand your **precise** issue. Do you want to check for duplicates? duplicates with different filenames? Or check for diskspace used?

**Comment by naisanzaa** [comment]
> > You haven't had this use case multiple times to require it.
> 
> I would like to understand your **precise** issue. Do you want to check for duplicates? duplicates with different filenames? Or check for diskspace used?

Duplicates with different filenames and in different directories.

**Comment by ptilopteri** [comment]
then why not utilize a file system duplicate finder app rather than require a photo application to do system file service work?  removing duplicate files, especially with different names doesn't seem to be a photo application job, ie: developting photo files.

**Comment by jenshannoschwalm** [comment]
The chance to get some sort of "duplicates" checker included in dt "core" by any of the active devs is likely zero. Maybe you can use the dt lua interface or a tool like `fdupes` for that.

**Comment by naisanzaa** [comment]
> The chance to get some sort of "duplicates" checker included in dt "core" by any of the active devs is likely zero. Maybe you can use the dt lua interface or a tool like `fdupes` for that.

That's why I'm just asking for a sort on file size. I'll just eyeball it as I'm going through rejecting images.

**Comment by wpferguson** [comment]
File size isn't stored in the database, so it's not available to sort on.

**Comment by Solarer** [comment]
I can see multiple use cases for this
* separating raw files from non-raws
* finding panorama images
* detecting some kinds of file corruption
* finding accidentally imported thumbnails
* finding jpeg exports with a certain quality (that is file size)

While most of this can be done by pixel size or file extension, you always have edge cases of file types that you did not know you had or extreme aspect ratios.
File size is also something very intuitive 😉
