### ISSUE TITLE
Share Pictures

### ISSUE THREAD

**Issue by 76mrmario** [darktable-org/darktable#14984]
**Is your feature request related to a problem? Please describe.**
share Pictures to someone 

**Describe the solution you'd like**
Share Button with Option for Mail, Airdrop, Instagram, Flickr 

**Alternatives**
Show In Explorer and use OS Function for Share

**Additional context**

**Comment by ralfbrown** [comment]
darktable used to have "export to Flickr" and the like, but the APIs kept changing faster than devs could keep up....  They were removed when at least one of the services changed their API ToS to include things that darktable was unable to comply with.

**Comment by 76mrmario** [comment]
Hello,Thank you for your answer.What about to show Picture in Explorer / Finder then use OS function for Sharing?Greetings from Germany.PS: Thank you for great Software.Nachricht von unterwegs.Am 02.08.2023 um 23:56 schrieb Ralf Brown ***@***.***>:﻿
darktable used to have "export to Flickr" and the like, but the APIs kept changing faster than devs could keep up....  They were removed when at least one of the services changed their API ToS to include things that darktable was unable to comply with.

**Comment by MStraeten** [comment]
there's a lua script for that: https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/contrib/openinexplorer

**Comment by 76mrmario** [comment]
Hello,unfortunately the Lua Option not appear on left side menu :-/ What can I do?Thanks!Nachricht von unterwegs.Am 03.08.2023 um 16:06 schrieb Martin Straeten ***@***.***>:﻿
there's a lua script for that: https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/contrib/openinexplorer

**Comment by victoryforce** [comment]
> unfortunately the Lua Option not appear on left side menu :-/ What can I do?

@76mrmario You did not provide information about your system (macOS? Linux? Windows?) and the origin of the darktable installation (official release? self-built? package from a Linux distro?) .

Basically, if you don't see the script installer module at all in the left panel, it's a sign that your darktable was built without Lua support. But this is a problem with your specific build and is not related to the raised issue, so I suggest you close it.

**Comment by difrkaguilar** [comment]
> Show In Explorer and use OS Function for Share

I posted a FR #11246 related to this function (Open the item(s) location after export option in export module) but apparently it is not a good idea because of portability problems in the different operating systems.

**Comment by victoryforce** [comment]
Some of the options you wanted (uploading to commercial services such as Flickr and Instagram) were once implemented but are no longer supported for the reason explained above in the comment.

Email sharing is implemented as a target in the export module.

As for features like Airdrop that are supported by the platform, it's hard to find a rationale for trying to push them into an application, let alone a cross-platform one.

In view of all the above, I'm closing this feature request.
