### ISSUE TITLE
duplicate "folders" created in database when importing 3089 images

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#14985]
### Describe the bug

When importing thousands of images, duplicate folders are created in the database, as if there were two identical folders (there isn't). 

I'm guessing there is a race condition. 

### Steps to reproduce

1. import 3089 images
2. duplicates created in database
3. see screenshot

### Expected behavior

not.

### Logfile | Screenshot | Screencast

<img width="282" alt="Screenshot 2023-08-01 at 02 32 02" src="https://github.com/darktable-org/darktable/assets/58240560/6845563d-0182-4831-b618-e3ebfc954b9e">

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

14.0 Beta (23A5301g)

### Describe your system?

2021 Macbook Air M1 16GB

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
I routinely import thousands of images (4170 on 7/24) without any problems.  

What steps did you use to do the import?

**Comment by naisanzaa** [comment]
> I routinely import thousands of images (4170 on 7/24) without any problems.
> 
> What steps did you use to do the import?

1. Click import foldet
2. Select recursive
3. Import
