### ISSUE TITLE
Crash when changing lens correction target geometry

### ISSUE THREAD

**Issue by krekr** [darktable-org/darktable#14995]
### Describe the bug

Program crashed when selecting a lens correction output format

### Steps to reproduce

open a .dng from a Parrot drone, select a canon lens (8-15mm) in the lens corrections, target geometry "Thoby fisheye" > instant reproducible crash

### Expected behavior

not crash :)

### Logfile | Screenshot | Screencast

https://pastebin.com/wTRjyg3n

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Macos

### What is the version of your OS?

12.6.8 (21G725)

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

awesome program, was just testing it out as an alternative :)

**Comment by krekr** [comment]
You're right, my title wasn't very helpful :)

**Comment by jenshannoschwalm** [comment]
Could you share a raw and used xmp file? Also a log “-d common" would be good.

**Comment by krekr** [comment]
[Archive.zip](https://github.com/darktable-org/darktable/files/12249420/Archive.zip)
you mean to use the command line arguments “-d common"? And where would I get the log?

**Comment by jenshannoschwalm** [comment]
Ok, on linux using cpu code doing what you suggested resulted in cpu "running wild on all cores because of
```
     6.4417 modify roi IN              [full]         flip                   (   0/   0)  830x 660 scale=0.2093 --> (   0/   0)  660x 830 scale=0.2093 
     6.4417 modify roi IN              [full]         ashift                 (   0/   0)  857x 694 scale=0.2093 --> (   0/   0)  830x 660 scale=0.2093 
     6.4426 modify roi IN              [full]         lens                   ( 476/   0)    4x 694 scale=0.2093 --> (   0/   0)  857x 694 scale=0.2093 
     6.4426 modify roi IN              [full]         demosaic               (2272/   0)   19x3320 scale=1.0000 --> ( 476/   0)    4x 694 scale=0.2093 
     6.4426 modify roi IN              [full]         highlights             (   0/   0) 4096x3320 scale=1.0000 --> (2272/   0)   19x3320 scale=1.0000 
     6.4426 pixelpipe data: full       [full]                                (   0/   0) 4096x3320 scale=1.0000 --> (   0/   0) 4096x3320 scale=1.0000 
     6.4426 pixelpipe process CPU      [full]         rawprepare             (   0/   0) 4096x3320 scale=1.0000 --> (   0/   0) 4096x3320 scale=1.0000 IOP_CS_RAW
     6.4465 pixelpipe process CPU      [full]         temperature            (   0/   0) 4096x3320 scale=1.0000 --> (   0/   0) 4096x3320 scale=1.0000 IOP_CS_RAW
     6.4516 pixelpipe process CPU      [full]         highlights             (   0/   0) 4096x3320 scale=1.0000 --> (2272/   0)   19x3320 scale=1.0000 IOP_CS_RAW
     6.4730 opposed chroma cache CPU   [full]         highlights             (   0/   0) 4096x3320 scale=1.0000 --> (2272/   0)   19x3320 scale=1.0000  red: -0.002459 (17928), green: 0.241908 (162477), blue: -0.087348 (28559) for hash=3d8781891ab408fc 
     6.4736 pixelpipe process CPU      [full]         demosaic               (2272/   0)   19x3320 scale=1.0000 --> ( 476/   0)    4x 694 scale=0.2093 IOP_CS_RAW -> IOP_CS_RGB

```
