### ISSUE TITLE
Crash When Using Diffuse and Sharpen

### ISSUE THREAD

**Issue by jinzapper** [darktable-org/darktable#14997]
### Describe the bug

When editing Sony ARW files (A7RV, lossy comp) or DNG, enabling Diffuse and Sharpen will crash darktable.

### Steps to reproduce

1.) Open darktable
2.) Open one ARW file or DNG file
3.) Enable Diffuse or Sharpen
4.) Edit anything
5.) Crash with no dialogs

### Expected behavior

No crash

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11, 22H2, 22621.1992

### Describe your system?

Windows 11, 22H2, 22621.1992
NVidia 4080 (laptop), Studio Driver 536.67
Intel 13900H, 32GB DDR5, 4800MHz 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 4080 (laptop), Studio Driver 536.67

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Need also help on how to get the crash log. Can't find where the log file goes. Already did "darktable.exe -d all".

**Comment by MStraeten** [comment]
have a look at `C:\Users\<your user>\AppData\Local\Microsoft\Windows\INetCache\darktable`

**Comment by jinzapper** [comment]
[darktable-log.txt](https://github.com/darktable-org/darktable/files/12257569/darktable-log.txt)
Found it. I have attached the log. Thanks @MStraeten !

**Comment by gi-man** [comment]
Your log file shows 4 GPU drivers. I think some are not valid since it is a Microsoft duplicate. Try removing the extra and updating the driver's for the Intel card.

Also, try with performance settings set to none. You have a very powerful card and should not needed it.

**Comment by jinzapper** [comment]
I disabled the intel display adapter by turning on the MUX switch. Both are now using the latest versions and still experiencing the same crash. Also, the multiple drivers correspond to different devices..

**Comment by gi-man** [comment]
Can You post an update on darktable-clinfo output?

**Comment by jinzapper** [comment]
If you mean, clitest, I have attached the output.
[clitest.txt](https://github.com/darktable-org/darktable/files/12268771/clitest.txt)

**Comment by jinzapper** [comment]
> Can You post an update on darktable-clinfo output?

if you mean clitest, I have attached the output. 
[clitest.txt](https://github.com/darktable-org/darktable/files/12268772/clitest.txt)

**Comment by gi-man** [comment]
Yes, cltest.

You still have 3 extra GPU drivers loading and available to darktable. They are Microsoft drivers.
