### ISSUE TITLE
LUA Skript Installer doesn't appear

### ISSUE THREAD

**Issue by 76mrmario** [darktable-org/darktable#15003]
### Describe the bug

When darktable 4.4.1 is started it should display the lua scripts installer module if the lua scripts are not installed, but it does not.

### Steps to reproduce

1. Start darktable 4.4.1
2. No lua scripts installer module appears in the lower left panel

### Expected behavior

lua scripts installer should be present

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Mac

### What is the version of your OS?

Ventura

### Describe your system?

16 GB Ram i7

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

Intel Iris Plus Graphics 655 1536 MB

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

reproducable

**Comment by wpferguson** [comment]
Do you have git installed on your system?  Also check in preferences->Lua options and make sure that **lua scripts installer dont show again** is not checked

**Comment by 76mrmario** [comment]
Deleting the .config/darktable Folder and downgrade to 4.0.1 and reimport pictures fix the issue. Nachricht von unterwegs.Am 03.08.2023 um 18:31 schrieb wpferguson ***@***.***>:﻿
Do you have git installed on your system?  Also check in preferences->Lua options and make sure that lua scripts installer dont show again is not checked

**Comment by MStraeten** [comment]
you might check, if there's a `luarc` file in your `~/.config/darktable/` directory.
if it is, check if it contains the line `require "tools/script_manager"`
if it doesn't create it ...

**Comment by Marius963** [comment]
Update: switched theme to "darktable" and restarted (I like more visible font) and script manager option disappeared again. Switched back to elegant gray (default) and restarted and it reappeared. Replicated twice.
