### ISSUE TITLE
OneDrive files trashing or permanent deletion is not working using delete(trash) on MacOS Monterey

### ISSUE THREAD

**Issue by jeugregg** [darktable-org/darktable#15015]
### Describe the bug

"delete (trash)" is not working with files from OneDrive cloud folder (integrated in Finder explorer) on MacOS : 
- location example : "/Users/my_name/Library/CloudStorage/OneDrive-Personnel/Images"
- try to delete : Trashing error
- "delete permanently" : deletion error

Actually, we cannot move to trash from finder directly, but just delete permanently is possible : Onedrive move the deleted files to the ondedrive online recycle bin.
Darktable is not able to do as Finder do : delete permanently

I am on Monterey MacOS.
Maybe MacOS Ventura is solving this issue? 
as you can see here : https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-mac-local-files-delete-immediately/279e0a78-c858-4bac-b9be-d5ba002ffc01?page=5

### Steps to reproduce

1. Select image to delete
2. Clic on Selected images / images/delete(trash)
3.  error prompt appears :  trashing error
4. select delete permanently
5. error prompt appears: deletion error 
6. abort

### Expected behavior

move to trash or choice to delete permanently

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 12.6.5

### Describe your system?

MacBook Pro M1 Pro 32 Go

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by MStraeten** [comment]
darktable uses the default os methods - so you might adress it at  apple or microsoft…

**Comment by jeugregg** [comment]
Yes. sure. but I will update OS before.
In the meanwhile, maybe someone have the same issue?

**Comment by Nilvus** [comment]
I doubt you will see many users who use OneDrive to save their images and use darktable. darktable team probably can't do anything as @MStraeten explains. I let that open few days anyway.
