### ISSUE TITLE
Olympus em1 mark II presets

### ISSUE THREAD

**Issue by emagin-es** [darktable-org/darktable#15026]
### Describe the bug

When I import the images from my camera, I can see correctly the thumbnails. But when I open one of them, the presets applied are wrong and the image is not even similar to the JPG version.
I tried with the version 4.2.1 and 4.4.2 in linux, I tried also in windows but I dont remember the version.
Some time ago I didnt have this problem, I dont know when it started happen.
Also, if I apply manually the presets of olympus, the result is even worst...

### Steps to reproduce

Import image and open it in darkroom.

### Expected behavior

Presets are applied to the image to get something similar to JPG

### Logfile | Screenshot | Screencast

lightroom
![image](https://github.com/darktable-org/darktable/assets/34460662/54ebbc40-5e0f-414c-86d6-50a915b0adda)
darkroom
![image](https://github.com/darktable-org/darktable/assets/34460662/bc0fdf0e-539a-4d21-a038-f2f7ac543692)
JPG
![image](https://github.com/darktable-org/darktable/assets/34460662/aa59e4b5-6e4f-450b-9f28-ed5e9102b437)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1-4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[_8040004.zip](https://github.com/darktable-org/darktable/files/12283221/_8040004.zip)

**Comment by gi-man** [comment]
What you experienced is normal and the default behavior of darktable. It is described in the manual. https://docs.darktable.org/usermanual/4.2/en/overview/workflow/process/

With dt 4.4.2, You can create automatic presets to each of the modules that will yield a almost finished image to your liking.

**Comment by emagin-es** [comment]
> Most Raw software goes to great lengths to reproduce the look of standard camera JPEGs out of the box. While this can be useful (if you only want to make very minor adjustments to the camera’s rendition of an image) we assume that you are using a Raw editor to make the image your own, and that the camera does not know how to do this.

That is exactly what I want. I want "the look of standard camera JPEGs out of the box", as "Most Raw software" does, to "make very minor adjustments". I like the color of Olympus cameras, and I'm colorblind, so I will certainly do a worst color processing.
Also, I don't want to lose a lot of time editing each image. 
I believe this is a wrong approach, specially for beginners. I don't understand why you changed one way for another, instead of allowing both. 

Anyway, I will try to install a previous version of the software or use another one.
Thanks for your fast answer.

**Comment by TurboGit** [comment]
> Also, I don't want to lose a lot of time editing each image.

I love this one. If you think developing a pictures is losing time then just look for another software.

**Comment by emagin-es** [comment]
Perhaps I have not expressed myself exactly. I think it is a waste of time to have to do the same actions over and over again or that each person has to create custom presets simply to have a result similar to what the camera already generates.
I think that makes the software more difficult to use and creates a barrier for people just starting out.
But hey, after all, you are the ones who are doing it and maintaining it, I suppose that if the rest of the users are satisfied with the change and I am the only one who thought it was a bug, it will be my problem. 
I will try to learn more about how to use your software and if I am not able I will have to look for another alternative.

**Comment by Nilvus** [comment]
So you just misunderstood what is the goal of darktable. darktable is made for photographers who want to process their RAW entirely without being influenced by what their camera produced by the jpg. It's a designed choice to not propose jpg rendering default.

If JPG default rendering is what you search, so darktable is just not for you.

**Comment by ptilopteri** [comment]
that is why you can create presets and styles and share them with other users of the same
camera.  camera manufacturers do not advertise/share their proprietary methods of *developing*
their out-of-camera jpgs.
