### ISSUE TITLE
Color Calibration module error

### ISSUE THREAD

**Issue by pikmeir** [darktable-org/darktable#15020]
### Describe the bug

The color calibration module will return "CCT: Undefined" when I try using the eyedropper. All other functions work normally besides the eyedropper.

### Steps to reproduce

1. Load up any file (RAW or other).
2. Click the eyedropper in the color calibration module.

### Expected behavior

Darktable should let me set the White Balance

### Logfile | Screenshot | Screencast

![t3f48hkmrz3b1](https://github.com/darktable-org/darktable/assets/24483487/7cd30b79-2c99-448a-8ef1-fff35310f4c0)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home 64-bit

### Describe your system?

Intel Core i7-9750H + 8GB GDDR6 NVIDIA GeForce RTX 2070 Max-P

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

8GB GDDR6 NVIDIA GeForce RTX 2070 Max-P

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Happens on all darktable versions that I've tried (since 3.8 to current).
Same effect happens with any image format I've tried (Panasonic RAW, Canon RAW, PNG).
Happens with any photo, whether on a new photo or one with edits. I've never seen it not happen yet.

**Comment by sg456** [comment]
Just to confirm, is this happening when you click on the eyedropper button, or when you then click on the image to set the point to pick from from?

**Comment by sg456** [comment]
One more idea, have you tried renaming your config folder (this one C:\Users\USER\AppData\Local\darktable - replace USER with your user name) to force dt to start with default settings?

**Comment by pikmeir** [comment]
> Just to confirm, is this happening when you click on the eyedropper button, or when you then click on the image to set the point to pick from?

It happens right when I click the eyedropper button, which automatically also selects the whole image first.

**Comment by sg456** [comment]
Seems very unusual - I'm not sufficiently technical to have any further ideas! But I've been running dt from 3.8 up to the nearly current 4.4 at the moment, on Win 11, and don't think I've seen that happen...

**Comment by pehar1** [comment]
"CCT: undefined" means that it is not possible to calculate the approximated color temperature from the image data. You need to select a custom illuminant from the menu :

![custom-illuminant](https://github.com/darktable-org/darktable/assets/104291381/4f51b106-4d5e-4b41-a269-db3dda4a6c89)

**Comment by KarlMagnusLarsson** [comment]
Hello @pikmeir 

Have you tried the suggestion from @sg456?  
> One more idea, have you tried renaming your config folder (this one C:\Users\USER\AppData\Local\darktable - replace USER with your user name) to force dt to start with default settings?

I am asking, because I have had exactly the same eyedropper lock and it looked the same as your screenshot-

I am on Linux Debian, but that might not be important here. What worked for me was to force darktable to start with default settings by renaming the darktable configuration file. Darktable will create a new default config file when restarting. On Windows the config is here: C:\Users\USER\AppData\Local\darktable - replace USER with your user name.

**Comment by pikmeir** [comment]
> One more idea, have you tried renaming your config folder (this one C:\Users\USER\AppData\Local\darktable - replace USER with your user name) to force dt to start with default settings?

Thank you! For some reason this fixed it. I'd previously tried uninstalling and reinstalling, but renaming that folder and letting it re-make it solves this issue.

**Comment by pikmeir** [comment]
> Hello @pikmeir
> 
> Have you tried the suggestion from @sg456?
> 
> > One more idea, have you tried renaming your config folder (this one C:\Users\USER\AppData\Local\darktable - replace USER with your user name) to force dt to start with default settings?
> 
> I am asking, because I have had exactly the same eyedropper lock and it looked the same as your screenshot.
> 
> I am on Linux Debian, but that might not be important here. What worked for me was to force darktable to start with default settings by renaming the darktable configuration file. Darktable will create a new default config file when restarting. On Windows the config is here: C:\Users\USER\AppData\Local\darktable - replace USER with your user name.

Yes it seems @sg456's suggestion was what was needed. Reinstalling didn't work, but renaming the folder and letting it re-create was the solution!
