### ISSUE TITLE
FR: Dither or Posterize module with a mask - could the posterization be based on just the mask area, not the whole image pls

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#15023]
Ubuntu 20.04,  DT 4.4.2 Flatpak,  no GPU
If you draw a mask in this module, and select a posterization preset, the effect is limited to the mask, which of course is correct.
However, the posterization itself is calculated from the whole image, not the masked area.  This makes the module less useful in my opinion.
If the posterization was calculated only from the masked pixels, I think it would be a lot better and allow much more in the way of creative possibilities.  For example in a landscape you could treat the sky one way, hills another way, and the foreground differently again, by using 3 instances each with its own mask.

**Comment by ralfbrown** [comment]
Posterization is calculated on a pixel-by-pixel basis.  All the module is doing is (for every pixel individually) taking each color channel, dividing the range 0.0-1.0 into N parts, and selecting the representative value for each of the color channels in the pixel.

If you want different posterization in different areas without also changing the number of levels per channel, you'll need to apply some region-specific color or tone edits before applying the posterization.  If you want to change the output colors, you'll need to add an instance of a color/tone editing module after the posterization.

**Comment by RawConvert** [comment]
So you closed this without allowing for any further discussion, nice.
The workaround you suggest is cumbersome and limited.
What you've implemented appears rather basic, if you don't want to develop it further then of course that's your right.  However in #14329 where you said it resolves #13470, it clearly doesn't.
Also I think the module misoperates with a raster mask, I was going to check that out properly and post a bug report, but I won't bother if it's just going to get closed off straight away.

**Comment by Dannny1** [comment]
Probably same issue like with blurs module, it's quite limiting there too.
https://github.com/darktable-org/darktable/issues/13838

**Comment by ralfbrown** [comment]
The problem is that the processing module has no access to the blend mask (blending is effectively a separate module which has one instance per maskable processing module instance).  For rhe reasons mentioned in regards to Blurs, doing what you have in mind will require a substantial redesign of the pixelpipe as well a rewrite of the processing module which will either slow it down considerably whether or not masked, or introduce a separate code path which will need to be maintained in the future.

**Comment by RawConvert** [comment]
Ok, I see, no access to the mask.
Would it be possible/doable to have some controls in the module so you could set the bounds.
So whereas at the moment it posterizes between "0 to 1", you'd be able to make it "a to b".
E.g. you have a bright-ish grey sky but with detail.  Suppose working with Lightness.  At the moment it will probably go to pure white.  But with adjustment controls, you could set say [0.8, 1] and get a pretty dramatic effect.
