### ISSUE TITLE
A couple of suggestions about improvement the functionality of global color picker

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#15021]
I am playing with color harmonies and currently using global color picker extensively.

Through this work I have noticed a couple of things that could possibly improve the use of global color picker.

1. If you have a list of live samples it would be nice to reorganize them in the list, to change the order, for example to see different color combinations. You can of course delete them and recreate them in the appropriate order, but this is cumbersome if you have a lot of live samples.

![image](https://github.com/darktable-org/darktable/assets/38165484/4663ed99-ec50-4889-a178-bb236eb57d94)

2. When you create a live sample, you can't change it anymore; (you can't change its position with the cursor on the canvas) but you have to create a new live sample.  It would be nice to be able to _correct_ the position of existing live samples on the canvas.

We currently have two very useful options that can be turned on and off as needed: 
display samples on image/vectorscope and
restrict scope to selection

3. It would also be nice to have option to display live samples _also in parametric masks of active module_. It's not about using them for the masking itself but rather as an orientation/indicator to see where the corresponding color could be found in the respective parametric mask.  For example, you can use already existing highlighting function - if you hover over the live sample with the mouse, it will be highlighted not only on the canvas and vectroscope, but also in the corresponding place in the parametric mask of the active module:

![image](https://github.com/darktable-org/darktable/assets/38165484/fd9305bc-3d4b-4982-8134-e64d309901c5)

**Comment by dterrahe** [comment]
Re. 1 & 2. No, you can't edit or move existing samples. You _can_ select them, by right-clicking (either on the color swab in the library list or, when "display samples on image" is enabled, within their dotted outline on the image, and then grab and move their corners to create a new one based on them, which may make it somewhat easier to make small adjustments or recreate all of them in a new order and then delete all the original ones.
Re 3. The same right-clicking will also select a sample area when the parametric mask color picker is active.

**Comment by s7habo** [comment]
> Re 3. The same right-clicking will also select a sample area when the parametric mask color picker is active.

I did not know that. Very nice. I have just tried it out.
