### ISSUE TITLE
exif.cc reports invalid focus distance for images from Nikon Z cameras with native Z-mount lenses

### ISSUE THREAD

**Issue by Matthias1102** [darktable-org/darktable#15028]
### Describe the bug

darktable 4.4.x reports for images from a Nikon Z6ii (latest firmware) with Nikkor Z 24-120 f/4 (latest firmware) that the focal distance is always 0.01 m. This incorrect focal distance value results in a failure of the vignetting compensation in the Lens Correction module, since this function depends on the focal distance value.

The discussion “[Lens Correction not fixing Vignetting](https://discuss.pixls.us/t/lens-correction-not-fixing-vignetting/38363)” provides additional information on this issue:

- **The issue seems to occur for all Nikon Z cameras with native Z-mount lenses.**
- NEF files from these cameras seem to provide two tags with the name `Exif.NikonLd4.FocusDistance`. One tag seems to refer to F-mount lenses with FTZ adapter, the other tag seems to refer to Z-mount lenses. The latest version of the exif.cc module does not consider the second tag.

In darktable 4.2, the issue did not occur, because the old version of [exif.cc ](https://github.com/darktable-org/darktable/blob/darktable-4.2.x/src/common/exif.cc#L1036) did not read the `Exif.NikonLd4.FocusDistance` tag at all. In consequence, the “image information” reported a focus distance of “-“. With this undefined focus distance, the lens correction worked as expected.

### Steps to reproduce

1. Load a RAF/NEF image from a Nikon Z camera with native Z-mount lens into darktable 4.4.x.
2. In the “image information” of the “darkroom” check the “focal distance”. Does it show the true value or 0.01 m?
3. Activate the Lens Correction module. Does it compensate the vignetting of your lens?

### Expected behavior

The “image information” should report the true focal distance instead of 0.01 m. The Lens Correction module should compensate the vignetting.

### Logfile | Screenshot | Screencast

<img width="908" alt="Screenshot 2023-08-07 214142" src="https://github.com/darktable-org/darktable/assets/43281689/45ba2926-d084-4cec-811e-79ff5936ab90">

### Commit

https://github.com/darktable-org/darktable/commit/ab07d9c5c518137c3fd6f915e145b9c4c321a403

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0 and above

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Example image: [example.zip](https://github.com/darktable-org/darktable/files/12284811/example.zip)

**Comment by kmilos** [comment]
See also e.g. https://github.com/darktable-org/darktable/issues/12264

Could be that a quite a few conversion formulas changed for Z bodies... I guess someone would need to figure out what/how exactly, and only then we can determine if it needs to be solved at dt or exiv2 level.

**Comment by kmilos** [comment]
Hm, possibly changes are needed in both places:

https://github.com/exiftool/exiftool/blob/d35e9e26e0a8b443dae307f55d0a4a067d311a16/lib/Image/ExifTool/Nikon.pm#L5363

**Comment by kmilos** [comment]
Can you please try the proposed fix?

**Comment by kmilos** [comment]
Btw, we might have a similar problem w/ focal length as well...

**Comment by Matthias1102** [comment]
> Can you please try the proposed fix?

Hey Miloš,
thank you for providing a fix for this issue.
I can try my best to verify the fix, but I have never built darkable by myself. I can try to do that later today on my Ubuntu machine, but I cannot guarantee that I will succeed.
However, I can definitively provide Nikon Z6ii test images with various focus distances if this helps...

**Comment by Scorpion078** [comment]
I applied the fix and the focus distance still gets reported as 0.01m. I checked with 4 different z lenses.
I will try to add the other exiv2 fix.

**Comment by kmilos** [comment]
> I will try to add the other exiv2 fix.

It won't work for the other exiv2 fix as 0x4f is no longer a known field. It'll require yet another exiv2 version check once that gets released.

**Comment by kmilos** [comment]
Yeah, the metadata does not get refreshed automagically... 

I have also updated the patch, please retest.

**Comment by Scorpion078** [comment]
I tested the updated patch and it seems like the same result as earlier.
No value in the focus distance but 1000 in lens correction module

**Comment by Matthias1102** [comment]
> I tested the updated patch and it seems like the same result as earlier. No value in the focus distance but 1000 in lens correction module

This is exactly the behavior that we had in darktable 4.2 (when exif.cc did not read the `Exif.NikonLd4.FocusDistance` tag at all). The lens correction module works fine with the 1000 value, since the lensfun database provides vignetting compensation parameters for Nikkor Z lenses at least for the distance of 1000 m. This behavior is better than the current behavior of darktable 4.4, but of course it would be nicer to have the true focus distance.
Thank you for testing the fixes!

**Comment by kmilos** [comment]
My own testing is different - I'm still getting 0.01 m on the fresh import of the attached sample, as if the FTZ mount value is still being read, so still some way to go...

`exiv2` (w/o the precision fix) output shows 16.79 m for the second Z mount value, we should be able to get to it somehow (`exiftool` shows the more precise 17.24 m).

**Comment by Scorpion078** [comment]
Re importing a raw file still doesn’t change the focus distance in the meta data. I had to open/import the files as new ones. I only had the problem with native z lenses, older f lenses with ftz adapter appeared to be fine. So I didn’t check any of those today

**Comment by kmilos** [comment]
For some reason the search by tag hex address does not work in this case, so I had to update the patch to actually look for the second appearance of the tag string.

Please test again, if possible w/ both exiv2 >= 0.27.4 and 0.28.0 (0.28.1 is not released yet).

**Comment by Scorpion078** [comment]
I tested a few images and dt now reports the distance in meter and adjust the lens correction module correctly.
The distance in dt is a little bit less compared to exif tools.
For example: dt reads 8.41m, exif tool has 8.65m and another one is 16.79 vs 17.28.
I would say that is close enough for me.

> Please test again, if possible w/ both exiv2 >= 0.27.4 and 0.28.0 (0.28.1 is not released yet).
I don't really know how to upgrade or downgrade exiv versions.

**Comment by kmilos** [comment]
> The distance in dt is a little bit less compared to exif tools.
> For example: dt reads 8.41m, exif tool has 8.65m and another one is 16.79 vs 17.28.

Yes, that's what the other exiv2 change is about. It should be aligned w/ exiftool from (unreleased) 0.28.1

**Comment by Scorpion078** [comment]
I'm currently on exiv2-0.27.7-1
Windows11 if that makes a difference

**Comment by kmilos** [comment]
> I'm currently on exiv2-0.27.7-1
> Windows11 if that makes a difference

Good.

For 0.28.0 it would be ideally someone testing on Arch/Manjaro or Tumbleweed...

**Comment by apostel338** [comment]
I've tested on Tumbleweed with 0.28.0, a couple of raws from Z50 and Z6 with different native and FTZ lenses and everything worked fine.

**Comment by Matthias1102** [comment]
I have tested the fix successfully on Ubuntu 23.04 with exiv2 0.27.6-1. Based on images from Nikon Z6ii for native Nikkor Z 24-120 mm f/4.
To read the focus distance value, darktable has executed the branch between #else (line 1193) and #endif (line 1202)
