### ISSUE TITLE
mac XMP is corrupted when used in windows?

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#15024]
### Describe the bug

I'm not sure how to describe it, but here's the screenshot of it. 

It's also happening to pretty much all of the images I had edited on a Mac and later imported on Windows.
 
On Windows, I've removed them from the database and re-imported them, and it's still showing the same. 

The only way to fix it is to just discard all history and start over again. 

I'll do some more testing, to see if there's some way to just discard the history and just paste it over again as some way of "tuning it off and on" to fix the issue.

But I'm really not sure what's causing this. 

I thought it might be because of Google Drive, so I deleted all the files and made them available Offline again, and it's still the same. 

### Steps to reproduce

1. edit on mac
2. import on windows

### Expected behavior

mac and windows would look the same

### Logfile | Screenshot | Screencast

![Screenshot 2023-08-07 213503](https://github.com/darktable-org/darktable/assets/58240560/6c48aa8e-1a61-4f80-b3c4-9bb8f1877cb7)

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

Edition	Windows 11 Pro
Version	23H2
OS build	22631.2129
Experience	Windows Feature Experience Pack 1000.22669.1000.0

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Nvidia GTX 2060

**Comment by MStraeten** [comment]
please provide the xmp - and maybe the output of `darktable -d common`
What happens if you compress the history stack?

**Comment by gi-man** [comment]
Maybe share an image and xmp? What version dt version is the Mac? Does it happen with dt 4.4.2 in windows?

**Comment by naisanzaa** [comment]
Mac version is `4.4.2` (https://github.com/darktable-org/darktable/issues/14985)

Oh let me update the windows version first.

**Comment by naisanzaa** [comment]
Upgrading to 4.4.2 fixed this.
