### ISSUE TITLE
Darktable: libexiv2.so.27 not found (libexiv2.so.28 installed on Manjaro linux / arch)

### ISSUE THREAD

**Issue by logikonabstractions** [darktable-org/darktable#15027]
### Describe the bug

After update on Manjaro, darktable doesn't start:

```
[franck@franck-vee ~]$ darktable
darktable: error while loading shared libraries: libexiv2.so.27: cannot open shared object file: No such file or directory
```

Manjaro/arch are rolling update. I have 

### Steps to reproduce

On an up to date manjaro linux (or arch), just launch dartkable.

### Expected behavior

Should start.

### Where did you install darktable from?

self compiled

### darktable version

darktable-git-4.3.0.r1754.g261920dd78-1-x86_64.pkg.tar.zst

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Describe your system?

Manjaro is a rolling release. Possibly installing the older lib (.27) would work. Need to figure out how to. This isn't the way manjaro is meant to be used however.

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
dr needs to be built/linked w/ the exiv2 version available on the system.

This is not a dt bug per se, please contact your distro maintainers and close this issue.

**Comment by sgotti** [comment]
@logikonabstractions  You reported darktable was self compiled, so it's not a darktable or a distro issue, you should just self (re)compile it as it's always needed when a dependency changes.

**Comment by victoryforce** [comment]
@logikonabstractions So I'm closing this issue as it's definitely not a darktable problem.
