### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by deba-1959** [darktable-org/darktable#15048]
I am using Windows 10 (22H2 ver), desktop. Unable to install DT 4.2.2 it gives a compatible issue, how to resolve it?

**Comment by ptilopteri** [comment]
you need to complete the template in order for anyone to have any idea of your problem.

**Comment by Nilvus** [comment]
darktable is unsigned, so if it's jus the sécurité alert about that, just force install.

Otherwise, post an issue with more precise infos. There's à template on purpose for that. With so few, it's hard to help more.
