### ISSUE TITLE
Perceptually uniform grey gradient in darktable.css

### ISSUE THREAD

**Issue by fabiosirna** [darktable-org/darktable#15052]
### Describe the bug

In the default darktable.css there are some color definitions:

```
/*--------------------------------------
  - Perceptually uniform grey gradient -
  --------------------------------------*/

/* grey_00 = pure black is forbidden for visual assessment */
@define-color grey_00 #000000;
@define-color grey_05 #111111;
@define-color grey_10 #1b1b1b;
@define-color grey_15 #262626;
@define-color grey_20 #303030;
@define-color grey_25 #3b3b3b;
@define-color grey_30 #474747;
@define-color grey_35 #525252;
@define-color grey_40 #5e5e5e;
@define-color grey_45 #6a6a6a;
@define-color grey_50 #777777;
@define-color grey_55 #848484;
@define-color grey_60 #919191;
@define-color grey_65 #9e9e9e;
@define-color grey_70 #ababab;
@define-color grey_75 #b9b9b9;
@define-color grey_80 #c6c6c6;
@define-color grey_85 #d4d4d4;
@define-color grey_90 #e2e2e2;
@define-color grey_95 #f1f1f1;
@define-color grey_100 #ffffff;
/* grey_100 = pure white is forbidden for visual assessment */
```

I have tried to reproduce the same values from the definition, and I get different values:

```
/*
--------------------------------------
  - Perceptually uniform grey gradient -
--------------------------------------

--grey_00: hsl(0deg, 0%, 0%);
--grey_05: hsl(0deg, 0%, 5%);
--grey_10: hsl(0deg, 0%, 10%);
--grey_15: hsl(0deg, 0%, 15%);
--grey_20: hsl(0deg, 0%, 20%);
--grey_25: hsl(0deg, 0%, 25%);
--grey_30: hsl(0deg, 0%, 30%);
--grey_35: hsl(0deg, 0%, 35%);
--grey_40: hsl(0deg, 0%, 40%);
--grey_45: hsl(0deg, 0%, 45%);
--grey_50: hsl(0deg, 0%, 50%);
--grey_55: hsl(0deg, 0%, 55%);
--grey_60: hsl(0deg, 0%, 60%);
--grey_65: hsl(0deg, 0%, 65%);
--grey_70: hsl(0deg, 0%, 70%);
--grey_75: hsl(0deg, 0%, 75%);
--grey_80: hsl(0deg, 0%, 80%);
--grey_85: hsl(0deg, 0%, 85%);
--grey_90: hsl(0deg, 0%, 90%);
--grey_95: hsl(0deg, 0%, 95%);
--grey_100: hsl(0deg, 0%,100%);
```

Which translated to hex:

```
@define-color grey_00 #000000;
@define-color grey_05 #0D0D0D;
@define-color grey_10 #1A1A1A;
@define-color grey_15 #262626;
@define-color grey_20 #333333;
@define-color grey_25 #404040;
@define-color grey_30 #4D4D4D;
@define-color grey_35 #595959;
@define-color grey_40 #666666;
@define-color grey_45 #737373;
@define-color grey_50 #808080;
@define-color grey_55 #8C8C8C;
@define-color grey_60 #999999;
@define-color grey_65 #A6A6A6;
@define-color grey_70 #B3B3B3;
@define-color grey_75 #BFBFBF;
@define-color grey_80 #CCCCCC;
@define-color grey_85 #D9D9D9;
@define-color grey_90 #E6E6E6;
@define-color grey_95 #F2F2F2;
@define-color grey_100 #FFFFFF;
```

### Steps to reproduce

There are no steps to reproduce but it's easy to verify, for example:

Hex: #1B1B1B
RGBA(27, 27, 27, 1)
**HSL(0, 0%, 11%)** 
CMYB(0%, 0%, 0%, 89%)

it's not grey 10% but 11%.

### Expected behavior

darktable.css should be updated with the proposed values

### Where did you install darktable from?

darktable.org

### darktable version

darktable-4.5.0+320~gd0dcf03649-arm64

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Ventura 13.5

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
Or not be updated.
You're right about values of course but interface colours works and is well balance. This was not easy and by expérience, updating those will bring many other things to update, especially in other linked thèmes.

So if ain't broken, don't change it. Values are near real percent.

**Comment by fabiosirna** [comment]
I believe the values add an extra bit of contrast that makes the UI easier to use. If you try them you will see that it doesn't change much — I mean is not a disruptive change — but at least it is consistent with the "perceptually uniform grey gradient" statement.

**Comment by Nilvus** [comment]
Did you check also other thèmes (dark and grey ones) carefully and for all parts? If you're sûre nothing is broken in all 3 thèmes, so just propose à PR and ping me.

**Comment by Nilvus** [comment]
Made a quick, and you're right, add an extra bit of contrast. I test it quickly but all 3 themes seems ok after that update. I let you propose a pull request to update that. If you don't know how to do it, I can make it.

**Comment by pitbuster** [comment]
Probably those were created with other color space (maybe Lab?). I don't think HSL is perceptually uniform.

**Comment by Nilvus** [comment]
darktable actual UI was made 4 years ago and those settings were set by Aurélien Pierre. Reading your last comments, I now remember this were in LCH colorspace. I will add that precision and so close this issue when the PR will be merged.

Here you can read an article that explains why LCH color space is good for an UI: https://atmos.style/blog/lch-color-space. So all settings are so great. It's right though that your initial proposal add some better contrast but it's tiny and better to keep respect of color space. Thanks anyway for your issue.

**Comment by fabiosirna** [comment]
Thanks! And really appreciated the link you shared.

**Comment by Nilvus** [comment]
I forgot a thing: thanks @pitbuster for your comment that help a lot to correctly fix that issue and remember the correct color space used.
