### ISSUE TITLE
Viewport jumps when activating retouch when zoomed in on a cropped image

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15059]
### Describe the bug

When zooming in to the place you want to retouch, then enabling retouch the view port jumps away from this spot.

### Steps to reproduce

Open image, crop, zoom in, activate retouch, viewport jumps away

### Expected behavior

viewport should stay where it was

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+320~gd0dcf03649

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

Wayland, 64GB RAM, Kernel 6.4.10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Polaris RX 580 (all time favorite)

**Comment by piratenpanda** [comment]
Most likely by design as it shows the whole image then but annoying still as it slows down the workflow

**Comment by ralfbrown** [comment]
My immediate reaction on seeing the issue title was that the new "show the uncropped image" was at fault. 
We should probably shift the viewport to keep the same portion of the image in view, though that might be tricky to implement.
