### ISSUE TITLE
Darktable keeps crashing when trying to add to library

### ISSUE THREAD

**Issue by TrVlogs** [darktable-org/darktable#15063]
### Describe the bug

darktable keeps crashing when trying to add to library. Then click on the folder it crashes. 

### Steps to reproduce

Go to Add to library
Then Under folders
the folder I'm trying to open where the files are.
I click on it then it crashes.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2-

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Describe your system?

N/A

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Everything else works but that. When I click on it, it crashes. Not to computer savvy so don't know what to do.

https://github.com/darktable-org/darktable/assets/51675840/53d0f1ff-211b-473c-b798-b2079be3d77c

**Comment by MStraeten** [comment]
provide the crash report ;) should be in your users \AppData\Local\Microsoft\Windows\INetCache\darktable
run darktable -d common from command line to get more info what exactly happens

**Comment by TrVlogs** [comment]
I'm sorry what? I am not too computer savvy. It's also installed on a portable hard. 
    On Sunday, August 13, 2023 at 03:02:07 PM EDT, Martin Straeten ***@***.***> wrote:  
 
 


provide the crash report ;) should be in your users \AppData\Local\Microsoft\Windows\INetCache\darktable
run darktable -d common from command line to get more info what exactly happens

**Comment by TrVlogs** [comment]
> 

Ok so I am not too computer savvy but here it is I think. 
[darktable-log.txt](https://github.com/darktable-org/darktable/files/12337121/darktable-log.txt)

**Comment by MStraeten** [comment]
seems your darktable database are locked. Have a look into your users AppData\Local\darktable directory and delete the data.db.lock and library.db.lock files if they exist. 
maybe first check via taskmaster if there’s already a darktable process hanging around an kill that process

**Comment by TrVlogs** [comment]
What is taskmaster? And how do I do that?Thank you.


Sent from Yahoo Mail for iPhone


On Monday, August 14, 2023, 1:17 PM, Martin Straeten ***@***.***> wrote:




seems your darktable database are locked. Have a look into your users AppData\Local\darktable directory and delete the data.db.lock and library.db.lock files if they exist.
maybe first check via taskmaster if there’s already a darktable process hanging around an kill that process

**Comment by ptilopteri** [comment]
you might consider using google.

**Comment by MStraeten** [comment]
Taskmanager was meant - damned autocorrection ;)

**Comment by TrVlogs** [comment]
> What is taskmaster? And how do I do that?Thank you. Sent from Yahoo Mail for iPhone On Monday, August 14, 2023, 1:17 PM, Martin Straeten ***@***.***> wrote: seems your darktable database are locked. Have a look into your users AppData\Local\darktable directory and delete the data.db.lock and library.db.lock files if they exist. maybe first check via taskmaster if there’s already a darktable process hanging around an kill that process — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Ok, so I deleted it again. Twice the data.db.lock and library.db.lock files just keep coming back. I delete then try t start darktable or delete them & restart the PC still having the same issue. When I delete the files & open the folder back up they reappear. 

[darktable-log.txt](https://github.com/darktable-org/darktable/files/12343694/darktable-log.txt)

**Comment by ptilopteri** [comment]
when darktable is active, you *should* have db locks to prevent access by another instance of darktable corrupting your databases.
if you have locks present and no instance of darktable, the locks should be removed, especially before starting darktable.

**Comment by collisionbend** [comment]
I'm having the same issue on Mac OS 13.4.1(c) Ventura with DarkTable 4.4.0. Maddening. Crash reports sent automagically.

**Comment by MStraeten** [comment]
> Crash reports sent automagically.

that goes to apple - and they won’t care a lot about a third party software ;)
You need to provide it here so someone can inspect where the crash occurs

**Comment by TrVlogs** [comment]
> when darktable is active, you _should_ have db locks to prevent access by another instance of darktable corrupting your databases. if you have locks present and no instance of darktable, the locks should be removed, especially before starting darktable.

I did delete it before I started but they reappear.

**Comment by ptilopteri** [comment]
certainly they reappear.  they are set by you activating darktable and are supposed to be there.  but they should close when you close darktable.
if they are present and you do not have darktable running, *usually* indicates an unclean darktable shutdown or system crash.

**Comment by RobLW** [comment]
Same issue for me on Linux.
If I start the import process, then flip to a different desktop in Linux, it seems to crash. 

One thing of note for me, is that I'm importing files over the network on an SMB share.

Not sure where to find relevant log for Darktable in Linux. Let me know and I'll post it if it has something useful.  I cannot see anything relating to DT in /opt or /var or /run. Arch Linux.

Thanks.

**Comment by TrVlogs** [comment]
> certainly they reappear. they are set by you activating darktable and are supposed to be there. but they should close when you close darktable. if they are present and you do not have darktable running, _usually_ indicates an unclean darktable shutdown or system crash.

The thing is I just reinstalled it did not change or do anything to any settings. Just installed it opened it tried to import pics to edit then it just crashes.

**Comment by gi-man** [comment]
@TrVlogs without a log of a crash it will be very hard to understand what is going on. It could be that you have a corrupted file during the import. 

Try to start darktable using -d common in the windows command line, obtain a crash and then upload the log file from a crash. Some steps for windows are here: https://www.darktable.org/about/faq/#faq-windows-bugs

**Comment by TrVlogs** [comment]
> @TrVlogs without a log of a crash it will be very hard to understand what is going on. It could be that you have a corrupted file during the import.
> 
> Try to start darktable using -d common in the windows command line, obtain a crash and then upload the log file from a crash. Some steps for windows are here: https://www.darktable.org/about/faq/#faq-windows-bugs

I never even opened a file it would not even let me get to a file to open it. This is what I got. Hoping they show.

[F__Darktable_bin_darktable_exe.txt](https://github.com/darktable-org/darktable/files/12379269/F__Darktable_bin_darktable_exe.txt)
[2 F__Darktable_bin_darktable_exe.txt](https://github.com/darktable-org/darktable/files/12379270/2.F__Darktable_bin_darktable_exe.txt)
[3 F__Darktable_bin_darktable_exe.txt](https://github.com/darktable-org/darktable/files/12379271/3.F__Darktable_bin_darktable_exe.txt)

**Comment by victoryforce** [comment]
> Hoping they show.

No, what you attached is non-identifiable binary data.

**Comment by TrVlogs** [comment]
That's all I could find. God this is so frustrating I have so many pics to edit.

**Comment by gi-man** [comment]
The files should look identical to the ones you posted 5 days ago. 

Start darktable via cmd using darktable -d common then go to the folder with the logs.

**Comment by TrVlogs** [comment]
> The files should look identical to the ones you posted 5 days ago.
> 
> Start darktable via cmd using darktable -d common then go to the folder with the logs.

So, anyone else having this issue. I think I fixed it. I completely uninstalled it. Did a "darktable" file search in "This PC". Deleted everything that had "Darktable" in it other than my "The Gimp" files. Make sure you have administrator permissions. Did a computer reboot. So far so good.

**Comment by victoryforce** [comment]
> So, anyone else having this issue. I think I fixed it.

If you problem is solved, please consider closing the issue.

**Comment by TrVlogs** [comment]
Thanks again to everyone who helped.
