### ISSUE TITLE
DNG Files from the Sigma SD Quattro are not rendered correctly

### ISSUE THREAD

**Issue by steph72** [darktable-org/darktable#15064]
### Describe the bug

In DNG files from the Sigma SD Quattro there are black and purple borders around the left and upper edge of the picture:

![image](https://github.com/darktable-org/darktable/assets/51749597/ea14173f-dd58-4be9-b6e9-f36c0e591793)

I'm making the zipped original DNG available here:
https://www.dropbox.com/scl/fi/q1qbad9qgiu96ofcic798/SDQ_0453.zip?rlkey=7x39cq7vc2vmmv8lh746cvdyg&dl=0

If needed, I can supply more test images.

### Steps to reproduce

1. Download SDQ_0453.zip and import the resulting SDQ_0453.DNG image
2. Open the image in the "darkroom" view

### Expected behavior

Darktable should render the image without black borders and purple and green artifacts.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

No

**Comment by kmilos** [comment]
Please upload samples (both X3F and DNG of the same content) to https://raw.pixls.us/

**Comment by steph72** [comment]
I have uploaded the images to raw.pixls.us.

X3F and DNG of the same file is not possible, as this is the camera's native DNG mode. The camera allows only one one or the other, not both.

**Comment by kmilos** [comment]
Thanks.

Obviously it can't be done simultaneously. I meant two consecutive shots of the same scene.

**Comment by steph72** [comment]
ah, ok, misunderstood you there ;)

I uploaded a couple more DNG & X3F files. When trying to import them into Darktable, I noticed that colour DNGs seem to be completely broken. The colour is all wrong, and the borders are there, also.

![image](https://github.com/darktable-org/darktable/assets/51749597/2728c016-de06-4d49-a5b1-887167890504)

**Comment by kmilos** [comment]
Thanks for the samples. @LebedevRI Please replace the old Sigma sd Quattro one on RPU with the new X3F+DNG pair (I guess color mode is of more interest).

Re color, as Sigmas are a bit special, they output a 3-channel LinerRaw DNG, and those might contain some "snags". For starters, if black level for each channel is not 0 (like it is for mono it seems), you'll have to set those manually in the raw black/white point module, as multi-channel DNGs are not supported as well as regular (CFA, single-channel) DNGs.

Also, while the crop issue is being investigated, you can set that manually as well by unhiding the crop sliders (set `` in your `~/.config/darktable/darktablerc` file before launching), and then adjusting those - going by the DNG metadata should be 216 from the left and 80 from the top, 248 from the left, and 80 from the bottom.

**Comment by kmilos** [comment]
The other option for colors is to turn off the color calibration module and switch the white balance one to "as shot". Seems to be a separate issue.

**Comment by steph72** [comment]
thanks, until there's a fix, that works wonderful! :)

**Comment by LebedevRI** [comment]
> Thanks for the samples. @LebedevRI Please replace the old Sigma sd Quattro one on RPU with the new X3F+DNG pair (I guess color mode is of more interest).

@steph72 i'm not sure which of the uploads is a set (hopefully the one with architecture).
i've deleted all unverified uploads, please upload a single pair that i shall keep

**Comment by steph72** [comment]
> > Thanks for the samples. @LebedevRI Please replace the old Sigma sd Quattro one on RPU with the new X3F+DNG pair (I guess color mode is of more interest).
> 
> @steph72 i'm not sure which of the uploads is a set (hopefully the one with architecture). i've deleted all unverified uploads for that camera, please upload a single pair that i shall keep

re-uploaded and renamed for clarity. sample1.dng and sample1.x3f are a set, as are sample2.x3f|dng and sample3.x3f|dng

**Comment by LebedevRI** [comment]
> > > Thanks for the samples. @LebedevRI Please replace the old Sigma sd Quattro one on RPU with the new X3F+DNG pair (I guess color mode is of more interest).
> > 
> > 
> > @steph72 i'm not sure which of the uploads is a set (hopefully the one with architecture). i've deleted all unverified uploads for that camera, please upload a single pair that i shall keep
> 
> re-uploaded and renamed for clarity. sample1.dng and sample1.x3f are a set, as are sample2.x3f|dng and sample3.x3f|dng

Thank you for the contribution, verified the third set!

**Comment by LebedevRI** [comment]
I don't believe the crop problem is on rawspeed's side here.

As for the color,
```
0xc65a Exif.Image.CalibrationIlluminant1            Short       1   2  17  Standard light A
0xc65b Exif.Image.CalibrationIlluminant2            Short       1   2  15  White fluorescent (WW 3200 - 3700K)
```
... which is not the usual `21` / D65, so it's not too surprising. (that it's not handled correctly)

**Comment by kmilos** [comment]
> which is not the usual `21 / D65`

That doesn't result in such a huge shift... We take the closest matrix to D65 and do chromatic adaptation on it - not perfect, but decent enough. This really is due to white balance vs color calibration modules, and has popped up for some other cameras as well.

Anyhoo, got to get to the bottom of cropping weirdness first...
