### ISSUE TITLE
DNG ActiveArea instructs to crop on top, but darktable crops on bottom

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#15069]
### Describe the bug

Hi, developer of https://github.com/dnglab/dnglab here. I'm working on X-Trans Pixel-Shift merging (Fuji X-T5 and the like) and discovered a strange problem in darktable with the resulting DNGs. It has not relation to the merged pixel data but the ActiveArea tag in general. For testing purposes, I've set the ActiveArea to some extreme values (cropping 3500 pixels from top):

```
exiv2 -pR fail.dng | grep ActiveArea
  590599330 | 0xc68d ActiveArea                   |     SHORT |        4 | 590599092 | 3500 0 10392 15744
```
The first value is the crop border from top, so the expected result should be cropped on top. But the opposite is true, the image bottom is truncated:
![grafik](https://github.com/darktable-org/darktable/assets/509535/eb193cc7-c542-4778-b077-546f749447b6)

Full image without any cropping by ActiveArea:

![grafik](https://github.com/darktable-org/darktable/assets/509535/058165fc-6230-4fcb-b049-fb0f4a85a4d5)

So for some reason, darktable always crops the image on bottom. I've modified the ActiveArea to "really" crop 3500 pixels from the bottom instead from top to verify if the processing is just inversed. But it's not. Darktable always crops bottom.

I've checked rawspeed DNG decoder, the extracted rectangle coordinates are correct. So I assume the problem is located somewhere else but I was not able to figure it out.
The DNG image is properly cropped and displayed in Adobe Camera btw.

### Steps to reproduce

1. Download DNG file from https://chaospixel.com/pub/github/dt/activeareabug/fail.dng
2. Open DNG file in darktable

### Expected behavior

darktable should crop as ActiveArea tag advises (crop on top for the example image)

### Where did you install darktable from?

self compiled

### darktable version

4.3.0+2514~gcd43e9e070 and 4.5.0+328~g1aca07c62d

### What OS are you using?

Linux

### What is the version of your OS?

Debian

### Describe your system?

One System with OpenCL, the other without OpenCL.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia

**Comment by kmilos** [comment]
Possibly related to https://github.com/darktable-org/darktable/issues/15064?

**Comment by cytrinox** [comment]
@kmilos My merged DNG is not bayer anymore but linear data. Afaik Sigma uses Foveon chips and the is also linear pixel data. Maybe this crop bug only hit on non-bayer input?
