### ISSUE TITLE
Add Charttu Colorchecker values

### ISSUE THREAD

**Issue by RedFox-Fr** [darktable-org/darktable#15079]
Hi,

Do you have any objection to add the Charttu Colorchecker values in Darktable ?
This is like X-Rite ColorChecker Classic but with slightly different values provided by the company.

http://www.charttu.com/
http://www.charttu.com/product/showproduct.php?id=153
https://fr.aliexpress.com/item/1005002726542535.html?spm=a2g0o.order_list.order_list_main.36.4c8e5e5bzSp2Ms&gatewayAdapt=glo2fra

![charttu_colorchecker](https://github.com/darktable-org/darktable/assets/82333326/d8a9aa8c-5b98-40d2-852f-cc0637538e1a)

![charttu_calibration_values](https://github.com/darktable-org/darktable/assets/82333326/ccba7dee-60a1-40ea-a1ba-632de1727a0c)

Best regards,

**Comment by MStraeten** [comment]
quite unlikely - since the geometry and values needs to be hardcoded that’s just done for charts with reliable colors constant over product lots over several years.
You might do a custom build where you integrate the values in https://github.com/darktable-org/darktable/blob/master/src/common/colorchecker.h

**Comment by RedFox-Fr** [comment]
OK,

What do you think about the possibility to create custom target in the interface without the need to create custom build ?

X-Rite/Calibrite recommands to buy a new ColorChecker every two years, if we take the best care of the target, because theirs colors become unreliable. (before you ask, this recommandation is in page 16 of their manual https://www.xrite.com/-/media/xrite/files/manuals_and_userguides/c/o/colorcheckerpassport_user_manual_en.pdf )

If we have the ability to create custom target in the interface, we can mesure our olds targets with a colorimeter or spectrophotometer and keep it (this is good for the planet)... or our news ones that you don't trust...

Thanks,

**Comment by MStraeten** [comment]
if you take that effort then you also can simply build your custom darktable ;) 
There are no known activities to replace those hardcoded targets by fully customizable targets. To much effort for too less user value.
But if you bite the bullet - fork and feel free to improve ...

**Comment by Jiyone** [comment]
I’ve made my own hardcoded it8 chart in color balance and I have the project to add custom it8 chart, when I’ll have the skill to do that 😅.

Just to say that I’m here if you need help.

**Comment by RedFox-Fr** [comment]
@Jiyone 

Thanks for your proposition, but that's not a priority until Darktable recognizes the RAW from my camera. I was just taking advantage of the holidays to reevaluate the tools that could integrate my workflow for the coming year.

I don't understand the flippancy with which some developers push to fork projects and fragment the user community. It's counterproductive.

I saw in the issues that I wasn't the only one who asked for this feature, so it's wrong to claim that there is no "known activity" about it and it's useless.

All things considered, some people may prefer to buy a new monitor rather than make the effort to recalibrate it... ;o)

**Comment by MStraeten** [comment]
"known activity" doesn't mean there was no one reasoning about it, but there's no developer working on it. Features aren't implemented if even several are demanding it until one starts coding...
