### ISSUE TITLE
Please allow thumbnail building off-screen.

### ISSUE THREAD

**Issue by RobLW** [darktable-org/darktable#15076]
**Is your feature request related to a problem? Please describe.**
No problem as such, just an idea to boost the user experience performance.

**Describe the solution you'd like**
If I import 1000 images as an example and viewing the grid in LightTable, it will build and cache the thumbnails of images which are currently in view on my screen. But there are 984 more images for me to scroll through and build thumbnails for.  The import is already complete while I made a nice cup of tea and the computer has sat idle for a few minutes. lightTable could have been building thumbnails for images which are off my screen instead of sitting idle. 

So in short, can there be an option to allow users to trigger to enable lighttable to continue building thumbnails for images which have not yet been scrolled onto my screen and not yet been cached.

**Alternatives**
A button that a user clicks which causes the scroll bar to automagically page down through the entire grid and bring all photos into view causing lighttable to build the thumb nails.

**Additional context**
I feel this will improve the smoothness and speed of users scrolling through images which haven't yet had their thumbnails/previews cached on disk it also makes more use of hardware resources which are otherwise just idling or doing very little work.

**Comment by pehar1** [comment]
You can use the commandline tool darktable-generate-cache : https://darktable-org.github.io/dtdocs/en/special-topics/program-invocation/darktable-generate-cache/

**Comment by jenshannoschwalm** [comment]
Implemented in #15294
