### ISSUE TITLE
upload folder from desktop

### ISSUE THREAD

**Issue by fiyakamstore** [darktable-org/darktable#15081]
### Describe the bug

Hello, I have a few secrets.
1)I am trying to add folders or photos to Darktable's library from desktop. however, when I tried to add the photos I normally see on the desktop to darktable, the folders I tried to add when I first installed darktable were fine. I think I tried to install it the second time. I must have messed something up in the settings but I don't know what I'm doing wrong. I am sending you a screen recording for this. Please check.
2) Some of the folders that I used to work on are scratched in the menu on the right and I cannot access them.
3) If I need to install a new darktable account to completely remove these errors, how can I reset my account and open a new one.

### Steps to reproduce

@sk1p @janfri @jonleighton @pope @kelvie 
#15080 

https://github.com/darktable-org/darktable/assets/131078529/04e67129-1cac-4319-80c5-43cd0a3a21c3

![Ekran görüntüsü 2023-08-18 102131](https://github.com/darktable-org/darktable/assets/131078529/df09a2a7-d40c-435b-a85a-f7b866005c02)

### Expected behavior

darktable

### Logfile | Screenshot | Screencast

![darktable ekran](https://github.com/darktable-org/darktable/assets/131078529/0b12a725-1355-48fb-9257-5051d7c1b133)

### Commit

upload folder from desktop

### Where did you install darktable from?

darktable.org

### darktable version

4,4

### What OS are you using?

Windows

### What is the version of your OS?

windows 11 

### Describe your system?

Device name asiyehp
Processor 12th Gen Intel(R) Core(TM) i5-12500H 2.50 GHz
Installed RAM 8.00 GB (usable: 7.68 GB)
Device ID F9DFB2A6-ADFB-4CB7-A8C5-7F8C609DF768
Product ID 00342-43322- 83232-AAOEM
System type 64-bit processor system, x64-based processor
Pen and touch No pen input or touch input on this display
Edition Windows 11 Home Single Language
Version 22H2
Upload date ‎11.‎05.‎2023
OS attack 22621.2134
Experienced Windows Feature Experience Pack 1000.22659.1000.0
Edition Windows 11 Home Single Language
Version 22H2
Upload date ‎11.‎05.‎2023
OS version 22621.2134
Windows Experience Experience Pack 1000.22659.1000.0

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Cihaz adı	asiyehp İşlemci	12th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz Takılı RAM	8,00 GB (kullanılabilir: 7,68 GB) Cihaz Kimliği	F9DFB2A6-ADFB-4CB7-A8C5-7F8C609DF768 Ürün Kimliği	00342-43322-83232-AAOEM Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci Kalem ve dokunma	Bu görüntü biriminde kalem girdisi veya dokunarak giriş yok

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I only know Turkish, so it is very difficult to find Turkish training videos. I want to use darktable for my work all the time.

**Comment by Nilvus** [comment]
darktable do not add folders, he link images. So if you remove images or folders (or move them) on your file explorer, you lost them. And then you have images with skull on dark background and crossed lines. You can only link images or folders with images inside. I suggest you to read the manual. All is explained on that. As this is not an issue (a bug or feature request), I close. If you need more help, go on pixls.us forum, it's there for that.
