### ISSUE TITLE
Missing search possibility for lenses in the collection filters section

### ISSUE THREAD

**Issue by 01McAc** [darktable-org/darktable#15086]
### Describe the bug

A search for specific lenses in lighttable/collection filters results in an empty set. It looks like the metadata is not being searched.
![Screenshot_20230819_175920](https://github.com/darktable-org/darktable/assets/88337479/8209c8a4-e746-42da-8ba6-55eab1fb1e2e)

### Steps to reproduce

1. Goto lighttable
2. click on collection filters
3. enter a lens of your choice (and which exists in your collection) in field 'search' 

### Expected behavior

dt should search the collection for the specific lens and show the results.

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+303~g64d57ebac

### What OS are you using?

Linux

### What is the version of your OS?

Fedora Rawhide

### Describe your system?

64GB RAM
X11 + proprietary driver from nvidia

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia and proprietary driver from nvidia

**Comment by Nilvus** [comment]
This part miss quite other filters. It's known but developer of that part do not have time since a year due to change on his life. And no other developer work on that part. So, I will close it because this is not an issue and this should not be added since a long time. You could find what you want on filters in collection module just above.

**Comment by zisoft** [comment]
I have added camera, maker, model and lens to the search capabilities in PR #13804.

Lens needed to be removed because it causes too much noise in the search results.

**Comment by Nilvus** [comment]
Thanks @zisoft. I so change statut to close as done to avoid reopen it and close it when it will be merged. Good to see that you could improve that part as AlicVB do not have time actually.

**Comment by Nilvus** [comment]
Oups, I didn't understood that this was merged some months ago (and miss so that). Sorry, I'm not sure so to understand what you mean by "Lens needed to be removed". Where?

**Comment by zisoft** [comment]
The search for lens needed to be removed from the PR because the search results were too noisy.
So only Camera, maker and model were implemented.
