### ISSUE TITLE
Feature request for Export module: Import and group exported images

### ISSUE THREAD

**Issue by norbre-hu** [darktable-org/darktable#15080]
I like to see the exported images next to the RAW files, so currently after exporting images from RAW files I import the created JPEG, TIFF files into DT and group them with their RAW files.

It would be nice if there was an option in DT to do this step automatically, even for multiple exports, even if the exported file names different from the original RAW file.

thank you

**Comment by MStraeten** [comment]
you might try https://darktable-org.github.io/luadocs/lua.scripts.manual/scripts/contrib/autogrouper/

**Comment by wpferguson** [comment]
You can use the lua script ext_editors which provides a collection target to the exporter.  Start the script, select collection as the storage target, then export your images.  They will be added to the collection and grouped with the raws.

**Comment by norbre-hu** [comment]
> You can use the lua script ext_editors which provides a collection target to the exporter. Start the script, select collection as the storage target, then export your images. They will be added to the collection and grouped with the raws.

I will try this, I guess this is a good solution, thank you

**Comment by norbre-hu** [comment]
> You can use the lua script ext_editors which provides a collection target to the exporter. Start the script, select collection as the storage target, then export your images. They will be added to the collection and grouped with the raws.

I will try this, I guess this is a good solution, thank you
