### ISSUE TITLE
gtk&macOS&css:  different behaviour regarding menu size on multi-instance and presets menu (on external display) depending on fonts

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#15083]
https://github.com/darktable-org/darktable/issues/14856 seemed to be fine if using gtk3 3.24.38 instead of 3.24.37.
but there seems to be a further issue regarding those menues:
the same behaviour that is no longer present with gtk3 for the modules presets menu keeps being reproducible for multi instance menu.
![image](https://github.com/darktable-org/darktable/assets/39386816/7c0f2bc7-ead8-4650-ab01-164591ec0abb)
 
I checked the source to find hints for a solution and found the the presets menu is created as a GTK_MENU:
```
  GtkMenu *menu = darktable.gui->presets_popup_menu;
  if(menu) gtk_widget_destroy(GTK_WIDGET(menu));
  darktable.gui->presets_popup_menu = GTK_MENU(gtk_menu_new());
  menu = darktable.gui->presets_popup_menu;

```
while the multiinstance menu is created as a GTK_MENU_SHELL:
```
GtkMenuShell *menu = GTK_MENU_SHELL(gtk_menu_new());
  GtkWidget *item;

  item = gtk_menu_item_new_with_label(_("new instance"));
```
the menues are generated the same way: adding entries via `gtk_menu_shell_append(menu, item);` and also `gtk_menu_shell_append(GTK_MENU_SHELL(menu), GTK_WIDGET(mi));`

replacing GtkMenuShell/GTK_MENU_SHELL by GtkMenu/GTK_MENU doesn't change the behaviour

the style popup menu ist defined similar to multiinstance menu and is rendered fine ...

Do you have an idea what also could be different so the size isn't adapted properly? maybe some css stuff?

**Comment by zisoft** [comment]
Do you have any steps to reproduce?
This is how it looks on my Mac with current master, homebrew built with gtk 3.24.38:

<img width="344" alt="Bildschirmfoto 2023-08-19 um 18 14 47" src="https://github.com/darktable-org/darktable/assets/4083281/9f92bc08-f4a0-4772-a17d-2dc4f975c9d8">

**Comment by MStraeten** [comment]
unfortunately just reproducible if you have a main retina display (in my case may macbook pro) and an external display (all similar cases reported had the same configuration)
on the retina display it's fine but the external show this issue
btw: when running darktable with gtk inspector (GSETTINGS_SCHEMA_DIR=/opt/local/share/glib-2.0/schemas/ XDG_DATA_DIRS=/opt/local/share GTK_DEBUG=interactive ./bin/darktable) the css seems to be ignored - then it's fine

**Comment by MStraeten** [comment]
i think i hav a hint: darktable.css doesn't show this behaviour but darktable-elegant-grey.css ...
so definitely css stuff ...

**Comment by zisoft** [comment]
just used my TV as external monitor (macOS setting: use as separate display) and moved dt to that display.
So I have my MacBook with retina display as main, the TV as second monitor.

Still not able to reproduce. Do I need to make further settings in dt?

**Comment by MStraeten** [comment]
which css are you using? darktable.css?

**Comment by zisoft** [comment]
I'm using `darktable-elegant-grey.css`

**Comment by MStraeten** [comment]
seems to be also dependent on the scree resolution: external 2K (2560x1440) shows the issue in native resolution but not in HiDPI 1280x720 resolution. So the scaling is root cause.
all css except darktable.css and darktable-icons.css show these: main difference is the changed fonts ...

**Comment by MStraeten** [comment]
menuitem label
{
  font-family: "Roboto Light", "Roboto",                  /* best case scenario */
                sans-serif;                                /* default default */
}
messes it up
menuitem label
{
  font-family: "Segoe UI Light", "Segoe UI",              /* Windows 10 default */
               "SF Pro Display Light", "SF Pro Display",  /* Mac OS X default */
               "Ubuntu Light", "Ubuntu", "IPAPGothic",    /* Ubuntu default */
               "Cantarell",                               /* Gnome default */
                sans-serif;                                /* default default */
}
is ok, so Roboto seems to be improper handled ...

**Comment by zisoft** [comment]
Very strange. I can toggle the resolution of the external display between native and HiDPI and still cannot reproduce.

As macOS nightly builds are currently broken, would you mind downloading my manual build and test:
https://zisoft.de/storage/app/media/download/darktable-4.5.0+332~g463102a53e-x86_64.dmg

Just to make sure its not a packaging issue.

**Comment by MStraeten** [comment]
```
Process 73250 launched: '/Volumes/darktable/darktable.app/Contents/MacOS/darktable' (x86_64)
warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not read from the host's in-memory shared cache. This will likely reduce debugging performance.

Process 73250 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001090ac9f9 libdarktable.dylib`dt_init + 121
libdarktable.dylib`dt_init:
->  0x1090ac9f9 <+121>: vcvtsi2sd %rax, %xmm0, %xmm0
    0x1090ac9fe <+126>: vcvtsi2sdl 0xcd8(%rsp), %xmm1, %xmm1
    0x1090aca07 <+135>: vfmadd132sd 0x365310(%rip), %xmm0, %xmm1 ; _action_fallbacks_combo + 608, xmm1 = (xmm1 * mem) + xmm0
    0x1090aca10 <+144>: vmovsd %xmm1, 0xa8(%rsp)
Target 0: (darktable) stopped.
```
the build i do in a virtual machine to get a 10.14 package runs fine but also has this issue

**Comment by zisoft** [comment]
> Roboto seems to be improper handled

Roboto is not installed on my system, did you install that font manually?
Is that the difference?

**Comment by MStraeten** [comment]
if it's not present then dt takes available fonts in that sequence (als styles derived form elegant-darker):
 "Roboto Light", "Roboto",                  /* best case scenario */
               "Segoe UI Light", "Segoe UI",              /* Windows 10 default */
               "SF Pro Display Light", "SF Pro Display",  /* Mac OS X default */
               "Ubuntu Light", "Ubuntu", "IPAPGothic",    /* Ubuntu default */
               "Cantarell",                               /* Gnome default */
                sans-serif;                                /* default default */
SF Pro isn't accessible by default unless it's explicitly installed  - so the system default sans-serif font will be taken

it seems the scaling for Roboto isn't properly done just for this menu (no idea why) 
if i set an explicit scaling factor:
![image](https://github.com/darktable-org/darktable/assets/39386816/d1da7f37-406a-45d0-a6e6-c7ea83756b7d)
it's properly rendered also on the external display.

**Comment by MStraeten** [comment]
default behaviour:
```
0,7002 [dt_get_system_gui_ppd] system ppd is 2,000000
0,7002 [screen resolution] setting the screen resolution to 72,000000 dpi
```
manually set to 71: it fine ;)
72 and 73 are bad then again it's fine ...

**Comment by MStraeten** [comment]
but 72 is ok on mbp retina screen ...

**Comment by jenshannoschwalm** [comment]
I cant remember exactly but there was some workaround for osx ppd and dpi settings for the second monitor. Iirc that was taken from first monitor?

**Comment by MStraeten** [comment]
yes, but it seems that this isn't the core issue.
- gtk3 3.24.38 is required to get a chance of a proper rendering of the menus (and at least works for presets menu)
- using a system font (done when using darktable.css) is fine with default rendering 

It seems it's exactly the Roboto font that isn't properly rendered if 72 or 73 dpi is set (manually as well as autodetected) - but just for the multiinstance menu
if i change the font to https://fonts.google.com/specimen/Roboto+Flex (using the fixed Regular ttf)
```
menuitem label
{
font-family: "Roboto Flex";
}
```
everything is fine also.

So there seems to be a font specific property that isn't handled equal in each situation ...

**Comment by MStraeten** [comment]
playing around with css font options gives quite interesting results:
```
menuitem label
{
font-family: "Roboto";
font-weight: lighter;
}
```
renders fine for multiinstance menu but improper for presets menu - so it seems to be originates in the css rendering of fonts ...

**Comment by Nilvus** [comment]
Just my 2cents on that one. I'm not sure CSS or fonts settings in CSS are the real issue even if it seems to solve (maybe hide seems more suitable here) it. First, I can't reproduce on Linux even by trying other screen resolutions on my external display. I have also Gtk3 3.24.38 and tested on last master. And I use elegant grey theme since the beginning and with Roboto fonts.

It maybe originates more on how macOS package (homebrew or something else) handle fonts as this seems to happen only on macOS. Anyway, as another try on a workaround (or a fix), could you test that:

menuitem label
{
  padding: 0.1em;
}

But more, my question would rely on your first comment and how menus are coded. Is it necessary to use Gtk Menu shell for multi instances menus and Gtk menu for others? Maybe use same elsewhere (of course except if difference is necessary regarding those 2 widgets). And on that, I would link an old issue I posted (and closed but could be reopened) about those menus (that I think need a rewrite): https://github.com/darktable-org/darktable/issues/11335

**Comment by MStraeten** [comment]
that padding is fine - even 0.001em ;)
since gtk and macOS aren't best friends it's quit hard to find the root cause:
- the font behaves different to other fonts
- the behaviour isn't consistent over multiinstance menu and styles menu (in darkroom) or presets menu 
- depending on the dpi setting: <72 and >73 is ok, but system detects 72 dpi ;) and just the external WQHD screen

but a line in darktable.css indicates there're 'anomalies' regarding menuitems ;)
```
/* fix for menuitem in bottom toolbar mainly */
menuitem > arrow
{
  padding-right: 0.42em;
}
```
so there's a working solution using user.css, maybe add the workaround to darktable.css (like for menuitem > arrow)

will do a pr for that workaround ...

**Comment by MStraeten** [comment]
needs menuitem label
{
padding: 0.01em 0.42em;
}
to keep arrows in styles menu ok

**Comment by dterrahe** [comment]
> replacing GtkMenuShell/GTK_MENU_SHELL by GtkMenu/GTK_MENU doesn't change the behaviour

Both menus are created using `gtk_menu_new`; the resulting pointer is either cast before or after storing it, but that doesn't make a difference.

The menus that _do_ seem to work correctly have at least one item (these are all checkmenuitems) marked with `dt_gui_add_class(mi, "active_menu_item");` 
This triggers the following CSS:
```
.active_menu_item *, /* needed for some Pango issues not rendering synthetic bold for all OS */
notebook tabs,
tooltip label,
#blending-tabs,
#modules-tabs
{
  font-family: "Roboto",
               "Segoe UI",
               "SF Pro Text",
               "Ubuntu", "IPAPGothic",
               "Cantarell",
                sans-serif;
}
```
which apparently was needed to work around some issue. The multi-instance menu (and possibly other menus; please search for `gtk_menu_new` and verify that menus in the collection, masks, modulegroups and tagging modules don't have similar issues) do not benefit from this fix, but maybe should? So I'm wondering if the "correct" fix (instead of #15093) is to change the line `menu_item *` in the CSS file to either `menu_item label` or `menu_item *`.

**Comment by MStraeten** [comment]
that just draws the menuitem label in bold - but since that doesn't change the font family the issue related to Roboto font keeps occuring.

**Comment by Nilvus** [comment]
Thanks @dterrahe for your precise and clear explanation. About your CSS change, it's not the good way as .active_menu_item is used also to make difference between some menuitem. And if you replace .active_menuitem by menuitem, you will some menus where text become bold. Just copy-paste CSS code you post and make change (you could check the difference on clicking in the arrow for filters conditions in collections module. Adding padding (so @MStraeten PR) works and is better (I will just propose a code improvement on that PR).

**Comment by dterrahe** [comment]
OK, thanks for testing and confirming.
