### ISSUE TITLE
Filmic: Apply auto-tune on reset&import

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#15090]
**Is your feature request related to a problem? Please describe.**
Right now, Filmic seems to use preset hardcoded values.
The autotune is usually a better start.  

**Describe the solution you'd like**
On import or reset I'd like Filmic to do this:
- run autotune
- increase the white-relative exposure by 1
- decrease the black-relative exposure by 1
That is a better starting point than hard coded values.

Additionaly, the autotune is good!
I use it often as a starting point.  
It could be improved a little:
- when it finds only a very very tiny 100% white spot, it is better to ignore it - this is often a few pixels reflection of the Sun or flash, which has no details/texture anyway.
- when it results in a wite-relative exposure of about 0, the image is very very contrasty.  In that case the image looks a lot better by increasing it around 2 stops.

**Comment by MStraeten** [comment]
that a matter of personal preferences - and depends on what’s happening in pipe before filmic comes into place. Filmic requires proper definition of mean grey using exposure - autotune doesn’t make sense until that’s done. In general the defaults are quite good initial setting (at least my experience and personal preference )

**Comment by todd-prior** [comment]
> Additionaly, the autotune is good!
> I use it often as a starting point.

If you run the Initialworkflow script you can autoexpose say based on 50% average for the image and you can run autotune with a few options for filmic... and also tweak many other starting sections.. check out https://github.com/UliGesing/Darktable-Initial-Workflow-Module

**Comment by elstoc** [comment]
I just apply keyboard shortcuts to the auto-tune and auto-exposure colour pickers, so it's really pretty easy to apply
