### ISSUE TITLE
OpenCl support is disabled

### ISSUE THREAD

**Issue by AufDerMauer** [darktable-org/darktable#15097]
### Describe the bug

Freezing at the very first start after installing darktable on new computer. Automatically disabling openCl support after some time of waiting. Darktable starts fast now, but my Nvidia GTX 1660 Super will not be used. OpenCl preferences are greyed out. Software is very useful and fast but exporting files need some time.

Four years ago I had the Nvidia GTX 1630 Ti and it works well. There was nothing special to do.

### Steps to reproduce

1. start darktable
2. go to preferences
3. the openCl options are greyed out

### Expected behavior

Darktable should support my Nvidia GTX 1660 Super

### Logfile | Screenshot | Screencast

I'm not a programmer but after reading some darktable docs I've found out how to use the cltest file. 
Here are the results, hopefully it's useful:

[darktable-cltest.txt](https://github.com/darktable-org/darktable/files/12409226/darktable-cltest.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Describe your system?

Processor: 
Intel i5-13400 (2.50 GHz)

RAM: 
16 GB

System: 
64-Bit

OS:
Win11 Home

Version:
22H2

GPU: 
Nvidia GTX 1660 Super (6GB)

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

GPU: Nvidia GTX 1660 Super (6GB) (Vers. 31.0.15.3699)

**Comment by dterrahe** [comment]
`     0.2577 [dt_opencl_build_program] problems while writing cl files` suggests window might be blocking darktable from writing the compiled opencl programs to disk. 
These would go into `C:\Users\<youraccount>\AppData\Local\Microsoft\Windows\INetCache\darktable`. Check your "controlled folder access" settings under "ransomware protection".

**Comment by ralfbrown** [comment]
Is Microsoft's OpenCL Compatibility Pack installed?  (It doesn't seem to be, but if so, **uninstall** it.)
The two likeliest causes are that you don't have a complete installation of the OpenCL support, or that for some reason the OpenCL compiler can't handle the compiler flag that darktable is passing it.  You can check if the flag is the problem by making  a copy of your `darktablerc` file and editing any lines containing `-cl-fast-relaxed-math` to remove just that string (keep the rest of each line).  Then remove the contents of the directory listed as `KERNEL DIRECTORY` in the cltest output and re-run `darktable-cltest`.

**Comment by AufDerMauer** [comment]
Thank you for answering. I will need some time to try out some steps, if I can. 
As I said above, I'm not a programmer and it sounds a little bit complicated for me. 

The path "INETCache\darktable" does not exists under "AppData" folder.

**Comment by dterrahe** [comment]
I think by default windows hides that folder. Also, I notice your account name contains non-ASCII letters. It is possible this causes problems.

**Comment by gi-man** [comment]
I think the Windows OpenCL Compatibility Pack is not installed. I agree with dterrahe, your username for windows can be a problem `\Users\Ren├®\` I dont know how to change that without creating a new windows user and breaking linkages to other software.

**Comment by AufDerMauer** [comment]
Unfortunately changing the username seems not easy and can be very difficult for my data.
I have installed too much software now, I will not start at the very beginning.

Darktable works fine for me, just exporting files need some time.
We talk about 10-12 seconds of waiting time instead of 1 second. Not enough for trouble.

Software like Blender, Gimp, Inkscape and QGis supports openCl also and it seems to work.
Maybe the handling with ASCII non conforming characters can be fixed by future updates of darktable.
At this point I think it's more easier to reinstall darktable than my whole system.

Thank you for helping.

**Comment by gi-man** [comment]
ralfbrown Can we relabel this to Windows Support? 

We handle the special characters when we navigate to Add images to Library, so it is maybe we should see if we could do something similar for the OpenCL kernel filepath.

**Comment by victoryforce** [comment]
> The path "INETCache\darktable" does not exists under "AppData" folder.

It does exists. As already written, AppData is a hidden folder, so you will not see it when browsing the file system in File Explorer. 

> Unfortunately changing the username seems difficult and can be very dangerous for my data.
I have installed too much software now, I will not start at the very beginning.

No one advises you to change your account name as a final solution. Create a new account with an ASCII-only name just to test: you can log in, run darktable / darktable-cltest and see if that fixes the problem. It's simple, fast, and will answer whether the problem is caused by non-ASCII characters in the path.

> Maybe the handling with ASCII non conforming characters can be fixed by future updates of darktable.

You can help with this by checking to see if non-ASCII characters in the path are actually causing the problem. Let me remind you, another version is write protection (controlled folder access) from your antivirus. You have not checked any of these versions.

**Comment by AufDerMauer** [comment]
I'm sorry, I was using a wrong path.
The folder "INETCache\darktable" exists and contains two folders and one file.

**1.** cached_v1_kernels_for_NVIDIACUDANVIDIAGeForceGTX1660SUPER_53130 (**folder is empty**)
**2.** cached_v1_kernels_for_NVIDIACUDANVIDIAGeForceGTX1660SUPER_53699 (**folder contains a 91.1 kb file with an unknown filetype**)
**3.** darktable-log ([darktable-log.txt](https://github.com/darktable-org/darktable/files/12420213/darktable-log.txt))

The "controlled folder access" seems to be a part of Windows Defender. 
My GData Antivirus software has disabled the Defender and it's functions. The above data was writen into the folder.

I will try it with a second ASCII conform account name, never used a second account before.

**Comment by victoryforce** [comment]
> I will try it with a second ASCII conform account name, never used a second account before.

It's very easy:
https://support.microsoft.com/en-us/windows/create-a-local-user-or-administrator-account-in-windows-20de74e0-ac7f-3502-a866-32915af2a34d#WindowsVersion=Windows_11

**Comment by dterrahe** [comment]
> cached_v1_kernels_for_NVIDIACUDANVIDIAGeForceGTX1660SUPER_53699 (**folder contains a 91.1 kb file with an unknown filetype**)

So _creating_ the file succeeds (we use the portable `g_fopen` function for that, here and elsewhere), but then renaming it to its final name fails, presumably because one of getcwd/chdir/basename/rename (are all of them) don't support utf8. I'd think it should be possible to create to file immediately with its final name under Windows (since we don't create a link, like under linux).
