### ISSUE TITLE
`darktable` Ubuntu package depends on `libicu70` which is not available on 23.04 (yet)

### ISSUE THREAD

**Issue by virtualritz** [darktable-org/darktable#15100]
### Describe the bug

See subject.

However, Ubuntu 23.04 does ship `libicu-dev`, currently at version `72.1-3`, which should suffice.

### Steps to reproduce

```
> sudo apt install darktable 
The following packages have unmet dependencies:
 darktable : Depends: libicu70 (>= 70.1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Where did you install darktable from?

distro packaging

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
Please contact your software distributor, packaging is not the responsibility of the darktable project.
