### ISSUE TITLE
[Support] Help build DT on fedora

### ISSUE THREAD

**Issue by quazardous** [darktable-org/darktable#15106]
Maybe not the right place...

I’m trying to build DT but it’s never ending…

```
✔ ~/dev/projects/darktable [master|✔] 
12:19 $ scbi  --deps --update c-darktable
2023/08/25 12:19:35 : module libavif-devel version v0.10.1 matching
2023/08/25 12:19:35 : module libavif-devel found
2023/08/25 12:19:35 : module cmake version v3.18.4 matching
2023/08/25 12:19:35 : module c-darktable=c-libavif using native variant
2023/08/25 12:19:35 : module c-libavif using native variant
2023/08/25 12:19:35 : module c-cmake using native variant
2023/08/25 12:19:35 : module exiv2-devel version v0.27.5 matching
2023/08/25 12:19:35 : module c-exiv2 using native variant

2023/08/25 12:19:36 : Building c-cmake [native] (v3.18.4)
2023/08/25 12:19:36 : native x86_64-redhat-linux
2023/08/25 12:19:36 : steps : setup config build install wrapup
2023/08/25 12:19:36 : no build needed, versions match
2023/08/25 12:19:36 : skip global install
2023/08/25 12:19:36 : End Building c-cmake [native] (v3.18.4)
```

I’ve mix the fedora wiki + scbi

the fedora command was not working

```
13:24 $ cmake --build obj -D CMAKE_INSTALL_PREFIX=/opt/darktable -D CMAKE_BUILD_TYPE=RelWithDebInfo ..
Unknown argument -D
```

**Comment by kmilos** [comment]
There should be no space after `-D`.

Please head over to https://discuss.pixls.us/ for any further user support.

This is a tracker for genuine darktable code issues.

**Comment by TurboGit** [comment]
Interesting, which SCBI version are you using?

`$ scbi --version`

**Comment by TurboGit** [comment]
I'll reopen because as the dev of SCBI I'm interested to understand why it work on Debian and not Fedora.

**Comment by quazardous** [comment]
thx for your concern

```
14:06 $ scbi --version
SCBI : v7.2-29-gc18de1e
CORE plugins : v7.2-30-gbc646ed
```

I let it run 30 minutes, is it enough ?

> There should be no space after -D.

Tried both

**Comment by TurboGit** [comment]
> I let it run 30 minutes, is it enough ?

Version is ok, yes 30 minutes is largely enough. Have you tried starting again the same command just after having interrupted it?

> >     There should be no space after -D.
> 
> Tried both

Just to be sure, this is fully independent of the scbi run, right?

**Comment by quazardous** [comment]
> Just to be sure, this is fully independent of the scbi run, right?

I've followed the minimal fedora build steps (installed the dependencies) first but cmake didn't worked (complains about non existing option).

So I tried the scbi command.

> Version is ok, yes 30 minutes is largely enough. Have you tried starting again the same command just after having interrupted it?

Yes several time

**Comment by TurboGit** [comment]
Ok, can you please run:

`bash -x scbi  --deps --update c-darktable > scbi.og`

Wait say 5 minutes, interrupt the command and attach the log here? TIA.

**Comment by quazardous** [comment]
```bash
bash -x scbi  --deps --update c-darktable >/tmp/scbi.out 2>/tmp/scbi.txt
```

[scbi.txt](https://github.com/darktable-org/darktable/files/12446555/scbi.txt)

**Comment by quazardous** [comment]
the error log complains about `OpenEXR-devel`

```bash
[root@another ~]# dnf search OpenEXR-devel
Dernière vérification de l’expiration des métadonnées effectuée il y a 0:25:54 le sam. 26 août 2023 20:42:59.
======================= Nom correspond à : OpenEXR-devel =======================
openexr-devel.x86_64 : Development files for openexr
openexr-devel.i686 : Development files for openexr
[root@another ~]# dnf install OpenEXR-devel
Dernière vérification de l’expiration des métadonnées effectuée il y a 0:28:44 le sam. 26 août 2023 20:42:59.
Le paquet openexr-devel-3.1.10-1.fc38.x86_64 est déjà installé.
Dépendances résolues.
Rien à faire.
Terminé !

```

it says already installed but it's not in the same case (`openexr-devel`)

**Comment by TurboGit** [comment]
> the error log complains about OpenEXR-devel

That's not the issue, it looks really strange maybe a bash bug given the log.

What's you bash version?

`$ bash --version`

Let's check something:

`$ which scbi`
(should output `~/.local/bin/scbi`)

And replace this binary by the one attached:

`$ cp scbi_script.txt ~/.local/bin/scbi`

[scbi_script.txt](https://github.com/darktable-org/darktable/files/12453310/scbi_script.txt)

**Comment by quazardous** [comment]
```bash
$ bash --version
GNU bash, version 5.2.15(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>

Ceci est un logiciel libre ; vous être libre de le modifier et de le redistribuer.
AUCUNE GARANTIE n'est fournie, dans les limites permises par la loi.
```

```bash
$ which scbi
~/.local/bin/scbi
```

```bash
mv ~/Téléchargements/scbi_script.txt ~/.local/bin/scbi
chmod +x ~/.local/bin/scbi
```

[scbi_0828.txt](https://github.com/darktable-org/darktable/files/12457267/scbi_0828.txt)

**Comment by TurboGit** [comment]
Ok, so to me there is an issue with bash. The log is saying that after returning from the function `check-pkg` (return 1 at the end of the log) nothing happens, but here we have:

```
        MES="$(check-pkg $module:$ref)"

        if [[ $? = 0 ]]; then
            return 0

```

So after `MES=...` there is some other commands to execute. It seems bash is somehow locked in check-pkg and cannot return.

You may want to try changing:

`        MES="$(check-pkg $module:$ref)"`
to

`        MES=""`

And see if the lock is still present.

**Comment by quazardous** [comment]
Seems to pass

now it's stuck at 

`2023/09/14 11:08:21 : get sources from git`

[scbi.txt](https://github.com/darktable-org/darktable/files/12607311/scbi.txt)
