### ISSUE TITLE
Create a background task for XMP startup update

### ISSUE THREAD

**Issue by quazardous** [darktable-org/darktable#15105]
**Is your feature request related to a problem? Please describe.**

For large photos libraries, turning on the update XMP at startup feature can delay the DT splash screen and main window.

It can be very confusing and can lead to try to open another DT (wich will be bocked by DB lock).

**Describe the solution you'd like**

The XMP startup update could occur after the main window is open and ready and be handled by a background task with a progression (or something) in the status bar.

Ideally a flag on photos not yet checked could be usefull. 

**Alternatives**
If background task is too complicated, a progression modal could be shown before the main window appears. 

**Additional context**

It can be related to #14686

**Comment by ralfbrown** [comment]
#17202 will provide an updating progress report on the sidecar check.
