### ISSUE TITLE
Multiple instances of Diffuse or Sharpen corrupted when copying and pasting between images

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#15112]
### Describe the bug

When a selective copy/paste or a style involves multiple instances of diffuse and sharpen, the instances aren't properly copied.  One or more instances are lost and the order of the modules is different.

### Steps to reproduce

1. Open an image in scene referred mode
2. Move the default diffuse or sharpen instance down to just above denoise(profiled).  Set the preset to denoise fine.  Turn it off.
3. Create a new instance of diffuse of sharpen and set the preset to denoise coarse. Turn it off.
4. Create a new instance of diffuse or sharpen and set the preset to sharpen AA filter.  Move the intstance to just below input color profile. Turn it off.
5. Create a new instance of diffuse or sharpen and move it just below filmic rgb.  Set the preset to local contrast. Turn it off.
6. Go to lighttable.  Do a selective copy and select the diffuse or sharpen modules and module order.
7. Paste into a new image and open it.
8. Observe the denoise fine instance is in the correct place (above denoise(profiled).
9. Observe the denoise coarse instance is just below filmic rgb.
10. Observe the other 2 instances are gone.

### Expected behavior

All the instances should be pasted in the correct order

### Where did you install darktable from?

darktable.org

### darktable version

Current master.  In 4.4.2 it the correct number of instances are copied, but one of the presets disappears.

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

Intel i7-12800HX
32 GB Ram
Nvidia 3070 GPU

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia 535

**Comment by wpferguson** [comment]
Have to run right now (grand daughter's birthday party).  I'll try and bisect in 10hrs or so

**Comment by wpferguson** [comment]
Checked 4.4.2 and it has all the instances, but the denoise fine instance loses it preset when pasted or applied.

**Comment by wpferguson** [comment]
Bisect points to 01bd8c633f84ba42925eceec472764c0bc1a81ba.  @TurboGit this one's yours.  All 4 instances get pasted but they are grouped together and in the wrong order.  I'm going to run another bisect and and the commit where it starts dropping instances.

**Comment by wpferguson** [comment]
Bisect for dropped instance is 0e28bab396b95e4ef172f94effebfc42bedf29ad, @TurboGit.  I think a later commit took care of the ordering and probably put everything in the correct place except for the fact that some of the instances were missing.

**Comment by wpferguson** [comment]
Did some debugging

Found the problem of the disappearing instance

Added print statements to src/common/history.c from lines 360 to 385 to try and understand the logic and got the following:

```
in dt_history_copy_and_paste_on_image
    29.2431 [history_copy_and_paste_on_image_merge] selected modules
    29.2431   module              diffuse, multiprio 0
    29.2431   module              diffuse, multiprio 1
    29.2431   module              diffuse, multiprio 2
    29.2431   module              diffuse, multiprio 3
  module              diffuse, multiprio 0
mod_same_prio = mod_dest
module will be replaced
  module              diffuse, multiprio 1
  module              diffuse, multiprio 2
mod_unused = mod_dest
module will be replaced
  module              diffuse, multiprio 3

This is probably due to all the instances being disabled when they are copied and pasted.  The first instance to be replaced seems correct, but then the third instance (2) gets replaced instead of added.

To kind of test this theory, I enabled all the instances and did a copy and paste.  All 4 instances pasted at the correct locations in the history stack but the instance order was corrupt (instead of the denoise instances being just above denoise(profiled, they were just before filmic rgb and just before input color profile, almost as if they were reversed).
```

**Comment by TurboGit** [comment]
@wpferguson : I think I have the fix in #15127, can you please check if all is ok on your side with this patch? TIA.

**Comment by wpferguson** [comment]
All 4 modules got posted, but the order was wrong.

Here's what was copied from:

![copied from](https://github.com/darktable-org/darktable/assets/1634891/3deb6484-027e-4d88-86c8-d68317a56b17)

and here's the pasted result

![pasted result](https://github.com/darktable-org/darktable/assets/1634891/d3be53c0-8667-4af5-b051-73df49056de8)

**Comment by TurboGit** [comment]
> I created a style with the 4 diffuse or sharpen modules, then applied it to an image and all of the instances showed up in the correct places and with the correct order.

You really mean that with styles all is fine and so the issue only occurs when copy/paste is done?

**Comment by TurboGit** [comment]
@wpferguson : I've pushed a new version that should copy in proper order the modules' instances now.

**Comment by wpferguson** [comment]
That works!  Thanks @TurboGit
