### ISSUE TITLE
[FR] retain harmony guides in xmp

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#15115]
**Is your feature request related to a problem? Please describe.**

Colour harmony guides set in histogram module typically only apply to an individual photo, yet are not remembered for that photo. If I open a new photo, apply a new harmony, then return to the previous photo, the previous harmony for it has been lost, while the new harmony does not apply to it.

**Describe the solution you'd like**

If possible, to save the colour harmony guides to xmp, so that each photo will remember their previous setting, and load when opened. If no harmony has been set, then don't write any harmony guides to xmp.

**Comment by TurboGit** [comment]
Yes it is possible to save this into the XMP. Let's try this for 4.6.
