### ISSUE TITLE
Cannon R50

### ISSUE THREAD

**Issue by DisturbedAngel** [darktable-org/darktable#15111]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by Nilvus** [comment]
Seems that you do not provide samples as explained there and you add no info or ask (when searching on raw.pixl.us, I see no samples). Thus, darktable could support that camera only when Libraw will support it. I so close.

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/darktable/issues/14574

**Comment by DisturbedAngel** [comment]
But I did actually upload two pictures
