### ISSUE TITLE
Green tint with the RAW Chromatic Aberrations module

### ISSUE THREAD

**Issue by yuri1969** [darktable-org/darktable#15121]
### Describe the bug

Enabling the RAW Chromatic Aberrations module brings a green tint on ARW files from Sony ILCE-7.

Reportedly the implementation comes from RawTherapee. Thus it is possible to compare them both.

The _avoid colorshift_ flag reduces the introduced tint in RawTherapee although it does nothing in Darktable.

### Steps to reproduce

1. Open an ARW file containing a portion of earthy tones
2. Enable the _raw chromatic aberrations_ module
3. Compare on/off colors

### Expected behavior

Darktable should remove the green tint as RawTherapee does.

### Logfile | Screenshot | Screencast

![raw_ca_off](https://github.com/darktable-org/darktable/assets/13468636/07eec305-e7c1-4f9c-a080-10ddff112dc5)
![raw_ca_on](https://github.com/darktable-org/darktable/assets/13468636/29ca0f71-8a2b-4122-840a-c995df71ee17)

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Are you using OpenCL GPU in darktable?

No

**Comment by jenshannoschwalm** [comment]
Unfortunately the problem rises from the color coeffs taken. So the correction in dt for some files doesn't work as good. You might use "as shot" in the temperature module for better results.

**Comment by jsmucr** [comment]
I have the same issue with my RW2 files. But it was there way before 4.4 came out.

**Comment by jenshannoschwalm** [comment]
I checked again the dt ca correction code vs what is in rt as the reference mplementation. All good to me.

The reason for some differences is in fact the differing coeffs presented to this module. I really think we can't do better atm, same problem for all modules between temp and demosaic btw.

So - unfortunately - i don't see a chance for a "fix".

**Comment by wpferguson** [comment]
Would it be possible to switch white balance to as shot to get the correct coefficients (and maybe store them for reuse), then switch back to camera reference?  

This affect denoise profiled also.

**Comment by jenshannoschwalm** [comment]
I thought about that for some time. The highlights module is also affected so I was interested a lot. 

We could probably
1. get the D65 parameters and keep them
2. Get the coeffs given by temperature module
3. always process temperature with 'as shot'
4. introduce a hidden module that process the difference matrix. But where should that be? And we can't be sure that "as shot" is always a safe bet.

**Comment by wpferguson** [comment]
> introduce a hidden module that process the difference matrix. But where should that be? And we can't be sure that "as shot" is always a safe bet.

We know that "camera reference" coeffs are not correct for input , so I think we would move from not being correct to being correct most of the time.

If I enable all modules and look at the pixelpipe, highlight reconstruction is just above white balance so the hidden module should probably be between them.

**Comment by wpferguson** [comment]
@rawfiner any thoughts?

**Comment by jenshannoschwalm** [comment]
> If I enable all modules and look at the pixelpipe, highlight reconstruction is just above white balance so the hidden module should probably be between them.

highlights reconstruction would love better coeffs as cacorrect :-) So the hidden correction should be probably just after demosaic ...

**Comment by rawfiner** [comment]
Even denoise profiled would love better coeffs. Best solution in my opinion would maybe be to reverse raw white balance before input color profile (actually not exactly reverse, but remove coeffs used and put back the camera reference coeffs). Note that we would need this only when chromatic adaptation is "modern", i.e. done by color calibration module.

**Comment by jenshannoschwalm** [comment]
Coming back to the original reported issue, this needs further investigation ...

**Comment by jenshannoschwalm** [comment]
@yuri1969 i got it :-)

**Comment by yuri1969** [comment]
I can confirm the _avoid colorshift_ checkbox actually works now 🎉
Thanks
