### ISSUE TITLE
Improving darktable's CLI: a proposal for enhanced output

### ISSUE THREAD

**Issue by fabiosirna** [darktable-org/darktable#15120]
I better described the problem statement and the solution in a [comment](https://github.com/darktable-org/darktable/issues/15120#issuecomment-1696476694) below.

Re-editing to avoid duplicates and keep the history.

---

**Is your feature request related to a problem? Please describe.**

I'm doing some benchmark test with darktable-cli and I just released that an important information is missing in the output, the darktable version. 

**Describe the solution you'd like**

Something like the output of `darktable-cli --version` at the beginning:

```
this is darktable-cli 4.5.0+320~gd0dcf03649-dirty
copyright (c) 2012-2023 johannes hanika, tobias ellinghaus

output file already exists, it will get renamed
[dt_detect_cpu_features] Not implemented for this architecture.
[dt_detect_cpu_features] Please contribute a patch.
     0,0000 [dt_init] SSE2 is unavailable, some functions will be noticeably slower.
[...]
```

**Alternatives**

I'm just adding this manually to my logs, that I want to keep for future reference.

**Comment by wpferguson** [comment]
darktable-cli already outputs version

```
$ /opt/darktable45/bin/darktable-cli --version
this is darktable-cli 4.5.0+371~g10652b32a3
copyright (c) 2012-2023 johannes hanika, tobias ellinghaus
```

```
$ /opt/darktable45/bin/darktable --version
this is darktable 4.5.0+371~g10652b32a3
copyright (c) 2009-2023 johannes hanika
```
or did you want the rest of the information that is produced with darktable --version, i.e.

```
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.2.0
  Colord support enabled
  gPhoto2 support enabled
  G'MIC support enabled (compressed LUTs will be supported)
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support disabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```

**Comment by fabiosirna** [comment]
hi @wpferguson 

if you try to run some performance test like:

**CPU only**
```
darktable-cli image.raf image.raf.xmp image.jpg --core --disable-opencl -d perf > performance.log
```

**CPU + GPU, using OpenCL**

```
darktable-cli image.raf image.raf.xmp image.jpg --core -d perf -d opencl > performance.log
```

There are no info about darktable's version that generated that output.
My suggestion is to add it in the first line the same output of `darktable-cli --version`. Hope it helps!

**Comment by kmilos** [comment]
I guess you can just do:
```
darktable-cli --version > performance.log
darktable-cli image.raf image.raf.xmp image.jpg --core --disable-opencl -d perf >> performance.log
```
etc.

**Comment by fabiosirna** [comment]
After opening this FR I just realized that not only darktable-cli but also all the others command that are dependent on darktable (darktable-cltest, darktable-generate-cache) can be improved in terms of output.

What I'm trying to say is that I think there is a better approach to design a command line user interface. There are best practices and I think darktable should follow them. Take blender for example, or other software (e.g. vim, rsync) and see their help. I'm attaching the output as a reference.

They all provide to the user all the important information to understand how they works, aside important information like the license and help or description of the parameters.

I made an attempt for a better output of darktable that can be used as a reference. I took the content from one of the latest nightly I built and be inspired by Blender CLI.

- added version
- license and copyright information
- darktable description and all the important link to follow the project, the community and the documentation
- divided the content by usage, options and debugging; I took most of the content from the [user manual](https://docs.darktable.org/usermanual/) but I do not have the knowledge to describe the options for the debugging part and I'll need some help; the idea behind this hierarchy is to group all the parameters for the main usage of the software from the debugging stuff;  
-  in my build (Apple Silicon) there are some debugging information that are printed as the very first lines; I believe this kind of things are important and they should be displayed at the very bottom.

What do you think? I'd like to hear different opinions.

Here below the current help and my proposed redesign.

[darktable--help_current.txt](https://github.com/darktable-org/darktable/files/12458441/darktable--help_current.txt)
[darktable--help_proposed.txt](https://github.com/darktable-org/darktable/files/12458442/darktable--help_proposed.txt)

Examples and reference I took inspiration from:

[blender--help.txt](https://github.com/darktable-org/darktable/files/12458440/blender--help.txt)
[rsync--help.txt](https://github.com/darktable-org/darktable/files/12458443/rsync--help.txt)
[unzip--help.txt](https://github.com/darktable-org/darktable/files/12458444/unzip--help.txt)
[vim--help.txt](https://github.com/darktable-org/darktable/files/12458445/vim--help.txt)

**Comment by jenshannoschwalm** [comment]
Has been fixed in master

**Comment by fabiosirna** [comment]
@jenshannoschwalm thanks 🙏
I saw some changes in the log during some tests and had a hunch that someone had contributed. Grazie mille!
