### ISSUE TITLE
Known Lens Not Found

### ISSUE THREAD

**Issue by MitchWoodin** [darktable-org/darktable#15126]
### Describe the bug

Using the latest version of Darktable I have lenses that I've always used and had no issues with are now "not found". It seems like it finds the right lens in the dropdowns but I still get an error.
![image](https://github.com/darktable-org/darktable/assets/42667068/f40d79b1-ee48-489e-8f3e-f515d2cd4ea9)

### Steps to reproduce

Import images with known lens
Enable "lens correction"
Error: "camera/lens not found"

### Expected behavior

Darktable should recognise my camera and lens as it previously did.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Mint 21.1

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment]
Is this a snap installation? Is your lensfun up to date (eg. lensfun-update-data?

**Comment by ptilopteri** [comment]
on openSUSE it is lensfun-update-data but I don't know mint.

**Comment by MitchWoodin** [comment]
So is the lensfun data separate to the Darktable install?
Or does darktable install that data with it? If so where does it install to?

**Comment by ptilopteri** [comment]
> So is the lensfun data separate to the Darktable install?   yes

**Comment by pehar1** [comment]
> How do I update the lensfun? Are there any docs on this?

https://lensfun.github.io/manual/v0.3.2/lensfun-update-data.html

On Ubuntu, the tool `lensfun-update-data` is not installed with the `liblensfun` package. There is a separate package (named `liblensfun-bin`) containing `lensfun-update-data` and two other tools. Unfortunately I don't know how the organization of the packages looks like under Mint.

Did you try running `lensfun-update-data` from the commandline ? What is the result ?

**Comment by MitchWoodin** [comment]
![image](https://github.com/darktable-org/darktable/assets/42667068/32a23d13-a15b-4ab6-96ab-f0ae86c7ef5e)

This is what I get

**Comment by gi-man** [comment]
Let's start with the simple first. Post the output of darktable --version

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/darktable/issues/4951

You might want to check what the lens gets detected as (check e.g. the "image information" panel), determine its actual ID number, and then assign the expected string to that ID in your `~/.exiv2` (or `exiv2.ini` if on Windows) [manually](https://exiv2.org/manpage.html#config_file).

**Comment by Nilvus** [comment]
I so close. Thanks @kmilos

**Comment by MitchWoodin** [comment]
I'm not entirely sure why/how it solved the issue. But my solution was deleting the tamron .xml from `/usr/share/lensfun/version_1` and then copying the tamron .xml from `usr/share/lensfun` back into that previous folder. I'm guessing that there is some differences between the two files that existed there. But not entirely sure what they were. I deleted the initial one without checking it initially...

**Comment by MitchWoodin** [comment]
Okay, so actually just deleting that `version_1` folder completely solves the issue. I had a similar issue with another of my lenses. It seems like the .xmls inside the versioned folder don't contain all the lenses that are in the parent folder. Removing the versioned folder seems to make darktable not look at that folder. Not sure if there is a cleaner solution than just removing that entire folder

**Comment by kmilos** [comment]
Please close the issue then if resolved.
