### ISSUE TITLE
Git master : Where have the pixel tiles gone in darkroom at 1600% image zoom level?

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#15137]
### Describe the bug

If I set darkroom magnification to 1600% in darktable git master I get a rendering of the raw file which looks a bit low-pass filtered. In darktable 4.4.2 (and earlier) I get a more pixelated rendering. The exported output looks identical from git master darktable and darktable 4.4.2.

The examples below are darktable default modules and order for a new raw import. 
 
git master demosaic = RCD @ darkroom image zoom level 1600%
![git-master-1600](https://github.com/darktable-org/darktable/assets/42386052/3c326d6b-1abf-4460-819c-d0de290c09f5)

v4.4.2 demosaic = RCD @ darkroom image zoom level 1600%
![v442-1600](https://github.com/darktable-org/darktable/assets/42386052/0bae2ecc-5c1f-42bd-a920-a52119fc9590)

### Steps to reproduce

1. Build git master and use default configuration.
2. Import or open a rawfile in order to go to darkroom.
3. Set image zoom level to 1600%.
4. A soft low-pass filtered image is rendered in darkroom without any visible pixels (tiles).

One example with demosaic = RCD can be found in **describe the bug** above. Another example with demosaic = photosite color, for even better visibility is attached below.

The exported output file (jpg, for instance) is identical between git master and v 4.4.2. The issue is just that darkroom renders a softer image at 1600%. 

Note: I used 800%-1600% to compare effects of demosaic algorithms, so 1600% zoom level can have some usability. But I must admit that I do not use 1600% that often.

git master demosaic = photosite color @ darkroom image zoom level 1600%
![git master-photosite-1600](https://github.com/darktable-org/darktable/assets/42386052/16aa1f26-3e9c-4ee0-bb29-86fb491adfb8)

v4.4.2 demosaic = photosite @ darkroom image zoom level 1600%
![v442-photosite-1600](https://github.com/darktable-org/darktable/assets/42386052/7164fc40-7930-456d-843b-842bf73dd466)

### Expected behavior

Darktable should render the pixel tiles at 800%-1600% (like v4.4.2) instead of a low-pass filtered version. This could be useful to invesigate the selection of demosaic algorithm, for instance.

### Logfile | Screenshot | Screencast

Check **Describe the bug** and **steps to reproduce**.

### Commit

4.5.0+411~g54f24cfa7f, but I think this issue has been around for a while. I have not yet bisected git master

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+411~g54f24cfa7f, but I think this issue has been around for a while. 

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12.1

### Describe your system?

- OS : Linux debian 6.1.0-11-amd64 1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
- Linux - Distro : Debian 12.1
- Memory : 16 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : Nvidia Driver Version:  25.125.06-1~deb12u1 amd64
- OpenCL installed : Yes,  OpenCL 3.0 CUDA 12.0.151
- OpenCL activated : Yes
- Xorg : X11
- Desktop : Gnome 43.6
- GTK+ :  libgtk-4-dev 4.8.3+ds-2 amd64
- gcc : (Debian 12.2.0-14) 12.2.0
- cflags : 
- CMAKE_BUILD_TYPE : Release

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Quadro RTX 4000, Nvidia Driver Version: 25.125.06-1~deb12u1 amd64

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Can you reproduce with another darktable version(s)? **This issue is in git master, but I have not bisected yet**
Can you reproduce with a RAW or Jpeg or both? RAW-file-format/Jpeg/both: **raw**
Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes, any raw file fresh or with history**
If the issue is with the output image, attach an XMP file if (you'll have to change the extension to .txt)
Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")?  **yes**
Do you use lua scripts?**no**.
        What lua scripts start automatically?
        What lua scripts were running when the bug occurred?

**Comment by ralfbrown** [comment]
ISTR that for zoom > 100%, dt tells Gtk to scale the image.  Something must have changed there so that it doesn't use simple nearest-neighbor pixel replication anymore.  Current master +419~g45bd3631c2 shows the smoothing, +326~g64d57ebac6 does not.

**Comment by jenshannoschwalm** [comment]
In `view.c` this part _tries_ to do that correctly
```
  GdkPixbuf *scaled = gdk_pixbuf_scale_simple(pixbuf, w, h, GDK_INTERP_HYPER);

  cairo_save(cr);

  cairo_translate(cr, ceilf(.5f * (width - w)), ceilf(.5f * (height - h)));

  cairo_pattern_set_filter
    (cairo_get_source(cr),
     zoom_scale >= 0.9999f ? CAIRO_FILTER_FAST : darktable.gui->dr_filter_image);
  gdk_cairo_set_source_pixbuf(cr, scaled, 0, 0);

  cairo_paint(cr);
```

1. missing `cairo_restore()` ?
2. The ` GDK_INTERP_HYPER` is **very** slow, probably causing the slower 'refresh'

But that's both not fixing the issue ...

**Comment by KarlMagnusLarsson** [comment]
Git bisect:

c1808fb53d38dc121b239ae14f46e752ee3df940 is the first bad commit
commit c1808fb53d38dc121b239ae14f46e752ee3df940
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Tue Aug 15 19:38:54 2023 -0400

    full resolution panning and white border jump fix

 src/develop/develop.c |   2 -
 src/libs/duplicate.c  |   2 +-
 src/libs/snapshots.c  |  14 +--
 src/views/darkroom.c  | 277 ++++++--------------------------------------------
 src/views/view.c      | 114 ++++++++++++++-------
 src/views/view.h      |   5 +-
 6 files changed, 121 insertions(+), 293 deletions(-)

**Comment by dterrahe** [comment]
> In `view.c` this part _tries_ to do that correctly

`dt_view_paint_pixbuf` only seems to be used by slideshow. I have not tried to fix that as well.

> 1. missing `cairo_restore()` ?

Looks like it.

**Comment by KarlMagnusLarsson** [comment]
After some further testing I get new artifacts, like flashes of noise over large areas. 

Steps to reproduce:

1. Build PR
2. Select raw in lighttable and go to darkroom
3. zoom in so image does not fit view.
4. Left click and drag drag to move around
5. Sudden flashes of noise bursts in rectangular areas, or the entire view. See screenshot

![Screenshot from 2023-08-30 23-37-05](https://github.com/darktable-org/darktable/assets/42386052/8afc4755-840c-4139-b4bf-5015f0a6ae49)

**Comment by KarlMagnusLarsson** [comment]
And now I can not trigger the artifacts in https://github.com/darktable-org/darktable/issues/15137#issuecomment-1699888316, anymore. 

I can now pan around a moderately zoom without issues and I see the tiles again at 1600%.

If "flashes of noise over large areas." reappear I will file a separate issue report.
