### ISSUE TITLE
Applying styles without keyboard shortcuts

### ISSUE THREAD

**Issue by pbischoff** [darktable-org/darktable#15132]
I have multiple styles defined for my photographs and don't want to have to remember all the shortcuts for them. It's slowing down my workflow significantly because I have to open the settings and search for the correct shortcut. I cannot find a solution currently to apply the styles without having to define and know shortcuts while being in the Darkroom (version 4.4.2).

I would like to see the styles in a list in the history stack to select by mouse clicks or have a separate module to create styles from the current history stack and select and apply saved styles.

**Comment by gi-man** [comment]
Are you asking for a style module?

https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/styles/

**Comment by ralfbrown** [comment]
Or the styles menu accessed via the 'three-circles' button at bottom left of the main image in darkroom view?

**Comment by wpferguson** [comment]
https://docs.darktable.org/usermanual/4.2/en/module-reference/utility-modules/lighttable/styles/

and 

https://docs.darktable.org/usermanual/4.2/en/module-reference/utility-modules/darkroom/history-stack/

specifically the part about the button to the right of the compress history stack button

**Comment by pbischoff** [comment]
Did not find the documentation about the 'three-circles' button in the bottom panel layout. Thank you to @wpferguson  and @ralfbrown. Will close this issue.
