### ISSUE TITLE
Rename "write sidecar file for each image" to "create sidecar file for each image"

### ISSUE THREAD

**Issue by fulldecent** [darktable-org/darktable#15144]
### Describe the bug

.

### Steps to reproduce

discussed at https://github.com/darktable-org/darktable/issues/3632

### Where did you install darktable from?

darktable.org

### darktable version

master

### What OS are you using?

Mac

### What is the version of your OS?

13

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
See https://github.com/darktable-org/darktable/issues/3632#issuecomment-1701345684
