### ISSUE TITLE
Dutch translations missing from 4.4.0

### ISSUE THREAD

**Issue by psik-sh** [darktable-org/darktable#15143]
### Describe the bug

In Darktable 4.2.1 the interface language can be set to Dutch.
![AnyDesk-48e7e83e_msi_Jc5y8PcuR9](https://github.com/darktable-org/darktable/assets/81476953/f0644ac6-d7cd-46a5-9f85-86391e1b3c7b)

In Darktable 4.4.0 that language is missing (among others, it seems).
![AnyDesk-48e7e83e_msi_ZFisBQhphD](https://github.com/darktable-org/darktable/assets/81476953/b58447f5-b79f-40f1-ab2c-f1f000cb6944)

Is that due to missing translations, or is this a bug?

### Steps to reproduce

1. Go to Settings.
2. Go to General.
3. Click on the language selector.

### Expected behavior

darktable should still be available in Dutch

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro 22H2

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
> Is that due to missing translations

Yes. See e.g. https://github.com/darktable-org/darktable/issues/14837

**Comment by victoryforce** [comment]
> Is that due to missing translations

Yes, there can be no other reasons. At the time of the string freeze, the Dutch translation [had 336 fuzzy translations and 62 untranslated messages](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06754.html) (and did not receive new translations until release). We have much stricter requirements, unfinished translations are not rejected only if they have less than 20 untranslated lines and less than 50 in the fuzzy state.
