### ISSUE TITLE
it doesn't work on win

### ISSUE THREAD

**Issue by petricho123** [darktable-org/darktable#15146]
### Describe the bug

I downloaded the program from this site, https://www.darktable.org

and i installed and I double-clicked to execute, but there is no response

### Steps to reproduce

1. intalled
2. run
3. error

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2-win64

### What OS are you using?

Windows

### What is the version of your OS?

window 10 edu, ver 22h2

### Describe your system?

cpu 3200g

ram 8gb*2

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by Nilvus** [comment]
Most users install darktable 4.4.2 on Windows and run the program without error. So it's something on your side that block that. You precise nearly nothing as your step by step is not reproductible on another system. And as this place is for possible bugs on darktable code, I close. For your issue and to have help, better to use pixls.us forum: https://discuss.pixls.us/c/software/darktable/19
Try to add on your post on that forum, more infos (precise system you have, CPU 3200g and 8gb*2 do not help). You will find more infos on system specs in Windows 10. See: https://support.microsoft.com/en-us/windows/view-your-system-info-a965a8f2-0773-1d65-472a-1e747c9ebe00
And if you have precise message error or log provided, add it on your future post in pixls.us.
