### ISSUE TITLE
Intel OpenCL not available anymore?

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#15150]
### Describe the bug

After compiling the latest master, darktable disables my Intel OpenCL device. It only seems to be enabled when "Other platforms" is selected in opencl settings.

### Steps to reproduce

1. Run darktable-cltest
2. Note that OpenCL is no longer active.
3. If "other platforms" is checked, then opencl is available.

### Expected behavior

not disable opencl that was previously working.

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+429~gefc8d2ff5c

### What OS are you using?

Linux

### What is the version of your OS?

Archlinux

### Describe your system?

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimizations enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.2.0
  Colord support enabled
  gPhoto2 support enabled
  G'MIC support enabled (compressed LUTs will be supported)
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

Intel NEO

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

4.5.0.r420.ged5442e1c5 has working OpenCL.

Output from darktable-cltest:
```
❯ darktable-cltest
     0.2149 [dt_get_sysresource_level] switched to 1 as `default'
     0.2149   total mem:       15727MB
     0.2149   mipmap cache:    1965MB
     0.2149   available mem:   7863MB
     0.2149   singlebuff:      491MB
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
[opencl_init] found 1 platform
[check platform] platform 'Intel(R) OpenCL Graphics' with key 'clplatform_intelropenclgraphics' is NOT active
[opencl_init] found 0 device
[opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.
```
Output from previously working version (4.5.0+420)
```
     0.2166 [dt_get_sysresource_level] switched to 1 as `default'
     0.2166   total mem:       15727MB
     0.2166   mipmap cache:    1965MB
     0.2166   available mem:   7863MB
     0.2166   singlebuff:      491MB
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl library 'libOpenCL' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) HD Graphics 520'
   PLATFORM NAME & VENDOR:   Intel(R) OpenCL Graphics, Intel(R) Corporation
   CANONICAL NAME:           intelropenclgraphicsintelrhdgraphics520
   DRIVER VERSION:           23.22.26516
   DEVICE VERSION:           OpenCL 3.0 NEO
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          12582 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 256 256 256 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /usr/share/darktable/kernels
   KERNEL DIRECTORY:         /home/---/.cache/darktable/cached_v2_kernels_for_IntelROpenCLGraphicsIntelRHDGraphics520_232226516
   CL COMPILER OPTION:
   KERNEL LOADING TIME:       0.0608 sec
[opencl_init] OpenCL successfully initialized. Internal numbers and names of available devices:
[opencl_init]           0       'Intel(R) OpenCL Graphics Intel(R) HD Graphics 520'
[opencl_init] FINALLY: opencl is AVAILABLE and ENABLED.
```

**Comment by MStraeten** [comment]
that’s intentional, the way activating/deactivating opencl changed. So have a look at the description of the latest opencl commits …

**Comment by jenshannoschwalm** [comment]
@groutr that's a bug :-) Your platform has no predefined driver name found so only available via others. Will fix asap
