### ISSUE TITLE
Glib-CRITICAL notice

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#15153]
### Describe the bug

when starting darktable from cl and working images, I get constant notices:

(darktable:29711): Glib-CRITICAL **: 08:21:04.207: g_stristr: assertion 'haystack != NULL' failed

### Steps to reproduce

start dt from control line
work an image, change to next or previous image
notice appears 8 times on command line

### Expected behavior

should not receive notice

### Where did you install darktable from?

darktable.org

### darktable version

  4.5.0+429!gefc8d2ff 5c

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed 20230828

### Describe your system?

X11
gtk3 3.24.38
32GB
 Kernel: 6.4.9-1-default
gcc v: 13.2.1
12th Gen Intel Core i7-12700
NVIDIA GA104 [GeForce RTX 3060 Ti Lite Hash Rate] 6GB
nvidia v: 535.86.05
OpenGL v: 4.6.0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GA104 [GeForce RTX 3060 Ti Lite Hash Rate] 6GB nvidia v: 535.86.05

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

can reproduce
editing raw NEF images
don't know about non-raw

**Comment by jenshannoschwalm** [comment]
Just a wrong build with some leftovers?

**Comment by ptilopteri** [comment]
I use the same script on five boxes.  the build log is:
  http:/wahoo.no-ip.org/~paka/dt.build.txt

tks

**Comment by jenshannoschwalm** [comment]
The "up-to-date" messages might hint that you haven't done an uninstall before so "left over" files???

**Comment by ptilopteri** [comment]
I clean "build" after every compile.  Is that not sufficient?
Or are you referring to uninstalling dt?  I cannot remember doing that on any of my 5 local installs.


tks

**Comment by jenshannoschwalm** [comment]
I mean uninstall. I always do that in the rebuild cycle ...

**Comment by ptilopteri** [comment]
trying your suggestion.

ok, uninstalled the openSUSE Tumbleweed rpm and removed the buiild output directory and reinstalled rpm and rebuilt master.

 still have same command line output  ??

tks

**Comment by ralfbrown** [comment]
`g_stristr` is not present anywhere in the darktable codebase, so code in some other library (presumably either Glib or Gtk) is calling it.  That will make finding the ultimate cause difficult.

I don't remember the details, but you can set a breakpoint on the function that prints the Glib-CRITICAL message (probably needs to be done after darktable's main() starts since it's in a shared library), then get a backtrace to find where it was called from.  Then restart darktable, set breakpoint(s) as appropriate and watch the parameters until things go off the rails.

**Comment by ptilopteri** [comment]
closing as apparently not dt issue
