### ISSUE TITLE
Highlight reconstruction fails with EXR Image

### ISSUE THREAD

**Issue by hcw70** [darktable-org/darktable#15156]
### Describe the bug

I have recently opened an EXR image which i had imported into darktable some time ago (nov 2022) with an
older darktable version.

When now opening the image in DT 4.4.2, only the upper third of the image is visible, in the preview and also in the
darkroom view.
The file itself is ok, since when opening with gimp or with an image viewer, it shows full content. See screenshot.

It re-appears fully in DT as soon as i click the module "filmic rgb" one below "highlight reconstruct". See screenshot.

As soon as i click in "highlight reconstruct" or any above that in the history, the image is broken again.

### Steps to reproduce

Since i dont want to upload my full image here, i have attached my xmp file.
1. Plug in an EXR file matching my XMP file, so it gets hopefully reproducible.
2. Import image into DT.
3. Go to Darkroom. Image should be broken
4. click into history step 6, Image should be ok.

XMP file:

[2022-11-05 22-28-13 (C,S2).exr.xmp.txt](https://github.com/darktable-org/darktable/files/12500237/2022-11-05.22-28-13.C.S2.exr.xmp.txt)

Screenshot showing the bug (click anything later than step 6):

![dt-bug-2](https://github.com/darktable-org/darktable/assets/1888459/506715ba-66ae-4065-ac19-1411ad0ff186)

Screenshot if clicking in step 6:
![Dt-Bug-1](https://github.com/darktable-org/darktable/assets/1888459/20293013-8809-4b52-b209-de582651b1c5)

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

NVidia RTX 3060 present, which is used for OpenCL rendering.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia RTX 3060

**Comment by hcw70** [comment]
When running with 

flatpak run  org.darktable.Darktable -d opencl  

i get an error from highlights:

```
    23,0393 [dt_opencl_check_tuning] use 5537MB (tunemem=ON, pinning=OFF) on device `NVIDIA CUDA NVIDIA GeForce RTX 3060 Laptop GPU' id=0
    23,1797 [dt_ioppr_transform_image_colorspace_cl] in `highlights', profile `linear Rec2020 RGB', invalid conversion from IOP_CS_RGB to IOP_CS_RAW
    23,1798 [dt_ioppr_transform_image_colorspace_cl] had error: CL_INVALID_KERNEL
    23,1798 [pixelpipe_process_CL]       [full]         highlights             (   0/   0) 1769x1179 scale=0,2940 --> (   0/   0) 1769x1179 scale=0,2940 couldn't run module on GPU, falling back to CPU
    23,1855 [_transform_matrix] invalid conversion from IOP_CS_RGB to IOP_CS_RAW
    23,1855 [dt_ioppr_transform_image_colorspace] in `highlights', profile `linear Rec2020 RGB', invalid conversion from IOP_CS_RGB to IOP_CS_RAW
    23,5264 [_transform_matrix] invalid conversion from IOP_CS_RGB to IOP_CS_RAW
    23,5264 [dt_ioppr_transform_image_colorspace] in `highlights', profile `linear Rec2020 RGB', invalid conversion from IOP_CS_RGB to IOP_CS_RAW




```

**Comment by jenshannoschwalm** [comment]
@TurboGit don't know how to handle this "best way".

In earlier dt versions we allowed the highlights module also for non-raws so we might have a valid history with module enabled (not only for exr but also for tiffs or 16bit pngs ...) So we have in fact two issues here
1. old edits might have this module enabled but we currently don't want it to be
2. a wrong colorspace conversion for such cases.

Although i doubt the value of highlights being enabled for such images there might be use cases. How to handle, i see these solutions
1. disable the module in the background - that would break old edits
2. keep the gui as "not applicable" but let it process in the background seems to be no good idea as we cant even disable the module or reset to defaults
3. allow such images to use highlights and fix the colorspace thing

**Comment by TurboGit** [comment]
I would say also 3 but I'm a bit worried about another special case in the code. So I would be ok if the actual implementation is very localized and simple. I'm not sure this can hold if we fix the colorspace... You may prove me wrong :)

So if at the end the fix is too convoluted I'll vote for 1. Yes, breaking old edits is bad, but since we do this for good reasons... Of course a release note entry will make this clear to users.

**Comment by jenshannoschwalm** [comment]
A very easy go would be to allow opposed also for other images. It comes at very small cost, doesn't break old edits and might be of value in some cases too. ok?

**Comment by hcw70** [comment]
For me it would be ok in this case to disable highlight reconstruct for this image. 
(Would have done it manually if i had the chance to.)
But cant speak for the genral user....
