### ISSUE TITLE
Quick mask subtraction

### ISSUE THREAD

**Issue by Ni-Ti** [darktable-org/darktable#15159]
**Is your feature request related to a problem? Please describe.**

For certain uses, it can be useful to subtract one mask by a second.
At present, we need to proceed as follows: 
1. add a mask
2. add a second mask
3. go to the mask management module
4. change the merge function from "union mode" to "difference mode".
This involves quite a few steps for a function that is, in the end, fairly basic.

**Describe the solution you'd like**

For the specific case of subtraction, which is still fairly common (unlike the others, which are always available in the masks module), it might be useful to be able to do this directly using a keyboard shortcut when creating it. In addition to the ctrl+click shortcut, we could add the shift+click shortcut for automatic subtraction (and keep the ctrl+shift+click option for combining the two).

**Comment by lapineige** [comment]
That would massively simplify and speed up the worflow of substracting mask :+1:
No more time dealing with the menus, more focus on the main view :ok_hand:

**Comment by 5TuX** [comment]
This feature would be of great relevance, basically enabling to work with an eraser brush. Currently, the 2-step process described in the original post is still required, which forces the user to "paint inside the lines" when trying to paint over a subject. Allowing brush strokes to be added in subtraction mode directly would enable a much more intuitive experience: the user could start with a coarse mask and refine it by removing the excess parts with the subtraction mode.

Describe the solution you'd like:

In the properties section of the mask manager, add a drop down option to select the mode of newly added shapes (have at least sum and difference available, possibly other modes as well)
