### ISSUE TITLE
Remove union and intersection symbols of filters from the UI

### ISSUE THREAD

**Issue by Ni-Ti** [darktable-org/darktable#15152]
**Is your feature request related to a problem? Please describe.**

I talked about this a few years ago, but I notice that the ∪ and ∩ symbols are still present in the user interface for filter functions.
I don't know about you, but I don't think you need to have learned the mathematical symbols of set theory to be able to use the filter functions for our photos on darktable.
![image](https://github.com/darktable-org/darktable/assets/88101913/4cc7887a-8373-4851-b21f-6c36b2523d4c)
![image](https://github.com/darktable-org/darktable/assets/88101913/c0248c9b-b3c9-47be-b86e-6bb0fea3efc4)

All the users I spoke to had no knowledge of these symbols and therefore never used the function, which poses a real problem for the user experience.

**Describe the solution you'd like**

Replace these obscure symbols with more understandable ones.

**Alternatives**

1/ Use AND et OR directly
2/ Use schematic representations :
![image](https://github.com/darktable-org/darktable/assets/88101913/c5a9fedd-f53d-4971-be37-65ee38eff339) 
![image](https://github.com/darktable-org/darktable/assets/88101913/aaba1ad0-2883-4221-8851-9c6bcf5e961d)

**Comment by lapineige** [comment]
> All the users I spoke to had no knowledge of these symbols and therefore never used the function, which poses a real problem for the user experience.

Same feedback here, almost nobody know those symbols, and very few make the link between the symbol and what it could actually do (and simply ignore it). Also it's hard to distinguish it in the UI (as it's very thin and close to the grey circle) and between both modes.

In lack of a better solution, switching to AND / OR seems a lot easier to locate and a lot clearer about the expected behavior.

**Comment by Ni-Ti** [comment]
> Also it's hard to distinguish it in the UI (as it's very thin and close to the grey circle) and between both modes.

The symbol is greyed out when it cannot be used. After selecting at least two coloured labels, it becomes more visible.
Alternatively, the symbol could simply be hidden from the interface when not usable.

**Comment by pehar1** [comment]
> nobody know those symbols

Generalizations are rarely helpful...
Just hover the mouse over the symbol and you get a tooltip with the explanation you need.

**Comment by lapineige** [comment]
> Generalizations are rarely helpful...

I talked about the people I saw using the software.
But you can make an user test, you are very likely to get the same result.


> Just hover the mouse over the symbol and you get a tooltip with the explanation you need.

Yes, icons are made not to be understood until you think it's possible to get a tooltip and read it :p
These icons fails to deliver enough affordance.

**Comment by victoryforce** [comment]
> Just hover the mouse over the symbol and you get a tooltip with the explanation you need.

This is no excuse for __obscure__ symbols. They should not be in the interface. This is bad design.

**Comment by AlicVB** [comment]
fwiw, there's already some icons like that used in the mask manager... but iirc, some have raised concern about the fact that they are not easy to read either (because too small)
Maybe some can test them and see how it looks ?

**Comment by lapineige** [comment]
If it's the same 2 icons, couldn't them all be replaced then ? They are not working icons sadly.

**Comment by zisoft** [comment]
Proposal:

The AND operator can be replaced by `&` which should be easy to understand.

![Bildschirmfoto 2024-10-25 um 19 26 31](https://github.com/user-attachments/assets/2ebc117f-52a1-45a3-90f5-d97f7f9e6e26)


But for the OR operator there is no well known symbol, how about `||`

![Bildschirmfoto 2024-10-25 um 19 27 03](https://github.com/user-attachments/assets/4a56b389-2cc2-432c-9ef0-2d1840d09b58)

Setting AND / OR as the button text would require to enlarge the button which distracts the UI.

**Comment by victoryforce** [comment]
> For us computer scientist, sure... for end users I doubt that `&` would be clearer. Likewise for `||`.

I would say that the currently used symbols from set theory are absolutely worse and more cryptic/mysterious. They are understandable only to those who have studied advanced maths. Instead, the vast majority of people understand that "&" means AND. What should "||" mean will be immediately clear, maybe only to programmers, yes. But it's still much easier to remember than the current characters.

Therefore, I strongly support this proposal.

**Comment by pehar1** [comment]
> They are understandable only to those who have studied advanced maths.

Definitely not. In Germany, set theory and Boolean algebra were taught in the 7th grade at grammar school.

The symbols currently used describe precisely which operation is meant. In my opinion, they should not be replaced by "_&_" and "_||_". The ampersand (& sign) is a ligature, which is used as a substitute for the “_and_” in the commercial field. The "_||_" is used in (some) programming languages, sometimes also the "_|_". In my opinion, this only increases the confusion.

Why is it too much to ask to learn these two symbols (union, intersection) again, actually they should be known from school anyway. And there is a helpful tooltip.

**Comment by lapineige** [comment]
While I would agree for the "||", the & is a much more widely known (as in "exposed to") character that set theory symbols.

> actually they should be known from school anyway.

That your guess based on your experience, not an universal truth.

Actually identifying the (un)clarity of these symbols would require user testing, not divination or preconceived ideas.
That's the lacking thing in this whole debate.
