### ISSUE TITLE
Pipette makes modules behave unexpectedly

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15157]
### Describe the bug

When using pipette, not disabling pipette input and opening for example the crop module, the crop border and guides are not visible yet crop area handles like move or resize from the respective border/edge are shown but don't work. This is highly confusing if you don't understand whats going on.

If it's possible to temporarily disable/grey out modules that don't accept pipette interaction this would help a lot I guess.

See https://discuss.pixls.us/t/why-does-darktable-not-close-the-pipette-automatically-when-selecting-modules-interacting-with-the-canvas/39209 for more details.

### Steps to reproduce

1. Use pipette and leave pipette input open
2. open crop module.
3. border handles are visible but do nothing

### Expected behavior

darktable should maybe make modules that can't take input from pipette inaccessible while using the pipette

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+435~gde5ff09c76

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD 6700 XT, ROCM 5.6.1

**Comment by jenshannoschwalm** [comment]
@piratenpanda i am not sure if making modules "un-accessible" would be the best way, disabling the pipette would be another option or even better getting around that crop-module misbehaving. Did you do further tests what modules don't work with an active pipette?

**Comment by jenshannoschwalm** [comment]
Looked into this and i think i understand and there is a fix.
