### ISSUE TITLE
white balance applied twice error

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#15151]
### Describe the bug

This error happens when simply changing the `white balance` on a new reset image.

Also, other times you get error that some filter has been applied multiple times. Especially for filters that don't allow you to have multiple instances of (e.g. white balance only allows one instance) 

This error also happens when Selective Copy `white balance` onto another image. 

Darktable doesn't overwrite the white balance instance, and appends another copy. 

### Steps to reproduce

1. Reset image
2. Edit white balance
3. white balance applied twice error

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/58240560/12066ea8-177d-4bc2-807c-e08a980cdd0a)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

```
Processor	AMD Ryzen 9 6900HX with Radeon Graphics           3.30 GHz
Installed RAM	16.0 GB (15.3 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

### Are you using OpenCL GPU in darktable?

None

**Comment by pehar1** [comment]
You get this error message if you have `white balance` _and_ `color calibration` applied and `white balance` is _not_ set to camera reference point (D65, bulb icon). This is intended behaviour.

**Comment by naisanzaa** [comment]
> You get this error message because you have `white balance` _and_ `color calibration` applied and `white balance` is _not_ set to camera reference point (D65, bulb icon). This is intended behaviour.

I have reset the image. Does resetting the image do anything? 

I'm assuming resetting the image starts from a good known state for me to start editing.

Or are you saying after resetting the image, I need to do something else before I can just start editing to avoid these errors?

**Comment by naisanzaa** [comment]
Or is `color calibration` the best practice way for adjusting white balance? (after playing with it, it seems better than the white balance filter)

**Comment by pehar1** [comment]
Please read https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/color-calibration/ especially section CAT warnings.

**Comment by naisanzaa** [comment]
> Please read https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/color-calibration/ especially section CAT warnings.

It seems this is the successor of the white balance module. 

Thanks for the link
