### ISSUE TITLE
#15163 breaks windows compile

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#15178]
### Describe the bug

Can't compile darktable on windows since #15163 was merged.

### Steps to reproduce

1. Download current master on windows
2. Try and compile
3. Observe the error in src/gui/about.c saying that "tools/darktable_authors.h" couldn't be found.

### Expected behavior

darktable should compile without error

### Where did you install darktable from?

darktable.org

### darktable version

Current master

### What OS are you using?

Windows

### What is the version of your OS?

Win 10

### Describe your system?

Windows in a VM

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

N/A

**Comment by zisoft** [comment]
This is strange because CI and nightly doesn't complain

**Comment by zisoft** [comment]
Just tried on my windows environment and cannot reproduce. It compiles and runs fine.

Did you try a clean build?

**Comment by wpferguson** [comment]
I always do a clean build.  Been bitten too many times.

Here's the error output

```
[ 33%] Building C object bin/CMakeFiles/lib_darktable.dir/dtgtk/thumbnail_btn.c.obj
[ 33%] Building C object bin/CMakeFiles/lib_darktable.dir/dtgtk/thumbtable.c.obj
[ 33%] Building C object bin/CMakeFiles/lib_darktable.dir/dtgtk/togglebutton.c.obj
[ 33%] Building C object bin/CMakeFiles/lib_darktable.dir/gui/about.c.obj
C:/msys64/home/bill/src/darktable/src/gui/about.c: In function 'darktable_show_about_dialog':
C:/msys64/home/bill/src/darktable/src/gui/about.c:52:10: fatal error: tools/darktable_authors.h: No such file or directory
   52 | #include "tools/darktable_authors.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1762: bin/CMakeFiles/lib_darktable.dir/gui/about.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:2287: bin/CMakeFiles/lib_darktable.dir/all] Error 2
```

**Comment by zisoft** [comment]
so does that mean that `build/bin/tools/darktable_authors.h` is not generated in you environment?

**Comment by wpferguson** [comment]
Correct, there is no build/bin/tools directory or darktable_authors.h.

**Comment by kmilos** [comment]
I guess it could be the
```
COMMAND bash ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
```
portion of the custom command generating that file?

This works for CI, nightlies, and people building using MSYS2 terminal as it actually is a bash terminal, but generally one could and should be able to build using Windows batch and regular cmd shell/PowerShell as well on Windows...

**Comment by TurboGit** [comment]
@kmilos : Maybe, but it was working before, the change just did move the code to another location, the previous command was:

```
-add_custom_command(
-  DEPENDS ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS
-  OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
-  COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/tools/
-  COMMAND bash ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
-  COMMENT "Generating authors.h for about dialog."
-)
```

And still had a `bash` call. So there must be something else...

**Comment by wpferguson** [comment]
Could it be that in the new location it's trying to create the build/bin/tools directory before build/bin exists?

**Comment by wpferguson** [comment]
If I go into the build directory, after the build crashes, then restart the build, it creates the tools directory and the darktable_authors.h file and finishes building successfully

**Comment by wpferguson** [comment]
my build process

```
lensfun-update-data
git submodule update
mkdir build
cd build
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/darktable37 -DBINARY_PACKAGE_BUILD=ON ../.
cmake --build .
cmake --build . --target package


```

**Comment by wpferguson** [comment]
Works with Ninja

**Comment by zisoft** [comment]
CMake `make_directory` is [deprecated](https://cmake.org/cmake/help/latest/command/make_directory.html#make-directory), maybe `file(MAKE_DIRECTORY)` makes a difference?

**Comment by zisoft** [comment]
If the recursive creation of the directory fails, how about doing that in two steps:

```
add_custom_command(
  DEPENDS ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS
  OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
  COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}
  COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/tools/
  COMMAND bash ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
  COMMENT "Generating authors.h for about dialog."
)
```

Not nice though, `make_directory` should work recursively out of the box.

**Comment by wpferguson** [comment]
So the original problem was that build/bin/tools/darktable_authors.h didn't get created until src/libs got compiled.  You moved it to src/CMakeLists.txt so it would get created earlier, but it looks like it might be getting created too early, i.e. before build/bin gets created.  So why not move that snippet to src/gui/CMakeLists.txt?

**Comment by wpferguson** [comment]
Tried moving the snippet to src/gui/CMakeLists.txt, which didn't exist so I created it.  I've taken a couple of shots at it, but haven't figured out the magical cmake incantation to get it to work.

I backed off from testing for a second and thought about the problem a little more.  build/bin/tools/darktable_authors.h is now a required dependency for src/gui/about.c.  That needs to be captured and in the build system so that somewhere down the road when somebody makes a change things don't start breaking "for no reason".  Or, that we depend on some magic in the build system to figure out our dependencies that we didn't state.

**Comment by zisoft** [comment]
Fully agreed regarding the dependencies. Before my change, darktable_authors.h was a dependency of src/libs/darktable.c.

But that does not explain why a CMake command fails on one platform while working on all others.

**Comment by zisoft** [comment]
I was finally able to reproduce that on windows as well as on my Mac.

The reason for Ninja not complaining is that Ninja compiles with multiple threads in parallel and one of these threads builds the target `generate_authors_h` before it is needed by another thread.

@wpferguson: Can you please test with PR #15199 ?

**Comment by wpferguson** [comment]
@zisoft works for me.  Thanks
