### ISSUE TITLE
Crash when clicking feathering border of drawn mask (path)  - 100% reproducible - Win 10 - dt 4.4.2

### ISSUE THREAD

**Issue by europlatus** [darktable-org/darktable#15189]
### Describe the bug

Darktable crashes to desktop when trying to adjust the feathering border of a mask drawn with the path tool. 
The bug only seems to affect drawn masks using the path tool. The feathering border of drawn paths has nodes that can be adjusted. Clicking on a node does not crash the program but clicking anywhere else on the feathering border causes the crash.
The crash happens with openCL enabled and disabled. 
No backtrace created.

### Steps to reproduce

1. Open a raw image from the Lighttable
2. Open a module and create a drawn mask using the path tool
3. Click anywhere on the feathering border (not a node) to cause the program to crash.

### Expected behavior

The program should not crash when the feathering border is clicked. You should be able to add a node to this border.

### Logfile | Screenshot | Screencast

[darktable-log  common.txt](https://github.com/darktable-org/darktable/files/12518446/darktable-log.common.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Radeon 6700XT

**Comment by apostel338** [comment]
Same on Tumbleweed. But it's not enough to _click_, I need to drag while clicking to get it to crash.

[-d common.txt](https://github.com/darktable-org/darktable/files/12520661/-d.common.txt)
[darktable_bt_JHH3A2.txt](https://github.com/darktable-org/darktable/files/12520662/darktable_bt_JHH3A2.txt)
