### ISSUE TITLE
Simplify zoom ratio's using (ctrl shift + keys) in Darktable

### ISSUE THREAD

**Issue by Stuntflyer** [darktable-org/darktable#15188]
**Is your feature request related to a problem? Please describe.** Not really if one doesn't mind the default behavior.

I'm always frustrated when typical zoom levels with the combo keys goes from fit to these zoom percentages before it reaches100. These are 52 57 63 69 76 84 92 100. I think that this is too many zoom percentages which take too much time in general to get to 100%
**Describe the solution you'd like**

I think that at the zoom percentages should be able to be limited to 50 100 200 400, 800.

**Alternatives**

Change the default zoom in key to (ctrl +) This falls in line with the default zoom out (ctrl -)

**Additional context**

Perhaps an option in preferences to pick ones default zoom levels with the revised ctrl + key

Thank you

**Comment by MStraeten** [comment]
zoom factors depends on your display properties to allow a quite fine zooming. You can use fixed rates via context menu on preview frame...

**Comment by dterrahe** [comment]
The zoom dropdown (on the navigator widget top-left) has those percentages (and fit/fill). You could assign shortcuts directly to that. Use shortcut mapping mode to assign keys and then go into the shortcuts dialog (by clicking on the dropdown while still in mapping mode) to change the _effect_ to _previous_/_next_. Or you could assign a key+scroll wheel if you don't want to use two keys.
![image](https://github.com/darktable-org/darktable/assets/1549490/8a1cde60-70bc-4931-b536-da9ed0d3d485)

**Comment by Stuntflyer** [comment]
My thinking was to be able to use (ctrl + or -) in order to zoom in or out to 50, 100,200,400,800 levels. This is very similar to LR and PS and perhaps Gimp which I don't use but it might work that way..

**Comment by dterrahe** [comment]
> Can I do that with your suggestion above?

You can try?

**Comment by Stuntflyer** [comment]
I think that I would need to go to the area where the different ctrl+shift+zoom levels currently reside so that they can be changed. Not being a coder, I'm pretty sure it's not something that I can do.

**Comment by MStraeten** [comment]
no need to be a coder, just add two lines to your users ./config/darktable/shortcutsrc file:
```
plus;shift;ctrl=views/darkroom/zoom;next
minus;shift;ctrl=views/darkroom/zoom;previous
```
or replace the current behaviour via:
```
plus;ctrl=views/darkroom/zoom;next
minus;ctrl=views/darkroom/zoom;previous
```
or use the gui after reading: https://docs.darktable.org/usermanual/4.2/en/preferences-settings/shortcuts/

**Comment by dterrahe** [comment]
@Stuntflyer have you tried if the steps described above lead to a solution that works for you? If so, please confirm here and close this issue. If not, please provide extra information.

**Comment by Stuntflyer** [comment]
The solution I was looking for was to use the ctrl+ and ctrl- keys to zoom to 33 50 100 200 400 800. The above recommendations do not do that as far as I can tell. Unless there is an option or an easy way to enable those zoom levels with a similar key combo, then it would be best to close the issue. 

Thanks!

**Comment by dterrahe** [comment]
Sometimes you add the 33%, sometimes you list only 50, 100, 200, 400, 800 so it is a bit hard to understand what you _really_ want/need. Setting up shortcuts to the zoom widget allows you to step through the values it contains, so only 33 would be missing. If that's not _exactly_ what you need then that is unfortunate.
![image](https://github.com/darktable-org/darktable/assets/1549490/cda248d9-6647-4a9c-baab-192368da3179)

To satisfy requests that are very specific to the individual user, it would be necessary to build a configuration framework that allows tailoring each aspect of the user interface. While this is possible when enough work is put in, it also means that a lot of complexity is added and that very few people will actually be able to fully use or understand the available functionality. This usually leads to complaints of "overengineering" and of not paying enough attention to the more basic functions of the program, where there are still more then enough improvements that can or should be made.

**Comment by Stuntflyer** [comment]
Yeas, I understand what you are saying and am not trying to mess it up for anyone else. After all I am only one of many.

My reasoning came from other software like ART, RT and PS. They all use the same zoom levels that I mentioned above from 50 onward. 50 100 200 400 800 1600, using a key stroke. So, my thinking was why does DT have to be the outlier with levels like 52 57 63 69 76 84 92, as an example on my display.

**Comment by dterrahe** [comment]
We have the same levels (in the dropdown, that you can define shortcuts/keystrokes for as repeatedly pointed out above) and we _also_ have more finegrained steps using the scroll wheel (that other people are used to/like).

**Comment by Stuntflyer** [comment]
Yes, but can the same key stroke like ctrl+ or ctrl- be used to change the zoom levels?

**Comment by dterrahe** [comment]
Obviously. You can choose any keys you like. Which you would have found out if you'd tried. Good luck!

**Comment by Stuntflyer** [comment]
Yes, that works. Thank you!

**Comment by Stuntflyer** [comment]
Please disregard my last post. I'm sill not getting it. I can't figure out how to use ctrl+ and ctrl- to go between these specific zoom levels. 33 50 100 200 400 800 1600. 

Sorry!

**Comment by MStraeten** [comment]
then you obviously didn’t even try the suggested solution ;)
