### ISSUE TITLE
Lens, "Canon EF 24-70mm f/2.8L II USM" is NOT identified correctly

### ISSUE THREAD

**Issue by chandra-100** [darktable-org/darktable#15190]
### Describe the bug

Lens, "Canon EF 24-70mm f/2.8L II USM" is NOT identified correctly; 
It is identified as " Canon EF 24-70mm f/2.8L II USM *OR* Sigma 24-70mm f/2.8 DG OS HSM | A"
In the 'image information' in 'lighttable' it shows above info; in the 'darkroom' under 'lens correction' module the lens need to be manually chosen to apply the lens correction. 

### Steps to reproduce

import attached tiff file which is short with Canon EF 24-70mm f/2.8L II USM on a Canon 5d iii.
import to DT and see 'image information' ; please see 'lens correction' tab under' in darkroom.

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux x86_64 

### Describe your system?

OS: Arch Linux x86_64 
Host: Latitude E6420Kernel: 6.1.50-1-lts 
DE: GNOME 44.4 
WM: Mutter 
CPU: Intel i7-2620M (4) @ 3.400GHz
GPU: NVIDIA NVS 4200M
GPU: Intel 2nd Generation Core Process 
Memory: 4590MiB / 7823MiB 

Note : Darktable is installed from the Arch repository
https://archlinux.org/packages/extra/x86_64/darktable/
download sample file shot with above lens: https://drive.google.com/file/d/1N9wLDRn5SA3C9qGGCC2W9I9E2QFRFG16/view?usp=sharing

### Are you using OpenCL GPU in darktable?

No

**Comment by MStraeten** [comment]
not reproducible on macos:
![image](https://github.com/darktable-org/darktable/assets/39386816/843634bc-5138-4d11-a97f-c0207b99b619)

maybe check:
https://github.com/darktable-org/darktable/wiki/User's-portal#my-lens-is-wrongly-identified

**Comment by chandra-100** [comment]
Hi Martin, Thanks a lot ; i followed the link and it did work !
The issue was actually in arch linux only , i tested fedora, UBU and none has the problem. 
i use arch ; so this was great help and appreciate your time.
cheers!
