### ISSUE TITLE
Pictures in portrait orientation have a black thumbnail in the darkroom

### ISSUE THREAD

**Issue by EC1000** [darktable-org/darktable#15198]
### Describe the bug

In the darkroom, pictures in portrait orientation are displayed with black thumbnails (after a parameter has been changed and after going to another picture). 

See examples posted by qmpel on https://discuss.pixls.us/t/pictures-with-orientation-module-have-a-black-thumbnail/37223/1

### Steps to reproduce

1. Use a collection with several pictures and with portrait orientation
2. Open such a picture in the darkroom
3. Change a parameter
4. Go to another picture
5. The thumbnail of the first picture becomes black

I reproduce with somes of my files (20 MPixels .cr3) but not all (not with 12 MPixels .cr2; it does not seem to be cr3 related though, since the example on pixls.us is with .arw files). 

The active picture (the one with the little arrow on top) is not affected (if it was black and I come back to this picture, it is ok again).  

### Expected behavior

Thumbnails should be correctly displayed

### Logfile | Screenshot | Screencast

[log1.txt](https://github.com/darktable-org/darktable/files/12528696/log1.txt) contains the result of `darktable -d common` for steps 1-5 above.  

### Where did you install darktable from?

OBS

### darktable version

4.4.1

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.1 Cinnamon

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1660 6G with nvidia-driver-525

**Comment by gi-man** [comment]
This seems like a similar issue to: https://github.com/darktable-org/darktable/issues/15185

In your log I see:

```
    16,6680 [pixelpipe_process_CL]       [thumbnail]    demosaic               (   0/   0) 5496x3647 scale=1,0000 --> (   0/   0)  110x  73 scale=0,0200 IOP_CS_RAW -> IOP_CS_RGB
    16,6962 [clip_and_zoom_roi_cl]       [thumbnail]    demosaic               (   0/   0) 5496x3647 scale=1,0000 --> (   0/   0)  110x  73 scale=0,0200 
    16,6965 [interpolation_resample_cl]                                        (   0/   0) 5496x3647 scale=1,0000 --> (   0/   0)  110x  73 scale=0,0200 Error: DT_OPENCL_PROCESS_CL
```

Try increasing the size of your thumbnails. The next option is to try using the darktable master instead of 4.4.1.

PS. I think you should turn off the memory and transfer in the OpenCL settings. It should yield faster performance for your GPU. This is unrelated to your issue, but something I noticed in your log file. :-)

**Comment by jenshannoschwalm** [comment]
The above mentioned GPU->CPU fallback is intended, not yet sure about remaining issues with the cpu code. Could you provide a xmp?

**Comment by EC1000** [comment]
Here is one [pic1.cr3.txt](https://github.com/darktable-org/darktable/files/12550136/pic1.cr3.txt) (.xmp was rename to .txt to be upload here)

**Comment by jenshannoschwalm** [comment]
Can't reproduce on Master any more. I suggest to update at least to 4.2.2 or even better to master and check again.

**Comment by EC1000** [comment]
I already upgraded to 4.4.2 but the issue is still there. I will try master and report here as soon as I can.

**Comment by EC1000** [comment]
> PS. I think you should turn off the memory and transfer in the OpenCL settings. It should yield faster performance for your GPU. This is unrelated to your issue, but something I noticed in your log file. :-)

Thanks! I find it is not easy to know which option is best depending on your configuration for these kind of technical options, so thank you for the advice. 

Side note: I add the option "memory size and transfer", but no "bullet" to indicate that the parameter was not the default one (which is "nothing"). I don't know if is a (small) missing feature or intended.

**Comment by EC1000** [comment]
Same issue with master, but that lead me to find a better clue: deleting `darktablerc` file solves the black thumbnails issue.
Any idea how to determine which option/line might be the culprit? If possible, I would rather like to avoid having to redo each modified parameter... :smiley:

**Comment by jenshannoschwalm** [comment]
I have no idea - but i would be interested in getting more feedback if you can find "something" to trigger! My current guess is some scaling/interpolating issue.

**Comment by EC1000** [comment]
> changing the demosaic method

Some demosaic methods have the issue while some don't: 
- KO: PPG, VNG4, RCP 
- OK: AMaZE, LMMSE

I don't understand the link with darktablerc...!

**Comment by EC1000** [comment]
> Try increasing the size of your thumbnails

You were right @gi-man, if I increase the filmstrip size and so the thumbnails size, the issue is not present.

**Comment by jenshannoschwalm** [comment]
Your observation with the demosaicers hint to opencl scaling issue. Does the issue persist with bicubic or bilinear scaling too?

**Comment by gi-man** [comment]
Just to be clear, you are still using master for these test? 

Can you post the old and new darktablerc?

**Comment by EC1000** [comment]
I just compile master with #15219 and it solves the issue :+1:  


> Your observation with the demosaicers hint to opencl scaling issue. 

Just so I understand: I tried (even before reporting the issue) to change "activate OpenCL support" to FALSE; as the problem persisted, I thought it wasn't related to opencl, but it seems I misunderstood. I you can explain, I would be grateful.

**Comment by jenshannoschwalm** [comment]
The issue was basically **not** related to opencl, it was a problem with downscaling - that happens right in the demosaicer code. In some cases the graphics card can't handle such scaling in an efficient way and falls back to cpu.

The main problem has been fixed in these lines. 

```
  const size_t scratchreq = dt_round_size(maxtapsapixel * sizeof(float) + 4 * sizeof(float), SSE_ALIGNMENT);
  // NB: because sse versions compute four taps a time
  const size_t metareq = dt_round_size(pmeta ? 4 * sizeof(int) * out : 0, SSE_ALIGNMENT);
```

With some inerpolation methods (lanc3) we had wrong (not correctly aligned) offsets plus some missing data :-) 
A pretty old bug btw

**Comment by EC1000** [comment]
Thanks for the clarification

**Comment by jenshannoschwalm** [comment]
Thanks for reporting the issue btw!
