### ISSUE TITLE
Without OpenCL, filmic's hl-reconstruction produces artifacts.

### ISSUE THREAD

**Issue by apostel338** [darktable-org/darktable#15203]
### Describe the bug

Without OpenCL, filmic's hl-reconstruction seems to produce artifacts.

### Steps to reproduce

Find a RAW with (some seriously) blown out highlights.
Enable HL reconstruct in filmic, play with some values. 
Moste visible when lower the treshold a bit, raise iterations of hq-rec., and lower the bloom<->reconstruct slider.

### Logfile | Screenshot | Screencast

OpenCL on:

![Screenshot_20230906_235027](https://github.com/darktable-org/darktable/assets/96216629/d11237b8-f137-4de9-a384-73660f3a8c7d)

OpenCL off:

![Screenshot_20230906_235116](https://github.com/darktable-org/darktable/assets/96216629/4dd956e0-b8f3-430e-8829-bb474294925f)

### Where did you install darktable from?

OBS

### darktable version

4.5.0~git328.1aca07c6-10447.5

### What OS are you using?

Linux

### What is the version of your OS?

Tumbleweed

### Describe your system?

Operating System: openSUSE Tumbleweed 20230902
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.109.0
Qt Version: 5.15.10
Kernel Version: 6.4.12-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × 12th Gen Intel® Core™ i5-12500T
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 770

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

RAW + XMP:

[000.tar.gz](https://github.com/darktable-org/darktable/files/12542895/000.tar.gz)

**Comment by jenshannoschwalm** [comment]
@ralfbrown i bisected and it seems to be https://github.com/darktable-org/darktable/commit/b0a5f320fae9eae8ce04f370cd3bd7e0896382f9

**Comment by jenshannoschwalm** [comment]
got it and fix following

**Comment by ralfbrown** [comment]
Thanks!  Was going to look at it tomorrow.
