### ISSUE TITLE
Export from a raw file to a TIFF is missing Title and Publisher

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#15204]
### Describe the bug

Export from a DNG or ARW file to TIFF doesn't copy the title and the publisher, while description, creator and rights are ok.
I don't know if notes is copied as I don't use it.

### Steps to reproduce

Export in Lighttable.

### Expected behavior

title, description, creator, publisher, rights, notes should be copied to the TIFF

### Commit

Export

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+517~g529af85930

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro, Processor	AMD Ryzen 7 5800X 8-Core Processor, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)

### Describe your system?

Normal PC

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600, latest driver

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Pleas ask if you need more.

**Comment by kmilos** [comment]
AFAIK, there is no equivalent to dc:title and dc:publisher in TIFF, i.e. Exif., like there is for e.g. dc:creator, dc:rights, and dc:description.

https://developer.adobe.com/xmp/docs/XMPNamespaces/dc/
https://developer.adobe.com/xmp/docs/XMPNamespaces/tiff/
https://developer.adobe.com/xmp/docs/XMPNamespaces/exif/

Are these still retained in the XMP payload of the exported TIFF? If so, then the behaviour is as expected.

**Comment by KIRSJ** [comment]
Ok, thanks.

Den tors. 7. sep. 2023 kl. 14.15 skrev Miloš Komarčević <
***@***.***>:

**Comment by KIRSJ** [comment]
It seems to be closed.

Den man. 11. sep. 2023 kl. 21.47 skrev Victor Forsiuk <
***@***.***>:
