### ISSUE TITLE
Timeline doesn't show image count

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#15211]
### Describe the bug

The timeline at the bottom of Lighttable doesn't seem to populate anymore. 

### Steps to reproduce

1. Enable bottom timeline
2. Zoom out to show all years

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/58240560/33c0acd8-0fd7-4c62-93ab-f06f0b5935c7)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

```
Processor	AMD Ryzen 9 6900HX with Radeon Graphics           3.30 GHz
Installed RAM	16.0 GB (15.3 GB usable)
```

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
Can't reproduce in linux or windows

**Comment by pehar1** [comment]
Same here with 4.5.0+445~g0fcf57c4fe (Ubuntu 22.04). Not able to reproduce.

**Comment by naisanzaa** [comment]
With more than 56K images?

**Comment by ralfbrown** [comment]
My timeline works fine with 352k images over 25 years.

Sanity check, to make sure the database hasn't somehow just lost the date information - open the collections module, and switch the "folder" pulldown to "capture date".  Does it show the expected number of images per year?

One thing I noticed in the screenshot is that the timeline extends into the future (2024).  It shouldn't matter, but maybe that confused dt?

**Comment by naisanzaa** [comment]
I had to delete the database and re-import everything.

i'm guessing through the multiple updates the timeline got lost over time.
