### ISSUE TITLE
Option to hide the overlay guides in the retouch module.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#15216]
### Describe the bug

Hello,

I really don't know if I should put this as an issue or if it was intentionally planned. I know you have done a wonderful job in the retouching module, that even if you have cropped the image, when this module is activated, the area that was left out of the crop comes out as well. The thing is that when I use the cropping module, either for an object, or especially faces, when I deploy the module, it automatically activates the guide lines and there is no way to deactivate them, neither by the module, nor by the icon in the bottom bar. This behavior of the guidelines being active all the time tends to distract from the retouching work being done.
The guide lines that come out are those of the last applied settings, golden ratio, grid, rules of thirds, etc but they are always activated, there is no way to deactivate them.

### Steps to reproduce

1. go to darkroom
2. active the retouch module
3. see the overlay guides over the image

### Expected behavior

If there are going to be guides in the retouch module, must be an option of hide them.

### Logfile | Screenshot | Screencast

![Screenshot from 2023-09-08 22-40-33](https://github.com/darktable-org/darktable/assets/67672868/38c16b90-c40b-4ebd-8640-7d363e8d1226)

### Commit

--------------

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0~git542.dad26a52-10552.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

530.41.03

**Comment by wpferguson** [comment]
Can't reproduce on Ubuntu 22.04 with same version

**Comment by MStraeten** [comment]
if you enable global overlays, then you need to disable them also globally

**Comment by Nilvus** [comment]
As @MStraeten: it's by design and you could easily enable or disable overlay guides by clicking on main overlay button on bottom bar in darkroom (icon on the right). So maybe you could close that issue?

**Comment by difrkaguilar** [comment]
The issue is on my side. I opened another instance as root and don´t saw this error. Sorry.
