### ISSUE TITLE
Corrupt library.db looks like a failure to open data.db

### ISSUE THREAD

**Issue by ajeddeloh** [darktable-org/darktable#15224]
### Describe the bug

My laptop ran out of battery while using Darktable, corrupting `library.db`. However the error message I got was:
```
[init] database `/home/andrew/.config/darktable/data.db' couldn't be opened. aborting
```
Which makes it seem like `data.db` is the problem. 

### Steps to reproduce

1. Corrupt `library.db`
2. See error message about `data.db`

### Expected behavior

Complain about a corrupt library.db

### Where did you install darktable from?

distro packaging

### darktable version

4.2.2

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

It looks like the issue is https://github.com/darktable-org/darktable/blob/master/src/common/database.c#L3176 succeeds with a corrupt database but then causes https://github.com/darktable-org/darktable/blob/master/src/common/database.c#L3205 to always fail with rc=11 (SQLITE_CORRUPT).

**Comment by MStraeten** [comment]
that’s just the last logging message, not an error message.
So if your library.db is broken, use the latest snapshot of it…

**Comment by Nilvus** [comment]
Not an issue but normal behavior after such closing. I so close. Félix free to be more precise if issue is not clear.

**Comment by ajeddeloh** [comment]
The issue is that what it logs doesn't say anything about `library.db` being corrupt and instead says `data.db` is corrupt, thus a user trying to debug what's going on is lead astray. It took hooking up a debugger to gdb to realize this for me. I think it should either handle the rc=SQLITE_CORRUPT differently (logging that the previous load was the cause of the failure) or explicitly check `library.db` for corruption after loading.
