### ISSUE TITLE
The image turns yellow when the CCT color picker in Color calibration is used 

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#15226]
### Describe the bug

The color picker in the Color calibration module has changed behavior within the latest builds.
It should present a suggested white balance based on the entire image - but the image is turned yellow.

### Steps to reproduce

1. Color calibration, CAT
2. Press the colorpicker

### Expected behavior

A usable suggestion for a white balanced image

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+548~g59c3eaa6d1

### What OS are you using?

Windows

### What is the version of your OS?

Win 10

### Describe your system?

Potent PC

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600, latest driver

**Comment by MStraeten** [comment]
Did you check, spot color matching isn’t active?
See https://docs.darktable.org/usermanual/4.2/en/module-reference/processing-modules/color-calibration/#spot-color-mapping

**Comment by KIRSJ** [comment]
Oh dear - that was it. Thank you Martin.

Den søn. 10. sep. 2023 kl. 12.52 skrev Martin Straeten <
***@***.***>:
