### ISSUE TITLE
Big white zone on exported file

### ISSUE THREAD

**Issue by nauotit** [darktable-org/darktable#15239]
### Describe the bug

Hi,
I from time to time get problem on export. It's quit strange because it doesn't happen always, just on some pictures and not at every export size. I for instance have a picture which is good exported at reduced size, but get big white zones on full size export.
![2R3A0033](https://github.com/darktable-org/darktable/assets/13032173/2572af58-e681-4049-b935-1faed3040c9c)
![2R3A0033_01](https://github.com/darktable-org/darktable/assets/13032173/db0d4244-1d65-4323-9c5a-852bebacf463)

### Steps to reproduce

I can't give you here the raw and XMP files because the raw is too heavy for github...
But if there is another way I have no problem to share them.
Once you have these file, just export the image full size in jpeg to reproduce the bug.

### Expected behavior

Export the proper image

### Logfile | Screenshot | Screencast

I don't get any message, just a bug on the resulting picture after export.

### Commit

No idea

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

fedora 37

### Describe your system?

I7 
8Gb RAM
NV137 / Mesa Intel® HD Graphics 630 (KBL GT2)

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

NV137 / Mesa Intel® HD Graphics 630 (KBL GT2)

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Are the steps above reproducible with a fresh edit (i.e. after discarding history)? -> yes
No idea about the others questions...

**Comment by MStraeten** [comment]
Filmic highlight reconstruction tends to overshoot in case of too high highlights. Might happen if too much brilliance was added in the highlights via colorbalancergb …

**Comment by pehar1** [comment]
See https://github.com/darktable-org/darktable/issues/12442 for further explanations.

**Comment by Nilvus** [comment]
Thanks @pehar1 to remind here that this is a duplicate. @nauotit: I so close your issue, you have all explanations on #12442, even by the developer of filmic author (clear explanations even if how it's written is not pleasant...). If needed, you can continue discussion on #12442.

**Comment by nauotit** [comment]
Thanks a lot for your fast answer. 

Le 14 septembre 2023 08:38:35 GMT+02:00, pehar1 ***@***.***> a écrit :
