### ISSUE TITLE
color label filter UI not consistent and does not cover all cases

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#15255]
### Describe the bug

1. If one or more color label filters are active, a double click on the filter will disable all. I would expect that double clicking if no labels are active would activate all - but it does nothing. Instead, there is a 'grey' color label that is used to activate/deactivate all.

2. There is no button that means `un-labeled`. Filtering for `un-labeled` images is implied by `Ctrl-clicking` the grey button which negates all other color labels. While this filters out all color labels and will leave only `un-labeled` images, I cannot express filters like this: show images that are unlabeled or blue. For this a dedicated button `un-labeled` is necessary.

Would it not be a better use of the grey button to mean `any-label` images? If the button is active, all images with at least one label will be displayed and if it is crossed out, only images without color labels will be displayed (`un-labeled`).

The example of no-label + blue could then be achieved by crossing out grey, enabling blue and connecting them with `OR`.

### Steps to reproduce

see above

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+592~g4fa7a254af

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Are you using OpenCL GPU in darktable?

None

**Comment by dterrahe** [comment]
> 1. If one or more color label filters are active, a double click on the filter will disable all. I would expect...

Why? double-click in many places in dt means "reset to default". This is not consistently applied; in some places it has a different meaning and maybe in this case that could be useful as well, but I'm not sure users (_I_) would _expect_ that.

**Comment by Solarer** [comment]
Sorry for the late reply.

Activating ALL or NO filters habe the same result: all images are displayed.
So you could consider both as default 😉.
