### ISSUE TITLE
Can't create an HDR image on Linux

### ISSUE THREAD

**Issue by SkiTcH-VI** [darktable-org/darktable#15264]
### Describe the bug

Can't create an HDR image on the latest Fedora instance.
On trying to generate an HDR image it shows a success message that "hdr.dng" was created.
![image](https://github.com/darktable-org/darktable/assets/118852060/9269ce75-7a1e-4933-b937-b6f03a54814b)
But when opening the film roll where it should be it shows a message that "-hdr.dng" doesn't exist.
I'm not familiar very well with this software and I'm using this feature for the first time, but it seems it's just an issue of naming file wrong, for some reason it adds "-" before the file name. 

### Steps to reproduce

1. Add to library set of images for HDR 
2. Go to 'selected image[s]'
3. Click 'create HDR'
4. Check if the resulting image exists in the program 

### Expected behavior

hdr.dng Image should exists

### Logfile | Screenshot | Screencast

     0.0001 application_directory: /app/bin
     0.0002 darktable.datadir: /app/share/darktable
     0.0003 darktable.plugindir: /app/lib64/darktable
     0.0003 darktable.localedir: /app/share/locale
     0.0004 darktable.configdir: /home/user/.var/app/org.darktable.Darktable/config/darktable
     0.0005 darktable.cachedir: /home/user/.var/app/org.darktable.Darktable/cache/darktable
     0.0005 darktable.sharedir: /app/share
     0.0005 darktable.tmpdir: /tmp
     0.0005 new_xdg_data_dirs: (null)
Gtk-Message: 13:00:34.340: Failed to load module "pk-gtk-module"
Gtk-Message: 13:00:34.342: Failed to load module "pk-gtk-module"
     0.0916 [dt_worker_threads] using 4 worker threads
     0.0933 [dt_get_sysresource_level] switched to 1 as `default'
     0.0933   total mem:       15340MB
     0.0933   mipmap cache:    1917MB
     0.0933   available mem:   7670MB
     0.0933   singlebuff:      119MB
     0.0933   OpenCL tune mem: OFF
     0.0933   OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
     0.0953 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL'
     0.0954 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL.so'
[opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
[opencl_init] could not get platforms: Unknown OpenCL error
[opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.
     0.3515 [dt_worker_threads] using 4 worker threads
     6.0606 [avif_open] failed to parse `/home/user/Pictures/TestHDR/P1020330.RW2': BMFF parsing failed
     6.0608 [rawspeed_open] extensions list to ignore: `cr3'
RawSpeed:Unable to find camera in database: 'Panasonic' 'DMC-GM1S' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
     6.0930 [rawspeed] (P1020330.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'Panasonic' 'DMC-GM1S', mode '' not supported, and not allowed to guess. Sorry.
     6.0931 [libraw_open] extensions whitelist: `cr3'
     6.0945 [dt_dev_read_history_ext] temporary history deleted
     6.0945 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     6.0947 [dt_iop_reload_defaults] defaults reloaded for basecurve
     6.0947 [dt_iop_reload_defaults] defaults reloaded for colormapping
     6.0947 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     6.0968 [dt_iop_reload_defaults] defaults reloaded for colorin
     6.0968 [dt_iop_reload_defaults] defaults reloaded for crop
     6.0968 [dt_iop_reload_defaults] defaults reloaded for exposure
     6.0969 [dt_iop_reload_defaults] defaults reloaded for retouch
     6.0969 [dt_iop_reload_defaults] defaults reloaded for clipping
     6.0969 [dt_iop_reload_defaults] defaults reloaded for flip
     6.0969 [dt_iop_reload_defaults] defaults reloaded for ashift
     6.0969 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     6.0979 [dt_iop_reload_defaults] defaults reloaded for lens
     6.0980 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     6.0980 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     6.0981 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     6.0981 [dt_iop_reload_defaults] defaults reloaded for demosaic
     6.0981 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     6.0981 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     6.0982 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     6.0982 [dt_iop_reload_defaults] defaults reloaded for highlights
     6.0982 [temperature] failed to read camera white balance information from `P1020330.RW2'!
     6.0985 [dt_iop_reload_defaults] defaults reloaded for temperature
     6.0986 [dt_iop_reload_defaults] defaults reloaded for invert
     6.0986 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     6.1021 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     6.1021 [dt_dev_read_history_ext] temporary history merged with image history
     6.1022 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.1022 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.1023 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     6.1023 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     6.1023 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     6.1024 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.1024 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.1024 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.1025 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.1025 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.1025 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.1064 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
     6.1278 [avif_open] failed to parse `/home/user/Pictures/TestHDR/P1020331.RW2': BMFF parsing failed
     6.1279 [rawspeed_open] extensions list to ignore: `cr3'
RawSpeed:Unable to find camera in database: 'Panasonic' 'DMC-GM1S' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
     6.1492 [rawspeed] (P1020331.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'Panasonic' 'DMC-GM1S', mode '' not supported, and not allowed to guess. Sorry.
     6.1493 [libraw_open] extensions whitelist: `cr3'
     6.1499 [dt_dev_read_history_ext] temporary history deleted
     6.1499 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     6.1500 [dt_iop_reload_defaults] defaults reloaded for basecurve
     6.1500 [dt_iop_reload_defaults] defaults reloaded for colormapping
     6.1500 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     6.1507 [dt_iop_reload_defaults] defaults reloaded for colorin
     6.1507 [dt_iop_reload_defaults] defaults reloaded for crop
     6.1507 [dt_iop_reload_defaults] defaults reloaded for exposure
     6.1507 [dt_iop_reload_defaults] defaults reloaded for retouch
     6.1507 [dt_iop_reload_defaults] defaults reloaded for clipping
     6.1507 [dt_iop_reload_defaults] defaults reloaded for flip
     6.1508 [dt_iop_reload_defaults] defaults reloaded for ashift
     6.1508 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     6.1514 [dt_iop_reload_defaults] defaults reloaded for lens
     6.1514 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     6.1514 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     6.1515 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     6.1516 [dt_iop_reload_defaults] defaults reloaded for demosaic
     6.1516 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     6.1516 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     6.1516 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     6.1516 [dt_iop_reload_defaults] defaults reloaded for highlights
     6.1516 [temperature] failed to read camera white balance information from `P1020331.RW2'!
     6.1520 [dt_iop_reload_defaults] defaults reloaded for temperature
     6.1520 [dt_iop_reload_defaults] defaults reloaded for invert
     6.1520 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     6.1544 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     6.1544 [dt_dev_read_history_ext] temporary history merged with image history
     6.1545 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.1545 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.1545 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     6.1546 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     6.1548 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     6.1548 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.1548 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.1549 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.1549 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.1549 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.1549 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.1574 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
     6.1776 [avif_open] failed to parse `/home/user/Pictures/TestHDR/P1020332.RW2': BMFF parsing failed
     6.1778 [rawspeed_open] extensions list to ignore: `cr3'
RawSpeed:Unable to find camera in database: 'Panasonic' 'DMC-GM1S' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
     6.2031 [rawspeed] (P1020332.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'Panasonic' 'DMC-GM1S', mode '' not supported, and not allowed to guess. Sorry.
     6.2031 [libraw_open] extensions whitelist: `cr3'
     6.2038 [dt_dev_read_history_ext] temporary history deleted
     6.2038 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     6.2039 [dt_iop_reload_defaults] defaults reloaded for basecurve
     6.2039 [dt_iop_reload_defaults] defaults reloaded for colormapping
     6.2039 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     6.2046 [dt_iop_reload_defaults] defaults reloaded for colorin
     6.2046 [dt_iop_reload_defaults] defaults reloaded for crop
     6.2046 [dt_iop_reload_defaults] defaults reloaded for exposure
     6.2046 [dt_iop_reload_defaults] defaults reloaded for retouch
     6.2046 [dt_iop_reload_defaults] defaults reloaded for clipping
     6.2046 [dt_iop_reload_defaults] defaults reloaded for flip
     6.2046 [dt_iop_reload_defaults] defaults reloaded for ashift
     6.2046 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     6.2053 [dt_iop_reload_defaults] defaults reloaded for lens
     6.2053 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     6.2053 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     6.2054 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     6.2055 [dt_iop_reload_defaults] defaults reloaded for demosaic
     6.2055 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     6.2055 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     6.2055 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     6.2055 [dt_iop_reload_defaults] defaults reloaded for highlights
     6.2055 [temperature] failed to read camera white balance information from `P1020332.RW2'!
     6.2058 [dt_iop_reload_defaults] defaults reloaded for temperature
     6.2058 [dt_iop_reload_defaults] defaults reloaded for invert
     6.2058 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     6.2079 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     6.2079 [dt_dev_read_history_ext] temporary history merged with image history
     6.2080 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.2080 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.2080 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     6.2080 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     6.2080 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     6.2081 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.2081 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.2081 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.2081 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.2082 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.2082 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.2104 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
     6.2319 [avif_open] failed to parse `/home/user/Pictures/TestHDR/P1020333.RW2': BMFF parsing failed
     6.2321 [rawspeed_open] extensions list to ignore: `cr3'
RawSpeed:Unable to find camera in database: 'Panasonic' 'DMC-GM1S' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
     6.2566 [rawspeed] (P1020333.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'Panasonic' 'DMC-GM1S', mode '' not supported, and not allowed to guess. Sorry.
     6.2566 [libraw_open] extensions whitelist: `cr3'
     6.2571 [dt_dev_read_history_ext] temporary history deleted
     6.2571 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     6.2571 [dt_iop_reload_defaults] defaults reloaded for basecurve
     6.2572 [dt_iop_reload_defaults] defaults reloaded for colormapping
     6.2572 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     6.2577 [dt_iop_reload_defaults] defaults reloaded for colorin
     6.2577 [dt_iop_reload_defaults] defaults reloaded for crop
     6.2577 [dt_iop_reload_defaults] defaults reloaded for exposure
     6.2577 [dt_iop_reload_defaults] defaults reloaded for retouch
     6.2577 [dt_iop_reload_defaults] defaults reloaded for clipping
     6.2578 [dt_iop_reload_defaults] defaults reloaded for flip
     6.2578 [dt_iop_reload_defaults] defaults reloaded for ashift
     6.2578 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     6.2583 [dt_iop_reload_defaults] defaults reloaded for lens
     6.2584 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     6.2584 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     6.2585 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     6.2585 [dt_iop_reload_defaults] defaults reloaded for demosaic
     6.2585 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     6.2585 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     6.2585 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     6.2585 [dt_iop_reload_defaults] defaults reloaded for highlights
     6.2585 [temperature] failed to read camera white balance information from `P1020333.RW2'!
     6.2587 [dt_iop_reload_defaults] defaults reloaded for temperature
     6.2587 [dt_iop_reload_defaults] defaults reloaded for invert
     6.2588 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     6.2607 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     6.2608 [dt_dev_read_history_ext] temporary history merged with image history
     6.2608 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.2608 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.2609 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     6.2609 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     6.2609 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     6.2609 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.2609 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.2610 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.2610 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.2610 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.2610 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.2632 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
     6.2809 [avif_open] failed to parse `/home/user/Pictures/TestHDR/P1020334.RW2': BMFF parsing failed
     6.2810 [rawspeed_open] extensions list to ignore: `cr3'
RawSpeed:Unable to find camera in database: 'Panasonic' 'DMC-GM1S' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
     6.2987 [rawspeed] (P1020334.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'Panasonic' 'DMC-GM1S', mode '' not supported, and not allowed to guess. Sorry.
     6.2987 [libraw_open] extensions whitelist: `cr3'
     6.2992 [dt_dev_read_history_ext] temporary history deleted
     6.2992 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     6.2993 [dt_iop_reload_defaults] defaults reloaded for basecurve
     6.2993 [dt_iop_reload_defaults] defaults reloaded for colormapping
     6.2993 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     6.2998 [dt_iop_reload_defaults] defaults reloaded for colorin
     6.2998 [dt_iop_reload_defaults] defaults reloaded for crop
     6.2998 [dt_iop_reload_defaults] defaults reloaded for exposure
     6.2998 [dt_iop_reload_defaults] defaults reloaded for retouch
     6.2998 [dt_iop_reload_defaults] defaults reloaded for clipping
     6.2998 [dt_iop_reload_defaults] defaults reloaded for flip
     6.2999 [dt_iop_reload_defaults] defaults reloaded for ashift
     6.2999 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     6.3004 [dt_iop_reload_defaults] defaults reloaded for lens
     6.3004 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     6.3004 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     6.3005 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     6.3005 [dt_iop_reload_defaults] defaults reloaded for demosaic
     6.3005 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     6.3005 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     6.3005 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     6.3006 [dt_iop_reload_defaults] defaults reloaded for highlights
     6.3006 [temperature] failed to read camera white balance information from `P1020334.RW2'!
     6.3007 [dt_iop_reload_defaults] defaults reloaded for temperature
     6.3008 [dt_iop_reload_defaults] defaults reloaded for invert
     6.3008 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     6.3079 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     6.3081 [dt_dev_read_history_ext] temporary history merged with image history
     6.3083 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.3083 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.3083 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     6.3084 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     6.3084 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     6.3084 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.3085 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.3085 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.3085 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.3085 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.3086 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.3109 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
     6.3286 [avif_open] failed to parse `/home/user/Pictures/TestHDR/P1020335.RW2': BMFF parsing failed
     6.3287 [rawspeed_open] extensions list to ignore: `cr3'
RawSpeed:Unable to find camera in database: 'Panasonic' 'DMC-GM1S' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
     6.3468 [rawspeed] (P1020335.RW2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&, const std::string&, const std::string&), line 171: Camera 'Panasonic' 'DMC-GM1S', mode '' not supported, and not allowed to guess. Sorry.
     6.3468 [libraw_open] extensions whitelist: `cr3'
     6.3473 [dt_dev_read_history_ext] temporary history deleted
     6.3473 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     6.3473 [dt_iop_reload_defaults] defaults reloaded for basecurve
     6.3474 [dt_iop_reload_defaults] defaults reloaded for colormapping
     6.3474 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     6.3479 [dt_iop_reload_defaults] defaults reloaded for colorin
     6.3479 [dt_iop_reload_defaults] defaults reloaded for crop
     6.3479 [dt_iop_reload_defaults] defaults reloaded for exposure
     6.3479 [dt_iop_reload_defaults] defaults reloaded for retouch
     6.3480 [dt_iop_reload_defaults] defaults reloaded for clipping
     6.3480 [dt_iop_reload_defaults] defaults reloaded for flip
     6.3480 [dt_iop_reload_defaults] defaults reloaded for ashift
     6.3480 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     6.3486 [dt_iop_reload_defaults] defaults reloaded for lens
     6.3486 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     6.3486 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     6.3486 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     6.3487 [dt_iop_reload_defaults] defaults reloaded for demosaic
     6.3487 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     6.3487 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     6.3487 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     6.3487 [dt_iop_reload_defaults] defaults reloaded for highlights
     6.3487 [temperature] failed to read camera white balance information from `P1020335.RW2'!
     6.3489 [dt_iop_reload_defaults] defaults reloaded for temperature
     6.3489 [dt_iop_reload_defaults] defaults reloaded for invert
     6.3489 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     6.3509 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     6.3509 [dt_dev_read_history_ext] temporary history merged with image history
     6.3509 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.3509 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.3510 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     6.3510 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     6.3510 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     6.3510 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.3510 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
     6.3510 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
     6.3511 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.3511 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
     6.3511 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     6.3533 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[exiv2 dt_exif_read_blob] : : Failed to open the data source: No such file or directory (errno = 2)
     6.3571 [exif] `-hdr.dng` dng illuminant 21 (6500K) selected from  [1] 21 (6500K), [2] 0 (0K), [3] 0 (0K)
     7.9909 [avif_open] failed to parse `./-hdr.dng': BMFF parsing failed
     7.9910 [rawspeed_open] extensions list to ignore: `cr3'
     7.9911 [rawspeed] (-hdr.dng) virtual rawspeed::RawImage rawspeed::DngDecoder::decodeRawInternal(), line 472: Image has zero size
     7.9912 [libraw_open] extensions whitelist: `cr3'
     7.9923 [dt_dev_read_history_ext] temporary history deleted
     7.9924 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
     7.9925 [dt_iop_reload_defaults] defaults reloaded for basecurve
     7.9926 [dt_iop_reload_defaults] defaults reloaded for colormapping
     7.9926 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
     7.9926 [dt_iop_reload_defaults] defaults reloaded for crop
     7.9926 [dt_iop_reload_defaults] defaults reloaded for exposure
     7.9926 [dt_iop_reload_defaults] defaults reloaded for retouch
     7.9926 [dt_iop_reload_defaults] defaults reloaded for clipping
     7.9927 [dt_iop_reload_defaults] defaults reloaded for flip
     7.9927 [dt_iop_reload_defaults] defaults reloaded for ashift
     7.9927 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
     7.9927 [dt_iop_reload_defaults] defaults reloaded for lens
     7.9927 [dt_iop_reload_defaults] defaults reloaded for scalepixels
     7.9927 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
     7.9928 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
     7.9943 [dt_iop_reload_defaults] defaults reloaded for colorin
     7.9943 [dt_iop_reload_defaults] defaults reloaded for demosaic
     7.9943 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
     7.9943 [dt_iop_reload_defaults] defaults reloaded for hotpixels
     7.9943 [dt_iop_reload_defaults] defaults reloaded for cacorrect
     7.9943 [dt_iop_reload_defaults] defaults reloaded for highlights
     7.9943 [dt_iop_reload_defaults] defaults reloaded for temperature
     7.9943 [dt_iop_reload_defaults] defaults reloaded for invert
     7.9944 [dt_iop_reload_defaults] defaults reloaded for rawprepare
     8.0040 [dt_dev_read_history_ext] temporary history initialised with default params and presets
     8.0040 [dt_dev_read_history_ext] temporary history merged with image history
     8.0042 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
     8.0042 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
     8.0043 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
     8.0043 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
     8.0072 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
    12.1019 Session fullpipe cache report. hits/run=0.00, hits/test=0.000

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Can reproduce on flatpak and distro rpm package

**Comment by kmilos** [comment]
It doesn't work because the camera is not supported, so need to handle https://github.com/darktable-org/darktable/issues/15265 first.

**Comment by victoryforce** [comment]
And obviously, once this camera is supported, HDR creation should work. Therefore, I see no point in keeping this issue open.

**Comment by jenshannoschwalm** [comment]
Closing this as
1. Not related to Linux at all
2. Rawspeed got the image support already so pretty soon it will be in master.

**Comment by kmilos** [comment]
@SkiTcH-VI Please feel free to verify w/ the updated cameras.xml

**Comment by SkiTcH-VI** [comment]
It works now, thanks!
