### ISSUE TITLE
#15271 causes every lua script to start when darktable starts

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#15280]
### Describe the bug

When #15271 is installed, darktable tries to start every lua script in the ~/.config/darktable/lua directory.

I'm not sure of the cause at present, but you end up with a messed up darktablerc file as the result.  It may be fixable by just deleting all the lua lines, but I'm trying to report this before it affects too many people.

### Steps to reproduce

1. git pull
2. build darktable
3. start darktable
4. observe all the loading messages and the UI going nuts

### Expected behavior

darktable should not try and start every script on startup

### Where did you install darktable from?

darktable.org

### darktable version

darktable 4.5.0+685~g46ff33e4f2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

```
46ff33e4f27bbfc07a8fc9b48cd35b6e68921218 is the first bad commit
commit 46ff33e4f27bbfc07a8fc9b48cd35b6e68921218
Author: Milos Komarcevic <milos.komarcevic@arm.com>
Date:   Mon Sep 18 16:58:43 2023 +0200

    convert grayscale config to bool

 data/darktableconfig.xml.in | 10 +++++-----
 src/control/conf.c          |  2 +-
 src/imageio/format/avif.c   | 10 +++++-----
 src/imageio/format/tiff.c   | 10 +++++-----
 4 files changed, 16 insertions(+), 16 deletions(-)

```

@kmilos I just did a quick look at the commit...  Maybe something to do with the true/false....

**Comment by wpferguson** [comment]
src/control/conf.c 

Adding `&& (str[0] != '0')` breaks all the lines in the darktablerc file that leave a value blank to represent false and only explicitly set true

**Comment by kmilos** [comment]
We still need to check for numbers as well since changing type from your int to bool...

Would a positive test for '1' work instead?

**Comment by wpferguson** [comment]
It's not an int, it's a string, i.e. `=TRUE` for for false `=`

**Comment by kmilos** [comment]
I know. But we changed a param from int type to bool type, so can now also get strings "0" and "1" from an old config...

**Comment by wpferguson** [comment]
But what happens if 0 is really 0 and 1 is really 1.  Do they get changed to bools?

>I  know. But we changed a param from int type to bool type, so can now also get strings "0" and "1" from an old config...

But it breaks everyone's darktablerc file if they are using lua scripts, which may not be a problem because the result is darktable crashes so you can't do anything anyways.

So, perhaps we should revert #15271 and figure out a way to do it without breaking things.  Maybe it requires changes to the Lua API, but it also needs some kind of peaceful transition, not a crashing darktable to announce the change.

**Comment by wpferguson** [comment]
Just a thought.  Maybe changes to how we handle the configuration file should be their own separate PR to ensure they get plenty of visibility and testing, since it may effect things that we weren't aware of.

**Comment by wpferguson** [comment]
This works for conf.c

`const int val = (str[0] != 'F') && (str[0] != 'f') && (str[0] != '0') && (str[0] != '\0');`

Just add a check for an empty string
