### ISSUE TITLE
Canon EOS Kiss F issues

### ISSUE THREAD

**Issue by markfqs** [darktable-org/darktable#15299]
### Describe the bug

Since darktable 3.x, (may be older) I found that cameras.xml list "Canon EOS 1000D" (equivalent) with aliases:

* EOS Digital Rebel XS
* EOS Kiss Digital F

But my camera reports itself as "_Canon EOS Kiss F_" (without Digital), so I added the alias and it worked. I have been manually workarround this since DarkTable 3.x (I will be pleased if someone does it upstream).

However, on DarkTable 4.4 some (but **not al**l) previously edited photos (with older DarkTable version) appear fully black.

If I go to darkroom and go back to 'original' in history stack, the image appears as RAW (so the RAW file is OK and contains the image)

Removing the cabinet .xmp file (and losing my edits) makes darktable recover the image again.

As lighttable shows the existing rating, tags and color mark I don't think about a corrupted XMP

So summarizing:

* Occurs with photos edited in old DarkTable versions (3.x)
* Not all photos show the issue (many appear OK)
* If I reset the history stack back to 'original' the RAW image is properly shown
* XMP seem fine (as lighttable shows the rating,tags and colors assigned)
* Removing the xmp (and losing the edition) make the image appear OK (so I suspect of some module incompatibility),

I can upload the RAW and XMP files if you would like

### Steps to reproduce

1- Edit cameras.xml file to add "Canon EOS Kiss F" Alias to "Canon EOS 1000D" camera
2- Load RAW file into darktable

### Expected behavior

Darktable should show the proceesed image result

### Logfile | Screenshot | Screencast

[darktable.log](https://github.com/darktable-org/darktable/files/12699640/darktable.log)
![Screenshot from 2023-09-22 12-12-44](https://github.com/darktable-org/darktable/assets/8191236/3218117c-3e69-4e28-9f23-46481e71484d)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2-1.1+69.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

System doen't matter, tested in a Dell Laptop 
XPS13 9333 Intel(R) Core(TM) i7-4510U  (4 cores) with 8GiB RAM

and in a Desktop Dell Inspiron 3847 Intel(R) Core(TM) i7-4790 CPU (8 cores) 16GiB RAM

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
> But my camera reports itself as "_Canon EOS Kiss F_" (without Digital), so I added the alias and it worked. I have been manually workarround this since DarkTable 3.x (I will be pleased if someone does it upstream).

Please provide a sample at https://raw.pixls.us/ and I will look into upstreaming that. @LebedevRI 

> However, on DarkTable 4.4 some (but not all) previously edited photos (with older DarkTable version) appear fully black.

IIRC, around 4.0 or 4.2 there were some changes made in how Canon black and white levels were handled. Instead of resetting the whole history, you could try resetting just the raw black/white point module?

**Comment by markfqs** [comment]
Hi thanks for the quick response

You were right, the problem was with the raw black/white point module, as after resetting it the images appeared OK. Thanks much for pointing it.

Sadly they are personal family photos I wouldn't like to public upload to raw.pixls.us, I will research for other photos to upload (although not affected by this issue) shot with this "Canon EOS Kiss F".

As additional note I found one of them shown full white instead of black (and the fix was the same).

Thanks much.

**Comment by kmilos** [comment]
@markfqs The alias has been added permanently since dt 4.6, can this issue be closed now?

**Comment by LebedevRI** [comment]
I'm regularly hitting these "image is black/white" when even just testing submodule updates,
there must be a lot more race conditions than the last time i checked.

**Comment by kmilos** [comment]
On Canons only? If so, it might be a consequence of switching to reading black and white levels from raw file metadata rather than cameras.xml before dt 4.6, so one has to hit reset on the rawprepare module.

**Comment by LebedevRI** [comment]
> On Canons only?

No
