### ISSUE TITLE
Color calibration: make the slider colours in the channel mixer more intiutive

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15292]
**Is your feature request related to a problem? Please describe.**
Using the channel mixer is a recurring question at discuss.pixls.us.
In the comment https://discuss.pixls.us/t/howd-they-do-this-achieving-a-specific-look-in-darktable/39572/9, Boris describes why he drags each of the sliders:
"In the green channel I increased green with input red (to get orange) and input blue (to get cyan) "
"In the blue channel I decreased the value of blue with input red (to have more yellow in red)"

**Describe the solution you'd like**
Would it make sense to replace the bars to reflect the effect? For example, instead of
![](https://d2x313g9lpht1q.cloudfront.net/original/3X/1/7/17cc54162812d7256c83b10bb602a0f3bf3f7367.png)
Instead of magenta -- green pairs, colour the slider under of red from magenta to yellow; similarly, colour the slider under blue from magenta to cyan (I hope I got the colours right); and similarly for the green and blue sliders on the red channel, red and green on the blue channel.

**Alternatives**
Leave as-is, the new _rgb primaries_ module provides a more intuitive interface.

**Comment by Nilvus** [comment]
Hi Kofa,

It could seems unintuitive but that module just show what it does. I so don't think it's good to change that. You could read on color calibration page in the manual, following statement:

> For a more intuitive understanding of how the mixing sliders on the R, G and B tabs behave, consider the following:
> 
>     for the R destination channel, adjusting sliders to the right will make the R, G or B areas of the image more “red”. Moving the slider to the left will make those areas more “cyan”.
>     for the G destination channel, adjusting sliders to the right will make the R, G or B areas of the image more “green”. Moving the slider to the left will make those areas more “magenta”.
>     for the B destination channel, adjusting sliders to the right will make the R, G or B areas of the image more “blue”. Moving the slider to the left will make those areas more “yellow”.

See R, G, B tabs part on manual: https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/color-calibration/

When you understand just above statement (quite easy finally), channel mixer become intuitive.

Changing to what you propose will break that logic and what channel mixer does.

**Comment by kofa73** [comment]
I understand the maths behind the channel mixer.

However, taking the following from the manual:
> for the G destination channel, adjusting sliders to the right will make the R, G or B areas of the image more “green”. Moving the slider to the left will make those areas more “magenta”.

If on the green (destination) channel up move the _input R_ slider to the right, I'll mix more green to the reds. Thus, the reds will be shifted towards yellow. Sure, they will become 'more green', but for a red hue that means shifting towards yellow. If I have a colour as input RGB (70%, 0%, 0%), and I use 10% for _input R_ on the the green channel, I'll shift that colour to (70%, 7%, 0%) -> no longer pure red, a bit shifted towards yellow.

This is how a desaturated pinkish hue looks in the Gimp mixing +/-100%, +/-30%, +/-10% of R into G:
![image](https://github.com/darktable-org/darktable/assets/3177739/2c55f556-188e-4156-ad77-3974f99d1b04)

I think if the red slider on the green channel went from magenta to yellow, it'd show the effect mixing input R into target G would have on the image.

**Comment by europlatus** [comment]
I just wanted to say that the title should perhaps be edited to say "color calibration" because we are not talking about the color balance RGB module here.

**Comment by kofa73** [comment]
Thanks for the correction, @europlatus and @ralfbrown.
