### ISSUE TITLE
Noise Profile for Sony ILCE-6700

### ISSUE THREAD

**Issue by zinger565** [darktable-org/darktable#15297]
For noise profiles, please also attach the entire archive with `.pdf` plots.

Noise profile for Sony a6700.

`{
  "version": 0,
  "noiseprofiles": [
    {
      "maker": "Sony",
      "models": [
        {
          "comment": "ilce-6700 contributed by zingerpb",
          "model": "ILCE-6700",
          "profiles": [
            {"name": "ILCE-6700 iso 100", "iso": 100, "a": [5.76053979453422e-06, 1.64066922966823e-06, 2.85686415339633e-06], "b": [4.01668774056514e-09, 9.98930190588784e-10, 3.52099537986009e-09]},
            {"name": "ILCE-6700 iso 125", "iso": 125, "a": [6.14360146353539e-06, 1.96213051808145e-06, 3.44369725153972e-06], "b": [7.29246851221506e-09, 1.59384202545674e-09, 4.52527250526334e-09]},
            {"name": "ILCE-6700 iso 160", "iso": 160, "a": [8.43830931265727e-06, 2.41413259128975e-06, 4.27699985503522e-06], "b": [7.50366387783866e-09, 2.62587140373834e-09, 6.40128115487989e-09]},
            {"name": "ILCE-6700 iso 200", "iso": 200, "a": [1.03116755376055e-05, 2.9561030333074e-06, 5.25359227307302e-06], "b": [1.02551737082835e-08, 3.94940487374463e-09, 8.69056611532273e-09]},
            {"name": "ILCE-6700 iso 250", "iso": 250, "a": [1.27167716020352e-05, 3.62836636437792e-06, 6.4906527631863e-06], "b": [1.38017625151036e-08, 5.89371939742931e-09, 1.17102403746839e-08]},
            {"name": "ILCE-6700 iso 320", "iso": 320, "a": [1.64800513966764e-05, 4.63958119464139e-06, 8.32499998427807e-06], "b": [1.45029996619789e-08, 5.53234187717876e-09, 1.2187598854578e-08]},
            {"name": "ILCE-6700 iso 400", "iso": 400, "a": [2.03534997457091e-05, 5.70196882475284e-06, 1.02868848466887e-05], "b": [1.8973832793303e-08, 7.68834354778311e-09, 1.57727589599677e-08]},
            {"name": "ILCE-6700 iso 500", "iso": 500, "a": [2.52110762831804e-05, 7.10056009450875e-06, 1.28708565731686e-05], "b": [2.47159633604734e-08, 1.05836733135886e-08, 2.05821214923002e-08]},
            {"name": "ILCE-6700 iso 640", "iso": 640, "a": [3.11599433434169e-05, 8.78756725706935e-06, 1.59169738757878e-05], "b": [3.22504145245829e-08, 1.45202465035735e-08, 2.68638191346383e-08]},
            {"name": "ILCE-6700 iso 800", "iso": 800, "a": [3.87772469550643e-05, 1.09752242199879e-05, 1.98983138735287e-05], "b": [4.08087230018107e-08, 1.95690472717791e-08, 3.46606492556151e-08]},
            {"name": "ILCE-6700 iso 1000", "iso": 1000, "a": [4.84501685938573e-05, 1.37206522441251e-05, 2.49019719157765e-05], "b": [5.22198811352048e-08, 2.59513702953746e-08, 4.47820612545891e-08]},
            {"name": "ILCE-6700 iso 1250", "iso": 1250, "a": [6.0776819372837e-05, 1.71398486218102e-05, 3.12957869800792e-05], "b": [6.59484647015256e-08, 3.49604945322332e-08, 5.62959643035763e-08]},
            {"name": "ILCE-6700 iso 1600", "iso": 1600, "a": [7.57718315646812e-05, 2.13470571026429e-05, 3.91487776714039e-05], "b": [8.27948343033413e-08, 4.69414321379659e-08, 7.22741244287671e-08]},
            {"name": "ILCE-6700 iso 2000", "iso": 2000, "a": [9.49522495029707e-05, 2.67723052950055e-05, 4.90624517155735e-05], "b": [1.03899546472129e-07, 6.11739206585868e-08, 9.12609693942212e-08]},
            {"name": "ILCE-6700 iso 2500", "iso": 2500, "a": [0.000119734809504315, 3.37871146152048e-05, 6.17579015569583e-05], "b": [1.28282789878586e-07, 8.01330174832348e-08, 1.1467670376128e-07]},
            {"name": "ILCE-6700 iso 3200", "iso": 3200, "a": [0.000149720406002819, 4.2564780279924e-05, 7.7783945306085e-05], "b": [1.56055828206538e-07, 1.01801255329722e-07, 1.41641207085749e-07]},
            {"name": "ILCE-6700 iso 4000", "iso": 4000, "a": [0.000188637071713793, 5.35473037311419e-05, 9.83299161705534e-05], "b": [1.93806229366126e-07, 1.34578367195364e-07, 1.78160310247483e-07]},
            {"name": "ILCE-6700 iso 5000", "iso": 5000, "a": [0.000236211826233346, 6.70755576293674e-05, 0.000123454654935268], "b": [2.33095526280788e-07, 1.70417351799916e-07, 2.19349567965472e-07]},
            {"name": "ILCE-6700 iso 6400", "iso": 6400, "a": [0.000298290627660824, 8.45648111397153e-05, 0.000154909345003776], "b": [2.79432322949163e-07, 2.14377635420347e-07, 2.70622030221362e-07]},
            {"name": "ILCE-6700 iso 8000", "iso": 8000, "a": [0.000375283732720437, 0.000106949986572504, 0.000195945749497864], "b": [3.36566244428701e-07, 2.74904136843124e-07, 3.35764980168448e-07]},
            {"name": "ILCE-6700 iso 10000", "iso": 10000, "a": [0.000469709163288037, 0.000133849683268407, 0.00024680882099669], "b": [3.81445051840935e-07, 3.41662827950407e-07, 4.03021811619142e-07]},
            {"name": "ILCE-6700 iso 12800", "iso": 12800, "a": [0.000598589557764176, 0.000170150425979597, 0.00031346276261512], "b": [4.37460166886083e-07, 4.30669646968546e-07, 4.98535355541121e-07]},
            {"name": "ILCE-6700 iso 16000", "iso": 16000, "a": [0.000420213250027509, 0.000118927847723971, 0.000211522107904091], "b": [5.02611106257439e-07, 4.52706657431437e-07, 5.39864048181092e-07]},
            {"name": "ILCE-6700 iso 20000", "iso": 20000, "a": [0.000529602308389873, 0.000150627134333399, 0.000268402379309673], "b": [5.49169854485803e-07, 5.32692397976574e-07, 6.23657864865721e-07]},
            {"name": "ILCE-6700 iso 25600", "iso": 25600, "a": [0.000666125430175872, 0.000189035906485928, 0.00033725938603723], "b": [5.88119450596344e-07, 6.5247433095073e-07, 7.4283962428867e-07]},
            {"name": "ILCE-6700 iso 32000", "iso": 32000, "a": [0.00087783501937456, 0.000246734163409722, 0.000445728542402174], "b": [4.74782382320257e-07, 5.70369653394941e-07, 6.46330794364318e-07]},
            {"name": "ILCE-6700 iso 32000", "iso": 32000, "a": [0.000860062394895381, 0.000243252662242582, 0.000434433836512951], "b": [4.02641753283809e-07, 6.05240672434411e-07, 6.77327624785912e-07]},
            {"name": "ILCE-6700 iso 40000", "iso": 40000, "a": [0.00108031263659543, 0.000308270529351213, 0.000554402950358943], "b": [2.6991673947087e-07, 7.07021298520812e-07, 7.30007712507438e-07]},
            {"name": "ILCE-6700 iso 51200", "iso": 51200, "a": [0.00136097783040805, 0.000387702994221882, 0.000696672654431157], "b": [2.10843642494744e-07, 1.04566956903592e-06, 1.07160774184481e-06]},
            {"name": "ILCE-6700 iso 64000", "iso": 64000, "a": [0.00172119448961222, 0.000488724737503561, 0.000892309836440566], "b": [-5.76834148389228e-09, 1.58191847607904e-06, 1.61393626262433e-06]},
            {"name": "ILCE-6700 iso 80000", "iso": 80000, "a": [0.00209332483618867, 0.000627153392137457, 0.00113069390817479], "b": [-5.46364822129028e-07, 2.2080994135526e-06, 2.04892367823974e-06]},
            {"name": "ILCE-6700 iso 102400", "iso": 102400, "a": [0.00285453544659552, 0.000834263410371187, 0.00149319805708772], "b": [-1.70900577074965e-06, 2.48461706476613e-06, 2.40854223206604e-06]}
          ]
        }
      ]
    }
  ]
}
`

[darktable-noiseprofile-20230921.tar.gz](https://github.com/darktable-org/darktable/files/12696405/darktable-noiseprofile-20230921.tar.gz)

**Comment by KevinDAdam** [comment]
Thanks for contributing this @zinger565. I was looking to do the same, but didn't have any black card to run the test.
Tried adding the presets into noiseprofiles.json and it seems to be making a good job :)

**Comment by KevinDAdam** [comment]
@zinger565 - were these taken with RAW compressed or RAW lossless compressed?

**Comment by zinger565** [comment]
> @zinger565 - were these taken with RAW compressed or RAW lossless compressed?

Hey, I don't recall off hand, and am away from my camera for a few days. Not sure if there's a way to tell from the .arw itself, but they range in size from 26MB to 31MB

**Comment by kmilos** [comment]
> Not sure if there's a way to tell from the .arw itself

Of course there is, that's what exiftool/exiv2 is for 😉

**Comment by da-phil** [comment]
I just saw that this ticket is still open and easy to fix so I spend a minute to set up a PR: https://github.com/darktable-org/darktable/pull/15369

**Comment by rawfiner** [comment]
Perfect, thank you @da-phil !
Time flies unfortunately, I wish I could be more reactive... Doing PR like you did definitely helps, thank you!
