### ISSUE TITLE
Build from GIT fails to complete

### ISSUE THREAD

**Issue by dtteufel** [darktable-org/darktable#15307]
### Describe the bug

I have been successfully building from the git for many years - now it
fails to complete!

/home/****/darktable/src/imageio/imageio_exr.cc: In function
‘dt_imageio_retval_t dt_imageio_open_exr(dt_image_t*, const char*,
dt_mipmap_buffer_t*)’:
/home/****/darktable/src/imageio/imageio_exr.cc:145:15: error:
‘hasCameraMake’ is not a member of ‘Imf’
  145 |       if(Imf::hasCameraMake(header))
      |               ^~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

### Steps to reproduce

I cloned the GIT by the usual method:
git clone --recurse-submodules --depth 1 https://github.com/darktable-org/darktable.git

and used the usual build command: ./build.sh --prefix /opt/darktable-test --build-type Release --install
--sudo

I always delete the 'build' and 'opt/darktable-test' directories before
running the script. 

### Expected behavior

Build should complete without errors!

### Where did you install darktable from?

darktable.org

### darktable version

b63c20d46e - compiles later not

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.2/Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
Commit you point is about one week. Some days ago an issue block compile. This had been fixed same day. Just update master and you should be able to build master. Be sure to be on last commit before posting such issue. If building works again, think about closing that issue.

**Comment by dtteufel** [comment]
Still failing to complete from current master.
See attached build log.
[git build.log](https://github.com/darktable-org/darktable/files/12706927/git.build.log)

**Comment by gi-man** [comment]
Most likely this change: https://github.com/darktable-org/darktable/pull/15141

Ubuntu 22.04 is on OpenEXR 2.5.7 per repology.

**Comment by wpferguson** [comment]
I'm building on 22.04 without problems.  OpenEXR is 2.5.7-1

**Comment by wpferguson** [comment]
Differences -

I have libheif > 13.0

but don't have

Imath or JXL

I'm at 4.5.0+727~gc41951c53b
I'm building with RelWithDebInfo

**Comment by dtteufel** [comment]
#15141
Excluding EXR in DefineOptions.cmake allows build to complete.
openEXR 3.x.x is not avaiable for Ubuntu 22.04.

**Comment by gi-man** [comment]
I don't think we should close this yet. Let's ping @kmilos to have a look.

**Comment by dtteufel** [comment]
@gi-man
That seems sensible.
The real issue is that those of us using LTS versions of Ubuntu often have to wait a very long time for updates to esoteric packages.
I tried to compile openEXR 3.2 on Ubuntu 20.04 but it seems there are far too many dependency issues!

**Comment by kmilos** [comment]
The dt CI uses Ubuntu 22.04, and builds just fine w/ OoenEXR 2.5.x, as confirmed by @wpferguson

**Comment by dtteufel** [comment]
@kmilos 
Yes I note that, but nonetheless my build fails ...
I can live without openEXR for the moment, perhaps it is a compiler issue.
I'll investigate further.
Thank you

**Comment by kmilos** [comment]
It looks like you do have OpenEXR 2
3.2 installed from somewhere....

**Comment by wpferguson** [comment]
Are you removing the build directory between builds.  Sometimes leftover "things" make the compile fail.  I always remove the build directory to make sure this doesn't catch me (again).

**Comment by dtteufel** [comment]
Thanks to all who assisted with this. 
Pilot error I fear. We can now put this to bed.

@kmilos 
You are quite right - I had attempted and failed to compile openEXR 3.2.0, it nonetheless created libraries in /usr/local/ that I had failed to notice. I have removed them.
@wpferguson 
Yes indeed, I also remove both 'build' directory and installed version prior to compile.

Happily, I can now compile from git master.
However, as I have openEXR 2.5.7 installed the build completes without EXR  as is to be expected.

**Comment by kmilos** [comment]
> I have openEXR 2.5.7 installed the build completes without EXR

It does not, it'll use 2.5.7 quite happily for now (as in the updated CMake output above). Check your `darktable --version` output.

**Comment by dtteufel** [comment]
@kmilos 
All working fine now.
I had to remove jxl to allow libopenexr-dev to install!
Many thanks for your persistence.

darktable 4.5.0+756~g76cf661582
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimizations enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.2.0
  Colord support enabled
  gPhoto2 support enabled
  G'MIC support enabled (compressed LUTs will be supported)
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support disabled
  libjxl support disabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
