### ISSUE TITLE
change_timestamp in main.images might not be updates

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#15303]
### Describe the bug

The timestamp for change is not kept correct in all cases.

1. when called from 'discard-history' it is always zero 
2. rotation in lighttable seems not to affect it at all.

### Steps to reproduce

Apply suggested triggers 1) or 2) and check via some tool.

### Expected behavior

Should keep a changing timestamp :-)

### Commit

don't know

### Where did you install darktable from?

self compiled

### darktable version

today's master

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Does not matter here

**Comment by TurboGit** [comment]
See #15304.

Also I haven't changed the time stamp for discard history. The fact that the TS is set to NULL is done on purpose to be able to get all images not yet edited.
