### ISSUE TITLE
sqlite3 error when searching for searching collection for camera

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#15302]
### Describe the bug

Searched for `Canon EOS R` while testing #15301.  Got the following error in the log...

```
sqlite3 error: /home/bill/src/darktable/darktable/src/common/collection.c:854, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT mi.id) FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,                flags, version,  position, aspect_ratio,               aperture, exposure, focal_length,               iso, import_timestamp, change_timestamp,               export_timestamp, print_timestamp        FROM main.images AS mi                WHERE 1=1) AS mi WHERE   (flags & 256) != 256  AND  (( (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/bill/Pictures/darktable45/Play.Raw'))) AND ( (1=1) AND (1=1) AND 1=1 AND ((1=0)  OR camera_id IN (SELECT id FROM main.cameras WHERE maker || ' ' || model LIKE '%Canon EOS R%')))) ORDER BY import_timestamp, datetime_taken, filename, version LIMIT ?1, ?2": no such column: camera_id
sqlite3 error: /home/bill/src/darktable/darktable/src/common/collection.c:857, function _dt_collection_compute_count(): no such column: camera_id
```

Maybe introduced by #15293

@AlicVB 

### Steps to reproduce

1. start darktable in a terminal
2. open collection filters
3. add new rule based on camera
4. fill in` Canon EOS R`
5. hit enter
6. check console output

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+719~g641d72e618

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
Thanks for reporting @wpferguson. The same issue was reproducible with the lens filter. Both should be fixed now.
