### ISSUE TITLE
Filmic RGB reconstruction with slider on bloom causes gray highlights when not using OpenCL

### ISSUE THREAD

**Issue by Tai-Mai** [darktable-org/darktable#15329]
### Describe the bug

While writing this issue, I actually fixed it myself by installing OpenCL. Before I did that, this is what happenend to me when I tried to reconstruct highlights with filmic RGB and moved the bloom $\leftrightarrow$ reconstruct slider to the left. 

In the first picture, the highlight reconstruction module is enabled by default.

![image](https://github.com/darktable-org/darktable/assets/57625350/9043afc0-8bea-49a8-8108-5bd134d1fcc1)

I'm using the default options:
![image](https://github.com/darktable-org/darktable/assets/57625350/22930cf3-ed67-4419-b475-0c9f7e1ac9bf)

I tried disabling the highlight reconstruction module, which is enabled by default, and when I do that, the highlights turn pink.

![image](https://github.com/darktable-org/darktable/assets/57625350/76677f5d-229a-4973-a86b-514bd6036e7f)

White balance is left at default (camera reference).

### Steps to reproduce

1. Make sure OpenCL is not enabled in settings
2. Open a RAW image (in my case a Nikon .NEF file)
3. Check "enable highlight reconstruction" in the filmic rgb module
4. Set the threshold to where the clipped highlights are masked
5. Move the bloom $\leftrightarrow$ reconstruct slider towards bloom and observe the highlights becoming a darker and darker gray

### Expected behavior

Moving the bloom $\leftrightarrow$ reconstruct slider towards bloom should bloom the highlights and not turn them gray

### Logfile | Screenshot | Screencast

[d_common_log.txt](https://github.com/darktable-org/darktable/files/12717915/d_common_log.txt)
[d_opencl_log.txt](https://github.com/darktable-org/darktable/files/12717959/d_opencl_log.txt)

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Arch

### Describe your system?

* Kernel: 6.5.4-arch2-1
* KDE
* X11
* NVIDIA GeForce GTX 970, proprietary drivers
* AMD Ryzen 5 2600
* 16 GB RAM

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 970, proprietary drivers

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I'm pretty sure I had the same issue on Wayland. The weird thing is that it used to work for me as expected a couple of days ago before I had OpenCL installed/enabled. System updates might have broken something else?

**Comment by gi-man** [comment]
Can you check if the problem is still there in current master? 

https://github.com/darktable-org/darktable/issues/15203

https://github.com/darktable-org/darktable/pull/15223

**Comment by Tai-Mai** [comment]
Looks like it is. Thanks! Sorry I wasn't able to find those issues before. I'll close the issue.
