### ISSUE TITLE
"can't find history entry while adding mask" error when snapshot gets activated

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#15327]
### Describe the bug

When you use drawn masks and then create a snapshot, when you activate it you get an error message like 
`can't find history entry 24 while adding mask brush #8(1695655754)`

### Steps to reproduce

1. create drown mask in some module 
2. create snapshot and activate it 

### Logfile | Screenshot | Screencast

[darktable_snapshot_error.txt](https://github.com/darktable-org/darktable/files/12717348/darktable_snapshot_error.txt)

https://github.com/darktable-org/darktable/assets/38165484/76fa6340-75b0-4a70-b480-bbc1691eb299

### Where did you install darktable from?

[darktable.org](https://github.com/darktable-org/darktable)

### darktable version

4.5.0+756~g76cf66158

### What OS are you using?

Linux

### What is the version of your OS?

Ununtu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-1028-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
NVIDIA driver: 535.86.05

### Are you using OpenCL GPU in darktable?

Yes

**Comment by s7habo** [comment]
>  I tried a simple edit/snapshot and couldn't reproduce. 

yes, this only happens when you have _drawn mask_. I have also tried with parmetric and raster masks and there was no error with them.

**Comment by TurboGit** [comment]
Fix is here : #15328.

Not that the bug is only an alarming display on the console, but everything else was functional.
