### ISSUE TITLE
Change Request: Primaries RGB parameters and history change report values should be consistent

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#15337]
The values in history change report and the parameters of primaries RGB module aren't consistent:

![image](https://github.com/darktable-org/darktable/assets/39386816/e341c3b5-4baf-4ddb-9b7c-e6b3e78e3f10)

**Describe the solution you'd like**
gui parameters and displayed parameters should be equal

(detected in current master)

**Comment by dterrahe** [comment]
The history diff uses introspection to directly look at the internal representation, whereas the sliders apply additional transformation and formatting. At the time I would have liked to add those to introspection as well, but this was vetoed by @houz

**Comment by MStraeten** [comment]
in this case the display of change is quite useless, because there's no chance to get the relation between gui settings and internal representation so that veto is quite strange from an user perspective ;)

**Comment by dterrahe** [comment]
Yep.
