### ISSUE TITLE
CR3 Files not showing up during import

### ISSUE THREAD

**Issue by BentiGorlich** [darktable-org/darktable#15336]
### Describe the bug

`.cr3` files are not beeing recognized while importing. There are a lot of those already in the library, but the import dialog hides them now... Do I have to enable that somewhere or do I have to install a library. This problem occured after I fixed #15334 , so after I switched from Win 10 to Fedora 38. To fix my previous problem I deleted every windows path entry in my config at `~/.config/darktable/darktablerc`. I don't think that this causes this problem, but I don't know.
I found this forum post, seemingly having a similar problem: https://darktable.club/d/565-upgraded-to-4-2-now-can-t-import-cr3-files

### Steps to reproduce

1. Open DT
2. Click on `add to library...` 
3. Select folder that contains CR3 files. 
4. CR3 files don't show up

### Expected behavior

Show the CR3 files to import

### Where did you install darktable from?

distro packaging

### darktable version

darktable-4.4.2-1.fc38

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

- CPU: Ryzen 3600
- GPU: Nvidia Rtx 2700 SUPER
- RAM: 32 GB

### Are you using OpenCL GPU in darktable?

Yes

**Comment by kmilos** [comment]
Fedora packages exiv2 w/o BMFF support enabled, so CR3s are simply not support on Fedora OOTB.

**Comment by BentiGorlich** [comment]
If thats the case, why are the ones already in my library working flawlessly? And how do I fix it? Is there a workaround? Does using the flatpack version linked on the homepage fix it?

**Comment by kmilos** [comment]
> why are the ones already in my library working flawlessly?

Are they? Try re-reading their metadata etc.

**Comment by BentiGorlich** [comment]
How would I do that? And I mean obviously it doesn't work anymore... I am fairly certain that even importing CR3 files worked before I update a bunch of stuff sometime last week...

**Comment by ptilopteri** [comment]
examine your library.db using sqlite3 or sqlitebrowser or ...

**Comment by BentiGorlich** [comment]
How is examining my library.db rereading the metadata...

**Comment by ptilopteri** [comment]
your library.db *should* contain the data in your xmp files.

**Comment by BentiGorlich** [comment]
I disabled the XMP files, because they clutter my nextcloud instance (yeah I know I could just add them to the ignore list, but I don't like these sidecar files)

**Comment by ptilopteri** [comment]
ok then.  your library.db *should* contain the data your xmp files
would contain.

**Comment by BentiGorlich** [comment]
Appreciate your help, but as I said using the flathub version works for me :)

**Comment by barukasu** [comment]
I have the same issue. I also have fedora 38. This was working fine a week ago. 

What does this mean?  "library.db should contain the data your xmp files
would contain." 

How can I fix this problem or help with the developers find this bug?
