### ISSUE TITLE
Crash on opening the import dialog

### ISSUE THREAD

**Issue by BentiGorlich** [darktable-org/darktable#15334]
### Describe the bug

Whenever I open the import dialog darktable crashes within 5 seconds

### Steps to reproduce

1. Open Darktable
2. Expand the import menu
3. click on "add to library...."
4. wait a few seconds
5. crash

### Expected behavior

just open the import dialog and let me choose photos

### Where did you install darktable from?

distro packaging

### darktable version

darktable-4.4.2-1.fc38

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

- CPU: Ryzen 3600
- GPU: Nvidia Rtx 2700 SUPER
- RAM: 32 GB 

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Notably I switched from windows to linux and corrected the file paths in the darktable database, so I suspect that this is a factor within the crash. I have not been able to find the logfiles of darktable, so if anyone could tell me where they are I'll be more than happy to provide the logs

**Comment by BentiGorlich** [comment]
I found 2 log files in the `/tmp` folder, so I attached them here
[darktable_bt_970ZB2.txt](https://github.com/darktable-org/darktable/files/12725492/darktable_bt_970ZB2.txt)
[darktable_bt_N760B2.txt](https://github.com/darktable-org/darktable/files/12725494/darktable_bt_N760B2.txt)

**Comment by BentiGorlich** [comment]
Thats a great info. I suspected the same thing, but I couldn't find the file I need to edit so DT wouldn't crash anymore. I removed all references in the old windows style that were in there and the import dialog doesn't crash anymore, thank you :)

**Comment by jenshannoschwalm** [comment]
@BentiGorlich i am interested in getting this fixed "generally". Unfortunately i couldn't modify the darktablerc file in such a way to reproduce. Could you share that file (or the parts you had to remove)?

**Comment by BentiGorlich** [comment]
github mails kinda fly by and I don't notice. Yes it just works now as it should.
