### ISSUE TITLE
Mouse wheel sensitivity is a bit too low

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#15335]
### Describe the bug

Everywhere in DT where I scoll up and then down , or down and then up, I must roll two 'clicks' in the opposite direction. 
Only the second click is picked up.   

It feels unreliable.

This does not happen in other applications.

It is like one roll of the mousewheel gives 99 points and DT only responds at 100.

### Steps to reproduce

It happens with my Logitech MX 3 mouse; not with every mouse.

I can not change the DPI or sensitivity of the mousewheel.

Every other program on my computer responds immediately to the first motion of the mousewheel. 

### Expected behavior

DT should scroll everytime I scroll the mousewheel

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 23.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel UHD and intel driver

**Comment by wpferguson** [comment]
> I can not change the DPI or sensitivity of the mousewheel.

Actually, you can as well as remap buttons

https://github.com/PixlOne/logiops

**Comment by piratenpanda** [comment]
I wonder if this really is a dt issue and not a libinput one. I also suffer the same with my anywhere 2s but it seems to be in almost every application for me.

**Comment by jenshannoschwalm** [comment]
> I wonder if this really is a dt issue and not a libinput one. I also suffer the same with my anywhere 2s but it seems to be in almost every application for me.

Absolutely true.
