### ISSUE TITLE
Upload to Piwigo fails

### ISSUE THREAD

**Issue by fgtham** [darktable-org/darktable#15343]
### Describe the bug

Export to Piwigo fails with generic error message "[imageio_storage_piwigo] could not upload to Piwigo!".

After setting `piwigo_EXTRA_VERBOSE TRUE` the following server reply is logged: `server reply: {"stat":"fail","err":1003,"message":"image_id must be an positive and not null integer"}`. Simply removing the `image_id` from the upload request fixes the upload for me:

```
diff --git a/src/imageio/storage/piwigo.c b/src/imageio/storage/piwigo.c
index 14487b8b3d..bbda957923 100644
--- a/src/imageio/storage/piwigo.c
+++ b/src/imageio/storage/piwigo.c
@@ -912,9 +912,6 @@ static gboolean _piwigo_api_upload_photo(dt_storage_piwigo_params_t *p,
   if(p->tags && strlen(p->tags)>0)
     args = _piwigo_query_add_arguments(args, "tags", p->tags);
 
-  if(pwg_image_id >= 0)
-    args = _piwigo_query_add_arguments(args, "image_id", pwg_image_id_string);
-
   _piwigo_api_post(p->api, args, fname, FALSE);
 
   g_list_free(args);
```

### Steps to reproduce

1. In the export module, log in to Piwigo, refresh folder list, start export.
2. Export fails.

### Expected behavior

darktable should upload the image(s).

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+723~g12fe3a93dd

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

irrelevant

**Comment by TurboGit** [comment]
So maybe just:

```
-  if(pwg_image_id >= 0)
+ if(pwg_image_id > 0)
```

But now we need to understand why `pwg_image_id` is 0 in some cases.

**Comment by TurboGit** [comment]
After checking the code doing this:
```
-  if(pwg_image_id >= 0)
-    args = _piwigo_query_add_arguments(args, "image_id", pwg_image_id_string);
-
```
Will actually break the update metadata if the picture has already been uploaded.

Can you confirm that the upload is done with option `on conflict` set to `don't check`?

**Comment by TurboGit** [comment]
And can you check that this fixes the issue:

```
diff --git a/src/imageio/storage/piwigo.c b/src/imageio/storage/piwigo.c
index 14487b8b3d..6712f2c1d8 100644
--- a/src/imageio/storage/piwigo.c
+++ b/src/imageio/storage/piwigo.c
@@ -1251,7 +1251,7 @@ int store(dt_imageio_module_storage_t *self,
 
     if(status)
     {
-      int pwg_image_id = NO_IMGID;
+      int pwg_image_id = -1;
 
       if(conflict_action != DT_PIWIGO_CONFLICT_NOTHING)
       {

```

**Comment by fgtham** [comment]
> Can you confirm that the upload is done with option `on conflict` set to `don't check`?

If I set `on conflict` to `don't check`, the upload will fail.

> And can you check that this fixes the issue:
> 
> ```
> diff --git a/src/imageio/storage/piwigo.c b/src/imageio/storage/piwigo.c
> index 14487b8b3d..6712f2c1d8 100644
> --- a/src/imageio/storage/piwigo.c
> +++ b/src/imageio/storage/piwigo.c
> @@ -1251,7 +1251,7 @@ int store(dt_imageio_module_storage_t *self,
>  
>      if(status)
>      {
> -      int pwg_image_id = NO_IMGID;
> +      int pwg_image_id = -1;
>  
>        if(conflict_action != DT_PIWIGO_CONFLICT_NOTHING)
>        {
> ```

Yes, this fixes the issue for me. After patch application the upload completes successfully. Thanks!

**Comment by TurboGit** [comment]
Thanks for testing, now fixed in master.
