### ISSUE TITLE
Do not switch collection when move completes

### ISSUE THREAD

**Issue by zakwilson** [darktable-org/darktable#15352]
### Describe the bug

When I'm organizing photos, I often apply several  filters to a collection, select the results, and move them to an external hard drive. I might repeat this several times before I have all the photos where I want them. When Darktable completes the move, it switches the active collection to the destination, often while I'm in the middle of setting up the next set of filters. I would like it not to change the collection when a move finishes.

### Steps to reproduce

1. View any collection in lighttable view
2. Select some images
3. Click [selected images] -> [move]
4. Choose a destination

### Expected behavior

Not change the active collection

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Arch

### Are you using OpenCL GPU in darktable?

None

**Comment by elstoc** [comment]
I think I prefer the existing functionality. It's pretty easy to revert back to the previous collection from the "recently used collections" module.

**Comment by zakwilson** [comment]
It's easy to revert if you're not in the middle of building your next search. It's pretty jarring when an asynchronous operation finishes and resets the state of the UI.
