### ISSUE TITLE
Make it possible to chose between framing/no framing in full preview layout in Lighttable

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#15356]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by KIRSJ** [comment]
The problem is that the current thin frame is covering the outer pixels of the image, which can hide edge problems.
Under Preferences the framing feature should be an option - not just at default feature.
The obvious alternative would be to add the frame to the image - i.e. draw the frame on the 'canvas' and not upon the image.
Maybe the frame drawing can be avoided by including a CSS under General?

**Comment by ptilopteri** [comment]
in the setting menu (hamburger icon upper right) 
open darkroom tab
there is a setting: border around image in darkroom mode.

I set to "0"
perhaps this solves your problem.

if so, please close issue

**Comment by KIRSJ** [comment]
If you are talking about the ISO 12646 framing in Darktable - that one is perfect.
I am talking about the framing**in full preview in Lighttable**.
I can't follow your instruction - no 'setting menu' visible - and the 'border around image in darkroom mode' is not the issue.

**Comment by AlicVB** [comment]
@KIRSJ : yes, the border is define in css, so easy to change : 
something like
```
.dt_fullview #thumb-main:selected #thumb-image
{
  border: none;
}

.dt_fullview #thumb-main:hover #thumb-image
{
  border: none;
}
```
But be aware that with this css, you will loose the "image hovering" indication...

**Comment by KIRSJ** [comment]
Just what I needed. Thank you, AlicVB.

**Comment by KIRSJ** [comment]
Solved.
