### ISSUE TITLE
preset: make it possible to set "lensfun-method", while still auto-detecting the other parameters of the file

### ISSUE THREAD

**Issue by airflow2010** [darktable-org/darktable#15359]
### Describe the bug

I would like to auto-apply a mainly blank "lens-correct" preset to all my pictures to fix distortion. This worked fine in the past using the "lens-fun" method. Depending on focal length and other parameters the correct corrections were applied. However, since some recent darktable version, instead of the lens-fun-method, the "embedded metadata" method is used per default. This doesn't work in my case. Corrections are not applied. After some research, I found that my habit to convert all my pictures from Sony RAW to Adobe DNG (I do this for disk space preservation) is to blame. The "embedded metadata" method works for Sony RAW, but not for Adobe DNG. :-(

As I workaround, I would like to continue using the lensfun-method. However, when I update the preset with the setting "lensfun-method", this also saves and sets the detected focal length as the same value for all pictures. This is basically impossible to use, because now the properties of the picture are not set for the correct values, therefore the corrections are not applied properly.

### Steps to reproduce

1. create preset for lens-correction for correction of converted DNG-files
2. auto-apply them to pictures with different focal-length
3. a) if preset is set to have blank values - doesn't work because of "embedded metadata" default, which does not work with DNG
4. b) if preset is set to have pre-filled values to set "lensfun-method" - other parameters are not dynamically set when preset is being auto-applied

### Expected behavior

darktable should make it possible to create a auto-apply preset for lensfun-enabled auto-correction

### Where did you install darktable from?

darktable.org

### darktable version

4.2.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

None

**Comment by jenshannoschwalm** [comment]
I think we have either
1) the file takes dng lens corrections which are wrong due to wrong conversion
2) we don't check the correction parameter properly.

Could you share such a file?

**Comment by airflow2010** [comment]
> I think we have either
> 
> 1. the file takes dng lens corrections which are wrong due to wrong conversion
> 2. we don't check the correction parameter properly.
> 
> Could you share such a file?

Absolutely! Please find attached a sample picture in the format DNG, converted with the Adobe DNG converter tool. As this is a very recent picture, I still had the original ARW (Sony RAW) on my SD-card. So I can provide this as a reference as well. If you open both in darktable, you'll see that the corrections won't work out of the box with the DNG-variant. You have to manually select "lensfun-method" to make it work, as described above.

due to size restrictions, I have to provide it via link:
DNG: https://web.fp.on.at/FPS04079.DNG
ARW: https://web.fp.on.at/FPS04079.ARW

**Comment by paolodepetrillo** [comment]
In this case the Adobe DNG Converter has put a WarpRectilinear opcode in the DNG file which performs only TCA correction but not distortion correction (leaves the green channel unchanged). darktable is applying this correction properly when lens correction is enabled as 'embedded metadata'. So it looks like for some unknown reason Adobe DNG Converter is ignoring the distortion correction in the ARW file.

**Comment by jenshannoschwalm** [comment]
Right, so not a dt issue at all

**Comment by airflow2010** [comment]
OK. Thanks for checking. So that means the Adobe DNG converter is not properly converting the relevant metadata. That's bad, and I hope Adobe fixes this in the converter at some point. I will check if there is a more recent version available than which I use.

Speaking of workarounds, setting the correction-method in the lens correction module to "lensfun" does work - in this case, corrections are applied correctly for my DNG files. However, I am not able to make this preset work in an automized way. It seems that I cannot set the method in the preset permanently to "lensfun" without also permanently setting the focal length and other parameters which should instead be dynamically set.

Regarding this preset issue, is my observation correct and I cannot apply lens correction with lensfun method automatically, or do you have an idea how to achieve this?

**Comment by jenshannoschwalm** [comment]
You could do a camera-specific prest ...

**Comment by airflow2010** [comment]
> You could do camera-specific preset.

You mean lens-specific preset? I only have one camera. But even if I make a lens-specific preset, in case it's a zoom-lens, I cannot set a fixed focal length within the preset, as it can have a range of different values for focal length for the same lens. :-(

**Comment by airflow2010** [comment]
Just upgraded to latest version of Adobes DNG converter. Issue remains.

I convert because of two reasons: filesystem space preservation (DNG conversion nearly cuts space requirements in half). And the idea of a "universal" RAW-format, vendor-independent. Latter is debatable.

So there is no option to make a preset with lensfun-method pre-selected, while the other fields are dynamically set? Mmh. That's a bummer. Perhaps there is some option somewhere to disable the "embedded metadata"-method generally, so darktable falls back to lensfun automatically?

**Comment by TurboGit** [comment]
>  Latter is debatable.

Both are wrong. If it save spaces it loose probably information as RAW are compressed. And the universality of DNG is a pure fiasco.

**Comment by airflow2010** [comment]
> Both are wrong. If it save spaces it loose probably information as RAW are compressed. And the universality of DNG is a pure fiasco.

Ever heard of lossless compression?

**Comment by jenshannoschwalm** [comment]
Whatever,if you want to convert to DNG, that's up to you. Just make sure that adobe does include lens correction and leaves no lens correction data. Or let adobe convert the vendor data to proper dng opcodes so no lensfun but what dng files should do, use embedded data. That's what the standard is for.

**Comment by TurboGit** [comment]
> Ever heard of lossless compression?

Sure and what? RAW has also lossless compression.

**Comment by airflow2010** [comment]
> Sure and what? RAW has also lossless compression.

1) DNG is lossless compression (opposed to your statement that it "probably looses information", which is wrong)
2) Sony's RAW does *not* have lossless compression, it's lossy actually. So your second statement is also wrong (for Sony).

**Comment by TurboGit** [comment]
All good then, Sony is to me quite broken by providing only lossy compression. At least nothing we can do on dt side.

**Comment by jenshannoschwalm** [comment]
Loosing information is not about compression but vendor information not exposed via exif data. Also most images I saw after converting where sraw files done with Adobe demosaicer which is often of worse Quality that what dt offers.
