### ISSUE TITLE
segmentation fault when clicking on "add to library" or "copy & import"

### ISSUE THREAD

**Issue by MarkoSchuetz** [darktable-org/darktable#15365]
### Describe the bug

On a freshly started execution of darktable, when I click on either "add to library" or on "copy & import" I consistently get a segmentation fault.

### Steps to reproduce

 Start darktable
click on "add to library"

### Expected behavior

A dialogue should open for me to choose a file.

### Logfile | Screenshot | Screencast

[darktable_bt_PV7VB2.txt](https://github.com/darktable-org/darktable/files/12807115/darktable_bt_PV7VB2.txt)

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Describe your system?

I'm using Xorg. I have this hunch that it might have to do with the KDE tiling window manager bismuth, but that's just a guess...

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by rekcodocker** [comment]
If you delete your database file when darktable is not active (home/YourUser/.config/darktable/library.db ) , does it still happen?

**Comment by jenshannoschwalm** [comment]
Did you re-use your settings file? Or a brand-new?

**Comment by MarkoSchuetz** [comment]
> If you delete your database file when darktable is not active (home/YourUser/.config/darktable/library.db ) , does it still happen?

Yes

**Comment by MarkoSchuetz** [comment]
> Did you re-use your settings file? Or a brand-new?
> 
> EDIT: duplicate of #15334 maybe ?

I now tried with a brand-new: same thing.

**Comment by MarkoSchuetz** [comment]
I even tried with a completely new .config/darktable folder and it still crashes in the same way.

**Comment by MarkoSchuetz** [comment]
I experimented with this some more: among the many folders inside Pictures, there was a folder called 'Bilder f'$'\374''r Ralf' that had been there since around 2005. It had never before caused any issues, but apparently darktable cannot handle it now. Interestingly, the same happened with rawtherapee. I've now renamed that folder and both programs no longer crash.
So, it seems that a library that both use is to blame?

**Comment by jenshannoschwalm** [comment]
Thanks you identified that folder name...

**Comment by jenshannoschwalm** [comment]
I tried to add a directory with the `...ralf` name and cannot reproduce here. Could you try to re-create such a directory and try to reproduce?

**Comment by fwilmsh** [comment]
I'm currently experiencing the exact same behavior. Same with existing config as well as with a freshly created config folder and database. 
If darktable is started on the console i get some big stacktrace, mostly gtk stuff and many things optimized out. 
I've attached the stacktrace. Let me know if I can/should repeat this with any debug symbols or similar. 

[darktable_bt_Y26702.txt](https://github.com/user-attachments/files/18550324/darktable_bt_Y26702.txt)
