### ISSUE TITLE
Panasonic DMC-G10

### ISSUE THREAD

**Issue by twjacobs** [darktable-org/darktable#15368]
Please add support for the Panasonic DMC-G10. I have uploaded raw files through raw.pixls.us (P1030954.RW2, P1030957.RW2, P1030963.RW2, P1030971.RW2) on Oct. 4, 2023. I populated the comment field with the aspect ratio the picture was taken in.

**Comment by kmilos** [comment]
Feel free to make changes to your local cameras.xml as in the linked PR in the meantime.

**Comment by kmilos** [comment]
> It's a bit weird the basic/fallback mode is not being used?

Ah, this is because we explicitly set `d->failOnUnknown = true;` in the dt loader...
