### ISSUE TITLE
There is no more SSE on IOP

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15376]
Should we then now stop testing on the CI the non-sse branch?

This will save some CPU cycles on GitHub-CI and lesser CO² emission!

@victoryforce @ralfbrown?

**Comment by victoryforce** [comment]
This is exactly what I was going to suggest.

**Comment by ralfbrown** [comment]
The few remaining bits of SSE/nonSSE duplicate code are all selected at compile time, and the non-x86 builds would cover the nonSSE variants, so I concur that we can drop the non-SSE tests on x86.
