### ISSUE TITLE
Ability to hide scopes

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#15382]
In preferences we have the option to place scopes on the right or left so I place my scopes on the left to give myself more  room for the modules on the right. However, I rarely use the scopes during my editing and they take up valuable screen real estate. Would it be practical to add the option to disable scopes in the preferences. Alternatively could we contract the scopes module and only expand it when we need it. This second option might also be good for the navigation panel as we sometimes need it expanded, but other times it is just consuming limited screen real estate.

**Comment by ptilopteri** [comment]
not sure what you call scopes but you can hide the left side
menu panel
<ctrl><shift><L>

if that satisfies your needs, please consider closing this issue

**Comment by ralfbrown** [comment]
Already possible without hiding the corresponding side panel: Ctrl-Shift-H to toggle Scopes (H because it use to be the Histogram module) and Ctrl-Shift-N to toggle the navigation window.

**Comment by tpinfold** [comment]
Thanks Ralf for the solutions. I will close the issue.
