### ISSUE TITLE
Retouch circles get lens correction applied in latest git

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15384]
### Describe the bug

I almost finished a picture and then decided to change the crop of it and had to use the retouch module to clone out a tree. I noticed that the circle shape changes depending on the area of the image you are on.  Also when the circles overlap the arrow points away from the area that is getting changed and not to the area. Most likely two different bugs but I wanted to report anyway.

And here's a screenshot:
![retouch](https://github.com/darktable-org/darktable/assets/920721/dd5e5c93-c74f-4390-8584-86120bef154e)
This is NOT! using ellipses as shape, but circles

When disabling lens corrections this goes away but I think lens corrections should not influence the shapes of the retouch module independent from where in the module order it gets inserted. Also this is the default location and I did not change it that leads to the above behaviour.

### Steps to reproduce

Use lens correction on a wide-angle lens and then enable retouch.

### Expected behavior

darktable should always show the selected shape and not apply lens correction to it

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+811~g9e99f783c5

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD 6700 XT, ROCM 5.7

**Comment by AlicVB** [comment]
Hi,

This has already been discussed lot of time, and we have decided to leave it as it is now : 
- when you are doing some retouch, you want to patch/hide/correct/... a specific subject in the image
- for sure, you don't want this subject area to change during further editing, including "distortion" one
- so we need to store shapes positions/size... in the initial image space. Then transform all there points through the pipeline.

Currently, the only drawback is that circle can sometime appear distorted (what you mention here), but you'll note that the distorted shape correspond exactly to the changed area... which is what we need...

If for some reason you really need to have a "real" circle in the final image space, I would suggest to use a path shape, with enough points

I leave the issue open, for the second point you mentioned (the arrow). @TurboGit : iirc you have worked on that point recently ?

**Comment by MStraeten** [comment]
it’s not a bug but a feature: masks are applied in relation to the raw geometry, so also the retouch masks.

**Comment by piratenpanda** [comment]
Yeah now after reading your comments and thinking about it it makes totally sense. Thanks!

**Comment by ralfbrown** [comment]
The arrow direction is I think the result of a recent change to connect the closest point fo the source outline to the closest point of the target outline.  That's exactly what has happened in your screenshot, though I agree it looks wrong.

**Comment by TurboGit** [comment]
> I leave the issue open, for the second point you mentioned (the arrow). @TurboGit : iirc you have worked on that point recently ?

Yes, but was can we do better when shapes overlap? How should one position the arrow?

**Comment by TurboGit** [comment]
> That's exactly what has happened in your screenshot, though I agree it looks wrong.

To me it looks ok, the arrow is really from target to source in the screenshot. It looks weird because the shapes are overlapping.

**Comment by piratenpanda** [comment]
Would arrows from the center of the shapes look strange? Did someone try this already?

**Comment by TurboGit** [comment]
Yes it was from the center before, but then the arrow was hiding part the actual source shape. It has been changed to avoid that and also to have a consistent display for all forms.

**Comment by piratenpanda** [comment]
I understand. I think best would be to close this issue.
