### ISSUE TITLE
Adding new demosaicing methods that do not introduce colour fringes for images containing fine diagonal lines

### ISSUE THREAD

**Issue by dllu** [darktable-org/darktable#15381]
### Describe the bug

The ceiling of this photograph has magenta colour casts in Darktable when using AMAZE, LMMSE, VNG64, PPG, RCD, and combinations thereof. It's either just magenta, or alternating regions of magenta and green. LMMSE has the least colour cast but still noticeable.

PPG:

![image](https://github.com/darktable-org/darktable/assets/14482624/1be6f6ab-8e55-4424-8722-96bd7040beba)

AMAZE:

![image](https://s.dllu.net/8WGLhYljjKl46QHO.png)

VNG64:

![image](https://s.dllu.net/1wd0KAU_05h_deiE.png)

RCD:

![image](https://s.dllu.net/ggPY4mrtEymRF1b5.png)

LMMSE:

![image](https://s.dllu.net/TsebBFCxumq7OHbU.png)

Original straight-out-of-camera JPEG:

![image](https://s.dllu.net/fToJpy_DjQ5r0jhT.png)

Original camera JPEG: https://i.dllu.net/2023-02-11-16-58-22_DSCF8770_a1916a3f44245ec41cf3b3bdff7efdbbb73631db_43469b7b4d81d585.jpg

Original camera RAW: https://i.dllu.net/2023-02-11-16-58-22_DSCF8770_a1916a3f44245ec41cf3b3bdff7efdbbb73631db.raf (I tried to upload it to https://raw.pixls.us/ but they said they already have an image like that or something)

### Steps to reproduce

1. Download the raw file
2. Open it in Darktable
3. Part of the glass ceiling has magenta colour casts when it should not have any

### Expected behavior

darktable should not introduce colour casts

### Commit

83758c7d9c053efd06211941d75fa637437f98f5

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+777~g83758c7d9c

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

```
OS: Arch Linux x86_64
Kernel: 6.5.5-arch1-1
Uptime: 1 hour, 16 mins
Packages: 2311 (pacman)
Shell: bash 5.1.16
Resolution: 7680x4320
WM: i3
Theme: Yaru-Lavender [GTK2/3]
Icons: Adwaita [GTK2/3]
Terminal: alacritty
Terminal Font: black: '
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz
GPU: NVIDIA GeForce RTX 3090
Memory: 8614MiB / 64211MiB
```

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
Turn off filmic and color calibration and you get the equivalent of the jpg root/sky.  The sky is overexposed so when filmic pulls the overexposed area back you get the magenta tint from the over exposure.  The blue shade of the sky is from color calibration doing a white balance.

**Comment by jenshannoschwalm** [comment]
The title is strongly misleading...

**Comment by MStraeten** [comment]
no issue, works as designed - you might use sigmoid if playing around with filmic color reconstruction doesn’t give proper results

**Comment by dllu** [comment]
It is clearly not working as designed, nor is the title misleading. If the color casts were in fact not caused by demosaicing,

* Can you explain why the color cast only shows up in certain parts of the roof where the lines are diagonal but not in areas where it's close to horizontal or vertical?
* Can you explain why changing the demosaicing algorithm changes the amount of color casts and whether it's magenta or partially green?

Color casts in diagonal lines is a well-known and common weakness of classical demosaicing algorithms because of the structure of the Bayer filter. The line goes through either all green pixels or all red and blue pixels. However, newer deep-learning based techniques can overcome such challenging cases.

**Comment by wpferguson** [comment]
> Can you explain why the color cast only shows up in certain parts of the roof where the lines are diagonal but not in areas where it's close to horizontal or vertical?

Chromatic aberations

Zoom in to 1600%. to an area with diagonal lines.
Select original image from the history stack.
Step up the history stack and notice the changes.
Once you've got to filmic, enable the chromatic aberrations module.  Notice the color fringing is removed.

Original

![original](https://github.com/darktable-org/darktable/assets/1634891/752f2a28-2035-406b-843f-03ee314dffcb)


chromatic aberrations applied

![ca](https://github.com/darktable-org/darktable/assets/1634891/fbafaeeb-3e58-4b16-9249-63554563ef27)

**Comment by jenshannoschwalm** [comment]
Or raw chromatic fixing...

**Comment by dllu** [comment]
The CA module can be a band-aid solution since it removes any magenta edges but chromatic aberrations are not a root cause of the issue. If it were chromatic aberrations, we would see that the fringes depend on whether the lines are tangential or sagittal, rather than whether the lines are diagonal or horizontal. Moreover, the lens is a very high quality one that has very little chromatic aberrations. I can take some test pictures with all the lines in the center of the image to demonstrate this later.

**Comment by wpferguson** [comment]
It's not about the lens. You have a bright (overexposed in places) light source back lighting.  the ceiling grid.  You're going to get color fringing

**Comment by dllu** [comment]
The fact that the fringes are highly orientation dependent even when it's in the middle of the image strongly suggests that it's an artifact from demosaicing. Yes, perhaps there are some chromatic aberrations, but the amount is far less than what you suggest, and cannot possibly introduce this sort of inconsistent color casts in different parts of the roof due to different orientations of the fine line structures.

You can take a slightly overexposed photo of concentric black and white rings in the middle of the image to verify this yourself.

PPG:

![ppg](https://s.dllu.net/oL4ezNsoFUIAwh1s.png)

Amaze:

![amaze](https://s.dllu.net/gd4s9glBjvSKMQEo.png)

VNG64:

![vng64](https://s.dllu.net/9iSCdyFfnDdXe5zS.png)

RCD:

![rcd](https://s.dllu.net/a81ubkNevkWKu_SD.png)

LMMSE:

![lmmse](https://s.dllu.net/RhyH5EPwfM-_O8cT.png)

Close up of AMaZE:

![amaze](https://s.dllu.net/wZnPML5eWnjH0L_Z.png)

Straight out of camera JPEG:

![jpeg](https://s.dllu.net/1w7BwoQvFDgONLBB.png)

In each case, you'll see that along the diagonals close to 45 degrees, the magenta casts are maximized. For the horizontal or vertical lines, there are occasionally yellow or teal casts instead. 

I'll also point out a separate bug: The preview is demosaiced without taking into proper account for the boundary of the image, leading to even worse color artifacts near the boundaries. This could be fixed by rendering the preview with some slight padding beyond the boundary of the viewport.

**Comment by jenshannoschwalm** [comment]
You seem to hop from one point to the next. What exactly is the issue you are reporting?

**Comment by dllu** [comment]
The issue is that the demosaicing methods implemented in Darktable do not cope well with high contrast edges and often introduce color artifacts.

**Comment by jenshannoschwalm** [comment]
I agree here (at least partly), there are artefacts at regions with sharp white-black-white transitions close to nyquist frequency related to the maths behind them. That's a problem of all demosaicers i am aware of unfortunately.

1. Are you aware of any demosaicer algo that is safe? Or any prefilter ...?
2. Would you share your concentric rings raw with a proper licence so we/i can keep that for further evaluations.
3. Could you please update the issue title to something more clear?

**Comment by wpferguson** [comment]
Perhaps this should just be a feature request to implement a deep learning demosaic module.  Take the justification from the title and add it to the description.

**Comment by jenshannoschwalm** [comment]
> ... request to implement a deep learning demosaic module.

I re-did a search for publications including source code and still could not find any state-of-the-art and efficient implementations, same as last year.  Are you aware of any? Or do you you know someone who has been working on this?

**Comment by dllu** [comment]
I found https://github.com/ddlee-cn/MuLUT, a recent paper from last year, which claims to outperform classical demosaicing algorithms while being super fast. It is supposedly many orders of magnitude faster than D-LMMSE while being equally as good. 

![image](https://github.com/darktable-org/darktable/assets/14482624/ffbf04f4-cc48-4fa4-8d6f-857526331163)

I would also be interested in seeing if there are any ways of making [demosaicnet](https://github.com/mgharbi/demosaicnet) faster. As far as I'm aware, the deep demosaicing techniques implemented in Lightroom and Topaz use something like that for joint demosaicing and denoising.

**Comment by jenshannoschwalm** [comment]
Aah, thanks I think i already saw other stuff from those people before. @dllu have you been working somehow on these topics? Interested to go into it?

**Comment by jenshannoschwalm** [comment]
Just one more comment. There was a bug in LMMSE demosaicer, now having better results using master.
