### ISSUE TITLE
metadata are not included after exporting photos

### ISSUE THREAD

**Issue by rail02000** [darktable-org/darktable#15387]
### Describe the bug

The exported photo didn't include metadata like EXIF. 
However it works properly sometimes. I have had a hard time to figure out which setting could solve the issue.

### Steps to reproduce

1.import a photo ("open with darktable" from digikam, or just "add to library" in darktable.
2.export without changing anything or exporting after edited(for example haze removal)
3.the exported file didn't include any metadata for example EXIF.

Which settings i have tried - sometimes it works fine, and sometimes not.
- changing interface language: en/zh_tw/ja
- "use raw file instead of embedded JPEG from size" switch to NERVER or ALWAYS
- enable disk backend for full preview cache" turns to ON or OFF
- disabling openCL didn't change anything.
- "create sidecar files" and "store XMP tags in compressed format" turns to NEVER or other options.

### Expected behavior

metadata should be inclueded in exported photo

### Logfile | Screenshot | Screencast

the logfile of staring darktable -> importing 3S9A8248.JPG -> export it
[darktablelog.txt](https://github.com/darktable-org/darktable/files/12841222/darktablelog.txt)

### Where did you install darktable from?

OBS

### darktable version

4.5.0~git816.b4955f75-10696.4

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed 20231006

### Describe your system?

KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.4-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600 6-Core Processor
Memory: 46.9 GiB of RAM
Graphics Processor: AMD Radeon RX 6600

AMD ROCm 5.6.0.50600-sles154.67

![Screenshot_20231009_002753](https://github.com/darktable-org/darktable/assets/111188018/3fa830fa-028a-4f9e-92f5-c44c5d2fa1c0)
![Screenshot_20231009_002802](https://github.com/darktable-org/darktable/assets/111188018/8ab4b3e7-fd70-4652-bc16-5d44bb82edb8)
![Screenshot_20231009_002812](https://github.com/darktable-org/darktable/assets/111188018/aa5234e8-4025-4783-a177-28f272d4f604)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600, 8GB, kernel-firmware-amdgpu 20230829-1.1

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- I didn't try another darktable version. But it works fine in September.
- both RAW and JPEG
- Are the steps above reproducible with a fresh edit : yes
- Is the issue still present using an empty/new config-dir : no
-  Do you use lua scripts? : no

**Comment by rail02000** [comment]
Hi, i tried a setting and it seen to work fine in my environment.

1. "create sidecar files"  - after edit , "store XMP tags in compressed format" - only large entries
2. import a photo
3. export it -> no metadata included
4. edit it and export it -> works fine.

**Comment by ralfbrown** [comment]
There is an issue with AVIF exports if you don't enable *all* ExIF tags.
But first be sure that you have in fact enabled export of the tags you want (by default, tags are not exported for privacy reasons) in the Export module.
See #14755, #14303, #12394, and many more....
