### ISSUE TITLE
RFC: collection sorting order for tags

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15383]
In the left pan of lighttable we have the collection module. There is an option to sort the entries in the collection in ascending or descending order. Fine.

This also affect the **tags** order which I feel this being wrong. We really have the habit to have an order from A to Z for names. So to me changing the order for all collections is fine but I think we should always keep tag order from A to Z as a common ascending order. 

I don't remember this being discussed before... Hence the RFC !

Thoughts?

**Comment by jenshannoschwalm** [comment]
Would agree to keep a-z sorting, also would not want to add some sort-otherwise ui thing.

**Comment by pehar1** [comment]
> always keep tag order from A to Z

Never used a different sorting order for tags.

**Comment by zisoft** [comment]
Never changed the sort order of tags because a-z is what I expect and used to.

**Comment by da-phil** [comment]
I wouldn't know how else to sort tags, ascending order seems to also make most sense for me.
