### ISSUE TITLE
White balance Applied twice every time.

### ISSUE THREAD

**Issue by SteveMan67** [darktable-org/darktable#15390]
### Describe the bug

Whenever I go into the white balance module and adjust the temperature slider, an error appears at the top of the module, saying "White Balance Applied Twice," even thought I adjusted the temperature by 1 degree kelvin.

### Steps to reproduce

1. Go to the active modules tab
2. find White Balance
3. Adjust the temperature slider.

### Expected behavior

Darktable should not see this as an error, at the least.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by pehar1** [comment]
I guess you have activated the modules "white balance" _and_ "color calibration".
Please read the manual https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/color-calibration/, especially section "CAT warnings".

**Comment by SteveMan67** [comment]
The part that makes this a bug, which I didn't make clear (sorry) was that If I open a photo, do nothing except adjust the white balance, do not even touch the Color Calibration module, and adjust the slider for temperature, It still reports the same error

**Comment by ptilopteri** [comment]
if you will look at the "history" window on the left panel, you will see that "white balance" is automagically applied when you open an image to edit.  your subsequent white balance edit *is* a second occurance

**Comment by pehar1** [comment]
> The part that makes this a bug

This is not a bug. Please read the manual : https://darktable-org.github.io/dtdocs/en/preferences-settings/processing/
You can set "_auto-apply pixel workflow defaults_" to "_none_".
