### ISSUE TITLE
ILME-FX3

### ISSUE THREAD

**Issue by SkinniestSpade** [darktable-org/darktable#15393]
Hello, 

I have already submited a raw sample, I understand that the FX3 has the same sensor as the A7Siii, which is supported. Is there anyway I could use darktable with my FX3 raws, either via an option or a setting I missed?

Thank you.

**Comment by kmilos** [comment]
Thanks for the samples (Ideally all compression modes and crops should be submitted together).

You can help test https://github.com/darktable-org/rawspeed/pull/461 in the meantime.

**Comment by LebedevRI** [comment]
Thank you for the sample.
FWIW, that sample is rather bad. RPU very intentionally asks for something daylight-based.

**Comment by LebedevRI** [comment]
@SkinniestSpade it would be really helpful if you could contribute a better sample.
The current one is horrendeous.

**Comment by LebedevRI** [comment]
b220d54d8ea6c8b8bca8c7d1b28e50cfe67838ea
