### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by vredesbyyrd** [darktable-org/darktable#15409]
### Describe the bug

Darktable is producing two zombie children processes.

### Steps to reproduce

1. Run Darktable
2. View Darktable process in any process monitor, e.g bottom

### Expected behavior

Darktable does not produce zombie processes

### Logfile | Screenshot | Screencast

There does not appear to be anything suspicious in the log, but here is output from `darktable -d common` .  I also disabled `OpenCL` but the issue persists. 

[darktable.log](https://github.com/darktable-org/darktable/files/12887507/darktable.log)

![Screenshot from 2023-10-12 16-09-10](https://github.com/darktable-org/darktable/assets/22080838/b1f3b8d3-8874-4691-a607-b84015fd25f5)

### Where did you install darktable from?

self compiled

### darktable version

4.5.0.r828.g13c3c99e8d

### What OS are you using?

Linux

### What is the version of your OS?

Archlinux

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel UHD Graphics 620

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I first noticed the issue on `4.5.0.r828.g13c3c99e8d`. Prior I was on `4.5.0.r548.g59c3eaa6d1` which did not have the issue.

**Comment by wpferguson** [comment]
Can't reproduce on Ubuntu 22.04

**Comment by ptilopteri** [comment]
cannot reporduce on openSUSE Tumbleweed 20231010
self compiled darktable 4.5.0+880~gdfa03dc5b

**Comment by simonspa** [comment]
I can reproduce this on Fedora 39, dt 4.4 either compiled from source of installed from Fedora RPM. Whenever I quit darktable, the process never ends regularly but zombies out:

![image](https://github.com/darktable-org/darktable/assets/1677436/e6f97a9c-99c9-4132-816c-e1866c829012)

**Comment by vredesbyyrd** [comment]
I can no longer reproduce this issue on latest master `1.7.5.r191.ge74c2dc2-1`. 

I am going to close this. If anyone else can still reproduce ping me and I can reopen.
