### ISSUE TITLE
unsupported input profile has been replaced by linear REC709 RGB

### ISSUE THREAD

**Issue by glsarto** [darktable-org/darktable#15405]
### Describe the bug

loading an old collection of DNGs scanned with Nikon LS5000, colors went beserk with the following message:
"unsupported input profile has been replaced by linear REC709 RGB" 
However:
- same DNG opened in Gimp which in turn loads DT show colors correctly
- same DNG opened in Shotwell show colors correctly
- same DNG opened with same version of DT on other PC shows colors correctly

### Steps to reproduce

open collection

### Expected behavior

DT should display colors correctly

### Logfile | Screenshot | Screencast

![Screenshot from 2023-10-11 18-58-54](https://github.com/darktable-org/darktable/assets/139809549/d657b0f3-c676-4d7c-870b-b7e7a853efd4)

### Commit

don't know, I seldom access this collection

### Where did you install darktable from?

distro packaging

### darktable version

darktable 4.4.2 copyright (c) 2009-2023 johannes hanika https://github.com/darktable-org/darktable/issues/new/choose  compile options:   bit depth is 64 bit   normal build   SSE2 optimized codepath enabled   OpenMP support enabled   OpenCL support enabled   Lua support enabled, API version 9.1.0   Colord support enabled   gPhoto2 support enabled   GraphicsMagick support enabled   ImageMagick support disabled   libavif support enabled   libheif support disabled   libjxl support disabled   OpenJPEG support enabled   OpenEXR support enabled   WebP support enabled

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.03 LTS

### Describe your system?

Lenovo Intel Pentium G3220 32GB RAM 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1650 driver 535.113.01

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- another Ubuntu 22.04.03 with DT 4.4.2 is working fine albeit different Nvidia card
- the collection is made of DNG
- happens just opening the collection
- same as above, load collection in Lighttable
- did not try new config-dir because other collections work fine, only Nikon LS5000 scans show this issue
- don't use LUA scripts

**Comment by glsarto** [comment]
Thanks for pointing me to LCMS2.
Will check next Monday, now I'm away.
I see here, on another Ubuntu 22.04.3 LTS, multiple liblcms2.so installed with snap.
Maybe on the first PC there is the same situation: what should I do? remove the oldest version? How do I do that?

**Comment by glsarto** [comment]
I have a mix of LCMS2 on that system:
/snap/cups/980/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/cups/980/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12
/snap/cups/974/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/cups/974/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12
/snap/snap-store/638/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/snap-store/638/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8
/snap/inkscape/10539/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/inkscape/10539/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12
/snap/inkscape/10542/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/inkscape/10542/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12
/snap/gnome-3-38-2004/143/usr/lib/x86_64-linux-gnu/liblcms2.so
/snap/gnome-3-38-2004/143/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/gnome-3-38-2004/143/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8
/snap/gnome-3-38-2004/140/usr/lib/x86_64-linux-gnu/liblcms2.so
/snap/gnome-3-38-2004/140/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/gnome-3-38-2004/140/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8
/snap/gnome-42-2204/141/usr/lib/x86_64-linux-gnu/liblcms2.so
/snap/gnome-42-2204/141/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/gnome-42-2204/141/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12
/snap/gnome-42-2204/126/usr/lib/x86_64-linux-gnu/liblcms2.so
/snap/gnome-42-2204/126/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/gnome-42-2204/126/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12
/snap/gnome-3-28-1804/194/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/gnome-3-28-1804/194/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8
/snap/gnome-3-28-1804/198/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/snap/gnome-3-28-1804/198/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8
/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.12

do I need to remove the older ones?
how to do that safely?

**Comment by glsarto** [comment]
Gimp, Shotwell and Darktable were installed with apt so I assume they all use /usr/lib/x86_64-linux-gnu/liblcms2.co.2

**Comment by ptilopteri** [comment]
I only have one version on my Tumbleweed system

**Comment by 01tot10** [comment]
I have a similar scenario, same error message, but slightly different symptoms. Wanted to post here first before opening a separate issue. Let me know if this should be given it's own thread.

I'm trying to open some older B&W scans with DT, done with a Plustek OpticFilm 8200i.
While the small thumbnails in Lighttable show up correctly, opening the scans in Darktable gives the same error message as OP reported. In my case, only part of the scan is rendered correctly, and the rest is left black. 

Here's how the small thumbnails look like in Lighttable.
![bug-lighttable-crop](https://github.com/darktable-org/darktable/assets/35490779/6523e130-773f-4e8b-a717-aa243326da52)

When opening any of the scans, Darktable gives the same error as OP and only renders part of the image
![bug-darktable-crop](https://github.com/darktable-org/darktable/assets/35490779/f28c0b8b-8b47-4e4e-8721-3f7286346168)

I tried to upload an example file, but the file is unfortunately larger than the 25Mb limit in Github.
I can upload one to some outside service if needed.

Darktable version:
```
darktable:
  Installed: 4.4.2-1.1+69.1
  Version table:
 *** 4.4.2-1.1+69.1 500
        500 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04  Packages
        100 /var/lib/dpkg/status
```

System:
```
Ubuntu 22.04.3 LTS
```

No GPU.

**Comment by kmilos** [comment]
> I can upload one to some outside service if needed.

Yes, please @01tot10

**Comment by 01tot10** [comment]
> > I can upload one to some outside service if needed.
> 
> Yes, please @01tot10

Edited the earlier post to include an example file.

**Comment by glsarto** [comment]
I was about to say that, while I wasn't able to understand what was the problem, yesterday evening I fixed the issue with:
- remove all pictures from collection
- exit DT
- rm -rf *.xmp
- start DT
- import images
So everything is working as it should and have always been.

**Comment by glsarto** [comment]
issue solved

**Comment by 01tot10** [comment]
Hey @kmilos! 

I upgraded darktable using a [snapshot from the master branch](https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable) but the provided .DNG still renders only partially, similarly as before.

Would you have any further clues what could be causing this?

```
darktable:
  Installed: 4.5.0~git924.06d30b47-1+10740.1
  Candidate: 4.5.0~git924.06d30b47-1+10740.1
  Version table:
 *** 4.5.0~git924.06d30b47-1+10740.1 500
        500 http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_22.04  Packages
        100 /var/lib/dpkg/status
```

**Comment by kmilos** [comment]
Does it work if you remove (backup first if you need to) the XMP sidecars, and also start w/ a clean database? Basically import from scratch...

**Comment by 01tot10** [comment]
Thanks again @kmilos! We got a bit further with the issue, but didn't quite resolve it yet. Do you mind, if I still reply here, since I'm not sure what to include if I'd start a brand new ticket.

There was no sidecar files, which is a bit confusing, since the photos clearly have edits, as the white borders from the raw scan show up in your version, and not mine. Could it be, that an older version of Darktable (from circa ~2019) didn't save the edits in the sidecar, but rather in the library? 

Anyways, starting up Darktable from CLI with a fresh database (`darktable --library :memory:`, see [here](https://docs.darktable.org/usermanual/development/en/special-topics/program-invocation/darktable/)) makes the image render fully, although without the history, which is supposedly stored in the library.  Thus, it would seem that some older version of a module breaks the rendering.

I could open a separate issue, if backwards compatibility is something you support. I would need some help in exporting the right information for you from my library to aid the debugging. Or should I just upload my whole library.db?

**Comment by kmilos** [comment]
@01tot10 Please do open a new issue (the same info is already a good start), as it seems specific to your history. Just mention the exact versions, and I wouldn't upload your entire db file though.

> if backwards compatibility is something you support

Whenever possible, I would say. But someone else will have to dig into this...

**Comment by 01tot10** [comment]
Alright, thanks! I'll start another thread for this issue. Thanks for your time!
