### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [darktable-org/darktable#15411]
### Describe the bug

Dear @darktable-org team, @boucman, @hean01, @houz, @hanatos, @prokoudine,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/darktable/

To disable/delete tabs, go here: https://sourceforge.net/projects/darktable/
To add a new tab, go here: https://sourceforge.net/projects/darktable/
To change informations, go here: https://sourceforge.net/p/darktable/admin/overview
To export, go here: https://sourceforge.net/p/darktable/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/darktable/admin/overview
- A new tab, go here: https://sourceforge.net/projects/darktable/

Thanks in advance.

### Steps to reproduce

Read before.

### Where did you install darktable from?

darktable.org

### darktable version

master

### What OS are you using?

Linux

### What is the version of your OS?

*

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
The best would be to completely remove dt from sourceforge. We probably need @hanatos for this?

**Comment by Neustradamus** [comment]
Dear @darktable-org team, @boucman, @hean01, @houz, @hanatos, @prokoudine,

Have you progressed on it?

**Comment by Neustradamus** [comment]
.

**Comment by Neustradamus** [comment]
.

**Comment by Neustradamus** [comment]
.

**Comment by hanatos** [comment]
.. not that it matters: if i remember correctly i tried to remove it but for whatever reason that wasn't possible. i don't have an sf.net account any more, it was tied to an email address that i no longer have access to. as pretty much every sane person replies in all the other tickets / copies of this ticket for other projects. why does anyone care anyways? the only plausible explanation i have is some sort of social engineering/generating github activity log for a plausible troll account.

**Comment by Neustradamus** [comment]
@hanatos: Can you reopen this ticket which is not solved?

Darktable team on SF: https://sourceforge.net/p/darktable/_members/
Jeremy rosen	boucman	Admin
Henrik Andersson	hean01	Admin
Tobias Ellinghaus	houz	Admin
Johannes Hanika	jhanika	Admin
Alexandre Prokoudine	prokoudine	Admin

Thanks in advance.

**Comment by Neustradamus** [comment]
@TurboGit, like I have specified at begining in this ticket about the team, @hanatos is Johannes Hanika and is jhanika SF Admin, so he can do all requests (like other SF admins) that I have specified to have a really continuous Darktable project.

It is really easy to inform SF users which currently use a very old unsecure Darktable version with CVE since more 10 years...

**Comment by Neustradamus** [comment]
@TurboGit: Because people go on SF, and it is important to inform that the project is now here.

You can see download stats here:
- https://sourceforge.net/projects/darktable/files/stats/timeline

**Comment by wpferguson** [comment]
> don't have an sf.net account any more, it was tied to an email address that i no longer have access to.

No one has admin access or the means to recover the admin account, therefore we can't fix it.
