### ISSUE TITLE
Make polarity icon sense (+)/(-) the same for drawn and parametric masks

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/darktable#15429]
I like the (+) and (-) polarity **icons** now used for both drawn and parametric masks, but find it confusing that the polarity seems reversed when a subset (region/range) is selected or excluded. 
The drawn mask polarity is negative (-) when a drawn mask region is masked. 
The parametric mask polarity is positive (+) when the parametric mask range  is masked. 

**Describe the solution you'd like**
Both polarity icons are positive (+) when a subset (region/range) is selected and negative (-) when the subset (region/range) is excluded. 

**Alternatives**

**Additional context**
Picture of example from dt 4.4.2 web build/install on macOS 14.
interior of drawn shape is selected  - polarity is negative (-) 
parametric yellow-green range is selected - polarity is positive (+) 

![PolarityInvert](https://github.com/darktable-org/darktable/assets/105315850/e78b2e30-ea33-48d2-94f8-fbc2ff02c1d2)

**Comment by MStraeten** [comment]
don’t forget that ‚combine masks‘ selection…

**Comment by TiredOfGuessing** [comment]
@MStraeten Using a search with the "right" term I found the same issue. Per todd-prior It seems the default (-) drawn mask sign is to make the no/zero drawn shapes and a parametric mask scenario work correctly.

So conceptually, drawing a shape is not the addition of a masked region but subtraction from the default "uniform" mask. On the [drawn mask] tab with [no mask used] pressing [show mask icon] makes whole image yellow, so effectively "no mask" means everywhere is masked . So the absence of a mask is the "uniform mask" not "no mask".

I think for the most part in spite of the complexity masks work as expected without considering every setting each time one uses a new mask. But occasionally things get more complicated (I had multiple of each, some inverted, then deleted the shapes without the shape polarity reverting to default), something does not work as expected, then it is a challenged to understand exactly what happened and debug to solution. Hopefully future module/mask-manager enhancements will improve clarity in these interactions.
Thx
[https://github.com/darktable-org/darktable/issues/11860#issuecomment-1136254109](url)
