### ISSUE TITLE
Samsung Galaxy NX (EK-GN120)

### ISSUE THREAD

**Issue by ge0rg** [darktable-org/darktable#15427]
I've read in the darktable 4.4 release notes that Galaxy NX is removed due to missing raw samples, so I had to purchase one to be able to upload some.

I've upladed a first SRW file according to the requirements on RPU, but can provide further raw samples, respective jpeg counterparts if needed, and might be able to convert to dng as well.

**Comment by ge0rg** [comment]
Should be resolved by https://github.com/darktable-org/rawspeed/pull/544

**Comment by LebedevRI** [comment]
@ge0rg thank you for contributing the sample!

**Comment by LebedevRI** [comment]
b220d54d8ea6c8b8bca8c7d1b28e50cfe67838ea
