### ISSUE TITLE
Copying and pasting module order has side effects - or selective copy/paste broken?

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15425]
### Describe the bug

Selective copy/paste (of module order?) has side effects. See more below.

### Steps to reproduce

1. Get the raws and the sidecars from https://tech.kovacs-telekes.org/files/2023-10-15module-order-copy-paste-side-effect/ (note: 2023-09-24-10-09-05_P1010579_05.RW2.xmp is a lighter stack for the 2nd image; the screenshots were made using the original stack, 2023-09-24-10-09-05_P1010579.RW2.xmp, so your output will be somewhat different, but the effect is still obvious),
2. Import them to darktable,
3. Open 2023-09-18-19-49-32_P1010520.RW2; check the module order - it should be _custom_ (filmic and sigmoid have been swapped for this demo):
  ![image](https://github.com/darktable-org/darktable/assets/3177739/1a6ad025-aafd-4a32-aec0-8cac71840cfe)
4. Open 2023-09-24-10-09-05_P1010579.RW2. Check it module order; should be _v3.0 RAW_; the history stack should have 20 elements, the last one being _sigmoid_(with the _05 stack, 14 modules, the last being _crop_):
  ![image](https://github.com/darktable-org/darktable/assets/3177739/0b4f680b-f436-423f-b1c0-8e2c28faaece)
5. In the lighttable, select 2023-09-18-19-49-32_P1010520.RW2, duplicate it, then use Ctrl+Shift+C, keep only _module order_; copy the stack:
  ![image](https://github.com/darktable-org/darktable/assets/3177739/b54609c2-da54-4841-a742-51bd58a62f73)
6. Select 2023-09-24-10-09-05_P1010579.RW2, use Ctrl+Shift+V, keep only _module order_; paste the stack:
  ![image](https://github.com/darktable-org/darktable/assets/3177739/ac468bdc-c557-45b0-8dea-d2b4d4f7a2fa)
7. Observe that the duplicate is flipped around, and its aspect ratio changes:
  ![image](https://github.com/darktable-org/darktable/assets/3177739/0c91ba08-7847-4a10-9a7b-35ad81deb491)
8. Open the duplicate. Its stack contains 37 (with the _05 stack, 32) elements. Above the original _sigmoid_ (entry 20), we have:
  ![image](https://github.com/darktable-org/darktable/assets/3177739/7d762310-d79f-41c3-aaa9-faf1ca8907ad)

### Expected behavior

darktable should only apply the selected item: module order

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+908~g84906440ed

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6GB, 525.125.06

**Comment by pehar1** [comment]
Can reproduce with 4.5.0+1014-g5f25f79812, Ubuntu 22.04

- Happens also if copy is done in darkroom, if the stack of the source image is minimal, if other images are used or if the copy is done the "other way round" (read: copy _V3.0 RAW_ over _custom_).
- Does **not** happen if only **one additional** item is added to _module order_ (two items copied, for example _module order_ and _crop_)
