### ISSUE TITLE
Is it practical to add an eraser to the masking options. 

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#15424]
When I create a parametric mask in DT it usually does a great job, but sometimes there are areas selected by the parametric mask that I would like to erase. I can use a drawn mask brush and subtract it from the parametric mask. But then I don’t see a way of using one instance of the brush to add to the selection and then another to subtract from the selection. Would it be practical to have a separate eraser brush that can remove any part of a drawn or parametric mask. It would also be good if this eraser brush had opacity control so you could do a partial erasing of the mask. 

There may possibly be work arounds for this issue using the mask manager, but a simple eraser seems like a feature enhancement that would be worth considering.

**Comment by ralfbrown** [comment]
Use the mask manager in the left-hand panel.  You can set individual shapes (brushes, circles, etc) to combine in various ways, including having some add and some subtract.

**Comment by jenshannoschwalm** [comment]
> There may possibly be work arounds for this issue using the mask manager, but a simple eraser seems like a feature enhancement that would be worth considering.

The "simple eraser" is a big underestimation :-) Until now dt has avoided any painting-like stuff ...
