### ISSUE TITLE
Darktable does not open on macOS (not related to gatekeeper)

### ISSUE THREAD

**Issue by xxyxxyxyx1** [darktable-org/darktable#15445]
### Describe the bug

When I try to open darktable, from the terminal or Finder, nothing happens. I see a darktable process running in activity monitor, but no GUI or error messages. 

This is _not_ the Gatekeeper/quarantine problem: I have disabled gatekeeper per the installation instructions. 

I have killed the darktable process, re-installed darktable, restarted the computer, etc. 

### Steps to reproduce

attempt to open darktable, by any method

### Expected behavior

open

### Logfile | Screenshot | Screencast

If I start from the terminal with debugging, it runs until I kill it with ctrl-c, but no GUI is ever displayed:
```
./darktable -d all
[dt_detect_cpu_features] Not implemented for this architecture.
[dt_detect_cpu_features] Please contribute a patch.
     0.0000 [dt_init] SSE2 is unavailable, some functions will be noticeably slower.
     0.0001 application_directory: /Applications/darktable.app/Contents/MacOS
     0.0001 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
     0.0002 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
     0.0002 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
     0.0002 darktable.configdir: /Users/redacted/.config/darktable
     0.0002 darktable.cachedir: /Users/redacted/.cache/darktable
     0.0003 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
     0.0003 darktable.tmpdir: /private/var/folders/h4/5ssl80dx16x4fv9ypc76przr0000gp/T
     0.0003 [memory] at startup
     0.0003 [memory] max address space (vmpeak):         unknown
            [memory] cur address space (vmsize):    408814576 kB
            [memory] max used memory   (vmhwm ):         unknown
            [memory] cur used memory   (vmrss ):        22432 kB
     0.0004 new_xdg_data_dirs: (null) 
```

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

macOS 13.6

### Describe your system?

M1 Max computer
installed darktable with `brew install --cask --no-quarantine darktable`

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by MStraeten** [comment]
how long did you wait before shutting down? The initial start can take a while ….

**Comment by xxyxxyxyx1** [comment]
The last time, I let it run for about 6 hours before I remembered to kill it.

**Comment by gsora** [comment]
Just built a version from HEAD for arm64, darktable opens and runs fine, so i'm expecting it to be fixed by the next stable release.

**Comment by MStraeten** [comment]
the official arm64 builds for 4.4.2 or 4.6.0 aren't known for not running with macOS - so the reported issue is specific for that custom install...

**Comment by gsora** [comment]
Weird that it's happening though? 

Is there something else I can do to help debug this issue?

**Comment by MStraeten** [comment]
run darktable using a debugger: lldb <path to darktable executable> to see where exactly the start fails

**Comment by victoryforce** [comment]
> Just built a version from HEAD for arm64, darktable opens and runs fine, so i'm expecting it to be fixed by the next stable release.

@gsora Can we close this issue then?

**Comment by xxyxxyxyx1** [comment]
I have installed darktable 4.6.1, and it opens properly. 
I will now close my issue, thank you for the reminder.
