### ISSUE TITLE
trashing error - could not send XXX to trash

### ISSUE THREAD

**Issue by slamer59** [darktable-org/darktable#15448]
### Describe the bug

I try to delete image to trash and getting this error. 

```
could not send XXX to trash:
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freeddesktop.portal.Desktop was not provided by any .service files

do you want to ...
```

### Steps to reproduce

1. Select images
2. got to selected images 
3. Click delete (trash) button

### Expected behavior

Should move to trash and remove from darktable

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by gi-man** [comment]
> ### Where did you install darktable from?
> darktable.org

Is this flatpak instead?

**Comment by slamer59** [comment]
Sorry, I miss this line (default answer).

**Comment by gi-man** [comment]
So is it flatpak? Yes/No

**Comment by slamer59** [comment]
Yes. it is via flatpak.

**Comment by gi-man** [comment]
@paperdigits flatpak permissions ?

**Comment by victoryforce** [comment]
This is a problem not with darktable itself, but with [the flatpak packaging](https://github.com/flatpak/flatpak/issues/5201#issuecomment-1337471997):

Quoting the answer from the above link here:

"Please install [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) and a desktop-environment-specific backend suitable for your choice of UI, such as [xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome) for GNOME Shell, [xdg-desktop-portal-kde](https://invent.kde.org/plasma/xdg-desktop-portal-kde) for KDE Plasma, or [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk) for environments that do not offer anything more specific.

Your OS distribution's packaging system should install these as a required dependency (Debian Depends, RPM Requires,etc.) or a recommended dependency (Debian Recommends, etc.) when you install Flatpak. If it does not, please report this to your OS distribution as a bug."

**Comment by victoryforce** [comment]
Since this is definitely a problem that has nothing to do with the darktable code and is beyond the control of the darktable developers, I am closing this issue.
