### ISSUE TITLE
I'd like to suggest a new feature. If it is possible to create a new module "overlay", for the possibility of insert an image or a overlay picture on a raw picture. I think is going to be useful create this module with blend options. 

### ISSUE THREAD

**Issue by enrikmonteiro** [darktable-org/darktable#15447]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by TurboGit** [comment]
> btw: darktable is a raw processor, not an image editor like gimp

Sure but people use watermark module to do that... Maybe a dedicated module without the need to mess with watermark could be a nice addition.

**Comment by TurboGit** [comment]
A PR is ready to support this, see #15465.
