### ISSUE TITLE
RFC Thoughts/ideas about the internal darkroom image cache

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#15450]
Initially #15084 and now #15436 have made me look at the image cache and think about what improvements could be made there to potentially make ui interactions more smooth and/or faster. The main thing those PRs achieve is that the calculated image(s) is(/are) no longer always shown screen-filling but can be repositioned and scaled to fit the changed viewport if the user zoomed or panned around.

It is however still the case that any such action (as well as changes to module parameters and some other toggles) triggers a complete recalculation of the center screen (and, if needed, the top-left miniature in the navigator widget) for the current position, zoom and size. In some cases the finished recalculation will give exactly the same result, besides a sub-pixel shift, as what was already shown based on the previous image. For example if the size of the center view is reduced (while a fixed zoom level is active), for example by toggling color assessment mode, or if we zoom in from 100% to 200% or higher (which will just take the 100% image and shows it with 2x, 4x, 8 and 16x larger blocks of pixels). It could even be that the recalculated image is _less_ useful. If a screen filling 100% image is shown and we zoom in to 400%, we could pan around quite a bit with full resolution before reaching the edges of the previous, already fully calculated, image, but once the first recalculated image arrives, that contains just the smaller area immediately after zooming, we could actually see a drop in resolution for the part we are at that moment looking at (it will be temporarily based on zooming the miniature image) until a second recalculation is triggered and completes for the area we are now seeing.

What is now also more obvious, since the screen gets more frequently updated as each recalculated image arrives, rather than continuing to show the scaled up and repositioned miniature as was happening before, is that when we start moving, an image is immediately requested that is just a few pixels different from what we already have. By the time it arrives, we have likely moved much further and the update is practically useless/unnoticeable and immediately a new one is requested.

These observations suggest the following "obvious" ideas for improvement:
- rather than looking in the cache for an image with the _exact_ size we _need_ right now, see if it has one that covers at least that area, but maybe more.
- when we find an image with the same module etc parameters, but that is slightly to small, rather than requesting the same thing but a little moved, calculate a larger area (in the direction of movement) so that it is more likely to be sufficient even when the move completes, or otherwise at least gives a more useful intermediate step.
- more wild (and unrealistic) instead of recalculating parts of the image we already _have_, only calculate a small additional strip that's needed to the side and then merge them. A little like tiling. Would probably have to be done for each step in the pipe and would probably require us being able to use part of a too large cached image in a previous step in the pipe to be effective. Might have been possible if this was done from the outset, but rearchitecting this now... no.
- go the whole vkdt way and always calculate the full image at 100%. Yes, heats up the room nicely in winter, but also means we'd only need max 1 pipe instead of 3... And for those 4k monitors we'd be doing a large chunk of this work anyway. People would want to hide this behind a toggle in preferences :-)

All of these would require that the size, position and zoom is stored in the cache rather than just taken into account in the hash calculation as it is now. Because that only allows finding the image if you know the coordinates you are looking for beforehand.

Additionally we would then realise that if we store images in the cache with coordinates relative to the original RAW, then there is really no difference between a cropped an uncropped image (unless the cropped area is overwritten later in the pipe, for example by a border). But currently whenever a non-history toggle is flipped (i.e. one that doesn't affect the hash of the image but requires some of the pipe to be reprocessed), like color picker activation or "display mask", or even focusing a module like retouch or liquify, that wants to (un)hide the crop (the crop module itself also), part of the cache is wiped because it cannot be just reused. But then when that toggle is switched _back_, we now have to recalculate the image that we had previously. It seems that a scheme should be possible that dictates pipe processing without throwing away useful data. This sounds like a much more invasive undertaking not the least of which would be identifying _all_ the corner cases that need to be handled correctly and then _testing_ if they are not broken. But often it turns out that if fragile workarounds are needed for a shortcoming of the architecture, that then fixing that architecture can lead to a lot more stability, less complexity and sometimes even performance (or responsiveness) improvements. And easier understandable (and therefore maintainable) code. 

I'd like some feedback on these ideas. None of them are "required". None of them would lead to more functionality, although more maintainable code makes it easier to implement changes or makes it take less effort so that more time, and motivation, is left over for yet more improvements (not just functionality but also optimisations). At best, this could make the UI more responsive. So those that already have top of the line GPUs probably care less. They might be able to work more fluidly with modules set to extreme settings, but other than that this will not affect them much. Others might really like being able to use dt on aging laptops longer. Or on smaller laptops without discrete gpus. Or they might feel that buying a 4K monitor causes less of a slowdown.

Feedback please. @TurboGit @jenshannoschwalm (as the cache specialist; if there's anybody else I should @?) Does anything here sound like it is unachievable? Definitely not worth it? Likely to cause new minor annoyances that people will always hate more than the ones they've grown used to and fond of over the years? Please let me know before I waste tons of time on this. Rather than something else you feel needs dt's limited "resources" more. Thanks!

Oh, if someone wants to cross-post to pixls, please do.

**Comment by ralfbrown** [comment]
Separating the viewport settings from the processing settings had occurred to me quite some time ago, so I'm definitely in favor of adding that to the cache handling.  My thought at the time was to have a base entry in the cache corresponding to the processing parameters, and associate each cached viewport setting with the base entry (via linked list, subsidiary hash table, or the like).

Basing the recalculation viewport on extrapolated movements would definitely be a good thing, and shouldn't be invasive in terms of code changes.  Unlike recalculating strips and merging with existing cache entries....  But the latter could result in massive speedups while panning if done effectively.

**Comment by dterrahe** [comment]
> had occurred to me quite some time ago

I always left the cache to "those wizards" because it really requires a deep dive to understand what's going on, so I couldn't remember if you had worked on it. You're in your busy season now, aren't you?

> shouldn't be invasive in terms of code changes

Not once the cache allows finding a larger-than-needed available area. Otherwise it would be easy to generate, but would not be found again on the next small move.

> the latter could result in massive speedups while panning

Agreed, but people don't seem to care about panning in low-res at all, so the payoff would be small compared to all the work (and headaches).

**Comment by jenshannoschwalm** [comment]
I am not sure we talk about the same cache. We have some image `dt_image_t` caching and we have the `iop cache`. That doesn't hold images but output data for a) a hash reflecting parameters including masks from all modules prior to the one in question and b) the full region of interest.

 

> * rather than looking in the cache for an image with the _exact_ size we _need_ right now, see if it has one that covers at least that area, but maybe more.
> 
> * when we find an image with the same module etc parameters, but that is slightly to small, rather than requesting the same thing but a little moved, calculate a larger area (in the direction of movement) so that it is more likely to be sufficient even when the move completes, or otherwise at least gives a more useful intermediate step.
> 

For me it would be *obvious* to change the way we do the roi_handling. Currently we use some "exact match" for required output size and location, the idea behind is "only do exactly what is required".

I had some very interesting sessions when designing highlights and raw cacorrection to use full data instead of minimal roi. More processing just once! The obvious thing for me would be to 
1. request the pixelpipe to process a **slightly expanded and locked to certain displacement steps** (for example the roi positions could always start at a pos&63 location and be of size+128)
2. when painting to darkroom we know what we used to calc the expanded roi and can take what really is required.
 
That wouldn't fight with iop caching in any way and would certainly increase hit rate if we slightly move the selected area.
 


> All of these would require that the size, position and zoom is stored in the cache rather than just taken into account in the hash calculation as it is now. Because that only allows finding the image if you know the coordinates you are looking for beforehand.

That's not correct, explained above.


> It is however still the case that any such action (as well as changes to module parameters and some other toggles) triggers a complete recalculation of the center screen (and, if needed, the top-left miniature in the navigator widget) for the current position, zoom and size.

In a way. But note and that's exactly what the iop cache is for, while changing a parameter in a module we have a different hash as explained above. The big thing for calculating pixelpipe is, very likely there is a cacheline having available the input data for the changed module (watch via -d pipe and look for HIT) and we effectively only process from the changed module.

**Comment by dterrahe** [comment]
> the `iop cache`

That's the one. I think :-) `dt_dev_pixelpipe_cache_t`. I had assumed this was shared between the pipes, but now looking into it, maybe it isn't. Which could be another optimisation for those that use the second preview window. Wouldn't improve things _now_ but if changes are made to use any large enough 100% scaled result then maybe the "center" and "preview2" pipe could contain useable data for eachother (presumably they need to use the same display profile; maybe there's other things that will always cause hash differences). When you say "b) the full region of interest" you mean the calculated (intermediate) image data, right? When requesting for display, this is copied and then later during expose fed into a cairo surface. Only the one coming out of the end of the pipe, of course.

> a hash reflecting parameters including masks from all modules prior to the one in question

`dt_dev_pixelpipe_cache_hash` adds the roi data to the hash. I haven't seen it getting stored separately. May have missed that?

> 1. request the pixelpipe to process a **slightly expanded and locked to certain displacement steps**

Basically the user can be in one of two "modes":
a. they are tweaking module parameters (even enabling/disabling). The image dimensions don't change (unless crop/rotate etc). We may be generating a lot of slightly different images, but generating a "larger than needed" image would be a waste because never used.
b. they are zooming/panning to admire the results. The pipe hash won't change for a while, but now the dimensions/locations do. We may by some smart logic be able to deduce in which direction we are moving and move/expand the roi that way. That would mean we might need to generate as many images as the bigger one could be sufficient for a while (so there's no need to build in a delay to avoid small moves).

Consider the following concrete scenario:
100% zoom; square centered on image, say pixels 2000-4000 horizontal and 1000-3000 vertical.
Change zoom to 200%. 2500-3500x1500-2500. We can reuse the result from above because 200% just uses 100% and scales it up by 1<<closeup and the area we need is contained in the previous one.
Move north-west a little (2250-3250x1250-2250) cache should still be good, but how can I predict which coordinates it is stored at? But if the roi is stored in the cache I can just check all the images with the same pipe has and check if the roi covers my needs.

> In a way.

What I meant to say is images get generated for two kinds of reasons; roi changes and pipe hash changes. The second will always need to be calculated (if not in cache yet). May whole point in this discussion is that the previous one might not be necessary. 

3 reasons really, changes that don't influence pipe or roi but still invalidate data. If we could have a better/smarter/more complex hash, we _might_ be able to cover this without throwing away results that might become valid again in future.

**Comment by jenshannoschwalm** [comment]
@dterrahe after having 4.6 we might do some video talk about this "caching thing". Any idea on time&date?

I have already - and again - looked deeper into the pipecache code and as you said, there is certainly room for improvement. The most important thing - so it seems to me - would be to remove the roi from the hash and keep is seperately in the caching struct. That would allow a 1) test for validity and 2) take what is desired strategy. Any ideas on this.
