### ISSUE TITLE
Cannot upgrade the data base

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#15458]
### Describe the bug

I built Version 4.5.0-957-g37b57020ff and when starting dt, the upgrade database popup appears: 

![grafik](https://github.com/darktable-org/darktable/assets/49004103/a41ffab3-42c5-4949-8818-e2cbbc55bf55)

but then no dt fired up, so I started the console and get the following output got thrown to me

```
$ darktable -d sql
     0.0382 [init sql] library: /home/gerber/.config/darktable/library.db, data: /home/gerber/.config/darktable/data.db
     9.1649 [init] can't drop legacy_presets
     9.1650 [init]   no such table: legacy_presets
     9.1650 [init] database `library.db' couldn't be upgraded from version 45 to 46. aborting
     9.1652 ERROR : cannot open database
```

It looks like commit 2a1447cc91 introduced this issue. so may I ping you @TurboGit ? ;-)

I asked on IRC and looks like many do not have this issue...
My own laptop also works fine, so I am lost, what I could do...

### Steps to reproduce

see above

### Expected behavior

upgrade db as it worked well in the past....

### Commit

2a1447cc91

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0-915-g2a1447cc91 and newer

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

* darktable version : ~
* OS                : Linux - kernel 6.5.7-gentoo
* Distro            : Gentoo Base System release 2.14
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-535.113.01
* OpenCL installed  : Yes (opencl-headers-2023.04.17)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.8-r2
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.38
* gcc               : 13.2.1_p20230826
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

see above

**Comment by AxelG-DE** [comment]
As @gi-man asked me: my sqlite version is dev-db/sqlite-3.43.2

**Comment by AxelG-DE** [comment]
fwiw: I have deleted my library.db on 25th September and imported my picture folder at that day to a fresh library.db. Is there a chance, that this is related?

**Comment by wpferguson** [comment]
One user of my weekly builds just reported an issue upgrading the database with the weekly build, https://discuss.pixls.us/t/darktable-windows-insider-program-10-22/40058/2
