### ISSUE TITLE
Sinarback eVolution 75H .sti files

### ISSUE THREAD

**Issue by robert-olding** [darktable-org/darktable#15466]
Sinar will no longer be making digital backs or software.  They are going to concentrate on cameras and are going to support Phase One digital back and Capture One.  Sinar's software only supports up to macOS 10.13.6 (High Sierra) and all my Macs are new and only support macOS 12 (Monterey) on.  I have a number of Sinar RAW files (.sti) that I'd love to be able to open.

**Comment by LebedevRI** [comment]
As it is menttioned on RPU in excruciating detail, please, please, please, don't upload random junk images.
It kind of works, but i can't begin to guess if the tomatoes are meant to be green or not:
![image](https://github.com/darktable-org/darktable/assets/88600/4d7a2a49-77f0-4ea0-9d31-d3fe8d8d53fe)

**Comment by robert-olding** [comment]
Yes, I understand it may be hard to decipher what it's supposed to look like.  But to call it junk, well let's just say that's subjective.

This is part of a series of images that I shot with a Sinar P3 camera and a Sinarback eVolution 75H.  This particular image didn't make the cut but it's something I have that doesn't include people in the shot.  It's the .sti files I have of people that I'm most interested in recovering.

Those are tomatillo's, they're green.  I'm attaching JPEGs of different items shot on the exact same surface that you can use to get a sense of what everything should look like.

Best,
Robert

![clementine](https://github.com/darktable-org/darktable/assets/148662639/968d3228-621d-462a-80f1-d2dbebe0848a)
![white-onion](https://github.com/darktable-org/darktable/assets/148662639/52897cd8-2c9e-4d39-a426-f9a6bd330ede)
![pomegranate](https://github.com/darktable-org/darktable/assets/148662639/a41ffdf0-3d57-4155-a4b5-3dacd2e449ae)

**Comment by LebedevRI** [comment]
Basic support added in b220d54d8ea6c8b8bca8c7d1b28e50cfe67838ea.
