### ISSUE TITLE
False Colour Exposure Preview [feature: new]

### ISSUE THREAD

**Issue by BAGELGENESIS** [darktable-org/darktable#15486]
(BTW, I’m new to free software dev, so please forgive netiquette mistakes I will make.)
**Is your feature request related to a problem? Please describe.**

As a user, I am frustrated when I cannot expose my image for skin tones at ~60 IRE. The issue is, that if I expose the image for the forehead by using the “Exposure” slider and the adjacent area selection in the module of the same name, it will try to average the exposure of the forehead to ~50 IRE, therefore to low. By moving the slider blindly, I can never come anywhere near where I want to expose the skin tones to.

**Describe the solution you'd like**

As a user, I want to be able to preview exposure levels of each pixel in the entire image simultaneously, such that I can accurately expose for certain areas of the image.

I would wish that the False Colour would work like in the linked thread; I got a special button in the indicator menu bar where I can see a False Colour Exposure preview of the current image in the viewscreen.

Examples:
- https://d2x313g9lpht1q.cloudfront.net/original/3X/7/b/7be03abf3011287272fd833d5c5aa83be4c7c53f.png

- https://d2x313g9lpht1q.cloudfront.net/original/3X/e/e/ee610095ff9110058b348d739300b9742961ebe9.png

The solution using LUTs is suboptimal. It would be preferable and by far more accurate, if the module were to take an available luminance value for a given pixel, such as the L component in the LAB model and place them on an IRE scale.

**Alternatives**

While I am aware of the existence of the deprecated “Zone-Tool”, I would like a special preview, hence I think that is more useful than said Zone-Tool, as it clearly shows the effects of **any** luminance altering module directly on the image.

**Sources**
- LUTs for False Colour I use: https://luts.iwltbap.com/false-color-lut/
- Thread where I got almost all information from (thx [difrkaguilar](https://discuss.pixls.us/u/difrkaguilar)): https://discuss.pixls.us/t/false-color-exposure-guide-in-darktable/35937/7
- False Colour Legend (CC BY-SA 4.0 Deed) from said thread (thx [difrkaguilar](https://discuss.pixls.us/u/difrkaguilar)): https://discuss.pixls.us/uploads/short-url/prghCR2Fwqfl3D8PMBdZmQMm0hE.zip

**Comment by dterrahe** [comment]
I would recommend that you remove your difficulty assessment from the title. It is unlikely that anyone unfamiliar with the code would be able to implement this for you and would potentially discourage those with that ability to even read your request.
