### ISSUE TITLE
A problem with Microsoft Zhuyin

### ISSUE THREAD

**Issue by Niehyi** [darktable-org/darktable#15485]
### Describe the bug

When you're using Chinese IME (Zhuyin) and want to adjust the value of module with the numeric keypad in darktable 4.4.2. darktable will crash immediately.
This happened on Win10 and Win11, but it won't happen on Linux with Chewing.
I know that there are few people using Chinese IME (Zhuyin) with darktable, and it's not a big problem for me. So if you're busy on other more important issues,  just ignore this.

### Steps to reproduce

Change to Chinese IME (Zhuyin) and adjust any  modules with numeric keypad.

### Where did you install darktable from?

darktable.org

### darktable version

darktable 4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Win10 and Win 11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nv4060ti 940m and 1650

**Comment by TurboGit** [comment]
> So if you're busy on other more important issues, just ignore this.

Well in fact the issue is to have a dev on darktable:
- Working on Windows
- and Using the UI in Chinese
- and Using Zhuyin

You bet... The final result is the empty set :)

**Comment by TurboGit** [comment]
@wpferguson : Do you think you can have a look? And or know someone who could have a look at this?

**Comment by wpferguson** [comment]
I can try...

**Comment by dterrahe** [comment]
Are you talking about right-clicking a slider and then typing a value in the pop-up that appears?

Quite a few changes/fixes were made there recently that are not included in 4.4.2. Could you please try if the weekly snapshot provided by @wpferguson still has the same issue? As usual, be careful when trying a snapshot because running it on your normal database and images will prevent you from returning to 4.4.2.

**Comment by HSUfineprint** [comment]
I can confirm this issue. If I accidentally type Chinese in that fields, darktable will crash.

darktable: 4.5.0+912~g4558ba7f77
OS: windows 10 22H2

**Comment by dterrahe** [comment]
This was autoclosed when #15500 was merged. If you find that the problem isn't (completely) solved in the next weekly that includes it, please reopen.
