### ISSUE TITLE
Keyword substitution for 35mm equiv focal length

### ISSUE THREAD

**Issue by smartintec** [darktable-org/darktable#15481]
When ckecking the nightly build 4.5.0+790~gddc2a5ba2e with the calculated 35mm equiv focal length, 
I was missing the opportunity for keyword substitution like $(EXIF_FOCAL_LENGTH) for that, so it can be used for image information (below thumbnail/when hovering) in lighttable.

I like the idea because it makes pictures from full-frame and crop-sensor cameras more comparable.

**Comment by victoryforce** [comment]
Resolved by #15459.
