### ISSUE TITLE
Sigma FPL Tethered Shooting

### ISSUE THREAD

**Issue by Damani2** [darktable-org/darktable#15490]
### Describe the bug

![image](https://github.com/darktable-org/darktable/assets/80477750/3d1108e5-3e1e-4542-8403-37fa5acd933d)

I’m having a hard time getting darktable to connect to my sigma FPL. I looked at the gphotolib compatibility and it said I should be able to connect. I used Zadig to change the USB driver and that lets me see the camera and mount it in darktable. But when I tried to adjust controls nothing works. Is there a way to update gphotolib separately or should I have the latest with darktable 4.4.2?

### Steps to reproduce

1. Connect Sigma FPL camera to computer using a USB cable.
2. Launch Darktable and wait for it to detect and mount your camera.
3. Once the camera is mounted, attempt to adjust camera controls or perform any other camera-related operations within Darktable.
4. Fail

### Expected behavior

let me control the camera and take a picture

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

windows 11 pro

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by gi-man** [comment]
Under windows, you might need to follow this instructions. I've never tried this, so I can't help. 

https://www.darktable.org/about/faq/#faq-tethering

**Comment by kmilos** [comment]
Please upload a raw sample to https://raw.pixls.us/ nonetheless.

**Comment by kmilos** [comment]
Also, it looks like this was added to libgphoto2 [only in the latest 2.5.31 version that was released a month ago](https://github.com/gphoto/libgphoto2/blob/master/NEWS).

**Comment by Damani2** [comment]
Is there a way for me to update libgphoto2 independent of Darktable?

**Comment by ptilopteri** [comment]
libgphoto2 is not part of darktable.  you would have to determine what windows package includes libgphoto2 and upgrade that.

**Comment by ptilopteri** [comment]
perhaps:  http://www.gphoto.org/

according to google

**Comment by kmilos** [comment]
@ptilopteri There is a known (i.e. more suitable) source for a newer libgphoto2 package for Windows...

But I would prefer a contribution of that sample first.

**Comment by Damani2** [comment]
> @ptilopteri There is a known (i.e. more suitable) source for a newer libgphoto2 package for Windows...
> 
> But I would prefer a contribution of that sample first.

I've uploaded a sample image today. Hopefully it's satisfactory. The Sigma FPL rights .DNG raw files. I truthfully still don't quite understand the utility of reviewing this sample data. I found information about updating libgphoto2 via MSYS2 which I'm attempting now.

**Comment by kmilos** [comment]
Thank you very much for the sample @LebedevRI 

One thing to keep in mind - it might not be enough to just update the package through MSYS2 pacman. If you installed darktable in `C:\Program Files\darktable`, you'll need to replace libgphoto2.dll in `C:\Program Files\darktable\bin`, and also replace (or add) all the related *.dll in `C:\Program Files\darktable\lib`. Then also double check the CAMLIBS and IOLIBS environment variables once you do that to make sure they're pointing to the desired directories.

**Comment by Damani2** [comment]
Thank you for this. I tried this but for some reason I can't get it to work unfortunately. I can run gphoto from msys2 but I can't get the updated libraries to work in Darktable. I supposed I have to just wait for the proper updated Darktable release. 

> Thank you very much for the sample @LebedevRI
> 
> One thing to keep in mind - it might not be enough to just update the package through MSYS2 pacman. If you installed darktable in `C:\Program Files\darktable`, you'll need to manually replace libgphoto2-6.dll and libgphoto2_port-12.dll in `C:\Program Files\darktable\bin`, and also replace (or add under new version subdirectories) all the libghoto2 and libgphoto2_port related *.dll in `C:\Program Files\darktable\lib`. Then also double check the CAMLIBS and IOLIBS environment variables once you do that to make sure they're pointing to the desired directories.

**Comment by Damani2** [comment]
Ok apologies as I'm new to github but I have another discovery of note. The Sigma FPL comes with it's own SDK and that works specifically with the MTP USB driver. I'd used Zadig to switch to a more generic driver that Darktable liked before I messed with the libraries and .DLL files. Now it doesn't recognize the camera at all. Looking forward to seeing the FPL support added to Darktable.

**Comment by kmilos** [comment]
Which msys2 package did you actually try to use, as there are multiple flavours? Darktable builds w/ ucrt64...

@wpferguson Can we test and bump libgphoto2 for the next release please?

**Comment by wpferguson** [comment]
> Can we test and bump libgphoto2 for the next release please?

I was just about to ask if we needed to.  I'll bump starting with  this weekly

**Comment by Damani2** [comment]
> Which msys2 package did you actually try to use, as there are multiple flavours? Darktable builds w/ ucrt64...
> 
> @wpferguson Can we test and bump libgphoto2 for the next release please?

I think I used Ming? Sorry not very experienced with the coding/compiling. With this being tested in a nightly build could it make it into the upcoming December release?

**Comment by kmilos** [comment]
> With this being tested in a nightly build could it make it into the upcoming December release?

That's the plan indeed.

**Comment by wpferguson** [comment]
@kmilos  libgphoto2 is already 2.5.31-2

**Comment by kmilos** [comment]
> libgphoto2 is already 2.5.31-2

For your weekly builds? Great.

It wasn't the case for 4.4.2, and the nightly build environment is still 3 months old AFAIK...

**Comment by victoryforce** [comment]
> > libgphoto2 is already 2.5.31-2
> 
> For your weekly builds? Great.
> 
> It wasn't the case for 4.4.2,

Sure, because libgphoto2 2.5.31 was released on September 2nd.

> and the nightly build environment is still 3 months old AFAIK...

No, in the nightly build environment, the libgphoto2 package is also version 2.5.31-2.

**Comment by kmilos** [comment]
> in the nightly build environment, the libgphoto2 package is also version 2.5.31-2

Ok, the msys2 installer got updated on Oct 26th, after the issue was opened and I last checked the package in the nightly build.

So both the nightly and weekly builds now provide a way to test this.

**Comment by Damani2** [comment]
I still haven't been able to get this to work tethered. I don't think gphoto is the issue. What should I try next?

**Comment by Damani2** [comment]
ok I have an update. I actually got this to work on the latest nightly build. The issue I have now is that I can't manually control settings.

**Comment by Damani2** [comment]
Sorry I also don't have all settings.  I can trigger a capture, but the camera doesn't respect shutter and aperture settings I set. And iso didn't appear at all. Does this sound like a permissions issue?

**Comment by kmilos** [comment]
> I actually got this to work on the latest nightly build.

Glad to hear.

This is now the time to take this discussion back over to https://discuss.pixls.us/tag/darktable, as this place is for actual bugs and development, not end user support.
