### ISSUE TITLE
purge non existing images from the database

### ISSUE THREAD

**Issue by ddittmar** [darktable-org/darktable#15493]
**Describe the solution you'd like**

I like to purge non existing images from the database with a button in the UI

**Alternatives**

If managed to clean the database from within the flatpak:

1. `flatpak run --command=sh org.darktable.Darktable`
2. and then in flatpak: `/app/share/darktable/tools/purge_non_existing_images.sh -c ~/.var/app/org.darktable.Darktable/config/darktable/ --purge`

... but that's kind a cumbersome and a technical solution.

**Comment by Nilvus** [comment]
This had already been asked (good to search and would have been better so to ask to reopen this old issue): #12554

Remember just 2 things:
- darktable is made freely on their free time by a small team of developers. So this will be done only if one want to do that and spent time on it
- flatpak packages are not supported by darktable team

**Comment by ddittmar** [comment]
I have implemented this feature with a Lua script: https://github.com/darktable-org/lua-scripts/pull/435

**Comment by victoryforce** [comment]
> I have implemented this feature with a Lua script: [darktable-org/lua-scripts#435](https://github.com/darktable-org/lua-scripts/pull/435)

Great! Thanks for the contribution! So I guess we can close this issue?

**Comment by ddittmar** [comment]
> Great! Thanks for the contribution! So I guess we can close this issue?

Yes :+1:
