### ISSUE TITLE
Incorrect DateTimeOriginal values

### ISSUE THREAD

**Issue by mingos777** [darktable-org/darktable#15494]
### Describe the bug

For images processed with Photos Exif Editor, Darktable fails to read DateTimeOriginal correctly and always rounds it down to the first day of the month. This does not happen with the original files, just the ones exported with Photos Exif Editor.
The incorrect value is shown in Darktable's image information tab and the image tooltip. It is also saved incorrectly to exported files and the xmp file.
E.g. if the original date is "2023:10:06 12:34:56", Darktable will change it to "2023:10:01 00:00:00".

### Steps to reproduce

1. Open an image (raw or jpeg, doesn't matter) in Photos Exif Editor
2. Save with any edit (make sure the create date is set; if not, set it)
3. Import in Darktable
4. exif.DateTimeOriginal value is invalid, both displayed and stored in the xmp file.

### Expected behavior

DateTimeOriginal should be correct.

### Logfile | Screenshot | Screencast

Files:

* NZ7_ORIG.NEF - original image
* NZ7_EDIT.NEF - edited with Photos Exif Tool (added manual lens info, date unchanged)
* NZ7_EDIT.jpg - edited file exported using Darktable
* NZ7_ORIG.NEF.xmp, NZ7_EDIT.NEF.xmp - XMP files for original and edited NEFs

Here's the relevant output:
```
mingos@Dominiks-Mac-mini Desktop % exiv2 -pa NZ7_ORIG.NEF | grep 2023
Exif.Image.DateTime                          Ascii      20  2023:10:24 16:28:26
Exif.Photo.DateTimeOriginal                  Ascii      20  2023:10:24 16:28:26
Exif.Photo.DateTimeDigitized                 Ascii      20  2023:10:24 16:28:26
Exif.Image.DateTimeOriginal                  Ascii      20  2023:10:24 16:28:26
Xmp.xmp.CreateDate                           XmpText    22  2023-10-24T16:28:26.76
mingos@Dominiks-Mac-mini Desktop % exiv2 -pa NZ7_EDIT.NEF | grep 2023
Exif.Image.DateTime                          Ascii      20  2023:10:24 16:28:26
Exif.Photo.DateTimeOriginal                  Ascii      20  2023:10:24 16:28:26
Exif.Photo.DateTimeDigitized                 Ascii      20  2023:10:24 16:28:26
Exif.Image.DateTimeOriginal                  Ascii      20  2023:10:24 16:28:26
Iptc.Application2.DateCreated                Date        8  2023-10-24
Xmp.xmp.CreateDate                           XmpText    22  2023-10-24T16:28:26.76
mingos@Dominiks-Mac-mini Desktop % exiv2 -pa NZ7_EDIT.jpg | grep 2023
Exif.Image.DateTime                          Ascii      20  2023:10:26 12:57:44
Exif.Photo.DateTimeOriginal                  Ascii      20  2023:10:01 00:00:00
Exif.Photo.DateTimeDigitized                 Ascii      20  2023:10:24 16:28:26
Exif.Image.DateTimeOriginal                  Ascii      20  2023:10:01 00:00:00
Iptc.Application2.DateCreated                Date        8  2023-10-24
Xmp.exif.DateTimeOriginal                    XmpText    23  2023:10:01 00:00:00.000
Xmp.xmp.CreateDate                           XmpText    22  2023-10-24T16:28:26.76
mingos@Dominiks-Mac-mini Desktop % cat NZ7_ORIG.NEF.xmp | grep 2023
   exif:DateTimeOriginal="2023:10:24 16:28:26.760"
mingos@Dominiks-Mac-mini Desktop % cat NZ7_EDIT.NEF.xmp | grep 2023
   exif:DateTimeOriginal="2023:10:01 00:00:00.000"
```

I'm happy to provide the files in question if needed, as well as the full output of `exiv2`.

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

14.0 (23A344)

### Describe your system?

Tried on a Mac Mini M2 Pro and Macbook Pro 2019 (Intel i5) (both running the same OS version)

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

* This happened in previous Darktable versions as well, 4.2 for sure, possibly earlier too.
* This happens regardless of the original file type. I tried with .NEF files from three different Nikon models (D90, Z50 and Z7) as well as with a jpeg file from a scanner. While this looks like an issue with Photos Exif Editor, both `exiv2` (v0.28.0) and Flickr show correct values, only Darktable messes them up.
* Edit history is not changed (fresh import).
* No lua scripts.

**Comment by gi-man** [comment]
Can you provide the .NEF (original and modified)? Does the photo exif editor apply or modify GPS/Geotags/time offset?

**Comment by mingos777** [comment]
Files: https://drive.google.com/drive/folders/18cID9mXeMlADkdnmoU7qyUCWb441hwsT?usp=sharing

As far as I can tell, Photos Exif Editor does not apply a time offset, or at least it is not an option I can choose in the date set dialog. However, in the output edited file, when opened with xxd or vim, the original time offset of +02:00 is visible so it looks like the app doesn't modify it.

As for GPS, there is an option to set it but I don't use it (unmodified fields are not altered, at least the app claims so).

I don't see an option to set Geotags in the app's UI.

**Comment by gi-man** [comment]
The files you share are different than the ones from the Issue, correct? I'm getting different dates.

I think the problem starts here with this tag that Photo Exif Editor adds:

Iptc.Application2.DateCreated                Date        8  2023-10-24

From my analysis:
Normally, dt uses first XMP, then IPTC and then EXIF. The XMP.CreateDate is not currently searched for, so it is not used. When the file is the original.nef, there is no IPTC, so dt uses the EXIF. When then .NEF is edited with the additional IPTC, dt reads the IPTC and uses it in the database as the datetime value. This is then used during the .jpg export.

But, there is an issue since it seem like dt is only capturing the YYYYMM and not the DD (2023-10-01 in your example). In the files you shared, it yields 2022-12-01 instead of 2022-12-09. 

![image](https://github.com/darktable-org/darktable/assets/97920861/22318448-3fbc-4685-86b3-958a7f40cef7)

**Comment by mingos777** [comment]
The files are different because I don't currently have access to my home computer and I created another set of files from a random photo from my collection. The issue is the same though.

So, if I understand your explanation right, DT ignores `Xmp.xmp.CreateDate`, relies on `Iptc.Application2.DateCreated` instead and has a problem parsing it correctly?

The website https://exiv2.org/iptc.html holds this description for `Iptc.Application2.DateCreated`:

>Represented in the form CCYYMMDD to designate the date the intellectual content of the object data was created rather than the date of the creation of the physical representation. Follows ISO 8601 standard.

So, irrespective of whether DT parses the date correctly or not, it sounds like Photos Exif Editor writes a date format that is technically incorrect.

**Comment by gi-man** [comment]
On the cellphone most of today. 

Xmp.createdate is not setup to be read instead of being ignored. Each one of the tags needs to be setup. 

I think the IPTC has the correct format. I think there is an error in the string reading, but I was too sleepy to look further into it.

**Comment by gi-man** [comment]
So here is the problem: `YYYY-MM-DD` Exiv2 added the ability to use that format. Exiftool changes it to `YYYY:MM:DD`

darktable was reading that string correctly but the database is expecting `YYYY:MM:DD`. I have regex to detect the `YYYY-MM-DD` and overwrite the `-` with `:` I will do a PR this week once I stress test it some more.

**Comment by kmilos** [comment]
> darktable was reading that string correctly but the database is expecting `YYYY:MM:DD`. I have regex to detect the `YYYY-MM-DD` and overwrite the `-` with `:` I will do a PR this week once I stress test it some more.

Note that we already had this for YYYYMMDD:

https://github.com/darktable-org/darktable/blob/815b313fbcc36be6f150ed95e314e8c1f64230b3/src/common/exif.cc#L727-L733

Which matches the length 8 reported by exiv2. Where dos the YYYY-MM-DD come from then? It is not length 8...
```
Iptc.Application2.DateCreated                Date        8  2023-10-24
```

**Comment by kmilos** [comment]
Turns out there is no need for all this extra pre-processing for `Iptc.Application2.DateCreated` (and `Iptc.Application2.TimeCreated`) as exiv2 should already return ISO 8601 compliant strings, so one should focus on `dt_datetime_exif_to_img()`.
