### ISSUE TITLE
Panasonic DC-ZS200D is in rawspeed cameras.xml but raw format not supported

### ISSUE THREAD

**Issue by robosicotte** [darktable-org/darktable#15499]
### Describe the bug

Darktable cannot open a raw file taken on my DC-ZS200D yet this is a supported camera
UPDATE: Attempted SELF-FIX 

Appended <Alias>DC-ZS200D</Alias> to <Camera make="Panasonic" model="DC-TZ202" mode="3:2">in cameras.xml
and it works fine now.
Section of XML Edited:
```
<Camera make="Panasonic" model="DC-TZ202" mode="3:2">
		<ID make="Panasonic" model="DC-TZ202">Panasonic DC-ZS200</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="142" white="4095"/>
		<Aliases>
			<Alias>DC-TZ200</Alias>
			<Alias>DC-ZS200</Alias>
			<!--LINE ADDED-->
			<Alias>DC-ZS200D</Alias>
		</Aliases>

``` 
Note that the DC-ZS200D is a 3:2 sensor camera and the default mode appears to be "3:2"
Seems to work for raw files
### Steps to reproduce

1. Open folder in Darktable and import raw files from folder using "add to library"
2. Thumbnails show up but cannot be made fullscreen by clicking on them
3. I checked cameras.xml and do have the latest version

### Expected behavior

open the raw file successfully

### Logfile | Screenshot | Screencast
Logfile:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13183156/darktable-log.txt)
Note:
RawSpeed:Unable to find camera in database: 'Panasonic' 'DC-ZS200D' '3:2'

Screenshot: First image from
![darktablescreenshot1](https://github.com/darktable-org/darktable/assets/43213924/62a647a9-0bb9-440f-9082-cee4484ad4cf)

### Where did you install darktable from?

distro packaging

### darktable version

4.5.0+991~g16fd5b7b95

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Are you using OpenCL GPU in darktable?

Yes

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This only is a bug with the RW2 files.
JPG files work fine.

**Comment by ptilopteri** [comment]
The DC-ZS200 is listed as supported but there is no DC-ZS200D listed.

have you provided the requested images for support to be added?

see https://raw.pixls.us/

**Comment by robosicotte** [comment]
The images were provided previously by someone else

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/14963

Please search before opening new issues.

This has been added already to raswspeed, just not propagated to dt yet.
