### ISSUE TITLE
Nikon Z8<Enter your camera name here>

### ISSUE THREAD

**Issue by NickDolfin** [darktable-org/darktable#15502]
I just installed the latest version 4.4.2 and wanted to start tethering.

I tells me that there is no camera support.

Any idea on how to resolve this?

**Comment by kmilos** [comment]
Like https://github.com/darktable-org/darktable/issues/15490, this depends on [most recent libgphoto2 2.5.31](http://www.gphoto.org/news/)

**Comment by NickDolfin** [comment]
Many thanks for this reply.

Unfortunately I am not able to compile the latest libgphoto and install it into the latest darktable program. 
You see, I'm a photographer - not a programmer.

Perhaps someone can update the 4.4.2 version?

**Comment by Nilvus** [comment]
Updating a release is not something fast to do. So you will probably have to wait 4.6 release in december. As it do not depend to darktable developers team (packaging is not by darktable developers team), I close that issue.

**Comment by Nilvus** [comment]
Or update libgphoto2 separately (how to do that, depend on your OS). If you need help for that, pixls.us forum is there for any help about darktable or related. This place is especially for updates needed on darktable code source.
