### ISSUE TITLE
darktable segfault

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15508]
### Describe the bug

I was playing with the _sigmoid_ module's new _primaries_ controls using an SDR sRGB colour wheel image. I made a snapshot and was comparing the effects; I think the crash happened when I clicked on the snapshot to turn on the comparison. I had been dragging the sliders around quite wildly, so I'm not exactly sure.

### Steps to reproduce

I have been unable to reproduce the crash.

### Logfile | Screenshot | Screencast

Copying the dump from the console, as it has a bit of processing history at the beginning, maybe it is of some use.
[crashlog.txt](https://github.com/darktable-org/darktable/files/13195941/crashlog.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+1014~g5f25f79812

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Describe your system?

X11, 64 GB, NVidia 1060/6 GB, nvidia driver v525.125.06.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6 GB, nvidia driver v525.125.06

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Built using:
./build.sh --prefix /home/kofa/darktable-master --build-type Release --install -DCUSTOM_CFLAGS=ON -DCMAKE_CXX_FLAGS="-O3 -march=native" -DCMAKE_C_FLAGS="-O3 -march=native"
GCC 12.3.0

**Comment by dterrahe** [comment]
I've been trying to reproduce, but so far unsuccessful. I _have_ messed around with buffer memory allocation recently (135d5a62d99952a6b11bbb72f7cb635e107f2a7f), so wasn't too surprised about crash reports, but had hoped that I'd fixed them in 5a678cd8505394008165bbc7391c4438c3d0e169 . Are you sure your crash happened with 4.5.0+1014~g5f25f79812 and not a (slightly) older one? As always, concrete steps to reproduce would be really helpful, but I understand that sometimes crashes are elusive and you should still report them!

**Comment by kofa73** [comment]
Yes, I'm certain it was that version. I understand it's hard to reproduce; I'll let you know if it occurs again.
Shall I build now with RelWithDebugInfo, does it provide a more useful stack trace?

**Comment by kurld** [comment]
I can reproduce it every time on g5f25f79812.

Build from Arch AUR darktable-git 4.5.0.r1014.g5f25f79812-1
Arch Linux, RTX 2070, 545.23.06, opencl enabled

1. Open a file in darkroom.
2. Create a snapshot
3. Change exposure value in Exposure module
4. Click on snapshot created in step 2
5. segfault

**Comment by dterrahe** [comment]
Strange. Can't reproduce on two OSes, 3 compilers, with or without OpenCL.

> Shall I build now with RelWithDebugInfo, does it provide a more useful stack trace?

Not sure. It looks like the buffer containing the generated snapshot cannot be accessed when it's about to be shown on the screen. Presumably it got released somewhere earlier, but that would not show in the trace anyway.

@kurld is that with any image? Could you post a stack trace as well please?

**Comment by kurld** [comment]
[darktable_bt_L4YCD2.txt](https://github.com/darktable-org/darktable/files/13199197/darktable_bt_L4YCD2.txt)

**Comment by kurld** [comment]
I've updated steps to reproduce in previous comment.

**Comment by dterrahe** [comment]
Now also tried to reproduce on old laptop. Still works fine for me. Mystifying.

**Comment by TurboGit** [comment]
> I can reproduce it every time on g5f25f79812.
> 
> Build from Arch AUR darktable-git 4.5.0.r1014.g5f25f79812-1 Arch Linux, RTX 2070, 545.23.06, opencl enabled
> 
>     1. Open a file in darkroom.
> 
>     2. Create a snapshot
> 
>     3. Change any value in any module
> 
>     4. Click on snapshot created in step 2
> 
>     5. segfault or goto step 3 and repeat

Cannot reproduce. I have also OpenCL with NVidia 525.125.06. @kurld : Do you reproduce without OpenCL?

**Comment by TurboGit** [comment]
BTW, the backtrace point to some routine in CAIRO, what is the version used to build dt on your side?

**Comment by dterrahe** [comment]
> the backtrace point to some routine in CAIRO

It does, but a little bit earlier is says `error: Cannot access memory at address` (in `dt_view_paint_surface`) which makes me suspect that `buf` has been freed somewhere. But maybe I'm reading that message wrong?
```
#16 0x00007fbb9435de7d in dt_view_paint_surface (cr=cr@entry=0x559436855bb0, width=width@entry=2609,
height=height@entry=1913, port=port@entry=0x559435796ec0, window=window@entry=DT_WINDOW_MAIN,
processed_width=<optimized out>, processed_height=1024, buf=0x7fba87cf2040 <error: Cannot access memory at address
0x7fba87cf2040>, buf_scale=1.83886719, buf_width=1883, buf_height=1883, buf_zoom_x=<optimized out>, buf_zoom_y=
<optimized out>) at /home/kofa/darktable/src/views/view.c:1768 
```

**Comment by TurboGit** [comment]
@dterrahe : Indeed, and looking at the code I think I have the fix, see #15530.

@kofa73 @kurld : Can you test the fix in #15530 and report if it works on your side? TIA.

**Comment by kofa73** [comment]
> BTW, the backtrace point to some routine in CAIRO, what is the version used to build dt on your side?

1.16.0

**Comment by kofa73** [comment]
> @kofa73 @kurld : Can you test the fix in #15530 and report if it works on your side? TIA.

I'll try -- but I had trouble reproducing the issue in the first place. That's the problem with mandelbugs.

**Comment by kofa73** [comment]
I was able to reproduce it with current master, but not with the PR. But then later I was also not able to reproduce it with master, despite using the _adjust - compare to snapshot - turn off snapshot - adjust - compare again - ..._ cycle until I literally got nauseous because of repeating the same operations over and over. So let's hope the fix works, but I cannot be sure.

**Comment by dterrahe** [comment]
Could it be that you first need to clear/reset the snapshot module _before_ this problem occurs?

There's no after `s->buf = NULL` after `if(s->buf) dt_free_align(s->buf);` in `_clear_snapshots`...

My bad!

**Comment by kurld** [comment]
Still crashes with [5ab8b40](https://github.com/darktable-org/darktable/pull/15530/commits/5ab8b40f49b5aee312bf6dbe1f8af52712892dbe).
Cannot reproduce anymore after [123ba23](https://github.com/darktable-org/darktable/pull/15531/commits/123ba232181dfab9d926d92909b78090ac3d7748),
