### ISSUE TITLE
RAW image only partially rendered in Lighttable

### ISSUE THREAD

**Issue by 01tot10** [darktable-org/darktable#15511]
### Describe the bug

This is a continuation of the discussion started in https://github.com/darktable-org/darktable/issues/15405#issuecomment-1766080955. 

I'm trying to visit some older B&W scans that were processed with an earlier version of Darktable.
While the small thumbnails in Lighttable show up correctly, opening the scans in Darktable results in only partially rendered images. Often times, the error message `unsupported input profile has been replaced by linear REC709 RGB` is shown.

View from Lighttable
![bug-lighttable-crop](https://github.com/darktable-org/darktable/assets/35490779/9980d780-0a61-44e5-9060-a586c5b807b3)

View from Darktable
![bug-darktable-crop](https://github.com/darktable-org/darktable/assets/35490779/02eb773d-2b70-449a-990d-1e468e3bacce)

There are no sidecar files accompanying the images, but since they are clearly edited, perhaps the version of Darktable that I was using at the time (circa ~2019) stored the edits in the database instead? Anyways, if I open up any of the scans using a fresh database (`darktable --library :memory:`) as reported [here](https://github.com/darktable-org/darktable/issues/15405#issuecomment-1770132689), the images render correctly (but without edits), which makes me think the problem has to do with backwards compatibility.

I uploaded an example file to this issue, but don't know exactly how I can share the edit history from my database?

### Steps to reproduce

1. Open the provided .DNG-file in Darktable using the edit history from my database (don't know how to share this).
2. See partially rendered image

### Expected behavior

Darktable should render the image fully (with edits)

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0~git924.06d30b47-1+10740.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

Wayland

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Here's an example [file](https://www.dropbox.com/scl/fi/4auuxamy2xafcihualhoy/2019-10-04-0019.dng?rlkey=25p136gi2lyn2k7olsbf0x5jy&dl=1).

- Can you reproduce with another darktable version(s)?
  - yes with 4.4.2-1.1+69.1
- Can you reproduce with a RAW or Jpeg or both?
  - RAW (.DNG) 
- Are the steps above reproducible with a fresh edit (i.e. after discarding history)?
  - Discarding the history makes the issue disappear, but doesn't solve the problem
- If the issue is with the output image, attach an XMP file
  - There are no XMP files
- Is the issue still present using an empty/new config-dir
  - Haven't tried
- Do you use lua scripts?
  - Not that I know of

**Comment by ptilopteri** [comment]
>> I uploaded an example file to this issue, but don't know exactly how I can share the edit history from my database?

open subject image in dt with --library :memory: and have dt write xmp file.

provide image and xmp file here.

**Comment by 01tot10** [comment]
Thanks @ptilopteri! Actually, there ARE some XMP-files dating back to 2019 that I somehow seem to have missed. Importing the image using a fresh database together with the XMP-file breaks the rendering, so the edit history is definitely the culprit. Here's an [XMP-file](https://www.dropbox.com/scl/fi/4b7fs3c9xrgzpz1y43hbb/2019-10-04-0019.dng.xmp?rlkey=dpbaqnb4s7jt3v85metg54ubv&dl=0) that goes with the .dng uploaded earlier to aid debugging.

**Comment by jenshannoschwalm** [comment]
Thanks for providing the xmp.
1. There was an active highlights module, we don't have that for monochromes any more as it doesn't make sense. So the bugfix was to make sure we don't use it :-)
2. So you also were almost right with the assumption: The history is the culprit :-)

**Comment by 01tot10** [comment]
Updating Darktable from nightly (thus, including #15513) fixed the rendering. Thanks!
