### ISSUE TITLE
LUA ERROR in script_manager : invalid escape sequence near '"dir /b/s \s'

### ISSUE THREAD

**Issue by manu-p** [darktable-org/darktable#15524]
### Describe the bug

Hi, don't know what's changed on my system, I find no LUA extensions anymore.

### Steps to reproduce

1. start dt
2. no LUA scripts are avalaible

3. Try to start dt with -d Lua
4. see error message : see below

### Expected behavior

Have LUA scripts working as before

### Logfile | Screenshot | Screencast

$ darktable -d lua
     6,6950 LUA ERROR : error loading module 'tools/script_manager' from file '/home/manu/.config/darktable/lua/tools/script_manager.lua':
	/home/manu/.config/darktable/lua/tools/script_manager.lua:516: invalid escape sequence near '"dir /b/s \s'

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3

### Are you using OpenCL GPU in darktable?

No

**Comment by manu-p** [comment]
[script_manager.lua](https://github.com/darktable-org/darktable/files/13204895/script_manager.lua.txt)

**Comment by ptilopteri** [comment]
diff of your "script_manager.lua" and the one provided by dt:

516c516
<     find_cmd = "dir /b/s \s" .. script_dir .. "\\*.lua\" | sort"
---
>     find_cmd = "dir /b/s \"" .. script_dir .. "\\*.lua\" | sort"

**Comment by ptilopteri** [comment]
the "first" thing to check when something doesn't work is the most basic, 
is it plugged in
is it typed correctly
...
