### ISSUE TITLE
Allow 0% borders in the framing module

### ISSUE THREAD

**Issue by jonasberge** [darktable-org/darktable#15528]
**Is your feature request related to a problem? Please describe.**

I'd like to have a "0%" frame on my photos, meaning there is only frame on either the top/bottom or left/right, but not on the other sides, e.g. with a square aspect ratio frame and a landscape or portrait photo. E.g. like so (ignore the grey around the photo, that is the background of Darktable):

![grafik](https://github.com/darktable-org/darktable/assets/24623262/23375852-3c45-42fd-9743-86db240b4146)

Unfortunately that's not possible, the minimum border size possible is 0.01%, which introduces a thin pixel strip on one side where I don't want to have a border, like so:

![grafik](https://github.com/darktable-org/darktable/assets/24623262/6f8721a3-4ee6-4b9e-8074-06b6e73f33a3)

With 0% the border is entirely gone.

Also, with 0.01%, sometimes the thin pixel strip is visible in darkroom, and sometimes it's not, depending on the zoom level. Either way, the export contains it.

Also, when using a "horizontal offset" of 1.0 (which should offset the image entirely to the right), there is still a thin pixel strip of border on the right side (like in the screenshot above), even though there shouldn't be.

**Describe the solution you'd like**

It would be nice if 0% borders only add border to the vertical or horizontal axis, but not the other.
It might also be good to fix the problem with a 1.0 "horizontal offset" and a thin pixel strip remaining.

**Alternatives**

**Additional context**

darktable version: master, commit `815b313fbcc36be6f150ed95e314e8c1f64230b3`

It's kinda finicky to test, under some circumstances it happens, under some it doesn't. I used export max width/height of 1080x1350.

**Comment by TurboGit** [comment]
I'll fix as part of my work on the new modules I'm proposing to do some composition. Hopefully this will be back-ported to master for 4.6.

**Comment by TurboGit** [comment]
Now fixed and two new regression tests added to cover more settings of the framing module.

**Comment by jonasberge** [comment]
@TurboGit I have compiled master today (`6e4bb81ac1a04b22c37a0a2f6621b9b822b7083c`), darktable version `darktable 4.5.0+1081~g6e4bb81ac1`, and to me there is no difference to before. I used a fresh config directory, imported a photo without any old XMP, went to the framing module and set it to 0.01% and there is still a thin pixel strip on the right. With 0% there is no border at all. Am I doing something wrong?

**Comment by TurboGit** [comment]
> With 0% there is no border at all. Am I doing something wrong?

This is what has been fixed. Previously with 0% we still had a one pixel in some zoom level and/or screen definition.

**Comment by jonasberge** [comment]
I see, thank you for the clarification!

I actually intended for this to be a feature request, to allow 0% borders which add white (or the border colour) only to the top+bottom or left+right, but not on the other sides (thus only increasing the width or the height of the export, but not both). Do you think you can reopen this feature request?

**Comment by TurboGit** [comment]
Oh I see, that's not what I had understood at all. I thought you were speaking of the bug with always a remaining 1px on right or bottom. You want the possibility of having a border even if 0% set for the border size as the aspect ratio may be different than the one of the picture!

**Comment by TurboGit** [comment]
@jonasberge : Can you test #15528? BTW, this is a far easier fix than the one put in place for the remaining 1px :)
