### ISSUE TITLE
Sony Alpha 7C II, ILCE-7CM2

### ISSUE THREAD

**Issue by VaporBear** [darktable-org/darktable#15521]
Hi,

(Apologies since I am not familiar with github)
(I searched for Issues & Pull requests for Sony ILCE-7CM2 and did not find any results.)

There are a few raw files uploaded to raw.pixls.us for ILCE-7CM2 but not by me. 
I've tried to upload my set of raw files but it has not shown up in the repo for some reason. Let me know if you need any of these uploaded:

> Sony ILCE-7CM2 Set:
> 
> (3:2) Raw Uncompressed
> (3:2) Raw Lossless Compressed (L)
> (3:2) Raw Lossless Compressed (M)
> (3:2) Raw Lossless Compressed (S)
> (3:2) Raw Compressed
> 
> (4:3) Raw Compressed
> (4:3) Raw Lossless Compressed (S)
> (4:3) Raw Lossless Compressed (M)
> (4:3) Raw Lossless Compressed (L)
> (4:3) Raw Uncompressed
> 
> (16:9) Raw Uncompressed
> (16:9) Raw Lossless Compressed (L)
> (16:9) Raw Lossless Compressed (M)
> (16:9) Raw Lossless Compressed (S)
> (16:9) Raw Compressed
> 
> (1:1) Raw Compressed
> (1:1) Raw Lossless Compressed (S)
> (1:1) Raw Lossless Compressed (M)
> (1:1) Raw Lossless Compressed (L)
> (1:1) Raw Uncompressed
> 
> Cropped mode
> (1:1) Raw Uncompressed
> (1:1) Raw Lossless Compressed (M)
> (1:1) Raw Lossless Compressed (S)
> (1:1) Raw Compressed
> 
> Cropped mode
> (16:9) Raw Compressed
> (16:9) Raw Lossless Compressed (S)
> (16:9) Raw Lossless Compressed (M)
> (16:9) Raw Uncompressed
> 
> Cropped mode
> (4:3) Raw Uncompressed
> (4:3) Raw Lossless Compressed (M)
> (4:3) Raw Lossless Compressed (S)
> (4:3) Raw Compressed
> 
> Cropped mode
> (3:2) Raw Compressed
> (3:2) Raw Lossless Compressed (S)
> (3:2) Raw Lossless Compressed (M)
> (3:2) Raw Uncompressed

**Comment by kmilos** [comment]
See https://github.com/darktable-org/rawspeed/pull/528

**Comment by LebedevRI** [comment]
b220d54d8ea6c8b8bca8c7d1b28e50cfe67838ea

**Comment by Mdmdma** [comment]
I am on 4.8.1, why do I get the color matrix not found error when trying to open pictures in the darkroom. The camera should be added as far as I got it.

**Comment by Mdmdma** [comment]
I see, my problem was that I used S files. Is there a way I can contribute so that M and S files can be supported in the future?
