### ISSUE TITLE
random crash on loading next photo

### ISSUE THREAD

**Issue by sss123next** [darktable-org/darktable#15533]
### Describe the bug

loading next photo causing a crash, randomly

### Steps to reproduce

1. try to load next image in darkroom mode
2. 

### Expected behavior

darktable should load next photo

### Logfile | Screenshot | Screencast

[darktable_crash.txt](https://github.com/darktable-org/darktable/files/13209617/darktable_crash.txt)

### Where did you install darktable from?

darktable.org

### darktable version

current master, probably 815b313fbcc36be6f150ed95e314e8c1f64230b3

### What OS are you using?

Linux

### What is the version of your OS?

nixos, kernel 6.5.9

### Describe your system?

nixos 23.05

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment]
I cannot reproduce. 4.5.0+1036~g3c19610
Fedora 38 KDE Xorg Nvidia 3060.

**Comment by dterrahe** [comment]
> loading next photo causing a crash, randomly

It would be very helpful if you could find a specific combination of images (and xmps) and zoom settings (% and what part of image shown) that reliably triggers the crash. That would/should/could allow me to easily trigger it here, find the cause and hopefully a fix. At the moment I haven't seen this yet (after experimenting a while).

Thanks for reporting!

**Comment by sss123next** [comment]
looks like it was on my side, i have rebuilt darktable form latest master on fresh system configuration and problem is gone, sorry to trouble, but if it occurs again, i will provide samples which causing it.

**Comment by sss123next** [comment]
happened again, at "fit to window" zoom level
[FC_07986.zip](https://github.com/darktable-org/darktable/files/13217185/FC_07986.zip)
[FC_07987.zip](https://github.com/darktable-org/darktable/files/13217189/FC_07987.zip)

i can reproduce problem by changing photos forward<>backwards, crash does not happening on zooming, only in switching to next/prev photo

here is darktable configs 
[darktable.zip](https://github.com/darktable-org/darktable/files/13217232/darktable.zip)

**Comment by sss123next** [comment]
i have not applied anything yet, but here is also xmp's, i havr frw modules enabled by default...

[FC_07986.xmp.zip](https://github.com/darktable-org/darktable/files/13217294/FC_07986.xmp.zip)
[FC_07987.xmp.zip](https://github.com/darktable-org/darktable/files/13217295/FC_07987.xmp.zip)

**Comment by dterrahe** [comment]
Unfortunately those images are working fine here (switching back and forth I mean; no crashes) :-/

**Comment by sss123next** [comment]
maybe something wrong in config ?, i have explicitly disabled opencl for intel gpu as it causing crash on startup...

**Comment by pehar1** [comment]
Also not able to reproduce, 4.5.0+1038-g6697a9e457, Ubuntu 22.04

> maybe something wrong in config ?

You can check this by running dt with a completely fresh configuration from the command line. See https://darktable-org.github.io/dtdocs/en/special-topics/program-invocation/darktable/ ( `-configdir` pointing to an empty directory)

**Comment by sss123next** [comment]
i have done few more tests, it seems problem not related to darktablerc, happening only if i turn on all modules

```
Thread 1 ".darktable-wrap" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a4a7e0 in dt_dev_get_viewport_params () from /nix/store/s1d5qhwckl6xv9k55f7ilszhr9cbsb3m-darktable-git/lib/darktable/libdarktable.so
(gdb) set logging on 
Warning: 'set logging on', an alias for the command 'set logging enabled', is deprecated.
Use 'set logging enabled on'.
```

[darktable_crash2.txt](https://github.com/darktable-org/darktable/files/13225472/darktable_crash2.txt)

**Comment by sss123next** [comment]
i have created new group of modules based on `all` set, removed ones which i rarely use or not using at all, and this seems to resolve this crash....

**Comment by kofa73** [comment]
> i have created new group of modules based on `all` set, removed ones which i rarely use or not using at all, and this seems to resolve this crash....

Does this not sound like having a specific item in the module groups causing the issue? Maybe bisecting the module list could also help. Does it happen when *all* modules are enabled? Does it happen perhaps based on the size of the window? If have had one bug (unrelated and already fixed) that only happened with specific dimensions of the window.

**Comment by sss123next** [comment]
yes, this happened if `all` modules is enabled.
so how can i help ?

here is my current ~/.config/darktable :
[darktable.zip](https://github.com/darktable-org/darktable/files/13225946/darktable.zip)

i have created `my` module set, which seems works and not crash.

**Comment by sss123next** [comment]
crashed again.
but with reduced module count it happens very rarely, looks like some race condition ..., also  i have relatively slow hdd connected via network, so i have a huge lag in data transfers sometime.

**Comment by sss123next** [comment]
while reducing module count make this crash appear much rarely, it's still happening,  most stable seems `search only`, but even in this mode i am able to trigger crash if i switch photos very quickly

**Comment by sss123next** [comment]
also, this problem seems to appear recently, i think i can relatively easy find which commit works for me...

**Comment by TurboGit** [comment]
Can you try disabling the automatic write of XMP? Check the pref in `Storage` section of the pref and set the value to 0.

**Comment by sss123next** [comment]
tested on 16fd5b7b95e8076f04caa2e69be06219d3ab5bdc , does not crash.

**Comment by sss123next** [comment]
> Can you try disabling the automatic write of XMP? Check the pref in `Storage` section of the pref and set the value to 0.

yes, i can.

**Comment by sss123next** [comment]
> > Can you try disabling the automatic write of XMP? Check the pref in `Storage` section of the pref and set the value to 0.
> 
> yes, i can.

i set `create sidecar files` : `after edit`

still crashing.

**Comment by sss123next** [comment]
also still works fine on 16fd5b7b95e8076f04caa2e69be06219d3ab5bdc commit (i just peeked random commit 5 days ago)

**Comment by TurboGit** [comment]
@sss123next : No I was speaking about the "**save history while developing**" option:

![image](https://github.com/darktable-org/darktable/assets/467069/6411385e-081d-408d-89d2-a20876e55f7d)

**Comment by TurboGit** [comment]
Also, would be nice to have a backtrace with debug information. You would need to compile with `RelWithDebInfo` or `Debug` on the `--build-type` option.
