### ISSUE TITLE
Darktable Raw File Import, using imbedded JPG images

### ISSUE THREAD

**Issue by a-1b-2** [darktable-org/darktable#15540]
**Is your feature request related to a problem? Please describe.**
Darktable will not import or process my RAW photo images. I have a new Panasonic DC-ZS200D/ or in Europe the TZ200D travel zoom. This camera is identical to the ZS200/TZ200 except that Panasonic could not source enough LCD screens so they switched to an OLED display screen. This ZS200D/TZ200D is otherwise identical to the ZS200/TZ200 which Darktable will import and work with.  I have tried to  submitte a photo set for inclusion in the profiled list with no result.

**Describe the solution you'd like**
The suggestion for a feature addition to Darktable is to provide a default software routine which could create a profile for an undefined raw format from the JPG image that is always imbedded in a cameras RAW image file. This is much like what "RawTherapee" does in their raw photo processing program, which does work with my cameras Raw images. That way Darktable could work with a much wider spectrum of cameras, and adapt to new camera raw formats faster.

**Alternatives**
A simple alternative to doing a bunch of coding is to add my ZS200D/TZ200D to the list of accepted camera profiles and use the same Raw profile as the ZS200/TZ200. This would however only help me and the other owners of the new Panasonic travel zoom camera version.

Thanks for your consideration!

**Comment by MStraeten** [comment]
have a look at https://github.com/darktable-org/rawspeed/pull/538 and be patient ...
btw: there's a search function available ...
