### ISSUE TITLE
New crop changes cause massive flickering

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15549]
### Describe the bug

I just tested the zero offset crop in latest git and for me it looks like this:
[Bildschirmaufzeichnung vom 2023-11-01, 16-35-37.webm](https://github.com/darktable-org/darktable/assets/920721/41d0c2c7-5d37-4230-a722-dc65660e4f8c)

Happens with or without opencl

### Steps to reproduce

Zoom in
Enable and disable crop module
flickering

### Expected behavior

darktable should not flicker

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+1015~gb954c56d12

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

64 GB RAM, Ryzen 9 7950X

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

AMD 6700 XT, ROCM 5.7.1

**Comment by dterrahe** [comment]
It would have been useful if the video had shown either the navigator widget (top left panel) or the expanded crop module, so it would be easier to tell what is really happening.

**Comment by piratenpanda** [comment]
[Bildschirmaufzeichnung vom 2023-11-01, 20-59-55.webm](https://github.com/darktable-org/darktable/assets/920721/8683f2a2-b869-4b67-8a94-30af483fc9ed)
Hope this is better

**Comment by dterrahe** [comment]
Yes; thank you!

We're still working on improving the smoothness of panning/zooming/(un)cropping switches. The challenge here is that to try to keep the same location visible, independent of crop showing or not, we need to store its location with reference to the location in the original RAW. To translate between that coordinate system and the location within the image currently on screen, we need to go through the pipe that is set up based on the currently active history. When crop, retouch or liquify are active, the crop module is temporarily removed from that pipe and then it is recalculated. _While_ this switcheroo is going on, it is temporarily hard to do the coordinates conversion correctly. I'm still hopeful we may be able to improve on the current situation, which has several manifestations; the flashing you are experiencing is not as obvious on my machine, but the second preview window and snapshots all behave sub-optimally when a crop is present but temporarily switched off.

All I can do for now is ask for patience (and thoughts and prayers, obviously).
