### ISSUE TITLE
borders: bug introduced while implementing the support for basis border computation

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15545]
### Describe the bug

For some aspect ratio (16:9 for example) the borders are not properly rendered.

We used to have:

![image](https://github.com/darktable-org/darktable/assets/467069/005b6346-7ee6-4c7d-aecf-b3e4aeb67cc9)

Now we have:

![image](https://github.com/darktable-org/darktable/assets/467069/736b6f6d-54f8-44b7-94b4-969f210ffd39)

### Steps to reproduce

1. Go to darkroom
2. Enable the Framing module
3. Select 16:9 as aspect ratio

See that the top/bottom borders are not properly rendered.

### Expected behavior

We expect a top/bottom border.

### Where did you install darktable from?

darktable.org

### darktable version

Current master (dc567c0d8ec3e3c235417c18cb737681c3093e0f)

### What OS are you using?

Linux

### What is the version of your OS?

Debian/sid

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The first bad commit is acd621d698531e3a4e5c1af2d83afb6762e34318.

Reproduced with both CPU & OpenCL.

**Comment by TurboGit** [comment]
@jonasberge : A regression introduced with your PR. Can you have a look? TIA.

**Comment by jonasberge** [comment]
Sorry, I didn't properly test all possible combinations.

I removed this in my PR:
```c
    // insane settings used?
    if(roi_out->height < (float)roi_in->height / (1.0f - size))
    {
      roi_out->height = roundf((float)roi_in->height / (1.0f - size));
      roi_out->width = roundf((float)roi_out->height * aspect);
    }
```
adding it back at the end of the big else-block fixes it.

I made a PR with a more logically sound solution though.

#
