### ISSUE TITLE
Ability to retain file extension when renaming images. 

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#15551]
I use the lua script to rename images and this feature works very well except it doesn't retain the file extension. The script will also not allow me to apply a variable for the naming process, which in my case I would want to use use the variable of file extension. Is it practical to retain the file extension when renaming the images or is it just too difficult to code for this?

**Comment by wpferguson** [comment]
$(FILE_EXTENSION)

**Comment by wpferguson** [comment]
Issues with the scripts should be raised at https://github.com/darktable-org/lua-scripts/issues.  

Just tested with an image named 117EOS7D2__D2_6008.CR2.  The argument I gave to rename_images was `$(FILE_FOLDER)/testing.$(FILE_EXTENSION)`.  After clicking the button the image was renamed to `testing.CR2`

**Comment by tpinfold** [comment]
Well I be damned or is that DAMed. It is working now. Thanks for the reply.
