### ISSUE TITLE
NEF files from Nikon D3400 fail to load on Fedora 36

### ISSUE THREAD

**Issue by tac-gb** [darktable-org/darktable#15562]
### Describe the bug

The camera is listed as supported on the website but the raw files cannot be loaded. Version is 4.4.2 on Fedora 36.

![image](https://github.com/darktable-org/darktable/assets/10121496/6fbf0f72-5765-4a3e-9183-c0671d6957d1)
![image](https://github.com/darktable-org/darktable/assets/10121496/c646fb39-5638-42ca-91d7-3604e2f41a0b)
![image](https://github.com/darktable-org/darktable/assets/10121496/fd36c042-5a9b-42ee-b1ba-ae341a6799ca)

### Steps to reproduce

1. Install darktable from OBS on Fedora 36
2. Load a Nikon NEF RAW image taken by Nikon D3400

### Where did you install darktable from?

OBS

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 36

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
Unreproducible on D3400 samples from raw.pixls.us. You'll have to provide a sample of the file that you failed to load.

**Comment by TurboGit** [comment]
Works also on my side on one D3400 sample.

**Comment by tac-gb** [comment]
Here is a sample of one of the files that fails to load.

https://f005.backblazeb2.com/file/quantum-phoenix-nebula/DSC_0326.NEF

**Comment by tac-gb** [comment]
Actually; I am mistaken; that image and other image file seems to work fine. The problem was that some of the files being picked up in the recursive directory search had their contents missing.

**Comment by japamax** [comment]
I've the same issue with darktable-git 4.5.0.r1268.g594c98c90b-1 on archlinux for photos from Nikon D7000 and Tamron lens
I join 2 photos taken one minute part : the _DSC8803.NEF fails ans the _DSC8804.NEF works
All raw application but darktable (krita, rawtherapee ...) can open the 2 images
[_DSC8803.zip](https://github.com/darktable-org/darktable/files/13450715/_DSC8803.zip)
[_DSC8804.zip](https://github.com/darktable-org/darktable/files/13450717/_DSC8804.zip)

**Comment by kmilos** [comment]
@japamax AFAICT, these files are not straight out of camera, and have been modified by other software (e.g. for tagging etc.), correct?

**Comment by japamax** [comment]
I've a backup
The Header had some more infos (gHex) but all other software can open it
I joined the backup 
[_DSC8803_202031113.zip](https://github.com/darktable-org/darktable/files/13451189/_DSC8803_202031113.zip)

**Comment by japamax** [comment]
exiftool or/with  digikam could modify the image.
But that doesn't explain why only Darktable is unable to open it. Krita, RawTherapee, XnView, and all other software can open the file correctly, even with additional data added to the header.

**Comment by kmilos** [comment]
> But that doesn't explain why only Darktable is unable to open it. Krita, RawTherapee, XnView, and all other software can open the file correctly, even with additional data added to the header.

They all have/use different raw file decoding libraries/code. dt uses rawspeed. Others most likely LibRaw, dcraw, etc. Different libraries, different implementations, features, bugs...

**Comment by LebedevRI** [comment]
@japamax please contribute one of the problematic `.NEF`s to https://raw.pixls.us/
You are really not supposed to modify original raw files in any way whatsoever,
otherwise things just break with no warranty.

**Comment by kmilos** [comment]
@japamax You also might want to report this to digiKam and/or exiftool

**Comment by japamax** [comment]
For all other software, it's a Placebo operation. 
I can't report anything !!! 

Here's how it will go:

Me: The modification with exiftool adds data to the header of the files. For you, it doesn't change anything, and the programs that use dcraw or libraw are not affected, only Darktable is impacted.

Them: Contact the Darktable developers.

**Comment by kmilos** [comment]
> I can't report anything !!!

Au contrarie. You can report they have modified the raw file w/ unpredictable consequences.

**Comment by kmilos** [comment]
@japamax Turns out this is also almost the same as https://github.com/darktable-org/darktable/issues/5149

**Comment by japamax** [comment]
You have a disrespectful attitude towards the issue. I'm showing you that the modified header of Nikon files doesn't impact the file's readability in all other software. Yet, you argue that it's the other software that shouldn't modify the header.

Firstly, in the previous post, you clearly demonstrated that the header of the files is correct since NO ERRORS are detected by exiftool.

Secondly, I have tens of thousands of images from various cameras, and only the NEF files are affected.

You cannot consciously ignore this problem just because the header has been modified. All other file formats in Darktable and all other software work, except for the ultra-rigid reading of NEF files in Darktable. 

Your approach lacks a 'professional' attitude in deliberately not addressing this issue.

**Comment by LebedevRI** [comment]
@japamax i think you are completely missing the point, up to the point of inventing arguments we never said.
Also, please take this down a notch.

**Comment by kmilos** [comment]
Thanks Roman. Time to unsubsribe.

**Comment by japamax** [comment]
The facts and only the facts:
The files have modified headers that result in NO ERRORS in the exiftool executable or in any other RAW file reading programs.
You are unwilling to investigate why this error occurs in Darktable, under the pretext that header modification cannot be allowed—it's just an unproven dogma.

Your documentation/reverse engineering of NEF files is incomplete, and you are unwilling to reconsider.

**Comment by ptilopteri** [comment]
and you apparently cannot understand that dt is INTENDED to work on unmodified raw files and is provided by donated personal efforts, not on demand.

plain fact, your file(s) *are* modified.

why don't you try UNmodified files?

**Comment by TurboGit** [comment]
@japamax : It is not because a program can read a modified header that there is nothing broken there. In an header there is lot of information and all software are not reading all of them. Changing a RAW file is a huge mistake and should never be done by any software, period. That's not a dogma that something we have learn on darktable as it has already proved to be creating unsolvable issues.
