### ISSUE TITLE
segfault when comparing with snapshot of deleted image

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15565]
### Describe the bug

When comparing with the snapshot of a deleted image, darktable crashes.

### Steps to reproduce

1. Open an image (it's probably a good idea that it's a duplicate, as we'll delete it).
2. Create a snapshot.
3. Return to the lighttable.
4. Delete the image.
5. Open another image.
6. Enable snapshot comparison.
7. Zoom in => crash

### Expected behavior

Invalidate the snapshot of the deleted image and not crash

### Logfile | Screenshot | Screencast

With OpenCL enabled:
```
Thread 93 "darktable" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5a84b6c0 (LWP 59842)]
0x00007fffa41d75b1 in _process_linear_opposed._omp_fn.0 () at /home/kofa/darktable/src/iop/hlreconstruct/opposed.c:157
157               if((input[idx] >= clips[c]) && (mask[c*msize + mdx] == 0))
logging debugredirect:  off: Debug output will go to both the screen and the log file.
logging enabled:  on: Logging is enabled.
logging file:  The current logfile is "gdb.txt".
logging overwrite:  off: Logging appends to the log file.
logging redirect:  off: Output will go to both the screen and the log file.
#0  0x00007fffa41d75b1 in _process_linear_opposed._omp_fn.0 () at /home/kofa/darktable/src/iop/hlreconstruct/opposed.c:157
#1  0x00007ffff7f6848e in ??? () at /lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff7297ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#3  0x00007ffff732847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
At another time (this time running with OpenCL disabled):
```
Thread 93 "darktable" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff524f46c0 (LWP 61120)]
0x00007fffb47f8162 in process._omp_fn.2 () at /home/kofa/darktable/src/iop/temperature.c:602
602             out[k+c] = in[k+c] * d_coeffs[c];
(gdb) bt
#0  0x00007fffb47f8162 in process._omp_fn.2 () at /home/kofa/darktable/src/iop/temperature.c:602
#1  0x00007ffff7f6848e in ??? () at /lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff7297ada in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#3  0x00007ffff732847c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### Where did you install darktable from?

Self-compiled

### darktable version

4.5.0+1083~g295ccd75fc

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Ryzen 5 5600, 64 GB RAM, NVidia 1060/6 GB, 525.147.05

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6 GB, 525.147.05

**Comment by TurboGit** [comment]
@kofa73 : Can you test with #15567?

**Comment by kofa73** [comment]
That was quick! Unfortunately, I'm away from my computer. I'll try tomorrow morning.

**Comment by kofa73** [comment]
Confirmed: can no longer reproduce the crash. Thanks!
