### ISSUE TITLE
Can't correct vignetting in Lens correction module with DNG files

### ISSUE THREAD

**Issue by kurld** [darktable-org/darktable#15574]
### Describe the bug

Not sure if it affects all files in DNG format or only some specific ones.
Lens correction module when set to "embedded metadata" mode does not correct vignetting and does not allow fine tuning of vignetting  (the slider is not there), despite VignettingCorrParams tag present
in EXIF. Other fine tuning options are also not available except distortion and image scale - see screenshot.

```
exiftool -s DSC09088.dng|grep VignettingCorrParams
VignettingCorrParams            : 0 16 48 80 128 192 272 368 496 608 784 1104 1584 2256 3168 4512
```

### Steps to reproduce

1. Open DNG file in darkroom
2. Enable Lens corrections and set Embedded metadata mode
3. No vignetting corrections applied and no 'fine tuning' slider  for vignetting available

![Screenshot from 2023-11-05 10-13-46](https://github.com/darktable-org/darktable/assets/9458921/18a5fc96-696a-466c-875e-306132c7bb9a)

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1064~g03e6c67782

### What OS are you using?

Linux

### What is the version of your OS?

Arch

### Are you using OpenCL GPU in darktable?

Yes

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[download dng](https://drive.google.com/file/d/1gFLMRQS9CO8Gk0P4b7O9R2k28A1UV7Zd/view?usp=sharing)

**Comment by MStraeten** [comment]
why not provide a sample if you're not sure if it affects all DNG or just specific ones - so someone can reproduce ...

**Comment by jenshannoschwalm** [comment]
It's probably not according to dng opcode list...

**Comment by kurld** [comment]
Download link is now available in the first post.

**Comment by paolodepetrillo** [comment]
In this case the VignettingCorrParams tag is a Sony proprietary vignetting tag that existed in the original ARW file. If the original ARW file had been opened in darktable, then it would have applied the correction in that tag. Adobe DNG Converter did copy the Sony tag into the DNG file to where exiftool can see it (inside the DNGPrivateData tag), but darktable doesn't see it there. Adobe DNG Converter did not interpret it and convert it to a FixVignetteRadial opcode inside the OpcodeList3 tag, which is the only vignetting correction that darktable supports for DNG files.

**Comment by kurld** [comment]
Thanks for that explanation. Do you know if that's an issue with Adobe DNG converter not following some sort of format specification or is it Darktable's design decision?
Meanwhile I've checked some other DNG files produced by cameras that natively save to DNG (Pentax, Leica) and those corrections are also not available in Darktable for those files.

**Comment by kmilos** [comment]
> Do you know if that's an issue with Adobe DNG converter not following some sort of format specification or is it Darktable's design decision?

I think the jury is out on this one, it's not 100% clear to me what's the intent/usefulness of vendor MakerNotes after Adobe conversion...

Even if they're still usable, there is a potential problem that Adobe changes the MakerNotes payload slightly when storing it in `DNGPrivateData` upon conversion, and it's not at all guaranteed exiv2 can still decode it just as before. And there's also no guarantee Adobe transfers 100% of all proprietary data over, as it can be scattered across several places in a raw file, not just the MakerNotes...
