### ISSUE TITLE
Edits lost when storage prematurely detached

### ISSUE THREAD

**Issue by cmjns** [darktable-org/darktable#15595]
### Describe the bug

I realize this may not be recommended but I have DT put its database on a removable drive with my photos. I worked with LR this way for years, so... Anyway last night I unmounted my drive before closing DT. When I plugged the drive back up and started DT all of my edits and ratings were gone. That was half a day of work. 

I was surprised at this because I do have DT writing sidecar files on import. Does DT only write changes to the db or to the sidecar files when closed? If the DT database were on my local drive and not my external storage, would I not have lost my work? 

I'm filing this as a bug because I was surprised at the behavior and I imagine other users might be as well, and because it seems like dt shouldn't be holding onto changes and flushing them to db only when closed (if that is what happened).

### Steps to reproduce

Open DT, 
Put the db on an external drive. 
Do a lot of work
Unmount the drive
Close DT
Reattach the drive
Start DT
Work is missing

### Expected behavior

If my drive gets detached for any reason, I should not lose my work. 

### Where did you install darktable from?

darktable.org

### darktable version

4

### What OS are you using?

Linux

### What is the version of your OS?

Mint (latest)

### Are you using OpenCL GPU in darktable?

None

**Comment by ptilopteri** [comment]
<quote>
Steps to reproduce
Open DT,
Put the db on an external drive.
Do a lot of work
Unmount the drive
Close DT
Reattach the drive
Start DT
Work is missing
</quote>

why would you unmount the drive before closing dt?

I suggest you change to:
     close dt
     unmount drive

     remount drive
     open dt
     open collection just worked on

removing the drive before dt has finished may be your problem.

**Comment by wpferguson** [comment]
darktable 4.6, to be released in December, has an option under the storage menu to periodically save edits.  You can set the interval in seconds.

**Comment by ralfbrown** [comment]
Other than the image you were currently working on at the time the drive was unmounted, dt will have updated its information for all images.  The dt 4.6 enhancement will ensure that all but the last few seconds of the current image's edit will be written to the database as well.

If the disk file for the database isn't actually being updated, then either dt has misconfigured something in sqlite or sqlite/Mint has a bug/misconfiguration when it comes to flushing writes to the external drive.  Since you said you unmounted it, I assume you didn't just disconnect it without first giving the OS a chance to write anything still in its disk cache -- that would be BAD....

**Comment by cmjns** [comment]
There are all kinds of reasons why an external USB drive might become detached, either properly or improperly. The plug can get bumped. Or even if the drive is properly unmounted, it can be the case that darktable is minimized at the time the drive is removed and the user forgets that's the case. I always take great care to properly unmoAccepting that users do silly things from time to time, either due to ignorance or negligence, I think the question is whether the software could be more resistant to fault, not to troubleshoot user behavior.
