### ISSUE TITLE
Soft proofing not working?

### ISSUE THREAD

**Issue by mminelli** [darktable-org/darktable#15590]
### Describe the bug

Activating the soft proofing does not change anything in the displayed image, even when selecting a very different profile. Similar to what was discussed in https://github.com/darktable-org/darktable/issues/15313, but I did not really get what the conclusion was there.

### Steps to reproduce

1. Open an image in darkroom and set the soft proofing profiles as in the screenshot below
2. Activate soft proofing
3. The histogram changes but the image does not

![image](https://github.com/darktable-org/darktable/assets/29192188/292ea285-bc7b-4285-ad33-998ea0b2d2c8)

### Expected behavior

The image should be displayed with a BRG profile (so colors should be quite strange)

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Are you using OpenCL GPU in darktable?

None

**Comment by parafin** [comment]
soft-proofing with BGR profile shouldn’t result in swapped channels, you are misunderstanding what it does

**Comment by parafin** [comment]
Please read my comment at the issue you linked yourself:

**Comment by mminelli** [comment]
OK thanks again for the info. The confusing thing for me is that I have the same behavior no matter what softproof profile I choose (e.g., Adobe RGB or Rec709 RGB, etc.).
In each of these cases, when I click the icon, the histogram changes, so "something" is happening. But the image never changes one bit.

So I wonder, how I am supposed to use soft proofing. Is it a problem with my display, my setup, etc.? Or, if this is the expected behavior, what is the "value" of soft proofing if I don't see how the image would change once printed?

**Comment by parafin** [comment]
To be clear - I’m not saying soft-proofing works correctly in darktable - I’m not sure of that. But so far people provide only wrong arguments about why it’s broken.

**Comment by mminelli** [comment]
Thanks for the pointers, I will dig a bit deeper because now I am even more curious. To be clear

> How choosing the soft-proofing profile is different from just **(I would say "temporarily")** changing the display profile?

is exactly what I was wondering.

And as for whether it's broken or not, I honestly don't know. All I can say is that, as a user, "I click the icon and nothing happens". Then it might be the intended behavior, but I find it counterintuitive.

That said, I must say I hugely appreciate such a powerful and versatile tool that comes completely for free.

**Comment by parafin** [comment]
Try choosing Adobe RGB profile (or some other wide gamut profile) as display profile and sRGB/Rec709 (so smaller gamut than display profile) as soft-proof profile. Then if you have very saturated colors (outside of sRGB gamut) they (and only they) should change to the duller colors when you enable soft-proofing. Probably easier to test with some artificial source file which has pure red/green/blue and choosing Adobe RGB as input profile. That would be a correct test.

**Comment by mminelli** [comment]
OK, now I get what you mean. I will try, thanks a lot!
