### ISSUE TITLE
Noise Profile for Canon IXY 220F

### ISSUE THREAD

**Issue by chapatt** [darktable-org/darktable#15598]
I have generated a noise profile for my Canon IXY 220F for inclusion upstream. Please see attached. Thank you :)

These were taken with CHDK v1.6.1 in order to take DNG raw images. Additionally, the PowerShot ELPH 110 HS and IXUS 125 HS should be the same camera.

~~[darktable-noiseprofile-20231107.tar.gz](https://github.com/darktable-org/darktable/files/13292111/darktable-noiseprofile-20231107.tar.gz)~~

Please see updated profile below.

**Comment by kmilos** [comment]
We don't have this camera (under any of the three designations) in the database for checking basic support.

Please also upload a sample (incl. a CRW dump if possible) to https://raw.pixls.us/

**Comment by chapatt** [comment]
Thanks, @kmilos, I uploaded sample DNG and CRW files there.

**Comment by chapatt** [comment]
I've actually realized the camera occasionally chooses a native minimum ISO of 96, meaning darktable does not automatically apply one of the noise profile or interpolate between two (as 96 is below the minimum provided profile of 101). Can we simply change the `iso` property in the JSON to `96`, or do I need to recapture and process the data?

**Comment by kmilos** [comment]
Possibly, but I'll leave that decision for @rawfiner

**Comment by rawfiner** [comment]
@chapatt sometimes the noiseprofile script and darktable disagree slightly on ISO setting reading due to difference in metadata library. Maybe it is the case here, because ISO 101 and 96 seem very close...
Do you see both ISO values within darktable?
If yes, we need a profile for both. If not, we just need to match the correct ISO setting in the profile.

Also, is there something that allows to differenciate CHDK raw from non-CHDK raw for profile matching? We would want one profile for each

**Comment by chapatt** [comment]
@rawfiner, I don't think a discrepancy like that is the problem here (the images I used to generate the profile show the same ISO metadata as the script detected.

I took another photo at ISO 96 and regenerated the profile. It seems to be working correctly. Please see attached.

If I understand what you're asking, the stock firmware on this camera does not take raw photos, so CHDK raw is the only option here (like most of the Canon point and shoot cameras in the db, I assume).

P.S.
I set the ISO manually via CHDK, but using the natural, auto-exposure, I found it interesting the difference between the actual ISO (captured by CHDK in the raw metadata) compared to the rounded numbers in the matching JPG (they're all DNG + JPG captures). It seems the camera uses very granular ISO, but shows a conventional, round number in the metadata (which is the same as what it shows on the camera screen, e.g. when it says 100, it usually is actually 96). I'm not sure if it adjusts the exposure while developing the JPG in order to make this number correct (or if it's just a lie XD). Below are some more example numbers:
```
100
	96
125
	139
	118
160
	172
	146
200
	215
	192
250
	243
	265
320
	293
	351
400
	415
	443
500
	497
	490
640
	586
	591
800
	800
1000
	911
	1015
1250
	1181
	1261
1600
	1600
```
[darktable-noiseprofile-20231114.tar.gz](https://github.com/darktable-org/darktable/files/13360455/darktable-noiseprofile-20231114.tar.gz)

**Comment by rawfiner** [comment]
@chapatt thanks for explaining. Profile looks good to me, so it can be integrated.
I won't have time to do the PR until (at best) sunday, so if anyone wants to do it, go ahead :-)

**Comment by kmilos** [comment]
@LebedevRI Can you please publish these samples on RPU as well?

**Comment by LebedevRI** [comment]
@chapatt thank you for contributing the samples!
