### ISSUE TITLE
Add option to scale watermark relative to cropped image size

### ISSUE THREAD

**Issue by cmjns** [darktable-org/darktable#15608]
**Is your feature request related to a problem? Please describe.**
When applying a watermark the mark is scaled relative to the original image size rather than to the cropped image size.

**Describe the solution you'd like**
I'd like the option to scale the watermark to the cropped image size so all watermarks come out the same size

**Alternatives**
A checkbox or a dropdown selection to chose "Scale to Original" or "Scale to Cropped", or just change the behavior as I'm not sure if the current behavior is a feature or a bug.

**Additional context**

**Comment by TurboGit** [comment]
That's the case! Which version are you using?

Take for example the default watermark. Set scale to 50% or larger border, it gives:

![image](https://github.com/darktable-org/darktable/assets/467069/b0581332-6974-4413-bbb3-9fe3a3aaf48e)

Now do a square crop of the image, see that the watermark still has 50% of the larger border:

![image](https://github.com/darktable-org/darktable/assets/467069/982fca92-6a0d-41b5-904e-c0785caadad0)

**Comment by cmjns** [comment]
I'm using version 4. I saved my watermark settings as a preset. When applied to an uncropped image, The watermark was small. When applied to a larger image, the watermark was bigger.

**Comment by cmjns** [comment]
Note that I'm using a PNG image, not the internal darktable watermark. Perhaps the behavior I describe is particular to a user defined image watermark?
