### ISSUE TITLE
mass thumbnails (re)generation

### ISSUE THREAD

**Issue by sss123next** [darktable-org/darktable#15607]
**Is your feature request related to a problem? Please describe.**

currently thumbnails generating on-demand, but for large directories of large photos on slow block device it may take large amount of time.

**Describe the solution you'd like**

it would be nice to have ability to generate thumbnails for whole library.
it's wise to implement 2 modes:
1. generate only missing thumbnails
2. regenerate all thumbnails

**Comment by victoryforce** [comment]
Please see #15076 and #15294.

**Comment by MStraeten** [comment]
there’s a commandline tool for it: https://docs.darktable.org/usermanual/4.2/en/special-topics/program-invocation/darktable-generate-cache/

**Comment by sss123next** [comment]
i see,  this is it, sorry to trouble...
