### ISSUE TITLE
Unable to locally control Fuji XT-4 during tethered capture even with latest libgphoto2

### ISSUE THREAD

**Issue by bocajnotnef** [darktable-org/darktable#15611]
### Describe the bug

I had an issue in Darktable where when tethering my Fuji XT-4 I was unable to use the controls on the camera. I could configure and trigger a capture from Darktable, but pressing buttons on the camera didn't do anything.

I dug around and found this was an issue in the underlying gphoto2 and libgphoto2 libraries ([related issue]https://github.com/gphoto/libgphoto2/issues/653)). That issue has been fixed in the latest master of `libgphoto`, which I've tested and confirmed, but the problem persists in Darktable: when I start a capture session, I have no local control of the camera.

I expected the problem would be fixed given that triggering a tethered capture in gphoto with the latest changes from gphoto's master works; that is, when doing `gphoto2 --capture-tethered` I can use the camera's shutter release and receive the pictures just fine.

I don't see any configuration options within Darktable to allow for local control--Am I missing something?

### Steps to reproduce

 install libgphoto2 and gphoto dependencies (`libjpeg-dev libusb-dev libpopt-dev debian-goodies build-essential`
- clone libgphoto2
  - `git clone git@github.com:gphoto/libgphoto2.git`
- configure and compile libgphoto2
  - (in the `libgphoto2` directory)
  - `autoreconf --install --symlink`
  - `./configure --prefix=/usr/local`
  - `make`
  - `make install`
- clone gphoto2
  - `git clone git@github.com:gphoto/gphoto2.git`
- configure and compile gphoto2
  - `./configure && make && make install`
- launch Darktable
- mount camera
- choose 'Tethered Shoot'
- Try to use camera's shutter release

### Expected behavior

The camera takes a photo and the images are downloaded to Darktable

### Where did you install darktable from?

distro packaging

### darktable version

3.8.1

### What OS are you using?

Linux

### What is the version of your OS?

PopOS 22.04

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by pehar1** [comment]
The darktable version you are using is outdated (about 2 years old). The current version is 4.4.x, in a few weeks (around the winter solstice) version 4.6 will be released. I think it would be useful to update darktable first, then check if the problem persists.

**Comment by Nilvus** [comment]
No need so to let an issue about a 2 years old release. I so close. @bocajnotnef: when you can test with latest release, if you still reproduce, just ping me and I will reopen it.
