### ISSUE TITLE
strange refresh behaviour in color assessment mode onzoomed area

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#15615]
in color assessment mode zooming in to an image results in a partial refresh - (not rpeorducible if color assessment mode is deactivated:
<img width="400" alt="refreshIssue" src="https://github.com/darktable-org/darktable/assets/39386816/18e5a89e-2330-4331-974f-af5690777693">

just the framed area from preview window is ok:
![image](https://github.com/darktable-org/darktable/assets/39386816/4cadcc3a-c720-486b-8d07-41f85288a8c2)

log from -d common:
[log.txt](https://github.com/darktable-org/darktable/files/13320598/log.txt)

latest build with proper behaviour was darktable-4.5.0+997~g0321f1b325_arm64 at 26.10; next build at 28.10 show that behaviour

### Where did you install darktable from?

self compiled

### darktable version

darktable-4.5.0+1127~gd6a2829bf5

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Sonoma

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1 Max

**Comment by dterrahe** [comment]
Color assessment mode should show a white and a grey border around the image. That does not seem to be happening here. If you are not zoomed in, are they visible? Does it get overwritten by the blocky area that is outside the zoomed in area? Everything outside of the framed area in preview should not be visible at all. The `cairo_clip` command here https://github.com/darktable-org/darktable/blob/1a673701ca808243f9da7e5d705a7c17ff43544b/src/views/view.c#L1731 should take care of that.

**Comment by dterrahe** [comment]
This is probably ppd related; could you please try if removing `* port->ppd` in these two lines resolves the problem?
https://github.com/darktable-org/darktable/blob/1a673701ca808243f9da7e5d705a7c17ff43544b/src/views/view.c#L1716-L1717

**Comment by MStraeten** [comment]
that resolves the issue with color assessment mode
