### ISSUE TITLE
[DT 4.5.0] When snapshot is activated, canvas gets a selection area

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#15626]
### Describe the bug

If you have previously used color pickers in one of the modules, even if you are in another module, if you have created a snapshot and then activated it, the selection area remains active.

![image](https://github.com/darktable-org/darktable/assets/38165484/795dd52c-3c05-42a4-b482-a5beeb53aced)

### Steps to reproduce

1. use a color picker in a module (e.g. exposure, color calibration)
2. then use another module
3. create snapshot
4. activate it
5. a selection area appears on the canvas
6. deactivate snapshot  
7. selection area disappears

To solve the problem:

1. activate snapshot again 
2. activate _color picker_ in the color _picker module_
3. selection area is switched off

### Expected behavior

Selection area should no longer be displayed after changing the module and after activating the snapshot.

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1138~g8fa44f311

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-1028-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070/PCIe/SSE2, 535.129.03

**Comment by piratenpanda** [comment]
Did you press the exposure pipette some time? I can confirm that the exposure pipette area stays active even if you are not in the exposure module for example when using snapshot comparison

**Comment by s7habo** [comment]
> Did you press the exposure pipette some time? I can confirm that the exposure pipette area stays active even if you are not in the exposure module for example when using snapshot comparison

Yes, but what I have noticed is that it does not matter from which module you have used the color picker. To fix the problem, you have to _activate and deactivate_ the color picker in the _color picker module_.
