### ISSUE TITLE
Nikon HLG RAW not supported

### ISSUE THREAD

**Issue by zasdfgbnm** [darktable-org/darktable#15625]
### Describe the bug

This file: https://drive.google.com/file/d/10A6c67piDc6dwuHQu3p8EtWi-PZM0PzJ/view?usp=drive_link

Displayed normally by Nikon Studio:
<img width="1499" alt="image" src="https://github.com/darktable-org/darktable/assets/1032377/aa0243a2-fd3a-4b0c-b2a6-5b56147210ff">

<img width="1167" alt="image" src="https://github.com/darktable-org/darktable/assets/1032377/f93f802e-9ca6-458f-9ba0-8184ddf6f856">

### Steps to reproduce

Just download the file and import it

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Sonoma 14.1

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
As the release notes clearly state already, Nikon's new "high efficency" compression mode is not yet supported, so this is a known issue ([since the Z 9 launch](https://github.com/darktable-org/darktable/issues/10889)).

Nothing to do w/ HLG output profile.
