### ISSUE TITLE
tiling results in segmentation fault on small systems

### ISSUE THREAD

**Issue by v923z** [darktable-org/darktable#15624]
### Describe the bug

This bug report is a continuation of https://github.com/darktable-org/darktable/issues/13464. 

In short, `darktable` produces a segmentation fault, when an image requires heavy processing, and memory use is restricted in the settings. The crash happens both in the `darkroom`, and in `lighttable`, when the thumbnail image is generated.

### Steps to reproduce

1. In the `processing` tab of settings, set the `CPU / GPU / memory` section to `small`
2. Try to open a file that employs heavy tiling (example attached at the end of this report)
3. Watch `darktable` crash with a segmentation fault

### Expected behavior

`darktable` should run at a lower speed, if RAM is an issue, but should not crash

### Logfile | Screenshot | Screencast

darktable -d opencl -d pipe -d tiling
     0.3884 [dt_get_sysresource_level] switched to 0 as `small'
     0.3884   total mem:       7492MB
     0.3884   mipmap cache:    468MB
     0.3884   available mem:   936MB
     0.3884   singlebuff:      29MB
     0.3884   OpenCL tune mem: OFF
     0.3884   OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
     0.3927 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL'
     0.3927 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL.so'
[opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
[opencl_init] could not get platforms: Unknown OpenCL error
[opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.
     6.6393 [pixelpipe_cache_checkmem]   [full]                                 64 lines (removed invalid=0, oldlines=0). Now important=0, used=0. Cache: freed=0MB. Now using 0MB, limit=117MB
     6.6394 [pixelpipe starting on CPU]  [full]                                (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 
     6.6394 [modify roi IN]              [full]         demosaic               (   0/   0) 6020x4024 scale=1.0000 --> (   0/   0) 1206x 806 scale=0.2003 
     6.6394 [modify roi IN]              [full]         rawprepare             (   0/   0) 6048x4024 scale=1.0000 --> (   0/   0) 6020x4024 scale=1.0000 
     6.6394 [pixelpipe data: full]       [full]                                (   0/   0) 6048x4024 scale=1.0000 --> (   0/   0) 6048x4024 scale=1.0000 
     6.6395 [pixelpipe_process_on_CPU]   [full]         rawprepare             (   0/   0) 6048x4024 scale=1.0000 --> (   0/   0) 6020x4024 scale=1.0000 IOP_CS_RAW
     6.6485 [pixelpipe_process_on_CPU]   [full]         temperature            (   0/   0) 6020x4024 scale=1.0000 --> (   0/   0) 6020x4024 scale=1.0000 IOP_CS_RAW
     6.6560 [pixelpipe_process_on_CPU]   [full]         highlights             (   0/   0) 6020x4024 scale=1.0000 --> (   0/   0) 6020x4024 scale=1.0000 IOP_CS_RAW
     6.6664 [opposed chroma cache CPU] red: 0.000000 (0), green: 0.000000 (0), blue: 0.000000 (0) for hash   1904413423052090228
     6.6846 [process TILE]               [full]         demosaic               (   0/   0) 6020x4024 scale=1.0000 --> (   0/   0) 1206x 806 scale=0.2003 
     6.6846 [default_process_tiling_roi] [full] **** tiling module 'demosaic' for image input size 6020x4024 --> 1206x806
     6.6846 [default_process_tiling_roi] [full] (2x1) tiles with max dimensions 4418x4024, good 604x808, overlap 12->3
     6.6846 [default_process_tiling_roi] [full] process tile (0,0) size 3029x4024 at origin [0,0]
     6.7775 [write detail mask on CPU]   [full]                                (   0/   0) 3029x4024 scale=1.0000 
     6.7776 [clip_and_zoom_roi]          [full]         demosaic               (   0/   0) 3029x4024 scale=1.0000 --> (   0/   0)  607x 806 scale=0.2003 
     6.8214 [default_process_tiling_roi] [full] process tile (1,0) size 3024x4024 at origin [2994,0]
     6.8986 [write detail mask on CPU]   [full]                                (2994/   0) 3024x4024 scale=1.0000 
     6.8987 [clip_and_zoom_roi]          [full]         demosaic               (2994/   0) 3024x4024 scale=1.0000 --> ( 600/   0)  606x 806 scale=0.2003 
     6.9393 [pixelpipe_process_on_CPU]   [full]         denoiseprofile         (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 IOP_CS_RGB
     7.0133 [pixelpipe_process_on_CPU]   [full]         hazeremoval            (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 IOP_CS_RGB
     7.0358 [pixelpipe_process_on_CPU]   [full]         exposure               (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 IOP_CS_RGB
     7.0370 [blend with form on CPU]     [full]         exposure               (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 IOP_CS_RGB 
     7.0512 [refine_detail_mask on CPU]  [full]         exposure               (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 
     7.1551 [pixelpipe_process_on_CPU]   [full]         exposure.1             (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 IOP_CS_RGB
     7.1562 [blend with form on CPU]     [full]         exposure.1             (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 IOP_CS_RGB 
     7.1812 [refine_detail_mask on CPU]  [full]         exposure.1             (   0/   0) 1206x 806 scale=0.2003 --> (   0/   0) 1206x 806 scale=0.2003 
Segmentation fault (core dumped)

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Describe your system?

8 GB of RAM, X11, 

```bash
dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'

ii  libgtk-3-0:amd64           3.24.37-1ubuntu1   amd64        GTK graphical user interface library
ii  libgtk-3-bin               3.24.37-1ubuntu1   amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common            3.24.37-1ubuntu1   all          common files for the GTK graphical user interface library
ii  libgtk-4-1:amd64           4.10.4+ds-0ubuntu1 amd64        GTK graphical user interface library
ii  libgtk-4-bin               4.10.4+ds-0ubuntu1 amd64        programs for the GTK graphical user interface library
ii  libgtk-4-common            4.10.4+ds-0ubuntu1 all          common files for the GTK graphical user interface library
ii  libgtk-4-media-gstreamer   4.10.4+ds-0ubuntu1 amd64        GStreamer media backend for the GTK graphical user interface library
ii  libgtk2.0-0:amd64          2.24.33-2ubuntu2   amd64        GTK graphical user interface library - old version
ii  libgtk2.0-bin              2.24.33-2ubuntu2   amd64        programs for the GTK graphical user interface library
ii  libgtk2.0-common           2.24.33-2ubuntu2   all          common files for the GTK graphical user interface library
ii  libgtk3-perl               0.038-3            all          Perl bindings for the GTK+ graphical user interface library

```

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Here is an image file that consistently breaks `darktable` in the way described above

[DSC48854.zip](https://github.com/darktable-org/darktable/files/13325768/DSC48854.zip)

**Comment by jenshannoschwalm** [comment]
Should be fixed in master.
