### ISSUE TITLE
Blocky mask artefacts when feathering (only with OpenCL)

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15621]
### Describe the bug

A follow-up to https://github.com/darktable-org/darktable/issues/14215 after https://github.com/darktable-org/darktable/pull/15612.

Import the following into darktable, open the images in the darkroom.

### Steps to reproduce

Import the following into darktable, open the images in the darkroom.

![black-dot2](https://github.com/darktable-org/darktable/assets/3177739/198e2443-7072-4517-bf51-ef3581f44f8e)
[black-dot2.png.xmp.txt](https://github.com/darktable-org/darktable/files/13325579/black-dot2.png.xmp.txt)

![dot2](https://github.com/darktable-org/darktable/assets/3177739/ce59f0ce-535d-4ec7-bc12-b9d1ebb7f60e)
[dot2.png.xmp.txt](https://github.com/darktable-org/darktable/files/13325620/dot2.png.xmp.txt)

### Logfile | Screenshot | Screencast

With OpenCL:

![image](https://github.com/darktable-org/darktable/assets/3177739/7a50b15b-56bd-40f4-9b84-2ff6aedfc682)

![image](https://github.com/darktable-org/darktable/assets/3177739/4774d0a8-a927-4941-b32c-908653ae7d08)

Without:
![image](https://github.com/darktable-org/darktable/assets/3177739/90a4cba4-78c8-41e0-a37a-3cfc78006acf)

![image](https://github.com/darktable-org/darktable/assets/3177739/ac01f541-006d-4b3c-8269-221441fbf5d3)

### Where did you install darktable from?

self-compiled from git master branch

### darktable version

`4.5.0+1137~gd72544e3fc` (and many others, the initial report used `3.7.0+1111~g2a83a6389`)

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Ryzen 5, 64 GB, NVidia 1060 / 6 GB, driver 525.147.05

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 / 6 GB, driver 525.147.05

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Occurs with clean config as well.

**Comment by s7habo** [comment]
I can not confirm this in Ubuntu 22.04 and the last master (4.5.0+1138~g8fa44f311):

![image](https://github.com/darktable-org/darktable/assets/38165484/942a0b0b-4ea7-4124-b9ea-4a89e9fb2d35)

![image](https://github.com/darktable-org/darktable/assets/38165484/1b686450-ea5b-4ac6-ab20-0dfcfeec9e91)

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-1028-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

**Comment by kofa73** [comment]
> I can not confirm this in Ubuntu 22.04 and the last master (4.5.0+1138~g8fa44f311):

Could you please try with my XMPs?

**Comment by s7habo** [comment]
> Could you please try with my XMPs?

With your XMP I also have artifacts. 

![image](https://github.com/darktable-org/darktable/assets/38165484/7f440268-72de-4c2e-ad76-7dbbad92f811)


They only occur with the _feathering radius_.  All other functions of the feathering guide seem to be without errors:

![image](https://github.com/darktable-org/darktable/assets/38165484/bc6084aa-5d59-492a-9cce-4f90ff14f0a5)

> Or use just one exposure, but set the feathering guide to any of the output options:

Yes, this also creates artifacts:

![image](https://github.com/darktable-org/darktable/assets/38165484/994a9337-2ac0-45dd-8860-1c130f1a1887)

**Comment by kofa73** [comment]
@s7habo : Thanks for confirming. I was beginning to think it was simply a curse placed on my PC. :-D

**Comment by jenshannoschwalm** [comment]
I can confirm too. On the track...
