### ISSUE TITLE
Compilador opencl (darktable-cltest.exe) no funciona con el mismo hardware desde la version 4.4.0 y posteriores.

### ISSUE THREAD

**Issue by Matueca** [darktable-org/darktable#15630]
### Describe the bug

Tengo un equipo con w10. procesador i5 4460, 12gb de ram y tarjeta gráfica Nvidia geforce  rtx 2060 con 12gb de memoria. Llevo varios años con esta configuración y trabajando con darktable sin problemas hasta las ultimas vesiones, (4.4.0 y posteriores). Al actualizar a la ultima, la 4.4.2, el programa dejó de usar la gráfica, ralentizando el programa un montón. Estoy hablando de minutos, uasando el modulo, por ejemplo, "difuso y nitido". Creyendo que era un fallo de las actualizaciones de windows 10 estuve investigando y probando soluciones durante días sin hallar ninguna. Instalé, desinstalé componentes una y otra vez sin encontrar solución alguna, hasta que me decidí a desinstalar darktable e instalar una versión antigua, con la cual el compilador  "darktable-cltest.exe" comenzo a trabajar bien de nuevo.  Fui probando versiones cada vez mas nuevas hasta llegar a la 4.2.1, siendo esta la que uso actualmente, ya que las siguientes no compilan bien y me dice que no tengo gráfica instalada. Personalmente creo que el error está en el compilador del kernel de las nuevas versiones, que por algún motivo no trabaja bien. Espero que esto sirva de ayuda a quien haya tenido mi mismo problema, y que este se solucione, por parte de los desarroladores. Muchas gracias por vuestra atención, y muy agradecido por todo lo que aportais. Atte
 Javier Bandera. (Matueca en GitHub)

### Steps to reproduce

El problema es la instalacion en si de dartable 4.4.0 y posteriores.
Con mi configuración opencl deja de funcionar.

### Expected behavior

Trabajar con la gráfica

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0 y posteriores

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)

### Describe your system?

 Time of this report: 11/11/2023, 19:20:43
             Machine name: DESKTOP-CJKHIPD
               Machine Id: {90F20CD0-FB27-44B7-A92D-1F463D004441}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: Z97-HD3
                     BIOS: BIOS Date: 07/31/15 13:12:45 Ver: 04.06.05 (type: BIOS)
                Processor: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 CPUs), ~3.2GHz
                   Memory: 24576MB RAM
      Available OS Memory: 24438MB RAM
                Page File: 6767MB used, 21253MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
---------------
Display Devices
---------------
           Card name: NVIDIA GeForce RTX 2060
        Manufacturer: NVIDIA
           Chip type: NVIDIA GeForce RTX 2060
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_10DE&DEV_1F03&SUBSYS_C7571462&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 24293 MB
    Dedicated Memory: 12075 MB
       Shared Memory: 12218 MB
        Current Mode: 3840 x 2160 (32 bit) (29Hz)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia geforce rtx 2060  Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_8f6c80ec02b538e6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_8f6c80ec02b538e6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_8f6c80ec02b538e6\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_8f6c80ec02b538e6\nvldumdx.dll  Driver File Version: 31.00.0015.4601 (English)       Driver Version: 31.0.15.4601          DDI Version: 12

**Comment by gi-man** [comment]
Maybe post the results from darktable-cltest

**Comment by victoryforce** [comment]
> Espero que esto sirva de ayuda a quien haya tenido mi mismo problema, y que este se solucione, por parte de los desarroladores. 

¿Entiendo correctamente que esto es sólo una historia y que no proporcionarás la información necesaria para que los desarrolladores comprendan cuál es el problema?

Si es así, cierro el informe de problemas.

Si se proporciona información, se puede reabrir el informe de problemas.

_Do I understand correctly that this is just a story and you will not provide the necessary information for the developers to understand what the problem is?_

_If so, I'm closing the issue._

_If information is provided, the issue may be reopened._
