### ISSUE TITLE
[FR] Revert to snapshot

### ISSUE THREAD

**Issue by Donatzsky** [darktable-org/darktable#15637]
Now that, if I understand it correctly, snapshots have their own history stack, I think having an option to revert to that state would be a very useful feature. It would also mean that snapshots work more like new users often expect them to.

In terms of UI, having a hamburger menu to the right of the snapshot seems like the best way to go. This can then also hold the rename option (which is currently not very discoverable) as well as delete and who knows what else.

**Comment by TurboGit** [comment]
I had thought about this when implementing the latest snapshot support, and definitely agree that having a way to revert to a given snapshot would be nice.

**Comment by ralfbrown** [comment]
Resolved by #16039
