### ISSUE TITLE
Some RAWs from Canon EOS 77D have pink / magenta highlights

### ISSUE THREAD

**Issue by jnerin** [darktable-org/darktable#15636]
### Describe the bug

Hello, as stated I noticed that some pictures had that pink / magenta highlights, I saw that the values in [rawspeed's cameras.xml](https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml#L727-L754) for 77D doesn't look very complete, so I took one picture at each ISO (100, 125, 160, 200, 250, 320, 400, 500, 640, 800, 1000, 1250, 1600, 2000, 2500, 3200, 4000, 5000, 6400, 8000, 10000, 12800, 16000, 20000, 25600, 51200), converted them to DNG and processed them with [dngmeta.rb](https://github.com/darktable-org/darktable/blob/master/tools/dngmeta.rb), the output blob is this:

```
invsensors {[511, 11892]=>[100, 125], [511, 10755]=>[160], [511, 14338]=>[200, 250], [2048, 10755]=>[320, 640, 1250, 2500, 5000], [2049, 14338]=>[400, 500, 800, 1000, 1600, 2000, 3200, 4000, 6400, 8000, 10000, 12800, 16000, 20000, 25600], [2041, 14338]=>[51200]}

sensors [[100, [511, 11892]], [125, [511, 11892]], [160, [511, 10755]], [200, [511, 14338]], [250, [511, 14338]], [320, [2048, 10755]], [400, [2049, 14338]], [500, [2048, 14338]], [640, [2048, 10755]], [800, [2049, 14338]], [1000, [2049, 14338]], [1250, [2048, 10755]], [1600, [2048, 14338]], [2000, [2048, 14338]], [2500, [2048, 10755]], [3200, [2048, 14338]], [4000, [2048, 14338]], [5000, [2048, 10755]], [6400, [2048, 14338]], [8000, [2049, 14338]], [10000, [2049, 14338]], [12800, [2049, 14338]], [16000, [2049, 14338]], [20000, [2048, 14338]], [25600, [2048, 14338]], [51200, [2041, 14338]]]
mostfrequent [[2049, 14338], [400, 500, 800, 1000, 1600, 2000, 3200, 4000, 6400, 8000, 10000, 12800, 16000, 20000, 25600]]
invsensors {[511, 11892]=>[100, 125], [511, 10755]=>[160], [511, 14338]=>[200, 250], [2048, 10755]=>[320, 640, 1250, 2500, 5000], [2041, 14338]=>[51200]}

        <Camera make="Canon" model="Canon EOS 77D">
                <ID make="" model="">Canon EOS 77D</ID>
                <Sensor black="2049" white="14338"/>
                <Sensor black="511" white="11892" iso_list="100 125"/>
                <Sensor black="511" white="10755" iso_list="160"/>
                <Sensor black="511" white="14338" iso_list="200 250"/>
                <Sensor black="2048" white="10755" iso_list="320 640 1250 2500 5000"/>
                <Sensor black="2041" white="14338" iso_list="51200"/>
        </Camera>
```

Please tell me if there's anything else that may be required.

### Steps to reproduce

Open some files with non-standard ISO, like 160, 640, 2500, 5000...

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/rawspeed/issues/417

**Comment by jnerin** [comment]
> See also [darktable-org/rawspeed#417](https://github.com/darktable-org/rawspeed/issues/417)

Thank you @kmilos , that looks like the best option, I assume the values I got are still good to merge in the interim, while the general solution is worked on.

I can create a PR for [rawspeed's cameras.xml](https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml#L727-L754) with the output I got from [dngmeta.rb](https://github.com/darktable-org/darktable/blob/master/tools/dngmeta.rb) if that speeds up a merge.
