### ISSUE TITLE
Canon 5D mk3 not recognized for tethering

### ISSUE THREAD

**Issue by cparadis777** [darktable-org/darktable#15646]
### Describe the bug

My Canon 5D MKIII isn't recognized by Darktable for tethering.

### Steps to reproduce

1. Connect powered off camera
2. Open darktable
3. turn on camera
4. Go to the tethering tab in Darktable

### Expected behavior

Darktable should recognize the camera for tethering

### Logfile | Screenshot | Screencast

[camctl.log](https://github.com/darktable-org/darktable/files/13335677/camctl.log)
[gphoto2_debug.log](https://github.com/darktable-org/darktable/files/13335678/gphoto2_debug.log)

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 39

### Describe your system?

16GB Ram, IntelCore I5-8350U x 8

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reproduced after a fresh install of Darktable and using both Gnome Store and DNF install of the software

**Comment by ralfbrown** [comment]
Darktable uses gphoto2 for tethering.  Does the standalone gphoto2 recognize your camera?  If not, there is nothing dt can do....

**Comment by cparadis777** [comment]
I was able to tether the camera using the troubleshooting steps found in the manual. I was able to take a test picture with the gphoto2 CLI.

**Comment by MStraeten** [comment]
was able to reproduce this with my R7 but just if not connecting the camera in the darktable GUI;)
So: did you connect the camera in darktable (and just forgot to mention that in your steps to reproduce)?
from the manual:
`After the USB cable is connected, go to the [import](https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/import/) module in the [lighttable](https://darktable-org.github.io/dtdocs/en/lighttable/) view. If your camera is available for use, a new section should appear in the import module containing the name of your camera and a “mount camera” button. Click this button to connect your camera and three additional buttons will appear: “copy & import from camera”, “tethered shoot” and “unmount camera”. Click “tethered shoot” to enter the tethering view. When you are finished, press the “unmount camera” button before physically disconnecting it.`

**Comment by shuttertux** [comment]
Hi there. I am experiencing the same difficulties with my Canon 5D mkII.
Xubuntu, DT 4.4.2 installed from Ubuntu(snap), gphoto2 installed afterwards separately.
Success in all troubleshooting steps in https://docs.darktable.org/usermanual/3.8/en/tethering/troubleshooting/
The import module in lighttable view does not show the additional buttons.

**Comment by ralfbrown** [comment]
> Xubuntu, DT 4.4.2 installed from Ubuntu(snap), gphoto2 installed afterwards separately.

The snap won't see the separately-installed gphoto2....  You would need to add it to the actual snap package, but I don't know how that would be done.

**Comment by shuttertux** [comment]
> The snap won't see the separately-installed gphoto2.... 

@ralfbrown : Great hint. Removed the snap Darktable instance, installed from the binary package prepared for my version of Ubuntu on the darktable.org and tethering works!

Thanks a lot!
