### ISSUE TITLE
MacOS lldb returns OpenCL Error not occuring outside lldb

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#15650]
if running darktable via lldb an OpenCl error is reported, that darktable -d common doesn't report outside lldb:
`2023-11-13 22:36:23.105606+0100 darktable[76362:4503429] [CL_INVALID_KERNEL] : OpenCL Error : Failed to release kernel! Kernel given is invalid!`

no crash, no abnormalities during editing, just that strange message

### Where did you install darktable from?

self compiled

### darktable version

darktable 4.5.0+1177~g4f66a1c8a8-dirty

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Sonoma

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1 Max

**Comment by jenshannoschwalm** [comment]
There is no dt check and possible error report for releasing a CL kernel yet, so nothing reported. Could be a double-release and the cl system reporting that ...

**Comment by jenshannoschwalm** [comment]
@MStraeten still valid?

**Comment by MStraeten** [comment]
not longer reproducible with recompiled kernels for 4.7.x
