### ISSUE TITLE
Detection of tag duplicates case insensitively

### ISSUE THREAD

**Issue by l0f4r0** [darktable-org/darktable#15666]
Hi,

**Is your feature request related to a problem? Please describe.**
It's not very efficient to manage what appears to me to be duplicated tags

**Describe the solution you'd like**
In tagging module, it would be nice to detect tag duplicates case insensitively

Thanks in advance for considering this feature request :)

**Comment by zisoft** [comment]
If I'm not mistaken, this will also be accomplished by #15696 ?

**Comment by zisoft** [comment]
Closed by #15696
