### ISSUE TITLE
The user may not know the reason if dt terminates due to a too new version of the database

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#15673]
A situation is possible when a user created (or updated) a database with a version of darktable that created a schema of a newer version, and then runs a darktable build that does not support such a new version.

For example, a user installed multiple releases of darktable (with different schema versions) and hoped to run them alternately. Or installed a development snapshot (and updated the base), and then wants to return to work with a stable release.

A user running the program from the OS desktop by clicking on the icon will not be able to see the error message printed on stdout. And on the Windows platform, even launching from the command line will not help, since all printing goes to the log file.

Therefore, in this case, we need to report the reason for the termination of the program in the GUI window.

**Comment by dterrahe** [comment]
The gui window is not (and won't be) open at that point, so `dt_gui_show_standalone_yes_no_dialog` has to be used (with only one string; "understood").

**Comment by victoryforce** [comment]
> so `dt_gui_show_standalone_yes_no_dialog` has to be used (with only one string; "understood").

Yes. This is exactly what I'm coding right now. Only "quit darktable" instead of "understood".

However, I did not understand why you wrote that the GUI window cannot be opened. But that might be because I'm already sleepy.

Ah, by GUI window you mean the main darktable interface? No, I was writing about outputting a message to the GUI as opposed to outputting to stdout.

**Comment by dterrahe** [comment]
> This is exactly what I'm coding right now. Only \"quit darktable\" instead of \"understood\".

Perfect! (The button text obviously depends on the explanation/main text, which i assumed already would say that darktable would close; I feel it is a bit mean to make the user "choose" to quit, when there is no other option :-) )

> GUI window you mean the main darktable interface?

That's what I thought _you_ meant. GUI vs just a dialog. But terms don't matter; we understand and agree on the solution.
