### ISSUE TITLE
Crash during opening

### ISSUE THREAD

**Issue by desman735** [darktable-org/darktable#15670]
### Describe the bug

Darktable crashes when trying to initialize OpenCL, happens every time. It might be connected with the driver version, updated the driver recently

### Steps to reproduce

Try to run bin\darktrable.exe

### Logfile | Screenshot | Screencast

[darktable_bt_7BCSE2.txt](https://github.com/darktable-org/darktable/files/13373844/darktable_bt_7BCSE2.txt)
[darktable_bt_F4XAE2.txt](https://github.com/darktable-org/darktable/files/13373848/darktable_bt_F4XAE2.txt)
[darktable_bt_UGPKE2.txt](https://github.com/darktable-org/darktable/files/13373849/darktable_bt_UGPKE2.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.0.1, 4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Describe your system?

DxDiag info:
[DxDiag.txt](https://github.com/darktable-org/darktable/files/13373991/DxDiag.txt)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 3080, driver version 546.17

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

More details on darktable version:
[version.txt](https://github.com/darktable-org/darktable/files/13374021/version.txt)
After that tried to update the version to 4.4.2:
[version.txt](https://github.com/darktable-org/darktable/files/13374204/version.txt)
It crashes there as well, but silently, here's relevant log files:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13374250/darktable-log.txt)
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13374225/darktable-log.txt)
Running with the empty config-dir did not help
Did not any changes related to lua scripts

**Comment by jenshannoschwalm** [comment]
Thus is a well known problem with windows activating multiple drivers. Fixed I master already

**Comment by jenshannoschwalm** [comment]
`PLATFORM NAME & VENDOR: OpenCLOn12, Microsoft`

That's the problem :-) Or more precise, you shall never enable that driver except there is no vendor supplied one. That's fixed in master so people on windows won't need to fiddle with disabling buggy drivers or make sure there is only one driver enabled per device.

**Comment by ptilopteri** [comment]
the offered solution was to ONLY USE ONE and you still have two.

**Comment by ptilopteri** [comment]
the offered solution was not the number of devices but the number of drivers.

you can disable opencl by starting dt from the commandline,
  darktable --help
  darktable --disable-opencl

or you can use "master" which solves the problem for you which was also advised.
