### ISSUE TITLE
segfault after opening image

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15680]
### Describe the bug

I opened an image and darktable crashed. I have been unable to reproduce this.

### Steps to reproduce

Open image in darkroom. I'll add more details and share an image if I can find a reliable way to reproduce this. Until then, I can only share the backtrace.
It was this image, but I don't know which sidecar:  https://tech.kovacs-telekes.org/files/dt-issue-15680-segfault/

### Logfile | Screenshot | Screencast

[darktable_bt_PO0CE2.txt](https://github.com/darktable-org/darktable/files/13399313/darktable_bt_PO0CE2.txt)

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+1219~geb2d8420a0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Ryzen 5 5600, 64 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 / 6 GB, driver 525.147.05

**Comment by jenshannoschwalm** [comment]
Thanks for reporting. Interesting as the log shows a OpenCL problem in a) colorbalancergb in tiling mode and b) the guided filter for the mask had to do a fallback to cpu. I remember some other people mentioning instability of that module - those reports were all on AMD so i looked into the code for "typical AMD issues like NaN issues".

Would you be able to share the image or at least the xmp? You could also send via email hanno@schwalm-bremen.de and i would remove that image after analysing...

Any special OpenCL config settings?

**Comment by kofa73** [comment]
Tiling and fallback -- that's interesting. It's a 10 MPx image, with a 6 GB Nvidia card, nvidia-smi showing 5 GB free. There is nothing special in the XMPs -- I'll add the shared files to the original report; unfortunately I cannot recall which version it was that I opened.
- My OpenCL scheduling profile is set to 'default'.
- I have a prio string forcing GPU-only processing: `+0/+0/+0/+0/+0`
- I have 'use all device memory' enabled.

I opened the photo pretty fast (started darktable; navigated to the directory; opened it). Thumbnails were all visible, but could it be that some background processing was still running because of the lighttable? I have 'generate thumbs in the background' enabled.

**Comment by jenshannoschwalm** [comment]
Feathering does require extra memory so the chance for tiling increases. A correction for that was added to master lately so you might have that not in your dt version.

Unlimited CL memory is pretty dangerous if you don't monitor your memory already used. With Firefox windows open it's adding some 100mb. You are sure your headroom is OK?

**Comment by kofa73** [comment]
I was on eb2d8420a0, which is quite recent. Thanks for the warning, I'll disable the 'use all memory' option.

**Comment by jenshannoschwalm** [comment]
My bet would be version 2 (the one with the mask in color lookup table) as that requires significantly more cl memory and i am not sure yet we take care of that while calculating mem requirements.

**Comment by jenshannoschwalm** [comment]
I think we can close this, checked clmem requirement of that module while processing and it was well above  what is allowed. Fixed via merged pr.
