### ISSUE TITLE
Panasonic DMC-GM1S not working in Lens Correction

### ISSUE THREAD

**Issue by JGSphaela** [darktable-org/darktable#15689]
Hi! I was going to file a issue for supporting the Panasonic DMC-GM1S but I saw #15265 and seems like it's been added. I download the newest AppImage and it does work! But the Lens Correction menu has no DMC-GM1S option, so I have to manually select DMC-GM1 to use it. I wonder if it's possible to add a alias there as well? Thanks a lot!

**Comment by kmilos** [comment]
Feel free to request it at https://github.com/lensfun/lensfun, this is out of scope for DT.
