### ISSUE TITLE
Styles menu is floating away from the pointer

### ISSUE THREAD

**Issue by beesyrupfactory** [darktable-org/darktable#15695]
### Describe the bug

The Styles menu is floating away from the pointer, making the UI a bit awkward to use.

### Steps to reproduce

1. Start darktable
2. Import a set of styles (I used [t3mujinpack](https://github.com/t3mujin/t3mujinpack) - specifically t3mujinpack_0.6.0_one-level.zip)
3. Import an image from the lighttable tab
4. Double click the image to enter into darkroom
5. From the bottom menu click on the Styles quick access menu

Actual behavior:
Some of the styles menu on the second and third level are floating. Also, related to #15694, not all menu options are shown for long lists exceeding 4 options as seen in the third level "t3mujinpack - Color Slide" menu option. The first level is fine.

### Expected behavior

darktable should align the context menu to the pointer

### Logfile | Screenshot | Screencast

Here's the second level and third level showing the styles menu opening away from the pointer:
![image](https://github.com/darktable-org/darktable/assets/86087525/492b1458-52ae-40d8-8bb8-7a3c92785e9b)
![image](https://github.com/darktable-org/darktable/assets/86087525/31dc2ba1-3184-4967-9741-732f37f95675)

The first level menu is working fine:
![image](https://github.com/darktable-org/darktable/assets/86087525/faeb3e2a-071c-4a0e-8f8f-13af9145fa6b)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

macOS Sonoma 14.1.1

### Describe your system?

MacBook Pro M1 Max 14-inch 2021 32GB

### Are you using OpenCL GPU in darktable?

No

**Comment by MStraeten** [comment]
there were several issues with gtk 3.24.37 used for the last official build. 
see  https://github.com/darktable-org/darktable/issues/14856#issuecomment-1657092082 for an arm build of 4.4.2 with gtk3 3.24.38

**Comment by beesyrupfactory** [comment]
Thanks @MStraeten for the build. I haven't used a RAW processing software since 2011 with Lightroom. The SaaS model turned me away from it, and I'm so happy to have found darktable. I love this project, and want to thank all of the creators and contributors for making such a good piece of software.
