### ISSUE TITLE
Collection filter by file name forgets to show the applied filter text after restart

### ISSUE THREAD

**Issue by victoryforce** [darktable-org/darktable#15701]
The title says it all.

To reproduce:

- Select a collection.
- Enter in the extension field of filename filter any extension that is not present in the collection. You'll get no thumbnails in the lighttable.
- Exit darktable and start again.
- Collection filtering will be preserved (you'll see no thumbnails), but the extension field will not show the extension entered before restart.

This is a rather harmful bug, since the user can't determine from the UI that filtering is active. To the user, it will look like there are no images in the collection.

Reproducible in Windows. I don't have a chance to check on Linux at the moment.

**Comment by zisoft** [comment]
cannot reproduce on macOS.
The entered text in the extension field is preserved and still there after restart.

<img width="343" alt="Bildschirmfoto 2023-11-21 um 21 46 29" src="https://github.com/darktable-org/darktable/assets/4083281/7f14128c-a9fd-46a7-ac1b-5b6b28e4f6f8">

**Comment by victoryforce** [comment]
Quite surprising, because it's hard to imagine what could be platform-dependent in the collection filter code. But in Windows, it is observed consistently.

**Comment by zisoft** [comment]
will try to reproduce on my Windows setup tomorrow

**Comment by gi-man** [comment]
I cannot reproduce it on Fedora 39 KDE 4.5.0~git1258.372dbabb

**Comment by zisoft** [comment]
Yes, I can reproduce on Windows.
The filter is still active but the entered text is not visible in the filter module:

![image](https://github.com/darktable-org/darktable/assets/4083281/7f62aa14-7c6d-4134-8e86-273375fe0b0a)

**Comment by victoryforce** [comment]
@zisoft and @gi-man Thanks for checking on macOS and Linux! This helped me to understand what could be platform dependent in this code and to quickly catch the bug.
