### ISSUE TITLE
segfault when dragging on background in zoomable lighttable

### ISSUE THREAD

**Issue by geraldgattringer** [darktable-org/darktable#15711]
### Describe the bug

In the zoomable lighttable view when dragging the background (not an image) darktable segfaults here: https://github.com/darktable-org/darktable/blob/594c98c90bb688f9bf849676969fa0776d14fc96/src/dtgtk/thumbtable.c#L1310

Observed on Ubuntu 23.04 compiled from source from current [nightly](https://github.com/darktable-org/darktable/commit/b12f92d5380cb708c1b66cca38b22aed465d4d1c). 

### Steps to reproduce

1. go to lighttable
2. select zoomable view
3. drag on the background

### Commit

2b3ccea

### Where did you install darktable from?

self compiled

### darktable version

 darktable-4.5.0+1264.gb12f92d538

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
I have reproduced this issue. Thanks @geraldgattringer! Will fix it soon.
