### ISSUE TITLE
AVIF export: resolution reduced to 72 dpi

### ISSUE THREAD

**Issue by silversurferarea** [darktable-org/darktable#15715]
### Describe the bug

Hi in the community,
using darktable in release 4.4.2 (flatpak kubuntu) it seems, that for export to AVIF format with following settings...
- 12 bit
- RGB color
- Tiling on
- compression lossless

global options:
- size in pixel (file)
- resampling yes
- profile sRGB
- prefix relative color
- style none
... the resolution cannot be changed to 300 dpi for the AVIF export file; it's always fixed to 72 dpi, independent of any changes in the global settings (size). 

Is that a specific problem based on the AVIF codec (because video codec) or a real bug in darktable?

Thank you so much for your response.
Best regards

### Steps to reproduce

Go to lighttable
Select a pic
define export settings for AVIF, 12bit, RGB color, tiling on, compression lossless
define global settings - size = in pixel (file), no specific pixel size selected, allow enlargement no, high quality resampling yes, (raster-mask is not feasible, when AVIF selected), color profile sRGB, prefix relative colorimetric, style none

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 22.04 LTS

### Describe your system?

Darktable installed within a flatpak package. AVIF codec installed within an gThumb installation. 

OpenCL settings are as standard installation (unchanged).

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Specific AVIF export problem, export in TIFF is fine (=300 dpi).

**Comment by MStraeten** [comment]
dpi is completely meaningless for image dimensions in darktable - if you're exporting e.g. 1920 pixels width, the resulting file will have these 1920 pixels.
if you're using the dpi setting to get proper pixelcount for printing, then the dpi value is just used to calculate the required pixel count for the export

**Comment by kmilos** [comment]
This could be because we have a limitation on handling Exif data for AVIF/EXR/JXL/XCF -  those formats are not supported by exiv2 for writing, so we can't have a second pass of Exif/XMP update after the file is created like we do for JPEG/PNG/TIFF, and as a result, some of the tags are probably at default/import values.

Unfortunately, not much dt can do here at this point.

**Comment by TurboGit** [comment]
DPI (dot per inch) is meaningful when there is some physical dimensions (inch, cm). When you export using size in pixel an image stored in disk what does dpi could mean?

An yes I know that Photoshop propose this option since long long time... I have yet to understand the meaning and many people seems confused because of this.

**Comment by ralfbrown** [comment]
Maybe we should include a pointer to https://www.rideau-info.com/photos/mythdpi.html somewhere in the docs....

**Comment by silversurferarea** [comment]
First of all, thank you for all your comments. I am aware of the insignificance of DPI for digital files and that the resolution only plays a role for print media. And here is the reason of my request.

Basically, the reduced resolution for AVIF export is not a problem for me at first. However, I am surprised that all other export formats generate 300 dpi with the Darktable standard settings, and AVIF does not. 

A changed export setting in the global export options (see attachment), related to printing (inches for printing), also only produces 72dpi. I would have expected real 300dpi here at the latest. 
![screen_exportAVIF_300dpi](https://github.com/darktable-org/darktable/assets/79654353/b9744a9c-58c4-4029-9056-b75d8848aa63)
![screen_exportAVIF_300dpi_fault](https://github.com/darktable-org/darktable/assets/79654353/def27721-bb40-484b-ba19-462558c81c1a)

I would like to switch to AVIF as the standard export for the entire workflow. The format offers enormous data storage savings with comparable image quality compared to the TIF used so far. However, a separate work step would then be necessary to increase the resolution from 72 dpi to 300 dpi, because in most cases the export results are then to be printed.

**Comment by kmilos** [comment]
See my explanation above again. There is a slight difference in export behaviour for AVIF/EXR/JXL/XCF when it comes to metadata.

**Comment by TurboGit** [comment]
> Maybe we should include a pointer to https://www.rideau-info.com/photos/mythdpi.html somewhere in the docs....

@elstoc : What about referencing this doc or adding a paragraph about this common misunderstanding in the dt doc that we could use as reference when replying to issues?

**Comment by parafin** [comment]
> I would like to switch to AVIF as the standard export for the entire workflow. The format offers enormous data storage savings with comparable image quality compared to the TIF used so far. However, a separate work step would then be necessary to increase the resolution from 72 dpi to 300 dpi, because in most cases the export results are then to be printed.

300 dpi sounds as random as 72 dpi. You haven’t actually explained the reason why DPI matters to you, surely it’s not about looking at metadata window? Maybe you could describe your workflow, I guess it involves printing?

**Comment by MStraeten** [comment]
> Basically, the reduced resolution for AVIF export is not a problem for me at first.

There’s no reduced resolution according to the second screenshot. Since you didn’t give a print size (width=heigth=0,00) you’re exporting all available pixels. 

if you don’t believe it, simply replace that 300 by an arbitrary other value… that number just matters if you’re entering a real print size.

**Comment by silversurferarea** [comment]
> See my explanation above again. There is a slight difference in export behaviour for AVIF/EXR/JXL/XCF when it comes to metadata.

Ok, I've understood.

> > ....because in most cases the export results are then to be printed.
> 
> 300 dpi sounds as random as 72 dpi. You haven’t actually explained the reason why DPI matters to you, surely it’s not about looking at metadata window? Maybe you could describe your workflow, I guess it involves printing?

Yes, selected images go to print (wall prints , some of them larger than 200cm in diameter).

I think I can make progress with the information.  So I would like to thank all the commentators for your input and support.
