### ISSUE TITLE
Make storage XMP/sidecar preferences more consistent

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#15727]
The preferences > storage tab currently has the following options:

![Screenshot_2023-11-25_13-40-16](https://github.com/darktable-org/darktable/assets/9555491/6c1ad984-e415-40a8-8753-682ced061ba9)

The first option refers to sidecar files and the remaining options refer to XMP files (as does the header). It would be better if we could agree on a consistent name. Perhaps "XMP sidecar files" is the best compromise?

**Comment by victoryforce** [comment]
I'd vote for just XMP.  Maybe let's add the word "sidecar" only in the corresponding tooltips? We tend to want short option labels with no additional details, expecting to see more verbose explanations in tooltips.

**Comment by elstoc** [comment]
Perhaps have "XMP sidecar files" as the header, then just "XMP" in the individual option descriptions?

**Comment by victoryforce** [comment]
> Perhaps have "XMP sidecar files" as the header, then just "XMP" in the individual option descriptions?

I love this idea!

**Comment by elstoc** [comment]
Cool, PR on the way...
