### ISSUE TITLE
segfault when entering darkroom

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15735]
### Describe the bug

I opened an image in the darkroom. I *think* I had made a snapshot from an image which I later deleted.
After a restart, the crash did not occur again.
We had a snapshot-related segfault recently, but that has been fixed. I tried to reproduce this (created a snapshot, removed the image, opened another), but there was no crash.

### Steps to reproduce

Unclear

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1294~g749a577100

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 / 6 GB, driver 525.147.05

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[darktable_bt_JJQGF2.txt](https://github.com/darktable-org/darktable/files/13464962/darktable_bt_JJQGF2.txt)

**Comment by TurboGit** [comment]
I'll try to understand what is going on, from the backtrace I see that we request an image in the cache having an ID of 0, this is wrong. But now I have to understand how a `snap->id` can have been set to 0.

**Comment by TurboGit** [comment]
Ok, understood, the scenario is:
- go to darkroom with an image
- create a snapshot
- select it
- go back to lighttable
- delete image used in darkroom
- enter lighttable

Here darktable crash as the snapshot is still selected but the image is removed. Fix coming in a moment.

**Comment by TurboGit** [comment]
@kofa73 : Thanks for reporting!

**Comment by kofa73** [comment]
This was such a quick fix that I first thought I sent an invalid report (e.g. a duplicate). :-D
Thanks!
