### ISSUE TITLE
Provide the ability to change timestamp format/localization

### ISSUE THREAD

**Issue by beesyrupfactory** [darktable-org/darktable#15730]
**Is your feature request related to a problem? Please describe.**
What I'm observing is that the timestamp is showing the datestamp with the character for Hour (時), minutes (分) and seconds (秒) as seen in the following image.

![image](https://github.com/darktable-org/darktable/assets/86087525/9d4752df-cec5-4069-9099-e2cb50f6cd3c)

Context: I have a unique setup on my Mac where I'm using the en-JP locale (English in Japan). It's a non-standard locale that Apple provides. The OS's country is set to Japan as I live here (hence JP), but my OS localization is set to English (en). (Not important, but the benefit of this localization--it's useful for Japanese place names, and names in addition to whatever en-US provides.)

**Describe the solution you'd like**
What I'm hoping to do is set the timestamp to use colons instead, so for example, 09:35:40. I'm fine with 24 hour time, but an AM/PM toggle might be useful, too, in addition to the date format (e.g., my locale's sets it as YYYY/MM/DD.)

**Alternatives**
I suppose I can change my OS region, but it seems like it might be simpler if I could override this. If there are any options for this that I missed in the documentation, please feel free to point me to it!

**Additional context**
N/A

Thank you!

**Comment by victoryforce** [comment]
What is the content of your `preferences > lighttable > pattern for the thumbnail tooltip` ? I'm guessing it contains `$(EXIF.DATE.REGIONAL) $(EXIF.TIME.REGIONAL)`. Just replace it with substitution variables with separate date and time elements, in the order you want and with the delimiters you want. See the link below.

> If there are any options for this that I missed in the documentation, please feel free to point me to it!

Yes, they are:
https://docs.darktable.org/usermanual/development/en/special-topics/variables/

**Comment by beesyrupfactory** [comment]
Hi @victoryforce,

Thanks so much for your response. I didn't know where to look, and you've found the exact variables I was looking for. Thanks for the documentation.

My original settings were as follows:
```<b>$(FILE_NAME).$(FILE_EXTENSION)</b>$(NL)$(EXIF.DATE.REGIONAL) $(EXIF.TIME.REGIONAL)$(NL)$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • $(EXIF_ISO) ISO```

**Comment by beesyrupfactory** [comment]
That did it! Thank you for the help @victoryforce.
![image](https://github.com/darktable-org/darktable/assets/86087525/a14be0bb-c000-44b2-99cf-649359a363d1)

Reference - replaced $(EXIF.TIME.REGIONAL) to $(EXIF.HOUR):$(EXIF.MINUTE):$(EXIF.SECOND)

`<b>$(FILE_NAME).$(FILE_EXTENSION)</b>$(NL)$(EXIF.DATE.REGIONAL) $(EXIF.HOUR):$(EXIF.MINUTE):$(EXIF.SECOND)$(NL)$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • $(EXIF_ISO) ISO`
