### ISSUE TITLE
Include white balance as part of copy and paste process for editing steps. 

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#15744]
When I do CTRL+SHIFT+C the white balance settings are not automatically included in the list of modules copied. I would regard this as a critical unit to copy when processing a series of images taken in a shoot. This feels like an oversight. Would it be an easy fix  to include white balance? I know others have commented on this as well.

**Comment by ralfbrown** [comment]
White balance is one of the modules which was explicitly omitted from the default 'all' selection because it varies from camera model to camera model even when set to a fixed value like "reference".  So including it by default leads to unpleasant surprises....

**Comment by gi-man** [comment]
This is not an oversight. It is explained in the manual and the way around it is with selective copy/paste.

https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/history-stack/#module-controls

**Comment by elstoc** [comment]
I agree and at the same time also disagree. The vast majority of users (I suspect) have only one camera and copy-paste between images from the same camera rather than between images from different cameras (or at least only process images from a single camera at a time). The exclusion of modules from copy/paste is great for preventing foot-shootery by inexperienced users but it would be nice for more experienced users to be able to take the training wheels off to save a bit of time.

It also remains really weird that "selective" copy is the only way to copy everything (and that the straight "copy" button is also selective but just doesn't advertise it)

**Comment by elstoc** [comment]
What might be even better is if we could detect the source and destination camera/lens and smartly copy modules depending on whether or not they differ.

**Comment by tpinfold** [comment]
I use this option when editing a series of shots taken in a single shoot. There would never be a time of switching cameras. It seems strange that WB copy is not allowed but the cropping is by default. Now cropping tends to be more per individual shot. By default I do selective copy and include WB and decide about cropping. It is not a huge problem to me, but despite the explanations given I still feel it would stream line the use of DT if WB was included by default. I am also really appreciative of the ability to do selective copy as it may be only some modules we want to copy.

**Comment by ptilopteri** [comment]
Is it that hard to remember that wb needs "selective".

fwiw: I have 4 bodies and rotate frequently between 2 or three on the same shoot and
would really *not* want wb to be copied to a different camera shots.

I'ts one of those habits one adopts to keep sane :)

**Comment by ptilopteri** [comment]
cannot recall ever copying "crop" across different camera shots.  I do between very similar shots from same body.  but I shoot action primarily.

**Comment by ptilopteri** [comment]
cannot recall ever copy/paste across bodies, cannot understand need.
since wb is not auto copied, doubt there would be a problem.  I believe
crop would be a problem as none of my bodies have same image size.

**Comment by ptilopteri** [comment]
mouse click :)

**Comment by ptilopteri** [comment]
I do use key combos for crop and straightening, not menu

**Comment by tpinfold** [comment]
I am confused. How do you do a mouse click for copying?

**Comment by gi-man** [comment]
What about a single copy and just two paste types (selective and all)? The selective is defaulted to the safe ones.
