### ISSUE TITLE
un-needed cache generation with "--library :memory:"

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#15749]
### Describe the bug

when starting dt with "--library :memory:" and importing a large collection, if dt is stopped/quit before generating the image cache, that generation continues and I believe it should not.

### Steps to reproduce

open dt with:   darktable --library :memory:
import a collection, 50 images or so
close darktable 

image cache generation continues.

### Expected behavior

generating image cache should stop

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1310~g368a50677

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed 20231124

### Describe your system?

openSUSE Tumbleweed 20231124 | Linux 6.6.2-1-default x86_64 | 12-thr Intel(R) Core(TM) i7 CPU 970 3193MHz | Load: 0.31 Tasks: 2452 | Mem: 13295/36068MB | Disk: 2913/17809GB | Gfx: @ 4480x1080

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

afaik, has been this way for quite some time.

**Comment by jenshannoschwalm** [comment]
That thumb generating job for images shown in light table is not aborted yet.

**Comment by jenshannoschwalm** [comment]
> if not, should not it cease if "--library :memory:" and dt is closed?

It was a statement :-) For information, if we have some thumbnails not developed and thus not valid while being in one of the lighttable modes we start some background jobs (4 if your system has enough resources) calculating them, these jobs do a thumbnail pixelpipe run, that is very difficult to intercept in a safe way to keep database and xmps correct.

So what you observe is those jobs finishing. We could reduce the number of jobs for your case with memory db but that would leave the UI less responsive. So overall i don't see a good way to solve this atm.

**Comment by ptilopteri** [comment]
thanks for the explanation.  if you see no solution, you can close this issue.  tks.
