### ISSUE TITLE
weird panning, when zoomed and using eyedropper for colorcalibration

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#15747]
### Describe the bug

I zoomed into a pic (100% and 200%) and used the eyedropper of colorcalibration. When the mouse, the picture is moving (panning). 

I saw similar behaviour on rotate and perspective, when manually drawing lines for keystoneing. I initially thought it is a feature...

@dterrahe can it be, this is also related to commit 135d5a6 or its parrents? (just a smell of somebody who cannot do the coding :slightly_smiling_face:  )

### Steps to reproduce

1) Go to darkroom
2) middle click to zoom e.g. 100% or 200%
3) use eyedropper of colorcalibration
4) pick an area, drag the mouse around and see

### Expected behavior

there should be no movement of the picture

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/49004103/550313c0-7332-467b-a3d1-60ab88646178

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0-1310-g368a506772

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

* darktable version : 4.5.0-1310-g368a506772
* OS                : Linux - kernel 6.6.2-gentoo
* Distro            : Gentoo Base System release 2.14
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-535.129.03
* OpenCL installed  : Yes (opencl-headers-2023.04.17)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.9
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.38
* gcc               : 13.2.1_p20230826
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

please see system description

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

not tried yet other versions of dt
only tried with RAW (ORF)
yes, it can be reproduced with discarded history
I didn't try with empty config yet

**Comment by AxelG-DE** [comment]
and here is the example with rotate and perspective (I assume when touching the lower border of the image, that pan is a feature, but see the other panning, when moving left to right or slightly up and down, the picture moves...):

https://github.com/darktable-org/darktable/assets/49004103/a29a73e3-0a76-4093-823d-090b458be0b1

**Comment by AxelG-DE** [comment]
I found it

it is related to the lens correction:
- Lens correction off, no issue
- Lensfun database, issue sometimes not noticeable sometimes just minor
- embedded metadata, issue is reproducible here

https://github.com/darktable-org/darktable/assets/49004103/f971e8e2-ed1a-4317-8652-f8bcbb4f93ee


@jenshannoschwalm as you also have an Oly and you also tested the #12760 .... can you reproduce?

@paolodepetrillo and @sgotti may I ping you here?

**Comment by AxelG-DE** [comment]
I have just tested with moved-away ~/.config/darktable but still pans
Next I will test #15739

**Comment by dterrahe** [comment]
The issue with lens correction seems to be that a round trip via `distort_transform`/`distort_backtransform` leads to greater rounding errors than "most" other modules. This may just be a property of the algorithm used. Or it may be that cumulative approximations are used that could be improved. If that could be done at little cost to calculation speed it would definitely be worth it.

**Comment by AxelG-DE** [comment]
@dterrahe 

I just tested #15739 and it improves tremendously but not fully gone. When releasing the mouse, the picture still jumps a bit...

https://github.com/darktable-org/darktable/assets/49004103/94b82499-a52f-4cd5-a285-f8e7d4ef987a

**Comment by jenshannoschwalm** [comment]
> The issue with lens correction seems to be that a round trip via `distort_transform`/`distort_backtransform` leads to greater rounding errors than "most" other modules. This may just be a property of the algorithm used. Or it may be that cumulative approximations are used that could be improved. If that could be done at little cost to calculation speed it would definitely be worth it.

I will have a look. But for nothing for 4.6

**Comment by AxelG-DE** [comment]
I anyway run master as daily driver :)

**Comment by dterrahe** [comment]
> When releasing the mouse, the picture still jumps a bit...

That is actually caused by the colorpicker updating the temperature slider and thereby causing a recalc. This recalc then leads to a check if repositioning is necessary (it might be, if the changed module were a rotation or other distortion) and that accumulated rounding errors by doing back and forward transforms. Even just moving the exposure up and down could cause small movement.

The latest update to #15739 now avoids storing the updated position (in RAW terms) if it hasn't visible changed in the currently displayed image. This avoids accumulation of rounding errors and I can't easily reproduce the bug anymore.

Please kindly test again.
