### ISSUE TITLE
tone equalizer stuck in "wait for the preview to finish computing"

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15743]
### Describe the bug

Clicking on tone EQ's auto-tune (exposure + contrast) buttons may result in the message "wait for the preview to finish computing". Normally, a subsequent click (after waiting a bit) succeeds. However, recently the module may get 'stuck': no matter how long one waits, the same message is displayed again and again.

One photo + sidecar: https://tech.kovacs-telekes.org/files/2023-11-26-toneeq-wait/
I'm not sure there's anything special in the history to trigger this. I have seen it with several images, and have not been able to figure out a pattern (history or user actions) to trigger this.

### Steps to reproduce

1. Click the auto-tune button
2. The message may appear
3. Once it disappears, click the auto-tune button again
4. The message may appear again, indefinitely.
5. Exit to the light table
6. Open the image again in the darkroom
7. Click the auto-tune button again. Most probably it will work now.

### Expected behavior

After a wait, the next click should result in the desired auto-tuning operation.

### Logfile | Screenshot | Screencast

The pointer switches to "? EV", the "wait for the preview to finish computing" message is displayed. It goes away after a while, but clicking the auto-tune sliders produces it again (10 MPx image, waited for several minutes):
![image](https://github.com/darktable-org/darktable/assets/3177739/d38fa272-1460-47a7-a1a9-62d1259e6468)

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+1309~gb1d268184e

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 / 6 GB, driver 525.147.05

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

OpenCL enabled/not does not matter.
Console log (I was stupid and did not take this immediately, so I'm not sure at what part is relevant). Active flags were ` -d opencl -d perf -d memory -d common -d tiling`, let me know if some others are needed.
[2023-11-15_07-36-21_P1020360.RW2.log](https://github.com/darktable-org/darktable/files/13466781/2023-11-15_07-36-21_P1020360.RW2.log)

**Comment by ralfbrown** [comment]
It looks like the improved caching is resulting in some variable(s) not being set.  The message is being triggered when either `luminance_valid` or `histogram_valid` in the module's GUI data are False, and the former at least is only set to True when the module's `process` function is called for the preview pipe.

**Comment by jenshannoschwalm** [comment]
@kofa73 i can't reproduce here so far. Could yo try to add
```
dt_iop_refresh_center(self);
```
to toneequal.c Line 641 for a test.

**Comment by kofa73** [comment]
So like this, before `refresh_preview`, right?

```c
  dt_iop_gui_leave_critical_section(self);
  dt_iop_refresh_center(self); // line 641
  dt_iop_refresh_preview(self);
```

**Comment by kofa73** [comment]
Short update: I have done very little editing lately (maybe this weekend...), but so far I have not had the issue with `dt_iop_refresh_center(self);` inserted as suggested. Could be due to the low usage, or to this being a genuine fix. I just wanted to let you know I have not forgotten about the issue.

**Comment by jenshannoschwalm** [comment]
Ok, I will check again and maybe do a pr if convinced

**Comment by kofa73** [comment]
Note: it still happens at times (I encountered it yesterday). Exiting to the lighttable and opening the image again in darkroom resolved the issue.
