### ISSUE TITLE
something wrong with the issue template

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#15748]
### Describe the bug

whenever clicking in one of the fields of a bug report, there is an overlay of "leave a comment" on top of our guidance...

before entering the box:
![grafik](https://github.com/darktable-org/darktable/assets/49004103/f51ebf0f-82e7-4c85-84c8-0ab69e9e4c30)

after entering the box
![grafik](https://github.com/darktable-org/darktable/assets/49004103/7ae2840f-acac-4c5c-ba17-c4aa6660d3d7)

@TurboGit something you could influence? Easy-fix, insert an empty line :-D 

### Steps to reproduce

please see above

### Expected behavior

n/a

### Logfile | Screenshot | Screencast

n/a

### Commit

n/a

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0-1310-g368a506772

### What OS are you using?

Linux

### What is the version of your OS?

gentoo

### Describe your system?

* darktable version : 4.5.0-1310-g368a506772
* OS                : Linux - kernel 6.6.2-gentoo
* Distro            : Gentoo Base System release 2.14
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-535.129.03
* OpenCL installed  : Yes (opencl-headers-2023.04.17)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.9
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.38
* gcc               : 13.2.1_p20230826
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

n/a

**Comment by gi-man** [comment]
Funny, an issue on the issue template. 

It's all over github with the same comments since they implemented this change. I will do a PR to add an empty row.
