### ISSUE TITLE
SONY ILCE-7CR

### ISSUE THREAD

**Issue by Nostroboy** [darktable-org/darktable#15764]
Hello team !

I just uploaded RAW files from my SONY ILCE-7CR on https://raw.pixls.us/. They are named:

DSC00794: RAW uncompressed Full frame - 3:2
DSC00795: RAW Losseless Comp (L) Full frame - 3:2
DSC00796: RAW Losseless Comp (M) Full frame - 3:2
DSC00797: RAW Losseless Comp (S) Full frame - 3:2
DSC00798: RAW Compressed Full frame - 3:2

DSC00799: RAW Compressed APS-C crop - 3:2
DSC00800: RAW Losseless Comp (S) APS-C crop - 3:2
DSC00801: RAW Losseless Comp (M) APS-C crop - 3:2
DSC00802: RAW Uncompressed APS-C crop - 3:2

Copyright under CCO

Shot with a Sigma 24-70mm F2.8 DG DN | Art at 50mm

**Comment by kmilos** [comment]
Thank you for the samples!

See https://github.com/darktable-org/rawspeed/pull/537
