### ISSUE TITLE
dt 4.5 loop when switching in darkroom between particular images from filmstrip

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#15771]
### Describe the bug

I am testing dt weekly build of November 26th “4.5.0+1308~gb15765654a” for Windows, downloaded from Bill Ferguson’s link here “https://discuss.pixls.us/t/darktable-windows-insider-program-11-26/40647” .
When switching from MAC41091.RAF to a duplicate of the original of MAC41094.RAF the central view doesn’t appear any further and the GPU gets into a loop (100% occupied).

### Steps to reproduce

[MAC41091.zip](https://github.com/darktable-org/darktable/files/13492821/MAC41091.zip)
[MAC41094.zip](https://github.com/darktable-org/darktable/files/13492822/MAC41094.zip)
I attach these 2 raw files and their XMP files. 
1.	Import MAC41091.RAF and MAC41094.RAF and their XMP files
2.	Open MAC41094 in the darkroom
3.	Duplicate the original of MAC41094
4.	Select MAC41091 in the filmstrip to open
5.	Now select the duplicate of MAC41094
6.	Central view is not opening and the GPU goes into a high load.

### Expected behavior

The central view should appear and no loop to expect.

### Logfile | Screenshot | Screencast

If this cannot be reproduced using my 2 included pictures, then please let me know the command line to start darktable, including parameters and switches, to obtain a relevant logfile.

### Where did you obtain darktable from?

an online forum

### darktable version

“4.5.0+1308~gb15765654a”

### What OS are you using?

Windows

### What is the version of your OS?

Microsoft Windows 11 Pro

### Describe your system?

Microsoft Windows 11 Pro     10.0.22621 Build 22621
Computer/laptop MSI P65 Creator 9SG
Processor Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, 2301 MHz, 8 core('s), 16 threads
BIOS American Megatrends Inc. E16Q4IMS.318, 18/05/2020
RAM	32,0 GB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Geforce RTX 2080 with Max-Q – 8 GB - NVIDIA Studio Driver 546.01

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

If this cannot be reproduced using my 2 included pictures, then please let me know to command line to start darktable, including parameters and switches, to obtain a relevant logfile.

**Comment by wpferguson** [comment]
I tested on a CPU only Win 10 VM and it was slow, and went to 100%, but it didn't hang.  I just had to wait for it to catch up.

What is your system resource setting (in the settings->processing) set to.  If it's set to large, I'd set it to default and try again.  You may simply be running out of GPU memory which then forces things to just run on the CPU.

You can check by running darktable from the command line with the `-d perf -d opencl -d memory` flags

**Comment by gi-man** [comment]
I just tried on my windows build (4.5.0+1328~g0b2d4ade8e) and cannot reproduce. Win11, Ryzen 5700X, Nvidia 3060 12GB 546.17

Can you post (via pastebin or similar) darktable-cltest and then via command line darktable -d common ?

The logfile is at this location (type it in the explorer bar), https://www.darktable.org/about/faq/#faq-windows-logs .

**Comment by cabuy** [comment]
@gi-man @wpferguson 
Further tests:
With the darktable resources on default instead of large: looping.
With the opencl “use all device memory” thicked or non thicked: looping
When I run it in the CPU only, no loop.
Attached the logfile with the -d common switch. I am not sure it is relevant since I have to kill dt using the task manager.
Any further suggestions ?
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13493442/darktable-log.txt)

**Comment by cabuy** [comment]
It's late evening here in Europe. I'll see your reaction tomorrow. Thank you.

**Comment by cabuy** [comment]
OK just 2 more tests here. 

1. Switching from MAC41091 to the original of MAC41094 requires often scrolling the mouse wheel down for having the MAC41094 to appear.

2. Switching off the cropping on the original MAC41094 (not the duplicate) then it also loops when switching from MAC41091 to the original of MAC41094.

@dterrahe : is nb 1 related to my earlier issue #15648, since I have to scroll down the mouse wheel for the central view to appear ?

**Comment by wpferguson** [comment]
@cabuy try setting your resources to small.

**Comment by gi-man** [comment]
13,0497 [dt_opencl_check_tuning] use 7791MB (headroom=ON, pinning=ON)  I'm not sure why pinning is on. We removed those options for 4.6. Maybe if you had a previous version of dt with it ON, then it could still be on in the darktablerc file.  Check your darktablerc for these settings:

```
opencl_mandatory_timeout=2000
opencl_scheduling_profile=very fast GPU
opencl_synch_cache=active module
opencl_tune_headroom=FALSE
opencl_tuning_mode=nothing
```

> I am not sure it is relevant since I have to kill dt using the task manager.

Can you explain this part? How long do you wait before killing dt?

**Comment by jenshannoschwalm** [comment]
```
13,0497 [dt_opencl_check_tuning] use 7791MB (headroom=ON, pinning=ON)
```

We have removed the pinned-transfer from the gui but if there are some device specific setting manipulated by the user it's still available and done. 

This is the "interesting" part of the log
```
    17,5586 pixelpipe starting CL      [full]                                  (-2147483648/   0) 1317x 876 scale=0,2183 --> (-2147483648/   0) 1317x 876 scale=0,2183 device=0 (nvidiacudanvidiageforcertx2080withmaxqdesign)
    17,5588 modify roi IN              [full]           lens                   (   0/  13) -2069814912x 848 scale=0,2183 --> (-2147483648/   0) 1317x 876 scale=0,2183 
    17,5588 modify roi IN              [full]           demosaic               (   0/  57) -2147483648x3883 scale=1,0000 --> (   0/  13) -2069814912x 848 scale=0,2183 
    17,5588 modify roi IN              [full]           highlights             (   0/   0) 6032x4014 scale=1,0000 --> (   0/  57) -2147483648x3883 scale=1,0000 
    17,5588 modify roi IN              [full]           rawprepare             (   0/   0) 6048x4038 scale=1,0000 --> (   0/   0) 6032x4014 scale=1,0000 
    17,5588 pixelpipe data: full       [full]                                  (   0/   0) 6048x4038 scale=1,0000 --> (   0/   0) 6048x4038 scale=1,0000 
    17,5685 pixelpipe process CL       [full]           rawprepare             (   0/   0) 6048x4038 scale=1,0000 --> (   0/   0) 6032x4014 scale=1,0000 IOP_CS_RAW
    17,5755 pixelpipe process CL       [full]           temperature            (   0/   0) 6032x4014 scale=1,0000 --> (   0/   0) 6032x4014 scale=1,0000 IOP_CS_RAW
    17,5822 pixelpipe process CL       [full]           highlights             (   0/   0) 6032x4014 scale=1,0000 --> (   0/  57) -2147483648x3883 scale=1,0000 IOP_CS_RAW
    17,5893 opposed chroma CL          [full]           highlights             (   0/   0) 6032x4014 scale=1,0000 --> (   0/  57) -2147483648x3883 scale=1,0000 red: 0,0000, green: 0,0000, blue: 0,0000 for hash=dc02cb9b2ba39ae2, saved to cache, unclipped

```

The parameters while starting the pipe are simply bad and thus lead to excessive processing.

**Comment by jenshannoschwalm** [comment]
@dterrahe maybe you have an idea here? I think there is something wrong in develop.c at this part
```
  const int wd = MIN(window_width, scale * pipe->processed_width);
  const int ht = MIN(window_height, scale * pipe->processed_height);
  const int x = port ? MAX(0, scale * pipe->processed_width  * (.5 + zoom_x) - wd / 2) : 0;
  const int y = port ? MAX(0, scale * pipe->processed_height * (.5 + zoom_y) - ht / 2) : 0;

  dt_get_times(&start);
  if(dt_dev_pixelpipe_process(pipe, dev, x, y, wd, ht, scale))
```

**Comment by cabuy** [comment]
Dear @wpferguson , @jenshannoschwalm , @gi-man and @dterrahe ,
I want to thank you for already looking into my issue and the advice about the darktablerc settings. 
But I have also done a few more tests:
The result is that while my darktablerc settings are (were ?) probably awkward, the setting of the LENS CORRECTION METHOD on “embedded metadata” will RESULT in the LOOP.
I am adding my darktablerc file like it was for TEST E below.
Please read about my tests and advise the parameter making darktable logging data that are helpful for further analysis.
TEST A
1.	Delete darktablerc and startup darktable
2.	darktable creates darktablerc
3.	NO loop occurs when switching from MAC41091 to MAC41094 in the filmstrip of the darkroom
4.	Leaving darktable and startup again
5.	LOOP again when switching from MAC41091 to MAC41094 in the filmstrip of the darkroom
TEST B
1.	Kill looping darktable and restart
2.	In LENS CORRECTION MODULE choose correction method “Lensfun database” for image MAC41094 
3.	Now NO LOOP occurs when switching from MAC41091 to MAC41094 in the filmstrip of the darkroom
4.	Though I need to scroll the mousewheel down for the central image to appear
5.	Leaving darktable
TEST C
1.	Re-installing the ALWAYS USED darktablerc file 
2.	Starting darktable and verifying whether LENS CORRECTION METHOD is on “Lensfun database” for MAC41094
3.	Now NO LOOP occurs when switching from MAC41091 to MAC41094 in the filmstrip of the darkroom
4.	Though I need to scroll the mousewheel down for the central image to appear
5.	Leaving darktable
TEST D
1.	Updating the ALWAYS USED darktablerc file as per gi-man’s advice
2.	Starting darktable and verifying whether LENS CORRECTION METHOD is on “Lensfun database” for MAC41094
3.	Now NO LOOP occurs when switching from MAC41091 to MAC41094 in the filmstrip of the darkroom
4.	Though I need to scroll the mousewheel down for the central image to appear
TEST E
1.	Updating the LENS CORRECTION METHOD is on “embedded metadata” for MAC41094
2.	LOOP again when switching from MAC41091 to MAC41094 in the filmstrip of the darkroom

**Comment by cabuy** [comment]
[darktablerc.txt](https://github.com/darktable-org/darktable/files/13499625/darktablerc.txt)

I am adding my darktablerc file like it was for TEST E below.

Thank you in advance for your further help/advice,
Marc.

**Comment by dterrahe** [comment]
> maybe you have an idea here? I think there is something wrong in develop.c at this part

I (we all, probably) suspect this could be a side effect of #15739 (I warned we might skip some necessary updating 😜)
I'm not sure if you are both talking about the same issue, but @jenshannoschwalm could you please test if changing
https://github.com/darktable-org/darktable/blob/65f09145e545d8c29dc84bbd84519ffe36c6f012/src/develop/develop.c#L395
to
`dt_dev_zoom_move(port, DT_ZOOM_MOVE, 0.0f, TRUE, 0.0f, 0.0f, TRUE);`
addresses your concern? `pipe->processed_width/height` should _always_ be updated when changing images, but we now might be inadvertently skipping that when the zoom levels haven't changed. This change would force it and possibly prevent a few unnecessary recalculations.

Not at all sure that would solve @cabuy's problem but I know he can't test until this lands in the nightly. It feels to me like the need to scroll to see an update might be cured by this change, but that getting stuck in a loop might not.

**Comment by cabuy** [comment]
I found another pair of pictures with the same issue. Switching in the darkroom filmstrip from MAC32755 to MAC32783 with the latter on lens correction method “embedded metadata” results in a similar loop. Changing the lens correction method to “Lensfun database” and it works fine, except that I have to turn the scroll wheel down to visualize MAC32783. Perhaps try with this pair to reproduce the issue.  Since one of the zipped RAW files istoo large, I made them available for the next 7 days in WeTransfer under this link: https://we.tl/t-0sSXxIbhd8

**Comment by jenshannoschwalm** [comment]
> This change would force it and possibly prevent a few unnecessary recalculations.

I tried to see where/how `pipe->processed_width/height` are defined here, don't spot it. In
```
const int x = port ? MAX(0, sc ....
```
we 1) take them for granted and b) why can x be smaller than zero? Missing cast in MAX?

**Comment by cabuy** [comment]
@dterrahe @wpferguson @jenshannoschwalm @gi-man 👍
The crossing out in my comment hereabove is occurring due to the character string of the dt built version. So ...
 ... this LOOP issue is SOLVED, also the issue of requiring to SCROLL MOUSE WHEEL DOWN is SOLVED.
I can't judge what has changed in the code since the weekly build of November 26th, but it can be closed.
A big thank you to all,
Marc.
