### ISSUE TITLE
Mouse hover focus Image change on row-change

### ISSUE THREAD

**Issue by londeril** [darktable-org/darktable#15780]
### Describe the bug

Hello all,
Introduction

Longtime Lightroom Classic user here - I've only very recently looked into Darktable and I'm currently in the process of switching over to it because I love the image pipeline that much going back to Lightroom to try things out feels "stale" and quite "limiting" - so first of all THANKS to everyone who is or has written code for this amazing project!
The issue

I've been searching around the interwebs and this github because I found the "Act-on-hover" thing DT does quite disorienting. I understand the logic behind it and I can see the benefits of it (I'm a "focus follows mouse" guy since forever) so I can get my head around the fact that the mouse hover selects an image (though I'd still prefer it to be an option to turn this off and have "normal" click to select functionality).
BUT - the "Act-on-hover" gets very weird and I think even "workflow impeding" when using the arrow keys to navigate the Lighttable view. The way I like to use the Lighttable is to have rather big thumbnails for a quick overview in my culling process and use the arrow keys to select the next image or go back to the previous one. this works fine as long as the Lighttable view stays "on the same page" as soon as the images get "pushed up" (or down) to make room for the next row - and the mouse hovers over an image (like in the middle of the screen) that image gets selected and pressing the arrow keys will select the next image starting from there... this is very confusing... and now that I write it down I realize that it's also quite hard to show in text... so I made a screen capture off it (with sample images to for privacy concerns, naturally):
https://streamable.com/ze5n3g

This can be mitigated by simply moving the mouse out of the Lighttable (over a module, or over the window decoration) but I feel like this should not be necessary.

Yeah... well... in the end I just wanted to add this to the conversation - forgive me if that has been discusses before - this issue has been open for a long time, I see ;)

### Steps to reproduce

1. Have Lighttable open with more images than the screen can display at once
2. Select a image in the center of the screen and leave the mouse pointer there
3. advance the the next image(s) using the arrow keys
4. when Darktable shifts the content of the Lighttabe up (or down) to display a new row of images the image under the mouse gets focused
5. using the arrow keys again will start from that newly selected image

### Expected behavior

darktable should disregard the mouse hover and just continue to the next image after (or before) the one that was previously selected

### Logfile | Screenshot | Screen-cast

screencast: https://streamable.com/ze5n3g (I don't know how long this will stay up... please comment if this link becomes unavailable and I'll re-upload to another platform)

### Commit

Flatpak from Flathub

### Where did you obtain darktable from?

flatpak

### darktable version

4.2.2

### What OS are you using?

Linux

### What is the version of your OS?

OpenSUSE Tumbleweed and Fedora 39

### Describe your system?

Two systems:
Dell XPS 13 with Xe Graphics (OpenSuse Tumbleweed) - Plasma - Wayland
Gaming-PC (AMD Ryzen 9 3900X, Nvidia RTX 3060-Ti) - Plasma - X11

### Are you using OpenCL GPU in darktable?

Yes (Nvidia) - No (Intel)

### If yes, what is the GPU card and driver?

Fedora 39 packaged Nvidia driver

**Comment by Nilvus** [comment]
That is a long time issue (and controversial one). See #6025. I so close as it's a duplicate. If needed I could reopen but better to continue discussion and push to change that on related issue.

**Comment by Nilvus** [comment]
Reopen, just see answers on related issue after.

**Comment by ralfbrown** [comment]
Please put any continued discussion on #16850.
