### ISSUE TITLE
lens correction broken for Pentax KP and DA*16-50 PLM in DT 4.4.2 en 4.5.0

### ISSUE THREAD

**Issue by bjornlinzer** [darktable-org/darktable#15782]
### Describe the bug

Lens correction module does not find Pentax KP anymore, though it is mentioned in the meta data. This was not the case
 in 4.4.1. 
The 16-50mm PLM lens is not recognized anymore in the .deb versions of 4.4.2 en 4.5.0. Flatpak version of 4.4.2 recognizes both camera and lens. But that version does not support OpenCL...
The database on lensfun website does mention the lens as supported.

![lens correction module](https://github.com/darktable-org/darktable/assets/152430294/2dacbbf0-8405-4e87-84fd-0033bdbe3f1a)

![metadata](https://github.com/darktable-org/darktable/assets/152430294/c802993c-18d9-48d0-a41c-281d048454c7)

### Steps to reproduce

import a pentax raw file
open the file
look at the lens correction module and try to find Pentax KP and DA*16-50 PLM
look at the meta data

### Expected behavior

import meta data of both camera and lens, and use them as an input for automatic lens correction

### Where did you obtain darktable from?

OBS

### darktable version

4.5.0~git1360.a3df4f0b-1+10987.1

### What OS are you using?

Linux

### What is the version of your OS?

pop os 22.04

### Describe your system?

Thinkpad P53, 32GB RAM, Nvidia Quadro 2000, core i7, X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia Quadro 2000, 345.29.06

**Comment by kmilos** [comment]
Np. For future reference, [please seek user support on the forum first](https://discuss.pixls.us/c/software/darktable/19) before establishing whether there is a real issue with the dt code.
