### ISSUE TITLE
compiling master failing when linking on Ubuntu 23.10

### ISSUE THREAD

**Issue by jbinpg** [darktable-org/darktable#15797]
### Describe the bug

Compiling from master with all dependencies except portmidi satisfied. gmake is bombing as shown here:

58%] Linking C executable darktable
/usr/bin/ld: libdarktable.so: undefined reference to `uregex_matches_72'
/usr/bin/ld: libdarktable.so: undefined reference to `ucol_open_72'
/usr/bin/ld: libdarktable.so: undefined reference to `ucol_close_72'
/usr/bin/ld: libdarktable.so: undefined reference to `ucol_strcoll_72'
/usr/bin/ld: libdarktable.so: undefined reference to `uregex_open_72'
/usr/bin/ld: libdarktable.so: undefined reference to `uregex_close_72'
/usr/bin/ld: libdarktable.so: undefined reference to `uregex_setText_72'
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/CMakeFiles/darktable.dir/build.make:196: bin/darktable] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2596: bin/CMakeFiles/darktable.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

Unsure if this is a failure in my build environment, a bug in cmake, or a bug in darktable.

### Steps to reproduce

Build using the recommended commands.

### Expected behavior

Compile should finish cleanly.

### Where did you obtain darktable from?

self compiled

### darktable version

master as of 20231130

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

CPU: 12-core AMD Ryzen 9 3900XT (-MT MCP-) speed/min/max: 2649/2200/4776 MHz
Kernel: 6.5.0-13-generic x86_64 Up: 17h 13m Mem: 4.04/62.69 GiB (6.4%)
Storage: 35.01 TiB (36.3% used) Procs: 556 Shell: Bash inxi: 3.3.29

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Lua scripts compiled from vendor-supplied liblua5.4-dev.

**Comment by TurboGit** [comment]
Have you purged the build directory first?

**Comment by kmilos** [comment]
These are icu library symbols. Perhaps some missing devel package after update, or packaging error?

**Comment by jbinpg** [comment]
Thanks, all libicu files are available and downloaded. It does look like a local problem, though. Will investigate further.

**Comment by jbinpg** [comment]
Re-installed Ubuntu 23.10 and manually downloaded all dependencies. Compile completed successfully. Something was obviously borked. Issue closed.
