### ISSUE TITLE
Collections widget sometimes shows wrong section of the scrollable list 

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15793]
### Describe the bug

I wonder if this is really a bug in dt or something else, but I thought I'd raise it as we are in the 4.6 bugfixing phase. I have a rather long filmroll list in the collections widget and as I can't sort it the other way around anymore (that's another issue here https://github.com/darktable-org/darktable/issues/15669) the new filmrolls are at the bottom. 

When working on images for a while, sometimes the widget shows the top of the list and as soon as you click into the widget the proper content is shown. This has confused me several times now, yet it's hard to tell what exactly is triggering this.

### Steps to reproduce

- Scroll to the bottom of the collections widget using filmrolls
- Work on images
- Sometimes the widget shows the top of the list until you click into it

### Expected behavior

darktable should not change the content of the collections widget

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.5.0+1372~ga28c3f5eb9

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux, latest updates

### Describe your system?

64 GB RAM, AMD Ryzen 9

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD 6700 XT, ROCM 5.7.1

**Comment by elstoc** [comment]
Yes I've seen this on darktable 4.4.2 as well. Hard to reproduce consistently though.

**Comment by piratenpanda** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/14836
