### ISSUE TITLE
Ellipse figure mask does not save position when compressing history stack

### ISSUE THREAD

**Issue by arturoisilvia** [darktable-org/darktable#15808]
### Describe the bug

Ellipse figure mask does not save position when compressing history stack
It only happens with ellipse. With circle it works fine

### Steps to reproduce

1) Set an ellipse mask 
2) Compress the history stack
3) Without moving the ellipse position, move only the size and/or opacity handles.
4) Compress the history stack

The ellipse figure returns to its previous state.

### Expected behavior

The ellipse figure should retain the last movement

### Commit

gb9edf6897a

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.5.0+1392.gb9edf6897a

### What OS are you using?

Windows

### What is the version of your OS?

windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
Can you check #15809? TIA.

**Comment by TurboGit** [comment]
@arturoisilvia : I'm now merging the PR as I really want to get some field testing. Hope you'll be able to check master.

**Comment by arturoisilvia** [comment]
> @arturoisilvia : I'm now merging the PR as I really want to get some field testing. Hope you'll be able to check master.

I have just checked it. Now it works perfectly.
Thank you.
