### ISSUE TITLE
not enough saturation in image when shown in darkroom

### ISSUE THREAD

**Issue by pbeyens** [darktable-org/darktable#15804]
### Describe the bug

Saturation of the colors of imported images (jpg or raw) not shown correctly in darkroom.
When exporting the image from DT, the saturation is correct again (I first thought it was an export issue).
OpenCL on/off -> no difference.
Also does not seem be to color-profile (input/output) related.

Only 'active' pipeline in case of jpg is: input color profile, orientation, output color profile. Playing with configuration of those modules does not seem to solve it.

Issue found in 4.4.2 (latest stable) as well as in git master package.

### Steps to reproduce

- import an image (jpg or raw) and load it an image in darkroom
- color-saturation of the shown image is incorrect -> not enough in comparison with other viewers such as gThumb or RawTherapee

### Where did you obtain darktable from?

distro packaging

### darktable version

4.5.0~git1392.b9edf689-1+11008.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

Nvidia GPU but opencl enabled/disables makes no difference.

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment]
what exactly is the issue? ‚Not enough‘ is depending on expectations so please give a sample and something to reproduce.
What are your darktable settings?

**Comment by ralfbrown** [comment]
My guess is an incorrect screen profile, since the OP says that the image is OK on export, just not when editing in dt.

**Comment by pbeyens** [comment]
> what exactly is the issue? ‚Not enough‘ is depending on expectations so please give a sample and something to reproduce. What are your darktable settings?

It is in comparison with opening the same jpg in RawTherapee or gThumb. So, darktable shows less saturation in comparison with RT or gThumb. It is relative to.

Color profiles -> tried a lot but no difference.

Attached are 2 screenshots where gThumb is compared to RT and DT. You can clearly see the difference.
You can see the pipeline in DT.

![Screenshot from 2023-12-02 10-18-02](https://github.com/darktable-org/darktable/assets/439197/5d3d0626-c134-46e7-9582-b8e662b68266)
![Screenshot from 2023-12-02 10-18-43](https://github.com/darktable-org/darktable/assets/439197/3c8e6fb8-2ded-4887-85e9-243de1ad7e0e)

**Comment by pbeyens** [comment]
> @pbeyens Please attach the output of darktable-cmstest (found in the same directory as darktable). Watch out for the last line. Fix your setup if it's not `Your system seems to be correctly configured`, but something like:
> 
> ```
> Better check your system setup
>  - <description of problem>
> You may experience inconsistent color rendition between color managed applications
> ```
> 
> For me:
> 
> ```
> kofa@eagle:~/darktable-master/bin$ ./darktable-cmstest 
> darktable-cmstest version 4.5.0+1391~g0a39901aa5
> this executable was built with colord support enabled
> darktable itself was built with colord support enabled
> 
> primary CRTC is at CRTC 0
> CRTC for screen 0 CRTC 1 has no mode or no output, skipping
> CRTC for screen 0 CRTC 2 has no mode or no output, skipping
> CRTC for screen 0 CRTC 3 has no mode or no output, skipping
> 
> DP-2    the X atom and colord returned the same profile
>         X atom: _ICC_PROFILE (968116 bytes)
>                 description: U2720Q #1 2023-09-13 12-10 D5000 2.2 M-S XYZLUT+MTX
>         colord: "/home/kofa/.local/share/icc/U2720Q #1 2023-09-13 12-10 D5000 2.2 M-S XYZLUT+MTX.icc"
>                 description: U2720Q #1 2023-09-13 12-10 D5000 2.2 M-S XYZLUT+MTX
> 
> Your system seems to be correctly configured
> ```
> 
> What does RawTherapee's _Preferences/Color Management_ screen show? ![image](https://private-user-images.githubusercontent.com/3177739/287432534-b8d8d26a-9827-44c9-a852-581cc5e194a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDg2MDUsIm5iZiI6MTcwMTUwODMwNSwicGF0aCI6Ii8zMTc3NzM5LzI4NzQzMjUzNC1iOGQ4ZDI2YS05ODI3LTQ0YzktYTg1Mi01ODFjYzVlMTk0YTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDkxMTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDYzNDlkMzU5MGUyNDVjNDYzNjhiNTAzZTQyM2RkMmNiMWIyNzI1YThmZmI5OGM1NGE2OTlmNGYwM2M5NTA1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FFHLkjiET2o3h6el5FDgD_4AHGg-WgpUwuOw-5B-M24)
> 
> I assume you use xorg, not Wayland, is that right?

```
pbeyens@pc:~$ darktable-cmstest 
darktable-cmstest version 4.5.0~git1392.b9edf689-1+11008.1
this executable was built with colord support enabled
darktable itself was built with colord support enabled

primary CRTC is at CRTC 0
CRTC for screen 0 CRTC 2 has no mode or no output, skipping
CRTC for screen 0 CRTC 3 has no mode or no output, skipping
CRTC for screen 0 CRTC 4 has no mode or no output, skipping
CRTC for screen 0 CRTC 5 has no mode or no output, skipping
CRTC for screen 0 CRTC 6 has no mode or no output, skipping

HDMI-1	the X atom and colord returned the same profile
	X atom:	_ICC_PROFILE (1630056 bytes)
		description: PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX
	colord:	"/home/pbeyens/.local/share/icc/PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX.icc"
		description: PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX

DP-1	the X atom and colord returned different profiles
	X atom:	_ICC_PROFILE_1 (0 bytes)
		description: (none)
	colord:	"/home/pbeyens/.local/share/icc/PL2230HS #2 2023-11-29 17-26 D6500 2.2 F-S XYZLUT+MTX.icc"
		description: PL2230HS #2 2023-11-29 17-26 D6500 2.2 F-S XYZLUT+MTX

Better check your system setup
 - some monitors reported different profiles
You may experience inconsistent color rendition between color managed applications
```

Note that I compare on the same monitor, so I doubt this is the problem?

I am using X11.

RawTherapee: can't find the preferences ??

**Comment by kofa73** [comment]
> HDMI-1	the X atom and colord returned the same profile
> 	X atom:	_ICC_PROFILE (1630056 bytes)
> 		description: PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX
> 	colord:	"/home/pbeyens/.local/share/icc/PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX.icc"
> 		description: PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX
> 
> DP-1	the X atom and colord returned different profiles
> 	X atom:	_ICC_PROFILE_1 (0 bytes)
> 		description: (none)
> 	colord:	"/home/pbeyens/.local/share/icc/PL2230HS #2 2023-11-29 17-26 D6500 2.2 F-S XYZLUT+MTX.icc"
> 		description: PL2230HS #2 2023-11-29 17-26 D6500 2.2 F-S XYZLUT+MTX
> 
> Better check your system setup
>  - some monitors reported different profiles
> You may experience inconsistent color rendition between color managed applications
> ```
> 
> Note that I compare on the same monitor, so I doubt this is the problem?

Different programs use different methods to query the display profile. Unfortunately, under Linux, there are at least two ways, the "X atom" and "colord".
For PL2230HS on HDMI-1, both are set to the same value, "PL2230HS #1 2023-11-29 16-50 D6500 2.2 F-S XYZLUT+MTX".
For PL2230HS on DP-1, the "X atom" is not set; colord is set to "PL2230HS #2 2023-11-29 17-26 D6500 2.2 F-S XYZLUT+MTX". So software using "X atom" will not be able to adapt colours for that display, software using "colord" will.

As for your RawTherapee, you did not set a specific profile in "Monitor/Default color profile", and you also did not ask RT to check the operating system settings, either, so it will not adapt colours for your monitor. According to https://rawpedia.rawtherapee.com/Preferences#Monitor, "In Linux, the _ICC_PROFILE **X11 atom** is used to automatically find the monitor's ICC profile." -- which is not set, so your RT has no way of obtaining the profile, even if you enable the _Use operating system's main monitor color profile_ option.
Either set the _icc_ option, pointing it at `/home/pbeyens/.local/share/icc/PL2230HS #2 2023-11-29 17-26 D6500 2.2 F-S XYZLUT+MTX.icc` (and keep it up-to-date when you recalibrate), or make sure the X atom is set. You can load it using `dispwin -I`, for example.

**Comment by pbeyens** [comment]
Ok thx, now I (kind of) understand the problem.
Quickly tried to change te settings of RawTherapee and indeed, color are less saturated now but still not like darktable (which is more saturated now...).

xiccd does not find my monitors and also: "it should not be used in desktop environments that support color management natively, like GNOME"

dispwin complains about VideoLUT depth (8 vs 10)...

So, I'm a little step further but the colors are different everywhere now: DT vs RT vs gThumb vs Image Viewer. See screenshot... (and this is only 1 monitor).

I suppose it's not a darktable issue.

![Screenshot from 2023-12-02 13-32-50](https://github.com/darktable-org/darktable/assets/439197/10db74b8-196b-4b06-970e-bbd3b6cef1ec)
