### ISSUE TITLE
review what darktable default supported feature should be

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15803]
**Is your feature request related to a problem? Please describe.**

Often people install a version from the Linux distribution and found that such or such feature are missing (like CUPS, HEIF support...)

**Describe the solution you'd like**

Have what we want to be a proper darktable config be the default.

What about making more packages as required and have an option to disable them instead of the opposite?

This would avoid packagers to build with missing feature silently. If a given package is not available on the target version then one will have to disable explicitly the support.

How does that sound?

EDIT: We had many issue like this, last one:
https://discuss.pixls.us/t/cr3-and-heif-support/32800/37

**Comment by kmilos** [comment]
Although this is good from the perspective of making packagers more aware, I don't see how it can manage user expectations?

**Comment by TurboGit** [comment]
To me the missing features are just an overlook from packagers as the build silently skip missing libs, so it will help manage user expectations by most probably engage the packager to support more features. Or did I missed your point?

**Comment by kmilos** [comment]
Silent or not, the feature will be missing, and that's what the user cares about. I don't think the users understand (or care) why it's missing, nor that they should reach out to the distro packagers instead of here or discuss.pixls.us.

**Comment by parafin** [comment]
Silently disabling features is bad for packagers, since it’s very easy to miss that some feature is no longer functioning due to changes in dependencies. It’s especially painful for rolling-release distributions. Build options should be on/off with no automatic behaviour (or auto being a third option). What to choose as default is a separate question. Perhaps off is actually better for newly added features, since it won’t break existing packaging scripts then.

**Comment by kmilos** [comment]
Ok, I've made a first stab at it, let me know what you think. The next question is what should be ON by default, as I guess this will start failing for a lot of people OOTB.

I haven't covered a couple that look a bit more complicated (COLORD and LUA I think).
