### ISSUE TITLE
Darktable 4.4.2 crashes quietly on win 11 after locking database files

### ISSUE THREAD

**Issue by malone-patpat** [darktable-org/darktable#15819]
### Describe the bug

Darktable 4.42, Windows 11 Pro version 22h2.
Something has happened on my system and Darktable launch.  It's starts but quietly crashes.  I have found it leaves the DB lock files in place, but if I delete them (or event the full DB files), it happens every time.  The darktable-log.txt file in InetCache\darktable does not have any useful information.  I have uninstalled/re-installed, rebooted between installs, downloaded and tried versions back to  4.2.1, but nothing works.  I notice in the InetCache\darktable folder it creates some graphic card cache folders.  I wonder if there is some conflict.  My system as an AMD Radeon Graphic card with a driver version of 30.0.15002.1004. 
I have found if I start it from the command line with --disable-opencl it works?  But I have been told it will be just too slow without opencl.

### Steps to reproduce

Do a fresh install of Darktable v 4.42
Launch Darktable
A quick dark box appears and disappears, and then nothing more happens.
Process explorer does not show the darktable process running.
The pid in the DB lock files is not there.
Delete the DB lock files and start again with the same results
I ran darktable with a -d common and again with a -d opencl and will attach the log file.  I don't know how to get a backtrace.

### Expected behavior

Darktable launches or give some actionable error

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/13541707/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable 4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro version 22h2

### Describe your system?

AMD Ryzen 9 5900HX with Radeon Graphics           3.30 GHz
32.0 GB (31.4 GB usable)

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by gi-man** [comment]
You have the OpenCL compatibility pack installed on this system. Go to windows apps and remove them. 

The FAQ explains this. There is also an issue with windows 11 Pro. 

https://www.darktable.org/about/faq/#faq-windows-issues

**Comment by jenshannoschwalm** [comment]
Closing as a) a well known issue and b)already fixed in master.

**Comment by malone-patpat** [comment]
Well gosh - that did it.  Sorry.  I did alot of searching in threads but
missed this in the FAQ.  A windows update must have added those.  A well
deserved RTFM.  Cheers

Pat
