### ISSUE TITLE
Pentax K-3 Mark III Monochrome files can't be developed in Darktable

### ISSUE THREAD

**Issue by apolozanionut** [darktable-org/darktable#15811]
### Describe the bug

Opening .PEF files captured with Pentax K-3 Mark III Monochrome simply show an error on open.
![Screenshot 2023-12-02 090023](https://github.com/darktable-org/darktable/assets/62916502/8f93d44f-9475-426d-8a61-31f1338a7b94)

### Steps to reproduce

1. Add to Library
2. Double click on file in Lighttable
3. Darkroom opens on light background with error message
4. Software returns for Lighttable and shows a skull for the image preview of the .PEF file.

### Expected behavior

Darktable should open the file and allow disabling of white balance/demosaicing options for raw b&w files, similar to Lightroom.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro 23H2

### Describe your system?

Dell Precision M6700, AMD FirePro M6000, 32 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD FirePro M6000, driver version 15.200.1045.0

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I can reproduce the same behavior on my Mac.
Issue only appears on RAW file open.
Steps above can be reproduced with a fresh edit.
[IMGP0282.PEF.txt](https://github.com/darktable-org/darktable/files/13536861/IMGP0282.PEF.txt)
Unsure how to empty/new config-dir.
I do not use Lua scripts, Darktable fresh install from a few days ago.

**Comment by ptilopteri** [comment]
is your camera even supported by this version of darktable?

**Comment by jenshannoschwalm** [comment]
Could you share an raw image? Checked for examples already uploaded to raw pixls?

**Comment by apolozanionut** [comment]
> is your camera even supported by this version of darktable?

Apologies, how can I verify that?

**Comment by apolozanionut** [comment]
> Could you share an raw image? Checked for examples already uploaded to raw pixls?

Hi Jens, sure thing. I uploaded them to raw pixls. Thank you for your support.

**Comment by kmilos** [comment]
> I uploaded them to raw pixls. Thank you for your support.

@LebedevRI

**Comment by LebedevRI** [comment]
@apolozanionut thank you for contributing the sample set!

**Comment by kmilos** [comment]
The DNGs should already be handled by https://github.com/darktable-org/rawspeed/pull/487

I'll take a look at the PEFs as soon as I get chance.

**Comment by apolozanionut** [comment]
> The DNGs should already be handled by [darktable-org/rawspeed#487](https://github.com/darktable-org/rawspeed/pull/487)
> 
> I'll take a look at the PEFs as soon as I get chance.

I confirm that the DNG files were successfully opened in DT.

**Comment by LebedevRI** [comment]
> > The DNGs should already be handled by [darktable-org/rawspeed#487](https://github.com/darktable-org/rawspeed/pull/487)
> > I'll take a look at the PEFs as soon as I get chance.
> 
> I confirm that the DNG files were successfully opened in DT.

(FWIW, DNG's should just work even without that patch)

**Comment by kmilos** [comment]
@apolozanionut It would seem the DNG you uploaded was done by Adobe Lightroom? Please upload the unaltered OOC DNG.

**Comment by kmilos** [comment]
I have now updated https://github.com/darktable-org/rawspeed/pull/487 with support for PEF as well, please test if you can.

**Comment by LebedevRI** [comment]
@apolozanionut if possible, it would be nice to replace the newly-uploaded sample set
yet again - the left border is solid black, it's impossible to verify the crop with it.
Something like daylight landscape usually is best.

**Comment by apolozanionut** [comment]
> @apolozanionut if possible, it would be nice to replace the newly-uploaded sample set yet again - the left border is solid black, it's impossible to verify the crop with it. Something like daylight landscape usually is best.

Hi Roman. I've uploaded the .DNG and .PEF samples, same subject, exposure, early morning landscape. Thank you for your support.

**Comment by LebedevRI** [comment]
@apolozanionut thank you, these are much better!

@kmilos @TurboGit what's the hard cut-off date, when will the tag be in place?

**Comment by TurboGit** [comment]
I'll tag late on Dec 14th around 20h CET.
