### ISSUE TITLE
[RGB Color Balance] perceptual brilliance grading drop at 40%

### ISSUE THREAD

**Issue by fabiosirna** [darktable-org/darktable#15821]
### Describe the bug

I noticed a strange behavior when I adjust ll perceptual brilliance value in the RGB Color balance module.
If I change the value by increasing it from 0% to 60%, as soon as it reaches 40% it suddenly 'loses' brilliance, and then regains it from 40.1% onwards.
I took screenshots at 30%, 40% and 50%. Beyond the pixelation, you can clearly see that the middle image is darker.
This does not happen with all images.

**Edit:** you can find an archive with an image RAF and the XMP file with the problem, at the end of this issue.

### Steps to reproduce

1. open a raw image
2. RGB color balance
3. change the value 'perceptual brilliance grading' from 0 to any value after 40%

### Expected behavior

Briliance should not drop, but should be continuos (my gut)

### Logfile | Screenshot | Screencast

# 30%
![image](https://github.com/darktable-org/darktable/assets/2249234/e831af3d-3213-4443-afb0-92dca310179d)

# 40%
![image](https://github.com/darktable-org/darktable/assets/2249234/b9fc4587-3634-4ce3-ba3d-a5b4360a3f76)

# 50%
![image](https://github.com/darktable-org/darktable/assets/2249234/9d805fe2-7479-47b0-9cf9-e7a5d0338f2a)

### Where did you obtain darktable from?

OBS

### darktable version

darktable 4.5.0~git1402.9f0088ce-1+11013.1

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 22.04

### Describe your system?

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.3
Kernel Version: 6.2.0-37-generic (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C35
System Version: 2.0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6700 XT (driver below)

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

GPU Driver

```bash
➜  ~ sudo lshw -c video

  *-display                 
       description: VGA compatible controller
       product: Navi 22 [Radeon RX 6700/6700 XT / 6800M]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:2f:00.0
       logical name: /dev/fb0
       version: c1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=amdgpu latency=0 resolution=1920,1200
       resources: irq:99 memory:d0000000-dfffffff memory:e0000000-e01fffff ioport:e000(size=256) memory:fca00000-fcafffff memory:c0000-dffff
```

# An image with the issue

[20160924_171036_FinePix X100_000.raf.tar.gz](https://github.com/darktable-org/darktable/files/13546455/20160924_171036_FinePix.X100_000.raf.tar.gz)

**Comment by jenshannoschwalm** [comment]
There have been various reports about colorbalance rgb giving wrong results on AMD hardware, never could be reproduced on intel,  nvidia or cpu. The OpenCL kernel function `kernel void colorbalancergb` has been checked for common amd problems like non-initialized data or NaN but that seems to be safe. In many places we use native functions that might be unstable for some drivers, you might try to test that - any feedback is appreciated.

Just to make sure - you don't have special cl compiler flags set? (see via darktable -d opencl)

**Comment by fabiosirna** [comment]
@jenshannoschwalm thanks, I'll keep in mind to not go above 20%!

these are the options from 'darktable -d opencl'

```
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DAMD=1 -I"/usr/share/darktable/kernels"
```

I can paste the full output if needed.

**Comment by jenshannoschwalm** [comment]
I guessed so. For a number of reasons the optimizing flag is disabled for amd by default.

Why did you spexify it manually is the question for me :-)

Would you try on this issue with defaults and freshly built kernels?

**Comment by fabiosirna** [comment]
Sorry, I don't think I understood your request.
The darktable version I'm using the taken from OBS repository.

**Comment by jenshannoschwalm** [comment]
Sorry, I meant you
1. should delete your opencl kernels in your local hidden .cache/darktable directory
2. remove the compiler options line from your resource configure file. Didn't you manually change that?

**Comment by jenshannoschwalm** [comment]
@piratenpanda you have often been testing such amd issues. You you test things I suggested and report?

**Comment by piratenpanda** [comment]
No fast math is enabled by default iirc. Will test tonight

**Comment by piratenpanda** [comment]
Cannot reproduce with a RX 6700 XT with opencl driver version 3590.0 (latest 5.7.1 ROCM extract on arch linux). Which version are you on @fabiosirna you can use darktable -d opencl to find out.

**Comment by fabiosirna** [comment]
@piratenpanda @jenshannoschwalm attaching the full log from ` darktable -d opencl`.

[dt.log](https://github.com/darktable-org/darktable/files/13572437/dt.log)

**Comment by fabiosirna** [comment]
> Sorry, I meant you
> 
>     1. should delete your opencl kernels in your local hidden .cache/darktable directory

Removed.

>     2. remove the compiler options line from your resource configure file. Didn't you manually change that?

Never touched :) IDK which file is the _resource configure file_.

This morning (after rebooting) I tried the same file I posted here, but I cannot replicate the issue. 
I didn't notice this issue again.

**Comment by jenshannoschwalm** [comment]
There was a subtle fix on the OpenCL code for that module that was the origin of many amd faults. Not sure though. XClosing this for now until we / you run into this or alike issue again.
