### ISSUE TITLE
"add to library" file selector does not update

### ISSUE THREAD

**Issue by chaseadam** [darktable-org/darktable#15831]
### Describe the bug

the "add to library" modal appears to not update after interation. Clicking on any of the elements other than the following have no visible effect:
* "cancel" (or top X)
* "+" to open file browser modal
* "?" 

It is notable that if I select a "checkbox" at the top, it appears to have toggled, but I can only see the effect when I close and re-open the "add to library" modal.

When the modal opens I get the following in the terminal repeated many times:

```
(darktable:1053882): GLib-GIO-CRITICAL **: 17:00:33.380: GFileInfo created without standard::is-hidden

(darktable:1053882): GLib-GIO-CRITICAL **: 17:00:33.380: file ../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached
```

I can get *sometimes* get the modal to populate with the contents of a folder if executed with a path as an argument. It is inconsistent

### Steps to reproduce

click on "add to library"
attempt to select a folder or toggle checkbox

### Expected behavior

files display in the large pane on the right

### Logfile | Screenshot | Screencast

[Screencast from 2023-12-05 16-57-28.webm](https://github.com/darktable-org/darktable/assets/333031/e778f23b-b620-4796-89e2-230cd7f99cf9)

### Where did you obtain darktable from?

distro packaging

### darktable version

darktable-4.4.2-1.fc39.x86_64

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 39

### Describe your system?

Wayland, i9-9900, 64GB

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by ClaudeMercier** [comment]
It may be related to fc39, I have the same problem, its works sometimes if we keep trying, then the check boxes and menus from style or copy history are is also not very often, drives me crazy. I use darktable 4.5.0+1439~g88819c341e, updated fc39, and recompiled td today.

**Comment by ClaudeMercier** [comment]
looks like selection in a list work , but focus is lost as soon as there is a checkbox

**Comment by ClaudeMercier** [comment]
Took quite a while for me to figure out, this is not a darktable bug
if I use gnome over Xorg, darktable works

**Comment by chaseadam** [comment]
@ClaudeMercier do we have any ideas where the bug is that we can follow up? Seems worth some upstream followup to address non-working state in the default fc39 install.

**Comment by ClaudeMercier** [comment]
@chaseadam , I really dont know, spent 3 full days to figure out why darktable was crazy.
I believe fc39 has a few bugs, emacs was fixed for me today with some mesaxxx package updates.
I will try again gnome not on Xorg from time to time. 
Could not see anyone complaining about gnome except us!

**Comment by ptilopteri** [comment]
it would be advisable to stick with X as wayland is still not optimal for photo processing, not color managed and most dt experiences are with X.

**Comment by ClaudeMercier** [comment]
good to know, thanks
