### ISSUE TITLE
AppImage Darktable-4.5.0+1412.g3b2f2fb2d9-x86_64.AppImage does not start because of GLIBC_2.34

### ISSUE THREAD

**Issue by GuentherE** [darktable-org/darktable#15835]
### Describe the bug

After setting exec perms the Appimage does not start. It gives an error message as shown.

### Steps to reproduce

1) downlad file
2) set exec perms
3) start with ./Darktable-4.5.0+1412.g3b2f2fb2d9-x86_64.AppImage

### Logfile | Screenshot | Screencast

/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/AppRun.wrapped)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libmvec.so.1: version `GLIBC_2.35' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdarktable.so)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgomp.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgomp.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libglib-2.0.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgtk-3.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgdk-3.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcairo.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgio-2.0.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgio-2.0.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libxml2.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libxml2.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgphoto2.so.6)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgphoto2_port.so.12)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libOpenEXR-3_2.so.31)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libjxl.so.0.8)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libjxl.so.0.8)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libjxl_threads.so.0.8)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libwebp.so.7)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libavif.so.16)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libheif.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libheif.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libheif.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libheif.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libsqlite3.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libsqlite3.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgmodule-2.0.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/librsvg-2.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/librsvg-2.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/librsvg-2.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcurl-gnutls.so.4)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcurl-gnutls.so.4)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libtiff.so.5)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libexiv2.so.27)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libexiv2.so.27)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libexiv2.so.27)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libopenjp2.so.7)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libGraphicsMagick-Q16.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libGraphicsMagick-Q16.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libGraphicsMagick-Q16.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libicuuc.so.70)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libicuuc.so.70)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcups.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcups.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libepoxy.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libxkbcommon.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libmount.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libmount.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libselinux.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libselinux.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/liblzma.so.5)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/liblzma.so.5)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libltdl.so.7)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libIlmThread-3_2.so.31)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libIlmThread-3_2.so.31)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libOpenEXRCore-3_2.so.31)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdav1d.so.7)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdav1d.so.7)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgav1.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgav1.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgav1.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libaom.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libssh.so.4)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libpsl.so.5)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgnutls.so.30)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgnutls.so.30)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgssapi_krb5.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libldap-2.5.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libldap-2.5.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libgcrypt.so.20)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libudev.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libudev.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libavahi-common.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libavahi-common.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libavahi-client.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdbus-1.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libdbus-1.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libblkid.so.1)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libunistring.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libunistring.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcrypto.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcrypto.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libp11-kit.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libp11-kit.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libkrb5.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libkrb5.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libk5crypto.so.3)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libkrb5support.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libkrb5support.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libsasl2.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libsystemd.so.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libabsl_malloc_internal.so.2206.0.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libabsl_base.so.2206.0.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libabsl_base.so.2206.0.0)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libcap.so.2)
/tmp/.mount_Darktau49WFg/AppRun.wrapped: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_Darktau49WFg/usr/bin/../lib/libabsl_time_zone.so.2206.0.0)

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.5.0+1412.g3b2f2fb2d9

### What OS are you using?

Linux

### What is the version of your OS?

MXLinux 21

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia GForce 750

**Comment by victoryforce** [comment]
This is not a bug. darktable AppImage is no longer compatible with your distribution release (MXLinux 21) for some time. The reason for this is that it is not possible to build the application on GitHub in the Ubuntu 20.04 environment, which would ensure compatibility with your version of MXLinux.

In order to use darktable AppImage, update your distribution to the latest version.
