### ISSUE TITLE
Darktable is not working on my windows 11 computer

### ISSUE THREAD

**Issue by private18201** [darktable-org/darktable#15853]
### Describe the bug

Hello!
First: I am not from a englsih country, so my english is not perfect.
I have a HP computer with windows 11. I used darktabel since july 2023 but suddenly it do not work even more. If I try to start it, it does not start.
It could be, that this is since the last windows update. But I am not sure about that.
What could I do, for removing this problem? I like your programme very much and so I want to use it again.
I would be happy about a solution.

### Steps to reproduce

I start it but it is not starting. 

### Expected behavior

start

### Commit

I don't know

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

it updated, and I think since then darktabel dont work 

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by victoryforce** [comment]
Check if the "OpenCL Compatibility Pack" is installed on your system? If so, uninstall it.

**Comment by MStraeten** [comment]
did you check all those win11 issue reports here if one of them might contain a solution?

**Comment by private18201** [comment]
> Check if the "OpenCL Compatibility Pack" is installed on your system. If so, uninstall it.

how can I do this?

**Comment by private18201** [comment]
@victoryforce i found it and it removed the problem. thank you very much!
