### ISSUE TITLE
Add color harmony guides to CIELUV (u*v*) vectorscope

### ISSUE THREAD

**Issue by Donatzsky** [darktable-org/darktable#15852]
According to [this Pixls thread](https://discuss.pixls.us/t/color-harmony-with-ryb/39614/26), the RYB color wheel is "wrong and outdated", and the color harmony guides in the vectorscope are effectively useless.

However, the CIELUV (u\*v\*) vectorscope does behave correctly, in terms of color harmonies, so it would make sense to also have the guides there.

**Comment by HSUfineprint** [comment]
It could be important to discuss a consensus before someone is willing to write actual codes. Do we want to just add the harmony guide to CIELUV? Or should harmony guide be applied to all similar scopes? Now it is Jzazbz, and what if we have CAM16-UCS or any other modern color models in the future?

**Comment by Donatzsky** [comment]
For the harmony guides to make any sense, it's important that complementary colors are actually opposite of each other in the vectorscope and that the primaries are evenly spread on the periphery. As long as that is the case, I don't see any UX reason why there can't be guides for any given color model. JzAzBz is a bit dodgy here, so unless there's a good reason to prefer it over CIELuv, I don't think it would be useful to have the guides there.

**Comment by Mark-64** [comment]
I am not sure about this.
Color harmony is art, not science.
I believe what we as humans find pleasing and harmonious is more the result of our aesthetic education than physics.
Moreover if we look at what we see around when coming to color harmonies, for example Adobe Color Wheel or Paletton, thay are clearly RYB, see below.

![immagine](https://github.com/darktable-org/darktable/assets/43290988/41696852-2c4e-4ed2-b976-d86dc41f388c)

Which of course doesn't mean other vectorscope layouts are not correct or not useful. They are just for different purposes.
Just my 2 cents

**Comment by HSUfineprint** [comment]
I'm not saying don't put put the harmony guide in CIELUV. I'm saying we should consider every color model's (vectorscope) possibility and outcomes. _Should we have harmony guide in all vectorsopes?_ 

RYB scope harmony guide for legacy usage. Modern color model harmony guide for more accuracy usage. Evenly spreading of color hue, chroma and lightness is one of the main goals for developing color models. Considering CIELUV did not have best performance in hue consistency and chroma prediction. Many modern models are developed. It's reasonable to bring all vectorscopes into the discussion. My point of view is we need to discuss the guideline for presenting harmony guides in darktable, not just a CIELUV feature.

**Comment by Donatzsky** [comment]
> _Should we have harmony guide in all vectorsopes?_

As I said, as long as a given vectorscope (current or future ones) is reasonably well-behaved, I see no reason why harmony guides can't be added to it. Then it's for the user to decide if it's actually useful to them.

And in any case, if support is added to CIELuv now, the smart thing to do would be to ensure that the code is properly decoupled, so that future scopes can be supported easily if wanted.

**Comment by Donatzsky** [comment]
Bruce Williams recently [did a video](https://www.youtube.com/watch?v=HyqteZsLZyI) on this feature, and there's a really interesting comment by *ronfrancis6012*.

Quoting:

> Anyway, colour harmony should be based on light, not pigment, so RGB should be used instead. The idea being, the complementary to red is cyan, so if you want to add a colour to 'balance the red", cyan will add the other colours of the spectrum, leaving your eye not wanting to see another colour as the whole spectrum is present. These are called optical complements.
