### ISSUE TITLE
The date filmstrip in Lighttable doesn't work well

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#15865]
### Describe the bug

This filmstrip with date columns doesn't work right

![Untitled](https://github.com/darktable-org/darktable/assets/2467520/e71ffd5c-db18-4d97-93c4-e3115b9848de)

It shows the images of a certain date correctly (e.g. 22/9/2023). But if we are about to see images from other dates and click somewhere, for example, a dot on the left, at the beginning of 2023, we go nowhere.

Instead this will be shown:
![Screenshot_2023-12-13_12-52-19](https://github.com/darktable-org/darktable/assets/2467520/2def7a03-c81f-4374-ace5-5d4d8d5cb34a)

The real 'culprit' for this problem is here:
![Screenshot_2023-12-13_12-52-19a](https://github.com/darktable-org/darktable/assets/2467520/8f18ab93-abde-48ae-8c08-4e620d4930e5)

If we use "Clear this rule"  the date filmstrip will be working correctly, as should. Now all images from our library can be chosen by clicking one or selecting multiple dots/columns in the filmstrip.

### Steps to reproduce

1. Import several image folders with various dates
2. Try to click on each date on the filmstrip. Only the current one is shown as the 'filmstrip' rule is preventing others to be shown, even though you wanted to navigate to other folders/dates by clicking on the filmstrip.
3. Clearing this rule makes the date filmstrip work correctly

### Expected behavior

DT should automatically switch to each date when user clicks or selects certain date(s) on the filmstrip

### Where did you obtain darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro latest

### Describe your system?

X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD GPU 6650XT

**Comment by ralfbrown** [comment]
It's working as designed - clicking (or dragging) on the timeline adds a date restriction *on top of* any existing selection criteria, rather than replacing them.

**Comment by maboleth** [comment]
> It's working as designed - clicking (or dragging) on the timeline adds a date restriction _on top of_ any existing selection criteria, rather than replacing them.
 
What's the rationale? Why the restriction after each import? 

The filmstrip/timeline certainly isn't greyed out or anything. We don't get any info that there is any restriction going, the filmstrip/timeline simply doesn't work. It took me a bit to figure this out. 

Shouldn't the user consciously selecting many dates on the timeline be above any local restriction that took place after import?

**Comment by AlicVB** [comment]
> What's the rationale? Why the restriction after each import?

This has already be discussed many times : what to do after the import button "clicked" : switch to the newly imported filmroll ? don't change anything ? etc... There should be some issue about that



> The filmstrip/timeline certainly isn't greyed out or anything. We don't get any info that there is any restriction going, the filmstrip/timeline simply doesn't work. It took me a bit to figure this out.

It is working : it allow you to refine your actual selection (but I understand that it's not what you want)
What can be misleading here is that ideally we should only show vertical bars for filtered images, not for the whole collection. But that's not so simple codewise...



> Shouldn't the user consciously selecting many dates on the timeline be above any local restriction that took place after import?

nope, you'll have the same result : no images shown. The collect module show the images at the intersection of the 2 rules ("AND" operator), and `A and B` is equivalent to `B and A`...

**Comment by maboleth** [comment]
> This has already be discussed many times : what to do after the import button "clicked" : switch to the newly imported filmroll ? don't change anything ? etc... There should be some issue about that

I got you. I can only offer suggestion as someone that is doing photography professionally. I'm no programmer.

To me, it would be logical/natural to display the newly added images first after import. However, I should not be restricted by them and should still be able to move freely on the Timeframe (meaning, without clearing the Filmroll date first).

I don't know if you are using Filmroll date to display newly imported images? If so, is there some other way to display the new imports by default, without other restrictions?

**Comment by ralfbrown** [comment]
> It is working : it allow you to refine your actual selection (but I understand that it's not what you want) What can be misleading here is that ideally we should only show vertical bars for filtered images, not for the whole collection. But that's not so simple codewise...

The filtered images are shown as a darker overlay on top of the bars for the full collection.  That may not be obvious if you only have a few folders in your collection, none of which have dates extending over multiple months.  It can also be hard to see that only part of each bar is darker due to the logarithmic mapping betweeen count and height if you have a lot of images in one month (I think six images is enough for 50% height, while the difference between 100 and 1000 is barely noticeable).
