### ISSUE TITLE
Nikon Z9

### ISSUE THREAD

**Issue by DanielTheGreat** [darktable-org/darktable#15873]
Darktable 4.4.2 does not handle RAW files from this camera (firmware revision 4.0) shot in HE* NEF format (I believe this is the most popular NEF format used by Z9 users).  Thumbnails are displayed (presumably from the embedded JPG previews), but nothing more can be done.

I've uploaded sample NEFs in the three available Z9 RAW formats to raw.pixel.us.

**Comment by ralfbrown** [comment]
Nikon "High Efficiency" is a proprietary compression algorithm whose details are not known to the open source community as far as I'm aware.  You'll need to avoid the HE and HE* formats until someone manages to reverse engineer them.

**Comment by DanielTheGreat** [comment]
OK, thanks Ralf.

Regards,
Daniel
---------------
"Be fearless in the pursuit of what sets your soul on fire." - Jennifer Lee 

 

________________________________

**Comment by kmilos** [comment]
This is a known issue, and already highlighted as such in the release notes.

See also https://github.com/darktable-org/darktable/issues/10889 and please search before opening new issues.

**Comment by blueglyph** [comment]
> Nikon "High Efficiency" is a proprietary compression algorithm whose details are not known to the open source community as far as I'm aware. You'll need to avoid the HE and HE* formats until someone manages to reverse engineer them.

No, there's a [pending PCT patent](https://worldwide.espacenet.com/patent/search/family/082942322/publication/WO2023025487A1?q=pn%3DWO2023025487A1), so I wouldn't advise to include any reverse-engineered code, unless the patent's rejected in all regions (the conclusion could still take a while).

On the other hand, there's a driver, so perhaps it can be used if it's installed. It's only for Windows, though.

For a global solution, you'd need the [official SDK](https://www.intopix.com/fasttico-raw-cpu-gpu-sdks), but I doubt it'll ever be provided in the context of an open-source project, since it'd make the library publicly available.

The only way I could see it may work is if a 3rd-party owning the licence created a binary release that includes the TicoRAW codec, but that means it should be an option allowing everyone else to build a release without it.

**Comment by blueglyph** [comment]
> @blueglyph No pending patent can make my guess about a possible encoding method illegal when I examine image data compressed using a patented technology. I perfectly understand the reasons for your advice, but I see no point in being afraid to touch anything that someone patents.

All I'm saying is that someone releasing any codec that processes that specific format without a proper licence risks being sued for patent infringement.

I'm not really sure what you mean by "make a guess illegal". The clear intent here of reverse-engineering the format is to add support in Darktable. Just analyzing that on your own and keeping it private is fine, of course, but pointless in the scope of this issue, so OOT. 🙂

**Comment by victoryforce** [comment]
> > @blueglyph No pending patent can make my guess about a possible encoding method illegal when I examine image data compressed using a patented technology. I perfectly understand the reasons for your advice, but I see no point in being afraid to touch anything that someone patents.
> 
> All I'm saying is that someone releasing any codec that processes that specific format without a proper licence risks being sued for patent infringement.

The reality is a bit more complicated than this statement, but I don't see any point in continuing this discussion. The truth is that the chances of someone investing their time in an independent implementation of a decoder for this format are slim. I also doubt that anyone will jump through hoops to bundle darktable with their SDK.

>  Just analyzing that on your own and keeping it private is fine, of course, but pointless in the scope of this issue, so OOT. 🙂

Tell about keeping it private to the ffmpeg and VLC projects.

**Comment by blueglyph** [comment]
> The reality is a bit more complicated than this statement, but I don't see any point in continuing this discussion. 

Ah yes, the "you are wrong but I won't explain why" approach. I've seen that a few times. My statement is accurate and I stand by it, for having worked in that field long enough, but believe what you want. 

If you comment further, though, please try and be more constructive. So far, your posts seem only aimed at contradicting randomly and without much ground.

> The truth is that the chances of someone investing their time in an independent implementation of a decoder for this format are slim. I also doubt that anyone will jump through hoops to bundle darktable with their SDK.

Maybe. I can't tell about the Darktable part of the code, but I can tell that the SDK isn't hard to use, nor would it be very hard to write a decoder from scratch, actually. TicoRAW is based on a lightweight algorithm, which also happens to be an quasi-open standard. Developing it with GPU support is another matter, of course.
 
> Tell about keeping it private to the ffmpeg and VLC projects.

If being enigmatic rocks your boats... Is it any relevant?

**Comment by RdWing** [comment]
Now that LibRAW supports HE*/TicoRAW files, would that change this issue?

**Comment by kmilos** [comment]
> Now that LibRAW supports HE*/TicoRAW files

Only it does not currently.

**Comment by RdWing** [comment]
> > Now that LibRAW supports HE*/TicoRAW files
> 
> Only it does not currently.

It does, it currently functions in RawDigger and FastRawViewer. [Support was added in v2.09](https://www.fastrawviewer.com/blog/FastRawViewer-2-0-9-Release#:~:text=Camera%2FRAW%20format%20support%0A%0ANikon%20HE%2FHE*%20compression%20support%20(for%20Nikon%20Z8%2C%20Z9%2C%20Zf%2C%20Z6_3%20cameras)). Unless that LibRaw is not the right LibRaw...

**Comment by kmilos** [comment]
RawDigger and FastRawViewer are paid for, and not open source products by LibRaw LLC (the commercial entity). LibRaw (the library) is not the same thing, and support for HE has not been added to it and publicly released yet.

**Comment by RdWing** [comment]
Well that is terribly confusing. I understand RawDigger et al are commercial products from libRaw LLC, but they claim to maintain and use LibRaw the library. [And the web page for LibRaw the library says](https://www.libraw.org/supported-cameras#:~:text=if%20our%20RawDigger%20announced%20at%20our%20blog%2C%20https%3A%2F%2Fwww.rawdigger.com%2Fnews%2C%20supports%20the%20camera%20%2F%20format%2C%20that's%20because%20LibRaw%20supports%20it.), "If Rawdigger announces support, it's because LibRaw supports it".
And it sounds like LibRaw does support it, but it has not been pushed to GitHub yet.

**Comment by blueglyph** [comment]
@kmilos Indeed. I think the same goes for Affinity Photo 2, which supports HE/HE* and still uses LibRaw (I think, but I'm not 100% sure).

I don't see how an opensource could include a paid SDK (TicoRAW), unless it had a non-opensource version for the HE support. There's also the delicate matter of reverse-engineering that Nikon proprietary format, though in general most companies don't mind too much (some do and sue).

**Comment by kmilos** [comment]
> And it sounds like LibRaw does support it, but it has not been pushed to GitHub yet.

The publicly available, open source version does not indeed ATM. What they have/use internally is anybody's guess.

**Comment by blueglyph** [comment]
All it would take is to uncompress the load and replace it before handling the full processing to LibRaw, I suppose (perhaps the library can be used to decode the header even in the HE format, thus avoiding redundancy in the code). So maybe it doesn't need to be part of that library.

**Comment by RdWing** [comment]
For what it's worth there is a [TicoRaw SDK](https://www.intopix.com/fasttico-raw-cpu-gpu-sdks) but as usual I'm sure it's fraught with licensing complications. But idk it might be worth a conversation with intoPix about it. 

Alternatively [Nikon also has an SDK](https://sdk.nikonimaging.com/apply/) that appears to support NEF file types including for the Z system cameras. The spec document is included in the SDK that you can download from that link, titled *Z_Series_RFmE_210.docx* Table 2.6.2.1 has the details for the compressed form, but it falls way short of anything actually useful. However, the included Nikon Image SDK does appear to support HE RAW. Might be a start.

**Comment by blueglyph** [comment]
@RdWing: That's what I mentioned earlier about the TicoRAW SDK, but it's a little more complex than that. I would have no problem contacting them, but I see no viable way to request its use that in an opensource project unless they'd we willing to have free binaries giving access to their decoder. Granted, it could be limited to the parameters Nikon is using (which we'd have to reverse-engineer). I feel that the demand should be addressed to Nikon instead, but it's doomed to fail unless someone has a personal contact in the right department (mines have moved on to other companies, unfortunately).

Great find about the Nikon SDK! I didn't find the HE/HE* in the specs or in the formats either, except a mention that it wasn't supported in 32 bits(?).

**Comment by isenberg** [comment]
I see the raw .NEF files from the Nikon D5 and Z9 on the Artemis 2 mission are compressed, which means they won't open in Darktable when they are released within a few months. They are not yet available to the public, only for a few selected individuals apparently, but in the full res JPEG metadata, the NEF compression flag can be seen. The fullres JPEGs with metadata are are available on this link: https://eol.jsc.nasa.gov/SearchPhotos/mrf.pl?scope=both&MRFList=ART002

**Comment by blueglyph** [comment]
@isenberg Yes, it's indeed using HE* compression:
https://www.linkedin.com/posts/intopix-s.a._intopix-ticoraw-nikonz9-activity-7455299889611177984-pv38?utm_source=share
