### ISSUE TITLE
Tagging does not work anymore

### ISSUE THREAD

**Issue by hanwolf1** [darktable-org/darktable#15889]
### Describe the bug

Hi, when I select tagging in collections (Sammlungen), no tag appears, although there are tags on the right side. This problem occurred suddenly (probably after importing new images). Previously the tags were also displayed on the left.
![1](https://github.com/darktable-org/darktable/assets/154011825/62a82964-b571-4b5e-8a20-7dfa28251a89)
If I filter the images by capture date (Aufnahmedatum) before and then refine the search by tagging, the tags are displayed correctly again.
![2](https://github.com/darktable-org/darktable/assets/154011825/faa78ccb-a035-4ae2-8195-47f278113221)
So this is a workaround for me, but I don't always want to have to select a capture date first. Does anyone know the behaviour and has a solution?

### Steps to reproduce

Unfortunately, I don't know exactly how the problem arose. No tags appear under collections when tagging is selected. If you filter by capture date beforehand, the tags appear again.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.0.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment]
> darktable version
> 4.0.1

Do you have any special reason using such an old version of darktable?
We are currently on 4.4.2 and 4.6.0 will be released next week.

**Comment by hanwolf1** [comment]
Thanks for your answer. I tried to install darktable 4.4.2 and was asked if I want to uninstall the old version before installing the new one. I was afraid that all my pictures and settings would be lost. Do you know if that would be the case?

**Comment by ralfbrown** [comment]
Nothing will be lost, though downgrading back to 4.0.1 will be difficult because internal formats of the database get updated, as well as any newly-written sidecars.
It's a good idea to make a backup first, but that applies to upgrading any software.

**Comment by hanwolf1** [comment]
Thanks a lot. Updating to 4.4.2 seems to solve the issue. Now the tags are displayed again as desired.
