### ISSUE TITLE
new module layout crashes darktable if the name has spaces

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#15880]
### Describe the bug

I made a new module layout, and named it "all with favourites". The name, with spaces, was accepted by darktable, and I could modify the modules layout. I closed and reopened dt without any problem.

But dt crashes, when I run

`$ LC_ALL=C darktable with --configdir "/tmp"`

I get the error:

`path lookup '/home/paolo/git/myphotoshare/with' fails with: 'No such file or directory'`

"with" is part of the layout name "all with favourites".

 

### Steps to reproduce

see descripcion

### Expected behavior

see descripcion

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

xubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia 3050

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

no lua scripts

**Comment by paolobenve** [comment]
I could see that when I re-run dt, I lost some change in the new layout

**Comment by ralfbrown** [comment]
Of course it will fail with a non-existent file/directory if you give it a non-switch commandline argument "with" (from which you're telling it to import images at startup) which doesn't exist.  Use
```
LC_ALL=C darktable --configdir "/tmp"
```
instead.

**Comment by paolobenve** [comment]
you're right!
