### ISSUE TITLE
Shaky images in lighttable on specific settings

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#15886]
### Describe the bug

Shaky images on lighttable with filmrolls between 16 and 20 images only and 5 images per row on main view.

See video below:
[Capture vidéo du 2023-12-16 11-26-00.webm](https://github.com/darktable-org/darktable/assets/45535283/92b13f92-362a-4912-b5e2-2059eee79dab)

### Steps to reproduce

1. set a filmroll with 16 to 20 images (I don't have that issue above or below that)
2. set 5 images per row (I don't have that issue above or below)
3. see the images shake

Issue reporduced with and without OpenCL and on all my filmroll with 16 to 20 images.

### Expected behavior

No shaking

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

Actual master

### What OS are you using?

Linux

### What is the version of your OS?

Debian Sid

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment]
An add on that issue. This not appear on all darktable window size. With same window moving from my 14" laptop screen (where I have the issue) to my external 32" 4K screen, I do not have the issue. And on my laptop, if I increase or decrease one panel size (to so change the thumbtable width), I can see the issue or no more have it. So seems that that issue is here only depending on the number of images AND size of thumbtable.

**Comment by jenshannoschwalm** [comment]
We have had issues like this several times if size-of-thumbs starts to fight with scroll-bar show/hide.

**Comment by TurboGit** [comment]
> We have had issues like this several times if size-of-thumbs starts to fight with scroll-bar show/hide.

Yes, but as far as I remember it was always fixed by adjusting the left/right panels, it seems this does not work here.

@dterrahe : You may want to comment on this.

**Comment by jenshannoschwalm** [comment]
@nilvus can also reproduce with other thumbs-per-row settings. Also the restriction to number of images in collection does not hold.

**Comment by Nilvus** [comment]
@jenshannoschwalm: seems logical. Seems to depend to thumbtable width.
