### ISSUE TITLE
Import videos from camera (FR)

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/darktable#15896]
Would be nice during the import process of pictures to be able to import videos as well.

**Comment by ptilopteri** [comment]
why would you want dt to transfer unsupported videos?
and if so, what other "unsupported" files should it also handle?

dt is already a very complex structure, why add more that few would utilize?

**Comment by ptilopteri** [comment]
ps:  would this not be a "feature request" rather than an "issue"?

**Comment by ActarusLeGrand** [comment]
> why would you want dt to transfer unsupported videos? and if so, what other "unsupported" files should it also handle?
> 
> dt is already a very complex structure, why add more that few would utilize?

Because cameras can record video also. It can put video aside the pictures. No need to display or play them into DT, as long as they are imported in the same folder as the pictures.

**Comment by ActarusLeGrand** [comment]
> ps: would this not be a "feature request" rather than an "issue"?

That is what I did, I clicked Issue, the feature request, get started. WHen do you want me to click?
![Screenshot 2023-12-17 202124](https://github.com/darktable-org/darktable/assets/54812718/d4d8c0f8-3108-47bc-8d59-7e7b3dd70c0d)

**Comment by gi-man** [comment]
There was text in the FR that was deleted to make it clear this is an FR.

If we copy the videos (and maybe rename them), but never show them in the light table and never play them, then how will you keep track of them? How will you know it was already copied? How will you know it was successful (eg. Not corrupted)? You don't want to tag them? Or add some metadata?

If we make them show and play, will you then want to trim or edit the video?

As you can see, this request opens up more complexity and focus away from raw image development into video handling. While technically feasible (I know lightroom does this), I don't think it is the right focus for the project.

**Comment by MStraeten** [comment]
maybe useful to ditch your camera file importer, but since video files aren't displayed in the ui you won't recognize, if anything failed during import of video files. 
A darktable guiding principle is to give you control - that is a contradiction to do something in the background you can't see the result ...
... but maybe someone who has an urgent demand for it starts coding it an provide a rfc pull request ;)

**Comment by jenshannoschwalm** [comment]
The gphoto stuff handling images is pretty tricky and we had a number of difficulties. I certainly wouldn't want to copy videos via that lib at all.

**Comment by ActarusLeGrand** [comment]
> maybe useful to ditch your camera file importer, but since video files aren't displayed in the ui you won't recognize, if anything failed during import of video files. A darktable guiding principle is to give you control - that is a contradiction to do something in the background you can't see the result ... ... but maybe someone who has an urgent demand for it starts coding it an provide a rfc pull request ;)

I can do it manually, that is what I do right now, but I can also forget about the video ,then format the SD card when I put it back in the camera and loose the videos.

**Comment by gi-man** [comment]
I think you can use digikam to import raw and videos. Then use the add to library feature.
