### ISSUE TITLE
Erroneous open on shortcuts window

### ISSUE THREAD

**Issue by wcampbell0x2a** [darktable-org/darktable#15897]
### Describe the bug

When in the darkroom image viewing window. Then clicking on the lighttable button on the top-right. Sometimes, instead of changing the view, it will instead open up the shortcuts window.

### Steps to reproduce

1. View image in darkroom
2. Click on "lighttable" button
3. shortcut window will appear

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Describe your system?

Lenovo laptop

### Are you using OpenCL GPU in darktable?

None

**Comment by Christian-Kr** [comment]
Hello to everyone,

I cannot reproduce this with at least 10 tries on a current ubunt4 23.10 with darktable 4.4.2 from ubuntu stable repository.

So maybe this is related to windows only.

Thank you in advance.
Greeting.

**Comment by ralfbrown** [comment]
@wcampbell0x2a Are you still experiencing this problem in 4.8.1?  Your original report is from two major releases ago.

**Comment by wcampbell0x2a** [comment]
Looks like it was fixed. Thanks!
