### ISSUE TITLE
Windows issues on Mac OS Ventura (homebrew)

### ISSUE THREAD

**Issue by ericlief** [darktable-org/darktable#15895]
### Describe the bug

Opened windows do not close with the mouse on upper left corner, only if there is the option to push a 'close' button. Thus I was unable to close the 'second darktable window' once open and has to force quit.

Also, the window for module presets does not expand beyond the first two options.

### Steps to reproduce

Install current version (4.4.2) with homebrew on M1 mac. Open second window or preferences/

### Expected behavior

Windows should close when upper left clicked

### Logfile | Screenshot | Screencast

![Screenshot 2023-12-17 at 10 34 43 AM](https://github.com/darktable-org/darktable/assets/16747511/73421034-d1e4-4f8e-b69c-5dd6234c73c0)
![Screenshot 2023-12-17 at 10 34 31 AM](https://github.com/darktable-org/darktable/assets/16747511/94159f2e-e01b-4826-be27-53ac9ee13673)
![Screenshot 2023-12-17 at 11 37 45 AM](https://github.com/darktable-org/darktable/assets/16747511/5504aecc-4281-4d01-a27a-009291114f2c)

### Commit

Master (homebrew)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Mac

### What is the version of your OS?

13.6.1

### Describe your system?

Macbook air (2019), 16GB, M1 

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This is the only version I can get to build correctly

**Comment by MStraeten** [comment]
it seems the window doesn't properly get focus - something i saw also on different applications - even apple applications ;) Just switch to a different app via command-tab and back - then the focus should be back.

**Comment by zisoft** [comment]
Yes, this is a very annoying bug which happens most often on the settings dialog (which does not have a close button).

What also works 100% reproducible: Move the window to a screen position where the red close button is NOT over a darktable window in the background. 

It seems that the mouse click event is not captured by the active window but by the window behind it.
To reproduce move the 2nd darkroom window so that the red close button is above the darktable logo. Now click the red button and see the about dialog open.

**Comment by ericlief** [comment]
Thanks, that seems to have worked for now.

**Comment by ericlief** [comment]
![Screenshot 2023-12-17 at 10 10 46 PM](https://github.com/darktable-org/darktable/assets/16747511/8713ff45-f5c4-4a25-bab6-c8d833f126cd)
I confirm that raising the window above the logo, works. There is still the problem of viewing options by right clicking. For me, only the first one or two are visible and there is no way of seeing the options below. Moving the window around doesn't help

**Comment by MStraeten** [comment]
latest post is known stuff ... (at least for external displays -  haven't seen that on the internal mbp display - see https://github.com/darktable-org/darktable/issues/15083)
now fixed in most cases, but sometimes it reoccurs ...

**Comment by TiredOfGuessing** [comment]
FYI the escape key closes the preferences window, but not the second preview.

**Comment by victoryforce** [comment]
Quoting from your another issue:

> I confirm that the window issue I reported (https://github.com/darktable-org/darktable/issues/15895) works as expected in settings.

Therefore, I close this issue.

**Comment by zisoft** [comment]
The issue has been [fixed upstream](https://gitlab.gnome.org/GNOME/gtk/-/issues/6297) and I can confirm it is working with gtk+ 3.24.41
