### ISSUE TITLE
Diffuse or Sharpen, Contrast Equalizer - different image look in lighttable and darkroom view

### ISSUE THREAD

**Issue by tomaszklucha-dev** [darktable-org/darktable#15890]
### Describe the bug

When working on images, I noticed that the exported image looks slightly different from what I saw in darktable. Further, I even notice that difference is even between lighttable and darkroom view. During investigation, I found that Diffuse or Sharpen, Contrast Equalizer modules causing this issue. Other modules that I use daily don't cause this. I've tested it on two different computers and effect was the same

### Steps to reproduce

Easiest way to reproduce this issue is to push modules to boundary values (like number of iterations in Diffuse And Sharpening)
1. Open image
2. Enable Diffuse Or Sharpen
3. Choose Dehaze preset
4. Change number of iteration to 128
5. Start switching betweeen darkroom and lightable views (full image view is advised)

### Expected behavior

Images should be the same

### Logfile | Screenshot | Screencast

![darkroom_view](https://github.com/darktable-org/darktable/assets/61212167/b9089b2b-4d49-44b0-bbbe-f31985cfd033)
![lighttable_view](https://github.com/darktable-org/darktable/assets/61212167/218cc437-6a1f-4ba1-a575-d3fc2ddcb91c)
![Zrzut ekranu 2023-12-13 201944](https://github.com/darktable-org/darktable/assets/61212167/95f7bf9c-26f2-4924-9fb9-42cb85c89f75)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.7.0+3~g9491da2c1c

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reproduced it both on 4.4.2 and latest nightly build.

**Comment by ralfbrown** [comment]
The darkroom works with a reduced-resolution version of the image for speed unless you have zoomed to 100% or more, and the thumbnails for the lighttable are generated from even more-reduced versions.  Many of the processing modules (including all wavelets-based, such as CE and D&S) are scale-dependent.  While they attempt to compensate for the different scaling, that compensation has varying effectiveness.

There is work underway to give an "export preview" in darkroom by running a full-resolution image through the entire pixelpipe.  Naturally, this will take as long as an actual export....

**Comment by tomaszklucha-dev** [comment]
@ralfbrown Thank for explanation. Looking forward for "export preview" feature.
