### ISSUE TITLE
$(ID) doesn't work on import

### ISSUE THREAD

**Issue by yetanotherphotographer** [darktable-org/darktable#15907]
### Describe the bug

When you import pictures, $(ID) doesn't work, it's populated with 0. 

If you use the rename LUA script it works just fine. 

[https://docs.darktable.org/usermanual/4.4/en/preferences-settings/import/](https://docs.darktable.org/usermanual/4.4/en/preferences-settings/import/)

### Steps to reproduce

Just import any pictures and use $(ID) in file name. 

### Expected behavior

Darktable should populate the correct ID when importing images

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia RTX 2070 Super

**Comment by TurboGit** [comment]
@yetanotherphotographer : Probably because the renaming is done before inserting the image into the DB and so at this time there is no ID created yet. I didn't look at the code, but this seems a good explanation. Not sure how to fix that and even if feasible.

**Comment by yetanotherphotographer** [comment]
Yes this was exactly my thought. Probably a matter of the way things are ordered during the import process. 

Anyway as of today, the ID is the only unique identifier that you can use to reliably name a picture, and have a consistent naming even after the import, which is quite important.

**Comment by TurboGit** [comment]
> Anyway as of today, the ID is the only unique identifier that you can use to reliably name a picture

In fact no, if you remove the picture from the library and reimport (in-place) it the ID will change in the DB but you'll still have the old id in the name.

**Comment by yetanotherphotographer** [comment]
But I guess you shouldn't remove it and reimport it? 

If you move it or rename it, then the ID doesn't change, which is the expected behavior for an ID.

**Comment by TurboGit** [comment]
> But I guess you shouldn't remove it and reimport it?

I do not do that, but many people import a directory, work on it, export pictures and remove from db. Then to rework some pictures they reimport. That's a common workflow.

**Comment by yetanotherphotographer** [comment]
Ok but this is irrelevant here.

**Comment by gi-man** [comment]
> the ID is the only unique identifier that you can use to reliably name a picture,

I think this is the least reliable unique identifier to use. It is just a sequential number of one program importing your images. I use (and a lot of others) a capture date (YYYYMMDD) _ Job Code (eg. 20231224_Christmas_Portraits). This gives you more useful information of what that image is about regardless of the program (digikam, dt, RT, lightroom).

**Comment by yetanotherphotographer** [comment]
I never said I used _only_ the ID. 

My file name pattern is something like MyName_Jobname_YYYYMMDD-HHMMSS, which was nice until cameras shoot multiple images per second. The best way would be to have milliseconds too obviously, but my camera doesn't populate the subsec EXIF field, (like a lot of others). 

Then you can use the sequence number $(SEQUENCE), which I do as a workaround, but it's not really reliable because it's dependent on the sequence of this specific import. As soon as you're outside of this specific import, the sequence number doesn't mean anything so you can't recreate it, for example if you move or rename images.

**Comment by TurboGit** [comment]
But again ID can't be used at import. 

When you import an image it is not populated, in the DB you have the name of the imported file. I don't see how one could have the ID in the DB which requires the ID do to known before to rename the file before importing. That's an chicken & egg issue.

**Comment by yetanotherphotographer** [comment]
You say "ID can't be used" like it's impossible, but it can, right? 

Funny enough your chicken & egg issue reminds me of a question we got asked by our teacher in the first or second C programming class, which was how do you place the value of _a_ in _b_ and the value of _b_ in _a_. 

As you know a=b;b=a doesn't work and we (very) young novice struggled a bit, until we obviously found out we had to create a third variable _c_. 

This little story aside, and as a matter of fact, as of today I import using $(SEQUENCE) and immediately after that I replace it with $(ID) with a rename. This is just me doing it manually but it shows it can be done, otherwise I wouldn't be able to do it at all.

**Comment by TurboGit** [comment]
> This is just me doing it manually but it shows it can be done, otherwise I wouldn't be able to do it at all.

Perfect then! But we won't support a 2 steps import in dt except if you propose a PR with the code.

**Comment by yetanotherphotographer** [comment]
I'm sorry but there is a misunderstanding here, I'm an artist (which is why I use DT), fulltime, I'm a user here. You want me to code this? What? I'd love to if I could but I don't really understand, this is my first ever issue report, is that what you expect people to do? 

This ID thing is in the manual, I report a bug (because it shouldn't report 0 if it can be used, right?). Then I receive so many questions about my workflow and about this or that. This is so odd. I just happen to know a bit of computer science, but is it really how you deal with users? 

Why attack me presuming I'm trying to do unreliable naming, or about my workflow or finally that ID can't be used instead of just explaining to me that you won't support a 2 steps import (the whole import is only one step?)?

**Comment by TurboGit** [comment]
Sigh...

**Comment by TurboGit** [comment]
Just to be clear I see no one attacking you. You want a unique ID, we have been two of us telling you that ID is not a unique ID with proof. @gi-man gave your the proper way to have a unique id for all your picture. And finally you tell us that you do it already and have a solution. So to me there is nothing more to do in dt expect documentation that ID cannot be used as import pattern.
