### ISSUE TITLE
Darkroom picture shifted from top left.

### ISSUE THREAD

**Issue by queequed** [darktable-org/darktable#15915]
### Describe the bug

Not sure if I set anything wrong but the DNG from my Sigma SD Quattro H are shifted from the top left (there is a black border on top and left sides with red bar on top , and the right and down sides of the pictures are missing). I have no module activated, and I have checked in Raw Therapee that the DNG is correct

Pictures from my other cameras, both JPG and RAW are still displayed normally.

### Steps to reproduce

1. open DNG file from a sigma quattro h (+100MB (https://filetransfer.io/data-package/GUe49L7Y#link)
2. open darkroom
3. top left corner of the picture is not on upper-left corner of the main view

### Logfile | Screenshot | Screencast

![Screenshot from 2023-12-20 16-38-56](https://github.com/darktable-org/darktable/assets/154453052/896b496c-460f-43f8-9ba1-540d8def0170)

### Where did you obtain darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

fedora 

### Describe your system?

cat /etc/fedora-release 
Fedora release 38 (Thirty Eight)
echo $XDG_SESSION_TYPE
x11
rpm -q gtk2
gtk2-2.24.33-13.fc38.x86_64

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

not reproducable with raw from Fuji or Canon cameras or with jpg from any cameras

**Comment by jenshannoschwalm** [comment]
I checked this on current master - which will be 4.6 in a few days and can't reproduce the issue.

Do you have a preset active for the raw black&white point module? (That also takes care of the initial cropping of invalid sensor data)
![Bildschirmfoto vom 2023-12-21 07-04-52](https://github.com/darktable-org/darktable/assets/50982232/9086d3d0-a893-4e19-a023-18d8bb6c95ab)

The red bar and invalid stuff is visible here too on master if i set the top/left crop to zero.

So no bug :-)

**Comment by kmilos** [comment]
Yep, already fixed by https://github.com/darktable-org/darktable/pull/15073 and will be in the upcoming release as mentioned.

Duplicate of https://github.com/darktable-org/darktable/pull/15073, please search before opening new issues.

**Comment by queequed** [comment]
Thanks for you reply, I have activated the crop setting in raw/black point and can correct it.
sorry for the duplicate, apologies.
