### ISSUE TITLE
Crash when opening CR2 file from EOS 350D

### ISSUE THREAD

**Issue by s12wu** [darktable-org/darktable#15929]
### Describe the bug

Since version 4.6.0, darktable crashes when I try to import a CR2 file from my Canon EOS 350D. This only occurs if it wants to read the raw image: Once after the import when generating the thumbnail (and checking if there's an embedded JPEG?), and then every time when switching to darkroom. If I set it to always use the embedded JPEG as thumbnail, the image appears in lighttable view when I restart darktable after it crashed. This doesn't happen for JPEGs or Sony ARW images.

On the command line, there's also an error complaining about libavif on startup, I don't know if that's related. This, as well, wasn't there on version 4.4.2

Example file: https://x0.at/maks.CR2

### Steps to reproduce

Go to 'import' and select the image. You can click to view the preview just fine.
Confirm the import dialog.
Navigate to a collection containing the image you just imported. As soon as it tries to create the thumbnail, darktable crashes. If you already were in a collection containing the newly imported image, darktable crashed immediately.

### Logfile | Screenshot | Screencast

```
$ flatpak run org.darktable.Darktable -d common
darktable 4.6.0
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> DISABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0022 application_directory: /app/bin
     0.0022 darktable.datadir: /app/share/darktable
     0.0022 darktable.plugindir: /app/lib/darktable
     0.0022 darktable.localedir: /app/share/locale
     0.0029 darktable.configdir: /home/soren/.var/app/org.darktable.Darktable/config/darktable
     0.0030 darktable.cachedir: /home/soren/.var/app/org.darktable.Darktable/cache/darktable
     0.0030 darktable.sharedir: /app/share
     0.0030 darktable.tmpdir: /tmp
     0.0030 new_xdg_data_dirs: (null)
Gtk-Message: 17:32:18.389: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:32:18.440: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:32:18.441: Failed to load module "canberra-gtk-module"
     0.1123 [dt_worker_threads] using 6 worker threads
     0.1595 [dt_get_sysresource_level] switched to 1 as `default'
     0.1596   total mem:       22959MB
     0.1596   mipmap cache:    2869MB
     0.1596   available mem:   11479MB
     0.1596   singlebuff:      179MB
     0.1941 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL'
     0.1941 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL.so'
     0.1951 [opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded, preference 'default path'
     0.4054 [dt_worker_threads] using 6 worker threads
     0.4360 [opencl_init] found 2 platforms
     0.4361 [check platform] platform 'Clover' with key 'clplatform_clover' is NOT active
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'NVIDIA GeForce GTX 1070'
   PLATFORM, VENDOR & ID:    NVIDIA CUDA, NVIDIA Corporation, ID=4318
   CANONICAL NAME:           nvidiacudanvidiageforcegtx1070
   DRIVER VERSION:           545.29.06
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          8106 MB
   MAX MEM ALLOC:            2026 MB
   MAX IMAGE SIZE:           16384 x 32768
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /app/share/darktable/kernels
   KERNEL DIRECTORY:         /home/soren/.var/app/org.darktable.Darktable/cache/darktable/cached_v3_kernels_for_NVIDIACUDANVIDIAGeForceGTX1070_5452906
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DNVIDIA_SM_20=1 -DNVIDIA=1 -I"/app/share/darktable/kernels"
     0.6554 [imageio_load_module_format] failed to open `avif': /app/lib/darktable/plugins/imageio/format/libavif.so: undefined symbol: avifRGBImageSetDefaults
   KERNEL LOADING TIME:       0.1191 sec
[opencl_init] OpenCL successfully initialized. internal numbers and names of available devices:
[opencl_init]		0	'NVIDIA CUDA NVIDIA GeForce GTX 1070'
     0.6912 [opencl_init] FINALLY: opencl is AVAILABLE and ENABLED.
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200
     9.1446 [rawspeed_open] extensions list to ignore: `cr3'
/usr/include/c++/12.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = int; _Dp = std::_Optional_base<int, true, true>]: Assertion 'this->_M_is_engaged()' failed.

```

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro 23.1.0 and Linux Mint 21.2 as VM

### Describe your system?

Manjaro 23.1.0: the one with the GPU, my main system
Linux Mint 21.2 as VM: Fresh install for testing

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia GTX 1070, 8GB VRAM, driver 545.29.06

**Comment by TurboGit** [comment]
Cannot reproduce with two CR2 from 350D, with yours:

![image](https://github.com/darktable-org/darktable/assets/467069/e32a6f36-3eea-4677-93a5-926ca1f278cb)

**Comment by s12wu** [comment]
Is your installation thorugh flatpak?
Because what we've discovered is that the flatpak package includes libavif 0.9.1
https://github.com/flathub/org.darktable.Darktable/blob/master/org.darktable.Darktable.json#L337
while the release notes for 4.6.0 say "libavif 0.9.2"
And there's also this error regarding libavif: `0.6554 [imageio_load_module_format] failed to open 'avif': /app/lib/darktable/plugins/imageio/format/libavif.so: undefined symbol: avifRGBImageSetDefaults`

**Comment by TurboGit** [comment]
> Is your installation thorugh flatpak?

No it is not. I'm a darktable dev and always building from sources.

**Comment by jenshannoschwalm** [comment]
Could you also provide the xmp file you have been using on dt 4.4 for that file?

**Comment by s12wu** [comment]
I only imported this image after updating to dt 4.6
The xmp file it creates is attached here.
When downgrading to dt 4.4, deleting the database and xmp file and importing the image, it creates the exact same xmp (apart from the import timestamp)
[maks.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/13756134/maks.CR2.xmp.txt)

**Comment by jenshannoschwalm** [comment]
mmm - can't reproduce right now.

**Comment by s12wu** [comment]
the same thing happens on an arm64 system, dt 4.6 installed as flatpak as well

**Comment by jenshannoschwalm** [comment]
So it may be a flat pack specific issue. Don't know about that.

@TurboGit do you see a way to make a conf option depending on flat pack or not? Or can we test for a flatpack somehow?

**Comment by victoryforce** [comment]
@s12wu Could you please check on appimage from https://github.com/darktable-org/darktable/releases/tag/nightly ? No need to install anything, just download the AppImage file, make it executable and run.

**Comment by Nilvus** [comment]
So as a flatpak issue, this has to be closed. @s12wu: probably yes a libavif issue on flatpak package. There find who package the flatpak and post the issue to him. darktable team do not support flatpak package.

**Comment by TurboGit** [comment]
> @TurboGit do you see a way to make a conf option depending on flat pack or not? Or can we test for a flatpack somehow?

Really no idea about this!
