### ISSUE TITLE
Recursive import to library does not work if corresponding .xmp files exist in folder

### ISSUE THREAD

**Issue by phrrk** [darktable-org/darktable#15928]
### Describe the bug

As per title images are not imported to library if .xmp files corresponding to the images exist.  On an attempted import Darktable instantly reports that x images have been imported but they have not been.  This has been tested with a clean (in memory) library file.  The images in question are imported (with data from .xmp) if selected directly (no recursion required) from their folder, i.e. the images and xmps are ok.

### Steps to reproduce

As described above select folder with at least one level of recursion to reach images and attempt to import them.

### Expected behavior

I would have expected the images to be imported along with the data in the xmps.  Maybe it was never intended for recursion to work when xmps exist, but if so it should be made clear somewhere.

### Commit

this is not a recently introduced problem

### Where did you obtain darktable from?

self compiled

### darktable version

4.7 latest, but has I think existed for a long time.

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

**Comment by badshah400** [comment]
I see the same issue with tagged version 4.6.0.

**Comment by TurboGit** [comment]
> I see the same issue with tagged version 4.6.0.

Which is expected on 4.6.

**Comment by badshah400** [comment]
> > I see the same issue with tagged version 4.6.0.
> 
> Which is expected on 4.6.

Sorry, the bug as reported suggests version 4.7, so I assumed this is some commits after version 4.6 was tagged. I wanted to chime in that I can see the same issue with version 4.6 as well.

Are you saying that it is expected that starting from version 4.6, dirs with prior xmp files in them can no longer be imported into the darktable library? If so, I did not know that. Please accept my apologies.

**Comment by phrrk** [comment]
I have just rebuilt and all is fine now.  My 'latest' was yesterday afternoon so I missed yesterday evenings commit.  Thanks @TurboGit

**Comment by TurboGit** [comment]
> Are you saying that it is expected that starting from version 4.6, dirs with prior xmp files in them can no longer be imported into the darktable library? If so, I did not know that. Please accept my apologies.

No, not need to apologies. I'm just too deep into this :) There is indeed a known issue in 4.6.0 that is fixed in master and will be fixed in 4.6.1. This was clear to me but I see that it is not for everyone. Hope this clarifies the situation.

**Comment by TurboGit** [comment]
> I have just rebuilt and all is fine now. My 'latest' was yesterday afternoon so I missed yesterday evenings commit. Thanks @TurboGit

Good to see that it is indeed fixed. Also fixed the display of the thumb for sub-directories when using recursive mode.
