### ISSUE TITLE
The navigation window doesn't reflect the changes correctly

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#15921]
### Describe the bug

I made two drawn masks - imagine a sphere and a smaller sphere within (they were drawn by hand - not made as circles). The first was drawn in the Color balance RGB tool and had Global brilliance raised - exclusively. The smaller was drawn in Exposure and lightened to a higher level than the bigger surrounding circle.
E.g. when the smaller Exposure based circle is toggled on and off, the larger circle is shown being on or off in the navigation window. Or the effect from other masking may occur - the lower part of the image had its light level decreased with a gradient mask in another module - but now it shows up when the small circle is toggled. Not consistent.

### Steps to reproduce

I can only provide the explanation above.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.5.0+1441~g83b1e7be17

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro, version 10.0.22621 build 22621

### Describe your system?

Able graphics card, screen and computer.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600, latest

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I know that this is just a cosmetic problem, but I would like Darktable to look nice and react logically.

**Comment by TurboGit** [comment]
Cannot reproduce!

> when the smaller Exposure based circle is toggled on and off, the larger circle is shown being on or off in the navigation window.

When I toggle on/off the Exposure mask (inner circle) I do have the toggled on/off on the main window and on the navigation window. Both a displaying the proper state on my side.

**Comment by KIRSJ** [comment]
Ok, good for you. I still have the problem. The navigator is just showing a zig-zag outside the circles now. I guess it's my GPU.
Don't put more energy into it. It's not critical.

**Comment by jenshannoschwalm** [comment]
No raw file and xmp you could share?

**Comment by KIRSJ** [comment]
No, it's confidential. The explanation says it all. Sorry not to be more helpful.

**Comment by victoryforce** [comment]
> No, it's confidential.

Do you mean that this issue only appears on this particular image?

**Comment by TurboGit** [comment]
@KIRSJ : If you reproduce easily on your side can't you reproduce on a non confidential image and send .XMP + RAW?

**Comment by gi-man** [comment]
You cant post a screenshot?

**Comment by KIRSJ** [comment]
I have not tried to reproduce the problem in another image. You will have to do without files from me. Not trying to obstruct you, but that's the way it is.
The error has taken different looks in the navigator as stated earlier. The failing presentation occurs when the Exposure module is toggled off and on, this is the module with the inner circular mask.

**Comment by TurboGit** [comment]
Ok, so nothing more to do on our side. We cannot fix something that we don't reproduce.

**Comment by KIRSJ** [comment]
Fair enough.
