### ISSUE TITLE
Recursive directory import doesn't work

### ISSUE THREAD

**Issue by Discostu36** [darktable-org/darktable#15938]
### Describe the bug

When I try to import images recursively, the import fails because the folder where the file is in (the deepest in the folder structure) seems not to be part of the path the program tries to import from. There are error messages flashing on the screen followed by an incorrect "imported x images"

Actual file path: `C:\Users\Public\Pictures\2022\03\PXL_20220312_124109583.dng`
Error in darktable: <code>error Ioading file `C:\Users\Public\Pictures\2022\PXL_20220312_124109583.dng'</code>

The file is imported successfully if I select the "03" folder and import. But I do not want to import every month in my photo collection seperately.

### Steps to reproduce

1. Go to "add to library"
2. Add folder with subfolders containing photos
3. Select "recursive directory"
4. Select "add to library"

### Expected behavior

Import images recursively

### Logfile | Screenshot | Screencast

I couldn't find the log file.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This is a fresh installation

**Comment by gi-man** [comment]
I know we had some issues with the import code that we could not all reproduce. The code fix was merged to master and tagged for 4.6.1. I'm not sure it will solve this problem, but you can give it a try via the nightly images (https://github.com/darktable-org/darktable/actions/runs/7304796542).

**Comment by Discostu36** [comment]
Thanks, yes, it seems to be fixed in the current nightly build.

**Comment by starze** [comment]
I can confirm, that the nightly-build 4.7.0+37~gbfb2721414 fixed importing Problems on mac. 
With the release version 4.6.0 it was not possible to import any picture but with the mentioned pre-release it works like a charme.
THX!

**Comment by MStraeten** [comment]
darktable-4.6.x bugfix build for macOS: https://discuss.pixls.us/t/current-osx-build/13213/727

**Comment by gdoirat** [comment]
Hi
I'm on OpenSuse Tumbleweed. I've updated system recently and recursive import doesn't work anymore. I confirm that on DT 4.6.0.1-1 I have the same issue describe here when i import recursively... Nothing is imported ! I hope that version 4.6.1 will come soon on tumbleweed!  ;)

**Comment by gi-man** [comment]
Normally 4.x.1 is a month or two after the 4.x.

**Comment by hraban** [comment]
Can confirm recursive import is fixed on mac in latest master

**Comment by Plouff** [comment]
Hello,
I add the same problem on Windows: import not working with 4.6.0.
Fixed with darktable-4.7.0+509.g55b95bb480.
Thank you.

**Comment by misaligar** [comment]
Recursive import does not work on Arch Linux with the latest official darktable package v4.6.0. What should I do?

**Comment by victoryforce** [comment]
> Recursive import does not work on Arch Linux with the latest official darktable package v4.6.0. What should I do?

@misaligar Wait for the 4.6.1 release, which will be sometime this week.

**Comment by wlloydw** [comment]
Recursive import does not seem to work on Mac in ver 5.0 when will this be fixed? Thanks

**Comment by MStraeten** [comment]
You’re commenting on a closed issue - so this won’t be recognized by any developer.
