### ISSUE TITLE
darktable displays pixel art instead of thumbnails

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#15936]
### Describe the bug

After applying the style to a RAW file, darktable displays pixel art image (based on a low resolution original image) instead of a thumbnail. Opening the image in a darkroom mode corrects the thumbnail. If the modification is applied for a number of selected images via the style or copy/paste, most of the thumbnails appear pixel art. Images are stored on the external HDD connected via USB. 
In the terminal the next message appears for each incorrect thumbnail:
24,6038 cannot get iop-order for colorout instance 1
69,5687 cannot get iop-order for colorout instance 1
 

### Steps to reproduce

Import some RAW images from a directory.
Apply some corrections to all of them at the same time via copy/paste of the style.
See pixel art instead of the thumbnails.

### Expected behavior

Show correct thumbnails

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Mint 21.2 Mate x64

### Describe your system?

AMD Ryzen 7950x, 32Gb RAM, AMD Radeon 580x.

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[A7_filmic.zip](https://github.com/darktable-org/darktable/files/13756656/A7_filmic.zip)

**Comment by jenshannoschwalm** [comment]
Imported your provided style and can't reproduce at all. Making sure a) also happens with --disable-opencl - i know you read you don't have it.

1. no idea how colorout is affected. Did you do something "magic" with module iop order? 
2. modern workflow with filmic default?
3. could you provide a log with `-d ioporder -d pipe -d params` while adding the style?

**Comment by BigSerpent** [comment]
Hello. I have OpenCl driver installed, but the CPU is faster than my graphics card.

1. I guess no, I didn't. The usual consequence is simple - import, select all, apply the style (or apply the style for the first, select its modules into the clipboard, select all, apply). The broken preview appears even if the style is applied to a single image.
2. Yes, scene-referred filmic.
3. Here is a part of the output when the style is applied:

81.4020 [styles_apply_to_image_ext] Apply style on image `(unknown)' id 792878, history size 0    81.4035 [dt_dev_write_history_ext] Writing history image id=792878 `(unknown)', iop version: 0
    81.4038      colorbalancergb, num  0, order 49, v(5), multiprio 0, enabled
    81.4039       denoiseprofile, num  1, order  9, v(11), multiprio 0, enabled
    81.4040              diffuse, num  2, order 32, v(2), multiprio 0, enabled
    81.4041             exposure, num  3, order 22, v(6), multiprio 0, enabled
    81.4042            filmicrgb, num  4, order 55, v(6), multiprio 0, enabled
    81.4043            filmicrgb, num  5, order 56, v(6), multiprio 1, enabled
    81.4044           highlights, num  6, order  4, v(4), multiprio 0, enabled
    81.6279 [dt_dev_read_history_ext] temporary history deleted
    81.6279 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
    81.6279 [dt_iop_reload_defaults] defaults reloaded for basecurve
    81.6279 [dt_iop_reload_defaults] defaults reloaded for colormapping
    81.6279 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
    81.6282 [dt_iop_reload_defaults] defaults reloaded for colorin
    81.6282 [dt_iop_reload_defaults] defaults reloaded for crop
    81.6282 [dt_iop_reload_defaults] defaults reloaded for exposure
    81.6282 [dt_iop_reload_defaults] defaults reloaded for retouch
    81.6282 [dt_iop_reload_defaults] defaults reloaded for clipping
    81.6282 [dt_iop_reload_defaults] defaults reloaded for flip
    81.6282 [dt_iop_reload_defaults] defaults reloaded for ashift
    81.6282 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
    81.6285 [dt_iop_reload_defaults] defaults reloaded for lens
    81.6285 [dt_iop_reload_defaults] defaults reloaded for scalepixels
    81.6285 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
    81.6286 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
    81.6286 [dt_iop_reload_defaults] defaults reloaded for demosaic
    81.6286 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
    81.6286 [dt_iop_reload_defaults] defaults reloaded for hotpixels
    81.6286 [dt_iop_reload_defaults] defaults reloaded for cacorrect
    81.6286 [dt_iop_reload_defaults] defaults reloaded for highlights
    81.6286 [dt_iop_reload_defaults] temperature: D65 2.627 1.000 1.388, AS-SHOT 2.709 1.000 1.434
    81.6286 [dt_iop_reload_defaults] defaults reloaded for temperature
    81.6286 [dt_iop_reload_defaults] defaults reloaded for invert
    81.6286 [dt_iop_reload_defaults] defaults reloaded for rawprepare
    81.6288 [dev_insert_module] `rawprepare' inserted to history
    81.6289 [dev_insert_module] `demosaic' inserted to history
    81.6291 [dev_insert_module] `colorin' inserted to history
    81.6294 [dev_insert_module] `colorout' inserted to history
    81.6295 [dev_insert_module] `gamma' inserted to history
    81.6295 [dev_insert_module] `temperature' inserted to history
    81.6297 [dev_insert_module] `flip' inserted to history
    81.6305 [dt_dev_read_history_ext] temporary history initialised with default params and presets
    81.6307 [dt_dev_read_history_ext] temporary history merged with image history
    81.6307 [history] successfully loaded module rawprepare from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 2:	version ok	params ok
    81.6307 [history] successfully loaded module colorin from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 7:	version ok	params ok
    81.6307 [history] successfully loaded module gamma from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 1:	version ok	params ok
    81.6307 [history] successfully loaded module temperature from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 3:	version ok	params ok
    81.6307 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params WRONG
    81.6307 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params WRONG
    81.6307 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params WRONG
    81.6307 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
    81.6307 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
    81.6308 cannot get iop-order for colorout instance 1
    81.6308 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
    81.6308 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
    81.6308 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
    81.6308 [history] successfully loaded module colorbalancergb from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
    81.6308 [history] successfully loaded module denoiseprofile from history
			blendop v. 13:	version ok	params ok
			params v. 11:	version ok	params ok
    81.6308 [history] successfully loaded module diffuse from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
    81.6308 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    81.6308 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    81.6308 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    81.6308 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
    81.6308 [_ioppr_check_rules] found rule colorout gamma module gamma (89) is before colorout monitor(2147483647) image 792878 (dt_dev_read_history_no_image end)
    81.6309 [dt_ioppr_check_iop_order] history module not used but enabled!! colorout monitor(2147483647) image 792878 (dt_dev_read_history_no_image end)
    81.6309 [dt_ioppr_check_iop_order] history base module set as not used colorout monitor(2147483647) image 792878 (dt_dev_read_history_no_image end)
    81.6334 synch all modules with defaults [thumbnail]                             
    81.6334 [iop_validate_params] `temperature' failed for type "float", field: various
    81.6334 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
    81.6412 [iop_validate_params] `borders' failed for type "float", field: aspect
    81.6412 [iop_validate_params] `borders' failed for type "dt_iop_borders_params_t"
    81.6489 synch all modules with history [thumbnail]                             
    81.6489 committed params           [thumbnail]      rawprepare             piece hash=d414434214eb2a80, 
    81.6489 committed params           [thumbnail]      colorin                piece hash=7563a39ceae1e96a, 
    81.6489 committed params           [thumbnail]      gamma                  piece hash=1ae2f37bb34a05, 
    81.6489 [iop_validate_params] `temperature' failed for type "float", field: various
    81.6489 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
    81.6489 committed params           [thumbnail]      temperature            piece hash=7dc6f98aab377972, 
    81.6489 committed params           [thumbnail]      channelmixerrgb        piece hash=5be37352c5bd77bd, 
    81.6489 committed params           [thumbnail]      exposure               piece hash=20f3bf4fd42e47c9, 
    81.6489 committed params           [thumbnail]      filmicrgb              piece hash=e117c1368c14a328, 
    81.6489 committed params           [thumbnail]      flip                   piece hash=0, 
    81.6515 committed params           [thumbnail]      colorout               piece hash=8e5a0f73242a7524, 
    81.6540 committed params           [thumbnail]      colorout               piece hash=8e5a0f73242a7524, 
    81.6540 committed params           [thumbnail]      demosaic               piece hash=b0702bc252c2d1d2, 
    81.6540 committed params           [thumbnail]      highlights             piece hash=19bfea6fe4b43879, 
    81.6540 committed params           [thumbnail]      colorbalancergb        piece hash=f6d6f592899202d7, 
    81.6543 committed params           [thumbnail]      denoiseprofile         piece hash=2cec4f8c3dd69950, 
    81.6543 committed params           [thumbnail]      diffuse                piece hash=aac55e56c83f11df, 
    81.6543 committed params           [thumbnail]      exposure               piece hash=3621c8ef4ebd848b, 
    81.6543 committed params           [thumbnail]      filmicrgb              piece hash=eef27eb91be9551, 
    81.6543 committed params           [thumbnail]      filmicrgb.1            piece hash=f97c1da042a9cdc9, 
    81.6543 committed params           [thumbnail]      highlights             piece hash=19bfea6fe4b43879, 
    81.6543 dt_dev_pixelpipe_synch_all [thumbnail]                             defaults 0.0155s, history 0.0054s
    81.6543 pixelpipe starting on CPU  [thumbnail]                             (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 
    81.6544 modify roi IN              [thumbnail]      demosaic               (   0/   0) 7031x4688 scale=1.0000 --> (   0/   0) 3840x2560 scale=0.5461 
    81.6544 modify roi IN              [thumbnail]      highlights             (   0/   0) 7032x4688 scale=1.0000 --> (   0/   0) 7031x4688 scale=1.0000 
    81.6544 modify roi IN              [thumbnail]      rawprepare             (   0/   0) 7168x5120 scale=1.0000 --> (   0/   0) 7032x4688 scale=1.0000 
    81.6544 pixelpipe data: full       [thumbnail]                             (   0/   0) 7168x5120 scale=1.0000 --> (   0/   0) 7168x5120 scale=1.0000 
    81.6544 pixelpipe process CPU      [thumbnail]      rawprepare             (   0/   0) 7168x5120 scale=1.0000 --> (   0/   0) 7032x4688 scale=1.0000 IOP_CS_RAW
    81.6635 pixelpipe process CPU      [thumbnail]      temperature            (   0/   0) 7032x4688 scale=1.0000 --> (   0/   0) 7032x4688 scale=1.0000 IOP_CS_RAW
    81.6720 pixelpipe process CPU      [thumbnail]      highlights             (   0/   0) 7032x4688 scale=1.0000 --> (   0/   0) 7031x4688 scale=1.0000 IOP_CS_RAW
    81.6805 opposed chroma CPU         [thumbnail]      highlights             (   0/   0) 7032x4688 scale=1.0000 --> (   0/   0) 7031x4688 scale=1.0000 red: 0.0000, green: 0.0000, blue: 0.0000 for hash=8811dced8ace9ad2
    81.7295 pixelpipe process CPU      [thumbnail]      demosaic               (   0/   0) 7031x4688 scale=1.0000 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RAW -> IOP_CS_RGB
    81.8802 clip_and_zoom_roi          [thumbnail]      demosaic               (   0/   0) 7031x4688 scale=1.0000 --> (   0/   0) 3840x2560 scale=0.5461 
    81.9264 pixelpipe process CPU      [thumbnail]      denoiseprofile         (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.2076 pixelpipe process CPU      [thumbnail]      exposure               (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.2167 pixelpipe process CPU      [thumbnail]      colorin                (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB -> IOP_CS_LAB
    82.2167 matrix conversion on CPU   [thumbnail]      colorin                (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 `standard color matrix'
    82.2230 transform colorspace CPU   [thumbnail]      channelmixerrgb        (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_LAB -> IOP_CS_RGB
    82.2279 pixelpipe process CPU      [thumbnail]      channelmixerrgb        (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.2531 pixelpipe process CPU      [thumbnail]      diffuse                (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.3876 pixelpipe process CPU      [thumbnail]      colorbalancergb        (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.4821 pixelpipe process CPU      [thumbnail]      filmicrgb              (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.5387 blend with form on CPU     [thumbnail]      filmicrgb              (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB, BLEND_CS_RGB_DISPLAY, no form
    82.5584 pixelpipe process CPU      [thumbnail]      filmicrgb.1            (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.6164 blend with form on CPU     [thumbnail]      filmicrgb.1            (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB, BLEND_CS_RGB_SCENE, no form
    82.6358 pixelpipe process CPU      [thumbnail]      gamma                  (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB
    82.6428 transform colorspace CPU   [thumbnail]      colorout               (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_RGB -> IOP_CS_LAB
    82.6480 pixelpipe process CPU      [thumbnail]      colorout               (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461 IOP_CS_LAB -> IOP_CS_RGB
    82.6600 cache report               [thumbnail]                             2 lines (important=0, used=0, invalid=0). Using 1120MB, limit=0MB. Hits/run=0.00. Hits/test=0.000
    82.6600 pixelpipe finished         [thumbnail]                             (   0/   0) 3840x2560 scale=0.5461 --> (   0/   0) 3840x2560 scale=0.5461

**Comment by jenshannoschwalm** [comment]
Very difficult to read this way. Could you please attach the log as a file?

**Comment by BigSerpent** [comment]
Here it is.
[style_log.txt](https://github.com/darktable-org/darktable/files/13768416/style_log.txt)

**Comment by jenshannoschwalm** [comment]
Ok, this is certainly wrong 

```
   587,7415 [history] successfully loaded module rawprepare from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 2:	version ok	params ok
   587,7415 [history] successfully loaded module colorin from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 7:	version ok	params ok
   587,7415 [history] successfully loaded module gamma from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 1:	version ok	params ok
   587,7415 [history] successfully loaded module temperature from history
			blendop v. 0:	version WRONG	params WRONG
```

```
   587,7416 [_ioppr_check_rules] found rule colorout gamma module gamma (89) is before colorout monitor(2147483647) image 792600 (dt_dev_read_history_no_image end)
   587,7416 [dt_ioppr_check_iop_order] history module not used but enabled!! colorout monitor(2147483647) image 792600 (dt_dev_read_history_no_image end)
   587,7416 [dt_ioppr_check_iop_order] history base module set as not used colorout monitor(2147483647) image 792600 (dt_dev_read_history_no_image end)
```
Again, gamma before colorout

```   587,9450 pixelpipe process CPU      [thumbnail]      gamma                  (   0/   0)  675x 450 scale=0,0960 --> (   0/   0)  675x 450 scale=0,0960 IOP_CS_RGB
   587,9471 transform colorspace CL    [thumbnail]      colorout               (   0/   0)  675x 450 scale=0,0960 --> (   0/   0)  675x 450 scale=0,0960 IOP_CS_RGB -> IOP_CS_LAB
   587,9478 pixelpipe process CL       [thumbnail]      colorout               (   0/   0)  675x 450 scale=0,0960 --> (   0/   0)  675x 450 scale=0,0960 IOP_CS_LAB -> IOP_CS_RGB
```
@TurboGit do you have an idea?

**Comment by TurboGit** [comment]
No idea how such a broken history could be created at this point. I have tried to apply the style to many images with style mode in append or overwrite. No issue on my side. Is that for RAW of a specific camera or on different ones?

**Comment by BigSerpent** [comment]
The same visual result is for Sony A99 RAW. I haven't tested the output though.

**Comment by jenshannoschwalm** [comment]
Can we we check somehow if the style in the database has a problem? Or - could it be it get's exported otherwise by some checks so we get a corrected one?

**Comment by TurboGit** [comment]
One test we can do:
- Backup data.db
- Import the style you sent us
- Apply it to an A99 RAW

**Comment by TurboGit** [comment]
If this still fails I can edit the .dtstyle to remove some operation to find the one breaking the style on your side. Maybe this will help understanding the issue.

Another question, do you remember with witch version of darktable the style was created?

**Comment by TurboGit** [comment]
Also if you compile from source you may try #15964.

**Comment by TurboGit** [comment]
I have just tested with an SLT-A99 RAW and cannot reproduce.

**Comment by TurboGit** [comment]
And is this new error with 4.6.0 or was it already broken on 4.4.2?

**Comment by jenshannoschwalm** [comment]
@TurboGit 

https://github.com/darktable-org/darktable/blob/18c7ddbf839f87d4afd873b0756ef0d4780fe376/src/common/iop_order.c#L2445

maybe we can do something better here? From my understanding we have a crippled iop list here which can't work - whatever the reason is.
1. Could we traverse back the list and remove all nodes until we find gamma?
2. Or give a warning and somehow do a safe "default order"?

**Comment by TurboGit** [comment]
> 1. Could we traverse back the list and remove all nodes until we find gamma?
> 
>     2. Or give a warning and somehow do a safe "default order"?

This is hard... If we go to default order we will loose all multiple instances and have a broken list and so broken rendering anyway. For sure at this point of the code there is not much we can do or some refactoring is needed.

**Comment by wpferguson** [comment]
If the iop list is corrupt, then maybe an error message and discard the history.  Or, a dialog box with the error message, and a choice for the user to discard the history, or try repairing it by editing the xmp file and re-importing it?

**Comment by TurboGit** [comment]
I have added debug output for now. We are not sure there is something corrupted in the XMP or iop order at this time.
