### ISSUE TITLE
Requesting an update to The Fine Manual

### ISSUE THREAD

**Issue by Graycard** [darktable-org/darktable#15933]
_The issue:_ 
The current (v4.6) darktable manual states on p. 184 under section 8.2.76, watermark: 
“User-designed watermarks should be placed into the directory $HOME/.config/darktable/watermarks.”  

_The problem:_ 
The above quoted text is incorrect, leaving out an important folder name. 

_Suggested corrections/updates:_ 
I would suggest the following re-wording to bring the text to current configuration: 
“Watermarks are placed in the file folders appropriate to the user’s operating system as follows:
    • Linux - standard watermarks: /usr/share/darktable/watermarks  (It is recommended that watermarks in this location not be modified or deleted.)
    • Linux - user-designed watermarks: $HOME/username/.config/darktable/watermarks 
    • Linux Mint - user-designed watermarks: var/lib/flatpak/app/org.darktable.Darktable/x86_64/stable/[long-ass-number]/files/share/darktable/watermarks 
    • Windows 10 - C:/Program Files/darktable/share/darktable/watermarks (All watermarks are available to be modified, deleted or added to.)
    • Mac - standard watermarks: /Applications/darktable.app/Contents/Resources/share/darktable/watermarks  (It is recommended that watermarks in this location not be modified or deleted.)
    • Mac - user-designed watermarks: $HOME/.config/darktable/watermarks”**Is your feature request related to a problem? Please describe.**

**Comment by MStraeten** [comment]
you better adress it here: https://github.com/darktable-org/dtdocs/issues

**Comment by Graycard** [comment]
Thanks for the correction, Martin.

**Comment by ralfbrown** [comment]
Moved to https://github.com/darktable-org/dtdocs/issues/602
