### ISSUE TITLE
DT 4.6.0 - corrupted image with .hdr files

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#15935]
### Describe the bug

DT 4.6.0, self built on Windows 11, fully updated MSYS2.

Opening .hdr files produces corrupted central image in darkroom.
Resetting history doesn't help, as well as turning OpenCL on/off.
I have tried with several samples, it happens consistently for me.

![immagine](https://github.com/darktable-org/darktable/assets/43290988/ed72d3a7-b18a-45f9-b6fa-1c80270b4662)

For example, files taken from [here](https://filesamples.com/formats/hdr)

It used to be working in previous releases.

### Steps to reproduce

1. import the .hdr
2. open in darkroom

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Win11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nVidia 1060

**Comment by jenshannoschwalm** [comment]
Can confirm also on Fedora, opencl on/off.

**Comment by victoryforce** [comment]
This kind of image distortion is clearly a problem with OpenMP.

But my OpenMP kung fu is too weak to understand why it worked in the previous release and doesn't work now.

As far as I understand, the problem can be fixed through double buffering, which will make it possible to avoid writing to the same buffer from which we read values in OpenMP'ed loop.

**Comment by victoryforce** [comment]
@jenshannoschwalm have you already started working on it? I think I have a fix ready.

**Comment by jenshannoschwalm** [comment]
Just disabling openmp :-) working on it for performance...

**Comment by victoryforce** [comment]
My guess was correct, double buffering fixes the problem with OpenMP enabled. I am ready to push the PR.
