### ISSUE TITLE
Newly created masks receive a mask opacity of 35%

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#15940]
If you create a mask in a module, e.g. a gradient in the exposure module, you can see in the mask manager that the mask is added to the module (e.g. exposure) group with an opacity of 35%.

I thought that the developers wanted this behaviour, por some obscure (to me) reason. But I searched the online manual and I coundn't find anything referring to that.

So I'd say that it's a bug. I cannot see any reason why the mask isn't given 100% opacity.

**Comment by gi-man** [comment]
See the Note: 

https://darktable-org.github.io/dtdocs/en/darkroom/masking-and-blending/masks/drawn/#creating-shapes

**Comment by elstoc** [comment]
Yes, this is intended behaviour
