### ISSUE TITLE
concerning bundled libraw

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#15947]
Are there any circumstances when the libraw library bundled in darktable is more up-to-date than the upstream version?
Upstream libraw has been included in Fedora repositories and I would like to unbundle it from darktable and use the Fedora one. 

I previously asked this question in dt-devel mailing list, but since I did not get any reply, I am posting it here
https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06831.html

**Comment by MStraeten** [comment]
did you check if setting `DONT_USE_INTERNAL_LIBRAW` cmake option is a solution?

**Comment by Germano0** [comment]
Hello @MStraeten , my question was not related about **the way** to disable darktable bundled libraw, but if there can be reasons to not do it

**Comment by MStraeten** [comment]
there was a reason to use bundled libraw when darktable got a pre release version of libraw to enable cr3 support within darktables release cycle that differs from the libraw release cycle.
It’s not known if or when this will be so again …

**Comment by kmilos** [comment]
> It’s not known if or when this will be so again

Exactly. It is possible the dt submodule will sync to a future "public snapshot" distros won't ship as it is not a "stable" release. When that is, no one except LibRaw devs knows: https://www.libraw.org/#updatepolicy

If/when it happens, we'll make sure distros building against the last stable shared system library keep working, they just might miss the support for some latest cameea models for example. C'est la vie, but it is what it is with such LibRaw release policy.

**Comment by victoryforce** [comment]
@Germano0 Since it was just a question, can we close this issue as resolved?
