### ISSUE TITLE
CR3 - horrendous image quality, noticed with EOS R6m2, high ISO

### ISSUE THREAD

**Issue by guigri** [darktable-org/darktable#15955]
### Describe the bug

darktable displays CR3 images in very poor quality under certain circumstances.
This was observed on images created with Canon EOS R6 Mark II with high ISO (25.600) values. The images look as if they consist of very few pixels and as if they have been scaled up. You can see staircase artifacts and there is no dynamic range at all.
( I know that the Canon EOS R6 Mark II is not yet officially supported by darktable. However, as I understand it, the lack of support is more of a color management issue and less of a problem that CR3 cannot be processed in general. Also, I've only noticed these issues with high ISO images so far. )
If you convert the CR3 images to DNG, then the DNG images are displayed normally by darktable.
The CR3 images also look as they should in Canon Digital Photos Professional.

### Steps to reproduce

Load the provided CR3 image into darktable and look at the display quality.

### Expected behavior

darktable should show / handle image with expected quality

### Logfile | Screenshot | Screencast

No logfile.

### Where did you obtain darktable from?

OBS

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

kubuntu desktop, nothing special

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia, GeForce GTX 750 Ti

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

CR3 image, Canon EOS R6m2, CRAW, ISO 25.600, poor quality in darktable 4.6.0 (pasword: darktable):
https://magentacloud.de/s/nH22WecAtDoHtaL

Screenshot (cropping) of the CR3 image in darktable 4.6.0:
![Screenshot of CR3 in darktable 4 6 0](https://github.com/darktable-org/darktable/assets/17358088/b3b00f18-68c9-47d2-8143-333022e8a7eb)
See also (password: darktable): https://magentacloud.de/s/M63oNkjSNLGfdRc

JPG version of the CR3 image created by the camera (password: darktable):
https://magentacloud.de/s/HYR5XB9tixpQHG5

Screenshot (cropping) showing the DNG file within darktable 4.6.0 (password: darktable):
https://magentacloud.de/s/nHTDDrFK8x2YPnF

DNG image created from CR3 (password: darktable):
https://magentacloud.de/s/astGJN55YeyRcwP

**Comment by MStraeten** [comment]
don't expect the same quality for unsupported camera raws. cr3 support is reverse engineered stuff, so if a camera isn't supoorted, the reverse engineering simply isn't done properly yet ...

**Comment by guigri** [comment]
Do you think that the problem has to be solved by LibRaw?

**Comment by jenshannoschwalm** [comment]
There are concrete hints how to make raw files available on the darktable website. That would be your first step.

**Comment by jenshannoschwalm** [comment]
Also if it's just with high iso, you could provide a raw file here for us to investigate.

**Comment by jenshannoschwalm** [comment]
@guigri i downloaded both the CR3 and the DNG file. The "issue" you are mentioning is absolutely not a dt issue at all. Have a look at what you got via the dng converter. Your raw file has a lot of chroma and luminance noise due to high ISO, the dng converter did some work to hide this. In darktable you'll find plenty of tools to reduce noise in a far better way. (Look into the manual...) But first, don't expect highest quality raw files from an APS sensor at those high amplifications (ISO). I checked other files, they look certainly very good. The "not fully supported" - right - we will try to fix that but certainly darktable does a quite good job here.

Closing this as not a dt issue at all.

**Comment by guigri** [comment]
@jenshannoschwalm: Thank you very much for your service!

Of course, I don't expect a really usable image at such high ISO values. Terrible noise and extreme loss of detail are normal.
But: I can't imagine that in this case the poor quality is only due to the generally low quality associated with high ISO values. The quality is so poor that it looks like a bug. There are clear "stair-stepping" effects, it doesn't look like a typical loss of quality at high ISO values.

Example (screenshot from darktable):
![Screenshot of high ISO CR3 in darktable](https://github.com/darktable-org/darktable/assets/17358088/2791297d-6128-4ac7-812f-88f6c390717e)

Here is another, maybe better example (password: darktable):
https://magentacloud.de/s/8NqbKamQiwJPeHr
(Sorry, I did upload examples to raw.pixel.us but afterwards I couldn't find my uploaded examples there and also no link to them...)

I don't think other software (e.g. DNG converter) is doing magical things here. If the problems I criticized were "normal" in regard to the high ISO values, then the Adobe DNG converter would do miracles here. I don't think so... ;-)

Maybe the problem is not with darktable, maybe with LibRaw, maybe with the lack of support from the camera.

It would be interesting to know whether CR3 photos with equally high ISO values from officially supported cameras look similarly bad in darktable.

**Comment by wpferguson** [comment]
R7 ISO 32000 doesn't show stair stepping

**Comment by jenshannoschwalm** [comment]
Ok, i can also see the zipper :-) BTW you can see what the sensor offers - a) you should disable lens correction for this to avoid moire - at least what dt sees - by using the "photosite color" demosaicer.
![Bildschirmfoto vom 2023-12-26 17-57-15](https://github.com/darktable-org/darktable/assets/50982232/8d7c3dba-c05f-4841-8f5c-028e1973b339)

I have absolute no idea how that could be related to libraw so far. Also that would mean some other algo of sensor layout depending on ISO? You don't have any "dirty tricks" active in your camera? compression. I just checked other software that also uses libraw like shotwell and same bad result. I looked closer again at your dng file, i just think that adobe dithered a lot :-)

Maybe ask libraw people or open a issue at their tracker? 

I just checked the test image https://www.dpreview.com/reviews/canon-eos-r6-mark-ii-in-depth-review#IQ at ISO 25k and there i don't see those artefacts here in dt.

**Comment by wpferguson** [comment]
I tested one of the files (3 people) with RawTherapee and didn't see the stair stepping.  I'm not sure what they are using for their raw decoder library.

**Comment by jenshannoschwalm** [comment]
> didn't see the stair stepping

Ok, that's a good point.

**Comment by guigri** [comment]
New insights: The problem apparently only occurs with compressed RAW (CRAW).
I had previously activated compression for RAW and now checked without compression. The stair-step artifacts do not occur without compression.

With compression (CRAW):
![grafik](https://github.com/darktable-org/darktable/assets/17358088/e3f2e1e7-33d1-493d-b3bc-42768fcbcb98)

Without compression (RAW):
![grafik](https://github.com/darktable-org/darktable/assets/17358088/8941cf74-a65c-4fd9-b99f-8187d2ded269)

Apparently either LibRaw or darktable have a problem with compressed CR3 files.
However, I don't see the problems in digiKam. As far as I know, both darktable and digikam are based on LibRaw. Perhaps different versions are used. But that could be an indication that the problem is with darktable.

**Comment by parafin** [comment]
Might digiKam use embedded preview instead of processing the raw data? It's not a raw photo developer after all...
Better reference is RawTherapee.

**Comment by guigri** [comment]
> However, I don't see the problems in digiKam. As far as I know, both darktable and digikam are based on LibRaw. Perhaps different versions are used. But that could be an indication that the problem is with darktable.

When I look at the high ISO RAWs (CR3) with Geeqie, they don't look very noisy. Obviously Geeqie only shows the embedded JPG that went through the camera's noise reduction.
When I look at the same high ISO RAWs with digiKam, I see terrible (normal) noise. This is an indication that digikam does not seem to display the embedded JPGs. ...this is all wild speculation. Maybe I should just read the websites. ;-)

**Comment by jenshannoschwalm** [comment]
Dt does not interfere in decompressing at all. That's all libraw business.

**Comment by MStraeten** [comment]
I‘m not sure if there’s a common understanding about ‚Canon R6mII isn’t supported by libraw yet‘
You’re eating soup with a fork and reasoning, why that’s not that effective as using a spoon …

**Comment by jenshannoschwalm** [comment]
I just checked RT on fedora39 with the staircase testimage and indeed it's the same problem. 
![Bildschirmfoto vom 2023-12-27 14-56-47](https://github.com/darktable-org/darktable/assets/50982232/cbdbef29-474e-4536-a272-aab4a20f00f0)

So - whatever the exact reason is
1. seek for proper support via libraw
2. the title of this issue is strongly misleading. "CR3 compressed raw files not supported in libraw" might be better

Please open a ticket at libraw ...

**Comment by guigri** [comment]
> the title of this issue is strongly misleading. "CR3 compressed raw files not supported in libraw" might be better

I understand your point of view. However, there is nothing wrong with the title I chose. If you know the cause of a problem, you can always name it precisely. For example: "Bad weather as a result of an incorrect type cast in Classe MyClass in line 37".  :-)
Just to explain myself, this is in no way meant as an accusation or anything similar: I think it is normal to first address a problem to the software where the problem is detected. DT probably uses 100 libraries and normal users can not be expected to differentiate between them.

Many thanks for your help!

**Comment by jenshannoschwalm** [comment]
The better the title is, the more likely users or devs will be able to find it again while looking for related issues. So quite often, such issue titles are improved / fixed.

**Comment by guigri** [comment]
@jenshannoschwalm: Sorry, I misunderstood you. I thought you meant that I should have given the title a different name from the start. I just realized that you can rename a title later, which I did right away.
Good that we've "talked" about it... :-)

**Comment by kmilos** [comment]
Is anyone able to confirm the upstream fix before I update the LibRaw submodule?

**Comment by TurboGit** [comment]
Yes, using LibRaw current master fixes the issue on my side.

**Comment by TurboGit** [comment]
![image](https://github.com/darktable-org/darktable/assets/467069/9ecb9e4f-6fa5-4218-84ae-2f2db5621c3b)
