### ISSUE TITLE
darktable 4.6.0 on Windows 11 crashes in lighttable view with Magick: caught exception 0xC0000005 "Access violation"

### ISSUE THREAD

**Issue by infjb** [darktable-org/darktable#15956]
### Describe the bug

The crash happens when the lighttable view generates the thumbnail of a specific CR3 RAW file. I still have to find the exact file from the set. 
Some thumbnails are still showing black or colorful blobs.

### Steps to reproduce

Scroll in the lighttable view through the thumbnails till the row with the problematic picture enters the displayed set of thumbnails. 
darktable instantly crashes.

The crash also happens with open "--disable-opencl".

### Expected behavior

darktable should render the previews

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/13766560/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

Gerätename	studiobook
Prozessor	13th Gen Intel(R) Core(TM) i9-13980HX   2.20 GHz
Installierter RAM	32,0 GB (31,6 GB verwendbar)
Geräte-ID	80753590-DC49-4B37-934C-747967EB3F5C
Produkt-ID	00330-80000-00000-AA260
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Unterstützung der Stift- und Toucheingabe mit 10 Touchpunkten

Edition	Windows 11 Pro
Version	23H2
Installiert am	‎14.‎04.‎2023
Betriebssystembuild	22631.2861
Leistung	Windows Feature Experience Pack 1000.22681.1000.0

darktable 4.6.0
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0,1218 [dt_get_sysresource_level] switched to 3 as `unrestricted'
     0,1232   total mem:       32396MB
     0,1238   mipmap cache:    4049MB
     0,1245   available mem:   518347MB
     0,1252   singlebuff:      32396MB
     0.1294 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded, preference 'default path'
     0.2422 [opencl_init] found 2 platforms
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'NVIDIA GeForce RTX 4070 Laptop GPU'
   PLATFORM, VENDOR & ID:    NVIDIA CUDA, NVIDIA Corporation, ID=4318
   CANONICAL NAME:           nvidiacudanvidiageforcertx4070laptopgpu
   DRIVER VERSION:           546.33
   DEVICE VERSION:           OpenCL 3.0 CUDA, SM_20 SUPPORT
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          8188 MB
   MAX MEM ALLOC:            2047 MB
   MAX IMAGE SIZE:           32768 x 32768
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 64 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   C:\Program Files\darktable\share\darktable\kernels
   KERNEL DIRECTORY:         C:\Users\frank\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_v3_kernels_for_NVIDIACUDANVIDIAGeForceRTX4070LaptopGPU_54633
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DNVIDIA_SM_20=1 -DNVIDIA=1 -I"C:\Program Files\darktable\share\darktable\kernels"
   KERNEL LOADING TIME:       0.6511 sec

[dt_opencl_device_init]
   DEVICE:                   1: 'Intel(R) RaptorLake-S Mobile Graphics Controller'
   PLATFORM, VENDOR & ID:    Intel(R) OpenCL HD Graphics, Intel(R) Corporation, ID=32902
   CANONICAL NAME:           intelropenclhdgraphicsintelrraptorlakesmobilegraphicscontroller
   DRIVER VERSION:           31.0.101.4255
   DEVICE VERSION:           OpenCL 3.0 NEO
   DEVICE_TYPE:              GPU, unified mem
   GLOBAL MEM SIZE:          12959 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      512
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 512 512 512 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   *** marked as disabled ***
[opencl_init] OpenCL successfully initialized. internal numbers and names of available devices:
[opencl_init]           0       'NVIDIA CUDA NVIDIA GeForce RTX 4070 Laptop GPU'
     1.0106 [opencl_init] FINALLY: opencl is AVAILABLE and ENABLED.
[opencl_init] opencl_scheduling_profile: 'very fast GPU'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 200
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           1       1       1       1       1
[opencl_synchronization_timeout] synchronization timeout set to 0
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           1       1       1       1       1
[opencl_synchronization_timeout] synchronization timeout set to 0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 4070 Laptop GPU, 8188 MB, 546.33

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The crash does not happen with darktable 4.6.0 on nobara Linux 38 KDE on an AMD Ryzen 9 7940HS with Radeon 780M iGPU (Minisforum UM 790pro with 64GB RAM / 8GB RAM dedicated to the GPU).
All thumbnails are shown without black or colorful blobs.

**Comment by gi-man** [comment]
Is it this file? `10,1202 [libraw_open] 3W7A1146.CR3: Libraw internal mempool overflowed `

or this file? `[dt_exif_xmp_write] X:\Fotos\EOS R5\2023-10-29\3W7A2956.CR3.xmp: caught exiv2 exception '[xmp_write] failed to serialize xmp data'`

Do you know what version of libraw you have in each system? Is this CR3 from a supported camera?

**Comment by infjb** [comment]
Both files are loading fine. It is another file. I have to isolate the files one by one.

The camera is a Canon EOS R5. I forgot to mention it. 

libraw on Windows is the one that comes with the official Windows binary of darktable 4.6.0.
On Linux it is version 0.21.1-4.fc38.

**Comment by gi-man** [comment]
Then post the file and xmp. Also post a -d common of only opening that file.

**Comment by infjb** [comment]
It happens with these two files together. Importing only one of them does not cause the crash.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13766997/darktable-log.txt)

The ZIP-Archive is to big to upload here. I have put it into my dropbox:
https://www.dropbox.com/scl/fo/pbhngb0596h8ipypcuwfr/h?rlkey=6t3t8lm5esyz6h1z8697fcfrq&dl=0

**Comment by kmilos** [comment]
In any case, the Magick exception has nothing to do with it, it just catches whatever real error that happened beforehand...

**Comment by jenshannoschwalm** [comment]
Here the Technicolor...cube is reported as bad. Not sure how that is handled on windows.

**Comment by gi-man** [comment]
@infjb I was looking at another Issue (https://github.com/darktable-org/darktable/issues/15939) and I think you have a similar problem. Switch your resources from `unrestricted` to `large` or `default`. The unrestricted is giving you an incorrect available memory. 

```
 0,1218 [dt_get_sysresource_level] switched to 3 as `unrestricted'
 0,1232   total mem:       32396MB
 0,1238   mipmap cache:    4049MB
 0,1245   available mem:   518347MB
```

**Comment by cabuy** [comment]
@infjb @gi-man I have similar hardware capacity and same OS. While unrestricted was ok for 4.4.2, I had to change it to "large" now.

**Comment by infjb** [comment]
I tried settings `large` and `default`. darktable still crashes.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13785650/darktable-log.txt)

**Comment by wpferguson** [comment]
Try `small`

**Comment by jenshannoschwalm** [comment]
The log shows at least errors for vng opencl sometimes backfalling to cpu.

**Comment by infjb** [comment]
darktable crashes with option `small`.

**Comment by infjb** [comment]
I tried nightly build 20240102 and darktable still crashes.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13814721/darktable-log.txt)

**Comment by gi-man** [comment]
I noticed this in the log. I noticed that the `[opencl_init] opencl_mandatory_timeout: 200`  The default should be 400. I dont think this is the issue but increase this value.

10,0117 [opencl_lock_device] reached opencl_mandatory_timeout trying to lock mandatory device, fallback to CPU

Do you get this problem if not using the 3DLUT?

**Comment by infjb** [comment]
Raising `opencl_mandatory_timeout` to 400 did not change anything.

I installed darktable on another Windows 11 notebook to remove only the 3DLUT module from the editings. daerktable did not crash.

Gerätename	zenbook
Prozessor	AMD Ryzen 7 5800U with Radeon Graphics            1.90 GHz
Installierter RAM	16,0 GB (15,4 GB verwendbar)
Geräte-ID	A30B8350-2EE1-4108-98D4-6CB4F3176044
Produkt-ID	00330-80000-00000-AA846
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Edition	Windows 11 Pro
Version	23H2
Installiert am	‎05.‎10.‎2022
Betriebssystembuild	22631.3007
Leistung	Windows Feature Experience Pack 1000.22681.1000.0

[darktable-log.txt](https://github.com/darktable-org/darktable/files/13968748/darktable-log.txt)

I will remove the 3DLUT module and report back from the other notebook.

**Comment by infjb** [comment]
I deleted all .xmp files which had the LUT3D module. darktable still crashes.

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14003180/darktable-log.txt)

**Comment by jenshannoschwalm** [comment]
Had another look at your latest logfile, indeed these lines look wrong and would likely make dt crashing as the roi_in / roi_out dont match for bilateral. It would help a lot if you could
1. recompile darktable with current master or use a recent build
2. just write the log with '-d pipe'
3. share the used xmp file for crashing image. Did you change the module order somehow?

**Comment by infjb** [comment]
I'm using the latest nightly builds for Windows.

Using darktable is frustrating at the moment. More and more of my filmrolls are crashing darktable. It always crashes in the lightable view when it loads the film roll.

It is hard to tell which images are responsible for the crash. Which debug options duoI have to set to see the file name in the log?

Film rolls are crashing even when I did not change the module order. I changed the order only on a few pictures.

I'm suspecting the surface blur module to mess up the previews. 

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14466523/darktable-log.txt)

**Comment by infjb** [comment]
I was able to cure the last crash with an update of Windows 11 and all drivers. 
And I can confirm that the surface blur module causes black artifacts in the preview. I'm using it on the red and green channel with a drawn masks to smooth out red areas on the skin.

**Comment by infjb** [comment]
It happens, when the red and green channel are set to 0.1 at the same time.

**Comment by victoryforce** [comment]
> I was able to cure the last crash with an update of Windows 11 and all drivers.

@infjb So can we close this issue?

Regarding your problems with surface blur, please open a separate issue.
