### ISSUE TITLE
Retouch Tool - feature request

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#15957]
Hi. Can we simplify how the retouch tool work? For example, if we use a brush to remove a blemish can we make it behave just like Lightroom or Photoshop where with just a simple stroke of a brush the blemish will go away? And is it possible to remove the extra step of pressing the CTRL key just to add a brush stroke? I think it would be best for the user to simply use the Healing, Clone tool just as they would work in Lightroom or Photoshop. They just keep on brushing the blemished areas to be removed until their satisfied with the results. I noticed this while I tried using the Retouch tool of Darktable v4.6. Thank you for your immediate response.

**Comment by MStraeten** [comment]
darktable isn't lightroom or photoshop - so try to learn the darktable way to do stuff. The tool gives a lot of control - so those who make use of that control are pretty good supported. You decide how a unwanted artifact should be handled.

**Comment by jenshannoschwalm** [comment]
Certainly not planned ...

**Comment by pitbuster** [comment]
> The tool gives a lot of control - so those who make use of that control are pretty good supported. 

That being said I recall an effort to bring GMIC resynthesizer to darktable. Maybe it would be better to try to reimplement it instead of trying to plug GMIC directly, but I think that besides the "LR/PS does it" comparison there is still some weight to the argument of havin an "smart" healing in retouch as an option.

**Comment by MStraeten** [comment]
even smart stuff requires someone to code that. If no one bites the bullet and provides a rfc pull request, there's simply not enough weight to suggested stuff...
foss is driven by code contribution, not by suggestions only ...

**Comment by blackzerotype** [comment]
or maybe atleast add a tab saying "SIMPLE" for those who use Darktable for bulk editing such as event photos. Sure there is a larger degree of control for the Retouch tool for those single to a few number of images to be retouched. But for just simply removing  an obstruction to a certain photo like removing a light stand in the frame, I'm sure by having a simple tab for those simple healing and cloning tasks would be a great addition to Darktable's arsenal of tools. I wish I know how to code this so I can make a contribution.

**Comment by jenshannoschwalm** [comment]
So, please update the title of this "issue" to something more meaningful. At least a "FR" for feature request and a precise description what you would like to have.
