### ISSUE TITLE
Nikon Z9 RAW support

### ISSUE THREAD

**Issue by law** [darktable-org/darktable#15952]
I have uploaded three RAW-types from the camera:

* Lossless
* High Efficiency Star
* High Efficiency 

These were copied straight from the camera.  I'm not entirely sure Nikon does 'uncompressed' RAW, but if there's a setting somewhere I'm happy to re-take.

**Comment by law** [comment]
Well shucks, my apologies.  I must've misread a chart somewhere.  Thanks for all your work on this great project!

**Comment by LebedevRI** [comment]
> I must've misread a chart somewhere.

Which chart? It's very possible some info somewhere needs updating.

**Comment by law** [comment]
Just the one on https://raw.pixls.us, for the samples.  I also couldn't find Z9 on the list of Supported Cameras at https://www.darktable.org/resources/camera-support/

As of today, it seems to show samples for the Nikon Z7, but nothing for a Z7ii, Z8, or Z9.

I did some searching of previous issues (about 45min too late, it seems, har har) and found https://github.com/darktable-org/darktable/issues/10889  as 'still open'.  I'm running Darktable 4.6.0 on macOS, and the uncompressed NEFs show up fine in the Light Table mode, but give the 'could not open' message when trying to view them in the Darktable mode.  Do you guys need anything else for a Z9 in order to better support it - white balance, elbow grease, etc?

**Comment by LebedevRI** [comment]
> the list of Supported Cameras at https://www.darktable.org/resources/camera-support/

Ah yes. That one is rather stale, refreshed: https://github.com/darktable-org/dtorg/commit/a3196a85e6663a6e9498d89a4f3183f01a9132db
