### ISSUE TITLE
Zoom level is not preserved in lighttable full preview between images

### ISSUE THREAD

**Issue by jamesadney** [darktable-org/darktable#15966]
### Describe the bug

When reviewing wildlife photos, I often zoom into my subject in full preview mode and switch between similar images. This is especially useful for images shot in continous mode that are almost identical in composition.

Before 4.6 my zoom level would be preserved when switching between images. Now the zoom resets when I use the arrow keys or scroll wheel to preview another image.

### Steps to reproduce

1. Go to lighttable
2. Select an image
3. Enter full preview layout
4. Zoom in
5. Use the arrow keys to view another image

### Expected behavior

Expected the zoom level to be preserved.

### Commit

0301d02b55c9311e689b408254356b2e86cf0e4a

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.0+36~g0301d02b55

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Gnome with Wayland session

### Are you using OpenCL GPU in darktable?

No

**Comment by Mark-64** [comment]
I noticed the same behavior, which is actually quite annoying when culling images

**Comment by TurboGit** [comment]
@AlicVB : Can you have a look at this regression? TIA.
