### ISSUE TITLE
Upgrade darktable to use cairo graphics "stable release" 1.18.0

### ISSUE THREAD

**Issue by TiredOfGuessing** [darktable-org/darktable#15965]
**Is your feature request related to a problem? Please describe.**
Hoping the Cairo -> macOS-quartz changes to display color space will improve the display rendering on macOS.

> John Ralls (4):
>       [quartz] Cleanup and make better use of cairo_quartz_image_surface_t.
>       [quartz] Pretty up the surface-type and zero-size tests.
>       [quartz] Replace surface-pattern xfail with latest CI fail image.
>       [quartz]Conditionally Use Main Display ColorSpace instead of kCGColorSpaceDefaultRGB.

Per the latest news the release 1.18.0 (2023-09-20) it seems that the upgrade would be generally beneficial to dt.

> The first stable cairo release in five years should be cause for celebration.
> 
> All the API added in the 1.17 development cycle is now considered stable, and
> will not change.
[https://www.cairographics.org/news/cairo-1.18.0/](url)

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by MStraeten** [comment]
cairo 1.18.0 isn't yet provided by macports so not available for arm64 build yet. If the port is done it will be used ...

**Comment by parafin** [comment]
I don’t think these changes allow dt to render colors outside of sRGB colorspace. It’s only about render performance (speed).

**Comment by victoryforce** [comment]
@TiredOfGuessing darktable is built with those libraries that are in the build environment. We have no influence on when this library appears in the various environments where darktable can be built.

So in what sense do you suggest "upgrading" darktable?

**Comment by TiredOfGuessing** [comment]
Sorry I don't know what drives this kind of feature/update. Sounds like it will automatically occur when available. Thx

**Comment by victoryforce** [comment]
> Sounds like it will automatically occur when available.

Probably darktable will simply work with a new version of the library when such a build becomes available. We will not be able to check whether there will be any problems until it happens.

**Comment by geni1105** [comment]
Just to comment on this for the records: I built darktable 5.0 myself with cairo 1.8.2+ and on macOS the behavior at first glance did not change perceivably; in particular with respect to the limitations on sRGB, the rendering is exactly the same as with the official 5.0.
