### ISSUE TITLE
Gimp cannot find darktable plugin for version 4.6.0

### ISSUE THREAD

**Issue by beew** [darktable-org/darktable#15968]
### Describe the bug

After upgrading darktable to 4.6.0 gimp can no longer open raw files. It complains that a raw plugin is missing even though darktable is installed  Darktable can open the file directly though.

Reverting to darktable 4.4.2 it works again

### Steps to reproduce

Update darktable to version 4.6.0

Try to open a raw file with gimp.

Gimp complains that it cannot find a raw plugin

### Expected behavior

open the file

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0 .  Darktable installed from the ppa https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/darktable

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

Ubuntu 22.04, Gimp 2.10.36 compiled from source

### Are you using OpenCL GPU in darktable?

None

**Comment by beew** [comment]
More info


Ubuntu 22.04, Gimp 2.10.36 compiled from source. darktable was installed from Ubuntu ppa as noted above. I emailed the ppa maintainer and here is his reply

"
I can reproduce the issue in 22.04 with Darktable 4.6.0 from both PPA and OBS Repository. Could be something to do with OpenCL initializing...

I'm not a programmer, so sorry I can't help! But, you can report the issue 
"



### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

intel opencl hd graohic

**Comment by SebastianoGuer** [comment]
As VERY temporary workaround You can patch executable "file-darktable", substituting the string
this is darktable [^0-9]
with the string
darkta[a-z][a-z][a-z][ ]
(the two strings have the same length),
and the string
Lua support enabled
with the string
Lua                
(the above padded with blanks up to the exact length of "Lua support enabled", and provided that darktable version shows line
 Lua                    -> ENABLED  - API version 9.2.0.
(Tested in Windows, executable modified by means of WinMerge).

**Comment by beew** [comment]
Is this fixed in 4.6.1?

**Comment by SebastianoGuer** [comment]
Yes, it was.

**Comment by victoryforce** [comment]
@SebastianoGuer Thanks for the confirmation, then I'm closing this issue.
