### ISSUE TITLE
Possible bug with sub directory naming pattern during import (EXIF DATA)

### ISSUE THREAD

**Issue by gid000** [darktable-org/darktable#15979]
### Describe the bug

Hi all,

Before importing around 5k images today, I noticed something strange. Not sure if is a bug or not, and I would like to double check with you guys.

Here are are my current settings:

``` 
base directory name pattern: $(PICTURES_FOLDER)/Darktable
sub directory name pattern: $(YEAR)$(MONTH)
file name pattern: $(YEAR)$(MONTH)$(DAY)_$(SEQUENCE).$(FILE_EXTENSION)
```

And here an example of a file I found after import:

```
Darktable/202312/20171010_211335.jpg
```

The only folder created was 202312, even if a 2017 file was found (as show above). Based on my settings, I was expecting another folder called "201710" to accommodate those files. Then I noticed in darktable documentation there is a difference between `$(YEAR)` and `$(EXIF_YEAR)`. I will change my settings to use EXIF_YEAR, however I find confusing the mismatch between the folder and file. Did I missed something?

### Steps to reproduce

1. Configure the settings above;
2. try to import a lot of photos.
3. find for inconsistency under the output folder 

### Expected behavior

no inconsistency

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.5.0+445.g0fcf57c4fe

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

It is an appimage:

./Darktable-4.5.0+445.g0fcf57c4fe-x86_64.AppImage

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment]
The folder is using today date (date of import). I think the filename is using the date of export from the jpg metadata.

**Comment by gi-man** [comment]
If you do exiv2 or exiftool on the jpg, it likely has an export date of 2017.10.10

**Comment by gi-man** [comment]
Dt uses exiv2, so ideally use that to evaluate your jpg. There are likely multiple date fields (icpt, xmp, exit,... Date taken, date capture, date ...)

But look at the image timestamp in the info you posted: 2017:10:10.

**Comment by zisoft** [comment]
The thing is that using the same variable $(YEAR) twice it should give the same results in both cases.

**Comment by zisoft** [comment]
According to the [variables documentation](https://docs.darktable.org/usermanual/development/en/special-topics/variables/) `$(YEAR)`, `$(MONTH)`, `$(DAY)` are substituted by the date of the import, thats why you get the folder 202312 which is correct.

To get the folder structure based on the image datetime you need to use `$(EXIF.YEAR)`, `$(EXIF.MONTH)` and `$(EXIF.DAY)`.

> file name pattern: `$(YEAR)$(MONTH)$(DAY)_$(SEQUENCE).$(FILE_EXTENSION)`

> Darktable/202312/20171010_211335.jpg

There is no sequence in the resulting filename, instead it is the filename of the original file without substitution so something other is strange.

**Comment by gi-man** [comment]
Share the jpg and I can look at it in more detail in a few hours.
