### ISSUE TITLE
output xmp from CLI

### ISSUE THREAD

**Issue by jrhizor** [darktable-org/darktable#15971]
Is it possible to output a darktable XMP from the CLI? For example, if I have a jpg I previously edited in Lightroom and want to use it via the darktable cli, I might do this, where `img.xmp` is the Lightroom sidecar:
```
darktable-cli img.jpg img.xmp output.jpg
```

This Lightroom XMP is [converted into darktable transformations](https://github.com/darktable-org/darktable/blob/master/src/develop/lightroom.c) and a modified image is output, but the command doesn't overwrite,  extend the specified XMP, or create a new one.

Is there a way to generate the darktable-specific `img.jpg.xmp` file that represents the changes that were applied?

**Comment by MStraeten** [comment]
not yet, darktable-cli isn't darktable just without the UI. It's designed for a specific purpose: process given images with applying a given xmp file or presets and then output the result using export options. All relevnt informations are given via commandline parameters, so no need to generate additional xmp files
