### ISSUE TITLE
RGB Curves question/issue

### ISSUE THREAD

**Issue by ericlief** [darktable-org/darktable#15970]
### Describe the bug

When I put a node on the curve and pull down the part of the curve above the node moves up, like spaghetti.
![Screenshot 2023-12-26 at 11 22 40 PM](https://github.com/darktable-org/darktable/assets/16747511/4e5eb4b0-aafc-4385-8caa-cd05bf059c6f)

### Steps to reproduce

Open curves 

### Expected behavior

The node should fix the part outside of the modified section

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

13.6.1

### Describe your system?

Macbook air, M1 (2019), 16GB

### Are you using OpenCL GPU in darktable?

No

**Comment by HSUfineprint** [comment]
That's what a curve works. You can try the curve function in photoshop, it works the same. In darktable, you can choose centripetal spline to avoid that.

**Comment by MStraeten** [comment]
not a bug, but a feature.

**Comment by ericlief** [comment]
Thank you. I just tried the curves in Lightroom and Gimp and they don't work the same way. I no longer have access to Photoshop, so I can't test this. The curve extends only within the nodes. In DT, the other modes mentioned or a little better, but there is still movement. I'm just curious what the motivation is for having values outside of the range we want to modify change?

**Comment by MStraeten** [comment]
nonlinear curves results in nonlinear change of colors - also known as banding. Usually not intended…
you may consult https://darktable-org.github.io/dtdocs/en/darkroom/processing-modules/curves/ for explanations of the modes
