### ISSUE TITLE
Lua scripts not imported

### ISSUE THREAD

**Issue by ericlief** [darktable-org/darktable#15976]
### Describe the bug

Followed tutorials on enabling Lua scripts present in my config dir. To take an example, I want to export to gimp using the script. 
My luarc:

File Edit Options Buffers Tools Help
require "tools/script_manager"
require "include_all"
require	"contrib/gimp.lua"
![Screenshot 2023-12-28 at 12 33 00 AM](https://github.com/darktable-org/darktable/assets/16747511/11ab2ae1-4791-496a-b052-14f142a4f4d5)
![Screenshot 2023-12-28 at 12 29 12 AM](https://github.com/darktable-org/darktable/assets/16747511/e27d739e-19ff-4e46-bbc1-6d1c13149c55)
![Screenshot 2023-12-28 at 12 28 20 AM](https://github.com/darktable-org/darktable/assets/16747511/e82577bc-aec5-4787-b2a7-711c74d9c13a)

### Steps to reproduce

Reopen DT and open preferences. There are only 3 options. In the YouTube tutorial, the guy had many other options. I can find no script manager anywhere. Where should this appear? 
I also have no option to export to gimp like the guy in the tutorial.

### Expected behavior

Enable the scripts

### Commit

4.6.0

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

13.6.1

### Describe your system?

M1 Macbook Air, 16GB (2019)

### Are you using OpenCL GPU in darktable?

No

**Comment by MStraeten** [comment]
You can see the script manager in the second screenshot at lower left side just bore the timeline …

**Comment by ericlief** [comment]
Thank you I must be blind hehe. That worked. The options in the video I saw were in preferences and must have been an earllier version.

**Comment by wpferguson** [comment]
You can start and stop lua scripts from script manager.  Some of the scripts do have preferences which show up in the Lua Options part of the settings dialog box.
