### ISSUE TITLE
Guide lines / grid do not appear when module 'rotate and perspective' is activated

### ISSUE THREAD

**Issue by guigri** [darktable-org/darktable#15984]
### Describe the bug

If you first activate the 'rotate and perspective' module for an image, the guides or the grid do not appear, although the grid display is configured in the module ('show guides' selected).
To make the grid visible, you have to close the module and then open it again by clicking on the module name. This is not a disaster, but a bit annoying. ;-)
It would be ideal if the grid appeared automatically as soon as the module is activated, at least if this behavior is configured in the module ('show guides' selected).
After the grid has been successfully displayed once, everything works as expected, i.e. the grid disappears when the module is deactivated and it is immediately displayed again when it is reactivated.

I have already observed this behavior in darktable versions older than 4.6.0.

### Steps to reproduce

1. Open an image in darkroom on which the module 'rotate and perspective' has not yet been applied.
2. Fold out / open module 'rotate and perspective' by clicking on the module name.
3. Activate module 'rotate and perspective' 
![grafik](https://github.com/darktable-org/darktable/assets/17358088/b887b091-1942-4527-a76b-a7cc7a9e9c0a)

Expectation: The grid/guide is displayed.
Instead, to make the grid visible: Close the module again and open / unfold it again by clicking on the module name

### Expected behavior

It would be ideal if the grid appeared automatically as soon as the module is activated, at least if this behavior is configured in the module ('show guides' selected).

### Where did you obtain darktable from?

OBS

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

kubuntu desktop, nothing special

### Are you using OpenCL GPU in darktable?

Yes

**Comment by gi-man** [comment]
Confirmed but I used different steps

1) Turn on guide lines (lines show)
2) Expand the `rotate and perspective` module (dont even need to turn it on) 
3) The guide lines turn off. 

If you turn on or expand the rotate module first and then turn on guides, they do work. 

4.7.0~git73.36e6a17b
