### ISSUE TITLE
Better readability

### ISSUE THREAD

**Issue by giovariot** [darktable-org/darktable#15994]
I tried exploring the app a little bit, even if I couldn't import images (cfr #15993) and noticed that readability is really poor. Most menus and windows (such as the settings one) show in my opinion too much text, items are almost the same size of settings groups titles (look down here at "Generale" and "Miniature" when compared with the options text.
<img width="1552" alt="Screenshot 2023-12-30 alle 19 35 09" src="https://github.com/darktable-org/darktable/assets/12408904/6168eba2-ef22-4e71-8a21-c6529cf79a54">

It is really nice to have great control of the program, but I think readability could be easily improved by separating settings sections with clear rectangles around the sections titles.

I have also noticed that around the interface buttons look very low contrast, I think both in use and disabled buttons should appear more contrasty as it would really help readability. Here is an example of the current interface.
<img width="302" alt="Screenshot 2023-12-30 alle 19 38 25" src="https://github.com/darktable-org/darktable/assets/12408904/ca173364-b247-49ec-8cf9-845294455997">

Also I think tabs should be more recognizable, maybe with a clear outline, as I just discovered by chance that "Immagini" and "Metadati" are actually interface tabs, not enabled buttons.

**Comment by MStraeten** [comment]
the more fancy the ui the less useful because the perception of the image to be edited is changed.
The UI is customizable via css - so you can change stuff yourself. maybe have a look at https://discuss.pixls.us/t/my-personal-darktable-theme/28942

**Comment by Nilvus** [comment]
darktable choice is to let the place to the image and avoid any distractions. Any choice have drawbacks. But on what you point, I have some other things to add:
- first, we already have other people asking for better UI but always WITHOUT proposing any solution (with respect of darktable choice stated above). Aurélien Pierre and I have worked on that UI and it's hard to have a readable UI while avoiding distractions.
- on your first screenshot, you probably have an issue on your side. I suppose you use darktable default choice, so rendering depends on fonts you use on your OS. On UI I worked on and on what I have on my side, contrast between titles and text is much better. See below:
![image](https://github.com/darktable-org/darktable/assets/45535283/66a65388-862c-46de-8e80-c1c04f1214c8)
- about many settings that overrides preferences, I completely agree but we also have the opposite: people asking for more settings. We can't please all people. About your only proposal about rectangles, I'm not sure it's the good way..
- about interface buttons, I don't see the issue on what you describe. You state that in use and disabled buttons lack of contrast but you post a screenshot of only disables buttons. In use buttons appears when an image is hovered and contrast is ok on my side. See screenshot below again where you will see in use and disabled buttons:
![image](https://github.com/darktable-org/darktable/assets/45535283/1b47cb3c-7e42-491d-8db3-17a4f69e6055)

I so have 2 things that I agree could be improved (I have other priorities in my life actually to do that by now):
- inactive tabs could be improved but I have tried the clear outline and that was not ok and hard to distinguish active and inactive tabs. I do not spent more time on that
- even though your UI is not what I have on my side, titles in settings could have more contrast

**Comment by scrste** [comment]
I do see both perspectives, but I do feel that there needs to be genuine choice which does not exist now. To my eye, all of the currently available UIs are various levels of illegible. As a relative beginner (coming from GIMP) I would love to be given the choice of a more visible UI so I could choose. I do find that the hard-to-read UI makes it harder for me to learn darktable and that's a serious drawback if you want to draw more people to the program.

I also note, in watching YouTube videos, that quite a number of the power users publishing videos have much more readable UIs than darktable offers natively. They obviously have used css to make their own UIs. I do not want to have to read up on CSS in order to have a more legible UI, I would like to be able to choose one from a menu. I understand that my choice may well not fit in with the perspective of a purist.

**Comment by scrste** [comment]
Sorry, "unreadable" is too strong a word, I should have said "hard to read."

A further thought -- would it be possible to have a button always available on the display somewhere that would permit virtually instantaneous switching between two chosen UIs -- one grey to be unobtrusive, and one with greater (perhaps user adjustable) contrast for learning the program and general ease of use and convenience?

**Comment by ptilopteri** [comment]
there is a way, but not a "single" button
config (gear wheel) -> general -> theme

**Comment by ralfbrown** [comment]
@giovariot #17245 added a high contrast theme which likely resolves this issue.
