### ISSUE TITLE
[Bug] Mask with detail threshold adjustment segfaults when low available memory

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#15999]
### Describe the bug

Originally reported at https://discuss.pixls.us/t/opencl-problem-dt-4-6-windows/41240/1

To reproduce, I had to setup darktablerc to use: `resource_small=128 4 64 **200**`

I reproduced on Windows 11 4.6.0 and Fedora KDE current master (4.7.0~git97.fcbe7dd5)

### Steps to reproduce

Use attached xmp or manually apply a mask to a D&S module and adjust the detail threshold.

CR3 and xmp here: https://discuss.pixls.us/t/open-cl-question-darktable-v4-5-0-816/39914/52?u=g-man

### Logfile | Screenshot | Screencast

```
     6.3712 blend with form CL         [full]           diffuse                (   0/   0) 1657x1106 scale=0.2373 --> (   0/   0) 1657x1106 scale=0.2373 IOP_CS_RGB, BLEND_CS_RGB_SCENE, no form
     6.3713 refine_detail_mask on GPU  [full]           diffuse                (   0/   0) 1657x1106 scale=0.2373 --> (   0/   0) 1657x1106 scale=0.2373 
     6.3713 [opencl memory] device 0: 110662836 bytes (105.5 MB) in use
     6.3713 [opencl memory] device 0: 153777156 bytes (146.7 MB) in use
     6.3760 [opencl memory] device 0: 153777208 bytes (146.7 MB) in use
     6.3764 [opencl memory] device 0: 153777156 bytes (146.7 MB) in use
     6.3965 [opencl memory] device 0: 110662836 bytes (105.5 MB) in use
     6.3967 [opencl memory] device 0: 67548516 bytes (64.4 MB) in use
     6.3977 distort detail mask        [full]           diffuse                (4668/   0) 2313x4660 scale=1.0000
     6.3977 distort detail mask        [full]           demosaic               (   0/   0) 6981x4660 scale=1.0000 --> (   0/   0) 1657x1106 scale=0.2373 
     6.3977 resample_1c_plain                                                  (   0/   0) 6981x4660 scale=1.0000 --> (   0/   0) 1657x1106 scale=0.2373 lanczos3
Segmentation fault (core dumped)
```

### Where did you obtain darktable from?

OBS

### darktable version

4.7.0~git97.fcbe7dd5

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 39 KDE X11

### Describe your system?

12GB 3060 Nvidia GPU

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia 3060 12GB 545.29.06

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

No LUA.
Changing from lanczos3 to bicubic

The OP on Pixls.us has a 4gb nvidia card and uses `default` for resource level. This should yield ~2.3Gb opencl memory (4-0.6) * (700/1024)

**Comment by gi-man** [comment]
I was wrong. It is not just OpenCL. It happens with low system memory too. 
resource_small=100 4 64 200 I have 16Gb system memory


```
     2.2713 transform colorspace CPU   [thumbnail]      channelmixerrgb        (   0/   0)  674x 450 scale=0.0966 IOP_CS_LAB -> IOP_CS_RGB
     2.2718 pixelpipe process CPU      [thumbnail]      channelmixerrgb        (   0/   0)  674x 450 scale=0.0966 --> (   0/   0)  674x 450 scale=0.0966 IOP_CS_RGB
     2.2750 pixelpipe process CPU      [thumbnail]      diffuse                (   0/   0)  674x 450 scale=0.0966 --> (   0/   0)  674x 450 scale=0.0966 IOP_CS_RGB
     2.2833 blend with form on CPU     [thumbnail]      diffuse                (   0/   0)  674x 450 scale=0.0966 --> (   0/   0)  674x 450 scale=0.0966 IOP_CS_RGB, BLEND_CS_RGB_SCENE, no form
     2.2834 refine_detail_mask on CPU  [thumbnail]      diffuse                (   0/   0)  674x 450 scale=0.0966 --> (   0/   0)  674x 450 scale=0.0966 
     2.3301 distort detail mask        [thumbnail]      diffuse                (3468/   0) 3510x4660 scale=1.0000
Segmentation fault (core dumped)

```

**Comment by todd-prior** [comment]
To reproduce, I had to setup darktablerc to use: resource_small=128 4 64 **200**


Is this different from setting small in preferences within the UI... I am a few commits behind you but I can set it to small on my system in the UI and set things to 128 iterations in the module and no crashing...

**Comment by gi-man** [comment]
> To reproduce, I had to setup darktablerc to use: resource_small=128 4 64 **200**
> 
https://darktable-org.github.io/dtdocs/en/special-topics/mem-performance/#darktable-resources

**Comment by gi-man** [comment]
I did a reset of the history to try this without so many modules. I can recreate it with just the `exposure` module using a mask and adjusting the detail threshold as long as I have low memory. Therefore, I'm going to edit the title again.

**Comment by jenshannoschwalm** [comment]
AThanks for reporting. High priority.
