### ISSUE TITLE
color zones picked positive/negative curves no longer work

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#15997]
It used to be possible to use the area color picker in color zones to automatically create a positive/negative curve by holding ctrl/shift respectively while selecting an area with the mouse, as documented in the user manual.

This no longer seems to work on the latest master -- holding ctrl/shift has no effect and just creates the control points without shifting them up/down. I suspect this has probably been lost as part of the consolidation of the color picker code.

darktable 4.7.0+97~gfcbe7dd5b1 on ArchLinux

**Comment by todd-prior** [comment]
Your a little further ahead than me but it works fine on my windows 11 install... at 4.7 + 73...

![image](https://github.com/darktable-org/darktable/assets/44409419/b5f8a231-f216-4238-acfe-898ef8de9d03)

**Comment by elstoc** [comment]
Hmm there must be some odd thing I did beforehand that broke it because it works fine for me now too. Will close for now and reopen if I can reproduce later

**Comment by todd-prior** [comment]
> Hmm there must be some odd thing I did beforehand that broke it because it works fine for me now too. Will close for now and reopen if I can reproduce later

I feel like I have seen this before to but I blamed my old keyboard... I wonder if the state of a certain module esp maybe one that uses a picker and or interacting with the color picker could create a unique issue from time to time??
