### ISSUE TITLE
Apply preset based on filename or Exif field

### ISSUE THREAD

**Issue by kengiskan** [darktable-org/darktable#16006]
I'm using darktable since version 2.x, really satisfied and happy to discover new features each year. I still prefer Darktable over lightroom, but in some situations (high iso, motion blur) i need to prepare the files before using darktable.

**Is your feature request related to a problem? Please describe.**
In my wokflow, i often use other software (topaz photo ai for denoise/sharpen) to prepare the raw before editing in Darktable. I cannot avoid some modules to apply (lens correction..), - apply some presets only on that type of file - because all default presets fields are the same (manufacturer, model, lens, iso...).

**Describe the solution you'd like**
I would like to have a new field in the automatic presets which allow the filtering on filename  ex  *.DNG, *topaz*... 

**Alternatives**
Adding a preset filter on any EXIF field, like software, filename...

Thanks for your attention,

**Comment by wpferguson** [comment]
It is possible to do this with a Lua script.
