### ISSUE TITLE
Darktable 4.6: Raw Chromatic Aberration causes munmap_chuck(): invalid pointer crash with SRW files and unhandled installtation exception

### ISSUE THREAD

**Issue by WoVollmer** [darktable-org/darktable#16007]
### Describe the bug

Version 4.0 was so far working without problems. Now I have updated darktable 4.0 => 4.6. 
I got the information that an unhandled exception occured (backtrace is uploaded).
However, starting darktable and working with lighttable is running well. 
But **darktable is shutting down by selecting the darkroom view for a raw picture**. 
In between I got once the notice that there is an OpenCL initilization issue but OpenCL support is not activated (screenshot preferences > processing is uploaded). For a jpg pcture I have so far no shutdown issue.

### Steps to reproduce

1. start darktable
2. click on raw picture to develop in the darkroom view
3. darktable is shutting down.

### Expected behavior

darktable should allow picture development in darkroom view

### Logfile | Screenshot | Screencast

[darktable_bt_NTW5G2.txt](https://github.com/darktable-org/darktable/files/13812080/darktable_bt_NTW5G2.txt)
![darktable-pref_processing](https://github.com/darktable-org/darktable/assets/35953268/7f4bb2ec-219f-4a6a-819c-c92db685bf1c)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0 install file darktable-4.6.0-win64.exe, downloaded on Dec 28, 2023

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Home 22H2 Build 19045.3803

### Describe your system?

Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz   2.71 GHz 16GB
On-Board Graphic Intel® HD Graphics 530

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reproducible with RAW pictures, not with Jpeg pictures.
The steps above reproducible with a fresh edit.
Lua scripts are not in use.

**Comment by WoVollmer** [comment]
Hi, Thanks for fast response. 
I have run C:\Program Files\darktable\bin>darktable -d common output
and have uploaded the
    Debug log and output will be written to this file:
    C:\Users\Wolfgang\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13813448/darktable-log.txt)

**Comment by WoVollmer** [comment]
Hi, I have done some further investigations and found the following dependencies:

- successfully opening an image in the darkroom depends on the modules used in the corresponding image style
- if **_raw chromatic aberrations_** is part of the image style, darktable will be shut down when selecting the darkroom view for this raw image.

After successfully opening a raw image w/o the **_raw chromatic aberrations_** module in the image style in the darkroom, I can work w/o issues. When I select and activate the **_raw chromatic aberrations_** module  darktable also shuts down. This is easily reproducible for me.

**Comment by gi-man** [comment]
You closed this Issue as complete. I did not look further into it. Please reopen and edit the title to reflect the raw  chromatic aberration issue you describe. Please include an example of the raw file, the xmp and maybe even the style. If you can create a log with the module off and turning it on with the crash, it might be helpful.

**Comment by WoVollmer** [comment]
The issue was only closed by mistake on my part, therefore reopened.
Upload of a raw file (*.SRW) and of  a xmp-file (*.SRW.xmp) is not possible, since GitHub "don’t support that file type".

Instead I uploaded a darkroom screenshot with history and camera info (Samsung NX500 with lens Samsung NX 16-50mm F3.5-5.6 PZ ED OIS). After the screenshot I activated the raw chromatic aberration module and darktable crashed. The same thing happens now when I try to open this image in darkroom.

After overwriting the "crashing style" with the previous one without the raw chromatic aberration module, the image is editable in darkroom again. 

![dt_screenshot_history_imgage_info](https://github.com/darktable-org/darktable/assets/35953268/6bdd8e3c-0f31-4467-a731-511a3d0e85d7)

**Comment by gi-man** [comment]
> Upload of a raw file (_.SRW) and of a xmp-file (_.SRW.xmp) is not possible, since GitHub "don’t support that file type".

Upload to dropbox/any other online sharing site and then share a link.

**Comment by WoVollmer** [comment]
Hi, i have uploaded the sample raw file (.SRW) and the corresponding xmp-file (.SRW.xmp) to the folder _darktable_issue_16007_ which is accessible via the link https://c.1und1.de/@519515387570690346/PgtKts6rQAODwpaMuu20ww .

**Comment by gi-man** [comment]
I can reproduce. Fedora 39 KDE 4.7.0~git98.bce83d51

WoVollmer: Can you extend the duration of the share files for at least 1 week? Also, edit your title to something like: [bug] Raw Chromatic Aberration causes munmap_chuck(): invalid pointer crash with SRW files.

```
    17.4003 [dev_pixelpipe] module `highlights' min: (0.003833) max: (2.072957) [preview]
    17.4003 pixelpipe_cache_get        [preview]        cacorrect              IOP_CS_RAW line  3(10) at 0x7fa5717ec040. hash=6e3d8207af713cda
    17.4010 [opencl memory] device 0: 0 bytes (0.0 MB) in use
    17.4011 pixelpipe process CPU      [preview]        cacorrect              (   0/   0) 1345x 897 scale=1.0000 --> (  18/  54) 1304x 767 scale=1.0000 IOP_CS_RAW
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

Do we support this camera sensor type with the Raw CA module? I know we block the use of this module with the fuji xtran sensors.

**Comment by WoVollmer** [comment]
Hi, the the duration of the share files is already one month, up to Feb 4, 2024.
