### ISSUE TITLE
Translation Italian

### ISSUE THREAD

**Issue by gabfus** [darktable-org/darktable#16001]
Hello, why the manuals pdf are not translate in Italian?

Thanks for your job

**Comment by victoryforce** [comment]
Because the Italian translation was not completed by the contributors. You can help complete it here: https://weblate.pixls.us/projects/darktable/dtdocs/it/

I am closing this issue as it is not related to the program itself, the documentation is a separate project.

**Comment by Vitoanna** [comment]
First of all excuse me for my very poor English.  I've downloaded the version 5.0 for Mac and I don't find  Italian translation. This is a my mistake or there isn't? If it is a my mistake, how I can resolve? tank you

**Comment by victoryforce** [comment]
> I've downloaded the version 5.0 for Mac and I don't find Italian translation. This is a my mistake or there isn't?

@Vitoanna No, this is not your mistake. The Italian translation has not been updated for the darktable 5.0.0 release. We don't ship translations that contain too many untranslated lines, so there is no Italian translation in this release as it was too incomplete.

This is also not something we as a project can fix. Translations are done by people who know the language and volunteer to contribute. If you find such a person and ask them to update the translation, the translation may appear again in future releases.

**Comment by Vitoanna** [comment]
Ok. Tank you.

vito


Il giorno mar 21 gen 2025 alle 12:56 Victor Forsiuk <
***@***.***> ha scritto:
