### ISSUE TITLE
Folder Sorting Issue in DT 4.6

### ISSUE THREAD

**Issue by luxagraf** [darktable-org/darktable#16018]
### Describe the bug

Darktable 4.6 has reversed the sort order of the folders view in the collections module. Here's a screen shot of the view in 4.4:

![dt44](https://github.com/darktable-org/darktable/assets/24277896/14a9c9dd-6197-466f-8505-93980f4b553a)

And this is what the same thing looks like in 4.6:

![dt46](https://github.com/darktable-org/darktable/assets/24277896/e33e4e1d-6a3a-4731-ad85-1639f7bfea60)

### Steps to reproduce

Import folders named by year
Select "folder" view in collections module
the oldest folder will be at the top

### Expected behavior

in darktable 4.4 the newest folder was at the top

### Where did you obtain darktable from?

distro packaging

### darktable version

darktable 4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux x86_64, Kernel: 6.6.8-arch1-1

### Are you using OpenCL GPU in darktable?

No

**Comment by luxagraf** [comment]
Forgot to say that I’ve read through the documentation and played with the new settings under the collections module preferences, but I can’t seem to get the old sort order back for the folder view. Can anyone point out where I’ve gone wrong here?

**Comment by gi-man** [comment]
I reproduce on Fedora 39 KDE 4.7.0~git98.bce83d51 Changing the module preference to sort descending has no effect when the collection is set to `folder`. I'm assuming it is an unintended effect of: https://github.com/darktable-org/darktable/pull/15392

**Comment by gi-man** [comment]
Hmm. It seems similar to this issue, but with folders vs filmstrip. https://github.com/darktable-org/darktable/issues/15669

If not addressed then, the tooltip needs updating. 
![image](https://github.com/darktable-org/darktable/assets/97920861/933d3e60-8658-4f09-b242-b3f4d00161d5)

**Comment by luxagraf** [comment]
Hmm, yeah looks like an "ASC" got added:

https://github.com/darktable-org/darktable/pull/15392/commits/c42e03da2f0395e5825512b4a4d80c162692ebd0#diff-2c4ad8c3aa04d783a05735ec0fbeb46a420d90c81153134287e320ff0a52f36b

**Comment by TurboGit** [comment]
This is expected behavior, folder are always named ascending. What you are looking for is a date folder view.

**Comment by gi-man** [comment]
But this was not the behavior in 4.4

**Comment by TurboGit** [comment]
> But this was not the behavior in 4.4

Right, it has been changed to:
- Always sort in alphabetical order all names
- All date based collection either ascending or descending based on the preference

Why?

If you select for example descending in preference to get the recent ones first and older at the end of the list you'll also get the Z entries for collection/folder/cameras... first which is not really user friendly.

A better approach to please every one would certainly to record sorting automatically (removing the preference altogether) for each collection kind independently. But that's something not that trivial UI wise.

**Comment by gi-man** [comment]
I see the change. I use folder 99% of the time and now I need to navigate all the way to the bottom to find 2023.

Automatic would be a nice but complex solution. What about just making the sorting button available instead inside the preference? Default it to the last state and just let the user quickly switch it.

**Comment by luxagraf** [comment]
Hmm, I guess what confuses me is the notion of what's use-friendly and what's not. What I was trying to say with this bug report is that the current approach is not user-friendly. It might be logical, I don't debate that, but it's not user-friendly to me. Are their metrics suggesting that the old behavior was confusing to users? Or was it just changed because it wasn't logical?

I can't think of another Linux app that doesn't allow sorting to be reversed. Unfortunately I don't know C well enough tackle this, but I hope someone else does.

**Comment by bengtfalke** [comment]
so it is not possible any more to change the sorting order of the folders in the Collection view? I have pulled all my hair out in trying to change that preference setting in the Collections from Ascending to Descending.... it is not possible... right?

**Comment by brunolas981** [comment]
I don't like it now either

**Comment by elstoc** [comment]
I would also prefer to have the option of reverse sort by name. It's not uncommon to have folders start with a date and having an always-ascending sort is a pain when you have lots of folders.

And AIUI the "sort by date" in film roll is not a sort by folder date but the date you first imported into darktable, which is also far from ideal. For example I have some stuff on an old camera that I haven't imported yet, but I have imported more recent images. So now there's no ordering that isn't screwed up in some way -- either unchangeably-ascending or by date with some stuff weirdly out of order.

**Comment by TurboGit** [comment]
I'm on it... stay tuned.

**Comment by bengtfalke** [comment]
Thank you for that, TurboGit!

**Comment by TurboGit** [comment]
See #16072
