### ISSUE TITLE
import not working as of 4.6.0

### ISSUE THREAD

**Issue by Spark198rus** [darktable-org/darktable#16029]
### Describe the bug

After upgrading to 4.6.0 , the functionality of import stopped working. When i click the import button, the import window appears, i select what i need, click import, it even shown "imported N images" , while in fact zero were imported. Have two machines on linux mint, tried on both. Tried system and flatpak. Tried removing all the configuration on both machines, for both versions.

### Steps to reproduce

1) Click "add to library" on import tab
2) Select some images
3) Click "add to library"

### Expected behavior

darktable should import selected images

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Mint 21.2 Cinnamon

### Describe your system?

HP EliteBook 840 G1
Intel i5-4300U
16G

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- no
- both
- yes
- ...
- yes
- no

**Comment by gi-man** [comment]
Duplicate and fixed on master last week.

https://github.com/darktable-org/darktable/pull/15894
