### ISSUE TITLE
OpenCL ha dejado de funcionar

### ISSUE THREAD

**Issue by Matueca** [darktable-org/darktable#16028]
### Describe the bug

Hasta la versión 4.2.1 de Darktable el compilador openCl ha funcionado correctamente en mi ordenador. A partir de esa versión, el openCL no trabaja con la misma configuracion de hardware que tenía. 

### Steps to reproduce

darktable 4.6.0
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.1568 [dt_get_sysresource_level] switched to 1 as `default'
     0.1569   total mem:       23989MB
     0.1575   mipmap cache:    2998MB
     0.1575   available mem:   11994MB
     0.1576   singlebuff:      187MB
     0.1685 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded, preference 'default path'
     0.5588 [opencl_init] found 3 platforms
     0.5589 [opencl_init] detected wrong OpenCL platforms setup
     0.5601 [opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.

### Expected behavior

Al ejecutar "darktable-cltest.exe" debería activarse la GPU nvidia que tengo , y que ha trabajado bien hasta la version 4.2.1

### Logfile | Screenshot | Screencast

darktable 4.6.0
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.1568 [dt_get_sysresource_level] switched to 1 as `default'
     0.1569   total mem:       23989MB
     0.1575   mipmap cache:    2998MB
     0.1575   available mem:   11994MB
     0.1576   singlebuff:      187MB
     0.1685 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded, preference 'default path'
     0.5588 [opencl_init] found 3 platforms
     0.5589 [opencl_init] detected wrong OpenCL platforms setup
     0.5601 [opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

 Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)

### Describe your system?

System Information
------------------
      Time of this report: 1/4/2024, 17:18:43
             Machine name: DESKTOP-CJKHIPD
               Machine Id: {90F20CD0-FB27-44B7-A92D-1F463D004441}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: Z97-HD3
                     BIOS: BIOS Date: 07/31/15 13:12:45 Ver: 04.06.05 (type: BIOS)
                Processor: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 CPUs), ~3.2GHz
                   Memory: 24576MB RAM
      Available OS Memory: 23990MB RAM
                Page File: 4747MB used, 22826MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 144 DPI (150 percent)
       System DPI Setting: 144 DPI (150 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.3636 64bit Unicode
---------------
Display Devices
---------------
           Card name: NVIDIA GeForce RTX 2060
        Manufacturer: NVIDIA
           Chip type: NVIDIA GeForce RTX 2060
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_10DE&DEV_1F03&SUBSYS_C7571462&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
 Device Problem Code: No Problem
 Driver Problem Code: Unknown
      Display Memory: 24069 MB
    Dedicated Memory: 12075 MB
       Shared Memory: 11994 MB
        Current Mode: 3840 x 2160 (32 bit) (29Hz)
         HDR Support: Supported
    Display Topology: Internal
 Display Color Space: DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
     Color Primaries: Red(0.679688,0.315430), Green(0.280273,0.673828), Blue(0.152344,0.049805), White Point(0.312500,0.329102)
   Display Luminance: Min Luminance = 0.392300, Max Luminance = 295.380310, MaxFullFrameLuminance = 237.846802
        Monitor Name: Generic PnP Monitor
       Monitor Model: LG HDR 4K
          Monitor Id: GSM7706
         Native Mode: 3840 x 2160(p) (60.000Hz)
         Output Type: HDMI
Monitor Capabilities: HDR Supported (BT2020RGB BT2020YCC Eotf2084Supported )
Display Pixel Format: DISPLAYCONFIG_PIXELFORMAT_32BPP
      Advanced Color: AdvancedColorSupported 
         Driver Name: C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_cafe8f782ed8b97e\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_cafe8f782ed8b97e\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_cafe8f782ed8b97e\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdsig.inf_amd64_cafe8f782ed8b97e\nvldumdx.dll
 Driver File Version: 31.00.0015.4633 (English)
      Driver Version: 31.0.15.4633
         DDI Version: 12
      Feature Levels: 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1
        Driver Model: WDDM 2.7
 Hardware Scheduling: Supported:True Enabled:True 
 Graphics Preemption: Pixel
  Compute Preemption: Dispatch
            Miracast: Not Supported
      Detachable GPU: No
 Hybrid Graphics GPU: Not Supported
      Power P-states: Not Supported
      Virtualization: Paravirtualization 
          Block List: No Blocks
  Catalog Attributes: Universal:False Declarative:True 
   Driver Attributes: Final Retail
    Driver Date/Size: 06/12/2023 1:00:00, 774912 bytes
         WHQL Logo'd: Yes
     WHQL Date Stamp: Unknown
   Device Identifier: {D7B71E3E-5C43-11CF-CB65-58E70EC2D235}
           Vendor ID: 0x10DE
           Device ID: 0x1F03
           SubSys ID: 0xC7571462
         Revision ID: 0x00A1
  Driver Strong Name: oem6.inf:0f066de30ddb0b2c:Section022:31.0.15.4633:pci\ven_10de&dev_1f03&subsys_c7571462
      Rank Of Driver: 00CF0001

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Con y hasta la versión 4.2.1 el compilador "darktable-cltest.exe" funciona correctamente y se activa la gpu.
A partir de esa versión y superiores, no se activa la gpu. Debo indicar que con la última versión, la 4.6.0 darktable trabaja 
mas rápido, aúnque la gpu sigue sin funcionar.

**Comment by gi-man** [comment]
Ensure you install the nvidia drivers directly from www.nvidia.com for your windows system.

**Comment by Matueca** [comment]
Los controladores son los últimos dado por el fabricante, y se han instalado desde la pagina de nvidia

**Comment by gi-man** [comment]
What's the version number of the Nvidia driver?

**Comment by Matueca** [comment]
Versione: 546.33  *WHQL*
Fecha de publicación: 2023.12.12
Sistema operativo: Windows 10 64-bit, Windows 11
Idioma: Español (España)
Tamaño: 669.35 MB

**Comment by victoryforce** [comment]
>  `0.5588 [opencl_init] found 3 platforms`
>  `0.5589 [opencl_init] detected wrong OpenCL platforms setup`
>  `0.5601 [opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.`

As I understand it, you have a _maximum_ of 2 OpenCL-capable devices: Intel (integrated GPU) and a separate Nvidia card (GeForce RTX 2060). However, the test finds 3 platforms. This means that two drivers are installed for some device in the system. This is an incorrect and unsafe setup, so starting with version 4.6, the duplicate platform is prohibited by the safety check.

You should search among the installed drivers for a duplicate for one of the OpenCL-capable devices and remove it. Also, if the `OpenCL™ and OpenGL® Compatibility Pack` is installed, it must be removed as well (it is only needed for devices that do not have native OpenCL drivers).

@jenshannoschwalm What do you think about making the messages in this safety check even more verbose? For example, report for which platform a duplicate was found?

**Comment by jenshannoschwalm** [comment]
Yes, we should do so :-) We did the safety-check as a bugfix after 4.6 string freeze so used an "approximate error message" for UI feedback. Feel free to go for this :-) (Hope you are warm & mostly safe at home btw)

**Comment by victoryforce** [comment]
> Feel free to go for this :-)

OK, wrote it down in my to-do list. I have higher priority entries on this list so far, so I won't start right now, but I will get around to it someday. :)

> (Hope you are warm & mostly safe at home btw)

Thank you! The power grid is much more protected this winter, so there have been no blackouts and power outages yet (which is a good thing, because I still can't get rid of the cough that started last winter). So we are warm, it was even a little hot, because the house on the street next to us was burned down during the last missile attack (sorry for the dark humor 🙂). But we are safe so far.

**Comment by Matueca** [comment]
Haha, thanks!

**Comment by Matueca** [comment]
Ok, I'll check it out.

**Comment by Matueca** [comment]
Al fin encontré la solución, gracias a las indicaciones de Victor Forsiuk. Tenia los controladores duplicados de Intel (GPU integrada) , que se duplicaron, probablemente con las actualizaciones que ofrece intel, y las instalé por error. Gracias a todos los que me proporcionaron ayuda, en especial  a Victor Forsiuk. ,y mis felicitaciones a Github por ofrecer un lugar para buscar soluciones a problemas cotidianos. Un saludo a todos.


Matueca

**Comment by Matueca** [comment]
Gracias por la ayuda.
