### ISSUE TITLE
Missing AVIF export in darktable 4.6.0

### ISSUE THREAD

**Issue by kadykov** [darktable-org/darktable#16026]
### Describe the bug

In the export module the export in the AVIF format is missing.
In darktable 4.4.2 this option was present and it was working great.

### Steps to reproduce

In darkroom or in lighttable open export module and try to find AVIF format export.

### Expected behavior

AVIF format export should be available

### Logfile | Screenshot | Screencast

![Screenshot from 2024-01-04 15-15-30](https://github.com/darktable-org/darktable/assets/62546709/0f558365-33c7-43e3-a802-3eed53d55857)

### Where did you obtain darktable from?

Flatpak from flathub

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora Silverblue 39

### Describe your system?

All the images are in a NFS storage.

#### System Details Report
---

##### Report details
- **Date generated:**                              2024-01-04 15:21:19

##### Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad T14 Gen 1
- **Memory:**                                      40,0 GiB
- **Processor:**                                   AMD Ryzen™ 5 PRO 4650U with Radeon™ Graphics × 12
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               256,1 GB

##### Software Information:
- **Firmware Version:**                            R1BET77W(1.46 )
- **OS Name:**                                     Fedora Linux 39.20240103.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.8-200.fc39.x86_64

**Comment by kmilos** [comment]
Please report any [flatpak issues to their bug tracker directly](https://github.com/flathub/org.darktable.Darktable), it is not maintained by the darktable project.

**Comment by hfiguiere** [comment]
> Please report any [flatpak issues to their bug tracker directly](https://github.com/flathub/org.darktable.Darktable), it is not maintained by the darktable project.

the problem is that the build recognized avif was detected:
```
-- The following OPTIONAL packages have been found:

...

 * libavif

```

But then at runtime, *in the console*

```
     0.5035 [imageio_load_module_format] failed to open `avif': /app/lib/darktable/plugins/imageio/format/libavif.so: undefined symbol: avifRGBImageSetDefaults
```

So there is something wrong somewhere and the build system let it happen.
