### ISSUE TITLE
Fujifilm Cameras

### ISSUE THREAD

**Issue by joao-lamares** [darktable-org/darktable#16037]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Alternatives**

**Additional context**

**Comment by joao-lamares** [comment]
I do not know if I do it wrong but I can't see my message so:
In lens correction I can't find several cameras made by fujifilm, like X-T2, X-T3, X-T4, X-T5, X-H1, X-H2, X-H2S, X-S10, X-S20, X-Pro2, ... also I cant find the profile for Tokina SZ 8mm F2.8 Fisheye.
Can you help?
Thanks
Joao

**Comment by MStraeten** [comment]
Please provide infos as asked in the bug report - it seems your lensfun database is outdated or broken since several those cameras are supported since a couple of years.

**Comment by joao-lamares** [comment]
Sory, I can't find the bug report.
I agree with you.  My Darktable version is 4.6.0 for Ubuntu Studio, but the lensfun database seems to be out of date. How can I update it?
Thank you for you time.

**Comment by kmilos** [comment]
Please seek end user support at https://discuss.pixls.us/c/software/darktable/19 or Ubuntu Studio forums.

This is a place for actual dt bugs and development, so closing as this is lensfun related.
