### ISSUE TITLE
Cannot read white balance: darktable does not process one of many pictures from the same camera, from the same day

### ISSUE THREAD

**Issue by klic** [darktable-org/darktable#16032]
### Describe the bug

While working on a row of raw images from Olympus E-M10 Mark III, DT does not process one image of many, claiming it cannot read the white balance

### Steps to reproduce

Click on the specific image in lightroom

### Expected behavior

Darktable should display this image in darkroom, as with the surrounding images as well

### Logfile | Screenshot | Screencast

Messages are:
   198,6084 [temperature] failed to read camera white balance information from `2023.09.27-13.39.26.orf'!
   199,0386 [temperature] `Olympus E-M10 Mark III' color matrix not found for image
   199,0387 [temperature] failed to read camera white balance information from `2023.09.27-13.39.26.orf'!
   199,0389 [temperature] failed to read camera white balance information from `2023.09.27-13.39.26.orf'!
   199,0553 [colorin] could not find requested profile `Standard-Farb-Matrix'!

### Where did you obtain darktable from?

distro packaging

### darktable version

darktable-4.4.2-1.fc38.x86_64

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz, 16GB Ram, X11, /usr/lib64/libgtk-3.so.0.2406.32, Intel Corporation CometLake-S GT2 [UHD Graphics 630] (rev 03)
Same on another computer, same sw version, Intel(R) Pentium(R) CPU G4560 @ 3.50GHz, Intel Corporation HD Graphics 610 (rev 04)

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I can provide you with the image, but it's 15MB

**Comment by ralfbrown** [comment]
That file is likely corrupt.  Note that many image viewers will show the embedded JPEG, so just because other programs can show the image does not mean that it is actually OK.

If you haven't formatted/erased/overwritten the memory card yet, copy the file again and see whether that helps.

**Comment by klic** [comment]
Guess this is the best explanation, thanks
