### ISSUE TITLE
Filmic RGB and Color Balance RGB show black screen with RustiCL driver

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#16036]
### Describe the bug

I know RustiCL is in heavy development right now, but I guess it might be worth reporting the issue I got in DT.

Using MESA 23.3.2 drivers
RustiCL drivers
AMD 6650XT GPU

I didn't experience any crashes or freezes, but was unable to use Filmic and Color Balance RGB modules in ALL images.
That includes, CR3, TIFF and JPG
The images goes completely black.

### Steps to reproduce

1. Install RustiCL driver and enable it in Environment with RUSTICL_ENABLE=radeonsi 
2. Start DT, it will recognize OpenCL
3. Try to change Filmic RGB or Color Balance RGB modules
4. Notice the image turns completely black
5. Disabling OpenCL or uinstalling Rusticl fixes this
6. Happens exclusively with Rusticl (all other OpenCL drivers work normally)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6

### What OS are you using?

Linux

### What is the version of your OS?

Arch rolling

### Describe your system?

Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.9-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6650 XT
Manufacturer: Micro-Star International Co., Ltd
Product Name: MS-7C02
System Version: 1.0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD 6650XT MESA

**Comment by jenshannoschwalm** [comment]
I really don't think it's a darktable issue at all, maybe some rustcl stuff, maybe your system runs wild, maybe something.... Nothing to be discussed here at all. You might assist the rustcl people if you into that kind of stuff. a

**Comment by TurboGit** [comment]
Agreed, not a dt issue and nothing to do on our side, we have working implementation for Windows driver, NVIDIA and AMD on Linux. So pretty sure RustiCL is still missing some needed features.

**Comment by karolherbst** [comment]
btw, this issue should be fixed with mesa-24, in case somebody reads this later or ping me if it isn't.
