### ISSUE TITLE
The collection selection does not work correctly

### ISSUE THREAD

**Issue by Pepa-D750** [darktable-org/darktable#16031]
### Describe the bug

I am solving the problem of how many times I used an aperture in the range of 2.8 to 4 with a Tamron 24-70 lens on a Nikon D750 while rating the image with 3 stars and a red mark at the same time. As long as I don't enter the aperture selection, everything filters fine. As soon as I try to add aperture selection nothing is found.
Example:
collection: Nikon-D750
rating: 3 stars
color mark: red
lens: Tamron 24-70mm ..
aperture: 2.8 -- it doesn't pick anything here

Am I doing something wrong or where is the problem?
Thanks for the direction if I'm doing it wrong.

### Steps to reproduce

1. collection: Nikon-D750
2. rating: 3 stars
3. color mark: red
4. lens: Tamron 24-70mm ..
5. aperture: 2.8 -- it doesn't pick anything here

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Leap 15.5

### Are you using OpenCL GPU in darktable?

Yes

**Comment by AlicVB** [comment]
I can't reproduce here...
Can you check some points : 
1. (to be sure) : with all the filters except aperture, you have image with aperture 2.8 shown, right ?
2. What if you use only the Aperture filter ?
3. How do you set the filters ? with the collection module, the filtering module or the top toolbar ?
4. Can you provide a screenshot with all the filters set ?

Thanks !

**Comment by Pepa-D750** [comment]
Hello, 
there is probably a problem with the aperture selection. I am attaching screenshots of a selection of several different filters. In this case, I always use the filters on the left side of the screen, see images. I hope this helps you to fix the problem that was already in version 4.4.2. thank you and have a nice day.

Pepa

![Good](https://github.com/darktable-org/darktable/assets/155672682/95ba2524-512a-4a01-8b8a-d768fe55910e)
![MAX-value-F](https://github.com/darktable-org/darktable/assets/155672682/c66fec72-f11d-468b-aea1-2c84a5db443f)
![MIN-value-F](https://github.com/darktable-org/darktable/assets/155672682/515eabee-8707-4dd5-bc1d-fd93aa89dceb)
![Screen-4014](https://github.com/darktable-org/darktable/assets/155672682/4bdbe78c-818d-4d66-a602-3c5ed21fbcef)

![Bed-F2 8-](https://github.com/darktable-org/darktable/assets/155672682/d80e783c-8ae8-489b-82d8-ea2f2943d5be)
![Darktable-version](https://github.com/darktable-org/darktable/assets/155672682/096d4383-5bd1-401d-b7d5-8d7889acf0ae)
![F-all-pictures-27076](https://github.com/darktable-org/darktable/assets/155672682/24826259-47b5-4835-9fa1-44ea02bdae1a)
![F2 8-5 0-bed](https://github.com/darktable-org/darktable/assets/155672682/165780ba-a46d-4403-b319-ba4f3de01ee8)
![F19-bed-pictures-27076](https://github.com/darktable-org/darktable/assets/155672682/90f5d651-8fd7-4af2-b1c6-9c5b63540dd3)
![F19-only-one](https://github.com/darktable-org/darktable/assets/155672682/fb4e6a7a-0db3-4161-8403-d5a579515be3)
![Good-F-question mark](https://github.com/darktable-org/darktable/assets/155672682/8b28be07-6fb1-449a-9c3d-eba889667c96)

**Comment by Pepa-D750** [comment]
Hello,
there is probably a problem with the aperture selection. I am attaching
screenshots of a selection of several different filters. In this case, I
always use the filters on the left side of the screen, see images. I hope
this helps you to fix the problem that was already in version 4.4.2. I put
the pictures on the website because it didn't go through my email.
Thank you and have a nice day.
Pepa

čt 4. 1. 2024 v 20:57 odesílatel AlicVB ***@***.***> napsal:

**Comment by zisoft** [comment]
It is a locale issue and I can reproduce!

In the german locale (and @Pepa-D750 locale as well) the decimal separator is a comma.
So f/2.8 gets to f/2,8 (see the screenshots above).

**Comment by MStraeten** [comment]
Maybe similar to https://github.com/darktable-org/darktable/issues/16034
a comma seems to be used to split the term there…
Please validate that for this case with `darktable -d sql` and search for the f-stop

**Comment by zisoft** [comment]
In this case it is the locale which needs to be taken into account for the aperture values.

**Comment by Pepa-D750** [comment]
So it should work in the next version? Am I correct?
Thank you and have a nice day.
Joseph

út 16. 1. 2024 v 19:34 odesílatel Mario Zimmermann ***@***.***>
napsal:

**Comment by Pepa-D750** [comment]
I have one more question. Would it not be possible when setting the colors
using "Datacolor Spyder Checkr" in the color calibration module - to
calibrate using the eyedropper - after setting the corners of the table and
when calculating the correct values. Make only one press and the tuning
between the reading of these values in this module and the adjustment in
the exposure module should not be done manually as it is now. Now I press
in the calibration module, calculate the values for setting the exposure
module. I go to the exposure module and set it there. I return to the
calibration module, calculate again and set the new values again in the
exposure module, and so sometimes it is necessary to do this more than ten
times before the values for adjusting the exposure do not change. This
could certainly be done automatically, these are just calculations that can
predict the correct value. It seems to me that human activity is somewhat
unnecessary here. But maybe there is no other way. What do you think? What
is your view on this matter?
Thank you and have a nice day.
Joseph

út 16. 1. 2024 v 19:34 odesílatel Mario Zimmermann ***@***.***>
napsal:

**Comment by zisoft** [comment]
This is out of scope of this so please open a new issue.
