### ISSUE TITLE
UI issue on Surface 8 Pro and Windows 10

### ISSUE THREAD

**Issue by Rundmaus** [darktable-org/darktable#16048]
### Describe the bug

When launching Darktable while controlling the Tablet via the Touch screen, the first touch/click on any menu item in the lighttable view catches the Focus on that menu item. Any following touch/click on an arbitrary screen position causes exactly the same response as the first Touch, i.e. opens/closes the same menu again and again, regardless of the touch position on the screen. After minimizing the window and restoring it again, another UI item can be selected, then the same happens with the new item, making the Software completely unusable.

The issue occurred on a fresh install right from the factory, all Windows Updates are done. Darktable is the only user installed software at this point. Issue occurs with Opencl enabled and disabled, no difference.

### Steps to reproduce

1. Open Darktable.
2. Click on any menu in the lighttable view to open it. (White triangles)
3. Click on any other menu item.

### Expected behavior

React to any input on the UI normally.

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/13851426/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro 22H2

### Describe your system?

Microsoft Surface 8 Pro, 16GB RAM, 256GB SSD

### Are you using OpenCL GPU in darktable?

No

**Comment by gi-man** [comment]
Do you have the same issue using a mouse?

**Comment by Rundmaus** [comment]
I will try and report back. Unfortunately I have only the tablet available rn, no pen yet. And as the tablet has only USB-C connectors, I need to find an adaptor for the mouse.

**Comment by Rundmaus** [comment]
The issue does *not* occur with a mouse. Everything works as expected then. So currently only the touchscreen input is definitely affected. I will test active pen input next week after obtaining a pen.

**Comment by gi-man** [comment]
We don't have a touch screen development environment. I think we assume we should always use a mouse. The sliders and buttons would be too hard to do with a finger touch.

**Comment by Rundmaus** [comment]
Pure touchscreen operation would be hard, I agree. But the requirement of a mouse kind of defeats the option of mobile use. I originally intended to use it with a pen. After the successful test with the mouse, I hope pen input will work as well.

If you regard touch input as not relevant for the use case, the issue could be closed if you want. Would you think I could reopen it when against all expectations pen input should fail?

I just wanted to make sure the developers know that the program behaves erratically with a more and more common input method.

Thanks for looking into it!

**Comment by MStraeten** [comment]
darktable isn't designed to work with a touch interface (there aren't that many linux driven mobile devices around that are supported by gtk3). 
Even if you're using a pen and a graphic tablet, the pen is expected to be handled like mouse actions by your os.
So as long as your os doesn't mimic mouse behaviour on touch or pen actions don't expect it to work properly.

**Comment by Rundmaus** [comment]
Tested pen input today and it works fine. The issue can be closed from my point of view.
