### ISSUE TITLE
Import module is too slow and needs multiple selection for folders

### ISSUE THREAD

**Issue by attorianzo** [darktable-org/darktable#16050]
I’m using Darktable 4.6.

The recursive directory import doesn’t work in this version. I understand that this is already been fixed so I’m waiting for the next version to come to light.
Moving in the “Add to library” window is painful, every click means long waiting because as soon as you click on a folder it starts to check the pictures inside.
I have more than 150k pictures stored in folders per year and months therefore I strongly need to split my collection in at least two or three large libraries. I can do that, I created symlinks on my desktop pointing to Darktable with different libraries. It works but I really wonder if in the future this possibility would become easier to do integrating it in Darktable itself.

It would be great to have the full path and name of the library db in use always on top to the app. In this way you can always be sure of what db you are using in order to avoid mistakes.

I need the ability to select more than 1 folder in “add to library”. At the moment I can only select one per time. For instance, I might need to import on a DB folders 2015 to 2020, because I need to import 2021 to 2025 in another library.

Any possibility improve the “add to library” function?

**Comment by ralfbrown** [comment]
You can start darktable with one or more directory names on the commandline, which will have it import them into the library.  As with the import dialogue, it will skip over images which are already in the library.

**Comment by ptilopteri** [comment]
the development version has the fixed import function.
fwiw:  I have been using the development version for >20 year with few difficulties.
