### ISSUE TITLE
"add to library", scanning the drive is very slow

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#16055]
### Describe the bug

While having >90,000 pictures in my database, it takes very long (up to half an hour! -provided the numbers in the output representing the time in seconds) to scan all the already existing pictures, before I can add new ones to the library.

Discussions with @TurboGit, we touch the point, that it is "expensive" to scan all the recursive folders for known file types. However, I see almost no IO; when checking with "iotop -o" and "gkrellm".

My picture dir is at ~/Bilder, which is a symlink to ~/DATA/Bilder (for historical reasons, to not mess the backup, I wouldn't like to change) on a quite fast HDD (/dev/sdb with an lvm-cache SSD /dev/sda).

My libray.db resides on a quite fast NVMe (Samsung 970 PRO)

I merely see extremely slow (kB/s) traffic on the NVMe but nothing on the HDD (see screenshot below) but one CPU core fully loaded (maybe this is the key)

### Steps to reproduce

1. go to lighttable
2. cick on add to library
3. if not done already, choose your pics folder
4. have select only new pictures, recursive directory and ingore non-raw all activated
5. check the time until the "add to library"-button on the lower right gets active (provided there are new pictures)

Better alternative; open a terminal, start "darktable -d sql -d perf" and abserve, by when the running lines stop. In my case today with 95307 pics, my last output came after 26,33 minutes =8-/

```
1589.3354 [sql] /home/gerber/.local/git/darktable/src/common/image.c:2023, function dt_image_get_id(): prepare "SELECT id FROM main.images WHERE film_id = ?1 AND filename = ?2"
  1589.3712 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1589.3719 [sql] /home/gerber/.local/git/darktable/src/common/image.c:2023, function dt_image_get_id(): prepare "SELECT id FROM main.images WHERE film_id = ?1 AND filename = ?2"
  1589.4073 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1589.4079 [sql] /home/gerber/.local/git/darktable/src/common/image.c:2023, function dt_image_get_id(): prepare "SELECT id FROM main.images WHERE film_id = ?1 AND filename = ?2"
```

### Expected behavior

dt should take the resources to a reasonable max e.g. disk-IO

### Logfile | Screenshot | Screencast

![Screenshot_20240107_151152_B](https://github.com/darktable-org/darktable/assets/49004103/b941d6fd-f289-437a-892f-c31e29d6d0fc)

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+184~g69cb426cd9

### What OS are you using?

Linux

### What is the version of your OS?

gentoo

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

please see below

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip
* darktable version : 4.7.0-184-g69cb426cd9
* OS                : Linux - kernel 6.6.10-gentoo
* Distro            : Gentoo Base System release 2.14
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-535.146.02
* OpenCL installed  : Yes (opencl-headers-2023.04.17)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.9
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.38
* gcc               : 13.2.1_p20230826
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by jenshannoschwalm** [comment]
> While having >90,000 pictures in my database, it takes very long (up to half an hour! -provided the numbers in the output representing the time in seconds) to scan all the already existing pictures, before I can add new ones to the library.
> 
> Discussions with @TurboGit, we touch the point, that it is "expensive" to scan all the recursive folders for known file types

Maybe the main "cost" here is checking for every file if it's already in the database? Maybe we can improve an index or do some sort of hash on filename for faster compare?

**Comment by ralfbrown** [comment]
> Maybe the main "cost" here is checking for every file if it's already in the database? Maybe we can improve an index or do some sort of hash on filename for faster compare?

That was my immediate thought as well.  From what I recall from when I worked on speeding up (fresh) import, every file gets processed individually.  It should be a lot faster to do a single SQL query that returns all of the filenames from the database, put them in a hash table, and then compare the filenames found in the directory scan against the hash table.  There's some trickiness involved with handling multiple sidecar files for an image....

**Comment by MStraeten** [comment]
maybe the hash table can be built using a select statement with a where in (<list of filenames to be imported>) that just returns the already present relevant filenames. This reduces the size of the hash table to be compared.

**Comment by TurboGit** [comment]
> maybe the hash table can be built using a select statement with a where in

SQL DB is kind of hash and should be very fast. The best is probably just to add an index for filename. To be sure about this we would have to look at the SQL query more deeply.

**Comment by TurboGit** [comment]
And we already have an index for `filename`.

@AxelG-DE : To check if this is the issue I'll prepare a PR with the check for existing file is removed.

**Comment by HansBull** [comment]
> > maybe the hash table can be built using a select statement with a where in
> 
> SQL DB is kind of hash and should be very fast. The best is probably just to add an index for filename. To be sure about this we would have to look at the SQL query more deeply.

The very `dt_image_get_id()`  function has been covered by an appropriate index for quite some time now (`images_film_id_index`).

**Comment by TurboGit** [comment]
@AxelG-DE : Can you check #16057 and report about speed? TIA.

**Comment by HansBull** [comment]
Can the `dt_film_get_id` on line 849 in `import.c` be extracted from the loop and moved to line 741?

**Comment by TurboGit** [comment]
> Can the `dt_film_get_id` on line 849 in `import.c` be extracted from the loop and moved to line 741?

Sure, probably more in line 798 as it is only in this code path that it is needed.

**Comment by AxelG-DE** [comment]
> @AxelG-DE : Can you check #16057 and report about speed? TIA.

To make sure, what I did:
I clicked on "add to library" on left pane and then did nothing, means I did not click on the  entry in "folders", because the scan already started....

I did test it and sorry, to say, that was not it, seems... took 1600s as well...

```
  1600.8478 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1600.9002 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1600.9388 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1600.9759 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1601.0129 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1601.0494 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1601.0922 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1601.1285 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
  1601.1654 [sql] /home/gerber/.local/git/darktable/src/common/film.c:102, function dt_film_get_id(): prepare "SELECT id FROM main.film_rolls WHERE folder = ?1"
```

And on top it offers me to import all the files now, even they wehre imported beforehand (maybe as expected)
![image](https://github.com/darktable-org/darktable/assets/49004103/f5038722-b063-4c36-9743-b6041ba1e8a2)

A second test is running, where I clicked on the upper most entry in "folders"....

**Comment by AxelG-DE** [comment]
> A second test is running, where I clicked on the upper most entry in "folders"....

I have cancelled that second test as it went into the same time range. 

I will try to do an investigation about the following phaenomenon:
- the first 30k pics take 250s
- the next 30k pics are completed at ~500s so that is linear,
- but 90k pics are not reached at 1000s even

I will write into a file and then do some simple calculations (diff and relative to former line etc., what ever illustrates)

**Comment by AxelG-DE** [comment]
here you can see a trend of how long each picture takes to be scanned:
![image](https://github.com/darktable-org/darktable/assets/49004103/45723aa1-522f-4c2a-a22c-b191367ef3e7)

The file is here (sorry I am not good with libreoffice Calc and tbh Excel is better in this regards):
[dt-import_20240107.ods.zip](https://github.com/darktable-org/darktable/files/13854771/dt-import_20240107.ods.zip)

**Comment by TurboGit** [comment]
> And on top it offers me to import all the files now, even they wehre imported beforehand (maybe as expected)

Yes expected as I have disabled the check for existing files. The goal of my TEST PR is to only check the relative speed compared to current master. At this stage we had many ideas about why it could be slow but we still don't know the real cause for this.

Given the data here we can say that the check on the DB for existing files is not the issue!

**Comment by TurboGit** [comment]
@AxelG-DE : I have updated my PR with some other stuff, can you check again the relative speed? TIA.

**Comment by AxelG-DE** [comment]
I have just tested commit e8a87b70d6 From PR #16057 and that improved from 1800s down to 30s
THAT I SOMETHING

**Comment by ralfbrown** [comment]
Yeah, re-sorting the file display after every file is definitely expensive....
