### ISSUE TITLE
unreliable detection of the lens during import

### ISSUE THREAD

**Issue by RomanSammer** [darktable-org/darktable#16053]
### Describe the bug

When importing Images to Darktable the lens is detected unreliable.
I imported Images from the same Camera and Lens combination and the same shooting and sometimes the lens (Canon EF-S 18-135mm f/3.5-5.6 IS USM) is detected right and on other images Unknown Lens (36912) is detected.
I also get this effect with other lenses and Cameras.

### Steps to reproduce

Import Images.

### Expected behavior

darktable should import the exiv information right

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Opensuse Tumbleweed

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia GTX1060Ti

**Comment by MStraeten** [comment]
darktable uses exiv2 library for extracting metadata from image exif data. So better report that there.
For a workaround see https://github.com/darktable-org/darktable/wiki/User's-portal#my-lens-is-wrongly-identified

**Comment by RomanSammer** [comment]
Thanks!
The workaround works now. Hope the issue is solved in future releases of exiv2.

**Comment by ptilopteri** [comment]
only if it is reported

**Comment by AxelG-DE** [comment]
Justnow I am struggling as well with exiv2

I do have a ~/.exiv2 file in place and it did work in the past, but all over sudden the recognition does not work anymore. I do have libexiv2-0.28.1 in place which is the current gentoo's version....

**Comment by MStraeten** [comment]
there are known issues with canon lens detection in exiv2 0.28 see https://github.com/Exiv2/exiv2/issues/2746

**Comment by AxelG-DE** [comment]
> there are known issues with canon lens detection in exiv2 0.28 see [Exiv2/exiv2#2746](https://github.com/Exiv2/exiv2/issues/2746)

thanks for pointing me there, @MStraeten

**Comment by AxelG-DE** [comment]
@RomanSammer which exiv2 version you are running?
