### ISSUE TITLE
4.6.x: double gridlines after commit b3f0d57 while cropping

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#16056]
### Describe the bug

the bugfix for Fixes https://github.com/darktable-org/darktable/issues/15984 done with https://github.com/darktable-org/darktable/pull/15990 causes double gridlines (whole image + cropped area) during cropping
![image](https://github.com/darktable-org/darktable/assets/39386816/3a8e4029-9fd7-4ed3-8707-e6647638666c)

### Steps to reproduce

perform crop with 4.6.x

### Commit

b3f0d57

### Where did you obtain darktable from?

self compiled

### darktable version

darktable 4.6.0+67~gbe30012e10-dirty

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14

### Are you using OpenCL GPU in darktable?

None

**Comment by elstoc** [comment]
Also reproduced on current master (4.7.0+186~g16561ac27b)
