### ISSUE TITLE
Compiling Master fails on Windows

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#16068]
### Describe the bug

Build aborts due to error in ```control/jobs/control_jobs.c```.
```
C:/msys64/home/user/darktable/src/control/jobs/control_jobs.c: In function 'dt_control_delete_images_job_run':
C:/msys64/home/user/darktable/src/control/jobs/control_jobs.c:1272:5: error: 'dirname' may be used uninitialized [-Werror=maybe-uninitialized]
 1272 |     g_free(dirname);
      |     ^~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

### Steps to reproduce

Update to latest Master, and start to build on Windows

### Expected behavior

Build without errors

### Commit

4.7.0+97~gfcbe7dd5b1 is compiling

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+97~gfcbe7dd5b1

### What OS are you using?

Windows

### What is the version of your OS?

Win 11 Enterprise 22H2

### Describe your system?

gcc 13.2.0

### Are you using OpenCL GPU in darktable?

Yes

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The file control_jobs.c: was updated on Jan 6th, but I was not able to find the commit (my lacking skills with git).

**Comment by zisoft** [comment]
Will be fixed when PR #16054 is merged.
