### ISSUE TITLE
 4.6.0 arm64: after install with .dmg, .app can't be opened because "is damaged"

### ISSUE THREAD

**Issue by BlkPingu** [darktable-org/darktable#16063]
### Describe the bug

After installing the dmg, I can't open the app because it says "it's damaged"

### Steps to reproduce

Download Darktable 4.6.0 on your favorite ARM Mac. Open the dmg, install the app. Open the app. 

### Expected behavior

should open darktable

### Logfile | Screenshot | Screencast

<img width="260" alt="Screenshot 2024-01-08 at 04 36 14" src="https://github.com/darktable-org/darktable/assets/28692167/45c2a342-21d1-4a89-bec2-cbfb05132831">

### Where did you obtain darktable from?

[downloaded from github.com/darktable-org](https://github.com/darktable-org/darktable/releases/tag/release-4.6.0)

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

14.2.1 (23C71)

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment]
see https://www.darktable.org/install/#macos
