### ISSUE TITLE
Map-View problem

### ISSUE THREAD

**Issue by diefau** [darktable-org/darktable#16062]
### Describe the bug

pushing the "left" cursor in the OSD multiple times, sometimes the map doesn't show the "next" left place of the map but some other place (sometimes with another zoom level).
But the behaviour is independent of th zoom level.

### Steps to reproduce

Map view -> show OSD (in the upper left corner) and use one of the "cursors" multiple times

### Expected behavior

darktable should show the "next" left place of the map

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Debian sid

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

4.4.2 has the same problem

**Comment by pehar1** [comment]
I can reproduce this only if I click **too fast** (double-click). Clicking step by step (no double-click) it's working fine.

**Comment by ralfbrown** [comment]
A double-click on the on-screen map controls shouldn't zoom the map though.  There's a branch in _view_map_button_press_callback which checks whether the mouse is on one of the thumbnails/pins and only does the zoom if not.  It should also check for the nav/zoom buttons and treat a double-click as a single-click (if possible) or ignore the double-click.  I haven't tracked down where single clicks on the on-screen controls are handled - that may be inside libosmgpsmap....

**Comment by pehar1** [comment]
This is what I observe:

> A double-click on the on-screen map controls shouldn't zoom the map though.

But it does, see below.

> There's a branch in _view_map_button_press_callback which checks whether the mouse is on one of the thumbnails/pins and only does the zoom if not.

Exactly **this** happens.

- double-clicking on a thumbnail/pin opens this image in darkroom
- double-clicking somewhere else on the map **increases zoom** level by one step and **centers** the clicked location on view

>  It should also check for the nav/zoom buttons and treat a double-click as a single-click (if possible) or ignore the double-click.

This is obviously not happening. **Double-clicking on nav/zoom buttons triggers the same action as double-clicking somewhere else on the map.**

I have looked at `_view_map_button_press_callback` in `map.c`. My marginal and outdated skills regarding C, C++,... unfortunately do not allow me to understand the almost uncommented code. So unfortunately I can only serve as a tester...

**Comment by zisoft** [comment]
We need to check if the OSD circle was clicked and let it handle the event.

@ralfbrown are you currently working on this? I think I have a fix.

**Comment by ralfbrown** [comment]
No, I just investigated to figure out where the problem was.
