### ISSUE TITLE
Overlay module don't recognize vertical orientation.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#16061]
### Describe the bug

The overlay module does not recognize vertically oriented photos (processed or not).

When an image is taken from the filmstrip and imported into the placeholder of the overlay module, the image comes out as shown in the screenshot.

### Steps to reproduce

Using a processed RAW from the filmstrip.

![Screenshot from 2024-01-07 13-29-48](https://github.com/darktable-org/darktable/assets/67672868/292c5de0-16e9-4e37-b2f8-e6ce3fa3ffe5)

Using an original RAW whitout process.

![Screenshot from 2024-01-07 13-29-48](https://github.com/darktable-org/darktable/assets/67672868/cf42a294-5cd2-4322-bc04-2dd2017638fb)

### Where did you obtain darktable from?

OBS

### darktable version

4.7.0~git187.2f51865d-11140.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Are you using OpenCL GPU in darktable?

Yes

**Comment by TurboGit** [comment]
Should be fixed.
