### ISSUE TITLE
Program crash in specific folder in lighttable view

### ISSUE THREAD

**Issue by photopteryx** [darktable-org/darktable#16080]
### Describe the bug

After editing about 20 images in a folder of about 90 photos, I switched back to lighttable view, and was met with a full program crash right as some thumbnails were loading. If I relaunch the program, it defaults to a different folder (the previous one I had been working in a few days ago), and when I re-import the new folder of 90 images with the 20 edits, the error occurs again while the thumbnails load in. 

### Steps to reproduce

1. Open darktable.
2. Import folder of raw images (some already edited in darktable)
3. Unhandled exception dialog box appears
4. Close error dialog box, and darktable crashes.

### Logfile | Screenshot | Screencast

[darktable_bt_22E4G2.txt](https://github.com/darktable-org/darktable/files/13892176/darktable_bt_22E4G2.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

3.4.1.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment]
darktable 3.4.1 was released in 09Feb2021. That's almost 4 yr old version that is missing multiple bug fixes from the last 6 major releases. Please install the 4.6 version and test again. Post a darktable -d common log if you encounter an issue with 4.6.

**Comment by photopteryx** [comment]
I just discovered that while submitting this bug report! 😅 Though 3.4.1 has worked flawlessly for me until now, so congrats on that. I'm downloading the new version now, and I'll see if I still encounter the issue. 
-------- Original message --------From: gi-man ***@***.***> Date: 1/10/24  2:44 PM  (GMT-05:00) To: darktable-org/darktable ***@***.***> Cc: photopteryx ***@***.***>, Author ***@***.***> Subject: Re: [darktable-org/darktable] Program crash in specific folder in lighttable view (Issue #16080) 
darktable 3.4.1 was released in 09Feb2021. That's almost 4 yr old version that is missing multiple bug fixes from the last 6 major releases. Please install the 4.6 version and test again. Post a darktable -d common log if you encounter an issue with 4.6.

**Comment by victoryforce** [comment]
@photopteryx If the problem still occurs in the current version, please open a new issue for this.
