### ISSUE TITLE
Incorrect tag sorting

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#16081]
### Describe the bug

If the interface language "English" was selected, then the list of tags in the tagging module is sorted as in the "english" screenshot.
If a different language was selected, special characters are not taken into account when sorting this list. I tried Deutsch and Russian ("deutsch" and "russian" screenshots).

english
![english](https://github.com/darktable-org/darktable/assets/15331117/2064a5cf-fdf4-4d26-baef-cc0d65161330)

deutsch
![deutsch](https://github.com/darktable-org/darktable/assets/15331117/e53370a3-6ad5-4f45-8282-2155cd774ab0)

russian
![russian](https://github.com/darktable-org/darktable/assets/15331117/1fbe2b7e-f4a3-4a1f-9c9a-e7b5432eed5e)

### Steps to reproduce

1. Create some tags with/without leading special characters.
2. Select English (and then some other) interface language.
3. Restart darktable and open tagging module.

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+227~g420bc453d7

### What OS are you using?

Linux

### What is the version of your OS?

Linux debian12 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment]
hmm, cannot reproduce on current master:

english:
![image](https://github.com/darktable-org/darktable/assets/4083281/d2617c1b-6e96-43f6-9177-535fbd2acb1f)

german:
![image](https://github.com/darktable-org/darktable/assets/4083281/42e5a360-d195-4552-8947-b20c71675de1)

russian:
![image](https://github.com/darktable-org/darktable/assets/4083281/611551d5-d6aa-4561-ab37-3d12d1bc8bee)

What are your OS' locale settings?

**Comment by parafin** [comment]
dt uses a little bit convoluted way to set language by looking at `locale -a` output, so result may depend on which locales are installed on the system. So both `locale` and `locale -a` output may be of interest.

**Comment by esq4** [comment]
```
my@debian:~$ locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
my@debian:~$ locale -a
C
C.utf8
en_US.utf8
POSIX
ru_RU.cp1251
ru_RU.utf8
```

**Comment by esq4** [comment]
[Wrong behaviour of g_utf8_strdown() using tr_TR.utf8 locale ](https://gitlab.gnome.org/GNOME/glib/-/issues/390)
maybe this is the problem? (see last comment)

In any case, when I removed the _g_utf8_casefold_ and _g_utf8_collate_key_for_filename_ functions from __compare_utf8_no_case_ (only _const gint sort = g_strcmp0(a, b)_ remained) - the sorting of tags became the same for different interface languages and different system locales.

How much need is there for case-insensitive sorting of tags?
For example, it is very convenient for me to see the names of people and cities at the beginning of the list all together. And don’t forget about the habit.
Or maybe could at least to make a control to disable case-insensitive sorting?

**Comment by zisoft** [comment]
> How much need is there for case-insensitive sorting of tags?

#15665

This was just implemented, see: #15696 #15983

**Comment by esq4** [comment]
It's clear. Now he's comfortable.
Can you make it more convenient for others? :)

**Comment by zisoft** [comment]
I made some further investigation on this.
To get the "natural" sort order ("tag_2" comes before "tag_10") we use `g_utf8_collate_key_for_filename()`. This function always sorts case-insensitive so in fact the `g_utf8_casefold()` can be removed.

That means we have no way to get the natural sort with case sensitivity.

> For example, it is very convenient for me to see the names of people and cities at the beginning of the list all together

For groupings of such kind I use hierarchical tags:
01_People|James
01_People|Carl

02_Cities|New York
02_Cities|London

**Comment by esq4** [comment]
If I understand you correctly, then _compare_utf8_no_case looks like this:
```
 char *a_nc_nat = g_utf8_collate_key_for_filename(a, -1);
  char *b_nc_nat = g_utf8_collate_key_for_filename(b, -1);
  const gint sort = g_strcmp0(a_nc_nat, b_nc_nat);
```
But such an implementation also creates current issue (taking into account the system locale).

**Comment by zisoft** [comment]
That's what I tried to explain: `g_utf8_casefold()` can be removed, the result is the same.

**Comment by zisoft** [comment]
@esq4 I have made it configurable in the preferences now, let's see what others say.

You should consider raising an upstream ticket at glib for `g_utf8_collate_key_for_filename()`
