### ISSUE TITLE
Phase One IQ180 white balance presets

### ISSUE THREAD

**Issue by BAGELGENESIS** [darktable-org/darktable#16090]
All four white balance presets for the Phase One IQ180. You cannot fine-tune the presets themselves, only other options are custom (by selecting a pixel of an image) or auto white balance. XF-Camera and digital back were both on the newest firmware as of capture.

[darktable-whitebalance-20240112.tar.gz](https://github.com/darktable-org/darktable/files/13923010/darktable-whitebalance-20240112.tar.gz)

Thanks,
BAGELGENESIS

**Comment by kmilos** [comment]
Please see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
