### ISSUE TITLE
color equalizer: activating guided filter changes image even no changes are made

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#16098]
### Describe the bug

if the module is enabled the activated guided filter changes the image even no color equalizer sliders are <> 0:
<img width="1083" alt="image" src="https://github.com/darktable-org/darktable/assets/39386816/4d763ed4-a64e-4103-9afa-54b9bef28acf">

### Steps to reproduce

activate color equalizer on a image with hard black-color borders

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+257~g2eccf8ea41-dirty

### What OS are you using?

Mac

### What is the version of your OS?

macOS14

### Are you using OpenCL GPU in darktable?

Yes

**Comment by todd-prior** [comment]
I also posted some examples here...just noticed your note.... png file was much more strongly impacted vs the raw file...

https://discuss.pixls.us/t/the-need-for-a-scene-referred-color-zones-replacement/39294/88?u=priort

**Comment by jenshannoschwalm** [comment]
Yes, what you see is a "known" effect from the guiding part. The module math is still under development ...

**Comment by MStraeten** [comment]
main point is: is an impact on the image just by activating a module even without changing image related parameters expectable?
and a more software engineering view: does it make sense to use master as a playground for new stuff with major open questions instead of using a separate feature preview branch until it’s mature enough to publish it for broad quality assurance.
In the past master had near to production quality …

**Comment by TurboGit** [comment]
> In the past master had near to production quality …

And I think it is the case, "near" but it all depends what near means for each others. This is a complex module which has been worked hard those last weeks and as we get reported bugs that will be fixed.

**Comment by jenshannoschwalm** [comment]
> main point is: is an impact on the image just by activating a module even without changing image related parameters expectable?

In this case: YES - so far. We can - and probably should disable guiding by default though.

> In the past master had near to production quality …

I agree here mostly. There have problems with this module making it a bit more difficult. The original author has left the team and has so far not been able to fix major issues on his branch. The first port was very unstable and there have been many bugs fixed on the road to the now merged pr. 

The images presented here have certain characteristics that make them a larger challenge than "normal raws".

**Comment by todd-prior** [comment]
> EDIT: what you see is the outside black border "bleeding" the color circle. This is "interesting" because of two reasons immediately:

I also see more than just border issues but granted that was a png so I will look for a raw image gray ramp but the bright values in the gray ramp all went a dull gray.... so white was darkened??

**Comment by jenshannoschwalm** [comment]
The last one seem to be one of the troy sobotka files. There are some not working on dt, i also observed this. Not sure if it's the input scaling ...

**Comment by flannelhead** [comment]
> The last one seem to be one of the troy sobotka files. There are some not working on dt, i also observed this. Not sure if it's the input scaling ...

Plenty of those use Rec.709 primaries but contain some negative values. Those get clipped off in the scaling in very early phase in the pipeline. There's no clipping when the image is zoomed to 100% so the scaling isn't in effect.

This is particular to raw files (in this case EXRs) which have negative values. Usually there are none in raws from real cameras.

**Comment by jenshannoschwalm** [comment]
> Plenty of those use Rec.709 primaries but contain some negative values.

Ah. We can't set black/white point on those.

**Comment by flannelhead** [comment]
And offsetting the black point would be totally wrong. The negative values have a real meaning, as they describe values that are out of the Rec.709 footprint and are meant to be like that.

**Comment by jenshannoschwalm** [comment]
OK. Will have a look into the specs.

**Comment by SoupyGit** [comment]
@MStraeten I personally don't understand why every open source project doesn't have a dev branch and a master branch. When a pull request gets accepted it should first go into dev for field testing, and once it's survived that for a period of time it gets merged into master. Ie. There is no guatantee everything in dev will make it to master, but once it does, it's no longer considered a work in processing. Rolling release distros could work only from master, not dev, and be more stable. Some might argue the dev branch really exists before they get merged, but in reality it doesn't quite work that way, when things that still need work and field testing get pushed to master. This is not a darktable issue, but seems to be industry wide. An example to follow would be something like debian, which has debian unstable (dev), debian testing (master), and debian stable.

**Comment by MStraeten** [comment]
master is the ‚dev branch‘; stable releases have their own branch. It’s a matter of taste. If rolling distros wants to have a recent but quite stable and reliable codebase they can use the bugfix branch of the latest release. That’s the darktable way. 
Being able to build and use master as the latest and hottest shit comes with a risk each packager and distributor should clearly communicate. That’s not the job of the dev team ;)
Merging into master to enable a broader test and get feedback and issue reports is a very valid decision.
Users just wanting to use latest stuff but not contribute to the dev process by testing or reporting issues aren’t the target users of master…

**Comment by SoupyGit** [comment]
I was merely replying to a point of discussion you raised, so **be sure to bold that for yourself next time too.** I am aware 'master' is the 'dev' branch and wasn't suggesting this way isn't valid. Just offering a solution to the issue you raised. Sorry if you don't want to hear it.

**Comment by jenshannoschwalm** [comment]
@MStraeten what is your position about this issue with current status of CE?

**Comment by MStraeten** [comment]
with current master the image seems to be unchanged - just the vectorscope or a live value global picker on intersections indicates changes:
guided filter off:
![image](https://github.com/darktable-org/darktable/assets/39386816/9fea2dd6-b763-43ee-b71f-79171a164a45)

guided filter on:
![image](https://github.com/darktable-org/darktable/assets/39386816/323755bc-ba6a-40b3-8b41-3cf34298e910)
These changed vectorsope is independent of the hue angle 

in raw images there's no visible change - so it quite 'good enough' and no longer an issue.
Maybe a note in the manual indicating that activating the module might have impacts makes sense ...

**Comment by jenshannoschwalm** [comment]
> in raw images there's no visible change - so it quite 'good enough' and no longer an issue.
> Maybe a note in the manual indicating that activating the module might have impacts makes sense ...

Agreed. Otherwise we would have to do a workaround like "bypass if no changed parameters" ...

**Comment by MStraeten** [comment]
behaviour was changed so initial issue no longer occurs
