### ISSUE TITLE
overlay: improper scaling of skull for missing overlay image

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#16095]
### Describe the bug

if the overlay image is missing, a skull? is displayed - but not properly scaled
![image](https://github.com/darktable-org/darktable/assets/39386816/1fc22ec0-3c64-4db1-a907-38332bba8728)

### Steps to reproduce

use darktable with --library :memory: and enable writing of xmps
add two images 
use image2 as an overlay for image1
restart darktable, just add the image1
check overlay module settings

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+257~g2eccf8ea41-dirty

### What OS are you using?

Mac

### What is the version of your OS?

macOS14

**Comment by TurboGit** [comment]
I cannot reproduce...

![image](https://github.com/darktable-org/darktable/assets/467069/65989787-b3cd-4a79-aa1b-13da5e6d9736)

**Comment by MStraeten** [comment]
need to check this with an external monitor - maybe a macOS retina scaling related issue …

**Comment by MStraeten** [comment]
wasn’t able to reproduce with latest build so maybe something inconsistent in the build environment…
