### ISSUE TITLE
color equalizer: unnecessary pixelpipe runs

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#16099]
### Describe the bug

When scrolling the mouse on the equalizer graph (but not near enough a node to highlight it), the scrolling has no effect but the pixelpipe is run anyway starting from color equalizer.  This happens whether the "hue", "brightness" or "options" tabs are active; it does not happen for the "saturation" tab.

### Steps to reproduce

Open color equalizer module
Move mouse pointer into graph, but not near enough one of the nodes to highlight it
Scroll.

### Expected behavior

The pixelpipe should not be run if no values are changed.  It would also be nice if one could scroll anywhere (vertically) within the graph and adjust nodes - when I first tried out the module, I thought scrolling wasn't working at all because I hadn't put the mouse pointer more or less on top of one of the nodes (then I noticed the flickering of the "working" message).

### Where did you obtain darktable from?

self compiled

### darktable version

Current master (2eccf8ea41)

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 9

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment]
@ralfbrown : Should be fixed now.

**Comment by ralfbrown** [comment]
Fix confirmed.  Thanks!
