### ISSUE TITLE
color equalizer: inconsistent tooltips

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#16109]
### Describe the bug

While ethere's a proper tooltip for analysis radias and effect radius the tooltip for analysis and effect feathering is the generic slider tooltip:
![image](https://github.com/darktable-org/darktable/assets/39386816/7379ecd4-c709-4bcd-9d2a-5ab6ab7b32b8)
since there's no visual control on the guided filter setting a tooltip explaining the setting is quite useful

### Steps to reproduce

mouse over on color equalizer options tab

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+270~g26ef1359d7-dirty

### What OS are you using?

Mac

### What is the version of your OS?

macOS14

### Are you using OpenCL GPU in darktable?

Yes

**Comment by jenshannoschwalm** [comment]
I am not sure how to describe the effect in a good way. Not even sure if we need those parameters to be changed by user at all.

**Comment by jenshannoschwalm** [comment]
Closing this as we don't expose the feathering in UI any more.
