### ISSUE TITLE
Git master: New module Color Equalizer: grey artifacts in darkroom main view.

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#16103]
### Describe the bug

I get grey artifacts in darkroom main view, when color equalizer is active, if a certain set of preconditions are fulfilled:

- Color equalizer module is active, ON, default state (no equalizer curve changes = flat).
- Preferences -> processing -> always use littleCMS 2 = ticked, ON
- Diffuse & Sharpen ON, activated using sharpen demosaicing AA filter preset.
- Sharpening module is ON, active using default values.
- Filmic rgb module is OFF, deactivated.

It is quite a complex set, but I can trigger issue on and off with Filmic rgb as long as the other conditions are present. One can do the same thing with other conditions like Preferences -> processing -> always use littleCMS 2. If I turn littleCMS2 OFF and restart darktable, then the issue is NOT present (when Filmic RGB is on or off).

Example of issue (click on picture and zoom in on marked areas):
![Screenshot from 2024-01-14 09-08-46_draw](https://github.com/darktable-org/darktable/assets/42386052/2d6b8cbc-99ae-4de5-a599-8b6eafea6c76)

Video example:
https://drive.google.com/file/d/1GAh2QDbShvbi01Qof2sYQhM3QZydYo6i/view?usp=sharing

### Steps to reproduce

Steps to reproduce:
1. Build darktable git master. Start from a clean cache and config
2. Preferences -> processing -> always use littleCMS 2 = ticked, ON
3. Import 0Y8A7917.CR2 (link below)
4. Go to darkroom
5. Activate color equalizer module, ON,  (no equalizer curve changes = flat)
6. Activate Diffuse and Sharpen module, ON, with demosaicing AA filter preset
7. Activate sharpening module, ON, defaults
8. Deactivate filmic rgb module, OFF
9. Notice the grey artifacts in darkroom main view when filmic rgb is OFF, inactive. Picture above at 100% in darkroom.

Expected result: No grey artifacts in darkroom main view.

Counterexample, i.e., no issues:
If I do not use color equalizer module (deactivated, OFF), then I can disable filmic rgb without issues for the same file and the same preconditions listed here.

RAW file example: Canon 5D mk IV, CR2: 0Y8A7917.CR2
https://drive.google.com/file/d/1ZGnvJNgbZ0eSXfbAd06ySgG-Rk21YSqX/view?usp=sharing

### Expected behavior

Expected result: No grey artifacts in darkroom main view.

### Logfile | Screenshot | Screencast

CR2 raw file and video linked above.

### Commit

release-4.7.0-260-gce5d92983a

### Where did you obtain darktable from?

Compiled from git master source.

### darktable version

release-4.7.0-260-gce5d92983a

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12.4

### Describe your system?

- OS : Linux debian 6.1.0-17-amd64 1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
- Linux - Distro : Debian 12.4
- Memory : 16 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : NVIDIA 525.147.05-4~deb12u1
- OpenCL installed : Yes,   OpenCL 3.0 CUDA 12.0.151
- OpenCL activated : Yes (EDIT: but --disable-opencl does not help, same issue)
- Xorg : X11
- Desktop : Gnome 43.9
- GTK:  4.8.3+ds-2+deb12u1, 3.24.38-2~deb12u1
- gcc : (Debian 12.2.0-14) 12.2.0
- cflags : 
- CMAKE_BUILD_TYPE : Release
- Intel® Core™ i7-3770K × 8
- motherboard: ASUSTeK COMPUTER INC. P8Z77-V

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000],  NVIDIA 525.147.05-4~deb12u1

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

**Can you reproduce with another darktable version(s)?  **no, not without new module color equalizer**
Can you reproduce with a RAW or Jpeg or both? **Also with jpg, just add D&S AA filter + sharpening + color eq. on/off**
Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
If the issue is with the output image, attach an XMP file if (you'll have to change the extension to .txt)
Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes/no
Do you use lua scripts? **no**

Open CL: **Open CL on or off does not matter.**

**Comment by TurboGit** [comment]
I suppose that the artifacts are only appearing if the guided filter in Color Equalizer is ON. Can you confirm?

**Comment by TurboGit** [comment]
Alternatively using a small radius should help, please confirm?

**Comment by KarlMagnusLarsson** [comment]
Hello @TurboGit,

Neither guided filter on/off nor any radius parameters have any visible effect on the grey artifacts.

**Comment by TurboGit** [comment]
So I cannot reproduce this on my pictures. Just tried your linked picture here and I also cannot reproduce. Let's wait for @jenshannoschwalm to test this...

**Comment by jenshannoschwalm** [comment]
I can't reproduce either. Could you check
1. if your artifacts depend on the chosen interpolator in preferences?
2. does this only happen at regions where you have very small and very bright "spots" inside dark regions?
3. does the observed problem look very different at different zoom scales while observing?

**Comment by KarlMagnusLarsson** [comment]
@jenshannoschwalm,

I will do some tests as per your suggestions later today.

What does this mean? Can you add some more test details here? 
"If your artifacts depend on the chosen interpolator in preferences?"

**Comment by jenshannoschwalm** [comment]
> If your artifacts depend on the chosen interpolator in preferences

It should be "Do your observed artifacts ..." :-)
meaning: can you reproduce your issue also after changing the interpolators in preferences->processing->pixel_interpolators to bicubic or bilinear?

**Comment by KarlMagnusLarsson** [comment]
Hello @jenshannoschwalm 


1. if your artifacts depend on the chosen interpolator in preferences? **No.**
2. does this only happen at regions where you have very small and very bright "spots" inside dark regions? **No, but they are confined to high contrast borders. You can also zoom into attached example picture in issue report to check what I see.**
5. does the observed problem look very different at different zoom scales while observing? **Yes, the gray areas vary when I zoom in monotonically. They become bigger and smaller when zoom tends to max**

**Comment by jenshannoschwalm** [comment]
Just to make sure: Do you mean this effect? using some strong sat changing in color equalizer and here i just toggle strong sharpening in D&S on/off?

**Comment by KarlMagnusLarsson** [comment]
@jenshannoschwalm 

I mean just toggle module D&S on/off. The preset I use is AA-filter.

I have not used any change in color equalizer, just module on/off and rest of module on default and flat curves.

==

I am working on another track, if moving from gcc to CLANG will change anything. A first test with CLANG 14.0.6 show that I can **not trigger issue** when I compile with CLANG.

I build like this, with GCC 12.2.
```
mkdir build/
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/camera2/test2/darktable-test/install -DCMAKE_BUILD_TYPE=Release .. 
make -j8
make install
```
=> I get issue

If I add:
```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
```
and recompile
=> I do not get issue.

Is this issue related to compiler options and optimization settings?

**Comment by TurboGit** [comment]
> and recompile
> => I do not get issue.

I'm using GCC 13..2 and don't have the issue. Looks like some compiler issue and probably related to OpenMP.

**Comment by KarlMagnusLarsson** [comment]
@TurboGit, @jenshannoschwalm and all,

Going back to GCC 12.2.0 on Debian stable (Bookworm) and configure Debug build type:
```
cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/camera2/test2/darktable-test/install -DCMAKE_BUILD_TYPE=Debug ..
```
=> No issue.

Checking  with `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`  I get this for  `-DCMAKE_BUILD_TYPE=Debug`:

`-Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wmaybe-uninitialized -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -fopenmp -march=native -msse2 -g -mfpmath=sse -g -O0 -g3 -ggdb3 -D_DEBUG -fPIC   -Werror -Wfatal-errors -std=c99 -MD -MT `
gcc compile with `-O0` and darktable is noticeably slower, **but no issue**.

`-Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wmaybe-uninitialized -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -fopenmp -march=native -msse2 -g -mfpmath=sse -O3 -DNDEBUG -O3 -ffast-math -fno-finite-math-only -fexpensive-optimizations -fPIC   -Werror -Wfatal-errors -std=c99 -MD -MT
`
That is gcc use `-O3` and **issue is present, that is gray artifacts**.

**Comment by KarlMagnusLarsson** [comment]
Can anyone reproduce this? On Debian stable? Using gcc 12.2.0?

**Comment by wpferguson** [comment]
I tried on Ubuntu 22.04 with gcc 12.3.  I could get some color fringing issues around the bottom of the coat and between her knees.  It was worse with lcms2 off.  Moving d or s AA filter before input color profile (as recommended by AP) and sharpen after color equalizer eliminated most of the fringing issues.

**Comment by jenshannoschwalm** [comment]
Maybe some openmp code with wrong aligning?

**Comment by wpferguson** [comment]
Maybe just set the default pixelpipe position of color equalizer before the sharpen module instead of after?  Or move sharpen as late as possible in the pipe?

**Comment by jenshannoschwalm** [comment]
> Maybe just set the default pixelpipe position of color equalizer before the sharpen module instead of after? Or move sharpen as late as possible in the pipe?

I think we got the issue mostly sorted out in color equalizer maths ...

**Comment by KarlMagnusLarsson** [comment]
@wpferguson, Thank you for the test.

The reported issue is not about color fringing. If you select the example picture and zoom in to marked areas (red contour) then there are flat gray blobs in high contrast areas. For that issue the position of modules like D&S does not matter, at least not for me.

**Comment by jenshannoschwalm** [comment]
Many things now reworked in that module. Please open another ticket if you run into "something".

**Comment by KarlMagnusLarsson** [comment]
Hej @jenshannoschwalm,

I can confirm that `-DCMAKE_BUILD_TYPE=Release` and `-O3` works for me on Debian stable Bookworm using the default gcc 12.2.0.

I no longer get the gray artifacts when I set up the condition in the trouble report.

Thank you.
