### ISSUE TITLE
Darktable v4.6.0 does not recognize GTX 1070 in Ubuntu 22.04

### ISSUE THREAD

**Issue by tonydiep** [darktable-org/darktable#16101]
### Describe the bug

Darktable v4.6.0 reports 'no opencl devices found' and does not enable opencl when installed on Ubuntu 22.04 with GTX 1070.

Workaround is to use older version of Darktable. Opencl is enabled on Darktable version 3.8.1.

### Steps to reproduce

1. Install Darktable 4.6.0
Result: Darktable shows error message 'No opencl devices found' and opencl options in settings not enabled.
2. Install Darktable 3.8.1
Result: Opencl options enabled

### Expected behavior

Darktable 4.6.0 should recognize GTX 1070 as it did in 3.8.1

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

GTX 1070

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GTX 1070

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Only noticed this error in the past 2 days. I believe Darktable was upgraded. OpenCL works with 3.8.1 It also worked before on the flatpak version befire this upgrade, which is 4.4(?)

**Comment by gi-man** [comment]
This is not a darktable problem. You need to ensure the flatpak has the opencl drivers and that you enable in the flatpak settings the use of the gpu. Fedora has a built in settings section for this. I dont know about Ubuntu.

Your other options is to use OBS or self build.

**Comment by tonydiep** [comment]
Ok. Thanks! 3.8.1 it is, then.

**Comment by victoryforce** [comment]
@tonydiep https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable -- click on Ubuntu, then on the desired installation option (directly or via adding a repository)

**Comment by tonydiep** [comment]
@victoryforce Thank you very much!

BTW: Ubuntu / Flatpak upgraded Darktable 4.4.x to 4.6.0 and automatically and that's when Darktable showed the No OpenCL Devices message on startup.

I manually uninstalled and re-installed the Darktable 4.6.0 Flatpak it and this time Darktable compiled its CL modules and activated OpenCL on startup.
