### ISSUE TITLE
color eq effect radius defaults

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#16117]
A place to discuss the default value of color eq 'effect radius' in 'options' tab. I personally feel the current default of 50px is much too high - allow me to demonstrate.

For all the below, curve smoothing and other options remained at defaults. Guided filter was on.

Here is a completely desaturated image using color eq only:

![desat-all](https://github.com/darktable-org/darktable/assets/69561443/493f3393-24f6-435c-8954-5b22b0f63ecc)

And here is the image if we increase just one slider with effect radius 50px default:

![desat-default-50px](https://github.com/darktable-org/darktable/assets/69561443/d06792be-8051-4b7c-8d7e-bfdecda9c499)

As you can see, although I have only lifted 'lime', colours on the other side of the spectrum, such as 'blue', become visible. In fact, looking at the scopes, all colours seem to have been increased by a similar amount!

Here is the image if the effect radius is changed to the minimum value of 3px:

![desat-min-3px](https://github.com/darktable-org/darktable/assets/69561443/3628fd61-4862-4967-9f27-16b16b4fbe14)

In my opinion, it looks much closer to expectations.

For brightness tab, here is a completely darkened image using color eq only:

![dark-default-50px](https://github.com/darktable-org/darktable/assets/69561443/a4458e13-0d00-44e1-94a8-f6039d5e0432)

If you want even the lightest colours to become black, you have to turn effect radius up to 100px:

![dark-black-100px](https://github.com/darktable-org/darktable/assets/69561443/29d9d6a6-e7e9-4300-969c-4ee6fc306d86)

Here is the image if we increase just one slider with effect radius 50px default:

![dark-default-50px-2](https://github.com/darktable-org/darktable/assets/69561443/91408e77-9477-47f0-9665-90b7dd1bfec3)

Compared to if we increase the same slider with effect radius at minimum 3px:

![dark-min-3px](https://github.com/darktable-org/darktable/assets/69561443/286ac222-4313-42be-9dcf-59844a7de39f)

Again, in my opinion it looks much closer to expectations.

In my tests, the impact of this slider on hue is negligible. 

Based on the above, I propose to change the default from 50px to something much lower, perhaps even the minimum of 3px (or 10px if we wish to be a little more conservative).

**Comment by TurboGit** [comment]
I agree with that, 50px is probably too large a default. I'm wondering also if we could come up with different presets for different purpose. I see it maybe a larger effect radius could be good for landscape?

**Comment by TurboGit** [comment]
That being said not 3px though otherwise we are close to what is done without the guiding filter and we get artifacts.

**Comment by jenshannoschwalm** [comment]
I would also Vote for 10pix. 

Just a reminder, the "inpainting" maths is likely not in final state...

**Comment by TurboGit** [comment]
@SoupyGit @jenshannoschwalm : See my comments in #16120, not sure 10px is good after all.

**Comment by jenshannoschwalm** [comment]
Closing this for now as we have applied radius correction under far better control and have new defaults.
