### ISSUE TITLE
Auto-applied presets are not updating thumbnails

### ISSUE THREAD

**Issue by thetruemist** [darktable-org/darktable#16126]
### Describe the bug

I have some auto-applied preset, e.g. framing. When I open the picture in darkroom, the thumbnail in the filmstrip is correctly updated while staying on this picture. If I scroll to the next picture without any manual activity, the thumbnail is back to original. Esp. with the framing, it's pretty obvious.
The thumbnails in lighttable are affected as well.

### Steps to reproduce

1. Create a preset in framing, set to auto-apply to all pictures
2. Import some pictures
3. Open one picture in darkroom (preset should be applied, thumbnail should be updated)
4. Do not change anything, skip to the next picture => previous thumbnail goes back to original/unedited

### Expected behavior

Thumbnail should be updated permanently (worked in previous versions)

### Where did you obtain darktable from?

OBS

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12.4

### Describe your system?

xfce/X11, nvidia GTX 1660, opencl enabled

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia GTX 1660 DRIVER VERSION: 525.147.05

**Comment by ralfbrown** [comment]
What is your setting for "create XMP files" on the "storage" tab of darktable's preferences?  Since you aren't manually changing any settings, darktable considers the image un-edited, so it would make sense that it doesn't actually store the auto-applied presets as part of the image's development until you make a manual edit.  Agreed that this leads to unexpected behavior.

**Comment by thetruemist** [comment]
> What is your setting for "create XMP files" on the "storage" tab of darktable's preferences? Since you aren't manually changing any settings, darktable considers the image un-edited, so it would make sense that it doesn't actually store the auto-applied presets as part of the image's development until you make a manual edit. Agreed that this leads to unexpected behavior.

It's set to "on import" now. But when I first observed the issue, it was set to "after edit". Had the same idea that his might change something, but it seems it doesn't (caveat: If I remember correctly...)

**Comment by thetruemist** [comment]
Quick update: No idea what happened, but it did work for the pictures that I just imported (for a different camera, though). I did not change anything in dt, just did some os upgrades -- and I cannot believe that this has any impact. So as of now: Sorry. At the moment, I cannot reproduce the effect.

**Comment by thetruemist** [comment]
Hi again, sorry, this ticket should be re-opened. I could not reproduce yesterday, for a different camera. Now, for some other camera, it happened again. Of course, the difference is not the camera or picture format itself, the difference is: For yesterday's camera I have *more* presets with auto-apply (actually, two "sharpen" presets match, so I have two instances of "sharpen" now (another new behaviour in 4.6.0). Anyway, the thumbnails are not generated as expected, depending on the presets which are auto-applied. It can be reproduced with "framing", though.

**Comment by TurboGit** [comment]
@thetruemist : So please go into darktable preferences in the `presets` section and remove the offending preset. The fact that you have two sharpen preset looks like a bug fixed in 4.6.0 which was applying only the first auto-preset found on the list. This has never been noticed and this bug was actually there since a long time.

**Comment by thetruemist** [comment]
Hi, yes, I understand the multiple presets, that's not the point of this issue. Of course, it's a bit difficult to have one default preset that matches "%", and one special preset that matches "%Pentax Q%". How would I exclude the "%Pentax Q%" from the default? But anyway, let's not discuss this here, it's not really problem, in most cases.
