### ISSUE TITLE
Fuji GFX100 II

### ISSUE THREAD

**Issue by irieger** [darktable-org/darktable#16130]
Hey,

I just uploaded a few samples (16 Bit uncompressed, 14&16 Bit lossy and lossless compressed) of the Fuji GFX100 II to https://raw.pixls.us. As a darktable user I'd be really happy to see that camera supported there.

libraw already is able to generally load the files, although it doesn't correctly report the black level. So I guess it is likely that the files are similarly to the first generation GFX100 (s) files from which at least some variants are already supported with mostly some minor details being different.

**Comment by LebedevRI** [comment]
Yay, finally samples for that camera!
Any chance you could contribute proper samples (Daylight landscape-ish), as listed on the RPU?

**Comment by irieger** [comment]
Sorry, only have those badly lit in store samples for now. (See discussion here https://github.com/LibRaw/LibRaw/issues/627)

That is why I first had hesitated to upload them. But not sure when I'll rent or buy that camera which would be the time I could provide some proper examples. Will add them once I have some.

**Comment by kmilos** [comment]
Thanks for the initial samples anyway!

**Comment by LebedevRI** [comment]
Ok, well, better than nothing i suppose...

@irieger thank you for contributing the samples!

**Comment by LebedevRI** [comment]
@kmilos thank you!
