### ISSUE TITLE
How to enable OpenCl with Intel Arc A770

### ISSUE THREAD

**Issue by TimmyWe** [darktable-org/darktable#16149]
### Describe the bug

I have a PC with dual GPU (onboard Intel Alder lake an an Intel Arc A770) I installed all driver-Packages from https://dgpu-docs.intel.com/driver/client/overview.html.
Darktable is finding the 'libOpenCL'
The output from darktable-cltest is:

[darktable-cltest.txt](https://github.com/darktable-org/darktable/files/13985782/darktable-cltest.txt)

and the output from clinfo is:
[CLinfo.txt](https://github.com/darktable-org/darktable/files/13985797/CLinfo.txt)

darktable recognizes the Intel_driver I think:
![8a254d674950b2a4d6ff97aa7d54d65a7ef2a62b_2_616x500](https://github.com/darktable-org/darktable/assets/157043510/695957bc-03fe-482d-844d-e0bc6a67b4e0)

What can I do else to enable OpenCl?

### Steps to reproduce

Clinfo
darktable-cltest

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Zorin Os 17

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Intel Arc A770M

**Comment by gi-man** [comment]
We implemented a platform check to detect incorrect setups of multiple drivers for one GPU card. In your case, you have two cards and both from Intel. It looks like we currently do not have a way to bypass the check and you have a valid reason to have two platforms. 

https://github.com/darktable-org/darktable/pull/15830

**Comment by TimmyWe** [comment]
I have the onboard Intel Alder-Lake and use the second GPU Intel Arc A770 for my monitor. Can I deactivate the onboard GPU in Linux? I´m very new in Linux and don´t know that.

**Comment by jenshannoschwalm** [comment]
Please share log with 'darktable -d opencl', IT might BE a Bug as mentioned, it could also be you have multiple drivers installed. Cpu Emulation?

**Comment by TimmyWe** [comment]
the output is:

$ darktable -d opencl
darktable 4.6.0
Copyright (C) 2012-2023 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> DISABLED
  libheif                -> DISABLED
  libjxl                 -> DISABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0,2231 [dt_get_sysresource_level] switched to 2 as `large'
     0,2231   total mem:       63875MB
     0,2231   mipmap cache:    7984MB
     0,2231   available mem:   43664MB
     0,2231   singlebuff:      998MB
     0.2260 [opencl_init] opencl library 'libOpenCL' found on your system and loaded, preference 'default path'
     0.3368 [opencl_init] found 2 platforms
     0.3368 [opencl_init] detected wrong OpenCL platforms setup
     0.3368 [opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.

**Comment by jenshannoschwalm** [comment]
Looked into your log and clinfo output again, indeed it seems to be a dt bug. 

So you have two options atm,
1. you can probably disable your onboard graphics card in BIOS
2. look again into your installed drivers and look if there are several drivers for 770 and others, if so remove the opencl stuff for the other drivers...

**Comment by TimmyWe** [comment]
I searched for possibilities in BIOS to deactivate internal GPU, but indeed there is no option. 

How can I check in Linux if there were several drivers ( I'm very new in Linux) Where can I find OpenCL-stuff that I don't need?

**Comment by gi-man** [comment]
I'm not sure if you will be able disable the opencl only for the igpu. I think your best bet would be to wait for a fix.

Hanno: this scenario can also happen if the system has a AMD iGPU and an AMD GPU. Maybe we should just provide a warning instead.

**Comment by jenshannoschwalm** [comment]
> How can I check in Linux if there were several drivers ( I'm very new in Linux) Where can I find OpenCL-stuff that I don't need?

You have "something" in your distribution that shows (let's you change) the driver "packages" you have installed. Search for "intel" or "opencl" ...



> this scenario can also happen if the system has a AMD iGPU and an AMD GPU. Maybe we should just provide a warning instead.

That's bad :-) I guess we will have to revert or modify opencl "plausability" checks then ...

**Comment by TimmyWe** [comment]
I searched in Synaptic for driver packages, found "intel-opencl-icd", "openCL-c-headers" nothing else. I think i need this drivers?

**Comment by jenshannoschwalm** [comment]
> I searched in Synaptic for driver packages, found "intel-opencl-icd", "openCL-c-headers" nothing else. I think i need this drivers?

Seems to be ubuntu :-) don't know that but there should be more ... (maybe not in driver section?)

**Comment by gi-man** [comment]
I don't know much about Ubuntu or Intel, but assuming it would be similar to AMD, you install rocm-opencl once. The system will use the drivers for both cards, hence I don't think there is a way to only install drivers for the GPU and not the igpu. 

Your best bet is waiting for a fix/revert in the dt code.

**Comment by TimmyWe** [comment]
Okay, then I will wait for a fix in DT. Can I get a hint here if its done?

**Comment by ptilopteri** [comment]
you have an open #issue 
you should get an email whenever any update or adjustment is made concerning this issue.

**Comment by TimmyWe** [comment]
Ah thank you

**Comment by jenshannoschwalm** [comment]
> I don't know much about Ubuntu or Intel, but assuming it would be similar to AMD, you install rocm-opencl once. The system will use the drivers for both cards, hence I don't think there is a way to only install drivers for the GPU and not the igpu.

I am not absolutely sure about this. Anyway i will do a dt fix asap.

**Comment by TimmyWe** [comment]
Now it works!!! Thanx a lot!
