### ISSUE TITLE
[Bug] No GPU leads to OpenCL always trying to start

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#16143]
### Describe the bug

I installed darktable in a laptop that has no GPU with the plan to just use it for culling/tagging while away from the main computer. Every time I start darktable, I get a pop up warning saying it cant start OpenCL. 

When I go to the preference/processing settings, the `activate OpenCL support` shows `not available` without the checkbox option. OpenCL is enable by default and without the checkbox I cant disable it. 

The workaround was to edit darktablerc `opencl=FALSE`

### Steps to reproduce

1. Install dt in a system without GPU
2. Start dt
3. Get warning 

### Expected behavior

Warning only once or no warning.

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/97920861/0a65098e-7ba0-4848-ba86-cc35bfdb8dbd)

### Where did you obtain darktable from?

OBS

### darktable version

4.7.0~git295

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37 KDE

### Describe your system?

Acer R11 laptop

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

My initial thoughts is that we should just default darktable to have OpenCL false by default and let the users turn it on. 

Another more complex option is to change it to false if any issue is detected so the next time the user starts darktable, it is off.

**Comment by ralfbrown** [comment]
What is the output of `darktable-cltest` ?  (Please attach as a file,  don't paste into a message)
On my system with no OpenCL installed, those entries are grayed out and say "not available", so it appears that you **do** have OpenCL drivers installed, even without a supported GPU.

**Comment by gi-man** [comment]
This is fresh install in a fairly underpower system using a SoC N3160 CPU 4mb ram. Fedora does report a HD 400 graphics processor and there is an libopencl installed by default from fedora. 

```
     0.0863 [opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded, preference 'default path'
     0.0864 [opencl_init] 0 platforms detected, error: Unknown OpenCL error
     0.0864 [opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.
```

cl info
```
Number of platforms                               0

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.3.2
  ICD loader Profile                              OpenCL 3.0
```

**Comment by jenshannoschwalm** [comment]
> Another more complex option is to change it to false if any issue is detected so the next time the user starts darktable, it is off.

I would prefer to make the conf variable switched to OFF if we don't have opencl available for some reason.

**Comment by jenshannoschwalm** [comment]
plain `opencl=FALSE` i was thinking of.
