### ISSUE TITLE
git pull for current master broken

### ISSUE THREAD

**Issue by pehar1** [darktable-org/darktable#16148]
### Describe the bug

Trying to build from source as always leads to :
```
git pull https://github.com/darktable-org/darktable.git
remote: Enumerating objects: 399, done.
remote: Counting objects: 100% (398/398), done.
remote: Compressing objects: 100% (152/152), done.
remote: Total 399 (delta 272), reused 346 (delta 246), pack-reused 1
Empfange Objekte: 100% (399/399), 974.41 KiB | 11.60 MiB/s, fertig.
Löse Unterschiede auf: 100% (272/272), abgeschlossen mit 19 lokalen Objekten.
Von https://github.com/darktable-org/darktable
 * branch                  HEAD       -> FETCH_HEAD
Anfordern des Submoduls src/tests/integration
Von https://github.com/darktable-org/darktable-tests
   b69a8c5..7bdf7bc  master     -> origin/master
fatal: Fehler am anderen Ende: upload-pack: not our ref ecbd2df65aed1335803c7816b5a073f8fc181e41
Fehler während des Anforderns der Submodule:
        src/tests/integration
```

broken reference ?

### Steps to reproduce

Try
`git pull https://github.com/darktable-org/darktable.git`

### Expected behavior

pull request should be executed without error

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+214~g18772356aa

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

I think this does not matter here

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

I think this does not matter here

**Comment by TurboGit** [comment]
A transient issue, try again and it will work.

**Comment by pehar1** [comment]
Tried three times before posting, always the same result.
Created a completely fresh clone half an hour later -> build succesful
