### ISSUE TITLE
BUG: the line to change image rotation using  rotate & perspective module is not visible

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#16150]
If a module is expanded the line is not visible.
If all module are collapsed the line is visible.

**Comment by AxelG-DE** [comment]
I am sorry to say, but this PR exactly introduced he bug to me, that manually drawn structure lines are not shown anymore

**Comment by AxelG-DE** [comment]
I will show two videos, one the commit before and one with this PR merged

former scenario:
https://github.com/darktable-org/darktable/assets/49004103/933ecde1-7c89-411b-aff2-560737fca468

current scenario:
https://github.com/darktable-org/darktable/assets/49004103/f6c190d7-bfec-40a9-a3d0-3ffbdd6bf0b6

**Comment by TurboGit** [comment]
What a mess :( Sorry, this should be fixed here #16153.

**Comment by TurboGit** [comment]
There is some many different cases of line overlay that I did miss those while testing.

**Comment by TurboGit** [comment]
Note that I was speaking about the line to fix perspective but the rotation using right click over the canvas even if the perspective correction module is not active.

**Comment by AxelG-DE** [comment]
Yeah, I actually also noticed that right-click-rotate bug, but for me it is not reproducible, just sporadic, therefore I kept silent
