### ISSUE TITLE
Problem with the "brightness " slider in the new "Color Equalizer" module

### ISSUE THREAD

**Issue by Christian-Bouhon** [darktable-org/darktable#16162]
### Describe the bug

The "Turquoise" slider or color in brightness seems to be reversed. See video

### Steps to reproduce

1 selected the clarity tab
2 slide the slider to the right and the turquoise color will darken

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/120166629/672e8679-834c-42ef-8d66-07b5fc6c3bb2
[Mire RVB et fond gris neutre 4_01.exr.zip](https://github.com/darktable-org/darktable/files/14002589/Mire.RVB.et.fond.gris.neutre.4_01.exr.zip)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.7.0+333~g0152465082

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11Pro

### Describe your system?

Processeur	AMD Ryzen 7 7735HS with Radeon Graphics           3.20 GHz
Mémoire RAM installée	16,0 Go (15,2 Go utilisable)
Version de DirectX :	12.0 
Processeur graphique :		NVIDIA GeForce RTX 4050 Laptop GPU
Version du pilote :	546.33
Type de pilote :	DCH
Niveau de fonctionnalité Direct3D :	12_1
Noyaux CUDA :		2560 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 4050 Laptop GPU Driver 546

**Comment by TurboGit** [comment]
That's because the slider used also create darker (low curve) on both side of the curve. And I bet that the darkened color are actually those where the curve goes below the axis.

**Comment by Christian-Bouhon** [comment]
That's right, it's where the nearby curves come down, but the change in brightness is not proportional. I only have these problems with the "luminosity" tab.

I've redone the video, because there are also inconsistencies, for example if you turn up the "Lavender" brightness, the blue becomes yellow? If you activate Sigmoid, it becomes black, and if you activate filmic, it becomes white.

https://github.com/darktable-org/darktable/assets/120166629/4e83f805-3063-4528-9491-c2e2ce02ddec

**Comment by TurboGit** [comment]
Looks like Color Equalizer may be creating NaN.

**Comment by TurboGit** [comment]
@Christian-Bouhon : Can you test with current master? TIA.

**Comment by Christian-Bouhon** [comment]
@TurboGit : Super, the problem seems to have been solved, I'll do some more detailed tests this afternoon? I'll also make a short video.

**Comment by Christian-Bouhon** [comment]
First of all, congratulations on the work you've done. I really like the new interface and the option of displaying the sliders or not.
Regarding the problem mentioned above, there's no longer any problem with the brightness setting.
I'm just still having a few problems with the guided filter option.

https://github.com/darktable-org/darktable/assets/120166629/2a3be24f-c60c-4b0b-91dd-af28ff800091

But I also have to admit that in some cases, it offers a pleasant rendering, here's a photo where I expressly pushed the sliders

https://github.com/darktable-org/darktable/assets/120166629/f405086b-b0bf-45ef-bcc9-fb0a55ba9fe4

On the other hand, when it comes to contrasting colours and on small surfaces, the 'guided filter' option degrades other colours.

https://github.com/darktable-org/darktable/assets/120166629/144ef267-909a-405c-b098-fa6a8ceb9359

Personally, I don't think the module should be activated by default. 
Greetings from Brussels,
Christian

**Comment by todd-prior** [comment]
It is interesting that you noted a problem with the turquoise slider.... In my early evaluation f the module I used the vector scope and to me it seemed like the turquoise  slider was acting more on blue than the blue  slider... Desaturating red or green work nicely on those hues but blue did  not have the same magnitude of effect and actually the turquoise slider would desaturate blue to a greater extent.... I will build the latest master and see if this still seem to be the case..

**Comment by Christian-Bouhon** [comment]
Hello,
@TurboGit @jenshannoschwalm 
 Congratulations, all the problems reported above have been solved with the latest master version.
 At first sight, the guided filter works very well, my only suggestion would be to have a minimum "effect radius" of 1 px.

@todd-prior 
Concerning the blue and lavender sliders, it seems logical to me that the blue color (0,0,255) corresponds to 240° and if I'm not mistaken the blue slider would be at 225° and the lavender slider at 270°. 
https://github.com/darktable-org/darktable/assets/120166629/f52cc824-c2f2-44df-95b4-1d40be70fd77

Greetings from Brussels,
Christian

**Comment by todd-prior** [comment]
> Hello, @TurboGit @jenshannoschwalm Congratulations, all the problems reported above have been solved with the latest master version. At first sight, the guided filter works very well, my only suggestion would be to have a minimum "effect radius" of 1 px.
> 
> @todd-prior Concerning the blue and lavender sliders, it seems logical to me that the blue color (0,0,255) corresponds to 240° and if I'm not mistaken the blue slider would be at 225° and the lavender slider at 270°. https://github.com/darktable-org/darktable/assets/120166629/f52cc824-c2f2-44df-95b4-1d40be70fd77
> 
> Greetings from Brussels, Christian

Using you provided image. It just seems like all the sliders work at the positions of the vector scope where you would expect except blue is down by cyan and -100% desaturates a little but the lavendar slider to be behaves more like I would expect blue to do...


https://github.com/darktable-org/darktable/assets/44409419/2e8a7301-a4dc-450c-9db4-b6267184c6b2

**Comment by Christian-Bouhon** [comment]
Hello,

You're right, there are inconsistencies with the blue cursor. I've made several attempts without really understanding where the problem could come from, and in all sincerity, I don't get it.
The only logic I've found is that we have the same problem with the "color zone" module.

I added 8 small color zones to my test pattern, each representing 1/8 of the color wheel, i.e. hue values 0; 45; 90; 135; 180; 225; 270 and 315.
I don't know if these tests are representative and can help developers.

https://github.com/darktable-org/darktable/assets/120166629/032e8a33-be88-4d55-b61d-ae2cc9e8b5bb

Greetings from Brussels,
Christian

**Comment by todd-prior** [comment]
> I added 8 small color zones to my test pattern, each representing 1/8 of the color wheel, i.e. hue values 0; 45; 90; 135; 180; 225; 270 and 315.

Its a nice image to use to visualize.... for me it seems that the lavendar slider seems to have a much stronger effect on blue than the blue slide as I have already mentioned. I based that on saturation but even for hue... blue only moves the hue a few degrees where as lavender will swing it way around to green... again I have the filter off but I think it still behaves the same so I feel at least that there is some assignment of math that is not accurate for blue... but I may just not get it... Basically all the other sliders to me seem to target what I would expect except those two....

Your image... samples from two of the blue patches on the vectorscope...

![image](https://github.com/darktable-org/darktable/assets/44409419/1cabcb27-e8a8-44cf-b620-33db55b396b0)

Rotate with blue -180...

![image](https://github.com/darktable-org/darktable/assets/44409419/51a24bfc-a52d-49a4-841f-97652c4432cc)

Rotate with lavender -180

![image](https://github.com/darktable-org/darktable/assets/44409419/534e4a42-9595-4c55-9f91-39b5635064b3)

**Comment by Christian-Bouhon** [comment]
Hello,

The problem with the guided filter is completely solved in my home, congratulations for this work.

Concerning the distribution of color vs cursor I saw that there is another post open, I propose to close this one.
Greetings from Brussels.
Christian

**Comment by victoryforce** [comment]
> I propose to close this one.

OK, So I close here. BTW, as the author of the issue, you have the power to close it yourself.
