### ISSUE TITLE
Auto-apply pixel workflow defaults (Sigmoid)

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#16169]
### Describe the bug

When I select to auto-apply scene-referred workflow (Sigmoid), Filmic RGB is also enabled.

### Steps to reproduce

1. Open any image
2. Set Sigmoid as preferred workflow
3. Reset the history stack
4. Both Filmic and Sigmoid are enabled 

### Expected behavior

Enable only Sigmoid

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

11 Pro

**Comment by TurboGit** [comment]
You've probably added an auto apply Filmic preset. Look in preferences / presets and delete the offending preset.

**Comment by Pizzacutter-at-tty3** [comment]
Solved, thank you.
