### ISSUE TITLE
Suppport to Nikon Z8 camera

### ISSUE THREAD

**Issue by luizhaduarte** [darktable-org/darktable#16165]
### Describe the bug

Darktable does not support yet the raw files from Nikon Z8

### Steps to reproduce

Try to open a .NEF file from Nikon Z8

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment]
The new "high efficiency" compression modes are not supported yet, as mentioned in the release notes

**Comment by ralfbrown** [comment]
The Z8 is supported (#14593 ), but only if you set your camera to "lossless compressed" - the proprietary "high efficiency" compression (HE and HE* modes) have not be reverse-engineered yet.
