### ISSUE TITLE
X-Touch midi controller: darktable appears to use the wrong channel to write to the controller in its default factory configuration

### ISSUE THREAD

**Issue by phrrk** [darktable-org/darktable#16175]
### Describe the bug

I have been trying to get the X-Touch mini controller working for me.  For the most part all is fine.  However from my reading of the manual the LED's under the key's should remian lit whilst an associated shortcut is active, but in me experience they only light up momentarily as the key is pressed.  A brief discussion on Pixls.us indicates that some other users also only observe transient light up.  I have had a look at the code in src/libs/tools/midi.c and it certainly looks like part of this code sets these LEDs on and off as appropriate (not: I am not a C programmer so might have this wrong).  I should add that the lights around the controllers work as expected, and I have tested, with another application, that the LEDs under the keys  on my controller can be lit (and remain on) when sent the appropriate midi message.  Should these lights remain on?

### Steps to reproduce

1.  Associate some shortcuts (e.g. as in x-touch.lua) with controller keys
2.  press a key to invoke shortcut e.g. to open a darkroom module
3. light does not remain on once key is released

### Expected behavior

I expected light to remain on

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+334~g267142e4

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Also checked with a windows nightly build downloaded from here with the same outcome

**Comment by MStraeten** [comment]
Please attach your shortcuts settings since this seems to be dependent on the assigned actions.
I have attached expand/collapse of some darkroom left side panel modules to the buttons and at least in this case the light corresponds to the expand status: expanded —> light on

**Comment by phrrk** [comment]
Ok, 

Here are some of the shortcuts I have tried.  A mixture of LHS (the first), RHS modules and bottom toggles.  I have recompiled the code with an extra debugging print out,  and it certainly looks the appropriate message is constructed to turn the relevant light on or off.

midi:G#-1=lib/masks
midi:A-1=iop/colorequal
midi:A#-1=iop/toneequal
midi:B-1=iop/colorbalancergb
midi:C0=iop/channelmixerrgb
midi:E0=global/modifiers
midi:F0=global/modifiers;ctrl
midi:F#0=global/modifiers;alt
midi:A0=views/darkroom/color assessment
midi:A0;long=global/toggle focus peaking

**Comment by phrrk** [comment]
Ok,  I have figured out what the problem is.  Darktable uses channel 10 (on 0-15 numbering) as the channel to read from and channel 0 to write to (i.e as the controller's global Rx channel).  As received from factory the controller does indend send on channel 10, but its global Rx channel is channel 11.  Using the X-touch editor on a windows machine to change this to zero (in this editor this actually means channel 1 as it uses 1-16 numbering) all works as expected with the lights staying on when they should.  What remains a mystery to me is why the lights around the controllers worked before when the wrong channel was being used.  I did however notice when I was using the little command line program sendmidi to test that occassionally sent messages were responded to on the wrong channel.

Clearly there are 2 ways forward.  

1/ As done here edit the X-Touch configuration (unfortunately no linux based editor exists, but then the manual needs changing as it says

`Default settings are assumed; if any have been changed they can be restored using this [X-Touch Editor](https://mediadl.musictribe.com/download/software/behringer/X-TOUCH/X-TOUCH-EDITORv1-21.zip)`

2/ Change the code in midi.c to use the X-Touch's default RX channel.  This would work for future users, but would be bad news for existing ones if there systems were working correctly.

I suspect route 1 is the better.  I will leave this open for now so that others can consider what to do.

**Comment by MStraeten** [comment]
on my macOS system the x-touch mini sends on channel 11 and receives Control and Note On/Off signal on channel 1

**Comment by Donatzsky** [comment]
Wouldn't the best solution be to add a preference to set the channels?

**Comment by phrrk** [comment]
I just did a factory reset on my x-touch mini just in case it was a strange initial quirk, but it returned the Rx channel to channel 12 so that certainly seems to be the default channel now.  I think I will raise an issue on the manual site suggesting that users are adviced to check the Rx channel.

**Comment by phrrk** [comment]
I'll close this here and leave suggested modification to the manual in place there
