### ISSUE TITLE
color eq feedback 2

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#16197]
After all the recent commits to color equaliser I have feedback on its current state, which still produces undesirable results. This is on dt matser as of 28th January (0228e9a). 

Using current defaults, with all saturation sliders set to 0, it is clear certain colours are not being desaturated:

![sat-desat-a](https://github.com/darktable-org/darktable/assets/69561443/b06f9565-fa36-4808-b70d-cdf62e62d037)

And with all brightness sliders set to 0, same again:

![bright-desat-a](https://github.com/darktable-org/darktable/assets/69561443/304971cb-33ac-440c-8334-c9bf4c465dd7)

On a real world image, 100% zoom, desaturating red, we see that not all red has been desaturated:

![image-desat](https://github.com/darktable-org/darktable/assets/69561443/9bb997df-77e1-44f1-9899-31ae7a05e769)

Another real world image, desaturating all colours, we still see some yellow on the rocks, some blue in the sky, and many colours still saturated in the scopes.

![image-2-desat](https://github.com/darktable-org/darktable/assets/69561443/2af07ad8-514e-4095-a056-4dd727e2cb69)

**Comment by MStraeten** [comment]
You‘re using guided filters - that mitigates the effect.

**Comment by SoupyGit** [comment]
I'm aware whats happening. The question is, 1) are the devs aware? If not, this makes it known to them, and 2) is that type of mitigation desirable/acceptable?

The below images shows there are four hues (selected with colour picker) where the effect is not so much mitigated, but actually inoperable - they hardly change even when saturation or brightness is at 0. For saturation, the rest of the hues respond predictably. For brightness, it is much more variable.

![chart-brightness](https://github.com/darktable-org/darktable/assets/69561443/8406a1f9-8e6d-4474-9350-7ef290d6068f)

![chart-desat](https://github.com/darktable-org/darktable/assets/69561443/f6fbd6bf-da3a-4518-bf09-14548e8ecf59)

**Comment by todd-prior** [comment]
I haven't noticed this but I have done all my exploring with the guided filter off to take that out of the equation...for me now its the blue and lavendar sliders in saturation... blue does very little to blue and lavendar seems to act more like the blue slider ... All the others line up and seem to behave on a vector scope.... I was trying as a total novice to understand the code and didn't get far but I see references in the to luts and or lut generation and I wonder if there might be an issue there as the sliders all seem in order or at least I didn't see something like a simple typo.... target radius has a big impact on the final result so you could play with that or experiement at first wiht the filter off....

**Comment by SoupyGit** [comment]
The issue is not about making b&w images - I simply use that as an example to clearly demonstrate the problem - however for a module like this, it is an entirely valid use case that someone would want to make all hues grey except for one. Think of how red is used in 'Schindler's List'. In current state, that is impossible with guided filter whenever an image contains any of the above four hues. (Yes you could still do it with color balance rgb, but one of the purposes of a module like this is to no longer require multiple instances of color balance rgb). 

![oops](https://github.com/darktable-org/darktable/assets/69561443/9e627951-fc66-4644-9ab4-4b4d364339f7)

![oops2](https://github.com/darktable-org/darktable/assets/69561443/7659f620-258a-46c3-a6a5-6ae41f3e7c8b)

Problem is obvious.

Moreover, if anyone wants to specifically adjust those four hues, either increase or decrease, by any amount, they can't. So the issue is not isolated to b&w.

To me, the attempts to improve guided filter for brightness has caused a clear regression for saturation.

It only seems to work as expected for hue:

![hue-ok](https://github.com/darktable-org/darktable/assets/69561443/8a56fa14-87d4-432c-baef-cd7a499b6020)

**Comment by todd-prior** [comment]
> It only seems to work as expected for hue:

Sample one spot...blue or a blue and look at the vectorscope... use the hue slider for blue and now lavender.... to me lavendar has too much impact on blue and blue too little so I am not sure ...Basically rotate red and green.. all good and the intermediate colors behave as they should but for me the blue slider behaves more like one of the intermediate colors and lavender will do the big swing in hue on blue.... See if you see this or I am just off base....

**Comment by SoupyGit** [comment]
Latest changes (3ae9a7a) are a great improvement, well done!

Saturation:
![saturation](https://github.com/darktable-org/darktable/assets/69561443/c568f662-dc30-490e-bfc6-e501f3fbcfe0)

Brightness:
![brightness](https://github.com/darktable-org/darktable/assets/69561443/dc63ee70-4d95-4c63-b32f-c47b9c52116b)

@todd-prior I definitely see what you see.

Blue:
![blue](https://github.com/darktable-org/darktable/assets/69561443/a3316039-6fcd-4246-bda7-9cade4d85101)

Violet:
![violet](https://github.com/darktable-org/darktable/assets/69561443/1bdfb637-cb8f-4c9a-ab98-0237e50f23ff)

My unlearned guess its that its probably some quirk of having to circle (hue, 360 degrees) a triangular or diamond shape (colour space). Also perhaps that 8 is an unusual number of points to choose. I understand why it is chosen in terms of available hardware with that many wheels to turn, but on the matter of colour itself, since colour spaces have 3 primaries, 3 secondaries, and 6 tertiaries, for finer separation between hues it would make more sense for the number of points to be divisible by 3 (I personally would opt for 12). Then the violet/purple slider would not effect blue so much.
