### ISSUE TITLE
Warning about "Night Mode"

### ISSUE THREAD

**Issue by mega-stoffel** [darktable-org/darktable#16196]
**Is your feature request related to a problem? Please describe.**
Not a technical one.

**Describe the solution you'd like**
It happens sometime to me, that I edit pictures in late afternoons/evenings. Then the windows night mode (or a similar process on my Ubuntu machine) slowly starts and changes my monitor colors, and I often don't notice it.

Therefore I'd like to have a warning of darktable, if such a process is starting to change my monitor colors. And I can manually deactivate it - or it maybe even could deactivate it automatically, as long as darktable is running.

**Alternatives**
I'd have to take care about it on my own, which doesn't work too good, since I'm only human. ;-)

**Additional context**

**Comment by zisoft** [comment]
On macOS I use an app called "shifty" which automatically disables night mode and true color modes when I start darktable.
Maybe there is something similar available for Window/Linux ?

**Comment by MStraeten** [comment]
Not a issue darktable can solve, as well as darktable can’t react on changed illumination of the room where you do your image editing, or improper calibration of your display …
Best: disable such features on your image editing machine -if you can’t take care

**Comment by victoryforce** [comment]
> Therefore I'd like to have a warning of darktable, if such a process is starting to change my monitor colors.

As far as I understand, this is not possible. darktable is not part of the OS and cannot monitor the running of processes in the system or their impact on the system display settings. If a certain OS allows control of "night mode" from application programs, then the best solution would be to create a batch file with the launch of such a program before (and after) darktable. But duplicating the functionality of such programs in the darktable itself is impractical and is simply a waste of developer resources.

Therefore, I close this issue. Feel free to comment further if you disagree.
