### ISSUE TITLE
Import dialogue - interface not responsive.

### ISSUE THREAD

**Issue by ThePeach** [darktable-org/darktable#16214]
### Describe the bug

After freshly starting Darktable I'm unable to import anything into my library. Only the close button works. 

Darktable version is 4.6.0-3 on Archlinux 

### Steps to reproduce

1. open darktable
2. click "add to library" or "copy & import"
3. try to interact with anything on the import dialogue

### Expected behavior

I should be able to click on anything on the dialogue.

### Logfile | Screenshot | Screencast

[Screencast from 2024-01-30 11-51-00.webm](https://github.com/darktable-org/darktable/assets/249718/3136f2ed-7ed7-4823-bb80-09222660ddce)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

ArchLinux

### Describe your system?

Using Gnome on Wayland, latest version.

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by ralfbrown** [comment]
Do you have the "recursive" checkbox ticked and have the import location as the top of a large directory tree with many many images?  If so, that's a known problem which has been fixed in master and the upcoming 4.6.1 release. You just need to be patient while darktable scans that entire tree....  (The fixed version does partial updates during the scan, so it remains responsive.)

**Comment by ThePeach** [comment]
> Do you have the "recursive" checkbox ticked and have the import location as the top of a large directory tree with many many images? If so, that's a known problem which has been fixed in master and the upcoming 4.6.1 release. You just need to be patient while darktable scans that entire tree.... (The fixed version does partial updates during the scan, so it remains responsive.)

So if that's the case, if I just let it sit there, it should work after a while, right? At least it works confirm your suspicion I hope. I'll report back soon

**Comment by ThePeach** [comment]
Have to say that waiting didn't do anything. I can try to build from git and see if that's still there. Unless there's a way to debug this version without having to use gdb.
