### ISSUE TITLE
Error loading files when recursive directory is checked on

### ISSUE THREAD

**Issue by Sciroccogti** [darktable-org/darktable#16215]
### Describe the bug

When using add to library with `recursive directory` on, almost every image is failed to load.

Manually adding single folder without `recursive directory` on works fine.

### Steps to reproduce

1. add to library...
2. check `recursive directory` on
3. select some folder and add it to library

### Logfile | Screenshot | Screencast

`.\darktable.exe -d opencl` outputs nothing wrong

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

2070 Super

**Comment by ralfbrown** [comment]
Known issue, fixed in master and the upcoming 4.6.1.

**Comment by pozix604** [comment]
> upcoming 4.6.1.

When will this release be cut?

**Comment by wpferguson** [comment]
Approximately 10 days
