### ISSUE TITLE
darktable "arm64" does not run on my macbook pro with Apple M1 chip

### ISSUE THREAD

**Issue by mc-ott** [darktable-org/darktable#16248]
Trying to run "darktable arm64" version on my MacBook M1 Pro, Sonoma 14.3, 16GB memory, I get the following error :
 <<< “darktable” is damaged and can’t be opened. You should move it to the Trash. >>>

The "darktable x86_64" installs and runs OK.

**Comment by ralfbrown** [comment]
It's a "bug" in the OS - it should be reporting that the installation file is unsigned, not damaged.
See https://www.darktable.org/install/#macos

**Comment by parafin** [comment]
Are you sure it’s a bug in OS? As far as I can see the code is “signed” with “ad-hoc” signature, which is pretty useless. So it’s not totally unsigned, that’s why I think the error is different. Have you tried removing all signatures instead, thus making the code truly unsigned? It may change the resulting error and significantly reduce the number of bug reports about damaged app (which does sound scary).

**Comment by zisoft** [comment]
The "App is damaged" message only occurs on arm64, not on x86_64.
The building and signing process is the same on both platforms.

**Comment by parafin** [comment]
The logic for newer architecture is newer, so what? I think it’s worth investing some time into investigating how arm64 behaves now, since x86_64 is becoming obsolete. Are other unsigned arm64 Mac apps being reported as damaged as well?

**Comment by parafin** [comment]
My point is that I think you shouldn’t use ad-hoc signature. x86_64 code may not be complaining, because IMHO ad-hoc signature is a relatively new thing, and x86_64 codepath might not know about it at all.

**Comment by zisoft** [comment]
I can remove ad-hoc signing but I doubt that this will help on arm64. Reasons for "App is damaged":

The file or app has unharmful content that XProtect can't recognize.
The file or app contains malware.
The content of the file or app has changed.
**The app is from an unidentified developer.**
**The app is unsigned or signed incorrectly.**
The app isn't notarized or notarized properly.
The app isn't well supported on your current operating system.

**Comment by parafin** [comment]
Yeah, it still won't run of course without that xattr command (or right-click/control-click), the point is to try to have less scary message from OS. I mean if I download something and OS says it is damaged, I would think that file was corrupted at some point, not that it's unsigned.

**Comment by zisoft** [comment]
yes, that is what @ralfbrown mentioned above with "bug in the OS". The message is scary and misleading.

**Comment by zisoft** [comment]
Just an addition from the Wiki page linked above:

> Ad hoc signing
> This is especially important on ARM64 M1 Apple processors which require all native code to be validly signed (if only ad hoc) or the operating system will not execute it, instead killing it on launch.

So ad-hoc signing is not necessary on x86_64, but required on arm64.
