### ISSUE TITLE
Darktable error when installing on Mac

### ISSUE THREAD

**Issue by krattster** [darktable-org/darktable#16245]
### Describe the bug

Hi,

I have tried to install Darktable on my Macbook Pro (M3 Max on Mac OS 14.2.1). After downloading and trying to install an error message appears that suggests the Darktable file is damaged. I have repeated a number of times with no success. Wondering what I can do to fix and install Darktable. Thank you for your assistance. I have attached screen shots to help clarify.

<img width="299" alt="Screenshot 2024-02-04 at 8 39 04 pm" src="https://github.com/darktable-org/darktable/assets/158797971/0d7db6c2-1598-47ce-9f74-8a9a849ab253">
<img width="746" alt="Screenshot 2024-02-04 at 8 39 19 pm" src="https://github.com/darktable-org/darktable/assets/158797971/bffdae65-dd7f-4f69-93fa-71a27c1d15d0">
<img width="304" alt="Screenshot 2024-02-04 at 8 39 31 pm" src="https://github.com/darktable-org/darktable/assets/158797971/16783763-9a61-4f88-876d-467a110e80cb">
<img width="554" alt="Screenshot 2024-02-04 at 8 39 45 pm" src="https://github.com/darktable-org/darktable/assets/158797971/40606af6-a7f5-4f58-b920-a91caa633f1a">
<img width="352" alt="Screenshot 2024-02-04 at 8 40 27 pm" src="https://github.com/darktable-org/darktable/assets/158797971/e9be19dd-736e-4d91-a3f7-3b752fca3b11">

### Steps to reproduce

1. After downloading and double clicking the dmg file, Mac OS prevents Darktable from opening. 
2. I then right click and choose 'Open with....'
3. File opens and I drag into Applications folder
4. When I then double click on the Darktable icon  icon in the Applications folder an error message is generated suggesting that the file is damages and that I need to move the file to the bin.

I have attached screenshots

### Expected behavior

Darktable should install successfully and open when I click on the Darktable icon.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0 arm.dmg

### What OS are you using?

Mac

### What is the version of your OS?

Mac OS 14.2.1

### Describe your system?

64 Gb RAM Macbook Pro M3 Max

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Hopefully information I have provided is sufficient. Please let me know what additional information you require.

64 Gb RAM Macbook Pro M3 Max

**Comment by victoryforce** [comment]
> downloaded from [www.darktable.org](http://www.darktable.org/)

Did you click on https://www.darktable.org/install/#macos and read the installation notes?

**Comment by krattster** [comment]
Thank you for your reply. Yes, I did read  the installation notes.

That is why I was able to open the and install the file after downloading (Step 1 of the Installation as per the first 3 screenshoots).

The issue I ran across was why did Mac OS indicate that the file was damaged (as per the last screen shot) after the icon was dragged into the applications folder).

This is represented by the last 2 screenshots (screen shots 4 & 5).

At this second stage I was unable to run Darktable after the initial installation and the Mac OS suggested that I move the Darktable application to the 'Bin'.

Hope that clarifies the situation further.

Regards

Mark




Mark Kratochvil

Learning Facilitator - Diploma PhotoImaging



P: 1300 575 803   M: +61 (0) 414 306 555 E: ***@***.***

 [cid:9b373a4c-b846-48d7-b356-d00aa08ee398]



Torrens University Australia acknowledges the Australian Aboriginal and Torres Strait Islander of Gadigal people as the first inhabitants of the nation and the traditional custodians of the lands where we live, learn and work. Torrens University Australia respectfully acknowledges their Ancestors and Elders, past and present.



–

We acknowledge and respect the privacy of individuals. The information above is intended for the addressee named and may contain confidential information. If you are not the intended recipient, please delete it and notify the sender. We operate through the following legal entities: Torrens Global Education Services Pty Ltd ABN 33 603 224 728; Think: Colleges Pty Ltd, ABN 93 050 049 299, RTO No. 0269, HEP No. 4375, CRICOS Provider Code 00246M; Torrens University Australia Ltd, ABN 99 154 937 005, RTO No. 41343, HEP No. 4449, CRICOS Provider Code 03389E ark

***@***.***?anonymous&ep=signature>           Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________

**Comment by krattster** [comment]
My apologies, I just noticed the text in the Install notes about the App being damaged (I assume this represents the step I am referring to, after the application is dragged into the Application folder and the 'damaged' notice appears.

I am not that familiar with Terminal and I am not confident about the recommended Terminal solution.

The message generated by Mac OS suggests that Darktable is damaged and the Terminal procedure would suggest that the issue is a quarantine issue?

Again apologies for my error.

Thank you for your assistance.

Regards

Mark




Mark Kratochvil

Learning Facilitator - Diploma PhotoImaging



P: 1300 575 803   M: +61 (0) 414 306 555 E: ***@***.***

 [cid:fd3c96b2-59f4-4ed4-8c64-7278447dcef1]



Torrens University Australia acknowledges the Australian Aboriginal and Torres Strait Islander of Gadigal people as the first inhabitants of the nation and the traditional custodians of the lands where we live, learn and work. Torrens University Australia respectfully acknowledges their Ancestors and Elders, past and present.



–

We acknowledge and respect the privacy of individuals. The information above is intended for the addressee named and may contain confidential information. If you are not the intended recipient, please delete it and notify the sender. We operate through the following legal entities: Torrens Global Education Services Pty Ltd ABN 33 603 224 728; Think: Colleges Pty Ltd, ABN 93 050 049 299, RTO No. 0269, HEP No. 4375, CRICOS Provider Code 00246M; Torrens University Australia Ltd, ABN 99 154 937 005, RTO No. 41343, HEP No. 4449, CRICOS Provider Code 03389E ark

***@***.***?anonymous&ep=signature>           Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________

**Comment by victoryforce** [comment]
> I am not that familiar with Terminal

There is absolutely no need to be familiar with the Terminal program. All you need is to open the Terminal program.

> and I am not confident about the recommended Terminal solution.

Please clarify. I'm not sure I understand your point. In what sense are you _not confident_ about the recommended solution?

Did you run the recommended command in Terminal?

**Comment by krattster** [comment]
Thank you,

Not confident as I have never used Terminal. Followed instructions and was successful. Issue resolved, used the 2nd Terminal command and was able to open the Darktable Program. Thank you


Mark Kratochvil

Learning Facilitator - Diploma PhotoImaging



P: 1300 575 803   M: +61 (0) 414 306 555 E: ***@***.***

 [cid:b7329d4c-339d-4329-a3de-c1d437961e64]



Torrens University Australia acknowledges the Australian Aboriginal and Torres Strait Islander of Gadigal people as the first inhabitants of the nation and the traditional custodians of the lands where we live, learn and work. Torrens University Australia respectfully acknowledges their Ancestors and Elders, past and present.



–

We acknowledge and respect the privacy of individuals. The information above is intended for the addressee named and may contain confidential information. If you are not the intended recipient, please delete it and notify the sender. We operate through the following legal entities: Torrens Global Education Services Pty Ltd ABN 33 603 224 728; Think: Colleges Pty Ltd, ABN 93 050 049 299, RTO No. 0269, HEP No. 4375, CRICOS Provider Code 00246M; Torrens University Australia Ltd, ABN 99 154 937 005, RTO No. 41343, HEP No. 4449, CRICOS Provider Code 03389E ark

***@***.***?anonymous&ep=signature>           Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
