### ISSUE TITLE
How to adjust workflow to darktable

### ISSUE THREAD

**Issue by webysther** [darktable-org/darktable#16252]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
[darktable-generate-cache](https://docs.darktable.org/usermanual/4.0/en/special-topics/program-invocation/darktable-generate-cache/) detected lock by the gui/cli, but I want to know if is possible to create a 'relaxed' way when call from cli to allow to run both at same time? This will allow me to automated some stuff.

**Comment by webysther** [comment]
One solution is start supporting WAL on SQLite, this maybe reduce the risk of corrupt the database and increase the performance like [happens with digikam](https://docs.digikam.org/en/setup_application/database_settings.html).

**Comment by jenshannoschwalm** [comment]
> Sure, that's why I looking to a way to running simultaneously,

That's clearly not supported and i also think not intended:-) Would require a lot of database / filesystem code changes and those would be very difficult to verify...

**Comment by webysther** [comment]
> > Sure, that's why I looking to a way to running simultaneously,
> 
> That's clearly not supported and i also think not intended:-) Would require a lot of database / filesystem code changes and those would be very difficult to verify...

Like the GTK migration, I believe this could be beneficial to consider for the future.

**Comment by webysther** [comment]
I'd rather invest 5 years or more taking this slowly for the project.

**Comment by webysther** [comment]
> The problem with running darktable and a darktable cl instance at the same time is system resources. A GPU is required for any reasonable performance. A darktable instance can peg the GPU developing the image, and peg the CPU updating the preview. If it was possible to run darktable-cli or darktable-generate-cache at the same time as a darktable gui instance the gui would become unresponsive.
> 
> You would need a system with multiple CPUs, GPUs, and a ton of memory to even have a chance of getting something responsive.
> 
> You could use multiple systems and clone the database while keeping the image files on NAS.

Yes, I think about clone but don't have ideia how this will make the workflow terrible to maintain, I need to test this. For resources I have a server with 256GB RAM and 3 GPU's that I want to test. I move from LrC to Darktable to able to access in a remote why and to be able to use any resources I want when access from VNC (LSIO KasmVNC version), the ideia is for my all homelab actually.

**Comment by webysther** [comment]
Well another point is about architecture strategy, if I was able to do this, I can keep the process more flat processing only one image at time for instance. I like the ideia of github actions (CI/CD) to have delegated runner with features available and redirect the job, like Tdarr do to video transcoding. Based on this I image to be able to redirect the job to some agent instance with the reqs needed and process the image, this can be made with any process of one image and this can be a game changer.

**Comment by webysther** [comment]
> Running dartable-generate-cache simultaneously would be extremely hard (if at all possible) to get right.

Besides sqlite lock, which here (https://github.com/darktable-org/darktable/blob/ad2feeb830e9d3a1b7c00959cdc30339fc7e091a/src/generate-cache/main.c#L48) is hard to make work? As far I get the complex process is all about the creation of mipmap, there any database write for cache or the check is only in disk?

**Comment by webysther** [comment]
> > Sure, that's why I looking to a way to running simultaneously,
> 
> That's clearly not supported and i also think not intended:-) Would require a lot of database / filesystem code changes and those would be very difficult to verify...

For database I found ~30 point of risk in code with `INSERT|UPDATE`, about any `SELECT` is very safe and can be changed easy. The problem is filesystem because if someone start in the wrong way mulitple tasks this can be dangerous do keep the state of XMP like the write of xmp in the thumb cache.

**Comment by parafin** [comment]
You want to do a major design change (strictly one-instance to concurrent execution) without any changes to the code architecture. You may get this particular feature (thumbs generation) to work in some (most) cases, but project as the whole will degrade because of that. dt history is full of such well-intentioned and not thought-through additions which made codebase very hard to maintain. It can’t be fixed by grepping SQL statements, because it’s about whole logic of application (its state), which is very hard to comprehend at this point of project development, even by core developers. I’m no longer an active developer/maintainer, but I want to state my concerns about this.

**Comment by webysther** [comment]
> You want to do a major design change (strictly one-instance to concurrent execution) without any changes to the code architecture. You may get this particular feature (thumbs generation) to work in some (most) cases, but project as the whole will degrade because of that. dt history is full of such well-intentioned and not thought-through additions which made codebase very hard to maintain. It can’t be fixed by grepping SQL statements, because it’s about whole logic of application (its state), which is very hard to comprehend at this point of project development, even by core developers. I’m no longer an active developer/maintainer, but I want to state my concerns about this.

I become concerned when developers working on a project avoid engaging in discussions.

I have participated in similar debates, and my experience leads me to consider these concerns valid. However, it's important to note that they can also be indicative of underlying issues. For code to evolve sustainably, it's essential to foster an environment of open and collaborative communication among developers. This practice is widely recognized as crucial for identifying and addressing challenges, ensuring that proposed solutions are robust and effective in the long term. Avoiding important conversations can result in gaps in understanding and, eventually, in ill-informed decisions that compromise the quality and scalability of the code. Therefore, encouraging and valuing constructive discussion is an essential approach to cultivate code that can thrive and adapt to constantly changing demands.

**Comment by webysther** [comment]
Indeed, I believe the fundamental basis here lies in the practices of refactoring, which can be applied with concrete concepts from Martin Fowler. This is precisely what I am attempting to achieve—incrementally introducing changes to the codebase that enable evolution. I will mention changes that can help address a common problem for projects like this:

- Migration of non-critical but error-prone components to Rust/Go using glib-rs
- Initiating the decoupling of core code components for standalone compilation (similar to what is already being done with rawspeed).

I believe all of these initiatives are highly valuable and can be implemented in a non-disruptive manner, particularly with the correct utilization of feature flags, as already implemented in certain parts of the codebase.

**Comment by webysther** [comment]
> You want to do a major design change (strictly one-instance to concurrent execution) without any changes to the code architecture. You may get this particular feature (thumbs generation) to work in some (most) cases, but project as the whole will degrade because of that. dt history is full of such well-intentioned and not thought-through additions which made codebase very hard to maintain. It can’t be fixed by grepping SQL statements, because it’s about whole logic of application (its state), which is very hard to comprehend at this point of project development, even by core developers. I’m no longer an active developer/maintainer, but I want to state my concerns about this.

For you, is the current code easy to maintain in its current state?

**Comment by webysther** [comment]
"To be honest, gentlemen, the feeling conveyed when each of the core developers participated in this issue to give an evasive and non-inclusive response makes me wonder what the real problem is here. Do you want only what the majority of the main developers desire to be implemented, such as the migration to GTK? How does it work so that I can persuade you to focus on what I should do instead of just saying it's impossible?"

**Comment by wpferguson** [comment]
darktable is a raw developer.  It can be used for other things, but at it's core it is a raw developer.  Making changes to the design of darktable so that it fits your use case doesn't align with the goals of the project.  darktable already supports concurrent cache generation internally, so that problem has been solved for darktable users.

**Comment by webysther** [comment]
> > and non-inclusive response makes me wonder what the real problem is here.
> 
> Lack of resources on the project maybe? Hard to understand your goal?
> 
> You want to run darktable-generate-cache run simultaneously with darktable-cli. But the former is only useful for the GUI whereas the second is only command line and as already said we have already a thumb updater on the darktable GUI.
> 
> We (core devs) know that this is a tricky path. So at then end why taking risk for a very specific feature?
> 
> That being said if you come up with a small patch, very clean, easy to review a quite localized we certainly can review it. The project is very open when there is really a need for something.

Maybe I'm not clear:

My current workflow

- I go outside, take some pictures
- Import the photos over Darktable to NAS (wait)
- Make local copy (wait)
- Generate cache (wait)
- Start working in the photos

My future workflow

- I go outside, take some pictures
- Start upload photos to NAS from Hotel
- Automatic income folder start a job to add and not import in darktable (here maybe this can be a import with a flag to make a local copy!?)
- Automatic start generate cache after finish the import (another flag to darktable-cli to generate the cache!?)
- Start working in the photos

**Comment by webysther** [comment]
> darktable is a raw developer. It can be used for other things, but at it's core it is a raw developer. Making changes to the design of darktable so that it fits your use case doesn't align with the goals of the project. darktable already supports concurrent cache generation internally, so that problem has been solved for darktable users.

Generate cache is a step of using any RAW editor...

**Comment by webysther** [comment]
@TurboGit maybe something like this?

```sh 
darktable-cli --add <folder> --generate-cache [--min-mip <0-8>] [-m, --max-mip <0-8>] --local-copy
```

**Comment by webysther** [comment]
> I think I better understand the goal, indeed copying pictures from over an Hotel to a NAS is slow... And could be very slow depending on the actual Internet speed. A better workflow for your scenario would be:
> 
> * Import picture locally
> * Start editing them right way
> * Create the local copies (should be fast as local)
> * Over the night move (in GUI do a `move...` action) the pictures to the NAS
> 
> Would this work for you? And this should work already.

I use a remote machine over VNC, my notebook don't have enough resources, this is why I move to the NAS to create a hot copy in the processing server.

Looks like no one is moving the workload to a homelab after all, this is how I read what you said.

![image](https://github.com/darktable-org/darktable/assets/750007/296586ed-83d9-40cd-8bb2-4447f8e3e1d2)

- Notebook: Energy efficient one just to access over VPN a PC using VNC
- PC: Powerhorse to work
- NAS: Backup/NFS

To enable this I use:
- LinuxServer Darktable on PC
- NAS over NFS
- Notebook over Browser

A read a lot of people doing this with homelab and to be more digital nomad, but maybe I lost something.

**Comment by webysther** [comment]
Maybe copy direct to PC but I need to enable a service to do this, normally every NAS is built with SFTP in mind to do this kindle of thing.

**Comment by webysther** [comment]
Now I will travel to Brazil to scan the family photos, normally I use the archival mode to make sure I can get the best every bit possible, which represent this:

![image](https://github.com/darktable-org/darktable/assets/750007/4fcb9cbd-f70c-4f57-b36e-c9d9ced67359)

Doing this processing when wait is really slow, normally use no less than 50GB RAM. I don't have too much time to scan when visit the family so I try to make the best and upload after, but to just open the scan file is not possible, using OS to look the tiff is ok just to validate.

**Comment by webysther** [comment]
I have a serious problem with big pictures, look my profile on Wikimedia commons: https://commons.wikimedia.org/wiki/User:Webysther

This picture is huge: https://commons.wikimedia.org/wiki/File:Webysther_20170619072151_-_Pedra_do_ba%C3%BA_e_a_direita_Vale_do_Paiol_Grande.jpg

And this is my last software to move to OSS to stop using windows. :(

**Comment by webysther** [comment]
For me darktable-cli will be the cli version to do everything what you can do in the gui, but this is not the focus. On Wikimedia you cannot change the picture, normally you can do a few minor changes, so mostly of the process can be automated to make more fast to document the articles when keep the quality level high.

**Comment by wpferguson** [comment]
@webysther can we start this process over?  What you are looking for is a workflow.  You have come up with one in your mind, but you need darktable changed in order to make the process work.

How about we table all of the "change darktable" issues, and open a new issue asking for help with a workflow.  You list:

* what your going to input to the workflow (pictures, type (raw, tif, ...), size, etc)
* what resources you have to work with (homelab, nas, multiple GPU's, etc)
* what you want the workflow to produce (images, size, etc...)

and then you ask for ideas about how to use darktable to make this work.

The nice thing about the devs is that they are users and have been for years.  They know how darktable works and what you can and can't do with it.  For instance, did you know that it's possible to automate the GUI?

**Comment by webysther** [comment]
> @webysther can we start this process over? What you are looking for is a workflow. You have come up with one in your mind, but you need darktable changed in order to make the process work.
> 
> How about we table all of the "change darktable" issues, and open a new issue asking for help with a workflow. You list:
> 
> * what your going to input to the workflow (pictures, type (raw, tif, ...), size, etc)
> * what resources you have to work with (homelab, nas, multiple GPU's, etc)
> * what you want the workflow to produce (images, size, etc...)
> 
> and then you ask for ideas about how to use darktable to make this work.
> 
> The nice thing about the devs is that they are users and have been for years. They know how darktable works and what you can and can't do with it. For instance, did you know that it's possible to automate the GUI?

Yes, using Lua, right? When utilizing Lua for automation in darktable, though it renders darktable almost useless, do you encounter any slowdowns when editing in the darkroom due to background jobs running with Lua?

The primary idea behind requesting these changes is not to alter the application to fit my workflow; the main focus is to gain autonomy in isolating problems. Consider:

- If the application can run on separate machines, I eliminate any chance of slowdown when I start using the GUI.
- If the application can run headless, I can integrate it with a vast array of other software, such as n8n, Node-RED, and other services using Docker, among others.
- If the application can run concurrently, I can perform parallel background jobs.

Please, don't misunderstand me. I understand your point. I skipped the step of explaining my workflow, which is based on what I've observed professional photographers attempting to do with LrC. With darktable, I've gathered the main concerns about flexibility that I've come across and tried to address them. I never imagined that this might come across in the worst way possible.

My background with software revolves around making it easier to expose an application to provide autonomy. However, in the case of darktable, the emphasis seems to be on staying within the GUI indefinitely, and the darktable-cli appears to be something you strongly dislike. Is that correct? Because personally, when I first read about darktable-cli, my initial reaction was like, 'Finally!' But if the focus is to remain solely within the GUI, then that's not a problem. What are my options?

1) Do I wait for the GUI to process 'add to library,' 'local copy,' and 'create thumb cache' tasks?
2) Do I need to loosen my constraints and spend more money? Should I buy a workstation notebook with 64GB RAM and a dedicated GPU like the RTX 4080? Or perhaps a gaming notebook with similar specifications like the RTX 4060?
3) Or should I simply step back and leave the volunteer?

**Comment by webysther** [comment]
@wpferguson Just a few questions about the automate the gui:

- I can run every gui command on darktable-cli?
- When running the gui to run a lua script the process of automation is based on polling/fs-watch a folder?

**Comment by webysther** [comment]
Another option maybe is creation a hot cache with ZFS in the processing machine (PC) to move direct the pictures to skip the process of local copy like you guys said before, with ZFS I have at least some disk security not a backup rule 3-2-1 but is better than just move to a disk direct. But I need to running the 'add to library' and 'thumb cache'.

**Comment by webysther** [comment]
The material I used to build this setup is based on these books:

- Photographer's Guide to the Digital Lifecycle - Ben Greisler
- Magnum Contact Sheets - Kristen Lubben
- Linux Photography - Dmitri Popov
- The DAM Book - Peter Krogh
- Digitizing Your Photos with Your Camera and Lightroom - Peter Krogh
- Organizing Your Photos with Lightroom 5 - Peter Krogh
- Multi-catalog Workflow with Lightroom 5 - Peter Krogh
- Lots of tips of much better photographer than me on wikimdia commons

Do you guys have any book or material to recomend?

I read the section about the darktable workflow is the same base of LrC in 3 steps, my exploration is about what normally happens inside a newspaper because is like a studio magnum is based of, explode the stages of darktable step 2 in minor steps.

**Comment by webysther** [comment]
Nevermind guys, I will give a shot here:

https://github.com/hanatos/vkdt
https://github.com/aurelienpierreeng/ansel

Looks like the project has I bad history already. :(

**Comment by webysther** [comment]
> Nice, that's all we get after answering your questions and trying to understand your goal!

Not really, I will probally trying doing this, but as I want sounds out of scope to you guys, I just give you peace to focus in what you want, I just need to get things done. I start move some code to rust already but I will never try to create a PR, some projects you just need to stay alone, more than 500 projects here in github and sometimes a few ones is too hard, is really sad, the project is great!

Please, use my images, I think the size maybe is rare to find and if you want more information, I just found this:

https://developer.adobe.com/lightroom/lightroom-api-docs/api
https://github.com/AdobeDocs/lightroom-public-apis
https://developer.adobe.com/lightroom

If you want my help please, let me know!

**Comment by webysther** [comment]
I will try to expose a API and maybe use the ideia of using lua script to process images, but this is crazy to use a gui to process batch request from API, if you want to move to future, consider my point, looks like I'm not alone after all:

https://community.adobe.com/t5/lightroom-classic-discussions/lightroom-command-line-usage/m-p/1862083

**Comment by webysther** [comment]
@TurboGit the project have the C API docs like this https://www.digikam.org/api/index.html?

**Comment by wpferguson** [comment]
@webysther 

* darktable-cli is not darktable GUI running headless.  darktable-cli is a wrapper around the export function.  It's used to export processed images.  It does not require database access unless you are applying a style to the exported images.  If you are then access to the data database is required to get the style settings.  https://docs.darktable.org/usermanual/4.6/en/special-topics/program-invocation/darktable-cli/
* why are you focused on darktable-generate-cache?  The purpose of this program is to populate the cache for darktable GUI.  Are you wanting to use the cache images for another purpose?
* The reason darktable is a GUI application is that YOU are needed to look at the image and decide what editing needs applied.  I suppose if you were able to get every image correct in camera, then you could just upload them and apply an xmp file with the necessary editing steps to darktable-cli and get the exported images for your website.  You could automate that process and the only thing you would need darktable GUI for was to generate the xmp file.
* Using Lua to automate portions of the GUI has cut my processing time from minutes to seconds (and probably saved me from carpal tunnel).
* darktable does not expose a C API.  It was never meant to be called from an external program.
* darktable does expose a Lua API, https://docs.darktable.org/lua/stable/lua.api.manual/

**Comment by webysther** [comment]
> @webysther
> 
> * darktable-cli is not darktable GUI running headless.  darktable-cli is a wrapper around the export function.  It's used to export processed images.  It does not require database access unless you are applying a style to the exported images.  If you are then access to the data database is required to get the style settings.  https://docs.darktable.org/usermanual/4.6/en/special-topics/program-invocation/darktable-cli/
> * why are you focused on darktable-generate-cache?  The purpose of this program is to populate the cache for darktable GUI.  Are you wanting to use the cache images for another purpose?
> * The reason darktable is a GUI application is that YOU are needed to look at the image and decide what editing needs applied.  I suppose if you were able to get every image correct in camera, then you could just upload them and apply an xmp file with the necessary editing steps to darktable-cli and get the exported images for your website.  You could automate that process and the only thing you would need darktable GUI for was to generate the xmp file.
> * Using Lua to automate portions of the GUI has cut my processing time from minutes to seconds (and probably saved me from carpal tunnel).
> * darktable does not expose a C API.  It was never meant to be called from an external program.
> * darktable does expose a Lua API, https://docs.darktable.org/lua/stable/lua.api.manual/

@wpferguson Because with cache I can reduce the load of thumbs, sometimes the response time is too slow, I like to put the thumb size in the max (25) because I want to produce more timelapse.

After all my worfkflow is far hard to fix, look around I don't have much to do, and my backgraound as PHP developer with all automations you can do with imagemagick I imaged in my ignorance that RAW editing is good enough stable to have some sort of automation as imagemagick made with jpg/png/gif, my I'm wrong and to make this happen I need to work in the concept. I don't work so much in the images I too focused to make the good picture in the pre-processing, so I really want to create the automation with another steps, like:

- After simple shoot I will put in a folder in the NAS called 'Direct to commons' which will:

1) Apply the naming
2) Metadata about CC-BY-SA
3) Run a AI auto description
4) Add to a album in immich

Here is what I imagine do with Darktable
5) Read XMP already create in steps back
6) Copy to local
7) Create thumb cache
8) Apply deskew
9) Remove lens noise
10) Export to digikam folder
End darktable

11) Export do commons digikam
12) Remove local files from Darktable after 1 month

The main ideia is create a form ou a webhook with my params when I do the upload and create some sort of automation inside home assistant or n8n

I have lots of automation and I just want to create to this tasks, when a image has problems normally I can upload a new version but sometimes a few things is about 'timing' like the current war or another things, the picture is much better than the quality

I worked a few years ago to the biggest newspaper in Brazil and this kind of automation was the core, few problems with some tools was fixed if a VM with the gui open and a macro/plugin polling from a folder, 6 years later I imagine that was fixed (the problem normally in adobe too, like incopy/indesign/photoshop/lrc/acrobat)

**Comment by webysther** [comment]
I was able to doing part of this using the darktable linuxserver docker: https://docs.linuxserver.io/images/docker-darktable/
