### ISSUE TITLE
SQlite WAL support

### ISSUE THREAD

**Issue by webysther** [darktable-org/darktable#16255]
**Is your feature request related to a problem? Please describe.**
Running any CLI tools with gui.

- darkatble-cli and darktable-generate-cache
- headless automation (per collection/file basis)

**Describe the solution you'd like**
Supporting WAL on SQLite is a required step to moving to support simultaneously access to database without the need of lock for some operations.

**Comment by parafin** [comment]
I don’t think it’s a viable target to allow changes in database while dt is running. It’s not about any DB feature, but logic of the written code, which never took into account such possibility.

**Comment by webysther** [comment]
> I don’t think it’s a viable target to allow changes in database while dt is running. It’s not about any DB feature, but logic of the written code, which never took into account such possibility.

I believe it's advantageous to start considering this for the future as it can expand the scope with third-party solutions, such as agents for performing bulk processing.

The steps could be:

- Enable the WAL feature and;
- Leave a configuration to enable the feature with something alpha.
- Address the issues reported when running darktable tools simultaneously.
