### ISSUE TITLE
Crash on startup (Windows 11)

### ISSUE THREAD

**Issue by zipy124** [darktable-org/darktable#16264]
### Describe the bug

When launching, the app either crashes or seems to work for anythin from 0-10 seconds before crashing

### Steps to reproduce

Start darktable
it crashes

### Expected behavior

Darktable should not crash

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14185402/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home

### Describe your system?

i9-12900HK
3080Ti Laptop
32GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

3080Ti Laptop 16GB 31.0.15.4601

**Comment by gi-man** [comment]
I looked thru the log. There is a ton of information in it, so it is hard to find a problem, but I did find one. 

```
   123.1669 pixelpipe process CL       [full]           demosaic               (   0/   0) 6032x4012 scale=1.0000 --> (   0/   0) 1105x 735 scale=0.1832 IOP_CS_RAW -> IOP_CS_RGB
   123.1670 [opencl memory] device 0: 109796372 bytes (104.7 MB) in use
   123.1670 [opencl memory] device 0: 109796516 bytes (104.7 MB) in use
   123.1670 [opencl memory] device 0: 497002660 bytes (474.0 MB) in use
   123.1670 [opencl memory] device 0: 884208804 bytes (843.2 MB) in use
   123.1670 [opencl memory] device 0: 1271414948 bytes (1212.5 MB) in use
   123.1670 [opencl memory] device 0: 1658621092 bytes (1581.8 MB) in use
   123.1670 [opencl memory] device 0: 1852224164 bytes (1766.4 MB) in use
   123.1670 [opencl memory] device 0: 2239430308 bytes (2135.7 MB) in use
   123.1670 [opencl memory] device 0: 2626636452 bytes (2505.0 MB) in use
   123.1704 [dt_opencl_enqueue_kernel_2d] kernel 126 on device 0: CL_MEM_OBJECT_ALLOCATION_FAILURE
   123.1704 [opencl memory] device 0: 2239430308 bytes (2135.7 MB) in use
   123.1704 [opencl memory] device 0: 1852224164 bytes (1766.4 MB) in use
   123.1704 [opencl memory] device 0: 1465018020 bytes (1397.2 MB) in use
   123.1704 [opencl memory] device 0: 1077811876 bytes (1027.9 MB) in use
   123.1704 [opencl memory] device 0: 690605732 bytes (658.6 MB) in use
   123.1704 [opencl memory] device 0: 497002660 bytes (474.0 MB) in use
   123.1704 [opencl memory] device 0: 497002624 bytes (474.0 MB) in use
   123.1704 [opencl memory] device 0: 497002480 bytes (474.0 MB) in use
   123.1704 [opencl memory] device 0: 109796336 bytes (104.7 MB) in use
   123.1704 [opencl_demosaic] markesteijn problem 'CL_MEM_OBJECT_ALLOCATION_FAILURE'
   123.1704 Error: process_CL          [full]           demosaic               (   0/   0) 6032x4012 scale=1.0000 --> (   0/   0) 1105x 735 scale=0.1832 device=0 (nvidiacudanvidiageforcertx3080tilaptopgpu), CL_MEM_OBJECT_ALLOCATION_FAILURE
   123.1705 pixelpipe process CL       [full]           demosaic               (   0/   0) 6032x4012 scale=1.0000 --> (   0/   0) 1105x 735 scale=0.1832 couldn't run module on GPU, falling back to CPU
   123.1705 [opencl memory] device 0: 96801536 bytes (92.3 MB) in use
   123.2004 [opencl memory] device 0: 0 bytes (0.0 MB) in use
   123.2012 pixelpipe process CPU      [full]           demosaic               (   0/   0) 6032x4012 scale=1.0000 --> (   0/   0) 1105x 735 scale=0.1832 IOP_CS_RAW -> IOP_CS_RGB
Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...========================================
```
Can you clear the log file and use -d common instead? If you can find the image that cause this and share it with the xmp, then we might be able to troubleshoot it.

**Comment by kofa73** [comment]
CL_MEM_OBJECT_ALLOCATION_FAILURE - did you perhaps set darktable resources = unlimited, or enabled 'use all device memory'?

**Comment by zipy124** [comment]
> CL_MEM_OBJECT_ALLOCATION_FAILURE - did you perhaps set darktable resources = unlimited, or enabled 'use all device memory'?

I tried all resource settings, as I thought maybe that might help but it did not. This log is indeed from when resources is set to unlimited I believe.

**Comment by ralfbrown** [comment]
No further response from OP in over four months, and 4.8 is about to be released.

@zipy124, feel free to reopen if you have this problem with 4.8.

**Comment by zipy124** [comment]
> No further response from OP in over four months, and 4.8 is about to be released.
> 
> @zipy124, feel free to reopen if you have this problem with 4.8.

Apologies for the slow response, my life is hectic! I discovered the root cause in the end (i think). Since the photos are large, when ingested into windows the thumbnail service starts creating thumbnails. This is resource intesive enough that even on a machine with 20 cores, 32gb of ram and 2tb pcie 5 SSD that it causes windows to both hog the files, and crash explorer/windows amongst other-things. 

Therefore I believe it is just a windows issue (like always) and not an issue with darktable itself!
