### ISSUE TITLE
Canon Rebel XT displays Black border on the raw

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#16278]
### Describe the bug

All images from this camera are displayed with a black border that needs to be cropped.

### Steps to reproduce

1 Open raw file
2 black border is displayed

### Expected behavior

border should not show

### Logfile | Screenshot | Screencast

Raw file can be sent if needed.

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.7.0+502~g986da0340c

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro/Arch/XFCE

### Describe your system?

Linux 6.6.10-1
Nvidia -390xx
Mem 16 Gb.
GTK 1.2.10-18

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Nvidia -390xx

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

no

**Comment by kmilos** [comment]
Until this is analyzed, the correct workaround is not the crop module, but the raw crop option in the raw black/white point module.

It is a hidden option, you need to enable it first by switching `plugins/darkroom/rawprepare/allow_editing_crop=false` to `true` in your user `darktablerc`.

**Comment by davidvj** [comment]
Thank you ..... it works well
Problem solved
