### ISSUE TITLE
JXL export: libjxl call failed with err 1

### ISSUE THREAD

**Issue by RafaelLinux** [darktable-org/darktable#16273]
### Describe the bug

Trying to export to lossless JXL ends after a long time (about 35 minutes) with an error. I tried with distinct RAW files and it works when exporting to TIFF.

### Steps to reproduce

1. Select a RAW file
2. In "export", select JXL format and 100 quality
3. Click on "Export"

### Expected behavior

Create a JXL file after about 7 seconds

### Logfile | Screenshot | Screencast

[output.txt](https://github.com/darktable-org/darktable/files/14215447/output.txt)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed

### Describe your system?

Operating System: openSUSE Tumbleweed 20240202
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.2-1-default (64-bit)
Graphics Platform: Wayland
libjxl: 0.8.1-4.1

Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 7600
Product Name: B550M Phantom Gaming 4

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I can export to lossless JXL with GIMP, Krita, Digikam … however when I try to export to JXL (quality 100, so lossless) with Darktable, it remains exporting forever, but doing nothing about (Darktable is loaded and working, but not exporting). If I cancel export queue and close Darktable window, I can see Darktable loaded in memory thru “system activity” (Plasma, KDE).

**Comment by gi-man** [comment]
I'm going to continue the conversation from pixls.us here since I think it is more appropriate. I'm not sure about the error you had, but based on the reading at libjxl, when using lossless, effort values above 4 dont provide too much benefit. Increasing the effort does increase the amount of time to encode. The recommendation was to use 3.

Therefore I did some test. Using a RW2 image (similar to your 5200x3900), I looked at the timestamp from the end of pixelpipe to export complete

```
* e1 19.0320 - 18.1609 = 0.8711 seconds | 24MB
* e2 705.0124 - 704.0106 = 1.0018 seconds |22.5MB
* e3 158.8485 - 157.6353 = 1.2132 seconds | 19.8MB
* e5 299.7103 - 254.4952 = 45.2151 seconds |19.0MB
* e7 622.9569 - 490.2849 = 132.672 seconds | 18.7MB
* e9 2174.5955 - 941.1407 = 1233.4548 seconds | 18.4MB
* tif uncompressed 2520.4391 - 2519.6864 = 0.7527 seconds | 58.5MB
```

I opened each of the images to check them using gwenview. e1 and e2 open instantly. For the other there is a short delay (decoding).  They are lossless and of course I dont see a difference. The e1 was about the same as the original raw file size. Therefore the short testing corroborates the recommendation that we should default the effort to 3 when **quality = 100** for a better user experience. 

When exporting at e9, I had plenty of time to look at the processes (20min of waiting). At some points it looked like only one CPU core was used close to 100%, but then all cores were being used at around 15%. Total memory usage remained at 8Gb for my system (3.5gb for dartktable).

**Comment by ralfbrown** [comment]
With that kind of slowdown, it might also be worth _limiting_ effort to at most 7.  Or at least putting up a big flashing warning when selecting 7 or above....

**Comment by RafaelLinux** [comment]
> I'm going to continue the conversation from pixls.us here since I think it is more appropriate. I'm not sure about the error you had, but based on the reading at libjxl, when using lossless, effort values above 4 dont provide too much benefit. Increasing the effort does increase the amount of time to encode. The recommendation was to use 3.

I tried (I answered in Pixl.us) your advice about `effort` parameter, but in my case, seems not to be related. Anyway, your info let me notice I didn't include my system `libjxl` version.

Anyway, you have a detailed and interesting  explanation about `effort` parameter [here](https://www.reddit.com/r/jpegxl/comments/10157np/analysis_of_effort_settings/).

**Comment by gi-man** [comment]
For quality settings less than 100, therefore lossy compression, the recommendation is an effort of 7. From what I read, the effort helps avoiding artifacts. Lossy is the normal use case for jxl when exporting from a raw editor and you keep the original raw. I will test the effort settings later today using q=80.

While this is interesting, it still doesn't address the OP error. I looked into their documentation and API, but I can't find the meaning of error code 1. 

OP, what version is libjxl in your system?

**Comment by kmilos** [comment]
> OP, what version is libjxl in your system?

libhwy could also play a part in this, if using the system one that is...

**Comment by RafaelLinux** [comment]
> For quality settings less than 100, therefore lossy compression, the recommendation is an effort of 7. From what I read, the effort helps avoiding artifacts. Lossy is the normal use case for jxl when exporting from a raw editor and you keep the original raw. I will test the effort settings later today using q=80.

I would love to be able to use RAW files as a source and perform non-destructive operations on them in a workflow or ecosystem such as Adobe's. But on Linux, unfortunately, we don't have that. Therefore, from a photo manager like Digikam/ShowFoto/Krita/GIMP I can't see in the thumbnails the filters applied by Darktable. Therefore, to follow my usual workflow (e.g. blending images, applying brushes, etc) I need a pre-processed file to work on losslessly, which until now, was TIFF. However, the appearance of JXL and its impressive native lossless and lossy capabilities make it clear to me that it is the format to work on once I'm done with what Darktable offers (which is no small feat). The release version (when all browsers adopt JXL) will be lossy. But it's a matter of opinion.

> 
> While this is interesting, it still doesn't address the OP error. I looked into their documentation and API, but I can't find the meaning of error code 1.
> 
> OP, what version is libjxl in your system?
I'm sorry. I forgot to put in my first post (I'll update it now) 0.8.1-4.1

**Comment by kmilos** [comment]
Unfortunately "err 1" does not give a useful hint:

https://github.com/libjxl/libjxl/blob/v0.9.2/lib/include/jxl/encode.h#L87-L89

Does this happen with the nightly AppImage?

**Comment by RafaelLinux** [comment]
> > OP, what version is libjxl in your system?
> 
> libhwy could also play a part in this, if using the system one that is...

1.0.7-1.2 in my case.

**Comment by kmilos** [comment]
Also, does the error happen if you disable metadata in the export preferences?

**Comment by RafaelLinux** [comment]
> Also, does the error happen if you disable metadata in the export preferences?

I'll try at night too, before trying AppImage. 
Anyway, I suppose that all the other applications I have mentioned will also use this library to export, and they have not given me any problems, although it is true that in these cases I have not started from a RAW file, but from a TIFF file, which have practically the same metadata (although not the same amount of information).

**Comment by gi-man** [comment]
Another test to try in 6 hours:

Q 100, E1 and
Q80, E1 

On Krita, what are your export settings?

**Comment by RafaelLinux** [comment]
> On Krita, what are your export settings?

- Save as JPEG-XL checked
- Lossless codification
- Compensation: 7 (default)
- Transcoding speed: 0 (default)

**Comment by gi-man** [comment]
Just for curiosity, using the same image and full scale, but quality = 80

```
* e1 25.6337 - 25.2424 = 0.3913 | 1.0MB
* e3 35.1569 - 34.767 = 0.3899 | 937kb
* e7 46.5521 - 43.6494 = 2.9027 | 912kb
* e9 99.1974 - 52.7649 = 46.4325 | 841.3kb
* jpg q=80, chroma=auto 197.1039 - 196.7244 = 0.3795 | 1.7MB
```
Size differences are from lossless are significant. Compared with jpg is also almost half the size. e3 compares to the same encoding speed as jpg. Comparing e1, e3, e9, I cant see a difference at 400%. I might see some minor differences at 800% zoom. More research would be needed, but I would not mind using e3 for lossy too when going from this size raw image. If only the format had more supporting system.

**Comment by RafaelLinux** [comment]
> Also, does the error happen if you disable metadata in the export preferences?

I don't know how to avoid metadata export. Doesn't find an option about that in export settings.

**Comment by RafaelLinux** [comment]
> Does this happen with the nightly AppImage?

It doesn't seems to exist an AppImage in Darktable homepage.

**Comment by gi-man** [comment]
In the export module, click on the hamburger menu and you will get to the export preferences.

The app image is here on GitHub as part of the nightly ci runs. It is the current version of the master branch (includes all bug fixes plus new development features).

**Comment by RafaelLinux** [comment]
> In the export module, click on the hamburger menu and you will get to the export preferences.

It seems no metadata is exported by default:
![imagen](https://github.com/darktable-org/darktable/assets/13048959/90223bcf-2998-43b8-b106-588549179b93)

> 
> The app image is here on GitHub as part of the nightly ci runs. It is the current version of the master branch (includes all bug fixes plus new development features).

Unfortunately, same behaviour :(

This is one of the files Darktable fails to export to JXL 
https://www.transfernow.net/dl/202402107TQuhCFm

**Comment by gi-man** [comment]
I was able to process your image without problem, but you never posted the xmp. 

Did you try with q=80 e1?

**Comment by RafaelLinux** [comment]
First, I must say that after using the AppImage, I can't not use my distro Darktable version, cause database is altered and can't be read by previous versions.

>Did you try with q=80 e1?

I tried that config to export JXL, and no issues!!!. I tried a lot of combinations and finally I found out that error is related to lossless quality. Any effort value (even max) works, but if quality value is 100 (lossless) always fails to export (mentioned error). I don't know why this happens, **only with Darktable and only with lossless quality**.

**Comment by gi-man** [comment]
Can you share your xmp? What the `profile` for export? sRGB? What's the `intent` for export?

And yes we know that it is only happening in dt with lossless. But I cant reproduce it...

**Comment by RafaelLinux** [comment]
>Can you share your xmp? 

Renamed to TXT, to get to upload to GitHub
[_1020827.RW2.xmp.txt](https://github.com/darktable-org/darktable/files/14232328/_1020827.RW2.xmp.txt)

>What the profile for export? sRGB? What's the intent for export?

Not sure about "intent" (maybe a translation issue), so this is the screenshot of "export" tab:
![imagen](https://github.com/darktable-org/darktable/assets/13048959/9f0c52cc-b530-4364-9e90-e280ed42794d)

>And yes we know that it is only happening in dt with lossless.

I didn't know only happens with lossless till yesterday. Never tried in lossy with Darktable, cause I don't want a lossy version  ;)

**Comment by gi-man** [comment]
Ok. Thanks for the xmp and the screenshot. The screenshot shows that you are using 16bit. Using the 16 and the unsigned integer; it takes a long time and generates a 99MB file. Using 16bit floating point does work and it is very fast at e1 for me (28.1MB). 

Can you try 16bit and float?

**Comment by RafaelLinux** [comment]
Again, you got it right. Using lossless compression, with maximum effort and floating point, it manages to export without problems. So, the problem is related to the whole pixel type, I don't know if it's the way Darktable handles it or if it's the library itself.

In view of the results it is worth using JXL as a lossless storage format. TIFF with lossless deflate takes 107M, while JXL takes 51M, almost half the size.

**Comment by gi-man** [comment]
I started to read thru our code and the libjxl api. There is some selection we do to set basicinfo that I'm not clear. There is also JxlEncoderSetFrameLossless feature that we should enable when q=100 to avoid issues since 0.7.0 version.

**Comment by RafaelLinux** [comment]
Thank you. I wish you get to fix it soon. Meanwhile, I'll use the AppImage version till my distro compiles official version.

**Comment by gi-man** [comment]
I read some more information online and added this JxlEncoderSetCodestreamLevel to 10 in a local branch. I dont notice a difference. 

As a test I used other images I had from PlayRaw. Images larger than yours (yields 150MB) and other RW2 are all instant. Your image is the only one that takes a long time.

**Comment by RafaelLinux** [comment]
> I read some more information online and added this JxlEncoderSetCodestreamLevel to 10 in a local branch. I dont notice a difference.

I read this, maybe related with the error showed: _"The default value is 5. To use level 10 features, the setting must be explicitly set to 10, the encoder will not automatically enable it. If incompatible parameters such as too high image resolution for the current level are set, the encoder will return an error."_

> As a test I used other images I had from PlayRaw. Images larger than yours (yields 150MB) and other RW2 are all instant. Your image is the only one that takes a long time.

Error happens with all my RAW files (from my Lumix). Maybe is a Lumix RAW native format complexity

**Comment by gi-man** [comment]
I think I have root cause. Your raw image metadata have:

`[ExifIFD]       Color Space                     : Uncalibrated`

I took images from raw.pixls.us from your same camera(DMC-GX8) and those processed instantly in lossless mode uint16. I then did a diff between the two files metadata. The main difference was Color Space is set as sRGB for the raw.pixls.us. 

I then took your image and edited the metadata via `exiftool -ExifIFD:ColorSpace="sRGB" .` Removed it from darktable, deleted the xmp and added to the library again. I then encoded it and it was instant.

Do you have control of the color space in your camera settings?

**Comment by RafaelLinux** [comment]
Usually, I put my camera color space to AdobeRGB, cause I do large photo prints and as you know, AdobeRGB spectrum is wider. Then, in Darktable export to sRGB when I'll use images for web.

**Comment by RafaelLinux** [comment]
> is not useful

I imagine, because you don't specify it, that you mean that if I only take pictures in RAW, the colour space is indifferent, as it is not taken into account. However, if I take pictures in RAW + JPG (which is what I usually do to be able to manage them immediately), the chosen colour space is important. In fact, my monitors are calibrated for AdobeRGB, so it is quicker for me to discard or accept the photos from the JPG with the AdobeRGB profile because I know that I will be seeing the exact colours on my monitor. It is when I am going to send the photo, after editing, that I choose CMYK or sRGB as the colour space.

**Comment by RafaelLinux** [comment]
Please, after testing with the AppImage version you asked me to test, the database is not the same and I still have to launch the AppImage version. With which version of Darktable from my distribution's repositories will I be able to use Darktable normally?

Thanks

**Comment by RafaelLinux** [comment]
I can't reproduce this issue in latest stable releases of DT, so I close it. Thanks again
