### ISSUE TITLE
Regression on integration test 094 after ashot to later D65

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#16280]
The PR #15602 did introduce a regression on this test.

The diff:

![image](https://github.com/darktable-org/darktable/assets/467069/068127d5-5ae2-4fd3-9585-8314ed1da886)

The expected output:

![image](https://github.com/darktable-org/darktable/assets/467069/2292095d-eeb6-4cbb-8480-7c8c6a13124a)

The new output:

![image](https://github.com/darktable-org/darktable/assets/467069/69e6616d-fe5c-4b28-89de-818ff8ad33a8)

See the green part in the skip, less redish seems good but it doesn't cover all the area...

So maybe we need:
- to update the integration test 
- fix segmentation based parameters to cope with PR

EDIT: The test is:

```
Test 0094-highlight-segmentation
      Image hlrecovery.arw
      Expected CPU vs. current CPU report :
      ----------------------------------
      Max dE                   : 8.59993
      Avg dE                   : 1.45689
      Std dE                   : 2.78868
      ----------------------------------
      Pixels below avg + 0 std : 78.43 %
      Pixels below avg + 1 std : 78.72 %
      Pixels below avg + 3 std : 100.00 %
      Pixels below avg + 6 std : 100.00 %
      Pixels below avg + 9 std : 100.00 %
      ----------------------------------
      Pixels above tolerance   : 21.49 %
 
  FAILS: image visually changed
```

**Comment by jenshannoschwalm** [comment]
> The PR #15602 did introduce a regression on this test.
> 
> The diff:
> 
> ![image](https://private-user-images.githubusercontent.com/467069/303823206-068127d5-5ae2-4fd3-9585-8314ed1da886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIwOTgsIm5iZiI6MTcwNzU1MTc5OCwicGF0aCI6Ii80NjcwNjkvMzAzODIzMjA2LTA2ODEyN2Q1LTVhZTItNGZkMy05NTg1LTgzMTRlZDFkYTg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNzU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzkxMTI1ZGExMjRhYTU2YWI1OThhOGM2MTUyMzM2YTA3Mjk4YWRhMmUyODVhZmY5NjQxY2FlMGE5MzRlM2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dez2fZACInYsKk-1tIwwRmcNlQqCAdoznGxw8EZPfoA)
> 
> The expected output:
> 
> ![image](https://private-user-images.githubusercontent.com/467069/303823215-2292095d-eeb6-4cbb-8480-7c8c6a13124a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIwOTgsIm5iZiI6MTcwNzU1MTc5OCwicGF0aCI6Ii80NjcwNjkvMzAzODIzMjE1LTIyOTIwOTVkLWVlYjYtNGNiYi04NDgwLTdjOGM2YTEzMTI0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNzU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDI4YTY1MzZhM2UxZDFmNzY2N2I3MDkzN2M5YjZkNjliMjJiNTU2Zjc1ZWVhZGI5Y2Y3YTg4OTkxOTJiNmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W9LWsuw5Bh9attP24fofJepxk3MRTPKS4Ml79nEA92E)
> 
> The new output:
> 
> ![image](https://private-user-images.githubusercontent.com/467069/303823232-69e6616d-fe5c-4b28-89de-818ff8ad33a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTIwOTgsIm5iZiI6MTcwNzU1MTc5OCwicGF0aCI6Ii80NjcwNjkvMzAzODIzMjMyLTY5ZTY2MTZkLWZlNWMtNGIyOC04OWRlLTgxOGZmOGFkMzNhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNzU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NThlNWUzYWE1MTNhODM0ZTQ0OWU3MzUyZTI1YTUzYTI0ZDIzMDUzZTdiNDA1YzNmNjc1ODg2ZjMyMzk0ODNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5oWvPuMnAsPPMUxJEt0Iv1pn_O3_VhU8Xy1IPVCkxD8)
> 
> See the green part in the skip, less redish seems good but it doesn't cover all the area...
> 
> So maybe we need:
> 
>     * to update the integration test
> 
>     * fix segmentation based parameters to cope with PR

I will check if there is a missing part in correction in segmentation stuff ...

**Comment by jenshannoschwalm** [comment]
> A side question, is it expected that almost all tests are slightly changed in the regression testsuite? I mean the new mode is the default but not for old edits, right? For example for recent test Test 0158-coloreq-no-guided-filter we had yesterday:

I think we both agree on this shouldn't be the case :-) (Old edits should have the same output...)
