### ISSUE TITLE
OM SYSTEM OM1 Mark II

### ISSUE THREAD

**Issue by philippeg2** [darktable-org/darktable#16297]
I have no sample yes because i did not buy the yet but raw can find here

https://www.dpreview.com/sample-galleries/0739659306/om-system-om-1-sample-gallery

**Comment by kmilos** [comment]
We’ll need the CC0 contributed samples first I’m afraid.

**Comment by mguzmann** [comment]
I'll get this camera in a couple of days, I'll be happy to provide some raw files. Could you maybe tell me in more detail what sorts of raw files you'd need, how should they be shot?

**Comment by kmilos** [comment]
> Could you maybe tell me in more detail what sorts of raw files you'd need, how should they be shot?

https://raw.pixls.us/
https://github.com/darktable-org/darktable/wiki/Camera-support
https://discuss.pixls.us/t/raw-samples-wanted/5420

Thanks

**Comment by krid** [comment]
I just uploaded nine RAW samples from my day-old OM-1 MkII to https://raw.pixls.us/.  They're pictures of my back yard: f8, 25mm, mix of sun & shade, lots of branches.  I believe I covered all the permunations & combitations of resolution & bit-depth.

They don't show up in the repository list yet, but I assume that's because they need some vetting/processing.  Please let me know if they're sufficient/useful.

**Comment by LebedevRI** [comment]
@krid thank you for the contribution! verified all 9 samples...

**Comment by krid** [comment]
I will try to muster up the patience to do the WB, noise, and basecurve shoots. maybe when it's raining this weekend.  I don't have a proper color chart so I'll pass on the profiling part.

**Comment by kmilos** [comment]
Those are new modes I guess, AFAIK the original OM-1 didn't do 14b...

**Comment by krid** [comment]
What do you mean by "don't successfully decode"?  Like the files are borked and I should shoot new ones, or there's something wrong on the rawspeed/darktable end?

**Comment by LebedevRI** [comment]
> Those are new modes I guess, AFAIK the original OM-1 didn't do 14b...

I mean, i'm surprised that out of four samples that are 14-bit, only these two don't work.



> What do you mean by "don't successfully decode"? Like the files are borked and I should shoot new ones, or there's something wrong on the rawspeed/darktable end?

I don't know yet.

**Comment by kmilos** [comment]
> I mean, i'm surprised that out of four samples that are 14-bit, only these two don't work.

I would think the "14b" ORIs matching those are still 12b.

**Comment by krid** [comment]
Last night I manually made the edits for #677 to my `cameras.xml`, but for some reason the test shot I used came up solid black.  I tried it this morning with the back-yard shots and those (well, the 12 bit ones) work fine.  I ran the three ORF files through and now I've got three perfectly boring JPGs of my back yard.
A 14 bit shot gives me the big white skull, but I can live w/o those for now.
Looks like the answer to the "how soon will Darktable support my camera" question is "Now!".

**Comment by krid** [comment]
Let me know if you need more 14 bit samples.  I can do those along with the WB and noise shots.  Heck, I can do 14 bit noise samples if you want (though that probably doesn't make sense).

**Comment by LebedevRI** [comment]
Ok, got a heuristic to explicitly bail on those, will merge that PR soon(TM).

**Comment by LebedevRI** [comment]
Ok, if you can build dt locally, update git rawspeed submodule to use develop branch, and it'll work.

> for some reason the test shot I used came up solid black

There's some race conditions in dt, that is one of the symptoms.

**Comment by krid** [comment]
> Ok, if you can build dt locally, update git rawspeed submodule to use develop branch, and it'll work.

Never tried building Darktable, but how hard can it be?  Looks like my rainy weekend is going to be busy with Darktable stuff...

**Comment by kmilos** [comment]
> > I mean, i'm surprised that out of four samples that are 14-bit, only these two don't work.
> 
> I would think the "14b" ORIs matching those are still 12b.

Yep, found this in the exiftool output for all ORIs:
```
[Olympus]       ValidBits                       : 12 0
```
Makes sense, as this is the native sensor format for a single frame, the others are a result of combining multiple ones.

**Comment by mlouielu** [comment]
Hi all, I tried it today and it works with rawspeed/develop for 12-bits photos. But how can I modify or update the code for lens corrections and denoise (profile)? Can you point me out what should I do? Thanks!

**Comment by kmilos** [comment]
@mlouielu See https://github.com/darktable-org/darktable/wiki/Camera-support

**Comment by mlouielu** [comment]
> @mlouielu See https://github.com/darktable-org/darktable/wiki/Camera-support

For noise profile, if I have a OLED screen, can I just put the gradient on the screen with black background? Since the black on OLED is black without backlight.

**Comment by kmilos** [comment]
> For noise profile, if I have a OLED screen, can I just put the gradient on the screen with black background? Since the black on OLED is black without backlight.

[I think not a problem](https://discuss.pixls.us/t/how-to-create-camera-noise-profiles-for-darktable/7428/51), the whole point is to get enough pixels throughout the whole range. @rawfiner For any further questions, please follow up on the article discussion directly.

**Comment by krid** [comment]
What is the status of 14-bit support?  Looks like it's [still excluded](https://github.com/darktable-org/rawspeed/blob/6364c6a94178868b7cc41b77edac421589514371/src/librawspeed/decoders/OrfDecoder.cpp#L147).  Should I file a separate bug for that?

**Comment by kmilos** [comment]
> Should I file a separate bug for that?

It's already tracked: https://github.com/darktable-org/rawspeed/issues/686
