### ISSUE TITLE
Import: Subfolders are ignored

### ISSUE THREAD

**Issue by outdoorbits** [darktable-org/darktable#16294]
### Describe the bug

raw images are not imported from subfolder.

### Steps to reproduce

My images are in a folder tree ordered by date. Every day has a subfolder called NEF containing my raw images.
If I try to add to library such a day folder, I check "select only new pictures", recursive directory" and uncheck "ignore non-raw images". The import list shows all my jpg and nef files, both are marked for import. But only the jpg files will be imported. Starting import again, all the nef are marked for import again, while the jpg are not, as they are imported already. I get a message like "47 images imported", but the nef are still missing.
If I select the NEF folder directly, the images will be imported.

### Expected behavior

darktable should import all the images, trom subfolders too.

### Logfile | Screenshot | Screencast

![Screenshot_20240211_113137](https://github.com/darktable-org/darktable/assets/45213053/67123288-1dbc-4a31-9268-d12d03c66bbe)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0-1.1+72.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS

### Describe your system?

Package from http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04

### Are you using OpenCL GPU in darktable?

Yes

**Comment by zisoft** [comment]
This is a known issue and already fixed in master.
Will come in 4.6.1.
