### ISSUE TITLE
darktable fails when the parametric masks details threshold slider takes a value other than 0

### ISSUE THREAD

**Issue by Fernando-Llavador** [darktable-org/darktable#16313]
### Describe the bug

If OpenCl is enabled, darktable fails when the parametric masks details threshold slider takes a value other than 0

### Steps to reproduce

1. Open image (CR2)
2. Open exposure module (or diffuse/sharp) and move the detail threshold slider
3. After trying to process the image, darktable closes and it is no longer possible to open that image without the program closing (unless openCL is disabled)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0 

### What OS are you using?

Windows

### What is the version of your OS?

10 Home 64 bits

### Describe your system?

Operating System: Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Manufacturer: Gigabyte Technology Co., Ltd.
System Model: To be filled by O.E.M.
BIOS: BIOS Date: 03/16/16 14:15:09 Ver: 05.0000B (type: BIOS)
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 CPUs), ~2.7GHz
Memory: 16384MB RAM
Available OS Memory: 16336MB RAM
Page File: 7666MB used, 22413MB available
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
DX Setup Parameters: Not found
User DPI Setting: 96 DPI (100 percent)
System DPI Setting: 96 DPI (100 percent)
DWM DPI Scaling: Disabled
Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
DirectX Database Version: 1.0.8
DxDiag Version: 10.00.19041.3636 64bit Unicode

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GT 103

**Comment by gi-man** [comment]
We will need a logfile to help troubleshoot, but must likely it is this bug that is already fixed on master. You should see it on 4.6.1 soon. https://github.com/darktable-org/darktable/issues/15999

**Comment by Fernando-Llavador** [comment]
Sorry, but invoking with   darktable -d pipe -d opencl   does not generate any .log file in   \AppData\Local\Temp
The error may be the same as #15999

**Comment by victoryforce** [comment]
> Sorry, but invoking with darktable -d pipe -d opencl does not generate any .log file in \AppData\Local\Temp

It should not be in the folder you specified. Run `darktable --help` and at the end of the output you will see the location of the log file.

On Windows 10/11 it is `C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt`

**Comment by Fernando-Llavador** [comment]
I'm sorry, I did not know. This is the darktable-log.txt file:

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14269588/darktable-log.txt)

Thank you so much.

**Comment by gi-man** [comment]
Can you do the `-d common` instead? the -d pipe and -d opencl did not show too much information.

**Comment by Fernando-Llavador** [comment]
Ok.

**Comment by Fernando-Llavador** [comment]
Here is the required information:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/14271291/darktable-log.txt)

**Comment by gi-man** [comment]
Same problem as the other Issue and should be fixed with https://github.com/darktable-org/darktable/pull/16003
