### ISSUE TITLE
Multiple export fails

### ISSUE THREAD

**Issue by Fernando-Llavador** [darktable-org/darktable#16314]
### Describe the bug

If openCl is enabled, when selecting in Lighttable to export more than two images, darktable crash after the second export, but if openCL is disabled the export works fine.

### Steps to reproduce

1. Select more than 2 images (CR2)
2. Export to disk as JPEG8

### Expected behavior

Export all selected images

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14270563/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Home 64 bits

### Describe your system?

Operating System: Windows 10 Home 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Manufacturer: Gigabyte Technology Co., Ltd.
System Model: To be filled by O.E.M.
BIOS: BIOS Date: 03/16/16 14:15:09 Ver: 05.0000B (type: BIOS)
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 CPUs), ~2.7GHz
Memory: 16384MB RAM
Available OS Memory: 16336MB RAM
Page File: 7666MB used, 22413MB available
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
DX Setup Parameters: Not found
User DPI Setting: 96 DPI (100 percent)
System DPI Setting: 96 DPI (100 percent)
DWM DPI Scaling: Disabled
Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
DirectX Database Version: 1.0.8
DxDiag Version: 10.00.19041.3636 64bit Unicode

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GT 1030

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

NVIDIA GeForce GT 1030     
   Display Memory: 10149 MB
   Dedicated Memory: 1981 MB
   Shared Memory: 8168 MB

**Comment by gi-man** [comment]
There was no need to close the other Issue and open a new one. 

This looks like the problem that was fixed with https://github.com/darktable-org/darktable/pull/16003 You should see the fix in 4.6.1 when it is released soon.
