### ISSUE TITLE
Darktable won't open on Mac OS

### ISSUE THREAD

**Issue by git-fabus** [darktable-org/darktable#16328]
### Describe the bug

I shutdown my Mac, while Darktable was open. Since then if I try to open it, nothing happens or I get an error report from my Mac. 
I also tried reinstalling Darktable, but nothing helped. 

### Steps to reproduce

1. Open Darktable
2. Shutdown Mac
3. try reopen darktable

### Expected behavior

darktable should just open normally

### Logfile | Screenshot | Screencast

```Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1003]

VM Region Info: 0 is not in any region.  Bytes before following region: 4377231360
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104e74000-104e84000    [   64K] r-x/r-x SM=COW  ...cOS/darktable
```

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable-4.6.0-arm64

### What OS are you using?

Mac

### What is the version of your OS?

Sonoma 14.3.1

### Describe your system?

Just a Basic Mac Studio with an M1 and 32GB RAM.

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I also updated MacOS to the newest Version, which didn't help

**Comment by zisoft** [comment]
I assume that your database files got corrupted due to the system shutdown while darktable was open.

The files are located in `~/.config/darktable`.
darktable makes backup snapshots of the database files regularly.

Try to rename the most recent snapshot files:

`data.db-snp-<datetime>` --> `data.db`
`library.db-snp-<datetime>` --> `library.db`

Then try again to open darktable.

**Comment by git-fabus** [comment]
That's a good idea, but apparently it didn't help. The shutdown happened yesterday and I took a snapshot from February 11.
Thanks for the quick reply

**Comment by git-fabus** [comment]
Yeah, the `darktablerc` file was the problem. Database wasn't the problem

thanks!

**Comment by Parpak02** [comment]
Hi man! It seems I have the same problem. Can you help me doing this steps? I don't know how to do them
