### ISSUE TITLE
Camera filter uses exact match in collection but contains in lightable grid

### ISSUE THREAD

**Issue by brianodwyer** [darktable-org/darktable#16336]
### Describe the bug

Hi,

I have taken images with a Leica M10 and an M10-D. 

The number in parentheses after the camera name is correct for each camera in the collection panel but over on the right, the count when I select the M10 is the count of the M10 and M10-D images but when I select the M10-D, the count is only of that camera.

I have the same issue with lens Summilux 1:1.4 35mm and Summilux 1:1.4 35mm ASPH as the first label is contained within the second.

Is there a setting I am missing here?

I've tried using exiftool to add -OG to the M10 but it updates the M10-D tags too (like it is using 'contains' and not =.

Thanks,
Brian.

### Steps to reproduce

Select Camera from the collections drop-down and view the count for each camera then click on each and see the number of filtered images on the lighttable is different for the one with the shorted name.

### Expected behavior

the filter should use exact match or offer a switch

### Commit

This happens in all versions including the bang up to date nightly build

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

ALL

### What OS are you using?

Mac

### What is the version of your OS?

macOS Monterey 12.7

### Describe your system?

I don't think any information will be relevant for this issue.

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
Try Shfit-Click on the camera model instead of plain click.  There's clearly a wildcard being added to the SQL query, and using Shift-Click for folders omits the wildcard; that may work for camera model as well.
https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/shared/collections/

**Comment by MStraeten** [comment]
related to #16034

**Comment by brianodwyer** [comment]
Thank you both for the information.
Shift-Click does not improve the results I'm afraid. I can see from trawling thru the linked info that LIKE is used in the SQL query and as a SQL developer, I would expect the same results using LIKE.
I shall go back to exiftool and see if I can get that to work in testing a tag for an absolute value.

**Comment by brianodwyer** [comment]
thanks very much for the fix and update 👍🏻On 22 Mar 2024, at 16:09, Pascal Obry ***@***.***> wrote:﻿
Closed #16336 as completed via #16500.
