### ISSUE TITLE
Olympus OM-D EM-5 purple lights

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#16345]
### Describe the bug

if you open this photo in darktable, the lights are purple 
https://germano.fedorapeople.org/canc/ark/41LT2662.ORF
it is a bug of libraw/rawspeed? This is how it should look like 
https://germano.fedorapeople.org/canc/ark/41LT2662.JPG

### Steps to reproduce

Just open the RAW image in darktable

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 39

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment]
works as designed - you need to take care of clipped highlights in the pipeline.
have a look at https://docs.darktable.org/usermanual/development/en/module-reference/processing-modules/highlight-reconstruction/#clipping
