### ISSUE TITLE
Different Delta E computation results

### ISSUE THREAD

**Issue by crazydiamondaz** [darktable-org/darktable#16351]
### Describe the bug

I use the calibrate with a color checker in CAT in color calibration as pic below:
![image](https://github.com/darktable-org/darktable/assets/46803604/3106978d-ef44-4e9a-9f66-bdab1601aa1e)
It turns out the output ΔE in the first button as pic below:
![image](https://github.com/darktable-org/darktable/assets/46803604/f9881956-4180-47ed-ab4f-6c626a0de7ee)
and the output ΔE in the second button as pic below:
![image](https://github.com/darktable-org/darktable/assets/46803604/2dbdcc1e-c053-4737-9434-56182c1cd803)
are different.
Is there any problem? Or please tell me why. 
Thanks for your hard and great work!

### Steps to reproduce

1.open darkroom
2.open color calibation
3.open CAT
4.go calibrate with a color chekcer
5.You can see the different ΔE in the same picture

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 pro

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment]
what's the issue?
one is the initial state, the other after calculation the correction matrix

**Comment by crazydiamondaz** [comment]
> what's the issue? one is the initial state, the other after calculation the correction matrix

Thanks for your reply. 
I mean the ΔE in the initial state should be same as the input ΔE in the other and the output ΔE should be the ΔE  after calculation.
I 've circled the ΔE i think should be the same as below:

![image](https://github.com/darktable-org/darktable/assets/46803604/c44857db-5f14-404f-9869-b16eef4f2213)
![image](https://github.com/darktable-org/darktable/assets/46803604/b8498543-2a55-4c2d-a4bd-d3b12ce299ee)
There should only be two different ΔE（one is the initial state, the other after calculation the correction matrix）. However, there are three different ΔE. What's the different meanings of these three different ΔE？Thanks for your patience again.

**Comment by MStraeten** [comment]
have a look at https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/color-calibration/#reading-the-profile-report
for discussions or explanations better post at https://discuss.pixls.us/c/software/darktable/19 
not in an issue tracker ;)
