### ISSUE TITLE
Fatal error in build of dt 4.6.1

### ISSUE THREAD

**Issue by LateJunction** [darktable-org/darktable#16356]
### Describe the bug

The last part of the build process (from 95%) produces a fatal error: "no matching function for call to ‘lfModifier::lfModifier(lfLens* const&, const float&, const int&, const int&)’. The error message further data appears to be pointing out a defect in the source code; See the attached screen shot of the terminal output.
![DT build fatal 2024-02-19_20-46](https://github.com/darktable-org/darktable/assets/78297934/3d039d46-88eb-46ac-b855-a740b58d5ddf)

### Steps to reproduce

Follow the process in the README document, Building Section, for the darktable project in git hub. The fatal error occurs when running the build command: "./build.sh --prefix /opt/darktable --build-type Release --install --sudo"

### Expected behavior

dt compile without error when the process described in the README is being followed precisely.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1 stable

### What OS are you using?

Linux

### What is the version of your OS?

Mint 21.3

### Describe your system?

Mainstream MSI MAG based motherboard with 11th Gen Intel© Core™ i5-11600 @ 2.80GHz, 32 GB RAM, nVidia RTX3060 GPU, multiple M.2, NVME, SATA SSD and HDDs installed; X11 display server

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GeForce RTX 3060 Lite Hash Rate]

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The rebuild has been repeated 8 times now, with deletions (sudo rm -R) of the darktable and /opt/darktable folders after each failure. Lensfun versions 0.3.95 and 0.3.0 have been removed; the current version is at 0.3.2-6 for all parts of lensfun

**Comment by kmilos** [comment]
Already supported via https://discuss.pixls.us/t/fatal-error-in-build-of-4-6-1-i-dont-understand-how-to-fix/42180

**Comment by LateJunction** [comment]
"Please use GitHub only for real, reproducible issues with the darktable code."

OK, understood the distinction between build and execute.. How do I go about closing this report ?
