### ISSUE TITLE
Panasonic DC-TZ95D raw files unreadable by darktable 4.0 (2024-02-19)

### ISSUE THREAD

**Issue by CavBird24** [darktable-org/darktable#16353]
I am only a very recent downloader of darktable (same day as this Issue post).

After selecting the Panasonic raw files in the 'lighttable' panel I proceeded to move to the 'darkroom' panel where I was met with the brief text warning that my travel camera's Panasonic colour matrix was not readable by the software and darktable moved me back to 'lighttable'.

Not really the start I was looking for. _c'est la vie_

The **TZ-95D** (**ZS-80** in other markets) is the last of Panasonic's travel zoom cameras to be released. I bought mine in the middle of 2023.

The TZ-95 uses the **Venus XI (2019)** Engine, if that is of any help.

My computer is running Microsoft Windows 10 Home, version 10.0.19045 Build 19045
and I have never used a command line.

Thank you.

**Comment by CavBird24** [comment]
@LebedevRI  the RW2 raw file has just been uploaded.

Thank you

**Comment by LebedevRI** [comment]
@CavBird24 thank you for contributing the sample!
The support was just added in https://github.com/darktable-org/rawspeed/pull/673,
so it will be supported in dt master soon^TM.
(if you can edit `cameras.xml` in your dt install, apply that diff manually, and it should just work for now)

**Comment by CavBird24** [comment]
@LebedevRI sorry, I wouldn't have the first idea as how to do that, but thank you for letting me know.

**Comment by CavBird24** [comment]
@LebedevRI  I can at least say that I've found the **camera.xml** file, but that still leaves me clueless as to what to do next.

In **Win10** it can be opened in default **Notepad** or **WordPad**

**Comment by kmilos** [comment]
> what to do next

Just make a change in it like this (leading "+" means "add line", not a literal symbol to add):

https://github.com/darktable-org/rawspeed/pull/673/files

**Comment by CavBird24** [comment]
@kmilos  _SUCCESS!_ Thank you.

I nearly pulled my hair out update/replacing the **.xml** but I can happily report that the **DC TZ-95D RW2** raw files are being read by **darktable** _without_ complaint.

Thank you both. @LebedevRI

**Comment by CavBird24** [comment]
![DC_TZ-95D_darktable-raw-error_screenshot_2024-02-20](https://github.com/darktable-org/darktable/assets/160484781/433c8078-c2e8-484f-a9c6-1a277420d631)

Screenshot from within the **darkroom** panel

**Comment by kmilos** [comment]
> Is there some setting within the **darktable** menus that I need to change?

You need to remove all the files previously imported (just select and delete in lightroom, they will remain on disk), then remove the .xmp sidecars on disk next to your raw files, then import again.

**Comment by CavBird24** [comment]
@kmilos will do

**Comment by CavBird24** [comment]
@kmilos Back on track, thank you.
