### ISSUE TITLE
Could we include the details threshold slider for editing non-raw images

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#16364]
One of the beautiful features of DT is the ability to apply sharpening and denoising using the details threshold slider to achieve the sharpest possible image with the least noise. This feature is currently limited to RAW files and DNG files. However, there are times when I am working with Tiff files and the lack of the details threshold slider in modules such as diffuse or sharpen compromise my edits. This is because global adjustments are sharpening noise and making it really obvious and when I denoise I cannot protect the details from the softening effect of noise reduction. I presume there is no technical reason that this slider is limited to Raw files only.

**Comment by ralfbrown** [comment]
If there were no technical reason, it would already be available for all types of images.  The technical reason is that the data for the details mask is taken from either the demosaicer (color images) or `rawprepare` (monochrome), so it's only available for RAW and *un*demosaiced DNGs.  See src/develop/masks/detail.c for detailed comments on the whys and wherefores.

**Comment by tpinfold** [comment]
Thanks for the informative reply. It is a shame that it is not possible to include the feature but I understand that what I want and what is possible don't always align.

**Comment by jenshannoschwalm** [comment]
Just one comment. While implementing that I experimented and evaluated with support for non-raw files. Results are simply not predictable enough so for not worth-to-do. Dt is mainly a raw processor for me :-)
