### ISSUE TITLE
selective copy paste: copy from lower instance of module overwrites higher instance on paste

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#16376]
### Describe the bug

If you have 2 instances of a module, change the lower (in pixelpipe) instance, then copy and paste it to another image with both instances, the higher (in pixelpipe) instance is changed.  If the instance has a label, the label is not changed so there isn't an indication that the incorrect instance got the change applied to it.

Tested the copy both instances work around that I found with #16375 and it works here also.

### Steps to reproduce

1. Open an image with 2 instances of tone equalizer and change the lower to compress dynamic range.  
![before](https://github.com/darktable-org/darktable/assets/1634891/6d8693c7-0d2c-41b7-a42c-abb75cb7169d)

2. Selectively copy the lower instance. 
![copy](https://github.com/darktable-org/darktable/assets/1634891/e5bd068e-f290-4cda-a5cf-d04ff0d85dea)

3. Paste the copy and then notice the upper instance changed, but the label remained the same. 
![after](https://github.com/darktable-org/darktable/assets/1634891/9b05b0b1-2c83-403a-a54a-89c664a658b0)

### Expected behavior

apply the change to the corresponding instance

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.7.0+630~gb0ebf97c59

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

**Comment by s7habo** [comment]
I can't reproduce it with https://github.com/darktable-org/darktable/pull/16373
