### ISSUE TITLE
Style with second instance of module overwrites first instance when applied

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#16375]
### Describe the bug

Creating a style from an image with two instances of a module and only selecting the second instance, causes the default instance to be overwritten when the style is applied instead of adding a second instance.

There is a work around.  If you specify both instances of the module when creating the style then it works correctly.

### Steps to reproduce

1. Open an image with the default scene referred workflow and add a 2nd instance of tone equalizer and place it just below filmic_rgb.  Set the second instance to `tone curve soft`. 
![2ndinstance](https://github.com/darktable-org/darktable/assets/1634891/b49b095b-c08e-4e41-bbd3-72dcaeb67c7b)

2. Create a style from the image selecting only the second instance.  
![createstyle](https://github.com/darktable-org/darktable/assets/1634891/d7bbd3ba-d4f3-4251-a282-ca24b1718bb8)

3. Apply the style, then open the image and look at the module list.  
![afterpaste](https://github.com/darktable-org/darktable/assets/1634891/38e4503c-b4e4-468e-bb7d-0cd8fb87639f)

### Expected behavior

Create the second instance and put it just below filmic_rgb.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.7.0+633~gb0e476554e

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
I investigated this further, trying to come up with a better example, and perhaps understand the issue a little better :).

Let's say that I create an instance of the exposure module with the EV set to 0 and a parametric mask set to mask midtones.  I name it midtones.  I create a style with this exposure instance.

I import an image.  I open the image and the default scene referred workflow is applied.  I return to lighttable and then apply my exposure stye.  I reopen the image in darkroom and I have 2 instances of exposure.  Everything is good.

I import an image.  I apply my exposure style.  I open the image in darkroom and I have no scene referred default exposure adding 0.7EV because my midtone exposure module had already been applied.  

So the issue is should an uninitialized image be initialized before pasting a style to it.  

I don't know the "correct" answer to this.

The "work around" is to always include the modules you want to have present as well as what you want to add to ensure you get what you want.  So maybe we just document?

**Comment by jenshannoschwalm** [comment]
@wpferguson is this still valid?

@TurboGit just an idea here - i have not worked on style code so i don't know if it's stupid. As we no have the order now as 100* old iop_order couldn't we make use of this here?

**Comment by wpferguson** [comment]
I think this is one of those "that's how it works, deal with it".  There was another issue about using a single module multiple times and then creating a style from it and it creates multiple instances of the module, which seems like the reverse of my problem.

I think the only way to fix both of the above is to give create style a whole lot more intelligence and even then I'm not sure there is a solution that will satisfy everyone.

I can make create style do what I want, so I'll close this.
