### ISSUE TITLE
Fujifilm X100VI

### ISSUE THREAD

**Issue by j-heinzel** [darktable-org/darktable#16393]
Trying to open RAF images from the new Fujifilm X100VI in darkroom (they are visible in lighttable) but it fails with "Failed to read camera white balance information from [filename]". 

I have just uploaded a sample to https://raw.pixls.us/

Images are RAW uncompressed.  Darktable 4.6.1.

**Comment by LebedevRI** [comment]
@j-heinzel thank you for contributing the sample!
(does that camera produce any other raw types other than uncompressed?)

**Comment by j-heinzel** [comment]
As I see it here in the menu: uncompressed, lossless compressed and compressed.

**Comment by LebedevRI** [comment]
@j-heinzel please take all three shots of the same subject, and contribute them all!

**Comment by j-heinzel** [comment]
Uploaded three more
DSCF0074.RAF - uncompressed
DSCF0075.RAF - lossless compressed
DSCF0076.RAF - compressed

**Comment by LebedevRI** [comment]
@j-heinzel thank you for contributing the samples!
