### ISSUE TITLE
Ability to shrink or grow parametric mask selections 

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#16409]
In GIMP when I make a selection using select by color, which is a form of parametric mask, I have the ability to shrink or grow a selection. This is very important when I have a subject against a solid colored background and select the background and invert selection to isolate the subject. Scenarios may include but are not limited to a bird flying across a blue sky. In a case like this a better selection is obtained if the selection is grown by one or two pixels. It would be good if this was an option when creating parametric masks in DT. GIMP also offers a threshold slider when using the automatic pipette to select colors. An inclusion of a threshold slider for parametric masks would further improve the parametric masks selection in DT. 

Unfortunately I am not a coder so I don't appreciate how easy or difficult this feature request would be to implement. I do feel it would have wide appeal and would further improve the already excellent masking system in DT.

Thanks

<img width="110" alt="image" src="https://github.com/darktable-org/darktable/assets/54665654/d3d40abf-2c75-4b4c-a230-4fa15adfdf31">
<img width="116" alt="image" src="https://github.com/darktable-org/darktable/assets/54665654/bb6c5409-8edb-4509-83f8-5673997685cf">

**Comment by MStraeten** [comment]
gimp masking is not a kind of parametric mask as in darktable. It’s a drawn mask generated once based. In darktable parametric masks are even changed after initially defining them if the input is changed afterwards
Have a look at https://docs.darktable.org/usermanual/4.6/en/darkroom/masking-and-blending/masks/parametric/ and https://docs.darktable.org/usermanual/4.6/en/darkroom/masking-and-blending/masks/refinement-controls/ to get how parametric masks works and how they can be refined

**Comment by tpinfold** [comment]
Thanks Martin, that makes sense and probably makes my suggestion impractical.

**Comment by jenshannoschwalm** [comment]
In fact it's not impractical - it's about how dt masks work. All dt masks are like grayscale images, one float between 0->1 per pixel. We "could" do morphological operations on masks, but what be the a) threshold for the morph op and b) resulting value. Plus added complexity of the module.

In dt we have the feathering of masks using a guided filter which is mostly much better than morphological expansion. So closing this as not planned.
