### ISSUE TITLE
Mask 'Boost Factor' not functioning

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#16404]
### Describe the bug

When creating a mask the 'boost factor' slider does not appear to function correctly.

### Steps to reproduce

1. select a parametric mask and establish a target area in the image.
2. a correct initial mask is created
3. move the boost-factor slider upwards to enlarge the pre-selected area
4. the slider only moves the indicators to higher levels but no change in the mask is seen
5. Before boost-factor ..... basic/initial mask is correctly shown
6. 
![Screenshot_2024-03-03_17-03-48](https://github.com/darktable-org/darktable/assets/6267270/40167ef4-5514-4af3-8707-72dda9505e98)
after boost-factor used .... the mask does not change despite massive change with the markers.
![Screenshot_2024-03-03_17-05-08](https://github.com/darktable-org/darktable/assets/6267270/08d4f3b5-dee8-477f-bdcd-f5c5eb4cb984)

### Expected behavior

Boost-factor appears to be incorrectly functioning.

### Commit

Function not previously used.

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.7.0+643~ga2babfa9a4

### What OS are you using?

Linux

### What is the version of your OS?

Current Manjaro/Arch/XFCE

### Describe your system?

16 Gb. Mem.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia -470xx GTX1660

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Problem shown on fresh edit and refreshed edit.
No Lua in use

**Comment by pehar1** [comment]
> ... but no change in the mask is seen

I think you misunderstood the functionality of this slider. From the manual :

> The boost factor slider allows the range of values targeted by the parametric mask sliders to be extended. It may be used in scene referred editing, where luminance values may extend beyond 100%, to target highlights.

This does **not** mean that the mask is changed by this slider, but the selectable range changes. Using this function frequently I can say it is working as expected.

**Comment by davidvj** [comment]
OK then, I totally misunderstood the use of the booster-factor. What I now understand is that the selection process is a "hit and miss" process. If I try one setting of the boost and that does not provide a correct response, the I change the boost and start all over again.
I do get it now. My misunderstanding. This functionality is totally unlike how I possibly imagined that it could be designed.
Sorry that I wasted everybody's time.

**Comment by davidvj** [comment]
I can confirm that the 'boost' slider is totally ineffective and does not assist in defining the masked area.
Further testing carried was out using the exposure module.

**Comment by pehar1** [comment]
> 'boost' slider is totally ineffective

It's definetly not. I think you continue to misunderstand the function of this slider. Setting a boost factor of

- 0 EV (default) sets an input range of 0 ...1, 
- 1 EV sets an input range of 0 ... 2
- and so on

> the slider only moves the indicators to higher levels

No, it does not. Look at your screenshots: the values of the indicator positions (_input_) are 0.62 , 0.64 , 0.74 and 0.76 for boost factor 0 EV (first screenshot) and do not change for boost factor 0.948 EV (second screenshot).
**The mask remains unchanged.**
**What changes is the selectable range**, it is extended to values larger than 1.

> does not assist in defining the masked area

It does. Again from the manual :

> It [the boost factor slider] may be used in scene referred editing, **where luminance values may extend beyond 100%, to target highlights.**

**Comment by davidvj** [comment]
My apologies .... the understanding that I had for this function were not in line with the concept of the dt design.
I , some years ago, led in the design of Landsat satellite analysis software where (masking) the selection of differing land-forms, both hard edged and fuzzy, was a critical requirement.
I simply had something different in mind.
Again, an apology.
