### ISSUE TITLE
RFC: Rename "overlay" module to "composite"

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#16423]
I think composite is a more commonly-used term in photography and potentially easier for people to get what it's for.

**Comment by elstoc** [comment]
While we're here, can I just say that in English the process of combining elements from multiple images is "composite" / "compositing" rather than "compose" / "composing" (which is something else). Just something I noticed in the PR and release notes, which I'll correct when I get around to the copy-edit.

**Comment by TiredOfGuessing** [comment]
Composite is the term I am familiar with for combining multiple images.

**Comment by jenshannoschwalm** [comment]
Also would like composite

**Comment by elstoc** [comment]
this is merged now
