### ISSUE TITLE
GoPro Hero 11 Black

### ISSUE THREAD

**Issue by dergib22** [darktable-org/darktable#16427]
From what I have seen, raw photos from my GoPro Hero 11 does not yet seem to be supported. I have uploaded a sample image to https://raw.pixls.us/

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
@dergib22 thank you for contributing the sample!

**Comment by LebedevRI** [comment]
We are also missing HERO12, if someone could contribute a sample from that camera, it would be great.

**Comment by kmilos** [comment]
GPR files should just work, regardless of the model...

Are you facing any particular issues?

**Comment by dergib22** [comment]
Now that I tried importing my GoPro Hero 11 raw images again, it does appear to be importing. I am not sure what I what doing initially that only worked after running the file through Adobe DNG Convert. 

On a slight side note, there does appear to be pink highlights where the RAW image has been clipped. The raw overexposed indication overlay does not show this area as being overexposed. The pink can be remedied with Highlight Reconstruction by reducing the clipping threshold down to around 0.9.

**Comment by kmilos** [comment]
> The pink can be remedied with Highlight Reconstruction by reducing the clipping threshold down to around 0.9.

This usually means that the white level metadata is either wrong or missing.

You can also reduce it in the raw black/white point module and leave the highlight reconstruction at 1.0. You could create a preset that applies to the particular model then.

**Comment by kmilos** [comment]
The sample file says
```
Exif.Image.WhiteLevel                         4095
```
So nothing further to do here in terms of support.
