### ISSUE TITLE
Geometric distortions not corrected using embedded metadata for Fujifilm x100t, but are corrected if wide or tele converters used

### ISSUE THREAD

**Issue by hamish37gmailcom** [darktable-org/darktable#16435]
### Describe the bug

Darktable 4.6.1 does not attempt to use metadata provided in .RAF file by Fujifilm x-100t using its built-in 23mm lens to correct geometrical distortion. However, when using the tele converter, (focal length 33 mm) the lens correction module corrects TCA, vignetting and geometric distortion. Same for the wide angle conversion lens (focal length 19mm): lens correction adjusts vignetting, TCA and geometric distortion. Without conversion lens, lens correction does not report an error but if you select the "only Distortion" item, lens correction reports "corrections done: none". The corrections for the wide angle and tele converters appear to be correct, and with just the fixed lens it appears to be true than no distortions are being corrected. Following is the actual embedded metadata regarding lens distortion: 1.  Bare 23mm lens: GeometricDistortionParams 267.4545455 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 0 0 0 0 0 0 0 0 0 0 0     2.With wide angle converter: GeometricDistortionParams 267.4545455 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 0 -0.185 -0.428 -0.786 -1.313 -1.992 -2.742 -3.546 -4.337 -5.061 -5.664   3. With tele converter: GeometricDistortionParams 267.4545455 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 0 0.039 0.11 0.244 0.47 0.82 1.335 2.085 3.104 4.47 6.289 . EDIT: AFTER STUDY OF GEOMETRIC DISTORTION PARAMETERS BEING REPORTED BY THE CAMERA THIS MAY NOT BE A BUG. It appears that the camera is reporting zero geometric distortion when no conversion lens is attached.

### Steps to reproduce

[RAF file.zip](https://github.com/darktable-org/darktable/files/14551639/RAF.file.zip)
1. Open first attached RAF file in Darktable 4.6.1.
2. Open Lens Correction module.
3. Lens correction will report that all corrections are being made based on embedded metadata
4. Change selection of corrections from "all" to "only distortion"
5. Corrections being made will report "none" and indeed no corrections are being made, despite the presence of geometric distortion metadata in the RAF file.
[RAF file 2.zip](https://github.com/darktable-org/darktable/files/14551656/RAF.file.2.zip)
6. Open RAF file 2 in Darktable 4.6.1
7. Alternately enable and disable lens correction. you will clearly see that geometric distortions are being corrected. The only difference is the presence of a conversion lens on the built-in fixed lens of the x-100t 

### Expected behavior

Darktable should use the geometric distortion embedded metadata to correct geometric distortions of the fixed lens of the x-100t. Darktable is able to make such corrections when either the wide or tele conversion lenses are attached.. 

### Logfile | Screenshot | Screencast

<img width="303" alt="image" src="https://github.com/darktable-org/darktable/assets/95568959/4590da4f-1a3f-4f91-ae4a-5dd62d9ee4c5">
<img width="1652" alt="image" src="https://github.com/darktable-org/darktable/assets/95568959/21864e13-f747-4a32-a15d-801d414a4ee9">
<img width="1591" alt="image" src="https://github.com/darktable-org/darktable/assets/95568959/1523e4c7-f501-4320-bbe0-fa916ee38c5a">
First screen snip shows issue with no conversion lens. next two screen snips show geometric distortion being corrected when there is a wide conversion lens attached. The last screen snip disables vignetting and TCA to demonstrate that Darktable is showing that geometric corrections are being made, unlike the first screen snip. 

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

windows 11 pro

### Describe your system?

12 core Intel desktop processor, 32 GB memory - I don't think my system is responsible.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia Quadro P1000 Driver 537.7 dedicated video memory 4096 MB GDDR5

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

1. Have not tried other versions of Darktable
2. This is just with raw files
3. yes, reproducible with fresh history

**Comment by ralfbrown** [comment]
Just to highlight this for any future readers:
> It appears that the camera is reporting zero geometric distortion when no conversion lens is attached

So, if there is a bug at all, it lies with the camera's firmware.
