### ISSUE TITLE
[dt 4.7.0] "cannot get iop-order" bug by selective paste

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#16441]
### Describe the bug

If you use the "selective paste" function, the photo is completely distorted and the terminal shows the message "cannot get iop-order" for the instances of the modules you have changed.

### Steps to reproduce

1. Make a change in one of the modules (here the exposure):

![grafik](https://github.com/darktable-org/darktable/assets/38165484/760fc8fd-7d2a-4cd3-80bb-2895f2c63838)

2. Go to the lighttable, choose either **selective copy** or **copy** option. 
3. Select another photo and click on **selective paste**. 
4. Without changing anything, click on **OK** :

![grafik](https://github.com/darktable-org/darktable/assets/38165484/6a77c94f-134c-4fea-bed4-877d4ff98381)

5. The photo is completely distorted and...

![grafik](https://github.com/darktable-org/darktable/assets/38165484/6070deba-f388-478f-b455-a5572c250d27)

...in the terminal you see "**cannot get iop-order for exposure instance 1**"

![grafik](https://github.com/darktable-org/darktable/assets/38165484/a112ee52-10bd-4102-a20a-262960b7ccd2)

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+713~g11546b30a

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.19.0-1028-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070/PCIe/SSE2, G Driver 535.129.03

**Comment by s7habo** [comment]
Strange. I have just recompiled the darktable and the problem is still there..


https://github.com/darktable-org/darktable/assets/38165484/a3207fae-9014-470e-b46f-c525bdc3baf2



Note that the **paste** option works. The problem only affects **selective paste**.

**Comment by s7habo** [comment]
I have the same issue with the latest master git version from OBS:
4.7.0~git720.7baaaf11-1+11426.1

**Comment by s7habo** [comment]
I just realized that "selective paste" works as expected when I **compress the history stack of the original photo first**.

**Comment by gi-man** [comment]
Ive been seeing the same issue as S7habo for a few days but I could not reproduce it. Ive been reprocessing images from 2013 and my first step was to discard the history via lighttable. Some of the images images show the exposure module off and the weird colors. Only resetting the history in the darkroom fixed them. 

Using the steps S7habo shared in the original post, I get the same issue. Terminal shows the same message about exposure 1.

**Comment by HansBull** [comment]
For me, selective copy is essentiallly broken in current master.  Selective copy  -> select all -> paste with overwrite (even with images with a clean history) -> garbled image as in s7habo's screenshot.

**Comment by gi-man** [comment]
I have two CR2 images taken in sequence. I reset them both. I edit image one by increasing the exposure. I go to lighttable and select the first one, selective copy. Go to image two and use selective paste. Weird colors. 

Output from darktable -d ioporder. https://pastebin.com/kdKHieFC

Looking at history, if I step back to the one previous to `exposure . 1` The colors get correct.

**Comment by gi-man** [comment]
I just tried it using the same steps as above, but doing an edit in filmic. I get the same issue: `filmic . 1`

```
   386.8987 cannot get iop-order for filmicrgb instance 1
   386.8988 [dt_ioppr_check_iop_order] history module not used but enabled!! filmicrgb 1(2147483647) image 3994 (dt_dev_read_history_no_image end)
   391.2838 [lib_modulegroups_update_iop_visibility] modulegroups
   391.3266 cannot get iop-order for filmicrgb instance 1
   391.3266 [dt_ioppr_check_iop_order] history module not used but enabled!! filmicrgb 1(2147483647) image 3994 (dt_dev_read_history_no_image end)
   391.6749 [dt_ioppr_check_iop_order] history module not used but enabled!! filmicrgb 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
   391.6750 [dt_ioppr_check_iop_order] history module not used but enabled!! filmicrgb 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
   391.6931 [lib_modulegroups_update_iop_visibility] modulegroups
```

**Comment by jenshannoschwalm** [comment]
Exposure is special because of the proxy. Maybe we have to check for that somehow.

**Comment by gi-man** [comment]
And I was able to produce it with filmic. It seems to only happen with the last edited module instead on all the multiple instances.

**Comment by HansBull** [comment]
Seems indeed to be fixed. Merci beaucoup!
