### ISSUE TITLE
Lens correction refuses to apply with adapted lens

### ISSUE THREAD

**Issue by TheBolshe** [darktable-org/darktable#16449]
### Describe the bug

I take photos with a Sony A7 IV and an adapter ring for EF lenses.
darktable identifies both my camera and my lens, however refuses to apply the corrections (i suspect because the lens mount is not native to the body and when i try to manually select the lens it's not proposed)
![image](https://github.com/darktable-org/darktable/assets/26492864/de25101c-bf0c-4fd6-ac92-434766cce1bc)
![image](https://github.com/darktable-org/darktable/assets/26492864/04de6b51-802e-42b6-b775-6d059fe36293)

### Steps to reproduce

Open this photo in darktable https://drive.google.com/file/d/1QpVq8xp8RIw2iB39fpLqPdtDaNrabtOl/view?usp=sharing
Try to apply lens correction

### Expected behavior

I this lens/body combination shouldn't be restricted to only native lenses

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by kmilos** [comment]
I guess this is not a know combo in the [lensfun ](https://github.com/lensfun/lensfun)database, and the issue should actually be reported there (and new calibration uploaded ideally).

**Comment by victoryforce** [comment]
> the lens mount is not native to the body and when i try to manually select the lens it's not proposed

@TheBolshe This is intentional behavior, so there is no bug in either darktable or upstream (ie lensfun). Please learn about [lensfun‑add‑adapter](https://lensfun.github.io/manual/v0.3.2/lensfun-add-adapter.html) and use it to solve your issue.

**Comment by TheBolshe** [comment]
> > the lens mount is not native to the body and when i try to manually select the lens it's not proposed
> 
> @TheBolshe This is intentional behavior, so there is no bug in either darktable or upstream (ie lensfun). Please learn about [lensfun‑add‑adapter](https://lensfun.github.io/manual/v0.3.2/lensfun-add-adapter.html) and use it to solve your issue.

Is there a way to do this on windows ?

**Comment by kmilos** [comment]
> Is there a way to do this on windows ?

Create a copy of the Sony E entry and add Canon EF as compatible mount (as below) and save as `_mounts.xml` either inside `%LOCALAPPDATA%\lensfun` or `%USERPROFILE%\.local\share\lensfun`

```xml
<lensdatabase>
    <mount>
        <name>Sony E</name>
        <compat>M42</compat>
        <compat>M39/1</compat>
        <compat>DKL</compat>
        <compat>T2</compat>
        <compat>Generic</compat>
        <compat>Canon EF</compat>
    </mount>
</lensdatabase>
```

Please keep GitHub to darktable directly related issues and development. You can seek general user support at https://discuss.pixls.us/c/software/darktable/19
