### ISSUE TITLE
Panasonic FZ28 .rw2 file does open in DT but not in Develop mode

### ISSUE THREAD

**Issue by wimttttt** [darktable-org/darktable#16457]
I want to try DT to develop my Panasonic Lumix FZ28 Raw images. I am able able to add them in my library but they do not open in DEVELOP mode. Failure:  failed to read camera white balance information. On pxls.us it was suggested that DT can open 4:3 and 16:9 but not 3:2 and that this might be unintentional.

DT 4.6.1 , Windows11

**Comment by kmilos** [comment]
Please upload a full set of aspect ratios to raws.pixls.us

**Comment by wimttttt** [comment]
done

**Comment by LebedevRI** [comment]
@wimttttt thank you for contributing the sample set!
That camera only has 3 crop modes, correct?

**Comment by kmilos** [comment]
> That camera only has 3 crop modes, correct?

I had a look at the manual online, it would seem only those 3 aspect ratios are possible, and not the 1:1...

**Comment by kmilos** [comment]
@wimttttt Please feel free to test the linked PR.

**Comment by wimttttt** [comment]
I will when I am back home in a few days. Thanks a lot!

**Comment by wimttttt** [comment]
Works fine. Thanks
