### ISSUE TITLE
[HDR Merge] Black patches in overexposed regions and white pixels appear 

### ISSUE THREAD

**Issue by a1302z** [darktable-org/darktable#16452]
### Describe the bug

I've never had any problems so far with the HDR merge tool so far and I couldn't find any similar issue yet. If some exist feel free to redirect me. 

The issue is pretty much the title. I wanted to merge three long exposure shots to an HDR but the result has large black patches in regions which are overexposed and additionally some white pixels appear (there are three in the screenshot, bottom right, middle left, lower left). 
![image](https://github.com/darktable-org/darktable/assets/15774442/9639861f-47e4-474b-9849-be65a079df74)

None of the modules seem to change anything, even when all are deselected the issue appears.

### Steps to reproduce

Select source images and perform an HDR merge. Source data is [here](https://syncandshare.lrz.de/getlink/fiMtNhQvQdVNpVFAwjBGeT/)

### Expected behavior

Overexposed areas should be white. No white pixels should appear.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070; Driver Version: 535.161.07

**Comment by kmilos** [comment]
> I wanted to merge three long exposure shots to an HDR

I might be wrong, but I think this works only for exposure bracketed shots, not three identical ones?

**Comment by a1302z** [comment]
You're right. I thought about it a bit more and it does work exactly as expected, so it's not a bug it's a feature. Actually it's really smart that for three images where two are black and one is white in the same exposure, which are assumed to be the same color to do a majority voting to black. The white pixels I still can't explain though. What I probably need to do is stack these images as a kind of fake even longer exposure shot. If you have any pointer how to do this with darktable or can recommend any other tool I would very much appreciate it. Otherwise I think this issue can be closed.
