### ISSUE TITLE
Inconsistent raw monochrome picture display in lighttable and darkroom

### ISSUE THREAD

**Issue by joaobrisson** [darktable-org/darktable#16471]
### Describe the bug

Raw files generated by Canon camera with Picture Style set to Monochrome correctly show as monochrome in lighttable but as colour pictures in darkroom
Darkroom shows no info about the Monochrome option 
This confuses the user that has to hop from darkroom to lighttable to check each picture's colour/B&W status
Off course it is disputable whether the Monochrome module should be automatically added and set on as raw files are colour files always
However an handy improvement would be to show the picture as B&W on the strip on the bottom of the screen of darkroom

### Steps to reproduce

1. Shoot a raw picture on a Canon camera with Picture Style turned to Monochrome
2. Import to dt
3. It shows as B&W on lighttable
4. Change to darkroom

### Expected behavior

dt should show information in darkroom to identify pictures taken with Picture Style set as Monochrome

### Logfile | Screenshot | Screencast

not applicable

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 12.7.4

### Describe your system?

not applicable

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Any raw file taken on a Canon with Picture Style set to monochrome will do

**Comment by ralfbrown** [comment]
The lighttable thumbnail is the embedded JPEG produced by the camera.  I don't think darktable is able to parse the camera settings to determine whether monochrome mode was used, so in darkroom view you get default processing - which is full color.

**Comment by jenshannoschwalm** [comment]
@ralfbrown you forgot
![Bildschirmfoto vom 2024-03-15 23-22-45](https://github.com/darktable-org/darktable/assets/50982232/3141cb49-f816-42c0-ba65-a0726ed0d776)

If you switch on "detect monochrome previews" we look for exactly this situation - a raw with a monochrome embedded JPEG - while importing the image file (or via "Refresh Exif" in actions on selection -> Metadata). If that is found we mark the image with a B&W tag. So when defining a preset - for example i use a preset in color calibration to use Fuji Acros 100 - and define that as
![Bildschirmfoto vom 2024-03-15 23-29-30](https://github.com/darktable-org/darktable/assets/50982232/3cff796a-80ed-4e73-bd1f-a2d5618d9f54)

The image will be B&W in darkroom already now :-) (That's my workflow ...)

**Comment by joaobrisson** [comment]
I am not reporting a bug but an serious interface inconsistency that makes users jump back and forth from darkroom to lighttable to check whether each photo was intentionally shot as b&w because in darkroom there is no hint if a photo was shot with b&w intent

as i said this could be alleviated if a photo shot in raw with b&w turned on was shown as b&w on the thumbnail strip at the bottom of darkroom

in the strip such a photo shown in colour and, once again, this is inconsistent with what lighttable displays 

and finally i am referring to pure raw files, not raw+jpeg files
the workaround does not work with raw only files

JB

**Comment by jenshannoschwalm** [comment]
That's not a workaround, i use it daily for raws. Just a reminder, your "monochrome raws" are not monochrome at all, the raw of such cameras are full color bayer images. If you do as above your images will all have a B&W tag shown above the image ... The darkroom basically sees the raw bayer file. Sp you have to use a preset ... that fully works as intended.

**Comment by joaobrisson** [comment]
Of course raws are not monochrome and lighttable shows it on the thumbnail and its label (CR2 and B&W on a Canon)

The problem is that info just goes away in darkroom

What we are discussing here is an interface inconsistency, one of the major sins in UI design

**Comment by parafin** [comment]
Fix for inconsistency is to disable Jpeg previews, then photo will be color both in lighttable and darkroom. darktable doesn’t support camera picture styles and monochrome is just one of them.

Perhaps indeed jpeg previews should be off by default, to stop reports like this about “colors suddenly change”.

**Comment by jenshannoschwalm** [comment]
> Fix for inconsistency is to disable Jpeg previews, then photo will be color both in lighttable and darkroom. darktable doesn’t support camera picture styles and monochrome is just one of them.

Generally yes. Although 'monochrome' seems to be far more important to me so we introduced support for a monochrome workflow some time ago. Another way to avoid "wrong look" would be to add some sort of automatic preset - for example in color calibration - but that seems not to be fine for the majority of users. So all users with special interest in monchrome can/should define their own presets.



> Perhaps indeed jpeg previews should be off by default, to stop reports like this about “colors suddenly change”.

Yes, this issue is just another round of "why do thumbs look different from darkroom" and alike. I have never used jpeg thumbs but always did "high quality from raw" but this comes with a perf penalty. Do you have a strong "pro" opinion? A RFC issue maybe?

**Comment by joaobrisson** [comment]
Absolutely not, your suggestion sidesteps the issue
The issue is a User Interface inconsistency

Please refer to some classical UI bibliography such as  
             Interaction Design: Beyond Human-Computer Interaction, Y Rogers, H Sharp, J Preece (any edition)
and read the chapters dealing with Heuristic Evaluation
Alternatively, google “Jakob Nielsen 10 heuristics”

I will now try to explain what is at stake here

Lighttable thumbnails are the darktable jpeg interpretation of the raw files based on the modules and module settings that were assigned to each file automatically (eg, import time) and by user manipulation (in darkroom).
In short, lighttable thumbnails are previews of the current development status of each file

Lighttable shows thumbnails of photos taken with monochrome camera settings as monochrome and shows the “B&W” label on the top left of the thumbnails
The user sees such thumbnails and clearly identifies them as shots taken with monochrome camera settings
The information is clear to the user’s eyes

Now step into darkroom and ask yourself “where are those shots that I took with monochrome settings?”
Nowhere is any information on this!
Why?

First, no Monochrome module (or any other for the same purpose) has been assigned to the photo under development
This is right, darkroom’s central area must display the result of all active modules and no more

Second, the thumbnail strip at the bottom shows the raw file as colour but … there is no hint to identify the file as shot with monochrome settings

Again the user asks himself “Which of these are the shots I took  with monochrome on?”
And the interface is incapable to show you this information!

The inconsistency is that you know which shots were taken with monochrome settings in lighttable but in darkroom you don’t know and there is nothing to help you
You have to go back to lighttable and check

But wait

In lighttable, collections, select tag darktable|mode|monochrome then move to darkroom. The thumbnails shown on darkroom’s thumbs strip will be the ones shot with monochrome camera settings.
The fast workaround, is to, while in lighttable with collections selected tag darktable|mode|monochrome,  select all and assign a previously created Style that sets a blind Monochrome module to them all

Nevertheless, the inconsistency lives on, sorry

**Comment by jenshannoschwalm** [comment]
If you care about monochrome-flag -> you can see that already in darkroom in "image information", the "m" letter. The filmstrip shows this info also as shown here (filmstrip size might need some enlargement to show this)
![Bildschirmfoto vom 2024-03-16 15-48-52](https://github.com/darktable-org/darktable/assets/50982232/8df2d84c-245f-4d63-afb0-4b417677efd3)


If you care about consistency - as described above - add a automatic preset for your favorite monochrome module if you want that module applied automatically. And/Or develop thumbs from raw files, see preferences.

**Comment by joaobrisson** [comment]
Yes! It was not showing because I wanted to maximize the central edit area, the filmstrip was reduced
Something should be done to make it show even when small

Will try to do as you advise, thks

**Comment by joaobrisson** [comment]
preset working faultless

thanks a lot
