### ISSUE TITLE
I cannot see and process orf files OM Digital Solutions camera OM-1. I use a purchased version of darktable 4.2.0 on windows

### ISSUE THREAD

**Issue by gabions** [darktable-org/darktable#16531]
I cannot see and process orf files OM Digital Solutions camera OM-1. I use a purchased version of darktable 4.2.0 on windows.

Could you add support for such raw files?

Thanks!

**Comment by LebedevRI** [comment]
> purchased 

o_O

4.2.0 is ancient, support was added in some later version.

**Comment by kmilos** [comment]
@gabions [darktable is freely available software](https://www.darktable.org/install/), you've been scammed.
