### ISSUE TITLE
Inconsistent output for similar files

### ISSUE THREAD

**Issue by ziadloo** [darktable-org/darktable#16548]
### Describe the bug

I use Darktable to adjust colors of my timelapse images. We are talking about RAW (CR2) images that are taken a few seconds apart and are very similar to each other. My process is to use Darktable to adust the color of one of the frames to my liking and then I'll apply the same exact settings to all the frames. The problem is that the generated output is not consistent across all the frames. This results in flicker once the images are stitched into a video.

To make sure that my color adjustment is not causing this issue, I disabled every single module applied to my images in Darktable (even white balance) and then exported the images. Having disabled WB, the colors of the output are bizarre but the important part is that the flicker is still there. It would be much simpler to see the flicker if you play the images one after the other (looking at them side by side, you might miss it).

![IMG_8618_01](https://github.com/darktable-org/darktable/assets/3235521/e1487e2b-3088-4b77-8b12-3621e31eee18)
![IMG_8619_01](https://github.com/darktable-org/darktable/assets/3235521/747ef8fe-007a-4f70-8dbc-234befeeb40c)
![IMG_8620_01](https://github.com/darktable-org/darktable/assets/3235521/f729cc39-65f9-48b2-b76f-f35b6de55b16)

The middle image in the above 3 is slightly brighter than the other two. But if I use Gwenview and convert the same RAW (source) images into JPEG, the resulting images (even though unacceptable) are not suffering from the same problem:

![IMG_8618](https://github.com/darktable-org/darktable/assets/3235521/54797c55-74e2-4419-9af7-20054e5223ea)
![IMG_8619](https://github.com/darktable-org/darktable/assets/3235521/98a62fd0-45b1-4467-8ace-6573750eaa4e)
![IMG_8620](https://github.com/darktable-org/darktable/assets/3235521/a9121ebe-e913-4294-b686-e625069fdd72)

Here are the source RAW images (only first two) if you want to test it yourself.

[IMG_8618.zip](https://github.com/darktable-org/darktable/files/14813842/IMG_8618.zip)
[IMG_8619.zip](https://github.com/darktable-org/darktable/files/14813843/IMG_8619.zip)

I'm using Darktable 4.6.1 on Manjaro KDE Plasma (Kernel 6.6.19-1). And as far as I can remember, this problem was always there (like a few years ago). It's just that I never suspected it's Darktable's fault until now.

### Steps to reproduce

1. Import the provided RAW images
2. Disable all the modules (even white balance)
3. Export the images
4. Compare the exported images

### Expected behavior

The sky in the exported images should be very much identical

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro KDE Plasma 5.27.11 (Kernel: 6.6.19-1-MANJARO (64-bit))

### Describe your system?

* RAM: 64 GB
* Wayland

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by ziadloo** [comment]
I would like to add that I just used RawTherapee and it gave me the same results as Darktable (with flickering). I don't know if RawTherapee is using the same libraries as Darktable or what. Maybe the problem is actually with my images? But then how come the Gwenview converts them without the flicker?

**Comment by HansBull** [comment]
Garbled output looks similar to #16441
Maybe you  could test with current master?

**Comment by ziadloo** [comment]
@HansBull Sorry for confusion. The green outputs look garbled only because I disabled the white balance module. If I enable it, it will look just fine. And that's not the issue. The issue is that I was expecting the two images look very similar when exported but they don't. And if I want to be honest, I'm not sure if this is because of my camera or Darktable. So far, two out of three software have exported my images with the problem as I explained above. I'm looking around to see if I can find someone with Lightroom as a tie breaker (it's not much of tie though).

**Comment by parafin** [comment]
gwenview most likely uses embedded JPEG, not the raw data, meaning it was processed by camera.

**Comment by ziadloo** [comment]
I didn't know CR2 (RAW) has an embedding JEPG in it! My camera has the option to capture RAW and JPEG at the same time but into two separate files. And I have set it to only save the RAW format. So, it sounds very strange to me to hear that there's still a JPEG embedded into the RAW file.

**Comment by kmilos** [comment]
> So, it sounds very strange to me to hear that there's still a JPEG embedded into the RAW file.

Almost all raw formats have the in-camera processed JPEG (preview and sometimes full size) embedded in them, precisely so other software that are not full-fledged raw developers can show you something.

**Comment by pehar1** [comment]
You can extract the embedded jpg for example with exiftool :
`exiftool -b -previewImage -w .jpg /path/to/your/imagefile.ext`

**Comment by jenshannoschwalm** [comment]
@ziadloo your images all **almost** identical, yet there is a subtle but important difference! The black-levels (inspect "Raw black/white point" module, this is slightly different but leading to different brightness signals resulting in your flicker. I don't know if that would be different with some camera option/setting (manual exposure maybe?) or if this is something canon decides in it's firmware. I know that canon also has some data about sensor-not-linear but that is propriatary.

If you develop your first image and want to apply "everything" for all other images make sure you include "Raw black/white point" in your selective copy. That would be the easiest solution.

**Comment by ziadloo** [comment]
@jenshannoschwalm Thank you for taking a close look. You are right that "Raw black/white point" is slightly different between the two images and I had missed that myself. Unfortunately, when I match the values for that module between the two images, while the gap is getting smaller but it's still there.

To provide context how these images were taken, I use Magic Lantern firmware's intervalometer with the camera set to Av mode. From my perspective, all the images are taken with the same exact settings. Yet somehow there are some subtle brightness differences between them and it's ruining the timelapse.

Any other idea what I can look into that might have caused this?

Thanks again.

**Comment by jenshannoschwalm** [comment]
> Any other idea what I can look into that might have caused this?

Nope, i am just pretty sure it's not a dt problem. Whatever magicklantern is doing here and how they tweak some things, probably they tune some amps here and there - av mode sounds like average?
1. you might look at more data found via exiftool or exiv2 but i wouldn't be surprised if that's undocumented
2. ask the firmware producers :-)
3. if there is an option to use or that sounds to "fixed" use that.

Plerase concider to close as it's not a dt problem ...

**Comment by ziadloo** [comment]
Thanks for the insight

**Comment by ralfbrown** [comment]
"Av" is aperture priority, "Tv" would be shutter priority.

Many cameras will record only standard rounded values for shutter time even though they can set virtually any exposure time.  That can lead to the exposure difference that OP sees even with identical EXiF - the camera records e.g. 1/125s for all three shots, but really had the shutter open for 1/130s on the first and third and 1/115s on the second.

I would recommend either using full manual exposure settings to avoid the flicker, or using the automatic mode in the exposure module to remove it (that is in fact called "deflicker" in the source code!).

**Comment by ziadloo** [comment]
@ralfbrown It seems to me that you are absolutely correct. When I reset the exposure module to "magic lantern defaults" (which I didn't know it existed until now) the differences between the two images are negligible. It's just that what would my process be like if I do need to adjust exposure? I mean should I export one time without touching exposure and then a second time only exposure? I'm pretty sure once RAW is exported to JPEG, it will lose some of its information. Does this mean that I'm doomed either way?

**Comment by ralfbrown** [comment]
The MagicLantern preset (or equivalent settings) will be fine for a daytime-only or nighttime-only timelapse series where the target exposure should remain constant.  Dawn or dusk would require a continuous adjustment of the exposure as the sun rises/sets.  ISTR a script which edits the sidecar files to achieve that, but due to the fact that sidecars contain version-dependent dumps of the internal binary representation of module parameters, that script likely doesn't work on current sidecars.
