### ISSUE TITLE
Darktable crashes when deleting an image

### ISSUE THREAD

**Issue by jrmb95** [darktable-org/darktable#16544]
### Describe the bug

Hello,

When i select an image and delete it, Darktable crashes with no error message.
I can then restart  Darktable normally, but it happens systematically.

The image is no longer in the library, the .nef file is deleted from its folder but the .xmp file has not been deleted

### Steps to reproduce

1- in the Lighttable module
2- select an image (one is enough but it is the same with multiple selection) 
3- click on 'Actions on selection / Delete'
==> Darktable crashes

### Expected behavior

Darktable should not crash when deleting file(s)

### Logfile | Screenshot | Screencast

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14811549/darktable-log.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Family  22H2 

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by jenshannoschwalm** [comment]
could you check if that's working with opencl disables? `darktable --disable-opencl` or after disabling it in preferences? Don't understand where the bad allocation is coming from.

**Comment by jrmb95** [comment]
Hi,
when launching "darktable --disable-opencl " it is the same, the first delete crashes Darktable (delete using trash or not, same).

Another information i forgot to mention : I installed Darktable recently (3 or 4 weeks ago). At the beginning, the delete was working fine, then it started to crash randomly, and now it crashes systematically

[darktable-log.txt](https://github.com/darktable-org/darktable/files/14827756/darktable-log.txt)

**Comment by jenshannoschwalm** [comment]
Maybe the database has been corrupted. You can delete it but would have to reimport all images afterwards.

**Comment by jenshannoschwalm** [comment]
Are you using any avif files? While working #16550 i had a database corruption. The only one in years :-)

**Comment by jrmb95** [comment]
No i am not using avis files. In fact i even did not know this kind of files 😄. Only .nef
