### ISSUE TITLE
Masking 

### ISSUE THREAD

**Issue by TheStoneG** [darktable-org/darktable#16559]
Hey today I used darktable for the first time and loved most of it only the masking was weird because I couldn’t make more mask for exposure so every mask was the same I always used Lightroom and they have like a handy thing that you can set different masks with different settings can you guys make something like that. thanks for the free editing software and all the work you guys do :)

**Comment by ralfbrown** [comment]
You need to use multiple instances of the exposure module if you want to apply different settings.  The mask only controls how much of that particular module instance's adjustment is applied to each pixel.
