### ISSUE TITLE
artefacts in picture on opening in darktable

### ISSUE THREAD

**Issue by astmuc** [darktable-org/darktable#16555]
### Describe the bug

With opencl enabled any picture opened in darkroom has horizontal artefacts. They affect around 1/10th of the height and all the width of the picture (see screenshot below)
<img width="312" alt="Screenshot_20240401_121551" src="https://github.com/darktable-org/darktable/assets/37765839/39717769-3c4d-4839-8f95-c14f08b60f7e">
These artefacts never disappear totally during editing in darkroom, but sometimes change slightly.

### Steps to reproduce

start darktable with ```darktable -d opencl -d pipe >debug.log```
open picture in darkroom with doubleclick (using vanilla setup for automatic processing)

### Expected behavior

darktable should not create artefacts in darkroom presentation

### Logfile | Screenshot | Screencast

[debug.log](https://github.com/darktable-org/darktable/files/14822457/debug.log)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Describe your system?

Devices
*******

Processor
---------

-Processors-
Package Information	
AMD Ryzen 9 7900 12-Core Processor	0	0:0	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	1	0:1	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	2	0:2	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	3	0:3	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	4	0:4	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	5	0:5	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	6	0:8	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	7	0:9	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	8	0:10	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	9	0:11	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	10	0:12	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	11	0:13	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	12	0:0	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	13	0:1	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	14	0:2	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	15	0:3	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	16	0:4	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	17	0:5	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	18	0:8	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	19	0:9	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	20	0:10	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	21	0:11	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	22	0:12	5482.00 MHz	
AMD Ryzen 9 7900 12-Core Processor	23	0:13	5482.00 MHz	

Memory
------

-Memory-
MemTotal	Total Memory	131045400 KiB	
MemFree	Free Memory	101055792 KiB	
MemAvailable		112923472 KiB	
Buffers		1178452 KiB	
Cached		11691844 KiB	
SwapCached	Cached Swap	6580 KiB	
Active		20884132 KiB	
Inactive		7520460 KiB	
Active(anon)		15632040 KiB	
Inactive(anon)		118864 KiB	
Active(file)		5252092 KiB	
Inactive(file)		7401596 KiB	
Unevictable		280 KiB	
Mlocked		280 KiB	
SwapTotal	Virtual Memory	8388604 KiB	
SwapFree	Free Virtual Memory	8305148 KiB	
Zswap		0 KiB	
Zswapped		0 KiB	
Dirty		796 KiB	
Writeback		0 KiB	
AnonPages		15531264 KiB	
Mapped		3796652 KiB	
Shmem		221024 KiB	
KReclaimable		456456 KiB	
Slab		780292 KiB	
SReclaimable		456456 KiB	
SUnreclaim		323836 KiB	
KernelStack		45040 KiB	
PageTables		101572 KiB	
SecPageTables		0 KiB	
NFS_Unstable		0 KiB	
Bounce		0 KiB	
WritebackTmp		0 KiB	
CommitLimit		73911304 KiB	
Committed_AS		27320284 KiB	
VmallocTotal		-1 KiB	
VmallocUsed		159744 KiB	
VmallocChunk		0 KiB	
Percpu		31392 KiB	
HardwareCorrupted		0 KiB	
AnonHugePages		0 KiB	
ShmemHugePages		0 KiB	
ShmemPmdMapped		0 KiB	
FileHugePages		0 KiB	
FilePmdMapped		0 KiB	
Unaccepted		0 KiB	
HugePages_Total		0	
HugePages_Free		0	
HugePages_Rsvd		0	
HugePages_Surp		0	
Hugepagesize		2048 KiB	
Hugetlb		0 KiB	
DirectMap4k		1813440 KiB	
DirectMap2M		26687488 KiB	
DirectMap1G		105906176 KiB	

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

see attached debug.log

**Comment by jenshannoschwalm** [comment]
I have not seen any CL issues at least on master for quite a while and all of them where related to wrong error code returned for small mem. could you provide raw and xmp

**Comment by astmuc** [comment]
This zip contains DNG and XMP and two screenshots with the effect. For me it happens on every picture. The artefacts appear row-wise in landscape and column-wise in portrait.
https://drive.google.com/file/d/1km-DV3ihJIbHuxSgPk4UoB5XuelERMgk/view?usp=drive_link

**Comment by jenshannoschwalm** [comment]
Could you first clear the opencl kernels `~/.cache/darktable/cached_ v3_kernel...` ?

Pretty old driver :-(

could you try current master again with a log ?

**Comment by astmuc** [comment]
I cleared the complete ```.cache/darktable``` folder, but the problem stays the same. The new log from a master/debug run is [debug-master.log](https://github.com/darktable-org/darktable/files/14826910/debug-master.log)

I had a version "3" of darktable running, because ububtu apt suggested a vanilla install for darktable. But this install was not up-to-date. 
Then i checked a flatpack version (4.6.1) with problems in regard to to to turboprint, now i am using the packaged version 4.6.1 for ubuntu 22.04 from https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

**Comment by jenshannoschwalm** [comment]
Here on fedora irs 550.xx

I simply don't know what's wrong, logs look OK. Have you tried the hq mode in master?

Do the artifacts go away if you zoom in?

What happens with exports?

Just wild guesses - no concrete idea - about things that could go wrong in the pipe. Any demosaic er that works? Disable highlights? Disable rgblevels?

**Comment by gi-man** [comment]
Doy you see this issue with raw images that are not dng?

**Comment by astmuc** [comment]
@jenshannoschwalm 
* Zoom in/out always has an effect: sometimes the artefacts go away, sometimes they appear at another place (always wandering multiple rows). Making a zoom-in and out (in total no effect), then the artefacts appear identical again.
* exporting an affected picture three times resulted in pictures without artefacts 

@gi-man the issue is present for the underlying ORF files also. I loaded one filmroll with ORF and DNG.

**Comment by jenshannoschwalm** [comment]
Please try if issues persist when using Lmmse demosaicer, that would rule out opencl in demosaicer&scaling.

**Comment by jenshannoschwalm** [comment]
Just select LMMSE in demosaic module :-)

**Comment by astmuc** [comment]
Ok, this i did and made a new preset with automatic apply. 
The history with a auto-applied demosaic (lmmse) looks like this:
<img width="157" alt="Screenshot_20240402_120445" src="https://github.com/darktable-org/darktable/assets/37765839/c91f1bd7-2d11-4d83-aaa8-6f442c9a3376">

Testing with a filmroll of 37 pictures 
* there are darktable-runs with no problems at all (e.g. opening each complete roll twice in darkroom). In this state i see the artefacts by clicking on step 10 in history
* But there also darktable runs (means i restarted), showing the problems again. In this case the artefacts looks like this
<img width="723" alt="Screenshot_20240402_120827" src="https://github.com/darktable-org/darktable/assets/37765839/65586e54-412e-4f47-adee-5d37e19b935d">

Somehow there seems to be a state in darktable (good session, bad session). Using the lmmse setup the bad sessions appear  much less.

**Comment by jenshannoschwalm** [comment]
Well, there is something deeply wrong with your system/installation it seems to me. 

Do you have any other automatic presets?

Any hardware tunings? Overclocking? Sufficient power supply?

Both - the whole Nvidia thing and dt are  from system repo for the os version? No other repo souces tried?

**Comment by astmuc** [comment]
The automatic preset was done for the lmmse test only. All other input of mine was done with vanilla presets. 
The system is turn-key, no tinkering, no overclock. 
Nvidia and os are taken from Tuxedo-OS distribution (vendor of the machine), which is a thin layer over ubuntu.
For me its fine to park/close the issue, if it takes too much time on your side.
I will switch off opencl.

**Comment by jenshannoschwalm** [comment]
I am just wandering what could be the issue as there have been no reports like this for years and I have been involved in dt opencl a lot. Atm I really would tip at some os setup.

**Comment by astmuc** [comment]
I enabled pipe-dump for rawprepare,demosaic and exposure and loaded the same picture until i had one case OK and on not OK. The first dump with diffs is demosaic output. Means, my opencl HW and/or driver is wonky and able to deliver different results for the same input. Feel free to close the issue.

**Comment by astmuc** [comment]
The processing settings were applied as specified in screenshot + bicubic for both
interpolator.

One picture was kept in darkroom and demosaic method and HQ mode were changed.

| method                  |effect with HQ| effect without HQ | comment                             |
|-------------------------|--------------|-------------------|-------------------------------------|
| RCD                     |NOK| sometimes OK      | random rows and pattern             |
| PPG                     |NOK| NOK               | HQ on/off each has constant pattern |
| Amaze                   |NOK| OK                | constant pattern                    |
| LMMSE                   |NOK| OK                | constant pattern                    |                                 
| passthrough(monochrome) |NOK| NOK               | 2 constant patterns                 |                                 

As soon as I used a dual method, the effects are shown in lighttable too and stayed like this.

I found dt_interpolation_resample_cl as common code-path and forced the use of CPU fallback, but no avail. 

So, yes i have a local build with intellij/Clion + gcc-12 and can apply changes.

**Comment by astmuc** [comment]
I made another experiment. Before you continue reading (takes probably a few minutes): I am a beginner in opencl and  my idea may be completely off therefore. So, please don't hesitate to say 'thx, no time'.

First the idea: It might be that the allocated (image) CL memory is freed to early. I have an AI assistent license from intellij and asked about this. The chat is 
[chat-3f63b75d-b056-4ea4-9a9b-f0e3aba8d246.txt](https://github.com/darktable-org/darktable/files/14847102/chat-3f63b75d-b056-4ea4-9a9b-f0e3aba8d246.txt)

I tried to shuffle the all the freeing after the CL queue finishes. The patch for this (dirty) code is 
[delay_freeing_of_cl_memory_until_queue_finishes.patch.txt](https://github.com/darktable-org/darktable/files/14847116/delay_freeing_of_cl_memory_until_queue_finishes.patch.txt)

Result is: artefacts are gone with HQ off. I made tests with different demosaic algorithms. But HQ on triggers row-wise smut again.

**Comment by jenshannoschwalm** [comment]
OK, thanks for your tests. Your results in the table strongly hint at something  in CL downscaling as the non CL demosaicers as LMMSE seem to be fine.

Could you please use an image with LMMSE as demosaicer and try many other modules and see if the output stays correct?

Anyway I will check again the code for CL interpolation, maybe there is some sort of roi displacer bug that for some reason only affects your machine.

Could you try to compile with a more recent version of gcc or clang?

BTW, I don't think it's a race condition with clbuffers but will also check that.

Except for compiler bugs I have no idea why this seems to affect only your system, we have so many Nvidia users...

**Comment by astmuc** [comment]
I rebuild with gcc-13 and see no difference.

I loaded my standard test-foto and applied LMMSE (no HQ) -> OK
As before: HQ on results in artefacts again !

Then i added/changed local contrast, tone curve, filmic rgb, rgb levels,rgb curve, sharpen and denoise. The picture stayed clean without HQ. 
A HQ on resulted in a black picture with artefacts. The black appears first with local contrast.

**Comment by gi-man** [comment]
You have a newer card (nvidia 4080), but on older drivers. Whats your Linux kernel version?

**Comment by astmuc** [comment]
```
andreas@andreas-ms7d75:~$ uname -r
6.5.0-10027-tuxedo
```

```
andreas@andreas-ms7d75:~$ ubuntu-drivers devices
== /sys/devices/pci0000:00/0000:00:01.1/0000:01:00.0 ==
modalias : pci:v000010DEd00002704sv0000196Esd000013BBbc03sc00i00
vendor   : NVIDIA Corporation
driver   : nvidia-driver-550-server-open - distro non-free
driver   : nvidia-driver-525 - distro non-free
driver   : nvidia-driver-525-server - distro non-free
driver   : nvidia-driver-535 - third-party non-free recommended <--------------
driver   : nvidia-driver-545-open - distro non-free
driver   : nvidia-driver-535-server - distro non-free
driver   : nvidia-driver-525-open - distro non-free
driver   : nvidia-driver-545 - distro non-free
driver   : nvidia-driver-550-server - distro non-free
driver   : nvidia-driver-535-open - third-party non-free
driver   : nvidia-driver-535-server-open - distro non-free
driver   : xserver-xorg-video-nouveau - distro free builtin
```
So, it is the recommended driver from the standard ppa.

**Comment by astmuc** [comment]
This is my collected information so far
* 4.6.1 and daily (packed from suse build-server) have the issue for me
* nvidia-535 and nvidia-550 have same behaviour
* same for a local build (see [cmake.log](https://github.com/darktable-org/darktable/files/14892213/cmake.log) )
* stress-test of the GPU (10 minutes, 75 degree) with http://wili.cc/blog/gpu-burn.html found no problems
* the problem disappear, if
    * switching cl off 
    * using LLMMSE
    * patching sources, so that module demosiac is not capable to use cl
* they appear with demosaic RCD, PPG and passthrough monochrome
* artefacts show up for the picture mire1.cr2 found in the integration tests also
* integration test-suite with a release build of mine show no CPU-GPU diffs, but CPU-CPU diffs ([test-20240406-054746.log](https://github.com/darktable-org/darktable/files/14892234/test-20240406-054746.log)). They are all red versions of the picture. The diffs looks not like the artefacts.

I agree, that it is not effective to invest in this issue, if there is only one installation affected. Nevertheless, i hope this info may help if it appears elsewhere.

**Comment by jenshannoschwalm** [comment]
@astmuc could you try to:

In src/develop/imageop_math.c Line 192, could you try again with that commented as
 `// if(err == CL_INVALID_WORK_GROUP_SIZE)`

That would make the in-pipe scaling always use the cpu fallback. `-d pipe -d opencl` would be your friend. Please report back !

**Comment by jenshannoschwalm** [comment]
@astmuc i don't unterstand the _exact_ problem (or why/how it seems to affect only you so far) but the common code that might introduce a race condition could be in `data/kernels/demosaic_rcd.cl` functions `rcd_border_green` and `rcd_border_redblue` and how we use the barrier and ensure all data have been processed. (Some problem for other demosaicers ...)

**Comment by astmuc** [comment]
I did not yet get a complete fix for this and maybe my GPU does some VRAM artefacting ( i do not see it elsewhere so far)

But i have some findings:

* the early ClReleaseMemObject calls
* There are kernel which fill a local buffer for their work-group. But at some places the loop is not able to fill the buffer in complete imho. (Please keep in mind: i have limited opencl experience)

E.g. in demosaic_ppg.cl, kernel pre_median

```
  for(int n = 0; n <= maxbuf/lsz; n++)
  {
    const int bufidx = mad24(n, lsz, l);
    if(bufidx >= maxbuf) continue;
    const int xx = xul + bufidx % stride;
    const int yy = yul + bufidx / stride;
    buffer[bufidx] = read_imagef(in, sampleri, (int2)(xx, yy)).x;
  }
```
This will leave some slots untouched when maxbuf is not divisable by lsz (like here). A fix for this could be
```
  const int nchunks = maxbuf % lsz == 0 ? maxbuf/lsz : maxbuf/lsz + 1;
  for(int n = 0; n <= nchunks; n++)
  {
    const int bufidx = mad24(n, lsz, l);
    if(bufidx >= maxbuf) continue;
    const int xx = xul + bufidx % stride;
    const int yy = yul + bufidx / stride;
    buffer[bufidx] = read_imagef(in, sampleri, (int2)(xx, yy)).x;
  }
```
Integration without HQ tests with a change like this in all demosaic kernels show an improvement. The artefacts disappear, but noise like diff appear. But this is OK, if the idea above is correct (and because of HQ odd prob.). Note, i did not check all diff-cl.png visually.

Nevertheless i will probably give up, because the block like artefacts (always 16 like in the picture above), appear again if i enable HQ mode in the integration tests.

**Comment by astmuc** [comment]
Sorry for the bogus post. I will stop at this point ... The effects are too random and always when i think i found something, the next test run breaks again

**Comment by astmuc** [comment]
I close the issue. I finally found a GPU memory test program (https://github.com/GpuZelenograd/memtest_vulkan?tab=readme-ov-file). This indicates an error rate of about 0.00036801% ... Additionally i found screen shots from GPU cards with VRAM issues. These artefacts are very similar to the one of my last screenshot.
You might doublecheck if the timing of the cl memory-release calls is correct.

Big thank you for all your help !

**Comment by jenshannoschwalm** [comment]
I had such an issue some time ago, the power supply died 2 weeks later.
