### ISSUE TITLE
New git clone failing on rawspeed module

### ISSUE THREAD

**Issue by jbinpg** [darktable-org/darktable#16561]
### Describe the bug

Decided to fetch a new git clone of darktable but rawspeed submodule update is failing.

### Steps to reproduce

Began with rm -rf darktable, then git cloned darktable and submodule init. But submodule init failing on rawspeed:

$ git submodule update
Cloning into '/home/jb/darktable_git/darktable/src/external/LibRaw'...
Cloning into '/home/jb/darktable_git/darktable/src/external/OpenCL'...
Cloning into '/home/jb/darktable_git/darktable/src/external/libxcf'...
Cloning into '/home/jb/darktable_git/darktable/src/external/rawspeed'...
Cloning into '/home/jb/darktable_git/darktable/src/external/whereami'...
Cloning into '/home/jb/darktable_git/darktable/src/tests/integration'...
Submodule path 'src/external/LibRaw': checked out '0d011198b2f75ffa3ede51566616b9b2797104e9'
Submodule path 'src/external/OpenCL': checked out '4fdcfb0ae675f2f63a9add9552e0af62c2b4ed30'
Submodule path 'src/external/libxcf': checked out '64efecf63ddd952ccf654e479714aaae6f8c5986'
fatal: remote error: upload-pack: not our ref 8a45bfbb68c43bb977e56da9e371a59ee11f107e
fatal: Fetched in submodule path 'src/external/rawspeed', but it did not contain 8a45bfbb68c43bb977e56da9e371a59ee11f107e. Direct fetching of that commit failed.

### Expected behavior

Unsure if this is a rawspeed fault or something on my end.

### Where did you obtain darktable from?

self compiled

### darktable version

new compile of latest code

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Is it possible that I need to get rid of some git leftovers from my previous compiles?

### Are you using OpenCL GPU in darktable?

None

**Comment by jbinpg** [comment]
Sorry, I meant submodule update failing, not submodule init.

**Comment by kmilos** [comment]
Confirmed, should be pointing to https://github.com/darktable-org/rawspeed/commit/a56970ceb8e1ad76987d1c549bb07c861d65eea3 @LebedevRI

**Comment by LebedevRI** [comment]
@TurboGit i don't suppose there's interest in just completely disallowing direct pushes to the default branch and requiring PR's?

**Comment by LebedevRI** [comment]
Sorry about that, see blurb in https://github.com/darktable-org/darktable/commit/b28b285e77a86a86e9b98c7bdb8c8c0620e8250a#commitcomment-140549316
All good now.
