### ISSUE TITLE
colorEqualizer: color picker values inconsistent to global picker values

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#16573]
### Describe the bug

using global picker and live samples displays the values via lines in the graph if color picker is activated.
picking colors from same areas results in a different line 

### Steps to reproduce

1. select some areas with global color picker and add them to live samples; activate option display samples on image
2. activate color equalizer color picker
3. select areas with local picker
see different indication

https://github.com/darktable-org/darktable/assets/39386816/97900441-bce5-4dab-abdf-f7742ebb5d71

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+870~ga3140d3d78-dirty

### What OS are you using?

Mac

### What is the version of your OS?

macOS 14

**Comment by jenshannoschwalm** [comment]
Right. Not sure yet how to fix.

**Comment by jenshannoschwalm** [comment]
Ok, for now we only support the picker in the module. Live pickers always show signals after processing the pipeline - not module input - thats leading to confusion.

**Comment by jenshannoschwalm** [comment]
Closing this for now..
