### ISSUE TITLE
History stack on fresh imported .NEF Files and removal

### ISSUE THREAD

**Issue by theclosesthing** [darktable-org/darktable#16577]
### Describe the bug

There seems to be a bug with the history stack.
I deleted all xmp files, restarted lightroom importing fresh my RAW .NEF Files.
Then go to darkroom (double-click or pressing 'd'), there is already an history stack.
This seems to be already a bug in my opinion, because i use fresh RAW - files (.NEF).

But the real issue, there is no way to remove this history stack for all my pictures in lighttable view.
Workarround is klick the history stack in darktable view by by klicking on step 0 in the history stack. 
But this is only possible for one image at a time.
'discard history' just doesn´t work and don´t set back the setting like it happens when klicking on step 0 manually. Discard history just does nothing.

This is a bug, discard history should really discard all the history, like when i press on step 0 in the history stack in darkroom view.

Picture of the stack after i deleted the .xmp file and imported the .NEF RAW file without applying any steps. There should be no steps and if so it should be possible to batch-delete.
![history_stack](https://github.com/darktable-org/darktable/assets/63181638/c2ae7a69-db1d-4f28-89e4-b904c1a31add)

### Steps to reproduce

Import fresh RAW files. 
Check there are already some setting. Try to batch-delete via history stack. Doesn´t work :( 

### Expected behavior

history stack removal (in lighttable) deletes the history stack

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Mac

### What is the version of your OS?

Sonoma 14.2.1

### Describe your system?

Macbook Air with M1

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by jenshannoschwalm** [comment]
Please read the manual about the history stack, this works exactly as designed. All modules intended for the setup workflow or required by image type are activated and shown in history.

**Comment by ralfbrown** [comment]
Every other raw processor applies the equivalent of those steps by default, they just don't show you that they've done so.  Without steps 1-5,  it isn't even possible to display an image from a raw file at all.

**Comment by pehar1** [comment]
> It makes impossible to transfer white balance settings between pictures.

This is of course possible. The use of "white balance" and "color calibration" to achieve consistent color matching across a series of images has been discussed several times for example in the forum [pixls.us](https://discuss.pixls.us/c/software/darktable/19) and there are videos that explain the procedure.

> I always get strange results.

You did not describe what you did when you got "_strange results_", so that is not comprehensible. You can copy the history stack (or parts of it). Be aware there are two different modes : "_append_" and "_overwrite_". And please : read the manual !

> A "delete history" setting which doesn´t delete the history is a bug

 The manual clearly describes the functionality of this button :

> Click the “reset parameters” button in the module header to discard the entire history stack **and reactivate any default modules**. This can also be achieved by selecting the “original image” history item and clicking “compress history stack”.
