### ISSUE TITLE
rawspeed: Cannot compile with CLang 16.

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#16576]
The configuration is ok, I have clang 16 which is supported, but during the build I have many issues like those:

```
...src/external/rawspeed/src/librawspeed/decompressors/../io/Endianness.h:95:17: error: no member named 'bit_cast' in namespace 'std'
  auto i = std::bit_cast<uint64_t>(d);
           ~~~~~^
...src/external/rawspeed/src/librawspeed/decompressors/../io/Endianness.h:95:26: error: unexpected type name 'uint64_t': expected expression
  auto i = std::bit_cast<uint64_t>(d);
```

@LebedevRI : Any idea ?

**Comment by LebedevRI** [comment]
> The configuration is ok, I have clang 16 which is supported, but during the build I have many issues like those:

Can you show full cmake+make output starting with newly-created build directory?

**Comment by LebedevRI** [comment]
> The command on a Debian-11 box:

That's debian oldstable, not debian stable, we don't support that.

https://www.debian.org/releases/:

> The current stable distribution of Debian is version 12, codenamed bookworm. It was initially released as version 12.0 on June 10th, 2023 and its latest update, version 12.5, was released on February 10th, 2024.

**Comment by kmilos** [comment]
> Maybe I'm missing a package as libstdc++ is too old !

There's a a whole [bunch of llvm-toolchain packages](https://packages.debian.org/source/oldstable/llvm-toolchain-16) to [update](https://github.com/darktable-org/darktable/pull/16578/files), not just clang-16.

**Comment by LebedevRI** [comment]
> > Maybe I'm missing a package as libstdc++ is too old !
> 
> There's a a whole [bunch of llvm-toolchain packages](https://packages.debian.org/source/oldstable/llvm-toolchain-16) to [update](https://github.com/darktable-org/darktable/pull/16578/files), not just clang-16.

That won't quite work. You'd need to update libstdc++-dev package.
The alternative is to use libc++, but since debian uses libstdc++,
that probably won't work either since then you end up with two different C++ STD libraries linked in.

I've wanted to post something funny on April 1'st about finally getting myself out
of the ongoing standstill by porting to Fortran, but maybe i really should just give up
and RIIR.
