### ISSUE TITLE
Contrast-brightness-saturation

### ISSUE THREAD

**Issue by szlali7** [darktable-org/darktable#16589]
**Please let "contrast brightness saturation" module be available again among the active modules.
It should be available to set on the quick access panel again.
This is the mostly used module for me and I cannot reproduct the same effect with the suggested "color balance rgb" module.
Darktable is the only one photo editor software I use and I was so happy to have an universal tool for picture editing.
The most cases the "contrast brightness saturation" covered the most of my need and now I cannot reach the same effect with the alternative methods.
Thanks  a lot for this great job developing Darktable for us!
Regards.
Lajos**

**Comment by gi-man** [comment]
In Pixls.us post you also did, share a raw image with the previous edit/look you want and ask folks how to archive the same results with the color balance rgb. I'm sure they can guide you.

**Comment by ralfbrown** [comment]
The "brightness" control in CBS is exactly the same as the middle (gray) control in RGB levels, a gamma adjustment.

**Comment by victoryforce** [comment]
@szlali7 From what I see in your pixls.us forum thread, you seem to have solved the problem of getting good results by other means? Can we close this issue?
