### ISSUE TITLE
Darktable Won't Open

### ISSUE THREAD

**Issue by loueyjay** [darktable-org/darktable#16590]
### Describe the bug

Darktable won't open. A black command box flashes up for a second before disappearing, and then nothing happens. I've tried opening using darktable.exe, uninstalling/reinstalling, still can't get it to open.

### Steps to reproduce

1. Click Darktable in Start Menu
2. Darktable should open
3. Empty command box opens before closing after 1 second
4. Nothing happens

### Expected behavior

Open

### Logfile | Screenshot | Screencast

========================================
version: darktable 3.8.1
start: 2024:04:07 11:05:27

ERROR : cannot open database
========================================
version: darktable 3.8.1
start: 2024:04:07 11:15:52

ERROR : cannot open database

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

10.0.19045 Build 19045

### Describe your system?

Lenovo, bit of an old laptop but was all working fine until 2 days ago.

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

na

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

na

**Comment by loueyjay** [comment]
Sorry I uninstalled old version after that log file, since installed the latest version:

C:\Program Files\darktable\bin>darktable --version
this is darktable 4.6.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.
Lua support enabled

darktable-cltest:

darktable 4.6.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.2410 [dt_get_sysresource_level] switched to 1 as `default'
     0.2444   total mem:       3954MB
     0.2467   mipmap cache:    494MB
     0.2486   available mem:   1977MB
     0.2505   singlebuff:      30MB
     0.2682 [opencl_init] opencl disabled via darktable preferences
     0.2743 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded, preference 'default path'
     0.3987 [opencl_init] found 1 platform
     0.3996 [check platform] platform 'Intel(R) OpenCL' with key 'clplatform_intelropencl' is NOT active
[opencl_init] found 0 device
     0.4030 [opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.

**Comment by gi-man** [comment]
Ok, you are in the latest version and it is not an openCL issue. Can you use `cmd` to start darktable with `darktable -d common` to generate a log? Please use pastebin or attach a txt file.

**Comment by loueyjay** [comment]
Ok, what should I type? I'm new to cmd. I've got C:\Program Files\darktable\

**Comment by gi-man** [comment]
The same as you did here:
C:\Program Files\darktable\bin>darktable --version

but with
C:\Program Files\darktable\bin>darktable -d common

The logfile is saved in a hard to reach spot in windows. See here for logfile location: https://www.darktable.org/about/faq/#faq-windows-logs

**Comment by loueyjay** [comment]
[darktable-log.txt](https://github.com/darktable-org/darktable/files/14907440/darktable-log.txt)

Not sure C:\Program Files\darktable\bin>darktable -d common worked as nothing seemed to happen. Found the log though

**Comment by gi-man** [comment]
It looks like your data.db file is corrupted. 

Go to C:\Users\louey\AppData\Local\darktable and rename the current data.db to data.old. Then you will find other data snp file in there. Those are snapshot/backups that datktable makes at some frequency. Copy those to a safe place and then rename the latest one to data.db.

**Comment by loueyjay** [comment]
Ok, just the data snp files or library snp files too?

**Comment by gi-man** [comment]
Let's try data only first. That's the one currently giving you an issue. If then we get library, then we can deal with it.

**Comment by loueyjay** [comment]
Ok done

**Comment by gi-man** [comment]
So it is working? We can close the issue?

**Comment by gi-man** [comment]
Delete or rename to data.old. Then rename a snap one to data.db

**Comment by loueyjay** [comment]
Ye still not opening

**Comment by loueyjay** [comment]
[darktable-log.txt](https://github.com/darktable-org/darktable/files/14907940/darktable-log.txt)

**Comment by gi-man** [comment]
Hmm, same message. Do you have an antivirus that could be blocking darktable?

**Comment by loueyjay** [comment]
I haven't changed any antivirus software, but only the last 2 days I've had this problem.

**Comment by loueyjay** [comment]
![darktable](https://github.com/darktable-org/darktable/assets/166386278/19d19385-4bb8-4d0e-b9de-294b02f36654)

I did the same for the lib files & got this message when trying to open darktable

**Comment by gi-man** [comment]
Press upgrade. This means that this version of data.db is older. 

If it continues to give you problems, I think you should look into a recent windows update or antivirus blocking darktable.

**Comment by victoryforce** [comment]
@loueyjay Did you upgrade your database?

**Comment by ralfbrown** [comment]
No further response from OP in over two months, assuming the problem was resolved.
