### ISSUE TITLE
Unable to close drawn path mask , using either tablet & stylus, or trackpad

### ISSUE THREAD

**Issue by EmmJSee** [darktable-org/darktable#16597]
### Describe the bug

When creating a drawn path using a tablet & stylus or trackpad, I am unable to close the path. I am using the right-click of the trackpad and the stylus also has a right-click button assigned.

This understandably makes editing images very difficult. The image I’m currently editing is very monochrome in colour (clouds against snow-capped mountains, so parametric masks don’t really work.

V4.6 on the latest macOS.

### Steps to reproduce

Select “Drawn mask” in a module. Use the tablet & stylus or trackpad to begin the meal creation (using the drawn vector path tool). This works fine until I want to finish the mask. Then clicking on any buttons assigned to “right-click” fail to close the mask.

### Expected behavior

The drawn vector mask shape should close

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Mac

### What is the version of your OS?

macOS 14.4.1 (Sonoma)

### Describe your system?

Mac Mini M2 16GB Ram, 256GB NMVE OS /application dune, and 2TB Samsung NMVE Thunderbolt drive. Apple trackpad (v1).  XP-Pen Deco tablet & stylus 

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by zisoft** [comment]
> When creating a drawn path using a tablet & stylus or trackpad, I am unable to close the path.

I cannot reproduce that on my Mac.

The trackpad closes the path with the right-click gesture (two finger click).
The top button of the stylus of my Wacom Intuos Pro S tablet is configured as right-click and this works as well without problems.

**Comment by EmmJSee** [comment]
Two-finger click. Ah. Okay. My apologies. I’ll try that.

**Comment by EmmJSee** [comment]
That resolved the issue. The tablet & stylus seems to be a bug with the driver.

thanks for your help.
