### ISSUE TITLE
rotate and perspective highlight artefacts

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#16608]
### Describe the bug

Strange highlight artefacts appear on some images if _rotate and perspective_ is used to rotate the image.

### Steps to reproduce

Download the raw and its XMP from http://tech.kovacs-telekes.org/files/2024-04-11-rotate-and-perspective-highlight-issues/, open it in the darkroom.
Select history entry 30:
![history30-rotate-and-perspective-off](https://github.com/darktable-org/darktable/assets/3177739/28ca77aa-34d7-42f0-8fd4-4a54f60ade71)
Select history entry 31:
![history31-rotate-and-perspective-on](https://github.com/darktable-org/darktable/assets/3177739/4a59f15f-e5b3-4f0a-88ea-0d0514b48e9f)

Affects both _filmic_ and _sigmoid_ (see history entry 33). With/without OpenCL. Zoomed-in view as well as zoomed out. The exported JPG is also affected.

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+909~gcaa592293e

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

XOrg
Ryzen 5 5600X, 64 GB RAM
GTK 3.24.38
GCC 13.2.0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 with 6 GB, driver 535.161.07 (the CPU path is also affected)

**Comment by jenshannoschwalm** [comment]
@kofa73 the problem seems to be "somewhere else". First test show the artifacts are introduced in the first instance of D&S, seems be be related to a combination of a) feathering b) details threshold c) no-cropping in rotate&perspective. Will investigate further (btw i can see "feathering blocky artifacts" here, it helps to use `darkroom/ui/develop_mask=TRUE` to visualize this.

**Comment by jenshannoschwalm** [comment]
Even after the fix in above PR we still have a "strange looking" spot at that burned-out part. For those running into this issue, it's related to not-cropping in the rotate&perspective module. So we have the completely black border pretty close, that's affecting the guided filter.

**Comment by sans-c** [comment]
> Even after the fix in above PR we still have a "strange looking" spot at that burned-out part. For those running into this issue, it's related to not-cropping in the rotate&perspective module. So we have the completely black border pretty close, that's affecting the guided filter.

I am indeed seeing artifacts as of today. Is there a workaround? How is it "Fixed in master" when it is actually not?

**Comment by jenshannoschwalm** [comment]
@sans-c please open a "precise" & proper issue if you really think there is something wrong.
