### ISSUE TITLE
Metadata IPTC "IPTC.Application2.TransmissionReference"

### ISSUE THREAD

**Issue by fredjoncour** [darktable-org/darktable#16600]
Hello,
The IPTC field equivalent to "Function identifier" (found in Lightroom) doesn't seem to be implemented in Darktable, which is rather annoying when you need to send batches of images to a professional image bank. This identifier is used to classify images by subject. In The Gimp, this identifier is called "IPTC.Application2.TransmissionReference" (task identifier).

Would it be possible to make this field editable in Darktable? I'm attaching an image with this identifier filled in with the words "Mes petits bouts de Provence".

Thank you very much.
Frédéric

![006807_2022-01-06-0002_070122083351](https://github.com/darktable-org/darktable/assets/166613702/78e197c8-9ca6-42a5-8393-b142a84ee48c)

**Comment by zisoft** [comment]
This can be accomplished by the _darktable way_.
Please read this very interesting comment: https://github.com/darktable-org/darktable/issues/7866#issuecomment-761086912

So to get what you want, create a hierarchical tag structure:

```
Jobs|This is job 1
Jobs|This is job 2
...
```

and assign the tags to the related images.

In export options define the `IPTC.Application2.TransmissionReference` to be filled with `$(CATEGORY0(Jobs))`:

![Bildschirmfoto 2024-04-16 um 18 22 20](https://github.com/darktable-org/darktable/assets/4083281/f52f67f1-2d0e-438c-af88-ded6e5c941f9)

This means that `IPTC.Application2.TransmissionReference` get filled with the first hierarchy tag of catagory `Jobs`.
Now export your images and find:

```
exiv2 -p i -g Transmission img_test.jpg
Iptc.Application2.TransmissionReference      String     13  This is job 1
```

This way gives you the advantage to easily get all images of a job by just using the collection filters.
