### ISSUE TITLE
Export IPTC metadata

### ISSUE THREAD

**Issue by fredjoncour** [darktable-org/darktable#16619]
Hello,
As part of a professional project, I need to export my keywords using the IPTC protocol. I've worked out how to do this for the title, description and keywords (export module). Unfortunately, as far as the keywords are concerned, the export is not complete, as the synonyms of the keywords are not exported. However, keyword synonyms are an important feature for photographers like me who license their rights through professional image banks, as they allow you to organise and enrich your images in a significant way.

In the export module I used the IPTC variable iptc.Application2.keywords to attach it to $TAGS. Despite this, the keyword synonyms are not present in the exported image, only the simple keywords.

Do you have enough time to modify the expected result?
Thank you very much in advance for your dedication.
Frédéric

**Comment by zisoft** [comment]
Cannot reproduce on current master.

First I created a tag with a synonym:
![image](https://github.com/darktable-org/darktable/assets/4083281/94edc899-6261-4a43-8aab-d39ab9ab737c)

Then I set the export options as you described:
![image](https://github.com/darktable-org/darktable/assets/4083281/000c6ece-b089-4079-aec7-41de08941a9c)

After the export the image contains the iptc tags:

```
$ exiv2 -p i IMG_6558.jpg
Iptc.Application2.Keywords                   String     12  Synonym-Test
Iptc.Application2.Keywords                   String      4  Test
```

**Comment by fredjoncour** [comment]
YESSSSSSS, it's working!!! I'm so sorry to have wasted your time! Many thanks !!!
Frédéric
