### ISSUE TITLE
Compilation error: Cannot find OpenMP_C on macOS

### ISSUE THREAD

**Issue by JeanGrng** [darktable-org/darktable#16612]
### Describe the bug

I am attempting to compile Darktable from source on my MacBook Pro using the build.sh script provided in the repository. Despite following the installation instructions, I am encountering an error related to OpenMP during the CMake configuration phase.

### Steps to reproduce

Run the following command:
`./build.sh --prefix /opt/darktable --build-type Release --install --sudo
`

### Expected behavior

The script should compile Darktable without any errors and complete the installation process.

### Logfile | Screenshot | Screencast

During the configuration process, CMake fails with an error indicating that it cannot find OpenMP_C, stating that OpenMP_C_FLAGS and OpenMP_C_LIB_NAMES are missing and that OpenMP version 4.5 or later is required.

Error :
```
CMake Error at /opt/homebrew/Cellar/cmake/3.29.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
  (Required is at least version "4.5")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.29.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.29.1/share/cmake/Modules/FindOpenMP.cmake:581 (find_package_handle_standard_args)
  CMakeLists.txt:90 (find_package)
```

### Where did you obtain darktable from?

GitHub nightly

### darktable version

d83cbc2

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14.2.1 Sonoma 

### Describe your system?

OS: macOS
CMake version: 3.29.1
Installation method: Homebrew

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment]
What package manager are you using? Homebrew or MacPorts?

Each has its own build instructions, please see the descriptions in `packaging/macosx` on how to install the dependencies and to build darktable.

**Comment by zisoft** [comment]
You most likely forgot to link the keg-only packages:

```
brew link --force libomp
brew link --force libsoup@2
```

**Comment by JeanGrng** [comment]
Thanks for the help, @zisoft. The issue was with the libomp library on my system. After running brew link --force libomp, the error resolved, and the compilation succeeded. Appreciate your guidance!

**Comment by zisoft** [comment]
Don't forget to also link libsoup@2 which is needed for the darktable map module.
