### ISSUE TITLE
field "changed_timestamp" not found for type dt_lua_image_t

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#16623]
### Describe the bug

[Documentation](https://docs.darktable.org/lua/stable/lua.api.manual/types/dt_lua_image_t/) says `changed_timestamp`, but it is actually `change_timestamp`.

### Steps to reproduce

```
local dt = require "darktable"
print(tostring(dt.database[1]))
print(tostring(dt.database[1].exif_datetime_taken))
print(tostring(dt.database[1].changed_timestamp))
```

### Expected behavior

Script should work based on documentation.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Either the API needs to rename its variable, or the documentation needs to fix the name.

**Comment by wpferguson** [comment]
The field name is `change_timestamp`

**Comment by wpferguson** [comment]
documentation updated.
