### ISSUE TITLE
Getting strange artifacts when applying certain noise reduction

### ISSUE THREAD

**Issue by oldblackcrow** [darktable-org/darktable#16634]
### Describe the bug

When I apply a noise reduction, like Denoise Profiled, I get strange artifacts as seen in this image. If I turn off the noise reduction filter, the artifact goes away. However, the artifacts do not show up in any exported image. 

![image](https://github.com/darktable-org/darktable/assets/45359956/7b1d9b45-a1fc-4d99-b798-3c3d5e0c85c4)

### Steps to reproduce

1. open a RAW image.
2. apply various noise filters.
3. depending on something, strange, colorful artifacts appear only within DarkTable.

### Expected behavior

Noise reduction should just reduce noise (or not) but should not show artifacts.

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/45359956/f5461eed-87b1-43d9-b4ab-1b3eb88e8028)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home Edition

### Describe your system?

Laptop with the following:
11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz   3.00 GHz
20.0 GB (19.7 GB usable)
64-bit operating system, x64-based processor
Touch support with 10 touch points

### Are you using OpenCL GPU in darktable?

None

**Comment by oldblackcrow** [comment]
Windows 11 Home Edition Version: 23H2
Build: 22631.3447

**Comment by jenshannoschwalm** [comment]
We would want the raw and xmp file to investigate.

**Comment by oldblackcrow** [comment]
I tried sending you the raw file but it is too big... even with zipping it.
Do you have another way for me to send it? Thanks!

**Comment by jenshannoschwalm** [comment]
Some file sharing service?

**Comment by oldblackcrow** [comment]
Okay... sorry about that!

Here's the link to my Google Drive
https://drive.google.com/drive/folders/1sz1Z3LNw4YJ_kOmQ13eSJ0XPI7y2m2JE?usp=sharing

Thanks again!

**Comment by jenshannoschwalm** [comment]
Got both files, so you are into astro photos?

Can't reproduce here on master. There is some heavy noise involved and i would say your numerous denoise modules will certainly fight with each other and could possibly not improve output any longer but such artifacts, no.

Can you confirm that **the only module** involved is "profiled denoise"? If so, what happens if you change internal parameters of algo?

Would you be able to produce a video of your dt window?

**Comment by ptilopteri** [comment]
* Hanno Schwalm ***@***.***> [04-20-24 10:16]:
> Got both files, so you are into astro photos?
> 
> Can't reproduce here on master. There is some heavy noise involved and i would say your numerous denoise modules will certainly fight with each other and could possibly not improve output any longer but such artifacts, no.
> 
> Can you confirm that **the only module** involved is "profiled denoise"? If so, what happens if you change internal parameters of algo?
> 
> Would you be able to produce a video of your dt window? 


I also tried sub image and increased to %400 but only oddity I see is
pixelation.

openSUSE Tumbleweed 20240418
dt 4.7.0+981~g63cf4e6d9b



-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by ralfbrown** [comment]
Not reproducible and no further response from original poster in over seven months.
