### ISSUE TITLE
Om 1 Mark 2 2024

### ISSUE THREAD

**Issue by achsbruch** [darktable-org/darktable#16630]
Bitte fügen Sie Unterstützung für die neue OM-1 Mark2 hinzu. Habe eine Raw bereits eine Raw Datei raw.pixl.us hochgeladen. 
https://raw.pixls.us
![P3220022](https://github.com/darktable-org/darktable/assets/167216901/ec438add-775a-4ddf-88c5-cbbe280309ee)

**Comment by achsbruch** [comment]
Ich hoffe ich habe alles richtig gemacht.

**Comment by LebedevRI** [comment]
We already have a full sample set for `OM-1MarkII`, and that camera is supported.

**Comment by LebedevRI** [comment]
Duplicate of #16297.
Because the support was added after 4.6.1 was released.

(i'm not sure what gives an idea that non-English language is best to use on clearly-English project.)

**Comment by achsbruch** [comment]
Sorry for using German. Unfortunately I don't speak English and am now using a translator. Can you tell me when an update will be released? Or if a new version has already been released. Regards JohannAm 16.04.2024 20:34 schrieb Roman Lebedev ***@***.***>:
Duplicate of #16297.
Because the support was added after 4.6.1 was released.
(i'm not sure what gives an idea that non-English language is best to use on an clearly-English project.)

**Comment by achsbruch** [comment]
Thank you for the information. I will wait until the new version is released. Thanks again for your help. Regards, JohannAm 16.04.2024 20:49 schrieb Roman Lebedev ***@***.***>:
The support was just added to git master branch in c7dae21,
so unless you are comfortable with using development version by either building from the source,
or using prebuilt snapshots (e.g. https://software.opensuse.org//download.html?project=graphics%3Adarktable%3Amaster&package=darktable),
I think the next release this will make it into is the next major release in summer, i think.
