### ISSUE TITLE
GoPro Fusion 360

### ISSUE THREAD

**Issue by bratsk360** [darktable-org/darktable#16646]
Hi! Sample was uploaded. I guess it must be there. I've done it month before but still nothing in base.

**Comment by ptilopteri** [comment]
* bratsk360 ***@***.***> [04-19-24 10:42]:
> Hi! Sample was uploaded. I guess it must be there. I've done it month before but still nothing in base. 
> 

"base" as you call, is only published several times a year.  If you want
to use updated support issues, install master.  there are nightly versions
or build for yourself.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by kmilos** [comment]
GPRs should already be supported.

Are you facing any particular issues?

**Comment by bratsk360** [comment]
Ok, fine.

**Comment by LebedevRI** [comment]
@bratsk360 thank you for contributing the sample set. I’ve now verified it.

As noted on https://discuss.pixls.us/t/raw-samples-wanted/5420/184?u=lebedevri,
It’s my fault, the signal-to-noise ratio with new uploads, by now,
has become abysmally low, so the sample review process
is grinding to a halt. I need to look into redesigning
the admin view of RPU, to improve the situation…
