### ISSUE TITLE
Failed to read camera white balance information / Sony ILCE-7M4

### ISSUE THREAD

**Issue by tdausner** [darktable-org/darktable#16653]
### Describe the bug

After import from SD card double-clicking on a photo results in error message "Failed to read camera white balance information from (image file name)".

- camera is a brand new Sony ILCE-7M4 (software revision 2.01) - supported as of https://www.darktable.org/resources/camera-support/
- darktable 4.6.1
- Compile options:
 ```
 Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> DISABLED
  libjxl                 -> DISABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED
```

### Steps to reproduce

1. import files
2. double click one file
3. error message instead in darkroom and switch back to lighttable

### Logfile | Screenshot | Screencast

```
$ darktable 
     0.0042 [l10n] error: can't open iso-codes file `/snap/gnome-42-2204-sdk/current/usr/share/iso-codes/json/iso_639-2.json'
                   there won't be nicely translated language names in the preferences.
Gtk-Message: 20:32:05.998: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try
[2024-04-18_22-08-55_0008.zip](https://github.com/darktable-org/darktable/files/15044548/2024-04-18_22-08-55_0008.zip)
 to not load it.
     0.0240 [init] moving database into new XDG directory structure

(darktable:98290): Gtk-WARNING **: 20:32:06.127: Theme parsing error: gtk.css:1:21: Failed to import: Error opening file /home/thomas/snap/darktable/216/.config/gtk-3.0/colors.css: No such file or directory
Gtk-Message: 20:32:06.140: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 20:32:06.141: Failed to load module "colorreload-gtk-module"

(darktable:98290): IBUS-WARNING **: 20:32:06.248: Failed to mkdir /home/thomas/snap/darktable/216/.config/ibus/bus: Not a directory

(darktable:98290): GLib-GIO-WARNING **: 20:32:06.423: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
     0.4665 [lib_load_module] failed to open `gamepad': libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
    19.0249 [rawspeed] (2024-04-18_22-08-55_0008.ARW) void rawspeed::ArwDecoder::DecodeLJpeg(const rawspeed::TiffIFD*), line 306: Unsupported photometric interpretation: 6
    19.0249 [libraw_open] extensions whitelist: `cr3'
    19.0250 [qoi_open] no proper file header in /home/thomas/Bilder/Fotos/2024/2024-04-18 Test SONY A7M4 im Hallenbad /2024-04-18_22-08-55_0008.ARW
    19.0275 [temperature] failed to read camera white balance information from `2024-04-18_22-08-55_0008.ARW'!
    19.0276 [temperature] failed to read camera white balance information from `2024-04-18_22-08-55_0008.ARW'!
    19.2908 [temperature] failed to read camera white balance information from `2024-04-18_22-08-55_0008.ARW'!
    19.2909 [temperature] `Sony ILCE-7M4' color matrix not found for image
    19.2909 [temperature] failed to read camera white balance information from `2024-04-18_22-08-55_0008.ARW'!
    19.2996 [colorin] could not find requested profile `standard color matrix'!
```

[2024-04-18_22-08-55_0008.zip](https://github.com/darktable-org/darktable/files/15044553/2024-04-18_22-08-55_0008.zip)

### Where did you obtain darktable from?

distro packaging

### darktable version

snap: darktable                    4.6.1                       216       latest/stable    sergiusens 

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

```
Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-27-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
Memory: 58.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 21K9002HGE
System Version: ThinkPad P16s Gen 2
```

```
$ gtk-launch --version
3.24.38
```

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by ralfbrown** [comment]
What compression mode is the camera set to use?  Not all of the newest compression modes are supported....

**Comment by tdausner** [comment]
Camera is set to compression mode RAW-s (loss free compression)

Am Freitag, dem 19.04.2024 um 19:34 -0700 schrieb Ralf Brown:
> What compression mode is the camera set to use? Not all of the newest
> compression modes are supported....
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
---
Thomas Dausner
Binger Straße 65
56154 Boppard
Phone: +49-151-598-56154

**Comment by ptilopteri** [comment]
can you provide a couple of the failing raw files on a file sharing site?

**Comment by victoryforce** [comment]
> Camera is set to compression mode RAW-s (loss free compression)

Such files (downsized lossless ARWs) are not supported. This is clearly written in the [release notes](https://github.com/darktable-org/darktable/releases/tag/release-4.6.1) (look for the Missing Compression Mode Support section).

**Comment by kmilos** [comment]
Loss should be supported since 4.6.1

**Comment by lkarcz** [comment]
> Lossless should be supported since 4.6.1 - L size only though, not M nor S.

@kmilos aaaaaand... any plans / possible dates for M/S support?

**Comment by tdausner** [comment]
@victoryforce thank you for clearance.
@other  release notes  say: "Missing Compression Mode Support -> Sony downsized lossless ARWs ("M" for full-frame, "S" for full-frame & APS-C)"
I'll set my camera to "no compression". The (few) images taken with compression are accepted by darktable after conversion with Adobe DNG converter :smile:

**Comment by lkarcz** [comment]
> Tracked by [darktable-org/rawspeed#442](https://github.com/darktable-org/rawspeed/issues/442)
> 
> Note that you don't have to turn compression completely off, just stick to "L".
> 
> @lkarcz I personally have no plans for this. For all I know, maybe you're working on a patch!

I wish I was able to... As for now, GH ticket is all I can make ;)
