### ISSUE TITLE
Color picker behaves odd [1/2 = start-, end point not steady]

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#16660]
### Describe the bug

When using the color picker e.g. in colorcalibration (but not limited hereto), the starting point is moving, the end point is not sticking to the mouse --> this is THIS issue
---and clicking on the an edge again causes to restart but being able to re-adjust --> this is ANOTHER issue and I will likely provide another report (I figured while testing). At least I will do separate bisecting.

While I type here, I realize it is two bugs. re-adustment and the not steady start/endpoint....

And it is getting more complex, because commit e218b77121-dirty is o.k. when starting top-left or bottom right but not o.k. when starting top-right or bottom-left

Git bisect gave me:
`
e2042d91ece193e009d5837648038191e8986c75 is the first bad commit
commit e2042d91ece193e009d5837648038191e8986c75
Author: hanno@schwalm-bremen.de <hanno@schwalm-bremen.de>
Date:   Thu Mar 28 20:11:09 2024 +0100

    Make pickers position relative to image input
    
    The pickers box and point positions are now relative to image input.
    This allows the pickers to follow all distorting modules like crop, ashift and lens.

 src/develop/pixelpipe_hb.c   |  56 +++++------
 src/gui/color_picker_proxy.c |  50 ++++++++--
 src/views/darkroom.c         | 221 ++++++++++++++++++++++++++++---------------
 3 files changed, 213 insertions(+), 114 deletions(-)

`
@jenshannoschwalm may I ping you here

### Steps to reproduce

1. go to darkroom
2. open e.g. color calibration
3. click on color picker and move around
4. see screencast

### Expected behavior

behave as before. Start- and endpoint behave reliably and corners can be used to re-adjust

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/49004103/c9804906-c98a-49a2-ac38-44e3543483e2

### Commit

e2042d91ece193e009d5837648038191e8986c75

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.7.0-841-ge2042d91ec and up to current master

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

* darktable version : 4.7.0-841-ge2042d91ec
* OS                : Linux - kernel 6.8.7-gentoo
* Distro            : Gentoo Base System release 2.14
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : NVIDIA GeForce GTX 1060 6GB
* Graphics card1    : NVIDIA GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-550.67
* OpenCL installed  : Yes (opencl-headers-2023.04.17)
* OpenCL activated  : Yes
* Xorg              : xorg-server-21.1.13
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.41
* gcc               : 13.2.1_p20240210
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

please see system description

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I didn't try with fresh .config or history as it was so clearly bisectable

**Comment by jenshannoschwalm** [comment]
Checked this; principally this is due to the way we calculate the picker coordinates now, as they are defined in image-coordinates (and not output in canvas) they are expected to be approximated depending on active distorting modules in the pipe (mostly it will be lens and/or rotate&perspective). I checked that the input-coordinates of the picker are definitely correct, still investigating if we can make this "moving around" less "annoying".

**Comment by AxelG-DE** [comment]
Darned I didn't do the check with discarded history, otherwise we would maybe find it earlier
- discarded history, the effect is almost gone
- only the resize is super sensitive on the top left corner (at least on my first try) but the others work almost o.k.
- I think that is related, as with those coordinate-topic, likely the click is outside the corner-box and the tool considers a restart

Especially for my Olympus with the 15mm lens I apply the lens correction automatically as the distortion is huge (I do autoapply for many other lenses on my Nikons as well).

I used several pictures but the one with "The Palm" logo I will attach here inkl. xmp:
[EM50314.zip](https://github.com/darktable-org/darktable/files/15051207/EM50314.zip)

**Comment by AxelG-DE** [comment]
Hehehe, 

reading the comment in the commit "_This allows the pickers to follow all distorting modules like crop, ashift and lens._" , from my users-perspective it looks like opposite atm :smile: 

To me it was working nice before that change :-)

me hides :)

**Comment by jenshannoschwalm** [comment]
Try to apply a picker. Either area or point and possibly live pickers. Now rotate the image, crop or lens on/off. Pickers will stay at position. That's what the pr was about.

**Comment by AxelG-DE** [comment]
This issue is almost not noticeable on my D750 NEF but #16661 is

**Comment by AxelG-DE** [comment]
> Try to apply a picker. Either area or point and possibly live pickers. Now rotate the image, crop or lens on/off. Pickers will stay at position. That's what the pr was about.

internet-speach "no front" was missing.
Especially for you it is very obvious, that you know, what you are doing :)

**Comment by AxelG-DE** [comment]
I found out what made it more ugly/stonger...
rotate and perspective 
- automatically analyse line structure
- automatically correct vertical perspective distortion

**Comment by AxelG-DE** [comment]
https://github.com/darktable-org/darktable/assets/49004103/3d2e7fac-af86-473d-9390-317dc62490eb

@jenshannoschwalm did not wait for your yes/no for screen recording :-)

**Comment by jenshannoschwalm** [comment]
In short, this is the price for the pickers defined on input space. 

The big advantages are, 1) pickers drawn will always show the area they really use. Also for the modules pickers. 2) pickers will stay at their position if image is cropped or rotated or whatever.

**Comment by AxelG-DE** [comment]
Maybe it is not that visible, but the moment I click, this corners they still stay but once I move the mouse, that endpoint jumps unpredictably. It is really annoying, especially I do rotations and crop at early beginning of the editing

From my users perspective, I could easier live (for the time being until  is saw the consequences) with  a slight inaccuracy rather  than this behaviour which makes it really hard for me to adjust the frame :-/

**Comment by Jiyone** [comment]
Couldn't the mouse's coordinate be translated to input coordinate so it would be coincident with box handles ? 🤔 🤷🏻‍♂️

**Comment by AxelG-DE** [comment]
and here is another video, where I try to add a path and drag the nodes but it behaves similar. In that picture, I did not have lens correction or rotation yet, only crop

https://github.com/darktable-org/darktable/assets/49004103/fc8184d6-7876-41ee-a969-07b2dc343bbe

@jenshannoschwalm is is another issue or the same things?

**Comment by jenshannoschwalm** [comment]
@AxelG-DE not related.

**Comment by jenshannoschwalm** [comment]
@Jiyone and @AxelG-DE mouse coordinate back to image coordinates is no problem as you see for point picker.

But, you want a visible rectangle with fixed handles backtransformed to some rectangle in module xyz? Until the new pickers we took rectangle data from some module but the shown box was not the box taken by picker in module. Global pickers were fine btw.

**Comment by AxelG-DE** [comment]
> @Jiyone and @AxelG-DE mouse coordinate back to image coordinates is no problem as you see for point picker.
> 
> But, you want a visible rectangle with fixed handles backtransformed to some rectangle in module xyz? Until the new pickers we took rectangle data from some module but the shown box was not the box taken by picker in module. Global pickers were fine btw.

What I would highly appreciate is, picking the corners and start moving the mouse, then the corner shall stick to my mouse and not jump far away and usually outside of my visible area which forces me to release, zoom-out and start the action again. This really annoys me as it hits me nearly every edit. If it is up to me, I would rather revert to what we had before (sorry to say like this and even I appear ignorant to the benefits, which I maybe never faced it before).

Just now I hit another thing I donno is related or not...
if I click the eye-dropper (most of the time filmix and colorCal) and the frame is not within my visible range, then sometimes I can do a right click (regardless inside or outside that frame) and it automatically re-set to the visible part of my picture (with a certain amount of distance to the border). But every now and then this does not work anymore....

**Comment by jenshannoschwalm** [comment]
> I would rather revert to what we had before

Certainly i wouldn't want to do so :-) I see the "inconveniance" here but there are many advantages in the workflow. Just think of: Use a picker for color calibration or whatever. Distort by ashift, do cropping, rotate ... your picker will stay where it is. Or take #14598 ... 

1. Feel free to open an issue about "revert that crap" - no objections :-)
2. I will rethink about picker areas for modules ...



> But every now and then this does not work anymore....

Will check

**Comment by AxelG-DE** [comment]
I saw #14598 now and I do understand.

1. I hope I do not appear that disrespectful as I potentially call it crap :) 
2. maybe it is not alone in "your area" as I every now and then experience that the drawn path mask also just jumps away when I left-click it in order to drag. Unfortunately not a reliable behaviour, so I have difficulties on my own to reproduce

Thanks for all your hard work, I ever wonder how to accomplish that besides your day-job...

**Comment by jenshannoschwalm** [comment]
No problem about "respect" :-) and in fact if something I do is crap it can be called such :-) 

The other good point with the new area picker: the area shows the part it is taken from, that was not always the case before.

**Comment by AxelG-DE** [comment]
> The other good point with the new area picker: the area shows the part it is taken from, that was not always the case before.

The question is, which user is the corner case? :-Those using the color picker from left pane and rotate or lens-correct afterwards or the ones rarely use that one but use color calibration and filmic with the picker often. If we want to drive @elstoc nuts, we make it optional :smile:

**Comment by jenshannoschwalm** [comment]
Not only Chris! Handling both modes would be a nightmare.
I will think about this in 5.0 cycle again for sure.

**Comment by elstoc** [comment]
Options are fine when they just touch a single small "if" statement. Things like this will likely pollute all the code with conditional logic so probably not a good idea.

**Comment by AxelG-DE** [comment]
@jenshannoschwalm I have checked your work and it works like a charm! BIG THANK YOU!!!!!

(donno is related but there was an oddity in retouch module which a quick check showed, it seems also is fine now)

**Comment by jenshannoschwalm** [comment]
It's dterrahe work !

**Comment by AxelG-DE** [comment]
Ooops sorry, then indeed also @dterrahe a big BIG THANK YOU. That thing works like a charm now
