### ISSUE TITLE
User Interface 

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#16677]
**Is your feature request related to a problem? Please describe.**
Not really a problem but an inquiry

**Describe the solution you'd like**
I would like to know where can I find the module equivalent of the attached. Thank you

**Alternatives**
N/A

**Additional context**
I would like to know what is the equivalent module of the attached photo and where can I find it.
![LightroomExposure](https://github.com/darktable-org/darktable/assets/154827269/c1843f5f-5511-41cc-a2d2-6ad0077330b0)

**Comment by ralfbrown** [comment]
There is no single module with equivalents of all those controls.

Exposure module for exposure.
ColorbalanceRGB, FilmicRGB, or Sigmoid for global contrast.
Tone Equalizer or legacy Shadows&Highlights for shadows and highlights.
Not sure how "Whites" differs from "Highlights", but probably Tone Equalizer or possibly white level in FilmicRGB.

You should ask on https://discuss.pixls.us/c/software/darktable/19

**Comment by blackzerotype** [comment]
> There is no single module with equivalents of all those controls.
> 
> Exposure module for exposure. ColorbalanceRGB, FilmicRGB, or Sigmoid for global contrast. Tone Equalizer or legacy Shadows&Highlights for shadows and highlights. Not sure how "Whites" differs from "Highlights", but probably Tone Equalizer or possibly white level in FilmicRGB.
> 
> You should ask on https://discuss.pixls.us/c/software/darktable/19

That's what I thought too. I hope in the next iteration of darktable this is a simplfied version of the exposure module that has all the important varaibles and then use the other modules for more detailed tweaking. Thanks for the reply.

**Comment by ralfbrown** [comment]
That would be a far more complex module, not a simplified version.  And it would put many of the controls at the wrong point in the processing chain, yielding poor results.  darktable briefly had a basic adjustments module, which was deprecated and replaced by the quick access panel for exactly that reason.

[DARKTABLE IS NOT LIGHTROOM](http://linux.oneandoneis2.org/LNW.htm).  You can customize the quick access panel to put all the relevant controls more or less together, but trying to make it work exactly alike will be an exercise in frustration, just like trying to use any of the commercial competitors in exactly the same way would be.
