### ISSUE TITLE
Darktable crashes when opened

### ISSUE THREAD

**Issue by stefanoforcina** [darktable-org/darktable#16693]
### Describe the bug

Darktable crashes when opened, this is the report of terminal:

`iMac-di-stefano:~ stefano$ /Applications/darktable.app/Contents/MacOS/darktable

(process:1983): GLib-GObject-CRITICAL **: 18:07:13.181: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(darktable:1983): Gtk-CRITICAL **: 18:07:13.787: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2024-04-27 18:07:13.787 darktable[1983:35452] *** Assertion failure in -[NSMenuItem initWithTitle:action:keyEquivalent:], NSMenuItem.m:467
2024-04-27 18:07:13.808 darktable[1983:35452] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: aString != nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8014ac11a __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800fd10b7 objc_exception_throw + 48
	2   Foundation                          0x00007ff802383cd8 -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x00007ff8044c54b4 -[NSMenuItem initWithTitle:action:keyEquivalent:] + 363
	4   libgtkmacintegration-gtk3.4.dylib   0x0000000108f42f0a gtkosx_application_set_menu_bar + 1052
	5   libdarktable.dylib                  0x0000000108326b00 dt_gui_gtk_init + 1200
	6   libdarktable.dylib                  0x000000010818eb83 dt_init + 8803
	7   darktable                           0x0000000107a73f3a main + 42
	8   dyld                                0x00007ff800ffe41f start + 1903
)
libc++abi: terminating due to uncaught exception of type NSException
Abort trap: 6`

I thank everyone who can help me.

### Steps to reproduce

1. Open darktable from icon or terminal;
2. Crash.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.6.6

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by parafin** [comment]
Backtrace looks somewhat similar to that issue: https://gitlab.gnome.org/GNOME/gtk-mac-integration/-/merge_requests/6

It’s not exactly the same, but I suspect it’s still locale/encoding-related and probably another bug in GTK stack…

**Comment by stefanoforcina** [comment]
Thanks, a user on another channel solved the problem for me. I had to delete the darktable configuration folder that remained even if I uninstalled the program. It was corrupt. Darktable created a new one and everything was resolved. I thank you.
