### ISSUE TITLE
Export multiple images

### ISSUE THREAD

**Issue by kacnje** [darktable-org/darktable#16700]
### Describe the bug

I'm a noobie Darktable user and it looks very promising. Back in time, I worked with Capture One, but it is not available on Linux. 
Yesterday I imported and edited a bunch of images. But whatever I tried (in the Darkroom tab), it always exported only one image. 
I carefully selected all images (I saw "10 images selected of 10" above), but it always exported only one. 

### Steps to reproduce

1. Import 10 RAW images into Darktable. 
2. Select all images in the Darkroom tab and choose Export. 

### Expected behavior

Darktable should export all selected images.

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.3

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
Export in darkroom view only exports the image you're currently editing.  To export multiple images, switch to lighttable, select the images you want to export, and *then* choose export.

**Comment by ptilopteri** [comment]
* kacnje ***@***.***> [04-28-24 09:40]:
> ### Describe the bug
> 
> I'm a noobie Darktable user and it looks very promising. Back in time, I worked with Capture One, but it is not available on Linux. 
> Yesterday I imported and edited a bunch of images. But whatever I tried (in the Darkroom tab), it always exported only one image. 
> I carefully selected all images (I saw "10 images selected of 10" above), but it always exported only one. 
> 
> 
> ### Steps to reproduce
> 
> 1. Import 10 RAW images into Darktable. 
> 2. Select all images in the Darkroom tab and choose Export. 
> 
> ### Expected behavior
> 
> Darktable should export all selected images.
> 
> ### Logfile | Screenshot | Screencast
> 
> _No response_
> 
> ### Commit
> 
> _No response_
> 
> ### Where did you obtain darktable from?
> 
> flatpak
> 
> ### darktable version
> 
> 4.6.1
> 
> ### What OS are you using?
> 
> Linux



note that I do not use "flatpak", but compile master on opensuse
tumbleweed.

but I am able to export multiple images directly from darkroom by
selecting on the film strip display and <ctrl><e>


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by ralfbrown** [comment]
Interesting.... Ctrl-E only exports multiple images if the mouse is hovering over one of the selected images at the time.  If hovering an unselected image, only that image is exported, and if not on the filmstrip, only the current image is exported.

**Comment by ptilopteri** [comment]
* Ralf Brown ***@***.***> [04-28-24 13:41]:
> Interesting.... Ctrl-E only exports multiple images if the mouse is hovering over one of the selected images at the time.  If hovering an unselected image, only that image is exported, and if not on the filmstrip, only the current image is exported.
> 

I displayed the filmstrip which I seldom do and selected several images,
then <ctrl><e> and they export.  

note, they were not <developed> into the designated directory.
perhaps a bug.

but I ONLY did this as a test.  that is an abnormal workflow for me.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by kacnje** [comment]
Thank you. 
I didn't even see that there is a right panel in Lighttable. I read a user manual where the hell do you have "export" in Lighttable? Now it works as it should.

**Comment by victoryforce** [comment]
> Interesting.... Ctrl-E only exports multiple images if the mouse is hovering over one of the selected images at the time. If hovering an unselected image, only that image is exported, and if not on the filmstrip, only the current image is exported.

@ralfbrown Another "act on" feature, almost undiscoverable (unless by accident) and fragile in operation due to the need to take care of the cursor position?

> I didn't even see that there is a right panel in Lighttable. I read a user manual where the hell do you have "export" in Lighttable? 

@kacnje The right panel in Lighttable is to the right of the central thumbnail table and is shown by default. Obviously, you somehow hid it (with a keyboard shortcut or by pressing the hide triangle).

> Now it works as it should.

So this issue can be closed?

**Comment by kacnje** [comment]
Yes, close this "issue".

**Comment by ralfbrown** [comment]
> Another "act on" feature, almost undiscoverable (unless by accident) and fragile in operation due to the need to take care of the cursor position?

Yup.

**Comment by wpferguson** [comment]
Perhaps we need to do a better job of advertising/explaining/demonstrating.  If you know about it and how it works, then it's easy to avoid the pitfalls. Now, having said that I have no idea of how "to do a better job of advertising/explaining/demonstrating".

As an example of how it's useful, if I have a collection full of image groups I can simply hover over an image and hit a keyboard shortcut to invoke a lua script to just display that group only.  Hit the shortcut again and revert to the full collection.  Move the mouse over a different image and repeat.
