### ISSUE TITLE
Reconstruct in Filmic RGB with OpenCL glitches preview image

### ISSUE THREAD

**Issue by JumpingPistachio** [darktable-org/darktable#16704]
### Describe the bug

When using OpenCL, running the reconstruct feature within the Filmic RGB module causes the image previews in the top left, image carousel, and when zooming become glitched, with colors becoming almost inverted, with random black static splotches. 

### Steps to reproduce

1. Enable openCL
2. Turn on the Filmic RGB module
3. In the reconstruct tab, enable highlight reconstruction

### Expected behavior

darktable should provide preview images as normal, with highlights reconstructed.

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/76599467/bfc154ef-7bb6-42fc-9d52-04f15f561cea)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.2.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia GTX 1050ti

**Comment by victoryforce** [comment]
> ### darktable version
> 4.2.1

Does this problem occur on the current stable release (4.6.1)?

**Comment by JumpingPistachio** [comment]
The new version fixes it. Thanks!
