### ISSUE TITLE
High Pass effects image outside masks or even when opacity is set to 0%.

### ISSUE THREAD

**Issue by ghwaldo** [darktable-org/darktable#16706]
### Describe the bug

I hve a image with white clouds for example.
I wanted to use high pass filter, but not on parts where luminance is very high.
So i decided to use a parametric mask.
But when i set mode to overlay or linear light i noticed that parts of the sky changed.
For a test i used a very hard circle mask, same result.
Now i tested the following:
High Pass with sharpness, contrast and opacity set to 0, only mode set to overlay.
I expected that the image would not change at all.
But the white clouds change, so i think, there are operations done on the image.

I i operate for example with monochrome module and set mask mode to overlay, but opacity to 0, the behaviour is as expected: nothing changes.

### Steps to reproduce

Image with white clouds, high pass, mask mode overlay, contrast 0, sharpness 0, opacity 0

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

10

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment]
Thanks for the issue report. Can you test with 4.6.1? Also, if it is still happening in 4.6.1, can you share some screenshots to help visualize the issue? or an image/xmp? I tried using current master and I dont see an issue, but I'm also not clear in your steps.

**Comment by ghwaldo** [comment]
> Thanks for the issue report. Can you test with 4.6.1? Also, if it is still happening in 4.6.1, can you share some screenshots to help visualize the issue? or an image/xmp? I tried using current master and I dont see an issue, but I'm also not clear in your steps.

Sorry, i just saw that my version is 4.6.1.

Image area before applying hipass
![image](https://github.com/darktable-org/darktable/assets/44200786/d159c5cd-9148-41e4-b607-670976881abe)

Settings of hipass
![image](https://github.com/darktable-org/darktable/assets/44200786/6113e841-6087-454c-a2d3-9c048d86be56)

After applying
![image](https://github.com/darktable-org/darktable/assets/44200786/35aace90-47d4-41fd-9524-2aa294dcbdc2)

I will read more as mentioned in #7916 so iwill hope to understand this. For now, however, this function is useless for many images as i don't like it :(


But thank you all for the great work on darktable

**Comment by victoryforce** [comment]
> I will read more as mentioned in #7916 so iwill hope to understand this. For now, however, this function is useless for many images as i don't like it :(

In addition, it would be worth reading [the documentation](https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/highpass/). BTW, it is just two clicks away: click on the `?` icon, and then on the module. There you can read that while you consider this module useless, we consider it not recommended.  Please use the recommended modules that perform its function in a better way.
