### ISSUE TITLE
Crash with new Ubuntu 24.04 

### ISSUE THREAD

**Issue by Suppenlaender** [darktable-org/darktable#16710]
### Describe the bug

After installing the new Ubuntu version 24.04 LTS darktable crashes.
[darktable_bt_96IFN2.txt](https://github.com/darktable-org/darktable/files/15163726/darktable_bt_96IFN2.txt)
After launching everthing seems fine. I can also export the last imported pictures. But for example when I launch the 'preferences' or want open the 'darkroom' the application crashes completly

### Steps to reproduce

1. launch darktable
2. select "preferences" button
3. darktable crashes

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04 LTS

### Describe your system?

AMD Phenom(tm) II X4 955 Processor
RX570
12 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RX570

**Comment by ralfbrown** [comment]
Looks like something to do with font handling.  

The first trouble-shooting step is to run darktable with default configuration.  Rename `darktablerc` (in ~/.config/darktable if a native install, somewhere under ~/.var if a flatpak) to something like darktablerc.bak, then try running darktable.

**Comment by wpferguson** [comment]
I've built master on 24.04 (in a VM)_ and it runs without problems, including editing images and opening/closing/changing preferences.

**Comment by Suppenlaender** [comment]
> Looks like something to do with font handling.
> 
> The first trouble-shooting step is to run darktable with default configuration. Rename `darktablerc` (in ~/.config/darktable if a native install, somewhere under ~/.var if a flatpak) to something like darktablerc.bak, then try running darktable.

I tried your proposal. The only thing what changed is that I can start the preferences dialog. If I start editing(darkroom) then then application crashes completly.
Btw., I used v4.6.1 in ubuntu 23.10 whitout any problems (version 4.6.1). Since 24.04 I have this problems. I tried the version which comes which the ubuntu install packages (v4.6.1), also the version from the ppa  https://ppa.launchpadcontent.net/ubuntuhandbook1/darktable (v4.6.1), and also self compiled versions 4.6.1 and darktable-nightly from https://github.com/darktable-org/darktable. I also start the application w/o opencl, always the same result.

**Comment by wpferguson** [comment]
>  and also self compiled

I updated the package install commands on the wiki (https://github.com/darktable-org/darktable/wiki/Build-instructions-for-Ubuntu) to work with 24.04

**Comment by Suppenlaender** [comment]
> Looks like something to do with font handling.
> 
> The first trouble-shooting step is to run darktable with default configuration. Rename `darktablerc` (in ~/.config/darktable if a native install, somewhere under ~/.var if a flatpak) to something like darktablerc.bak, then try running darktable.

Nothing todo with font handling.
After the crash syslog reports 

kernel: darktable[44520]: segfault at 0 ip 0000000000000000 sp 00007fffa5a15a88 error 14 likely on CPU 1 (core 1, socket 0
kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6

**Comment by Suppenlaender** [comment]
> > and also self compiled
> 
> I updated the package install commands on the wiki (https://github.com/darktable-org/darktable/wiki/Build-instructions-for-Ubuntu) to work with 24.04

What do you want to tell me? This has nothing to do with the failure!

**Comment by gi-man** [comment]
A pastebin or .txt file of the output from darktable -d common might be more helpful to understand the problem.

**Comment by ralfbrown** [comment]
Both of your backtraces show that the crash happens in `pango_coverage_get` inside libpango, which "is a library for layout and rendering of text, with an emphasis on internationalization", while trying to compute a Gtk widget's width.  That's due to either the font in use or some very odd text being used in the widget.

Since resetting `darktablerc` cleared up the crash in the preferences dialog but not darkroom view, it's likely that you have a corrupted edit history on the crashing image(s).  Do you still get a crash when you start with a completely fresh setup with a newly-imported image that **doesn't** have a sidecar?  Copy some raw image to `/tmp/foo.{ext}`, then run `darktable --configdir /tmp/dt-test /tmp/foo.{ext}` (assuming /tmp/dt-test doesn't exist or at least is completely empty).

If that works without crashing, then you should try resetting the edit histories for any images that cause a crash when you start darktable normally -- select them in lighttable view, then use `discard history` in the `history stack`  module in the right pane.

**Comment by Suppenlaender** [comment]
> darktable --configdir /tmp/dt-test /tmp/foo.

If I run 'darktable --configdir /tmp/dt-test /tmp/foo.nef' the application crash immediately after launching
[darktable_bt_FEB0M2.txt](https://github.com/darktable-org/darktable/files/15190468/darktable_bt_FEB0M2.txt)

**Comment by GateaD** [comment]
I have had exactely the same problem. Solved by going in Settings>Apps>Darktable where i have disabled opengl, and Darktable wors fine. NO more crashes !

**Comment by GateaD** [comment]
I forgot to say, my Darktable is a snap version, installed via App Center.

**Comment by Suppenlaender** [comment]
> I have had exactely the same problem. Solved by going in Settings>Apps>Darktable where i have disabled opengl, and Darktable wors fine. NO more crashes !

Obvisealy you mean "opencl". But as I described before it has nothing to do with that for my system

**Comment by Suppenlaender** [comment]
Now I has found a workaround for my problem. The note for a font-libpango-libgtk3 problem left me no peace. So I deinstalled all fonts-noto (in one of the crash reports I see a note to this font family) from my system and now darktable doesnt crash anymore.
Curiously enough at other systems that I have running these problems are not exists with istalled noto fonts. So I think the deinstallation of a font group only bypasses the true problem. I think it have to do with the quantity of installed fonts at all.
