### ISSUE TITLE
lookup for updated XMP files on startup: duplicates on different workstations

### ISSUE THREAD

**Issue by KueWW** [darktable-org/darktable#16716]
### Describe the bug

I'm using darktable on different workstation. Both Workstations accessing the images on a shared folder. Creating a duplicate on one of the workstations the other workstation does not import it on startup.
Currently I solve the situation on removin the image from the database on the second workstation and reimport it again. After that duplicate appears.

### Steps to reproduce

1. Activate _lookup for updated XMP files on startup_
2. An image is listed in the dtabase of both workstations
3. Create a duplicate of an image on workstation 1
4. Finish editing duplicate on workstation 1
5. Close DT on workstation 1
6. Start workstation 2
7. If the window to choce different versions of images select the latest version of all listed images
8. The duplicate is not listed in the database
9. Remove the existing version of the image from the database
10. Re-Import the image
11. The duplicate(s) are listed

### Expected behavior

darktable should list all duplicates after scanning XML sidecars on startup

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12.x

### Describe your system?

The system is running inside a VMware 17.x virtualization. The images are stored on shared folders on the host machine of workstation 1. The 2nd workstation accesses the images using CIFS shares.

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I'm software developer. If your interested in, give me some hints where too search inside the code I would try to analyze the current behavior by my own.

**Comment by wpferguson** [comment]
The scan looks for updated xmp files for existing images.  Your second workstation has no knowledge of the duplicate (it's a new image) until you import it.

**Comment by KueWW** [comment]
I see.
I often create several duplicates on one of the workstations. I can't remember them all when I go back to the other workstation. In this case, it would be useful to show the duplicates as new images in the import dialog to import them automatically. I don't think this is currently the case.

**Comment by wpferguson** [comment]
>  it would be useful to show the duplicates as new images in the import dialog to import them automatically. I don't think this is currently the case.

That is correct.  I created a duplicate, then did a remove which left the file.  I tried to import, but it didn't show the duplicate as a new image.  I double clicked on the original image and imported that, which also gave me the duplicate.

As a workaround, you could reimport the directory which would pick it up, as well as update any changed images from the xmp files.

**Comment by KueWW** [comment]
Thanks for that!
