### ISSUE TITLE
All images in all phases of darktable pixelates periodically

### ISSUE THREAD

**Issue by Excaliburst** [darktable-org/darktable#16715]
### Describe the bug

Library, many images and scrolling make other pics pixelate.
Darktable (develop): the image I'm working on pixellates in shifting places. It is not permanent, but very annoying.
The strip in the bottom many images pixelates. And the pixelation changes and shifts to other images...

### Steps to reproduce

Install DT 4.6.1 Windows.
And use it.

### Expected behavior

No pixelation of any kind in any images as before.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Describe your system?

I am working on a new PC that I built myself. 

GPU: AMD Radeon RX 6700 XT
Processor	AMD Ryzen 9 7950X 16-Core Processor               4.50 GHz
Motherboard Aurus X670 Aourus Elite AX
Installed RAM	32,0 GB (31,1 GB usable)
Device ID	80EDF457-5DBF-40DC-9070-67D1ACA44B1C
Product ID	00330-81625-73627-AA529
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Pro
Version	23H2
Installed on	‎01-‎03-‎2024
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6700 XT (Drv: 31.0.24019.1006) Latest

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I only process RAW from OM-1 MK1 (Olympus) ORF.
![DT error - Pixelation](https://github.com/darktable-org/darktable/assets/10078661/0a93c8bb-4e88-4a19-80f0-05b9cf630685)

**Comment by gi-man** [comment]
Can you provide a log file (in txt or pastebin) of darktable-cltest?

**Comment by Excaliburst** [comment]
Where do I find the log?

**Comment by Excaliburst** [comment]
![DT Error2 - Darkroom](https://github.com/darktable-org/darktable/assets/10078661/154df800-da1b-4976-895c-520781d704ac)

This is the worst error I have seen. Apparantly it is not pixelation, but parts of the image repeated in the wrong places.

**Comment by victoryforce** [comment]
> Where do I find the log?

You will need to run `darktable-cltest` from the command line, where you will see the output of the command. You can copy the output from the command line window, or you can redirect that output to some file and attach it here.

Can you confirm that this problem does not occur when working with OpenCL disabled?

**Comment by gi-man** [comment]
The logs the debug and log files are explained in the FAQ. 

I'm not sure this is an opencl problem, but the log can help use. Another aid would be a log from -d common.

**Comment by Excaliburst** [comment]
Thanks a lot. The output of that command:

C:\Program Files\darktable\bin> .\darktable-cltest
darktable 4.6.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0,0493 [dt_get_sysresource_level] switched to 2 as `large'
     0,0505   total mem:       31893MB
     0,0511   mipmap cache:    3986MB
     0,0518   available mem:   21802MB
     0,0524   singlebuff:      498MB
     0.0547 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded, preference 'default path'
     0.0742 [opencl_init] found 1 platform
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'gfx1036'
   PLATFORM, VENDOR & ID:    AMD Accelerated Parallel Processing, Advanced Micro Devices, Inc., ID=4098
   CANONICAL NAME:           amdacceleratedparallelprocessinggfx1036
   DRIVER VERSION:           3608.0 (PAL,LC)
   DEVICE VERSION:           OpenCL 2.0 AMD-APP (3608.0)
   DEVICE_TYPE:              GPU, unified mem
   GLOBAL MEM SIZE:          12280 MB
   MAX MEM ALLOC:            10002 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   USE HEADROOM:             600Mb
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   C:\Program Files\darktable\share\darktable\kernels
   KERNEL DIRECTORY:         C:\Users\Morten\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_v3_kernels_for_AMDAcceleratedParallelProcessinggfx1036_36080PALLC
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DAMD=1 -I"C:\Program Files\darktable\share\darktable\kernels"
   KERNEL LOADING TIME:       0.0523 sec

[dt_opencl_device_init]
   DEVICE:                   1: 'gfx1031'
   PLATFORM, VENDOR & ID:    AMD Accelerated Parallel Processing, Advanced Micro Devices, Inc., ID=4098
   CANONICAL NAME:           amdacceleratedparallelprocessinggfx1031
   DRIVER VERSION:           3608.0 (PAL,LC)
   DEVICE VERSION:           OpenCL 2.0 AMD-APP (3608.0)
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          12272 MB
   MAX MEM ALLOC:            10431 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   USE HEADROOM:             600Mb
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   C:\Program Files\darktable\share\darktable\kernels
   KERNEL DIRECTORY:         C:\Users\Morten\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_v3_kernels_for_AMDAcceleratedParallelProcessinggfx1031_36080PALLC
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DAMD=1 -I"C:\Program Files\darktable\share\darktable\kernels"
   KERNEL LOADING TIME:       0.0521 sec
[opencl_init] OpenCL successfully initialized. internal numbers and names of available devices:
[opencl_init]           0       'AMD Accelerated Parallel Processing gfx1036'
[opencl_init]           1       'AMD Accelerated Parallel Processing gfx1031'
     0.6827 [opencl_init] FINALLY: opencl is AVAILABLE and ENABLED.
[opencl_init] opencl_scheduling_profile: 'very fast GPU'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[dt_opencl_update_priorities]           1       1       1       1       1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           1       1       1       1       1
[opencl_synchronization_timeout] synchronization timeout set to 0
   UNIFIED MEM SIZE:         7973 MB reserved for 'amdacceleratedparallelprocessinggfx1036'
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           0       0       0       0       0
[dt_opencl_update_priorities]           1       1       1       1       1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities]           image   preview export  thumbs  preview2
[dt_opencl_update_priorities]           1       1       1       1       1
[opencl_synchronization_timeout] synchronization timeout set to 0

**Comment by gi-man** [comment]
Datktable found 2 GPU cards/drivers. Your description above list only one. How many do you have? Could you have two drivers installed on windows?

**Comment by Excaliburst** [comment]
Yes - I have a small diminutive GPU on the Motherboard. But I need to use the AMD 6700 AX.
How do I select the right one.

**Comment by gi-man** [comment]
You will need to edit the darktablerc file to switch that disable via value in h in the GPUstring. https://docs.darktable.org/usermanual/4.6/en/special-topics/mem-performance/#device-specific-opencl-configuration

**Comment by Excaliburst** [comment]
I have no ideo how to edit this config file. 

In Device Manager, I have disabled the GPU on the motherboard. Should I then just uninstall, and reinstall DT for it to not get confused about GPUs? Are settings stored when I uninstall DT?

**Comment by gi-man** [comment]
Use Notepad to edit the file. darktablerc is just a txt file. The FAQ explain this too. https://www.darktable.org/about/faq/#faq-windows-config

Uninstalling does nothing. All of configuration files remain in //AppData/local/darktable

**Comment by Excaliburst** [comment]
An update.

Thanks gi-man. You took me on the right path. Everything is great now. Stable and no pixelations anymore.

The problem: I was simultaneously using 2 GPUs (one on mainboard, whose output is not used), and one on my GPU board.

The solution: In Device manager, I disabled the small GPU.

Results: Now I have no performance problems. And no pixelation.

Thanks a lot for feedback.
