### ISSUE TITLE
What version?

### ISSUE THREAD

**Issue by miguelviqueira** [darktable-org/darktable#16734]
What version for Mac Air M3 should I download: [darktable-4.6.1-x86_64.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.6.1/darktable-4.6.1-x86_64.dmg)  or
[darktable-4.6.1-arm64.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.6.1/darktable-4.6.1-arm64.dmg)  or even 
[darktable-4.6.1-arm64-](https://github.com/darktable-org/darktable/releases/download/release-4.6.1/darktable-4.6.1-arm64-macOS-12.5.dmg)

Thank you!
M.V.

**Comment by victoryforce** [comment]
@miguelviqueira x86_64 means Intel architecture.

**Comment by zisoft** [comment]
For a Mac with M3 processor you need one of the arm64 builds.

If you have macOS 14.x use the [darktable-4.6.1-arm64.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.6.1/darktable-4.6.1-arm64.dmg).
For older macOS versions use [darktable-4.6.1-arm64-macOS-12.5.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.6.1/darktable-4.6.1-arm64-macOS-12.5.dmg)
