### ISSUE TITLE
Vignetting module: please add option "increase exposure" postive brightness

### ISSUE THREAD

**Issue by ethpi** [darktable-org/darktable#16741]
**Is your feature request related to a problem? Please describe.**
I use the very cheap Nikon lens 35mm/1.8 for DX with an FX camera, so the corners of the image get dark. I'd like to enlight them with the vignetting module, but when increasing the brightness, the corners get white instead of bright.

**Describe the solution you'd like**
Instead of using white color in the vignetting module for increasing the brightness in the corners, increase the exposure in the corners. 

**Alternatives**
The exposure module with an inverted circle mask does the same, but the transmission is not as smooth as necessary. And I can't save the mask in a preset.

**Additional context**
I generated a lensfun profile (vignetting and distortion) for this DX lens mounted on a FX camera. The vignetting correction improves the result, but there are still dark corners, so the vignetting module should do the rest. (for focus 1.8 and small distance the vignetting is really less).

**Comment by MStraeten** [comment]
why not simply add a second instance of lens correction with correction mode "only manual vignette"?

**Comment by ethpi** [comment]
That's a good workaround. I tried it with for instances of lens correction. This works much better than using the exposure module with the inverted circular mask. 

But I think I get would get the best workflow, when there is a vignetting module with exposure increasing in the corners, because I can automatically use a preset ...

**Comment by ralfbrown** [comment]
You can also use a style, if you ensure that the instance of lens correction that you include in the style has a specific name (click on the two-squares icon in the module header and choose "Rename").  Named instances in a style are **added** to the current edit as new instances instead of replacing the settings in an existing instance, unless you happen to have an instance with the same name.

**Comment by ethpi** [comment]
I never used styles so far. I will try this. Thanks.

**Comment by ethpi** [comment]
Using a special style (that contains multiple instances of the lens correction module) is a strong improvement for my workflow. Is there a possibility to apply this special style automatically depending on the EXIF info of the lens?

**Comment by ralfbrown** [comment]
Unfortunately, darktable doesn't have auto-apply styles, only auto-apply presets.

**Comment by ethpi** [comment]
Ok. I don't use this lens very often. I can apply style manually. I will close this thread. Thanks for all your advice.

**Comment by wpferguson** [comment]
>  Is there a possibility to apply this special style automatically depending on the EXIF info of the lens?

I think we could do this with a lua script that triggers when the image is loaded into darkroom or when the image is selected in lighttable and a shortcut used..  Let me see what I can come up with.
