### ISSUE TITLE
Quick access panel: disabling module via shortcut does not update switch icon 

### ISSUE THREAD

**Issue by grothesque** [darktable-org/darktable#16760]
### Describe the bug

See title.

### Steps to reproduce

1. Go to darkroom view, and view the list of base modules.
2. Use "define shortcuts" icon to define a shortcut for toggling a module.  For example F2 for "filmic rgb".
3. Quit define shortcuts mode and verify that the shortcut works.  Use it to disable the module.
4. Now go to the quick access panel where the said module should be visible.
5. Press F2 once.  "filmic rgb" gets enabled and its switch icon becomes brighter.
6. Press F2 again. "filimc rgb" gets disable, but its swtitch icon stays bright.

### Expected behavior

In the quick access panel, the switch icon of modules toggled by shortcut should behave just like in the regular module lists

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable (bookworm)

### Describe your system?

The darktable I use is a self-compiled backport of the package in Debian testing.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RTX 3060 Ti

**Comment by ralfbrown** [comment]
Reproduced in a very recent master (4.7.0+1157~g223bcf62a7).
Likely related to the on-off button in the QAP being a separate widget that forwards actions to the one in the module proper, but it's odd that it changes on module activation, just not on deactivation.
