### ISSUE TITLE
Maps page not appearing in available screens anymore + not starting with keybaord shortcut

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#16799]
### Describe the bug

For an unknown reason, the Maps page is not available anymore:
![image](https://github.com/darktable-org/darktable/assets/3989573/c9806023-1143-4ab7-a9cc-61108006e2dc)

Compile options are

> darktable 4.6.1
> Copyright (C) 2012-2024 Johannes Hanika and other contributors.
> 
> Compile options:
>   Bit depth              -> 64 bit
>   Debug                  -> DISABLED
>   SSE2 optimizations     -> ENABLED
>   OpenMP                 -> ENABLED
>   OpenCL                 -> ENABLED
>   Lua                    -> DISABLED
>   Colord                 -> DISABLED
>   gPhoto2                -> DISABLED
>   GMIC                   -> DISABLED - Compressed LUTs are NOT supported
>   GraphicsMagick         -> DISABLED
>   ImageMagick            -> DISABLED
>   libavif                -> ENABLED
>   libheif                -> ENABLED
>   libjxl                 -> ENABLED
>   OpenJPEG               -> ENABLED
>   OpenEXR                -> DISABLED
>   WebP                   -> ENABLED

It was working on 4.4

### Steps to reproduce

1. Open dt
2. Click on the arrow next to Other which display available page/view such as Slideshow, Map
3.  Map is not available

Same issue when using my configured keyboard shortcuts
![image](https://github.com/darktable-org/darktable/assets/3989573/75ebc8c4-83c4-4122-be8c-f002b4f822e4)

### Expected behavior

See the menu, be able to open map with it or via keyboard shortcuts.

### Logfile | Screenshot | Screencast

Activated dartkable -d all ... saw nothing specific.

When using KB shortcuts, I only see this
```

68,4293 [lighttable] expose took 0,0000 sec
**69,0866   [dt_shortcut_move] shortcut received: ctrl+m**
72,5975 [lighttable] expose took 0,0000 sec
```

Could not find any dependencies I should add for the Map module to work

The compilation throws a
OPTIONAL OSMGpsMap  not found ... but I'm not sure this package is for Linux/(K)Ubuntu !! Cant find it in the repo

### Where did you obtain darktable from?

self compiled (git)

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 24.04

### Describe your system?

CPU: Intel 7700k
RAM: 32GB
GPU: Nvidia 1070 8GB VRAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1070 (nvidia-driver-550-server)

**Comment by GLLM** [comment]
Recompiled again after ensuring libosmgpsmap-1.0 is on my computer : no change :-/

**Comment by jbinpg** [comment]
You need the libosmgpsmap-1.0-dev if you are compiling.

**Comment by GLLM** [comment]
Yep, that was my mistake, i used libosmgpsmap-1.0 instead of the required libosmgpsmap-1.0-dev !
Thanks for your help @jbinpg , closing the thread ;)
