### ISSUE TITLE
Ubuntu darktable.cli is failing

### ISSUE THREAD

**Issue by sherwingws1** [darktable-org/darktable#16802]
### Describe the bug

darktable.cli ./P1135035.ORF  ./P1135035.jpg
warning: unknown option '--datadir'
warning: unknown option '--moduledir'
warning: unknown option '--configdir'
warning: unknown option '--localedir'
darktable 4.6.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

<https://www.darktable.org>
darktable is an open source photography workflow application and

### Steps to reproduce

darktable.cli ./P1135035.ORF, ./P1135035.jp

### Expected behavior

Convert an ORF file and output a jpg file

### Where did you obtain darktable from?

distro packaging

### darktable version

3.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.4 LTS

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by gi-man** [comment]
Are you using `darktable.cli` or `darktable-cli`?

Are you in 4.6.1 or 3.8.1? flatpak? snap?

https://docs.darktable.org/usermanual/4.6/en/special-topics/program-invocation/darktable-cli/

**Comment by sherwingws1** [comment]
Thank you for responding Your question as to which darktable I am using actually solved my problem.
I was using darktable.cli as shown in my post.  Because of your question, I tried darktable-cli and it worked.
Thank you.
