### ISSUE TITLE
Regression? Canon SX50 RAWs open in a strange and unreadable way.

### ISSUE THREAD

**Issue by briest** [darktable-org/darktable#16815]
### Describe the bug

I came back to some photos I made about a year ago — I mention it, because apperently something has changed between then and now (seems I was still using Darktable 4.2.1 back then for some reason). Now, if I open one of the RAWs for the first time, Darktable displays it as a one almost monochrome rectangle (there's a faint shape where the original photo was overexposed; screenshot and original file attached). Funny thing, RAWs that were opened back then, even with no modifications, do open OK today.

(I do not import whole directory at once, just single images one by one, by calling `darktable imagename.CR2`)

I have tried few images, all open in the same way. By opening them in RawTherapee and converting in dcraw I have verified, that they indeed do contain the image, so it's not matter of file corruption, I suppose.

RAWs from other cameras do open OK (but they're Lumixes).

### Steps to reproduce

None – the images immediately open that way, after running `darktable imagename.CR2`.

### Expected behavior

Well, darktable should display something I could work with ;)

### Logfile | Screenshot | Screencast

logfile from start until file is displayed: [dt.log](https://github.com/darktable-org/darktable/files/15365667/dt.log)

![dt-screenshot](https://github.com/darktable-org/darktable/assets/77794220/3d5f7b82-4dcd-4866-bb53-660e7f1bfa25)

### Where did you obtain darktable from?

OBS

### darktable version

4.6.1-1.1+74.1

### What OS are you using?

Linux

### What is the version of your OS?

Devuan Daedalus, corresponding to Debian Bookworm (12)

### Describe your system?

X11, 8GB RAM, Intel onboard graphics card (not sure about model, lshw says only “4 Series Chipset Integrated Graphics Controller”), GTK version 3.24.38-2~deb12u1

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I haven't checked with another version (other than originally with 4.2.1). Unfortunately shortly after the camera failed (mechanical issue), so I cannot find moment/version when the problem appeared for the first time.

JPEGs (and RAWs from other cameras) open just fine.

Neither resetting history nor removing image from Darktable and importing again changes anything.

Running with empty config shows same behaviour.

No scripts.

I attach zip containing one of the images and its XMP.
[IMG_9282.zip](https://github.com/darktable-org/darktable/files/15365760/IMG_9282.zip)

**Comment by ralfbrown** [comment]
Confirmed.  The raw black/white point settings are messed up - white point is 2820 and all four black levels at 65535....
Manually setting black levels to 120 and white point to 4000 yields a fairly good-looking result.

cameras.xml is missing the \<sensor\> tag with black and white levels for this model.

**Comment by LebedevRI** [comment]
This is unfortunately the same issue as in https://github.com/darktable-org/rawspeed/issues/717,
black area handling is broken.
