### ISSUE TITLE
Can't open and use Darktable 

### ISSUE THREAD

**Issue by Pazit3766** [darktable-org/darktable#16813]
Hello, after I downloaded and installed darktable I cannot open and use it on my new pc.
It has Windows 10 pro. 
I uninstalled and reinstalled again and still it won't open and I cannot use it. 
I read all the information about it and couldn't solve the problem.  A friend who is a computer specialist could not overcome this issue also.
I also tried to install older versions of dark table  - and still the same result. the program would not open and I cannot use it. 
Please help me because I would like very much to use your program. 
Thank you.

**Comment by victoryforce** [comment]
Please, when you open a new issue, use the "[Bug Report](https://github.com/darktable-org/darktable/issues/new?assignees=&labels=needs-triage&projects=&template=bug_report.yml)" template (not "Open a blank issue") and fill in all the information that is requested. I am closing this issue for convenience.

**Comment by MStraeten** [comment]
to be able to provide more information please read:
https://www.darktable.org/about/faq/#faq-windows-bugs
and 
https://www.darktable.org/about/faq/#faq-windows-logs
please provide the generated logs since otherwise you just can get random help
