### ISSUE TITLE
Cannot open the program after installing

### ISSUE THREAD

**Issue by Pazit3766** [darktable-org/darktable#16814]
### Describe the bug

Hello, after I downloaded and installed darktable I cannot open and use it on my new pc.
It has Windows 10 pro.
I uninstalled and reinstalled again and still it won't open and I cannot use it.
I read all the information about it and couldn't solve the problem. A friend who is a computer specialist could not overcome this issue also.
I also tried to install older versions of dark table - and still the same result. the program would not open and I cannot use it.
Please help me because I would like very much to use your program.
Thank you.

### Steps to reproduce

4

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

10 pro 

### Are you using OpenCL GPU in darktable?

Yes

**Comment by victoryforce** [comment]
Will it start when you run it with `darktable --disable-opencl`?

**Comment by victoryforce** [comment]
Also, what is the GPU card and driver?

**Comment by ralfbrown** [comment]
And if you have the "Microsoft OpenCL Compatibility Pack" installed (typically automatically installed), you should uninstall it as it has known incompatibilities.

**Comment by jenshannoschwalm** [comment]
That "Microsoft OpenCL Compatibility Pack" should not be a problem any more as that driver is disabled by default.

**Comment by victoryforce** [comment]
@Pazit3766 We can't help you if you don't give us the information we need.

**Comment by Pazit3766** [comment]
Thank you very much for your answers.
My knowledge of computers is very little so I need assistance on how to
check the open cl issue..

My GPU:
Intel(R) UHD Graphics 620.

This is my computer:

Lenovo T480
Intel(R) Core (TM) i5-8350u CPU @ 1.70GHz 1.90GHz
Ram 8GB
Windows 10 pro
Version 22H2
Build 19045.4412
Windows feature experience pack.

I would very much appreciate it if you could write here how can I check the
"open cl" issue in my computer.
 I have no idea how to approach it.

From the answers I got I assume that this is the reason why the program
won't open.

Thank you very much.


בתאריך יום ה׳, 23 במאי 2024, 21:40, מאת Victor Forsiuk ‏<
***@***.***>:

**Comment by devdasilva2015** [comment]
I am experiencing the same issue with darktable 4.6.1, but on macOS 14.5, tried installing the x86 and arm64 (for I am using an M3 Apple Silicon processor) but after clicking to start or starting from terminal, it stays open for 1 second and then crashes... I am only able to run on my Debian 12 Linux machine.

**Comment by zisoft** [comment]
@devdasilva2015: Can you please check if the directory `$HOME/.config` exists and has the correct permissions.
If that exists, please check for `$HOME/.config/darktable`

There was a similar case recently.

**Comment by devdasilva2015** [comment]
Thank you for the reply @zisoft 
I verified my macOS Home directory with the hidden files display enabled, I do have the .config folder, but no folder for darktable in it...

**Comment by zisoft** [comment]
Please check the permissions on the `.config` folder and make sure it is writeable for your user account.
You can ensure this via terminal:

`sudo chown <username> .config`
`sudo chmod -R .config`

Then try again to start darktable.

**Comment by devdasilva2015** [comment]
@zisoft that did the trick! It finally opened and didn't crash! Thank you so much!
Am curious now, why would I not have permission to the .cofig folder? I am the admin user of my mac...

**Comment by victoryforce** [comment]
> My knowledge of computers is very little so I need assistance on how to check the open cl issue..

@Pazit3766 I wrote to you in the comments above:

"Will it start when you run it with `darktable --disable-opencl`?"

Since you are asking for assistance after this advice, I take it that you have no experience running Command Prompt in Windows?
The easiest way is to type `cmd` in the Windows search bar and press Enter. After that, enter in the window that opens:

```
"c:\Program Files\darktable\bin\darktable.exe" --disable-opencl
```

But it makes sense to update darktable to 4.8.0 first. I don't hold out too much hope that this will fix the problem, but I wouldn't rule it out. So update first.

Please let me know if this fixes the problem.

**Comment by Pazit3766** [comment]
Thank you very much,
 I did all of the above - wrote the command.
 the response I got:
"The system cannot find the patch specified".
The program didn't open.




בתאריך יום ה׳, 27 ביוני 2024, 13:27, מאת Victor Forsiuk ‏<
***@***.***>:

**Comment by victoryforce** [comment]
> the response I got: "The system cannot find the patch specified".

You actually got a response "The system cannot find the ___path___ specified" (path, not patch). From this, I can guess that you typed this answer manually, not copy-pasted. Therefore, I suspect that, similarly, you entered the command I gave above manually and made a typo somewhere.

This command must be copied completely, up to the last character, into the command line via copy-paste. If that doesn't work either, you may have installed the program in a different location (for example, on a different drive). In this case, replace the path to the program with the actual one.
