### ISSUE TITLE
Map Module - missing image icons, missing scroll bar in film strip on Intel Mac

### ISSUE THREAD

**Issue by Peter-syd** [darktable-org/darktable#16838]
### Describe the bug

No image icons are shown for geotagged images - map is displayed in the correct position though. Also, there are no scroll bars in the film strip in map module, so only handful of images can be used.

### Steps to reproduce

1. select an image in lighttable
2. click on map module
3. map displays in the correct area, but no image icons visible
4. scroll bars missing from film strip

### Expected behavior

display image icons for geotagged images, scroll bars should be present to allow image selection

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Mac

### What is the version of your OS?

Monterey 12.7.4

### Describe your system?

Model Name:	MacBook Pro
Model Identifier:	MacBookPro13,3
Processor Name:	Quad-Core Intel Core i7
Processor Speed:	2.9 GHz
Number of Processors:	1
Total Number of Cores:	4
L2 Cache (per Core):	256 KB
L3 Cache:	8 MB
Hyper-Threading Technology:	Enabled
Memory:	16 GB
System Firmware Version:	526.0.0.0.0
OS Loader Version:	540.120.3~37
SMC Version (system):	2.38f12
Serial Number (system):	C02TM00SGTF1
Hardware UUID:	6403312C-ED0D-55D9-9315-AE598F17B708
Provisioning UDID:	6403312C-ED0D-55D9-9315-AE598F17B708

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

<img width="1680" alt="Screen Shot 2024-05-20 at 18 15 46" src="https://github.com/darktable-org/darktable/assets/170349075/8ce344c5-bd36-4ded-8085-4910456a21da">

**Comment by zisoft** [comment]
Cannot reproduce on my Intel Mac with current master:

![Bildschirmfoto 2024-05-20 um 18 55 39](https://github.com/darktable-org/darktable/assets/4083281/18a82c3b-937d-401e-a8e6-93288e120206)

> Also, there are no scroll bars in the film strip in map module, so only handful of images can be used.

The filmstrip can be scrolled with the mouse [see the manual](https://docs.darktable.org/usermanual/4.6/en/overview/user-interface/filmstrip/)

**Comment by ralfbrown** [comment]
> map displays in the correct area, but no image icons visible

In the map settings module in the right panel, make sure that "thumbnail display" is set to either "thumbnails" (default) or "count", rather than "none"

> scroll bars missing from film strip

As @zisoft indicated, you use the scroll wheel to adjust which images are shown.  Neither the filmstrip nor the timeline (in lighttable view) have scrollbars on any platform.

**Comment by Peter-syd** [comment]
Yes, you are right. Both suggestions worked. Sorry for jumping the gun, should’ve asked the forum first

Kind Regards,
Peter
