### ISSUE TITLE
Colorzones doesn't work with gray colors

### ISSUE THREAD

**Issue by yaitskov** [darktable-org/darktable#16842]
### Describe the bug

Hue tab doesn't change gray color. All darktable tutorials refer to color zones feature, but it is not working with gray.
I have grey socks on picture. I have no idea how to make them pink or yellow. 
The bottom line is darktable cannot change all colors.

### Steps to reproduce

1. Take picture with grey areas
2. Activate color zones
3. Switch to HUE
4. Drag the curve across the whole range

### Expected behavior

gray areas should change color

### Where did you obtain darktable from?

self compiled

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu with nix

### Describe your system?

```
nix-shell -p darktable --command darktable
```
nixpkgs commit aa9d4729cbc99dabacb50e3994dcefb3ea0f7447

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
In the default mode of select by hue, you are selecting by (range of) color, but gray does not have a color in that computation.
Have you tried select by chroma?  Raising/lowering the left edge of the graph will then adjust gray tones (but you'll need to really raise the chroma curve high to see effects of hue adjustments.

A better solution would be a masked instance of color balance rgb (global sliders in 4-way tab) or color correct (you'll probably want to move both white and black dots to the same color).  For the mask, either draw a shape covering the socks or use a parametric mask selecting only near-zero chroma (C/Cz/S channel, depending on color space).
