### ISSUE TITLE
Export: please add ability to export without reencoding

### ISSUE THREAD

**Issue by vitaly-zdanevich** [darktable-org/darktable#16846]
My usecase: I want to upload photos to Wikimedia Commons, using this plugin https://github.com/trougnouf/dtMediaWiki - and I want to upload original JPGs if nothing changed in them. [Related issue](https://github.com/trougnouf/dtMediaWiki/issues/14).

**Comment by wpferguson** [comment]
This already exists in the exporter, just select `copy`.  If you want that to occur while using dtMediaWiki, then you need to raise an issue there.

**Comment by vitaly-zdanevich** [comment]
> This already exists in the exporter, just select copy

Where? In `file format` I have JPEG, PNG, TIFF, WebP.

![image](https://github.com/darktable-org/darktable/assets/3514015/c3132cfc-5766-4c7f-8537-85dba97d3cd7)


Author of dtMediaWiki said that this is about Darktable - not about the plugin https://github.com/trougnouf/dtMediaWiki/issues/14#issuecomment-2122885292

**Comment by vitaly-zdanevich** [comment]
Solved by creator of dtMediaWiki - now I see `copy` https://github.com/trougnouf/dtMediaWiki/issues/14#issuecomment-2123168003

**Comment by ptilopteri** [comment]
local problem with installed app or build
it is available, see: http://wahoo.no-ip.org/~paka/Screenshot_20240521_164908.png

darktable 4.7.0~git1278.0e47c61f-11730.1

locally built on openSUSE Tumbleweed
