### ISSUE TITLE
[Feature request] Enable the possibility to activate the ISO 12646 Color assessment by default when editing pictures

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#16859]
Hi all,

Logging this feature request after a discussion on pixls.us.

Whenever I'm editing pictures, the first thing I do is activate the ISO 12646 for better color assessment conditions by pressing  CTRL+B

I believe it would make sense to have a setting to activate this by default when editing pictures. 
And of course still be able to disable it with  CTRL+B if needed.

Couldn't find how to do so in 4.6.1

Thanks

GLLM

**Comment by wpferguson** [comment]
Do you want it activated each time you load an image in darkroom?

**Comment by GLLM** [comment]
If a setting allows to, yes I would like to have it activated each time I open darkroom... 

Honestly, I'll probably switch it off once the WB/exposure arE properly set.
So being able to switch it on/off is key.

**Comment by wpferguson** [comment]
Here's a script that will toggle it on when an image is loaded into darkroom.  Drop it into the contrib folder, then turn it on.  When an images loads it will toggle color assessment mode.  Just turn off the script when you don't need it..
[auto_color_assess.zip](https://github.com/darktable-org/darktable/files/15424401/auto_color_assess.zip)

**Comment by GLLM** [comment]
Will try this, thanks @wpferguson

**Comment by GLLM** [comment]
hey @wpferguson 
It works when I'm in lighttable then open darkroom to retouch my photos 👍🏻 

Yet, when I'm editing in darkroom and move from one pic to another (backspace/enter), it does not ;-)

Thanks anyway !

**Comment by wpferguson** [comment]
Here's a version that just set's it to on, instead of toggle.  It worked for me spacing and backspacing.

[auto_color_assess.zip](https://github.com/darktable-org/darktable/files/15440916/auto_color_assess.zip)

**Comment by GLLM** [comment]
Working fine now, thanks a lot !

**Comment by jenshannoschwalm** [comment]
I think we should keep the setting as we do for the second window for consistency and better workflow

**Comment by wpferguson** [comment]
The script seems to have fixed the issue.  @GLLM can we close this?

**Comment by GLLM** [comment]
@wpferguson 
If this shall remain a script and will not be native in darktable binary, yeah let's close it ! :-)

**Comment by wpferguson** [comment]
I'll add it to the lua-scripts repository.  Thanks for the idea
