### ISSUE TITLE
Too many white balance messages in the Terminal window running darktable

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#16861]
### Describe the bug

Suppose you use a setting such as User Modified or From Image Area in the White Balance Module, and you also use the Color Calibration module.  Then the Terminal window is populated with many message pairs like
  1321.9551 Trouble: [white balance] double application of white balance (_6D_13002.CR2 656)
  1321.9552 Trouble: [color calibration] white balance is not using reference illuminant (_6D_13002.CR2 656)
The volume of these makes spotting genuine problems difficult.
These are not system error messages, they are the result of a genuine user choice, so I do not think they should be logged like this.  The GUI warns the user if they are doing double application, so I think this should be sufficient.

### Steps to reproduce

as above

### Expected behavior

DT should not log lots of these messages.  It could log none at all.  Maybe it could log just one pair if the image is output.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

Darktable-4.7.0+1282.gb1942b8a21-x86_64.AppImage

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Are you using OpenCL GPU in darktable?

No

**Comment by jenshannoschwalm** [comment]
Closing as fixed
