### ISSUE TITLE
Darktable crashes randomly

### ISSUE THREAD

**Issue by MakotoE** [darktable-org/darktable#16870]
### Describe the bug

Darktable crashes after a random time a photo is open in darktable or the lighttable. It can crash even without making modifications to the photo.

I found that closing and reopening Darktable contributes to the crash. Restarting my PC temporarily fixes the issue. See the last section of this post.

### Steps to reproduce

1. Open Darktable and make modifications to a photo.
2. Close Darktable.
3. Reopen Darktable.
4. Open a photo and edit it. Darktable crashes within one minute.

### Expected behavior

Darktable should not crash.

### Logfile | Screenshot | Screencast

```

(darktable.exe:225932): GLib-GObject-CRITICAL **: 13:42:13.391: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(darktable.exe:225932): GLib-GObject-CRITICAL **: 13:42:13.391: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(darktable.exe:225932): Gtk-CRITICAL **: 13:42:13.391: gtk_tree_model_foreach: assertion 'GTK_IS_TREE_MODEL (model)' failed
[INFO] tile number 1 / 1
Magick: caught exception 0xC0000005 "Access violation"...
(darktable.exe:301260): Gtk-WARNING **: 12:51:25.204: Couldn't export handle, unsupported windowing system
Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...========================================
version: darktable 4.6.1
start: 2024:05:11 15:02:38

     0.0951 [init] the database lock file contains a pid that seems to be alive in your system: 58816
     0.0951 [init] database is locked, probably another process is already using it
     0.0951 [dt_init] trying to open the images in the running instance
Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...
```

The log is the exact same for all crashes.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

5.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 23H2

### Describe your system?

Here are the processing settings, which should be close to default.

<img width="585" alt="Screenshot 2024-05-25 102930" src="https://github.com/darktable-org/darktable/assets/36318069/d0061caf-aa7a-499f-aee1-36ff5c6d4083">

My GPU is a AMD Radeon RX 6900 XT. Graphics driver version is 24.4.1. AMD Adrenalin Edition does not report that the graphics driver crashed.

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- I tried using Darktable with a PNG image, after removing all raw images from the library, and it still crashed with the same log.
- I tried uninstalling and reinstalling Darktable. This did not work.
- I tried resetting my graphics driver overclock settings, but this did not work.
- I tried restarting my PC, then opening Darktable and editing. This fixed the issue, and I was able to get my work done without any crashes. I think that this makes the `database is locked, probably another process is already using it` line of the log a suspicious hint as to what caused the crash.

**Comment by MakotoE** [comment]
After Darktable crashed, I searched `darktable.exe`  in task manager but could not find it. If you want me to find out what process is locking the database, I can try your suggestion.

**Comment by kofa73** [comment]
To unlock the database, please delete the lock files `data.db.lock` and `library.db.lock`. They are in:
`%LOCALAPPDATA%\darktable`, which is, on English Windows, `C:\Users\<user login>\AppData\Local`.

Similar crashes (_"Access violation"...Magick: caught exception_) were often reported when _resources_ was set too high (especially to _unrestricted_). Please try a lower setting.
If that does not help, disable OpenCL.

**Comment by MakotoE** [comment]
Do I need to delete those lock files every time I exit out of Darktable? I know they are supposed to be deleted automatically, but if I have to do it manually it can be laborious.

**Comment by MakotoE** [comment]
Additional question, is the Magick exception what is causing the crash, or the database lock that is causing the crash every time?

**Comment by kofa73** [comment]
Normally, the lock files are only there while darktable is running, to avoid corrupting the database when a second instance is accidentally launched. They are removed when the application _closes normally_, but may be left behind when it _crashes_. The DB lock does not cause a crash.

Have you tried disabling OpenCL? (Note that github is not a support forum, though. Initial troubleshooting is usually done at https://discuss.pixls.us/c/software/darktable/19.)

**Comment by MakotoE** [comment]
Thank you. It does seem like a troubleshooting concern now that we established that it's something related to resource capacity. I will go there in case it happens again.
