### ISSUE TITLE
Incorrect Color Calibration illuminant in 4.7.0, while it is correct(?) in 4.6.1.

### ISSUE THREAD

**Issue by somename-123** [darktable-org/darktable#16888]
### Describe the bug
In the new darktable version, Color Calibration's default illuminant is set to a pinkish color, while the photo was made during a cloudy day. If Color Calibration is disabled, the image looks pink, which was not the case in the previous version. Also, If Color Calibraton is disabled, but Input Color Profile is set to Lab, the image looks [more] normal.

### Steps to reproduce

I took these steps before making each screenshot / opening a different darktable version. I did not modify any values inside modules.

1. ``rm -rf ~/.config/darktable``.
2. ``rm 20240527_133049.dng.xmp`` (if exists).
3. Open the file with ``darktable -d common 20240527_133049.dng > log_461.txt`` or ``./Darktable-4.7.0+1305.gec2d6cb431-x86_64.AppImage -d common 20240527_133049.dng > log_470.txt``.
4. Disable all default modules except for White Balance and Color Calibration.

### Expected behavior

darktable should pick a correct illuminant? (I am very new to darktable, maybe what it does is already the correct behavior)

### Logfile | Screenshot | Screencast

[log_461.txt](https://github.com/darktable-org/darktable/files/15455646/log_461.txt)
[log_470.txt](https://github.com/darktable-org/darktable/files/15455647/log_470.txt)

##### Color Calibration + White Balance (default values)
![grab_461](https://github.com/darktable-org/darktable/assets/57208295/a87b8b39-4892-45dd-b405-ab4a38486225)
##### Disable Color Calibration
![grab_461_no_calibration](https://github.com/darktable-org/darktable/assets/57208295/c14e31c1-5865-4f54-91d8-acf3cbf461b6)

##### Color Calibration + White Balance (default values)
![grab_470](https://github.com/darktable-org/darktable/assets/57208295/1d04db4f-9166-442b-b949-d4e83e2a8030)
##### Disable Color Calibration
![grab_470_no_calibration](https://github.com/darktable-org/darktable/assets/57208295/f1daeacd-808a-4648-a1a7-4000759c6fc6)
##### Switching to Lab input profile solves the problem...?
![grab_470_no_calibration_input_lab](https://github.com/darktable-org/darktable/assets/57208295/a0bc5e5e-407e-417d-b559-ac6273d5717d)

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.7.0+1305~gec2d6cb431

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 39

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GTX 1050 | Driver Version: 550.78 | CUDA Version: 12.4

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[20240527_133049.zip](https://github.com/darktable-org/darktable/files/15455676/20240527_133049.zip)
This is ``20240527_133049.dng`` renamed to ``~.zip``.

[20240527_133049.dng.xmp.version470.txt](https://github.com/darktable-org/darktable/files/15457003/20240527_133049.dng.xmp.version470.txt)
[20240527_133049.dng.xmp.version461.txt](https://github.com/darktable-org/darktable/files/15457004/20240527_133049.dng.xmp.version461.txt)

**Comment by somename-123** [comment]
<details>
  <summary>exiftool 20240527_133049.dng</summary>

  ```
  $ exiftool 20240527_133049.dng
  ExifTool Version Number         : 12.70
File Name                       : 20240527_133049.dng
Directory                       : .
File Size                       : 24 MB
File Modification Date/Time     : 2024:05:27 13:41:07+02:00
File Access Date/Time           : 2024:05:27 14:24:27+02:00
File Inode Change Date/Time     : 2024:05:27 14:24:27+02:00
File Permissions                : -rw-r--r--
File Type                       : DNG
File Type Extension             : dng
MIME Type                       : image/x-adobe-dng
Exif Byte Order                 : Little-endian (Intel, II)
Subfile Type                    : Full-resolution image
Image Width                     : 4000
Image Height                    : 3000
Bits Per Sample                 : 16
Compression                     : Uncompressed
Photometric Interpretation      : Color Filter Array
Image Description               : 
Make                            : Xiaomi
Camera Model Name               : MI 9
Strip Offsets                   : (Binary data 25621 bytes, use -b option to extract)
Orientation                     : Unknown (9)
Samples Per Pixel               : 1
Rows Per Strip                  : 1
Strip Byte Counts               : (Binary data 14999 bytes, use -b option to extract)
X Resolution                    : 72
Y Resolution                    : 72
Planar Configuration            : Chunky
Resolution Unit                 : inches
Software                        : Xiaomi/cepheus_eea/cepheus:11/RKQ1.200826.002/V12.5.2.0.RFAEUXM:user/release-keys
Modify Date                     : 2024:05:27 13:30:49
CFA Repeat Pattern Dim          : 2 2
CFA Pattern 2                   : 0 1 1 2
Copyright                       : 
Exposure Time                   : 1/101
F Number                        : 1.8
ISO                             : 100
Date/Time Original              : 2024:05:27 13:30:49
Focal Length                    : 4.8 mm
TIFF-EP Standard ID             : 1 0 0 0
DNG Version                     : 1.4.0.0
DNG Backward Version            : 1.1.0.0
Unique Camera Model             : MI 9-Xiaomi-Xiaomi
CFA Plane Color                 : Red,Green,Blue
CFA Layout                      : Rectangular
Black Level Repeat Dim          : 2 2
Black Level                     : 64 64 64 64
White Level                     : 1023
Default Scale                   : 1 1
Default Crop Origin             : 8 8
Default Crop Size               : 3984 2984
Color Matrix 1                  : 1.5625 -0.7421875 -0.2421875 -0.96875 1.875 0.0390625 0.0390625 -0.1328125 0.6953125
Color Matrix 2                  : 2.5234375 -1.75 -0.4453125 -1.0703125 2.1796875 -0.0078125 0.0546875 -0.1328125 1.1796875
Camera Calibration 1            : 0.546875 0 0 0 1 0 0 0 0.59375
Camera Calibration 2            : 1 0 0 0 1 0 0 0 1
As Shot Neutral                 : 0.529296875 1 0.509765625
Baseline Exposure               : 0
Calibration Illuminant 1        : D65
Calibration Illuminant 2        : Standard Light A
Active Area                     : 0 0 3000 4000
Forward Matrix 1                : 0.4375 0.3828125 0.140625 0.21875 0.71875 0.0625 0.015625 0.09375 0.7109375
Forward Matrix 2                : 0.4375 0.3828125 0.140625 0.21875 0.71875 0.0625 0.015625 0.09375 0.7109375
Opcode List 2                   : GainMap, GainMap, GainMap, GainMap
Noise Profile                   : 5.4272927e-05 2.0385919e-07 5.4272927e-05 2.0385919e-07 5.4272927e-05 2.0385919e-07
Aperture                        : 1.8
CFA Pattern                     : [Red,Green][Green,Blue]
Image Size                      : 4000x3000
Megapixels                      : 12.0
Shutter Speed                   : 1/101
Focal Length                    : 4.8 mm
Light Value                     : 8.3
  ```
</details>

**Comment by wpferguson** [comment]
invalid is explained here, https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/color-calibration/.  It's not a error, just a status.

**Comment by jenshannoschwalm** [comment]
> I guess this is related to #16624 @jenshannoschwalm

Right. Camera calibration data are available and i think processed correctly here. DT4.6 missed that correction so output is expected to be different.

**Comment by somename-123** [comment]
> invalid is explained here, https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/color-calibration/. It's not a error, just a status.

> Right. Camera calibration data are available and i think processed correctly here. DT4.6 missed that correction so output is expected to be different.

Thanks for the replies.

As I understand it, an illuminant is whatever lights your scene, in my case it was a cloudy day.

In 4.6.1 I would've used Daylight illuminant to adjust white balance to my taste, and it is set to Daylight 4353K by default. But in 4.7.0, setting it to Daylight does not result in correct colors, and by default it is set to Custom with pinkish color.

So, what is the new way to set color temperature? Setting it with Hue and Chroma is a bit unusual to me, so, if I want to keep using color temperature values, should I just disable Color Calibration and use only White Balance module? Or Hue + Chroma is the new way I should learn to use? Or darktable does what is should but my files have bad data?

**Comment by somename-123** [comment]
Yes, it worked! Thank you!
