### ISSUE TITLE
Darktable freezes on large imports

### ISSUE THREAD

**Issue by Smartich0ke** [darktable-org/darktable#16886]
### Describe the bug

When I import large amounts of files (about 500-800 dual nef/jpeg), darktable will freeze when I go from grid layout to culling layout.

My computer should be more than enough to handle this - ryzen 5 5600x, rx6600, 32gb RAM, ssd storage. The same happens when i try to load of a microsd card with a usb 3.0 reader. Kind of disappointing for a program who's sole job is to sort and process images.

I'm using darktable 4.4.2 (installed through apt) on Ubuntu 23.10 using GNOME on Xorg.

### Steps to reproduce

1. Boot up darktable
2. Import a bunch of photos
3. Wait for the thumbnails to generate
4. Select an image and go into fixed or dynamic culling mode
5. The program freezes and the gnome "program isnt responding" dialogue pops up. If I wait a while, the program will eventually load the image and continue as normal.

### Expected behavior

darktable should run normally

### Where did you obtain darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

GNOME 45.2 on xorg

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600

**Comment by wpferguson** [comment]
My average import is ~1500 raws and I haven't seen this problem.  

Are you importing from an existing folder or doing a copy and import from an SD card or external drive?

**Comment by jenshannoschwalm** [comment]
1. Also there have been numerous fixes related to mem consumption for pixelpipes since 4.4
2. I dt is still importing while opening an image in darkroom it will do so after the thumbnail pipelines have finished. (if you generate thumbs from raw and possibly have modules automatically switched on that could take a time) If using OpenCL that could also depend on your sheduler setting.

**Comment by jenshannoschwalm** [comment]
Closing as incomplete and no further information was given.

**Comment by gauvinalexandre** [comment]
I tried importing *.jpg and *.dng files from the DCIM directory of my phone connected through the best USB C cable and plug I have: same symptom, no response and Linux dialog popup to forcefully crash darktable. I had to copy files in a local directory first, then import in darktable.
