### ISSUE TITLE
Color Calibration module is misoperating - jerky response to slider movement

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#16897]
### Describe the bug

I was just trying the fix for #16861.  The messages in the Terminal window have gone, so that's good.
However the CC module seems to be playing up now. With the warnings for double white balance showing on the right of the screen, adjustments in CC for any of the sliders cause repeated jerky re-displaying of the module details.  I don't think it used to do this.

Same behaviour in the WB module.

### Steps to reproduce

Set WB module to "from image area".  Enable CC and move temperature slider.

### Where did you obtain darktable from?

GitHub nightly

### darktable version

Darktable-4.7.0+1309.g40d9f8ec7b-x86_64.AppImage

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Describe your system?

not using opencl

### Are you using OpenCL GPU in darktable?

None

**Comment by RawConvert** [comment]
I don't know how to do a video and haven't time to find out this afternoon.  However here are 2 screenshots.  The one without the warning msg was taken whilst sliding the hue.  The other was taken after I stopped sling the hue.  The module flickers as I slide the hue and so I've caught it without the warning msg in this instance. Hope that helps...
![Screenshot from 2024-05-28 15-24-44](https://github.com/darktable-org/darktable/assets/16868433/64580d79-23aa-40f2-9958-d97902737a4b)
![Screenshot from 2024-05-28 15-24-39](https://github.com/darktable-org/darktable/assets/16868433/191bc9a4-b2e3-4995-96e1-67b6876b7b8d)

**Comment by apostel338** [comment]
Is this what you mean? I get jerky things when I provoke the "double wb warning" by modifying the settings in wb module to non-6500k setting:

https://github.com/darktable-org/darktable/assets/96216629/37c5b916-c6de-41b8-a6d1-d81c87b0db22

**Comment by RawConvert** [comment]
@apostel338 , yes that's it, thanks for videoing.

**Comment by gi-man** [comment]
I can reproduce with no opencl. It looks like while at some point processing the pipe, the warning doesnt show, but then it shows when the pipe finishes.

**Comment by jenshannoschwalm** [comment]
Confirmed. Working on it.

**Comment by jenshannoschwalm** [comment]
Got it, it's basically something else and old, fix follows tomorrow so just hold on.
