### ISSUE TITLE
Feature request: AppImage for stable release

### ISSUE THREAD

**Issue by BluishHumility** [darktable-org/darktable#16899]
Hello,

If it is realistic to implement, I would be grateful to have an AppImage provided for the stable releases. I did take a look to see if this has been requested before and I found [this thread](https://github.com/darktable-org/darktable/issues/3925). It was heartening to see the AppImages have been incorporated into the release cadence, however it appears the AppImages are currently only published for the testing/nightly build releases.

I don't know the story behind the decision to only release AppImages for nightly builds, and I certainly do appreciate that there is more to it than I am aware of; if it is not practical to publish AppImages for the stable releases as well, I completely understand. I just wanted to mention that there is at least some interest in the community for getting the stable releases in this format, in case it is a manageable thing to add.

Thank you for taking a look. 🙂

**Comment by victoryforce** [comment]
We now provide the official darktable build in AppImage container format. Therefore, I close this issue.
