### ISSUE TITLE
Remove all obsolete film rolls

### ISSUE THREAD

**Issue by danyelf** [darktable-org/darktable#16901]
**Is your feature request related to a problem? Please describe.**

My workflow involves getting film rolls, once processed, off my (rather small) hard drive. That means that after I'm done with a shoot, I move it to archival storage. The "collections" tab helpfully updates the roll with a strikethrough line to show me it's gone.

I then right-click, get a confirm dialog. Unfortunately, I might be dealing with ten or twelve film rolls at a time, and it gets monotonous. Find a roll with a strikethrough, remove, repeat.

**Describe the solution you'd like**
I would like an option for "remove all deleted film rolls", or something similar. I think it would have to sit under the preset menu for Collections, but you might have better ideas.

**Comment by ralfbrown** [comment]
There are a couple of different options to bulk-remove unavailable images from the database: purge_non_existing_images.sh, and ISTR a Lua script (though I don't see it in the repo - it may have been posted on pixls.us).  Once a filmroll no longer contains any images, it won't appear in collections anymore.

**Comment by wpferguson** [comment]
Here's a lua script that can scan for and remove missing film rolls or missing images from the database.

Unzip the file and drop it in your .config/darktable/lua/contrib directory.  Start darktable, open script_manger, find dbmaint and start it.  The script creates a module in the left center panel.  To use it select film rolls or images from the drop down, then scan.   The whole database is scanned for missing film rolls, or the current collection is scanned for missing images.  If anything is found missing, it's listed and then you can press the remove button to remove the entries from the database.  In the case of a film roll, all the image entries that belong to that film are also deleted.

If you use a NAS and sometimes forget to mount it, this script might not be for you :).

[dbmaint.zip](https://github.com/user-attachments/files/15520292/dbmaint.zip)

**Comment by danyelf** [comment]
These are both fantastic solutions -- thank you!

**Comment by victoryforce** [comment]
> These are both fantastic solutions -- thank you!

So can we close the issue then?

**Comment by mikae1** [comment]
> In the case of a film roll, all the image entries that belong to that film are also deleted.

Just to be sure @wpferguson. By “image entries that belong to that film are also deleted” you mean removed from the database? The actual files on disk are not deleted?

**Comment by wpferguson** [comment]
The actual files on disk are missing.  What dbmaint.lua does is make the database agree with the state of the disk.

For example, you move a directory of images to other storage.  When darktable starts it can't find the filmroll so it strikes through the name.  When you run dbmaint, it flags the filmroll as missing and the images as missing.  When you delete to fix it, you are deleting the database records.
