### ISSUE TITLE
Behaviour of White Balance (WB) and Color Calibration (CC) modules

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#16906]
### Describe the bug

Warning messages appear inconsistently and WB seems to show incorrect white balance details.

### Steps to reproduce

1. Load a raw with a reasonable camera white balance that is new to DT (with scene-referred sigmoid in preferences).
2. Change WB to "camera reference" then change to temp=6501 i.e. slight change.  Notice "wb applied twice" in WB  BUT   no warning showing for CC.
3. Expand CC, switch off, switch on, see "white balance module error".  Why is this?
4. Change temp to 6500 in WB.  CC has no warning message, shouldn't it have?
5. In CC change daylight to custom, now the wb module error msg appears, why?

Second test with a Unity White Balance raw -
1. Drag in the raw, new to DT.  Note that WB and CC both have warnings.
2. Open WB and see msg "white balance missing" even though the module is On.
3. Raw has wb coefficients 1,1,1 but temp shown as 5181 which seems wrong.
4. Change temp to 5182 , setting is now "user modified" with msg "white balance applied twice" which seems sensible.
5. However the WB details look wrong. Switch CC off , set WB to cam ref and note the image looks ok, not green, and the coeffs look ok (2.2, 1, 1.4)   Now change WB to As shot to reference.  Temp becomes 5181 again, coeffs are back to 1,1,1  BUT  the image has not changed, it should now be green surely.
6. Switch CC on and see the wb missing message.  Change from custom to daylight and the first time doing this, I had the msg disappear.  Switching like this second time and on, the msg remained.
7. Change WB to "from image area", see "wb applied twice", ok, BUT no warning in CC.

UniWB raw attached

### Expected behavior

as above

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

Darktable-4.7.0+1315.gd2c11c4f54-x86_64.AppImage

### What OS are you using?

Linux

### What is the version of your OS?

ubuntu 22.04

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

[Uploading _6D_12990.zip…]()

**Comment by RawConvert** [comment]
Doesn't seem to be uploading...

**Comment by RawConvert** [comment]
UniWB raw file is here as .zip - https://discuss.pixls.us/t/pls-ignore-this/43820

**Comment by jenshannoschwalm** [comment]
Will do my best for release.

**Comment by jenshannoschwalm** [comment]
1. Indeed there was a bug related to UniWB images.
2. The rest was UI stuff, hopefully i fixed all those via #16915

**Comment by jenshannoschwalm** [comment]
Closing this after testing your "doing wrong" cases. Feel free to open a new issue if there is still something wrong ...
