### ISSUE TITLE
Darktable binaries fails to launch - "free(): invalid pointer"

### ISSUE THREAD

**Issue by jhillest** [darktable-org/darktable#16914]
### Describe the bug

Darktable does not launch on my system.

### Steps to reproduce

Launching Darktable from [Konsole](https://konsole.kde.org/), I get the following output:
```
free(): invalid pointer
fish: Job 1, 'darktable' terminated by signal SIGABRT (Abort)
```
I get the same output for `darktable-cltest` and `darktable-generate-cache`

### Expected behavior

Darktable should launch normally

### Logfile | Screenshot | Screencast

[darktable_strace.log](https://github.com/user-attachments/files/15517769/darktable_strace.log)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch

### Describe your system?

- Operating System: Arch Linux (last updated ~24 hours ago)
- KDE Plasma Version: 6.0.5
- KDE Frameworks Version: 6.2.0
- Qt Version: 6.7.1
- Kernel Version: 6.9.2-zen1-1-zen (64-bit)
- Graphics Platform: Wayland
- Processors: 4 × Intel® Core™ i5-4670K CPU @ 3.40GHz
- Memory: 31,3 GiB of RAM
- Graphics Processor: AMD Radeon RX 580 Series - using the open source `amdgpu` driver, `srcversion: 4C17F56561301970174720`
- Motherboard: ASUS Z87M-PLUS

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Could this be an issue with "arch compiles prod software with asserts on" type of deal?
Have a look at [this bug-report](https://github.com/surge-synthesizer/surge/issues/7401) to see what I mean.

I bought the RX580 second-hand to replace my GTX970, spesifically because I wanted a better user experience with Wayland. I must admit that it's been a while since I've been using Darktable after getting my RX580, because of a period of newfound interest in gaming (the "new" GPU had to be tried out), but I think Darktable ran fine before when I had my GTX970 in operation.

Another thing that might be worth mentioning, is that the early access beta of [Bitwig](https://www.bitwig.com/) 5.2 crashes my GPU driver. One of Bitwig's 5.2 mayor new features is that it frees the CPU from drawing the graphics and offloads it on to the GPU. [Polarity Music has a video about this, saying Bitwig now behaves like a game.](https://youtu.be/z4wCmJWyADE)

I have verified that Vulkan is working with `vkcube` and Portal 2.
`libOpenCL` is detected by Darktable.

I hope the above context have some relevance.
I must also admit that I have some suspicion that there might be something wrong with my setup - so yeah, I'm grasping at straws here.

**Comment by victoryforce** [comment]
> I must also admit that I have some suspicion that there might be something wrong with my setup - so yeah, I'm grasping at straws here.

So we can be busy looking for a black cat in a dark room when it's not actually there... :)

strace is of no help here. Maybe try running datktable under the debugger and attach the backrace. This does not guarantee that we can get enough information to understand the reason, but it is worth a try.

**Comment by ralfbrown** [comment]
The `free()` message is from libc.  I agree with @kmilos that it's probably a system library version mismatch.

**Comment by jhillest** [comment]
@kmilos I went to #archlinux @ libera.chat and got help from "Namarrgon" and "gromit" there.
It was suggested I uninstall the [opencl-amd](https://aur.archlinux.org/packages/opencl-amd) package, which I did.

Turns out there **was** something wrong with my setup, because now, Darktable is usable again, but without OpenCL-support (until i find a solution).

@victoryforce I learned how to do a proper backtrace with GDB.
[darktable-gdb.log](https://github.com/user-attachments/files/15531872/darktable-gdb.log)

I also learned that AMD has dropped [ROCm support for the RX5xxx series GPU's](https://github.com/ROCm/ROCm/issues/1659)

Thanks for your input, it was helpful.
I'll go looking for that black cat on my own now :)

**Comment by ralfbrown** [comment]
The backtrace confirms that it was ROCm crashing.
```
#5  0x00007ffff76b3085 in malloc_printerr (str=str@entry=0x7ffff77c006b "free(): invalid pointer") at malloc.c:5772
#6  0x00007ffff76b549c in _int_free (av=<optimized out>, p=p@entry=0x60bf70, have_lock=have_lock@entry=0) at malloc.c:4507
        size = <optimized out>
        fb = <optimized out>
#7  0x00007ffff76b7dae in __GI___libc_free (mem=0x60bf80) at malloc.c:3398
        ar_ptr = <optimized out>
        p = 0x60bf70
        err = 12
#8  0x00007fffdff2fc70 in ??? () at /opt/rocm-6.1.1/lib/libamdocl64.so
```
