### ISSUE TITLE
Cant find point of procedure CreateFile2 in DLL-file KERNEL32.dll

### ISSUE THREAD

**Issue by amateurben** [darktable-org/darktable#16911]
### Describe the bug

Starting de execute file te first time i get an error as specified in the title of this issue.
My operatings system is Windows 7.

### Steps to reproduce

1. Download Windows version of dark table
2. Installation compleet
3. Execute program
4. Error

### Expected behavior

starting the program

### Logfile | Screenshot | Screencast

not available

### Commit

starting the program

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

windows version from website; there's only one

### What OS are you using?

Windows

### What is the version of your OS?

Windows 7

### Describe your system?

PC with windows 7

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

GPU CARd and driver ???

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I have none additional context

**Comment by victoryforce** [comment]
Windows 7 is unsupported
