### ISSUE TITLE
Film rolls are removed recursively

### ISSUE THREAD

**Issue by somename-123** [darktable-org/darktable#16921]
### Describe the bug

Given the directory structure:

```
top
├── nested
│   ├── nested image.dng
│   └── nested image.dng.xmp
├── top image.dng
└── top image.dng.xmp
```

Removing the ``top`` film roll also removes the ``nested`` film roll, while UI shows that the ``top`` film roll only contains ``top image.dng``.

### Steps to reproduce

1. Import -> add to library...
2. Add photos (either by checking "recursive directory" or individually).
3. Right click -> remove... on the ``top`` film roll.

### Expected behavior

darktable should not remove film rolls recursively

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.7.0+1332~geeb6ad3f8d

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 40

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment]
When you try and remove a nested filmroll, how should it work?  
* Fail silently?
* Refuse to give you the option to remove?
* Fail with a message?
* ???

**Comment by somename-123** [comment]
Just to clarify what I am talking about. I know, should've added them in the original issue.

https://github.com/darktable-org/darktable/assets/57208295/4fd40ac6-5206-41c4-8696-d19bcec59707


https://github.com/darktable-org/darktable/assets/57208295/a019394a-619c-4f95-b2ee-25ba0b780b48

> When you try and remove a nested filmroll, how should it work?

I guess only remove the first layer.

**Comment by wpferguson** [comment]
The files on disk are still there, so you could just move the nested directory out from under top, and import it again.  When you delete a film roll, it only affects the database.

**Comment by somename-123** [comment]
Got it, just thought it was a bug. Closing.
