### ISSUE TITLE
Sony UMC-R10C

### ISSUE THREAD

**Issue by dogmaphobic** [darktable-org/darktable#16937]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

_Done_

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
@dogmaphobic thank you for contributing the sample!

**Comment by dogmaphobic** [comment]
@kmilos 

> Please feel free to test the linked PR.

Tested and works fine. Thanks!
