### ISSUE TITLE
darkroom guide lines do not appear in dt 4.7 on Windows

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#16943]
### Describe the bug

I am testing dt 4.7 under Windows. 
In the darkroom the guide lines do not appear when using the toggle button or the “g” shortcut.

### Steps to reproduce

See above.

### Expected behavior

Guide lines should appear when using the toggle button or the “g” shortcut.

### Where did you obtain darktable from?

GitHub nightly

### darktable version

“4.7.0+1347~gbea7622b61” for Windows; also didn’t work on “4.7.0+1334~gf3245d1a5b”.

### What OS are you using?

Windows

### What is the version of your OS?

Microsoft Windows 11 Pro

### Describe your system?

Microsoft Windows 11 Pro 10.0.22631 Build 22631
Computer/laptop MSI P65 Creator 9SG
Processor Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, 2301 MHz, 8 core('s), 16 threads
BIOS American Megatrends Inc. E16Q4IMS.318, 18/05/2020
RAM 32,0 GB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Geforce RTX 2080 with Max-Q – 8 GB - NVIDIA Studio Driver 555.99

**Comment by MStraeten** [comment]
could not reproduce this with a current master build

**Comment by cabuy** [comment]
guide lines back after dt recreating its default darktablerc
--------------------------------------------------------------
So can be closed ... . 
I don't know what happened to my darktablerc file but ... : after dt recreating a default darktablerc file, the guide lines are back. 
Of course this implies reworking other preferences or darktablerc updates, but it seems to be worth now doing that.

**Comment by cabuy** [comment]
Maarten thank you for your feedback.
