### ISSUE TITLE
 Darktable's extremely slow export 

### ISSUE THREAD

**Issue by ktatar156** [darktable-org/darktable#16958]
### Describe the bug

Hello,

Since I upgraded somewhere from v3.x to latest one, exporting photos to JPEG works extremely slow and consumes a lot of RAM. I also observe that this process, freezes PC for few seconds (for each photo).
Do you know guys what changed in this area?

Furthermore, using some of modules, increase dramatically the size of jpeg files (from 6-7 mb to 13-14 mb with filmic rgb module turned on).
CPU: AMD Ryzen 5 2600X, 3.6 GHz; GPU: RX590 8GB; RAM: 2x8GB, darktable 4.6.1 on Arch linux. 

darktable-cltest https://pastebin.com/q7WzG8zz

I run export on the same (duplicated image) - one with 'filmic rgb' and one without - both of them are slow, but the second (with 'filmic rgb' turned on) was extremely slow....

With OpenCL turned ON
https://pastebin.com/VJnNJ0A5
With OpenCL turned OFF (it's even worse):
https://pastebin.com/AQb7sq0a
So it seems that using 'Diffuse' module with 'Filmic RGB' slows dramatically the whole process.. When I turn Diffuse or Sharpen OFF, export work good!

Furthermore, after some time while using darktable (several clicks on different images, etc.) sth broke the view - going into darkable mode, DT shows artifacts instead of image:

https://imagebin.ca/v/84NnIKwVN4Lh

(and also export with this artifacts... :( ) - I need to restart Darktable to get it working again :(

So I suffers three issues:
1. Slow exporting.... :(
2. Artifacts instead of my photos....
3. Exporting consumes a lot of ram (is it normal?) When I start exporting, first photo takes 5-7 GB of RAM.... And when i close DT, this 5-7 RAM is not released... :(

### Steps to reproduce

Described above

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch

### Are you using OpenCL GPU in darktable?

Yes

**Comment by ralfbrown** [comment]
As pointed out over on pixls.us, your second instance of Diffuse&Sharpen is taking the bulk of the processing time.  If your "3.x" version was 3.6 or earlier, that module didn't exist yet, so it wouldn't have added to the processing time.  In fact, 4.6 on CPU is substantially faster than any 3.x version *if you use the same sidecar* made with the older version.

**Comment by gi-man** [comment]
I can't find the pixls.us thread. You are using rusticl and I am not sure if it is supported. What's the results with rocm?

**Comment by jenshannoschwalm** [comment]
1. there are some issues with rustcl running dt 4.6, some have been fixed upstream, some in dt master.
2. there was a bug in export resulting in excessive performance drop depending on the output size and "high quality " setting, also fixed in master

**Comment by ralfbrown** [comment]
Ah, misremembered, it was Reddit: https://old.reddit.com/r/DarkTable/comments/1d6zvz6/darktables_extremely_slow_export/
