### ISSUE TITLE
www.darktable.org - please specify system requirements (MS Windows) in a prominent position

### ISSUE THREAD

**Issue by caganer** [darktable-org/darktable#16978]
**Is your feature request related to a problem? Please describe.**

I installed and tried running darktable-4.6.1-win64.exe on Windows 7 Pro SP1 running 0Patch Pro and got the error message precluding moving further:
"darktable.exe - Entry Point Not Found
The procedure entry point CreateFile2 could not be located in the dynamic link library kernel32.dll"

I assume this signifies that darktable for Windows requires Windows 10 or more recent. If so could you action as below?

**Describe the solution you'd like**

I suggest the system requirements be made more prominent on the www.darktable.org page, perhaps add to the FAQ?

**Alternatives**

Put system requirements on the www.darktable.org landing/home page?

**Additional context**

None applicable.

**Comment by gi-man** [comment]
> Supported platforms
    Linux (64-bit)
    FreeBSD (64-bit)
    Windows (64-bit), 8.1 w/ [UCRT](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c) and later
    macOS 13.5 and later

https://github.com/darktable-org/darktable?tab=readme-ov-file#supported-platforms

**Comment by victoryforce** [comment]
You better address it here: https://github.com/darktable-org/dtorg/issues
