### ISSUE TITLE
Clipping threshold does not exist in the exposure module 

### ISSUE THREAD

**Issue by rstanuwijaya** [darktable-org/darktable#16971]
### Describe the bug

The 4.6 manual mentions that there is a clipping threshold slider in the exposure module, but it is nonexistent for me. 

link to the manual page: https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/exposure/

exposure module:
![image](https://github.com/darktable-org/darktable/assets/55012032/6ea5a40f-cb47-4250-8861-6534971e22c2)

### Steps to reproduce

N/A

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

SteamOS Holo

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
@rstanuwijaya Thanks for the bug report. Indeed, this inaccuracy is present in the user manual for 4.6. The error has already been fixed in https://github.com/darktable-org/dtdocs/pull/613 and will not be in the next manual release.
