### ISSUE TITLE
Export JPEG seems Broken on Flatpak 4.6.1 Debian 12.5

### ISSUE THREAD

**Issue by dorpauli** [darktable-org/darktable#16979]
### Describe the bug

If i want to export an image as jpeg (8-bit), i'm not able to set any options for that format. Then when i export the image, it is exported as whatever was selected before jpeg, for example png, tiff or webp. This is the case in lighttable and darkroom. I have installed Darktable via Flatpak and it's on version 4.6.1. I am on Debian 12.5. 
![image](https://github.com/darktable-org/darktable/assets/70518303/36f276f3-fcbe-4fa2-b473-8bfc908d4e97)

### Steps to reproduce

1. Start Darktable
2. Select any Image
3. Try to export as jpeg if sth. else was selected before

### Expected behavior

I should make settings like jpeg compression and so on. And then it should export as jpeg.

### Where did you obtain darktable from?

flatpak

### darktable version

darktable developers org.darktable.Darktable 4.6.1 stable system

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12.5

### Describe your system?

Its a thinkpad x1 extreme gen2 with 32gb ram and an core i7 and an nvidia graphics card. I run on Gnome Desktop with X11 instead of new wayland. 

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

OpenCL is not selectable in settings

**Comment by ptilopteri** [comment]
* Paul F. ***@***.***> [06-11-24 15:44]:
> ### Describe the bug
> 
> If i want to export an image as jpeg (8-bit), i'm not able to set any
> !options for that format.  Then when i export the image, it is exported
> !as whatever was selected before jpeg, for example png, tiff or webp. 
> !This is the case in lighttable and darkroom.  I have installed
> !Darktable via Flatpak and it's on version 4.6.1.  I am on Debian 12.5. 
> ![image](https://github.com/darktable-org/darktable/assets/70518303/36f276f3-fcbe-4fa2-b473-8bfc908d4e97)

I don't know, am not familiar with flatpack(darktable), but it works
correctly on my compiled master on openSUSE Tumbleweed.

note that the dt developers do not package dt.  I would contact the
flatpak publisher about your problem.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by dorpauli** [comment]
> * Paul F. ***@***.***> [06-11-24 15:44]:
> > ### Describe the bug
> > 
> > If i want to export an image as jpeg (8-bit), i'm not able to set any
> > !options for that format.  Then when i export the image, it is exported
> > !as whatever was selected before jpeg, for example png, tiff or webp. 
> > !This is the case in lighttable and darkroom.  I have installed
> > !Darktable via Flatpak and it's on version 4.6.1.  I am on Debian 12.5. 
> > ![image](https://github.com/darktable-org/darktable/assets/70518303/36f276f3-fcbe-4fa2-b473-8bfc908d4e97)
> 
> I don't know, am not familiar with flatpack(darktable), but it works
> correctly on my compiled master on openSUSE Tumbleweed.
> 
> note that the dt developers do not package dt.  I would contact the
> flatpak publisher about your problem.
> 
> 
> -- 
> (paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
> facebook/ptilopteri
> Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc
> 

Who are the Flatpak developers? Do they have a Github page where i can create this issue for them?

**Comment by victoryforce** [comment]
> Who are the Flatpak developers? Do they have a Github page where i can create this issue for them?

Yes, you can raise issue at https://github.com/flathub/org.darktable.Darktable/issues

> I should make settings like jpeg compression and so on. And then it should export as jpeg.

For your Linux distro release, Debian 12, there is a much easier way to install the latest darktable release, use the OBS repository: see links at https://www.darktable.org/install/

**Comment by dorpauli** [comment]
I opened an issue in the other repo as you can see. I'm closing this one for now.
