### ISSUE TITLE
Script manager fails to start due to "Lua API version 9.3.0 or later required"

### ISSUE THREAD

**Issue by LucasGGamerM** [darktable-org/darktable#16995]
### Describe the bug

I cannot enable the script_manager due to this error, and even manually editing the script to allow for an earlier api, it still fails. 

### Steps to reproduce

Install darktable through the flatpak, enable the script manager through the luarc file, restart darktable and see that it does not appear.

### Expected behavior

darktable should load the script manager

### Commit

No idea :(

### Where did you obtain darktable from?

flatpak

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

PopOS 22.04

### Describe your system?

Nothing much, really 

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Nvidia 3050, using latest available driver

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The lua scripts installer tab disappeared, and I couldn't make it work again with the info available on the internet. 

My luarc file looks like this: 

```
require "tools/script_manager"
```

**Comment by wpferguson** [comment]
First let's fix your problem.  Go into the lua directory and enter the command `git checkout API-9.2.0`. 

That will get you up and running.

The fix for this is to make scripts_installer API aware.  The only time it really becomes an issue is this one, where the script_manager API requirement changes.

**Comment by LucasGGamerM** [comment]
> git checkout API-9.2.0

Thank you! That fixed my issue.
