### ISSUE TITLE
Canon CR3 raw image cannot shown in darkroom due to white balance read issue

### ISSUE THREAD

**Issue by Pretorian2077** [darktable-org/darktable#17005]
### Describe the bug
After import CR3 raw files (not cRAW) from Canon EOS250D camera the cannot open in darkroom with white balance error.
After ~10-15 sec it change back to lighttable.

`19.1366 [libraw_open] extensions whitelist: cr3'`
`19.7325 [libraw_open] detected unsupported image 20240616_0278.CR3'`
`19.7449 [qoi_open] no proper file header in /home/*****/Pictures/PhotoLAB/*********/20240616_0278.CR3`
`19.7893 [temperature] failed to read camera white balance information from 20240616_0278.CR3'!`
`19.7900 [temperature] failed to read camera white balance information from 20240616_0278.CR3'!`
`22.1535 [temperature] failed to read camera white balance information from 20240616_0278.CR3'!`
`22.1539 [temperature] Canon EOS 250D' color matrix not found for image`
`22.1540 [temperature] failed to read camera white balance information from 20240616_0278.CR3'!`
`22.2215 [colorin] could not find requested profile standard color matrix'!`

### Steps to reproduce
Click on the specific image in lightroom

### Expected behavior
Darktable should display this image in darkroom, as with the surrounding images, as it worked with Ubuntu 22.04 in last year.

### OS
- Ubuntu 24.04
- Darktable 4.6.1 (checked with snap and deb version)

**Comment by ralfbrown** [comment]
We really should figure out a way to stop the pipeline before it gets to the white balance module when there's an issue reading a file....

CR3 format is problematic, as it requires both LibRaw and exiv2 to have been compiled with CR3 support.  If either were compiled without that support, there's nothing darktable can do to read CR3 files (LibRaw) or handle their metadata, including white balance (exiv2).  Unfortunately, the container format for CR3 (unlike every other raw format) is based on the heavily patent-encumbered MP4 format, so a lot of packagers are unwilling to enable support by default....

**Comment by Pretorian2077** [comment]
Thanks for feedback. As in 2022 and 2023 I have made CR3 pictures and all are visible correctly I have studied and realized the exiv2 package was not installed. I have installed it and for safety installed the libraw packages incl. libraw-dev.
The white balance issue has been existed with the imported pictures. I have re-import the pictures from camera and the white balance issue has gone.
