### ISSUE TITLE
Simultaneous edit inside Darkroom

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#17010]
**Is your feature request related to a problem? Please describe.**

- A friend who happens to be a lightroom user showed me how he does his bulk editing. I noticed he selects the photos he wanted to edit inside of Develop module. When he made some changes on one of the selected photos, it also affects the rest of the selected photos. I tried that in Darktable but I noticed there is no such feature. I have to go outside darkroom, click Select Copy button before highlighting the photos and clicking the Paste button for the changes to take effect on the selected photos.   

**Describe the solution you'd like**

- I wish I can make the changes inside of darkroom on the selected photos. That way it make my editing a whole lot faster.

**Alternatives**

- I don't think there is an alternative way of doing this other that going back to Lighttable module, click Copy button, select the effects, click Ok, highlight the photos and clicking the Paste button. I wish I can do that inside of Darkroom module.

**Additional context**

- Please see attached screenshot

![darkroom_editing](https://github.com/darktable-org/darktable/assets/154827269/cc7a3d1b-fdd3-40a0-8ac6-2d675e202242)

**Comment by ralfbrown** [comment]
You can use keyboard shortcuts to copy and paste edits from inside darkroom mode.

Ctrl-C (copy entire history) or Shift-Ctrl-C (copy selectively).
Then in the filmstrip at bottom, Ctrl-Click to select first image, Shift-Click to select end of range of image (optional: Shift-Ctrl-A first to clear previous selection).
Finally, Ctrl-V or Shift-Ctrl-V to paste edits.  The thumbnails in the filmstrip will briefly show "working..." as they regenerate with the updated edits.

Actual live updates to multiple images would require substantial re-architecting of darktable's internals.

**Comment by blackzerotype** [comment]
> > You can use keyboard shortcuts to copy and paste edits from inside darkroom mode.
> > Ctrl-C (copy entire history) or Shift-Ctrl-C (copy selectively). Then in the filmstrip at bottom, Ctrl-Click to select first image, Shift-Click to select end of range of image (optional: Shift-Ctrl-A first to clear previous selection). Finally, Ctrl-V or Shift-Ctrl-V to paste edits. The thumbnails in the filmstrip will briefly show "working..." as they regenerate with the updated edits.
> > Actual live updates to multiple images would require substantial re-architecting of darktable's internals.
> 
> @ralfbrown
> 
>     * It worked. Many thanks. But I noticed that it worked and then for some reason, it doesn't apply to the other photos when I repeat the same process. Could there could be some glitch?

**Comment by ralfbrown** [comment]
Please describe what you are seeing when you try to repeat.  In particular, where is your mouse pointer at the time? (darktable has an unusual feature where hovering over an image has priority over the selection if the hovered image is not part of the selection)

**Comment by blackzerotype** [comment]
> Please describe what you are seeing when you try to repeat. In particular, where is your mouse pointer at the time? (darktable has an unusual feature where hovering over an image has priority over the selection if the hovered image is not part of the selection)
- I noticed that if the mouse is pointed away from the selected photos the changes doesn't take effect. When I point the mouse at the selected photos sometimes it work sometimes doesn't so I had to repeat the whole process that you suggested and it works. The behavior appears to  be inconsistent.

**Comment by wpferguson** [comment]
The inconsistent behavior is being addressed/looked at/discussed in #16850.

**Comment by victoryforce** [comment]
> It worked. Many thanks

@blackzerotype Can we close this issue?
