### ISSUE TITLE
Darktable keeps crashing when export is started.

### ISSUE THREAD

**Issue by Katja8610** [darktable-org/darktable#17020]
### Describe the bug

Darktable keeps chrahing when I try to export pictures.

### Steps to reproduce

1. open darktable
2. choose picture
3. export to jpeg 
4. Export starts
5. Darktable chrahes

### Expected behavior

export the file

### Logfile | Screenshot | Screencast

[](url)
[darktable_bt_FMLKP2.txt](https://github.com/user-attachments/files/15906575/darktable_bt_FMLKP2.txt)
[darktable_bt_TXGDP2.txt](https://github.com/user-attachments/files/15906576/darktable_bt_TXGDP2.txt)
[darktable_bt_ZR6PP2.txt](https://github.com/user-attachments/files/15906577/darktable_bt_ZR6PP2.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 23H2

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Choosing one or multiple files or exporting in another format does the same thing.
Darktable keeps chrashing.

**Comment by MStraeten** [comment]
have a look at https://www.darktable.org/about/faq/#faq-windows-bugs and https://www.darktable.org/about/faq/#faq-windows-logs to help helping you since a crash during export isn’t known to be buggy.
So run darktable with -d common option and provide the logfile …

**Comment by ralfbrown** [comment]
The first backtrace is empty.  The other two (FMLKP2 and ZR6PP2) indicate a crash at startup, in the function which would tell you that the database is locked by another (possibly crashed) instance of darktable.

**Comment by victoryforce** [comment]
@Katja8610 As explained above, the contents of non-empty backtrace files indicate an issue with the deletion of lock files after the previous program crash. This issue was only on the Windows platform and was fixed in the 4.6.1 release. Therefore, either you don't actually have darktable 4.6.1 (maybe 4.6.0?), or you attached files from older crashes.

Since the 4.8.0 release is now available, try to see if the crashes are reproduced on this version.

**Comment by Katja8610** [comment]
I moved some stuff, to another harddrive. The problem did not occur again.
Thanks for the help.
