### ISSUE TITLE
Gimp cannot find darktable plugin for version 4.8.0

### ISSUE THREAD

**Issue by rouelle** [darktable-org/darktable#17039]
### Describe the bug

After upgrading darktable to 4.8.0 gimp can no longer open raw files. It complains that a raw plugin is missing even though darktable is installed Darktable can open the file directly though.

Reverting to darktable 4.6.1 it works again. Same bug as https://github.com/darktable-org/darktable/issues/15968 that was closed for 4.6.0 and corrected in DT 4.6.1.

### Steps to reproduce

- Update darktable to version 4.8.0
- Try to open a raw file with gimp.
- Gimp complains that it cannot find a raw plugin
- There is no darktable plugin in Gimp import file settings

### Expected behavior

darktable should open when a raw image is opened in gimp and darktable send back the image in gimp after treatment.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

Linux 6.9.5-arch1-1
GNOME 46.2
Wayland, display 3840x2160 @ 60Hz
16 Gb memory

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

GPU AMD Radeon RX 570 amdgpu driver

**Comment by jenshannoschwalm** [comment]
The fix is already pending in gimp. Next sub release will have it

**Comment by rouelle** [comment]
Thanks, I then close the bug :-)
