### ISSUE TITLE
4.8.0 don't work on Mac 12.7.5 Monterey

### ISSUE THREAD

**Issue by jollijumper** [darktable-org/darktable#17042]
### Describe the bug

unable to start darktable after update to 4.8.0

<img width="297" alt="Bildschirmfoto 2024-06-23 um 11 26 45" src="https://github.com/darktable-org/darktable/assets/1527883/01021ead-b486-42b5-b561-1e448993d33f">

### Steps to reproduce

download 
<img width="482" alt="Bildschirmfoto 2024-06-23 um 11 29 26" src="https://github.com/darktable-org/darktable/assets/1527883/ed032093-6aa8-4f4e-ad97-e557bc8047dd">

### Expected behavior

should start according to website "macOS These bundles support macOS versions starting with 12.5 (Monterey)!

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 12.7.5 Monterey

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
> should start according to website "macOS These bundles support macOS versions starting with 12.5 (Monterey)!

This is an error on the website page where the macOS version requirements have not been updated for the latest darktable release. This will be fixed soon. The actual minimum requirement is macOS 13.5 Ventura.

So I'm closing this issue since darktable won't work on Monterey.

**Comment by ralfbrown** [comment]
At least not the official build.  There is at least one unofficial build for older MacOS versions.

**Comment by 1837456** [comment]
I have of course read about the new policy since version 4.4 but since macOS Monterey ist still officially supported by Apple I do not understand that 4.8 drops support for Monterey. Maybe someone can help me to understand this topic better.

**Comment by zisoft** [comment]
We have discussed this and you are right: The support for macOS 12 was dropped too early with this release. Apple will drop support for macOS 12 when macOS 15 is released in October so the darktable winter release (5.0) would be the time to drop.

We will keep an eye on that for the next upcoming macOS releases.
