### ISSUE TITLE
Using Aspect Adjust for desqueezing anamorphic images produces wrong vertical resolution when exported

### ISSUE THREAD

**Issue by doppioslash** [darktable-org/darktable#17046]
### Describe the bug

I'm using a Sirui 1.33x anamorphic lens on a Canon M50, shooting at 3:2, original resolution: 6024x**4020**.
I'm desqueezing the photo with the Rotate and Perspective->Lens Model->Specific->Aspect Adjust->1.33. 
The desqueezed photos look right within Darktable, but when I export them the output resolution is wrong: it's 6947x**3485** instead of the expected 8012x**4020**. 

It seems they have been scaled down vertically, for some reason.
If you force the resolution to be the expected one, the image is first downscaled and then upscaled, significantly losing sharpness and detail.

Original photo resolution:
![Original Resolution](https://github.com/darktable-org/darktable/assets/508324/6932a5f2-575d-452a-89fc-7a5a78e0f5a0)

Export settings:
![Export Settings](https://github.com/darktable-org/darktable/assets/508324/253ee007-ac98-41d1-a604-a9f2c2a1a92a)

Aspect adjust settings:
![Aspect Adjust Setting](https://github.com/darktable-org/darktable/assets/508324/a37fd8df-e48b-43e1-9778-8ec931ed178f)
Note: changing focal length and crop factor in the settings above has **no effect**.

Output image resolution when opened in Affinity:
![Output Image Resolution when opened in Affinity](https://github.com/darktable-org/darktable/assets/508324/5462e62e-6275-46d4-bf89-da4f226c337e)

### Steps to reproduce

1. Change aspect ratio to 1.33: Rotate and Perspective->Lens Model->Specific->Aspect Adjust->1.33
2. Export with empty "size", default settings. Scale 1 will also produce the same result.
3. Check that the output jpg have decreased vertical resolution from the original.

### Expected behavior

darktable should not downscale the image at all

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Original Raw (CR3) zipped
[IMG_8967.zip](https://github.com/user-attachments/files/15946112/IMG_8967.zip)

Example of export with wrong resolution:
![IMG_8967_desqueezed_wrong_resolution](https://github.com/darktable-org/darktable/assets/508324/1f29e84b-87ab-4c9e-9563-f93fba097d64)

**Comment by jenshannoschwalm** [comment]
@doppioslash i can confirm this, unfortunately the very tricky "solver" maths is not suited well for this purpose.

Please note that we have good support for anamorph lenses via the "scale pixels" module, it's much faster, works in an excellent position in the pixelpipe and allows presets for your lens to be automatically applied.

@TurboGit we missed that in the release note: Support for anamorphic lenses has been added to scale pixels

**Comment by doppioslash** [comment]
Thanks @jenshannoschwalm.
I installed the 4.9.0 nightly and tried with "scale pixels" and it does work.
