### ISSUE TITLE
DT 4.8.0 flatpak crashes when generate thumbnails in background is set to 5k

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#17047]
### Describe the bug

I tried to set DT to generate previews at 5k resolution (to generate level 7 cache files). In few seconds it crashes.
As a comparison I did the same when running DT from AppImage - it did not crash. However my library under AppImage is 300+ vs under Flatpak is likely around 20k

### Steps to reproduce

1. start DT from flatpak
2. go to settings - lighttable 
3. Enable disk back end for thumbnails cache
4. Enable disk backend for full preview cache
5. Set generate thumbnails to 5k

### Expected behavior

should generate level 7 cache

### Logfile | Screenshot | Screencast

[d all.txt](https://github.com/user-attachments/files/15948592/d.all.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

PopOS 22.04

### Describe your system?

OS: Pop!_OS 22.04 LTS x86_64 

Kernel: 6.9.3-76060903-generic 
Uptime: 4 hours, 52 mins 
Packages: 3187 (dpkg), 81 (flatpak) 
Shell: bash 5.1.16 
Resolution: 2560x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 3900 (24) @ 3.100GHz 
GPU: NVIDIA GeForce RTX 2070 Mobile / Max-Q Refresh 
Memory: 8872MiB / 64194MiB 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 2070 Mobile / Max-Q Refresh

**Comment by vancouverbluesea** [comment]
I maybe doing something wrong here. Perhaps a combination of settings.
Currently my settings are like this
![image](https://github.com/darktable-org/darktable/assets/69771189/1871e48e-f99d-4f10-9ddc-650007a01582)
and for now it is working.
I did change a few of them and I am afraid I got lost at some point. Most likely the first one "use raw file instead of jpg was set to always. But then - I do have some .jpg
also 
`flatpak run --command=darktable-generate-cache org.darktable.Darktable -m 7
`
works just fine.
I'd like to monitor for 1-2 days please and if it completes okay I am going to close the issue.

**Comment by jenshannoschwalm** [comment]
Flatpacks mostly restrict memory, this is not yet checked properly in dt. Thus the crash.

**Comment by jenshannoschwalm** [comment]
@TurboGit we should really try to find out about available memory for flatpacks and alike ...

**Comment by vancouverbluesea** [comment]
I cannot observe the issue anymore. closing the issue.
