### ISSUE TITLE
file export broken

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#17054]
### Describe the bug

in current buiild, 4.9.0+33~ga93d38c4db, I have export set to:
"$(FILE_FOLDER)/DrkTbl$FILE_NAME)" 
but photos are being exported as:  DrkTbl$FILE_NAME).jpg

### Steps to reproduce

select a photo and export it

### Expected behavior

photos should be exported to $FOLDER/DrkTbl/xxxxxxx.jpg

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+33~ga93d38c4db

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed 20240621

### Describe your system?

not relevant, happens on 5 boxes, all current Tumbleweed

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

do not have another version available

**Comment by ptilopteri** [comment]
nvrm, something has changed in the default configuration concerning export parameters that has affected all my installs

**Comment by zisoft** [comment]
> $(FILE_FOLDER)/DrkTbl$FILE_NAME)

You are missing the directory separator `/` and the opening parentheses `$(`

--> `$(FILE_FOLDER)/DrkTbl/$(FILE_NAME)`

**Comment by ptilopteri** [comment]
tks, closing

**Comment by ptilopteri** [comment]
ps, there was a change
previous there was 
  session/base_directory_pattern=$(PICTURES_FOLDER)/DrkTbl
now
  plugins/imageio/storage/disk/file_directory=$(FILE_FOLDER)/DrkTbl$FILE_NAME)


that is a SURPRISE  
and surprises and not usually good :(
