### ISSUE TITLE
Copy & import of file does not include darktable xmp file

### ISSUE THREAD

**Issue by petrushy** [darktable-org/darktable#17091]
### Describe the bug

Reading 

https://docs.darktable.org/usermanual/4.6/en/overview/sidecar-files/sidecar-import/

I would expect that importing a folder with darktable edited photos (not yet in database) would include the xmp files (and edits) in that source folder and copy them also to the import destination. This does not seem to be the case, no xmp file is generated or copied for the RAW fies. For jpg where i have no xmp file, there is a new xmp file generated in the import target dir.

I have it set to use original filename.

Note that "add to library" takes the .xmp files into consideration if the source folder is added through that. But the purpose is to get it into the same directory structure (and avoid duplicates).

### Steps to reproduce

1 copy & import the directory with (on other computer) darktable edited photos (raw + xmp)
2 open the folder in desktop env
3 review files and compare with source, no xmp files copied 

### Expected behavior

darktable should import the original (darktable generated) .xmp files into the destination

### Where did you obtain darktable from?

flatpak

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

PopOS 22.04

### Are you using OpenCL GPU in darktable?

No

**Comment by pehar1** [comment]
Read https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/import/ section copy & import. This is intended behaviour.

**Comment by petrushy** [comment]
Ok, did not see that! If that is the intended behaviour, I think this text is somewhat unclear:

https://docs.darktable.org/usermanual/4.6/en/overview/sidecar-files/sidecar-import/

_"When importing an image, darktable automatically checks if it is accompanied by a sidecar file. As well as looking for files named <basename>.<extension>.xmp and <basename>_<number>.<extension>.xmp (darktable’s XMP file naming formats) darktable also checks for the presence of a file in the form <basename>.xmp (the naming format for Lightroom’s XMP sidecar files). Files with the latter naming format will be read by darktable but will not be written to. Once the image has been imported, darktable will generate an additional XMP file using its own naming convention."_

The darktable xmp I think matches <basename>.<extension>.xmp but the text doesn't really state what darktable does with it. If it is only lightroom xmp that is imported I would suggest to remove the initial text.

**Comment by ptilopteri** [comment]
* Petrus Hyvönen ***@***.***> [07-06-24 09:44]:
> Ok, did not see that! If that is the intended behaviour, I think this text is somewhat unclear:
> 
> https://docs.darktable.org/usermanual/4.6/en/overview/sidecar-files/sidecar-import/
> 
> _"When importing an image, darktable automatically checks if it is accompanied by a sidecar file. As well as looking for files named <basename>.<extension>.xmp and <basename>_<number>.<extension>.xmp (darktable’s XMP file naming formats) darktable also checks for the presence of a file in the form <basename>.xmp (the naming format for Lightroom’s XMP sidecar files). Files with the latter naming format will be read by darktable but will not be written to. Once the image has been imported, darktable will generate an additional XMP file using its own naming convention."_
> 
> The darktable xmp I think matches <basename>.<extension>.xmp but the
> text doesn't really state what darktable does with it.  If it is only
> lightroom xmp that is imported I would suggest to remove the initial
> text.

the article referred is: 
  importing sidecar files generated by other applications


and does not explain dt's own xmp files which is:
  sidecar files
  https://docs.darktable.org/usermanual/4.6/en/overview/sidecar-files/sidecar/

  

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by petrushy** [comment]
Closing this, as stated this is intended behaviour, and seems to be clear for others.

**Comment by msharp1** [comment]
Hi @petrushy, using darktable 5.2.1 here. I spent one hour working on workflow migrating from lightroom, and I have found the section "importing sidecar files generated by other applications" confusing as well.
If "copy & import" doesn't read any XMP file (which seems the expected behavior), the article shouldn't use the word "importing", like in "When importing an image, darktable automatically checks if it..."

**Comment by TurboGit** [comment]
By all mean if you think the manual is not clear please contribute a rewording. Thanks.
