### ISSUE TITLE
"trouble message for channelmixerrgb" when opening image

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#17096]
### Describe the bug

I think it happens with all my Panasonic TZ100 and LX7 images, even with a clean config + DB.
Darktable logs messages like this:
trouble message for channelmixerrgb : temp=0x5723a28caf10 adapt=0x5723a2a806f0

### Steps to reproduce

1. Download http://tech.kovacs-telekes.org/files/2024-07-06-trouble-message-for-channelmixerrgb/2024-06-27-18-34-41-P1030720.RW2
2. Import into darktable
3. Open it in the darkroom.

I run darktable with `darktable  -d tiling -d opencl -d perf -d common -d pipe -d verbose`.

### Logfile | Screenshot | Screencast

[darktable.log](https://github.com/user-attachments/files/16115735/darktable.log)

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+56~ga6ac3d4d30

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

X11, Ryzen 5 5600X, 64 GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060 with 6 GB, driver 535.171.04

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Occurs with/without OpenCL

**Comment by jenshannoschwalm** [comment]
Right - this is just a message about to-be-checked module data only available with the verbose switch, not relevant except while debugging temperature trouble stuff. So - **not a bug** at all.

**Comment by kofa73** [comment]
Thanks for the clarification. I did not see any image corruption, but I thought I'd mention it.
