### ISSUE TITLE
Lua scripts not working in 4.8 (MacOS)

### ISSUE THREAD

**Issue by mingos777** [darktable-org/darktable#17105]
### Describe the bug

Lua scripts tab is completely gone. When trying to use a Lua script that I've bound to a key shortcut, darktable claims the scripts aren't active.
<img width="1920" alt="Screenshot 2024-07-07 at 22 32 59" src="https://github.com/darktable-org/darktable/assets/1941200/f2ce527f-2b08-455a-80c8-1fafcf251f97">

### Steps to reproduce

Update darktable from 4.6 using homebrew.
Open darktable 4.8 and enjoy the bug.

### Expected behavior

Lua scripts tab should be displayed; when using a script, it should work.

### Logfile | Screenshot | Screencast

Upon starting darktable with `-d lua`, I get this log:
```
(darktable:2427): Gtk-CRITICAL **: 22:23:42.767: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
     2,6095 LUA [script installer] dont show not set
     2,6095 LUA [script installer] checking for lua directory
     2,6095 LUA [script installer] checking for scripts
     2,6128 LUA [script installer] line is darktablerc
     2,6128 LUA [script installer] line is data.db
     2,6128 LUA [script installer] line is data.db-pre-4.2.1
     2,6128 LUA [script installer] line is data.db-pre-4.4.0
     2,6128 LUA [script installer] line is data.db-pre-4.4.2
     2,6128 LUA [script installer] line is data.db-pre-4.6.0
     2,6128 LUA [script installer] line is data.db-pre-4.8.0
     2,6128 LUA [script installer] line is data.db-snp-20240324192736
     2,6128 LUA [script installer] line is data.db-snp-20240402233114
     2,6128 LUA [script installer] line is data.db-snp-20240416181508
     2,6128 LUA [script installer] line is data.db-snp-20240425191256
     2,6128 LUA [script installer] line is data.db-snp-20240507231313
     2,6128 LUA [script installer] line is data.db-snp-20240515223853
     2,6128 LUA [script installer] line is data.db-snp-20240524202010
     2,6128 LUA [script installer] line is data.db-snp-20240610214304
     2,6128 LUA [script installer] line is data.db-snp-20240617234656
     2,6128 LUA [script installer] line is data.db-snp-20240626142854
     2,6128 LUA [script installer] line is data.db-snp-20240705003334
     2,6128 LUA [script installer] line is data.db.lock
     2,6128 LUA [script installer] line is library.db
     2,6128 LUA [script installer] line is library.db-pre-4.2.1
     2,6128 LUA [script installer] line is library.db-pre-4.4.0
     2,6128 LUA [script installer] line is library.db-pre-4.4.2
     2,6128 LUA [script installer] line is library.db-pre-4.6.0
     2,6128 LUA [script installer] line is library.db-pre-4.8.0
     2,6128 LUA [script installer] line is library.db-snp-20240324192736
     2,6128 LUA [script installer] line is library.db-snp-20240402233114
     2,6129 LUA [script installer] line is library.db-snp-20240416181508
     2,6129 LUA [script installer] line is library.db-snp-20240425191256
     2,6129 LUA [script installer] line is library.db-snp-20240507231313
     2,6129 LUA [script installer] line is library.db-snp-20240515223853
     2,6129 LUA [script installer] line is library.db-snp-20240524202010
     2,6129 LUA [script installer] line is library.db-snp-20240610214304
     2,6129 LUA [script installer] line is library.db-snp-20240617234656
     2,6129 LUA [script installer] line is library.db-snp-20240626142854
     2,6129 LUA [script installer] line is library.db-snp-20240705003334
     2,6129 LUA [script installer] line is library.db.lock
     2,6129 LUA [script installer] line is lua
     2,6129 LUA [script installer] scripts found
     2,6129 LUA [script installer] line is luarc
     2,6129 LUA [script installer] line is shortcutsrc
     2,6129 LUA [script installer] line is shortcutsrc.backup
     2,6129 LUA [script installer] line is shortcutsrc.defaults
     2,6129 LUA [script installer] line is shortcutsrc.edit
     2,6129 LUA [script installer] line is styles
     2,6129 LUA [script installer] line is user.css
     2,6129 LUA [script installer] line is watermarks
     2,6148 LUA ERROR : ...rs/mingos/.config/darktable/lua/tools/script_manager.lua:63: attempt to index a function value (local 'gettext')
```

### Commit

I don't know; I use whatever homebrew serves me.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.0

### What OS are you using?

Mac

### What is the version of your OS?

Sonoma 14.5

### Describe your system?

The issue is happening on both of my computers:

* Mac Mini M2 Pro, MacOS Sonoma 14.5, 32 GB RAM
* MacBook Air M3, MacOS Sonoma 14.5, 16 GB RAM

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

As described above: the issue is happening on Apple machines with the newest MacOS version on board, when running darktable 4.8 upgraded from 4.6 via homebrew. I don't know about other platforms or distribution channels. I also haven't done a clean install of darktable 4.8, only upgraded from 4.6.
Possibly related to #16812

**Comment by wpferguson** [comment]
That's exactly the issue you have.  Go into the lua directory and do a git pull to fix it, or remove the lua directory and use scripts installer to reinstall the scripts.

**Comment by zisoft** [comment]
@mingos777 can the issue be closed?

**Comment by mingos777** [comment]
@zisoft I'll let you decide. My issue is resolved. However, if there's a general problem with darktable leading people to this issue upon upgrading, I would say it's something that needs to be looked at. Not everyone will reach out on GH or be familiar with git. Anyway, up to you.
