### ISSUE TITLE
[Feature Request] Additional default theme choices, specifically Light Theme and High Contrast Themes

### ISSUE THREAD

**Issue by CryHavoc21** [darktable-org/darktable#17104]
**Is your feature request related to a problem? Please describe.**

Using darktable, I often find myself having trouble recognizing UI elements quickly. I find the contrast of the UI elements to be too low. 

Searching the discussion on open issues (#15994), it looks like the decision is made that the defaults should stay the defaults in pursuit of not distracting from the photo, and that any users that want to change it can do so from the "CSS tweaks" option. While I can appreciate this design, I believe that it might additionally be useful to provide some alternative defaults for users that like myself can swap to, provided preinstalled with the application. 

At minimum, I believe a light theme (light background, dark text) would be useful to include. Preferably, I would also like to include High Contrast Dark and High Contrast Light themes, along the lines of how Windows (or Github) provides both dark and light high contrast options. However, I think if we only wanted one theme to be added, it should be just the light theme.

**Describe the solution you'd like**

I would like a Light Theme, Dark High Contrast, and Light High Contrast themes to be added to the current list of preinstalled themes in darktable.

I can write the CSS part of the themes myself and PR them into the source code, but I would also like the themes to be added to the preinstalled themes dropdown.

**Alternatives**

As an alternative to having the themes preinstalled, a section on the https://www.darktable.org/ website (perhaps under Resources, or Install) with copy-pasteable CSS blobs for the themes could be a good alternative to including it inside the application when it is installed. This can also help users who already have the application installed to apply the CSS, or take a given theme and edit it to their preferences.

**Additional context**

Specifically, disabled buttons and text input placeholder text feels too low contrast for what I would prefer to use.

![image](https://github.com/darktable-org/darktable/assets/7771347/a3312f72-8f14-4aa7-ab0d-68182d802f83)

Current list of themes on my install (darktable 4.6.1, installed on Windows 10)
**
![image](https://github.com/darktable-org/darktable/assets/7771347/540ac2a6-3f63-4e0f-8ccb-b0d5c4e3119e)
**

Github's list of available themes:
![image](https://github.com/darktable-org/darktable/assets/7771347/4eac8d3c-644e-425d-9a5f-5223432d222a)

Windows High Contrast Dark

![image](https://github.com/darktable-org/darktable/assets/7771347/3cab83e5-50bc-4909-a60e-2ec8df407cc9)

Windows High Contrast Light 
![image](https://github.com/darktable-org/darktable/assets/7771347/b5c8d8e0-a937-4a00-ac12-0118c6353471)

**Comment by ralfbrown** [comment]
#17245 added high-contrast.

**Comment by victoryforce** [comment]
> At minimum, I believe a light theme (light background, dark text) would be useful to include.

@CryHavoc21  I don't think that will ever happen.

You won't find any serious photo editing software with a light background theme. A light background is definitely not a good idea, in fact it is very harmful to the photo editing process. Bright interfaces can affect how you see the image and what image processing looks optimal. But the result of photo processing will not be viewed in bright lighting, and your processing will look suboptimal under normal viewing conditions.

**Comment by victoryforce** [comment]
Since the high contrast theme part of this feature request has been implemented, I'm closing the issue.
