### ISSUE TITLE
DT 4.8 enlarge canvas for portrait images

### ISSUE THREAD

**Issue by oelki9** [darktable-org/darktable#17128]
### Describe the bug

Everything seems ok for landscape images.

But for portraits increasing top will increase the image to the left.
This happens for all directions (top -> left, bottom -> right, right -> top, left -> bottom)

### Steps to reproduce

Use a portrait image to recreate the behavior. 

### Expected behavior

increase the image in the correct direction 

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu

### Are you using OpenCL GPU in darktable?

Yes

**Comment by MStraeten** [comment]
please check the order of rotation an enlarge canvas module. Which one is done first (lower in the right side panel)?

**Comment by oelki9** [comment]
The order doesn't matter. The outcome is always 90 degrees counter clockwise rotated.

**Comment by ralfbrown** [comment]
I can only reproduce if rotate and perspective or orientation are in the pixelpipe *after* enlarge canvas, which is expected - you add to the canvas and then rotate it, including the added area.  @oelki9, the order in which you make changes to modules (bottom to top in *left* panel) is not the order in which the modules are applied while processing (bottom to top in *right* panel).

**Comment by ralfbrown** [comment]
The default module ordering has enlarge canvas after both of the others, so you must be using a custom order, presumably via (auto-applied) preset.
