### ISSUE TITLE
Simultaneous edit inside Darkroom (Issue Still Persists)

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#17132]
**Is your feature request related to a problem? Please describe.**

- This is in relation with Issue #17010 

**Describe the solution you'd like**

- Although darktable is now on its 4.8th version, applying the edits from 1 photo to other selected photos is still a hit or miss. Sometimes it work sometimes it doesn't. Please refer to ticket # 17010 for the screenshot

**Alternatives**

- Before the iteration of darktable, pressing CTRL / SHFT+ clicking the desired photos then CTRL + SHFT + V (Paste) by pointing the mpuse cursor at any of the chosen photo the same edit applies. When you point the mouse pointer away from these selected photos, the edit doesn't apply.

**Additional context**

- Why can't we add a simple mpuse right-click to apply the changes rather than using a shortcut key? Is it hard to encode? I understand that darktable is different with lightroom but can we make it easier to use?

**Comment by ralfbrown** [comment]
See discussion at #16850

**Comment by blackzerotype** [comment]
> See discussion at #16850

I've seen it. when will it be implemented?

**Comment by ralfbrown** [comment]
When someone submits a pull request.  As covered in that discussion, there is one in progress, but it touches *many* areas of darktable.  Keep in mind that people are doing this work as volunteers, in their spare time.  You might get faster results by hiring someone to make the changes if you have a spare $10,000 or so....

**Comment by blackzerotype** [comment]
> When someone submits a pull request. As covered in that discussion, there is one in progress, but it touches _many_ areas of darktable. Keep in mind that people are doing this work as volunteers, in their spare time. You might get faster results by hiring someone to make the changes if you have a spare $10,000 or so....

- What do you mean by that? I'm just asking. I'm not rushing anyone.

**Comment by ptilopteri** [comment]
perhaps the "tone" implied in your original post

**Comment by blackzerotype** [comment]
> perhaps the "tone" implied in your original post
- I'm just reporting that the issue is still there. Don't get mad at me.

**Comment by wpferguson** [comment]
> when will it be implemented?

comes across as demanding.  Perhaps a "Do you know " at the start would help.

There's another PR that #16850 depends on, #13278 which is being worked right now.  You can monitor the progress by reading the comments on #13278, or just watch for when it gets merged.
