### ISSUE TITLE
rescan library applying new presets

### ISSUE THREAD

**Issue by sss123next** [darktable-org/darktable#17131]
**Is your feature request related to a problem? Please describe.**
i am not able to find quick and convenient method to apply changes in presets to whole collection

**Describe the solution you'd like**
it can be  button to rescan collection somewhere in gui, or maybe cli command to rescan collection and apply new presets, maybe even some new command like `darktable-generate-cache`

**Alternatives**

**Additional context**

**Comment by ptilopteri** [comment]
* Alexandr ***@***.***> [07-12-24 20:10]:
> **Is your feature request related to a problem? Please describe.**
> i am not able to find quick and convenient method to apply changes in presets to whole collection

maybe looking into the fine manual??? 

open dt to lighttable mode
select image with settings you wish to apply to "whole collection"
in the right side panel, open "history stack"
select settings you wish to apply to "whole collection"
set mode to append

select images "whole collection"
<ctrl><v> to past to selected images.



-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by ralfbrown** [comment]
Or, if you want to update auto-applied presets and don't care whether you lose existing edits, you can select all images and then use "discard history" in the history stack module.

**Comment by sss123next** [comment]
thank you for help.
