### ISSUE TITLE
Segmentation fault when clicking on filter options in lighttable

### ISSUE THREAD

**Issue by hannonq** [darktable-org/darktable#17139]
### Describe the bug

After recently upgrading to darktable 4.8, I experience crashes in different places in lighttable. 

### Steps to reproduce

1. Open darktable
2. Click on Filter Preferences -> New Filter
3. Darktable crashes with segmentation fault
4. Same happens when clicking on Sort by and trying to change from the default "filename"

### Expected behavior

darktable should offer the expected options from the menus and not crash

### Logfile | Screenshot | Screencast

Crash happens when clicking on the "New filter" arrow here:
![Screenshot from 2024-07-14 15-48-13](https://github.com/user-attachments/assets/ee5b4e5f-a01a-47ba-bb19-c4aa6f76e9e7)

Log file:
[darktable-logs.txt](https://github.com/user-attachments/files/16227671/darktable-logs.txt)

### Where did you obtain darktable from?

I dont know

### darktable version

darktable 4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

EndevourOS

### Describe your system?

System:
Intel i7
32GB RAM
NVIDIA GeForce GTX 1650 Ti
Gnome Shell on Wayland

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1650 Ti 4GB, NVIDIA Driver Version 555.58.02

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Darktable was installed using `yay`, but I chose "I don't know" because I'm not sure which option fits best from the dropdown menu. Issue didn't happen in previous version of darktable, but started happening after updating darktable via `yay`

Issue still happens if I run darktable with opencl disabled e.g. `darktable --disable-opencl`

Issue persists after removing my old `library.db` and (later) `~/.conf/darktable` and adding a small collection of new photos.

> Is the issue still present using an empty/new config-dir  

Yes.

I saw [this bug report](https://github.com/darktable-org/darktable/issues/17124), but it looks like it's a different issue.

**Comment by ralfbrown** [comment]
Unfortunately, it seems your executable has been stripped of debug info, so the only thing that can be determined from the log is that the crash happened somewhere deep inside the GUI toolkit darktable uses....

Wayland has been problematic in the past, but I'll need to leave it to others to say whether it's still an issue with 4.8.

**Comment by hannonq** [comment]
> Unfortunately, it seems your executable has been stripped of debug info

Is there a flag I can use to run darktable with better debug logs?

**Comment by ralfbrown** [comment]
The best info for tracking down a crash comes from the backtrace - what you have in the log you uploaded.  But only if it also includes line-number information, which your log doesn't, and there's no way to enable it without recompiling.

Adding commandline flags like "-d common" can help narrow down the problem by telling us that darktable got at least as far as point X, but doesn't pinpoint it like a full backtrace does.

**Comment by jenshannoschwalm** [comment]
> Adding commandline flags like "-d common" can help narrow down the problem by telling us that darktable got at least as far as point X, but doesn't pinpoint it like a full backtrace does.

Please note there is a bug in 4.8 that will crash dt when -d imageio is enabled.

**Comment by victoryforce** [comment]
@hannonq I can't reproduce the crash on Windows and Ubuntu.

I suggest you [download AppImage from the official website](https://www.darktable.org/install/), make it executable and run . If it works without problems (which I hope it will), then it's a problem with the darktable build in your distro. If AppImage also crashes, I can only suspect another problem with Wayland.

**Comment by hannonq** [comment]
I ended up (hopefully temporarily) switching to Windows because I also have other Wayland issues (for example, I can't add tags when running on Wayland like mentioned on [this issue](https://github.com/darktable-org/darktable/issues/14729)).

I need to find a working solution for DE with (fractional) scaling first :( 

I'll close this issue for now. Thanks for your input, everyone.
