### ISSUE TITLE
Reliable crash when pasting settings to multiple images, while multiple images are resetting

### ISSUE THREAD

**Issue by RUDANTU** [darktable-org/darktable#17146]
### Describe the bug

darktable crashes if you quickly reset and paste multiple images in the thumbstrip while in darktoom mode

### Steps to reproduce

1. In darkroom, have multiple images selected in the bottom thumbstrip. Example 15 images with edits are selected.

3. **reset history** of these selected images  (I do this with a shortcut)

_while working, thumbnails have (working) appear over them — sometimes this takes a second._

5. quickly try paste settings onto these same images (I do this with a shortcut)

6. darktable crashes. 

### Expected behavior

darktable should wait until all images are reset before trying to paste new settings onto them

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14.5 (23F79

### Describe your system?

Mac Studio M1 Max 32GB RAM

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Mac Studio M1 Max 32GB RAM

**Comment by victoryforce** [comment]
> We may have this fixed in 4.8.1 as a similar issue with undo/redo as been fixed (proper concurrency support on history).

@RUDANTU Can I ask you to check if 4.8.1 fixed the problem?

**Comment by ralfbrown** [comment]
No response from OP in four months.
