### ISSUE TITLE
sqlite3 error in master release-4.9.0-69-gf90646ac81

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#17154]
### Describe the bug

sqlite3 error: /data1/software/build/darktable/src/common/tags.c:1163, 
function dt_tag_get_suggestions(), query "INSERT INTO memory.taglist (id, count, count2)  
SELECT S.tagid, COUNT(imgid) AS count,    CASE WHEN count2 IS NULL THEN 0 ELSE count2 END AS count2  
FROM main.tagged_images AS S  LEFT JOIN (    SELECT tagid, COUNT(imgid) AS count2    
FROM main.tagged_images    WHERE imgid IN main.selected_images    
GROUP BY tagid) AS at  ON at.tagid = S.tagid  WHERE S.tagid NOT IN memory.darktable_tags  
GROUP BY S.tagid": sub-select returns 2 columns - expected 1

### Steps to reproduce

open dt and select image

### Where did you obtain darktable from?

self compiled

### darktable version

0.8.99-66-gf9853cf4

### What OS are you using?

Linux

### What is the version of your OS?

openSUSE Tumbleweed 20240714

### Are you using OpenCL GPU in darktable?

None

**Comment by pehar1** [comment]
Duplicate of #17137

**Comment by ptilopteri** [comment]
closed as dup of #17137
