### ISSUE TITLE
Release-4.8.0 : Segmentation fault : filter image in darkroom and press space to move to next

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#17153]
### Describe the bug

I get segmentation fault using darktable 4.8.0 built from source on Debian stable 12.6 when I select a picture, then go to darkroom,filter an image to get zero pictures as filter result and press next (space).

### Steps to reproduce

Build from source:

```
git clone https://github.com/darktable-org/darktable.git
cd darktable
git submodule update --init
git checkout release-4.8.0
git submodule update --recursive
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/magnus/test/darktable-test/install -DCMAKE_BUILD_TYPE=Release ..
make -j32
make install
```
Then execute from a clean new install of darkroom:
```
1. ./darktable  --configdir /home/magnus/test/darktable-test/config --cachedir /home/magnus/test/darktable-test/cache
2. Import some pictures.
3. Select a picture from lighttable and click to go to darkroom.
4. In darkroom select `filter image by color label` and tick, for instance, `red` or select `range rating (star)`. The precondition is that NO files have the selected color label or star rating.
5. The filmstrip, after step 4, in darkroom will not display any pictures, since all pictures are filtered out.
6. In darkroom press `space`, to move to next.
7. Darktable crashes with a segmentation fault. The crash logs are attached in logfile below.
```

### Expected behavior

Darktable should not crash.

### Logfile | Screenshot | Screencast

The console output can be found here: [crash.txt](https://github.com/user-attachments/files/16247995/crash.txt)

The darktable backtrace file is here: [darktable_bt_Z594Q2.txt](https://github.com/user-attachments/files/16248008/darktable_bt_Z594Q2.txt)

### Commit

I have tested release-4.8.0, git master tip at 4.9.0 and late 4.7.0 commits. All have same issue.

### Where did you obtain darktable from?

cloned from https://github.com/darktable-org/darktable.git

### darktable version

I have tested release-4.8.0, current git master 4.9.0 and late 4.7.0 commits, with same issue.

### What OS are you using?

Linux

### What is the version of your OS?

Debian stable bookworm 12.6. 

### Describe your system?

- OS : Linux debian 6.1.0-22-amd64 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux
- Linux - Distro : Debian 12.6 Stable Bookworm
- Memory : 64 GB
- Graphics card : NVIDIA Corporation TU104GL [Quadro RTX 4000]
- Graphics driver : NVIDIA 535.183.01 from Debian non-free repo
- OpenCL installed : Yes,   OpenCL 3.0 CUDA 12.2.148
- OpenCL activated : Yes (but --disable-opencl does not help, same issue)
- Xorg : X11
- Desktop : Gnome 43.9
- GTK:  3.24.38-2~deb12u1, 4.8.3+ds-2+deb12u1, 2.24.33-2
- gcc : (Debian 12.2.0-14) 12.2.0
- cflags : 
- CMAKE_BUILD_TYPE : Release
- Intel® Core™ i9-14900K × 32
- motherboard: ASUS PRIME Z790-A WIFI

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Corporation TU104GL [Quadro RTX 4000], NVIDIA 535.183.01 from Debian non-free repo

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I have not bisected, but current tip of git master, release-4.8.0, or some late commits of 4.7.0 does not matter. I get the same segfault.

I have tested on two different PCs with separate installations of Linux Debian 12.6 and I get the same segmentation fault => I think I have working Debian stable systems without any misconfiguration.

**Can you reproduce with another darktable version(s)?  **yes, I have tested release-4.8.0, current git master 4.9.0 and late 4.7.0 commits. All have with same issue.**
Can you reproduce with a RAW or Jpeg or both? **I can select a tiff file, for example, with same segfault as when I select a raw file (Canon CR2).**
Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
If the issue is with the output image, attach an XMP file if (you'll have to change the extension to .txt) **The selected picture file raw or tiff does not matter.**
Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
Do you use lua scripts? **no**

Open CL: **Open CL on or off does not matter.**

**Comment by ralfbrown** [comment]
Based on a quick look at the backtrace, it appears that the cause of the crash is passing an image id of zero to `dt_dev_reload_image`, which eventually makes `dt_mipmap_cache_get` segfault.  Not sure at which level it would be best/easiest to add a check for a valid image id.

**Comment by KarlMagnusLarsson** [comment]
Works for me. Thank you.
