### ISSUE TITLE
Color equalizer - hue curve not working

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#17165]
### Describe the bug

The hue curve setting in the Color equalizer module does nothing both in the graph and the image itself.
 
![Capture 2024-07-19 16,32,08](https://github.com/user-attachments/assets/d39f6396-0a18-4296-86ab-1c6f83fc2505)

![Capture 2024-07-19 16,32,27](https://github.com/user-attachments/assets/942830ec-340a-4312-a567-4315dce82d90)

### Steps to reproduce

1. Open the Color equalizer module
2. Change the hue curve setting
3. No change of the curve

### Expected behavior

self explanatory

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel Iris Xe

**Comment by jenshannoschwalm** [comment]
It's designed to modify only the curve in the hue tab. See pr

**Comment by Pizzacutter-at-tty3** [comment]
Oh, I guess that makes sense..  😅 I thought it modifies the curve for each tab
