### ISSUE TITLE
Cannot add new tags

### ISSUE THREAD

**Issue by joaobrisson** [darktable-org/darktable#17187]
### Describe the bug

Cannot create new tags
Can only attach/detach existing tags that were created with version 4.6.1

### Steps to reproduce

1. Fill the tagging dialog box with something
2. Press New
3. the tag list displays all tags starting with the first tag in the list
4. No new tag is attached to the selected image

### Expected behavior

New tag should show on the tag list and shown on the selected image information

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14.5 Sonoma

### Describe your system?

MacBook Air M3 16 GB RAM 512 GB SSD

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by zisoft** [comment]
Cannot reproduce on current master.
Since you are using a Mac I have a suspicion:
Can you please check the permissions on the following folders and see if your user has write permissions:

- `~/.config`
- `~/.config/darktable`

And check if your database files are writeable as well:

- `~/.config/darktable/data.db`
- `~/.config/darktable/library.db`

**Comment by joaobrisson** [comment]
ThanksWill check when back home and let you knowWill also check for the pop up dialogue, was using Darktable in maximized windowEnviado do meu iPhoneNo dia 22/07/2024, às 12:12, Mario Zimmermann ***@***.***> escreveu:﻿
Cannot reproduce on current master.
Since you are using a Mac I have a suspicion:
Can you please check the permissions on the following folders and see if your user has write permissions:

~/.config
~/.config/darktable

And check if your database files are writeable as well:

~/.config/darktable/data.db
~/.config/darktable/library.db

**Comment by joaobrisson** [comment]
Right on spot, thank you

data.db was only readable, chmod -u+rw data.db did the job

data.db was copied to my new Mac from a Time Machine snapshot of my old Mac that was running 4.6.1
when I installed darktable 4.8 on the new Mac (I did not install 4.6.1) it refused to start normally claiming that the library was corrupt  so I had to create a new library and import all photos
somehow data.db permissions were set to read only along all this way

issue closed from my side , thanks for helping
