### ISSUE TITLE
Add skin tone line to vectorscope

### ISSUE THREAD

**Issue by michmill1970** [darktable-org/darktable#17212]
Add a skin-tone line to the vectorscope in the darkroom view.

All skintones fall along a straight line in a vectorscope view.  The paler the complexion, the closer to the middle of the scope, and darker complexions will have an elongated distribution, but all complexions will fall along a very similar line.  Some may be slightly above the line, and some complexions may fall a very small amount below.

This line will help considerably when color grading portraits, especially when dealing with odd lighting.

I use this in Davinci Resolve, and it's an incredibly useful feature.

**Comment by ralfbrown** [comment]
Previously discussed in #11467, along with alternatives.  There is in fact **not** a common tone among all ethnicities.

**Comment by MStraeten** [comment]
btw: darktable 4.4 added color harmony indicators to the vectorscope - so it’s quite easy to show something like a skin tone value line using a monochromatic indicator, rotating it to a proper value and reducing the width according to user’s preferences
