### ISSUE TITLE
Cannot install DarkTable on M1 Mac.

### ISSUE THREAD

**Issue by ReshV** [darktable-org/darktable#17222]
### Describe the bug

Cannot install DarkTable on M1 Mac.

### Steps to reproduce

1. Installed the DMG.

2. followed the fix instructions from the page "Fixing issues with macOS security settings"

3. App pretends to load but in reality just sits on the dock not responding.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable-4.8.1-arm64-macOS-13.5.dmg

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14.5 Sonoma

### Describe your system?

MacBook Pro M1

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

N/A

**Comment by zisoft** [comment]
Can you please try with [darktable-4.8.1-arm64.dmg](https://github.com/darktable-org/darktable/releases/download/release-4.8.1/darktable-4.8.1-arm64.dmg) which is for macOS 14 and above.

**Comment by ReshV** [comment]
Same issue.

It says MacOS can't verify the source

I ran the following command and it says permission denied-
xattr -dr com.apple.quarantine /Applications/darktable.app

**Comment by MStraeten** [comment]
Please run darktable via terminal:
`/Applications/darktable.app/Contents/MacOS/darktable  -d common` to see if there are messages indicating where it fails

**Comment by ReshV** [comment]
Hi, 
Tried it,

Pasting the screenshot below. trying to interprit it.

<img width="671" alt="Screenshot 2024-07-30 at 12 13 33 AM" src="https://github.com/user-attachments/assets/5f0d3bb0-ef4d-4e98-9a11-7a75eb5eba83">

**Comment by zisoft** [comment]
Check the permissions of the `~/.config` folder, it needs to be writeable for your user.

```
sudo chown <username> ~./config
sudo chmod -R 755 ~./config
```

Then try again to run darktable.

**Comment by ReshV** [comment]
Hi,

Tried the following commands and running DarkTable. It's still the same issue. It looks like it just doesn't want to run at this point.

sudo chown <username> ~/.config
sudo chmod -R 755 ~/.config

**Comment by ReshV** [comment]
This worked.

Thanks a lot!!!
