### ISSUE TITLE
Darktable freezes after import

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#17238]
### Describe the bug

Darktable freezes after importation of photos. Although it says import complete when I went to darkroom to cull the images only a few were there and not all the photos imported. So I don't know what to do. Please advise. Thank you
![darktable_error_import](https://github.com/user-attachments/assets/da134644-85a1-4246-8be6-c903a6eb9351)

### Steps to reproduce

go to add / copy / import

### Expected behavior

darktable should be running smoothly when importing photos 

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8

### What OS are you using?

Windows

### What is the version of your OS?

Edition	Windows 10 Pro Version	22H2 Installed on	‎11/‎19/‎2020 OS build	19045.4717 Experience	Windows Feature Experience Pack 1000.19060.1000.0

### Describe your system?

Device name	DESKTOP-RNR2OEA
Processor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
Installed RAM	8.00 GB
Device ID	C0838FCF-50BF-485F-9EA9-E0AA8F8516AE
Product ID	00331-10000-00001-AA218
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎19/‎2020
OS build	19045.4717
Experience	Windows Feature Experience Pack 1000.19060.1000.0

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

1650 super

**Comment by da-phil** [comment]
Your hardware specs, especially the available RAM look suspicious. Can you pls try to monitor the RAM usage (e.g. in the task manager) while importing images? I suspect that dt uses up all available RAM and then runs into an out-of-mem exception.
What are your settings for "darktable ressources"? I would suggest to use "small" in your case.

**Comment by luzpaz** [comment]
@blackzerotype :point_up_2:

**Comment by ralfbrown** [comment]
Closing due to no response from OP in over three months.
