### ISSUE TITLE
Feature Request: Ability to Hide Starred Repositories

### ISSUE THREAD

**Issue by mirr-x** [darktable-org/darktable#17252]
**Is your feature request related to a problem? Please describe.**

Currently, all starred repositories on GitHub are public and visible to anyone who views a user's profile. This can be an issue for users who wish to keep their interests or certain projects confidential. The lack of privacy for starred repositories may deter users from starring repositories they genuinely find useful or interesting due to privacy concerns.

**Describe the solution you'd like**

I would like the ability to make starred repositories private. This could be implemented as an option in the user's settings, allowing users to choose whether their starred repositories are public or private. Alternatively, users could have the option to make individual starred repositories private directly from the repository page.

**Alternatives**

As a workaround, users can:

Unstar repositories they want to keep private.
Use a secondary GitHub account to star repositories privately.
Bookmark repositories in their web browser instead of starring them.
However, these alternatives are not as convenient or integrated as having a direct option to make starred repositories private within GitHub.

**Additional context**

Making starred repositories private would enhance user privacy and encourage more engagement with the starring feature. Users would feel more comfortable expressing their interests and supporting projects without concern for their public profile visibility.

**Comment by zisoft** [comment]
Wrongly assigned?
I think this has nothing to do with darktable.

**Comment by victoryforce** [comment]
> Wrongly assigned?

Undoubtedly so. Closing.
