### ISSUE TITLE
Metadata Editor module in Darkroom (next to the Tagging module)

### ISSUE THREAD

**Issue by arigit** [darktable-org/darktable#17261]
Currently, in darkroom mode, on the left-side modules, we have the Tagging module where we can create/assign tags as we browse/edit each pic. In my workflow, I do a first pass/reject type scan of new photo sets directly on the Darkroom. Having tagging is great but we are currently missing all other metadata. I am mainly seeking to have Title and Description.

**Describe the solution you'd like**
Adding the Metadata editor module in the left pane next to the Tagging module in the Darkroom

**Alternatives**
N/A

**Additional context**
N/A

**Comment by ralfbrown** [comment]
Should be a one-line change in the code - mark the module as appearing in the darkroom as well as lighttable view.  I'd also be in favor of having metadata editor in darkroom view.

**Comment by ralfbrown** [comment]
A much more general solution is now in master following the merge of #17425 and #17467 (plus several other PRs in between).
