### ISSUE TITLE
DT 4.8.1 seg fault on loading a folder of images

### ISSUE THREAD

**Issue by FrancescoScaglioni** [darktable-org/darktable#17273]
### Describe the bug

I have a folder that contains 136 canon cr2 files from 2013 along with xmp files that were created by DT earlier this month.  On either "Open with darktable" or "Import into darktable" DT starts the process then crashes. leaving a segfault file in /tmp.

### Steps to reproduce

Right click or keyboard to access folder menu, select "Open with other application" then DT or open DT and select import folder (All images already marked as in the database as if I select "Only show new images" they are all unselected.  DT then crashes.

### Expected behavior

Open that folder as it does with (Most) of the other folders of images that I have. 

### Logfile | Screenshot | Screencast

https://pastebin.com/d39yk2zJ (The segfault file from / tmp)

### Where did you obtain darktable from?

ppa ubuntuhandbook1/darktable/ubuntu/jammy/main

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

Ubuntu jammy 22.04 x86_64
XPS 8910 (1.0.9), Intel(R) Core(TM) i7-6700 (8) @ 4.00 GHz, NVIDIA GeForce GTX 1070 [Discrete], Memory: 4.67 GiB / 15.51 GiB.  I have been running DT and linux on this machine since purchase back in 2015 or 2016 (And many machines prior)
Linux 6.5.0-41-generic

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070 [Discrete], NVIDIA driver

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

No LUA scripts.  Issues applies to several random folders of images and not just the one mentioned above.

**Comment by ptilopteri** [comment]
* FrancescoScaglioni ***@***.***> [08-06-24 04:14]:
> ### Describe the bug
> 
> I have a folder that contains 136 canon cr2 files from 2013 along with xmp files that were created by DT earlier this month.  On either "Open with darktable" or "Import into darktable" DT starts the process then crashes. leaving a segfault file in /tmp.
> 
> ### Steps to reproduce
> 
> Right click or keyboard to access folder menu, select "Open with other application" then DT or open DT and select import folder (All images already marked as in the database as if I select "Only show new images" they are all unselected.  DT then crashes.
> 

Just had a similar experience, found a single image which apparently had a
corrupted xmp file.

I discovered by moving the current xmp files to another location and the
directory opened successfully.  So I restored subject xmp files a few at a
time to locate the errant one.

You may have same problem.

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by FrancescoScaglioni** [comment]
> * FrancescoScaglioni ***@***.***> [08-06-24 04:14]:
> ### Describe the bug I have a folder that contains 136 canon cr2 files from 2013 along with xmp files that were created by DT earlier this month. On either "Open with darktable" or "Import into darktable" DT starts the process then crashes. leaving a segfault file in /tmp. ### Steps to reproduce Right click or keyboard to access folder menu, select "Open with other application" then DT or open DT and select import folder (All images already marked as in the database as if I select "Only show new images" they are all unselected. DT then crashes.
> Just had a similar experience, found a single image which apparently had a corrupted xmp file. I discovered by moving the current xmp files to another location and the directory opened successfully. So I restored subject xmp files a few at a time to locate the errant one. You may have same problem.
> […](#)
> -- (paka)Patrick Shanahan Plainfield, Indiana, USA @ptilopteri facebook/ptilopteri Photos: http://wahoo.no-ip.org/piwigo paka @ IRCnet oftc

I had already tried deleting all the xmp files but DT still segfaulted. I guess I shall have to open each image one at a time :(

**Comment by FrancescoScaglioni** [comment]
> * FrancescoScaglioni ***@***.***> [08-06-24 04:14]:
> ### Describe the bug I have a folder that contains 136 canon cr2 files from 2013 along with xmp files that were created by DT earlier this month. On either "Open with darktable" or "Import into darktable" DT starts the process then crashes. leaving a segfault file in /tmp. ### Steps to reproduce Right click or keyboard to access folder menu, select "Open with other application" then DT or open DT and select import folder (All images already marked as in the database as if I select "Only show new images" they are all unselected. DT then crashes.
> Just had a similar experience, found a single image which apparently had a corrupted xmp file. I discovered by moving the current xmp files to another location and the directory opened successfully. So I restored subject xmp files a few at a time to locate the errant one. You may have same problem.
> […](#)
> -- (paka)Patrick Shanahan Plainfield, Indiana, USA @ptilopteri facebook/ptilopteri Photos: http://wahoo.no-ip.org/piwigo paka @ IRCnet oftc

I once again deleted all the xmp files.  Checked to confirm that DT was set to only create xmp files after edit.  Asked DT to open the folder.  It again crashed but on checking the folder xmp files had been recreated for all images.

**Comment by wpferguson** [comment]
What happens if you start darktable from the menu rather than a right click?

**Comment by FrancescoScaglioni** [comment]
Strange resolution.  I deleted all the xmp files, removed images in batches and tried the folder again ( and repeat).  All xmp files were recreated (Presumably from the DT database).  Repeated the remove images and xmp files process in iterations.  Eventually narrowed it down to a single image remaining in a temporary folder. ie all others in the original folder which DT opened without issue.  Then opened the tmp folder containing only the presumed rogue image and it opened!  Copied the rogue image back to the original folder and the folder opened without issue.  I have absolutely no idea what was going on.  Thanks you all for your help and suggestions.

**Comment by ptilopteri** [comment]
* FrancescoScaglioni ***@***.***> [08-06-24 12:21]:
> Strange resolution.  I deleted all the xmp files, removed images in batches and tried the folder again ( and repeat).  All xmp files were recreated (Presumably from the DT database).  Repeated the remove images and xmp files process in iterations.  Eventually narrowed it down to a single image remaining in a temporary folder. ie all others in the original folder which DT opened without issue.  Then opened the tmp folder containing only the presumed rogue image and it opened!  Copied the rogue image back to the original folder and the folder opened without issue.  I have absolutely no idea what was going on.  Thanks you all for your help and suggestions.

then you might close the #ISSUE

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by jenshannoschwalm** [comment]
> Then opened the tmp folder containing only the presumed rogue image and it opened! Copied the rogue image back to the original folder and the folder opened without issue. I have absolutely no idea what was going on.

Do you still have the xmp file for that "bad-boy" ?

**Comment by FrancescoScaglioni** [comment]
> > Then opened the tmp folder containing only the presumed rogue image and it opened! Copied the rogue image back to the original folder and the folder opened without issue. I have absolutely no idea what was going on.
> 
> Do you still have the xmp file for that "bad-boy" ?

Sadly no I do not.  Every time I added images back into the original folder then opened that folder with DT the xmps were recreated.  The culprit image has not been edited in DT since its guilt was established an thus no current xmp.

**Comment by FrancescoScaglioni** [comment]
As this now seems to be solved, albeit without me really understanding why, I shall close this.  Many thanks to all who helped me.
