### ISSUE TITLE
Darktable 4.8.1 Not Working

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#17271]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

After installation, darktable closes automatically after lauch

**Alternatives**

The Bug Report link seems not working so I'll post the bug report here

**Additional context**

**Comment by zisoft** [comment]
Please fill in the issue template with the required information.

**Comment by blackzerotype** [comment]
> Please fill in the issue template with the required information.

Hi. Where can I find the issue template?

**Comment by ralfbrown** [comment]
Click on the green "New Issue" button or go to `https://github.com/darktable-org/darktable/issues/new/choose`, then click the green "Get Started" button next to Bug Report.
