### ISSUE TITLE
Darktable not wokring after installtion

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#17272]
### Describe the bug

After installation, darktable closes automatically after launch

### Steps to reproduce

- Run as administrator
next > next > finish

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Edition	Windows 10 Pro Version	22H2 Installed on	‎11/‎19/‎2020 OS build	19045.4717 Experience	Windows Feature Experience Pack 1000.19060.1000.0

### Describe your system?

Device name	DESKTOP-RNR2OEA
Processor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
Installed RAM	16.0 GB
Device ID	C0838FCF-50BF-485F-9EA9-E0AA8F8516AE
Product ID	00331-10000-00001-AA218
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎19/‎2020
OS build	19045.4717
Experience	Windows Feature Experience Pack 1000.19060.1000.0

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

gigabyte 1650 super

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

After installation, darktable closes automatically after launch

**Comment by MStraeten** [comment]
have a look at https://www.darktable.org/about/faq/#faq-windows
There's no common startup  issue with darktable 4.8.1 known.
So more specific information (at least log files) are needed

**Comment by jenshannoschwalm** [comment]
Is there any pen for the display connected ?

**Comment by blackzerotype** [comment]
> have a look at https://www.darktable.org/about/faq/#faq-windows There's no common startup issue with darktable 4.8.1 known. So more specific information (at least log files) are needed

Hi. How can I get the log file if darktable closes immediately after launching it? Is there another place where I can find the log file that you require? Please advise.

**Comment by victoryforce** [comment]
>> have a look at https://www.darktable.org/about/faq/#faq-windows There's no common startup issue with darktable 4.8.1 known. So more specific information (at least log files) are needed

> How can I get the log file if darktable closes immediately after launching it?

In the same way as when darktable doesn't crash immediately. The location of the log is indicated on the page https://www.darktable.org/about/faq/#faq-windows

> Is there another place where I can find the log file that you require? Please advise.

It was already advised above. Please read https://www.darktable.org/about/faq/#faq-windows

**Comment by blackzerotype** [comment]
> > > have a look at https://www.darktable.org/about/faq/#faq-windows There's no common startup issue with darktable 4.8.1 known. So more specific information (at least log files) are needed
> 
> > How can I get the log file if darktable closes immediately after launching it?
> 
> In the same way as when darktable doesn't crash immediately. The location of the log is indicated on the page https://www.darktable.org/about/faq/#faq-windows
> 
> > Is there another place where I can find the log file that you require? Please advise.
> 
> It was already advised above. Please read https://www.darktable.org/about/faq/#faq-windows

Itried redint he article and when I checked drive c:/ it only says:"Admin" as the username and no AppData folder too. Please see screenshot below

![darktable_error_import2](https://github.com/user-attachments/assets/69e32f6a-d192-4f2d-a38b-4f5fce78b174)
![darktable_error_import3](https://github.com/user-attachments/assets/26a5a5d4-3cee-4af8-b9da-888d6401ddb8)

**Comment by gi-man** [comment]
@blackzerotype If you are going to use the Windows Explorer interface, you will need to change your settings to Show Hidden Files and Folders. Also, your windows username should be a folder in the Users folder (not Admin). 

Please keep in mind that most of us dont use Windows, so we are trying to help in an area we dont have a lot of exposure.

**Comment by blackzerotype** [comment]
> @blackzerotype If you are going to use the Windows Explorer interface, you will need to change your settings to Show Hidden Files and Folders. Also, your windows username should be a folder in the Users folder (not Admin).
> 
> Please keep in mind that most of us dont use Windows, so we are trying to help in an area we dont have a lot of exposure.

I got it. It is buried inside of Windows c:: I hope there will also be support for WIndows users in the future. :)

**Comment by gi-man** [comment]
We support darktable for Windows users. Your questions are more around support on how to use Windows as an operating system (eg. how to show hidden files in windows explorer).

**Comment by blackzerotype** [comment]
> We support darktable for Windows users. Your questions are more around support on how to use Windows as an operating system (eg. how to show hidden files in windows explorer).

Actually the executable file was not hidden. I just tried re-installing it from within c:/ and worked. Previously I was trying to reinstall darktable from the downloads folder of the desktop and for some reason was not working. So I tried looking for the executable file from within.

**Comment by jenshannoschwalm** [comment]
> I just tried re-installing it from within c:/ and worked.

Do i understand this correctly - your dt now works fine?

**Comment by blackzerotype** [comment]
> > I just tried re-installing it from within c:/ and worked.
> 
> Do i understand this correctly - your dt now works fine?

Yes. just tried relaunching and is now working. :)

**Comment by jenshannoschwalm** [comment]
So what's left to do, you should please describe what you did wrong  and maybe correct the title of this issue **before** closing.

**Comment by luzpaz** [comment]
bump

**Comment by MStraeten** [comment]
> bump

What do you want to achieve with this comment? There’s no known general issue with running darktable

**Comment by luzpaz** [comment]
Can this be closed then ?

**Comment by victoryforce** [comment]
Yeah, no point in keeping it open.

Since, as you know, reinstalling the program does not solve any problems, I have only one explanation why it seemed to help the bug reporter. It is possible that the versions of the originally installed and reinstalled darktable differed (there is a very vaguely worded comment that may indicate this).

So, I'm closing this issue.
