### ISSUE TITLE
Tone equalizer hue/saturation

### ISSUE THREAD

**Issue by HanaMcHanaface** [darktable-org/darktable#17317]
Hello!

Hope this hasn't been mentioned before/is already available but I haven't been able to find it.

I have a feature request that I think makes a lot of sense. Basically in color equalizer it's possible to change hue/saturation/brightness based on the original hue of the pixel. That's great. Now I'm thinking why can't we also do that for different tones in tone equalizer? I think that would be very useful.

So to clarify that would mean in the tone equalizer there would also be hue and saturation tabs, which could be used to change hue/saturation (and brightness which is already available) based on the original brightness of the pixel.

For example then we could adjust foliage shadows to get a more blue tone, or make highlights warmer like they came from a warm sun and so on.

Of course there is some of that functionality in `4 ways` in `color balance rgb` but that is a very crude tool compared to what I'm suggesting.

**Comment by MStraeten** [comment]
in tone equalizer you're changing tonal values based on a calculated greyscale mask, not on the original image pixel information. 
so both tools operate quite different - hard to integrate those different approaches without driving complexity of the ui and the required math ...

**Comment by HanaMcHanaface** [comment]
@MStraeten well the UI would just look pretty much like the `color equalizer` but also with the masking tab. When it comes to the math I'm not quite sure what you are saying the difference is. But at some point you do have to change pixel information in order to get the module to do anything and so at that point it would affect hue/saturation/brightness instead of only brightness.

**Comment by MStraeten** [comment]
maybe have a look at https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/tone-equalizer/
