### ISSUE TITLE
Cannot open 4.8.1 on Ventura 13.3

### ISSUE THREAD

**Issue by jcampbell05** [darktable-org/darktable#17323]
### Describe the bug

Upon installing darktable and following instructions to remove quarantine flag - It won't open, instead we get a "You cannot use this application with this version of mac OS"

The link to darktable Ventura 13.5 is broken on the website

### Steps to reproduce

1. Install darktable
2. Try to open it

### Expected behavior

darktable should be able to open it

### Logfile | Screenshot | Screencast

<img width="372" alt="Screenshot 2024-08-14 at 09 58 53" src="https://github.com/user-attachments/assets/ce4016a8-ac24-4824-ac21-1d09ec821844">

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.3

### Describe your system?

Macbook M1 Pro

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment]
You have downloaded the x86_64 package, which is for the Intel architecture. You need to use the arm64 package on an M1 Mac.

**Comment by bphun95** [comment]
> The link to darktable Ventura 13.5 is broken on the website

Waiting for this as well 👍

**Comment by zisoft** [comment]
[darktable 4.8.1 releases](https://github.com/darktable-org/darktable/releases/tag/release-4.8.1)

**Comment by gi-man** [comment]
Martin provides an unofficial builds for older macos. Maybe give those a try.

https://discuss.pixls.us/t/darktable-4-8-1-for-older-macos-versions-10-14-11-0/44768
