### ISSUE TITLE
Supporto per Lumix S5 II

### ISSUE THREAD

**Issue by Genialsky** [darktable-org/darktable#17325]
Salve, è possibile aggiornare il sistema per poter gestire i file raw (Rw2) della Lumix S5 II? Grazie

**Comment by victoryforce** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/13511

Please search before opening new issues.

P.S. You can track the progress of adding support at https://github.com/darktable-org/rawspeed/issues/367
