### ISSUE TITLE
How do I open Sony A7IV ARW files? + other bad first user experiences

### ISSUE THREAD

**Issue by tgrushka** [darktable-org/darktable#17320]
### Describe the bug

I'm a software engineer and trying to use DarkTable for the first time to curate, select, and hopefully color correct a bunch of photos I just shot at a concert. I find it extremely frustrating that there is no real help (Google search yielded this question being asked multiple times, and the responses are less than helpful) on how to fix this problem:

## How do I use Sony A7IV ARW files in this software?

Issue #14766 was closed, but I argue that it is not resolved, and the suggestions in that issue are not helpful. Why was it closed?

Running DarkTable 4.8.1 on macOS Sonoma 14.5, previews of Sony ARW files from my A7IV work (thumbnails, I guess?):

4.8.1

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/14c60913-6fa7-4d2e-af8a-80987c9267e7">

<img width="822" alt="image" src="https://github.com/user-attachments/assets/80c4ad65-d31a-4a1c-9b48-bb179c02a64c">

I get the above totally unhelpful message:
```
'Sony ILCE-7M4' color matrix not found for image
```

The manual also is not helpful. Finally found this page by Googling around until I eventually found a link to the old docs, then found the latest page:

https://docs.darktable.org/usermanual/4.6/en/module-reference/processing-modules/input-color-profile/

Under "processing modules," really? Is a new user really going to know to look in there to find info about this error message? Why does the error message disappear after only a few seconds? Why is there not a link in the error message to the relevant documentation?

To add insult to injury,  #14766 references the **release notes** which state that Sony Uncompressed RAW is not supported 🤦. (Why is this not in the documentation??) Any explanation for this? Does Sony just not make this matrix available? If so, I know one of the chief product guys at Sony and I'm going to write him about it.

So basically ALL of the photos I've shot in Sony Uncompressed ARW are totally useless in this software. Who knows why?!?

Then, I converted them to DNG. But, opening the DNG file, when DarkTable doesn't crash (yes, it crashes about every other time I double-click on a thumbnail to open it in light table -- my MacBook Pro M1 Max with 64 GB of RAM is no slouch), it appears DarkTable cannot even read the "as shot" (whatever it's called) color profile from the DNG (maybe it's lost in the translation?) and I get this "washed out" (obviously the raw profile):

<img width="1606" alt="image" src="https://github.com/user-attachments/assets/c954cab0-123b-48e9-aefa-b5394f32aebf">

I'm pretty good at using my screen reader and magnifier to find information. I'm a techie programmer and have worked with nearly 20 programming languages. Therefore, I empathize with photographers who are **not** software engineers and trying to figure this out. I got as far as the manual, the info buried in the release notes, and the only way was I looked up this project on GitHub and found info buried in the above issue. And it's been closed... why?

I know programming is hard. I do it all day every day. But as programmers, we need to empathize with people and document our stuff **for** people who are **not** programmers, and who might have other challenges, if we want them to use our software.

I was hoping to find a Lightroom alternative as I'm moving to Linux. But it looks like I can't even get this software to work with a very common raw format from a very common camera. I'm sorry, this is just totally unnerving. You guys have put so much time and effort into this, and it's sad that those efforts seem lost to so many due to these basic usability issues. DarkTable could really take off, if only the average target user could figure it out.

### Steps to reproduce

1. Import a Sony ARW file that is uncompressed.
2. Double-click the thumbnail.
3. Note the error message and blank window background where the photo should appear.

### Expected behavior

I expect the latest build of this software to support raw formats for a camera that is nearly 3 years old. If it can't be supported, I expect documentation to this effect with stated reason(s) why it is not supported, and instructions on either: obtaining the relevant color profile and adding it to the software, or an alternative workaround.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

14.5

### Describe your system?

MacBook Pro 2021 M1 Max with 64 GB RAM

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

Apple M1 Max

**Comment by wpferguson** [comment]
> Any explanation for this? Does Sony just not make this matrix available? If so, I know one of the chief product guys at Sony and I'm going to write him about it.

Camera manufacturers don't supply information about their file formats.  Everything darktable uses is reverse engineered.  If the person you know did supply you with information, he'd probably include an NDA with it.

The people that work on darktable are all volunteers.  We all have real jobs, real lives, and real problems.  We do this because we enjoy it, want to give back, want to add our favorite feature, etc.

You mentioned the documentation.  There are 2 people that handle the darktable manual.  They would surely welcome any help.

All or almost all of the developers work on Linux.  There might be 1 or 2 on MacOS and none on Windows.

You're more that welcome to step up and contribute to fixing some of the deficiencies you see.

**Comment by gi-man** [comment]
> Any explanation for this? Does Sony just not make this matrix available? If so, I know one of the chief product guys at Sony and I'm going to write him about it.

Sony raw format is proprietary. They dont share how anything works. We need to reverse engineer it. Go ahead and ask the chief product guys to open source their intellectual property.

> I was hoping to find a Lightroom alternative as I'm moving to Linux.

The main product page highlights that `darktable is not a free Adobe® Lightroom® replacement.`. We strive to make something better for us to use in our own images. We freely open and share our work for others to use (aka FOSS).

**Comment by MStraeten** [comment]
> DarkTable could really take off, if only the average target user could figure it out.

the darktable user is expected to be able to read at least the first chapters of the manual. If he then just expects a free lightroom clone, then he‘s obviously not an ‚average target user‘

**Comment by victoryforce** [comment]
> I expect the latest build of this software to support raw formats for a camera that is nearly 3 years old.

Your expectations are completely unreasonable. As already mentioned, camera manufacturers never describe the formats, metadata and encoding principles of their raw files. In new models, the format may not change relative to older models that are already supported. In such cases, support appears quickly and requires only the creation of xml with a description of the parameters of the raw files. If the format changes, new encoding algorithms are introduced, then open source programs have to wait for someone to reverse-engineer it.

> If it can't be supported, I expect documentation to this effect

Unsupported formats are now documented in the most logical and expected place: the camera support page on the official darktable site.

> with stated reason(s) why it is not supported,

No, the reasons why one or another format is not supported are technical information that should not be dumped on the user.

> instructions on either: obtaining the relevant color profile and adding it to the software, or an alternative workaround.

The color profile message should not have been displayed. Failure to find the color matrix is ​​a consequence of the fact that the format is not supported at all. This is now fixed, the unnecessary message is no longer displayed.

In the end, I don't see a reason why this issue should be open, so I'm closing it.
