### ISSUE TITLE
Cannot create style in light table

### ISSUE THREAD

**Issue by alasta4204** [darktable-org/darktable#17331]
### Describe the bug

 I cannot create a style from the light table menu

### Steps to reproduce

Click on style - create and the dialogue box appears but it's not possible to tick or untick the boxes and it is not possible to type in any text .

### Expected behavior

Darktable should allow me to create a style from an edited image

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro Gnome

### Describe your system?

I am using Manjaro Gnome . 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

[Radeon RX 580 2048SP]

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I  have two PCs running Manjaro . One is used for gaming ( this is the one that has the problem.) The other PC is in my music studio running the same version of Manjaro and the same version of darktable however it is using XFCE and this PC works fine. I suspect this is a GNOME thing.

**Comment by gi-man** [comment]
Are you using wayland? Can you try with X11?

**Comment by gi-man** [comment]
I don't know if it is a Wayland issue, hence why I would like you to test it.

**Comment by alasta4204** [comment]
Good morning everyone this issue is still ongoing for me has there been any
progress?

Warmest Regards

Alastair

**Comment by jenshannoschwalm** [comment]
Whatever the reason to fail is on manjaro, latest fixes to GNOME / wayland / mutter have fixed this.

**Comment by jenshannoschwalm** [comment]
Ok i see. From my understanding this has been fixed in late upstream. Feel free to reopen ...
