### ISSUE TITLE
Request for an Android Version of Darktable

### ISSUE THREAD

**Issue by ArianeNapoli** [darktable-org/darktable#17333]
Hi! 

I was wondering if there are any plans or considerations to develop an Android version of Darktable.

**Comment by ralfbrown** [comment]
None that I'm aware of.  To have any chance at all of happening, all of the libraries that darktable depends on will need to have versions which run on Android.  Starting with Gtk, the GUI library which is deeply intertwined with almost all of darktable.

**Comment by victoryforce** [comment]
I would like to add to this that from the point of view of the UI/UX it will be a completely different program. So, in addition to ensuring the availability of all the necessary libraries, we are talking about rewriting a large part of the program.

If it's a question of whether the desired product is possible, then the answer is yes, of course it is _theoretically possible_, in case a mobile development team comes along to make it happen (but only after they port GTK3, at least).

If this is a request to those people who are currently developing darktable, then the answer is no, you should not expect Android support.
