### ISSUE TITLE
Preserve original filename on import

### ISSUE THREAD

**Issue by mardom1** [darktable-org/darktable#17343]
**Is your feature request related to a problem? Please describe.**
When importing images with a filename pattern the original filename is lost. This prevents reverting to it in the future, ~~which goes against the otherwise non-destructive nature of Darktable.~~

**Describe the solution you'd like**
On import, store the original filename in the XMP metadata, i.e., inside the `xmpMM:PreservedFileName` or `dc:Title` field. Probably wise to do, even if imported without renaming.

**Comment by ptilopteri** [comment]
* Marcel Marquardt ***@***.***> [08-19-24 12:25]:
> **Is your feature request related to a problem? Please describe.**
> When importing images with a filename pattern the original filename is lost. This prevents reverting to it in the future, which goes against the otherwise non-destructive nature of Darktable.
> 


darktable absolutely does not change the original/import filename unless
you have configured darktable to do so.  check your import settings.


-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by mardom1** [comment]
I know that I can configure it to keep the original filename, but I **do** want to rename them. I just want to keep the original filename in the metadata, just in case. Other programs like Lightroom or Digikam also offer the option to preserve it, but it would be incredible if I could do everything inside Darktable.

**Comment by ptilopteri** [comment]
* Marcel Marquardt ***@***.***> [08-19-24 12:44]:

> I know that I can configure it to keep the original filename, but I
> **do** want to rename them.  I just want to keep the original filename
> in the metadata, just in case.  Other programs like Lightroom or Digikam
> also offer the option to preserve it, but it would be incredible if I
> could do everything inside Darktable.


if you had said that to begin with, ... 

-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
facebook/ptilopteri
Photos: http://wahoo.no-ip.org/piwigo                   paka @ IRCnet oftc

**Comment by mardom1** [comment]
Sorry, thought it was clear enough

**Comment by pehar1** [comment]
One of the general principles of darktable is to **never** change the file content. This includes the metadata. I strongly suspect that nobody will be willing to change this.

**Comment by mardom1** [comment]
Oh, I am absolutely not suggesting to touch the file contents. I would treat the preserved filename like all the other metadata and store it in the sidecar files and possibly in the database in case sidecar files are disabled.
