### ISSUE TITLE
Compile in HEIC/HEIF support for ubuntu 22.04

### ISSUE THREAD

**Issue by kpm** [darktable-org/darktable#17361]
### Describe the bug

I found that I was unable to open HEIC files from apple devices in darktable.  I downloaded the latest version of darktable from pre-built .deb made available via https://www.darktable.org/install/  .  libheif1 is already present on my system (because I installed imagemagick perhaps).

Also the "apt install" version of darktable from ubuntu (3.81) has heif support built-in, so it shouldn't be difficult to enable it for OBS builds.

### Steps to reproduce

I downloaded the latest version of darktable from pre-built .deb made available via https://www.darktable.org/install/  .  On the page:

https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

I selected Packages for xUbuntu 22.04: and downloaded darktable_4.8.1-1.1+80.1_amd64.deb

When I use it, libheif support is disabled in the compiler options according to the output of `darktable --version`:

darktable 4.8.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> DISABLED
  libheif                -> DISABLED
  libjxl                 -> DISABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

### Expected behavior

darktable as downloaded from the https://www.darktable.org/ should support heif

### Where did you obtain darktable from?

OBS

### darktable version

darktable_4.8.1-1.1+80.1_amd64.deb

### What OS are you using?

Linux

### What is the version of your OS?

Kubuntu 22.04.4 LTS

### Describe your system?

Imagemagick is installed 

libheif version:
libheif1 is already the newest version (1.12.0-2build1).

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA T550 Laptop GPU Driver Version: 550.90.07      CUDA Version: 12.4

**Comment by kpm** [comment]
Thanks for the info you've supplied.  Only one minor version out, dang!  

I'm probably the only person who has this particular sequence of conditions (running previous LTS, installed from .deb, and trying to import .HEIC), so I will close this issue.  

FYI, I also created an ask ubuntu for this problem at https://askubuntu.com/questions/1524274/how-to-enable-heic-file-support-in-darktable-in-jammy-22-04-4 just incase anyone's interested.  I'm able to use Imagemagick's convert to convert to png, and possibly no information is being lost that way.

Thanks again.

**Comment by victoryforce** [comment]
> As a workaround, I'm able to use Imagemagick's `convert` utility to convert to png, and possibly no information is being lost that way.

You don't need to make such perversions in the workflow. If you can't update Ubuntu to the current LTS, then just use AppImage instead of the package compiled in the native environment.
