### ISSUE TITLE
Master: won't display images after latest update :(

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#17377]
9cbb4a816f6bf21c1ae6f5a2627f67cfa17b6d4e is the first bad commit
commit 9cbb4a816f6bf21c1ae6f5a2627f67cfa17b6d4e
Author: Mario Zimmermann <mail@zisoft.de>
Date:   Fri Aug 23 09:45:17 2024 +0200

    preserve original import filename in xmp data

 src/common/exif.cc              |  3 ++-
 src/common/metadata.c           |  3 ++-
 src/common/metadata.h           |  1 +
 src/control/jobs/control_jobs.c |  7 +++++++
 src/libs/metadata.c             | 13 ++++++++++++-
 src/libs/metadata_view.c        |  2 +-
 6 files changed, 25 insertions(+), 4 deletions(-)

Ubuntu 22.04

**Comment by ptilopteri** [comment]
odd, works for me on openSUSE tumbleweed

**Comment by KarlMagnusLarsson** [comment]
Works for me on Debian 12.6.

**Comment by zisoft** [comment]
@wpferguson: This commit only deals with metadata.
What is the exact problem?

**Comment by wpferguson** [comment]
Did a pull.  Compiled.  Started darktable and no images appeared in lighttable.  Clicked other collections and no images appeared.  Checked out the previous commit and compiled.  Started darktable and images appeared in lighttable.  Ran darktable with -d common, but didn't see any problems.

**Comment by wpferguson** [comment]
![noimages](https://github.com/user-attachments/assets/6688f7ad-7734-4e04-998d-62ab017ba87b)


![version](https://github.com/user-attachments/assets/939a367f-4dd5-46e3-adcb-c417f09d4a41)

**Comment by wpferguson** [comment]
Another data point.  It only occurs for images that I've edited in the last week or so.  Older images display properly and images/collections that I've imported but not edited.

**Comment by wpferguson** [comment]
I had 6 collections that I had edited in the last 2 weeks.  None of them would display any images.

On a guess, I opened the oldest of those collections and reimported the first image.  That image appeared in darkroom.  I returned to lighttable and all the images were there.  I checked the other collections and they also showed all the images.

I don't have any clue about what caused this.  This environment is my ride master and process images.  I spin off other environments for testing so it shouldn't be polluted.

Anyway, it's working now and I'll close this.  If anyone else has the problem then try reimporting an image and see if that clears it.

**Comment by wpferguson** [comment]
Another thought.  These were the images I was working with when we had the database upgrade issue.  Perhaps reimporting the one image created something that was missing in the database?

**Comment by gi-man** [comment]
I had this same issue. Bill fixed solved it.

**Comment by wpferguson** [comment]
Reopened since it's more than just me...

It seems that something isn't getting written to the database and reimporting an image fixes it.  I only noticed on images that had been recently imported (last 30 days).  Older images had no problem.

**Comment by gi-man** [comment]
Mine was on all images. Re importing one that was already there fixed them all.

**Comment by Dero99** [comment]
I also have this issue, osx 64 nightly build. 
Installed build, collections show correct, but no images. Set to show all images and random images show. Relink latest images to image location, now images show, but...
All collections on a certain usb drive have line through them, other locations are linked correctly. Manually relinked collections, then noticed random jpgs now are skulled!  Open those and bump any modules and jpg now shows.

**Comment by pitbuster** [comment]
I confirm that reimporting any of the affected directories fixes the problem on the latest tag.

**Comment by ralfbrown** [comment]
I've seen an empty lighttable when doing an import immediately on a first start with a fresh configuration directory (repeatably if the import is initiated from the commandline, sporadically if from the import module).

There's an initialization error in the collection filters module when darktable starts with a fresh config.  I can make the images show by resetting the module or by switching its "module order" filter from "all images" to something else and back.

I haven't seen issues with previously-imported images or after reimporting, since I was using fresh configs for testing other things....

**Comment by zisoft** [comment]
@ralfbrown: I tried to reproduce that. When I start with a clean config and import an image from the command line

`/darktable --cachedir /Users/mario/src/darktable_test_data/cache --configdir /Users/mario/src/darktable_test_data/config -d common /Users/mario/TestPics/IMG_1234.CR2`

darktable crashes with uninitialized mutexes:
In `src/control/control.c`, function `dt_control_log()`, `dt_pthread_mutex_lock(&darktable.control->log_mutex);`

I have added a `dt_pthread_mutex_init(&darktable.control->log_mutex, NULL);` there, then dt crashes later when trying to lock the mutex `run_mutex`.

This is all called before `dt_control_init()` where all these mutexes are initialized.

**Comment by ralfbrown** [comment]
`dt_control_init` gets called way before any cmdline importing is attempted.  I'm guessing whatever lack of initialization is giving me an empty lighttable is causing other problems on your system.  Can you provide a crash log with stack trace?

**Comment by zisoft** [comment]
I think I found the reason. On an empty config, the styles are imported from the share directory. This is done before `dt_control_init()` is called.

https://github.com/darktable-org/darktable/blob/0f5bd178e3b90726eb7eaeb31efe4a162eef3f59/src/common/darktable.c#L1548-L1577

The style import tries to lock a mutex which isn't initialized at that time.

**Comment by ralfbrown** [comment]
Interesting that that wasn't an issue on my system.  I'm currently running Valgrind to find uninitalized accesses, will make a PR with your suggestion and any other fixes that turns up.

**Comment by jenshannoschwalm** [comment]
@wpferguson can't we close this ?

**Comment by wpferguson** [comment]
Sorry, I thought it had been closed.  Done
