### ISSUE TITLE
full preview icon in light table suggests "cmd+w" shows focus detection. Instead it triggers jumpback to previous layout

### ISSUE THREAD

**Issue by LeoWelter** [darktable-org/darktable#17381]
### Describe the bug

When I select the full preview layout icon at the bottom of lighttable, above the filmstrip is shows: 
f,normal, toggle
w, normal
cmd+w, focus detection

I would expect some sort of focus detection in the full preview to be triggered,
but instead it jumps back to the latest light table view. (the actual focus peaking is activated with shift-cmd-f)

### Steps to reproduce

1: go to light table
2: hover over full preview layout icon and see the suggestions
3: click full preview layout icon
4: keys CMD+w

### Expected behavior

the correct function description for cmd +w

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

MAcOS Sonoma

### Describe your system?

MacBook M1 / 16 GB / 1 TB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Yes, using 4.8.1 on Intel Mac running Sonoma with OCLP
NEFs are from Nikon D700

**Comment by zisoft** [comment]
I think this is a misunderstanding.

The tooltip explains what will be done in the thumbnail view (not fullscreen):

f - will toggle to fullscreen mode
w - will show the currently selected image in fullscreen mode, as long as you hold down w
cmd+w - same as w, the focus areas of your camera (if available) will be shown in the fullscreen view

**Comment by LeoWelter** [comment]
Ok, thanks for the clarification. I misinterpreted focus area (camera) with
the focus peaking (calculated).
