### ISSUE TITLE
Diffuse or sharpen module stronger in low quality preview

### ISSUE THREAD

**Issue by jsmucr** [darktable-org/darktable#17396]
### Describe the bug

With the introduction of high quality preview, it became more obvious that the _Diffuse or sharpen_ module has significantly stronger effect in the low quality preview than in the high quality one. This goes further, and even after exporting, the module effect is noticeably weaker than during the editing session.

Another way how to observe this is to find on an image a detailed area hidden in a deep shade, apply local contrast (like with the _local contrast_ preset) to make the shade more pronounced up to the point where most of the details are gone. Then zoom in to 100 %, and suddenly the details are back, and the shade is no longer as deep.

I'm aware that the module needs to work with a limited amount of image data in order to be usable in the editing scenario, but it I believe it should provide results more similar to what the user gets when the image is exported. The current state presents a challenge when dealing with hundreds of photos a day, where it gets unlikely to finetune each photo separately.

### Steps to reproduce

1. Find an image that would use some local contrast enhancement.
2. Turn on the `Diffuse or sharpen` module, and apply the `Local contrast` preset.
3. Increase the number of iterations up to the point where it appears to be perhaps "too much".
4. Turn on the high quality preview mode.
5. The local contrast effect is no longer as pronounced.

### Expected behavior

While some minor differences are to be expected, the module should provide similar results in all scenarios.

### Logfile | Screenshot | Screencast

Screencast posted here by a different user where the issue is very well obvious:
https://discuss.pixls.us/t/exporting-from-diffuse-or-sharpen/29224/13

My darkroom preview:

![ezgif-3-e9609123b9](https://github.com/user-attachments/assets/dab3a0d0-11fb-448a-b66f-efa67eba0ba8)

Diff:
![preview diff](https://github.com/user-attachments/assets/05ddf504-25fe-4362-a49d-ea232fd29986)

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+331~ga03a2d1adc

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10, Windows 11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070 (but the result is the same with OpenCL turned off and on a different computer)

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Observed in older DT versions too.

**Comment by ralfbrown** [comment]
The d&s algorithm is scaling-sensitive, and darkroom preview normally uses a downsampled image for speed.  Although d&s tries to compensate for the downsampling, that is only an approximation.  It's a major reason why the HQ preview mode was added to darktable...

**Comment by jsmucr** [comment]
I'm aware of that, so the main question here is if that approximation mechanism can be improved in order to get it closer to the intended result.

**Comment by elstoc** [comment]
> the main question here is if that approximation mechanism can be improved

I think the question is "can the mechanism be improved without adversely impacting performance or code quality, and does anyone want to do this work given the size of the gains that might result?" The original author of this module did a lot of work to try to compensate for this, and IIRC thought it a good enough compromise between effort and reward (it's definitely much better than it was in the initial version of the module). 

I usually either zoom or enable HQ mode if I want to see the actual impact on the final image and IMO this is good enough.

**Comment by jsmucr** [comment]
@elstoc How do you see the impact on the entire image if you zoom all the way in? I don't know how about you but I use local contrast to make the image pop, and that's something 100% zoom doesn't solve when it comes to tweaking the overall impression.

Did you guys watch the screencast? I agree that the photos I attached don't look much convincing.

I understand the current state is good enough for a couple of photos. But exporting a couple of hundreds photos, later to learn that they look dull, and that I need to double the amount of iterations for all of them to get closer to the original intention... that is the very reason why I filed this issue.

I'll replace the static photos with a before/after gif.

**Comment by elstoc** [comment]
Again, this is what the high quality processing button is for. If you want an accurate preview of how the image will look when exported, processing the whole image is the easiest way - any alternative approximation may be inaccurate in other ways, since it doesn't have access to the whole image. Yes this will increase processing time (a lot), but that's what you get with diffuse|sharpen.

**Comment by jsmucr** [comment]
Again, I've already read why (allegedly) it's not possible. I'm a developer too, and despite DT not being my domain at all, I know that this is the starting point of nearly every discussion based on a user feedback (especially in FOSS). So let's skip it, please, and let's focus on what can actually be done. If you're fine with the current state, then more power to you, but I hope you'll understand it doesn't really move this topic forward.

Also, if I my point wasn't clear enough, it's the **strength of the effect** what bothers me. Not the quality or precision.

**Comment by jsmucr** [comment]
When my team deals with an issue, a member who has the most suitable knowledge is selected to perform the task. And while I wouldn't dare to assign any task to anyone here, I'm under impression that I'm surrounded by experts who may already know their way around the DT code. I'm used to "no" and "do it yourself" responses in various welcoming communities, and where I know how to do it, I definitely scratch my own itches myself. 
This is however not the case. I don't know C++, I don't know the maths, I don't know anything about color science... I just ask for help. It's that simple. I don't know why such a thing always attracts so many negative responses.

**Comment by parafin** [comment]
Because it’s not an easy (if at all possible) task to solve, while workaround already exists (high quality processing). So others don’t think that result to effort ratio is high enough for this project to be worthwhile. Your estimation may be different (and that’s OK), but you yourself said, that you’re not an expert. Not every idea warrants a positive response, and it’s not personal. I hope in your team you first discuss the idea with the team members most knowledgeable, whether it’s doable and how do they estimate the hours of work needed, before committing to executing it and beginning to assign tasks. Suggestion to try it yourself is actually the most constructive in case you choose to ignore the feedback - you will either come to the same conclusion that it’s too hard to do (and will learn something along the way), or you will prove everyone else wrong, solve this problem and enhance the darktable project in the process.

**Comment by elstoc** [comment]
I literally learned C and GTK in order to fix issues in darktable that were annoying me, because the issues I raised didn't get much attention, and I wanted to contribute to the team.

In my day job we are expected to consult the experts, yes, but also to learn and get our hands dirty if we see something that needs doing, or if we disagree with what the experts are telling us.

**Comment by jsmucr** [comment]
Alright. So I'll hop back on to the original topic train myself. :-)

The fact that the module deals with much lower resolution in LQ is quite obvious when it comes to detail enhancement. My _itch_ is however not the sharpnes but the overall pop of the image. I don't know the terminology, so I'll say "large shadow-ish areas". I can solve the sharpness issue by zooming in but not the impression of the image as a whole.

Here's a gif of HQ with 20 iterations of the _local contrast_ preset, then 6, 7, 10 and 20 in LQ.

![ezgif-3-cacd69020d](https://github.com/user-attachments/assets/ad464d38-2834-4fac-b4eb-fbdaba4490c9)

To my eye, 6 iterations is somewhere around the sweet spot, 10 is too much, and 20 is definitely way too much. So just based on this single use case, I'd create a function transforming HQ to LQ iterations, with an additional bonus of making the preview faster for higher number of iterations. Clearly, this would impact rendition of narrower edges as well, but I hope you see where I'm going.

I'll try the same thing with some other presets tomorrow.

**Comment by jsmucr** [comment]
There's barely any difference with the _bloom_ preset.

![bloom](https://github.com/user-attachments/assets/52391d98-9c1e-4b62-8d53-450e6a810f94)

**Comment by jsmucr** [comment]
Unfortunately, the test didn't go well for _surface blur_.

![surface-blur](https://github.com/user-attachments/assets/7cfe30d1-3fe7-4b0e-a7ef-0a0f01646b69)

**Comment by elstoc** [comment]
> But I don't see any pattern yet

The module is capable of so many varied things, that I don't think you're likely to find a single parameter tweak that works for all use cases. It needs someone who understands what the module is doing under the hood, and the guy who did all the original dev no longer contributes to the project.
