### ISSUE TITLE
darktable crash after loading OM system highresolution file

### ISSUE THREAD

**Issue by Mathieu1965** [darktable-org/darktable#17408]
### Describe the bug

With Olympus E-M1X I created high resolution raw files with 7792 x 10400  Pixel (81.04 MPixels). Importing and showing the thumbnails in lighttable works fine, but changing to darkroom crashes, in all cases. 

### Steps to reproduce

Go to lighttable and select any foto created with Olympus Highres mode (*.ORF) for opening in darkroom, Then immediately darktable crashes. 
Repeating with OpenCL deactivated shows succesful display of foto in darkroom. no crash
Repeating with OpenCl activated and with OpenCL option "use all device memory" activated show correct and stable operation of darktable.

### Expected behavior

darktable should not crash

### Logfile | Screenshot | Screencast

[dt_log.txt](https://github.com/user-attachments/files/16825965/dt_log.txt)
[dt_log opencl.txt](https://github.com/user-attachments/files/16826016/dt_log.opencl.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

AMD Ryzen 7 5700G with Radeon Graphics 
18 GB RAM 2666 MHz

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon  (build in CPU) 512 MB 

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes  and showed
    Magick: caught exception 0xC0000005 "Access violation"...
LUA scripts used: 
require "official/yield"
require "contrib/affinity"  (self made from gimp.lua)
require "contrib/ext_editor" 
require "contrib/OpenInExplorer"
require "contrib/clear_GPS"
require "contrib/copy_attach_detach_tags"
require "contrib/select_untagged"
require "contrib/gpx_export" 
require "official/image_path_in_ui"
require "official/delete_unused_tags"

**Comment by gi-man** [comment]
Can you download and install the lastest AMD drivers for your GPU? 

https://www.amd.com/en/support/download/drivers.html

**Comment by Mathieu1965** [comment]
Indeed the update to the latest drivers to AMD 24.8.1did help. darktable is now stable when using high-res Olympus raw files in following settings: 
- OpenGL off 
- openGL on + use all device memory OFF  (how I found the issue)  
- openGL on + use all device memory ON  
Thanks for the hint!

**Comment by Mathieu1965** [comment]
ticket can be closed

**Comment by gi-man** [comment]
You should not use the all memory setting. It can cause problems.
