### ISSUE TITLE
Specify export size on long and/or short sides instead of width and/or height

### ISSUE THREAD

**Issue by fuzzah** [darktable-org/darktable#17424]
Hello!

Can we specify export size for the long (and/or short) side instead of width/height?

Why: when I export a landscape (horizontal) image, I need to set width (as it's the long side), and when I export a portrait (vertical) image I need to specify height (it's the long side now). If I have 2000 images in different orientations to export, it's impossible to do at the same time: need to select and export landscapes first, and then portraits.

Alternative: we could at least have a "landscape/portrait" filter for image before exporting.

**Comment by wpferguson** [comment]
> Alternative: we could at least have a "landscape/portrait" filter for image before exporting.

You can sort the lighttable by aspect ratio.  > 1 is landscape, < 1 is portrait

**Comment by victoryforce** [comment]
> I.e. rename the "set size" label to "set max size" or even "set max dimensions size"

If you were attentive, you would have noticed that "set size" is a label of the drop-down menu, and it determines in which units of measurement we set the dimensions.

When you hover over the size input fields, you see tooltips that clearly indicate that these are the maximum dimension limits, and not the dimension sizes to which the output will be set.

**Comment by fuzzah** [comment]
> If you were attentive, you would have noticed that "set size" is a label of the drop-down menu, and it determines in which units of measurement we set the dimensions.

So the label is not for the values, but for the drop-down list. It makes sense now, thank you.
But then the values are without any labels: what do they specify? Need to hover over the input fields to see it's the _max_ size (I failed to notice there were tooltips, my bad).

Still, specifying two values kinda suggests the export module would use both of them for every image it processes, e.g. looks like if it would preserve the aspect ratio of the values you specified.

Furthermore, in the interface it may look like this:
```
set size: in pixels
1280 x 1280 px
allow upscaling: yes
```
Kinda looks like exporting with these settings would make the longer side 1280 px but also upscale the shorter side to the same 1280 px, otherwise why would you need to specify two values and have this upscaling option nearby? You may think this scenario preposterous for photographs, but imagine preparing photos for some deep learning algorithm, which would typically require exactly that: squares upscaled or downscaled to certain size no matter what aspect ratio original images had. Hence some users could misinterpret the interface.

It would improve user experience, if the export module's interface was impossible to misunderstand. A lazy user _(such as myself)_ wouldn't bother checking every option's tooltip or trying to export with different settings, they would just come here and create yet another issue :)

**Comment by pehar1** [comment]
Did you read https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/shared/export/ ?
