### ISSUE TITLE
Add option to rate all grouped images when filter displays only part of the group

### ISSUE THREAD

**Issue by fuzzah** [darktable-org/darktable#17423]
Hello!

Can we have a setting to allow rejecting/rating all image formats in group in the lighttable mode at the same time even though image collection is filtered only to a certain format with a filter such as ".JPG"?

Why: I import RAW + JPEG, which gets grouped by the file name. I skim through my images in the lighttable mode to reject/rate them. While doing so I tend to pixel peep at 100% zoom to check for details such as focus. When zooming, lighttable displays RAW image instead of JPEGs I wish to use for 100% zoom. I don't like how RAW image looks, so I apply filter ".JPG". I only use RAWs as a backup in case I miss exposure on JPEG. When this filter is active and I reject/rate an image, its counterpart format (RAW) stays unrated.

Alternative 1: a setting to display JPEG when zoomed in the lighttable mode.
Alternative 2: some helper to propagate one format ratings on other formats in group.
Alternative 3: add a "reject group" button and similar "rate group" buttons 0-5.

Can we have any of these or did I happen to miss such already existing functionality?

**Comment by wpferguson** [comment]
There is a lua-script, `contrib/rate_group` that does this.  Start it, go into the settings->shortcuts->lua-scripts and assign keystrokes to the shortcuts.

**Comment by fuzzah** [comment]
@wpferguson , I believe this would solve the issue. Thank you!
Sadly, the script fails to load for some reason. Created an issue: https://github.com/darktable-org/lua-scripts/issues/506
