### ISSUE TITLE
Failed to read white balance information

### ISSUE THREAD

**Issue by Krenkoth** [darktable-org/darktable#17463]
### Describe the bug

When attempting to open a CR2 file from a Canon Rebel SL2, darktable will not open the file, reverting to lighttable. The message is  "failed to read camera white balance information".

### Steps to reproduce

1. Add CR2 file to library in Darktable
2. Double click to open photo in darkroom
3. Error appears

### Expected behavior

Darktable should open the photo in darkroom

### Logfile | Screenshot | Screencast

![Screenshot (38)](https://github.com/user-attachments/assets/be39c661-7555-479e-ab82-20eac9a3333a)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Describe your system?

16 GB ram, AMD cpu

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Raw file only. I use base darktable with no changes.

**Comment by ralfbrown** [comment]
Does this happen only on a specific file, all files in a particular directory, or all Rebel SL2 files?

That's a spurious error message being reported long after the real error.  The real error is either a missing/unreadable/corrupted file or an unsupported camera model or compression mode for an otherwise supported camera.  It looks like the Rebel SL2 is fully supported, so check that the file exists and can be read.

The next release will have better error handling and reporting (it was merged to master about two weeks ago).

**Comment by Krenkoth** [comment]
All files taken by my SL2 do this. The file can be read, it can be seen in light table, it can be seen in file explorer and it works in dark table when it was converted to a jpeg.

**Comment by ralfbrown** [comment]
OK, we'll need a sample image to see what's going on, or at least the log output from running `darktable -d imageio`.  What you are seeing in lighttable and file explorer is the embedded JPEG generated by the camera, which can often be shown even if the actual raw image can't be decoded.

**Comment by Krenkoth** [comment]
Github does not allow CR2 Image uploads, so here's a google drive link: https://drive.google.com/drive/folders/1EqD-nEt0iZC_QlUDCvIVFJix1sgGQ52z?usp=drive_link

**Comment by ralfbrown** [comment]
This is something you can actually fix in your own installation with a text editor.  Darktable is looking for a mixed-case model name, while the camera has stored it in all-caps....

I don't know where it would be installed on Windows, but search your hard drive for a file  named `cameras.xml` in a directory named `rawspeed`.   You may want to make a backup copy just in case.

Open it with a text editor like Notepad and search for "Rebel SL2".  You should see something like
```
<Alias id="EOS Rebel SL2">Canon EOS Rebel SL2</Alias>
<Alias id="EOS Kiss X9">Canon EOS Kiss X9</Alias>
```
Now duplicate that "Alias" line and change the "Rebel" to "REBEL" in one of the copies to get
```
<Alias id="EOS Rebel SL2">Canon EOS Rebel SL2</Alias>
<Alias id="EOS Rebel SL2">Canon EOS REBEL SL2</Alias>
<Alias id="EOS Kiss X9">Canon EOS Kiss X9</Alias>
```
Save the file.

You will probably need to re-import your images, but after that they should work (when I just tried it now, I got a black image after editing the file but before reimporting).

@LebedevRI Something for the next Rawspeed update.

**Comment by Krenkoth** [comment]
Thank you, this fixed it!

**Comment by ralfbrown** [comment]
RPU likely didn't have an SL2 sample - it's not among those I downloaded for generating camera-specific styles (I did get the 200D which the Rebel SL2 is aliased to).

**Comment by victoryforce** [comment]
@kmilos Why WTH? Everything is clear: in firmware version 1.0.0 the model name contains `Rebel`, in firmware version 1.0.1 it contains `REBEL`.
