### ISSUE TITLE
Unable to open app

### ISSUE THREAD

**Issue by literallyjacked** [darktable-org/darktable#17482]
### Describe the bug

I've tried downloading the three versions of darktable on MacOS and it comes up with the message "cannot be opened as Apple can't check it for malicious software". I've also tried running the commands you've mentioned on Terminal yet it still comes up with the same message. I currently own the MacBook Air M3 and this app is required for my media coursework. If you could, please reply as soon as possible.

### Steps to reproduce

1.  Install darktable via Safari
2. Double click on the downloaded darktable
3. Message pops up and unable to open app
4. Try moving darktable into Finder
5. Click on the app
6. Two options appear: darktable and Applications
7. Click on darktable, same message pops up
8. Click on Applications, takes you back to Findr, placing you in a loop

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

all versions

### What OS are you using?

Mac

### What is the version of your OS?

MacBook Air M3

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment]
> 5. Click on the app
> 6. Two options appear: darktable and Applications

This is a convenience window for easier installation of the app. In this window drag the darktable icon onto the Applications folder. The app will then be installed in the `/Applications` folder on your Mac.

Once you have done that, open the terminal and type
`sudo xattr -c /Applications/darktable.app`
(you will get asked for your password). This needs to be done only once.

**Comment by literallyjacked** [comment]
I’ve followed your instructions but the error still applies. Are there any
other possible ways?

**Comment by zisoft** [comment]
Open terminal and type:

`sudo xattr -dr com.apple.quarantine /Applications/darktable.app`

and see if that works

**Comment by zisoft** [comment]
No response from OP within 2 months, so I'm closing this.
