### ISSUE TITLE
Crash when exiting darkroom "from" Quick Access panel

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#17489]
### Describe the bug

When I have Quick Access panel active and I exit darkroom to lighttable, dt crashes without a trace. When I have any other panel active, I don't have any issues.

### Steps to reproduce

1. Open an image
2. Select quick access panel in the right hand side bar
3. Click lighttable text on the upper right hand corner
4. Crash

### Expected behavior

dt should open lighttable view

### Logfile | Screenshot | Screencast

There is nothing written in the log file. I tried to start dt from command line with -d all -d verbose. The only trace is in Windows event log message Invalid window handle.

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+516~g09e219c19d

### What OS are you using?

Windows

### What is the version of your OS?

Win 11 Enterprise 23H2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA T500, 538.78

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I have deleted every thing from my build directory and the darktable runtime directory, and the issue remains.

**Comment by dterrahe** [comment]
Interesting. Clearly i never even tested that scenario. And neither did anybody else before #17467 got merged and the PR was sitting there for quite a few days exactly for that purpose. 


So, previously, all widgets in all panels were explicitly killed on each view change. Now, widgets are killed for each module that is closed. But modulegroups creates widgets outside its main "widget". So those might persist. it looks to me like the `_basics_hide` in `view_leave` should take care of them, but apparently not. Or the crash could have a totally different reason.


I'm getting on a plane and won't have access to my developer machine for two weeks...

**Comment by ralfbrown** [comment]
Unable to reproduce on Linux with 4.9.0+527~gd8bc3557af using either an existing or a fresh config directory.  I even tried with swapped left/right panels in both cases.

**Comment by dterrahe** [comment]
So it might depend on the content of the qap. Any graphs in there maybe?

**Comment by ralfbrown** [comment]
The default with a fresh config includes graphs for both color equalizer and tone equalizer, as does the existing config I tested.

**Comment by lintujuh** [comment]
The issue has disappeared in 4.9.0+916~gbc7af25093.
