### ISSUE TITLE
Cannot install darktable on Mac studio M2 Max with newest OS installed.

### ISSUE THREAD

**Issue by R1ck7016** [darktable-org/darktable#17497]
### Describe the bug

I followed the procedures for installation of darktable using the sequence and instructions for Mac silicone processors. The Mac indicated that installation was not possible because of the risk of malware. Apple senior advisors, indicated that the developer would have to address the issue by making changes that would allow installation. The workaround published in the installation instructions on the darktable website did not solve the issue. My OS fully up-to-date.

### Steps to reproduce

Followed the installation sequence described on the darktable.org website

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

Most recent download available.

### What OS are you using?

Mac

### What is the version of your OS?

Mac Sonoma 15

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment]
> The Mac indicated that installation was not possible because of the risk of malware

Please select your OS version and see the corresponding instructions here: https://support.apple.com/en-gb/guide/mac-help/mchleab3a043/mac

> Apple senior advisors, indicated that the developer would have to address the issue by making changes that would allow installation

Making changes that would allow the program to be installed without warning is signing that program. This requires the purchase of a membership in the Apple Developer Program and costs the developer 99 USD per year of membership. Want to sponsor this?

**Comment by victoryforce** [comment]
Since this isn't really a darktable bug that we can fix with code changes (without paying Apple annually, that is), I'm closing this issue. The closed status does not prevent further commenting here if anyone has something to add.
