### ISSUE TITLE
Rating via keyboard shortcut in darkroom mode is applied to wrong image if mouse hovers over bottom strip

### ISSUE THREAD

**Issue by fabiosirna** [darktable-org/darktable#17499]
### Describe the bug

In darkroom mode, when trying to assign a rating to the current image using keyboard shortcuts (e.g., 1-3), the rating is applied to the image that the mouse is hovering over in the bottom strip, rather than the currently displayed image.
![Screenshot_20240920_081709](https://github.com/user-attachments/assets/1bd12534-b529-4879-94b8-5e45f6ceb7df)

### Steps to reproduce

1. Open darkroom mode and select an image.
2. Move the mouse over an image in the bottom strip but don’t click it.
3. Use a keyboard shortcut (e.g., 1-3) to assign a rating.
4. The rating is applied to the image in the bottom strip, not the one currently displayed.

### Expected behavior

The rating should be assigned to the image currently displayed in the darkroom view, not the one the mouse is hovering over in the bottom strip. This bug is particularly problematic for users who rely on keyboard navigation (e.g., space and backspace) and might not realize the mouse is over a different image in the bottom strip, leading to incorrect image ratings.  This issue causes confusion and misapplied ratings, especially in workflows where keyboard navigation is preferred.

### Where did you obtain darktable from?

OBS

### darktable version

darktable 4.9.0~git540.f2467107-11967.2

### What OS are you using?

Linux

### What is the version of your OS?

opensuse Tumbleweed

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD RX6700XT

**Comment by pehar1** [comment]
Not a bug but the "act-on" feature which is currently reworked https://github.com/darktable-org/darktable/issues/16850.
