### ISSUE TITLE
When copying a drawn mask from another module, preserve feathering/opacity/etc.

### ISSUE THREAD

**Issue by salmo6** [darktable-org/darktable#17506]
**Is your feature request related to a problem? Please describe.**

I make frequent use of drawn masks, and in almost every case I'm using the same mask (of my subject) in multiple modules. After creating the drawn mask in the first module, I often then use the same mask in several other modules, by using the "use same shapes as x" feature. When I do that, the mask is copied with no feathering, blurring, opacity, or contrast. I then need to reapply those settings manually each time I copy the mask, which is a source of frustration.

**Describe the solution you'd like**

In my use case, there is never a situation where I want those settings to be different in each module -- I want the mask to be completely identical each time I use it. Can there be (or is there already?) a method by which each time I use a mask, it is used with the same feathering, etc. settings applied?

**Comment by ralfbrown** [comment]
The feathering/blurring/mask opacity/mask contrast sliders are for the *final* mask that is built out of *all* shapes and parametric selections.  They are not associated with any particular drawn shape, so they can't be re-used by selecting from the "drawn mask" dropdown.

if you want to re-use the *exact same* mask,  choose the raster mask and select the previous module instead.

**Comment by salmo6** [comment]
Ah, I see. I've never used raster masks before, and to be honest have kind of ignored them. But after a few minutes of experimenting with them I see how they work. I sense a new workflow coming on. :-)

I'll just also say that the raster masks section of the manual, while clear enough on the technical aspects of what they are, doesn't really go into much detail on how they can be used, which may be part of the reason why I've ignored them until now.
