### ISSUE TITLE
More smoother experience using styles

### ISSUE THREAD

**Issue by XRDGlacier** [darktable-org/darktable#17513]
**Is your feature request related to a problem? Please describe.**

- Styles tab should also be on the left side in the darkroom mode. Not it's on the right side on the lighttable and below of the image in the darkroom mode.
- Ability to choose to turn styles pop up preview off
- Ability to choose style apply with double click or single click

**Describe the solution you'd like**

Make these changes optional
- Show styles tab on the left panel in darkroom
- Turn off styles pop-up review
- Choose style apply from double click to single click

**Alternatives**

**Additional context**

**Comment by ralfbrown** [comment]
Current master allows control of which utility modules are displayed, and optionally swapping the utility and processing modules in darkroom view.

Single-click apply in the styles module would prevent you from selecting styles for export, renaming, etc.

**Comment by XRDGlacier** [comment]
Do you have tutorial (video, picture) how I can swap those utility modules or display them?

**Comment by ralfbrown** [comment]
They haven't been written yet, as that functionality was only added last week....
If you're running master, swapping is in the global preferences on the darkroom tab, configuring which are shown is done by right-clicking an empty area in the side panels.

**Comment by XRDGlacier** [comment]
Thank you very much!
