### ISSUE TITLE
smooth scrolling regression - cannot zoom lighttable

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#17517]
After commit `d680195f7e48b420ccb1563d65ac668cc429108f` it is not possible anymore to zoom the lighttable with `ctrl+scroll`.

**Comment by bastibe** [comment]
I'll have a look tonight.

**Comment by bastibe** [comment]
Should be fixed in #17521.

A fairly subtle interaction, where the branch for `DT_THUMBTABLE_MODE_ZOOM` is also used for zooming the `DT_THUMBTABLE_MODE_FILEMANAGER`. Sorry I missed this in the original pull request.
