### ISSUE TITLE
Image corruption when OpenCL "use all device memory" is enabled

### ISSUE THREAD

**Issue by MWP** [darktable-org/darktable#17515]
### Describe the bug

When "use all device memory" is enabled in the OpenCL settings, the right hand 1/3rd of the image preview is corrupted.
It does not occur if "use all device memory" is disabled.
I'm unsure if its related to a single module.

### Steps to reproduce

Description explains it.

### Where did you obtain darktable from?

self compiled

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 22

### Describe your system?

System:
  Kernel: 6.8.0-44-generic arch: x86_64 bits: 64 compiler: gcc v: 13.2.0
  Desktop: Cinnamon v: 6.2.9 Distro: Linux Mint 22 Wilma
    base: Ubuntu 24.04 noble
CPU:
  Info: 12-core model: AMD Ryzen 9 7900X bits: 64 type: MT MCP arch: Zen 4
    rev: 2 cache: L1: 768 KiB L2: 12 MiB L3: 64 MiB
Graphics:
  Device-1: NVIDIA TU104GL [Quadro RTX 4000] vendor: Dell driver: nvidia
    v: 550.107.02 arch: Turing bus-ID: 01:00.0
Info:
  Memory: total: 64 GiB note: est. available: 61.42 GiB
    used: 10.35 GiB (16.9%)
  Processes: 633 Uptime: 1h 25m Init: systemd target: graphical (5)
  Packages: 3602 Compilers: gcc: 13.2.0 Shell: Bash v: 5.2.21 inxi: 3.3.34

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Quadro RTX 4000

**Comment by MWP** [comment]
I've done a little more testing.
It doesn't appear to be related to any particular module. I tried disabling/enabling each when the corruption occurs, and they have no effect.
It also seems to only happen in the darkroom, when DT is maximised on my 4K monitor. If i reduce the size of the DT window, the problem doesn't seem to happen.

**Comment by jenshannoschwalm** [comment]
This is not a dt bug. If you allow all cl memory to be used you are responsible that your system does not use more than the "headroom". See the manual ...

**Comment by MWP** [comment]
The manual says it'll drop back to using the CPU, not that image corruption will occur.
It may be a good idea to add some more info to the tooltip about this.
Thanks.

**Comment by jenshannoschwalm** [comment]
We have https://darktable-org.github.io/dtdocs/en/special-topics/mem-performance/ , i think that explains everything pretty well and correctly.



> The manual says it'll drop back to using the CPU, not that image corruption will occur.

I couldn't spot that. Could you pinpoint me?



> It may be a good idea to add some more info to the tooltip about this.

fair point. Maybe point to the relevant part in the manual ...

**Comment by MWP** [comment]
"The default of 600MB should be fine for most systems. If you find you run into performance problems due to darktable falling back to CPU, try changing it to 800 or larger."

It doesn't say it'll drop back to the CPU exactly, but it kinda implies it.
