### ISSUE TITLE
darkroom: pressing ctrl+e does nothing and raises a Gtk-CRITICAL on console

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#17530]
```
(darktable:449605): Gtk-CRITICAL **: 14:19:41.890: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed

(darktable:449605): Gtk-CRITICAL **: 14:19:52.281: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
```

Maybe related to @dterrahe recent work?

**Comment by dterrahe** [comment]
Probably. Is the export module hidden?

**Comment by dterrahe** [comment]
I'll add a check to prevent the error message when I get back. Hiding a module _will_ disable (most) shortcuts too. And modules that aren't enabled in a view by default won't have working shortcuts in that view either (as I think I mentioned in the PR).
