### ISSUE TITLE
opening darktable from commandline with one image opens in wrong mode

### ISSUE THREAD

**Issue by pejax** [darktable-org/darktable#17539]
### Describe the bug

According to the documentation opening darktable via commandline should open a single image file in darkroom mode and a folder in lighttable mode. Actually it always opens a single file lighttable mode.

### Steps to reproduce

```
darktable <image.raf>
darktable <folder>
```

### Expected behavior

darktable commandline should open an image in darkroom mode

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

macOS 15 Sequoia

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple M1

**Comment by zisoft** [comment]
This is a restriction we have to live with on macOS. It was necessary to fix a crash on import (see #17298).

On macOS it is not possible to distinguish between only a single file passed as parameter on command line or multiple files, so we do not request to open the darkroom here.

**Comment by pejax** [comment]
Thanks for the clarification - this is not a real problem.
