### ISSUE TITLE
Odd timeline behaviour in lighttable

### ISSUE THREAD

**Issue by pejax** [darktable-org/darktable#17541]
### Describe the bug

(Accidentally) clicking outside of the selected timeline range causes the filter to remove all images from the lighttable and to to display a timeline without the current date - which is correct. I found no way to reset the (import) date in the timeline (see screenshot) and have to re-import the images.

### Steps to reproduce

1. Import images to lighttable
2. Click outside the selected range in the timeline (i.e. to the right)
3. The date filter removes the images from the lighttable
4. The timeline now shows a range which does not include the date of the original import (see screenshot)

### Expected behavior

darktable should be able to reset the timeline date filter to original import date range

### Logfile | Screenshot | Screencast

<img width="1440" alt="Bildschirmfoto 2024-09-26 um 13 36 49" src="https://github.com/user-attachments/assets/773544ba-dffc-4366-9082-1b659662220c">
<img width="1440" alt="Bildschirmfoto 2024-09-26 um 13 37 10" src="https://github.com/user-attachments/assets/454998a8-f033-49c1-bb7b-4ea07b3c79e1">

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

macOS 15 Sequoia

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple M1

**Comment by zisoft** [comment]
Selecting something in the timeline adds a rule to the collections module. There you can reset this rule to clear it. No need to reimport the images.

![image](https://github.com/user-attachments/assets/03a88615-3169-40f5-95f2-2f3a93b5a8dd)

**Comment by pejax** [comment]
Ah great, thanks!
