### ISSUE TITLE
Missing index

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#17543]
### Describe the bug

It looks like the DB migrations lose an index (maybe more, this one I spotted when investigating an issue posted on pixls).

The migration step from DB `version == 29` creates the index:
```sql
    TRY_EXEC("CREATE INDEX IF NOT EXISTS main.tagged_images_imgid_index ON tagged_images (imgid)",
             "[init] can't create image index on tagged_images\n");
```
When migrating `version == 32`, the table is recreated, and the indexes are provided:
```sql
    TRY_EXEC("ALTER TABLE `tagged_images` RENAME TO `tagged_images_old`",
         "[init] can't rename tagged_images\n");

    TRY_EXEC("CREATE TABLE `tagged_images` (imgid integer, tagid integer, position INTEGER, "
        "primary key(imgid, tagid), FOREIGN KEY(imgid) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE)",
        "[init] can't create new tagged_images table\n");

    TRY_EXEC("CREATE INDEX tagged_images_position_index ON tagged_images (position)",
        "[init] can't add index tagged_images_position_index\n");
    TRY_EXEC("CREATE INDEX tagged_images_tagid_index ON tagged_images (tagid)",
        "[init] can't add index tagged_images_tagid_index\n");
```

However, the index on `tagged_images (imgid)` is not re-created. According to https://www.sqlite.org/foreignkeys.html#fk_indexes:
> Indices are not required for child key columns but they are almost always beneficial.

Note that there is no FK constraint declared on the tags, only on the images.

The index is also not created (and the FK to the tags table is also not set up) if the library schema is created from scratch:
```sql
  sqlite3_exec(db->handle, "CREATE TABLE main.tagged_images (imgid INTEGER, tagid INTEGER, position INTEGER, "
                           "PRIMARY KEY (imgid, tagid),"
                           "FOREIGN KEY(imgid) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE)", NULL, NULL, NULL);
  sqlite3_exec(db->handle, "CREATE INDEX main.tagged_images_tagid_index ON tagged_images (tagid)", NULL, NULL, NULL);
  sqlite3_exec(db->handle, "CREATE INDEX main.tagged_images_position_index ON tagged_images (position)", NULL, NULL, NULL);
```

### Steps to reproduce

See https://discuss.pixls.us/t/darktable-getting-very-slow/45788/

### Expected behavior

dt should have indexes to speed up DB operations

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

All OSes

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment]
> Note that there is no FK constraint declared on the tags, only on the images.

Not sure I understand. The tags table is in the data.db, not in library.db

**Comment by kofa73** [comment]
OK, now I understand.
`tagged_images` is a join table for an m:n (many-to-many) relationship.
It references 2 foreign keys: the image ID and the tag ID. Normally, if they were in the same schema, one would set up a foreign key constraint; it's probably not possible to do that between different schemas. I just saw one FK set up, and wondered why the other was missing -- now I know. Thanks!

**Comment by kofa73** [comment]
It's not needed, after all, and the observed slowness is due to the sheer size of the DB mentioned on pixls:

> Since imgid is already the first part of the primary key of tagged_images there will be no performance degradation.
https://github.com/darktable-org/darktable/pull/7863#issuecomment-761147206

This is confirmed by the docs ("idx3" is a multi-column index, where the 1st indexed column is the same column as the column indexed by "idx1"):
> Note that Idx3 contains all the same information as the original [Idx1](https://www.sqlite.org/queryplanner.html#fig3). And so if we have Idx3, we do not really need Idx1 any more. The "price of peaches" query can be satisfied using Idx3 by simply ignoring the "state" column of Idx3:
https://www.sqlite.org/queryplanner.html#_multi_column_indices
