### ISSUE TITLE
exposure bias does not show a value

### ISSUE THREAD

**Issue by jocus11** [darktable-org/darktable#17567]
### Describe the bug

In the lighttable the exposure bias for the image information does not show a value. It shows only -.
![2024-09-30 16_35_31-Window](https://github.com/user-attachments/assets/9cbf1cbc-45db-4a6a-ac97-35d316fe0718)

### Steps to reproduce

Go to lighttable
Select picture
Select image information on the left

### Expected behavior

Should show a value

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

None

**Comment by elstoc** [comment]
Please can you confirm that you definitely shot that image in a mode where a non-zero exposure compensation was applied? I wouldn't necessarily expect this to appear if, for example, no compensation was applied, or the image was shot in manual mode.

At the end of the day we're dependent on this information actually being present in the raw file being imported, so if you could provide some output from exiftool (or some other exif viewer) to confirm that the information is definitely present on the image in question, that would be helpful.

**Comment by zisoft** [comment]
I see in your screenshot that "Exposure program" is empty as well.

Please perform a "Refresh Exif" on that image and see if that helps.
(Action on selection module --> metadata tab --> refresh EXIF)

**Comment by jocus11** [comment]
Case closed

**Comment by victoryforce** [comment]
> Though it is weird that the info for all pictures (>50.000) was gone

@jocus11 If I understand your case correctly, those 50k images were imported before darktable added support for a few more EXIF ​​fields. So those fields didn't gone from those images, instead they were read into the darktable database when importing. That's why refreshing EXIF ​​fixes it.
