### ISSUE TITLE
cannot open qoi file format

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#17560]
I know this has been discussed somewhere but I cannot find the reference. So better tracking this here to ensure it is fixed for 5.0.

**Comment by ralfbrown** [comment]
Didn't see the discussion on 12894 at the time, but merging 17368 should fix the error by recognizing QOI files and specifically invoking the QOI loader on them.

**Comment by victoryforce** [comment]
@TurboGit There is no issue with 4.9.0-661-gf10d881fcd.
