### ISSUE TITLE
Unable to Export JPG if image has Blurs module active

### ISSUE THREAD

**Issue by Dero99** [darktable-org/darktable#17569]
### Describe the bug

Processed Image, using Blurs and Darktable crashes.  Using History, go before Blurs applied, Exports OK.
 Apple Problem Report:
Process:               darktable [1081]
Path:                  /Applications/darktable.app/Contents/MacOS/darktable
Identifier:            org.darktable
Version:               4.9.0 (4.9.0.331)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-30 09:39:33.7261 -0700
OS Version:            macOS 15.0 (24A335)
Report Version:        12
Bridge OS Version:     9.0 (22P353)
Anonymous UUID:        BD2BA9FA-C8A7-ED35-D381-480CDE321C7C

Time Awake Since Boot: 540 seconds

System Integrity Protection: enabled

Crashed Thread:        1  Dispatch queue: opencl_runtime

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   darktable [1081]

Application Specific Information:
abort() called

Application Specific Signatures:
Graphics hardware encountered an error and was reset: 0x00000002

Launched Darktable via Terminal:
% /Applications/darktable.app/Contents/MacOS/darktable -d all
 
34.5527 [masks] render all masks took 0.0249 sec
    34.5540 blend with form           CL0 [export]         blurs                  (   0/   0) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000 IOP_CS_RGB, BLEND_CS_RGB_SCENE, inverted, form available and rendered
    34.5541 [opencl memory] device 0: 223906884 bytes (213.5 MB) in use, 639.8 MB available GPU memory, 1536.0 MB global GPU mem size
    49.7334 [opencl memory] device 0: 246273092 bytes (234.9 MB) in use, 639.8 MB available GPU memory, 1536.0 MB global GPU mem size
    49.7334 [opencl memory] device 0: 268639300 bytes (256.2 MB) in use, 639.8 MB available GPU memory, 1536.0 MB global GPU mem size
zsh: abort      /Applications/darktable.app/Contents/MacOS/darktable -d all

### Steps to reproduce

Enable Blurs, Crash on Export, deselect Blurs, Export success

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.9.0+621~gf737cc4fdd  and version two weeks earlier

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 15.0

### Describe your system?

Mac mini Intel

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple

**Comment by ralfbrown** [comment]
Actual crash or just stopped responding?  What radius have you set for the blur?  Blurs gets **extremely** slow at large radii because each doubling of the radius quadruples the compute.

**Comment by Dero99** [comment]
As log clips show, full crash.

Disabling OpenCL and it exports with Blurs, quite fast actually.

Blurs set to 60px radius, with a mask.

D

**Comment by jenshannoschwalm** [comment]
@Dero99 could you provide a screenshot of your mask settings? Details threshold or guided filter active?

As your OpenCL memory is pretty small i suspect there is a bug in our code calculating the mem requirements for blending. A proper log (-d pipe -d opencl) would also be helpful.

**Comment by Dero99** [comment]
Hi





￼







Terminal output of Export session:

***@***.*** ~ % /Applications/darktable.app/Contents/MacOS/darktable -d pipe -d opencl
darktable 4.9.0+621~gf737cc4fdd
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.4.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> DISABLED
  ImageMagick            -> ENABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  LibRaw                 -> ENABLED  - Version 0.22.0-Devel202403
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0002 [dt starting] /Applications/darktable.app/Contents/MacOS/darktable -d pipe -d opencl

(process:32606): GLib-GObject-CRITICAL **: 07:16:57.912: g_object_set: assertion 'G_IS_OBJECT (object)' failed
     0.2477 [dt_get_sysresource_level] switched to 1 as `default'
     0.2477   total mem:       65536MB
     0.2477   mipmap cache:    8192MB
     0.2477   available mem:   32768MB
     0.2477   singlebuff:      512MB
     0.2495 [opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL' found on your system and loaded, preference 'default path'
     0.2495 [opencl_init] found 1 platform
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz'
   CONF KEY:                 cldevice_v5_appleintelrcoretmi38100bcpu360ghz
   PLATFORM, VENDOR & ID:    Apple, Apple, ID=-1
   CANONICAL NAME:           appleintelrcoretmi38100bcpu360ghz
   DRIVER VERSION:           1.1
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              CPU, unified mem
   GLOBAL MEM SIZE:          65536 MB
   MAX MEM ALLOC:            16384 MB
   MAX IMAGE SIZE:           8192 x 8192
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1 1 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                1000
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   *** marked as disabled ***

[dt_opencl_device_init]
   DEVICE:                   1: 'Intel(R) UHD Graphics 630'
   CONF KEY:                 cldevice_v5_appleintelruhdgraphics630
   PLATFORM, VENDOR & ID:    Apple, Apple, ID=16925952
   CANONICAL NAME:           appleintelruhdgraphics630
   DRIVER VERSION:           1.2(Aug 12 2024 21:40:39)
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              GPU, unified mem
   GLOBAL MEM SIZE:          1536 MB
   MAX MEM ALLOC:            384 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 256 256 256 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /Applications/darktable.app/Contents/Resources/share/darktable/kernels
   KERNEL DIRECTORY:         /Users/fleming/.cache/darktable/cached_v5_kernels_for_AppleIntelRUHDGraphics630_12Aug122024214039
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DUNKNOWN=1 -I/Applications/darktable.app/Contents/Resources/share/darktable/kernels
   KERNEL LOADING TIME:       0.0127 sec
[opencl_init] OpenCL successfully initialized. internal numbers and names of available devices:
[opencl_init]		0	'Apple Intel(R) UHD Graphics 630'
     0.2831 [opencl_init] FINALLY: opencl PREFERENCE=ON is AVAILABLE and ENABLED.
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_update_priorities] these are your device priorities:
[opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[opencl_update_priorities] 		image	preview	export	thumbs	preview2
[opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200
   UNIFIED MEM SIZE:         1536 MB reserved for 'appleintelruhdgraphics630'
[opencl_update_priorities] these are your device priorities:
[opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[opencl_update_priorities] 		image	preview	export	thumbs	preview2
[opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200

(darktable:32606): Gtk-CRITICAL **: 07:16:58.404: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2024-10-02 07:17:02.477 darktable[32606:1107994] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-02 07:17:02.477 darktable[32606:1107994] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15 (delta 10), reused 8 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (15/15), 6.19 KiB | 373.00 KiB/s, done.
From https://github.com/darktable-org/lua-scripts
   ee9384b..e359567  master     -> origin/master
Switched to branch 'master'
Your branch is behind 'origin/master' by 28 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
    47.9731 modify roi OUT                [export]         flip                   (   0/   0) 4928x3264 scale=1.0000 --> (   0/   0) 3264x4928 scale=1.0000 ID=14201
    47.9732 modify roi OUT                [export]         crop                   (   0/   0) 3264x4928 scale=1.0000 --> ( 630/1126) 2137x2601 scale=1.0000 ID=14201
    47.9732 pipe starting             CL0 [export]                                (   0/   0) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000 ID=14201, appleintelruhdgraphics630
    47.9732 [dt_opencl_check_tuning] use 639MB (headroom=OFF, pinning=OFF) on device `Apple Intel(R) UHD Graphics 630' id=0
    47.9735 modify roi IN                 [export]         crop                   (   0/   0) 2137x2601 scale=1.0000 --> ( 630/1126) 2137x2601 scale=1.0000 ID=14201
    47.9736 modify roi IN                 [export]         flip                   ( 630/1126) 2137x2601 scale=1.0000 --> (1201/ 630) 2601x2137 scale=1.0000 ID=14201
    47.9739 modify roi IN                 [export]         lens                   (1201/ 630) 2601x2137 scale=1.0000 --> (1215/ 641) 2571x2112 scale=1.0000 ID=14201
    47.9740 pixelpipe data 1:1 copied     [export]                                (1215/ 641) 2571x2112 scale=1.0000 --> (1215/ 641) 2571x2112 scale=1.0000 bpp=16
    48.0156 process                   CL0 [export]         temperature            (1215/ 641) 2571x2112 scale=1.0000 --> (1215/ 641) 2571x2112 scale=1.0000   3 IOP_CS_RGB
    48.0370 process                   CL0 [export]         highlights             (1215/ 641) 2571x2112 scale=1.0000 --> (1215/ 641) 2571x2112 scale=1.0000   4 IOP_CS_RGB
    48.0469 process                   CL0 [export]         colorin                (1215/ 641) 2571x2112 scale=1.0000 --> (1215/ 641) 2571x2112 scale=1.0000   9 IOP_CS_RGB -> IOP_CS_LAB
    48.0809 transform colorspace      CL0 [export]         denoiseprofile         (1215/ 641) 2571x2112 scale=1.0000 IOP_CS_LAB -> IOP_CS_RGB
    48.1085 process tiled             CL0 [export]         denoiseprofile         (1215/ 641) 2571x2112 scale=1.0000 --> (1215/ 641) 2571x2112 scale=1.0000  10 IOP_CS_RGB
    48.5517 process                   CL0 [export]         lens                   (1215/ 641) 2571x2112 scale=1.0000 --> (1201/ 630) 2601x2137 scale=1.0000  14 IOP_CS_RGB
    48.7547 process                   CL0 [export]         flip                   (1201/ 630) 2601x2137 scale=1.0000 --> ( 630/1126) 2137x2601 scale=1.0000  18 IOP_CS_RGB
    48.7734 process                   CL0 [export]         exposure               ( 630/1126) 2137x2601 scale=1.0000 --> ( 630/1126) 2137x2601 scale=1.0000  25 IOP_CS_RGB
    48.7922 process                   CL0 [export]         exposure.1             ( 630/1126) 2137x2601 scale=1.0000 --> ( 630/1126) 2137x2601 scale=1.0000  26 IOP_CS_RGB
    48.8202 blend with form           CL0 [export]         exposure.1             ( 630/1126) 2137x2601 scale=1.0000 --> ( 630/1126) 2137x2601 scale=1.0000 IOP_CS_RGB, BLEND_CS_RGB_SCENE, inverted, form available and rendered
    49.0893 process                   CL0 [export]         crop                   ( 630/1126) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000  30 IOP_CS_RGB
    49.0981 process                   CL0 [export]         channelmixerrgb        (   0/   0) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000  34 IOP_CS_RGB
    49.1250 process tiled             CL0 [export]         diffuse                (   0/   0) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000  35 IOP_CS_RGB
    68.2395 process                   CL0 [export]         blurs                  (   0/   0) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000  38 IOP_CS_RGB
    68.2569 blend with form           CL0 [export]         blurs                  (   0/   0) 2137x2601 scale=1.0000 --> (   0/   0) 2137x2601 scale=1.0000 IOP_CS_RGB, BLEND_CS_RGB_SCENE, inverted, form available and rendered
zsh: abort      /Applications/darktable.app/Contents/MacOS/darktable -d pipe -d opencl
***@***.*** ~ % 


D

**Comment by jenshannoschwalm** [comment]
... Still missing a screenshot of the module's blending parameters like
![Bildschirmfoto vom 2024-10-02 17-15-33](https://github.com/user-attachments/assets/9c2a4be9-1e80-4a9f-9d4c-e11c05fbb24e) or provide details otherwise.

**Comment by Dero99** [comment]
Humm, it was in my reply but doesn’t show on GitHub. Guess you can’t attach images. Will try again soon. DarrellOn Oct 2, 2024, at 8:16 AM, Hanno Schwalm ***@***.***> wrote:﻿
... Still missing a screenshot of the module's blending parameters like
Bildschirmfoto.vom.2024-10-02.17-15-33.png (view on web) or provide details otherwise.

**Comment by Dero99** [comment]
![Screenshot 2024-10-02 at 9 16 54 AM](https://github.com/user-attachments/assets/c5772aeb-f325-421f-bdf9-96b686a1de3d)

**Comment by jenshannoschwalm** [comment]
From your log the module should not do the processing of the blur module with blending on the GPU, there is certainly not enough memory. Investigating ...

**Comment by jenshannoschwalm** [comment]
Could you check this with current master? If issue is persiting, could you provide a fresh log? Otherwise concider to close this...

**Comment by Dero99** [comment]
Installed current nightly for x86_64 and it correctly exported the image with Blurs to jpg.Fixed, thanks. D.On Oct 12, 2024, at 9:41 PM, Hanno Schwalm ***@***.***> wrote:﻿
Could you check this with current master? If issue is persiting, could you provide a fresh log? Otherwise concider to close this...
