### ISSUE TITLE
MONITOR COLOR CALIBRATION PROFILE FOR DARKTABLE (inquiry not an issue)

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#17601]
**Is your feature request related to a problem? Please describe.**

- I recently calibrated my monitor using the Spyder 5 Elite calibration tool. I also did a calibration using DisplayCal software and preferred its profile.  I would like to know if there is a way for these newly created profiles be added to darktable. I notice that the color and brightness is different within darktable vs the actual exported file. When I tried exporting 1 photo it appeared darker when viewed outside darktable. Is there a way to fix this?
![darktable_error4](https://github.com/user-attachments/assets/207c495a-36d1-407f-b220-d6ea4139919c)

**Describe the solution you'd like**

- Color calibration profile (icc profile) be available within darktable

**Alternatives**

- waiting for suggestions

**Additional context**

![darktable_error4](https://github.com/user-attachments/assets/ee5d11a0-b02b-4138-a541-daf13b5e59ec)
- Nothing follows

**Comment by ralfbrown** [comment]
For getting multiple programs to display things the same way, you need to embed the color profile in the output file (which darktable does for all formats supporting it) *and* ensure that the other programs properly apply color management.  For a custom display profile, the best approach is to install it as your operating system's default monitor profile so that all programs get it by default; if you use a colorspace other than sRGB in the image file, you still need to ensure that all programs apply color management to properly map the stored colors.

For darktable specifically, you can add output profiles to its configuration directory in subdirectory `color/out` (you will likely need to create the subdirectory).  They will then be shown in darktable's profile selection.  See also https://darktable-org.github.io/dtdocs/en/special-topics/color-management/display-profile/ and https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/output-color-profile/

**Comment by blackzerotype** [comment]
> For getting multiple programs to display things the same way, you need to embed the color profile in the output file (which darktable does for all formats supporting it) _and_ ensure that the other programs properly apply color management. For a custom display profile, the best approach is to install it as your operating system's default monitor profile so that all programs get it by default; if you use a colorspace other than sRGB in the image file, you still need to ensure that all programs apply color management to properly map the stored colors.
> 
> For darktable specifically, you can add output profiles to its configuration directory in subdirectory `color/out` (you will likely need to create the subdirectory). They will then be shown in darktable's profile selection. See also https://darktable-org.github.io/dtdocs/en/special-topics/color-management/display-profile/ and https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/output-color-profile/

Thank you. I don't quite understand the coding. Can you please show me how to create this subdirectory and apply it to darktable? Very much appreciated the assistance. :)

**Comment by MStraeten** [comment]
you forgot to tell, that you’re on windows, so you need an additional hint: https://www.darktable.org/about/faq/#faq-windows-config
This directs to the directory the settings are saved on windows. There you need to create the color/out directory for your profile file

**Comment by blackzerotype** [comment]
> you forgot to tell, that you’re on windows, so you need an additional hint: https://www.darktable.org/about/faq/#faq-windows-config This directs to the directory the settings are saved on windows. There you need to create the color/out directory for your profile file

-I've already created the subdirectory, copied and pasted the icc profile to it. I also restarted darktable but the icc profile is not in the dropdown under profiles in darktable. Did I miss something or am I doing wrong? 

![image](https://github.com/user-attachments/assets/adc775cf-f013-4bdc-a468-3b51a6556c6f)

**Comment by ralfbrown** [comment]
What did you call the file you put in color/out?  Darktable will only look for files named *.icc and *.icm (upper/lowercase doesn't matter).

**Comment by blackzerotype** [comment]
> What did you call the file you put in color/out? Darktable will only look for files named *.icc and *.icm (upper/lowercase doesn't matter).

This one. Please see

![image](https://github.com/user-attachments/assets/2df0577f-02d5-46d3-b978-4cdc40b4ee84)

**Comment by MStraeten** [comment]
then it's time to read further in https://www.darktable.org/about/faq/#faq-windows-logs and https://www.darktable.org/about/faq/#faq-windows-bugs

please run darktbale from commandline with option -d common and serach the result for the term "output profile". there you should get a hint, if your profile is supported or not

**Comment by blackzerotype** [comment]
> then it's time to read further in https://www.darktable.org/about/faq/#faq-windows-logs and https://www.darktable.org/about/faq/#faq-windows-bugs
> 
> please run darktbale from commandline with option -d common and serach the result for the term "output profile". there you should get a hint, if your profile is supported or not

I have this in the command propmpt
![image](https://github.com/user-attachments/assets/a43fcd0c-8c76-44f7-ba9b-00126d76be1e)

**Comment by MStraeten** [comment]
maybe you need quotation marks for directories containing blanks …

**Comment by todd-prior** [comment]
@blackzerotype You are not going to want a display profile for and output profile when exporting... If you see the profile when you set your display profile and not when you export it seems DT is figuring that out for you... That profile from displaycal should be set for your system, darktable ( in color/out) and for any apps that you are trying to view with... you could trust the software to correctly use the OS setting as this is what many are set to by default but I like to explicitly set it.... if you can't there might even be a good chance that the software is not color manage and so will be defaulting to something else.... Making sure they are all using the same display profile should be the first thing... then if you are using a current version of DT you will likely need to turn on the HighQuality processing preview esp if you use yes when exporting to get the best match of preview and export.... if you still have issue then I guess we could look for some other issue....

**Comment by blackzerotype** [comment]
> @blackzerotype You are not going to want a display profile for an output profile when exporting... If you see the profile when you set your display profile and not when you export it seems DT is figuring that out for you... That profile from displaycal should be set for your system, darktable ( in color/out) and for any apps that you are trying to view with... you could trust the software to correctly use the OS setting as this is what many are set to by default but I like to explicitly set it.... if you can't there might even be a good chance that the software is not color manage and so will be defaulting to something else.... Making sure they are all using the same display profile should be the first thing... then if you are using a current version of DT you will likely need to turn on the HighQuality processing preview esp if you use yes when exporting to get the best match of preview and export.... if you still have issue then I guess we could look for some other issue....

this seemed to work. But can you please tell me where can I find this HighQuality processing preview? I'll try it too

![image](https://github.com/user-attachments/assets/621330f1-fce0-462c-8873-c3a183a27a42)

**Comment by todd-prior** [comment]
![image](https://github.com/user-attachments/assets/d1731a1d-fa8d-43e4-b04c-537a49d7c6be)

Icon at the bottom of darkroom view...next to color assessment lightbulb icon.... it makes the preview very slow....but its a better match if you are using yes when you export for HQR....

**Comment by blackzerotype** [comment]
> ![image](https://private-user-images.githubusercontent.com/44409419/375198431-d1731a1d-fa8d-43e4-b04c-537a49d7c6be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Mjk3NTUsIm5iZiI6MTcyODUyOTQ1NSwicGF0aCI6Ii80NDQwOTQxOS8zNzUxOTg0MzEtZDE3MzFhMWQtZmE4ZC00M2U0LWIwNGMtNTM3YTQ5ZDdjNmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZDE3YTE5OWQ4ZDk3YzdhZWFlMjU5MjJhYWI1ODc5ZTRhZWE2M2RmNGJlOWMyNzhkYzViNjcxZWQ4ZDc3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BPlO05pDev6WlEHueuchXi1bcxrH7Og3tbhgyoP_Hw8)
> 
> Icon at the bottom of darkroom view...next to color assessment lightbulb icon.... it makes the preview very slow....but its a better match if you are using yes when you export for HQR....

Got it thank you.

**Comment by MStraeten** [comment]
> you will likely need to turn on the HighQuality processing preview esp if you use yes when exporting to get the best match of preview and export

high quality processing isn’t about proper color management during export. Don’t mix up colormanagement stuff related to the display and colormanagement related to the embedded profile of an exported image.

**Comment by blackzerotype** [comment]
> > you will likely need to turn on the HighQuality processing preview esp if you use yes when exporting to get the best match of preview and export
> 
> high quality processing isn’t about proper color management during export. Don’t mix up colormanagement stuff related to the display and colormanagement related to the embedded profile of an exported image.

what module should I use to reduce the reds on skin tone? I'm confused as what module to go to correct this. Please help. ty

**Comment by MStraeten** [comment]
> what module should I use to reduce the reds on skin tone? I'm confused as what module to go to correct this. Please help. ty

for such discussion better switch over to https://discuss.pixls.us/c/software/darktable/19 since this is not an issue ;)

(but you might have a look at https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/color-equalizer/)

**Comment by todd-prior** [comment]
> > you will likely need to turn on the HighQuality processing preview esp if you use yes when exporting to get the best match of preview and export
> 
> high quality processing isn’t about proper color management during export. Don’t mix up colormanagement stuff related to the display and colormanagement related to the embedded profile of an exported image.

He is asking about color and brightness and asking about matching the export all things that can really change quite a bit by simply activating the HQ preview... It seems to have quite strong impact for some images and combinations of modules such that the preview can appear to show some color shifts and changes in brightness and even at times percieved contrast. Having normal preview and HQ reprocessing on for an export can introduce a mismatch in the two results so I was just suggesting that he check it.... I wasn't suggesting it as part of color management but as a means to have the most accurate preview for his export.....

**Comment by blackzerotype** [comment]
> > > you will likely need to turn on the HighQuality processing preview esp if you use yes when exporting to get the best match of preview and export
> > 
> > 
> > high quality processing isn’t about proper color management during export. Don’t mix up colormanagement stuff related to the display and colormanagement related to the embedded profile of an exported image.
> 
> He is asking about color and brightness and asking about matching the export all things that can really change quite a bit by simply activating the HQ preview... It seems to have quite strong impact for some images and combinations of modules such that the preview can appear to show some color shifts and changes in brightness and even at times percieved contrast. Having normal preview and HQ reprocessing on for an export can introduce a mismatch in the two results so I was just suggesting that he check it.... I wasn't suggesting it as part of color management but as a means to have the most accurate preview for his export.....

Thank you guys for the inputs and suggestions. I was messing with the color equalizer module and haven't found the right mix for the skin tone. I will explore this module further. For now, you may close this ticket. Thanks again I appreciate it :)
