### ISSUE TITLE
Garbage pixels outside image border

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#17605]
### Describe the bug

When using the _scale_ slider in _lens correction_, pixels that would normally fall outside the image border can become visible. It seems that with the Panasonic LX7 in 3:2 mode at least, these pixels are garbage (there have been similar issues before, due to the multi-aspect setup of the camera).

### Steps to reproduce

1. Get the files (raw + sidecar) from http://tech.kovacs-telekes.org/files/2024-10-05-garbage-pixels-outside-border/2024-09-29-16-03-32-P1040483.RW2
2. Import, open in darkroom

### Expected behavior

No garbage pixels

### Logfile | Screenshot | Screencast

https://tech.kovacs-telekes.org/files/2024-10-05-garbage-pixels-outside-border/garbage-pixels.png

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+693~gf302ac54ea

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

OpenCL on/off makes no difference

**Comment by MStraeten** [comment]
is it really a bug? unfortunately i can't download the sample - maybe check the raw crop (you can enable that via `plugins/darkroom/rawprepare/expanded=TRUE` in darktablerc) if there's some weird stuff around.

**Comment by kofa73** [comment]
My bad - I somehow managed to copy the raw crop from another image (with a different aspect ratio) onto this one. Resetting the module fixed it. Thanks!
