### ISSUE TITLE
Unusual color and contrast difference when exporting and downsizing an ARW file to output 8 bit JPG from Lightbox

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#17638]
### Describe the bug

Go to 'additional context'...
I am not able to provide files.
I just want to describe the phenomenon based on more than one year of daily editing in Darktable without this problem - has this problem been reported by others.
Normally using Darktable and lately version 4.9.0-549-g0fbd178e3 the Export function typically to 8 bit JPG at 80 percent quality creates JPG copies close to be visually identical to the source raw file (ARW). 
_The latest image shows a discrepancy in color and contrast._
The original and often slightly cropped raw file, i.e. almost original size, is exported with the following parameters:
JPEG (8-bit), 80, auto, 2048x0, no, yes, sRGB (web-safe), relative colorimetric, none.
Thumbnails use the raw file instead of the embedded JPG.
This is my suspicion: With the actual image having a yellow-green foreground with grass isolated from the background of more grey-blueish tree trunks using a masking path in the Color equalizer module, it seems as if the separation is lost in the copy and the editing making the grass more warm with a saturation - bleeds to the background - making it more warm and less contrasty.

### Steps to reproduce

See the description above.

### Expected behavior

The JPG copy is normally largely identical viewed in Lighttable.

### Commit

The Export function in Lighttable.

### Where did you obtain darktable from?

GitHub nightly

### darktable version

 4.9.0-549-g0fbd178e3 and 4.9.0+776~g6667649af8

### What OS are you using?

Windows

### What is the version of your OS?

Microsoft Windows 11 Pro, version 10.022631

### Describe your system?

Dimensioned for image editing.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

The same behavior for the mentioned versions of Darktable.
A TIFF file from editing the same ARW-file in Affinity exported to the actual Darktable folder - and stripped from the xmp-file - can be exported to an identical JPEG using the same settings in Darktable.
**Fresh edit: The problem seems to be introduced with the Haze removal module here used at 0.51 strength.**

**Comment by KIRSJ** [comment]
I think the Haze removal module is not being written or read properly to/from the xmp-file.

**Comment by jenshannoschwalm** [comment]
Another round of "haze removal" issue so basically a duplicate.

**Comment by KIRSJ** [comment]
jenshannoschwalm,
Duplicate of which report, could you be more specific?

**Comment by jenshannoschwalm** [comment]
@KIRSJ see above PR. If i misunderstood your issue please provide more precise information including at least the rawfile and xmp . Also i was not sure what you were comparing *exactly*.

**Comment by KIRSJ** [comment]
jenshannoschwalm,
Thank you. The #17650 explanation goes over my head, as I am not directly involved with the Darktable code. My observation is a shift in contrast and colors using this module when the (ARW) raw-based output from Darkroom is exported to a JPEG. If the technical explanation in #17650 covers that then good, otherwise I can't provide further documentation. Sorry about that, but wanted to ring the bell anyway should have had a similar problem.
I rarely use the Dehaze removal module. But as far as I understand is has not been flagged as problematic when using the scene-referred (filmic) mode.

**Comment by jenshannoschwalm** [comment]
1. You might share the raw and xmp file with your edits so i could investigate if there are other problems :-)
2. It's not about scene-referred mode at all. Haze-removal had some code parts missing leading to a more stable/correct result. It will be much better after the mentioned PR has been merged.

Anyway, thanks for reporting and thus reminding me to fix this :-)

**Comment by KIRSJ** [comment]
jenshannoschwalm,
Thanks for the clarification. When do you think the fix will be available from nightly builds?

**Comment by jenshannoschwalm** [comment]
Pretty soon i think :-)

**Comment by KIRSJ** [comment]
Good, thanks.
