### ISSUE TITLE
There are some English parts in the Chinese translated version of Darktable (may they be untranslated?)

### ISSUE THREAD

**Issue by C-CH621** [darktable-org/darktable#17633]
### Describe the bug

When I used the Chinese translated version of Darktable, I noticed that the prompt section about Lua scripts installer in the bottom left corner of the page was presented in English. What is the reason for this? Is it because it is a new module added after the existing translation?

### Steps to reproduce

After downloading the software and opening it, you will find this problem. The translation of other parts is very appropriate.

### Logfile | Screenshot | Screencast

![eebb472ab900590c7a46a4a5c40345d](https://github.com/user-attachments/assets/e660a456-17d1-4f2b-873d-cade59d3226a)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment]
I don't think Lua scripts (including the script installer) were localized in 4.8 -- it looks like that work didn't start until August, although there were some preparations made in January.

**Comment by C-CH621** [comment]
I am a beginner, so I may know a little less. Does Lua scripts localization in Chinese refer to extracting these texts and translating them? So is no one doing this job now?

**Comment by ralfbrown** [comment]
The non-technical translation of the above is that it wasn't even possible to have scripts with translated texts (other than making multiple versions) until after 4.8 was released....
And the script installer is itself a script.

**Comment by C-CH621** [comment]
What should we do if we want to localize this part of the content now? Is there anything I can contribute to? It would be great if my work could be used in future versions to help future users! Even if it may only be a small change. (I hope I understand your meaning correctly, because I may have simplified this question before and thought that only this part was not translated. Sincerely thank you for your help)

**Comment by HSUfineprint** [comment]
> What should we do if we want to localize this part of the content now? Is there anything I can contribute to?

Lua scripts could not be translated before, there is nothing translators can do. Just wait for the future release version. And, you can contact the translator to show your willingness to help.

**Comment by C-CH621** [comment]
Okay, thank you for your answer🎇

**Comment by victoryforce** [comment]
This issue was fully resolved after the merge of #17736. So I'm closing this.
