### ISSUE TITLE
DARKROOM SHOW CYAN SPOTS ON PHOTO.

### ISSUE THREAD

**Issue by Anden-art** [darktable-org/darktable#17658]
### Describe the bug

In lightroom all photos look as they should. In the darkroom, however, the photos are filled with a lot of cyn spots. Even older photos that I already edited without any issues at the time of editing.
I did one uninstall and reinstall. It did not help.
I am using Windows 10 on a Lenovo T15 laptop and this problem suddenly appeared without me changing any settings whatsoever.
![Picture error](https://github.com/user-attachments/assets/7e28fcf4-f115-4ee1-af03-8ff2444a17a9)

### Steps to reproduce

1. Lightroom
2. Dbl click photo.
3. - .
4. Error shows up.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Describe your system?

I have 2 external monitors connected. Same issue on all 3 screens.
I tried disconnecting all external monitors. 
The problem remained on the laptop screen.

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Can you reproduce with another darktable version(s)?  / NO.
Can you reproduce with a RAW or Jpeg or both? / RAW-file-format.
Are the steps above reproducible with a fresh edit (i.e. after discarding history)? / YES.
If the issue is with the output image, attach an XMP file if (you'll have to change the extension to .txt) / NOT applicable.
Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? /NO
Do you use lua scripts? / NO

**Comment by wpferguson** [comment]
You have gamut checking turned on (bottom right underneath main window in darkroom view).

**Comment by Anden-art** [comment]
> You have gamut checking turned on (bottom right underneath main window in darkroom view).

Oh so!!   Problem solved!!! 1000 000 THX! :)
