### ISSUE TITLE
"Overwrite if Changed" should also write if export file does not exist

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#17655]
**Is your feature request related to a problem? Please describe.**

If export's "overwrite if changed" option is selected and an image has been exported before, then deleted off disk, trying to export the image again does not work. Since the image has not changed, no export file is generated despite it not being present on disk.

However, if the user removed the export file, the user very likely intended for it to be re-exported as is. 

**Describe the solution you'd like**

The behavior of the option should be re-interpreted to be "overwrite if changed or if export file does not exist".

**Alternatives**

And another option with this behavior.

**Comment by zisoft** [comment]
This is already fixed in master by #17188
