### ISSUE TITLE
White Balance with pipette via Color Calibration results in Pink

### ISSUE THREAD

**Issue by danyo2008** [darktable-org/darktable#17675]
### Describe the bug

I'm using a Sony A74 and develop my RAW files with darktable. 
I am using the latest Version 4.8.1 of Darktable.

What I have noticed is, that every time i try to change the white balance via the color calibration module, the picture end with a pinkish tint. 

So, i am not able to do an automatic white balance via the pipette within darktable. I have to do all manually.
 
<img width="1174" alt="white_balance_color_calibration_pink" src="https://github.com/user-attachments/assets/11d609b2-4b99-4a31-9b38-e88f6ddbf3f0">

### Steps to reproduce

1. Open the image in darktable edit mode
2. Open the module "Color Calibration"
3. Select "CAT16" if not already default
4. Select the Pipette
5. Select a neutral grey or white area within the picture

The Result is, that the image gets a pinkish look

### Expected behavior

Darktable should adjust the white balance as expectet from the selectet area

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Win 11 Pro

### Describe your system?

Ryzen 7, 32GB RAM, Nvidia GTX 1070TI

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia GTX 1080TI, Nvidia 560.94

**Comment by MStraeten** [comment]
did you check the setting in ‚Farbtransfer‘ it seems there’s something not neutral…

**Comment by danyo2008** [comment]
> did you check the setting in ‚Farbtransfer‘ it seems there’s something not neutral…

Hi, have checked it. I don't now what the wrong setting was, but i have switched some settings, and then set it back and now it worked as expected.... Strange....

Thanks for the hint, 
Dan
