### ISSUE TITLE
4.8.1 Release - Retouch module applies with transparency even if transparency slider is all the way to opaque

### ISSUE THREAD

**Issue by wcampbell0x2a** [darktable-org/darktable#17687]
### Describe the bug

Since I've gotten the new update whenever I use the retouch module, it applies with a transparency even if I have the transparency slider set all the way to 100% opaque. I'm finding it does this with all types of masks and brushes available in that module

### Steps to reproduce

1. Open retouch module and create any type of mask.
2. Try to move the mask around - it will not apply without transparency regardless of settings.

### Expected behavior

Allow you to apply the retouch module without transparency

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

None

**Comment by jenshannoschwalm** [comment]
Can't reproduce so far on current master ...

**Comment by wcampbell0x2a** [comment]
> Can't reproduce so far on current master ...

I could test on master, but I doubt I could switch back to a stable release?

**Comment by jenshannoschwalm** [comment]
There are database changes so you'd have to make sure a full backup and revert that after testing.

**Comment by pehar1** [comment]
Also cannot reproduce with master. Did you check, after you selected a shape, if the opacity is at 100 % (CTRL-scroll, not the blend mask opacity slider of the module) ? You can also look into `darktablerc` and you should find

`plugins/darkroom/masks/opacity=1`

If your value is different, you can edit it to 1 (daktable may not run during editing, otherwise the application will overwrite your change).

**Comment by jenshannoschwalm** [comment]
@pehar1 thanks for reminding me about that.

**Comment by piratenpanda** [comment]
Is the opacity also set to 100% in the mask manager?

**Comment by wcampbell0x2a** [comment]
I was able to fix it, I was looking at the wrong slider. It looks like the default slider in the newer version was 42% opacity instead of totally opaque.
