### ISSUE TITLE
Denoise profiles for EOS R8

### ISSUE THREAD

**Issue by svenakela** [darktable-org/darktable#17694]
For noise profiles, please also attach the entire archive with `.pdf` plots.

Source photos are created according to the [Pixls guideline](https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/). Profiles are verified with DT 4.8.1 and looks good.

[darktable-noiseprofile-20241020.tar.gz](https://github.com/user-attachments/files/17447861/darktable-noiseprofile-20241020.tar.gz)

**Comment by donyagithub** [comment]
Hi,
I would like to point out that this is probably not the right place for my request, and I apologize.
I have been trying for weeks to generate the noise profile for a Canon G1 X, but without success (I don't have much experience with the terminal). I would have taken the images following the instructions on [Pixls](https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/). I would kindly ask if someone can process them. In any case, thank you.

**Comment by svenakela** [comment]
> Hi, I would like to point out that this is probably not the right place for my request, and I apologize. I have been trying for weeks to generate the noise profile for a Canon G1 X, but without success (I don't have much experience with the terminal). 

Add your request in the [following **thread](https://discuss.pixls.us/t/contribute-to-denoise-profiles/46123/17)** and I can help you with that.

**Comment by donyagithub** [comment]
ok I'll do it. Thanks again for your availability

**Comment by mvimercati** [comment]
Am I wrong or the R8 shares the same sensor and processor of R8 Mk2?

**Comment by svenakela** [comment]
> Am I wrong or the R8 shares the same sensor and processor of R8 Mk2?

There is no R8 Mk 2. There is an R6 Mk 2.
R8 and R6Mk2 share the same sensor but images out are not exactly the same, R6Mk2 has been rated with a slightly higher dynamic range. Also, the R6Mk2 allows both lower and higher ISO.
The denoise profiles are close but no cigar, so to say.

**Comment by mvimercati** [comment]
> > Am I wrong or the R8 shares the same sensor and processor of R8 Mk2?
> 
> There is no R8 Mk 2. There is an R6 Mk 2. R8 and R6Mk2 share the same sensor but images out are not exactly the same, R6Mk2 has been rated with a slightly higher dynamic range. Also, the R6Mk2 allows both lower and higher ISO. The denoise profiles are close but no cigar, so to say.

Yes I was referring to R8, just a typo. Ok, good to know.

**Comment by svenakela** [comment]
> AFAIK the profile is not merged yet, do you really want to close the issue? @svenakela 

No please should be open! My bad.

**Comment by svenakela** [comment]
> > R8 and R6Mk2 share the same sensor but images out are not exactly the same, R6Mk2 has been rated with a slightly higher dynamic range. Also, the R6Mk2 allows both lower and higher ISO.
> > The denoise profiles are close but no cigar, so to say.
> 
> Hm, Bill's measurements kind of say they should be identical, and ISO range is the same as well...
> 
> https://www.photonstophotos.net/Charts/PDR.htm#Canon%20EOS%20R6%20Mark%20II,Canon%20EOS%20R8 https://www.photonstophotos.net/Charts/PDR_Shadow.htm#Canon%20EOS%20R6%20Mark%20II,Canon%20EOS%20R8 https://www.photonstophotos.net/Charts/RN_ADU.htm#Canon%20EOS%20R6%20Mark%20II_14,Canon%20EOS%20R8_14 https://www.photonstophotos.net/Charts/RN_e.htm#Canon%20EOS%20R6%20Mark%20II_14,Canon%20EOS%20R8_14

I don't own an R6Mk2 . I own R8s. I can only rely on other's tests and ratings. 
I had to check and it seems the latest firmware really do have the same ISO-range on both cameras. They do have the same sensor and I _think_ they have the same processor. On the other hand, one has IBIS one has not. In any case your links are pretty obvious in that sense that they are very similar. I compared the R6Mk2 and R8 denoise profiles and they are very close but again, not exactly the same. Seems to be a close call.

**Comment by svenakela** [comment]
To anyone who stumble across this thread before 5.0 is released and would like to get the denoise working with an R8, the `noiseprofiles.json` you need with the camera included [can be found here](https://discuss.pixls.us/uploads/short-url/fkdk7eTVsqMz7ArGASnNbzag1lT.zip).
