### ISSUE TITLE
Lua translation not 100% possible

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#17699]
@wpferguson : See the attached screen shot:

![image](https://github.com/user-attachments/assets/7e5b459a-38c1-4c5c-9736-4bc9574df0f8)

- The combo with **official**, **contrib**... are not translatable
- The "page 1 of 2", **page %d of %d** is not translatable
- The name of the script are not translatable would it be possible to have a displayed name /= than the actual script. The first one apply_camera_style should be displayed in French as "Appliquer les styles de boîter" for example.
- We may keep in the tooltip the script name, and in this case instead of name as title we should use "script"
- In the tooltip **name** (should probably be script, see above), **purpose**, **author**, **help** are not translatable

**Comment by victoryforce** [comment]
I will add, in the module created by the enfuse script, the module name and widget labels are not translatable.

**Comment by wpferguson** [comment]
> The "page 1 of 2", page %d of %d is not translatable

Fixed, the translation wrapped string.format - reversed it

> The combo with official, contrib... are not translatable

Those values are the folder names that are populated on startup as script_manager reads the script directory structure.  official, contrib, examples, and tools could probably be translated and other folders that users have added are probably already localized.  I'll have to think about it, but if you have any ideas...

My roadmap for script_manager was to let users create their own categories and assign scripts to them, but I'm not close to that yet.

> The name of the script are not translatable

We could translate the name in the metadata and use that for the display while still using the filename to start and stop it.

I need to play with how I use the metadata to get the translations to work.  Right now I just parse it out as strings for the files that aren't running but it looks like I need to parse it out as code to take advantage of the translations.  Give me a day or so....
