### ISSUE TITLE
Darktable won't launch anymore after system crash

### ISSUE THREAD

**Issue by Rugith-1** [darktable-org/darktable#17726]
### Describe the bug

I was processing and exporting images using darktable and as I was exporting a JPEG my computer crashed.

Darktable itself is not the cause of the crash, as I have had a couple crashes here and there recently without using darktable.

But after rebooting, darktable simply doesn't launch anymore. I have tried uninstalling and reinstalling, and it still refuses to launch.

I have updated my graphics drivers (AMD) and nothing has changed.  I have also tried installing a nightly version of darktable, but it still does not launch.

### Steps to reproduce

1 Double click darktable.exe

2 Darktable does not launch

### Expected behavior

Darktable should launch

### Logfile | Screenshot | Screencast

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0635 [dt_get_sysresource_level] switched to 2 as `large'
     0.0649   total mem:       16305MB
     0.0657   mipmap cache:    2038MB
     0.0664   available mem:   11146MB
     0.0672   singlebuff:      254MB
     0.0701 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded, preference 'default path'
     0.2531 [opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'gfx1010:xnack-'
   CONF KEY:                 cldevice_v5_amdacceleratedparallelprocessinggfx1010xnack
   PLATFORM, VENDOR & ID:    AMD Accelerated Parallel Processing, Advanced Micro Devices, Inc., ID=4098
   CANONICAL NAME:           amdacceleratedparallelprocessinggfx1010xnack
   DRIVER VERSION:           3628.0 (PAL,LC)
   DEVICE VERSION:           OpenCL 2.0 AMD-APP (3628.0)
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          8176 MB
   MAX MEM ALLOC:            6732 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1 / 4.9.0 (nightly)

### What OS are you using?

Windows

### What is the version of your OS?

WIndows 10

### Describe your system?

Ryzen 7 5700X3d
Rx 5700 xt
16 gigs of ram
Windows 10

### Are you using OpenCL GPU in darktable?

No

**Comment by pehar1** [comment]
Reinstalling darktable does not touch your local configuration files and databases. A crash as described may have damaged your database for example. A first attempt would be to rename your .config folder and see if darktable is starting up correctly with default configuration and a new (empty) database. If this is the case, the damaged file in .config has to be located in the next step.

**Comment by Rugith-1** [comment]
Renaming the database did fix it, it launches just fine now. What do i need to do now?

**Comment by pehar1** [comment]
Depending on your settings you should have several backups (snapshots) of your data.db and library.db. Rename the damaged database to something like data.old resp. library.old and rename the snapshot you want to use to data.db resp. library.db.

**Comment by Rugith-1** [comment]
I have done as you said, but now there is another issue; when I go to launch darktable it prompts me to upgrade the database.

When I click on upgrade it, the window closes and nothing seems to be happening. There is a warning that it may take a while, but I don't see darktable present in the task manager once I click upgrade.

**Comment by pehar1** [comment]
This might indicate the snapshot you used is also damaged. You should have several snapshots, try another one. If this also fails start darktable from the command line with debug option -d common to create a log and post (attach) this file here.

**Comment by Rugith-1** [comment]
Trying a different snapshot didn't work. Here is what log.txt says :

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     5.6609 [init] can't create table overlay
     5.6610 [init]   attempt to write a readonly database
     5.6610 [init] database `library.db' couldn't be upgraded from version 47 to 53. aborting
     5.6615 ERROR : cannot open database

**Comment by victoryforce** [comment]
> 5.6610 [init]   attempt to write a readonly database

As you can see, the database files have a read-only attribute. Change it in the properties.

**Comment by Rugith-1** [comment]
Alright, everything seems to be working great now !

Thank you very much to the both of you !
