### ISSUE TITLE
Closing the 'About darktable' box after clicking a link within box crashes darktable

### ISSUE THREAD

**Issue by pejax** [darktable-org/darktable#17723]
### Describe the bug

Closing the 'About darktable' box after clicking a link (http/mailto) crashes darktable. Closing the 'About darktable' box without clicking on any link works.

I re-tested after [#17692](https://github.com/darktable-org/darktable/issues/17692) has been fixed.

### Steps to reproduce

Click 'About darktable'
Click a link (http/mailto)
Close 'About darktable' using either window->x or the close button
darktable crashes

### Expected behavior

darktable should close the 'About box'

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.9.0+925~gb7288e18b2

### What OS are you using?

Mac

### What is the version of your OS?

MacOS Sequoia 15.0.1

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1

**Comment by zisoft** [comment]
This is another bug in GTK which cannot be resolved in darktable.
The about dialog in darktable is just a standard GTK about dialog without anything special.

So please consider to open an issue report upstream.
