### ISSUE TITLE
clock on splash screen in windows 10

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#17730]
### Describe the bug

The cute clock on the splash screen doesn't look like the clock in Windows 10.

### Steps to reproduce

Start darktable in Windows 10.

### Logfile | Screenshot | Screencast

![dt splash clock](https://github.com/user-attachments/assets/2ecca47a-5192-4940-8b76-d57d7e6a8c51)

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+925~gb7288e18b2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600

**Comment by esq4** [comment]
U+23f2 is in the Times New Roman

**Comment by zisoft** [comment]
BTW: The splash screen uses the Font DejaVu Serif which is not installed on all systems (at least not on macOS).

**Comment by esq4** [comment]
I found **(saw)** it only in Segoe UI Symbol and Segoe UI Light on Windows.

**Comment by ralfbrown** [comment]
@esq4 Can you try adding the following to the CSS tweaks box on the General tab in global preferences?
```
#splashscreen-remaining { font-family: sans-serif, "Segoe UI Light", "Arial Unicode MS"; }
```
(and if that doesn't work, use Segoe UI Symbol instead of Light).

**Comment by esq4** [comment]
@ralfbrown I tried them both. In my opinion, this is not a good solution: it is difficult to predict the effect on all OS versions other than Linux.
I tried to do it with gif. The result is in the video.

https://github.com/user-attachments/assets/25f41b09-b754-4b79-bd4c-1b44ae70a450

**Comment by ralfbrown** [comment]
I'm afraid I won't have time to revise the code to deal with an image rather than just plain text before the December release....  Someone else is welcome to propose a PR.

**Comment by esq4** [comment]
@ralfbrown What do you think about https://github.com/darktable-org/darktable/pull/17749?
