### ISSUE TITLE
(Still) existing rounding error in image export after crop

### ISSUE THREAD

**Issue by Noxdor** [darktable-org/darktable#17746]
### Describe the bug

I am trying to crop camera images from a Sony Alpha to 16:9 and then export them as 1920x1080. When I export, I am constantly getting 1920x1079 images. I saw that this issue was already mentioned in #3757 and supposedly fixed, but I am on 4.8.1 and still running into this issue.

### Steps to reproduce

1. Open up Darktable and crop an image to 16:9 
![image](https://github.com/user-attachments/assets/b9dbb7d0-82cd-485d-b52f-8699c6382cf5)

2. Export it with size set to 1920x1080
![image](https://github.com/user-attachments/assets/6f66b05c-6450-42a5-ba75-5482ab60e272)

3. Inspect the exported image 
![image](https://github.com/user-attachments/assets/9b104590-ac6d-47c8-a90b-a44ea1b29900)

### Expected behavior

darktable should export an image in the format 1920x1080

### Logfile | Screenshot | Screencast

    22,4596 [avif_open] failed to parse `/run/media/<redacted>/DSC09352.ARW': BMFF parsing failed
    22,4598 [rawspeed_open] extensions list to ignore: `cr3'
    22,5578 [dt_dev_read_history_ext] temporary history deleted
    22,5578 [dt_iop_reload_defaults] defaults reloaded for filmicrgb
    22,5579 [dt_iop_reload_defaults] defaults reloaded for basecurve
    22,5579 [dt_iop_reload_defaults] defaults reloaded for colorequal
    22,5579 [dt_iop_reload_defaults] defaults reloaded for colormapping
    22,5579 [dt_iop_reload_defaults] defaults reloaded for channelmixerrgb
    22,5588 [dt_iop_reload_defaults] defaults reloaded for colorin
    22,5588 [dt_iop_reload_defaults] defaults reloaded for crop
    22,5588 [dt_iop_reload_defaults] defaults reloaded for exposure
    22,5589 [dt_iop_reload_defaults] defaults reloaded for retouch
    22,5589 [dt_iop_reload_defaults] defaults reloaded for clipping
    22,5589 [dt_iop_reload_defaults] defaults reloaded for overlay
    22,5589 [dt_iop_reload_defaults] defaults reloaded for flip
    22,5589 [dt_iop_reload_defaults] defaults reloaded for ashift
    22,5589 [dt_iop_reload_defaults] defaults reloaded for cacorrectrgb
    22,5598 [dt_iop_reload_defaults] defaults reloaded for lens
    22,5598 [dt_iop_reload_defaults] defaults reloaded for rotatepixels
    22,5602 [dt_iop_reload_defaults] defaults reloaded for denoiseprofile
    22,5602 [dt_iop_reload_defaults] defaults reloaded for demosaic
    22,5602 [dt_iop_reload_defaults] defaults reloaded for rawdenoise
    22,5602 [dt_iop_reload_defaults] defaults reloaded for hotpixels
    22,5602 [dt_iop_reload_defaults] defaults reloaded for cacorrect
    22,5602 [dt_iop_reload_defaults] defaults reloaded for highlights
    22,5602 [dt_iop_reload_defaults] scene=YES, modern=YES, CAT=NO. D65 2,739 1,000 1,369, AS-SHOT 2,574 1,000 1,523
    22,5602 [dt_iop_reload_defaults] defaults reloaded for temperature
    22,5602 [dt_iop_reload_defaults] defaults reloaded for invert
    22,5602 [dt_iop_reload_defaults] defaults reloaded for rawprepare
    22,5660 [dt_dev_read_history_ext] temporary history initialised with default params and presets
    22,5661 [dt_dev_read_history_ext] temporary history merged with image history
    22,5661 [history] successfully loaded module rawprepare from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
    22,5661 [history] successfully loaded module demosaic from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
    22,5661 [history] successfully loaded module colorin from history
			blendop v. 13:	version ok	params ok
			params v. 7:	version ok	params ok
    22,5662 [history] successfully loaded module colorout from history
			blendop v. 13:	version ok	params ok
			params v. 5:	version ok	params ok
    22,5662 [history] successfully loaded module gamma from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
    22,5662 [history] successfully loaded module temperature from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
    22,5662 [history] successfully loaded module highlights from history
			blendop v. 13:	version ok	params ok
			params v. 4:	version ok	params ok
    22,5662 [history] successfully loaded module channelmixerrgb from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
    22,5662 [history] successfully loaded module exposure from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    22,5662 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    22,5662 [history] successfully loaded module flip from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
    22,5662 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    22,5662 [history] successfully loaded module bilat from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
    22,5662 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    22,5662 [history] successfully loaded module bilat from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
    22,5663 [history] successfully loaded module bilat from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
    22,5663 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    22,5663 [history] successfully loaded module filmicrgb from history
			blendop v. 13:	version ok	params ok
			params v. 6:	version ok	params ok
    22,5663 [history] successfully loaded module bilat from history
			blendop v. 13:	version ok	params ok
			params v. 3:	version ok	params ok
    22,5664 [history] successfully loaded module monochrome from history
			blendop v. 13:	version ok	params ok
			params v. 2:	version ok	params ok
    22,5664 [history] successfully loaded module crop from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
    22,5664 [history] successfully loaded module crop from history
			blendop v. 13:	version ok	params ok
			params v. 1:	version ok	params ok
    22,5743 synch all module defaults     [export]
    22,6244 synch all module history      [export]
    22,6244 dt_dev_pixelpipe_synch        [export]         rawprepare             enabled  order= 1, piece hash=ed68fbe2d10c71ad,
    22,6244 dt_dev_pixelpipe_synch        [export]         demosaic               enabled  order= 8, piece hash=b0702bc252a94bd2,
    22,6245 dt_dev_pixelpipe_synch        [export]         colorin                enabled  order=32, piece hash=7563a39ceae1e96a,
    22,6354 dt_dev_pixelpipe_synch        [export]         colorout               enabled  order=84, piece hash=8e5a0f73242a7524,
    22,6354 dt_dev_pixelpipe_synch        [export]         gamma                  enabled  order=92, piece hash=1ae2f37bb34a05,
    22,6354 dt_dev_pixelpipe_synch        [export]         temperature            enabled  order= 3, piece hash=4678d94e1d9157f9,
    22,6354 dt_dev_pixelpipe_synch        [export]         highlights             enabled  order= 4, piece hash=26abe6488bb0049c,
    22,6354 dt_dev_pixelpipe_synch        [export]         channelmixerrgb        enabled  order=33, piece hash=5b61c20bd73215b,
    22,6354 dt_dev_pixelpipe_synch        [export]         exposure               enabled  order=24, piece hash=ee4f97460e9b04c9,
    22,6354 dt_dev_pixelpipe_synch        [export]         filmicrgb              enabled  order=58, piece hash=7485aacf18589f28,
    22,6354 dt_dev_pixelpipe_synch        [export]         flip                   disabled order=17, piece hash=0,
    22,6355 dt_dev_pixelpipe_synch        [export]         filmicrgb              enabled  order=58, piece hash=7485aacf18589f28,
    22,6355 dt_dev_pixelpipe_synch        [export]         bilat                  enabled  order=68, piece hash=87180639253870b1,
    22,6355 dt_dev_pixelpipe_synch        [export]         filmicrgb              enabled  order=58, piece hash=7485aacf18589f28,
    22,6355 dt_dev_pixelpipe_synch        [export]         bilat                  enabled  order=68, piece hash=87180639253870b1,
    22,6355 dt_dev_pixelpipe_synch        [export]         bilat.1                enabled  order=69, piece hash=4b2071bd6843ccc1,
    22,6355 dt_dev_pixelpipe_synch        [export]         filmicrgb              enabled  order=58, piece hash=7485aacf18589f28,
    22,6355 dt_dev_pixelpipe_synch        [export]         filmicrgb.1            disabled order=59, piece hash=0,
    22,6355 dt_dev_pixelpipe_synch        [export]         bilat.1                enabled  order=69, piece hash=4b2071bd6843ccc1,
    22,6355 dt_dev_pixelpipe_synch        [export]         monochrome             disabled order=78, piece hash=0,
    22,6355 dt_dev_pixelpipe_synch        [export]         crop                   enabled  order=28, piece hash=9352c353f96aa005,
    22,6355 dt_dev_pixelpipe_synch        [export]         crop                   enabled  order=28, piece hash=9352c353f96aa005,
    22,6355 synch all modules done        [export]                                defaults 0,0501s, history 0,0111s
    22,6355 [dt_imageio_export_with_flags]  modules: rawprepare temperature highlights demosaic exposure crop colorin channelmixerrgb filmicrgb bilat bilat.1 colorout finalscale gamma
    22,6355 modify roi OUT                [export]         rawprepare             (   0/   0) 8000x5320 scale=1,0000 --> (   0/   0) 7980x5320 scale=1,0000 ID=4807
    22,6355 modify roi OUT                [export]         crop                   (   0/   0) 7980x5320 scale=1,0000 --> (   0/ 803) 7958x4476 scale=1,0000 ID=4807
    22,6356 [dt_imageio_export] export imgid 4807, 7958x4476 --> 1920x1079 (scale=0,2413, maxscale=1,0000). upscale=no, hq=no
    22,6356 pipe starting             CL0 [export]                                (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413 ID=4807, nvidiacudaquadrot1000
    22,6356 [dt_opencl_check_tuning] use 2131MB (headroom=OFF, pinning=OFF) on device `NVIDIA CUDA Quadro T1000' id=0
    22,6356 modify roi IN                 [export]         crop                   (   0/   0) 1920x1079 scale=0,2413 --> (   0/ 193) 1920x1079 scale=0,2413 ID=4807
    22,6357 modify roi IN                 [export]         demosaic               (   0/ 193) 1920x1079 scale=0,2413 --> (   0/ 798) 7958x4472 scale=1,0000 ID=4807
    22,6357 modify roi IN                 [export]         highlights             (   0/ 798) 7958x4472 scale=1,0000 --> (   0/   0) 7980x5320 scale=1,0000 ID=4807
    22,6357 modify roi IN                 [export]         rawprepare             (   0/   0) 7980x5320 scale=1,0000 --> (   0/   0) 8000x5320 scale=1,0000 ID=4807
    22,6357 pipe data: full               [export]                                (   0/   0) 8000x5320 scale=1,0000 --> (   0/   0) 8000x5320 scale=1,0000
    22,6649 process                   CL0 [export]         rawprepare             (   0/   0) 8000x5320 scale=1,0000 --> (   0/   0) 7980x5320 scale=1,0000   1 IOP_CS_RAW
    22,6708 process                   CL0 [export]         temperature            (   0/   0) 7980x5320 scale=1,0000 --> (   0/   0) 7980x5320 scale=1,0000   3 IOP_CS_RAW
    22,6778 process                   CL0 [export]         highlights             (   0/   0) 7980x5320 scale=1,0000 --> (   0/ 798) 7958x4472 scale=1,0000   4 IOP_CS_RAW
    22,6933 opposed chroma            CL0 [export]         highlights             (   0/   0) 7980x5320 scale=1,0000 --> (   0/ 798) 7958x4472 scale=1,0000 red: 0,0000, green: 0,0000, blue: 0,0000 for hash=33f8be160a29023c
    22,7293 process tiled             CL0 [export]         demosaic               (   0/ 798) 7958x4472 scale=1,0000 --> (   0/ 193) 1920x1079 scale=0,2413   8 IOP_CS_RAW -> IOP_CS_RGB
    22,7930 clip_and_zoom_roi         CL0 [export]         demosaic               (   0/ 798) 4016x4472 scale=1,0000 --> (   0/ 193)  969x1079 scale=0,2413
    22,9000 clip_and_zoom_roi         CL0 [export]         demosaic               (3974/ 798) 3983x4472 scale=1,0000 --> ( 959/ 193)  961x1079 scale=0,2413
    22,9410 process                   CL0 [export]         exposure               (   0/ 193) 1920x1079 scale=0,2413 --> (   0/ 193) 1920x1079 scale=0,2413  24 IOP_CS_RGB
    22,9424 process                   CL0 [export]         crop                   (   0/ 193) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  28 IOP_CS_RGB
    22,9439 process                   CL0 [export]         colorin                (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  32 IOP_CS_RGB -> IOP_CS_LAB
    22,9439 matrix conversion         CL0 [export]         colorin                (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413 `standard color matrix', corrected by: 1,064 1,000 0,898
    22,9465 transform colorspace      CL0 [export]         channelmixerrgb        (   0/   0) 1920x1079 scale=0,2413 IOP_CS_LAB -> IOP_CS_RGB `linear Rec2020 RGB'
    22,9522 process                   CL0 [export]         channelmixerrgb        (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  33 IOP_CS_RGB
    22,9540 process                   CL0 [export]         filmicrgb              (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  58 IOP_CS_RGB
    22,9580 transform colorspace      CL0 [export]         bilat                  (   0/   0) 1920x1079 scale=0,2413 IOP_CS_RGB -> IOP_CS_LAB `linear Rec2020 RGB'
    22,9606 process                   CL0 [export]         bilat                  (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  68 IOP_CS_LAB
    22,9784 process                   CL0 [export]         bilat.1                (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  69 IOP_CS_LAB
    22,9930 blend with form           CL0 [export]         bilat.1                (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413 IOP_CS_LAB, BLEND_CS_LAB, form available and rendered
    22,9984 process                   CL0 [export]         colorout               (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  84 IOP_CS_LAB -> IOP_CS_RGB
    23,0069 process                   CPU [export]         gamma                  (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413  92 IOP_CS_RGB
    23,0128 cache report                  [export]                                2 lines (important=0, used=0, invalid=0). Using 1299MB, limit=0MB. Hits/run=0,00. Hits/test=0,000
    23,0128 pipe finished             CL0 [export]                                (   0/   0) 1920x1079 scale=0,2413 --> (   0/   0) 1920x1079 scale=0,2413 ID=4807

    23,3133 [export_job] exported to `/home/<redacted>/img_0001_06.png'

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Garuda Linux (Arch based)

### Describe your system?

# System Details Report
---

## Report details
- **Date generated:**                              2024-10-29 20:28:45

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad P1 Gen 2
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-9750H × 12
- **Graphics:**                                    Intel® UHD Graphics 630 (CFL GT2)
- **Disk Capacity:**                               512.1 GB

## Software Information:
- **Firmware Version:**                            N2OET65W (1.52 )
- **OS Name:**                                     Garuda Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.11.4-zen1-1-zen

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by Hpbirkeland** [comment]
Yes, this is still annoying, and it is not only for 16:9. I often export as 2048 on the long side, and they usually come out as 2047. And twice a year when I submit images to a national contest, the images have to be exactly 2400 on the long side. Mine almost never are, so I have to export full size and take the extra step via Gimp for resizing.

**Comment by jenshannoschwalm** [comment]
From my testing on master this has been fixed for 5.0 so closing the issue.

**Comment by Noxdor** [comment]
@jenshannoschwalm Thank you for your feedback, do you have an ETA for 5.0?

**Comment by Noxdor** [comment]
@TurboGit coolest software release dates ever :D Thanks, looking forward to it!
