### ISSUE TITLE
darktable-generate-cache

### ISSUE THREAD

**Issue by sss123next** [darktable-org/darktable#17753]
### Describe the bug

using `darktable-generate-cache` often leading to corrupted thumbnail and  empty image metadata (just blind guess, but looks like insufficient memory)
![2024-10-31_22-02_screenshot](https://github.com/user-attachments/assets/a96038ed-aab7-4ea9-b256-e7e5840fdafd)

nothing suspicious in `darktable-generate-cache` log

### Steps to reproduce

1. add set of images into library (100+ imgs)
2. close darktable ui
3. run `darktable-generate-cache` and wait till it finished
4. open darktable ui and look at added images

### Expected behavior

added images should have correct thumbnails and metadata

### Commit

7a75c3d9ed34c9672e261e0990a6d1819f01a5a9

### Where did you obtain darktable from?

self compiled

### darktable version

7a75c3d9ed34c9672e261e0990a6d1819f01a5a9

### What OS are you using?

Linux

### What is the version of your OS?

nixos unstable

### Describe your system?

x11 awesome wm
16core + 128gb ram  + intel a380 gpu

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

intel arc a380 6gb + intel-compute-runtime + intel-media-driver on top of current mesa release

**Comment by wpferguson** [comment]
Disable opencl and try it again.  I'm not sure how good the intel opencl drivers are.

**Comment by sss123next** [comment]
understood, will do with next photoset.

**Comment by sss123next** [comment]
tested with opencl turned off, still happening, so not related to opencl

**Comment by sss123next** [comment]
interesting, after turning off and turning on opencl, problem disappeared ...

**Comment by jenshannoschwalm** [comment]
Closing as not reprocible. Feel free to reopen.
