### ISSUE TITLE
Link error when trying to build darktable Windows MSYS2 / UCRT64 environment

### ISSUE THREAD

**Issue by dtrtuser** [darktable-org/darktable#17770]
### Describe the bug

Getting an error when trying to build from master on Windows (latest MSYS2 / UCRT 64 environment). I have been able to build with no problem for the last year.

Here is the error message:

`[403/945] Linking C shared library bin\libdarktable.dll
FAILED: bin/libdarktable.dll bin/libdarktable.dll.a
C:\windows\system32\cmd.exe /C "cd . && C:\msys64\ucrt64\bin\cc.exe -O3 -Wall -Wno-format -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wmaybe-uninitialized -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -fopenmp -O3 -DNDEBUG  -Wl,--enable-runtime-pseudo-reloc -shared -o bin\libdarktable.dll -Wl,--out-implib,bin\libdarktable.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\lib_darktable.rsp && C:\windows\system32\cmd.exe /C "cd /D C:\msys64\home\msika\darktable\build\bin && C:\msys64\ucrt64\bin\cmake.exe -E make_directory .debug && objcopy --only-keep-debug C:/msys64/home/msika/darktable/build/bin/libdarktable.dll C:/msys64/home/msika/darktable/build/bin/libdarktable.dll.dbg && objcopy --strip-debug C:/msys64/home/msika/darktable/build/bin/libdarktable.dll && objcopy --add-gnu-debuglink=libdarktable.dll.dbg C:/msys64/home/msika/darktable/build/bin/libdarktable.dll""
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin/liblib_darktable_imageio_rawspeed.a(imageio_rawspeed.cc.obj):imageio_rawspeed.cc:(.text$_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv]+0x0): multiple definition of `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()'; C:/msys64/ucrt64/lib/libheif.dll.a(libheif_dll_d002335.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
[420/945] Building C object lib/darktable/plugins/lighttable/CMakeFiles/navigation.dir/navigation.c.obj
ninja: build stopped: subcommand failed.
`

### Steps to reproduce

`cd ~/darktable/
git reset --hard
git fetch -p
git merge
git submodule update --init --recursive
rm -rf build
mkdir build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/darktable -DCUSTOM_CFLAGS=ON -DCMAKE_CXX_FLAGS="-O3" -DCMAKE_C_FLAGS="-O3" -DBINARY_PACKAGE_BUILD=OFF ../.
cmake --build . --target package
`

### Expected behavior

Expecting to be able to build darktable

### Logfile | Screenshot | Screencast

`[403/945] Linking C shared library bin\libdarktable.dll
FAILED: bin/libdarktable.dll bin/libdarktable.dll.a
C:\windows\system32\cmd.exe /C "cd . && C:\msys64\ucrt64\bin\cc.exe -O3 -Wall -Wno-format -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wmaybe-uninitialized -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -fopenmp -O3 -DNDEBUG  -Wl,--enable-runtime-pseudo-reloc -shared -o bin\libdarktable.dll -Wl,--out-implib,bin\libdarktable.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\lib_darktable.rsp && C:\windows\system32\cmd.exe /C "cd /D C:\msys64\home\msika\darktable\build\bin && C:\msys64\ucrt64\bin\cmake.exe -E make_directory .debug && objcopy --only-keep-debug C:/msys64/home/msika/darktable/build/bin/libdarktable.dll C:/msys64/home/msika/darktable/build/bin/libdarktable.dll.dbg && objcopy --strip-debug C:/msys64/home/msika/darktable/build/bin/libdarktable.dll && objcopy --add-gnu-debuglink=libdarktable.dll.dbg C:/msys64/home/msika/darktable/build/bin/libdarktable.dll""
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin/liblib_darktable_imageio_rawspeed.a(imageio_rawspeed.cc.obj):imageio_rawspeed.cc:(.text$_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv[_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv]+0x0): multiple definition of `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()'; C:/msys64/ucrt64/lib/libheif.dll.a(libheif_dll_d002335.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
[420/945] Building C object lib/darktable/plugins/lighttable/CMakeFiles/navigation.dir/navigation.c.obj
ninja: build stopped: subcommand failed.
`

### Commit

Latest master as of 11/03/2024

### Where did you obtain darktable from?

self compiled

### darktable version

Version string: 4.9.0+765~g8f3f81da8e

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

Windows 11 Pro Version	23H2 OS build	22631.4317
Processor	AMD Ryzen 7 5700G with Radeon Graphics            3.80 GHz
Installed RAM	32.0 GB (31.9 GB usable)
GPU NVIDIA GeForce RTX 3050

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 3050

**Comment by wpferguson** [comment]
Reproduced on Win10 with updated build environment (11/3) and master (11/3).  It has something to do with imageio_rawspeed...

**Comment by Scorpion078** [comment]
I also get the same error message

Win 11
Intel i5
64GB
RTX 3060

**Comment by wpferguson** [comment]
It's the libheif package.  Downgrade it to 1.18.2-3.

**Comment by dtrtuser** [comment]
Thank you @wpferguson !

uninstalled libheif 1.19 and installed 1.18.2-3 and was able to build.

**Comment by farindk** [comment]
This is different than https://github.com/strukturag/libheif/issues/1365 because this is no libheif symbol, but from the `std::string` class. That should not be in the libheif interface at all because that is C only. At least if you compile it with the cmake variable `WITH_REDUCED_VISIBILITY=ON`. Do you compile libheif with that flag?

If that flag is off, I could imagine that the std::string symbol gets into the library and then there may be a C++17 / C++20 mismatch.

If that doesn't help, could you bisect the libheif commit to see where it comes from?

**Comment by farindk** [comment]
> It's ON by default, no?

It depends on the cmake preset used. But since darktable doesn't seem to use a preset when building libheif, it should be on.
It then sets `CMAKE_CXX_VISIBILITY_PRESET: hidden` which in turn should set the compiler option `-fvisibility=hidden`.

But I'm not sure if that has any effect on the linked C++ standard library.

This is where we switched to C++20: [aab4c9f87](https://github.com/strukturag/libheif/commit/aab4c9f879e9055ac28ada33decddf8361edbef3), maybe try whether the issue was introduced by this.

**Comment by farindk** [comment]
libheif has this code in `heif.h`:
````C++
#if defined(_MSC_VER) && !defined(LIBHEIF_STATIC_BUILD)
...
#define LIBHEIF_API __declspec(dllexport)
````

Could it be that we need a different `#if defined()` for msys2?

**Comment by farindk** [comment]
@fancycode : in the following commit, you replaced `_WIN32` with `_MSC_VER`. Do you remember why? We might have to change it back to make it work with non-Microsoft compilers on Windows.
https://github.com/strukturag/libde265/commit/92f74e5187a4890a2e8269223a3cb3e359dfc514#diff-5b01fde5650da0cdf1ba2a352e966404e21926a882384f96ed9df3f93dcc1e30L34

(That code was later copy-pasted into libheif.)

**Comment by fancycode** [comment]
> @fancycode : in the following commit, you replaced `_WIN32` with `_MSC_VER`. Do you remember why? We might have to change it back to make it work with non-Microsoft compilers on Windows. [strukturag/libde265@92f74e5#diff-5b01fde5650da0cdf1ba2a352e966404e21926a882384f96ed9df3f93dcc1e30L34](https://github.com/strukturag/libde265/commit/92f74e5187a4890a2e8269223a3cb3e359dfc514#diff-5b01fde5650da0cdf1ba2a352e966404e21926a882384f96ed9df3f93dcc1e30L34)
> 
> (That code was later copy-pasted into libheif.)

Well, that commit almost 11 years ago, so I can't remembed why I enabled it for MSVC only :laughing: Maybe we didn't support MinGW or others yet at that time or there were problems with them? 

Anyway, as I haven't done any Windows development in ages, I would say feel free to change back to `_WIN32` if `_MSC_VER` doesn't work.

**Comment by farindk** [comment]
The gcc manual page that @kmilos linked above uses this
````
#if defined _WIN32 || defined __CYGWIN__
````
Is the CYGWIN part necessary?

**Comment by farindk** [comment]
> > Is the CYGWIN part necessary?
> It looks like it - I just checked the cygheif-1.dll 

I mean: isn't cygwin automatically covered by the `_WIN32` ?

**Comment by wpferguson** [comment]
@kmilos works for me :smile:, thanks

**Comment by farindk** [comment]
Thanks for testing. I'll prepare a v1.19.2 soon.

**Comment by dtrtuser** [comment]
Sorry for the late reply: all working fine now with the latest 1.19.1.2
