### ISSUE TITLE
Crash in idle darkroom due to dtgtk_cairo_paint_intersection()

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#17808]
### Describe the bug

I had an image opened, but was not editing it, I was just comparing the contents with that of another window. I was dragging the other window over the screen when darktable crashed.

### Steps to reproduce

I had a raw image open in the darkroom. Later I found the crash is reproducible even if a simple JPG is open in the darkroom.

I was dragging an image viewer window, partially covering darktable. The darkroom in darktable was zoomed to 100%, but I later found that was not a requirement. Screen resolution is 4K. The crash is reproducible within seconds on my machine. The window I was dragging over darktable was a Java app, but I can reproduce the problem with e.g. dragging KDE's text editor, `kate`, over darktable.

### Expected behavior

dt should not crash

### Logfile | Screenshot | Screencast

[dt-crash.txt](https://github.com/user-attachments/files/17690536/dt-crash.txt)

### Where did you obtain darktable from?

self compiled

### darktable version

4.9.0+1048~g0739a92dea

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04

### Describe your system?

NVidia 1060/6GB
Ryzen 5 5600X, 64 GB
nvidia-driver-550                                        550.120-0ubuntu0.24.04.1   

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6GB 550.120-0ubuntu0.24.04.1

**Comment by pehar1** [comment]
Can't reproduce on my system (three HD monitors side by side, desktop 5760 x 1080 px), darktable takes one monitor (1920x1080).

Tried with LXImage-Qt (image viewer), PCManFM-Qt (filemanager), FeatherPad (texteditor), LibreOffice, Firefox, Database Manager (self written Java application), Eclipse (IDE)

darktable 4.9.0+1065-g633fea155a                                                                               
OS : Linux 6.8.0-48-generic / Ubuntu 24.04.1 LTS                                                               
Memory : MemTotal:       65759336 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 550.120
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu3
Desktop : LXQt
GTK+ : 3.24.41
Glib : ldd (Ubuntu GLIBC 2.39-0ubuntu8.3) 2.39
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
CMAKE_BUILD_TYPE : release

**Comment by kofa73** [comment]
Here: reproducible with/without OpenCL, and even if darktable's window is quite small, dragging `xterm` over it.
![image](https://github.com/user-attachments/assets/35b6740d-f699-4255-a0a1-9c04606bfcad)

**Comment by pehar1** [comment]
Tried again with multiple windows overlaying darktable, moving windows around, bringing them to background / foreground, changing sizes ... no crash.

X session or wayland session ?

Only a wild guess : I remember a strange problem (not a crash) reported here related to the window manager used (#15948). Maybe it would be worth trying a different window manager ? I use openbox.

**Comment by kofa73** [comment]
I use Xorg with KDE.

**Comment by kofa73** [comment]
I've tried with openbox, and that crashed, too. NB: openbox behaved very strange on my system, dragging or closing a window never repainted the background, leaving the last drawn window visible. Nevertheless, the crash is the same (the window I dragged this time was whatever terminal openbox gave me).

**Comment by parafin** [comment]
This looks like video drivers or Xorg problem. Check what relevant packages you’ve updated recently and try to roll them back to an old version.

**Comment by kofa73** [comment]
> This looks like video drivers or Xorg problem. Check what relevant packages you’ve updated recently and try to roll them back to an old version.

The darktable 4.8.1 AppImage does not crash.

**Comment by jenshannoschwalm** [comment]
Is it related to the filmstrip being shown?

**Comment by kofa73** [comment]
Not related to filmstrip, also occurred with it turned off.

Bisect failed, as sometimes I was not patient enough (the crash would sometimes occur in seconds, sometimes only after a longer time, and I probably did not wiggle the mouse long enough). I'm restarting it.

**Comment by kofa73** [comment]
OK, I was on the wrong track, it has something to do with the stack stored in the DB. Does not occur with a clean DB, which makes bisecting harder, because I normally use a temp DB for bisecting, especially given that some versions cannot even read the latest DB. However, I always import the same images, and they have XMP files next to them.

That's it for today, I'm tired.

**Comment by ralfbrown** [comment]
Crash while idling in darkroom view says "sidecar autosave" or "background thumbnailer" to me.  Does the crash happen with those two features disabled?

**Comment by parafin** [comment]
IMHO it's more likely to be about darktablerc settings, which affect how darkroom looks, than database.

**Comment by kofa73** [comment]
Yes, but I've already tested with a config dir containing my darktablerc. Nevertheless, I'll test again -- sometime.

**Comment by jenshannoschwalm** [comment]
At least the thumbnailer reports activity via the logs so you get noticed ...

**Comment by ralfbrown** [comment]
My thought was that the autosave or thumbnailer (especially the latter) are doing something which causes a problem when the GUI thread responds to a window manager event at the same time....

**Comment by jenshannoschwalm** [comment]
Forgot to mention, backthumbs tests for current view and is just idling while in view is darkroom...

**Comment by kofa73** [comment]
OK, here is a `-d all -d verbose` log:
- I started darktable
- Opened an image in the darkroom
- Waited a few seconds for things to settle (I think the last log entry from that is at the 6.8987 mark)
- Started moving a window over the darkroom (from 10.0599)

There are lots of `dt_view_paint_surface` entries (I assume redrawing the screen), as well as quite a few like
`14.7273 expose module                 [full]           demosaic                800  2752x1812, px=3193 py=108`
No other processing messages, though.
[crashlog.zip](https://github.com/user-attachments/files/17708111/crashlog.zip)

**Comment by kofa73** [comment]
I've moved darktablerc out of the way. Darktable created a new one, then crashed before the GUI would show. Trying to restart darktable results in the same crash. That probably warrants a separate bug report, but I'll add the file here, in case not, please check.
[crash-with-fresh-darktablerc.zip](https://github.com/user-attachments/files/17708129/crash-with-fresh-darktablerc.zip)

**Comment by jenshannoschwalm** [comment]
The log `might` hint to a control job not working correctly.

There is one more way - as mentioned before elsewhere - to make dt crash immediately. 
Start it from the console and click on the close button as soon as possible and the chance for a crash happening in `dt_control_shutdown` is very high. @ralfbrown any idea? Until the splash-thing we had everything running up before using `darktable.gui` - now it's at least partly initialized and we might try to use control on the ui before it's completely safe?

**Comment by ralfbrown** [comment]
We could indeed need some guards to avoid dereferencing null pointers or the like.  It looks like either darktable.control or darktable.mipmap_cache may have been uninitialized.

@kofa73 From your latest backtrace, it looks like darktable was starting up with the lighttable in culling mode.  Does the crash happen if you are in some other mode at the time the previous run exits? (it didn't for me with startup in either fixed or dynamic culling modes)

**Comment by kofa73** [comment]
@ralfbrown 

> @kofa73 From your latest backtrace, it looks like darktable was starting up with the lighttable in culling mode. Does the crash happen if you are in some other mode at the time the previous run exits?

There was no previous run -- that crash occurred after I moved my `dartablerc` out of the way. I can later try what happens if I leave it in place, switch to the culling mode (which I never use), and try to start darktable. But then it seems it'll really need a separate bug report.

**Comment by jenshannoschwalm** [comment]
@kofa73 still happening to you ?

**Comment by kofa73** [comment]
I'll try to 'bisect' my darktablerc (halving the contents), to see if I can track it down to a problematic setting.

**Comment by kofa73** [comment]
Interestingly, even though the crash happens while the darkroom is displayed, it seems to depend on the state of the lighttable -- what collection filters are applied and/or whether I'm in _folder_ or _film roll_ view. Digging further.

**Comment by jenshannoschwalm** [comment]
What is folder mode?

**Comment by kofa73** [comment]
![image](https://github.com/user-attachments/assets/31b2f03d-625d-4149-8632-4be3c3ddce66)

**Comment by jenshannoschwalm** [comment]
Any deep tree directories involved?

**Comment by jenshannoschwalm** [comment]
you mean absolutely no issues with film mode ?

**Comment by kofa73** [comment]
> you mean absolutely no issues with film mode ?

Now it failed in 'film mode' as well. It would be weird for it to make a difference, since all this time, I'm in the darkroom. In my current config, the background thumbs generation is actually disabled.
What was strange, though, is that the system was under high load, with no visible activity in the darkroom. I waited until that stopped, then started dragging the window (KDE's terminal, `konsole` over darktable), and then it crashed. I'm attaching the latest log, just in case.
[darktable_bt_66UOX2.txt](https://github.com/user-attachments/files/17907497/darktable_bt_66UOX2.txt)

I'm quite close to giving up on this, I just cannot find a pattern. But the crashes, if I were editing, could be painful.

**Comment by jenshannoschwalm** [comment]
In collect.c `_lib_connect_gui update` we might not define a button->icon (lines 2615) if there was no proper mode. Could you try to add an `else` at the end ?

**Comment by kofa73** [comment]
You mean here?
```c
      if(mode == DT_LIB_COLLECT_MODE_AND)
        button->icon = dtgtk_cairo_paint_intersection;
      else if(mode == DT_LIB_COLLECT_MODE_OR)
        button->icon = dtgtk_cairo_paint_union;
      else if(mode == DT_LIB_COLLECT_MODE_AND_NOT)
        button->icon = dtgtk_cairo_paint_andnot;
      else
        printf("@@@ kofa\n");
```

The crash is reproduced, the debug string is never printed.

**Comment by kofa73** [comment]
The darktable stack frame that calls into libcairo:
![image](https://github.com/user-attachments/assets/0497419a-ace7-4eb5-bd49-3b65a8f5bb68)

**Comment by jenshannoschwalm** [comment]
Hmm. I checked some of your logs and it seems to always happen there in Cairo code. The snippet does not look critical to me though, the data being null should not be the issue.

Have you tried not-using the icon in question or using another one? Or just commenting the fill? 

A libcairo problem? Your version? 

@dterrahe any idea on this?

**Comment by dterrahe** [comment]
The logs consistently shows a crash in XRenderFindDisplay. So either there's an issue with any of the libraries in the stack (gtk/cairo/xrender/xorg) or the video driver or the video configuration. This issue can be triggered by the fill/group cairo instructions in the recent icon changes (hence why self compiled 4.8.1 with the same libraries might be fine) but it does seem something with your system if nobody else can reproduce.

**Comment by kofa73** [comment]
@jenshannoschwalm : I have no idea which icon it is.

What I do:
- leave darktable in the darkroom
- grab any window by the titlebar, and move it over the darktable window. Sometimes it crashes almost immediately (that's how I discovered the issue), sometimes I have to keep moving the window at high speeds for half a minute. I don't use any darktable icon; I assume simply the redrawing of the screen triggers the issue. I'm on KDE, if that counts; I don't use any fancy compositor settings or such, I try to keep my desktop experience rather plain.

I'll try to upgrade to Ubuntu 24.10 (currently, I'm on 24.04), and will let you know. However, I may not do that for a while.

**Comment by zisoft** [comment]
> `button->icon = dtgtk_cairo_paint_intersection;` :-)

That was introduced by me with #17720 and indeed the intersection icon is somewhat complicated by using groups and `airo_paint_with_alpha()`

**Comment by kofa73** [comment]
@jenshannoschwalm : correct. Based on your tip:
- I'll hide the top section in the darkroom, the crash does not occur.
- The crash also occurs in the lighttable, which also has this icon.
- If I disable the color label filter (and thus hide the _intersection_ icon), the crash does not occur.

**Comment by jenshannoschwalm** [comment]
Good to hear.

**Comment by jenshannoschwalm** [comment]
> The logs consistently shows a crash in XRenderFindDisplay.

Could that be related to using `CAIRO_OPERATOR_IN` being unbounded?

**Comment by jenshannoschwalm** [comment]
@kofa73 maybe a fresh test after #17901 ?

**Comment by kofa73** [comment]
Unfortunately, I still got a crash (the one I'm attaching is from the lighttable, which also has the icon, but the darkroom also crashed when I tried).
[darktable_bt_8NO7X2.txt](https://github.com/user-attachments/files/17963135/darktable_bt_8NO7X2.txt)

**Comment by jenshannoschwalm** [comment]
No idea now, works fine here on wayland or X11. Very annoying.

**Comment by zisoft** [comment]
Or try to simplify the icon to test.
This icon uses two nested groups, try to remove the inner group and see if that still crashes.
And it uses `cairo_paint_with_alpha()`, maybe a driver problem on your system?

**Comment by kofa73** [comment]
Downgraded to nvidia-driver-535 (535.183.01-0ubuntu0.24.04.1), still crashes.

**Comment by kofa73** [comment]
> Any CSS modifications?

Yes, but disabling them did not help:
```css
@define-color bg_color #7F7F7F;
@define-color fg_color #eee;
@define-color base_color #444;

@define-color text_color #eee;
@define-color selected_bg_color #666;
@define-color selected_fg_color #eee;

@define-color tooltip_bg_color #666;

@define-color tooltip_fg_color #111;
@define-color really_dark_bg_color #595959;


@define-color darkroom_bg_color #777777;
@define-color darkroom_preview_bg_color shade(@darkroom_bg_color, .8);
@define-color lighttable_bg_color @darkroom_bg_color;
@define-color lighttable_preview_bg_color shade(@lighttable_bg_color, .8);
```

**Comment by kofa73** [comment]
Replacing the body of dtgtk_cairo_paint_intersection with the following eliminates the crash.

 I've tried adding an error check after each call, but that did not print anything at all:
```c
void dtgtk_cairo_paint_intersection(cairo_t *cr, gint x, gint y, gint w, gint h, gint flags, void *data)
{
  PREAMBLE(1, 1, 0, 0)

  double r, g, b, alpha;
  if(cairo_pattern_get_rgba(cairo_get_source(cr), &r, &g, &b, &alpha) != CAIRO_STATUS_SUCCESS) {
    printf("@@@@ 0, %d\n", cairo_status(cr));
    goto final;
  }

  cairo_set_source_rgba(cr, r, g, b, 1.0);
  if (cairo_status(cr) != CAIRO_STATUS_SUCCESS) {
      printf("@@@@ 1, %d\n", cairo_status(cr));
      goto final;
  }

  // and so on
```

**Comment by jenshannoschwalm** [comment]
@kofa73 could you tell your libcairo version?

**Comment by kofa73** [comment]
libcairo2 (1.18.0-3build1) 
I've now started an upgrade to Ubuntu 24.10, where it will be 1.18.2-2. I'll report back.

Meanwhile, I've also tested if display scaling had an effect, but it does not (was set to 150%, tried with 100%, but the crash remained).

**Comment by kofa73** [comment]
Crashes just the same. :-(
```text
ii  libcairo-gobject-perl                                    1.005-4build3                                        amd64        integrate Cairo into the Glib type system in Perl
ii  libcairo-gobject2:amd64                                  1.18.2-2                                             amd64        Cairo 2D vector graphics library (GObject library)
ii  libcairo-gobject2:i386                                   1.18.2-2                                             i386         Cairo 2D vector graphics library (GObject library)
ii  libcairo-perl                                            1.109-5                                              amd64        Perl interface to the Cairo graphics library
ii  libcairo-script-interpreter2:amd64                       1.18.2-2                                             amd64        Cairo 2D vector graphics library (script interpreter)
ii  libcairo2:amd64                                          1.18.2-2                                             amd64        Cairo 2D vector graphics library
ii  libcairo2:i386                                           1.18.2-2                                             i386         Cairo 2D vector graphics library
ii  libcairo2-dev:amd64                                      1.18.2-2                                             amd64        Development files for the Cairo 2D graphics library
ii  libcairomm-1.0-1v5:amd64                                 1.14.5-2                                             amd64        C++ wrappers for Cairo (shared libraries)
ii  libcairomm-1.16-1:amd64                                  1.18.0-1build1                                       amd64        C++ wrappers for Cairo (shared libraries)
```

**Comment by zisoft** [comment]
can you try without the nested group in the icon?
Just remove the inner group.

**Comment by zisoft** [comment]
And the next test:
Replace the final `cairo_paint_with_alpha(cr, alpha);` by `cairo_paint(cr);`

**Comment by kofa73** [comment]
> Just remove the inner group.

@zisoft : I know nix about GTK and Cairo.
Which lines make up the inner group?

I've tried this, but then things like the darktable logo are also lost:
```c
void dtgtk_cairo_paint_intersection(cairo_t *cr, gint x, gint y, gint w, gint h, gint flags, void *data)
{
  PREAMBLE(1, 1, 0, 0)

  double r, g, b, alpha;
  if(cairo_pattern_get_rgba(cairo_get_source(cr), &r, &g, &b, &alpha) != CAIRO_STATUS_SUCCESS)
    goto final;

  cairo_set_source_rgba(cr, r, g, b, 1.0);

  const double radius = 0.3;

  // we draw the outline of the 2 circles
  cairo_push_group(cr);
  cairo_arc(cr, radius, 0.5, radius, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_arc(cr, radius * 2.4, 0.5, radius, 0, 2.0 * M_PI);
  cairo_stroke(cr);

  /*
  // we draw the intersection of the 2 circles
  cairo_push_group(cr);
  cairo_arc(cr, radius, 0.5, radius * 1.2, 0, 2.0 * M_PI);
  cairo_fill(cr);
  cairo_set_operator(cr, CAIRO_OPERATOR_IN);
  cairo_arc(cr, radius * 2.4, 0.5, radius * 1.2, 0, 2.0 * M_PI);
  cairo_fill(cr);
  cairo_pop_group_to_source(cr);
  cairo_paint(cr);
  cairo_pop_group_to_source(cr);
  */
  cairo_paint(cr);
final:
  FINISH
}
```


I've tried replacing the cairo_paint_with_alpha, but that did not help. I think we already saw that it does not get to that line. See https://github.com/darktable-org/darktable/issues/17808#issuecomment-2499008232

That line is now 2192, not 2193. Commenting it out avoids the crash:
```c
  cairo_push_group(cr);
  cairo_arc(cr, radius, 0.5, radius * 1.2, 0, 2.0 * M_PI);
  cairo_fill(cr);
  cairo_set_operator(cr, CAIRO_OPERATOR_IN);
  cairo_arc(cr, radius * 2.4, 0.5, radius * 1.2, 0, 2.0 * M_PI);
//  cairo_fill(cr);
  cairo_pop_group_to_source(cr);
  cairo_paint(cr);
  cairo_pop_group_to_source(cr);
  cairo_paint_with_alpha(cr, alpha);
```
The icon looks like this:
![image](https://github.com/user-attachments/assets/91c677b3-ce17-4cf3-bdb8-0193fd2a3a33)

**Comment by kofa73** [comment]
@zisoft Playing with an LLM (yeah, sorry), I got this -- but it paints the exact opposite, filling in everything but the intersection:
![image](https://github.com/user-attachments/assets/0685600b-6d5b-42d4-aab3-3982156b2bcb)

 Maybe it gives you an idea. It does avoid the crash.
```c
     // Set color (RGB)
     cairo_set_source_rgb(cr, r, g, b);

     // Draw first circle
     cairo_arc(cr, radius, 0.5, radius, 0, 2.0 * M_PI);
     cairo_stroke_preserve(cr);

     // Draw second circle
     cairo_new_sub_path(cr);
     cairo_arc(cr, radius * 2.4, 0.5, radius, 0, 2.0 * M_PI);
     cairo_stroke_preserve(cr);

     // Fill intersection
     cairo_set_fill_rule(cr, CAIRO_FILL_RULE_EVEN_ODD);
     cairo_fill(cr);
```

**Comment by kofa73** [comment]
I've managed to cobble this together:
```c
  double r, g, b, alpha;

  const double radius = 0.3;

  cairo_save(cr);

  if(cairo_pattern_get_rgba(cairo_get_source(cr), &r, &g, &b, &alpha) != CAIRO_STATUS_SUCCESS) {
    goto final;
  }

     // Set color (RGB)
     cairo_set_source_rgb(cr, r, g, b);

  // Draw and paint the circles
  cairo_arc(cr, radius, 0.5, radius, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_arc(cr, radius * 2.4, 0.5, radius, 0, 2.0 * M_PI);
  cairo_stroke(cr);

  // Re-draw them, restrict fill to 1st circle
  cairo_arc(cr, radius, 0.5, radius, 0, 2.0 * M_PI);
  cairo_clip(cr);
  cairo_arc(cr, radius * 2.4, 0.5, radius, 0, 2.0 * M_PI);
  // fill the intersection
  cairo_fill(cr);

  cairo_restore(cr);
```
![image](https://github.com/user-attachments/assets/f3118c49-5bf7-4510-adfe-ff34705020eb)

The result does not crash.

**Comment by zisoft** [comment]
Would be interesting to see if what happens if you take the code from `dtgtk_cairo_paint_masks_intersection()` which is constructed in a similar way.

**Comment by kofa73** [comment]
I'd rather hand it back to you. As I said, I don't really know what I'm doing here. For example, this one (I tried to copy the mask intersection code) just crashes darktable when it tries to open the main window:
```c
  double red, green, blue, alpha;

  cairo_save(cr);

  if(cairo_pattern_get_rgba(cairo_get_source(cr), &red, &green, &blue, &alpha) != CAIRO_STATUS_SUCCESS) {
    goto final;
  }
     cairo_set_source_rgb(cr, red, green, blue);

  // we want 2 round of radius R that intersect in the middle,
  // so the width needs R + R*0.8 + R*0.8 + R = R*3.6
  // with a safety belt of *0.95 to be sure the stroke is draw inside the area
  const double r = fmin(w / 3.6, h / 2.0) * 0.95;
  const double padding_left = (w - r * 3.6) / 2.0;

  // we draw the outline of the 2 circles
  cairo_save(cr);
  cairo_set_line_width(cr, cairo_get_line_width(cr) * 0.5);
  cairo_arc(cr, padding_left + r, h / 2.0, r, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_arc(cr, padding_left + r * 2.6, h / 2.0, r, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_restore(cr);

  // we draw the intersection of the 2 circles we slightly different radius so they are more visible
  cairo_push_group(cr);
  cairo_arc(cr, padding_left + r * 1.3, h / 2.0, r * 0.85, 0, 2.0 * M_PI);
  cairo_fill(cr);
  cairo_set_operator(cr, CAIRO_OPERATOR_IN);
  cairo_arc(cr, padding_left + r * 2.3, h / 2.0, r * 0.85, 0, 2.0 * M_PI);
  cairo_fill(cr);
  cairo_pop_group_to_source(cr);
  cairo_paint(cr);

  cairo_restore(cr);
```

**Comment by zisoft** [comment]
The problem is that nobody else has reported these kind of crashes and I cannot reproduce.

Your code looks much simpler, great solution! My thinking here is that it might be better to also replace the code for the mask intersection icon as well to avoid crashes when this icon is displayed.

**Comment by kofa73** [comment]
OK, I'm on it.

**Comment by kofa73** [comment]
So, I've updated the way the mask intersection icon is drawn, but there is a difference in the result. Only the part below `// we draw the intersection of the 2 circles we slightly different radius so they are more visible` was updated:
```c
void dtgtk_cairo_paint_masks_intersection(cairo_t *cr, gint x, gint y, gint w, gint h, gint flags, void *data)
{
  // note : as the icon is not square, we don't want PREAMBLE macro
  // we want 2 round of radius R that intersect in the middle,
  // so the width needs R + R*0.8 + R*0.8 + R = R*3.6
  // with a safety belt of *0.95 to be sure the stroke is draw inside the area
  const double r = fmin(w / 3.6, h / 2.0) * 0.95;
  const double padding_left = (w - r * 3.6) / 2.0;

  // we draw the outline of the 2 circles
  cairo_save(cr);
  cairo_set_line_width(cr, cairo_get_line_width(cr) * 0.5);
  cairo_arc(cr, padding_left + r, h / 2.0, r, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_arc(cr, padding_left + r * 2.6, h / 2.0, r, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_restore(cr);

  // we draw the intersection of the 2 circles we slightly different radius so they are more visible
  cairo_arc(cr, padding_left + r * 1.3, h / 2.0, r * 0.85, 0, 2.0 * M_PI);
  cairo_clip(cr);
  cairo_arc(cr, padding_left + r * 2.3, h / 2.0, r * 0.85, 0, 2.0 * M_PI);
  cairo_fill(cr);
}
```

The original icon (on my screen) has grey values of 147. The new one produces pixels of 181.
Original:
![image](https://github.com/user-attachments/assets/86b2a8fa-29eb-4028-968e-0302fc4f7402)

Any idea, why that is?
New:
![image](https://github.com/user-attachments/assets/b6697ddf-e4d7-4132-9cc3-be8f839a4156)

**Comment by jenshannoschwalm** [comment]
I think the new icon is even better.
 :-)

**Comment by zisoft** [comment]
This is the reason why I first set the alpha to 1.0, then draw the whole thing and paint it with the original alpha.

**Comment by kofa73** [comment]
I also think the brighter intersection area 'highlights' (no pun intended) that it's the intersection we're talking about.

**Comment by kofa73** [comment]
It is possible to save a drawing operation by using `stroke_preserve` on the 2nd circle, and the re-draw the 1st one only. This is how the icons look then:
![image](https://github.com/user-attachments/assets/48767147-5284-4ab5-9269-3b8deaf6f833)
![image](https://github.com/user-attachments/assets/a9978e5b-6d72-4683-97d5-87ba59103597)

![image](https://github.com/user-attachments/assets/83f09ad2-86eb-4f39-8147-804f523ec3fc)
![image](https://github.com/user-attachments/assets/ee302b8a-d31d-48d2-8a47-56cb471968fc)

```c
  // we draw the outline of the 2 circles
  cairo_arc(cr, radius, 0.5, radius, 0, 2.0 * M_PI);
  cairo_stroke(cr);
  cairo_arc(cr, radius * 2.4, 0.5, radius, 0, 2.0 * M_PI);
  cairo_stroke_preserve(cr);

  // we limit drawing to the area of the 2nd circle
  cairo_clip(cr);

  // we redraw the 1st circle
  cairo_arc(cr, radius, 0.5, radius, 0, 2.0 * M_PI);
  // and fill - clipping to the area of the 2nd circle means the intersection only
  cairo_fill(cr);
```
(and similarly for the other function)

Would you like me to add this to the PR?

**Comment by zisoft** [comment]
In the color label icon the circles are more close together so the overlapping intersection area is better visible.

**Comment by kofa73** [comment]
> In the color label icon the circles are more close together so the overlapping intersection area is better visible.

OK, how about this? And should I also nudge the union's circles closer together, for consistency?
![image](https://github.com/user-attachments/assets/c2b5e80f-ee5d-4c11-933f-8e4d03efb0a8)

I've tried to do that (turning 3.6 into 3.4, 2.6 into 2.4, 1.3 into 1.2 etc):
![image](https://github.com/user-attachments/assets/61ebde9d-4463-4c0a-8fda-5226b49a96eb)
