### ISSUE TITLE
When converting dng file to jpeg file, jpeg file is generated with color discrepancy

### ISSUE THREAD

**Issue by mohanrajams** [darktable-org/darktable#17825]
### Describe the bug

The dng file has embedded adobe xmp, when we try to convert to jpeg the color is not applied properly (white balance I guess)

I am not able to attach dng file , however I have attached extracted xmp file

I want to know
1. Whether the xmp from adob is supported by darktable
2. If not supported is there a way to convert adobe xmp to darktable xmp (are there any tools available?)

### Steps to reproduce

1. Extract xmp file using exiftool (`exiftool -xmp -b sample_file_to_investigate.dng > sample_file_to_investigate.xmp`)
2. use the extracted xmp file with darktable-cli ( `darktable-cli sample_file_to_investigate.dng sample_file_to_investigate.xmp sample_file_to_investigate_newdarktable.jpeg`)

[sample_file_to_investigate_xmp.txt](https://github.com/user-attachments/files/17711689/sample_file_to_investigate_xmp.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

I am using it inside linux docker (base image is ubuntu latest)

### Describe your system?

I have attached the docker file here
[Dockerfile.txt](https://github.com/user-attachments/files/17711652/Dockerfile.txt)

### Are you using OpenCL GPU in darktable?

None

**Comment by pehar1** [comment]
Did you read https://darktable-org.github.io/dtdocs/en/overview/sidecar-files/sidecar-import/ ?
The related code is old and has not been maintained for some time. You should not expect much...

**Comment by Donatzsky** [comment]
I assume that the Adobe xmp comes from Lightroom. Darktable isn't compatible with Lightroom processing, so that will never work as you seem to think. And while there is some support for converting certain LR operations to the rough DT equivalent, that code is really old and broken, and I'm not sure it ever worked with `darktable-cli`.

**Comment by jenshannoschwalm** [comment]
Embedded metadata for dt must be "standard" exif tags supported by `exiv2` so (unfortunately for you) only those are read by dt and possibly processed.
