### ISSUE TITLE
My personal names for the color coding spots don't stick (are not saved)

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#17832]
### Describe the bug

The names disappear right away. Sometimes stick until another activity is introduced.

### Steps to reproduce

In Lightbox we can right-click on the colored spots in footer, and an input field opens where we can key-in our own hint for what the colors mean in our image-organization.
Almost immediately the added names disappear.

### Expected behavior

Darktable should save the added names (for five colors)

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.9.0+980~g8f3f81da8e

### What OS are you using?

Windows

### What is the version of your OS?

Microsoft Windows 11 Pro, version 10.022631

### Describe your system?

Sufficient

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon RX 6600

**Comment by pehar1** [comment]
Works correctly for me, typed text is saved between sessions, 4.9.0+1087~ge4f31fccb9, Ubuntu 24.04

**Comment by KIRSJ** [comment]
I may not have entered the input with Enter...!
Anyway, with 4.9.0+1115~g9a899036c7 it works here too.
Thank you, pehar1.
