### ISSUE TITLE
Color picker not sampling exact colour under crosshairs in Color Equalizer module

### ISSUE THREAD

**Issue by europlatus** [darktable-org/darktable#17851]
### Describe the bug

I'm not sure how the colour samples are calculated using the color picker in the Color Equalizer module, but it doesn't seem to be accurate to the crosshairs. Perhaps it is calculating an average of the whole circle, but it still seems to have an offset.

In this example of a RAW file at 100% zoom, the crosshairs are clearly over the yellow colour, and the majority of the circle is also over the yellow colour, but the sample colour is a dark grey.

![image](https://github.com/user-attachments/assets/b58422b2-2952-4c7f-968d-513f457eb439)

Should the sampled colour be directly under the crosshairs? This would be ideal.
If the current behaviour is as designed, could the weighting be adjusted to more accurately reflect the colour that the circle is mostly covering (e.g. yellow in the sample image above)?

### Steps to reproduce

- Open an image file.
- Enable Color Equalizer, then click on the colour picker.
- Sample a color near another colour and move the reticle around to see how the sample colour changes under the crosshairs

### Expected behavior

As there is already an "area select" mode for the colour picker, I think the crosshairs should be highly accurate for picking a hue. If this can't be done for some reason, the sample colour should more accurately reflect the colour that the crosshairs are hovering over.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

Yes

**Comment by jenshannoschwalm** [comment]
All pickers get the values from the (downscaled) preview pipe so there is some "locatation in-accuracy". The point-picker is not doing any area at all, it takes data from one "pixel".

**Comment by jenshannoschwalm** [comment]
> So is there any option to make it more accurate, like a toggle to not use the preview pipe if more accuracy is needed? 

Short answer is no with current codebase, the preview pipe is downscaled and pickers take data from that. Sorry.

**Comment by tpinfold** [comment]
I wonder if the color picker could be improved by adopting a method used in GIMP. In GIMP you can adjust the radius of the sample average. I would have thought sampling a single pixel could be problematic for getting a good color read as an individual pixel might be influenced by noise or even a speck of dirt on the surface being read whereas an average would be more accurate at picking the color of a patch we might be interested in.   
<img width="160" alt="image" src="https://github.com/user-attachments/assets/38087756-d77b-49af-9842-543770d23d66">

**Comment by jenshannoschwalm** [comment]
We have the area picker exactly for that right now :-)

**Comment by tpinfold** [comment]
Thank you for pointing out that already exists. This option was not obvious to me but now I now it exists that is great.

**Comment by jenshannoschwalm** [comment]
Closing this as not planned for the moment.
