### ISSUE TITLE
Fujifilm X-M5

### ISSUE THREAD

**Issue by poldo23** [darktable-org/darktable#17868]
Hi, since https://raw.pixls.us isn't working (is down) I write the request here

I am not able to attach .raf files to this post, so please find samples in this review gallery:

https://www.dpreview.com/sample-galleries/3219370504/fujifilm-x-m5-pre-production-sample-gallery/1046752801

or here https://www.dpreview.com/sample-galleries by searching for X-M5

if I can provide any additional files, data or anything please contact me at branislav.poldauf@gmail.com and let me know where to upload or send the files

thanks for your work

**Comment by Donatzsky** [comment]
You should provide sample files you have taken yourself, I believe.

**Comment by poldo23** [comment]
Thanks a lot for very fast response, will test for sure

where and how can I provide my samples they are kinda big for email ?
google drive link would be OK ?

is there something I have to do to grant a licence (or can I waive my
rights to IP by email?)

It is rainy and now snowy since I get the camera, so all my pictures are
kinda boring and dull but I would love to provide them if that helps you

I shot all of them lossless, do you need uncompressed too?

pls let me know how I can help

Branislav Poldauf


st 20. 11. 2024 o 18:51 Miloš Komarčević ***@***.***>
napísal(a):

**Comment by poldo23** [comment]
Hi a just tested development build 4.9.0+1162 for windows

I am still not able to open RAF files (unsuported camera model) - I tried on lossless and uncompressed files

but in imported JPEGs, the camera and lens are recognised in lens correction module (this wasn't working before)

**Comment by poldo23** [comment]
@kmilos thanks, I will try that (I am not very experienced in this)

google drive link for some (10) of my random .raf files (uploading right now):
https://drive.google.com/drive/folders/1-mprGjn5N02cI8iUheBf2NITotLaZhm0?usp=sharing 

will it help ? is it enough ? I claim no right to them, anyone is free to use them as they see fit - public domain

**Comment by poldo23** [comment]
I uploaded 4 new exaples per your request to the shared google drive folder - uncompressed, lossless, compressed, and sports finder (1,25 crop) in lossless
all with the same settings - F8, 1/160, iso 640, its meike 55mm lens 

BTW the manual merge works perfectly

Thank you so much for your help

**Comment by LebedevRI** [comment]
@poldo23 Hello. RPU is finally up. Please contribute the full sample set.
X-Ref https://github.com/darktable-org/rawspeed/issues/821

**Comment by poldo23** [comment]
> [@poldo23](https://github.com/poldo23) Hello. RPU is finally up. Please contribute the full sample set. X-Ref [darktable-org/rawspeed#821](https://github.com/darktable-org/rawspeed/issues/821)

Thanks for notice, I uploaded my samples

**Comment by LebedevRI** [comment]
@poldo23 thank you for contributing the samples!
