### ISSUE TITLE
Surface blur causing visual glitches in darkroom.

### ISSUE THREAD

**Issue by michelklaasen** [darktable-org/darktable#17870]
### Describe the bug

When turning surface blur on and zooming in far into the image, usually at about 400%, visual glitches start to appear. Things like blacked out areas, pixelation, color distortion. The higher the parameters of the module are set, the earlier the glitches appear.

### Steps to reproduce

1. Open image in darkroom
2. Turn on surface blur
3. Optional: set parameters to max values
4. Zoom in until 1600%

### Expected behavior

Not produce visual glitches when applying surface blur.

### Logfile | Screenshot | Screencast

Made a video about it:
https://youtu.be/3IdBJrZ-mt8

Screenshot:
![2024_11_20 19h32m33s PC](https://github.com/user-attachments/assets/bd9ad48c-252e-4b9e-8a54-320927588140)

### Commit

I don't know

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro 22H2 Build 22621.4317

### Describe your system?

Gigabyte Aorus Ultra Gaming x470
AMD Ryzen 9 5900X
32 GB RAM
AMD Radeon 6900XT

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon 6900XT 
Driver Version: 24.20.19.01-241011a-408380C-AMD-Software-Adrenalin-Edition 
AMD Windows Driver Version: 32.0.12019.1028 
16GB of memory

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Running script manager with only OpenInExplorer enabled, everything else off.

I only have and use RAW CR3 files from Canon R6 Mark II.

Disabled openCL & openCL drivers in processing settings to see what'd happen. It still glitches, but they look different, more hexagonal.

**Comment by jenshannoschwalm** [comment]
It's the guided filter going wild if there is not enough data, here due to being zoomed in. Not sure if there is a good fix.
