### ISSUE TITLE
fujifilm xt5 raw file fails to import

### ISSUE THREAD

**Issue by clwwufa** [darktable-org/darktable#17891]
### Describe the bug

Fujifilm xt5 raw file import fails
message raw file <name> could not load 
 `Fujifilm X-T5' color matrix not found for image

### Steps to reproduce

1 drag and drop raw file to lighttable
2 double click on file

### Expected behavior

import fujifilm raw files

### Logfile | Screenshot | Screencast

version: darktable 4.8.1
start: 2024:11:26 10:58:21

darktable 4.8.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

    51.7727 [avif_open] failed to parse `D:\geoff\photos\2024\Glasgow\Gartnavel\nov21\raw\XT504257.RAF': BMFF parsing failed
    51.7736 [rawspeed_open] extensions list to ignore: `cr3'
    51.7853 [rawspeed] (XT504257.RAF) rawspeed::FujiDecompressor::FujiDecompressor(rawspeed::RawImage, rawspeed::ByteStream), line 854: compressed RAF header check
    51.7854 [libraw_open] extensions whitelist: `cr3'
    51.7866 [qoi_open] no proper file header in D:\geoff\photos\2024\Glasgow\Gartnavel\nov21\raw\XT504257.RAF
    89.9672 [temperature] `Fujifilm X-T5' color matrix not found for image

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

windows 10 pro

### Describe your system?

Device name	Z230
Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz   3.60 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	972D2D17-3850-44BB-98D8-A1FE99B992A4
Product ID	00331-20020-00000-AA923
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA CUDA Quadro K600

**Comment by victoryforce** [comment]
@clwwufa Are your raws lossy compressed?

**Comment by clwwufa** [comment]
No. They are uncompressed.

**Comment by clwwufa** [comment]
My apologies. The file was lossy compressed. I wouldn't normally have chosen that but may have been misled by the fact that it is simply "compressed" in the fuji menu.
I have now successfully managed to import uncompressed and lossless compressed images.

**Comment by clwwufa** [comment]
And  misled by the fact that XnView MP, which I use, showed "Compression None" in the image properties.
