### ISSUE TITLE
Crop ignored for the right border

### ISSUE THREAD

**Issue by limbusdev** [darktable-org/darktable#17898]
### Describe the bug

When cropping an image the right border is wrong. Instead the area to the right is not croppped all the way. It looks like the original aspect ratio is applied again but in landscape mode instead of portait mode. Happens in portrait mode photos only.

### Steps to reproduce

1. open darkroom for the appended image
2. enable crop
3. set "original"
4. choose a smaller area
5. apply

### Expected behavior

darktable should crop the image on all sides

### Logfile | Screenshot | Screencast

[Bildschirmaufzeichnung vom 2024-11-27 20-41-43.webm](https://github.com/user-attachments/assets/b0dd9e88-331b-4b0b-891e-c35fd6f32c4d)

### Where did you obtain darktable from?

flatpak

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04

### Describe your system?

GNOME, Nvidia with X11, Used the flatpak 4.8.1 from flathub

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reproduce with

![2024-08-13 13 28 08 G](https://github.com/user-attachments/assets/5bac2a51-7a09-40dd-ace3-7e9a180f8c7b)

**Comment by jenshannoschwalm** [comment]
Fixed in master, will be available in dt 5.0 around christmas.

**Comment by juuzo** [comment]
I discovered that there's a workaround while waiting for dt 5.0:
1. Set the crop as you desire.
2. Change the aspect ratio on the crop tool to "Freehand".
3. Move the crop slightly by dragging it from the middle area (do not touch the edges as that will change the aspect ratio).
This is a bit clumsy when wanting to experiment with the size of the crop, but at least it gets me unstuck with cropping.
