### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [darktable-org/darktable#17900]
### Describe the bug

Following https://github.com/darktable-org/darktable/issues/15411 where we can not reply on it and ticket unsolved.
Note: I am not a bot.

Thanks in advance to solve this big problem.

--------------

Dear @darktable-org team, @boucman, @hean01, @houz, @hanatos, @prokoudine,

Sourceforge Darktable team members list:
- https://sourceforge.net/p/darktable/_members/

Steps:
- to remove the "Code" tab (Padlock -> Gear on Code tab -> "Delete everything") : https://sourceforge.net/p/darktable/code/
- to remove the old mailing list link on it: https://sourceforge.net/projects/darktable/support // Go here: https://sourceforge.net/p/darktable/admin/overview
- to update the official website with HTTPS for security // Go here: https://sourceforge.net/p/darktable/admin/overview
- to add the "move box" with link to GitHub: https://github.com/darktable-org/darktable // Go here: https://sourceforge.net/p/darktable/admin/overview
- to add Mastodon, Facebook and X/Twitter social networks // Go here: https://sourceforge.net/p/darktable/admin/overview

----------

To add a "move" box like https://sourceforge.net/projects/handbrake for example, go here: https://sourceforge.net/p/darktable/admin/overview
To disable/delete tabs, go here: https://sourceforge.net/projects/darktable/
To add a new tab, go here: https://sourceforge.net/projects/darktable/
To change informations, go here: https://sourceforge.net/p/darktable/admin/overview
To export, go here: https://sourceforge.net/p/darktable/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/darktable/admin/overview
- A new tab, go here: https://sourceforge.net/projects/darktable/

Thanks in advance.

### Steps to reproduce

Read before.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

master

### What OS are you using?

Linux

### What is the version of your OS?

*

### Are you using OpenCL GPU in darktable?

None

**Comment by Donatzsky** [comment]
As was said in the old issue, no one has admin access anymore, so this can't be done.

**Comment by Neustradamus** [comment]
@Donatzsky: You can see that there are team member in common (normally it is the same project), I have cited people in this ticket:
- https://sourceforge.net/p/darktable/_members/
- https://github.com/orgs/darktable-org/people

I am in contact with Sourceforge if there is a problem with "lost account" too.

**Comment by Neustradamus** [comment]
@Donatzsky: You can see that there are team member in common (normal, it is the same project), I have cited people in this ticket:
- https://sourceforge.net/p/darktable/_members/
- https://github.com/orgs/darktable-org/people

I am in contact with Sourceforge if there is a problem with "lost account" too.

**Comment by pehar1** [comment]
To the best of my knowledge : 
None of the people mentioned (team members list) are still actively involved in the development of darktable.
None of the currently active developers have an admin account for the former project at SourceForge.

**Comment by jenshannoschwalm** [comment]
As discussed and commented in the closed issue, we just don't care.

**Comment by Neustradamus** [comment]
Dear @darktable team,

I inform you that Sourceforge users do not know that Darktable 5.0.0 is out :/

**Comment by parafin** [comment]
> Sourceforge users

Best joke of the year:))

**Comment by Neustradamus** [comment]
@parafin: It is not null.
Good to inform people.
