### ISSUE TITLE
XMP not properly written or deleted

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#17918]
The scenario:

- Import an image
- Go to darkroom and activate a module (say RGB Curve)
- Go to lighttable, click on "discard history" and "remove" from darktable
- Import again image, go to darkroom and see that RGB Curve is activated

Two solutions to fix this, when we click on "discard history":
1. Write the XMP when "discard history" is clicked, simple but does not respect the XMP write setting
2. Or better, if create XMP files is "after edit" then we need to delete the XMP and if "on import" we want to write the XMP.

**Comment by jenshannoschwalm** [comment]
I am pretty sure it used to be solution (1) ...
