### ISSUE TITLE
Digicam converted DNG files crashes Darktable

### ISSUE THREAD

**Issue by phenrypereira** [darktable-org/darktable#17912]
### Describe the bug

When editing DNG images created by digiKam ARW conversion, Darktable crashes randomly while editing in darkroom.

### Steps to reproduce

1. Open Darktable;
2. Import a DNG images collection;
3. Go to darkroom mode
4. Edit some images.
5. See Dark table closes suddenly (w/o messages)

### Expected behavior

Darktable should not close. 

### Logfile | Screenshot | Screencast

[darktable_crash_dng.txt](https://github.com/user-attachments/files/17969387/darktable_crash_dng.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

KDE Neon 6.2.3

### Describe your system?

Operating System: KDE neon 6.2
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.8.0-49-generic (64-bit)
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 3200G with Radeon Vega Graphics
Memory: 13.6 GiB of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics
Manufacturer: BIOSTAR Group
Product Name: A320MH

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I haven't been able to try other versions yet to see if the problem is happening in those.

Previously, with other image formats, including the original RAW from my camera (Sony SLT-A57), I was editing normally.

The problem persists when editing an image by clearing the history, or with the automatic application pattern created by me for some modules.

The problem is not attributed to any specific image or module. I noticed the problem coming when trying to switch between images in the darkroom, and even when returning to the lighttable.

I'm starting Darktable with the Lua scripts: gimp, autogrouper and autosnapshot. I wasn't actively using any of them during the edits.

**Comment by jenshannoschwalm** [comment]
No chance to get into this without one of those files plus the sidecar xmp file. Also, some stability problems have been solved for the soon-coming 5.0
