### ISSUE TITLE
Cannot build darktable from git master.

### ISSUE THREAD

**Issue by john-k-h** [darktable-org/darktable#17934]
### Describe the bug

When running make install, I get a fatal error:
[ 98%] Built target darkroom
In file included from /bausite/git/darktable/build_dark/lib64/darktable/plugins/introspection_lens.cc:175:
/bausite/git/darktable/src/iop/lens.cc: In function ‘lfModifier* _get_modifier(int*, int, int, const dt_iop_lens_data_t*, int, gboolean)’:
/bausite/git/darktable/src/iop/lens.cc:993:46: error: no matching function for call to ‘lfModifier::lfModifier(lfLens* const&, const float&, const int&, const int&)’
  993 |   mod = new lfModifier(d->lens, d->crop, w, h);
      |                                              ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [lib64/darktable/plugins/CMakeFiles/lens.dir/build.make:85: lib64/darktable/plugins/CMakeFiles/lens.dir/introspection_lens.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8312: lib64/darktable/plugins/CMakeFiles/lens.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

### Steps to reproduce

I'm building darktable from git master.  The make install stops as noted above.

### Expected behavior

Darktable should build.

### Where did you obtain darktable from?

self compiled

### darktable version

I cannot give you the version as this is from git master just pulled tonight.

### What OS are you using?

Linux

### What is the version of your OS?

slackware-current

### Describe your system?

It's a linux box I put together from parts.  64 gb of ram, 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Card: VGA compatible controller: NVIDIA Corporation GA104 [GeForce RTX 3060 Ti Lite Hash Rate]   Driver:  NVIDIA-Linux-x86_64-550.135

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This is a build issue.  DT usually builds and works just right :-)

**Comment by ralfbrown** [comment]
Which version of lensfun do you have installed?  There's a 0.3.95 floating around (which some distros include simply because it has a higher version number) that is really a pre-alpha version having incompatible API changes with no practical way to determine automatically at compile-time which API to use....  You need 0.3.3 or 0.3.4.  Current master builds just fine for me with 0.3.3.

**Comment by john-k-h** [comment]
OK, that was it.  I was using lensfun-3.99 and that was a no-go, as you just told me ;-)

I'm now running lensfun-3.4 and DT builds just fine.

Thanks for the help.

**Comment by john-k-h** [comment]
My comment is above.
