### ISSUE TITLE
The visibility of the information shown with an image in full screen (F from Lighttable) should be cursor dependent

### ISSUE THREAD

**Issue by KIRSJ** [darktable-org/darktable#17944]
**Is your feature request related to a problem? Please describe.**

No, just timesaving

**Describe the solution you'd like**

I currently run 4.9.0+1162~ge079290f37
I would like the information shown in the upper left corner covering the image to only be shown when the cursor is inside the image - and to immediately disappear when the cursor is moved outside the image. In this way the timeout feature is unneccessary and the user will not have to wait seconds for the information to disappear each time he has moved the cursor.

**Alternatives**

Can's think of anything better.

**Additional context**

na

**Comment by jenshannoschwalm** [comment]
I read this report three times and confess, I have not the slightest idea what you are talking about.

**Comment by zisoft** [comment]
I have set the image information overlay in full screen to off, if that helps for you:

- Enter full screen mode (F)
- Let the top tool bar appear by pressing ctrl+shiftt+t
- turn the overlay off for this mode

![Screenshot 2024-12-04 151841](https://github.com/user-attachments/assets/f35b850f-05fa-4f5f-9c15-87217a293e66)

**Comment by KIRSJ** [comment]
jens,
My mistake - I only mentioned full screen (F) in the title.

zisoft,
Thank you.
I was not aware of this feature in full screen mode.
I can go down to zero seconds.
But more interesting regarding my suggestion - I can actually move the cursor to the edge of the screen to make the information go away until I enter the screen again.
This solves the problem. I withdraw my suggestion.
