### ISSUE TITLE
Non OpenCL build are failing

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#17953]
@jenshannoschwalm : 

This breaks the compilation for builds without OpenCL support:

```
/home/pascal/dev/git/darktable/src/develop/pixelpipe_hb.c:2777:75: error: 'CL_SU
CCESS' undeclared (first use in this function); did you mean 'EXIT_SUCCESS'?
 2777 |                           ? (dt_opencl_events_flush(pipe->devid, TRUE) !
= CL_SUCCESS)
      |                                                                         
  ^~~~~~~~~~
      |                                                                         
  EXIT_SUCCESS
compilation terminated due to -Wfatal-errors.
```

And indeed the call to `dt_opencl_events_flush` is done outside of `#ifdef HAVE_OPENCL`.

_Originally posted by @TurboGit in https://github.com/darktable-org/darktable/pull/17947#discussion_r1870733120_

**Comment by jenshannoschwalm** [comment]
As CL_SUCCESS is zero that revert would be ok. Maybe better to #define CL_SUCCESS in opencl.h in the non-opencl build part for clarity.
