### ISSUE TITLE
random crashes (segmentation faults) on mac ARM (DT 4.8.1, macOS 14.7.1)

### ISSUE THREAD

**Issue by mgiambon** [darktable-org/darktable#17976]
### Describe the bug

darktable crashes erratically during use producing a segmentation faul. Quite frequently straight upon startup. In such circumstances an immediate second launch usually works, just to further crash at some future random point such as when editing a picture, when importing a new one or when exporting a rendered one. I attach a trace with two different sessions both with crashes, generated with "-d all", hoping this can help. 

### Steps to reproduce

1. Startup darktable -> crash straight away (seg fault)
3. Startup again -> works fine up to a point where apparently with no clear pattern it crashes again (seg fault)

### Expected behavior

more stability in general

### Logfile | Screenshot | Screencast

[darktable 2.txt](https://github.com/user-attachments/files/18064718/darktable.2.txt)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

Sonoma 14.7.1

### Describe your system?

Mac Studio M1 Max 32GB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Mac Studio GPU

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Previously I was successfully using darktable 4.2 (2022) and than  4.4 (2023) with no such issues at all.

**Comment by mgiambon** [comment]
Just an update on this. I did a fresh install and I rebuilt the db in the hope of adding a bit of stability. Initially I was happy as I managed to import all photos and file structure (ca. 200 GB) into the new instance with no crashes. All adjustments were still there and worked. But my luck did not last long. After the initial success I'm back to 3-4 crashes in a row just by starting up the app...

**Comment by victoryforce** [comment]
@mgaimbon Just yesterday darktable 5.0.0 was released. Please check if it fixed this issue.

**Comment by mgiambon** [comment]
Hi Victor, thanks for the feedback I’ll give it a try as soon as I can.Cheers,mgIl giorno 22 dic 2024, alle ore 11:18, Victor Forsiuk ***@***.***> ha scritto:﻿
@mgaimbon Just yesterday darktable 5.0.0 was released. Please check if it fixed this issue.

**Comment by mgiambon** [comment]
Yes, installing version 5.0 solved the issue altogether! Successfully migrated the DB,  did edit a few pictures, worked with custom presets, exported pictures, with no stability issues. Many thanks! This bug report can be closed.
