### ISSUE TITLE
Clicking Reset or Hamburger menu in some module hearders toggles the open/close 

### ISSUE THREAD

**Issue by paperdigits** [darktable-org/darktable#17985]
### Describe the bug

In the Export module, clicking the Reset of Hamburger menu toggles the open/close action of the module. c/o https://github.com/darktable-org/darktable/pull/17979

### Steps to reproduce

1. Go to the lighttable view.
2. Click the Reset button on the Export Module
3. The module opens (if closed) or closes (if open). 

### Expected behavior

It shouldn't toggle open/close if there is a button there, even if the button is inactive. 

### Commit

https://github.com/darktable-org/darktable/pull/17979

### Where did you obtain darktable from?

self compiled

### darktable version

23a71cd9ac744a7a4187c8f8e00ce9e95dfe595e

### What OS are you using?

Linux

### What is the version of your OS?

NixOS 24.11

### Describe your system?

Wayland, openCL off

### Are you using OpenCL GPU in darktable?

No

**Comment by elstoc** [comment]
There's a similar issue with the on/off button toggle in processing modules. It's because the buttons are using a toggle action and I don't know how to stop that event also causing the button release event from firing.

**Comment by elstoc** [comment]
Apart from reverting my PR, I don't know how to resolve this

**Comment by elstoc** [comment]
This looks to be fixed in master
