### ISSUE TITLE
Supporting korean

### ISSUE THREAD

**Issue by p030610** [darktable-org/darktable#17994]
Hello, Developers & Users.

I use this software from South Korea, and I realized that many people in Korea doesn't use this software.

Koreans said if Darktable has Korean support, they will gladly use one.

I think I can add Korean support. 

As a Korean, I want to support this project.

Thank you.

**Comment by victoryforce** [comment]
@p030610 Great! If some help is needed, don't hesitate to ask.

**Comment by victoryforce** [comment]
Since this issue is only used to communicate a desire to do some work, I don't see a need to keep it open. If any questions arise, they can be asked here, regardless of the issue status.

**Comment by p030610** [comment]
Thank you, I am working for Korean .po file now. If the translation finishes, I will ask some questions about adding .po file and translations to Darktable. I think the translation will take several days.

**Comment by victoryforce** [comment]
The current state of the `darktable.pot` file that you are translating corresponds to the GUI strings of darktable 5.0.0 release. The source code of this version has already been finalized, so your translation will not be included in it. As a rule, a correction release is made shortly after the release of the scheduled stable version (currently it may be 5.0.1). If you manage to complete the translation before this release, it may be included in it.

Darktable is developing quite dynamically and in new releases the number of changed GUI strings can be significant. Only those languages ​​that have a small (less than a certain threshold) number of untranslated entries are included in darktable release. Therefore, a certain commitment is required for the constant availability of the GUI language. The good news is that updating the translation for the next release requires an order of magnitude less work than the initial translation.

**Comment by p030610** [comment]
If I make merge requests with finalezed translation .po file before Dec 21st, will be the translation applied in next release? I can complete the  translation till tomorrow.

**Comment by p030610** [comment]
Thank you for replying. Till next fix release, I will review my translations.
