### ISSUE TITLE
module presets not being applied

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#18018]
### Describe the bug

Attempting to apply a module preset does nothing.

### Steps to reproduce

1. Open a fresh image in darkroom
2. open any module with predefined presets (or use the presets button from the QAP, e.g. for color equalizer)
3. select a preset
4. notice that nothing happens (e.g. with color equalizer, tone curve, and the like, the graph does not change)
5. click on the preset button again and note that the selected preset is not highlighted as the current setting

### Expected behavior

The selected preset should be applied.

### Commit

4676fec3a8f8d445d98357cde25841cbbf214403 is the first bad commit
commit 4676fec3a8f8d445d98357cde25841cbbf214403
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Mon Dec 9 19:41:46 2024 -0500

    improve presets menu click behavior
    fixes 17889

I can confirm that current master works again after reverting this commit.

### Where did you obtain darktable from?

self-compiled

### darktable version

master

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 9

### Are you using OpenCL GPU in darktable?

None

**Comment by elstoc** [comment]
I can't reproduce this on darktable 5.1.0 (ArchLinux, nVidia). Presets work fine for me

**Comment by pehar1** [comment]
Checked with 4.9.0+1296~ga927ce4cb8 (Ubuntu 24.04), fresh `.config` and `.cache`, cannot reproduce either.

**Comment by ralfbrown** [comment]
OK, this is inexplicable - I can't repro with 5.1.0 either.  And going back to the commit found by the bisect, that works too!  What changed in the meantime?  A reboot....  [all tests before and after run with compilations after completely removing the build and for-test config directories]

**Comment by wpferguson** [comment]
Might be related to #18014.

**Comment by wpferguson** [comment]
Switching to lighttable and back did cause mine to update.
