### ISSUE TITLE
Darktable 5.1 app crash

### ISSUE THREAD

**Issue by pmuntianu** [darktable-org/darktable#18039]
### Describe the bug

When I use the DarkTable, it fails and exists. Then I have to start it again

### Steps to reproduce

Open Darktable
Use ToneEqualiser
Duplicate instance
Reset the original instance
Delete the new instance

### Expected behavior

should delete the instance

### Logfile | Screenshot | Screencast

[log.txt](https://github.com/user-attachments/files/18221683/log.txt)

### Where did you obtain darktable from?

downloaded from GitHub.com

### darktable version

5.1.0

### What OS are you using?

Linux

### What is the version of your OS?

15.1.1 (24B91)

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I am new to the darktable, so cant tell if that was happening before. But I believe no, because it would be unacceptable UX

**Comment by pmuntyanu** [comment]
Reinstalled 5.0 from the website. It is crashing as well when I past the edits from one photo to another

**Comment by MStraeten** [comment]
not reproducible on my macbook pro m1max with 5.0 ( macos 15.2 tried with custom build, official build, offcial 13.5 build)
maybe run darktable from terminal via  `/Applications/darktable.app/Contents/MacOS/darktable -d common` to get more information what exactly fails ...

**Comment by pmuntyanu** [comment]
[apple_error_report.log](https://github.com/user-attachments/files/18226477/apple_error_report.log)
[terminal_stdout.txt](https://github.com/user-attachments/files/18226478/terminal_stdout.txt)


Hi @MStraeten , here is the crash with the terminal output. The crash happened when I tried to delete another instance of just copied module. Hope that helps!

**Comment by MStraeten** [comment]
seems to be like #18052 - the new instance needs to have focus to cause the crash.
