### ISSUE TITLE
Darktable 5.0 locks up CPU when saving file with Blur function utilised & LightTable file viewer glitches and can't see files

### ISSUE THREAD

**Issue by Daf-T** [darktable-org/darktable#18046]
I posted up recently that Darktable was locking up my CPU to 100% for 45+ minutes when trying to save photos.

The kind folks here helped me narrow down my issue to the Blur function being unstable on 4.8.1, and that this should be resolved with version 5.0.

I’ve upgraded to 5.0 but I’m still getting the exact same issues:
CPU locked up @ 100% when trying to save files.

This time it’s only for c.3 minutes, but it’s still not working properly.

In fact, the first time I opened DT 5.0 and started editing a photo to test it out, after a few minutes of working with the Blur function, DT suddenly quit and closed down!

When I re-opened it, it refused to identify that specific file I was working on using drag & drop.

I tried navigating to the relavent folder using the Import / Add to Library function in LightTable instead, but when I get to the folder location, although it’s full of JPGs, it says “No items match your search”…?!

(Clearly the Import function isn’t for loading in photos…)

Then I  just clicked on the filter tab in the top left of the file viewer window in LightTable, selected ‘Legacy’ and it showed no files atall.
I then re-selected ‘all images’, and ALL my photos reappeared!?!

So that’s not so bad, even though it appears to be a slight glitch…

Hmm…

Looks like DT 5.0 has a few bugs in it.
Any suggestions about what’s happening, or is it just bug testing for v5.0…?
Thanks. -D

**Comment by MStraeten** [comment]
please add raw file and xmp sidecar so one can try to reproduce

**Comment by kofa73** [comment]
The user's XMP file on discuss.pixls.us used a blur radius of 96, using CPU-only processing. The documentation clearly states:

>This module is implemented using a “naive” convolution, which is a slow algorithm. Faster approaches are available (using FFT) but not yet implemented. The GPU implementation, through OpenCL, should hide this issue somewhat. In any case, **the runtime of the module will increase with the square of the blur radius**.
(https://darktable-org.github.io/dtdocs/en/module-reference/processing-modules/blurs/#caveats)

This is therefore not a bug, but a documented feature. Until an FFT-based version is created, it will remain slow.
https://discuss.pixls.us/t/darktable-5-0-blur-using-jpg-source-files-still-locks-cpu-lighttable-file-view-issues/47148/5

**Comment by Daf-T** [comment]
Hi Kofa73,

Does your answer suggest that a PC with an additional graphics card / GPU would be faster at saving JPG files utilising the Blur function? And would the saving time be faster with a lesser Blur amount / radius selected?

To be honest, I thought the Blurring calculations had already been done, as DT is displaying the Blurred effect on the display before I save the file.

Does DT have to recalculate the Blur again when you save the file?
So am I seeing a low-res 'off-line' version on the display, and when you save the file it then calculates a hi-res 'on-line' version..?

Otherwise, I don't understand why it takes any time atall to save the JPG file.

My laptop doesn't have a separate GPU, although it does have a spare express-card slot on the side, so maybe I could look into getting an additional graphics card to assist in my photo editing (if such exist)..?

**Comment by MStraeten** [comment]
> So am I seeing a low-res 'off-line' version on the display, and when you save the file it then calculates a hi-res 'on-line' version..?

Since image processing is quite resource consuming, there are several ways to speed up processing at cost of precision:
preferences-darkroom: reduce resolution of preview image
preferences-processing: prefer performance over quality
and especially https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/darkroom/high-quality-processing/
Unless you activate this darktable prioritizes speed over precision

**Comment by kofa73** [comment]
> Does your answer suggest that a PC with an additional graphics card / GPU would be faster at saving JPG files utilising the Blur function? And would the saving time be faster with a lesser Blur amount / radius selected?

Yes to both. I provided OpenCL vs CPU measurements, and quoted the documentation in https://discuss.pixls.us/t/darktable-5-0-blur-using-jpg-source-files-still-locks-cpu-lighttable-file-view-issues/47148/5, and suggested alternatives, too.

In the darkroom, usually not the whole image is processed (only the visible part, and only at the resolution required to display what's visible). Additionally, it is my understanding that such processing results are not cached on disk (not reused outside the darkroom, not even for exports initiated from the darkroom -- I may well be wrong).

So, for such high blur radii, please switch to another module, another computer, or to a GPU. Unless you have reason to believe there is an actual bug, please close this issue. While processing is slow, I don't see a lock-up.

**Comment by Daf-T** [comment]
I've just tried to save a file which has maybe an 1/8 of the picture blurred using the Blur function radius 96.

The CPU has been @ 100% for over 15 minutes now, and still it's 'locked-up'...
I've clicked on the 'x' / cancel tab to try and stop the file save function, but the CPU is STILL @ 100%...
Closing Darktable makes no difference, CPU STILL @ 100%...

I have to navigate to the Darktable process in the Task Manager and 'End Process' to kill the CPU 100% usage...

If this isn't the definition of a software bug, then I don't know what is TBH.

Here's the DT log file:
[darktable-log.txt](https://github.com/user-attachments/files/18255301/darktable-log.txt)

I can't upload the XMP sidecar file as the file type isn't supported on this forum's attachment facility, apparently.
(Although it is supported on the pixel/darktable forum... Odd)

Other DT users pointed out that this CPU glitch when saving JPGs with Blur function on DT 4.8.1 was a bug that was going to be addressed in v5.0.
It doesn't appear to have been resolved, and it wasn't me that identified this as a software bug.

Any suggestions would be greatly appreciated, as the Blur function is something I use all the time, so having it unusable is far from ideal.

Thanks - D

**Comment by kofa73** [comment]
> I've just tried to save a file which has maybe an 1/8 of the picture blurred using the Blur function radius 96.

That's not how masks work. First, the effect is applied to the whole image; then, the original and the processed images are blended according to the mask.

In https://discuss.pixls.us/t/darktable-5-0-blur-using-jpg-source-files-still-locks-cpu-lighttable-file-view-issues/47148/5 I gave you an example for _diffuse or sharpen_ settings that were about 10x faster and looked similar.

You have a very old machine, and are trying to use a large blur radius on an module whose processing time depends on the *square* of the blur radius, all that without a GPU. Until someone implements the FFT-based approach hinted at in the documentation, this module, with those settings, will be too slow on your machine.

**Comment by victoryforce** [comment]
> So, for such high blur radii, please switch to another module, another computer, or to a GPU. Unless you have reason to believe there is an actual bug, please close this issue. While processing is slow, I don't see a lock-up.

I completely agree, there is definitely no bug here. We observe extremely slow processing due to the imperfection of the algorithm. Yes, this module needs to be rewritten as FFT code. But if we want to keep an issue open to remind us of this need, then it should be a clear FR. Since there is no bug, it would be better to close this bug report.

BTW, I am tempted to suggest a PR to set a soft limit for this parameter with a smaller blur radius and allow the current max value as a hard limit.

**Comment by Daf-T** [comment]
Thanks for the comments and attempts at help.
I find it incredible to think that it's acceptable for a PC to have to run its CPU @ 100% for half an hour or so, in order to save 1 photo file with a bit of blurring added.

My old XP tower used to render 16:9 (non-HD) video far faster than that on Premier, and that often had FX added too.

You may be right about this aspect of it, but I myself can't wrap my head around the disparity of it all.

**Comment by victoryforce** [comment]
> I find it incredible to think that it's acceptable for a PC to have to run its CPU @ 100% for half an hour or so, in order to save 1 photo file with a bit of blurring added.
> 
> My old XP tower used to render 16:9 (non-HD) video far faster than that on Premier, and that often had FX added too.

@Daf-T I really don't understand what idea you are trying to convey with your comment.

**Comment by Daf-T** [comment]
Thanks for the comments and attempts at help.
I find it incredible to think that it's acceptable for a PC to have to run its CPU @ 100% for half an hour or so, in order to save 1 photo file with a bit of blurring added.

My old XP tower used to render 16:9 (SD) video far faster than that on Premier, and that often had FX added too.

You may be right about this aspect of it, but I myself can't wrap my head around the disparity of it all.
