### ISSUE TITLE
Segmentation fault when using Lua

### ISSUE THREAD

**Issue by jakub-wawrzyniak** [darktable-org/darktable#18044]
### Describe the bug

I found a segmentation fault, and it's reproducible. I just wanted to let you know it's there, if you think it's not worth investigating feel free to dismiss the issue.

Segfault occured after running a Lua script via keyboard shortcut. The Lua code looks like:
```lua
local dt = require("darktable")
local function do_segfault(event, shortcut)
	dt.gui.action("iop/exposure", "instance", "new", 1, 8)
end

dt.register_event("segfault shortcut",
	"shortcut", do_segfault,
	"A shortcut that causes segfault")
```

After running it in the "darkroom" view and clicking anywhere on the screen, the segfault occures.

### Steps to reproduce

1. Add the attached Lua code to luarc in ~/.config/darktable
2. Run `$ darktable -d lua` from bash
3. Bind a new keyboard shortcut to "segfault shortcut"
4. Open any image in darkroom view
5. Run the shortcut
6. Click anywhere on the screen
And the segfault occures

### Expected behavior

Darktable should throw a Lua error, instead of crashing

### Logfile | Screenshot | Screencast

[backtrace.txt](https://github.com/user-attachments/files/18223140/backtrace.txt)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 41

### Describe your system?

KDE Plasma 6 + Wayland

### Are you using OpenCL GPU in darktable?

No

**Comment by wpferguson** [comment]
You specified instance `8` in your command when you should have specified instance `0` or just left it out and `0` would be assumed.  darktable seg faulted because the instance didn't exist.

Also, the 1 should be `1.0`.

**Comment by jakub-wawrzyniak** [comment]
Yeah, I'm assuming I did something wrong in Lua. Just thought that maybe some bound checks on the C side might improve stability. But thanks for a quick response anyway!
