### ISSUE TITLE
darktable 5.0 on macOS: color deviations in darkroom view.

### ISSUE THREAD

**Issue by geni1105** [darktable-org/darktable#18099]
### Describe the bug

With darktable 5.0, on macOS color in darkroom view is not correct. The preview and lighttable views look the same, the darkroom views show a hue shift and less saturation. RGB values (as measured with the Digital Color Meter application) show 221/72/42 in darkroom, and 236/45/41 in preview / lighttable.
<img width="1728" alt="Bildschirmfoto 2024-12-28 um 19 18 26" src="https://github.com/user-attachments/assets/263961b3-c662-4a12-b901-b481713121de" />
Issue occurs with both OpenCL on and off.

I used the image downloaded from this discussion https://discuss.pixls.us/t/darktable-on-macos-are-there-bugs-with-icc-profiles/28930/120 , which is in AdobeRGB.
![e726e9ba9be338b7e805da91d3110315899d6015](https://github.com/user-attachments/assets/999fca26-ae23-44cd-97c5-79aa8011dbb8)

Other applications, like Photoshop, fit to preview and lighttable, when the image is converted to sRGB at import. 
darktable 4.8.1 works correctly, color rendering in darkroom view, preview and lighttable are the same (and like in other applications). 

### Steps to reproduce

Import the attached test image and switch to darkroom view. 

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

5.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 15.2 Sequoia

### Describe your system?

iMac 27" Retina 2020 (monitor is Display P3 capable).    

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Radeon Pro 5300 4 GB

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

4.8.1. works correctly.

**Comment by MStraeten** [comment]
you're in softproof mode - so the rendering depends on your given icc profile

**Comment by geni1105** [comment]
Oh, stupid me - did not notice that. Sorry for the  noise ...
