### ISSUE TITLE
Multiple "forward matrix in '...', please report via darktable github" Messages on Import

### ISSUE THREAD

**Issue by RayJW** [darktable-org/darktable#18109]
### Describe the bug

I'm trying to import a bunch of old images on a fresh installation of darktable, and I'm getting a lot of these error messages. Once imported, the images seem to look fine.

### Steps to reproduce

1. Use "add to library..."
2. Select a few pictures with this issue
3. Watch the warning pop up

### Expected behavior

Darktable should either not have a problem with this or if that's expected behaviour maybe change the message to avoid a bunch of duplicated bug reports. Although, I will say, searching for forward matrix didn't show a single issue that seems related.

### Logfile | Screenshot | Screencast

`darktable -d common`: [log.txt](https://github.com/user-attachments/files/18269630/log.txt)

### Where did you obtain darktable from?

distro packaging

### darktable version

darktable 5.0.0

### What OS are you using?

Linux

### What is the version of your OS?

CachyOS Linux

### Describe your system?

I think none of that applies here. Otherwise, let me know and I'll happily provide any information.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel Iris Xe Graphics [Integrated]

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

- Can you reproduce with a RAW or Jpeg or both? I'm importing both the JPEG and RAW files, but the error only shows for the DNGs.
- Are the steps above reproducible with a fresh edit (i.e. after discarding history)? Yes
- Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Yes
- Do you use lua scripts? None

Edit: I forgot to add, if pictures producing this issue would be of help, I'll gladly try to find a few that do not contain any personal data. I don't feel comfortable sharing all pictures here on GitHub just like that.

**Comment by jenshannoschwalm** [comment]
> Edit: I forgot to add, if pictures producing this issue would be of help, I'll gladly try to find a few that do not contain any personal data. I don't feel comfortable sharing all pictures here on GitHub just like that.

Yes. I would be **very** interested in such images if they are native DNG files from a camera (No real interest if the files where written by some adobe soft.) 
I would only use those files to investigate and possible improve color maths ...

**Comment by AlexKalopsia** [comment]
First time using DT, and also getting this behavior on a lot of DNG files. Those were - I believe - converted by Lightroom from canon/sony raw to DNG.

**Comment by RayJW** [comment]
> No real interest if the files where written by some adobe soft

Come to think of it, that might be the case. Those aren't my pictures personally but were supplied to me by someone. However, that camera brand wouldn't produce DNGs. So, those might have been reexported from Lightroom. Does that mean I should close this issue then?

**Comment by jenshannoschwalm** [comment]
Maybe you could share one of those converted files to test my fix here :-)

**Comment by RayJW** [comment]
> Maybe you could share one of those converted files to test my fix here :-)

This one should do the trick ^^
[forward_matrix.zip](https://github.com/user-attachments/files/18277779/forward_matrix.zip)

**Comment by jenshannoschwalm** [comment]
> This one should do the trick ^^

Nope :-) I need the DNG file ...

**Comment by jeffjeffreyjeff** [comment]
Hi, it seems that all raw images created in my Samsung S23 phone using Expert Raw have this issue. I have attached an example (dng inside zip): 
[20241113-20241113_205123.zip](https://github.com/user-attachments/files/18280938/20241113-20241113_205123.zip)

**Comment by jeffjeffreyjeff** [comment]
I should have noted that the images do not open in the darkroom

**Comment by jeffjeffreyjeff** [comment]
> > No real interest if the files where written by some adobe soft
> 
> Come to think of it, that might be the case. Those aren't my pictures personally but were supplied to me by someone. However, that camera brand wouldn't produce DNGs. So, those might have been reexported from Lightroom. Does that mean I should close this issue then?

I'm not sure this should be closed, I am seeing this with DNGs from several sources including: S23 Expert Raw, HDR DNGs generated by LR.

**Comment by RayJW** [comment]
> > This one should do the trick ^^
> 
> Nope :-) I need the DNG file ...

Huh, I have no idea how that happened. I could've sworn I double-checked. Here's the correct file now, sorry ^^'
[forward-matrix-the-second.zip](https://github.com/user-attachments/files/18281216/forward-matrix-the-second.zip)

**Comment by jeffjeffreyjeff** [comment]
> > > No real interest if the files where written by some adobe soft
> > 
> > 
> > Come to think of it, that might be the case. Those aren't my pictures personally but were supplied to me by someone. However, that camera brand wouldn't produce DNGs. So, those might have been reexported from Lightroom. Does that mean I should close this issue then?
> 
> I'm not sure this should be closed, I am seeing this with DNGs from several sources including: S23 Expert Raw, HDR DNGs generated by LR.

However, I'm finding that only LR, PS and Topaz seem to be able to handle these files S23 files, Affinity and Rawtherapee can't handle them either.

**Comment by PerennDT** [comment]
I have the same issue as AlexKalopsia. I import files that has been used with LR. I have also a strange case for Jpg-files from Canon G1X mark II. These files are imported with a kind of Vingette that looks like a picture in a lens. It looks like the view is from inside the lens.

**Comment by jscooksey** [comment]
I'm having the same issue as well.  I have added these same files to darkroom before without issue on MacOS, but Im now using Fedora 41.  I'll check out the images in question and report on what camera they came from.  They were in Lightroom prior to this but I dont believe it created the files (on import converted from camera raw to DNG).  
I also still have darktable 5.0 on the MacOS so I can check and confirm they are added in to that catalog.

**Comment by TeamMasse** [comment]
I'm having the same issue. Imported into Lightroom on Windows. And on Import to darktable I get the forword matrix error on Windows and on Linux (Kubuntu)
