### ISSUE TITLE
GPS Data NOT being exported when working with jpgs

### ISSUE THREAD

**Issue by newenglanddroneservices** [darktable-org/darktable#18119]
### Describe the bug

When processing multiple jpg images from my DJI drone, the exported images DO NOT have the GPS data associated with the jpg images. Prior to modifying the images I checked the original jpgs from the drone and the GPS info was there. 
After processing, the GPS data was stripped out. GPS data is required when processing the imagery into maps or 3d models.

It seems when processing DNG files, the GPS info IS preserved.

### Steps to reproduce

- Load up any jpg image that contains GPS coordinates in the GPS section of the metadata. Observe the GPS data prior to importing into DarkTable
- Apply some changes to it i.e saturation, contrast etc
- Select that one image and export it.
- View the processed image and examine the meta data. The data that was in the GPS section is now deleted.

### Expected behavior

Dark table should preservice this key information. When dealing with drone imagery, you could have over a 1000 images easily. Adding accurate GPS data manually is not an option. All original metadata should be preserved.

### Commit

I used 4.8 and the latest 5.0 release, and both have this problem.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

5.0.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.04

### Describe your system?

128 gig
48 core processor

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Nvidia GE RTX 2070 - 560.31.02 - gcc version:13.3.0

**Comment by newenglanddroneservices** [comment]
![DJI_20241228151221_0086_V](https://github.com/user-attachments/assets/d41dfaf0-a4f6-4f97-a205-dbb2c308545a)
Example JPG with GPS data. Run this through a simple adjustment, export and GPS data will be stripped.

**Comment by ralfbrown** [comment]
Have you enabled "geo tags" in the export module's preferences? (on its hamburger menu)
What file format are you exporting to?  Several formats (such as AVIF and JPEG XL) only support all or nothing for metadata export and thus get nothing by default, as explained in the release notes.

**Comment by newenglanddroneservices** [comment]
That did it! 
Exporting the geo-tags. There is a "geo-tagging" module also and I was locked on that... didn't think to look at the export menu. :(

Thanks!
