### ISSUE TITLE
For your info: Windows Defender Antivirus finds virus in nightly build of 29 December ???

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#18112]
### Describe the bug

For your information:
Microsoft Defender Antivirus notifies that the nightly build for Windows (of 29 December)
“darktable-5.1.0+19.gf2352efd98-win64.exe”
Contains a virus : Trojan:Win32/Wacatac.B!ml
This program is dangerous and it executes commands from a malicious user.
Not sure how serious this is.

### Steps to reproduce

Not sure how serious this is.

### Where did you obtain darktable from?

GitHub nightly

### darktable version

5.1.0+19~gf2352efd98

### What OS are you using?

Windows

### What is the version of your OS?

Not sure how serious this is.

### Describe your system?

Not sure how serious this is.

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Not sure how serious this is.

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Not sure how serious this is.

**Comment by ptilopteri** [comment]
you should make a report against Windowz Defender mis-identifying
it is a "serious" windowz problem

**Comment by cabuy** [comment]
Probably yes.

**Comment by victoryforce** [comment]
> “darktable-5.1.0+19.gf2352efd98-win64.exe”
> Contains a virus : Trojan:Win32/Wacatac.B!ml

This is a [nightly build](https://github.com/darktable-org/darktable/releases/tag/nightly), it is placed on the release download page by [GitHub action](https://github.com/darktable-org/darktable/blob/nightly/.github/workflows/nightly.yml).

In the process of creating this package for Windows, all the build of program binaries from source code and the movement of binaries between servers takes place only in the GitHub infrastructure.

Therefore, the statement that the downloaded binary of the darktable build contains a virus would mean that at least one of the following is true:

- Malicious code is present in the darktable source code. I declare as a person who has reviewed all this code that this is absolutely impossible.

- GitHub servers are infected with a virus that is capable of infecting programs built on these servers.

- Malicious code is present in one of the widely used open source libraries used by darktable.

- Malicious code is present in GitHub runner image software supply chain.

The last three assumptions mean huge problems for potentially a lot of applications (it's ridiculous to think that someone was planning a targeted attack specifically on darktable). I don't rule out the possibility of another supply chain attack, but from a practical point of view, it is much more likely to assume that some crappy antiviruses do a poor job and give false positives based on unreliable heuristics alone.

You can report this to the Windows Defender team. If you don't want to, maybe I'll find the time to do it someday (after finding out where such reports are accepted first). But I'll probably report it in much stronger language.

> Not sure how serious this is.

For whom?

**Comment by cabuy** [comment]
It is possible to chat with someone from the support team. Ultimately, you'll end up in some call center. There’s little chance that this will be escalated. Or perhaps it’s just a chatbot.  

I can no longer recover the file where the meant virus was said to be located. So, I downloaded the nightly build from December 30, but a scan with Microsoft Defender Antivirus does not identify any virus there. As a result, I no longer have any material to demonstrate the issue. 
 
In the meantime, I had installed the weekly build that Bill Ferguson posts on pixls.us, so the darktable.exe is overwritten. I also scanned my "system" drive, my "data" drive, and performed an offline scan. Nothing was found anywhere.  

This remains an unresolved issue. I am assuming it’s a "false positive." I’m leaving it here and close it.

**Comment by cabuy** [comment]
@victoryforce also thank you for having a look and your comments.

**Comment by cabuy** [comment]
Kind regards,
Marc.

**Comment by wpferguson** [comment]
For anybody that reads...

The release build (and the weekly snapshots) are built on a windows 10 VM that is only used for building darktable.  After every build the entire tree is scanned by Windows defender to check for viruses.

**Comment by ralfbrown** [comment]
Being familiar with Ken Thompson's 1984 Turing Award lecture "Reflections on Trusting Trust" [[3-page PDF]](https://www.cs.cmu.edu/~rdriley/487/papers/Thompson_1984_ReflectionsonTrustingTrust.pdf), I wouldn't go as far as Victor to say malicious code in the darktable repos is categorically impossible, but it would be even harder to accomplish than the other three possibilities.

**Comment by cabuy** [comment]
@wpferguson, @ralfbrown, @victoryforce : thank you all for your comments. 

Advice can be to scan the .exe by an antivirus app after the download. (That's what I did with Bill's weekly build before installing.)

And if anything possibly malicious found, report it. 

Unless similar issues appear in the near future, I will assume that this was a false positive.

Marc.
