### ISSUE TITLE
Windows Colors and image changeing without alter

### ISSUE THREAD

**Issue by stilicrafter** [darktable-org/darktable#1925]
Hi.
I have the following problem:
My darktable behaves strange.
It changes information of the color (but not the slider, only image) if i do stuff refreshing the screen like croping. Also the Histogramm behaves strange.
It is hard to explain, but maybe a movi clip will help you: How can the CUT tool change colors.
I Think, windows update and a Windows libary are the problem, but i dont know :(

https://www.youtube.com/watch?v=h1SeCO5AS4k

(I am very sorry about my poor english, but i hope you understand my problem ^^ )

**Comment by TurboGit** [comment]
I'm not sure about the module you're using maybe "global tonemap" and so the behavior is correct. When you activate it the tone in the image are remapped, this is a complex algorithm that do change lot of value in the image. And it is also expected that the histogram changes to correspond to the new tone in the image.

**Comment by peterbud** [comment]
He is using the **crop and rotate** module as I see on the video

**Comment by TurboGit** [comment]
Looking closer it seems yes, but then there is a missing slider at the end! Not sure what is this version!

**Comment by TurboGit** [comment]
@stilicrafter : can you tell us where you have downloaded this version and which actual version it is?

**Comment by stilicrafter** [comment]
Hi.
I am useing Version 2.4.4 (see below icon, but if there is a more detailed version info, could you tell me where to find?)

The System is Windows 10 PRO on a Surface PRO 15 512GB

This image is a freshly opened RAW (see YouTube link) with all the setting. (And for easy understand i switched the GUI Langue from German to englisch ):  
https://www.youtube.com/watch?v=irnAjWw9b_0&feature=youtu.be
**I think**, you can also change the color whenn I open up or close the botom line (but i am not compleatly sure and it wasnt reproducable in the Video.
I also uploaded the RAW image. (see below)

[DSC07441.zip](https://github.com/darktable-org/darktable/files/2705590/DSC07441.zip)

**Comment by stilicrafter** [comment]
Setting s start in Youtube Video at Second 40.

**Comment by stilicrafter** [comment]
And , expect for GUI: These are my settings: 
https://www.youtube.com/watch?v=5YMK6vP2lWA&feature=youtu.be

**Comment by aurelienpierre** [comment]
Could it be a cache refreshing issue ? (crop and rotate just force a cache regeneration or something ?)

**Comment by stilicrafter** [comment]
>           Could it be a cache refresh issue ? (crop and rotate just force a cache regeneration or something ?)

How can i clear the cache ?
In Darktable itself? But also image altering actions can cause this. (Like Color tone Curve)

**Comment by aurelienpierre** [comment]
the cache is cleaned when you zoom in/out.

Could you provide the list of the modules you are using ?

**Comment by stilicrafter** [comment]
>           the cache is cleaned when you zoom in/out.
Also when Zooming in and out the Colors can change itself

> Could you provide the list of the modules you are using ?

Only the default one.
(Sharpen, base curve, orientation, highlight reconstruction, white balance)
And then , if i zoom on and out, it will change the colors.

**Comment by stilicrafter** [comment]
I Have some more buginformation: It must be an Nvida Library of my Laptop.
Reason: If my Battery drops below 5%,the dedicated GPU is disconnected by Windows from the System (result in forced close off all apps useing the Nvida), and only the integrated Intel GPU is used.
If I use DarkTable with less then 5 %, everything is fine.

**Comment by stilicrafter** [comment]
Since a new Windows Update the problem has been solved.
