### ISSUE TITLE
French translation: minor issues

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#1926]
**Dans les options de fusion des masques :** 

mask contrast -> actuel : masque de contraste -> suggéré : contraste du masque (l'inversion nom/complément en Fr revient souvent)

mask blur -> actuel : masque d'adoucissement -> suggéré :  floutage du masque

mask feathering -> actuel : rayon adoucissement -> suggéré : adoucissement du masque

**Dans la balance des couleurs :** 

contrast fulcrum -> actuel : contraste pivot -> suggéré : pivot du contraste

**Dans filmique :** 

middle-grey destination -> actuel : destination du gris moyen -> suggéré : gris moyen cible (label anglais à revoir)

destination power factor -> actuel : destination facteur de puissance -> suggéré : gamma cible (label anglais à revoir)

En général : en anglais, le complément du nom est placé devant le nom qu'il qualifie. En français, c'est l'inverse. 

Poke @TurboGit ;-)

**Comment by TurboGit** [comment]
All done, thanks!
