### ISSUE TITLE
Deprecate Tethering

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#1927]
This is a proposal to deprecate the tethering view.

Arguments:
* Entangle does it all, it's FOSS, uses the same libgphoto and is more lightweight,
* dt thethering lacks features (only basic camera controls & settings),
* nobody maintains it (last features added 3 years ago, last bug corrected 2 years ago).

**Comment by TurboGit** [comment]
But some people are using it, I do use it from time to time and it is quite handy to be able to develop immediately as it is imported automatically. Sure it lacks features, but well for my use (and probably others) I suppose it is enough.

**Comment by peterbud** [comment]
Also Entangle is not available on Windows, it's last release is also 1+ year.
I agree tethering is indeed not the most polished part of dt, but based on that we could also deprecate many other things.

**Comment by aurelienpierre** [comment]
Does the tethering work on Windows with dt though ?

**Comment by peterbud** [comment]
Yes, it works, there is a short description how to make it work in the FAQ:
https://www.darktable.org/about/faq/#faq-tethering

**Comment by aurelienpierre** [comment]
Ok then, let's keep it.
