### ISSUE TITLE
No PGP signature for 2.6.0 tarball?

### ISSUE THREAD

**Issue by ArchangeGabriel** [darktable-org/darktable#1936]
Until this release, Darktable used to PGP sign release artifacts (e.g. https://github.com/darktable-org/darktable/releases/download/release-2.4.4/darktable-2.4.4.tar.xz.asc). However, there is no signature for the current 2.6.0 release.

At first I thought it was an issue with the release process failing at some point, especially with the missing Windows .exe, but this latter issue has been fixed while no sigs appeared.

Is this expected?

**Comment by TurboGit** [comment]
Yes, expected as I did not sign the release.
