### ISSUE TITLE
OS X App: recent lensfun db

### ISSUE THREAD

**Issue by pick2510** [darktable-org/darktable#1939]
Hi,
I'd like to use darktable on OS X with newer lensfun db versions. 
The reason for this is the usage of converted lens profiles from Camera RAW. I somehow don't manage to build a functional version of darktable in OS X using newer lensfun versions. The built version randomly crahes. But this could be related to other dependencies of the build.
Is it possible to bundle the OS X app with a more recent lensfun version?

**Comment by parafin** [comment]
macOS package uses latest stable release (0.3.2) with latest lensfun database, updated at the moment of the build.

**Comment by pick2510** [comment]
Hmm.... 
But it should look into .local/share/lensfun ?
Somehow it doesn‘t work if I use the lensfun-convert-lcp. This script puts the additional data in .local/share/lensfun/version_2
On Linux everything is fine.
Do I need to put this somewhere else?

**Comment by parafin** [comment]
lensfun db is inside app bundle: darktable.app/Contents/Resources/share/lensfun
I think the one in user's home directory is not used. Try copying it over.

**Comment by pick2510** [comment]
So, I copied the new db to the appropriate directory and I found out, that lensfun 0.3.2 stable doesn't support the acm model in the database (model="acm"). Since 0.3.2 stable is already three years old and I'm not sure if they release a stable version very often: Would it be possible to build against a newer version? A more recent version is 0.3.95-alpha
I think Ubuntu packager do this but can't check at the moment since my linux notebook is at the office until the end of my vacation.  
I would try to do it, but I have installed homebrew and would probably mess up my system with an additional MacPorts installation.
A lot of lenses, even a lot from major manufacturer like Canon, don't have complete lens profiles with TCA and vigenitting in lensfun. 
Usage of converted Camera Raw profiles would help a lot to completely abandon Lightroom.

**Comment by parafin** [comment]
I will consider upgrading lensfun for 2.6.1 release.

**Comment by pick2510** [comment]
Great! Thx

**Comment by parafin** [comment]
@pick2510, just letting you know that I won't update lensfun for next release. I tried it, but currently darktable and lensfun alpha release are incompatible - a lot of crashes and code changes are required in DT.
