### ISSUE TITLE
Enable mixed (mouse + keyboard) shortcuts/accels

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#1950]
For now, we can only assign keyboard shortcuts to GUI events such as slider increase/decrease/reset. That makes at least 3 shortcuts by setting, and enforces to use both hands on the keyboard, while the mouse is still often needed, so we need to move too much (repetitive strain injury for the win).

I would like to be able to assign only one letter to a slider (E for exposure, T for temperature, H for hue etc.) and then use the mouse to increase/decrease/reset the value. For example:

- Wheel up: fine increase
- Wheel down: fine decrease
- Right click: coarse increase
- Left click: coarse decrease
- Double click: reset

That way, we have only one shortcut to remember per setting, and one hand always stays on the keyboard (to select the setting) while the other hand always stays on the mouse (to modify the value), and the ergonomics are much better.

**Comment by TurboGit** [comment]
This would be wonderful, but I'm not sure it is possible with Gtk+, if an expert pass by can you comment on the feasibility?

**Comment by aurelienpierre** [comment]
Fixed by #2620
