### ISSUE TITLE
Fujifilm X-T3 support - Lens correction "Camera/lens not found"

### ISSUE THREAD

**Issue by francoiscourt** [darktable-org/darktable#1961]
on both Linux Mint 19.1 and Win10, the lens correction module does not find the camera/lens
the model X-T3 does not show up ib the Fujifilm list when trying to select manually

**Comment by aurelienpierre** [comment]
Have you tried http://lensfun.sourceforge.net/manual/v0.3.2/lensfun-update-data.html

**Comment by TurboGit** [comment]
Common issue with lensfun database not being updated or missing the camera+lens in the database. You can contribute this to the lensfun project. Thanks.

**Comment by levitte** [comment]
According to digicamdb.com, the crop factor for the X-T3 should be 1.534 (you have to calculate it yourself, as they show the value rounded to two decimals).

I submitted a [merge request](https://sourceforge.net/p/lensfun/code/merge-requests/3/) a few minutes ago...
