### ISSUE TITLE
Add support for Space Navigator (3D Mouse / 6 axis)

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#1967]
The Space Navigator is a 6 axis (3 rotations /  3 translations) + 2 buttons joystick used primarily to move/handle objects in 3D space, in apps such as CAD and 3D modellers. It has 2 drivers on Linux, one proprietary, [one free](https://github.com/FreeSpacenav). The free one is packaged in all the Linux distros I have tested (Ubuntu, Debian, Fedora) and the API are compatible.

I propose to add the support for it, as I own one. I will need some guidance, because I have never integrated drivers before (namely : which files to hack).

Basic features could be mapping axes with darkroom preview and lighttable (zoom in, zoom out, scroll x, scroll y).

**Comment by dterrahe** [comment]
#8078 supports gamepad like controllers via SDL2, which maintains its own database of controller definitions that tries to map any device to the more or less standard gamepad design (two joysticks, a 4 way hat, 4 buttons, 2 triggers and two shoulder buttons). You could maybe try if it is possible to create a definition for the Space Navigator, using for example https://generalarcade.com/gamepadtool/

If that doesn't work at all, a dedicated joystick module may be needed that uses the lower level SDL1 type joystick api.

You may have to prevent X from capturing the device and #8078 isn't done (and there will be follow ups to it for some time), so some types of actions are not mappable yet or are captured at the view level (by the key_pressed methods). There's still a bit of work to do...
