### ISSUE TITLE
Feature Request: fill (black) edges (eg useful after perspective correction)

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#1975]
Right now anything that does not exist cannot be drawn onto, so the perspective correction leaves a black shape that needs to be cropped along with the whole side, and it gets ignored in every operations (s.a. heal).

Often we don't want to crop that whole side out because that band happens to be where the most crucial part of the picture is (and the part that is missing is often simple low frequency stuff).

In these cases my workflow is to export the image and finish the inpainting in gimp/g'mic. It's pretty straightforward but I much prefer to do everything in darktable and click on [export to Wikimedia Commons](https://github.com/trougnouf/dtMediaWiki).

**Comment by edgardoh** [comment]
And what is exactly your request here?

**Comment by trougnouf** [comment]
For the black corners/edges (eg resulting from a perspective correction without automatic cropping) to be drawable on by the healing/cloning tool.

**Comment by edgardoh** [comment]
If you compile it from master you can reorder the modules now, so place the
retouch or spot removal after perspective correction and it should work.

**Comment by trougnouf** [comment]
Indeed, thank you!

**Comment by stippingerm** [comment]
@edgardoh which version does it apply to? 2.6.2 came out Mar 21, 2019.
@trougnouf I would point out that reordering is may not be a complete solution.
In my version 2.6.2 spot removal nicely follows the tilted lines of perspective correction and I prefer not to loose this feature. This also implies spot removal happens after perspective correction, still, it does not draw outside the original canvas of the photo, i.e., I cannot fill up the black areas.
