### ISSUE TITLE
Equalizer (maybe?) add black square on picture when editing and export

### ISSUE THREAD

**Issue by pierre-guillot** [darktable-org/darktable#1980]
Hello guys.
I updated darktable to 2.6 on my Archlinux (directly from official repo) and now I have a problem with the equalizer module.
I usualy apply the style "EQ+Denoise+HotP - Matt Eastwood" (you can found it on https://dtstyle.net/) on my high ISO picture to denoise it but since the last version, some "black square" are presents on the picture when I use this style :  https://framapic.org/7x6tOxMTPuEV/MhcL4XAH5zY1.png
If I export this picture, the problem is still present.
Used camera : DMC G7 and RAW file. Tested with a RAW downloaded here and same result : http://www.mamiyaleaf.com/samples_credo_80.html

**Comment by upegelow** [comment]
Looks like a tiling problem. Do you run with OpenCL? If yes, what 
happens if you disable it?

Ulrich

Am 07.01.19 um 19:15 schrieb pierre-guillot:
> Hello guys.
> I updated darktable to 2.6 on my Archlinux (directly from official repo) 
> and now I have a problem with the equalizer module.
> I usualy apply the style "EQ+Denoise+HotP - Matt Eastwood" (you can 
> found it on https://dtstyle.net/) on my high ISO picture to denoise it 
> but since the last version, some "black square" are presents on the 
> picture when I use this style : 
> https://framapic.org/7x6tOxMTPuEV/MhcL4XAH5zY1.png
> If I export this picture, the problem is still present.
> Used camera : DMC G7 and RAW file. Tested with a RAW downloaded here and 
> same result : http://www.mamiyaleaf.com/samples_credo_80.html
>

**Comment by edgardoh** [comment]
It seems like a non-local means denoise issue, this happens only with
opencl, so until is fixed you can disable opencl for export.

**Comment by pierre-guillot** [comment]
Yes I confirme : disable Opencl fix the problem. Thank you :)

**Comment by upegelow** [comment]
I would be interested to see the output when exporting with opencl 
enabled and with command line parameters '-d opencl'.

**Comment by pierre-guillot** [comment]
sorry for the late response, Can you explain to me exactly what I need to do? Lunch darktable with command line with the "-d opencl" parameter and copy/past the output?

**Comment by upegelow** [comment]
Please open a terminal session. Find out the full path of the darktable 
binary (there are different ways; try e.g. 'which darktable' or 'locate 
darktable').

Then start darktable the following way:

/FULLPATH/darktable -d opencl -d nan > /tmp/darktable.out

(Where FULLPATH is the path of the darktable binary.) Within darktable 
you now export an image which you know will produce black rectangles. 
Then you close darktable and you post the contents of /tmp/darktable.out 
here.

Ulrich

Am 18.01.19 um 08:32 schrieb pierre-guillot:
> sorry for the late response, Can you explain to me exactly what I need 
> to do? Lunch darktable with command line with the "-d opencl" parameter 
> and copy/past the output?
>

**Comment by pierre-guillot** [comment]
Hi!

re-enabled opencl and ran the command above. You can download output file here : 

https://framadrop.org/r/HVbD1nu4d7#2wfIxuY4Su4sYezduE9jsZJlSQ1gowuovzj4eczxtVk=

**Comment by rawfiner** [comment]
Hi
Do you still experience the bug on master?
PR #1999 and #2000 that have been integrated today should have fixed the nlmeans issue

**Comment by pierre-guillot** [comment]
I confirme : With version 2.7.0+496~g38e361f28 there is no problem!
