### ISSUE TITLE
OpenCL masking broken with last commits

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#1992]
With OpenCL on:

- mask opacities on exposure module don't give the same result as same settings on SSE2/C codepaths. The OpenCL path gives softer results and low opacities (< 20 %) actually entirely disable the module. This is with mask feathering on, mask blur on, general opacity < 100%, parametric + drawn masks blending, key blending on luminance.
- mask previews won't display at all. This sees to affect pretty much every IOP tested.

This affects master with commits from the 9th and 10th January. I haven't been able to bissect for now since git is rebasing in a weird fashion, so I get conflicts with the last changes on the lighttable UI and Cairo segfaults.

Ping @houz

**Comment by TurboGit** [comment]
Confirmed!

**Comment by TurboGit** [comment]
Second point is fixed.

**Comment by aurelienpierre** [comment]
Great !

**Comment by TurboGit** [comment]
And can you still reproduce the first point? Looks like it could be fixed too by my change...

**Comment by aurelienpierre** [comment]
Seems all good now, indeed.
