### ISSUE TITLE
Capability to disable/hide hard-coded presets

### ISSUE THREAD

**Issue by msdm** [darktable-org/darktable#1994]
**Is your feature request related to a problem? Please describe.**
Hard-coded presets cannot be removed. Lately, a lot of such presets have been added to the master branch that make the presets list of some iops lengthy, specially when someone has also a bunch of personal presets. I personally prefer my own presets and almost never use those hard-coded ones.

**Describe the solution you'd like**
Add capability to hide/disable hard-coded presets. I think the presets section of preferences is a good place for this feature, so that a user can selectively hide the presets (s)he doesn't use.

**Comment by aurelienpierre** [comment]
which modules are affected ?

**Comment by msdm** [comment]
> which modules are affected ?

Actually this is a feature request and affects all iops. Personally I have lengthy presets lists for tone curve, equalizer, filmic, and channel mixer.

**Comment by aurelienpierre** [comment]
How bad is the length issue ? What is the size of your screen ? Because that sounds like a lot of GUI rewriting for a a small benefit, from where I sit. (as in: do we want a preference for all IOPs, or for each one ?). Also, if you don't use the default presets and yours are better, maybe share them to see if we can merge them ?

**Comment by junkyardsparkle** [comment]
I agree, it seems odd that there's such a sophistcated filtering system in place to keep lists uncluttered, but there's nothing you can do about the shipped presets. The graduated density module is one where I find this to be a bit of an annoyance (13 hard-coded presets). It would be less annoying if it was possible to get one's own presets to sort above these, but I don't think that's possible.
