### ISSUE TITLE
Zoom beyond 200% does not respect a proper reference point

### ISSUE THREAD

**Issue by msdm** [darktable-org/darktable#1995]
**Describe the bug**
For zoom-in by Ctrl+mouse wheel, the reference points of view for zoom levels higher than 200% is not the location of mouse pointer which makes user lose the location on the photo. In addition, when you zoom-in from 200% to 400% (by Ctrl+mouse wheel), then zoom-out to 200% without moving mouse, the view jumps to a new location other than initial view before zoom-in. The same thing also happens in 800% and 1600% zoom levels.

**To Reproduce**
1. Zoom to 200%
2. Move mouse pointer over a spot on the photo
3. Zoom to 400% using Ctrl+mouse wheel (mouse pointer is no longer on that spot)
4. Zoom-out to 200% using Ctrl+mouse without moving the mouse (still the pointer is not on the initial spot)

**Expected behavior**
Mouse pointer should point to a similar location on the photo when zoom level is changed

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: git-master

**Comment by TurboGit** [comment]
Thanks for reporting. This is now fixed.
