### ISSUE TITLE
Exporting Olympus High Res Shot crash

### ISSUE THREAD

**Issue by phixxx5** [darktable-org/darktable#1997]
**Describe the bug**
Since the update i can now open and edit High Res Mode Raw files from my Olympus OMD EM-5 Mark ii. I can also export them without making changes. But whenever i try to export them after making changes Darktable crashes.

**To Reproduce**
1. Open Darktable
2. Load 60 MP High Res File
3. Activate Local Contrast Module for example
4. Export Image

**Expected behavior**
Darktable calculates for some seconds and then closes without a message.

**Screenshots**
No Screenshot possible

**Platform (please complete the following information):**
 - OS: [Ubuntu 18.04]
- Memory [8 GB]
 - Version [2.6.0]

**Additional context**
Is it possibly caused by running out of RAM or something similar?
I could send you the RAW files I used but I can't attach them here.

**Comment by matejvanco** [comment]
Same issue on o OSX 10.14.2 (18C54), 8 GB RAM, DT version 2.6.0

**Comment by hellbuster** [comment]
I tested in 2.6.1 and it does not crash, but it instantly hangs. I activated local contrast (on default values) and levels.

**Comment by edgardoh** [comment]
opencl? No opencl? only with local contrast?

**Comment by matejvanco** [comment]
Any type of edit. Problem is during the export. When image is exported darktable crashes.

**Comment by edgardoh** [comment]
Please try disabling opencl and with only the exposure active.

**Comment by heitorPB** [comment]
I confirm the issue with Darktable 2.6.2, ArchLinux, 8 GB of RAM + Firefox open. If I close Firefox to free some RAM, Darktable exports all the images without crashing. But when I have all my 73 tabs in Firefox, Darktable does not have enough RAM and crashes.

Why does Darktable needs some GB of RAM to process photos of ~20 MB?

**Comment by phixxx5** [comment]
I tested it again today in darktable 2.6.1 with some more edits in my image and (after processing for some minutes) it successfully exported my image. So either version 2.6.1 fixed it or it really depends on the RAM usage during the processing because most of my RAM was free this time.

**Comment by edgardoh** [comment]
OK, still need an answer, but if dt don't have the resources to process the image then yes, it will crash.

**Comment by hellbuster** [comment]
Hi everyone,

Since I remembered that editing the same file converted to DNG worked fine, I did some tests with both the original and DNG.

At the end, I could track the problem to the Local Laplacian Filter for Local Contrast. Bilateral Grid works fine.

Maybe we could warn the users that Local Laplacian may use too much memory for big files.

**Comment by luhk** [comment]
I have had the same issue with Local Contrast using Darktable 2.6.0, 2.6.1, and 2.6.2, no OpenCL.
With large panoramas (80 megapixels from 16-bit TIFFs), the OOM killer kills Darktable when the Local Contrast module is enabled during export. With smaller images, Darktable sometimes is killed, sometimes isn't, depending on how much RAM other applications use. Setting the number of background threads to 1 and lowering the maximum tile size sometimes also helps.

This is on a machine with 8 GB RAM.

Apparently, the local contrast module needs large amounts of RAM. Is this a bug, or is this just the way it is?

**Comment by matejvanco** [comment]
Installed DT2.6.2 I tool several hours to export Oly EM5Mk2 HighRes photo. But DT did not crasehd this time. So far so good.

**Comment by Nilvus** [comment]
@phixxx5 : as it seems ok for you with 2.6.1, do you consider this resolved ? If yes, please close this issue.
