### ISSUE TITLE
Darkroom history flooded by tiny modifications during manipulation of sliders in Darkroom modules

### ISSUE THREAD

**Issue by aadm** [darktable-org/darktable#2007]
**Darkroom, history gets swamped by any modification on modules**

Working in Darkroom, on any module I believe (but only tried the most common: Exposure, Shadows/Highlights, Tone Curve, Local Contrast etc), for any small modifications of the input sliders the history gets another row added instead of waiting for the user to end his fine-tuning and accept the final value as the one to be added to History.

**To Reproduce**
1. Go to Darkroom, activate Exposure
2. Right MB click on the exposure EV slider to pop up the multi-functional control
3. adjust the exposure with the mouse
4. See History panel going crazy recording every tiniest movement of the mouse

**Platform**
 - OS: Ubuntu 18.10
 - Version: 2.7.0_git251.fff6ec3c5_a

**Note**
This issue only came up testing the very latest git compile (darktable_2.7.0_git251.fff6ec3c5_amd64.deb).

**Comment by TurboGit** [comment]
This generally happen when having a module activated with an old version of the module and then using it. The blend version has changed in master and I suspect that this is the culprit. Not really a bug. Just compress the history and this won't happen again on this image.

Can you check that?

**Comment by aadm** [comment]
You're right. After compressing the history stack the issue goes away. I can live with that! Just to be clear (maybe I misunderstood), this happens also on newly imported photos with no previous "history" in Darktable (I understood from what you wrote that this misbehaviour should only occur in a photo that was edited with a prior version of DT then modified).

**Comment by TurboGit** [comment]
Right, only those was was edited with a prior version.

**Comment by aurelienpierre** [comment]
> this happens also on newly imported photos with no previous "history" in Darktable (I understood from 

The culprit might be an automatic presets built with previous API and not updated. Or sometime, when you go back to older versions of dt, your presets database still has the newer API.
