### ISSUE TITLE
Redraw failure in lighttabe

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#2009]
**Describe the bug**
Changing the thumbnail size does not force redraw of the whole lighttable.

**To Reproduce**
1. Checkout and build fff6ec3c5332aa9abbab6523eced6eae94e988e7
2. Change the number of images per row with alt-1/alt-3

**Expected behavior**
A redraw of all thumbnails in the correct size.

**Platform (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version fff6ec3c5332aa9abbab6523eced6eae94e988e7

**Additional context**
May have to do with recent lighttable speed improvements.

**Comment by TurboGit** [comment]
Fixed. Thanks for reporting.
