### ISSUE TITLE
[UI usability] [WIP] masks selection from icons in 1-click

### ISSUE THREAD

**Issue by flowernert** [darktable-org/darktable#2011]
**Is your feature request related to a problem? Please describe.**
I make use of masks more than often, others probably do so, and it always bugs me that to access one of the few masking options I have to : 
- click on the combobox
- hover to my selected mask
- click on it

to be able to select my mask. 
To me, masks are a feature important enough for it to be a 1-click action to select the mask type and unfold its options.

**Describe the solution you'd like**
I would like to see an horizontal box with icons to select the mask type and allowing to access it in 1 click replacing the cumbersome combobox.

Screenshot of what I did after hacking a bit in the code : 

**basic view**
![image](https://user-images.githubusercontent.com/2923696/51400819-a1a4b780-1b49-11e9-9650-2d83e4c335f6.png)

**tooltips** on hover are preserved
![image](https://user-images.githubusercontent.com/2923696/51401310-b766ac80-1b4a-11e9-80f9-f58b867b3b27.png)

**toggling:** when one mask option is clicked, the mask becomes active and the box is toggled
![image](https://user-images.githubusercontent.com/2923696/51400982-04964e80-1b4a-11e9-933e-d7b70961ac70.png)

**disabling:** mask can be disabled by clicking the cross on the left
**1** hovering the cross 
![image](https://user-images.githubusercontent.com/2923696/51401258-98681a80-1b4a-11e9-8793-3c851eab989c.png)

**2** after clicking the cross
![image](https://user-images.githubusercontent.com/2923696/51401193-78385b80-1b4a-11e9-948a-8cda827325b4.png)

**Additional context**
I've taken caution of preserving the following functionalities : 
- in the darkroom, when the displayed image is updated (by film roll or key press), the toggled mask icon is updated appropriately to the updated image modules settings.
- only one mask type can be enabled at any time
and add this spec:
- the cross doesn't stay toggled once clicked as it is rather an un-toggling button

Currently I've implemented the proposed feature in an additive way (apart from not showing the combobox, every line of code that is related to it is still present). I'm looking forward to get rid of it without breaking anything yet, and to reuse at most the existing code and structures in develop/blend.h develop/blend.c and develop/blend_gui.c

I'll submit a PR once I'm completed.

Let me know what you think of the feature I propose :)

**Comment by TurboGit** [comment]
Sounds like a nice improvement to me!

**Comment by flowernert** [comment]
Thanks @turbogit

I mainly reused already existing icons defining code with a bit of tweaking, but I would appreciate suggestions for them if you or other people have some.

**Comment by TurboGit** [comment]
I'm no good at designing icons :)

Can you describe the icons from left to right?

Note that we have a new entry in the combo for raster mask.

**Comment by flowernert** [comment]
left to right
disable mask (cross), uniform (linear gradient), drawn mask (pencil), parametric mask (black/white circle), drawn+parametric (pencil+black/white circle), raster mask

**Comment by TurboGit** [comment]
Closing as now done/merged.
