### ISSUE TITLE
filmique, preserve chrominance issue

### ISSUE THREAD

**Issue by kikoucalou** [darktable-org/darktable#2029]
Now there is a very very important change in brightness when the "preserve chrominance" option is activated

 - OS: [build on linux mint]
 - Version [2.7.0+270] (git download 2019-01-22)

**Additional context**
On previous build version (git download 2019-01-21) filmique was fine with "preserve chrominance" option

**Comment by aurelienpierre** [comment]
Indeed. fixed with #2030
