### ISSUE TITLE
Not all languages are offered in interface language combo box

### ISSUE THREAD

**Issue by maruncz** [darktable-org/darktable#2034]
HI

when i installed darktable 2.6.0 from ppa:pmjdebruijn/darktable-release it was in czech because my system localization settings.

I then switched to english translation of darktable because i was trying to reproduce some steps from tutorial and i wasn't sure how to translate few things.

but when i wanted to switch it back i found that there is not entry for czech.

I use ubuntu 18.04

I tried install darktable on windows too and it was in english right away and also limited language selection

**Comment by aurelienpierre** [comment]
I think the CZ translation has been disabled in dt 2.6 because it is not complete. So you got the legacy translation at first, but then the option was removed. I think you can revert that in darktablerc. Or maybe contribute a translation for darktable 2.6.1.

**Comment by maruncz** [comment]
Ok, thanks
