### ISSUE TITLE
Configurable font-size

### ISSUE THREAD

**Issue by bapBardas** [darktable-org/darktable#2036]
I would like to be able to configure the size of the font used for menus and text elements in the panels.

Additional Context : _I actually am facing this issue while using darktable on an external display connected to my laptop (mac OS X) : I can barely read the menus and options due to the size of the font being too small._

**Comment by parafin** [comment]
Set screen_dpi_overwrite setting to something like 72 in `~/.config/darktable/darktablerc`.

**Comment by aurelienpierre** [comment]
Incoming ! See #2037

**Comment by bapBardas** [comment]
> Incoming ! See #2037

Thanks for this commit Aurélien, and for the improvement you bring to the product !

**Comment by Dpiximaj** [comment]
Font is still very thin and difficult to read even after increase in font size

**Comment by Nilvus** [comment]
@TurboGit : another one to close !

**Comment by TurboGit** [comment]
Closed!
