### ISSUE TITLE
Get GDK multi-threading

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2044]
By default, GDK is using a single CPU thread, which makes it slow, especially on Full HD and 4 K to paint wigets and such.

It can be made multi-threaded by using https://developer.gnome.org/gdk3/stable/gdk3-Threads.html

Good candidates for this are the bauhaus widgets, the darkroom image painting and the lighttable thumbnails.

**Comment by matze** [comment]
Drive-by comment: you will get much worse problems (and a few headaches) than the current performance issues. GTK+ is inherently single-threaded with its main loop and not thread-safe at all (just read the description in that link).

**Comment by aurelienpierre** [comment]
Are you sure nothing can be done ?

**Comment by matze** [comment]
The current approach would be to prepare anything required for display asynchronously in a separate thread through the `GTask` API and display only when the result is ready. [Here](https://www.socallinuxexpo.org/scale7x/sites/scale7x.socallinuxexpo.org/files/Christian_gs.pdf) is a very old presentation (probably from the time this API was designed) that shows the basic workflow. I am not too familiar with the DT codebase so I have no clue how easy or difficult it would be to move to an asynchronous model though …
