### ISSUE TITLE
Ability to disable some modules while in darkroom

### ISSUE THREAD

**Issue by qosch** [darktable-org/darktable#2046]
I have a few modules that I always use by default: the two instances of profiled denoise, chromatic abberations, lens correction and so on.
The sum of these modules slows darktable down quite a bit, though.
I do not find the proposed solution of enabling these modules at last very elegant.

My idea:
Give us a list in the settings where for each module it can be selected under what circumstances it is enabled, e.g. when zoomed in to 100%, when the module is selected or always.

That way I can enable these modules by default on import and they only slow my processing down when I fine tune them or when I work on fine details (zoomed in all the way).

Of course when exporting pictures all enabled modules will be used

**Comment by aurelienpierre** [comment]
That might create more problems than the one it tries to solve, e.g. preview inconsistencies, weird corner cases and such. For example, that would require some sort of head-up display to monitor wether or not said modules are applied. Where do we fit this in the (already cluttered) UI ?

I think it might be better to just bake yourself a style and apply it manually when you are done editing, instead of using auto presets.

**Comment by qosch** [comment]
About the preview inconsistencies I agree, I guess there is no real solution to it. Concerning the UI I had a table like this in a separate tab in the settings in mind:

                                                            Enabled
Module Name                 Always      100%        Module expanded
Profiled denoise                               x               x
Chromatic abberations                     x               x
Base curve                    x
...

**Comment by qosch** [comment]
About the preview inconsistencies I agree, I guess there is no real solution to it. Concerning the UI I had a table like this in a separate tab in the settings in mind:

|                       | always | in 100% view | when module is expanded |
|-----------------------|--------|--------------|-------------------------|
| profiled denoise      |        | x            | x                       |
| chromatic abberations |        | x            | x                       |
| base curve            | x      |              |                         |
| equaliser             | x      |              |                         |
| ...                   |        |              |                         |

**Comment by aurelienpierre** [comment]
Your "when module is expanded" column is linked to GUI code and the state of the GTK widget. We already have a hard time ensuring the "open only one module at the time" global option is respected in the GUI, relying more heavily on it is taking odds at this time. Not that it's a bad idea, but dt's code is not stable enough at this time.

**Comment by aurelienpierre** [comment]
You are welcome. I have something pending for blues and out-of-gamut issues : #2035 But it's bugged for now.

**Comment by aurelienpierre** [comment]
Fixed by the fast pipe option.
