### ISSUE TITLE
[Feature request] Use the one or more selection areas to auto generate the parmetric mask

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#2047]
If you want to create a parametric mask, you have to move the slider manually for one (or more) channels. Color picker helps to estimate where the desired areas to be selected are located on each channel.

Can color picker area be used to auto generate the parametric mask?

The best way to explain what I mean is to give an example.

In this image I would like to mask red and blue berries:

![mask1](https://user-images.githubusercontent.com/38165484/52102876-08fb4680-25e3-11e9-90e0-01d5615de5b8.jpg)

Now I choose an area to mask the red berries. Color and brightness values are read out and the parametric mask is generated:

![mask2](https://user-images.githubusercontent.com/38165484/52102939-82933480-25e3-11e9-9ddd-a69ce2c23be8.jpg)

To this mask I add an additional value by selecting the blue berry:

![mask3](https://user-images.githubusercontent.com/38165484/52103032-ea497f80-25e3-11e9-99a0-e17d1221f612.jpg)

In order to make the mask even more precise, I choose at the end an area that should be subtracted from the mask:
![mask4](https://user-images.githubusercontent.com/38165484/52103192-cb97b880-25e4-11e9-83ee-5d9044e1d01e.jpg)

I have to admit that I'm not a developer and I can't judge whether such a thing would be achievable. However, from a user perspective, I think this would be a great enhancement.

**Comment by aurelienpierre** [comment]
I guess that falls back into U-points, because you would need an extra inclusion/exclusion radius to drive the limits and blending of the parametric range.

It's definitely a good idea, but it needs some thinking, because there is no ready-to-use way to do that already.

**Comment by s7habo** [comment]
Ok. Thanks for feedback @aurelienpierre 

Would perhaps be possible a simplified version of the proposal above? To generate a parametric mask from only one selection area? 
If you take the **area** for the color picker instead of the **point**, you get the limited (inclusion) radius of values for each channel on the sliders. 

For example, for this area (red berry in the upper picture)...

![area](https://user-images.githubusercontent.com/38165484/52151827-a3f03100-2674-11e9-8495-d0ce780bebd9.png)

... the range looks like this:

L channel:

![slider1](https://user-images.githubusercontent.com/38165484/52151650-23313500-2674-11e9-93b1-5cfb1d7c70d4.png)

a channel:

![slider2](https://user-images.githubusercontent.com/38165484/52151759-6db2b180-2674-11e9-9fbe-060ed1602925.png)

b channel:

![slider3](https://user-images.githubusercontent.com/38165484/52151771-760aec80-2674-11e9-8c44-d79eac05a354.png)

Now, you need to **manually** move markers to that indicators to get your parametric mask.

Proposal:

1. Select a specific area using color picker (area)

2. The upper and lower triangular markers are automatically placed exactly on the edge of the indexed area for each channel:
![area2](https://user-images.githubusercontent.com/38165484/52152826-22020700-2678-11e9-8c97-dadb68d2d767.png)

3. To expand **the area** of the mask, press **Shift + scroll mouse wheel** to move **all** triangular markers outwards:
![area3](https://user-images.githubusercontent.com/38165484/52153286-b6209e00-2679-11e9-86b7-1c276d65b258.png)

4. Or, to expand **only the edge** of the mask, press **Ctrl + scroll mouse wheel** to move the **lower** triangular markers outwards:
![area4](https://user-images.githubusercontent.com/38165484/52153374-0f88cd00-267a-11e9-9f36-e6b5df2cd25b.png)

All channels should be simultaneously affected by changes. 

5. If you are not satisfied with your mask afterwards, move the triangular markers manually to the desired result.

**Comment by s7habo** [comment]
@aurelienpierre 

> I guess that falls back into **U-points**

BTW, I remember you asking for the **math behind that**. I found something that might be of interest:

[http://chiakailiang.org/touchtone/](url)

The paper from the site:

[http://chiakailiang.org/touchtone/touchtone.pdf](url)

**Comment by edgardoh** [comment]
(partially) addressed by #2151

**Comment by sacredbirdman** [comment]
At the moment it would be very helpful if we could sample the path that center of the brush stroke creates (with say radius of 10px) and use that to automatically configure the parametric mask (instead of a rectangular area). This would somewhat mimic "auto mask" ability which is well-liked and found in certain other raw editing applications.

**Comment by johnny-bit** [comment]
I'd love to have it at some point and I do agree that it's a complex issue...
