### ISSUE TITLE
Win10: fast snapshot slider rotation crashes the darkroom view

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#2053]
**Describe the bug**
**Fast changing** (rotation) of the snapshot slider crashes the 'darkroom' view. Fast! Slow is fine.

**To Reproduce**
1. Go to 'darkroom view'
2. take a snapshot
3. activate the snapshot
4. rotate the slider bar fast, about 3-4 times
5. The darkroom view crashes and you are back on lighttable view

**Expected behavior**
you can rotate the slider waithout crashing

**Screenshots**
n/a

**Platform (please complete the following information):**
Windows 10 (i3 8Mb / i3/16Mb / i5/8Mb)
Version 2.6.0

**Additional context**
Consistent error on all 3 machines. Not tested on Linux. 

This happens because: I activate the slider, instead of moving it I click it accidentally at the rotation point. I want to get quick back to default - and crash! Doing it slow works fine.

**Comment by aurelienpierre** [comment]
sounds like non-thread-safe GUI code being reset before completion, possibly resulting in double free on pointers.

**Comment by peterbud** [comment]
Confirmed. based on my experience a simple double-click on the rotation symbol is enough to being thrown back to lighttable. However the program does not crash (at least there was no crash for me), but behaves erroneously.

**Comment by TurboGit** [comment]
Yes, no crash just back to lighttable as expected on a double click.
