### ISSUE TITLE
Intel new denoise library

### ISSUE THREAD

**Issue by brigazvi** [darktable-org/darktable#2055]
Intel released new open image denoise library. Based on machine learning.
Maybe we can use it in darktable.
https://openimagedenoise.github.io/

**Comment by TurboGit** [comment]
Quote : "High-Performance Denoising Library for Ray Tracing "

Not sure it applies to pictures.

**Comment by aurelienpierre** [comment]
> It filters out the Monte Carlo noise inherent to stochastic ray tracing methods like path tracing

Camera noise is a combination of gaussian and poissonian noise. Monte Carlo noise is not what we deal with in natural images. You can close @TurboGit
