### ISSUE TITLE
Enable arrow key navigation in sidebars

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2059]
Right now, the darkroom and lighttable sidebars can be scrolled only dragging the sliders with the mouse, or scrolling using the wheel. Both ways, it needs to be done using the mouse.

They need to be scrollable from the keyboard using arrow keys too.

**Comment by dterrahe** [comment]
Arrow keys currently go to the central pane. To support something like this, there would have to be a concept of an "active" pane/module/widget. If we did have active widgets, we could use tab to switch between them (like in any other windowed application; unfortunately we already use tab for something else). So yes, I agree full heartedly that our keyboard support must become more complete. But there are a lot of clashes with our current approach that need to be resolved in a clean way.
