### ISSUE TITLE
double preview triggered when zooming in

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2064]
**Describe the bug**
After zooming in, darktable relaunch the preview processing twice instead of once, resulting in bad performance (UI lag).

**To Reproduce**
1. Launch darktable with `-d perf` option from a terminal
2. In the darkroom, zoom in on the picture from mouse wheel scroll or move (drag) the preview
3. Look at the terminal: 2 reprocessings are triggered, at the beginning and at the end of the mouse event.

**Expected behavior**
Juste one processing is enough. Wait for the mouse event to finish.

**Platform (please complete the following information):**
 - OS: Fedora 29

**Comment by AxelG-DE** [comment]
@aurelienpierre 

I am at 2.7+1087 now and for me it looks like this:

_882,574061 [dev] took 0,000 secs (0,000 CPU) to load the image.
882,577653 [dev_pixelpipe] took 0,003 secs (0,020 CPU) initing base buffer [full]
882,587030 [dev_pixelpipe] took 0,009 secs (0,002 CPU) processed `Raw-Schwarz-/Weißpunkt' on GPU, blended on GPU [full]
882,588016 [dev_pixelpipe] took 0,001 secs (0,001 CPU) processed `Weißabgleich' on GPU, blended on GPU [full]
882,589180 [dev_pixelpipe] took 0,001 secs (0,000 CPU) processed `Spitzlicht-Rekonstruktion' on GPU, blended on GPU [full]
882,616071 [dev_pixelpipe] took 0,027 secs (0,016 CPU) processed `Entrastern' on GPU, blended on GPU [full]
882,618088 [dev_pixelpipe] took 0,002 secs (0,001 CPU) processed `Eingabefarbprofil' on GPU, blended on GPU [full]
image colorspace transform Lab-->RGB took 0,002 secs (0,002 GPU) [basecurve ]
882,623352 [dev_pixelpipe] took 0,005 secs (0,003 CPU) processed `Basiskurve' on GPU, blended on GPU [full]
image colorspace transform RGB-->Lab took 0,002 secs (0,000 GPU) [sharpen ]
882,630845 [dev_pixelpipe] took 0,007 secs (0,000 CPU) processed `schärfen' on GPU, blended on GPU [full]
882,633536 [dev_pixelpipe] took 0,003 secs (0,001 CPU) processed `Ausgabefarbprofil' on GPU, blended on GPU [full]
882,642722 [dev_pixelpipe] took 0,009 secs (0,057 CPU) processed `Gamma' on CPU, blended on CPU [full]
882,642744 [dev_process_image] pixel pipeline processing took 0,069 secs (0,102 CPU)
882,712307 [dev] took 0,000 secs (0,000 CPU) to load the image.
882,712378 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)
882,728214 [dev] took 0,000 secs (0,000 CPU) to load the image.
882,728254 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)_

Sometimes also have 5 times processing at the end:

_946,705230 [dev] took 0,000 secs (0,000 CPU) to load the image.
946,708424 [dev_pixelpipe] took 0,003 secs (0,019 CPU) initing base buffer [full]
946,713785 [dev_pixelpipe] took 0,005 secs (0,003 CPU) processed `Raw-Schwarz-/Weißpunkt' on GPU, blended on GPU [full]
946,715853 [dev_pixelpipe] took 0,002 secs (0,001 CPU) processed `Weißabgleich' on GPU, blended on GPU [full]
946,717420 [dev_pixelpipe] took 0,002 secs (0,001 CPU) processed `Spitzlicht-Rekonstruktion' on GPU, blended on GPU [full]
946,743404 [dev_pixelpipe] took 0,026 secs (0,015 CPU) processed `Entrastern' on GPU, blended on GPU [full]
946,746438 [dev_pixelpipe] took 0,003 secs (0,003 CPU) processed `Eingabefarbprofil' on GPU, blended on GPU [full]
image colorspace transform Lab-->RGB took 0,003 secs (0,002 GPU) [basecurve ]
946,753440 [dev_pixelpipe] took 0,007 secs (0,004 CPU) processed `Basiskurve' on GPU, blended on GPU [full]
image colorspace transform RGB-->Lab took 0,002 secs (0,001 GPU) [sharpen ]
946,761386 [dev_pixelpipe] took 0,008 secs (0,004 CPU) processed `schärfen' on GPU, blended on GPU [full]
946,764057 [dev_pixelpipe] took 0,003 secs (0,002 CPU) processed `Ausgabefarbprofil' on GPU, blended on GPU [full]
946,774276 [dev_pixelpipe] took 0,010 secs (0,073 CPU) processed `Gamma' on CPU, blended on CPU [full]
946,774312 [dev_process_image] pixel pipeline processing took 0,069 secs (0,127 CPU)
946,848018 [dev] took 0,000 secs (0,000 CPU) to load the image.
946,848077 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)
946,857732 [dev] took 0,000 secs (0,000 CPU) to load the image.
946,857788 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)
946,936948 [dev] took 0,000 secs (0,000 CPU) to load the image.
946,936993 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)
947,027523 [dev] took 0,000 secs (0,000 CPU) to load the image.
947,027568 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)_

Is that what you where looking after? Is that still the case for you? 

Sorry if that sound silly to you, but I am actually wondering, how this might be related to "my case" in [#2404](https://github.com/darktable-org/darktable/issues/2404) There I see the whole pixel pipe gets run thru twice just for one WB adjustment and also have this repeatedly pixel pipeline processing at the end...

**Comment by AxelG-DE** [comment]
I strongly feel a relation, as also zooming is WAY more performant in 2.6.2....

**Comment by aurelienpierre** [comment]
> I strongly feel a relation, as also zooming is WAY more performant in 2.6.2....

It should be the opposite actually, because this was fixed in the UI changes in 2.7 (close reprocessings are skipped, hence the operations that took 0.000 sec… computations are actually aborted). So it might be related to something else. 

On my desktop (Fedora 29, GTK 2.24) dt 2.7 master is actually a lot more responsive than 2.6.2 because of this.

**Comment by AxelG-DE** [comment]
Well noted. 
Strange, as Claes does confirm my findings.... I am just now busy filing a new issue and close my #2404... Let's see....

**Comment by AxelG-DE** [comment]
In my opinion, considering  [#2484](https://github.com/darktable-org/darktable/issues/2484) and the related master update to +1099, this can be closed?

**Comment by Nilvus** [comment]
@TurboGit or @aurelienpierre as @AxelG-DE says, this issue seems resolved so could be closed ?

**Comment by TurboGit** [comment]
@Nilvus : thanks for the heads-up, closing indeed.
