### ISSUE TITLE
Rating in darkroom sometimes not working

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2085]
**Describe the bug**
When entering the darkroom, or changing images while in the darkroom, if the mouse is not moved, rating don't work. Color labels are working fine.

**To Reproduce**
Go to darkroom or while in the darkroom change to another image and without moving the mouse try to change the rating.

**Expected behavior**
Rating changes.

**Comment by TurboGit** [comment]
Should be fixed now.
