### ISSUE TITLE
Export selected - file on disk broken

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#2091]
Error when creating a new folder in the module export selected - file on disk (even with no special character).
![dt-export error](https://user-images.githubusercontent.com/23012047/52596428-95fa9700-2e50-11e9-835f-69dfcaea3762.PNG)

If I create the folder outside dt and try to export that doesn't work neither. 
![dt-export error-2](https://user-images.githubusercontent.com/23012047/52596463-a4e14980-2e50-11e9-8f3c-21542e8ef84b.PNG)

 - OS: windows 10
 - Version 2.6.0

**Comment by TurboGit** [comment]
Very very suspicious... as this would mean that nobody would be able to use 2.6 on Windows :) I have no idea of what could be wrong though as I'm not using Windows.

**Comment by aurelienpierre** [comment]
Does it work if you use a directory that already exists ?

**Comment by phweyland** [comment]
I've checked with 2.7, with 2.6 with new database from scratch, I get the same result, for both creating a new folder and exporting for an existing folder (here my desktop).

![dt-export error-3](https://user-images.githubusercontent.com/23012047/52616615-6623b180-2e99-11e9-8865-72f4f9ff4f44.PNG)

**Comment by phweyland** [comment]
-d traces for export to existing folder:

```
[dev_pixelpipe] module `point noir/blanc raw' min: (0.001072) max: (1.057842) [export]
[dev_pixelpipe] module `balance des blancs' min: (0.001311) max: (2.202460) [export]
[dev_pixelpipe] module `reconstruire hautes lumières' min: (0.001311) max: (1.00 0000) [export]
[dev_pixelpipe] module `dématriçage' min: (-0.048494; 0.000000; -0.009361) max:  (1.032105; 1.000000; 1.252111) [export]
[dev_pixelpipe] module `courbe de base' min: (0.000000; 0.000000; 0.000000) max:  (1.004701; 0.999985; 1.034031) [export]
[dev_pixelpipe] module `profil de couleur d'entrée' min: (1.251348; -106.764259;  -79.662918) max: (102.092522; 87.188484; 182.408234) [export]
[dev_pixelpipe] module `renforcer la netteté' min: (-2.761406; -106.764259; -79. 662918) max: (114.538879; 87.188484; 182.408234) [export]
[dev_pixelpipe] module `profil de couleur de sortie ' min: (0.000000; 0.000000;  0.000000) max: (1.155800; 1.229580; 1.197575) [export]
[xmp_attach] C:\Users\Philippe\Desktop\20180212_BH_001.jpg: caught exiv2 excepti on 'C:\Users\Philippe\Desktop\20180212_BH_001.jpg: Failed to open the data source: No such file or directory (errno = 2)'

```

-d traces for creation of a new folder folder:

```
2.192547 LUA ERROR : cannot open C:\Users\Philippe\AppData\Local\darktable\luarc                                              : No such file or directory
```

**Comment by peterbud** [comment]
I have no problem with exporting to an existing or non-existing folder. Would be interested in others as well.

A few questions:
* what is the -d traces switch? for me this command line does nothing:
`"c:\Program Files\darktable\bin\darktable.exe" -d traces`
* with `-d control `I got the following trace:```
```
[run_job-] 08 259401445.790393 23.675839 
load image 100 mip 1 | queue: 1 | priority: 423.676838 
23.676838 [run_job-] 04 259401445.791894 23.677339 load image 98 mip 1 | queue: 1 | priority: 423.677841 
31.674014 [add_job] 0 | 31.674509 export | queue: 3 | priority: 031.674509 
31.675008 [run_job+] 08 259401453.790064 31.675519 export | queue: 3 | priority: 031.676011 
[export_job] exported to `C:\Users\peterbud\Pictures\lakas/test/DSC_0068.jpg'
```
* How do you specify the output folder? Typing in the folder by hand or by using the directory selection button?
* Do you have LUA scripts enabled and if yes which one? Is LUA configured properly?

**Comment by phweyland** [comment]
>     * what is the -d traces switch?

`-d all` sorry for not mentioning. But it works only for 2.7. With official 2.6 I don't get any message.

>    * How do you specify the output folder? Typing in the folder by hand or by using the directory selection button?

Using the directory selection button.

>    * Do you have LUA scripts enabled and if yes which one? Is LUA configured properly?

On my normal dt installation I have lua configured and these scripts:
```
require "official/yield"
require "dt-plugins/maintain-tags"
require "dt-plugins/groupDerivedImages"
require "dt-plugins/OpenInExplorer"
require "BzKevin/enfuse_pro_2"
```
However only those which do not use files seem to work (but slowly apparently)...
And I don't remember how I did configure LUA the first time.

On the testing dt, I often delete darktable local folder to start with a fresh database. On this one there is no lua(rc) file. 

![image](https://user-images.githubusercontent.com/23012047/52694219-3f34b080-2f69-11e9-8b35-eb617d188cf8.png)

In both (2.6) cases I have the same errors both on folder creation and export into an existing folder.

**Comment by phweyland** [comment]
Trying to troubleshot.
1. deleted darktable folder. not luarc file => message:
`1,771488 LUA ERROR : cannot open C:\Users\Philippe\AppData\Local\darktable\luarc: No such file or directory`
2. adding luarc file + some scripts => message:
```
1,875614 LUA ERROR : ...ppData\Local\darktable/lua/dt-plugins/OpenInExplorer.lua:31: module 'lib/dtutils.file' not found:
	no field package.preload['lib/dtutils.file']
	no file 'C:\Program Files\Darktable\bin\..\share\lua\5.3\lib/dtutils\file.lua'
	no file 'C:\Program Files\Darktable\bin\..\share\lua\5.3\lib/dtutils\file\init.lua'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\lib/dtutils\file.lua'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\lib/dtutils\file\init.lua'
	no file 'C:\Program Files\Darktable\bin\..\share\lua\5.3\\lib/dtutils\file.lua'
	no file 'C:\Program Files\Darktable\bin\..\share\lua\5.3\\lib/dtutils\file\init.lua'
	no file '.\lib/dtutils\file.lua'
	no file '.\lib/dtutils\file\init.lua'
	no file 'C:\Program Files\Darktable\share\darktable/lua/lib/dtutils\file.lua'
	no file 'C:\Users\Philippe\AppData\Local\darktable/lua/lib/dtutils\file.lua'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\lib/dtutils\file.dll'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\..\lib\lua\5.3\\lib/dtutils\file.dll'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\loadall.dll'
	no file '.\lib/dtutils\file.dll'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\lib/dtutils.dll'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\..\lib\lua\5.3\\lib/dtutils.dll'
	no file 'C:\Program Files\Darktable\bin\..\lib\lua\5.3\loadall.dll'
	no file '.\lib/dtutils.dll'
```

3. adding lib folder for lua. Scripts start ok.
4. When trying to export an image to an existing folder:
```
[xmp_attach] C:\Users\Philippe\Desktop\20190121_Chartres_001_01.jpg: caught exiv2 exception 'C:\Users\Philippe\Desktop\20190121_Chartres_001_01.jpg: Failed to open the data source: No such file or directory (errno = 2)'
[imageio_storage_disk] could not export to file: `C:\Users\Philippe\Desktop\20190121_Chartres_001_01.jpg'!
```
5. When trying to create a new folder:
![image](https://user-images.githubusercontent.com/23012047/52707417-f2140700-2f87-11e9-9f24-2f5fb5984bad.png)
Here is the trace: [darktable-log.txt](https://github.com/darktable-org/darktable/files/2860075/darktable-log.txt)

I guess that LUA issues are misleading here and `export selected` should work without lua installed, correct ?

**Comment by TurboGit** [comment]
Remove your luarc and try again. This can't be the export module as it works for many people.

**Comment by peterbud** [comment]
Disable LUA. It's very confusing to locate the issue, and my guess is that this is your problem.

Also I have noticed on one of the screenshot your path begins with `C:\\Users` (note the double `\`), on the other screenshot it begins with `C:\Users`.

So disable LUA (e.g no luarc _file_ in your config directory), start with a clean darktable. Import an image. Select the export folder with the directory selection button. Pls note that if you select a folder this way the folder name will contain double `\\` as separators, because houz's variable replacement works only that way...

**Comment by phweyland** [comment]
Without luarc, same issue for both folder creation and export in existing folder.
But, by mistake I've created successfully a `test` folder on C:\. And then export there does work.
So in fact any system folder, C:\users, C:\users\Philippe\desktop or D:\Documents or D:\Documents\Images (that's where my images are), creates an issue.
But when I use a non system folder everything works fine (with or without luarc).

About `\\` or ` \` here is what I have in a working case:

![dt-export ok](https://user-images.githubusercontent.com/23012047/52711026-17f1d980-2f91-11e9-86b9-e9b17a6a52a8.PNG)
![dt-export ok2](https://user-images.githubusercontent.com/23012047/52711049-24763200-2f91-11e9-9ae7-f0ec9b1e88e8.PNG)

**Comment by peterbud** [comment]
4 times `\`? How?
When I select D:\Test\test2 using the button I get this:
![image](https://user-images.githubusercontent.com/7863452/52714063-45428580-2f99-11e9-9781-01d5a4a6db5b.png)

For the without lua scenario: can you send the log pls? The one you have attached before is full of lua messages

Here is my log you can compare:
[darktable-log.txt](https://github.com/darktable-org/darktable/files/2860462/darktable-log.txt)

**Comment by peterbud** [comment]
And one more thing:

> 2.192547 LUA ERROR : cannot open C:\Users\Philippe\AppData\Local\darktable\luarc : No such file or directory

Is perfectly normal as far as I know.

**Comment by phweyland** [comment]
When there is no image in the folder I get the same as you. When there is already an image in the folder I get `\\` or `\\\\` depending the way I open the folder test2.
But that doesn't not prevent export to work.
Two:
![open folder 2](https://user-images.githubusercontent.com/23012047/52719959-fbf93280-2fa6-11e9-8f28-4074f3beb591.PNG)
Four:
![open folder 4](https://user-images.githubusercontent.com/23012047/52720281-96f20c80-2fa7-11e9-963e-8166549837cd.PNG)

Here I've played:
1. failing folder creation (in D:\Documents)
2. failing export into D:Documents
3. successful creation test and test2 on D:\
4. successful export into D:\test\test2

[darktable-log.txt](https://github.com/darktable-org/darktable/files/2860875/darktable-log.txt)

**Comment by phweyland** [comment]
> Is perfectly normal as far as I know

Without lua, that's right.

**Comment by peterbud** [comment]
Based on my experience having 2 `\` or 4 `\` is independent of whether you have images in the folder or not. The per-requisite for having 4 `\` is that the existing export folder on the UI should contain already a drive letter. If that's the case you will get 4 `\` after selecting a different folder even if you have no image in the folder.

At the same time whether 4 or 2 `\`, the export always works, as you have also stated. 

I have also tried with "system" folders like Documents etc, and for me those are working as well.

So first thing to fix : folder selection should be fixed to avoid 4 `\`, even better would be good to avoid even double `\`, because it's rather ugly and confusing. But this is cosmetics, and does not stop the export.

Second thing to fix: What is interesting is that when during export the file is written, and if that is unsuccessful, the return value is not being evaluated, and export will try to add exif data even in case the file creation at the first place was unsuccessful.

here is when the file is created:
https://github.com/darktable-org/darktable/blob/master/src/common/imageio.c#L913

and here is when independent of the success/failure of the file creation, exif data is being added:
https://github.com/darktable-org/darktable/blob/master/src/common/imageio.c#L929

So based on this I believe for you the file creation fails silently in `write_image()`, and then export tries to add an exif data to a non-existing file, and that what you see in the log.

But this still does not explains your problem, and does not help me to repro it still.

Philippe, can you check the permissions for those folders where the export fails? Which accounts have write access to that folder? Can you launch darktable as admin (right click on the stat menu, `More...`/`Run as administrator`, and then try to export to those problematic folders?

**Comment by phweyland** [comment]
> can you check the permissions for those folders where the export fails?

On D:\ all folders Documents as test\test2 have write acces for all authenticated users. I don't see any difference there.

> Can you launch darktable as admin ?

This produces the same effects as for a non admin user (authenticated user).

If you have other ideas to be tested don't hesitate to ask me. Meanwhile I'll have a look at the sources.

**Comment by phweyland** [comment]
> PS: all this worked fine with 2.4.4.

To be sure I've uninstalled 2.6.0 and installed again 2.4.4. .... which has the same issue now.
So the problem is on my system, for some reason I've to discover. Sorry for inconvenience. :-(
Please close the issue.
