### ISSUE TITLE
misplaced "local copy" icon in lighttable zoom mode

### ISSUE THREAD

**Issue by anarcat** [darktable-org/darktable#2092]
**Describe the bug**

The "local copy" icon is misplaced when in "zoom" mode in the light table. It should be in the upper right of the picture (I guess?), at least if it follows the main light table layout. Instead, it clobbers the "G" button.

**To Reproduce**
1. Go to the lighttable view
2. Click on an image, then <kbd>copy locally</kbd> in the <kbd>Selected images</kbd> section
3. Hit the <kbd>z</kbd> key to zoome the image in
4. Try to find the "copied locally" marker

**Expected behavior**

Here is how the image look when zoomed out in the light table:

![image](https://user-images.githubusercontent.com/796623/52604942-c6cfd180-2e3a-11e9-8546-bb47f29580f2.png)

**Screenshots**

Here it what the upper left of the zoomed picture looks like:

![image](https://user-images.githubusercontent.com/796623/52604834-82dccc80-2e3a-11e9-867e-6fb8c49a6deb.png)

**Platform (please complete the following information):**
 - OS: Debian GNU/Linux 10 "buster"
 - Version 2.6.0-1

**Additional context**

I might have modified the keybinding for "zoom". I don't exactly remember, but I suspect I might have switched between <kbd>z</kbd> (lowercase) and <kbd>Z</kbd> (uppercase) to make the "z" key "permanent" (that it "sticks" when you release it). Or maybe that's the default? I'm sorry I forgot that part... :/

**Comment by TurboGit** [comment]
Good catch! Thanks. Should be fixed now.

**Comment by anarcat** [comment]
awesome, thanks for the speedy resolution! :)
