### ISSUE TITLE
Color picker reading is completely off

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2094]
**Describe the bug**
The color measured by the global color-picker is off completely. The tone-curve color-picker is ok. On the example below, the color read on skin is light blue.

**To Reproduce**
1. Pick a color in darkroom with the global color-picker

**Screenshots**
![capture d ecran du 2019-02-12 16-25-35](https://user-images.githubusercontent.com/2779157/52669429-0ef6fe80-2ee4-11e9-9493-147e4b17e21f.png)

**Platform (please complete the following information):**
 - OS: Fedora 29
 - Version master 6ed9ce3cfbd4089c70d14b820f2afc4a431d10ea

**Additional context**
OpenCL off.

**Comment by edgardoh** [comment]
Confirmed.
