### ISSUE TITLE
Metadata editor : auto-completion broken

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2103]
Looking at the code in `/src/libs/metadata.c`, it seems the XMP tags editor in the lighttable is supposed to have an auto-completion feature looking in the database for entries that contains the string being typed, and loading them in the combobox. I don't recall having seen this feature at work, and it is broken for sure now, so the combobox arrows are there for nothing. 

git blame shows @hanatos, @houz, @LebedevRI and @hean01 names, so if anyone can explain to me how it is supposed to work, I can try to fix.

**Comment by amousset** [comment]
I had a look at the code, and completion is only used and actually enabled when mass editing multiple selected images.
