### ISSUE TITLE
Export RAW to JPG impossible.

### ISSUE THREAD

**Issue by ArdubX** [darktable-org/darktable#2104]
I Can't export the RAW files to JPG after treatment. When i press Export, Darktable exporting to the file selectionned of the deck. But nothing appears in the file.

OS : Mac OS Mojave 10.14.2
Darktable : 2.6.0

**Comment by Nilvus** [comment]
@TurboGit : to be closed I think. Quite difficult to answer with so less details. And quite old.

**Comment by TurboGit** [comment]
Closed.
