### ISSUE TITLE
Is pinch zoom on Mac supposed to work?

### ISSUE THREAD

**Issue by snipem** [darktable-org/darktable#2105]
**Is your feature request related to a problem? Please describe.**
Pinch Zoom (https://support.apple.com/en-us/HT204895) does not work in Darktable 2.6.

https://redmine.darktable.org/issues/11482

**Describe the solution you'd like**
Moving around in a picture works just like in any other Mac app. See Apple Link above.

**Describe alternatives you've considered**
Downloading newer version (2.6). I was searching darktable for users talking about this. Only this https://redmine.darktable.org/issues/11482 came up. But now answer was given.

**Additional context**
I'm using macOS Mojave 10.14.1

**Comment by TurboGit** [comment]
No it is not supported on any platform as far as I know.

**Comment by aurelienpierre** [comment]
Touchscreen events are supposed to work with GTK 4.0 which has no release ETA as of now (AFAIK). So we have no way to make that work until they do their job.

**Comment by snipem** [comment]
Touchscreen and touchpad gestures are handled the same way with GTK 4.0?

**Comment by aurelienpierre** [comment]
I have no idea, GTK4 does not even exist yet.

**Comment by aurelienpierre** [comment]
Gtk bug.
