### ISSUE TITLE
Color picker with softproofing displays incorrect color

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#2106]
When activating softproofing with the new "color-space aware" picker, the RGB values displayed seem correct, but the color rendered on screen is incorrect.

**To Reproduce**
1. Select an area with the color picker. Optionally click "add" on the picker panel to remember the area. We get:
![picker-normal](https://user-images.githubusercontent.com/14709/52882837-39a5b900-3169-11e9-878e-da58b2578483.jpg)
2. Choose a histogram&picker profile very different from display profile, eg Linear Rec2020 RGB.
3. Activate softproofing. The color patches change completely:
![picker-softproof](https://user-images.githubusercontent.com/14709/52882838-39a5b900-3169-11e9-9f55-7d467a826009.jpg)

**Expected behavior**
Unless softproofing actually changes the image displayed because of out-of-gamut colors, the color patches displayed in the picker panel shouldn't change. What's expected is that the RGB values displayed as numbers should change, but I guess a conversion from softproof color space to display color space is missing when displaying the color patches.

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version: master as of today.

Cc: @edgardoh, author of #2069 .

**Comment by edgardoh** [comment]
The same rgb value you see on screen is what's sent to the widget, is that value correct?

**Comment by aurelienpierre** [comment]
Still on
