### ISSUE TITLE
OpenCl masks broken?

### ISSUE THREAD

**Issue by chrik5** [darktable-org/darktable#2110]
**Describe the bug**
darktable version: 2.7.0+493~ged0ced2e0

OpenCl starts to fail on export as soon as you use blending with this error message:
[opencl_blendop] couldn't enqueue kernel! -38
[opencl_pixelpipe] could not run module 'exposure' on gpu. falling back to cpu path

**To Reproduce**
1. Open an image in darkroom
2. Activate a module and turn on a blend mode - no matter which one
3. Export the image
4. See error [opencl_blendop] couldn't enqueue kernel! -38 of the module with active blending

**Expected behavior**
OpenCl should not fail.

**Platform (please complete the following information):**
 - OS: Debian
 - Version 9 (kernel 4.19.0-0.bpo.1-amd64; nvidia driver 390.87)

**Additional context**
Reverting commit 7609a0948ba7c5b132e42b5559685611b394f962 prevents OpenCl from failing. 

```
[opencl_init]` opencl related configuration options:
[opencl_init] 
[opencl_init] opencl: 1
[opencl_init] opencl_library: ''
[opencl_init] opencl_memory_requirement: 768
[opencl_init] opencl_memory_headroom: 0
[opencl_init] opencl_device_priority: '0/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl_size_roundup: 16
[opencl_init] opencl_async_pixelpipe: 1
[opencl_init] opencl_synch_cache: 0
[opencl_init] opencl_number_event_handles: 175
[opencl_init] opencl_micro_nap: 500
[opencl_init] opencl_use_pinned_memory: 0
[opencl_init] opencl_use_cpu_devices: 0
[opencl_init] opencl_avoid_atomics: 0
[opencl_init] 
[opencl_init] could not find opencl runtime library 'libOpenCL'
[opencl_init] could not find opencl runtime library 'libOpenCL.so'
[opencl_init] found opencl runtime library 'libOpenCL.so.1'
[opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
[opencl_init] found 2 platforms
[opencl_init] found 2 devices
[opencl_init] device 0 `GeForce GTX 1060 6GB' has sm_20 support.
[opencl_init] device 0 `GeForce GTX 1060 6GB' supports image sizes of 16384 x 32768
[opencl_init] device 0 `GeForce GTX 1060 6GB' allows GPU memory allocations of up to 1519MB
[opencl_init] device 0: GeForce GTX 1060 6GB 
     GLOBAL_MEM_SIZE:          6078MB
     MAX_WORK_GROUP_SIZE:      1024
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 64 ]
     DRIVER_VERSION:           390.87
     DEVICE_VERSION:           OpenCL 1.2 CUDA
```

What else should I do to describe this bug clearer?

**Comment by upegelow** [comment]
Yep, I also experienced this problem. Should be fixed now in master.

Ulrich

Am 16.02.19 um 16:13 schrieb Christian Kanzian:
> *Describe the bug*
> darktable version: 2.7.0+493~ged0ced2e0
> 
> OpenCl starts to fail on export as soon as you use blending with this 
> error message:
> [opencl_blendop] couldn't enqueue kernel! -38
> [opencl_pixelpipe] could not run module 'exposure' on gpu. falling back 
> to cpu path
> 
> *To Reproduce*
> 
>  1. Open an image in darkroom
>  2. Activate a module and turn on a blend mode - no matter which one
>  3. Export the image
>  4. See error [opencl_blendop] couldn't enqueue kernel! -38 of the
>     module with active blending
>

**Comment by chrik5** [comment]
Works now!
