### ISSUE TITLE
Chromatic aberration correction preview is not reliable

### ISSUE THREAD

**Issue by 5N44P** [darktable-org/darktable#2111]
**Describe the bug**
I was trying to do some CA correction on a RW2 panasonic image from the lens correction tab.
I adjusted the sliders until i was satisfacted with the image on the preview. Then i exported the image and the TCA correction was different from the one i viewed on the darkroom preview.

I've noticed that moving around the image in the preview (at max zoom) without touching the TCA parameters, changes quite a lot the look of the chromatic aberration in the image, I attach some screenshots of the same image with the same TCA parameters, shifted around in the preview. Please note how much the aberration changes.

The issue is presented only when the **chromatic aberration module** is enabled.

I've experienced this same issue on windows 10 and linux, version 2.6.0 in linux, if it's important i can chech also which one on windows.

**To Reproduce**
1. Go to darkroom
2. Enable chromatic aberration module
3. Zoom the image and move around
4. See that the CA changes

**Expected behavior**
The CA correction should be consistent for a given feature in the picture, no matter how it's moved.

**Screenshots**
![image](https://user-images.githubusercontent.com/17505995/52915468-bb662580-32d4-11e9-86f0-edfb1d7f87f1.png)
![image](https://user-images.githubusercontent.com/17505995/52915475-c8831480-32d4-11e9-9b6d-36894870bc1d.png)
![image](https://user-images.githubusercontent.com/17505995/52915481-d6d13080-32d4-11e9-9ec9-b8280ee3ce7d.png)
![image](https://user-images.githubusercontent.com/17505995/52915492-fd8f6700-32d4-11e9-85d8-021a44eeb56c.png)

**Platform (please complete the following information):**
 - OS: Solus Linux, Windows 10
 - Version 2.6.0(linux) & 2.4.3 (windows)

**Additional context**
Photo was shot on a panasonic GH3 with a panasonic 12-32 lens

**Comment by AxelG-DE** [comment]
I confirm issues with CA switched on and than zoom, you get weired fringing, while in the full view the effect is as expected.

**Comment by Nilvus** [comment]
@5N44P and @AxelG-DE : Be careful here as it's maybe not an issue but how you use these modules. Lens correction module depend on lensfun support. It have chromatic aberration so adding chromatic aberration module above lens correction module could just add two chromatic aberration so one above another. Of course that will not work correctly as chromatic aberration is an automatic module which will try to correct already corrected aberration.

So, only use this last module if your lens doesn't have TCA correction on lensfun library.
You could verify this on lensfun site : https://lensfun.github.io/lenslist/.
Be sure to select correct version on top of this page. For example, I have 0.3.2 library installed by have update lens correction with lensfun-update-data command so I use develop lens corrections (so I could verify on develop version not 0.3.2).
Here, you could see that your 12-32 lens have TCA correction with lensfun, so don't use chromatic aberration for this lens.

@5N44P : after reading that, think about closing this issue.

**Comment by 5N44P** [comment]
@Nilvus thank you for the reply.  
Do you agree that panning and zooming around a picture shouldn't modify it's CA correction? Because this is the issue here.  

Even though i'm sure that having two concurrent chromatic aberration corrections might lead to unexpected results, i'm not so sure about the connection between the issue presented here and your suggestion.

**Comment by Nilvus** [comment]
> @Nilvus thank you for the reply.
> Do you agree that panning and zooming around a picture shouldn't modify it's CA correction? Because this is the issue here.
> 
> Even though i'm sure that having two concurrent chromatic aberration corrections might lead to unexpected results, i'm not so sure about the connection between the issue presented here and your suggestion.

I'm not sure for panning and zooming but I have never see that. I can't see how chromatic aberration could appear just by panning. For zooming, it just could be possible, like noise, that chromatic aberration are sometimes more viewable on 100% zoom. But that's normal behavior. In general CA are made by lens or by using some modules together like what I suggested.

My comment is really suitable on your issue as when I see history on all your images, chromatic aberration and lens correction modules are both activated. So just test panning and zooming with only one modules (prefer lens correction one of course if TCA is supported by lensfun for your lens).

I suggest you to close this issue as all your images have both modules and made some test again with what I said. If you see it again with chromatic aberration module and a lens which doesn't have TCA support by lensfun, post a new issue with more precise and adapted details.

And be careful on adjusting TCA manually as lensfun have normally calibrated corrections (if made correctly of course). I also have Panasonic hardware (GX8, 12-60 and 100-400 lenses) and I never adjust manually that (both have TCA correction ok on lensfun). That's correct always chromatic aberration and it's ok when I pan or zoom.

Last thing I could recommand, is seeing on lensfun if your lenses are TCA supported. If they are all supported, just forget chromatic aberration module by removing it from your list.

**Comment by 5N44P** [comment]
Thank you for the great usage tips. 
I will do some tests with only one module activate and report back here. 
In the meantime, please take a moment to observe the actual image in the screenshots i've attached to the first post. You'll see the displayed CA changing quite a lot between small pan movements and zooms of the image. 

Please note also that the issue is presented only in the darkroom, the export is always consistent through multiple exports

**Comment by Nilvus** [comment]
> Thank you for the great usage tips.
> I will do some tests with only one module activate and report back here.
> In the meantime, please take a moment to appreciate the shot in the screenshots i've attached to the first post. You'll see the displayed CA changing quite a lot between small pan movements and zooms of the image.

I see that but chromatic aberration and lens correction modules are both activated as I see on history, so it's not reliable as it's. Export could sometimes be consistent, depends on image size export and/or other parameters.

So, your issue have to be confirmed (or not) with just one of the two modules as I've previously described.

I just see that you use old release of darktable. Stable one is 2.6.2 and if an issue remaining after your tests, it maybe could be solved on main development version as lot of things as changed (color, pipeline as seen important reworks).

**Comment by AxelG-DE** [comment]
@Nilvus
>@5N44P and @AxelG-DE : Be careful here as it's maybe not an issue but how you use these modules. Lens correction module depend on lensfun support. It have chromatic aberration so adding chromatic aberration module above lens correction module could just add two chromatic aberration so one above another. Of course that will not work correctly as chromatic aberration is an automatic module which will try to correct already corrected aberration.

Makes a lot of sense, don't dare to think, how often I made that wrong :-) 

I ever thought CA will be measured and the acting accordingly. But yes, now I know better :blush:

TNX

**Comment by upegelow** [comment]
Please have a look into the manual 
(https://darktable.gitlab.io/doc/en/correction_group.html; section 
3.4.4.16) on the inherent limitations of the chromatic aberrations 
module. That module has known shortcomings when it comes to panning and 
zooming and one should better either use the lens correction module 
(preferred if appropriate lens data are available) or the defringe module.

IHMO the chromatic aberrations module is a candidate to being deprecated.

Am 19.05.19 um 14:35 schrieb 5N44P:
> Thank you for the great usage tips.
> I will do some tests with only one module activate and report back here.
> In the meantime, please take a moment to observe the actual image in the 
> screenshots i've attached to the first post. You'll see the displayed CA 
> changing quite a lot between small pan movements and zooms of the image.
> 
> Please note also that the issue is presented only in the darkroom, the 
> export is always consistent through multiple exports
>

**Comment by Nilvus** [comment]
@5N44P : so as @upegelow complete me and answer your issue from panning and zooming, and it's a module to be deprecated, your issue could be closed.
Just use lens correction module only, (for chromatic aberration module, just use it the least possible, only if you have chromatic aberration not corrected by lens correction module).

**Comment by Nilvus** [comment]
@TurboGit : to be closed !

**Comment by TurboGit** [comment]
Closing!
