### ISSUE TITLE
Yellow frame persistance

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2117]
In Lighttable mode, when you move the mouse pointer out from a grouped image, the yellow frame persists even if the next image is not linked with the previous one

**Comment by aurelienpierre** [comment]
I'm working on that in #2037

**Comment by PaoloAst** [comment]
Merci Aurelien !

Sent from my mobile

Il mer 20 feb 2019, 20:15 Aurélien PIERRE <notifications@github.com> ha
scritto:

**Comment by Nilvus** [comment]
@PaoloAst : could you confirm if it's ok now as PR mentioned is merged since more than a month. And if ok for you, could please close it ?

**Comment by PaoloAst** [comment]
I think it is solved. I'm closing the case
