### ISSUE TITLE
missing scroll in style panel

### ISSUE THREAD

**Issue by alglez** [darktable-org/darktable#2130]
**Describe the bug**
When the number of styles to apply goes beyond the limits of the screen,  some styles are not visible/accessible. 

**To Reproduce**
1. Go to Darkroom
2. Open style panel 

**Expected behavior**
In past versions there were some sliders at the edge of the panel to move through the styles

**Screenshots**
![untitled3b](https://user-images.githubusercontent.com/666155/53309828-f7cfed80-38a1-11e9-9d08-cba4c6c2e24f.png)

**Platform:**
 - OS: Manjaro, i3 wm
 - Version: 2.6.0 and .2.7.0.r526.g3a37c58b6-1

**Comment by aurelienpierre** [comment]
Fixed on 3.0.2.
