### ISSUE TITLE
Add "skip" conflict resolution in export module

### ISSUE THREAD

**Issue by Papierkorb** [darktable-org/darktable#2131]
Hello!

**Is your feature request related to a problem? Please describe.**

I usually develop photos in darktable in batches in the same film roll.  I then export these using the export module and process them further in the GIMP.  For that I just give the ready-to-export photos a higher star count, making these easy to select.

However, right now I have to manually track which photos were already exported, as the *On Conflict* options only allow me to **rename** or to **overwrite** existing exported photos.  I don't want already-exported photos to be exported again to save time.

**Describe the solution you'd like**

Add a **Skip** option the the *On Conflict* option.  The conflict should still work on the file name, just the way it already does for the **rename** option.  With the change that instead of renaming the exported file, to simply not doing anything for this specific photo.

I don't think it's necessary to track if a photo has already been exported other than doing a file existence check.

**Describe alternatives you've considered**

I could increment the star count of exported photos, and then adjust the filter option to only see to-be-exported photos.  While possible today, I think it's a bit tedious to do.  This route also requires a "teardown" by me (the user) afterwards, as in, I have to revert the filter option.

Thank y'all for working on darktable!  This is one of the programs I'm always excited when an update arrives, so thanks a lot for your time!

**Comment by tomaszg7** [comment]
I have a similar problem and I often have to alt-tab to image viewer to check if the file was already exported. It would be nice to have some UI indicator showing that (both in lighttable and darkroom mode). Another thing would be to just add "unexported only" to the collection filter.

**Comment by edgardoh** [comment]
Addressed in #2298

**Comment by Papierkorb** [comment]
@edgardoh Thank you!

**Comment by edgardoh** [comment]
You're welcome.

Please close this if you feel is completed.
