### ISSUE TITLE
Darktable crashes on Windows when changing keyboard layout

### ISSUE THREAD

**Issue by asmigala** [darktable-org/darktable#2136]
**Describe the bug**
When changing the keyboard layout on Windows, (either by win+space or by selecting the layout from the taskbar menu, Darktable crashes immediately. There is nothing related to the crash in the debug log when running with `-d all`

**To Reproduce**
1. Have multiple keyboard layouts specified 
2. Open darktable
3. Press win+space
4. Darktable closes

**Expected behavior**
Darktable should remain open

**Platform (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by peterbud** [comment]
Confirmed, same here. I'll try to look into this

**Comment by peterbud** [comment]
I have tested with the latest master and the latest gtk, and it does not crash anymore (both debug and release version was working and did not crash upon keyboard layout change)

So I suggest to test with the upcoming 2.6.1 release.

**Comment by peterbud** [comment]
@asmigala have you had a chance to test this with the 2.6.1 release?

**Comment by peterbud** [comment]
I think we should close this due to lack of response.

**Comment by TurboGit** [comment]
Agreed! People tend to ask others to fix things and dash away without cooperation for us to be able to actually understand/reproduce/fix.
