### ISSUE TITLE
Colour correction with colour wheel

### ISSUE THREAD

**Issue by lyonzy** [darktable-org/darktable#2140]
**Is your feature request related to a problem? Please describe.**
I notice a lot of great photos make use of colour wheel theory, e.g. complementary colours. For an example see [this article](https://digital-photography-school.com/stylize-images-using-complementary-colors-lightroom/) - the author has picked a well balanced scheme with complementary colours in Adobe Colour CC and uses Lightroom to align colours with that. It seems really cumbersome though and it would be nice to have a module like Color Zones but in a wheel format so we could see and adjust an image's main colours on the wheel.

Full disclosure I'm very new to darktable so there might be some relevant features I haven't discovered yet :)

**Describe the solution you'd like**
I'd like something similar to Olympus Workspace, which has this:
![image](https://user-images.githubusercontent.com/11625419/53541243-fede5080-3b6c-11e9-842b-7e73f8696f87.png)

_Note that I've adjusted this to make it look like the feature I've got in my head. It doesn't do point 2 below - it's analogous to the Lightroom HSL tool._

It would:

1. Be able to be put into Saturation or Luminance/Brightness mode (not sure which of Luminance or Brightness is more appropriate)
2. Show the amount of each hue (`sum(S)` or `sum(L or B)`) as the distance of the point/line from the centre (much like a radial graph)
3. Show draggable points at either fixed intervals or local minima/maxima
4. Be able to adjust the amount (Saturation or Luminance/Brightness depending on what mode the module was in) of that hue by dragging a point towards or away from the centre
5. Be able to adjust the hue of pixels at a current hue by dragging a point to a different angle around the wheel - Olympus Workspace does do this:
![image](https://user-images.githubusercontent.com/11625419/53541363-9e9bde80-3b6d-11e9-9393-37048e2af87a.png)

6. Be able to be 'aligned' in some way so that it's easy to see whether maxima are at, say, 30° and 75° rather that 26.4° and 71.4°. Basically it would be nice to see 'relative hue' as well as absolute hue to make maths easier.
7. Show the hue and the `sum` value on hover.

**Describe alternatives you've considered**
The closest features I can think of are Color Zones and the Color Look Up Table. These aren't ideal because it's hard to tell where an image's major colours are on the colour wheel (I know we can look up individual hue values, but it's hard to see all the colours in the image visualised). Also I can't think of any way of even seeing the quantity of each hue in an image (as per formulae in 2 above, or similar) - but I'm not an expert on Color Zones so it might be there somewhere.

In fairness Color Zones does do points 1, 4 and 5 above (albeit in a different way), so maybe this could be distilled down to a 'radial mode' and 'show levels in current image mode' in the Color Zones module.

**Additional context**
Nothing other than great work! I'm very happy with darktable so far :)

**Comment by lyonzy** [comment]
Another similar concept to my point (2) above is a Vectorscope:
![image](https://user-images.githubusercontent.com/11625419/53542228-8463ff80-3b71-11e9-92be-ceebbb6deb2f.png)

Only they seem to be mostly read-only.

**Comment by aurelienpierre** [comment]
I don't like the color wheels to be honest. You basically have 3 axes to control from the tip of your cursor, it's impossible to use them. In pro industries, they have wheel interfaces for color grading because they use physical wheels on hardware control panels: https://www.blackmagicdesign.com/products/davinciresolve/control

But emulating that in soft interfaces would just make things more complicated. Color zones separates your 3D polar nodes into 3 1D linear axes. I think it's the best we can do until we support actual MIDI consoles.
