### ISSUE TITLE
Import from SD card or USB camera shows only the first 96 pictures

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2141]
**Describe the bug**
When trying to import pictures from an SD memory card or from the camera mass storage (connected through USB), the import window only shows the first 96 pictures over 400 total pictures. Since my camera has a dual slot (SD/CF) and I use them in replication, I tested both and the result is the same.

This worked as expected in commit 3a37c58b6e063387e1108912ec62def682cb6a00

**Platform (please complete the following information):**
 - OS: fedora 29
 - Version: master 9820e3b9c1dbb7612f64becab075e1b18181c7b7

**Comment by aurelienpierre** [comment]
This bissects to commit 9820e3b9c1dbb7612f64becab075e1b18181c7b7 by @TurboGit 
```
Date:   Wed Feb 27 22:43:48 2019 +0100

    googlephoto: remove unsued field gphoto_ctx.

:040000 040000 6be72abb734a9091ce8cc3a5989507fd16aaad94 023cfea0d76b3a3ed379ec409e92809fdc93d4d8 M	src
```

**Comment by aurelienpierre** [comment]
Nevermind, it seems a reboot fixed it…

**Comment by TurboGit** [comment]
And it is not possible as I have pushed this AFTER you reported the issue. The commit was done before but I did pushed later.

**Comment by aurelienpierre** [comment]
Yes, I don't get what triggered that bug anyway.
