### ISSUE TITLE
interpolate preview thumbnail from main view instead of computing a whole pixelpipe

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2147]
**Is your feature request related to a problem? Please describe.**
On my system, with CPU SSE codepath, interpolating a whole image at 4K resolution takes about 60-80 ms maximum. The preview thumbnail, in darkroom, can take between 400 ms (just demoisacing) to 2 s to generate (heavy denoising), because it recomputes a whole pixelpipe in parallel.

We should just reuse the resized center image as the thumbnail, and also copy it when moving from the darkroom to the lighttable so it is used there as well.

In addition, the preview thumbnail is recomputed ever when the left panel is collapsed and it is not visible.

Responsiveness matters.

**Comment by junkyardsparkle** [comment]
It does seem like the idea behind the current parallelism kind of falls apart in the real world, but it probably varies widely depending on hardware, so it might be worth trying to get some input from people as to whether anyone actually uses the thumbnail as a "more responsive" feedback while editing. For me, personally, using GPU for main image and CPU for thumbnail doesn't make it very useful in that regard, and I don't use it that way... but somebody, somewhere might.
