### ISSUE TITLE
Monochrome module -- collapse forces on

### ISSUE THREAD

**Issue by visualcurrent** [darktable-org/darktable#2148]
The Monochrome module toggles ON automatically when the module is collapsed regardless of the user turning module OFF.

**To Reproduce**
1. From Darkroom, expand the Monochrome module
2. Make sure the On/Off button is set to OFF
3. Collapse Monochrome module
4. See error: Monochrome has automatically and unintentionally turned on.

**Expected behavior**
All other modules respect the user choice for the On/Off toggle button.

**Platform (please complete the following information):**
 - OS: Windows 10 Home build 1803
 - darktable Version  2.6.0

**Comment by aurelienpierre** [comment]
It does not reproduce on my side. Sorry.

**Comment by peterbud** [comment]
It does show this erroneous behaviour on the Windows version. I'll look into this

**Comment by pphotography** [comment]
I can reproduce this. I've got version 2.6.1 from PPA running on Ubuntu 18.04. See attached video:
[2019-03-28-monochrome.zip](https://github.com/darktable-org/darktable/files/3015638/2019-03-28-monochrome.zip)

**Comment by aurelienpierre** [comment]
Bug about 2.6 version. Feel free to reopen if still present.
