### ISSUE TITLE
missing output profile has been replaced by sRGB!

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#2161]
I have just upgraded to darktable 2.6.1 using the Arch Linux package from the official repositories. Each time I make an image amendment (load an image into the darkroom, switch on or alter a module) I get a popup message saying "missing output profile has been replaced by sRGB!"

**Comment by elstoc** [comment]
I've managed to get the message to stop appearing by manually setting my display profile in the lighttable settings to use a custom icc profile. When I set it back to 'system display profile' (which is how it started after the upgrade) I can't get the popup to reappear.

**Comment by TurboGit** [comment]
So closing.
