### ISSUE TITLE
Command line automatic perspective correction

### ISSUE THREAD

**Issue by guderkar** [darktable-org/darktable#2162]
I want to correct perspective for several images from command line. The problem is that I want to make it automatic without accessing GUI for every one of them. When I create style and then apply it with --style option it will always use same fixed parameters for every image. Is it somehow doable?

**Comment by aurelienpierre** [comment]
> When I create style and then apply it with --style option it will always use same fixed parameters for every image. Is it somehow doable?

No. That would need a rewrite. Also, the detection does not always succeed, so you need to check it manually anyway.

**Comment by shalnoff** [comment]
:+1: really required feature. As well as other "auto" settings. 
Currently it is just impossible to process batch of files with automated parameters, that significantly reduce usability of such great app.

**Comment by thesystemera** [comment]
Yeah we would love this too for one of our automation processes. We are working on a big texture creation project and perspective correction is a much desired aspect to all of this. Any and all advice welcome.

**Comment by softy2k** [comment]
> 
> 
> I want to correct perspective for several images from command line. The problem is that I want to make it automatic without accessing GUI for every one of them. When I create style and then apply it with --style option it will always use same fixed parameters for every image. Is it somehow doable?

Any news about this ?

**Comment by Wikinaut** [comment]
The Windows program ShiftN can do automatic corrections, I use ShiftN on Linux Ubuntu / Linux Mint wrapped in the following shell script:

```
env WINEPREFIX="/home/benutzer/.wine";wine C:\\Program\ Files\ \(x86\)\\ShiftN\\ShiftN.exe "$1" "${1%.*}" A5
# http://www.shiftn.de/ShiftN_Funktionsweise.html
# https://www.shiftn.de/ShiftN_functionality.html see at the command line use
# 1: jpeg
# 2: bmp
# 4: tiff
```

**Comment by Wikinaut** [comment]
before ShiftN
![steglitz](https://user-images.githubusercontent.com/1151915/146849401-598482fc-3929-4c73-8927-9f0d67329a61.jpeg)
after
![steglitz_ShiftN](https://user-images.githubusercontent.com/1151915/146849397-d557488b-d05b-4b29-9147-cd5fa66cbd3e.jpg)
