### ISSUE TITLE
Leica C

### ISSUE THREAD

**Issue by epeeist** [darktable-org/darktable#2164]
Missing support for Leica C RWL files

Trying to open an RWL file from a Leica C generates the message:

"failed to read camera white balance information from `Lnnnnnnn.RWL'!"

Darktable then just spins in the state "working" and consuming CPU

Running version 2.6.1 on OpenSuse Tumbleweed

[L1000006.RWL.zip](https://github.com/darktable-org/darktable/files/2940593/L1000006.RWL.zip)

**Comment by LebedevRI** [comment]
The full sample set should go to https://raw.pixls.us/

**Comment by LebedevRI** [comment]
Please contribute better sample, something daylight with much lower ISO.
