### ISSUE TITLE
Specification of modules.

### ISSUE THREAD

**Issue by joereddington** [darktable-org/darktable#2171]
I'm a budding photographer and I'm interested in finding out what controls like 'highpass' and 'change exposure' _really_ mean. It seems obvious to me to look at the code directly and I've had some luck working out what some controls do, but it's a fairly hard slog.  I'm interested to know if there are test files or specifications lying around for any of the modules? 

If not, I'd also be grateful for any resources anyone might be able to link to that give a really detailed specification of what goes on in these and similar transformations.

**Comment by Nilvus** [comment]
You have tooltips on the software and manual (see darktable.org, blog and resources parts) for that or tutorials on the web. Here it's for issues (so bugs) and feature requests not for how modules or settings works. For discussions, see pixl.us forum.

@TurboGit : to be closed, thanks !

**Comment by TurboGit** [comment]
Closing.
