### ISSUE TITLE
OSX crash with current master

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2172]
crash on launching darktable with current master build (OSX, macports as described in /packaging/macosx/BUILD.txt)
GLib:ERROR:ghash.c:377:g_hash_table_lookup_node: assertion failed: (!g_atomic_ref_count_compare (&hash_table->ref_count, 0))
Abort trap: 6

**Comment by TurboGit** [comment]
You've built it yourself? See #2173

**Comment by MStraeten** [comment]
yes, i built it myself:
darktable --version

```
this is darktable 2.7.0+617~g57b8955d0
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
bit depth is 64 bit
normal build
SSE2 optimized codepath enabled
OpenMP support enabled
OpenCL support enabled
Lua support enabled, API version 5.0.1
Colord support disabled
gPhoto2 support enabled
GraphicsMagick support enabled
OpenEXR support enabled
```

darktable -d all > trace.txt: [trace.txt](https://github.com/darktable-org/darktable/files/2947294/trace.txt)

after deleting content in ~/.config/darktable:
darktable -d all > trace.txt: [trace.txt](https://github.com/darktable-org/darktable/files/2947313/trace.txt)
.txt:

**Comment by TurboGit** [comment]
Please delete: /usr/local/lib/darktable/plugins/imageio/storage/libgphoto.so

It was renamed /usr/local/lib/darktable/plugins/imageio/storage/libgooglephoto.so

Best to completely clean the install directory.

**Comment by MStraeten** [comment]
Thanksfor the solution
