### ISSUE TITLE
Current master hangs at startup

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2173]
I've no additional information, since no message appears.

I'm running on Ubuntu 18.10

**Comment by TurboGit** [comment]
You've built it yourself?

You may try to run:

`$ darktable --version`

To get the actual version. And maybe display all messages to see if something useful is displayed:
`
$ darktable -d all`

**Comment by PaoloAst** [comment]
This is the outuput of --version:

this is darktable 2.7.0+625~gaf997cb8e-dirty
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled


------

This are last two lines of -d all:

29,348651 [sql] /home/paolo/darktable/src/common/image_cache.c:227, function dt_image_cache_write_release(): prepare "UPDATE main.images SET width = ?1, height = ?2, maker = ?3, model = ?4, lens = ?5, exposure = ?6, aperture = ?7, iso = ?8, focal_length = ?9, focus_distance = ?10, film_id = ?11, datetime_taken = ?12, flags = ?13, crop = ?14, orientation = ?15, raw_parameters = ?16, group_id = ?17, longitude = ?18, latitude = ?19, altitude = ?20, color_matrix = ?21, colorspace = ?22, raw_black = ?23, raw_maximum = ?24 WHERE id = ?25"
29,348950 [run_job-] 03 261517252,869981 29,348958 load image 68687 mip 9 | queue: 1 | priority: 429,348962

**Comment by PaoloAst** [comment]
No way. I've tried to rebuild from scratch without success. It hangs after the display of a black window in the middle of the screen

**Comment by PaoloAst** [comment]
We can close this issue, I deleted all the darktable related directories and rebuilt again. Now it works

**Comment by TurboGit** [comment]
Ok.
