### ISSUE TITLE
Haze Removal strange behaviour

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#2175]
Experiencing the following issues with the haze removal module on darktable 2.6.1 on Arch Linux:

If I switch the haze removal module on without changing settings, it seems to apply haze removal correctly to the image.

If I then alter the strength slider on the module, the image no longer shows any effect - it is visually as if the module has been switched off (strength set to zero). If I switch the module on or off, go backwards and forwards in the history stack, or change any of the module settings, it remains as if the haze module is switched off.

However, if I move the strength negative, it does indeed make the image hazier as expected. If I move it back to positive, it is again as if the module is switched off.

If I move the strength slider to the maximum, restart darktable and then reopen the image in the darkroom, the module is correctly applied at its full strength setting. As before, if I then modify the strength slider, the image appears as if the module were switched off.

**Comment by elstoc** [comment]
Same issue on darktable 2.6.0

**Comment by elstoc** [comment]
Sorry. All a little weird. Seems to have stopped happening!!

**Comment by elstoc** [comment]
And back again. Sorry guys. Thought it was fixed. Worked ok for an image for a while. Issue reappeared now but can be worked around by navigating between images while in the darkroom, which seems to force the display to update with the revised haze removal settings. Just have to make haze removal the last thing I do for now.

**Comment by rabauke** [comment]
Can not reproduce the issue. Do debug this further, please mention

- Which version was employed when this problem was observed? 
- How is darktable configured on your system? What are the values of the options `codepaths/openmp_simd` and `codepaths/sse2` and `opencl_*` in `darktablerc` (if present)?

**Comment by elstoc** [comment]
This was on the packaged darktable 2.6.1 on Arch Linux. I'm now on darktable 2.6.2 and (currently) not seeing the issue, though as you can see from the above, it wasn't happening entirely consistently on 2.6.1.

Config values as follows:

codepaths/openmp_simd=false
codepaths/sse2=true
opencl_async_pixelpipe=true
opencl_avoid_atomics=false
opencl_checksum=888092221
opencl_device_priority=*/!0,*/*/*
opencl_enable_markesteijn=true
opencl_library=
opencl_mandatory_timeout=200
opencl_memory_headroom=300
opencl_memory_requirement=768
opencl_micro_nap=0
opencl_number_event_handles=75
opencl_omit_whitebalance=
opencl_scheduling_profile=very fast GPU
opencl_size_roundup=16
opencl_synch_cache=false
opencl_use_cpu_devices=false
opencl_use_pinned_memory=false

**Comment by rabauke** [comment]
Possibly this was just a transient issue. Please report if problem comes up again. Was OpenCL active= (option `opencl=TRUE`)?

**Comment by elstoc** [comment]
I haven't seen this for a while now so I'm closing.

**Comment by bes1002t** [comment]
I have exactly the same issue as described in the initial post. The issue persists for a bunch of images.
Should I create a new ticket?

OS: Fedora 38
DT: Darktable Linux 4.6.1, installed via dnf
