### ISSUE TITLE
Patch not merged in 2.6.1

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2176]
The patch #2030 has been forgotten in dt 2.6.1 while the issue it solves is in 2.6.1 so user experience dark images with filmic chroma preservation on CPU/SSE2

**Comment by TurboGit** [comment]
It was marked in 2.8 :(

**Comment by TurboGit** [comment]
Now merged! Will be in 2.6.2.

**Comment by aurelienpierre** [comment]
or maybe a quick 2.6.1.1 ?

**Comment by TurboGit** [comment]
Sadly not possible. There is nothing like a quick release at this point. We need an announce, to create a new tag for this new release, attach the sources, ask the Windows and MacOS maintainer to create a new release, download them on the release page... etc...
