### ISSUE TITLE
darktable UI small fonts thin and difficult to read - want to change font not just size

### ISSUE THREAD

**Issue by Dpiximaj** [darktable-org/darktable#2177]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. funtoo linux]
 - Version [e.g. 2.6.0]

**Additional context**

**Comment by Dpiximaj** [comment]
version 2.60 &  2.61 Windows version.
![Darktable font prob](https://user-images.githubusercontent.com/48366825/54054758-10e97000-41b9-11e9-86ee-b077d7da113e.JPG)

**Comment by aurelienpierre** [comment]
You might have a problem with Windows Clear Type : https://www.howtogeek.com/howto/28790/tweak-cleartype-in-windows-7/

**Comment by Dpiximaj** [comment]
Yep that was it! Never knew, Thanks.

**Comment by Nilvus** [comment]
@Dpiximaj (or @TurboGit). This issue should be closed, as the issue was resolved.

**Comment by TurboGit** [comment]
Indeed, closing.
