### ISSUE TITLE
Error when try to create a new instance of a module

### ISSUE THREAD

**Issue by dcendal** [darktable-org/darktable#2179]
**Describe the bug**
Every time that I try to create a new instance of a module, the system crashes.

**To Reproduce**
1. Open any file in the darkroom
2. Click on "multiple instances action" of the module Exposure
3. Select New instance
4. Darktable crashes

**Expected behavior**
The module is duplicated

**Platform (please complete the following information):**
 - OS: Ubuntu 18.10
 - Version: darktable 2.7.0+625~gaf997cb8e

**Additional context**
This is the backtrace file
[darktable_bt_ULQOYZ.txt](https://github.com/darktable-org/darktable/files/2948432/darktable_bt_ULQOYZ.txt)

**Comment by edgardoh** [comment]
I can't duplicate on my system, but I'm using the master from this morning. If you haven't already try a fresh build and then start dt with a new database and we'll see from there.

**Comment by dcendal** [comment]
I'm using also the master (last commit af997cb8e942ba89e238e62c35c88b2711af7223).
I delete the database, the current version of the database is 18 (select value from db_info)
Now when the option "multiple instances action" is activated, the only option enabled is "rename", the rest of the options are disabled.
If I click on the option "rename", the situation is very similar to the described before.
[darktable_bt_6V4HYZ.txt](https://github.com/darktable-org/darktable/files/2948866/darktable_bt_6V4HYZ.txt)

I install a new version on 2.6.1 in a new database, everything works OK. Then upgrade to the last master version. Where the UI ask to upgrade to the new database version, click OK. I got the same error as described.

Please, let me know if there is some additional test that I could do.

**Comment by edgardoh** [comment]
With fresh build I mean, before compiling, delete the build directory and the install directory. I you haven't done it please do.

**Comment by edgardoh** [comment]
Never mind, I can duplicate it.

**Comment by edgardoh** [comment]
I have entered PR #2182, please test it.

**Comment by aurelienpierre** [comment]
that worked for me. Actually, there is another click-event to fix, for the reset button.

**Comment by edgardoh** [comment]
No, the reset has two parameters, that's OK.

**Comment by aurelienpierre** [comment]
> No, the reset has two parameters, that's OK.

for now, yes, but the next dude who will try to extend the reset button with a special click will have to figure out why it doesn't behave like the other buttons, and given the noticeable lack of doc, we are not helping him by making a special case. I would just keep it uniform and be future-proof and dev-friendly.

**Comment by edgardoh** [comment]
Clicked is the right event for the reset.
