### ISSUE TITLE
Overexposed module slows down the pipeline a lot

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#2183]
The overexposed module slows down the pipeline significantly, making darktable very painful to use (I have to switch to the 1080p display because it's unusable on the 4K) and often making the preview fall back to CPU.

Here is a -d perf opencl output without overexpose: https://pastebin.com/raw/ntedGNSA (.471s)

With overexpose: https://pastebin.com/raw/Rj7WNKjQ (3.648s)

Version: commit 6188d46 (today) on Arch Linux
GPU: NVidia GTX 1070 (8GB) with opencl-nvidia 418.43-2

**Comment by TurboGit** [comment]
Probably because it now properly report information given the export profile whereas before it was given some "information" not fully correct. Not sure if the speed can be improved.

**Comment by edgardoh** [comment]
There are some improvements that can be made, I'll be working on that.

**Comment by TurboGit** [comment]
This should be fixed now. Thanks Edgardoh.

**Comment by trougnouf** [comment]
It works great, thank you @edgardoh !
