### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [darktable-org/darktable#2184]
Would you like to [wrap any pointer data members](https://github.com/darktable-org/darktable/blob/7680f17053f840315930a43b66955f4fca3e7bc3/src/iop/Permutohedral.h#L58 "Update candidate: HashTablePermutohedral class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by TurboGit** [comment]
No since dt is 99% C and not C++.
