### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [darktable-org/darktable#2185]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [color_picker_helper_4ch_parallel](https://github.com/darktable-org/darktable/blob/3cf1692db56ab5c4dcaca35bb07e15e1aa1eaf90/src/common/color_picker.c#L61)
- [pthread_mutexattr_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutexattr_init.html "Initialize the mutex attributes object.") ⇒ [dt_pthread_mutex_init_with_caller](https://github.com/darktable-org/darktable/blob/7680f17053f840315930a43b66955f4fca3e7bc3/src/common/dtpthread.h#L87)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by aurelienpierre** [comment]
That sounds like a good idea, but the best option is to open a pull request for that. Closing here since it's not a bug or a feature request, but code management.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by parafin** [comment]
Patches are welcome. There a lot of issues in the current code, fixing them all will require a substantial refactoring/rewrite which nobody yet volunteered to put their time into. Just collecting the warning messages won't make a difference in that regard.

**Comment by johnny-bit** [comment]
Hmmm... I do agree with @aurelienpierre that this is mostly about code management.

We have regression tests (which I do need to put inside CI - I already know couple of problems that stem from different compilation flats), benchmarks and skeleton unit testing.

If you want to help with unit testing, please look here: https://github.com/darktable-org/darktable/tree/master/src/tests/unittests - that could be one of contributions possible.

As for static analysis tools: we do have some coding standard that could be adhered too, there's a bit of info about it scattered across the code.
Then there's https://github.com/darktable-org/darktable/blob/master/.clang-format which needs a bit of love ;)

As for the tool usage: currently CI build is set to treat warnings as errors, that's one part of static analysis so anything that compiles is regarded as "should work" (tm). I know from experience that running ANY static code analyzer on any codebase yelds results, so the best approach at introducing static analysis here would be to slowly fix the potential bugs reported by static analysis until there's very little and introduce analysis as part of workflow. Rawspeed has a lot of that, including fuzzing so we do know rawspeed is pretty much stable ;)
