### ISSUE TITLE
osx:dt hangs on applying second user defined style 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2186]
**Describe the bug**
dt hangs after selecting a second user defined style within darkroom

**To Reproduce**
1. cleaned dt install directories  & .config/darktable
2. import raw, open in darkroom
3. apply first style via context menu --> ok
4. select&click on second style

**Platform (please complete the following information):**
 - OS: OSX
 - Version:
this is darktable 2.7.0+659~g36da86baa
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

built with master +pullrequest 2037

**Additional context**
trace of darktable -d all: [style_error.txt](https://github.com/darktable-org/darktable/files/2949734/style_error.txt)
first style: [Canon 5DmIV Monochrome.dtstyle.txt](https://github.com/darktable-org/darktable/files/2949750/Canon.5DmIV.Monochrome.dtstyle.txt)
second style: [Canon 5DmIV Neutral.dtstyle.txt](https://github.com/darktable-org/darktable/files/2949752/Canon.5DmIV.Neutral.dtstyle.txt)

**Comment by TurboGit** [comment]
Try disabling OpenCL you have many errors reported.

**Comment by MStraeten** [comment]
same behaviour with opencl activated or deactivated.
scenario works fine with dt 2.6.1 (with opencl)
my last working build: darktable-2.7.0+575~g68849b1cf (with opencl)
error occurs since my first build requesting a database update (darktable-2.7.0+650~g1b8154372)

**Comment by MStraeten** [comment]
further information: after applying the first style (contains a tonecurve) adding a further toncurve by context menu is deactivated

**Comment by MStraeten** [comment]
recreated the styles with 2.6.1
after opening with 2.7 the database update is done with following messages:
[imageop_init_presets] updating 'tonecurve' preset 'Canon 5DmIV Monochrome' from blendop version 8 to version 9
[imageop_init_presets] updating 'tonecurve' preset 'Canon 5DmIV Neutral' from blendop version 8 to version 9
--> the conversion of the styles seems to be weird

**Comment by MStraeten** [comment]
seems to be fixed with a former commit ...
