### ISSUE TITLE
Wacom doesn't always work

### ISSUE THREAD

**Issue by verysame** [darktable-org/darktable#2188]
When I launch Darktable the first time, my Wacom Intous PTH-651n works fine.
If I close Dartkable and then I reopen it, the Wacom doesn't work anymore. I can use it to move the cursor, but the click doesn't work.

Windows 10 PRO 1809 / Build 17763.348
Darktable 2.6 and 2.6.1

**Comment by Nilvus** [comment]
This PR seems related : #2575

**Comment by aurelienpierre** [comment]
Gtk bug.
