### ISSUE TITLE
current master: compilation error in denoiseprofile.c 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2189]
**Describe the bug**
compilation error:
Scanning dependencies of target denoiseprofile
[ 59%] Building C object src/iop/CMakeFiles/denoiseprofile.dir/introspection_denoiseprofile.c.o
In file included from /Users/martinstraeten/src/darktable/build/src/iop/introspection_denoiseprofile.c:50:
/Users/martinstraeten/src/darktable/src/iop/denoiseprofile.c:1328:17: error: 
      variable 'd' must have explicitly specified data sharing attributes
            if(!d->fix_anscombe_and_nlmeans_norm)
                ^
1 error generated.
make[2]: *** [src/iop/CMakeFiles/denoiseprofile.dir/introspection_denoiseprofile.c.o] Error 1
make[1]: *** [src/iop/CMakeFiles/denoiseprofile.dir/all] Error 2
make: *** [all] Error 2

**Platform (please complete the following information):**
 - OS: OSX
 - Version: Merge pull request #2127: https://github.com/darktable-org/darktable/commit/a31bbc3ad23223bc18e709ad48b5e7c4d6465b33

[console_output.txt](https://github.com/darktable-org/darktable/files/2953712/console_output.txt)

**Comment by TurboGit** [comment]
Can you test the attached patch?And report if it works. Thanks.

[0001-denoiseprofile-fix-build-on-OSX.patch.txt](https://github.com/darktable-org/darktable/files/2953821/0001-denoiseprofile-fix-build-on-OSX.patch.txt)

**Comment by parafin** [comment]
This might be relevant:
https://redmine.darktable.org/issues/12568#note-13

**Comment by MStraeten** [comment]
applied the patch --> compiling successful
