### ISSUE TITLE
Module reordering: random order at picture opening

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2190]
**Describe the bug**
When opening a new picture (no previous history), the modules are ordered in a random inconsistent way. For example, on one picture, you can find the denoise profile applied after the input color profile, but on another one, it will be ok (before the exposure module). Affected modules, so far, are:

* retouch
* exposure
* crop and rotate
* denoise profile
* lens correction.

Note that the pipe order (`darktable -d perf`) is consistent with the GUI one.

**Comment by kikoucalou** [comment]
An unusual comment now appears when export to jpg : 

_[dt_ioppr_check_iop_order] gamma is not the last iop, last is denoiseprofile 1(10,500000) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] module denoiseprofile 1(10,500000) should be after gamma (71,000000) image 0 (dt_dev_modules_update_multishow)
[export_job] exported to `/home/pascalou/Images/2019-03-03/darktable_exported/_IGP9814.jpg'_

Perhaps this bug is in relation ?

dt : 2.7.0+656~gef50c0556

**Comment by edgardoh** [comment]
Can you share the xmp?

**Comment by kikoucalou** [comment]
Yes !

[_IGP9814.PEF.xmp.tar.gz](https://github.com/darktable-org/darktable/files/2958359/_IGP9814.PEF.xmp.tar.gz)

**Comment by edgardoh** [comment]
Works fine for me. to confirm you can run darktable with -d perf and check
on the console that the modules are on the right order.

**Comment by kikoucalou** [comment]
Look working fine and quick: no unusual comment now 
[Dt-d perf.txt.tar.gz](https://github.com/darktable-org/darktable/files/2958765/Dt-d.perf.txt.tar.gz)

**Comment by edgardoh** [comment]
I'm not sure here, maybe someone else can confirm, but I don't see the
gamma here:

95,409639 [dev_pixelpipe] took 0,012 secs (0,012 CPU) processed `filigrane'
on CPU, blended on CPU [export]
95,422555 [dev_pixelpipe] took 0,013 secs (0,013 CPU) processed `filigrane
1' on CPU, blended on CPU [export]
95,422594 [dev_process_export] pixel pipeline processing took 5,664 secs
(47,931 CPU)

I don't remember if gamma is executed on export.

**Comment by TurboGit** [comment]
Cannot reproduce either:

```
[dev_pixelpipe] module `point noir/blanc raw' min: (-0.008601) max: (1.000075) [export]
[dev_pixelpipe] module `balance des blancs' min: (-0.016078) max: (1.362228) [export]
[dev_pixelpipe] module `reconstruire hautes lumières' min: (-0.016078) max: (1.000000) [export]
[dev_pixelpipe] module `dématriçage' min: (0.010517; 0.000000; 0.000000) max: (0.703251; 0.694982; 0.467954) [export]
[dev_pixelpipe] module `réduction bruit (profil)' min: (0.010632; 0.000000; 0.000000) max: (0.703252; 0.694983; 0.467953) [export]
[dev_pixelpipe] module `réduction bruit (profil) 1' min: (0.010632; 0.000000; 0.000000) max: (0.703252; 0.694983; 0.467953) [export]
[dev_pixelpipe] module `exposition' min: (0.025340; 0.000000; 0.000000) max: (1.676106; 1.656398; 1.115304) [export]
[dev_pixelpipe] module `correction des objectifs' min: (0.025340; 0.000000; 0.000000) max: (1.676106; 1.656398; 1.115304) [export]
[dev_pixelpipe] module `profil de couleur d'entrée' min: (27.110384; -40.538998; -11.837816) max: (126.343163; 1.676023; 47.711552) [export]
[dev_pixelpipe] module `balance couleur' min: (25.359760; -37.577957; -11.061406) max: (139.806412; 1.322940; 42.473339) [export]
[dev_pixelpipe] module `renforcer la netteté' min: (24.874491; -37.577957; -11.061406) max: (150.433334; 1.322940; 42.473339) [export]
[dev_pixelpipe] module `profil de couleur de sortie ' min: (-0.108992; 0.000000; 0.000000) max: (1.460245; 1.667390; 1.235941) [export]
[dev_pixelpipe] module `filigrane' min: (-0.108992; 0.000000; 0.000000) max: (1.460245; 1.667390; 1.235941) [export]
[dev_pixelpipe] module `filigrane 1' min: (-0.108992; 0.000000; 0.000000) max: (1.460245; 1.667390; 1.235941) [export]
7.567019 [dev_process_export] pixel pipeline processing took 1.390 secs (2.940 CPU)
```

**Comment by edgardoh** [comment]
This is just a guess, but maybe you edited this image and when saved things
go back to normal. If happens again (on export), before editing copy the
xmp from disk, this message should not happen and with an example I'll try
to fix it.

**Comment by kikoucalou** [comment]
Ok, thanks
