### ISSUE TITLE
Lens Correction for SONY DSC-W1

### ISSUE THREAD

**Issue by JozsefTaborita** [darktable-org/darktable#2200]
In the 2.4.4 version I can set my lens correction **SONY DSC-W1, -> Carl Zeiss, Standard -> mm = 0,0 f/ = 0,0**. With these settings I can correct my lens distortion perfectly.

In the 2.6.0 version I can ONLY set my lens correction **SONY DSC-W1, -> Carl Zeiss, Fixed lens -> mm = 4,3 f/ = 0,0**. With these setting I cannot correct my lens distortion.

I miss the possibility of the setting of **SONY DSC-W1, -> Carl Zeiss, Standard -> mm = 0,0 f/ = 0,0**
Will it be included in the next version? How can I resolve this problem? Is there any workaround to solve this problem? 

![image](https://user-images.githubusercontent.com/36929104/54274553-a9e90400-4588-11e9-907e-aab1becfde76.png)

![image](https://user-images.githubusercontent.com/36929104/54274587-b9684d00-4588-11e9-901c-706cd3de2723.png)

**Comment by Nilvus** [comment]
This module only read and use lensfun library so it's probably related to a lensfun update. I have last update of lensfun (develop database one) and I confirm I just see on the list fixed lens, not standard. So please see here : https://lensfun.github.io/ (you could find a github for lensfun). Maybe it was removed or replaced by the fixed one.

So @TurboGit, as it's not a darktable issue : to be closed I think.

**Comment by TurboGit** [comment]
Closed.
