### ISSUE TITLE
Fail to select by history altered

### ISSUE THREAD

**Issue by denever** [darktable-org/darktable#2207]
**Description**
With darktable 2.6.1 from PPA on Ubuntu 18.10 Cosmic Cuttlefish, trying to reduce selection by "history altered" fails.

**To Reproduce**
1. Go to LightTable
2. In module "collect images" click on pop up menu for current film roll
3. Click on "narrow down search"
4. Use history as selection predicate
5. Select "altered"
6. See error, no selection applied and error in console:

`sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:605, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT a.id) FROM images AS a WHERE   (flags & 256) != 256 AND (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/denever/Immagini/Darktable/20190314_NUDM_2019_8M')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=images.id)) ) ORDER BY filename, version LIMIT ?1, ?2": no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:609, function _dt_collection_compute_count(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:610, function _dt_collection_compute_count(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:605, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT a.id) FROM images AS a WHERE   (flags & 256) != 256 AND (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/denever/Immagini/Darktable/20190314_NUDM_2019_8M')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=images.id)) ) ORDER BY filename, version LIMIT ?1, ?2": no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:609, function _dt_collection_compute_count(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:610, function _dt_collection_compute_count(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:1466, function dt_collection_update_query(), query "DELETE FROM main.selected_images WHERE imgid NOT IN (SELECT DISTINCT id FROM images AS a WHERE   (flags & 256) != 256 AND (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/denever/Immagini/Darktable/20190314_NUDM_2019_8M')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=images.id)) ) ORDER BY filename, version LIMIT ?1, ?2)": no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:1467, function dt_collection_update_query(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:1468, function dt_collection_update_query(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:605, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT a.id) FROM images AS a WHERE   (flags & 256) != 256 AND (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/denever/Immagini/Darktable/20190314_NUDM_2019_8M')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=images.id)) ) ORDER BY filename, version": no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/common/collection.c:605, function _dt_collection_compute_count(), query "SELECT COUNT(DISTINCT a.id) FROM images AS a WHERE   (flags & 256) != 256 AND (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/denever/Immagini/Darktable/20190314_NUDM_2019_8M')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=images.id)) ) ORDER BY filename, version": no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/views/lighttable.c:325, function _update_collected_images(), query "INSERT INTO memory.collected_images (imgid) SELECT DISTINCT id FROM images AS a WHERE   (flags & 256) != 256 AND (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/denever/Immagini/Darktable/20190314_NUDM_2019_8M')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=images.id)) ) ORDER BY filename, version LIMIT ?1, ?2": no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/views/lighttable.c:326, function _update_collected_images(): no such column: images.id
sqlite3 error: /build/darktable-7bxYsm/darktable-2.6.1/src/views/lighttable.c:327, function _update_collected_images(): no such column: images.id`

**Expected behavior**
A selection of only altered pictures is shown.

**Platform (please complete the following information):**
 - OS: Linux Ubuntu 18.10 Cosmic Cuttlefish
 - Version: 2.6.1-0pmjdebruijn1~cosmic

**Comment by TurboGit** [comment]
Should be fixed in master.

**Comment by Gon0S** [comment]
@TurboGit 
Just for your information, 2.6.2 released so far suffer from the same problem.
It looks like the Google Photo/Drive bug that is correctly fixed in master branch but not in version 2.6.2 branch. Really hope it will be ported for next 2.6.3 release.

Best regards.

G

**Comment by TurboGit** [comment]
Sadly I doubt it will in 2.6.3, the bad news is that we have made lot of very extensive changes in master in many part (if not all) of the code. See current RELEASE_NOTES. So at this stage it will be quite difficult to merge changes into 2.6 branch as both have diverged completely.

I understand that I said I'll try to make more incremental releases, but we have never made such massive changes in dt. This bad news is also a quite good news... Next major release will be a formidable one :)

**Comment by Gon0S** [comment]
Wow ! This is a big news ! :-p

Really excited for this next major release !!!
