### ISSUE TITLE
Export from grouped RAW+JPG

### ISSUE THREAD

**Issue by Gon0S** [darktable-org/darktable#2209]
**Describe the bug**
Hello

in previous versions, before 2.6.0 then, when using the export button in lighttable, in grouped view, only the raw file was exported.

In 2.6.0 and latest one, this behaiviour changed, and all files under a grouped raw are now exported.

In order to avoid this export behaviour, I have to switch off grouped view, and only pick the intended and modified raw files in order to export them into jpg final files.

I know it is easy to select only edited raw files, but it stays a cumbersome way of usage against previous behaviour.
Worse part is that switching between grouped files to ungrouped files make the browsing and selection really sluggish as you have to wait until all thumbnails are loaded again and the scroll bar fly all over at a random position in the film roll.

Could it be possible to bring back the previous behaviour ? Or give an option setting to toggle between both behaviour ?

**To Reproduce**
1. Go to lighttable with RAW + jpg files and GROUPING button activated
2. Click on 'export' button
3. If the exported group contain a RAW + a jpg files, you will get 2 files
4. See the target folder and look at the dual jpg coming from the one RAW file (ant its jpg sibling)

**Expected behavior**
only export the grouped RAW file to a jpg. If the grouped jpg file was intended to be export to a jpg, just don't use the group view and select it explicitly to export the modified jpg to target

**Platform (please complete the following information):**
 - OS: Solus Project Linux
 - Version 2.6.0 or 2.6.1

**Comment by LiranV** [comment]
I also suffer from this new behavior.
This is caused due to changes in the way Darktable treats grouped images.
A clean solution will probably be to add a selection in the export dialog, between exporting the "group leader" or all the images in the selected group.

**Comment by jansilar** [comment]
I would also love to have this fixed. Thanks.

**Comment by aurelienpierre** [comment]
Exporting from a group is ambiguous, the behaviour described here is logical. Narrow-down the selection in collection by selecting only the raw files in lighttable, then export.
