### ISSUE TITLE
distorted mask not correct

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#2210]
**Describe the bug**
This is not a new issue, but we may want to revisit it. I've never been able to fix it personalty.

**To Reproduce**
1. Open the attached picture in darkroom
2. Activate the monochrome
3. Create a selection on the green square (or use attached .xmp)
4. The square is grey, all ok
5. Activate the perspective correction module and set rotation to 10
6. All OK, the mask is distorted and still cover all the square
7. Activate liquify, and add a single node pushing on one of the face of the square

Here is the issue, the mask is distorted but not correctly and so some green part of the square are not now covered.

8. If the perspective correction module is deactivate then all is OK.

So the issue is only when Liquify and perspective correction are used together.

**Expected behavior**
Mask properly distorted and the green should never be visible.

**Screenshots**

Initial  image with mask:

![Capture d’écran de 2019-03-14 14-56-27](https://user-images.githubusercontent.com/467069/54362725-bc873a00-4669-11e9-9630-d5da38a73a38.png)

With perspective correction:

![Capture d’écran de 2019-03-14 14-56-37](https://user-images.githubusercontent.com/467069/54362740-c610a200-4669-11e9-86bb-f33b9d38aee5.png)

With Liquify:

![Capture d’écran de 2019-03-14 14-56-44](https://user-images.githubusercontent.com/467069/54362749-cb6dec80-4669-11e9-8f54-2f8f9c16827c.png)

With both:

![Capture d’écran de 2019-03-14 14-56-50](https://user-images.githubusercontent.com/467069/54362755-cf9a0a00-4669-11e9-85df-c56b23973753.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Version all up to now

**Comment by TurboGit** [comment]
The files to reproduce:

[distmask.jpg.xmp.txt](https://github.com/darktable-org/darktable/files/2966773/distmask.jpg.xmp.txt)
![distmask](https://user-images.githubusercontent.com/467069/54362892-1556d280-466a-11e9-8bf3-932d9c4d96e9.jpg)

**Comment by TurboGit** [comment]
@edgardoh : given your recent work on the pixel-pipe and mask you may have an idea?

**Comment by edgardoh** [comment]
When updating the iop's I have noticed that the liquify and perspective
correction work different than the other distord modules (and it was more
difficult to port!), probably because the position on the pipe.

Now that modules can be re-ordered we should check if distord modules need
a particular order, but it will be nice if they can be moved anywhere. I'll
take a look at this, maybe there's something generic that can be made.

**Comment by edgardoh** [comment]
I've been playing with the distord modules and everything seems fine, there's some issues but they seem module related.

For this specific one I don't know the code so I can't really follow it, but it seems that the liquify don't like when a distord module is before in the pipe.
The crop & rotate with an angle or the lens correction show the same problem as the perspective correction, but between them things are OK, so I'm taking a wild guess and assume is the liquify.

It seems that the liquify is not applying the same distortion on the process() than in _distort_xtransform(), so modules that follow and use a mask get the mask with the incorrect distortion. 
Maybe _distort_xtransform() is not applying the distortion from the previous modules?

As a side note, the process() and process_cl() should use MIN(roi_in->width, roi_out->width), MIN(roi_in->height, roi_out->height), as the input image can be larger or smaller than the output (I had a few crashes)

I hope this helps.
