### ISSUE TITLE
modules from user generated styles arent persisted in history stack

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2212]
**Describe the bug**
after restarting darktable modules assigned by user defined style aren't in history stack

**To Reproduce**
1. clear .config/darktable
2. import 2 files
3. apply a toncurve to the first file
4. create a style based on the first file (select tonecurve)
5. apply the style to the second file
6. close darktable & reopen
7. open first file in darkroom --> tonecurve is applied
7. open second file in darkroom --> tonecurve isnt in history stack

**Platform (please complete the following information):**
 - OS: osx
 - Version: master with pr 2037
this is darktable 2.7.0+724~ge13baa5d8-dirty
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by edgardoh** [comment]
Confirmed.

**Comment by TurboGit** [comment]
Could this have been fixed by #2242 ?

**Comment by MStraeten** [comment]
seems to be fixed - thanks
