### ISSUE TITLE
Zoomable light table extends in every direction and outside of available range, thumbnails are gone from lightable

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#2215]
I'm not sure how the "zoomable light table" is intended to work but the current behavior seems counterintuitive, zoom lv >1 causes images to expand both vertically and horizontally outside of the screen boundary (also it allows to continue pressing the arrow keys outside of the image range)

My biggest issue with this update is that the thumbnail previews are gone from lighttable. My typical use is "file manager" mode where i can ctrl+wheel to zoom in/out and wheel to browse, or click on a thumbnail to jump to it, but it looks as if the thumbnails have been replaced with a timeline and removing the timeline doesn't restore the thumbnails.

The expose view is close to being very useful, it shows the images in fill size and the thumbnails are clickable on the bottom, but the arrow keys and mouse wheel are not active there and clicking on each image is too tedious for practical browsing.

Screenshots from zoomable light table:
![vert-hor-expansion](https://user-images.githubusercontent.com/6899116/54440671-79959700-473b-11e9-985b-296405bd6a21.png)
![going-out-of-range](https://user-images.githubusercontent.com/6899116/54440670-79959700-473b-11e9-9433-65d27d57fdbf.png)
![zoom1-out-of-range](https://user-images.githubusercontent.com/6899116/54440669-78fd0080-473b-11e9-9acd-3332a4703b32.png)

**Comment by TurboGit** [comment]
All this is normal. Please read the doc.

Also which version? And please a reported issue should have a single issue described. Here you are mixing exposé, zoomable view, arrow use...
