### ISSUE TITLE
Replace the byte-skull for unreadable files

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2222]
Putting a byte-skull graphic for unreadable files is subjective taste. A simple X is enough

**Comment by matze** [comment]
"A simple X" is subjective taste.

**Comment by johans3** [comment]
It's not and i teach you why, matze. 
X is minimal. A kind of space invaders skull for unreadable files is not minimal. Maybe you're still playing that kind of games and therefore you like this kind of "pixel art"

**Comment by Nilvus** [comment]
If we use darktable on the good way (i.e., manipulating files only darktable), we can't have skull graphics appear (or rarely). So I personnaly consider that developer have more important things to do than changing graphics.

But if you don't like that, you could search on source code where is the file contains this image and change it for you own use.

**Comment by TurboGit** [comment]
That's the way it has been done by the original author.

**Comment by johans3** [comment]
If that resource is available as simple file inside the application bundle OK. I'll take a look. 
Agree it's low priority. Mac is another Linux but still... I see that skull more often. Most files are visible the expected way fortunately
