### ISSUE TITLE
Reference pictures back to our default file manager application

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2229]
Sometimes would be nice to right click a picture in lighttable and click "show original" (picture) to get the original file but displayed in our default file manager application

**Comment by Nilvus** [comment]
This is possible in another way by cloning functions.

**Comment by johans3** [comment]
Is this documented somewhere, please? 

Would be very useful to have a search field able to check the whole online user manual  :)

**Comment by Nilvus** [comment]
It is documented on manual yes. You could download the manual in PDF on darktable.org (resources). Searching is easy on PDF.

**Comment by TurboGit** [comment]
You want to see the original over the current thumbnail? Right? That would be handy indeed.

**Comment by johans3** [comment]
Hmmm no 
I rather thought at a command able to reveal the original file on hard drive. Darktable is self sufficient I like that. 

Talking about right click it wondered getting no contextual menu options hovering over pictures. Maybe just a weight less.
