### ISSUE TITLE
Unable to select and confirm pop-up-menu entries

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2231]
I'm able to open Pop up menus with click, but unable to select a different menu item in the pop up, when I hover on another menu item my move is ignored, the menu entry rests grayed out (inactive). Definitely a bug. 

The work around I found is to select with the directional keys up/down and confirm with enter.

**Comment by TurboGit** [comment]
Well let me be clear. I'll close all your tickets as I don't have time answering all the questions that are already in the manual.

Now, please read the manual, from first page to last one. And come back with some real issues.

**Comment by johans3** [comment]
It seems a not working pop-up is correct behavior in darktable. I don't think my text was unclear. 
The bug I described should be a "feature"?
Sounds not very serious. The Mac users on this tracker aren't much so you can't understand what works fine because you're using Linux system.

**Comment by johans3** [comment]
This report addresses a bug not a feature
Bugs aren't described in your manual, such a thing would be ridiculous. 

Did you check THIS issue reported here *on Mac*?

**Comment by parafin** [comment]
This issue existed, but was fixed at some point with GTK update. In any case it's not a bug in darktable.

**Comment by johans3** [comment]
OK. Some pop up, the filter (upper menu) menu work, but it's also inconsistent (it doesn't stay open but after some clicks). Not so for the pop-ups in the modules, there I'm unable to click-select entries, with my mouse. Luckily the keyboard input works

It's platform related. At the end of the day a little annoyance but nothing disrupting. I'm  happy you made a package available for Mac. : )

**Comment by parafin** [comment]
Dunno, those popups work for me too. Tested on latest macOS with 2.6.2 DT release DMG.
Workaround that worked before is to move mouse inside the popup, then outside, then back inside, after that menu selection used to start to work.

**Comment by johans3** [comment]
My machine runs 10.11 and that's the last update I could install. Of course it's not possible to make everything backward compatible. I see.

Your tip worked for me! Maybe an useful note for the manual
