### ISSUE TITLE
Double click to confirm a selection

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2232]
When I select a picture from the film-roll (the menu at the bottom) in darkroom, then I expect darktable to open the new selection instantly. 
There's no need for a double click, really.

**Comment by Nilvus** [comment]
Read the manual, please, read the manual. One tap on one touch of your keyboard is also possible. And simple click has is used for another function. So, please read the manual before posting issue that are not one. Not your first in just few hours...

**Comment by johans3** [comment]
I guess users writing on this bug tracker care about Darktable. Duplicates occur and some topics aren't repeated enough. 

There is also a difference between platforms. Stuff perfectly working on one system may not, on another. Not sure how many of you use Macs.
