### ISSUE TITLE
Generic world map when offline

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2233]
I'd like to have a genetic world map for the pictures which have Geo location coordinates. 
Right now I see just a bunch of pictures on a white screen :(

**Comment by Nilvus** [comment]
I would not ! I prefer saving space for photos.

**Comment by johans3** [comment]
@Nilvus
I didn't say anything about a high resolution map. 
A very simple map with some zoom-able detail is suffice and won't kill Darktable

**Comment by johans3** [comment]
I know the online map is precise and perfect. But what if I'm offline? 

What about a vector map just to have a rough idea where on the planet we took the pictures? What says the community?
