### ISSUE TITLE
Genetic Frame around unselected pictures useless

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2234]
The generic grey frame around every picture in the lighttable list makes me think that everything is selected. 

Why not using the common Black theme and make things clearer for un-selected items?

**Comment by Nilvus** [comment]
We already said that to you. Please read and stop using issues that are not ones or are already work in progress. This is not a forum but a place to post unknown issues. That's part of UI rework like a lot of graphics improvement.
