### ISSUE TITLE
color picker in lookup table doesnt mark best fit patch

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2235]
**Describe the bug**
clicking the color picker icon beneath color lut patches and then selecting an area within the picture selected the nearest patch in 2.6.1 but not in 2.7.0+717~g5c40fc801

**To Reproduce**
1. Go to 'darkroom'
2. select module 'color look up table'
3. click on color picker icon
4. select area within picture

**Expected behavior**
the nearest patch ist selected (white frame inside)

**Platform (please complete the following information):**
 - OS: OSX
 - Version 2.7.0+717~g5c40fc801

**Comment by MStraeten** [comment]
quite strange: if i click on the color picker icon, draw a area and then activate 'restrict histogram to selection' the in the color picker module, the selection of the proper patch is successful. evean after deactivataing it.

**Comment by MStraeten** [comment]
no longer reproducible

**Comment by victoraalvarez** [comment]
Has there been a resolution to this? Having this issue on Mac.
