### ISSUE TITLE
DB conversion mess up retouch in iop order

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2238]
**Describe the bug**
after database conversion 2.6.1 --> 2.7.0 the module retouch is misordered:

[dt_ioppr_transform_image_colorspace] module retouch must be between input color profile and output color profile

**To Reproduce**
1. clean .config/darktable
2. open file in darkroom and apply retouch in dt.2.6.1
3. click display wavelet scale --> fine
4. close dt2.6.1. open dt 2.7.0, confirm db conversion
5. open file in darkroom expand module retouch, click display wavelet scale
4. messed up display

**Platform (please complete the following information):**
 - OS: OSX
 - Version:
`this is darktable 2.7.0+753~gb320074dc
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
`

**Comment by edgardoh** [comment]
Does this happens only on darkroom or on export too?

If you import the original xpm, can you still reproduce the issue?

**Comment by MStraeten** [comment]
only if clicking display wavelet scale --> the image turns red
export --> the retouch is applied as expected
same misbehaviour with discard history stack and reload xmp as written by 2.6.1

**Comment by edgardoh** [comment]
Can you share the xmp?

**Comment by MStraeten** [comment]
[20190223-IMG_5936.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/2975145/20190223-IMG_5936.CR2.xmp.txt)

**Comment by edgardoh** [comment]
The problem was not the db conversion, so you don't need to convert it again.

**Comment by MStraeten** [comment]
thanks for the fix
