### ISSUE TITLE
basic adjustment applied before input profile

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2241]
**Describe the bug**
if already the 'input profile' is set in the history stack due to usage of a style a later applied basic adjustment is processed before input profile messing up the image

**To Reproduce**
1. open image in darkroom 
2. apply attached style to a picture ([Canon M6 Neutral.dtstyle.txt](https://github.com/darktable-org/darktable/files/2975600/Canon.M6.Neutral.dtstyle.txt))
2. apply basic adjustment

**Platform (please complete the following information):**
 - OS: OSX
 - Version:
this is darktable 2.7.0+755~gac7648cff
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Additional context**
xmp file: [20190317-IMG_3634.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/2975603/20190317-IMG_3634.CR2.xmp.txt)

**Comment by edgardoh** [comment]
This is a current limitation, see the error message on the command line.

I'll eventually do something about it, but I'm working on other things right now.

**Comment by MStraeten** [comment]
fixed
