### ISSUE TITLE
[haze removal] Makes image to bright now

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#2243]
**Describe the bug**
I've just worked on a photo from last year, then I noticed that one photo in my collection is too bright now.

I'm running git sha: 195f5a3b2

The haze removal shifts the histogram to the right making everything brighter ...

Haze removal on:
<img src="https://xor.cryptomilk.org/pics/x/darktable_haze_removal_on.png" />
https://xor.cryptomilk.org/pics/x/darktable_haze_removal_on.png

Haze removal off:
<img src="https://xor.cryptomilk.org/pics/x/darktable_haze_removal_off.png" />
https://xor.cryptomilk.org/pics/x/darktable_haze_removal_off.png

**Comment by edgardoh** [comment]
Can you share the original xmp and this one?

**Comment by cryptomilk** [comment]
Only the XMP?

**Comment by cryptomilk** [comment]
You can find it here: https://xor.cryptomilk.org/pics/x/2018-07-25__7M33756.ARW.xmp

**Comment by edgardoh** [comment]
Is this the original one?

**Comment by cryptomilk** [comment]
I can roll back to the version I edited with an older darktable version, if you want that ...

**Comment by cryptomilk** [comment]
https://xor.cryptomilk.org/pics/x/ now has new and orig

**Comment by edgardoh** [comment]
I don't get it, I though this was an old edit that when migrated looks
different. Is not that the case?

**Comment by cryptomilk** [comment]
I've did the edit of that picture last year. Today I've opened the collection and noticed that the image is too bright now. Then I clicked through the history stack and when I deactivated the haze removal, it went back to normal. Then I just turned the haze removal on and off and saw that the module shifts the histogram to the right (see screenshots).

**Comment by cryptomilk** [comment]
This is the untouched file, I just checked out from my git tree: https://xor.cryptomilk.org/pics/x/2018-07-25__7M33756.ARW.xmp.orig

With that file I get a too bright image cause by the haze removal.

**Comment by cryptomilk** [comment]
Do you want the RAW file too to reproduce it?

**Comment by edgardoh** [comment]
With a random image I can't duplicate, but to be sure can you try it with a
2.6 release? Doesn't seem to be related to the module order as the haze
removal is before the colorin.

**Comment by cryptomilk** [comment]
With 2.6.1 everything is fine: https://xor.cryptomilk.org/pics/x/darktable_2.6.1_haze_removal.png

**Comment by cryptomilk** [comment]
OK, in darktable from master, if I go back in the history stack and click around at one point it is fine. But then as soon as white balance is activated (which comes after haze removal in the history) it is going mad.

**Comment by cryptomilk** [comment]
Ok, I can reproduce it.

Go back in the history to 6 and apply 7 and 8. Then haze removal is working. Now apply 9 and 10 (white balance) and it is going to bright.

The tone curve in 6 seems to reset it to a normal state, and the white balance in 10 seems to mess it up.

**Comment by cryptomilk** [comment]
I can send you the RAW it might be dependent on that data.

**Comment by edgardoh** [comment]
I can't find anything that explain this. 
The haze removal and white balance seem to have commits that are not included in 2.6, you can try with a previous commit, at least to see where the problem is.

**Comment by cryptomilk** [comment]
I can try doing a `git bisect`. It normally works fine as long as you don't use merge commits.

**Comment by rabauke** [comment]
@cryptomilk Can not reproduce the issue. Do debug this further, please mention

- Which version was employed when this problem was observed? 
- How is darktable configured on your system? What are the values of the options `codepaths/openmp_simd` and `codepaths/sse2` and `opencl_*` in `darktablerc` (if present)?

**Comment by cryptomilk** [comment]
I've sent you details via e-mail.

**Comment by cryptomilk** [comment]
@rabauke Did you have some time to look into this?

**Comment by rabauke** [comment]
@cryptomilk Thanks for sending me the raw file. I was, however, not able to reproduce the issue with current git master. Everything looks reasonable, with and without OpenCL enabled.

![Bildschirmfoto](https://user-images.githubusercontent.com/1159508/58734064-a54d2280-83f6-11e9-9a5c-3cb7e00d876e.png)

Side remark as the sky in your picture is almost completely blown out: The haze removal module searches for the brightest pixel among the most hazy pixel to estimate the brightness and the color of the diffuisive background light. Overexposed pixels can be identified erroneously as bright hazy pixels, which may lead to strong artifacts.

**Comment by cryptomilk** [comment]
Thanks for investigating. I will check again.
