### ISSUE TITLE
failing sed command on OSX in tools/io-layout.sh

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2244]
**Describe the bug**
BSD sed on OSX requires an additional "" after -i option: 
sed -i "/plugins\/darkroom\/group_order\//d" $FILE
--> invalid command code m

sed -i "" "/plugins\/darkroom\/group_order\//d" $FILE
--> works fine
(same with the second sed command)

I'm not sure if this is also fine with gnu sed, maybe this is a bsd specific problem ...

**Comment by TurboGit** [comment]
To me the second version makes no sense! I bet it just does nothing on the file.

**Comment by MStraeten** [comment]
on osx it reorders the iop modules - seems to be a bsd specific behaviour

**Comment by TurboGit** [comment]
Show the doc please, as I said the fix makes no sense to me.

**Comment by MStraeten** [comment]
I found the workaround here: 
https://markhneedham.com/blog/2011/01/14/sed-sed-1-invalid-command-code-r-on-mac-os-x/
Now i found also https://unix.stackexchange.com/a/131940 stating this is osx specific 
So the issue can be closed
