### ISSUE TITLE
segfault if using opencl in rgbcurve if inputprofile is set via style 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2245]
**Describe the bug**
applying a mask in rgbcurve results in a segmentation fault if 
- opencl ist activated and 
- a mask within a different module is already defined 
- and input profile is set via applied style .
i found it not beeing reproducible if the colorin section of the attached xmp file is deleted 

**To Reproduce**
1. open file
2. add 'exposure' and apply a gradient mask
3. add 'rgb curve' and apply a gradient mask
4. add style [Canon M6 Neutral.dtstyle.txt](https://github.com/darktable-org/darktable/files/2980421/Canon.M6.Neutral.dtstyle.txt)

resulting xmp file: [20190223-IMG_5937.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/2980445/20190223-IMG_5937.CR2.xmp.txt)

58,034366 [dev_pixelpipe] took 0,275 secs (0,752 CPU) processed `Entrastern' on GPU with tiling, blended on CPU [thumbnail]
[dev_pixelpipe] module `Entrastern' min: (0,000512; 0,000000; 0,000000) max: (0,620160; 0,617545; 0,618875) [thumbnail]
58,034740 [opencl memory] device 0: 290400 bytes (0,3 MB) in use
58,035256 [opencl memory] device 0: 580800 bytes (0,6 MB) in use
58,036358 [opencl memory] device 0: 581056 bytes (0,6 MB) in use
58,036382 [opencl memory] device 0: 653656 bytes (0,6 MB) in use
58,036457 [masks Verlauf #1] gradient draw took 0,0001 sec
58,036472 [masks Verlauf #1] gradient transform took 0,0000 sec
58,036564 [masks Verlauf #1] gradient fill took 0,0001 sec
58,036612 [masks 0] combine took 0,0002 sec
58,036618 [masks] render all masks took 0,0002 sec
58,036631 [opencl memory] device 0: 726256 bytes (0,7 MB) in use
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Abort trap: 6
full console output: [opencl_mask_rgbcurve.txt](https://github.com/darktable-org/darktable/files/2980451/opencl_mask_rgbcurve.txt)

**Platform (please complete the following information):**
 - OS: OSX
 - Version
this is darktable 2.7.0+769~gb311cd37c-dirty
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by edgardoh** [comment]
I'm working on this, until then do not use the rgb curve or the basic
adjustments before the input color profile.

**Comment by MStraeten** [comment]
works fine, thanks for the fix
