### ISSUE TITLE
New non-CIELAB pipe breaks the darktable-chart utility

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#2252]
Previously, the `darktable-chart` utility made use of [a "hidden" darktablerc option to enable a no-op output color profile which dumped the CIELAB data directly to a file](https://www.darktable.org/usermanual/en/darktable_chart_making_input_images.html). The recent changes to the pipeline in the master branch have broken this "feature". Prior to any 2.8 release, this should probably be addressed somehow.

**Comment by TurboGit** [comment]
Broken how? Crash? Wrong output? A simple way to reproduce?

**Comment by junkyardsparkle** [comment]
I'm sorry, I thought the link would make it clear. With current master, if you follow those steps for producing a file (using the "hidden" Lab output color profile), you don't actually get the expected Lab output (because the output profile is based on assumptions about the old pixelpipe).

Since the new pixelpipe allows module reordering and different working colorspaces, the solution for this may not be simple.

**Comment by TurboGit** [comment]
I know what is inside the link and I did use darktable-chart, but when you say broken nothing can be guessed. We need to know more, don't expect us to spend hours to understand what is wrong.

That's why I have asked if is was a crash or a wrong output. That's as simple as that. Now I have the answer I think, the output must be wrong at export when exporting in Lab.

**Comment by junkyardsparkle** [comment]
> We need to know more, don't expect us to spend hours to understand what is wrong.

Again, I'm sorry, I don't really expect anyone (other than maybe the author of darktable chart) to think about this too much *right now*. I just wanted to create a "memo" about a peripheral issue (the nature of which I thought was fairly obvious) so that it wouldn't be overlooked prior to 2.8 release... maybe there's a better way to have done that?

**Comment by TurboGit** [comment]
I don't think that's a darktable-chart issue, we probably want to have a solution for this as it is quite important. I suppose Edgardoh will have a look at this at least to devise a possible solution.

**Comment by edgardoh** [comment]
No idea what the issue is, how to duplicate it and why it is assumed that the pipe is the cause.

**Comment by TurboGit** [comment]
Right, please junkyardsparkle can you describe the exact steps to reproduce. And what you get as output and what you would have expected. Thanks.

**Comment by junkyardsparkle** [comment]
Ok, I just did a fresh build, this time running without any existing darktable config, and tried the process described in the linked docs. It still fails to produce a usable PFM file from a 48-bit scanner TIFF (which works fine in 2.6), *but* I *did* manage to export a usable PFM from a camera RAW file. However, when running the new build with existing darktable config, I still can't successfully export any formats. It looks like it's not the simple issue that I thought.

I'll try to narrow down the problem and upload a sample file if I can create steps to reproduce. Sorry for any confusion.

**Comment by edgardoh** [comment]
I may found something, check #2264
