### ISSUE TITLE
Google Photos export failure

### ISSUE THREAD

**Issue by Gon0S** [darktable-org/darktable#2256]
Hello
I am not sure if previous 2.6.0 had the same problem, but actual 2.6.1 build available onto solus project repository is unable to get folder list when logging into my Google Photos account.

Overlay message : Unable to retrieve album list
Console message : ** (darktable:4050): CRITICAL **: 15:34:47.191: picasa_parse_response: assertion '(ret)' failed

In 2.4.0, it was working fine whereas I had to log in and grant access through OTP chain every time.

Best regards

**Comment by TurboGit** [comment]
Be sure to clean-up the install directory and rebuild from scratch. It looks like you still have an old picasa library now named googlephoto.

**Comment by Gon0S** [comment]
Hi

I am getting some conflictual information about this one, as one of Solus Project package maintainer tell me the 2.6.2 source is still showing picasa.c library whereas the master branch has googlephoto.c library...

Not sure what he is really talking about as I am not skilled for package maintenace and even worser at programming, but I think there is a mismatch somewhere...
They are asking me to wait for a fix from the source branch from Darktable...

If you have time to look at it, I got the reply here : https://dev.getsol.us/T7743

Regards.

**Comment by TurboGit** [comment]
No, you are right. Google photo is in master not 2.6 branch. Sorry I though you were building from sources the master branch (read too fast). So in 2.6.x there is no luck as Picasa API is now deprecated. I'll see if this can be scheduled for 2.6.3.

**Comment by Gon0S** [comment]
OK ! Fine. So this is an easy fix that just need an update.

I will wait for it. I am not an everyday user of this feature, and I have a manual workaround for the moment.

Really pleased of Solus project team and work. Keep going !

Thank you very much.

**Comment by TurboGit** [comment]
Nothing more to do, closing.

**Comment by JohnMaguire** [comment]
@TurboGit Any ETA on when 2.6.3 will be released?

**Comment by TurboGit** [comment]
A 2.6.3 won't happen. In fact there was so many (and deep) changes in dt after 2.6.2 was released that is was almost impossible or very difficult to merge anything in 2.6 branch. So you'll have to wait for next major release which is (as usual) not so far now.
