### ISSUE TITLE
Expose and timeline when returning from darkroom issue

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2268]
**Describe the bug**
While in expose mode if I double click on an image I can go to darkroom (sometimes it takes a few try), when returning to lighttable the timeline is also visible to the left of the filmstrip.

If I double click on the filmstrip I can't go into darkroom.

**To Reproduce**
In expose mode double click on an image (re-try if doesn't work), it goes to darkroom
Double click again, it goes to lighttable, but the timeline is also visible.

Doble click on any image on the filmstrip, it does not go to darkroom.

**Expected behavior**
Timeline is not visible and I can go to darkroom by double click on the filmstrip.

**Comment by AlicVB** [comment]
Just add a PR to fix the timeline visibility.
For the double-click inside the filmstrip, I've no idea, as I don't use it. Are you sure that double-clicking on a thumbnail in the filmstrip should enter in darkroom ? Because at first sight, I can't understand what timeline has changed that has repercussion on such behaviors...

**Comment by edgardoh** [comment]
>
> Just add a PR to fix the timeline visibility.
>
Thanks!

> For the double-click inside the filmstrip, I've no idea, as I don't use
> it. Are you sure that double-clicking on a thumbnail in the filmstrip
> should enter in darkroom ? Because at first sight, I can't understand what
> timeline has changed that has repercussion on such behaviors...
>
It should, but maybe is an expose issue. Or maybe in expose the feature is
not available for some reason.
My bad, I should have entered two separate reports...
