### ISSUE TITLE
Update user manual section concerning OpenCL

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#2271]
**Is your feature request related to a problem? Please describe.**
Contrary to information in user manual, OpenCL generally doesn't work on AMD cards.

**Describe the solution you'd like**
The information given in https://www.darktable.org/usermanual/en/darktable_and_opencl_amd.html reads:

>While NVIDIA devices and most modern AMD/ATI devices will most often run out of the box, there is more to do for older AMD/ATI graphics cards, namely those prior to the HD7xxx series.

That doesn't reflect current situation now, as most AMD cards now use open drivers which do not support OpenCL well enough to work in darktable (missing image operations: https://dri.freedesktop.org/wiki/GalliumCompute/, https://bugs.freedesktop.org/show_bug.cgi?id=87738). There are two alternatives, namely amdgpu-pro or ROCm. They usually don't work *out of the box* and require manual setup. Moreover quite often they don't work at all. In my particular use case, amdgpu-pro gives corrupted images and crashes the system, while ROCm doesn't work due to lack of PCIe atomics. See also the discussion below the article https://www.darktable.org/2012/03/darktable-and-opencl/

Thus I believe the information in user manual is quite obsolete and misleading and should be partially rewritten. 
* section 10.2.1 should note that AMD cards may cause problems (also `ATI` should be changed at least to `ATI/AMD`)
* section 10.2.5 should mention the case of `[opencl_init] discarding device 0 XXX due to missing image support.`
* section 10.2.6 is generally completely obsolete as it deals with really old cards running with long unsupported fglrx driver. It should be updated to describe a current situation and the existing text should clearly reflect that it deals with a legacy situation.
* possibly even the article https://www.darktable.org/2012/03/darktable-and-opencl/ should get another update concerning this situation.

**Comment by XanomalieX** [comment]
Thank you.
Knowing that would have saved me time!
My RX 580 worked great for 2 days and since then the opencl option is grayed out.
Tried a lot figuring out, how to make it work again.

**Comment by tomaszg7** [comment]
> ... Even though the features list of my Card says: "OpenCL 2.0"
The card does support it. It is Mesa which doesn't: https://dri.freedesktop.org/wiki/GalliumCompute/ All image functions are still "TODO".

**Comment by XanomalieX** [comment]
Honestly RC2 completely solved my problems!
I just once deleted 
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\INetCache\darktable
and after that OpenCL was available and stayed there all the time.

**Comment by tomaszg7** [comment]
Well, it is still valid. Myself, I managed to get amdpro to work for me (barring https://github.com/darktable-org/darktable/issues/4213).

**Comment by johnny-bit** [comment]
Newest manual - https://darktable.gitlab.io/doc/en/darktable_and_opencl_amd.html still has the same problem.

Overall OpenCL on Linux with AMD cards is minefield, eg no mobile cards despite what model they are except for some cases, yes new cards but only with very new cpu, with old cpu very new cards only, ROCm **might** work but might not, AMDGPUPro **might** work with some cards or not but not with open drivers etc...

With regards to intel OpenCL I found out that OpenCL ver actually gives me better results than CPU one...

Overall I think the manual sections for setting up OpenCL should be scrapped for same reason google/filckr/etc... import was/is being scrapped: It's too much effort to keep it up-to-date and true. Instead should be replaced by generic "refer to your distribution and hardware vendor manuals on how to setup OpenCL for your HW combination"

**Comment by coffeeandspaceships** [comment]
> should be replaced by generic "refer to your distribution and hardware vendor manuals on how to setup OpenCL for your HW combination"

That gets my vote but I think we could add some quality-of-life debug messages and things so that you can find out *why* OpenCL isn't working, when it isn't working. At the moment there is the OpenCL slider in the UI and a sense of false confidence when you slide that to "on." Perhaps there should also be some indication whether a particular module uses OpenCL or not, because for instance I didn't realise Amaze wasn't offloading, and demosaicing is pretty fundamental to *everybody's* workflow. 

The situation in general will improve now @turbogit has created the means to automatically test whether the OpenCL pipeline is valid on a system anyway, with the new test suite in PR #4818.

**Comment by elstoc** [comment]
As the documentation is no longer being maintained in this repository I've created a new issue https://github.com/darktable-org/dtdocs/issues/238 and will close this one. Please add any comments to the new issue if you feel they are still relevant.
