### ISSUE TITLE
Mouse wheel changes image size while in expose mode

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2279]
When in expose mode, if the mouse wheel is used over the image nothing happens, but when changing to file manager view the size of the thumbs has changed.

It will be great if the mouse wheel could offset the selecting in expose mode, let's say I have images 1 and 2 selected, by using the wheel it offset to 2, 3; 3, 4; etc.

If that's not possible at least the mouse wheel shouldn't be propagated to the file manager view.

**Comment by AlicVB** [comment]
I've done the simplest fix.
For the feature "scrolling to move the selection", I'm not sure it's a good idea as we have no idea if the selection is continuous, nor if there's other size/ratio images around...

**Comment by edgardoh** [comment]
@AlicVB , thanks!

For the requested feature, what I actually need is this:

Very often I have several very similar images and I want to compare them side by side to reject the ones I don't like. I do this by setting the filter to >= 1 stars and I set to zero the images I want to reject.
I can do this right now, but I have to manually re-select the next 2 (or any number) that I want to compare.

This is a different concept of what we have now, but is really close, so it feels that something can be done.
Maybe adding a new mode: now we have "display based on selection", we can add a "display a fixed number of images", with a setting similar to what we have on the file manager, and dt will always display that number of contiguous images side-by-side, when rejecting one the next available will be displayed.
We'll still need the scroll feature for this, but as a nice-to-have.
Do you think this is possible?

**Comment by edgardoh** [comment]
@AlicVB , so we don't duplicate efforts, I'll start working on this new mode. This is just a first thought so I don't know what I'll end up doing, but at first I'll try what I described.

**Comment by AlicVB** [comment]
ok great !
