### ISSUE TITLE
Module renaming not working when window focus is "sloppy"

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#2281]
**Describe the bug**
https://github.com/darktable-org/darktable/pull/1841 reverts https://github.com/darktable-org/darktable/pull/1890

**To Reproduce**
1. Set Gnome window focus to sloppy, e.g. via gnome-tweaks.
![Bildschirmfoto vom 2019-03-24 20-55-24](https://user-images.githubusercontent.com/1159508/54884969-4c519300-4e77-11e9-9290-557ef276787a.png)
2. Open darktable and try to rename some module.

**Expected behavior**
No UI element pops up to enter a new name. (Actually the new window with the textbox to enter the new name looses immediately its focus (because the mouse cursor is not above the new window) and disappears before the user can see it.) 

**Platform (please complete the following information):**
 - Ubuntu 18.4, darktable master branch

The bug had already been fixed by https://github.com/darktable-org/darktable/pull/1890 but was later reverted by https://github.com/darktable-org/darktable/pull/1841 .

**Comment by edgardoh** [comment]
Probably my fault, I'll look into it.

**Comment by TurboGit** [comment]
And mine as I did not notice the revert. But the PR was quite big :( Anyway good to have detected this issue now, we have time to fix it.

**Comment by TurboGit** [comment]
Should be fixed.
