### ISSUE TITLE
OpenCL unavailable on supported hardware > slowdown 

### ISSUE THREAD

**Issue by RhvdG** [darktable-org/darktable#2286]
On 2.6.2, "Activate OpenCL support" is not available in Core options (I can't tick the check box) on my Late 2015 iMac 5K that does have the necessary hardware and drivers. As a result (I'm guessing) many operations are considerably slower, causing me to revert to 2.6.1 (where the option is available and things run much more smoothly).

**To Reproduce**
Open Core options on an iMac 5K Late 2015 (and probably on other hardware) and see if the option is available.

**Expected behavior**
OpenCL use should be available as an option on all supported hardware.

**Platform**
 - OS: macOS Mojave 10.14.3 (18D109)
 - iMac (Retina 5K, 27-inch, Late 2015)
 - AMD Radeon R9 M395 2048 MB
 - darktable 2.6.2

**Comment by parafin** [comment]
It's a known issue on Mac that you need to restart darktable several times before OpenCL becomes available in darktable. It's a bug in MacOS, nothing we can do.

**Comment by RhvdG** [comment]
Thanks. After six darktable restarts, a system reboot, and two more darktable restarts, the OpenCL option appeared.
