### ISSUE TITLE
bug in jpeg export

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#2290]
**Describe the bug**
When an image is exported as jpeg from darktable and then parsing image tags using exiftool the following error message is displayed:
"Warning" => "Can't decrypt Nikon information (no ShutterCount key)". The implication is that, among others, the tag LensID is missing. LensID gives a detailed information about the used lens -> "LensID" => "Tamron SP AF 150-600mm f/5-6.3 VC USD (A011)"

**To Reproduce**
1. Use any raw file (NEF): exiftool -LensID image.nef
Output: Lens ID                         : Tamron SP AF 150-600mm f/5-6.3 VC USD (A011)
2. Export the raw file to jpeg from Darktable
3. exiftool -LensID image.jpg
Output: Warning: Can't decrypt Nikon information (no ShutterCount key) - image.jpg

**Expected behavior**
Step 3 should output: 
Lens ID                         : Tamron SP AF 150-600mm f/5-6.3 VC USD (A011)

**Platform (please complete the following information):**
 - OS: Debian Sid (Unstable)
 - Version 2.6.0

**Additional context**
I Have exported jpg's for 2.4.x which contains the same bug.

**Comment by mir07** [comment]
I forgot to mention that exporting from Rawtherapee works as expected.

**Comment by mir07** [comment]
Read more here: https://github.com/LycheeOrg/Lychee/issues/234

**Comment by Nilvus** [comment]
Maybe it's not a darktable issue. As you said on Lychee, it's the same on Gimp that share libraries. So maybe it's an exiv or lensfun (exiv probably) issue. See which version you use and if lens is recognize correctly by these libraries.
And putting a RAW in this type of issues could help.

**Comment by mir07** [comment]
Files showing the problem attached.
Use:
exiv2 -Pkyct pr [file.jpg]
exiftool -LensID [file.jpg]

Both works with raw file exported to jpeg with Rawtherapee but only exiv2 works with the exported raw from darktable. I am not able to upload the raw file since it is both to large and it does not conform to the allowed file types for upload.

![20190421-zoo-24-darktable](https://user-images.githubusercontent.com/2576455/57990387-879ec580-7aa6-11e9-903c-da2f69a6c128.jpg)
![20190421-zoo-24-rawtherapee](https://user-images.githubusercontent.com/2576455/57990391-8d94a680-7aa6-11e9-8d65-101bafd234d8.jpg)

**Comment by mir07** [comment]
Forgot:
exiftool -ver
11.16
 exiv2 --version
exiv2 0.25 001900 (64 bit build)
darktable --version
this is darktable 2.6.2+13~g0bef6bb76-dirty
rawtherapee -v
RawTherapee, version 5.5
