### ISSUE TITLE
Export Selected  - save "on conflict" setting in preset

### ISSUE THREAD

**Issue by t3mujin** [darktable-org/darktable#2291]
**Is your feature request related to a problem? Please describe.**
In the "export selected" module, when used file on disk mode, the "on conflict" option is always set to Create Unique Filename, regardless of its setting when creating a preset. Some of my saved presets would rely on overwriting the existing files, so I have to change the flag every time I want to run that preset.

**Describe the solution you'd like**
A saved preset action would save everything in the current module settings, including the "on conflict" value. I agree that the default value for that flag should be "create unique filename", but I can't find a reason not to save the preset with all the modules options at a given moment.

**Describe alternatives you've considered**
The only available alternative I considered would be to have my presets set to save to a temporary folder, instead of the final folder, so  But that would mean manually move the

**Comment by TurboGit** [comment]
> The only available alternative I considered would be to have my presets set to save to a temporary folder, instead of the final folder, so But that would mean manually move the

No, the alternative is to select the preset and conciously set the "overwrite" the "on conflict" setting. This has been done so to avoid erasing pictures.

**Comment by t3mujin** [comment]
@TurboGit Sorry, but that's a bit condescending, because that's saying users aren't smart enough to handle such a dangerous feature. I think if users are able to learn darktable they can easily understand the impact of that dropdown. 
Having a feature that saves the current settings of a module in a preset, but silently ignores some of those settings because that "might be too dangerous" is really bad UX. This along with  [#2131](https://github.com/darktable-org/darktable/issues/2131) would add more options and control to the export batches.

**Comment by TurboGit** [comment]
I don't see where I'm condescending... And BTW **I'm a darktable user**, right!

**Comment by t3mujin** [comment]
I'm not really saying you're condescending, but that not letting users do something because they will mess up is a condescending reason.

**Comment by edgardoh** [comment]
Addressed in #2304

**Comment by t3mujin** [comment]
[#2304 ](https://github.com/darktable-org/darktable/pull/2304) work perfectly, no need to keep this one open. Closing it.
