### ISSUE TITLE
dt 2.7: Some jpeg are displayed head down in the darkroom

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#2296]
**Describe the bug**
Using dt 2.7, some jpeg pictures are displayed head down in the darkroom

**To Reproduce**
1. Import the attached jpeg picture
![IMG162](https://user-images.githubusercontent.com/22872204/55070615-f5220d00-5086-11e9-8461-fd3bd6a3e734.jpg)
2. In the lighttable, see the picture, head up
3. Go to the darkroom and see head down display

**Expected behavior**
Proper (head up) display in lighttable & darkroom

**Platform (please complete the following information):**
 - Observed using dt 2.7.0+216~g7e345791c / Linux
 - NOT observed using dt 2.6.2 / Windows

**Comment by leclercj** [comment]
I believe it has to do with the "top, right" Exif.Image.Orientation tag in impacted jpeg pictures
exiv2 -g Exif.Image.Orientation IMG135.jpg
Exif.Image.Orientation                       Short       1  top, right

**Comment by TurboGit** [comment]
2. the picture is shown properly in the lighttable only if the embedded thumbs is used, otherwise it is also upside down in the lt as in the darkroom.

**Comment by TurboGit** [comment]
Quite strange as exiftool seems to report the wrong value but exiv2 report the right one:

$ exiftool IMG162.jpg | grep Ori
Orientation                     : Mirror horizontal

Which is plain wrong, and indeed exiv2 report the right value "top, right".

But we do use libexiv2 to get the exif data... so at this point I don't have a clue, but debugging the code I do get 2 as the orientation parameter from jpeg and 2 is FLIP_HORIZONTALLY which explains the flip you're seeing.

**Comment by TurboGit** [comment]
Maybe a bug in recent exiv2 library?

**Comment by TurboGit** [comment]
Hum... Wondering if this is not an issue only affecting Jpeg exported from Lightrroom. The orientation there could be from Lr and not the original orientation? Do you have the original Jpeg around to check?

**Comment by leclercj** [comment]
You're lucky: I was able to find the original Jpeg from an old backup.
This is a scan from a slide. No orientation information in the exif data
As far as I can remember, I did this scan batch putting all slides in the wrong side, so later used LightRoom to mirror all images.
![IMG162-original](https://user-images.githubusercontent.com/22872204/55110544-879ecc80-50d8-11e9-9802-82437651c0db.jpg)

**Comment by leclercj** [comment]
I do believe that Orientation = 2 (FLIP_HORIZONTALLY) is a correct exif value for this image after I fix it with Lr

**Comment by TurboGit** [comment]
I see a scan with not orientation information and Lr which has added some. So now it seems clear that exiv2 is the issue has it reports "top, right" whereas the proper orientation should be "mirror horizon". This match with my debug session and there is nothing to fix in dt. Maybe report this in exiv2 project?

**Comment by TurboGit** [comment]
But wait, your original jpeg has no orientation information but it is in the correct orientation, so the added orientation from Lr seems wrong to me, no?

**Comment by leclercj** [comment]
No, the original jpeg is not correct. I had to add a mirror horizon to fix it.
And please note the behaviour change in dt between 2.6 and 2.7. dt 2.6 is not using exiv2 ?

**Comment by leclercj** [comment]
to me, exiv2 is correct reporting "top, right" for Orientation = 2
See http://sylvana.net/jpegcrop/exif_orientation.html

**Comment by TurboGit** [comment]
> No, the original jpeg is not correct. I had to add a mirror horizon to fix it.

But the one you just posted is displayed correctly on my side. Isn't it the same on your side?

**Comment by leclercj** [comment]
No. Please look the difference between the 2 images using eog or nautilus in linux. Those tools are correctly using the Orientation=2 exif to flip the first image horizontally.

**Comment by leclercj** [comment]
![Capture d’écran du 2019-03-27 22-38-25](https://user-images.githubusercontent.com/22872204/55114015-24656800-50e1-11e9-9a92-0702c81c7588.png)

**Comment by TurboGit** [comment]
Ah indeed!!! I think I found and fixed the bug locally. I'll sleep on this and see if it still seems correct tomorrow :)

**Comment by leclercj** [comment]
Using the test patterns from https://github.com/recurser/exif-orientation-examples we can clearly see the problem in dt 2.7 is with exif.Orientation = 2 or 4. The others seems correctly managed.
![Capture d’écran du 2019-03-28 06-25-17](https://user-images.githubusercontent.com/22872204/55132448-bfcafd00-5122-11e9-89e8-acf6804a855c.png)
