### ISSUE TITLE
List for applying stles does not scroll in Windows 10 versions 2.6.1 and 2.6.2, OK for 2.6.0

### ISSUE THREAD

**Issue by antoniotrincone** [darktable-org/darktable#2297]
**Describe the bug**
 I recently installed DT 2.6.1 and 2.6.2 on Windows 10 disintalling previous 2.6.0 version perfectly functioning.  One thing does not work: the long list of styles when one have to apply it, is not
scrolling both in 2.6.1 and 2.6.2. Reinstalling back  2.6.0 version, no problem was present all
work flawlessly
 Thanks
 Antonio
that's the best way I can express this bug at best of my knowledge

**To Reproduce**
1. Go to Darkoroom
2. Click on applying a darktable style (small icon on the left)
3. TRY to scroll down the long list

**Expected behavior**

List scrolling as usual

**Screenshots**

**Platform (please complete the following information):**
 - OS: [Windows 10]
 - 2.6.1 and 2.6.2

**Additional context**

**Comment by fastlorenzo** [comment]
Same problem here, v2.6.2 on Windows 10.

![image](https://user-images.githubusercontent.com/768639/59263574-99a4fb80-8c41-11e9-8d37-202fa668a1bf.png)
