### ISSUE TITLE
Copy history stack, lighttable

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2300]
**Describe the bug**
- in dt. 2.6.x and also the former official versions, the copy of history stack in lighttable had the order of the history stack I see in darkroom
- in the current dt git-master (2.7.0+796~g8a5ce514f) the order is different in that pop-up window
- I know has nothing to do with the actual sequential working order of those modules, when it comes to pixel-pipe
- However, inside that copy-window in lighttable it is challenging to disable basecurve, sharpen and rotation as you have to dig them out of the list somewhere, where they previously where at the beginning (means bottom) of the list.
- My point: handling of that “which elements to copy in lighttable from one pic to another” is less convenient now

**To Reproduce**
1. Go to 'lighttable'
2. Click on 'copy history stack'
3. See the sequence is not anymore as in 2.6.2 and earlier officials (and maybe git-master)

**Expected behavior**
I would be very happy to see it in the previous behaviour, as it makes it more easier to find the elements one want to alter

**Platform (please complete the following information):**
 - OS: [e.g.gentoo linux]
 - Version [e.g. 2.7 git-master several versions up to 2.7.0+816~g5e8d065a7

**Comment by AxelG-DE** [comment]
Sorry for pasting her again, as I am not familiar, how it is seen the best, or where is the optimum position:

Currently that list is upside down compared to previous versions and also compared to history stack.

It is better now than unsorted. However, same orientation than history stack would be helpful, I guess

**Comment by TurboGit** [comment]
The order as also been reversed now. So closing as all should be fine now :)
