### ISSUE TITLE
have an visible indicator in lighttable and more importent in darkroom, whether opencl is working or not

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2301]
**Is your feature request related to a problem? Please describe.**
Especially on GENTOO-Linux there are several ways to mess up opencl or a new development-masked driver does not support opencl, or any other flaw...

**Describe the solution you'd like**
maybe near the dt-logo in the top left corner of darktable's window (lighttable and darkroom), have an indicator, whether or not opencl is activated successfully (additional opencl-logo, or have a "tick" attached to the logo or any other clear visual indicator....

**Describe alternatives you've considered**
I know, one can start "darktable -d opencl" or go to preferences and check. However, such indicator would be WAY more convenient to have an eye on from time to time

**Additional context**

**Comment by rabauke** [comment]
I do not think that darktable needs such a feature. It would target an issue that is specific for users of rolling release distributions. Users of less volatile distributions setup their system once, check if OpenCL works properly by `darktable-cltest` and just forget about the OpenCL issue.

What you are really looking for is an indicator for a working OpenCL configuration in the Gentoo-Linux desktop.

**Comment by AxelG-DE** [comment]
understand your point. Is 99% correct. Just as long you do not trigger opencl, the devices on my gentoo are anyway off.... but yes, that would be a first step. 

As I agreed to Mica on pixls.us, I admit 99.99% of the cases, it is not dt's issue, I just thought, it would not hurt to show on the UI, what I see in the preferences, if I would open....

**Comment by AxelG-DE** [comment]
as pphoto said on pixls.us just now, an error-message, once opencl is activated in preferences but doesn't work, would suffice

**Comment by TurboGit** [comment]
Like @rabauke I'm not sure we want this. This will add some more info on the GUI which is most of the time non useful.

**Comment by AxelG-DE** [comment]
got it.
than how about phorot's idea?

**Comment by junkyardsparkle** [comment]
I can't easily test this, but if `darktable-cltest` works the way I think it does, and returns false with no working opencl, then you could launch darktable with a script like this:

```bash
if darktable-opencl then
    exec darktable
else
    xmessage "opencl is broken"
fi
```
Just a thought. :)

**Comment by AxelG-DE** [comment]
Dear all,
I know, currently there are more important things to do on dt. May I anyway update some thoughts here:

- I accept the comment from @rabauke 
- The solution from @junkyardsparkle is challenging, when you want to handle debugs or other commandline options (I know is doable, but always a pain to handle) 
- Can we have a warning indicator (but let dt still work normally), which merely pops up (similar like the x-mas cap on the logo), when  opencl is activated by darktablerc but not working, no matter why...?

**Comment by TurboGit** [comment]
@AxelG-DE : see #2683 for a proposed solution.

**Comment by AxelG-DE** [comment]
@TurboGit
Thanks, I'll check as soon I'm back home next week.

**Comment by AxelG-DE** [comment]
@TurboGit 
I did test this PR and after build and install I first started dt normally and opencl is active. Afterwards I made a 
- rmmod nvidia_uvm. 
- darktable_cltest confirmes, opencl is not working. 
- I started dt and got nothing different. No information widget got displayed. 
- I checked settings quickly but didn't find anything there, which I might need to switch on firstly...

Anything I did wrong or checked the wrong place?

**Comment by TurboGit** [comment]
Sorry, no doc yet so you cannot guess. You need to add the variable $(OPENCL_ACTIVATED) in the information pattern (prefs -> GUI options -> darkrooom (section) -> information line pattern)

You already have "$(EXIF_ISO) ISO..." just add at the end OpenCL:$(OPENCL_ACTIVATED).

This line is activated on darkroom at the bottom by default IIRC, you can change that with the corresponding setting.

**Comment by AxelG-DE** [comment]
Thanks.
It works
Is it possible, in case OpenCL: no that this part `Opencl: no` is displayed in bold red?

**Comment by AxelG-DE** [comment]
In general, I should be happy, as you don't like this idea basically, and still doing something on this users wish.

If, by chance, now you support this idea more strongly, may I wish, I would prefer to have this information widget "Shutter, Apperture, ISO" clean (even though I added || as a separator) and in case of malfunction of opencl, have a graphical symbol (e.g. crossed out OpenCL logo with red cirle around, like road sign) next to the dt logo. Actually also in lighttable, as you need OpenCL there as well :smile:

**Comment by TurboGit** [comment]
I don't think this is possible to have red and conditional (only for no) here.

**Comment by TurboGit** [comment]
I understand, but well this require too much energy at the moment and there is certainly more important things to do :)

**Comment by AxelG-DE** [comment]
Accepted, then we take it as is at the moment. Happy to see it merged.

**Comment by AxelG-DE** [comment]
@ClaesGitHub
I know, you are also fiddling around with Gentoo, so you may like this one here...

in Prefes, Gui Options, Pattern for the image infos line, I have the following: "OpenCL activated: $(OPENCL_ACTIVATED) || $(EXIF_EXPOSURE)s  f/$(EXIF_APERTURE)  $(EXIF_FOCAL_LENGTH)mm  ISO $(EXIF_ISO)"

@TurboGit 
AFAIK, there is no plural for "info", so it should be "Pattern for the image info line" :smile:

**Comment by AxelG-DE** [comment]
I'm already very happy with this [variable](https://github.com/darktable-org/darktable/commit/0e2ded8042a1459adbf4f28f80ff70ff5369a7ab)

Mini shortcoming, one have to switch to darkroom. A small icon next to dt's logo which indicates a wanted opencl does not work (still happens from time to time, e.g. After kernel rollback) would be more elegant :-)

**Comment by AxelG-DE** [comment]
I do realize, I am not the only one, using OpenCL:$(OPENCL_ACTIVATED) hence still hoping for a more visible indicator, not only in darkroom :)

**Comment by elstoc** [comment]
@AxelG-DE you can also add this variable to image thumbnails (or the hover tooltip) in the lighttable.

**Comment by AxelG-DE** [comment]
It still happens to me, have some gentoo updates and suddenly opencl is not working any more. Would be so nice if the logo top left would either be B/W or blinking, if opencl is intended but not working, due to whatever reason, so I get alert right away rather than wondering "eh.... why machine is so slow...."

**Comment by elstoc** [comment]
> blinking

Please no blinkies
