### ISSUE TITLE
Option to order modules alphabetically

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2303]
**Is your feature request related to a problem? Please describe.**
Often I have a hard time finding a specific module that I want to work with. The modules that I use often are saved in my favourite list which is quite long with around 30 modules. 
I don't use the other tabs (Correction group or basic group) because I don't remember which module in which group is.

For example I'm working with the equalizer module opened and want to add some haze removal. Now the question is: where is the haze removal module, do I have to scroll up or down in the module list?
Even if I know that haze removal is somewhere below the equalizer in this case, I cannot remember the relative positions of all modules to each other.

The left side of the screenshot below shows my current search process. First I jump down a row and then I have to look left or right to the beginning of the text if it begins with 'haze' or not.
This is very complicated and time-consuming.

**Describe the solution you'd like**
- Align the module heading text left. The beginning letters are all on a vertical line which make them much easier to read and scroll
- Add an option to order the modules alphabetically. This should only affect the display order in the GUI, not the pixel pipe. If I want to re-order modules (move up or down) I must deactivate the alphabetical order.
- For sorting the program should use the module names first, then the user-given names.

**Possible implementation**
- Right-click on the favourites group
- Activate option 'Alphabetical order'
- Icon for favourites group has an indicator that option is active, for example:
![az_indicator](https://user-images.githubusercontent.com/49001045/55116569-fc2d3780-50e7-11e9-943a-9992e20c165e.jpg)

**Additional context**
Screenshot with my search process (left the current situation, right my request)
![modulelist2](https://user-images.githubusercontent.com/49001045/55115464-dc484480-50e4-11e9-850a-2a6669abe400.jpg)

**Comment by edgardoh** [comment]
There's now a search box, check in
config->shortcuts->views->darkroom->search modules for the shortcut and in
config->GUI options->darkroom->show searchmodule text entry for the setting

**Comment by pphotography** [comment]
I don't have these options. I've got version 2.6.1 from PPA running on Ubuntu 18.04.

**Comment by edgardoh** [comment]
This is in master, will be for 2.8, but if it covers this requirement
there's no need for a order by module's name.

**Comment by pphotography** [comment]
That's true, a search function would provide an easy way to find a module. According to your description I could open a search box using a keyboard shortcut and enter the module's name. 
Sounds good.

**Comment by Nilvus** [comment]
@pphotography : maybe could be closed if search module is ok for you ? Goal is to clean up issues to help see which issues remaining to work on.

**Comment by Nilvus** [comment]
@TurboGit : I think this could be closed in regards of recent modification like search module and possibility to change modules order.

**Comment by pphotography** [comment]
Cannot really say, I don't have version 2.7

**Comment by Nilvus** [comment]
> Cannot really say, I don't have version 2.7

What I could say is with 2.7 you could, as erdgadoh says, search module quickly with a search option above modules and with also edgardoh work, there's a possibility to reorder modules. But remember that modules order have an impact on the image. With 2.6, module order in pipe is blocked by default. Now, with reordering modules, that have impact on pixelpipe order. So, for example, contrast local by default after filmic, if moved before filmic change the result on image. And it's better before filmic. That change add so more options to treat with images as changing the place of a module could change the result on image.

So having modules alphabetically will not be a good thing with that change. And I think if you mix with 2.7 search modules with tabs, it's really fast to find a module ! Hope that helps !

**Comment by TurboGit** [comment]
Indeed, closing.

**Comment by chhil** [comment]
I am on a Darktable facebook group and one user had a comment that since the pipeline ordering can be changed it would impact the use of styles. Sounded like a valid concern. Could you let me know if styles are impacted and what would be the way to work around the impact?
