### ISSUE TITLE
Drag zoomed image display thumb icon

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2305]
When dragging a zoomed image in file manager it drags it a bit and then it displays the drag icon for the thumb.
It works fine on expose mode.

In both file manage & expose the zoom don't follow the mouse when in full preview or when comparing images.

**Comment by AlicVB** [comment]
hmm, not sure to understand... you can zoom inside images in filemanager mode ? I so that's a bug, but I can't reproduce...

For the second part, "zoom follow mouse", you mean that the zoom should be center at mouse position ? If so, I agree and will look at it.

**Comment by edgardoh** [comment]
> hmm, not sure to understand... you can zoom inside images in filemanager
> mode ? I so that's a bug, but I can't reproduce...
>
When in file manager mode, if you go to sticky preview (that's what I use)
you can zoom in, then try to pan (drag) the image, the thumb icon is
displayed. This does not happen when in expose mode.

> For the second part, "zoom follow mouse", you mean that the zoom should be
> center at mouse position ? If so, I agree and will look at it.
>
Yes, that's what I mean.

**Comment by AlicVB** [comment]
OK, got it, you need to be in manual sorting mode... Will have a look too
