### ISSUE TITLE
dt2.7: zoom preview in darkroom does not work with images with exif.Orientation = 2 or 4

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#2306]
**Describe the bug**
After https://github.com/darktable-org/darktable/issues/2296 is fixed, another issue remains with images with exif.Orientation = 2 or 4: Zoom preview in darkroom does not work properly

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a picture with exif.Orientation = 2 or 4 then go to darkroom
Such picture can be found using https://github.com/recurser/exif-orientation-examples
2. Try to zoom on a part of the image
4. See error: The displayed part of the picture in the main window is not the same as in the preview

**Screenshots**
See screenshot
![Capture d’écran du 2019-03-28 19-29-03](https://user-images.githubusercontent.com/22872204/55183344-e07d6c00-518f-11e9-8aa4-69d5f08a85ef.png)

**Platform (please complete the following information):**
Observed using dt 2.7.0+825~gc75bbd330 / Linux
NOT observed using dt 2.6.2 / Windows

**Comment by TurboGit** [comment]
Ok, this one looks amusing :)

**Comment by TurboGit** [comment]
Should be fixed, was a quite difficult one to fix. Do not hesitate to tests again and again. Thanks.

**Comment by leclercj** [comment]
Thanks @TurboGit for the fix. Looks great.
Testing further, I'd report that dt 2.6.2 does not seem to behave the same with regards to image orientation on Windows vs Linux
More specifically, I observed https://github.com/darktable-org/darktable/issues/2296 and https://github.com/darktable-org/darktable/issues/2306 both already affecting dt 2.6.2 on Linux, while dt 2.6.2 on Windows is working like a charm.
So at this stage, I'm wondering if the changes made to fix those issues might have broken the Windows version.
Is somebody testing 2.7 on Windows currently ? Any possibility to do so ?

**Comment by leclercj** [comment]
Good news; I've now built and tested dt 2.7.0+847~g21223246b on Windows, and it still works correctly for all exif orientations.
The only point still unclear to me is why dt2.6.2 behaves differently on Linux vs Windows, and how dt 2.6.2 on Windows can work without the https://github.com/darktable-org/darktable/issues/2296 and https://github.com/darktable-org/darktable/issues/2306 fixes.

**Comment by TurboGit** [comment]
@leclercj : thanks for testing and this is reassuring! Indeed the Windows 2.6.2 behavior is quite strange!!! Don't know what is happening here. But I suppose that all this is over with your 2.7 test on both Windows and Linux. Thanks.
