### ISSUE TITLE
dt stalls for ~40s, sporadically & occupies 1 of 8 CPU cores 100%

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2312]
**Describe the bug**
similar issue observed in two diff. scenarios
1) in lighttable I want to copy one or several actions from history stack to a set of other pics (panos)
2) I am in darkroom, in front of me one of the pics belonging to a pano, all have a certain history stack. I want to move to the next pic with space-key

Than what happens is, one CPU core is fully loaded and dt appears frozen for approx. 40s

I created a log wit -d all >dt-log_a, attached as zip. 
- The occasion is in that log, just I am not sure, what you see, e.g. at 14239,384941s is exactly that moment
- I wish I would have tail -f in a sep. window, than I could tell you exactly the hang time
- by a second try it did not happen
[dt-log_a.zip](https://github.com/darktable-org/darktable/files/3025354/dt-log_a.zip)

**To Reproduce**
see above, unfortunately sporadically a 100% reproduce, I cannot imagine at this moment

**Expected behavior**
no hang as previously

**Platform (please complete the following information):**
 - OS: gentoo
 - Version 2.7.0+833~g521127f62 

**Additional context**
because of the flip-issue, I want to upgrade soon, but if you guys stop me and stay here, I could do so, for further analysis

**Comment by AxelG-DE** [comment]
it still happens in 2.7.0+838~g07d7e6f36

unfortunately I am in dt at this moment without logging :-/

**Comment by AxelG-DE** [comment]
I was able to isolate it.
it happened at 154,803952s
you can see, the next entry is at 313,615570s and that is the time, dt was frozen, later you can still see  a big lag between 313,62396s and 324,692407s.
it is ever sql...

I have the following sql-things installed....
# qlist -Iv sql
dev-db/mysql-connector-c-6.1.11-r1
dev-db/mysql-init-scripts-2.3
dev-db/sqlite-3.25.3
dev-perl/DBD-mysql-4.44.0
dev-qt/qtsql-5.11.3
virtual/libmysqlclient-18
virtual/mysql-5.6-r12


[dt-log_c.zip](https://github.com/darktable-org/darktable/files/3025919/dt-log_c.zip)

what else can I do?

**Comment by johans3** [comment]
We all know how resource hungry DT can be and it's OK but sometimes I got the impression the processes take way too much energy. 

So it isn't just platform related, as I've a powerful desktop Mac OsX, not a laptop or iMac
If the rolling bug releases are able to fix this issue(s) then I'll be super excited to see the next version of DT  :)

**Comment by TurboGit** [comment]
I'm using dt daily and it is blazing fast for almost everything.

Can you test disabling OpenCL if it is activated?

**Comment by AxelG-DE** [comment]
I could do so, but as it is so sporadically, I soubt, how long shall I sit without opencl :-)

Actually I have the feeling, it has something to do with the now solved flip issue. 
- Here and there I still have had some rotated, 
- which might be related to, I rotated them during the issue in order to continue my work. 
- And just now I had to rotate some back, as they now where still fliped when I zoomed out in lighttable

I could imagine, such manual rotated pics, that those where the ones, which caused my PC to stall. 

Today I processed about 10-20 panos, in total ~150pics and it didn't happen anymore...

**Comment by johans3** [comment]
after disabling OpenCL and working awhile with this setting my machine calmed down and doesn't roar anymore like a Ferrari on full speed.. 

My graphic card is an AMD RADEON HD 7970 with 3 gigs

**Comment by TurboGit** [comment]
> which might be related to, I rotated them during the issue in order to continue my work.

Right, as I pointed out in my message all images edited with the buggy version are affected.

> Today I processed about 10-20 panos, in total ~150pics and it didn't happen any more...

Which is very reassuring! Thanks.

**Comment by TurboGit** [comment]
@johans3 : so a buggy driver? or maybe the config was set to use two cards? Do you have an integrated Intel graphic card too?

**Comment by johans3** [comment]
@**TurboGit**
Basically Apple is so user-friendly that we  hadn't ever to care about drivers. Consequently there's no setting to configure graphic cards-at least not if we have just on gc mounted. 

And no, I've no integrated Intel graphics card, this would apply to newer machines. 

On Mac we have just a preference to set brightness and color profile of the monitor.

**Comment by TurboGit** [comment]
@johans3 : so issue solved? I know next to nothing about Apple! Should this be closed?

**Comment by johans3** [comment]
sure thing! 
Pity that this Interface to improve and optimize GPU acceleration is not compatible with slightly older graphics cards. As much as i understand we cannot profit from this resource. Also an interesting read:
Bug report #2271

**Comment by AxelG-DE** [comment]
For quite some time I didn't see this initial behaviour any more, hence closing. Thanks for everyone...
