### ISSUE TITLE
old topic new: detach side pannels in order to make use of two monitors

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2323]
Dear DT-Team,

pls allow me to address an old topic again.
What I am after, I also have adressed here:
https://discuss.pixls.us/t/darktable-on-two-monitors/11952/5

I remember, colour management is an issue, let me address this further down below

**Is your feature request related to a problem? Please describe.**
I use two monitors (yes different panel and lighting technology, hence colour mismatches)
1) HP LP2475w @1920x1200
2) EIZO CS270 @2560x1440
(both connected to GPU0 as I have two, second merely for opencl)

The EIZO is my main screen for editing. No matter 27" I often use zoom or "tab" for fullscreen, by means, I could use more space

**Describe the solution you'd like**
I'd like to see the sidepanels (prio 1=right panel, prio 2= left panel, prio 3=filmstrip) detachable (keep me having the main-window than still free of window-manager-borders with F11 pls.)

Somehow as it is in GIMP, where I can place toolboxes freely at will.

**Describe alternatives you've considered**
Buy me a >=60" wide gamut :-)

**Additional context**
Colour management:

If I remember correctly, this topic was long time ago already an issue on redmine. What I have in mind was, it got refused due to unresolvable issues about colour management.

From my personal perspective it looks not that relevant (indeed I might be wrong)

I am far away not a professional about this topic. 
I have calibrated my two monitors with displaycal & spider4 and they are user based "system-wide" (colord disabled in dt, -another topic, "why")

Now... what I expect from my point of view: 
- yes my screens are not that exactly same colours but however, 
- if I have the "main window" on the EIZO and the panels on the other, I cannot see a problem, when the grey of the UI is a bit different. 
- I could even bear, if the little preview on top of left panel is not that accurately, as I only use it for navigation purposes. 
- I am only afraid of one thing: the PRO's may say "yaaaahhhh, the whitebalance for instance, somehow would react on the screen, it got touched/triggered on and not only on the picture to modify..." In such case I would run out of words (for the moment..... :-) )

Thanks in advance for openly reconsider

**Comment by bes1002t** [comment]
> I am only afraid of one thing: the PRO's may say "yaaaahhhh, the whitebalance for instance, somehow would react on the screen, it got touched/triggered on and not only on the picture to modify..." In such case I would run out of words (for the moment..... :-) )
they don't have to use such a feature ;)

I had a conversation in #darktable about this topic some days ago. There are a much more users who wants this feature. It simply makes sense, since many developers and designers are also working with two screens. Why should darktable not provide such a feature and ignore a much more efficient workflow?

**Comment by edgardoh** [comment]
I think that the side panels detachable has nothing to do with color management, that was an issue in another request: to have two separate images on darkroom, so they can be used on two different monitors.

The problem with the detachable panels is that it will be a lot of work and probably require some big redesign.

**Comment by bes1002t** [comment]
@edgardoh I saw another issue about that darktable is only usable with one CPU core. Maybe it is worth to switch the ui technology to a more state of the art technology which makes it possible to use darktable with multiple cores and which makes it possible to create multiple windows for multiple purposes e.g. tools.

**Comment by TurboGit** [comment]
@bes1002t : please learn before saying "a more state of the art technology" ! dt is based on Gtk one of the best toolkit around. And this toolkit does support detachable widgets. But it is not because it is possible that it is easy given the current dt development design.

> I know this is a lot of work, but would improve the user experience and performance so much.

Can you contribute it?

**Comment by aurelienpierre** [comment]
> @edgardoh I saw another issue about that darktable is only usable with one CPU core. Maybe it is worth to switch the ui technology to a more state of the art technology which makes it possible to use darktable with multiple cores and which makes it possible to create multiple windows for multiple purposes e.g. tools.

You mean redesigning the whole UI overnight ? As much as I hate GTK, this won't happen anytime soon.

The multiscreen app is, indeed, grounded into the ability to retrieve the right monitor profile for the right GTK widget, and I have no idea how to do that.

> Why should darktable not provide such a feature and ignore a much more efficient workflow?

Because it is more difficult than what you think.

**Comment by chrik5** [comment]
>... , but would improve the user experience and performance so much.

After 10 years of dual screen setup in the office (CAD, GIS, ...) I can't tell you how happy I'm with a single but bigger screen now. Head turning all the time has gone.

27" screens are pretty much standard today. I would like to see how one works on two 27" screens with panels on one screen and the image on the other without turning the head. 

I don't think I will improve user exprience in any way.

**Comment by bes1002t** [comment]
> 
> 
> @bes1002t : please learn before saying "a more state of the art technology" ! dt is based on Gtk one of the best toolkit around. And this toolkit does support detachable widgets. But it is not because it is possible that it is easy given the current dt development design.
> 
> > I know this is a lot of work, but would improve the user experience and performance so much.
> 
> Can you contribute it?

Could you please stop acting like I said this is easy, you should do it over night?

Fact is, many other tools are providing multi window toolbars and multi core support. It is obvious that this is not a trivial implementation and will need a lot of time.

**Comment by TurboGit** [comment]
@bes1002t : you come with  "a more state of the art technology", how should I take that?

Sorry, but that's certainly not a way to start a discussion.

**Comment by bes1002t** [comment]
You're right, sorry. It was not my intention to belittle the work of the Darktable devs. You're doing a great work providing such a good open source tool. :)

"a more state of the art technology" is a little bit misleading, I meant using GTK in a different way would enhance the user experience. For instance using XML files for views, like Android and Angular, and as already mentioned the multi core support (it it is really no existent yet).

**Comment by aurelienpierre** [comment]
GTK is not intended to be multithreaded, so there is no "adding multicore support", there is only "ditching GTK entirely for something else" or waiting for a rewrite of GTK (4.0 ?).

Also, XML files solve none of the technical issues we have, it's merely another way to do it (the preferences use XML, what difference does it make ?).

It's like people constantly asking to switch from C to C++ instead… Who cares ? It's only a mean to an end, the way it is coded doesn't solve anything feature-wise.

**Comment by AxelG-DE** [comment]
@chrik5 
as you can see in the initial post, I do have a 27" screen and still I zoom a lot and also, getting older I'd appreciate to change width from 350 to 450px. So if I'd have a what ever bigger screen (didn't do the math) to represent, what I see, when I press tab today, I'd also need to turn my head

@aurelienpierre do I get it right:
- from the other thread [#2044](https://github.com/darktable-org/darktable/issues/2044) basically you also support to the idea of multiscreen support? At least that is my impression from what I read there...
- and the shortcomings for GTK force us to be more patient, whether or not a future version offers us a technique, which at least may give us a chance to implement such multi window option with reasonably amount of efforts?
- on the other hand, that indicates me (as a non coder) GIMP, which I compared to, has a different UI technology (is backend the right word here)?

Thank you all for engagement!

**Comment by chrik5** [comment]
@AxelG-DE : Yes I saw that. Do you consider GIMP as good example? GIMP started with separate panels and GIMP users asked for years for a single window mode.

**Comment by aurelienpierre** [comment]
>     * from the other thread [#2044](https://github.com/darktable-org/darktable/issues/2044) basically you also support to the idea of multiscreen support? At least that is my impression from what I read there...

yes

>     * and the shortcomings for GTK force us to be more patient, whether or not a future version offers us a technique, which at least may give us a chance to implement such multi window option with reasonably amount of efforts?

multi-window is a completely different issue than multithreading. It is doable right now, but at what cost ? Basically, we will need different GTK context with different display profiles, and ensure the proper GTK widgets use the right context. I personnaly have no idea how to do that nor if it is even possible.

>     * on the other hand, that indicates me (as a non coder) GIMP, which I compared to, has a different UI technology (is backend the right word here)?

GIMP uses GTK too, but they have a long history of beeing sloppy on color management, so I suspect they just drop widgets in sRGB and don't bother to be consistent with calibrated screens.

**Comment by AxelG-DE** [comment]
I saw the conversation at a certain point of time digressed to multithreading and frankly speaking I could not judge whether or not those topics where linked somehow or it was really a digress (as I seem to learn now).

I would not mind sliders and other things have a bit colour-management issues, when they are placed on a second screen (the new colour zone even do not look too weird, when I extend the window to overlap to the second screen.

So all in all, that means, as because I cannot program, I need to be patient whether somebody is an UI-programming nerd and like to step in. Meanwhile I gotta be patient or anything else I could do to contribute?

**Comment by AlicVB** [comment]
Well, the main question is : do we need to have color-management for side panels (or as @aurelienpierre say : what is the cost of dropping cm for side panels) As for as I can tell, this can be a problem for : 
- navigation preview.
- color picker lib (certainly the most problematic)
- colored sliders (?)
- color zone iop
- ...
imho, if we warn the user that colors can be off (by superposing an "danger" icon, some text, or by displaying a warning box when panels are detached, or ...) it may be enough...

Notes : 
- I've done some quick and basic experiments and coding such feature _shouldn't_ be to hard or invasive (note the italics) I can eventually work further on it if we reach a consensus
- I only speak of side panels here. Filmstrip is of course a completely different point here as color management is critical in this case !

**Comment by edgardoh** [comment]
Personally I don't find the detachable panels very useful, it will be better to have a second window on the darkroom. I've done some experiments on this but so far I can't make the image "sharp" as in darkroom and I have no idea what's happening.

**Comment by AlicVB** [comment]
> I don't find the detachable panels very useful

Having more space to display image ?

**Comment by TurboGit** [comment]
Exactly, more space, full screen for the actual image and just panels on the other screen.

**Comment by edgardoh** [comment]
I suppose that's personal, but I have used it for a while in GIMP and did
not work for me. Having a second window should work better as I can have
the full image in one display and work on the zoomed image on the other,
but until I have a functional version I can't say for sure.

**Comment by AlicVB** [comment]
see #2351 for a very naive and basic implementation

**Comment by AxelG-DE** [comment]
I am quite happy with that "second darkroom image window". Just one thing (and I admit that is in majority my problem) both monitors I have, are wide gammut and well calibrated. Still the appearance is not totally the same. Also it is expensive, even though I do have to GPUs, you can feel, the second window creates some lagging.
 
I have heard @aurelienpierre that he said, it is way too hard or have too many drawbacks if one day we would have achieved it. Frankly speaking, I still wonder how gimp made it :) That's all I wished. 

So somehow my dream is still there :-)

**Comment by AxelG-DE** [comment]
Actually I am fine with 2nd preview, closing now

**Comment by bes1002t** [comment]
I think the second window solution was the best tradeoff. Just another window to see the whole picture in full screen works perfectly if you zoomed in editing some details.

Thanks for your great work guys :)
