### ISSUE TITLE
Time offset is lost after reimport

### ISSUE THREAD

**Issue by bes1002t** [darktable-org/darktable#2324]
**Describe the bug**
I Forgot to change the time of my camera at vacation, so I tried to use darktable to add an time offset. It was working like a charm, the image information was updated and the exported jpg had the correct time.

After deleting the film roll and reimporting the raw images (the .xmp files are located in the same directory as the raw files), the time offset was gone and I had to add the offset for every single file again. For 10 files this is ok, but for hundrets of RAWs this is very annoying. So before I edit all of them, I wanna check whether I do something wrong or this is really a bug.

I also tried the button "write xmp file" on the image with the applied time offset, before deleting the film roll and the button "read xmp file" after the reimport, but this did not change anything.

**To Reproduce**
1. go to "geo tagging"
2. add an time offset of -1 hour
3. press the hook behind the input field
4. datetime of the image changes to the correct time
5. delete the current film roll
6. reimport all images of the deleted film roll
7. time offset of the datetime is gone

**Expected behavior**
Time offset should be there after reimport, otherwise restoring a backup would be hell for every photographer.

**Platform (please complete the following information):**
 - OS: Windows
 - Version 2.6.1

**Comment by TurboGit** [comment]
The time offset is not saved into the xmp it is only used to match the time in the GPX and the time if the images.

**Comment by bes1002t** [comment]
so if I edit my images and add a time offset to them, I have to edit ALL of my images again after a reimport?

How about a discussion about changing this behavior instead of closing the issue?

A photographer who fixes the timestamps of his 4000 raws has to do this again and again after each reimport, if he wants to see the correct exif creation date after he exported his raws.

After applying the time offset the datetime of the raw has changed. As user I expect that this datetime is the same after a reimport.

At my last vacation I had 3 different time zones and I wanted to fix the wrong datetimes with darktable. Since the datetime is gone after a reimport I have to remember which image was taken in which timezone and fix this probably in a few years when I have to restore a backup, otherwise the datetime and so the ordering may be corrupted.

**Comment by TurboGit** [comment]
My bad, I did not understand your first report. I confirm that the time offset is lost.

**Comment by bes1002t** [comment]
@TurboGit would it be an option to include the time offset information to the xmp file of an RAW, if the time offset is already applied? This would avoid situations like someone has to apply the time offset again for each raw file after a reimport.

**Comment by TurboGit** [comment]
I have a proposed fix for this #2341.

If you build from source can you test this?

**Comment by bes1002t** [comment]
oh sorry, missed this @TurboGit 
I don't build it from source, but if it's in master now I could test it again. :P

**Comment by houz** [comment]
Storing the date/time in XMP was not done on purpose as it has serious implications. For example, it makes it impossible to safely apply a sidecar file to any other image to get its processing.
