### ISSUE TITLE
bugs after testing darktable-bin in terminal

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2327]
**Describe the bug**
My goal was to check if darktable is able to run lua scripts on my Mac

**To Reproduce**
1. Go inside the application bundle: Darktable/Contents/MacOs/
2. Launch the Terminal in /Applications/Utilities/
3. Drag darktable-bin (from the path in point 1) into the terminal window
4. Add ' -d lua' at the of the line and confirm with enter

**Expected behavior**
Darktable executes scripts on startup by itself so why do I get errors and lua scripts not loading into Dt? 

**Terminal output**
(process:2472): GLib-GObject-CRITICAL **: 19:43:55.505: g_object_set: assertion 'G_IS_OBJECT (object)' failed  

(darktable-bin:2472): GdkPixbuf-WARNING **: 19:43:55.788: Cannot open pixbuf loader module file '/opt/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /opt/local/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(darktable-bin:2472): GLib-GObject-WARNING **: 19:43:55.884: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(darktable-bin:2472): Gtk-CRITICAL **: 19:43:55.884: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2,791858 LUA ERROR : error loading module 'ExportCaptureDate' from file '/Users/home/.config/darktable/lua/ExportCaptureDate.lua':
	/Users/home/.config/darktable/lua/ExportCaptureDate.lua:4: unexpected symbol near '<\194>'

(darktable-bin:2472): Gtk-WARNING **: 19:43:58.511: Could not find the icon 'pan-down-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

**Platform (please complete the following information):**
 - OS: Mac
 - Version 10.11

**Additional context**

**Comment by parafin** [comment]
And why exactly are you using darktable-bin? You should start darktable script instead, which sets up the environment correctly.

**Comment by johans3** [comment]
because **darktable** it is just a startup script, not the actual binary. This is the output using "darktable"

```
(process:2867): GLib-GObject-CRITICAL **: 15:46:16.928: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(darktable-bin:2867): GLib-GObject-WARNING **: 15:46:17.350: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(darktable-bin:2867): Gtk-CRITICAL **: 15:46:17.350: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
[rawspeed] (Figur–70–121302.jpg) virtual std::unique_ptr<RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData *), line 91: No decoder found. Sorry.
Not a JPEG file: starts with 0x89 0x50
allocation failed???
3,507696 LUA ERROR : /Users/joe/.config/darktable/lua/gimp.lua:67: module 'lib/dtutils' not found:
	no field package.preload['lib/dtutils']
	no file '/opt/local/share/lua/5.3/lib/dtutils.lua'
	no file '/opt/local/share/lua/5.3/lib/dtutils/init.lua'
	no file '/opt/local/lib/lua/5.3/lib/dtutils.lua'
	no file '/opt/local/lib/lua/5.3/lib/dtutils/init.lua'
	no file './lib/dtutils.lua'
	no file './lib/dtutils/init.lua'
	no file '/Applications/Suite Design/darktable.app/Contents/Resources/share/darktable/lua/lib/dtutils.lua'
	no file '/Users/joe/.config/darktable/lua/lib/dtutils.lua'
	no file '/opt/local/lib/lua/5.3/lib/dtutils.so'
	no file '/opt/local/lib/lua/5.3/loadall.so'
	no file './lib/dtutils.so'
```

**Comment by johans3** [comment]
After installing lua dependencies…
```
(process:3335): GLib-GObject-CRITICAL **: 17:26:38.065: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(darktable-bin:3335): GLib-GObject-WARNING **: 17:26:38.448: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(darktable-bin:3335): Gtk-CRITICAL **: 17:26:38.448: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
Not a JPEG file: starts with 0x89 0x50
Not a JPEG file: starts with 0x89 0x50
[rawspeed] (Figur–70–121302.jpg) virtual std::unique_ptr<RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData *), line 91: No decoder found. Sorry.
Not a JPEG file: starts with 0x89 0x50
allocation failed???
```
