### ISSUE TITLE
Add Nikon D300s RAW-Files to raw.pixls.us

### ISSUE THREAD

**Issue by verylongusername69** [darktable-org/darktable#2329]
I just uploaded 6 files with all possible RAW combinations of compression and bitness settings.
When I uploaded them I got a message that I have to put an issue here, otherwise what I've made would be useless.
So sorry if I posted it on the wrong place or something but I suppose I have to post it here in order to appear in raw.pixls repository and furthermore to be supported better. I can see it has support it your website, but there is only 1 files for D300s and it's from the license you don't want.

**Comment by LebedevRI** [comment]
> I just uploaded 6 files with all possible RAW combinations of compression and bitness settings.

Thank you!

> When I uploaded them I got a message that I have to put an issue here, otherwise what I've made would be useless.

That comment talks about the case when one just uploads samples with comment like "do not work in", in which case one indeed should file an issue report.
In this case, all these raws are already supported and load fine, i just checked, so no action required.
