### ISSUE TITLE
darktable.exe caused an Access Violation

### ISSUE THREAD

**Issue by oriflama** [darktable-org/darktable#2330]
When I try to run the program, I get an error message and the program does not start. 
The error dialog say:
"An unhandle exception ocurred.
etc"

1. Doble click in the program shortcut
2. A cmd windows appears for a few milisecons (I can't see any data inside that black windows)
3. I get the error message window

**Expected behavior**
I expect that the program runs normally

**Screenshots**
I attach the backtrace file generated by the program:
[darktable_bt_SP1UZZ.txt](https://github.com/darktable-org/darktable/files/3038306/darktable_bt_SP1UZZ.txt)

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 1809 (17763.379)
- Intel i7-6700K
- 32GB

**Additional context**

**Comment by TurboGit** [comment]
Disable OpenCL and it will work. Which version of dt BTW? If not 2.6.2, please upgrade.
