### ISSUE TITLE
Update to lensfun 0.3.95

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#2332]
**Is your feature request related to a problem? Please describe.**
lensfun has issued a 0.3.95 version in 2018, which is more and more used in many distributions
To my experience, trying to build, install, and execute darktable with this latest lensfun version will fail. The lastest lensfun version supported by darktable seems 0.3.2

As far as I observed, lensfun 0.3.95 introduces several disruptive changes :

1) Static lfXX::Create() and lfXX:Destroy() methods of various Lensfun classe are now marked as deprecated. C++ new/delete syntax should be used instead.
This is creating several warnings for darktable at build time.
_C:/msys64/home/jlecl001/darktable/src/iop/lens.c:354:3: error: 'lf_modifier_new' is deprecated [-Werror=deprecated-declarations]_

2) the database format is now at version 2
It has impact on darktable Makefile, as lensfun database version number is used in installation paths
_CMake Error at src/cmake_install.cmake:157 (file):
  file INSTALL cannot find
  "C:/msys64/mingw64/bin/../share/lensfun/version_1"._

3) C interface: all lf_lens_interpolate_...() functions now require an additional crop parameter.
Probably the reason why I got an an Access Violation exception trying to use it anyhow.

See http://lensfun.sourceforge.net/changelog/2018/06/29/Release-0.3.95-Changelog/ for more details

**Describe the solution you'd like**

1) Document the need for dt 2.6 to use lensefun <= 0.3.2, with explanation where to find the old lensfun package for major distributions and how to install it

For instance, for Windows / MSYS2:
Check lensfun version with:
$ pacman -Q mingw-w64-x86_64-lensfun
If lensfun version > 0.3.2, then download mingw-w64-x86_64-lensfun-0.3.2-4-any.pkg.tar.x from http://repo.msys2.org/mingw/x86_64/
and rever lensfun to 0.3.2 using :
$ pacman -R mingw-w64-x86_64-lensfun
$ pacman -U mingw-w64-x86_64-lensfun-0.3.2-4-any.pkg.tar.xz

2) Prepare darktable to support lensfun 0.3.95 for next major darktable release
It  would also be nice to keep a backward compatibility with lensfun < 0.3.95

**Comment by leclercj** [comment]
Was already discussed in may 2018 in https://redmine.darktable.org/issues/12200
The need is more stringent now that lensfun 0.3.95 is released and is not a dev-only version anymore

**Comment by parafin** [comment]
I have tried that beta release with macOS, but there are issues that make it impossible to use as-is. Main problem that it crashes. I plan to retry with master branch instead, maybe I will have better luck. I have necessary changes to make it compile in my local branch.

**Comment by TurboGit** [comment]
It would be nice indeed to join our force to make this move a reality!

**Comment by parafin** [comment]
See #2606 for my progress so far. Someone has to take over.
Be advised that 0.3.95 release won't work, but we can try to support lensfun from git.

**Comment by markus1189** [comment]
@leclercj are there any updates on this?  What's the reason for the close? :wink:

**Comment by leclercj** [comment]
I see the darktable adaptation work to new lensfun API now done with https://github.com/darktable-org/darktable/pull/2793
Next step would be on lensfun side to deliver a new stable and working version from their git master branch. lensfun 0.3.95 is now close to 18 month old and has issues.

**Comment by leclercj** [comment]
See also https://github.com/lensfun/lensfun/issues/508
