### ISSUE TITLE
Hide shapes in Spot removal module

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2342]
**Is your feature request related to a problem? Please describe.**
After adding a spot to remove I want to take a look at the result. For the assessment  I need to hide the shape.
Other modules (like the 'retouch' module) have got a button to hide the used shapes. 

In the 'spot removal' module I have to deactivate the module. To hide the shapes I can collapse the module, to see the shapes again I can expand the module.
This behaviour is inconsistent to other modules with a dedicated button to show/hide the shapes

**Describe the solution you'd like**
Please add a button that shows and hides all used shapes to the 'spot removal' module, see below

**Additional context**
![grafik](https://user-images.githubusercontent.com/49001045/55667760-f14d7200-5860-11e9-9135-ad6c3addb436.png)

**Comment by junkyardsparkle** [comment]
Agreed the button should be there for consistency. But maybe we can do some brainstorming here about improving the usablility further than that? I was thinking it would be nice if clicking within the cloning "source" shape temporarily made the "destination" shape hidden (while leaving the arrow pointing to it). To me, this would be far more ergonomic for the process of finding the best source location: you click, if adjustment is needed, you procede to dragging. This would save moving the mouse pointer constantly between the module and the work area.

**Comment by pphotography** [comment]
That's a good point hiding the target shape when moving the source. But while dragging you can modify the target with mousewheel and modifier keys SHIFT and CTRL.
With a hidden target you cannot see the resulting shape of these modifications.

Maybe it would be a good solution to implement a modifier key that hides the shape only while being pressed. 
With this solution you can modify the target shape and show/hide its shape while moving the source shape.

This could be usable for the retouch module, but since this has nohting more to do with the initial topic I think this should be discussed in a new issue.

**Comment by junkyardsparkle** [comment]
> With a hidden target you cannot see the resulting shape of these modifications.

You're right, a keyboard shorcut would be better. Interestingly, the show/hide button in the retouch module doesn't seem to have an accel for this... but it would probably be better to implement it more globally under darkroom shortcuts so as to not have to use up a key for each module (similar to the brush size/opacity/hardness shortcuts).

> This could be usable for the retouch module, but since this has nohting more to do with the initial topic I think this should be discussed in a new issue.

It seems fairly related to the issue title to me, but in any case I think we can agree that along with adding the show/hide/ button, a shortcut would be good, too. :)

**Comment by elstoc** [comment]
> Interestingly, the show/hide button in the retouch module doesn't seem to have an accel for this... but it would probably be better to implement it more globally under darkroom shortcuts so as to not have to use up a key for each module (similar to the brush size/opacity/hardness shortcuts).

In addition to #4736, which resolves the original bug (among other things), global blendop show/hide shapes accels are now implemented in #4707 (a single shortcut to show/hide blendop shapes of the current gui module). However, due to how masks are used in spot and retouch it wasn't possible to have the same shortcut operate on those modules.

However, #4729 adds an accel for retouch show/hide shapes.
