### ISSUE TITLE
sqlite3 error: /home/lebedevri/darktable/src/common/iop_order.c:1046, function dt_ioppr_check_db_integrity(), query "SELECT styleid, operation FROM data.style_items WHERE iop_order <= 0 OR iop_order IS NULL": no such column: iop_order

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/darktable#2343]
**Describe the bug**
console output:
```
sqlite3 error: /home/lebedevri/darktable/src/common/iop_order.c:1046, function dt_ioppr_check_db_integrity(), query "SELECT styleid, operation FROM data.style_items WHERE iop_order <= 0 OR iop_order IS NULL": no such column: iop_order
```

**To Reproduce**
1. purge .config/darktable
2. build dt from before all the latest iop order nonsense (jan-feb or so?)
3. start dt, import some image, do something
4. remove .config/darktable/library.db
5. build dt git master
6. start dt
7. ???
8. profit

(steps 1-3 are a guess, i haven't tried reproducing)

**Expected behavior**
No errors?

**Platform (please complete the following information):**
 - debian sid

**Comment by junkyardsparkle** [comment]
I can reproduce this with a fresh config created with 2.6.2 and opened with 2.7.0+884~g43702be1 when only the library.db is removed. There's no error if data.db is also removed.

**Comment by TurboGit** [comment]
Should be fixed! And for point 2, the iop order makes lot of sense for some people :)
