### ISSUE TITLE
rgb curve 0-100?

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2344]
In difference to tone curve the range in rgb curve is from 0 to 1 instead of 0 to 100. So adjusting nodes by cursor keys doesnt change displayed values for several steps even the node moves far away from its original place.

**Describe the solution you'd like**
change multiplicator of the range so finer adjustments can be identified

**Comment by aurelienpierre** [comment]
So it's a matter of adding decimals I guess ?

**Comment by MStraeten** [comment]
adding more decimals or multiplying with 100 doesn't matter in my opinion, but from an UI view it would be better if tonecurve and rgb curve uses the same range/format. I prefer the 0-100 range, because its more easy to read than 3 digits after a decimal point.

**Comment by edgardoh** [comment]
Probably scaling to 100.f will do it, I'll see if I can find the time this weekend.

**Comment by aurelienpierre** [comment]
Ok if you add a %.

**Comment by edgardoh** [comment]
> Ok if you add a %.
>
I don't follow, add a % where?
