### ISSUE TITLE
Outdated Build Instructions

### ISSUE THREAD

**Issue by BlueStilton** [darktable-org/darktable#2347]
**Describe the bug**
Linux distro build instructions may be outdated.

https://github.com/darktable-org/darktable
links to 
https://redmine.darktable.org/projects/darktable/wiki/Building_darktable_20
for "a comprehensive list of build instructions for all the widely used Linux distributions", but it was written at the time of  DarkTable 2.0, and e.g. the Gentoo instructions are probably superseeded by an available ebuild, making this far simpler to do. I'm not in a position to validate the other instructions, but I think this page may be candidate for review by various distro users.

**To Reproduce**
1. Go to https://github.com/darktable-org/darktable
2. Click on _comprehensive list_ (of build instructions..)
3. Scroll down to Gentoo Linux
4. These are most likely outdated.

**Expected behavior**
Quick Fix: A warning saying these are probably outdated because they were written at the time of DT 2.0.
Later: updated instructions, ask various users of those distros, I'll volunteer the Gentoo experience, which AFAICT is now something like:

```
$ sudo emerge =darktable-9999
(accept the change to automask)
$ sudo etc-update
(update automask)
$ sudo emerge =darktable-9999
```

**Comment by aurelienpierre** [comment]
fixed in main Readme.md
