### ISSUE TITLE
Enabled OpenCL produces side effects 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2355]
When I was trying to use the color zones modules, just enabling it made the image go blue.  Sometimes the image does not go blue and the small image top right goes blue. 
I have attached the before and after images and the history is available in the image.

**Screenshots**
![after](https://user-images.githubusercontent.com/1119439/55723287-4c7c9180-5a26-11e9-8742-0aba851ab6bb.jpg)
![Before](https://user-images.githubusercontent.com/1119439/55723288-4c7c9180-5a26-11e9-9691-629efc7b433d.jpg)

**Platform (please complete the following information):**
 - OS: [Win10]
 - Version [e.g. 2.6.1]

Adapter Description	NVIDIA GeForce GTX 1060
Driver : 23.21.13.9140

**Comment by TurboGit** [comment]
The driver version does not correspond to a NVIDIA version. The current version is 410.xx and previous one was 390.xx. But this is certainly a Windows issue as I have never seen that on Linux nor was it reported by others.

**Comment by chhil** [comment]
Its on my surface book 2 with the nvidia card. The driver version is from the device manager.

**Comment by TurboGit** [comment]
Not enough memory? Can you reproduce that on a standard PC?

**Comment by chhil** [comment]
I dont have a standard PC with a NVIDIA card to reproduce it.
The Surface Book 2 has 16GB ram and the Nvidia card has 6 GB of memory.
