### ISSUE TITLE
Enabled OpenCL produces side effect while export jpeg

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2356]
**Describe the bug**
After completing the edit, and exporting the image, the image has issues and this example the lights start have a black center. When I disable opencl, I dont see this after export.

**Screenshots**
![image](https://user-images.githubusercontent.com/1119439/55723622-21467200-5a27-11e9-9359-4cb34e0712c9.png)

**Platform :**
 - OS: [Windows`10]
 - Version [e.g. 2.6.1]
Adapter Description	NVIDIA GeForce GTX 1060
Driver : 23.21.13.9140

**Additional context**

**Comment by aurelienpierre** [comment]
What modules are in use ?

**Comment by chhil** [comment]
Currently on 2.6.2, tried the export with opencl turned on and it worked fine.

**Comment by chhil** [comment]
Opencl on the same machine is no longer enabled in 2.7.xxxx
