### ISSUE TITLE
performance issues with heavy processed fotos (5 min to generate xmp file)

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2361]
**Describe the bug**
within darkroom switching between heavy retouced (about 10-20 points) results in a long waiting time when switching to the next image by pressing the Space bar or returning to lighttable

here some lines from darktable -d all:

...
247,408666 [sql] /Users/martinstraeten/src/darktable/src/develop/develop.c:566, function dt_dev_write_history_item(): prepare "UPDATE main.history SET operation = ?1, op_params = ?2, module = ?3, enabled = ?4, blendop_params = ?7, blendop_version = ?8, multi_priority = ?9, multi_name = ?10, iop_order = ?11 WHERE imgid = ?5 AND num = ?6"
247,408742 [sql] /Users/martinstraeten/src/darktable/src/develop/develop.c:1041, function dt_dev_write_history_ext(): prepare "UPDATE main.images SET history_end = ?1, iop_order_version = ?3 WHERE id = ?2"
247,409843 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:232, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
247,410101 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:315, function dt_image_path_append_version(): prepare "SELECT version FROM main.images WHERE id = ?1"
247,410148 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:232, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
247,410184 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:260, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"

waiting after switching to next image

307,898636 [sql] /Users/martinstraeten/src/darktable/src/common/exif.cc:2680, function dt_exif_xmp_read_data(): prepare "SELECT filename, flags, raw_parameters, longitude, latitude, altitude, history_end, iop_order_version, datetime_taken FROM main.images WHERE id = ?1"
307,898775 [sql] /Users/martinstraeten/src/darktable/src/common/exif.cc:2748, function dt_exif_xmp_read_data(): prepare "SELECT key, value FROM main.meta_data WHERE id = ?1"
307,898844 [sql] /Users/martinstraeten/src/darktable/src/common/tags.c:503, function dt_tag_get_attached(): prepare "SELECT DISTINCT T.id, T.name FROM main.tagged_images AS I JOIN data.tags T on T.id = I.tagid WHERE I.imgid = 11798 AND NOT T.name LIKE "darktable|%" ORDER BY T.name"
307,898923 [sql] /Users/martinstraeten/src/darktable/src/common/tags.c:503, function dt_tag_get_attached(): prepare "SELECT DISTINCT T.id, T.name FROM main.tagged_images AS I JOIN data.tags T on T.id = I.tagid WHERE I.imgid = 11798 AND NOT T.name LIKE "darktable|%" ORDER BY T.name"
307,898976 [sql] /Users/martinstraeten/src/darktable/src/common/exif.cc:2811, function dt_exif_xmp_read_data(): prepare "SELECT color FROM main.color_labels WHERE imgid=?1"
307,899016 [sql] /Users/martinstraeten/src/darktable/src/common/exif.cc:2836, function dt_exif_xmp_read_data(): prepare "SELECT imgid, formid, form, name, version, points, points_count, source, num FROM main.masks_history WHERE imgid = ?1 ORDER BY num"

waiting after switching back to lighttable

433,112359 [sql] /Users/martinstraeten/src/darktable/src/common/exif.cc:2888, function dt_exif_xmp_read_data(): prepare "SELECT module, operation, op_params, enabled, blendop_params, blendop_version, multi_priority, multi_name, num, iop_order FROM main.history WHERE imgid = ?1 ORDER BY num"
436,081262 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:1856, function dt_image_write_sidecar_file(): prepare "UPDATE main.images SET write_timestamp = STRFTIME('%s', 'now') WHERE id = ?1"
436,081524 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:232, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
436,081601 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:260, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"
436,081661 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:790, function dt_image_altered(): prepare "SELECT operation FROM main.history, main.images WHERE id=?1 AND imgid=id AND num<history_end AND enabled=1"
436,081760 [dev] took 0,000 secs (0,000 CPU) to load the image.
436,081942 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:232, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
436,081997 [sql] /Users/martinstraeten/src/darktable/src/common/image.c:260, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"
436,082045 [sql] /Users/martinstraeten/src/darktable/src/common/image_cache.c:231, function dt_image_cache_write_release(): prepare "UPDATE main.images SET width = ?1, height = ?2, filename = ?3, maker = ?4, model = ?5, lens = ?6, exposure = ?7, aperture = ?8, iso = ?9, focal_length = ?10, focus_distance = ?11, film_id = ?12, datetime_taken = ?13, flags = ?14, crop = ?15, orientation = ?16, raw_parameters = ?17, group_id = ?18, longitude = ?19, latitude = ?20, altitude = ?21, color_matrix = ?22, colorspace = ?23, raw_black = ?24, raw_maximum = ?25 WHERE id = ?26"
436,083614 [sql] /Users/martinstraeten/src/darktable/src/develop/develop.c:1252, function dt_dev_read_history_ext(): prepare "SELECT iop_order_version FROM main.images WHERE id = ?1"
436,083692 [sql] /Users/martinstraeten/src/darktable/src/common/image_cache.c:231, function dt_image_cache_write_release(): prepare "UPDATE main.images SET width = ?1, height = ?2, filename = ?3, maker = ?4, model = ?5, lens = ?6, exposure = ?7, aperture = ?8, iso = ?9, focal_length = ?10, focus_distance = ?11, film_id = ?12, datetime_taken = ?13, flags = ?14, crop = ?15, orientation = ?16, raw_parameters = ?17, group_id = ?18, longitude = ?19, latitude = ?20, altitude = ?21, color_matrix = ?22, colorspace = ?23, raw_black = ?24, raw_maximum = ?25 WHERE id = ?26"
436,083853 [sql] /Users/martinstraeten/src/darktable/src/develop/develop.c:1276, function dt_dev_read_history_ext(): prepare "SELECT history_end FROM main.images WHERE id = ?1"
436,083874 [sql] /Users/martinstraeten/src/darktable/src/develop/develop.c:1289, function dt_dev_read_history_ext(): prepare "SELECT imgid, num, module, operation, op_params, enabled, blendop_params, blendop_version, multi_priority, multi_name, iop_order FROM main.history WHERE imgid = ?1 ORDER BY num"
436,084089 [sql] /Users/martinstraeten/src/darktable/src/develop/develop.c:1466, function dt_dev_read_history_ext(): prepare "SELECT history_end FROM main.images WHERE id = ?1"
436,084138 [sql] /Users/martinstraeten/src/darktable/src/develop/masks/masks.c:1045, function dt_masks_read_masks_history(): prepare "SELECT imgid, formid, form, name, version, points, points_count, source, num FROM main.masks_history WHERE imgid = ?1 ORDER BY num"
436,185891 [export] creating pixelpipe took 0,064 secs (0,372 CPU)
436,185929 [pixelpipe_process] [thumbnail] using device 0

the affected xmp are very large (see example) 
[20190407-IMG_6076.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3056229/20190407-IMG_6076.CR2.xmp.txt)

regenerating the xmp file is about 5 min per xmp file

**Platform (please complete the following information):**
 - OS: OSX
 - Version:
darktable 2.7.0+904~g5db9e6d26
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by MStraeten** [comment]
new record: 39 min to generate: 
[20190407-IMG_6094.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3056330/20190407-IMG_6094.CR2.xmp.txt)

**Comment by edgardoh** [comment]
You will have to give some details on how you managed to get this, there's
a lot of masks/groups duplicated.

**Comment by MStraeten** [comment]
I transferred several settings between images via ctrl-c & ctrl-v in darkroom as well as via lighttable history stack copy & paste. Including retouch module.
The images were processed with about 3 different builds.
Is there a way to get rid of duplicated masks and groups stuff?

**Comment by edgardoh** [comment]
I don't see a way, compress history & clean masks don't do it. You have a
backup of the xmp, so you can try deleting them individually.

See if you can duplicate the issue, I've done a lot of copy/paste and I
didn't have this problem.

**Comment by MStraeten** [comment]
brute force solution:
via sqlite on library.db:
delete from masks_history where rowid not in (select min(rowid)from masks_history group by imgid,formid)
