### ISSUE TITLE
Fujifilm X-T30 Support

### ISSUE THREAD

**Issue by tylorr** [darktable-org/darktable#2366]
I've uploaded a raw image to https://raw.pixls.us from the x-t30 and would like support for it in darktable.

**Comment by LebedevRI** [comment]
Please upload full sample set. There are two raw modes on that camera.

**Comment by BlueStilton** [comment]
DNG of that first file at: https://olde.dev/Fujifilm-X-T30-14bit_uncompressed-3_2-.dng

Open to suggestions as for how to upload those here given the 10MB and file type limit.. split and gzip all parts?

**Comment by tylorr** [comment]
Ok, I uploaded a compressed version as well as a separate upload. Let me know if you need anything else.

**Comment by LebedevRI** [comment]
> Ok, I uploaded a compressed version as well as a separate upload. 

I was gonna complain that it was a single sample, but it was a full set, nice.

**Comment by BlueStilton** [comment]
https://olde.dev/Fujifilm-X-T30-14bit_uncompressed-3_2-.dng
https://olde.dev/Fujifilm-X-T30-14bit_compressed-3_2-.dng

**Comment by BlueStilton** [comment]
I re-downloaded from RP and re-converted because the file sizes made no sense until I realised the old uncompressed file was replaced as well.. Sorry about that. Makes more sense now ; same photo and similar sizes, probably because DNG has its own compression.

**Comment by Biont** [comment]
@LebedevRI How about noise profiles? Can the ones from the X-T3 be reused, since it's the exact same sensor and processor?

**Comment by LebedevRI** [comment]
I'm unable to answer that, i don't really handle noiseprofile side of things, sorry.

**Comment by schenlap** [comment]
@Biont
And same software? As we can not know what manufactures do in processing raw images ;-( the profiles can be different. Please create a new profile and open a new issue.

**Comment by LebedevRI** [comment]
(to be noted, the color matrix was not identical to any other existing color matrix, so i would strongly suggest not to play luck, and simply always create new noiseprofile for each camera.)

**Comment by aesteve** [comment]
Hello folks, and first of all a huge thank you for this awesome open source software.
I'm guessing by the commit date that the X-T30 isn't available yet in darktable 2.6.2.

I own an X-T30, and already have some lossless RAWs available, and can shoot other RAWs with the other profile if needed. 

Is there anything I can do to help you with the next release ?

Or should I just wait for the 2.6.3 ?

Thanks again. Great work, great software.

**Comment by Biont** [comment]
Hello @aesteve 

I've been meaning to try and take the needed photos for a while but keep getting sidetracked by real-life.

If you're able to step in, then what's left to do is to basically [https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/](this tutorial). It's worth reading into the comments, since they go into more detail into what other options there are for coming up with usable pictures.

**Comment by aesteve** [comment]
Thanks for your answer and the explanatory link.

My bad, I thought the "standard" pictures out of my camera would be enough. I do not own a printer, unfortunately.

So I'll need to print the grdaient somewhere else (maybe at work) before I can contribute anything.

So sorry :( will try my best to give it a shot though, but don't count on me very soon.

Hope someone can jump in this issue in the meantime, just in case.

**Comment by LebedevRI** [comment]
I think for basic support in 2.6.x everything is in place, only the release needs to happen.
