### ISSUE TITLE
Range selection is wrong when entering darktable

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2368]
When entering darktable and there's only one image selected in file manager, shift+click on another image don't select the desired range.

If when entering culling is active, and switch to file manager, instead of having the displayed images selected, images until the end are selected.

I did some debug and selection->last_single_id=0 when entering darktable, this probably should be the imgid of the selected image, but I'm not sure how selection works, so I don't want to mess with this.

**Comment by TurboGit** [comment]
I can reproduce. I'll have a look at this.

**Comment by TurboGit** [comment]
Should be fixed now.

**Comment by edgardoh** [comment]
Thanks!
