### ISSUE TITLE
Importing a folder imports only the first edit

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#2372]
**Describe the bug**
When importing a folder, darktable reads only the main edit, not any additional edits/xmp files that are related to a raw image.

**To Reproduce**
1. Import folder where there are multiple edits on a same raw image
2. Only the main/first edit is imported

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.1

**Additional context**
This doesn't happen on Linux

**Comment by junkyardsparkle** [comment]
More context, from [darktable-user list](https://www.mail-archive.com/darktable-user@lists.darktable.org/msg07363.html):
> I tested more and found an interesting detail. If I work only in Ubuntu,
everything works fine like Patrick described, but in Windows it doesn't
work. The additional xmp files are named differently in Windows and Linux.
In Windows it is image.raw_01.xmp and in Linux image_01.raw.xmp. Linux will
recognize the additional Linux style xmps, but not the Windows style.
Windows doesn't recognize either.

Possibly related redmine issue: https://redmine.darktable.org/issues/12649

**Comment by juhavlintula** [comment]
This issue is still in 3.0rc2 in Windows.

**Comment by juhavlintula** [comment]
This is also discussed in pixls.us. https://discuss.pixls.us/t/darktable-how-to-import-when-multiple-sidecar-files-for-an-image-exist/15522/6

**Comment by johnny-bit** [comment]
Just tested - the issue is NOT PRESENT on dt 3.2.1 on windows :)
