### ISSUE TITLE
Scrolling in lighttable with arrow-keys gives weird results

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2376]
**Describe the bug**
Using the arrow-keys by scrolling thru the thumbnaisl of lighttable gives a very weird result, where not all the pics are scrolling. Some just remain at the position, they where

It is hard to explain. Just the rows do not stay connected as they where and as they actually doing normally when using the mouse wheel....

**To Reproduce**
1. Go to lighttable and set it to 5 pics in a row (me having a selection of 150 pics)
2. Click on second row middle pictures
3. Hit the down-arrow several times

**Expected behavior**
Same behaviour then using the mouse wheel, where all the pics scrolling logically row by row

**Screenshots**
I have a screen cast, but it is 7.2MB and also is my first time to use OBS-Studio, hence things are not ideal, yet. Do I need to upload or is it "clear" by trying to reproduce?

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version 2.7.0+927~ge1835549f-dirty; 2.7.0+930~g85ccaaa16-dirty

**Comment by AlicVB** [comment]
I confirm.
I'll have a look when I come back from holidays if no one fix it before

**Comment by AlicVB** [comment]
should be fixed in PR #2444 
fix looks simple, but was hard to find ! Thanks for reporting

**Comment by AxelG-DE** [comment]
@AlicVB 
Thanks it works!
Interestingly scrolling is faster downwards and slower upwards. Is that worthwhile for reporting? :)
