### ISSUE TITLE
Image switches between dark and bright during edit

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2379]
**Describe the bug**
While editing a certain image in darkroom the image switches between bright and dark. 
This happens only to one specific image, no to others. On my computer this happens only with OpenCL activated.
Without OpenCL I see the filmic module's settings darken the image.

**Steps to Reproduce**
* Get RAW file from this thread: https://discuss.pixls.us/t/play-raw-a-cats-portrait/11122
* Get this XMP: [DSC02876.ARW.zip](https://github.com/darktable-org/darktable/files/3072918/DSC02876.ARW.zip)
* Open image in darkroom
* Zoom in and out, switch to older history steps

**Expected behavior**
Image brightness stays where it is

**video**
[DT_darkbright.zip (1.8MB)](https://github.com/darktable-org/darktable/files/3072833/DT_darkbright.zip)

**Platform (please complete the following information):**
- Ubuntu 18.04
- Darktable 2.6.1 from PPA

clinfo:
>   Platform Name                                   NVIDIA CUDA
>   Platform Vendor                                 NVIDIA Corporation
>   Platform Version                                OpenCL 1.2 CUDA 9.2.210
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
>   Platform Extensions function suffix             NV
> 
>   Platform Name                                   Clover
>   Platform Vendor                                 Mesa
>   Platform Version                                OpenCL 1.1 Mesa 18.2.8
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_khr_icd
>   Platform Extensions function suffix             MESA
> 
>   Platform Name                                   NVIDIA CUDA
> Number of devices                                 1
>   Device Name                                     GeForce GTX 1050 Ti
>   Device Vendor                                   NVIDIA Corporation
>   Device Vendor ID                                0x10de
>   Device Version                                  OpenCL 1.2 CUDA
>   Driver Version                                  396.54
>   Device OpenCL C Version                         OpenCL C 1.2 
>   Device Type                                     GPU
>   Device Topology (NV)                            PCI-E, 01:00.0
>   Device Profile                                  FULL_PROFILE
>   Device Available                                Yes

**Comment by TurboGit** [comment]
Darktable 2.6.2 has a fix for filmic on OpenCL, it may be the issue here.

**Comment by pphotography** [comment]
> aurelienpierre commented on 8 Mar
> The patch #2030  has been forgotten in dt 2.6.1 while the issue it solves is in 2.6.1 so  user experience dark images with filmic chroma preservation on CPU/SSE2

Found this info on #2176 in milestone 2.6.2

After reading this I tried to reproduce that behaviour without the option 'preserve the chrominance' in the filmic module and it didn't appear. After reactivating this option the behaviour occured again.

Looks like I just found this known bug.
