### ISSUE TITLE
Shade bug covers menu entries in preferences - Mac

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2380]
**Describe the bug**
In preferences, extreme top/bottom/side scrolling is accompanied by an animated shade effect (like seen on mobile phones). 
On Mac we get just a black bar which stays in place and covers preference entries

**To Reproduce**
Open the preferences:
1. Scroll up as much as possible
2. Scroll sidewards, max 
3. Scroll down, max '....'
4. See the missing "shade" effect - black bar

**Expected behavior**
No need to animate the borders of preferences with animation effects. ( I'd love a gentle and simple animation switching from lighttable to darkroom :p ) 

**Platform (please complete the following information):**
 - OS: Mac 10.11
 - Dt Version: 2.6.1

**Comment by parafin** [comment]
Yeah, it's very annoying. A fix would be much welcome.

**Comment by aurelienpierre** [comment]
This does not happen on Linux, could you send a screenshot ?

**Comment by johans3** [comment]
![Screen Shot 2019-04-21 at 10 07 15](https://user-images.githubusercontent.com/48620536/56467370-36a39f00-641e-11e9-8fbf-e2f1515fdb84.png)
![Screen Shot 2019-04-21 at 10 07 32](https://user-images.githubusercontent.com/48620536/56467371-36a39f00-641e-11e9-815a-089ed209307f.png)

**Comment by aurelienpierre** [comment]
It seems like something related to your desktop environment. There is no shadow explicitely set on the GTK part.

**Comment by parafin** [comment]
Desktop environment is plain GTK on macOS. It might be something from default theme, that's not overridden by dt css.

**Comment by johans3** [comment]
This happens on Mac 10.12 aka sierra 

I didn't set anything special in dt's preferences

**Comment by aurelienpierre** [comment]
> Desktop environment is plain GTK on macOS. It might be something from default theme, that's not overridden by dt css.

darktable inherits Adwaita's (dark variant) theme defaults, then reset some.

**Comment by parafin** [comment]
https://www.youtube.com/watch?v=2PCC2f__9a0 - here is the effect we are talking about. In DT it looks ugly, because there's no alpha-blending of the effect.

**Comment by parafin** [comment]
https://askubuntu.com/questions/706399/how-to-remove-the-scroll-limit-fade-edge-overshot-effect - here is how to disable it. Does DT theme implement it?

**Comment by aurelienpierre** [comment]
There is this in dt 2.7:
```CSS
undershoot.top,
undershoot.bottom,
undershoot.left,
undershoot.right
{
  background: none;
}
```
I will add `border: none`

**Comment by parafin** [comment]
Are undershoot.* and .overshoot the same? They don't look to me. Maybe I will experiment later with these CSS settings.

**Comment by aurelienpierre** [comment]
Ah, right. I forgot overshoot.

**Comment by aurelienpierre** [comment]
So, indeed, the CSS selector was not even correct in 2.6 and 2.7 because it should have been `.overshoot`
