### ISSUE TITLE
Lighttable: scan all visible images for sensor clipping

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2382]
**Is your feature request related to a problem? Please describe.**

After importing images into Darktable I mostly select only some of the images for detailed editing. Often I delete images that are unsharp or too over- or underexposed.

In lighttable view I cannot check for badly exposed images. To check this I have to enter the darkroom and turn on the sensor highlight clipping for each image individually.

**Describe the solution you'd like**
In lighttable I want to have a button that lets Darktable scan all currently visible images for sensor highlight clipping and then flags them visually (maybe a red exclamation mark).
A button to start the scan could be on the lower border of the screen next to the star and color ratings.

I want to be able to filter the lighttable view for images with clipping to be able to browse them in darkroom mode.
I want to be able to remove that flag manually from lighttable and darkroom.

This would make it much easier and faster to sort out images with bad exposure.

**Comment by johans3** [comment]
;)
Our goals are the same: I asked more effective grouping criteria for images defecting in tone value and color tints in my previous post about *workflow speedup*

**Comment by pphotography** [comment]
:)
For the meantime I found a manual workaround described here:
https://discuss.pixls.us/t/display-highlight-clippings-in-lighttable/12105
