### ISSUE TITLE
Usability: export all dtpresets

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2383]
if switching between different test data.db an export function for all presets in one step would be helpful, to simplify reconstruction of a brand new test environment from scratch.

**Comment by MStraeten** [comment]
Its a feature request not yet implemented

**Comment by MStraeten** [comment]
Feature request not yet implemented or triaged ...

**Comment by johnny-bit** [comment]
Would simple "export all user-made presets to given dir" be simplest descirption of this FR? (no exporting of build-in presets)

**Comment by MStraeten** [comment]
yes, exporting built-in presets is not necessary - they don’t get lost when ditching data.db

**Comment by johnny-bit** [comment]
Please check #7405 - does it match your expectations?

**Comment by MStraeten** [comment]
Yep, that’s it
