### ISSUE TITLE
OSX: opencl segmentation fault

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2384]
**Describe the bug**
when opencl is enabled after a couple of correction darktable crashes with an segmentation fault:
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Abort trap: 6

**To Reproduce**
hard to reproduce because sometimes the error occurs earlier, sometimes later.
Latest steps to reproduce:
- remove data.db and library.db to start from scratch
- imported some dtpresets
- imported pictures with xmps
- open picture in darkroom
- apply color lookup tables until it crashes ;)

xmp:
[20180624-IMG_0509_01.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3074904/20180624-IMG_0509_01.CR2.xmp.txt)
preset applied:
[colorchecker_Canon 5DmIV Standard.dtpreset.txt](https://github.com/darktable-org/darktable/files/3074927/colorchecker_Canon.5DmIV.Standard.dtpreset.txt)

**console output**
[opencl_segfault.txt](https://github.com/darktable-org/darktable/files/3074889/opencl_segfault.txt)

**Platform (please complete the following information):**
 - OS: OSX
 - Version this is darktable 2.7.0+941~g9dce2d1ef
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by MStraeten** [comment]
next scenario:
start darktable, reopen image in darkroom, compress history --> segfault:
xmp:
[20180624-IMG_0509_01.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3074962/20180624-IMG_0509_01.CR2.xmp.txt)
console output:
[second_crash.txt](https://github.com/darktable-org/darktable/files/3074959/second_crash.txt)

**Comment by parafin** [comment]
You should attach macOS crash report which includes a backtrace, console output is pretty useless.

**Comment by MStraeten** [comment]
ok, next:
after rebuild with new #2381:
while regenerating thumbnails darktable crashes:
here the osx crash report:
[osx_crash report.txt](https://github.com/darktable-org/darktable/files/3075072/osx_crash.report.txt)

**Comment by parafin** [comment]
Yeah, I guess you will have to disable OpenCL, looks like a bug in OpenCL driver.

**Comment by MStraeten** [comment]
without -d all darktable had following console output:
darktable(688,0x11433b5c0) malloc: Incorrect checksum for freed object 0x7f956183cb38: probably modified after being freed.
Corrupt value: 0x0
darktable(688,0x11433b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by parafin** [comment]
That's new - there were no such errors in your previous logs. Did that crash produce a crash report? Though with memory corruption backtrace won't be much useful either.
It might be unrelated issue due to recent changes in master and not macOS-specific.

**Comment by MStraeten** [comment]
next try to isolate the problem:
clean install of OSX mojave, build environment and deleted library.db.
- imported two raw files
- applied following xmp file to one of them:
[20190223-IMG_5937.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3086266/20190223-IMG_5937.CR2.xmp.txt)
- crash on compress history stack and following following restart of darktable 
[osx crash report.txt](https://github.com/darktable-org/darktable/files/3086273/osx.crash.report.txt)

here the latest messages from darktable -d all:
[console outputs.txt](https://github.com/darktable-org/darktable/files/3086301/console.outputs.txt)

seems to terminate at different processing steps ...

this is darktable 2.7.0+1022~g6a9574be3
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by MStraeten** [comment]
so i got it:
this is darktable 2.7.0+1027~g82cd94e6a
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

console output:
darktable(26103,0x700005175000) malloc: Incorrect checksum for freed object 0x7ffcef315e38: probably modified after being freed.
Corrupt value: 0x700007ffcef30b1f
darktable(26103,0x700005175000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

and the crash report:
[crash_report.txt](https://github.com/darktable-org/darktable/files/3091407/crash_report.txt)

**Comment by MStraeten** [comment]
I did some git checkouts for older commits to isolate the origin of the bug.
with git checkout b5a1aa149e438cdf579c896c3f0879222cfa4b0 i couldn't reproduce the segfault
with git checkout 201c215f4d3e23f6a1bb1b55491fb3afe9bdfc2b the segfault could be reproduced

the commits/merges of 10 April changed several opencl stuff and since then it fails on osx mojave (macbookpro 11.3, Intel Iris Pro, NVIDIA GeForce GT 750M, current CUDA driver)

**Comment by MStraeten** [comment]
played a little with opencl settings.
default opencl_number_event_handles=25 crashes, lower or higher values are fine ...

**Comment by semperit89** [comment]
Got the same bug with a clean install of darktable 3.2.1.  Imac 27" 2013 with Geforce GT755M

Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Abort trap: 6

As you mentioned, I changed the "default opencl_number_event_handles" from 25 to 100 and everything seems fine now. Maybe it´s possible to change the value permanent to another number?

**Comment by jenshannoschwalm** [comment]
@MStraeten do you still have this issue on current master (2022.04.05) ?

**Comment by MStraeten** [comment]
i replaced the old machine and continued using quite higher opencl_number_event_handles so never hat this again ...

**Comment by jenshannoschwalm** [comment]
And with low handles like default? I am asking because I couldn't understand how the number of handles could trigger the issue...

**Comment by MStraeten** [comment]
not reproducible on my current system configuration...
