### ISSUE TITLE
Preferences: option to disable library database

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2386]
**Is your feature request related to a problem? Please describe.**
I use Darktable for RAW processing only. All my files are ordered in folders and subfolders on my hard drive.

The only thing that interest me is the editing history of my photos. I have no usage for tagging, film rolls or groups.

I never bothered about the library database until one day the database was out of sync with the XMP files and every image showed up twice. Almost lost many edits which were not saved in XMP. Luckily I was able to copy the histories between database and XMP versions and recover the edits.

After that and rebuilding the database I didn’t had any problems, but I’m asking myself why keeping the same information in two different places in different formats.

Darktable has an option to disable the usage of XMP files, bot not to disable the database.

**Describe the solution you'd like**
I want the option to disable XMP files extended to a selection of the following options:
- Use library and XMP 
- Only library
- Only XMP

**Describe alternatives you've considered**
Starting Darktable with the option `darktable --library :memory:` but the edits I did weren't saved to the XMP

**Comment by ptilopteri** [comment]
there is an option to write sidecar file for each image
when I run w/o the library and this option enabled, my edits are saved to the xmp files

**Comment by pphotography** [comment]
How do you run without library?

**Comment by c64club** [comment]
It would be perfect if styles/profiles were saved but only "picture library" was not created. Plus regular, straight file manager instead of "importing"  (like in Rawtherapee - AFAIK "non-importing" file manager is unique to RT).

**Comment by TurboGit** [comment]
That's not dt. Keep using rawtherapee.
