### ISSUE TITLE
GUI not showing some icons

### ISSUE THREAD

**Issue by rawfiner** [darktable-org/darktable#2388]
Since the merge of ui-rework, the GUI seems incomplete on my side:
the icons for activating modules, presets, preferences etc are missing.
Also, sliders don't look the same as on @aurelienpierre screenshots.
![Capture du 2019-04-13 10-31-35](https://user-images.githubusercontent.com/34063828/56077029-b48cf800-5dd7-11e9-9176-d045fb9e9121.png)

I am on linux mint Sarah, with libgtk in version 3.18.9, libglib in version 2.48.2.
Launching darktable with commandline does not give any particular error/hint

**Comment by TurboGit** [comment]
Do you have a specific CSS? If so you need to remove it and use the standard one. Old CSS are probably not compatible.

**Comment by rawfiner** [comment]
Unfortunately not, I used an empty folder as a config directory...
I will try to do a git bisect when I find some time (probably during the week) if it can help

Maybe just to try, could you share a CSS which works, so that I can try again with it?

**Comment by TurboGit** [comment]
I'm using the default CSS which is installed here:
`
/opt/darktable/share/darktable/themes/darktable.css `

The md5sum (so you can check that we have the exact same one) is:

```
$ md5sum /opt/darktable/share/darktable/themes/darktable.css 
a3318ba795b184939efb51cff792d438  /opt/darktable/share/darktable/themes/darktable.css
```

**Comment by TurboGit** [comment]
I'm using libgtk 3.24 on my side. @aurelienpierre : what is your libgtk version?

**Comment by edgardoh** [comment]
Same here, and the same happens in darkroom.

**Comment by rawfiner** [comment]
@edgardoh , what version of libgtk are you using?
On my portable computer, I do not have this bug with libgtk 3.22.

**Comment by edgardoh** [comment]
No idea, how do I check that?

**Comment by rawfiner** [comment]
On mint I use this command:
dpkg -s libgtk-3-dev

**Comment by rawfiner** [comment]
I think cmake also prints the library version

**Comment by edgardoh** [comment]
It works here too:

Package: libgtk-3-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 10534
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: gtk+3.0
Version: 3.18.9-1ubuntu3.3
Depends: libgtk-3-0 (= 3.18.9-1ubuntu3.3), gir1.2-gtk-3.0 (= 3.18.9-1ubuntu3.3), libgtk-3-common, dconf-gsettings-backend | gsettings-backend, libglib2.0-dev (>= 2.43.4), libgdk-pixbuf2.0-dev (>= 2.30.0), libpango1.0-dev (>= 1.37.3), libatk1.0-dev (>= 2.15.1), libatk-bridge2.0-dev, libcairo2-dev (>= 1.14.0), libepoxy-dev (>= 1.0), libx11-dev, libxext-dev, libxinerama-dev, libxi-dev, libxrandr-dev, libxcursor-dev, libxfixes-dev, libxcomposite-dev, libxdamage-dev, pkg-config, libegl1-mesa-dev, libwayland-dev (>= 1.5.91), libxkbcommon-dev, libmirclient-dev (>= 0.13.3), libmircookie-dev (>= 0.17.0), nettle-dev
Suggests: libgtk-3-doc
Description: development files for the GTK+ library
 GTK+ is a multi-platform toolkit for creating graphical user
 interfaces. Offering a complete set of widgets, GTK+ is suitable
 for projects ranging from small one-off tools to complete application
 suites.
 .
 This package contains the header and development files which are
 needed for building GTK+ applications.
Homepage: http://www.gtk.org/
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>

**Comment by aurelienpierre** [comment]
> I'm using libgtk 3.24 on my side. @aurelienpierre : what is your libgtk version?

3.24 too here, with glib 2.58. I have seen many exceptions for gtk 3.18 in the code (with pragmas), and I know CSS margins are not available for this version, so this looks like a version compatibility issue.

@rawfiner @edgardoh do you have any way to upgrade GTK ? The version 3.18 was released in November 2015, it's strange it still ships with modern OS/DE.

**Comment by rawfiner** [comment]
I will update gtk yes.
@aurelienpierre , could you add a rule in cmake files so that build fails if gtk is too old?

**Comment by edgardoh** [comment]
I did, this is how it looks now

Text on buttons is supposed to be centered?
History entries are supposed to be bold?

![Screenshot_2019-04-13_16-00-34](https://user-images.githubusercontent.com/16430501/56084211-30059e00-5e06-11e9-938a-5c1955673771.png)
![Screenshot_2019-04-13_16-02-26](https://user-images.githubusercontent.com/16430501/56084212-30059e00-5e06-11e9-99ae-29c73876a881.png)

**Comment by aurelienpierre** [comment]
> I did, this is how it looks now
> 
> Text on buttons is supposed to be centered?
> History entries are supposed to be bold?
> 
> ![Screenshot_2019-04-13_16-00-34](https://user-images.githubusercontent.com/16430501/56084211-30059e00-5e06-11e9-938a-5c1955673771.png)
> ![Screenshot_2019-04-13_16-02-26](https://user-images.githubusercontent.com/16430501/56084212-30059e00-5e06-11e9-99ae-29c73876a881.png)

I suppose you are missing the font roboto roman/regular, but it's supposed to be normal weight in buttons.

>  @aurelienpierre , could you add a rule in cmake files so that build fails if gtk is too old?

yes

**Comment by edgardoh** [comment]
@aurelienpierre , ok, should I install it? how do I do it?

**Comment by aurelienpierre** [comment]
> @aurelienpierre , ok, should I install it? how do I do it?

You should have several roboto font packages in your package manager, the best is to install them all.

**Comment by edgardoh** [comment]
I have installed, now I get this:

![Screenshot_2019-04-14_12-24-27](https://user-images.githubusercontent.com/16430501/56095203-b971aa80-5eb0-11e9-8bb5-45d1307323a7.png)
![Screenshot_2019-04-14_12-24-49](https://user-images.githubusercontent.com/16430501/56095204-ba0a4100-5eb0-11e9-9170-fa1c6efb5256.png)
![Screenshot_2019-04-14_12-25-02](https://user-images.githubusercontent.com/16430501/56095205-ba0a4100-5eb0-11e9-9179-f72d9d6f3b3c.png)

Seems that text buttons is still bold, no idea what happen with the config dialog.

**Comment by rawfiner** [comment]
I have upgraded gtk, I have got the right gui now. I will close the issue once cmake files are updated :-)
