### ISSUE TITLE
merge photo like panorama tools

### ISSUE THREAD

**Issue by chenjie199234** [darktable-org/darktable#2392]
I like landscape photography.
I offen merge several photos into one,so that i can get a big scene.
I can do it in lightroom,but i switch the system from windows to linux.
Will darktable support this?just like the photo merge in lightroom.

**Comment by aurelienpierre** [comment]
There is no plan to do that for now because Hugin does that very well. You can export from dt to Hugin in TIFF 16 bits, then merge in Hugin, then import back the merged TIFF 16 bits in dt.

**Comment by pphotography** [comment]
There's a plugin for Darktable that does that automatically. I got it installed and it does the job very well.
https://darktable.fr/2017/03/weekly-edit-30-plugin-darktable-holger-pour-enfuse/

**Comment by chenjie199234** [comment]
hugin can't match images automatically like lightroom.

**Comment by theres** [comment]
> hugin can't match images automatically like lightroom.

What do you  mean by that? It can do fully automatic pano merge.

I suggest to use https://github.com/darktable-org/lua-scripts/blob/master/contrib/hugin.lua plugin - you get another entry in export module that allow you to automatically stick selected images. You can also check 'lauch hugin gui' to get more control how it's projected, cropped, etc.

**Comment by chenjie199234** [comment]
thx everyone.problem solved.
