### ISSUE TITLE
non-default shortcut to previous image fails

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2393]
previously reconfigured "previous image" shortcut to "B" unshifted seems to toggle the screen zoom to ?borderless? and back rather than the previous image.  checked and reset shortcut to                                                                 
unshifted "b" but still see the ?zoom?  action rather than the previous image.  reset shortcut to "backspace" to no avail.  after setting five or six different keys and several dt restarts, it now respects the unshifted "B" and goes to previous image.

**Comment by Nilvus** [comment]
Not sure to really understand your issue but 'B' shortcut is now to show/hide window border (If I remember correctly that's from the new UI). And shortcuts could be easily edited in tab related section of preferences. So, if you want 'B' for 'previous image', you could change that on prefs and change border shortcut or let it without shortcut if you don't use it.

Maybe this could be closed as I don't think is a real issue (or maybe I don't really understand what you write here). @TurboGit

**Comment by TurboGit** [comment]
Closing indeed. I don't understand either.
