### ISSUE TITLE
input color profile notice

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2394]
I have unset and unused "input color profile" default to "standard color matrix" as I am using filmic.  advancing to next image or previous image invokes an information window announcing "unsupported input color profile has been replaced by linear Rec709 RGB!"

**Comment by edgardoh** [comment]
If you can build a PR try #2389 and run it with -d perf, this seems to happen when the thumb is generated, but I would like to confirm it.

**Comment by ptilopteri** [comment]
color me dumbbb.  I use master builds for openSUSE by darix and the
latest/last is darktable-2.7.0~git996.ef3752478-1161

the subject collection was not newly imported and when imported the import
color profile was not active.

or, I do not understand.

**Comment by edgardoh** [comment]
The message you describe is displayed on the screen, I have added a Pull Request so the text is also displayed on the console, this helps in the diagnostics. But the PR is not yet merged, so I was asking if you can build it from source.

**Comment by ptilopteri** [comment]
* edgardoh <notifications@github.com> [04-13-19 15:13]:
> The message you describe is displayed on the screen, I have added a Pull
> Request so the text is also displayed on the console, this helps in the
> diagnostics.  But the PR is not yet merged, so I was asking if you can
> build it from source.

no, I do not build from source but utilize master builds for openSUSE from
darix.

tks,
-- 
(paka)Patrick Shanahan       Plainfield, Indiana, USA          @ptilopteri
http://en.opensuse.org    openSUSE Community Member    facebook/ptilopteri
Registered Linux User #207535                    @ http://linuxcounter.net
Photos: http://wahoo.no-ip.org/piwigo		    paka @ IRCnet freenode

**Comment by ptilopteri** [comment]
the latest update to master in darix's openSUSE Tw build is corrected.
darktable-2.7.0~git1007.2c02989e8-1169

as far as I am concerned, this issue may be closed
or I can close it???

**Comment by ptilopteri** [comment]
no comment to my previous post, closing issue as solved
