### ISSUE TITLE
[image_cache_allocate] failed to open image 1275328648 from database: unknown error

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2398]
I'm getting this error very often when changing images in darkroom by double-click on the film strip

[image_cache_allocate] failed to open image 1275328648 from database: unknown error

the image number seems to be random and do not exists on the database.

**Comment by junkyardsparkle** [comment]
I've seen this one time so far; I didn't have film strip open at the time, didn't find anything to relate it to.
