### ISSUE TITLE
Drakroom: groups are missing

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2400]
**Describe the bug**
once you go to darkroom the groups are missing

**To Reproduce**
1. Go to 'darkroom'

**Expected behavior**
Groops as before...

**Screenshots**
![Screenshot_20190413_234920_crop](https://user-images.githubusercontent.com/49004103/56085666-41bb6580-5e47-11e9-9715-25b0becb48dd.png)

**Platform:**
 - OS: [gentoo linux]
 - Version [2.7.0+996~gef3752478-dirty]

**Additional context**

**Comment by ptilopteri** [comment]
from the screenshot it appears the left side/column is collapsed
can you not expand it?

**Comment by AxelG-DE** [comment]
#1) it should not matter
#2) nope, is just a cut section :)

**Comment by AxelG-DE** [comment]
darned, started with a new ~/.config/darktable folder and the groups are back.

Now I gonna check, what's the difference in darktablerc...

**Comment by AxelG-DE** [comment]
unfortunately too many differences, I deleted almost any of the "plugin....group" things but still the same. 

I'd be really not that happy if I have to give up my over the years optimized darktablerc :-/ 

@aurelienpierre do you have a hint for me?
I wonder, which kind of incompatibilities could happen with the new design. Once I know this, I could just merge that one line from a from a fresh darktablerc

**Comment by ptilopteri** [comment]
> #1) it should not matter

  yes, if the left-side menus are collapsed, only the triangle will appear, no menus

> #2) nope, is just a cut section :)

I don't understand "cut section" unless you mean not the full screenshot, but
still stands.  if the left-side menus are collapsed, you will not see them.
see two attachments:
![Screenshot_20190414_083739](https://user-images.githubusercontent.com/32614680/56093028-c29f4f00-5e91-11e9-8ba3-238c57e7297d.png)
![Screenshot_20190414_083739](https://user-images.githubusercontent.com/32614680/56093029-c6cb6c80-5e91-11e9-9c73-a529e71c114d.png)

**Comment by AxelG-DE** [comment]
Yes I meant not full screenshot, just a section

But anyhow, I don't get your point. Im not talking about left panel at all. I mean the groups, which usually shown underneath of histogram, they are gone. That's why I provided that screenshot

**Comment by ptilopteri** [comment]
OH, I see now.  I don't have that condition on my system.
![Screenshot_20190414_091952](https://user-images.githubusercontent.com/32614680/56093419-90dcb700-5e96-11e9-8ca3-6fcd1c8cb2ef.png)

**Comment by AxelG-DE** [comment]
That's what I'm missing as long I keep my old darktablerc. Once I use a fresh one it also works :blush:

**Comment by aurelienpierre** [comment]
What is your GTK version ?

**Comment by ptilopteri** [comment]
I am still using my previous darktablerc
GTK 3.24.7-1

**Comment by edgardoh** [comment]
In config->GUI option->show search module text entry you can set if display
groups, search text or both

**Comment by AxelG-DE** [comment]
@edgardoh 
brilliant, that was it. Thank you very much!
Just cannot understand, why it was all over sudden "search" only. I did not change that on purpose.

If one ask me, the "groups" shall be never off, you almost cannot dt without it. So merely the question, whether the search field is on or off...

**Comment by TurboGit** [comment]
Closing then.
