### ISSUE TITLE
UI 2.7: low contrast in histogram of 'tone curve' module

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2402]
**Describe the bug**
In the top-right corner of the histogram in the new 'tone curve' module from version 2.7 the contrast between the histogram data and the background is getting very low. It becomes hard to distinguish from the background.
Foreground is around #969696 and background around #929292 which makes a contrast ratio of 1.05:1
See area in red square below

**Expected behavior**
Contrast should be ok if the background gradient's brightness goes up to the grey that is in the green square below

**Screenshots**
![Contrast_UI](https://user-images.githubusercontent.com/49001045/56086201-e478e180-5e51-11e9-82f0-62855047bb7b.jpg)

**Platform (please complete the following information):**
 - Version2.7.xx

**Comment by Nilvus** [comment]
After some tests and using Gtk inspector, that could not be improved by CSS. Nodes and item around widget tone curve could be edited only, not the graph and histogram on this module.

But now, you could use new rgb tone curve that doesn't have this behavior.

**Comment by Nilvus** [comment]
To be closed as solved by PR #2638 (@TurboGit)

**Comment by TurboGit** [comment]
Closing.
