### ISSUE TITLE
2nd preview: can it be borderless?

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2405]
**Is your feature request related to a problem? Please describe.**
Not a real Problem, just a wish for design.

I'd like to see the 2nd preview window (can I call it 2pW) is borderless, just like dt can do

**Describe the solution you'd like**
same like main window, when I activate that window and press F11 it can be borderless.

**Comment by rabauke** [comment]
I am missing this feature as well. I started to figure out what has to be done to implement a full-screen mode for the 2nd preview and would like to implement this. However, I am not very familiar with GTK gui programming and might therefore need some time (which is lacking). Hints are welcome. Possibly, this is even a trivial task for somebody else.

**Comment by TurboGit** [comment]
I put the second window in the desired screen and press F11 (full screen mode), it is almost borderless this way. Won't this work on your side?

**Comment by AxelG-DE** [comment]
At least for me nothing special happened once I pressed F11

**Comment by TurboGit** [comment]
Well which DE are you using? On GNOME Shell F11 is the "maximize" action.

**Comment by AxelG-DE** [comment]
DE?

As you sufferingly know :smile: I'm using the rolling distro Gentoo with quite up to date KDE. Now on mobile phone, hence cannot check the PC now......

**Comment by TurboGit** [comment]
Sorry, DE -> Desktop Environment

**Comment by AxelG-DE** [comment]
Hihihi
Now you got it.... 
Update kde

I'll not hide, currently I do have issues with keystroke for screenshots (not working) . So I cannot neglect a potential risk something lies within my system...

**Comment by rabauke** [comment]
@TurboGit There might be some desktop environments which provide short keys for maximizing application windows to full screen. But this is not generally the case. For example, F11 does not work for the 2nd preview on my system (Ubuntu 18.04, Gnome). 

Full screen mode for the main window is triggered via `fullscreen_key_accel_callback` in `gtk.c` if I understand the darktable code correctly, not by the desktop environment. A similar mechanism has to be implemented for the 2nd preview window as well.

**Comment by Nilvus** [comment]
I test that and F11 doesn't work for 2nd preview window, as it works great for main window (or other software I use). I'm on Gnome 3.32. So as @rabauke said, it's not implemented. This would be great to implement that. When using two screens, it could be great to have the 2nd preview window on the other screen full size.

For border, It's not possible in state to remove it, even with css (to be more precise, the only way is to change background-color of the windows (which make the border) but that would also change background-color of main-window. That's not what we want. So I see two possibilities here :

- Adding the B shortcut to remove this border on 2nd preview as it's actually the behaviour on main window
- Or add a tag id on window widget on this 2nd preview window. Main window has tag id (as I see with Gtk Inspector) called 'main_window'. If the 2nd window widget have a tag like, for example, 'second_window', it could be possible to just change background-color to middle-grey like widget inside and removing with css the border.

@edgardoh : as you make this 2nd window, what do you think on that ?

**Comment by AxelG-DE** [comment]
As I said borderless at beginning, I also meant the window manager's elements.

Why I emphasize? From above's comment about changing bg colour, I get the feeling, the min/max/hide buttons etc might persist. But I'm newbie on such details so easily be wrong :blush:

**Comment by Nilvus** [comment]
> As I said borderless at beginning, I also meant the window manager's elements.
> 
> Why I emphasize? From above's comment about changing bg colour, I get the feeling, the min/max/hide buttons etc might persist. But I'm newbie on such details so easily be wrong blush

What do you mean for "window manager's elements' ? If you mean about min/max/hide buttons, that's just related on full screen or not, so that "F11" feature to go on full screen is not implemented.

There's really two things here : possibility to go full screen or not and border. And they are not related.

**Comment by edgardoh** [comment]
@Nilvus , no idea about any of this, but I can look into it.

**Comment by AxelG-DE** [comment]
@Nilvus
I am afraid you got me :blush:

Yes I mean Full screen, fortunately I said F11 at beginning ;-)

**Comment by Nilvus** [comment]
@AxelG-DE or @TurboGit : to be closed as the PR is merged !

**Comment by TurboGit** [comment]
Closing!
