### ISSUE TITLE
Histogram: exposure-infos missing

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2406]
**Describe the bug**
previously histogram had shutter speed, aperture and ISO, which I found useful. Currently is missing

**Expected behavior**
as before or switchable (or am I just unable to do so?)

**Screenshots**
Now
![Screenshot_20190413_234920_histogramm_new](https://user-images.githubusercontent.com/49004103/56091266-26834100-5ead-11e9-9b8d-2730143e2902.png)

previously
![Screenshot_20190413_234920_histogramm_old](https://user-images.githubusercontent.com/49004103/56091271-31d66c80-5ead-11e9-817c-2199885347e6.png)

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [2.7.0+998~g959466989-dirty]

**Additional context**

**Comment by theres** [comment]
It has been discussed in #2041, you can now enable similar functionality in configuration that will show you these informations above histogram:
![image](https://user-images.githubusercontent.com/1242921/56091486-ce017300-5eaf-11e9-80b6-428ff11190f8.png)
It is avaliable in: `GUI options -> pattern for the image infos line`  and  `GUI options ->  position of the image infos line`. As you can see you can now adjust shown information and the information placement (you cannot show it directly on the histogram though).

**Comment by AxelG-DE** [comment]
@theres thank you very much!

can I close this here, and if so, how (sorry if that is a too noob question)

**Comment by pphotography** [comment]
I do not have DT 2.7 the new UI yet, question: 
What is the default setting when upgrading to this version, is this info visible? imho it should be visible for not to confuse users.

**Comment by AxelG-DE** [comment]
with my "old" darktablerc, it is top-center, but due to another [issue 2400](https://github.com/darktable-org/darktable/issues/2400) I had to start with a fresh darktablerc and there it was "bottom"

Actually top-center is cool, as it uses anyway free space and the histogram is bigger though...

**Comment by gadolf66** [comment]
> I do not have DT 2.7 the new UI yet, question:
> What is the default setting when upgrading to this version, is this info visible? imho it should be visible for not to confuse users.
When I upgraded yesterday, it was shown bottom center, between the film roll and the main view. Regarding the arrow to minimize the film roll, the first click minimizes the film roll, the second click hides the image information. I didn't like it this way, so I followed @theres tip and set it up to top right.

**Comment by TurboGit** [comment]
Right, now those data are in the bottom center area and can be configured in pref.
