### ISSUE TITLE
Hot pixels / impulse noise reduction now working

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#2407]
**Describe the bug**
In Rawtherapee, turning on Impulse Noise Reduction module eliminates many hot pixels.
In Darktable, turning on Hot Pixels doesn't, even changing the sliders.
Please, maximize the view of the screenshots below to be able to see some hot pixels.
RT before:
![Screenshot from 2019-04-14 13-25-57](https://user-images.githubusercontent.com/46730249/56096010-f2158200-5eb8-11e9-926f-9cc3716b7901.png)
RT after:
![Screenshot from 2019-04-14 13-26-01](https://user-images.githubusercontent.com/46730249/56096012-f477dc00-5eb8-11e9-9254-1df42fa045bb.png)

**To Reproduce**
1. Download [this file](https://drive.google.com/open?id=1iuGZlPSLoWvCQmnqy1J3j2Pcv5GpPWA0)
2. Open the file with DT and zoom in the same region show in the screenshots at 400%
3. Turn on Hot Pixels module

**Expected behavior**
The hot pixels should be eliminated as in Rawtherapee

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 2.7.0~git1000.83e5e4a60

**Additional context**

**Comment by TurboGit** [comment]
Can't comment I don't use RT. But hot-pixels in dt is working on my side. The algo in RT may be different and this is only for hot-pixels in dt where photosite/pixels may be dead. In RT is it named with "noise reduction". To me that different modules.
