### ISSUE TITLE
Rearrange controls in 'exposure' module UI

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2409]
**Is your feature request related to a problem? Please describe.**

**a)** The most important and most used control in the 'exposure' module is the exposure slider. 
It should be positioned in the UI for easiest access. When I open the 'exposure' module I have to scan several lines until I get to the exposure slider:
- mode
- black level correction
- exposure

**b)** The word 'mode' is much closer to the text below than to its option to the right ('manual'). This looks like the 'mode' belongs to the text below. 

**Describe the solution you'd like**
**a)**  I'd like the exposure slider to be positioned above the 'black level correction' slider
**b)**  I'd like the word 'mode' to be removed and inserted into the menu entries to the right ('manual mode' and 'automatic mode')

With this changes the word 'exposure' is on the top right corner within the module and the first text a user reads after opening the module.

See mockup below:

![Exposure_new](https://user-images.githubusercontent.com/49001045/56099299-3d588080-5f0b-11e9-90e5-bb025b4be1e9.jpg)

**Comment by AxelG-DE** [comment]
Currently I'm fine with the given layout. 

Also I could be flexible and accept the change. In order to make the new style more obvious, I suppose having a separation, e.g. by a blank line, between exposure and black level correction.

**Comment by saknopper** [comment]
This hasn't been a huge pain for me, only a minor annoyance. But I do agree that the proposed solution would make things better in my opinion.

**Comment by aurelienpierre** [comment]
That makes sense.
