### ISSUE TITLE
Lua scripts in GENTOO

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2410]
**This is not a dt-bug, I know...**
I'm referring to this [#2392](https://github.com/darktable-org/darktable/issues/2392) as I also would like to use pano_pro plugin

dt requires LUA >=5.2 
GENTOO, due to lack of maintainers merely offers 5.1 (pls. no discussions about distro shortage, which it is)

I tried with other repository thru overlay. Finally did not work out, just caused pain...

Is there any chance, dt could also accept LUA-5.1?

**Comment by parafin** [comment]
There is lua-5.2 in gentoo, it's just masked. Or you can use lua bundled with dt. DT won't support multiple lua version.

**Comment by AxelG-DE** [comment]
That masked Lua is, what caused the pain. I was wrong with overlay. 

But sorry, what did you mean with Lua bundled with dt? How to use, how to activate? Sorry if that sounds silly, even I am quite experienced with Linux and even gentoo....

**Comment by parafin** [comment]
-DDONT_USE_INTERNAL_LUA=OFF option for cmake call, you will have to modify darktable ebuild I guess.

**Comment by AxelG-DE** [comment]
I tried this part as well. Finally I gave up as I got more headaches than solutions :-/

**Comment by AxelG-DE** [comment]
How could I activate internal LUA on git-master? That I build with the normal build.sh
