### ISSUE TITLE
Compress history in lighttable enables disabled modules

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2412]
**Describe the bug**
When there are disabled modules in the history stack, compressing history turns them back on instead of removing them from the stack.

**To Reproduce**
1. Enable then disable one module in darkroom
2. Go back to lighttable and trigger "compress history"
3. Check the history in darkroom : disabled modules are now on.

**Comment by AxelG-DE** [comment]
Is it possible, there is a fix already 
I tried to reproduce and for me everything is fine. I am on: darktable 2.7.0+1025~g0384a4bb1-dirty

**Comment by aurelienpierre** [comment]
I can't reproduce anymore.

**Comment by s5k6** [comment]
This bug persists for at least "white balance", and maybe other modules.
