### ISSUE TITLE
New GUI Issue

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2418]
Right now this is only a question, not a bug report or a feature request:

I have upgraded to xubuntu 18.04 (GTK is the right version) and installed Roboto. The GUI now looks like the following, is this how it is supposed to look? If not, what can I do?

**Comment by edgardoh** [comment]
![Screenshot_2019-04-16_16-23-59](https://user-images.githubusercontent.com/16430501/56238371-bc150100-6064-11e9-9b68-543c10d92e82.png)
![Screenshot_2019-04-16_16-24-40](https://user-images.githubusercontent.com/16430501/56238372-bc150100-6064-11e9-8f45-4d442102f0bf.png)
![Screenshot_2019-04-16_16-24-56](https://user-images.githubusercontent.com/16430501/56238373-bc150100-6064-11e9-8e3a-bf7e1b1c2087.png)

**Comment by Nilvus** [comment]
Bold text doesn't fit to darktable-elegant theme so it seems to not apply correctly.

Have you just tried to change theme one time and revert back to darktable-elegant theme ?
I've had the same UI than yours and doing this then display the correct UI

**Comment by edgardoh** [comment]
Yes, I have changed from darktable to elegant and back several times.

**Comment by TurboGit** [comment]
Indeed, the buttons on your side seems bold, strange.

**Comment by aurelienpierre** [comment]
Buttons are supposed to be semi-bold (`font-weight: 600`), which supposes you have a semi-bold Roboto font variant installed under the name "Roboto Medium". Otherwise, we could try a font weight of `500` (`400` is supposed to be normal, `700` is bold).

**Comment by edgardoh** [comment]
Just upgraded to 18.10 and it looks nice now, so it seems that I had some issue on my system.

If this is how it is supposed to look the only thing left is the config dialog that has all the controls too big.

![Screenshot_2019-04-19_16-25-10](https://user-images.githubusercontent.com/16430501/56440566-2a093480-62c0-11e9-9bf6-edefecb0996f.png)

**Comment by TurboGit** [comment]
Last screenshot looks as expect (very nice) to me.

**Comment by edgardoh** [comment]
Yes, is nice indeed.

About the config dialog, it is also as expected or I still have some issues
on my side?

**Comment by TurboGit** [comment]
I do not see anything wrong with the pref dialog from the screenshot.

**Comment by edgardoh** [comment]
Controls (widgets?) are a lot bigger than use to be, or maybe I remember wrong?

**Comment by aurelienpierre** [comment]
> Controls (widgets?) are a lot bigger than use to be, or maybe I remember wrong?
which controls ?

**Comment by edgardoh** [comment]
On the config dialog, text entries, check box, combo box, etc are bigger than I remember.

**Comment by edgardoh** [comment]
@TurboGit , why did you close this? I still don't have an answer, and the "issue" is still present.

**Comment by edgardoh** [comment]
Never mind, I just saw a printscreen in #2128 with the same issue, I'll file a new bug report.
