### ISSUE TITLE
Tone curve creates countless new entries/lines in history stack

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2420]
**Describe the bug**
when ever you click or track anything in the controls of tone curve, it creates a new entry in the histroy stack. Rapidly you reach 300 lines and lose all performance of dt.

**To Reproduce**
1. Go to 'darktroom'
2. Click on 'tone curve'
3. drag the black point to somewhere or activate a mask and change chormacity'
4. enjoy the error

**Expected behavior**
like all the other modules and the behavior before, there should be merely one line in history stack per each attempt to change or edit

**Screenshots**
![Screenshot_20190417_230102](https://user-images.githubusercontent.com/49004103/56320622-dc2be980-6164-11e9-970f-31b44ef41440.png)

**Platform (please complete the following information):**
 - OS: [ gentoo linux]
 - Version [darktable 2.7.0+1025~g0384a4bb1-dirty]

**Additional context**

**Comment by AxelG-DE** [comment]
maybe it is not just, or not at all a tone curve issue, just now I figured strange things in the history stack... (unfortunately cannot reproduce that color zones created hell of line too)

**Comment by TurboGit** [comment]
I also get this from time to time (rare though) and generally compressing the history fix the issue.

**Comment by AxelG-DE** [comment]
Yes compressing history stack does help unless you touch tone curve again :-)

Actually 2.7-1040 does not show this behavior anymore. Probably this issue can be closed?

**Comment by TurboGit** [comment]
Ok, closing.

**Comment by AxelG-DE** [comment]
@TurboGit 
acc. to #2538 does it make sense, to reopen this one?

**Comment by AxelG-DE** [comment]
@TurboGit
Please see this video at around 9 minutes and please reopen this bug report. 

@brucewilliamsphotography is using official release, and I still see this on git-master from time to time. 

Also I have big suspiciousy, once we solved this, we might also solve other performance issues like #2514

Thanks in advance!

**Comment by dtorop** [comment]
I've also seen this over the years, but not recently. Hard to remember, but my suspicion may have been that it happened with older XMPs being opened with newer versions of darktable, but I never verified this. Perhaps the workaround was to switch to lighttable then back to darkroom.

**Comment by AxelG-DE** [comment]
@dtorop
That pic from Bruce was a very new one, so was my case. 

In that #2514 case I have a similar issue, that every time I change levels, I get a new entry in history stack. Indeed workarounds are possible but it feels buggy...

**Comment by matejmarti** [comment]
I have the same issue, currenty with 2.7.0+1477. It happens in multiple modules, for example in the graduated density module as you can see in the screenshot. The module creates an entry in the history module for every mouse click. Dragging the hue-slider with the mouse also creates multiple entries at once. Compressing the history helps, for this particular image. On the next image the same problem appears again. 
![weird_history](https://user-images.githubusercontent.com/46395848/60485102-11dc6b00-9c9c-11e9-83ea-4476979ce642.png)

**Comment by AxelG-DE** [comment]
If I remember correctly, I have one open and one closed issue in github. Just look after AXELG-DE and hook on it. Pascal knows about this, but currently thinks, compressing history stack is good enough :-) Von meinem Mobiltelefon gesendet-------- Ursprüngliche Nachricht --------Betreff: Re: [darktable-org/darktable] Tone curve creates countless new entries/lines in history stack (#2420)Von: matejmarti An: darktable-org/darktable Cc: AxelG-DE ,Author I have the same issue, currenty with 2.7.0+1477. It happens in multiple modules, for example in the graduated density module as you can see in the screenshot. The module creates an entry in the history module for every mouse click. Dragging the hue-slider with the mouse also creates multiple entries at once. Compressing the history helps, for this particular image. On the next image the same problem appears again.

**Comment by edgardoh** [comment]
@matejmarti , can you share the xmp?

**Comment by matejmarti** [comment]
@edgardoh sure, please see attached (I've changed the ending to .txt) The first xmp is the original. dt showed a history as in the picture above. The second xmp is from the same file, but after clicking "compress history stack"
[20190629_P6290090.ORF_original.xmp.txt](https://github.com/darktable-org/darktable/files/3355854/20190629_P6290090.ORF_original.xmp.txt)
[20190629_P6290090_history_compressed.ORF.xmp.txt](https://github.com/darktable-org/darktable/files/3355855/20190629_P6290090_history_compressed.ORF.xmp.txt)

**Comment by edgardoh** [comment]
I can't duplicate it by loading the xmp, anything else you can add to help
duplicate the issue?

**Comment by matejmarti** [comment]
Hm... interesting. I've noticed it with a lot of modules on a lot of images. I can't say for sure if it's happening with every image, I will test it the next few days. I'm running 2.7.0+1477 on Windows 10.
