### ISSUE TITLE
Previews get regenerated

### ISSUE THREAD

**Issue by aadm** [darktable-org/darktable#2421]
**Describe the bug**
In lighttable, full screen previews are recomputed over and over again.

**To Reproduce**
1. go to lighttable
2. select image
3. hit whatever shortcut key is assigned to preview or sticky preview
4. exit to default grid view
5. select another image, display preview
6. go back to previous image, display preview; Darktable recomputes the preview as it has never stored the previously computed version.

**Expected behavior**
Previews should be stored and not recomputed over and over again. This does not happen in 2.6.2. Also generating thumbnails beforehand with `darktable-generate-cache` does not solve the problem; when a preview is displayed the first time, darktable correctly recalls the version stored on disk, but the second time triggers the recomputation.

**Platform:**
 - OS: Ubuntu 18.10
 - Version: 2.7.0~git1007.2c0298e8

**Comment by Nilvus** [comment]
Yes, I confirm this issue. It's quite a loose time as previous versions doesn't have this behavior.

**Comment by TurboGit** [comment]
A quite annoying issue ! I'll mark it for 2.8. We'll discuss that when AlicVB is back. Thanks for reporting.

**Comment by AlicVB** [comment]
ok, I've done a PR to fix it. Now the full preview mipmaps are written to disk, instead of being recompute each time. (for the full res mipmap, you have to enable it in the prefs.)
Thanks for reporting

**Comment by AlicVB** [comment]
> I would add that when using zoom in on lighttable, preview took regularly too much time to be generated. Trying same thing on darkroom take much less time than on lighttable

That's "normal" : in darkroom, there's some complex mechanism to only compute the part of the image needed for display. In lighttable, the full image at the needed resolution is computed.
Maybe something to enhance in the future, but I fear than this would imply to rework a large part of the mipmaps code...
