### ISSUE TITLE
 GLib-GObject-WARNING when apply a style

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2425]
When apply a style from darkroom I get this warnings:

(darktable:13609): Gtk-CRITICAL **: 16:57:46.351: gtk_label_set_markup: assertion 'GTK_IS_LABEL (label)' failed

(darktable:13609): GLib-GObject-WARNING **: 16:57:46.351: invalid cast from 'GtkDarktableButton' to 'GtkLabel'

This is from here:
https://github.com/darktable-org/darktable/blob/master/src/develop/develop.c#L1027

I guess that expander widgets has changed, but I don't know how it works now.

**Comment by TurboGit** [comment]
Should be fixed now. Thanks for reporting.
