### ISSUE TITLE
Controls in global preferences are almost twice as big as the ones in modules

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2428]
Controls in global preferences are almost twice as big as the ones in modules, see in print screen the text entry compared with the one in the export module.

It should be the same or have some way to configure it.

**Comment by edgardoh** [comment]
![Screenshot_2019-04-19_16-25-10](https://user-images.githubusercontent.com/16430501/56457856-fd542c00-6356-11e9-80b7-76c3e5c34700.png)

**Comment by Nilvus** [comment]
dialog prefs is made of a grid, so entry, label, etc. adjust their height on the line.

The only way I see is to remove margin on this tag css :
dialog *
{
  margin: 0pt;
  padding:0;
}

On actual css from @aurelienpierre, the margin is 1pt;

This margin is here to aerate the options. See how prefs looks when margin is put on 0 :

![Capture-20190517205940-806x830](https://user-images.githubusercontent.com/45535283/57950284-1e248880-78e7-11e9-85ff-9765c04bcfca.png

**Comment by edgardoh** [comment]
Looks better to me.

BTW, your message is not on github, did you send it by mail or directly on
the issue? I ask because I have lost some of my and I'm not sure why.

**Comment by Nilvus** [comment]
> Looks better to me. BTW, your message is not on github, did you send it by mail or directly on the issue? I ask because I have lost some of my and I'm not sure why. El vie., 17 may. 2019 a las 16:03, Nilvus (<notifications@github.com>) 

No, I delete just after posting it as I find a better way. I will, this week-end, post a new PR with other improvements on the UI. Stay on !

**Comment by Nilvus** [comment]
@edgardoh : as the PR is merged, could you please close your issue if the new prefs window is ok for you ? Thanks.

**Comment by edgardoh** [comment]
Sure, and thanks for your work!
