### ISSUE TITLE
Bottom bar in color zones too small

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2429]
The bottom bar in color zones is too small, it should be bigger or configurable.

![Screenshot_2019-04-20_10-35-39](https://user-images.githubusercontent.com/16430501/56458116-080fc080-6359-11e9-8b88-b9f2d9b3e101.png)

**Comment by TurboGit** [comment]
Indeed, should be themed as the sliders I think.

**Comment by TurboGit** [comment]
Now fixed.
