### ISSUE TITLE
Filmic - middle gray auto tune

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2430]
**Describe the bug**
Clicking on the middle gray luminance color picker , it changes black and white cursors too.
Actually I don't know if this behavior is wanted or not, but it causes to me an issue when I'm trying to use this module. I remember this picker applied its effects only on middle tones.
At the same time, moving the middle cursors, it causes black and white ones to change too.

**To Reproduce**
1. click the color picker on middle gray luminance

**Platform (please complete the following information):**
 - OS: ubuntu
 - Version 18.10

**Comment by Nilvus** [comment]
It's a normal behavior as it keeps good balance between black and white. But you also could change them separately after middle gray auto tune, with white auto tune then black one and you could also adjust manually each black and white slider.

**Comment by aurelienpierre** [comment]
Please read the doc.

**Comment by PaoloAst** [comment]
Sorry, Aurelien, but I remember (possibly I'm wrong) that in the past that module were working differently. Now all is clear. Thanks
