### ISSUE TITLE
Retouch color picker getting darker colors

### ISSUE THREAD

**Issue by hellbuster** [darktable-org/darktable#2432]
When using the color picker for the **fill tool** on the **retouch module**, I consistently get darker colors than expected. I compared the results with the global color picker, but it gets the correct colors. I attached a screenshot showcasing the problem.
![screen-2019-04-20-19:09:11](https://user-images.githubusercontent.com/650365/56463360-8b083980-63a0-11e9-8d43-66738ec127a8.png)

 - OS: Archlinux
 - Darktable version 2.6.2

**Comment by edgardoh** [comment]
If you mean on the module's color button, that's expected. This is the
color at that point on the pipe, what you see on the screen and with the
global color picker are the color at the end of the pipe, with all other
modules applied.

If you fill an area with that color you should see (on the screen) the same
as the source.

**Comment by hellbuster** [comment]
Oh, you are right! That explains why I was getting artifacts if I picked the "real" color manually.

I am worried that this make the tool a bit unintuitive at first, so a mention on the manual would be the first step, but maybe a warning to the user on the tool itself could be useful?

**Comment by TurboGit** [comment]
>  but maybe a warning to the user on the tool itself could be useful?

The doc will solve that.
