### ISSUE TITLE
[lens correction] Missing Camera Olympus E-M5 Mark II and objective Olympus M.Zuiko Digital ED 40-150mm F2.8 Pro / 12-40 F2.8 Pro support

### ISSUE THREAD

**Issue by Swissbite** [darktable-org/darktable#2434]
**Is your feature request related to a problem? Please describe.**
I'm getting the message "please choose camera / objective manually" on  "objective correction" while shooting with my Olympus E-M5 Mark II camera and my Olympus M.Zuiko Digital ED 40-150mm F2.8 Pro or my ... 12-40mm F2.8 Pro objective mounted. So the objective correction dialog is not prefilled

**Describe the solution you'd like**
Automatic detection of my camera / objective model

**Describe alternatives you've considered**
None except not using darktable 

**Additional context**
Today, I've uploaded two images on raw.pixls.us with both lenses adapted. One has a comment of the mounted objective, the other has not.

**Comment by Nilvus** [comment]
This module use lensfun library. Before, darktable read exif infos to know which camera and lens you use with exiv2 library. So it's probably not really a darktable issue. Which version of these two libraries do you use ? And on which OS (name and version) and darktable do you use ?
For example, on last master branch of darktable, lensfun 0.95 and exiv2 0.25.4, on Linux, I see your camera and your lenses on "objective correction" module.

**Comment by AxelG-DE** [comment]
So guys, 
I am on:
- 2.7.0+1045~gd9b652cf1-dirty
- lensfun 0.3.2-r1
- exiv2 0.27.0-r2

I do have an em5 mk II my own and it is properly recognized fully automatic.

So I hope @Swissbite, you can confirm that one of your libs was out of date or missing :lightsmile:

**Comment by Swissbite** [comment]
I'm on:

- Ubuntu 19.04
- Darktable: 2.6.2 snap Version (https://snapcraft.io/darktable)

After your hints I think the issue is already reported on https://github.com/kyrofa/darktable-snap/issues/16

**Comment by AxelG-DE** [comment]
@Swissbite 
when did you last time run
`/usr/bin/lensfun-update-data`??

**Comment by Nilvus** [comment]
> I'm on:
> 
>     * Ubuntu 19.04
> 
>     * Darktable: 2.6.2 snap Version (https://snapcraft.io/darktable)
> 
> 
> After your hints I think the issue is already reported on [kyrofa/darktable-snap#16](https://github.com/kyrofa/darktable-snap/issues/16)

I am on Ubuntu 19.04 and have your camera and lenses and the module. Running command AxelG-DE update lensfun db and will add your camera and lenses.

**Comment by Swissbite** [comment]
Until now: Never. The tool was not installed.
But even after installing `liblensfun-lib` and execute `/usr/bin/lensfun-update-data` it does not take an effect on the darktable. Be aware: I am using the *snap* version.

**Comment by AxelG-DE** [comment]
@swissbite
I know nothing about snap version, also I think it doesn't matter, because darktable does not "include" lensfun rather refers to it. 

As it does work perfectly for others and me, I think, there's nothing to be done but your config to be checked. 

Hence the question still remains:
- which lensfun version you use? 
- which exiv2 version you use? 

Ideally the same than mine....

**Comment by Swissbite** [comment]
As I said: With a snap version, everything is included **within** the snap package. So I cannot say which version of lensfun and exiv2 (and db version) is defined in the snap package. I will install the default debian way (with apt install ...) and I am sure, that it will work afterwards..
