### ISSUE TITLE
Nikon icm profile not supported

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#2438]
**Describe the bug**
An icm profile for the Nikon D4s is stated as "Not supported" and "replaced by linear RGB rec709". 

**To Reproduce**
1. copy the profile into .confg/draktable/color/in
2. run dt and load a photo into the darkroom
3. input color profile module, profile, then select the profile

**Expected behavior**
the profile should be applied

**Screenshots**
No screenshots.

**Platform (please complete the following information):**
 - ubuntu 18.04 LTS
 - darktable 2.6.1 (latest 2.4 was affected too)
[D4s.zip](https://github.com/darktable-org/darktable/files/3108025/D4s.zip)

**Additional context**

**Comment by edgardoh** [comment]
The output on the console:

[colorin] input profile color space `YCbr' not supported

Only RGB profiles are supported.

**Comment by TurboGit** [comment]
So nothing to fix.

**Comment by FalCT60** [comment]
Oops !
I was on the way to ask how the same software that had correctly generated the profile for both my D700 and N1V1 could have done something bad for the D4s, but, now, I am not sure anymore - there must have been updates that could explain this.
Rgrds,
