### ISSUE TITLE
Put unreadable files at the bottom list - always

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2439]
**Describe the bug**
Unreadable files are mixed with readable files. This causes various issues like Dt hanging or crashing apart to display nothing, in the case you *select* such unreadable files - which happens then and when. if you've a workflow you look not always for the next file when you're in dark room, especially if you deal with many many pictures. 

**To Reproduce**
Just check for unreadable files by looking for **ugly** space-invaders-skull-icons

**Expected behavior**
Put unreadable files at the bottom of the list in lighttable no matter how filter criteria looks like. And yet better add some recover mechanisms (for files in the same path-i don't talk about moved files) and if not possible, a hide-from-list preferences. 
It's possible that Dt refuses to read files with extension ".JPG" and extension ".jpeg" ? I had such cases. 

**Platform (please complete the following information):**
 - OS: Mac 10.11
 - Version 2.6.1

Edit. 
I get many unreadable files.. Maybe a 8% (40 unreadable on 500 files) Else I'd not bother just for the sake to submit a bug report

**Comment by Nilvus** [comment]
A filter would be better and sufficient I think. But the best way is to avoid having these images by using correctly darktable (ie : never move or delete, etc. outside of darktable ; unreadable files means files changes outside darktable, so library is not updated). So the main way to resolve it is to have correct usage !
