### ISSUE TITLE
Will darktable support stack images

### ISSUE THREAD

**Issue by chenjie199234** [darktable-org/darktable#2446]
Will darktable support stack images,just like ps,not the panorama
It is very useful to use this to:
merge night sky images
remove people in images
make a beautiful night city image,cars have light trails...
soft water surface.
beautiful clouds..
etc.
Darktable has hdr function,i think it is very similar to make stack images function.

**Comment by TurboGit** [comment]
I doubt this will be done but we never know. You are looking at a composing software and GIMP seems more appropriate for this.

**Comment by pphotography** [comment]
There's the 'Enfuse Pro' plugin for Darktable that can do stacking. 
https://www.multimedia4linux.de/index.php/fotografie/magic-lantern/12-darktable/143-darktable-tutorial-pano-pro-plugin

Think that an automated translation should help

**Comment by wpferguson** [comment]
There is also a lua-script int the darktable lua-scripts repository, https://github.com/darktable-org/lua-scripts, that does this: contrib/image_stack.lua.
