### ISSUE TITLE
Darkroom: improve style management

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2451]
**Is your feature request related to a problem? Please describe.**
The situation: I have edited a photo and now I want to save the history stack as a style.
I click on 'create a new style from history stack' and see the 'create new style' window. Here I have the following issues:

* The list of history steps to be included is incomplete. Some checkboxes are active and some are not. To use all history steps I have to click on many checkboxes.
* Since I cannot overwrite an existing style I have to keep version numbers or naming conventions in mind. When I accidentally enter a style name that already does exist, the saving process ends with an error message.
I have to click on 'create a new style from history stack' again and have to reclick many checkboxes. I choose another name and hope that it is unique now.

**Describe the solution you'd like**
I like to have the following features:
* When the 'create new style' window opens I want all checkboxes to be activated. If there is a reason why not all are active, there should be a 'select all' button.
* When I try to save a style with a name that already does exist, I want a dialog saying 'This style name already exists. Do you want to overwrite?' and two buttons 'Yes' and 'No'. When I click 'Yes', the old style is overwritten. When I click 'No' I am back in the 'create new style' window with the previously entered data (names and checkboxes).

**Comment by AxelG-DE** [comment]
I am on 2.7.0+1061~g1008a7868 and I can confirm your point first bullet point. I do not remember, it was like this in the past...

**Comment by wpferguson** [comment]
I just tried it with a 2.7 build and the all the unchecked items, except for basecurve and orientation, had drawn masks.  Since basecurve and orientation are always on, or were until just lately, I can understand why they wouldn't be checked.  I'm not sure why a module with a drawn mask wouldn't be included.  Multiple instances of a module also do not get selected.  2.6.2 also works this way.
