### ISSUE TITLE
Use exif variables in metadata fields for retrieving date, etc. when importing files

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#2452]
**Is your feature request related to a problem? Please describe.**
Allow exif variables into the metadata fields at import

**Describe the solution you'd like**
Be able to type something like "Copyright $year J.-Luc" into one of the fields, then dt automatically replaces $year by the corresponding value read from the currently being imported file.

**Describe alternatives you've considered**
Filling the field manually, but this can be a probllem for files that were taken long ago, and one can't remember at which date. Currently the only option.

**Additional context**

**Comment by FalCT60** [comment]
I hoped it would be done with dt 3.0, alas it is not afaik.

**Comment by phweyland** [comment]
Very old issue. In you haven't encountered a solution, here a suggestion:
With selected export configuration (right to "export" button), you can build the string for the "rights" metadata of your choice based on different variables ($(YEAR), $(CREATOR)...).
And if ok for you, please close the issue.

**Comment by FalCT60** [comment]
Sorry, but what I need is not export metadata, but **_retrieve them_** from pictures on **_import_**.
This has not been possible so far, I hope it will in a future release.
Yes, this issue is very old, indeed - even older since I already asked it 2 years befor on the previous board, and even before on the list - and yet not solved, alas !

**Comment by phweyland** [comment]
> but **_retrieve them_** from pictures on **_import_**.

Sorry. Got it. Interesting indeed.
Have you looked on the side of lua scripts ?

**Comment by FalCT60** [comment]
I wish I were a programmer...

**Comment by johnny-bit** [comment]
@FalCT60 - consider changing title of the issue to mention that you want exif metadata on IMPORT and edit issue opening post to clearly state the issue is with import :)

**Comment by FalCT60** [comment]
Title edited.
However, note that the first post mentioned the import need twice in both the first two lines.
To sum-up, what I wish lays on the screenshot :
![Darktable2452](https://user-images.githubusercontent.com/49912948/102828928-32dfd100-43e6-11eb-8cb2-ff679848a601.png)

**Comment by johnny-bit** [comment]
@wpferguson - is this something currently existing lua script can do somehow or does it have to be coded in import flow?

**Comment by phweyland** [comment]
> To sum-up, what I wish lays on the screenshot :

Understood. That makes sense. Just a bit of wiring... :smile:

**Comment by wpferguson** [comment]
@johnny-bit there is a post-import-image event in the lua api that gets triggered after each image is imported.  It can run a callback and supplies the image to the callback.  I've wrote variable substitution for the postsharpen.lua script so that already exists.  So, yes we can do this.  The issues would be:

* we'd be specifying metadata in 2 or 3 places (import dialog, settings?, metadata module, and then this one...)
* the call is blocking.  I'm guessing that import is threaded, but if not we'll slow it down by another database write (maybe, not sure if writes are cached).
* I have to find time to write it :smile:

Here's the variables I currently have:

```
placeholders = {"ROLL_NAME","FILE_FOLDER","FILE_NAME","FILE_EXTENSION","ID","VERSION","SEQUENCE","YEAR","MONTH","DAY",
                  "HOUR","MINUTE","SECOND","EXIF_YEAR","EXIF_MONTH","EXIF_DAY","EXIF_HOUR","EXIF_MINUTE","EXIF_SECOND",
                  "STARS","LABELS","MAKER","MODEL","TITLE","CREATOR","PUBLISHER","RIGHTS","USERNAME","PICTURES_FOLDER",
                  "HOME","DESKTOP"}
```

**Comment by wpferguson** [comment]
I could also do it using a post-import-film event, so that it would run after the import
