### ISSUE TITLE
parametric masks: share between modules, copy/paste and mask manager

### ISSUE THREAD

**Issue by althio** [darktable-org/darktable#2457]
**Is your feature request related to a problem? Please describe.**
I want to apply the same selection to several modules.
This is possible for drawn masks, with `created shapes` in the mask manager, dropdown in module with `add existing shape` or `use same shape as: (other module)`.
This is not possible with parametric masks.

**Describe the solution you'd like**
I would like to have the same functionalities for sharing parametric masks (their "parameters") than with drawn masks (their "shapes").
This could be done in module with a dropdown with `add existing parameters` or `use same parameters as: (other module)`.
This could be done in the mask manager with a new box `existing parameters` (similar to `created shapes`).
Just like shapes, "parameters" could be renamed (with names such as "dark zone", "blue cast", "red and orange objects" ...).
Power users could use set operators to define a combinaison of parametric masks.

**Comment by aurelienpierre** [comment]
You have raster masks in 2.7 now that allow to duplicate the output (not the params) of any module's mask to apply it elsewhere. There is no raster mask manager though (in the same sense as the drawn masks).

**Comment by chhil** [comment]
It would be great to have a raster mask manager. 
Raster masks are not always available based on where they are in the pipeline.
