### ISSUE TITLE
User manual: images don't load

### ISSUE THREAD

**Issue by jshholland** [darktable-org/darktable#2461]
The images in the Darktable user manual at https://darktable.gitlab.io/doc/en/ don't load, and just 404 instead.

![image](https://user-images.githubusercontent.com/107689/56851142-b391b580-6903-11e9-813d-f29ce1809bbc.png)

**Platform:**
 - Firefox v66

**Comment by Nilvus** [comment]
Manual is on gitlab and I've posted an issue some time ago (but I don't suit if it was solved). See here : https://gitlab.com/darktable/doc
It's seems that a merge request that solve that is waiting to be merged. @upegelow or @TurboGit, could you see that ?

**Comment by TurboGit** [comment]
Now merged! I did not get a notification for this PR :(
