### ISSUE TITLE
lensfun error on Sigma lens

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2463]
**Describe the bug**
With Sigma 10-20mm F3.5 mounted on a Pentax K-5 this message appears:
[Lensfun] /home/paolo/.local/share/lensfun/updates/version_1/slr-sigma.xml:1646:104: Unknown attribute `distance' for element <distortion>!

**To Reproduce**
1. Open a raw file and use "lens correction module"
2. check the lens correction applied
3. see the error on CLI

**Expected behavior**
The lens was correctly recognized some time ago

**Screenshots**
See attached image
![Schermata da 2019-04-27 17-45-58](https://user-images.githubusercontent.com/43513892/56851882-80a3ed80-6914-11e9-9c78-c2e421c9390c.png)

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version 19.04

**Comment by junkyardsparkle** [comment]
You happened to grab an update at just the right time to get the problematic element; It's [fixed now](https://github.com/lensfun/lensfun/commit/d5b87fc0618bfaa92d7ccf1111edba6b07cb0610#diff-6771ca5200f9566f28eff1c9110ff3b2), so another update should solve the problem.

**Comment by Nilvus** [comment]
As it is not a darktable issue but lensfun one and it seems to be solved, please close your issue (or @TurboGit)

**Comment by TurboGit** [comment]
Closing indeed.
