### ISSUE TITLE
Compressing history stack screws up module labels

### ISSUE THREAD

**Issue by matze** [darktable-org/darktable#2466]
**Describe the bug**

Compressing the history stack duplicates the module label with a different font.

**To Reproduce**

1. Open image.
2. Click on 'compress history stack'
3. See error

**Expected behavior**

No change in labeling.

**Screenshots**

Before:
![before](https://user-images.githubusercontent.com/115270/56852756-5146ae00-691f-11e9-9b26-44e1cec744e3.png)

After compressing the history:
![after](https://user-images.githubusercontent.com/115270/56852758-54419e80-691f-11e9-9aee-0984d6657e9d.png)

**Platform (please complete the following information):**

 - OS: Ubuntu 18.04
 - Version: 4d6d678c92dd1d9d5ce32b0ac46723430ec1e6f5

**Comment by TurboGit** [comment]
I can reproduce, I think it comes from adding the style with icons. A nice side effect :)

**Comment by TurboGit** [comment]
Should be fixed.
