### ISSUE TITLE
Can't toggle panel visibility

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#2472]
**Describe the bug**
Had an older version of 2.7.  Downloaded latest changes, recompiled and started it.  Opened in lighttable, then all the panels changed to hidden by themselves.  Clicked the arrows to make them visible again, but wasn't able to make the header visible again.

Looked at the darktablerc file and found these conflicting lines

lighttable/ui/1/header_visible=FALSE
ui_last/header/visible=TRUE

so, it appears that the ui_last are new changes and don't check/reset the existing panel visibility to make sure they are in sync.  Or perhaps the older ones are deprecated and need to be removed from the darktablerc.

**To Reproduce**
Checkout a commit of 2.7 before the ui_last changes were introduced, compile it, and run it.
Checkout the newest changes, compile it and run it.

**Expected behavior**
The header should have displayed when I redisplayed the top panel.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 2.7+1046~g8144ac0dc-dirty

**Additional context**
This is probably the same issue that 2462 has.

**Comment by wpferguson** [comment]
I was able to get the header back using the keyboard shortcut.  However, the issue still exists that when the ui_last items are added to the interface, the interface sometimes gets left in an inconsistent state.  Perhaps a warning, or maybe this just falls under the "ATTENTION: darktable master may have some GUI glitches" umbrella.  @TurboGit if that's the case, then just close it.

**Comment by TurboGit** [comment]
Fact is that both prefs:

```
lighttable/ui/1/header_visible=FALSE
ui_last/header/visible=TRUE
```

Are not used anymore on the code, so I doubt that this is the issue.

I think I should create a script to detect all prefs declared in darktableconfig.xml.in and not used in the code. We may have quite some to remove!

**Comment by aurelienpierre** [comment]
I think the header is a different part of the top panel that can be toggled with Ctrl+H. The default state of panels, if not set, is visible so the behavior you describe is quite strange.

**Comment by wpferguson** [comment]
@TurboGit, I agree about the "stale" preferences.  I've been using the same config directory since 1.6, so I'm sure by now there is a lot of unused parameters that have accumulated.  I've also started running into the same problem with the lua scripts.  You can add, read, and write preferences, but you can't remove them.  I guess there's another API change coming. :-)

@aurelienpierre I just started darktable with a new configuration directory, and everything worked as it should.  I'll play around and see if I can recreate the circumstances and problem.

**Comment by Nilvus** [comment]
@wpferguson : just see that this issue is open. Maybe I'm wrong but with recent panels changes and improvements by AlicVB, I think this is solved now. Maybe to be closed ?

**Comment by wpferguson** [comment]
I agree.  This should have probably been closed a long time ago.  Maybe I need to search all the issues for the ones I created and make sure they're still valid. :)
