### ISSUE TITLE
Lighttable culling mode breaks lighttable mode lua API 

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#2473]
**Describe the bug**
I have a script that gets the current lighttable mode (in this case file manager) and zoom level (in this case 5) and saves them.  I display some images, then exit the script.  On exit, the view should be restored to file manager with a zoom level of five.  Instead I get cullling with a zoom level of 2.  The collection gets manipulated during the script, but that also is saved on entry and restored on exit.  However only 2 images are in the collection after the script exists, so the collection lua API is broken too.

**To Reproduce**
Checkout out commit  8f68a9da342be36e4d9a18204fe3d980a73490d1.  Compile, start it, and run the compare script (attached).  Simply start it and exit it with the keyboard shortcut.  Notice that the lighttable is restored to the previous settings.

Checkout the current, or   2c3f4c79c2d923e18d996c34c7f994d676d28fa6.  Compile, start it, and run the compare script.  Exit it and notice that we are in culling mode with a zoom level of 2 and 2 images in the collection.

**Expected behavior**
View and collection should be restored to the state before running the script

**Additional context**
[compare.zip](https://github.com/darktable-org/darktable/files/3125396/compare.zip)

**Comment by wpferguson** [comment]
Okay, went to write a stripped down version of compare and everything worked correctly.  I had assigned the keyboard shortcut CRTL X, to exit compare.  It turns out that the keyboard shortcut CTRL X toggles culling mode.  Unfortunately, that's not configurable in the options.  I'll close this and submit an issue that this should be configurable.

**Comment by edgardoh** [comment]
It is, shortcuts->modules->lighttable->toggle culling/expose mode

**Comment by wpferguson** [comment]
Found it, thanks.  Would it make more sense to put it in
shortcuts->views->lighttable, since it changes the view?

I'll close the issue.

Bill
