### ISSUE TITLE
Mac-Place main folder in application support

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2474]
**Is your feature request related to a problem? Please describe.**
Move the invisible configuration directory  (home/.config/) to: home/library/application support/darktable/

**Describe the solution you'd like**
Managing lua scripts / deleting corrupted -``db`` or -``lock`` files is easier if the main folder is placed following Mac default paths instead to create hidden folders which are just accessible with hacks or terminal commands. Linux uses terminal all times, (I myself used Ubuntu and Elementary), Mac users use terminal never mostly.

**Comment by parafin** [comment]
The downside is that Linux users don't have any idea about macOS directory structure, so they won't be able to help macOS users with anything, when they ask for help.
IMHO it's too late to change this, because it will also entail writting some migration process.
