### ISSUE TITLE
Crop and rotate: Aspect editor

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2476]
**Is your feature request related to a problem? Please describe.**
The 'crop and rotate' module allows the user to add custom aspect ratios. 
To achieve this the user has to open the Darktable configuration file darktablerc with a text editor and add a line with the new ratio.
The user has to leave the program for this

**Describe the solution you'd like**
Implement an aspect editor within Darktable.

**Comment by MStraeten** [comment]
right mouseclick on ratio selection and typing a custom ratio is already available - but the ratio is not persisted

**Comment by pphotography** [comment]
When I right-click on ratio selection I only get the list of aspect ratios. How exactly to you get to the point for typing a custom ratio?

**Comment by TurboGit** [comment]
Maybe by reading the documentation:
https://www.darktable.org/usermanual/en/modules.html#basic_group
