### ISSUE TITLE
Crop and rotate: resize in all directions

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2478]
**Is your feature request related to a problem? Please describe.**
To resize a crop area I can drag on the borders or the corner areas.
This allows me to adjust the size of up to two of the four borders at the same time.

Sometimes I want to increase or decrease the whole crop area. To achieve this I have to move the mouse to one corner and resize, then I have to move the mouse to an opposite corner and resize that too. 
If the result is not convenient, I have to repeat this procedure.

**Describe the solution you'd like**
Implement a modifier key that resizes all borders of the crop area when I resize the area at any border.

**Comment by junkyardsparkle** [comment]
This is already implemented with the shift key (on Linux, at least). You have to be holding the key when you click, though.

**Comment by pphotography** [comment]
That's right, I totally missed that (DT 2.6.1).
