### ISSUE TITLE
File operation also is executed on highlighted file not just selected.

### ISSUE THREAD

**Issue by moghyukon** [darktable-org/darktable#2479]
I select more than one File "Image" and want to delete these (Ctrl + Delete = Permanent remove or move to recycle bin )

Darktabel deletes the selected images which is fine, **but also** the image the mouse hoovers over and highlights. -> this image is in many cases not selected and I doubt somebody wants this behavior .

**To Reproduce**
1. Select more than one image in Lighttable view
2. move mouse over a not selected image to highlight
3. delete the images with a preferred keyboard shortcut
4. selected images (fine) + **highlighted (not fine)** are deleted.

**Expected behavior**
Only Selected image should be deleted (modified)

 - OS: Windows 10
 - Version 2.6.1

**Comment by EvgeniiFrolov** [comment]
I confirm this on ArchLinux (Plasma Desktop on X) with darktable 2.6.2.

Though the behaviour is a bit different:
1) I choose an image in lighttable
2) I choose the second image (ctrl + left mouse click)
3) I point (no click!) the mouse on the third image and use DELETE key.

Expected result:
both selected images are deleted, highlighted image is not.

Actual behavior:
Only the highlighted image is deleted.



ADDITIONAL INFO:
If I point (no click!) to the third image, then point (no click!) to one of the selected images
and push DELETE button on keyboard, the both selected images are deleted as expected.

**Comment by EvgeniiFrolov** [comment]
Have [submitted a pull request](https://github.com/darktable-org/darktable/pull/2545) that seems to fix this. Looking forward to any feedback.

**Comment by moghyukon** [comment]
Sorry I just saw this its already closed ... very disapointing ...
