### ISSUE TITLE
GTK undershoot and overshoot cover content in scrollable windows (e.g. preferences)

### ISSUE THREAD

**Issue by Tracerneo** [darktable-org/darktable#2481]
#2380 is also present on Linux, is not fixed in #2445 

Please see https://github.com/darktable-org/darktable/pull/2445#issuecomment-487612378 for details.

**Platform:**
 - OS: Gentoo
 - darktable 2.6.2
 - GTK+ 3.24.7

**Comment by aurelienpierre** [comment]
Ok then.

**Comment by Nilvus** [comment]
As answer on #2445 I don't think this workaround will work on 2.6.x as it's based on new UI where all changed. It certainly need other tweaks on 2.6.x. But as this is resolve on 2.7, you certainly have to wait next major release to see this resolve (or test 2.7 development version).
@TurboGit : what do you think of that ? To be closed ?

**Comment by Nilvus** [comment]
@TurboGit : this one to close also. Thanks.

**Comment by TurboGit** [comment]
Closing.
