### ISSUE TITLE
Sticky preview missing

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2482]
**Describe the bug**
In previous versions "B" and "CTRL-B" were enabling sticky preview (with and without zoom)
I really liked this feature, but it seems not to be present anymore.

Am I missing something?

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version 19.04

**Comment by Nilvus** [comment]
Which version of darktable do you use ? It helps to precise the version each time.

As far as I know, for sticky preview, that Z or Ctrl-Z or Alt-Z... depends on what you want. On darktable 2.4.4, I was already using these shortcuts activated by default. And just remember that you could find and change shortcuts on darktable preferences window.

**Comment by PaoloAst** [comment]
I apologize for missing the version. I'm using the master branch. 2.7.0

Sent from my mobile

Il lun 29 apr 2019, 23:25 Nilvus <notifications@github.com> ha scritto:

**Comment by TurboGit** [comment]
So in latest 2.7 branch it is w and ctrl-w. See RELEASE_NOTES for why.

**Comment by PaoloAst** [comment]
Hi Pascal,

I've read it, but W and CTRL-W are for a full screen with or without focus
indicators like the old Z and CTRL-Z.

I was using B and CTRL-B to have a "sticky" fullscreen and I don't find
such feature

Il giorno mar 30 apr 2019 alle ore 15:23 Pascal Obry <
notifications@github.com> ha scritto:

**Comment by AlicVB** [comment]
iirc, sticky preview as no default shortcuts. You have to set them in pref dialog.

**Comment by PaoloAst** [comment]
Thanks @AlicVB , I've found it.
