### ISSUE TITLE
New "Shift+Ctrl+N" shortcut to toggle navigation thumbnail visibility doesn't work

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2483]
**Describe the bug**
As the title, this shortcut doesn't work. For example, other new ones like Shift+Ctrl+H for histogram works great but not the one for navigation thumbnail.
I've tried few times to change or reactivate the shortcut in darktable preferences tab but same behavior : nothing happen.

@aurelienpierre 

**Expected behavior**
A working shortcut ;-)

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Master compile version 7fe35d67d

**Comment by aurelienpierre** [comment]
Did you try to edit the shorcut in the preferences ?

**Comment by aurelienpierre** [comment]
Confirmed.
