### ISSUE TITLE
Mask history entries are duplicated on applying a style or copying history stacks

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2485]
**Describe the bug**
if drawn masks are used and also for retouch masks the mask history entries are doubled each time styles are applied or history stacks are copied (via lighttable or ctrl-c/v)
--> leads to massive processing time if styles are used due to exponential growth

**To Reproduce**
1. open a picture
2. apply a module with drawn mask
3. apply some retouches
4. apply a style ( e.g.
[t3mujinpack - Ilford XP2.dtstyle.txt](https://github.com/darktable-org/darktable/files/3131495/t3mujinpack.-.Ilford.XP2.dtstyle.txt)
5. copy history stack from a different picture
6. check duplicates in mask manager, the xmp or library.db (sqlite: select imgid, formid, count(formid) from masks_history group by imgid,formid) before and after steps 4 & 5

can be fixed by purging duplicates in the library: sqlite: delete from masks_history where rowid not in (select min(rowid)from masks_history group by imgid,formid)

**Platform (please complete the following information):**
 - OS: OSX
 - Version darktable 2.7.0+1087~g7fe35d67d-dirty (but also older 2.7 builds e.g. darktable 2.7.0+904~g5db9e6d26)

**Comment by edgardoh** [comment]
Confirmed.
