### ISSUE TITLE
Not able to remove a film roll

### ISSUE THREAD

**Issue by heitorPB** [darktable-org/darktable#2490]
**Describe the bug**
Missing `remove` from film roll list.

**To Reproduce**
1. Go to `lighttable`
2. On `collect images` select `film roll`
3. Right click on a film roll, nothing happens.
4. Switch from `film roll` to `folders`, right click, you can now remove.

**Expected behavior**
Expected to be able to remove a film roll. Or at least "refresh" it to check for deleted files on HD.

**Platform (please complete the following information):**
 - OS: ArchLinux
 - DarkTable Version 2.6.2

**Comment by MStraeten** [comment]
just remove all pictures of the film roll in lighttable and the film roll will removed

**Comment by johans3** [comment]
I stumbled over the same issue. Maybe they forgot to implement it everywhere in the filmroll list because too busy to work on more important stuff. 
Anyway I was relieved to find out I could remove filmrolls in folder view. 

A refresh button? Basically no bad idea, but what if we moved our folder on disk?
Refreshing would purge all our edits. 
I should add that pressing "refresh"is our own responsibility

**Comment by TurboGit** [comment]
Not a bug, a feature.

**Comment by heitorPB** [comment]
> Not a bug, a feature.

Could you elaborate on that, @TurboGit ? I understand this is not a high priority stuff to work on, but not be able to remove a film roll is a feature?

> A refresh button? Basically no bad idea, but what if we moved our folder on disk?
> Refreshing would purge all our edits.
> I should add that pressing "refresh"is our own responsibility

That makes a lot of sense. I agree.

**Comment by TurboGit** [comment]
Elaborate on what? You entered a bug:

```
Describe the bug
Missing remove from film roll list.
```

And it is not a bug. If you want a new feature you should open a feature request. We have so many things opened here with wrong categorization, wrong description, wrong procedure to reproduce and so few devs that I just close the ones that are not proper.
