### ISSUE TITLE
Add checksum and length fields to xmp sidecar files to help identify original image

### ISSUE THREAD

**Issue by sjmudd** [darktable-org/darktable#2492]
Seen on darktable 2.6.1 and earlier.

After importing files for storage I often rename them to help better identify when they were created and also to prevent filename conflicts.

I may "edit" the original `.CR2` or `.JPG` files prior to doing these renames or later so darktable will generate a side car file with the `.xmp` extension to track what it is doing.

If I rename the photo images and don't rename the `.xmp` files at the same time it's possible to lose track of the original file I was editing. This is because the `.xmp` file only records the filename and editing details performed on the image.

I would like to propose, but am not sure if the xmp specifications allows for this or not, that additionally each xmp file would contain the photo image length and checksum. This is because with the combination of the 2 values it should be possible to uniquely identify and match any file. (It's basically what git does for it's _backing store_.).

If I renamed files or found a `.xmp` file and would do identify the image it was for I could check the length and checksum against the values from all the photo images I store. and then rename the `.xmp` file after adjusting the `xmpMM:DerivedFrom="IMG_9999.JPG"` setting in the `.xmp` file I was adjusting.

Which checksum could be used? I don't really mind. MD5 is probably too old and not good enough to guarantee uniqueness. Git uses an SHA-1. Storing the length is useful as it's a much quicker way to find a file, after which you can verify the file is the required one using the checksum.

If this is not possible for a reason I'd be interested to know what prevents this from being possible but for me at least it would ensure that I could much more easily match a random `.xmp` file against a random photo filename even if either file has been renamed in between.

**Comment by sjmudd** [comment]
After a small amount of code inspection I notice that the darktable SQLite database has an `sha1sum` field for each image in the `images` table. I do not see a `length` or `size` column or equivalent., but may be missing that.

While adding both values would be good including only the `sha1sum` value to the xmp sidecar would be fine and I would imagine easier to do as you already have the information.

**Comment by sjmudd** [comment]
Having said that looking at a the content of the `images` table the `sha1sum` column is not currently populated, so I guess populating that is needed first.

**Comment by pphotography** [comment]
I do have a similar workflow. After copying the images on my hard drive I rename the files using a mass-rename tool. For ex. i convert 'IMG_9999.DNG' to '20190428_9999_Norway_Sundown.DNG'.
After that I import into Darktable. I never touch the filenames after that and did not have the need to do so.

When using a PNG or JPG file in Darktable I sometimes switch to Gimp, do some edits to the file and then continue with Darktable. What happens the the checksum?

Would it be enough when Darktable had a renaming function that renames image and XMP files?

**Comment by s5k6** [comment]
I would very much love when DT stopped encoding the raw image in the XMP's filename, and store that information inside the XMP instead.

For convenience, of course, DT probably should still name the XMPs after the RAWs.  But making this optional, it would allow me have a naming scheme like this:

    DSC_4766.NEF
    DSC_4766.NEF.xmp
    bob-at-chritmas.xmp           --contains crop to Bob's face
    alice-unpacking-present.xmp   --containc crop to Alice

I think it would be more in line with how I as programmer write `#include`s into source files, and would thus feel more natural to me.  Also, I've consistenly found files knowing their filename to be doomed in some way...

Extending this thought, an XMP might not only refer to RAW images, but also to other XMPs, and extend the corresponding history stack.  Using pseudocode to convey this idea, I'll write XMP-file contents in a JSON-like syntax below:

    DSC_4766.NEF
    -- contains raw image, never edited by DT

    DSC_4766-basic-edit.xmp
    { src: "./DSC_4766.NEF"
    , hash: "md5:d41d8cd98f00b204e9800998ecf8427e"
    , history: [ exposure: +0.5EV, crop: ... ]
    }

    DSC_4766-online.xmp
    { src: "DSC_4766-basic-edit.xmp"
      // no hash, XMPs are likely to change!
    , history: [ export-profile: "sRGB", ... ]
    }

    DSC_4766-printing.xmp
    { src: "DSC_4766-basic-edit.xmp"
    , history: [ export-profile: "SaalDigital_FineArt_Pearl.icc"
               , exposure: +1EV
               ]
    }

The idea would be that the history stack for each XMP is built up following the chain of `src` references up to the root raw image.  In this example, `DSC_4766-printing.xmp` and `DSC_4766-online.xmp` would share the same crop, but use different export profiles, and the print version even changes the exposure a bit.

A change of crop in `DSC_4766-basic-edit.xmp` would propagate to all derived images.

**Comment by pphotography** [comment]
I think that an inheritance feature for XMP-files would be a very powerful feature. I often do different variations of a photo.

For example one final crop in 16:9 for screen and one crop in 1:1 for Instagram. Currently I have to duplicate the whole history.
If I want to change something else afterwards I have to do changes in both versions to be consistent.

For a simple solution XMP-format could be extended with a predecessor tag that contains a reference to another XMP file. Darktable would apply that history steps before processing the actual XMP.
Lighttable should get a new button in the 'Selected image(s)' section, maybe called 'branch' or something like that.

Question is if it should be possible to create multiple levels of inheritance, means should the user to be able to reference to a XMP that references to another XMP instead of an image.
Which leads to the problem of endless circle references...

I disagree with the idea of removing image references out of the XMP filename. In the first example it is not transparent where an XMP file ('bob-at-chritmas.xmp') belongs to. If you have multiple images in that folder all structure gets lost.
As a consequence, I would use one folder for every image. But for the most images I process there is only one history stack and having every image in a separate folder would be a major drawback.

**Comment by parafin** [comment]
You already can apply styles on export in dt, which basically implements inheritance.
As for SHA1 of original file - it needs to be computed on import, which will slow down the process considerably. Or maybe it can be done on first open in darkroom, there we read the whole file anyway, it should be less noticeable.

**Comment by pphotography** [comment]
Export styles are something different. For example, for different cropping I have to use darkroom. An export style does not know which part of an image I want to use.

**Comment by s5k6** [comment]
There are a couple of caveats though:

  * Cyclical references must be detected and yield an error.

  * Renaming a raw file would require *editing* each sidecar.  While this can be scripted, it is certainly more involved than scripting a consistent renaming of sidecar files.  Also, a naive script might break when the sidecar format is changed.

  * On startup DT currently checks whether a sidecar has been updated, and asks the user whether these changes should be loaded to the database.  Right now, this is decided using the `mtime` (touch(1) an .xmp file to verify this).  With the possibility of chaining sidecar files, it would be necessary to actually read each of them, and check the chain of ancestors.

    This could be avoided if the DB would store a list of all XMP files contributing to the creation of an image, and check all their `mtime`s.

**Comment by parafin** [comment]
Please create a separate issue for XMP inheritance feature request, it has nothing to do with the topic.

**Comment by sjmudd** [comment]
@parafin you said: 
> As for SHA1 of original file - it needs to be computed on import, which will slow down the process considerably. Or maybe it can be done on first open in darkroom, there we read the whole file anyway, it should be less noticeable.

I can see the concern of the extra overhead of calculating the checksum when loading a file. However, when you're already loading the file the I/O overhead is going to be negligible as you're already reading the file. So the overhead is extra CPU
* if that is a concern and not done already parallelisation of the import process would help.
* I personally would record the length and checksum as the length check is easy and fast to do. You can always check the image length and if it has not changed assume the checksum is good.
* raw files never change so you only ever need to do the check once and can use that value forever.
* if you are concerned about extra load/import time then make the option optional for those who do not need it. I still think it should be done and the default behaviour.

**Comment by s5k6** [comment]
Just to clarify: I'm not a darktable devloper.  I've just shared my thoughts on a feature I consider useful.  With the complexity involved (outlined by parafin and me above), I'm not going to request the feature of "XMP inheritance" right now.

As of now, I'm supporting your feature request.

In the long run, I still would like to have more flexibility in naming XMPs, but that is not ripe yet.  I only wanted to mention an idea that might be beneficial to have in mind when implementing your requested feature.

**Comment by sjmudd** [comment]
**Updated:** Removed attempt to re-open issue here. As requested  and shown below it has been moved elsewhere.

**Comment by sjmudd** [comment]
To clarify. My intention would be to provide a patch to existing darktable to handle this. It's suggested I discuss this here first prior to starting.

**Comment by wpferguson** [comment]
I would open a new issue and then copy/paste your proposal there.  Posting to a dead issue isn't really good.

In your proposal, how do you plan to handle existing xmp files (I have 1M+)?

You might also want to look at https://github.com/darktable-org/darktable/pull/21850.

**Comment by sjmudd** [comment]
**ok, it wasn't clear to me which process to follow. I'll create a new proposal.**

To answer your question: I plan to write something to back fill data as that's a bulk change. This proposal will populate new files when xmp files get updated IF the configuration is enabled. So it's minimal. This seems like the safest way to do things. It's not intrusive and someone with 1,000,000 files (I have about 200k) clearly will want a process to populate things to work differently.
