### ISSUE TITLE
"collapse module when disabled"

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2494]
**Describe the bug**
When the setting "⚙ » GUI options » darkroom » expand the module when it is activated, and collapse it when disabled" is activated, clicking ⏻ on a module in darkroom *always* toggles the module's collapsedness (well, always collapses an expanded, and expands a collapsed module), no matter whether it is being switched on or off.

**Expected behavior**
Should expand iff switching on.
Should collapse iff switching off.

**Platform (please complete the following information):**
  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * darktable 2.7.0+1087~g7fe35d67d

**Comment by aurelienpierre** [comment]
yes, there is a glitch here. It's on my todo list.

**Comment by leclercj** [comment]
I think this issue is now fixed by PR https://github.com/darktable-org/darktable/pull/2645
Could you please test using latest master, and close it ?

**Comment by s5k6** [comment]
Sorry for the late reply, I've been away.
Tested 6f0010465 and found the issue resolved.
Thank you very much!
