### ISSUE TITLE
PgDn, PgUp sometimes needs two keystrokes to advance to prev/next image

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2495]
**Describe the bug**
In darkroom mode, PgDn and PgUp sometimes need two keystrokes to advance to prev/next image.

With the Filmstrip switched on, I observe that PgDn sometimes only scrolls the filmstrip to the left, but the highlighted image stays highlighted, and the image in the main view does not change.  A second PgDn will move the highlighting too the next image in the filmstrip, and also change the image in the main view.

This is not always reproducible.

It also happens with the filmstrip switched off, but is more subtle to recognise.

When using PgDn to advance to the next window, the settings in the right pane seem to be updated immediately, but there's about 1s delay before the main view gets updated, and another 1s delay before the histogram gets updated.  The bug described above seems to be reproduced easier when advancing to the next image between the update of the main view and the update of the histogram, although tis is not the only occasion when this happens, and does not always happen.

The same holds for PgUp for advancing to the previous image.

**Platform (please complete the following information):**
  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * darktable 2.7.0+1087~g7fe35d67d

**Comment by johnny-bit** [comment]
Default shortcuts changed + can't reproduce on 3.2.1 nor current master. Histogram update is tied to pipe run same as any previews so the delay might be noticeable.
