### ISSUE TITLE
Lighttable not repainted when switching to fullscreen

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2496]
**Describe the bug**
Occasionally, the middle area of lighttable is not repainted when switching to fullscreen mode.  It will be repainted about one second after moving the mouse.

**To Reproduce**
1. In lighttable view, fullscreen mode
2. switch off fullscreen (F11).
3. Move the mouse out of the DT window.
4. Move mouse over an image in the lighttable view (moving mouse into an empty region of the main area, but not over an image, won't reproduce this).
5. Switch to fullscreen mode (F11)

The main area will not be repainted.
![screenshot Ap5u4FOH3s](https://user-images.githubusercontent.com/16781735/57019452-de8f4880-6c26-11e9-9105-bbd45b448a79.png)

When starting to move the mouse, thumbnails that happen to be under the curser start to be repainted.  About 1-2 seconds after starting to move the mouse, the main area will be repainted entirely.

**Platform (please complete the following information):**
  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * darktable 2.7.0+1087~g7fe35d67d

**Comment by TurboGit** [comment]
A known issue (at least to me :), but I have no idea to fix this one. We probably need to catch an event from Gtk when the window is raised and send a refresh? For now just move the mouse outside the center area.

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by s5k6** [comment]
Yes, fixed.  Thank you!
