### ISSUE TITLE
Not easy to zoom when editing masks

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2497]
**Is your feature request related to a problem? Please describe.**
AFAIKT scrolling with the mouse wheel over the image in darkroom mostly zooms the image, and with Ctrl held down even beyond the limits of fit-screen and 1:1.

When creating a mask, this is not possible with the pointer inside a mask.  Just scrolling changes the size of the mask, and Ctrl+Scrolling changes its opacity.

**Describe the solution you'd like**
Maybe Alt+Scroll could be used for the masks opacity, it seems to change the size of the mask just like scrolling without modifier.  I would like to have one kind of event (maybe Ctrl+Scroll) that is reserved for zooming when the pointer is on the image in darkroom, or on the image collection in lighttable.  I think it would make usability more consistent.

**Describe alternatives you've considered**
The most flexible solution would be to make the actions bound to keyboard and mouse events completely configurable (like in Emacs), but that may be difficult.  See [https://github.com/darktable-org/darktable/issues/1950]

**Additional context**

**Comment by edgardoh** [comment]
There's already a shortcut for this: views->darkroom->aloow to pan & zoom..

**Comment by s5k6** [comment]
The issue persists with `d0b1edd12`.

**Comment by DaveInDev** [comment]
it would be nice to address this issue. I often change the mask opacity by error when trying to use ctrl-wheel to zoom...
