### ISSUE TITLE
Import dialog: CSS styling missing from titlebar

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#2503]
**Describe the bug**
The new CSS theme is missing support for dialogs with actions (other than close).

**To Reproduce**
1. Go to Lighttable
2. Click on Import (either image or folder)
3. See error

**Expected behavior**
The dialog should have a titlebar and frame.

**Screenshots**
![darktable-import](https://user-images.githubusercontent.com/10246/57080520-fb914d80-6cf2-11e9-8ef6-9be362ff0b3f.png)

As the style is missing from the header bar, it's seen as transparent.

**Platform (please complete the following information):**
 - OS: Fedora 29
 - Darktable version: master (b9d32f687f189d0415a73c33a4a5503fe8fd6797)

**Comment by Nilvus** [comment]
It seems that you're using grey css. I forgot to verify this dialog but what is strange is don't have same dialog. See what I have with the new grey css I made (I think anyway there one or two things to improve) :

![Capture-20190502173212-978x593](https://user-images.githubusercontent.com/45535283/57087564-9c3a3a00-6d00-11e9-84b7-869eef7a668d.png)

For your problem, which desktop environment are you using (name and version) and which theme for this desktop environment are you using (theme that display title bar of course) ?

**Comment by Nilvus** [comment]
Euh, something strange. On my computer, title bar is black not transparent but here it is... It seems that it is transparent by default but why on my computer title bar is black, I don't know. I'm note sure it is a css issue, maybe a gtk one as the default black css render same title bar.
@aurelienpierre or @TurboGit if you have some tips about that ?

Anyway, I will see if I find something on css.

**Comment by Nilvus** [comment]
@garrett : please this PR #2504 to see if it correct your issue.

**Comment by garrett** [comment]
@Nilvus: Thanks for the PR! I made a suggestion on how the padding could be improved for the sides of the titlebar.

(FWIW: I happen to be a longtime FOSS designer & developer who knows a bit about CSS and such, in addition to a photographer and Darktable user. But it's just a very simple change, so that doesn't really matter much. :wink:)

**Comment by Nilvus** [comment]
@garrett : so could you please close this issue and continue on the PR. I will finish to correct that today.

**Comment by garrett** [comment]
@Nilvus: Great! Thanks!
