### ISSUE TITLE
culling order of images

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#2509]
not sure if it's a bug or a feature, but when you scroll images in culling layout, it doesn't follow the filemanager order.
if in you filemanager, you see images 1,2,3,4,5,... you select image 2, enter culling mode (4 images), you see : 2,3,4,5 (expected) but when you scroll up, you get 6,3,4,5 and then 6,4,5,7... If it's intended, then I don't understand...
I just hope I've not broken something...

**Comment by edgardoh** [comment]
I didn't test it, so this is just in theory, but I use a function get_selected() and get_collection(), that I assume follow the order of the collection.
I'll try to check it later.

**Comment by edgardoh** [comment]
Seems to be working fine for me in latest master, I have set in file manager order by time, then went to culling and it keeps the order. Same with order by rating.

**Comment by TurboGit** [comment]
Yes, working for me too on current master.

**Comment by AlicVB** [comment]
example (you can compare image order with the filmstrip...) : 
![Capture d’écran_2019-05-03_18-06-29](https://user-images.githubusercontent.com/1818223/57150369-6b283b00-6dce-11e9-9d36-6b6fed6c2891.png)
After some more test, it seems that the problem comes from the query used to retrieve ratios... I'll try to understand what happen there and provide a fix

**Comment by AlicVB** [comment]
ok, found it... and hopefully fix it :)
technical details in the PR #2511
