### ISSUE TITLE
Darktable Speed in macOS slower than windows 10

### ISSUE THREAD

**Issue by AlbertoVelazquez** [darktable-org/darktable#2510]
I know it's a subject that seems to have been dealt with more than once. And that improvements have been made in version 2.6.2 as opposed to 2.6.0. But I also have to say that the performance in macOS (macbook mid 2014, 2,5Ghz i7, 16GB ram, NVIDIA GeForce GT 750M 2 GB Intel Iris Pro 1536 MB and macOS mojave) is very bad, even running the application at half resolution the performance is much lower than on the same computer with Windows10 running at full resolution.

I know that comparing performance differences between different OS is unfair. But the difference in usability between both OS is gigantic, windows 10 even without being perfect is usable when you use the darktable or zoom in the darkroom. On the other hand in macOS it is a pain both tasks in this equipment.

As an important detail to say that OpenCL doesn't work in macOS, at least in my macbook, maybe it also explains some difference.

I understand that comparisons are unfair and unpleasant, but any other processing program does the retouching in practically real time, at least the most basic (capture one, lightroom, affinity photo) and I understand that these programs can have GPU acceleration. But many times I look at the screen 10-20 seconds to see the result of the denoise in a small part of the image making the developing tedious. Maybe it's the fault of the build, which is not done correctly, but making the darktable build for macos is quite tedious for someone like me. So I haven't been able to compare.

I put all this as a glue because darktable is the developing program that I like but after trying capture one express for sony I think I prefer to use this with its limited options just to not waste so much time hitting me with the speed of the interface and the program. Besides, I don't consider my computer to be especially bad, even if it's a laptop. Well, it only works badly with darktable. The rest of programs works at 30-60fps.

Curious details
---------------

- It takes longer (5-10 times) to pass any filter when you are at 100% although the screen space shown is the same. Why? Doesn't render only what is in view?
- It's passing the filter while you zoom in. It couldn't wait for you to stop for a moment while zooming to start processing the image? at least it would help to have a more fluid zoom.
- Same thing happens when panning

**Comment by AxelG-DE** [comment]
Could you:
- start dt with the option '-d perf' from a kind of terminal and 
-than take one of the actions assumed to be slow, 
-subsequently paste the output to a text-file and post it here

**Comment by parafin** [comment]
How exactly OpenCL doesn't work for you? What if you restart DT 10-15 times? What's in "-d opencl" debug output?

**Comment by AlbertoVelazquez** [comment]
Maybe is a problem with MacOS, But I don't know how to use that command

```
Macbook:~ alberto$ open /Applications/darktable.app -d perf
open: invalid option -- d
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-s <partial SDK name>][-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.
      -s                For -h, the SDK to use; if supplied, only SDKs whose names contain the argument value are searched.
                        Otherwise the highest versioned SDK in each platform is used.
```

**Comment by AlbertoVelazquez** [comment]
> How exactly OpenCL doesn't work for you?

basically in options where the OpenCL options I have a text "Not Avalaible"

**Comment by johans3** [comment]
I installed Linux "Elementary Juno" on a partition of my Macpro desktop computer, this days. 
The difference in speed is noticeable. On Linux Dt flies, on Mac Dt is not the same, in every aspect (startup, switching to modules, selecting another picture in the film roll in darkroom, applying adjustments) 

Of course the porting to Mac is an extra work with its technical issues and I'm glad the application works on Mac as well. Can't be anymore without Dt. Kudos to the few who brought us Dt

**Comment by johans3** [comment]
@AlbertoVelazquez 

Right-click on Dt, "show package contents" and go to:

``/Applications/darktable.app/Contents/MacOs/darktable``
Use this path to debug Dt in **Terminal**

**Comment by AlbertoVelazquez** [comment]
Hi, I have made some tests. I separate the Outputs to make easy to search.

Remarkable things

- The same image (when DT is used at full resolution) takes much longer (5.6 sec) to process the same filters being at 100% zoom as when the image is fit (1.5 sec).

- The opposite happens if we use darktable at half resolution. The 100% image takes less time (0.6 sec) than fit (1.2 sec).

- I've tried some image with almost all the filters

- The times to me seem greater than the debug mode says.

[DT Tests.zip](https://github.com/darktable-org/darktable/files/3142545/DT.Tests.zip)

**Comment by mjut** [comment]
I'd love to run DT as my main image dev. I like the features and the concept.
Unfortunately, I am experiencing the same performance issues over here. 
I am running Darktable 2.6.2 on macOS 10.12 / with a 8GB GPU and 64GB ram. So, its a pretty powerful machine – with an i7 intel.
Will the lack of performance be fixed in later versions for the macOS? (I am no developer, so I have no idea if this is a huge deal or rather easy to do)

**Comment by homer3018** [comment]
There are quite a few improvements performance wise between 2.6.2 and master. If possible you should consider building master and test (with openCL enabled) it out, or alternatively wait for 3.0 to be out later this year as usual.
I'm also on a Mac and I'm not complaining anymore of the performances (whether on the lighttable or in the darkroom), even using it on a 5k screen. Granted it's not the fastest but certainly fast enough, thanks to all the developpers out here willing to improve it.

**Comment by mjut** [comment]
Thanks for the suggestion @homer3018 
I am already trying to build the app on my mac. I am struggling though. 
The build is not finishing. I am always running into an cmake error. "Could NOT find OpenMP_C" which is known, but I coulndt get it to work. Do you have any suggestions, that would point into the right direction?

**Comment by homer3018** [comment]
Maybe have a look [there](https://discuss.pixls.us/t/compiling-darktable-dmg-a-bump-in-the-tracks/6231/89).

**Comment by mjut** [comment]
Thank you.
I couldn't get it to work. I ll quit for today, and try again tomorrow.
