### ISSUE TITLE
OSX: using Culling with mouse swipes to the right results in an segfault (also >10 cursor key steps)

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2512]
**Describe the bug**
After switching into Culling layout, changing the number of fields by cursor keys works fine, but changing via mouse swipe results in an segfault

**To Reproduce**
1. Go to culling layout
2. Click on slider for number of shown picture
3. swipe left/right with mouse or trackpad
4. See error:
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Abort trap: 6
[CrashReport.txt](https://github.com/darktable-org/darktable/files/3143027/CrashReport.txt)

reproducible with opencl disabled and enabled

**Platform (please complete the following information):**
 - OS: OSX
 - Version darktable 2.7.0+1113~g248fbccd6
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by MStraeten** [comment]
could reproduce the behaviour also by stepping 10 steps with the right cursor key ...

**Comment by MStraeten** [comment]
got additional console output:
darktable(35789,0x111ad75c0) malloc: *** error for object 0xffffffff00000000: pointer being freed was not allocated
darktable(35789,0x111ad75c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
[CrashReport.txt](https://github.com/darktable-org/darktable/files/3143101/CrashReport.txt)

**Comment by MStraeten** [comment]
seems to be fixed with latest culling commits

**Comment by MStraeten** [comment]
unfortunately only ok if not more than 10 pictures in the film roll

**Comment by AlicVB** [comment]
This should have been fixed in PR #2530 (not yet merged in master)

**Comment by MStraeten** [comment]
confirmed, thanks
