### ISSUE TITLE
Panasonic FZ300 lens profile not shown in the list

### ISSUE THREAD

**Issue by lapineige** [darktable-org/darktable#2515]
**Is your feature request related to a problem? Please describe.**
FZ300 camera+lens (it's a bridge) are not recognised by Darktable, not even present in the camera list.
But it is already supported by Lensfun : https://github.com/lensfun/lensfun/issues/259#issuecomment-343548536 and as it's using the same lens as FZ200 (https://github.com/lensfun/lensfun/blob/master/data/db/compact-panasonic.xml#L280) the same profile is used. 

The same apply for FZ330 (US version).

**Describe the solution you'd like**
Darktable automatically detect FZ300 and use its profile (aka FZ200 profile).

**Describe alternatives you've considered**
Na.

**Additional context**
(I hope this is the good place to talk about it)

Off-topic question: other formats than 4:3 are not supported yet, where can I submit RAW files to improve that ? :)

**Comment by Nilvus** [comment]
darktable only read Exif infos from images by the exiv2 library. (images infos you could read on darktable) This library then display the real name, so darktable could after that use lensfun to recognize camera or lens on corrective lens module.

So if the problem is in displaying infos, you have to check from exiv2 library (report or if you have the last version). If it's about the corrective lens module, that's about lensfun where to check or report.

darktable as only one real issue about lensfun : improve compatibility with lensfun 0.3.95 as you can see here : #2332

**Comment by lapineige** [comment]
Well, thanks a lot for that information, because I tried `lensfun-update-data`, it said I had to install  `liblensfun-bin` package, I did it and then… Darktable recognize my camera :)

(does that mean a dependency was missing ?)

I'm closing this, thanks a lot :)

> Off-topic question: other formats than 4:3 are not supported yet, where can I submit RAW files to improve that ? :)

I guess I should open another issue for that question ?

**Comment by Nilvus** [comment]
Glad to see that solves your problem.
And no it's not a dependency problem, just a problem of version. Actually, you already have lensfun installed. Package you have installed is just about tools like the one you use to update data, even for those automatically added on lensfun 0.3.95 even if you have an older version (compatible with darktable). That's all about the issue I post. You could use last lensfun profiles but not the last version of lensfun by now with darktable.

**Comment by Nilvus** [comment]
> > Off-topic question: other formats than 4:3 are not supported yet, where can I submit RAW files to improve that ? :)
> 
> I guess I should open another issue for that question ?

See there before posting an issue : https://www.darktable.org/resources/camera-support/
This page explains which camera and formats are supported and how to add more. Posting RAW images on pixl.us is one of the first step.
