### ISSUE TITLE
Fujifilm s6500fd Support

### ISSUE THREAD

**Issue by GioMaxIT** [darktable-org/darktable#2516]
I just added a RAF from Fujifilm s6500fd on raw.pixls.us with cc0 license.
Please add support, particularly the denoising preset.

I also have huge artefacts on high iso, so I shotted 100iso

I was available to test all you need.
Many thanks
Giovanni

**Comment by LebedevRI** [comment]
Thanks for the sample!
I'm quite sure that camera is already supported.
See some other resources on noise profile creation (not sure what how-to is most up-to-date)
