### ISSUE TITLE
Noise profile for Fujifilm s6500fd

### ISSUE THREAD

**Issue by GioMaxIT** [darktable-org/darktable#2519]
Thanks Roman for previous reply. 
Unfortunately Noise profile for my model is missing. There is for a similar camera, X100, but I cannot use or test it. 
Now I see as profile option only a "generic poissonian".
Can you do something, or can I?
Thanks again
![Immagine](https://user-images.githubusercontent.com/50272678/57184268-82902280-6eb9-11e9-8e9d-dba005deb33c.jpg)

**Comment by rawfiner** [comment]
Please follow this tutorial:
https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/

**Comment by GioMaxIT** [comment]
I did all, now I have noise profile shots.
Unfortunately I have Win 8, not Linux, so I can't generate the noise profile: preset.json and noise_result.pdf
Can I ask an help to generation? I have 6 RAF, 13Mb each.
Many thanks.

**Comment by rawfiner** [comment]
Please upload the raws files on a drive, and put the link here
I will try to find some time to do the generation part

**Comment by GioMaxIT** [comment]
https://drive.google.com/open?id=1YKhrKBtbWTHkoZrIwrei8nZnGhpMGh77
https://drive.google.com/drive/folders/1YKhrKBtbWTHkoZrIwrei8nZnGhpMGh77?usp=sharing
Many thanks.

**Comment by rawfiner** [comment]
Hi @GioMaxIT
I have just downloaded your shots (sorry for the latency)
It seems strange to me that your shots are so "mottled", even the smallest ISO is full of this...
Is it due to the sheet of paper you used, or something like that?

**Comment by ClaesGitHub** [comment]
@GioMaxIT Did you ever check the replies you have got on pixls.us,
where you asked the same question?

**Comment by GioMaxIT** [comment]
Sorry for delay in response, I stay here to my help request, sorry for duplication.
I confirm I have always had so many noise in dark shots,
Also shotting with the plug lens cover, any ISO, I have such noise!
I don't know if it is my camera that it is malfunctioning or if it is a common behaviour of my model S6500fd .

**Comment by rawfiner** [comment]
This kind of noise is not normal I think. When there is such coarse grain noise, there should be quite a lot of fine grain noise too. And your picture at ISO 100 should not exhibit such mottled aspect

**Comment by GioMaxIT** [comment]
So, what can I do? Maybe it is a sensor problem to 400 ISO and higher.

**Comment by rawfiner** [comment]
I don't know where the problem comes from, but you can try to:
- print again the gradient, or make sure it is smooth on the print
- clean your lens, and remove any UV filter or things like that in front of the lens
- take pictures again

**Comment by ClaesGitHub** [comment]
@GioMaxIT and @rawfiner 
I have a hunch that it is a bad quality piece of paper that shows up as mottles @ ISO100...

**Comment by GioMaxIT** [comment]
Well, I will reprint on ticher paper, clean lens and do again shots.

**Comment by GioMaxIT** [comment]
Please @rawfiner you mean i do use a thiner or a thicker paper to print gradient?
Sorry, what you mean for "smooth on the print"?
Thanks

**Comment by GioMaxIT** [comment]
Just last question: I read that many people had problems to set my camera on infinity; can be this the reason? Maybe my shots aren't on infinity, so in the pictures you see the grain of paper?

**Comment by rawfiner** [comment]
Sorry completely forgot to answer... I would say thiner paper.
Also, if focusing to infinity is not working, you can try setting focus to the closest point possible. We want the scene to be blurred, but it does not matter if it is blurred because the focus is too far, or too close.

**Comment by johnny-bit** [comment]
@GioMaxIT Ping ;)
