### ISSUE TITLE
Darktable crashes when running darktable-cli immediately after upgrading darktable

### ISSUE THREAD

**Issue by dllu** [darktable-org/darktable#2522]
**Describe the bug**
Darktable crashes when running darktable-cli immediately after upgrading darktable from a previous version which has resulted in an older version of the database.

**To Reproduce**
1. Run an older version of darktable
2. Upgrade to a recent version on git (I used ` darktable 2.7.0+1123~g8555f5feb`)
3. Run `darktable-cli` to process a photo, for example, I ran the following command `darktable-cli 2018-06-18-01-42-57_DSC05952_4ff887edb0adef297f922886009768f8778611e8.arw 2018-06-18-01-42-57_DSC05952_4ff887edb0adef297f922886009768f8778611e8.arw.xmp /home/dllu/pictures/cooked/2018-06-18-01-42-57_DSC05952_4ff887edb0adef297f922886009768f8778611e8.jpg`
4. Crashes with stack trace `darktable_bt_AZ3X0Z.txt` attached

**Expected behavior**
Should export a photo without crashing.

**Platform (please complete the following information):**
 - OS: Arch Linux
 - x86_64 Linux 5.0.10-arch1-1-ARCH

**Additional context**

My suspicion is that it is trying to run `dt_gui_show_standalone_yes_no_dialog` in [`/src/common/database.c#L1717`](https://github.com/darktable-org/darktable/blob/bf5651a71ae20333267ca3aa6cff35298046e068/src/common/database.c#L1717), but is crashing with segmentation fault since the GUI hasn't been initialized in CLI mode.

**Workaround**

Run `darktable`, click through any dialogs, then close `darktable` and then run `darktable-cli`

[darktable_bt_AZ3X0Z.txt](https://github.com/darktable-org/darktable/files/3146077/darktable_bt_AZ3X0Z.txt)

**Comment by edgardoh** [comment]
This is a known issue, but if you run darktable-cli --configdir {pointing to an up-to-date config} it should work.

**Comment by rawfiner** [comment]
Indeed, same issue as #2460
I agree with your suspicion.
