### ISSUE TITLE
UI: color picker live samples areas displayed as small strips

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2524]
**Describe the bug**
live sample picker areas are displayed as small strips instead of boxes:
![image](https://user-images.githubusercontent.com/39386816/57220960-8a58df80-6ffd-11e9-806a-c679ed2ece14.png)

**Platform (please complete the following information):**
 - OS: osx, windows
 - Version  darktable 2.7.0+1123~g8555f5feb

**Comment by Nilvus** [comment]
Confirmed also on Linux. I didn't find any possibility to change that on CSS. So, it's probably on GTK code that this could be changed (or with a very hidden css tag ;-) !).
@aurelienpierre or @TurboGit  : any idea ?

live samples should be like this : 
![picker](https://user-images.githubusercontent.com/45535283/57319285-89f33e00-70fc-11e9-9d76-b4dbd12490cd.png)

**Comment by Nilvus** [comment]
@TurboGit : so to be closed.

**Comment by TurboGit** [comment]
Closing now.
