### ISSUE TITLE
[FEATURE] Allow to specify which metadata to export

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#2526]
If I export an image to a JPG I don't want to share the GPS coordinates in the exif data especially privacy reasons.

It would be great to have a way to disable exporting of certain exif data. For me it would be enough to have a line with some regex what to remove.

**Comment by s5k6** [comment]
Considering the [complex structure of metadata](https://www.exiv2.org/metadata.html), using a regex is probably not the right thing to do.  But maybe you can adapt [this example](https://github.com/s5k6/dtscripts/blob/master/scrubMetadataOnExport.lua) to your needs?

**Comment by cryptomilk** [comment]
On the right of the export button is a new settings dialog for metadata to be exported. You can disable geo tags to be exported now!

**Comment by johnny-bit** [comment]
according to discussion on IRC:

>oh this is already addressed
as you can select what data to export now
it is also stored in presets

So... Closing :)
