### ISSUE TITLE
initial number of picture in culling mode

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#2527]
**Describe the bug**

The number of image on culling mode is not initialized with the number of thumbs selected initialy

**To Reproduce**
1. select 5 picture in culling mode
2. clcik ctrl-x to move on culling mode
3. the number of picture is not 5

(if 5 is actually the current default number, select 4 or 6 thumbs). 

**Expected behavior**
The number of picture displayed initially should correspond to the number of selected thumbs just before ctrl-x.

I'm pretty sure this is a regression.

**Platform (please complete the following information):**
 - OS: Linux
 - Version 2.7 current master

**Comment by edgardoh** [comment]
@TurboGit , this is not how its supposed to work, the number of images is set with the slider on culling mode and next time the culling is entered that same value is used.

**Comment by Nilvus** [comment]
@TurboGit : if I made what you say, this pass from culling to navigation mode with of course not the same number but previous number of navigation mode. That's works great for me as this way darktable keeps number for each mode. Most of the time, I don't want to have same number of images, especially between navigation and culling modes.

**Comment by Nilvus** [comment]
@TurboGit : on culling mode, you just have to select first picture and choose which number of images to display.

**Comment by TurboGit** [comment]
Ok, closing then. I was pretty sure it was working before... My bad memory plays tricks with me :)
