### ISSUE TITLE
Raw import: Red channel corrupted when using color matrix

### ISSUE THREAD

**Issue by hattedsquirrel** [darktable-org/darktable#2528]
**Describe the bug**
When importing raw files and selecting one of the color matrix options as input profile the red channel shows patches of black pixels as well as a ghost image of what might be the green channel. The problem only exists with color matrices, color profiles like Rec709 work as expected.
The problem exists with native camera raw files (.cr2 in my case) as well as with .dng files from Adobe's DNG converter using "embedded color matrix". Converting the raw file with dcraw and importing the resulting tiff in darktable (sRGB color profile) works fine. The problem seems to be solely related to handling color matrices.
I double-checked the image with dcraw, RawTherapee and Canons "Digital Photo Professional". Neither of them has this issue, so I'm positive the image file itself is fine.
Also, I already made sure that adobe_coeff.c of darktable uses the same color matrix for my camera as dcraw does, so I expected compareable results.

**To Reproduce**
1. Import the attached .cr2 file into Darktable. It contains strong TCA which helps to make the problem more prevalent.
2. Make sure "stadard color matrix" is selected as input color profile.
3. Use the channel mixer to only show the red channel.
4. Set zoom level to 200%, watch for black seams on the windows in the upper right corner and double lines at the top center.

**Expected behavior**
- No dark patches, no double lines.
- Similar behaviour when using color matrices vs. color profiles during import.
Currently some information in the red channel is lost / distored and can't be recovered by and of darktables modules.

**Screenshots**
screenshot_cr2_import_1.png, screenshot_cr2_import_2.png - CR2 file directly imported into Darktable, only the red channel is shown in grayscale. Dark patches are visible around the windows. While the doubled lines are a bit hard to spot, the comparison to the other screenshots reveal the issue and how the lines *should* look like.
screenshot_dcraw_import_1.png, screenshot_dcraw_import_2.png - CR2 converted by dcraw into sRGB, then imported into Darktable: Problems are gone.
screenshot_rawtherapee_1.png, screenshot_rawtherapee_2.png - CR2 directly imported into RawTherapee for comparison. Lines are much clearer, no dark patches.

**Platform**
 - OS: Ubuntu 18.04.02 LTS + Darktable Relase PPA
 - Tested versions: 2.6.1, 2.6.2, darktable-master from May 5th (commit 8555f5feb17334e84483c010982a427e4dd67f87)

**Additional context**
While the image artifacts might not be overwhelmingly obvious in the color image right after import, they show up when further editing the image. Most notably these artifacts on the red channel mess with the TCA correction of the lens correction module. After TCA correction the image appears blurry and overall quality is visibly worse than with other tools that use lensfun.
While converting all raw file with dcraw into sRGB and then importing these resulting files into darktable works (even the TCA correction works fine after that), it is cumbersome and eats lots of storage space for all the additional files.

screenshot_cr2_import_1.png
![screenshot_cr2_import_1](https://user-images.githubusercontent.com/50338637/57252225-f2361700-704b-11e9-8fef-7f0c16600362.png)

screenshot_cr2_import_2.png
![screenshot_cr2_import_2](https://user-images.githubusercontent.com/50338637/57252226-f2cead80-704b-11e9-8943-fd7adc501e38.png)

screenshot_dcraw_import_1.png
![screenshot_dcraw_import_1](https://user-images.githubusercontent.com/50338637/57252228-f2cead80-704b-11e9-9e55-40353b6f1b5b.png)

screenshot_dcraw_import_2.png
![screenshot_dcraw_import_2](https://user-images.githubusercontent.com/50338637/57252229-f2cead80-704b-11e9-9eb6-cc7835387be2.png)

screenshot_rawtherapee_1.png
![screenshot_rawtherapee_1](https://user-images.githubusercontent.com/50338637/57252230-f3674400-704b-11e9-9141-174dae0b5663.png)

screenshot_rawtherapee_2.png
![screenshot_rawtherapee_2](https://user-images.githubusercontent.com/50338637/57252231-f3674400-704b-11e9-9ecd-c73ca113b238.png)

**Comment by hattedsquirrel** [comment]
I couldn't attach the .cr2 files directly (too big), so I uploaded it to google drive:

Raw .cr2 file:
https://drive.google.com/open?id=1ZpR4v1pDwr9MY-Kx4NR7uGEBFMSX-5ty
Darktables .xmp file:
https://drive.google.com/open?id=1bzibRBCc2hxaLrc07in1F5BP8DP60pJC

**Comment by parafin** [comment]
Try Gamut clipping: https://darktable.gitlab.io/doc/en/color_group.html#input_color_profile

**Comment by hattedsquirrel** [comment]
Doesn't make any difference.

**Comment by LebedevRI** [comment]
That's just lens TCA.
Manually setting TCA red = 1.0007, TCA green = 1.0003 in lens correction module highlights it.
I guess you need to create a lens correction profile for your lens for lensfun.

**Comment by hattedsquirrel** [comment]
No, it is not just TCA. TCA triggers the bahaviour of darktable because the green and red channel differ spatially. Remeber i oly process the red channel in my screenshots. There shouldn't be any double / ghost images int he red channel alone.

I created a lensfun profile for this lens (hence the type of high contrast picture) and it works great for example in RawTherapee (also uses lensfun). But the results with Darktable are much inferior. Thats why I traced this issue and found that the red channel showed the described corruptions right after import. That is even without TCA correction. Red channel corruptions gets worse if I apply TCA correction.
When doing the cross checking to dcraw, rawtherapee, and DPP i make shure to have the same settings on all programs so it is a fair comparison with as few processing steps applied as possible.

If you want to see it for yourself toggle between "standard color matrix" and Rec709 in the import profile module and watch the black patches show up and disappear.

**Comment by LebedevRI** [comment]
Neverimind, did not meant to reply.

**Comment by Benja1972** [comment]
I always have green tint in my cr2 files (with standard color matrix and enhanced ). Usually I correct them in white balance module. Would be nice if it will be fixed in future.

**Comment by hattedsquirrel** [comment]
Problem no longer exists in darktable 3
