### ISSUE TITLE
Nodes in color zones module, periodic boundary conditions do not work properly

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#2533]
**Describe the bug**
If lightness, saturation or hue are selected in the color zones module by hue periodic boundary condition have to be applied to the interpolating curve. These boundary conditions are not implemented correctly, which leads to various unintuitive effects.

By default, two nodes are present at the extreme left and right end of the hue spectrum, which refer to the same hue due to periodicity of the hue scale. If one of the node is pushed slightly into the direction of the center the other node moves into the opposite direction. Why? This is not the correct way to implement periodic boundary conditions for an interpolation curve. Pushing the the nodes further, nodes may even loose contact with the interpolating curve.

**To Reproduce**
Push left and right most nodes.

**Expected behavior**
Proper periodic boundary conditions for the interpolating curve.

**Screenshots**
Nodes are indicate by arrows.
![color_zones](https://user-images.githubusercontent.com/1159508/57357743-ee051900-7173-11e9-909f-1398799b32e1.png)

Another example illustrating the non-periodicity of the interpolating curve. Problem applies to all three interpolation methods.
![color_zones](https://user-images.githubusercontent.com/1159508/57632001-d88f5500-75a0-11e9-92fa-8d902a31c65a.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: git master

**Comment by Nilvus** [comment]
@rabauke: if I'm not wrong, this is fixed since some weeks or months now. I close it, we need to clean issues. I sometimes use this module since few months and never had this issue. Feel free to reopen if I'm wrong.

**Comment by rabauke** [comment]
I think, I was involved in fixing. @Nilvus Thanks for closing this issue.
