### ISSUE TITLE
Colorzones: natural skin tones preset strange behaviour

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2536]
**Describe the bug**
after applying natural skin tones preset no change in the curve is visible 

default color zones: 
![image](https://user-images.githubusercontent.com/39386816/57402494-be87f800-71d7-11e9-9ec4-67b46af62cb7.png)
after applying natural skin tones preset:
![image](https://user-images.githubusercontent.com/39386816/57402549-d5c6e580-71d7-11e9-9bb9-420731f1c778.png)
just some dots at the bottom, curve cannot be edited (just moving dots aroung without an effect on the curve (or more precise flat line )

**To Reproduce**
1. Go to colorzones, activate it with default behaviour
2. edit curve --> fine
3. reset color zones and apply natural skin tones preset
4. try to edit the curve 

**Platform (please complete the following information):**
 - OS: OS
 - Version darktable 2.7.0+1146~gf34ea1c6b
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by TurboGit** [comment]
I conformed this is broken by 295bd95a.

**Comment by TurboGit** [comment]
Should be fixed new.
