### ISSUE TITLE
dt2.7: Histogram in darkroom sometimes not updated when toggling modules active/inactive

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#2538]
**Describe the bug**
In darkroom, the histogram (upper right corner) is sometimes not updated when toggling modules active/inactive.

**To Reproduce**
1. Go to darkroom
2. Apply image correction using modules. Lens correction as a simple example, but also reproducible with other modules.
3. de-active then re-active corrections modules several times and observe the histogram after each clic
4. Sometimes, after several activation/deactivation cycles, the histogram is not updated anymore.

**Expected behavior**
Histogram update each time the picture correction changes

**Platform (please complete the following information):**
 - OS: Ubuntu 18.10
 - Version : 2.7.0+1146~gf34ea1c6b

**Comment by TurboGit** [comment]
I confirm, I suppose this could be caused by the rework of the pixelpipe.

@edgardoh : what do you think? could you have a look at this as you're quite familiar with this part.

**Comment by edgardoh** [comment]
This is not new, is a limitation of how the cache works, to update the
histogram the pipe must be run, if the cache is used and no process is done
then the histogram is not updated.

To confirm, run dt with -d perf, if the pipe is not reprocessed (at least
one module) then histogram is not updated.
If the pipe IS reprocessed, then we have a bug.

**Comment by ClaesGitHub** [comment]
@edgardoh said "This is not new..."  
Well, the histogram updates OK in dt 3.6.2, 
but the histogram does **not** update properly in dt 3.7.0+1149.

Proof: open an image. Go to darkroom. 
Set a module, for example _base curve_, to ON: main window, the small orientation window, and the histogram all change. Correct.
Turn _base curve_ OFF: main window, orientation window, and histogram all change. Correct.
Turn _base curve_ ON: main window, and orientation window change but _not_ the histogram. Wrong.

I feel that the histogram ought to reflect the settings/looks of the main window.

As far as I can see, this behaviour is the same for many (all?) modules.
I also have a hunch that this bug is somewhat coupled to the bugs that AxelDE has reported.

OS: Manjaro KDE 18.04

**Comment by leclercj** [comment]
@edgardoh : Using -d perf option, I do confirm the correlation between histogram not updated and pipe not reprocessed.
Do we have similar pipe mechanism in dt 2.6 ? I can't succeed to reproduce this issue in dt2.6, and -d perf seems not supported by dt 2.6
Any possibility to modify the cache mechanism such a way that it also manage the histogram ?

**Comment by edgardoh** [comment]
-d perf is supported in 2.6, no idea why is not working for you.

Are you using opencl?
Check opencl_synch_cache in darktablerc, if is different than false, then
cache is used with opencl, maybe it was not set in 2.6

**Comment by AxelG-DE** [comment]
I can confirm the behaviour 

The link to my opencl [2514](https://github.com/darktable-org/darktable/issues/2514) issue like @ClaesGitHub indicated: 
Difficult for me to really directly see them related
They may have some interference

- As long as "my lag" is there (prior off/on) the histogram still works fine
- From the moment on, the histogram does not work as expected, that is the moment, the performance goes up. 
- AND: an old topic [#2420](https://github.com/darktable-org/darktable/issues/2420) pops up again. I just fiddled with "levels" on of, dragging etc. but see, how many history stacks I get: 

![Screenshot_20190509_221913](https://user-images.githubusercontent.com/49004103/57484460-5d305980-72a9-11e9-836e-346764817c07.png)

I wonder which influence the gcc-version has?!? I am on 8.2.0 but could go back to 7.3.0...

**Comment by leclercj** [comment]
My mistake: I now succeed to used -d perf with dt 2.6

I'm using opencl with both dt 2.6 and dt 2.7
I've `openCL=TRUE` in both dt 2.6 and dt 2.7
I've `opencl_synch_cache=false` in both dt 2.6 and dt 2.7

When histogram is updated with dt 2.7, I typically got the following traces:
```
32,659709 [dev] took 0,000 secs (0,000 CPU) to load the image.
32,666817 [dev_pixelpipe] took 0,007 secs (0,012 CPU) processed `renforcer la netteté' on GPU, blended on GPU [full]
32,723960 [dev_pixelpipe] took 0,057 secs (0,195 CPU) processed `profil de couleur de sortie ' on CPU, blended on CPU [full]
32,729688 [dev_pixelpipe] took 0,006 secs (0,012 CPU) processed `gamma' on CPU, blended on CPU [full]
32,729744 [dev_process_image] pixel pipeline processing took 0,070 secs (0,219 CPU)
32,737549 [dev_pixelpipe] took 0,006 secs (0,010 CPU) processed `renforcer la netteté' on GPU, blended on GPU [preview]
32,815886 [dev_pixelpipe] took 0,078 secs (0,274 CPU) processed `profil de couleur de sortie ' on CPU, blended on CPU [preview]
32,823344 [dev_pixelpipe] took 0,007 secs (0,020 CPU) processed `gamma' on CPU, blended on CPU [preview]
image colorspace transform RGB-->RGB took 0,149 secs (0,528 lcms2) [final histogram]
32,992871 [dev_process_preview] pixel pipeline processing took 0,333 secs (1,074 CPU)
```

When histogram is not updated with dt 2.7, I got the following shorter traces:
```
696,005568 [dev] took 0,000 secs (0,000 CPU) to load the image.
696,005610 [dev_process_preview] pixel pipeline processing took 0,000 secs (0,000 CPU)
696,005630 [dev_process_image] pixel pipeline processing took 0,000 secs (0,000 CPU)
```

My observation is that same operation in dt 2.6 can produces same shorter log, but then histogram is updated anyway.

**Comment by edgardoh** [comment]
>  My observation is that same operation in dt 2.6 can produces same
> shorter log, but then histogram is updated anyway.
>
I can't reproduce that, and I had noticed this behavior for some time. But
I agree that is annoying and histogram should be updated even if the cache
is used. so the difference is only if this is a bug report or a feature
request.

**Comment by leclercj** [comment]
An easy way for me to reproduce that is to use the "sharpen" module with high parameters (to make the histogram delta visible), the toggle this module on/off several times

**Comment by AxelG-DE** [comment]
In case of not updated histogram, it is not representing the content of the picture.

Difficult to consider this a feature :->

**Comment by AxelG-DE** [comment]
Why the cache is not being activated from the second time. It takes 2 or three on/off cycles. Here I do see a link to #2514

**Comment by AxelG-DE** [comment]
different compiler didn't make a difference, I tried GCC-7.5.0

**Comment by edgardoh** [comment]
There's more than the module on/off, if when the histogram is not updated I zoom in, which causes the pipe to reprocess, the histogram is still not refreshed.
This is new for me, no idea when started to happen.

**Comment by edgardoh** [comment]
This was introduced by the histogram profile, it needs the gamma input image to do the transform, and the image is not always available.
The same happen with the waveform histogram, even before 2.6.

Still no idea what to do with this, I'll keep looking.

**Comment by junkyardsparkle** [comment]
If it helps, I'm still using 2.7.0+901~ge2188ea4b built 2019-04-07 (before the big GTK changes) and I can reproduce this.

**Comment by AxelG-DE** [comment]
@edgardoh 
thank you very much. That part works here...
