### ISSUE TITLE
Consistent UI : having metadata import options on all 3 import options (not only image and folder ones)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2544]
**Describe the bug**
I've just found that my metada settings on preferences are not applied anymore since march. I've seen that my photos imported on 9th of March have these metadata (I never applied them with metadata editor) and since 23th of March, no metadata applied on importing (no photos between these two dates).

**To Reproduce**
1. Have creator, rights or one of the four metadata that could be applied on importing,
2. Click on import from camera (with camera or card plugged of course)
3. Select images you want to import and import them
4. See image information or if datas are applied on metadata editor (these infos are empty)

**Expected behavior**
Have default metadata settings on prefs applied on importing

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - darktable master

**Additional context**
It's probably a revision between the 1st march and 23th March that cause this bug as I regularly update darktable master.

**Comment by TurboGit** [comment]
Maybe to my work on metadata (and more generally lt) undo. I'll check.

**Comment by Nilvus** [comment]
@TurboGit : just a reminder but not the most urgent one. I will just add (valmy on french forum of darktable) precise that metadata editor keeps datas on fields when clicking on applying, making thinking that nothing applying. Of course, when using metadata editor, that works but having a way to know that options have been applied would also be better (a message for example just between fileds and buttons in grey saying that fiels have been applied would be sufficient I think).

**Comment by jenshannoschwalm** [comment]
I had a look into this; in fact i think it's not really a bug, it's just working in a different way than the manual says.

- The metadata import works only when enabling **apply metadata on import** in the **import options**.
- Maybe we should set the default to **On** to keep the old behaviour style?

**Comment by Nilvus** [comment]
>     * The metadata import works only when enabling **apply metadata on import** in the **import options**.
> 
>     * Maybe we should set the default to **On** to keep the old behaviour style?

@jenshannoschwalm : Thanks for helping here.

I've searched 3 times on preferences window and didn't find this option. I've always had import working by default on darktable 2.6 and master one until march.

Anyway, I look on darktablerc file and indeed I find this line:

`ui_last/import_apply_metadata=FALSE`

Change FALSE to TRUE and restarting darktable making import options working automatically as it was before.

So, you're right that's not a bug but a changed and not wanted behaviour. Probably by commit published on march.

I agree with you, **this should be activated by default to keep the old behaviour and most of the time, when we set import options (author, title...) on preferences window, we want this to be activated.**

And **I also suggest to add this option on preferences window, not only on darktablerc file.**

@TurboGit : is it possible to change that ? That seem to be quick fix with this informations.

**Comment by jenshannoschwalm** [comment]
@Nilvus 
![shot](https://user-images.githubusercontent.com/50982232/63371975-6b504480-c385-11e9-949e-c134e8e58b19.png)
You don't find **apply metadata on import** in the preferences window but in the small
submenu positioned low-left in the import window!

**Comment by TurboGit** [comment]
Indeed, on for me it is set (and in darktablerc value is TRUE). So I suppose that this was just a wrong click at some point. Looking at the code nothing has changed since a long time regarding this setting.

@Nilvus : do you confirm that using the "apply metadata on import" setting in the import window works for you?

**Comment by Nilvus** [comment]
> @Nilvus
> You don't find **apply metadata on import** in the preferences window but in the small
> submenu positioned low-left in the import window!

So we didn't talk on same thing. I was here talking about importing from the camera (or SD card with a card reader). That not same button than image and folder import. And one import option that appear only when an SD card or camera is plugged and detected, this option doesn't appear.

**Comment by Nilvus** [comment]
> @Nilvus : do you confirm that using the "apply metadata on import" setting in the import window works for you?

I was just answering to @jenshannoschwalm here. Of course, the "apply metadata on import from folder or image works. But this option doesn't exist when importing from SD card or directly from the camera. And that's here that my issue appear on march. This issue only applies to the window allowed to import directly from the camera (or SD card). So from "Mass Storage Camera" option only. Changing line talked on my previous comment from FALSE to TRUE make it works. In french, the window I'm talking about here :

![Capture-20190820224457-615x630](https://user-images.githubusercontent.com/45535283/63382955-2edc1300-c39c-11e9-8b0e-8ca883ee0d33.png)

**Comment by Nilvus** [comment]
> Indeed, on for me it is set (and in darktablerc value is TRUE). So I suppose that this was just a wrong click at some point. Looking at the code nothing has changed since a long time regarding this setting.

Reading on what you precise here, I have just tested one thing. darktablerc line related here `ui_last/import_apply_metadata=FALSE` applied on all 3 import options (folder, image and camera ones) but could only be changed from folder and image option (not camera storage one). So it seems that's probably not a darktable bug (nor changed code) but maybe a forgotten uncheck option from mine on march and didn't think it could also applied on import from camera as this option doesn't appear on this import window.

So I would just conclude this : it's just a not consistent UI here. As this option apply on all import windows, this option should appear on all import windows. So I would suggest if possible to just add same import options existing on folder and image ones, on the camera import one.

**Comment by TurboGit** [comment]
I see, indeed would be nice to have this option also on the import from camera dialog. Thanks for testing.

**Comment by TurboGit** [comment]
@Nilvus : can you test https://github.com/darktable-org/darktable/pull/2875 ?

Thanks.

**Comment by Nilvus** [comment]
Tested. PR solved that. Great.

**Comment by TurboGit** [comment]
@Nilvus : Glad to hear that all works well! I'm also pleased to have worked on that, since I'm reading/merging PR from others I have hardly time to work on dt myself, I'm back with this one :)
