### ISSUE TITLE
Errors compiling for Window's - non-fatal...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#2548]
I get 2 sets of errors when compiling for windows....not sure if its me or the code and it does not seem fatal but not sure what issues it would introduce...involves color mapping and transfer objects
**First set** 
[ 58%] Building C object src/iop/CMakeFiles/colormapping.dir/introspection_colormapping.c.obj
In file included from C:/msys64/home/prior/darktable/build/src/iop/introspection_colormapping.c:54:
C:/msys64/home/prior/darktable/src/iop/colormapping.c:231:1: warning: ISO C90 forbids variable length array 'mi' [-Wvla]
 static void get_cluster_mapping(const int n, float mi[n][2], const float wi[n], float mo[n][2], const float wo[n],
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colormapping.c:231:1: warning: ISO C90 forbids variable length array 'wi' [-Wvla]
C:/msys64/home/prior/darktable/src/iop/colormapping.c:231:1: warning: ISO C90 forbids variable length array 'mo' [-Wvla]
C:/msys64/home/prior/darktable/src/iop/colormapping.c:231:1: warning: ISO C90 forbids variable length array 'wo' [-Wvla]
C:/msys64/home/prior/darktable/src/iop/colormapping.c:232:33: warning: ISO C90 forbids variable length array 'mapio' [-Wvla]
                                 const float dominance, int mapio[n])
                                 ^~~~~
C:/msys64/home/prior/darktable/src/iop/colormapping.c:263:1: warning: ISO C90 forbids variable length array 'mean' [-Wvla]
 static void get_clusters(const float *col, const int n, float mean[n][2], float *weight)
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colormapping.c:283:1: warning: ISO C90 forbids variable length array 'mean' [-Wvla]
 static int get_cluster(const float *col, const int n, float mean[n][2])
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colormapping.c:300:1: warning: ISO C90 forbids variable length array 'mean_out' [-Wvla]
 static void kmeans(const float *col, const int width, const int height, const int n, float mean_out[n][2],
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colormapping.c:301:20: warning: ISO C90 forbids variable length array 'var_out' [-Wvla]
                    float var_out[n][2], float weight_out[n])
                    ^~~~~
C:/msys64/home/prior/darktable/src/iop/colormapping.c:301:20: warning: ISO C90 forbids variable length array 'weight_out' [-Wvla]
[ 58%] Linking C shared module libcolormapping.dll

**Second set**
[ 68%] Building C object src/iop/CMakeFiles/colortransfer.dir/introspection_colortransfer.c.obj
In file included from C:/msys64/home/prior/darktable/build/src/iop/introspection_colortransfer.c:33:
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:187:1: warning: ISO C90 forbids variable length array 'mi' [-Wvla]
 static void get_cluster_mapping(const int n, float mi[n][2], float mo[n][2], int mapio[n])
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:187:1: warning: ISO C90 forbids variable length array 'mo' [-Wvla]
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:187:1: warning: ISO C90 forbids variable length array 'mapio' [-Wvla]
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:207:1: warning: ISO C90 forbids variable length array 'mean' [-Wvla]
 static void get_clusters(const float *col, const int n, float mean[n][2], float *weight)
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:226:1: warning: ISO C90 forbids variable length array 'mean' [-Wvla]
 static int get_cluster(const float *col, const int n, float mean[n][2])
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:243:1: warning: ISO C90 forbids variable length array 'mean_out' [-Wvla]
 static void kmeans(const float *col, const dt_iop_roi_t *const roi, const int n, float mean_out[n][2],
 ^~~~~~
C:/msys64/home/prior/darktable/src/iop/colortransfer.c:244:20: warning: ISO C90 forbids variable length array 'var_out' [-Wvla]
                    float var_out[n][2])
                    ^~~~~
[ 68%] Linking C shared module libcolortransfer.dll

**Comment by leclercj** [comment]
We have exact same warnings compiling for linux and this is not new
This is only warnings, not errors, and this does not prevent darktable to build and run

**Comment by todd-prior** [comment]
Thanks…did some checking and its still a bit of a mystery…error is about declaration of variables…apparently your compiler might not deal with mixed declaration of variables and so the error but I saw a line checking
 for c99 compatibility for mixed declaration and it passed so not sure why the errors are happening??? Outside my understanding…thanks for your feedback
 
Sent from my Windows 10 device
 

From: leclercj
Sent: May 11, 2019 9:48 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Author
Subject: Re: [darktable-org/darktable] Errors compiling for Window's - non-fatal... (#2548)

 


We have exact same warnings compiling for linux and this is not new
This is only warnings, not errors, and this does not prevent darktable to build and run
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by Nilvus** [comment]
@TurboGit : should probably be closed.

**Comment by TurboGit** [comment]
Closing.

**Comment by leclercj** [comment]
Warning messages now removed by https://github.com/darktable-org/darktable/pull/2613
