### ISSUE TITLE
[culling] star-rating when number-key pressed twice or come back from full screen with "W"

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2558]
**Describe the bug**
when I press e.g. "4" (to give 4 stars) twice, the star rating 4 is applied to all pictures in current culling view (rating 4 is applied to 4 pictures)

**To Reproduce**
1. Go to 'culling, 4 (or 6) pics to be displayd, star-rating in my case >=3'
2. press 4 twice on the same image
or
2b. view full screen with "W" key and after come back change the rating
3. See "error"

**Expected behavior**
do not auto-apply a rating to all pics in view
- as it might happen, one press the key twice because:
- not clear, first one got taken
- cannot see the stars well, due to background
- afraid of lag

@AlicVB if that is a feature, I'd prefer to be able to switch it off :-)

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [current master +1154]

**Comment by Nilvus** [comment]
I don't know if it is a feature or not but I don't understand why press twice on same image ? Even for undo, I prefer using other choice I want (for example, 3 shortcut if I want to change for 3 stars...). But as this mode is in discussion to merge with expose mode, maybe this could be related to the actual PR for this merge : #2539

**Comment by AlicVB** [comment]
As @Nilvus said, there's a big rework in progress in this area.
If I understand well, you want actions to be applied just to the image under the mouse, right ? If so it involve how selection is kept (or not) in synch with culling view, and it's "under construction"

**Comment by AxelG-DE** [comment]
Guys, forgive me, if my explanation wasn't very well.
What I found was, suddenly my choice of selecting 4* was applied to all images in view. So I tried to figure out, what made it happen.

I do not press the same key twice on purpose :), so I can understand the wonders of @Nilvus 

@AlicVB you are right, I want my "command" to be applied only to the pic under mouse.

As I said, when I leave "W" mode (full screen), also weird things  happen. If all this is under rework, I will also shut up for some time :smile: :smile:

**Comment by Nilvus** [comment]
@AxelG-DE : indeed, that's not the same thing :smile: :smile:

What you want seems to be quite the opposite than this PR : #2545

**Comment by AxelG-DE** [comment]
@Nilvus 
>What you want seems to be quite the opposite than this PR : #2545 

not really, as I was not referring to multiple selections and intended behaviour outside the selection. My issue is without particular selection and hover on one pic, all over sudden the change is applied to all in view without intending this, sorry for repeating :) 

Here in this issue #2558 I really see a bug, from today's perspective (e.g. have a selection of 6 pics, hover on no 4 and press "W", release it and press again, you will see no action, because at that moment suddenly pic no 1 is selected. I hope that will be addressed as well in the rework @AlicVB mentioned :smile: ).

I see that discussion in that PR #2545 interesting and my opinion is 50/50, let's see, whether later I join in :-)
