### ISSUE TITLE
[Feature] Adding possibility to dissociate position displayed on an image when zooming on culling/expose modes

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2559]
@AlicVB 
One great feature to add would be the possibility to compare images with position of viewing dissociated on zooming. To be clear, sometimes, when we zoom to compare images, zoom could make an offset on view displayed between image.

I think that a good behavior would be to use a shortcut with mouse hover the image wanted to adjust and moving the position displayed on the image without moving others. And of course, this only with shortcut pressed (like actual W to display preview on lighttable only when it pressed).

**Comment by AlicVB** [comment]
@Nilvus : can you test PR #2593 ? I've implemented that, but with SHIFT key, not W (currently, dt don't take in account specific keys masks)
