### ISSUE TITLE
2nd preview window on Mac

### ISSUE THREAD

**Issue by homer3018** [darktable-org/darktable#2563]
So there are 2 things I just noticed when using the 2nd preview window on my Mac 5k. I'm using Master 2.7.0 1154 g1ea1ab272. Here are the two issues (that I think are linked) and I'll be referring to 1) and 2) in the steps to reproduce.
1) the size of the image displayed in this 2nd preview window
2) 2nd preview window seems to trigger an offset in the dimensions of the main Darktable window leading to offset pointer (and click) location.

Steps to reproduce the behavior 1):
1. Start DT
2. Click on a picture and go into the darkroom
3. Start the 2nd preview window
4. Use the scroll wheel to zoom in and wait a couple of secs

In my case, it is zooming, but after 1 or 2 secs the display size changes and the image is not taking the entire window real estate but 1/4 of it. Further zooming or out behave the same, it always revert to 1/4 of the size of the window.

Steps to reproduce the behavior 2): (directly following 1) steps)
1. go back to the main darktable window
2. Try to expand any module that is collapsed

In my case, when doing 2. I'm actually expanding the module that sits right below the one I do want to be expanded, as a result of the offset. My pointer appear to be on the module but it actually is really a few pixels below. This is occurring for me anywhere on the main window, the step 2. and the module was just to make the behaviour clear, hopefully it is.
It is even more obvious of you go and hover the icon "quick access for applying any of your styles" since they let you know that you're hovering them. If you do you'll actually be hovering one of the picture below and to hover the icon you'd need to point just above the icon.

Needless to say I was expecting the image to take en entire available real estate of the window regardless of the its current size. As for 2) I was not expecting any offset like that. It seems to occur whether DT was in full screen or not on my machine, I still have the same offset as a result (and it doesn't seem to be proportional to the size of the main window when I clicked the 2nd preview).

**Screenshots**
1) 2nd preview window full screen unzoomed
<img width="2560" alt="Screenshot 2019-05-12 at 15 00 23" src="https://user-images.githubusercontent.com/36423314/57582648-b249b680-74c7-11e9-8c1b-a78cb88abbf9.png">
1) same state, just zoomed in using the scroll wheel
<img width="2560" alt="Screenshot 2019-05-12 at 15 00 45" src="https://user-images.githubusercontent.com/36423314/57582656-d1484880-74c7-11e9-8d93-be7d07390afc.png">
I had screenshots for issue 2) but since it does not show the pointer position it won't be as useful. I'll try and and add some later if needed.

**Platform (please complete the following information):**
 - OS: Mojave 10.14.4 on 5k display
 - Master 2.7.0 1154 g1ea1ab272 

ps : this is my very first issue so please bear with me if this is lacking crucial information or anything like that.

**Comment by edgardoh** [comment]
I take that you are using darktable main window on one monitor and the 2nd window in another, and both have different resolutions.
If that's the case, can you try it with both, darktable main window and the second window, on the same monitor?
Try this two scenarios:
1 - 2nd window is first displayed on the other monitor and you move it to the first one.
2 - 2nd window and main window are first displayed on the same monitor.

For every scenario, try to resize the second window and refresh it, you can refresh it by modifying a value in any module on darkroom.

**Comment by homer3018** [comment]
I do not use 2 screens - I was just playing around with some of the new features and saw this. Just thought I would report if not already by someone else.

I used to use this on LR even on a single monitor to display at 100% the picture at the pointer location when I was trying to decide within a small set (2/3 typically) which one of those portraits was best in focus when you look at the eyes. So i would have the fit to screen view to look at the overall shot and a small 2nd window in a corner setup like so, and I would point the eyes to check, move to the next one with the filmstrip, point the eyes etc. When I saw this features has been added this is the use case I had in mind.

Anyhow, I can check again but I don't think moving the 2nd window does anything to my problem. I wonder if the pointer movement has something to do with it. It looks like when I use the scroll wheel without movement it's ok (ie displayed full screen) but as soon as I move my mouse again this is pretty much when it decides to display it 1/4 of its size. Not sure about that though might be a coincidence. The only thing that I noticed for sure is that if DT was in full screen, it would exit that mode. If after starting the 2nd view I go back to DT and select full screen again, then it gets rid of the offset.
If DT was not if full screen, then it stays like that, yet the offset is there (I thought it was the full screen at first but i dont think so).

I will give it a try again tonight with what you suggest and report back.

**Comment by homer3018** [comment]
Moving and resizing the 2nd window does not do anything with regards to the issue. It still behaves the same, and refresh correctly: I do monochrome and it refreshes straight away keeping the same 1/4 display size.

**Comment by edgardoh** [comment]
I don't see anything that can break the zoom, but I work on linux, maybe
I'm missing something specific for Mac. Let's see if someone else can
duplicate it, maybe we get more info.

**Comment by homer3018** [comment]
I just tried again. When I zoom in, it uses the full size of the window and the picture is still blurry, but once it's done working, this is when it shrinks it. Not sure if it helps but since I mentioned it might be my pointer moving or something, it is not, it's just the time it takes to render.

**Comment by edgardoh** [comment]
We can make a few attempts, can you build from source and test if I enter a
PR?

**Comment by homer3018** [comment]
I'm using the master at the moment and I think I should be able to pull your PR, build it and test.
Let me know whenever you have something and I'll do my best to test it asap.

Thanks for helping @edgardoh :)

**Comment by edgardoh** [comment]
Let's start by gathering some data. I have entered #2569, it will output some data on the console (or the Mac equivalent).
We want to know what happens before and after the zoom in on the 2nd window, if you can attach two different text files with the output of the console even better.

Let's continue this on the PR itself, is usually easier this way.

**Comment by MStraeten** [comment]
i had this behaviour too when i used it several commits ago and didn't use it since then. With my current build (darktable 2.7.0+1202~g53483fc94) everything is fine with the second preview window - it scales to fit the window
(OSX Mojave, retina display + full HD second screen)

**Comment by edgardoh** [comment]
This can be closed now.
