### ISSUE TITLE
Piwigo export doesn't work with special characters in the password

### ISSUE THREAD

**Issue by pvalsecc** [darktable-org/darktable#2564]
**To Reproduce**
1. Change your password to `E36#q$tvFR&I` in piwigo's web interface
2. try to login on piwigo in darktable with this password

**Expected behavior**
Export working.

**Platform (please complete the following information):**
 - OS: linux
 - Version 2.6.2

**Additional context**
I think this is because you don't URL encode the password when doing the POST.

**Comment by leclercj** [comment]
This is fixed in dev / master branch now
Thanks for this report

**Comment by pvalsecc** [comment]
Thanks for the fix!
