### ISSUE TITLE
Sigma 17-70mm recognised as EF 500mm f4/L IS

### ISSUE THREAD

**Issue by nilsholle** [darktable-org/darktable#2567]
**Describe the bug**
darktable wrongly recognises the Sigma 17-70mm 2.8-4 DC lens as Canon EF 500mm f4/L IS. I'm not quite sure if this issue is related to rawspeed or lensfun.

**To Reproduce**
Here is an example image.
[IMG_4993.zip](https://github.com/darktable-org/darktable/files/3171560/IMG_4993.zip)

**Expected behavior**
Image recognised to have been taken using a Sigma 17-70mm 2.8-4 DC lens.

**Platform (please complete the following information):**
 - OS: Kubuntu 19.04
 - Version 2.7 (built from master)

**Comment by parafin** [comment]
neither. It's related to exiv2.

**Comment by junkyardsparkle** [comment]
...and this is the suggested workaround:
 https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/

**Comment by Nilvus** [comment]
@TurboGit : I think this could be closed !

**Comment by TurboGit** [comment]
Ok, closing. Thanks for helping clean-up the issues.
