### ISSUE TITLE
Lens not recognized Sony 18-105 f 4

### ISSUE THREAD

**Issue by matthias-weiss** [darktable-org/darktable#2571]
**Describe the bug**
Camera is a Sony Alpha 6300. Lens is Sony SELP18105G E PZ 18-105mm F4 G OSS. In the lens correction module the lens, focal length and aperture has to be entered manually.

**To Reproduce**
1. Import image shot with this camera/lens combination
2. in darkroom enable "lens correction" module
3. module requires manual input

**Expected behavior**
automatic detection of lens + camera

**Platform (please complete the following information):**
 - OS: Debian GNU Linux "testing"
 - darktable version: 2.6.0
 - exiv2 version: 0.25-4

**Additional context**
I read the info text ["On Lens Detection"](https://www.darktable.org/2015/02/on-lens-detection-and-correction/) . I checked with the `exiv2` tool and it spits out `Exif.Sony2.LensID                            Long        1  Manual lens`.
However in darktable under `image information` it says for `lens`: `E PZ 18-105mm F4 G OSS`
So is this a problem of exiv2 or darktable?
Can you also recommend a quick temporary fix? because manually setting camera, lens, focal length and aperture for thousands of fotos is kinda ... annoying.

**Comment by matthias-weiss** [comment]
Find attached a raw file from my Sony Alpha 6300 for testing.

[_DSC6400.ARW.gz](https://github.com/darktable-org/darktable/files/3179165/_DSC6400.ARW.gz)

**Comment by chrik5** [comment]
For me lens correction works in darktable with you sample. I have exiv2-25 from Debian Buster. So it is not exiv2.

The lens could also be missing in the lensfun data. You can try to update your lensfun database with `lensfun-update-data`. If the command is not avaliable you need to  install `liblensfun-bin` package.

**Comment by matthias-weiss** [comment]
The installed liblensfun-data-v1 and liblensfun1 packages were already the latest versions for Debian "testing".

As you recommended I installed liblensfun-bin and updated with `lensfun-update-data`, the issue seams to be fixed. I am a little perplexed that having the latest packages wouldn't include equally up to date lens correction data.

Thank you for the quick resolution!

One last thing: I noticed that the `aperture` is not set automatically in the `lens correction` module (while the focal length is). Wouldn't that parameter affect vignetting and CA correction?

**Comment by Nilvus** [comment]
> The installed liblensfun-data-v1 and liblensfun1 packages were already the latest versions for Debian "testing".
> 
> As you recommended I installed liblensfun-bin and updated with `lensfun-update-data`, the issue seams to be fixed. I am a little perplexed that having the latest packages wouldn't include equally up to date lens correction data.
> 
> Thank you for the quick resolution!
> 
> One last thing: I noticed that the `aperture` is not set automatically in the `lens correction` module (while the focal length is). Wouldn't that parameter affect vignetting and CA correction?

You have to consider two things on lensfun last version or not : "official" last version of library (so packages) and last added or updated lens correction (lot of this was added on master version of lensfun).

Before posting an issue, please search quite largely as a lot of issues are already posted for this type of issue. As you can see, that's not a darktable issue but lensfun issue.
See on lensfun project page for more information : https://lensfun.github.io/. On "Supported lenses" page, you will see what is really corrected for your lens and see if vignetting and/or TCA correction is or not. You will also find on the lensfun page how it's possible to help on improve lens support for lensfun.

Please think of close this issue as it's not a darktable one.

**Comment by matthias-weiss** [comment]
thank you for the pointers. Closing the issue.
