### ISSUE TITLE
On culling a frame is draw around the images

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2577]
On culling a frame is draw around the images, this didn't happen when I first worked on culling, no idea when it was introduced or why, but it goes against the 50% grey background rule, so at least and option should be available for it, and disabled by default.

Same goes for the 'focus' feature, but I don't have an strong opinion on it. I find it distracting when comparing two images, but is useful when rating, so I can be sure on which image the action will be applied.

**Comment by Nilvus** [comment]
I've search on CSS AND with Gtk inspector to find if it's possible to change that on css. I've also asked @aurelienpierre and it seems that's always hardcoded. So I think the best way would be to move that's on css to easily adjust frame colors (and/or size). If this go on css, I could work on modify css.

**Comment by edgardoh** [comment]
I'm pretty sure that this wasn't there a while ago, but also is possible
that my memory fails.
Anyway, this is not the point. If this goes on CSS it will be great, sadly,
I have no idea how to do that.

**Comment by Nilvus** [comment]
I think a frame has always been here (not the hover one but the "default one") but on previous darker background so less visible.
I don't have any skills on C and GTK code, just on CSS. Hope someone could make this possible to tweak on CSS.

**Comment by aurelienpierre** [comment]
> I've search on CSS AND with Gtk inspector to find if it's possible to change that on css. I've also asked @aurelienpierre and it seems that's always hardcoded. So I think the best way would be to move that's on css to easily adjust frame colors (and/or size). If this go on css, I could work on modify css.

All the lighttable center is drawn with Cairo, there are no GTK widgets here. The best we can do is declare a color in the CSS and make Cairo fetch it and apply it, but if you see a frame, it's a Cairo rectangle.

**Comment by AlicVB** [comment]
I know exactly where it's coded. as @aurelienpierre it's cairo drawing, but with a css defined color. it's in `dt_view_image_expose` in view.c I have not the exact lines, as I'm currently on a modified PR, but it's after `// border around image`
colors used : 
- DT_GUI_COLOR_THUMBNAIL_BORDER (classic border)
- DT_GUI_COLOR_THUMBNAIL_SELECTED_BORDER (mouse over border)
Maybe the best here would be to use more specifics css colors for that, so we can finetune them (and even set them to the background color, if we want to hide them

**Comment by edgardoh** [comment]
I've been playing with the DT_GUI_COLOR_THUMBNAIL_*, but even if I make all the same I still get a border around the image, a shadow like this:

![culling border](https://user-images.githubusercontent.com/16430501/57808946-e678dd80-773a-11e9-917c-72c935bc73a4.jpg)

Probably something to do with how is draw, but I can't quite get it. Is around here:

https://github.com/darktable-org/darktable/blob/master/src/views/view.c#L1385

If I set no_deco = TRUE I have no border, so the 'else' is where things are draw.

It will be better to have colors for the culling, this is draw as thumbs, but is really an image and it should be possible to set a different format.
The issue is that this is draw on view.c and lighttable.c is who knows about culling.

**Comment by Nilvus** [comment]
Glad to see where it's coded.
@aurelienpierre : a possibility to adapt code and add CSS tags to edit frame with CSS ? I could help on CSS if I know how or if code is adjusted if necessary.

**Comment by AlicVB** [comment]
After some test too, the residual border, @edgardoh sees, seems to be an artefact of cairo drawing :(
I've done experiments to avoid that (by comparing the colors and skipping the drawing in case they are equals) and it seems to work well.
What I would propose if you agree, is to add a "DT_GUI_COLOR_THUMBNAIL_PREVIEW_BORDER" color, which can be defined by css (and be equals to thumbnail background if we want to hide it)

But, I would prefer to do that once PR #2359 is merged, to avoid too many rebasing.

**Comment by edgardoh** [comment]
> After some test too, the residual border, @edgardoh
> <https://github.com/edgardoh> sees, seems to be an artefact of cairo
> drawing :(
> I've done experiments to avoid that (by comparing the colors and skipping
> the drawing in case they are equals) and it seems to work well.
> What I would propose if you agree, is to add a
> "DT_GUI_COLOR_THUMBNAIL_PREVIEW_BORDER" color, which can be defined by css
> (and be equals to thumbnail background if we want to hide it)
>
Another option is to have a setting for this, as the focus can be useful in
some situations and get in the way in others. We already have the
use_decorations parameter, maybe it can be linked the the 'show 'overlays',
or create a new one specific for this, maybe a popup when right click on
the 'show overlays'.

> But, I would prefer to do that once PR #2359
> <https://github.com/darktable-org/darktable/pull/2359> is merged, to
> avoid too many rebasing.
>
Sure, if we go with the setting I can handle. The CSS I'm afraid is not my
thing.

**Comment by AlicVB** [comment]
well, if you ask me, I'm in favor on removing entirely this frame (for preview and culling) But I can understand that some people want to keep it. That's why I propose to set it in css, like all other gui elements now...
and if we add another color like DT_GUI_COLOR_THUMBNAIL_PREVIEW_HOVER_BORDER one can even set css to hide frame, except on mouse_over (imho, that's the best compromise, with a very light color in this case)

For the settings, I don't really like them if we can avoid them...

**Comment by edgardoh** [comment]
I thought you wanted to keep it. For me it should be removed too, and
that's easier, so maybe is better to wait for more feedback, with some luck
everybody agrees.

**Comment by TurboGit** [comment]
Well I think it would be nice to be able to keep them. I'll have a look to see how to control them with CSS.

**Comment by Nilvus** [comment]
> Well I think it would be nice to be able to keep them. I'll have a look to see how to control them with CSS.

I don't know if it's quick to make that but in case it is and you could add css control on this quickly, please inform me as I'm actually on correct other things on UI (some quite big items as dropdown arrows, and 2 other issues actually opened). So I could add css on this frame after GTK code is adapt if you want.

**Comment by AlicVB** [comment]
@TurboGit : as said earlier, I have a prototype working here with css. The tricky thing is that (don't ask me why) actual cairo drawing seems to produce artefacts, even with all colors equals... The quicker solution I've found is to check if colors are equals and skip all the drawing in that case.
This is just if you want to do it (otherwise I can do it too, as you want)

**Comment by TurboGit** [comment]
Ok I let you check then. I was wondering if this could not be due to the alpha channel being used in the loop to make a shape on the border. I would probably just use a simple border and not play with the alpha.

**Comment by AlicVB** [comment]
@TurboGit : yes I think it's the alpha channel too, but I don't get why drawing COLOR_A with whatever opacity on top of the same COLOR_A change anything (note that I'm far from an expert here...)
Anyway, I'll have a more precise look and do it (maybe just after PR #2539 )

**Comment by AlicVB** [comment]
I've done a first try here : https://github.com/AlicVB/darktable/tree/preview_frame
As said, we now have 2 new colors in css : `preview_border_color`  and `preview_hover_border_color` They are use for full preview and culling.
- They are set to actual values in darktable.css (that means frames are drawn like before)
- In darktable-elegant.css, I've hidden the "normal color" (by setting it to transparent)
- In darktable-elegant-grey.cs, I've also hidden the hover border

Note that I've changed a little how hover border is drawn : it's now just a really thin line around the image.
screenshot with darktable-elegant : 
![Capture d’écran_2019-05-18_19-09-40](https://user-images.githubusercontent.com/1818223/57972949-8172f100-79a1-11e9-9dce-033ce28f6efa.png)

Please also note that this is build on top of PR #2539 (so things may slightly differ from master if you test it)

**Comment by Nilvus** [comment]
Great, really great. Thanks a lot for all your hard work. I find this really better and the possibility now to change that with css...
I hope it's normal that you have two image without separation (top right).

**Comment by AlicVB** [comment]
As the PR as been merged during my msg writing, I've done a real PR for that : #2587

**Comment by AlicVB** [comment]
@Nilvus : yes it's normal, just to test images with plenty different ratios...
