### ISSUE TITLE
Raw overexpose indicators and histogram on lighttable

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2579]
**Is your feature request related to a problem? Please describe.**
One of major reason to exclude an image to be worked is the clipping on highlights (other the misfocusing, of course). I'd like to have a quick way to exclude a damaged image.

**Describe the solution you'd like**
I think useful to have a raw clipping indicator and a small histogram directly on lighttable display.

**Describe alternatives you've considered**
Until now I have to switch back and forth from the darkroom display

**Comment by pphotography** [comment]
Good idea, same as this issue:
https://github.com/darktable-org/darktable/issues/2382

**Comment by AlicVB** [comment]
This will be difficult for performance reasons : computing raw clipping (and even worse histogram) will take way too long...
fyi, we have been forced to not compute final image sizes, for the same issue, although computing image size doesn't require to load image data ! (on my computer, difference was x10)

**Comment by PaoloAst** [comment]
Maybe it can be possible while dt creates thumbnails.

**Comment by TurboGit** [comment]
I'm ok with AlicVB, maybe in some years with quantum machines, but right now that's certainly not wise to do that. While creating thumbnails that's not all is needed, in which color-space? You need to compute an histogram and the resulting cliping....
