### ISSUE TITLE
Epson R-D1x raw file not supported in darktable

### ISSUE THREAD

**Issue by calgarykev** [darktable-org/darktable#2582]
Submitted a file on raw.pixls.us and was directed here.  Hope I'm doing this right.  It's not really a bug, just looking for raw support so...

**Describe the bug**
Epson RD1X raw file not supported in darktable

**To Reproduce**
I get the "cannot read white balance" error msg

**Expected behavior**
it should open and be editable?

**Screenshots**
n/a

**Platform (please complete the following information):**
 - Ubuntu 16.04
 - Version 2.7.0+796~g8a5ce51

**Additional context**
n/a

Thanks!

Kev

**Comment by calgarykev** [comment]
I did a pull and recompiled now the error message I get is:
'SEIKO EPSON CORP. R-D1x' color matrix not found!

**Comment by LebedevRI** [comment]
Worksforme.
Did you update both the darktable and the submodule?

**Comment by calgarykev** [comment]
Dumb me!  Forgot the git submodule update.  Thank you very much!
