### ISSUE TITLE
Import parameter

### ISSUE THREAD

**Issue by Pirail** [darktable-org/darktable#2584]
**Describe the bug**
When importing photos create an empty folder on the date of import in addition to the import folder request.

**To Reproduce**
See the screenshots.

**Expected behavior**
For my session options I have the expected result except for this unnecessary and undesired empty folder.

**Screenshots**
![dartable preferences](https://user-images.githubusercontent.com/50749011/57949002-748fc800-78e3-11e9-9da9-79283226bff6.png)
![test import 1](https://user-images.githubusercontent.com/50749011/57948427-ea932f80-78e1-11e9-91a7-3e391ac72d75.png)
![test import 2](https://user-images.githubusercontent.com/50749011/57948428-ea932f80-78e1-11e9-8cc6-f68f4317c71f.png)
![test import 3](https://user-images.githubusercontent.com/50749011/57948430-eb2bc600-78e1-11e9-835a-12fb9c3fc435.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version darktable 2.6.2

**Additional context**
After several attempts I realized that what creates this empty folder and using the parameter $(EXIF_DAY) in "base directory naming pattern" or in "sub directory pattern" it does not create an empty folder however if you use it in "file naming pattern".

**Comment by abraxxa** [comment]
I have the same behavior.
