### ISSUE TITLE
[Culling] speed while scrolling in bigger collections

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2589]
**Describe the bug**
In current culling mode dt-2.7+1201 a collection of 10738 pics is way slower when scrolling in culling mode (maybe very logic) than one with ~50.

I have my timelapse and panos together in the same folder, 
- both I filter out by tags and star rating to 3, 
- than I have 1135pics, which I do by days, so I have finally ~60 filtered

@AlicVB 
this is alright with you, or shall I describe more?

**To Reproduce**
1. Go to 'lighttable --> culling' select collections with ~50 and one with around 12.000 pics
2. 'scroll by mouse wheel'
3. See the effect

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [e.g. 2.7+1201]

**Comment by AlicVB** [comment]
@AxelG-DE : can you test and report if PR #2588 enhance things ? Can you also test with filmstrip hidden ? Thanks

**Comment by AxelG-DE** [comment]
@AlicVB is it enough to use that little triangle at the bottom to hide filmstrip or do I need to disable in settings?

**Comment by AlicVB** [comment]
no, it should be enough with the triangle

**Comment by AxelG-DE** [comment]
hard to say but even at current master seems already a little faster
will fetch now

**Comment by AxelG-DE** [comment]
@AlicVB 
did the testing
- collection with 11.000 pics filtered to 68 pics
- mouse is Logitech MX-Master 2s (free spinning wheel)
- scroll from beginning to end with one spin of wheel

both: master and #2588 need (no real diff between the two)
-  9,7s without filmstrip
- 11,5s - 12s with filmstrip

**Comment by AlicVB** [comment]
@AxelG-DE : thanks for the testing. I'll have a look, but no promise I can do anything (As said earlier, time is spent in dt_selection_select(...) and dt_view_filmstrip_scroll... so 2 areas not directly related to culling)

**Comment by AxelG-DE** [comment]
@AlicVB 
please don't waste your valuable time! At the current stage, it is improved already a lot, compared to previously. 

It is really very nicely workable. A bit (nowadays, really only a bit) slower on larger vs. smaller collections, so what. 
It is not sluggish! 
I worked half a day now on that big collection and it was pure joy with +1202 

So it is not worthwhile to spend lots of efforts, merely when by chance we see something reasonable, why it makes a difference.

I can easily accept, we close this one here. #2592 and #2565 seems more important IMHO...

**Comment by AxelG-DE** [comment]
@AlicVB 
I am at +1613 currently and have the feeling, the scrolling speed got slower. 

Does this information help anything???

Cheers
 Axel

**Comment by AxelG-DE** [comment]
No action doesn't mean issue is solved.

**Comment by DieGoldeneEnte** [comment]
have you tested master again?
I saw some changes to improve improvements recently and read about some improvements in 3.0 specifically for lighttable.

**Comment by AxelG-DE** [comment]
for quite some time I didn't look into it, I even oversaw the comment from @DieGoldeneEnte, sorry for that.
It is damned fast now, and with my free spinning mouse wheel, I am an extreme tester now :) (and I do see some little odd things like mini squares, during the time, when no pics displayed yet, just grey background, but again, this is now at insane speeds)

@AlicVB thanks for all your efforts!
