### ISSUE TITLE
[Culling] show the correct pic when pressing "W"

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2592]
**Describe the bug**
@AlicVB 
sorry, I still found two small flaws :blush:

**To Reproduce**
1. Go to 'culling, zoom=4'
2. Click on '1st pic (top left)' and press W
3. Move mouse to '2nd pic (opt right) and press W. 
4. Sporadically, still pic 1 (top left) will be fullscreen-viewed. 
I think related is also the following:
5. sporadically when I want to uprate from 3* to 4* the first time key "4" is not acknowledged and I need to press twice

**Expected behavior**
Always switch the correct pic under mouse (not touched at that moment)  to full screen

**Platform (please complete the following information):**
 - Version [2.7.+1202]

**Comment by AlicVB** [comment]
@AxelG-DE :  can you test with PR #2588 that *may* solve your issue

**Comment by AxelG-DE** [comment]
@AlicVB 
I will, but now need to go to gym :->

**Comment by AxelG-DE** [comment]
@AlicVB 
I tested, however, it is still too sporadically on master, hence it is very difficult to confirm #2588 solve this issue...

One thing #2588 does actually do way better:
- on master, when I was outside of dt window, hover back on dt and scroll, that scrolling works.
- than try to press W or a star rating, it does not work.
- I need to actively click into dt-window.

- that behaviour totally is gone on #2588
- hover on dt, scrolling works and key strokes are recognized right away...

**Comment by AxelG-DE** [comment]
@AlicVB 
thank you for all your efforts. I think, this one needs to be closed :-)
