### ISSUE TITLE
Regression: #2512 is back: segfault with culling > 10 selectetd pictures in a film roll 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2597]
**Describe the bug**
Regression, see #2512

was fixed with #2530 but is back in

**Platform (please complete the following information):**
 - OS: OSX
darktable 2.7.0+1221~gc57a56ca0
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by AxelG-DE** [comment]
@AlicVB 
I confirm for master. For #2588 I can zoom up to 20

**Comment by AlicVB** [comment]
@MStraeten : Yes, I *think* I know exactly where it comes from. It has been reintroduce with the "specific zoom/pan" feature. I forgot a check at some point in the code. I'll fix it asap (maybe today, certainly tomorrow)
Thanks for the report.

@AxelG-DE : I was puzzle at first, but in fact, #2588 is not involved here, it's just that it's based on a previous master than the "specific zoom/pan". If you rebase it to current master, you will certainly have the same pb.

**Comment by AxelG-DE** [comment]
sorry to cause confusion. I should have had a better "navigation-view" on `git log --graph --abbrev-commit --decorate --oneline --all` :-)

You are totally right, now #2588 is merged and still crashes, sorry for confusing report

**Comment by MStraeten** [comment]
works fine, thanks for the fix
