### ISSUE TITLE
Images darkened just after import without user changes

### ISSUE THREAD

**Issue by seanmavley** [darktable-org/darktable#2598]
**Describe the bug**
Didn't behave like that in 2.4.x, so I'm assuming as a bug, unless some workflow process has changed.

Images imported are darkened in terms of exposure about a stop. 

**To Reproduce**
1. Import a photo (jpeg)
2. Image looks darkened relatively, without any change input whatsoever by user.

**Expected behavior**
Image imported, remains exactly as source file, awaiting user changes before anything happens.

**Screenshots**
Image on left imported to darktable. Darkened by default, just by importing. Original source image on the right.

![Screenshot from 2019-05-19 21-59-18](https://user-images.githubusercontent.com/5289083/57989571-05a1a300-7a8c-11e9-9db2-7a72958221e7.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Version 2.6.2

**Additional context**
Didn't behave like that in 2.4x. Just weird in 2.6.2

[Stackexchange question](https://photo.stackexchange.com/questions/108374/darktable-darkens-images-automatically-cant-reset)

**Comment by junkyardsparkle** [comment]
It sounds like a color management issue, but you'll probably need to supply a JPEG that exhibits this behavior in order for anyone to try to reproduce the problem. Do you observe the same thing (difference between dt and shotwell) with JPEGs from the web?

**Comment by seanmavley** [comment]
I ended up deleting Darktable's config and reinstalling Darktable.
