### ISSUE TITLE
GUI - partial copy check box not visible

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#2603]
**Describe the bug**
The check boxes on the partial copy dialog are not visible (tested on standard & elegant thème).

**To Reproduce**
1. Select an image on lighttable
2. Select copy on development module or ctrl-shift+c

**Expected behavior**
The check boxes should be visible.

**Platform (please complete the following information):**
 - OS: Linux
 - Version current master 2.7

**Comment by Nilvus** [comment]
Oh yes, I will see that.

**Comment by Nilvus** [comment]
I see it again and something strange here. The whole gui is a one box. Anyway, I can make checkbox appear by adding this (after dialog zone) :

```
.dialog-vbox treeview
{
  background-color: @grey_25;
}
```
And changing this line to a more brighter color (like grey_55 here) :
`@define-color field_hover_bg @grey_55;`

But that only work when hovering the line (and only for lines not selected, not for the line selected). I've tried all field lines, all "check" ones by using some flashy colors and can't find how to make checkbox appear with CSS for all items, even when not hovering.

So I'm now quite sure that something missed on GTK code to correct that with CSS. If someone who have skills on GTK could check that. @TurboGit or @aurelienpierre or @AlicVB

**Comment by TurboGit** [comment]
Found a solution, this is now fixed for 3.0 release.

**Comment by TurboGit** [comment]
@Nilvus : thanks for the hint it makes me on the right track, we just missed "check":

`.dialog-vbox treeview check`

**Comment by Nilvus** [comment]
> @Nilvus : thanks for the hint it makes me on the right track, we just missed "check":
> 
> `.dialog-vbox treeview check`

Wow, I was really sure that's could be solved before by GTK tweak. Never thought a second of just the check add... Anyway, good to see that fixed and quite surprise to see it was really simple.
