### ISSUE TITLE
[Performance] utilisation of GPU and CPU when importing panoramas

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2607]
**Describe the bug**
On a Core i9 9900k with 2x GTX1060 6GB I am importing 75 pano tiff files. (admittedly they are huge, 640MB-1.1G)
- CPU-load ~6% except short spikes
- only one of the two GPUs (GPU-0) is loaded with max 33% during peaks, mostly lower
- GPU-1 is idle
- HDD is capable of >140MB/s but only loaded 44MB/s (so also not the bottle neck)
- after approx 15 min. only 50% of the thumbnails are generated

**Ammendment**
also rendering those pics in lightroom/culling takes a fortune (~13s). Again, yes they are big, but
- no reasonable  CPU-Load
- no reasonable GPU-Load
- 20MB/s load to the HDD

**To Reproduce**
see above.

**Expected behavior**
Utilization of the available resources to the maximum to provide max. performance

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - nvidia-drivers-430.14
 - Version [2.7.0+1231~gf6692a045]

**Additional context**
I saw Aurelien's post on pixls.us and I can understand him and most of it easy to accept. Anyhow, my I kindly ask for support to _"improve the performance"_ , particularly the efficient usage of opencl?

While typing this bug report, I reached 2/3rd ;->>>

My library is an a very fast NVMe SSD

darktable-generate-cache has been executed

**Comment by AxelG-DE** [comment]
@dtorop
If your time allows, may I ask you to please also look into this one?

That's the one why I said at #2517 in general we have an opencl issue.

Thanks 
Axel

**Comment by aurelienpierre** [comment]
The biggest performance bottleneck with OpenCL is RAM <-> vRAM buffers copies (which are really expensive). It's worse in lighttable since pixels move from CPU to GPU for each thumbnail processing (several times, if not all your pipe uses OpenCL-enabled modules), then from GPU to CPU for GTK UI painting, then back to GPU for HDMI/VGA screen output.

At this point in the software's life, to fix this issue, you need to move from OpenCL + GTK libs to something that does everything on GPU. I don't see any easy fix here.

**Comment by AxelG-DE** [comment]
Dear @aurelienpierre,

got it, fully understand.

As there is no way, to handle this with reasonable efforts, shall I close this one or does it make any sense, to keep this open for documentation purpose or if someday the chance is there for what you have described?

**Comment by AxelG-DE** [comment]
No action doesn't mean issue is solved.

**Comment by DieGoldeneEnte** [comment]
You could try setting `opencl_use_pinned_memory` in darktablerc to true. In theory this should speed up transfers, but I haven't seen any speedups in darktable with normal sized raws.
The manual warns about this setting, so you should be carefull with this setting and verify the results:

> As they may not show any performance gain and even may produce garbled output, opencl_use_pinned_memory should be left at its default FALSE for those devices.
