### ISSUE TITLE
Zoom on lighttable preview doesn't work anymore

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2608]
**Describe the bug**
When using one image preview from lighttable (W or Alt+W shortcuts), it's now impossible to zoom. When using ctrl+mouse wheel or even shortcut to go to 100% zoom (I've reset shortcut but that doesn't resolve anything), nothing happen. The image still remains fit to screen.

Zooms works great on culling mode and it seems that preview zoom disappear since some last commit about culling or maybe 2nd preview window ? It was working some days before with an older commit, but don't which one.

**To Reproduce**
1. Go to 'lighttable ; navigation file'
2. Click on 'Alt+W or W'
3. Try to zoom with ctrl+mouse wheel or shortcut to 100% zoom
4. See that nothing happen. No zoom

**Expected behavior**
A working zoom on preview view with ctrl+mouse wheel and shortcut for that function.

**Platform (please complete the following information):**
 - OS: Ubuntu Linux 19.04
 - darktable 2.7 last revision

**Comment by AlicVB** [comment]
confirmed, it's certainly one of my last commits. I'll fix it asap, sorry

**Comment by AlicVB** [comment]
Should be fixed by PR #2612 it was a stupid omission from the "specifc" zoom PR.
Fact was that if you enter preview from culling there was no bug !

**Comment by Nilvus** [comment]
No problem ! That's the normal life of development, sometime forgotten something or create a new bug. And that's why development version and people ok to use and test it exists !.

All my congratulations and thanks for great functions you add on a so awesome software and your reactivity on improving it and correcting issues like this one ! I close this issue.
