### ISSUE TITLE
Presets for "export selected" doesn't restore the max height

### ISSUE THREAD

**Issue by pvalsecc** [darktable-org/darktable#2609]
**Describe the bug**
The "export selected" module in lighttable doesn't restore the max height value when selecting a preset

**To Reproduce**
1. Go to 'lighttable'
2. In the "export selected" module, create a preset with a max_height=0
3. set the max_height to 2000
4. Select the previously created preset

**Expected behavior**
The max_height should go back to 0, but stays at 2000. The max_width behaves as expected.

**Platform (please complete the following information):**
 - OS: ubuntu linux 18.04
 - Version 2.6.2

**Comment by johnny-bit** [comment]
Not reproducible on 3.2.1 nor current master (and most likely 3.4.0) :)
