### ISSUE TITLE
Shadow/Higlights slider in Split Tone Module.

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#2610]
Not sure if you'd call it a "bug", or just an oddity.
The shadow/highlights slider in the Split Toning module is orientated in a non-intuitive manner.
Shadows are on the right end of the slider, and highlights are on the left end of the slider.
Given that the histogram (and every other tool that maps luminosity in some fashion) has shadows at the left, and highlights at the right, wouldn't it make more sense for this slider to be orientated the same way?
Cheers,
Bruce.

**Comment by TurboGit** [comment]
I agree, this is counter intuitive.

**Comment by hellbuster** [comment]
I opened PR #2874 for this.
