### ISSUE TITLE
Pagefile.sys makes darktable unable to list directory listing

### ISSUE THREAD

**Issue by cyclops1982** [darktable-org/darktable#2616]
**Describe the bug**
I've just downloaded darktable 2.6.2. I store my photos on c:\photos\.
When i browse to my c:\ drive to import photos, darktable gives me the error message:
Could not read the contents of \
Error when getting information for file "C:\pagefile.sys": Input/output error

**To Reproduce**
1. Start Darktable
2. From the import on the left select 'Folder'
3. Click on the '\' at the top of the import film dialog.
4. Error occurs
Make sure you have windows pagefiles.
THere is no directory listing of files

**Expected behavior**
Allow me to import photo's. Ignore pagefile.sys file and/or continue reading directory listing if one file causes an issue.

**Screenshots**
Can be provided if needed, but description is quite clear.

**Platform (please complete the following information):**
 - OS: Windows 10 LTSC
 - Version Darktable 2.6.2

**Comment by Nilvus** [comment]
As this issue is old and Windows support had been improved, this is probably fixed. If needed, @cyclops1982 wait for 3.6 which will be released in a week and if you still reproduce, please ask here to reopen.
