### ISSUE TITLE
perspective correction: reconsider parameter limits

### ISSUE THREAD

**Issue by afr-e** [darktable-org/darktable#2617]
E.g., lens shift (vertical). See: https://discuss.pixls.us/t/perspective-correction-does-not-respect-proportion/12668/10

>Is there a limit in the vertical lens shift? I cannot seem to be able to correct this image to orthogonality.

>Although PTLens seems to have the same limitation as Darktable, I was able to achieve the following result with Hugin.

>Indeed, it seems the limit is too conservative.

**Comment by leclercj** [comment]
With this PR https://github.com/darktable-org/darktable/pull/2662 we may produce expected result also with darktable:

![65282ac4641242164604211804906cbb73192c63_2_1035x775](https://user-images.githubusercontent.com/22872204/58899958-6f61b400-86fe-11e9-844b-76cf717957bf.jpg)
