### ISSUE TITLE
dt2.7 "crop and rotate" active/inactive switch should come back to a 2-state logic

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#2618]
**Describe the bug**
In darkatble 2.7, the "crop and rotate" active/inactive switch ⏻ in darkroom toggles between 3 different states, whatever the module is expended or collapsed:
  1. active / original picture displayed + crop zone visible
  2. active / cropped picture displayed
  3. inactive / original picture displayed

**To Reproduce**
1. Go to 'darkroom'
2. Use the 'crop and rotate' module to resize the picture
3. Click on the activate/deactivate switch ⏻ several times
4. See the different possible states

**Expected behavior**
Come back to dt2.6, with 2-state toggling: active/inactive

If module is expended:
  1. active / original picture displayed + crop zone visible
  2. inactive / original picture displayed, crop zone hidden

If module is collapsed:
  1. active / cropped picture displayed
  2. inactive / original picture displayed, crop zone hidden

**Platform (please complete the following information):**
 - OS: ubuntu 18.10 or Windows 7
 - darktable version: 2.7 master (2.6 is not affected)

**Additional context**
- I'm not using the "expends the module when it is activated, and collapse it when disable" option
- Same issue also with "perspective correction" module

**Comment by leclercj** [comment]
After some investigations, I believe this regression has been introduced by https://github.com/darktable-org/darktable/commit/309f20b2665f84015aa9bc7ea295a5cfb60b1de5 and https://github.com/darktable-org/darktable/commit/23c81b9c81e15d9eeef7d137ac711ae2dc70a0ed commits.
More specifically, I can fix this issue by reverting back the code of dt_iop_gui_off_callback() in develop/imageop.c, but this is breaking the "automatically expand modules when switching on, and collapse when swttching off" code.
Here I'd appreciate help from @aurelienpierre

**Comment by leclercj** [comment]
https://github.com/darktable-org/darktable/issues/2535 has same origin

**Comment by TurboGit** [comment]
@leclercj : can you please try #2642 ?

Need to check very carefully as this is a tricky area. Thanks.
