### ISSUE TITLE
nikon d500, color target, raw.pixls.us

### ISSUE THREAD

**Issue by blonchkman** [darktable-org/darktable#2619]
Dear all,
Accordingly request on raw.pixls.us, i just uploaded nikon d500 raw samples of the xrite color target. The series of 16 nefs covers all crop, size and compression variants. I hope these pictures are usable, but if they are not, feel free to ask for corrected shots.

A big thank you to the whole team for this fantastic software.

kind regards
i blonchk

**Comment by johnny-bit** [comment]
Nikon D500 images work totally fine now, thanks!
