### ISSUE TITLE
Settings of the transition area of the mask drawing tools

### ISSUE THREAD

**Issue by Pirail** [darktable-org/darktable#2622]
**Describe the bug**
Inability to reduce the transition area of the mask drawing tools
**To Reproduce**
1. Go to a module that includes drawing masks
2.Choose the exposure module for exemple. In blend choose draw mask then choose add brush or add circle or add ellipse. And varying the transition area with the caps key+the mouse wheel and the transition area only increases whatever the direction of rotation of the mouse wheel.

**Expected behavior**

**Platform (please complete the following information):**
 - OS:Macos
 - Version  High Sierra 10.13.6
**Additional context**
After several tests the operation is normal with the use of the trackpad or a graphic tablet

**Comment by johnny-bit** [comment]
> After several tests the operation is normal with the use of the trackpad or a graphic tablet

It seems to me like the issue might've been mac input issues and/or gtk handling in mac. Either way it's outside of darktable scope.
