### ISSUE TITLE
CSS grey theme : strange black colors at some places

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#2624]
**Is your feature request related to a problem? Please describe.**
With the actual CSS grey theme (great thanks to @Nilvus ), there's some place in the UI where color are too dark/contrasted , IMHO : 
- histogram background
- surround of sliders

Here is what I have at home : 
![Capture d’écran_2019-05-25_12-52-32](https://user-images.githubusercontent.com/1818223/58368395-d1dfd680-7eec-11e9-9c6d-7f7bc8dd66a8.png)
In the first iteration of the theme, I'm quite sure it was not the case (you can compare with the screenshot in the initial PR : #2487 )
At first sight, it has been introduce in this commit : https://github.com/darktable-org/darktable/pull/2586/commits/85e615521e016823ea0c54062fd48dad13f67760 by the removing of the define-color for @graph_* 
If it's intended for any reason, no problems (I can always put them back anyway), I just want to be sure it's not an unwanted side-effect of some other changes...

**Describe the solution you'd like**
I really like the colors in the "initial" screenshot, but I'll perfectly understand if it has been decided that it was better like that for the "default" of this theme

**Describe alternatives you've considered**
tweaking the theme by myself

**Comment by Nilvus** [comment]
@AlicVB : Glad to see that you like my grey theme. What you have is of course not intended but normal on state. It's not a CSS issue but a sort of Gtk one. Some widgets doesn't change on fly when you change theme like the histogram backgrounds and sliders (bauhaus widgets). As I've understand, those widgets are special widgets adapted from how Gtk works so to have change on fly, they will need a quite big rework (with the risk of creating new issues). I use last revision of darktable (so with the commit you point) and I still have the same UI on these widget than the inital PR you also point.

So you just have to restart darktable to see normal CSS.

**Comment by AlicVB** [comment]
oops, my bad, I've too much switch back and forth between all of this... You're right, everything is back to normal after restart !
Sorry for the noise !

**Comment by AlicVB** [comment]
That said, I'll still have a look if we can't do anything, if I understand correctly the code, it's the same sort of code as in lighttable drawing for thumbnails, etc... and it change on the fly there...
If I find something not too intrusive, I'll do a PR and ping you !

**Comment by Nilvus** [comment]
> That said, I'll still have a look if we can't do anything, if I understand correctly the code, it's the same sort of code as in lighttable drawing for thumbnails, etc... and it change on the fly there...
> If I find something not too intrusive, I'll do a PR and ping you !

That would be a great thing and if something to adapt to css, I will be on !

As I don't know anything in development (except html/css) and Gtk, I have no idea of the level of difficulties here (and risks). @aurelienpierre or @TurboGit are certainly much more competent on this !

**Comment by AlicVB** [comment]
@Nilvus : I have something, see PR #2626 :)
finally, if I haven't make mistakes, that wasn't too much work !
Note that as for the rest of the ui, this works except if you want to change something in widget sizes (margins, ...)
