### ISSUE TITLE
Generating previews on Gimp affects Darktable

### ISSUE THREAD

**Issue by leonixyz** [darktable-org/darktable#2632]
**Describe the bug**

I don't know if this behaviour is actually a bug, nor whether it's Gimp's fault or Darktable's fault, but it is extremely weird and I would like to report it. I have never seen anything like this: something done in Gimp affects another running software - Darktable.

I start both programs then choose "File > Open" on Gimp. I browse to a directory containing images that were previously imported to Darktable, then select all images and click on "Generate previews". As soon as the previews start getting generated, Darktable keeps jumping from one picture to the next one, following the same order and timing Gimp is working on the previews.

**To Reproduce**

1. Start both Gimp and Darktable
2. Import a directory containing some images in Darktable
3. In Gimp choose "File > Open"
4. Browse to the directory imported in step 2 (using Gimp)
5. Select all images and click on "Generate previews" (using Gimp)

**Expected behavior**
Darktable should not be influenced by Gimp

**Platform (please complete the following information):**
 - OS: Arch Linux 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux
 - Gimp Version: 2.10.10
 - Darktable Version: 2.6.2

**Additional context**
Same issue created on Gimp's issue tracker: https://gitlab.gnome.org/GNOME/gimp/issues/3429

**Comment by rabauke** [comment]
What kind of file are you talking about? Raw files or jpg (or similar standard image format)? Is there any EXIF data embedded in the image files?

Just guessing: Generating previews in Gimp may affect some file system time stamps, which affects the ordering in lighttable view. Choose a sorting criteria in lighttable view that is not time and date and check if Gimp still affects Darktable.

**Comment by leonixyz** [comment]
> What kind of file are you talking about? Raw files or jpg (or similar standard image format)? Is there any EXIF data embedded in the image files?

Raw files. 

> Just guessing: Generating previews in Gimp may affect some file system time stamps, which affects the ordering in lighttable view. Choose a sorting criteria in lighttable view that is not time and date and check if Gimp still affects Darktable.

Actually it's not lighttable view. When I say "darktable keeps jumping from one picture to the next one", I mean it enters Darkroom view for each image that gimp is processing.

I was able to replicate this behaviour again and take a screenshot... hopefully that explains better what I mean.

![bug](https://user-images.githubusercontent.com/4563795/58632758-de966d00-82e6-11e9-9f1d-de3c2331a3d3.png)

**Comment by chrik5** [comment]
Gimp uses darktable to generate the previews I guess as Gimp has no internal RAW processor. So it is more a feature than a bug.

**Comment by leonixyz** [comment]
This issue is still present using GIMP 2.10.14 and Darktable 3.1.0+456~gc5536e0b2

**Comment by rabauke** [comment]
I think @chrik5 is right here. It looks to me as if Gimp tries to use darktable to generate previews of raw files. If there is already a running darktable instance, Gimp takes over this instances, which leads to the weird effects as reported. Not sure who to blame here.

**Comment by houz** [comment]
There is nothing wrong on the darktable side, it's a bug in how GIMP creates the thumbnails.
