### ISSUE TITLE
Raw HDR images only displaying one exposure, causing images to appear underexposed

### ISSUE THREAD

**Issue by joshbarrass** [darktable-org/darktable#2634]
**Describe the bug**
Raw HDR images taken with the HDR feature of the Lightroom mobile app do not display correctly in Darktable. Whereas in Lightroom (mobile), Lightroom (desktop) and the embedded JPG, the images appear bright with a high dynamic range, the raw .DNG file appears gloomy and underexposed, suggesting that the additional exposures are not being read by Darktable.

**To Reproduce**
1. Using the Lightroom mobile app, use the HDR camera in RAW mode (this was done in my case on an iPhone 8) to take a raw HDR photo.
2. Export the original .DNG from Lightroom mobile and copy it to a computer.
3. Open the file in Darktable.

**Expected behavior**
The image should appear as seen in the Lightroom app -- bright, and utilising the full dynamic range of the image.

**Screenshots**
[Image as it appears correctly in Adobe Lightroom](https://i.imgur.com/6iAVh4j.jpg)
[Image as it appears incorrectly in Darktable](https://i.imgur.com/QLBtEHu.jpg)

**Platform (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Version 2.4.4

I've tested again on Version 2.6.2 and the issue appears to still be present.

**Comment by WORD559** [comment]
I've tested again on Version 2.6.2 and the issue appears to still be present. I will try compiling Darktable from source tomorrow to see if it is still present there.

**Comment by Entropy512** [comment]
It's not exactly clear, but it's strongly implied that what LR Mobile exports is already an aligned/merged image - https://blogs.adobe.com/lightroomjournal/2017/03/lr-mobile-update-raw-hdr-capture-mode-for-ios-and-android.html

It may simply be that LR desktop automatically tonemaps or exposure-fuses such images, while Darktable just displays it as-is.

Try the exposure fusion function in the basecurve module, or simply push the exposure - is the shadow noise significantly worse than in LR desktop at similar shadow exposure?  (obviously this will clip your highlights, but for the purposes of determining what is/is not in the file, it's informative)

Note that if exposure fusion in the basecurve module seems to consistently cause an overexposed output - I'm going to be filing a bug report on this over the weekend and starting discussion on proposed fixes.  (I've got a patch that works really well, but has potential negative impacts for some users and thus needs some additional work/discussion on proper method of fixing the issue.)

**Comment by johnny-bit** [comment]
This is procesing question rather than darktable issue. The data is there, but the default modues and settings aren't the same. LR can also add processing info to DNG which darktable doesn't have access to which makes it a bit harder to have automagically "good out of the box" edit. That being said - current darktable flow would imo allow you to process the image in few steps achieving same or surpasing LR results.

Closing since it's not really a bug IMO.
