### ISSUE TITLE
[Feature request] Selective color editor 

### ISSUE THREAD

**Issue by Benja1972** [darktable-org/darktable#2646]
Watching some short tutorial on Color edit module in Capture one comes to thoughts that we can do same with  Color zone module in Darktable. I launched darktable and started plying. Comes to some issues. It is difficult keep edit on separated color swathes. Cannot control by numbers deltas of changes, cannot easily change lightness, saturation and hue for specific   selected color, we need to select same color three times switching between tabs in darktable. If you changed several colors and would like to back to zeros all changes for only one color, this is not possible as double click will reset curve in total.  Would be nice to have color equalizer in darktable with predefined standard colors used for color correction.   Maybe in can be integrated with existing color zones as in fact it do same. For more details look to documentation on Capture one 12.  [https://help.phaseone.com/en/CO12/Editing-photos/Working-with-colors/Color-editor](url)

**Comment by junkyardsparkle** [comment]
Have you looked at the [color lookup table module](https://darktable.gitlab.io/doc/en/color_group.html#color_look_up_table)?

**Comment by Benja1972** [comment]
Yes I use color lookup table module. And you are probably right that it is in some sort color equalizer. But it is not clear how colors are interpolated between selected colors. I cannot select a range of the colors like I can in color zone module and definitely we can do in color editor of C1

**Comment by edgardoh** [comment]
A copy of that module is probably not going to happen, but new features can
be added to ours. I'm currently working on a new feature, so if you enter a
feature request with some specific requirements we can discuss it.

**Comment by Benja1972** [comment]
Yes, It would be nice to have some new featuresi existing color zone modules. Now this module is color space oriented. I mean you have color space or original image and by tweaking curves you  can transform colors to new space/ranges. I propose feature with is switch this module to single color oriented. For example you know that you have many reds in your image, you what to select reds with adjacent colors and keeping this range of color selected have ability to control everything including lightness, hue and saturation in one instance. Moreover would be nice if selected range of colors can be highlighted on image (turning all other colors to grays for example). This is what we need for color grading and color correction. Same as in color look up table but there color swatches are fixed. I think we have everything now to implement this. We need to combine color zones with color look up table modules. You can be inspired  by watching shot introduction to color editor in C1 https://www.youtube.com/watch?v=m2PMsatRhEk

**Comment by edgardoh** [comment]
And how do you propose to do that in the current module?

**Comment by Benja1972** [comment]
I have some ideas. I need to think more and explain correctly with pictures what I would like to propose.

**Comment by aurelienpierre** [comment]
Be aware that color zones in darktable works in Lab color "space" whereas Capture One feature works in HSL, which can trigger other issues with hue linearity.

**Comment by edgardoh** [comment]
@Benja1972 , I have entered PR #2650 with a couple of features related to this.

**Comment by Benja1972** [comment]
Thanks I add my proposals there

**Comment by Benja1972** [comment]
I did a quick mockup of the module based on existing elements in darktable 
![MockUp-ColorEditor](https://user-images.githubusercontent.com/11920879/58823731-b1292680-863a-11e9-8447-8ef832a37f21.png)

**Comment by aurelienpierre** [comment]
Great, that's very helpful @Benja1972. Let us think of some algorithm to do that.

**Comment by edgardoh** [comment]
@Benja1972 , this is the same as the C1 module and I find it very limited (not sure if this is the right word), even the advanced mode. We have more powerful tools in darktable and by doing this it feels like we'll be duplicating functionality just to have a more limited module.

On this approach the main difference seems to be the ability of defining multiple color/saturation ranges, but the selection seems to be quite limited, at least compared to the blend module. So this will work fine for simple cases (like the image on the video that you shared), but with more complex cases we'll probably need to refine the selection using the blend module, and that will prevent from using multiple color selection on a single instance, so it will be the same as using the color zones.

The more I think about it the more I think that my approach is wrong regarding the color zones. I'm using it the same way as in 2.6, but now we have a lot of new and powerful features. Now that we can move modules and re-use masks, maybe the way to go is to let the blend module to handle the selection and let the curves to deal with the adjustment.
I know that this way I'll probably end up creating a new instance for each color, but that for me is not an issue, is just a couple of clicks, and having the edits separate usually makes my work easier.

Sorry for the long post, but as I said before I'm still not sure about the right way to go, so this is just to add to the discussion.

**Comment by Benja1972** [comment]
OK, we are thinking in same direction. I understand you. 


> but with more complex cases we'll probably need to refine the selection using the blend module

This is what I propose. I wold imagine one module with basic adjustment like on my mockup upper part but with possibility to handle several masks switching between them. Here we come to idea of basic local editor as one module. Creating mask based on color range gives as selective color editor, in general masks can be any types. So mock up can be in such structure

```
============================
list of adjustment sliders
-------------------------------
mask creating sliders 
-------------------------------
list of masks (local selection area)
============================
```

When I was thinking about this it remind me local edits in LR. There are no list of local areas in LR, they are presented by points of edits on image. 
![LR_loc](https://user-images.githubusercontent.com/11920879/58893977-7209dc80-86f1-11e9-9de2-56d0ff4e3249.jpg)

More or less same principle is  applied for C1 color editor with restriction to selective colors. 

If you think further in this module we can reuse masks from other modules but stack them to the list and quick apply basic changes to masked area, say change hue, lightness, saturation etc.  

Color editor for basic colors exist in GIMP see 
![Hue-Saturation_043](https://user-images.githubusercontent.com/11920879/58893913-59012b80-86f1-11e9-8340-57b9031cac1c.png)

**Comment by Benja1972** [comment]
Just want to add possible mockup
![MockUp-ColorEditor1](https://user-images.githubusercontent.com/11920879/58899930-5bb64d80-86fe-11e9-903d-962dac7fc557.png)
![MockUp-ColorEditor2](https://user-images.githubusercontent.com/11920879/58899934-5c4ee400-86fe-11e9-96eb-34cab1a35e8e.png)

**Comment by edgardoh** [comment]
I'm afraid we are going in opposite directions, what I meant is we should rely on the blend module for the selection, you're going the other way, you want to be able to define a selection and then apply any number of adjustments on it.
There's advantages for both approaches, but right now I'm more focused on the first one.

**Comment by Benja1972** [comment]
Probably you are right. It makes everything very complex and change the concept of darktable. So I would propose to make a selective color editor with predefined colors same as in GIMP with simply overlap slider (and probably feathering) but with possibility to change color by color picker.  This module will also work as hue/saturation for master (for image overall)

**Comment by edgardoh** [comment]
I don't use GIMP but I'll see if I find the time to play a bit with that module.

**Comment by aurelienpierre** [comment]
Could we at least have an HSL mode in the color zones module ?

**Comment by edgardoh** [comment]
Is there an advantage with HSL instead of LCh?

**Comment by aurelienpierre** [comment]
That's what Gimp, Photoshop, Capture One and Lightroom seem to use for selective hues editing, so I guess… The one thing that should behave better is the blending of the hues bands.

**Comment by aurelienpierre** [comment]
Also, note that, in theory, perceptual spaces like Lab, IPT or JzAzBz are better for selective color manipulation (in terms of colour remapping). What seems to be the issue here is the user control of the algorithms, and the way small changes in parameters produce unintuitive changes in the image.

**Comment by edgardoh** [comment]
Those are two separate issues, this module is Lab native and LCh is close to Lab, so if other colorspace is better for color manipulation maybe it will be better to create a new rgb native module.

The user control of the algorithms is mostly GUI, and that's what I'm concerned now. My current thinking is to change the workflow, that is, leave the module like it is and use the blend module when using the curves for selection doesn't work very well.

**Comment by aurelienpierre** [comment]
Sorry, in my mind Lab or LCh is the same (take the arctan and the euclidian distance of a and b, and you got h and C). It's similar with IPT or JzAzBz.

The problem of user control is not limited to the GUI, there is something in the algorithm that doesn't behave as it should, and probably nasty hacks. The new soft mode addresses some of the issues of the noise creation and hue blending, but I find it dilutes the settings too much. I have some ideas to improve that, but it will need testing.
