### ISSUE TITLE
Leaf Aptus 22 Support

### ISSUE THREAD

**Issue by homeiss** [darktable-org/darktable#2647]
I uploaded uncompressed and compressed raw files to raw.pixls.us and would love to see support for this the Leaf Aptus 22 digital back.

Thanks,
Cory

**Comment by LebedevRI** [comment]
Hmm. The sample that was previously on RPU loads just fine in darktable.
I'm guessing this is at least partially because 
```
Exif.Image.Software                           Camera Library
```
i.e. they were modified by some software afterwards

**Comment by homeiss** [comment]
I think there are two different versions of the Aptus digital backs, would this cause an issue? You can see there are two serial numbers on phase one's firmware page ( https://www.phaseone.com/en/Search/Article?articleid=2312&languageid=1 ). I have the older LFxxxxx KODAK version.

**Comment by LebedevRI** [comment]
Yes, that seems to have been it.
As for support for compressed raws - please open a separate issue in https://github.com/darktable-org/rawspeed/issues/new
