### ISSUE TITLE
Add support for Panasonic S1R raw

### ISSUE THREAD

**Issue by ChristopherRogers1991** [darktable-org/darktable#2649]
I have uploaded raw samples to raw.pixls.us that should cover all the aspect ratios supported by the camera (3:2, 4:3, 16:9, 1:1, 2:1, 65:24). Please let me know if there are any issues with the images, or if you need anything else.

**Comment by LebedevRI** [comment]
Looks like, just a year after introducing a new compression algo, they have changed it again.
It isn't immediately obvious to me what it is. The raw is certainly compressed.
(If they didn't change their block/packet layout, then now the packet has 11 pixels, i guess)
Please open an issue in https://github.com/darktable-org/rawspeed/issues/new

**Comment by bzhmurov** [comment]
FYI, LibRaw and RawTherapee now support S1/S1R. May be this could help.

**Comment by LebedevRI** [comment]
Yes, it will. I'm planning to look into that first before hopefully looking into cr3 stuff.

**Comment by bzhmurov** [comment]
So no S1 support then in 3.0?

**Comment by ElektroQuark** [comment]
I have an S1 here. How could I help adding the support to darktable?

**Comment by LebedevRI** [comment]
Err, this was supposed to get fixed by 6b08bc9a93cccf126277b93ae891aab10e1f25c4.
