### ISSUE TITLE
Severe bug on database migration from 2.6 to 2.7

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2652]
**Describe the bug**
Since commit 43e6bd2525383fc7e984313933462eecf7b7f434 from @edgardoh , migrate a database seems to no work properly. A friend just install darktable 2.7 and tried to migrate his 2.6.2 database. The migration seems to have begin as when he tries to launch again 2.6, an error message show that the database is too new for this version.
Anyway, when he tries to launch darktable 2.7, he have this message : `[init] database '/home/nicolas/.config/darktable//data.db' is out-of-date. aborting.`

Of course, he use the darktable executable and not darktable-cli. With the help of @rawfiner, we help this friend with a `git revert 43e6bd2525383fc7e984313933462eecf7b7f434`. After reverting this commit and compile darktable again, this friend succeed to launch darktable 2.7 and have his database migrated correctly.

**To Reproduce**
1. Start from a 2.6.2 database
2. Try launch darktable 2.7 to migrate the database.
3. See error message mentioned above

**Expected behavior**
Having this commit not make darktable thinking there's no UI as he launch for the first time and migrate older database.

**Platform (please complete the following information):**
 - OS: Fedora 30
 - darktable master

**Comment by Nilvus** [comment]
Just an important add : after migration complete and darktable launching correctly without the commit related, revert back the commit with git checkout master and recompile darktable make darktable still working great again. That confirms that this issue only appear if database migration is not made before applying the related commit : 43e6bd2525383fc7e984313933462eecf7b7f434

**Comment by edgardoh** [comment]
Strange, any way you can share the database?

**Comment by Nilvus** [comment]
Not sure, since he now have a migrated database. I just post this issue from what we test with this friend, as he doesn't have github account. I will ask him anyway if he have a saved 2.6 database.

Anyway, I would suggest to make the database migration more secure. For example by making a copy of the database before migration and if migration is ok and darktable correctly launch, add a short dialog that confirm database migration and asking to remove older database. That also could prevent some problem during the migration.

**Comment by Nilvus** [comment]
> Strange, any way you can share the database?

I send you his database by mail to avoid publishing his data publicly.
