### ISSUE TITLE
White points when demosaicing with 'local average'

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#2654]
**Describe the bug**
I was working on an image from PlayRaw at pixls.us. After switching demosaicing from PPG to AMaZE many big white spots appeared all over the image.
Happens when 'match greens' is set to 'local average' or 'full and local average' with demosaicing methods 'AMaZe', 'PPG' and 'VNG4'

![amaze](https://user-images.githubusercontent.com/49001045/58758882-7af88380-8522-11e9-8676-d36cff5fa05d.jpg)

XMP:
(https://github.com/darktable-org/darktable/files/3244592/20190531-092259-LackawannaStatePark_BullHillTrail-0037.cr2.zip)

RAW file:
https://discuss.pixls.us/t/play-raw-salamander-in-the-woods/

In exported images the white points are small but still present

**To Reproduce**
* Load RAW file with attached XMP
* Set 'match greens' in demosaicing to 'local average' or 'full and local average'

**Expected behavior**
Since the Darktable manual does not tell anything about white points that appear, these white spots should not be there

**Platform (please complete the following information):**
Darktable 2.6.2 from PPA on Ubuntu 18.04

**Comment by PaoloAst** [comment]
I can confirm that this bug is present in the development version too.

Sent from my mobile

Il dom 2 giu 2019, 10:52 Prugo Photography <notifications@github.com> ha
scritto:

**Comment by Nilvus** [comment]
I have it too with this image but I never have it with my images (not same camera, I have a Lumix one). And on the manual, it's written this : "In some cameras the green filters have slightly varying properties."

So maybe, this option is not suitable for the Canon camera used to take this image. And, these white points have a specific form so maybe it's not an issue. I tried exporting the image and the export is great, without any white point. So probably a feature to show something on some cameras, but what ?

**Comment by junkyardsparkle** [comment]
Also discussed [here](https://redmine.darktable.org/issues/11340).

**Comment by clavinet** [comment]
This still happens in darktable 3.4.0 with "match greens" set to a mode including local average, so both "local average" and "full and local average".

It's most noticeable on images with clipped shadows.

**Comment by johnny-bit** [comment]
So... we'd need to analyze if further... can you post a raw + xmp file that produces such result + output from run with `-d nan` for full picture of what's going on?

**Comment by clavinet** [comment]
I found it with an .orf raw, but it also happens with a .cr2 raw like the one linked in the OP, and I guess any bayer-based raw demosaiced with amaze.

- OP raw:

https://pixls-discuss.s3.dualstack.us-east-1.amazonaws.com/original/3X/3/1/318016c6056b3484d49d6507830aa435d0402fe6.cr2

- darktable console output, loaded the raw, selected amaze demosaic with local average:
```
$ LANG=en darktable -d nan
WINDOW DECORATIONS RELOADED
WINDOW DECORATIONS RELOADED
[dev_pixelpipe] module `raw black/white point' min: (-0.011474) max: (0.274229) [full]
[dev_pixelpipe] module `white balance' min: (-0.023484) max: (0.348116) [full]
[dev_pixelpipe] module `highlight reconstruction' min: (-0.023484) max: (0.348116) [full]
[dev_pixelpipe] module `demosaic' min: (-0.002539; -0.001511; -0.002098) max: (0.208913; 0.239483; 0.262098) [full]
[dev_pixelpipe] module `exposure' min: (-0.003244; -0.001791; -0.002621) max: (0.295691; 0.338908; 0.370880) [full]
[dev_pixelpipe] module `input color profile' min: (-1.533974; -19.768305; -14.715219) max: (63.207970; 30.390844; 46.773811) [full]
[dev_pixelpipe] module `color calibration' min: (0.000000; 0.000000; 0.000000) max: (0.289283; 0.323703; 0.429005) [full]
[dev_pixelpipe] module `filmic rgb' min: (0.000149; 0.000000; 0.000000) max: (0.258981; 0.288648; 0.402777) [full]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.599346; 0.576989; 0.677789) [full]
[dev_pixelpipe] module `raw black/white point' min: (-0.000651) max: (0.228904) [preview]
[dev_pixelpipe] module `white balance' min: (-0.001036) max: (0.242012) [preview]
[dev_pixelpipe] module `highlight reconstruction' min: (-0.001036) max: (0.242012) [preview]
[dev_pixelpipe] module `demosaic' min: (-0.001036; -0.000407; -0.002148) max: (0.205917; 0.228904; 0.248377) [preview]
[dev_pixelpipe] module `exposure' min: (-0.001120; -0.000230; -0.002692) max: (0.291455; 0.323952; 0.351482) [preview]
[dev_pixelpipe] module `input color profile' min: (-0.294124; -21.649368; -34.332920) max: (62.307766; 30.905529; 44.096493) [preview]
[dev_pixelpipe] module `color calibration' min: (0.000000; 0.000000; 0.000000) max: (0.286817; 0.310338; 0.405512) [preview]
[dev_pixelpipe] module `filmic rgb' min: (0.000149; 0.000000; 0.000000) max: (0.253960; 0.279671; 0.384018) [preview]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.522578; 0.567587; 0.662837) [preview]
[dev_pixelpipe] module `demosaic' min: (-0.001036; -0.000603; -0.005015) max: (0.203980; 0.228904; 0.245409) [preview]
[dev_pixelpipe] module `exposure' min: (-0.001120; -0.000508; -0.006744) max: (0.288717; 0.323952; 0.347286) [preview]
[dev_pixelpipe] module `input color profile' min: (-0.577006; -19.397192; -8.533200) max: (62.388371; 24.493486; 43.379612) [preview]
[dev_pixelpipe] module `demosaic' min: (-0.002539; -0.001511; -0.002098) max: (0.208913; 0.239483; 0.262098) [full]
[dev_pixelpipe] module `color calibration' min: (0.000000; 0.000000; 0.000000) max: (0.283393; 0.313967; 0.400027) [preview]
[dev_pixelpipe] module `exposure' min: (-0.003244; -0.001791; -0.002621) max: (0.295691; 0.338908; 0.370880) [full]
[dev_pixelpipe] module `filmic rgb' min: (0.000149; 0.000000; 0.000000) max: (0.256697; 0.286118; 0.379879) [preview]
[dev_pixelpipe] module `input color profile' min: (-1.533974; -19.768305; -14.715219) max: (63.207970; 30.390844; 46.773811) [full]
[dev_pixelpipe] module `output color profile' min: (0.001753; 0.000000; 0.000000) max: (0.523844; 0.574508; 0.659447) [preview]
[dev_pixelpipe] module `color calibration' min: (0.000000; 0.000000; 0.000000) max: (0.289283; 0.323703; 0.429005) [full]
[dev_pixelpipe] module `filmic rgb' min: (0.000149; 0.000000; 0.000000) max: (0.258981; 0.288648; 0.402777) [full]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.599346; 0.576989; 0.677789) [full]
[dev_pixelpipe] module `demosaic' min: (-0.001036; -0.000687; -0.004788) max: (1820.148071; 1820.148560; 1820.148193) [preview]
[dev_pixelpipe] module `exposure' min: (-0.001120; -0.000626; -0.006423) max: (2573.190186; 2573.190674; 2573.190186) [preview]
[dev_pixelpipe] module `input color profile' min: (-0.677039; -19.029417; -7.698896) max: (1573.578613; 24.145842; 46.143047) [preview]
[dev_pixelpipe] module `color calibration' min: (0.000000; 0.000000; 0.000000) max: (2575.389160; 2557.084473; 2837.908203) [preview]
[dev_pixelpipe] module `filmic rgb' min: (0.000149; 0.000000; 0.000000) max: (0.999998; 0.999998; 0.999998) [preview]
[dev_pixelpipe] module `demosaic' min: (-6729.381836; -6729.381836; -6729.381836) max: (10859.842773; 10859.842773; 10859.842773) [full]
[dev_pixelpipe] module `exposure' min: (-9513.499023; -9513.499023; -9513.499023) max: (15352.836914; 15352.836914; 15352.836914) [full]
[dev_pixelpipe] module `output color profile' min: (0.001762; 0.000000; 0.000000) max: (0.999993; 0.999993; 0.999993) [preview]
[dev_pixelpipe] module `input color profile' min: (-8593509.000000; -22.058748; -14.776010) max: (2867.082764; 61.298370; 46.202709) [full]
[dev_pixelpipe] module `color calibration' min: (0.000000; 0.000000; 0.000000) max: (15362.226562; 15360.451172; 15425.984375) [full]
[dev_pixelpipe] module `filmic rgb' min: (0.000148; 0.000000; 0.000000) max: (1.000000; 1.000000; 1.000000) [full]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.999994; 0.999994; 0.999994) [full]

```

- screenshot of what happens:
https://i.imgur.com/0XIm7PY.png

**Comment by johnny-bit** [comment]
@jenshannoschwalm or @heckflosse - since it's in amaze maybe you'll be able to know what's going on or what other debugging can be done to not have random white points in image?

**Comment by clavinet** [comment]
Here's one of my raws.

I found that adjusting the raw white point changes the distribution of the white dots.
[P2064530.tar.gz](https://github.com/darktable-org/darktable/files/5937675/P2064530.tar.gz)

**Comment by heckflosse** [comment]
Does this also happen with RCD?

**Comment by heckflosse** [comment]
> random white points in image

Start darktable from console this way:

```
OMP_NUM_THREADS=1 darktable
```

If the white points are still random, it's uninitialized memory, else it's a data race in omp.

**Comment by clavinet** [comment]
I tried running darktable with this option and the points were still there.
darktable still spawned multiple threads, I don't know whether it's supposed to with this option though or if that's irrelevant.

**Comment by heckflosse** [comment]
> and the points were still there.

still there or random?

**Comment by clavinet** [comment]
I'm not sure what you mean by that, but the distribution didn't change between various runs of the program.
They did change distribution when adjusting the raw white point slider.
Some raw white point values caused them to disappear.

**Comment by heckflosse** [comment]
> so the points appeared in the same locations every time.

then it's not a race and not uninitialized memory

**Comment by jenshannoschwalm** [comment]
@heckflosse, i observed the same issue when implementing rcd on some images. I am pretty sure this is the result of "non-normalized" input data.

When the demosaicer is processed the data may well be below zero or larger than 2-3 depending on black level and white balance matrix applied so this issue can only be observed under special circumstances (mostly dark/night images with high iso). @clavinet a first try would be to lower the black level values in "raw black/white point" or disable the white balance module.

Anyway - i am still fighting the cacorrect module to behave perfect with the roi concept, it's more difficult than i imagined so it will take a few more days. After that is done i will take care of this issue @johnny-bit

**Comment by heckflosse** [comment]
> i am still fighting the cacorrect module to behave perfect with the roi concept, it's more difficult than i imagined

If you master that issue, I will spend you a beer or two, in case we meet in future ;-)

**Comment by ralfbrown** [comment]
@clavinet darktable overrides the OMP_NUM_THREADS environment variable.  Use `darktable -t 1` to run with one thread (though there are still a couple of places where external code runs multithreaded, e.g. the GTK code which generates the stamp in the watermark module).  `OMP_THREAD_LIMIT=1 darktable -t 1` *might* get everything to run single-threaded.

**Comment by clavinet** [comment]
I tried `OMP_THREAD_LIMIT=1 darktable -t 1` but it still spawned more than one thread. It's probably not the culprit though as jens said.

**Comment by jenshannoschwalm** [comment]
@TurboGit i think this can be closed.
