### ISSUE TITLE
enter/leave notify are not executed on gradient slider

### ISSUE THREAD

**Issue by edgardoh** [darktable-org/darktable#2657]
The enter_notify_event and leave_notify_event are not executed on gradient slider, as a result the active handle is not highlighted unless is being dragged.

https://github.com/darktable-org/darktable/blob/master/src/dtgtk/gradientslider.c#L383

Not sure if this a gtk issue, I tested it before the CSS and iop order were merged and the issue was already there.

**Comment by dterrahe** [comment]
This seems to be resolved on master. Please test and close if appropriate.

**Comment by johnny-bit** [comment]
According to my tests it indeed works on master.
