### ISSUE TITLE
"lowlight vision" module breaks "display mask" in upstream modules with OpenCL

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#2659]
Enabling the "lowlight vision" module appears to somehow break the "display mask" functionality of some (possibly all) modules earlier in the pipe.

**To Reproduce**
Open an image, apply a drawn mask with the pencil tool in, for instance, the local contrast module. Click the yellow "display mask" button to see the mask. Enable the lowlight vision module, then again observe the display of the mask in previous module. For me, the yellow mask covers a region entirely unrelated to the drawn mask, possibly somehow related to the implicit masking in the lowlight vision module. The *actual* masking is *not* affected, only the *display* of the mask.

**Expected behavior**
Enabling a module shouldn't impact the display of masking in another module.

Version 2.7.0+1373 on Linux with OpenCL, NVIDIA driver 430.14 (initially 418.30)

UPDATE: Further testing shows that this also happens on 2.6.2, and only when OpenCL is enabled. Also, if I repeatedly toggle the "display masks" button, at some point the expected mask display comes back, but if I continue to toggle, the result seems to vary either randomly or according to some unknown time factor. Very weird. I would appreciate knowing if anyone can or can't reproduce this.

**Comment by junkyardsparkle** [comment]
Still there, but closing anyway, since apparently it's not an issue for anybody else.

**Comment by parafin** [comment]
It's a bug in lowlight openCL kernel:
https://github.com/darktable-org/darktable/blob/master/data/kernels/basic.cl#L2136

It should copy fourth channel from input to output, but it doesn't.
