### ISSUE TITLE
Bug: Ver 2.6.2 fails to recognize external drive on imac 10.14.5

### ISSUE THREAD

**Issue by OldRadioGuyAustin** [darktable-org/darktable#2660]
Darktable 2.6.2 fails to recognize external hard drive connected to iMac with OS 10.14.5.

1. Open Darktable and select lighttable
2. Import -> Scan for Devices
3. Reports: no supported devices found.

Should have reported a Seagate drive containing images. Finder recognizes this drive, and other image apps recognize it, also.

**Comment by parafin** [comment]
External hard drive is not a camera, import from device is for importing from the camera. I'm not sure what do you want here, but you can either import files directly from hard drive using import directory/files, or copy files to other location using Finder and then import that directory (you can copy files in darktable too, but it's probably easier to do in file manager).
