### ISSUE TITLE
Failing to build on Fedora 30 again after pull request #2650

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#2661]
pull request #2650 makes build on Fedora 30 fail.
Tested with gcc9 and clang as the main compiler. Seems to be the same problem as bug report #2458 
[bug-2650.txt](https://github.com/darktable-org/darktable/files/3250504/bug-2650.txt)

**Comment by Nilvus** [comment]
That's a difficulty of how compilers works (about OpenMP) between GCC 8 and GCC 9 and quite difficult to manage. See that PR about that problem (work in progress) : #2663

**Comment by jenshannoschwalm** [comment]
Yes - you are right.Thanks
