### ISSUE TITLE
Mask sliders do not catch mouseenter

### ISSUE THREAD

**Issue by lolluslollus** [darktable-org/darktable#2666]
Darkroom: every module with masks: the mask sliders (above and below, input and output) only sporadically respond to mouseenter. As a consequence, it can be a pain to make fine adjustments. 
Instead, I would expect a largish catchment area, so I can hover my pointer over the slider icon and turn the mouse wheel, immediately making an adjustment as fine as I need.
Version 2.7 fixed a similar issue in the tone curves, where the points have grown and catch mouseover just perfectly.
This happens in the windows and in the ubuntu version, 2.6.2 and 2.7.

**Comment by edgardoh** [comment]
Yes, see #2658 and #2657
