### ISSUE TITLE
Ctrl + Z gets me out of mask editing mode

### ISSUE THREAD

**Issue by lolluslollus** [darktable-org/darktable#2667]
Darkroom: every module with masks: apply a path mask (or any type of drawn mask), turn on "view mask", then draw a couple of points, then press Ctrl + Z to undo the last step. The last step will be correctly undone, but "view mask" is also disabled, and so is "show and edit mask elements".
Instead, I would expect that Ctrl + Z undoes the last step (like today) and preserves "view mask" and "show and edit mask elements", if they are switched on.

This happens in the windows and the ubuntu version, 2.6.2 and 2.7.

**Comment by m93a** [comment]
I agree this is very frustrating.

**Comment by m93a** [comment]
I checked. The bug is still present in v3.0. Issues don't just magically disappear when you leave them long enough.

**Comment by johnny-bit** [comment]
Yeah, the bug is still present even now - Undo action disables "display mask" and "show and edit mask elements"... @TurboGit - can you look at this once you have some time?

**Comment by TurboGit** [comment]
This will be very hard or impossible to fix. The undo actions know nothing about what is going on on the module. The iop is restored with it full params from an older version. So for sure if a fix is possible it cannot be in the undo code, maybe around by looking at the state before and restoring after... Some idea, did not look at the code and I won't have time soon.

**Comment by TurboGit** [comment]
Hum... I have an idea...

**Comment by TurboGit** [comment]
See #7373
