### ISSUE TITLE
darktable.css: version 2.7 does not pull the local version

### ISSUE THREAD

**Issue by lolluslollus** [darktable-org/darktable#2673]
I made some changes to darktable.css (scrollbar width) and I saved the file as /home/<myuser>/.config/darktable/darktable.css
After restarting the application, the changes do not take effect.
Then I made the same changes in the original file at /usr/share/darktable/themes/darktable.css, I restarted the application and the changes took effect.
This looks like a bug, but perhaps it works as designed.

This happens on Mint with the latest nightly for Ubuntu 18.04.

**Comment by Nilvus** [comment]
That's not a bug, just how you use it. CSS works great on user config (many users use it correctly. The path is quite the same as the default one. Here you don't put the css on the right folder. you have to add a default themes folder on your .config/darktable folder.

So please take time to search and verify if issues you post are real one or really useful to post (as one of your first issue where a PR was already posted (edgardoh answer). Think that all developers are volunteers that use their free time to improve darktable and answer issues.

So please close this issue.Last thing : please precise each time which version of darktable you use. For example, css is not the same way on 2.6 than on master.

**Comment by lolluslollus** [comment]
OK it's not an issue, but it is a breaking change coz /home/<myuser>/.config/darktable/darktable.css works on 2.6.2. Still, the improvements are worth it. Closing the issue.

**Comment by Nilvus** [comment]
> OK it's not an issue, but it is a breaking change coz /home//.config/darktable/darktable.css works on 2.6.2. Still, the improvements are worth it. Closing the issue.

Yes, and you will find quite others changes like that one as the master is a step to lot of improvements and some game changing.
