### ISSUE TITLE
Collect images, filter on geotagging values

### ISSUE THREAD

**Issue by shbitsus** [darktable-org/darktable#2674]
**Is your feature request related to a problem? Please describe.**
Collect Images, Geotagging:  is a boolean: geotag is populated or not.
It seems all the tools are built around helping to populate blank GPS metadata.
But even w/o fancy cameras, most users now have nearly ten years of smartphone images that are already geotagged. 
Looking at the other available filters (exposure, camera, aperture...), I see we can filter for images shot at 1/732 second (essentially any value), and while hovering over the query field shows a Tool-Tip saying we can enter a query, it would appear developers insist on providing a selectable list, even if that list is 100's of values long. Perhaps that's the trouble:  the list of geotags would be tens to hundreds of thousands of values long, and nobody would ever want to select one specific (very precise) location, but instead look for values near a location, or bounded by min/max Lat and Lon. 

**Describe the solution you'd like**
at a minimum, a SQL like query field:  where LAT between a and b AND LON between c and d.
, with support for decimal degrees format would be so much easier to enter.
An option to specify within radius of LAT/LON would also be handy.

**Describe alternatives you've considered**
I've tried using the Map view, but I can't seem to create a collection based on current Map view, nor even get it to select/preview only images on current map. Seems the only point of the Map view is to correct geotag values.

**Additional context**
I understand darktable roots are with Pro Photographers who are likely to have large collections of images that are well organized and tagged often using commercial software purchased decades ago.
I think I may be a new class of more technical amateur user that could never justify the cost of commercial software to organize photos, but has now found tools like darktable useful in cataloging their existing image archives.

Thank You,
Shawn Hughes

**Comment by phweyland** [comment]
Have you tried the current master ? There is now a "location" function which allows you to group images on the map. The locations are visible as collections under geotagging/tagged.

**Comment by johnny-bit** [comment]
Yeah, I think it's fixed in #6613 by @phweyland :)

**Comment by shbitsus** [comment]
Wow!  Why so complicated?  Now using (ancient v5.9) Digikam: drag a rectangle on the map. Done: collection of images I wanted are displayed.  Optionally, I may now select by any number of additional filters and apply tags, or not. Anyway, I hope my query improved Darktable.

**Comment by johnny-bit** [comment]
Yeah, module locations works nicely, check out the docs: https://darktable-org.github.io/dtdocs/module-reference/utility-modules/map/locations/

This can be combined with filtering and tagging
