### ISSUE TITLE
3D Lut from Windows to Linux

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#2681]
**Describe the bug**
In linux, 3D Lut module shows a warning when it tries to load a xmp with 3D lut created on windows

**To Reproduce**
Add a 3D Lut in Windows. Load the xmp in Linux.
**Expected behavior**
lut loaded
**Screenshots**
![image](https://user-images.githubusercontent.com/46730249/58995642-64c12080-87cb-11e9-83e4-535d22fafbbf.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version [e.g. 2.7.0]

**Additional context**
Issue found while doing a Play Raw session in discuss.pixls.us: (https://discuss.pixls.us/t/play-raw-playing-with-b-w/12868/9?u=gadolf)

**Comment by matze** [comment]
It's practically impossible to share such edits at the moment because the LUTs are not embedded into the xmp but load from a fixed external path (and this has of course nothing to do with the operating system). #2534 might help in the future but even that won't help with existing edits.

**Comment by edgardoh** [comment]
I'm not familiar with this module, but if it saves the relative path you can save your luts on one that can be accessed in both linux and windows (i.e. the config directory)

**Comment by phweyland** [comment]
I haven't paid attention too much to potential filepath issues between different OS. 
I'll try to find if dt has some resources to overcome this.

**Comment by phweyland** [comment]
I've tried to fix that PR #2690 but I cannot check the effect on Linux...

**Comment by johnny-bit** [comment]
AFAIK LUT3D files are external dependencies for edits, meaning that if one was to share edits done with lut included, the lut file would have to be added too (and then lut module path adjusted).

There's also another problem: some lut files are commercial + copyrighted, meaning you're not supposed to share them in things like PlayRAWs etc ;) So imo this is not really a bug.

(Also I tried sharing xmp file with my wife who has same luts as I do in same structure, but on windows and it seemed to work so... Fixed?)
