### ISSUE TITLE
Metadata editor : copy/paste broken

### ISSUE THREAD

**Issue by JonLur** [darktable-org/darktable#2700]
On Mac it is not possible to use command-V to paste text into fields in Metadata editor.
It is possible to right click with mouse and select 'paste' to paste the text from clipboard

I have used this function in previous versions and have not had any problems. Not sure when this was changed.

 - OS: MacOs 10.14.5
 - Version 2.6.2

**Comment by Nilvus** [comment]
It has been fixed since.
