### ISSUE TITLE
Undo doesn't work with photo rating

### ISSUE THREAD

**Issue by m93a** [darktable-org/darktable#2702]
**Describe the bug**
When I rate a photo as rejected and then change my mind, Ctrl+Z doesn't undo the rating. This is very frustrating when the rejected photos are hidden and I have to change the view, find the photo I rated by mistake and change the rating by hand.

**To Reproduce**
1. Go to darkroom
2. Set view to 'all but rejected'
2. Select an arbitrary photo in the film roll
2. Click on Reject (the photo should disappear)
3. Press Ctrl+Z (nothing happens)

**Expected behavior**
Rating should be a part of the history stack and Undo and Redo actions should have effect on it.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Version: 2.6.2 (and also `2.7.0~git1423.a63dd508e`)

**Comment by m93a** [comment]
In version 3.0 (from FlatHub) this issue is now fixed in light table, but remains in the film strip

**Comment by johnny-bit** [comment]
Indeed Ctrl+z doesn't work for filmstrip... @AlicVB - can you take a look once you have time?

**Comment by AlicVB** [comment]
Confirmed, and same happen for colorlabels. PR #7338 should fix it...
@johnny-bit : thanks a lot for your work in issue this days, it's so easy to miss them !
