### ISSUE TITLE
error: ‘gslider’ undeclared (first use in this function); did you mean ‘gsize’?

### ISSUE THREAD

**Issue by brothermechanic** [darktable-org/darktable#2703]
**Describe the bug**
Build error
**Platform (please complete the following information):**
 - OS: gentoo linux~
 - Version GIT
See build log 
[build.zip](https://github.com/darktable-org/darktable/files/3269523/build.zip)

**Comment by AlicVB** [comment]
@edgardoh : seems this one is for you (if you don't have time, I can fix it)

**Comment by edgardoh** [comment]
I'll try to take a look later today.

**Comment by AlicVB** [comment]
fixed by 8ba7509777bdd9ad4e30a8d8a18fe368b4821ac6 thanks
