### ISSUE TITLE
Fujifilm XF1

### ISSUE THREAD

**Issue by AlfredoXF1** [darktable-org/darktable#2706]
I have uploaded a Raw file in Raw.Pixls.us

Thank you for your job.

**Comment by AlfredoXF1** [comment]
Lets me know if you need more examples. Thank you again.

**Comment by LebedevRI** [comment]
Thanks for the sample.
That camera seems to be supported already?

**Comment by AlfredoXF1** [comment]
Hello Roman:
I found this and I saw that the XF1 file.raw was not in the list.
I am learning about Darktable but I dont have used a Fujifilm file yet ( I have several cameras)
I dont know if is already supported. I will try in a few days, in holidays.
Thanks.



    En domingo, 9 de junio de 2019 21:13:14 CEST, Roman Lebedev <notifications@github.com> escribió:  
 
 
Thanks for the sample.
That camera seems to be supported already?

**Comment by LebedevRI** [comment]
> I found this and I saw that the XF1 file.raw was not in the list. I am learning about Darktable but I dont have used a Fujifilm file yet ( I have several cameras)

Sooo i have to ask, the raw you uploaded, whom/where it's from?

**Comment by AlfredoXF1** [comment]
The raw is from my camera Fujifilm XF1. But I dont have used Darktable with the Raw yet. I want to learn about this tool in my holidays. Until now I have used another program with my fujifilm raws.

**Comment by AlfredoXF1** [comment]
The raw is from my camera Fujifilm XF1, but I dont have tried Darktable with my Fujifilm RAWs yet.  I thought was unsupported.
Greetings.
---------------------------------------------------------------------
    En miércoles, 12 de junio de 2019 21:40:49 CEST, Roman Lebedev <notifications@github.com> escribió:  
 
 

I found this and I saw that the XF1 file.raw was not in the list. I am learning about Darktable but I dont have used a Fujifilm file yet ( I have several cameras)


Sooo i have to ask, the raw you uploaded, whom/where it's from?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Fujifilm XF1 · Issue #2706 · darktable-org/darktable

I have uploaded a Raw file in Raw.Pixls.us Thank you for your job.
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 36 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |
