### ISSUE TITLE
IOP preset menus do not react to button-release

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2707]
**Describe the bug**
Releasing the mouse button over an entry in a module preset menu closes the menu, but does not apply the preset.  Instead, it is required to release the mouse button over the ≡-symbol before moving it, and to then perform another click on the desired item.

**To Reproduce**
1. Open an image in darkroom, press (and hold) left mouse button on an IOP preset menu (≡-symbol).  E.g., use the "equalizer" module.
2. Drag the mouse down to the preset you want to apply, e.g., "bloom".
3. Release the left mouse button.

The menu will be closed, but the preset will not be applied.

**Expected behavior**
The preset should be applied when releasing the mouse button.  

**Platform (please complete the following information):**
  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * darktable 2.7.0+1375~g6f0010465

**Comment by Nilvus** [comment]
Fixed by #2720 so could be closed (@TurboGit

**Comment by TurboGit** [comment]
Closing!
