### ISSUE TITLE
Olympus TG-6 Camera Support

### ISSUE THREAD

**Issue by luxagraf** [darktable-org/darktable#2712]
I have uploaded raw samples to raw.pixls.us that should cover all the aspect ratios supported by the camera (as far as I can tell it only supports 4:3 and all other listed ratios only apply to JPGs which are cropped). Please let me know if there are any issues with the images, or if you need anything else.

FWIW, I know DT supports the TG-5. When I click on these RAW files in DT, I get "failed to read camera white balance information from <filename>".

**Comment by sboukortt** [comment]
In the meantime, a possible workaround is [Adobe DNG Converter](https://helpx.adobe.com/photoshop/using/adobe-dng-converter.html) (which works in Wine), which [added support for the TG-6 in the 11.3 update in May](https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html#Latest_cameras). The resulting DNG file appears to work correctly in darktable.

**Comment by LebedevRI** [comment]
> In the meantime, a possible workaround is [Adobe DNG Converter](https://helpx.adobe.com/photoshop/using/adobe-dng-converter.html) (which works in Wine)

It actually doesn't. https://bugs.winehq.org/show_bug.cgi?id=46972

> which [added support for the TG-6 in the 11.3 update in May](https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html#Latest_cameras).

Are you very sure that talks about `Adobe DNG Converter` and not `Camera Raw`?

> The resulting DNG file appears to work correctly in darktable.
