### ISSUE TITLE
Storage option "Edit with GIMP" does not work in DT 2.7

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#2714]
**Describe the bug**
If I select "edit with GIMP" as a target storage in storage options, GIMP is launched, but the image is not opened.
GIMP gives a file not found error in its console, for example 
`failed: Could not open 'C:\Users\marco\AppData\Local\Temp\DSC03137.tif' for reading: No such file or directory`
In fact the export image is not created in C:\Users\marco\AppData\Local\Temp\, but it is created in the current film roll.
I guess the export image file is created in the wrong folder, or GIMP is called with a wrong parameter string.

**Platform (please complete the following information):**
- Windows 10
- DT version 2.7.0+1442~gca5f223e5

**Comment by chrik5** [comment]
I guess you are using the LUA script [gimp.lua](https://github.com/darktable-org/lua-scripts/blob/master/contrib/gimp.lua) as storage plugin?

Maybe @wpferguson can be of help here and he can move the bug report to the right place as well ...

**Comment by Mark-64** [comment]
Yes, I forgot this was not a native DT feature, sorry.
Fell free to move the report in the appropriate place

**Comment by Mark-64** [comment]
I move the bug report under the lua scripts project
