### ISSUE TITLE
CMake Warning at CMakeLists.txt

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2721]
**Describe the bug**
I build dt 2.7 with the following script:
```
#!/bin/sh

PATH_SCRIPT="/root/darktable"
CFLAGS_SCRIPT="-march=native -O3 -mtune=native -pipe"
CXXFLAGS_SCRIPT="${CFLAGS_SCRIPT}"
BUILD="Release"
MAKE="-j14"

cd $PATH_SCRIPT
git pull
git submodule update

cd $PATH_SCRIPT/build
cmake -DCMAKE_BUILD_TYPE=$BUILD CFLAGS=$CFLAGS_SCRIPT CXXFLAGS=$CXXFLAGS_SCRIPT ..
make $MAKE && make install

echo
echo "======================================================="
echo `/opt/darktable/bin/darktable --version  | grep "is darktable"`
echo "---installed successfully---"
echo "======================================================="


exit 0
```

and I get the following error-output:
```
`CMake Warning at CMakeLists.txt:343 (message):
  Could not find clang opencl-c.h header include dir`
```

```
CMake Warning at CMakeLists.txt:344 (message):
  Test-compilation of OpenCL programs can not be done.
```
clang 8.0.0 is installed...

What shall I do, 

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [current master]

**Comment by LebedevRI** [comment]
You probably also want `libclang-common-dev`, `llvm-dev`.

**Comment by AxelG-DE** [comment]
@LebedevRI sorry for soooo late reply.

Gentoo does not have -dev packages, when you install llcm and clang-common, you should have all in.

I do have those packages, but still get the errormessages from this issue

**Comment by LebedevRI** [comment]
It's been awhile since i last used gentoo.
Then you need to `find` if `opencl-c.h` is being installed, and where, and then compare the path to it with the paths it is being looked for in.
https://github.com/darktable-org/darktable/blob/ebda207c314031e55b9ec02ae3cc2971864b6c49/CMakeLists.txt#L293-L297

**Comment by AxelG-DE** [comment]
Dear Roman,

thanks for comming back on this...

I find:
# locate opencl-c.h
/usr/lib/clang/6.0.1/include/opencl-c.h
/usr/lib/clang/7.1.0/include/opencl-c.h
/usr/lib/clang/8.0.1/include/opencl-c.h

this ${LLVM_INSTALL_PREFIX} I can "read" but donno where this is defined. When I locate llvm, it is misleading me. Wondering, if @parafin could lead me to the right thing....

**Comment by LebedevRI** [comment]
Ah, yes, this is https://github.com/darktable-org/darktable/pull/1599.
Relevant: https://github.com/darktable-org/darktable/pull/1599#issuecomment-357709476
Dunno if things changed since then.

**Comment by AxelG-DE** [comment]
Not really as I still have this warning. At the same time, I cannot tell, if I really do have an effect by this. I did not dive into any clang topics yet. I do use gcc and ninja atm

**Comment by LebedevRI** [comment]
> Not really as I still have this warning.

... because that pr was never merged i would hazard a guess?

**Comment by AxelG-DE** [comment]
"i would hazard a guess?"
what do you wanna say? :-)

**Comment by AxelG-DE** [comment]
busy going thru my old BRs, whether they still persist, today I found this:
```

$ cmake -DCMAKE_BUILD_TYPE="Release" CFLAGS="-march=native -O3 -mtune=native -pipe" CXXFLAGS="-march=native -O3 -mtune=native -pipe" .. >> error.log
 CMake Warning at CMakeLists.txt:291 (find_package):
   Could not find a configuration file for package "LLVM" that is compatible
   with requested version "10".
   The following configuration files were considered but not accepted:
     /usr/lib/llvm/9/lib64/cmake/llvm/LLVMConfig.cmake, version: 9.0.1
     /usr/lib/llvm/8/lib64/cmake/llvm/LLVMConfig.cmake, version: 8.0.1
```
I am still building thru my own script, so I never saw this warning. Updated to llvm-10 and all related errors where gone after a reboot.
