### ISSUE TITLE
[performance] first attempt using a module is sluggish

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2724]
**Describe the bug**
During [#2514](https://github.com/darktable-org/darktable/issues/2514#issuecomment-497859835) I found this issue...

- My pixle pipe is rather emtpy.
- Open a NEF or ORF file
- I grab & drag the WB slider (WB always on), the response is a bit(!) sluggish, means the reaction is a bit scattering (also the "working..." indicator is less "hectical")
- also the histogram shows that scattering
- relieve the slider and grab&drag it again, now the response is way more fluent including the "working..." indicator is flickering more hectical...
- change opencl_synch_cache from _active module_ to _false_, the issue still persists
- start dt with --disable-opencl --> the issue persists **= not an opencl-issue**
- not only WB also exposure behaves the same
- I tried darktable -d perf, but cannot see a useful ouput
- darktable -d dev shows a little little evidence in a very little higher "cache hit rate so far" after re-touching the slider

**To Reproduce**
see above

**Expected behavior**
Same responsiveness from the beginning, as what I see, after I relieved the slider for once

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [**2.6.2 and current master**]

**Additional context**
Which further analysis could I do?
@dtorop I still hope, you have a good idea out of our discussions in #2514 (what one I will close now)

@ClaesGitHub I know you don't copy my case. As we have comparable HW, may I ask you, go thru this one here again, and have a brief look at your system?

TNX y'all...

**Comment by AxelG-DE** [comment]
Folks,

After I saw, I can visualize it with CPU-usage (higher on 2nd touch), I spent time analysing "-d perf" again
See attached .xlsx file, where I dragged the WB slider (keep in mind, it works also with exposure)...

- Filter column "E" after [dev_process_preview] and you can see in row 6, 2nd attempt benefits ~20 - 30%
- Filter column "E" after [dev_process_preview] is ~6% benefit (insignificant)
- Filter column "E" after  [dev_pixelpipe] and column L to "base" it is ~34% benefit (hmmmm one by one.....)
- Filter column "E" after  [dev_pixelpipe] and column L to "highlight" it is ~30% benefit (hmmmm one by one.....)
- Filter column "E" after  [dev_pixelpipe] and column L to "input" it is ~20% benefit (hmmmm one by one.....)

So, I hope this helps a bit....

[dt-perf_20190616.xlsx](https://github.com/darktable-org/darktable/files/3293972/dt-perf_20190616.xlsx)

**Comment by AxelG-DE** [comment]
Hello y'all,

I was suspicious, whether or not this issue is related to the situation, I have 2 GTX1060 in my PC. So I took out one, but still have the same issue.

Am I really the only one, who can reproduce?

I really find it annoying and disturbing the artistic flow, when I have to release the slider one more time, to get the smooth behaviour I can get after grabbing the slider again.

@AlicVB as you often cannot reproduce my issues :-)))) may I directly ask you for your experience...

Cheers
 Axel

**Comment by AxelG-DE** [comment]
sorry clicked wrong button

**Comment by AxelG-DE** [comment]
As this issue is still persistant in 3.0.0rc0-98-g46b65042f

Here I provide a "naked" log file after -d opencl -d perf
What I have done: 
- touched the WB-slider and gently slide to the right (25,000k)
- at 23s I clicked the reset button of WB
- at 27s I clicked the WB-slider again and in almost same speed, I slide again to the right (25,000k)

What I do see: for the second time grabbing the slider, from then on, I have way higher opencl usage reported in nvidia-smi.

I grep thru the log for quite some time and cannot find the culprit. Hopefully somebody can...

[dt-log_20191110_c.log](https://github.com/darktable-org/darktable/files/3828995/dt-log_20191110_c.log)

**Comment by AxelG-DE** [comment]
I wonder I found something, when I see those two sequences via less, side by side and more focues on "what happens" rather than how fast...


First touching the WB-slider

```
3,368957 [pixelpipe_process] [full] using device 0
3,377297 [dev_pixelpipe] took 0,008 secs (0,036 CPU) initing base buffer [full]
3,384763 [dev_pixelpipe] took 0,007 secs (0,008 CPU) processed `raw black/white point' on GPU, blended on GPU [full]
3,404142 [dev_pixelpipe] took 0,019 secs (0,008 CPU) processed `white balance' on GPU, blended on GPU [full]
3,407079 [dev_pixelpipe] took 0,003 secs (0,001 CPU) processed `highlight reconstruction' on GPU, blended on GPU [full]
3,445423 [dev_pixelpipe] took 0,038 secs (0,022 CPU) processed `demosaic' on GPU, blended on GPU [full]
3,450308 [dev_pixelpipe] took 0,004 secs (0,001 CPU) processed `input color profile' on GPU, blended on GPU [full]
3,454533 [dev_pixelpipe] took 0,004 secs (0,002 CPU) processed `sharpen' on GPU, blended on GPU [full]
3,460028 [dev_pixelpipe] took 0,005 secs (0,002 CPU) processed `base curve' on GPU, blended on GPU [full]
3,465678 [dev_pixelpipe] took 0,006 secs (0,002 CPU) processed `output color profile' on GPU, blended on GPU [full]
3,477705 [dev_pixelpipe] took 0,012 secs (0,038 CPU) processed `gamma' on CPU, blended on CPU [full]
3,477720 [opencl_profiling] profiling device 0 ('GeForce GTX 1060 6GB'):
3,477722 [opencl_profiling] spent  0,0056 seconds in [Write Image (from host to device)]
3,477724 [opencl_profiling] spent  0,0010 seconds in rawprepare_1f
3,477725 [opencl_profiling] spent  0,0010 seconds in whitebalance_1f
3,477727 [opencl_profiling] spent  0,0262 seconds in [Read Image (from device to host)]
3,477728 [opencl_profiling] spent  0,0010 seconds in highlights_1f_clip
3,477729 [opencl_profiling] spent  0,0030 seconds in ppg_demosaic_green
3,477731 [opencl_profiling] spent  0,0044 seconds in ppg_demosaic_redblue
3,477732 [opencl_profiling] spent  0,0003 seconds in border_interpolate
3,477733 [opencl_profiling] spent  0,0156 seconds in interpolation_resample
3,477735 [opencl_profiling] spent  0,0006 seconds in colorin_unbound
3,477736 [opencl_profiling] spent  0,0005 seconds in sharpen_hblur
3,477738 [opencl_profiling] spent  0,0005 seconds in sharpen_vblur
3,477740 [opencl_profiling] spent  0,0007 seconds in sharpen_mix
3,477741 [opencl_profiling] spent  0,0010 seconds in [Copy Image (on device)]
3,477743 [opencl_profiling] spent  0,0005 seconds in colorspaces_transform_lab_to_rgb_matrix
3,477744 [opencl_profiling] spent  0,0005 seconds in basecurve_lut
3,477746 [opencl_profiling] spent  0,0005 seconds in colorspaces_transform_rgb_matrix_to_lab
3,477748 [opencl_profiling] spent  0,0012 seconds in colorout
3,477749 [opencl_profiling] spent  0,0642 seconds totally in command queue (with 0 events missing)
3,479656 [dev_process_image] pixel pipeline processing took 0,111 secs (0,122 CPU)
```

Second touch of the slider
```
27,305859 [pixelpipe_process] [full] using device 1
27,308647 [dev_pixelpipe] took 0,003 secs (0,005 CPU) processed `white balance' on GPU, blended on GPU [preview]
27,309021 [dev_pixelpipe] took 0,000 secs (0,001 CPU) processed `highlight reconstruction' on GPU, blended on GPU [preview]
27,310420 [dev_pixelpipe] took 0,001 secs (0,001 CPU) processed `demosaic' on GPU, blended on GPU [preview]
27,311693 [dev_pixelpipe] took 0,001 secs (0,003 CPU) processed `input color profile' on GPU, blended on GPU [preview]
27,313931 [dev_pixelpipe] took 0,002 secs (0,006 CPU) processed `sharpen' on GPU, blended on GPU [preview]
27,318088 [dev_pixelpipe] took 0,004 secs (0,007 CPU) processed `base curve' on GPU, blended on GPU [preview]
27,321537 [dev_pixelpipe] took 0,003 secs (0,005 CPU) processed `output color profile' on GPU, blended on GPU [preview]
27,326466 [dev_pixelpipe] took 0,005 secs (0,026 CPU) processed `gamma' on CPU, blended on CPU [preview]
27,328585 [dev_pixelpipe] took 0,023 secs (0,075 CPU) processed `white balance' on GPU, blended on GPU [full]
27,331312 [dev_pixelpipe] took 0,003 secs (0,023 CPU) processed `highlight reconstruction' on GPU, blended on GPU [full]
27,333102 [opencl_profiling] profiling device 0 ('GeForce GTX 1060 6GB'):
27,333110 [opencl_profiling] spent  0,0009 seconds in [Write Image (from host to device)]
27,333113 [opencl_profiling] spent  0,0001 seconds in whitebalance_1f
27,333115 [opencl_profiling] spent  0,0038 seconds in [Read Image (from device to host)]
27,333116 [opencl_profiling] spent  0,0001 seconds in highlights_1f_clip
27,333118 [opencl_profiling] spent  0,0002 seconds in ppg_demosaic_green
27,333119 [opencl_profiling] spent  0,0003 seconds in ppg_demosaic_redblue
27,333121 [opencl_profiling] spent  0,0000 seconds in border_interpolate
27,333123 [opencl_profiling] spent  0,0003 seconds in colorin_unbound
27,333125 [opencl_profiling] spent  0,0003 seconds in sharpen_hblur
27,333127 [opencl_profiling] spent  0,0003 seconds in sharpen_vblur
27,333128 [opencl_profiling] spent  0,0004 seconds in sharpen_mix
27,333133 [opencl_profiling] spent  0,0005 seconds in [Copy Image (on device)]
27,333136 [opencl_profiling] spent  0,0003 seconds in colorspaces_transform_lab_to_rgb_matrix
27,333137 [opencl_profiling] spent  0,0003 seconds in basecurve_lut
27,333139 [opencl_profiling] spent  0,0003 seconds in colorspaces_transform_rgb_matrix_to_lab
27,333141 [opencl_profiling] spent  0,0006 seconds in colorout
27,333143 [opencl_profiling] spent  0,0084 seconds totally in command queue (with 0 events missing)
27,333511 [dev_process_preview] pixel pipeline processing took 0,028 secs (0,107 CPU)
```
@cryptomilk maybe you have also an idea, as you are an opencl-geek as well :smile:

**Comment by AxelG-DE** [comment]
- it is way more obvious, when you grab one of the RGB sliders rather than temp or tint

- I just tried with ALT+mouse wheel. Then it is smooth. 

- merely when you grab the slider with the left mouse button, it is reproducible.

**Comment by AxelG-DE** [comment]
@ClaesGitHub may I kindly ask you to test again, as our machines do have some similarities and I don't wanna believe, I am the only one :)

**Comment by ClaesGitHub** [comment]
Sorry, Axel. I can not make this phenomenon appear on my machine.
/Claes

**Comment by AxelG-DE** [comment]
To me the issue still persists

**Comment by AxelG-DE** [comment]
Many guys tried and seems nobody could reproduce my case. So I have to accept, somewhere I have the sand in my own gear box.... I will analyze on my side further and close for now...

**Comment by AxelG-DE** [comment]
I tried three different OS (2x Gentoo, 1x Kubuntu), Also I can see the effect on my Lenovo T450s (here best is exposure slider as WB is anyway seconds of reaction)

As of todays discussions on IRC I prepared those two gdb logs. Hopefully somebody can advice me how to proceed:

[dt-opencl.gdb.txt](https://github.com/darktable-org/darktable/files/4624154/dt-opencl.gdb.txt)
[dt_--disable-opencl.gdb.txt](https://github.com/darktable-org/darktable/files/4624153/dt_--disable-opencl.gdb.txt)

**Comment by AxelG-DE** [comment]
And here is a screenrecording...
[Sluggish_20200513-2020-05-13_23.00.59.mp4.zip](https://github.com/darktable-org/darktable/files/4624850/Sluggish_20200513-2020-05-13_23.00.59.mp4.zip)
[Sluggish_20200513_B-2020-05-13_23.36.13.mp4.zip](https://github.com/darktable-org/darktable/files/4624851/Sluggish_20200513_B-2020-05-13_23.36.13.mp4.zip)

**Comment by parafin** [comment]
Confirmed, found the fix, will commit a little bit later.

**Comment by AxelG-DE** [comment]
@parafin out of curiosity I tried today again with darktable 3.9.0+1595~g798668104 and the  behaviour is back. So from my perspective something or somebody has reverted your work. For this huge distance it would be hard to bisect due to so many db updates and such...

**Comment by parafin** [comment]
The logic of this code has been changed since. I suggest you open a new issue about this degradation. I have no desire (nor time) to debug this GTK shit again though, so it’s up to whomever did the refactoring to restore the previous behaviour (haven’t tried to reproduce it myself).

**Comment by AxelG-DE** [comment]
@parafin
I am happy to reopen a new issue. Just I donno what you have had done by that time to solve the issue. So for that new issue may I ping you anyway, that you could explain, where an inadvertent something might need to be refactored?

**Comment by AxelG-DE** [comment]
@parafin need to correct my self, what you have done is perfectly documented in the linked commit.

Donno whether I can bisect it over such long "distance". Usually it fails due to updated compilers or libs or such...

**Comment by AxelG-DE** [comment]
I am happy to open a new issue, just I would like to provide more analysis. 

ATM donno how. Due to rawspeed, I cannot do a git checkout at September 11th 2021 commits even, hence cannot bisect.

Is there another way how to find out, what or who might have touched this part?

@TurboGit do you have a good hint?
