### ISSUE TITLE
PR #2643 brakes opencl

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2725]
**Describe the bug**
opencl is not working anymore after darktable 2.7.0+1463~g77b3f7762

cltest gives me:
<kernel>:23:10: fatal error: 'rgb_norms.h' file not found
#include "rgb_norms.h"

bisect gives me:
[77b3f77629f739f3cc00c4a0d83f4b1bb1ccfb72] Tonecurve - added norms to tc RGB (#2643)

@phweyland could you please look into it?
TNX #

**Comment by MStraeten** [comment]
sudo cp <...>/darktable/data/kernels/rgb_norms.h /usr/local/share/darktable/kernels/ (or wherever the kernels are located on your system)helps
the makefiles needs to be updated

**Comment by AxelG-DE** [comment]
I'm lost.
8d19bd6f7 compiles well and opencl works
77b3f7762 compiles too but opencl does not work

Why should I need manual copy action?

**Comment by MStraeten** [comment]
the updated rgbcurve.cl requires the rgb_norms.h the former version didn't
On my system (osx) make install copies the required stuff from my build directory to /usr/local ...
but not the rgb_norms.h file ;)

**Comment by AxelG-DE** [comment]
Got it, will check soon

Anyhow, manual actions will fail on lots of users in the first place, I guess :)

**Comment by AxelG-DE** [comment]
That did the trick...

Hmmm where should be the proper copy of rgb_norms.h being invoked? 
How did you find that fast?

**Comment by MStraeten** [comment]
on osx darktable dev has some strange behaviour if starting from an installed binary (needs several attempts until all kernels are properly compiled to enable opencl) so i usually start it via darktable -d opencl from the command line. In general there aren't problems during stratup but this time compiling of kernels run into an error: missing rgb_norms.h resulting in an disabled opencl
Comparing the source and target kernel directory gave the result.

**Comment by AxelG-DE** [comment]
are you on IRC, if yes, which NICK?

**Comment by phweyland** [comment]
I'm building again from scratch to check what happens.

**Comment by phweyland** [comment]
I've just build this PR again.
rgb-norms.h is not copied in `C:\msys64\opt\dt-tc-norm\share\darktable\kernels`, I've cleared the kernel caches and open_cl starts.

![image](https://user-images.githubusercontent.com/23012047/59564383-8ec0e100-901c-11e9-9840-80cac6b6ad68.png)

![image](https://user-images.githubusercontent.com/23012047/59564402-c16ad980-901c-11e9-9821-d2931c9235c4.png)

I don't know how it succeeds in compiling but it does ...


What do you suggest ?



0.796662 [opencl_build_program] saving binary
0.796662 [opencl_init] compiling program `basic.cl' ..
0.812292 [opencl_fopen_stat] could not open file `C:\Users\philippe\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_GeForceGTX1050Ti_39907\basic.cl.bin.9fc3d00f89eb8a574f21210af5545ffd'!
0.812292 [opencl_load_program] could not load cached binary program, trying to compile source
0.812292 [opencl_load_program] successfully loaded program from `C:\msys64\opt\dt-tc-norm\share\darktable\kernels\basic.cl'
0.812292 [opencl_build_program] successfully built program
0.812292 [opencl_build_program] BUILD STATUS: 0

1.062225 [opencl_build_program] saving binary
1.062225 [opencl_init] compiling program `rgbcurve.cl' ..
1.062225 [opencl_fopen_stat] could not open file `C:\Users\philippe\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_GeForceGTX1050Ti_39907\rgbcurve.cl.bin.5e24199f70326fd463fa0d1e51327ab5'!
1.062225 [opencl_load_program] could not load cached binary program, trying to compile source
1.062225 [opencl_load_program] successfully loaded program from `C:\msys64\opt\dt-tc-norm\share\darktable\kernels\rgbcurve.cl'
1.077847 [opencl_build_program] successfully built program
1.077847 [opencl_build_program] BUILD STATUS: 0

**Comment by AxelG-DE** [comment]
It did build here as well, but then darktable-cltest failed

So without copying that file manually, your darktable-cltest is successfull?

I wonder, why this file is not being copied and I have no suggestion from my side, how to get it failsafe

**Comment by MStraeten** [comment]
darktable/data/kernels/CMakeLists.txt seems to be the key for it:

```
#
# install opencl kernel source files
#
FILE(GLOB DT_OPENCL_KERNELS "*.cl" "common.h")
```
...
`install(FILES ${DT_OPENCL_KERNELS} DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/darktable/kernels COMPONENT DTApplication)`

so "rgb_norms.h" in GLOB DT_OPENCL_KERNELS  is missing

**Comment by AxelG-DE** [comment]
@MStraeten 
you are really running warm on such things :-)))

**Comment by MStraeten** [comment]
... if its compiling but not installed, then something with install statements in the makefiles must be wrong - and fortunately it was quite easy to find the first line ;)

**Comment by phweyland** [comment]
> darktable/data/kernels/CMakeLists.txt seems to be the key for it:
> 
> ```
> #
> # install opencl kernel source files
> #
> FILE(GLOB DT_OPENCL_KERNELS "*.cl" "common.h")
> ``

I did already that and I got problem with travis.
Either using rgb_norms.cl or rgb-norms.h and FILE(GLOB DT_OPENCL_KERNELS "*.cl" "common.h" "rgb-norms-h") makes travis fail, because it tries to compile rgb_norms alone ...

**Comment by phweyland** [comment]
But what surprises me is that the rgbcurve.cl dynamic compilation works while the the included file is not there. There must be an explanation ...

**Comment by phweyland** [comment]
I'll make a try with FILE(GLOB DT_OPENCL_EXTRA "programs.conf" "rgb_norms.h")
Maybe travis will let pass.

**Comment by MStraeten** [comment]
the initial compilation of the *.cl files at the first start of darktable is based on the install-directory.  if it compiles even without copying the rgb_norms.h there, then there might be additional environment variables helping to find it at a different place.

**Comment by phweyland** [comment]
>  if it compiles even without copying the rgb_norms.h there, then there might be additional environment variables helping to find it at a different place.

Maybe. But the build won't work in another environment.
I've to find the way to makje the file rgb_norms.h copied at the right place, but preventing travis to try to compile this file.

**Comment by Nilvus** [comment]
@AxelG-DE : could you test now with #2727 now merged and should fixed that. To be closed.

**Comment by AxelG-DE** [comment]
- tested
- confirmed
- closed :-)

@phweyland thanks a lot for being that fast
@MStraeten thank you for pointing into the right direction
