### ISSUE TITLE
[FEATURE] Improve mask drawing

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#2730]
I would like to have some easier mask drawing. Currently you have to do a lot of clicks to get a result. If we use the gradient as an example.

You have to select it, click somewhere in the picture, then change the direction then change the transition zone.

I would like to click in the picture and keep the mouse button pressed. The direction I move the mouse to now defines the direction of the gradient. The further I move the mouse away from the first point the bigger the transition zone gets. This would make it much faster to draw a gradient mask.

The same can be applied to circles. The first clicks selects the middle, if I move it away from the mouse I can define the size. However it would need to drawn already while I move the mouse.

**Comment by cryptomilk** [comment]
@AlicVB

**Comment by edgardoh** [comment]
For the circle I don't see any difference with what we already have: we can set the size and feather with the mouse wheel on preview, and the click and drag sets the source area.

For the gradient a preview can be added, the mouse wheel can change the transition area and shift+ctrl mouse wheel the direction, so it will consistent with the ellipse. When already created, drag can set the transition area, that will be consistent with the clone circle/ellipse.

**Comment by AlicVB** [comment]
hmm for circles I don't think this is a good idea as click + drag is already used in retouch to define the source.
For gradient, I agree that there's some room for improvements. But at first thought, I would have said that click + drag should define the direction (you draw the gradient line)
And @edgardoh idea is great too.

I'll try to have a look

**Comment by cryptomilk** [comment]
Question: If a module is open with drawn masks activated. I there a keyboard shortcut to draw a gradient, e.g. ctrl+g. I don't find anything in the shortcut list, maybe I'm blind.

**Comment by AlicVB** [comment]
You can find a PR for most part of this here : #2739 
@cryptomilk : I've tested your proposal (define compression by distance from starting point of the click+drag) by I find it really confusing, so I ditch it for the moment (but you can now set compression before click+drag with mouse scroll and this is consistent with how other shapes works)

For the shortcuts, there's currently no possibility to add a new shape with a shortcut. This could be useful, but need to be carefully thought as there's a lot a small designs things to take care (cloning, manager, etc)

**Comment by TurboGit** [comment]
Closing as done now.
