### ISSUE TITLE
Better support for raws from negative scanners

### ISSUE THREAD

**Issue by kubrickfr** [darktable-org/darktable#2732]
Hello,

It would be great if you could support this scanner's raw files. It already kind of works but the invert module is really not working great with it so I suspect it's due to the lack of colour matrix or something...

I have uploaded a sample DNG.

**Comment by vonj** [comment]
Inverting color film negatives is actually a bit more involved than one can believe at first glance. Have a look at the negfix8. https://github.com/chrishunt/negfix8/blob/master/negfix8

It fails on color negatives if there is too much unexposed area in the film frame. (Too much of the orange film base.)

My workaround is to create a color profile from a crop without the unexposed area, then use that for the complete image.

There are commercial alternatives of course, a new one is:

https://www.negativelabpro.com


A side question - is it against the license of darktable to offer closed source plugins for it? (I assume yes, because of GPLv3)

**Comment by kubrickfr** [comment]
You are right in that I assume that inverting negatives, color or b&w, is relatively easy.
Specifically though, my problem is with b&w negatives, and considering how pink the pictures look in Darktable, I assumed that the lack of colour matric in DT was the issue:
![image](https://user-images.githubusercontent.com/2634188/59965785-1625bd00-9513-11e9-8f1e-293e3234fab3.png)
Then in Invert, if I select the darkest area possible, the result is thus:
![image](https://user-images.githubusercontent.com/2634188/59965807-3a819980-9513-11e9-9162-289c0377df4a.png)
Intrestingly enough, the colour of the film material appears gray:
![image](https://user-images.githubusercontent.com/2634188/59965814-4c633c80-9513-11e9-9c9e-24c1acd8b0ce.png)

**Comment by kubrickfr** [comment]
Maybe it's just the default WB (set in the DNG?) that is F-ed up?
![image](https://user-images.githubusercontent.com/2634188/59966043-b03b3480-9516-11e9-8743-afe08f534c3c.png)
If I set it to 1/1/1 it looks grey...

**Comment by kubrickfr** [comment]
RawTherapee doesn't have the same issues. No funky tint, inverting is as easy as inverting the tone curve (which I'm now doing in dt too, gives better results) and it opens files that dt just refuses to read, like this one:
https://drive.google.com/open?id=11n68m0ZLY23pkKBGof2_l-AT6f95sTJ4

**Comment by kubrickfr** [comment]
Do you want me to open a separate bug for the DNG that dt cannot open? I feel like I'm talking to myself here...

**Comment by Entropy512** [comment]
I'll need to revisit with the most recent DT version, but here's my experience with the "Invert" module:

The colorpicker really needs to be replaced with sliders that offer fine tuning.  The "dropper" function to choose the negative color sort-of works but the results of the invert module are HIGHLY dependent on getting the "color of film material" EXACTLY right.

The UI for fine-tuning a color in its current state is HORRIBLE for achieving this.

Another issue is that the module is operating on linear data prior to white balance, and the "color of film material" values are displayed as if they were post-whitebalance sRGB.  As a result, a "dropper" operation on orange film material results in the "color of film material" appearing green  (At almost any white balance setting, the blue/red multipliers are significantly higher than green - so attempting to display "unbalanced" RAW as if it were sRGB data causes the UI to show a greenish color that is confusing to the user.)

When you say "darkest area possible" - do you mean darkest in the negative, or darkest in the scene (which is BRIGHTEST in the negative) - you want to choose the brightest orange part of the negative.

**Comment by jenshannoschwalm** [comment]
Couldn't this Issue be closed now?

**Comment by TurboGit** [comment]
Yes, indeed!

**Comment by kubrickfr** [comment]
Thank you, that now works much better thanks to #2787
