### ISSUE TITLE
Overall preset speed decreases when "collect images" is in tag mode

### ISSUE THREAD

**Issue by t3mujin** [darktable-org/darktable#2734]
**Describe the bug**
Some actions on darkroom mode, most noticeably applying a preset, become much slower when "collect images" is using tag.

**To Reproduce**
1. Open darktable with a larger database (mine has around 340MB)
2. In lighttable click on 'collect images' and select a set of images per tag
3. Select a image and go darkroom mode
4. Click any preset

**Expected behavior**
It should be significantly slower than normal, in my case was around 7 to 10x slower

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version 2.6.2

**Additional context**
Suddenly I noticed a huge hit on performance for no apparent reason, some actions were taking much longer than usual. Initially I thought it could be related with OpenCL and started running darktable in debug mode and checking the logs. I noticed no issues in the pipeline with the OpenCL side, but several queries with LIKE where clauses got me suspicious, sometimes  an action would trigger dozens and dozens of queries like the one below. I switched the Collect Images from Tag to another and problem was no longer there. Changing the collect  and were able to replicate the behavior.

167,811531 [sql] /build/darktable-xuXDPt/darktable-2.6.2/src/libs/tools/filmstrip.c:693, function _lib_filmstrip_draw_callback(): prepare "SELECT DISTINCT id FROM images AS a WHERE   (flags & 256) != 256 and (flags & 7) >= 1 AND (flags & 7) != 6 AND (1=1 AND (id IN (SELECT imgid FROM main.tagged_images AS a JOIN data.tags AS b ON a.tagid = b.id WHERE **name LIKE 'Places|Europe|Netherlands'**))) ORDER BY datetime_taken DESC, filename DESC, version DESC LIMIT ?1, ?2"

**Comment by AlicVB** [comment]
sqlite queries in filmstrip redraw is normal, but I wonder why we don't reuse the "in-memory" table like we do in lighttable...
I'll have a look.
btw @TurboGit : are your "not-redraw-all" changes present in 2.6.2 ?

**Comment by t3mujin** [comment]
Just adding something: my workstation is an older PC with an OpenCL ready graphics card, it's not blazing fast but usually it gets the work done without too long delays. This issue is likely to be less noticeable in newer and more powerful machines, but I'd say the pattern in measured times should be the same.

**Comment by AlicVB** [comment]
proposed fix in PR #2737 
Be careful if you want to test it, it's based on dt master (2.7) and you won't be able to revert to 2.6.2 after...

**Comment by t3mujin** [comment]
I have a 2.7 version running in a VM, I can pull the latest changes, compile and run it on the same machine and the same database.

**Comment by AxelG-DE** [comment]
I tested, but honestly in dt 2.7.0+1472 I could hardly reproduce t3mujin's case. Anyhow, the current PR is pretty instant
