### ISSUE TITLE
Dragging multiple photos w/ custom sort resets the selection

### ISSUE THREAD

**Issue by m93a** [darktable-org/darktable#2736]
**Describe the bug**
When custom sort is enabled in lightroom, the user can reorder the photos using drag&drop. However, the UX breaks a few principles that are standard with drag&drop, which may cause rearanging images to become rather painful.

**To Reproduce**
1. Import some images
1. Go to lightroom
2. Select "sort by: custom sort"
3. Select mutliple images
    - either by „click, shift-click“
    - or with „click, ctrl-click, ctrl-click, …“
4. Try to move the selection to a different position
5. In the moment you click on the selection in order to move it, the selection changes, so that you're now dragging only one photo

**Expected behavior**
Selection should only change at the *mouse-up* event and only if the mouse was held for short enough time and drag didn't happen. The *mouse-down* event should *never* trigger the change of selection, it should be reserved for dragging.

**Workaround**
The only way to move multiple photos in the current version is to start the drag with shift pressed and then release it before dropping.
Steps:
1. Select multiple images
2. Press and hold shift
3. Click on one of the images and hold
4. Release shift
5. Move the cursor to the location where you want to drop the photos
6. Release mouse button

**Screenshots**
Video of the problem, using on-screen keyboard to show what keys I'm holding.
https://youtu.be/akqGH28NnUI

**Platform**
 - OS: Ubuntu 18.04
 - Version 2.7.0~git1468.f762741f8

**Comment by AlicVB** [comment]
I've done a PR which should solve this issue here : #2745 
Thanks for reporting
