### ISSUE TITLE
Improve accels window

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2738]
**Is your feature request related to a problem? Please describe.**
Actually, the new accels window is a good shortcuts reminder. But I think this window could be improved. The window is a a sort of "pop-out" window inside the main window and that recover the whole window. When this window is activated, there's no possibility to show the main window without quit this reminder. Even when this reminder is activated, it's impossible to show another application. The other application remains on background, the reminder always remains on first foreground. I find that behaviour trying to work on CSS for this reminder, but quite difficult without moving GTK inspector and text editor on another screen. Not the best way to work.

**Describe the solution you'd like**
@AlicVB : Making this reminder window as an **independant AND resizable window** would, I think, be better. To be more precise, So being the same type of window as the 2nd preview one on darkroom. 

And *why not add a button to display this reminder, for example with group, help, prefs... buttons?**

**Comment by Nilvus** [comment]
One more argument about having an independant window : that could make, for users who want to keep shortcuts viewable, the possibility to keep the reminder visible on another screen (for example). Of course, that seems having a reminder automatically updated if main view change.

**Comment by Nilvus** [comment]
As I post here to improve the reminder window, I'm also working on improving the UI with what's possible to do with CSS. Here the first preview of my work (work in progress). Hope you'll like it.

![Capture-20190618234413-1919x1051](https://user-images.githubusercontent.com/45535283/59722194-60f9b900-9223-11e9-997d-070b902a520a.png)

![Capture-20190618234508-1919x1050](https://user-images.githubusercontent.com/45535283/59722197-635c1300-9223-11e9-8d63-3a4c3075a756.png)

**Comment by AlicVB** [comment]
@Nilvus : an idea to implement what you propose : 
- add a "pin" icon in top corner of the actual accel window
- when clicking on this icon, switch to a "normal" window (resizable, ...) which will be around until one close it.

Note that it's not really straightforward (but possible) as it implies for the window to react to main ui changes, and that in many areas. No promise I'll have time to do that before holidays !

About css, don't hesitate to ask me if you need something else inside the code. Currently, you can play with class `accels_window` `accels_window_scroll` `accels_window_box` `accels_window_cat_title` `accels_window_list` (but I suppose you know that)

**Comment by Nilvus** [comment]
> @Nilvus : an idea to implement what you propose :
> 
>     * add a "pin" icon in top corner of the actual accel window
> 
>     * when clicking on this icon, switch to a "normal" window (resizable, ...) which will be around until one close it.

That would be great, take your time, the freeze of this version is only in about 3 months ;-)

> About css, don't hesitate to ask me if you need something else inside the code. Currently, you can play with class `accels_window` `accels_window_scroll` `accels_window_box` `accels_window_cat_title` `accels_window_list` (but I suppose you know that)

Yep, thanks, I have them all ! If needed more, I will come back to ask you.

**Comment by AlicVB** [comment]
@Nilvus : I have something for you here : #2741 
For css, I've done a "minimal" change to resize the "sticky" icon. Please check and enhance if needed. Also I'm not sure if I need to add another special class for the sticky window, just ask me if you need it !

btw, for the "sticky" icon, I've reused the "multi-instances" one, but if someone comes with something better...
