### ISSUE TITLE
(dt_dev_pixelpipe_t *) pipe->nodes not updated accordingly to (dt_iop_module_t *) module->iop_order

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2748]
https://github.com/darktable-org/darktable/blob/52bc31cacdb266d1f9a9c78f2c409e366faec416/src/develop/pixelpipe_cache.h#L55-L57

allows to compute a hash at any module level in order to check, for example, if lower modules have changed and invalidate the cache properly.

The `int module` argument is the position of the module in the `Glist * (dt_dev_pixelpipe_t *).nodes`. This list is built in 
https://github.com/darktable-org/darktable/blob/52bc31cacdb266d1f9a9c78f2c409e366faec416/src/develop/imageop.c#L1455
, which reads the ` GList * (darktable_t *).iop` and does not seem to care at all about the `(dt_iop_module_t *).iop_order`.

So, `Glist * (dt_dev_pixelpipe_t *).nodes` is not synchronized with `(dt_iop_module_t *).iop_order`.

Thus, effectively, the cache invalidation seems broken since the cache reading does not follow the same order as the pipe applications. It seems to be a leftover of @edgardoh pipe reordering ability. Or maybe I got it wrong (but anyway, I need `dt_dev_pixelpipe_cache_hash` to work properly).

As a matter of fact, the pixelpipe only uses the function checking for the first module :

https://github.com/darktable-org/darktable/blob/52bc31cacdb266d1f9a9c78f2c409e366faec416/src/develop/pixelpipe_hb.c#L2768

So, if that first module is not the latest of the pipe, it might explain why the preview is not properly refreshed in some cases.

**Comment by aurelienpierre** [comment]
For some reason,
```C
  int position = dt_ioppr_get_iop_order(self->dev->iop_order_list, self->op) - 1;
  uint64_t hash = dt_dev_pixelpipe_cache_hash(piece->pipe->image.id, roi_out, piece->pipe, position);
```
seems to behave as it should (the position in nodes is as expected from the iop order), but I don't understand why (looking at the code).

**Comment by jenshannoschwalm** [comment]
@aurelienpierre shouldn't his be closed as iop_order should be fine now?

**Comment by aurelienpierre** [comment]
This involves iop_order and the pixelpipe cache hash, and I still doubt they work as they should together. Until someone is able to explain me what actually happens here.
