### ISSUE TITLE
Central panel of darkroom stuck

### ISSUE THREAD

**Issue by tvcat** [darktable-org/darktable#2750]
**Describe the bug**
1, The central panel of darkroom stuck in "working..." when dragging or zooming with mouse or apply module. It's not consistent.
2, The cursor will stuck on the screen but still able to click and move around.
3, A message from AMD pop up "Default Radeon WattMan settings have been restored due to an unexpected system failure".
4, The cursor will unstuck after alt-tab to other application. 
5, Module is still clickable and actually apply the effect but the central panel won't update and still stuck.
6, It can't go back to lightroom in this case.
7, Darktable then went unresponsive and I have to force close and there is no crash dialog.
8, If I apply some module after the stuck then the applied module will show up after reopen Darktable.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://imgur.com/G2JBSBz

**Platform (please complete the following information):**
 - Windows 10 Pro x64
 - AMD Radeon HD 7700 (19.6.2)
- this is darktable 2.7.0+1423~ga63dd508e
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Additional context**

**Comment by parafin** [comment]
This sounds like a GPU (OpenCL) driver bug. Disable OpenCL in preferences to avoid this issue (costing you performance). Nothing darktable can do here IMHO.

**Comment by Nilvus** [comment]
@TurboGit or @tvcat  : this could probably be closed.

**Comment by TurboGit** [comment]
Agreed !
