### ISSUE TITLE
Panasonic Lumix DC-G95/DC-G90/DC-G91/DC-G99 camera support

### ISSUE THREAD

**Issue by tuxsoy** [darktable-org/darktable#2753]
Request for supporting the Panasonic Lumix DC-G95. I've uploaded all the crops (1:1, 4:3, 3:2, 16:9) to https://raw.pixls.us/

Let me know if there's anything else I can do to help.

**Comment by sbolten** [comment]
Once supported - will this automatically include the DC-G90 and DC-G91? Or do we have to open a dedicated support request for those?

Stephan

**Comment by LebedevRI** [comment]
Looks like those are aliases, as usual. I'll try not to forget then..
That being said, DC-G90 sample is missing.

**Comment by sbolten** [comment]
I do own a DC-G91. Anything I can do to support? All samples for DC-G95 were submitted by the person starting this thread. Do you need specific samples from the G90 as well?
