### ISSUE TITLE
Issue with changing exposure value from histogram view

### ISSUE THREAD

**Issue by msdm** [darktable-org/darktable#2760]
**Describe the bug**
After creating multiple instances of exposure iop, changing exposure value by mouse roll over histogram view creates some weird artifacts all over the photo.

**To Reproduce**
1. Open a photo in darkroom
2. Enable exposure iop
3. Create a second instance of exposure iop and enable it
4. Select first exposure entry from history stack
5. Try changing exposure value by mouse roll from the histogram view

**Expected behavior**
Changing exposure value in the first (default) instance of exposure iop

**Screenshots**
Before:
![Screenshot from 2019-06-30 17-18-32](https://user-images.githubusercontent.com/8253237/60396795-29600a80-9b5b-11e9-81c0-90de53a57801.png)

After:
![Screenshot from 2019-06-30 17-18-42](https://user-images.githubusercontent.com/8253237/60396812-311faf00-9b5b-11e9-9d7a-3a9c23f36da7.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: git master

**Comment by Nilvus** [comment]
Hi,
Do you have screenshots to show the weird artefacts ? I've just tried 3 times your steps but on image I tested I can't reproduce what you describe (no artefacts on image).

**Comment by msdm** [comment]
> Hi,
> Do you have screenshots to show the weird artefacts ? I've just tried 3 times your steps but on image I tested I can't reproduce what you describe (no artefacts on image).

Thank you for your reply. Actually I don't have access to my laptop right now. I will send the screenshots when I get back home.

**Comment by msdm** [comment]
For reproduction, in step 4, please change first exposure entry instead of deleting the second instance (updated the original post).

**Comment by Nilvus** [comment]
Indeed, I confirm your issue. What I see is slider on exposure module doesn't move, even if I roll on histogram. So it seems to not update the right thing. In waiting this issue is corrected, I suggest to use sliders on exposure modes (that works great with sliders on exposure mode).

**Comment by msdm** [comment]
Thank you for confirmation. As you explained, the exposure slider works flawlessly.
