### ISSUE TITLE
Latest master causes hang on startup

### ISSUE THREAD

**Issue by MartinScharnke** [darktable-org/darktable#2763]
Running darktable 2.7.0~git1504.a4d5069cb (first upgrade in  days or so) today,
darktable continually freezes up irrespective of --disable-opencl
**Possible clue**: output to terminal as below (for 21 distinct images)

There are unassigned iop_order in the history!!!

image: 55685 module: collect version: 1

**Comment by AxelG-DE** [comment]
Which camera's raw files you try to open? 
Which moment it freezes? As you da 21 images, I assume/interprete, the moment, you wanna switch to darkroom?

**Comment by edgardoh** [comment]
It seems that you have a custom module named 'collect' that has not been upgraded to the latest code. Did you upgraded from 2.6 or earlier?

**Comment by MartinScharnke** [comment]
> Which camera's raw files you try to open?
NEF (Nikon D7200)
> Which moment it freezes? As you da 21 images, I assume/interprete, the moment, you wanna switch to darkroom?
Yes - wanting to switch to darkroom brings on the freeze. I can collapse modules in lightroom, even switch to map view and change my collection of images (but all my cached thumbnails seem to have gone). Any attempt to actually bring up images causes freeze.

**Comment by MartinScharnke** [comment]
> It seems that you have a custom module named 'collect' that has not been upgraded to the latest code. Did you upgraded from 2.6 or earlier?

**Comment by MartinScharnke** [comment]
> It seems that you have a custom module named 'collect' that has not been upgraded to the latest code. Did you upgraded from 2.6 or earlier?

No; I have upgrading every week or so to latest 2.7 git master.  I have tried to disable all scripts by renaming my lua folder and renaming my luarc file, but even so, the issue persists. I upgraded once again tonight - now version 2.7.0~git1505.63e2ee346 - but the problem remains.  

I can start with --configdir= [someplace new] thus creating a new database and importing some images; this works fine.  Is my database irretrievably damaged?

**Comment by MartinScharnke** [comment]
Is there a way I can comment out lines in my darktablerc to disable individual modules?  Collect is indeed a module, but a fairly central one - collect images!! However there is a bunch of lua lines that I could possibly try commenting out in sections (if commenting is allowed)

**Comment by AxelG-DE** [comment]
I have a D7100, I'll try, once I'm at home

--confdir might help nailing down

.cache can be broken too....

**Comment by edgardoh** [comment]
What the message say is that collect is an iop module, not the one on lighttable.

Can you share the xmp?

**Comment by AxelG-DE** [comment]
I was on +1504 and I can open:
- Olympus em5 MK2
- D750
- D7100

So all fine

I suggest you try:
- different config-dir and if that still does not work out, 
- please rename ~/.cache/darktable/ 
(indeed dt off by that moment)

If the chache is the one, you can rebuild with `/opt/darktable/bin/darktable-generate-cache` afterwards (takes time, do it over night, depending on database size)

**Comment by MartinScharnke** [comment]
For whatever reason, it seems my database must have become corrupt; database rebuilt - 32000 images imoprted, and their xmps fortunately all present. I'll close this.
