### ISSUE TITLE
[FEATURE] Add lighttable button to read image data (exif)

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#2764]
Currently to reread for example the exif data from an image, you have to delete it and then import it again. We should have a button in the lighttable to select all images and read the data again to update the metadata in the library.

I've added support for calculating the focus distance for Sony A7 and A6xxxx cameras with exiv2 0.27.2. So I need to reread all images to get the focus distance that lensfun can calculate the vignetting correction.

**Comment by sams96** [comment]
I've started looking at implementing this, and I figure I'll need to run the function dt_exif_read from src/common/exif.cc but that needs the full file path but I can't seem to find a way to retrieve the path for the selected images.

**Comment by sams96** [comment]
Perfect, thank you.
