### ISSUE TITLE
Compress history in lighttable breaks data structure

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2774]
**Describe the bug**

After compressing history in lighttable, recording further changes in darkroom to the history is messed up:  Every individual edit change of a value may be recorded to history, e.g., using the scroll wheel on the exposure module's slider may easily add 20 items to the history

**To Reproduce**

Open image in darkroom and create a history that will change under compression, e.g., change the exposure, then the cropping, and then the exposure again.

Back in lighttable, select the same image, choose "history stack/compress hist…".

Open the image in darkroom again.  Go to, say, the "exposure" module, and change the exposure slider by dragging or scrolling.  Every single change will be recorded to the history.  The same effect appears with other modules.

I guess "lighttable/history stack/compress hist…" does not correctly enumerate the image operations in the history stack.

**Expected behavior**

All consecutive changes in the exposure moudule should create only one entry in the history.

**Platform (please complete the following information):**

  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * release-2.7.0-1514-g122cca227

**Comment by s5k6** [comment]
Related to #2420.

**Comment by s5k6** [comment]
One can use the database to look at the history stack.  Use the image ID to find the image.  Say it's 9.  After using "history stack/compress hist…" in lighttable, I observe this:

    $ sqlite3 tmp/dt/config/library.db
    sqlite> .headers on
    sqlite> .mode columns
    sqlite> select num, module, operation, enabled from history where imgid == 9;
    num         module      operation   enabled
    ----------  ----------  ----------  ----------
    0           2           flip        1
    1           6           basecurve   1
    4           5           clipping    1
    5           5           exposure    1

Note that `num` does not contain 2 and 3.  My guess is that
lighttable's compression does not reenumerate the itms properly.
Darkroom;s compression leaves this column densely populated.

**Comment by jenshannoschwalm** [comment]
Fixed by #2949

**Comment by jenshannoschwalm** [comment]
@Turbogit Please close as fixed.

**Comment by TurboGit** [comment]
Indeed, closing.
