### ISSUE TITLE
Darkroom's compress history does not minimize stack

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2775]
**Describe the bug**

Using "historu/compress history stack" in darkroom does not “create a minimal history stack which produces the same image” as the tooltip promises.  Instead, "off" modules remain in the stack.  

**To Reproduce**

Open an image in darkroom.  Change its exposure, then switch off the exposure module.  Change its tone curve, then switch off the tone curve module.  Select "history/compress history stack".  The modules "exposure (off)" and "tone curve (off)" remain on the stack.

**Expected behavior**

A “minimal history stack which produces the same image” must not contain modules which do not contribute to the image.

**Additional context**

Using "lighttable/history stack/compress hist…" will remove disabled modules, but is otherwise [buggy](https://github.com/darktable-org/darktable/issues/2774).

I have [suggested a solution here](https://www.mail-archive.com/search?l=darktable-dev@lists.darktable.org&q=subject:%22%5C%5Bdarktable%5C-dev%5C%5D+implementation+question%5C%3A+remove+all+unused+modules%22&o=newest).

**Comment by TurboGit** [comment]
That's the expected behavior. The "off" module still retains the last edit for the module and can then be activated back.
