### ISSUE TITLE
LUT cube files location causes Darktable to throw exceptiom

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2779]
**LUT Location  causes Darktable to throw exception**

**To Reproduce**
Pointed to a folder where  where LUT cube file were present.
Trying to use them did not allow me to select a LUT immediately after setting location.
I figured I should restart.
Opens into into darktables lightable view, double click image. I get a pop up dialog with a text file location where exception gets written.
Application shuts down.
This happens everytime making darktyable unusable.
Open darktable and try go to setting and change the LUT location to some folder.
This new folder setting never gets saved and it keeps throwing an exception an writing file.

**Expected behavior**
If LUT files have an issue, allow the user to fix the error.

The following files were generated after multiple attempts to open darktable. Other than a fresh install I don't see a way forward.

[darktable_bt_RARS4Z.txt](https://github.com/darktable-org/darktable/files/3367829/darktable_bt_RARS4Z.txt)
[darktable_bt_TWGJ4Z.txt](https://github.com/darktable-org/darktable/files/3367830/darktable_bt_TWGJ4Z.txt)
[darktable_bt_VH814Z.txt](https://github.com/darktable-org/darktable/files/3367831/darktable_bt_VH814Z.txt)
[darktable_bt_LZ4K4Z.txt](https://github.com/darktable-org/darktable/files/3367832/darktable_bt_LZ4K4Z.txt)
[darktable_bt_OMMP4Z.txt](https://github.com/darktable-org/darktable/files/3367833/darktable_bt_OMMP4Z.txt)

**Platform (please complete the following information):**
 - OS: Windows 10.0.18362
 - Version  2.7.0+1513~g4a3cb1df5 [build on win 10 by myself]

**Comment by phweyland** [comment]
Hi @chhil 

```
   968:       char *ext = g_ascii_strdown(g_strdup(g_strrstr(filepath,".")), -1);
>  969:       if (ext[0])
```
This line is buggy and I'll try to fix it asap.
Your lut file seems not to have any extension.


> This new folder setting never gets saved and it keeps throwing an exception an writing file.

Whenever you change the folder you must exit darktable to make it saved.

**Comment by phweyland** [comment]
A workaround is to remove all files without extension from your folder.

**Comment by chhil** [comment]
The filenames had a .cube extension. I simply pointed it to the luminar LUT files that came with the Luminar software.

The directory file listing of the folder lutfiles is as follows. 



C:\Program Files\Skylum\Luminar 3\Data\LutFiles\1960.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\1990.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Beijing.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Candlelight.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Color Punch Cold.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Color Punch Hot.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Genius.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Grace.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Involve.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Kodack chrome  3.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-2-Strip-Process.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Aged-K-14.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Blade-Green.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-BW-Max.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Chrono-Print-Teal_and_Orange.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Chrono-Steel.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Cine-Print-Teal_and_Orange.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-D-Max-Teal_and_Orange.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-D-Min-Teal_and_Orange.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-K-Chrome.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-PRO-Blue.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-PRO-Brown.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-PRO-Crisp-Teal_and_Orange.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Teal-Duo-Tone.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Lutify.me-Warm_and_Cold.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Manhattan.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Red Trace.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Sepia.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Smokey.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Tritone.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Ushuaia.cube
C:\Program Files\Skylum\Luminar 3\Data\LutFiles\Wooden.cube


When I moved it to a path with no spaces it worked but for some reason a previously edited file with a lut had the lut entry in the history in the db and going to the image crashed darktable. I ended up deleting the db's and let darktable create new ones.

Thank you for looking into it.

**Comment by phweyland** [comment]
I've fixed the exception.

However I haven't been able to reproduce any issue related to space inside the path of the file. At least on my system it works fine:

![image](https://user-images.githubusercontent.com/23012047/61381454-77764d00-a881-11e9-9e7e-7c13fa4f209e.png)

**Comment by chhil** [comment]
Spaces was speculation as I dont know what those methods do.  Did you notice that files had a "." in their name ?
Will it pass the test?

**Comment by phweyland** [comment]
> Did you notice that files had a "." in their name ?

Yes, I did. But I remembered that folders have usually no "." inside. I had to fix in the PR #2534 already.

**Comment by chhil** [comment]
Thank you.

**Comment by phweyland** [comment]
@chhil, do you have any pending point about this issue ?
If not, you may close it. :)
