### ISSUE TITLE
Compress history in lighttable does not retain disabled modules

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#2780]
**Describe the bug**

When a module is disabled, compressing its history stack from lighttable will remove that module from the stack.

**To Reproduce**

Open image in darkroom.  Change exposure.  Then disable the "exposure" module by clicking on its ⏻ symbol.  The history stack will contain "exposure (off)" as topmost entry.  Go to lightroom.  Make sure the same image is selected.  Choose "history stack/compress hist...".  Open the same image in darkroom again.  The exposure module has vanished from the history stack.

If you cannot reproduce this, it may be an effect of #2774.  Make sure you have a consistent history stack to start with.

**Expected behavior**

According to [this](https://github.com/darktable-org/darktable/issues/2775#issuecomment-509542189), compressing history should retain disabled modules.

**Platform (please complete the following information):**
  * current ArchLinux
  * no desktop environment (plain X11 and FVWM)
  * $ git describe: release-2.7.0-1514-g122cca227

**Comment by TurboGit** [comment]
I can reproduce indeed.

**Comment by jenshannoschwalm** [comment]
Hi, i can't look into this myself for the next two weeks but i think this code might be at least a major part of the underlying problem.
In src/common/history.c we find
> void dt_history_compress_on_image(int32_t imgid)
> {
>  // make sure the right history is in there:
>  dt_dev_write_history(darktable.develop);
>
>  // compress history and remove disabled modules - adapted from libs/history.c
>  sqlite3_stmt *stmt_local;
>  DT_DEBUG_SQLITE3_PREPARE_V2(dt_database_get(darktable.db),
>                              "DELETE FROM main.history WHERE imgid = ?1 AND num "
>                              "NOT IN (SELECT MAX(num) FROM main.history WHERE "
>                              "imgid = ?1 AND enabled = 1 GROUP BY operation, "
>                              "multi_priority)",
>                              -1, &stmt_local, NULL);

@TurboGit : The **enabled = 1** seems to be wrong because dis-abled modules in the history are simply not taken care of.  Or do i oversee something?
BTW, compare with similar code in src/libs/history.c `static void _lib_history_compress_clicked_callback`
