### ISSUE TITLE
darktable crashes on start up on macOS 10.14

### ISSUE THREAD

**Issue by IanL01** [darktable-org/darktable#2781]
**Describe the bug**
darktable crashes just when it starts to display its first window. The screen starts to draw the dark frame then crashes. 

Have rebooted the machine, Have uninstalled and reinstalled the app. The problem happens every time I try and start the app

 - OS: macOS  Mojave
 - Version 10.14.5

[darktable-bin_2019-07-11-092407_Ian-iMac.txt](https://github.com/darktable-org/darktable/files/3379827/darktable-bin_2019-07-11-092407_Ian-iMac.txt)

**Comment by parafin** [comment]
Try removing all caches and configuration also:
```
rm -Rf ~/.config/darktable ~/.cache/darktable
```

**Comment by IanL01** [comment]
Thank you that has resolved the issue.
