### ISSUE TITLE
Unassigned iop_order in the history when upgrading from 2.6 to 2.7

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#2790]
**Describe the bug**
When upgrading a 2.6 database to current 2.7 I get these warning.
I've observed that if I edit a faulty image and compress the history stack the image disappears from this list, but another comes, and the size of this list never decreases ...

**Screenshots**

![image](https://user-images.githubusercontent.com/23012047/61380161-439a2800-a87f-11e9-8de2-fe5d4a87d062.png)

**Platform (please complete the following information):**
 - OS: windows 10

**Comment by edgardoh** [comment]
This sounds familiar, this error says that you have a custom iop module in the history called collect. If you have a backup can you check if that is the case in 2.6?

**Comment by phweyland** [comment]
> If you have a backup can you check if that is the case in 2.6?

I did try with 2.6. I don't get any of these messages.

**Comment by edgardoh** [comment]
What I mean is, in the 2.6 database, check if the history table has a operation='collect'

**Comment by phweyland** [comment]
Few images have this operation (out of 40.000):

![image](https://user-images.githubusercontent.com/23012047/61397765-f9c23980-a8a0-11e9-8441-9f495d379e32.png)

**Comment by edgardoh** [comment]
That's what the error says, you have a non-existing iop module. No idea where that comes from, but is strange that two people has the same issue, unless you are sharing edits or a broken style.

**Comment by phweyland** [comment]
Collect is a lib module. Maybe at some point there was on on this...

What if I delete the collect operation in the database ?

**Comment by edgardoh** [comment]
> Collect is a lib module. Maybe at some point there was on on this...
>
History should have only iop modules, no idea how this could happen.

> What if I delete the collect operation in the database ?
>
You will left the history in an inconsistent state. I think that the safer
way is to go to darkroom and compress the history, as you did for the other
image.

**Comment by phweyland** [comment]
> I think that the safer way is to go to darkroom and compress the history, as you did for the other image.

OK !

**Comment by phweyland** [comment]
additional info: only jpg, but not all, are concerned. 
Could have relationship with lightroom import ?
If I remember well lightroom.c only treats raw files. That would mean that some lightroom xmp code in jpg file could have produce this.

**Comment by phweyland** [comment]
I've removed all. The behaviour is quite strange. If I compress the history of one image in a folder, it disappears of the list but the other images of the folder appears ..
To avoid this I've copied the history of a clean image and pasted it on the images of the folder.
And this for a lot of folders containing jpg files generated by Lightroom.
Right, I've cleaned it up. But ... reopening dt make some images appears again in the faulty list.
I've checked that my jpg files are not updated with that correction. But somehow the collect operation appears again.

**Comment by edgardoh** [comment]
The jpg have an xmp generated by Lightroom?
Can you duplicate it? i.e. remove it from dt, re-import it, the collect is in the history again.
Does this happens with raw files?

**Comment by phweyland** [comment]
I've copied a jpg image which is shown with the defect and imported the copy with dt 2.7.
I got this in db:
![image](https://user-images.githubusercontent.com/23012047/63051772-38550f00-beb4-11e9-8f5f-38b2e02775ad.png)

> Does this happens with raw files?

Very few. When I tried to clean up them (process above) I've seen some, less than 10, raw files, out of nearly a thousand of jpg.

**Comment by phweyland** [comment]
I have just import one hundred images.
I get this for 4 images:

```
[dev_read_history] the module `collect' requested by image `20190831_EstradaReal_016.NEF' is not installed on this computer!
[dev_read_history] the module `collect' requested by image `20190831_EstradaReal_014.NEF' is not installed on this computer!
[dev_read_history] the module `collect' requested by image `20190831_EstradaReal_012.NEF' is not installed on this computer!
[dev_read_history] the module `collect' requested by image `20190831_EstradaReal_013.NEF' is not installed on this computer!
```

If I import the same images into a fresh database, I have no message. 

To try track the issue (putting traces...), where I should start from your standpoint ?

**Comment by phweyland** [comment]
the collect module seems to come from data.presets (develop.c line 1260)...
![image](https://user-images.githubusercontent.com/23012047/65166726-8aec9280-da41-11e9-83c3-2e113fb92eb9.png)

**Comment by phweyland** [comment]
If I remember well, these presets were set up in collect module ...

**Comment by phweyland** [comment]
Confirmed. If I create a preset in collect module it does appear in data.presets. Then it is candidate to be applied by develop.c ...
