### ISSUE TITLE
Lens correction for Canon PowerShot G9 X Mark II

### ISSUE THREAD

**Issue by catcombo** [darktable-org/darktable#2795]
There is not lens correction in darktable for Canon PowerShot G9 X Mark II. I tried to use lens correction for G7 or similar Canon models, but they didn't work. But I find out that [gThumb](https://github.com/GNOME/gthumb) has module to open RAW images and it has lens correction for my camera. I can even export correct version to TIFF. Is it possible to get lens correction information for Canon PowerShot G9 X Mark II from gThumb and add it for darktable?

**Comment by LebedevRI** [comment]
Lens correction is lensfun issue.

**Comment by catcombo** [comment]
Got it. Thanks.

**Comment by catcombo** [comment]
I found out that lens correction data is included in the RAW file. When I import a RAW photo in Lightroom it applies lens correction automatically with tip "Built-in Lens Profile applied". When I click on this tip I got detailed information "This raw file contains a built-in lens profile for correcting distortion and chromatic aberration. The profile has already been applied automatically to this image". Is it possible to extract lens profile from RAW image for my camera in DarkTable too?

**Comment by Entropy512** [comment]
Manufacturer lens profiles are proprietary and (usually) not documented.

Sony's correction profile data has been reverse engineered ( http://stannum.co.il/blog/0PwljB ) - but this model is not compatible with the lensfun distortion correction module.

In theory you could implement some sort of curve-fitting to convert a "known" non-lensfun model to a lensfun model, but in practice it's unlikely - and I'm unaware of any documentation of Canon's distortion correction parameter format.  At least for the Sony stuff, most lenses I use already have a lensfun profile which demotivates me to ever try and implement the Sony->lensfun conversion curve-fit.  (At some point I may go the other way for a hardware project that I've been slowly poking at for the past 3-4 years, but that's a LONG way off...)

If you want lens distortion correction data for your camera, the best option is to either wait for it to be added to lensfun, or head over to lensfun's site where there is a tutorial on how to generate profiles for your camera/lens combination.

**Comment by catcombo** [comment]
@Entropy512 Thank you for the explanations. Seems I'll have to use Lightroom for a couple of years more.

**Comment by Entropy512** [comment]
I know you closed this, however there are two possibilities that will be less than a few years away:
1)  Lensfun gives instructions for profiling your camera and generating a distortion model yourself
2)  Apparently the development alpha/beta release of Lensfun did add Adobe Camera Model (ACM) support.  So if you can find an LCP file describing your camera, you MIGHT be able to use it with recent darktable master branch builds (which use the new version of lensfun).  Option 1 is still better in the long term.
