### ISSUE TITLE
Canon EOS 4000D

### ISSUE THREAD

**Issue by Gabrock94** [darktable-org/darktable#2803]
Hello people,
recently received a Canon EOS 4000D, but it's not currently working.
I've been able to submit a RAW file to raw.pixls.us, but can't understand how to obtain an mRAW or sRAW. Any help! Or are those format not available with this camera?
How should I proceed in order to be helpful?

**Comment by LebedevRI** [comment]
That level of Canon cameras doesn't have mRAW/sRAW

**Comment by LebedevRI** [comment]
Actually, that camera is supported since https://github.com/darktable-org/rawspeed/commit/615af31a22f0212bb7b646f246a253a513ba9ff6 / 4cefd24c3a4240de8c96ff20ffd74c35e5c5a287.
So it should certainly be working with 2.6.x release.
You did not indicate which release you are using.

**Comment by Gabrock94** [comment]
You're right! my fault, tought mint repo had the latest version! Thanks for your help!
