### ISSUE TITLE
Bounding box overlay in preview not removed after cycling back to Fit to Screen using middle button

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#2806]
In darkroom, when cycling through zoom modes 100%/200%/fit to screen, using the middle mouse button, the preview window shows a navigation bounding box with the correct zoomed size. However, this box should disappear when we get back to fit-to-screen. But it doesn't until something else triggers a refresh of the preview window.

1. open image in darkroom
2. middle-click on main image
3. zoom switches to 100%; preview window top left still shows full image, but with bounding box for zoomed area
4. middle-click again
5. zoom now 200%, bounding box shrinks further
6. middle-click again
7. zoom now fit-to-screen; full image visible in center view
8. preview still shows smallest bounding box corresponding to 200% zoom
9. click-drag in center view
10. preview now gets updated and bounding box disappears.

Expected behavior:
Preview window updates as soon as middle mouse button clicked and bounding box immediately disappears when zoom is switched to fit-to-screen.

**Comment by dterrahe** [comment]
I've tried to find why the behaviour is different for different zoom levels, but I'm not getting very far. The switching happens in darkroom.c :: button_pressed, but there is nothing specific for each zoom level:

   if(zoom == DT_ZOOM_1)
    {
      if(!closeup)
        closeup = 1;
      else
      {
        zoom = DT_ZOOM_FIT;
        zoom_x = zoom_y = 0.0f;
        closeup = 0;
      }
    }
    else
      zoom = DT_ZOOM_1;

The dark overlay zoom box on the preview gets drawn in _lib_navigation_draw_callback but I don't know where it gets triggered. It seems to be multi-threaded and doesn't get fired for any zoom level under the debugger for me...

**Comment by edgardoh** [comment]
You have to add:

  dt_control_queue_redraw_center();
  dt_control_navigation_redraw();

after the dt_dev_invalidate(), here:
https://github.com/darktable-org/darktable/blob/master/src/views/darkroom.c#L2849

like is done on the scrollbar_changed()

**Comment by dterrahe** [comment]
Thanks @edgardoh, that indeed worked. And it was also needed when zoom is changed using shortcut keys.
