### ISSUE TITLE
OSX: compiling kernels for opencl for packaged darktable.app needs several attempts

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#2810]
**Describe the bug**
on the first start of packaged darktable.app it needs plenty of attempts until all kernels are compiled. (last try >40 attempts)

error example:
```
5.144612 [opencl_load_program] could not load cached binary program, trying to compile source
5.144626 [opencl_load_program] successfully loaded program from `/Applications/darktable.app/Contents/Resources/share/darktable/kernels/highpass.cl'
5.166519 [opencl_build_program] could not build program: -11
5.166536 [opencl_build_program] BUILD STATUS: -2
5.166550 BUILD LOG:
5.166551 <program source>:19:10: fatal error: 'common.h' file not found
#include "common.h"
         ^
5.166555 [opencl_init] failed to compile program `highpass.cl'!
5.166572 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
5.166574 [opencl_init] initial status of opencl enabled flag is OFF.

```
it needs several attempts until the compiler realizes, that common.h is really existing ...

**To Reproduce**
build darktable / make osx package / install darktable.app from package like described in BUILD.txt

1. delete ~/.cache/darktable/cached_kernels*
2. start /Applications/darktable.app/Contents/MacOS/darktable -d opencl from terminal
3. see error, but darktable starts without opencl
4. be patient and restart several times until darktable compiled all kernels and enables opencl
as long as darktable further is started from darktable.app it keeps opencl enabled

**Expected behavior**
all kernels compiles on the first attempt. 
if darktable ist started from /usr/local/bin via GSETTINGS_SCHEMA_DIR=/opt/local/share/glib-2.0/schemas/ XDG_DATA_DIRS=/opt/local/share darktable all kernels compile swithout problems

**Screenshots**

**Platform (please complete the following information):**
 - OS: OSX
darktable 2.7.0+1613~g055479ffa
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by parafin** [comment]
This is a known issue and looks like a bug in macOS'es OpenCL framework. No idea how to fix or even debug it.

**Comment by MStraeten** [comment]
workaround:
after installing a new build let bash do the annoying stuff:
```
#!/bin/bash
while true; do 
 str=`/Applications/darktable.app/Contents/MacOS/darktable-cltest | grep "OpenCL successfully initialized."` 
 if [[ $str =~ "OpenCL" ]]; then 
  echo "openCL enabled"
  break 
 fi 
done

```

**Comment by MStraeten** [comment]
script needs to be modified to ensure all OpenCL kernels are built since darktable now enables OpenCL if all kernels  for at least one GPU are built.  

```
#!/bin/bash
while true; do 
 str=`/Applications/darktable.app/Contents/MacOS/darktable-cltest | grep "failed to compile program"` 
 if [[ ! $str =~ "failed to compile program" ]]; then 
  echo "openCL enabled"
  break 
 fi 
done 
```

**Comment by MStraeten** [comment]
Its not fixed yet

**Comment by MStraeten** [comment]
not fixed, makes sense to keep it just to document the workaround for it

**Comment by johnny-bit** [comment]
I think Adding that script to tools just for mac would be beneficial. Just add one special steps for mac: "run this script to have working OpenCL if your mac is capable of OpenCL" and that would get rid of some opencl problems on mac :)

**Comment by rds13** [comment]
I cannot reproduce that error on macOS Monterey version 12.6.3 with darktable 4.2.1
```
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```

**Comment by MStraeten** [comment]
no longer reproduced for a long time - so closing this here
