### ISSUE TITLE
New tag tree : expand/collapse tree not possible by clicking on the left arrow

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#2817]
**Describe the bug**
@phweyland : great new tag tree but an annoying bug on my system. I can't keep the tree expanded, if I click on a left arrow, the tree collapse the second I stop the click on it. It's only when clicking on the left arrow that I have the behavior. If I click on the tag just after or on the column on the left of the arrow, it's ok

**To Reproduce**
1. Go to 'tags module on right'
2. Click on 'the new toggle tree/list view' to be on tree view
3. Click on an arrow
4. release the click and see the tree closing himself

**Expected behavior**
Having the possibility to expand normally the tree on normal behavior.

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version last master

**Comment by Nilvus** [comment]
@phweyland : if you have read the mail before this, forget my first "bug" with the quite strange tag. It's maybe a tag from an image I have previously download from french darktable forum and delete the image since without seeing this tag. Just think about that after posting this issue.

Anyway, a bug remains.

**Comment by phweyland** [comment]
> I can't keep the tree expanded, if I click on a left arrow, the tree collapse
The expansion/collapsing works well for me (my OS is Windows).
Wherever I left-click on the line (before the arrow, on it or after it) the line toggles its expansion (as it is expected).

What do you mean by "I click on a left arrow" ?
The only arrows I have are down and right.

Double-click attaches the tag (if exists) and, yes, the tree collapses (this may be a wrong behaviour, I'll check this). Have configured somewhere double-click = simple-click ?

**Comment by Nilvus** [comment]
> > I can't keep the tree expanded, if I click on a left arrow, the tree collapse
> > The expansion/collapsing works well for me (my OS is Windows).
> > Wherever I left-click on the line (before the arrow, on it or after it) the line toggles its expansion (as it is expected).
> 
> What do you mean by "I click on a left arrow" ?
> The only arrows I have are down and right.
> 
> Double-click attaches the tag (if exists) and, yes, the tree collapses (this may be a wrong behaviour, I'll check this). Have configured somewhere double-click = simple-click ?

Nothing related to double click here

I talk about that (just on the left of a parent tag (red circle below)). The behavior is not the same as clicking (on same line) on the column on the left and on the tag text.

![Capture-20190726205253-297x258](https://user-images.githubusercontent.com/45535283/61974899-f852e880-afe7-11e9-9f1d-887dd4321264.png)

**Comment by phweyland** [comment]
> Just click precisely on this arrow, and a pixel or two outside on the left or the right and you will see that the behavior is not the same.

I don't see any different behaviour, all the line along, on the arrow or not.
Do you have strange message on the console ?

**Comment by Nilvus** [comment]
> > Just click precisely on this arrow, and a pixel or two outside on the left or the right and you will see that the behavior is not the same.
> 
> I don't see any different behaviour, all the line along, on the arrow or not.
> Do you have any strange message on the console ?

I'm quite surprise that you don't have it, as it systematic on my system and only on that module. Nothing appear on console when clicking on the arrow or on another part of the line.

To be more precise (I hope) : the state revert back as soon as I release the mouse click when clicking on the arrow. That's works on both ways. For example, if the tree is developed so children visible, clicking on the arrow reduce the tree (ok) but as soon I release the mouse click, the tree remains developed. Making a video would be better but I never done that and not sure Github permit to post videos.

``

**Comment by TurboGit** [comment]
This is quite strange as I cannot reproduce either! What DE are you using? GNOME / KDE / others?

**Comment by Nilvus** [comment]
> This is quite strange as I cannot reproduce either! What DE are you using? GNOME / KDE / others?

Euh, indeed, quite strange. I use Gnome 3.32.2 with Gtk 3.24.8

**Comment by TurboGit** [comment]
On my side GNOME 3.30 and Gtk 3.24.10. So pretty close to you.

**Comment by Nilvus** [comment]
> On my side GNOME 3.30 and Gtk 3.24.10. So pretty close to you.

Indeed... but not the same behavior. And what's it's more strange is I have this behavior only on this new tag tree view, nowhere else on darktable. Something between a code line and Gtk 3.24.8 (as you have 3.24.10) ?

**Comment by phweyland** [comment]
@Nilvus , here is a proposal to try to find the issue.
I can make a version with console messages and post it on github. If you take it and build it we could retrieve the messages and check if we can find the origin of the issue... What do you think ?

**Comment by Nilvus** [comment]
> @Nilvus , here is a proposal to try to find the issue.
> I can make a version with console messages and post it on github. If you take it and build it we could retrieve the messages and check if we can find the origin of the issue... What do you think ?

Ok, we could try that. Thanks for helping.

**Comment by phweyland** [comment]
@Nilvus please find the version with printf here : https://github.com/phweyland/darktable/tree/tag-printf.
I have tried to put them where meaningful... feel free to add  other ones as necessary.
Thanks

**Comment by Nilvus** [comment]
@phweyland : just tested. I have these lines displayed when I'm clicking on the arrow (same lines when clicking on other parts of the line, other parts working great) :

```
view_onButtonPressed
view_onButtonPressed - left-click
view_onButtonPressed - left-click - expand
```
I don't know anything in C and GTK code but I just compare with styles.c file (to see how tag tree seems to be coded). I just see a difference on a specific line (line 1245 on tagging.c file on your printf commit : https://github.com/phweyland/darktable/commit/00d09d6eb3889c7a69c2b825c2fabad04a974144).

On that line, the same on on styles.c has a "!" before gtk_tree_model_iter_has_child. So I add it on the tagging.c file and recompile on your branch. Just adding the "!" solve this issue. Of course, please verify that this the correct way to do. So the line 1245 become :
`
 if(**!**gtk_tree_model_iter_has_child(model, &iter))`

The only thing with that if the arrow become the only way to collapse/expand the tree and not more the entire line as before (but that solve the issue). I have check back on styles tree (hierarchical view I use) and that just the arrow that allow to collapse/expand the tree. Same way on filter collection if for example I use tag filter to have a tree.

**Comment by phweyland** [comment]
> if(!gtk_tree_model_iter_has_child(model, &iter))

If I do that on my system, I cannot expand the tree any more.
In fact doing this is not logical and that breaks my code.

It seems that the arrow is self working on your system, and my code somehow is in conflict with that.
If I understand properly I should remove this left-click code and find why the arrows do not work alone on my system.

**Comment by Nilvus** [comment]
> > if(!gtk_tree_model_iter_has_child(model, &iter))
> 
> If I do that on my system, I cannot expand the tree any more.
> In fact doing this is not logical and that breaks my code.
> 
> It seems that the arrow is self working on your system, and my code somehow is in conflict with that.
> If I understand properly I should remove this left-click code and find why the arrows do not work alone on my system.

On my system, that just allow your code (and so the tag tree) to work exactly the same way as other trees on darktable. If you see how other trees works, you will see that they collapse/expand only when clicking on the arrow, not on the title. Quite strange you don't have the same behavior.

**Comment by phweyland** [comment]
I've found the issue. I'll the fix to the current PR. Thanks for the help !

**Comment by Nilvus** [comment]
> I've found the issue. I'll the fix to the current PR. Thanks for the help !

And thanks a lot to you for following this issue and all your great work on improving darktable. I confirm that the issue is solved with your last PR.
