### ISSUE TITLE
Improve the integration of Darktable Styles

### ISSUE THREAD

**Issue by somniumAeternam** [darktable-org/darktable#2822]
**Is your feature request related to a problem? Please describe.**
Darktable Styles are a very handy tool to increase the productivity. But the way the styles are integrated in the UI is in my opinion not optimal. There is no possibility to sort or group styles, or to declare favorites. Every time I have to scroll through the whole list. This is time consuming.

**Describe the solution you'd like**
The button for the styles seem to be out of place from the other editing tools. I propose the integrate the Styles as a module on the right side with the other editing tools. In the styles module you can add the possibility to add groups and sort the styles, maybe with a drop-down list.

**Describe alternatives you've considered**
There are no workarounds for a better usability.

**Comment by Nilvus** [comment]
On new features of darktable 2.6.1, you could read that :

- add hierarchical view for styles (separated with |)

So grouping is possible and easy since that release. You just have to rename your styles by adding before the name style the tree you want and separating each children with a pipe.

And Styles module already exists in the right panel on Lighttable. It's doesn't have to be on right panel on darkroom (if it's what you mean) as darkroom is to edit the image, not the styles or a set of images (lighttable function for that).

**Comment by somniumAeternam** [comment]
Thank you very much. This is really helpful.

**Comment by chhil** [comment]
Will this work in the darkroom styles popup ?
I use the denoise style from the darkroom view all the time or my  custom style for luminosity masks, scrolling through them is such a pain.

![image](https://user-images.githubusercontent.com/1119439/64194468-d6793b00-ce9c-11e9-997d-0cb50ac69857.png)

**Comment by chhil** [comment]
> Will this work in the darkroom styles popup ?
> I use the denoise style from the darkroom view all the time or my custom style for luminosity masks, scrolling through them is such a pain.
> 
> ![image](https://user-images.githubusercontent.com/1119439/64194468-d6793b00-ce9c-11e9-997d-0cb50ac69857.png)

Please ignore  my query.
If the name in the style is piped it shows up hierarchial in lightable and darkroom.

<?xml version="1.0" encoding="ISO-8859-1"?>
<darktable_style version="1.0">
    <info>
        <name>A|B|Fashion</name>
        <description></description>
    </info> 
Darkroom view after piped style name import.
![image](https://user-images.githubusercontent.com/1119439/64194998-070da480-ce9e-11e9-9cdf-c20785f3a6a7.png)

Lightable view after piped style name import.
![image](https://user-images.githubusercontent.com/1119439/64195039-1b51a180-ce9e-11e9-8c90-4a548602a4e4.png)
