### ISSUE TITLE
Some film scanner's DNGs are not supported

### ISSUE THREAD

**Issue by kubrickfr** [darktable-org/darktable#2823]
**Describe the bug**
Follow up to #2732 
Trying to open files like this on https://drive.google.com/open?id=11n68m0ZLY23pkKBGof2_l-AT6f95sTJ4 fails on darktable but works in other software (such as rawtherapee)
On this scanner, it only happens with high resolution scans, lower resolutions work just fine.

**To Reproduce**
Open the linked file

**Expected behavior**
The unprocessed file should appear

**Comment by LebedevRI** [comment]
That file looks severely broken to me.
* It has TIFF entries with type = 15. What is that? It's not invalid per-se but i don't see it in TIFF spec.
* It has overlapping TIFF IFD's. That's an immediate sign that something is really wrong.
  Here RawSpeed stopped trying to parse it as TIFF.
  Either the file is corrupt, or it was written by broken software.
