### ISSUE TITLE
Better dialog to insert presets

### ISSUE THREAD

**Issue by mkentaro1** [darktable-org/darktable#2825]
Working with darktable, it's quite annoying that the dialog to insert the preset doesn't have any label specifing what the textfield has to contain.

They should have a simple label with "Name" and "Description" in order to let the user know what is inserting. I'm a newbie with darktable and I find that should be a minor change that can improve the user experience.

Thanks in advance

**Comment by sams96** [comment]
There are tool tips for the dialog boxes, but I've submitted a PR to add placeholder text as well.
