### ISSUE TITLE
Tags - missing features - synonyms

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#2826]
I've added some features to hierarchical tags, but some are still missing, like:
* add synonyms to a tag
* flag the tag for export or not (private ?)
* category (or first level node)  to help to organize tags but which are not a keyword in itself

Before starting on that topic I would like to have:
* your suggestions about the missing features
* some information about the current design

About the current design:
* why the data.db ? why the tags table is not in library.db ? 
* in the table tags (data.db), the fields `icon, description, flags` seem not to be used. Is there any plan to use them ? Can we remove them ? Are they available for new features ?

**Comment by Haribo-66** [comment]
I think it would be very smart to see and know all the tags and tag
counts within a given image collection. What do you think ?

**Comment by phweyland** [comment]
If you have open a collection and select all images (Ctrl-A) the first windows give the list of tags which are used. 

![image](https://user-images.githubusercontent.com/23012047/62540229-840d1600-b82d-11e9-8697-08d5c16c99bd.png)

Does that answer a part of your question ?

About the count. Which one do you think about ? How many time the tag is used in the selection ? How may time the tag is used in the data base ?

**Comment by Haribo-66** [comment]
How many times the tag is used in the selection would be very helpful.

Especially to work on missing or forgotten tags and to understand that there is a difference between the selection and the tag counters.

If I add the "tags"  to the collection module (left panel) I would want to see all used tags and all the counters of the selection but this does not work anymore. The collection disapears and I only see one individual tag.

**Comment by phweyland** [comment]
> If I add the "tags" to the collection module (left panel) I would want to see all used tags and all the counters of the selection but this does not work anymore. The collection disapears and I only see one individual tag.

I don't understand this. Could make a snapshot of this ?

**Comment by Haribo-66** [comment]
I open a filmrole and I add 3 more empty filters e.g. date, tag and colour label.

Going to date directly works fine.

![capture_08062019_154952](https://user-images.githubusercontent.com/53818783/62545699-7de55c80-b862-11e9-9550-fb7855f0dcb6.jpg)

I could select now an individual date but I see all the dates (the full tree) in the filmrole together with all the counts for each date within the tree of dates.

Going to tag first of all deletes my collection and I would need to increase the list and keep all the tags and counts.

![capture_08062019_155111](https://user-images.githubusercontent.com/53818783/62545917-de749980-b862-11e9-8aa6-4740c48ac9cd.jpg)

**Comment by phweyland** [comment]
Understood, this is a collection module matter.
Not sure but that may be "dates" which doesn't behave like the other collections... 
However I would suggest you open an issue on this topic and expose what you would like (preferably something which would apply to other collections).

**Comment by Haribo-66** [comment]
... ok I will go this way then, but the right panel Tagging windows (your earlier snapshot) should show all the counts of all the selected images anyway.

**Comment by phweyland** [comment]
> the right panel Tagging windows (your earlier snapshot) should show all the counts of all the selected images anyway

I've noted that. On the way.

**Comment by Haribo-66** [comment]
Another tag related feature request ...

I want to use tags to create tag based (related) watermarks to finally add this tag information via watermarks on top of a slideshow?

**Comment by phweyland** [comment]
> create tag based (related) watermarks to finally add this tag information via watermarks on top of a slideshow

This linked to the tagging down stream. 
Watermarks is already able to integrate metadata like Xmp.dc.creator, ...
There may be a not too difficult to create automatically the metadata Xmp.dc.subject (which is the list of tags of the image)...

**Comment by phweyland** [comment]
> but the right panel Tagging windows (your earlier snapshot) should show all the counts of all the selected images anyway.

Multiple images selected:
![image](https://user-images.githubusercontent.com/23012047/62873522-f0888900-bcf5-11e9-98f3-cb72c2865819.png)

Single image;
![image](https://user-images.githubusercontent.com/23012047/62873637-29286280-bcf6-11e9-9670-d81b57d9ee2f.png)

**Comment by phweyland** [comment]
done in PR #2850
