### ISSUE TITLE
Only Write Sidecar On Edit?

### ISSUE THREAD

**Issue by metal450** [darktable-org/darktable#2832]
I'm exploring options to move away from LR.  In DarkTable, the moment images are added to the catalog, it seems to immediately generate sidecar files for each & every photo.  Would it be possible to introduce an option so that DarkTable would *only* generate a separate xmp file when a photo has actually been edited in some way?

This is preferable for a number of reasons:
* It follows how other software behaves (i.e. both LR and RawTherapee)
* It makes it much easier to locate edited files from outside the software (i.e. you can just use a file explorer & instantly notice which files you've worked on / developed)
* It results in considerably less clutter.  Scrolling through double-length directories makes it more cumbersome to locate a specific file when using a non-xmp-aware browser.
* It results in faster backups.  I often work remotely, & my photo collection is backed up online - doubling i.e. 20,000 photos to 40,000 files makes a notiecable difference in backup time from the much larger directory listings.
* When working on jpgs, DarkTable doesn't embed xmp back in the source images ("non-destructive"), but if desired, 3rd party tools can be used to accomplish that behavior (_exiftool -tagsfromfile %d%f.xmp -xmp:all -ext jpg -r someDir_).  Creating sidecars for every single file means this process will write to every jpg, rather than just those that actually have user-triggered modifications to be written.

**Comment by grumpazoid** [comment]
Agree with this.
For the reasons stated, I use an external image viewer first and then only import those files I wish to edit.

**Comment by metal450** [comment]
Not stale; this just hasn't gotten any actual response...

**Comment by phweyland** [comment]
Should be soved by #4448

**Comment by metal450** [comment]
Nice!! Can't wait until the next release - hopefully it'll at long last be the one that enables me to migrate away from Lightroom :)

**Comment by metal450** [comment]
Just to clarify: that was merged 6 weeks back, but is tagged as 3.2 - I think this means it won't actually be in the releases until 3.2, correct? Which is listed as due Dec 31, 2020?

**Comment by metal450** [comment]
I'm still seeing this behavior in the most recent release, 3.4.1-1.1.  All I did was install the software (from scratch) & import a folder of jpegs. It instantly created thousands of new xmp files, despite no edits.  Am I missing something? Was this indeed fixed?

**Comment by johnny-bit** [comment]
#4450 has more steam so this one gets the close. 

duplicate of #4450
