### ISSUE TITLE
dartable 2.6.2 always crash upon importation of folders containing pictures edited with Snapseed

### ISSUE THREAD

**Issue by mlaverdiere** [darktable-org/darktable#2835]
I'm on Linux Fedora 30, with darktable-2.6.2-1.fc30.

While trying to import 2 picture folders, darktable starts the importation process and then crash at some point. I can manage to complete the importation process by starting it multiple times, with the same folder, and going through multiple crashes. I've tried with and without the options related to recursive folder import and metadata upon import, without any difference. 

The 2 folders in cause include RAW (nef & dng) + JPG and are relatively large: one of 312 files, for 2.1GB and the other of 36 GB for 5262 files.

Backtrace attached.

[core_backtrace.txt](https://github.com/darktable-org/darktable/files/3463775/core_backtrace.txt)

**Comment by mlaverdiere** [comment]
I did some further tests with the same folders, starting from a fresh darktable setup (i.e. complete reset of config file and without any pictures previously imported) and found out the following: it seems that some jpg files (named *.jpeg) created (edited) with the Android Snapseed app. could be the cause of the darktable crash previously reported (other nef and jpg files in the same folders are importing fine).

For testing purposes, here's one of these jpg files created/edited with Snapseed: 

![DSC_0087-01](https://user-images.githubusercontent.com/30075133/62413050-c7227b80-b5d8-11e9-9c83-1c1125cc8be6.jpeg)

**Comment by jenshannoschwalm** [comment]
Unfortunately the Fedora 30 darktable 2.6.2 rpm sucks!
For many years Fedora has a good working dt, for F30 there are at least three problems i am aware of.
1. I also observed exactly what you describe, but after some importing restarts all files were available.
2. The dt performance is terrible when using fedoras original rpm, the introduction of the new c and c++ compilers was not compatible with darktables code when they released F30. They 'fixed' it by disabling multithreading... [See](https://bugzilla.redhat.com/show_bug.cgi?id=1728682)
3. Fixing compiler stuff for dt and Fedora30 is absolutely fine for darktable#s git master tree but has  not been backported to the 2.6 tree.

What can **you** do?
Look at [https://www.darktable.org/install/#3rdparty](url) and either
1. Look out and get a 2.7 darktable-git version rpm
2. try to compile your own as described in [http://www.darktable.org/install/](url), see the git version section.

BTW, if you use the current git darktable version you will see it working faster than ever :-)

**Comment by jenshannoschwalm** [comment]
ok, thanks for the file. That indeed crashes immediately when importing, i will look into it...
