### ISSUE TITLE
Show wrong color when the picture is open

### ISSUE THREAD

**Issue by Stepi007** [darktable-org/darktable#2837]
When I open the photo in Darktable it shows me photo with some grey filter. In preview the picture look normal. Sometimes it works normaly but it is rarely.

**To Reproduce**
1. Open photo through Dark Table

**Expected behavior**
I dont know how to remove this filter....

**Screenshots**
darktable preview
![image](https://user-images.githubusercontent.com/53668100/62418139-f14a6b00-b6b6-11e9-8c2f-97b1c4e66e32.png)

how can I see it
![image](https://user-images.githubusercontent.com/53668100/62418145-163ede00-b6b7-11e9-9db6-13d34e592929.png)

**Platform (please complete the following information):**
 - OS: W10 
 - Version 2.6.1/2

I am a new one. So I am sorry If I make some stupid mkistake

**Comment by chhil** [comment]
You can see your thumbnail in darktable appears brighter than the raw image. You can read up on why the difference is there here.
[https://www.darktable.org/usermanual/en/thumbnails.html](url)

Most raw files will contain a full sized embedded fully processed in camera jpeg and that is what windows image viewer is displaying. In fact that's what the camera displays too through its LCD panel when you are shooting in raw.
Hence you are seeing the difference.
