### ISSUE TITLE
Segfault on startup under KDE Neon 5.16 with Vega56 and ROCm

### ISSUE THREAD

**Issue by qosch** [darktable-org/darktable#2839]
I am opening this issue because I encountered problems described in this thread on pixls.us (no real need to read the thread, thogh):
https://discuss.pixls.us/t/amd-rocm-opencl-and-linux-kernel-4-18/8793/5

After reinstalling my operating system KDE Neon 5.16 and ROCm (latest version, 2.6 I think) to make sure nothing else was causing the problem I installed Darktable 2.6.2 from the de Bruijn PPA. When starting it from the UI just nothing happens, the backtrace below is from starting it with `darktable -d opencl`.

My System (in case this helps):
Ryzen 5 3600
Vega 56
16GB DDR4 RAM

Backtrace is attached.
[darktable_bt_SNS65Z.txt](https://github.com/darktable-org/darktable/files/3464964/darktable_bt_SNS65Z.txt)

Any help appreciated!

**Comment by Entropy512** [comment]
Observations:
1) Not sure if 2.6.2 includes the cache invalidation fixes for OpenCL that went in back in January
2) Given how much difficulty people seem to be having getting ROCm installed, it may have maturity problems, similar to the issues that caused NEO to be blacklisted for a while.  (NEO has matured significantly, to the point where I was able to argue for the removal of the blacklist.  Does ROCm run Khronos cert against every release like Intel does for NEO?)
3)  Determine if the cache invalidation code isn't there/isn't working right, try removing the OpenCL kernel caches from ~/.cache/darktable/ - please note before deletion if the cache directory appeared to carry a version number, and if that version number seemed sensible for your OCL driver.  (As opposed to some NEO releases misreporting 1.0.0...)

**Comment by qosch** [comment]
1. and 3. I did delete the cache and config file, did not help.
2. @cryptomilk reported ROCm to work fine (see pixls.us thread mentioned in first post)

To be fair I am not even sure if this problem is openCL related (maybe someone can confirm this by looking a the backtrace?). I am just guessing because before trying to get openCL to work darktable did not crash on startup.

**Comment by johnny-bit** [comment]
Do you still have the issue? Judging from bactrace it was problem with drivers, outside of darktable's controll so I'll close the issue... If you still have the issue on most recent release/master and updated drivers please comment so I can reopen and we can continue investigation afresh
