### ISSUE TITLE
Snapshot not working on build 1594

### ISSUE THREAD

**Issue by sona30g** [darktable-org/darktable#2842]
**Describe the bug**
On windows build 1594 the snapshot compare slider is not showing
**To Reproduce**
1. Go to darkroom in Darktable with any image,and do some basic editing 
2. Click on  Snapshot module and create 2 snapshots to compare try clicking the two snapshots to compare, the comparison bar does not appear
3. The snapshot was working fine on hte previous build 1477

**Expected behavior**
The snap shot comparison bar should appear whenever two snapshots are selected to view the comparison
**Screenshots**
![image](https://user-images.githubusercontent.com/5626525/62562874-93c54280-b89f-11e9-9d63-980b59bffe4b.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 2.7.0+1594]

**Additional context**
The snapshot module is working fine on previous build, i.e. 1477

**Comment by phrrk** [comment]
I have just built latest git master on Ubuntu and windows with same version of gcc (9.1) and can confirm that this is a windows issue, i.e snapshots are fine on Ubuntu.  I cannot see on obvious recent changes to snapshots and so am trying to home in on which commit is the problem. This might take a little while.

**Comment by phrrk** [comment]
I have now worked back to build 1450, i.e. before the 1477 which you said worked for you, and still do not get snapshots working with split screen etc.  I am beginning to wonder whether this is in some way compiler related as I fairly recently updated to gcc 9.1 on my mingw set up (though as I said I have no problem with gcc 9.1 on Ubuntu).   Unfortunately I cannot recall when I last had snapshots working (I don't use them much).  Which compiler are you using?  Do other windows users also have this issue?

**Comment by phrrk** [comment]
Some discussion on pixls.us confirms that another person experiencing this issue had also recently updated their msys2/mingw system. I reverted gtk3 to an earlier version (as this had recently been updated as part of the general system update) but this did not solve the problem.  I don't think reverting gcc to an earlier version is straightforward.  It would be useful to know if anyone has been successful in recently building of a version of dt for windows that does still support snapshots.

**Comment by peterbud** [comment]
Confirmed, it's not working as `g_open() ` has changed in glib. I have a fix will submit a PR

**Comment by peterbud** [comment]
fixed with #2897

**Comment by peterbud** [comment]
@TurboGit  could you pls close this issue?

**Comment by TurboGit** [comment]
Done!
