### ISSUE TITLE
Drag and drop does not work from light table, only from darkroom bottom panel filmstrip

### ISSUE THREAD

**Issue by lsolbach** [darktable-org/darktable#2843]
**Describe the bug**
As I am often work with bracketed shots for HDR processing in photomatix, I need to drag a bunch of RAWs on the photomatix window. While this works from the filmstrip in the bottom of the darkroom, it does not work from the file manager (or zoomable lighttable) in the light table.

This is an inconvenience, because in the light table you have a much better overview of the images.

**Expected behavior**
Enable Drag and drop from the light table, at least in file manager mode.

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version 2.6.0

**Comment by johnny-bit** [comment]
the filmstrip & filemanager have been overhauled with completely different feature set. While I won't hide that I don't understand your workflow and simply never use d&d functionality anywhere, I must close this issue as it doesn't match at all current dt featureset. Please check recent release and if you still have a problem, file a bug against current release :)

**Comment by lsolbach** [comment]
Just for the reference, it works in 3.4.
