### ISSUE TITLE
darkroom right side menu bar missing 

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2844]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. funtoo linux]
 - Version [e.g. 2.6.0]

**Additional context**

**Comment by ptilopteri** [comment]
current master darktable-2.7.0~git1607.ac52cb79c does not have the menu bar which allow switching between groups of modules
screenshot:  http://wahoo.no-ip.org/~paka/dt.screenshot.menu.png

**Comment by Nilvus** [comment]
I still have both on the same master version. It's not an issue but an option to set on preferences GUI. See above which one and be sure to have both selected. Be careful, you have to restart darktable after changing the setting to have it applied.

![prefsgui](https://user-images.githubusercontent.com/45535283/62725942-68189880-ba16-11e9-80ef-12f71f73ff42.jpg)

**Comment by Nilvus** [comment]
Think of closing this issue if your problem is solved.

**Comment by ptilopteri** [comment]
tks, my problem is solved, closing
