### ISSUE TITLE
Export of full resolution file is incorrect/missing edits . Lower res exports are correct (Caused by Haze Removal Module)

### ISSUE THREAD

**Issue by grumpazoid** [darktable-org/darktable#2845]
I have experienced the same problem on a few different edits from NIKON RAW files (D3300)
Exporting at lower resolution such as 2048 everything is fine.
If I set values to 0 / 0 for full res export, then the export is messed up with missing edits.

I have posted sample files on the darktable user email list : 
https://www.mail-archive.com/darktable-user@lists.darktable.org/msg07741.html

I am using version 2.6.2
I have tried on two windows machines and one linux machine with the same results.

To reproduce just load up the RAW with associated XMP
Perform two exports one at 2048 and one at full res.
The two results are quite different.

**Comment by grumpazoid** [comment]
I have carried out some further testing. 
If I turn off the haze removal module, then the exported images are near identical at loewr and maximum resolutions. 

Haze removal module shows  desired result in darktable while editing, but is causing unpredictable results to the  way exported files look at different resolutions.

**Comment by hellbuster** [comment]
@grumpazoid could you do the same experiment with OpenCL turned off? There has been reports of Haze Removal doing funny stuff on export and knowing if the problem is reduced to the OpenCL implementationg would be helpful.

**Comment by grumpazoid** [comment]
@hellbuster On my main PC, OpenCL is shown as not available so it is not being used.
I've looked onto this - I have a OpenCL capable card but because it is an older card it is not supported by DT.
So doesn't seen to be OpenCL related?

**Comment by jakubfi** [comment]
I've tested it on current 2.7 with no OpenCL. Same image, but with a minimal edit (only haze removal enabled). It's not that there is a difference between fullsize and a smaller version export. Haze removal behaves differently for different export sizes. Attached is a set of images exported in horizontal resolutions between 500px and 3000px in 100px increments - each one is rendered differently.
[dt-exported.zip](https://github.com/darktable-org/darktable/files/3521350/dt-exported.zip)

**Comment by grumpazoid** [comment]
@jakubfi. Many thanks for this.
It is amazing how just a small change in resolution can have a big change in output - e.g. files 37 and 38
That is certainly similar to what I experienced.

I'd be interested to know why this happens and if there is any way that the output at a chosen resolution could be made to look the same as the image when viewed in darkroom.

I've been exporting at resolutions of 1024/2048 for the web and 6000x4000 (original size) to keep as my master copy. I'd be grateful for any suggestions to keep the output consistant.

**Comment by jakubfi** [comment]
Ok, so I am basically a pixel pushing baby here and it's likely that I'm talking nonsense: Isn't this all because haze removal runs a guided filter and other things with fixed window sizes (w1 and w2)? @rabauke?

**Comment by hellbuster** [comment]
That would explain a lot. How do other modules operate, they scale everything when exporting?

**Comment by aurelienpierre** [comment]
In tone equalizer, I'm also using a guided filter, but the size of its window is adapted to the zooming factor (± float to int rounding error). It becomes quite slow when you zoom at 100%, but the output is scale invariant.

**Comment by wezm** [comment]
Pretty sure this is still an issue.

**Comment by rabauke** [comment]
@grumpazoid : The whole discussion on https://redmine.darktable.org/issues/11763 started with a bug report affecting the edit of an image which does not include the haze removal module (20170927_0006.CR2.xmp). Later, however, the issue is attributed to the haze removal module. Even later another image is attached with an image stack not including the haze removal module (DSC_3775.NEF.xmp).

Thus, I wonder what is the bug report about?

By the way, I can reproduce the issue reported for 20170927_0006.CR2.xmp in https://redmine.darktable.org/issues/11763 even in current git master, but as already mentioned the haze removal module is not used at all here.

**Comment by grumpazoid** [comment]
All I can report is that I stopped using haze removal and I have not noticed the problem since.

**Comment by jakubfi** [comment]
> Thus, I wonder what is the bug report about?

@rabauke See the file attached in commend https://github.com/darktable-org/darktable/issues/2845#issuecomment-523063502

**Comment by rabauke** [comment]
@jakubfi This contains just a bunch of exported files. No raw file, no xmp file. How can I reproduce and debug this?

**Comment by jakubfi** [comment]
@rabauke This is a set of exmaple exports with an explanation, which answer your question "what is the bug report about" (also expanging on the original bug report). Those exports were done from a raw and xmp provided by the reporter in a thread mentioned in the first comment. For your reference:
RAW: https://drive.google.com/file/d/14WweXn74nf3GgXf-boz4wl0_NnzqUJOm/view
XMP: https://drive.google.com/file/d/1U3Pd6_YbqEbJp0VLjFi_LxMO54zDD5Qk/view
Using these, I am still able to reproduce the bug with dt-master.

**Comment by rabauke** [comment]
@jakubfi As I see you have applied two instances of the haze removal module. In each of the two instances sliders have been pushed way beyond what appears reasonable to me, creatting a lot of artifacts and noise. These artifacts of the first instance affect the second instance of the haze removal module. The intrinsic noise in the (scaled) image as well as the noise produced by the first instance of the haze removal module depend on the scale of the exported image, which finally leads to the scale dependent output. You can avoid this by enabling "high quality resampling" for export. In this case down sampling to the final output size happens at the very end of the pixel pipe. I.e., the haze removal module always gets the same unscaled input image.

Furthermore, you use a drawn mask to include the _sky only_ in the second instance of the haze removal module. The sky, however, is usually the region where the algorithm implemented by the haze removal module is most prone to create artifacts. The haze removal module can compensate the effect of atmospheric haze between the camera and some objects at _finite_ distance. You should use a mask to _exclude_ the sky!

I do not consider the described behavior a bug, although it might be unsatisfactory and unexpected. I do not see what we can do against this behavior. I consider this more a miss use of the haze removal module.

**Comment by jakubfi** [comment]
@rabauke Let me just state for the record that I'm not the original reporter and it wasn't me using haze removal this way. ;-) I was just trying to figure out the scope of the problem using the data provided.

Let's forget about the original edit for now, here is my minimal, much more sane test case. Take the same image, reset the history stack, enable _only_ one instance of haze removal, no masks. Set the strength to 0.65. Export the image in several different sizes (with or without hq resampling, although with hq it is much more obvious). Images will be drastically different (both color-wise and tonality-wise). I would expect to see no such differences. No other module behaves this way.

This is much better visible when switching between images, but let me illustrate it here somehow anyway. First column: no hq resampling, second column: with hq resampling. Images rescaled after the export to fit together nicely. The only thing that changes between images in each column is the export size.

![Untitled](https://user-images.githubusercontent.com/1270167/73614638-4bde6880-4601-11ea-8d7a-3d66a338f15a.jpg)

**Comment by grumpazoid** [comment]
@rabauke  Well done in posting my sample pictures. I was about to do that. I think I originally posted the links to them on the darktable mailing list. There was some acknowledgement of the problem but no real progress. 
Haze removal work well if just looking at the on screen darktable image but definitely causes vastly different outputs at different export resolutions.
It would be great if it could be fixed as I miss using it.

**Comment by rabauke** [comment]
@grumpazoid @jakubfi It has been reported in https://redmine.darktable.org/issues/11763 for two different examples that darktable produces output-scale dependent color casts very similar we are talking about here. These examples **do not** employ the haze removal module. I can reproduce these  output-scale dependent color casts (with edits **not** utilizing the haze removal module) in the current version of dt git master.

Before I can fix anything here, I have to understand better what is going on here. Because the issue has been reported also in cases **not including** the haze removal module the color casts cannot be attributed to the haze removal module alone. I suspect that the haze removal module merely enhances a general issue in darktable rather than being the (only) source of the observed problem.

**Comment by jakubfi** [comment]
@rabauke Good to know (and a bit scary) that haze removal is not the only known case of such problem. Happy hunting!

**Comment by grumpazoid** [comment]
@rabauke Thanks for that link and explanation. As you say, maybe the problem is more pronounced when using haze removal as I had not noticed in other edits.
Looks like this has been a long standing issue.

**Comment by skolarianer** [comment]
Here is another example where the haze removal module produces (or enhances) the "what you see is not what you get" issue.

Screenshot (preview vs. export):
![image](https://user-images.githubusercontent.com/6286711/79283425-1931d580-7eb8-11ea-9ec2-28c8fcd7cb4e.png)

Original file to play with:
![Sterntest](https://user-images.githubusercontent.com/6286711/79283167-47fb7c00-7eb7-11ea-9cc8-be5ecac0a948.png)

Interestingly sometimes (not always) the preview looks exactly like the eventual wrong export if viewed at 100%. But at any other zoom level the haze removal is applied correctly … whereas the export is still incorrect.

![image](https://user-images.githubusercontent.com/6286711/79284196-37003a00-7eba-11ea-9ad9-06c80182be75.png)

**Comment by wezm** [comment]
Why did the bot close this? Is it fixed?

**Comment by ptilopteri** [comment]
iirc, the bot closes items which have had no action in one year.

**Comment by wezm** [comment]
> iirc, the bot closes items which have had no action in one year.

Sounds right given it was a year since the last comment. I think the problem remains, can the issue be reopened?

**Comment by ptilopteri** [comment]
If *you* filed the issue, you have rights to re-open

if not, you are free to open a new issue

**Comment by grumpazoid** [comment]
I opened this issue. As far as I know it still exists. I have stopped using haze removal module. Would be good to re-open if it is still causing problems for people - how is that done?
