### ISSUE TITLE
culling mode cannot pan on 2nd image

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#2851]
I cannot pan when on second image.

**To Reproduce**
1. Start dt
2. Select one picture
3. Select "culling" mode with 2 pictures displayed
4. Zoom on 2nd one (on the right, ctrl-shift-scroll)
5. Pan on this image, nothing happens

I have also some strange & different behavior. So I'm not sure this will reproduce all the time but it is quite frequent.
 
**Expected behavior**

We should be able to pan. Sometimes you can pan the second image going over the first one.

**Platform (please complete the following information):**
 - OS: GNU/Debian
 - Version git current master

**Comment by TurboGit** [comment]
@AlicVB : would you mind having a look? Thanks.

**Comment by AlicVB** [comment]
@TurboGit : half back from holidays, but it should be fixed with my last PR (with a very slight perf improvement)

**Comment by TurboGit** [comment]
Thanks @AlicVB, fix is merged.
