### ISSUE TITLE
darktable-cltest.exe caused an Access Violation at location 00007FFCFA657EC7 in module amdocl64.dll Reading from location 000000000000001C.

### ISSUE THREAD

**Issue by jdegraef** [darktable-org/darktable#2853]
**Describe the bug**
darktable and darktable-cltest close with an access violation

**To Reproduce**
try to run darktable

**Platform (please complete the following information):**
- Windows10 Home
- version 2.6.2
- hardware asus x570zd ( nvidia gtx1050 / amd radeon vega8)

[darktable_bt_0YWF6Z.txt](https://github.com/darktable-org/darktable/files/3495453/darktable_bt_0YWF6Z.txt)
[darktable_bt_PNLK6Z.txt](https://github.com/darktable-org/darktable/files/3495454/darktable_bt_PNLK6Z.txt)
[darktable_bt_ZVRP6Z.txt](https://github.com/darktable-org/darktable/files/3495455/darktable_bt_ZVRP6Z.txt)

**Comment by Nilvus** [comment]
Please see these issues already related to your problem and opencl, especially with specific configuration like yours (2 graphics cards of 2 different brands) :
https://github.com/darktable-org/darktable/issues/2655
https://github.com/darktable-org/darktable/issues/2599

In general, disable OpenCL or update AMD driver fix this problem. Sometimes, deactivate one of the cards (on BIOS if possible on what I have already seen).
So please close the issue if one or the other option solve your issue. That's a problem with some specific configuration. Unfortunately, darktable community doesn't have at this time sufficient Windows developers to have better solution.

**Comment by jdegraef** [comment]
DT is runnable w/o openCL. FWIW updating drivers did not resolve the issue with opencl enabled.
