### ISSUE TITLE
Mask Path tool does not start from cursor location when cursor is on the edge

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2856]
**Describe the bug**
The path tool for a mask offsets its starting point from the cursor location when cursor starting point is placed on edge. The behavior is identical on any of the 4 edges (except when the vertical edges center is used, here the path gets drawn correctly).

**To Reproduce**
1. In any image, any module that supports drawn mask, select drawn mask using path.
2. Try to draw the path from any edge near the corners. The path starts at an offset. 
3. See sample image's cursor placement and path line.

**Expected behavior**
The path should start from the arrow tip of the cursor.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [Win 10]
 - Version [darktable-2.7.0+1612~g9e212dc9d-win64]

**Additional context**
![image](https://user-images.githubusercontent.com/1119439/62997675-af73ae80-be86-11e9-9e74-887cd2d549b1.png)

**Comment by TurboGit** [comment]
Is that with lens correction activated?

**Comment by chhil** [comment]
@TurboGit 
I tried it with and without lens correction. It only happens with lens correction activated.

I also tried moving the activated lens correction module before and after the retouch module hoping the pipeline change would make a difference but it didn't and the cursor gets an offset.

**Comment by jenshannoschwalm** [comment]
I have also observed this, if you activate the yellow box displaying the mask channel you will see the mask _effect area_ is correct, the circle is wrongly positioned by the cairo drawing code as it doesn't know about lens corrections.

**Comment by TurboGit** [comment]
Can you check that https://github.com/darktable-org/darktable/pull/2892 fixes the issue?

**Comment by chhil** [comment]
@TurboGit 
I tested my use case after building  darktable-2.7.0+1660~gfc45676ea-win64.exe this morning.

It works correctly now. Thank you.
