### ISSUE TITLE
Darktable 2.7 → Preferences window size issues

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#2858]
**Description**
Preferences window is not consistent in it's design. Some elements are oversized yet some are small. 

**To Reproduce**
1. Install dt 2.7
2. Open preferences window

**Expected behavior**
Reduce oversized dimensions. Make it more like dt 2.6 window — everything is cramped )))

**Platform (please complete the following information):**
 - OS: Debian 10 Stable

**Additional content**
Schema migration window: What happened to window borders?

**Screenshots**
![prefs_2 7](https://user-images.githubusercontent.com/53873917/63072102-b0f6b280-bf2a-11e9-80e7-76d430159450.png)

![prefs_2 6](https://user-images.githubusercontent.com/53873917/63072107-b6ec9380-bf2a-11e9-9761-a1cc52bb22b8.png)

![schema_migration](https://user-images.githubusercontent.com/53873917/63072113-bc49de00-bf2a-11e9-9fed-13ea64334462.png)

**Comment by Nilvus** [comment]
Most GTK widgets (that's a limitation of GTK not darktable here) are related. Here, the size depends on the font and darktable css theme use font OS system, so how buttons, preferences and all things with text inside or around could be different with that theme depending of OS used and default OS font and size used. This was discussed a lot (and tested by many users) this past months (@aurelienpierre and me works on this new UI). See what I have on my OS for example with darktable default theme. I don't have same "not consistent" design. The darktable-elegant themes are the themes recommanded by @aurelienpierre and me to avoid that. The font and size is fixed and same for all.

![Capture-20190815184546-800x830](https://user-images.githubusercontent.com/45535283/63110980-ec29cd80-bf8c-11e9-9ca5-0233f0426bd1.png)

So please search a little issues and PR already posted before posting issues. This issue can't be improved for reasons explained here.

Here the main ones about your issues (many others could be find by using "UI" and "CSS" tags on search, both issues and pull requests) :

https://github.com/darktable-org/darktable/pull/2037
https://github.com/darktable-org/darktable/pull/2586

**Comment by timur-davletshin** [comment]
Thanks for pointing out to PRs, I will try it. But those screenshots doesn't look like a lot of improvement. Sure, I do my own tweaks in CSS but it hurts to see those boxes on fresh installations ))) Probably I should spend less time in blender — program which I always try to compare with dt (only UI of course).

**Comment by timur-davletshin** [comment]
What about those orphaned schema migration windows? Warning about starting second dt instance is another example. Cannot they be more "native" like?

**Comment by Nilvus** [comment]
The main limit remains GTK himself and be sure that @aurelienpierre and I spent some time and many tries to have better things. Of course, that screenshots aren't a lot of improvement. They're just the best possible we tried to have regarding of GTK limits here. Even Gimp developers now see GTK limits (and GTK is just Gimp ToolKit, so created by Gimp developers many years ago). 

Better design on darktable now could only pass by using another UI library. But not so easy to rework completely and change language as this will also breaks lot of other actual useful features on darktable.

I propose you, if it's ok to you, to close these issues as we can't do something better here. And if you find with CSS a way we didn't find, of course, don't hesitate to propose it as a PR. I will be happy to improve UI if possible (I don't have skills on GTK but see it's limit when working on CSS) and I like to have the most consistent and beautiful UI.

**Comment by Nilvus** [comment]
> What about those orphaned schema migration windows? Warning about starting second dt instance is another example. Cannot they be more "native" like?

Not sure to understand what you mean here. And if it's about design, really that's not the part really important to work on. Migration window only appear one time when a major update appear (so for users who don't use master development one, that's just no more than one time a year if they update on each release). About second dt instance, that's also only appear when a user try to open darktable a second time or if darktable doesn't closed correctly.

**Comment by Nilvus** [comment]
> Thanks for pointing out to PRs, I will try it. But those screenshots doesn't look like a lot of improvement. Sure, I do my own tweaks in CSS but it hurts to see those boxes on fresh installations ))) Probably I should spend less time in blender — program which I always try to compare with dt (only UI of course).

Last thing, if you have made tweaks on CSS, and don't know how to propose a PR, it would be good to post css lines here. I could post the PR (by of course telling that you're the author) if it's great for many users (testing on other languages is important ; default UI have to be the best compromise on most configurations so also have something quite good on many used languages. Difficult point on what I've tested ; and some headaches sometimes).

**Comment by timur-davletshin** [comment]
It looks like my understanding of consistent UI design is a bit different from your's. I had enough trying to convince Aurelien to avoid additional font dependencies in CSS )))

**Comment by timur-davletshin** [comment]
> Migration window only appear one time... that's also only appear when a user try to...

Doesn't look like what they call "consistent" )

**Comment by aurelienpierre** [comment]
The issue with notebook tabs width can be fixed by adding:

```
gtk_container_child_set(GTK_CONTAINER(notebook), page1, "tab-expand", TRUE, "tab-fill", TRUE, NULL);
```
like this:
```
g->notebook = GTK_NOTEBOOK(gtk_notebook_new());
  GtkWidget *page1 = GTK_WIDGET(gtk_box_new(GTK_ORIENTATION_VERTICAL, 0));
  GtkWidget *page2 = GTK_WIDGET(gtk_box_new(GTK_ORIENTATION_VERTICAL, 0));
  GtkWidget *page3 = GTK_WIDGET(gtk_box_new(GTK_ORIENTATION_VERTICAL, 0));

  gtk_notebook_append_page(GTK_NOTEBOOK(g->notebook), page1, gtk_label_new(_("simple")));
  gtk_notebook_append_page(GTK_NOTEBOOK(g->notebook), page2, gtk_label_new(_("advanced")));
  gtk_notebook_append_page(GTK_NOTEBOOK(g->notebook), page3, gtk_label_new(_("masking")));
  gtk_widget_show_all(GTK_WIDGET(gtk_notebook_get_nth_page(g->notebook, 0)));
  gtk_box_pack_start(GTK_BOX(self->widget), GTK_WIDGET(g->notebook), FALSE, FALSE, 0);

  gtk_container_child_set(GTK_CONTAINER(g->notebook), page1, "tab-expand", TRUE, "tab-fill", TRUE, NULL);
  gtk_container_child_set(GTK_CONTAINER(g->notebook), page2, "tab-expand", TRUE, "tab-fill", TRUE, NULL);
  gtk_container_child_set(GTK_CONTAINER(g->notebook), page3, "tab-expand", TRUE, "tab-fill", TRUE, NULL);
```

But then, the problem of width is a conundrum. You have to account for every typical word length in each language (English = 5-6 letters/word, French = 8-10 letters/word, German = 9-12 letters/word, etc.), then every screen size × DPI scaling, then every typical font width (hence the imposed font, to fix at least one parameter), then every anti-aliasing/kerning sweet spot in every desktop/OS. 

So, all in all, as long is it's readable, well… it's readable.

**Comment by Nilvus** [comment]
Thanks for completing with your GTK coding skills. Length language code is the main difficult thing here !

**Comment by Nilvus** [comment]
> > Migration window only appear one time... that's also only appear when a user try to...
> 
> Doesn't look like what they call "consistent" )

They're not as we don't spend anytime on them. And, I rarely see them so I don't care. I just help here (like all developers) on my free time. If you want to improve them, feel free to help.

**Comment by timur-davletshin** [comment]
> Thanks for completing with your GTK coding skills. Length language code is the main difficult thing here !

It's not a problem at all. I use Russian which is more like French or even German and when names are used (creator, publisher, etc.) they are nearly identical to English. Copyright = Копирайт, Aurelien = Аурэлиен.

**Comment by aurelienpierre** [comment]
Well, last time I did translations of the UI from English to French, I had to take ugly shortcuts to fit the strings into the 320 px typical sidebar width, and the French users certainly don't have exact translations…

**Comment by Nilvus** [comment]
> > Thanks for completing with your GTK coding skills. Length language code is the main difficult thing here !
> 
> It's not a problem at all. I use Russian which is more like French or even German and when names are used (creator, publisher, etc.) they are nearly identical to English. Copyright = Копирайт, Aurelien = Аурэлиен.

Not all words are like your examples. Some really doesn't have same lengths and lines on tagging modules (your other issue) is the perfect example. From english to french, some letters more on french (same in german).

new = nouveau ; import = importer ; export = exporter (so french have here 8 characters more than english).

**Comment by timur-davletshin** [comment]
> Well, last time I did translations of the UI from English to French, I had to take ugly shortcuts to fit the strings into the 320 px typical sidebar width, and the French users certainly don't have exact translations…

Me too. But fields in preferences window is a special case. 

> and the French users certainly don't have exact translations…

And I'm sure it is a good thing. Some English phrases are really long without reason for that. It would be a good idea for someone to check those tooltips like "delete selected tag" vs "deletes the selected style". I don't get why buttons with similar action have different tooltips, and I doubt that "the" is needed before "selected style".

**Comment by timur-davletshin** [comment]
> new = nouveau ; import = importer ; export = exporter (so french have here 8 characters more than english).

Yet none of them is used preferences fields. BTW average word lenght is a poor index. E.g. Russian and Belorussian and nearly identical in every aspect except that Russian is using analytical constructions in some cases. "Робитиму" in Belorussian and "Буду работать" in Russian. Russian phrase is 50% longer but Russian average word in that phrase is 50% shorter.

**Comment by Nilvus** [comment]
> Yet none of them is used preferences fields. BTW average word lenght is a poor index. E.g. Russian and Belorussian and nearly identical in every aspect except that Russian is using analytical constructions in some cases. "Робитиму" in Belorussian and "Буду работать" in Russian. Russian phrase is 50% longer but Russian average word in that phrase is 50% shorter.

Hmmm, that was an example... The idea remains the same on all parts of darktable (fields on preferences windows are smaller in French than in English, that's a reality. And fields lengths here couldn't so easily be adjusted). As you, I could find terms confirm the opposite of what you say on preferences windows; Just a waste of time here...

**Comment by timur-davletshin** [comment]
So it was not a problem to have fields like shown above in dt 2.6 for several years and now suddenly we need 50% more space just for the same information in dt 2.7? Was lack of horizontal space addressed by someone?

**Comment by aurelienpierre** [comment]
The preference window was way too small on 4K prior to 2.7, with the +/- buttons on the right of the fields being hidden by the scroll bar. The window is dynamically resizable too.

Again, if you have some code to fit :
(every screen size) × (every resolution) × (every DPI scaling factor) × (every font size) × (every language),
be my guest, because I don't.

**Comment by aurelienpierre** [comment]
![Screenshot_20190816_003422](https://user-images.githubusercontent.com/2779157/63131349-a6d1c400-bfbd-11e9-9f3c-544ba170d6f4.png)
not sure if it's too wide…
