### ISSUE TITLE
Image information → Geodata leading zero

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#2860]
**Describe the bug**
Latitude is without leading zero, while longitude is with leading zero.

**Expected result**
Remove leading zeroes.

**Screenshot**
![img_info_zero](https://user-images.githubusercontent.com/53873917/63072779-4c3d5700-bf2e-11e9-99ad-76e76f73d9dd.png)

**Comment by MStraeten** [comment]
Thats correct since longitude can have 3 digits and latitude only 2. Using 3 digits for longitude is common in navigation to avoid misunderstanding

**Comment by timur-davletshin** [comment]
Thank you. At least now I see logic ))) But personally I prefer data representation used in google maps, bing and OSM — without leading zeroes.

**Comment by MStraeten** [comment]
However, a different personal preference is not a bug

**Comment by timur-davletshin** [comment]
You right. Not a bug.
