### ISSUE TITLE
Crash after trashing second photo,

### ISSUE THREAD

**Issue by MikeCatan** [darktable-org/darktable#2862]
I am able to successfully trash a photo in Lighttable.  However, trashing a second photo within ten seconds from the first crashes Darktable. 

**To Reproduce**
1. Launch Darktable
2. Click on Lighttable
3. Import Photos from Folder that contains 412 .NEF files
4. Select a Photo
5. In Select Image[s] dropdown click trash
6. In Select Image[s] dropdown (of different photo) click trash

**Expected behavior**
I would expect Darktable to delete the second photo when I click the trash button and then continue running.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.2

**Comment by peterbud** [comment]
I could not repro a crash this way.
@MikeCatan could you pls provide more info on how to repro this, and pls also attach the crash log / backtrace pls?

**Comment by MikeCatan** [comment]
Peter,

I was subsequently able to use darktable once successfully for an extended
period without it crashing. So I suspect that it may have been a one time
issue with my internal system.  Please close my inquiry and if it recurs I
will attempt to attach a log.

Thanks

**Comment by peterbud** [comment]
@MikeCatan thanks for confirming that it works now. Unfortunately only you or one of the admins can close the issue. The best would be you closing it.
