### ISSUE TITLE
Exif information not displaying in the Histogram panel

### ISSUE THREAD

**Issue by sona30g** [darktable-org/darktable#2865]
The Exif information, like shutter speed,ISO and aperture was getting displayed on histogram panel in version 2.6.2, But with build 1477 I do not see that information in the same place anymore

**To Reproduce**
1. open darktable
2. open an image in darkroom
3. in build 1477 the exis data is not visible, but with the stable build 2.6.2 it was visible
4. The screenshot with build 2.6.2 and 1477 respectively are shared in the below thread
Histogram panel with build 2.6.2
![2019-08-17 22_41_09-darktable](https://user-images.githubusercontent.com/5626525/63217162-64d18b00-c141-11e9-934d-8f006738a1a2.png)

Histogram panel with build 1477
![2019-08-17 22_27_24-](https://user-images.githubusercontent.com/5626525/63217166-7c107880-c141-11e9-87e4-8265ee9b222d.png)

**Expected behavior**
The exif information should be visible 

**Platform (please complete the following information):**
 - OS: windows
 - Version 2.7, build 1477

**Additional context**

**Comment by sona30g** [comment]
Now I can see the information at the bottom of the open image, so closing the issue

**Comment by theres** [comment]
https://github.com/darktable-org/darktable/issues/2406#issuecomment-482943164.

@TurboGit maybe this should be enabled by default?

**Comment by sona30g** [comment]
It is enabled by default, but I used to see it near the Histogram(In 2.6.2), so was not able to find it once I switched to the build 1477 as it was at the footer section of the image.
