### ISSUE TITLE
Add Fujifilm X-T2 camera to the lens correction module

### ISSUE THREAD

**Issue by fabienengels** [darktable-org/darktable#2869]
Hi,

Currently (0d348ba), the Fujifilm X-T2 is not recognized by the lens correction module. Would be possible to add it ?

```
camera/lens not found. Please select manually corrections.
```

Thank you in advance

**Comment by levitte** [comment]
Darktable uses liblensfun, could it be that liblensfun needs an update?

**Comment by fabienengels** [comment]
Thank you to redirect me to liblensfun, after checking their database, the X-T2 is present : https://github.com/lensfun/lensfun/blob/master/data/db/mil-fujifilm.xml#L62-L67

But my distro (Archlinux) provides lensfun 0.3.2-7 (released in 2015) which is the last tagged version of the library. So in the end, I'm not sure if the problem is relevant to Archlinux or that there is no new version of libfun released since 2015 while the project keep evolving.

The issue should be also present on other distribution like Ubuntu. I see two solutions :
- liblensfun releases new version so they can be packaged and updated
- darktable add liblensfun as submodule

The latter solution may be better as it will allow to use the last updated version of liblensfun which may help darktable to support the latest released hardware without waiting update from Linux distributions (my two cents).

**Comment by LebedevRI** [comment]
You probably want to use `lensfun-update-data`.

**Comment by fabienengels** [comment]
> You probably want to use `lensfun-update-data`.

It works ! Thank you !
But won't be more user friendly to directly integrate these updates in Darktable ? That's fine for me to regularly launch a command line but what about regular users who will expect that works directly out of the box ?

**Comment by Nilvus** [comment]
> > You probably want to use `lensfun-update-data`.
> 
> It works ! Thank you !
> But won't be more user friendly to directly integrate these updates in Darktable ? That's fine for me to regularly launch a command line but what about regular users who will expect that works directly out of the box ?

Not needed as we just have to updated it once time when we have a new camera or lens. Having an automatic update will add lines of code not really as useful as time and space spent needed. And having an automatic update when we don't have not so much updates (our gear for most users is not so often changed) and even the lensfun library is not updated so often. We don't need to add more space and resources used.

Maybe adding a button that allow the user to update the lensfun library could help but not an automatic one.

**Comment by fabienengels** [comment]
I was not thinking about an automatic update but to embedded updates with darktable releases as it works with software like Capture One or Lightroom. You don't have to think about updating these data.
