### ISSUE TITLE
darktable.exe caused an Access Violation in module igdrcl64.dll

### ISSUE THREAD

**Issue by leapautrel** [darktable-org/darktable#2871]
Hello,

I downloaded darktable, the last version available, and I installed it. But just a few minutes after opening it, it crashes. I downloaded it again, reinstalled it,  and it still doesn't work.
The document created is the following : 

> this is darktable 2.6.2 reporting an exception:
> 
> -------------------
> 
> Error occurred on Tuesday, August 20, 2019 at 13:50:14.
> 
> darktable.exe caused an Access Violation at location 00007FF82DA309C0 in module igdrcl64.dll DEP violation at location 00007FF82DA309C0.
> 
> AddrPC           Params
> 00007FF82DA309C0 0000000000010000 00000001000C000E 0000000000000000  igdrcl64.dll!clGetCLObjectInfoINTEL
> 00007FF8A0A445A1 00000000043C7718 0000000000000001 00000000000B3340  GDI32.dll!StretchBlt
> 00007FF8A2E3A49C 0000000000000000 00000000043C76E0 0000000000000000  ntdll.dll!RtlUnsubscribeWnfNotificationWaitForCompletion
> 00007FF8A2E3A176 0000000000000000 00000000207E5620 0000000000000000  ntdll.dll!RtlUnsubscribeWnfNotificationWaitForCompletion
> 00007FF8A2E3A010 00000000000EDDF0 00000000000EDF78 000000007FFE0386  ntdll.dll!RtlUnsubscribeWnfNotificationWaitForCompletion
> 00007FF8A2E1C814 00000000000EDF78 000000000010D650 0000000000000000  ntdll.dll!TpWaitForTimer
> 00007FF8A2E165D9 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlReleaseSRWLockExclusive
> 00007FF8A0294034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
> 00007FF8A2E63691 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
> 
> darktable.exe	2.6.2.0
> ntdll.dll   	10.0.17134.799
> aswhook.dll 	19.6.4546.0
> KERNEL32.DLL	10.0.17134.753
> KERNELBASE.dll	10.0.17134.885
> msvcrt.dll  	7.0.17134.1
> libglib-2.0-0.dll	2.58.3.0
> ADVAPI32.dll	10.0.17134.471
> sechost.dll 	10.0.17134.319
> RPCRT4.dll  	10.0.17134.648
> ole32.dll   	10.0.17134.858
> combase.dll 	10.0.17134.885
> ucrtbase.dll	10.0.17134.677
> bcryptPrimitives.dll	10.0.17134.950
> GDI32.dll   	10.0.17134.285
> gdi32full.dll	10.0.17134.950
> msvcp_win.dll	10.0.17134.619
> USER32.dll  	10.0.17134.376
> win32u.dll  	10.0.17134.1
> SHELL32.dll 	10.0.17134.950
> cfgmgr32.dll	10.0.17134.1
> shcore.dll  	10.0.17134.112
> windows.storage.dll	10.0.17134.950
> shlwapi.dll 	10.0.17134.1
> kernel.appcore.dll	10.0.17134.112
> profapi.dll 	10.0.17134.1
> powrprof.dll	10.0.17134.1
> FLTLIB.DLL  	10.0.17134.1
> WS2_32.dll  	10.0.17134.1
> libintl-8.dll	0.19.8.0
> libdarktable.dll
> PSAPI.DLL   	10.0.17134.1
> libwinpthread-1.dll	1.0.0.0
> libpcre-1.dll
> libiconv-2.dll	1.15.0.0
> libgcc_s_seh-1.dll
> libstdc++-6.dll
> libcairo-2.dll
> exchndl.dll 	0.8.2.0
> libexiv2.dll
> libgdk-3-0.dll	3.24.5.0
> IMM32.dll   	10.0.17134.1
> SETUPAPI.dll	10.0.17134.1
> libgdk_pixbuf-2.0-0.dll	2.38.1.0
> libgmodule-2.0-0.dll	2.58.3.0
> libgobject-2.0-0.dll	2.58.3.0
> libgphoto2-6.dll
> libgphoto2_port-12.dll
> libGraphicsMagick-3.dll
> libIlmImf-2_3.dll
> libjpeg-8.dll
> libjson-glib-1.0-0.dll
> liblcms2-2.dll
> lua53.dll
> libpango-1.0-0.dll	1.43.0.0
> libpangocairo-1.0-0.dll	1.43.0.0
> libpng16-16.dll
> libpugixml.dll
> libsecret-1-0.dll
> libsoup-2.4-1.dll
> libsqlite3-0.dll
> libtiff-5.dll
> zlib1.dll
> MSIMG32.dll 	10.0.17134.1
> libfontconfig-1.dll
> libfreetype-6.dll	2.10.0.0
> libpixman-1-0.dll
> mgwhelp.dll 	0.8.2.0
> VERSION.dll 	10.0.17134.1
> libexpat-1.dll
> dwmapi.dll  	10.0.17134.1
> WINMM.dll   	10.0.17134.1
> libcairo-gobject-2.dll
> libepoxy-0.dll
> libpangowin32-1.0-0.dll	1.43.0.0
> gdiplus.dll 	10.0.17134.950
> libffi-6.dll
> libexif-12.dll
> libltdl-7.dll
> libsystre-0.dll
> libbz2-1.dll
> libHalf-2_3.dll
> libIex-2_3.dll
> libIlmThread-2_3.dll
> libImath-2_3.dll
> libthai-0.dll
> libpangoft2-1.0-0.dll	1.43.0.0
> libgcrypt-20.dll	1.8.4.17417
> libpsl-5.dll
> liblzma-5.dll	5.2.4.0
> libzstd.dll
> libharfbuzz-0.dll
> dbghelp.dll 	10.0.17134.1
> WINMMBASE.dll	10.0.17134.1
> USP10.dll   	10.0.17134.1
> libtre-5.dll
> libdatrie-1.dll
> libidn2-0.dll
> DWrite.dll  	10.0.17134.885
> libgraphite2.dll
> dbgcore.DLL 	10.0.17134.1
> libgomp-1.dll
> libgio-2.0-0.dll	2.58.3.0
> libgtk-3-0.dll	3.24.5.0
> comdlg32.dll	10.0.17134.1
> libopenjp2-7.dll
> librsvg-2-2.dll
> libxml2-2.dll
> libfribidi-0.dll
> libgpg-error-0.dll	1.36.0.0
> libunistring-2.dll	0.9.10.0
> DNSAPI.dll  	10.0.17134.915
> NSI.dll     	10.0.17134.1
> IPHLPAPI.DLL	10.0.17134.1
> COMCTL32.dll	6.10.17134.858
> WINSPOOL.DRV	10.0.17134.753
> libatk-1.0-0.dll	2.30.0.0
> PROPSYS.dll 	7.0.17134.619
> OLEAUT32.dll	10.0.17134.950
> bcrypt.dll  	10.0.17134.885
> libcroco-0.6-3.dll
> CRYPTSP.dll 	10.0.17134.1
> rsaenh.dll  	10.0.17134.254
> CRYPTBASE.dll	10.0.17134.1
> uxtheme.dll 	10.0.17134.1
> clbcatq.dll 	2001.12.10941.16384
> mswsock.dll 	10.0.17134.1
> rasadhlp.dll	10.0.17134.1
> fwpuclnt.dll	10.0.17134.1
> MSCTF.dll   	10.0.17134.950
> DEVOBJ.dll  	10.0.17134.1
> WINTRUST.dll	10.0.17134.556
> MSASN1.dll  	10.0.17134.1
> CRYPT32.dll 	10.0.17134.1
> OpenCL.dll  	2.2.1.0
> IntelOpenCL64.dll	25.20.100.6326
> dxgi.dll    	10.0.17134.112
> intelocl64.dll	6.6.0.359
> task_executor64.dll	6.6.0.359
> OPENGL32.dll	10.0.17134.1
> GLU32.dll   	10.0.17134.1
> cpu_device64.dll	6.6.0.359
> nvopencl.dll	25.21.14.1634
> nvfatbinaryLoader.dll	25.21.14.1634
> nvapi64.dll 	25.21.14.1634
> IntelOpenCL64.dll	21.20.16.4534
> igdrcl64.dll	21.20.16.4534
> igdfcl64.dll	21.20.16.4534
> igdmcl64.dll	21.20.16.4534
> igc64.dll   	21.20.16.4534
> nvcompiler.dll	25.21.14.1634
> winhttp.dll 	10.0.17134.590
> IconCodecService.dll	10.0.17134.1
> WindowsCodecs.dll	10.0.17134.345
> libpixbufloader-png.dll
> mscms.dll   	10.0.17134.1
> USERENV.dll 	10.0.17134.829
> ColorAdapterClient.dll	10.0.17134.1
> icm32.dll   	10.0.17134.1
> TextInputFramework.dll	10.0.17134.858
> CoreUIComponents.dll	10.0.17134.376
> CoreMessaging.dll	10.0.17134.471
> ntmarta.dll 	10.0.17134.1
> wintypes.dll	10.0.17134.523
> libdarkroom.dll
> libknight.dll
> liblighttable.dll
> libmap.dll
> libosmgpsmap-1.0-1.dll
> libslideshow.dll
> libtethering.dll
> libcopy.dll
> libexr.dll
> libj2k.dll
> libjpeg.dll
> libpdf.dll
> libpfm.dll
> libpng.dll
> libppm.dll
> libtiff.dll
> libwebp.dll
> libwebp-7.dll
> libdisk.dll
> libemail.dll
> libfacebook.dll
> libcurl-4.dll
> WLDAP32.dll 	10.0.17134.1
> libbrotlidec.dll
> libnghttp2-14.dll
> libcrypto-1_1-x64.dll	1.1.1.2
> libssl-1_1-x64.dll	1.1.1.2
> libbrotlicommon.dll
> secur32.dll 	10.0.17134.1
> SSPICLI.DLL 	10.0.17134.376
> libflickr.dll
> libflickcurl-1.dll
> libgallery.dll
> liblatex.dll
> libpicasa.dll
> libpiwigo.dll
> libashift.dll
> libatrous.dll
> libbasecurve.dll
> libbilat.dll
> libbilateral.dll
> libbloom.dll
> libborders.dll
> libcacorrect.dll
> libchannelmixer.dll
> libclahe.dll
> libclipping.dll
> libcolisa.dll
> libcolorbalance.dll
> libcolorchecker.dll
> libcolorcontrast.dll
> libcolorcorrection.dll
> libcolorin.dll
> libcolorize.dll
> libcolormapping.dll
> libcolorout.dll
> libcolorreconstruct.dll
> libcolortransfer.dll
> libcolorzones.dll
> libdefringe.dll
> libdemosaic.dll
> libdenoiseprofile.dll
> libdither.dll
> libequalizer.dll
> libexposure.dll
> libfilmic.dll
> libfinalscale.dll
> libflip.dll
> libgamma.dll
> libglobaltonemap.dll
> libgraduatednd.dll
> libgrain.dll
> libhazeremoval.dll
> libhighlights.dll
> libhighpass.dll
> libhotpixels.dll
> libinvert.dll
> liblens.dll
> liblensfun.dll
> liblevels.dll
> libliquify.dll
> liblowlight.dll
> liblowpass.dll
> libmonochrome.dll
> libnlmeans.dll
> liboverexposed.dll
> libprofile_gamma.dll
> librawdenoise.dll
> librawoverexposed.dll
> librawprepare.dll
> librelight.dll
> libretouch.dll
> librotatepixels.dll
> libscalepixels.dll
> libshadhi.dll
> libsharpen.dll
> libsoften.dll
> libsplittoning.dll
> libspots.dll
> libtemperature.dll
> libtonecurve.dll
> libtonemap.dll
> libvelvia.dll
> libvibrance.dll
> libvignette.dll
> libwatermark.dll
> libzonesystem.dll
> libbackgroundjobs.dll
> libcamera.dll
> libcollect.dll
> libcolorlabels.dll
> libcolorpicker.dll
> libcopy_history.dll
> libdarktable_label.dll
> libduplicate.dll
> libexport.dll
> libfilmstrip.dll
> libfilter.dll
> libgeotagging.dll
> libglobal_toolbox.dll
> libhinter.dll
> libhistogram.dll
> libhistory.dll
> libimage.dll
> libimport.dll
> liblighttable_mode.dll
> liblive_view.dll
> liblocation.dll
> libmap_settings.dll
> libmasks.dll
> libmetadata.dll
> libmetadata_view.dll
> libmodulegroups.dll
> libmodulelist.dll
> libmodule_toolbox.dll
> libnavigation.dll
> libratings.dll
> librecentcollect.dll
> libselect.dll
> libsession.dll
> libsnapshots.dll
> libstyles.dll
> libtagging.dll
> libviewswitcher.dll
> libview_toolbox.dll
> libpixbufloader-svg.dll
> libpixbufloader-jpeg.dll
> Ninput.dll  	10.0.17134.441
> 
> Windows 10.0.17134
> DrMingw 0.8.2
> 

[darktable_bt_RINT6Z.txt](https://github.com/darktable-org/darktable/files/3520424/darktable_bt_RINT6Z.txt)

How can I fix this ?

Thank you !

**Comment by peterbud** [comment]
Please run an OpenCL test as described here:
https://www.darktable.org/about/faq/#faq-windows-opencl

and share the results.

**Comment by pratheeshp007** [comment]
@peterbud I am also facing a similar issue, I had updated windows recently, I think this happened after that, i ran the opencl test. I am getting below output and the popup saying exception
```
0.046903 [opencl_init] opencl related configuration options:
0.046903 [opencl_init]
0.046903 [opencl_init] opencl: 0
0.046903 [opencl_init] opencl_library: ''
0.062528 [opencl_init] opencl_memory_requirement: 768
0.062528 [opencl_init] opencl_memory_headroom: 300
0.062528 [opencl_init] opencl_device_priority: '*/!0,*/*/*'
0.062528 [opencl_init] opencl_mandatory_timeout: 200
0.062528 [opencl_init] opencl_size_roundup: 16
0.062528 [opencl_init] opencl_async_pixelpipe: 0
0.078137 [opencl_init] opencl_synch_cache: 0
0.078137 [opencl_init] opencl_number_event_handles: 25
0.078137 [opencl_init] opencl_micro_nap: 1000
0.078137 [opencl_init] opencl_use_pinned_memory: 0
0.078137 [opencl_init] opencl_use_cpu_devices: 0
0.078137 [opencl_init] opencl_avoid_atomics: 0
0.078137 [opencl_init]
0.078137 [opencl_init] found opencl runtime library 'OpenCL.dll'
0.093732 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
```

content of the exception
```
this is darktable 2.6.2 reporting an exception:

-------------------

Error occurred on Monday, August 26, 2019 at 00:06:17.

darktable.exe caused an Access Violation at location 00007FF97306EE5F in module igdrclneo64.dll Reading from location 0000000000000038.

AddrPC           Params
00007FF97306EE5F 00000000008042A0 000000000061E340 0000000000000000  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF97306F0E5 00000000045C66C0 00000000071742A8 000000000061E3A9  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF972EECF7F 0000000000000000 0000000000000000 0000000000000000  igdrclneo64.dll!0x7ff90001cf7f
00007FF972EECEEF 0000000008664A90 0000000008664B20 0000000000000000  igdrclneo64.dll!0x7ff90001ceef
00007FF9730470D0 0000000007100F10 0000000007100D20 0000000000000002  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF973046E48 0000000000000003 00000000000003F0 0000000008664A90  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF973046F3C 00007FF973349480 0000000008664A90 00000000071743E0  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF972EEC33B 00000000071742F0 00007FF973349480 00000000071742F0  igdrclneo64.dll!0x7ff90001c33b
00007FF972F030C5 00000000007F3240 00000000071742F0 0000000000000001  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FF972F3D564 0000000000000001 0000000000000001 00000000071742F0  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FF972F3CF3D 0000D4FD6452C484 0000000000000000 0000000000000000  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FF972EED10E 0000000008380EB0 0000000000000000 0000000000000000  igdrclneo64.dll!clGetPlatformIDs
00007FF972EF41E9 0000000008380ED0 00007FF972EF3C80 0000000008380EB0  igdrclneo64.dll!clEnqueueTask
00007FF9736032B5 00007FF9A820E360 0000000000000000 0000000000000000  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FF9735CC85B 00007FF9735C48A9 00007FF9A82188E8 00007FF9735C0000  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FF9A82010FC 0000000000000000 00007FF9A82188E8 0000000000000000  OpenCL.dll!0x7ff9000010fc
00007FF9A8203477 0000000000000000 0000000000000000 000000006383079C  OpenCL.dll!clWaitForEvents
00007FF9B080B05F 00000000041EECE0 000000006389DB20 000000000061F25C  ntdll.dll!RtlRunOnceExecuteOnce
00007FF9ADA222DB 0000000000000002 0000000000000014 00000000041EECE0  KERNELBASE.dll!InitOnceExecuteOnce
00007FF9A8202D8C 00000000042274C0 00000000041EECE0 00000000056A3FF0  OpenCL.dll!clGetPlatformIDs
00000000636449EF 0000000000000000 0000000000000046 0000000000000000  libdarktable.dll!dt_opencl_init  [D:/build/darktable/src/common/opencl.c @ 601]
00000000635E2410 00007FF900000001 0000000002E0F280 00007FF900000001  libdarktable.dll!dt_init  [D:/build/darktable/src/common/darktable.c @ 889]
00000000004030B5 000000000000005A 0000000000000000 00000000004016A0  darktable.exe!main  [D:/build/darktable/src/main.c @ 82]
0000000000401605 000000000000005A 0000000000000000 0000000000408610  darktable.exe!wmain  [D:/build/darktable/src/win/main_wrapper.h @ 15]
00000000004013FE 0000000000000000 0000000000000000 0000000000000000  darktable.exe!__tmainCRTStartup  [C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 334]
000000000040153B 0000000000000000 0000000000000000 0000000000000000  darktable.exe!mainCRTStartup  [C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 223]
00007FF9AE8C7BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF9B086CE71 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	2.6.2.0
ntdll.dll   	10.0.18362.267
KERNEL32.DLL	10.0.18362.86
KERNELBASE.dll	10.0.18362.267
msvcrt.dll  	7.0.18362.1
libintl-8.dll	0.19.8.0
libglib-2.0-0.dll	2.58.3.0
libdarktable.dll
ADVAPI32.dll	10.0.18362.1
GDI32.dll   	10.0.18362.1
sechost.dll 	10.0.18362.267
ole32.dll   	10.0.18362.113
win32u.dll  	10.0.18362.295
RPCRT4.dll  	10.0.18362.1
gdi32full.dll	10.0.18362.295
combase.dll 	10.0.18362.267
ucrtbase.dll	10.0.18362.267
msvcp_win.dll	10.0.18362.267
bcryptPrimitives.dll	10.0.18362.295
USER32.dll  	10.0.18362.267
libiconv-2.dll	1.15.0.0
PSAPI.DLL   	10.0.18362.1
SHELL32.dll 	10.0.18362.295
cfgmgr32.dll	10.0.18362.1
shcore.dll  	10.0.18362.1
libwinpthread-1.dll	1.0.0.0
windows.storage.dll	10.0.18362.295
libgcc_s_seh-1.dll
libstdc++-6.dll
profapi.dll 	10.0.18362.1
powrprof.dll	10.0.18362.1
UMPDC.dll
exchndl.dll 	0.8.2.0
shlwapi.dll 	10.0.18362.1
libcairo-2.dll
kernel.appcore.dll	10.0.18362.1
libexiv2.dll
cryptsp.dll 	10.0.18362.1
WS2_32.dll  	10.0.18362.1
libgdk-3-0.dll	3.24.5.0
libgdk_pixbuf-2.0-0.dll	2.38.1.0
IMM32.dll   	10.0.18362.1
libgmodule-2.0-0.dll	2.58.3.0
SETUPAPI.dll	10.0.18362.1
bcrypt.dll  	10.0.18362.267
libgphoto2-6.dll
libgobject-2.0-0.dll	2.58.3.0
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.5.0
libIlmImf-2_3.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
lua53.dll
comdlg32.dll	10.0.18362.1
libpangocairo-1.0-0.dll	1.43.0.0
libpango-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
libsoup-2.4-1.dll
libtiff-5.dll
libsecret-1-0.dll
zlib1.dll
mgwhelp.dll 	0.8.2.0
MSIMG32.dll 	10.0.18362.175
libfontconfig-1.dll
VERSION.dll 	10.0.18362.1
libfreetype-6.dll	2.10.0.0
libpixman-1-0.dll
libpcre-1.dll
libexpat-1.dll
gdiplus.dll 	10.0.18362.295
dwmapi.dll  	10.0.18362.267
libcairo-gobject-2.dll
WINMM.dll   	10.0.18362.1
libepoxy-0.dll
libexif-12.dll
libltdl-7.dll
libpangowin32-1.0-0.dll	1.43.0.0
libffi-6.dll
libbz2-1.dll
libHalf-2_3.dll
libIex-2_3.dll
libIlmThread-2_3.dll
libImath-2_3.dll
COMCTL32.dll	6.10.18362.295
libatk-1.0-0.dll	2.30.0.0
WINSPOOL.DRV	10.0.18362.267
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.43.0.0
liblzma-5.dll	5.2.4.0
libzstd.dll
libpsl-5.dll
libgcrypt-20.dll	1.8.4.17417
dbghelp.dll 	10.0.18362.1
WINMMBASE.dll	10.0.18362.1
USP10.dll   	10.0.18362.1
PROPSYS.dll 	7.0.18362.267
IPHLPAPI.DLL	10.0.18362.1
DWrite.dll  	10.0.18362.267
OLEAUT32.dll	10.0.18362.295
libgraphite2.dll
libidn2-0.dll
dbgcore.DLL 	10.0.18362.1
libgomp-1.dll
libgio-2.0-0.dll	2.58.3.0
libgphoto2_port-12.dll
libopenjp2-7.dll
librsvg-2-2.dll
libsqlite3-0.dll
libfribidi-0.dll
libxml2-2.dll
libthai-0.dll
libunistring-2.dll	0.9.10.0
libgpg-error-0.dll	1.36.0.0
libsystre-0.dll
DNSAPI.dll  	10.0.18362.267
NSI.dll     	10.0.18362.1
libdatrie-1.dll
libtre-5.dll
libcroco-0.6-3.dll
rsaenh.dll  	10.0.18362.1
CRYPTBASE.dll	10.0.18362.1
uxtheme.dll 	10.0.18362.1
clbcatq.dll 	2001.12.10941.16384
mswsock.dll 	10.0.18362.1
rasadhlp.dll	10.0.18362.1
fwpuclnt.dll	10.0.18362.207
MSCTF.dll   	10.0.18362.295
DEVOBJ.dll  	10.0.18362.1
WINTRUST.dll	10.0.18362.145
MSASN1.dll  	10.0.18362.1
CRYPT32.dll 	10.0.18362.1
Wintab32.dll	1.0.5.8
HID.DLL     	10.0.18362.1
WTSAPI32.dll	10.0.18362.1
MPR.dll     	10.0.18362.1
ISD_Tablet.dll	7.6.1.22
MSVCP140.dll	14.15.26706.0
VCRUNTIME140.dll	14.15.26706.0
IconCodecService.dll	10.0.18362.1
WindowsCodecs.dll	10.0.18362.1
OpenCL.dll  	2.2.1.0
IntelOpenCL64.dll	25.20.100.6793
dxgi.dll    	10.0.18362.267
dxcore.dll  	10.0.18362.1
intelocl64.dll	7.6.0.228
task_executor64.dll	7.6.0.228
cpu_device64.dll	7.6.0.228
igdrcl64.dll
igdgmm64.dll	25.20.100.6793
igdfcl64.dll	25.20.100.6793
igc64.dll   	25.20.100.6793
IntelOpenCL64.dll	23.20.16.4973
igdrclneo64.dll
Oleacc.dll  	7.2.18362.1
TextInputFramework.dll	10.0.18362.267
CoreUIComponents.dll	10.0.18362.207
CoreMessaging.dll	10.0.18362.1
ntmarta.dll 	10.0.18362.1
wintypes.dll	10.0.18362.267
iertutil.dll	11.0.18362.267

Windows 10.0.18362
DrMingw 0.8.2
```

**Comment by peterbud** [comment]
@pratheeshp007 : As you see in the trace those crashes are in the driver, so if that's the latest video card driver there is not much you can do, bu to disable OpenCL - this is another example of Intel OpenCL not working.

**Comment by peterbud** [comment]
I'd suggest to close this case - when @leapb share more information we can continue the discussion here.

**Comment by johnny-bit** [comment]
Yeah, windows opencl driver issue - see https://github.com/darktable-org/darktable/issues/5988#issuecomment-674581664 for causes and workaround possible here: https://github.com/darktable-org/darktable/issues/6492#issuecomment-706512073
