### ISSUE TITLE
Mix control on equalizer module changes frequency in some cases.

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#2873]
**Describe the bug**

With some settings I've been using lately, the 'mix' control on the equalizer module shifts the frequency (x axis) of the nodes when adjusted,

**To Reproduce**

Apply the attached dtstyle to an image, then lower the equalizers mix control.

[equalizer_mix_test.dtstyle.txt](https://github.com/darktable-org/darktable/files/3522437/equalizer_mix_test.dtstyle.txt)

**Expected behavior**

According to the manual, this control adjusts the amplitude (y axis) of the settings; I would expect it to do this, and produce something more of a "blend" effect when lowered, without shifting the nodes on the x axis and substantially changing the nature of the equalization.

**Screenshots**

Original settings:
![screenshot-1566331739](https://user-images.githubusercontent.com/4522189/63380792-252abf00-c34c-11e9-9bab-325467864241.png)

After lowering mix control:
![screenshot-1566331809](https://user-images.githubusercontent.com/4522189/63380793-252abf00-c34c-11e9-92f1-c915b33bc2c6.png)

**Platform (please complete the following information):**
 - OS: Slackware Linux
 - Version 2.7.0+1634

**Additional context**

Changes to the behavior of this control .shouldn't require any versioning control, since it isn't a saved parameter, only a UI "convenience widget"...

**Comment by junkyardsparkle** [comment]
There seems to be a consensus in #3095 for re-implementing this control, but since that issue has been closed, I'll keep this one open for now.

**Comment by elstoc** [comment]
The mix slider has now been incorporated into the stored module parameters as part of #8219. @junkyardsparkle: please can you retest on latest master.

**Comment by junkyardsparkle** [comment]
> The mix slider has now been incorporated into the stored module  parameters as part of #8219

Nice! I haven't been following development lately, thanks for the heads up. I only had time for a quick test, but from what I can tell, the issue described here is actually *worse* now. The old mix control would only mangle the x-position of the nodes when pushed to a certain extreme, but now it appears that *any* movement of the mix control immediately and proportionally shifts the x-positions. My expectation would (still) be for it to only change amplitude (y-positions).

**Comment by junkyardsparkle** [comment]
On further testing, I notice that the x-shift doesn't seem to happen to nodes who's x-position was never changed from default. If you reset the module, then pull the nodes down/up alternately without changing their original frequency setting, the mix control works as expected, all the way to complete inversion. However, after sliding some of the nodes over to the right, the mix control then causes the shifting on those nodes (shifting them to the left as the control is lowered, even past the zero point).

**Comment by junkyardsparkle** [comment]
I just tried the same things described in my last post on 3.4.1, and it seems that the behavior is actually the same (or at least more similar than I remembered), so it looks like the new mix control implementation didn't really impact this issue.

**Comment by jenshannoschwalm** [comment]
@junkyardsparkle is this issue still valid?

**Comment by jenshannoschwalm** [comment]
Closing as not under investigation by OP any more
