### ISSUE TITLE
[UI Feature] Highlight currently loaded image

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#2876]
When using Darkroom edit view, it is possible to select images in bottom image carousel. Currently in latest GIT, there is no way to know which image is currently loaded into the editor. With many images that are similar it can be hard / impossible to tell which image is loaded.

This can cause issues if a user is pasting image attributes from one image, then selecting the currently loaded image to load the attributes into.

Having an icon placed on the image that is loaded in the carousel would make it very easy to tell which image is currently loaded, or alternatively a highlight shadow, or highlight background for that image slide in the carousel.

**Comment by aurelienpierre** [comment]
bottom image carousel == film strip view underneath the main preview, just to be clear.

**Comment by alcomposer** [comment]
Yes. Thanks @aurelienpierre

**Comment by AlicVB** [comment]
Hmm, if iirc, I've worked on that part and it should be the case (some sort of highlight) in master. I'll have a look once fully back home, in a week or so...
Just to know,
- this is with current master ?
- which theme do you use ?
- is it the same with other themes as well ?

Thanks

**Comment by alcomposer** [comment]
* this is with current master ?
**Yes**  building using `./build.sh` then installing, running on Arch Linux
Darktable verson: 
2.7.0+1640~gb82d08d57

* which theme do you use ?
**Darktable** (but just noticed Darktable-elegent which looks lovely)

* is it the same with other themes as well ?
**Yes**

![Filmstrip View](https://user-images.githubusercontent.com/12004932/63581623-a7c6af00-c5d6-11e9-9cb1-258c5aa1fc18.png)

**Comment by Nilvus** [comment]
@AlicVB : highlight works as you can see on @alcomposer screen capture. The only problem is if you just select another image (without unloading it, for example for history copying purpose), the loaded image highlight became the last selected image, not the loaded one. So it indeed be great to have a way to show permanently which image is loaded independantly than the highlighted one (and we have to keep the possibility to see the highlighted one of course). The icon idea suggested seems to be a great way to do that.

**Comment by alcomposer** [comment]
@Nilvus anything that would show clearly which image is currently loaded would be fantastic. 

In my screenshot one can clearly see that I have selected a different image than what is loaded, but there are two very similar images to what is loaded. From a small thumbnail, (even large) it can be hard to tell which is the photo currently loaded. (Small facial expressions or even identical photos)

Even a upwards pointing triangle would clearly show that the image is currently loaded (placed at the top of the film strip thumbnail). That way an image can be loaded & selected at the same time without introducing added complexity. (Added complexity such as an additonal highlight color background)

**Comment by AlicVB** [comment]
ok, got it !
The simplest way to fix this is to use borders, as @alcomposer proposal. I'm not fund of adding some icons, because there's already lot of icons that can be show on thumbnails (and it'll need lot more work ;) )
For culling, this is already the case (borders are drawn only for shown images, only background indicate the selection)

I'll try to do it asap

**Comment by AlicVB** [comment]
done. You can test PR #2894

**Comment by Nilvus** [comment]
@AlicVB : indeed, you're right, simple thin borders are the simplest and lightest way to do that.

**Comment by alcomposer** [comment]
@AlicVB Just tested, awesome!  :+1:
