### ISSUE TITLE
Esc key to switch from the darkroom to the lighttable

### ISSUE THREAD

**Issue by fabienengels** [darktable-org/darktable#2877]
I opened this issue but really as a suggestion. I realize many times, I hit Esc hopping to switch back from the darkroom to the lightroom.

It could be nice to be able to add the Esc key to switch from the darkroom to the lighttable, I know I can still do it by simply hitting the l key but Esc feels more natural and easier to hit without thinking.

**Comment by jakubfi** [comment]
Key bindings can be changed in darktable preferences (shortcuts tab). You can change shortcut for "global/lighttable view" from "L" to "Escape" to have it work your preferred way. F11 will still toggle fullscreen on/off.

**Comment by fabienengels** [comment]
I know but I still think it can be a good thing on the ergonomic level. Most of people hold their mouse with the right hand and press the L key with the same hand. Searching the L with the left hand feels unnatural.

The idea is to be able to switch quickly between the lighttable and the darkroom with the left hand while the right hand can stay on the mouse. It seems maybe overthought but when you retouch a large series of photos like a wedding, in the end that makes a difference.

And as you said, F11 already toggle the fullscreen as you can expect as a standard behavior from a software (vlc, firefox) and as you don't toggle screen every 5 minutes, you don't need a very accessible key for that. So in the end, I think Esc could be used for an action used more often.

**Comment by Nilvus** [comment]
Personnaly, I disagree with you. A lot of shortcuts are choosed using the first letter of what you want to activate, here 'l' for 'lighttable'. I find it quite easy to memorize and if you change the default behaviour on this, you cut this logic and coherence. Searching a letter feels natural if you know your keyboard (that needs of course practice but most of the time, I don't look at the keyboard to use a letter).

Default behaviour is coherent and logic so don't need to be changed. And that's for what you like (different than default behaviour) that you have the possibility to change shortcut.

So changing by default this would be a bad thing. Another reason is that this is by default since many years, so most users already have their habits (default one or custom ones).

**Comment by jakubfi** [comment]
:+1: @Nilvus, although I agree with @fabienengels on one thing: using Esc for switching to a windowed mode by default is a strange choice, especially when F11 already toggles between fullscreen/windowed. Such a nice key, such a waste. ;-) But then again, user has the option to bind it to something more useful.

**Comment by fabienengels** [comment]
@Nilvus  I should have been more clear, my idea is not to remove the L shortcut. Let's say the idea is to add a key allowing to switch between the lighttable and the darkroom (where 90% where users spent their time in the end).

For example, blender have something similar, you can quickly switch between normal mode and editing mode by pressing the TAB key.

And changing the shortcut won't work either, I would be able to go to one mode but not switching between them but here, it's my fault, next time I'll take more time to explain what I'm looking for.

**Comment by Nilvus** [comment]
> @Nilvus I should have been more clear, my idea is not to remove the L shortcut. Let's say the idea is to add a key allowing to switch between the lighttable and the darkroom (where 90% where users spent their time in the end).
> 
> For example, blender have something similar, you can quickly switch between normal mode and editing mode by pressing the TAB key.
> 
> And changing the shortcut won't work either, I would be able to go to one mode but not switching between them but here, it's my fault, next time I'll take more time to explain what I'm looking for.

So if I understand correctly, you suggest to add a shortcut for same thing, so having both actual 'l' shortcut and add 'Esc' shortcut. Why not, if we keep the actual shortcut, I don't care if we have another shortcut or not. I will let a developer answer you if this is possible or not (If I don't make mistake, shortcut are related to GTK library, I don't know if it's possible to add 2 shortcuts for same thing with this library).

**Comment by darkelectron** [comment]
Perhaps the shortcut `.` is what you could use. It switches back and forth between lighttable and darkroom.

**Comment by dterrahe** [comment]
As pointed out by @darkelectron there is a shortcut key for _global/switch view_ which toggles between darktable and lightroom. It can be reassigned to Esc if you want (although Esc by default has a different function). This should get you the configuration that you want.

Closing this issue; please reopen if there is an aspect of your request that is not covered by this existing functionality.
