### ISSUE TITLE
Short cut key to to move modules up or down.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2882]
**Is your feature request related to a problem? Please describe.**
As an example, I created a style for luminosity masks using the tone curve module and parametric masks.
Now based on pipeline these masks aren't always available for use and I wanted to move a module around to be able to use the mask. 

**Describe the solution you'd like**
Enable configuration of a short-cut key to move modules up or down OR enable drag / drop of modules to change order.
The above plays around with the pipeline, which is not a good thing, so alternatively have a raster mask manager that can be used to select the parametric mask.

**Describe alternatives you've considered**
Currently, doing the menu-driven move up or down.

**Comment by MStraeten** [comment]
Drag and  drop is possible using ctrl + shift drag

**Comment by chhil** [comment]
Duh.... thank you.
