### ISSUE TITLE
Tamron lens not identified correctly, thus lens correction does not match

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [darktable-org/darktable#2886]
**Describe the bug**
Whenever I import a NEF shot with the older Tamron 70-200mm (sometimes retronymed the G1 lens) the lens correction can't figure out what lens it is.

**To Reproduce**
1. Import NEF file shot with the 70-200 G1
2. Click on Lens Correction
3. Enable lens correction
4. See lens being identified as `Tamron SP AF 70-200mm F/2.8 Di VC USD` that can't be matched to `Tamron SP 70-200mm f/2.8 Di VC USD A009` in the database. Selecting the right lens from the dropdown applies corrections successfully.

**Expected behavior**
I expected lens correction to pick the correct lens from the database, as it does with all my other Nikkor lenses.

**Platform (please complete the following information):**
 - OS: Arch Linux
 - Version: 2.6.x

**Additional context**

exiftool on the LensID says it is `Tamron SP 70-200mm f/2.8 Di VC USD (A009)` thus matching more of the lensfun database than the darktable identifier. Initially reported as https://github.com/lensfun/lensfun/issues/957 (which includes a link to a NEF file) but it seems the database matches the EXIF data so I assume the issue is somewhere on the darktable side (generating an `AF` bit that prevents matching).

**Comment by Nilvus** [comment]
Identifying is made by exiv2 library, so maybe you have to see on that side. That's probably not a darktable issue as darktable only use exiv2 and lensfun to identify camera and lenses.

**Comment by Leonidas-from-XIV** [comment]
Haha, okay, looks like I'm not particularly lucky in filing my bug reports to the correct places.

I'll try to reproduce with the exif2 CLI tooling and report there, thanks!

**Comment by Nilvus** [comment]
> Haha, okay, looks like I'm not particularly lucky in filing my bug reports to the correct places. I'll try to reproduce with the exif2 CLI tooling and report there, thanks!

Don't worry, it's easier to know where to post when you know which library are used by darktable.
Think of closing this issue.

**Comment by Leonidas-from-XIV** [comment]
I opened a PR but looking at the source code it looks like all lenses have `AF` in the name, so it might well be that none of the Tamron autofocus lens names match (I don't have any more Tamrons to test). In which case they might need to be all renamed in exiv2 or darktable might need to be a bit more lenient and ignore these bits. I seem to remember that it already does that to some extent.

**Comment by alcomposer** [comment]
I had a similar issue with a Tamron 24-70 G2. Running:
`lensfun-update-data` 
fixed it for me.

**Comment by Leonidas-from-XIV** [comment]
@alcomposer That won't help since lensfun identifies it as `Tamron SP 70-200mm f/2.8 Di VC USD A009`/`Tamron SP 70-200mm f/2.8 Di VC USD` and exiv2 as `Tamron SP AF 70-200mm F/2.8 Di VC USD` and these don't match.

You can find the relevant entry in lensfun: https://github.com/lensfun/lensfun/blob/4ad84940108eb50939fc9ccff82784c497597e17/data/db/slr-tamron.xml#L1245-L1246

And the analogous entry in Exiv2: https://github.com/Exiv2/exiv2/blob/98e63e4bb4d78ee9dec2ba9dca2aa1785278e51c/src/nikonmn_int.cpp#L2368

**Comment by jamesbo13** [comment]
Noticed this for my Tamron AF 16-300mm F/3.5-6.3 Di II VC PZD ... exiv2 reports the AF, lensfun does not so no match is found.

Opened an issue with lensfun here: https://github.com/lensfun/lensfun/issues/1110

**Comment by aurelienpierre** [comment]
Upstream bug. Closing.
