### ISSUE TITLE
Whitebalance presets for Panasonic DMC-G8/81/85 and additional noise profile

### ISSUE THREAD

**Issue by asl5757** [darktable-org/darktable#2887]
please find included a few additional data chunks to support Panasonic DMC-G8 / DMC-G81 / DMC-G85:

1. patch for noiseprofiles.json: coefficients for ISO 100. These are extrapolated from higher ISO values. This is much better than landing on the generic profile.
2. white balance data for the G81 (should be valid for G8 / G80 and G85 too).
3. wb_extract.pl with enhancements to work with Panasonic cameras.
4. make & model exif data from my camera (for reference only)

best regards, Andreas

**Comment by asl5757** [comment]
[Data_Panasonic_DMC-G8x.zip](https://github.com/darktable-org/darktable/files/3538334/Data_Panasonic_DMC-G8x.zip)

here is the file as zip (tgz was not accepted)

**Comment by junkyardsparkle** [comment]
I wonder about using extrapolated values for ISO 100... I know that my Olympus cameras, for instance, produce exactly the same RAW for "extended" ISO <200 as it does for ISO 200... there's only a difference in the camera JPEG rendering (pulled down a stop). Is this also the case for this camera?

Anyway, if it does make more sense to use extrapolated values (rather than duplicating ISO 200) for these "fake" ISO settings, probably some of the existing Olympus profiles should have their ISO 100 values adjusted similarly.

**Comment by junkyardsparkle** [comment]
I completely agree about the importance of preventing the fallback to generic for these values, the results can be really bad, and it might not be clear to users what is happening. Maybe the best way to handle this consistently without having to worry about which cameras need this would be to leave these lines out of the profiles and let the module itself handle extrapolation for ISO values not in the profile... @rawfiner, any thoughts on this?

**Comment by rawfiner** [comment]
Sorry for the late answer
I understand the problem, but I am not sure about the solution. Would be better to redo a profiling step for the 2 lowest ISO values, because the lowest value can be half the next one, or can be identical depending on the camera

**Comment by asl5757** [comment]
Hi rawfiner,

I am working with this profile for over 1/2 a year now and it just does
what it is supposed to do. So at least I can label this with "works for
me" (TM). I use a G81.

I plotted the coefficients on a double log chart and was completely
astonished that the measured values (ISO 200 and above) follow the
linear curve (in log-log) so nicely. For the a1 coefficient the
correlation coefficient R^2 ist 0.999932 for a linear fit (in
transformed coordinates).
.. and then did a linear extrapolation from the 200/400 ISO data points
to 100 ISO.

The resulting coefficients at 100 ISO are really tiny, so the noise
correction is not really noticable. It is also not the purpose of these
coefficients to manage denoising.
The sole purpose is to avoid accidental mangling of images with the
default profile if dealing with a collection of images where some have
low and others have high ISO values.

Best regards, Andreas

Am 17.02.20 um 19:25 schrieb rawfiner:

**Comment by rawfiner** [comment]
Hi asl5757
Yes, the coefficients follow a linear curve in log-log, but unfortunately we cannot extrapolate for the extremities of the curve, as they do not always follow the linear curve.
Typically, for extended ISOs, the values are usually (not always) the same as the ones of the closest "normal" ISO.
Without actually making a profile for these values to check which hypothesis is the correct one, we cannot actually know what their values should be.
And if we make a mistake, I am concerned about the backward compatibility issues we may have latter when correcting the profile...

Maybe, a simpler solution than making a profile would be to take pictures of a uniform grey background with ISO 100, 200, 400, and then to check the variance values at 100% zoom level within denoise profiled (to have this mode you need within darktablerc to activate the "show compute variance" option). Or just send me the 3 raw files of the uniform grey background, and I can do that. That way we will actually know the relationship between ISO values, and we will be able to correctly infer the missing values from the existing ones :-)

**Comment by johnny-bit** [comment]
@asl5757 - can you provide files mentioned by rawfiner?

also - your wb looks fine. If you still have the data can you re-create them using extract_wb.py from current repo? https://github.com/darktable-org/darktable/wiki/White-balance-presets It looks like yours aren't as fine-grained as our current tool provides (if you don't have them, then no problem - those look fine as-is.

**Comment by johnny-bit** [comment]
Well, if there are no other objections I'd say this can be closed - whe have noise profiles for DMC-G8 (which is identical with G-81), but that doesn't have iso100 too...

@asl5757 - if you can provide files mentioned by rawfiner we could then have better profiles instead of interpolating :)
