### ISSUE TITLE
darktable-cli does not work with `--library :memory:`

### ISSUE THREAD

**Issue by cetra3** [darktable-org/darktable#2890]
I'd like to run multiple instances of darktable-cli at once and to do that I need to disable locking of the db per PID.

**To Reproduce**

Run the following command:

```
darktable-cli --library :memory: input output
```

You will receive the following:

```
error: can't open file :memory:
```

**Expected behavior**

The cli runs with the library in memory, which allows me to run multiple instances at once.

**Comment by amousset** [comment]
I could not reproduce this error in master, but it appears that since b3ecd74f1f (2.6.1) the data db is loaded from disk in darktable-cli, and its lock prevents starting another instance anyway.

**Comment by cetra3** [comment]
Please do not close this issue. It is still a problem

**Comment by bobobo1618** [comment]
@cetra3 as @amousset says, `darktable-cli` always loads the library from memory, so there's no reason to pass the `--library :memory:` flag.

Also as @amousset says, `darktable-cli` tries to load `data.db`, which is also locked by another instance of Darktable. That's the lock you're running into that prevents you from running multiple instances of `darktable-cli`.

You can tell `darktable-cli` not to load `data.db` (and hence not run into the lock) by using `--apply-custom-presets false`. This will allow you to run multiple instances of `darktable-cli`.

**Comment by bobobo1618** [comment]
I believe the problem here isn't `darktable-cli`'s behaviour but a problem with documentation. Perhaps we can add a short message to the command line help that says this flag enables multiple instances?
