### ISSUE TITLE
Performance Regression detected from stable release 2.6.2 to master branch 7.19

### ISSUE THREAD

**Issue by jiebinn** [darktable-org/darktable#2891]
**Describe the bug**
18-44% performance loss in darktable(option: boat, masskrug, server room) from stable release 2.6.2 to master branch 7.19.

**To Reproduce**
1.  wget https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v8.4.1.tar.gz
     cd ~
     tar zxf ~/phoronix-test-suite-8.4.1.tar.gz
     cd ~/phoronix-test-suite
     sudo ~/phoronix-test-suite/install-sh

2. phoronix-test-suite run darktable

3. Select test option boat, masskrug, server room

**Expected behavior**
We hope there is no performance regression here

**Screenshots**

**Platform (please complete the following information):**
Phoronix Test Suite v8.4.1
System Information

  PROCESSOR:          Intel Core i7-8700 @ 4.60GHz
    Core Count:       6
    Thread Count:     12
    Extensions:       SSE 4.2 + AVX2 + AVX + RDRAND + FSGSBASE
    Cache Size:       12288 KB
    Microcode:        0xb4
    Scaling Driver:   intel_pstate performance

  GRAPHICS:           Intel UHD 630 3GB
    Frequency:        1200MHz
    Vulkan:           1.1.102
    OpenCL:           OpenCL 2.1
    Display Driver:   modesetting 1.20.5
    Monitor:          DELL SE2218HV
    Screen:           1920x1080

  MOTHERBOARD:        Dell 0HVPDY
    BIOS Version:     1.5.11
    Chipset:          Intel Device a36f
    Audio:            Realtek ALC891
    Network:          Realtek RTL8111/8168/8411 + Qualcomm Atheros QCA9565 / AR9565

  MEMORY:             8192MB

  DISK:               Samsung SSD 970 EVO 250GB
    File-System:      ext4
    Mount Options:    relatime rw stripe=256
    Disk Scheduler:   MQ-DEADLINE

  OPERATING SYSTEM:   Clear Linux OS 30840
    Kernel:           5.2.9-825.native (x86_64)
    Desktop:          GNOME Shell 3.32.2
    Display Server:   X Server 1.20.5
    Compiler:         GCC 9.2.1 20190821 gcc-9-branch@274807 + Clang 8.0.0 + LLVM 8.0.0
    Security:         KPTI + usercopy/swapgs barriers and __user pointer sanitization + Full generic retpoline IBPB: conditional IBRS_FW STIBP: conditional RSB filling + SSB disabled via prctl and seccomp + PTE Inversion; VMX: conditional cache flushes SMT vulnerable

**Additional context**

**Comment by johnny-bit** [comment]
Loads of performance improvements in 3.2.1 and 3.4 though :)
