### ISSUE TITLE
Please Cut a New Release

### ISSUE THREAD

**Issue by lovesegfault** [darktable-org/darktable#2895]
Dear Maintainers,

I'd like to request for either:
1. A new release to be cut off of master
2. The fixes to the GCC 9.x compilation to be merged into 2.6.2, and for a point release to be made.
3. If neither of the above is possible, an expectation on the date for the next release.

As a Gentoo user, the current inability to build 2.6.x with GCC 9 bars me from using Darktable entirely, which means I now have hundreds of pictures I need to import from my camera waiting.

Thank you!

**Comment by ff2000** [comment]
As a Gentoo user you should know that running non-stable packages - especially toolchain - might cause issues. If you want to stay with unstable-gcc you can easily use darktable-9999 until there is a new release. Or downgrade gcc to current stable 8.3.0-r1.

**Comment by TurboGit** [comment]
@lovesegfault:

> As a Gentoo user, the current inability to build 2.6.x with GCC 9 bars me from using Darktable entirely

I'm surprised, which version is provided by Gentoo at the moment? And can't you have another version of GCC installed on this machine. I know next to zero about Gentoo, but on my GNU/Debian I have GCC 6, 7, 8 and 9 installed and ready to be used.

>  which means I now have hundreds of pictures I need to import from my camera waiting.

The new version is not ready yet. As announced on the mailing-list, a feature freeze will happen end of September and string freeze a month later. At this stage will will tag an RC0.

As you can see, we are not ready for a new version.

**Comment by lovesegfault** [comment]
@ff2000 Huh, I hadn't even realized a live ebuild of Darktable was around! Nice!

@TurboGit 
> I'm surprised, which version is provided by Gentoo at the moment? And can't you have another version of GCC installed on this machine. I know next to zero about Gentoo, but on my GNU/Debian I have GCC 6, 7, 8 and 9 installed and ready to be used.
I _can_ have distinct GCCs installed simultaneously, since it's a so-called "slotted" package. What is harder, however, is to force the ebuild to use GCC 8 as opposed to 9. 

I'll open an issue downstream asking how to force the compiler for darktable <=2.6.2 to be GCC 8.

Thanks!
