### ISSUE TITLE
Stack usage is greater than 32 kb

### ISSUE THREAD

**Issue by peterbud** [darktable-org/darktable#2896]
When compiling on Windows _debug_ version (gcc 9.2.0), I get the following error:
```
[ 87%] Linking C shared module libcolortransfer.dll
In file included from [...]/darktable/build/src/iop/introspection_colormapping.c:54:
[...]/darktable/src/iop/colormapping.c: In function 'reload_defaults':
[...]/darktable/src/iop/colormapping.c:913:6: error: stack usage is 33264 bytes [-Werror=stack-usage=]
  913 | void reload_defaults(dt_iop_module_t *module)
      |      ^~~~~~~~~~~~~~~
[...]/darktable/src/iop/colormapping.c:936:1: error: the frame size of 33216 bytes is larger than 32768 bytes [-Werror=frame-larger-than=]
  936 | }
      | ^
```

**Expected behavior**
We should be able to compile without errors even the debug version.

**Platform**
 - OS: Windows
 - Version current master branch

If I change the max stack size [here](https://github.com/darktable-org/darktable/blob/master/cmake/compiler-warnings.cmake#L42) from 32kb to 64kb it compiles without problem.

**Question**: shall we change the limit or revise the function  `reload_defaults()` in question to use less stack?

**Comment by TurboGit** [comment]
I would fix the implementation. Do you want me to have a look or do you want to do that?

**Comment by peterbud** [comment]
I'd glad if you would fix the function implementation

**Comment by TurboGit** [comment]
Ok, should be done. Can you test master? Thanks.

**Comment by peterbud** [comment]
Hi Pascal, that looks OK now, no problem with compiling
