### ISSUE TITLE
Scroll mouse wheel in monochrome module doesn't work

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#2907]
In Dt 2.7.0+1664-gc93795b73-dirty (ubuntu studio 18.04, 18.10, 19.04), and before too, the scroll mouse wheel in monochrome module doesn't work.

**Comment by amousset** [comment]
Cannot reproduce. What do you mean by "does not work"? Which component of the module are you trying to modify?

**Comment by dim162** [comment]
When you put the cursor on the color cheker board, you have a popup: "drag
and scroll mouse wheel to adjust the virtual color filter".
the drag works, the scroll... scroll the  whole panel, instead of changing
the white circle diameter.

Le ven. 13 sept. 2019 à 18:31, Alexis Mousset <notifications@github.com> a
écrit :

**Comment by hellbuster** [comment]
It may be related to this one  #2967
