### ISSUE TITLE
Provide zip binary for windows

### ISSUE THREAD

**Issue by linsui** [darktable-org/darktable#2908]
**Is your feature request related to a problem? Please describe.**
Since 2.6.0 there is no zip binary in release any more. Scoop prefer to unpack installer first but darktable installer can't be unpacked with 7zip, see https://github.com/lukesampson/scoop-extras/issues/1831 . Could you please provide a zip binary again, or for some reasons installation is nessary? Thanks!

**Describe the solution you'd like**
A zip binary or some way to unpack exe installer.

**Comment by luzpaz** [comment]
:point_up_2:

**Comment by luzpaz** [comment]
soft bump so it doesn't get closed

**Comment by valdotdev** [comment]
Is there a reason for dropping windows zipped binaries? I usually use Scoop and the Darktable scoop manifest is too old.

**Comment by TurboGit** [comment]
I don't think dt maintainers have ever provided a .zip. Maybe some other peoples have made this available.

**Comment by valdotdev** [comment]
It started in version 2.4.X though.

But anyway thanks for the reply.

**Comment by linsui** [comment]
The last release with zip binary is [2.4.4](https://github.com/darktable-org/darktable/releases/tag/release-2.4.4). The first one is [2.4.0](https://github.com/darktable-org/darktable/releases/tag/release-2.4.0) which said 
> The Windows .zip file can be used when using the installer is not possible. It lacks some features that rely on a proper installation, like integration with GIMP and tethering, but should work in general.

Thanks anyway.
