### ISSUE TITLE
base modules (enabled by default) not saved in history

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#2910]
The modules `colorin`, `colorout`, and possibly `demosaic` and others don't write an entry in history (either XMP sidecars or database) if user has not changed the default parameters. This is a problem since modules can be reordered in pipe, because it leads to undefined behaviours:

* if the default params of said modules are changed in a future version, they will be used in place of the former and will result in history breaking,
* when copy-pasting history between images, the pipe order can be randomly changed (see https://github.com/darktable-org/darktable/pull/1904#issuecomment-527615248),
* if the default pipe order is changed in a future version, these untracked modules will be automatically moved in the pipe accordingly to the new default, with no warning to users (see https://github.com/darktable-org/darktable/pull/2905#issuecomment-527652211),
* history compression needs fiddling around these special cases of modules being there in processing but not tracked in history,
* the current default pipe order is already not consistent with the legacy one (`exposure` moved after `colorin` for example), whereas no explicit rule is changing it.

Proposed solution for darktable 2.6 to 3.0 migration:
1. browse the database and force-commit untracked modules to history,
1. associate untracked modules with their pipe position in 2.6
1. update default pipe order for new edits
1. force base modules to write an entry from now on

**Comment by aurelienpierre** [comment]
Copy-paste of @parafin from IRC (for later reference):

> it seems that all modules enabled by default which are present in the history stack got there using preset system while missing ones just have default_enabled flag set to 1. I think they can be added to the history in function dt_dev_read_history_ext from src/develop/develop.c file. add some kind of loop near the end of the function to find enabled but not present in the history modules

**Comment by parafin** [comment]
I think this one is already fixed?

**Comment by jenshannoschwalm** [comment]
Yes. Turbogit committed

**Comment by TurboGit** [comment]
Yes, closing.
