### ISSUE TITLE
Right click on trackpad not being recognized in main image window in darkroom mode

### ISSUE THREAD

**Issue by rhithyn** [darktable-org/darktable#2911]
**Describe the bug**
I'm trying to use crop and rotate right-click feature on my surface book 2 trackpad but it fails to recognize any right clicks in the main image window.

**To Reproduce**
1. Go to an image in darkroom
2. Click on 'crop and rotate' and enable it
3. try to double-finger right click in the image to try to draw a line, but it ignores it altogethe

**Expected behavior**
Using two fingers on the trackpad should register a right-click and then dragging will draw a levelling line like it does with the mouse

**Platform (please complete the following information):**
 - OS: Windows 10 1809
 - Version 2.6.2

**Additional context**
Using the two finger click on the slider for angle opens up the precision slider dialog as expected.  Nothing that should be supported via right-click on the main window doesn't seem to work at all.

**Comment by jrussell88** [comment]
Me too.

**Comment by hodapp512** [comment]
Same problem here.

**Comment by chaintng** [comment]
sam problem here

**Comment by chaintng** [comment]
As a workaround, you can use Two Finger *CLICK* (Index Finger + Middle Finger)
And then, u can lift your Index Figner, and drag with middle finger.

**Comment by Nilvus** [comment]
2.6.2 is a quite old release now and I can't reproduce on master. So I close. If you can reproduce on actual master or future 3.6, we could of course consider reopening with a more precise step by step.

**Comment by plxl** [comment]
This is still an issue nearly 6 years later with version 5.2.0.
On a Macbook using the trackpad, right-clicking (two finger clicking) does not do anything.

**Comment by zisoft** [comment]
@plxl: Can you please elaborate?

My most used right-click action is to straighten an image (right-click and drag the line).
This works without issues using the two finger clicking on a Mac trackpad.

**Comment by plxl** [comment]
@zisoft It seems I may have misunderstood the use of right-clicking. I expected a context menu when right clicking photos to perform actions, but now I'm realising perhaps that just isn't a feature of the program. It would be worth implementing, however, to save a little bit of time when working with lots of photos not having to move over to the right actions bar.
