### ISSUE TITLE
History cannot be scrolled down when too long

### ISSUE THREAD

**Issue by stakaz** [darktable-org/darktable#2912]
**Describe the bug**
When the history becomes too long, there is no way to scroll down to the first item and to the "compress history stack" button.

**Expected behavior**
A scrollbar should appear or it should be possible to scroll with the mouse wheel/arrows etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/998651/64344915-ad1cf400-cfef-11e9-8cd7-ddd93928045a.png)

**Platform**
 - OS: arch linux
 - Version 2.6.2

**Comment by chhil** [comment]
@stakaz 
Use the scrollbar on the left in your image to scroll down the history list view and access the compress history. Mouse on the scroll bar lets you scroll with the mouse.

**Comment by stakaz** [comment]
Sorry, I never ever seen a scrollbar on the left. Thanks for the quick "fix" ;)
