### ISSUE TITLE
iso/f-stop/shutter-speed overlay on histogram

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2913]
The iso/f-stop/shutter-speed overlay on the lower portion of the histogram quite handy, especially when doing noise correction for stadium lights on soccer field.

It would really be nice to have that turned back on or an option where one could use it if desired.

**Comment by MStraeten** [comment]
in settings dialog:
![image](https://user-images.githubusercontent.com/39386816/64407006-8d371000-d083-11e9-962a-31bdd8e0a533.png)
switch it to top right and it's above the histogram

**Comment by ptilopteri** [comment]
I keep all the borders/panels closed except for the right side modules panel as I prefer all the visible real estate possible.  Positioning the display to top right makes it visible.  BUT also takes space from the modules display panel.

Top right is *better* than having to display and then hide an area but I still prefer and would like to have the ability to overlay that information.

tks
