### ISSUE TITLE
some keyboard shortcuts not working (zoom and preview)

### ISSUE THREAD

**Issue by jdeanefreeman** [darktable-org/darktable#2915]
**Describe the bug**

Specifically the "Z" key (in lighttable or darkroom) doesn't show a preview (or do anything).
Also the "zoom in" key ("B" or the assigned button on my Wacom Intuos Pro) does work but the "zoom out" key ("A" or assigned button) doesn't.

**To Reproduce**
1. Go to 'darkroom'
2. Click on 'Z'

**Expected behavior**
Clicking "Z" should show a fullscreen preview of the image.

**Platform (please complete the following information):**
 - OS:  Linux Mint 19.2
 - 19.2 (Cinnamon 4.2.4)

**Additional context**

**Comment by Nilvus** [comment]
Which version of darktable ? "Z" key works for lighttable but it was never intended for darkroom. So it's normal it doesn't work on darkroom (lighttable and darkroom are two different parts of darktable so functions are not totally the same). "Z" key works great on lighttable on my system.

For others keys, I don't use them. But please check before posting how it really works and to see shortcuts preferences on darktable (which one are set and to reset and apply them back if necessary).

**Comment by jdeanefreeman** [comment]
Sorry I thought I wrote the version - 2.6.2 However "Z" and the zoom keys are working now so I guess I can close this. I'm not sure what changed.

**Comment by jdeanefreeman** [comment]
Thanks for the reply!
