### ISSUE TITLE
Snapshots aren't reset when editing a new image

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#2920]
**Describe the bug**
Snapshot history from a previous edit session of a different image show up when editing a new image.

**To Reproduce**
1. Edit an image in darkroom and take a snapshot
2. Go to lightroom, select another image and enter darkroom

**Expected behavior**
Snaphot history should be blank when a new image is opened in darkroom

**Screenshots**
![image](https://user-images.githubusercontent.com/46730249/64477440-ebdab780-d171-11e9-81e4-03c907a25600.png)
The only module applied to this image was WB. The snapshot from another image is showing.

**Platform (please complete the following information):**
 - OS: ubuntu 18.04
 - Version 
![image](https://user-images.githubusercontent.com/46730249/64477471-3bb97e80-d172-11e9-844c-3cab728ed426.png)

**Additional context**
DT wasn't closed between edits

**Comment by TurboGit** [comment]
That's expected, this make it possible to compare two images.
