### ISSUE TITLE
waveform mode histogram not updated whit color picker in area mode

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2923]
**Bug**
Even if "restrict histogram to selection" is enabled, when I'm using the color picker in area mode and the histogram is in "waveform", the histogram is not updated. It works correctly in linear and logarithmic mode

**To Reproduce**
1. Enable "restrict histogram to selection" in color picker panel
2. Select an area on the image
3. change histogram mode to "waveform"

**Expected behavior**
If "restrict histogram to selection" is enabled, when I'm using the color picker in area mode, I suppose the histogram should reflect only the selected area

**Screenshots**
Attached

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - Version 19.10
- Darktable development version

![Schermata da 2019-09-08 11-40-13](https://user-images.githubusercontent.com/43513892/64486450-b5fb0900-d22d-11e9-98b7-0daa6454c223.png)

**Comment by johnny-bit** [comment]
This issue has been picked and will be worked on in #8008
