### ISSUE TITLE
Whitebalance spot area selection persists across images

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2928]
**Describe the bug**
Spot area in whitebalance module persists across images.

**To Reproduce**
1. Select pic.
2. Select white balance module and change the preset from camera to spot.
3. Drag a rectangle on the image for selection.
4. Select a different image and select white balance module and change the preset from camera to spot. Uses the same area from previous image. 
**Expected behavior**
On selection of spot from the second image the selected area from previous image should not be available. In some images based on position the image can turn black and there is no was other than to reset and start again.

**Screenshots**
Image below is first image where spot is applied and rectangle selected.
![image](https://user-images.githubusercontent.com/1119439/64587003-9691e680-d3bb-11e9-9691-abf123233352.png)
Image below is after selecting spot in second image without drawing the selection area.
![image](https://user-images.githubusercontent.com/1119439/64587056-bfb27700-d3bb-11e9-91b3-be2696e27425.png)

**Platform (please complete the following information):**
 - OS:Win 10
 - Version 2.7.0-1676 (built locally)

**Comment by jenshannoschwalm** [comment]
Hi, could you also check this with current master? If persisting, could you pass all modules used please?

**Comment by chhil** [comment]
@jenshannoschwalm Yes it persists across images in /darktable-3.0.0rc0+57~g036dd5775-win64

The one where whitebalnce was done using spot + stretched rectangle.
![image](https://user-images.githubusercontent.com/1119439/68450055-92dddd00-020f-11ea-9b24-65808c6e3f08.png)


The one where the persistence can be seen.
![image](https://user-images.githubusercontent.com/1119439/68450022-6b871000-020f-11ea-9d54-70b10028d081.png)

**Comment by junkyardsparkle** [comment]
I find that this depends on the amount of other actions after selecting the 'spot' area but before moving to another image. I can reproduce it consistently if I do nothing between selecting the area and moving to the next image.

**Comment by chhil** [comment]
Not if the next image the selected area turn the image completely black :)
