### ISSUE TITLE
Darktable inconsistently crashes in retouch module

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2937]
**Describe the bug**
Trying to remove the brush clone point app crashes.
On restart when I go that picture, the history does not have retouch but the retouch module is in the enabled state.

**To Reproduce**
1. Select retouch module.
2. Zoom into pic.
3. Select brush and activate cloning.
4. Shift + left click on pic to set clone area.
5. Left click to area you want to clone to.
6. Right click.
7. Right click again to remove it.
8. DT will crash.

If you have done multiple clones , in that case app wont crash after right click, it happens only when there is one area cloned (at least in my environment, and its inconsistent)

**Expected behavior**
Should not crash and when restarted either retouch should be in history with retouch module enabled or not be in history with retouch module disabled.
Currently, its not in history and retouch is enabled.

**Platform (please complete the following information):**
 - OS:Win 10 
 - Version 2.7.0.1687

**Additional context**
Exception log that was generated
[darktable_bt_XYHM7Z.txt](https://github.com/darktable-org/darktable/files/3608080/darktable_bt_XYHM7Z.txt)

**Comment by jenshannoschwalm** [comment]
Could you also check with master now?

**Comment by chhil** [comment]
I can't reproduce this but I don't recall what the original file I was working on that had the problem.

I think the history of the steps matter based on the stack trace in the log. Did try to set amaze in demosaic module based on trace but couldn't reproduce.

**Comment by jenshannoschwalm** [comment]
I think this is fixed. Please concider to close issue :-)
