### ISSUE TITLE
Cannot compile on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [darktable-org/darktable#2944]
**Describe the bug**
Cannot compile on Ubuntu xenial

**To Reproduce**
1. Try to build using https://github.com/probonopd/darktable/blob/05a00d4bd69197146e213583d6777575dcd488f2/.travis.yml
2. See error

**Expected behavior**
Compiles

**Screenshots**
```
-- Checking for module 'gtk+-3.0'

--   Found gtk+-3.0, version 3.18.9

CMake Error at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):

  Could NOT find GTK3 (missing: VERSION_OK) (Required is at least version

  "3.22")

Call Stack (most recent call first):

  /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)

  cmake/modules/FindGTK3.cmake:58 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)

  src/CMakeLists.txt:264 (find_package)
```

Full build log:
https://travis-ci.com/probonopd/darktable/builds/127706935

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version: Xenial 16.04

**Additional context**
Travis CI build script:
https://github.com/probonopd/darktable/blob/05a00d4bd69197146e213583d6777575dcd488f2/.travis.yml

**Comment by probonopd** [comment]
Gtk 3.22 is newer than what ships with Ubuntu xenial. Is it really needed for Darktable, or can the Darktable source code be changed so that it can be compiled on all still-supported versions of Ubuntu?

**Comment by parafin** [comment]
darktable's team reasoning is that if you're using old stable distribution you are OK with using old stable applications, so we don't have to support 5-year old versions of dependencies in new releases. If you want the latest darktable you will have to update to 18.04, or investigate other means of installing it (there are other package systems aside from native Ubuntu one, which don't use system libraries).

**Comment by probonopd** [comment]
> if you're using old stable distribution you are OK with using old stable applications

No, I know many people who want a stable, seldomly-changing operating system but still the latest applications.

> we don't have to support 5-year old versions of dependencies in new releases

it would be good if you would do that, because then everyone could run your application rather than just those users who happen to be running the latest and greatest operating system.

Would you also deny the latest darktable from Windows 8 or macOS 10.10 users?

**Comment by probonopd** [comment]
Which Ubuntu version is the oldest on that is supported? Is there any kind of policy?
