### ISSUE TITLE
Gradent mask shows curved lines instead of straight lines.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2945]
**Describe the bug**
When gradient curve is used after lens correction module, it draws curved lines for the mask. 

**To Reproduce**
1. On the image do a lens correction.
2. Select a module (tone in my case) and apply a gradient mask.
3. The lines are straight when the gradient is select but when you drop it  on the image they bend based on what lens correction has fixed.

**Expected behavior**
The mask should have straight lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/1119439/64934964-ad2cb780-d86b-11e9-89c0-415cfe510b3f.png)

**Platform (please complete the following information):**
 - OS: Win 10
 - Version 2.7.0.1709 (dev build)

**Additional context**
May be related to [#2856](https://github.com/darktable-org/darktable/issues/2856)

**Comment by AlicVB** [comment]
Yes, that's perfectly normal.
And you can note that it's the same for all drawn shapes...
You will find more explanation here : [https://darktable.gitlab.io/doc/en/blending.html#drawn_mask](url)

**Comment by TurboGit** [comment]
Indeed, that's "normal" or at least the current behavior. But I must say that in such case most users would want a straight line. After you are removed lens distortions by using this module it is common to want to use a straight gradient on the sky or sea to apply some adjustment. But this is not possible.

@AlicVB :
I had thought about this, nothing easy to fix this issue. What we would want is a way to create a gradient and say "do not apply transform/backtransform" on the corresponding mask.  If you have a better idea or a simple way to propose such feature it would be worthwhile.

**Comment by AlicVB** [comment]
Well, I completely understand the problem in that case, but I doubt there's a simple approach to solve that...

I don't remember exactly all the details, but it has been well discussed in the implementation phase.
The first thing that comes in my mind is that we can't be sure in which time-order we apply iop : If I draw a mask without (back)transform in whatever iop and apply a distortion after, mask position/form will be completely off...
not to speak about iop order modification if they include drawn masks...

That's not to say it's not possible (in fact, quite easy to implement), but it will certainly need lot of thinking before, to avoid ending up with something even worse...
