### ISSUE TITLE
[Culling] Auto advance fails in unstarred only mode

### ISSUE THREAD

**Issue by bastnic** [darktable-org/darktable#2951]
**Describe the bug**
Auto advance with culling mode and "unstarred only" is broken as it auto advance to an empty screen that we cannot leave.

**To Reproduce**
1. From lightable, filter "unstarred only"
2. press "x" to enable culling mode
3. press 0-5 / r, the picture correctly take the note, but it auto advance on an empty screen.
4. I'm stuck, the only way to be back in culling mode is to press x again to quit culling mode and start again. 

FYI, no problem with "w" mode.

**Expected behavior**
it autoadvance, as with "w" mode.

**Platform (please complete the following information):**
 - OS: ubuntu
 - master

**Additional context**

When not on "unstarred only", there is no auto advance, but there i can rate a photo and navigate to next/previous one with right/left.

**Comment by bastnic** [comment]
FYI: so happy to have a culling mode in darktable :heart_eyes:.

**Comment by AlicVB** [comment]
ok, I manage to reproduce if culling zoom is set to 1. I'll try to fix that asap.
btw, what is your use case for culling with zoom == 1 ? Isn't "sticky" preview more adequate ?

**Comment by bastnic** [comment]
I was trying to get my hand on culling and see differences / advantages with sticky preview mode (as it's not yet documented). I happened to see that it's the same on sticky preview mode but with a bug so I reported it. 

And btw, I was puzzled with "sticy previw" shortcut being "alt+z" now that preview is "w". Maybe move it to "alt+w" ?

**Comment by AlicVB** [comment]
I've just proposed a fix in PR #2957 
- For the manual, I've added a point about "sticky preview" in master
- For the shortcut, currently sticky preview has no default shortcut. I'll see what I can do

**Comment by AlicVB** [comment]
see PR #2958 for sticky preview default keys
