### ISSUE TITLE
Current DT build on windows doesnt start app.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2952]
**Describe the bug**
Built a clean darktable-2.7.0+1727~g0672f79d0-win64.exe today, installed it first as upgrade to my previous 2.7.xxxx build. Started app , popped the initial dt window , the one before the app actually starts. That window disappeared and nothing started. 

Then I installed again and this time I used the clean install, same thing , DT doesnt start.

Ran dt executable with the -d all command line option , no log got created  C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt

**Comment by chhil** [comment]
I uninstalled and did a clean install, got the log file.

[darktable-log.txt](https://github.com/darktable-org/darktable/files/3621965/darktable-log.txt)

**Comment by MStraeten** [comment]
confirmed. after deleting the library.db darktable starts, initial importing one picture into the library is ok, two or more files results in a termination.

**Comment by chhil** [comment]
I have had to roll back to an older install that works.
darktable-2.7.0+1735~gc80f4156f-win64 too crashes on startup if the database is still around from an older install. Deleting the config dir results in app starting, but crashes on import.

**Comment by chhil** [comment]
The last one that worked was 2.7.0.1687

**Comment by todd-prior** [comment]
Same issue just built it and it is not opening direct to an error code ...running Win10Pro on intel core i7
Erro 0xc0000142

**Comment by jenshannoschwalm** [comment]
Have also been testing, removing the database (library.db plus data.db) and started importing files, first one then some 20 and then thousands. Not a single problem at all.
tested two versions
1) c80f415 plus pr# 2955 on fedora 30
2) master 0954325
Both went just as expected, masks import, all modules activated as desired. BTW - i does not matter having xmp files or not.

What i couldn't test: I have no old database at hand.

Mmm, don't know right now. Any more details?

**Comment by chhil** [comment]
@jenshannoschwalm 
Here are my config file that were being used on an upgrade, maybe it helps.
[config.zip](https://github.com/darktable-org/darktable/files/3628984/config.zip)

**Comment by jenshannoschwalm** [comment]
I can see that your library.db contains signs of an old history. But on first sight i can't identify a database corruption.
You describe a situation where you import just one file to an empty database and can't use dt later onwards.
Could you share such an image file+xmp plus the config data as you sent right **after** that import?

**Comment by chhil** [comment]
@jenshannoschwalm 
I did not try one file, that was @MStraeten .
I import folder that has sub folders. (image of folder structure and images+xmp imported before crash are in the zip file). I had to look at the library db to see which ones were in there and I have shared the ones that were in the library.db images table.
Please grab it from the drop box link.
https://www.dropbox.com/sh/6b905xltzknxkk7/AACiLsjK7qdGA4yXs1Td3lA6a?dl=0


C:\Program Files\darktable\bin>darktable.exe --version
this is darktable 2.7.0+1775~g060abe657
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by chhil** [comment]
The log file generated.
[darktable-log.zip](https://github.com/darktable-org/darktable/files/3629669/darktable-log.zip)

**Comment by MStraeten** [comment]
@jenshannoschwalm: you checked with windows? I think, it's a windows specific issue since my osx builds are working fine ...

it seems to be related to the generation of thumbnails in ~\AppData\Local\Microsoft\Windows\INetCache\darktable. If the mipmaps-... directory is deleted, darktable starts, but no new mipmaps-... directory is created.
also darktable-create-cache fails after processing the first file

**Comment by phweyland** [comment]
I've the same issue with current master on windows.
I've tried with commit  580bf49da0f7527686a5978af37f9711a8067dd1. This one works for me.

**Comment by jenshannoschwalm** [comment]
I tested on linux only and i don't do any dt work/devel on windows. Thought that you ( @MStraeten ) were again testing on osx and that was really worrying me.

**Comment by chhil** [comment]
> I've the same issue with current master on windows.
> I've tried with commit [580bf49](https://github.com/darktable-org/darktable/commit/580bf49da0f7527686a5978af37f9711a8067dd1). This one works for me.

Thanks @phweyland , I built (darktable-2.7.0+1709~g580bf49da-win64)  based on your commit referenced and it works

**Comment by todd-prior** [comment]
This same behaviour happened to me so not sure about a specific image being the issue on one of my recent installs I was prompted that my database needed updated and I selected yes. It seemed to work okay…sorry can’t remember what build but maybe around 1702??  My issue with this started when I tried to install 1727…I am compiling the latest version now and will see if the problem persists. I do know that in the past I update version right on top of one another without pursuing the install but I wondered if that was an issue so I use uninstall on my last couple of new installations so I am not sure if something happened there or not??

**Comment by MStraeten** [comment]
i found 5ede285b9bedec8383ad9525f13ff9094548a16c beeing the commit introducing the termination.

**Comment by phweyland** [comment]
> i found [5ede285](https://github.com/darktable-org/darktable/commit/5ede285b9bedec8383ad9525f13ff9094548a16c) beeing the commit introducing the termination.

It runs well until `free(blob);` but doesn't come back in mipmap_cache.c:
![image](https://user-images.githubusercontent.com/23012047/65263803-9907e500-db0d-11e9-8234-5313f29ab667.png)

**Comment by phweyland** [comment]
in memory.cpp:
`#include <malloc.h> // for _aligned_malloc, _aligned_free`

the windows version of dt_alloc_align() calls _aligned_malloc().

dt_malloc_align() => needs dt_free_align(). 

suggestion: dt_free_align() could encapsulate free() and _aligned_free() depending on the OS.

![image](https://user-images.githubusercontent.com/23012047/65265392-2567d700-db11-11e9-93fd-0d45c386ba30.png)

**Comment by todd-prior** [comment]
@phweyland @MStraeten You guys are super sleuths...thanks for hunting this down.

**Comment by chhil** [comment]
Current build [darktable-2.7.0+1778~g57d00fa4c-win64.exe]  with commit  57d00fa fixes the problem reported. Thank you all who were involved in resolving it.

**Comment by todd-prior** [comment]
My thanks as well..outside the scope of my talents by far so very grateful….
