### ISSUE TITLE
Ricoh GRIII Camera Support

### ISSUE THREAD

**Issue by maltmoose** [darktable-org/darktable#2953]
Please can you fully support Ricoh GRIII.
24 megapixel APSC camera.

Let me know if you need any more samples?

**Comment by LebedevRI** [comment]
That camera produces dng, so basic support just is there.
As for noiseprofiles/lens corrections/white balance presets you need to profile them yourself.
I'm not sure what are the most up-to-date guides on that.

**Comment by maltmoose** [comment]
A profile for the GRIII vignetting would be useful as its fairly heavy on this camera. Noise and white balance profiles a bonus, Improved colors?

Welcome any pointers on profiling the vignetting and getting that included.

**Comment by LebedevRI** [comment]
https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ might be the most recent article
