### ISSUE TITLE
colorchecker module is being incorrectly relocated in new pixelpipe ordering for existing images.

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#2954]
**Describe the bug**
After #2905, when opening a folder of previously imported images, they become pure white or faintly-detailed magenta in the thumbnails. The terminal output complains that colorchecker module must be between colorin and colorout, and indeed, when checking these images, colorchecker (which is active on most of my images as a camera color profile) had been moved to a place before colorin. Importing new images or discarding history results in the module being auto-applied (via preset) in the correct pixelpipe position.

**To Reproduce** 
Create a fresh profile directory with a 2.7 version prior to #2905. Import some pictures, enable the colorchecker ("color look up table" in English locale) module on some of them, and quit darktable. Ingest this profile directory into version 2.7.0+1735 (last version I built). Open the images with colorchecker enabled, and observe location of module in pixelpipe.

**Expected behavior**
The active colorchecker module should be moved to the intended location within the pixelpipe.

**Platform (please complete the following information):**
Linux 4.19.69 (Slackware)

**Comment by junkyardsparkle** [comment]
Working backwards in time, I found that this issue does NOT exist with images in the database which were originally imported with the 2.6.2 release version, only those imported after 2019/03 when I began using git master. Unfortunately, I no longer have a "clean" 2.6.2 profile directory on hand to test with, but I guess this might also not happen when ingesting one of those... which would make this a less severe issue.

**Comment by TurboGit** [comment]
Yes, indeed from 2.6.2 to next upcoming release there should be no problem. That's a transient issue to dev version of dt.

**Comment by junkyardsparkle** [comment]
@TurboGit Transient, sure, and I can work around it myself, but I think quite a few people have been using the 2.7 branch (see #2952), with potentially many months of editing work based on it, who might reasonably expect to be able to transition to the next release. :-)
