### ISSUE TITLE
How to build an older version of DT when current dev branch doesn't work?

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2956]
**This is not a bug but a How to Question **
I am at darktable-2.7.0+1735~gc80f4156f-win64 and the app crashes and cannot be used. I know of an older build that last worked  2.7.0.1687.
How do I get the build script to get to that build?
How are the version numbers for builds generated so that I can think of a way to get to the build I want?
Is it possible to have the build number printed at the beginning of the build to not end up building the same build again and cancel out?  

Pointers will be appreciated.

**Comment by MStraeten** [comment]
get the commits from https://github.com/darktable-org/darktable/commits/master then
`git checkout <latest working commit>`

**Comment by chhil** [comment]
@MStraeten How do I get a commit from  2.7.0.1687 ? 
My build process is , I see emails and something that interests me or a bug is fixed I get a build that day its not based off commit hashes.
Whats the relation between 1687 in the version and the commit at that point in time ?

**Comment by chhil** [comment]
There is a shell script that does a git describe --tags --dirty to get the version.
