### ISSUE TITLE
Double click to select one item skipping others 

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#2960]
**Is your feature request related to a problem? Please describe.**

I'm using the "copy [parts of] history stack" feature increasingly and most often it's just one module which I want to replicate in other shot(s). There's a button to first "select none" and then I can click on the one I want to copy.

**Describe the solution you'd like**

A shortcut approach: if I double click on an item it'd be automatically be selected and the other ones deselected. I personally would not mind if the dialog also went ahead and proceeded with copying the module I wanted to. I understand if this would be too obscure behavior or potentially confusing to the uninitiated.

**Describe alternatives you've considered**

The current two(/three)-click solution is fine I guess.

**Comment by TurboGit** [comment]
I like the idea of the double click to select only a given item.

**Comment by progo** [comment]
Thank you very kindly :)

**Comment by TurboGit** [comment]
This is now implemented. Closing.
