### ISSUE TITLE
Standardisation of the keyboard shortcut in user manual

### ISSUE THREAD

**Issue by mepi0011** [darktable-org/darktable#2963]
In the user manual, the key combinations are written differently from page to page.
Sometimes it is written in lower case (ctrl-x), sometimes in upper case (Ctrl-x) and sometimes with a plus (ctrl+x) or a mixture of both.

In a [discussion via darktable dev mailing list](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg04643.html) it was suggested to capitalise the keyboard shortcuts (letters) and use a plus sign as separator.

The recommended spelling is for e.g. Ctrl+X

**Comment by TurboGit** [comment]
Yes, I'm ok with that.

**Comment by mepi0011** [comment]
Solved with [PR #2963 ](https://github.com/darktable-org/darktable/issues/2963)
