### ISSUE TITLE
New pictures in chapter 2.3.12 Tagging are pale-coloured

### ISSUE THREAD

**Issue by mepi0011** [darktable-org/darktable#2964]
The images inserted in chapter 2.3.12 are pale compared to the other images in the manual.
For example see picture [panel-tagging-default.png](https://github.com/darktable-org/darktable/blob/master/doc/usermanual/lighttable/images/panel_tagging-default.png) or attached picture below.

**The screenshots should be adapted to the images in the manual.**

![2019-09-20_darktable-usermanual-de](https://user-images.githubusercontent.com/9118135/65313498-bc29a780-db94-11e9-8e40-a4a60e02859e.png)

**Comment by TurboGit** [comment]
Ah indeed! Now that we have multiple theme we must be sure the dark one is used for all screenshot.

**Comment by phweyland** [comment]
Then the theme to be used for doc is "darktable", correct ?

**Comment by TurboGit** [comment]
No, I would go with darktable-elegant which is cleaner. And this will certainly be what Aurélien will use for its documentation part.

**Comment by phweyland** [comment]
OK, I'll do it.

**Comment by mepi0011** [comment]
I would like to return to the subject.
By default, darktable uses the design darktable, which corresponds to the brighter images.
Therefore, the images in the user manual should also correspond to the brighter design. 
I would like to replace a few pictures in the user manual with newer ones.
So that I don't do the work twice, the design to be used should be clarified.
Currently the pictures in the user manual are still mixed!

**Comment by Nilvus** [comment]
@TurboGit: I think this could be closed as if I'm not wrong, #3015 PR by @phweyland solved this one.

**Comment by TurboGit** [comment]
I think so indeed. Thanks.
