### ISSUE TITLE
basic adjustment applied after tone curve 

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2965]
**Describe the bug**
Basic adjustment is applied after tone curve. This cause the behaviour shown in the picture attached. There is a difference between the histogram in the tone curve module end the one displayed on top most of the screen. Additionally, tone curve correction is applied wrongly
![Schermata da 2019-09-20 15-38-33](https://user-images.githubusercontent.com/43513892/65334367-8bf8fd80-dbc2-11e9-9525-d2f5839d78b9.png)

This happens on the master development branch, ubuntu 19.04

**Comment by aurelienpierre** [comment]
1. histograms shown in modules are input of such modules, they will generally be different than the global histogram, which is the output of the whole pipeline. 
1. the basic adjustment module is a mistake that squeezes scene-referred and display-referred operations at once, whereas scene-referred ops need to be done before camera transforms (filmic or base curve) and display-referred ones need to be done after.

There is no good place in the pipe to put this module. The colour science in it is wrong.

**Comment by chhil** [comment]
@aurelienpierre Could you help identify which sliders are  scene-referred and which ones are display-referred?

**Comment by todd-prior** [comment]
https://github.com/darktable-org/darktable/commit/2cb026277e583542c55863432d11f4c6cc56f24d

**Comment by aurelienpierre** [comment]
@chhil exposure and black level are scene-referred, all the rest is display-referred.

**Comment by chhil** [comment]
@aure
