### ISSUE TITLE
Mouse wheel hovering slider doesn't adjust the value but scrolls panel instead

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#2967]
**Describe the bug**
Mouse wheel hovering slider doesn't adjust the value but scrolls right panel instead.

In the doc:
![image](https://user-images.githubusercontent.com/23012047/65346378-e3a46280-dbdc-11e9-863e-bde6e063db32.png)

**Expected behavior**
make the mouse wheel hovering a slider adjust the value

**Platform (please complete the following information):**
 - OS: windows 10
 - Version master (2.7)

**Comment by AxelG-DE** [comment]
That behaviour can now be altered in the settings

**Comment by phweyland** [comment]
I did miss that ! Thanks.
