### ISSUE TITLE
Colorize module broken

### ISSUE THREAD

**Issue by franklepore** [darktable-org/darktable#2969]
**Describe the bug**
The colorize module has stopped working. The default setting turns the image white and the hue slider changes the image to random colors that are unrelated to the chosen color. Using the parametric dialog and the input slider results in no effect at all.

**To Reproduce**
1. Go to 'colorize' and activate
2. Just play around with any of the sliders

**Platform (please complete the following information):**
 - OS: linux (Mint 19.2)
 - Version 2.7.0~git1780.0f86fcdd5

**Additional context**
The problem has existed for at least a week or so. Loading up git1739 showed the same issue.

**Comment by thugcee** [comment]
I have the same problem. Messages on console:
```
[dt_ioppr_transform_image_colorspace] module colorize must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorize must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorize must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
```

Bloom module is broken too.

**Comment by TurboGit** [comment]
Please search the previous reports, this has been already debated.

**Comment by franklepore** [comment]
Reports about what? I can't find any other bug report on the colorize module. Is there another issue affecting colorize that I should be looking at?

**Comment by MStraeten** [comment]
You can drag the module with holding ctrl+shift to the appropriate place in the stack.

**Comment by franklepore** [comment]
I have confirmed that ctrl+shift to move the module fixes the problem. Thanks for the fix. Should I assume that the bug is in the module ordering? Also, should I assume that moving to a position that doesn't cause a problem is "the appropriate place in the stack."?

**Comment by TurboGit** [comment]
Yes, and yes. But this (as explain in other PR) is a transient issue. It should not reproduce with new pictures (at least I have never been able to reproduce) and was due to a bug in a 2.7 dev release now fixed.

**Comment by franklepore** [comment]
Thank you for the clarification. Looking forward to the 2.8 release.
