### ISSUE TITLE
Bloom module doesn't have any effect in latest git

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#2972]
**Describe the bug**
The bloom module has no effect on the image when enabled and the settings are changed.

**To Reproduce**
1. Open an image in darkroom mode
2. Open bloom module.  Set size and strength to 87 and threshold to 10.
3. Notice that image doesn't change.  Image should be very high key with histogram to the right.
4. Turn module on and off and observe no change to displayed image

**Expected behavior**
Image should have been very bright with histogram values to the right.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 2.7.0+1779~g7f181859b

**Additional context**
Works correctly in 2.7.0+1687~gbc430e37e

**Comment by wpferguson** [comment]
Opened an image edited with 2.7.0+1779~g7f181859b in 2.7.0+1687~gbc430e37e.  Tried the bloom module with no effect.  Duplicated the image with no history and bloom worked correctly.  

Left the image with the bloom edit from 2.7.0+1687~gbc430e37e and imported it into 2.7.0+1779~g7f181859b.  The bloom effect did not show up.

**Comment by wpferguson** [comment]
Looked back through the console output and found 

[dt_ioppr_transform_image_colorspace_cl] module bloom must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module bloom must be between input color profile and output color profile

**Comment by wpferguson** [comment]
I opened the image again with the latest git.  Opened the image in darkroom mode, went to the used modules tab and moved bloom up above input color profile and it worked as it should. 

So, it appears to be an iop ordering problem.

**Comment by parafin** [comment]
This is one of the many bugs introduced by recent changes to iop order. Obviously there is a problem with current master.

**Comment by TurboGit** [comment]
Yes, big issues with iop_order!

**Comment by ptilopteri** [comment]
change iop_order back to fixed/frozen and only allow visual movement of the order displayed on darktable and provide a method to change the displayed order to reflect the fixed order.

**Comment by TurboGit** [comment]
I think I now understand what is going wrong. The iop_order has been changed without updating the iop_order_version. This is wrong I suppose.

**Comment by TurboGit** [comment]
You may want to test:
https://github.com/darktable-org/darktable/pull/2974

This must be tested with images that have not been edited since September 16th.

**Comment by wpferguson** [comment]
Tested and it works.  Images edited before September 16th display correctly.  New edits using bloom and color lookup table modules now work correctly.

If you edited an image with the corrupt iop order, you need to remove it from the database, probably git rid of the xmp file, then reimport it.

**Comment by TurboGit** [comment]
You could also reorder the module manually.

Anyway fix merged now #2974.

**Comment by wpferguson** [comment]
Hi Pascal,

This works.  Thanks

Bill

P.S.  Sorry it took so long, you caught me on the road...
