### ISSUE TITLE
Module search does not show deprecated but used module

### ISSUE THREAD

**Issue by bastnic** [darktable-org/darktable#2995]
**Describe the bug**
Filmic v3 just landed in master and so filmic v2 is deprecated. But in old edit we still have filmic enabled. We can see it "active modules" tab and in the correct group depending on your iop layout config. 
BUT it never shows up if you search for it. Only filmicrgb will be there, but never filmic.

Not sure it's a bug or a feature but it seems like a bug to me.

see https://github.com/darktable-org/darktable/pull/2938#issuecomment-534748307

**To Reproduce**
1. old edit with filmic v2 enabled
2. see that it's present in active module
3. search "filmic"
4. only "filmicrb" shows up

**Expected behavior**
Search should not show deprecated module if disabled. But if enabled, it should show it.

**Platform (please complete the following information):**
 - OS: not relevant
 - Version: master

**Comment by PaoloAst** [comment]
I'm attaching a simple request: when you press the shortcut for "search module", I think could be better to have the focus on the input box. This will save some time..

**Comment by TurboGit** [comment]
I would say a feature, the search does not consider the deprecated modules.

**Comment by PaoloAst** [comment]
> I would say a feature, the search does not consider the deprecated modules.

What about the automatic focus on the input box? Do you think it feasible?

**Comment by aurelienpierre** [comment]
not sure I understand what you want. You have defined a keyboard shortcut so that the module search input box is… triggered ? Then you want to see the module highlighted ?

From a GTK point of view, "giving focus" means allowing the widget to capture mouse and keyboard events, so if you have a shortcut to "enable" the search box, I think it's already happening.

**Comment by PaoloAst** [comment]
> From a GTK point of view, "giving focus" means allowing the widget to capture mouse and keyboard events, so if you have a shortcut to "enable" the search box, I think it's already happening.
You're right. My fault. I had such shortcut, but it has been deleted. The search box is shown always, so I didn't realize my shortcut wasn't functional. I've re-enabled the shortcut and (magically ;) ) it worsk... sorry for the misunderstanding
