### ISSUE TITLE
filmic v.3 curve

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#2997]
**Describe the bug**
Strange curve on midtones as per attached picture
![Schermata da 2019-09-25 09-18-06](https://user-images.githubusercontent.com/43513892/65578228-ac83d780-df75-11e9-9aa4-3539c4ea21c5.png)

A second instance of filmicrgb works as expected and, after that, closing and running DT again (even on different pictures) make the problem disappear, so I'll close the issue.

**To Reproduce**
From a new, untouched image, open filmicrgb module

**Platform :**
 - OS: Ubuntu Disco
 - Version master branch

**Comment by aurelienpierre** [comment]
mmh you are not the only one to report it, but it doesn't reproduce on my side.

**Comment by TurboGit** [comment]
I have seen this once or twice... Looks like a missing initialization somewhere.

**Comment by aurelienpierre** [comment]
but there is no initialization (aka no LUT), values are computed on the fly from the polynom, given the polynom coefficients. It's funny that it should be the linear part that fails, because the curvy parts are computed from it, and they work.

**Comment by AlicVB** [comment]
I *may* have found the error, see PR #3000 
As said there, it's just a change in code looking suspicious, without knowing anything about the maths involved there ! So please check carefully !
