### ISSUE TITLE
Stars / rating should not be resized (Negatives)

### ISSUE THREAD

**Issue by mjut** [darktable-org/darktable#2998]
**Stars growing too big in the negatives display**
I think, the stars and the rating - sitting underneath each photo - are way too big. Especially when I change the size of the negatives to bigger/less photos, the stars are enlarging too. 
I am finding this not very helpful, as these huge stars are distracting from the photo itself.
I am trying to explain with the following screenshots I made:

_The size of the stars is okay when looking at a lot of photos:_

<img width="1142" alt="Bildschirmfoto 2019-09-25 um 10 38 03" src="https://user-images.githubusercontent.com/601038/65585147-481b4500-df82-11e9-89a7-d95375738530.png">

_Even by zooming in just a bit, the stars are growing:_

<img width="1168" alt="Bildschirmfoto 2019-09-25 um 10 38 28" src="https://user-images.githubusercontent.com/601038/65585366-a5af9180-df82-11e9-8992-bc398c6fc9c3.png">

_With enlarging the photos even more, the stars are enlarged way too much:_

<img width="1629" alt="Bildschirmfoto 2019-09-25 um 10 38 47" src="https://user-images.githubusercontent.com/601038/65585479-cf68b880-df82-11e9-95ad-1221ee16a081.png">

**Make the stars and colour rating part of the UI**
I would love to see a consistent size, no matter what zoom factor in the negatives view.
I don`t know, how to achieve this – I was messing with the css-files (in the themes folder) without finding a solution.  

**A look at RawTherapee**
Just to explain a bit more the idea, see following screenshots taken from RawTherapee.
(Don't get me wrong, I like the Darktable view better. I just think, RawTherapee handles the zoom better..)

<img width="860" alt="Bildschirmfoto 2019-09-25 um 11 02 56" src="https://user-images.githubusercontent.com/601038/65586518-93ceee00-df84-11e9-9759-9a2e0e22ae35.png">

_When resizing the images, stars are not being resized and still looking neat:_

<img width="707" alt="Bildschirmfoto 2019-09-25 um 11 03 13" src="https://user-images.githubusercontent.com/601038/65586589-b06b2600-df84-11e9-9f98-1cc4f783010e.png">

**This is no bug**
Of course – but I think, this would be an overall improvement of the look and UI of Darktable. Unfortunately, I am no developer and I have no idea where to change this.  
I tried to change the css-files in the themes. But that does not do the trick...

**Comment by aurelienpierre** [comment]
The stars are drawn as Cairo objects, so the CSS won't change anything. 

I have redone the styling for the darkroom, but I didn't got time for the lighttable yet. It definitely needs some clean-up and redesign too (at least to get rid of the borders and shadows).

**Comment by mjut** [comment]
Thanks for the information. I am looking forward to the new version of darktable.
I am interested in taking a look at it myself. Is this the "Cairo" you are talking about: https://en.wikipedia.org/wiki/Cairo_(graphics) ?
As I am a frontend developer, this is something I've never worked width..

**Comment by aurelienpierre** [comment]
Yeah, Cairo is the vector drawing from GTK project.

**Comment by Nilvus** [comment]
> The stars are drawn as Cairo objects, so the CSS won't change anything.
> 
> I have redone the styling for the darkroom, but I didn't got time for the lighttable yet. It definitely needs some clean-up and redesign too (at least to get rid of the borders and shadows).

As I answer to @mjut on pixl.us for this, that's confirm what I was thinking : not related to CSS. I agree to @mjut : it's clearly one of the last thing on the UI to improve visually. Anyway, I don't have skills on that.

**Comment by aurelienpierre** [comment]
I'm working on that right now.
