### ISSUE TITLE
tone equalizer: "simple" tab controls cause a ringing curve

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#3004]
**Describe the bug**
Tone equalizer produces a misinterpolated / ringing curve.

**To Reproduce**
1. Enable tone equalizer
2. Reset it to default settings
3. In the "simple" tab, lift "- 6 EV : shadows" slider by 0.5 EV
4. In the "advanced" tab, see that the curve not interpolating the control points and has ringing. See image below.

**Expected behavior**
I expect the curve to go through the control points and not ring. I am not sure if this is actually an expected property of the interpolation curve, but as a result of the ringing, moving a single slider has surprising effects on the tone response. On the other hand, scrolling the mouse on the image (this is very cool and useful!) or dragging the curve on the advanced tab works intuitively without surprises.

Thank you for this very useful tool in Darktable!

**Screenshots**
![toneeq_ringing](https://user-images.githubusercontent.com/5001906/65616882-76ba0f80-dfc4-11e9-9d31-02764c079dfe.png)

**Platform (please complete the following information):**
 - OS: Arch Linux
 - Version ce84aeff9e624a52d62d57970ab98d6492dbc5d2

**Comment by aurelienpierre** [comment]
It's not a bug, it's a drawback of the interpolation method. All you can do is to decrease the curve smoothing parameter, but it's generally not a good idea to increase sharply only one channel. There is nothing I can do in the code to alleviate that, the reason it's happening is grounded in maths.

**Comment by flannelhead** [comment]
Thanks for the response, that's what it seemed like indeed. It just initially surprised me a bit since for example, decreasing one channel can result in a slight increase on other channels. This is seen in the image itself, but is not immediately clear since the curve is not displayed on the simple tab.

Just an idea (or a personal opinion): from brief testing it seems to me that editing on the Advanced tab gives a curve with less ringing (since dragging on the curve seems to affect a few of the neighbouring control points), that could even be considered as the default way of using this module. Personally I find the user experience there amazing.

**Comment by aurelienpierre** [comment]
> it seems to me that editing on the Advanced tab gives a curve with less ringing (since dragging on the curve seems to affect a few of the neighbouring control points),

yes, exactly. But I can't reproduce the same behaviour for sliders, and it's also a good things to have this really independant way of setting channels as a fall-back.
