### ISSUE TITLE
Vertical waveform display

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#3005]
For some pictures the waveform display is extremely useful. I understand why cinematographers only rely on a horizontal waveform view, the typical aspect ratios tend to be landscape oriented (this may change with more and more smartphone videgraphy ;) ). However, in photography, it would totally make sense to not only have a horizontal but a vertical waveform display as well. Maybe even an arbitrary direction would make sense, but as pictures tend to be rectangular, maybe a vertical waveform is already enough.

I am not sure if it would make sense to change the orientation of the containing “box”, but probably it would. But as this would mess up the darkroom view a lot, this has to be discussed a bit more.

**Comment by spaceChRiS** [comment]
Hm, I still consider this useful, despite the bot having another opinion.

**Comment by parafin** [comment]
#4149 is somewhat related and mentions this problem in the comments.

**Comment by dtorop** [comment]
@spaceChRiS I'm finally noticing this. I've wondered about this as well. Are you suggesting that the widget becomes vertical, or (and?) that the x/y axes on waveform can flip, such that brightness data is horizontal and spatial data is vertical?

It would be fairly trivial to make the waveform have an option to flip axes. The only question would be where to hide the extra button to do this -- unless this should be automatic for vertical images.

Of course unless the histogram widget changed shape, when axes were flipped there'd suddenly be a plethora of luminance data on the x-axis and not much spatial data on the y-axis. Regarding actually making the widget be vertical, see https://github.com/darktable-org/darktable/issues/4149#issuecomment-616407567:

> The preview on the left and the histogram on the right should have the same size to keep the GUI balanced.

I suppose it would be possible to change the orientation of the preview widget as well for vertical images, but this seems like a significant change.

**Comment by johnny-bit** [comment]
@dtorop - recently @elstoc made a PR which allows histogram to change size. Houz's comment is just "should" not "has to" ;)

**Comment by elstoc** [comment]
Yes, ctrl+scroll should resize the histogram vertically now

**Comment by dtorop** [comment]
Just catching up on recent work! I appreciate the ability to vertically resize the histogram. I added a note (https://github.com/darktable-org/darktable/pull/5276#discussion_r437840580) as it may be easy to just resize the widget without worrying about the underlying buffer -- but I haven't tested how this looks.

The question, then, is whether there should be a way to flip the axes of the waveform. This should be trivial, but it'd also add one more button to the UI, and it may add a bit of extra code to make sure that both versions are reasonably fast. I'm pretty neutral on this...

**Comment by spaceChRiS** [comment]
Thanks for looking into that, @dtorop and all! Regarding the questions, I was solely thinking about having a way to assess the brightness distribution in both directions and not only “x”. I had to correct a severe gradient in ~30 pictures and it was easy in x-direction with the waveform, but in y direction I was lost. The only question is if the analysis along the image y axis should also rotate the waveform. I think it should, such that more brightness shifts the curve to the right, and the y axis matches the image orientation.

Having a resizable widget may really be handy for this task. Thanks for adding this feature, @elstoc :)

**Comment by dtorop** [comment]
@spaceChRiS Glad to hear back. I also agree that shifting the axes for a vertical waveform makes sense. I guess the only thing to do is to code it and see how it works, unless others have clear design visions.

I'm happy to work on this. It may not be right away, as I want to pull together #4298 which may require altering a bunch of the histogram plumbing.

Currently the waveform work is done here:

https://github.com/darktable-org/darktable/blob/26a903a65203d189b7c1d14a5e941ead565c177c/src/develop/pixelpipe_hb.c#L1009-L1118

It may be this code is optimized for the current axes, and also that the resolution of the underlying buffer is optimized for a horizontal histogram. I'll have to see.

The other question is whether this will really start overloading the button in the histogram to add one more mode to waveform. At some point I think these buttons should shift to gtk/bauhaus which would simplify histogram code and make them more flexible. These are all v3.4 questions.

**Comment by spaceChRiS** [comment]
> It may not be right away […] These are all v3.4 questions.

As I was able to solve my task already without this feature, I am anyway not holding my breath. I just had a task where this would have been handy, and I did not understand that I never saw this feature in a photo editor. I understand some of the multiple reasons that this tool is like it is in video tools (on one hand, for landscape oriented video it is more important to keep the brightness sound from left to right, and on the other hand, the analog origin of this tool which probably was much easier to implement horizontally), but for photography (and maybe for vertical video as it becomes more and more popular) it made sense to me to have it in both directions.

Regarding the implementation questions, I can hardly contribute. But thank you so much again for looking into this :smiley:!

**Comment by johnny-bit** [comment]
Hey @dtorop - I recently had to work on couple portrait-oriented pics and vertical waveform would be cool to have if you're still interested ;) (although vectorscope is waaaay cooler!)

**Comment by dtorop** [comment]
@johnny-bit Yes! I've totally forgotten about this, in fact. Thanks for the reminder. As I keep writing, it should be easy to do. I've got a whole list of scope fixups in my head right now, and this would be a quick one to start in on.

I'm assuming that at this point any such changes would be for v3.8?

**Comment by johnny-bit** [comment]
Yes. According to recent mail from pascal were now in "safe mode" meaning that most likely no new features or features that are prety much non-breaking. But code freeze is not till late june so "fixups" are very much welcome ;)

**Comment by dtorop** [comment]
I'll give it a look. I'd hate to break something, and this is not a pressing feature, so probably a v3.8 goal. Especially as if there are vertical waveforms, it may tweak the UI from the current (with subtypes in parentheses):

```
histogram (logarithmic/linear) ->
waveform (regular/parade) ->
vectorscope (linear/logarithmic & CIELUV/JzAzBz) ->
```

to

```
histogram (logarithmic/linear) ->
waveform (horizontal/vertical) ->
rgb parade (horizontal/vertical) ->
vectorscope (linear/logarithmic & CIELUV/JzAzBz) ->
```

Which is enough to really not want to mess with "safe mode" code.

**Comment by johnny-bit** [comment]
Yeah, would work for me :)

**Comment by dtorop** [comment]
I worry that if I have various bits of histogram/waveform/vectorscope work for v3.8 lingering in multiple PRs, that they'll overlap with each other, and won't apply cleanly as separate git branches. But first I have to make the changes, so will cross that bridge then.

**Comment by dtorop** [comment]
Testing a bit more. In horizontal configuration it's slightly off from the current waveform, so clearly will need a bit more attention.
