### ISSUE TITLE
Image scale issue on HiDPI monitor [Windows 10]

### ISSUE THREAD

**Issue by Kelvin-Wu** [darktable-org/darktable#3008]
Hi All. I use darktable on my Win10 PC with 4K monitor. 
Since the resolution is very high, I changed the "size of text, apps and other items" to 200%. (I use chinese version.)
![dpi](https://user-images.githubusercontent.com/55777209/65655350-7ebe9180-e04e-11e9-811d-35439d92ccc4.jpeg)

When I use scale 100% function in datktable, the image size look like 200% not 100%.
![dt](https://user-images.githubusercontent.com/55777209/65655354-85e59f80-e04e-11e9-8bad-39f21cd059e6.jpeg)

But the scale function is work correct on other apps like Lightroom, Rawtherapee, and digiKam.
They show the 100% resolution of image.

**Lightroom**
![lr](https://user-images.githubusercontent.com/55777209/65655357-8bdb8080-e04e-11e9-8846-6d19a52546dc.jpeg)

**Rawtherapee**
![rt](https://user-images.githubusercontent.com/55777209/65655362-9433bb80-e04e-11e9-9e75-a593b89a74c8.jpeg)

**digiKam**
![digi](https://user-images.githubusercontent.com/55777209/65655365-985fd900-e04e-11e9-92eb-b7ab7986eab3.jpeg)

**Comment by aurelienpierre** [comment]
Yes, it's not just on Windows. The 100 % zoom in darkroom is actually a 200 % view if you set the DPI scaling equal to 200 %. Same here, on 4K, to get 1:1 pixel scaling, I actually need to use the 50 % zoom level.

**Comment by Kelvin-Wu** [comment]
I think this problem should be fixed. Or....can we have modified shortcut can make quick switch between 50% and fit screen?

**Comment by sboukortt** [comment]
I agree that it should probably be fixed, as getting 1:1 mapping:

1. is possibly the main use-case for selecting “100%”;
2. is otherwise impossible with certain scaling factors (200% is the “easy case”).

**Comment by snaggen** [comment]
It sounds like the devs need to use gdk_window_get_scale_factor or similar, to get the scaling factor and compensate for it.

https://wiki.gnome.org/HowDoI/HiDpi

**Comment by Kelvin-Wu** [comment]
Hope it can be fixed one day...

**Comment by jenshannoschwalm** [comment]
I think this is fixed, at least for osx and Linux. There is a remaining issue with a secondary monitor non-hdi though.

**Comment by aurelienpierre** [comment]
No it's not, I can confirm:
![Screenshot_20210418_231640](https://user-images.githubusercontent.com/2779157/115161134-2b7eba80-a09c-11eb-8f4e-8e4e6da40187.png)

This is a 1000×563px image displayed at 100% zoom level in a 3840×2160px viewport. It should occupy roughly 25% of the screen width, here it takes more than 50%.

**Comment by jenshannoschwalm** [comment]
The whole pixels-per-dot (PPD) stuff really drives me mad. But if your screenshot is on a ppd==2 display, isn't that absolutely correct that way? 25% would be on a ppd==1 display i think. There were discussions about exactly this problem, see #6382 , there is a comment from parafin at the very top.

Or is it the scaling display the issue?

**Comment by Nilvus** [comment]
I close this one as it had been fixed in #8870. See last comments that confirm that.
