### ISSUE TITLE
Export images parameters are not reset

### ISSUE THREAD

**Issue by techexo** [darktable-org/darktable#3014]
Hi everyone.

I just noted that the `reset parameters` button doesn't seem to do anything in the `export selected` module of the lightroom pane. I would expect to fall back on default values for target storage and max size when clicking it, but nothing happens.

It would be particularly helpful after modifying the target storage to be able to have again the default `$(FILE_FOLDER)/darktable_exported/$(FILE_NAME)` when clicking on reset.

This is present on darktable 2.6.2 for Windows as well as for the `2.7.0~git1778.57d00fa4c` compiled version from [OpenSuse](http://download.opensuse.org/repositories/graphics:/darktable:/master/Debian_Next/).

Cheers.

**Comment by jpverrue** [comment]
Confirmed for release 3.0 and 3.1
