### ISSUE TITLE
Support for Canon EOS Rebel T7i

### ISSUE THREAD

**Issue by TechRancher** [darktable-org/darktable#3018]
Hello,
I have contributed to the RAW file for the Canon EOS Rebel T7i.
I would like to see if we can get support for this camera in Darktable.

**Comment by LebedevRI** [comment]
Support for that camera was added several years ago, in 88a76289b873bbd2928847d4478023bf77f1ebb3 / 926e4a5b33ddfba97653867d967247718978de26.
It should be supported in current stable release.

**Comment by sudoforge** [comment]
> Support for that camera was added several years ago, in [88a7628](https://github.com/darktable-org/darktable/commit/88a76289b873bbd2928847d4478023bf77f1ebb3) / [926e4a5](https://github.com/darktable-org/darktable/commit/926e4a5b33ddfba97653867d967247718978de26).
> It should be supported in current stable release.

I'm using `darktable` on Arch Linux, which downloads the latest `.tar.xz` release, runs `cmake` to build it, then installs it with `make install` (you can [see the PKGBUILD here][0]). This does _not_ contain an entry for the EOS Rebel T7i.

[0]: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/darktable

**Comment by LebedevRI** [comment]
> an entry

??

**Comment by sudoforge** [comment]
Sorry if that was confusisng.

To be more explict, under "Lens Correction", I `Canon EOS Rebel T7i` does not exist.

**Comment by LebedevRI** [comment]
https://www.darktable.org/about/faq/#faq-external-deps
>lensfun is used for lens correction. If the lens correction module isn’t showing your camera or lens, or a wrong one, then please report that to those folks.

**Comment by sudoforge** [comment]
Got it, thanks. I checked the manpage and user manual, but didn't find anything referring to lens correction. I'll be sure to add the FAQ to the list of sources to check before leaving issue comments in the future.
