### ISSUE TITLE
Culling: [was: top left] pic does not show the info on hover

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#3019]
**Describe the bug**
mouse hover on pic #1 top/left, does not show the information (it does so right away on all the others

**To Reproduce**
1. Go to culling with zoom = 4
2. mouse hover on pix#1 and don't move
3.
4. no info as you can see on my screenshot

**Expected behavior**
same as pic 2-3, info should come up right away with the border (also missing on pic1)
@AlicVB as discussed in PR #3007

**Screenshots**
![Screenshot_20190926_182938](https://user-images.githubusercontent.com/49004103/65708281-7a19cd80-e08e-11e9-8263-e24266fe1c45.png)

**Platform (please complete the following information):**
 - OS: gentoo-linux
 - Version 2.7.0+1874~g3443cbd76

**Additional context**

**Comment by AxelG-DE** [comment]
Ammendment: I can reproduce this "not showing info" also on the others pics in culling:
![Screenshot_20190926_185826](https://user-images.githubusercontent.com/49004103/65708874-d4fff480-e08f-11e9-8300-f7b2571f438b.png)

**Comment by AlicVB** [comment]
Hmm, I can't reproduce (as always)
Just to be sure, you're aware that the infos/stars only show up if mouse is in the top part of the image ?
For the border of the top left image, I've already done a fix locally and will deploy it in my next PR

**Comment by Nilvus** [comment]
Same as @AlicVB. Same as your other issue, the goal is to let the most of the UI for images, not text. Culling view works great as it should : no text and stars except if you apply what @AlicVB precise.

**Comment by AxelG-DE** [comment]
> Hmm, I can't reproduce (as always)
> Just to be sure, you're aware that the infos/stars only show up if mouse is in the top part of the image ?
> For the border of the top left image, I've already done a fix locally and will deploy it in my next PR

Kindly disagree, you reproduced a lot already (just today the frames) and we have solved lots of things :smile: 

But you are right on the core thing. I was not aware, the info is merely shown when on top of the picture. Actually partially not logic to me, as in that 4pic, mode, of course you are "cruising" around the center cross. Anyhow with that said, this is to be closed
