### ISSUE TITLE
New PR #3007 info text color in thumbnail same than darktable-icon's frames = illegible

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#3020]
**Describe the bug**
If I am not mistaken, with PR #3007 the text color of the thumbnail changed and hence in the theme darktable-icons is not legible anymore, except the one hover.

@aurelienpierre I try to be anoying :smile: 

![Screenshot_20190926_184531](https://user-images.githubusercontent.com/49004103/65709433-193fc480-e091-11e9-903c-e912ec3f5e21.png)

**Comment by Nilvus** [comment]
As I've also worked on CSS, I don't understand what's the problem here. Of course, stars and text is not legible on thumbnails except hover. The main goal of the new UI (#3007 PR complete the work) is to have the best place to the images. I find it better to see text and stars only when hovering the image. That make lighttable more clean and legible.

**Comment by hellbuster** [comment]
I suppose there is a middle ground of using very low contrast on those items when not hovering instead of making them invisible.

**Comment by aurelienpierre** [comment]
> @aurelienpierre I try to be anoying smile

You are so good at that.

Indeed, overlays text and icons need to be brightened a bit since this change. Sit tight.

**Comment by aurelienpierre** [comment]
> I suppose there is a middle ground of using very low contrast on those items when not hovering instead of making them invisible.

There is an option for that (star icon in the top right bar in lighttable).

**Comment by AxelG-DE** [comment]
> > @aurelienpierre I try to be anoying smile
> 
> You are so good at that :-P
> 
> Indeed, overlays text and icons need to be brightened a bit since this change. Sit tight.

TNX Aurelien!

**Comment by AxelG-DE** [comment]
> > I suppose there is a middle ground of using very low contrast on those items when not hovering instead of making them invisible.
> 
> There is an option for that (star icon in the top right bar in lighttable).

I'm a little bit lost on that. I merely see the gear wheel but an star icon and which option is meant?

**Comment by Nilvus** [comment]
> > > I suppose there is a middle ground of using very low contrast on those items when not hovering instead of making them invisible.
> > 
> > 
> > There is an option for that (star icon in the top right bar in lighttable).
> 
> I'm a little bit lost on that. I merely see the gear wheel but an star icon and which option is meant?

This option is to let text infos visible permanently or not on thumbnails. The star icon is just on the left of the wheel, between G and ?
See this capture screen :

![Capture-20190927160113-200x128](https://user-images.githubusercontent.com/45535283/65775339-44cdb800-e140-11e9-8e7c-b56379db73df.png)

**Comment by AxelG-DE** [comment]
@Nilvus my bad, donno, how I could have overlooked this :blush: just one little Whisky cannot be the explanation :-)

@aurelienpierre when I toggle this star, also your grey overlay (to improve star visibility in highlighted picture) switches on/off, do you want that?

**Comment by AxelG-DE** [comment]
Merci!
