### ISSUE TITLE
Preferences needs some way to restore defaults or not apply changes

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3025]
**Is your feature request related to a problem? Please describe.**
When using the preferences dialog and use the mouse scroll to scroll, but at times the mouse can end up in a text entry box and  instead of scrolling it will increment the number. The user may not be aware and realize its not scrolling move the move and scroll again.

**Describe the solution you'd like**
I would like to see  a button that allows one to apply the change or discard the changes and continue in the dialog and let close do what it does today. A restore-defaults would be a good button to have too.

**Describe alternatives you've considered**
I currently use the ESC key to close the dialog without changes, this only after I have realized some setting changed and not knowing what the original values were.

**Comment by TurboGit** [comment]
> A restore-defaults would be a good button to have too.

Double clicking on the any label in the preference dialog will restore the corresponding default value. Isn't this enough?

**Comment by chhil** [comment]
I unintentionally changed a few values while scrolling, and didn't know which defaults I changed.

**Comment by ptilopteri** [comment]
How would dt know which changes were intended and which were by mistake?

**Comment by chhil** [comment]
Giving it more thought, a restore default to restore to clean installed values. Other wise an esc key can be used to quit without saving.

**Comment by ptilopteri** [comment]
I cannot say that this is resolved

**Comment by chhil** [comment]
It's been picked up in the preference GUI  rework
https://github.com/darktable-org/darktable/pull/4821

**Comment by elstoc** [comment]
ESC key can now quit without saving.

You can restore all settings to default by deleting your darktablerc file.

You can see which items you have changed by hovering over the label (which will tell you what the default is).

**Comment by elstoc** [comment]
Also you should now have no need to scroll any of the screens so inadvertent changes shouldn't happen any more (plus the entry boxes no longer span the whole screen so if you did need to scroll you could do so without the possibility of changing things).

**Comment by johnny-bit** [comment]
This can be imo closed as of now, all changed prefs are clearly indicated and reset is just double-click away. Also - all new preferences window is guaranteed not to scroll weirdly so less chance of accidental setting change :)
