### ISSUE TITLE
Inconsistency when reset parameters in tone equalizer

### ISSUE THREAD

**Issue by dcendal** [darktable-org/darktable#3027]
**Describe the bug**
By default the Mask quantization is set to +1 EV, when double click on the bar the value is set to 0 EV

**To Reproduce**
Tone equalizer.
Go to masks.
Change the value of mask quantization.
Double click on the slider, the new value is 0.

**Expected behavior**
The new value should be the first one +1 EV

**Platform (please complete the following information):**
2.7.0+1880-g566d9fd85-dirty

**Comment by aurelienpierre** [comment]
fixed
