### ISSUE TITLE
Segmentation fault in darkroom in g_type_check_instance_is_a

### ISSUE THREAD

**Issue by atlesn** [darktable-org/darktable#3028]
Darktable has crashed a couple of times with the attached backtraces. Only one of them are with debug symbols, but they appear to describe the same issue.

It is difficult to describe a method to reproduce the crash, but the first crash happened in darkroom after adjusting one picture then double-clicking on the next photo at the bottom.

I'm also not sure whether this is a GTK or Darktable issue. At least it's reported in case somebody else encounters it. Bug is also reported to GTK (issue 2170).

Please let me know if more information is needed.

- darktable 2.4.2-1
- libgtk-3-0:amd64 3.22.30-1ubuntu4
- libglib2.0-0:amd64 2.56.4-0ubuntu0.18.04.4

[darktable_bt_6AJC8Z.txt](https://github.com/darktable-org/darktable/files/3663388/darktable_bt_6AJC8Z.txt)
[darktable_bt_OZTO8Z.txt](https://github.com/darktable-org/darktable/files/3663389/darktable_bt_OZTO8Z.txt)

**Comment by atlesn** [comment]
A GTK developer has commented on the bug report there and close the issue at their end.

> Darktable is calling `gtk_widget_get_allocation()` with an invalid pointer—likely the widget has been destroyed but there's still something holding a reference to it.

**Comment by johnny-bit** [comment]
2.4.2 is old news by now, loads of overhauling was done, so if there are any cases where there are invalid pointers to `gtk_widget_get_allocation`, it's probably in very narrow codepath, so closing for now as provided backtraces would most likelly tell nothing in current code...
