### ISSUE TITLE
"Workflows" to clean the UI and enhance usability

### ISSUE THREAD

**Issue by Raven38911** [darktable-org/darktable#3029]
Suggestion: "Workflows" to clean the UI and enhance usability

A "workflow" could be a selection of modules for the right hand panel. The display order of these modules would be based on usability aspects, independent from the module's actual position in the pixel pipeline.

Darktable could ship with a number of pre-defined workflows for different audiences, i.e.
* users who are switching from Adobe Lightroom,
* users who are completely new to RAW development,
* users who like "filmic" vs. users who like base curves,
* advanced users who know wavelets,...

Each workflow should only include one module for every purpose (i.e. raising shadows, changing brightness/exposure, denoise, sharpen, split-toning). The module selection should assure that everything works together flawlessly. Workflows may contain "invisible" modules, so new users are not confused about modules like "demosaic" which they are not interested in. The displayed order of modules in pre-defined workflows should be a suggestion for the user to work from top to bottom.

Advanced users could also benefit as workflows would basically be multiple customizable sets of favorites.

**Comment by MStraeten** [comment]
Isn’t that already applicable by defining modules as favourites?

**Comment by Raven38911** [comment]
This isn't primarily about organizing modules for advanced users. This an attempt to start reducing complexity for new users or users who are switching from other RAW development software. You probably have no idea how overwhelming Darktable can be for new users.

There are about 60 modules. Some replicate each other's functionality (i.e. at least 3 modules for split toning, lots of "denoise" modules, MANY ways to do your exposure/contrast/shadows/highlights). Some modules replace each other and should not be used together, which is not apparent from the software itself but only from the manual (base curve and filmic).

I would assume that many users consider switching to Darktable, look at the program for an hour and then decide to abandon it because of the complexity. Darktable's main competitor is probably Adobe Lightroom - and this is a program that new users can learn just by playing around with the sliders.

Therefore I suggest giving new or switching users a carefully chosen subset of the available options. Advanced users might benefit too, because they could have a different workflows for the "filmic" vs. the "base curve" way of doing things.

[Yes, I suggest this, because I have real problems using darktable - even though I have spent a few hours with the manual and Youtube-Tutorials AND I have a degree in computer science.]

**Comment by MStraeten** [comment]
You can reduce the number of visible modules using presets (https://darktable.gitlab.io/doc/en/more_modules.html) maybe it‘s just defining a set of ‚beginners quick start modules’ in https://github.com/darktable-org/darktable/blob/master/src/libs/modulelist.c, void init_presets(...)

**Comment by todd-prior** [comment]
Are there not several already...I went in and selected to show all modules but there are other options

![image](https://user-images.githubusercontent.com/44409419/65826045-6d42d880-e24c-11e9-8782-7b425175c22d.png)

**Comment by Raven38911** [comment]
Wow, I didn't know this existed. This is actually already similar to what I meant and could be a starting point and even uses almost the same terminology.

However:
* It is hard to find.
* It resets the favorites when I choose a preset.
* It is hard-coded and can not be changed by the user.

When looking at the contents, I wonder if the workspaces are "official recommendations" from the darktable team as they use very similar sets of modules. For example all use filmic, while in my impression the manual still seems to favor base curves.

**Comment by MStraeten** [comment]
As other presets user can save their own selection as a preset.
There‘re several disussions on ‚darktable for beginners‘ - see https://discuss.pixls.us/t/lug-talk-darktable-for-beginners/13622/38 for example.

**Comment by aurelienpierre** [comment]
> When looking at the contents, I wonder if the workspaces are "official recommendations" from the darktable team as they use very similar sets of modules. For example all use filmic, while in my impression the manual still seems to favor base curves.

Workspaces are official recommendations of me.

**Comment by johnny-bit** [comment]
This is present in 3.4 now thanks to #5683 and documented here: https://darktable-org.github.io/dtdocs/module-reference/utility-modules/darkroom/manage-module-layouts/
