### ISSUE TITLE
Segmentation fault in lighttable

### ISSUE THREAD

**Issue by ctouz** [darktable-org/darktable#3031]
**Describe the bug**
darktable --version
this is darktable 2.7.0+1890~gf70a03ab3
Darktable crashes often when scrolling in lighttable

[logfile.txt](https://github.com/darktable-org/darktable/files/3664843/logfile.txt)

**Comment by aurelienpierre** [comment]
```
[dt_ioppr_check_duplicate_iop_order] modules bilat (39,000000) and colorzones (39,000000) have the same iop_order
[dt_ioppr_check_duplicate_iop_order] modules filmicrgb (39,000000) and bilat (39,000000) have the same iop_order
```
might be fixed by #3046

**Comment by TurboGit** [comment]
Sadly #3046 is not a fix, it was a wrong track for the moment there is still something I don't get about the iop-order.

**Comment by aadm** [comment]
I'm having the same issue described above. I'm seeing the same "segmentation fault" crash also with `darktable-generate-cache`. In addition to that, the crash would occur in DT after simply scrolling around the library for a few minutes, all the thumbnails are recreated again. I'm attaching two logs here, one generated using `darktable-generate-cache --min-imgid 49423 --max-mip 6 > ~/darktable-generate-cache_20191002.log 2>&1` and another with  `darktable -d all  > ~/darktable_20191002.log 2>&1`. Both logs are cut off below a certain point, where the same messages start repeating ad infinitum:

```
[dt_ioppr_check_duplicate_iop_order] modules bilat (39,000000) and velvia (39,000000) have the same iop_order
[dt_ioppr_check_duplicate_iop_order] modules tonecurve (39,000000) and shadhi (39,000000) have the same iop_order
[dt_ioppr_check_duplicate_iop_order] modules shadhi (39,000000) and bilat (39,000000) have the same iop_order
[dt_ioppr_check_duplicate_iop_order] modules bilat (39,000000) and velvia (39,000000) have the same iop_order
```

[darktable_20191002_41klines.log](https://github.com/darktable-org/darktable/files/3679782/darktable_20191002_41klines.log)
[darktable-generate-cache_20191002_100lines.log](https://github.com/darktable-org/darktable/files/3679783/darktable-generate-cache_20191002_100lines.log)

**Comment by todd-prior** [comment]
@TurboGit  I still seem to have this issue even after patching from your iop v4  code....I will try on a folder of naive images to see if its a strange combination in my xmp file for the group that seems to be giving me the issues when it first arose...
[darktable-log (2).txt](https://github.com/darktable-org/darktable/files/3681008/darktable-log.2.txt)

**Comment by TurboGit** [comment]
Fix merged.
