### ISSUE TITLE
Garbled text color picker live sample

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#3034]
**DT Version:** Git Master

**Issue:**

Load an image- enter darkroom, add a color picker live sample, values display as garbled text. Am I missing a font? Also the column extends past its area- and looks cut off.

![issue_garbled_text_color_picker](https://user-images.githubusercontent.com/12004932/65811387-def03780-e1f6-11e9-92a4-03f81b28f499.png)

Even worse in Lab view:
![lab_view](https://user-images.githubusercontent.com/12004932/65811404-0941f500-e1f7-11e9-89d5-6e6f04307f1d.png)

**Comment by Nilvus** [comment]
This text use a specific font : courier. It's a quite very standard font but it's possible you don't have this one on your OS. I have the font and the text displayed correctly.

@TurboGit : what do you think about that ? Does that need to add this font needed on release notes ?

**Comment by alcomposer** [comment]
Roboto comes in monospace as well. 

If if user has Roboto, then they also have monospace.

**Comment by aurelienpierre** [comment]
monospace makes a lot more sense indeed.

**Comment by Nilvus** [comment]
Indeed, that's better.

**Comment by alcomposer** [comment]
This may be a bit bike-shedding, *but*...

Is there a particular reason why the live-sample-data is bold? Would not regular monospace be fine? 

Also- why are these values monospace (as in courier) yet other number values in DT are not?
![live_sample](https://user-images.githubusercontent.com/12004932/66094025-9effca80-e5d1-11e9-9059-a6520e9fc990.png)

**Comment by alcomposer** [comment]
I uninstalled the bad courier font that was in my Arch Linux system (apparently an Adobe one that for some reason installs - but is broken).

It works now- but not using Roboto-Mono. Either way it was my system fault.

But may still be good to specify a font family that is related to the main font in DT.
