### ISSUE TITLE
Scrolling through the objectives in the correction module is impossible.

### ISSUE THREAD

**Issue by lepolau** [darktable-org/darktable#3043]
In the lens correction module, when I click on the lens manufacturer box, a list of models appears, I see models from top to bottom of my screen, but the whole list does not appear and it is not possible to scroll through the list.
The only way to scroll, point a lens, press the left arrow on the keyboard, then right, and at that moment you can scroll the list.
I use darktable 2.6.2 on debian 10

**Comment by junkyardsparkle** [comment]
This situation has been improved in the current development branch. :-)

**Comment by lepolau** [comment]
Thank you for your quick answer, and what more can I say, great and thank you for the work you did.
