### ISSUE TITLE
toneequalizer results in color picker Lab values >100 or rgb >256

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3050]
**Describe the bug**
if bright areas are superexposed with toneequal, the color picker can report lab values >100 or rgb > 256.
Is that intended? 

**To Reproduce**
1. open image with bright areas Go to 'toneequal'
2. increase exposure via picker on bright area to maximum
3. select bright area with color picker 

**Expected behavior**
with
 exposure or toncurve it's not possible to achieve lab values > 100

**Screenshots**
<img width="1222" alt="Bildschirmfoto 2019-09-30 um 23 32 04" src="https://user-images.githubusercontent.com/39386816/65918796-d5272980-e3da-11e9-9a54-49c563f77ae3.png">

**Platform (please complete the following information):**
 - OS: osx
 - Version: darktable 2.7.0+1921~g5734dbc38

**Comment by aurelienpierre** [comment]
I don't reproduce. What is the RGB colour profile used by the colour picker ?

**Comment by MStraeten** [comment]
i'n not shure, where the rgb colorprofile for the picker is set - i used it after a discard history in lighttable, so default settings. Here's the xmp.
[20190223-IMG_5937.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3677835/20190223-IMG_5937.CR2.xmp.txt)
and here the raw file https://mega.nz/#!ffpmRCzR!bUE1Ti4Wbx_ikwZZCwcFUbXSClvW8yZUTl6vt74qK7I

**Comment by MStraeten** [comment]
maybe this is an osx specific issue; i wasnt able to reproduce it with a windows build.

**Comment by aurelienpierre** [comment]
None of these module clips highlights anyway, so you are able to get past 100% Lab internally. The thing is the colour picker fetch colour at the extreme end of the pipe, after the output colour profile conversion, so they should be display-referred and bounded in [0; 100]. But depending the colour space you are using, I'm not sure what can happen in-between.

The setting for histogram and colour picker space is there:
![Screenshot_20191003_120350](https://user-images.githubusercontent.com/2779157/66118186-1172a980-e5d6-11e9-8a98-606dfcb8a556.png)

**Comment by MStraeten** [comment]
<img width="344" alt="Bildschirmfoto 2019-10-03 um 17 05 12" src="https://user-images.githubusercontent.com/39386816/66139049-02a0ec80-e600-11e9-9c7f-53f03057b1f3.png">
change the settings doesn't affect the values

**Comment by MStraeten** [comment]
no longer reproducible
