### ISSUE TITLE
DT opens however as soon as I begin to scroll in Lightable it just disappears from the screen spontaneously closing

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#3055]
**Describe the bug**
DT ver 2.7-1923 opens however as soon as I begin to scroll in Lightable it just disappears from the screen spontaneously closing

**To Reproduce**
1. Open darktable
2. Scroll through thumbnails
3. Program spontaneously closes instantly
4. I was able to also open an image in darkroom view and scrolling the film strip created this as well

**Expected behavior**
Scrolling thumbnails should not induce this.
No log entry was written...may try to run in debug mode but adding -d in windows does not allow the program to run...likely I have a syntax error..

**Screenshots**
nothing on the screen to show program vanishes abruptly

**Platform (please complete the following information):**
 - OS: Win 10
 - Dev version 2.7-1923

**Additional context**
I have deleted all files in the darktable config directory and the cached thumbs to start from scratch but this did not correct the problem...
[darktable-log.txt](https://github.com/darktable-org/darktable/files/3679380/darktable-log.txt)

**Comment by todd-prior** [comment]
As an update to the following issue I have printed out a log of debugging lighttable...I really can't decipher it but I think I have conflict issues in my XMP files that are messing up the pipeline....there are many entries of modules having the same iop order or needing to be in a certain location...I don't often add input and output color spaces as of late I am editing a lot of JPEG files....but the last couple of versions have been adding those modules a gamma module that I cannot find and orientation and demosaic even though the images are JPEG....anyway I may just have to try removing all the xmp files and let redo the edits....

**Comment by MaTeng211** [comment]
Hello,
just adding to this comments.
I also had this behaviour on DT Dev version 2.7-1923 running on Ubuntu 19.04.
Not a developer and savy to debug, but my investigations showed, that the crash indeed most likely was related to a specific XMP. Deleting XMPs and reimporting picture did fix the behaviour.

**Comment by aadm** [comment]
I think this is the same issue as described here:

https://github.com/darktable-org/darktable/issues/3031

**Comment by todd-prior** [comment]
@aadm thanks it seems like Pascal has some changes on his repo....holding for a bit more testing. I think they will address this. Fingers crossed...

**Comment by todd-prior** [comment]
[darktable-log (2).txt](https://github.com/darktable-org/darktable/files/3680992/darktable-log.2.txt)

Still having this issue after trying a built from the TurboGit Fork....

**Comment by todd-prior** [comment]
So if I delete all the xmp files from two of my folders that seem to be affected and allow DT to create new blank ones the collection based on that folder seems stable. If I load the original sidecars back via lighttable's load sidecars the crashing starts again and I have to delete all of the sidecar files and the library to clear the crash....I have attached one of the offending xmp files maybe there are some clues in there as to why this is happening....renamed it *.txt to allow upload
[20190801_123055.jpg.txt](https://github.com/darktable-org/darktable/files/3684409/20190801_123055.jpg.txt)

**Comment by aadm** [comment]
Unfortunately I haven't been able to do the same test as @todd-prior i.e. removing the specific xmp files and regenerating from scratch; even on a very small subset of my entire library (~500) photos I havent' been able to pinpoint a range of recently edited photos (i.e., with the latest version of DT) that may have been affected by this issue. And obviously these edits are born out of precious hours of work so the last thing I'd like to do is to erase all my edits and start from scratch... on this subset... (can't imagine doing this for the entire library!!!)

**Comment by TurboGit** [comment]
@todd-prior : with the fix in place you should have been safe if you had kept the broken db as it. that is the patch is fixing the db to ensure proper order. you can't load a broken xmp (iop-order v3).

**Comment by TurboGit** [comment]
@aadm: no worries, if you do nothing the fix put in place should fix on the fly the broken v3 iop-order. if you edit the db by hand and/or remove and try reloading the file with the broken XMP I think you are lost. Also note that the iop-order has been broken only for a short period of time.

**Comment by TurboGit** [comment]
Let me add that I'm sad about this situation, but we do our best to keep dt as stable as possible. Having something broken is part of the game when one use master every day. And yes, I do that too and had some broken edits.

**Comment by todd-prior** [comment]
@TurboGit @aadm Thanks Pascal for all your hard work to provide a fix. I was following the commits and rebuilt and reinstalled a few times over the last couple of days so I have lost track of where I am at. I did delete my database thinking it might be the problem or corrupt. I had been relying on sidecars down the road to re-import if necessary. I do have a fairly recent backup of the database from before that issue. If I update to the latest software version with the change you made today and copy back the old database files will things get sorted?? Just trying to wrap my head around the series of events that corrupted the xmp files and where the files stand currently. Before seeing you comment this AM I was going to copy a folder of older edits today and import them just to see how things go and see what happened to the xmp files....my current version is missing the one change you made today...I will update to that before trying this test and pending your comments will try to restore my old database and update that....

**Comment by todd-prior** [comment]
> Let me add that I'm sad about this situation, but we do our best to keep dt as stable as possible. Having something broken is part of the game when one use master every day. And yes, I do that too and had some broken edits.

No complaints mate....inherent risk as you say....good reason to have a non-synced back up so as not to propagate the error....this was my issue as I work on files from the cloud so they are backed up but since they are synced not safe from corruption of this kind...need to rethink that one...

**Comment by TurboGit** [comment]
> I do have a fairly recent backup of the database from before that issue. If I update to the latest software version with the change you made today and copy back the old database files will things get sorted??

Yes, it should. Hopefully we have fixed the last bit of bugs in this area. Crossing fingers.

**Comment by todd-prior** [comment]
I’ll let you know how it goes....have a nice weekend....
 
Sent from 
Mail for Windows 10
 

From: Pascal Obry
Sent: October 4, 2019 7:35 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Mention
Subject: Re: [darktable-org/darktable] DT opens however as soon as I begin to scroll in Lightable it just disappears from the screen spontaneously closing (#3055)

 



I do have a fairly recent backup of the database from before that issue. If I update to the latest software version with the change you made today and copy back the old database files will things get sorted??

Yes, it should. Hopefully we have fixed the last bit of bugs in this area. Crossing fingers.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by chhil** [comment]
Clean db.
Clean import with no xmp (12K files).
Did some tagging of images in bulk.
go midway to the list of pics in lightable.
Select 1 and then shift+up arrow to select more. At some point DT crashes.
Note: I have tried the down arrow selection and that does not crash the app.

[darktable-log.txt](https://github.com/darktable-org/darktable/files/3690353/darktable-log.txt)


23.628202 [sql] F:/msys64/home/chill/darktable/src/common/collection.c:834, function dt_collection_get(): prepare "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM images AS mi WHERE   (flags & 256) != 256  AND  (flags & 7) >= 0 AND (flags & 7) != 6  AND  (1=1) ORDER BY filename, filename , version LIMIT ?1, ?2) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3"
23.644122 [sql] F:/msys64/home/chill/darktable/src/common/collection.c:1705, function dt_collection_image_offset_with_collection(): prepare "SELECT DISTINCT mi.id FROM images AS mi WHERE   (flags & 256) != 256  AND  (flags & 7) >= 0 AND (flags & 7) != 6  AND  (1=1) ORDER BY filename, filename , version LIMIT ?1, ?2"
23.652126 [sql] F:/msys64/home/chill/darktable/src/common/collection.c:813, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
23.654122 [sql] F:/msys64/home/chill/darktable/src/common/selection.c:205, function dt_selection_toggle(): prepare "SELECT imgid FROM main.selected_images WHERE imgid=?1"
Assertion failed: !(res && pthread_equal(rwlock->writer, pthread_self())), file F:/msys64/home/chill/darktable/src/common/dtpthread.h, line 269

**Comment by aadm** [comment]
@TurboGit everything works now, excellent work! Just tested `2.7.0~git1945.d8c468a27`, I can see from the log that stuff is being done on the broken xmps, haven't lost any edit so thanks a lot!

Also thanks for the nice words but don't worry, it's up to us using these untested version, and we kinda have to work having in mind potential instability. After 2.7 final will come out I will stop messing around with the nightly builds and let developers do their work while I as a normal and happy end-user will carry on using DT to edit my photos without worrying too much about novelties (I realize that in the end I use maybe 20% of all the modules).

**Comment by TurboGit** [comment]
@aadm: thanks a relief to read this! it has been a hard journey.

The branch is now waiting for review and will be merged soon I hope.

**Comment by TurboGit** [comment]
Fix merged.
