### ISSUE TITLE
Enabled modules not showing up as enabled.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3056]
**Describe the bug**
Enabled modules not showing up as enabled.

**To Reproduce**
1. Open an image to edit.
2. Edit image in darkroom.
3. Double click in grey area , takes you to lightable view.
4. Double click on image you were editing.
5. In darkroom the modules that are in history are not shown as enabled 
If you toggle show only active modules it shows the correct enabled and if you click it again to disable it it still shows the active module, this gets it into the right state.

**Expected behavior**
Enabled modules should show up as enabled.

**Screenshots**
You can see local contras in the history but its not enabled in the modules panel
![image](https://user-images.githubusercontent.com/1119439/66025367-ed4e9400-e513-11e9-8456-e1b4bcf00a08.png)

**Platform (please complete the following information):**
darktable-2.7.0+1924~g4704995bb-win64

**Comment by jenshannoschwalm** [comment]
I think this is fixed. Please concide to close issue :-)

**Comment by chhil** [comment]
Tested on 2.7.0.2054. Its working.

**Comment by Nilvus** [comment]
@TurboGit : should be closed as it is fixed.

**Comment by TurboGit** [comment]
Indeed, closing.
