### ISSUE TITLE
Darktable themes other than the "darktable" one mess up the fonts

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3057]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1119439/66030698-8afb9080-e51f-11e9-8ee0-9702b929b5d3.png)

The fonts in history and the parameters inside module look horrible.

**Comment by aurelienpierre** [comment]
You need to disable the font hinting and anti-aliasing in Gnome fonts preferences or GTK fonts settings.

**Comment by chhil** [comment]
I am on windows, don't know where I would do it.

**Comment by aurelienpierre** [comment]
So it's in Microsoft Clear Type options : https://www.howtogeek.com/howto/28790/tweak-cleartype-in-windows-7/

**Comment by hellbuster** [comment]
Maybe the fact of using too thin font weight should be given more though, suggesting to disable system level hinting and aliasing doesn't sound too robust for a solution.

**Comment by hellbuster** [comment]
I found something strange, according to this https://fonts.google.com/specimen/Roboto, Roboto Light shouldn't be so thin. Maybe the combination of the font and `font-weight: 200` is giving problems?

**Comment by aurelienpierre** [comment]
Roboto provides a thin variant (`font-weight: 100`) and a light one (`font-weight: 300`). So I rather think some software is playing smart-ass by interpolating or de-aliasing. I saw that issue in the past, both on Windows and Gnome/Linux. As a matter of fact, font anti-aliasing is quite ugly and non-necessary on high-dpi screens.

**Comment by hellbuster** [comment]
@aurelienpierre but then, we should use 300 as the font weight instead of 200, right?

**Comment by aurelienpierre** [comment]
You use whatever you want, the soft is supposed to pick the closest font variant if available.

**Comment by phweyland** [comment]
On my windows machine, Segoe UI and Roboto both fail on the sizing standpoint.
About Roboto it seems that Roboto Light is not recognized but the generic Roboto follows the weighting. I've downloaded it from Google. 
I've tried also to tweak Microsoft Clear Type options without success.

**Comment by chhil** [comment]
I have all the fonts downloaded and installed. My clear type is tuned for my regular use and wont be touching it for one app doesn't work well with the fonts. I will just use the darktable theme though I used to like the darktable + icons theme. None work as expected ,  except one.

**Comment by aurelienpierre** [comment]
So maybe Roboto Light has a different name on your system or just needs to be called "Roboto" then selected through its font weight. I will try a fix.

**Comment by chhil** [comment]
Raw therapee which also uses GTK allows one to pick a font and the roboto font looks alright in the raw therapee UI.
![image](https://user-images.githubusercontent.com/1119439/66188908-2dde1700-e6a6-11e9-9b36-8d637c809dd7.png)


![image](https://user-images.githubusercontent.com/1119439/66189027-6da4fe80-e6a6-11e9-8217-b12a428c77f0.png)

The s

**Comment by aurelienpierre** [comment]
That tells us they don't use CSS to configure the fonts. Maybe it's part of the problem ?

**Comment by TurboGit** [comment]
Or that RawTherapee does not use the same Gtk version. Fact is that on Wndows all this is non standard, so hard to tell as there is a whole bunch of layers that can be failing!

**Comment by chhil** [comment]
They do have CSS for font related properties but not the font name/family.

> Maybe it's part of the problem ?
This world of GTK is new to me and the only reason I know a little bit as I decided to understand darktable.

**Comment by aurelienpierre** [comment]
The easiest way should be to ask a nice RawTherapee dev how they do it.

@heckflosse ? :-)

**Comment by TurboGit** [comment]
@chhil : since darktable.css is working and all this is CSS, maybe you could try to change darktable-elegant.css by removing/changing some fonts to try to see what is going wrong?

Aurélien and I don't have Windows machines... It will takes ages to send you possible fixes to try.

How does that sounds?

**Comment by TurboGit** [comment]
@aurelienpierre :
```
$ ls /usr/share/rawtherapee/themes/
 images                             TooWaBlue-GTK3-_19.css
 RawTherapee-GTK3-_19.css           TooWaBlue-GTK3-20_.css
 RawTherapee-GTK3-20_.css          'TooWaGrey - Average Surround-GTK3-20_.css'
 size.css                          'TooWaGrey - Bright-GTK3-20_.css'
 system.iconset                    'TooWaGrey - Dark-GTK3-20_.css'
'TooWaBlue - Bright-GTK3-20_.css'   TooWaGrey-GTK3-20_.css
'TooWaBlue - Dark-GTK3-20_.css'
```
Now the hardest part is to get the right section :)

**Comment by TurboGit** [comment]
In the RT CSS I don't see any "font-weight: <number>" , maybe the issue? Some weight that can't be natively rendered and need to be created-on-the-fly? I would try removing them.

**Comment by TurboGit** [comment]
@chhil : thanks !

**Comment by phweyland** [comment]
> maybe you could try to change darktable-elegant.css by removing/changing some fonts to try to see what is going wrong?

As far as I can see in the initial screenshot above, the font height is 6 pixels for lower case (as on my machine), which is not enough.

As you can also see in RT screenshot, the user can also choose the font-size (I think that's more or less equivalent to change the DPI). Letting the user choose the main font and size would help to fit with different screen sizes / dpi.

**Comment by heckflosse** [comment]
@aurelienpierre 

> @heckflosse ? :-)

I hate gui coding ;-) Maybe @Hombre57 knows more about the font stuff and can give you some hints
