### ISSUE TITLE
OpenCL RGB<->Lab colour conversions are painfully slow

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3059]
Native RGB modules placed in the Lab part of the pipe get an input and output colour conversion to the expected spaces. 

I'm implementing filmic RGB OpenCL version, which happens in the Lab part of the pipe and needs these conversions done externally.

Filmic v2 performed the same operations internally (Lab -> RGB -> log + tone curve -> RGB -> Lab) in 8 ms on my system.

Now, in the same conditions, the Lab<->RGB conversions alone take 5-7 ms each (12 ms total average), and a dummy OpenCL kernel (copy input to output) takes 18 ms itself.

I have tried to optimize the colour conversions (inline functions and improve vectorization), or do the opposite and try to make the kernel perform heavy ops, but I get ±2 ms change top. At that point, I suspect an issue with memory buffers handling.

Where could the bottleneck be ? We are talking about ×3 slow-downs here.

Possibly related to #2191 and #2891

**Comment by jenshannoschwalm** [comment]
> a dummy OpenCL kernel (copy input to output) takes 18 ms itself.

No real idea. Just guessing: Aligning? Related to _width_ of data somehow? Some mutex blocking?

**Comment by jenshannoschwalm** [comment]
On more idea although i confess i don't understand what **exactly** you are measuring. Could you hint at code in your fork?

Could your measuring be affected by the pipeline change introduced by #2772 ?
(your code being fast but waiting for some synchronising)

**Comment by aurelienpierre** [comment]
At this point I have optimised the colour space conversion for CPU only, reordering loops, and got maybe a ×3 to ×4 speed-up in RGB <-> Lab conversions.

For the GPU/OpenCL code, I suspect image buffers go back and forth in memory, between RAM and vRAM, which causes a lot of memory copy overhead, and badly degrades performance such that the OpenCL colour space conversion on GPU takes overall twice the time needed on CPU.

Anyway, I'm working on that, we will see what can be done.

**Comment by aurelienpierre** [comment]
> No real idea. Just guessing: Aligning? Related to width of data somehow? Some mutex blocking?

To be more specific, this happens only if the OpenCL kernel is put in-between a Lab -> RGB -> Lab roundtrip. Other kernels are fine.
