### ISSUE TITLE
[LUT 3D] output image looks very different from what the output looked like from a 3DLUT creator app.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3062]
**Describe the bug**
The LUT3D module output does not match the output of LUT in a 3D LUT creator app.

**To Reproduce**

Made changes to a raw file in darktable.
Exported output as tiff and imported it into 3D LUT creator.
Made changes in there and exported 3D LUT cube file.
Now in darktable on edited image I used the LUT 3D module as the next step.

The images below shows what the 3D LUT creator comparison of TIFF as before and the transformed as after.

![image](https://user-images.githubusercontent.com/1119439/66097489-31956f00-e5bc-11e9-9698-da58cf74b224.png)

The image below shows the before applying LUT and after applying LUT in darktable.

![image](https://user-images.githubusercontent.com/1119439/66097716-24c54b00-e5bd-11e9-9af5-135f91941ea4.png)
Left is after, right is before.

I tried changing opacity at 10% increments and could not get the output as the expected.

**Comment by chhil** [comment]
Here is the same LUT applied in GIMP. It has the desired output.

![image](https://user-images.githubusercontent.com/1119439/66099022-b3889680-e5c2-11e9-9daa-1c59e2b2c207.png)

**Comment by chhil** [comment]
Ok figured out the problem.

The LUT #D module should be the last one in your pipeline in my case. I think in general it would make sense to grade/apply LUT after all raw processing.

![image](https://user-images.githubusercontent.com/1119439/66100456-a8386980-e5c8-11e9-82a6-3cf26a7e6788.png)

Does the Lut 3D IOP order need to change?

**Comment by TurboGit** [comment]
The LUT 3D module should be between color input and color output.

Where was it for the buggy blue image?

**Comment by chhil** [comment]
I compressed history and got rid of Lut 3D.
Then I selected and enabled Lut 3d and selected the cube file.
In the pipeline it gets inserted outside color  input and color output.
![image](https://user-images.githubusercontent.com/1119439/66128945-8365e580-e60c-11e9-869c-d1b006c8b68a.png)

**Comment by TurboGit** [comment]
So that wrong indeed. 

@chhil I think you have seen the numerous issues reported because of a bug in iop-order? So I think you can close all your recent reports, they all seems related to this issue being worked on.

**Comment by chhil** [comment]
I was going through the issues I had opened and I can't say if its IOP related or not.

This one for example is, will the insert order change and should I close this prior to that?

**Comment by wilecoyote2015** [comment]
Interesting: The lut3d results were correct for me with my last build (maybe from one month ago), but with recent master I notice this issue, too.

Furthermore, changing the application color space has no effect. Hence, I'd guess that the color space transform into the application color space is not performed anymore?

**Comment by wilecoyote2015** [comment]
Seems like the lut3d module is placed before input color profile in the new iop order.

**Comment by TurboGit** [comment]
@aurelienpierre : do you confirm that 3dlut must be between input & output color profile?

**Comment by wilecoyote2015** [comment]
Seems reasonable to me, as an LUT represents a color space transform and hence it can only be applied on data that has been transformed into the source color space the LUT has been engineered for.

**Comment by aurelienpierre** [comment]
LUT 3D should come right after colorin and colorchecker, before further colour grading, and colorout.

**Comment by TurboGit** [comment]
@aurelienpierre : so my proposed patch (#3075) is wrong as it comes just after colorin. it seems that mixing rules after/before in iop_order.c does not works properly.

**Comment by chhil** [comment]
> LUT 3D should come right after colorin and colorchecker, before further colour grading, and colorout.

Should the position be based on a users workflow?
This is what I had done here, did all the tweaks in DT and then applied a LUT to it. So according to my flow it should be at the very end of the pipe.

I can understand someone has a image shot in say a cineD  profile on camera and may apply a cineD to maybe a rec709 lut at early stage and then do the grade.

**Comment by TurboGit** [comment]
@chhil : you can always move it around to the position you want it to be.

**Comment by TurboGit** [comment]
Fix merged.

**Comment by chhil** [comment]
Thank you.

**Comment by allcracksoft** [comment]
This the best website where i visit this site very often. i found so much of information from this site. i’m very much satisfied with this.Thank you admin Foodies Pie
https://allcracksoft.org/3d-lut-creator-crack/
