### ISSUE TITLE
crash in color_picker if colorreconstruction is outside input/output profile

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3065]
**Describe the bug**
Using the color picker from color reconstruction ended up in a crash.
```
[dt_ioppr_transform_image_colorspace] module colorreconstruct must be between input color profile and output color profile
[dt_unreachable_codepath] {unreachable} /Users/martinstraeten/src/darktable/src/common/color_picker.c:420 (dt_color_picker_helper) - we should not be here. please report this to the developers.Illegal instruction: 4

```

**To Reproduce**
1. added attached history stack to multiple raw files 
[20190223-IMG_5937_01.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3685490/20190223-IMG_5937_01.CR2.xmp.txt)
2. add module colorreconstruction (it's added outside input and output profile)
3. enable parametric mask
4. click color picker icon

seems to be related to iop_order in existing history stacks, since i'm not able to reproduce it starting from scratch.

**Expected behavior**
color reconstruction is in correct place
or color reconstruction is disabled if not in correct place

**Platform (please complete the following information):**
 - OS: OSX
 - Version: this is darktable 2.7.0+1934~gd3aa70553

**Comment by junkyardsparkle** [comment]
Maybe #3067 fixes this?

**Comment by aurelienpierre** [comment]
Could you try to enable the global preference "always use LittleCMS2", to see if the error persists ?

Unreachable code path can mean several things and can be related to SSE2 vs. OpenMP SIMD codepaths (to enable/disable in darktablerc) or related to a colour conversion with an unhandled colour profile, this possibly an issue in iop_order indeed.

**Comment by MStraeten** [comment]
enabling the LittleCMS2 preference and the pr #3067 doesn't fix. Exploring history table in library i found colorout having iop_order 58 and 63.5 (colorin between 8.x and 27.x) maybe the best way for me is to update the iop_order on database level ;) - But that doesnt solve the potential issue of a code segment, that shouldn't be executed ...

**Comment by MStraeten** [comment]
the pr #3067 seems to avoid getting the misalignment of colorreconstruction in the iop order - the history stack i attached in the original post seems to be the result of some of the numerous changes of iop_orders in former pull request i includes (found messed up iop orders for edits since 24.8. having iop version 2 )

**Comment by TurboGit** [comment]
> enabling the LittleCMS2 preference and the pr #3067 doesn't fix.

> the pr #3067 seems to avoid getting the misalignment of colorreconstruction in the iop order

Ok, at least #3067 does it's job and then the way to reproduce above step 2 is misleading, right?

**Comment by TurboGit** [comment]
And looking at the point of crash it really looks like an iop-order issue which should be fixed. I cannot reproduce this on my side with colorereconstruction at the default order in the pipe.

**Comment by MStraeten** [comment]
i reset all images having iop_order_version 4 back to 3 and after reordering everything is fine. this also helped for edits messed up iop orders and version 2.
--> so i close
