### ISSUE TITLE
Contrast equalizer, stange image color and blurring behavior when apply

### ISSUE THREAD

**Issue by kikoucalou** [darktable-org/darktable#3066]
Dt 2.7.0+1935~g202df068c on linux mint

From fresh compilation and clean install, when apply Contrast Equalizer preset Noise reduction and accentuation, image change with  strange color behavior and very blurring

See samples whith and whitout Contrast Equalizer preset applied:

![DSC00935_02](https://user-images.githubusercontent.com/7946021/66123260-db3b2700-e5e1-11e9-944b-782671cffc0a.jpg)
![DSC00935_03](https://user-images.githubusercontent.com/7946021/66123287-e8f0ac80-e5e1-11e9-933c-a5c905c2830e.jpg)

**Additional context**
Works nicely before 2019-10-01 changes

BRGDS

Pascal LACROIX

**Comment by kikoucalou** [comment]
I never had before such strange change whith same process. 

My Color profile input is before. 
It hapen when « denoise & sharpen » presets is apply from Contrast Equalizer

My DT is just build today 2019-10-03 from latest git master download

**Comment by TurboGit** [comment]
Cannot reproduce with today build.

**Comment by kikoucalou** [comment]
I play again with  presets "sharpen" : a green color cast happen on shadows 

I just made a test with new clean clowned image and only Filmique rgb  and contrast equalizer (sharpen preset), its look working fine like that 

(xpm)

 <rdf:li
      darktable:num="8"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="9a9913410ad78bc00ad78b403333b3419a999341000000000000c842f6281c400000c8410000a03f000000000000000001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="47.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="9"
      darktable:operation="atrous"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="gz05eJxjZ4CAs2d87M6eOWM3a6akPZBtz8DQYE8HcfvwFl771RzS9ky9GvaRgmb266Y6g8VJxCQBAMcENw0="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="32.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>

Back to my  problematic image  (xpm):

 <rdf:li
      darktable:num="9"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="00000441514b83c0514b83403333b3419a999341000000000000c8423a0d1c400000c8410000a03f90ebe1400000000001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="47.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="10"
      darktable:operation="colorbalance"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="010000000000803fd7a3803f3a6d803f52b87e3f0000803fd7a3803f52b87e3fd7a3803f0ad7633f3233733f7777773f6766863f0000803f3333733f000010406666663f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="40.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="11"
      darktable:operation="colorcorrection"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="00f1fd3f40933d4000000000000000000000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="53.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="12"
      darktable:operation="atrous"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="gz05eJxjZ4CAs2d87M6eOWM3a6akPZBtz8DQYE8HcfuQx5z2K44J2/9ZKWsf0Ktuv6TAECxOIiYJAAC8AzlG"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="32.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>

Perhaps something is very wrong with my color-balance and color-correction between filmic rgb and atrous. But I often do that an never had such side effect before.

Aurelian will probably think that I apply my modules according to a sacrilegious order, it is ignorance

**Comment by aurelienpierre** [comment]
No sacrilegious order here :D, it should behave as supposed. 

The real stopping point here is the input colour profile (output as well, but it seems to cause fewer issues), you need to check that the Lab modules are put between both profiles in the pipe. Since they are not provided in your XMP here, maybe the in/out color profile don't get a proper entry into the history, and their priorities are messed up.

**Comment by kikoucalou** [comment]
I am not sure to understand; 

here is the full XMP module list

<rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="000000000000000020000000000000000002000200020002ac3f0000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="1.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="1"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="00401b400000803f0080d93f0000c07f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="3.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="2"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="000000000000803f00000000000000000000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="4.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="3"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="7.5000305175781"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="4"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz48eJzjYRgFowABWAbaAaNgwAEAPRQAEQ=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="37.5000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="5"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="gz35eJxjZBgFo4CBAQAEEAAC"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="63.5000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="6"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="71.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="7"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="8.0078125000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="8"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="000000000000000041bbff3e00004842000080c0"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="21.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="9"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="00000441514b83c0514b83403333b3419a999341000000000000c8423a0d1c400000c8410000a03f90ebe1400000000001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="47.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="10"
      darktable:operation="colorbalance"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="010000000000803fd7a3803f3a6d803f52b87e3f0000803fd7a3803f52b87e3fd7a3803f0ad7633f3233733f7777773f6766863f0000803f3333733f000010406666663f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="40.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="11"
      darktable:operation="colorcorrection"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="00f1fd3f40933d4000000000000000000000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="53.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="12"
      darktable:operation="atrous"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="gz05eJxjZ4CAs2d87M6eOWM3a6akPZBtz8DQYE8HcftP3az2T8S57a8vFrA/pS9mv2e3NFicREwSAACwpzkt"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="32.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
    </rdf:Seq>

**Comment by aurelienpierre** [comment]
As I said in my first message, in your full XMP:
* atrous (contrast equalizer) has iop_order = 32
* colorin (input profile) has iop_order = 37.5

So colorin comes after atrous in your pipeline, which explains what you see because it's not supposed to happen. You need to reorder these 2 modules.
