### ISSUE TITLE
Sony ILCE-7RM4 camera support

### ISSUE THREAD

**Issue by ErnstTmp** [darktable-org/darktable#3070]
Hello,
when I try to read a raw image from my SONY 7alpha R4, I get an error message and I can not edit the image.

I uploaded 3 Raw Images from my camera to raw.pixls.us, and can upload more if you need them.

temperature] failed to read camera white balance information from `20191003_0021.ARW'!
[temperature] `SONY ILCE-7RM4' color matrix not found for image
[temperature] failed to read camera white balance information from `20191003_0021.ARW'!

Thank yo very much for your help!
Ernst

**Comment by MStraeten** [comment]
Its not yet supported. Try building current master with pr #2942

**Comment by ErnstTmp** [comment]
@MStraeten: Thanks, I did that! 
unfortunately, now I get 
[colorin] `SONY ILCE-7RM4' color matrix not found!

**Comment by LebedevRI** [comment]
@ErnstTmp
Please see disscussion in https://github.com/darktable-org/rawspeed/pull/202
This will not be resolved until full raw sample set for that camera is contributed to [RPU](https://raw.pixls.us/).
To recap, 4 samples are needed: 14bit comressed, 14bit uncompressed, 12bit compressed, 12bit uncompressed.
Use single-shot mode for 14bit raws, and see https://www.sony.com/electronics/support/e-mount-body-ilce-7-series/ilce-7rm4/articles/00229990 for how to produce 12bit samples.

**Comment by ErnstTmp** [comment]
@LebedevRI thanks a lot for your feedback! I hope I can upload all you need in the next few days.

**Comment by LebedevRI** [comment]
(To be noted, to read through the blurb on [RPU](https://raw.pixls.us/) beforehand - all images should preferably have the same content, outside daylight landscape works best, no people)

**Comment by LebedevRI** [comment]
Samples recieved & reviewed, will handled soon.
