### ISSUE TITLE
RGB tone curve & levels don't support multiple instances

### ISSUE THREAD

**Issue by cigno5** [darktable-org/darktable#3071]
**Describe the bug**
Any multiple instances of RGB Tone Curve or RGB Levels module will be lost as soon as we leave the darkroom for the image

**To Reproduce**

- Open any image file (attempt done with CR2 Canon raw file from Canon 6D) in the darkroom
- Enable "rgb level", use a mask to apply only to a part of the image
- Create second instance of "rgb level" module, use different settings, apply different mask
- Double click on the same image in the filmstrip under the image
    - (as an alternative press spacebar to go to the next image and backspace to get back to same image)
- The second module's instance is gone, only the first remains. 
- (apparently the mask created for the second instance is kept)

**Expected behavior**
darktable should keep the second module

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS 
 - darktable version 2.7.0+1943~g3f12d6d7e

**Comment by aurelienpierre** [comment]
Can you confirm or deny these :

1. other modules behave as expected ?
1. these faulty modules behave as expected with no mask or parametric blending ?
1. second instances of modules are kept as they should when changing images from the lighttable (and not the filmstrip) ?

**Comment by cigno5** [comment]
1. Other modules behave as usual (tried explicitly with normal level and tone curve module) 
2. Same faulty behavior without masking. Haven't tried with parameter blending though. 
3. Second instance is lost as soon as you leave the darkroom (eg switching back to the light table) 

Moreover no difference  if you rename the instance or if you leave it with the progressive counter.

**Comment by cigno5** [comment]
My gut feeling is that something happens when darktable saves changes into xmp file.

**Comment by TurboGit** [comment]
Cannot reproduce !

**Comment by cigno5** [comment]
This evening I will try to make it happens starting from scratch, I will clean settings and I will try to do it again. 

I tried with different files in the both same folder and different folder. If I still have the problem I will post a sample file with the related xmp file.

Do you have any advice (log enabled, log level, any tricks...) to have a better insight of what is going on on my machine? Any other important environmental property to show here?

**Comment by cigno5** [comment]
Ok, I've done further and deeper tests: the issue is actually not reproducible if I import from scratch the picture into darktable, deleting first the xmp file.

**I found a workaround: the 'discard' button in the history stack panel resets everything, and then darktable behaves as expected** (this also means that I lost all drawn masks!)

But, for sake of knowledge, here it follows the workflow:

- I duplicate the image and I reset history cutting off everything above standards applied modules (+ sharpen):
![01](https://user-images.githubusercontent.com/11832142/66225870-ce016380-e6d9-11e9-8be4-e002c90dd8c5.png)
- then I enable first 'rgb module' and I make changes
- then I create second instance, rename it to "second", make changes and apply a drawn mask:
![03](https://user-images.githubusercontent.com/11832142/66225972-0608a680-e6da-11e9-9bb6-77a72788ffbb.png)
- Double click on the filmstrip (not leaving darkroom) and I see second instance disappear:
![04](https://user-images.githubusercontent.com/11832142/66226013-22a4de80-e6da-11e9-98ed-a17d8344be1a.png)

Then I looked into the xmp file and I can see both instances at the end of the of the history. 

[0164_02.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3691584/0164_02.CR2.xmp.txt)


```xml
[...]
   <darktable:history>
    <rdf:Seq>
[...]
     <rdf:li
      darktable:num="10"
      darktable:operation="rgblevels"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="000000000100000000000000d05dd63dd05d563e000000000000003f0000803f000000000000003f0000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="50.2500000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="11"
      darktable:operation="rgblevels"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000001000000000000000000003f0000803f000000000000003f0000803f000000000000003f0000803f"
      darktable:multi_name="second"
      darktable:multi_priority="1"
      darktable:iop_order="50.3750000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>
     <rdf:li
      darktable:num="12"
      darktable:operation="rgblevels"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="00000000010000000000000057682e3e5768ae3e000000000000003f0000803f000000000000003f0000803f"
      darktable:multi_name="second"
      darktable:multi_priority="1"
      darktable:iop_order="50.3750000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="gz10eJxjZmBgkGAAgRNOIHJB+fRYBihgZCAWNNhD8EjlYwcArxgbEg=="/>

[...]
    </rdf:Seq>
   </darktable:history>
```
After this I quit darktable and I reopen the same file again: the xmp file is half of the size, and the second instance is definitely disappeared from the file as well.

[0164_02_after_re-opening.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3691585/0164_02_after_re-opening.CR2.xmp.txt)

**Comment by jenshannoschwalm** [comment]
Yet another iop_order problem, here we have in your attached xmp
>    darktable:iop_order_version="1">

I guess you had developed that image earlier and reimported with existing xmp file, correct?

@Turbogit Any other explanation? I don't think this scenario is currently supported in `_ioppr_legacy_iop_order_step`

**Comment by cigno5** [comment]
> I guess you had developed that image earlier and reimported with existing xmp file, correct?

Actually I haven't reimported it. I've edited the picture a while ago, then I duplicated the picture and I duplicated again from the previous clone. Then I cut the history to keep crop&rotate and started over with new modules to see difference. 

From the first edit and the second I have definitely compiled darktable more than once

**Comment by cigno5** [comment]
Confirmed same behavior for all images in the same folder and re-imported. Changing manually `iop_order_version` to 4 doesn't do the trick and it is reverted to 1 as soon as dt saves the changes.

dt should convert those files when reimported.

The only way to overcome the problem is duplicate, discard history, and copy & paste history stack. It also imports masks correctly.

**Comment by jenshannoschwalm** [comment]
> Changing manually iop_order_version to 4 

Don't do that :-) Will make things worse.

> dt should convert those files when reimported.

Yes. Needs further attention, definitely!

**Comment by TurboGit** [comment]
> @TurboGit Any other explanation?

No, I confirm that this is an issue with the fact that iop_order_version is set to 1.

But it seems that this is affecting only with modules introduced AFTER the iop_order_version of the image. I had the change to have an image with iop_order_version = 1 and was able to reproduce the issue with "rgb levels" but also with "filmic rgb" but not with "levels" which was existing in v1.

So, definitely a bug to fix but we don't want to migrate from v1 to newer version as we must keep original order used for the edit.

**Comment by cigno5** [comment]
Yes I confirm that the bug affects only modules appeared after `iop_order_version=1`. Normal "levels" and tone curve modules worked as expected. 

I agree you have to keep retroactive compatibility, but, in my opinion, when you edit a picture already developed in the past, as soon as you enable a module which works with higher version of the "iop_order", darktable should upgrade the xmp file. It's actually a on-the-fly migration. As it is now, as far as I understood, whatever picture I take from my archive I could encounter the same issue. 

I should study the code but I'm not used to C programming!

**Comment by TurboGit** [comment]
I made some progress, it looks like we need an auto migration from v1 -> v2 as v2 is only v1 plus the new modules.
