### ISSUE TITLE
history issue/doubts

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#3073]
On the snapshot the symbol /!\ may tell me that filmic is deprecated (I don't see it anymore in the module list). Is that correct ?

What is gamma (entry 7) ?
gamma is not in the list of modules. 
Should have it the same deprecated symbol /!\ ?
Is that an other name of unbreak input profile ?

How can I remove a deprecated module without losing the most recent history (as I cannot deactivate it) ?

![image](https://user-images.githubusercontent.com/23012047/66189656-87d0e380-e68a-11e9-94ea-227216736f5e.png)

 - OS: windows 10
 - Version 2.7 20191004

**Comment by TurboGit** [comment]
> On the snapshot the symbol /!\ may tell me that filmic is deprecated (I don't see it anymore in the module list). Is that correct ?

Yes correct.

**Comment by TurboGit** [comment]
> What is gamma (entry 7) ?

A mandatory module hidden in previous version.

> gamma is not in the list of modules.

Right. That the last module in the pipe. It is mandatory and cannot be removed.

> Should have it the same deprecated symbol /!\ ?

No, as it is not deprecated.

> Is that an other name of unbreak input profile ?

No.

**Comment by TurboGit** [comment]
> How can I remove a deprecated module without losing the most recent history (as I cannot deactivate it) ?

First you are not forced to remove it. Filmic will stay supported for as long as dt is running.

To remove it and for example use FilmicRGB instead, on darkroom:
- change some values on Filmic to have it top of the history stack
- compress history stack
- filmic is now to of the list
- select history just below
- compress and it is gone
- enable FilmicRGB now and redo the dev with this new module

Hope this helps!

**Comment by chhil** [comment]
@phweyland 
Depends on which version you are, a deprecated module will show you the module in the list. There was an issue with an older version  where it did not show up when you searched for it. Then it got fixed. So the image with deprecated modules still allows you to edit with deprecated modules. 

For new images you wont see deprecated modules.

You can read about it here
https://github.com/darktable-org/darktable/issues/2995

**Comment by phweyland** [comment]
Thanks. Cristal clear.
