### ISSUE TITLE
Darktable crashes when importing large number of images

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3074]
**Describe the bug**
Installed DT on a new system. 
Fresh DB.
Imported 12K + images from folders (recursing).  Images had xmp files.
DT crashed.

Log 
[Uploading darktable_bt_TV1V8Z.txt…]()

AddrPC           Params
00000000151D70D0 00000000051D4990 0000000064942DE8 0000000000000000  libtemperature.dll!process_sse2._omp_fn.1  [F:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/xmmintrin.h @ 931]
   929: _mm_load_ps (float const *__P)
   930: {
>  931:   return *(__m128 *)__P;
   932: }
   933: 

OS : Win 10 	
Version 2.7.0.1943

**Comment by TurboGit** [comment]
It is:
https://github.com/darktable-org/darktable/issues/3055#issuecomment-538310346

**Comment by chhil** [comment]
On a clean DB, and 12K files with no xmps, the import worked with no crash. Then did a selection test and selected 700+ images using shift+down arrow, no crash here either.
