### ISSUE TITLE
OpenCL not supported Windows 10

### ISSUE THREAD

**Issue by ForresterAlex** [darktable-org/darktable#3078]
Clean install of Darktable 2.6.2 on windows 10, OpenCL is "not available".

Darktable refuses to use OpenCL or any type of GPU acceleration. All rendering is done on CPU.

Is it possible that Darktable just lacks support for OpenCL on RDNA (NAVI) GPUs?

Hardware:
5700xt
x470 Asrock SLI/Master AC
2700x
16GB ram
256GB SSD NVME

GPU info:
Graphics Card Manufacturer - Built by AMD
Graphics Chipset - AMD Radeon RX 5700 XT
Device ID - 731F
Vendor ID - 1002
SubSystem ID - 0B36
SubSystem Vendor ID - 1002
Revision ID - C1
Bus Type - PCI Express 4.0
Current Bus Settings - PCI Express 3.0 x4
BIOS Version - 017.001.000.042
BIOS Part Number - 113-D1820501-101
BIOS Date - 2019/06/16 22:38
Memory Size - 8176 MB
Memory Type - GDDR6
Memory Clock - 875 MHz
Core Clock - 1755 MHz
Total Memory Bandwidth - 448 GByte/s
Memory Bit Rate - 14.00 Gbps
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
OpenGL® API Version - 4.6
OpenCL™ API Version - 2.0

GPU driver info:
Radeon Settings Version - 2019.0910.1749.32088
View Release Notes - https://www.amd.com/en/support/kb/release-notes/rn-rad-win-19-9-2
Driver Packaging Version - 19.30.03.01-190910a-346729E-RadeonSoftwareAdrenalin2019
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1634
Direct3D® Version - 9.14.10.01410
OpenGL® Version - 26.20.11000.13571
AMD Audio Driver Version - 10.0.1.12
Vulkan™ Driver Version - 2.0.106
Vulkan™ API Version - 1.1.119

**Comment by AxelG-DE** [comment]
In general opencl works on Win10, as my labtop does so. 

In particular for your case, sorry, I cannot be of much help.

**Comment by ForresterAidan** [comment]
> 
> 
> In general opencl works on Win10, as my labtop does so.
> 
> In particular for your case, sorry, I cannot be of much help.

Do you have any idea whether it is a problem with AMD OpenCL? what GPU is your laptop using?

**Comment by AxelG-DE** [comment]
it might be yoru AMD driver, yes
my labtop uses an CPU internal HD5500 which had to be activated manually as the devs say, the onCPU GPUs are worthless, but I find 7% or so, hence I use it :-)

**Comment by aurelienpierre** [comment]
It might just be a matter of telling darktable (in darktablerc) where the OpenCL lib is installed (OpenCL path). darktable will look for standard places, maybe it's not there.

**Comment by ruudmaas** [comment]
What directory i do have to find the OpenCL lib?

**Comment by ForresterAidan** [comment]
> 
> 
> It might just be a matter of telling darktable (in darktablerc) where the OpenCL lib is installed (OpenCL path). darktable will look for standard places, maybe it's not there.

Where would I define the path to the OpenCL lib, and what would that path be?

**Comment by AxelG-DE** [comment]
In Win, is it possible even, to start darktable out of a shell and pass the option "-d opencl"?

**Comment by fhug** [comment]
On Windows, you can run C:\Program Files\darktable\darktable-cltest.exe in a command prompt to debug openCL. 
To get darktable to have openCL available on my PC, I had to install it in a folder without space (C:\darktable). Using the default install location makes openCL not available in darktable.
I don't have the issue on my laptop (Intel HD5500). My PC has a AMD Radeon RX550.

**Comment by peterbud** [comment]
> To get darktable to have openCL available on my PC, I had to install it in a folder without space (C:\darktable). Using the default install location makes openCL not available in darktable.

That's misleading as a blanket statement. OpenCL in darktable works even when you install it in a folder with space(s) in the file name like `C:\Program Files\darktable`. So it might be that _some_ OpenCL drivers are having issues with folder names with space, but Nvidia, AMD and even Intel drivers are working with such folders.

**Comment by BigSerpent** [comment]
Hello. I have a similar problem with 3.0 rc1 on Windows 10. Sometimes darktable detects OpenCL, sometimes - not.  

c:\Program Files\darktable\bin>darktable-cltest
0.071042 [opencl_init] opencl related configuration options:
0.074042 [opencl_init]
0.076042 [opencl_init] opencl: 1
0.078043 [opencl_init] opencl_library: ''
0.080042 [opencl_init] opencl_memory_requirement: 768
0.083044 [opencl_init] opencl_memory_headroom: 300
0.086045 [opencl_init] opencl_device_priority: '*/!0,*/*/*'
0.090046 [opencl_init] opencl_mandatory_timeout: 200
0.093047 [opencl_init] opencl_size_roundup: 16
0.096047 [opencl_init] opencl_async_pixelpipe: 0
0.099048 [opencl_init] opencl_synch_cache: false
0.102049 [opencl_init] opencl_number_event_handles: 25
0.104049 [opencl_init] opencl_micro_nap: 1000
0.106049 [opencl_init] opencl_use_pinned_memory: 0
0.109053 [opencl_init] opencl_use_cpu_devices: 0
0.111051 [opencl_init] opencl_avoid_atomics: 0
0.112051 [opencl_init]
0.114052 [opencl_init] found opencl runtime library 'OpenCL.dll'
0.117052 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
0.197072 [opencl_init] found 1 platform
0.200071 [opencl_init] found 1 device
0.202073 [opencl_init] device 0 `Ellesmere' supports image sizes of 16384 x 16384
0.207075 [opencl_init] device 0 `Ellesmere' allows GPU memory allocations of up to 4048MB
[opencl_init] device 0: Ellesmere
     GLOBAL_MEM_SIZE:          8192MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 1024 ]
     DRIVER_VERSION:           2906.10
     DEVICE_VERSION:           OpenCL 2.0 AMD-APP (2906.10)
0.572176 [opencl_init] options for OpenCL compiler: -w  -DAMD=1 -I"c:\Program Files\darktable\share\darktable\kernels"
0.581179 [opencl_init] compiling program `demosaic_ppg.cl' ..
0.596182 [opencl_load_program] loaded cached binary program from file `C:\Users\rabtchevich\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_Ellesmere_290610\demosaic_ppg.cl.bin'
0.609184 [opencl_load_program] successfully loaded program from `c:\Program Files\darktable\share\darktable\kernels\demosaic_ppg.cl'
0.619188 [opencl_build_program] could not build program: -11
0.624188 [opencl_build_program] BUILD STATUS: -2
0.628189 BUILD LOG:
0.630190 Error: The binary is incorrect or incomplete. Finalization to ISA couldn't be performed.

0.639194 [opencl_init] failed to compile program `demosaic_ppg.cl'!
0.645193 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.650194 [opencl_init] initial status of opencl enabled flag is OFF.

**Comment by XanomalieX** [comment]
3.0 RC2 solved this for me.

**Comment by BigSerpent** [comment]
I've just installed the 3.0 release ind it hasn't helped.

**Comment by fhug** [comment]
3.0 RC2 solved it for me too, and it still works with the new 3.0 release.

**Comment by BigSerpent** [comment]
So, what should I do? I still cannot use OpenCl.

**Comment by BigSerpent** [comment]
Just to prevent automatic close...

**Comment by johnny-bit** [comment]
@BigSerpent - your problem is different from the one from @ForresterAlex. Your log shows that your system has trouble building OpenCL kernels (apps ran on your GPU).

your exact error is CL_BUILD_PROGRAM_FAILURE (a bit generic :P) maybe try updating opencl drivers?

**Comment by BigSerpent** [comment]
So I've downloaded and updated radeon driver to the newest one (v 2020) and the problem became solved. But before that I had the previous version (2019), which had been updated up to date and OpenCL didn't work.

**Comment by johnny-bit** [comment]
@ForresterAlex - can you try updating drivers like @BigSerpent and report if anything helps?

**Comment by ForresterAlex** [comment]
Sorry, I reached a point where I was done with dealing with windows bullshit, this no longer applies to me.

**Comment by coffeeandspaceships** [comment]
I've just had a look around some OpenCL discussion on other forums and it is beyond doubt that the 2019 drivers for Navi were AWFUL.

As the 2020 drivers fixed it for @BigSerpent I suspect very strongly that Alex's problem was also the drivers, but as s/he cannot retest now as they've abandoned the Windows platform, I vote (if I have a vote...) that we close this issue.

**Comment by johnny-bit** [comment]
Closing as suggested. Let's hope opencl on windows will be fine...

**Comment by MCian42** [comment]
I found the solution on this post : https://www.photo.buet.us/post/darktable-can-t-activate-opencl
I works great for me, with OpenCL up and running :-)
Darktable 3.4.0, Windows 10 20H2, Intel Core i9 9900K, GPU UHD630 driver Intel version 27.20.100.9316 (Feb 18th, 2021)
