### ISSUE TITLE
[Color Zone] Select by lightness behavior question

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3080]
**Describe the bug**
Color zone select by lightness.
Select the color picker for range.
The histogram color looks alright.
![image](https://user-images.githubusercontent.com/1119439/66264828-f8facd00-e829-11e9-995f-7061e35c7e30.png)
Now move one of the points and the color changes to blue.

![image](https://user-images.githubusercontent.com/1119439/66264836-0c0d9d00-e82a-11e9-885a-d868f2320c8f.png)

The single color picker to the left of the range picker does not have this color change effect.

Am adding the IOP order just in case.
![image](https://user-images.githubusercontent.com/1119439/66264910-08c6e100-e82b-11e9-8194-526887d8f142.png)

I don't know enough about this modules behavior for different select criteria, I generally use select by hue and am familiar with it. 

Win 10.
DT 2.7.0.1945

**Comment by TurboGit** [comment]
I think this is expected. It is blue at the start BTW, this is a way to represent the lightness from dark-blue to white. The left picker does the same for me as soon as you release it. The right picker is to raise or lower the value with ctrl or shit when selecting the picker or just to display the zone in the histogram with a simple click. So to me all looks correct.

**Comment by chhil** [comment]
The left color picker behaves differently for me hence the confusion. Because its easier to see which color was picked and then moving points in the same color (not blue)  gives the user a good idea what color changes are expected.

![image](https://user-images.githubusercontent.com/1119439/66280053-8134ad00-e8d2-11e9-9a97-253bbee1c0b3.png)

**Comment by TurboGit** [comment]
A misunderstanding. The left picker can be used as a point (click) or area (ctrl-click). In both case when editing the curve the behavior is the same. The right picker is "transient" and can be used to create a curve (positive/negative) automatically for the selected area. So as soon as some edits happen it is deactivated. At least that was the idea for this behavior.

**Comment by chhil** [comment]
Thank you , understood.
