### ISSUE TITLE
GUI enhancement: keep scroll position per module group

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#3085]
**Is your feature request related to a problem? Please describe.**
When using the module group buttons in darkroom to switch between different groups, adjusting the scrolling for optimal display of a module interface will replace a previous such adjustment in another group, requiring constant re-adjustment when frequently switching between two modules in different groups.

**Describe the solution you'd like**
If the scroll position could be retained *per group*, the behavior would be more similar to "tabs", which these buttons more or less perform the role of. Using this method of switching between modules in different groups is IMHO less tedious and haphazard than doing large amounts of scrolling within a group, particularly on moderate-size displays.

**Describe alternatives you've considered**
I have tried different approaches involving the favorites group and the active modules group, but find myself increasingly favoring switching between groups when using the newer 2.7 GUI.

**Additional context**
Also adding the ability to bind keyboard shortcuts to the group button actions would enhance this enhancement. :-)

**Comment by junkyardsparkle** [comment]
Bump. This is still a valid feature request as far as I'm concerned.

**Comment by junkyardsparkle** [comment]
This is somewhat less relevant now with the expanded group configuration ability coming in 3.4; I'm leaving it open pending discussion in #5129 about module and group dynamics.

**Comment by Nilvus** [comment]
@junkyardsparkle: since #5129 issue you link this one to, had been fixed and closed, what about this one? I think actual master has better behavior now. Do you think this issue need something to be solved? If yes, could you precise it as you said in your last comment that was less relevant now (in october)? If no, maybe we could close this issue.
