### ISSUE TITLE
Finding untagged images

### ISSUE THREAD

**Issue by muenznej** [darktable-org/darktable#3088]
Hello, I tried to find all images on my database that where not tagged **by me**. Every image imported into darktable has a darktable|* tag. Therefore, it is not possible to find untagged images in big collections conveniently. 
 
I think a decent solution would be to have darktable tags be treated differently than all others, so that they can be easily excluded/ignored. 

kind regards
JB

P.S.: thx for all the effort with dt

**Comment by Egocentrix** [comment]
Agreed, filtering for untagged images does not work now. I work around it by auto-applying a tag on import called 'workflow|Needs tagging'. Now I can just filter by that tag, and remove it when I'm done tagging.

**Comment by muenznej** [comment]
Thx for pointing out this workaround! I personally still think it would be more consistent to be able to find untagged images via built-in options. Especially if you want to add tags to old images.

**Comment by Haribo-66** [comment]
I am using a LUA script called "select_untagged" here.
See https://github.com/darktable-org/lua-scripts/tree/master/contrib

**Comment by johnny-bit** [comment]
This is fixed in #7752 :)

**Comment by muenznej** [comment]
<3
