### ISSUE TITLE
Portrait pictures imported with LightRoom edits are displayed head-down

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3089]
**Describe the bug**
When I'm importing portrait pictures in darktable previously edited with LightRoom, I got the images head-down in darktable

**To Reproduce**
1. Edit a portrait picture in LightRoom so that a LightRoom xmp file is created and associated to the picture in the disk.
2. Switch to darktable and import this same picture
3. See the picture displayed head down.

**Expected behavior**
Portrait picture displayed head up
(and LightRoom edits translated into darktable edits)

**Platform (please complete the following information):**
 - OS: linux
 - Version: 2.7.0+1956~g552a1d6f7

**Additional context**
- Same operation with darktable 2.4 and 2.6 was working fine.
- Same portrait picture imported in darktable 2.7 without the LightRoom xmp is correctly displayed (but LightRoom edits lost)

**Comment by leclercj** [comment]
Sample of wrongly imported picture available here (too big for GitHub, so using We Transfer, link available 1 week only)
https://we.tl/t-noHrdVuZGV

**Comment by TurboGit** [comment]
Thanks for reporting. I suppose this is due to the fix on orientation put in dartable which has not been propagated to the lightroom import module. I'll have a look.

**Comment by leclercj** [comment]
Good progress with this https://github.com/darktable-org/darktable/pull/3100
It fixes my sample case, but not all cases.
I'll propose a complement PR after additional tests

**Comment by TurboGit** [comment]
I was sure that some other cases where not properly fixed. I have no mean to test, so yes please open new PR for the other issues with what is needed to reproduce. Thanks a lot!
