### ISSUE TITLE
Light table behaves erratically when applying color labels, ratings, or tags.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#3090]
**Describe the bug**
In the light table, when color labels, ratings, or tags are applied, the light table view jumps to the first selected image in the collection, even if the operation was applied only to the image under the mouse cursor.

Also, when ratings are applied using a keyboard shortcut, all images are deselected.

**To Reproduce**
1. Bring up a collection of images independent of color labels, ratings, or tags (e.g., collect by film roll).
1. Select a block of images.
1. Scroll far enough away that the _first_ of the selected images is no longer on screen.
1. Apply a color label, rating, or tag.
1. Note that the position of the light table view has changed.
1. Note that, if a rating was applied using a keyboard shortcut, there are no longer any images selected.

**Expected behavior**
The behavior of Darktable 2.6.2 and earlier: applying color labels, ratings, or tags should have no effect on the position of the light table view, and applying ratings via keyboard shortcuts should have no effect on the set of selected images.

**Platform (please complete the following information):**
 - OS: Fedora 30
 - Version: Git master (revision a6b9b90)

**Comment by sams96** [comment]
I fixed the ratings part, but when I try to replicate the first part of the issue, I just get bounced back to the start of the selection which seems intended to me.

**Comment by schwerdf** [comment]
Getting bounced back to the start of the selection when applying a tag is exactly the behavior I was seeing.

If this change is intentional, I am requesting that it be reversed:
* A significant amount of my interaction with Darktable is going through collections and applying tags and/or color labels to contiguous blocks of images, and it is very annoying when after each tag application I have to scroll _again_ past the block I have just tagged.
* When a tag/color label is applied only to the image under the mouse cursor, and the light table then jumps away to show an image to which _no_ change was applied, it is very counterintuitive and the change may not be easily reversed.

**Comment by sams96** [comment]
I guess it would be best to add a setting to toggle this behaviour, I'll see what I can do.

**Comment by schwerdf** [comment]
This issue should be re-opened, as per comments in #3293 it is still being actively worked on.

**Comment by chhil** [comment]
Ratings in darkroom misbehave too.
Here the cursor when moved on the first start highlights 1 to 3 stars.
![image](https://user-images.githubusercontent.com/1119439/68453490-aabb5e00-021b-11ea-882f-e1d7a06bdba7.png)

**Comment by AlicVB** [comment]
yes, it was an "automatic" close by github, but this issue is only partially fixed. For the second part, this is clearly a bug and certainly not intended. I'll try to find what append and fix it, except if @sams96 as already done it !

@chhil : not sure to understand, but if it's a problem related to mouse cursor not acting at the right position, it's a different issue imho...

**Comment by sams96** [comment]
@AlicVB I did fix it in 724b2a0, but I'd appreciate it if you'd give it a look to make sure I didn't break what you were trying to do when you made that change.

**Comment by chhil** [comment]
@AlicVB , I will open a new issue for it.

**Comment by AlicVB** [comment]
@sams96 : yes, that's a good catch, it was obviously wrong, and fix the first part of the issue (thanks for that !).
I speak here of the second part, when lighttable "jump" to show selection when applying rating/colorlabels from keyboard. Anyway, I'm on it. I've found the source of the problem, but now need to find a way to fix that without broken something else !

**Comment by AlicVB** [comment]
@schwerdf : I've just done a PR that should fix the second part here : #3334
