### ISSUE TITLE
snapshot comparison size mismatch in global/toggle side borders view mode

### ISSUE THREAD

**Issue by lromano** [darktable-org/darktable#3091]
Hello, 

I noticed an issue with snapshot when activating the global/toggle side borders feature. 
The size of the original versus snapshot steps are not the same.

Steps:
- Take a snapshot and activate the comparison slider
- Press tab to remove side panels and get the photo 'full screen'
- Try to use the comparison slider. One picture is magnified, the other is still in 
the previous viewing mode size (prior to press tab).

Expected behavior should be both images at the same size.

Can it be considered as a bug ? If it's related to the fact that it's just a snapshot, taken at the size it was displayed when clicking 'take snapshot', maybe is it better to disable comparison on this magnified / side panels free view ? Because in the current state, it's not really usable in this view mode.

Thanks!

**Comment by TurboGit** [comment]
> Can it be considered as a bug ?

No.

**Comment by lromano** [comment]
Ok thanks for your answer.

Anyways, this is my modest feedback from a user perspective :
The feature itself is very clever and useful.

It's perfectly usable when the side panels are visible, but when you activate this mode, the experiece becomes a bit clumsy and the feature looses a bit of its interest.

Comparing pictures this way, I believe sizes should match in any given scenarios.

**Comment by TurboGit** [comment]
Sure, and at some time the snapshot will be dynamic hopefully and all issues will be solved. But at this stage what is proposed has been designed this way. So not a bug.

**Comment by lromano** [comment]
I perfectly understand, thanks to you ;)

**Comment by c-h-r-i-s-t-i-a-n** [comment]
From a users perspective I definitely would call this a bug. Anway, if it's not a bug please take it on the **feature-request** list. :)
