### ISSUE TITLE
iop order doubt - contrast equalizer moving before colorin without request

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#3094]
I have an image with this history:

![image](https://user-images.githubusercontent.com/23012047/66400868-8aad3a80-e9e2-11e9-8e39-3fb9170a1a13.png)

The corresponding iop order is this one:

![image](https://user-images.githubusercontent.com/23012047/66400938-a7e20900-e9e2-11e9-91c7-c53308f1f0d9.png)

In history, if I select the step 8 - orientation, the iop order moves to:

![image](https://user-images.githubusercontent.com/23012047/66401081-d95ad480-e9e2-11e9-8c61-fc37acf02d7d.png)

It is a bit surprising. If I selected back the step 13 - filmic rgb in history contrast equalizer is back to the right position.
Working on that image I had noticed that contrast equalizer was before colorin which was giving weird result (I don't know how it got there...). I have moved it after colorin. 
It seems that in some way the history keeps memory of this position.

If copy (ctrl-c / ctrl-v on filmstrip) the history to another image, this behavior is also copied, which is really boring.

 - OS windows 10
 - dt 2.7

**Comment by phweyland** [comment]
> It seems that in some way the history keeps memory of this position.

memory is kept even if I compress the history stack. I would expect it goes away.

**Comment by chhil** [comment]
You are selecting favorites, does favorites need to maintain order? (I dont use favorites so dont have modules in there).
I use show active modules and that keeps the order.

**Comment by phweyland** [comment]
> does favorites need to maintain order?

I think so. If I change the order under favorites the same order (for active modules) is respected on active tab.

**Comment by chhil** [comment]
But favorites may not have all the modules, so no way to keep order , I think favorites order should be independent of iop order.

**Comment by phweyland** [comment]
> But favorites may not have all the modules, so no way to keep order , I think favorites order should be independent of iop order.

I understand all modules are not there. This mean that changing the order there doesn't control the order with the non visible ones.
So no, I don't agree. I expect to see the visible ones in the right order.

**Comment by phweyland** [comment]
I've rebuild with last merge (PR #3096) but the behavior described above is still alive.

I would like this issue to be reopened, at least to understand what should be expected.

**Comment by TurboGit** [comment]
Reopened.

**Comment by TurboGit** [comment]
Do you have this issue only with contrast equalizer?

**Comment by TurboGit** [comment]
The favorites section does not represent the iop-order at all. It is a bag with all your favorites modules and has nothing to do with the actual iop-order (the order of the module in the internal pixel pipe).

**Comment by TurboGit** [comment]
So what you are expecting I suppose is a stable order in the favourites. Right?

**Comment by TurboGit** [comment]
BTW, I cannot reproduce? Can you reproduce with a new edit or is that with an old edit?

**Comment by TurboGit** [comment]
Is that after applying a style?

**Comment by phweyland** [comment]
> Do you have this issue only with contrast equalizer?

Yes so far. But I haven't put "contrast equalizer" before colorin, just maybe by mistake. But this mistake happened 2 or 3 times without having been able to understand how and why...
In the presentation/tutorial made by @aurelienpierre I've noted he was surprised once or twice not to find his modules in the expected order.

> So what you are expecting I suppose is a stable order in the favourites. Right?

In fact it does currently. When I change the order in favorites, the behavior of the module is changed and I see the same move in active modules. 
Yes, I expect the modules to be displayed in the current pipe order. Now the order can be modified and it produces effects, it seems useful to have it as visible as possible.

But that isn't the reason of that PR.

My trouble comes from the interaction between the history and the module order I have set (and then I expect). In the above example, when I regress in the history of an image, the pipe order is updated as it was at that old step, potentially changing the order I've decided to have now. In itself it should be OK as long that doesn't not affect other images. I have checked the other images are not affected, but ....

the change of order in the history is transmitted by copy and it is not forgotten when I compress the history. That's this point which seems to be dangerous, because sooner or later, I'll see some order changes I cannot explain anymore ...

> Can you reproduce with a new edit or is that with an old edit?

New edit (today edit, I did not start a new edit since the last merge).

**Comment by phweyland** [comment]
> 
> Is that after applying a style?

no

> I cannot reproduce

It seems this transmitted by xmp.
Apply the xmp to an image.
In darkroom set your favorites as in the second snapshot above. 
You should have the first snapshot above as history for that image.
Select step 8 - orientation. You should have now in favorites the third snapshot.

[20190826_Ipoema_003.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/3704688/20190826_Ipoema_003.NEF.xmp.txt)

**Comment by junkyardsparkle** [comment]
> The favorites section does not represent the iop-order at all. It is a bag with all your favorites modules and has nothing to do with the actual iop-order (the order of the module in the internal pixel pipe).

AFAIK this isn't the case, the favorites group seems very much coupled to actual iop order. The situation you describe would probably please some people, though... I seem to remember at least once or twice somebody somewhere requesting the ability to re-arrange the modules within the interface for convenience.

**Comment by jenshannoschwalm** [comment]
> the change of order in the history is transmitted by copy and it is not forgotten when I compress the history.

I am not sure what exactly you mean by this. Currently if you re-arrange the order while developing there will likely be two iop_orders for different history items of the same module. By compressing you select the latest.

Isn't the order the modules are displayed by walking the module list in `static void _lib_modulegroups_update_iop_visibility(dt_lib_module_t *self)`.

So if the order is wrong it must be the module list?

**Comment by phweyland** [comment]
> Currently if you re-arrange the order while developing there will likely be two iop_orders for different history items of the same module.

Yes, that is what I see. 

> By compressing you select the latest.

That's what I expect, but it does not. Compressing history doesn't make it forget the first order.

That's the issue.

**Comment by parafin** [comment]
Changes to iop order are basically a part of the history. Otherwise you couldn't reproduce the previous processing steps. If you select some older history item and press compress history, then newer iop order will be lost. But compressing history doesn't get rid of older iop order changes in the history. So I don't understand what is the bug here. Please clearly explain what actions do you do, what results are you getting and what results do you expect instead.

**Comment by phweyland** [comment]
> Changes to iop order are basically a part of the history. Otherwise you couldn't reproduce the previous processing steps. 

Agreed. And I understand that I came back to a contrast equalizer step with its position in the pipe at this time (in case I had several steps of contrast equalizer. but this is not the case).

> Please clearly explain what actions do you do, what results are you getting and what results do you expect instead.

I have given an example above. For some reason, at the original step 8 contrast equalizer was before colorin. As this produces garbage I've moved it after colorin as I was adding new steps in the development.
When you select back the step 8, where contrast equalizer is not involved, what is the benefit to move it back before colorin in the pipe. That's just confusing.
And as there is only one step in the full development stack where contrast equalizer is present it is counter intuitive to keep memory in the history of several positions of that module. The only right position of contrast equalizer in a compressed history should be the last one (position it has at step 12 in the above example). The position it had before has no interest and should never appear again.

**Comment by phweyland** [comment]
BTW when I open dt and go to darkroom with the image above I've this trace. That may be linked to above issue.


```
$ /opt/darktable/bin/darktable.exe
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 262144
[imageio_load_module] `C:\msys64\opt\darktable\lib\darktable/plugins/imageio/storage\libpicasa.dll' is compiled for another version of dt (module 19 (opt) != dt 20 (opt)) !
[imageio_load_module] failed to open storage `picasa': (null)
warning: can't load darktable logo from SVG file `C:\msys64\opt\darktable\share\darktable\pixmaps\idbutton.svg'
Operation not supported
[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 56380 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 56380 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (20.000000) image 56380 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20.000000) is after clipping (17.000000) image 56380 (dt_dev_read_history_no_image end)
[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 56380 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 56380 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (20.000000) image 56380 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20.000000) is after clipping (17.000000) image 56380 (dt_dev_read_history_no_image end)
[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 56380 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 56380 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (20.000000) image 56380 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20.000000) is after clipping (17.000000) image 56380 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (20.000000) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule flip clipping module flip (20.000000) is after clipping (17.000000) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 0 (dt_dev_pop_history_i

```

**Comment by parafin** [comment]
You should discard the history stack from the lighttable and start from the scratch to get rid of these errors.

And I disagree that iop shouldn't move - you should be able to get back to original iop order when going back in the history, otherwise you're not really going back. So not a bug. It may make sense to set final iop order for all history items after doing history compression, but it's more of a feature request than a bug.

**Comment by jenshannoschwalm** [comment]
At this moment i think we are discussing at least these (might be related or not) problems.

1. what iop_order should a module have when we select an entry in history?
2. what iop_order for a module should be kept in history after compression?
3. has the activated module the correct iop_order reflecting the selected position in history?
4. is the presentation in the modules tab correct? Does "correct" mean? _"Display all modules in this tab in the order the currently selected history defines. (In this case it's expected that the order should change when selecting items in history"_
5. Does module re-ording in one of the tabs like favourites always lead to a safe & correct new iop_order? (The iop_order for watermarks looks really weired, related to this?)

**Comment by jenshannoschwalm** [comment]
>  It may make sense to set final iop order for all history items after doing history compression, but it's more of a feature request than a bug

Hmmh, not sure. To what iop_order should we set a module? Certainly not to "default"

**Comment by parafin** [comment]
> > It may make sense to set final iop order for all history items after doing history compression, but it's more of a feature request than a bug
> 
> Hmmh, not sure. To what iop_order should we set a module? Certainly not to "default"

To the iop order of the selected history item (so final one in the resulting history stack). Again, I'm not sure if it's useful.

**Comment by phweyland** [comment]
> And I disagree that iop shouldn't move - you should be able to get back to original iop order when going back in the history, otherwise you're not really going back.

Your statement is fine to me but I think you have not got the point:
Multiple positions in the pipe for a module which appears only once in the history does not make sense. The rest is OK.

This question leads to another one. What does happen, study and stupid case, if one changes the iop order every time a new module is added to an image ? How this image is developed ? What is the current logic ?

**Comment by phweyland** [comment]
> At this moment i think we are discussing at least these (might be related or not) problems.
> 
>     1. what iop_order should a module have when we select an entry in history?
> 
>     2. what iop_order for a module should be kept in history after compression?
> 
>     3. has the activated module the correct iop_order reflecting the selected position in history?
> 
>     4. is the presentation in the modules tab correct? Does "correct" mean? _"Display all modules in this tab in the order the currently selected history defines. (In this case it's expected that the order should change when selecting items in history"_
> 
>     5. Does _"You do a module iop_order drag&drop"_ in one of the tabs like favourites always lead to a safe & correct new iop_order? (The iop_order for watermarks looks really weired, related to this?)

Your questions are valid to me, meaning, they need an answer, at least what is (should be) the reality today. Even if I could disagree with some answers, knowing where we are is the only way to have constructive discussions.

**Comment by parafin** [comment]
> > And I disagree that iop shouldn't move - you should be able to get back to original iop order when going back in the history, otherwise you're not really going back.
> 
> Your statement is fine to me but I think you have not got the point:
> Multiple positions in the pipe for a module which appears only once in the history does not make sense. The rest is OK.

I does make sense. You have default iop order. You can move iop and enable it, this will create a history entry. Then you want to revert that change, so you go back to previous entry. iop has to move to default position to fully revert the change you just did, so even though there is only one history entry for it, its order still changes.

**Comment by phweyland** [comment]
> so you go back to previous entry. iop has to move to default position to fully revert the change you just did

This makes sense indeed. But that's not the previous order of the module in history, that's the default position. 
I may have made the confusion between both types of order. But nothing on the screen tells me what is what. I just see order changes.
Which one is the default order ? Which order is not the default one ?
What is in fact the default order ? When you make an order change, does that become the default order ? For that image ? For the others ?

**Comment by parafin** [comment]
If we simplify a bit (by assuming user starts with empty configuration and all images unprocessed), then there's only one default order - the one image gets the first time you open it in darkroom or when you discard history stack. By moving iop you change the order for this specific image, so order changes from default one to custom. Indeed there is no indication when iop isn't in its default location. It might be a good idea to add such flag and a way to reset its location to default one.

**Comment by junkyardsparkle** [comment]
> Indeed there is no indication when iop isn't in its default location. It might be a good idea to add such flag and a way to reset its location to default one.

I think this might be helpful to keep people from getting themselves into trouble when "playing around" with this new feature. For that matter, would it make sense to restrict which module group views actually allow the drag-and-drop? At least by default, maybe only in active module group (or no group)?

**Comment by jenshannoschwalm** [comment]
I am currently preparing a pr for improved debugging iop_order information. Hopefully makes it easier to understand whats going on and we all can faster agree on bug or no-bug :-)

**Comment by phweyland** [comment]
> Indeed there is no indication when iop isn't in its default location. It might be a good idea to add such flag and a way to reset its location to default one.

If we add an indicator for "not at default position" it could be worse to show also the sub-case "not at a good position" to inform the user the module may not work well at this position.

**Comment by jenshannoschwalm** [comment]
I think something like an "indicator" or a "reset button" in the modules tab is something for later. We also likely want things like hard or soft fences to restrict senseless iop reordering, also not for 3.0.

What we could do without effort is a hint in the history. We have the deprecated symbol, we could add "+" and "-" indicators for increased or decreased iop_order compared to default. @TurboGit What is your opinion?

**Comment by parafin** [comment]
I think history is a bad place for such indication, because it visually has no correlation to iop order - it will confuse users even further about how pipeline works.

**Comment by phweyland** [comment]
> I think history is a bad place for such indication, because it visually has no correlation to iop order - it will confuse users even further about how pipeline works.

Agreed. I was thinking to show this indicator on the right panel, at least in active module tab.
