### ISSUE TITLE
contrast equalizer looses mix setting when compress history stack

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#3095]
The mix setting in contrast equalizer is lost after a "compress history stack" whatever its position in the history stack.

It is also lost when I select a different step in history stack.

 - OS: windows 10
 - Version 2.7

**Comment by jenshannoschwalm** [comment]
For me it looses it's setting right after going back to lightroom and re-open.

**Comment by junkyardsparkle** [comment]
Yes, it's just a "utility widget"... this came up recently in #3044. I wonder if there's a way to make this more apparent in the GUI?

**Comment by jenshannoschwalm** [comment]
Aah, missed those issues.

**Comment by phweyland** [comment]
> Yes, it's just a "utility widget"... this came up recently in #3044. I wonder if there's a way to make this more apparent in the GUI?

Understood. Nothing is lost in fact. The slider is just misleading for who has not read thee doc. Yes, that would deserve an ad hoc GUI representation, something like another type of slider...

**Comment by TurboGit** [comment]
Agreed, this behavior has always been there and I must say that I find it quite confusing. This mix slider looks like something added to make the whole effect stronger or softer. I think it would be better to have this mix part of the params or even remove it as it is somewhat redundant with the fusion opacity.

I'm really more leaning on removing this slider.

**Comment by junkyardsparkle** [comment]
I was thinking something that behaved more like a sprung "jog wheel", which re-centers itself each time it's released... no idea if GTK3 offers anything like that, though. Of course, then the question would be what value to display at that point... it could have the same "sticky-while-focused" behavior that the control has now, I guess...

The name of the control (in English, at least - "mix") also doesn't really tell much about its special purpose. I'm not sure if there's a good, short label that would be better, but the tooltip, at least, could be something more like "adjust amplitude of all nodes at once", which is what it actually does.

> I'm really more leaning on removing this slider.

I think it's worth improving and retaining. It can increase the effect, which isn't easily done with normal blending. It's useful for having a single, moderate amplitude preset which can have its amplitude easily adjusted on a case-by-case basis.

**Comment by parafin** [comment]
Also blending is slower than just adjusting the iop params. And I don't think blending can replace mix slider in case of equalizer, so why not keep it here too.

**Comment by TurboGit** [comment]
Ok, why not keep it so maybe add it into the parameters as all other parameters as the current behavior is awkward compared to all other controls.

**Comment by parafin** [comment]
Agreed, mix should be in iop params.

**Comment by junkyardsparkle** [comment]
I'm almost asleep, and might be missing something, but... if the actual positions of the nodes are already stored as parameters, what meaning would storing the mix parameter have?

**Comment by parafin** [comment]
It will make UI more intuitive.

**Comment by hellbuster** [comment]
I think a good name could be "amplification"

**Comment by junkyardsparkle** [comment]
> It will make UI more intuitive.

I don't disagree, I was just wondering how the value would then be considered when saving the node values and displaying the graph... if the graph displays the muliplied ("amplified") values, making further adjustments after applying this gain factor could be weird. The graph could simply always display the un-amplified values (I would lean towards this) but I'm not sure if that would still be "more inuitive" or not... since the graph would no longer change with the slider.

**Comment by junkyardsparkle** [comment]
> I think a good name could be "amplification"

...or even simply "strength", if implemented as described above... a familiar term already in use for denoise modules.

**Comment by TurboGit** [comment]
I think the "mix" slider value must be stored and used dynamically to change the curve. Today move slider to 0 and then go to another image and back. Result... you've lost all the edit as all nodes are set to 0 and there is no way to get them back.

**Comment by TurboGit** [comment]
Yes strength is certainly fine and something already used.

**Comment by junkyardsparkle** [comment]
It might be really nice if there was a "shadow" graph showing the effects of this value being applied to the nodes. This would provide the visual feedback that the "mix" control has now, but have the benefit of leaving the active nodes at an optimal scale for being manipulated. :-)
