### ISSUE TITLE
macOS 10.15 (Catalina): Error opening directory '...': Operation not permitted

### ISSUE THREAD

**Issue by d4rkd3v1l** [darktable-org/darktable#3107]
**Describe the bug**
On macOS Catalina I'm not able to access my photos, and when I go to import, I get an "Operation not permitted" error message.

**To Reproduce**

**Expected behavior**
I expect to able to use my photos and import new photos like before Catalina ;-)

**Screenshots**
<img width="754" alt="Screenshot 2019-10-09 at 20 31 03" src="https://user-images.githubusercontent.com/13336238/66509905-3d10fa80-ead4-11e9-82e0-5634838baa32.png">

**Platform (please complete the following information):**
 - OS: macOS 10.15
 - Version 2.6.2

**Additional context**
Seems like Apple changed something here, but seems like other apps kind of do request file/folder access and then work just fine.

**Comment by mnogueir** [comment]
Same problem here.

**Comment by mnogueir** [comment]
Could it be App Sandbox?

https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html#//apple_ref/doc/uid/TP40011183-CH1-SW1

**Comment by parafin** [comment]
I won't be upgrading to 10.15 any time soon, because it removes support for 32 bit applications, so someone should help out here.
I haven't enabled App Sandbox explicitly anywhere and it would have been strange for defaults to change like that... Maybe it's something else.

**Comment by parafin** [comment]
Could you try the following:

1. go to System Preferences->Security&Privacy->Privacy->Full Disk Access
2. unlock settings (click on lock icon in the left bottom corner and enter password)
3. click on + button and select darktable application
4. restart darktable and try accessing files again

**Comment by mnogueir** [comment]
I tried, didn't work. In the Privacy->File (maybe not the correct name, I'm running a Portuguese version) the + button doesn't work :(. For what I've read, the application must "ask" permission to access external volumes? With "terminal" I got the dialog asking, and now it appears on the privacy->file menu...

Thanks for the help

**Comment by bobsomers** [comment]
I have the same issue, Full Disk Access does not solve the problem.

In my case it's because my photos are on a SMB share, which requires permission to access "network volumes" in Catalina. If I grant iTerm access to "network volumes" (it properly asks for them, I guess) then launching Darktable from the iTerm command line is a functional workaround.

```
cd /Applications/darktable.app/Contents/MacOS
./darktable
```

@d4rkd3v1l That should work for your problem as well temporarily (giving iTerm permission instead) until Darktable requests these permissions from macOS directly.

<img width="681" alt="Screen Shot 2019-10-09 at 8 05 55 PM" src="https://user-images.githubusercontent.com/101756/66536233-18675380-ead1-11e9-9199-bec6108aed6b.png">

**Comment by mnogueir** [comment]
The workaround works! Thanks a lot

**Comment by parafin** [comment]
OK, will have to investigate how to ask for permissions.

**Comment by parafin** [comment]
@bobsomers, so you've managed to add darktable to Full Disk Access?
@mnogueir, I think you went wrong somewhere. Probably you chose Files and Folders instead of Full Disk Access. Maybe switch system language for a test, dunno.

I'm not sure why these restrictions apply to darktable, since it's not using App Sandbox.

**Comment by mnogueir** [comment]
@parafin , I tried both. In Full Disk Access I was able to add Darktable, but the problem persisted (after restart, of course). In "Files and Folders" I have no option to add new apps.

**Comment by d4rkd3v1l** [comment]
> @parafin , I tried both. In Full Disk Access I was able to add Darktable, but the problem persisted (after restart, of course). In "Files and Folders" I have no option to add new apps.

Yes, I noticed this as well, seems like on can add stuff to full disk access, but not to "files and folders" >.<

**Comment by parafin** [comment]
Then I'm currently lost on what to do here. Google doesn't help.
Which ways did you try to start darktable (aside from mentioned iTerm workaround)? I can think of at least 4, please try them all:

1. from the Dock
2. from the Files app browsing to /Applications
3. from the Launchpad
4. from the Terminal (/Applications/darktable.app/Contents/MacOS/darktable)

**Comment by d4rkd3v1l** [comment]
5. Spotlight (or sth like Alfred)

But everything but iTerm should be pretty much the same, I guess?

**Comment by mnogueir** [comment]
1. NOK
2. NOK
3. NOK
4. OK (I previously gave permission for terminal to use external drives)
5. NOK
6. /Applications/darktable.app is a directory, not an executable. I'd say this one is = 4
7. Don't have it installed

**Comment by parafin** [comment]
6. "open " is part of the command.

Can you show which permissions Terminal has in Privacy settings on your Mac?

**Comment by mnogueir** [comment]
OK, got it.

6. NOK

<img width="741" alt="image" src="https://user-images.githubusercontent.com/4836557/66612966-b5062000-ebbb-11e9-8c65-d16070b5eb44.png">

In Portuguese; it's  "Removable Volumes" and "Desktop"

**Comment by d4rkd3v1l** [comment]
> I have no idea. It looks like sandbox gets inherited from the parent process (iTerm workaround points to that), so there might be some difference.

I'm basically 100% sure about this as well.

I just did some tests, and really the only thing that worked for me, was using iTerm/Terminal (doesn't matter I think) and run/execute darktable from there. Despite `open`ing it doesn't really run/execute it "via Terminal", but just opens it, like you would do by using Dock, Spotlight, or just double-clicking darktable with your mouse in `/Applications`.

What's also interesting is, that I didn't have "Desktop" permissions set for iTerm, which led to the Permission Alert coming up, as I tried to access my Desktop. While obviously it just worked fine for my external drive, as I already had the permission for "Removable Volumes" granted for iTerm before.

<img width="758" alt="Screenshot 2019-10-11 at 16 40 39" src="https://user-images.githubusercontent.com/13336238/66661415-3fe02c80-ec47-11e9-9eff-a8e4a997e7f0.png">

<img width="780" alt="Screenshot 2019-10-11 at 16 40 55" src="https://user-images.githubusercontent.com/13336238/66661432-466ea400-ec47-11e9-8526-e99dafe6e3a6.png">

Now the big question really is, how do we get darktable to "request" these permissions by it's own, or how does darktable has to access the file system to make macOS trigger them?!

**Comment by parafin** [comment]
Please try modifying /Applications/darktable.app/Contents/Info.plist by adding the following lines after <dict> line:
```
        <key>NSSystemAdministrationUsageDescription</key>
        <string>NSSystemAdministrationUsageDescription</string>
        <key>NSNetworkVolumesUsageDescription</key>
        <string>NSNetworkVolumesUsageDescription</string>
        <key>NSRemovableVolumesUsageDescription</key>
        <string>NSRemovableVolumesUsageDescription</string>
        <key>NSDownloadsFolderUsageDescription</key>
        <string>NSDownloadsFolderUsageDescription</string>
        <key>NSDocumentsFolderUsageDescription</key>
        <string>NSDocumentsFolderUsageDescription</string>
        <key>NSDesktopFolderUsageDescription</key>
        <string>NSDesktopFolderUsageDescription</string>
```
After that start darktable the normal way and tell me if anything changes and which messages appear if they do. I hope it will allow application to start after Info.plist modification...

**Comment by d4rkd3v1l** [comment]
Just tested it, adding those UsageDecription keys to Info.plist, unfortunately it still doesn't work, that means I still get the original "Operation not permitted" alert.

**Comment by parafin** [comment]
Please do the following:

1. open a Terminal and execute the following command:
```
log stream --predicate 'subsystem == "com.apple.TCC" || subsystem == "com.apple.sandbox.reporting"' --level info > log.txt
```
2. start darktable and open import file dialog to get the error, then exit from darktable
3. Press Ctrl-C in the Terminal
4. Attach resulting log.txt file here
5. Revert changes to Info.plist (better just re-install from DMG package)
6. Repeat steps 2-4

**Comment by d4rkd3v1l** [comment]
[log_usagedesc.txt](https://github.com/darktable-org/darktable/files/3719553/log_usagedesc.txt)
[log.txt](https://github.com/darktable-org/darktable/files/3719554/log.txt)

**Comment by parafin** [comment]
How did you start darktable when you produced these logs?

**Comment by d4rkd3v1l** [comment]
Spotlight

**Comment by parafin** [comment]
Hmm, did you re-install darktable from DMG? What does the following commands display:
```
codesign -vvvv /Applications/darktable.app/
spctl --verbose --assess --type execute -v /Applications/darktable.app/
```

**Comment by mnogueir** [comment]
I tried the Info.plist changes, same result (running from dock). 

codesign:

> --prepared:/Applications/darktable.app/Contents/MacOS/darktable-bin
--validated:/Applications/darktable.app/Contents/MacOS/darktable-bin
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-cltest
--validated:/Applications/darktable.app/Contents/MacOS/darktable-cltest
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-generate-cache-bin
--validated:/Applications/darktable.app/Contents/MacOS/darktable-generate-cache-bin
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-rs-identify
--validated:/Applications/darktable.app/Contents/MacOS/darktable-rs-identify
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-chart
--validated:/Applications/darktable.app/Contents/MacOS/darktable-chart
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-cli-bin
--validated:/Applications/darktable.app/Contents/MacOS/darktable-cli-bin
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-cli
--validated:/Applications/darktable.app/Contents/MacOS/darktable-cli
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-cltest-bin
--validated:/Applications/darktable.app/Contents/MacOS/darktable-cltest-bin
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-generate-cache
--validated:/Applications/darktable.app/Contents/MacOS/darktable-generate-cache
--prepared:/Applications/darktable.app/Contents/MacOS/darktable-chart-bin
--validated:/Applications/darktable.app/Contents/MacOS/darktable-chart-bin
/Applications/darktable.app/: valid on disk
/Applications/darktable.app/: satisfies its Designated Requirement

spctl:

> /Applications/darktable.app/: accepted
source=Notarized Developer ID
origin=Developer ID Application: XIMEA s.r.o. (85Q3K4KQRY)

**Comment by bobsomers** [comment]
It looks like people are running into the same issues with [emacs](https://emacs.stackexchange.com/questions/53026/how-to-restore-file-system-access-in-macos-catalina) and [gimp](https://gitlab.gnome.org/GNOME/gimp/issues/3710).

The gimp issue might be particularly interesting as I believe Darktable's UI also uses GTK?

**Comment by parafin** [comment]
What I'm seeing from the logs is that macOS 10.15 changed the logic for shell scripts as applications - on 10.14 granting permissions to /Applications/darktable.app worked, on 10.15 permissions are checked for /bin/sh instead for some reason. So probably granting Full Disk Access to /bin/sh will allow darktable to access at least some files, but it's a bad workaround since permissions won't be limited to just darktable (so it will open a security hole). Getting rid of a start script for darktable might help, but I don't want to re-implement everything from there in C...

**Comment by parafin** [comment]
Anyway, I will try to prepare something next week for you to test. Right now I'm unable to notarize packages.

**Comment by parafin** [comment]
Please try the following build: http://paraf.in/junk/darktable-2.6.2+28.dmg

**Comment by bobsomers** [comment]
I will try to test this build tonight! Thanks @parafin!

**Comment by bobsomers** [comment]
Great news! That build appears to completely fix the issue for me.

I tried opening some existing photos which live on a network drive and got the appropriate permissions request. After saying "ok" my photos loaded with no issues.
<img width="503" alt="Screen Shot 2019-10-17 at 8 04 55 PM" src="https://user-images.githubusercontent.com/101756/67063213-c3ec5580-f11a-11e9-9caa-30aec41c1a38.png">

Next I tried to import some new photos from a local protected directory to make sure this worked as well. I got the expected prompt and the photos imported perfectly after saying "ok".
<img width="494" alt="Screen Shot 2019-10-17 at 8 05 47 PM" src="https://user-images.githubusercontent.com/101756/67063260-ec744f80-f11a-11e9-8163-5279ca0239c4.png">

Lastly, I checked that Darktable shows up in the System Preferences > Security & Privacy > Privacy > Files and Folders list, and it does!
<img width="692" alt="Screen Shot 2019-10-17 at 8 09 49 PM" src="https://user-images.githubusercontent.com/101756/67063331-470dab80-f11b-11e9-9828-9ab8ce5c1e32.png">

This looks 100% fixed to me! Thanks so much for a quick turnaround @parafin!

**Comment by d4rkd3v1l** [comment]
I can also confirm, that it works now. Thanks a lot @parafin!

**Comment by mnogueir** [comment]
Confirmed! Thanks a lot :)

**Comment by parafin** [comment]
Fix will be released soon as 2.6.3.

**Comment by pombay** [comment]
Dear Parafin,

tried everything to get 2.6.3 working, but cannot get to the external hard drives or access the network with that version. Do you still have your workaround?

**Comment by pombay** [comment]
> Fix will be released soon as 2.6.3.

Dear Parafin,

tried everything to get 2.6.3 working, but cannot get to the external hard drives or access the network with that version. Do you still have your workaround?

**Comment by parafin** [comment]
works for everyone else

**Comment by akirahou** [comment]
> Please try the following build: http://paraf.in/junk/darktable-2.6.2+28.dmg

I got the same problem. May I get this file? It seems that it works but also has beed removed. Thanks a lot.

**Comment by parafin** [comment]
2.6.3 and 3.0 releases already include this fix.

**Comment by TsvetkovP** [comment]
Create new scripts with ```#!/bin/zsh``` + enter in the console ```chmod +x ./scripts/*``` and run scripts
