### ISSUE TITLE
using tags with watermarks simple text

### ISSUE THREAD

**Issue by Haribo-66** [darktable-org/darktable#3112]
**Is your feature request related to a problem? Please describe.**

I want to add tags to (watermarked?) photos for a later use during slide shows.
Adding tags first  -> reuse these tags via simple text as a new watermark -> then use these tags during a slide show.

**Describe the solution you'd like**

I want watermarks using tags and then do slide shows showing these tags or watermarks with these tags.

**Describe alternatives you've considered**

Simply allow turning on / off tags for slide shows would do it as well.

**Additional context**

I remember that this might be possible today, but I can not figure out how.

**Comment by TurboGit** [comment]
This is not really possible. Which tags? If you have 20 or more of them on a picture which one to display? All ?

That being said it is possible to use "title" metadata IIRC.

**Comment by Haribo-66** [comment]
as an idea which tags to display on top of a slide show photo:
- exif date
- gps location and or location name tag
- name tag of person / fauna or flora /what ever your slide show is talking about
- any progress indicator e.g. slide 5 of 300
in total up to 4 tags
- one for each corner or
- all in one line

title will not really work as most of the tags already exist 

the watermark definition could be a pre-selection and a style attached only for a slide show usage

**Comment by phweyland** [comment]
Working on tagging and export metadata I had a look at watermark.
But the variable calculation is not the same as for files (and therefore export metadata), so I have let it as it was.
I'll try to factorize the code and get tags and categories (like $(CATEGORY0$(creator)) ) available on watermark. It may require some additional configuration (for $(TAGS), private, synonyms, ...).

However I don't know how watermark could integrate with slideshow. Also, your requirements involve other topics like "on each corner" and "progress indicator" that are even not supported by watermark if I'm not mistaken.

**Comment by Haribo-66** [comment]
Here is an example

![Screen-2019-10-13_21-45-48](https://user-images.githubusercontent.com/53818783/66721763-26391380-ee06-11e9-8049-d5e31c0e2bd6.jpg)

Only the selected tags are missing, the file export sequence number can be used as a progress indicator.

I think a style can have this watermark and you can turn this style on or off. 

4 different watermarks will have 4 different text sizes, which doesn't look very nice.  So 4 corners with 4 watermarks will not be the way.

**Comment by phweyland** [comment]
> Only the selected tags are missing

Do you use the keyword $(IMAGE.TAGS) to get the tags ?

**Comment by Haribo-66** [comment]
> Do you use the keyword $(IMAGE.TAGS) to get the tags ?

I didn't know that, seems to work somehow.

- but different hierarchial tags are splitted and mixed up and 
- I see "all" tags and can not select the tags I want to use ...

**Comment by phweyland** [comment]
>     * I see "all" tags and can not select the tags I want to use ...

That's the purpose of categories in the new tagging system. I'll try to add these categories to watermark. Patience.

**Comment by Haribo-66** [comment]
one last comment about the wrong displayed hierarchy, assume this 2 tags

![Screen-2019-10-14_21-22-58](https://user-images.githubusercontent.com/53818783/66777843-619d1600-eeca-11e9-924b-5291f80dbcaa.jpg)

and this is the related wrong sorted watermark view

![Screen-2019-10-14_21-21-45](https://user-images.githubusercontent.com/53818783/66777886-78dc0380-eeca-11e9-8592-2372c552042f.jpg)

**Comment by phweyland** [comment]
Sorry, I don't see anything wrong here. Could you explain a bit more ?

**Comment by Haribo-66** [comment]
I expected 2 tags with the full path:

Tag A level 01|Tag A 02|Tag A 03|Tag A 04 followed by Tag B level 01|B 02|B 03|B 04

or maybe all 8 segments (2x tags with 4x segments each) ordered like the full path:

Tag A level 01, Tag A 02, Tag A 03, Tag A 04, Tag B level 01, B 02, B 03, B 04

but it was 

- B name tags before A name tags
B 02 before B 03 before B 04 before A Tags, followed by Tag A 01 and finally B level 01 

WHY?

**Comment by phweyland** [comment]
Simple tags (Xmp.dc.subject) decomposes hierarchical tags in pieces. That the way it works. You can get only the leave pieces using the configuration "omit hierarchy in simple tags list".

About the order, "B xx" is definitively before "Tag A xx".

**Comment by phweyland** [comment]
> I expected 2 tags with the full path

Xmp.lr.hierarchical subject does that, but is not available in watermark.

**Comment by Haribo-66** [comment]
questions:

- I am fine with all the pieces, but I would definitely prefer hierarchical subjects, do I have a choice?  
- About the alphabetical order of pieces: I can not see any use for that, why would I use this?
- All decomposed pieces as they are would look like hierarchical subjects right?
- Finally, where can I enter "omit hierarchy in simple tags list" to retrieve the leaves only?

**Comment by phweyland** [comment]
>     * I am fine with all the pieces, but I would definitely prefer hierarchical subjects, do I have a choice?

currently no

>     * Finally, where can I enter "omit hierarchy in simple tags list" to retrieve the leaves only?

dt preferences, core options, miscellaneous

**Comment by Haribo-66** [comment]
There seems to be an error in using "tags with watermarks simple text" depending on which way you are creating it

![capture_10172019_170637](https://user-images.githubusercontent.com/53818783/67022782-11a89400-f102-11e9-8017-34e3ecec163b.jpg)

1. via the Watermark module preset it is working fine (see the left photo)
2. via a separate style (only for the Watermark preset) it is not working (see the right photo)

Any suggestions?

**Comment by Haribo-66** [comment]
My last watermark problem was linked to an history stack problem, solved.

**Comment by Haribo-66** [comment]
Last question on watermarks using tags:

how can I usetags as watermarks using plain text AND some background colour like  the little resizing window? Then I can use a style and place my watemark using always the same colour?

**Comment by johnny-bit** [comment]
> how can I usetags as watermarks using plain text AND some background colour like the little resizing window? Then I can use a style and place my watemark using always the same colour?

You have to create your own watermark as explained by docs https://www.darktable.org/usermanual/en/module-reference/processing-modules/watermark/

For example you can copy `simple-text.svg` to your svg dir and then edit it using text editor (or inkscape) to create the effect you'd like to have. For svg text element reference check out http://tutorials.jenkov.com/svg/text-element.html

Closing since core issue is wontfix (watermarks just for slideshow) and fixed (using tags in watermarks), also fixed history stack problem. If you wish to request any new features (or watermarks) to watermark module, feel free to open a new issue :)
