### ISSUE TITLE
darktable-cli Segmentation fault

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#3114]
**Describe the bug**

Segmentation fault (core dumped)
when using darktable-cli from version dt 2.7.0+1972~g066980eb1

**Steps to reproduce**

> /opt/darktable/bin/darktable-cli Something.RAF Name.jpg

Backtrace written into 
[darktable_bt_T3RD9Z.txt](https://github.com/darktable-org/darktable/files/3712908/darktable_bt_T3RD9Z.txt)

**Platform:**
OS: Manjaro 18.1.0 KDE

**Additional context**
CPU 3rd generation Ryzen (3900X)
Motherboard Aorus Pro

Help, please...

/Claes in Lund, Sweden

**Comment by TurboGit** [comment]
Problems seems obvious with the trace. Will fix.

**Comment by ClaesGitHub** [comment]
Merci! But sorry: the bug is still there.
Here is a fresh dump, based on latest dt version:
[newDump.txt](https://github.com/darktable-org/darktable/files/3713924/newDump.txt)

**Comment by TurboGit** [comment]
That's another instance of the same bug. Will fix !

**Comment by TurboGit** [comment]
Second fix installed. Can you try again ? Thanks.

**Comment by TurboGit** [comment]
Good to hear! Thanks.
