### ISSUE TITLE
No EXIF in files exported from darkroom mode

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#3119]
**Describe the bug**
I export my photos to 16-bit TIFF from darkroom mode. In current GIT HEAD (fa2d1c204ab73a4c0d2d4600d66531c29cb8ed38), exported files are missing EXIF data. Surprisingly, it happens only if I export from darkroom view (via ^E). If I do it from lighttable view, exif shows up. As far as I could tell all file formats are affected.

Exif metadata doesn't show either with `exiftool` or `exiv2`.

**To Reproduce**
1. Enter darkroom mode
1. Export photo (e.g. to 16-bit TIFF) via ^E.
1. Check for EXIF.

**Platform (please complete the following information):**
 - OS: Gentoo Linux
 - exiv2-0.27.2

Attaching log from `-d all`:
[dt.log.gz](https://github.com/darktable-org/darktable/files/3714979/dt.log.gz)

**Comment by phrrk** [comment]
I have observed similar issue when exporting from lightable mode, when using a storage type I have written as a lua script.  This script uses phototeleport (a windows application) as an uploader to Flickr.  exiftool reports that none of the exif data stored in the .xmp file are incorporated into the exported file.  However image description and GPS tagging do seem to make it through to the exported file, but title and darktable processing history do not (I have checked export settings).  All exif data are included if I simply export to file on disk.

**Comment by phweyland** [comment]
ooops, I've not tested the export (crtl-e) from darkroom indeed. I'll look at this asap.

> when using a storage type I have written as a lua script
@phrrk, your case in not clear to me. I don't know well what can be done with lua for export. Could you explain a bit more how that works ? Maybe share the script ?

**Comment by TurboGit** [comment]
@phweyland : thanks!

**Comment by phweyland** [comment]
> @phweyland : thanks!

I may not have too much time the next 2 or 3 days. Do you have any hard deadline for that ?

**Comment by TurboGit** [comment]
No, I would say that before end of month is ok.

**Comment by phrrk** [comment]
@phweyland, I attach my lua script which is based on the gimp one.  Essentially all it does is export an image, or images, into a temporary storage location and then passes this image, or images, to the external application (phototeleporter) in this case.  Once the uploads are complete the exported files are deleted from the temporary storage.  I haven't checked but I would assume that the same issue applies with the gimp.lua script that comes with darktable as my script is heavily based on that one.

[phototeleport_upload.zip](https://github.com/darktable-org/darktable/files/3716534/phototeleport_upload.zip)

**Comment by phrrk** [comment]
I can confirm that the same issue occurs with the gimp.lua script distributed with darktable.  I guess that the problem lies somewhere in src/lua/luastorage.c

**Comment by phweyland** [comment]
@phrrk, thanks, that helps.

**Comment by phrrk** [comment]
@phweyland I can confirm that exif data is now exported by lua export script, thanks.

**Comment by phweyland** [comment]
> I can confirm that exif data is now exported by lua export script, thanks.

In fact, it should follow what you have (set) in export metadata settings as for the other storages. Exif data can be disabled there.

**Comment by phrrk** [comment]
@phweyland Yes indeed settings are followed correctly
