### ISSUE TITLE
Darktable won't start after building with BUILD_PRINT="OFF"

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#3120]
**Describe the bug**
Darktable doesn't start after building it with BUILD_PRINT set to OFF instead of the default ON.

**To Reproduce**
1. Build darktable using -DBUILD_PRINT="OFF"
2. Install darktable
3. start darktable (/opt/darktable/bin/darktable)

GDB Backtrace: 
[dt.backtrace.txt](https://github.com/darktable-org/darktable/files/3718127/dt.backtrace.txt)

Build+Install+Extra info logfile:
[dt.build.20191011.1601.log](https://github.com/darktable-org/darktable/files/3718157/dt.build.20191011.1601.log)

**Expected behavior**
darktable starts, PRINT entry is not accessible or present in the main screen under the OTHER pull-down menu.

**Platform:**
 - OS: Linux, Debian 10.1 (Buster)
 - darktable 2.7.0+1979~ga2feac3b8

see _Build+Install+Extra info logfile_ for extended info

**Additional context**
I don't know if previous version behave the same, this is the first time I try building without printer support.

**Comment by parafin** [comment]
Have you cleaned /opt/darktable before re-installing darktable? I suspect you did not, because you have libprint.so in the backtrace.

**Comment by jade-nl** [comment]
Didn't think I had to clean out /opt/darktable.......

I'll make that a standard action from now on.

Solved.

Thanks and sorry for wasting your time (lesson learned though....)
