### ISSUE TITLE
Copying history stack between photos from Fuji X-E2 results in double base curve module

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#3123]
**Describe the bug**
I had to process several RAW files from Fuji X-E2 and noticed a strange behaviour that was not present when working with RAWs from any of my own Canon cameras. Namely, while copying history stack between photos, the `base curve` module was duplicated. Both copies had the same default curve (I didn't touch it at any point in my workflow) resulting in too bright image. I had to manually delete one instance of this module and things returned to normal.

**To Reproduce**
1. Add two photos from Fuji X-E2 to Darktable
2. Do some changes to one of them.
3. Copy the changes to another photo (in darkroom mode with ^c and ^v)
4. Notice double base curve module.

**Expected behavior**
Only one copy of base module should be enabled.

**Platform (please complete the following information):**
 - OS: Gentoo Linux
 - Version fa2d1c204ab73a4c0d2d4600d66531c29cb8ed38

**Comment by jenshannoschwalm** [comment]
Did you auto-apply any style?

**Comment by tomaszg7** [comment]
I have auto-apply on demosaic (selecting Amaze), which should not work on Fuji X-trans cameras. I don't think I auto-apply any other style but I don't know how to check it globally. For sure nothing on base curve module.

**Comment by jenshannoschwalm** [comment]
There is only one X-E2 file on pixls. Could you share another?

**Comment by tomaszg7** [comment]
I would guess making a copy of that one photo should do the trick for the purpose of this bug, but here are two more: http://tomaszg.pl/fuji I'll keep them online for a few days.

**Comment by TurboGit** [comment]
Yes, I suppose it is also related to #3153 as I have also seen strange things and indeed some times double base curve!

**Comment by jenshannoschwalm** [comment]
Hi @tomaszg7 , i tested with latest master and for me it seems to be fixed. If you auto apply basecurve you will see two entries after copy&merge but (at least here) no strange effects. Can you confirm?

**Comment by TurboGit** [comment]
Fixed, closing.
