### ISSUE TITLE
Over/under exposed indicator shows the picture as completely blue (underexposed)

### ISSUE THREAD

**Issue by cigno5** [darktable-org/darktable#3130]
**Description**
When the over/under exposed indicator is enabled (by clicking icon or by pressing key `o`) the whole image is showed as underexposed, thus completely blue.

Disabling OpenCL (using `darktable --disable-opencl`) darktable shows correctly the over/under exposed areas

**Screenshots**
![Screenshot from 2019-10-12 16-05-08](https://user-images.githubusercontent.com/11832142/66702640-1f2cdb00-ed0a-11e9-9d9c-e02bfef108be.png)

**Platform**
 - OS: Ubuntu 18.04
 - Version: master commit 0ae2c5cc1

**Comment by TurboGit** [comment]
Yes, I've seen that already this happens only with OpenCL. Something to fix...

**Comment by flannelhead** [comment]
I noticed this too. This fixed it for me:
https://github.com/darktable-org/darktable/pull/3129

**Comment by TurboGit** [comment]
Yes, fixed for me too now.
