### ISSUE TITLE
culling moves to first line of collection if space is pressed on the first image of the culling view

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#3133]
**Describe the bug**
Running 2.7.0+1971~g4315ff6e6 culling loses track of the culled images when I press <space> on the first culled image. lighttable then jumps to the beginning of the collection and the culling view loses all previously culled images.

**To Reproduce**
1. Go to lighttable
2. switch to the culling mode
3. Select the first image in the culling view
4. Press <space>
5. You will see that your culling view loses all culled images and jumps to the beginning of the collection.

**Expected behavior**
Behave like pressing <SPACE> on any other image inside the culling view.

**Platform:**
 - OS: ubuntu linux
 - Version 2019.04

**Comment by AlicVB** [comment]
Confirmed, there's something really strange with space.
I will take care of that asap.

**Comment by codingdave** [comment]
Thank you @alicvb. Is there documentation on how to use the module? Is there a better way than sorting out images that aren't currently interesting by <space>? And why is there a limitation on zooming into the images set to 4 images? 

Very useful module for me. Thanks a lot.

Cheers,
Dave
