### ISSUE TITLE
Where is map view ?

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#3135]
**Describe the bug**
No map view on darktable master

**To Reproduce**
1. Go to 'right top menu'
2. See that there's only slideshow and print views, no more map view

Try also with key shortcut, nothing happen.

I've tested to launch darktable with a totally new config folder. Same thing : no more map view. So it's not related to my config.

**Expected behavior**
Having the map view back

**Screenshots**
![gnome-shell-screenshot-GQTH9Z](https://user-images.githubusercontent.com/45535283/66707351-59fd3600-ed3f-11e9-8e10-78de54cf17d0.png)

**Platform (please complete the following information):**
- OS: Ubuntu 19.10 beta
- last commit of 11 october (0ae2c5)

**Comment by TurboGit** [comment]
Probably a build done with a missing libcups. Nothing to be done on our side.

**Comment by Nilvus** [comment]
> Probably a build done with a missing libcups. Nothing to be done on our side.

No, libcups is installed. Anyway, thanks for your answer that makes me on the way. I've just forgot that I've made change on my system and just forgot to install optional dependencies listed on wiki redmine "building darktable 2.6" page. Installing them and rebuilding darktable solved that...
