### ISSUE TITLE
Colors missing from part of the image when using Crop and Rotate

### ISSUE THREAD

**Issue by hellbuster** [darktable-org/darktable#3136]
A part of the image is missing colors when using Crop and Rotate. I suspect than there is something wierd with the IOP orders

![20190714-europa-55](https://user-images.githubusercontent.com/650365/66708864-ef8fca00-ed2d-11e9-8f96-b910f44290f5.jpg)
![screen-2019-10-12-20-20-48](https://user-images.githubusercontent.com/650365/66708868-164e0080-ed2e-11e9-9841-26dbbbc50e5e.png)

**Comment by hellbuster** [comment]
I forgot to mention that this only happens on export, the preview is fine. I tried with and without OpenCL and the result is the same.

**Comment by hellbuster** [comment]
There are some weird interactions between **denoise profiled** and rotations in **crop and rotate**. If I disable the denoise modules, I don't get the problem. If I disable the first instance (the one with chroma denoise), I get the same band as before, but only with the lightness affected, it shows the correct colors).

**Comment by aurelienpierre** [comment]
Are you using parametric or mask blending with denoise profile ?

**Comment by hellbuster** [comment]
Yes, I am using parametric blending, since I use the chroma and luma presets.

**Comment by aurelienpierre** [comment]
Ok, so it might be that your mask manager (invisible) module comes after the orientation module, thus the module output and its mask don't have the same orientation.

**Comment by aurelienpierre** [comment]
Could you move the orientation module before denoise profile ?

**Comment by jenshannoschwalm** [comment]
> Ok, so it might be that your mask manager (invisible) module comes after the orientation module, thus the module output and its mask don't have the same orientation.

Is this really true? I have the impression the mask manager is visible and is added to history when you compress it.

**Comment by aurelienpierre** [comment]
The mask manager is in the history, but not in the modules list, so you can't move it.

**Comment by jenshannoschwalm** [comment]
Sure, you can't move it. But is it in history (still unvisible) and made visible after history compression. After compression it has a fixed position in history. BTW do you know you can now start dt with -d ioporder and will see information about history and modules iop_order on the console?

**Comment by aurelienpierre** [comment]
> BTW do you know you can now start dt with -d ioporder and will see information about history and modules iop_order on the console?

I didn't, but that's really cool.

**Comment by hellbuster** [comment]
@aurelienpierre I moved Orientation and Crop and Rotate before Denoising and that made the problem disappear. Now I returned them to the original position and it is still working. I suppose that forced the Mask Manager to be on the right position.

**Comment by TurboGit** [comment]
Because the OP said that the problem was solved?

**Comment by hellbuster** [comment]
Solved through a workaround. I think that there is still something fishy about iop order migration, but I didn't want to make more noise.
