### ISSUE TITLE
Guide increment

### ISSUE THREAD

**Issue by senpai49** [darktable-org/darktable#3139]
**Is your feature request related to a problem? Please describe.**
Would it be possible from the light table to embed custom layout guides?

**Describe the solution you'd like**
Guide increment> Path ...> Select a layout guide in PNG

**Describe alternatives you've considered**
Existing guides to incrust (Symmetry Dynamic Symmetry Camera Pack (204)).
http://www.dynamicsymmetryart.com/dynamic-symmetry-grids.html

**Additional context**
![grid 1](https://user-images.githubusercontent.com/45768233/66716225-a1c99f00-edcb-11e9-8843-f3e2c40dc10f.JPG)
![grid 2](https://user-images.githubusercontent.com/45768233/66716227-a1c99f00-edcb-11e9-9ed1-2a531c99471e.JPG)
![grid 3](https://user-images.githubusercontent.com/45768233/66716228-a1c99f00-edcb-11e9-80f0-718e9619d392.JPG)

**Comment by senpai49** [comment]
is it possible to add grids in the module crops?

**Comment by TurboGit** [comment]
Not for 3.0. The feature freeze is on since October 1st.

**Comment by hatsunearu** [comment]
not sure if still interested, but if you want custom ones, they need to be defined programmatically (so not as images). I can implement the funky one but I'm not sure if it's "mainstream" enough to be mainlined.

**Comment by dterrahe** [comment]
There is support for defining guides in lua, https://www.darktable.org/lua-api/index.html#darktable_guides, which would be the venue for non-mainstream additions.

There is an example in contrib (lua/contrib/passport_guide.lua).

If this satisfies your needs, please close the issue. Thanks!

**Comment by johnny-bit** [comment]
While the issue can be solved with lua (mostly), however in cases like "dynamic symmetry grids" it'd be beneficial for users to be able to use images. The "pack" (found on different site - https://www.the-art-of-composition.com/dynamic-symmetry-grids.html) contains 200+ images with different guides. Coding all those in lua would be rather loooooong task ;)

**Comment by dterrahe** [comment]
> contains 200+ images with different guides. Coding all those in lua would be rather loooooong task

Most of these seem to be duplicates in different colors, formats (jpg, png _and_ tif) or rotations. Some of the remaining 14 (?) might be variations with different parametrization. It would definitely be more efficient to distribute these in formulaic/lua form. And easier to select, possibly more efficient/faster and higher quality to scale and render than bitmaps.

Not saying that there is _no_ justification for supporting bitmapped guides, but not sure this pack is it.

If @hatsunearu is still willing to implement (some of) these (I haven't checked; they may already have) then I think it would be a nice addition to the lua library and a testament to its flexibility.

**Comment by AlicVB** [comment]
tbh, I don't like the idea of bitmap guides. I would prefer them to be coded directly (lua allow that iirc) : 
- That would avoid all problem of resampling
- That would satisfied the guides styles and color set by the user

In @senpai49 , I don't see anything really difficult to implement... I can help if needed ;)

**Comment by johnny-bit** [comment]
Thinking more about it and i agree with @dterrahe - the "sensible ones" can be coded in lua and then the best ones could be integrated into core if they need to be. This will cut the cruft of the bitmap guides.

The only sensible, non-coded, external guides I think i'd be for actually would be SVG guides, as those can have definded stroke color/style.

**Comment by johnny-bit** [comment]
I've created one on small "help" request from user on pixls.us forum https://discuss.pixls.us/t/add-custom-guides/26288/10?u=johnny-bit

So... Which guides would be "useful" to try and code in lua and which code in code? :)

**Comment by johnny-bit** [comment]
harmonic armature guide added in darktable-org/lua-scripts#359

contrary to harmonic armature, the dynamic symmetry guides are based on width/height ratio and are defined per individual ratio.
