### ISSUE TITLE
denoiseprofile opencl kernel doesn't seem to be loadable on AMD ROCm

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3144]
On the console I'm seeing:

```
16.521265 [opencl_denoiseprofile] couldn't enqueue kernel! -52, devid 0
16.521286 [opencl_pixelpipe] could not run module 'denoiseprofile' on gpu. falling back to cpu path
```

I there a way to get more useful output? This is already with `-d opencl`. I use AMD ROCm

**Comment by rawfiner** [comment]
Only with wavelets?
Unfortunately I can't reproduce... would you be able to add some printfs in the code to find which kernel cannot be enqueued?

**Comment by cryptomilk** [comment]
Just add the printf's you need and tell me where to find the patch :-)

**Comment by rawfiner** [comment]
Ok I'll do that. Thanks for your help :-)

**Comment by parafin** [comment]
Usually it's an indicator that there's not enough GPU memory. Try to increase opencl_memory_headroom setting value.

**Comment by cryptomilk** [comment]
I have 

```
opencl_memory_headroom=300
opencl_memory_requirement=1024
```

lets double it ...

**Comment by cryptomilk** [comment]
Doubling those two values didn't fix it.

**Comment by rawfiner** [comment]
I added the printfs in the branch rawfiner-test-opencl of my git (https://github.com/rawfiner/darktable)
Please test both in wavelets and non-local means modes :-)
Thanks !

**Comment by cryptomilk** [comment]
With wavelets I get:
```
kernel backtransform_v2 failed
14.006171 [opencl_denoiseprofile] couldn't enqueue kernel! -52, devid 0
14.006189 [opencl_pixelpipe] could not run module 'denoiseprofile' on gpu. falling back to cpu path
```
With non-local means I don't see these messages.

**Comment by rawfiner** [comment]
Thanks for testing. It seems I have to add more printf. I will do that probably tomorrow

**Comment by rawfiner** [comment]
I pushed another commit on the same branch. Please test again

**Comment by cryptomilk** [comment]
I don't get any additional output.

```
kernel backtransform_v2 failed
14.006171 [opencl_denoiseprofile] couldn't enqueue kernel! -52, devid 0
14.006189 [opencl_pixelpipe] could not run module 'denoiseprofile' on gpu. falling back to cpu path
```

As kernel backtransform_v2 failed I would say that one of the dt_opencl_set_kernel_arg() for backtransform_v2 is setting invalid or wrong values. Especially the return values of this function are not checked!

I've added debug here: https://github.com/cryptomilk/darktable/tree/master-test

```
/home/asn/workspace/projects/darktable/src/iop/denoiseprofile.c:2926
/home/asn/workspace/projects/darktable/src/common/opencl.c:1953
/home/asn/workspace/projects/darktable/src/common/opencl.c:1958
/home/asn/workspace/projects/darktable/src/common/opencl.c:1965
rc=-51
```

which tells me that

`dt_opencl_set_kernel_arg(devid, gd->kernel_denoiseprofile_backtransform_v2, 7, 4 * sizeof(float), (void *)&bias);`

fails!

**Comment by rawfiner** [comment]
Ok, that helps, thank you for testing again, and for the additionnal debugging you have done.
I will try to see what can go wrong

**Comment by rawfiner** [comment]
I think I found the (stupid) mistake I did, it should be sizeof(float) instead of 4*sizeof(float) on that line.
I will change that later today (I am away from my computer right now)
Thank you for all the great help!

**Comment by cryptomilk** [comment]
That seems to fix it.
