### ISSUE TITLE
Option menu items are missaligned in RTL language hebrew to a degree they can not be seen

### ISSUE THREAD

**Issue by sbraitbart** [darktable-org/darktable#3145]
**Describe the bug**
Some option menus like the "export selected" for example, show the option title at one side and the options on the other side.
In Hebrew mode only the title is always visible but the options are sometimes visible and sometimes partly visible, or not at all.
It seems the options are situated on the right of the proper  alignment line.  

**To Reproduce**
just open light table or dark room in Hebrew language and click on one of the option menus 
Some options menus behave better in a sense that the options can be seen, but when clicking on to make changes the option title migrate right and sticks to the option item.

**Expected behavior**
The option title should be on one side (preferably on the right side but not critical) and the option item on the other side

**Screenshots**
![Screenshot from 2019-10-13 21-57-56](https://user-images.githubusercontent.com/17427276/66720402-b4ac9580-ee04-11e9-91b2-1c94ac6eb4e8.png)

**Platform (please complete the following information):**
 - OS: Debian 10
 - Version 2.7.0+1968~g63a293f9a

**Comment by sbraitbart** [comment]
![Screenshot from 2019-10-13 22-07-15](https://user-images.githubusercontent.com/17427276/66720510-3c46d400-ee06-11e9-8b0d-e9362138e41a.png)
The above is an example of how, in the "global options" for example only the "profile" is visible and the others  like "intent" are not.

**Comment by junkyardsparkle** [comment]
Confirmed, but I have no clue why this would affect some list items and not others, unless some labels are in bounding boxes that are themselves not justified correctly. I wasn't even aware that a R>L language setting flipped the *entire* screen horizontally... now I'm dizzy. :-)

**Comment by sbraitbart** [comment]
It seems like it depends on the first letter. If the first letter is Hebrew it is justified to the right and than goes our of sight to the right. Its like the right boundry is not defined to within the menu width.
I will be happy to help in solving this, but I am not a programmer. I will supper in all I can
Thanks
Shlomi

On 23 באוקטובר 2019 03:18:46 GMT+03:00, junkyardsparkle <notifications@github.com> wrote:
>Confirmed, but I have no clue why this would affect some list items and
>not others, unless some labels are in bounding boxes that are
>themselves not justified correctly. I wasn't even aware that a R>L
>language setting flipped the *entire* screen horizontally... now I'm
>dizzy. :-)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/darktable-org/darktable/issues/3145#issuecomment-545209197

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
