### ISSUE TITLE
Levels module not applied at export

### ISSUE THREAD

**Issue by defdef1** [darktable-org/darktable#3148]
**Describe the bug**
When the levels module is set to "automatic", it is not applied at export when the perspective correction module is turned on at the same time (at least for me). It does work though, when it's set to "manual". It only affects the exported image, not the preview in dt.

**To Reproduce**
1. Open image in darkroom
2. Activate "levels" and set it to "automatic
3. Export the image
4. Activate "perspective correction" additionally
5. Export again and look at the difference
6. Optionally turn both modules off and export again, it should look the same as in step 5

**Expected behavior**
Should be obvious.

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version 2.6.2

**Additional context**
There's a bug on redmine that may be related: https://redmine.darktable.org/issues/11533
I'm working with .cr2, maybe this plays a role as well.

**Comment by defdef1** [comment]
I have to add, that the exported image after applying automatic levels still looks much darker than in the preview (when perspective correction is turned off), but at least I can see a difference.

**Comment by defdef1** [comment]
Apparently it seems to affect some photos, some not. I'll try to provide samples later.

**Comment by defdef1** [comment]
First sample: https://mega.nz/#F!0WJUmARB!uzaOG_tho3nPzbvhzxaAzw

This link expires after a few days, if you cannot access it, I'll generate a new one.

In this case, automatic levels doesn't work regardless of perspective correction. So only the levels module is turned on.

I'm trying to find a sample where turning on perspective correction makes a difference since the files, where the problem currently persists, contain people whose permission to upload their photos I don't have.

**Comment by defdef1** [comment]
There seems to be something wrong with the automatic-function of the levels module. On some photos it doesn't work in preview, sometimes it works when turning certain modules off (like exposure or perspective correction), sometimes it doesn't work on export. I'll attach the output of `darktable -d all` when turning levels on and off while nothing happens in preview. It would be nice if someone could have a look at this.

[log.txt](https://github.com/darktable-org/darktable/files/3731098/log.txt)

**Comment by defdef1** [comment]
In the meanwhile I found out, that setting the white-level of the levels module in automatic mode to 99,9% works as a workaround in most cases, in most of the remaining cases turning off perspective correction does the job.

**Comment by TurboGit** [comment]
Cannot reproduce with current dev version even with the test picture posted here.
