### ISSUE TITLE
darktable-2.7.0~git2008.df4fca34f-1665 produces corrupted images

### ISSUE THREAD

**Issue by martinky82** [darktable-org/darktable#3151]
**Describe the bug**
Today I updated my system (Fedora 30), having the darktable master OBS repo enabled. darktable was upgraded:

    Upgrade  darktable-2.7.0~git2008.df4fca34f-1665.1.x86_64      @graphics_darktable_master
    Upgraded darktable-2.7.0~git1852.ca53b88d8-1573.1.x86_64      @@System

After the upgrade, I can no longer use darktable as it produces trimmed, thus unusable files on export (below are two files exported to jpg from the same raw, using identical settings (including resize to 4000px on the longer side), 01 exported with git1852.ca53b88d8-1573, 02 exported with git2008.df4fca34f-1665:

-rw-rw-r--. 1 mkyral mkyral 17347428 Sep 27 12:58 DSC_2150_01.jpg
-rw-rw-r--. 1 mkyral mkyral  9169076 Oct 14 12:07 DSC_2150_02.jpg

The image is corrupted the same way if exported full-res and webp format.

**To Reproduce**
1. export image

**Expected behavior**
See above

**Screenshots**

![DSC_2150_02](https://user-images.githubusercontent.com/11974982/66745705-0e05da80-ee80-11e9-904e-fce49c904d2a.jpg)

**Platform (please complete the following information):**
 - OS: Fedora 30
 - Version 2.7.0~git2008.df4fca34f

**Additional context**

**Comment by TurboGit** [comment]
Looks like an issue with this specific build or a library on your system which is not correct. I cannot reproduce this on my side and I have exported more than 300 pictures in jpeg yesterday.

**Comment by martinky82** [comment]
I updgraded to Fedora 31 and periodically trying new builds (including 3.0.0rc0): the problem persists. I am trying the 'official' builds from: https://download.opensuse.org/repositories/home:/darix:/darktable:/master/Fedora_Rawhide/x86_64/

I even tried to rebuild the package myself to no avail.

Anyone else here using new darktable on Fedora?

**Comment by martinky82** [comment]
And - the trimming seems to be quite regular
 - landscape orientet photos are trimmed as can be seen in the attached image above
 - portrait oriented images are trimmed so they're all back (file size being just ~ 160KB)

**Comment by martinky82** [comment]
In the end it is either build specific or already fixed in master:

latest build from: https://download.opensuse.org/repositories/home:/darix:/darktable:/master/Fedora_Rawhide/x86_64/darktable-3.0.0rc0~git17.7f59e3721-1992.1.x86_64.rpm is affected (from yesterday)

latest build from: https://download.opensuse.org/repositories/home:/darix:/darktable:/master/Fedora_30/x86_64/darktable-3.0.0rc0~git25.acd466272-2000.1.x86_64.rpm is not

**Comment by TurboGit** [comment]
Yes this is fixed since yesterday. Looks at the recent closed issues.
