### ISSUE TITLE
Darktable (2.6.2) leads to system freezes

### ISSUE THREAD

**Issue by bmhorn** [darktable-org/darktable#3152]
**Describe the bug**
I am not a hundred percent sure but until the last update (2.6.2) I have reproducibly system freezes if I use Darktable. Sometimes I get an error message that the data.db and library.db ( ~/.config/darktable/) are locked and Darktable is not able to start. After removing the .lock-files I can start Darktable but with the already mentioned system freezes. I additionally found out that the saved styles are present in the file system ( ~/.config/darktable/styles) but not visible in Darktable. I am not sure if this related to this bug. If you need further information please let me know. 

**To Reproduce**
1. Open darktable
2. Go to darkroom

**Expected behavior**
No system freezes

**Platform**
 - OS: Arch Linux (Gnome Desktop)
 - Version: 2.6.2

**Comment by jenshannoschwalm** [comment]
This issue should be fixed in master (work on database locking) #3181

**Comment by TurboGit** [comment]
Yes, closing.

**Comment by bmhorn** [comment]
Thanks for fixing this so fast and sorry for replying so late. I just updated to Version 2.6.3 and after removing the old xmp-files, everythings seems to run as espected.
