### ISSUE TITLE
Only able to make new Google Photos Gallery

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#3158]
Is it possible to upload to existing gallery? (Or replace images in existing gallery?)

![Only_able_to_make_new_album_](https://user-images.githubusercontent.com/12004932/66806138-4c79c300-ef6e-11e9-8de4-b3293730fa89.png)

**Comment by TurboGit** [comment]
No! This is due to Google Photo API change. You can only add to existing gallery created with latest version of dt (read latest version of Google Photo API). Nothing we can do.

**Comment by alcomposer** [comment]
Thanks @TurboGit - Google seems like it's intending to hinder Google Photos a bit... :-( I wasn't aware of the API Change. :-1:
