### ISSUE TITLE
Selecting Culling kill DT

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3162]
**Describe the bug**
New dt built, ran it from the build folder and pointing to a clean db using the command line args. Imported folder with images that had raw/jpg and their  xmp files   from a day old build.
Changing to culling in lighttable  immediately  crashes DT.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/3729139/darktable-log.txt)

![image](https://user-images.githubusercontent.com/1119439/66830289-c744dd00-ef72-11e9-940b-6706e07d0aa7.png)

darktable 2.7.0+2015~g1a11ea71d  

The  crash log doesnt have any thing meaningful like a stacktrace..
[darktable_bt_XVOX9Z.txt](https://github.com/darktable-org/darktable/files/3729144/darktable_bt_XVOX9Z.txt)

I would also like to know why opencl support is not avail;able, it used to be available in 2.6.2.
![image](https://user-images.githubusercontent.com/1119439/66830807-fe67be00-ef73-11e9-9b98-d3fa99eaeafd.png)

The darktable log has opencl info in it.

0.503998 [opencl_init] opencl related configuration options:
0.503998 [opencl_init] 
0.503998 [opencl_init] opencl: 1
0.503998 [opencl_init] opencl_library: ''
0.503998 [opencl_init] opencl_memory_requirement: 768
0.504999 [opencl_init] opencl_memory_headroom: 300
0.504999 [opencl_init] opencl_device_priority: '*/!0,*/*/*'
0.504999 [opencl_init] opencl_mandatory_timeout: 200
0.505999 [opencl_init] opencl_size_roundup: 16
0.505999 [opencl_init] opencl_async_pixelpipe: 0
0.505999 [opencl_init] opencl_synch_cache: active module
0.506998 [opencl_init] opencl_number_event_handles: 25
0.506998 [opencl_init] opencl_micro_nap: 1000
0.506998 [opencl_init] opencl_use_pinned_memory: 0
0.506998 [opencl_init] opencl_use_cpu_devices: 0
0.507998 [opencl_init] opencl_avoid_atomics: 0
0.507998 [opencl_init] 
0.509001 [opencl_init] found opencl runtime library 'OpenCL.dll'
0.509001 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
0.770020 [opencl_init] found 2 platforms
0.770020 [opencl_init] found 4 devices
0.771020 [opencl_init] device 0 `Intel(R) HD Graphics 4600' supports image sizes of 16384 x 16384
0.771020 [opencl_init] device 0 `Intel(R) HD Graphics 4600' allows GPU memory allocations of up to 407MB
[opencl_init] device 0: Intel(R) HD Graphics 4600 
     GLOBAL_MEM_SIZE:          1630MB
     MAX_WORK_GROUP_SIZE:      512
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 512 512 512 ]
     DRIVER_VERSION:           20.19.15.4835
     DEVICE_VERSION:           OpenCL 1.2

**Comment by jenshannoschwalm** [comment]
Hi, could you please test again with these two scenarios:

1. Clear database, start importing and wait until all thumbnails are visible (maybe add some more seconds to be sure). Then start culling again or darkroom mode.
2. Do you observe the same culling mode problem after the crash and a restart?

**Comment by chhil** [comment]
> 1. Clear database, start importing and wait until all thumbnails are visible (maybe add some more seconds to be sure). Then start culling again or darkroom mode.

Didnt crash when I selected culling from the dropdown.

> 2\. Do you observe the same culling mode problem after the crash and a restart?

Now I can't get it to crash after getting it to load all 487 pics.
I can't  get it to crash on a clean db while in the process of loading.
For  some reason the once loaded successfully does not crash it any more. Could it be cache related?

**Comment by jenshannoschwalm** [comment]
I think this is fixed. Please concide to close issue :-)

**Comment by chhil** [comment]
Could not reproduce.
