### ISSUE TITLE
Culling mode history copying doesn't work

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3164]
**Describe the bug**
I have images that I have edited and put 3 starts on them. In Culling mode I select the filter of 3 stars. Then select an image and copy history, I make sure its copy and not copy all so that I know the history popped up is being selected.
Then I select 2 starred images , the ones I have not edited. Then select an image and paste history to see whats being pasted.
Then I open this image in darkroom and the history is not updated,  its the default history of a fresh image import.

OS win 10
DT : 2.7.0.2015

**Comment by jenshannoschwalm** [comment]
Has been fixed. Concider to close issue please.

**Comment by chhil** [comment]
Successfully tested fix on darktable-2.7.0+2054~gdd12b7089-win64
