### ISSUE TITLE
Low pass modules takes into account the vignette while masking using the preset.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3165]
**Describe the bug**

Lowpass comes before vignette in the iop and can be seen in the listed modules of the image.

But when I enable lowpass after a few steps post vignette, the lowpass preset of "local contrast mask" masks it based on the shape of the  vignette.

If I turn off vignette, the low pass preset seems to work as it should.

**Expected behavior**
The low pass should not take into account the vignette.

**Screenshots**
![image](https://user-images.githubusercontent.com/1119439/66857316-a6957b00-efa4-11e9-900b-2191d769eb42.png)

**Platform (please complete the following information):**
 - OS: Win 10.
 - Version 2.7.0.2015

**Comment by todd-prior** [comment]
Drag the vignette outside the output profile??

**Comment by chhil** [comment]
That shouldn't be the way to fix it and moving it doesn't fix it either.

**Comment by todd-prior** [comment]
That does seem weird...LP happens way before and vignette is designed to be inside the color profiles for the current order so that is weird....

**Comment by aurelienpierre** [comment]
What you see is the product of vignette being applied on top of the low pass filter. It doesn't mean the LP actually takes the vignette as an input. I'm not sure what you try to achieve here, but it seems ok to me.

(Also… LP in local contrast mask is exactly what the shadows and highlights module does).

**Comment by chhil** [comment]
The vignette being applied on top of LP, that makes sense to me.
