### ISSUE TITLE
[Tone Equalizer] showing line matching cursor in out of bound area 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3171]
**Describe the bug**
After setting up mask and then going to advanced tab, using the cursor to see where the point is located in the histogram, the line showing it is outside the bounded area.

![image](https://user-images.githubusercontent.com/1119439/66903503-42b09800-f020-11e9-99e8-420685b253d9.png)

Masking was setup like this
![image](https://user-images.githubusercontent.com/1119439/66903564-59ef8580-f020-11e9-95db-d8370c391d6c.png)

That line should never be outside the bounded area.
The font issue is in all likelihood related to styles, I am using the darktable with icons style.
Its worth noting that the x axis starts with 0 and to represent +0.4 it is probably drawing it correctly to the right of it.

**Platform (please complete the following information):**
 - OS: Win 10
 - Version 2.7.0.2015 release with debug info build.

**Comment by aurelienpierre** [comment]
Ah I didn't bound the cursor in graph. Easy to fix.

What funny thing did you do to your font BTW ?

**Comment by chhil** [comment]
I didn't do anything, using default darktable icons theme. There is a ticket that describes how the styles are misbehaving across os's and fonts available on the system.
