### ISSUE TITLE
darktable-cli crashes when opening folders

### ISSUE THREAD

**Issue by Ruderknecht** [darktable-org/darktable#3175]
Hi all,

i try to run a script, which should run darktable-cli on folders.

I try to run the following command:

darktable-cli /home/lutzifer/Bilder/NEF/tmp1 /home/lutzifer/Downloads/bench.SRW.xmp /home/lutzifer/Bilder/JPG3/$FILE_NAME.png --hq 1 --core --library :memory: -t 8 --conf opencl_device_priority='1/1/1/1'

Giving a single Image as input it will not crash.
The interesting thing is that this command without the "opencl_device_priority='1/1/1/1'" also crashes on a second linux system.

The two systems are:
Intel E5-2667v2
Opensuse 15.1
Darktable 2.6.2 (also a user repo 2.7.0-....)

Intel E5-2630v2
Ubuntu 18.04.3
Darktable 2.4.2 

Here are the backtrace files from darktable.
[darktable_bt_OpenSuse15.1.txt](https://github.com/darktable-org/darktable/files/3736315/darktable_bt_OpenSuse15.1.txt)
[dartable_bt_Ubuntu18.04.3.txt](https://github.com/darktable-org/darktable/files/3736316/dartable_bt_Ubuntu18.04.3.txt)

**Comment by Ruderknecht** [comment]
Similar behaviour was reported before 9 in:

#2008

**Comment by Ruderknecht** [comment]
All builds since 20 days including 3.0rc0 showing the same behavior.

Opening only a folder with darktable-cli like described in man-pages chrashes with linux.

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by Ruderknecht** [comment]
I can confirm that it is fixed.

Is it only fixed in 3.0 or also in 2.6.3? Thanks a lot!

**Comment by TurboGit** [comment]
Will be in final 3.0 only.
