### ISSUE TITLE
copy & paste from darkroom filmstrip locks

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#3177]
**Describe the bug**
copy & paste from darkroom filmstrip locks

**To Reproduce**
1. Go to darkroom

Probably related to recent fixes on copy/paste (#3153 ) where locks have been added.

**Comment by jenshannoschwalm** [comment]
Yes, i can reproduce and also it fixes this hang.

There is a remaining problem i am not yet sure what the exact reason is.

If you start some action that leads to auto-generation of a large number of thumbnails **and** you start developing an image it sometimes happens that dt either simply crashes or the history database is wrong, one time i could not re-open the image at all.

I could trigger this by

1. clearing history on many images
2. copy&paste on many images
3. removing thumbnails from cache before starting dt.

So i am sure there is a problem with database access interfering. After adding the (now removed) locks i did not observe this any more when doing 2. When trying to develop an image that is pending for thumbnail update it takes a short time (background job still owning the lock?) and then it's working fine & safe.

I will look deeper into this and hopefully come back with a proper locking suggestion. I have two questions related you might be able to answer without effort.

1. Do you have any idea **why** the removed locks result in a hanging system? When looking at the code this is not obvious for me.
2. Could you hint at the thumbnail refreshing code?

**Comment by TurboGit** [comment]
For 1, looking more deeply at the trace it seems that there is something wrong indeed.

```
- history.c:914 (dt_history_copy_and_paste_on_selection) we call dt_history_copy_and_paste_on_image for each imgid of selection
- history.c:790 (dt_history_copy_and_paste_on_image) we call dt_dev_reload_history_items if current image is edited but this routine is enclosed by a lock/unlock of db
- develop.c:1019 (dt_dev_reload_history_items) we call dt_dev_read_history which call dt_dev_read_history_ext (with param no_image = FALSE)
- develop.c:1506 (dt_dev_read_history_ext) we call _dev_auto_apply_presets.
- develop.c:1259 (_dev_auto_apply_presets) we lock again the database and hang there
```

**Comment by TurboGit** [comment]
So as you see the copy_paste_on_image does a lock at high level in the call stack so nothing wrong can happen when pasting.

We may want such a lock when clearing history of an image if it does not exists?

**Comment by TurboGit** [comment]
See #3181 which is probably a better fix for 1 & 2.

**Comment by TurboGit** [comment]
>     2\. Could you hint at the thumbnail refreshing code?

I suppose this is all in src/common/mipmap_cache.c
