### ISSUE TITLE
Unable to import images & folders

### ISSUE THREAD

**Issue by sgschwab** [darktable-org/darktable#3179]
**Describe the bug**
When I go to import a folder images do not populate and there are no errors. When I try to import an image it responds with "error loading file '_File path and name_'". 
Checked Windows Defender for issues but was unable to find any.  

**To Reproduce**
1. Go to 'lighttable'
2. Click on 'import'
3. Click on 'import'
4. Select image to import
5. Click on open

**Expected behavior**
Image selected should show on screen

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/42947203/67097500-3d6e5d00-f188-11e9-9894-11e6bb9dc5ea.jpg)

**Platform (please complete the following information):**
 - OS: Win 10 1903
 - Version 2.6.2 & 2.7 (Have tried on both versions with some

**Additional context**

**Comment by phrrk** [comment]
Does the user that is running darktable have write permissions in the directory where the image is located?  It looks a bit like the image is located in a folder owned by an adminstrator.

**Comment by sgschwab** [comment]
I am the admin. It’s the only user on the machine.

**Comment by johnny-bit** [comment]
@sgschwab - since your report we've had several reports where antivir interfered with darktable actions on windows, be it import or export of images.

Do you still have an issue on windows with say darktable 3.2.1 or current master?

If not - please close the issue.
If yes - let's investigate further :)

**Comment by Nilvus** [comment]
This issue has more than a year and no answer since last comment, near a month ago. I close it to clean issues. @sgschwab: regarding of @johnny-bit comment, feel free to reopen with more infos if needed (and if it's not the antivirus and if tested in 3.2.1 or 3.4.
