### ISSUE TITLE
Plustek OpticFilm 8200i - 'color matrix not found'

### ISSUE THREAD

**Issue by 01tot10** [darktable-org/darktable#3182]
I'm having issues properly rendering my scanned black&white films.
The scans are made with:
Plustek OpticFilm 8200i + VueScan as the software, saved to .DNG.

By default, when I open up the .DNG's in Darktable, they load up as pinkish hued black&white images, together with an error message:
‘Plustek Opticfilm 8200i’ color matrix not found!

I uploaded an example .DNG from the latest batch to raw.pixls.us.

All help much appreciated!

**Comment by 01tot10** [comment]
If you need me to provide more example .DNGs or details of the scanning process, I'm naturally willing to help!

**Comment by LebedevRI** [comment]
Seems to work in master.

**Comment by jenshannoschwalm** [comment]
Right. Monochrome should be fixed.

**Comment by 01tot10** [comment]
@LebedevRI @jenshannoschwalm 
Oh, that sounds promising!
I'm running 2.6.2 from chocolatey on Windows 10 Pro.
So I'd only have to wait for the next release, is that so?

**Comment by 01tot10** [comment]
Or is there something that I can do to manually alter 2.6.2. to add support for the scanner-files?
I looked into compiling from source on Windows and it looked rather involved to be honest.
If 2.6.3 is super far away still, and there's nothing I can do manually to alter 2.6.2 I guess I can look into the compiling option as well.

Thanks for any help again!

**Comment by jenshannoschwalm** [comment]
You could use the monochrome module :-)

**Comment by 01tot10** [comment]
> You could use the monochrome module :-)

OK, thank you! I didn't understand that's what 'Monochrome should be fixed." meant in the first place!

After enabling the monochrome module, I'm still getting the constant pop-ups telling me about the missing color profile. Is there something I can do with that side of the story?

Thanks for all the help!

**Comment by jenshannoschwalm** [comment]
You slightly misunderstood. The monochrome module has been around for long. The monochrome being fixed meant something different, the mono files are detected much earlier and are handled without any sort of color "transformation".

The messages can be ignored.

**Comment by 01tot10** [comment]
> You slightly misunderstood. The monochrome module has been around for long. The monochrome being fixed meant something different, the mono files are detected much earlier and are handled without any sort of color "transformation".
> 
> The messages can be ignored.

OK, thanks for clearing that out! That's good to know, I was wondering whether the missing color profile would still affect the monochrome processing, but apparently there's no need to worry.

Thank you very much for the replies and help! I'm been bothered with this issue for a while now, but didn't dare to write anywhere for help.

One last thing though - I think seeing this pop-up come up all the time with every photo I open is a little bit annoying in the long run, even if it can be effectively ignored. I'm just wondering could I somehow help providing a specific sort of a file from the OpticFilm 8200i to help add the support for this scanner? Or is that very cumbersome / not as simple as that?

**Comment by 01tot10** [comment]
> One last thing though - I think seeing this pop-up come up all the time with every photo I open is a little bit annoying in the long run, even if it can be effectively ignored. I'm just wondering could I somehow help providing a specific sort of a file from the OpticFilm 8200i to help add the support for this scanner? Or is that very cumbersome / not as simple as that?

Ah, to answer myself:
I just installed a newer build for Windows from the 2.7-branch that someone was kind enough to provide on https://pixls.us/ forums, and indeed on 2.7 the error message is gone.

I think the whole thing is cleared now.

Thanks a lot for the help again! Very happy!

**Comment by jenshannoschwalm** [comment]
Maybe close the issue ...
