### ISSUE TITLE
HDR merging should filter out ACTIVEAREA exif tag

### ISSUE THREAD

**Issue by oib** [darktable-org/darktable#3186]
darktable "create HDR" (from selected images)

**To Reproduce**
1. Go to lighttable and select an some Images 
2. Click on "create HDR"
3. HDR image is created but cant be vewed
4. on the command line 
```
[rawspeed] (IMG_20191018_200915.1-hdr.dng) void rawspeed::DngDecoder::handleMetadata(const rawspeed::TiffIFD*), line 441: Rectangle (0, 0, 2592, 1944) not inside image (0, 0, 2576, 1928).
allocation failed???
```

**Expected behavior**
be able to view the created HDR image

**Platform (please complete the following information):**
 - OS: Debian testing
 - Version 2.6.2-3

**Additional context**
https://github.com/darktable-org/rawspeed/issues/203

**Comment by jenshannoschwalm** [comment]
DNG files should have active area set. The question is, why is is set not correctly?

**Comment by LebedevRI** [comment]
> DNG files should have active area set.

They don't as per https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf, the default is whole image.

> The question is, why is is set not correctly?

Because the tag got blindly copied over from the original DNG's that were stacked.

**Comment by jenshannoschwalm** [comment]
Ooh. I looked into the code. A the image dimensions are not as they were for the original files the "cropping hints" in dng must be modified or removed. ACTIVEAREA plus probably also DefaultCropOrigin&size and DefaultUserCrop

I guess the "blindly copy" is in `dt_control_merge_hdr_job_run` --> `dt_imageio_write_dng` and the  exif data passed as an argument is wrong.

I have never used the hdr merge before (so please be patient if my comments are far off). If i use exiftool to get an impression what data are included i was **very** surprised. The exif blob seems to be quite "corrupted", wrong filenames, the white balance has changed while keeping the Calibration illuminant, the byte order, some vendor data seem to be moved? ... btw i could not find the ActiveArea tag in a merged hdr image.

From looking into the history this part of the code seems to be pretty old and you seem to have been involved some years ago. Could you comment and maybe give a hint or two to give me a better start to fix this? On first sight there seems to be wrong more than this single issue.

**Comment by LebedevRI** [comment]
> A the image dimensions are not as they were for the original files the "cropping hints" in dng must be modified or removed. ACTIVEAREA plus probably also DefaultCropOrigin&size and DefaultUserCrop

Likely most of dng tags, yeah (does it drop dng opcodes at least?)

> From looking into the history this part of the code seems to be pretty old and you seem to have been involved **some years ago**.

Important part highlighted. I gave up.

> Could you comment and maybe give a hint or two to give me a better start to fix this?

If it were up to me i'd just completely rip out that entire feature.
It never worked and always produced broken output.

**Comment by jenshannoschwalm** [comment]
@LebedevRI could you also look into the pr?
