### ISSUE TITLE
Fujifilm FinePix S7000 camera raw file support (RAF)

### ISSUE THREAD

**Issue by agittins** [darktable-org/darktable#3188]
Output from darktable after loading a RAF raw file from my Fuji S7000:

```
RawSpeed:Unable to find camera in database: 'FUJIFILM' 'FinePix S7000' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (dscf3391.raf) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 168: Camera 'FUJIFILM' 'FinePix S7000', mode '' not supported, and not allowed to guess. Sorry.
```
Initial import of RAF file appears to work (thumbnail image shows in lighttable), but opening into developer mode give ```failed to read camera white balance information from `dscf3391.raf`!```

After messing about a bit and finding the developer controls rather non-functional, returning to the lighttable the thumbnail will often revert to ye olde skull and crossbones.

These cameras had a sensor that was effectively rotated 45 degrees so the demosaic can be a bit different for them, but the preview came through ok so perhaps that's already implemented and it's just the model-specific recognition that needs tweaking.

I have just uploaded a raw file from the FujiFilm FinePix S7000 to https://raw.pixls.us/ which I release under the CC0 license.

ufraw and dcraw both seem to have worked well for this camera historically, if that's of any aid in adding support to darktable.

The camera I owned no longer works, but I have several years worth of raw files in various lighting conditions if that's at all helpful.

**Comment by agittins** [comment]
In case the uploads on RPU are subject to review, here's the same raw file on my google drive:
https://drive.google.com/open?id=1FXt7QYQNZkl1DUoDi4nnN_R9DAIhW6eB

**Comment by chhil** [comment]
On 2.7.0,2001
What the view looks like when import happens...


On import , view in lightable.
![image](https://user-images.githubusercontent.com/1119439/67171667-b7475600-f3d5-11e9-80fe-da316c5fd83f.png)

On double clicking to open in darktable
![image](https://user-images.githubusercontent.com/1119439/67171593-77806e80-f3d5-11e9-9259-4a45bbedca4e.png)

On further double clicking it becomes a skull.
![image](https://user-images.githubusercontent.com/1119439/67171701-d9d96f00-f3d5-11e9-96b5-4b2784cdd219.png)

Should the import happen on an unsupported camera and then turn into a skull later?

**Comment by agittins** [comment]
I have just applied the diff to my local cameras.xml (from dt 2.6.2) and it works perfectly. Thanks for an amazingly swift response!
