### ISSUE TITLE
webp support: exif/icc/xmp inromation is not saved on export to webp

### ISSUE THREAD

**Issue by dmitryash** [darktable-org/darktable#3191]
**Describe the bug**
It turned out that exif information is not saved to files in webp format during export. exif information is saved for jpg and jp2 but not for webp. At the same time cwebp command line utility is able to save EXIF/ICC profile to webp if I convert jpg to webp manually.

**To Reproduce**
1. Try to export one image to jpg and webp
2. Check that EXIF information is present for jpg file
3. Check that EXIF information isn't preserved for webp file

**Expected behavior**
It'll be nice if exif information is saved for webp file format during export.

**Platform (please complete the following information):**
 - OS: linux, opensuse 15.1

**Version information:**
this is darktable 2.6.2

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by dmitryash** [comment]
Looks like it was fixed here d18b81f2c0d42c68939632b5605d98b58537957a . Am I correct?

**Comment by TurboGit** [comment]
Sadly no, this throw an exception in fact:

`[exiv2] /home/...DSC_1922_03.webp: /home/...DSC_1922_03.webp: The file contains data of an unknown image type`

**Comment by TurboGit** [comment]
Ok, issue understood. The webp support in exiv2 has landed in v0.26 and I'm still using 0.25 on my Debian box. So all is fine to me on the dt side, this will be supported properly when the build will be done using v0.26.
