### ISSUE TITLE
tone equalizer cursor issue

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#3202]
Color picker activation deactivates the over image tone equalizer control (and vertical line of under cursor luminance). Deactivating color picker doesn't bring back the over image tone equalizer control.

I have noticed that sometimes the same problem appear without obvious reason.
Deactivating, reactivating tone equalizer usually doesn't bring back the over image tone equalizer control.
Applying a manual correction on one of the tone equalizer module slider (curve smoothing for example) brings back the over image tone equalizer control every time.

Normal:
![image](https://user-images.githubusercontent.com/23012047/67423006-c693f280-f5d3-11e9-8acd-633761113443.png)

Cursor missing (the mouse is at the same place as previously):
![image](https://user-images.githubusercontent.com/23012047/67423412-8aad5d00-f5d4-11e9-9fd7-8f74146fd2dc.png)

**Platform (please complete the following information):**
 - OS: windows 10
 - Version 2.7.0+2055~g36f87d176

**Comment by aurelienpierre** [comment]
Hmm this is a limitation of the modular approach in GTK. The cursor is enabled only if the module has the focus (from GTK), which means it can capture key strokes and various other events. This focus is given only after the module box has been interacted with, and is lost as soon as you collapse the module or another module captures the focus.

**Comment by phweyland** [comment]
> just click somewhere on the module to get the focus, or we need to give the focus to modules on mouse hover event.

Just clicking somewhere on the module is not enough (hoovering neither). To get the cursor back I have to make some change on a slider.

BTW. Just to test your suggestion, I even did not get the cursor opening the module. This doesn't happens every time but does happen.

The module reacts:
![image](https://user-images.githubusercontent.com/23012047/67584603-49d95380-f74e-11e9-89b9-2f08a35554c5.png)

but I have not the cursor.

**Comment by aurelienpierre** [comment]
> The module reacts:

If the equalizer view reacts on mouse hover, it doesn't count since it's a custom GTK widget, which doesn't give the focus to the module. You will need to click it to get focus.

But I could make it though (benefit of being a custom widget).

**Comment by phweyland** [comment]
>  You will need to click it to get focus.

But clicking is not enough.

**Comment by alcomposer** [comment]
I also find myself having a hard time knowing when tool focus will happen, sometimes it works, sometimes not.

Could there be a button to activate/deactivate the canvas interaction for each module? (Which has interaction)
