### ISSUE TITLE
Undoing history compression on dup image does not restore the image back.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3204]
**Describe the bug**
On duplicate image created from a processed image.
Compress history of duplicate just having default modules (I compressed on step 0)...
It takes a few upto 3- 5 ctrl+z's to undo the history compression.
First few ctrl+z dont do anything, one might see working... label on the image at times.

Once the history is undone i.e. from default history to history before compression, the visible image does not revert back to the one with current undone history.

The only way to get it back is to double click the highest number (latest) history entry to trigger  redraw/reprocess  the image.

All of this attempted on duplicate image.
This happens on the original image too, but not as consistent. 

This was attempted with 2.7.0.2071 . It includes the history compression fix at level 0 ( https://github.com/darktable-org/darktable/pull/3198#issue-331210764 ).

**Expected behavior**
ctrl-z should work immediately.
The image should get restored when history is restored.

**Platform (please complete the following information):**
 - OS: Win 10
 - Version 2.7.0.2071.]

**Comment by TurboGit** [comment]
@chhil : feel free to test the PR with the proposed fix. thanks.

**Comment by chhil** [comment]
@TurboGit Is it in the master branch?
I usually pull from master and build.
If its not, how do I get these changes built  to test?

**Comment by TurboGit** [comment]
@chhil : got to #3205 
On bottom of the page you have a line "command line instructions". Click on it.
Do "step 1" and build from there.

When you've done go back to master branch:
`$ git checkout master`

**Comment by chhil** [comment]
@TurboGit 
>On bottom of the page you have a line "command line instructions". Click on it.
>Do "step 1" and build from there.

I did not find the instructions, however I went to your github repo and cloned https://github.com/TurboGit/darktable/tree/po/fix-undo-redo

This is my shell script
`#!/bin/bash
cd ~
rm -R ./darktable/
#git clone git://github.com/darktable-org/darktable.git
git clone git://github.com/TurboGit/darktable.git

cd darktable

#git pull
#git checkout 580bf49
git submodule init
git submodule update
mkdir build

cd build
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./releaseDT ../.
cmake --build .
cmake --build . --target install
cmake --build . --target package`

I got a build darktable-1.1+15417~g2b293ad2b-win64.
Installed it.
Its missing the compress history at 0th position, worked around it by clicking another position in the defaults.
Did a ctrl+z , the undone history appeared immedaitely.
However the image did not get refreshed and had to double click the latest in history to get it back..

I think the problem may be that if I use step 5 to compress history. On ctrl+z the history get undone, but step 5 is still highlighted leading me to believe the image does not restore because of this. Now this could be working as designed. Then double clicking at the latest history position restores it.

Image showing history restored but highlight is still at position 5.
![image](https://user-images.githubusercontent.com/1119439/67552766-50090900-f729-11e9-9917-0b494e631df4.png)
(ignore the face obfuscation)
