### ISSUE TITLE
OSX: opencl support broken by color_conversion: constant float matrix[9]

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3212]
**Describe the bug**
compiling opencl kernels at system start terminates for color_conversion.cl 

```
/Applications/darktable.app/Contents/Resources/share/darktable/kernels/color_conversion.cl:114:63: error: parameter may not be qualified with an address space
inline float4 matrix_product(const float4 xyz, constant float matrix[9])
                                                              ^
/Applications/darktable.app/Contents/Resources/share/darktable/kernels/color_conversion.cl:124:132: error: parameter may not be qualified with an address space
inline float get_rgb_matrix_luminance(const float4 rgb, constant dt_colorspaces_iccprofile_info_cl_t *profile_info, constant float matrix[9], read_only image2d_t lut)
```
 
**To Reproduce**
1. call /Applications/darktable.app/Contents/MacOS/darktable-cltest

**Platform (please complete the following information):**
 - OS: OSX 10.14
 - Version darktable 2.7.0+2091~gbe6a92465-dirty

**Comment by TurboGit** [comment]
Any fix to propose? I'm not on OSX, not sure how to test this...

**Comment by parafin** [comment]
Obviously remove constant before float matrix. This error was introduced in #3189. global and constant keywords make sense in function arguments only for pointers type.

**Comment by parafin** [comment]
There's similar error in more places.

**Comment by parafin** [comment]
Maybe constant should be replaced with const, not removed, but there's probably not much difference.

**Comment by TurboGit** [comment]
Thanks, can you test #3225. Thanks.
