### ISSUE TITLE
Exported images rotated -90 degrees.

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#3213]
**Describe the bug**
Exporting an image in portrait orientation rotates the result -90 degrees. This does not affect any images in landscape orientation.

**To Reproduce**
1. Go to any image in portrait format (tall)
2. Click Export
3. Open image in GIMP
4. Gimp will prompt whether you want the keep the original image or honor the orientation metadata (which is incorrectly rotated -90 degrees)

**Expected behavior**
I expect export not to rotate the image.

**Platform (please complete the following information):**
 - OS:  archlinux
 - Version master (be6a924650418b0b23d57018ccd5ab8a04c4aede).

**Comment by TurboGit** [comment]
Thanks, I can confirm that. It is due to commit a88be9282b0069.

@jenshannoschwalm : can you have a look at this? thanks.

**Comment by TurboGit** [comment]
Fix should be there: #3214

**Comment by TurboGit** [comment]
@groutr : can you test this fix?

**Comment by groutr** [comment]
@TurboGit, your commit appears to resolve the issue. :+1:

**Comment by TurboGit** [comment]
Thanks! I'll merge now as I'm 99% sure this is a correct fix.
