### ISSUE TITLE
darktable-cli command to decode/encode xmp file

### ISSUE THREAD

**Issue by aster94** [darktable-org/darktable#3215]
**Problem**
From a darktable xmp file is quite hard to extract human readable data

**Describe the solution you'd like**
`darktable-cli` could provide a easy to use command like `darktable-cli --xmp-decode <file.xmp>` and output the decoded values

**Describe alternatives you've considered**
Right now there are a few solution but none of them is immediate and easy to use, for example: https://github.com/wmakeev/darkroom-xmp-tools/

**Additional context**
The needs for such a tool is old: https://darktable-devel.narkive.com/7wvyu2mP/combine-darktable-with-timelapse-scripts

**Comment by parafin** [comment]
I think it's outside of the scope of darktable project itself. XMP format is standard and there's introspection in iops (exported as introspection_init, get_p, get_introspection, get_introspection_linear functions). You most likely don't want just extracting the values, you will want to change them, and I don't think it should be implemented as some cli command. One should write separate C program implementing the logic for particular project (be that timelapse or whatever).

**Comment by aster94** [comment]
yep i need to change them and then rewrite xmp file. I may opt to write a lua script, can you point me out some resources on how to decode/encode xmp file with lua?

**Comment by AxelG-DE** [comment]
@aster94 may I point you to my article on [pixls.us here: about a related topic](https://discuss.pixls.us/t/timelapse-photography-and-darktable/14579)

Cheers
 Axel

**Comment by johnny-bit** [comment]
I *think* we can continue with #4250 on this... or should we reopen?

**Comment by AxelG-DE** [comment]
Seems original author quit. I'm fine keep on going thru #4250 even though I start losing hope there

**Comment by AxelG-DE** [comment]
Regarding my edit

After seeing the labeling, I gained some hope again for #4250 :-)
Let's see...
