### ISSUE TITLE
tone equalizer: New Instance gets lost

### ISSUE THREAD

**Issue by pass712** [darktable-org/darktable#3216]
**Describe the bug**
A new Instance of tone eqalizer doesn't persist.

**To Reproduce**
1. Go to tone equalizer
2. Click on 'multilple instance actions. A new instance appears. Erverything in this instance is working fine.
3. Leave editing by clicking on another picture in the film-strip or double clicking on the same picture in the film-strip => Second instance is lost / deleted.

**Expected behavior**
The secon instance should persist after leaving picture editing.

**Screenshots**
Works on every picture.

**Platform (please complete the following information):**
 - OS: Win10
 - Version 2.7.0+1945~gd8c468a27

**Additional context**
-

**Comment by TurboGit** [comment]
Known and fixed already since long time.
