### ISSUE TITLE
exporting to the imported directory

### ISSUE THREAD

**Issue by guillaumeportails** [darktable-org/darktable#3217]
After importing a directory of many JPEGs, I successfully geotagged them using GPX files, thanks.

But then it seems impossible, from darktable GUI at least (Windows8), to write back these tags to the original JPEG files.

**Comment by TurboGit** [comment]
Which version of dt ? I have extensively used that in all 2.6 versions.

**Comment by spaceChRiS** [comment]
I guess this is a misunderstanding. Darktable stores the metadata in its database and in xmp sidecar files. It never overwrites the original files, but adds such metadata to exported files.

**Comment by junkyardsparkle** [comment]
If you don't want to actually do any image editing/exporting, but only want to embed geotags in JPEG files from GPX data, you can use exiftool: https://owl.phy.queensu.ca/~phil/exiftool/geotag.html

**Comment by guillaumeportails** [comment]
> 
> 
> If you don't want to actually do any image editing/exporting, but only want to embed geotags in JPEG files from GPX data, you can use exiftool: https://owl.phy.queensu.ca/~phil/exiftool/geotag.html

Yes, thank you. I did that, back to command-line but fits perfectly (WSL inside Windows10 helps).
[I may also like to just modify my original JPEGs (changing light, cropping, etc)]
