### ISSUE TITLE
Drawn masks difficult to use after flipping and rotating an image

### ISSUE THREAD

**Issue by ChrisPfi** [darktable-org/darktable#3218]
**Describe the bug**
If an image is flipped and rotated in the Crop and Rotate module, drawn masks in other modules behave as if the mouse pointer is shifted compared to the location where you draw the mask. Masks become very difficult to place at the right location. This applies to all Drawn Masks tools: brush, circle, ellipse, path, gradient.

**To Reproduce**
1. Go to Crop and Rotate module
2. Apply a rotation (very slight rotation produces already the effect) and flip the image horizontally (haven't tried vertically)
3. Go to any other module allowing Drawn Masks and apply a mask (e.g. pencil)
4. Display mask (yellow button)
5. The mask is not where you placed it with the mouse, or the drawn line is not in sync with the actual mask (several types of errors are possible). When you try to adjust the points of let's say of a brush, the points flip to another location and are difficult to place correctly (see also screenshots, I tried to paint on the bill and the neck)

**Expected behavior**
Drawn masks should behave "normally", as without flip/rotate in the Crop and Rotate module.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/57043403/67623322-fc2f1a80-f823-11e9-96b2-82ec4879bc01.png)
![grafik](https://user-images.githubusercontent.com/57043403/67623334-254fab00-f824-11e9-896f-76ab92e18a7b.png)
![grafik](https://user-images.githubusercontent.com/57043403/67623395-fdad1280-f824-11e9-81ee-5f84bba4512b.png)

**Platform (please complete the following information):**
 - OS: Win10, Ubuntu Linux
 - Version 2.6.2 & 2.6.3

**Additional context**
The issue was discussed on the French dt forum and Pascal Obry participated at the discussion. The user IMM40 found out exactly how to reproduce this behavior

**Comment by TurboGit** [comment]
Thanks for reporting, I can reproduce too. Note that I don't have this issue when mirror is set to "both". Probably an issue with the transformation matrix in transform/backtransform.

**Comment by TurboGit** [comment]
I also reproduce with current master branch.

**Comment by TurboGit** [comment]
Could be fixed in #3219
