### ISSUE TITLE
Mix value of Equalizer module not maintained

### ISSUE THREAD

**Issue by demarestk** [darktable-org/darktable#3222]
When setting a value of the 'mix' slider in the Equalizer module, either by dragging the slider to left or right or manually entering a value and then clicking somewhere on the Equalizer curve, the value of the mix slider resets back to default value 1
![2019-10-27 08_30_30-darktable](https://user-images.githubusercontent.com/55547939/67631253-215b7180-f894-11e9-8a41-83184cb94194.png)
![2019-10-27 08_30_42-darktable](https://user-images.githubusercontent.com/55547939/67631255-21f40800-f894-11e9-9c5b-c0c7c95273aa.png)

**Comment by TurboGit** [comment]
https://github.com/darktable-org/darktable/issues/3095
