### ISSUE TITLE
darktable 2.6.3 | can not compare two snapshots

### ISSUE THREAD

**Issue by senpai49** [darktable-org/darktable#3224]
you can not compare two snapshots in darktable 2.6.3

**Comment by senpai49** [comment]
> you can not compare two snapshots in darktable 2.6.3 under windows 10

**Comment by TurboGit** [comment]
Just to be clear, you're speaking about one step in history and one snapshot, right? One cannot compare two snapshots.

**Comment by ChrisPfi** [comment]
Yes I confirm but also when you try to compare to another image (which was possible in version 2.6.2)

Example within history comparison. No separation line is visible between step 5 and 7 (difference is quite pronounced)

![Sanpshot](https://user-images.githubusercontent.com/57043403/67637356-2d6a2200-f8da-11e9-91bb-002dcdae26e0.jpg)

**Comment by TurboGit** [comment]
@peterbud : I kind of remember something was done to fix this in previous release? It affects only Windows. Any idea? Thanks.

**Comment by peterbud** [comment]
This has been fixed with this PR: https://github.com/darktable-org/darktable/pull/2897
But that has not been picked for release 2.6.3 as far as I see.

**Comment by TurboGit** [comment]
@peterbud : You're certainly correct this is indeed needed and I forgot to pick it for 2.6.3. But do you remember why this was working in 2.6.2 ?

**Comment by peterbud** [comment]
I believe `glib` has changed after releasing 2.6.2, and that resulted the `g_open()` to open files as default in text mode and not in binary mode.
