### ISSUE TITLE
White balance module returns to displaying "camera" in preset menu after changing values.

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#3228]
**Describe the bug**
Newly imported RAW file defaults to using embedded camera values for white balance, and displays "camera" in the (lower)  preset dropdown. After changing the white balance by adjusting controls or selecting "spot" from the dropdown, the menu will display nothing or "spot" to reflect the change. However, after leaving the darkroom view of that image, upon returning to it the menu now displays "camera" again, despite no longer being set to the default camera white balance.

**To Reproduce**
See above.

**Expected behavior**
The menu should indicate that the white balance has been changed from the camera supplied values.

**Platform (please complete the following information):**
2.7.0+2092 on Linux

**Additional context**
Using the name "preset" for that menu is confusing given that every module already has a preset menu in its header... I don't have a suggestion for a better name at the moment, though. ;-)

**Comment by junkyardsparkle** [comment]
This hasn't been fixed, AFAIK.

**Comment by johnny-bit** [comment]
ohh! I can tackle this in #4360 !

**Comment by jenshannoschwalm** [comment]
Has been fixed in master .
