### ISSUE TITLE
History stack UI `copy` & `paste` should be ...

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#3229]
Copy and Paste in History Stack UI should be:

**Copy...**
**Paste...**

This is because they both open up a dialogue to choose what to copy and paste.

**Comment by TurboGit** [comment]
Every details count! Thanks.

**Comment by alcomposer** [comment]
There are many other examples of this in the UI:

In `import`:

`image` & `folder` both open up dialogues.

History stack also has `load sidecar file`.  

Copy & Paste in history stack are important to distinguish quickly and in a universal manner.

**Comment by TurboGit** [comment]
Done also for those.

**Comment by alcomposer** [comment]
I still think there are more scattered around the UI. @aurelienpierre - having worked on the UI quite extensively what are your thoughts? I think it would make sense to have all button text that opens a dialogue to have ellipsis? (to be consistent)

**Comment by TurboGit** [comment]
Fact is that we are entering string freeze in 3 days :)

**Comment by alcomposer** [comment]
I found these additional dialogues:


Selected Images:
* `remove` Y/N dialogue
* `trash` Y/N dialogue
* `copy` file picker
* `move` file picker

History Stack:
* `discard history` Y/N dialogue

Styles:
* create multi-choice dialogue
* import: file-picker

Geotagging:
* apply GPX track file: file-picker

None of which have ellipsis to indicate dialogues.

If it is going to be ellipsis for dialogues it would have to be consistent.

**Comment by TurboGit** [comment]
I have done some more before seeing your message. Looks like I have missed some but we are getting closer.

We cannot handle the one with Y/N dialog as those dialog are optional (controlled by a preference).

**Comment by alcomposer** [comment]
**Re: Y/N dialog**
I think that is fine. The dialogues look like they are only there as a last resort to exit the command.

I also think ellipsis reduce the stress for a user- as `...` indicates they can press the button without direct consequences.

**Comment by TurboGit** [comment]
All done now I suppose.

**Comment by alcomposer** [comment]
Great fast work @TurboGit. I hope this will be ok with the team. I think it's very clear now what is going on.

**Comment by aurelienpierre** [comment]
> having worked on the UI quite extensively what are your thoughts? I think it would make sense to have all button text that opens a dialogue to have ellipsis? (to be consistent)

Sure, it's consistent.
