### ISSUE TITLE
Display `n of n` export dialogue

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#3230]
![export](https://user-images.githubusercontent.com/12004932/67659207-c026c180-f9ab-11e9-8783-111d013a39c1.png)
The bottom left export dialogue shows how many photos are to be exported, but not which photo the process is up to. It would be simpler to the end user to see how far in a number as well as a progress bar.

`Exporting n of n images to file on disk`

**Comment by TurboGit** [comment]
This dialog has very little space and the "n of n" is displayed for every image on screen.

**Comment by alcomposer** [comment]
The display on each image only pops up for a short time. It would only be one extra number.

Maybe take away the text 'image' to make it:

Exporting n of n to file on disk

I am guessing DT only exports images anyway?

**Comment by TurboGit** [comment]
Yes only images indeed. Let me think about this.

**Comment by chhil** [comment]
Logging this NFR was on my mind. If you export a large bunch of pics and
 walk away there is no way to see where you are at immediately. 

Just as multiple exports get stacked in the area where export is taking place
stacking the x of y progress would be great.

**Comment by TurboGit** [comment]
Ok, let's make this for 3.0.1. It is a NF and cannot be part of 3.0 at this stage.

**Comment by junkyardsparkle** [comment]
Displaying this in the window title would be a nice touch, too, so that it could be observed even if the darktable window is not in the foreground. :-)

**Comment by darkelectron** [comment]
Or maybe `n/n` instead of `n of n.`

**Comment by AxelG-DE** [comment]
please not in the window title, as I always run in F11 mode

**Comment by junkyardsparkle** [comment]
> please not in the window title, as I always run in F11 mode

I meant *also* the window title, not *only* the window title. :-)

**Comment by TurboGit** [comment]
Fixed.
