### ISSUE TITLE
Funny colorful rectangles if you enable denoise profiled at 100% zoom

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3234]
**Describe the bug**

If I zoom in at 100% into a picture and enable 'denoise profiled' then I get rectangles in pink, green and black.

master tree efde14b
OpenCL turned on
AMD ROCm OpenCL

Picture where I reproduced this: https://discuss.pixls.us/t/the-fog-and-the/14233

@rawfiner

**Comment by TurboGit** [comment]
Cannot reproduce with Nvidia OpenCL. Can you reproduce without OpenCL on your side?

**Comment by rawfiner** [comment]
Cannot reproduce with Intel Neo OpenCL
Same question as TurboGit: is it only with OpenCL, or also with CPU?
Could you post a screenshot?
Also, does the size of the rectangles change if you modify the module's parameters?

**Comment by aurelienpierre** [comment]
@cryptomilk what if you remove `-cl-fast-relaxed-math` in `src/common/opencl` line ?

**Comment by cryptomilk** [comment]
@aurelienpierre Removing `-cl-fast-relaxed-math` fixes it.

**Comment by cryptomilk** [comment]
`-cl-fast-relaxed-math` enables  `-cl-finite-math-only` and `-cl-unsafe-math-optimizations`. So I've tested those individually. The culprit is `-cl-unsafe-math-optimizations`. Setting  `-cl-finite-math-only` is fine!

**Comment by cryptomilk** [comment]
Should we use different flags based on the vendor_id or set `-cl-finite-math-only`.

**Comment by TurboGit** [comment]
My immediate fix (for 3.0.0rc0) will be to use -cl-finite-math-only and remove the "unsafe"option. Given the name I don't think we want it to be used anyway. But this will require deeper thinking.

**Comment by TurboGit** [comment]
@cryptomilk : and thanks for testing!

**Comment by aurelienpierre** [comment]
>  Given the name I don't think we want it to be used anyway

`-cl-unsafe-math-optimizations` disables floating point arithmetic checks like NaN or infinity, disables signed zeros and enables multiply-add rounding. It's good for performance assuming these checks are done manually in the code (and most of them are).

**Comment by TurboGit** [comment]
Most of them, but not all so until this is fixed we can't use this option. But there could be more than that as the issue does not happen in Nvidia OpenCL.

**Comment by aurelienpierre** [comment]
As usual… OpenCL is "portable" until you test it on different platforms.
