### ISSUE TITLE
Applying a style twice does not create new instances of module in the style.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3235]
**Describe the bug**
I have imported a denoise [style](https://dtstyle.net/download.php/391/Denoise%20-%20profiled.dtstyle) from dtstyle website .

Apply the style once and as expected appears in the used modules list with 3 instances of denoise profiled. 
If I apply the style again, I expect 3 more denoise modules to get added but that's not the case and only the 3 modules from the time the style was applied is visible.
History shows a total of 6 denoise profiled but the numbering is the same. If I compress history then the dups are removed correctly but that means my style is only being applied once.
The image shows the pipeline and the history after applying the style twice.
![image](https://user-images.githubusercontent.com/1119439/67743893-09c3ea80-fa46-11e9-875a-b3936c1251da.png)

Another issue is if I have a denoise profiled in my pipeline already and I use the denoise style the pipeline one's get overwritten.

**Expected behavior**
The second time a style is applied I expect the new instances to be created for modules within the style.
There are modules that can have multiple instances and then there are those that cannot, care should be taken when instantiating new modules through styles.

**Platform:**
 - OS: Win 10
 - Version darktable-2.7.0+2113~gefde14b3d-win64

**Comment by TurboGit** [comment]
No, the current behavior is the one implemented and expected. Another semantic would be quite unexpected to me. Two times the same style on the image would have probably a broken result anyway. At least this is not a bug.
