### ISSUE TITLE
Darktable crash on trackpad pinch (OSX 10.9.5)

### ISSUE THREAD

**Issue by mr-a500** [darktable-org/darktable#3236]
**Describe the bug**
A trackpad pinch will consistently crash Darktable, no matter which screen or item is in focus. Two finger up/down on trackpad zooms correctly.

**To Reproduce**
Open Darktable (on OSX 10.9.5), do trackpad pinch. Crash will occur.

**Expected behavior**
Should not crash.

**Screenshots**

**Platform (please complete the following information):**
OSX 10.9.5

**Additional context**
I think the way pinch is handled in OSX changed in 10.10.

**Comment by parafin** [comment]
Can't reproduce on macOS 10.14.6 with darktable 2.6.3.1. What action do you have set for pinching in System Preferences? Zoom in and out?

**Comment by mr-a500** [comment]
OK thanks. I guess I'll just have to avoid pinching.

(Yes, pinching is set for zoom in and out.)
