### ISSUE TITLE
darktable 2.7 produces corrupted file

### ISSUE THREAD

**Issue by blitzgneisserin** [darktable-org/darktable#3239]
**Describe the bug**
darktable 2.7+2071-gcd3cf4669 produces a file with a strange margin on the right edge when exporting to original size

**To Reproduce**
open any raw file, copy the attached history stack/xmp file to it and export the file in ORIGINAL SIZE

**Expected behavior**
exported file has a strange margin at the right edge
![Screenshot at 2019-10-30 12-15-18](https://user-images.githubusercontent.com/16564210/67866390-28e77880-fb29-11e9-87ab-cb4612bf4de9.png)
![Screenshot at 2019-10-30 14-22-44](https://user-images.githubusercontent.com/16564210/67866405-2e44c300-fb29-11e9-8bb0-7456351ebe4f.png)

**Platform (please complete the following information):**
 - OS: MX Linux
 - Version 19

**Additional context**
[P2090860.ORF.xmp.tar.gz](https://github.com/darktable-org/darktable/files/3789385/P2090860.ORF.xmp.tar.gz)

**Comment by chhil** [comment]
Does the import not fix the broken iop order currently?

The xmp has a   darktable:iop_order_version="5"> which is current. Would changing that to a previous version enable the reordering?

**Comment by TurboGit** [comment]
> Does the import not fix the broken iop order currently?

No, not for the pictures edited for a short period of time (around Sep IIRC) where the broken iop-order was producing mess.

**Comment by blitzgneisserin** [comment]
actually it is true, I think I edited the photo some months ago with dt 2.6

**Comment by blitzgneisserin** [comment]
@TurboGit I redid the edit from a clean image. I exported after almost every step. Apparently the margin comes when I use the equalizer or denoise. Anyway, I do not get a correct image if I redo the edit from clean.
