### ISSUE TITLE
History compression and all modules list display are not kept in synch.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3245]
Sample image after sample edits. Note history and all modules listed tab
![image](https://user-images.githubusercontent.com/1119439/67918217-5f70d200-fbc1-11e9-8a81-5f3437e4494c.png)

Compressed history to original.
See history which is fine, but modules show multiple denoise , had to scroll modules up to see this.
![image](https://user-images.githubusercontent.com/1119439/67918283-b4144d00-fbc1-11e9-827d-d6dbb2785a1c.png)

This is a refresh issue, if I enable show only used modules and disable it again by clicking it the contents get corrected. The following image is after enable disable of modules tab.

![image](https://user-images.githubusercontent.com/1119439/67918341-ec1b9000-fbc1-11e9-9124-6eb4c71a464d.png)

**Comment by aurelienpierre** [comment]
Looks to me that some `gtk_widget_queue_draw()` should be inserted in the history compression sequence.

**Comment by TurboGit** [comment]
Cannot reproduce this! As soon as I select [original] in the history the multiple instance of modules are removed! I tested that with denoise and exposure.

**Comment by TurboGit** [comment]
Ok, reproduced, not sure how... But interleaving many modules I was able to get multiple enoise modules.

**Comment by TurboGit** [comment]
There must be some very special steps as I cannot reproduce now :(

**Comment by chhil** [comment]
I have used the denoise style multiple times referenced in https://github.com/darktable-org/darktable/issues/3235

**Comment by chhil** [comment]
This is fixed in 3.0rc1+7, cant reproduce this anymore.
