### ISSUE TITLE
Darktable 2.7.0 produces corrupted files - Again

### ISSUE THREAD

**Issue by ArJo45** [darktable-org/darktable#3247]
**Describe the bug**
With OpenCl activated and upon activation of some modules, e. g.  Local Contrast (Local Laplacian Filter mode), Contrast Equalizer and Lens Correction identified so far, grey or black square patches appear randomly within the image in Darkroom, or the image goes completely grey witout details. Upon return to Lighttable the thumbnail may be unaffected or turn completely black. My latest version working flawlessly was 2.7.0-2071. The latest version I tried was 2.7.0-2128.

**To Reproduce**
1. Open a raw file, CR2 in my case. Base curve turned off
2. Adjust Exposure, White Balance and activate Filmic
3. Activate one or a combination of Local Contrast (local laplacian filter, bilateral mode seems to be unaffected), Contrast Equalizer and/or Lenscorrection. OpenCl activated. With OpenCl deactivated everything works flawlessly.
4. The images is filled with black or grey square patches, or goes completely grey

**Expected behavior**
A clean image without the disturbing elements.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Linux Mint 19.2, 64-bit version, GPU Nvidia GTX 1050
 - Version 2.7.0 2071 latest working version, 2128 latest version tried.

**Additional context**
A healthy and corrupted example xmp file
[Reference files.tar.gz](https://github.com/darktable-org/darktable/files/3794732/Reference.files.tar.gz)
 attached.

**Comment by TurboGit** [comment]
If you redo the step from a clean image (after deleting all history) you should have no issue.
