### ISSUE TITLE
iop order corrupted on import

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#3248]
**Describe the bug**
I imported a large number of files (2873).  In the first 400 images I've had 4 images that gave this type of output in the console:

[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 11803 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module flip (0)(16.000000) and rawprepare (0)(16.000000) have the same order image 11803 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(16.000000) and flip (0)(16.000000) have the same order image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (16.000000) image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (16.000000) is after invert (2.000000) image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorout gamma module gamma (16.000000) is before colorout (69.000000) image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorout gamma module colorout (69.000000) is after gamma (16.000000) image 11803 (dt_dev_read_history_no_image end)
[dt_ioppr_transform_image_colorspace] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module gamma must be between input color profile and output color profile
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 11803 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module flip (0)(16.000000) and rawprepare (0)(16.000000) have the same order image 11803 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(16.000000) and flip (0)(16.000000) have the same order image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (16.000000) image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (16.000000) is after invert (2.000000) image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorout gamma module gamma (16.000000) is before colorout (69.000000) image 11803 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorout gamma module colorout (69.000000) is after gamma (16.000000) image 11803 (dt_dev_read_history_no_image end)

The thumbnail produced is either red, green, or black.  I can select the image and discard the history stack, then the image is imported correctly and displays a normal thumbnail with no errors in the console.

Opening one of the corrupted history stack images in darkroom shows input and out color profile at positions 6 and 7 instead of 5 and 6 in images that don't have errors.  All the images have also been imported in 2.6.2 without any errors.

On a corrupted image the history stack looks like:
8 - gamma
7 - output color profile
6 - input color profile
5 - highlight reconstruction
4 - white balance
3 - orientation
2 - raw black/white point
1 - demosaic
0 - original

After discarding the history stack it now looks like this:

8 - orientation
7 - gamma
6 - output color profile
5 - input color profile
4 - demosaic
3 - highlight reconstruction
2 - white balance
1 - raw black/white point
0 - original

darktable sometimes crashes with a segfault when trying to open the images with the corrupted history stack.

One thought on this.  All the images were high iso, so after I imported them, but before I scrolled through and generated thumbnails, I changed the demosaic to do color smoothing 3 times.  I left it on PPG.

As a test, I removed all the images from the database, then removed the xmp files and reimported them.  I only got ~5 corrupted history stacks and only one of those displayed as black.  The rest displayed good thumbnails.

I will try importing other large folders and see if the behavior continues.

**To Reproduce**
I'm not sure I can reproduce every time.  This appears to be somewhat random, though it seems fiddling with the demosaic makes it worse.

**Expected behavior**
Import all the files without error.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 2.7.0+2112~gb04bbeb29

**Comment by wpferguson** [comment]
So, after the import I tried the demosaic action again, changing color smoothing to three times on the first image.  I copied that history item, pasted it to the rest of the files.  Thumbnails started regenerating and darktable crashed.  Everytime I try and restart it, it crashes again.

**Comment by wpferguson** [comment]
The console output is: 
[dt_ioppr_check_iop_order] module temperature (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 14578 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module highlights (0)(28.000000) and temperature (0)(28.000000) have the same order image 14578 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module flip (0)(28.000000) and highlights (0)(28.000000) have the same order image 14578 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and flip (0)(28.000000) have the same order image 14578 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 14578 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule highlights cacorrect module cacorrect (5.000000) is before highlights (28.000000) image 14578 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (28.000000) image 14578 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 14578 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule highlights cacorrect module highlights (28.000000) is after cacorrect (5.000000) image 14578 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (28.000000) is after clipping (17.000000) image 14578 (dt_dev_read_history_no_image end)
/home/bill/bin/darktable30: line 1: 15667 Segmentation fault      (core dumped) /opt/darktable30/bin/darktable -d lua --configdir $HOME/.config/darktable30

**Comment by wpferguson** [comment]
Manipulated the recent collection entry in darktable so that I could restart it.  When I did, it started regenerating thumbnails and crashed again.  Manipulated the recent collections again, opened settings and told it to use the embedded preview then reimported the folder.  Got corrupted images of amazing colors and patterns.  Discarding history stack clears it up.

**Comment by TurboGit** [comment]
I suppose those 2873 were already imported at some point in darktable, right?

I don't see how the orientation could be at place 3 in the corrupt import!!! But there is always the possibility of a bug. So first I'd like to understand better the context.

This will also help @jenshannoschwalm which is quite expert on the iop-order at this point.

**Comment by wpferguson** [comment]
The 2873 were imported into 2.6.2 without issue.  I decided to process in 2.7 because they are high ISO and noisy and I wanted to take advantage of rawfiner's fine work.

I'll troubleshoot this with a slightly more disciplined process.  I just pulled the latest from git, did a clean build, and installed it.  I'll do multiple runs, with a fresh database each run, to see if there is any kind of pattern.  I'm planning to use SQL queries to get a better idea of the problem and isolate potential problem images.

**Comment by TurboGit** [comment]
Ok, if those were imported from the first time in 2.7 it is worry some. If you can isolate a picture (RAW + XMP) and dump the corresponding line in SQLite from images and history table it would be very helpful. Thanks.

**Comment by wpferguson** [comment]
First test - darktable default settings (i.e. using the embedded jpg for thumbnail).  All images imported without issue.  Checked the history entries and only had 9 for the first image which I opened in darkroom.  It appears the history stack isn't created until the image is opened in darkroom.

Second test - removed database from first test.  Set thumbnail to half size raw.  Images imported without issue.  Closed darktable after import and checked database.  Only the first 30 images had a history stack.  Reopened darktable, scrolled through all the images to generate thumbnails, and didn't get any errors. Yay!  Did some SQL queries on the history table and found a few images that had more than 9 (0 - 8)entries such as 
sqlite> select * from history where imgid = 1004 order by num;
1004|0|1|rawprepare|H|1||9|0||1.0
1004|1|3|temperature||1||9|0||3.0
1004|2|2|highlights||1||9|0||4.0
1004|3|3|demosaic||1||9|0||8.0
1004|4|6|colorin|
                 |1||9|0||28.0
1004|5|5|colorout||1||9|0||69.0
1004|6|1|gamma||1||9|0||77.0
1004|7|2|flip|����|1||9|0||16.0
1004|8|6|basecurve||1||9|0||43.0
1004|9|1|rawprepare|H|1||9|0||16.0
1004|10|2|flip|����|1||9|0||16.0
1004|11|3|temperature||1||9|0||3.0
1004|12|2|highlights||1||9|0||4.0
1004|13|3|demosaic||1||9|0||8.0

Will start a new test with another clean library and see if the same images give the same result.  Last time I got 7 images with large history stacks.  This time I go 6.  And none of the images identified this time where identified last time.  The one with the most entries appears to have written the history stack twice

sqlite> select * from history where imgid = 2592 order by num;
2592|0|1|rawprepare|H|1||0|0||1.0
2592|1|3|temperature||1||0|0||3.0
2592|2|2|highlights||1||0|0||4.0
2592|3|3|demosaic||1||0|0||8.0
2592|4|6|colorin|
                 |1||0|0||28.0
2592|5|5|colorout||1||0|0||69.0
2592|6|1|gamma||1||0|0||77.0
2592|7|2|flip|����|1||9|0||16.0
2592|8|6|basecurve||1||9|0||43.0
2592|9|1|rawprepare|H|1||0|0||1.0
2592|10|3|temperature||1||0|0||3.0
2592|11|2|highlights||1||0|0||4.0
2592|12|3|demosaic||1||0|0||8.0
2592|13|6|colorin|
                  |1||0|0||28.0
2592|14|5|colorout||1||0|0||69.0
2592|15|1|gamma||1||0|0||77.0
2592|16|2|flip|����|1||9|0||16.0
2592|17|6|basecurve||1||9|0||43.0


Did another test (4).  Got the dreaded console iop errors.  Image 16 was black.  Image 16 has been fine in all the tests so far.  The history table for image 16 is 

sqlite> select * from history where imgid = 16 order by  num;
16|9|1|rawprepare|H|1||0|0||28.0
16|9|6|colorin|
               |1||0|0||28.0
16|10|3|temperature||1||0|0||3.0
16|11|2|highlights||1||0|0||4.0
16|12|3|demosaic||1||0|0||8.0

If I try and open image 16 in darkroom I get 

[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 16 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 16 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 16 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 16 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 16 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 16 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_transform_image_colorspace_cl] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module rawprepare must be between input color profile and output color profile

Discarding the history stack fixes it.
16|13|2|flip|����|1||0|0||16.0




Test 5 - No console errors.  Several images with history stack counts greater than 9.

Test 6 - Scrolled though the images quicker this time and got 11 images with stack counts greater than 9

Test 7 - Tried scrolling through the images slowly to see if that lessened the amount of images with history stack counts greater than 9.  Instead I got 

[dt_ioppr_check_iop_order] module flip (0)(77.000000) and rawprepare (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorin (0)(77.000000) and flip (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorout (0)(77.000000) and colorin (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(77.000000) and colorout (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (77.000000) image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (77.000000) image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (77.000000) is after invert (2.000000) image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (77.000000) is after clipping (17.000000) image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_transform_image_colorspace_cl] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
[dt_ioppr_check_iop_order] module flip (0)(77.000000) and rawprepare (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorin (0)(77.000000) and flip (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorout (0)(77.000000) and colorin (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(77.000000) and colorout (0)(77.000000) have the same order image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (77.000000) image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (77.000000) image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (77.000000) is after invert (2.000000) image 986 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (77.000000) is after clipping (17.000000) image 986 (dt_dev_read_history_no_image end)
[dt_ioppr_transform_image_colorspace_cl] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile

in the console and a black thumbnail in lighttable.

history entry in database looks like this:

sqlite> select * from history where imgid = 986 order by num
   ...> ;
986|6|1|rawprepare|H|1||0|0||77.0
986|6|2|flip|����|1||0|0||77.0
986|6|6|colorin|
                |1||0|0||77.0
986|6|5|colorout||1||0|0||77.0
986|6|1|gamma||1||0|0||77.0
986|7|3|temperature||1||0|0||3.0
986|8|2|highlights||1||0|0||4.0
986|9|3|demosaic||1||0|0||8.0

Going slower resulted in 22 images with history stack counts greater than 9.

Test 10 - did the import with no console errors.  Used darktable-generate-cache to generate the thumbnails.  Only 2 images where over a count of 9 and they were both generated during the initial import.  It appears that darktable-generate-cache does not suffer from the IOP problems.
  
Test 11 - Different data set comprised of 1885 images.  This set imported with no errors.  Images were actually on a network drive so processing was slower generating the thumbnails.

Test 12 - New data set compised of 3089 images.  Images were on a network drive.  3 images had a high history stack count (>8).

Test 13 - Small data set on local SSD.  4 images with high history stack count (>8).

select * from history where imgid = 174 order by num;
174|4|6|colorin|
                |1||0|0||28.0
174|5|5|colorout||1||0|0||69.0
174|6|1|gamma||1||0|0||77.0
174|7|2|flip|����|1||9|0||16.0
174|12|6|colorin|
                 |1||0|0||28.0
174|13|5|colorout||1||0|0||69.0
174|14|1|gamma||1||0|0||77.0
174|15|2|flip|����|1||9|0||16.0

and here's the xmp

<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2019:10:19 15:30:50"
   xmp:Rating="0"
   xmpMM:DerivedFrom="102EOS7D2_D2_8607.cr2"
   darktable:xmp_version="3"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="0"
   darktable:iop_order_version="0">
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Bill Ferguson</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">(c) 2019 Bill Ferguson. All Rights Reserved.</
rdf:li>
    </rdf:Alt>
   </dc:rights>
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq/>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>


Ran one last test trying to create another black image and succeeded.

Console error

[dt_ioppr_check_iop_order] module flip (0)(28.000000) and rawprepare (0)(28.000000) have the same order image 660 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module colorin (0)(28.000000) and flip (0)(28.000000) have the same order image 660 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module invert (2.000000) is before rawprepare (28.000000) image 660 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module clipping (17.000000) is before flip (28.000000) image 660 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule rawprepare invert module rawprepare (28.000000) is after invert (2.000000) image 660 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (28.000000) is after clipping (17.000000) image 660 (dt_dev_read_history_no_image end)
[dt_ioppr_transform_image_colorspace_cl] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module rawprepare must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile

database history table 

sqlite> select * from history where imgid = 660 order by num;
660|8|1|rawprepare|H|1||0|0||28.0
660|8|2|flip|����|1||0|0||28.0
660|8|6|colorin|
                |1||0|0||28.0
660|9|3|temperature||1||0|0||3.0
660|10|2|highlights||1||0|0||4.0
660|11|3|demosaic||1||0|0||8.0

xmp 

<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2019:10:25 19:09:48"
   xmp:Rating="0"
   xmpMM:DerivedFrom="102EOS7D2_D2_9267.cr2"
   darktable:xmp_version="3"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="0"
   darktable:iop_order_version="0">
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Bill Ferguson</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">(c) 2019 Bill Ferguson. All Rights Reserved.</
rdf:li>
    </rdf:Alt>
   </dc:rights>
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="4800000026000000000000000000000000080008fb07fb07fc3a0000
"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="28.0000000000000"/>
     <rdf:li
      darktable:num="0"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="28.0000000000000"/>
     <rdf:li
      darktable:num="0"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz48eJzjYRgFowABWAbaAaNgwAEAPRQAEQ=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="28.0000000000000"/>
     <rdf:li
      darktable:num="1"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0060d33f0000803f0020fb3f0000c07f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="3.0000000000000"/>
     <rdf:li
      darktable:num="2"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="000000000000803f00000000000000000000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="4.0000000000000"/>
     <rdf:li
      darktable:num="3"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="8.0000000000000"/>
    </rdf:Seq>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>


Summary - I imported 30,000+ images and only got the really corrupted iop order (resulting in black image and possible segfault if you try and open in darkroom) 3 times.  Every time I did an import, except once, I got some history stacks with extra entries.  It didn't stop the image from displaying.  It all appears to be random, though the problem appears to occur more frequently when the images are on a local SSD.  Images on a network drive (slower access) show less or no history stacks with extra entries.

I've included the databases from the last test.  The corrupt image id was 660.  You can also check the images with large history stacks by 

select imgid from history where num > 8

since there shouldn't be a num greater than 8 because I had base curve turned off.

I'll try looking at the iop code and see if anything jumps out at me.


Bill
[last_test.zip](https://github.com/darktable-org/darktable/files/3799968/last_test.zip)

**Comment by wpferguson** [comment]
Tried disabling opencl, but it didn't seem to make a differrence.

**Comment by wpferguson** [comment]
I had a thought...

Since dt_ioppr_check_iop_order has caught every corrupted history stack, could the processing be restarted if dt_ioppr_check_iop returns iop_order_ok = 0 (i.e. do a discard history stack equivalent and just regenerate the history stack)?

**Comment by TurboGit** [comment]
Thanks for the testing! From your report the issue seems clear... We are missing a lock and get corrupted db when dt is massively updating it. Now the challenge is to find where a lock is missing :(

**Comment by TurboGit** [comment]
@jenshannoschwalm : maybe you have an idea about this ?

**Comment by TurboGit** [comment]
@wpferguson : can you try this https://github.com/darktable-org/darktable/pull/3256 ?

The import should be slower, but it will help understanding where the issue is maybe. Thanks.

**Comment by jenshannoschwalm** [comment]
@TurboGit still enjoying moscow, will dig into this on Monday.

**Comment by wpferguson** [comment]
You're right, it's slower :-D.  But, it did work.  No extra history stack items, no corrupt history stacks.

**Comment by TurboGit** [comment]
@wpferguson : thanks, at least we know where to look now and we have a safe (even if slower) backup solution for the release if we cannot find better.

BTW, how slower it is on your side? x2 x3 ? More? Is that something a user can live with? Just want to have your feeling about this.

**Comment by TurboGit** [comment]
Found the culprit I think. Latest master should fix this. Please can you test again?

**Comment by TurboGit** [comment]
For the record I was able to reproduce when not using the embedded jpegs in the RAW. With the fix just committed I cannot reproduce anymore, so I'm confident that it fixes this issue. Thanks for reporting just in time for the first RC !

**Comment by wpferguson** [comment]
Tested and works.  I did the full import, with fast scroll, then backed through to finish completing the thumbnails.  In the past this usually results in a corrupted history stack on at least one image, and multiple images with extra history stack entries.  This time there were no errors.  Gook job, @TurboGit!
