### ISSUE TITLE
Slideshow Extremely slow and freezes

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3253]
**Describe the bug**
Have collection of 448 pics.
In lightable view.
Press S to start slideshow.
Machine starts spinning out of control with memory usage spiking, mouse disappears.
Slideshow preference has a 1 second delay between images.
Press the space bar to start slideshow.
Images dont change, clicking on the screen or using arrow keys or tab does nothing or it takes a long time to do anything
When it does start to change  the pic the CPU usage is 100% memory usage crosses 1Gb, after  slide change it comes back to 0.
I have seen the usage climb as high as 
![image](https://user-images.githubusercontent.com/1119439/68066354-70097f80-fd5c-11e9-93c5-fd6f20cd1553.png)

What I have figured out with trial and error, left click takes it forward, right click takes it backwards, havent figured out how to get out of the slideshow yet. Is this documented somewhere ?

Have to kill darktable to get out of slideshow.
Opencl is permanently disabled on my 2.7 version.
Have 32 GB Ram.
Images are on external SSD.

**Platform (please complete the following information):**
 - OS: Win 10
 - Version 2.7.0+2113~gefde14b3d

**Comment by blitzgneisserin** [comment]
appears to behave very similarly here, dt 2.7 on Mx 19

**Comment by TurboGit** [comment]
Can you try disabling the slidewhow high quality option in the preference and test again?

**Comment by TurboGit** [comment]
Or make the delay between each image something like 10s and start again the experiment; It may be that the time rendering an image is too long in high-quality for the delay. Just guessing...

**Comment by TurboGit** [comment]
Clicking on space will stop the slideshow. Clicking on any unsupported key in slideshow will quit it (like q for example). Note that there is a small delay as nothing happens until the currently rendered image is displayed.

**Comment by TurboGit** [comment]
> When it does start to change the pic the CPU usage is 100% memory usage crosses 1Gb, after slide change it comes back to 0.

That's ok, the image is rendered and it indeed takes lot of CPU and memory to run the pixelpipe.

**Comment by blitzgneisserin** [comment]
ok. apparently that's it. thanks

**Comment by TurboGit** [comment]
I'm wondering if a safe guard won't be to not allow delay below 4 seconds ? After all a slideshow is at least to see the picture !

**Comment by chhil** [comment]
>Can you try disabling the slidewhow high quality option in the preference and test again?
This resolves it for me. Thank you @TurboGit .

>I'm wondering if a safe guard won't be to not allow delay below 4 seconds ? After all a slideshow is at least to see the picture !
I assume there is no key to pause the slideshow. If there was I can see why one may want to speed through some images and then use the forward back to see surrounding images.

Though I did get a rare flicker before next image.
