### ISSUE TITLE
Import Dialogues Cut off corners (top)

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#3254]
*neofetch:*
```
OS: Arch Linux x86_64 
Host: TM1701 
Kernel: 5.3.7-arch1-2-ARCH 
Uptime: 1 hour, 32 mins 
Packages: 2354 (pacman), 20 (flatpak) 
Shell: bash 5.0.11 
Resolution: 1920x1080 
DE: GNOME 3.34.1 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: NVIDIA GeForce MX150 
GPU: Intel UHD Graphics 620 
Memory: 5554MiB / 15899MiB 
```
*DT Master*

*Issue*
When opening dialogues the top corners are cut off, and there is no window shadow (shadow is less of a problem)

![import_diagloue](https://user-images.githubusercontent.com/12004932/68066716-73b4fa80-fd8c-11e9-8692-8fdd4b7554ad.png)

**Comment by Nilvus** [comment]
Thanks for reporting that. I had corrected that on PR #2504 merged in may. Probably recent great improvements on CSS by @aurelienpierre broken that. I will work on correcting that again this afternoon.
