### ISSUE TITLE
Expose OpenCL building options in darktablerc

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3258]
#3234 and other issues have shown that the same [building options](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clBuildProgram.html) give various results depending on the vendor × driver combination. 

I think hard-coding every possible combinations will backfire. So I see 2 options here:

1. let power users add custom building options in darktablerc, like:
````
opencl_building_gpu0=-cl-mad-enable -cl-no-signed-zeros -cl-unsafe-math-optimizations -cl-finite-math-only -cl-fast-relaxed-math
opencl_building_gpu1=-cl-mad-enable -cl-no-signed-zeros
````
2. let every user check the wanted options in a checklist in preferences, for each GPU.

**Comment by parafin** [comment]
1. is better.

**Comment by TurboGit** [comment]
I agree with @parafin, option 1 for me too.
