### ISSUE TITLE
[FR] Export Dialogue show Megapixel sampling

### ISSUE THREAD

**Issue by alcomposer** [darktable-org/darktable#3269]
Currently we are able to set custom width:height for output images.

It would be good to also have a megapixel setting for down-sampling. 

That way a user could simply type in a value, 9; 12; 24 megapixel output size.

This setting would effect the whole image- not width only - or height only.

**Comment by johnny-bit** [comment]
Huh. This is interesting! Can I have no-issue-activity taken off of this and I'll try to add those?

**Comment by johnny-bit** [comment]
I saw 2 ways about doing it now... Both suck ;)
1. Just write out how many MPix is there for specified width/height
2. create set of presets for the export module with only specified width/height... but then export module preset also has file format & storage preset :/

then there are other 2:
3. actual entry, similar to current "scale" or "print size" which will allow user to input: mpix and ratio.
4. combobox with several common sizes...
