### ISSUE TITLE
A 'virgin' image previously opened in 2.6.2 and its 'virgin' duplicate have different module order

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#3270]
I understand the logic behind the following issue, but I think it'd be worth mentioning it in the documentation: opening a seemingly virgin image that had an XMP created by dt version < 3 (e.g. 2.6.2) will keep the legacy module order; in order to switch to the new module order, a 'virgin' duplicate needs to be created.
Also, the effect of copying an individual module, or a set of modules, from one image's history stack to another could have confusing effects (did not test that).

Rev. 99cf6ae5e, Kubuntu 19.04.
I started with an image I had previously imported into darktable 2.6.2. I did not perform any editing in 2.6.2, except for the application of some styles that I always apply (e.g. base curve = off, lens correction = on, hot pixels = on).

I closed dt 2.6.2. My compiled-from-master darktable uses a completely distinct directory structure (config, data, cache). I imported the image into dt 3.

The module order was not the one from dt 3.

I clicked the (+) icon (create 'virgin' duplicate) in the duplicate manager. The order of modules changed to the dt 3 defaults in the duplicate.

In the following shared folder, you'll find:
- the raw file (2019-10-14_15-44-48_DSC_0096.NEF);
- the XMP from dt 2.6.2 (2019-10-14_15-44-48_DSC_0096.NEF.xmp);
- the XMP written by dt 3 for the duplicate (2019-10-14_15-44-48_DSC_0096_01.NEF.xmp)
- screenshots showing the module order (orig-from-dt-2.6.2.png for 2019-10-14_15-44-48_DSC_0096.NEF.xmp, virgin-duplicate.png for 2019-10-14_15-44-48_DSC_0096_01.NEF.xmp)
https://drive.google.com/open?id=1A8XnGYE55zPttbiemLKQd93UXtKY6DXn

**Comment by junkyardsparkle** [comment]
To clarify, are you saying the issue is that the duplicate doesn't retain the "legacy" module order of the original? That's the only part of this that I can see as possibly "unexpected" behavior...

**Comment by kofa73** [comment]
Nope. It's that if you imported an image into DT 2.x, didn't really edit it, then upgraded to 3, you'll get the legacy module order. It's understandable, but I think it's worth mentioning.
The other is what happens when you copy (part of) the history from another image (possibly from 2.x), with source and target having different module order - I think that can be quite complicated (what if you just copy one module? what if more? in append mode? overwrite mode?).

**Comment by junkyardsparkle** [comment]
I think the phrase "didn't really edit it" isn't very well defined, but I would say it certainly doesn't apply if you have auto-presets enabled - that's editing, whether it involved user interraction or not. :-)

> The other is what happens when you copy (part of) the history from another image (possibly from 2.x), with source and target having different module order - I think that can be quite complicated (what if you just copy one module? what if more? in append mode? overwrite mode?).

Last I heard, the logic was decided to be: images with same iop order version, use the changed module locations; different iop order version, use the defaults for destination image. There might be potential for some unexpected results here... is there a specific case you can describe?

**Comment by kofa73** [comment]
> I think the phrase "didn't really edit it" isn't very well defined, but I would say it certainly doesn't apply if you have auto-presets enabled - that's editing, whether it involved user interraction or not. :-)

That's why I started with 'I understand the logic behind the following issue'.

> Last I heard, the logic was decided to be...

OK. I just suggested that it be documented in the manual by those in the know (if possible, with more user-friendly wording, e.g. not 'iop' but 'module', etc.).

**Comment by junkyardsparkle** [comment]
Agreed. There's a lot about this release that needs to be made clear to people... hopefully they'll RTFM. There's still a possibility of some things changing if the release candidates uncover new issues, though. Give it some good testing!

**Comment by groutr** [comment]
Will there be a way to preview and then migrate edits to the new iop order?

**Comment by TurboGit** [comment]
Maybe migrate and then undo ctrl-z will do?

**Comment by johnny-bit** [comment]
AFAIU - "works as intended", even for "silly" things like basecurve vs filmic and legacy vs modern color workflows. Image imported with "old" settings is considered for "old" flow and image imported (basically creating virgin duplicate is re-importing image)
