### ISSUE TITLE
[Tone Equalizer] Masking Issue

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3274]
**Describe the bug**
darktable-3.0.0rc0+3~g58605f701-win64
Default image loaded.
Tone equalizer enabled and go to masking tab.
![image](https://user-images.githubusercontent.com/1119439/68101354-4171dd00-fef3-11e9-913e-f6d77913648f.png)

Dragged exposure histogram, got the mask processing bar change as exposure was increased.
![image](https://user-images.githubusercontent.com/1119439/68101390-70884e80-fef3-11e9-82cf-e12726d42a10.png)

Now reset params was clicked and module disabled.
![image](https://user-images.githubusercontent.com/1119439/68101417-8c8bf000-fef3-11e9-9f4d-b4117c379c0a.png)

Now enable the module.
Based on where the increased exposure is I expected the mask to get generated again to the value prior to reset, but mask processing bars remains empty.

![image](https://user-images.githubusercontent.com/1119439/68101481-dc6ab700-fef3-11e9-9119-f964ff67fdf3.png)

I was expecting the bar to re appear as it was before.

If I do the exposure first and then enable tone equalizer it works as expected.

**Comment by chhil** [comment]
Also when exposure is increases, it shows up in the history but not in the modules used tab. Its a refresh issue, need to go to a different tab and come back.

**Comment by aurelienpierre** [comment]
Cache invalidation issues. I might have a fix soon.
