### ISSUE TITLE
Build time warning with pages in different languages

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3276]
**Describe the bug**
While building getting the following...

no introspection requested for rawoverexposed.c.
no introspection requested for clahe.c.
Your input po file po/de.po seems outdated (The amount of entries differ between files: 239 is not 17
). Please consider running po4a-updatepo to refresh it.
Your input po file po/fr.po seems outdated (The amount of entries differ between files: 239 is not 31
). Please consider running po4a-updatepo to refresh it.
Your input po file po/de.po seems outdated (The amount of entries differ between files: 239 is not 31
). Please consider running po4a-updatepo to refresh it.
Your input po file po/de.po seems outdated (The amount of entries differ between files: 239 is not 189
). Please consider running po4a-updatepo to refresh it.
Your input po file po/de.po seems outdated (The amount of entries differ between files: 239 is not 47
). Please consider running po4a-updatepo to refresh it.
Your input po file po/de.po seems outdated (The amount of entries differ between files: 239 is not 17
). Please consider running po4a-updatepo to refresh it.
Your input po file po/es.po seems outdated (The amount of entries differ between files: 234 is not 17
). Please consider running po4a-updatepo to refresh it.
Your input po file po/es.po seems outdated (The amount of entries differ between files: 234 is not 31
). Please consider running po4a-updatepo to refresh it.
Your input po file po/es.po seems outdated (The amount of entries differ between files: 234 is not 189
). Please consider running po4a-updatepo to refresh it.
Your input po file po/es.po seems outdated (The amount of entries differ between files: 234 is not 17
). Please consider running po4a-updatepo to refresh it.
Your input po file po/es.po seems outdated (The amount of entries differ between files: 234 is not 47
). Please consider running po4a-updatepo to refresh it.
Your input po file po/fr.po seems outdated (The amount of entries differ between files: 239 is not 17
). Please consider running po4a-updatepo to refresh it.
Your input po file po/fr.po seems outdated (The amount of entries differ between files: 239 is not 189
). Please consider running po4a-updatepo to refresh it.
Your input po file po/fr.po seems outdated (The amount of entries differ between files: 239 is not 47
). Please consider running po4a-updatepo to refresh it.
Your input po file po/fr.po seems outdated (The amount of entries differ between files: 239 is not 17
). Please consider running po4a-updatepo to refresh it.

I couldn't find po4a-updatepo to run.

Ran the build using the following on my windows machine...

#!/bin/bash
cd ~
#rm -R ./darktable/
#git clone git://github.com/darktable-org/darktable.git

cd darktable
git pull
#git checkout 580bf49
#git submodule init
git submodule update
mkdir build

cd build
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBINARY_PACKAGE_BUILD=ON -DCMAKE_INSTALL_PREFIX=./debugReleaseDT ../.
cmake --build .
cmake --build . --target install
cmake --build . --target package

**Comment by peterbud** [comment]
`po4a-updatepo` is part of `po4a`, which is needed only for the usermanual:
https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt#L42

I had no problem today building 3.0 rc0

**Comment by chhil** [comment]
My build instructions are provided, I don't build the user manual.

**Comment by johnny-bit** [comment]
The problem is present because translations don't keep up with master in regards to strings and so the warnings are simply that: just warnings. Meant to encourage translations if that's your thing ;) po4a-upddaterepo is required if you'd wish to contribute translations :)
