### ISSUE TITLE
mask strange pattern

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#3277]
**Describe the bug**
After activating and tweaking many modules, I tweak denoise and apply a parametric mask. The mask behaves as expected.
When I zoom to 100%, the mask shows stripes and seems to cover a different area than at zoom out

**To Reproduce**
1. Open the raw attached and apply the attached xmp.
2 - go to denoise profile and activate the mask. It should cover darker areas
3 - Zoom in at 100%

**Expected behavior**
The mask shows a wrong pattern, as show in the screenshot.

**Screenshots**
Zoom out - mask ok
![Screenshot from 2019-11-04 07-37-03](https://user-images.githubusercontent.com/46730249/68114923-fb5a5080-fed5-11e9-8bc2-1c13223de9c9.png)

zoom at 100% - wrong pattern
![Screenshot from 2019-11-04 07-38-51](https://user-images.githubusercontent.com/46730249/68115014-2ba1ef00-fed6-11e9-851b-3051d0edb501.png)

**Platform (please complete the following information):**
 - OS: ubuntu 18.04
 - Version 3.0.0-git6.3540

**Additional context**
Raw and xmp -> [https://drive.google.com/open?id=1l04EROSSaKseS0yuEaiXe76CAT1adUQb](https://drive.google.com/open?id=1l04EROSSaKseS0yuEaiXe76CAT1adUQb)
Note: After posting this bug report, I updated DT to the version stated above, and the issue remains.

**Comment by blitzgneisserin** [comment]
looks very similar here though not exactly the same
![Screenshot at 2019-11-04 12-00-26](https://user-images.githubusercontent.com/16564210/68116321-cf04fb00-fefa-11e9-898f-46cd7f96a5a9.png)

**Comment by groutr** [comment]
I get the same behavior.  I tried on one of my raw images where only denoise profile was activated (parametric mask to only the darkest input areas).  Zooming in at all produces a garbled mask.
Tried parametric mask on lowpass module as a control and I don't see a garbled mask there.
