### ISSUE TITLE
No tarball for 3.0.0rc0

### ISSUE THREAD

**Issue by hfiguiere** [darktable-org/darktable#3278]
There is not tarball for 3.0.0rc0. Just the automatically generated one.

(I got the release notification email and it had them, but everything is gone)

**Comment by chhil** [comment]
Only 2 source assets are present at the URL mentioned in the release notification 

https://github.com/darktable-org/darktable/releases/tag/release-3.0.0rc0

**Comment by parafin** [comment]
Release is not yet published, be patient. Notification email was sent by error (I pressed the wrong button).
