### ISSUE TITLE
OSX: toneequal performance: dramatical slowdown in 100% view

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3285]
**Describe the bug**
enabling toneequalizer slows down the processing in 100% view:

without toneequalizer:
`461,207339 [dev_process_image] pixel pipeline processing took 0,617 secs (0,825 CPU)`
with toneequalizer (default setting)
`543,471325 [dev_process_image] pixel pipeline processing took 24,894 secs (169,061 CPU)`

fit to screen view:
without:
`990,819389 [dev_process_image] pixel pipeline processing took 0,890 secs (3,468 CPU)`
with:
`1085,089492 [dev_process_image] pixel pipeline processing took 1,275 secs (6,214 CPU)`

on export:
without:
`1357,441986 [dev_process_export] pixel pipeline processing took 11,130 secs (23,644 CPU)`
with toneequal:
`1298,763360 [dev_process_export] pixel pipeline processing took 20,778 secs (96,342 CPU)`

the -d perf output tells me it's not using GPU and beein processed on cpu
`543,024582 [dev_pixelpipe] took 21,650 secs (158,445 CPU) processed `tone equalizer' on CPU, blended on CPU [full]`

processing time scales with the scale factor:
30%: [dev_process_image] pixel pipeline processing took 2,607 secs (15,862 CPU)
50%: [dev_process_image] pixel pipeline processing took 5,171 secs (33,202 CPU)
67%: [dev_process_image] pixel pipeline processing took 9,122 secs (61,960 CPU)
85%: [dev_process_image] pixel pipeline processing took 16,828 secs (115,837 CPU)
100%: [dev_process_image] pixel pipeline processing took 25,011 secs (173,619 CPU)

**Platform (please complete the following information):**
 - OS: OSX
 - Version 3.0.0 rc0

**Comment by aurelienpierre** [comment]
Duplicate of #3081

**Comment by MStraeten** [comment]
#3395 and several further improvements brings significant performance improvement of tone equalizer in combination with denoise - so i close this
