### ISSUE TITLE
"rgb levels" vs "base curve" position in iop order

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3286]
I see the new "rgb levels" iop as an improvement over the legacy "levels" iop, with the great advantage to preserve colors.
"levels" is applied AFTER "base curve", and this seems logical to me.
But the current default iop order is to have the new "rgb levels" BEFORE "base curve", and I'm questioning this.
Today, each time I want to use the new "rgb levels" the same way I was using "levels", I've to manually move it after "base curve".
Do I miss-understand the purpose of the new "rgb levels" iop ?

**Platform (please complete the following information):**
 - Version 2.7.0+2177~g58605f701

**Comment by TurboGit** [comment]
This is the order that Aurélien has proposed. I can't comment about this choice, I'll let Aurélien comment.

**Comment by leclercj** [comment]
Asking @aurelienpierre to provide his view then. Thanks

**Comment by aurelienpierre** [comment]
Base curve is a camera rendering transform (as is filmic) that corrects the linear sensor reading to a visually plausible image (aka : raise midtones, add contrast). Before it, the RGB signal is assumed to be scene-referred, after it, the RGB signal is assumed to be display-referred.

The thing is RGB curves and levels can work both in scene-referred and display-referred spaces, but theory and practice show that scene-referred spaces are better behaved when doing colour adjustments, and are necessary if you are doing alpha blending and occlusion (using masks, parametric blending and opacities). So, I have put the RGB curves and levels when they are the most robust : before non-linear camera transforms.

But… the legacy tone curve and levels wark in Lab colour space, which is not suitable for HDR imagery (> 5 EV dynamic range) and therefore they need to be used after the scene-referred signal (that can be HDR or LDR depending on the shot) is tone mapped to a LDR signal (again, using that 
camera transform). So the Lab modules are but after base curve and filmic.

**Comment by spaceChRiS** [comment]
I wonder what happens to signal values > 1 in these modules, or is the input already clamped?

**Comment by aurelienpierre** [comment]
Nothing is clamped in them, but values > 1 get extrapolated settings, and this works more or less (sometimes less rather than more). As a general rule of thumb, it's better to avoid clipping anyway.

**Comment by spaceChRiS** [comment]
Thanks :) Maybe we need a per module clipping indicator at some point in the future ;)

**Comment by junkyardsparkle** [comment]
> Today, each time I want to use the new "rgb levels" the same way I was using "levels", I've to manually move it after "base curve".

Ultimately, since there's no default ordering that will satisfy everybody, my feeling is that we need a way to quickly and easily replicate our own frequently used re-orderings. #3266 is my own crazy proposal for how this might be implemented; feedback appreciated.

**Comment by leclercj** [comment]
Thank you @aurelienpierre for your explanations. I now better understand the iop order choices and I'll adapt my workflow to use it as defined, as it make more sense to me now: adjust levels or exposure BEFORE non-linear transforms like base curve or filmic.
One difficulty remains for me with usage of rgb levels. The histogram in rgb levels seems to have a bias that I don't understand. But this is another story.
I agree with @junkyardsparkle that a way to quickly and easily replicate our own frequently used re-orderings would be nice. I'll have a look at your #3266 proposal.
