### ISSUE TITLE
Opencl disabled on system due to multiple runs of darktable-cltest

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3292]
**Describe the bug**

In 2.6.2 opencl was available but with 2.7 onwards its permanently disable on my system.
I was trying to figure out why that was the case.
I think I probably ran darktable cl test multiple time causing this grief.

Steps to reproduce.
I deleted contents of C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCache\darktable

Ran darktable-cltest first time and output is 
[out.txt](https://github.com/darktable-org/darktable/files/3808384/out.txt)

Darktable preference shows opencl is available
 ![image](https://user-images.githubusercontent.com/1119439/68198669-81fc5400-ffe2-11e9-8ba8-824b873b13dc.png)

If darktable-cltest is run the second time without deleting any files the output is
[out1.txt](https://github.com/darktable-org/darktable/files/3808391/out1.txt)
It conveys that the opnecl is not supported.

And can be seen in the preferences.
![image](https://user-images.githubusercontent.com/1119439/68198869-df90a080-ffe2-11e9-9e3f-45137ca7b0b2.png)

**Platform (please complete the following information):**
 - OS: Win 10, Graphics card Intell HD Graphics 4600 and AMD Fire Pro 5100
 - Version [3.0 rc0]

Currently, I have got back my opencl enabled and set to multiple GPU.
If it matters these were the folders created under  C:\Users\<user>\AppData\Local\Microsoft\Windows\INetCache\darktable

cached_kernels_for_Capeverde_18005VM
cached_kernels_for_IntelRHDGraphics4600_2019154835
mipmaps-c008acc5801fe7ae410de802a78ec92fab3af0a7.d

**Comment by chhil** [comment]
Then midway in the exercise, I turned opencl off.  While editing an image it went out of control with mouse spinning (I was doing the white balance).
Eventually killed the app and restarted. On restarted I check the preferences and opencl was no longer available.

![image](https://user-images.githubusercontent.com/1119439/68200801-96dae680-ffe6-11e9-9e82-45158501fc28.png)

**Comment by jenshannoschwalm** [comment]
Is it really a good idea to have multiple gpus forced on? Also i vaguely remember there have already been issues with dual graph cards on windows.

**Comment by chhil** [comment]
It's what darktable picks up. On my laptop one card is for it's lcd and the other is for external monitor. Nothing powerful though.

**Comment by peterbud** [comment]
Your Intel card is definitely not supported: Intel's OpenCL driver is blacklisted in darktable due to the known problems.

The AMD card is more than 5 years old, and it seems that you have an outdated driver:
https://www.amd.com/en/support/professional-graphics/firepro/firepro-wx100-series/firepro-w5100
You might try the latest driver (19.10.24), that supports OpenCL 2.0 according to the description:
https://www.amd.com/en/support/kb/release-notes/rn-pro-win-19-q3-1

I never had any AMD card, so I cannot advise further.

**Comment by chhil** [comment]
So what does this mean, I can't use opencl because my version is at 1.2 for the driver?


@peterbud 
Thank you for the feedback.
Yes laptop (Dell Precision 4800)  and card are old. I did install the updated driver now.
![image](https://user-images.githubusercontent.com/1119439/68269729-e40b9680-0080-11ea-9023-64b41a1d9051.png)

The old one gave 
[opencl_init] device 0: Capeverde 
     GLOBAL_MEM_SIZE:          2048MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1800.5 (VM)
     DEVICE_VERSION:           OpenCL 1.2 AMD-APP (1800.5)


the new one gave
[opencl_init] device 2: Capeverde 
     GLOBAL_MEM_SIZE:          2048MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 1024 ]
     DRIVER_VERSION:           2841.5
     DEVICE_VERSION:           OpenCL 1.2 AMD-APP (2841.5)

Confirmed that its only opencl 1.2  supported even with the latest driver.
![image](https://user-images.githubusercontent.com/1119439/68270402-28983180-0083-11ea-8f10-7ec07c52d181.png)

**Comment by chhil** [comment]
Not seeing this currently.
