### ISSUE TITLE
UI grows out of the 13" size screen can't risize

### ISSUE THREAD

**Issue by concealedResonances** [darktable-org/darktable#3295]
**Describe the bug**
No matter what I do, the UI won't fit the screen, I can't resize it and when entering fullscreen still I'm loosing UI function on one side or the other.

**To Reproduce**
test the application on a Mac with a screen smaller than 15"

**Expected behavior**
This was never an issue before 

**Platform (please complete the following information):**
 - macOS 10.15.1 on MacBook Pro retina 13" 2015
 - darkatble 3.0.0rc0

**Additional context**
Even if enter full screen one one the side bar becomes inactive

**Comment by Nilvus** [comment]
Could you please post a screen capture to see what you have ? And which theme do you use ? Which resolution your screen have ? Is it the default retina one or another ? Have you check if screen_dpi settings on darktablerc file (in your .config/darktable folder) have the default setting on -1.0 (both screen settings) ?

I use (on Linux) same screen as I have a Macbook Pro Retina 13" late 2013 and never had problems to have whole darktable UI correctly.

**Comment by Nilvus** [comment]
Could you please post a screen capture to see what you have ? And which theme do you use ? Which resolution your screen have ? Is it the default retina one or another ? Have you check if screen_dpi settings on darktablerc file (in your .config/darktable folder) have the default setting on -1.0 (both screen settings) ?

I use (on Linux) same screen as I have a Macbook Pro Retina 13" late 2013 and never had problems to have whole darktable UI correctly.

**Comment by concealedResonances** [comment]
Could you please post a screen capture to see what you have ?
- I attached all of them including screen shots of darktable 2.6.3

And which theme do you use ?
- Darktable

Which resolution your screen have ? Is it the default retina one or another ?
- 1440x900

Have you check if screen_dpi settings on darktablerc file (in your .config/darktable folder) have the default setting on -1.0 (both screen settings) ?

- I have look at it before posting the issue and all was good, I knew about this already

I use (on Linux) same screen as I have a Macbook Pro Retina 13" late 2013 and never had problems to have whole darktable UI correctly.
- I only had the same problem once maybe 3 years ago (that’s how I know about .config setting) and the issue was resolved with an update.

thanks

<img width="1440" alt="Screenshot 2019-11-06 at 4 20 04" src="https://user-images.githubusercontent.com/57402269/68240194-c7a33600-004f-11ea-96ac-c0c2e292c249.png">

<img width="1060" alt="Screenshot 2019-11-06 at 4 22 06" src="https://user-images.githubusercontent.com/57402269/68240195-c7a33600-004f-11ea-8f02-542af46ea651.png">

<img width="1440" alt="Screenshot 2019-11-06 at 4 26 27" src="https://user-images.githubusercontent.com/57402269/68240196-c83bcc80-004f-11ea-96e1-b1df6e69b2a4.png">

<img width="1440" alt="Screenshot 2019-11-06 at 4 26 49" src="https://user-images.githubusercontent.com/57402269/68240197-c83bcc80-004f-11ea-8aa3-375047927af7.png">

<img width="1440" alt="Screenshot 2019-11-06 at 4 28 55" src="https://user-images.githubusercontent.com/57402269/68240198-c8d46300-004f-11ea-9e39-a0fbe0eb6032.png">

<img width="752" alt="Screenshot 2019-11-06 at 4 30 36" src="https://user-images.githubusercontent.com/57402269/68240199-c8d46300-004f-11ea-80ec-1125464f2a79.png">

**Comment by Nilvus** [comment]
Ok, so you don't have the normal behaviour we developed. As the CSS is made, it tells to GTK to rendering the UI related to OS font (that's not what you have). It's probably related to dpi specific rendering on MacOS (or some MacOS screens) who makes the text bigger than it should. Quite difficult here as darktable is made by most developers working on Linux and a few ones on MacOS or Windows. On darktable dev mailing lists, @aurelienpierre see that specific issue this day on the Mac of a friend of him.

If you could test if this PR by @aurelienpierre help to solve what you have : #3068

**Comment by bouscram** [comment]
I have a similar problem on a (non Retina) iMac (resolution = 1920 x 1080) : the font size is way too big. By tweeking the theme css, I found that reducing the size by 30% (using 0.7em instead of 1.0em) seemed good for me.

**Comment by parafin** [comment]
I didn't quite get it - is there is a difference between 2.6 and 3.0 in font rendering?

**Comment by MStraeten** [comment]
I found setting the screen_dpi_overwrite to 95 solved that behaviour on my macbook. You need to tweak the value until a reasonable size is found.

**Comment by bouscram** [comment]
Nice finding! On my iMac, it's more 70 or 75, but I guess it really depends on the screen size and actual DPI.

**Comment by concealedResonances** [comment]
Eventually, I tried with difference values suggested here and ...screen_dpi_overwrite=93 seems to do the job for me. I can resize the window and works like expected in full screen. Thank you

**Comment by parafin** [comment]
I've compared 2.6 and 3.0 too, and indeed font size is much bigger on 3.0. I've now disabled DPI auto-detection, so next package will work as if screen_dpi_overwrite is set to 72 (if it's not overridden in config file). If for you 96 looks OK, then 72 will look too small probably, but font size should actually be the same as in all native macOS applications (e.g. Finder). Hopefully #3207 will be implemented and user will be able to modify font size in preferences instead of editing config files manually.

**Comment by sotsoguk** [comment]
> I've compared 2.6 and 3.0 too, and indeed font size is much bigger on 3.0. I've now disabled DPI auto-detection, so next package will work as if screen_dpi_overwrite is set to 72 (if it's not overridden in config file). If for you 96 looks OK, then 72 will look too small probably, but font size should actually be the same as in all native macOS applications (e.g. Finder). Hopefully #3207 will be implemented and user will be able to modify font size in preferences instead of editing config files manually.

This is something i noticed as well. On my macbook 15" (2012), for older versions i had to change dpi to 120 and ui-scale to 1.2 in order for the text to be readable. Now i had to go back to dpi 90 and ui-scale to the default 1.0

**Comment by aurelienpierre** [comment]
> I didn't quite get it - is there is a difference between 2.6 and 3.0 in font rendering?

3.0 uses the default OS font size as its base UI font size, so it is no longer hardcoded (and set to 10pt IIRC) in the CSS.
