### ISSUE TITLE
darktable-cmstest: Not in current install

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3305]
**Describe the bug**
The [online user manual](https://www.darktable.org/usermanual/en/overview_chapter.html#darktable_cmstest_commandline_parameters) talks about darktable-cmstest, I cannot find the executable in the current build/install.

**Platform (please complete the following information):**
 - OS: Win 10
 - Version [darktable-3.0.0rc0+23~gcb0aaf0c1-win64]

**Comment by blitzgneisserin** [comment]
I think darktable-cmstest is only available on Linux (maybe this should be mentioned in the documentation)

**Comment by chhil** [comment]
@TurboGit Can this be specified in the user manual?

**Comment by TurboGit** [comment]
@parafin : is darktable-cmstest provided on MacOS ?

**Comment by parafin** [comment]
No, because it's pointless on macOS. GTK/cairo on macOS can only render in sRGB colorspace, which is converted to display profile by OS.

**Comment by TurboGit** [comment]
Closing, doc fixed here: 17cc55e611d338052d9626e9a72fee33716a7cc6
