### ISSUE TITLE
Darkroom: mouse hover filmstrip strange/misaligned

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#3312]
**Describe the bug**
When I want to select another picture in darkrooms filmstrip, the highlighting flips at a strange moment, when you reached ~50% of the next picture.

**Expected behavior**
When the mouse cursor slides over the filmstrip, the highlighting should flip, once the mouse is about a certain (small) amount of pixels of the next photo

**Screenshots**
I think it is very hard to demonstrate via screenshot, if someone has a good idea, how I could show better than with words, I will add...

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version 3.0.0rc0+47~gd859b89a2

**Comment by AxelG-DE** [comment]
Btw: the consequence is, when you want to change the active picture thru clicking on filmstrip, often nothing happens, because wrong picture is highlighted.

**Comment by TurboGit** [comment]
@AxelG-DE : I cannot reproduce that, and I have never ever experienced such issue since I'm using dt. Really strange...

**Comment by AxelG-DE** [comment]
Hmmmm
I tried with --configdir /tmp and in the first place it looked, the effect is gone
than I tried with removed ~/.config/darktable and in the first place it looked gone, until I found the **reaction is differently strong on different positions in the filmstrip...**

This Moment it should have flipped:
![Screenshot_20191107_201521](https://user-images.githubusercontent.com/49004103/68420563-df3c0500-019c-11ea-8f9a-9c832fbb3231.png)

This Moment it actually flipped:
![Screenshot_20191107_202745](https://user-images.githubusercontent.com/49004103/68420666-1e6a5600-019d-11ea-8b48-12f00e2c1c74.png)

**Comment by junkyardsparkle** [comment]
I can't reproduce this either... are you sure it's not a *time* lag rather than a *distance* issue?

**Comment by AxelG-DE** [comment]
> I can't reproduce this either... are you sure it's not a _time_ lag rather than a _distance_ issue?

No time lag, I can keep the mouse there for ever. 

Why I always run into something nobody can reproduce ;-( 
:)

**Comment by junkyardsparkle** [comment]
> Why I always run into something nobody can reproduce ;-(

Well, *somebody* has to be the first one to trigger these things... ;-)
GTK bugs in particular seem to depend on system specifics... can you make this happen anywhere other than filmstrip (normal lighttable thumbs, for instance?).

**Comment by AxelG-DE** [comment]
:)

Actually I have two totally diff machines. Both run kde and both sho the effect on the left end/beginning of the filmstrip (~320pics). The more you go to the right, towards the end, the more the effect disappears.

No such phenomenon in lighttable.

**Comment by AlicVB** [comment]
Ok, I sort of reproduce it, but I've needed to have way larger collections than you to see this "effect" I'll try to find the reason in the code...

**Comment by junkyardsparkle** [comment]
> Edit : to be more specific, I'm able to reproduce if filmstrip is scrolled enough so there's a big blank space on the left of the filmstrip... (the first image of the filmstrip is in the middle of the screen)

Ah, ok, I see it under those conditions too, regardless of collection size.

**Comment by AlicVB** [comment]
@AxelG-DE @junkyardsparkle : can you test PR #3337 please ? it seems to fix this...

**Comment by junkyardsparkle** [comment]
That does seem to eliminate the issue, but I don't know what the reason for adding 'line_width' there was to begin with... I don't use the filmstrip much, and don't really know what it's "supposed to look like". :-)

**Comment by AxelG-DE** [comment]
Thank you guys, I will test this afternoon CET.

**Comment by aurelienpierre** [comment]
> That does seem to eliminate the issue, but I don't know what the reason for adding 'line_width' there was to begin with... I don't use the filmstrip much, and don't really know what it's "supposed to look like". :-)

`line_width` is a margin between thumbnails equal to the width of a line, to avoid the framing on hover to be uneven (with neighbouring thumbnails overlapping it).

**Comment by AxelG-DE** [comment]
I also confirm, it is fixed :-)

@AlicVB thank you very much, again!
