### ISSUE TITLE
Pink overexposed areas with DT2.7/3.0rc0

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#3314]
**Describe the bug**
overexposed parts of image after export to file using linear prophoto RGB are pink, they are white on the screen in dt 
/probably issue with the shipped ProPhoto RGB profile/

**To Reproduce**
1. Export image with overexposed area in the ProPhoto RGB profile shipped with dt

**Expected behavior**
Exported image should match the displayed (where these areas are white)

**Platform (please complete the following information):**
 - OS: Linux and Windows
 - Version 2.7 and 3.0rc0

**Comment by blitzgneisserin** [comment]
can reproduce
![Screenshot at 2019-11-07 12-29-22](https://user-images.githubusercontent.com/16564210/68385530-4ab0b300-015a-11ea-816f-98f84d00a751.png)

**Comment by TurboGit** [comment]
Looks like a bounded vs unbounded issue in profile.

**Comment by TurboGit** [comment]
@phweyland : this seems to be due to the rophoto_primaries_prequantized that you have added into colorspaces.c (not sure). can you double check the pre-quantized values are correct? thanks.

**Comment by TurboGit** [comment]
What about this #3320 ?

**Comment by phweyland** [comment]
> can you double check the pre-quantized values are correct?

I haven't yet found the site where I've picked up this matrix, but the one given [here](https://en.wikipedia.org/wiki/ProPhoto_RGB_color_space)  is aligned.


> What about this #3320 ?

I'm not an expert in color space. I've just copied the recipe from rec2020 for prophoto.
I'm afraid I don't have any valuable opinion on this :(

**Comment by phweyland** [comment]
Doing the same operation (export) with rec2020 seems ok in highlights but is weird in shadows.

I agree, if we export an image with a color profile dt should read it properly with the same color profile. That should work for any profile.

On the other hand if I use prophoto or rec2020 as softproof profile both behave the same way...

**Comment by TurboGit** [comment]
@phweyland : ok, I'll continue my re-implementation of prophoto which seems to give better results to me and fix this issue. I'll see if the other color-spaces can also be redone the same way.

**Comment by TurboGit** [comment]
Please can you test #3320, this final version fix this issue. Hopefully there is no regression. Thanks.

**Comment by Dannny1** [comment]
It seems ok, not pink anymore. Thank you very much.

**Comment by phweyland** [comment]
Looks better to me (at least for prophoto).
1. In dt, original and prophoto jpg are close. OK.
2. I don't see issue with prophoto in lut3d.
3. But imported in dt the rec2020 jpg is has some shadow green artifacts

Original image (crop 100%) - no correction:
![image](https://user-images.githubusercontent.com/23012047/68527914-ee31cd00-02ec-11ea-82e4-2eca9a69ccd9.png)

(I've tried both perceptual and absolute colorimetric profiles with same effect)

Prophoto jpg  absolute colorimetric 
![image](https://user-images.githubusercontent.com/23012047/68527976-95166900-02ed-11ea-97c4-c6f988641002.png)

rec2020 jpg  absolute colorimetric 
![image](https://user-images.githubusercontent.com/23012047/68527924-191c2100-02ed-11ea-96f8-09feb494b57d.png)

rec2020 jpg  with +1.2 exposure
![image](https://user-images.githubusercontent.com/23012047/68528033-2ab1f880-02ee-11ea-91fb-40bedfb55ae2.png)

**Comment by TurboGit** [comment]
>     3\. But imported in dt the rec2020 jpg is has some shadow green artifacts

You mean you see a difference between the current master and with the code in my branch, Right? Can you share the RAW?

**Comment by phweyland** [comment]
> You mean you see a difference between the current master and with the code in my branch

No, with current master and and your branch. Between the original image (in dt) and the exported image (rec2020) jpeg imported again in dt. If everything is going well I should not see any difference, right ?

> Can you share the RAW?
Of course. Could remind me the way to do it.

**Comment by TurboGit** [comment]
Ok, so this is not a regression on my PR, good :)

Now, indeed if you have selected the Rec 2020 as display profile in dt you should see the same image when exporting using Rec 2020. Maybe create a new issue for this.

**Comment by phweyland** [comment]
> Ok, so this is not a regression on my PR, good :)

Correct ! :-)


> indeed if you have selected the Rec 2020 as display profile in dt

No, I have no reason to change the display profile. I just let dt use the embedded profile as input profile. If I switch to rec2020 as input profile the issue is the same (hopefully !)


![image](https://user-images.githubusercontent.com/23012047/68531104-3661e700-030f-11ea-87fa-6143e387cc32.png).
