### ISSUE TITLE
Trashing groups does not work

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#3321]
**Describe the bug**
For all photos I have RAW + JPG. I have turned grouping on to work on the photo abstraction (I want that actions like rating and deletion works on the complete group). When I select lets say 6 photos in the top I can read "12 photos selected". Now I "trash" them and the raw files have been removed but not the JPGs and the text now reads "6 photos selected".

**To Reproduce**
1. Go to lighttable
2. turn grouping on
3. Select some photos that you have JPG and RAW from
4. Check that you can read "12 photos selected" in the top
5. Click on "trash"
6. Check that the RAW files are removed but the JPGs are there, that you can read "6 photos selected", that the selection persists
7. Now "trash" again and observe that the selected files finally have been removed

**Expected behavior**
When grouping is turned on I expect the UI to work on all images that are part of the selection equally. Rating as trashing should behave identically.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version darktable 3.0.0rc0+56~gefb4f9284

**Comment by junkyardsparkle** [comment]
Duplicate of #3154 maybe?

**Comment by codingdave** [comment]
Yes, sounds exactly like the problem I am facing.

junkyardsparkle <notifications@github.com> schrieb am Fr., 8. Nov. 2019,
01:13:

**Comment by codingdave** [comment]
It's a duplicate as mentioned above. Closing it.
