### ISSUE TITLE
After MSYS2 Update CMAKE errors in windows current build

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3323]
**Describe the bug**

-- Configuring done
CMake Error in src/external/rawspeed/CMakeLists.txt:
  Imported target "Pugixml::Pugixml" includes non-existent path

    "F:/msys64/mingw64/include/pugixml-1.9"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in src/external/rawspeed/CMakeLists.txt:
  Imported target "Pugixml::Pugixml" includes non-existent path

    "F:/msys64/mingw64/include/pugixml-1.9"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by chhil** [comment]
The build fails in the end with...

[ 93%] Checking validity of noiseprofiles.json
Traceback (most recent call last):
  File "F:\msys64\mingw64\bin\jsonschema-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by jsonschema
make[2]: *** [data/CMakeFiles/validate_noiseprofiles_json.dir/build.make:59: data/CMakeFiles/validate_noiseprofiles_json] Error 1
make[1]: *** [CMakeFiles/Makefile2:7325: data/CMakeFiles/validate_noiseprofiles_json.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by MStraeten** [comment]
you need to clean your build directory first to remove old build settings. Then let cmake generate new settings

**Comment by chhil** [comment]
Thank you @MStraeten, that fixed it.

**Comment by chhil** [comment]
@MStraeten 
Closed it the ticket to quickly.
The pugixml error was no longer there but eventually the build fails, identical to the initial post.

[ 93%] Checking validity of noiseprofiles.json
Traceback (most recent call last):
  File "F:\msys64\mingw64\bin\jsonschema-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "F:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by jsonschema
make[2]: *** [data/CMakeFiles/validate_noiseprofiles_json.dir/build.make:59: data/CMakeFiles/validate_noiseprofiles_json] Error 1
make[1]: *** [CMakeFiles/Makefile2:7325: data/CMakeFiles/validate_noiseprofiles_json.dir/all] Error 2
make: *** [Makefile:152: all] Error 2



I have an older msys2 , the project builds fine there.

**Comment by agusmba** [comment]
I reported something like this on the [dev-list](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg04823.html) before v3.rc.0 was available.
I switched to the release candidate from github and stopped trying to compile under Win10, but it seems like the same problem reported here.

**Comment by dterrahe** [comment]
I ran into the same problem after the MSYS2 update. Eventually noticed that the log mentions a missing python module, importlib_metadata. I don't know if this was removed during the update or is a new dependency somewhere, but after installing that (and, if i recall correctly, a further one or two dependencies that then showed up in the log) cmake started working again.

**Comment by mbaumgae** [comment]
Installing following packages fixes the build issues on my side:
pacman -S mingw-w64-x86_64-python3-importlib-metadata
pacman -S mingw-w64-x86_64-python3-more-itertools

It seems the update to Python 3.8 coming with recent update, needs these two packages.

**Comment by chhil** [comment]
Thank you @dterrahe  and @mbaumgae . Getting the 2 missing packages got it resolved.

@TurboGit If the install build for windows needs to be updated to include these 2 dependencies then could you please add it. People will run into this issue as they update msys.

**Comment by TurboGit** [comment]
@chhil : Sorry I know next to nothing about Windows. I'll let @peterbud do the right thing.

**Comment by chhil** [comment]
Sounds good to me. Michael Baumgaertner has updated the build doc, someone will eventually need to give the go ahead and merge it.
