### ISSUE TITLE
"Other" drop down menu In tabs top right unreadable

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3326]
**Describe the bug**
Tabs top right lightable|darkroom|other, other is not readable. Casn the font text color be  changed to what the other 2 tabs have?
![image](https://user-images.githubusercontent.com/1119439/68450253-6080af80-0210-11ea-9caf-4c1f631b695c.png)

When mouse over or selected
![image](https://user-images.githubusercontent.com/1119439/68450218-3e872d00-0210-11ea-8a7b-f8361ef62ad6.png)

**Comment by Nilvus** [comment]
@TurboGit : forget to point that one. Fixed by my last PR #3362. So could be closed.

**Comment by TurboGit** [comment]
Ok, closing. Thanks.
