### ISSUE TITLE
Color spaces conversions and tone equalizer broken on MacOS

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3327]
I had the opportunity to test darktable 3.0rc0 on a MacBook last week (don't know the version though) and found out that the Lab <-> RGB colour conversions (used when channel mixer and filmic rgb are enabled with their default position in the pipe) as well as tone equalizer are broken on the CPU path (OpenCL works for the colour conversions, but tone equalizer doesn't have an OpenCL path).

The issue is the output is full black, no matter the settings (just enabling the modules is enough).

Since they all contain my code, there are 2 possible culprits:

* `__DT_CLONE_TARGETS__`, which shouldn't be enabled on Clang since it's defined as follow (in `common/darktable.h`):
```
#if __has_attribute(target_clones) && !defined(_WIN32) && defined(__SSE__)
#define __DT_CLONE_TARGETS__ __attribute__((target_clones("default", "sse2", "sse3", "sse4.1", "sse4.2", "popcnt", "avx", "avx2", "avx512f", "fma4")))
#else
#define __DT_CLONE_TARGETS__
#endif
```
 we know `target_clones` are not supported on GCC Win32 but the source still builds and it's only at runtime that you find out (that's why there is a special check for `defined(_WIN32)`). So it could be that Clang is still trying to enable it at building time but it fails at runtime.
* the vectorized functions and loops optimizations, defined in `iop/filmicrgb.c`, `iop/toneeq.c` and `common/iop_order.c`:
```
#ifdef _OPENMP
#pragma omp declare simd \
  aligned(xyz, rgb, matrix:16) \
  uniform(xyz, rgb, matrix)
#endif
static inline void _ioppr_linear_rgb_matrix_to_xyz(const float rgb[3], float xyz[3],
                                                   const float matrix[9])
{
```
and
```
#ifdef _OPENMP
#pragma omp parallel for simd default(none) \
    dt_omp_firstprivate(stride, image_out, profile_info_from, profile_info_to, ch, matrix_in, matrix_out) \
    schedule(static) aligned(image_out:64) aligned(matrix_in, matrix_out:16)
#endif
    for(size_t y = 0; y < stride; y += ch)
    {
```

I don't have much more details, so it would be nice if more Mac users could check these particular modules (filmic rgb, channel mixer and tone equalizer) on the CPU SIMD and SSE pathes.

**Comment by parafin** [comment]
Works for me.
I assume if clang doesn't support target_clones, then __has_attribute(target_clones) is false and __DT_CLONE_TARGETS__ is defined to empty string. As for OpenMP SIMD - clang complains about some OpenMP pragmas, but I think it only means that code will be slower, not that it will be thrown out.
So yeah, we need a way to reproduce this, I assume you no longer have access to that MacBook.

**Comment by aurelienpierre** [comment]
> I assume you no longer have access to that MacBook.

Indeed.

**Comment by MStraeten** [comment]
i found a set of minimal examples forcing black output, maybe this has the same origin:
it affects the preview in lighttable and the fitted view in darkroom or zoomed out; zooming in is fine as well as the top-left preview.

in addition to the default modules (without sharpen and basecurve)
- enable filmic rgb (mandatory)
- enable color balance (earlier in the pixel pipe)
- enable local contrast - local laplacian filter (later in pixel pipe) other modules later in the pipe are fine, even local contrast using blateral

earlier in the pixel pipe color balance can be replaced by
- rgb levels default settings
- rgb curve - independent channels 
- rgb curve - linked channels depending on the curve (reproducible with gamma 2.0 or contrast high gamma 2.2 preset)
- channel mixer
- high pass
wihout changing the behaviour.

module before colorin doesnt affect the behaviour.

i found also a way to get a black partial area if using a module later than filmic rgb in the pixel pipe having an parametric mask with feathering radius >= 0.2
in this case there's no dependency on the settings of rgb curve - so maybe this is a different issue 

tested with released 3.0 and current master with and without openCl activated:
this is darktable 2.7.0+2729~g8eb0f1b36-dirty
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

**Comment by MStraeten** [comment]
if i force the system to use only device 1: Intel(R) UHD Graphics 630 (`opencl_device_priority=!1,*/!1,*/!1,*/!1,*`) , after a zoom in and zoom back, the fit to screen view is ok, but switching on/of one of the three modules turns it black again
forcing it to use only device 2: AMD Radeon Pro 5500M Compute Engine (`opencl_device_priority=!0,*/!0,*/!0,*/!0,*`) fit to screen remains black in even after zoomin and back

**Comment by MStraeten** [comment]
several further test later: if the fit to screen view is processed with Intel Graphics everything is fine, if done with AMD it's black

**Comment by MStraeten** [comment]
i think, this issue can be closed - i never had this behaviour again after power rgb norm was modified with https://github.com/darktable-org/darktable/pull/3890
so i think, this was the origin of the issue ...
