### ISSUE TITLE
[3.0] Missing icons for many modules (especially new ones)

### ISSUE THREAD

**Issue by darix** [darktable-org/darktable#3329]
$subject

**Comment by Nilvus** [comment]
It's not an issue, it's just that many developers don't create icons for the last modules.

**Comment by Nilvus** [comment]
Oups, written this too fast. I don't use icons but just for curiosity, I just check and indeed it's another problem : even the default icon is not applied. So for those using icons, that make the UI not consistent.

@darix : anyway as I ask you on a previous UI issue you post, more details and a screen capture help. You even don't answer to that previous issue and it didn't help to answer you better and so help improving darktable....

@aurelienpierre : your last two modules are impacted. See here :
![Capture-20191108174719-235x222](https://user-images.githubusercontent.com/45535283/68495120-d6583b80-024f-11ea-9936-0eeed9507ffe.png)

**Comment by TurboGit** [comment]
That should be simple to fix. I'll do that.

**Comment by Nilvus** [comment]
@TurboGit : I'm already on fixing that

**Comment by Nilvus** [comment]
It was indeed simple to fix that, more than I was thinking on start.

**Comment by darix** [comment]
using the default icon for everything is of course a "workaround" but tbh ... then we could just kill the icons. because then it is just wasted space. so while this is the most minimal solution to at least fill the icon space. it is not actually solving the bug.

**Comment by parafin** [comment]
On macOS I see icons only in more modules widget. Is it configurable? I don't see such option in preferences.

**Comment by TurboGit** [comment]
The icons are visible only if you select one of the icons based theme.

**Comment by TurboGit** [comment]
@darix: I agree, but designing icons are not something easy and needs some specific skill. Just waiting for the community loving icons to come with proposal.

**Comment by parafin** [comment]
Ah, then I guess user can decide for himself if it's a waste of space or not.

**Comment by darix** [comment]
@parafin  you need to switch to a -icon theme in the preferences.
