### ISSUE TITLE
old filmic iop is still displayed

### ISSUE THREAD

**Issue by parafin** [darktable-org/darktable#3330]
When updating from 2.6 installation to 3.0 if filmic was enabled in more modules, then it will be still displayed in the iop list for new images, so it's possible to use it (and get that warning sign in the history for newly developed images). And it's not listed in more modules, so it's not possible to remove it either.

**Comment by chhil** [comment]
It does make sense. If you have edited a pic with deprecated filmic it should show up when one upgrades but won't show up for new edits. History shows the module with the deprecated icon.

**Comment by parafin** [comment]
It does show up for new edits, that's my point.

**Comment by chhil** [comment]
Last when I tested it, it didn't , something changed. I haven't seen the module in new imports that's for sure.

**Comment by parafin** [comment]
It means you had it disabled in darktable config when you updated to 3.0. Change plugins/darkroom/filmic/visible to TRUE in ~/.config/darktable/darktablerc and it will become visible for you too. This options isn't changed when upgrading versions.

**Comment by Nilvus** [comment]
It didn't show up for me on new edits. I only have filmic displayed on new images when I was using a preset to automatically applied it on new images. After removing that preset, no more filmic displayed on new images.

**Comment by aurelienpierre** [comment]
Don't reproduce either on new edits with `plugins/darkroom/filmic/visible=TRUE`

**Comment by parafin** [comment]
Where did you look? It's there if you unselect all groups (so that all iops are visible).

**Comment by aurelienpierre** [comment]
ah, if you unselect all groups, indeed, but it's not specific to filmic. I'm not sure if it's a bug or a feature though, it can be useful to still have a semi-hidden access to deprecated modules.

**Comment by parafin** [comment]
The problem is that you can remove other iops by toggling them in more modules, but not deprecated ones (e.g. filmic) - you will be stuck with it (unless you edit config file by hand).

**Comment by parafin** [comment]
Also it's inconsistent, that some users will be able to use filmic on new pictures, but not others, depending on what they had in the config file when they update to 3.0.

**Comment by jenshannoschwalm** [comment]
Isn't this the relevant test 

https://github.com/darktable-org/darktable/blob/4c6df92a066856af0fb854fa727f267112dbac0a/src/libs/modulegroups.c#L440-#L445

What's wrong with it? Are some of the modules flags changed by the `plugins/darkroom/filmic/visible=TRUE`

**Comment by aurelienpierre** [comment]
Working on that.

**Comment by aurelienpierre** [comment]
So I tried to sync `src/libs/modulelist.c` with `src/libs/modulegroups.c`, and it turned out to be much worse than I expected.

`modulegroups.c` get the modules list from `darktable.develop->iop` and cast them as `dt_iop_module_t`.

`modulelist.c` get the modules list from `darktable.iop` and cast them as `dt_iop_module_so_t`.

The `dt_iop_module_so_t` structure is nested in the `dt_iop_module_t` in its `(dt_iop_module_t *)->so` member. Only the  `dt_iop_module_so_t` contains the `state` member which is a boolean flag indicating if the module is displayed, favourite or hidden.

Then I tried to make `modulelist.c` fetch modules from `darktable.develop->iop`  too, cast them as `dt_iop_module_t` and use the `(dt_iop_module_t *)module->so` member in place of all old `(dt_iop_module_so_t *)module`. That makes the presets fail for some reason.

Then, I tried, as in `modulelist.c`, to still display the deprecated modules if they are enabled. But it seems that `modulelist.c` widget is initialized before the pipe, and the only modules having `module->enabled` set to `TRUE` are the always-enabled ones.

So, I don't know… Should we just display all the modules, deprecated or not ? Or try to rewrite the thing around that ?

**Comment by aurelienpierre** [comment]
Connecting to:
```
dt_control_signal_connect(darktable.signals, DT_SIGNAL_DEVELOP_UI_PIPE_FINISHED,
                            G_CALLBACK(_lib_modulelist_populate_callback), self);
```
seems to make at least the enabled detection work. But looking at `signal.h`, we see:

```
  /** \brief This signal is raised when darktable.develop is initialized.
      \note any modules that wants to access darktable->develop should connect
      to this signal to be sure darktable.develop is initialized.
  no param, no returned value
   */
  DT_SIGNAL_DEVELOP_INITIALIZE,
```

Thus, if only part of the modules are initialized in the pipe when the signal is raised, it might be another weird mutex thread lock error.

**Comment by aurelienpierre** [comment]
pinging @AlicVB here for advice

**Comment by AlicVB** [comment]
not sure I can give advice here, as I've never touch this part of the code...
Anyway I've tried some things, and first basic question which comes in my mind is what differs in code when we have a group select or not

**Comment by AlicVB** [comment]
oh wait, I think I got it, can you try PR #3509 ?
If it doesn't produce other problems, it was "just" a matter of properly update iop list when entering darkroom (this is what is done if a group is selected)

**Comment by AlicVB** [comment]
So, let's reopen and continue the discussion here, as it seems the mentioned commit only fix part of the issue.
For reference, I'm quoting relevant part of discussion from PR #3509
@aurelienpierre : 
> ... the issue is deprecated modules don't appear in the "more modules" panel, even when enabled in current image. So if users hide filmic in 2.6 but have it enabled one some pictures, they will never be able to show it again in UI.

@parafin : 
> I think all enabled modules are shown in active modules list, even if disabled in more modules. They won’t be listed in groups though. If I’m right, then I don’t think that it’s actually an issue.

So, if I understand well, we need to ensure that enabled modules are always shown in the list, whatever his deprecated state. That clearly make sens. I'll try to make a PR with that asap.
For the more module part, I really think that deprecated modules shouldn't appear there... but I'm not sure to understand @aurelienpierre idea here, so correct me if I'm wrong !

**Comment by AlicVB** [comment]
I've just re-tested, and it's already the case here : filmic appears in modules list (activated group and tone group) if it's enabled in the current image...
I propose to let you decide whether the bug is still valid or not...

**Comment by parafin** [comment]
I’m not sure why you re-opened it then…

**Comment by parafin** [comment]
I guess this is fixed.
