### ISSUE TITLE
Problem with displaying zoom indicator on Windows

### ISSUE THREAD

**Issue by mlales** [darktable-org/darktable#3341]
Zoom value has 2 digits: OK

![Zoom 1](https://user-images.githubusercontent.com/56188259/68524423-fecf4c80-02c6-11ea-8cff-df89f7d451dc.JPG)

Zoom value has 3 digits: value overlaps image

![Zoom 2](https://user-images.githubusercontent.com/56188259/68524427-07278780-02c7-11ea-9de0-3bfda0272336.JPG)

Zoom value has max (1600% value): only 1600 is displayed, without % symbol

![Zoom 3](https://user-images.githubusercontent.com/56188259/68524435-20c8cf00-02c7-11ea-848e-a009ed86aef2.JPG)

It seems not enough space for max length of string.

**Describe the solution you'd like**
More space for properly displaying zoom values. 

Version: 3.0.rc0
OS: Windows 10

**Comment by Nilvus** [comment]
I don't have this issue but it could be a Windows issue. As some things have been fixed on recent commits, could you close this issue if fixed or confirm by replying that this issue is always here for you ?
As this doesn't appear one my system, if this issue remaining, that probably would mean it's a Windows one.

**Comment by mlales** [comment]
I prepared a Windows build today from last merged commit ( 8a52195) but the issue is still here.

**Comment by Nilvus** [comment]
So you have to wait that a developer (we have only one or two developers for Windows) see that for Windows as this issue doesn't exist on Linux. I suggest you to add "on Windows" to the issue title.

**Comment by Nilvus** [comment]
Just a precision, I only have % symbol disappear when using a 4 digit zoom number (like your last screen but no overdisplay).

Last thing : which side width you use for panels (setting on first tab in preferences) ?

**Comment by mlales** [comment]
Side width for panels is 350 (default). Increasing to 355 and 360 doesn't help.

Thank you for your assistance !

**Comment by junkyardsparkle** [comment]
It's not a Windows issue, I can reproduce on Linux. It seems trivial, though... do people really zoom to >999% for any reasonable purpose?

**Comment by Nilvus** [comment]
> It's not a Windows issue, I can reproduce on Linux. It seems trivial, though... do people really zoom to >999% for any reasonable purpose?

I can’t reproduce overlay issue on Linux. I only have % symbol disappear when on 4 digit zoom.
Anyway, I agree that >999% zoom is not useful.

**Comment by junkyardsparkle** [comment]
The (very slight) overlay issue only happens for me at aspect ratios wider than 3:2, but this might also depend on sidebar width settings.
