### ISSUE TITLE
Unreadable text on some controls where hovering over with mouse

### ISSUE THREAD

**Issue by mlales** [darktable-org/darktable#3343]
Some controls (buttons, drop down menus) become unreadable
(white text on light grey background) when hovering with mouse over them:

![Hovering 1](https://user-images.githubusercontent.com/56188259/68524678-f0cefb00-02c9-11ea-9328-98693f3bd3b3.JPG)

![Hovering 2a](https://user-images.githubusercontent.com/56188259/68524688-06442500-02ca-11ea-9404-5fe52c5606e9.jpg)

![Hovering 3a](https://user-images.githubusercontent.com/56188259/68524689-0e03c980-02ca-11ea-9fb3-a32366ac3c88.jpg)

![Hovering 4a](https://user-images.githubusercontent.com/56188259/68524692-165c0480-02ca-11ea-97cb-89e943f3c96c.jpg)

![Hovering 5a](https://user-images.githubusercontent.com/56188259/68524696-1f4cd600-02ca-11ea-8f9d-5feb21bf75c5.jpg)

Text should change color to something more dark, like this:

![Hovering 6a](https://user-images.githubusercontent.com/56188259/68524701-283da780-02ca-11ea-9bba-4de5cace81a0.jpg)

or as implemented in  lighttable | darkroom | other   tabs.

Version: 3.0.rc0
OS: Windows 10

**Comment by aurelienpierre** [comment]
Yep, the font colour on hover is supposed to change, but for some reason that CSS rule is not honoured, and I have been looking for the solution for 6 months, but I see no way around that.

**Comment by Nilvus** [comment]
@mlales and @aurelienpierre : Thanks to @roussieau and his #3356 try, I found a way to fix correctly buttons hover. I will now search fixing menuitems hovering and propose a PR after that. I hope to fix that this day.
