### ISSUE TITLE
OSX: uncaught NSRangeException --> Segfault in lighttable on accessing preferences

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3345]
**Describe the bug**
in lighttable in several gui scenarios (accessing preferences, click on export, expand styles etc.) darktable terminates with  

```
2019-11-09 09:25:25.025 darktable[31374:1304618] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 34 beyond bounds [0 .. 33]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff35067acd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5f769a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff350a6ac4 -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
	3   CoreFoundation                      0x00007fff34fbf6c9 -[__NSSingleObjectSetI member:] + 0
	4   libpangocairo-1.0.0.dylib           0x0000000102108029 pango_core_text_fontset_get_font_at + 61
	5   libpangocairo-1.0.0.dylib           0x0000000102107fc2 pango_core_text_fontset_foreach + 42
	6   libpango-1.0.0.dylib                0x00000001021297ac get_shaper_and_font + 208
	7   libpango-1.0.0.dylib                0x0000000102128a1d itemize_state_process_run + 955
	8   libpango-1.0.0.dylib                0x00000001021282de pango_itemize_with_base_dir + 113
	9   libpango-1.0.0.dylib                0x000000010212db3a pango_layout_check_lines + 629
	10  libpango-1.0.0.dylib                0x0000000102131474 pango_layout_get_extents_internal + 44
	11  libgtk-3.0.dylib                    0x0000000101aec2af gtk_label_measure + 332
	12  libgtk-3.0.dylib                    0x0000000101a4bef1 gtk_css_custom_gadget_get_preferred_size + 30
	13  libgtk-3.0.dylib                    0x0000000101a4f131 gtk_css_gadget_get_preferred_size + 681
	14  libgtk-3.0.dylib                    0x0000000101aea4a5 gtk_label_get_preferred_width + 48
	15  libgtk-3.0.dylib                    0x0000000101b8523b gtk_widget_query_size_for_orientation + 563
	16  libgtk-3.0.dylib                    0x0000000101b84866 gtk_widget_compute_size_for_orientation + 92
	17  libgtk-3.0.dylib                    0x0000000101b847c4 gtk_widget_get_preferred_width + 97
	18  libgtk-3.0.dylib                    0x0000000101a0364e gtk_box_get_content_size + 516
	19  libgtk-3.0.dylib                    0x0000000101a4bef1 gtk_css_custom_gadget_get_preferred_size + 30
	20  libgtk-3.0.dylib                    0x0000000101a4f131 gtk_css_gadget_get_preferred_size + 681
	21  libgtk-3.0.dylib                    0x0000000101a02e35 gtk_box_get_preferred_width + 48
	22  libgtk-3.0.dylib                    0x0000000101b8523b gtk_widget_query_size_for_orientation + 563
	23  libgtk-3.0.dylib                    0x0000000101b84866 gtk_widget_compute_size_for_orientation + 92
	24  libgtk-3.0.dylib                    0x0000000101b847c4 gtk_widget_get_preferred_width + 97
	25  libgtk-3.0.dylib                    0x0000000101c368d7 gtk_window_get_preferred_width + 279
	26  libgtk-3.0.dylib                    0x0000000101b8523b gtk_widget_query_size_for_orientation + 563
	27  libgtk-3.0.dylib                    0x0000000101b84866 gtk_widget_compute_size_for_orientation + 92
	28  libgtk-3.0.dylib                    0x0000000101b847c4 gtk_widget_get_preferred_width + 97
	29  libgtk-3.0.dylib                    0x0000000101b84d77 _gtk_widget_get_preferred_size_and_baseline + 216
	30  libgtk-3.0.dylib                    0x0000000101c2e153 gtk_window_compute_configure_request + 135
	31  libgtk-3.0.dylib                    0x0000000101c358ca gtk_window_realize + 573
	32  libgobject-2.0.0.dylib              0x00000001024632a1 _g_closure_invoke_va + 208
	33  libgobject-2.0.0.dylib              0x0000000102476d20 g_signal_emit_valist + 1125
	34  libgobject-2.0.0.dylib              0x00000001024776a8 g_signal_emit + 120
	35  libgtk-3.0.dylib                    0x0000000101c19117 gtk_widget_realize + 279
	36  libgtk-3.0.dylib                    0x0000000101bdfda1 gtk_tooltip_show_tooltip + 426
	37  libgtk-3.0.dylib                    0x0000000101be05e6 tooltip_popup_timeout + 44
	38  libgdk-3.0.dylib                    0x0000000102061a5d gdk_threads_dispatch + 50
	39  libglib-2.0.0.dylib                 0x0000000101895ea8 g_timeout_dispatch + 20
	40  libglib-2.0.0.dylib                 0x00000001018989ad g_main_context_dispatch + 258
	41  libglib-2.0.0.dylib                 0x0000000101898ca8 g_main_context_iterate + 426
	42  libglib-2.0.0.dylib                 0x0000000101898ede g_main_loop_run + 191
	43  libgtk-3.0.dylib                    0x0000000101afd055 gtk_main + 74
	44  libdarktable.dylib                  0x0000000101589883 dt_gui_gtk_run + 195
	45  darktable                           0x0000000101422f4e main + 62
	46  libdyld.dylib                       0x00007fff60f383d5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

**To Reproduce**
1. Select multiple images in lighttable 
2. open preferences dialog (this seems to be reproducible on every access)

**Platform (please complete the following information):**
 - OS: OSX
 - Version darktable-2.7.0+2247~gcc15f8d93

**Additional context**
My build darktable-2.7.0+2197~gcb0aaf0c1 seems to be ok - maybe the latest gui stuff introduced the error

**Comment by MStraeten** [comment]
seems to be introduced with commit a6a6c7a35980165ac75777fcf05ee4e58725b6ad
PR #3068

**Comment by parafin** [comment]
This looks like a GTK bug.

**Comment by MStraeten** [comment]
seems to be an css issue: if "darktable" theme is used, the crash is not reproducible

**Comment by MStraeten** [comment]
setting ui_last/theme=darktable allows opening preferences, but on switching to a darktable_elegant setting the crash occurs

**Comment by parafin** [comment]
Do you have the needed font installed? Are there any warnings printed if you start darktable from terminal?

**Comment by MStraeten** [comment]
fonts are installed Roboto as well as SF; i dont get font warnings:
start with elegant-darker:
```
(process:49073): GLib-GObject-CRITICAL **: 12:00:29.209: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(darktable:49073): GLib-GObject-WARNING **: 12:00:29.472: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(darktable:49073): Gtk-CRITICAL **: 12:00:29.472: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
```
start with darktable:
```
(process:49089): GLib-GObject-CRITICAL **: 12:02:03.170: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(darktable:49089): GLib-GObject-WARNING **: 12:02:03.431: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(darktable:49089): Gtk-CRITICAL **: 12:02:03.431: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
```
i found only one additional font aside sans-serif (wheater Roboto or SF) is ok (both fonts are available on my system

**Comment by MStraeten** [comment]
quite strange: if i reduce darktable-elegant-darker to Roboto + sans serif in the css file and start darktable with ui theme darktable, i'm able to access preferences, select the darktable_elegant-darker theme as well as the non edites further themes

**Comment by parafin** [comment]
I tested with no additional fonts installed and it works fine (tested on Catalina). So I'm guessing it's some incompatibility between these custom fonts, GTK/Pango/Cairo on macOS and darktable's theming (CSS and C code).
I don't know what I can do here, but maybe you and @aurelienpierre can figure something out.

**Comment by aurelienpierre** [comment]
CSS rules that produce segfaults ??? Wow, that's a first. 

I don't know what to do here. Maybe report upstream to GTK team ?

**Comment by MStraeten** [comment]
latest check: if i remove just SF lines then it's fine, if i just remove Roboto lines it's fine too.
The issue occurs if Roboto **and** SF are in the css-file

**Comment by aurelienpierre** [comment]
So it's definitely an issue with GTK : it should stop at the first found font-family in the list. Well, at least that's what CSS2 and 3 do…

**Comment by homer3018** [comment]
For what it's worth, I was very recently about 1000 commits behind master (around 2.7.0 days), with roboto fonts installed manually, and everything was running ok. Now I'm seeing weird characters in some places, and I had to limit darktable-elegant-darker to just Roboto so I'm able to at least swap themes, otherwise I get the crash mentioned by the OP.
I remember seeing weird character as well when I first got to 2.7.0 from 2.6.2, but I hadn't installed Roboto at the time. All of it was gone after doing so.
Nothing changed in my installed fonts, only the os got updated. I can't tell whether this is GTK or something else however.

**Comment by homer3018** [comment]
Would it be possible to know for sure which font is being used ? I'm trying to think of a way for us to get certain (or not) that GTK is to blame here, so we can at least move forward with this.
Would `GTK_DEBUG=interactive` provide the information ?
Since I've installed Roboto manually on my system, I was not expecting it to go wrong this time, or not as wrong compared to when we went from no CSS to CSS... But somehow even if all the font family are there and readily available, I'm not 100% convinced that there are being used, or maybe no for everything. Otherwise I'd think I'd not see symbols like above with a modified CSS containing only the Roboto font family.

**Comment by MStraeten** [comment]
> I tested with no additional fonts installed and it works fine (tested on Catalina). ...
Yep, thats correct. On a new macbook without additional fonts installed, the issue is not reproducible. Maybe because Apples is hiding the San Francisco Font - it's just not accessible from applications.
If the San Francisco Fonts are separately installed to make them accessible for further applications the error occurs.
So in my opinion the SF Pro... lines in darktable-elegant-darker.css are useless - if the font is not installed in addition to the system font installation or causes an error. So in my opinion the best most universal solution ist to remove these from the css file.

**Comment by homer3018** [comment]
I have only Roboto installed, and it crashes as described unless I remove all the other fonts other than roboto in the css.

**Comment by MStraeten** [comment]
not yet solved ...

**Comment by johnny-bit** [comment]
@MStraeten - How about now? :) This looks totally like an "upstream" problem though with GTK & Mac not playing nice with fonts :/

**Comment by MStraeten** [comment]
no longer reproducible (at least on BigSur)
