### ISSUE TITLE
Fillight problem picked target grey value (thin line) vanishes when pulling ruler

### ISSUE THREAD

**Issue by rainer042** [darktable-org/darktable#3346]
**Describe the bug**
In 3.0.0rc0 when you use the color picker in fill light to select a gray value around which light should be filled up you see a thin line representing the picked grey "target" value. However when you select the triangle ruler and drag it towards the target grey value (thin line) this thin line disappears immediately. So its now harder to select the desired grey value where you wanted to go to.

**To Reproduce**
1. Use color picker in fill light module in V3.0.0.rc0.  Now drag the triangular shaped ruler towards the thin line representing the picked grey value.
2. The thin line showing you target will dissappear immedeately.

**Expected behavior**
The thin target value line that appears when you selected a grey value from your photo using  the color picker should remain visible in order to be able adjust the grey center to exactly this value.

**Platform (please complete the following information):**
 - OS: openSuSE Leap 15.1
 - Version 15.1

**Comment by TurboGit** [comment]
Should be fixed in master now. Thanks.
