### ISSUE TITLE
Photos added/removed  to the DTs current folder are not recognized by DT upon startup

### ISSUE THREAD

**Issue by rainer042** [darktable-org/darktable#3347]
**Describe the bug**
I organize my photos in folders like "year/photolocation/subject/..." . This way it often happens that I have to add new photos to a folder that contains already photos where I recently worked on. So the new photos go into the same directory where the older ones already are. When I was in exactly this folder when running darktable the last time, it will open this folder again upon the next start  however it will then not show the added photos. 
To see the new photos in the light table view I first have to click on "folders" which shows me a file selector with the contents of the current directory which is exactly the one I added photos before start. All I have to do then is to click "Open" and then the new photos are shown. For deleted photos darktables reaction is more weird because it keeps on showing the deleted photos but of course there is an error when I try to open on of them  because its no longer there. So here manually cleaning up the database is needed, a job darktable could do much better on its own.

The problem seems to be that DT does not adjust its database to the existing files in the directory being opened upon startup and the possible new files inside. This adjustment happens not before I open the directory again I am already in (in case of added photos).  

**To Reproduce**
1. In darktable V3.0.0rc0 or V2.x open a folder with photos in it. 
2. Terminate darktable
3. copy some new photos eg from your camera into this folder
4. start darktable
5. the copied photos will not be visible
6. click on "folders" and without any change on "open" et voila the photos are visible

**Expected behavior**
Since photos could be added or removed during the time darktable does not run then upon startup of darktable in its  current directory the new photos therein should be scanned and added/be dropped to/from its database and be displayed/removed from display. In other words when darktable starts it should adjust its database to the files it finds in the current directory.

**Platform (please complete the following information):**
 - OS: Linux, openSuSE Leap 15.1
 - Version Leap 15.1

**Comment by parafin** [comment]
Not a bug, but a designed feature. You have to re-import the directory to add new photos. And you have to remove images if you deleted them (or better yet delete them from darktable itself). Read the manual.

**Comment by rainer042** [comment]
Thanks for your answer.  Interesting that this behaviour should be desired? After all it makes managing albums (folders) more complicated than necessary. For me its "extra" work without any benefit that could be saved from the user. I know how to get around this and I already thought about writing a script to be called upon startup instead of darktable that does the cleaning up of the database for its current folder and then calls darktable. Should be quite easy.

But I think the best way would be if a solution inside darktable could be found. I also read the manual but the manual does not explain *why* the current behavior is considered desired? 

I would really like to know why the current behaviour has been selected instead of another approach? So can you please explain to me why a mandatory manual reimport of darktables current (changed) disk folder is better than an automatic rescan/reimport of the current folder upon startup?

**Comment by parafin** [comment]
Some people store images on external drives, which might not be present at each darktable execution. So removing missing images doesn't fit all use-cases. Importing newly added images makes more sense, but it may result in darktable doing some work (importing consumes resources) on startup which user doesn't expect/want. So again, there are a lot of use-cases, not just yours. If you don't want to use database concept you can just pass --library :memory: option to it and import the directories as you need them each time.
I'm not sure what do you expect here, total re-design of darktable architecture? Consider it historical if you'd like.

**Comment by spaceChRiS** [comment]
There are more workflows that rely on this separation. To add an example, the import dialog offers some options how to deal with imported images, which might be different for different folders. Without separation of folder and film roll these feature would not be possible.

**Comment by rainer042** [comment]
A little longer answer for motivating what I am asking for. If you are already motivated :-) you can just read the last part starting with "My idea is to:"

Thank you very much for your explanations of the problem. Now I can understand why the current photo management solution has been chosen and of course no one wants or could redesign the complete darktable architecture from scratch. Nevertheless I think that this situation is not as optimal as it could be. Especially for people that used a different raw developer and now change to darktable are fighting with in their eyes strange problems related to album/photo management (so was I). I started a year ago to
use darktable and had this experience as described. Before this time I worked with digikam and AfterShot and also tried Raw Therapee. These and many other Photo applications are transparent in regards to photo file management. Thats also why I think that I am not the only darktable user who would like for things to improve.  (Externally) removing or adding photos in those apps is possible without the effects that such an action has in darktable. The user is acquainted  with  being able to add or remove photos using the application or a filemanager or a cp/rm to to the photo-directory and also would like to see the changes right away and thus wonders why this is different in darktable and how to solve it.
Don't get me wrong I myself work with darktable because I like its very powerful modules, its much more powerful than all other available raw developers available for my platform which is linux.
But optimizing photo management would make a new user instantly feel more "home", the learning curve would be less steep and daily work afterwards always a bit more easy.  Thats why I think its important to think about how things could be improved in regards to the problems I depicted initially.

That said I also started thinking how this could be done. The problem arises because darktable never knows if a filmroll-path that eg seems to be empty is on a currently unplugged removable device or if the removable device is plugged in and the filmroll itself is really empty. My idea to solve this problem without big changes rests in the owner of the system, the user because he knows which path on his system is on a local disk and which paths are on one of his removable devices. 

My idea is to:

1. Offer a new Option say "Local_Filmroll_Path"  (which can be empty) where the user can define the path to a photo-root directory on his system that is on a *local* disk not on a removable one, e.g. /home/user/Pictures/. 

2. When darktable is closed with a film roll opened that is beneath Local_Filmroll_Path (eg /home/user/Pictures/Irland/Landscapes/), then  upon restart darktable knows that this filmroll is on a local path and thus new photos could be automatically re-imported and externally deleted photos could be safely deleted from the database. The result would be a transparent and correct view on the files in the filmroll-directory on a local disk.

This would not change anything to the import process, which has to be done once for each filmroll as usual allowing the use of all the options available for this. It would also not put any load on the system since one path check on startup is cheap and it should not be hard to implement. At last it would not change anything regarding the management of filmrolls on removable devices. If this new option is left empty nothing would change at all.

Just an idea but I (and as other requests I found searching for this topic indicate probably other users as well) hope this idea or a better one will make it in a future darktable version. This would be great.

**Comment by parafin** [comment]
1. Why is this logic limited only to the currently open filmroll? I assume because of performance concerns? Please note, that collect module can display for example all photos in the collection, not one specific filmroll, what should be done in this case? What happens when user changes current filmroll after starting darktable, should it be re-scanned too? You don't mention it.

2. There are already scripts that remove non-existing images (https://github.com/darktable-org/darktable/blob/master/tools/purge_non_existing_images.sh) and import images as soon as they appear in the folder (https://github.com/darktable-org/darktable/blob/master/tools/watch_folder.sh). So mostly, I think, what you have in mind can be achieved without adding any functionality to darktable itself. It's just a question of re-factoring those two scripts in some wrapper start script for darktable. IMHO that's definitely something that can be expected from the community, without asking core developers to implement it.

**Comment by rainer042** [comment]
regarding 1) The logic behind the "limited to current filmroll" was to create a lean  solution
that should not cause much work for the developers and is fast. It can of course not solve the whole problem. So your hint to go beyond film rolls to collections is good. 

Think you created a collection to show all photos e.g. taken with  F22. You terminate darktable and then take your external filemanager and copy some fresh photos from the camera into an existing filmroll. Suppose some of the new photos were taken with F22. Now you start darktable again and look again your collection. 

In the current implementation the new photos that do comply to you collection criteria
would nevertheless not be shown since they were not automatically imported to the database and thus cannot be found.

Since darktable cannot not know to which local filmroll the new files were copied what you need to do in this case is to search all local filmrolls for changes. This is by thew way the method digikam has chosen to solve the same problem: Gather up to date information in your database about all photos you manage. Digikam does this scan in the background, so you can start working  even if the database update has not yet terminated. A similar method could also be applied to darktable. With no new files the background scan takes about 3sec for about 20000 photos in my library. 

So the idea for this extended scenario would be:

1. (Same as before:) Offer a new Option say "Local_Filmroll_Path" (which can be empty) where the user can define the path to a photo-root directory on his system that is on a local disk not on a removable one, e.g. /home/user/Pictures/

2. Upon startup scan all filmrolls below Local_Filmroll_Path for changes (added/removed photos) and if a change is found reimport this filmroll.

With this concept the new photos from above would appear after the new start of darktable in your collection, as soon as the automatic scan would have finished. 

regarding 2) Darktable is a raw editor as well as a photo manager so aside of its great raw development functionality it offers grouping, deletion, moving, displaying and tagging photos and more as well as search for particular properties of photos (catalogs). 

Because of this I would say that keeping track of all photos by automatically updating its database to "know" what photos it currently has to manage is a core functionality of a photo manager. Else things like not found photos taken with F22 from above can and will happen. So this part should in my eyes not be performed by external scripts but by darktable itself. 
A solution via script is kind of a last resort and shows that people are missing this functionality in darktable (so do I). But scripts cannot integrate this functionality as good as if it was a core part of darktable.
