### ISSUE TITLE
Basecurve legacy history stack not properly converted

### ISSUE THREAD

**Issue by upegelow** [darktable-org/darktable#3354]
**Describe the bug**
Legacy history stacks (dt 2.6.x) with basecurve and exposure fusion activated are not properly converted to dt 3.0. The exposure bias parameter gets always set to zero.

**To Reproduce**
1. In darktable 2.6.3 edit image, activate exposure fusion in basecurve and set exposure bias to a non-zero value
2. Launch darktable 3.0.rc0 (which leads to history stack being converted)
3. Inspect basecurve module and observe difference in image vs. 2.6.x
4. Exposure bias parameter is set to zero, regardless of the original value

**Expected behavior**
Exposure bias setting needs to be preserved. darktable must guarantee compatibility of legacy history stacks.

**Platform (please complete the following information):**
 - OS: Linux (OpenSuse 15.1)
 - Version: 3.0.rc0

**Additional context**
See example xmp file generated by 2.6.3 with exposure bias set to 0.5.
[example2.xmp.gz](https://github.com/darktable-org/darktable/files/3827713/example2.xmp.gz)

**Comment by upegelow** [comment]
Looks like the bug is here:

[https://github.com/darktable-org/darktable/blob/56bf781bbbb2f9e6ffb1fce0311282ebb3faba77/src/iop/basecurve.c#L171](url)

It should read `dt_iop_basecurve_params5_t` instead of `dt_iop_basecurve_params4_t`

**Comment by TurboGit** [comment]
Good catch! I'll have a look.

**Comment by TurboGit** [comment]
Thanks, that's fixed now. It was trivial after you pointed out the wrong code.

**Comment by upegelow** [comment]
Thanks for fixing.

BTW I am a little bit concerned about the coding style in that place. To my knowledge the C standard does not guarantee the memory layout of a struct. The compiler might add padding bytes for example and these might differ depending on the structure. Filling the new struct partially by a memcpy from the previous one is therefore a bit doubtful. Practically it will probably work in any current compiler setup.However, if an issue would occur at some point in time it would be extremely difficult to track down.

**Comment by parafin** [comment]
Looks fine to me. Adding struct members at the end can't change the layout of previous members. What is more concerning is that this struct is serialized to xmp file, so it really should be using only sized types (e.g. int32_t) and probably disable struct padding. This is though a general problem, I think not limited to this iop. In general, int and short types are fine (they seem to be the same size on every relevant platform, and aligned the same in the struct). long and double would be problematic on the other hand (long has different sizes in Linux and Windows, and double is aligned differently, depending on whether the system is 32-bit or 64-bit).
