### ISSUE TITLE
Preloading images in darktable 3.0.0RC

### ISSUE THREAD

**Issue by borissmidt** [darktable-org/darktable#3355]
Hello darktable developers,

When i apply a heavier calculation on a full set of images, like for example lens correction.
Then it takes a long time before all the images in the set are calulated.

There are two things which i have noticed. If i first zoom out it will precalculate all the images in view and if i zoom in again then all previews will be quick to be seen.

If however i want to see a full size preview by pressing ctrl-w. Then all the other previews are thrown away and i have to zoom out again. update: it stopped throwing away the previews once the set became smallr.

Maybe it could help to keep the previews even when ctrl-w is pressed and precalculate an amount of preview. So i don't have to do the zoom out trick.

Please tell me if this ticket is specific enough, I'm a programmer myself so i understand that a ticket needs to be very detailed. 

I have a 4k screen so that might also be a cause of the issue that al images are rendered till it hits the required resolution. (i noticed that darktable became slower compared to when i used a HD monitor)

Kind regards, Boris Smidt

**Comment by AlicVB** [comment]
If I understand what you say, it seems that you need to increase your cache memory values in the prefs... (in your title, you mean lighttable, not darkroom, right ?)

**Comment by borissmidt** [comment]
Yes, Thank you for the fast response i will try that :). (i have enough ram anyway)

**Comment by borissmidt** [comment]
It works!!! great i also increased the number of threads which increased the efficiency of the preloading. Thank you very much. I will close this ticket.
I think it was reset when i upgraded to the 3.0.0 version. Hence the feeling there was a 'regression'
