### ISSUE TITLE
What exactly happens when you say yes or no to uninstall DT when installing a new version...either option seems to perform and install??

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#3357]
https://discuss.pixls.us/t/upgrading-darktable/10721

Following up on this esp with the move to 3.0 it might be nice to clarify the consequences of saying yes or no wrt to Windows install options.....

**Comment by MStraeten** [comment]
Since this seems to be a windows installer specific behaviour, why not just try it and then describe the behaviour yourself? 
In both cases the old version becomes unusable since the library will be updated and not usable with the old version. So it doesnt make sense to keep the old version.
