### ISSUE TITLE
SQL error in src/common/collection.c when collecting by history altered

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#3358]
**Describe the bug**
Open a collection of images.  Go to collect images, select narrow down search, then choose history from the drop down.  Double click on altered.  No images are displayed and the following errors are displayed in the console:

sqlite3 error: /home/bill/src/darktable/darktable/src/common/collection.c:834, function dt_collection_get(), query "SELECT id FROM main.selected_images AS s JOIN (SELECT DISTINCT mi.id FROM (SELECT * FROM main.images WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/bill/Pictures/darktable30/20191026-Football.Varsity.Warren.Reserve.vs.Linsly')) AND (id  IN (SELECT imgid FROM main.history WHERE imgid=mi.id)) )) AS mi LEFT OUTER JOIN main.color_labels AS b ON mi.id = b.imgid ORDER BY datetime_taken, color DESC, filename, version LIMIT ?1, ?2) AS mi WHERE mi.id = s.imgid LIMIT -1, ?3": no such column: mi.id
sqlite3 error: /home/bill/src/darktable/darktable/src/common/collection.c:840, function dt_collection_get(): no such column: mi.id
sqlite3 error: /home/bill/src/darktable/darktable/src/common/collection.c:841, function dt_collection_get(): no such column: mi.id
sqlite3 error: /home/bill/src/darktable/darktable/src/common/collection.c:845, function dt_collection_get(): no such column: mi.id

This sounds like a recurrence of #2207 

**To Reproduce**
1. Open a collection of images.  
2, Go to collect images, select narrow down search. 
3. Choose history from the drop down.  
4. Double click on altered.  
5. No images are displayed

**Expected behavior**
A list of altered images

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version  3.0.0rc0+82~g4c6df92a0

**Comment by TurboGit** [comment]
I cannot reproduce! Is there more context for this to reproduce?

**Comment by TurboGit** [comment]
Ok, found, this happens only when the lt filter is:
- color label
- group
- full path
- user sort
- title
- description
- aspect

**Comment by wpferguson** [comment]
Thanks @TurboGit, it's working now.
