### ISSUE TITLE
hbox'd buttons expand on hover

### ISSUE THREAD

**Issue by sams96** [darktable-org/darktable#3359]
**Describe the bug**
Buttons contained within a GTK hbox expand on hover, these include buttons in the following modules, styles, tagging, vignetting, rgb levels, levels, color mapping, basic adjustments. Thanks to Timur in the mailing list for reporting this.

**To Reproduce**
Hover over buttons in one of the modules listed above

**Expected behavior**
Buttons should stay the same size

**Screenshot**
![test](https://user-images.githubusercontent.com/1129989/68539722-b8f7ae80-03c2-11ea-8d92-f90573a0fcdf.gif)

**Platform (please complete the following information):**
 - OS: I'm on Arch Linux, but I don't think this is platform specific.
 - Version 3.0RC0

**Additional context**
I fixed this issue in the metadata modules in 53deee7 by changing from a hbox to a grid, but I thought maybe there's a more elegant way to fix this. If not I'll change the rest to grids soon.

**Comment by phweyland** [comment]
>     * OS: I'm on Arch Linux, but I don't think this is platform specific

I don't see this effect on windows 10.

**Comment by aurelienpierre** [comment]
Maybe your GTK theme is setting a different padding or border size for the `:hover` pseudo-class.

**Comment by junkyardsparkle** [comment]
I don't see this, using a minimal window manager rather than a desktop, for whatever that's worth.

**Comment by TurboGit** [comment]
And I don't see that using GNOME Shell with latest Gtk on Debian/sid.

**Comment by junkyardsparkle** [comment]
It sounds like migrating from deprecated hbox to grid is not a bad idea in general, though... at least in theory. Are there any known weird GTK3 bugs associated with that?

**Comment by sams96** [comment]
Hmm... I'm using XFCE/BSPWM, I've emailed Timur (who reported this on the mailing list) to find out what he's using since we seem to be the only ones here seeing this issue.

Also I looked up hbox being deprecated and noticed that they aren't actually hboxs in darktable, it's just a gtk box but the variables always seem to be names hbox.

But anyway I just did some testing and if I change the theme it no longer happens, even if I change back to the default theme. Only when starting darktable with the default theme enabled does this happen.

**Comment by AxelG-DE** [comment]
maybe an obsolete question...
Realy **all** Roboto font packages installed?

**Comment by sams96** [comment]
I actually don't have roboto packages installed.

However, I just tested #3362 and it fixes the issue for me.

**Comment by AxelG-DE** [comment]
I have had similar experiance like you, before I installed Roboto. I suggest, you try this as well prior merging of #3362

**Comment by Nilvus** [comment]
@sams96 and @AxelG-DE : I never have this issue on my system but I'm glad my PR also solves that for you. That was not the purpose but good to see it helps here. Anyway, installing Roboto is a good thing to do to have the best experience on this new UI.

My PR should be merged this day or tomorrow by @TurboGit.

**Comment by sams96** [comment]
@AxelG-DE I just tested the master branch after installing roboto and the issue is still present
