### ISSUE TITLE
filmicrgb causes inconsistent recomputations

### ISSUE THREAD

**Issue by matze** [darktable-org/darktable#3363]
**Describe the bug**

Enabling filmicrgb and playing with the black slider causes different recomputations with no apparent reason, i.e. sometimes only a few operations are recomputed
```
[dev_pixelpipe] module `filmic rgb' min: (0,000000; 0,000000; 0,000000) max: (0,945891; 0,946208; 0,945628) [preview]
[dev_pixelpipe] module `Ausgabefarbprofil' min: (0,000000; 0,000000; 0,000000) max: (0,976319; 0,975058; 0,974915) [preview]
[dev_pixelpipe] module `Eingabefarbprofil' min: (-37,861107; -35,862141; -34,018124) max: (105,419022; 30,675858; 79,398048) [full]
[dev_pixelpipe] module `filmic rgb' min: (0,000000; 0,000000; 0,000000) max: (0,957320; 0,958640; 0,953454) [full]
[dev_pixelpipe] module `Ausgabefarbprofil' min: (0,000000; 0,000000; 0,000000) max: (0,980263; 0,981006; 0,978441) [full]
```
sometimes a lot more which increases the time to finish
```
[dev_pixelpipe] module `filmic rgb' min: (0,000000; 0,000000; 0,000000) max: (0,948935; 0,949180; 0,948879) [preview]
[dev_pixelpipe] module `Ausgabefarbprofil' min: (0,000000; 0,000000; 0,000000) max: (0,977594; 0,976446; 0,976437) [preview]
[dev_pixelpipe] module `Raw-Schwarz-/Weißpunkt' min: (-0,006475) max: (1,145895) [full]
[dev_pixelpipe] module `Weißabgleich' min: (-0,013356) max: (2,734931) [full]
[dev_pixelpipe] module `Spitzlicht-Rekonstruktion' min: (-0,013356) max: (1,000000) [full]
[dev_pixelpipe] module `Entrastern' min: (-0,048125; -0,036022; -0,027651) max: (1,124832; 1,106859; 1,099834) [full]
[dev_pixelpipe] module `Eingabefarbprofil' min: (-37,861107; -35,862141; -34,018124) max: (105,419022; 30,675858; 79,398048) [full]
[dev_pixelpipe] module `filmic rgb' min: (0,000000; 0,000000; 0,000000) max: (0,959603; 0,960965; 0,955618) [full]
[dev_pixelpipe] module `Ausgabefarbprofil' min: (0,000000; 0,000000; 0,000000) max: (0,981321; 0,982087; 0,979446) [full]
```
**To Reproduce**
1. Enable filmicrgb.
2. Play with the black slider.
3. Monitor the log.

**Expected behavior**
Exactly the same, minimal amount of recomputations.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: current Git HEAD

**Comment by aurelienpierre** [comment]
Not sure I understand. A new recomputation is triggered each time a parameter is changed in a module. If the previous modules outputs have been cached, only the modules coming after the changed one are recomputed.

How do you interact with the slider ? Mouse wheel scrolling, left click, arrow keys or touchpad scrolling ?

If you are using touchpad scrolling, it's possible that it's a GDK issue causing the parameter change to be recorded before you actually finished scrolling. There is something strange going in there.

**Comment by matze** [comment]
> How do you interact with the slider ? Mouse wheel scrolling, left click, arrow keys or touchpad scrolling ? Does it happen with other modules or other sliders ?

It happens with all sliders in filmicrgb and with a single left click. I have not yet noticed similar issues with other modules.

**Comment by aurelienpierre** [comment]
> P.S.: I can rightfully assume that demosaic and highlight reconstruction should never be triggered again unless I mess with the order?

As long as you are not zooming/panning, yes. Otherwise, everything gets recomputed.

> It happens with all sliders in filmicrgb and with a single left click. I have not yet noticed similar issues with other modules.

Weird. The sliders callbacks are not much different from other modules, the only exception being the enqueue the graph redraw.
