### ISSUE TITLE
opencl: discarding device when raising opencl_memory_requirement=2048 (6GB available)

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#3365]
**Describe the bug**
Follwing [this thread on pixls.us](https://discuss.pixls.us/t/darktable-3-0-and-opencl-on-modern-hardware/14782) I experimented with 
`opencl_memory_requirement=2048`

The effect is, opencl will be deactiveted, eventhouh my GTX1060 (two of them) have 6GB each.

-d opencl complains:
[0.321075 [opencl_init] found opencl runtime library 'libOpenCL'
0.321088 [opencl_init] opencl library 'libOpenCL' found on your system and loaded
0.437657 [opencl_init] found 2 platforms
0.437682 [opencl_init] could not get device id size: -1
0.437686 [opencl_init] found 2 devices
0.437866 [opencl_init] device 0 `GeForce GTX 1060 6GB' has sm_20 support.
0.437992 [opencl_init] discarding device 0 `GeForce GTX 1060 6GB' due to insufficient global memory (6069MB).
0.438144 [opencl_init] device 1 `GeForce GTX 1060 6GB' has sm_20 support.
0.438285 [opencl_init] discarding device 1 `GeForce GTX 1060 6GB' due to insufficient global memory (6078MB).
0.438289 [opencl_init] no suitable devices found.
0.438290 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.438291 [opencl_init] initial status of opencl enabled flag is OFF.
1,434961 [pixelpipe_process] [thumbnail] using device -1](url)

my other opencl settings in darktablerc are:
```
opencl=TRUE
opencl_async_pixelpipe=true
opencl_avoid_atomics=false
opencl_checksum=1269930737
opencl_device_priority=1,*/!1,0,*/*/*
opencl_disable_drivers_blacklist=false
opencl_library=
opencl_mandatory_timeout=200
opencl_memory_headroom=300
opencl_micro_nap=100
opencl_number_event_handles=300
opencl_scheduling_profile=multiple GPUs
opencl_size_roundup=16
opencl_synch_cache=active module
opencl_use_cpu_devices=false
opencl_use_pinned_memory=false
```

**Expected behavior**
opencl should be activated, as the memory is sufficient

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [3.0.0rc0-85-g56bf781bb]
 -nvidia-driver: x11-drivers/nvidia-drivers-435.21
  USE=X acpi driver gtk3 kms multilib tools uvm -compat -libglvnd -static-libs -wayland 
 ABI_MIPS="-n32 -n64 -o32" 
 ABI_RISCV="-lp64 -lp64d" ABI_S390="-32 -64" ABI_X86="32 64 -x32" KERNEL="linux -FreeBSD"

**Comment by TurboGit** [comment]
Should be fixed. Can you test with master and confirm? I don't have enough memory to check the overflow :)

**Comment by TurboGit** [comment]
New fix just pushed, please be sure to test this second version.

**Comment by AxelG-DE** [comment]
@TurboGit 
I confirm 3.0.0rc0-98-g46b65042f fixed this issue. Thank you!
