### ISSUE TITLE
add key to apply again the last tag

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#3366]
When I tag people in a series I often need to type again and again the same tag:

For example:

> people|marc

**Describe the solution you'd like**
Looking at the lighttable it should be possible to have a key to apply again the last applied tag. A single key to add back the same tag will make it as easy as adding a color label to a picture.

**Describe alternatives you've considered**
None!

This sounds like a nice enhancement and should not be too difficult to code.

**Comment by spaceChRiS** [comment]
There's the copy paste tags lua script which I use for a similar workflow. Assigning the keys c and v is very convenient. It's one additional key, but it gives much more flexibility as well.

But of course I do not want to stop you doing a native implementation ;)

**Comment by TurboGit** [comment]
If you are speaking about quick_tag it does not suite my need. I was to use the standard tag module and tag as usual and when I want to apply the last tag again I use the action key.

The quick tag just provide a list of 5 tags which must be first entered and then used, not very handy or at least not what I'm looking for.

**Comment by spaceChRiS** [comment]
No, I am speaking about copy and paste, I think it's https://github.com/darktable-org/lua-scripts/blob/master/contrib/copy_attach_detach_tags.lua but I cannot check now as I am not on my computer.

**Comment by TurboGit** [comment]
Fixed.
