### ISSUE TITLE
Retouch module failed this time

### ISSUE THREAD

**Issue by HardySoftware** [darktable-org/darktable#3368]
**Describe the bug**
The retouch module does not work under some particular circumstance.

**To Reproduce**
 - Download my raw file and sidecar file from https://ln2.sync.com/dl/1aa47bf90/7qjknhmj-5ugss5th-372sswhv-fwxbzm87
 - Open it in version 2.6.3
 - Export this file

**Expected behavior**
In my workflow I have remove the high voltage wire at top right corner, it is clear that you can see it either in lighttable or darkroom preview. However after you export it (I also attached my result in the same archive file) you can see the top right corner still has the wire.

Export settings: JPEG (8-bit), 100% quality, max size, no up scaling.

**Screenshots**
See my archive file, it is included.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.3

**Additional context**
Nope

**Comment by blitzgneisserin** [comment]
confirmed, Lubuntu 19.10, dt 3.0rc

**Comment by HardySoftware** [comment]
I think it is "crop and rotate" module. What I tried is to turn off all modules except for "white balance", "highlight reconstruction" and "base curve" on. I can see the wire in fit-to-window now. As soon as I turn on the "crop and rotate" it is gone from fit-to-window but still visible 100%.

So it leads me to ask the question that are there 2 bugs? Preview is one, and export is another one? Did I use retouch module properly? I think according to the wavelet layers in retouch module the wire should have been removed.

**Comment by pphotography** [comment]
This just happened to me with 3.0.0rc2~git62.ab5436b3a on Ubuntu 18.04.

I was editing a photo and retouching some sensor dust was one of my last steps when I  noticed that the  circles I used in heal mode didn't remove the spots.
I'm on a state where this behavior is reproduce able every time I open a image. 

The results look like the retouch module is working with reduced opacity. I deactivated OpenCL without any change.

This is the original part with a dust particle I wanted to remove:
![01_original](https://user-images.githubusercontent.com/49001045/70248084-b3e80e00-177a-11ea-8432-ebb9d91a1425.png)

Now this is the result after using a circle shape in heal mode, normally this would remove that spot completely:
![02_heal](https://user-images.githubusercontent.com/49001045/70248521-4e485180-177b-11ea-9677-dc261f5a7d98.png)

Same spot in clone mode:
![03_clone](https://user-images.githubusercontent.com/49001045/70248567-5c966d80-177b-11ea-9fc8-c47513445c9c.png)

Cloned a complete different looking area:
![04_clone](https://user-images.githubusercontent.com/49001045/70248609-6ddf7a00-177b-11ea-96d8-ca1540f99ecb.png)

Tried the old spot removal module:
![05_spotremoval](https://user-images.githubusercontent.com/49001045/70248682-8bacdf00-177b-11ea-85b2-c0b5b1416d7e.png)

Here is my file with the XMP's (the first one was done with dt 2.6.2, I started a second XMP without copyinf the old history in the duplicate manager where the problem occured)



[20181015_Elbsee.zip](https://github.com/darktable-org/darktable/files/3927641/20181015_Elbsee.zip)

**Comment by TurboGit** [comment]
> The results look like the retouch module is working with reduced opacity.

And why don't you think it is the case actually ?

**Comment by pphotography** [comment]
Is this intended? If this is the case I would need several attempts to remove a single point.

**Comment by TurboGit** [comment]
I don't understand ! Nothing is intended but are you sure you have not change the opacity of the tool? Nothing seems to indicate this is not the issue. If you are confused please read the documentation :)

**Comment by pphotography** [comment]
Thanks for the hint. Seems I accidentally changed the shape's opacity. Most likely I pressed CTRL instead of SHIFT while changing the outer borders with the mousewheel.
