### ISSUE TITLE
Star ratings in darkroom not applied to the image under edit

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#3369]
**Describe the bug**
In darkroom, rating and colour labels are applied to image hovered in film strip, and not to the image currently loaded. I consider this behaviour unexpected from a user perspective, as I would always expect that in darkroom, rating and colour labels (and tags etc.) belong to the image I am working on. I hardly see use cases where I would rate another image in the film strip.

**To Reproduce**
1. Go to darkroom
2. Hover over an image that is not the one currently worked on
3. Press e.g. a number (1 to 5)
4. The hovered image changes stars, not the one worked on

**Expected behavior**
I would expect that in darkroom, rating and labels etc. always belong to the image worked on.

**Screenshots**
n/a

**Platform (please complete the following information):**
 - OS: Ubuntu 16.04
 - Darktable 2.6.0 (unfortunately I cannot upgrade and test on newer version atm)

**Additional context**
n/a

**Comment by TurboGit** [comment]
As far as I know this has always been the case. It is a feature not a bug of the filmstrip in the darkroom.

**Comment by Nilvus** [comment]
I will add that I remember that few months ago we discussed that and ended on letting how that's works actually because having the possibility to change other images than the ones selected is very useful, for example to copy/paste edits/settings from the edited image to other by hovering. A thing improved for next darktable 3.0 was a way to better see which image is selected, to avoid confusion between selected and hovered image.

**Comment by spaceChRiS** [comment]
I was sure that this was discussed already, maybe there are even reports on redmine. I am using darktable now for at least 7 or 8 years, maybe more, and from time to time it still happens that I rate or label a wrong image because I am not aware that the mouse pointer is hovering another image. It happened yesterday again, and I decided to report it. IMHO it makes sense that it happens if I select another picture by clicking, but hover is too weak. I always have to check where the pointer is, which is not happening all the time. E.g., when I release my mouse, it often happens that the pointer jumps a bit. Sometimes similar things happen in lighttable as well, but that's another story.

**Comment by parafin** [comment]
Just an idea - how about giving a selection by hover on filmstrip some timeout, e.g. 5 seconds. So if mouse hasn't moved for 5 seconds, image gets deselected and actions are applied on the currently open image. Timeout should be reset back to original if user does an action on hovered filmstrip image.

**Comment by spaceChRiS** [comment]
Hm, I still do not get the benefits of hover over clicking to select an image. IMHO, hover should not select, clicking should select and double click should load. If no image is selected, apply rating to edited image, if an image is selected, apply rating to selected image. What do I miss?

**Comment by arigit** [comment]
> As far as I know this has always been the case. It is a feature not a bug of the filmstrip in the darkroom.

I can confirm this as I have been bitten by this strange DT behaviour many times, with random images getting the rating/colour I wanted to assign the image on screen (I use a combination of keyboard and mouse while culling).
 
I agree with the OP that this behavior is counter-intuitive and that when on darktable mode, the most reasonable behavior would be that all operations including rating, tagging and whatnot (in addition to module operations) should affect only the opened image, the image being edited.

While culling it's common to have the need to jump out of culling mode to inspect a version of a shot and sometimes culling just continues in darktable mode. Unfortunately the current user experience is kind of broken for this use case. Not a fun of the "hover and wait" idea above - I'd rather simplify and make rating/labelling while in darktable mode just affect the image being edited.

**Comment by spaceChRiS** [comment]
As I am not alone with my opinion, could somebody please re-open to give the chance to discuss it further? I especially want to understand what the benefits of the current behaviour are.

**Comment by AlicVB** [comment]
More generally, once my big lighttable rewrite in place, we can imagine to discuss the "operate on image over" behavior, and especially propose other (optional) algorithms. They should be easier to implement as everything will happen in one unique place.
Maybe you can wait for my rewrite to land, and then open a FR ? Thanks
(but be patient, it's far from finished...)

**Comment by spaceChRiS** [comment]
> Maybe you can wait for my rewrite to land, and then open a FR ? Thanks
> (but be patient, it's far from finished...)

Of course I can wait, and thanks for working on this big lighttable rewrite! I would still prefer to keep this report open, even if it takes a long time, otherwise I would have to open a duplicate of a closed report, what does not make sense to me. Unfortunately I cannot reopen it by myself.

**Comment by AlicVB** [comment]
Anyway it should be a new FR, as it'll cover more that this specific use case...

**Comment by spaceChRiS** [comment]
K, I'll try to not miss the right time. What else should it cover, general change of hover behaviour, as option?

**Comment by AlicVB** [comment]
yes
