### ISSUE TITLE
Lut3d causes grey speckles on the image

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3371]
**Describe the bug**
When a LUT is applied the image gets these gray pecs in the darkroom view, the preview looks fine.

![Annotation 2019-11-11 082217](https://user-images.githubusercontent.com/1119439/68557623-6c60b180-045c-11ea-83a7-6039f3320c9e.png)

If I move the LUT module to after the output color the gray specs go away in the darkroom view.

The image captures the history, modules in pixelpipe and the color spaces being used.

OS : Win 10
darktable-3.0.0rc0+98~g46b65042f-win64

**Comment by TurboGit** [comment]
This should already be fixed.

**Comment by chhil** [comment]
I am running the most current build.

**Comment by TurboGit** [comment]
Strange this issue has already been reported and fixed.

**Comment by phweyland** [comment]
on you screenshot preview displays a duller image than darkroom. What are your opencl settings ?
could you play around with and without opencl ?

**Comment by chhil** [comment]
Looks like it happens on a newly imported image and the first step is adding lut module.
Adding does create 2 lut entries in history for whatever reason.
![image](https://user-images.githubusercontent.com/1119439/68571248-9334dd00-0488-11ea-9fb3-57b35d5c4153.png)

I have opencl enabled. Even when I uncheck it, the same problem occurs.

Duller image is with the lut applied. Thats what I meant when preview looks fine.

**Comment by chhil** [comment]
I was playing around and when I clicked gamut check the specs disappear for good.

**Comment by phweyland** [comment]
> Duller image is with the lut applied. Thats what I meant when I said preview looks fine.

not sure to understand everything. can you confirm that when opencl is disabled both previous and darkroom images are dull (and without specs) ?

**Comment by chhil** [comment]
I confirm that specs appear ONLYwhen opencl is on AND the image edit is new with only the default modules (i.e. if I have a full edited image with lots of history, then I add the same LUT it does not misbehave with opencl on).
