### ISSUE TITLE
Strange behavior in history stack compression

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3372]
**Describe the bug**

If you open a new image you can see all the modules which are always applied to an image like demosaicing, white balance, input color profile etc.

If you select 'origin' in the history stack and then press compress history, the modules are still staying there. This is what we want.

However if you have 'origin' in the history stack selected and activate e.g. the orientation module. It gets compressed and you only have 'origin' and 'orientation' in the history stack.

@TurboGit Is this really intended?

**Comment by todd-prior** [comment]
I think if you look they are still active for example highlight reconstruction over in the module pane but they are indeed not showing after doing that in the history. This might lead someone to think they have disabled highlight reconstruction and or other modules  when they have not...

**Comment by cryptomilk** [comment]
Fixed by https://github.com/darktable-org/darktable/commit/15c4a785123dcba40d2884fa92c987723f0c5715 and https://github.com/darktable-org/darktable/commit/44c9f0d66b5db94ab14375e02c56fd2b6a48c811
