### ISSUE TITLE
first run under hyper-v

### ISSUE THREAD

**Issue by kairos10** [darktable-org/darktable#3373]
[darktable_bt_X3P8A0.txt](https://github.com/darktable-org/darktable/files/3830357/darktable_bt_X3P8A0.txt)
using a relatively clean win10 image on a secondary HDD:
   a) win10 image on HyperV
   b) win10 image on baremetal

a) under HyperV, darktable would crash on the first run.
b) darktable started fine when the win10 image was ran on barematal

After the first successful start, darktable runs fine on both (a) and (b)

**Comment by aurelienpierre** [comment]
darktable is supported as much as possible on Windows, but we don't have ressources to ensure virtualization works.
