### ISSUE TITLE
local laplacien broken

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#3374]
**Describe the bug**
Error reported:
[local laplacian cl] failed: -4

**To Reproduce**
1. Go to darkroom
2. Activate module "local contrast"
3. Export image
4. See error on the console

**Expected behavior**
No message!

**Platform (please complete the following information):**
 - OS: Debian obviously with OpenCL (Nvidia)
 - Version master

Seems to be broken since a long time. At least afbaa7e has already this issue.

**Comment by TurboGit** [comment]
Can someone reproduce?

Any taker for this one? I'm really not expert on OpenCL :(

**Comment by TurboGit** [comment]
On locallaplaciancl.c it fails on this line:
`    err = dt_opencl_enqueue_kernel_2d(b->devid, b->global->kernel_laplacian_assemble, sizes);`

**Comment by chhil** [comment]
Exports fine for me without any error with opencl enabled

![image](https://user-images.githubusercontent.com/1119439/68577915-03e2f600-0497-11ea-99d6-3751b36f519c.png)


darktable-3.0.0rc0+98~g46b65042f-win64

**Comment by TurboGit** [comment]
What is also strange is that my export looks fine.

**Comment by TurboGit** [comment]
The documentation says about the error code:

```
-4  CL_MEM_OBJECT _ALLOCATION_FAILUREif 
there is a failure to allocate memory for buffer object.
```

How much memory do you have on your card?

**Comment by TurboGit** [comment]
Ok, that's indeed a memory issue. Raising my opencl_memory_headroom fixed the issue. And my output was ok because dt had used the CPU has fallback. All good, closing.
