### ISSUE TITLE
Canon EOS M6 Mark II camera support

### ISSUE THREAD

**Issue by Harry456-foto** [darktable-org/darktable#3375]
Can the Canon EOS M6 Mark II be supported and also the CR3-file format of the images?

Kind Regards,

**Comment by LebedevRI** [comment]
Please contribute full sample set.
If not, there should be 8 samples - {RAW,CRAW} x {each aspect ratio - 3:2,4:3:16:9,1:1}
Does that have dual-pixel raws? If yes, then multiply that by two (with and without dualpixel raw)
_Please_ name each sample accordingly.

**Comment by aurelienpierre** [comment]
This issue is closed for lack of response from the original poster. Reopen if they come back.

**Comment by LebedevRI** [comment]
Can you please not.

**Comment by aurelienpierre** [comment]
> Can you please not.

Ok sorry, I will let you manage the camera support issues. I was just trying to make some space here.

**Comment by Harry456-foto** [comment]
I have uploaded following files from the camera Canon EOS M6 MKII:

RAW/CRAW | Aspect   ratio | Name
-- | -- | --
RAW | 3:2 | IMG_RAW_3_2.CR3
CRAW | 3:2 | IMG_CRAW_3_2.CR3
RAW | 4:3 | IMG_RAW_4_3.CR3
CRAW | 4:3 | IMG_CRAW_4_3.CR3
RAW | 16:9 | IMG_RAW_16_9.CR3
CRAW | 16:9 | IMG_CRAW_16_9.CR3
RAW | 1:1 | IMG_RAW_1_1.CR3
CRAW | 1:1 | IMG_CRAW_1_1.CR3

Can also create a call so that Rawtherapee will be updated with CR3 filetypes?

**Comment by LebedevRI** [comment]
@Harry456-foto thank you very much!

**Comment by balta3** [comment]
what is needed to get this camera supported? Right now I'm using Darktable 3.8.1 and switched to an EOS M6 Mark II recently.

* In the Image information of captured RAW images Darktable is showing "EOS M6" as camera model which is wrong, Exiftool is showing correctly "EOS M6 Mark II"
* The lens correction tool is showing me an error that the camera cannot be found, If I want to select it manually I can just find the M6, not the Mark II
* The denoiser tool is using profiles for the M6, not the M6 Mark II
* The white balance tool is using profiles for the M6, not the M6 Mark II

The release notes for 3.8.0 contain support for the M6 Mark II but is seems to be not working correctly. Is there some way I can help? I can send you all needed test images and even create a PR if you can point me in the right direction.

**Comment by kmilos** [comment]
Here's the status in dev version 3.9.0+1647~g2dfa2224d:

* Basic support: indeed, the model name lookup needs to be fixed up (I'll do that shortly)
* Lens module seems to be ok and shows "EOS M6 Mark II" for me, so you might want to update your lensfun database
* There is indeed no noise profile, [please feel free to create one and submit a PR](https://github.com/darktable-org/darktable/wiki/Camera-support#noise-profiles)
* There is indeed no WB preset, [please feel free to create one and submit a PR](https://github.com/darktable-org/darktable/wiki/White-balance-presets)

**Comment by jheidemann** [comment]
The patch that was merged above is not sufficient to support Canon EOS M6 Mark II because there is missing data in rawspeed.  Please pick up the patch I just posted to https://github.com/darktable-org/rawspeed/issues/284

Thanks.

**Comment by jheidemann** [comment]
Hmm, wrt "CR3-based Cannon support is not currently provdied through RawSpeed": stock fedora 41 darktable is 4.8.1.  It refused to read cr3, giving error 

`Canon EOS M6 Mark II' color matrix not found for image

That went away when I added the patch.  Isn't 4.8.1 similar to the tip of the git here?

(Or if not, I can take the patch to Fedora, I suppose.)
