### ISSUE TITLE
DT very regularly stuck with working label on the image and requires killing the process

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3376]
**Describe the bug**
Unfortunately I don't have enough information other than the app (version: darktable 3.0.0rc0+98~g46b65042f)  just keeps freezing and I have to kill it and restart it. It doesn't get unresponsive but the working ...label on the image persists. I know its frozen as when I move some sliders , like the exposure, the sliders move but the histogram doesn't change.

I did run the app with -d all from command line and it did not log anything. My build is release with debug info.

Is there anything I can do to provide you more info?

In all likelihood I will start running an older build and keep this one around for a bit.

**Comment by TurboGit** [comment]
This is recent, right? Would be nice to identify the first commit making this issue.

**Comment by chhil** [comment]
Yes, its the recent one from this morning in my timezone.

The problem is it could be any module so not sure of direction to take.

**Comment by chhil** [comment]
I have seen it happen in exposure quite often.

Just happened.
![image](https://user-images.githubusercontent.com/1119439/68591475-d7d76d00-04b6-11ea-8e22-47c533ae5054.png)

Moved the exposure extreme left using the histogram (top right), note the histogram hasnt changed but the image has changed.

**Comment by chhil** [comment]
It goes unresponsive but there is no CPU usage.
![image](https://user-images.githubusercontent.com/1119439/68591694-56340f00-04b7-11ea-80c3-b9839b1ff420.png)

**Comment by chhil** [comment]
I have narrowed it down to an opencl issue. If its enabled and I let the mouse wheel scroll infinitely giving it a free spin on the exposure histogram, I can get it to hang. If opencl is not on, I cannot reproduce it.
The mouse is one of those that you can give a hard push and let it spin. Though this is not what caused all the hangs when I logged the issue, but this one is reproducible.

**Comment by chhil** [comment]
With the newer builds I am not seeing this. Closing this for now.
