### ISSUE TITLE
Strange Patterning in lightable

### ISSUE THREAD

**Issue by brigling** [darktable-org/darktable#3380]
![Screenshot from 2019-11-11 15-09-12](https://user-images.githubusercontent.com/54001084/68608154-89c06a80-04b2-11ea-8277-ac7627f8a7ac.png)
**Patterning in lightable full image preview**
Once I start editing this photo and some others the full frame preview in lightable gives a strange pattern.

I am finding it hard to reproduce, it is only happening on some photos and I don't think it is specific to a single module. filmic rgb makes it the strongest though.

**Screenshots**
included

**Platform (please complete the following information):**
 - OS: [popOS 19.10
 - Version [e.g. 3.0.0rc0]

**Additional context**
I am using compressed raw from Fujifilm xt2

**Comment by aurelienpierre** [comment]
Did you try to change the demosaicing options ?

**Comment by aurelienpierre** [comment]
This issue is closed for lack of response from the original poster. Reopen if they come back.
