### ISSUE TITLE
target black luminance on filmic rgb. Shadows Filled White

### ISSUE THREAD

**Issue by brigling** [darktable-org/darktable#3381]
![Screenshot from 2019-11-11 18-46-50](https://user-images.githubusercontent.com/54001084/68608730-e53f2800-04b3-11ea-9e1f-9416adacaa25.png)

when I raise the target black luminance above 0% the shadows are destroyed.

**To Reproduce**
apply filmic rgb and adjust the target black luminance slider

**Expected behavior**
see screenshot

**Platform (please complete the following information):**
 - OS: [popos]
 - Version [3.0.0rc0]

**Additional context**
I am using fujifilm xt2 compressed raw

**Comment by blitzgneisserin** [comment]
cannot reproduce

**Comment by brigling** [comment]
> cannot reproduce

do you need a copy of a xt2 compressed raw file?

**Comment by blitzgneisserin** [comment]
> do you need a copy of a xt2 compressed raw file?

Probably good idea. I checked with an ORF.

**Comment by brigling** [comment]
[XT2 Compressed filmic bug.zip](https://github.com/darktable-org/darktable/files/3835819/XT2.Compressed.filmic.bug.zip)

This includes an xmp file with the module already applied issue. all the black turns to pure white.

![Screenshot from 2019-11-12 12-16-57](https://user-images.githubusercontent.com/54001084/68667489-634c0f00-0546-11ea-8d7d-0f366603d70e.png)

Thanks for your help!

**Comment by junkyardsparkle** [comment]
This is a result of raising 'target black luminance' in the 'display' tab. I can reproduce this using CPU, but not with OpenCL.

**Comment by brigling** [comment]
I Also tried with OpenCL on and It takes away the whitening effect.

**Comment by aurelienpierre** [comment]
Reproduced on CPU only. Under investigation…

**Comment by aurelienpierre** [comment]
Found it. I did a very stupid mistake, I can't believe it took that long to get noticed. Fix on the way.
