### ISSUE TITLE
Seg fault when opening second image in a session

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#3382]
**Describe the bug**
Start a session.  Open an image by double clicking in lighttable.  Return to lighttable.  Open a second image. darktable crashes with a seg fault.  I traced it to commit 27da9536c .

**To Reproduce**
1. Start darktable.
2. Double click on an image to open in darkroom.
3. Click lighttable link to return to lighttable.
4. Double click on different image.
5 darktable seg faults.

**Expected behavior**
Open the second image in darkroom

**Platform (please complete the following information):**
 - OS: unbuntu 18.04
 - Version git HEAD

**Additional context**

Commit 27da9536c and after exhibit the problem.

[darktable_bt_UBMBB0.txt](https://github.com/darktable-org/darktable/files/3832716/darktable_bt_UBMBB0.txt)

**Comment by TurboGit** [comment]
Indeed! I don't know how this commit could be the culprit, but I'll find out.

**Comment by TurboGit** [comment]
Ok, an easy one... A paste at the wrong location :)
