### ISSUE TITLE
version g44dcf6f35, double-click in lighttable unselects image rather than opening in darkroom

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#3383]
**Describe the bug**
double-click on image in lightroom unselects image rather than opening in darkroom mode

**To Reproduce**
as described:
1. Go to lighttable
2. Double-Click on an image
3. See msg "No image selected"

**Expected behavior**
image opened in darkroom mode

**Platform (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Version g44dcf6f35

**Comment by TurboGit** [comment]
Maybe related to #3382 ?

**Comment by wpferguson** [comment]
I looked at the log attached to the e-mail on the dev list and it shows the seg fault at line 709 in src/iop/levels.c.

this is darktable 3.0.0rc0+112~g44dcf6f35 reporting a segfault:

warning: Currently logging to /tmp/darktable_bt_A4JUA0.txt.  Turn the logging off and on to make the new setting effective.
#0  0x00007f4cd33ba6c2 in __GI___waitpid (pid=pid@entry=23389, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f4cd37a6050 in _dt_sigsegv_handler (param=11) at /home/goetz/repo/darktable/src/common/system_signal_handling.c:118
#2  0x00007f4cd3314f20 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f4cd0c7d032 in g_type_check_instance_cast () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007f4c5a9cfa48 in gui_init (self=0x558bb551da30) at /home/goetz/repo/darktable/src/iop/levels.c:709

**Comment by TurboGit** [comment]
So very same issue indeed, closing.

**Comment by ptilopteri** [comment]
reopen, problem still exists.
