### ISSUE TITLE
Filmstrip loses selection when ungrouping

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#3386]
**Describe the bug**
When you have groups like RAW+JPG and grouping enabled and you are somewhere in the collection and this is correctly displayed on the filmstrip, then when you click G to see the JPG of the same group all the grouped images expand and the filmstrip flips to some other image of the collection - so you lose the position in the filmstrip and are not able to click on the unfolded JPG without finding the position in the filmstrip again.
 
**To Reproduce**
1. Open a collection having grouped images (e.g. JPG+RAW)
2. Go to darkroom and check that G is selected (grouping is on)
3. Pick a photo somewhere in the middle of your collection
4. click on G to see the corresponding JPG (ungroup)
5. You will see that the filmstrip is not showing the selected image any longer

**Expected behavior**
I would expect the filmstrip to keep the selected image centered (and logically the groped images to appear in the visible part of the filmstrip).

**Platform (please complete the following information):**
 - OS: ubuntu 19.10
 - Version latest master

**Comment by AxelG-DE** [comment]
I am afraid this is a combination of related to a known bug, where the focus is way out of range, when you change the view of star ratings

**Comment by codingdave** [comment]
Well, the issue still persists. Closing an issue does not solve it ;)

**Comment by AxelG-DE** [comment]
@codingdave you should be capable to reopen it, aren't you?

**Comment by aurelienpierre** [comment]
Sorry, setting up bots is a trial-and-error process.

**Comment by Nilvus** [comment]
@codingdave: that part has been hugely reworked since your issue and reopening one year ago. Could you test again and check if this issue is solved or not? And closing in case it's now ok and no more issue. Thanks.

**Comment by codingdave** [comment]
Hi @Nilvus I will create a testsetting in the following days and report about the current status. Thanks for the reminder.

**Comment by Nilvus** [comment]
@codingdave: could you test again and anwser here if you still reproduce in actual master? Or close it if you don't reproduce. Thanks!

**Comment by codingdave** [comment]
Hi, I would like to test this old report but I am not able to do various important steps that have at least changed or got removed. So I need some help:

1. I do not see a way to get the filmstrip to show up together with the filemanager layout. I can only show/hide the timebar.
2. Formerly grouped items did have a G symbol on the group header that was clickable. If the group was collapsed a click on the G was opening the group. The image with G on it was the group leader(head). Clicking on another images button would make this the new group leader(head). This functionality seems to have gone or at least has changed. -- Update, I am able to see the group/unfold icon by changing the overlay to "permanent extended overlays"
3. 'G' seems to not be tied to the grouping any longer but I believe this can easily get re-assigned

So I need your help for 1. @Nilvus possibly? Thanks!

**Comment by codingdave** [comment]
pressing h reveals:
Control+f: toggle filmstrip and timeline.
But I only can toggle the timeline.

(Also: Control+G: selected images: group)

**Comment by Nilvus** [comment]
> Hi, I would like to test this old report but I am not able to do various important steps that have at least changed or got removed. So I need some help:
> 
>     1. I do not see a way to get the filmstrip to show up together with the filemanager layout. I can only show/hide the timeline.

Filmstrip is a mini filemanager for other views. So there's really no reason to have it in that view. You could have it so in all views except filemanager and zoomable ones because you already have thumbnails. And so ctrl+f works to display filmstrip or timeline depending on the view. Just normal behavior (explains in the manual)

>     2. Formerly grouped items did have a G symbol on the group header that was clickable. If the group was collapsed a click on the G was opening the group. The image with G on it was the group leader(head). Clicking on another images button would make this the new group leader(head). This functionality seems to have gone or at least has changed. -- Update, I am able to see the group/unfold icon by changing the overlay to "permanent extended overlays"

So all good here as it's also the normal behavior. You have the G that you can click depending on overlay set. The different overlays allow to display or not different thumbnail infos.

>     3. 'G' seems to not be tied to the grouping any longer but I believe this can easily get re-assigned

It's possible that NG input feature by @dterrahe had reset some shortcuts. You should indeed easily assign them back.

So, it's seems that there's no more issue here. If it's ok for you, please close this issue. If not, please precise clearly what's remains wrong. About shortcuts not assigned, if you want them set back by default, please consider closing this issue and open a new one (as feature request). Thanks.

**Comment by codingdave** [comment]
As @Nilvus has poited out there was a massive overhaul. The reported issue was adressing an older dt workflow and UI. I close it because the workflow and UI have changed so much that this report is not adding value anymore. A quick looks shows that the current dt behavior makes sense.
