### ISSUE TITLE
rotate vignetting

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#3387]
**Is your feature request related to a problem? Please describe.**
You can create an ellipsis and even change the shape of the vignette but you cannot rotate the shape. So an ellipse is always aligned to one of the borders and cannot be rotated freely.

**Describe the solution you'd like**
A rotation slider and possibly an area on the sketched vignette would make it easy to rotate. The UI slider is more important as it is easy to understand and possibly more easy to implement.

**Describe alternatives you've considered**
I could export the image, open it in gimp, and continue. But this breaks my workflow.

**Comment by junkyardsparkle** [comment]
You could always just use an inverted elipse mask with an appropriate module, and probably have more versatility (although adjusting the feathering without a slider isn't much fun). :-)

**Comment by juanbretti** [comment]
@junkyardsparkle , can you clarify how to do the work around? Thanks.

**Comment by juanbretti** [comment]
> 

@junkyardsparkle , can you clarify how to do the work around? Thanks.

**Comment by juanbretti** [comment]
> You could always just use an inverted elipse mask with an appropriate module, and probably have more versatility

@junkyardsparkle , can you clarify how to do the work around? Thanks.

**Comment by juanbretti** [comment]
To rotate an elipse mask, you need to press "Ctrl" while grabbing the handle to change the size of the elipse.

**Comment by CubicrootXYZ** [comment]
> To rotate an elipse mask, you need to press "Ctrl" while grabbing the handle to change the size of the elipse.

Can confirm this is working for the eclipse mask but for the vignette itself I could not find any way to rotate it. Would love seeing this getting added.

**Comment by DaveInDev** [comment]
yes, it could be very useful to have this ctrl-rotate behavior on the vignetting ellipse.
