### ISSUE TITLE
Filmic preserve chrominance artifacts

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#3389]
**Describe the bug**
When using the "Luminance Y" setting on preserve chrominance, black artifacts appear on the preview.  These artifacts worsen when zooming in and do not appear on the exported photo. Seems to happen only with OpenCL enabled.

**To Reproduce**
1. Open a photo in darkroom (ensure that opencl is enabled)
2. Enable filmic rgb and switch "preserve chrominance" to "Luminance Y" in the "look" tab.
3. Note the dark squares on the border of the image.  The pattern changes sometimes to cover the whole image.

**Expected behavior**
I don't expect to see any artifacts.  None of of the other "preserve chrominance" modes seem to be affected.

**Screenshots**
[![luminance-y-artifacts.png](https://i.postimg.cc/sXy069vG/luminance-y-artifacts.png)](https://postimg.cc/06WfrSG9)

**Platform (please complete the following information):**
 - OS: archlinux
 - Version 733fc5d97f2d3570f1577d4d4b0a571ab74fc01f

**Additional context**
```
0.490726 [opencl_init] opencl related configuration options:
0.490743 [opencl_init] 
0.490747 [opencl_init] opencl: 0
0.490750 [opencl_init] opencl_library: ''
0.490753 [opencl_init] opencl_memory_requirement: 768
0.490757 [opencl_init] opencl_memory_headroom: 300
0.490760 [opencl_init] opencl_device_priority: '*/!0,*/*/*'
0.490764 [opencl_init] opencl_mandatory_timeout: 200
0.490767 [opencl_init] opencl_size_roundup: 16
0.490770 [opencl_init] opencl_async_pixelpipe: 1
0.490773 [opencl_init] opencl_synch_cache: true
0.490777 [opencl_init] opencl_number_event_handles: 25
0.490780 [opencl_init] opencl_micro_nap: 1000
0.490785 [opencl_init] opencl_use_pinned_memory: 1
0.490788 [opencl_init] opencl_use_cpu_devices: 1
0.490791 [opencl_init] opencl_avoid_atomics: 0
0.490800 [opencl_init] 
0.494007 [opencl_init] found opencl runtime library 'libOpenCL'
0.494042 [opencl_init] opencl library 'libOpenCL' found on your system and loaded
0.796507 [opencl_init] found 1 platform
0.796533 [opencl_init] found 1 device
0.796564 [opencl_init] device 0 `Intel(R) Gen9 HD Graphics NEO' supports image sizes of 16384 x 16384
0.796569 [opencl_init] device 0 `Intel(R) Gen9 HD Graphics NEO' allows GPU memory allocations of up to 4095MB
[opencl_init] device 0: Intel(R) Gen9 HD Graphics NEO 
     GLOBAL_MEM_SIZE:          12597MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           19.43.14583
     DEVICE_VERSION:           OpenCL 2.1 NEO 
```

**Comment by blitzgneisserin** [comment]
cannot reproduce

**Comment by TurboGit** [comment]
I fear the issue is **Intel(R) Gen9 HD Graphics NEO**. Some people keep saying that Intel drivers are fine but it seems we have some reports showing that this is not the case. I may be wrong, but let's see if people reproducing this also have the same card.

**Comment by aurelienpierre** [comment]
I'm using Intel Neo too, I don't seem to reproduce.

**Comment by TurboGit** [comment]
So I was wrong :) And that's good :)

**Comment by TurboGit** [comment]
Then try changing some prefs in darktablerc, as you seem to have 4gb on your card, you may try this:

```
opencl_memory_requirement=2048
opencl_memory_headroom=1024
```

**Comment by aurelienpierre** [comment]
@groutr is it only with luminance preservation mode ? What if you decrease the black level in exposure module ? Does it appear only on certain pictures ?

**Comment by groutr** [comment]
@aurelienpierre, issues are only observed in the luminance preservation mode. I updated my kernel and now picture is completely black on the 'fit-to-screen' zoom level.  Each zoom level can either have no artifacts or the artifacts like the image above.  On my machine it seems to happen with every image I've tried so far.

These artifacts don't appear in the exported image, which to me means that the neo drivers are not the problem.

**Comment by aurelienpierre** [comment]
Ok, I have been able to reproduce on one picture with Intel Neo. The culprit is the OpenCL building flag `-cl-finite-math-only`… Fix upcoming but we will lose some performance.

**Comment by groutr** [comment]
@aurelienpierre I don't think #3407 fixed the issue on my system.  I'm still getting artifacts more often than not with a fresh build of 0c6995fbe3797f8a60cd31bc68449b996ecff6ce.  At some zoom levels, I get this pattern of artifacts.
[![neo-artifacts.png](https://i.postimg.cc/qMhVpX83/neo-artifacts.png)](https://postimg.cc/7fkQVztH)

**Comment by groutr** [comment]
@aurelienpierre, I've discovered that I can invert the value of the artifacts by changing the target black luminance (in the display tab).

**Comment by groutr** [comment]
There was also an update to the NEO drivers yesterday on archlinux, though they don't seem to affect this issue.
```
0.248574 [opencl_init] device 0 `Intel(R) Gen9 HD Graphics NEO' supports image sizes of 16384 x 16384
0.248598 [opencl_init] device 0 `Intel(R) Gen9 HD Graphics NEO' allows GPU memory allocations of up to 4095MB
[opencl_init] device 0: Intel(R) Gen9 HD Graphics NEO
     GLOBAL_MEM_SIZE:          12597MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           19.44.14658
     DEVICE_VERSION:           OpenCL 2.1 NEO
```

**Comment by aurelienpierre** [comment]
The issue I had with OpenCL Intel was a full black picture. Still can't reproduce these salt and pepper thing. It's still only Y luminance mode ?

**Comment by groutr** [comment]
@aurelienpierre I think I might have stumbled onto a very strong correlation. The artifacts seem to appear when I have firefox running in the background (I use the nightly which has webrender enabled for intel gpu).  When firefox is busy in the background, I get the artifacts in darktable.

I tested it by running the motionmark, a graphics heavy benchmark, in firefox with webrender. While running that benchmark, I was able to reproduce the salt and pepper artifacts almost 100% of the time.  There is a very strong correlation between the two programs.

I think we can add back in the -cl-finite-math-only flag (I was testing a local build with that and I was unable to reproduce the full black screen).

**Comment by groutr** [comment]
@aurelienpierre, the issues with the full black pictures seemed to resolve themselves after the NEO driver update and a reboot.  I've been testing with `-cl-finite-math-only` in my local builds and have not observed any further issues.  Funnily enough, when I used `-cl-opt-disable` I got full black pictures.
