### ISSUE TITLE
Clicking on the group header needs many clicks to work

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#3393]
**Describe the bug**
Having RAW+JPGs that constitute groups and "Groups" turned on only the Group Header is displayed. Now the manual https://www.darktable.org/usermanual/en/image_grouping.html tells 

> If you press the “G” symbol in the group's thumbnail, only this group gets expanded; if you then expand another group, the first group collapses. To collapse an expanded group again, just click on the “G” symbol of its group head.

I mostly need to click on G between 3 and 20 times. 

**To Reproduce**
1. Have the preconditions for grouping set (collection with groups and groups collapsed s.t. you see the G icon on the group head)
2. Click on a group header and see that nothing happens
3. Repeat clicking and see that at some time the group expands
4. Click on another group headers "G" to show the other group and repeat at step 3.

**Expected behavior**
Depending on dts usability concept 
* either first select the image by clicking anywhere and have a second click on "G" to open the group 
* or click once on a G to unfold its group 

**Platform (please complete the following information):**
 - OS: ubuntu 19.10
 - Version dt: latest master

**Comment by aurelienpierre** [comment]
I think I have the same problem with global keyboards shortcuts. For example, in culling mode, to make the bottom bar appear (and get zoom scale and number of pictures options), I need to type at least twice the Ctrl+Shift+B shortcut.

**Comment by codingdave** [comment]
Well, the issue still persists. Closing an issue does not solve it ;)

**Comment by AlicVB** [comment]
@codingdave : as the Author of the issue, I really think that you should be able to reopen it...
Anyway, in lighttable rewrite process, I'm currently dealing with that part, and it seems that this code is just a leftover of a very old behavior. So I'm not surprised it doesn't work well.

I'll take care of that.

**Comment by johnny-bit** [comment]
Hey @AlicVB - where can I chekc out your current work on lighttable rewrite? It seems like a great UI/UX improvement overall :)

Another note - @aurelienpierre can bugs/issues with "wip" tag not be auto-marked with no-issue-activity (or be auto unmarked after reply)?

**Comment by AlicVB** [comment]
@johnny-bit : here : #4370

**Comment by AlicVB** [comment]
closing, now that lighttable rewrite as landed in master
