### ISSUE TITLE
exporting images with vignetting gives ugly color bands

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#3394]
**Describe the bug**
When you are using the vignetting module the fadeoff looks fine in darktable and the resulting export seems to be broken.

**To Reproduce**
1. Maybe you can validate that on your own by trying to export an image that has a vignetting effect applied.
2. You could also import the attached data
3. Look at the fadeoff in darkroom
4. Export the image as you like (JPG/Tiff, all intents, high quality resampling, vignetting dithering,  do not affect the issue)
5. Look at the fadeoff in your favorite image viewer or import it back to darktable to see the issue is not on the viewer side.

**Expected behavior**
The darktable "preview" is much nicer that the final exported result. Should be the other way around or equally good.

**Screenshots**
attached and labeled

**Platform (please complete the following information):**
 - OS: ubunut 19.10
 - Version latest dt master
![screenshot: before exporting](https://user-images.githubusercontent.com/3075641/68686480-ff3c4180-056b-11ea-945b-b3adab56f424.png)
![screenshot: detail before exporting](https://user-images.githubusercontent.com/3075641/68686482-ffd4d800-056b-11ea-9686-3c55094aa85c.png)
![screenshot: detail exported and imported back into dt](https://user-images.githubusercontent.com/3075641/68686486-ffd4d800-056b-11ea-89bf-e4dd535a3321.png)
![screenshot: exported and imported back into dt](https://user-images.githubusercontent.com/3075641/68686487-ffd4d800-056b-11ea-9592-bda2b4592883.png)
![vignetting settings](https://user-images.githubusercontent.com/3075641/68686489-ffd4d800-056b-11ea-83b6-8f116811e456.png)

**Comment by codingdave** [comment]
I can share the raw if helpful.
The xmp is here (couldnt upload xmp and so I added .jpg to the end): 

![DSC_8462 NEF xmp](https://user-images.githubusercontent.com/3075641/68688009-59d69d00-056e-11ea-88dd-844ccf54fa96.jpg)

**Comment by codingdave** [comment]
rawtherapee renders that beautifully: 
![DSC_8462](https://user-images.githubusercontent.com/3075641/68688103-8094d380-056e-11ea-8265-52abb8b837fb.jpg)

**Comment by TurboGit** [comment]
The rawtherapee rendering and the one in dt are completely different so it seems that this is expected. Please at least read the manual, for example about the dither module and corresponding option in dt vignette module. Also at least try to have the same lightness and white balance it will probably help.

**Comment by codingdave** [comment]
@TurboGit Please reopen the case (Rawtherapee was just mentioned because I wanted to see if a jpg is able to have better colors in the end):

The issue I describe is a darktable only issue. Please see the description above and the images that show that darktable export looks different than darktable preview. And not only a bit different but very wrong.

**Comment by TurboGit** [comment]
Ok well see. I'm using vignette and never seen such issue.

**Comment by aurelienpierre** [comment]
I looked at the vignette code and I didn't understand what it was about. A vignette is a simple exposure decrease blended with a circular gradient, possibly with some desaturation. The code should be 3 lines in the `for` loop, what we have is rocket science doing a cosine weighting of pixels based on their lightness (which, at this point of the pipe, is display-referred, so good luck with blending…) plus dithering that would be totally unnecessary if things had been done properly.

Just use an exposure module with -0.33 EV and a circular mask with a large feathering radius, that should do the trick @codingdave. 75% of darktable's modules could be replaced with a masked and blended exposure module anyway, if people knew how to use it.

**Comment by codingdave** [comment]
Thanks @aurelienpierre for the hint and the confirmation that I am not the only one seeing that artifact. I also think Vignetting should be a very easy problem but I might be wrong. I mean I would implement it as a linear fade out but it also could be done in a non-linear fashion. Anyhow, all ways should not end up in "eating" image information. 

I will follow your idea to use the exposure with a mask.

**Comment by TurboGit** [comment]
@codingdave : I didn't read that @aurelienpierre  was able to reproduce. And maybe this fall down again to some wrong iop order.

**Comment by TurboGit** [comment]
Just to be clear, this is very suspicious. I do and probably many people are using the vignette since years and nothing has changed in the code recently. So I don't see why "it is broken". It is maybe broken in some very specific cases but a generic report like this is always suspicious. Do you really think that dt is broken at this point in such a common module without anyone having reported here before?

So yes please also provide the RAW. I'll see if this is a very specific case. Thanks.

**Comment by codingdave** [comment]
https://drive.google.com/drive/folders/1N6Gwo73gFGiudcdWNCsys9m8KCrA30Sg?usp=sharing

Well, I do report that this happens. I did not want to say it happens for everyone always. But I can tell I have this for several images on 2 PCs running the same OS and same master dt version. So there might be something worth looking at. For me, at least, the vignetting module is unusable. 

Also from what I notice people are lazy and do not always report what they see. So it might be apparent to some lazy ones that did not share their insights.

Are you using the vignetting module s.t. some part is completely faded out to see the issue or are you only using a fraction of the vignetting? Maybe you just did not notice it yet?

**Comment by TurboGit** [comment]
To me nothing wrong. You are clipping the black by add too much vignette (far more than with the rawtherapee example). When clipping everything can happen, you are getting some banding because you probably export in jpeg with low quality <= 95% Set to 100% and you export look ok to me. Also not that dt add -0.5 in saturation something like rawtherappee probably does not do. I know you said RT was only an example.

So again to me nothing wrong here and I doubt RT with the same level of vignette and jpeg quality would do better.

**Comment by codingdave** [comment]
Hi @TurboGit 

The Issue I describe is that the image inside DT looks fine and after exporting it it looks bad. 

Please drop all RT comparisons as I will not talk about RT anymore. I wish I never had mentioned RT. :-)

I must say I was so stupid to overlook the 95% JPG setting. You are correct. I can reduce the color banding to a very nice end result by going to 100%. 

I will explore the masks now as @aurelienpierre suggested. The upside is it already supports rotation. The result is different and I will find out what I like more. 

So I can confirm that with the correct settings the color banding does disappear. 
And - btw - thanks for the good work both, @aurelienpierre for the new and clever features/fixes and @TurboGit for stemming the massive amount of MR and code reviews. Thank you very much, great work!
