### ISSUE TITLE
RC0: Splash (Intro) screen not shown

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#3402]
**Describe the bug**
The initial splash screen is not shown anymore in 3.0.RC0.

**Expected behavior**
Show splash screen like in 2.6 / 2.7

**Platform (please complete the following information):**
 - OS: WINDOWS 10
 - Version 3.0.0 RC0

**Comment by TurboGit** [comment]
I don't remember having seen a splash screen for dt ????

**Comment by Nilvus** [comment]
I don't remember having that too. And really not needed. I prefer to have directly my images when I open darktable and work as quick as possible.

**Comment by ptilopteri** [comment]
I believe there used to be an overlay window which disappeared after a time when dt was initiated.  Cannot remember when I last saw it.

**Comment by TurboGit** [comment]
I'm using dt since more than 5 years, never seen that, never crossed this in the code.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Ok, seems I'm mixing this up with gimp or so.
