### ISSUE TITLE
Size of node-circles can not be changed when option "mouse wheel scrolls sidepanel" is selected

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#3403]
When option "mouse wheel scolls side panel by default" is selected, it is no longer possible to change the size of the node-circles in the contrast equalizer, because this was also done by mouse wheel.

Feature request: Size of the node-circles should be adjustable by holding the shift key and scrolling the mouse wheel or similar. 

OS:Windows 10
Version 3.0.0 RC0

**Comment by junkyardsparkle** [comment]
With this option selected, Ctrl+Alt+scroll performs the "normal" function of scrolling. This is explained in the tooltip for this option (tooltips contain quite a bit of useful information in darktable, probably more important than in other software).

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Confirmed. Ctrl+Alt works.
