### ISSUE TITLE
Piwigo export not working on 3.0rc0 nor main branch

### ISSUE THREAD

**Issue by Gon0S** [darktable-org/darktable#3404]
When trying to export a photo to Piwigo, the process stop with the message:
[imageio_storage_piwigo] could not upload to piwigo!

**To Reproduce**
1. Go to Lightable
2. Click [Export Selected] and connect to your Piwigo server
3. Login on your Piwigo instance
4. Click export button for the selected photo
5. See error : When trying to save the rendered file, the process try to post onto the piwigo website but the process die almost in an eyeblink without futher notification

See Apache logs below to look at the Piwigo server side problem : 
77.xxx.xx.xxx - - [13/Nov/2019:00:01:44 +0100] "POST /ws.php?format=json HTTP/1.1" 200 3655 "-" "-"
77.xxx.xx.xxx - - [13/Nov/2019:00:01:45 +0100] "POST /ws.php?format=json HTTP/1.1" 200 43409 "-" "-"
77.xxx.xx.xxx - - [13/Nov/2019:00:01:47 +0100] "POST /ws.php?format=json HTTP/1.1" 200 3655 "-" "-"
77.xxx.xx.xxx - - [13/Nov/2019:00:01:48 +0100] "POST /ws.php?format=json HTTP/1.1" 500 589 "-" "-"
77.xxx.xx.xxx - - [13/Nov/2019:00:01:49 +0100] "POST /ws.php?format=json HTTP/1.1" 200 43409 "-" "-"

**Expected behavior**
Picture should be export properly into Piwigo

**Screenshots**

**Platform (please complete the following information):**
 - OS:
$ cat /etc/os-release 
NAME="Solus"
VERSION="4.0"
ID="solus"
VERSION_CODENAME=fortitude
VERSION_ID="4.0"
PRETTY_NAME="Solus 4.0 Fortitude"
ANSI_COLOR="1;34"
HOME_URL="https://getsol.us"
SUPPORT_URL="https://getsol.us/articles/contributing/getting-involved/en/"
BUG_REPORT_URL="https://dev.getsol.us/"
$ uname -a
Linux yoshimitsu 5.3.8-133.current #1 SMP PREEMPT Sun Nov 3 21:46:29 UTC 2019 x86_64 GNU/Linux

 - Version 3.0rc0 or Git main branch

**Additional context**
Piwigo version 2.10.1
Was working fine with main branch snapshot of Saturday 9th November

**Comment by TurboGit** [comment]
Since Saturday 9th November there is no change that could explain that. Can you try again with a snapshot from this date again? I suspect some external issues.

**Comment by TurboGit** [comment]
Maybe a transient issue, I just got a message from Piwigo saying that they migrated by account to 2.10. I just tested and all is fine on my side.

**Comment by leclercj** [comment]
I cannot reproduce neither. Working with me with current master

**Comment by ptilopteri** [comment]
I can export to piwigo to existing albums, but cannot create a new album while exporting as provided in the module.  darktable current master, piwigo 2.10.1

**Comment by leclercj** [comment]
That's strange. On my side I'm successful with export to existing album and also with export in a new album.
Any error message to help investigation ?
- Do you use https://piwigo.org, or run it on a hosted server ?
- Do you use http or https ?

**Comment by ptilopteri** [comment]
I run on a hosted server, http://wahoo.no-ip.org/piwigo

I can log in and I can export to existing albums (usually), but cannot export to a new album created w/darktable.  The new album never appears.

**Comment by Gon0S** [comment]
Hello all.

I guess I have something borked in my piwigo instance or the apache server... I encounter the same failures using my old laptop running DT 2.6.2 whereas it was working properly a few days ago.
I even managed to upload a pic with the 3.0rc0 tarball once, but now it does not upload anything anymore.

Sorry for the inconveniences.

**Comment by ptilopteri** [comment]
and you closed an issue "assuming" it ONLY affected you w/o regard for ensuing conversatiion.

**Comment by TurboGit** [comment]
I cannot reproduce either. I'm able to upload, create new albums, upload in old albums.

**Comment by Gon0S** [comment]
Sorry ptilopteri, but I discovered the Piwigo server (self hosted) that is plagued with the "bug" had encountered a database crash during the weekend.
Since then, the upload does not work anymore, even when using stable DT 2.6.2, or any other DT 3.0 snapshots. Tried other photomanagers that usually can upload to piwigo, and they are unable to upload to that specific Piwigo instance.

I built another instance from scratch and don't have any issue at all. I now have to rebuild/restore the concerned galleries onto the new Piwigo instance.

This is why I closed the issue, as it is from my POV a piwigo server side problem and not a Darktable issue.
Sorry for the inconveniencies, but I don't want to lure Darktable devs nor users with a "case" unproperly documented.

Regards.

**Comment by ptilopteri** [comment]
#gonOS: what was the "bug".  my piwigo instance is several years and 10s of thousands of photos, rebuilding not fun.

**Comment by Gon0S** [comment]
> #gonOS: what was the "bug". my piwigo instance is several years and 10s of thousands of photos, rebuilding not fun.

The server had a disk issue and heavily crashed with many services dead after disk repair, especially MariaDB.
The guy who manage the server did a dirty trick to restart the MySQL service, but did not check DB consistencies. Now I have strange SQL server behaviour on existing DB that have been touch by the dirty trick. I even discovered a few dead system files that had to be overwriten to recover proper execution whereas the admin told me the server was fine and running without any glitches.

About the folder creation error, DT 3.0RC0, RC1 or 2.6.x are able to do it flawlessly. Only the file upload is borked in my situation.
