### ISSUE TITLE
Intelligent copy&paste

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#3412]
To transfer the look from one picture to another I press ctrl-c in one picture and ctrl-v in the other picture (in the lighttable or in the filmstrip).

This works good with darktable 2.6.x. But with darktable 3.0.0~rc0 - uhh, ugly bad!

The reason for this is, that the "core" modules (like raw black/white point and the color profiles) are select by copy. In the target they exists twice after paste, which makes no scene.

Ok - one solution is using the mode 'overwrite' for the panel history stack. But in this case all steps in the stack will be overwritten (also crop and rotate and lens correction - for example). 

I think the better solution is an global option for an intelligent selection of the steps which are copied. This intelligent selection is already implemented in darktable, when a style is created in the darkroom (not in the lighttable). This feature only has to be used in the copy routine (and the style creation in the lightroom).

Screenshots describe better what I mean:

After copy all items are checked:
![Auswahl_221](https://user-images.githubusercontent.com/57417616/68793906-2ff4a780-064e-11ea-9129-4577cfaa1c7f.png)

After create style only the items checked, which make sense:
![Auswahl_222](https://user-images.githubusercontent.com/57417616/68793908-2ff4a780-064e-11ea-9300-5043d2eb932b.png)

**Comment by MStraeten** [comment]
You know about copying by ctrl-shift-c ?
