### ISSUE TITLE
Uniformly mask goes out of sync (RC0, RC1)

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#3415]
**Describe the bug**
Sometimes the uniformly mask goes out of sync (gui state vs processing state) or completely stops to work correctly. 

**To Reproduce**
-Go to effects group
-turn on lowpass, set mask mode to uniformly, blend mode=difference
-turn off lowpass
-turn on highpass (also happens with other modules)
-turn off highpass
-turn on lowpass again
-at this state sometimes the applied mode is "normal", but GUI still says "difference"
 or overlay slider has no effect anymore 
-sometimes several iterations of the above steps are necessary until the bug occurs

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0 RC0

![Bild2](https://user-images.githubusercontent.com/57685590/68801151-c54a6880-065b-11ea-88fe-09e14bc392c5.jpg)

**Comment by groutr** [comment]
I think I can reproduce this.
[![lowpass-bug.png](https://i.postimg.cc/FK7fqXXS/lowpass-bug.png)](https://postimg.cc/Nyvf9VMG)
What is being displayed is difference at 0% even though the gui is set for normal mode at 100%.

If I change the blend mode doesn't update the image preview, until I change the opacity.
Deactivating lowpass and reactivating/deactivating highpass and then reactivating lowpass shows the same stale blend mask (difference @ 0%), regardless of what the gui is set to.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Bug still present in release 3.0.0.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Today I had this issue with the denoise module, so the bug is not linked to the highpass/lowpass but to the mask managment in general.
