### ISSUE TITLE
Scaling Issues MacOS Catalina Macbook 13 inch

### ISSUE THREAD

**Issue by matejmarti** [darktable-org/darktable#3416]
Hello, 

I have issues with scaling with the latest 3.0.0rc0 on my 13" Macbook running MacOS Catalina. Some fonts appear huge and I can't display the complete application on my screen. 

Attached is a screenshot from dt, right after installing the rc (I used the .dmg provided on github). I've already tried deleting all darktable files under .config
<img width="1440" alt="DT_Scaling_MacOS" src="https://user-images.githubusercontent.com/46395848/68802716-b7e2ad80-065e-11ea-90c9-94aa28f1915a.png">

Any additional info I can give?

**Comment by parafin** [comment]
Should be fixed in 3.0.0rc1 which will be released soon. Please try it then and if it's still a problem, we will re-open this issue.
