### ISSUE TITLE
local contrast: wrong colors in 100% view

### ISSUE THREAD

**Issue by blitzgneisserin** [darktable-org/darktable#3418]
when using local contrast (local laplacian) with Opencl at high detail values dark colors appear too bright and all bright areas too dark at 100% view

**To Reproduce**
1. edit any photo with dark areas
2. make sure you use OpenCL
3. activate local contrast in local laplacian mode
4. pull up detail to 500% so dark areas get black
5. switch to 100% view and look at the dark areas
6. hide all tools (modules, history, thumbnails etc) with the tab key
7. unhide modules/side panels/thumbs with the tab key

**Expected behavior**
the colors should be identical at all zoom levels

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/16564210/68807871-ec5b6700-0668-11ea-9b6a-eba178a5a32b.png)
![Screenshot-1](https://user-images.githubusercontent.com/16564210/68807874-eebdc100-0668-11ea-9847-965d68831a97.png)

the screenshots are not at detail 500% but lower, probably 350 or so. It is more obvious at 500%

**Platform (please complete the following information):**
 - OS: MX Linux 19, Windows 10
 - Version: dt 3.0rc1 (MX), dt 2.6.3 (Win)

Additional info: I checked color management, I had the right screen profile, also checked with wrong/different/no profiles, same behavior

My (I am not a mathematician) guess is that this is some kind of miscalculation. Low values produce an invisible mistake, still the result is not 100% correct.

Edit: There is also a problem with light colors.

![Screenshot-7](https://user-images.githubusercontent.com/16564210/68942487-fedcba00-07a8-11ea-82bf-0a23d7f77a00.png)
![Screenshot-6](https://user-images.githubusercontent.com/16564210/68942491-00a67d80-07a9-11ea-9ecd-be2a88ba0e9f.png)

**Comment by groutr** [comment]
I think I see the same effect.  If I use bilateral grid method for local contrast, the exposure doesn't change as I zoom in. When I use local Laplacian, it gets lighter as magnification increases.

**Comment by blitzgneisserin** [comment]
@hanatos Have you noticed this?

**Comment by blitzgneisserin** [comment]
@hanatos apparently it's the tab key (I updated the description). If I hide all side panels and the thumbs I get the right preview. Is it easier to fix this now? (You know, I did not look for this... and I am sorry for being a nuisance and I'd really fix this myself if I could.)

**Comment by aurelienpierre** [comment]
Again… local laplacian is a frequency filter, its output depends on the image scale. The reference is zommed at 100%, any other zoom level is merely informative. 

Not a bug.

**Comment by blitzgneisserin** [comment]
@aurelienpierre bug or not, thank you very much for fixing!

**Comment by blitzgneisserin** [comment]
sorry, it is not fiexed. I forgot to switch on OpenCL

**Comment by blitzgneisserin** [comment]
Was something changed here? I see a different behavior now. Colors are not correct now when top and bottom "panels" are hidden at fit-to-screen view. Apparently it has something to do with the fact that the image is resized when the top and/or bottom panel(s) are visible. However, 100% view is never correct now, not even when the panels are invisible.
Using dt 3.1 git master from opensuse now.
