### ISSUE TITLE
FEATURE: Add search to the preferences dialog

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3423]
We already have a nice search for modules! It would be great to have a search in the preference dialog too. This would make it quicker for some people who already know what can be change to find it quicker.

**Comment by Haribo-66** [comment]
yes, this is a very nice idea!

**Comment by Nilvus** [comment]
Just think in that about especially having a search box for shortcut. See my closed issue #3604 related to that.

**Comment by Nilvus** [comment]
Feature request, not fullfill so needs to remain active.

**Comment by elstoc** [comment]
Search has now been added to the shortcuts section of preferences as part of #4747. This PR also splits the preferences down into more manageable chunks (hopefully) making it easier to find what you're after.

**Comment by Nilvus** [comment]
We are on working to simplify preferences as discussed in #7050, so I suggest to continue discussion in #7050 and have only one issue for preferences. A work have already been done by @phweyland but still work remains to do. I so close this issue. Hope it's ok for you @cryptomilk to continue in #7050 issue.
