### ISSUE TITLE
Search case sensitive [Bug or feature?]

### ISSUE THREAD

**Issue by sotsoguk** [darktable-org/darktable#3424]
**Describe the bug**
I am using the german version of darktable 3.0.0rc0. When i am searching a module, not all expected results are found. At least in the german version, the module names are sometimes only lowercase and sometimes starting with a capitel letter. Looking for "Farb*" does not reveal some modules which in the german version are name "*f*arb".

**To Reproduce**
1. Go to module search
2. Search for a module

**Expected behavior**
For me it would be more useful if the search function would be case insensitive

**Platform (please complete the following information):**
 - Windows 10
 - 3.0.0rc0

**Additional context**
Is there any link / guide how to contribute to the translation of darktable? I would like to fix these problems of wrong upper / lowercase words in the german translation.

**Screenshots**
![darktable_vVBxLXRIt8](https://user-images.githubusercontent.com/462611/68845278-789e7600-06cb-11ea-8a8e-d22fdbe3e7aa.png)
![darktable_yVOk48P9AT](https://user-images.githubusercontent.com/462611/68845281-789e7600-06cb-11ea-90d7-e9d18c304f40.png)

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I agree that the search should be case insensitive.

**Comment by junkyardsparkle** [comment]
Agreed, and as a side-note, I just noticed that changing the visibility of the searchbox in preferences seems to require a restart, but this isn't indicated in the tooltip.

**Comment by arigit** [comment]
+1 and I would add: can we have "Escape" clear the search text box? currently there doesn't seem to be any keyboard shortcut to clear the searchbox

**Comment by aurelienpierre** [comment]
Fixed by #4290
