### ISSUE TITLE
Tone equalizer : cursor placement question / feature

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3428]
**Is your feature request related to a problem? Please describe.**
I'm loving @aurelienpierre 's new Tone Equalizer with its new cursor over picture feature... 
But _almost_ each time I have used it, I have mistaken the cursor (aiming at the zone to be PP'ed) with the circle showing the equalization/impact
This is because the cursor shows ["effect" / aimed zone / EV]
![image](https://user-images.githubusercontent.com/3989573/68860201-5156a180-06e9-11ea-9ed8-ed51ddcb2c23.png)

**Describe the solution you'd like**
I would rather have it displayed the other way around : [aimed zone / effect / EV]
![image](https://user-images.githubusercontent.com/3989573/68860368-aeeaee00-06e9-11ea-9790-5ce70fc53142.png)
And since the EV is directly (as far as I understood) linked with the "effect" being applied, wouldn't it be more logic to have it this way ?

**Additional context**
This could be a user's customized preferences ... I'm not sure if it's related to being left or right handed, or anything else ... or if it's just me (right handed, native tongue in L2R) :-(

**Comment by aurelienpierre** [comment]
I actually find that less intuitive and graphically unbalanced, I expect the spotted area to be in the center.

That said, if more people think it would be better, I can add a custom pref somewhere.

**Comment by GLLM** [comment]
I understand your point regarding graphic balance ... yet, usually, a large mouse pointer is used at one of its ends for precise aiming.
In our case, the cursor could be _caricaturaly_ simplified as a straight horizontal line.
I would, out of habit, use the leftmost end to actually select/click (or the right if I have no choice, but not the middle).

**Comment by aurelienpierre** [comment]
The thing is the luminance mask you are spotting with the cursor is blurred, so there is no need for precise aiming anyway (or precise aiming is just an illusion in this situation).

What if I made the effect level round, circling around the cursor (Capture One-like), instead of straight and vertical ?

**Comment by GLLM** [comment]
I need to find a video or a screenshot of Capture-One to see what you have in mind ;-)

Would you be able to easily represent the fact that you, apply an under or over exposure ?


(_Oh ! and while I'm at it : thank you so much for introducing a cursor-over picture driven module ! It's a h3ll of a good novelty !! and thanks for FilmicRGB, that I still have difficulties to fully understand/use ... :)_ )

**Comment by aurelienpierre** [comment]
Here is what I mean:
![Capture d’écran du 2019-11-14 15-44-09](https://user-images.githubusercontent.com/2779157/68867268-d778e500-06f5-11ea-8686-6d0aca15ccbe.png)

**Comment by GLLM** [comment]
It looks nice(r) ! 
[teasing_mode]and does help with my issue :) :) b/c i fear i will still sometime mistakingly use the left circle, which is on the line when you start using it[/teasing_mode]

**Comment by aurelienpierre** [comment]
ok so let's see how it goes with this change, and we will change some more if it's not enough.

**Comment by junkyardsparkle** [comment]
> The thing is the luminance mask you are spotting with the cursor is blurred, so there is no need for precise aiming anyway (or precise aiming is just an illusion in this situation).

Even so, I guess it might still be a cognitive comfort for this to be immediately unambiguous to the user. I've only started looking at this module now (I wasn't sure I would have any use for what it does, but it does what it does so well that I'm re-evaluating that attitude) and I did have the same feeling as the OP at first. I suspect that putting any little hint of something resembling "cross-hairs" on the circle, even just little stubs at the perimeter, would instantly provide "this is what you aim with"... my two cents.

**Comment by aurelienpierre** [comment]
Like that ?
![Capture d’écran du 2019-11-15 13-59-57](https://user-images.githubusercontent.com/2779157/68945276-54689500-07b0-11ea-8a02-87df8ae15979.png)

**Comment by junkyardsparkle** [comment]
That's definitely clear to me! It could probably even be a scaled-down version of that and still be effective, if it would work better with the "rotary" indicator.

**Comment by todd-prior** [comment]
Cross hair looks great to me....just laughing at myself as I was not sure before which was considered to be the active sampling position...crystal clear with that change....nicely done...

**Comment by Nilvus** [comment]
@GLLM (or @TurboGit) : as this issue is fixed with #3436 PR merged 2 days ago, think about closing this issue.

**Comment by TurboGit** [comment]
Right, closing.

**Comment by GLLM** [comment]
Hi !
Sorry for being the OP and not closing the issue. I expected to close it once tested in r2 :)

Thanks all anyway !
