### ISSUE TITLE
[Vignette] Disabling vignette module does not hide the vignette mask

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3430]
**Describe the bug**

Enable the vignette module.
The default mask gets drawn on the pic.
Now disable the vignette module [module is still open], mask does not go away.
Click on the disable vignette module to close it, mask goes away.
Now click on the disabled module to open it, mask gets displayed again (remember module is still disabled).
darktable-3.0.0rc1+4~g6455c5f7d-win64

**Comment by blitzgneisserin** [comment]
confirmed (but this seems very minor to me)
