### ISSUE TITLE
[Channel Mixer] color-* preset adds colored noise

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3432]
**Describe the bug**
Using presets that are the 3 color based ones adds colored specs to any image, is that the desired effect of those 3 presets?
You may need to click on the image to see it in the larger form, I did not see the specs in the github preview pane.
![image](https://user-images.githubusercontent.com/1119439/68867332-a7dcd380-071b-11ea-84ad-fcfb7f033ed6.png)

darktable-3.0.0rc1+4~g6455c5f7d-win64

**Comment by blitzgneisserin** [comment]
I get something similar
![Screenshot-2](https://user-images.githubusercontent.com/16564210/68889348-09517200-071d-11ea-9e23-5b44c6142e4b.png)

**Comment by aurelienpierre** [comment]
Out-of-gamut issue. Ensure your black point is not too low (it would create negative RGB values) and limit the saturation in low-lights. You may also enable the hotpixels module.

**Comment by chhil** [comment]
I currently don't see this on darktable-3.1.0+342~g112559639-win64.
