### ISSUE TITLE
New Download

### ISSUE THREAD

**Issue by EdaurAfon** [darktable-org/darktable#3433]
I've just downloaded the software and it won't open. The error code is 10400. It says there's a live PID file in my system?

**Comment by ptilopteri** [comment]
command line:  ps aux |grep darktable
should provide the PID # 
kill -9 PID#

or command line:  kill -9 $( pidof darktable)

**Comment by EdaurAfon** [comment]
You're going to have to be a bit more basic than that sorry...

**Comment by ptilopteri** [comment]
don't guess I understand "bit more basic".  what is more basic than command line invocations?
open and xterm session or log into a tty and type the "command line" examples I provided and use the <enter> key

**Comment by groutr** [comment]
@EdaurAfon, that error means that darktable is already running (you can only have one instance of darktable running at a time).  You need to close the already running darktable before you can start another instance. @ptilopteri gave instructions to find and close the darktable instance that is already running.

**Comment by blitzgneisserin** [comment]
maybe killall darktable?

**Comment by moy** [comment]
In most cases, rebooting your machine will solve the issue. It's a bit of a brute-force solution, but it's probably the easiest for people not familiar with the command-line.
