### ISSUE TITLE
[Feature Request] Sea-thru Module

### ISSUE THREAD

**Issue by s83** [darktable-org/darktable#3434]
**Is your feature request related to a problem? Please describe.**
A suggestion to implement a sea-thru module for underwater photography

**Describe the solution you'd like**
Automatically remove the color cast and backscatter caused by the way light moves through a body of water, and being able to capture underwater landscapes as they would look to the human eye on dry land—in other words: if all the water were gone

**Describe alternatives you've considered**
N/A

**Additional context**
Article: https://www.scientificamerican.com/article/sea-thru-brings-clarity-to-underwater-photos1/
Research Paper: http://openaccess.thecvf.com/content_CVPR_2019/papers/Akkaynak_Sea-Thru_A_Method_for_Removing_Water_From_Underwater_Images_CVPR_2019_paper.pdf

**Comment by GLLM** [comment]
Oh ! That wasn't long before someone requested it !! :)
I saw the research presentation video not later than yesterday !!

**Comment by junkyardsparkle** [comment]
> One caveat is that the process requires distance information to work.

This seems more geared towards CV than single-camera photography. :-)

**Comment by aurelienpierre** [comment]
> Or maybe just by adding the math formula to the Dehaze Module. We already have a distance slider :)

The paper doesn't compute the distance map with a guided filter (as dehaze module does), so the implementation will be more complicated than that.

**Comment by aurelienpierre** [comment]
Reading the paper in diagonal, it seems they need different pictures of the same scene at various angles and distances from object to compute that distance map. So, again, it's more complicated than just building a new module, you need to fetch data from a set with proper spatial coordinates, mix that into a mask, then unroll the image filter.

**Comment by s83** [comment]
Thank you for your insights @aurelienpierre. This looks hard to achieve indeed.

**Comment by benelot** [comment]
I found a reimplementation with an enhancement that replaces the depth map estimation with monodepth2. I am currently trying to reproduce the results and improve on the datasets that were used to train the monodepth2 estimator. As soon as I have that, I will try to turn this into a reasonable python package, which could be integrated as a sea-thru module here. Any help with the module creation will be highly appreciated.

**Comment by ximonline** [comment]
> I found a reimplementation with an enhancement that replaces the depth map estimation with monodepth2. I am currently trying to reproduce the results and improve on the datasets that were used to train the monodepth2 estimator. As soon as I have that, I will try to turn this into a reasonable python package, which could be integrated as a sea-thru module here. Any help with the module creation will be highly appreciated.

Hello! Any progress?.. 
Very interesting in implimentation sea-thru

**Comment by benelot** [comment]
I did not get to implementing it here because I realized a significant difference in quality with monodepth2. The problem is that monodepth2 is trained on images from above sea, so its estimation is not so great below sea. But since that is its only purpose here, I thought about training it on underwater images, but then did not get to it.
