### ISSUE TITLE
Documentation request : variables available in info line & watermark

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3439]
Hi all !

I was trying to add the lens in my info line in the Darkroom module. To no avail ... tho I tried many

I couldn't find anywhere, so I resort to asking for a doc : is there or could there be a doc listing all variables usable in info line or watermark (see #3150) ?

Thanks

Edit : seems someone's also trying to find out what can be used : https://discuss.pixls.us/t/darktable-3-exif-tags/14856

**Comment by TurboGit** [comment]
In the official doc I suppose !

**Comment by GLLM** [comment]
I have indeed found _some_ doc in the export module part ... 
I expected more fields would be available $(LENS), $(COMMENT) ...

The official doc is still on 2.6 (I think, at least it's the one I found) so I believe it does not describe the info line or watermark possibilities

Sorry for the inconvenience.
