### ISSUE TITLE
motorola moto g(7) play

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#3442]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
Thank you for the sample!
This is DNG, so basic camera support is there out-of-the box.
I'm not sure what are the current up-to-date docs about lens correction, noise profile support..
