### ISSUE TITLE
[BUG] Lighttable : filters in the top bar can appear empty when scrolled + list is displayed too high

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3444]
Hi, 

I have found a GUI/display bug in darktable 3.0rc1 (Kubuntu 19.04 - OpenCL on w/ intel core i7 7700k +32GB Ram + NVidia GTX 1070)

Open darktable, go in Lighttable, make sure that the window touches the top of the screen.

Click on the _View_ filter (the one which filters based on stars/rejected status).
If you (mouse) scroll down, entries are hidden progressively, until you dont see any.

![image](https://user-images.githubusercontent.com/3989573/68966881-64e43400-07df-11ea-9858-71be81ca552a.png)

It should not be possible to make entries disappear : they should all remain visible.
The same behavior as with the keyboard arrows should be implemented : have the entries selected, and when you reach the top or the bottom of the list, jump to the other end of it ... rather than scrolling into blank lines

In addition, the list is displayed to high on the screen. The user should still see the initial filter place :+1: 

None if these issue happen with the _Sort by_ menu/filter
At you disposal if you need more details.

Thanks
G.

**Comment by leclercj** [comment]
Yes, I'm observing similar issue

This happen for me only when I first select "rejected only" or "all except rejected' which are at the end of the list. In these cases, coming back to the view filter, the drop-down selection box is displayed outside of main darktable window, and then the usage of mouse scroll down is producing the strange effect you're describing.

![Capture d’écran du 2019-11-16 11-18-51](https://user-images.githubusercontent.com/22872204/68991860-bcc47e80-0863-11ea-9a04-2209aaff00c2.jpg)

What I don't get in your case is why you don't have more space between the 'view' menu and the top of the window. Don't you have a space on the top with darktable log (on the left), then number of images in current selection (middle), then 'lighttable / darkroom / others' (on the right) ?

**Comment by leclercj** [comment]
Can also affect the 'sort by' combo box

![Capture d’écran du 2019-11-16 12-05-43](https://user-images.githubusercontent.com/22872204/68992299-d9fc4b80-0869-11ea-8a8b-2ced4e96e7ca.jpg)

**Comment by leclercj** [comment]
Minor GUI issue, but still affect current master branch

**Comment by johnny-bit** [comment]
This is actually a GTK issue that *we* can't really fix. Similar behaviour can happen for any GTK-based app and it's combo boxes. I sorta "got used to it".

See https://gitlab.gnome.org/GNOME/gtk/-/issues

and If I understand correctly, this is what's happening: https://gitlab.gnome.org/GNOME/gtk/-/issues/2793
