### ISSUE TITLE
UI glitch in History stack (Win10) in 3.0rc1

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#3446]
**Describe the bug**
History stack has extra space below for default modules than for the user added modules (Win10). This was introduced in rc1, it didn't exist in rc0.

**Screenshots**
![image](https://user-images.githubusercontent.com/5797282/68974164-bbaa3780-07f8-11ea-9f48-f958673c3ed1.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 3.0rc1

**Comment by Nilvus** [comment]
History is still a work of progress and this has already be pointed and I just propose a fix. See this PR : #3414

**Comment by Nilvus** [comment]
@TurboGit : to be closed as your #3414 PR fix this issue.

**Comment by TurboGit** [comment]
Yes, closing.
