### ISSUE TITLE
Tone Equalizer resets exposure mask

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#3447]
**Describe the bug**
In Tone Equalizer module when you open masking tab and turn the display exposure map on. The exposure map will turn off, when you make any adjustments to the sliders. If you activate another window or make adjustments in the advanced tab, the mask will stick. It's only when you work on the masking tab alone and for the first time.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version: 3.0rc1

**Comment by junkyardsparkle** [comment]
Fox for this was commited a few hours ago: 1c5371aa77919e24dbe577e6803544f295b20ffb
