### ISSUE TITLE
Export to Facebook fails

### ISSUE THREAD

**Issue by dtteufel** [darktable-org/darktable#3454]
**Describe the bug**
Export to Facebook fails with message - see attached file

**Screenshots**
![Screenshot from 2019-11-16 13-49-02](https://user-images.githubusercontent.com/54858103/68994222-66ae0600-0878-11ea-8cff-f59851e78825.png)
![Screenshot from 2019-11-16 13-56-00](https://user-images.githubusercontent.com/54858103/68994269-f9e73b80-0878-11ea-87d6-744f114a3a2b.png)

**Platform (please complete the following information):**
 - OS: Linux Mint 19 (Ubuntu 18.04)
 - Version 3.0.0rc1+8~g5a6cbdfc0
- Linux / Firefox 54: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
or
- Linux / Firefox 69: Mozilla/5.0 (X11; Linux i686; rv:64.0) Gecko/20100101 Firefox/69.0

**Additional context**
This has not worked for me in 2.6.x either.
Previously reported on Redmine 12 months ago.
Would probably be best to remove the Facebook export option if this cannot easily be resolved.

**Comment by sams96** [comment]
Facebook deprecated the api that allows this a while ago:

>  Deprecation:
>
>The publish_actions permission will be deprecated. This permission granted apps access to publish >posts to Facebook as the logged in user. Apps created from today onwards will not have access to this >permission. Apps created before today that have been previously approved to request publish_actions >can continue to do so until August 1, 2018. No further apps will be approved to use publish_actions >via app review. Developers currently utilizing publish_actions are encouraged to switch to Facebook's >Share dialogs for web, iOS and Android.

https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/

[The replacement](https://developers.facebook.com/docs/sharing/web) doesn't look like something that we can use from darktable. I will happily go though and remove the FB export option but I thought maybe someone else would want to have a look at the new API first.

**Comment by dtteufel** [comment]
Good to see taht it has been removed.
Thank you
