### ISSUE TITLE
missing refresh of tagging module

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#3456]
The tag darktable|changed is not displayed on darkroom due to a missing refresh.

**To Reproduce**
1. Clear dev history from lighttable
2. Go to darkroom
3. On the left on tagging module active the display of darktable tags
4. Activate any module

**Expected behavior**
The tag darktable|changed should have been displayed in tagging module.

**Platform (please complete the following information):**
 - OS: Linux
 - Version current master

**Additional context**
If you deselect and re-select the button to enable/disable darktable tags the tag is displayed. So it is correctly added but the tagging module not properly refreshed.

**Comment by TurboGit** [comment]
@phweyland : would you mind having a look? Thanks.

**Comment by phweyland** [comment]
>  would you mind having a look? Thanks.

I'll do.

**Comment by TurboGit** [comment]
Thanks!

**Comment by TurboGit** [comment]
Fixed, so closing. Thanks @phweyland !
