### ISSUE TITLE
Contrast equalizer: wrong colors at zoomed view

### ISSUE THREAD

**Issue by blitzgneisserin** [darktable-org/darktable#3460]
**Describe the bug**
Very dark (black) and very bright (white) areas look less dark or bright at zoomed view if luma contrast (e.g. preset clarity) is set to a high value.

**To Reproduce**
1. open a photo in darkroom
2. activate module (contrast) equalizer
2. choose preset clarity
3. switch to fit to screen view
4. increase mix until you can see black and white areas
5. switch to 100% view
6. check the black and white areas
7. switch to 200% view
8. check the black and white areas

**Screenshots**
fit to screen view:
![Screenshot-13](https://user-images.githubusercontent.com/16564210/69000015-6853ea00-08c9-11ea-8e9a-8f509d7d2ac9.png)
100% view in dt:
![Screenshot-14](https://user-images.githubusercontent.com/16564210/69000020-773a9c80-08c9-11ea-9521-4a8413c10a32.png)
100% view of the exported photo in an image viewer:
![Screenshot-15](https://user-images.githubusercontent.com/16564210/69000021-7e61aa80-08c9-11ea-9faa-a82c3974140c.png)

**Platform (please complete the following information):**
 - OS: MX Linux 19 + Windows 10
 - 3.0rc1 (Linux) + 2.6.3 (Windows)

**Additional context**
This appears to be very similar to #3418, however this time apparently there is no link to OpenCL. Maybe this second report can help to solve the first issue as well. Maybe IMPORTANT: As I change the position of the preview in 100% view, for a fraction of a second I see the right colors, although I am not sure if fit to screen/exported or zoomed in are actually correct.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I'm not able to see a brightness change when zooming.

**Comment by blitzgneisserin** [comment]
> I'm not able to see a brightness change when zooming.

Which version and which system are you using?

I am not sure, I checked my screen calibration about 2 weeks ago. Even if you cannot see it on your screen this does not mean that the difference between fit to screen and 100% or even 200% is not there.

Actually I think I'll recalibrate and check again. Anyway I have not noticed this earlier.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I'm using DT 3.0RC1 on Win10.

**Comment by blitzgneisserin** [comment]
I checked my calibrations. I checked it on my internal screen which is surprisingly an srgb-screen. And I checked on another Win10 machine. This bug is present everywhere and clearly visible at any time of the day (since light does have an influence on seeing especially very dark greys on the screen).

@c-h-r-i-s-t-i-a-n If you don't see it, maybe something is wrong with your screen? Sometimes it is hard to see the difference between similar colors. How did you calibrate your screen? Maybe you can see it in the evening or if you set screen brightness higher?

Checked with and without OpenCL, Intel and Nvidia GPUs, Win10 and MX Linux 19 with Xfce.
Screens were internal laptop screens, one sRGB (calibrated), one 60% sRGB (uncalibrated), one BenQ SW240 (hardware-calibrated and profiled with Displaycal). Screen brighness is about 120 cd/m2.

Actually I can image that it is much harder to see this in summer when there is a lot of daylight.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
@blitzgneisserin I don't have a calibrated screen, so maybe the effect is only noticable on good displays.

**Comment by aurelienpierre** [comment]
What is the position of contrast equalizer in pipe ?

It is expected that frequency filtering is scale-variant, meaning you won't get the same effect if you downsize the picture then apply the filter, or apply the filter (at full resolution) then downsize the picture (that's what the high quality export does). 

> Maybe IMPORTANT: As I change the position of the preview in 100% view, for a fraction of a second I see the right colors, although I am not sure if fit to screen/exported or zoomed in are actually correct.

What you see when zooming in/out or panning before the preview is recomputed is the stretched thumbnail (full image resized at about 1100×1100 px then processed, it's the one you see in the navigation module). 

If this thumbnail looks ok, it means you are pushing the global contrast too far. 

The reference scope to preview frequency filters (sharpen, high-pass, low-pass, contrast and tone equalizers, highlights and shadows) is zoomed at 100%. Anything else but 100% is an approximation for previewing purposes that may or may not represent the actual output.

**Comment by blitzgneisserin** [comment]
well then the fit to screen preview and the exported result in original size are wrong
As mentioned the exact same issue exists in local contrast, but not in "normal" contrast in the contrast brightness saturation module or in the exposure module

**Comment by aurelienpierre** [comment]
> well then the fit to screen preview and the exported result in original size are wrong

They are not wrong, it's expected. You need to always work at full resolution (or 1.1 zoom level)  to get a consistent result. Meaning, when exporting, you need to export with "high quality resampling" enabled. The only way around that is to always process the full size image, even when previewing, which will slow-down your computer quite a lot.

>  but not in "normal" contrast in the contrast brightness saturation module or in the exposure module

Because these modules are not frequency filters, but simple transfer functions. 

Frequency filters process every pixel by taking its neighbours into account (local contrast is "how much a single pixel stands out from its neighbours"). If you downscale a picture, you sort of average every pixel with its neighbours, so you change the relationship between each pixel and its neighbours. As a consequence, all frequency operations, because they rely on these neighbourhood relationships, will be affected.

**Comment by blitzgneisserin** [comment]
first, high quality resampling does not do anything

@aurelienpierre  aaaah I think I've got it. I get the right preview if I hide everything, all tools, modules history and film strip/thumbnails with that key whose name I don't know. Then I can unhide the history and the modules but if I unhide the filmstrip the wrong preview is there again

wrong:
![Screenshot-22](https://user-images.githubusercontent.com/16564210/69184182-a8f37380-0b14-11ea-891f-d515314724ed.png)
right:
![Screenshot-21](https://user-images.githubusercontent.com/16564210/69184183-a8f37380-0b14-11ea-9bf7-503172d0c558.png)
wrong:
![Screenshot-20](https://user-images.githubusercontent.com/16564210/69184184-a98c0a00-0b14-11ea-9d09-1bd9dfd210e1.png)
