### ISSUE TITLE
Recently used collections' saved positions are ignored.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#3461]
**Describe the bug**
When a collection in the "recently used collections" module is clicked, the light table is always positioned at the first image in the collection, ignoring the previous position as stored in the `plugins/lighttable/recentcollect/pos...` line.

**To Reproduce**
1. Open a collection.
1. Scroll to a position in which the first image in the collection is not visible.
1. Switch to another collection.
1. Click on the first collection's entry in the "recently used collections" module.
1. Note that the light table is positioned at the first image in the collection.

**Expected behavior**
The light table should have returned to the same position as it was in at the end of step 2.

**Platform (please complete the following information):**
 - OS: macOS 10.14
 - Version: 3.0.0rc1

**Comment by blitzgneisserin** [comment]
confirmed (3.0rc1, Linux)

**Comment by AlicVB** [comment]
Confirmed (and it's my fault)
I'll have a look asap
