### ISSUE TITLE
Excessive CPU usage under macOS.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#3462]
My macOS installation of Darktable, whenever the light table is the active view, regularly uses every scrap of CPU time it can get its hands on (by "Activity Monitor" metrics, running at about 1500%) for some minutes after even the slightest interaction with the UI.

An instance running on Linux with the same "CPU/GPU/memory" parameters does not exhibit this behavior. By rapidly scrolling through images I can produce a spike in CPU usage, but it falls off immediately when I stop moving the mouse.

**Platform (please complete the following information):**
 - OS: macOS 10.14
 - Version: 3.0.0rc1

**Additional context:**
Screenshot of the "CPU/GPU/memory" section of my Darktable preferences.
<img width="561" alt="DarktableCPUSettings" src="https://user-images.githubusercontent.com/3303477/69003395-f24e8380-08c6-11ea-96d2-86b5bfd6e8ca.png">

**Comment by schwerdf** [comment]
This still happens with version 3.0.0. I have not been able to stand up a working build environment for Darktable on macOS and hence cannot test the Git master version.

**Comment by schwerdf** [comment]
Yes, this is on the same hardware (although I was able to reproduce it reliably on a different macOS machine as well).
Activating OpenCL does not affect the problem ("Activity Monitor" shows no GPU usage, but the CPU usage remains abnormally high).
On further experimentation, although I was able to reproduce the problem by copying my existing database to another machine, I was not able to reproduce it reliably with a clean database. Also, I found that the high CPU usage only occurs when there is an image in the light table that has been highlighted by hovering -- whether the mouse cursor is still over that image, or whether I have switched to another application via a keyboard shortcut.

**Comment by DieGoldeneEnte** [comment]
This reminds me of #2770 (bad performance, because of sql-queries), but that should already be in 3.0 . How many images are in your library?

**Comment by schwerdf** [comment]
My recent experiments were on a library with about 500 images. I tried removing blocks of them and the CPU hogging stopped once there were less than 200 left.

**Comment by DieGoldeneEnte** [comment]
> I was able to reproduce the problem by copying my existing database to another machine

Was this a linux machine?

> I tried removing blocks of them and the CPU hogging stopped once there were less than 200 left.

Is the database maybe on a slow external drive? 200 seems way too low for performance issues.

Also could you run datktable with `-d sql` (this should work, if not I will have to look up the correct argument) and add the file? Maybe I can spot something.

**Comment by ptilopteri** [comment]
I experience the same with master on openSUSE Tumbleweed, see #4172.  Also lessened with fewer images in the library, but not really noticible until > 1k images and unusable with > 20k.  

I do not have the degradation with dt 3.0.0 with > 300k images.
