### ISSUE TITLE
open and close a picture with Darkroom kills the stack

### ISSUE THREAD

**Issue by Haribo-66** [darktable-org/darktable#3463]
**Describe the bug**
open and close a picture with Darkroom kills the whole stack
OR open a picture in darkroom and compress history within Darkroom mode kills whole history stack!

**To Reproduce**
1. Go to 'Lighttable' and press D, return from Darkroom to Lighttable and the history stack is gone forever.

OR got to Darkroom and press compress history stack and it is completely gone.

**Expected behavior**
Do nothing. Keep or compress the stack.

**Screenshots**
before pressing compress stack button
![stack before compress](https://user-images.githubusercontent.com/53818783/69006698-fdd79400-0932-11ea-8d47-5b3bea58b541.jpg)
after pressing compress stack button
![stack after compress](https://user-images.githubusercontent.com/53818783/69006699-fdd79400-0932-11ea-8c4e-634c787b7241.jpg)

**Platform (please complete the following information):**
darktable 3.0.0 rc1
Windows 10 prof. / OS Build 18362.476

**Additional context**
open a picture in darkroom and compress history within Darkroom mode kills whole history stack!

I did an intense run using "darktable-generate-cache" (~130.000 pictures) seen lots of on the fly conversions v1 to v2 and V4 to V5 and more error messages, remembered image IDs and opened some.

**Comment by Haribo-66** [comment]
I found 2 messages (warning + critical) during start up

![capture_11172019_151458](https://user-images.githubusercontent.com/53818783/69008664-721f3100-094d-11ea-9bc0-0b17b661851c.jpg)

**Comment by leclercj** [comment]
On Windows 10 I've these 2 error messages at darktable startup (1 warning + 1 critical), but I do not reproduce this issue. Hower, I not using a database migrated from 2.6 but a fresh one
Do you have same problem with fresh image in dt3.0 ?

**Comment by leclercj** [comment]
Adding @peterbud to comment on this gdbus error on Windows porting, if possible.

**Comment by Haribo-66** [comment]
I tried a separate installation, deleted the existing database (version 19) and a new one was created during start up, then I reimported a folder -> dt is working as expected now -> problem theoretically solved.

Is there any idea available to not reimport everything into an empty database?
 
Seems that there was / is (?) a bug in the dt 2.6 to dt 3 database conversion.

**Comment by peterbud** [comment]
> Adding @peterbud to comment on this gdbus error on Windows porting, if possible.

Sorry, how the gbus message is related to the issue presented here?

**Comment by leclercj** [comment]
I do not make any link with the issue presented here.
Just concerned that we are 2 different persons observing the gdbus error message, and do not understand what could be the consequences. If this is a problem, we could open a different issue for that.

**Comment by peterbud** [comment]
> 
> 
> I do not make any link with the issue presented here.
> Just concerned that we are 2 different persons observing the gdbus error message, and do not understand what could be the consequences. If this is a problem, we could open a different issue for that.

OK, now it's clear.

It seems now we need to package glib's gdbus.exe to the installer. Will open a PR separately

**Comment by jenshannoschwalm** [comment]
This pr is related to iop_order and database integrity :-(

> I did an intense run using "darktable-generate-cache" (~130.000 pictures) seen lots of on the fly conversions v1 to v2 and V4 to V5 and more error messages, remembered image IDs and opened some.

v1->v2 conversions are related to 2.6 developed images so this is not an error message but expected.

v4->v5 is more difficult to understand, it can take place if you had developed an image in a dt2.7~Sept19 git version and now reimported. @Haribo-66 Can this be the case? These images can have completely wrong histories/activated modules, there have been many issues about this.

Could you identify such an image and post the sidecar xmp file? If you know how to use a sqlite data brower it would be also very cool to look for the history entries in the database!

**Comment by Haribo-66** [comment]
> Can this be the case?

Yes I used all of the 2.7 versions from https://discuss.pixls.us/t/darktable-2-7-dev-windows-builds/12579

**Comment by Haribo-66** [comment]
> If you know how to use a sqlite data brower it would be also very cool to look for the history entries in the database!

I am having a db browser and I can see the history table, what do you want me to do?

**Comment by Haribo-66** [comment]
> Could you identify such an image and post the sidecar xmp file?

I am reimporting into a new database right know, after having access again I will upload an sidecar xmp file ...

**Comment by jenshannoschwalm** [comment]
> Yes I used all of the 2.7 versions from...

Ok, so there __could__ be really broken image histories included, most likely those with a mentioned v4->v5 on-the-fly conversion. If you can identify: xmp file plus the sql history for that image would be perfect to confirm. Here is what i would like...
![Bildschirmfoto von 2019-11-18 19-29-58](https://user-images.githubusercontent.com/50982232/69079280-ef27d480-0a39-11ea-9d54-267767e613a2.png)

If you can reproduce the loosing of history instead of compression it would help to have the xmp and raw file **before** doing the compression (i guess it will be very difficult to have the database file before compressing ...)

**Comment by Haribo-66** [comment]
all the requested files ...
[100_8224.ZIP](https://github.com/darktable-org/darktable/files/3861079/100_8224.ZIP)

![image id # 163479 after compress](https://user-images.githubusercontent.com/53818783/69100652-ecd77180-0a5d-11ea-91d1-95ef4ed6d353.jpg)
![image id # 163479 before compress](https://user-images.githubusercontent.com/53818783/69100653-ecd77180-0a5d-11ea-946d-ff57741372e5.jpg)



[100_8224.KDC.before.xmp.txt](https://github.com/darktable-org/darktable/files/3861072/100_8224.KDC.before.xmp.txt)
[100_8224.KDC.after.xmp.txt](https://github.com/darktable-org/darktable/files/3861074/100_8224.KDC.after.xmp.txt)

**Comment by jenshannoschwalm** [comment]
I tested your file using the given xmp-before, looks fine btw :-) But when clicking on history compression selecting the top line everything is ok here... cannot confirm any issue yet.

**Comment by Haribo-66** [comment]
as expected! I can not either.

It  works fine with a fresh darktable 3 database and it completely removes history with my darktable 2.6 to darktable 2.7 converted database.

Thats why I reimporting everything right now into an empty one!

**Comment by jenshannoschwalm** [comment]
So, is this really a bug?

**Comment by Haribo-66** [comment]
Really a bug, if you expect 'upgrade to 3.0 is as easy as' converting the 2.6 database (to 2.7 ? and to 3.0?) and their usage afterwards
but not really a bug if you expect every one - having used 2.7 before - to reimport from zero ...

(e.g. for myself I will need 5 days to do so and darktable stopped responding already 2 times during import)

At the beginning of writing this 'issue', I was thinking it might be possible to 'correct' the database and keep it, today I think I will finally delete the converted one after reimporting ... 

At least: Isn't it interesting to know how to start and run darktable 3, either with a clean and empty database and reimport ... or with deleting all 2.7 history stacks?

**Comment by jenshannoschwalm** [comment]
If you have used dt 2.7 there might have been many residule problems in the database that are not solvable as is, they have been fixed now. (iop_order, databse locking and many more) You can't expect a devel version to be perfectly stable. Especially large imports or generate-cache could have been **very** faulty.

What would really concern and would be a bug:
1. Any problems with pure dt2.6.x -> 3.0 conversion
2. Any sidecars with 2.6 history to be a problem in 3.0

> At least: Isn't it interesting to know how to start and run darktable 3, either with a clean and empty database and reimport ... or with deleting all 2.7 history stacks?

I know what you mean and it's interesting. But if you use a devel version you have to expect everything :-))

**Comment by Haribo-66** [comment]
Thx for your help and clarifications!

**Comment by jenshannoschwalm** [comment]
Closing this issue? Re-open if still having issues?
