### ISSUE TITLE
Fonts of darktable-elegant-* and darktable-icons-* themes are hard to read

### ISSUE THREAD

**Issue by fvollmer** [darktable-org/darktable#3466]
**Describe the bug**
The fonts used by the themes `darktable-elegant-*` and `darktable-icons-*` are very hard to read. The problem appears to be the roboto font. On widows this font is neither installed by default nor installed by darktable.

**To Reproduce**
Open Darktable and use the any non default theme (`darktable-elegant-*` and `darktable-icons-*`)

**Workaround**
Install roboto font manually.

**Screenshots** (click to view 100%)
Left: `darktable-icons-darker` theme with missing font
Right: `darktable-icons-darker` theme with manually installed roboto font
![image](https://user-images.githubusercontent.com/16699443/69012490-c8549a00-0976-11ea-8bcb-f8bdc9a05115.png)

![image](https://user-images.githubusercontent.com/16699443/69012604-de168f00-0977-11ea-9562-3fd81e2474eb.png)

**Platform**
 - OS: Windows 10
 - Version: 3.0.0rc1
 - Resolution: 1920x1200

**Comment by fvollmer** [comment]
I just tried ubuntu 19.10 and it looks different (bigger and better). I used the same PC and OS scaling was set both times to 100%. 
![Unbenannt](https://user-images.githubusercontent.com/16699443/69010858-3ba0e080-0964-11ea-8696-9e3ef988fb39.png)

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Hi,
I'm using the default theme _Darktable_ which looks okay on my Win10 Notebook.
All other themes have a somewhat thinner font which I do not like.

**Comment by fvollmer** [comment]
@c-h-r-i-s-t-i-a-n thanks. I switched to the *darktable* theme and the fonts are much better readable. I'll adjust the bug report.

**Comment by MStraeten** [comment]
Maybe this is because it seems to use segoe instead of roboto. Do you have roboto installed on your system?

**Comment by fvollmer** [comment]
Good guess! I installed roboto manually and the fonts are looking much better. Left with missing fonts, right with roboto manually installed (click for 100%):
![image](https://user-images.githubusercontent.com/16699443/69012490-c8549a00-0976-11ea-8bcb-f8bdc9a05115.png)

I guess the best solution would would be, that the darktable windows installer ships all necessary fonts. Is this still a valid bug report, or should I close is?

**Comment by Nilvus** [comment]
It was already discussed and on release notes, you could see that these themes gives best experience with Roboto fonts installed. Anyway, they propose other fonts if Roboto are not installed as darktable use default OS font. So that's not a valide issue as it is the normal behaviour. So I would said that you could close the issue. Reading at least release notes is always a good idea !

**Comment by fvollmer** [comment]
Ok, thanks!

**Comment by parafin** [comment]
Given issue #3345 and this one, doesn't it make sense to limit font list in elegant theme to just Roboto?

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Do I have to install all 13 subtypes of this font? Or only Roboto-Regular.ttf?

**Comment by fvollmer** [comment]
@c-h-r-i-s-t-i-a-n I just installed all variants. I guess one could look up which are used by the theme.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Ok, I'm finding following references in the source:

Roboto, Roboto Light, Roboto Medium, Roboto Condensed.
