### ISSUE TITLE
Darkroom: strange Artifacts while zooming

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3472]
**Describe the bug**
I work on a RAW file with DT 3.0 RC1. When I zoom in and out I suddenly see strange artifacts until the image is recalculated.

![Bildschirmfoto von 2019-11-18 00-09-06](https://user-images.githubusercontent.com/49001045/69015813-4e350d00-0998-11ea-9bf1-cc2799be89ce.jpg)
![Bildschirmfoto von 2019-11-18 00-09-10](https://user-images.githubusercontent.com/49001045/69015815-57be7500-0998-11ea-8b62-c365a14783bb.jpg)

This only happens when the 'chromatic aberrations' module is active. I've already made a blank copy of the image with just the ca module active without being able to reproduce that behaviour. Same for combinations with other modules.

Previously I edited this photo with DT 2.6.2. With DT 3.0 RC1 I made a 'virgin copy' with the duplicate manager in darkroom and started to edit.
RAW and XMP's here:
[20190731_Blüten_Takumar.zip](https://github.com/darktable-org/darktable/files/3856260/20190731_Bluten_Takumar.zip)

**To Reproduce**
1. Import RAW and corresponding XMP in DT 3.0 RC1
1. Open RAW in darkroom
1. Zoom in and out => artifacts appear 
1. Turn off the 'chromatic aberrations' module
1. Zoom in and out => artifacts do not appear

**Expected behavior**
Artifacts do not appear

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: darktable RC1 (3.0.0rc1~git11.dc641cdc9)
- OpenCL is activated, output of `clinfo`:
[clinfo.txt](https://github.com/darktable-org/darktable/files/3856278/clinfo.txt)

**Additional context**
I started darktable with `darktable -d all` and saved the output of one zoom:
[darktable_log.txt](https://github.com/darktable-org/darktable/files/3856273/darktable_log.txt)

Moreover I am not able to reproduce that with other images, If there is a XMP from DT 2.6.2 or not.

**Comment by upegelow** [comment]
This is a known issue of the underlying algorithm in the chromatic 
aberrations module. See section 3.4.4.16 in 
https://darktable.gitlab.io/doc/en/correction_group.html.

**Comment by pphotography** [comment]
Thank you, that explains the behaviour. I will close this issue in a week if nobody else has something to contribute
