### ISSUE TITLE
Framing module crash (RC1)

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#3473]
This seems to work in any image:

- switch on the frame tool in Darktable 3.0.0rc1-win64
- adjust frameline size > 0%
- adjust frameline offset = 100%
- get a crash

**Screenshots**

![Bild1](https://user-images.githubusercontent.com/57685590/69041153-4b193b80-09ef-11ea-8781-94ade5025aef.png)

**Platform (please complete the following information):**
 - OS: Windows-10 / 64bit
 - Version 3.0RC1

**Additional context**
This was originally reported on the dev mailing list.

**Comment by leclercj** [comment]
This I can reproduce easily
backtrack attached here:
[darktable_bt_FWLFB0.txt](https://github.com/darktable-org/darktable/files/3858447/darktable_bt_FWLFB0.txt)

**Comment by c-h-r-i-s-t-i-a-n** [comment]
How can I add the red label "BUG" to this issue?

**Comment by aurelienpierre** [comment]
Reproduced on Linux without OpenCL, doesn't reproduce with OpenCL

**Comment by aurelienpierre** [comment]
Preliminary report:
```
double free or corruption (out)
#0  0x00007ffff7ab3e35 in raise () at /lib64/libc.so.6
#1  0x00007ffff7a9e895 in abort () at /lib64/libc.so.6
#2  0x00007ffff7af723f in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff7afe7bc in  () at /lib64/libc.so.6
#4  0x00007ffff7b001a8 in _int_free () at /lib64/libc.so.6
#5  0x00007ffff7e26e68 in dt_dev_pixelpipe_cache_get_weighted (cache=0x34fe0b0, hash=0, size=21788832, data=0x7fffc57eb3d0, dsc=0x7fffc57eb450, weight=weight@entry=0)
    at /home/aurelienpierre/Documents/Programmes/darktable/src/develop/pixelpipe_cache.c:170
        max_used = <optimized out>
        max = <optimized out>
        sz = <optimized out>
```

Faulty line is 
```dt_free_align(cache->data[max]);```, 
yet adding
```if(cache->data[max] != NULL) dt_free_align(cache->data[max]);```
doesn't solve it.

**Comment by parafin** [comment]
Freeing NULL pointer doesn't crash. There's no need for that check.

**Comment by aurelienpierre** [comment]
How do you check for double freeing then ?

**Comment by parafin** [comment]
I don't see how this code do double freeing, because it re-allocates the buffer just after that. The only thing that comes to mind is multi-threading - if 2 threads are executing this function at the same time, there might be a race condition. Or some other code that touches the same memory pointer.

**Comment by aurelienpierre** [comment]
Sounds fun.

**Comment by leclercj** [comment]
I think I got it. I'll propose a PR later today

**Comment by leclercj** [comment]
Fixed in git master. Will be available for Windows at next delivery

**Comment by TurboGit** [comment]
Closing now.
