### ISSUE TITLE
Google OAuth - Unverified app

### ISSUE THREAD

**Issue by jcsogo** [darktable-org/darktable#3475]
Google just sent me an email saying that darktable needs to update the OAuth verification and that we've reached 60 out of 100 users allowed to use the OAuth service since the last unverified screen was shown (which I don't know when it was). More information [here](https://support.google.com/cloud/answer/7454865?hl=en)

In order to solve this, and OAuth verification form - but there are some issues that need to be solved first:

- There is a requirement to show an email address on the help page of the page. You can only choose between the own email address (the one that created the API) and a Google Group that I admin. I don't have the latter, and I don't think I will ever reply to any email to the former. This also arises other issue, which is that I am the one holding that API.
- We need to setup a Privacy Policy page in our webpage and link to it from the API page.

Anyone wanting to take the lead on this? Or we will get blocked and the option to directly upload photos to Google Photos need to be removed.

**Comment by darix** [comment]
many of those things seem to assume that we are a webservice trying to use their api.

**Comment by TurboGit** [comment]
At some point I fear all storage will be removed from dt ! It is becoming lot too difficult to maintain the stuff imposed to us by those services!

**Comment by TurboGit** [comment]
And note that we need more than that. We need to set a token on the verified domain where the given pages (privacy is one of them) are hosted. This new system seems to be done only for big company. Of course we could do that on darktable.org.... But I don't even know who is managing this domain.

**Comment by aurelienpierre** [comment]
External storages have now been removed from core and let for third-party developers to manage through Lua scripts/extensions. The reason is proprietary API are constantly changing and we don't have time to comply. 

This won't fix.
