### ISSUE TITLE
Predefined tags in DT installation, and quick apply while importing

### ISSUE THREAD

**Issue by Praveen-Rai** [darktable-org/darktable#3478]
I have a huge library to migrate to DarkTable. I wish if it came with pre-defined tags out-of-box, which i could simply apply to my photos.

Suggested solution :
Define a few tags, based on genre of photography e.g. Street, Wedding, Landscape, Kids, Portrait etc. 

Implementation Cost : 
As such the implementation cost wouldn't be much, to auto-create tags on installation. The majority of efforts for now would into finalizing the tags, and defining a standard tag hierarchy. 
But may be if we want to enhance the work-flow to let users easily apply pre-defined tags onto new imports, this could be something that might require some efforts.

Benefits : 
1. Pre-defined tags will help arrange photographs, as they are imported.
2. Will provide inspiration for the users to create their own tags.
3. These predefined tags, might also help in suggesting presets for quick development scenarios. Once we have standard tags defined, we might also promote preset creators to use them to specify which particular genres their preset out-shines, which then can be auto suggested to the users.

**Comment by aurelienpierre** [comment]
And then we will need to deal with translations…

**Comment by spaceChRiS** [comment]
There is an option to import a tag list into darktable, using the corresponding button in the tagging module. Unfortunately this is not documented, but you can get an idea how to organise an input file by exporting a tag list and analysing the file.

**Comment by parafin** [comment]
tagging module already has ability to import and export tag collections. So users can share this stuff themselves, I don't think darktable as a project should force any preference here.

**Comment by Praveen-Rai** [comment]
@parafin @spaceChRiS Thanks for bringing up the import functionality. The idea is to get an user started quickly with predefined tags. They can anyways add/edit the tags to fit their needs, while the OOTB tags will serve as stepping stones. I understand that the community users can create and share tag templates, but it still adds a step for a new user to search around for such templates. 

@aurelienpierre Thanks for bringing up the point.
