### ISSUE TITLE
Color picker -> sRBG range <> 0..255

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#3479]
**Describe the bug**
Using darktable  3.0.0.rc1+28 and the color picker, shown RGB values are outside the 0..255 range. Histogram profile = sRGB. See images.

**Screenshots**
![image](https://user-images.githubusercontent.com/19223977/69082250-01a50c80-0a40-11ea-80ea-df702ecdb28c.png)
![rgb](https://user-images.githubusercontent.com/19223977/69082271-0bc70b00-0a40-11ea-8322-f5aeadce229b.png)
![Lab](https://user-images.githubusercontent.com/19223977/69082278-0ff32880-0a40-11ea-9dfb-676a4c1a52b5.png)

**Platform (please complete the following information):**
Present version Manjaro/KDE

**Comment by vsz1lu** [comment]
confirmed, if sRGB is the histogram profile

(Ubuntu 19.10 / GNOME 3.34.1)

**Comment by wpferguson** [comment]
You can also get negative values with linear Rec709 RGB,  Should the negative values be clamped at zero, or is there a conversion problem?

**Comment by wpferguson** [comment]
I have a photo printer evaluation image with a prophoto color profile.  I opened it in GIMP and used the color picker to select colors and got out of bounds (less than 0, greater than 255) on the rgb scale.  This was also the image I was using to test this report.  Converted the prophoto color profile to srgb and saved as s jpg.  Got different values, but still out of bounds.  I included the jpg.  Here's a link to the tif

![PrinterEvaluationImage_V002_ProPhoto](https://user-images.githubusercontent.com/1634891/69569264-47eff380-0f8b-11ea-81ae-11c2dc08dad9.jpg)

https://drive.google.com/file/d/10ekU6k_iqDxxEuQ4uN2RouoN9azVAII_/view?usp=sharing

**Comment by wpferguson** [comment]
The bright colors seem to be the worst.  I used the color ramps and color patches to get the out of bounds values.

**Comment by wpferguson** [comment]
Also tested on 2.6.2.  Didn't get out of bounds values, but did get different values between the sRGB and ProPhotoRB profile images (which I expected).

**Comment by wpferguson** [comment]
@aurelienpierre could you take a look at this if you have time?  Or if not, could you point me in the right direction?

**Comment by aurelienpierre** [comment]
@wpferguson I'm not familiar with how the measurements are taken and where in the pipe. I need to look at the code, it will take some time.

**Comment by wpferguson** [comment]
38e361f28 introduced negative numbers and values greater than 255 for RGB values.  It did fix the color that you pick is the color that shows up in the color picker module.

**Comment by wpferguson** [comment]
Okay, I think I've figured it out.  When the color patch is drawn, the rgb values are CLAMPed between 0.f and 1.f.  When the rgb value string is printed the unclamped values are multiplied by 255.  So, if we need to CLAMP the values to get the correct color to display, then we should CLAMP the values to get the correctly printed values.

**Comment by aurelienpierre** [comment]
I wonder if we shouldn't let the values unclamped so gamut and dynamic issues get easier to debug. Seeing 255 is not going to alert people, if they see 400, they might get a sense something is wrong (and the out-of-gamut alert does not say how much it is out of gamut). Since the histogram profile can now be changed, that doesn't seem an issue to me.

**Comment by wpferguson** [comment]
You definitely have a point.  We could just update the documentation to say that values greater than 255 or less than 0 are out of gamut.  @TurboGit, thoughts?

**Comment by TurboGit** [comment]
I still prefer to display clipped values (consistent with histogram) and have a tooltip to show unclipped values. See  #3653 which should please every party :)

**Comment by aurelienpierre** [comment]
Tooltips don't pop-up in your face though. I quite like having something to nag you as soon as you do something stupid (because people don't know what's stupid or not otherwise).

**Comment by TurboGit** [comment]
Agree it don't pop-up, but most people gets confused by those out of bound values. When you have some values set to 255 and the histogram on the right you pretty know that you're clipping. The tooltip will tell you how much. As I said a compromise.

**Comment by aurelienpierre** [comment]
Histogram doesn't show gamut clipping though. Pixels having valid values on 2 channels and an outlier on the third will still look ok on the histogram.
