### ISSUE TITLE
[Feature] Crop & rotate module : display grid when using key+mouse accel

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3481]
Hi all !

In the Crop & rotate section of my shortcuts,, I have set a dynamic shortcut, so that I can correct my horizon by just pressing the key r and scrolling with my mouse !
It great, and I love those dual key+mouse accels (which configurability is missing in some module ;) )

I would really love that the grid defined in my Crop & rotate module is displayed when using this key+mouse accel ... it is not as of v3.0rc1 !

This way, I can correctmy horizon with a keypress + a mouse, without even having to care about the module itself !

Thank you

**Comment by vsz1lu** [comment]
I think an constant (on/off by shortcut and/or a small button) grid over the preview in the darkroom would be more practical.

**Comment by elstoc** [comment]
#5041 now gives the ability to switch the grid on and off by giving gui focus to the crop & rotate module. You can do this via a keyboard shortcut or by control-clicking on the enable module toggle button. Given that some people want gridlines on and some people do not, I think this is probably the best solution and I will close #4608. You can commit your changes by removing gui focus from the module again, using the same shortcut or control-click.

@GLLM please can you close the issue if you are happy with this solution.

**Comment by GLLM** [comment]
Hi @elstoc 
As a matter of fact, I can now, using shortcut enable the grid (C (my config) set focus on the Crop module) before I use by accel (R (my config) + mousewheel) to rectify my picture's angle.

It's still one more shortcut than in my craziest  wild wish ... I'd have the angle action make the grid visible visible as soon as I press 'R'

But fair enough : I'll close it :-)

Thank you for the work & commit enabling this !!
Appreciated :+1: 

GLLM
