### ISSUE TITLE
[Feature] Basic adjustment module : enable dynamic (key+mouse) accels

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3482]
HI all !

I love the new Basic Adjustment module (#2168), and use it to adjust :
* Black level
* Exposure
* Contrast
* Brightness
* Saturation
* Vibrance to come in #3121

![image](https://user-images.githubusercontent.com/3989573/69091407-83019c80-0a4a-11ea-8806-5df50ee7b085.png)

I would really love to be able to set Dynamic shortcut for each of those entries so that I can adjust them using accels, i.e. a simple keypress + mouse scroll U/D without having to go on the sliders in the module.

![image](https://user-images.githubusercontent.com/3989573/69091866-7c275980-0a4b-11ea-9a2d-21f0c607bfd0.png)

(This FR could probably apply to maaaany modules ;) )

Thanks
GLLM

**Comment by dterrahe** [comment]
I'm happy to pick this up. Already added accelerators for the basic adjustments module, but will hold off posting a merge request until I've included the other modules with missing accelerators.

**Comment by GLLM** [comment]
> I'm happy to pick this up. Already added accelerators for the basic adjustments module, but will hold off posting a merge request until I've included the other modules with missing accelerators.

\o/

**Comment by TurboGit** [comment]
@dterrahe : Thanks !
