### ISSUE TITLE
Color look up table - color picker difficult to invoke

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#3483]
**Describe the bug**

To make the Color look up table's color picker to function (i.e. to select/mark a suitable swatch),
one most often has to minimize + maximize the module (by clicking on its headline) one of more times. After that it works OK. (Just turning it on/off is not sufficient.)

**Platform (please complete the following information):**
darktable 3.0.0rc1+28
latest Manjaro/KDE

**Comment by wpferguson** [comment]
I was able to recreate with git 3.0rc1+52.  Open an image, open color lookup table, click the color picker then click in the image.  I clicked all around the image selecting different colors and the patch never changed.  I collapsed the module with the color picker active, then expanded it again and the correct color patch was selected.  From that point I could select different colors and see the resulting patches displayed.

I checked in 2.6.2 and the color picker in color lookup table worked correctly.

@TurboGit I'll play with it and see if I can figure it out.  

It might have to do with line 1188 in src/iop/colorchecker.c changing from 

darktable.gui->reset = 0;

to 

darktable.gui->reset = reset;

**Comment by wpferguson** [comment]
1188 wasn't it.  Still playing.  I'm not sure what happens, code wise, when you collapse a module then expand it again, but that makes the color picker work.

**Comment by ClaesGitHub** [comment]
Thank you for looking into this.
An odd thought: might it have something to do with a forced (?) screen update?

**Comment by wpferguson** [comment]
If I force a gui update it works correctly, but I'm not sure that's the correct way to fix it.  It was working correctly in 2.6, so I need to figure out what changed that made it stop working.

 Also, the color picker doesn't turn off when the module is turned off.  And, when white is selected the outline is white so you can't tell white is selected.

**Comment by wpferguson** [comment]
PR 3530 submitted
