### ISSUE TITLE
darktable-cltest -> segfault

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#3488]
**Describe the bug**
dt 3.0.0rc1+38-gc37eb813f

The cmd darktable-cltest results in

> [Inferior 1 (process 15910) detached]
> backtrace written to /tmp/darktable_bt_FF2PB0.txt
> Segmentation fault (core dumped)
> 

[darktable_bt_FF2PB0.txt](https://github.com/darktable-org/darktable/files/3864587/darktable_bt_FF2PB0.txt)

**Platform (please complete the following information):**
Latest Manjaro/KDE
Ryzen 3900X/GTX-1660Ti /Nvidia driver

The darktable version as of yesterday (3.0.0rc1+28) worked OK in this context.

**Comment by ptilopteri** [comment]
confirm on openSUSE Tumbleweed 20191116, dt 3.0.0rc1~git37.841120d5e

including bt 
[darktable_bt_NGGNB0.txt](https://github.com/darktable-org/darktable/files/3864949/darktable_bt_NGGNB0.txt)

**Comment by peterbud** [comment]
This was probably the only change in this timeframe which is relevant: https://github.com/darktable-org/darktable/commit/841120d5e0f357543d2bf8cd8fbf3cfe8b5de56b

Do you see any piece which could cause this?

**Comment by ptilopteri** [comment]
I am not competent to advise.  I only know that something causes darktable-cltest to segfault on my system from current git master version of dt on my system.

tks

**Comment by jenshannoschwalm** [comment]
can confirm the crash, my log
[test.log](https://github.com/darktable-org/darktable/files/3865335/test.log)

**Comment by TurboGit** [comment]
My fault :( Will fix.

**Comment by TurboGit** [comment]
Fixed.
