### ISSUE TITLE
Artefacts with shadows and highlights

### ISSUE THREAD

**Issue by mhechthz** [darktable-org/darktable#3490]
Hi,

with darktable 2.6.3 on windows 10 on some jpeg files from a sony alpha 6400 I get terrible jpeg artefacts with shadows and highlights in default settings. I attached a file "enhanced" by gimp to make the bug better visible. If necessary I can also add (the much bigger) original jpeg.
![DSC01314](https://user-images.githubusercontent.com/37075144/69175171-8c9b0b00-0b03-11ea-9f16-9a73006ea0fa.jpg)
Without shadows an highlights all works well.

**Comment by vsz1lu** [comment]
I saw similar results with other 8bit images. Maybe it will solving your problem:

https://darktable.gitlab.io/doc/en/correction_group.html#dithering

**Comment by mhechthz** [comment]
Hmmm ... I've never noticed this with versions before 2.6.3. So, was there a change in algorithms or was this only by chance?

**Comment by vsz1lu** [comment]
@mhechthz 

I can reproduce the effect with an built-in jpeg from a raw (Nikon D7000), but dramatically slighter and hardly detected by eye with dithering.

original:
![142231-D36551-00](https://user-images.githubusercontent.com/57588193/69182688-ce32b280-0b11-11ea-8372-a268ac8663a9.jpg)

dt3.0.0rc1 default shadow and highliths:
![142231-D36551-00-dt_300rc1_export](https://user-images.githubusercontent.com/57588193/69182893-32ee0d00-0b12-11ea-86f5-9e8c6c6bac62.jpg)

dt3.0.0rc1 default shadow and highliths + default dithering:
![142231-D36551-00-dt_300rc1_export_with_dithering](https://user-images.githubusercontent.com/57588193/69182931-439e8300-0b12-11ea-8bf6-90fa5302119c.jpg)

**Comment by mhechthz** [comment]
Ok, it is like this. So I have to apply dithering for comparable scenes in future. Working with RAW for thousands of pictures is definitely no alternative.

Thank you.

**Comment by johnny-bit** [comment]
Unfortunately that's a limitation of: using jpegs + very delicate gradients and on top of that shadows&highlights is a Lab module... So as a workaround use dithering or work on RAWs (disks several TB of space now cost pennies ;) (rotating ones that is) ) & use modern workflow with soon to come dt 3.4 :)
