### ISSUE TITLE
[Feature] Renaming multiple instances of modules by double click action

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#3491]
All in the tittle. I think this simple and great future make more comfort and speed up the working with multiple modules.

**Comment by johnny-bit** [comment]
That would be confusing though. My workflow depends on being able to read name of module. and modules shown in pipe-order help too. If you mean things like multiple instances of module and naming purpose of instances then I'm ok with that.

**Comment by vsz1lu** [comment]
@johnny-bit Yes! I changed the title for clearing.

**Comment by elstoc** [comment]
I went with shift-click because it's easier than double-click. Hope that's ok.

**Comment by shiro** [comment]
Just my 2 cents, but I think double clicking sounds way easier than shift-clicking.

**Comment by elstoc** [comment]
I agree it is easier from a user perspective but I can't work out how to code it, so I chickened out and went for the simpler option.

Unfortunately the callback function that the mouse-click uses executes twice when you double-click. The first click executes the normal action (collapses/expands the module) and doesn't know about the second click until the second time it's called. If someone can suggest a tidy way to code a double-click action I'm all for it.
