### ISSUE TITLE
UI - some more typos

### ISSUE THREAD

**Issue by mlales** [darktable-org/darktable#3492]
**Describe the bug**
1. graduated density: Missing space between value and ev (should be EV).
    Similar problem was already solved in #3342

![Graduated density ev](https://user-images.githubusercontent.com/56188259/69182089-9bd48580-0b10-11ea-955d-1df99e9c8bb2.JPG)

2. grain: Missing space between value and ISO

![Grain ISO](https://user-images.githubusercontent.com/56188259/69181712-e4d80a00-0b0f-11ea-8eab-a0b779933a29.JPG)

3. white balance: Missing space between value and K

![WB Kelvin](https://user-images.githubusercontent.com/56188259/69181836-249ef180-0b10-11ea-8f74-1fdbe1438644.JPG)

4. lens correction: too much space between text and value, for example as if 21 belongs to f/

![Lens correction focal length](https://user-images.githubusercontent.com/56188259/69182431-477dd580-0b11-11ea-9d20-ee5d954e07f3.JPG)

5. I also noticed missing space between value and % in the following  modules which   affects readability: bloom, color mapping, exposure, framing,, graduated density, grain,
highpass, lowlight vision, shadows and highlights, soften, vibrance, vignetting, watermark.
One example:

![Framing](https://user-images.githubusercontent.com/56188259/69183459-55345a80-0b13-11ea-83db-299e9ce0f5ba.JPG)

This is OK:

![Filmic RGB OK](https://user-images.githubusercontent.com/56188259/69183832-ff13e700-0b13-11ea-8004-19dd1c313fb7.JPG)

**Comment by vsz1lu** [comment]
yes :)

addition:

In the lens correction the 'mm' is unit not type. the type of the first value is 'Focal length'. Or 'F' but it's easily confusable :) so if we want precise: 'Focal length: 21mm'
