### ISSUE TITLE
EXIF data still missing from webp exports

### ISSUE THREAD

**Issue by kelna** [darktable-org/darktable#3493]
**Is your feature request related to a problem? Please describe.**
No EXIF data in exported webp files.

**Additional context**
I opened an issue regarding this (#2768). It was closed, but the issue wasn't resolved and no explanation provided. Actually, there was a commit regarding this, but the fix does not work and the issue is ongoing. I felt I need to open a new request as there was no reply to my question for months.

**Comment by sams96** [comment]
Which version are you using? I don't think that commit made it into 2.6.3

**Comment by wpferguson** [comment]
It works in 3.0RC1+62.  You should see it around Christmas

**Comment by kelna** [comment]
Very good, thanks for the heads up!
