### ISSUE TITLE
darktable-generate-cache --help needs improved details

### ISSUE THREAD

**Issue by Firstyear** [darktable-org/darktable#3494]
**Describe the bug**
When using darktable-generate-cache, the help is extremely sparse:

```
darktable-generate-cache --help
usage: /Applications/darktable.app/Contents/MacOS/darktable-generate-cache [-h, --help; --version]
  [--min-mip <0-7> (default = 0)] [-m, --max-mip <0-7> (default = 2)]
  [--min-imgid <N>] [--max-imgid <N>]
  [--core <darktable options>]

When multiple mipmap sizes are requested, the biggest one is computed
while the rest are quickly downsampled.

The --min-imgid and --max-imgid specify the range of internal image ID
numbers to work on.
```

For example, is a min-mip the large thumbnail? Or is it the small one? What's the best way to run this command if I have thumbnail rendering performance issues or a large import? How can I find what the darktable core options are?

These would all be helpful details to improve the use of this command. 

**Expected behavior**
Help from the command should help to guide you in using the command better and why you may want to use it.

**Platform (please complete the following information):**
 - OS: MacOS
 - Version 2.6.x

**Comment by TurboGit** [comment]
https://darktable.gitlab.io/doc/en/overview_chapter.html#darktable_generate_cache_commandline_parameters

**Comment by Firstyear** [comment]
Sorry, this is not a constructive or appropriate response.

That URL is not in the --help output of the tool. You can not assume people will be able to find it via a search request. This means you need to improve the --help output.

Additionally, the link shown also does *not* answer the questions I have presented here.

Please re-open this, and really consider the user experience.

**Comment by jenshannoschwalm** [comment]
You could read the manual...

**Comment by Firstyear** [comment]
I had to read the *source code* followed by testing what the different mip levels actually emited by analysing the resulting jpgs. The manual does not include the information I requested. I'm trying to say you need to improve your communication here around these concepts because it's unreasonable to expect everyone to have that level of ability when interacting with your software.

**Comment by TurboGit** [comment]
Then please propose a text to be more explicit. A patch and a PR would be welcome too. Thanks.
