### ISSUE TITLE
Setting memory-in-mb-for-thumbnail-cache causes performance loss

### ISSUE THREAD

**Issue by Firstyear** [darktable-org/darktable#3495]
**Describe the bug**
On a machine with a large quantity of ram (32GB), setting the thumbnail cache memory in mb to a higher value (default 256mb, set to 1024 or higher) causes extreme performance loss.

**To Reproduce**
1. Go to 'gear icon'
2. Set core option memory-in-mb-for-thumbnail-cache to a high value (8192 is an extreme example)
3. Restart
4. Import a large set of photos (say 1000~)
5. Set the viewer to single image (1)
6. Start iterating through images - they take a long time to render but then are in memory so they are "faster" when you go back
7. Restart darktable
8. iterate over the images from the start again - they begin to render again.

**Expected behavior**
Image viewing should be fast: generally images take 3 seconds to load per image (jpg source 6000x4000)

**Platform (please complete the following information):**
 - OS: MacOS
 - Version 2.6.3

**Additional context**
I suspect from a brief reading of the way that darktable-generate-cache works, that the issue may be that the image cache in memory when set to a large value never evicts the renders to disk, which means on a restart they begin to be regenerated instead into memory. This causes each restart to have to re-render all thumbnails when you set a high memory amount.

There are maybe some ways to potentially improve (from a naive viewpoint)

* pre-heat the cache in memory by reading disk items to the memory cache for the current selection (not just whats on screen, but as much as would fill the cache for the spatial close items forward and back)
* have the memory cache evicted on shutdown similar to how darktable-generate-cache works instead of discarding it.
* keep more thumbnail preview levels in the disk/memory cache (rather than just the large size) to prevent cpu rendering if possible.
* more aggresive background generation of thumbnails

**Comment by AlicVB** [comment]
You say that this happen when you set nb of images to 1, right ?
In this case, if you have a big screen res., dt may have to load full image, and this can take time ! In order to be sure that your full preview is cached too, there's a new entry in prefs (don't remember exactly the wordings) be sure to use it !

Now to see if your image is cached, you can just browse darktable image cache directory. You'll see subdirs with numbers. check for the higher ones.

**Comment by Firstyear** [comment]
That's not correct. I have nearly 50,000 images in my database. The issue is the images-in-cache-mb (megabytes) setting.

What is occuring is that when that cache-mb value is high, the previews are never written to the image cache directory you are referring too. This means the only way to have reasonable performance is to pre-render them all with the darktable-generate tool. 

Hope that clarifies it.

**Comment by AlicVB** [comment]
Well, I've tried what you said (on Linux) but can't reproduce.
Can you please share some more infos :
- what is your screen res.
- post your darktablerc file

and do a test to be sure : 
- locate your cache dir. and rename it (to have a backup)
- open darktable and browse some images with the exact steps you propose in first post
- close darktable
- in your newly created darktable cache dir, check the subdirs with numbers 1->7
- in which ones do you see the image browsed in darktable ?

**Comment by Firstyear** [comment]
I have two 1920x1200 monitors, darktable is only on one of them.
[darktablerc.zip](https://github.com/darktable-org/darktable/files/3913491/darktablerc.zip)

I did the cache dir rename and, close and restart.

I see a lot of files in: folders 2, 3, 4. 

Saying this, the browsing experience is still extremely slow

**Comment by AlicVB** [comment]
My bad, I've read to quickly. You're on 2.6.3, so there's no such full preview cache pref... Sorry.
There has been a lot of changes and fix in this area for 3.0. Can you, by any chance, test if you can reproduce on current 3.0 RC ?

**Comment by Firstyear** [comment]
3.0.0rc1 seems much better :)
