### ISSUE TITLE
missing hints when adding shapes

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#3497]
**Describe the bug**
Missing hints when adding shapes

**To Reproduce**
1. Open any raw file in darkroom mode.
2. Open mask manager
3. Add any shape
4. No hints displayed on top of windows about shortcuts

**Expected behavior**
Hints about way to resize, change opacity... should be displayed as in 2.6.

**Comment by wpferguson** [comment]
I tried to recreate this and couldn't with git 3.0rc1+29, git 3.0rc1+52, and the po/fix-order-multi-inst branch.  I tried an image with existing masks and an image with no masks so that I had to create them.  In both cases hints displayed fine.  I tested all shapes, and all worked fine.

**Comment by TurboGit** [comment]
Yes, seems to work indeed. This was reported to me and I probably did something wrong when testing or expected a hind where none was present.

For example when you click on a circle in the drawn mask wasn't a hint displayed before creating it? I'm not sure... I'll try to find a 2.6.x install to test.

**Comment by wpferguson** [comment]
I still have 2.6.2.  In mask manager I clicked a circle and no hint was displayed until I clicked on the image to create the shape.  Once the shape created the hints were displayed when the shape was selected.

**Comment by TurboGit** [comment]
Ok, thanks for testing. Closing this and I'll wait for more information then.
