### ISSUE TITLE
Failure to apply lens correction on import (+cause +reproducible)

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#3502]
In a certain usecase Lens correction and Denoise are not applied on import. 
It is unfortunately not possible to re-do the import because DT stores these settings in its database - but I found a (not preferable) workaround.

Usecase:
I import and organise my photos in Digikam.  I import my photos there.  On tagging or applying geolocation, digikam will write an XMP file.

Then I import the files/folder in Darktable.
Darktable imports the image file.
Darktable reads the XMP file.  
There are no lens corrections / denoise-settings in the XMP file and Darktable does not apply any. 

Then I realise my mistake. I exit Darktable.
I delete all the XMP files. 
I open Darktable again. Doh! Darktable has a backup of the data in its database and still does NOT apply lens-correction or denoise.

It has now become impossible to apply lens correction/denoise on this group of images as DT does on import. 
Workaround: Exit DT. Delete the XMP files. Delete the database. Open DT and re-import the files.

Preferred solution: I would like an option to re-import the files as if they were imported for the 1st time, ignoring the database info.

**Comment by ptilopteri** [comment]
delete subject xmp files
open darktable, select the mis-handled files 
choose "selected images" -> "remove" and "yes"
select "import"
choose subject images
import

you should now be able to apply noise corrections. 
btw: YOU must choose to apply denoise and/or lens-correction in some manner

**Comment by ptilopteri** [comment]
and if this satisfies your use-case, please close this issue.

**Comment by rekcodocker** [comment]
It works.
Problem was then the word 'collection' - as this might easily refer to the collection of images on my harddrive, I would not want to 'remove' it. 
But I understand from your post that this only refers to the Darktable concept of a collection, not the actual files on the harddrive.
Thanks.

**Comment by parafin** [comment]
@rekcodocker, have you created auto-applied presets for lens correction and denoise? because otherwise they aren't applied automatically on any imported images. If so, I think this is a valid bug, specifically that these presets aren't applied if XMP file exists, but created not by darktable.
