### ISSUE TITLE
Change in preference dialog not immediate for gui-options->"position of infos line" (refresh issue)

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3504]
**Describe the bug**
If you are in the darkroom view and you change the preference for "position infos line", close the preference dialog, the information is still at the previous position.

Work arounds
Go to lighttable view and come back to darkroom and the info line position is updated.

If you change the preference in the lightable view and then go to darkroom, the position is correctly updated.

Win 10, darktable-3.0.0rc1+44~g9534ab08d-win64

**Comment by chhil** [comment]
The text  "infos"  doesn't sound right, maybe change it to "info"?

Singular and plural are both "information".

**Comment by TurboGit** [comment]
Right and won't change that.

**Comment by TurboGit** [comment]
I mean not possible.
