### ISSUE TITLE
Support for Dual Demosaicing (e.g. 3-pass+fast and AMaZE+VNG4)

### ISSUE THREAD

**Issue by SZim92** [darktable-org/darktable#3513]
Last year RawTherapee added support for "[Dual Demosaicing](https://rawpedia.rawtherapee.com/Demosaicing#Dual_Demosaic)", which uses two different types of demosaicing on the same image, with each type being used on the parts of the image that it would work best with.

This feature has been very well received on RawTherapee, and it would be great to see Darktable add it as well. In particular, the feature has been well received in the 3-pass+fast (Markesteijn) implementation on X-Trans sensors (as it helps with noise performance on flat areas). [AMaZE+VNG4](https://discuss.pixls.us/t/combined-amaze-and-vng4-demosaic/7897), RCD+VNG4, and DCB+VNG4 have been well received on Bayer sensors as well.

**Comment by PeterWem** [comment]
Anything new about this? It would be great with AMaZE+VNG4 to smooth flat areas and sharp details.

**Comment by johnny-bit** [comment]
In #6500 @soupygit and @jade-nl expressed interest in seeing this implemented :)

**Comment by rgo** [comment]
@johnny-bit this one can be closed, it has been implemented here : https://github.com/darktable-org/darktable/pull/7981

**Comment by johnny-bit** [comment]
Indeed it has! :)
