### ISSUE TITLE
UI → helper hints are missing in dt 3.0rc

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3515]
Steps to reproduce:

1. Open any raw file in darkroom mode.
2. Open mask manager or spot removal tool
3. Add any shape

Problem:

dt 2.6 was giving useful hints top of the window about shortcuts,
feathering size changing and so on. dt 3.0rc shows nothing. Same
problem can be observed in retouch module, spot removal.

Looks like whole piece of that interface responsible for hints is not
working.

Screenshots for comparison:

![screenshot](https://user-images.githubusercontent.com/58066490/69407490-a3b14700-0d15-11ea-9bd7-6c950eb51106.jpg)
![screenshot_2 6](https://user-images.githubusercontent.com/58066490/69407502-a90e9180-0d15-11ea-8aad-1a74a2ed97b0.jpg)

**Comment by TurboGit** [comment]
Works on my side, really strange.

**Comment by timur-davletshin** [comment]
> Works on my side, really strange.
Have you tried to run with empty profile?
P.S. I use Debian stable, no backports, builds from: 
https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

**Comment by wpferguson** [comment]
Just checked latest git 3.0rc1+62 and could not reproduce.  Started with fresh install and empty config directory.  Opened image, opened mask manager, created shape, saw hints.

Is your top panel collapsed.  Never mind, just tried that and it still works.  Perhaps it's the build?

**Comment by timur-davletshin** [comment]
Can anyone else try those builds? They are kinda "official".

**Comment by timur-davletshin** [comment]
> Works on my side, really strange.

I found what has changed after comparing 2.6 and 3.0 (or at least the way it works for me) — hints in 2.6 appear as soon as you choose tool but in 3.0 you need to click on the edited image for hints to appear. This hints message is not going away even if I close module which produced it. It stays until something else rewrites it.

For me it looks like UI refresh issue.

**Comment by TurboGit** [comment]
But on my side, even with 2.6 I don't have the hint before creating the shape.

**Comment by timur-davletshin** [comment]
I just select shape in module, hover it over picture and see hints. No clicks. Seems pretty logical to me to show hints this way from usability standpoint.

**Comment by wpferguson** [comment]
> I just select shape in module, hover it over picture and see hints.

I just tried 2.6.2 and 3.0RC1+85 and they work the same.  Select a created shape from mask manager then hover over the shape in the image and the hints are displayed.  For me, both versions work the same.

**Comment by timur-davletshin** [comment]
@wpferguson I'm unlucky to have 2.6 working in a more logical manner. dt 3.0 requires clicking on image and probably creating shape which user will have to remove later because he didn't get proper information from hints. This is what I showed on screenshots.

**Comment by wpferguson** [comment]
@timur-davletshin 2.6 and 3.0RC1+85 work exactly the same, for me.  There is no difference.

I'm running Ubuntu 18.04 with 3.0.0rc1+85~g3d6a29f8b built this morning.  The other version of darktable is 2.6.2 from Pascal's PPA.

**Comment by timur-davletshin** [comment]
@wpferguson I insist that this behavior is buggy and I get 100% reproduction on two Debian systems. One Intel, another Nvidia videocard (proprietary drivers).

**Comment by jenshannoschwalm** [comment]
Ok, i tested and can sort of reproduce the described problem.

It#s best seen when using a more complicated/larger brush as mask. When moving the mouse over it
1. The mask is not always highlighted
2. The info on top seems to be written but is removed immediately.
3. CL activated or not doesn't matter.

For me it looks like a timing issue.

**Comment by timur-davletshin** [comment]
Additional info: liquify module hints work as expected — they appear as soon as I select tool. Which proofs that problem is in darktable mask module.

**Comment by TurboGit** [comment]
Not really a proof as the masks in liquify are not handled as other masks.

**Comment by timur-davletshin** [comment]
I'm telling that mechanism of how those hints are shown is failing somewhere in mask module. I doubt that this is my gtk-related issue.

**Comment by timur-davletshin** [comment]
Just to illustrate difference.

Screencast with 2.6:
[dt 2.6.zip](https://github.com/darktable-org/darktable/files/3906800/dt.2.6.zip)

Screencast with 3.0
[dt 3.0.zip](https://github.com/darktable-org/darktable/files/3906801/dt.3.0.zip)

Notice hints appearing only after adding first shape in dt 3.0. While 2.6 shows them just after tool selection.

**Comment by TurboGit** [comment]
Looks like my fault... I'll fix that.

**Comment by timur-davletshin** [comment]
@TurboGit 😄. Maybe, if have enough time, you'll take a look at #3514. Darktable 3.0 changelog claims "color picker support has been fixed by a complete rewrite" on very first place in bug fixes. But described behavior looks buggy to me.
