### ISSUE TITLE
3D LUT → segmentation fault

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3516]
System: Debian 10 stable + dt master builds. Segmentation fault on loading big HaldLUT.

File: 
https://drive.google.com/open?id=1WoPFoouBbJlbQa5VsWXiT2kPJMH5NREI

File comes from:
http://rawpedia.rawtherapee.com/Film_Simulation#RawTherapee_Film_Simulation_Collection

Additional: where was report on mailing list that dt windows builds corrupt image but do not fail.

**Comment by TurboGit** [comment]
Confirmed !

**Comment by TurboGit** [comment]
@phweyland : can you have a look ? thanks.

**Comment by madSec** [comment]
Hi, just found the same segmentation fault with the file @timur-davletshin posted above on my RC1 installation on Linux Mint. The file has a higher resolution (4096 px) than the other LUT files from the set (1728 px) which work fine.

**Comment by phweyland** [comment]
> can you have a look ? thanks.

Sure, I'll do.

**Comment by phweyland** [comment]
The bug is simple, the lut size exceeds 255 (in fact 256).
Two possibilities.
Either I limit the possible sizes to 255 (in fact 64 because the constraint for haldclut is that size^3 must be have an integer square root).
Or I change the lut size type from uint8 to uint16 to cope with sizes > 255.

With this lut size the calculation time is quite long (few seconds) ...

@TurboGit What do you think ?

**Comment by TurboGit** [comment]
I'm not expert on Lut. I'm not sure how many Lut found on the Web fall into the category of size <= 64. But if the time is few seconds for larger luts I think it makes sense to restrict this module to size <= 64 for now.

**Comment by phweyland** [comment]
>  I'm not sure how many Lut found on the Web fall into the category of size <= 64

That's the first time I see a such large size for an haldclut (png). In the PR #2534 I've used a size = 48 for cache files, as suggested by David Tschumperle.

> I think it makes sense to restrict this module to size <= 64 for now.

OK, I'll limit the size.

**Comment by timur-davletshin** [comment]
3d lut needs better error handling. It doesn't say anything if you try to feed it with any png file.

**Comment by timur-davletshin** [comment]
@phweyland that file which caused crash comes from set of luts recommended to use with rawtherapee.

**Comment by phweyland** [comment]
> 3d lut needs better error handling. It doesn't say anything if you try to feed it with any png file.

Fixing that.



>  from set of luts recommended to use with rawtherapee.

It would be interesting to know if RT users can see benefits using such a LUT size.

**Comment by timur-davletshin** [comment]
> It would be interesting to know if RT users can see benefits using such a LUT size.

I doubt that too. But this set is what users get if they google for free luts. My idea is purely from user standpoint — keeping up some compatibility and less confusion for first time users.

**Comment by timur-davletshin** [comment]
> It would be interesting to know if RT users can see benefits using such a LUT size.

BTW, look like GMIC handles that file correctly too.

**Comment by phweyland** [comment]
Just checked the cube file specification. Looks like we should support the 256 value ...

![image](https://user-images.githubusercontent.com/23012047/69565593-96b28300-0fb5-11ea-9fde-a6f3849355e0.png)

**Comment by phweyland** [comment]
PR #3566
