### ISSUE TITLE
UI → Wrong button order

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3517]
Since dt uses reversed button order in UI (approval buttons are on the right side). This can be considered a bug. Similar problem was fixed before in export settings.

Steps to reproduce:

1. Open lighttable mode → tagging module.
2. Create any tag if list of available tags is missing.
3. Right click on created tag:
        a) "delete tag" action opens confirmation window with reversed
button order. Same for "delete branch".
        b) "create tag..." opens dialog window with reversed button
order. Same for "edit tag...".

**Comment by sams96** [comment]
I thought I'd have a look for other cases of this, and I was wondering what you thought of this dialog in the export module:

![exportmetadata](https://user-images.githubusercontent.com/1129989/69420058-d9c3ea80-0d58-11ea-9b3b-7805018f0b9e.png)

I feel like it should be the other way around because 'done' cancels the action but I thought I'd check

**Comment by sams96** [comment]
Also this box accessed through the presets section in preferences:

![presets](https://user-images.githubusercontent.com/1129989/69420871-923e5e00-0d5a-11ea-8bc1-72089c3e2446.png)

**Comment by timur-davletshin** [comment]
Sam96, I'm really not looking forward to start long discussion about Gnome HIG, my point is very simple. People getting used to certain button position in UI, putting them in opposite order makes people click wrong buttons.

**Comment by sams96** [comment]
I'm not looking for a long discussion either, I just wanted to ask if these two fit the system or if not how they should be.

**Comment by timur-davletshin** [comment]
As a user I'm OK with first one, but second... 3 buttons for two actions look redundant to me.

**Comment by sams96** [comment]
It seems that 'save' and 'ok' do different things, so I think they need to stay. I guess 'cancel' should be first though?

**Comment by timur-davletshin** [comment]
Cancel, Save, OK — OK :)

**Comment by houz** [comment]
dt wasn't wrong in its order, it was just different from what you are used to. There is no one correct way to do this.

**Comment by sams96** [comment]
@houz Different to what is used in other parts of darktable, consistency is good.

**Comment by agusmba** [comment]
Each OS has different defaults regarding button placement and order

**Comment by TurboGit** [comment]
> Each OS has different defaults regarding button placement and order

Sure, but this does not mean that dt should use random placement in different parts of the GUI. As @sams96 said, consistency is important.
