### ISSUE TITLE
[Feature] Export : Option to add a watermark on exported images

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3519]
Hi !

_I hope this has not been requested before. I searched & couldnt find such a F.R._

I have a folder that I want to export, say for web publication.
I have retouched some photos, but not all of them.
When I exported them, I noticed/realized that many of them were missing my watermark.

In the export options, I'd like to be able to select a Watermark preset so that all exported photos are added the selected watermark. This way, I'm sure not exported picture is missing my watermark.

Thanks
GLLM

**Comment by chhil** [comment]
Export allows a style. Could your watermarks be made into standalone styles and used ,

**Comment by TurboGit** [comment]
Yes, use a style at export time.

**Comment by GLLM** [comment]
hi @chhil & @TurboGit 
I didn't see it this way ... that's clever indeed !

Thanks for the solution :-)
