### ISSUE TITLE
UI → non-scrollable lists

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3520]
Long lists like the one in lens correction module are not scrollable. Options down bellow are not available to user. Renders them unusable.

Additional info: Similar list in 3d lut module is scrollable.

![noscroll1](https://user-images.githubusercontent.com/58066490/69408775-a5c8d500-0d18-11ea-8d7c-8e3817cc1878.png)

**Comment by ptilopteri** [comment]
you don't state operating system or version but above scrolls fine with mouse wheel on my openSUSE Tumbleweed darktable master versions git54.bfecbb5ca and git54.bfecbb5ca

**Comment by TurboGit** [comment]
This has already been reported and it was a Gtk bug now fixed. Don't remember the exact first version fixing that but you can find this here in GitHub.
