### ISSUE TITLE
UI → Line height in confirmation dialog

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3522]
Steps to reproduce:
1. Enable "ask before removing empty folders"
2. Disable "send files to trash when erasing images"
3. Create folder with one image and import it
4. Delete that image from collection via "selected image[s] → delete"

Problem:
Confirmation dialog height is too small to show folder name.

OS: Debian 10 Stable + dt master builds

![screenshot1](https://user-images.githubusercontent.com/58066490/69409327-bb8aca00-0d19-11ea-9add-ebd3f26d282a.png)

**Comment by GLLM** [comment]
@timur-davletshin : 

if I may : since you are reporting a lot of display issue, you should detail the setup you are using, in your issues. darltable version + OS/version + Screen resolution at least.

Have a nice day :)

**Comment by johnny-bit** [comment]
Line height is good in current master and should be totally fine in 3.2.1 and 3.4+ releases.
