### ISSUE TITLE
[Feature] collect images by their ID or by their module used ...

### ISSUE THREAD

**Issue by Haribo-66** [darktable-org/darktable#3524]
**Is your feature request related to a problem? Please describe.**

I am trying to get rid of old (deprecated) modules used by earlier worked on images. 
I can see all the usage of an indivudual module in the database (table called history).

The problem ist that I would need a filename because the image ID is actually not supported to select these images with the old modules I found in the database.

**Describe the solution you'd like**

Support image ID as a new attribute for collecting images.

**Describe alternatives you've considered**

An alternative would be to search for a single module name to remove the unwanted ones in one sequence.

**Additional context**

![capture_11222019_141211](https://user-images.githubusercontent.com/53818783/69428753-4aa3dc00-0d32-11ea-9c6d-9e8808f9832a.jpg)

**Comment by TurboGit** [comment]
For such a case it would be better to have a way to filter by modules. This was discussed already I think.

**Comment by Haribo-66** [comment]
All my current image errors / on-the-fly history conversions / darktable crashes are going to the terminal right now (due to the debug output) and they are all "named" by their image ID. 

I remember asking about the module search - a year ago - but I can not remember a discussion ...

**Comment by Haribo-66** [comment]
workaround is running ...
