### ISSUE TITLE
Small bug in borders.c

### ISSUE THREAD

**Issue by kbarni** [darktable-org/darktable#3525]
**Describe the bug**
https://github.com/darktable-org/darktable/blob/master/src/iop/borders.c#L782 reads:

    p->pos_v = g->pos_h_ratios[which];

should be:

    p->pos_v = g->pos_v_ratios[which];

Probably just a copy-paste code that wasn't corrected. Fortunately has no effect at the moment, as the `pos_v_ratios` and `pos_h_ratios` are the same, but might be a problem later.

**Comment by TurboGit** [comment]
Thanks, I agree with the analysis. Good catch, now fixed.
