### ISSUE TITLE
RC1: lens correction causes blur with OpenCL

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3527]
**Describe the bug**
After applying lens correction I noticed increased blur in the image. First I thought it had to do with distortion but the effect occured even with TCA or vignetting only. 
I tracked it down to the usage of OpenCL

Screenshot of applied lens correction without Opencl (100% crop from center):
![Bildschirmfoto von 2019-11-22 15-07-59](https://user-images.githubusercontent.com/49001045/69432603-54314200-0d3a-11ea-9c35-b5daffb1ef45.png)

Same area after enabling OpenCL and turning lens correction off and on again for recalculation:
![Bildschirmfoto von 2019-11-22 15-08-23](https://user-images.githubusercontent.com/49001045/69432658-68753f00-0d3a-11ea-997a-65fa688e5a54.png)

**Platform (please complete the following information):**
DT 3.0.0rc1~git11.dc641cdc9 on Ubuntu 18.04
NVIDIA-SMI 440.31 Driver Version: 440.31 CUDA Version: 10.2
[clinfo.txt](https://github.com/darktable-org/darktable/files/3879864/clinfo.txt)

**Additional context**
Since I got an additional pixel line visible on the right image border this behaviour is
possibly related to https://github.com/darktable-org/darktable/issues/3503

**Comment by junkyardsparkle** [comment]
That looks more like loss of contrast from lifted shadows than blur, but either way, your OpenCL seems to be broken. I don't know how hard it is to try different driver versions on Ubuntu, but as long as it's not a very recent card, rolling back might be worth a try.
