### ISSUE TITLE
UI → rgb curve

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3528]
Steps to reproduce:
1. Import two files.
2. Apply rgb curve module for both of them with independent channels option enabled.
3. Open "G" or "B" channel inside rgb curve.
4. Press space to move to the next file (do not close rgb curve module).

Problem:
rgb curve module does not refresh  UI ("R", "G", "B" tabs) for the next file. "R" curve is loaded correctly but UI remain on "G" or "B". See that on attached screenshot.

![Untitled](https://user-images.githubusercontent.com/58066490/69440217-74242e00-0d59-11ea-8949-c417bbd40bc2.png)

**Comment by TurboGit** [comment]
Confirmed ! The tab stays on G or B but the curve is R.

**Comment by TurboGit** [comment]
Probably just a gui_update() implementation issue.
