### ISSUE TITLE
Active color picker isn't turned off when module is turned off

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#3532]
**Describe the bug**
When an active module with a color picker has the color picker active and the module is disabled, the color picker remains active.  When you open the module and turn the color picker off, the module turns back on, so then you have to turn it back off.

This behavior appears to work the same with all modules that have a color picker.  This behavior is also present in 2.6.x and probably earlier.

**To Reproduce**
1. Open an image in darkroom
2. Open a module that has a color picker
3. Activate the color picker
4. Turn the module off
5. See the color picker is still active
6. Open the module
7. Turn the color picker off
8. Notice the module turns back on

**Expected behavior**
It makes sense (at least to me) that when the module is turned off that the color picker should turn off if active.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 3.0rc1+62

**Additional context**
This is the current behavior in 2.6.x also, so I don't think it needs to be fixed for the 3.0 release.

**Comment by timur-davletshin** [comment]
I reported something similar #3514

**Comment by blitzgneisserin** [comment]
I think this is similar #3451

**Comment by wpferguson** [comment]
So it sounds like when another module gets focus, an active color picker from a module losing focus should be turned off so that we don't get unintended edits.

**Comment by blitzgneisserin** [comment]
Are you working on this?

**Comment by wpferguson** [comment]
I haven't touched it for a week or so.  I tried one solution, but it only fixed one instance.  I still need a better understanding of the code before I figure out a fix.

**Comment by blitzgneisserin** [comment]
@wpferguson ok, thanks for the update

**Comment by timur-davletshin** [comment]
Similar to #3642 — shape's editor isn't turned off after closing mask manager.
