### ISSUE TITLE
I constantly get the error inconsistent output

### ISSUE THREAD

**Issue by jefferson2z** [darktable-org/darktable#3533]
I constantly get the error inconsistent output. When I turn a module on or off, or when I zoom in or out.

**To Reproduce**
1. Turn any module on or off
2. The message inconsistent output appears over the image (Sometimes I get local "laplacian inconsistent output")

**Platform (please complete the following information):**
 - OS: Fedora 31
 - OS: Fedora 30 as well
 - Version 2.6.3-2

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Today I got this message "inconsistent output" in local contrast module...
DT3.0.0 Windows10.

**Comment by aurelienpierre** [comment]
Will be fixed in 3.0.x
