### ISSUE TITLE
Fujifilm x-a10 camera support

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/darktable#3534]
darktable part of https://github.com/darktable-org/rawspeed/issues/209

**Comment by LebedevRI** [comment]
Please contribute a new sample to https://raw.pixls.us/ - something like daylight landscape - the existing one is waay too dark.

**Comment by LebedevRI** [comment]
@mk989 i'm not propagating support to darktable as of presently though.
In the meantime, if you build yourself, just update rawspeed submodule
to point to latest develop and it will work.

**Comment by mk989** [comment]
Thank You, after that I have preview and I can start editing photos. However info about missing color matrix is still showing. I updated .raw on pixls.us, but  I think it is not updated yet.

**Comment by LebedevRI** [comment]
> if you build yourself, just update rawspeed submodule
> to point to latest develop and it will work.

**Comment by LebedevRI** [comment]
Err, i mean, you also need darktable master branch.

**Comment by mk989** [comment]
Hmm, I've updated cameras.xml in darktable/shear/rawspeed, what I should also update, because I don't get it?

**Comment by LebedevRI** [comment]
Like i have already said, it will only work if you build darktable yourself - you need to build darktable git master (and ensure that in rawspeed submodule, rawspeed develop branch is checked out)

**Comment by mk989** [comment]
Unfortunately I'm not programmist and really don't know how to build darktable git master. Is there any tutorial?

**Comment by LebedevRI** [comment]
See https://github.com/darktable-org/darktable#building e.g.
Though after `git submodule update` you need to do `cd src/external/rawspeed && git checkout origin/develop && cd ../../`

**Comment by mk989** [comment]
I have problem when trying build, after ./build.sh --prefix /opt/darktable --build-type Release i get ./build.sh: line 305: cmake: command not found
I downloaded cmake how can i install it in git?

**Comment by mk989** [comment]
CMake Error at C:/cmake-3.16.0-rc4-win64-x64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
  (Required is at least version "4.0")
Call Stack (most recent call first):
  C:/cmake-3.16.0-rc4-win64-x64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  C:/cmake-3.16.0-rc4-win64-x64/share/cmake-3.16/Modules/FindOpenMP.cmake:511 (find_package_handle_standard_args)
  CMakeLists.txt:57 (find_package)
any ideas?

**Comment by mk989** [comment]
Was this issue involved in 3.0 rc2?
