### ISSUE TITLE
histogram and file export are broken in git master

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#3540]
An image is displayed correctly in the darkroom, but the histogram shows
it is almost black and the resulting file is black too. Reverting the commit 0ecd0312f555ca526791f4f9558fd00194415a34 made it work.

Here is the link to a file https://yadi.sk/d/DD7Sm6W1F_2u_A with color matrix and base curve.

**Comment by TurboGit** [comment]
Thanks! I just exported and the image looks correct, so there is something else. Is the use LittleCMS selected in preference?

![DSC03893-01](https://user-images.githubusercontent.com/467069/69480205-bdca5280-0e05-11ea-9106-01053086b304.jpg)

And histogram looks correct:

![image](https://user-images.githubusercontent.com/467069/69480217-ddfa1180-0e05-11ea-854f-b7b53a3e6a5e.png)

**Comment by timur-davletshin** [comment]
It's kinda strange. Only works with images I never imported before. If I open same image second time it works fine.

**Comment by timur-davletshin** [comment]
But I can reproduce it if started with clean profile.

**Comment by TurboGit** [comment]
Just pushed a fix, not sure it makes a difference here but you can try.

**Comment by BigSerpent** [comment]
The image I see is different - it uses my base curve and color profile SonyA99.icc from the file.
![DSC03893_1600](https://user-images.githubusercontent.com/47396887/69480471-bf514600-0e18-11ea-9306-5ab6228ae79b.jpg)

**Comment by BigSerpent** [comment]
No, LittleCMS,2 is not checked in the preferences.

**Comment by TurboGit** [comment]
Ok, test new version and tell me if it is fixed. No much I can do without reproducing.

**Comment by BigSerpent** [comment]
It works now! Thank you!

**Comment by BigSerpent** [comment]
It works now, thank you!

With respect,
Alexander Rabtchevich

Pascal Obry wrote:

**Comment by TurboGit** [comment]
Big relief :) A stupid code clean-up error on my side :)
