### ISSUE TITLE
dt 2.6 → dt 3.0 wrong orientation

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3545]
All my portrait negative color film scans have wrong rotation after moving to dt 3.0 :)

Steps to reproduce:
1. Import any raw file in dt 2.6.
2. Apply invert module.
3. Apply orientation module so picture looks upside down.
4. Now import that picture to dt 3.0

Problem:
Picture has wrong rotation in after importing to dt 3.0

Sample xmp file:
[2016-11-29-05-58-53-0.ARW.zip](https://github.com/darktable-org/darktable/files/3883292/2016-11-29-05-58-53-0.ARW.zip)

**Comment by TurboGit** [comment]
Hi timur,

> All my portrait negative color film scans have wrong rotation after moving to dt 3.0 :)

Probably because the previous version of the orientation module was quite bugged! We have fixed this issue in 3.0 using a set of test pictures to ensure all orientations are properly handled.

See #2306

But this breaks the previous rotations.

**Comment by timur-davletshin** [comment]
OK. So, I have to rotate them all manually 😢

**Comment by TurboGit** [comment]
Yes, but you can you that from the lighttable, select all your portrait negatives and rotate them in one click. Not that bad. The compatibility would have been very hard and would have obfuscated the code quite a lot.
