### ISSUE TITLE
display mask seems broken

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#3547]
**Describe the bug**
In my opinion "display mask" is severely broken. When you zoom with "display mask" activated, strange effects happen.

opencl on/off = same effect

e.g. in exposure, use some drawn masks, like I did here:
https://discuss.pixls.us/uploads/short-url/3x3lmhqb5nLAms0bv77oGxPQVZW.xmp
for patdavid's photo
https://pixls-discuss.s3.amazonaws.com/original/2X/d/d198acee5386038eebdf8e91084f2c9cf3fd3892.ORF

**To Reproduce**
1. go to darkroom
2. activate "display mask"
3. Click mouswheel to zoom **or**  ctrl+mouse-wheel

**Expected behavior**
masks schould be displayed correctly, regardless the zoomfactor (btw: it was a round mask, not squared

**Screenshots**
![Screenshot_20191124_141756](https://user-images.githubusercontent.com/49004103/69495437-5b398b00-0ec7-11ea-9298-a9418b4bbbdb.png)
![Screenshot_20191124_141829](https://user-images.githubusercontent.com/49004103/69495438-5d034e80-0ec7-11ea-944e-d712e1ce89ba.png)
![Screenshot_20191124_141847](https://user-images.githubusercontent.com/49004103/69495440-5f65a880-0ec7-11ea-9b8a-c6f1c6589bf9.png)

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [3.0.0rc1+77~g318500a16]

**Comment by vsz1lu** [comment]
confirmed - some with or without opencl

**Comment by TurboGit** [comment]
From a fresh edit I can't reproduce, so is that an iop-order issue? What is the order in the pipe? Can you post a step-by-step reproducer without an XMP?

**Comment by AxelG-DE** [comment]
@TurboGit I'm a bit confused, how can I be more precise than withe an xmp?
Currently in gym, try to reply iop question later. Just so far, I never change module orders in pipe and version was up to date when I edited

**Comment by TurboGit** [comment]
I'm trying to asses if the bug can be reproduced with fresh edit. I cannot on my side. I'm short on time to test everything, so please help... Thanks.

**Comment by AxelG-DE** [comment]
I'm not reluctant, just got confused :-)

**Comment by AxelG-DE** [comment]
Fresh edit test will come after gym

**Comment by vsz1lu** [comment]
A path and two combined ellipse.

Fit to screen:
![Képernyőkép erről: 2019-11-24 16-05-01](https://user-images.githubusercontent.com/57588193/69496626-65ae5180-0ed4-11ea-8632-5c20b5e3bc0e.png)

100%
![Képernyőkép erről: 2019-11-24 16-05-20](https://user-images.githubusercontent.com/57588193/69496629-7959b800-0ed4-11ea-9733-5209105b5dcf.png)

I can't reproduce now the stripped lines as on last screenshot of @AxelG-DE, but sometimes I see similar.

xmp: 
[191873-D40003.NEF.zip](https://github.com/darktable-org/darktable/files/3883729/191873-D40003.NEF.zip)



It's not a critical bug, but need enchantments. However an harder anitaliasing maybe growing up the processing time at the preview.

**Comment by AxelG-DE** [comment]
@TurboGit 
I did fresh edit with dt 3.0.0rc1+77~g318500a16 and same like you, I cannot reproduce anymore. I checked quite older edits, where I used the same method and it is also o.k.
iop-order, I guess is not the case.

This is the pipe of the effected edit (no effect shown, only the pipe):
![Screenshot_20191124_194457](https://user-images.githubusercontent.com/49004103/69499647-91d9ca80-0ef4-11ea-8da6-fc425c4feb3f.png)

and this one is the new edit, w/o the effect:
![Screenshot_20191124_195003](https://user-images.githubusercontent.com/49004103/69499657-aa49e500-0ef4-11ea-80a2-d048271979ab.png)

**Comment by AxelG-DE** [comment]
I did one more thing...

- I moved over to my laptop. (both machines now on 3.0.0rc1+79~g4234dd87f)
- Took above foto
- duplicate
- copy history stack except that one exposure
- made that exposure new
- same error like my initial post
- changed zoom factor with mouse wheel and **dt crashed** w/o trace (frozen screen) (I admit, I use CMAKE_Build_Type=Release)
- tried the same things on my PC and similar things happen, except the crash

@jade-nl, I know you have similar experiance. Feel free to comment.

**Comment by AxelG-DE** [comment]
@vsz1lu 
> A path and two combined ellipse.
A bit OT and sorry if that is a noob question (I think I use dt already quite intense), how did you substract one elipse of the other. I know "invert" but that usually inverts all

**Comment by vsz1lu** [comment]
@AxelG-DE Combining:

Make some shape whats have overlapped  area. This shape makes an union by default. You can make logical relations between the shapes in the mask manager. In the group where used the shapes right click the lower and select intersection. This make a mask from only the overlapped area. select difference. This time the lower shape is cutting the upper shape. (What I used my sample.) Chose exclusion and the overlapped excluded all others not. You can play the order of the shapes too. Shapes with custom names make the work easier ;) You can rename the shapes out by double click out of groups.

Good old and great future in the darktable, use it :)

**Comment by AxelG-DE** [comment]
@vsz1lu thanks a lot

I hope we did not digress too much from the issue, described here :)

**Comment by AxelG-DE** [comment]
@TurboGit 
I kept on playing and unfortunately I must say, even fresh edits create weird results. There where two circular masks...
![Screenshot_20191124_225707](https://user-images.githubusercontent.com/49004103/69502292-fe14f800-0f0d-11ea-9ca4-2088c02b6ef7.png)
![Screenshot_20191124_225725](https://user-images.githubusercontent.com/49004103/69502294-00775200-0f0e-11ea-849f-ac8493b4c09a.png)

**Comment by AxelG-DE** [comment]
on my laptop similar issues, that was a fresh edit as well:
![Screenshot_20191125_202008](https://user-images.githubusercontent.com/49004103/69570959-3aedf700-0fc1-11ea-8d8e-88b43fed2b2d.png)

**Comment by upegelow** [comment]
There are two issues reported here:
1) in the first post: mask elements shifted or completely distorted
2) in the following posts: uneven borders of masks

Concerning (1): looks a lot like a coordinate mismatch along the pixelpipe. Maybe a rounding error somewhere in roi calculation. Difficult to track down.

Concerning (2): that's probably quite easy. In order to reduce memory overhead and for better performance intermediate mask shapes are generated with a reduced resolution and then interpolated. This can lead to the described aliasing artifacts. If someone wants to test: in src/develop/masks/circle.c look for constant `mesh`. If you reduce it to 1 the shape is generated with full resolution directly without interpolation. 
To should be evaluated how this affects the overall performance. Memory overhead has been crucial in the times when the code was developed (darktable still mostly run on 32bit systems at that time) but might be of less concern today. Mask generation timings can be analyzed by calling darktable with `-d masks -d perf` (pipe the output through 'grep masks' for a better overview).

**Comment by chhil** [comment]
> in the first post: mask elements shifted or completely distorted

Just a thought, would lens correction cause this and if it needs to be moved around in the iop order ?

**Comment by AxelG-DE** [comment]
@chhil interesting thought, I'll test as soon I find time in front of PC

**Comment by jenshannoschwalm** [comment]
>in the first post: mask elements shifted or completely distorted

@upegelow wasn't #2892 for this?

**Comment by AxelG-DE** [comment]
>     2. in the following posts: uneven borders of masks
> 
> Concerning (2): that's probably quite easy. In order to reduce memory overhead and for better [...]
interpolated. This can lead to the described aliasing artifacts. 

I have difficulties to considert those aliasing artifacts :smile: 
...also I think that wasn't the case in the past (2.7, summer time)
![Screenshot_20191127_210502](https://user-images.githubusercontent.com/49004103/69755969-b8e50600-1159-11ea-88cf-0b193a375c37.png)
![Screenshot_20191127_210231](https://user-images.githubusercontent.com/49004103/69755970-b97d9c80-1159-11ea-8131-c7f9c00ce285.png)

**Comment by AxelG-DE** [comment]
> Just a thought, would lens correction cause this and if it needs to be moved around in the iop order ?

I tried w/o lens correction. Unfortunately situation unchanged...

**Comment by upegelow** [comment]
> I have difficulties to considert those aliasing artifacts smile
> ...also I think that wasn't the case in the past (2.7, summer time)

Nope, Has been there also in 2.7 (and going back in time to when drawn masks where first introduced).

Quickly checked: setting mesh to 1 in circle.c removes the aliasing artifacts.

Now comes the difficult part. Mask generation with such a change would now take significant more processing time (factor 16 or so). The problem on the other hand is only relevant for low resolution preview cases - fully zoomed out center view. As you zoom closer to 100% resolution you see that these artifacts play no role any more. Also not for exported images. How much slowdown would we accept for a preview improvement?

**Comment by upegelow** [comment]
Idea for an adaptive interpolation:

`const int mesh = CLAMP(4.0f*(log10(roi->scale) + 1.0f), 1, 4);`

**Comment by AxelG-DE** [comment]
Maybe I am not competent enough to understand the differences... This pic I edited long time ago, likely with 2.6.x and it is a path, not a circle mask. However, (almost) no such effects...
![Screenshot_20191127_233722](https://user-images.githubusercontent.com/49004103/69763995-31a28d00-116f-11ea-8bad-c1957ba22108.png)

**Comment by upegelow** [comment]
It's an issue with circle, ellipse and (probably to a lower extent) gradient. Path and brush are not affected.

**Comment by AxelG-DE** [comment]
I checked in 3.1 this issue is solved now. I will cose this one, but sorry guys, I will come up with some new about masking :-/  :-)

**Comment by AxelG-DE** [comment]
Sorry, forgot to say @upegelow thank you very much!
