### ISSUE TITLE
Group of shapes auto collapse after right click action in the mask manager - dt3.0.0rc1

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#3549]
**Describe the bug**

If you want edit the properties of a shape what assigned to a group the group go to collapsed state immediately after the right action. In dt2.6.2. not.

**To Reproduce**
1. turn on any module (ex. exposure) and click drawn mask
2. make some shape
3. go to the mask manager on the left panel
4. click the arrow of 'grp exposure'
5. right click on a shape
6. select any action
7. the group of shapes collapsed automatically

**Screenshots**
![Képernyőkép – 2019-11-24 16-55-53](https://user-images.githubusercontent.com/57588193/69497365-56cb9d00-0edc-11ea-866a-c28e4c6e7c8b.png)

**Platform:**
 - OS: Ubuntu 19.10
 - Version dt 3.0.0rc1

**Comment by blitzgneisserin** [comment]
confirmed

**Comment by vsz1lu** [comment]
Same problem in dt 3.0.0 rc2. Please handle as bug.
