### ISSUE TITLE
[Regression] 3.0.0-rc2 Exposition and Local Contrast fail if DT is built with LTO

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#3551]
**Describe the bug**
All thumbnails both in darkroom and lighttable view are blank/white.
darktable-generate-cache doesn't seem to generate anything, too: completes very fast and nothing in ~/.cache is seen.

**To Reproduce**
Build DT with LTO support.
Open DT with existing collection.

**Expected behavior**
Thumbnails are shown as usual.

**Platform (please complete the following information):**
 - OS: gentoo linux
 - Version 3.0.0-rc1

UPD: Freshly imported untouched shots seem to work OK. Mostly, some are still shown white. Preview (W) if thumbnail is shown white is white, too. Focus areas on (Ctrl-W) are shown on white. After some processing thumbnail becomes white, thus it seems to work if taken from image's buili-in JPEG and fails if generated from RAW.

**Comment by junkyardsparkle** [comment]
This obviously isn't happening to everyone else with your given steps to reproduce; can you reproduce this starting with a clean config, and list any changes to settings and other steps which lead to it happening? Are you using OpenCL, color management, etc?

**Comment by kanyck** [comment]
With discarded darktablerc -- the same.
Color management: 
```
darktable-cmstest version 3.0.0~rc1
this executable was built without colord support
darktable itself was built without colord support

primary CRTC is at CRTC 0
CRTC for screen 0 CRTC 1 has no mode or no output, skipping
CRTC for screen 0 CRTC 2 has no mode or no output, skipping
CRTC for screen 0 CRTC 3 has no mode or no output, skipping
CRTC for screen 0 CRTC 4 has no mode or no output, skipping
CRTC for screen 0 CRTC 5 has no mode or no output, skipping

DisplayPort-0
	X atom:	_ICC_PROFILE (560 bytes)
		description: Adobe RGB (1998)

Your system seems to be correctly configured
```
Use OpenCL -- yes, but switching it off doesn't help.
Also, I noticed this version demands graphite to build. Previously graphite was off, so the dependencies are built without it. I doubt it matters but JFYI...

**Comment by kanyck** [comment]
It is LTO to blame. DT works fine when built without it.

**Comment by parafin** [comment]
Please show the exact flags you are building DT with (e.g. emerge --info output).

**Comment by kanyck** [comment]
Here you go...
http://dpaste.com/16BAZ49

I also may notice that I'm on Git version for awhile, like 6 or 8 months maybe, and recompiled it last time about a couple months ago, so it's quite recent regression.

**Comment by kanyck** [comment]
UPD: it is not LTO that caused the issue. It's -fipa-pta GCC flag to blame. Currently DT is built with
```
CFLAGS="-march=native -O3 -fno-semantic-interposition -flto=4 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -msse3"
CXXFLAGS="-march=native -O3 -fno-semantic-interposition -flto=4 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -msse3"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -march=native -O3 -fno-semantic-interposition -flto=4 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe"
```
and seems to work properly. So probably the https://github.com/darktable-org/darktable/issues/3680 is what I was suffering from. At the moment DT seem to work just fine. 
Closing this so far. Will reopen it if need be.

**Comment by kanyck** [comment]
Well, I have to reopen the issue.
I found that two modules don't work properly if DT if built with LTO: Exposition and Local Contrast.
Exposion, if touched, produces colored mosaic.
LC produces black field.
In both cases it's a regression since 2.7.

**Comment by kanyck** [comment]
Closed in favor of https://github.com/darktable-org/darktable/issues/3769 and https://github.com/darktable-org/darktable/issues/3865

**Comment by johnny-bit** [comment]
I think this might be unsafe compiler flags in the play. Modules are separate .so files, and i/o gets passed in app to/from them + some compiler flags do not play well with openmp and all that. I think Diego E Panateno (if i remember correctly) had some sort of fuzzing setup where he'd recompile with every flag possible to squeeze out what's causing errors.

It's mostly undef behaviours and dragons doing shenenigans. With "optimization-first" based flags we'd get very random behaviours.

My advice on that - try to build from basic flags and then replicating. If you can't add another flag till you find what's wrong.

Additionally - compiling dt using clang instead of gcc can and will cause crashes, but needs more work for hunting it (if it's undef behaviour or compiler fault)
