### ISSUE TITLE
DNG → fix demosaic UI

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3556]
Darktable shows demosaic module turned on when opening DNGs with regular pixel order (already demosaiced). It looks like internally it processes them correctly since no visible changes happen when passthrough (or other options) are changed.

Expected behavior: disable demosaic module for such files just like for JPGs or regular TIFF files.

Picture author notice: Serge Ramelli, publicly available on his site.

[Episode 178 San francisco.zip](https://github.com/darktable-org/darktable/files/3885152/Episode.178.San.francisco.zip)

**Comment by vsz1lu** [comment]
Confirmed. Tested with grayscale raw dng from transparent film scan by VueScan.

![Képernyőkép erről: 2019-11-25 17-01-19](https://user-images.githubusercontent.com/57588193/69557190-76c79300-0fa6-11ea-8bfe-04645e76971d.png)


Demosaic modul turned on but automatically set to passtrough mono. So I think it's not problem (for me) by technically - however hiding this module maybe more elegant solution in similar case.

**Comment by timur-davletshin** [comment]
It doesn't set to passthrough for color images.

**Comment by vsz1lu** [comment]
You're right!

Here is 2 1600dpi negative dng in grayscale and AdobeRGB color space (20MB)  - free use :
[https://drive.google.com/open?id=18gdWB-zoJZdEp5p-tuNjPeoxk7qVDH2u](https://drive.google.com/open?id=18gdWB-zoJZdEp5p-tuNjPeoxk7qVDH2u)

The demosaic module goes to PPG by automatically after open.

**Comment by timur-davletshin** [comment]
@vsz1lu exactly! That was my point. Passthrough is fine, but PPG is wrong.

**Comment by TurboGit** [comment]
Should be fixed.
