### ISSUE TITLE
UI → Export to lossless WebP

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3557]
Lossless settings in export to WebP should hide quality slider because it makes zero difference for the end result.

**Comment by sams96** [comment]
So I wrote a patch for this, but the insensitive slider doesn't seem to grey-out very well, not sure what I can do about that though.

**Comment by timur-davletshin** [comment]
Maybe just hide that slider? Or, I don't know, maybe it could be fixed on CSS level. I'm not sure if we have inactive sliders somewhere else in dt.

**Comment by sams96** [comment]
It seems they all look like that, oh well. I also found the same issue in TIFF exports and fixed that.

**Comment by timur-davletshin** [comment]
I think it's worth asking @aurelienpierre or @TurboGit about cssing inactive sliders so they look like inactive.

**Comment by timur-davletshin** [comment]
@sams96 or maybe it's better to follow logic of, let's say, demosaic module and hide non-relevant sliders.

**Comment by TurboGit** [comment]
Agreed, we need better CSS style for inactive sliders.

**Comment by timur-davletshin** [comment]
> Agreed, we need better CSS style for inactive sliders.

Sure, it's good to have one. But is it not better just hide them?

**Comment by cryptomilk** [comment]
That's what I did in the AVIF module I'm currently working on. Just use `gtk_widget_show()/gtk_widget_hide()`.

**Comment by timur-davletshin** [comment]
@sams96 will you make another attemp with show/hide?

**Comment by timur-davletshin** [comment]
@sams96 now ask politely @TurboGit to include it in 3.0. We deserve less bugs in UI in final release 😃
