### ISSUE TITLE
Highpass → 5-6% sharpness

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3559]
Steps to reproduce:
1. Enable 'highpass' module
2. Change sharpness to 6% contrast boost leave at 50%
3. Change sharpness to 5%

Sharpness disappears at all, gradual change is expected.

Samples with 6 and 5 percent sharpness:
![highpass_six](https://user-images.githubusercontent.com/58066490/69519867-19165500-0f6c-11ea-98b3-ce1af444634e.png)
![highpass_five](https://user-images.githubusercontent.com/58066490/69519918-32b79c80-0f6c-11ea-94bd-287e1f2586c8.png)

**Comment by TurboGit** [comment]
I think this is the way high-pass works. The same happens with 2.6.2 and probably before too.

**Comment by timur-davletshin** [comment]
Yes, I know that it was in previous versions too, but I doubt that 1% change could make such jaggy result if everything processed in 32bit float. I'm just saying that from user stanpoint there is no point to show lower 5% if they are not usable.

**Comment by TurboGit** [comment]
Well there is max 16 discrete radius for a range of 0 - 100%. This means that values are ranged from 0 - 16 and 0 means no details. You can see that using the sharpness slider, it is not continuous.

**Comment by chhil** [comment]
Doesn't sharpness depend on the zoom level? So the %age that is not visible at a certain zoom level will become visible at other zoom levels.

**Comment by pphotography** [comment]
Tried it even at 1600%, the sharpness disappears on values <6%
