### ISSUE TITLE
Accelerators for lighttable and filmstrip conflict

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#3562]
The Preferences/Shortcuts editor will not allow the same keys to be defined for an action in lighttable and filmstrip (which is used in darkroom). This is inconvenient, because in the standard keyboard layout (and logically) rating and color assignments use the same keys in both (1..5, F1..F5). If one accidentally reassigns one of these keys, _both_ original assignements will be removed, but it will only be possible to set one of them back.

**Comment by AlicVB** [comment]
yes, this is because filmstrip can be used in lighttable too (culling and full preview).
Now I agree with you about the reassignment problem. I'll have to dig in the code and see how we can solve that.
