### ISSUE TITLE
UI: Ugly fonts in Color Picker on Windows 10

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#3568]
Darktable 3.0 RC1 under Windows 10, theme darktable-elegant-darker, see below the color picker 

![Cattura](https://user-images.githubusercontent.com/43290988/69571387-442b9380-0fc2-11ea-9c24-b600918dba70.JPG)

Fonts for Lab values in color picker and in live samples are different, they should be equal.
Also # of decimal digits is 3 in color picker, 2 in live samples, they should be equal

**Comment by timur-davletshin** [comment]
They are monospaced and they are fine IMO. I could only wish they were monospaced in picker part too, not only in live samples. Same precision will make picker module even better.

**Comment by MStraeten** [comment]
Using a monospaced font makes it easy to have fixed columns in live samples section, in the upper part you don’t need fixed column

**Comment by timur-davletshin** [comment]
@MStraeten any ideas on higher precision?

**Comment by MStraeten** [comment]
Whats the benefit of higher precision? You wont be able to change lab values in 1/1000 steps ...

**Comment by Nilvus** [comment]
@MStraeten, @timur-davletshin and @Mark-64 : anyway, I agree that could be better to have consistent display. Not the most important thing but just more consistent. And have same decimals number also. To apply monospace, that just needs to add the "live-sample-data" tag on the color picker part number line to apply monospace font. I asked @TurboGit if that could be done.
