### ISSUE TITLE
blendop_rgb and blendop_mask_rgb are not applied in style

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#3571]
I set Profiled Denoise to use parametric mask (to apply heavier blending for darker parts), then save it as a style to apply only on export (to not slow down my editing). This is working correctly in 2.6.

However, on latest master branch, the style applied on export doesn't have the blending applied. If I apply the style to the image in lighttable, then export without the style, it still works fine.

I ran darktable -d all, and compared the console outputs of the two cases. The only difference is the missing of "blendop_mask_rgb" and "blendop_rgb" (between "denoiseprofile_backtransform" and "denoiseprofile_init").

**To Reproduce**
1. Apply a module with parametric mask
2. Save the module to a style, and apply the style on export
3. The parametric mask doesn't apply on export.

**Expected behavior**
The parametric mask should be applied when applying the module from a style on export.

**Platform:**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Original bug report: https://redmine.darktable.org/issues/12690

**Comment by hqhoang** [comment]
Currently my temporary fix is to re-patch src/common/styles.c everytime I pull. Around line 600, the last else block:

```
else
{
    // original: memcpy(module->blend_params, module->default_blendop_params, sizeof(dt_develop_blend_params_t));
    memcpy(module->blend_params, style_item->blendop_params, sizeof(dt_develop_blend_params_t));
}
```

I have no idea what that does, I simply observed that the first IF block is called when the style is applied directly to the image, while the last ELSE block is applied on export, thus copied from the first IF over.

**Comment by wpferguson** [comment]
Thanks @hqhoang.  Now I know where to start.  I'll look at it.

**Comment by junkyardsparkle** [comment]
> I set Profiled Denoise to use parametric mask (to apply heavier blending for darker parts), then save it as a style to apply only on export (to not slow down my editing).

On a side note, I did similarly with 2.6, but I've found that when using the new parameters which have been added to the profiled denoise module, I no longer need to use blending at all. YMMV, but you may want to investigate that.

**Comment by TurboGit** [comment]
The solution is probably to use dt_develop_blend_legacy_params() to update the blend params.
