### ISSUE TITLE
Hot pixels/Raw denoise → Blending operations

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3573]
Blending operations are not disabled even if modules (hot pixels and raw denoise) cannot be activated (e.g. non raw file).

Should look like other non-applicable modules. Compare it with scale pixels.

**Comment by jenshannoschwalm** [comment]
@TurboGit I am not sure right now how to handle this. For me it's a bug. In my view there are two options:
1. Disable the blending gtk widgets for only-raw modules in case of a non-raw image. This seems to be a bit tricky looking at how module->flags are implemented.
2. Or just **don't show** the module in the tabs - as if it were a hidden module.

What do you (or others) think about this?

**Comment by TurboGit** [comment]
I would just do point 2. No need to show the blending widget in this case.

**Comment by jenshannoschwalm** [comment]
Ok. As this is closely related with #3591 i will do it there.

@TurboGit Just to make sure i understand it right; we **don't** want to see raw-only modules in the modules tab listing in darkroom at all if we have a non-raw image?

**Comment by TurboGit** [comment]
Oh, I was thinking of hiding the blend module only. Some module have text info when not usable on some format to explain why. So I don't think it is good to hide them completely. I would disable them (already the case I think) and ensure that the blending widget is completely hidden.

**Comment by johnny-bit** [comment]
This is fixed by #3662
