### ISSUE TITLE
Export settings → JPEG settings

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3576]
Add subsampling (4:4:4, 4:2:2, 4:2:0) and progressive mode support in JPEG export settings.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
Subsamping is already linked to the quality slider AFAIK.

**Comment by timur-davletshin** [comment]
It is always 4:4:4 in dt exported JPGs according to exiftool.

**Comment by parafin** [comment]
I don't think so: https://github.com/darktable-org/darktable/blob/master/src/imageio/format/jpeg.c#L339

**Comment by parafin** [comment]
So it actually depends of which settings jpeg_set_defaults function apply. But I think it's 4:2:0 subsampling.

**Comment by timur-davletshin** [comment]
> So it actually depends on which settings jpeg_set_defaults function applies. But I think it's 4:2:0 subsampling.

Actually you're right! Good to know. It would be even better if I could set it myself. I don't see why anyone could prefer low quality JPG settings but color subsampling is very common even in high quality in camera JPGs.

**Comment by junkyardsparkle** [comment]
> but color subsampling is very common even in high quality in camera JPGs.

My guess is that this is because, at full resolution, it's probably not really throwing away any information that would ever be visible to anyone in the real world. Downsampled and sharpened images might be a different story, though.

**Comment by senjacob** [comment]
Hey bot, please don't close it
