### ISSUE TITLE
Clarify where we want to install the support binaries long term and adapt the documentation

### ISSUE THREAD

**Issue by darix** [darktable-org/darktable#3580]
bremner would like to move the basecurve and noise tools into /usr/bin.

Another option would be that we actually move some of the other tools into the same subdir (e.g. -cltest,-cmstest,-rs-identify.

If we change any of those paths documentation should be updated at the same time.

**Comment by bremner** [comment]
To be clear, I mainly care about where the packages in Debian install things. Of course there is less friction if this is the same as other debian packaging and upstream.

**Comment by darix** [comment]
We should really get it to similar paths to all distros to make it easier to write documentation
