### ISSUE TITLE
UI → Module settings auto collapse

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3584]
Steps to reproduce:
1. Make sure that "expand a single darkroom module at a time" is enabled in dt preferences.
1. Open (just as example) 'shadows and highlights' module settings.
2. Click 'new instance' to create new 'exposure' instance.

Expected result: 'shadows and highlights' module collapsed
Actual result: both modules are open

**Comment by elstoc** [comment]
Reproduced in current master. Have noted other issues around this setting not being observed as well.

For example:

- Create two instances of exposure and leave one of them expanded
- Exit back to the lighttable
- Re-enter the darkroom
- Both instances are now expanded
