### ISSUE TITLE
DNG → Nikon lens detection

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3586]
Steps to reproduce:
1. Download two file (NEF and DNG produced from it):
    https://drive.google.com/open?id=1zRm38G8N84VX9tOnmZxv2lCtKc1NCrgE
    https://drive.google.com/open?id=1CA5mt45h9qZmYPTBXK8_Rsk53wpCQb3y
2. Import to darktable and compare image information
3. Notice that focus distance is not displayed and lens information is shortened. Lack of full lens information makes lens correction to fail detecting proper lens type.

Additional info:
1. Rawtherapee works fine with that DNG file picking up correct Exif values.
2. exiftool shows that information in DNG is not missing but dt uses wrong values:
  a) in case of NEF it shows LensID but in case of DNG only LensModel (Canon DNGs work fine).
  b) focus distance is in DNG according  to exiftool output.

**Comment by johnny-bit** [comment]
This is not a darktable bug. darktalbe uses exiv2 for reading all metadata info from image. here's what we get:

```
exiv2 -pa Nikon\ -\ D5200\ -\ 14bit\ compressed\ \(Lossy\ \(type\ 2\)\)\ \(3_2\).dng | grep -i focus
Error: Directory Nikon1 with 25665 entries considered invalid; not read.
exiv2 -pa Nikon\ -\ D5200\ -\ 14bit\ compressed\ \(Lossy\ \(type\ 2\)\)\ \(3_2\).NEF | grep -i focus
Exif.Nikon3.Focus                            Ascii       7  Ciągły AF
Exif.NikonLd3.FocusPosition                  Byte        1  6
Exif.NikonLd3.FocusDistance                  Byte        1  3.35 m
Exif.NikonAf2.ContrastDetectAFInFocus        Short       1  0
```

As you can see - problem is outside of darktable. you can file a bug against exiv2.
