### ISSUE TITLE
DNG → exposure information

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3588]
Exposure information is not properly stripped/checked from some DNGs. Must be numeric value, not number plus ". This leads to potential errors if those values will be treated as numbers somewhere and to UI problems. Notice image information in the bottom shows 1" s instead just 1 s.

File: 
https://drive.google.com/open?id=1iguUpM2gMkhEUZo80RvYAM5_t0wQqxLA

**Comment by timur-davletshin** [comment]
Same happens with this image https://discuss.pixls.us/t/playraw-autumn-island/4288 by @houz. Shows 30" s in bottom image information line.

**Comment by jenshannoschwalm** [comment]
This is certaily **not a bug at all**. What you describe is just the "visual representation" of a time and the double-prime " character is commonly used for seconds. But this is only about displaying a time. Maybe just s for seconds would be enough though, but for many of us the " makes it very clear and btw also my camera shows this.

The value is calculated from exif data and is a number in database as inx the sidecar. So: not a bug at all. Concider to close.

**Comment by timur-davletshin** [comment]
I have no idea if that value is used as a string or as a number somewhere but visual representation is wrong. Consistensy is another point — some raw files have this problem, yet some don't. Question...

**Comment by jenshannoschwalm** [comment]
The float value is used. **all** imgs with an exposure time greater 1sec will probably show this

**Comment by timur-davletshin** [comment]
So, this is a small issue to be fixed :)

**Comment by jenshannoschwalm** [comment]
You seem to have a nice humor :-) I would not want to change behaviour, for me this seems perfectly right. Don't know what other people think ... it's a UI design decision and not a bug.

**Comment by timur-davletshin** [comment]
:) well, this way or another using double prime " with s is just wrong. Any other examples of such use except darktable?

**Comment by parafin** [comment]
Yeah, it should be either " or s.

**Comment by timur-davletshin** [comment]
Stripping " will do fine for the time. But "s" should be added in image information on the left for consistency. For future releases it's better have "s"  translatable along with other units used in image information.

**Comment by parafin** [comment]
Here's the code in question: https://github.com/darktable-org/darktable/blob/master/src/libs/metadata_view.c#L442

There's no s, so it's fine as is. Just because you like s better than ", doesn't mean everybody agree. " is common to signify whole seconds in camera interfaces. And fractional exposure times are known to be fractions of one second. Yes, adding s (and removing ") would be another alternative on how to display the exposure time, but you present no arguments, so there's no reason to change anything.
