### ISSUE TITLE
DNG → Colorspace transfrom warning

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3589]
After recent patches related to DNG I started getting this warning in console:

[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile

File: https://github.com/darktable-org/darktable/files/3885152/Episode.178.San.francisco.zip

**Comment by jenshannoschwalm** [comment]
We know. You can ignore it, To be seen in all formally monochrome images. Will fix it after real bugs are done. So please close for now.
