### ISSUE TITLE
cleaner dng support

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#3591]
A DNG file can contain either a RAW or non RAW data.

In #3565 this has been fixed but a better solution has been devised. This ticket is to track work on this for 3.0.1.

The idea is to introduce more high level routines like:

```
dt_image_is_ca_correct_supported(imgid);
dt_image_is_matrix_correction_supported(imgid);
```

And use that in IOP where needed.

After doing that the dt_image_is_raw() routine will just check the flags and this routine will be used in place where we check for the flags directly. Partly reverting #3565 

We do expect this will ease maintenance.

**Comment by aurelienpierre** [comment]
See #7129

**Comment by TurboGit** [comment]
Probably fixed now.
