### ISSUE TITLE
Probable Infinite loop in filmic RGB color picker

### ISSUE THREAD

**Issue by adrien-bellanger** [darktable-org/darktable#3595]
Sometimes after selecting the color picker for "middle gray luminance", the value of the middle gray luminance is changed but the "working" mask on the image stays, and I am not sure if the image was modified.

It occurs several times in the last weeks, but not regularly. And it occurs always when I have made some crop work before which are not saved in the xmp such that I can't reproduce the bug without a lot of luck (or unluck).

In the following file, you can find the last output of darktable -d all.
[darktableLog.txt](https://github.com/darktable-org/darktable/files/3898578/darktableLog.txt)

Platform
 - OS: debian 10 
 - Version 3.0.0rc2+3~g34ad71813-dirty (without opencl)

**Comment by flannelhead** [comment]
I've also encountered this several times. Had no luck reproducing it yet, though. :/

**Comment by timur-davletshin** [comment]
I noticed that too today but in different module — exposure. Infinite "working.." after selecting "auto exposure". Didn't manage to reproduce though...

**Comment by junkyardsparkle** [comment]
I wonder if there might be a relation to this: https://github.com/darktable-org/darktable/issues/2808#issuecomment-559600561

**Comment by upegelow** [comment]
#2808 has been fixed. Would be interesting to see if this also is true for this one.

**Comment by junkyardsparkle** [comment]
> #2808 has been fixed. Would be interesting to see if this also is true for this one.

I was never able to reproduce this reliably (and I don't use the pickers frequently), but I was seeing occasional stuck "working" pointers prior to that commit, and don't now, for whatever that's worth.

**Comment by adrien-bellanger** [comment]
Until now I can't reproduce the bug, so I expect it was fixed with #2808 
Tahnks for the gut job.
