### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by jpverrue** [darktable-org/darktable#3597]
dans "tagging module" --> "dictionnary window" --> "context menu"
- La traduction de "edit tag" est "éditer le mot clé". C'est certes exact, mais très 'informatique'. Je pense que "modifier le mot clé" est plus correct en français.
- Dans ce même menu on a pour deux objets identiques, deux terminologies différentes : 
"delete branch" --> "supprimer la branche"
et
"rename path" --> "renommer un chemin"
il faudrait harmoniser les deux en branche ou en chemin, peu importe ; mais il faudrait utiliser le même mots pour la même chose.

**Comment by TurboGit** [comment]
Done.
