### ISSUE TITLE
Crop to Zoom...Feature Request

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#3600]
I have always wondered about cropping to zoom. I have found that I land on the best crop composition while zooming and panning to look at other aspects or check sharpening etc....It would be nice to hit a key or activate the crop module and have it crop to the current zoom level of the image....As it stands now you create a crop from a box...scale it move it around and hit apply...only then do you get the zoomed view and often its not quite right but zooming in esp I find with a scroll wheel and dragging to pan is where I find the best compositions...so I take landmarks and try to replicate it ...I think this would be a nice feature and I don't think it would be too hard to invoke???

**Comment by vsz1lu** [comment]
I think it's an usable feature, but in one case: if You want make a very small crop from a larger pic. ex. 100% -> ~10-25% And don't forget the aspect ratio ;)

Numerical control for the crop maybe better idea.

**Comment by todd-prior** [comment]
Ya I know if for print you would need to be careful but for general display or review for example of some vacation pictures or whatever it wouldn’t really matter too much I don’t think…should be no worse then free cropping…
