### ISSUE TITLE
Image info line → Long exposures

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3603]
This line in dt → preferences doesn't work fine with long exposures:

$(EXIF_EXPOSURE) s • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • ISO $(EXIF_ISO)

E.g. 15 seconds exposure will look like 15" s which is incorrect.

**Comment by vsz1lu** [comment]
Confirmed. Printing the 's' is unnecessary in all other case too. Everybody know what is 1/30, 1/250 etc.

Shooting datas on a camera's LCD. No 'sec' or 's'.
![IMG_20191128_173344](https://user-images.githubusercontent.com/57588193/69822949-e12b3e00-1207-11ea-950b-e652a2e3d9ab.jpg)

**Comment by timur-davletshin** [comment]
@vsz1lu well, looks like double prime appears only on exposure longer than 1 second. And it is in conflict with "s" from that line. Not a big deal, but default value is just wrong.

**Comment by jenshannoschwalm** [comment]
I know what you mean and it's a bit noisy / redundant. But just see this image
![Bildschirmfoto von 2019-12-01 14-17-53](https://user-images.githubusercontent.com/50982232/69914516-ac0c2f00-1445-11ea-8490-5cac46da3217.png)

At least for some people me the missing s might confuse as the exposure is pretty non-standard.

**Comment by timur-davletshin** [comment]
Sure, it will confuse! For that purpose we need to decide whether s or " is used and avoid using both of them.
