### ISSUE TITLE
[Feature request] Preferences - shortcuts tab : add search box

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#3604]
Sometimes on forums, we could see questions about where to find a shortcut to edit. Last example focus edition on pixl.us. Actually, we have a lot of shortcuts and it's not always easy to find them on the quite long, long list of shortcuts preferences tabs.
So having a simple way to easily search with keywords a shortcut to find and/or edit will help.

**Describe the solution you'd like**

Like the now useful search box on darkroom modules panel, I suggest to just add a search box on preferences shortcuts tab (at the top of the tab).

**Comment by sams96** [comment]
Somewhat related to #3423

**Comment by Nilvus** [comment]
@sams96 : Oups, my bad. I've searched before posting but visibly quite bad... Thanks for pointing that.
