### ISSUE TITLE
UI → Selected text in default theme

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3610]
Select any text, lets say, in image information. This selection is almost the same in text color and background as regular text. It should stand out.

Screenshot (that line is actually selected):
![selected](https://user-images.githubusercontent.com/58066490/69828670-cff52800-122d-11ea-9c5b-631a79518951.png)

**Comment by blitzgneisserin** [comment]
confirmed, dt 3.0rc1 on Debian

**Comment by GLLM** [comment]
Idem on Kubuntu 19.04
