### ISSUE TITLE
Darktable 3.0.0-rc2 does not start at windows

### ISSUE THREAD

**Issue by rokondo** [darktable-org/darktable#3611]
**Describe the bug**
After starting a black box is coming up for milliseconds and disappear. Data files gets copied with a new suffix. No errors in windows log, no crash report and the debug log get not updated (from yesterday). 

**To Reproduce**
1. Open darktable from startmenu
2. Closes 

**Platform (please complete the following information):**
 - OS: Windows 10 Pro, 10.0.18362 Build 18362
 - Version 3.0.0 rc2
 - Intel(R) HD Graphics 520
 - NVIDIA GeForce GPU

**Additional context**
Tried also to disable opencl but it does not help. With rc1 everything worked fine.

**Comment by peterbud** [comment]
Please run an OpenCL test as described here:
https://www.darktable.org/about/faq/#faq-windows-opencl
and share the results.

Also start darktable from the command prompt using the command line parameters -d all, like:
`"c:\Program Files\darktable\bin\darktable.exe" -d all`
 and share the log as described here:
https://www.darktable.org/about/faq/#faq-windows-logs

**Comment by rokondo** [comment]
- OpenCL: Runned test and seems good: [log-cltest.txt](https://github.com/darktable-org/darktable/files/3905298/log-cltest.txt)
- I created a link on desktop for executing the command -d all (And copy pasted) but there is no log updated. I renamed the log file and it creates a new after launching but empty.

**Comment by rokondo** [comment]
There was a problem with the data and/or library file and after removing them it worked now.
