### ISSUE TITLE
Export module: reset button has no effect

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#3612]
**Describe the bug**
The reset button on the export module header is does nothing when clicked, despite appearing to be an active control.

**To Reproduce**
Change some settings in the module, click the reset button.

**Expected behavior**
The button should perform a reset function, or otherwise be shown as disabled.

**Platform (please complete the following information):**
Current master on Linux.

**Comment by blitzgneisserin** [comment]
confirmed

**Comment by Nilvus** [comment]
Confirmed

**Comment by wpferguson** [comment]
2.6.2 also doesn't do anything when the reset is pressed.

**Comment by junkyardsparkle** [comment]
2.6.3 doesn't either... but the button is still styled as actionable. Same for the lighttable history stack module, in fact, even though the preset button isn't. I'm guessing it's just because there's a reset routine defined. It's not a big deal, but there's been a lot of UI styling refinement lately, so... ;-)

**Comment by wpferguson** [comment]
I looked at the code.  The gui_reset routines get called, but all it does is reload the data and set the gui_elements to what they are already set to and update the gui_data.

**Comment by junkyardsparkle** [comment]
Yeah, which may be the reasonable thing in the context of this module, although it seems like a "real" reset might be useful sometimes... particularly now that this module has a fairly large set of parameters if you consider the metadata options and all.

**Comment by jpverrue** [comment]
Confirmed

**Comment by junkyardsparkle** [comment]
Hmm, looks like this probably duplicates #3014, which I missed before.

**Comment by Nilvus** [comment]
@junkyardsparkle: I suggest to continue this issue in following new one (that includes other modules and adds the idea of consistency): #7859
