### ISSUE TITLE
Compiler warnings 3.0.0rc2

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#3613]
**Describe the bug**
Compiling dt 3.0.0rc2 with clang 9 gives several OpenMP related warnings:
[warnings.txt](https://github.com/darktable-org/darktable/files/3903098/warnings.txt)
I think the code needs to be reorganized to be suitable for vectorization.

**To Reproduce**
Compile dt 3.0.0rc2 with clang 9 via
`CC=clang CXX=clang++ ./build.sh --prefix /usr/local/darktable-3.0.0rc2 --build-type Release`

**Expected behavior**
No warnings.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04, x86_64

**Comment by TurboGit** [comment]
Any proposal to avoid the warnings with clang?

**Comment by parafin** [comment]
We can silence them, but I don't think it's a good idea, because the problem is real. I'm not sure why "no warnings" is expected though, it's not an error. But it would be nice for someone to reorganize the code so that clang likes it. The problem may be that then gcc won't like it;)
Anyway, I suggest to leave everything as it is now (warnings in clang build, this bug report open).

**Comment by aurelienpierre** [comment]
Getting rid of the OpenMP warnings is simple: remove every SIMD clause in OpenMP pragmas, and write duplicate functions for the pure SS2 path with awful intrinsics even the geeks don't understand.

Clang makes me depressed.

**Comment by parafin** [comment]
It's hard to support multiple compilers for such advanced stuff...

**Comment by rabauke** [comment]
Is it sure that GCC actually vectorizes the respective loops? Possibly the code is just silently not vectorized when compiled by GCC. The OpenMP SIMD directive is not a magic bullet. I cannot find a compiler switch to give better diagnostics about OpenMP vectorization (`-fopt-info-vec-optimized` affects GCC's auto vectorizer only, afaik).

**Comment by parafin** [comment]
I guess one should check the generated assembly to confirm if openmp simd pragmas are working in gcc. Or/and benchmark the code with and without those pragmas.

**Comment by rabauke** [comment]
The reported issue affects among others the filmicrgb module. Thus I performed some benchmarks for this particular module. To get some robust results I employed various versions of GCC and Clang on two different systems. One with an somewhat dated Intel(R) Core(TM) i7-4500U CPU @ 1.80GH, and another with a more recent Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz. Qualitatively, my benchmark results do not depend on the employed compiler and the hardware configuration. Main results

- Best performance is obtained with a single OpenMP thread (dt option `-t 1`).
- Employing more the one OpenMP thread has either no effect or a negative effect on performance.
- The `simd` OpenMP instructions have no effect on performance.
- Performance the the `process` function of the filmicrgb module can be enhanced by removing all OpenMP declarations, i.e., no parallelization at all, and tweaking some details of the implementation. This revised single-threaded version requires only 70% to 80% of the computing time of the current OpenMP implementation running on a single thread.
- The `filmic_spline` function turned out to be a main performance impediment.

See https://github.com/rabauke/darktable/commit/083007c0eed6101f73b18ccff88572961b28469f for my benchmark code, and the enhanced version of the `process` function. 

I think, the lesson that should be learned here is that one has to be careful when employing OpenMP directives. It is very difficult to obtain good multi-core performance for algorithms with linear complexity.

**Comment by aurelienpierre** [comment]
I will see if I can reproduce your results. There might be some benefits to manually tweaking the SIMD vector size to half the supported size, I think @parafin posted something about AVX2 vectors being slower than AVX for the same code. 

Also, it makes no sense that the unmasked and unparallelized filmic spline function runs faster than the SIMD one. The vector size is tweaked to run the 3 polynomial evaluations as vectorized `fma` through Horner algorithm.

**Comment by aurelienpierre** [comment]
Also, just thinking of it, it might bring some good to unpack the elements of `work_profile->` used for luminance computation depending on the colour profile as simple float matrices before calling the loop, so OpenMP can optimize the function calls too. I have seen cases where passing `struct` members to in-loop functions prevented float arithmetic optimizations.
