### ISSUE TITLE
Denoise profiles gone after upgrade

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3622]
**Describe the bug**
Just upgraded from 3.0.0rc1~git11.dc641cdc9 to 3.0.0rc1~git102.e9963abec on Ubuntu 18.04 and found out that no denoise profile is available in the profiled denoise module.

Usually I start darktable with the option to keep the image database in memory without saving. After I found this behaviour, I started darktable with the '-d all' option and imported one directory with only one RAW without any XMP. Still no denoise profile.
Terminal output: [darktableopen.txt](https://github.com/darktable-org/darktable/files/3905660/darktableopen.txt)

After that I deleted all files in the .cache/darktable directory without any change.

Then I backed up my .config/darktable folder, deleted the original and started darktable again, still no profile available.

Finally I imported the folder with all RAW files I collected from 'play RAW' at pixls.us with RAWs from many different cameras, darktable did not found any profile.

**To Reproduce**
- Download example RAW here: https://discuss.pixls.us/t/playraw-narcissus/11974
- Import RAW with  3.0.0rc1~git102.e9963abec
- Open 'denoise (profiled)' module
- check if darktable found a denoise profile

**Expected behavior**
Denoise profile should be available

**Comment by timur-davletshin** [comment]
Latest Debian build works fine with that picture — https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

**Comment by pphotography** [comment]
Thank you very much, after upgrade to darktable 3.0.0rc2~git14.35d90efcd the profiles are back
