### ISSUE TITLE
rc2: color picker shows RGB Values > 255

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3628]
**Describe the bug**
I was experimenting with the new filmic RGB module regarding clipping. I made the image bright using the 'white relative exposure' slider.
The indicator for under/overexposed areas showed a small overexposed area in my image. A check with the color picker resulted in the RGB: 
max: 259, 198, 126
mean: 257, 196, 122
min: 255, 194, 120
![Bildschirmfoto von 2019-11-30 00-54-40](https://user-images.githubusercontent.com/49001045/69893032-49634800-130c-11ea-9774-07e5b2c56ee1.jpg)
Then I used the 'exposure' module and increased it by 3EV. Now the color picker gives me:
377, 320, 235

![Bildschirmfoto von 2019-11-30 01-00-19](https://user-images.githubusercontent.com/49001045/69893111-f50c9800-130c-11ea-941b-5b79be265740.jpg)

**To Reproduce**

- Open any image
- Set exposure to +3EV
- Add another exposure module
- Set exposure to +3EV in the new module
- Take sample with color picker

(I got RGB values of more than thousand and LAB more than 280 in L channel and 250 in B)

**Expected behavior**
Hard to say what has to be expected. The user may find the information useful, how far his RGB or LAB values are out of range. But I think it should be visible to the user if a value is in the range or not

**Platform (please complete the following information):**
3.0.0rc1git102.e9963abec on Ubuntu 18.04

**Comment by sams96** [comment]
This is the same as #3479?

**Comment by timur-davletshin** [comment]
I don't get what's the problem if you use higher than 8 bit representation. Color picker and histogram use 8 bit as far as I understand. Those higher (or lower) will be just cut off on export or display.

**Comment by aurelienpierre** [comment]
Actually these values are consistent if the picture is overexposed that much. darktable does't clip values.

**Comment by TurboGit** [comment]
This only happens if the screen profile is set to sRGB or AdobeRGB or whatever. If you set it to a profile created by DisplayCal for example there is no issue.

**Comment by pphotography** [comment]
Just got an upgrade to 3.0.0rc2~git35.8c0160daa and this behavior is gone. Did not change any settings in the screen profile.

I added 3 exposure modules with a setting of +3EV and wasn't able to push over 255.

Maybe this was only a bug that already is fixed. But knowing how far clipped values are could be interesting for the user.

Currently the indication of vlipped areas shows a red area and the picker shows us '255' if set to RGB.
But how far does the clipping go? If it's '260' you might even ignore that or move the exposure slider a tick, but what when it reaches to '450'?

Maybe it would be useful to have an option that toggles between showing the 'real' data even if it's out of the color space?

**Comment by wpferguson** [comment]
> This only happens if the screen profile is set to sRGB or AdobeRGB or whatever. If you set it to a profile created by DisplayCal for example there is no issue.

My screen profile is generated by DisplayCal and I got negative numbers.  Played around to see what is causing it and it seems to be setting histogram profile to sRGB(web safe).

**Comment by wpferguson** [comment]
A good image for causing this is this Play Raw from pixls.us  https://discuss.pixls.us/uploads/short-url/mqHs3CpJiMQsIXnmRXN94XFQouX.NEF  The yellow flower is full of out of gamut values.  Select a value from an overexposed area.  Change the histogram profile and notice how the values in the color picker change.

**Comment by Nilvus** [comment]
@TurboGit : this was not fixed by your color picker commits on décember, 2nd ?
