### ISSUE TITLE
[Tone Equalizer] Consistently causes DT to crash with window disappearing.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3630]
**Describe the bug**
A have an imaged edited which has used the tone equalizer.
I copy the full history in overwrite mode onto another image.
The tone equalizer doesn't make sense in  open the module. There is a yellow exclamation top right and the DT window disappears.
Starting dt with -d all does not log anything.
No opencl.

In the zip found at https://www.dropbox.com/s/ba3925dfd8kbxrn/Problem_Images_with_XMP.zip?dl=0
the 47 file was the original raw edit, the 53 file is the image where the history of 47 was copied.
xmps for both have been included. If there is any additional info you would like to have let me know, its reproducible everytime for me. 

**Platform (please complete the following information):**
 - OS: Win 10
 - Version darktable-3.0.0rc2+16~g680668c58-win64  (debug build)

**Comment by chhil** [comment]
If I copy the history without tone equalizer and then enable tone equalizer in the history stack copied to image I can still crash it.
In the image go to tone equalizer, then select the default of blend mode none and go the tab where the graph is drawn, it crashes.

**Comment by aurelienpierre** [comment]
Could you provide the backtrace ?

**Comment by aurelienpierre** [comment]
(both files tested, they open fine on Linux).

**Comment by chhil** [comment]
Unfortunately no  logs get created.

**Comment by aurelienpierre** [comment]
Without a log or the ability to reproduce, there is nothing I can do here, sorry.

**Comment by chhil** [comment]
Unfortunately I am not aware of any other way than -d all. 

Maybe it's a Windows only problem and someone on a Windows machine can try reproduce it. 

It's so frequent that I avoid using the tone equalizer now.

**Comment by jenshannoschwalm** [comment]
Are you serious? No log at all?

**Comment by chhil** [comment]
Currently not seeing this happen. Closing.
