### ISSUE TITLE
[Feature] Folders in collections : right-click > open in file manager

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3633]
When browsing through pictures with folders in Darktable, I sometime need to go check the actual disk folder containing those pictures. I'm not sure I can do this.

A new right-click option on Folders in collections > "_Open in file manager_" could help the user do so in 1 click.

Thanks
GLLM

**Comment by ptilopteri** [comment]
there is a lua script which will provide what you want, see:
  https://github.com/darktable-org/lua-scripts/blob/a3d0983d3379f18d07db2512babebfbf1c1addcc/official/image_path_in_ui.lua
