### ISSUE TITLE
[Feature] Reset/delete/empty a shortcut assignment.

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3637]
Currently, the user can reset all shortcuts to their default values, at once.

I'd like to be able to rest a unique shortcut to its default value.
(A right click > reset to default, on the said shortcut, could work)

Note: if the reset is supposed to work per-shortcut, then I guess it required :)

Thanks
GLLM

**Comment by AlicVB** [comment]
hi,
I'm not sure to see a really usecase for this feature... Accels keys are personal choices. Default values are not really meaningful, except if you need to follow some tutorials, and in this case, you'll need to reset all of them...
Can you describe the problem you want to solve ? (if it's related to #3636, the mentioned problem is clearly a (small) bug and will be fixed soon)

**Comment by GLLM** [comment]
hi @AlicVB !
Once again you are right ... 
Actually, I assigned a shortcut (unassigned by default) ... and couldnt find any way to just disable the shortcut assignment.
So I thought, maybe use the "reset default value" will work. But it does not work at a specific setting level.

Actual use case is : remove/disable the shortcut assigned to an action ... so that it is empty again.
I'll edit the title :)

Thanks

**Comment by AlicVB** [comment]
have you tried to press DEL on the shortcut ?
(even if I know that it can be rude, you may want to read the manual and search for other issues before posting... thanks !)

**Comment by GLLM** [comment]
@AlicVB : you are not rude :)

But ...
Let's suppose I want to remove the shortcut for _Select none_, which is CTRL+SHIFT+A
![image](https://user-images.githubusercontent.com/3989573/69905483-65222900-13b4-11ea-8a71-7bcb893df26b.png)

I click on the said shortcut once, to select it.
Then I click on [Del] on my keyboard :
I get this
![image](https://user-images.githubusercontent.com/3989573/69905497-96025e00-13b4-11ea-93bd-1b544df46306.png)

No right click option is available.

And if double click on the shortcut and press [Del], I get the following :
![image](https://user-images.githubusercontent.com/3989573/69905514-c2b67580-13b4-11ea-97fa-94700a583ce9.png)
Of course I dont want to set Del as shortcut ... but pressing [Del] has no effect on the said shortcut.

Conclusion, as of now, I'm not able to remove this shortcut !

What did I miss ?

Linux Kubuntu 19.04 with i7-7700k / 32GB RAM / NVidia GFX 1070
darktable 3.0rc2

**Comment by AlicVB** [comment]
right, I see : you need to select it (simple click), not set it (double click) and then press [backspace] (not DEL, sorry for the mistake)

**Comment by GLLM** [comment]
@AlicVB : working with Backspace. Had only tried Delete (even before your reply).
"Right-click > reset" would be more user friendly and easier to find ;)
