### ISSUE TITLE
SONY ILCE-6600

### ISSUE THREAD

**Issue by RodrigoRiosC** [darktable-org/darktable#3638]
I've uploaded two raw images from the new SONY ILCE-6600 cammera to get Darktabe support it. Thanks to you all.

**Comment by LebedevRI** [comment]
Thanks, support added (color matrix + rawspeed).
Though i'm not updating rawspeed submodule yet, so if you really need it working right now,
if you can build darktable yourself, do make sure to build darktable git master branch,
but for submodule be sure to checkout the rawspeed develop branch.
