### ISSUE TITLE
Mask manager + Compress history stack

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3640]
There is an odd interaction between mask manager and compress history stack button.

1. Load any raw file with supplied XMP file.
2. Delete all shapes in mask manager via right clicking on every on them. It creates new new line in history manager.
3. Click compress history stack button in history manager.

Problem:
Shapes restored in history manager which is wrong.

Additional info:
Couldn't reproduce it on fresh imports, only on some old files from previous dt versions.

File:
[_DSC0259.NEF.zip](https://github.com/darktable-org/darktable/files/3907445/_DSC0259.NEF.zip)

**Comment by jenshannoschwalm** [comment]
Sure, this is know and postponed after 3.0. See #2955 
atm it doesn't hurt except you can't remove masks after history compression.
Concider closing as this is already in the todo-soon pipeline :-)
