### ISSUE TITLE
No way to copy image location or export location.

### ISSUE THREAD

**Issue by borissmidt** [darktable-org/darktable#3641]
Dear Darktable developers,

I really like darktable and use it instead of lightroom and i'm starting to learn photoshop to step up my editing options. So my workflow is currently rate and edit the photos in darktable, then if i want to retouch or give it more character i move to photoshop.

What currently doesn't work wel:
- You cannot copy the raw location, except by doing a select all on location and then copy which is cumbersome.
- Nor is there an easy way to open the export folder that would be used to export the raw image.

Possible solutions, give a right click menu with copy image location. Add a keybinding to this.
So there is a configurable keybinding to copy the image location.

To give you some more context:
My archive is something along the line of $year/shoot-name/$day so if i search for photos i use darktable filter for the highest rated images. So it requires some work to find the right folder. especially because the raw location is abbreviated by `...`

Ps. resetting the defualt keybindings doesn't work in darktable 3.0.0RC2 i accidentally binded escape to copy image. I expected escape to cancel the keybind.

**Comment by junkyardsparkle** [comment]
In general, Lua scripts are good for this kind of thing, but I don't think there's a generic way to set/get clipboard contents directly... you would probably need to call some platform-specific utility for that. There are plenty of examples for directly calling another program for various purposes, though: https://github.com/darktable-org/lua-scripts

**Comment by EC1000** [comment]
[OpenInExplorer.lua](https://github.com/darktable-org/lua-scripts/blob/master/contrib/OpenInExplorer.lua) opens the raw folder in file manager.

**Comment by borissmidt** [comment]
Oh thank you i will try it out tomorrow.
