### ISSUE TITLE
colorpicker: in point mode size of crosshair depends on image orientation

### ISSUE THREAD

**Issue by upegelow** [darktable-org/darktable#3645]
**Describe the bug**
The color picker in point mode is displayed as a square with a crosshair. The size of this symbol is dependent on the image orientation. It's larger for an image in landscape orientation and smaller for an image in portrait orientation:
![Landscape_Screenshot_20191201_110505](https://user-images.githubusercontent.com/1794020/69912516-aead5b00-142a-11ea-89b0-6fe5f8b04435.png)
![Portrait_Screenshot_20191201_110439](https://user-images.githubusercontent.com/1794020/69912519-b5d46900-142a-11ea-86fe-16f9315453d5.png)

**To Reproduce**
1. Open image in darkroom
2. Activate the color picker in point mode
3. Zoom image to 100% magnification
4. Toggle between portrait and landscape orientation in the orientation module
5. See the difference in the crosshair size

**Expected behavior**
At a given magnification level the crosshair should have a defined size. Maybe dependent on image resolution but not on image orientation.

**Platform (please complete the following information):**
 - OS: OpenSuSE 15.1
 - Version: 3.0.rc2

**Comment by jade-nl** [comment]
Confirmed.

Version 3.0.0rc2 (+39)
Debian 10(.2)

**Comment by TurboGit** [comment]
This is only GUI stuff, but will fix as part of the 3.0 GUI rework. Every details count :)
