### ISSUE TITLE
Artifacts on right corner of thumbnails

### ISSUE THREAD

**Issue by upegelow** [darktable-org/darktable#3646]
**Describe the bug**
Thumbnails of Images from my Canon 5DMkIV show artifacts on the right border. These artifacts are quite obvious if the lowpass module with a high radius and high saturation is applied. For me the artifacts manifest as a greenish halo (see screenshot). The tint of the green artifact is similar or the same than the color of the non-whitebalanced image.

The artifact is only visible in thumbsnails at certain magnification steps. It's not visible in the the other darktable views nor in exported images. It goes away if I crop away about 15 lines from the right hand side of the input image.

**To Reproduce**
1. Open 5DMkIV image into darktable
2. Reset history stack
3. In darkroom: activate lowpass module with a radius of 150 and saturation of 2
4. switch to another image or leave darkroom to have the thumbnail be reprocessed

**Expected behavior**
No artifacts.

**Screenshots**
![Screenshot_20191201_121239](https://user-images.githubusercontent.com/1794020/69913168-7d398d00-1434-11ea-8cb9-737ad66dfb24.png)

**Platform (please complete the following information):**
 - OS: OpenSuSE 15.1
 - Version: 3.0.rc2

**Additional context**
I personally don't assume that the lowpass module is the cause of the issue. Most likely the rightmost part of the scaled down thumbnail image (maybe only one line) has an artifact. The lowpass module just smears it over and makes it more visible.

**Comment by jenshannoschwalm** [comment]
I took two raws from pixls ("Canon - EOS 5D Mark IV - RAW (3_2).CR2" and "Canon - EOS 5D Mark IV - RAW (3_2)(1).CR2" and both did not show any artefacts. (Fedora 31, git master) Neither cl activated or not. ???

**Comment by upegelow** [comment]
> Neither cl activated or not. ???

Both. The artifacts are a bit more pronounced with OpenCL active.

Here is an example image which produces the issue for me:

[https://www.dropbox.com/s/93z6vgc6i9rpjer/IMG_4347.cr2?dl=0](url)

**Comment by upegelow** [comment]
Just checked. Issue is also present with darktable 2.6.3.

**Comment by timur-davletshin** [comment]
No problem on Debian 10. See no artifacts.

**Comment by jenshannoschwalm** [comment]
@parafin your link is not valid (any more?).

I tested thumbnails generated from raw or not. Still can't reproduce.

**Comment by upegelow** [comment]
I took one image from here:
[https://www.dpreview.com/sample-galleries/9485291827/canon-eos-5d-mark-iv-sample-gallery/6665024062](url).

This is my history stack:
[793A0578.CR2.xmp.gz](https://github.com/darktable-org/darktable/files/3912704/793A0578.CR2.xmp.gz)


And here is a screenshot of the thumbnail. Not a very strong artifact but still visible on the right border. This is with OpenCL. With CPU processing the artifact is a bit weaker but still visible.
![Screenshot_20191202_191734](https://user-images.githubusercontent.com/1794020/69984054-71cf8a00-1538-11ea-8c52-ded0fabeef83.png)

**Comment by jenshannoschwalm** [comment]
I still can't reproduce whatever options for thumbnails i choose. I guess you already checked it's also the thumbnail.jpg that's corrupt and not the presentation on the lighttable surface?

**Comment by upegelow** [comment]
It's the jpegs that show the artifact.

I have some suspicion that the root cause is an artifact which already resides in the raw image. I have some files that show it, others not. The same with external resources like dpreview. I have yet to find any systematic. Wild idea: effect is visible only on images taken with long focal length (> 200mm).... I know :)

Certainly this is only a cosmetic problem. Not worth to invest too much time.

**Comment by junkyardsparkle** [comment]
> Wild idea: effect is visible only on images taken with long focal length (> 200mm).... I know :)

Something related to lens correction, maybe?

**Comment by upegelow** [comment]
Lens correction is not active.

**Comment by upegelow** [comment]
Here is the debug output for developing the thumbnail. This time without the lowpass filter:

```
86,629098 [dev_pixelpipe] took 0,018 secs (0,103 CPU) initing base buffer [thumbnail]
86,644790 [dev_pixelpipe] took 0,016 secs (0,015 CPU) processed `Raw-Schwarz-/Weißpunkt' on GPU, blended on GPU [thumbnail]
86,648364 [dev_pixelpipe] took 0,004 secs (0,002 CPU) processed `Weißabgleich' on GPU, blended on GPU [thumbnail]
86,655292 [dev_pixelpipe] took 0,007 secs (0,006 CPU) processed `Entrastern' on GPU, blended on GPU [thumbnail]
86,658867 [dev_pixelpipe] took 0,004 secs (0,003 CPU) processed `Eingabefarbprofil' on GPU, blended on GPU [thumbnail]
86,660934 [dev_pixelpipe] took 0,002 secs (0,001 CPU) processed `Ausgabefarbprofil' on GPU, blended on GPU [thumbnail]
86,661421 [dev_pixelpipe] took 0,000 secs (0,001 CPU) processed `Gamma' on CPU, blended on CPU [thumbnail]
```
And here is the mipmap in question. You need to magnify it in order to see the artifacts. But they are visible on the rightmost line of pixels.
![139](https://user-images.githubusercontent.com/1794020/70024859-9d379080-159b-11ea-8574-c1e869228081.jpg)

**Comment by chhil** [comment]
I have seen pink artifacts but not off late.

Recently I got artifacts when I shot in high resolution mode on my G9 (shoots in 80 megapixel with some sensor shifting). Are you perhaps shooting in a similar high res mode?

**Comment by upegelow** [comment]
Well, I shoot in raw with my Canon 5DMkIV. This means a resolution of 6880 x 4544 pixels.

I meanwhile digged a bit deeper and found that the problem occurs very early in the pixelpipe, namely already in the rawprepare module. The pixelpipe wants to process a thumbnail with a very low resoltuion in the range of 150 x 100. This requires a calculation of the input region of interest (roi_in) down the whole pixelpipe to the full size of the input image in module rawprepare. What now happens is that this calculation can lead to an input image width of 6886 pixels, so 6 pixels more than the image provides. 

Reading from those "pixels" outside of the right border will give different results between CPU and GPU. On CPU it will read the first pixels of the next pixel row (or read out of the buffer on the last row). On GPU reading past the image buffer will repeat the outmost valid pixel value. As we talk about pre-demosaiced data it is obvious that luminance and color are off, which is what I see. This also explains why CPU and GPU show a different level of these artifacts.

Now the question is how to fix this. I have yet to find the root cause of the wrong roi. I fear that this is mostly a rounding problem as x-offset, y-offset, width and height are stored as integer values. Scaling up from 150 to 6880 means that a delta of 1 ends up with over 40 pixels. The roi also holds a scaling factor (float) which plays a major role in the calculations and suspiciously seems to be a bit off in these cases. I will need to have a closer look at this.

**Comment by upegelow** [comment]
OK I found the culprit:

https://github.com/darktable-org/darktable/blob/a24e84de4259117d678f49fb98e994d52ece4967/src/common/imageio.c#L756-L757

As assumed in my previous comment the roi calculation for thumbnails involves a huge scale factor where a delta of 1 in the width of the output image means a delta of 40 in the width of the required input image.

The relevant function in imageio.c calculates the allowable width and height of the output image based on the scale factor and the available width/height of the input image. But then it rounds the value to the next integer, which means that in the worst case the pixelpipe reads outside the boundaries of the input image. 

In my opinion this should never be allowed. The calculation needs to floorf() to the next lower integer value instead.

The code in question is coming from the early days of darktable (2010) and has not been questioned since then. I am hesitating to make changes here shortly before the release of 3.0 and without intensive testing. I will prepare a PR to be tested and potenially merged for 3.0.1.

**Comment by parafin** [comment]
I would say reading outside of the allocated buffer is something that needs to be fixed ASAP, since it might lead to crashes too, ain't it?

**Comment by upegelow** [comment]
> ... since it might lead to crashes too, ain't it?

Could be if the buffer's end lies at a page boundary. In reality this does seem to happen very seldomly, else we would have long since noticed. As far as I can see the code in question is practically unchanged since 2010.
