### ISSUE TITLE
Inconsistency in image development: copy all and paste all produces different results on the same image

### ISSUE THREAD

**Issue by EdgarLux** [darktable-org/darktable#3650]
**Issue description**
I have a developed image in lighttable, then I duplicate it and discard the history. Later, making "copy all" from original and "paste all" produces different results compared with original image (the histogram change).

**Steps to reproduce the behavior:**
On lighttable
1. Select a developed image and duplicate it
2. Discard history stack on duplicated
3. Make copy all from original developed image
4. Make paste all on duplicated 
5. The result varies compared to the original 

**Expected behavior**
Get the same development result on a duplicated image with copy all / paste all

**Developed Image vs. Duplicated / discarded / copy all & paste all image**
![Original](https://user-images.githubusercontent.com/47407674/69926504-59009f00-147a-11ea-8595-bce72c7761d7.png)
![side-panel2019-12-02_10-25](https://user-images.githubusercontent.com/47407674/69976155-209aa880-14ee-11ea-8210-d25095b93e88.png)
**Histogram
Developed Image vs. Duplicated / discarded / copy all & paste all image**
![Histogram](https://user-images.githubusercontent.com/47407674/69926734-3d49c880-147b-11ea-9a74-ed803db24acb.png)

**Platform:**
 · OS: Parrot OS 4.7 (based on Debian 10)
 · Version: 3.0.0rc2~git39.e6affab93 (without opencl)

**Additional context**
As seen in the images, the order and number of development steps of the history stack change on duplicated. The orientation and base curve modules appear twice.

**Comment by ptilopteri** [comment]
was the first edit performed on a version < 3.0 ?

the change from filmic to filmicRGB may be the reason

**Comment by EdgarLux** [comment]
> was the first edit performed on a version < 3.0 ?
> 
> the change from filmic to filmicRGB may be the reason

It's a new edition. There is no RGB filmic module in the edition. The modules used are seen on the right side, but with a compressed history stack.

**Comment by TurboGit** [comment]
Would be nice to have the full stack on the left. And even better the list of active module on the right panel.

**Comment by EdgarLux** [comment]
> Would be nice to have the full stack on the left. And even better the list of active module on the right panel.

Of course, I just updated that comment. On the right side, the 21 steps (19 modules) are active and are the ones that are active on the left side. But in different order and avoiding unnecessary steps. The strange thing is that the base curve and orientation modules appear duplicated (if unnecessary steps are deleted, only one of each should appear).

**Comment by TurboGit** [comment]
> And even better the list of active module on the right panel.

As I said better to have the actual activated modules on the list of active modules on the right. Here it is quite difficult to analyze the 35 entries + 21 to see how they differ. Can you do that?

**Comment by TurboGit** [comment]
Also, I'm asking that as the actual order in the active module may be different and this is a good data point whereas the order in the history has just no meaning.

**Comment by EdgarLux** [comment]
> As I said better to have the actual activated modules on the list of active modules on the right. Here it is quite difficult to analyze the 35 entries + 21 to see how they differ. Can you do that?

I compared both history stack and they have the same modules. Only the two additional steps mentioned differ.

>Also, I'm asking that as the actual order in the active module may be different and this is a good data point whereas the order in the history has just no meaning.

Ok, now I understand.  I'll take a screenshot of that. I thought it was important because it was the behavior of dt 2.6.x: to have the same order in the history stack.

**Comment by MStraeten** [comment]
Did you use raster masks? Maybe providing both xmps might help to analyze the difference

**Comment by EdgarLux** [comment]
As seen in the image below, the sequence of the modules changes after the tone equalizer (from bottom to top). The same modules are active on both sides. @TurboGit 

Colored area: order matching
Uncolored area: the order differs

**Developed Image vs. Duplicated / discarded / copy all & paste all image**
![Modules-position](https://user-images.githubusercontent.com/47407674/69984088-e46f4400-14fd-11ea-960c-74a703f53ac7.png)

**Comment by TurboGit** [comment]
Can you post here the XMP of the original image (left one)?

**Comment by TurboGit** [comment]
Note that the right order is correct. The base curve should be between the input and output color profile. So it probably means that on the left you have not only edited the picture but also moved some modules. Is that right?

**Comment by TurboGit** [comment]
Also vignetting should be below "output color profile".

**Comment by EdgarLux** [comment]
> Did you use raster masks? Maybe providing both xmps might help to analyze the difference

I am not using raster mask or drawn mask. I'll upload in txt format, cause xmp isn't supported .

[6020-T5.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3912892/6020-T5.CR2.xmp.txt) original developed (left side)

[6020-T5_01.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/3912893/6020-T5_01.CR2.xmp.txt)  duplicated / history discarded / copy all / paste all (right side)

**Comment by EdgarLux** [comment]
> Note that the right order is correct. The base curve should be between the input and output color profile. So it probably means that on the left you have not only edited the picture but also moved some modules. Is that right?

No, I didn't do it.. I only started to develop in the sequence shown as in the history stack.

**Comment by TurboGit** [comment]
Well I don't know how you get to this point with the original image but I just did apply all modules as shown in your active module and I have the proper order on my side.

![image](https://user-images.githubusercontent.com/467069/69992238-8bc59880-1549-11ea-8a25-272c5413b8a1.png)

Sorry for the French UI but the name for "vignette" is bellow the output profile and "base curve" is between input (entrée) and output (sortie) color profile.

**Comment by TurboGit** [comment]
Ok, in your XMP colorout is 58 whereas the default is 69 and the iop_order_version for this image is 2. It means that your image is an old edit. So it seems that your original image iop-order is damaged, most probably because it was edited with a broken dev version. There was many issues about iop-order and we expect all of them to be fixed now. The good point here is that at least the paste on the new image (iop-order-version 5) is correct.

To me there is nothing to be fixed at this point.

**Comment by EdgarLux** [comment]
>Sorry for the French UI...

Pas de problème, je comprends aussi le français.

>Ok, in your XMP colorout is 58 whereas the default is 69 and the iop_order_version for this image is 2. It means that your image is an old edit. So it seems that your original image iop-order is damaged, most probably because it was edited with a broken dev version. There was many issues about iop-order and we expect all of them to be fixed now. The good point here is that at least the paste on the new image (iop-order-version 5) is correct.
To me there is nothing to be fixed at this point.

Ok, merci.

This let me with some questions. Like I comment before, with version 2.6, I saw the same order on history stack when I did the same process (it was very useful to me). The question is: there will be any change or this will be the new behavior on history stack order?

Other question is, if this affect my older edits (like in 2.6) and what can I do for mantain those edits intact?

**Comment by TurboGit** [comment]
Nothing will be changed automatically but we will provide a way to migrate each picture from iop-order in 2.6 to the latest iop-order. For sure a picture edited in 2.6 and not modified will stays the same. As seen here, if an old edit is modified with 3.0 there may be issues and we will encourage people to use the new iop-order in this case.

**Comment by EdgarLux** [comment]
> Nothing will be changed automatically but we will provide a way to migrate each picture from iop-order in 2.6 to the latest iop-order. For sure a picture edited in 2.6 and not modified will stays the same. As seen here, if an old edit is modified with 3.0 there may be issues and we will encourage people to use the new iop-order in this case.

Thanks a lot!
