### ISSUE TITLE
[bug] White Balance - Copy & pasting white bal not consistent between different cameras

### ISSUE THREAD

**Issue by MWP** [darktable-org/darktable#3652]
I have different two cameras (Nikon D500, D750) that I use together at the same time.

If I manually adjust white balance on an image from one camera, then use the lighttable view to copy the whitebal settings to images from the other camera, I find the values pasted do not match the first camera at all.

This makes copy & pasting white bal settings impossible unless I copy and paste for only the same type of camera.

RT 3.0.0rc2 official build on Win10

**Comment by parafin** [comment]
At what values are you looking? Temperature and tint are irrelevant, you should look at RGB coefficients, they should match. But copy-pasting WB from one camera to another in general doesn't make sense. These settings are specific to sensor.

**Comment by MWP** [comment]
Yes, im looking at temperature and tint.

It may not make sense from a processing point of view, but it absolutely does for a usage point of view.
If i copy 5700/1.000 from one image to another, I should get 5700/1.000 on that image also... just as i would do if i were to manually enter those values.

**Comment by parafin** [comment]
Temperature and tint are calculated from RGB coefficients, which are the ones that are saved in the history. So numbers are expected to be different. Also they aren't really reliable. I would say your use-case is invalid and unsupported, and this bug should be closed. But I'll leave it for someone else to give an opinion too.

**Comment by MWP** [comment]
You're talking about it from a internals/processing point of view again, not a usage point of view.

When the majority of users adjust white-bal, they do it by temp & tint. Not by RGB values.
When I copy and paste values, i would expect DT to copy and paste temp & tint (I dont care what DT is doing internally) values which would give the results I was hoping to see.

**Comment by parafin** [comment]
It's not possible to get the results you are hoping to see in general case.

**Comment by pphotography** [comment]
D500 and D750 do have different sensors with different sizes. The D500 has as DX (APS-C) sensor while the D750 uses FX (full format). I doubt both use the same white balance parameters.

To be sure, you can read out your white balance parameters for all presets from your RAW files, example here:
https://www.rawdigger.com/node/429
Are they the same for both cameras?

**Comment by MWP** [comment]
This is the particular problem im facing...

I had a wide angle lens on my D750, and a telephoto on my D500.
It's a sporting event, with ~500 keepers taken on the day which im now adjusting (all photos in together sorted by time).
I had my D750 set to auto-white bal, and my D500 set accidentally to manual.

I've found a mid-line white bal from the D750 which is about right for all the photos... its 7500 temp with 1.005 tint.
Ive set one D750 photo to that white bal, copied it in light table, and pasted it to all the 500 photos.
All the D750 photos look fine. All the D500 photos are very wrong.

If you asked any average DT user (like myself) to do this, they would probably do exactly as ive just done, expecting the copied white bal settings to be copied properly across all the photos.
Most other photo editing software would probably do it just fine (i know LR does).

DT doesn't... its unexpected behaviour. Its a problem/bug.
It doesn't matter if dev's think "oh yes, its does that because of X". It's not what should happen.

**Comment by parafin** [comment]
Just enter temperature and tint by hand if it looks OK to you. In general it's not a valid operation - you won't get the same white balance, because these numbers are just estimation. I don't think it's a good idea to support your use-case, because it will give false promises to users.

**Comment by MWP** [comment]
So keep temp/temp info as well, and only apply via that method if the camera is different?

**Comment by parafin** [comment]
That's exactly the false promise I'm talking about - it won't produce the results you expect in general case, because these numbers are just estimations with unknown precision. I think I'm repeating myself already.

**Comment by MWP** [comment]
But it's closer (probably very close) to the desired result.
Better than a completely incorrect result (as it is now), or no result at all.

**Comment by junkyardsparkle** [comment]
> Most other photo editing software would probably do it just fine (i know LR does).

Realistically, it can't, even if it pretends to. There's just no way that software can do this accurately with consumer cameras without doing a bunch of calibration first. The spectral characteristics not only vary between camera/sensor models, but even between copies of the same model, and any given lens will add its own shift to this. There's just no way for software to know what the spectral relationship between two different camera/lens/filter/etc combinations is... *unless you provide that information*.

So, try this: shoot a gray/white card in lighting that approximately resembles the lighting at the scene (as close as possible, anyway) with each camera (using the same lenses as at the scene). Spot white balance this reference in darktable for the "master" camera. Copy/paste that setting (remember, it's the RGB multipliers that matter, ignore the other meaningless stuff) to the reference shot taken by the "slave" camera. Now, you select the target area in the "slave camera" image using the color picker module, and make it a "live sample".

Now, you use a color adjustment module to adjust the RGB values shown to neutral gray. You could use a second instance of the white balance module, but for various reasons related to how presets and styles work, using the "channel mixer" module will keep things simpler later. Adjust the RGB multipliers under each of the red, green, and blue dropdown menu entries, using only the respective slider in each. Now, you can make this a preset and/or style and apply it to the "slave camera" images only. They should then be white balanced to match the "master" camera (assuming the same WB setting has already been applied to both).

This same preset should work fine for a wide range of "normal" light sources, but YMMV. Also note that there can still be differences in the color rendering between both cameras, even when calibrated to the same neutral reference... but that's a whole 'nother issue. :-)

**Comment by MWP** [comment]
Thank you for the more detailed description of the problem.
By the sound of it, I was just lucky that manually setting the same temp & tint to images of the same scene from the two different cameras worked correctly. I guess that makes sense too since they are both Nikons of about the same age.
I guess if one of the cameras was a different brand, the chance of it working out would have been much lower.

Thankyou for the possible solution too, I'll give it a try.

**Comment by junkyardsparkle** [comment]
> By the sound of it, I was just lucky that manually setting the same temp & tint to images of the same scene from the two different cameras worked correctly. I guess that makes sense since they are both Nikons of about the same age.

In some cases this might result in "close enough", but the main point is that in darktable at least, the primary use of the temp/tint controls is to allow you to manually change the relationship of the RGB values in a more natural and intuitive way, and the values they display should be taken "with a grain of salt". Maybe the user interface could eventually be improved somehow to make this situation less confusing.
