### ISSUE TITLE
[White Balance] Copying WB with 'camera' preset shall honor WB from camera

### ISSUE THREAD

**Issue by martinky82** [darktable-org/darktable#3654]
**Describe the bug**
When I copy & paste setting between images with the WB plugin set to 'camera', WB of the latter image is actually not as it should (ie. WB from camera) but the value set in camera for the former. This issue makes bulk editing of images really painful as the WB must be fixed for each of the edited images separately.

**To Reproduce**
1. Have two images with different WB from camera (let's say one in sunlight, the other in shade)
2. Let (set) WB on the former to 'camera' and copy the stack from it
3. Apply the stack to the latter
4. The latter WB is wrong now
5. WB can be fixed in lighttable by selecting 'camera' again

**Expected behavior**
Both images take the WB from camera, no need for 5

**Comment by jenshannoschwalm** [comment]
I don't concider this a bug but more a misunderstanding of the workflow.

1. By default images take the camera setting read from raw data.
2. If you copy the whitebalance history from one image to another you are perfectly fine if the camera is the same. If different cameras you should not copy "whole" but select items you want. This feature is the better option in most cases as you have to think before what you are doing :-)
3. There are so many camera specific balances that behave quite different or in many case are non-existant for cameras. There is no way to copy this.

**Comment by martinky82** [comment]
Well, I think is I have a module set to use an automatic setting and copy it to another image, the automatic shall be copied rather than the value it set for the former image. IIRC, in darktable 1.x and 2.x it worked that way. It has nothing to do with the camera brand - if the camera sets 3000K for image #1 and 6000K for image #2, I have 'camera' preset selected in the in WB module for #1 and copy it to #2, I expect the WB module honors the 'camera' preset and uses 6000K for #2, rather than 'camera' being set as the preset along with the value of 3000K (which is not just wrong, but also misleading, because the WB actually used then is anything but the value set by the camera)

**Comment by parafin** [comment]
If you want camera white balance, then don't copy anything, it is default anyway. Copying on the other hand is useful if you want to copy the actual white balance from one picture to another, not auto flag.

**Comment by martinky82** [comment]
OK, I take your point. Anyways, I such case the preset shall be switched to 'manual' because: the WB actually used then is anything but the value set by the camera.

**Comment by parafin** [comment]
That is indeed a bug.

**Comment by junkyardsparkle** [comment]
These bugs? #3228 #3521

**Comment by parafin** [comment]
Yeah, these 3 seems to be duplicates. Closing this one.
