### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by snaggen** [darktable-org/darktable#3655]
I have a laptop with HiDPI and then I have a second screen which is regular DPI. Unfortunately this scenario is not handle very well in XWayland. So to work well with a multi screen setup of different DPI (and for photo editing I assume it is quite common to have multiple screens) it would be nice if darktable could be made work with Wayland natively. And since darktable now is going to use GTK3, this should not be a very big issue. I took a quick look at the code, and it seems in fact that it is very little X11 dependent code left.

Wayland is also the default rendering stack on Fedora, and Ubuntu is moving towards using that.

**Comment by aurelienpierre** [comment]
darktable has been using GTK3 forever, I don't understand what is needed to make darktable run on Wayland compared to Xorg.

Notice that Wayland developers have made very clear that they don't care about colour management support, so it is not considered an option for graphic arts at this point, until further notice : https://discuss.pixls.us/t/wayland-color-management/10804/417

If you want consistent colour management for graphic arts, use Xorg, or better, MacOS.

**Comment by snaggen** [comment]
I did a quick grep for x11 in the code and found a few uses of x11 functions. So replacing them with alternative gdk versions if possible, should probably make it wayland compatible.

**Comment by snaggen** [comment]
And about color management, I thought that was merged years ago? https://www.phoronix.com/scan.php?page=news_item&px=MTM2OTQ

Did that not happen, or is there an issue with it?

**Comment by aurelienpierre** [comment]
The post you mention is about Weston, not Wayland itself. Weston is one window compositor. 

There are known issues with Wayland and multi-screen setups : https://www.reddit.com/r/DarkTable/comments/ek0lue/exported_image_much_darker_than_preview/

**Comment by aurelienpierre** [comment]
I just checked the code, X11 support is only checked at compilation time to enable xatom support. AFAIK it is fully optional.

**Comment by parafin** [comment]
https://github.com/darktable-org/darktable/pull/1453
https://redmine.darktable.org/issues/11535
https://redmine.darktable.org/issues/11041
https://redmine.darktable.org/issues/11818

Otherwise it's completely fine:)) But seriously, someone needs to test it thoroughly, before enabling Wayland support.

**Comment by snaggen** [comment]
Did a quick test, commented out forcing of x11 backend and disabled xatom and found this:
* Menus seems to work from a quick test, looked ok
* Buttons at the bottom of darkroom (raw overexposed, over/underexposed, softproof, gamut check) seemed to work
* Scrolling the lighttable worked using the mouse and trackpad. 
* The stars and color dots at the bottom of the light table did not work. 
* The window border did not look native
* The lighttable and darkroom area have some scaling issues. Toggling maximized caused it to scale wrong and have rendering artifacts. 

So, there are some issues that someone need to look at, but it seems that they are not as many as before if my impressions are correct (probably due to bug fixes in the gnome wayland compositor).

**Comment by snaggen** [comment]
It sounds like the new lighttable based on proper gtk widgets have the potential to improve the Wayland issues. Have it been tested under Wayland?

**Comment by matze** [comment]
> Have it been tested under Wayland?

I just ran Darktable master with `GDK_BACKEND=wayland` and checked using `xeyes` that Wayland is indeed used. Everything related to processing images works as expected. However, the title bar looks totally out of place (no idea if anyone is willing to add a proper `GtkHeaderBar`) and resizing the window by dragging the border does not work.
