### ISSUE TITLE
crop and rotate: colored guides

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3657]
**Is your feature request related to a problem? Please describe.**
The guide lines in grey colors are sometimes hard to see, especially when working monochrome. Example:
![crop_guide01](https://user-images.githubusercontent.com/49001045/69976347-219cfb80-1529-11ea-8d8d-eaa28cf0c023.jpg)

**Describe the solution you'd like**
With a color picker for bright and dark color the user can choose his own colors for the guide lines. Example:
![crop_guide02](https://user-images.githubusercontent.com/49001045/69976375-2bbefa00-1529-11ea-8d27-70741848926b.jpg)

**Comment by jade-nl** [comment]
I second this.

And maybe not limit this to the crop and rotate module, other module have guides/help lines too. Could it be so that we can choose the colour of the help/guide lines in the preferences section?

**Comment by pphotography** [comment]
That's a good idea, should be configurable for mask shapes, too.

**Comment by AxelG-DE** [comment]
2 second this too

**Comment by AxelG-DE** [comment]
I'd still appreciate to see this upgrade come to reality...

**Comment by pphotography** [comment]
I don't think this should be closed due to inactivity. There are many good ideas documented in several issues that just wait to be implemented.

**Comment by dterrahe** [comment]
@elstoc Is it possible to have a click on the new new overlay color icon immediately open the list of color options rather than having to move the mouse and click on the (single) option in the menu?

Or are you planning on adding more items to the menu?

**Comment by TurboGit** [comment]
@dterrahe : note that you can use `Ctrl+O` to quickly change the overlay color too. Your idea is ok until we add some more items into the main menu, so I'm not sure we want to go this path especially since none of the combo are behaving this way.

**Comment by dterrahe** [comment]
Sure, sure, it just feel like a little overkill to allocate a whole icon for one function and then still require an extra step to access it :-) But yes, if more functionality is planned...

**Comment by elstoc** [comment]
I think I agree with @dterrahe. The styles and presets icons on the left-hand-side work like this. @TurboGit I can't think of any additional comboboxes we might add to this.
