### ISSUE TITLE
[CSS with icons] Modules' icon not vertically aligned

### ISSUE THREAD

**Issue by homer3018** [darktable-org/darktable#3659]
Modules' icons are not vertically aligned making it look awkward.

**To Reproduce**
1. Select any theme with icons
2. Go in the darkroom and see

**Expected behavior**
A proper alignment.

**Screenshots**
<img width="353" alt="Screenshot 2019-12-02 at 21 48 33" src="https://user-images.githubusercontent.com/36423314/69994707-bbc36a80-154e-11ea-8a8c-5f69ef824b54.png">

**Platform (please complete the following information):**
 - OS: MacOS 10.15
 - Version 3.0.0 rc2 (680668c58a1415322b89af0a689cb792e747bd6f)

**Comment by Nilvus** [comment]
I had already fixed that few months ago on these CSS. Another thing broken since... I will see that.

**Comment by homer3018** [comment]
@Nilvus I do remember, and I'm also seeing your `margin` in the current theme. Not sure why but it seems we've gone back to the previous behaviour. Please confirm whether or not you have the same on your side.
Thanks for looking into it once more :)

**Comment by Nilvus** [comment]
> @Nilvus I do remember, and I'm also seeing your `margin` in the current theme. Not sure why but it seems we've gone back to the previous behaviour. Please confirm whether or not you have the same on your side.
> Thanks for looking into it once more :)

No, something else change the margins on icons themes, probably module height or something like that because I put a margin of 3px instead of 1px and alignment is now back. PR is coming in a minute.

**Comment by homer3018** [comment]
Thanks!
