### ISSUE TITLE
Style applied auto-exposure for mass photo adjustments

### ISSUE THREAD

**Issue by MWP** [darktable-org/darktable#3661]
Hi (again) all,

I use DT for mass editing RAW photos.
I regularly take up to 3000 photos a day of VERY varied conditions, and end up with over 500 keepers that all need tweaking.

I've been trying to find a way to do some kind of simple style-applied auto-exposure in 3.0.0, but haven't been able to work out how to do so.
I'm not looking for something that will automatically correct the exposure perfectly (i know this wont happen), but I think it reasonable for something to get it close 75% of the time so only a quick extra tweak is needed.

All the modules I've tried so far that have an "auto" button, don't do the equivalent of pressing that auto button when the style is applied to a fresh image.

For example, a perfect outcome for me would be to setup & save a style that uses the basic adjustments module, and when that style is applied to a image, the basic adjustments module automatically does the "auto" function.

Is this possible?

Thanks again.

**Comment by junkyardsparkle** [comment]
The exposure module will work this way if you change the mode from "manual" to "automatic", but it might be difficult to find a setting that works well for every type of scene.
