### ISSUE TITLE
Applying style with whitebance in it prints an error label on screen

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3665]
**Describe the bug**
I have repeated steps when I edit some images of the same camera (pana G9).
So I created a style from the history of one image.
When I apply the style to other images I keep getting this error : failed to read camera white balance information from (unknown)!
![image](https://user-images.githubusercontent.com/1119439/70108669-da6d5280-166f-11ea-81c1-0a4dda19f0a1.png)

This is the style file I exported to share, extension renamed as .txt to enable sharing here.
[Generic Starting Point.dtstyle.txt](https://github.com/darktable-org/darktable/files/3919772/Generic.Starting.Point.dtstyle.txt)

OS win 10
Version : darktable-3.0.0rc2+56~ga24e84de4-win64 [build type : release]

**Comment by TurboGit** [comment]
Confirmed !

**Comment by TurboGit** [comment]
Fixed, the issue was just a GUI thing, nothing really broken.
