### ISSUE TITLE
better OpenCL Scheduling Profile strategy

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#3667]
**Is your feature request related to a problem? Please describe.**
Both nVidia card and the Intel 620 IGP support OpenCL. I set the "OpenCL Scheduling Profile" to default and set the device priority manually in darktablerc file (so that the faster nVidia handles main pipelines while the Intel handles thumbnail and preview). However, the nvidia-uvm module doesn't get unloaded on suspend/sleep if an application is using it (in this case, darktable). Thus, I usually lose OpenCL support for the nVidia device upon wakeup/resume (this is on Ubuntu). 

After closing darktable and modprobe nvidia-uvm, darktable would start up and see the nVidia again, then set the Scheduling Profile to "Multiple GPUs", which utilizes the Intel as the primary device (as it's device #0).

**Describe the solution you'd like**
Since there's already device benchmarking on startup, might as well use that to determine the primary vs secondary device and set priorities accordingly in case of "Multiple GPUs".

**Describe alternatives you've considered**
Or, if user manually specified device priorities in darktablerc, don't change the Scheduling Profile away from "default". Or, both.

**Comment by upegelow** [comment]
Valid point. I would opt for your second proposal. I assume that only users will notice and are able to manage who would also be able to manually adjust darktablerc. In that case we could let them write a "magic number" into `opencl_checksum` which disables the automatic check for configuration updates - instead the settings once chosen by the user remain active until they are changed again.

**Comment by hqhoang** [comment]
I also prefer second option, since the device_priorities is in darktablerc only.

However, I still want to improve the auto-priorities for Multiple GPUs a bit. Currently I think it sets to `*/*/*/*`, but if one device is at least 2x faster than the other, than the priorities can be better, e.g. `+1,*/!1,*/+1,*/0,*` (this is my current setting, with 1 being the faster), or just `1,*/!1,*/1,*/0,*`

I set the last one to `0,*` because I noticed in darkroom, when I hit the spacebar to go to the next image, the faster device sometimes is used to generate thumbnail for the current image, thus, not available to render the "full" view of the next image, thus, causing a slight delay.

**Comment by upegelow** [comment]
I just saw that the config variable `opencl_checksum` is anyhow stored as a string. I will introduce the option to set this to OFF meaning no automatic re-checks in case of configuration changes.

**Comment by jenshannoschwalm** [comment]
Does this also respect the case when there is a new graphics driver found requiring updating the compiled cl code?

**Comment by upegelow** [comment]
> Does this also respect the case when there is a new graphics driver found requiring updating the compiled cl code?

No, those two are different.

**Comment by upegelow** [comment]
> However, I still want to improve the auto-priorities for Multiple GPUs a bit.

You should continue adapting your system with the manual settings in darktablerc. They take effect if you use the default profile. Automatic fine tuning of the GPU priority would be way over what darktable can do during the initialization phase. It would require much more extensive benchmarking than the simple gaussian blur test which we currently do for a rough separation of cases.
