### ISSUE TITLE
Panasonic LX100m2 and lens correction module

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#3682]
Darktable does apply "panasonic like" base curve to this camera's rw2 files, but lens correction module doesn't know this camera, only knows the LX100, which moreover shares the same lens.

I think it's quite simple to add the info for the LX100m2 lens.

**Comment by LebedevRI** [comment]
Lens correction is lensfun issue, see
https://www.darktable.org/about/faq/#faq-external-deps

**Comment by paolobenve** [comment]
please correct the lensfun project home, in dartable faq, lensfun is now at https://github.com/lensfun/lensfun
