### ISSUE TITLE
Darktable crashes after start

### ISSUE THREAD

**Issue by mhechthz** [darktable-org/darktable#3684]
Hi,

darktable 2.6.3 was working well for a while. Now it crashes directly after start. I appended some error files.
[darktable_bt_DP6JC0.txt](https://github.com/darktable-org/darktable/files/3935240/darktable_bt_DP6JC0.txt)
[darktable_bt_4FJGC0.txt](https://github.com/darktable-org/darktable/files/3935241/darktable_bt_4FJGC0.txt)

**Comment by TurboGit** [comment]
Which OS? Which version?

Of course we can have this information into the log... But well can people reporting issues help a bit more!!!! Please!

**Comment by mhechthz** [comment]
Windows 10.0.17763 ... as written in the error log ;)

**Comment by mhechthz** [comment]
Hmmm ... a restart of the computer "solved" the problem. Maybe someone will nevertheless find the error logs useful.
