### ISSUE TITLE
Drawn masks not working in darktable 3.0.0 rc2

### ISSUE THREAD

**Issue by Hpbirkeland** [darktable-org/darktable#3685]
**Describe the bug**
When making drawn masks, it is not possible to make adjustments inside the masks. If the mask is inverted, the adjustment affects the whole image. And if you click the "display mask" button, the yellow mask is not shown. The image only becomes grayscale. Affects all modules, including the retouch module, where I first discovered this. Parametric masks on the other hand work as expected.

**To Reproduce**
1. Activate Drawn masks or Drawn and parametric masks in any module, or use the tools in the Retouch module.
2. Select a shape
3. Place the shape in the image
4. Make an adjustment in the module
5. The adjustment is not applied to the image. If the mask is inverted, then the adjustment is applied to the whole image.
6. If the "display mask" button is clicked, the whole image becomes grayscale, and the yellow mask is not shown. If the mask is inverted, the whole image becomes yellow.

**Expected behavior**
The module adjustments should be visible inside the mask and the mask should be displayed in yellow when clicking the "display mask" button.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Linux Mint 19.1
 - darktable 3.0.0rc2~git68.4c7f7c163 from download.suse.com

**Additional context**
CPU: Intel© Core™ i5-4210M CPU @ 2.60GHz × 2
GPUs: Intel integrated and Nvidia GeForce GTX 850M.

This happens both with Intel and Nvidia, and both with and without OpenCL on Nvidia.
Nvidia driver is 430.50-0ubuntu0.18.04.2

**Comment by TurboGit** [comment]
Don't know what you are doing but hopefully I cannot reproduce this!

**Comment by TurboGit** [comment]
So please add more context.

**Comment by Hpbirkeland** [comment]
I'm not sure what more context you would need. Can you be more specific?

**Comment by Hpbirkeland** [comment]
There was a new darktable-update just now, 3.0.0rc2~git72.0c31228da. I also updated Nvidia-driver to 435.21. The problem is still there. It started yesterday, after updating darktable to 3.0.0cr2~git66.something, but only after working through a couple of images.

**Comment by AxelG-DE** [comment]
@Hpbirkeland
I am at 3.0-rc2+72 and everything works as expected.

There is one known topic. If you install a new dt-master, make sure, you delete all the files in the install-dir, not only paint it over. That caused me lot of headaches already.

**Comment by Hpbirkeland** [comment]
@AxelG-DE So you mean not letting update-manager handle the updates, but rather uninstall and make sure every trace is removed before installing again? That's a bit of a pain...

**Comment by TurboGit** [comment]
A context like : 
- can you reproduce on all pictures?
- can you reproduce on new edits ? Or only with some older files you had edited with a previous version?
- on RAW or Jpeg only?
- have you tried with a previous version ? was it working ?

As you see, there is many more context to be given !

Note that the bug is so improbable (many people would have already complained) that before reporting you should try hard to find a reproducible scenario. If you can reproduce easily on all edits and all images kind then there is something broken on your side I fear !

**Comment by AxelG-DE** [comment]
Dear Pascal,


You last sentence is not really logic IMHO. In case dt 'would' have a 
severe bug, it could show up on all edits :-)

But as I cannot reproduce as well, I also think there is something wrong 
on his end or on the packager side....

Am 07.12.19 um 23:30 schrieb Pascal Obry:

**Comment by TurboGit** [comment]
> You last sentence is not really logic IMHO. In case dt 'would' have a severe bug, it could show up on all edits :-)

Sure but I would have reproduced it no? And you too? And probably many others already as there was no change in mask support recently :)

**Comment by AxelG-DE** [comment]
> So you mean not letting update-manager handle the updates, but rather uninstall and make sure every trace is removed before installing again?

By the time I wrote my first reply to you, I oversaw, you are using the package manager... What I described is a known "issue" (not a bug) with the developers version, which I still use, so I clone the github version and build by my self. In that scenario, the install-dir better to be flushed prior new installation. That would be actually one of several things you could do. 
- Install the git-hub-version in parallel (will be in /opt/darktable than) and see, whether you have the same issue. (backup your ~/.config/darktable beforehand)
- you could start your current version with --configdir /tmp and see... (wouldn't be the first broken library)

**Comment by AxelG-DE** [comment]
@TurboGit 
maybe OT here, sorry.... I saw, you updated the bug-report template. May I recommend some more:
- did the user try with new/empty config-dir
- with / without opencl
- which GFX-card and GFX-driver
- for gentoo users, please provide the output from _emerge --info_ (as you can see there all used libs and other stuffs)

**Comment by Dannny1** [comment]
I noticed that drawn masks aren't working (rc2-73) for me.
I then opened file edited with this version in rc1 a it also didn't worked. But in new duplicate it did. 
Then i found out that i need to change ctrl mouse wheel opacity on the file and then it works in both versions.

**Comment by TurboGit** [comment]
@AxelG-DE : thanks!
I have added some. The with/without opencl was already there. I feel the genttoo too much specific and will have to add specificities from other OS otherwise.

**Comment by TurboGit** [comment]
@Dannny1 : your issue is probably an edit done around setp-oct which is broken. That's an iop-order issue.

**Comment by Hpbirkeland** [comment]
Well, after a bit more digging it seems like @Dannny1 is closest. When I add a new mask, the opacity is 0, and I have to ctrl-scroll to change it for every shape. Is that too only me or does everyone see this behaviour? 

And to add some more context: This happen on all edits, old and new, for new masks. Existing masks in old edits are ok. It also happens on all file formats (RAW, tif, jpg).

**Comment by TurboGit** [comment]
But when changing the opacity it should be stored and new masks should start with the latest stored opacity. Right? That's the way it works on my side.

**Comment by Hpbirkeland** [comment]
It should, but for a while after I first got it changed back it did not. But now suddenly it does, and I'm back to normal. Also, I am not aware that I ever changed it to 0%, as I had no reason to do so. But then I consider this solved, and I'm sorry for all the noise I made.

**Comment by AxelG-DE** [comment]
No need to apologise. I also had several occasions, where problems where "self healed" and I never got a clue, what happened

**Comment by AxelG-DE** [comment]
> I feel the genttoo too much specific and will have to add specificities from other OS otherwise.

Totally fine, just thought, for a rolling distro, where is no version, that output could help :)

**Comment by blonchkman** [comment]
I might be wrong but i think only OBS brand is impacted. 
kind regards

**Comment by ccmoralesj** [comment]
Hey guys :smile: 

I had the same issue today. I think the way to replicate this is:
- Go to any module e.g Tone Curve
- Create a brush mask with default opacity (100%)
- Go to another module (or create a new instance of the same module)
- Create a brush mask with an opacity different from the default (100%) e.g Ctrl + scroll twice
- All mask from here will be at 0%

As @Dannny1 said, if I go to the drawn mask and Ctrl + scroll over it, the mask will appear and set an opacity, but I never set the opacity of any mask to 0% so this is kind of annoying.

Let me know if you could replicate the issue. :raised_hands:
