### ISSUE TITLE
Add support for ICC recommended (ISO 12646:2008) colour proofing conditions

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#3686]
**Référence:**  http://www.color.org/resources/r8-13/3.20170809_Consistent_Colour_Appearance_assessment.pdf

![Screenshot_2019-12-07 Standard images - 3 20170809_Consistent_Colour_Appearance_assessment pdf](https://user-images.githubusercontent.com/2779157/70378570-34953e80-1922-11ea-8d0a-b329ef646e1e.png)

**Proposal:**
In lighttable and darkroom, add a white frame around pictures on top of a grey background (L = 50) for the zoomed-out/full preview image (about 10-15% width of the picture):
![Capture d’écran du 2019-12-07 19-13-11](https://user-images.githubusercontent.com/2779157/70378851-a622bc00-1925-11ea-8d05-462075c3cd1e.png)
That could be a preference or even a toggle on/off in darkroom (ISO 12646-compliant mode).

**Benefit:**
The white frame gives a visual reference to assess the global contrast in image. The overall grey backgound gives a reference for the average exposure.

**Note**
As usual, I'm basing this on indirect info I have found on the ISO standard, not directly the standard since you have to pay for it to get the PDF.

**Comment by parafin** [comment]
already fixed
