### ISSUE TITLE
Unlimited number of strokes in spot removal tool

### ISSUE THREAD

**Issue by ionphractal** [darktable-org/darktable#3689]
**Is your feature request related to a problem? Please describe.**
Opening a photo in Darktable, I noticed a lot of dust was on the lense and I wanted to remove it from the photo with the spot removal tool. After adding 64 shapes, the stains were visibly not removed anymore. I tried to export the photo but there as well, no removal.

**Describe the solution you'd like**
I want to be able to add any number of shapes for spot removal.

**Describe alternatives you've considered**
I don't really see any reason why to limit the number of shapes added, but if there was, it should be settable in the app settings.

**Additional context**
It seems like the algorithm only iterating over the first 64 strokes (hardcoded number) and then silently quits the process loop as the condition doesn't match anymore:

https://github.com/darktable-org/darktable/blob/ad1110f98ffccb826d7340ea9f0c94b223cea1b7/src/iop/spots.c#L393

**Comment by ptilopteri** [comment]
employe a second instance of the spot removal module for >64 spots

**Comment by AlicVB** [comment]
Yes, this a known limitation of the spot module. You can bypass it by adding new instances of module.

That said, we shouldn't "silently" allow user to draw more than 64 shapes. I'll have a look

**Comment by AlicVB** [comment]
@ionphractal : PR #3690 should prevent user to add more than 64 shapes (with a message suggesting to add a new instance of the module). That will be for 3.01, as we are in feature freeze (and it's not a critical issue)
Thanks for reporting

**Comment by ionphractal** [comment]
@ptilopteri @AlicVB Thank you for the tip with the multiple instances! That's not quite optimal because I could probably use this as a preset (dust is on the inside of this vintage lens) and I now have to create/apply multiple profiles. But better than being limited... and thanks for the PR, this'll save some time for others that hit this limitation in the future.

**Comment by chhil** [comment]
Maybe create a style and apply it.

**Comment by ionphractal** [comment]
O_O I just created a style out of it and applied it to another photo. The module instances are there but the shapes of each module are empty/0 so nothing is changed... I guess I should open another issue for that or am I doing something wrong?

**Comment by chhil** [comment]
Maybe styles are not supposed to work with masks. I havent tried it myself.
