### ISSUE TITLE
Provide seamless RAW loading for GIMP on macOS

### ISSUE THREAD

**Issue by miguelmorin** [darktable-org/darktable#3691]
**Is your feature request related to a problem? Please describe.**

When using GIMP for loading a RAW file, Darktable is suggested as a loader. After installing Darktable on macOS and opening a RAW file, it seems that nothing happens. But in fact, Darktable is launched as a separate program in the background, and only when closing it does GIMP load the picture. Opening multiple RAW files launches multiple instances of Darktable.

**Describe the solution you'd like**

I would like Darktable to exit after loading the RAW file so it looks like GIMP is able to load RAW files directly.

**Describe alternatives you've considered**

I have been closing the one or many instances of Darktable manually to return focus to GIMP.

**Additional context**

Original Q&A [here](https://graphicdesign.stackexchange.com/questions/131647/how-to-make-darktable-work-in-gimp/131648?noredirect=1#comment196034_131648), along with suggestion of filing issue here.

**Comment by parafin** [comment]
I think GIMP bug tracker is more suitable for this question.

**Comment by miguelmorin** [comment]
Done: https://gitlab.gnome.org/GNOME/gimp/issues/4345

**Comment by samm-git** [comment]
Lets keep this open, as it is also darktable (or to be more specific - gtk/macos) issue. I will try to work on that in the gnome repo

**Comment by parafin** [comment]
Sure, let's keep it open. But if something is required on darktable's side please be specific what and why.

**Comment by samm-git** [comment]
@parafin first thing i would like to do is to debug an issue. But binary provided does not provide ability to attach to it using lldb. Could you please share build scripts/setup for macos, so i will try to rebuild it myself?

**Comment by parafin** [comment]
https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt

**Comment by samm-git** [comment]
@parafin sorry for the late reply, finally got some time working on it. Problem is very clear - GIMP is calling darktable by spawning process. It is never requesting focus in that case. Could you please add [NSApp activateIgnoringOtherApps:YES]; to the mac code? E.g. this is the way i done it for the gimp: https://gitlab.gnome.org/GNOME/gimp/merge_requests/37/diffs

**Comment by parafin** [comment]
I have to think about where to put it, there are at least 2 situations when requesting focus is desired - starting up and importing a file through some means. I wonder how it works on Linux and Windows right now...

**Comment by samm-git** [comment]
@parafin you do not have this problem in windows or linux as normally if app is started from cli in this OS - it will be foreground by desgin. In Mac it is different, this is the case if you start it as a bundle (clicking on the icon) but not the case if you starting it as a CLI (what is non-native way for mac).

**Comment by samm-git** [comment]
@parafin i think starting up is a right place.

**Comment by parafin** [comment]
How exactly does GIMP start darktable on macOS? I've tested various options and indeed when executing darktable directly from terminal with full path to the binary it won't get focus. But if you use "open" command instead it works as expected. E.g. try "open -Wb org.darktable path/to/file". As a bonus it works even if darktable is already running. With direct call it complains about locked database, though if dbus was available it should have worked also. But I've never investigated how to get dbus to work on macOS, probably some environment variable to make it auto-start, as on Linux.
On the other hand "open" requires darktable to be installed as an application bundle, which isn't the case for various macOS package managers. So my question remains - how does GIMP start darktable, does it support darktable installed as an app bundle?

**Comment by parafin** [comment]
Right, loading through dbus is disabled when built with mac integration support enabled, don't remember why exactly...

**Comment by samm-git** [comment]
@parafin dbus is kind of useless on mac. It is possible to install it, but i think most of the users dont have it.

**Comment by parafin** [comment]
Anyway, I've added the call you asked, it seems to work. But gimp should look into supporting darktable app bundle via "open" command.

**Comment by samm-git** [comment]
@parafin thank you! 

About loading with "open" command - not sure if its a good idea at all.

1. No stdout/stderr, so very hard to debug if things go wrong.
2. Different execution path on macos compared to other systems
3. We are using "memory" database, so we should not care about locking issues.

So for now i would prefer to leave it as is.
