### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by afr-e** [darktable-org/darktable#3692]
https://www.darktable.org/usermanual/en/lighttable_chapter.html

![image](https://user-images.githubusercontent.com/42004791/70383518-21dc3300-193d-11ea-9317-df9ccad0c1f6.png)

**PS** Soon this will be `ctrl+w` right?

**Comment by Nilvus** [comment]
Yes, manual is not updated by now. But if you can, any help to updated the manual will be appreciated.
