### ISSUE TITLE
'toggle header' (ctrl+H) doesn't work

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#3701]
Hello
The shortcut 'toggle header' (ctrl+H) doesn't work, even remapped with another combination (compiled  a937398db8e3c9606aef419fb3f92bc275a8a0bc commit/ubuntu studio 18.10/opencl on)

**Comment by ptilopteri** [comment]
works here on openSUSE Tumbleweed git master git74.a937398db

**Comment by Nilvus** [comment]
Work great on my system (same commit and on Ubuntu 19.10). Have you checked if something wrong on your darktablerc file (header lines) ?

**Comment by dim162** [comment]
I have changed the keyboard, checked the darktablerc & the keyboardrc, remap the shortcut, rebuild Dt with fresh Git files... This is the only shortcut which doesn't work! That's not my day!

**Comment by ptilopteri** [comment]
move/rename ~/.config/darktable/keyboardrc and see if it solves your discomfort.

**Comment by dim162** [comment]
Nothing change the problem. I migrated to the Ubuntu studio 19.10, compiled Dt3.0.0rc2+74-ga937398db, it works.
