### ISSUE TITLE
Gamma module?!

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#3702]
Hello!
In history & create new style appear a gamma module... But i found nothing about it (compiled commit a937398db8e3c9606aef419fb3f92bc275a8a0bc/ubuntu studio 18.10)
![Screenshot_2019-12-08_19-17-55](https://user-images.githubusercontent.com/10468352/70394693-a8ede180-19f7-11ea-9ba3-9fa8e3d2c455.png)

**Comment by Nilvus** [comment]
All first modules are the default modules applied to let darktable show the RAW as an image. It's not a module you will find on other parts. These lines (original, gamma, etc.) are just shown to inform the user what is really done. That was already applied on previous release but not shown.
So it's not an issue, please think about closing this issue.
