### ISSUE TITLE
modules pipeline positions & create new style

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#3703]
Hello!
When i create new style, & if i had rearranged modules position in the pipeline, when i apply the new style, to others similar raw, the pipeline modules position, is not what i choosed. (compiled commit a937398/ubuntu studio 18.10)

**Comment by herbert-50** [comment]
Yes - i have noticed this behavior too. The module order of the pipeline is not part of a style. But i think its necessary that it will become  part of the style.

**Comment by junkyardsparkle** [comment]
This situation is discussed in #3149.

I've proposed one approach to getting around this problem in #3266.
