### ISSUE TITLE
Delete styles

### ISSUE THREAD

**Issue by salkalero** [darktable-org/darktable#3705]
Description of the problem.
It is related to the list of styles that appears on the light table, there are several buttons to interact with the list that exists, one of them is to delete, which only allows you to do it one by one and in the case of wanting to delete several styles at once, it is not possible.

That I would like to meet.

I would like to be able to choose several styles at once, be they 2 or 35 styles and be able to eliminate them at once, without having to do it tediously one at a time.

Additional context

It would not be necessary to add more buttons, it would only be necessary to be able to choose several styles in the container box by pressing the "shift" key, and in the case of having several styles selected, the option of applying the style to the photograph would be canceled.

Thanks

**Comment by salkalero** [comment]
Currently in the style box, in the light table, this is what you find, you can only select a single style to remove
![Captura de pantalla de 2019-12-13 10-21-59](https://user-images.githubusercontent.com/48950749/70789119-ba860f00-1d92-11ea-83f1-eff08ccfc8c8.png)

I think that the ideal would be to be able to select more styles at the same time, so that the elimination of the styles that do not interest you, is more comfortable.with the typical keyboard combination, Shift and Crtl
![selección múltiple](https://user-images.githubusercontent.com/48950749/70789945-4cdae280-1d94-11ea-9a27-29d4f8f0e277.png)

It would even be good to apply several styles at once to a single image

**Comment by EdgarLux** [comment]
This would be very useful when a bunch of styles have been imported, and after have been tested, those that are not be very useful will be discarded.

**Comment by salkalero** [comment]
Imagine you have 50 styles and only use 10, the list that is created in the dark room is very large and annoying to find the 10 styles you use most. And if you want to clean the styles, now you would have to do it one by one, it is very cumbersome and slow.

**Comment by obturadorlibre** [comment]
I think it would be very interesting to apply this feature, I also think that it is not necessary to add another button but as in other softwares, keep the control key pressed to select several and with the shift key to select continuous.

**Comment by salkalero** [comment]
Hi. I have been able to activate the multiple selection of the created styles, but the remove, edit and export buttons stop working. If anyone has any suggestions I will be all ears. The modified file is as follows "https://github.com/darktable-org/darktable/blob/master/src/libs/styles.c" I modified line 407. And I replaced the GTK_SELECTION_SINGLE with GTK_SELECTION_MULTIPLE

**Comment by salkalero** [comment]
Ese
