### ISSUE TITLE
masks transparency GUI inconsistency

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#3708]
Hello. There is a problem how masks transparency is adjusted, displayed and remembered between sessions.

1. If a brush stroke is selected in a module such as retouching, its central spot opacity is increased with Ctrl+mouse wheel down. In case of any other mask (circle, ellipse, contour), the same action decreases the opacity. 
The same is if the brush stroke is selected and its opacity is adjusted afterwards. 
2. In case of circle, ellipse, contour mask, opacity of already not created mask (as of a tool itself by GIMP analogy) can be adjusted with Ctrl+mouse wheel. But that fact is not displayed anywhere. So further applied masks can have 0%-100% opacity, but no one can judge it. Tool opacity should be shown in its module at any stage (it's not about blending of the whole module, it's about the currently selected tool opacity).
3. Masks opacity is transferred between darktable sessions without any displaying. 
4. Newly applied mask has the opacity of the last used mask tool. Adjustment of mask opacity after its selection with mouse does not change the initial opacity of further created masks. It may be right, but the opacity of the tool should be displayed.
5. If an opacity of a tool was adjusted with circle, ellipse or contour, it is applied to a newly created brush too. But it cannot be adjusted in that way for the brush, because its adjustment assumes additional mechanism of its opacity.

**Comment by Nilvus** [comment]
Hello, please precise on which darktable release you are and OS (name and version).

**Comment by BigSerpent** [comment]
OK. Linux Mint 19.2 Mate X64, git master at commit a937398db8e3c9606aef419fb3f92bc275a8a0bc

**Comment by junkyardsparkle** [comment]
There have been a few issues posted lately that turned out to be related to opacity settings that the user wasn't aware of having changed. It does seem like this should be made easier to notice in the GUI *somehow*.

**Comment by TurboGit** [comment]
>     2\. In case of circle, ellipse, contour mask, opacity of already not created mask (as of a tool itself by GIMP analogy) can be adjusted with Ctrl+mouse wheel. But that fact is not displayed anywhere. So further applied masks can have 0%-100% opacity, but no one can judge it. Tool opacity should be shown in its module at any stage (it's not about blending of the whole module, it's about the currently selected tool opacity).

The opacity is displayed into the hint message top-center of the window. So one can judge about the current setting.

**Comment by TurboGit** [comment]
>     3\. Masks opacity is transferred between darktable sessions without any displaying.

Again this is wrong, see above.

**Comment by BigSerpent** [comment]
> > 2. In case of circle, ellipse, contour mask, opacity of already not created mask (as of a tool itself by GIMP analogy) can be adjusted with Ctrl+mouse wheel. But that fact is not displayed anywhere. So further applied masks can have 0%-100% opacity, but no one can judge it. Tool opacity should be shown in its module at any stage (it's not about blending of the whole module, it's about the currently selected tool opacity).
> 
> The opacity is displayed into the hint message top-center of the window. So one can judge about the current setting.

I cannot see the hint message. Where is it located? I cannot find it within the top of the window (the top panel is visible now).

**Comment by TurboGit** [comment]
It is located on top-center (as I said in my previous message), at the same height has the logo. That's were all information are written (number of selected image, hint when a form is selected...).

**Comment by BigSerpent** [comment]
Could you please point me into the right direction? Here is a snapshot of my darktable with panels on.

![Снимок экрана в 2019-12-10 22-45-09](https://user-images.githubusercontent.com/47396887/70563201-dde86880-1b9e-11ea-8d85-b8c14212f1d6.png)

**Comment by Nilvus** [comment]
> Could you please point me into the right direction? Here is a snapshot of my darktable with panels on.

Press Ctrl+h to show header and so see top center place where infos are displayed.

**Comment by BigSerpent** [comment]
Oh, now I see. Thank you. I turned that panel off to save precious vertical space. My monitor has 1200 pixels height and even with this panel off it is not enough to observe history and metadata at the left or different right modules at the same time. So I'll better turn the panel off again and concern its existence as a help.
IMHO current implementation is not the best. There is a difference between a hint, which is optional, and displaying of a tool current state, which is mandatory. Also, textual representation at arbitrary position due to previous text is not intuitive and fast to understand.
Nevertheless, articles 1 and 5 are actual.

**Comment by BigSerpent** [comment]
And now I'm observing at my git master build, than if brush central part opacity is changed, it is restored in a new session as tool opacity.

**Comment by arigit** [comment]
This sounds similar to #3772
