### ISSUE TITLE
Asymmetric side panels

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#3710]
**Is your feature request related to a problem? Please describe.**
I'd like to maximise the amount of space available for the image while editing and often end up hiding the left panel while editing and then having to unhide it to work with my history stack/snapshots. 

**Describe the solution you'd like**
It would be great if we could set the left and right panel widths independently. This would allow me to keep my left panel narrow and my right panel wide and give as much space as possible to the image, while reducing unnecessary clicks.

**Describe alternatives you've considered**
I've reduced my font size and reduced the width of the panels as much as I can.

**Comment by ptilopteri** [comment]
I use a similar but different approach.  In darkroom modeI hide both panels, display the image to fill the screen, then size the right panel to fill the remaining space.  I only display the left panel when absolutely necessary and hide it again as soon as possible.

**Comment by elstoc** [comment]
That's about where I am. However, I do use the left panel fairly frequently to judge the effect of my edits. I just don't need it to be that wide. It could easily be half the width of the right panel and still be very useful.

**Comment by Nilvus** [comment]
Waiting to see if that could/will be implemented, you could already use (with 3.0) these shortcuts to hide/show panels you want :

Maj+Ctrl+t : top panel (between image and header)
Maj+Ctrl+b : bottom panel (between image and filmstrip)
Maj+Ctrl+l : left panel
Maj+Ctrl+r : right panel
Maj+Ctrl+n : navigation thumbnail image
Maj+Ctrl+h : histogram

That's help a lot to let more space to image and choosing which part you need to show depending on your actual actions. A tip to add : just keep pressing Maj+Ctrl then the letter shortcuts of each panel you want to hide or show if you have more than one to change.

**Comment by ptilopteri** [comment]
what is:  Maj+Ctrl+n : navigation thumbnail image
on linux, <shift><ctrl><n>
but it does not do anything that I can see and is not in keyboardrc*

**Comment by Nilvus** [comment]
> what is: Maj+Ctrl+n : navigation thumbnail image
> on linux,
> but it does not do anything that I can see and is not in keyboardrc*

The image preview on top left in darkroom mode. Be sure to have a recent release of darktable as it was a time not working. This shortcut is working on 3.0.0rc0 and next ones.

**Comment by ptilopteri** [comment]
I see it, never knew that one and probably will not use it but nice to know.  tks

**Comment by elstoc** [comment]
Thanks for the tip @Nilvus. I've remapped the left/right panel toggles to "," and "." respectively. If I press both at the same time it toggles both so I can flip between left- and right-panel visibility. A good workaround for now but would still like independent width settings.

**Comment by elstoc** [comment]
Even better would be able to click and drag to change the side panel widths without going into settings.

**Comment by AlicVB** [comment]
I've just done PR #3726 to solve that, if someone want to try...
