### ISSUE TITLE
Option to enable/disable tooltips?

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#3711]
Sometimes with long text in tooltips  (with FilmicRGB), their appearance are disturbing & can cause misuse. To remember & learning the how to use modules & all the parameters, they have their importance. Afterwards, speed, accuracy & straight use are the big goal. Is it possible to have an option to enable/disable tooltips?

**Comment by pphotography** [comment]
I'd like to see that, too. Tooltips can be distracting sometimes.

**Comment by Nilvus** [comment]
I agree to that proposal. Tooltips are really useful to understand how darktable and a new module works. After that, when we know how it works, they're not useful anymore. Having a possibility in preferences (and why not with a shortcut accessible anywhere in darktable)

**Comment by TurboGit** [comment]
Maybe this:

```
tooltip {
  visibility: hidden;
}
```

Or using some transparent properties?

**Comment by junkyardsparkle** [comment]
I like having the information from the tooltips enabled, but what I find is that they often appear in places that are too close to the pointer and can interfere with use of the controls (especially when they appear below the pointer). I wonder if it's possible to improve this with styling, maybe padding them in a larger invisible bounding box or something?

**Comment by Nilvus** [comment]
> Maybe this:
> 
> ```
> tooltip {
>   visibility: hidden;
> }
> ```
> 
> Or using some transparent properties?

Already try that. Simply doesn't work. transparent make just them inherit from parent tag, so just change color but remains visible. visibility:hidden seems to not be able with Gtk. Adding that simply make theme not responding !

**Comment by Nilvus** [comment]
> I like having the information from the tooltips enabled, but what I find is that they often appear in places that are too close to the pointer and can interfere with use of the controls (especially when they appear below the pointer). I wonder if it's possible to improve this with styling, maybe padding them in a larger invisible bounding box or something?

I will try that, a padding could be an improvement (just to check if that will apply as we want).

**Comment by Nilvus** [comment]
@TurboGit : do you know which is the parent of tooltip tag with Gtk/CSS ? I can't see that part with Gtk inspector and after many tries, I change the padding inside the tooltip but not the margin outside. It seems there is a parent to use and do that...

As you want for the time you want to spent on that. For me, I will not spent lot of a time and the good thing here would be to have an option to activate/deactivate tooltips.

**Comment by junkyardsparkle** [comment]
> the good thing here would be to have an option to activate/deactivate tooltips.

It would be good to have, but it would also be good if users weren't too much tempted to disable them immediately; some of the new modules, especially, put a lot of important usage information into those which currently isn't easy to find anywhere else.

**Comment by dim162** [comment]
I read the Darktable, Darktable.FR, Pixls.us, Patdavid.net (resources, blog, manuals, articles), i look at some videos (Aurelien,...), follow discussions on forum & github. All those are crucial informations, tooltips are reminder, helpfull for the first steps.  After i need to think about my pictures & what i want to do. If i make a mistake, i learn from it, not from the tooltips. You wrote that when tooltips appears just under the cursor, it's disturbing, you're right. An improvement will be welcome.

**Comment by TurboGit** [comment]
@Nilvus : I would say that the tooltip parent is the widget on which it is registered. I'm really not sure though. I'm no Gtk expert but this is what makes more sense to me.

**Comment by Nilvus** [comment]
> @Nilvus : I would say that the tooltip parent is the widget on which it is registered. I'm really not sure though. I'm no Gtk expert but this is what makes more sense to me.

Thanks but I was also suspected widget tag but that doesn't work. Anyway, I find tooltips good as they are. They could be a little bit improved but I don't think that needs to spent more time to search how.

**Comment by dnlyko** [comment]
This is a real problem in 3.7 Windows insider version

**Comment by Nilvus** [comment]
> This is a real problem in 3.7 Windows insider version

Such comment doesn't provide any useful information to help. This issue had been fixed. It is now possible to enable/disable tooltips. You can see how in the manual. And with actual 3.7, all shortcuts could be more tweakable than before.

**Comment by dnlyko** [comment]
Sorry, I am new to this.  I have only started using (testing) the program and was trying to let folks know that there still exists issues with how the popup tooltips are displaying in the Windows version 3.7.0+1637~g7975368df.
I do not see that the issue has been fixed.
I do not want to disable it.
I did spend some time searching the 3.6 & 3.87 manuals for how to disable but could not find any answer.
I searched on Pixls.us as well as Google and could not find an answer.
![tooltip](https://user-images.githubusercontent.com/38403574/145733709-87f2d68e-0fa2-436e-86b6-2f9b9dbcb48b.jpg)

**Comment by Nilvus** [comment]
This is not darktable issue. It's Gtk one (Gtk is the graphic library used for the UI), so darktable team can't do anything.

I'm not behind my computer but as I remember shortcut should be something like shift+ctrl+c
You could search shortcuts in main settings and related tab. It's easier in actual master.

**Comment by dnlyko** [comment]
shift+t

**Comment by dim162** [comment]
It also needs a compositor turned on, which slows down the display
