### ISSUE TITLE
Synchronise history stack during edit

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#3713]
**Is your feature request related to a problem? Please describe.**
Darktable is mostly pretty stable. However, on the odd occasion that it crashes, it's usually after a fairly heavy editing session with a single image. When I reopen darktable after a crash my entire edit history for that session is lost and I have to start again. It appears that the only time that the history stack is saved to the database/xmp file is when finishing an editing session (going back to lighttable, changing image, quitting darktable etc.).

**Describe the solution you'd like**
I would like the history stack/masks in my current editing session to be periodically saved to the database and/or xmp file so that I can easily recover my work following a crash.

**Describe alternatives you've considered**
The workaround, when you remember to do it, is to periodically manually switch images to force the history stack to save to the database. I'm raising this feature request following a discussion on https://discuss.pixls.us/t/synchronize-darktable-sidecar-file-as-you-work/15158, in which some alternatives have been suggested.

For example:
- have a setting that allows the user to select how often to copy the history stack back to the database during an edit session
- automatically copy session to the database each time a user selects a new module or when the user compresses the history stack

It probably still makes sense to only update the xmp file when leaving an edit session but, in case a user does not re-enter the edit session after a crash, it might be necessary to automatically update xmp files if the last xmp write time is before the last save to the database. This could be a check on startup.

**Comment by Bbawt** [comment]
This would be a great addition. I'm not sure if data needs to go into the database or sidecar file, but I'd love to be able to click a button that updates edits while remaining in the darkroom module. Having the Compress History button also write updated edits would be an efficient way.

**Comment by elstoc** [comment]
I think the primary storage is the database. Sidecar files can be switched off in the preferences. Personally I'd prefer not to have to remember to click a button and I don't compress the history stack very often. Auto (timed or when changing module) would be best but having the ability to force-save without exiting the session might be good too if going with the timed option.

**Comment by Bbawt** [comment]
I've never really understood what data goes in the database and what data goes in the sidecar xmp file. I'm not too fussed one way or another...just want an easy way to know editing steps have been captured in case of a crash. Auto saving after switching editing tools could work too - or any other options the devs might consider.

**Comment by junkyardsparkle** [comment]
To save on frequent writes to the database, this could be implemented by having a temporary "crash file" for whatever image is currently loaded in darkroom, which is deleted when the changes are flushed to the database. This file could be updated every time another entry is added in the history module.

**Comment by pphotography** [comment]
I support this feature request. In the rare occasion darktable crashes I lose the last edits I did. As far as I see, sidecar files are being updated when leaving one image in darkroom.

One solution for doing a manual update could be a function that triggers a manual update of the sidecar file (and database), like a save button. Could be triggered by a hotkey, like 'CTRL-S' in many applications.

**Comment by tpinfold** [comment]
I support having some way to recover edits when a crash occurs. BTW, great job the developers have done on Darktable

**Comment by johnny-bit** [comment]
This should be IMO considered in the socope of work related to #4313 and/or related issues
