### ISSUE TITLE
OpenCL not detected

### ISSUE THREAD

**Issue by HardySoftware** [darktable-org/darktable#3717]
**Describe the bug**
In darktable preference --> core options --> activate OpenCL support, the only open I have is "not available"; OpenCL scheduling profile's option is also "not available".

**To Reproduce**
It is self explained. I just bought a new PC
- AMD Ryzen 5 3600x CPU
- Radeon RX 590 graphic card

**Expected behavior**
I should be able to use GPU for my processing.

**Screenshots**
There are 2 screenshots here http://imgur.com/a/InDkXP5 the one to confirm OpenCL is supported, and what I can see from the darktable preference screen.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.3
 - OpenCL activated or no -- not detected
 - which GFX-card and GFX-driver -- https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-590

If I run darktable-cltest.exe command, I got what you can see from my first response below.

But if **_I log in with another profile on the same computer_**, the OpenCL is detected in darktable, just like this user complained https://discuss.pixls.us/t/opencl-suddenly-is-not-available-anymore-dt-2-7-win64/14307 but there is no more further explanation. This could not be my solution, I have to use this profile.

**Comment by MStraeten** [comment]
On my osx machine it usually needs 30-40 attempts to build the kernels. I delegated it to a shell-script (https://discuss.pixls.us/t/current-osx-build/13213/9) This needs to be done once ...

**Comment by HardySoftware** [comment]
This is a very interesting insight, I never know I need to compile kernels myself. Upon first run I got

> C:\Program Files\darktable\bin>darktable-cltest.exe
> 0.104024 [opencl_init] opencl related configuration options:
> 0.105024 [opencl_init]
> 0.106024 [opencl_init] opencl: 1
> 0.107024 [opencl_init] opencl_library: ''
> 0.108024 [opencl_init] opencl_memory_requirement: 768
> 0.109025 [opencl_init] opencl_memory_headroom: 300
> 0.110025 [opencl_init] opencl_device_priority: '*/!0,*/*/*'
> 0.112026 [opencl_init] opencl_mandatory_timeout: 200
> 0.114026 [opencl_init] opencl_size_roundup: 16
> 0.116027 [opencl_init] opencl_async_pixelpipe: 0
> 0.117027 [opencl_init] opencl_synch_cache: 0
> 0.119027 [opencl_init] opencl_number_event_handles: 25
> 0.121028 [opencl_init] opencl_micro_nap: 1000
> 0.122028 [opencl_init] opencl_use_pinned_memory: 0
> 0.125028 [opencl_init] opencl_use_cpu_devices: 0
> 0.126029 [opencl_init] opencl_avoid_atomics: 0
> 0.127029 [opencl_init]
> 0.129029 [opencl_init] found opencl runtime library 'OpenCL.dll'
> 0.130029 [opencl_init] opencl library 'OpenCL.dll' found on your system and loaded
> 0.207047 [opencl_init] found 1 platform
> 0.208047 [opencl_init] found 1 device
> 0.210048 [opencl_init] device 0 `Ellesmere' supports image sizes of 16384 x 16384
> 0.212048 [opencl_init] device 0 `Ellesmere' allows GPU memory allocations of up to 4048MB
> [opencl_init] device 0: Ellesmere
>      GLOBAL_MEM_SIZE:          8192MB
>      MAX_WORK_GROUP_SIZE:      256
>      MAX_WORK_ITEM_DIMENSIONS: 3
>      MAX_WORK_ITEM_SIZES:      [ 1024 1024 1024 ]
>      DRIVER_VERSION:           2906.10
>      DEVICE_VERSION:           OpenCL 2.0 AMD-APP (2906.10)
> 0.460104 [opencl_init] options for OpenCL compiler: -cl-mad-enable  -DAMD=1 -I"C:\Program Files\darktable\share\darktable\kernels"
> 0.465106 [opencl_init] compiling program `demosaic_ppg.cl' ..
> 0.467106 [opencl_load_program] loaded cached binary program from file `C:\Users\Hardy\AppData\Local\Microsoft\Windows\INetCache\darktable\cached_kernels_for_Ellesmere\demosaic_ppg.cl.bin'
> 0.473107 [opencl_load_program] successfully loaded program from `C:\Program Files\darktable\share\darktable\kernels\demosaic_ppg.cl'
> 0.478108 [opencl_build_program] could not build program: -11
> 0.480108 [opencl_build_program] BUILD STATUS: -2
> 0.482109 BUILD LOG:
> 0.483109 Error: The binary is incorrect or incomplete. Finalization to ISA couldn't be performed.
> 
> 0.486110 [opencl_init] failed to compile program `demosaic_ppg.cl'!
> 0.489111 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
> 0.490111 [opencl_init] initial status of opencl enabled flag is OFF.
> 
> press any key to exit

I assume this is the similar issue you had? Let me run it multiple times.

**Comment by peterbud** [comment]
This is fixed in 3.0.0 RC2, see #3384

Can you try the RC2 version? Be mindful of the database backup/update.

**Comment by HardySoftware** [comment]
Thanks @peterbud it is good to know. For the moment I am using 2.7, which is very buggy. But at least 2.7 recognized OpenCL properly.

How does 3.0rc2 comparing with 2.7? If it is more stable I will install it.

**Comment by XanomalieX** [comment]
RC2 was my solution using R9 3900X + RX580
just delete this folder and start darkatable:
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\INetCache\darktable
then OpenCL was available

**Comment by s7habo** [comment]
I have this issue on 3.0.0rc2~git119.2112d5698 

My OS: Ubuntu 18.04

**Comment by s7habo** [comment]
With darktable 3.0.0rc2~git121.92e27fd9a openCL is recognized again! :)
