### ISSUE TITLE
"Smart" preset for Lens Correction

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#3718]
**Is your feature request related to a problem? Please describe.**
Says, I want to apply only "Distortion & TCA" to an image, whatever the lens and focal length that darktable can detect. However, upon saving this as a preset, when applying to other images of different lenses or different FL, the Lens Correction module applies the saved preset with the exact previous parameters (that is, wrong lens and/or wrong FL).

**Describe the solution you'd like**
Similar to how Profiled Denoise can have presets that use the detected ISO dynamically, it'd be nice if Lens Correction presets can use the detected lens/FL/aperture instead of what have been saved to the preset.

**Comment by hqhoang** [comment]
Thinking more about this, I'd like to categorize this as a bug instead. If I copy lens correction from an image to another image at a different FL (same lens, same camera), the Lens Correction module of the second image will then have the wrong correction applied, until I hit the Reset button on the module. Thus, copying and pasting Lens Correction is currently broken.

Here's an example. Original image with FL = 44mm, no lens correction applied:
![no_LC](https://user-images.githubusercontent.com/1099071/72546186-f0198e80-384f-11ea-9255-6659d96f6eeb.jpg)

then, copied and pasted LC from another image with FL = 18mm, the incorrect LC is applied thus the table edge is even curvier:
![incorect_LC](https://user-images.githubusercontent.com/1099071/72546263-17705b80-3850-11ea-8d7b-17734fe7cf41.jpg)

after resetting the LC module, the correct LC is then applied:
![correct_LC](https://user-images.githubusercontent.com/1099071/72546290-27883b00-3850-11ea-8feb-507f9dc77483.jpg)

**Comment by ptilopteri** [comment]
It will be wrong if you copy the lens correction for another camera, also.  Why would you expect the lens correction for one lens to be the same for another?  You can configure lens correction to always be applied and let it determine the current lens.

**Comment by hqhoang** [comment]
> It will be wrong if you copy the lens correction for another camera, also. Why would you expect the lens correction for one lens to be the same for another? You can configure lens correction to always be applied and let it determine the current lens.

That's why I'm asking for a "smart" preset, just like Profiled Denoise that automatically detects the camera and ISO and applies the correct setting accordingly. I don't want to always apply LC, e.g. there are photos with people near the edges, or the image doesn't have straight lines, ...  images better without LC applied.

Currently copying/pasting is the only easy way to apply LC to multiple images selectively. If the operation is allowed, it should perform correctly.

**Comment by junkyardsparkle** [comment]
I'm not sure I agree about the copy/paste behavior (I generally expect this to be literal settings), but I do agree there should be a way to use presets as you describe originally. Right now, presets aren't really useful except for auto-applying the full defaults (or for prime lenses without vignetting correction). There's some discussion about an overhaul for this module in #1990.
