### ISSUE TITLE
Lighttable Group buttons seems to require pixel perfect clicks

### ISSUE THREAD

**Issue by hellbuster** [darktable-org/darktable#3728]
Today I noticed I had trouble interacting with the lighttable group buttons. For a moment I though that they were not working until I noticed that if I click exactly on the 'G', they work normally. I normally use a modified darktable-elegant theme, but I tested with the regular darktable theme and the problem is also there.

**Platform (please complete the following information):**
 - OS: Arch Linux
 - Version 3.0.0.rc2+83~g5981e2aec

**Comment by AlicVB** [comment]
really strange... and I can't reproduce...
Some question : 
1. does it happen for other buttons next to 'G' too ?
2. is the background color of the button changing when you hover it (not 'exactly' on G) ?

**Comment by hellbuster** [comment]
@AlicVB For 1, I would have to test when I get home. For 2, no, the background wasn't changing on hover.

**Comment by Nilvus** [comment]
I confirm, that's really strange. Never seen that. I also use last commit master and I don't have this behaviour. I could click on any part on a square around and inside the icon, like the 3 others ones. And hover is present as it should. I work on the UI so test that and never seen anything like your issue.

Are you sure that you don't break anything by tweaking CSS (yes I see that you said you have same problem with regular darktable theme but sometime...) ? I suggest you to save all css you have, remove darktable and reinstall properly to see.

**Comment by hellbuster** [comment]
@AlicVB @Nilvus 
Wait, I am refering to the G button that appear as an overlay only in grouped images, not the global group button that is above the lightable (besides the star, help and preferences button). By your comments, it seems that you both refer to the second one.

**Comment by Nilvus** [comment]
@hellbuster : so it's normal that it works this way. It's not a button. It's on start an info that images are grouped. You can click on it yes but it's easier to use the G icon next to star, help, etc. Until your post, I even didn't know that we could click on it. It's a good way to not care about it ;-)

**Comment by hellbuster** [comment]
@Nilvus the functionality is not the same, though. First, it allows to expand a group individually. Second, it allows to change the group representative (I use this a lot). So, I don't think not caring is as easy as you make it sound.

**Comment by EC1000** [comment]
I confirm I encountered the exact same problem (making it really difficult and annoying to change group header). 

Checking again today with 3.0.0rc2~git97.b26d5128f, it seems to work properly (I have to click inside the "G", clicking on its shape does not work, but I think it was always like that).

For reference, the functionnality is described [here](https://github.com/darktable-org/darktable/blob/879f1e5f9cf6ac812b1396be777a4ca992075017/doc/usermanual/lighttable/concepts/grouping.xml#L89).

**Comment by hellbuster** [comment]
This is fixed on master, so I am closing.
