### ISSUE TITLE
Tone equalizer: the cursor disappears with color picker area mode

### ISSUE THREAD

**Issue by EdgarLux** [darktable-org/darktable#3729]
**Bug description**
The cursor disappears from the image area when an area is selected with color picker in the tone equalizer module.

**Steps to reproduce the behavior:**
1. Activate tone equalizer
2. Activate parametric mask or drawn and parametric mask
3. Select an area with color picker in the image
4. The cursor disappears only in the image area

In this screenshot, the cursor is placed near the selected area
![Captura de pantalla -2019-12-11 23-44-18](https://user-images.githubusercontent.com/47407674/70686118-e9a45f80-1c70-11ea-9c08-ed9de3740865.png)

**Expected behavior**
The cursor must be visible all the time.

In this screenshot, the cursor is near the selected area and visible, with exposure module
![Captura de pantalla -2019-12-11 23-18-19](https://user-images.githubusercontent.com/47407674/70686194-1f494880-1c71-11ea-8e11-e843b7b97a60.png)

**Platform :**
- OS: Parrot OS 4.7 (based on Debian 10) with MATE 1.22.2
- Version: 3.0.0rc2~git83.5981e2aec 
- No OpenCL
- Intel Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller
- Kernel driver in use: i915

**Additional context**
· This happens only with this module
·  Same problem with both RAW and Jpeg
·  Reproduced with a fresh edit
·  deb package downloaded from openSUSE repositories

**Comment by aurelienpierre** [comment]
The true question is : what do you need masking for in tone equalizer ? (provided it has its own internal masking and parametric blending). If you are to use masks, maybe consider using the exposure module instead.

**Comment by EdgarLux** [comment]
> The true question is : what do you need masking for in tone equalizer ? (provided it has its own internal masking and parametric blending). If you are to use masks, maybe consider using the exposure module instead.

I usually try different modules to see the final results. And I use masks to reduce the area of the effect. This module has fascinated me, because I achieve the results that the exposition module does not. I have already used it this way before, with very satisfactory results.

**Comment by EdgarLux** [comment]
It happens with regular color picker too.
![color picker](https://user-images.githubusercontent.com/47407674/70759798-2b82e380-1d0d-11ea-81d1-6e1da1df64ad.png)

**Comment by salkalero** [comment]
I am using ubuntu 18.04.3 with Darktable 3.0.0rc2-git83.5981e2aec
And the same thing happens to me as the companion Edgar, it happens with the two selectors. The cursor disappears when it enters the area of ​​the photo, but it does appear while the cursor is in loading mode.
![Captura de pantalla de 2019-12-13 01-41-52](https://user-images.githubusercontent.com/48950749/70760553-43c52380-1d4a-11ea-9463-9dd8f61e7438.png)

**Comment by salkalero** [comment]
The moment the pointer stops thinking, it disappears. The pointer is in the same place even if it does not appear
![Captura de pantalla de 2019-12-13 01-41-52](https://user-images.githubusercontent.com/48950749/70760769-ff865300-1d4a-11ea-8b0f-e2bae00e7552.png)

**Comment by aurelienpierre** [comment]
> I usually try different modules to see the final results. And I use masks to reduce the area of the effect. This module has fascinated me, because I achieve the results that the exposition module does not. I have already used it this way before, with very satisfactory results.

The tone equalizer is only a shortcut to the exposure module. The algo is exactly an exposure compensation, but instead of a flat correction on the whole range, it uses a parametric one that let you define different corrections depending on the pixel "luminance". So, using another parametric blending on top of that is kind of making things complicated for nothing, since the algo is already parametric.

**Comment by EdgarLux** [comment]
>The tone equalizer is only a shortcut to the exposure module. The algo is exactly an exposure compensation, but instead of a flat correction on the whole range, it uses a parametric one that let you define different corrections depending on the pixel "luminance".

Now I have it clearer. That confirmed my assumptions. That is why in many cases it works better for me. And I think it's a wonderful module.

>So, using another parametric blending on top of that is kind of making things complicated for nothing, since the algo is already parametric.

Maybe it's because I use the drawn and parametric mask mode very often. And maybe it's because it's a new module.
But in the little use I have given it, I feel that I achieve the result with fewer clicks and .
Just to illustrate the case (exaggerating the edition so that it can be noticed): in these two images I have the same parameters. The only thing that changes is that in one use drawn and parametric mask mode and in the other not. And I can restrict the effect to an specific area.

![comparison](https://user-images.githubusercontent.com/47407674/70769961-220b7280-1d31-11ea-8a4c-a37fb8ec1185.png)
![modules-toneq](https://user-images.githubusercontent.com/47407674/70770651-d60dfd00-1d33-11ea-9247-4f37084a8b50.png)

**Comment by aurelienpierre** [comment]
Ok I need to add an exception checking for the color picker state before overwriting the cursor.

**Comment by EdgarLux** [comment]
> Ok I need to add an exception checking for the color picker state before overwriting the cursor.

Ok, merci beaucoup Aurelien. Et mes plus sincères félicitations pour ton mariage.

**Comment by aurelienpierre** [comment]
Merci !
