### ISSUE TITLE
White Balance shows wrong "preset"

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#3732]
**Describe the bug**
After WB adjustment, either with "SPOT" or manually, the preset shows "spot" or the preset area is empty. That is the correct behaviour

However, after changing to next picture and comming back to this one, all over sudden, the preset says "camera" again, even though, the chosen WB-values are still there

**To Reproduce**
1. Go to darkroom
2. Change WB setting, e.g. by spot
3. klick on another photo in filmstrip and back to the photo just edited

**Expected behavior**
The entry in WB's preset shall remain

**Screenshots**
Changed WB
![grafik](https://user-images.githubusercontent.com/49004103/70719879-1b5e0a80-1cf3-11ea-872e-2b317b403b90.png)

After changing the photo and comming back to this one
![grafik](https://user-images.githubusercontent.com/49004103/70720007-552f1100-1cf3-11ea-98d4-2a59be2123f8.png)

**Platform (please complete the following information):**
 - OS: [gentoo linux]
 - Version [3.0-rc2+84]
 - OpenCL activated / deactivated, both are same
 - which 2 x nvidia-gtx 1060 with nvidia-drivers-440.36-r1

**Additional context**
Add any other context about the problem here, for example:
 - Can you reproduce with another dt --> still have to try, currently only this version installed
 - Can you reproduce with a RAW or Jpeg or both? --> RAW
 - Are the steps above reproduce with a fresh edit (removing history)? --> Yes
 - Is dt compiled by yourself? If so which compiler is used? Which options?
    ---> yes. gcc 9.2.0; CMAKE_BUILD_TYPE="Release" ; CFLAGS="-march=native -O3 -mtune=native -pipe"
 - Is the issue still present using an empty/new config-dir --> YES

**Comment by pphotography** [comment]
Confirmed in #3654
