### ISSUE TITLE
channel mixer draw mask Windows version

### ISSUE THREAD

**Issue by drphysic2033** [darktable-org/darktable#3733]
Bugs report just saying it crashes without filling most of the items
below and making no effort to help developpers to reproduce will be
closed without notice.

**Describe the bug**
Using Win10, adjusting the size of the blend mask using either the circle or ellipse mask with the mouse scroll wheel only affects the mask itself. The blend mask boundary does not change. 

**To Reproduce**
1. Go to 'channel mixer module'
2. Click on 'draw mask'
3. Chose either 'circle' or 'ellipse'
4. Error: using the mouse scroll wheel to change the radius of the blend mask changes the mask radius, the blend mask size relative to the mask does not change

**Expected behavior**
As verified on the Linux version of darktable, selectthe  mask boundary until the blend mask boundary illuminates, then using the mouse scroll, the blend mask boundary moves in or out relative to the mask boundary.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 1909 (2)
 - OpenCL activated
 - GTX 1050, 3.20.1 driver

**Additional context**
Add any other context about the problem here, for example:
 - Problem does not occur in the Linux version. Did occur in both 2.6.0 and 2.6.3 Win10 versions
 - Tested only with RAW file (NEF)
 - Tested on 3 separate occasions, once in a general editing session, twice in an isolated edit.
 - Used the default Win10 versions
 - Is the issue still present using an empty/new config-dir: Did not test for this

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I don't know what you mean by "blend mask", but it works ok on my Windows 10 laptop. 

Scrolling the mouse wheel over the circle changes the size of the circle and the size of the (yellow) mask as well.

**Comment by johnny-bit** [comment]
Works as expected for me on 3.2.1 and current master (and ths 3.4)
