### ISSUE TITLE
dt3.0 combobox: Gtk-CRITICAL assertion 'GTK_IS_WIDGET (widget)' failed 

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3747]
**Describe the bug**
Using darktable 3.0, comboboxes are triggering a `Gtk-CRITICAL assertion 'GTK_IS_WIDGET (widget)' failed` error
This is a generic problem with many (if not all) comboboxes (lighttable and darkroom)
100% reproducible
```

(darktable:8494): Gtk-CRITICAL **: 08:29:30.756: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed

(darktable:8494): Gtk-CRITICAL **: 08:31:54.920: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed

(darktable:8494): Gtk-CRITICAL **: 08:33:42.323: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed

(darktable:8494): Gtk-CRITICAL **: 08:35:34.121: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed

(darktable:8494): Gtk-CRITICAL **: 08:35:38.573: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed
```

**To Reproduce**
Steps to reproduce the behavior (as a simple example):
1. Select an image and Go to 'darkroom'
2. In 'exposure' module, right-Click on 'mode' combobox so that the list of available values are displayed. 'manual' and 'automatic' in this case
3. Do not select any value. Instead, click outside of the combobox to close it
4. See Gtk-CRITICAL assertion 'GTK_IS_WIDGET (widget)' failed` error in the console

Same issue with 'lighttable' /'history stack'/'mode' combobox (as another simple example)

**Expected behavior**
No Gtk error

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 / Gtk 3.24.12-1ubuntu1
 - darktable 3.0.0rc2+56~ga24e84de4

```
jacques@Hugo-8:~$ dpkg -l libgtk2.0-0 libgtk-3-0
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-déclenchements
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom               Version          Architecture Description
+++-=================-================-============-==================================================
ii  libgtk-3-0:amd64  3.24.12-1ubuntu1 amd64        GTK graphical user interface library
ii  libgtk2.0-0:amd64 2.24.32-4ubuntu1 amd64        GTK graphical user interface library - old version
```

**Additional context**
 - darktable 2.6.3 on the same computer does NOT have the issue
 - reproduced on a second computer, same Ubuntu / Gtk version
 - dt compiled by myself using standard build instruction. No specific option added
```
mkdir build/
cd build/
cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable/ ..
make
sudo make install
```

**Comment by leclercj** [comment]
Same problem on Windows 10 with Gtk 3.24.12-1
```
$ pacman -Q mingw-w64-x86_64-gtk3
mingw-w64-x86_64-gtk3 3.24.12-1
```
```
(darktable.exe:52424): Gtk-CRITICAL **: 09:10:19.732: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed

(darktable.exe:52424): Gtk-CRITICAL **: 09:10:39.825: gtk_widget_set_state_flags: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by TurboGit** [comment]
I can reproduce ! Indeed this happens only if you do not select any values/

**Comment by TurboGit** [comment]
Fixed now. Thanks for reporting.

**Comment by leclercj** [comment]
Thank you for the quick fix
That's better. No assert anymore when clicking ouside of combobox's module to close it
But still the Gtk assert when clicking inside the same module without having selected any value.
Now in 3.0.0rc2+94~g05514499e

**Comment by TurboGit** [comment]
This second instance of the same error is now fixed. Thanks for reporting. Two more bugs killed for 3.0 final!

**Comment by leclercj** [comment]
It works now. Thanks!
