### ISSUE TITLE
Copy/paste history: increase window size

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3748]
**Is your feature request related to a problem? Please describe.**
When I copy/paste history stacks in lighttable I have to increase the window size. 
On my 1920x1080 screen the window has got a height of 300px showing me 8 entries of the history stack.
![historystack](https://user-images.githubusercontent.com/49001045/70844955-2d51c180-1e49-11ea-8634-57461847bdf3.jpg)

In many cases the history is longer than that, to see all entries I have to increase the window height.

**Describe the solution you'd like**
A bigger selection window for history entries would increase the clarity and speed up the selection process of history entries.

Considerations for a new height:

On a screen resolution of 1920x1080 a window height of 700px seems to be reasonable. 
![historystack_1920_1080](https://user-images.githubusercontent.com/49001045/70845286-efef3300-1e4c-11ea-958c-a96b44d434aa.png)

On a screen resolution of 1280x720 500px should be ok:
![historystack_1280_720](https://user-images.githubusercontent.com/49001045/70845351-dc909780-1e4d-11ea-8fc9-3f0e886341c3.png)

At 1020x768 I wasn't able to reduce darktable's window size to fit into the screen, I interpret that darktable does not support that resolution at all.

I think that a final solution should be based on the smallest screen resolution darktable supports. Unfortunately I was not able to find information about that in the manual or on the website.

**Describe alternatives you've considered**
Currently all history entries are shown in one column. Maybe the window could go for a second column instead of one?
![historystack_2columns](https://user-images.githubusercontent.com/49001045/70845477-6a20b700-1e4f-11ea-89f9-e3f7f1488ae6.png)

**Comment by Nilvus** [comment]
Not so easy. 700px would not fit to all screens, 500px is maybe a compromise. Anyway, I'm quite sure (I can't test it) that we will find a bigger screen when even with 500px that would not be good (too small).

Having two columns, why not but if it could be dynamic. If few modules, one column, two if more like on your screen capture. I'm not sure it's actually an important thing to change as, like you said, the windows is resizable.

I don't know if it possible but if yes, the simplest way would be to store the size on darktablerc file so each user just have to resize one time the window, and darktable will restore same size on next launch. @AlicVB : what do you think about that ? Is it possible ?

**Comment by jakubfi** [comment]
Or maybe calculate the window height as a percentage of screen height?

**Comment by junkyardsparkle** [comment]
I think two columns might be more ergonomic even aside from window size considerations. What would also be nice for this diaolog: if the complete label could be made sensitive to clicks rather than just the small checkbox. I actually thought this would be an easy fix, and looked at the code some time ago, but it turns out that the construction of the list is more complicated than I expexted, and the item names aren't just widget labels... which I guess could have implications for some of the other ideas discussed here?
