### ISSUE TITLE
dt3.0: lut 3D: Gtk-WARNING drawing failure for widget 'GtkWindow' & 'GtkDrawingArea'

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3753]
**Describe the bug**
The combobox at first line of lut 3D module is producing two Gtk warnings when the "lut file" selection icon is not used before.
100% reproducible in this context

**To Reproduce**
1. Select an image and Go to 'darkroom'
2. Open the 'lut 3D' module
3. At the first parameter line, do not use the "lut file" icon on the left, but directly Click on the combobox on the right.
4. No choice proposed (no file listed), but See the following 2 Gtk warnings in the console:
```
(darktable:26403): Gtk-WARNING **: 17:03:45.033: drawing failure for widget 'GtkDrawingArea': invalid value (typically too big) for the size of the input (surface, pattern, etc.)

(darktable:26403): Gtk-WARNING **: 17:03:45.033: drawing failure for widget 'GtkWindow': invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```
**Expected behavior**
No Gtk warning

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 / Gtk 3.24.12-1ubuntu1
 - darktable 3.0.0rc2+97~gb26d5128f

**Additional context**
When the "lut file" icon on the left is used before, and a lut file selected, then the list of choices on the combobox is not empty, and no Gtk warning reported

dt compiled by myself from latest git master using standard build instruction. No specific option added

**Side comment**
I do not fully understand the logic to have two different widgets (the "lut file" icon, and then the combobox) on the same line to select the lut file

**Comment by timur-davletshin** [comment]
Can reproduce it on Debian 10.

**Comment by phweyland** [comment]
> I do not fully understand the logic to have two different widgets (the "lut file" icon, and then the combobox) on the same line to select the lut file

When you have selected a file in folder, the lut is applied on this file, and the combox is fulfilled with the list of files of that folder. Then you can change of lut just with the mouse wheel.

> When the "lut file" icon on the left is used before, and a lut file selected, then the list of choices on the combobox is not empty, and no Gtk warning reported

That's correct. The issue occurs with an empty combo box. I add this to my to do list.

**Comment by phweyland** [comment]
Beside this there is another issue: in preferences when the user reset the lut folder it is not properly reset. darktablerc shows a default user folder instead of a not defined one.
