### ISSUE TITLE
dt3.0: type 'h' inside the seach module line: Gtk-CRITICAL assertion

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3755]
**Describe the bug**
Using darktable 3.0, typing 'h' inside the 'seach module' line is triggering a Gtk-CRITICAL assertion.
100% reproducible
```
(darktable:26403): Gtk-CRITICAL **: 18:01:54.608: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
```
**To Reproduce**
1. Select an image and Go to 'darkroom'
2. In 'seach module' line, type 'h' letter, lowercase
4. See Gtk-CRITICAL assertion 'GTK_IS_WIDGET (widget)' failed` error in the console

**Expected behavior**
No Gtk assertion

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 / Gtk 3.24.12-1ubuntu1
 - darktable 3.0.0rc2+56~gb26d5128f
 - no custom shortcut defined

**Additional context**
 - reproduced on a second computer, same Ubuntu / Gtk version
 - dt compiled by myself using standard build instruction. No specific option added

**Comment by TurboGit** [comment]
Fixed, was a bad interaction with the help window. Another bug killed just in time :)

**Comment by leclercj** [comment]
Yes fixed. thanks
Then I have another one I was hopping to disappear also when this one fixed, but this is not the case. I'm to open another issue for that.
