### ISSUE TITLE
shortcut show module does not always show module

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#3762]
**Is your feature request related to a problem? Please describe.**
I have created shortcuts for all iop modules. This is a nice an fast way to find the module.
But the problem is, that the shortcuts do not always show the module. Instead of this they toggle the module, if is is in an other group.

Here is an example to explain what i mean:

The following shortcuts are created:
w - whitebalance
b - base curve
c - color zones

First all modules are not shown. Then I press:

w - switches to the basic group and shows white balance - OK
b - stays in the basic group, shows base curve and hides white balance - OK
c - switches to the color group and shows color zones - OK
w - switches to the basic group and shows white balance - OK
c - switches to the color group and **hides** color zones - NOT OK
w - switches to the basic group and **hides** white balance - NOT OK

**Describe the solution you'd like**
I think the problem is that the "show module" shortcut does toggle the module instead of showing it.

To fix it, i have changed the function imageop.c/show_module_callback() in my private version:

```
#ifdef MYVERSION
  /* if module is already expanded dont toggle expand */
  if (!module->expanded)
    dt_iop_gui_set_expanded(module, TRUE, dt_conf_get_bool("darkroom/ui/single_module"));
  /* activate module */
  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(module->off), TRUE);
  dt_iop_request_focus(module);
#else /* ORGVERSION */
  dt_iop_gui_set_expanded(module, TRUE, dt_conf_get_bool("darkroom/ui/single_module"));
  dt_iop_request_focus(module);
#endif
```
The first change is: if the module is already expanded, the expand-state will be not toggled.

The second change is: activate the module. This is not necessary, but it is a nice feature. When I show a module I want to activate it too in 95% of all cases. Perhaps it can be done in dependence of a global setting.

**Comment by Nilvus** [comment]
If you have a fix, why not propose a PR ?

**Comment by herbert-50** [comment]
Sorry, I do not know, how to do this. Is it necessary to create a new branch for this few lines?

And ... 
Its a fix and not a solution. I don't know the whole code and concepts of darktable. Perhaps lies the solution in the function dt_iop_gui_set_expanded(), which closes only the modules in the same group and not all.
