### ISSUE TITLE
lu3d → add Adobe RGB color space

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#3766]
It seems that at least some of freely available 3d luts are made with Adobe RGB color space in mind which is missing in darktable.

E.g. https://drive.google.com/open?id=115-vUPKrUxr1Q2qG_WN8Xj2Vj-1qGcfP (freely available from https://www.on1.com/free/luts/ ) — check color space comment inside .cube files.

**Comment by phweyland** [comment]
Taking the opportunity to add Adobe RGB, is there other one which could be useful ?

**Comment by timur-davletshin** [comment]
@phweyland those I could find "in the wild" were sRGB, Adobe RGB or Rec709. There is a huge ImpulZ set but they are camera specific (though one set is Rec709 compatible). Some of luts available freely do not specify color space at all. I assume they are sRGB (e.g. https://github.com/cedeber/hald-clut ).

**Comment by phweyland** [comment]
> ImpulZ set but they are camera specific

Camera specific lut is another story because lut3d should be placed before colorin. Not sure this would be compatible with the current pipe out of the box.


> Some of luts available freely do not specify color space at all. I assume they are sRGB

Yes, that's the first guess.

**Comment by TurboGit** [comment]
Fixed.
