### ISSUE TITLE
Rating → Double rating one star message

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3767]
1. Make sure that "rating an image one star twice will not zero out the rating" is disabled in setting.
2. Select some images and press 1 and darktable writes "applying rating 1" as expected.
3. Press 1 again and darktable says "applying rating 1" while in fact it applies 0 rating (or removes it).

**Comment by codingdave** [comment]
@timur-davletshin double negations are easy to misunderstand. Please apply the checkbox if you dont want the second 1-star rating to zero out the rating. 
Can you confirm that this fixes your issue?
