### ISSUE TITLE
starring duplicate images (raw) acts on all of the dup group and not on the individual images

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#3770]
openSUSE Tumbleweed 20191213
darix's build darktable-3.0.0rc2~git102.c09d36df9-2039.1.x86_64
raw image duplicated three times a,b,c
give "a" 3 stars and nothing happens to "b" and "c"
give "c" 3 stars and "b" gets 3 stars and "c" nothing
give "c" 5 stars and "a" changes to 5 stars, "b" does not change

ratings should apply to individual images and the selected image rather than affecting unselected images

color labels work as expected

**Comment by timur-davletshin** [comment]
Can't reproduce. Works for me. Same build on Debian 10.

**Comment by ptilopteri** [comment]
must be local issue
