### ISSUE TITLE
dt3.0: Gtk-CRITICAL assert using 'seach module'

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#3773]
**Describe the bug**
In darktable 3.0, when darkroom 'seach module' line is not empty, clicking to 'lighttable' is triggering a Gtk-CRITICAL assertion.
```
(darktable:22220): Gtk-CRITICAL **: 19:37:28.214: _gtk_accel_group_attach: assertion 'g_slist_find (accel_group->priv->acceleratables, object) == NULL' failed
```
**To Reproduce**
1. Select an image and Go to 'darkroom'
2. Type something in the 'seach module' line
3. Click on 'lighttable' on top to Go back to 'lighttable' (do not use the 'L' shortcut) 
4. See Gtk-CRITICAL assertion in the console

**Expected behavior**
No Gtk assert

**Platform (please complete the following information):**
 - OS: Ubuntu 19.10 / Gtk 3.24.12-1ubuntu1
 - darktable 3.0.0rc2+110~gd89099a05

**Additional context**
 - dt compiled by myself using standard build instruction. No specific option added

**Comment by TurboGit** [comment]
It is not when it is not empty, it is when the entry has the focus. Can you confirm?

**Comment by leclercj** [comment]
Yes, you're right

**Comment by TurboGit** [comment]
Should be fixed. There was the same issue with the text entry of the watermark iop.
