### ISSUE TITLE
Culling Mode - support of scroll-wheel-click for pointer-centered Zoom: 100% > 200% > fit 

### ISSUE THREAD

**Issue by arigit** [darktable-org/darktable#3774]
Culling Mode currently does not support "scroll-wheel click" for zooming - in Darkroom Mode, scroll-wheel-click will zoom centered in the current position of the pointer, and cycling 100% > 200% > 'fit in window'

The new culling mode is just awesome and intuitively I find myself scroll-wheel-clicking to compare focus between shots - and that doesn't currently work :/ - I need to ctrl-scroll-wheel to obtain that result.
There doesn't seem to be any conflict by adding scroll-wheel-click support to culling mode so: please add it :), it will add some consistency between modes and for many it will also be intuitive

**Comment by AlicVB** [comment]
I don't use scroll-wheel-click, as it always end up with click+scroll ;)
But that seems like a valid request.
I'll see what I can do (the tricky part is the "center to pointer")

**Comment by arigit** [comment]
Just to note: in darkroom mode, also the normal scroll-wheel zoom is somehow centered on wherever the mouse pointer is within the image. So I guess the same concept could be applied to both scroll-wheel-click and regular zooming in Culling mode. The code that handles darkroom mouse events could give pointers on the algorithm (or maybe the code can be made reusable for both modes?)

**Comment by arigit** [comment]
Just to avoid closure - and to confirm there is interest :). NB 30-day auto-closure sounds a bit too short.

**Comment by arigit** [comment]
@AlicVB I believe there is some major lightable redesign going on, not sure if Culling mode is also in scope of the re-work. If yes, wondering if this feature stands a chance of being scoped-in

**Comment by AlicVB** [comment]
@arigit Yes, major rewrite, but it's a huge tasks, so don't expect it to be finished soon... And this will have impact for culling and preview. I'll try to remember this one at this moment...
