### ISSUE TITLE
Sticky preview: fix navigation in a selection of group images

### ISSUE THREAD

**Issue by blonchkman** [darktable-org/darktable#3775]
Dear developer, 
I encounter the following minor bug.
Kind regards

**Description**
The persistent preview ignores the selection when it only contains images from the same group.

**Reproducible:** always

**To Reproduce**

1. In Lighttable,  select a few images belonging to the same group
2. open the persistent preview
3. Navigate through the images

**Expected behavior**
Only the selected images should be displayed.

**Workaround:** Add an image taken outside the group to lock the selection. 

**Platform:**
 - Ubuntu 18.04 and Debian 
 - darktable 3,0rc2 (compiled src and OBS bin)
 - darktable 2.6.x

**Comment by AlicVB** [comment]
@blonchkman : can you test PR #3776 ? That should fix this small bug.
thanks for reporting

**Comment by blonchkman** [comment]
It works for me on ubuntu 18.04!
Well done AlicVB. Many thanks for your action.

**Comment by blonchkman** [comment]
It works for me on ubuntu 18.04
Well done @AlicVB . Many thanks for your action.
