### ISSUE TITLE
UI: color picker sample areas positions displayed incorrectly

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#3780]
In color picker, live samples areas are displayed to an offset. The more samples, the bigger the offset.

Steps to reproduce:
1) In color picker select "display sample areas on image"
2) click on the eyedropper in area mode
3) select an area, click add to live samples
4) select another area, click add
5) repeat

You will see the blue box shifted with respect to the areas selected, the shift increases with the number of areas.

For example see below. Each selection was done precisely on one patch of the greyscale

![Capture2](https://user-images.githubusercontent.com/43290988/70912586-891c7600-2014-11ea-9cd3-2d97c4276f0a.JPG)

DT 3.0 RC2 on Windows 10, default theme

**Comment by junkyardsparkle** [comment]
I've noticed this too, on Linux, so it's not a Windows issue, for whatever that's worth.

**Comment by Mark-64** [comment]
I could look in the code myself, which is the part of the code where those rectangles are drawn ?
