### ISSUE TITLE
Culling view reverts rotation

### ISSUE THREAD

**Issue by ppaspp** [darktable-org/darktable#3788]
**Describe the bug**
When switching from Lighttable file manager view to culling, the orientation of some images, which have been rotated manually, is not respected. Instead, it seems that the opposite rotation is applied (CW instead of CCW and vice versa). Switching back to file manager view shows the images as expected again.

**To Reproduce**
This bug only occurs with some images and I cannot clearly reproduce the bug. However, after resetting the rotation and than applying the same rotation again, then culling view shows the images as expected. It seems to me that only image rotations, which where applied with the previous version of Darktable (2.6) are affected by this bug.

**Expected behavior**
Respect rotation in culling view

**Platform (please complete the following information):**
 - OS: arch linux
 - Version 3.0.0-rc2-115
 - OpenCL no

**Additional context**
 - only tested with jpeg
 - resetting rotation and applying again with DT 3.0 git solves the problem.

**Comment by TurboGit** [comment]
>     * resetting rotation and applying again with DT 3.0 git solves the problem.

Yes, rotation has been fixed in dt 3.0 as there was some bugs in this area. So some manually rotated images are indeed wrongly rendered now. I don't think this has anything to do with culling view btw. Anyway, the only solution is to fix the rotation manually.
