### ISSUE TITLE
darktable 3.0.0rc2 segfauls by duplicate or new instance of tone equalizer

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#3790]
darktable 3.0.0rc2 segfaults by duplicate or new instance of tone equalizer

1. add new instance or duplicate tone equalizer in darkroom

 - OS: Ubuntu
 - Version [18.04]
 - OpenCL  no
 - GFX-card: GeForce GTX 1070 
 - NVIDIA Driver Version: 390.116

backtrace:
[darktable_bt_3B0ZC0.txt](https://github.com/darktable-org/darktable/files/3974146/darktable_bt_3B0ZC0.txt)

**Comment by timur-davletshin** [comment]
Confirmed on Debian 10.

**Comment by upegelow** [comment]
Not sure but might be related to PR3754.

Could you go back to commit 12a3e26fc73d78c6b88e93de18da761fbb172874 and 
see if problem persists?

**Comment by pphotography** [comment]
Confirmed with 3.0.0rc2~git116.f26d09563 on Ubuntu 18.04

**Comment by jenshannoschwalm** [comment]
@aurelienpierre shouldn't it have IOP_FLAGS_ONE_INSTANCE?

**Comment by aurelienpierre** [comment]
Confirmed.

> @aurelienpierre shouldn't it have IOP_FLAGS_ONE_INSTANCE?

No.

**Comment by aurelienpierre** [comment]
Found it.  Merry Christmas !

**Comment by s7habo** [comment]
> Found it. Merry Christmas !

That was quick! Thx @aurelienpierre

**Comment by aurelienpierre** [comment]
It's easy when I can reproduce (but that's not often).
