### ISSUE TITLE
Ability to export from darkroom

### ISSUE THREAD

**Issue by Praveen-Rai** [darktable-org/darktable#3795]
Currently one needs to go back to the LightTable, select the image ( could be hard to locate, especially if filters are changed ) and then use the Export panel to export the image. 

Availability of Export option on Right-click context menu would be great.

**Comment by Nilvus** [comment]
You could already press Ctrl+e shortcut to export an image from darkroom (the shortcut will use export module setting).

**Comment by pphotography** [comment]
The shortcut exports the image with the current export settings. I often find myself switching to lighttable to select another export preset.

For example I got two export presets, one for desktops with 3840x2160 (4K) in PNG and one for Instagram with 1080x1080 in JPG.

I often make a second version for Instagram using the duplicate manager and applying another crop to the copy. The first version is for desktop and the second for Instagram. 
For the second export I have to switch to lighttable and choose another preset.

Would be easier if there would be a preset-selection within darkroom.

**Comment by Praveen-Rai** [comment]
I guess the quick & effective work-around would be to enable / display "Export" module ( panel ) in the DarkRoom as well, may be on the left side, below the "History" panel.

**Comment by pphotography** [comment]
3.0 already is in feature freeze, but I think this should be discussed for the next release. There's issue #3740 where a redesign of the top menu is discussed. Maybe there could be an export button that opens a pop-up window with the export settings.

The left and right side already are overloaded with information and functions, you already have to scroll up and down many times during your editing to get to the modules u need.
