### ISSUE TITLE
Ambiguous string "compression" in translations

### ISSUE THREAD

**Issue by BathoryPeter** [darktable-org/darktable#3800]
As I can see, the same string is used in imageio modules (pdf, png, tiff) and in graduatednd module. Compression of an image is a different term then compression of a gradient, and therefore its hard to translate correctly.

**Comment by junkyardsparkle** [comment]
Maybe "hardness" would be better?

**Comment by BathoryPeter** [comment]
Adding a context parameter for the one of them would be enough I think.

**Comment by TurboGit** [comment]
@jenshannoschwalm : thinking more about this and looking at the code it seems indeed that hardness would be better anyway.
