### ISSUE TITLE
[BUG] Importing files or folder(s) fails (3.0rc2)

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3802]
Hello,

**Setup**
I'm using Darktable 3.0.0rc2~git115.eff9c65e1 on Kubuntu 18.04 (intel i7700k + 32GB RAM + NVidia GFX 1070).
I use the binary manually installed from the .deb file (available in pixl.us) and use some arguments to use dedicated folders or files / settings : _darktable --library /path/_darktable_/library.db --tmpdir /path/_darktable_/tmp/ --cachedir /path/_darktable_/cache/ --configdir /path/_darktable_/_

**Issue**
* Folders
Importing **folder**(s) with several images does not work :
1. Click on Import Folder
2. Select either one or several portfolios (Apply metadata On or Off has no impact)
3.Click on Open (to actually start the import)
4. The import windows closes, and the (too) small progress bar show up but remain stuck and never evolves
![image](https://user-images.githubusercontent.com/3989573/71063063-440b5780-216c-11ea-969b-4031c9ef76e1.png)

You can wait for a long time, the import will not work. 
Every time I need to kill & restart DT, and start the import again, one single file is added to the folder.

If I try to import several folders at once, I have the same issue.

* Files
When trying to import several **files** (not a folder), the same happens : the progress bar is stuck,  and I need to to kill the app (closing it normally does not work).
In the end, only one file is imported.

FYI : it failed with previous builds as well (similarly available on pixl.us)

Does anyone have the same issue ?

Thanks
GLLM

**Comment by junkyardsparkle** [comment]
> Does anyone have the same issue ?

Probably not, since importing directories is a very fundamental operation. :-)

Are you sure you have write permission for the directories you're specifying on the command line?

**Comment by GLLM** [comment]
It's been working for quite some time, even with 3.0rc0 ... btu now, it's not working anymore !
I did not change anything to my setup (folders rights, command line, ...) only installed more recent .deb

**Comment by groutr** [comment]
I would double check the permissions on those folders.  Perhaps try running darktable with some debug output like `-d all` could be helpful.

**Comment by GLLM** [comment]
Folders rights are fine, as they've always been.
![image](https://user-images.githubusercontent.com/3989573/71287307-59e56c00-2368-11ea-8ce2-cbe4b8813be5.png)

And the files right are fine too !
![image](https://user-images.githubusercontent.com/3989573/71287468-bcd70300-2368-11ea-99c7-c528b9d96b65.png)

Moreover, what does not fit this folder/files rights is the fact that each time I start an import, only *one* file gets imported. Not zero, simply one.

I'll try run darktable with -d all, and look at the console.

**Comment by GLLM** [comment]
Got it !
Thanks for the **-d all** advice
![image](https://user-images.githubusercontent.com/3989573/71288997-3d4b3300-236c-11ea-84ff-b1743930fca3.png)
It's the following LUA :
![image](https://user-images.githubusercontent.com/3989573/71289075-784d6680-236c-11ea-8c0d-fca37fdb5ac9.png)

I deactivated it, everything is back to normal ! \o/

Thanks @groutr :)
Closing the issue
