### ISSUE TITLE
Add a confirmation dialog when exporting with overwrite mode from darkroom

### ISSUE THREAD

**Issue by EC1000** [darktable-org/darktable#3805]
**Is your feature request related to a problem? Please describe.**
On dt 3.0, the 'overwrite' option on export from lighttable now triggers a confirmation dialog (instead of being automatically reset to 'create unique filename' as in dt 2.6). 
However, when exporting from darkroom with Ctrl+e, there is no confirmation dialog. It seems 
potentially dangerous regarding data loss. 

**To Reproduce**
1. In lighttable, set the export to 'overwrite'
2. If you export, you will have a warning / confirmation dialog 
3. Enter darkroom. 
4. Export (with Ctrl+e): there is no confirmation dialog. 

**Describe the solution you'd like**
Same confirmation dialog in darkroom as in lighttable.

**Comment by junkyardsparkle** [comment]
Since only one image is being exported in darkroom mode, it might be nice to only show a confirmation in the case of an actual collision, keeping the workflow efficient otherwise... just a thought.
