### ISSUE TITLE
Retouch followed by crop shows part of non retouched in view,

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3812]
Before retouch
![image](https://user-images.githubusercontent.com/1119439/71148721-65467380-2252-11ea-9a51-a1ac4d30290e.png)

Retouched
![image](https://user-images.githubusercontent.com/1119439/71148579-084abd80-2252-11ea-82b8-ce0c6f3c8c90.png)

Crop following retouch
![image](https://user-images.githubusercontent.com/1119439/71148626-21536e80-2252-11ea-9220-ee43a7a8fd6e.png)

What retouch areas look like. Maybe the framing is causing it to not draw part of the retouched area.
![image](https://user-images.githubusercontent.com/1119439/71148858-da19ad80-2252-11ea-9021-a7c742b39145.png)

Pipeline
![image](https://user-images.githubusercontent.com/1119439/71148783-99ba2f80-2252-11ea-922e-0b33bad215cb.png)

**Comment by chhil** [comment]
Its not the framing, the recalculation of area is failing.
![image](https://user-images.githubusercontent.com/1119439/71148985-38469080-2253-11ea-9a71-7a5de0a2302d.png)

**Comment by TurboGit** [comment]
Already reported, a feature not a bug.
