### ISSUE TITLE
Weird interaction between 'preserve colours' and lens correction

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#3813]
**Describe the bug**
Enabling filmic RGB or RGB curve or base curve with 'preserve colours' set to maxRGB or power norm along with lens correction can produce jagged lines that disappear after changing lens correction parameters, even though they are seemingly the same as the initial ones; resetting lens correction brings back the jaggies without (seemingly) changing any values on the UI.

**To Reproduce**
1. Download the NEF and XMP from https://tech.kovacs-telekes.org/files/darktable-issue-3813/
2. Import - see https://tech.kovacs-telekes.org/files/darktable-issue-3813/1-filmic_disabled.png
3. Enable filmic (switching to preserve colours = maxRGB will make the effect stronger) -- see https://tech.kovacs-telekes.org/files/darktable-issue-3813/2-filmic_enabled.png and https://tech.kovacs-telekes.org/files/darktable-issue-3813/6-filmic-maxRGB.png
4. Adjust lens correction by scrolling with the mouse wheel (I set TCA red to 1.00010 -- see https://tech.kovacs-telekes.org/files/darktable-issue-3813/3-lens-correction-change.png)
5. Undo change by scrolling/typing (see https://tech.kovacs-telekes.org/files/darktable-issue-3813/4-lens-correction-change-back.png)
6. Reset lens correction (https://tech.kovacs-telekes.org/files/darktable-issue-3813/5-lens-correction-reset.png)

The same can be demonstrated using (at least) base curve and RGB curve (https://tech.kovacs-telekes.org/files/darktable-issue-3813/8-base-curve-maxRGB.png and https://tech.kovacs-telekes.org/files/darktable-issue-3813/9-rgb-curve-maxRGB.png). Using luminanceY reduces/hides the issue (https://tech.kovacs-telekes.org/files/darktable-issue-3813/7-filmic-luminanceY.png).

Of course it's entirely possible that the RGB modules just make the problem easier to see, and there's something uninitialised in lens correction.

**Expected behavior**
No jaggies (lens correction should produce the same results after initially enabling it or after resetting it as what I got in https://tech.kovacs-telekes.org/files/darktable-issue-3813/4-lens-correction-change-back.png).

**Platform (please complete the following information):**
 - OS: Ubuntu 19.04
 - Version master, 865c2be24e
 - OpenCL activated: does not matter, effect visible both with and without OpenCL
 - which GFX-card and GFX-driver: NVidia 1060/6GB, driver 418.56

**Additional context**
Add any other context about the problem here, for example:
 - Are the steps above reproduce with a fresh edit (removing history): yes
 - Attach an XMP if this is necessary: done
 - Is dt compiled by yourself? If so which compiler is used? Which options? Yes, self-compiled with `cmake --build "/home/kofa/darktable/build" --target install -- -j2`. 
`-- The CXX compiler identification is GNU 8.3.0`
`-- The C compiler identification is GNU 8.3.0`

**Comment by junkyardsparkle** [comment]
> after changing lens correction parameters, even though they are seemingly the same as the initial ones;

One of the odd quirks of the lens correction module is this: if you manually adjust one of the red or blue TCA values, the other value becomes "manual" as well, and is initialized to no correction, and changing the manually adjusted value back does NOT restore the original corrections. If the original correction was a strong one, the visual effect of this can be quite surprising, maybe this is what you're seeing?

**Comment by junkyardsparkle** [comment]
After downloading the file, it looks like the weird moire-like artifact is from the extreme contrast between the clipped sky and the roof edge interracting badly with TCA correction, and is being "enhanced" by using AMaZE demosaicing without smoothing... doesn't seem particularly related to "preserver colors" (increasing saturation by other methods does the same). Probably all you can do with a situation like that is enable the defringe module. :-)

**Comment by kofa73** [comment]
> One of the odd quirks of the lens correction module is this: if you manually adjust one of the red or blue TCA values, the other value becomes "manual" as well, and is initialized to no correction, and changing the manually adjusted value back does NOT restore the original corrections. If the original correction was a strong one, the visual effect of this can be quite surprising, maybe this is related to what you're seeing?

Well, if that's the case, that's certainly not intuitive (and not documented, at least not for 2.6 - https://darktable.gitlab.io/doc/en/correction_group.html#lens_correction). I've never seen such behaviour with with 2.6, and I cannot reproduce it with this image, either (I've just tried). I do get the 'changing from 1.00000 to 1.00010 and back does not restore the initial effect' part, but I don't get those artefacts. The 2.6.2 XMP (https://tech.kovacs-telekes.org/files/darktable-issue-3813/2019-06-15_12-09-39_DSC_0152_02.NEF.xmp) does not trigger the issue with v3, either, so it's probably as you say, the 'preserve colours' that's bringing it out. I don't really think the solution is to use defringe, as simply adjusting the values in lens correction fixes it, too.

**Comment by junkyardsparkle** [comment]
Well, assuming the TCA corrections in the lenses profile are correct (I don't know), then changing them isn't really the right way to deal with weird fringes which aren't really *transverse*, but rather due to things like the extreme backlighting of edges, etc. If you do this, you should be careful to check the other corners of the image to make sure you aren't "uncorrecting" the actual TCA there. :-)

The artifact you mention is just one (most apparent?) of the problematic areas. The root cause is the strongly backlight scene and blown-out sky against dark edges, and the 1.8 EV exposure boost pushes things even further... then some of the various chroma preservations each do their own weird things with those problematic edges - you can see it on the roofline and the plant vines, even without the lens correction enabled... it just doesn't have the "jagged" look until you add the lens correction. So... different combinations give different flavors of artifact. I thought the defringe module actually did a pretty good job of improving it in all cases, myself.

**Comment by junkyardsparkle** [comment]
Oh, and about the TCA slider behavior: it's always been that way AFAIK, and yes, it's not very intuitive, sometimes even quite annoying. IMHO that module is due for a rewrite, if anyone is brave enough to try... there's some discussion about improving it in #1990.

**Comment by aurelienpierre** [comment]
Keep in mind that filmic chroma preservation… preserves also chromatic aberrations, demoisaicing artifacts and such. So filmic might make a lot of bad things pop out, but it doesn't mean it creates them.

**Comment by kofa73** [comment]
Thanks for the clarifications. As stated in the original report: 'Of course it's entirely possible that the RGB modules just make the problem easier to see' -- only there I suspected that 'there's something uninitialised in lens correction', which turned out not to be the case (it's just that lens correction has a non-intuitive interface, going from automatic params to manual ones). Closing the issue.
