### ISSUE TITLE
Export: On Conflict, Prompt

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#3816]
**Is your feature request related to a problem? Please describe.**
The options available in the 'On Conflict' option in the Export module aren't really working for me. Most of the time, I'm creating new files, so I'm not bothered what the option is set to. Sometimes I'm re-editing an existing file and want to overwrite what's there, and sometimes I have two different edits and I want to keep both of them. However, when I'm bulk exporting, I might want to do either, depending on the image. I occasionally forget what I've set the option to and overwrite when I didn't mean to, or create a new image when I didn't mean to, and then I have to go back and sort it out later.

**Describe the solution you'd like**
I would like a new option in the 'On conflict' drop-down, of 'Prompt'. When selecting this option, the image would be overwritten if no file exists and a prompt displayed if not. It would also be nice, if I do create two separate edits in duplicate files to be able to give one of them an automatic suffix (perhaps with A/B/C etc) on export so that they're not treated as duplicates by the export module. Perhaps via an extra field in the metadata editor?

**Describe alternatives you've considered**
The second option (file suffix), I could probably do by tagging the duplicated file somehow, but it might be nice to have something built in.

**Comment by pphotography** [comment]
There are similar requests regarding file export in #3805, #3795, #3816

**Comment by elstoc** [comment]
#3805 and #3795 are about exporting from darkroom (#3816 is **this** issue). I note that there is a change to the 'Overwrite' option in lighttable (in 3.0) such that it prompts every time you select export. However, this prompt appears regardless of whether or not any conflicts are found, meaning it now takes two clicks every time I want to export. If a prompt appears every time you do something it's too easy to get into the habit of just 'clicking through' the dialog box without engaging brain.

Ultimate option would be, on conflict, to show small thumbnails of both the existing image and the new one, with the option to choose a new filename (for on or both?) or overwrite.

**Comment by elstoc** [comment]
I still want this. A single generic "you might overwrite stuff" message doesn't really add anything. The only question I can't resolve is how such a "prompt" action should work when there's no gui. Perhaps it should be a separate tick box?
