### ISSUE TITLE
Altered/not altered on newly imported pictures

### ISSUE THREAD

**Issue by homer3018** [darktable-org/darktable#3818]
**Describe the bug**
I'm reporting what I think is a bug or at least a discripency. I am importing regularly the same folder as I add pictures in it. I have a standard style that I apply on each picture that is giving the baseline for my edits. Upon importing the same folder once more, I was trying to locate the last picture to have at least my style in the history, and realise while in the lighttable that some photos were not showing the altered icon, and some that obviously I had just imported were showing it.
I checked one of the very latest which was showing an icon in the darkroom and saw that the history was the default one. Back on the lighttable I understood that there was no way for me to differentiate the pictures that had my style, and the new one without it but just with the default history, since all of them will be altered, but that is something else... I'm writing this just for more context about how it happened.
The issue is with the altered icon which was not showing initially. It did show on some picture after I previewed it full screen using the W key. Once the embedded jpg ignored, and the raw with its default history loaded up, the icon (upon releasing the W key) showed up, but I did not touch the history, and I didn't even go into the darkroom.

**To Reproduce**
1. Import some pictures
2. Check whether or not you see the altered icon in the corner or each thumbnail in the lighttable (I had none)
3. Preview it full screen using the (default) W key
4. Release W key to go back on the lighttable and check that now the altered icon is showing up
5. We can push this further using the dedicated filter. Select altered or not altered. This will initially show you how many are in each case.
6. Suppose you're viewing the not altered ones, preview one using W, and upon releasing the key, it will disappear since it is now altered, however the number for altered and not altered are not being refreshed.

**Expected behavior**
Not sure here. Either the default history, since it is the default, is not considered as "altering the picture", and in this case, it should still not show until we go in the darkroom and we add a module.
Or the default history is considered as altered, and newly imported picture should show straight away the icon, but then it defeats the filtering purpose of altered vs not altered, since every single pic will be altered (unless the user choose deliberately to remove everything ?)
In any case I'd have expected at least the number in the filter to refresh as pictures got altered by being rendered full screen with the previewing tool.

**Screenshots**
not relevant

**Platform (please complete the following information):**
 - OS: MacOS 10.15 Catalina
 - Version 3.0 rc2 +130 (92e7d3d4a99229a47ca4beb061bc7d48bf7826e0)
 - OpenCL activated
 - AMD Radeon Pro 580, not sure about the driver used in the back end.

**Comment by arigit** [comment]
Duplicate of #3815 - it's a bug and there is patch there that you can test. Just tested it and it works.

**Comment by homer3018** [comment]
Oup's sorry about the duplicate, but at least it's been captured so that's good.
I'll wait for the PR to be merged then.
Thanks.
Closing.
