### ISSUE TITLE
Error into Rec2020 Primaries values?

### ISSUE THREAD

**Issue by RigacciOrg** [darktable-org/darktable#3823]
I was examining the source code **src/common/colorspaces.c**, searching for the **Rec2020** definition.

I compared the constant values against the ITU document [R-REC-BT.2020-2-201510-I!!PDF-E.pdf](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2020-2-201510-I!!PDF-E.pdf) and I found a difference into the **red primary** color:
```
Rec2020_Primaries = {
  {0.7000, 0.2920, 1.0}, // red
  {0.1700, 0.7970, 1.0}, // green
  {0.1310, 0.0460, 1.0}  // blue
};
```
the ITU document, in Table 3, states instead a Red primary x value of **0.708**. Is this a problem?

**Comment by TurboGit** [comment]
Arg!!! Indeed a cut&paste error on my side :( Will fix right away and thanks for reporting that.... Just in time for the release coming!

**Comment by TurboGit** [comment]
Fixed now. Thanks!

**Comment by TurboGit** [comment]
For reference commit is: aba3ee3
