### ISSUE TITLE
Title Bar looks weird on Windows 10

### ISSUE THREAD

**Issue by xorz57** [darktable-org/darktable#3824]
Bugs report just saying it crashes without filling most of the items
below and making no effort to help developpers to reproduce will be
closed without notice.

**Describe the bug**
I wouldn't call it a bug but it looks very weird. Maybe it is a limitation of what GTK can do.
The title bar looks very weird. The top left is a rounded corner and the top right is a sharp corner.
Also the "exit" button is protruding from the title bar.

**To Reproduce**
1. Just launch the application
2. Notice the up right corner of the title bar

**Expected behavior**
I don't know what can be done about it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1548352/71261479-25f94f00-2346-11ea-9791-55cc5f990ec9.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 1903
 - OpenCL activated
 - GTX 1070 and 441.66

**Additional context**
Add any other context about the problem here, for example:
 - Can you reproduce with another dt version?
 - Can you reproduce with a RAW or Jpeg or both?
 - Are the steps above reproduce with a fresh edit (removing history)?
 - Attach an XMP if this is necessary
 - Is dt compiled by yourself? If so which compiler is used? Which options?
 - Is the issue still present using an empty/new config-dir

**Comment by phrrk** [comment]
I see that you are using dt version 2.6.6.  With 3.0.0rc2 and similar windows setup I don't see this issue.  There have been a lot of improvements made to the appearance of the interface, so I would consider upgrading.  I guess that version 3.0 will be released in the next few days

**Comment by Nilvus** [comment]
Indeed, UI is quite different on 3.0 (release will probably be tuesday) and your title bar is awful. Anyway, the title bar is not darktable related but OS related (here, if you use Windows, it's the way title bar is rendered by Windows, probably for Gtk if you don't have that on non Gtk apps ; I don't use Windows). I'm on Linux and if, I change my desktop environment theme, this bar will change on all apps I'm using (all Gtk apps) and rendering will be the same on each app. So, as darktable team can't do anything about that, think of closing this issue. Thanks.

**Comment by xorz57** [comment]
@Nilvus Thanks for the information!!! I will proceed to close this issue now.
