### ISSUE TITLE
in darktable everything is written in lower case

### ISSUE THREAD

**Issue by mepi0011** [darktable-org/darktable#3829]
Referring to the discussion I started in the darktable mailing list (see [here](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg05096.html)), I would like to open the topic here as an issue.

I think users find it strange if everything is written in small letters.
I would be willing, if desired, to take the lead on this issue to capitalize the letters and bring it into the right form.

I think the best time to address this issue is between the release of darktable 3.0.1 and the next December release. Pascal Obry suggested to use a script for this change. Unfortunately I don't have the experience here and I'm dependent on you for support (suggestions are welcome).

For the implementation I think a separate branch would be helpful. In addition, the translators must be involved.  Suggestions how the change can be done are welcome.

**Comment by Nilvus** [comment]
Duplicates this one #2078
