### ISSUE TITLE
Lua: need control over lighttable position

### ISSUE THREAD

**Issue by angryziber** [darktable-org/darktable#3831]
Currently there is (undocumented) `darktable.gui.libs.lighttable_mode.zoom_level()` that can be used to read/change zoom level, but nothing to move up-down, navigate.

This would be useful to implement go-to functionality, e,g, go to next tagged, labelled, etc photo in the current collection. So ideally there would be an api like `scroll_to(image)` or `ensure_visible(image)`.

There is api to read hovered image or change selection, but it doesn't affect the current scolling position, so cannot be used for navigation.

**Comment by wpferguson** [comment]
Actually, it is documented in the darktable 3.0.0 lua-api manual.  Currently the only way to get it is build from source.  Once 3.0.0 is released, I'm sure the manuals on the website will be updated.

In the next day or so, I'll add a post to pixls.us documenting the new api changes.  There is also example code in a pull request, https://github.com/darktable-org/lua-scripts/pull/203, demonstrating all the lua-api changes.

**Comment by wpferguson** [comment]
As far as the request for an api change, others have asked for similar changes.  I'll take a look at the code and see what needs to be done after 3.0.0 is released.

**Comment by angryziber** [comment]
great, thanks for the info!

**Comment by wpferguson** [comment]
Still valid.  I'll start working on it...

**Comment by wpferguson** [comment]
@angryziber, @supertobi, @TurboGit  any idea where in the API to put this?  I'm thinking maybe darktable.gui.views.lighttable.ensure_image_visible(imgid) to make sure the image is visible in the lighttable and/or darktable.gui.views.lighttable.image_visible(imgid) to set the image to the upper left corner.

**Comment by supertobi** [comment]
darktable.gui.views.lighttable.* sounds good. What do you think about:
set_image_visible(imgid)
is_image_visible(imgid)

**Comment by wpferguson** [comment]
@supertobi took your suggestions.  Done and submitted.
