### ISSUE TITLE
Can't get "splitline" in Darktable to compare snapshots?

### ISSUE THREAD

**Issue by flycaster** [darktable-org/darktable#3832]
I am in the evaluation stage of Darktable.  I am having much trouble in being able to check the editing progress when trying to compare images.  No matter what I do, I can't get the splitline to appear.  In order to save time, please refer to the following site to see my efforts at gaining a solution to this issue: https://discuss.pixls.us/t/before-after-not-working/15350/4.  BTW, I have uninstalled and then reinstalled version 2.3.6 thinking that the first download may have been corrupt.  Thanks for your help.

**Comment by wpferguson** [comment]
Open the image in darkroom mode
Open the snapshots module and reset it to remove any existing snapshots
Open the history stack and click on entry 0 - original
In the snapshots module click the take snapshot button
In the history stack, click on the top entry in the history stack
In the snapshots module, click on the snapshot, i.e. original (0)

This should give you the split.

To turn it off, click on the snapshot again.

**Comment by flycaster** [comment]
> 
> 
> Open the image in darkroom mode
> Open the snapshots module and reset it to remove any existing snapshots
> Open the history stack and click on entry 0 - original
> In the snapshots module click the take snapshot button
> In the history stack, click on the top entry in the history stack
> In the snapshots module, click on the snapshot, i.e. original (0)
> 
> This should give you the split.
> 
> To turn it off, click on the snapshot again.

Followed instructions step by step, Original and last image showed up as expected, however no splitline.  I'm in Windows 10 and have Firefox and Thunderbird opened; maybe I should close them?  There has to be something interfering with the process???

**Comment by TurboGit** [comment]
IIRC this was broken on 2.6.3 Windows and should now be fixed in coming release.
