### ISSUE TITLE
Horizontal flip followed by staright using right click in crop rotates it in the wrong direction

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3833]
1. Flip an image horizontally.
2. Go to crop and use the right click to level horizon.
3. Rotates in opposite direction. The angle should be negative of what was determined as the horizon levelling still uses the actual image.

Alternate is to level before flipping.

Version : darktable-3.1.0+8~g7871a4f25-win64

**Comment by junkyardsparkle** [comment]
(Also happens with vertical flip.)

**Comment by TurboGit** [comment]
Flip with the crop&rotate module, right? So point 2 "go to crop..." means you are already in crop. All in all, this issue is all in crop&rotate, right?

**Comment by TurboGit** [comment]
This is only a display issue of the rotation angle right? Nothing critical to me then...

**Comment by chhil** [comment]
You cant level, you select the horizon line and it gets worse.

**Comment by TurboGit** [comment]
I see, I can finally reproduce !

**Comment by TurboGit** [comment]
This will be fixed in 3.0.1.
