### ISSUE TITLE
Watermark text length restricted to 60 character when composited on the image

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3840]
Was trying to put a text longer than 60 as watermark.
Text field of the module allows the length but when composited on the image it only displays 60. 

This limit needs to be bigger or at least configurable.

Version : darktable-3.1.0+8~g7871a4f25-win64

**Comment by TurboGit** [comment]
There is indeed a limit of 64 characters. Question, is what could be a good limit?

**Comment by TurboGit** [comment]
I've proposed this #3851. Comment welcome !
