### ISSUE TITLE
Export: remember exported links/ids, so that exported photos can be updated after changes

### ISSUE THREAD

**Issue by angryziber** [darktable-org/darktable#3842]
It would be great to store (probably non-filesystem) exports to the DB, so that exported photos could be matched later with photos in the DB and vice-versa.

The main functionality that this could enable is re-export (update) a photo again after it has been changed in Darktable. Even if not implemented in Darktable itself, it could be done using lua scripts perhaps.

Many Lightroom export plugins provide this feature and it is very convenient. Usually there is a prompt to re-export an image after additional edits.

**Comment by angryziber** [comment]
All online exporters have been deleted from master.
I hope this can be reverted...

**Comment by TurboGit** [comment]
No, won't be restored, read #4008.
