### ISSUE TITLE
Make selected Preset more distinct

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#3843]
**Is your feature request related to a problem? Please describe.**
For most modules, the selected preset currently is just bold on the preset list, making it sometimes hard to spot.

**Describe the solution you'd like**
Since we have the space for the checkbox to the left of the label/text (for the "favourite" line at the bottom of the list), perhaps we can add a different symbol to the left of the text for the selected preset? Hopefully that'll make it easier to spot the currently selected preset.

**Comment by johnny-bit** [comment]
@Nilvus - what do you think about adding a checkbox to current present instead of "just" bolding it?

**Comment by Nilvus** [comment]
@johnny-bit: or simply the **✔** symbol, yes. Could you do that?

**Comment by Nilvus** [comment]
Not in green color of course, just the symbol (the color is just github thing!

**Comment by Nilvus** [comment]
This should probably on lines and files used in that PR to add it but not sure how to do it, even if that doesn't seems difficult: https://github.com/darktable-org/darktable/pull/7671/files

**Comment by johnny-bit** [comment]
Please test (if you can) PR #9557 - should fix the issue completely :)
