### ISSUE TITLE
styles editor have empty list - dt 3.0.0

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#3846]
Editing styles is impossible in dt 3.0.0 because the editor window is empty.

Reproduce:

Go to "styles" panel at the lighttable, choose any stlye and click edit.

![Képernyőkép erről: 2019-12-24 10-33-21](https://user-images.githubusercontent.com/57588193/71406760-618f6400-2639-11ea-99b3-eee58fa56b60.png)

Ubuntu 19.10
darktable 3.0.0
active OpenCL

**Comment by TurboGit** [comment]
Yes, just found out this yesterday, it is fixed in #3839 and will be in 3.0.1.

**Comment by TurboGit** [comment]
I'll keep this open in the hope that people will look here and avoid creating plenty of other issues for this :)

**Comment by TurboGit** [comment]
Fixed.

**Comment by t3mujin** [comment]
While the 3.0.1 version isn't released, is there any workaround for this in 3.0.0?

**Comment by aurelienpierre** [comment]
Fixed.
