### ISSUE TITLE
lg-h910 fails to show up in darktable windows for importing 

### ISSUE THREAD

**Issue by xhozt** [darktable-org/darktable#3847]
Follow up to #3671 and to quote LebedevRI
"That is a DNG camera, no support needed, it just works." Well It does not . 

**To Reproduce**
Plug in camera . set to mtp or ptp .
open darktable in windows 10 build 1809 . 
the device does not show under any of the import options at all . 
only workaround is to move to a drive then import . 

![Annotation 2019-12-24 050811](https://user-images.githubusercontent.com/36472754/71410551-6f2df500-260b-11ea-9450-5fec423a13d0.jpg)
![Annotation 2019-12-24 051034](https://user-images.githubusercontent.com/36472754/71410658-c207ac80-260b-11ea-9e31-f00abc980477.jpg)
![Annotation 2019-12-24 051011](https://user-images.githubusercontent.com/36472754/71410664-c7fd8d80-260b-11ea-9eef-d3badd91459e.jpg)

**Comment by parafin** [comment]
import from device is not a core functionality, libgphoto is used for that, so this should be requested from them.
