### ISSUE TITLE
[Retouch]switch between clone/heal and blur/color modes in 'retouch' module does not work.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3849]
Retouch Module.
Selected a fill color, selected a fill color from color palette.
Selected path tool and draw a shape. On closing shape, it gets filled.
Now I control click the blur tool, shows working, but the color fill remains.
I was expecting the color fill to get removed and get a blurred region in the path instead.

I did the same thing with clone/heal and did not see the effect I was expecting.

Maybe I don't understand what this new feature is supposed to do based on what I read 
in the release notes "Allow to switch between clone/heal and blur/color modes in 'retouch' module
after creating a shape using Ctrl+click on corresponding mode icon."

Version 3.1.0+8 win 10.

**Comment by chhil** [comment]
After the above control click experiment. Now regular retouch heal/clone does not work.

**Comment by chhil** [comment]
See the paths, have no effect, one is using clone, one is using heal.

![image](https://user-images.githubusercontent.com/1119439/71417747-04bd9900-268d-11ea-96d4-3e19a5096a8d.png)

**Comment by arigit** [comment]
See #3772, you may be hitting the same bug. Opacity is set to 0% by default for all masks including the ones created for retouching. Meaning that unless you manually change it to 100%, retouches will have no effect

Also discussed here
https://discuss.pixls.us/t/masks-hardness-vs-opacity-the-default-value-for-opacity-for-new-mask-shapes/15377

**Comment by chhil** [comment]
@arigit , you are absolutely correct. 

![image](https://user-images.githubusercontent.com/1119439/71428956-1719f000-26ea-11ea-9240-4f58c8ce22f5.png)
