### ISSUE TITLE
Color Zone module messed cloud easily when I tried to darken blue sky

### ISSUE THREAD

**Issue by HardySoftware** [darktable-org/darktable#3852]
**Describe the bug**
The my title suggested, you can open any raw image with blue sky and white cloud, as soon as I start to darken blue sky by using Color Zone module, the cloud started to mess up.

**To Reproduce**
Please see my screenshot https://imgur.com/a/6lRivgt, zoom it to 100% view, you can easily figure out the steps. All I have is the default steps + basic adjustment (exposure + black) + color zone. And you can see the outcome.

**Expected behavior**
The cloud should not have sharp edges

**Screenshots**
https://imgur.com/a/6lRivgt, zoom it to 100% view

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 3.0 formal release
 - OpenCL activated yes
 - which GFX-card and GFX-driver: AMD RX5 590 with Radeon Adrenalin 2019 driver

**Additional context**
Add any other context about the problem here, for example:
 - Can you reproduce with another dt version? Yes 3.0rc2 has same issue.
 - Can you reproduce with a RAW or Jpeg or both? I only have raw, no JPEG image.
 - Are the steps above reproduce with a fresh edit (removing history)? Yes
 - Attach an XMP if this is necessary, please see attachment
 - Is dt compiled by yourself? If so which compiler is used? Which options? No, I downloaded it from official web site
 - Is the issue still present using an empty/new config-dir, what is this directory?

[DSC_4728_01.NEF.zip](https://github.com/darktable-org/darktable/files/3998916/DSC_4728_01.NEF.zip)

**Comment by TurboGit** [comment]
Change the mode in module from strong to smooth or something like that.

**Comment by HardySoftware** [comment]
Ok, that works. Thanks

Anyway to set it to default process mode?

**Comment by TurboGit** [comment]
No, you have to change the mode. In many cases the default works well.

**Comment by aurelienpierre** [comment]
For future reference, this is a problem with the maths, not with the actual code.The hue mask transition is too harsh.

**Comment by HardySoftware** [comment]
So, would it make more sense to re-open this ticket and adjust the math?

**Comment by aurelienpierre** [comment]
We can't fix the maths once the module is published. The algorithm should stay the same to ensure compatiblity with previous edits. The most we can do is add alternatives blendings, like the smooth variant.
