### ISSUE TITLE
Parametric mask's "h" channel lost picker indicator

### ISSUE THREAD

**Issue by HardySoftware** [darktable-org/darktable#3853]
[DSC_4728_01.NEF.zip](https://github.com/darktable-org/darktable/files/3998923/DSC_4728_01.NEF.zip)
**Describe the bug**
I use parametric mask's h channel, if I drop a picker to my pictcure, there should be a vertical bar on input/output to indicate what color is under the picker, but there is none.

**To Reproduce**
1. Go to any module with h channel in parametric mask
2. Click on the single picker and drop it to somewhere on the photo
3. I don't know what color is selected

**Expected behavior**
I should be able to see a vertical bar to indicate the color being selected.

**Screenshots**
https://imgur.com/a/zVTj7iA zoom into to view 100%

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 3.0 formal release
 - OpenCL activated yes
 - which GFX-card and GFX-driver, AMD RX 590 + Radeon Adrenalin 2019 driver

**Additional context**
Add any other context about the problem here, for example:
 - Can you reproduce with another dt version? Yes 3.0rc2 has the same issue
 - Can you reproduce with a RAW or Jpeg or both? I only have raw images.
 - Are the steps above reproduce with a fresh edit (removing history)? Yes
 - Attach an XMP if this is necessary, see attachment
 - Is dt compiled by yourself? If so which compiler is used? Which options? No, official download
 - Is the issue still present using an empty/new config-dir, no idea what it is.

[DSC_4728_01.NEF.zip](https://github.com/darktable-org/darktable/files/3998925/DSC_4728_01.NEF.zip)

**Comment by vsz1lu** [comment]
I can't confirmed - on Ubuntu 19.10 works fine. OpenCL on.

**Comment by HardySoftware** [comment]
Any other Windows users can confirm?

**Comment by junkyardsparkle** [comment]
The picker is there, it's just very, very hard to see due to its color against that particular slider background. I thought there was already an issue for this, but can't find it now.

**Comment by johnny-bit** [comment]
On current master indicator is very well visible :)

![Zrzut ekranu z 2020-12-22 23-30-08](https://user-images.githubusercontent.com/10687765/102938997-ac8ec200-44ad-11eb-8b4b-fa3baa02403b.png)
