### ISSUE TITLE
3.0 crash on windows

### ISSUE THREAD

**Issue by OpenCoderX** [darktable-org/darktable#3856]
**Describe the bug**
Error message after launching 3.0 from Windows Start Menu

**To Reproduce**
1. Click Program Entry from start menu

**Expected behavior**
App should open

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - OpenCL: no
 - which GFX-card and GFX-driver: quadro m2200 , driver 431.94

**Additional context**
this is darktable 3.0.0 reporting an exception:

-------------------

Error occurred on Tuesday, December 24, 2019 at 16:38:28.

darktable.exe caused an Access Violation at location 00007FFED3D00819 in module igdrclneo64.dll Reading from location 0000000000000020.

AddrPC           Params
00007FFED3D00819 000000000061E828 00007FFED3EBCD00 0000000000000001  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FFED3CEC4A7 00007FFEDF2A3277 0000000000000001 0000000000000001  igdrclneo64.dll!0x7ffe0001c4a7
00007FFED3D3CEDA 0000598B14BF80F9 0000000000000000 0000000000000000  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FFED3CED10E 00000000083EDD70 0000000000000000 0000000000000000  igdrclneo64.dll!clGetPlatformIDs
00007FFED3CF41E9 00000000083EDD90 00007FFED3CF3C80 00000000083EDD70  igdrclneo64.dll!clEnqueueTask
00007FFEDF2A32B5 00007FFF02F24C08 0000000000000000 0000000000000000  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FFEDF26C85B 00007FFEDF2648A9 00007FFF02F3AEB0 00007FFEDF260000  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FFF02EC684C 0000000000000000 000000000061EFB0 0000000000000000  OpenCL.dll!clEnqueueWriteBufferRect
00007FFF02EC9147 0000000000000000 0000000000000000 0000000000000014  OpenCL.dll!clEnqueueWriteBufferRect
00007FFF2330D58F 0000000005ED2170 0000000000000000 000000000061F4D4  ntdll.dll!RtlRunOnceExecuteOnce
00007FFF1F3DCCAB 0000000000000014 0000000000000300 0000000000000000  KERNELBASE.dll!InitOnceExecuteOnce
00007FFF02EC899C 0000000000000300 0000000005ED2170 00000000056D8A40  OpenCL.dll!clEnqueueWriteBufferRect
0000000063668BC2 000000000061F8A0 0000000000000000 0000000000000000  libdarktable.dll!dt_opencl_init  [D:/build/darktable/src/common/opencl.c @ 636]
00000000635E5890 00007FFF00000001 00000000033B2490 00007FFF00000001  libdarktable.dll!dt_init  [D:/build/darktable/src/common/darktable.c @ 916]
0000000000403079 0000000000000010 0000000000000000 0000000000000000  darktable.exe!main  [D:/build/darktable/src/main.c @ 92]
00000000004015F8 000000000000005A 0000000000000000 0000000000408600  darktable.exe!wmain  [D:/build/darktable/src/win/main_wrapper.h @ 15]
00000000004013EE 0000000000000000 0000000000000000 0000000000000000  darktable.exe!__tmainCRTStartup  [E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 334]
000000000040153B 0000000000000000 0000000000000000 0000000000000000  darktable.exe!mainCRTStartup  [E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 223]
00007FFF22C77974 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFF2332A271 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.0.0.0
ntdll.dll   	10.0.17763.831
KERNEL32.DLL	10.0.17763.475
KERNELBASE.dll	10.0.17763.914
apphelp.dll 	10.0.17763.292
AcLayers.DLL	10.0.17763.292
msvcrt.dll  	7.0.17763.475
USER32.dll  	10.0.17763.914
win32u.dll  	10.0.17763.1
GDI32.dll   	10.0.17763.592
gdi32full.dll	10.0.17763.914
msvcp_win.dll	10.0.17763.348
ucrtbase.dll	10.0.17763.719
SHLWAPI.dll 	10.0.17763.1
combase.dll 	10.0.17763.737
RPCRT4.dll  	10.0.17763.864
bcryptPrimitives.dll	10.0.17763.678
ADVAPI32.dll	10.0.17763.1
sechost.dll 	10.0.17763.1
sfc.dll     	10.0.17763.1
WINSPOOL.DRV	10.0.17763.592
kernel.appcore.dll	10.0.17763.1
bcrypt.dll  	10.0.17763.1
PROPSYS.dll 	7.0.17763.719
OLEAUT32.dll	10.0.17763.914
shcore.dll  	10.0.17763.1
IPHLPAPI.DLL	10.0.17763.615
sfc_os.DLL  	10.0.17763.1
SortWindows61.dll	10.0.17763.1
IMM32.DLL   	10.0.17763.719
libglib-2.0-0.dll	2.62.2.0
libintl-8.dll	0.19.8.0
ole32.dll   	10.0.17763.503
libdarktable.dll
libiconv-2.dll	1.16.0.0
SHELL32.dll 	10.0.17763.831
PSAPI.DLL   	10.0.17763.1
cfgmgr32.dll	10.0.17763.1
libwinpthread-1.dll	1.0.0.0
windows.storage.dll	10.0.17763.831
libgcc_s_seh-1.dll
libstdc++-6.dll
profapi.dll 	10.0.17763.1
exchndl.dll 	0.9.2.0
libcairo-2.dll
libcurl-4.dll
CRYPT32.dll 	10.0.17763.864
libexiv2.dll
powrprof.dll	10.0.17763.1
libgdk-3-0.dll	3.24.13.0
MSASN1.dll  	10.0.17763.1
WS2_32.dll  	10.0.17763.771
cryptsp.dll 	10.0.17763.1
SETUPAPI.dll	10.0.17763.404
WLDAP32.dll 	10.0.17763.831
libgdk_pixbuf-2.0-0.dll	2.40.0.0
libgmodule-2.0-0.dll	2.62.2.0
libgphoto2_port-12.dll
libgobject-2.0-0.dll	2.62.2.0
libgphoto2-6.dll
libgtk-3-0.dll	3.24.13.0
libjpeg-8.dll
libGraphicsMagick-3.dll
libIlmImf-2_4.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
libpango-1.0-0.dll	1.43.0.0
lua53.dll
libpangocairo-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
libsecret-1-0.dll
libsoup-2.4-1.dll
libtiff-5.dll
libsqlite3-0.dll
libxml2-2.dll
zlib1.dll
mgwhelp.dll 	0.9.2.0
VERSION.dll 	10.0.17763.1
libfontconfig-1.dll
MSIMG32.dll 	10.0.17763.1
libfreetype-6.dll	2.10.1.0
libpixman-1-0.dll
dwmapi.dll  	10.0.17763.719
libpcre-1.dll
libbrotlidec.dll
libidn2-0.dll
WINMM.dll   	10.0.17763.1
libcairo-gobject-2.dll
libnghttp2-14.dll
libpsl-5.dll
libepoxy-0.dll
libssl-1_1-x64.dll	1.1.1.4
libpangowin32-1.0-0.dll	1.43.0.0
gdiplus.dll 	10.0.17763.914
libsystre-0.dll
libexif-12.dll
libffi-6.dll
libbz2-1.dll
comdlg32.dll	10.0.17763.771
libHalf-2_4.dll
libIex-2_4.dll
libIlmThread-2_4.dll
libthai-0.dll
libpangoft2-1.0-0.dll	1.43.0.0
libgcrypt-20.dll	1.8.5.54720
liblzma-5.dll	5.2.4.0
libzstd.dll
dbghelp.dll 	10.0.17763.1
libharfbuzz-0.dll
winmmbase.dll	10.0.17763.1
libtre-5.dll
USP10.dll   	10.0.17763.864
COMCTL32.dll	6.10.17763.831
libatk-1.0-0.dll	2.34.1.0
libdatrie-1.dll
libgraphite2.dll
dbgcore.DLL 	10.0.17763.1
libgomp-1.dll
libgio-2.0-0.dll	2.62.2.0
libopenjp2-7.dll
librsvg-2-2.dll
libexpat-1.dll
libcrypto-1_1-x64.dll	1.1.1.4
libfribidi-0.dll
libltdl-7.dll
libunistring-2.dll	0.9.10.0
libImath-2_4.dll
libgpg-error-0.dll	1.36.0.0
libbrotlicommon.dll
DNSAPI.dll  	10.0.17763.652
NSI.dll     	10.0.17763.831
libcroco-0.6-3.dll
CRYPTBASE.DLL	10.0.17763.1
rsaenh.dll  	10.0.17763.1
uxtheme.dll 	10.0.17763.831
clbcatq.dll 	2001.12.10941.16384
mswsock.dll 	10.0.17763.292
rasadhlp.dll	10.0.17763.1
fwpuclnt.dll	10.0.17763.771
MSCTF.dll   	10.0.17763.831
DEVOBJ.dll  	10.0.17763.771
WINTRUST.dll	10.0.17763.348
winhttp.dll 	10.0.17763.771
IconCodecService.dll	10.0.17763.1
WindowsCodecs.dll	10.0.17763.55
libpixbufloader-png.dll
mscms.dll   	10.0.17763.1
ColorAdapterClient.dll	10.0.17763.1
USERENV.dll 	10.0.17763.831
icm32.dll   	10.0.17763.1
TextInputFramework.dll	10.0.17763.1
CoreUIComponents.dll	10.0.17763.1
CoreMessaging.dll	10.0.17763.194
ntmarta.dll 	10.0.17763.1
wintypes.dll	10.0.17763.737
Oleacc.dll  	7.2.17763.1
OpenCL.dll  	2.2.1.0
nvopencl64.dll	26.21.14.3194
nvapi64.dll 	26.21.14.3194
dxgi.dll    	10.0.17763.771
IntelOpenCL64.dll	23.20.16.4973
igdrclneo64.dll

Windows 6.2.9200
DrMingw 0.9.2

**Comment by johnny-bit** [comment]
The issue is due to faulty Intel OpenCL drivers on windows. Update to newest version reportably helps (also removing those helps too if OpenCL was just working on cpu)
