### ISSUE TITLE
3.0.0 : Can't set preferences on 14" screen, "Close" below screen (Windows 10)

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#3858]
**Describe the bug**
Can't set preferences in lighttable on 14" screen notebook. The "Close" button is below screen (Windows 10) and can't be clicked.

This should NOT effect larger screen devices! My notebook is 14"

**To Reproduce**
1. Go to 'darktable > lighttable'
2. Click on 'preferences' icon
3. Scroll down to 'bottom'
4. See error: Bottom of preferences window not visible

**Expected behavior**
Being able to see and click the 'close' button.

**Screenshots**
attached

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version dt 3.0.0

<img width="960" alt="Screenshot 2019-12-25 08 00 18" src="https://user-images.githubusercontent.com/3244771/71427004-c1dfdd80-26ed-11ea-925e-8d18fd5ac3d4.png">

**Comment by TurboGit** [comment]
I suppose it is not a 14" issue but a definition. What is the definition of the screen?

**Comment by 4044ever** [comment]
> I suppose it is not a 14" issue but a definition. What is the definition of the screen?

Good point! I use 1920 x 1080 - which is already the maximum I can use. I solved this issue for me by switching the orientation portrait mode, setup my preferences, and then back to landscape mode.

**Comment by MStraeten** [comment]
Try some settings for screen_dpi_overwrite  settings in darktablerc file in your .config/darktable folder. It’s default is -1, but setting it to an explicit value might help (for a 14“ display full HD is ~157 dpi)

**Comment by 4044ever** [comment]
> Try some settings for screen_dpi_overwrite settings in darktablerc file in your .config/darktable folder. It’s default is -1, but setting it to an explicit value might help (for a 14“ display full HD is ~157 dpi)

It would enhance the user experience if preferences could be set regardless of screen size. Just making the preferences windows responsive (I have no idea how difficult that is) or simply make it a bit smaller (you need to scroll anyway). I think more of beginner level users.

I like to add that the 'Close' button on my notebook is just out of the screen. On my desktop (uses also 1920 x 1080) everything is visible. Both claim 16:9. So it's not just the resolution.

**Comment by chhil** [comment]
Having an accelerator on 

1. the close button would be very helpful.
1. tabs in the preference dialog.

Also enabling tab keypress to move around in the dialog would be a good addition.

**Comment by aurelienpierre** [comment]
Fixed.
