### ISSUE TITLE
Unwanted image rating changes in darkroom mode.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#3866]
In darkroom mode, the rating of an image can be changed when clicking on an area outside the rating stars on the image tile.

**To Reproduce**
1. Enter darkroom mode with more than one image in the collection.
1. Move the cursor onto an image in the bottom bar that is not the one currently displayed.
1. Hover over one of the rating stars at the bottom of the image tile.
1. Move the cursor vertically upward from the star onto the image itself.
1. Note that the star previously hovered over is still highlighted.
1. Double-click to open the image in the darkroom.
1. Note that the image's rating has changed.

**Expected behavior**
After the cursor is moved vertically upward, the star should no longer be highlighted, nor should clicking outside the area of the star change the rating.

**Platform (please complete the following information):**
 - OS: Fedora 31, macOS 10.14
 - Version 3.0.0

**Comment by PeterWem** [comment]
I had the same problem. Solved it by pressing "Hide image overlay" twice.

**Comment by AlicVB** [comment]
Will be fixed in my upcomming rewrite...

**Comment by AlicVB** [comment]
closing, now that lighttable rewrite as landed in master
