### ISSUE TITLE
OpenCL not run when default config folder are modified.

### ISSUE THREAD

**Issue by gitdarktable** [darktable-org/darktable#3867]
Created a direct access on desktop with other folders for config and cache:

X:\darktable\bin\darktable.exe --configdir W:\config --cachedir W:\cache

and OpenCL are disable.

If run only:

X:\darktable\bin\darktable.exe

create the default configuration folder in

U:\Users\UUUUU\AppData\Local\darktable\

and OpenCL run great.

If copy configuration files from other config folder to default folder also run great.

How can I use other folders and make OpenCL work?

System: Windows 7 x64 Pro and APU AMD video graphics.

**Comment by aurelienpierre** [comment]
Please post the content of darktablerc regarding lines containing `opencl`.

**Comment by MStraeten** [comment]
Maybe it needs several starts until all opencl kernels are build properly (on osx i need about 4-28 starts on different machines)
 If you run darktable-cltest, you can see if kernels are properly built or not - and it doesnt start a gui so several subsequent starts can be done more effective ...

**Comment by gitdarktable** [comment]
I replaced the OpenCL lines in darktablerc of the default directory to the alternative directory in the darktablerc file and OpenCL did not work. 

That's why I opened this is issue.
I think the OpenCL configuration could be out of darktablerc.

Default folder and OpenCL run great:

opencl=TRUE
opencl_async_pixelpipe=false
opencl_avoid_atomics=false
opencl_checksum=474798940
opencl_device_priority=*/!0,*/*/*
opencl_disable_drivers_blacklist=false
opencl_library=
opencl_mandatory_timeout=200
opencl_memory_headroom=300
opencl_memory_requirement=768
opencl_micro_nap=1000
opencl_number_event_handles=25
opencl_scheduling_profile=very fast GPU
opencl_size_roundup=16
opencl_synch_cache=false
opencl_use_cpu_devices=false
opencl_use_pinned_memory=false

Other folder config and OpenCL not run:

opencl=TRUE
opencl_async_pixelpipe=false
opencl_avoid_atomics=false
opencl_checksum=474798940
opencl_device_priority=*/!0,*/*/*
opencl_disable_drivers_blacklist=false
opencl_library=
opencl_mandatory_timeout=200
opencl_memory_headroom=300
opencl_memory_requirement=768
opencl_micro_nap=1000
opencl_number_event_handles=25
opencl_scheduling_profile=default
opencl_size_roundup=16
opencl_synch_cache=false
opencl_use_cpu_devices=false
opencl_use_pinned_memory=false

**Comment by jenshannoschwalm** [comment]
> Maybe it needs several starts until all opencl kernels are build properly (on osx i need about 4-28 starts on different machines)

Does it have to be this way? Is there a chance to do some sort of loop trying to compile the cl kernels terminating when either all kernels are compiled or ill-terminating when this could not be done.

Why is osx behaving like this, btw?

**Comment by parafin** [comment]
This is a bug in macOS OpenCL library and I doubt it's resolvable without application restart. Though maybe just reloading OpenCL library may be enough.

**Comment by MStraeten** [comment]
> > Maybe it needs several starts until all opencl kernels are build properly (on osx i need about 4-28 starts on different machines)
> 
> Does it have to be this way? Is there a chance to do some sort of loop trying to compile the cl kernels terminating when either all kernels are compiled or ill-terminating when this could not be done.
> 
a little script can do this: https://discuss.pixls.us/t/current-osx-build/13213/9

**Comment by gitdarktable** [comment]
Solved:

I deleted other folders config and have been created new for darktable from direct access on desktop.
I move all files config to these new folders and OpenCL run great.

They may have been permissions of the system NT folders because I have them synchronized with other computers. He had created the folders before he did darktable.

Please close this issue, my apologies for this wasted time.

**Comment by johnny-bit** [comment]
> Please close this issue, my apologies for this wasted time.

No problem!
