### ISSUE TITLE
Mark soon to be obsolete modules, see example...

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#3869]
3.0.0 on Windows 10, but I guess it's same for all versions.

Some modules seems to have a newer version but the old version is still operational in the menu. 

Example: 
_contrast brightness saturation_ looks to be beaten by _basic adjustments_

IMHO it might be a good idea soon to be legacy modules marked in some ways,

**Comment by MStraeten** [comment]
Basic adjustment is not a replacement since it combines several modules that are better placed at different positions in the pixel pipe. It’s just a noob-module - one to rule them all

**Comment by pphotography** [comment]
Think that there should be a part in the manual (maybe a table) that lists all modules and their status (like 'up to date', 'for beginners' or 'deprecated').

I could start such a table, how do I get a list of all available modules?

**Comment by pphotography** [comment]
OK, I took all modules that appear in darktable under 'more modules' and assigned them to a module group


group|module
------------ | -------------
basic|base curve
basic|basic adjustments
basic|color reconstruction
basic|contrast brightness saturation
basic|crop and rotate
basic|demosaic
basic|exposure
basic|highlight reconstruction
basic|invert
basic|orientation
basic|raw black/white point
basic|shadows and highlights
basic|tone equalizer
basic|white balance
tone|fill light
tone|filmic
tone|filmic rgb
tone|global tonemap
tone|levels
tone|local contrast
tone|rgb curve
tone|rgb levels
tone|tone curve
tone|tone mapping
tone|zone system
color|channel mixer
color|color balance
color|color contrast
color|color correction
color|color look up table
color|color zones
color|input color profile
color|lut 3D
color|monochrome
color|output color profile
color|unbreak input profile
color|velvia
color|vibrance
correction|chromatic aberrations
correction|contrast equalizer
correction|defringe
correction|denoise (bilateral filter)
correction|denoise (non-local means)
correction|denoise (profiled)
correction|dithering
correction|haze removal
correction|hot pixels
correction|lens correction
correction|liquify
correction|perspective correction
correction|raw denoise
correction|retouch
correction|rotate pixels
correction|scale pixels
correction|sharpen
correction|spot removal
effect|bloom
effect|color mapping
effect|colorize
effect|framing
effect|graduated density
effect|grain
effect|highpass
effect|lowlight vision
effect|lowpass
effect|soften
effect|split toning
effect|vignetting
effect|watermark

is that list complete?

**Comment by junkyardsparkle** [comment]
> is that list complete? In the source code I see module names like 'atrous' but I cannot assign them to a module visible in the darktable application

Here's a complete list of the name constants from the files in `iop` directory (includes deprecated and previously "hidden" modules):

source file | name constant
------------- | -------------------
ashift.c | "perspective correction"
atrous.c | "contrast equalizer"
basecurve.c | "base curve"
basicadj.c | "basic adjustments"
bilat.c | "local contrast"
bilateral.cc | "denoise bilateral filter"
bloom.c | "bloom"
borders.c | "framing"
channelmixer.c | "channel mixer"
clahe.c | "local contrast"
clipping.c | "crop and rotate"
colisa.c | "contrast brightness saturation"
colorbalance.c | "color balance"
colorchecker.c | "color look up table"
colorcontrast.c | "color contrast"
colorcorrection.c | "color correction"
colorin.c | "input color profile"
colorize.c | "colorize"
colormapping.c | "color mapping"
colorout.c | "output color profile"
colorreconstruction.c | "color reconstruction"
colortransfer.c | "color transfer"
colorzones.c | "color zones"
defringe.c | "defringe"
demosaic.c | "demosaic"
denoiseprofile.c | "denoise profiled"
dither.c | "dithering"
equalizer.c | "legacy equalizer"
exposure.c | "exposure"
filmic.c | "filmic"
filmicrgb.c | "filmic rgb"
finalscale.c | "scale into final size"
flip.c | "orientation"
gamma.c | "gamma"
globaltonemap.c | "global tonemap"
graduatednd.c | "graduated density"
grain.c | "grain"
hazeremoval.c | "haze removal"
highlights.c | "highlight reconstruction"
highpass.c | "highpass"
hotpixels.c | "hot pixels"
invert.c | "invert"
lens.cc | "lens correction"
levels.c | "levels"
liquify.c | "liquify"
lowlight.c | "lowlight vision"
lowpass.c | "lowpass"
lut3d.c | "lut 3D"
mask_manager.c | "mask manager"
monochrome.c | "monochrome"
nlmeans.c | "denoise non-local means"
overexposed.c | "overexposed"
profile_gamma.c | "unbreak input profile"
rawdenoise.c | "raw denoise"
rawoverexposed.c | "raw overexposed"
rawprepare.c | "raw black/white point"
relight.c | "fill light"
retouch.c | "retouch"
rgbcurve.c | "rgb curve"
rgblevels.c | "rgb levels"
rotatepixels.c | "rotate pixels"
scalepixels.c | "scale pixels"
shadhi.c | "shadows and highlights"
sharpen.c | "sharpen"
soften.c | "soften"
splittoning.c | "split toning"
spots.c | "spot removal"
temperature.c | "white balance"
tonecurve.c | "tone curve"
toneequal.c | "tone equalizer"
tonemap.cc | "tone mapping"
velvia.c | "velvia"
vibrance.c | "vibrance"
vignette.c | "vignetting"
watermark.c | "watermark"
zonesystem.c | "zone system"

**Comment by pphotography** [comment]
Thank you very much, I did a comparison between both lists. 

Not in my list are modules that are not accessible in the module list (right side of the screen):

- color transfer:  don't know what it is for
- gamma: always enabled in history
- legacy equalizer: deprecated
- local contrast (old): deprecated
- mask manager: always enabled
- overexposed: is this for the 'toggle over/under rexposed indication' button below the image?
- raw overexposed: is this for the 'toggle raw overexposed indication' button below the image?
- scale into final size: only used for export or zoom in screen display?

If my interpretations of these gaps are correct (excluding the open questions) I would add the two deprecated modules to my list.

btw: did not find 'chromatic aberrations' in your list.

**Comment by junkyardsparkle** [comment]
> btw: did not find 'chromatic aberrations' in your list.

Good catch! That file has the declaration formatted a little differently... it escaped my quick and dirty regex, but it's been added now.

> color transfer: don't know what it is for

Deprecated some time ago, don't know if it's worth mentioning for historical reasons (it's always possible that somebody has a collection where it's been used).

> overexposed: is this for the 'toggle over/under rexposed indication' button below the image?
> raw overexposed: is this for the 'toggle raw overexposed indication' button below the image?
> scale into final size: only used for export or zoom in screen display?

Yes, they're iops, but not really "modules" from a user perspective...

**Comment by pphotography** [comment]
Found some time to extend the table (edited my post above for better readibility of this thread)

In a first version I named base curve (successor: filmic rgb) and spot removal (successor: retouch) 'deprecated', but afterwards I had a problem with that. 
There are users who use these modules and don't want to change their behavior and the succerssors are more complex.
I think calling these modules 'deprecated' would not encourage beginners to get used to darktable, what do you think?

**Comment by junkyardsparkle** [comment]
I don't think the basecurve module itself can be considered "deprecated"; it serves the purpose of giving a default approximation of camera rendering curves. From everything I've seen in the way of feedback from "typical" users, this is a very important part of their first impression: "Ok, I import a file and get something that looks like a photo... so far, so good." Filmic RGB doesn't provide this "out of box experience", and in fact it won't get close to some of the stronger basecurves no matter how hard you try. Users will generally need some additional explanation as to why they might want to use filmic RGB instead (well, except for the ones who start using darktable after hearing about this module - they know what to do already).

I don't know if there are any good reasons for still using 'spot removal' or not. Probably the "legacy equalizer" and old version of "local contrast" don't need to be mentioned at all, they've been replaced for a while now, and the names would probably just cause confusion. There's some explanation of other proposed deprecations in #3013.

**Comment by MStraeten** [comment]
In my opinion it‘s more useful to prepare some user selectable preset favorite collections for beginners to have a good starting point for editing.

**Comment by GrahamByrnes** [comment]
> I don't think the basecurve module itself can be considered "deprecated"; it serves the purpose of giving a default approximation of camera rendering curves. 

It does rather more than that: it's a direct hands-on tone control which uses a different cognitive approach than filmic-RGB. Second thing is, I think basecurve and tonecurve are part of the same code (as you'd expect): if I could get by without basecurve, I would be *very* upset to lose tonecurve.

Note than some version of a tone curve is part of pretty much every photo software package, including even printer drivers like Canon Professional Print Layout or something like ICC Explorer. So even if one allows that the tone equaliser is "better"... (I would only allow "different" atm)... it will disorient anyone coming from a different program.

**Comment by johnny-bit** [comment]
With https://github.com/darktable-org/dtdocs we have https://darktable-org.github.io/dtdocs/module-reference/processing-modules/ which clearly mentions which module is deprecated and lists alternative

With #7024 every deprecated module has in-module deprecated message in edits using it and alternative mentioned
And generally #6915 IMO fixes this issue completely
