### ISSUE TITLE
timeline visible after disabling in settings

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#3873]
Bugs report just saying it crashes without filling most of the items
below and making no effort to help developpers to reproduce will be
closed without notice.

**Describe the bug**
Started darktable with new configuration directory.  Opened settings and set timeline to disabled.  Closed darktable, then restarted it.  Timeline was still visible.  Closed darktable and checked darktablerc file.  timeline_visible = TRUE and filmstrip_visible = FALSE.

**To Reproduce**
1. Start darktable with new configuration directory
2. Open settings and disable timeline.
3. Close darktable and restart it.  Notice timeline still visible.
4. Check darktablerc file and note timeline_visible = TRUE

**Expected behavior**
Timeline should not be visible

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 3.1.0+110~g3d980427f
 - OpenCL activated
 - Nvidia 390.116

**Additional context**
Edited the darktablerc file and set timelline_visible to FALSE.  Started darktable and it was visible again.  Stopped darktable and checked darktablerc and timeline_visible was back to TRUE.

**Comment by AlicVB** [comment]
oh, my bad, forgot that we can set them via settings...
That said, considering how easy it is now to hide/show them (and that they are remember per view/layout) I would vote for removing them completely from settings.
I'll take care
