### ISSUE TITLE
The 3.1 build fails on windows

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3878]
The build log is attached. Some files were deleted when got the updates.

Failure point
In file included from F:/msys64/home/chill/darktable/src/common/opencl.h:38,
                 from F:/msys64/home/chill/darktable/src/develop/imageop.h:37,
                 from F:/msys64/home/chill/darktable/src/develop/develop.h:30,
                 from F:/msys64/home/chill/darktable/src/control/jobs/develop_jobs.h:22,
                 from F:/msys64/home/chill/darktable/src/control/jobs.h:99,
                 from F:/msys64/home/chill/darktable/src/control/control.h:32,
                 from F:/msys64/home/chill/darktable/src/bauhaus/bauhaus.h:23,
                 from F:/msys64/home/chill/darktable/src/bauhaus/bauhaus.c:20:
F:/msys64/home/chill/darktable/src/common/dlopencl.h:27:10: fatal error: CL/cl.h: No such file or directory
   27 | #include <CL/cl.h>
      |          ^~~~~~~~~

[build.log](https://github.com/darktable-org/darktable/files/4003929/buil.log)

**Comment by chrik5** [comment]
I would recommend to subscribe  darktable-dev@list.darktable.org, because there was an annoucement about this yesterday:
> Am 26. Dezember 2019 21:25:52 MEZ  Pascal Obry wrote :

> Also, the OpenCL headers are now pulled from the upstream repository
instead of being copied and committed into dt. So with this in mind do
not forget to:

$ git submodule init
$ git submodule update

Next time you pull from dt repository.
