### ISSUE TITLE
Fix converting from PQ curves to linear

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#3880]
The following is copy&paste from #3749

@cryptomilk 
> The AVIF with PQ Rec2020 loads fine. It is completely black, but if I increase the exposure, then I start seeing the gradient.

@joedrago
> This means you are missing the luminance scaling part. PQ is implicitly a
> 10,000 nits container, whereas most other transfer functions are relative
> luminance (zero is black and one is "as bright as the monitor can go").
> After darktable converts to linear, it should multiply each channel by
> (10000/destLum), where the destination luminance is how bright you consider
> SRGB to be (or how bright you plan to display on the screen). Chrome always
> uses 80 when displaying PQ on SDR displays, Vantage lets you adjust it with
> the T keybind. assuming dark table handles overranging correctly
> (channels>1), everything should look really good.

@TurboGit 
> I see, this means that our color spaces are OK but when we are using them for whatever image on SDR display we need to adjust the final image by multiplying the 3 RGB channels by around 80. Is that correct?

@joedrago
> No, you don't multiply by 80, you scale by the ratio of "source luminance" to "destination luminance" when going between overranged linear and PQ. Here's Chrome's implementations of FromLinear and ToLinear, for example:
> 
> https://cs.chromium.org/chromium/src/ui/gfx/color_transform.cc?l=97
> https://cs.chromium.org/chromium/src/ui/gfx/color_transform.cc?l=177
> 
> The big question to ask yourself is "how bright, in nits, is (1.0, 1.0, 1.0, 1.0) when darktable is operating in rec2020 linear?" Chrome has locked in on 80 in their implementation (likely due to SRGB's semi-unused standard), macOS might think it is 100 nits, nominal HLG might prefer it was 203 nits, etc.
> 
> Does darktable offer a means to show how bright a pixel is already? If so, what math is it doing to calculate the value in nits? That should be the value you use in a ratio alongside 10000 when going to/from PQ.
> 

@joedrago 
> Scaling the channels like this only makes sense after converting to linear; scaling in PQ (or any other nonlinear TF) will do weird things.
> 
> In my opinion it should just be a part of the PQ->Linear and Linear->PQ conversions, assuming darktable's LinearRec2020 has a known luminance for (1.0,1.0,1.0) and does good things with overranging (channels > 1.0).

@TurboGit 
> Well sadly this is looking beyond my expertise :( Hopefully someone will shine in and help with the matter as to how best integrate this in dt.

**Comment by cryptomilk** [comment]
@parafin

**Comment by age1988** [comment]
I think that is possible to keep it simple for pq curve decoding and encoding.
`After darktable converts to linear, it should multiply each channel by
(10000/destLum)`
This could be hardcoded with (10000/100) because in this way we go from hdr compressed in 0-1 range to scene referred (actually 0-100 range for pq)

Decoding:
1)Pq to linear formula
2)linear * (10000/100)

Encoding
1a)scene referred=raw decoding and exposure for middle gray
1b)scene referred / (10000/100)
2)linear to pq formula

DestLum as well as peak source white are more usefull for tone mapping and display

**Comment by joedrago** [comment]
If dark table standardizes on (1.0, 1.0, 1.0) being 100 nits (instead of a configurable value), this is a perfectly reasonable choice. You can always add a configuration setting later and tweak this math.

**Comment by age1988** [comment]
Honestly i don't think it has to be configurable, probably you are talking about what itu documents describe as display scene but what is really important is to put middle gray at 0.18 for the scene referred workflow in darktable before filmic or others tonemappers.

Itu recommend to to put a 18% reflectance card at 20 nits (38% PQ code value) but this is a grading advice.

"For HDR, ITU is putting the grey card (18% reflectance at 38% PQ and 38%HLG) as a common point between the
two HDR systems and they are placing that point for output at  26 nits.  This is for the convenience
of making HLG and PQ compatible and having HLG show correctly on SDR sets.

So in essence, they are saying an HDR signal should be brighter.
Colorists doing content have already been lifting mid-levels into the 20nit range for HDR1000."

https://cml.news/g/cml-general/topic/hdr_and_pq_200/22737140?p=

The best choice to me is to assign 18 nits at 0.18 value and 100nits at 1.0 value.

**Comment by parafin** [comment]
Shouldn't HDR PQ content have some additional metadata like MasteringDisplay_Luminance? It can be used as 1.0 reference then.

**Comment by age1988** [comment]
The (1.0,1.0,1.0) value should be used for the sdr reference white and not the hdr peak white.

Itu bt.1886 recommends 100 nits for sdr  , so the value 1.0 represents 100nits in linear light, 2.0 value= 200nits and so on, with the middle grey correctly anchored at 0.18.

**Comment by parafin** [comment]
> The (1.0,1.0,1.0) value should be used for the sdr reference white and not the hdr peak white.

Could you explain why?

**Comment by age1988** [comment]
For the decoding part, the hdr image looked through a sdr display should be very similar to a sdr image but with only specular highlights clipped (load image-> hdr to linear-> linear to srgb).

Using the peak white to normalize the image in the 0-1 range results in a very dark image because grey is not anchored to 0.18.

For example for hdr10 1000nits, middle grey becomes 0.018 if we put 1000 nits at 1.0.

Now Darktable shows very dark image when it decodes PQ images
https://discuss.pixls.us/t/avif-8-10-12-bit-image-support-for-darktable/15014/10

That is because 10000nits is anchored at 1.0 and middle gray is 0.0018, i couldn't test it now but increasing  exposure (+6.643) after the conversion to a linear  working space, should gives the correct image in the scene referred light where middle grey is mapped to 0.18 and 100nits to 1.0.

The 6.643 value in the exposure module  is calculated with log2(10000nits/100nits)

**Comment by parafin** [comment]
Where exactly can files with PQ curve come from? What are the use-cases for these files to be used in darktable? Given that darktable is a photo editor, it's sometimes hard to fit video concepts in it, e.g. how one would go around processing an HDR file in darktable? It's not possible to displays values >1 currently in darktable, so basically HDR would be renderred in SDR mode. Also a lot of iop algorithms doesn't handle these values well. Usefulness of this is  quite limited...

I guess if 100 nits can be agreed on as SDR max (or better yet if it's defined in some standard), then it should be mapped to 1.0, I agree.

**Comment by joedrago** [comment]
I feel like you're conflating a working space with a storage format, in this context.

"Working in PQ" isn't necessarily an interesting goal, but *storing* in PQ is. PQ's severe curve gives you broad range of luminance (0-10000 nits) that curves along the Barten threshold (the curve defining where a human can distinguish changes in contrast/brightness). It's main goal is packing a large luminance range in 10bpc (or 12bpc) and apportioning appropriate amounts of range to the darker (more noticable) parts of the range.

When you're working with an HDR image, your _working space_ should probably be using some larger bit depth (16bpc or 32bpc), and some transfer function that makes sense for the kinds of operations you're doing (most likely linear, or in some cases, something SRGB-ish). Whether or not (1.0, 1.0, 1.0) is sdr white or maxLum is another choice. However, when *storing* a file, say for display on a web page or some other "let's make it as small as possible but keep the range" situation, being able to crush the image down to 10bpc is a huge win, and to get as low as 10bpc without introducing serious banding, you need PQ. 

PQ works great as a last-mile type of transfer function, IMO. It is great for on-disk storage, in-memory temp storage, or as a final destination for an opaque framebuffer (a swap chain, say), as R10G10B10A2 is very efficient in a graphics engine. Imagine it being a choice in Photoshop's "Export" feature, for example.

**Comment by cytrinox** [comment]
Is anyone working on this? I've hit the same problem with libheif when loading Canon HIF files into darktable. These are PQ Rec.2020 encoded and displayed too dark after import.
