### ISSUE TITLE
Direct naming for new module instances

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3881]
**Is your feature request related to a problem? Please describe.**
By default a new module instance get a sequential number in its name. To enter a speaking name I have to do two additional clicks:
- click on the 'multiple instance options' menu
- click on 'rename'

After that I can enter a name with the keyboard.

**Describe the solution you'd like**
After clicking on 'new instance' in the 'multiple instance options' menu I'd like to be directly in the data entry form for the module name.
This would save two clicks for every new module I add.

**Describe alternatives you've considered**
This solution would be a drawback for users who don't use module names. Therefore this feature should be a optional parameter in the global preferences.

**Comment by rabauke** [comment]
I think it would annoy many users if they are forced to enter an instance name. Nevertheless, I agree in that the default sequential numbering is not optimal. 

Another possible solution to assign more meaningful instance names to modules could consist in using  a preset's name as instance name. This means, when a preset is applied the preset name becomes the instance name.

**Comment by TurboGit** [comment]
I'm not sure using the preset name is a good idea. First one can change the settings after so letting the preset name for a module which does not use the preset values is misleading. A new instance is rarely used with a preset anyway. A new instance is often to cover part of the image with different settings (some masking or blending in different ways). So at the end automatically for me a number is what makes more sense.

And I certainly agree with you that it would be very annoying to have to enter a name each time.

**Comment by elstoc** [comment]
I've just submitted a PR (https://github.com/darktable-org/darktable/pull/4464) that will make this a bit less painful - so now you just have to shift-click on the module header to rename an instance.

**Comment by johnny-bit** [comment]
This is fixed in newer releases. Just click with ctrl on module name and have rename :) it's great workflow.
