### ISSUE TITLE
timezone selection for geotagging

### ISSUE THREAD

**Issue by igmerti** [darktable-org/darktable#3887]
Currently (ie dt 3.0.0) the combobox for camera's timezone selection within geotagging contains a really huge list.
In order to select the appropriate timezone one has to scroll down either by mouse or keyboard. There is no fast way by typing some letters, due to limitations of GTK (see https://gitlab.gnome.org/GNOME/gtk/issues/310).

I would like to propose some enhancements:

- For systems using zone.tab we could split the huge list of timezones into a hierarchical structure: first a list of regions and for each region a list of cities. This would result in two comboboxes: the first one for selection of region, and the second one for selection of city within the region. This would reduce the amount of scrolling significantly.

- For systems not using zone.tab (ie Windows) I currently haven’t a good proposal. I would like to leave it as it is with one combobox. Hence the GUI would be different a little bit.

What do you think about my thoughts?
Is it worth the effort?

**Comment by johnny-bit** [comment]
@phweyland - you've done quite a bit on module preferences and improved geotagging module... What do you think about this FR?

**Comment by phweyland** [comment]
If the combobox doesn't support completion we should be able to find some workaround (like in tagging, or even collect with filtering). This list is really really huge.
Also, we should probably bring back the timezone item into geotagging module to free up the file chooser dialog.
