### ISSUE TITLE
base curve is applied when turned off after a fresh install

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#3891]
**Describe the bug**
basecurve is auto applied after a fresh install and turning the auto-apply setting off.

Only happens after the first start. Does not happen again after the second start. The files that are opened in darkroom view during the first start still have the basecurve applied to them though.

**To Reproduce**
Steps to reproduce the behaviour:
1. remove xmp files from dir to be imported later
2. remove all files from ~/.config/darktable
3. start darktable
4. goto preferences -> core options: unset auto-apply basecurve and  close window
5. import a folder with images (or a single image)
6. open an image (any image) in darkroom view -> basecurve is applied
7. check preferences -> core options: auto-apply basecurve is not set
8. quit darktable and restart darktable -> problem is gone (except for those images you looked at in darkroom view the first time around, those have basecurve enabled).

**Expected behavior**
basecurve is not auto applied after disabling it.

**Platform (please complete the following information):**
 - OS: linux
- Distro: Debian 10.2 (buster)
 - Version: 3.1.0 (+192)
 - OpenCL: no

**Additional context**
Add any other context about the problem here, for example:
 - Can you reproduce with another dt version?
  Also happened yesterday with an earlier 3.1.0 version (+/- +80)
  This does not happen with the stable 3.0 (EDIT -> not 100% sure about this....)

**Comment by jade-nl** [comment]
Some time has passed and because I wasn't 100% the last time about this happening in 3.0 stable I decided to re-do the checks.

**Stable, 3.0.0**
This issue _does_ happen in the current stable 3.0 version. After disabling the base-curve in the preferences and then importing images it is already clear to see in lighttable view. Opening an image in darkroom view confirms this: base curve is used.

**Development 3.1.0+390~gfa0e8ee01**
Nothing has changed in the latest development version compared to the previous one (+192), issue is still present.

**Comment by Mark-64** [comment]
Confirmed in 3.1 git master as of today

**Comment by Mark-64** [comment]
Can't reproduce.
Please be aware that changing auto-apply basecurve in DT core options requires a restart (it is explained in the tooltip)

**Comment by jade-nl** [comment]
> (it is explained in the tooltip)

Sometimes you overlook the most obvious things....

Closing this issue.

**Comment by phweyland** [comment]
I've exactly the symmetric problem.
When enabling auto-apply, I don't get any on next import
