### ISSUE TITLE
180 degree image rotation (upside down) after migrating from darktable 2.6 to 3.0 (on portrait images)

### ISSUE THREAD

**Issue by mhoule418** [darktable-org/darktable#3892]
### **Problem**
I just install the 3.0.0 version (over the 2.6) and when I checked any converted photo directories, I noticed that all "portrait" format images are flipped upside down (180 degrees, heads pointing down). I am using the french darktable configuration. See my screenshot example of the . 

### **Context**
The original RAW image was taken "in portrait mode" (with battery grip, counterclock wise) with no automatic rotation (for my camera configuration).

ThenI used darktable version 2.6 and the "original" image was shown in "landscape format". I had to flip the image in the appropriate position, using 90 degrees counterclock wise. So after install of version 3.0.0, when checking all images, I flipped ones are showing upside down.
Please note that "landscape" format images are showing correctly (no problem).

In case you need my original file for testing, I will be able to find it at the directory _E:\Photos\Vacances\2018-08-25 - Gaspésie\IMGP6461.dng_ (on my computer).

Do not hesitate to contact me if you need more details.

![Upside down photos (after 3 0 version installed)](https://user-images.githubusercontent.com/59292061/71531725-fb674300-28bd-11ea-8738-55d48df88247.jpg)

**Comment by TurboGit** [comment]
Yes a know side effect of fixing the rotation in dt 3.0. In previous version the rotation was not correctly implemented, the new implementation is correct but this can affect some previous rotated images.
