### ISSUE TITLE
Sorting hierarchical tags should display child-tagged images by default

### ISSUE THREAD

**Issue by rivermont** [darktable-org/darktable#3895]
Clunky title but essentially, if I have the tags `thing|object` and `thing|object|tree`, I think all images tagged with `thing|object|tree` should show up when displaying `thing|object`-tagged images. This is currently not the case.

This can currently be done by searching for `thing|object%`, but it can get tedious and I feel like it should be the default behavior.

Another workaround is to manually tag all images with `thing|object|tree` also with `thing|object`, but this is obviously not a solution as it requires adding tags to lots of images.

I just feel like the hierarchical tagging should by nature display all child images, since that's what *hierarchical* tagging is. Open to discussion.

**Comment by phweyland** [comment]
Crtl-double-click acts as things|object|% and shift-double-click as things|object%.
