### ISSUE TITLE
Accels: case error

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#3896]
Version 3.0.0 Windows 10

In the accels window (ie opened with "h"), most of the single-letter short-cuts have the wrong case, ie ctrl-Z rather than ctrl-z for undo, W rather than w for preview etc.

**Comment by leclercj** [comment]
I don't think this is an error. Help is using upper case because this is the way letters are written on the keyboard.

**Comment by GrahamByrnes** [comment]
The keys are matked that way, but everyone understands that to get W you
use shift. In the case of the short cuts, you don't use shift. It's
unnecessarily confusing.

**Comment by aurelienpierre** [comment]
Shift is indicated explicitly if needed in shortcuts.

**Comment by GrahamByrnes** [comment]
So W means w and Shift-W means W?
Super clear.

**Comment by aurelienpierre** [comment]
It **is** clear. We are detailing sequences of key strokes, typography has no place here since you have no w on your keyboard and Shift is written when needed in the sequence.
