### ISSUE TITLE
“History stack” -> “paste…” pastes on wrong image

### ISSUE THREAD

**Issue by sboukortt** [darktable-org/darktable#3900]
If I copy the history stack of an image (say, `A`) and then select one or more other images to paste it on (let’s call them `B`), but my cursor happens to hover over yet another image (`C`) before I complete the pasting operation, then the history stack sometimes (not always) gets pasted onto `C` instead of `B`. (And then #3889 comes into play.)

**Comment by Mark-64** [comment]
Consider that cursor over an image is equivalent to selecting by clicking, in both lighttable and filmstrip. This is the normal behaviour of DT, not a bug, but I understand it can be confusing. You have to get used to that.

**Comment by sboukortt** [comment]
Oh wow, thanks for clarifying that. But having the cursor not placed over any image should revert back to the “clicked” selection, shouldn’t it? And that necessarily happens if I use the cursor to click the “paste…” button (which I do).

So, either darktable doesn’t properly detect that it happened, or I somehow manage to select the image again between the button press and the appearance of the dialog. I think both scenarios sound undesirable.

**Comment by sboukortt** [comment]
> This issue did not get any activity in the past 30 days and will be closed in 7 days if no update occurs. Please check if the master branch has fixed it since then.

Sadly not. When I click the “paste…” button, I must still wait for the dialog to appear before moving the cursor if I don’t want to accidentally select another image on my way there.
