### ISSUE TITLE
Darktable won't load Windows

### ISSUE THREAD

**Issue by Ruleof72** [darktable-org/darktable#3903]
I've downloaded/ installed the latest 3.0 version for Windows and when I start the app it doesn't load and I get an error message. I've attached the error file. Any help greatly appreciated!

[darktable_bt_UVEOD0.txt](https://github.com/darktable-org/darktable/files/4007379/darktable_bt_UVEOD0.txt)

**Comment by peterbud** [comment]
Refresh your video card driver.
Run `darktable-cltest.exe `as described here:  https://www.darktable.org/about/faq/#faq-windows-opencl
And if it still reports OpenCL problems, disable OpenCL as described here: https://www.darktable.org/usermanual/en/darktable_and_opencl_still_fubar.html

**Comment by Ruleof72** [comment]
I thought I had the most recent drivers but obviously not. Everything's working now. Thanks!

**Comment by peterbud** [comment]
@TurboGit : could you pls close this?

**Comment by TurboGit** [comment]
Closing.
