### ISSUE TITLE
DT Crash : Drawn gradient mask on image, then click uniformly circle icon next to drawn mask.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3918]
I have tried this on various modules so its not module related.
![image](https://user-images.githubusercontent.com/1119439/71551534-e995b500-2a0f-11ea-89a1-e53a79ff1159.png)

Select drawn mask and then I dropped a gradient mask on the image.
Then click the uniformly (circle icon) next to it, DT window just disappears.

Version : darktable-3.1.0+221~ga8695754f-win64 (local release build)

**Comment by chhil** [comment]
It crashes even when you do a drawn masks and select path tool. As soon as you click the image to put a point for the path it crashes.

**Comment by chhil** [comment]
I have reverted to 3.0 as the master build is currently not usable for me. 3.0 does not have the issue.

**Comment by upegelow** [comment]
This might be the same as #3907

**Comment by chhil** [comment]
@upegelow 
Built dt this morning that has the gradient fix.

It has got worse, 
On a clean dt with clean db, imported images with xmp.
Dropped gradient mask.
Tried to rotate it and it did not rotate, tried a couple of times and DT crashed.

Reopening DT did not work after that. Had to move the config dir out to treat is as clean.
Now by just dropping a gradient DT crashes.

**Comment by upegelow** [comment]
Am 30.12.19 um 04:16 schrieb Murtuza Chhil:
> @upegelow <https://github.com/upegelow>
> Built dt this morning that has the gradient fix.
> 
> It has got worse,
Please supply raw file plus xmp.

**Comment by chhil** [comment]
@upegelow , requested files are attached.

Darktable log file.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/4009625/darktable-log.txt)

Zip file contains raw+xmp. Remove the txt extension.
[P1044714.zip.txt](https://github.com/darktable-org/darktable/files/4009629/P1044714.zip.txt)

No module processing was done by me , just an import folder for images (no xmps were present), picked the image, went to exposure module, selected drawn mask, dropped gradient on image and it crashed.

**Comment by upegelow** [comment]
Thanks. Please check PR #3946.

**Comment by chhil** [comment]
One thing I forgot to mention.
When I drop the gradient , its supposed to be horizontal, but on drop it becomes vertical and then app dies.

**Comment by chhil** [comment]
@upegelow 
I currently am on the latest master, build 15 min ago.
Once your #3946 makes it to master I will build it and try again.

**Comment by upegelow** [comment]
Am 30.12.19 um 12:17 schrieb Murtuza Chhil:
> One thing I forgot to mention.
> When I drop the gradient , its supposed to be horizontal, but on drop it 
> becomes vertical and then app dies.

I can confirm that the gradient is gets flipped on creation. However, no 
crash here (with PR #3946).

**Comment by chhil** [comment]
On portrait pics the horizontal gradient drop turns vertical.
On landscape pics, the horizontal gradient stays horizontal.

Both cases crash DT.

**Comment by chhil** [comment]
@upegelow 
I copied your gradient.c into my src and built it.
Dropping didnt crash it, I rotated it, and it crashed.

**Comment by upegelow** [comment]
Am 30.12.19 um 12:58 schrieb Murtuza Chhil:
> @upegelow <https://github.com/upegelow>
> I copied your gradient.c into my src and built it.
> Dropping didnt crash it, I rotated it, and it crashed.
> 

This will be difficult to fix without a proper backtrace. The 'darktable 
-d all' output as supplied in a previous post will not help.

**Comment by chhil** [comment]
Not getting a backtrace. DT just disappears.

Potrait pic, vertical gradient, scroll to change size crash. Rotate to horizontal, it crashes.

Landscape, horizontal gradient scroll to change size crashes DT and changing it to vertical crashes it.

I wonder if the size of the gradient is the issue, it stretches way outside the image, maybe the bounds check fails there?
![image](https://user-images.githubusercontent.com/1119439/71581769-c876b680-2b2c-11ea-95fa-97872315bfd6.png)

**Comment by upegelow** [comment]
Am 30.12.19 um 13:20 schrieb Murtuza Chhil:
> Not getting a backtrace. DT just disappears.
> 
> I wonder if the size of the gradient is the issue, it stretches way 
> outside the image, maybe the bounds check fails there?

Should not be an issue. As said, no crashes here.

Can you do a git bisect? You said that 3.0.0 is fine but current master 
has the problem. It would help to find the single commit that makes 
things break for you.

**Comment by chhil** [comment]
After dropping gradient, if I click anything in DT the program crashes.

If I have a circular mask drop it change its size then click anywhere in DT (say a different module) it crashes. So I no longer feel its related to gradient.

This practically makes the current branch of DT not usable at all for me.

-----
Are you on windows or some other OS?
Not familiar with bisect but can try, so pull based on commit ids using bisect, build and test?
Build takes a lot of time for me so it will be a tedious process.

**Comment by upegelow** [comment]
I suspect that one of these commits might be the cause:

e569d43caa4a40f1defa9376135d31c5d9dde47b
2df89623ff55d4fbfaa7473c6296d369dbf4bd1d
2d7fab721f6934748f7f4370d9f325ae02fafadb
f1f5353e648c174623ddc74abef24e2eaaaa2bb8
396812ab678ec587a91e12a1578ad9d41ae8eb6d
93330135f3a19aba8cd66034426e1b04bbe7231c
aab3a4e58da75213cc207c5acf5951392ed77812
059c86e5ba19483c51aa2dcd2ae614daf558af4d
8c4d1a33d33b74030fb5120a9f2960878364e7de
e2e3615bce1a51bb372dd62ba4affac82e3db772
6b42190d12f242b2a9d0f2e7288198830ab184d7

**Comment by chhil** [comment]
darktable-3.1.0+258~g00c14d286-win64 has fixed the issue. The memory free call fix most likely fixed it.

**Comment by chhil** [comment]
> One thing I forgot to mention.
> When I drop the gradient , its supposed to be horizontal, but on drop it becomes vertical and then app dies.
Horizontal/vertical Fixed in darktable-3.1.0+269~gdd118d9a7-win64
