### ISSUE TITLE
Activating RGB curves turns image black

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3919]
Official DT Release 3.0

Opencl : On

Pipeline
![image](https://user-images.githubusercontent.com/1119439/71552445-96c5f880-2a23-11ea-8917-312797043189.png)

Just enabling rgb curve makes the image black.
Pipeline with rgb curve enabled
![image](https://user-images.githubusercontent.com/1119439/71552537-d93c0500-2a24-11ea-8bb2-40d761efe6de.png)

Opencl compiled kernels
cached_kernels_for_Capeverde_28415
cached_kernels_for_IntelRHDGraphics4600_2019154835

Results of darktable-cltest.exe
[darktable-cltest.out.txt](https://github.com/darktable-org/darktable/files/4007764/darktable-cltest.out.txt)

**Comment by chhil** [comment]
Image does not turn black with opencl deactivated.

**Comment by MStraeten** [comment]
I assume filmic rgb is using rgb power norm. Try to switch it to luminance or max rgb it will be fine. In this case https://github.com/darktable-org/darktable/pull/3890 is already merged, so you can try with current master

**Comment by chhil** [comment]
@MStraeten, it was already on luminance when it turned black. Max RGB also turns black.

Master, I am staying away from it right now, it crashes too often for me (logged various issues already)

**Comment by chhil** [comment]
Image does not turn black only on norm RGB.

**Comment by johnny-bit** [comment]
Due to #3890 beeing in master for quite some time and filmic rgb having strong opencl now we haven't had any new "blackout" reports I think this might be closed now...

Do you still have the issue on current release or current master? If not - Please close the issue :)

**Comment by matt-maguire** [comment]
I think I saw this a few times a while back (on 3.0.2?), but haven't seen it for a long time now...

**Comment by johnny-bit** [comment]
I think the issue is fixed. I tried to reproduce on current master and I know a person on windows using 3.2.1 and curves quite a bit and never had the issue. I think #3890 really fixed it.

@chhil - if you still have same issues with recent release and/or current master feel free to comment and I'll reopen.

**Comment by chhil** [comment]
Havent seen this lately.
