### ISSUE TITLE
git master build failing

### ISSUE THREAD

**Issue by RobbieAB** [darktable-org/darktable#3932]
git master build is failing with the following error:

`[ 78%] Building C object src/iop/CMakeFiles/watermark.dir/introspection_watermark.c.o
In file included from /home/robert/Code/darktable/build/src/iop/introspection_watermark.c:48:
/home/robert/Code/darktable/src/iop/watermark.c: In function ‘_watermark_get_svgdoc’:
/home/robert/Code/darktable/src/iop/watermark.c:863:3: error: unknown type name ‘dt_variables_params_t’
  863 |   dt_variables_params_t *params;
      |   ^~~~~~~~~~~~~~~~~~~~~
/home/robert/Code/darktable/src/iop/watermark.c:864:3: error: implicit declaration of function ‘dt_variables_params_init’ [-Werror=implicit-function-declaration]
  864 |   dt_variables_params_init(&params);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
/home/robert/Code/darktable/src/iop/watermark.c:865:9: error: request for member ‘filename’ in something not a structure or union
  865 |   params->filename = image->filename;
      |         ^~
/home/robert/Code/darktable/src/iop/watermark.c:866:9: error: request for member ‘jobcode’ in something not a structure or union
  866 |   params->jobcode = "watermark";
      |         ^~
/home/robert/Code/darktable/src/iop/watermark.c:867:9: error: request for member ‘sequence’ in something not a structure or union
  867 |   params->sequence = 0;
      |         ^~
/home/robert/Code/darktable/src/iop/watermark.c:868:9: error: request for member ‘imgid’ in something not a structure or union
  868 |   params->imgid = image->id;
      |         ^~
/home/robert/Code/darktable/src/iop/watermark.c:869:3: error: implicit declaration of function ‘dt_variables_set_tags_flags’ [-Werror=implicit-function-declaration]
  869 |   dt_variables_set_tags_flags(params, flags);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/robert/Code/darktable/src/iop/watermark.c:870:12: error: implicit declaration of function ‘dt_variables_expand’ [-Werror=implicit-function-declaration]
  870 |   svgdoc = dt_variables_expand(params, svgdata, FALSE);
      |            ^~~~~~~~~~~~~~~~~~~
/home/robert/Code/darktable/src/iop/watermark.c:870:10: error: assignment to ‘gchar *’ {aka ‘char *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  870 |   svgdoc = dt_variables_expand(params, svgdata, FALSE);
      |          ^
cc1: all warnings being treated as errors
make[2]: *** [src/iop/CMakeFiles/watermark.dir/build.make:68: src/iop/CMakeFiles/watermark.dir/introspection_watermark.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5473: src/iop/CMakeFiles/watermark.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`
**To Reproduce**
1. Checkout master
2. mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable/ .. && make
3. See error

**Expected behavior**
Build to complete without error

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: git master, commit 4585dba8d6a134ffc8b0743bf80207b6d0ce84f2
 - OS: Gentoo Linux
 - OpenCL activated: Not relevant
 - N/A

**Additional context**

**Comment by chhil** [comment]
https://github.com/darktable-org/darktable/issues/3878#issuecomment-569217668

**Comment by RobbieAB** [comment]
That bug is a different error.

**Comment by chhil** [comment]
The instructions still matter though.

**Comment by RobbieAB** [comment]
Same error with submodule openCL headers instead of system openCL headers.

Which is hardly surprising given the error is about a missing typedef in introspection and nothing to do with openCL at all.

**Comment by chhil** [comment]
Builds fine on my windows system under msys.

Cleaned contents of build dir and ran

#!/bin/bash
cd ~
cd darktable
git pull
git submodule update
cd build
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./releaseDT ../.
cmake --build .
cmake --build . --target install
cmake --build . --target package
