### ISSUE TITLE
Debug with Windows

### ISSUE THREAD

**Issue by rokondo** [darktable-org/darktable#3937]
**Describe the bug**
When enabling debug in windows with -d all only the help for commandline is posted but debug file is never written. At closing darktable crashes without response (waited 4h), so I hoped to find out why.

**To Reproduce**
Start darktable via command prompt or link with:
`"C:\Program Files\darktable\bin\darktable.exe" -d all`
Content of log file:
`========================================
version: darktable 3.0.0
start: 2019:12:29 16:24:03

usage: C:\Program Files\darktable\bin\darktable.exe [options] [IMG_1234.{RAW,..}|image_folder/]

options:

  --cachedir <user cache directory>
  --conf <key>=<value>
  --configdir <user config directory>
  -d {all,cache,camctl,camsupport,control,dev,fswatch,input,lighttable,
      lua, masks,memory,nan,opencl,perf,pwstorage,print,sql,ioporder}
  --datadir <data directory>
  --disable-opencl
  -h, --help, /?
  --library <library file>
  --localedir <locale directory>
  --luacmd <lua command>
  --moduledir <module directory>
  --noiseprofiles <noiseprofiles json file>
  -t <num openmp threads>
  --tmpdir <tmp directory>
  --version

  note: debug log and output will be written to this file:
        C:\Users\[username]\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt`

**Expected behavior**
Updated log file

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0rc2
 - OS: Windows 10
 - OpenCL: No
 - Intel(R) HD Graphics 520 + NVIDIA GeForce GPU

**Comment by Mark-64** [comment]
Can't reproduce. The log file works for me, I'm using it currently for lua debugging:
darktable -d lua

**Comment by chhil** [comment]
Doesnt work for me too on 3,0 release.

It creates a file but nothing gets written to it.

**Comment by chhil** [comment]
Ok I figured out the cause. I had setup dt to run as administrator. So no commandline flags worked while it ran as admin (would always prompt to allow). I turned of admin and it started logging.

**Comment by rokondo** [comment]
I already tried with admin in the past but what it solved now was:
- removing the darktable folder of in INetCache and in local profile 
- Setting up admin permission for "all users":
![image](https://user-images.githubusercontent.com/640866/71581231-8e91ba00-2b04-11ea-97a5-995575232201.png)

Thanks for your patient with me!

**Comment by chhil** [comment]
@rokondo 
I removed admin and also changed the default location of intecache to be in my temp folder so I dont run into admin issues.

![image](https://user-images.githubusercontent.com/1119439/71581950-d8db6100-2b2d-11ea-9466-2fa9e89e3ec5.png)
