### ISSUE TITLE
Import from camera, preserve sd card name

### ISSUE THREAD

**Issue by gciccarelli3** [darktable-org/darktable#3938]
On DT 2.6.0 and 3.0.0, I can connect and recognize the canon sl2/200d camera, and import photos cr2 and jpg to a target folder.  Before importing to the laptop, the dt preview panel shows the images in a /store_00020001/DCIM/100CANON/IMG_####.<cr2/jpg> convention.  However, upon import, they are renamed as <date of import YYYYMMDD>_####.<cr2/jpg> where the #### increments from 0 instead of preserving the image number on the sd card.  The sd card number is a global count number of all photos taken with the camera.  The DT number resets to 0 for each new import session.

Aside: This wouldn't be a problem at all because normally I "drag and drop" photos from the camera directly and import that folder to darktable.  However, in compiling dt 3 before it was available from a ppa, I somehow ruined my computer's ability (ubuntu 19.10) to recognize usb devices of any kind automatically.  Incredibly luckily, darktable alone, with this import method can still bring photos over to my computer, they just are named awkwardly.  I can manually mount usb sticks but cannot mount the camera as a usb storage device.

**Comment by Nilvus** [comment]
So, If I understand correctly, it's not an issue but how to use the import module. Automatic naming is configurable, so please read the manual for that (and use pixl.us forum eventually for help, this place is for bug report and feature request, thanks). Part of manuals to read :
- https://darktable.gitlab.io/doc/en/lighttable_panels.html#import
- https://darktable.gitlab.io/doc/en/session_options.html

**Comment by gciccarelli3** [comment]
Thank you for the speedy response.  Unfortunately, I had looked at those
sections prior to posting and was unsuccessful at changing the import
option.  pixl.us also registers as a 403 Forbidden so I can't post there
currently.

The "jobcode" number is "noname" by default, and if I change
to myfolder/$(FILE_NAME).$(FILE_EXTENSION) it keeps the same default name:
$(YEAR)$(MONTH)$(DAY)_$(FILE_NAME).$(FILE_EXTENSION) which evaluates to
20190101_####.<ext> but pre-pends literally the string of
$(YEAR)$(MONTH)$(DAY)_$(FILE_NAME).$(FILE_EXTENSION) to the folder path.

I could easily be missing something very obvious in the syntax?

**Comment by Nilvus** [comment]
jobcode is a tag you could choose if you use the $jobcode option in preferences session. Import settings are to be set on preferences dialog, in session options tab. It explain on manual links I supply. You didn't seems to read correctly these pages...

**Comment by gciccarelli3** [comment]
Perfect!  Thanks so much for your help.  That was the crucial sentence I
was missing: "You define the base directory for storing imported images and
the naming pattern of sub directories and individual images in the
preferences dialog (see Section 8.3, “Session options”)."

**Comment by Nilvus** [comment]
@gciccarelli3: good, so think about closing your issue to help community to see which ones remains to fix. Thanks.
