### ISSUE TITLE
slideshow freezes in dt 3.0 ubuntu ppa

### ISSUE THREAD

**Issue by insidebitrunner** [darktable-org/darktable#3939]
Slideshow freezes  machine when I have one image and I press the space key to start. Doc says esc key will stop slideshow, but that doesn't work In settings, shortcut key for starting and stopping is spacebar. after pressing spacebar, no key will work and have to reboot.

ubuntu 19.1 ubuntu ppa dt 3.0.0

**Comment by chhil** [comment]
See if this helps.

https://github.com/darktable-org/darktable/issues/3253

Makes suggestion 
>Can you try disabling the slidewhow high quality option in the preference and test again?

>Or make the delay between each image something like 10s and start again the experiment;

**Comment by insidebitrunner** [comment]
There is a tightly bound infinite loop somewhere in the slideshow code where a condition is never being met, so there is no chance to exit the code. That is where you need to focus attention.AndyOn Dec 30, 2019 12:35 AM, Murtuza Chhil <notifications@github.com> wrote:See if this helps.
#3253
Makes suggestion

Can you try disabling the slidewhow high quality option in the preference and test again?


Or make the delay between each image something like 10s and start again the experiment;

**Comment by TurboGit** [comment]
> There is a tightly bound infinite loop somewhere in the slideshow code where a condition is never being me

Where ? If you know point to the culprit code otherwise better not make assumption like that.

**Comment by insidebitrunner** [comment]
I was in IT for 25 years, so I know what the symptoms of an infinite loop are. However, I do not know C++. On Dec 30, 2019 3:37 AM, Pascal Obry <notifications@github.com> wrote:
There is a tightly bound infinite loop somewhere in the slideshow code where a condition is never being me

Where ? If you know point to the culprit code otherwise better not make assumption like that.

**Comment by magicgoose** [comment]
> ubuntu ppa dt 3.0.0

Which PPA? Official PPA hasn't been updated with dt 3.0.
If that's "ubuntuhandbook", then I'm not sure if it can be trusted...

**Comment by insidebitrunner** [comment]
Ubuntuhandbook, it is the only one I know of that will run ubuntu, and it is very buggy.On Jan 3, 2020 9:04 AM, magicgoose <notifications@github.com> wrote:
ubuntu ppa dt 3.0.0

Which PPA? Official PPA hasn't been updated with dt 3.0.
If that's "ubuntuhandbook", then I'm not sure if it can be trusted...
