### ISSUE TITLE
Brush mask seems to do always do a a light heal in retouch

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3941]
I can not draw the dark black line using the brush that would clone full strength in the 3.0

![image](https://user-images.githubusercontent.com/1119439/71574708-eeda2900-2b0f-11ea-8e2c-b5ff65abee7f.png)

The best I can get the brush black stroke to be is 
![image](https://user-images.githubusercontent.com/1119439/71575032-5e9ce380-2b11-11ea-844d-b72842131bf5.png)

I reinstalled a 2.7.x release and I could get dark black brush strokes to do a clean clone, now at best its a weak heal.

**Comment by chhil** [comment]
This one is with 3.0rc1works fine.
![image](https://user-images.githubusercontent.com/1119439/71577485-58f7cb80-2b1a-11ea-99b4-b9599e951e03.png)


In the current branch Basically there is some issue with the opacity, it shows 100% but it is not 100%.
Also when 100% is reached one can still scroll to make brush darker similarly at 0% one can still scroll to make it more transparent.

**Comment by jenshannoschwalm** [comment]
Could you check the darktablerc file for plugins/darkroom/masks/opacity. It should be set as default to 1.0, i found mine somehow changed to 0. That might be your problem too.

**Comment by chhil** [comment]
Had a clean install. Did not change any preferences so there was no darktablerc file.

When I change the preferences and exit DT, the darktable rc file got created, it had the 1.0. 
The brush painted black after this.

![image](https://user-images.githubusercontent.com/1119439/71609117-f9e29700-2bab-11ea-9c52-082532c29341.png)

**Comment by chhil** [comment]
No longer having an issue with  darktable-3.1.0+258~g00c14d286-win64 fixed .

Maybe its about the darktablerc not being present and using different defaults.

**Comment by TurboGit** [comment]
Should be fixed by #3969. Can you test?

**Comment by chhil** [comment]
I tested this earlier darktable-3.1.0+258~g00c14d286-win64 , it works.

Did a git pull the changes you made were already in my previously tested.
Any relation with the absent darktablerc when no prefrences are changed?

Current git pull had
 po/pl.po                 | 2 +-
 src/common/colorspaces.c | 5 ++---

So not going to test as its already tested and works.

**Comment by chhil** [comment]
Tried with and darktable-3.1.0+269~gdd118d9a7-win64 all works well.
