### ISSUE TITLE
Build warning in master for libavif

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3942]
This is probably related to the new AVIF support.

Building clean master get the following warning.

CMake Warning at src/CMakeLists.txt:324 (find_package):
  By not providing "Findlibavif.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libavif", but
  CMake did not find one.

  Could not find a package configuration file provided by "libavif"
  (requested version 0.5.2) with any of the following names:

    libavifConfig.cmake
    libavif-config.cmake

  Add the installation prefix of "libavif" to CMAKE_PREFIX_PATH or set
  "libavif_DIR" to a directory containing one of the above files.  If
  "libavif" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by chhil** [comment]
Fixed via https://github.com/darktable-org/darktable/pull/3947
