### ISSUE TITLE
Migration to 3.1 lost image rotation - for some images

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#3943]
_Preface_
Image collection in darktable since V1.4
Last edits in V2.4, after that migrated from Mint to debian sid, opened dt 2.6.3 for some image search and exports etc.
Then installed 3.1.0~git136.2a252d0b6 from OBS

_Describe the bug_
In my Kameras I have Image Rotation turned off.
So after import I have to turn all portrait images by 90° - I use rotate tool in lighttable for that by selecting multiple images and rotate them in the desired direction.
After searching through my collection with 3.1 installed I found many images (all of them portrait orientation) rotated by another 180° - so they are upside down.

_To Reproduce_
I did remove images, overwrite xmps from Version 2.4 backup and imported again - same issue with same photos.
I put sample images with V2.4 xmps [here](https://austausch.albicker.org/darktable/files/dt3-bug-3943.zip).

_Expected behavior_
I would expect the image rotation be preserved after upgrading to 3.x

_Additional context_
I checked for similarities in those affected images. Most of them are from Nikon DSLRs 700, 800, 850. To a significantly lower percentage images from Olympus E-P3 are affected also.

**Comment by bilddateien** [comment]
Is there already a ticket or fix for this I'm not aware of?

**Comment by TurboGit** [comment]
#3892 
#3545 
...

Did you really searched?

**Comment by bilddateien** [comment]
I put "rotation" in the search field and read all results - but those two entries were not shown (perhaps some filtering active(?)).
But thanks for clarification - and appologies for me making your job of "ticket master" even harder ...
