### ISSUE TITLE
metadata exportation details / exif

### ISSUE THREAD

**Issue by majobu** [darktable-org/darktable#3944]
With darktable 3.0.0 metadata exportation details are not working as expected. Variables of the manual do not work. 

For example, using $(EXIF_FOCAL_LENGTH) works, but $(EXIF_APERTURE) returns a value of 1.0.

**Comment by phweyland** [comment]
Could you please describe (or screenshot) your settings and attach the resulting data ? Thanks

**Comment by chhil** [comment]
The image information snapshot might be helpful to the dev to see what was expected.

**Comment by phweyland** [comment]
I confirm the issue using these variables for exported images metadata.
Currently these variables (all) return a string (text), which is convenient for file name or watermark text, but sometime not to fulfill metadata. 
I'll try to see if we can include in the PR #3951 some more control on this.

**Comment by junkyardsparkle** [comment]
Lua treats these as strings, too, I don't know if that might complicate things. I currently use a Lua script to fill several of these variables on import for images taken with old manual lenses. The new values work fine within darktable (matching in the lens correction module, for example), but they've never been exported by darktable. It would be great if they could be.

**Comment by johnny-bit** [comment]
This seems to be fixed by #3951 which is present in 3.0.1+, 3.2.1 and 3.4.x so closing :)

If it's not fixed, please reply and I'll reopen
