### ISSUE TITLE
Panasonic DC-TZ96 camera support

### ISSUE THREAD

**Issue by andijoos** [darktable-org/darktable#3948]
Please add support for Panasonic TZ96 to darktable. I just uploaded 4 raw files (one for each crop) to https://raw.pixls.us/.
Thank you!

**Comment by LebedevRI** [comment]
Thank you for contributing samples, will take a look.

**Comment by andijoos** [comment]
Great, thank you!

**Comment by andijoos** [comment]
Just out of curiosity.. I just installed darktable 3.0.1 and it seems that the support for TZ96 has not been added yet. Is there a plan, which release will contain the support?

**Comment by LebedevRI** [comment]
There was no(?) new camera support in 3.0.1 because no support was backported.
Please feel free to ask stable branch maintainer for more details.

**Comment by andijoos** [comment]
Ah, ok, thank you for the quick answer! I'm quite unfamiliar to this whole procedure, I didn't want to be pushy.
You guys are doing a great job!
