### ISSUE TITLE
Noise profiles for Panasonic Lumix DC-GH5

### ISSUE THREAD

**Issue by mjamado** [darktable-org/darktable#3950]
The profiling includes ISO 100, which is non-native to this camera (extended ISO). I really don't know if this matters or not, act accordingly.

[darktable-noiseprofile-20191230.tar.gz](https://github.com/darktable-org/darktable/files/4009839/darktable-noiseprofile-20191230.tar.gz)

**Comment by rawfiner** [comment]
The GH5 seems to have ISO values in between the one you provided (for example, ISO 1250). Please, profile for all ISO values, including the intermediate ones.
Apart of that, your profile is fine.

**Comment by mjamado** [comment]
Yes, it has. New set attached.

[darktable-noiseprofile-20200102.tar.gz](https://github.com/darktable-org/darktable/files/4017638/darktable-noiseprofile-20200102.tar.gz)

**Comment by mjamado** [comment]
Should I add the profile to the right place and make a pull request?

**Comment by rawfiner** [comment]
Sorry for the delay
I have just checked your pdf file, the profile is nice :-)
Yes, please add it to the noise profile file and make a pull request if you can! Thanks :)

**Comment by JosefR** [comment]
Thank you very much for integrating this. This improves working with the GH5 so much!
