### ISSUE TITLE
Nikon Z50

### ISSUE THREAD

**Issue by pandaadb** [darktable-org/darktable#3953]
Hi,

I have uploaded a number of 12bit and 14bit raw files from my Nikon Z50. The page then directed me here to open a camera support request. 

I hope the pictures are fit for the purpose. The only settings for raw that are on my Z50 are 12 and 14 bit. I don't seem to have influence over compression. 

Please let me know if there is anything else needed or I can help with other/better images. 

Thanks!

**Comment by LebedevRI** [comment]
Thank you for the samples.
There is something weird going on with them (though it is nikon, so i'm not surprized),
in second uploaded set all samples are 12bit. There was one (?) 14bit sample in first set.
I guess it will do though..

**Comment by pandaadb** [comment]
Would you like me to take a few other ones and reupload?

**Comment by LebedevRI** [comment]
If you can ensure that both 12bit and 14bit samples have the same image content, and that they are actually 12bit and 14bit - sure why not.
(in exiv2 output, look for `Exif.SubImage2.BitsPerSample`)

**Comment by pandaadb** [comment]
Great thank you, I wasn't aware of the command. (I must have clicked on the wrong files, I can see a few extra 14bit ones that I do have). 

When saying "same image content", do you mean exactly the same content (as in using a tripod) or just hand held taking roughly the same picture? I don't have a tripod which is why I ask. 

Today is a very grey day here, so the pictures won't be very bright. The website mentioned that the images must be "properly exposed" and I am not sure if that requires good light. My apologise for this, I have had this camera for only a week and am just beginning to play with all of these tools :) 

Thanks!

**Comment by pandaadb** [comment]
Hi again,

I looked through my pictures and found 2 pairs that I think are suitable. I used your command to determine that they are indeed 12 and 14 bit (and I hope I got that right this time) 

The pairs are: 

> DSC_0450.NEF (14 bit)
> DSC_0441.NEF (12 bit)

These are hopefully similarly enough, both just a bit of grass. And: 

> DSC_0456.NEF  (14 bit)
> DSC_0457.NEF  (12 bit)

Both are roughly the same graffiti. 

I can't see them yet in the browsable directory, but you might have a different way to access these files. I'm still happy to go outside and shoot some new images if you have more or different requirements.

In any case, if I can help, please let me know :) 

Artur

**Comment by LebedevRI** [comment]
Thank you, those will do.

**Comment by karolherbst** [comment]
Built darktable from the master branch, but I still get those errors:

```
RawSpeed:Unable to find camera in database: 'NIKON CORPORATION' 'NIKON Z 50' '14bit-compressed'
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (20200103_0001.NEF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 171: Camera 'NIKON CORPORATION' 'NIKON Z 50', mode '14bit-compressed' not supported, and not allowed to guess. Sorry.
RawSpeed:Unable to find camera in database: 'NIKON CORPORATION' 'NIKON Z 50' '14bit-compressed'
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (20200103_0002.NEF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 171: Camera 'NIKON CORPORATION' 'NIKON Z 50', mode '14bit-compressed' not supported, and not allowed to guess. Sorry.
```

**Comment by LebedevRI** [comment]
Yes, because as the bug status states, i didn't propagate this into darktable yet.
If you want to do it locally, you need to checkout `develop` branch in rawspeed submodule.

**Comment by karolherbst** [comment]
ohh, I thought that already happened as "branch = develop" was configured in .gitmodules, but for some reasons that didn't work out...

anyway, with the develop branch it works. Thanks!

**Comment by bromios** [comment]
Hi,
I have the same problem with my Nikon Z50 and darktable.
When this fix will be updated in the stable ppa?

Thanks in advance.

**Comment by febadev** [comment]
Hi, it seems like this problem still persists - at least with .nef files of my new Nikon Z 50.
I just got a brand new Nikon Z 50 and tried to edit the photos with darktable 3.0.2 on Manjaro. Also tried with a fresh darktable install on Win10. In both cases the same error: `Nikon Z 50' color matix not found!
The latest version claims _Base Support for Nikon Z 50 (12bit-compressed, 14bit-compressed)_.

Here a sample image from today,14 bit.
[DSC_0293.NEF.zip](https://github.com/darktable-org/darktable/files/5043511/DSC_0293.NEF.zip)
(I can provide more if necessary)

How can this be fixed?

Thanks in advance.
Felix

**Comment by matt-maguire** [comment]
Hi Felix,

Nikon Z50 is not supported in the Darktable release 3.0.x line. It is however supported in the 3.2.1 release, which is due to be formally released in the next few days I believe.

**Comment by febadev** [comment]
Hi Matt, thanks for clearing this up! I'm looking forward to the update then. :+1:
