### ISSUE TITLE
Importing folder of xmps generated by 3.1.x into 3.1.x causes DT to crash after few images get loaded.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3954]
Folder with raw+xmp
Import folder (with or without load from xmp check box checked in preferences)
DT crashes after few images, it disappears.

Removed xmp and tried it again same problem DT disappears after few images.

Removed config/database , this time it worked.

**Comment by aurelienpierre** [comment]
Your report is not in a shape to be used for debugging. Please [learn how to properly reports bugs](https://github.com/darktable-org/darktable/wiki/Reporting-bugs-and-issues). This issue will be closed in 2 weeks if it has not been improved according to the guidelines.
