### ISSUE TITLE
Resize on export: can cause artifacts

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#3956]
**Describe the bug**

Under these conditions I get artifacts in my output result:

* the picture contains pure, clipped white, (or is processed white enough)
* the picture needs to be resized down
* output is 8-bit format, PNG or JPEG
* "high quality resampling" is **enabled** 

The artifacts will only appear on the white, clipped portions of the image.

**Expected behavior**

High quality resampling should work the same as "non"-high quality resampling. 16-bit output formats are also fine, tested PNG 16-bit and it's okay.

**Screenshots**

In the following image is the same exact image exported out to PNG 8 bit with and without HQ resize. The top left is without HQ resize, the bottom left is with HQ resize. On the right side I applied some heavy curve work (in gimp, using the exported files as source) on duplicated images to highlight the problem.

![resize-errors](https://user-images.githubusercontent.com/667146/71593651-91f56780-2b3d-11ea-88ce-ee1a2a5f8b6f.png)

**Platform (please complete the following information):**
 - Darktable Version: has been a problem for a long time. Witnessed with versions  2.6.2, 3.0.0 at least.
 - OS: gentoo linux (darktable comes from portage 'master')
 - opencl ENABLED
 - nvidia, blob 435.21

**Additional context**

**Comment by aurelienpierre** [comment]
Please list the enabled modules.

**Comment by progo** [comment]
I narrowed it down to: 

* channel mixer
* crop and rotate
* exposure (required to blow things into white)

Channel mixer is the obvious suspect here. But I can't just disable it and get entirely blown white image because of lack of white balance adjustment and whatnot, I'm getting a cyan image. The original problem only presents in all-white areas of output image. So I enabled base curve instead and it blew the pixels back to pure white. But the problem is not present this time. 

* base curve 
* crop and rotate
* exposure

**Comment by aurelienpierre** [comment]
Out of curiosity, what if you enable/disable LittleCMS2 in preferences ? Also, does it happen with JPEG outputs ?

By the way, PNG is not intended for photographs (logo and graphics only).

**Comment by progo** [comment]
To clarify, this problem only happens with 8-bit image outputs.

* 8-bit JPEG: occurs
* 8-bit PNG: occurs
* 16-bit PNG: doesn't occur

"Always use littlecms2 to apply output color profile" was checked OFF. I checked it ON. It has no effect on the original problem, has minor effects on the picture otherwise.
