### ISSUE TITLE
Please add white balance presets for Panasonic TZ-96

### ISSUE THREAD

**Issue by andijoos** [darktable-org/darktable#3958]
I followed this instruction: https://redmine.darktable.org/projects/darktable/wiki/White_balance_presets
Hope, this helps you. I also copied the names of the presets as comment in the file.

  /* Panasonic DC-TZ96 Firmware Version 1.0 */
  /* Fine Weather, Cloudy, Shade, Tungesten (Incandescent), Flash, D55, ISO Studio Tungsten */
  
  { "Panasonic", "DC-TZ96", 1, 0, { 2.1328125, 1, 1.79296875, 0 } },
  { "Panasonic", "DC-TZ96", 2, 0, { 2.30859375, 1, 1.65625, 0 } },
  { "Panasonic", "DC-TZ96", 3, 0, { 2.4609375, 1, 1.54296875, 0 } },
  { "Panasonic", "DC-TZ96", 4, 0, { 1.4765625, 1, 2.55859375, 0 } },
  { "Panasonic", "DC-TZ96", 5, 0, { 2.3203125, 1, 1.56640625, 0 } },
  { "Panasonic", "DC-TZ96", 6, 0, { 1.9765625, 1, 1.90234375, 0 } },
  { "Panasonic", "DC-TZ96", 7, 0, { 1.4765625, 1, 2.55859375, 0 } },

[white_balance.txt](https://github.com/darktable-org/darktable/files/4010703/white_balance.txt)

**Comment by TurboGit** [comment]
Added, but the the third column was wrong we need names. I suppose the Redmine instruction are obsolete.
