### ISSUE TITLE
Since #3898, right panel in lighttable needs a larger minimum width without horizontal slider to see all panel

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#3959]
@phweyland: first thanks to this new feature on selected images on right panel of lighttable. Tabs is a better option. Anyway, since this PR #3898, it seems that some margins or paddings are hardcoded. These tabs have bad consequences on width panel size. The panel needs now a bigger width to see all things from left to right. I've searched with CSS how to adjust that but didn't any padding or margin to improve that.

This new notebook needs to be more flexible on horizontal space taking. CSS is here to adjust margins and paddings. So, is it possible to improve that ore am I missing something else ? Hope I'm clear.

**Comment by phweyland** [comment]
Not sure to understand the issue. Could you show some example ?
About the code of this notebook there nothing hard coded as far as I can see ... The change compared to before is that the grids are inside the notebook. May that disturb things ?

**Comment by Nilvus** [comment]
Maybe images will help:

Right panel size with 350px default size and without selected images module activated:
![350size](https://user-images.githubusercontent.com/45535283/71626192-3a620500-2bec-11ea-9640-e86d74785735.png)

Same right panel size with selected images module activated:
![350sizetabs](https://user-images.githubusercontent.com/45535283/71626209-49e14e00-2bec-11ea-908d-671dc2ec44ee.png)

As you can see, just activate this module and show notebook content, a scrollbar appear on the bottom panel. The notebook need to be reduced automatically (space is here to do that). And for example, notebooks on darkroom modules like tone equalizer or rotate and crop didn't use so much horizontal space and they have 3 tabs. See below, with always same size:
![350sizete](https://user-images.githubusercontent.com/45535283/71626350-ffac9c80-2bec-11ea-8d71-69956e50de26.png)

**Comment by phweyland** [comment]
For height I've noticed the module takes the biggest one. Would that be the same for width? Could show the Metadata tab opened in the same context?

**Comment by Nilvus** [comment]
Maybe, I don't know. Anyway, On both modules, there's some space that could be used to reduce panel without scrollbar. Below Metadata tab (in french) in same context. Doesn't change, same thing as first tab:

![350metadata](https://user-images.githubusercontent.com/45535283/71627235-a85cfb00-2bf1-11ea-9261-16f73c5afaa8.png)

**Comment by Nilvus** [comment]
Just after posting this answer, I just think about text length, so tested english one (generally shorter text than french) and can confirm that the problem is not here in english (or only if I reduce quite a lot the panel). This issue only appear for some languages with longer text.

@TurboGit and @phweyland: actually I don't have any idea on how to improve that but I really think this has to be improved. Any other module in french with notebook is ok, except this one.

**Comment by TurboGit** [comment]
@Nilvus  : Should be fixed.

**Comment by Nilvus** [comment]
> @Nilvus : Should be fixed.

Indeed. Just great now and couldn't be better. The scrollbar is only here when there's no margin between text, so just as it should. Thanks for this quick fix.
And your fix is already the 265th commit since 3.0.0 release, just a week ago. DT developers are just furious !
