### ISSUE TITLE
UI: quick access to favourites presets in random order

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#3961]
Hi,
in the "quick access to favourite modules presets"
![Cattura13](https://user-images.githubusercontent.com/43290988/71599727-5615ce80-2b4c-11ea-9642-c6ec23a15d86.JPG)

the modules seem to be in random order. It is difficult to find a specific module.
I suggest alphabetical order.

**Comment by MStraeten** [comment]
The order is based on the pixel pipe, so it's quite easy to learn a decent workflow

**Comment by Mark-64** [comment]
I see.
I suspected that, but I didn't realize that in the panels modules are ordered from bottom to top, while in the favourite preset it's the contrary (maybe the order shoud be reversed here).

**Comment by Mark-64** [comment]
Do you think it's worth to reverse the order, modules that come first in the pipeline to be at the bottom, in order to be more consistent with the rest of the UI ?
I could do a PR, but I don't want to lose my time
