### ISSUE TITLE
Ignore JPG still imports JPGs from camera

### ISSUE THREAD

**Issue by Eadword** [darktable-org/darktable#3966]
**Describe the bug**

When you import a batch of photos off a camera or SD card, there is an option to ignore JPG files to reduce redundancy with RAWs, however, Darktable still imports the RAW files even when this option is checked, although it will not load them to the lighttable after.

**To Reproduce**

Have photos on camera formatted SD card which include the RAW and JPG files, import with darktable, and you should see JPGs in the destination filesystem.

**Expected behavior**

When "Ignore JPGs" is enabled, only the RAW files should be imported.

How situations where there is a JPG and no RAW file should be handled is outside the scope of this issue.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Manjaro Linux
 - OpenCL Active
 - GTX 1070, driver: 440.44

**Comment by codingdave** [comment]
Hi @Eadword 

`When you import a batch of photos off a camera or SD card, there is an option to ignore JPG files to reduce redundancy with RAWs, however, Darktable still imports the RAW files even when this option is checked, although it will not load them to the lighttable after.`

I guess you are mixing RAW and JPG here. Do you mean that if you have checked the checkbox "ignore JPEG files" still JPG files are imported? Please clarify.

`How situations where there is a JPG and no RAW file should be handled is outside the scope of this issue.`
Well, a checkbox with the name "ignore JPEG files" will have an effect on all JPGs during import, not only JPGs that have a matching raw file (come in pairs). Detecting images that don't come in pairs would be a new feature.

**Comment by Eadword** [comment]
> I guess you are mixing RAW and JPG here. Do you mean that if you have checked the checkbox "ignore JPEG files" still JPG files are imported? 

Sort of. They are imported to the filesystem, but not to the darktable library.
