### ISSUE TITLE
Date used for naming on import should be same as metadata

### ISSUE THREAD

**Issue by Eadword** [darktable-org/darktable#3967]
**Describe the bug**

When you import a batch of photos which all represent one "job" but were shot over multiple days, the date codes used for each file is the day it was imported, not the day the photo was taken.
**To Reproduce**

1. Have a camera formatted SD card with photos from multiple days
2. Under settings -> session options, set "file naming pattern" to `$(YEAR)$(MONTH)$(DAY)_$(SEQUENCE).$(FILE_EXTENSION)`
3. Select "import from camera" in the lighttable
4. Select photos to import
5. Note that files taken on later days will still have the same date code as earlier photos

**Expected behavior**

Each file should be given the same date code as is in its metadata.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Manjaro Linux

**Comment by Nilvus** [comment]
Hi, it's not an issue but just the default setting that add the date import.
This can be change, so nothing to solve here as this part is only for issues needed to find code to improve. Automatic naming is configurable, so please read the manual for that (and use pixl.us forum eventually for help, this place is for bug report and feature request, thanks). It's always good to read the manual (yes, it takes some time but save some more after).

Part of manuals to read for what you ask:

    https://darktable.gitlab.io/doc/en/lighttable_panels.html#import
    https://darktable.gitlab.io/doc/en/session_options.html

To be simple, just add EXIF_ on each part of date. For example $(YEAR) become $(EXIF_YEAR), etc.

Think about closing this issue, thanks.

**Comment by gaga9999** [comment]
I secont that $sequence should not be added to the filename as it is an alteration of the original files, which is the whole point of the import process to not alter the original files. 
Also in my version (4.2.1) it imports everything in to a folder named after the sequence day and it does not add any subdirs according to exif creation date, although selected.

**Comment by Nilvus** [comment]
It's not _exif but EXIF_. Just read the manual, you will variables you could use. I use EXIF_* variables since years.
Again read manual, do not make statement on what you don't know.

You can remove $sequence if you want. It's just as simple as... remove it.

For example, see what I use on my side since years for import rules:
![image](https://github.com/darktable-org/darktable/assets/45535283/e22cfc19-9988-4d9a-b3a5-e84ecc9ac633)
