### ISSUE TITLE
Crop and rotate: merge 'main' and 'guides' tabs together

### ISSUE THREAD

**Issue by jakubfi** [darktable-org/darktable#3968]
NOTE: Opening this issue as a result of a short discussion in https://github.com/darktable-org/darktable/pull/3601#issuecomment-569753233 so people can see it and voice their opinion.

In #3601 crop and rotate module got new sliders for adjusting the crop. Those were put into a separate tab, which is fine. But apart from that, guides-related controls were separated and put into 'guides' tab.

I worked a bit with the tabbed version of "crop and rotate" and I think separating the guides controls from the main tab was not a good idea. Margins - sure, those are perfect for a separate tab. But main and guides in my oppinion should be merged back together.

How I see it:
- Selecting guides is one of the most important features of the cropping module (this is what helps with the composition) and should be always readily available.
- There are some specific workflows which rely on frequent switching between guides:
    - image straightening (by eye): rotation is on the main tab, but switching to helpful  'metering' or 'grid' guides require changing tabs,
    - recomposition when changing image aspect: again - aspect is on the main tab.
- The amount of vertical space saved in modules area is negligible in case of most guides (with the exception of 'grid' guides, which are rather rarely used, I would assume).

In ~90% of my usage cases I personally find it irritating to have guides on a separate tab.

@TurboGit argues that current solution helps with the issue of the module changing its size, which is a valid point. But this could be remedied by reducing the number of sliders for the most problematic 'grid' guides.

**Comment by Nilvus** [comment]
I totally agree with you @jakubfi. I didn't follow this #3601 PR but when opening the new tabs mode for this module, I was quite disappointed and I really don't like it. Even more, I find it harder and more confusing to use. I also use especially first tab and third one (guides) together. Switching between them (and separated by another tab) is quite longer and tedious.

Main and guides needs to be together and be merged in one tab. So having a main tab with margins options in it and we could keep the margins tabs separately.

**Comment by TurboGit** [comment]
Ok, let's move guides back to the main tab then.
