### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by Odud** [darktable-org/darktable#3970]
In Export Selected for Google Photos clicking on Login produces web page page to select Google account and then the attached error screen appears. There are no links or buttons to press that will allow me to override this.

![Capture](https://user-images.githubusercontent.com/15649511/71620256-cc541880-2bc0-11ea-9a4d-005b1d4e1e6e.PNG)

DT 3.0.0 on Windows 10

**Comment by Nilvus** [comment]
Duplicates #3475
