### ISSUE TITLE
Reject tag does not toggle anymore as it's only rejecting.

### ISSUE THREAD

**Issue by homer3018** [darktable-org/darktable#3972]
**Describe the bug**
Hitting the R keystroke or the dedicated icon on a hovered/selected picture will first mark it as discarded with the message "rejecting 1 image". However hitting the R keystroke once more (or using the dedicated icon) will not revert that state, and will also display the same message. 
Version 3.0.0 is fine with that (and does not display any message whatsoever).

**To Reproduce**
1. Go to the lighttable
2. Click on any picture you like (or dislike in this case)
3. Hit the R keystroke or use the dedicated icon to mark it as discarded
4. See that it's been marked correctly
5. Hit R once more or use the dedicated icon
6. See that the image is still marked as discarded

**Expected behavior**
The discarded state should be a toggle or a flag, not an irreversible state.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+263 - 349fe88b419bbc7d87ee50382e8edac69a8a553f
 - OS: MacOS 10.15
 - OpenCL activated

**Additional context**
3.0.0 does not exhibit this behaviour and does not display any message upon mark an image as discarded.

**Comment by phweyland** [comment]
probably linked to new copy metadata feature. I'll check this.
