### ISSUE TITLE
Drop-down lists appear on wrong monitor

### ISSUE THREAD

**Issue by sboukortt** [darktable-org/darktable#3974]
I am using darktable 3.0.0 on a Windows machine with two monitors. The darktable window is on the secondary monitor, but when I click on a drop-down button (for example: lighttable -> collect images -> film roll / folders / etc.), the menu appears in the corresponding location of the other monitor, often without any text.

**Comment by sboukortt** [comment]
@GitHub bot: I cannot easily test now but I have not seen a commit on the master branch that is susceptible to have fixed this.

**Comment by sboukortt** [comment]
As an aside, isn’t 30/7 days perhaps a bit too quick for closing inactive bugs?

**Comment by johnny-bit** [comment]
Maybe. The rule is now 30 days for reply and 1 year for autoclose. This assumes that devs respond.

That being said - My wife uses darktable on windows with 2 monitor setup and while she reports every little issue she has, I've never heard nor seen reports about menu being on separate monitor or menu without a text (or both). I haven't had that happen to me on Linux at all...

Can you re-check if you still have the issue?

**Comment by sboukortt** [comment]
Right now, not easily. Maybe we can tentatively close this, and I’ll reply here if I encounter the issue again?

**Comment by johnny-bit** [comment]
Sure! I'll reopen once you confirm the issue is still present!
