### ISSUE TITLE
tethering live view: detect focus and highlight it

### ISSUE THREAD

**Issue by Baranowski** [darktable-org/darktable#3976]
**Is your feature request related to a problem? Please describe.**

Focus support in DT Tethering is somewhat lacking, as indicated in https://github.com/darktable-org/darktable/issues/3899

**Describe the solution you'd like**

1. User plugs in the camera and switches to the Tethering view
2. User turns on Live View
3. User adjusts focus by physically rotating the focus ring on the lens
4. DT detects which areas are in focus and highlights them in Live View, just like "zoom with focus detection" does in the lighttable view.

**Alternatives**

* Support autofocus in DT Tethering. This feature and the one proposed have some overlap in the issues they solve, but they are significantly different. Autofocus would be very straightforward to use with modern lenses/bodies but would give the user little control. Focus detection would require more work from the user whenever changing the scene but would offer more control and make the cheap manual lenses much more usable.

**Comment by thisnamewasnottaken** [comment]
The NIKON specific manual focus drive noted by @Baranowski in https://github.com/darktable-org/darktable/issues/3899 was first raised in 2017 on [redmine #1170](https://redmine.darktable.org/issues/11710
) The ticket indicates that for Nikon at the very least manual focus drive is possible with gphoto.

**Comment by johnny-bit** [comment]
The tethering&focus controls for nikon were recently merged, so now at least canon&nikon have AF drive in tethering mode. Still - focus detection would be great to have (based on focus-peaking currently avail in lighttable/darkroom views)

**Comment by johnny-bit** [comment]
@aurelienpierre - i'm setting 3.8 milestone for this, hoping you'll have time to look into it :)

**Comment by thisnamewasnottaken** [comment]
Hello? Is it me you are looking for? 
Are we still expecting this sometime soon?
