### ISSUE TITLE
Problem compiling 3.0.0 on MacOS High Sierra 

### ISSUE THREAD

**Issue by rcarlitz** [darktable-org/darktable#3977]
**Describe the bug**

Compilation fails with error messages:

In file included from /Users/bob/Desktop/darktable-3.0.0/build/src/iop/introspection_toneequal.c:77:
/Users/bob/Desktop/darktable-3.0.0/src/iop/toneequal.c:1141:5: error: variable 'out' must have explicitly specified data sharing attributes
    out[i] = pixel_correction(centers_params[i], factors, sigma);
    ^~~
/Users/bob/Desktop/darktable-3.0.0/src/iop/toneequal.c:1141:50: error: variable 'factors' must have explicitly specified data sharing attributes
    out[i] = pixel_correction(centers_params[i], factors, sigma);
    .......................................................................^~~~~~~

**To Reproduce**

1. Follow easy build instructions for README.md in darktable-3.0.0
2. Compilation proceeds with no problems until

[ 53%] Building C object src/iop/CMakeFiles/toneequal.dir/introspection_toneequal.c.o

**Expected behavior**

Compilation should have finished, followed by installation.

**Platform (please complete the following information):**
 - Darktable Version:  3.0.0
 - OS:  MacOS 10.13.6
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- The C compiler identification is AppleClang 10.0.0.10001145

**Additional context**

Similar problem with darktable 2.6.3:

[ 85%] Building C object src/iop/CMakeFiles/spots.dir/introspection_spots.c.o
In file included from /Users/bob/Desktop/darktable-2.6.3/build/src/iop/introspection_spots.c:18:
/Users/bob/Desktop/darktable-2.6.3/src/iop/spots.c:382:24: error: variable 'in' must have explicitly specified data sharing attributes
    const float *inb = in + (size_t)ch * roi_in->width * (k + roi_out->y - roi_in->y)
    .............................^~
/Users/bob/Desktop/darktable-2.6.3/src/iop/spots.c:381:19: error: variable 'out' must have explicitly specified data sharing attributes
    float *outb = out + (size_t)ch * k * roi_out->width;
    .....................^~~

**Comment by MStraeten** [comment]
since you mentioned README.md: Ae you aware of https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt ? 
With catalina and also mojave everything was fine using these instructions

**Comment by parafin** [comment]
Probably it's due to a difference in compiler versions. Latest Xcode works only on macOS 10.14-10.15, so macOS 10.13 has older toolchain. I'm only testing the build with one version of Xcode (the one I have installed at any given moment).

**Comment by rcarlitz** [comment]
Thanks, Martin, for the link to the very useful and detailed BUILD.txt instructions. I will try them out after taking parafin's advice and upgrading to macOS 10.14 or 10.15. 

My interest in building darktable from source was to obtain a version that uses Lensfun 0.3.95. The current package on darktable.org appears to use Lensfun 0.3.2, which does not support version_2 files - specifically those lens corrections described by the Adobe Camera Model (acm). Is there a package available that does use Lensfun 0.3.2?

**Comment by parafin** [comment]
There are compatibility problems with switching to 0.3.95, that's why package is using latest stable release of lensfun.

**Comment by johnny-bit** [comment]
AFAIK fixed - openmp code now is checked in CI against possible problems.

**Comment by remarksbbq** [comment]
Why does darktable still use version 1 of lensfun. Lens in version 1 don't get updated. I'm using Linux Mint and updated darktable to 3.8 and it still uses the old lensfun database.

**Comment by ptilopteri** [comment]
you are expected to use lensfun-update-data or comparable for
your operating system to update the db.

**Comment by greenoid** [comment]
> you are expected to use lensfun-update-data or comparable for your operating system to update the db.

`$ lensfun-update-data -v
Info: root privileges needed for updating the system database.
Info: updating user DB in '/home/frerk/.local/share/lensfun/updates'
Reading http://lensfun.sourceforge.net/db/versions.json …
Reading http://wilson.bronger.org/lensfun-db/versions.json …
Successfully updated the database in /home/frerk/.local/share/lensfun/updates/version_1.
`
Update lensfun will only update version 1 files!

"The current package on darktable.org appears to use Lensfun 0.3.2, which does not support version_2 files - specifically those lens corrections described by the Adobe Camera Model (acm). "

I need darktable with lensfun in 0.3.95 and version 2 files that support the acm model.

**Comment by greenoid** [comment]
Sorry for hijacking this thread about compiling for MacOS. I use Linux and the problem persists with darkTable 3.8.0 and lensfun. The right way to go is to use the development information embedded in each RAW file, not to store it externally (for newer lenses). If have seen an approach for this kind of lens correction as a module, will research more.
