### ISSUE TITLE
Canon EOS 90D

### ISSUE THREAD

**Issue by juststur** [darktable-org/darktable#3980]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by juststur** [comment]
![image](https://user-images.githubusercontent.com/36450068/71872777-677e4e00-30eb-11ea-8189-205ee21d4ca8.png)

@LebedevRI, is this message that appears when opening DNGs converted from the 90D's CR3 RAW files have the same root cause, or is this a separate fix/issue to open?

**Comment by LebedevRI** [comment]
> is this a separate fix/issue to open?

Yes, separate

**Comment by urbach** [comment]
Is there anything I can help with here? Providing more raw samples? Test something? (I don't think I can be useful otherwise, as I don't know much about raw formats)

**Comment by johnny-bit** [comment]
ISOBMFF metadata reading is currently being worked on as well as CR3 reading support in rawspeed. We had a meeting recently, discussed a plan and cleared obstructions. You "just" have to be patient. I think we have proper samples of CR3 files in raw.pixls.us...

**Comment by urbach** [comment]
> ISOBMFF metadata reading is currently being worked on as well as CR3 reading support in rawspeed. We had a meeting recently, discussed a plan and cleared obstructions. You "just" have to be patient. I think we have proper samples of CR3 files in raw.pixls.us...

thanks! If I can be of any help, please let me know!

**Comment by roigis** [comment]
Hello,
I am very interested in using darktable with my 90D. Please let me know if I can help or if there is any update.
Thanks!

**Comment by victoryforce** [comment]
darktable now supports Canon 90D. It's done by libraw, but who cares? This issue is not about rawspeed camera support, but about darktable camera support.

Obviously, this issue should be closed.

**Comment by urbach** [comment]
yes, this can be closed!
