### ISSUE TITLE
darktable Demosaic module issue with Canon Small Raw file

### ISSUE THREAD

**Issue by ganouyang** [darktable-org/darktable#3988]
Use darktable 3.0 to process CR2 files from Canon EOS 6D Mark II saved as sRAW files. Tried to adjust Demosaic module parameters. The module was locked and shew message "Demosaicing only needed for raw images". Tried the same module with CR2 files saved as regular RAW, the module worked normal.

**Comment by parafin** [comment]
That's because sRAW isn't true raw, file is already demosaiced.
