### ISSUE TITLE
Nikon D7500 not available in Lens Correction module

### ISSUE THREAD

**Issue by kwazel** [darktable-org/darktable#3991]
The Nikon D7500 is not available as camera in the Lens Correction Module. I looked for the Nikon D500 since I remember this one has the same sensor, but that one is not there either. I usually choose on of the available siblings, D700, D7100 or D7200. This seems to work, but I use a prime lens so there is not much deformation anyway.
I don't want to upload footage because the footage is already available for D7500. However, I can add if specific photos are missing, please let me know.
If this is an easy fix that I can do myself in a pull request, please let me know where to look, because I could not find it so far.

**Comment by LebedevRI** [comment]
https://www.darktable.org/about/faq/#faq-external-deps
> lensfun is used for lens correction. If the lens correction module isn’t showing your camera or lens, or a wrong one, then please report that to those folks.

**Comment by kwazel** [comment]
I tracked down the problem. lensfun has been updated but Ubuntu still distributes an old version. This has been reported:
https://bugs.launchpad.net/ubuntu/+source/lensfun/+bug/1857862

**Comment by kwazel** [comment]
After updating Ubuntu to Focal the support for my camera broke again. I build and installed the most up to date version of lensfun froms source. Unfortunately darktable seems to fall back to `liblensfun.so.1` (which directs to Ubuntu's  `liblensfun.so.0.3.2`) where the most up to date version, `liblensfun.so.0.3.95`, can be reached using `liblensfun.so.2`. In short, my conclusion is that Darktable still uses liblensfun1. It can be argued that darktable cannot use liblensfun2 until among others debian provides this, but meanwhile uses of modern camera\s can no longer use lens correction in Darktable.

Note, I may be looking at this the wrong way. I know I 'fixed' this problem before updating Ubuntu, I just do not remember how. For now I manually added my camera to the database, but that is not a user-friendly solution.

**Comment by johnny-bit** [comment]
instead of changing version of lensfun (0.3.95 is "broken") use `lensfun-update-data` to update lens/body database.

**Comment by kwazel** [comment]
@johnny-bit It may be interesting to understand why 0.3.9.5 is broken. But the most important is: it works! I had to install `liblensfun-bin` to run `lensfun-update-data` but now I can use my camera without using updating lensfun itself.
I had tried `lensfun-update-data` but only the version from 0.3.9.5, which seemed to be, eh... broken.
