### ISSUE TITLE
[user manual] Outdated description in chapter 1.2.6. Shortcuts window

### ISSUE THREAD

**Issue by mepi0011** [darktable-org/darktable#3993]
I think the description in chapter 1.2.6 is no longer up to date. The described icon is no longer present in the current UI (or I don't see it).  In my opinion the chapter 1.2.6 can be deleted without replacement, because it is described again in chapter 8.4.

**Comment by AlicVB** [comment]
Nope, I think you'll discover a new feature by pressing 'H' ;)

**Comment by mepi0011** [comment]
Hi @AlicVB , 

Thank you for answering. Had misinterpreted something here.
