### ISSUE TITLE
Please add Panasonic DC-TZ91 as alias of DC-TZ90

### ISSUE THREAD

**Issue by andijoos** [darktable-org/darktable#3996]
Could you please add Panasonic DC-TZ91 as alias of DC-TZ90 in /usr/share/darktable/rawspeed/cameras.xml:

```
	<Camera make="Panasonic" model="DC-TZ90">
		<ID make="Panasonic" model="DC-TZ90">Panasonic DC-ZS70</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="-64" height="0"/>
		<Sensor black="139" white="4095"/>
		<Aliases>
			<Alias>DC-ZS70</Alias>
			<Alias>DC-FZ91</Alias>
			<Alias>DC-FZ92</Alias>
			<Alias>DC-FZ93</Alias>
			<Alias>DC-TZ91</Alias>
		</Aliases>
	</Camera>
	<Camera make="Panasonic" model="DC-TZ90" mode="4:3">
		<ID make="Panasonic" model="DC-TZ90">Panasonic DC-ZS70</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="-64" height="0"/>
		<Sensor black="139" white="4095"/>
		<Aliases>
			<Alias>DC-ZS70</Alias>
			<Alias>DC-FZ91</Alias>
			<Alias>DC-FZ92</Alias>
			<Alias>DC-FZ93</Alias>
			<Alias>DC-TZ91</Alias>
		</Aliases>
	</Camera>
```

**Comment by LebedevRI** [comment]
Can you link where it's stated that TZ91 and TZ90 are the same camera?

**Comment by junkyardsparkle** [comment]
@LebedevRI This is a well-known regional naming scheme of Panasonic, but I can't find any "official" documentation of it. However, [this page](https://www.panasonic.com/global/consumer/lumix/awards/compact.html)shows the equivalent models grouped together, for whatever that's worth...

**Comment by LebedevRI** [comment]
> @LebedevRI This is a well-known regional naming scheme of Panasonic

Yeah, i know.

> but I can't find any "official" documentation of it. However, [this page](https://www.panasonic.com/global/consumer/lumix/awards/compact.html) shows the equivalent models grouped together, for whatever that's worth...

Aha, nice find, thank you.

**Comment by LebedevRI** [comment]
@andijoos there are currently no samples for TZ91 camera on https://raw.pixls.us/, please contribute one.

**Comment by andijoos** [comment]
@LebedevRI I uploaded one sample of TZ41. Unfortunately I can only provide a 4:3 sample, since my TZ91 broke end of last year and I only have raw files in this aspect ratio.

**Comment by LebedevRI** [comment]
Thank you.
