### ISSUE TITLE
Avoiding color management options for preview?

### ISSUE THREAD

**Issue by NextTherapist** [darktable-org/darktable#3999]
Hi,

perhaps I only can't find it: how could I get rid of the color management options for previews or: what are they for? I think I do not need these:

lighttable:
- preview display intent
- preview display profile

darkroom:
- preview display profile

Thank you for help.

![lighttable color options](https://user-images.githubusercontent.com/16581692/71670100-298dcc80-2d6f-11ea-8546-c1061125ed76.png)

![darkroom softproof options](https://user-images.githubusercontent.com/16581692/71670108-2db9ea00-2d6f-11ea-8bbe-47dd09173b77.png)

**Comment by MStraeten** [comment]
If you don’t need color management then you might just ignore these ;)
These settings are useful if you care about colors.
For a short introduction: https://www.cambridgeincolour.com/tutorials/color-management1.htm

**Comment by aurelienpierre** [comment]
You can't ignore colour management. The best you can do to revert it to default is select sRGB as an output space, which is what is used by default in most OS if no custom profile is given.
