### ISSUE TITLE
Exported image very dark when local contrast is on and OpenCL

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4004]
DT 3.1 git master on Windows 10, nVidia 1060.
Occasionally the exported image in very dark. It happens when local contrast is activated and only with OpenCL.
I could't reliably reproduce the issue, but I could see in the log the following error:

[local laplacian cl] failed: -4

Hope it can help

**Comment by MStraeten** [comment]
Please add the xmp file so somebody can try to reproduce it.
