### ISSUE TITLE
UI: super tiny on/off history icons on Windows 10

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4005]
DT 3.1 git master on Windows 10, 4k monitor.
The on/off icons in the history stack are super small
![Cattura14](https://user-images.githubusercontent.com/43290988/71688293-ded87880-2d9f-11ea-98eb-21f8ff21683c.JPG)

while the same icons in modules are normal
![Cattura15](https://user-images.githubusercontent.com/43290988/71688330-f44da280-2d9f-11ea-81bd-09405aa6d01d.JPG)

**Comment by Nilvus** [comment]
These icons are actually 40% smaller than normal ones. That's wanted to make them quite different than other as these icons are not buttons like others, they are just here to inform module state.

Anyway, on your capture screen, they seems to be 50/60% smaller, so 10 to 20% smaller that's setting. 

Which theme do you use ? It seems to be the darktable one. Do you tweak something or use/have personal themes on you config folder ?

**Comment by Mark-64** [comment]
draktable-elegant-darker, no changes

**Comment by Nilvus** [comment]
> draktable-elegant-darker, no changes.
> But it's the same with all themes

Thanks. I can't and I never reproduce it on Linux I use. Maybe a Windows issue ? Anyway, quite strange as size is emphasis so font related and should be proportional as I said.
I made this CSS part. Sorry but solving it for you on darktable main code will break size on other OS (or some other Windows users who maybe don't have this issue). I could suggest you to create a personal CSS theme on your config darktable folder (add a themes folder in it) and use @import url line (like it's written on css file theme you use) and copy these lines:

#left #history-switch-always-enabled,
#left #history-switch-default-enabled,
#left #history-switch,
#left #history-switch-enabled
{
  font-size: 0.6em;
}

#left #history-switch-deprecated
{
  font-size: 0.5em;
}

Then you just have to increase font-size.

**Comment by Mark-64** [comment]
This works, thank you.
If I understand correctly, those are not real icons, but characters in some font !?
If so, which is the font ? It could be that Windows does not have such font installed and it falls back to something inappropriate.
I dis some investigation on my dual boot Win/Ubuntu, but I couldn't figure out.

**Comment by aurelienpierre** [comment]
Same issue here on Windows 10. Maybe GTK defaults to something else on Windows.

**Comment by Nilvus** [comment]
> This works, thank you.
> If I understand correctly, those are not real icons, but characters in some font !?
> If so, which is the font ?
> It could be that Windows does not have such font installed and it falls back to something inappropriate.
> I dis some investigation on my dual boot Win/Ubuntu, but I couldn't figure out.
> 
> edit:
> BTW there are other inconsistencies in the Windows GUI which seem to be font-related, so it could actually be the same issue:

Small icons on history seems to not affect all Windows 10 users. I have discussed on french forum with a user who show me capture which is good.

These icons are nor image nor fonts, they drawn by GTK with a related library named Cairo. They didn't need any font. Only font-size could be set, to set the size.
That's the same for the other glitch you have on the four icons.

**Comment by aurelienpierre** [comment]
Actually, the G and ? in the icons are fonts inserted in Cairo drawings as Pango objects. The rest of the icons are pure Cairo. Cairo drawings use DPI settings from darktablerc to scale the drawing coordinates. That part is pretty much fixed in our code. What I meant was the issue here is not really icons being smaller, but the font/icons proportions being off compared to other OS. So, it might be that GTK scales fonts differently on Windows, but that should be set somewhere in a config file.

**Comment by Mark-64** [comment]
In my Windows laptop with FHD resolution the proportions are OK, but in my desktop PC with 4k screen they are off in Windows, while they are ok in Ubuntu.
So it's actually the combination of Windows and HiDPI. For some reason HiDPI scaling in Windows is incorrect for few GUI elements

**Comment by Nilvus** [comment]
@Mark-64: good thing to read, so it's another DPI OS specific setting issue. Something already seen (for other parts of the UI) for Mac. I will let now other developers with Gtk and C coding skills to see if they can do something here. CSS doesn't manage directly DPI setting.

@aurelienpierre: maybe you could have more things to say here (or seeing that with a Windows developer, don't remember who).

**Comment by aurelienpierre** [comment]
We really need more workforce with Windows dev skills.

**Comment by Mark-64** [comment]
Fixed, closing
