### ISSUE TITLE
Export to Flickr Webalbum fails

### ISSUE THREAD

**Issue by DickThomas** [darktable-org/darktable#4007]
**Describe the bug**

I'm unable to export to Fickr, I'm told I'm unauthorised.

**To Reproduce**

1. Go to 'storage options'
2. Click on 'target storage'
3. Scroll down to 'Flickr web album'
4. try to login
5. See error on Flickr website

**Expected behaviour**

1. Go to 'storage options'
2. Click on 'target storage'
3. Scroll down to 'Flickr web album'
4. try to login
5. login? (not sure as I've never seen it)

**Screenshots**

![Screenshot from 2020-01-03 10-00-58](https://user-images.githubusercontent.com/822758/71717501-33b3d780-2e10-11ea-92f3-6bfd327b4fdc.png)

**Platform (please complete the following information):**
 - Darktable Version:3.00
 - OS: Arch Linux
 - OpenCL activated or not
Tried both.
 - Which graphics card and driver version
AMD Open-source version

I tried logging in to Flickr 1st and doing it signed out. 
also tried with Darktable run in a terminal but it gave nothing useful in the output.

**Comment by Nilvus** [comment]
It's just the problem to these proprietary solutions (it's the same for Facebook and Google Photos). They all change quite often their API (needed to let software communicate) and last API needs too many things, quite difficult to follow and maintain.  It's not only a darktable issue but what Flickr, Facebook, Google Photos ask to let now software use their API. Read this issue to understand more the problem: #4008

**Comment by DickThomas** [comment]
ah, Sorry my bad I did search Flickr I never thought to see if other APIs had stopped working too.

**Comment by aurelienpierre** [comment]
Flickr API has changed (again) so Flickr export will be deprecated in darktable and soon removed from the core. 

Third-party API will be handled from now on with Lua scripts, that should be easier to maintain.

**Comment by ybron** [comment]
@aurelienpierre Uh... I work at Flickr and the API has not changed, what are you seeing?
