### ISSUE TITLE
darktable 3.0 lut 3D does not work with 'activate OpenCL support' enabled

### ISSUE THREAD

**Issue by ganouyang** [darktable-org/darktable#4011]
**Describe the bug**
**To Reproduce**
1. Go to 'darktable preferences'
2. Check 'activate OpenCL support'
3. Open an CR2 file
4. Enable lut 3D, select a .png or .cube file
5. Strange dot overlay appears on the photo
-->
**Screenshots**
2 screenshots attached
xmp file attached
[IMG_9134.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/4019941/IMG_9134.CR2.xmp.txt)
**Platform (please complete the following information):**
 - Darktable Version: 3.0
 - OS: Windows 10 64bit
 - OpenCL activated or no activated
 - Which graphics card and driver version Intel HD Graphics Family 20.19.15.5070

**Additional context**
If uncheck 'activate OpenCL support', lut 3D works fine
![dt preferences](https://user-images.githubusercontent.com/59418292/71735724-c8203900-2e14-11ea-89ed-4d035bc64f6b.jpg)
![lut 3d result](https://user-images.githubusercontent.com/59418292/71735735-cce4ed00-2e14-11ea-9574-dbf1fc5487e1.jpg)

**Comment by pphotography** [comment]
That XMP and history show that it's unlikely a combination of 3d-lut with another module. Only thing I remenber was a bug with white spots in the image when using certain settings for demosaicing (I searched for the issue but didn't find it).

Maybe it's a driver issue. You mentioned a Intel HD Graphics Family driver. Is that driver for a CPU with integrated GPU or do you have a separate graphics card?

Can you try to re-install that graphics driver or try an older version?

**Comment by chhil** [comment]
https://github.com/darktable-org/darktable/issues/3371

I havent used lut 3d of late. My opencl is primarily switched off as I don't trust it results on my older laptop with 2 cards and intel and amd one. The intel one is disabled by darktable when I run the opencl test to load compiled kernels.

**Comment by Mark-64** [comment]
Can't reproduce with DT 3.1 on Windows 10, OpenCL on nVidia, same negative.png LUT.
Did you change the default module order ?

**Comment by chriscampbell96** [comment]
Seem to be having the same/similar issue:

LUT is loaded and not seen in the main picture unless the thumbnail, at the bottom, is double-clicked. Then on image zoom, the LUT colour grading disappears and the blocks appear. See screenshot below -

![Screenshot 2020-01-05 at 20 36 25](https://user-images.githubusercontent.com/17804704/71785777-8f8e8400-2ffb-11ea-9cd3-1ee9dd780dbb.png)

Then on image export, the image does not show the LUT, only small block pixels (lighttable also does not show LUT has been applied). See examples below - 
![GPTempDownload 4](https://user-images.githubusercontent.com/17804704/71785806-06c41800-2ffc-11ea-881f-44f84baf087a.jpg)

![GPTempDownload 4_02-min](https://user-images.githubusercontent.com/17804704/71785838-5dc9ed00-2ffc-11ea-990d-87cf06983f1c.jpg)

Currently running on Mac OS Catalina v10.15 - Darktable v3.0.0

**Comment by phweyland** [comment]
> Seem to be having the same/similar issue:

Do you get the same effect with any other lut, in particular not the log ones ?

**Comment by ganouyang** [comment]
> That XMP and history show that it's unlikely a combination of 3d-lut with another module. Only thing I remenber was a bug with white spots in the image when using certain settings for demosaicing (I searched for the issue but didn't find it).
> 
> Maybe it's a driver issue. You mentioned a Intel HD Graphics Family driver. Is that driver for a CPU with integrated GPU or do you have a separate graphics card?
> 
> Can you try to re-install that graphics driver or try an older version?

No change going back to older version. The graphics card is a integrated one - Intel HD Graphics 4400.

**Comment by ganouyang** [comment]
> Can't reproduce with DT 3.1 on Windows 10, OpenCL on nVidia, same negative.png LUT.
> Did you change the default module order ?

No I did not change the order

**Comment by ganouyang** [comment]
> > Seem to be having the same/similar issue:
> 
> Do you get the same effect with any other lut, in particular not the log ones ?

Yes, I tested with many, both .png and .cube files. The results are the same. Also, if I enabled openCL and made scheduling profile = multiple GPUs, the main screen seemed right, but the preview screen (the small one at top left corner) did not change.

**Comment by phweyland** [comment]
Could run darktable-cltest and share the output. Maybe there is some grain to grind there.

**Comment by ganouyang** [comment]
> darktable-cltest

Here is the output. I am not sure if I got everything, though.
[darktable-cltest.txt](https://github.com/darktable-org/darktable/files/4027560/darktable-cltest.txt)

**Comment by phweyland** [comment]
> Here is the output. I am not sure if I got everything, though.

Correct, it is truncated. Maybe you could do something like : darktable-cltest >file.txt

**Comment by ganouyang** [comment]
> > Here is the output. I am not sure if I got everything, though.
> 
> Correct, it is truncated. Maybe you could do something like : darktable-cltest >file.txt

Here is the complete output of darktable-cltest
[darktable-cltest-output.txt](https://github.com/darktable-org/darktable/files/4028706/darktable-cltest-output.txt)

**Comment by phweyland** [comment]
I haven't seen any particular issue apart the device `Intel(R) HD Graphics 4400`.
I have seen some discussions about Intel chipset, but I have no specific knowledge about this.

**Comment by aurelienpierre** [comment]
Did you check for negative pixels or out-of-gamut pixels ? What happens if you decrease the black level compensation in exposure module ?

**Comment by ganouyang** [comment]
> Did you check for negative pixels or out-of-gamut pixels ? What happens if you decrease the black level compensation in exposure module ?

I tried your suggested action, the results are the same, no improvement

**Comment by phweyland** [comment]
same issue here:
https://forums.darktable.fr/showthread.php?tid=4378&pid=37613#pid37613
