### ISSUE TITLE
darktable 3 for windows and CR3 file compatibility 

### ISSUE THREAD

**Issue by hk49100** [darktable-org/darktable#4014]
Hi

**Describe the bug**

**To Reproduce**
File attached is grabbed directly from the camera without any tranfer application (copy/past on Desktop then attached)
-->

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Sample**
Unable to attche the file (even zipped) due to size limitation but already submitted to https://raw.pixls.us/
FileName: IMG_3515.CR3
Size: 36,9 Mbytes (38 739 910 octets)

**Comment by MStraeten** [comment]
you know about search function? https://github.com/darktable-org/darktable/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+CR3
CR3 is not supported yet ...
