### ISSUE TITLE
Darktable not running anymore

### ISSUE THREAD

**Issue by nalpure** [darktable-org/darktable#4016]
I'm not sure if this is the right place to post this. If so just delete this. Really don't want to bother you guys.

**Describe the bug**
Since the 1st day of 2020 I can't run Darktable anymore. I only get the following message:

"An unhandled exception occurred. 
Backtrace will be written to [...]
If you report this issue, please share this backtrace with the developers."

This happened with darktable 2.6.3. By now I updated windows, my drivers and the darktable version - but still the same. Never had an issue before.

First backtrace: [darktable_bt_WWHSD0.txt](https://github.com/darktable-org/darktable/files/4021727/darktable_bt_WWHSD0.txt)
Latest Backtrace: [darktable_bt_9S2AE0.txt](https://github.com/darktable-org/darktable/files/4021728/darktable_bt_9S2AE0.txt)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Windows 10
 - I've run the default setup when installing, not sure if that means that OpenCl is activated or not.
 -   Intel(R) UHD Graphics 620 version 26.20.100.7262

Any idea of what could be the cause?

**Comment by aurelienpierre** [comment]
That's Intel Neo OpenCL driver failing. Try running darktable with OpenCL off, or update your driver, or uninstall it.

**Comment by MMRastatt** [comment]
Unfortunately I`ve since yesterday the same probem, but running darktable with with OpenCL off or uninstall doesn`t solve it. Any other ideas?

**Comment by cryptomilk** [comment]
The initial report shows it is the OpenCL driver of Intel which is crashing. If you say it fails for you with it off you need to provide a backtrace.

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by nalpure** [comment]
Alright, thanks a lot! Running it in the terminal with --disable-opencl works just fine. Took way to long till I found out that this command exists. 

But I've got another question: As I'm not the terminal using kind of guy, is there any way to set it up so it automatically opens with openCL off? In the settings, where I assumed you could do it, it just says "Not available" (in the screenshot "nicht verfügbar").

![debugScreenshot](https://user-images.githubusercontent.com/59500940/72138830-edb9bf00-338d-11ea-98d7-43f8b1e66fbe.jpg)

Any quick fix? Otherwise I'll just keep on using the terminal to open it.

**Comment by ptilopteri** [comment]
in win 10, open the dt program icon/link and add the command line parameters to the execute command.  I do not have windows available presently so cannot give better directions.

**Comment by chhil** [comment]
Find the darktable shortcut and edit it.
![image](https://user-images.githubusercontent.com/1119439/72161382-06ee5a00-33e6-11ea-9632-1e31a3d66e15.png)

Add the parameter you want and apply it. Next time you click or run darktable using the shortcut the disable opencl will always be used.
![image](https://user-images.githubusercontent.com/1119439/72161235-bd9e0a80-33e5-11ea-9760-4626feff2d5b.png)

**Comment by aurelienpierre** [comment]
Find your `darktablerc` config file and set `opencl=off`
