### ISSUE TITLE
Move 'Crop & Rotate' after 'Spot Removal' and 'Retouch'

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4018]
Often I will use the spot removal and retouch modules to clone/heal data from an area which I later crop. Because 'Crop & Rotate' is before the 'Spot Removal' and 'Retouch' modules in the pipeline, this is no longer possible in darktable 3.0 (since the retouched area is no longer present).

Please move 'Crop & Rotate' module in the default iop order.

**Comment by TurboGit** [comment]
Please read the release notes :)

**Comment by elstoc** [comment]
Ok I've re-read the release notes and it doesn't mention the three modules referenced in this issue. I assume that you must have meant the section on "Other Improvements", particularly the statements "The default order is safe and optimized for the majority of uses" and "It is now possible to re-order the modules"?

On the first statement, this is something that has always been emphasised in the manual (as a reason the module order previously could not be changed). However, the order has changed significantly in 3.0, so I can only assume the statement was not true before but is now?

Have you rejected my bug because there is a technical reason or a more common use case meaning Crop and Rotate needs to be placed before spot/retouch; or because the default order no longer has to be correct since users can re-order at will.

**Comment by TurboGit** [comment]
I have rejected it because it is not a bug and so nothing to fix. To get the older behavior you can change the module order from the darkroom and place sport removal before crop&rotate.

See also #3908.

**Comment by elstoc** [comment]
Should I have raised an enhancement request?

**Comment by TurboGit** [comment]
No, as there is currently all the support to do what you ask in v3.0.

**Comment by elstoc** [comment]
Ok so no changes to the default order from now on. Got it.
