### ISSUE TITLE
[Tone Equalizer] influences drawn masks in other modules when zooming

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4020]
**Describe the bug**
Weird artifacts showing, when zooming to finetune a drawn mask and tone-eq has been switched on.
It merely shows in the lower half of the picture, the upper part is just B/W

**To Reproduce**
1. Use filmicRGB and tone equalizer
2. e.g. creaete a drawn mask in denoise profiled
3. middle click on the lower half of the pic to zoom
4b. now switch of tone-eq and do step 3 again = no effect

**Expected behavior**
Drawn mask shall be always shown correctly

**Screenshots**
overview
![Screenshot_20200101_230615](https://user-images.githubusercontent.com/49004103/71765938-9bdee800-2efa-11ea-8136-03275879b428.png)

Zoomed in lower haf
![Screenshot_20200101_230638](https://user-images.githubusercontent.com/49004103/71765940-a4372300-2efa-11ea-89a9-1b72eee68797.png)

Zoomed in middle of pic
![Screenshot_20200101_231024](https://user-images.githubusercontent.com/49004103/71765944-ac8f5e00-2efa-11ea-8dcf-9b6e3b45b339.png)

Tone Eq off
![Screenshot_20200101_231209](https://user-images.githubusercontent.com/49004103/71765958-c6c93c00-2efa-11ea-93c7-9786805c1a2b.png)

**Platform (please complete the following information):**
 - Darktable Version: **3.0.0** and **current master**
 - OS: **Gentoo Linux**
 - OpenCL activated or no? **on and off**
 - Which graphics card and driver version **2x nvidia GTX1060; nvidia-drivers 440.44-r1**

**Additional context**
 - Can you reproduce with another Darktable version? **Yes**
 - Can you reproduce with a RAW or Jpeg or both? **RAW**
 - Are the steps above reproduce with a fresh edit (removing history)? **Yes**
 - Attach an XMP if this is necessary 
[2019-12-14_124134__EM50058_02.ORF.xmp.tar.gz](https://github.com/darktable-org/darktable/files/4021931/2019-12-14_124134__EM50058_02.ORF.xmp.tar.gz) 
not 100% same version, as I had to redraw the mask
 - Did you compile Darktable yourself? If so which compiler was used, with what options? **x86_64-pc-linux-gnu-9.2.0 CMAKE_BUILD_TYPE="Release" CFLAGS="-march=native -O3 -mtune=native -pipe"**
 - Is the issue still present using an empty/new config-dir **Yes**

**Comment by jade-nl** [comment]
Confirmed.

Using:
- Debian 10.2
- darktable 3.1.0+291
- opencl off
- nVidia GF104 [GeForce GTX 460]
- 2 random RAW's (different camera's)

**Comment by aurelienpierre** [comment]
ahhhhhhhh I'm stupid. I know where the mistake comes.

**Comment by AxelG-DE** [comment]
It seems WIP
