### ISSUE TITLE
[mask refinement] feathering radius weird artifacts

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4021]
**Describe the bug**
When mask opacity has been set to 1,00 in a drawn mask, feathering radius creates strange lines, and they are actually in the mask than

I know it makes no sense in a drawn mask only, but drawn and parametric, it does, typically L-Mask). Just the error also appears with drawn only, so we can concentrate on that.

**To Reproduce**
1. Go to any module, e.g. exposer
2. create a drawn mask
3. change opacity to 1,00
4. change feathering  radius to e.g. 2,4

**Expected behavior**
Mask should be handled propperly, as it is, when mask opacity is not changed

**Screenshots**
![Screenshot_20200104_142610](https://user-images.githubusercontent.com/49004103/71766347-5a047080-2eff-11ea-9e86-d2d811403e1c.png)

**Platform (please complete the following information):**
 - Darktable Version: **3.0.0** and **current master**
 - OS: **Gentoo Linux**
 - OpenCL activated or no? **on and off**
 - Which graphics card and driver version **2x nvidia GTX1060; nvidia-drivers 440.44-r1**

**Additional context**
 - Can you reproduce with another Darktable version? **Yes**
 - Can you reproduce with a RAW or Jpeg or both? **RAW**
 - Are the steps above reproduce with a fresh edit (removing history)? **Yes**
 - Attach an XMP if this is necessary 
[2019-12-14_124134__EM50100.ORF.xmp.tar.gz](https://github.com/darktable-org/darktable/files/4021953/2019-12-14_124134__EM50100.ORF.xmp.tar.gz)
 - Did you compile Darktable yourself? If so which compiler was used, with what options? **x86_64-pc-linux-gnu-9.2.0 CMAKE_BUILD_TYPE="Release" CFLAGS="-march=native -O3 -mtune=native -pipe"**
 - Is the issue still present using an empty/new config-dir **Yes**

**Comment by jade-nl** [comment]
Confirmed.

The order  in which the opacity and feathering are applied doesn't matter.

Played around a bit with the values:
- Opacity needs to be 1 or larger.
- Feathering needs to be .2 or larger.

Using:
- Debian 10.2
- darktable 3.1.0+291
- opencl off
- nVidia GF104 [GeForce GTX 460]
- 2 random RAW's (different camera's)
