### ISSUE TITLE
Re-reading exif data button is gone?

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#4022]
**Describe the bug**
@sams96  gave us #2792 to refresh exif data. This feature seems to have gone in master git.

**Expected behavior**
have it available again :-)

 - Darktable Version: 3.2 git master

**Comment by sams96** [comment]
It's under the metadata tab in selected image[s]

**Comment by jenshannoschwalm** [comment]
Oh man, i have done to much exiv2 code today :-) thanks
