### ISSUE TITLE
regression of color zones module in 3.0 

### ISSUE THREAD

**Issue by upegelow** [darktable-org/darktable#4023]
**Describe the bug**
With its current default setting the color zones module in 3.0 produces strong artifacts even for minor changes of the lightness curve. That module used to be a quite robust and reliable tool up to 2.6. This is no longer the case. 

I know that the old behavior can be activated by "process mode = smooth". However, I fail to see why that change has been implemented in the first place. Users will quickly get frustrated with the current default mode "strong".

[See also discussion in darktable-users](https://www.mail-archive.com/darktable-user@lists.darktable.org/msg08347.html)

**To Reproduce**
1. open image, e.g. with sky area
2. activate color zones module
3. modify lightness curve to darken sky
--> grain like artifacts

**Expected behavior**
A much more robust behavior like in 2.6 with low risk of artifacts. 

**Screenshots**
See artifacts in sky above the line of trees.
![Screenshot_20200104_174548](https://user-images.githubusercontent.com/1794020/71768875-d193c900-2f1a-11ea-8557-745abe888d74.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0 and 3.1
 - OS: OpenSuse Leap 15.1
 - OpenCL: has no influence

**Comment by TurboGit** [comment]
I've also experienced that? Maybe revert to the soft mode of the module where the behavior should be ok. Have you tried?

**Comment by upegelow** [comment]
> I've also experienced that. Maybe revert to the soft mode of the module where the behavior should be ok. Have you tried?

Yes, it's much better. Minimum should be to make "smooth" the default process mode.
But why then has the new mode been implemented in the first place. IMHO it's completely broken. If this would be my first encounter with that module it would also be my last :(

**Comment by TurboGit** [comment]
See #4025.

**Comment by upegelow** [comment]
Much better. Thanks!

**Comment by TurboGit** [comment]
Ok, merged on master and 3.0.1.
