### ISSUE TITLE
Preview menu interaction is a bit rough.

### ISSUE THREAD

**Issue by borissmidt** [darktable-org/darktable#4024]
**Is your feature request related to a problem? Please describe.**

I have found multiple unexpected behavior in darktable related to the preview:

In this case:
![screenshot_3](https://user-images.githubusercontent.com/5995670/71768992-cab98600-2f1b-11ea-95d8-664a08a62bfd.png)
If you toggle to the preview of an image (alt-w) [A]
and you open the bottom menu [B]

Then menu B doesn't change when navigating through the images using the arrow keys.
i.e. the ui would be really handy if you could see the current previewed image in the middle and then you will see wat comes next.

Another thing i found, is that when you select an image in menu B and then use the arrow keys to navigate then you will continue where the last preview was.
To put it a bit more technical:
Lets say we have images form 1 to 10 and i select image 2 in lighttable and move enablethe preview.
Then if i go to the next image, right arrow, i see image 3.
Then  I select image 7 in menu B and i see 7,
Then i press the right arrow key i see image 4 and not 8.

Other things i found:
When i lightroom if i go to the preview menu and navigate then the clicked image selection doesn't change. only the mouse over over image changes. So it is really hard to know which image you where at. Unless you click the preview image.

The preview starts from the position your mose is hovering over so it is hard to start the preview from where you left off.  

When you have the same setup as the image, and you double click the preview to go to darkroom, and come back then menu B will become hidden.

If you toggle to preview `alt-w` then only `alt-w` allows you to exit the preview not esc.

**Describe the solution you'd like**

I would be nice that window B followed your current preview highlighting the current image as the middle image.

When i click an image then this will become the new selected image and will be used as the reference for the next and previous key.

Change the selected image i.e. clicked one, depending on the preview you are looking at so you have reference where you came from.

**Alterntive**
I think it might be easier for navigation and everything if the preview becomes a seperate part in the ui. 
A bit like it is done in adobe bridge, one side are your images the other side the preview. 
The preview is then dependent on the mouse hover. 
if the mouse is not hovering over any image then the last clicked item will be displayed.
the arrow keys update the click selected image. i.e. you click an image it gets previewed and you continue with the arrow keys. 

alt-w would only show or hide this extra window.

I know these changes might be non trivial, (i've coded a long time ago in c++/ QT).
If you need any help in testing and finding these weird quirks i would be really happy to help. Since i really like darktable and it would become even better if it had less of these rough edges.

**Comment by borissmidt** [comment]
(i was finding new issues while describing the request that is why it is a bit long)

**Comment by borissmidt** [comment]
Sadly no reaction after 15 days,  i guss its better if i close it?

**Comment by johnny-bit** [comment]
@AlicVB is doing huge rewrite in #4103 which might address some of the issues mentioned here...

**Comment by Nilvus** [comment]
@borissmidt: this part has seen a huge rework since your post. I'll close it but if you find that your issue is still here, feel free to reopen (or create a new ones) with new infos from last darktable release.
