### ISSUE TITLE
Missing gridlines in tone curve with darktable-elegant-grey theme

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4026]
Using the darktable-elegant-grey theme, the gridlines on the tone curve module are only barely visible. 

![Screenshot_2020-01-04_18-10-26](https://user-images.githubusercontent.com/9555491/71769815-829b6300-2f1d-11ea-9207-03c538926d6a.png)

I've fixed this locally by changing @define-color graph_border from ‘@grey-35’ to ‘@grey-10’ in darktable-elegant-grey.css, which gives the following.

![Screenshot_2020-01-04_18-08-27](https://user-images.githubusercontent.com/9555491/71769786-436d1200-2f1d-11ea-80ed-b3efad0acb47.png)

I notice that the rgb curves doesn't seem to be affected by this, which presumably means it's not yet using those css colour values.

**Comment by Nilvus** [comment]
@elstoc : thanks for pointing that. I don't use tone curve so forget that. I will add this (and check that not breaks anything else) to my WIP progress #3854 (@TurboGit : just to inform you).

**Comment by TurboGit** [comment]
Ok, thanks @Nilvus .

**Comment by Nilvus** [comment]
@elstoc : I just set to grey_15 which I find a little better for UI consistency than grey_10.

**Comment by TurboGit** [comment]
Fixed now. Thanks to both of you!

**Comment by elstoc** [comment]
Thanks @Nilvus. I didn't play with the settings much - I just did enough to get it visible. I've tried locally with grey_15 and I agree - it's more consistent with the other modules.
