### ISSUE TITLE
Drawn & parametric masks for lens correction 

### ISSUE THREAD

**Issue by alexvanderberkel** [darktable-org/darktable#4028]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to control which area are being brighten within the lens correction module. The vignetting option approach of leads to blown out highlights which are not being blown out before applying this correction option.

**Describe the solution you'd like**
It would be very useful to have an option similar to the drawn & parametric masks to select which parts of the image should be brighten up via the vignetting options. With the option brush, circle etc. in addition to the parametric mask it would be possible to avoid the blown out highlands.

**Comment by junkyardsparkle** [comment]
The vignetting correction can sometimes be too strong, but I don't think adding masks to the module is the right way to deal with that (it certainly doesn't make any sense for the other corrections it performs). Manually adjustment of vignetting correction would be nice, though... see #1990.

You can use the "vignetting" module for what you describe, it works best for this when moved in the pipe (for instance, just after the cropping module if you want it to auto-fit to your crop, or just after lens correction otherwise).

**Comment by cryptomilk** [comment]
If the vignetting correction is too strong than the profile is bad! The right way would be to fix the vignetting parameters in lensfun:

https://pixls.us/articles/create-lens-calibration-data-for-lensfun/

**Comment by junkyardsparkle** [comment]
> If the vignetting correction is too strong than the profile is bad!

There are probably some cases where the profile is actually over-correcting (I think we've discussed that problem before). But even a "perfect" profile produces an absolute correction, such as would be used when stitching panoramas or for other technical purposes, and this can often be "too strong" for users; the in-camera correction I've seen doesn't go this far, either. Therefore, adding some user-adjustability to the module would make sense (right now, you can kind of "fake it" by spoofing aperture setting, but this is unpredictable, and must be done manually).

**Comment by aurelienpierre** [comment]
It seems sensible to be able to dial up or down the profile.

**Comment by alexvanderberkel** [comment]
How could this be implemented @aurelienpierre ?

**Comment by matt-maguire** [comment]
Best way is to profile your copy of the lens -- put a translucent cover over the lens that diffuses the light so you get an even light without any texture in it, take a picture, and use the tools to generate a new profile. You then have a custom profile that matches the precise characteristics of your copy of the lens.
