### ISSUE TITLE
Darktable 3.0.0 fails to start: error while loading shared libraries: libdarktable.so

### ISSUE THREAD

**Issue by silentcreek** [darktable-org/darktable#4029]
Hi,

I installed the Darktable 3.0.0-lp151.216.1 package from OBS graphics:darktable on my openSUSE Leap 15.1 machine. The software fails to start however (nothing happens). If I try to run it from the console, I get the following error message:
```
> darktable
darktable: error while loading shared libraries: libdarktable.so: cannot open shared object file: No such file or directory
```

The file does exist in /usr/lib64/darktable/libdarktable.so however. If I try to run darktable with a specific library path, the error looks a bit different:
```
> /lib64/ld-linux-x86-64.so.2 --library-path /usr/lib64/darktable/ darktable
darktable: error while loading shared libraries: darktable: cannot open shared object file
```

The library is world-readable, though, and not empty either, so I'm at loss to tell what's wrong here.

Cheers,

Timo

**Comment by TurboGit** [comment]
Maybe a packaging issue with the current OBS ?

**Comment by phorham** [comment]
Issue raised on the openSUSE bugzilla:
https://bugzilla.opensuse.org/show_bug.cgi?id=1160071


Temporary "fix" is to create a symlink:
ln -s /usr/lib64/darktable/libdarktable.so /usr/lib64/libdarktable.so

**Comment by silentcreek** [comment]
Ok, thanks. I wasn't sure where to report issues for OBS packages and hence darktable actively promotes them, I decided to do so here. But good to know where the right place is and that the cause is already determined so someone can work on it.

**Comment by cryptomilk** [comment]
It looks like it might skip the RPATH.

**Comment by cryptomilk** [comment]
It clearly has set:

`-DCMAKE_SKIP_RPATH:BOOL=OFF`

so it should work unless something else overwrites it.

**Comment by mikhailnov** [comment]
See https://github.com/darktable-org/darktable/issues/8122
