### ISSUE TITLE
White balance preset not considered, applying a style

### ISSUE THREAD

**Issue by alberanid** [darktable-org/darktable#4031]
**Describe the bug**

Applying a style which contains the White Balance module set to "camera" preset will apply the single values (tint, temperature, ...) used by the image when the style was saved, ignoring the "preset" value.

**To Reproduce**
1. open an image and set WB preset to "camera"
2. save the style, including the WB module
3. open a different image, taken with different settings/lens
4. apply the saved style
5. notice that the tint and temperature are wrong
6. set again WB "preset" to "camera" (even if the dropdown is already on "camera")
7. see that the image is now correct

**Expected behavior**

If the single values were not modified manually, apply the proper "camera" preset to the new image.

**Screenshots**

the image, just imported:
![imported](https://user-images.githubusercontent.com/222857/71778179-bec8d500-2faa-11ea-9279-5ccc4dbe291e.jpg)

saved style applied:
![apply-saved-style](https://user-images.githubusercontent.com/222857/71778193-e4ee7500-2faa-11ea-8c17-22c49652e0d5.jpg)

set again WB preset to "camera":
![set-preset-to-camera-again](https://user-images.githubusercontent.com/222857/71778197-f33c9100-2faa-11ea-8d02-74ac862a68e5.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Ubuntu 18.04
 - OpenCL activated
 - GeForce GTX 970, NVIDIA-SMI 440.33.01 Driver Version: 440.33.01 CUDA Version: 10.2

**Additional context**

The style I'm using for this test: [workflow 3.0 20200103.dtstyle.zip](https://github.com/darktable-org/darktable/files/4023263/workflow.3.0.20200103.dtstyle.zip)

**Comment by junkyardsparkle** [comment]
Yes, the "camera" preset isn't really an "auto" setting as found in some modules, although I guess it potentially could be. IMHO that whole menu arrangement could use some re-thinking (and it's currently broken, see #3228).

**Comment by aurelienpierre** [comment]
Duplicate #3228. Closing.
