### ISSUE TITLE
Current build Version string: 3.1.0+302~g98e608f63 fails to build on windows

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4036]
Current build fails on windows. Deleted the build directory. Git pull said the code is current.
Last successful build was from yesterday darktable-3.1.0+291~gc19fbc6ad-win64

[ 15%] Building CXX object src/CMakeFiles/lib_darktable.dir/common/exif.cc.obj
In file included from F:/msys64/mingw64/include/glib-2.0/glib/gi18n.h:23,
                 from F:/msys64/home/chill/darktable/src/common/darktable.h:58,
                 from F:/msys64/home/chill/darktable/src/common/colorlabels.h:3,
                 from F:/msys64/home/chill/darktable/src/common/exif.cc:57:
F:/msys64/home/chill/darktable/src/common/exif.cc: In function 'GList* dt_get_exiv2_taglist()':
F:/msys64/home/chill/darktable/src/common/exif.cc:238:10: error: '__printf__' is not a member of 'std'; did you mean '__printf__'?
  238 |     std::printf("[exiv2 taglist] exception: \"%s\"\n", e.what());
      |          ^~~~~~
F:/msys64/mingw64/include/libintl.h:350:12: note: '__printf__' declared here
  350 | extern int printf (const char *, ...);
      |            ^~~~~~
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:350: src/CMakeFiles/lib_darktable.dir/common/exif.cc.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1321: src/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

-----
Script used

#!/bin/bash
cd ~
cd darktable
git pull
git submodule update

cd build
cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./releaseDT ../.
cmake --build .
cmake --build . --target install
cmake --build . --target package

**Comment by TurboGit** [comment]
@phweyland : the std;printf in the new code seems to cause troubles on Windows, any idea ?

**Comment by phweyland** [comment]
@TurboGit : I look at it.

**Comment by Mark-64** [comment]
same here, build fails on windows, ok on Ubuntu

**Comment by Mark-64** [comment]
fixed with the last commit for me

**Comment by chhil** [comment]
Fixed for me (prior to mepi0011 commits, which appear incorrect) . Closing ticket.
