### ISSUE TITLE
Watermark preview blurs on rotation

### ISSUE THREAD

**Issue by simonkolotov** [darktable-org/darktable#4040]
When trying to rotate a watermark by more than 30 degrees it starts to blur very significantly.
My use case is that sometimes I will intentionally rotate the image by a significant angle and leave it uncropped.
In that case - if I choose to add a watermark - I like it rotated so it looks like a part of the image (see attached).

I noticed this behaviour in version 2.6 (maybe even earlier) and as I upgraded to 3.0 just now it's still there.

Note: As I was adding more information to this bug I noticed that it's a render issue - as the image is rendered smaller than 1:1, the SVG is blurred as if it were significantly downsampled.

Thanks,

Simon

ATTACHED:
screenshots at "full screen" lighttable and maximal zoom in darkroom, as well as a (downsampled) exported version of the image, where you see the watermark is blurred.
I also attach the SVG of the watermark

![IMG_9854_01](https://user-images.githubusercontent.com/4603429/71794561-f0678d80-2ff6-11ea-8f3e-ef7fc053fa13.jpg)
![Screenshot at 2020-01-05 19-58-54](https://user-images.githubusercontent.com/4603429/71794404-32dc9a80-2ff6-11ea-89f8-70bbd8a07b3d.png)
[SK.svg.zip](https://github.com/darktable-org/darktable/files/4024664/SK.svg.zip)

**Comment by jenshannoschwalm** [comment]
@aurelienpierre you agree i go for this one? I know cairo stuff fairly well.

**Comment by aurelienpierre** [comment]
@jenshannoschwalm No problem, thanks !

**Comment by TurboGit** [comment]
@jenshannoschwalm : sure, the code is no one property :) go ahead ! I would say you just have to send a notice to avoid having many people working on the same issue.

**Comment by jenshannoschwalm** [comment]
Has been fixed in master.

**Comment by jenshannoschwalm** [comment]
@aurelienpierre please close this manually ...

**Comment by jenshannoschwalm** [comment]
@TurboGit this had been fixed via #4135

**Comment by TurboGit** [comment]
Right. Closing.
