### ISSUE TITLE
Resizing side panel distorts waveform display

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#4049]
**Describe the bug**

A feature was recently merged that allow on-the-fly resizing of the left and right panels in darkroom.  Resizing the right panel 'permanently' corrupts waveform display.

I'm going to guess that the issue is located here:
https://github.com/darktable-org/darktable/blob/ab290c8f9ee8e52729084bbc6152a63e8b0a467f/src/libs/histogram.c#L195-L207

**To Reproduce**
1. Go to darktable with any raw.  Make sure the histogram view is set to the waveform mode.
2. Resize the right panel.  Any adjustment will do (even a 1px adjustment is enough)
3. Note that the distortion in the waveform.
4. Make any adjustment to the image and not that the waveform remains distorted.
5. Switch photos.  Waveform still unusable.

**Expected behavior**
Resizing the left panel should not render the waveform unusable.

**Screenshots**

With no distortion:
[![wf-no-distort.png](https://i.postimg.cc/yYX0bRfm/wf-no-distort.png)](https://postimg.cc/Ln5qqJF5)
Distorted:
[![wf-distort.png](https://i.postimg.cc/V6CCB0rb/wf-distort.png)](https://postimg.cc/G8btb2jc)

**Platform (please complete the following information):**
 - Darktable Version: master (3.1.0.r306.g2bb30a314)
 - OS: archlinux
 - OpenCL: yes (intel NEO)

**Comment by Nilvus** [comment]
Probably this PR is related: #4041 (@dtorop)

**Comment by groutr** [comment]
@Nilvus, great!  
I didn't observe a crash in my case, simply a corruption.
I can test it on my machine.
