### ISSUE TITLE
selected images tabbed ui breaks lua register_action

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#4050]
**Describe the bug**
The lua function register_action() adds a button to the selected_images module.  The changes to a tabbed implementation didn't update the register_action function therefore it expects a single page grid instead of a multi page notebook.  Any lua script using register_action() throws an error as follows:

```
(darktable:9561): GLib-GObject-WARNING **: 19:45:04.559: invalid cast from 'GtkBox' to 'GtkGrid'

(darktable:9561): Gtk-CRITICAL **: 19:45:04.559: gtk_grid_attach_next_to: assertion 'GTK_IS_GRID (grid)' failed
```

This error is only present in darktable 3.1+

**To Reproduce**
1. Edit the luarc file and add the line require "examples/multi_os"
2. Start darktable with -d lua
3. Open the selected images module
4. There should be a button `extract embedded jpeg`, but there isn't
5. Look in the console and see the following error
```
(darktable:9561): GLib-GObject-WARNING **: 19:45:04.559: invalid cast from 'GtkBox' to 'GtkGrid'

(darktable:9561): Gtk-CRITICAL **: 19:45:04.559: gtk_grid_attach_next_to: assertion 'GTK_IS_GRID (grid)' failed

```

**Expected behavior**
Button should be in the selected images module

**Platform (please complete the following information):**
 - Darktable Version: latest git
 - OS: Ubuntu 18.04
 

**Additional context**

I looked at the code.  I've been speedreading the GTK API manual trying to think of the best approach to fix it.

I could add page1 and page2 to the dt_lib_image_t structure, then just access page1 and update it.

or 

I could run down the widget tree until I get to page1 then update it.  The first is easier, but I'm not sure what else uses dt_lib_image_t.  Also, should we make page2 available to register_action()?

Thoughts?

**Comment by phweyland** [comment]
> I could add page1 and page2 to the dt_lib_image_t structure, then just access page1 and update it.
or
I could run down the widget tree until I get to page1 then update it. The first is easier, but I'm not sure what else uses dt_lib_image_t. Also, should we make page2 available to register_action()?

Sorry for that. I have not seen this feature.
For my understanding, this routine adds new features below the existing buttons, that's correct ?

I think your first proposal is enough. Just adding page1 & page2 into dt_lib_image_t with some explanation would clarify the context enough for any further changes.

**Comment by phweyland** [comment]
I can make the change myself, but I'm not a lua user and I'm not sure to test the fix properly...

**Comment by wpferguson** [comment]
Thanks @phweyland , adding page1 and page2 was the way I was leaning.  I'll go ahead and do it.
