### ISSUE TITLE
Local contrast module completely blacks out entire picture

### ISSUE THREAD

**Issue by HardySoftware** [darktable-org/darktable#4051]
**Describe the bug**
My title suggested the issue, once I enabled local contrast module, the entire picture becomes black in preview, the exported image is also pure black. It does not happen all the time, but certain unknown combination triggered the bug.

**To Reproduce**
Check the attached raw and xmp file, just enable/disable last step (local contrast).

**Expected behavior**
Picture should be previewed and exported properly.

**Screenshots**
I am not going to attach screenshot, but the actual file I am working on https://ln2.sync.com/dl/6190f2200/xfgn43zp-bdpzeku6-agqr2jdz-duybazjd

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Windows 10
 - OpenCL activated yes
 - Which graphics card and driver version: Radeon RX590, driver 19.12.1

**Additional context**
This is just my speculation, the culprit is filmic rgb. If this module is on many other modules start to behave strangely. I could even have the "shadows and highlights" to black out entire image if "filmic rgb" is on.

**Comment by MStraeten** [comment]
Have a look on the second tab of the filmic rgb module - check the setting of ‚preserve chrominance‘ - there you can select luminance Y or max rgb instead.
The behaviour is already fixed for 3.0.1; to understand the issue see https://github.com/darktable-org/darktable/issues/3865#issuecomment-569365681 
BTW: you can search for such issues - there plenty of them around here

**Comment by HardySoftware** [comment]
Thanks foe the explanation.
