### ISSUE TITLE
On import "module basicadj version mismatch 2!=1"

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4059]
Don't know in what version I had  previously edited the raws in this folder, I was importing them, and they had their xmps. The DB did not have these as I upgraded to 3.1 at some time and had a clean db.

![image](https://user-images.githubusercontent.com/1119439/71964530-c2b35c00-3223-11ea-828a-b7f6586f3d05.png)

darktable-3.1.0+320~g218dd5d8c-win64

**Comment by junkyardsparkle** [comment]
Also reported on list: https://www.mail-archive.com/darktable-user@lists.darktable.org/msg08377.html

**Comment by Mark-64** [comment]
I see the same message when I import folders with old edits

**Comment by aurelienpierre** [comment]
This happens if you used darktable 2.7 and the params stucture got changed since then.
