### ISSUE TITLE
[Tone Equalizer] Curve smoothing Issue

### ISSUE THREAD

**Issue by jefferson2z** [darktable-org/darktable#4062]
**Describe the bug**
On the new Tone Equalizer module, on the advanced tab, if I rise the curve smoothing above 0.93 the curve of exposures rises to the maximum and the expose on the image. (The points remain in the same position, but the curve jumps and the effect on the image jumps)

**To Reproduce**
1. On the Darkroom mode, activate the tone equalizer module.
2. Go to the advanced tab.
3. Rise the curve smoothing field above 0.93

**Expected behavior**
The curve

**Screenshots**
Screenshot right before the error
![image](https://user-images.githubusercontent.com/16234072/71990506-42d0c600-3212-11ea-94a6-85f89ec2a37a.png)

Screenshot after the error
![image](https://user-images.githubusercontent.com/16234072/71990581-64ca4880-3212-11ea-8295-37b26e6df329.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0-1
 - OS: Fedora Linux
 -  OpenCL not Activated

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both?
RAW
 - Are the steps above reproduce with a fresh edit (removing history)?
YES
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
No, from the repository.

**Comment by aurelienpierre** [comment]
Please read the tooltip of that setting. Not a bug.
