### ISSUE TITLE
Add Area Color Picker to Tone Curve Module

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4066]
The new rgb curve module allows you to choose either an area or a point colour picker to highlight on the histogram. Please can this functionality be added to the tone curve module as well.

In darktable 2.6 you used to be able to do it as follows:
 - Select the color picker in the tone curve module
 - Open the color picker module and change from 'point' to 'area'
 - Select the area you want to view

In darktable 3.0 it seems you have to actually add the area to the 'live samples' in order for it to highlight in the tone curve histogram, and then later remember to remove it again, which is a bit of a long-winded process.

**Comment by MStraeten** [comment]
ctrl+ selection of the picker enables the area select

**Comment by elstoc** [comment]
So it does. Thanks @MStraeten . I think it still would be nice for the UI to be consistent between the rgb and tone curves, but good not to have to use my long-winded workaround!

**Comment by elstoc** [comment]
Apologies I'd missed the point of the other picker in rgb curves - to create a set of points based on an area selection. The selection and display of areas on this histogram **is** consistent between the two modules (ctrl-click).
