### ISSUE TITLE
Brush Issue noticed in Retouch Module

### ISSUE THREAD

**Issue by jpmatsci** [darktable-org/darktable#4068]
I am running Darktable 3.0.0.  I just built it last night from source on Ubuntu 18.04.  The issue was first noticed in re-touch using the brush(but sometimes shows up other times), and appears to have limits outside of the graphical ones.  Meaning that if you continue to ctrl-scroll too far after the GUI has hit the limit you can push your brush limits outside of normal ones.  Then when you scroll back and the gui reports a percentage, it is in fact lower or higher than actual value, depending direction of previous scroll.  I read through your code and I think that the problem is probably in line 1086(&1135&1141) in /src/develop/masks/brush.c and based the diffs on them I ran from version 2.3.6 and 3.0.0.  I am sort of a noob at C but hopefully that helps.  I will try to modify it and re-build when I get the chance, and IF I understand the issue in terms of the issues with floating point numbers in binary,
BTW You guys are amazing and I am a huge proponent of Darktable to everyone I meet.

**Comment by jpmatsci** [comment]
Well I rebuilt with 0.05f changed back to 0.0005f and that just seemed to slow things down and not fix the problem.  So perhaps I have no idea whats going on?

**Comment by jpmatsci** [comment]
it seems that changing lines 1086 and 1135 from 0.5f to 1.0f and rebuilt and the other stuff back too which seemed to help but the problem persists but now seems to reset on restart.

**Comment by aurelienpierre** [comment]
What exactly is the problem here ?

**Comment by jpmatsci** [comment]
I didn't see the new version at the time.  It appears to be fixed.  I could
not find the problem.

**Comment by johnny-bit** [comment]
> I didn't see the new version at the time.  It appears to be fixed.  I could
not find the problem.

Then let's close the problem :)
