### ISSUE TITLE
Timeline counts 61 minutes in an hour.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#4069]
**Describe the bug**
The timeline has an off-by-one error in its reckoning of minutes: the range of the minute field is 0 to 60, _inclusive_. For example, when moving the mouse rightward over a position representing noon, the displayed times progress `11h59` -> `11h60` -> `12h00`.

When the button is released over an xx:60 time, it gives the resulting malformed interval to collect-by-time and the view invariably comes up empty.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Fedora 31

**Comment by Mark-64** [comment]
Confirmed.
There are also other small bugs in the timeline GUI:
- fonts extremely small with HiDPI display (at least with Windows)
- when selection goes past end, the final date is 00:00:00, which leads to an invalid selection, date shoud stay fixed at the maximum range
- uders certain conditions, the selection always start from the minimum of the database range
I'm looking into those bugs.

**Comment by schwerdf** [comment]
While you have the hood open, would it be possible to render the timeline's dates in ISO 8601 format, as is done elsewhere in Darktable? The "dd/mm/yy" format is not generally used in the U.S. and I get easily confused by it.

**Comment by Mark-64** [comment]
See #4143 
Then coming to time formats, it is controversial. I don't know where you see the ISO 8601, but I see the dd/mm/yy format in image information window. Either way, it would confuse US or Europe users.
The real solution would be an option in DT preferences, but this is beyond my scope here, as I am just fixing bugs.
Plase open a feature request.

**Comment by AlicVB** [comment]
@Mark-64 : thanks for fixing that, as I'm quite busy hacking other parts atm...
@schwerdf : the main problem is that we use "hand-made" date to write date spans : ex: (01-10)/04/12 Of course it would be good to handle other date-time formats, but in this case, we'll have to deal with *all* of them and their variants... That's why I've decided to stick with the format I know. Now if someone comes with a fix for that, no pb ;)

**Comment by Mark-64** [comment]
@AlicVB 
If you are fixing other parts of the timeline, please have a look to my PR, as there are several fixes already, not only the 61 minutes

**Comment by schwerdf** [comment]
By "elsewhere in Darktable" I was referring to the pattern strings for collect-by-date and collect-by-time, which are fed directly to the database and thus use the ISO 8601 order ("yyyy:mm:dd").

I assumed that since these are generated from the timeline, it would be a simple matter to use them in the display as well, but looking at the code, I see the complication with the date spans.

**Comment by AlicVB** [comment]
@Mark-64 : I don't work on timeline currently, but on the rewrite of filemanager... So go ahead with your fix (and thanks) :)

**Comment by Nilvus** [comment]
@TurboGit : seems to have been fixed this day by merging of #4143 by @Mark-64. So could be closed.
