### ISSUE TITLE
V3.0: some function crash

### ISSUE THREAD

**Issue by ChrisRose2020** [darktable-org/darktable#4071]
I have installed V3 yesterday on a Win 10 system. Workes well but when I activate some functions it immediately closes the entire app without any hint.
This happens for the correction of the camera objective or with the function to mark the overlighted areas in the pic.

**Comment by MStraeten** [comment]
you know the bug report template? (click new issue --> Bug report) It makes sense to give some more informations so someone can try to reproduce the issue.

**Comment by aurelienpierre** [comment]
That issue is incredibly unhelpful. Please learn to properly report bugs. This should be closed.

**Comment by aurelienpierre** [comment]
Your report is not in a shape to be used for debugging. Please [learn how to properly reports bugs](https://github.com/darktable-org/darktable/wiki/Reporting-bugs-and-issues). This issue will be closed in 2 weeks if it has not been improved according to the guidelines.

**Comment by johnny-bit** [comment]
Lack of necessary info/response = issue close
