### ISSUE TITLE
artefacts when using low or high pass filters

### ISSUE THREAD

**Issue by epeeist** [darktable-org/darktable#4077]
**Describe the bug**
When using DT 3.0 with a long exposure image I get artefacts on the exported JPG image if I use low or high pass modules.

**To Reproduce**
I have attached the XMP file for an image that gives the artefacts, this gives the sequence that reproduces the issue

**Expected behavior**
The black areas should not have the white lines on them

**Screenshots**
![salfordQuaysArtefacts](https://user-images.githubusercontent.com/2912394/72153267-55c7cf80-33a5-11ea-9af9-6926743668c7.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.0
 - OS: OpenSuse Linux Tumbleweed
 - OpenCL activated or no? No
 - Which graphics card and driver version? Intel Corporation Iris Pro Graphics 580

**Additional context**
 - Can you reproduce with another Darktable version? Untried
 - Can you reproduce with a RAW or Jpeg or both? Only RAW file available
 - Are the steps above reproduce with a fresh edit (removing history)?
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? No
 - Is the issue still present using an empty/new config-dir? Untried

I can supply the NEF file, but it is from a D850 and is quite large

**Comment by junkyardsparkle** [comment]
There doesn't seem to be an attached XMP (it will need to be compressed or have a ".txt" extension added in order to upload).

**Comment by elstoc** [comment]
Pretty sure it's the one attached to post 3 of this thread: https://discuss.pixls.us/t/strange-artefacts-in-dt-3-0-export/15684

**Comment by epeeist** [comment]
> Pretty sure it's the one attached to post 3 of this thread: https://discuss.pixls.us/t/strange-artefacts-in-dt-3-0-export/15684

It is, I can attach it here if you want to keep everything together.

**Comment by jenshannoschwalm** [comment]
This looks very much like "overstressing" the module and thus generating artefacts from noise and not like a bug at all. You really can't expect anyone to check if there is no image and corresponding xmp...
Either close this or share the image :-)

**Comment by epeeist** [comment]
> This looks very much like "overstressing" the module and thus generating artefacts from noise and not like a bug at all. You really can't expect anyone to check if there is no image and corresponding xmp...

As I said, the original image was from a Nikon D850, which means the RAW files are on the order of 48MB, this is beyond the limit that is accepted on the site. I can split it if the developers want me to.

As for the XMP file, here it is with a .txt suffix added. 

[_CTW0132.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/4050650/_CTW0132.NEF.xmp.txt)

**Comment by jenshannoschwalm** [comment]
Why don#t you use any file-sharing service ...

**Comment by epeeist** [comment]
> Why don#t you use any file-sharing service ...

Fine, here it is on WeTransfer - https://wetransfer.com/downloads/8640a094bf47730ca4ce1bbf7ab774c920200112135653/a8c21548e30da2bf6eae45dd21d7e37220200112135653/e8725c

**Comment by jenshannoschwalm** [comment]
tried and can't reproduce. What export settings are you using?

**Comment by epeeist** [comment]
> tried and can't reproduce. What export settings are you using?

8 bit JPG, 95% quality

Max size 2048x2048
Allow upscaling, high quality resampling
sRGB, relative colorimetric

**Comment by jenshannoschwalm** [comment]
Still can't reproduce on current git master. Just exporting to jpeg, what about png or tiff? Do resampling matter? Can you see those artefacts on all image viewers or gimp?

**Comment by epeeist** [comment]
Try it with this XMP file. 
[_CTW0132_02.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/4050807/_CTW0132_02.NEF.xmp.txt)

I have tried it with PNG files, both 8 and 16 bit. I get the same artefacts.

I am a KDE user, I see the artefacts both in GIMP and Gwenview.

**Comment by jenshannoschwalm** [comment]
Still can't reproduce really. Strong artefacts resulting from using modules in a very strange way. But **not** the lines you describe. This is what i get with exactly your sidecar. 
![_CTW0132](https://user-images.githubusercontent.com/50982232/72223629-45fce680-3571-11ea-8f2e-92310e9dc117.jpg)

Don't know how to help you right now. Have you tried to compile darktable from master and see what you get?

**Comment by epeeist** [comment]
At this point we are probably down to the tool chain used to build the executable.

Close this for now, I will raise it again if I can get something more reproducible. 

In any case the new tone equaliser looks better for improving shadows than a low pass filter.

**Comment by jenshannoschwalm** [comment]
Thanks for closing, i will remember this issue and have my eyes open :-)

Yes the tone equalizer is really good, also when trying you latest xmp i saw you had really strange settings for filmic rgb especially for the darks. Probably "overstreched". 

Are you aware of the parametric masks? Keep going and have fun

**Comment by epeeist** [comment]
> i saw you had really strange settings for filmic rgb especially for the darks. Probably "overstreched".

I know it is after the issue has been closed, but could you possibly say which ones?

> Are you aware of the parametric masks? 

Yes, are you suggesting masking off the dark area and applying filmic to this separately?

**Comment by jenshannoschwalm** [comment]
Do you know aurelianpierre excellent videos about related stuff? It helped me a lot when i changed to dt master some time ago.

Yes, you can apply any modules effect depending on the parametric mask, for example the luminance.
