### ISSUE TITLE
[Filmic RGB] User entered value not allowed 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4078]
darktable-3.1.0+326~g250fafcca-win64

Just playing with Filmic RGB.

On the scene tab for my pic the black relative exposure has a range from -16 to -3.
I move to the slider to the extreme left at -16.
Then On right clicking and entering something like -20.00 does not stick.
I don't know if I am allowed to enter values beyond the range.

![image](https://user-images.githubusercontent.com/1119439/72157350-b541d180-33dd-11ea-8acc-8cc803a954bf.png)

**Comment by Egocentrix** [comment]
Can confirm that in the source the black value is clamped between -16 and -0.1. Makes sense physically, because there are no(/very few) cameras capable of that dynamic range.

**Comment by MStraeten** [comment]
you're allowed to enter the value, but darktable but darktable sets it to -16.

**Comment by aurelienpierre** [comment]
There is no camera out there that handles more than 15 EV of dynamic range (says DxOmark), and also 14 bits raw files can't encode more than 14 EV (so I wonder where DxO gets its ratings…). 16 EV is just in case you are using 16 bits. But -20 EV is not sane.

**Comment by chhil** [comment]
Thank you all for the clarification, the explanation makes sense.
Can we get this information in the user guide?

**Comment by chhil** [comment]
One more question, so my G9 is said to have a dynamic range of 10 at most ISO's. Does it make sense to start at +5 and -5 on the white and black relative exposures?

**Comment by MStraeten** [comment]
Try it with several pictures taken in different conditions- if there’s a ‚one size fits all‘ setting resulting in a sufficient result, then you might define such preset for you. But in reality i doubt the main parts of a picture are exactly in the middle between black and white in any case and also not every image make use of the whole dynamic range ... so at least it doesnt matter.
The proper workflow ist to bring out the midtones of the main motive first and then adjust black and white according to it

**Comment by aurelienpierre** [comment]
@chhil I notice most of your issues are enquiries rather than bugs. Perhaps the mailing list is a better place to ask questions, and reserve the bug tracker for crashes and obvious misbehaviours.

**Comment by chhil** [comment]
I rarely ask for information here, wasnt sure if this was a bug or not, most of my tickets are crash or bug related.

**Comment by jenshannoschwalm** [comment]
What about closing this "issue"?
