### ISSUE TITLE
local contrast / local laplacian broken

### ISSUE THREAD

**Issue by blitzgneisserin** [darktable-org/darktable#4080]
**Describe the bug**
dt 3.1 displays wrong/different colors than in the exported image
This issue has been already reported several times - apparently there was an attempt fix it but now the result is worse than before - in dt 2.6 the colors were correct when the top/bottom/left/right panels were hidden at 100% view, now all zoom levels are wrong, with and without panels, including fit to screen view.

**To Reproduce**
1. open a photo, disable base curve
2. apply filmic
3. apply local contrast in local laplacian mode, choose a very high detail value, e.g. 400%
4. switch between fit to screen and 100% view, hide and unhide the top, bottom  left or right "panel" (which results in a smaller or larger preview) and compare the colors
5. export the photo, open it in an image viewer and compare carefully with the photo open in dt

**Expected behavior**
colors should always look the same at all zoom levels

**Screenshots**
exported photo, fit to screen view in image viewer:
![screenshot_fittoscreeneported](https://user-images.githubusercontent.com/16564210/72168352-4bb9c700-33cd-11ea-8053-0b516e1f9a1d.png)

photo in dt, fit to screen view:
![screenshot_fittoscreendt](https://user-images.githubusercontent.com/16564210/72168421-70ae3a00-33cd-11ea-8b4f-8518eca581aa.png)
you can see that an area in the middle of the sky is brighter, however, the area around the woman's feet (left bottom corner) is a little less bright

photo in dt, fit to screen, with thumbnails:
![screenshot_fittoscreenwiththumbs](https://user-images.githubusercontent.com/16564210/72168762-15307c00-33ce-11ea-9efb-e5d839a34b49.png)
here you can see that the whole sky is the same as in the exported image, but the botto left corner is brighter

finally screenshots at 100% view of the exported photo and the photo open in dt, I think you can see the difference, so no comments here
![screenshot_100percentexported](https://user-images.githubusercontent.com/16564210/72168982-853f0200-33ce-11ea-84b7-07c461520940.png)

![screenshot_100percentdt](https://user-images.githubusercontent.com/16564210/72169233-05656780-33cf-11ea-877f-aa13f82be160.png)

![screenshot_100percentexported2](https://user-images.githubusercontent.com/16564210/72169308-24fc9000-33cf-11ea-931b-a1cc4402e7ab.png)

![screenshot_100percentdt2](https://user-images.githubusercontent.com/16564210/72169671-d8fe1b00-33cf-11ea-8973-126cb49c78c3.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.1 (git master, deb-package from Opensuse), 3.0
 - OS: Debian Bullseye
 - OpenCL active and inactive
 - Nvidia MX250, driver Nvidia 430

**Additional context**
Sorry to report this again, nevertheless thanks for the attempt to fix. I thought it is important to report that there is a different behaviour now.
I can provide the raw + sidecar if necessary.
Maybe one more thing: The screenshots were taken on an external BenQ screen, I also checked on my internal screen, there the result is different, but the previews are not correct/identical with the exported photo either, I think it is exactly the other way round, the brighter areas are darker and the darker areas are brighter. It apprears to be really strange...

**Comment by aurelienpierre** [comment]
>  colors should always look the same at all zoom levels

Not possible. Won't fix. 

> The screenshots were taken on an external BenQ screen, I also checked on my internal screen, there the result is different, but the previews are not correct/identical with the exported photo either, I think it is exactly the other way round, the brighter areas are darker and the darker areas are brighter. It apprears to be really strange...

That sounds like a colour management issue on your desktop/image viewer.

**Comment by blitzgneisserin** [comment]
What I have not tried yet: choosing sRGB for my screen even though it is (approximately) AdobeRGB. I will do that now but so far I used the profiles shipped with dt 3.1 (AdobeRGB and sRGB), so there might be something wrong with those?

**Comment by blitzgneisserin** [comment]
Well I just tried. Same as before, i.e. same direction, only that the differences are even more obvious. It's logical since contrast and saturation are too strong when using a profile that is smaller than the screen's color space.

**Comment by aurelienpierre** [comment]
Are you absolutely sure that your external image viewer is properly color-managed ?

The problem I suspect is not with the ICC profiles themselves, but with the image viewer you are using that might use a different profile than darktable.

Also, is your BenQ monitor calibrated in hardware (with the Windows XRite app) ? If so, you could have 2 colour calibrations on top of each other (one software, and one hardware in the monitor chip).

**Comment by blitzgneisserin** [comment]
Lximage is not color managed at all but it shows correct colors if the photo and the screen have the same color space which is in my case AdobeRGB.
Here is a comparison with RT (exported photo opened in RT).
![screenshot_dt_100p](https://user-images.githubusercontent.com/16564210/72183924-79b00300-33ef-11ea-9efe-22ae0bf51067.png)
![screenshot_rt_100p](https://user-images.githubusercontent.com/16564210/72183925-79b00300-33ef-11ea-9bcd-29d1f26a21fd.png)

The only workaround I see  for myself is not using detail values above 300%.

I re-calibrated and profiled my screen before writing this report. And I just checked my color management settings again. My apps are not using different profiles.

Well, just thought this might be useful info. dt 3.1 certainly behaves differently here than dt 2.6.

**Comment by aurelienpierre** [comment]
> Lximage is not color managed at all but it shows correct colors if the photo and the screen have the same color space which is in my case AdobeRGB.

Not colour managed usually means it defaults to uncorrected sRGB. So that confirms you have an issue with your setup. There is some wrong gamma going on, maybe the gamma table of the video card being used in addition of the profile TRC.

Can you try some properly managed desktop environment like Gnome or KDE ? Yours looks like some low-end LXQT or XFCE, these are barely suitable for graphics arts.
