### ISSUE TITLE
Multiprocessing doesn't work for darktable-cli

### ISSUE THREAD

**Issue by pixelgun-dev** [darktable-org/darktable#4081]
**Describe the bug**
I have a sequence of about a 1000 CR2 image which I need to convert to TIFF16. The following command line works:

```
darktable-cli input_image.CR2 colorcard.xmp output.tiff --core --conf plugins/imageio/format/tiff/bpp=16
```

But when I want to execute that command in parallel I am getting the following error:

```
[init] the database lock file contains a pid that seems to be alive in your system: 31531
[init] database is locked, probably another process is already using it
ERROR: can't acquire database lock, aborting.
```

Here is my python code:

```python
#!/usr/bin/env python3

import glob
import shlex
import subprocess
import multiprocessing as mp

from multiprocessing import Pool


def call_proc(cmd):
    subprocess.run(shlex.split(cmd), stdout=subprocess.PIPE, stderr=subprocess.PIPE)


app = '/Applications/darktable.app/Contents/MacOS/darktable-cli '
xmp = ' colorcard.xmp '
opt = ' --core --conf plugins/imageio/format/tiff/bpp=16 --conf plugins/imageio/storage/disk/overwrite=true  --library /tmp/darktable.db'

raw_images = glob.glob('indata/*')

procs = []
for raw_image in raw_images:
    tif_image = raw_image.replace('.CR2', '.tif').replace('indata', 'outdata')
    cmd = app + raw_image + xmp + tif_image + opt
    procs.append(cmd)

pool = Pool(mp.cpu_count())
pool.map(call_proc, procs)
pool.close()
pool.join()
```

**Platform:**
 - Darktable Version: darktable-cli 3.0.0
 - OS: macOS Mojave 10.14.3 (18D42)
 - NVIDIA GeForce GTX 680MX 2048 MB

**Comment by jenshannoschwalm** [comment]
dt does **not** support multple instances so the database is locked :-)

**Comment by pixelgun-dev** [comment]
Too bad, but thanks for getting back so quickly.

**Comment by bobobo1618** [comment]
I had the same problem but found a solution. It actually does support multiple instances, the problem is that it tries to lock `data.db`. If you pass `--apply-custom-presets false` to `darktable-cli`, it doesn't need to load data from `data.db`, so doesn't lock `data.db`.

The downside of course is that you can't use custom presets you have stored in `data.db`.
