### ISSUE TITLE
darkroom 'loading image' message blanks screen

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4085]
In darktable 2.6, I often made a couple of different edits in duplicate files and then was able to easily compare them by navigating between images (using space or backspace). In the current master build, a new 'loading page' has been added which essentially blanks the screen while the next image is being loaded and presents a 'loading image' message on-screen.

Unfortunately the blanking of the screen also blanks my memory of what was there before, meaning I now have to take a snapshot or exit into the lighttable to do any comparisons.

Please can it be changed back to the previous behaviour, i.e. so that the previous image remains on-screen until the next is loaded. The 'loading image' message is still helpful (so we know darktable is doing something) so should probably be retained.

**Comment by elstoc** [comment]
I think it's the changes to darktable.c in https://github.com/darktable-org/darktable/commit/3e7449ccf0a15175294c87b1d1e803a666c42619

**Comment by jenshannoschwalm** [comment]
The new behaviour is intentional. Why not use one of the tools that are meant for comparing like culling mode or others.

**Comment by elstoc** [comment]
I can. It was just very useful to be able to do a quick forward/backward mid-edit without exiting to another mode and it would be nice to have it back. I'm using snapshots at the moment but the other methods are a lot more clicks for the same job.

**Comment by AlicVB** [comment]
Although I understand your use case, it has been done on purpose, because it can be really confusing for images with heavy modules on (or with low power computers). Not to speak about malformed raw files...

As you speak about duplicates, have you tried the duplicate module ? It has exactly the feature you want...

**Comment by elstoc** [comment]
I have tried it but found it doesn't render the same as the normal darkroom view, especially when pixel-peeping. For example I just took an edit, duplicated it, and then used the duplicate module to flip between them (identical history stacks) at 100% zoom. No matter which duplicate I start from, the currently loaded image is lighter than the duplicate and I think the overall contrast might be different too.

**Comment by mkunzBGC** [comment]
Like @elstoc I am missing the old behaviour. In addition to making comparisons harder in darkroom mode, the grey loading screen means that the user's eyes have to adapt two times when switching to the next image to edit, making the procedure more exhausting than it has to be.
If you are convinced that some users are confused by the old loading behaviour, would you mind to make the grey loading screen optional?

**Comment by johnny-bit** [comment]
I do agree with @elstoc and @mkunzBGC - just recently I had to do visual compare between couple images and really would love to have residual image instead of blank between edits...

Maybe please make loading image message optional? Please?
