### ISSUE TITLE
Update Lua API doc for Image flags

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4086]
**Describe the bug**
When importing a new folder, not all image flags (visible in image information) are set correctly.
In particular, the flag "RAW", is not set on import, but only when opening image in darkroom.
This causes the property image.is_raw in lua to malfunction (see issue 209 in lua scripts) and maybe other effects.
Other flags might be incorrect too.

**To Reproduce**
Import a new folder, never imported before, with a few images.
do no enter in darkroom.
see the RAW flag (fifth from the left) not set in the image information module in the left panel
now open one image in darkroom. The RAW flags is set
go back in lighttable, the flag RAW is now correct for the image opened in darkroom

**Expected behavior**
The image flags should be set correctly

**Screenshots**
![Cattura20](https://user-images.githubusercontent.com/43290988/72205250-21294600-3481-11ea-8492-2d9a3949bf79.JPG)

**Platform (please complete the following information):**
Tested with DT 3.1 master in Windows 10 and Ubuntu 19.10

**Additional context**
As I finally managed to setup Darktable in Eclipse under Windows, I could run the debugger, and it seems to me that the only place where the RAW flag is set is in dt_imageio_open_rawspeed() in imageio_rawspeed.cc, but that function is not called when importing images in lighttable. 
It is only called when opening in darkroom and there the flags are set correctly.

**Comment by aurelienpierre** [comment]
Flags are only debug stuff that got added into the UI for some reason and never got removed. I don't think it's relevant anywhere.

**Comment by Mark-64** [comment]
Well at least it is relevant in LUA, there is a specific image property for it in the API. 
You want to know if an image is raw (withouch checking the filename extension) to allow or not certain operations, at least this what I tried to do in one script, and there I found the issue.

**Comment by jenshannoschwalm** [comment]
For performance reasons (i think) importing into the database reads exif data & a few more things from the sidecars. Some flags like those detected by dt_imageio_open_rawspeed() or other loaders depending on the file data. This costs a lot of time so it's done when opening in the darkroom.

So if you want to use a lua script you should start a develop before using such flags (ldr, hdr, raw ...)

**Comment by Mark-64** [comment]
Ok, that's the behaviour I observe and what I see from the code, so strictly speaking it should not be considered a bug.
I wonder if those flags can be inferred from exif data, from a quick look it seems not.
At least the LUA API documentation should be updated

**Comment by wpferguson** [comment]
The flags also get updated when the thumbnail is generated, so it's not necessary to do an edit to force them to update.

I'll add a warning to the manual about checking the raw flag after an import without a thumbnail generation or edit.
