### ISSUE TITLE
retouch module masks won't show up macOS

### ISSUE THREAD

**Issue by concealedResonances** [darktable-org/darktable#4090]
retouch modules masks won't show up until the module is reloaded on macOS 10.15.2 on Darktable 3.0.0

**Comment by MStraeten** [comment]
Without a detailed description what exactly is happening it seems to be the default behaviour: 
as long as the retouch tool shape icon is highlighted it is in continuous add mode and doesnt show up already created shapes. Just click on it when you finished  and the shapes will be shown.

**Comment by concealedResonances** [comment]
@MStraeten wasn't like that on previous version, that's what got me confused I guess. I just tried now and discovered that when I right click after adding the mask it will show up right away. Sorry for wasting your time.

**Comment by StefanDieke** [comment]
While @concealedResonances revealed the solution for the general problem, I think it's at least irritating that clicking on the "edit-arrow" icon (for which the helping line states something like "showing and editing of forms in the current size" [my translation from the german version]) does neither show the forms nor switch to editing.
