### ISSUE TITLE
.cube file not Loading in LUT 3D module

### ISSUE THREAD

**Issue by concealedResonances** [darktable-org/darktable#4091]
**Describe the bug**
Can not load .cube files in the LUT 3D Module, try with at least 20 of them but not luck

**To Reproduce**
1. Go to Lut 3D module
2. Click on folder icon
3. go to Users/~/Library/Application\Support/Proapps/Custom\LUTs/
4. load any .cube file that you have saved
5. nothing happens

**Expected behavior**
the LUT should be applied to the image, but nothing changes

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: macOS 12.5.2
 - OpenCL activated
 - built in (Intel Iris Graphics 6100)

**Additional context**

 - Can you reproduce with another Darktable version? 
no, its a new module so I can't 
 - Can you reproduce with a RAW or Jpeg or both?
both
 - Are the steps above reproduce with a fresh edit (removing history)?
yes

**Comment by phweyland** [comment]
HI @concealedResonances , if you deactivate OpenCL, is that the same ?

**Comment by concealedResonances** [comment]
@phweyland yes

**Comment by phweyland** [comment]
> go to Users/~/Library/Application\Support/Proapps/Custom\LUTs

Have you set up the LU3D folder in preferences, exit dt and enter again ?

**Comment by concealedResonances** [comment]
@phweyland all you asked yes but no success. But I removed/reinstalled darktable and worked, thank you!

**Comment by phweyland** [comment]
> But I removed/reinstalled darktable and worked, thank you!

Great ! Thanks.
