### ISSUE TITLE
Wiki build instructions missing Lua dependency for Ubuntu

### ISSUE THREAD

**Issue by maresb** [darktable-org/darktable#4094]
**Describe the bug**
After following the instructions from [Install from source](https://www.darktable.org/install/#source) under Ubuntu 18.04, I get a build which does not support Lua.

**To Reproduce**
1.  Follow the link from the installation instructions page to the [Wiki](https://redmine.darktable.org/projects/darktable/wiki/Building_darktable_22)
2.  Install the minimal and optional dependencies listed under Ubuntu 17.04 and 17.10.  (Note: the same dependencies seem to work for 18.04, so you could add "18.04" to the heading as well.)
3.  Run `build.sh` (with no additional options) from `darktable-3.0.0.tar.xz`

**Expected behavior**
Since I installed the optional dependencies, I would expect my Lua scripts to work, but they do not.  Reviewing the build logs, I see
```
-- Checking for one of the modules 'lua53;lua5.3;lua-5.3;lua'
-- Lua support: System library for lua 5.3 not found (to use darktable's version use -DDONT_USE_INTERNAL_LUA=Off)
```
As per [this discussion](https://discuss.pixls.us/t/compiling-darktable-with-lua-support/10872/17?u=maresb), I resolved the issue by installing `liblua5.3-dev`.  (Note: the `lua5.3-dev` package mentioned in the link seems to be short for `liblua5.3-dev` because `apt-get` reports `Note, selecting 'liblua5.3-dev' for regex 'lua5.3-dev'`).  

Apparently, this issue could easily be resolved by adding `liblua5.3-dev` to the list of optional dependencies for Ubuntu 17.04, 17.10, and adding the 18.04 version number to the heading.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Ubuntu 18.04

**Comment by aurelienpierre** [comment]
The wiki page you mentionned is outdated.

To automatically install dependencies on Debian-based OS, use `sudo apt-get build-dep darktable`.

**Comment by maresb** [comment]
> The wiki page you mentionned is outdated.

That is exactly my point.  The wiki is linked from https://www.darktable.org/install/#source so it *is* currently the "official" instructions.

I'd much rather somehow fix this myself than take up your time, so I tried to register on the developer wiki, but the "Register" link fails.  :(

(Note: in Ubuntu, source repositories are disabled by default.  With your command, one gets the error `E: You must put some 'source' URIs in your sources.list` until they are enabled, e.g. via "Software & Updates".  Your tip about `apt-get build-dep` is very useful, so it would be great if we could get that documented.)

**Comment by aurelienpierre** [comment]
Ah. I guess we could recreate a wiki here on Github then, and change the link on the website.

**Comment by maresb** [comment]
I added a bunch of notes on the wiki about building from 18.04.  There are also links on the GitHub wiki back to the Redmine wiki.  I hope that makes it ready to change the link on the website now.

**Comment by maresb** [comment]
* the GitHub README now points to the GitHub wiki,
* the website still points to the Redmine wiki.

If editing the website is difficult, a lazy workaround would be to add a link from Redmine to the GitHub wiki.

The GitHub wiki is publicly editable.  On one hand this is great for collaboration.  On the other hand, there is little to stop random people from injecting malicious commands which might then get copy-pasted into a terminal.  I'm not sure what is the best strategy here.
