### ISSUE TITLE
hierarchicalSubject tags should use <rdf:Bag>, not <rdf:Seq>

### ISSUE THREAD

**Issue by raymondjohnson** [darktable-org/darktable#4095]
**Describe the bug**

When I open an image in Digikam that has been tagged using Darktable, my hierarchical tag structure flattens out and every level of the branch and leaves are selected. I believe this is because Darktable structures the tags in the xmp this way:

```
<lr:hierarchicalSubject>
  <rdf:Seq>
    <rdf:li>Country|State|City</rdf:li>
    <rdf:li>People|First Last</rdf:li>
  </rdf:Seq>
</lr:hierarchicalSubject>
```
while Digikam structures the tags this way:

```
<lr:hierarchicalSubject>
  <rdf:Bag>
    <rdf:li>Country|State|City</rdf:li>
    <rdf:li>People|First Last</rdf:li>
  </rdf:Bag>
</lr:hierarchicalSubject>
```

The `<rdf:Seq>` vs. `<rdf:Bag>` makes all the difference, at least in my testing. Since the sequence of the lines doesn't matter for the tags (not to be confused with the sequence of tags *within* each line), I believe rdf:Bag is the correct choice here. (And it is apparently what Lightroom and Exiftool use, as well.)

**To Reproduce**

To see for yourself, use Digikam to open an image and sidecar tagged with Darktable. You will likely need to use the "Reread metadata from image" option from the Item menu. The hierarchical tags will appear flattened out, unless you already have those tags in Digikam. They'll also appear selected at every level of the hierarchy, which I believe may have been the issue behind [a problem discussed on darktable-dev in 2017](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg02326.html). To see Digikam import tags correctly, manually edit the xmp *before* the import and change `<rdf:Seq>` to `<rdf:Bag>`. In my tests, this correctly imported the hierarchy of the tags and left only the leaves selected.

Applying the tags in Digikam switches the xmp to `<rdf:Bag>` but re-importing the file again into Darktable switches it back to `<rdf:Seq>`.

For these tests, I've been using Darktable 2.6.0 and Digikam 5.9.0 on Pop OS! 19.10.

**Comment by phweyland** [comment]
> The `<rdf:Seq>` vs. `<rdf:Bag>` makes all the difference,

In dt the job is made by exiv2 if I'm not mistaken. 
On this [Exiv2 page](https://www.exiv2.org/tags-xmp-lr.html) we have the same <rdf:Bag> ...
I'll try to look at that.

**Comment by phweyland** [comment]
I've checked in dt code that data are written in xmpData:

`xmpData.add(Exiv2::XmpKey("Xmp.lr.hierarchicalSubject"), v2.get())`;

and then retrieve everything from xmpData before writting xmpPacket to xmp file:
```
Exiv2::XmpParser::encode(xmpPacket, xmpData,
       Exiv2::XmpParser::useCompactFormat | Exiv2::XmpParser::omitPacketWrapper) 
```

I've read that digikam also use exiv2 to treat metadata. Is that done differently ?

**Comment by phweyland** [comment]
exiv2 version is 0.25-4 on my machine (Debian).

**Comment by aurelienpierre** [comment]
Should be fixed in master. Reopen if it is not.
