### ISSUE TITLE
Different behaviour of base curve in Darktable 3.0

### ISSUE THREAD

**Issue by viktorkrasovsky** [darktable-org/darktable#4100]
Hi, I'm concerned that the Darktable 3.0 produces different NEF file rendering results than it was in 2.6.x. I know that with filmic RGB you guys want to make something revolutionary in RAW editing, but there are situations, where this new approach does not work. E.g. I'm doing flash and mixed (flash and ambient) lighting portraiture.
I watched some of Darktable 3.0 workflow videos, they make sense in theory. But practically I can't get natural skin tones anymore either by using the old Base curves module nor via filmic RGB. It worked far better in 2.6.x with the default preset for my camera. The white balance module behaves also different because in 2.6.x I was able to successfully use white balance presets (flash has almost consistent color temperature) as a solid starting point and now I can't use it in same way in 3.0. Colors are strange.
Is it possible to add kind of legacy mode in Darktable settings to make the camera specific base curve presets work exactly as they did in 2.6.x? Or is there a way to modify the base curve for my camera to make it work exactly as it did in the 2.6.x?

**Comment by timur-davletshin** [comment]
I believe colors has got nothing to do with basecurve which is just tone reproduction. Until developers switched on preserve color option... Try to disable it and check your input color profile. In my case it is identical to old behavior.

@TurboGit as I said it in #3693 and #3677 that kind of changes is confusing for most users. I'm sure similar reports will follow.

**Comment by aurelienpierre** [comment]
Please provide images, screenshots, and possibly faulty raw + XMP to show exactly what your problem is.

**Comment by Grizzly1701** [comment]
Have you set the preserve colors in the base curve module on "none" instead of "luminance" as it is set by default?

**Comment by crbble** [comment]
Was there a hint somewhere that this behaviour has changed that I overlooked? 

I also ran into it and first I had to understand what is wrong, then try filmic RGB and then find this post to get the old behaviour.
