### ISSUE TITLE
Linux: libdarktable.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zakaria-chahboun** [darktable-org/darktable#4105]
### Darktable version 3.0.0 fails to launch.
_(i'm using OpenSUSE Tumbleweed)_

Invoking from a terminal results in this message:

`darktable: error while loading shared libraries: libdarktable.so: cannot open shared object file: No such file or directory`

The solution is:
add a link to the lib by:

**`ln -s /usr/lib64/darktable/libdarktable.so /usr/lib64/libdarktable.so`**

i hove to fix that in the next update 
Thanks
`

**Comment by aurelienpierre** [comment]
3.0 or current master ?

**Comment by parafin** [comment]
I very much doubt this is a darktable issue, because everything worked since ages. Most likely something is broken in build environment. How did you install darktable, can you link the package file directly?

**Comment by cryptomilk** [comment]
This is a bug in the %cmake macro of openSUSE Tumbleweed. I've created a fix you can find here:

https://build.opensuse.org/request/show/764183

**Comment by parafin** [comment]
closing since it's a downstream bug

**Comment by zakaria-chahboun** [comment]
> I very much doubt this is a darktable issue, because everything worked since ages. Most likely something is broken in build environment. How did you install darktable, can you link the package file directly?

sudo zypper in darktable

**Comment by zakaria-chahboun** [comment]
> This is a bug in the %cmake macro of openSUSE Tumbleweed. I've created a fix you can find here:
> 
> https://build.opensuse.org/request/show/764183

thanks
