### ISSUE TITLE
Improve the negative film inversion

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#4113]
## Problem

The current film inversion is very basic and applied before demosaicing and input profile. There are 2 cases of negative film processing in dt:

1. working on an high bit-depth TIFF from a film scanner,
2. working on a photograph of the negative taken with a DSLR in raw format.

For 1., the TIFF encoding RGB space needs to be decoded first (at least undoing the gamma, but possibly neutralizing the scanner color casts), for 2. the camera sensor needs to be profiled and neutralized in white balance and color casts first. Both cases need WB and input color profile before inversion, so the negative inversion should happen later in the pipe.

## Current work-around

![Capture d’écran du 2020-01-14 17-09-20](https://user-images.githubusercontent.com/2779157/72362673-df540600-36f3-11ea-8ee7-74b5f65321e1.png)

## Proposed method

Derivated from Kodak Cineon system, it aims at inverting a log-encoded (density-scaled) scan, then linearize it (sort-of) for better handling in the scene-linear pipe.

Here is the algo, designed for 10 bits integer encoding (to be adapted for floats):

1. Density(c) = -log10(dmin(c)/pixelValue(c))
2. densityEncoding(c) = s(c) * Density(c) * 500 + 95
3. linearized(c) = 10^densityEncoding(c) (or similar, see ref. 3.)

where :
* c is the colour channel
* dmin is the RGB colour of the film substrate
* 500 is an encoding gain adjusted for films having a density of 2.046, computed from 1023/2.046 = 500 (number of code values for current bit depth / film density)
* 95 is a black offset to adjust for compensating the variabilitiy of dmin, depending of film processing

So, user inputs are:

- film density,
- substrate colour,
- black offset

The encoding gain should be a constant if performing operations in float.

## References

- Thanks to Sidharth Sadhujan from Rochester Institute of Technology.
- http://www.digital-intermediate.co.uk/film/pdf/Cineon.pdf
- https://www.kodak.com/uploadedfiles/motion/US_plugins_acrobat_en_motion_education_sensitometry_workbook.pdf
- https://lists.gnu.org/archive/html/openexr-devel/2005-03/msg00009.html

**Comment by junkyardsparkle** [comment]
So, IIUC, the user would then end up using filmic RGB to "re-filmize" actual film scans? Love it. :-)

**Comment by aurelienpierre** [comment]
Not really, since the non-linear toe and shoulder of the film transmittance will be preserved. But, the option of inverting these toe and shoulders is still on the table, so you get a truly linearized (scene-referred) film scan

**Comment by junkyardsparkle** [comment]
> But, the option of inverting these toe and shoulders is still on the table, so you get a truly linearized (scene-referred) film scan

I don't know enough about film to know if this would be practical (seems like expanding the toe would get noisy?) but it sounds like fun in theory. So, what would be the recommended processing workflow following this module? Primarily just "color balance", or would a log curve also probably need to be re-applied at the end?

**Comment by aurelienpierre** [comment]
If you look at the algorithm, you will see it takes linear input and leave linear output, only doing inversion and tone mapping to anchor the RGB values to display white.  Once it's linearized, you do whatever you want as if it was digital raw. Although for me, film is a finished product, so my primarily use case for darktable in an analog workflow would be stains/dust/scratches removal, and possibly sharpening/denoising.

**Comment by laurencelumi** [comment]
Hi,

Not sure if this is the correct place to put this, but I thought I would start somewhere.

I have started hacking the negadoctor code to better reflect how the formula Derivated from Kodak Cineon system is implemented in the UI.

The current implementation hides or perhaps obscures the critical controls in the formula IMHO, and make it difficult to enhance.

I propose to change the UI implementation so that user has direct control, and the steps of the conversion are less opaque.

One feature that is impossible to control directly for example is the concept colour grading with of "printer lights".
