### ISSUE TITLE
Module "Retouch" - editing forms 

### ISSUE THREAD

**Issue by StefanDieke** [darktable-org/darktable#4116]
In the retouch module, to edit an existing form or source and target, it's necessary to fold and unfold the module. In other words source and target are not displayed and can not be accessed immediately after they have been created. 

It takes two times of hitting CTRL-Z to undo a single application of clone or heal. The same seems to be true for 'soften'. Although I can't see an effect taking place on the second CTRL-Z, it is only the third CTRL-Z which affects the action executed immediatley before applying soften.

I'm on version 3.1.0+342~g112559639

**Comment by MStraeten** [comment]
have a look at https://github.com/darktable-org/darktable/issues/4090

**Comment by StefanDieke** [comment]
Thank you for the pointer! I will continue in that other thread, which for some reason I missed although I searched for "retouch" before posting.
