### ISSUE TITLE
Wrong panning with drag and drop in darkroom when zoom > 100%

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#4117]
When you are zoomed < 100% in the darkroom, if you click on a pixel of the preview and drag & drop it elsewhere, that pixel ends up at the exact position where you dropped it, so the image is properly panned (so gesture amplitude == panning amplitude).

When you are zoomed >> 100%, if you do the same, the image will be panned by a very small fraction of the gesture you did, and the selected pixel will not land where you drop it.

I believe it's a wrong coordinates scaling somewhere in the code, that doesn't account for the zoom properly when zoom > 100%.

**Comment by TurboGit** [comment]
I cannot reproduce this issue. Maybe related to the DE you're using? I kind of remember some issue like that in some cases...

**Comment by aurelienpierre** [comment]
I'm using Gnome from Fedora.

**Comment by Nilvus** [comment]
Can't reproduce too. I'm on Gnome 3.34.2/Ubuntu 19.10. Works as expected and same way on all zooms.

**Comment by TurboGit** [comment]
GNOME Shell 3.34.3-1 from Debian. Really strange then.

**Comment by TurboGit** [comment]
Maybe related to #4152.

**Comment by Mark-64** [comment]
Works as expected on Windows 10
