### ISSUE TITLE
building 3.0 from tarbal requires libjasper.so.1

### ISSUE THREAD

**Issue by ljmdullaart** [darktable-org/darktable#4123]
**Describe the bug**

When building 3.0.0 from tarbal, the make fails at 30% because it cannot link libjasper.so.1. On the system, libjasper.so.4 is installed.

**To Reproduce**

make

**Expected behavior**

An error-free make.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  3.0.0
 - OS:  Slackware 15
 -  Not applicable
 -  Not applicable

**Additional context**

The build was successful after
sudo ln -s /usr/lib64/libjasper.so.4 /usr/lib64/libjasper.so.1

**Comment by parafin** [comment]
You need to show full output of cmake and make started from clean build directory.

**Comment by ljmdullaart** [comment]
ljm@verlaine[build]$ cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable/ ..
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found OpenMP_C: -fopenmp (Required is at least version "4.0") 
-- Found OpenMP_CXX: -fopenmp (Required is at least version "4.0") 
-- Is the target platform supported: 1
-- Found little endian system. Good.
-- Building SSE2-optimized codepaths: ON
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768
-- Performing Test C_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768 - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wframe-larger-than=32768 - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wstack-usage=32768
-- Performing Test C_COMPILER_UNDERSTANDS_-Wstack-usage=32768 - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wstack-usage=32768
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wstack-usage=32768 - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wlarger-than=524288
-- Performing Test C_COMPILER_UNDERSTANDS_-Wlarger-than=524288 - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wlarger-than=524288
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wlarger-than=524288 - Success
-- Looking for external programs
-- Found perl
-- Found intltool-merge
-- Found desktop-file-validate
-- Found LLVM 9.0.1
-- Found clang compiler - /usr/bin/clang-9
-- Found clang opencl-c.h header in /usr/lib64/clang/9.0.1/include
-- Will be able to test-compile OpenCL programs. Nice.
-- Missing jsonschema, problems in noiseprofiles.json might go unnoticed
-- Found xsltproc
-- Found xmllint
-- All external programs found
-- Found msgfmt to convert .po file. Translation enabled
-- Checking for -march=native support
-- Checking for -march=native support - works
-- Checking for -std=c++14 support
-- Checking for -std=c++14 support - works
-- Looking for OpenMP
-- Found OpenMP_C: -fopenmp (Required is at least version "4.0") 
-- Found OpenMP_CXX: -fopenmp (Required is at least version "4.0") 
-- Looking for OpenMP - found (system)
-- Looking for pugixml
-- Found Pugixml 1.70
-- Looking for pugixml - found (system)
-- Looking for JPEG
-- Looking for JPEG - found
-- Looking for ZLIB
-- Found ZLIB: /usr/lib64/libz.so (found suitable version "1.2.11", minimum required is "1.2.11") 
-- Looking for ZLIB - found (system)
-- The following features have been enabled:

 * OpenMP-based threading, used for parallelization of the library
 * XML reading, used for loading of data/cameras.xml
 * Lossy JPEG decoding, used for DNG Lossy JPEG compression decoding
 * ZLIB decoding, used for DNG Deflate compression decoding

-- The following OPTIONAL packages have been found:

 * LLVM (required version >= 9)
 * Gettext
 * XMLLINT, command line XML tool, <http://xmlsoft.org/>
   Used for validation of data/cameras.xml

-- The following RECOMMENDED packages have been found:

 * JPEG, free library for handling the JPEG image data format, implements a JPEG codec
   Used for decoding DNG Lossy JPEG compression
 * ZLIB (required version >= 1.2.11), software library used for data compression
   Used for decoding DNG Deflate compression

-- The following REQUIRED packages have been found:

 * OpenMP (required version >= 4.0), Open Multi-Processing, <https://www.openmp.org/>
   Used for parallelization of the library
 * Pugixml (required version >= 1.8), Light-weight, simple and fast XML parser, <http://pugixml.org/>
   Used for loading of data/cameras.xml

-- Checking for -std=c++14 support
-- Checking for -std=c++14 support - works
-- Found Glib 2.62.4
-- Found LibXml2: /usr/lib64/libxml2.so (found suitable version "2.9.10", minimum required is "2.6") 
-- Checking for one of the modules 'libsoup-2.2;libsoup2'
-- Found GIO 
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.10") 
-- Found Sqlite3 3.30.1
-- Found CURL: /usr/lib64/libcurl.so (found version "7.67.0")  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found JsonGlib 
-- Found OpenJPEG 
-- Found GraphicsMagick 
-- Does the compiler support __builtin_cpu_supports(): 1
-- Checking for -march=native support
-- Checking for one of the modules 'lua53;lua5.3;lua-5.3;lua'
-- Lua support: System library for lua 5.3 not found (to use darktable's version use -DDONT_USE_INTERNAL_LUA=Off)
-- Found Pugixml 1.70
-- Map mode: disabled, please install libosmgpsmap
-- No libcolord found, this build will lack the ability to get the screen profile from colord
-- Print mode: enabled
-- Found CURL: /usr/lib64/libcurl.so (found suitable version "7.67.0", minimum required is "7.56")  
-- Found recent CURL version to build piwigo.
-- no colord support for darktable-cmstest. not cool.
CMake Warning at doc/CMakeLists.txt:37 (message):
  the sources of the usermanual are missing so you won't be able to generate
  it.  if this is a release tarball then that's normal.

  please grab them from github if you want to work on the manual.


-- Configuring done
-- Generating done
-- Build files have been written to: /home/ljm/src/darktable/darktable-3.0.0/build
ljm@verlaine[build]$ make
[  0%] Updating version string (source package) - 3.0.0
[  0%] Built target create_version_gen
[  0%] Built target generate_version
[  0%] Built target locale_ja
[  0%] Built target locale_he
[  0%] Built target locale_ru
[  0%] Built target locale_es
[  0%] Built target locale_sl
[  0%] Built target locale_fr
[  0%] Built target locale_ca
[  1%] Built target locale_cs
[  2%] Built target locale_it
[  2%] Built target locale_hu
[  2%] Built target locale_da
[  2%] Built target locale_de
[  2%] Built target locale_nb
[  2%] Built target locale_nl
[  2%] Built target locale_pl
[  2%] Built target locales
[  2%] Built target validate-cameras.xml
[ 12%] Built target rawspeed
[ 12%] Checking validity of data/darktableconfig.xml
[ 12%] Built target validate_darktableconfig_xml
[ 12%] Built target generate_preferences
[ 12%] Built target generate_metadata
Scanning dependencies of target lib_darktable
[ 13%] Building C object src/CMakeFiles/lib_darktable.dir/version_gen.c.o
[ 13%] Linking C shared library libdarktable.so
[ 30%] Built target lib_darktable
[ 30%] Linking C executable darktable
/usr/bin/ld: warning: libjasper.so.1, needed by /usr/lib64/libGraphicsMagick.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_iccprof_destroy'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_writecmpt'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_create0'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_encode'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_decode'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_cleanup'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_iccprof_save'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_strtofmt'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_iccprof_createfromcmprof'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_init'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_addcmpt'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_matrix_destroy'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_destroy'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_stream_close'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_readcmpt'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_stream_memopen'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_image_getcmptbytype'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_stream_flush'
/usr/bin/ld: /usr/lib64/libGraphicsMagick.so: undefined reference to `jas_matrix_create'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/darktable.dir/build.make:150: src/darktable] Error 1
make[1]: *** [CMakeFiles/Makefile2:1841: src/CMakeFiles/darktable.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
ljm@verlaine[build]$

**Comment by parafin** [comment]
GraphicsMagick library is broken on your system, not darktable's issue.
