### ISSUE TITLE
Darktable doesn`t found pictures

### ISSUE THREAD

**Issue by MMRastatt** [darktable-org/darktable#4148]
**Describe the bug**
Darktable starts normally, but when I click in a directory, the error message comes up: "there are no images in this collection ....". Also comes an Error: "An unhandled exception occurred ...." 

![dt1](https://user-images.githubusercontent.com/59559811/72685355-a51aa800-3ae9-11ea-81ec-007ecc700247.JPG)

![dt2](https://user-images.githubusercontent.com/59559811/72685372-d1cebf80-3ae9-11ea-80b1-60265df52208.JPG)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Windows 10 64bit
 - OpenCL: off (cannot be activated) 
 - graphics card: Intel® HD Graphics 4600, Driver Version 20.19.15.5107

It doesn´t matter if they are jpg or raw, but some old picture directorys run normally. Adowngrade to darktable version 2.6.3. brought no success

The error file contains:

this is darktable 3.0.0 reporting an exception:

-------------------

Error occurred on Sunday, January 19, 2020 at 18:32:17.

darktable.exe caused an Access Violation at location 000000006362973E in module libdarktable.dll Writing to location 0000000000000428.

AddrPC           Params
000000006362973E 0000000000000000 000000000497D538 0000000000000000  libdarktable.dll!dt_image_import_internal  [D:/build/darktable/src/common/image.c @ 1182]
000000006368F30F 000000000497D538 00007FFB6DD39DA0 000000000FAAA7E0  libdarktable.dll!dt_film_import1  [D:/build/darktable/src/control/jobs/film_jobs.c @ 256]
000000006368F5FD FFFFFFFFFFFFFFFF 000000000FAAA810 000000000FAAA838  libdarktable.dll!dt_film_import1_run  [D:/build/darktable/src/control/jobs/film_jobs.c @ 33]
0000000063687BA7 0000000000000000 0000000000000000 0000000000000000  libdarktable.dll!dt_control_job_execute  [D:/build/darktable/src/control/jobs.c @ 304]
00000000636880E8 0000000004987520 0000000000000000 0000000000000000  libdarktable.dll!dt_control_work  [D:/build/darktable/src/control/jobs.c @ 323]
0000000064945092 0000000004846660 0000000000000000 0000000004987520  libwinpthread-1.dll!pthread_create_wrapper
00007FFB6DD5B04A 00007FFB6DDB06D0 0000000004987520 0000000000000000  msvcrt.dll!_beginthreadex
00007FFB6DD5B11C 0000000000000000 0000000000000000 0000000000000000  msvcrt.dll!_endthreadex
00007FFB6F4A7BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFB6F70CED1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.0.0.0
ntdll.dll   	10.0.18362.418
KERNEL32.DLL	10.0.18362.329
KERNELBASE.dll	10.0.18362.535
msvcrt.dll  	7.0.18362.1
libglib-2.0-0.dll	2.62.2.0
libintl-8.dll	0.19.8.0
libdarktable.dll
ADVAPI32.dll	10.0.18362.329
sechost.dll 	10.0.18362.267
RPCRT4.dll  	10.0.18362.476
GDI32.dll   	10.0.18362.1
win32u.dll  	10.0.18362.592
ole32.dll   	10.0.18362.113
gdi32full.dll	10.0.18362.535
libiconv-2.dll	1.16.0.0
combase.dll 	10.0.18362.449
msvcp_win.dll	10.0.18362.387
ucrtbase.dll	10.0.18362.387
USER32.dll  	10.0.18362.592
bcryptPrimitives.dll	10.0.18362.295
PSAPI.DLL   	10.0.18362.1
SHELL32.dll 	10.0.18362.535
cfgmgr32.dll	10.0.18362.387
shcore.dll  	10.0.18362.1
windows.storage.dll	10.0.18362.535
libwinpthread-1.dll	1.0.0.0
profapi.dll 	10.0.18362.1
libgcc_s_seh-1.dll
libstdc++-6.dll
powrprof.dll	10.0.18362.1
UMPDC.dll
libcairo-2.dll
shlwapi.dll 	10.0.18362.1
kernel.appcore.dll	10.0.18362.1
exchndl.dll 	0.9.2.0
cryptsp.dll 	10.0.18362.1
WS2_32.dll  	10.0.18362.387
libexiv2.dll
libgdk-3-0.dll	3.24.13.0
libgdk_pixbuf-2.0-0.dll	2.40.0.0
IMM32.dll   	10.0.18362.387
SETUPAPI.dll	10.0.18362.1
bcrypt.dll  	10.0.18362.267
libgmodule-2.0-0.dll	2.62.2.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.13.0
libcurl-4.dll
CRYPT32.dll 	10.0.18362.592
MSASN1.dll  	10.0.18362.1
WLDAP32.dll 	10.0.18362.449
comdlg32.dll	10.0.18362.418
libIlmImf-2_4.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
lua53.dll
libpango-1.0-0.dll	1.43.0.0
libpangocairo-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
libsecret-1-0.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
zlib1.dll
MSIMG32.dll 	10.0.18362.175
libfontconfig-1.dll
libfreetype-6.dll	2.10.1.0
libpixman-1-0.dll
mgwhelp.dll 	0.9.2.0
VERSION.dll 	10.0.18362.1
libpcre-1.dll
dwmapi.dll  	10.0.18362.267
gdiplus.dll 	10.0.18362.592
libgobject-2.0-0.dll	2.62.2.0
WINMM.dll   	10.0.18362.1
libcairo-gobject-2.dll
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.43.0.0
libltdl-7.dll
libsystre-0.dll
libbz2-1.dll
libexif-12.dll
COMCTL32.dll	6.10.18362.592
libbrotlidec.dll
libnghttp2-14.dll
libidn2-0.dll
libpsl-5.dll
WINSPOOL.DRV	10.0.18362.267
libatk-1.0-0.dll	2.34.1.0
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.43.0.0
libHalf-2_4.dll
libIlmThread-2_4.dll
libthai-0.dll
libgcrypt-20.dll	1.8.5.54720
libIex-2_4.dll
liblzma-5.dll	5.2.4.0
libzstd.dll
dbghelp.dll 	10.0.18362.1
libffi-6.dll
WINMMBASE.dll	10.0.18362.1
USP10.dll   	10.0.18362.476
libtre-5.dll
libbrotlicommon.dll
libgraphite2.dll
libdatrie-1.dll
PROPSYS.dll 	7.0.18362.267
OLEAUT32.dll	10.0.18362.535
dbgcore.DLL 	10.0.18362.1
IPHLPAPI.DLL	10.0.18362.1
libgomp-1.dll
libgio-2.0-0.dll	2.62.2.0
libopenjp2-7.dll
libexpat-1.dll
libssl-1_1-x64.dll	1.1.1.4
libcrypto-1_1-x64.dll	1.1.1.4
librsvg-2-2.dll
libfribidi-0.dll
libImath-2_4.dll
libunistring-2.dll	0.9.10.0
libgpg-error-0.dll	1.36.0.0
DNSAPI.dll  	10.0.18362.267
NSI.dll     	10.0.18362.449
libcroco-0.6-3.dll
CRYPTBASE.DLL	10.0.18362.1
rsaenh.dll  	10.0.18362.1
uxtheme.dll 	10.0.18362.449
clbcatq.dll 	2001.12.10941.16384
mswsock.dll 	10.0.18362.1
rasadhlp.dll	10.0.18362.1
fwpuclnt.dll	10.0.18362.207
MSCTF.dll   	10.0.18362.535
DEVOBJ.dll  	10.0.18362.387
WINTRUST.dll	10.0.18362.387
OpenCL.dll  	2.2.1.0
nvopencl64.dll	26.21.14.3160
dxcore.dll  	10.0.18362.1
nvapi64.dll 	26.21.14.3160
dxgi.dll    	10.0.18362.387
mscms.dll   	10.0.18362.267
USERENV.dll 	10.0.18362.387
ColorAdapterClient.dll	10.0.18362.267
IntelOpenCL64.dll	4.0.0.10094
intelocl64.dll	5.2.0.10094
task_executor64.dll	5.2.0.10094
OPENGL32.dll	10.0.18362.387
GLU32.dll   	10.0.18362.387
cpu_device64.dll	5.2.0.10094
igdrcl64.dll	20.19.15.5107
igdfcl64.dll	20.19.15.5107
igdmcl64.dll	20.19.15.5107
igdbcl64.dll	20.19.15.5107
igdusc64.dll	20.19.15.5107
nvcompiler.dll	26.21.14.3160
winhttp.dll 	10.0.18362.449
IconCodecService.dll	10.0.18362.1
WindowsCodecs.dll	10.0.18362.1
libpixbufloader-png.dll
icm32.dll   	10.0.18362.267
TextInputFramework.dll	10.0.18362.267
CoreMessaging.dll	10.0.18362.1
CoreUIComponents.dll	10.0.18362.207
ntmarta.dll 	10.0.18362.1
wintypes.dll	10.0.18362.449
iertutil.dll	11.0.18362.449
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libwebp-7.dll
libdisk.dll
libemail.dll
libfacebook.dll
secur32.dll 	10.0.18362.1
SSPICLI.DLL 	10.0.18362.1
libflickr.dll
libflickcurl-1.dll
libgallery.dll
libgooglephoto.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libborders.dll
libcacorrect.dll
libchannelmixer.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libmask_manager.dll
libmonochrome.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmodulegroups.dll
libmodulelist.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
libpixbufloader-svg.dll
explorerframe.dll	10.0.18362.418

Windows 10.0.18363
DrMingw 0.9.2

THX to all

**Comment by johnny-bit** [comment]
The crash like that is caused by things like antivir thining dt reading whole dir is "surelly a virus" and blocking access midway. Unblock darktable from (anti)virus control panel and/or mark darktable as "safe"
