### ISSUE TITLE
darktable-cli: _M_construct null not valid when trying to convert Canon CR2

### ISSUE THREAD

**Issue by lastzero** [darktable-org/darktable#4150]
**Describe the bug**

Converting a Canon CR2 to JPEG using `darktable-cli` fails with an unexpected error.

**To Reproduce**

Install darktable master build via download.opensuse.org:

```
sh -c "echo 'deb http://download.opensuse.org/repositories/graphics:/darktable:/master/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/graphics:darktable:master.list" && \
wget -qO - https://download.opensuse.org/repositories/graphics:darktable:master/xUbuntu_18.04/Release.key | apt-key add - && \
apt-get update && \
apt-get install darktable
```

Now try to convert our [CR2 test file](https://dl.photoprism.org/fixtures/testdata/import/raw/) with `darktable-cli`:

```
root@897c4e4c03c3:# darktable-cli IMG_2567.CR2 /tmp/test.jpg
WARNING: either your user id or the effective user id are 0. are you running darktable as root?
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

**Expected behavior**
`/tmp/test.jpg` should be created without error ("root" warning is ok)

**Screenshots**

Console only, no screenshot required.

**Platform:**
 - Darktable Version: `darktable-cli 3.1.0~git414.c2b133cfe`
 - OS: Linux (Ubuntu 18.04)

Dockerfile (might change as we are going to use an older version now):
https://github.com/photoprism/photoprism/blob/develop/docker/development/Dockerfile

**Additional context**

There's an XMP sidecar file available too, but it doesn't seem to change the behaviour. Other RAW files can be converted without error.

**Comment by lastzero** [comment]
Downgraded, darktable-cli **3.0.0** works as expected:

```
root@b3f6fb5df7c4# darktable-cli IMG_2567.CR2 /tmp/image.jpg
WARNING: either your user id or the effective user id are 0. are you running darktable as root?
[defaults] found a 64-bit system with 5068532 kb ram and 2 cores (0 atom based)
[defaults] setting very conservative defaults
[backup failed] /root/.config/darktable/data.db -> /root/.config/darktable/data.db-pre-3.0.0
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
[export_job] exported to `/tmp/image.jpg'
```

**Comment by sams96** [comment]
I think this is the same as #4142, does #4147 fix it for you?

**Comment by lastzero** [comment]
@sams96 Thanks for the quick feedback! Possible, but can't test it as I don't have a build environment (anymore). You're welcome to download our [CR2 test file](https://dl.photoprism.org/fixtures/testdata/import/raw/IMG_2567.CR2) to see if this is fixed (I'll trust you).

**Comment by sams96** [comment]
@lastzero It fixes it for me, and I got the same issue on the current master which is kind of weird because I couldn't reproduce #4142. 

Also I'd advise against running the master build because things do tend to break, you'll probably want to just stick with 3.0.0.

**Comment by lastzero** [comment]
Thank you! Closing this.
