### ISSUE TITLE
Crash on export in DT 3.1 git master

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4151]
DT 3.1 git master, built today. Nvidia 1060.
See the following image (free of copyright):

[https://drive.google.com/file/d/1VpPb7Lr-vCfuNeJFOxH0IPk9J8wOa0Pr/view?usp=sharing](url)
[DSC04344.ARW.xmp.txt](https://github.com/darktable-org/darktable/files/4084853/DSC04344.ARW.xmp.txt)

Export result is DT freeze on Ubuntu 19.10 and crash on Windows 10, with or without OpenCL, export format jpeg or tiff.
Here is the backtrace on Ubuntu 
[darktable_bt_QEKVE0_ubuntu.txt](https://github.com/darktable-org/darktable/files/4084862/darktable_bt_QEKVE0_ubuntu.txt)

and on Windows
[darktable_bt_VSY2E0_windows.txt](https://github.com/darktable-org/darktable/files/4084864/darktable_bt_VSY2E0_windows.txt)

**Comment by st-binder** [comment]
DT branch 3.0.x, built today crashes on export to disk too. Revert to Commit 4d0717dda60a9915a17dd0f5b06bdcbd2b4259ec works for me!
system: Arch Linux, AMD, AMD Polaris GPU

**Comment by Mark-64** [comment]
Reverting to 3.1.0+308~g2f82a6e43 works for me too, so it must be one of the latest commits

**Comment by junkyardsparkle** [comment]
I can't reproduce this so far myself on c2b133cfecaacea50f820660c5583d5f91d3e0d6, but possibly it's related to the stuff fixed in #4147?

**Comment by st-binder** [comment]
latest version of DT 3.0.x branch works fine for me, export doesn't crash DT anymore.

**Comment by Mark-64** [comment]
The crash is caused by corrupted metadata in library.db.
In a working version of the database I have this

![immagine](https://user-images.githubusercontent.com/43290988/72842043-e51f8d80-3c97-11ea-9dbc-c732e9def975.png)

while in the corrupted it's like this

![immagine](https://user-images.githubusercontent.com/43290988/72842176-231cb180-3c98-11ea-93f3-29ecfbbb7f94.png)

note the _NULL_ value instead of the string "(NULL)". This cause the function dt_metadata_get(imgid, "Xmp.dc.description", NULL) in exif.cc:1710 to return an invalid char* which provoke the crash.
 The problem is that I can't replicate the database corruption. If I import again the folder everything is OK, so most likely the corruption happened in one of the database upgrades.
Perhaps, just in case, I could insert a check to avoid to return a null pointer.

**Comment by Mark-64** [comment]
Also, the issue seems related to [https://github.com/darktable-org/darktable/commit/ab60895b43b8ac380914b1ccaffdda982985b594](url)

**Comment by phweyland** [comment]
> Also, the issue seems related to [https://github.com/darktable-org/darktable/commit/ab60895b43b8ac380914b1ccaffdda982985b594](url)

This link does not work for me. could you share another link ?

**Comment by phweyland** [comment]
Also, NULL value for metadata is not expected.
The only code I've found translating a null string to (null) value is lua code. Do you use lua plugins ?

**Comment by Mark-64** [comment]
Yes I do use lua plugins.
I was linking one of the recent commits on metadata, I can't remember which one as the link is dead.
Anyway i confirm that with the last fix there is no more crash.
I guess I can close this
