### ISSUE TITLE
Slow and sluggish preview panning in dt 3.1 git

### ISSUE THREAD

**Issue by jpenala** [darktable-org/darktable#4152]
**Describe the bug**
Panning a zoomed image is slow and unresponsive. Clear stutter in preview image and "rubberbanding" between the mouse cursor and preview image. Seems to be worst when around 50% zoom. 100% zoom performs okay. Zooming in and out (with mouse wheel) also feels less responsive than with 3.0.

**To Reproduce**

Zoom preview to ~50% and try panning. Compare with 3.0 release -> big difference.

**Expected behavior**
Responsive and stutter-free panning and zooming

**Screenshots**
Screen recording comparison of both 3.0 and 3.1, not sure how well the difference comes across in this (OpenCL off in both cases):
https://streamable.com/uv48s

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.1.0~git414
 - OS: Fedora Workstation 31 GNOME DE
 - OpenCL on could be slightly better, hard to say really. OpenCL on produces more single core spiking in 3.1 than 3.0 when panning.
 - NVIDIA Quadro w/ NVIDIA 440.44 driver

**Additional context**
 - Can you reproduce with another Darktable version?

No, 3.0 is smooth as butter. I'm referencing [this fix](https://github.com/darktable-org/darktable/pull/3957) for previously reported performance regression (maybe the panning regression is caused by something similar).

**Comment by TurboGit** [comment]
Can you go back in the history and find the first wrong commit ? Using git bisect could help. Thanks.

**Comment by jenshannoschwalm** [comment]
Is gmic enabled?

**Comment by jpenala** [comment]
How do I revert to a specific commit, I've been building just the latest?

How do I check if gmic is enabled? 

Also I assume the OBS pre-built dt master should have everything in order (gmic wise), because I get the panning lag with OBS build too...

**Comment by jpenala** [comment]
Nevermind I found instructions for commit checkout. I'll go through the old ones to see if I can catch anything.

**Comment by jpenala** [comment]
dt 3.1.0. +24 is the oldest build that compiles on my system, commits older than that result in build errors, so I can't test those. But git 24 has the same laggy panning behaviour (it also has the panel resize triggered ui lag which was already fixed). That should narrow it down considerably.

**Comment by jpenala** [comment]
Okay I got old commits to compile properly and I think I found the offending commit 3.1.0 +12: [f75c620 (Merge branch 'iso-12646')](https://github.com/darktable-org/darktable/commit/f75c620c21467ab91b33ae6ad52a2d6331fd1bb3)

The [previous commit](https://github.com/darktable-org/darktable/commit/d7274baacf7278f6aed74a9be4fec96ec36e42e0) is smooth, after building f75c620 it gets laggy.

**Comment by jpenala** [comment]
I changed every CAIRO_FILTER_BEST to CAIRO_FILTER_FAST in darkroom.c and compiled the latest build with that. Everything is now smooth as it is with 3.0, panning image preview is a breeze. So it's definitely about the cairo filtering.  Is there some benefit of the BEST vs FAST, I for one cannot see any obvious increase in image quality at least?

**Comment by jenshannoschwalm** [comment]
@jpenala this is definitely the right track. And YES - cairo filtering is very picky on alignment of data for dest and source for all sorts of filtering, when doing best filtering this gets even worse. About the quality, there is a difference. I personally think that CAIRO_FILTER_GOOD doesn't give any visible regression vs BEST and is much easier to handle with acceptable performance.

BTW i can fully reproduce your findings.

@aurelienpierre you did the original pr, any opinion on this?

**Comment by TurboGit** [comment]
@jpenala : Thanks for tracking this down. I'll check what is the visible quality difference between both options.

**Comment by TurboGit** [comment]
@jenshannoschwalm : do you even see a difference with FAST ?

**Comment by TurboGit** [comment]
@jpenala : Is the speed acceptable for you with CAIRO_FILTER_GOOD  ?

**Comment by TurboGit** [comment]
Maybe same issue as #4117.

**Comment by jpenala** [comment]
@TurboGit  Yes every BEST changed to GOOD is a night and day difference with my system, no noticeable lag. I can easily live with GOOD being the replacement for BEST. 

I have Core i5 9400F 6 x 3.90Ghz (mitigations off and high performance governor on) and with my system at least the performance penalty with BEST is not acceptable.  It's not the hottest processor out there but not the bottom of the barrel either, and I assume there are worse systems running dt and this could be a huge issue once 3.0.1. gets out and changing the default filtering definitely is worth considering. Especially if it's a hard coded option with no switch to change between different filters.

**Comment by aurelienpierre** [comment]
darktable pipeline is supposed to scale 1:1, so we could even use CAIRO_FILTER_FAST (which uses the nearest neighbour). But with the DPI scaling and such, I'm not sure the preview size is exactly 1:1, and since I didn't notice significant slow-downs on my computer, I went all the way to BEST.

Anyway, moving back to FAST is definitely not a big issue.

**Comment by jenshannoschwalm** [comment]
>  do you even see a difference with FAST ?

FAST vs GOOD makes a difference. I did a lot of cairo stuff on other projects. What i learned is pretty easy.
FAST is quite good if you can make sure that in- and output are both aligned on corrdinate sections like x=int+0.5. and you have full-steps for size transformations. If not - and thats the case with dt - GOOD or BILATERAL are definitely better and should be used in appropriate machines.

Maybe we should make that depending on the performance checking at startup? machines with >= cores should be able to do GOOD, others not?

Who is going to do the fixing pr?

**Comment by aurelienpierre** [comment]
I can fix that. So let's put another hidden pref in darktablerc and let users choose what they want ?
