### ISSUE TITLE
Glitch issue on focus peaking in culling mode (image zoomed)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4156]
Just see the images below. First image is an image fit in the borders preview. Second one is the same zoomed. darktable always show focus peaking of all image, even outside the preview zone of the image. Reproducible on few set of images tested. Quite ugly ! @aurelienpierre and @AlicVB ?

**To Reproduce**
Just select for example to images and go in culling mode with focus peaking on. Zoom on the images and see the issue.

**Expected behavior**
Limit to image preview zone.

**Screenshots**
![Capture-20200120231632-1922x1054](https://user-images.githubusercontent.com/45535283/72761335-0327b800-3bdc-11ea-85dc-c1bf68a398d5.png)

![Capture-20200120231545-1922x1054](https://user-images.githubusercontent.com/45535283/72761342-0622a880-3bdc-11ea-80a5-32156fe69e77.png)

**Platform (please complete the following information):**
 - Darktable Version: master (last commit of this day)
 - OS: Ubuntu 19.10
 - No OpenCL

**Comment by aurelienpierre** [comment]
I don't reproduce.

**Comment by Nilvus** [comment]
> I don't reproduce.

Quite strange, it's always reproducible, on all images I tested (something like a dozen) and I can also reproduce it each time in classic preview view on lighttable (default Alt+W shortcut). See below (on little grey borders, you could see focus peaking appear):

![Capture-20200121225712-1922x1054](https://user-images.githubusercontent.com/45535283/72846809-9b3ba500-3ca1-11ea-9640-c89a0746d8be.png)

**Comment by AlicVB** [comment]
oups, forgot this one... I can reproduce, and it comes from the fact that focus drawing doesn't clip to the image area like the image surface.
That said, actually for zoomed images, focus peaking is recompute each time you move the image, which is not necessary. But I'm reluctant to fix that now, as it'll be simpler once culling/preview is moved to specific widgets, like what I'm doing for filemanager.

**Comment by jenshannoschwalm** [comment]
@Nilvus what about closing this?
