### ISSUE TITLE
Multiple modules DT stops function with a waiting label

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4158]
darktable-3.1.0+416~ge7acabb2c-win64
Open CL : On or Off doesnt matter.
Here I was in the color balance on a clean image imported for the first time in the db.
You can see the preview has got updated but the main screen hasn't.  Need to kill DT every time.
DT is not unresponsive in the GUI but just doesn't do anything. This happened in the tone equalizer.

When I restart DT the image has the effect, which implies the edit holds but nothing changes when its displayed when it freezes.
![image](https://user-images.githubusercontent.com/1119439/72797020-59d9d400-3c66-11ea-9388-e4c96460ca86.png)

[darktable-log.txt](https://github.com/darktable-org/darktable/files/4090570/darktable-log.txt)

**Comment by leclercj** [comment]
I'm seeing probable connection between this and https://github.com/darktable-org/darktable/issues/4178

**Comment by chhil** [comment]
Tone equalizer does cause it a lot of times for me.

![image](https://user-images.githubusercontent.com/1119439/73072747-cf020f00-3edb-11ea-82d9-b6b88ae9008e.png)

**Comment by leclercj** [comment]
This is likely a leftover from https://github.com/darktable-org/darktable/issues/3790 and https://github.com/darktable-org/darktable/commit/0fccb87e3dc89a59853bd43beabb7fbc0e84b998 fixed by @aurelienpierre

**Comment by chhil** [comment]
And now in the exposure module with gradient mask and scrolling mouse to increase exposure.

![image](https://user-images.githubusercontent.com/1119439/73115132-440b2e00-3f48-11ea-91da-563948b4c9e3.png)

**Comment by leclercj** [comment]
> This is likely a leftover from #3790 and 0fccb87 fixed by @aurelienpierre 

With a more careful reading, I don't think anymore this has connection with the above, nor with #4178. Sorry for the confusion.

@chhil, do you have OpenCL activated or no? If Yes, what graphics card and driver version

**Comment by chhil** [comment]
@leclercj I have had this issue with opencl on and off. 

Finally with todays build darktable-3.1.0+697~g7f499ecc2-win64 I have not had to kill DT even once.
