### ISSUE TITLE
Working color space

### ISSUE THREAD

**Issue by zygmund2000** [darktable-org/darktable#4163]
Circumstances of the case:

- Darktable Version: 3.0
- OS: Linux Arch system with Xorg
- input profile: custom.icc
- output profile: sRGB
- monitor profile: sRGB or custom but it doesn't matter in that case

To reproduce

1. Open random RAW file already imported on older version than 3.0 and got to "working color space" in section "input color profile" when you select linear or gamma profile from list  nothing happen image looks always same.

2. Open completly new RAW file after upgrade to 3.0 and then try to do same in ponit #1 and I see big color affect on screen sRGB also afert export do sRGB

**Comment by aurelienpierre** [comment]
The working colour space is used only by native RGB modules, which have been introduced with 3.0. So, not seeing any effect with pictures edited with older version actually means we didn't broke backward compatibility, and is rather a good news.
