### ISSUE TITLE
[3.0.0] Light table current image cursor resetted after each image classification, leading to broken workflow

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#4168]
In darktable light table view, I always used to order photos "sort by rating", and then set the file manager with '1' shown photos (the highest zoom). Then I classified photos, for example pressing R to reject a photo, and
then moved ahead with the mouse scroll wheel. darktable 3.0.0 has a problem that I will explain below.

Legend:
- [n] means a photos
- ^ is the cursor of the current shown photo in lightable view

all previous darktable versions behaved in the following way. You have a collection of photos to be rated:
```
[1][2][3][4][5][6][7][8][9][10]
 ^.............................
```
you start going through all of them and for example you are watching photo [6]
```
[1][2][3][4][5][6][7][8][9][10]
................^..............
```
and you decide to mark the photo [6] with the red X. Then darktable will put it at the beginning of the photos list
```
[6][1][2][3][4][5][7][8][9][10]
...................^...........
```
Note the cursor: it is still in the same position

On darktable 3.0.0, instead, the cursor follows the marked photo, so to continue watching the remaining photos (from number [7]) you have to go through all of them again.
```
[6][1][2][3][4][5][7][8][9][10]
 ^.............................
```

Imagine having to go through hundreds of photos... Can you please resume old darktable behaviour?
Thank you

**Comment by AxelG-DE** [comment]
Actually I have (had) similar problem, but even for former versions, when you either change star rating e.g. from ** to *** or from = to =>. After coming back, you're never positioned, where you started off. In bigger collections, that is quite annoying...

**Comment by AlicVB** [comment]
I'm currently rewriting all this part. I'll try to not forget your cases.
I'll ping you for testing when it's ready if you want (but it's a huge task, so I need time !)

**Comment by Germano0** [comment]
>  I'll ping you for testing when it's ready if you want (but it's a huge task, so I need time !)

Sure, I am glad to help

**Comment by AxelG-DE** [comment]
@AlicVB always a great pleasure to cooperate with you!
Anything I can support, I'll be ready.

**Comment by AxelG-DE** [comment]
There is WIP AFAIK

**Comment by Germano0** [comment]
I just tested
https://github.com/darktable-org/darktable/pull/4370
against darktable master and the problem is fixed. I keep this ticket opened in case @AlicVB needs to keep track of it

**Comment by Germano0** [comment]
@AlicVB if the code that fixes this problem is easy to extract from your pull request, I could do a backport patch for darktable stable on Fedora

**Comment by AlicVB** [comment]
no, sadly it's closely dependent of the lighttable rewrite... we just need to be patient ;)
