### ISSUE TITLE
[lua] implement panel show/hide/resize

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#4174]
**Is your feature request related to a problem? Please describe.**
User may want to work with different panel configuration for the same view. Example : usual work in darkroom with only right panel, but expand left panel + bottom toolbar sometimes...
In fact it's impossible to handle all use cases with shortcuts directly inside dt

**Describe the solution you'd like**
It would be great to add panels configuration with lua. In my mind I would say we "just" need : 
- panel visibility (read/write)
- panel size (read/write)

So user can make their own script to handle every configurations they want and link them to a shortcut.

Sadly I've absolutely no time atm to develop that... So it will either have to wait or if someone want to take it over :)

**Comment by wpferguson** [comment]
Panel visibility is already there.  This was new in dt3.0.  There is an example script, panels_demo.lua, in the examples directory of the lua-scripts repository.

Size shouldn't be a problem to add.  It would be an API change, so it probably won't be available until dt3.2.

**Comment by AlicVB** [comment]
> Panel visibility is already there. This was new in dt3.0.

Shame on me, I've not compiled the right branch, so I 've not read the up-to-date api pdf :(

For the the "resize" feature, no hurry !
