### ISSUE TITLE
New instance of tone equalizer = CRITICAL assertion 'DTGTK_IS_EXPANDER(expander)' failed

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#4178]
**Describe the bug**
In darkroom, each time I create a new instance of tone equalizer iop, I got the following error message in the console:
```

** (darktable:19729): CRITICAL **: 00:01:35.115: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed

** (darktable:19729): CRITICAL **: 00:01:35.115: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed
```

**To Reproduce**
1. Go to 'darkroom'
2. Select the 'tone equalizer' module and create a new instance
3. See error messages in the console

**Expected behavior**
No error

**Platform (please complete the following information):**
 - Darktable Version: Affects both dt3.0 and dt3.1 current master
 - OS: Ubuntu 19.10

**Comment by leclercj** [comment]
Might help to solve https://github.com/darktable-org/darktable/issues/4158

**Comment by TurboGit** [comment]
Should be fixed ! Thanks for reporting.
