### ISSUE TITLE
Editing the "pattern for the image infos line" in 3.0.0 on Windows may have unintended results

### ISSUE THREAD

**Issue by beneix** [darktable-org/darktable#4181]
I was editing the "pattern for the image infos line" in the preferences for 3.0.0 on Windows x64. It worked a couple of updates, but after I copied the " • " and pasted it in as a separator between a new tag and the existing tags, the whole line is now showing completely blank in the GUI. No matter what I edit it to (including "", "Test" and the original "$(EXIF_EXPOSURE) s • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • ISO $(EXIF_ISO)") it will not show up.

**Comment by TurboGit** [comment]
Copy paste of UTF-8 character not working on Windows ?

**Comment by beneix** [comment]
But those characters are in there as default when you install darktable!

In the end, I uninstalled and reinstalled darktable and now I have the field as I want - $(MAKER) $(MODEL) • $(EXIF_EXPOSURE) s • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • ISO $(EXIF_ISO)

**Comment by TurboGit** [comment]
@beneix : please reread what I wrote !

**Comment by beneix** [comment]
> 
> 
> @beneix : please reread what I wrote !

Pascal, I understood your post to mean that you were suggesting as a possible explanation for the issue that one would not be able to copy and paste an UTF-8 character on Windows. Did I understand that correctly?

If yes, then please re-read what I wrote. The character I assume you are referring to is the "•" character. Not only did I just copy that character from my previous post and pasted it here in this post, using Windows. I also successfully pasted it in darktable after the reinstall.

If there is something I have missed in your post, please let me know.

**Comment by TurboGit** [comment]
> I also successfully pasted it in darktable after the reinstall.

This info was not part of your message!
