### ISSUE TITLE
Auto-apply Filmic RGB preset = crash

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4182]
DT 3.1.0+426~g88bf11bd2 on Windows 10, nVidia 1060.
Auto-apply basecurve off. I set a standard Filmic RBG preset (preserve crominance = no) as auto-apply.
On fresh imported, unedited images, DT crashes when entering darkroom.
It does not happen with all images and it happens only once per image (even discarding the history doen not happen again).

One sample image (Copyright free)
[https://drive.google.com/open?id=1rV5lpx-Am6q1kxcbmlUzxu6xGrwgA95p](url)
[DSC07280.ARW.xmp.txt](https://github.com/darktable-org/darktable/files/4110488/DSC07280.ARW.xmp.txt)

Backtrace shows crash in Filmic RGB
[darktable_bt_LBAJE0.txt](https://github.com/darktable-org/darktable/files/4110496/darktable_bt_LBAJE0.txt)

**Comment by Mark-64** [comment]
By the way, on Ubuntu 19.10 it segfaults as well. The console gives the following output
```
There are unassigned iop_order in the history!!!

image: 234 module: filmicrgb version: 1
marco@marco-desktop:~/darktable/build$ /opt/darktable/bin/darktable

There are unassigned iop_order in the history!!!

image: 234 module: filmicrgb version: 1

[dt_ioppr_migrate_iop_order] for image 129 has no valid history

 ***** On-the-fly history V[1]->V[2], imageid: 129 ****************
   0           rawprepare multi  0 :: iop  1,00000000000 ->  1,00000000000
   1          temperature multi  0 :: iop  3,00000000000 ->  3,00000000000
   2           highlights multi  0 :: iop  4,00000000000 ->  4,00000000000
   3              colorin multi  0 :: iop 27,00000000000 -> 27,00000000000
   4             colorout multi  0 :: iop 58,00000000000 -> 58,00000000000
   5                gamma multi  0 :: iop 71,00000000000 -> 71,00000000000
   6                 flip multi  0 :: iop 20,00000000000 -> 20,00000000000
   7             demosaic multi  0 :: iop  8,00000000000 ->  8,00000000000
   8            basecurve multi  0 :: iop 23,00000000000 -> 23,00000000000
   9            filmicrgb multi  0 :: iop  0,00000000000 -> 46,50000000000
[dt_ioppr_transform_image_colorspace] module filmicrgb must be between input color profile and output color profile
Segmentation fault (core dumped)
marco@marco-desktop:~/darktable/build$ Unable to attach: program terminated with signal SIGSEGV, Segmentation fault.
/home/marco/darktable/build/13831: No such file or directory.
warning: Currently logging to /tmp/darktable_bt_WZ8PE0.txt.  Turn the logging off and on to make the new setting effective.
```

**Comment by Mark-64** [comment]
I am able to reproduce consistently in the following conditions:

- basecurve auto-apply off
- filmic rgb auto-apply on
- import a folder where old .xmp exists with the following 

```
   darktable:xmp_version="3"
   darktable:raw_params="0"
   darktable:auto_presets_applied="0"
   darktable:history_end="0"
   darktable:iop_order_version="1">
```
crash when opening darkroom

**Comment by GrahamByrnes** [comment]
Given that the basecurve auto-apply is not necessarily defeated when one un-checks the box the first time you open an image, have you tried loading an image with the filmic-rgb off, turning off basecurve, then relaoding with filmic-rgb on?

**Comment by Mark-64** [comment]
Yes, and there is no crash doing so.
It seems there is something wrong in the conversion from the old xmp format to the new

**Comment by aurelienpierre** [comment]
The default filmic RGB priority in your pipe is 0, aka before demosaicing. What did you do ?

**Comment by Mark-64** [comment]
> The default filmic RGB priority in your pipe is 0, aka before demosaicing. What did you do ?

Nothing strange, just imported in DT 3.1 my pic folders. There are old edits, though

**Comment by Mark-64** [comment]
Anyway, it seem it's due to some old no-op .xmp files.
Can't reproduce with newer xmp. 
DT should be perhaps more robust when handling non standard xmp
Closing
