### ISSUE TITLE
Tamron 70-200 g2 not recognized 

### ISSUE THREAD

**Issue by VegasIsrael** [darktable-org/darktable#4183]
**Description:**
Camera: Canon 6D Mark II
Lens: Tamron 70-200 f2.8 Di USD G2
darktable: 3.0 (ubuntu handbook PPA)
exiv2: 0.27.99 (compiled from master)
lensfun: compiled from master
OS: ubuntu 19.04

Darktable "Image information" module detecting my Tamron 70-200 g2 lens as Canon 300mm lens
![tamron_70-200_g2](https://user-images.githubusercontent.com/29811339/73119702-5730f480-3f6e-11ea-8cdf-d7bc08e9f9b1.png)

**Comment by parafin** [comment]
Not a darktable problem. Exiv2 allows to fix such things using a config file.

**Comment by VegasIsrael** [comment]
@parafin the problem is Exiv2 the data correct! You can see it in terminal window of my screenshot. The problem that darktable does not take it right in image information module.

**Comment by parafin** [comment]
darktable is probably linked to another version of exiv2 (system one, not the one you've built). So you're comparing the output of wrong exiv2.

**Comment by VegasIsrael** [comment]
@parafin there is some way to define where darktable linked for exiv2? 
I did totally removed exiv2 and created links to compiled exiv2 in all relevant $PATH but result is same :(

**Comment by parafin** [comment]
The most reliable way is to recompile darktable yourself, like you did with exiv2.
Also, this is not a support forum, but a bug tracker, so please find some other place to ask these questions.
