### ISSUE TITLE
image-changed indicator should be on for non-standard iop order

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4185]
Images imported with DT pre-3.0 will keep the old iop order even if not edited.
This is understandable, however in that case the image-edited overlay should be on in lighttable.
That would help the users to understand that "discard history" must be performed to return to a real virgin status.
It is misleading that the indicator is off, but the status is not the same as a real clean import of the image under DT 3.

**Comment by TurboGit** [comment]
This will be part of #3908
