### ISSUE TITLE
Lens correction module in Linux Manjaro not recognizing camera

### ISSUE THREAD

**Issue by marcsitkin** [darktable-org/darktable#4188]
**Describe the bug**
In the Manjaro Linux distro I'm running darktable in, the lens correction module doesn't pick up on the model camera (Olympus Pen-F), and throws up a dialog to select the camera/lens combo.
The lens is selected (Panasonic Lumix 20mm...), but unless a camera is chosen in the upper dialog box, the correction is not supplied.
The Olympus Pen F model is not listed, but choosing another Olympus (EM5MkII) results in the correction applied.

I also have DT running on MacOS, and the lens correction module works as expected. The camera model is picked up, as is the lens, and the correction is applied as expected.

**To Reproduce**

**Expected behavior**
I'd expect the module to pick up the EXIF info , fill in the camera and lens and apply the correction as it does on the mac version

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0.0-1
 - OS:  Linux Manjaro Gnome 3.34.2
 -  OpenCL not activated
 -  Intel Iris on MacbookPro, running linux on Vbox guest

**Additional context**

**Comment by parafin** [comment]
Run lensfun-update-data command.

**Comment by marcsitkin** [comment]
Great, thanks for the prompt response, all is well now!
