### ISSUE TITLE
Blending modes in 'rgb curve' with a drawn mask apply to the whole image

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#4189]
**Describe the bug**

Blending modes in 'rgb curve' with a drawn mask apply to the whole image instead just to the mask.

**To Reproduce**
1. Go to 'rbg curve'
2. Click on 'drawn mask'
3. Create a mask in the image, e.g. a gradient mask
4. Select a blending mode like multiply or substract. The mode is applied to the whole image not and only to the drawn mask

**Expected behavior**
The blending mode should only be applied to the mask selection

Package: darktable-skylake-3.1.0~git416.e7acabb2c-2557.1.x86_64

**Comment by upegelow** [comment]
Works like expected here. Frankly, I do not fully get what you see or expect. Can you supply a screenshot.

**Comment by cryptomilk** [comment]
![dt_20200126_183846](https://user-images.githubusercontent.com/545480/73139148-4ca85500-406b-11ea-81b2-1b29556ec30d.png)

* left is the original
* right is a **rgb curve** with a drawn mask (circle in the middle)

If I select the mulitply blending mode, it should only affect the circle in the middle, however as you can see it also affects the sky. It shouldn't affect the sky.

**Comment by upegelow** [comment]
OK, I see what you mean. The reason is that this blend mode (like several others too) applies a clamping on the final output. Unbounded values are cut back to the default value range. The blend mask (e.g. shapes) controls how input and output are mixed. Clamping is always applied if this blend mode is active.

Should this blend mode behave differently? Maybe, but then other artifacts could pop up.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
@cyptomilk You should always leave the right point at (255/255) and use a tone curve like this:
![Bild1](https://user-images.githubusercontent.com/57685590/73195253-d7518880-412d-11ea-9d50-e0bad9c9d9af.jpg)

**Comment by c-h-r-i-s-t-i-a-n** [comment]
I think this can be closed?

**Comment by johnny-bit** [comment]
Should be fixed with #4688 and using blending modes respecting higher lightness values... However masking isn't straightrowrawd as evidenced by #7464
