### ISSUE TITLE
Difference between lighttable and darkroom

### ISSUE THREAD

**Issue by mehalon** [darktable-org/darktable#4190]
Hi all,

I have just started using darktable and it looks great, however one thing is preventing me from actually using it:
Whenever I open a photo from the lighttable in the darkroom, it looks entirely different. In case of JPG the colors are more saturated and it is darker, in case of RAW the colors are distorted and everything is much darker.
Other users wrote that this has something to do with a JPG preview my camera (Canon 7D, I set it to produce both a RAW and a JPG version of the same picture) produces, but I didn't quite get it to be honest. In my camera the colors are set to Adobe RGB, maybe that is also a reason for the issues.

Either way, I'm fine with changes between some preview photo and the darkroom, but then I want, after modifying the photo in the darkroom, to export it exactly the way I see it on my screen. Exporting however is only possible from the lighttable, but when going back there it yet looks totally different and is exported the way it is shown in the lighttable.

Maybe I'm doing something wrong, could you kindly help me out?

PS: I know this is technically not a bug report, I hope somebody can help me nonetheless, thank you very much in advance

**Comment by TurboGit** [comment]
Read the manual?

**Comment by aurelienpierre** [comment]
For raw files, as @TurboGit said… read the manual. Basically, what you see in lighttable is the JPEG thumbnail (produced by the camera) embedded in the raw file, but what you see darkroom is the raw processed by darktable.

For JPEG files though, both should be the same, except if you applied auto-preset for some modules in darkroom. Did you ?

**Comment by mehalon** [comment]
That there is a JPG preview I already knew, as I wrote above. My main problem was not that there are two versions of the same photo (for whatever technical reason), but that the export function only seemed to be available from the lighttable. So I would edit a picture in the darkroom where I see version 1 of it and export it from the lighttable as version 2 totally differently, which renders my edits useless.
After more research I found the ctrl+e shortkey (which would have been extremely helpful to mention by TurboGit, but "read the manual" was probably more satisfying for him). 
As for the differences between JPGs and auto-preset, I checked and indeed there are 4 steps in the history (they must be there by default as I just installed the app without changing anything). But shouldn't the photo be at least the same as in the lighttable when I click on step 0 "original"? Even then it appears totally differently to the jpg in the lighttable mode.
Could the color spaces (sRGB, Adobe RGB etc.) have something to do with it? I take the photos in my camera in Adobe RGB, should I then set the input profile in darktable to Adobe RGB, the working profile to sRGB and the export profile to sRGB as well when I want to have an sRGB in the end? The working profile and export profile should be the same to make sure that I export it the way I see it on the screen, right?

**Comment by TurboGit** [comment]
> but that the export function only seemed to be available from the lighttable.

Wrong.



> So I would edit a picture in the darkroom where I see version 1 of it and export it from the lighttable as version 2 totally differently, which renders my edits useless.

Wrong again ! Do you know that dt is used by some pro ? Do you really think such behavior would not have been reported. What you described as never been the was dt works since its inception.

**Comment by TurboGit** [comment]
So please stop spreading non sense and the first step would be to read the documentation. Thanks.

**Comment by mehalon** [comment]
I think you don't want to understand. I said I found the export shortcut by now, you mistake "having a problem and asking a question" for "spreading rumors about the software" and feel personally offended. When I write "it seemed like" to explain my issue, and you answer "wrong!", it shows me only that you are not even trying to be helpful and are just impolite.
In any case, this is probably the wrong place to ask for help about Darktable. Next time I will go to some photography forum and hope that you won't be active there as well.

**Comment by ptilopteri** [comment]
you appear to have personal problems and they are not related to darktable.  If you feel you must "vent", please choose an appropriate forum as this is definitely NOT it.
