### ISSUE TITLE
Source color acquisition in color-mapping crashes Darktable 3

### ISSUE THREAD

**Issue by KC3101** [darktable-org/darktable#4195]
Working on a 2018 MacBook Pro, OS X 10.15.2, recently upgraded to Darktable 3. In looking for a way to match sky color tones across images shot at the same location I began following the discussion on color mapping [https://www.darktable.org/2013/04/color-mapping/]. With an image active in Darktable, activate color mapping, clicking the "acquire as source" button crashes Darktable, an error report is generated. The image resides on my local network server, but that hasn't affected other modules
Graphics:Intel Iris Plus Graphics 640

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by parafin** [comment]
Attach an error report.

**Comment by KC3101** [comment]
Thank you for quickly responding.  I have attached the image causing the problem, and a screen shot of the open modules.  I did duplicate the image, discard the history and turned off everything except modules for white balance and orientation. Done this way, color mapping was able to acquire source color information.  Color mapping did acquire color information from other images in the same film roll. Is there a module conflict I should have known about?

<img width="346" alt="Screen Shot 2020-01-28 at 2 29 39 PM" src="https://user-images.githubusercontent.com/19418923/73303013-3d481980-41db-11ea-8331-1b7729413b85.png">

**Comment by KC3101** [comment]
Crash report is attached. The 3 files I mentioned above were dragged to the reply window, but I only see the screen shot above. Please let me know if the image files were missed.
[Darktable error report.pdf](https://github.com/darktable-org/darktable/files/4124512/Darktable.error.report.pdf)

**Comment by KC3101** [comment]
I do notice that with color mapping module active on the target image, and local contrast off, enabling the contrast equalizer causes Darktable to crash.

[Color Mapping enabled_contrast equalizer crash.pdf](https://github.com/darktable-org/darktable/files/4135953/Color.Mapping.enabled_contrast.equalizer.crash.pdf)

**Comment by johnny-bit** [comment]
Cannot replicate in current master nor in 3.2.1 - closing. If you still have problem on newest release, please create a new issue :)

Side note: Please please please attach logs as .txt files, not as .pdf. .pdf files are for things like books, not huge listings that are to be searchable etc.
