### ISSUE TITLE
Exposure to path is not working with darktable-cli and/or when applied through Styles

### ISSUE THREAD

**Issue by BrexitDayEntry** [darktable-org/darktable#4204]
**Describe the bug**
exposure is only applied to the defined path, if on the definig image. Using a Style does not consider the path but the whole image

**To Reproduce**
change to darkroom
Activate "exposure"
Define a "drawn mask" and "add path" -> define any path.
Change exposure and see, that it only applies to the region defined by the path
change to lighttable
Create a Style which contains this exposure
Apply that style to a different image -> The whole image is exposured, the path is NOT used!

Same result when using darktable-cli:
darktable-cli imageB.jpg imageA.jpg.xmp out/imageB.jpg
where imageA.jpg.xmp contains the exposure to a path

**Expected behavior**
I expect the path to be considered when used via Style or via darktable-cli

**Screenshots**
No screenshot necessary

**Platform (please complete the following information):**
 - Darktable Version: this is darktable 3.0.0
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support disabled
  GraphicsMagick support enabled
  OpenEXR support enabled

 - OS:Linux #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - 
I do not know, where to get this information form
 - 
nvidia

**Additional context**

**Comment by MStraeten** [comment]
drawn masks arent stored in styles generally (also the retouch masks) - so they cant be applied using styles

**Comment by BrexitDayEntry** [comment]
If not applied through Styles, why are they not applied when using:

darktable-cli imageB.jpg imageA.jpg.xmp out/imageB.jpg
where imageA.jpg.xmp contains the exposure to a path
