### ISSUE TITLE
New filters in collect images module

### ISSUE THREAD

**Issue by jpverrue** [darktable-org/darktable#4205]
As it has already been discussed on the darktable.fr forum, it would be useful in light table to be able to retrieve images according to their processing timestamp.

After thinking about this improvement, I thought it would be nice to be able to search for images not only by their processing timestamp, but also by their import and export timestamps, and eventually by their print timestamp.

Adding these new features would require :
- adding new columns to the images table,
- adding code to feed these new columns in the various functions that manipulate the images,
- and finally the addition of new filters in the collect images module.

If these new features are suitable, I would like to implement them. Although I am now retired, I have been a 'C' programmer all my career, mainly in business computing and system computing.
Coding these new features for darktable is therefore not a problem for me.

I have already started reading the code to see where and how it should be done. Nevertheless, I won't do anything without the agreement of the developers and the community.

Thanks for reading me. I look forward to your comments.

**Comment by TurboGit** [comment]
Sounds like a nice addition to darktable. The new fields is a bit challenging but not as before since now SQLite3 supports adding new columns. I'm wondering if it won't be better to have a timestamp table with the import, export, print stamps (and of course the image id as the key) and possibly others later. This would certainly be easier to update in the code and be better in terms of SQL data layout.

Welcome on board !

**Comment by AlicVB** [comment]
Good idea !
Just a question : will/should this ends in xmp ? That would be good in the perspective of xmp for backup, but what in case or reimport ? and for xmp sharing ?
Note that I've no real opinion here, I'm just thinking loud, to be sure we don't forget some aspects...

In any case, good luck for the work !

**Comment by jpverrue** [comment]
@TurboGit : I don't think creating a second table for this new data is a good idea. Indeed we break one of the normal forms of relational databases (I don't know which one). There is a risk that one of the two relationships will be deleted or modified while the other would not. Adding columns to the images table completely avoids this risk.
@AlicVB : I do indeed think that these new timestamps should be added in XMPs; at least for backup purposes. In case of re-importing, whether for oneself or as a share, the import timestamp will be updated anyway (Remember that each of the four timestamps provided only concerns the last action performed. We're not going to keep a timestamp every time we go through the darkroom!). So no problem on this side. For the other timestamps (export, processing, and printing), it would only be inconsistent in case of sharing. Do we have to do something special in this case?

**Comment by TurboGit** [comment]
@jpverrue : well the images table is already huge and 3 more date/time columns is not a great idea to me especially since we already have tow of them (datetime_taken and write_timestamp). I understand that dt db is far from following normal forms but aiming at better db layout is a good point to put in the balance :)

**Comment by phweyland** [comment]
This is an example of new metadata. Should then be put in meta_data table. Probably with some new metadata settings because they have not exactly the same nature as the existing ones (automatically set, read only ?, numerical, ...).
They are probably no standard Xmp.xxx.xxx tags for those above. So we could add them to the Xmp.darktable.xxx ones...

Maybe the PR #4194 be merged before...

**Comment by jpverrue** [comment]
@phweyland, @TurboGit : 
The meta_data table in its current state, illustrates precisely the problem I have raised regarding the respect of the database normalization. That is to say that data which should depend on a single key, are in fact distributed in two tables. 
The consequence is that one has to do systematic "LEFT OUTER JOIN" to read the information from both tables. This makes the code more cumbersome and may also affect performance. Last but not least, data integrity is no longer assured.
The existence of this table would be justified if new metadata could be added to the request, as has already been requested. But for the time being this is not possible. Only the 5 metadata: title, description, author, broadcaster and rights are possible. 5 columns in the images table would be more justified if no changes were envisaged.
As an example, I just took a quick look at my production database. I have 63534 rows in the images table. If the creation of the rows in the meta_data table was systematic, I should have 63534 * 5 = 317670 rows in the meta_data table. But I only have 215130 rows in the meta_data table, so the creation of the rows is probably only done when one of the 5 meta_data fields is valued.
But the most annoying thing is that I discovered that among these 215130 rows, I found 25371 rows whose ID field is 0! So there are 25371 rows lying around without being attached to any image! I did not push otherwise the investigations, but it is also probable that I would find rows whose ID is not at 0, but which does not correspond any more to any existing images...

So I confirm that the timestamp fields I propose to add must absolutely be in the images table. Besides, the image table is currently composed of 43 columns, which, all in all, is not very important. There are 3 columns in the images table: caption, description and license which, if we refer to their names, are meta_data and which, at least in my database, are not valued for any of the 63534 rows. I would tend to think that they are useless ;-). Anyone to confirm?

Finally concerning the timestamps, they are indeed metadata, but not of the same order as those that populate the meta_data table today. The latter are of public order. They are intended to be transmitted with the photos. And correspond to standards (EXIF and IPTC). The timestamps I propose to add are private. They will only be used by the photographer, in front of his computer to easily find such or such other photo. So, yes, they should be saved in "Xmp.darktable.xxx".

**Comment by phweyland** [comment]
> The consequence is that one has to do systematic "LEFT OUTER JOIN" to read the information from both tables. This makes the code more cumbersome and may also affect performance. Last but not least, data integrity is no longer assured.

Not agreed. If it was true LEFT OUTER JOIN should be forbidden.

>  so the creation of the rows is probably only done when one of the 5 meta_data fields is valued.

That's correct. At least that should be like that (bugs apart). And that justifies at least partially the usage of join.

> So I confirm that the timestamp fields I propose to add must absolutely be in the images table.

That's clearly one solution but that is not "absolutely" the unique one.


> concerning the timestamps, they are indeed metadata, but not of the same order as those that populate the meta_data table today. The latter are of public order. They are intended to be transmitted with the photos. And correspond to standards (EXIF and IPTC). The timestamps I propose to add are private. They will only be used by the photographer, in front of his computer to easily find such or such other photo. So, yes, they should be saved in "Xmp.darktable.xxx".

Facts partially agreed.
From my standpoint the mistake is to have too many specific type of data. 
I think important to keep dt metadata as generic as possible, following a set of common rules (which may vary: internal or not, private (user meaning) or not, textual or numerical, ...) having some common mechanisms to let the user import, use, display and export the ones he wants to.

At this stage you cannot say that these timestamps cannot be useful once exported. At this stage you don't know if a user would not find useful to have them on information panel. 
I would disagree to just add new specific things without looking at the global scene.

The work done in PR #4194 is clearly not complete, may not be the optimum solution and a lot of work is still to be done. But I defend the generic side as long as it make sense. 

Collect module is an example of a (bit too) long list of specific cases...

**Comment by jpverrue** [comment]
You're right. It seems smarter to put all the metadata in one place.
I looked at PR #4194. I didn't see any change in the structure of the meta_data table. So I'll be able to start working.  On the other hand I saw that you added an enumeration corresponding to the values from 0 to 4 which are in the column meta_data.key. Maybe we should go to the end of the concept and add a table in the database, let's call it meta_data_keys for example, with two columns meta_data_keys.id and meta_data_keys.value. whose content would be the following :
0|Xmp.dc.creator
1|Xmp.dc.publisher
2|Xmp.dc.title
3|Xmp.dc.description
4|Xmp.dc.rights

This table would be filled once and for all in _create_library_schema() and _upgrade_library_schema_step() [see common/database.c]

This way there would no longer be any dependency on the order of the fields. A simple JOIN would retrieve the photo id, the xml keyword and the assigned value. Adding new metadata such as new timestamps would certainly be easier.

**Comment by phweyland** [comment]
> Maybe we should go to the end of the concept and add a table in the database,

Sounds interesting to me in that sense that would bring some possibilities of dynamic configuration.
This table should have more fields (see dt_metadata_def line 43 in common/metadata.c same PR). 
Extending the usage we would also have to add some parameters, like "editable" or its opposite "calculated" to indicate the metadata item should not appear in metadata plugin. The type (text, date, ... ) to make sure we are able to convert it properly when necessary.

But there are some hard coded dependencies:
How to set up the translation of the names (macro "N_") displayed in the UI ?
How to we interfere with import parameters in case a new item is added ?

**Comment by jpverrue** [comment]
I'm glad you like it! :-)
Yes, of course you'll have to add several other columns to the table. What I put in my previous post was just to show the concept.
Answers: 
A) Just add a column for the English label in the table and apply the N_ macro on this label read with select. The small problem would be for the translation, because the automatic tools rely on the source code, not on the content of the DB ;-)
B) I don't really understand the question. Can you give more details?

**Comment by phweyland** [comment]
> The small problem would be for the translation, because the automatic tools rely on the source code, not on the content of the DB

That's what I meant. 

Metadata parameter includes metadata list. So if we change the number of metadata, the parameter list for metadata module (import module as well) should be updated accordingly (legacy params). This is hard coded too.

**Comment by jpverrue** [comment]
@phweyland : 
May I suggest this?
These are several SQL queries to apply to data.db, which will create the meta_data_params table and insert the rows we need.
```
CREATE TABLE "meta_data_params" (
	"id"	INTEGER UNIQUE,
	"destination"	INTEGER, -- 1:exifs, 2:darktable
        "display_order"	INTEGER,
	"gui_label"	TEXT,
	"xmp_key"	TEXT,
	"data_type" INTEGER,  -- 1:SQLITE_INTEGER, 2:SQLITE_FLOAT, 3:SQLITE_TEXT, 4:SQLITE_BLOB, 5: SQLITE_NULL
	PRIMARY KEY("id")
);
INSERT INTO meta_data_params VALUES (0, 1, 3, "creator", "Xmp.dc.creator", 3);
INSERT INTO meta_data_params VALUES (1, 1, 4, "publisher", "Xmp.dc.publisher", 3);
INSERT INTO meta_data_params VALUES (2, 1, 1, "title", "Xmp.dc.title", 3);
INSERT INTO meta_data_params VALUES (3, 1, 2, "description", "Xmp.dc.description", 3);
INSERT INTO meta_data_params VALUES (4, 1, 5, "rights", "Xmp.dc.rights", 3);
INSERT INTO meta_data_params VALUES (5, 2, NULL, "last import timestamp", "Xmp.darktable.import_timestamp", 1);
INSERT INTO meta_data_params VALUES (6, 2, NULL, "last export timestamp", "Xmp.darktable.export_timestamp", 1);
INSERT INTO meta_data_params VALUES (7, 2, NULL, "last change timestamp", "Xmp.darktable.change_timestamp", 1);
```
Then, just with this little piece of code you can display the first 5 rows correctly ordered in the window
```
sqlite3_stmt *stmt;
DT_DEBUG_SQLITE3_PREPARE_V2(
    dt_database_get(darktable.db),
    "SELECT p.id, p.gui_label, p.xmp_key "
    "FROM data.meta_data_params AS p JOIN main.meta_data AS m ON p.id = m.key "
    "WHERE p.display_order IS NOT NULL "
    "AND m.id = ?1 "
    "ORDER BY p.display_order", -1, &stmt2, NULL);
DT_DEBUG_SQLITE3_BIND_INT(stmt, 1, image_id);
while(sqlite3_step(stmt) == SQLITE_ROW)
  {/* display rows in GUI */}
sqlite3_finalize(stmt);
```

**Comment by phweyland** [comment]
> May I suggest this?

Thanks for help ! But playing with db queries is a bit too early for me. The features we want to bring for the time being do not rely on this and should work with hard coded definitions. So I think we should make it work that way first.
I like the idea of db table, but to move to it, we need to solve the above two points (if I don't miss other ones):
- translations
- module parameters 

If not, we still have hard coded parameters, not automatically linked to db table content, and we don't get the advantages of db. And once this solved, it should be simple replace hard coded data with db ones.

**Comment by phweyland** [comment]
Hi @jpverrue , back to this subject, I've revisited my position.
dt metadata (meta_data table) may not be the best place to implement new date time items.
First because meta_data items are mainly strings. Date is subject to localization. This makes the date capture as a string a bit tricky...
On the other side I've tried to summarize the usage of metadata through the different modules.
Here is a first draft:
[dt_info_mapping.xlsx](https://github.com/darktable-org/darktable/files/4198174/dt_info_mapping.xlsx)

Seen the nature of the info (date, internal) you want to add, I think your first suggestion is more appropriate than mine at this stage. And as you suggested they could replace some unused info in images table.

That doesn't close the debate about generalization but this will not happen at once...

**Comment by jpverrue** [comment]
Hi @phweyland,
Yes, I agree. The idea was appealing, but in practice difficult to implement. I discussed with Pascal "in French" the problem of internationalization. He doesn't see a solution, so we're stuck with it. And since I don't really know this mechanism, I'm not going to contradict him!
Bravo for the census. Great effort on your part! It could be useful for my implementation of time stamps.

How can I be sure that nothing anywhere uses the 3 columns caption, description and license?
I'll do recursive grep, but...

**Comment by phweyland** [comment]
> How can I be sure that nothing anywhere uses the 3 columns caption, description and license?

These fields are empty. 
In the code I've found some occurrences of these fields but only inside general inserts, never as individual fields.
So I think there is no use of them.
PS: if needed we can talk in French too :)

**Comment by jpverrue** [comment]
@phweyland In french here or on another chat ?

I did several recursive searches with grep on the whole src tree for each of the three column names. I only found references when creating or modifying the DB. There are also some SQL queries in collection.c that include these columns for sorting, but that's it. So we should be able to delete them without too much problem. I should also look for the sha1sum column which is also empty.

I would do this cleanup before recreating other columns. Should we create another issue? and wait for a green light before going ahead (I'm a newbie in this matter ;-))

**Comment by phweyland** [comment]
> In french here or on another chat ?

Here should be in English I'm afraid.

> I would do this cleanup before recreating other columns. Should we create another issue?

If you are clear with what you want to do, I think you should create a new branch on your side, make your changes and submit a PR when it works.  (sorry if I give obvious details).

**Comment by TurboGit** [comment]
This is done and merged. Closing.
