### ISSUE TITLE
DateTimeDigitized overwritten by DateTimeOriginal in exported photo

### ISSUE THREAD

**Issue by raymondjohnson** [darktable-org/darktable#4207]
**Describe the bug**

I have scanned photos with manually set values for their original and digitized dates and times. For example:
```
$ exiv2 -pt -g DateTime rj_20040709_063.jpg
Exif.Image.DateTime                          Ascii      20  2015:10:11 13:40:12
Exif.Photo.DateTimeOriginal                  Ascii      20  2004:07:09 00:00:17
Exif.Photo.DateTimeDigitized                 Ascii      20  2015:10:11 13:40:12
```
If I export that photo, the exported photo contains this DateTime information:
```
$ exiv2 -pt -g DateTime darktable_exported/rj_20040709_063_export.jpg 
Exif.Image.DateTime                          Ascii      20  2020:01:31 12:28:49
Exif.Photo.DateTimeOriginal                  Ascii      20  2004:07:09 00:00:17
Exif.Photo.DateTimeDigitized                 Ascii      20  2004:07:09 00:00:17
Exif.Image.DateTimeOriginal                  Ascii      20  2004:07:09 00:00:17
```
Exif.Photo.DateTimeDigitized should not be overwritten with the value of Exif.Photo.DateTimeOriginal. I believe it should stay the same as it is in the original (for me, the date the photo was scanned), even if the photo is modified.

In addition, I don't think the new Exif.Image.DateTimeOriginal tag should be written at all. I've looked at the Exif specifications and I'm not entirely sure how Exif.Image.* is supposed to be different from Exif.Photo.*, but it seems unnecessary.

**To Reproduce**

1. Add a photo with different values for Exif.Photo.DateTimeOriginal and Exif.Photo.DateTimeDigitized
2. Export that photo
3. Check the Exif DateTime values in the exported photo

**Expected behavior**

An exported photo should have the same Exif.Photo.DateTimeOriginal and Exif.Photo.DateTimeDigitized values as the original photo.

There is probably no need to write a Exif.Image.DateTimeOriginal tag.

**Screenshots**

**Platform (please complete the following information):**
 Testing done with 2.6.0 on Pop OS! 19.10.

**Additional context**

**Comment by TurboGit** [comment]
A lot of work has been done regarding meta-data support recently. Our architect here is @phweyland maybe this is already fixed ?

BTW, any chance for you to test on a more recent version ? 2.6.0 is more than one year old.

**Comment by raymondjohnson** [comment]
> BTW, any chance for you to test on a more recent version ? 2.6.0 is more than one year old.

Good point. That was the incentive I needed to try the latest snapshot, but unfortunately it has the same behavior as before. The tag Exif.Photo.DateTimeDigitized goes back in time instead of staying the same.

**Comment by ptilopteri** [comment]
consider that the raw was "digitized" at a particular time and the exported image at another time, ie: when exported.  I don't believe that this has changed in a verrry long time, if ever.

I routinely run an exiv2 script to redate the image files to the "digitized" date after transferring from camera to hard drive and again on export so they properly represent what I believe they should.

for your convenience:
exiv2 -T ./*.{nef,jpg}
exiv2 \-k \-r %y%m%d_%H%M%S_:basename: \.\/*.{nef,jpg}'

and I use exiv2 as being compiled is much faster than exiftool.

**Comment by phweyland** [comment]
> Exif.Photo.DateTimeDigitized should not be overwritten with the value of Exif.Photo.DateTimeOriginal.

I think you are right. 
Today we have:
```
// FIXME: What about DateTimeDigitized? we currently update it, too, which might not be what is expected
// for scanned images
exifData["Exif.Photo.DateTimeDigitized"] = cimg->exif_datetime_taken;
```

I'll fix that.

**Comment by phweyland** [comment]
> In addition, I don't think the new Exif.Image.DateTimeOriginal tag should be written at all. I've looked at the Exif specifications and I'm not entirely sure how Exif.Image.* is supposed to be different from Exif.Photo.*, but it seems unnecessary.

I have let Exif.Image.DateTime and Exif.Photo.DateTimeOriginal equal. Until we find specification saying the opposite. :)

**Comment by raymondjohnson** [comment]
> > In addition, I don't think the new Exif.Image.DateTimeOriginal tag should be written at all. I've looked at the Exif specifications and I'm not entirely sure how Exif.Image.* is supposed to be different from Exif.Photo.*, but it seems unnecessary.
> 
> I have let Exif.Image.DateTime and Exif.Photo.DateTimeOriginal equal. Until we find specification saying the opposite. :)

I don't really have an issue with that, so that's fine. I was questioning the need to add Exif.**Image**.DateTimeOriginal alongside Exif.**Photo**.DateTimeOriginal. As an extra tag doesn't really hurt, and maybe helps with some compatibility issues, it's less of a bug and more something that I don't have any use for personally.

As someone who really geeks out over metadata, I appreciate the work you've put in on this, @phweyland!

**Comment by phweyland** [comment]
> I was questioning the need to add Exif.**Image**.DateTimeOriginal alongside Exif.**Photo**.DateTimeOriginal.

I understand. Fact is dt is able to change this value through geotag module. So, at least both must be kept aligned.

> As someone who really geeks out over metadata

I take the opportunity... If you have any spare time please have a look on PR #4194. Don't hesitate to give comments and suggestions. This is really important to understand what the users expect.

**Comment by ptilopteri** [comment]
time digitized should represent the time the image was generated.  The in-camera image should display the time the image was shot, and an exported image time digitized should be the time of export.  DateTimeOriginal should be the *original* image time of birth.  "Digitized" and "Original" are NOT the same thing.

**Comment by raymondjohnson** [comment]
> time digitized should represent the time the image was generated. The in-camera image should display the time the image was shot, and an exported image time digitized should be the time of export. DateTimeOriginal should be the _original_ image time of birth. "Digitized" and "Original" are NOT the same thing.

Using yesterday's build, what I get with an exported image (shot in 2004, scanned in 2015) is exactly what I would expect:

- Exif.Image.DateTime is 2020:02:04, the date the _exported_ image was created
- Exif.Photo.DateTimeOriginal is 2004:07:09, the date that I clicked the shutter on the camera and captured to film
- Exif.Photo.DateTimeDigitized is 2015:10:11, the date I scanned the film

There are some other date fields in the exported image that weren't in the original, which I'm not personally concerned about:

- Exif.Image.DateTimeOriginal -- 2004:07:09
- Xmp.exif.DateTimeOriginal -- 2004:07:09
- Xmp.photoshop.DateCreated -- 2004-07-09
- Xmp.xmp.CreateDate -- 2015-10-11
- Xmp.xmp.ModifyDate -- 2015-10-11

The only one that surprises me there is the last one, as Exiv2's conversion table suggests Xmp.xmp.ModifyDate is the same as Exif.Image.DateTime.
