### ISSUE TITLE
Sony ILCE-6600 Noise Profile

### ISSUE THREAD

**Issue by Stefan-Kamps** [darktable-org/darktable#4211]
Hi.

I prepared a noise profile for the Sony Alpha 6600 (also called ILCE 6600).
Please review the profile and if its quality is OK, add it to darktable.

Best regards,

Stefan

[darktable-noiseprofile-20200131.tar.gz](https://github.com/darktable-org/darktable/files/4142997/darktable-noiseprofile-20200131.tar.gz)
[noise_result.pdf](https://github.com/darktable-org/darktable/files/4142998/noise_result.pdf)

**Comment by rawfiner** [comment]
Hi
Thank you for the profile!
