### ISSUE TITLE
Amaze Demosaicing produce artefact with OpenCL

### ISSUE THREAD

**Issue by emaimx** [darktable-org/darktable#4213]
When I am using Amaze demosaicing with OpenCL activated I get artefacts on the left of my picture. If I zoom in, I get the same type of artefact on the left side of my preview. If I render a jpeg, I get artefact on the left side of the jpeg. If I render the same image 2 times, I get different artefacts. I don't get any artefact using ppg or vng, and enabling or disabling colour smoothing doesn't change anything.

With amaze :
![DSC02599_01 amaze](https://user-images.githubusercontent.com/53395201/73606697-73a3e100-45ad-11ea-885b-320068112fd5.jpg)

Another run with amaze :
![DSC02599 amaze](https://user-images.githubusercontent.com/53395201/73606698-743c7780-45ad-11ea-80c5-006305075015.jpg)

With ppg :
![DSC02599 ppg](https://user-images.githubusercontent.com/53395201/73606699-743c7780-45ad-11ea-8c26-4051e21ad4ca.jpg)

I had also white balance, highlights reconstruction and orientation activated but deactivating them doesn't solve the issue.

I have that problem with darktable 3.0.0_rc2 (packaged with my distro Solus). I then packaged for myself darktable 3.0.0 and I get the same issue. These are the steps used by Solus for packaging darktable : 
```
setup      : |
    mkdir build && cd build
    %cmake -DBINARY_PACKAGE_BUILD=ON -DLIB_SUFFIX=%LIBSUFFIX% ..
build      : |
    %make -C build
install    : |
    %make_install -C build
```
The build is made by gcc 9.2.0 and :
`CFLAGS='-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT'
`

My GPU is an AMD R9 380. My OpenCL stack is the one from amdgpu-pro 19.30 used over the free amdgpu driver and linux 5.4.12.

EDIT : forgot to mention that I did not get these artefacts when OpenCL wasn't installed.

**Comment by kanyck** [comment]
Most probably the amdgpu-pro OpenCL stack is to blame. A couple of years ago I got very similar issue on HD 7770 which is GCN 1.0. AMD refused to fix this, and in later version of amdgpu-pro it simply stopped to recognize OpenCL on my card, so I was virtually forced to buy a newer one. If you have any opportunity to lend a newer card, try it. I expect the problem will go.

**Comment by kanyck** [comment]
And, BTW. AFAIK, amaze doesn't use OpenCL at all. The only demosaic that uses OpenCL is PPG.

**Comment by butcherg** [comment]
Don't know if this is pertinent, but the amaze implementation in librtprocess does a similar thing on what look like tile boundaries, with sse2 enabled.  Goes away when I disable sse2.

**Comment by tomaszg7** [comment]
I have very similar problem with amdgpu 19.30.838629 and Radeon Fury. I get artefacts in zoomed out view on the left and bottom border. However in my case, when I zoom in I get black screen. Also exported tiff is completely black. Switching to PPG makes darktable work again.

**Comment by kanyck** [comment]
AFAIK, the amdgpu-pro's opencl blob is still based on fglrx's codebase, slightly reworked to support newer cards (and probably the newer stack). AMD is now severely centered on it's new ROCm architecture, dreaming of deprecating the old stuff not to support two (and, if I recall correctly, even three) implementation. If your hardware supports ROCm, I suggest to set it up: it's fully opensource and under active development, that means you'll get the adequate support. I think, it's a pity that AMD effectively dropped the support of older implementation while a lot of cards are still in use (and quite capable), which is not a honorable decision that won't make the customers happy, but it's how it is...
The irony is that while OpenCL is the AMD's technology, and Nvidia seems to support it better than AMD at the moment... yet I personally prefer open-source solutions. Which is not Nvidia's blob for sure.

**Comment by tomaszg7** [comment]
I'll add to that that mixing amdgpu blob with fully open kernel module is unsupported and may lead to additional bugs.

As to ROCm, it's not only older GPUs which are unsupported, the problem lies also in CPU/motherboard. Even on AMD front, only Zen architecture is supported. Without it is not possible to run it. I'm still using AMD FX processor, so no ROCm for me :/ 

Note that apart from the problem with Amaze, I also get a lot of gpu faults which sometimes lead to gpu hangs:
```
[ 3266.208627] amdgpu 0000:01:00.0: GPU fault detected: 146 0x0642b714 for process darktable pid 21070 thread darktable pid 21070
[ 3266.208629] amdgpu 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00109506
[ 3266.208630] amdgpu 0000:01:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x0B0B7014
[ 3266.208632] amdgpu 0000:01:00.0: VM fault (0x14, vmid 5, pasid 32778) at page 1086726, write from 'SDM0' (0x53444d30) (183)
```

**Comment by emaimx** [comment]
> And, BTW. AFAIK, amaze doesn't use OpenCL at all. The only demosaic that uses OpenCL is PPG.

Now I am very curious: how can OpenCL have a sufficient side effect to mess up computations done on CPU?

> If your hardware supports ROCm, I suggest to set it up: it's fully opensource and under active development, that means you'll get the adequate support.

That's the issue for me, my 5 years old pc doesn't support pci-e atomics so no ROCm for me. Besides, AMD push precompiled ROCm packages not for a lot of distribution (understandable). That wouldn't be a problem if ROCm compilation process wasn't such a mess or if it had proper documentation. I have another computer with a card that should support ROCm, but after several hours trying to get it to work I gave up.

**Comment by aurelienpierre** [comment]
Amaze doesn't have an OpenCL version, it only works on CPU. That might be an issue with the support of your camera, probably from rawspeed (bad sensor boundaries or something).

**Comment by tomaszg7** [comment]
Anyway, the problem in my case appears *only* if I enable both Amaze and OpenCL. Disabling any of those makes the issue disappear. The fact that Amaze doesn't have OpenCL version doesn't mean that there isn't a bug along the data flow which manifests only when those two conditions are satisfied. 

The images in the top post are from Sony DSC-RX100M3, I can confirm the problem with Canon 300d, 30d, 7d and M100. These are the files I readily had, I can check it with other samples from the web if it would be helpful. However it seems unlikely that it is related to support of the particular camera.

To make things funnier I checked samples from Fujifilm X-E2 which uses X-Trans sensor and I could reproduce a similar effect with `frequency domain chroma` method. 

I also noticed that when I switch to one of the affected methods (Amaze or FDCh) the artifacts appear at once. When I switch back to another, good method, artifacts persist. I need to zoom-in/out to make them disappear. I can even chose "passthrough" and still see artifacts, even though obviously preview image is easily verified to be recomputed. Moreover width of the corrupted strip seems to generally vary.

**Comment by tomaszg7** [comment]
FWIW I noticed that enabling `hot pixels` module also makes the artifacts appear.

**Comment by tomaszg7** [comment]
It hasn't.

**Comment by tomaszg7** [comment]
I recently changed my motherboard and processor to Zen 2 platform and thus migrated from AMDGPU-pro to ROCm. The problem disappeared for me. Also intermittent crashes went away.

**Comment by jenshannoschwalm** [comment]
@johnny-bit closing this?

**Comment by johnny-bit** [comment]
No new reports, amaze seems to not have opencl, the artefacts might come from bazilion other places that might now be fixed... OK @jenshannoschwalm let's close it :)
