### ISSUE TITLE
sqlite3 errors on import

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4215]
while trying to debug or provide more information about degraded performance, I began with a clean empty library and imported ~35k images from local and nfs mounted drives.

**To Reproduce**
import a group of photos

**Platform (please complete the following information):**
openSUSE Tumbleweed 20200128
NVIDIA GF106 [GeForce GTS 450], 390.129
darktable 3.1.0~git451.f12feec38
OpenCL on 
i7 12-core 36GB

**Additional context**
 - Can you reproduce with another Darktable version? did not try
 - Can you reproduce with a RAW or Jpeg or both? importing both jpg and nef
 - Are the steps above reproduce with a fresh edit (removing history)?  do not know
 - Did you compile Darktable yourself? If so which compiler was used, with what options? no, using darix's master OBS builds for openSUSE Tumbleweed
 - Is the issue still present using an empty/new config-dir  new library

sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1827, function dt_collection_shift_image_positions(), query "COMMIT": cannot commit - no transaction is active
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1827, function dt_collection_shift_image_positions(), query "COMMIT": cannot commit - no transaction is active
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1827, function dt_collection_shift_image_positions(), query "COMMIT": cannot commit - no transaction is active
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1827, function dt_collection_shift_image_positions(), query "COMMIT": cannot commit - no transaction is active
sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git451.f12feec38/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction

**Comment by ptilopteri** [comment]
segfaulted, coredump @ http://wahoo.no-ip.org/~paka/darktable_bt_007DF0.txt

**Comment by TurboGit** [comment]
I have removed a transaction done for a single SQL statement, this is superfluous and may help fixed your issue. Can you double check ? If there is more will see...

**Comment by ptilopteri** [comment]
It will take a few minutes, I had removed 20k of ~40k images to see if the performance changed much and it did and appeared to be sql related.  

I am now importing again the removed images and do not see the sql errors reported earlier but have not yet finished.

Will update shortly, tks.

**Comment by ptilopteri** [comment]
darktable 3.1.0~git453.e30fb18d9

core dumped during import, http://wahoo.no-ip.org/~paka/core.darktable.lz4

restarting import

**Comment by ptilopteri** [comment]
Well, change helped as far as removing sql errors displayed on import.  Didn't see any.  But no improvement on performance.  Opened an image, opened crop module click on screen to change size of crop and (darktable -d sql) took from 19.667055 to 23.498973 before I was able to change the crop area.

full sql log during this interval is:  http://wahoo.no-ip.org/~paka/darktable.sql.txt

hope this helps

**Comment by TurboGit** [comment]
@ptilopteri : I really don't think that performance issue is related to SQL anyway. During editing a picture there is no much SQL request made anyway. What bother me is that you seem to be the only one to have this slow down (at least it is not common), so we have to think about the context in which you are running! On my side I have more than 55k image on the db and do not have any slowdown. It is even very fast for whatever action I do.

My config is close to yours : Nvidia 440.44-2, Debian unstable, Linux kernel 5.4, i7 8 cores, 16MB RAM and OpenCL on (Quadro M1000M). I'm on a Dell Precision notebook.

**Comment by TurboGit** [comment]
BTW, is you SQL database in local drive ?

**Comment by TurboGit** [comment]
Better close this and open a new issue if needed as the original issue (SQL errors) is fixed.

**Comment by ptilopteri** [comment]
> BTW, is you SQL database in local drive ?

yes along with darktable library

and already have https://github.com/darktable-org/darktable/issues/4172#, severe performance degradation.  Do you want another issue?

**Comment by TurboGit** [comment]
@ptilopteri : Indeed, no need for another issue.
