### ISSUE TITLE
Wrong selected photo when exiting Sticky preview mode

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4216]
Hello all !

Darktable 3.1.0~git447.5226e3462 installed on a Linux Kubuntu 19.04 with Intel Core 7700k + NVidia GFX 1070 + 32Go RAM.

**Description :**
When using the sticky preview, browsing through photos & exiting the Sticky preview mode back to the grid view, the selected photo in not the one you were on/previewing when exiting the  Sticky preview mode.
**_Expected behavior_**
I expect the photo selected in Grid view when exiting the Sticky preview mode to be the last photo previewed in Sticky preview mode.

**Test case**
0. Assign the sticky preview to your desired key (mine is Z)
1. Open a folder, make sure you are in grid mode and go to a photo (not the first one)
2. Press Z (or your shortcut) to enter the Sticky preview mode
3. Browse through several photos
4. Press Z again (or your own shortcut) to get back to the grid mode. The selected photo is not the one you were previewing when you exited the Preview mode.

Thanks
GLLM

**Comment by AlicVB** [comment]
Nope, it's not what is intended. Entering/existing (sticky-)preview doesn't change selection on purpose : 
1. you can preview images outside a selection (image hovered) and you don't want to loose your selection once back to lighttable
2. if you have a selection and start preview with an image inside your selection, preview list of images is restricted to the selection) This is how culling works too.

That said, when you exit preview, lt ensure that your last shown image is visible, by scrolling if needed.

To resume, dt avoid as much as possible to change selection in the back of the user...

**Comment by GLLM** [comment]
Hi @AlicVB 

Thanks for your reply and the details.

When going in Sticky preview mode, the user, when browsing through files, is actually changing the one selected pictures he is looking at.

Why would he get back to another one than the one he was looking at the second before ? 
Because, imagine you Sticky preview many images. The last one pleases you ... you exit sticky preview mode and realize you should 5-star it. You press your shortcut (you're in grid mode, remember).
And voilà, you just 5-starred a completely different image ! The one picture you entered the sticky preview mode is now 5-star ... if you actually browsed  through many images, you probably wont even notice this ! (the same goes for any actions : color/stars/reject/...)

_Why did I report this in the first place ?_
Since the navigation keys for previous/next cannot be assigned to left/right arrows in darkroom module and as switching from one pic to another is kinda slow in darkroom, i was looking for a way to quickly browse through full screen pics and having the full screen pic selected when I get back to the grid mode.

Is there actually another way to do what I'm trying to do ? Maybe I'm actually not using the correct feature !

Thanks !
GLLM

**Comment by AlicVB** [comment]
OK, I've just tested again master, and I have to say that it doesn't work as it should. I'm not sure of the reason, but anyway, I'll rework that in my big rewrite of all this part.

For your concern, as said, we don't change selection except on user explicit request. There's some reasons for that. One example : you want to export a set of image for specific use (piwigo, ...) you select some images, and for those you are unsure, you can preview them full screen and choose to add them to the selection or not.
Another point is that we rely on the selection to know in which images we want to navigate in sticky preview. That allow you to select non contiguous images and preview only this ones.

That said, about key press, what I plan to do is that mouse_over will only be changed when moving mouse. In your case, that would mean that when exiting preview (by key) the mouse hovered image (the one that will be rated) will stay the last one seen in preview until you move the mouse again. That also allow you to exit-reenter preview for the same image.
At some point that has been the case, and I'll ensure that it'll be in future !

Now, I admit that it would be good to improve the preview exit by making the exited image more visible. But I haven't really think at that for instance. Maybe a special highlight which disappear slowly... But for sure, we can't use selection for that !

**Comment by GLLM** [comment]
Hey @AlicVB 

Thanks for your reply ... I understand better the selection use case you just re-explained.
I'll wait to see how it will work post your refactoring w.r.t key press for action !
Bye !
