### ISSUE TITLE
Window minimized before quitting on macOS

### ISSUE THREAD

**Issue by Sangeppato** [darktable-org/darktable#4218]
Hello,
I'm on macOS 10.15.2 using Darktable 3.0.0.

My issue is quite "minor" but I still want to report it:
When quitting/closing Darktable, the window gets minimized to the dock and then it finally quits, but the expected behaviour is that there shouldn't be any minimization, it should just quit right away.

**Comment by johnny-bit** [comment]
This is (I believe) fixed in 3.4
