### ISSUE TITLE
lut3d failed to open (undefined symbol)

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#4220]
darktable 3.1.0+453~ge30fb18d9 version

**Describe the bug**
lut3d module missing.

Message when darktable is started from cli:
[iop_load_module] failed to open operation `lut3d': /usr/lib/darktable/plugins/liblut3d.so: undefined symbol: _ZN12cimg_library8CImgListIcE6assignEj

**Platform (please complete the following information):**
Latest Manjaro/KDE
openCL activated
gfx gtx-1660Ti
CPU Ryzen 9 3900X

Sincerely
Claes

**Comment by parafin** [comment]
That's not a darktable bug, but build environment problem. How your darktable was built?

**Comment by ClaesGitHub** [comment]
Thanks for the reply!
I built it using Manjaro/KDE's pamac, updating darktable-git.
[pkgbuild.txt](https://github.com/darktable-org/darktable/files/4147375/pkgbuild.txt)

Only changes I have made is to add _-march=znver1_ as compiler directive, and added parameter _-j23_ to every make.

**Comment by parafin** [comment]
Right, I remember now, take a look at this thread:
https://discuss.pixls.us/t/gmic-lookup-symbol-err-on-opensuse-darktable-master-build/15827

Basically gmic should be built without LTO.
