### ISSUE TITLE
[FR] Composition/pattern module or allow bitmap in watermark

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#4234]
I was thinking, that it would be nice if dt would allow to blend in some tiff with e.g. new sky, fabric pattern ... from pre-configured directory. 

I know there is the watermark module trick with embedded bitmap, but it's not very convenient and 
the quality suffers.

On the other hand, bitmap editors like gimp/krita don't provide parametric masking ability.
So allowing this in darktable would be great feature.

**Alternatives**
If you don't like idea of additional module, maybe allowing tif in watermark module could be alternative.

**Comment by johnny-bit** [comment]
Tiff in watermark with blending mode? huh... png too? Hmmmm... While it isn't the best idea it could make it a bit easier for me to do some things (eg i can't seem to get my signature right in inkscape, but it's no problem to draw it in krita/gimp). I'll try to take a look.

in Gimp you could try https://www.gimp.org/tutorials/Luminosity_Masks/ and go from there if nothing would happen out of this...

And can you change the title to something like "[FR] Composition/pattern module or allow bitmap in watermark"?

**Comment by Dannny1** [comment]
Ok, thank you, i changed the title.

**Comment by johnny-bit** [comment]
This will be fixed by #9817 
Let's reopen. Check if #9817 covers your request if you can.

**Comment by Dannny1** [comment]
Seems good, thank you.
