### ISSUE TITLE
great number of sql ?queries?

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4236]
sorry, fatfingered #4235

openSUSE Tumbleweed 20200201
NVIDIA GF106 [GeForce GTS 450], 390.129
darktable 3.1.0~git556.a2070508b
OpenCL on
i7 12-core 36GB
library.db contains >128k images

opened darktable:
darktable --library /home/paka/.config/darktable/library.db -d sql ./Photos/
(contains 3 raw images)

in lighttable mode, moving the mouse cursor in area where the images are displayed but not on any image produces continuous sql statements (while the mouse is moving).
http://wahoo.no-ip.org/~paka/darktable.sql.2.txt

If you place the mouse cursor on an image, continuous sql statements are generated
http://wahoo.no-ip.org/~paka/darktable.sql.3.txt

**Comment by AlicVB** [comment]
yes, we know :)
I'm currently rewriting all that part, and that point will be solved (and many other)

**Comment by ptilopteri** [comment]
@AlicVB 
then this should be closed?

**Comment by TurboGit** [comment]
Yes please. Let me do that @AlicVB is doing something great... Just don't hold your breath :)
