### ISSUE TITLE
[GIT version] Random fall-backs to CPU when processing images if default opencl profile is set

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#4237]
Few weeks ago after rebuilding dt from GIT I notices significant performance degradation. Running dt with -d perf showed that the same modules use CPU instead of GPU now and then as seen here https://github.com/kanyck/files/blob/master/perf.log.
It looks like
1. Thumbnails are always built with GPU just fine
2. First darkroom image generation is always done on CPU (lighttable -> darkroom)
3. While editing, subsequent image generation seems to randomly use CPU or GPU.

**Platform**
 - Darktable Version: 3.1.0+556~ga2070508b-dirty
 - OS: Gentoo Linux
 - OpenCL ON
 - [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] amdgpu + opencl blob from amdgpu-pro

**Comment by johnny-bit** [comment]
I won't be able to check your issue exactly (my main PC will not be able to do OpenCL for quite some time, and then I'll only be able to test nVidia card only), but I can aid in report.

Can you post output of `darktable-cltest`?
Can you produce similar log showing GPU->CPU drop with `-d perf -d opencl` so we'll know if opencl screams?
What version of kernel + amdgpu + amdgpu pro do you run?

with gentoo we know that tweaking kernel might introduce some weirdness... Can you check if other opencl-heavy apps have random hangups or anything like that?

**Comment by kanyck** [comment]
Kernel is still 5.1.0-pf7. It has not changed since OpenCL worked fine. Neither opencl blob has. It's still amdgpu-pro-19.30.838629 as a blob donor. xf86-video-amdgpu-19.1.0 but I don't think it's involved. Not sure it has changed, too. Probably not.

As for other opencl apps, I've imagemagic ffmpeg and x264. Not sure how can I make sure it really works in these apps. However in DT opencl is used when creating thumbnails it works, as you may see from the log. It only start to fallback to for darkroom calculations.

darktable-cltest output: https://github.com/kanyck/files/blob/master/dt.cltest

Combined log: https://github.com/kanyck/files/blob/master/dt.opencl.perf

BTW. Another fresh issue when compiling today's git version. Shall I open a separate bug?
```
/media-gfx/darktable-9999/work/darktable-9999/src/views/knight.c
/var/tmp/portage/media-gfx/darktable-9999/work/darktable-9999/src/views/knight.c: In function «_event_loop»:
/var/tmp/portage/media-gfx/darktable-9999/work/darktable-9999/src/views/knight.c:951:10: error: «res», probably is used uninitialized [-Werror=maybe-uninitialized]
  951 |   return res;
      |          ^~~

```
Had to add -Wno-error to compile...

**Comment by johnny-bit** [comment]
> Shall I open a separate bug?

If it's current master then yes.

for your perf log - can you please enable english locale when generating logs? modules are written with their display name in logs and if I coudn't read cyrylic I wouldn't know `Чёрная и белая точки Raw` is `black and white point raw` :stuck_out_tongue:

OK, I see GPU->CPU drops but no further explainations behind them... what's your opencl scheduling setting?

**Comment by kanyck** [comment]
Sorry about the locale))) Reloaded the file.
Here is excrept from darktablerc. When slowdown happened I tried to run darktable with a clean darktablerc with the same result. What doesn't mean it's non involved. TBH I don't have a clear understanding of these parameters' meaning. So it's hit-and-miss for me...
```
opencl=TRUE
opencl_async_pixelpipe=true
opencl_avoid_atomics=false
opencl_checksum=3259126302
opencl_device_priority=*/!0,*/*/*
opencl_disable_drivers_blacklist=false
opencl_enable_markesteijn=true
opencl_library=
opencl_mandatory_timeout=250
opencl_memory_headroom=200
opencl_memory_requirement=768
opencl_micro_nap=200
opencl_number_event_handles=75
opencl_scheduling_profile=default
opencl_size_roundup=16
opencl_synch_cache=false
opencl_use_cpu_devices=false
opencl_use_pinned_memory=true

```

**Comment by kanyck** [comment]
I switched scheduling profile to "Very fast GPU" and the issue seems to go. Amazingly, when it first showed up, it was set to Very fast GPU, I tried to fiddle with the options to see if something  would happen, but at that time there was no difference. Current 3.1.0+754~g4397473da-dirty is now sensitive to this option. I'll watch it for some time then probably close the ticket. Thanks @johnny-bit

**Comment by kanyck** [comment]
...but there is another issue. "Very fast GPU" causes DT to hang on some pictures. Only kill helps or ctrl/c if start from terminal. No error messages on the tty before hangups.  Looks like the retouch module causes DT to stall, but not only.  Some pics without retouching hang DT, too. Will try to find out what module(s) cause stalls.

**Comment by kanyck** [comment]
Now I have even more strange things than before... now it hangs (htop shows 100% cpu on DT instance) on some pics that were processed fine before. I'm afraid the database is probably corrupt (but just the same, even this must not cause hangups!)
BTW when I start DT I can see in htop about 40 instances. Is it normal?

**Comment by kanyck** [comment]
> Very fast GPU" causes DT to hang on some pictures.

Eventually it does not. This issue appears even if OpenCL is switched off completely. The problem was that DT has somehow created huge xmp files and correspondingly huge db entries that caused DT to stall.
https://github.com/darktable-org/darktable/issues/4418
Meanwhile "Very fast GPU" seems to work fine on my installation. Still watching... will post corresponding darktablerc options as soon as I'm sure it actually works.

**Comment by kanyck** [comment]
Okay. Looks like it works. Here come my current settings in darktablerc. Closing so far.
```
opencl=TRUE
opencl_async_pixelpipe=true
opencl_avoid_atomics=true
opencl_checksum=3259126302
opencl_device_priority=*/!0,*/*/*
opencl_disable_drivers_blacklist=false
opencl_enable_markesteijn=FALSE
opencl_library=
opencl_mandatory_timeout=250
opencl_memory_headroom=200
opencl_memory_requirement=2048
opencl_micro_nap=100
opencl_number_event_handles=60
opencl_scheduling_profile=very fast GPU
opencl_size_roundup=16
opencl_synch_cache=active module
opencl_use_cpu_devices=false
opencl_use_pinned_memory=true
```
