### ISSUE TITLE
Darktable does not open most of the time (Master - KDE)

### ISSUE THREAD

**Issue by YAFU** [darktable-org/darktable#4240]
I am a KDE and Darktable user for a long time. I use Darktable from master compiled by myself. In my system I have associated image files to be opened directly with Darktable, that is, from Dolphin file browser I simply double click on (for example) CR2 files and it automatically opens in Darktable. My way of working is generally that, navigate the images from Dolphin, open the files in Darktable (double click or Open With...), work on the image and then close Darktable. Darktable is installed in a folder "/home/USER/.darktable_master/" which I specify when I compile/build (./build.sh --prefix /home/USER/.darktable_master --buildtype RELEASE)
Since about a month ago with Darktable from master, most of the times I try to open my CR2 with Darktable from Dolphin, Darktable is hung halfway without showing the image and I must kill the Darktable application process.
"Darktable 3.0.0rc1 + 90 ~ gdaba32c08" is the last known version that I had built and where I do not have the mentioned problem (it works correctly). As I had said, about a month ago and new versions from master I have the mentioned problem.
the problem occurs even with a very empty "/home/USER/.config/darktable/" folder after opening a couple of CR2 files from Dolphin.

As a curiosity, when Darktable is hung up (what happens most of the time in the first attempt with the same image) and I kill the Darktable process, if I immediately try to open "the same image" after killing Darktable process, usually the image is successfully opened in that second attempt.

My system: Kubuntu 18.04 64bits

**Comment by johnny-bit** [comment]
Well... This shouldn't happen...

first of all - please update your build with current master and set buildtype to `RelWithDebInfo`
next sttart darktable this way:

`/home/USER/.darktable_master/bin/darktable -d all "PATH_TO_IMAGE"` and if darktable hangs please post output.

**Comment by YAFU** [comment]
Hi Sorry for the late reply.
I have noticed that when opening with "-d all" Darktable almost never hangs. Here the output of one of the very very few times that it hung with "-d all"
https://pastebin.com/GfLESjfn

If I open the image without "-d all" it still hangs as described in the first message of this report.

By the way, I am not sure why so many references to sources path appear in the log when the binary is executed. As you can see, one of the folders where I have the sources contains "@" symbols. I hope this is not causing problems.

**Comment by YAFU** [comment]
Hi. Currently, the problem is not present. I'm not sure if this is due to some KDE or Darktable update.
