### ISSUE TITLE
Denoise Profiled presets all gone....

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#4244]
Not sure if this was intended or not just thought I would report it. Recently one preset called Basic Start replaced all the usual ones and it seemed to work nicely. Latest build for me on Windows has no presets... 3.1.0+563~gf5c60707d    Not a big problem just reporting in case this was unintended....

**Comment by TurboGit** [comment]
Yes because this is not needed anymore with the latest Y0U0V0 wavelet mode. A single instance does the job for both luminance and chrominance noise.

**Comment by todd-prior** [comment]
@TurboGit Thanks...I had seen the basic start preset but really could not recall what the parameters were so I went looking and just noticed it was removed so I just thought I would check....good to know...might have others asking as that is not obvious or maybe I missed a post...Thanks again
