### ISSUE TITLE
Wrong color in jpg (very different from what is shown in Darktable)

### ISSUE THREAD

**Issue by Anode1** [darktable-org/darktable#4245]
After exporting (the blue sky) the color in jpg is not matching with rendition in 
The behavior is consistent. The module used is colorize. I had even a bigger effect - before I added lightness, and reduced saturation. The sky was brighter and greenish in jpg. Although the Darktable shows it exactly as in my other shot of the sky, i.e. correctly.

Screenshots attached. 

![Screenshot from 2020-02-06 20-19-33](https://user-images.githubusercontent.com/9967850/73994087-4dba6b80-4922-11ea-8601-9c52fc4bf897.png)
![Screenshot from 2020-02-06 20-43-50](https://user-images.githubusercontent.com/9967850/73994089-4f842f00-4922-11ea-876f-42a3c70fcd7e.png)

Platform:
Darktable [2.6.2] under Ubuntu Linux x86_64
Video card: NVIDIA GeForce GTX 1060 Mobile 6GB (rev a1)
$ clinfo
Number of platforms                               0

**Comment by Anode1** [comment]
I guess, it may be connected with the fact that I have 2 monitors: laptop one and external, photographic. Colors are shown differently, and I'm editing using the external (photographic) display. However, when jpg is exported, it is matching my laptop display, and when I move the window to the external display - the jpg is very greenish. So, some gamut or mapping is taken from the laptop (?)
When I do display screenshots, they are in fact different.  
But I would expect to be able somehow to render the consistent colors (with the photographic display) when working on the 2nd display only. I guess, it might be a switch, choosing the correct display/gamut/mapping (?), sorry for the wrong, probably, terminology. I tried different exporting intents, and the result was the same.

![Screenshot from 2020-02-06 20-43-50](https://user-images.githubusercontent.com/9967850/73994499-b9e99f00-4923-11ea-8615-afc47f35c518.png)
![Screenshot from 2020-02-06 20-53-28](https://user-images.githubusercontent.com/9967850/73994501-bb1acc00-4923-11ea-903f-202fc7d525f4.png)

**Comment by mdrmike** [comment]
Sounds like (color management issue with) your setup, not Darktable.

Here's a hint: https://help.ubuntu.com/stable/ubuntu-help/color.html

**Comment by Anode1** [comment]
Thank you.
BTW I just looked and found that I have Default (Automatic) color profiles and I didn't change it. No custom profiles at all. I also just tried to set both profiles to OFF with no visible effect. The interface (of Device Colour Profiles) looks like affecting nothing (the colors are very different on both displays, which is understandable: one display is photographic display with a wider gamut).

![Screenshot from 2020-02-25 15-54-42](https://user-images.githubusercontent.com/9967850/75287190-efc5c900-57e7-11ea-83ca-d04fead892f3.png)

**Comment by johnny-bit** [comment]
If you're using wayland then it doesn't really have color corection. Try using X server. And make sure ALL your monitors are callibrated and that darktable KNOWS about them.

**Comment by Anode1** [comment]
I do not use Wayland, I use X11.
My photographic IPS monitor was calibrated a month ago at the factory (I have documents for the calibration) and after receiving it I calibrated my laptop display, but the colors became even more different from each other, so I returned to the default color settings (this way the colors are closer to the photographic display).
  
>> and that darktable KNOWS about them.
This is interesting. I haven't seen any settings in Darktable concerning the monitors it runs. I can drag (in the extended Desktop) Darktable half screen on Laptop and half screen on the monitor and the colors are different as in the 1st post.

**Comment by johnny-bit** [comment]
This is both weird and wrong somehow. All my screens (even the most crappy one) match better after callibration! And I too had a bit of issues regarding color matching in jpegs, but after calibration all colors look way better everywhere since dt knows how to display them.

As for knowing about profile - see that "screen" icon in lower right corner? click it and see if it has your display selected. if not, see if it recognizes profile and then select it - that should be enough.

**Comment by Anode1** [comment]
Agree. Something is wrong.
I did calibration again (mostly defaults), and the last attached photo is done by my smartphone, where the difference is clearly visible (laptop's left screen is more magenta in the snow).
Thanks for the "screen" icon, it shows 'sRGB' as the 'display profile' and 'perceptual' for 'display intent' , which I believe correct.

![Screenshot from 2020-02-27 00-48-14](https://user-images.githubusercontent.com/9967850/75421324-fea39d00-5907-11ea-9efa-a3b47d148695.png)
![Screenshot from 2020-02-27 00-48-38](https://user-images.githubusercontent.com/9967850/75421342-05caab00-5908-11ea-9c8a-f7ced4a05f94.png)
![Screenshot from 2020-02-27 00-49-01](https://user-images.githubusercontent.com/9967850/75421347-09f6c880-5908-11ea-94cb-4e581fb7b964.png)
screenshot of the extended screen looks very different
![Screenshot from 2020-02-27 02-02-35](https://user-images.githubusercontent.com/9967850/75421372-1a0ea800-5908-11ea-8384-d05329add799.png)
![IMG_20200227_020832263](https://user-images.githubusercontent.com/9967850/75421737-f26c0f80-5908-11ea-9d8d-1eb0d6cf5fa1.jpg)

**Comment by parafin** [comment]
Generally display profile should be set to "system display profile". Your monitor is not sRGB, so sRGB is not a correct value. Maybe you should try removing darktable config directory and check if it works better with default settings.

**Comment by Anode1** [comment]
Thank you, I tried and from now on I use 'system display profile' which
actually is giving the same result.
I believe, this is not a Darktable problem but rather of the driver working
with multiple displays with different gamuts.
Thanks again for your help

**Comment by johnny-bit** [comment]
close issue then if you think it's ok to do so :)

**Comment by Anode1** [comment]
not a Darktable specific issue
