### ISSUE TITLE
[rgb curve] Shipped camera presets are wrongly implemented.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#4247]
**Describe the bug**

Selecting either of the shipped  presets ends up showing the *RGB, independent channels* (the red channel) and the image has a red colour.

Manually switching from *RGB, independent channels* to *RGB, linked channels* solves the problem.

Tested this with images made with a D750 and D7000, both have the same unwanted result.

EDIT: Downloaded and tested and confirmed with D90, D5100 and E-M10II.

**To Reproduce**

1. Choose and open an image made with a Nikon: D5100, D7000, D7200, D7500, D750, D90 or Oympus OM-D E-M10II (one of the currently shipped presets)
2. Select the rgb curve preset that goes with the camera (either from within the module or from *quick access*).

**Expected behavior**

Preset(s) to be implemented correctly as shown by third screenshot.

**Screenshots**

Freshly imported image:
![rgbcurve original](https://user-images.githubusercontent.com/56407344/74011544-737a5b80-4988-11ea-9f51-6a8bde9d04f9.png)

After the preset is applied:
![rgbcurve preset](https://user-images.githubusercontent.com/56407344/74011427-1bdbf000-4988-11ea-9933-8db708dfeb30.png)

After manually setting it to *RGB, linked channels:
![rgbcurve manually](https://user-images.githubusercontent.com/56407344/74011450-272f1b80-4988-11ea-8e8c-8af1b5d523b7.png)

**Platform (please complete the following information):**
 - Darktable Version: Stable 3.0.0 + Development 3.1.0+578
 - OS: Linux
 - Distro: Debian Buster (10.2)

**Additional info**
 - Is the issue still present using an empty/new config-dir: Yes.
 - Clean or filled history: Makes no difference.

**Comment by c-h-r-i-s-t-i-a-n** [comment]
**Confirmed** this gug in DT 3.0.0 on Windows10.

**Comment by TurboGit** [comment]
This is because the presets have been copied from tonecurve to rgbcurbe, but tonecurve are in Lab ! They are indeed quite broken !
