### ISSUE TITLE
Recent Build creates mismatch between history and modules selected and produces a scrambled image.

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#4248]
Some sequence in a few of my xmp files is getting modified to produce scrambled images. The culprit is a duplicate instance of the module being added to the history. This is only present in the history and does not match what is indicated by the active modules. This happened yesterday for the first time...not sure the build 424 perhaps but still there today on 3.1.578 See result
![image](https://user-images.githubusercontent.com/44409419/74031098-a7e91a00-497e-11ea-9441-d5058f554e96.png)   XMP is attached...only way to clear the issue is go back in the history before the duplicate module...here it is denoise profiled but on others it was a second phantom instance of the rgb curve...Running on Windows 10....

XMP

<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2017:04:06 20:34:21"
   xmp:Rating="1"
   xmpMM:DerivedFrom="WP_20170406_20_34_18_Pro_LI.jpg"
   darktable:xmp_version="4"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="15"
   darktable:iop_order_version="2">
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Todd Prior</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:publisher>
    <rdf:Bag>
     <rdf:li>Todd Prior</rdf:li>
    </rdf:Bag>
   </dc:publisher>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Todd Prior</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="1"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="2"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="3"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="4"
      darktable:operation="denoiseprofile"
      darktable:enabled="1"
      darktable:modversion="10"
      darktable:params="0000803f0000e0400000803f0000803f0000803f00000000000000000000803f000080bfb65dbf397e20323a0b16013563bd0c356abbdd340400000000000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f01000000010000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f00000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="010000001d0000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="5"
      darktable:operation="denoiseprofile"
      darktable:enabled="1"
      darktable:modversion="10"
      darktable:params="0000803f0000e0409a99993e0000803f0000803f00000000000000000000803f000080bf4e395039479dbe39d22e25356108e73457693b350400000000000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f00000000abaa2a3eabaaaa3e0000003fabaa2a3f5555553f0000803f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f00000000010000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f0000003f00000000000000000000000000000000"
      darktable:multi_name="1"
      darktable:multi_priority="1"
      darktable:blendop_version="9"
      darktable:blendop_params="010000001c00000000008c4200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="6"
      darktable:operation="vibrance"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffff5342"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="7"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0000803f0000803f0000803f0000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="8"
      darktable:operation="splittoning"
      darktable:enabled="0"
      darktable:modversion="1"
      darktable:params="000000000000003fcdcc4c3e0000003f0000003f00000442"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="9"
      darktable:operation="colorcontrast"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ae47813f000000000000803f0000000001000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="10"
      darktable:operation="colorzones"
      darktable:enabled="0"
      darktable:modversion="5"
      darktable:params="02000000000000000000003fa3291a3e805ee83e2549923e0000003fb76ddb3e0000003f2549123f0000003f6edb363f0000003fb76d5b3f0000003f0000803f0000003f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003f2549123e6666e63e2549923e0000003fb76ddb3e0000003f2549123f0000003f6edb363f0000003fb76d5b3f0000003f0000803f0000003f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003fe6580e3e6de4063f2549923e0000003fb76ddb3e0000003f2549123f0000003f6edb363f0000003fb76d5b3f0000003f0000803f0000003f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000800000008000000010000000100000001000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="11"
      darktable:operation="hazeremoval"
      darktable:enabled="0"
      darktable:modversion="1"
      darktable:params="cdcc4c3ecdcc4c3e"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="12"
      darktable:operation="colorbalance"
      darktable:enabled="0"
      darktable:modversion="3"
      darktable:params="010000000000803fd7a3803f3a6d803f52b87e3f0000803fd7a3803f52b87e3fd7a3803f0ad7633f3233733f7777773f6766863f0000803f3333733f000010406666663f"
      darktable:multi_name="1"
      darktable:multi_priority="1"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="13"
      darktable:operation="colorbalance"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="010000000000803f0000803f0000803f0000803f06f09e3f0000803f0000803f0000803f287e6c3f0000803f0000803f0000803f0000803f0000803f00009041fa0fa13f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="14"
      darktable:operation="bilat"
      darktable:enabled="0"
      darktable:modversion="3"
      darktable:params="010000000000003f0000003f0000803e0000003f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
    </rdf:Seq>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>

-->

**Comment by todd-prior** [comment]
Follow-up I get this dialogue for denoise which looks like a testing one and if I add a module and then go back to denoise profiled then the dialogue box looks back to normal in the darkroom panel 
![image](https://user-images.githubusercontent.com/44409419/74034500-68bec700-4986-11ea-8116-af7b751b11cd.png)

**Comment by TurboGit** [comment]
@todd-prior : can you attach the xmp ? The XML is broken when pasted into a message. Just rename it with extension .txt for being able to attach. Thanks.

**Comment by TurboGit** [comment]
Also, do you have the db containing the image ? Just in case to compare the history.

**Comment by rawfiner** [comment]
@todd-prior  About the checkboxes in denoise profiled: they are normal. They are here to provide backward compatibility: some bug fixing and algorithm changes break backward compatibility, and these checkboxes allow the user to choose between the old and new algorithm.
The scrambled image is a different problem though... I am not sure I understand what gives you this bug, could you explain more precisely how to reproduce?

**Comment by todd-prior** [comment]
It wasn’t always denoise …on some images it was rgb curve module…seems like a few of the images opened after conversion of the database there were two instances in the history but only one actually activated and present in darkroom. If you look closely at my screenshot the activated modules clearly shows one instance of denoise…there are two in the history. This was created after I updated I guess. I can click on any point in the history above the first line of denoise and the image is scrambled as shown however below that it appears fine….it only happened on select images so there must be some combination and or order of modules susceptible to this…I don’t do any manual reordering so its not because of that ….so not sure exactly how it happens…..

**Comment by todd-prior** [comment]
I’m at work now I will see if I still have it…Its on my PC at home…..

**Comment by todd-prior** [comment]
[WP_20170406_20_34_18_Pro_LI_01.jpg.txt](https://github.com/darktable-org/darktable/files/4173505/WP_20170406_20_34_18_Pro_LI_01.jpg.txt)
Here is the corrupt xmp that was created...

**Comment by todd-prior** [comment]
[database.zip](https://github.com/darktable-org/darktable/files/4173518/database.zip)
Database and Library...and Library previous version....curiously last update has doubled the size of my library???

**Comment by TurboGit** [comment]
Something wrong I can't explain you have the temperature module activated for the JPG file?

**Comment by todd-prior** [comment]
Must have used spot wb to improve wb
 
 
Sent from 
Mail for Windows 10
 

From: Pascal Obry
Sent: February 8, 2020 11:58 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Mention
Subject: Re: [darktable-org/darktable] Recent Build creates mismatch between history and modules selected and produces a scrambled image. (#4248)

 


Something wrong I can't explain you have the temperature module activated for the JPG file?
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by TurboGit** [comment]
Well maybe, but when I import the XMP you provided to one of my RAW I have no issue.

**Comment by todd-prior** [comment]
@TurboGit   Funny I just imported it   still creates a scramble on one of my images....
![image](https://user-images.githubusercontent.com/44409419/74094255-78383000-4aac-11ea-9450-e94c46f3fa29.png)

**Comment by todd-prior** [comment]
For me importing this xmp creates two denoise profiled entries in the history and that is the point where it fails.....there is only one instance actually and not instance of denoise profiled 1 as is present in the history.....I have pasted this on a few images.....maybe its just a weird coincidence for a few edits that I had done previously???

**Comment by todd-prior** [comment]
![image](https://user-images.githubusercontent.com/44409419/74094321-686d1b80-4aad-11ea-81fd-dfa99f8de9f2.png)

![image](https://user-images.githubusercontent.com/44409419/74094332-7de24580-4aad-11ea-851b-31896b8ac1f7.png)

**Comment by TurboGit** [comment]
And the image in which you import does it has some history ? Do you have basecure and sharpen activated in the preference?

**Comment by TurboGit** [comment]
@todd-prior : Was able to reproduce this morning. And I have just pushed a fix. The bug was due to a missing iop-order list in the XMP. To fix your issue, you need first to ensure that the XMP is written again (just use the write xmp button). And then you should be able to import this XMP to other images without trouble.

**Comment by TurboGit** [comment]
@todd-prior : And BTW thanks a lot for this report, a corner case that is now fixed ! Hopefully the last one :)

**Comment by todd-prior** [comment]
Thanks for your detective work…this appeared on a few existing xmp files being converted when I updated to a new build…as for importing it was just a collateral symptom of the. Issue I guess. I am glad it was real and
 apparent in the end..you guys amaze me…
 
Sent from my Windows 10 device
 

From: Pascal Obry
Sent: February 9, 2020 5:07 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Mention
Subject: Re: [darktable-org/darktable] Recent Build creates mismatch between history and modules selected and produces a scrambled image. (#4248)

 


@todd-prior : And BTW thanks a lot for this report, a corner case that is now fixed ! Hopefully the last one :)
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by Nilvus** [comment]
@TurboGit: seems to not been totally solved. I have some images where I create a second instance (last ones, was noise reduction (profiled)). All is ok. Then I on lighttable, I select another image (which don't have any module with a second instance) and just copy one or two modules on the first image (which have a module with a second instance), then weird artefacts like in this issue appears.

Each time, I have to open the corrupted image on darkroom, then go before the second instance used in history, then recreate them. Hope it's clear.

**Comment by TurboGit** [comment]
@Nilvus : I will really need a reproducer as I cannot create any wrong edit on my side. I got 2 clean images (no edit). Say A and B. I have added two denoise profile instance on A (0 & 1).

- From lighttable I have copied instance 0 of denoise from A and copied to B. All ok.
- From lighttable I have copied instance 1 of denoise from A and copied to B. All ok.
- From lighttable I have copied instance 0 & 1 of denoise from A and copied to B. All ok.

Is that what you did ?

**Comment by TurboGit** [comment]
BTW, at this stage I think it is better to open a new issue. Thanks.

**Comment by todd-prior** [comment]
@TurboGit  @Nilvus Let me know if you want me too...last night I did an edit using two instances of color zones. The edit was fine last night when I closed DT....opened it today and the same problem with the scrambled image and what looks like a mismatch between the modules and the history....I have to run to work but I will submit a screen shot file and xmp....and version details etc....so now this has happened with several different module and always when I have used multiple instances...

**Comment by TurboGit** [comment]
@todd-prior : No don't reopen but create a new issue if you have a step by step reproducer. Without it would be difficult to do anything. Thanks.

**Comment by todd-prior** [comment]
Will do
 
Sent from my Windows 10 device
 

From: Pascal Obry
Sent: February 12, 2020 11:53 AM
To: darktable-org/darktable
Cc: Prior,Todd; 
Mention
Subject: Re: [darktable-org/darktable] Recent Build creates mismatch between history and modules selected and produces a scrambled image. (#4248)

 


@todd-prior : No don't reopen but create a new issue if you have a step by step reproducer. Without it would be difficult to do anything. Thanks.
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
