### ISSUE TITLE
SOME params in xmp human legible and editable for timelapse photography and darktable

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4250]
**Is your feature request related to a problem? Please describe.**
Basically my todays wish is directly linked with my thread in pixls.us, I started, called [Timelapse photography and darktable](https://discuss.pixls.us/t/timelapse-photography-and-darktable/14579)

My major intention is, to push dt a little bit into a direction, where is a *chance*, dt one day can be compatible with [LRTimelapse](https://lrtimelapse.com)

I do not want anybody to fully make dt adopt to LRT, I just would like to see, that dt comes to a stage, it can have an interface. Please see above discussion, which I hope my intention and motivation becomes clear.

**Describe the solution you'd like**
As I have described in my [post #37](https://discuss.pixls.us/t/timelapse-photography-and-darktable/14579/37), I would like to get (for the beginning) 

- two new modules, which are a modification of the today's existing exposure module and white balance module
- to be called _exposure timelapse_ and _white balance timelapse_ or _exposure TL_, _white balance TL_
- having their major setting (like temp and tint for WB and exposure for EXP) extracted from the darktable:params="base64-ziped-code" and store it in a human legible and script editable value (just like RT does)

e.g.
```
darktable:operation="temperature"
darktable:enabled="1"
darktable:modversion="3"
darktable:params="046c32400000803f8c4dd63f0000807f" (example !)
darktable:temperature="5748"
darktable:tint="1.012"
```
For many reasons (not least backwards compatibility), I think, it is necessary to implement this in separate, new modules and leave the todays existing ones untouched. But this is my non-coding-guy's view

For any background questions, please first consult [Timelapse photography and darktable](https://discuss.pixls.us/t/timelapse-photography-and-darktable/14579) and please also note my disclaimer in the initial post.

Thank you very much in advance!

**Comment by parafin** [comment]
It's closely related to #3215 (or even a duplicate).

**Comment by AxelG-DE** [comment]
@parafin: 
thank you for looking up and connect. 
Somehow I hope it will not be considered to be a duplicate (even I admit they are quite similar, for motivation I donno) and finally just closed, as the discussions around this topic and the above mentioned thread are not that simple :-)

**Comment by AxelG-DE** [comment]
I still hope, this function would come live. Hence I'd stop the bot :)

**Comment by aster94** [comment]
hi @AxelG-DE i went from another route: https://github.com/darktable-org/lua-scripts/issues/195 but I stopped, if i could get a little bit of help from the developers in the understanding of how darktable use this files i will continue to code

**Comment by AxelG-DE** [comment]
The one who probably has the deepest knowledge, I suppose is @houz.

... and you need to be aware of the very high priority from the devs, its not to break backwards compatibility. Hence for my purpose I proposed to merely add it to new modules. But it might be also possible, that the version, which is used initially will be reported and then accept the relevant method. AFAIK "denoise profiled" from @rawfiner is capable of such.

**Comment by aster94** [comment]
Who ever talked about breaking compatibility? Even if I did I don't see how could I do it with a lua script 😅

**Comment by AxelG-DE** [comment]
I just put this compatibility into the pot as I have noticed, this is a, understandably, high priority :smile:

**Comment by AxelG-DE** [comment]
I still hope it would get some activity...

**Comment by aster94** [comment]
@AxelG-DE in lua you can get exposure in a quite simple, human and script editable way

**Comment by AxelG-DE** [comment]
@aster94 if you see my [pixls-post](https://discuss.pixls.us/t/timelapse-photography-and-darktable/14579), which explains the motivation, you can see, lua-script wouldn't be my preferred solution :)

**Comment by AxelG-DE** [comment]
I am still looking after this and hope one day it will come true......
@aurelienpierre could you pls. remove the "no-activity-tag"? TNX

**Comment by AxelG-DE** [comment]
pls do not close this, as just now introspection got merged and next step maybe about to come

**Comment by AxelG-DE** [comment]
Link to #5335

**Comment by AxelG-DE** [comment]
Ping
...bot too nervous...

**Comment by tacman** [comment]
Idea: how about a "verbose" option for sidecar files.

The Unity IDE (for games, etc.) has an option when saving files to use YAML, perfect for source control, also easy to see all the settings and what's changes.  A "verbose" option for sidevar files could include expanding the compressed strings.  Even simply storing the params as a JSON string would be better than having everything that want's to read and write the sidecar files need to implement its own parser

Thank you to the folks who are putting together external tools for reading and writing, but I really do think that settings should not be compressed or encoded within xml.  XML already compresses very well (ascii text, lots of repeated tags), and the XML is only ever used as an intermediary format anyway.  

I'm working on a tool in PHP to create tutorials from the sidecar file (do this, then this), and creating the instructions from the existing sidecar files is maddening.

**Comment by johnny-bit** [comment]
This FR could also help in debugging some errors caused by not-aggressive enough value sanitization etc :) I'm really looking forward to it... some day...

Part introspection, part read/write work...

**Comment by AxelG-DE** [comment]
Due to several discussions on IRC, I give up hope on this. 

I do understand, particularly for backward compatibility, that would be a mega-project, where the user base, actually demand for or need this is marginal.

Introspection has landed in the code, just me, I do not have the competence to utilize that for my purpose...

Thanks to @hanatos I finally understood, what was meant, when the message was transmitted, that it is actually possible to access dt from "outside" on the example of darktable-chart.

Those two code lines give examples from code -> xmp:
[chart/main.c Line 845](https://github.com/darktable-org/darktable/blob/master/src/chart/main.c#L842)
_"that's how you write a custom tonecurve to xmp"_
and
[chart/main.c Line 639](https://github.com/darktable-org/darktable/blob/master/src/chart/main.c#L639)
_"this is how you write it to xml"_

Here comes the deconding part xmp -> code:
[exif.cc Line 2117](https://github.com/darktable-org/darktable/blob/master/src/common/exif.cc#L2117)
_"the implementation, not the caller side as the other two links were
because chart doesn't call it..
and you'll still need the (symmetric) code as during writing, matching the decoded memory to the struct {} holding the parameters for the module.
reading is slightly more difficult than writing, because it may be a newer or older version of the params"_
