### ISSUE TITLE
Collection ordering is bizarre

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4252]
For a couple of versions now, but still in 3.1.0+578, the collections list looks like this:
![dt_collections](https://user-images.githubusercontent.com/58031430/74070533-909f4080-4a01-11ea-8771-73b4e8163517.png)

Seems to be since the ordering was changed 5-6 days ago.
Windows 10pro

**Comment by elstoc** [comment]
Same here. I have collections/directories named by date (yyyymmdd) and am used to my collections displaying in the same order. Pretty much have to use the search every time now.

**Comment by TurboGit** [comment]
This is a choice. To have the order per date use the corresponding filter. The folder are now sorted with the more recent first (depending on the film-id).

**Comment by elstoc** [comment]
Not sure I can see a case where that would be a useful order but perhaps I've missed something. I'll just use the 'folder' view from now on.
