### ISSUE TITLE
When a locked iphone is connected, multi-second freezes in darktable occur.

### ISSUE THREAD

**Issue by Firstyear** [darktable-org/darktable#4253]
**Describe the bug**
When an iphone is connected that is locked, darktable will repeatedly freeze for 20 second bursts every few seconds. This makes the application unusable.

**To Reproduce**
Connect a locked iphone to the computer
Attempt to use darktable.

**Expected behavior**
Darktable should not have repeated 20 second freezes.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: MacOS 10.15.3
 - yes
 - intel + amd

**Additional context**
Excerpt from "-d all". This repeats frequently in the ui. Please note the timestamps.

```
28.124258 [run_job-] 05 290509503.617078 28.124272 load image 55095 mip 5 | queue: 1 | priority: 428.124274
28.202782 [camera_control] loaded 4 port drivers.
28.225976 [camera_control] 1 cameras connected
52.521500 [camera_control] gphoto2 error: PTP Timeout
52.528347 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
52.528365 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
```

It is very likely that this is an overly large ptp timeout (~20 seconds), or that the device that fails should not be re-accessed multiple times. This second log shows the frequency of the failure:

```
199.576946 [camera_control] loaded 4 port drivers.
199.594054 [camera_control] 1 cameras connected
224.040824 [camera_control] gphoto2 error: PTP Timeout
224.047100 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
224.047117 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
224.419803 [camera_control] loaded 4 port drivers.
224.439813 [camera_control] 1 cameras connected
249.252118 [camera_control] gphoto2 error: PTP Timeout
249.258691 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
249.258706 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
249.614205 [camera_control] loaded 4 port drivers.
249.632948 [camera_control] 1 cameras connected
273.941400 [camera_control] gphoto2 error: PTP Timeout
273.946939 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
273.946956 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
274.331886 [camera_control] loaded 4 port drivers.
274.349876 [camera_control] 1 cameras connected
299.236188 [camera_control] gphoto2 error: PTP Timeout
299.242825 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
299.242842 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
299.280366 [camera_control] loaded 4 port drivers.
299.301680 [camera_control] 1 cameras connected
323.314390 [camera_control] gphoto2 error: PTP Timeout
323.320565 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
323.320580 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
323.963701 [camera_control] loaded 4 port drivers.
323.983832 [camera_control] 1 cameras connected
347.994794 [camera_control] gphoto2 error: PTP Timeout
348.000815 [camera_control] failed to initialize camera Apple iPhone 5 (PTP mode) on port usb:020,023
348.000828 [camera_control] failed to initialize device Apple iPhone 5 (PTP mode) on port usb:020,023, probably causes are: locked by another application, no access to udev etc.
348.393905 [camera_control] loaded 4 port drivers.
348.410991 [camera_control] 1 cameras connected
```

**Comment by frankenmichl** [comment]
Out of curiosity, I just tried reproducing this on Linux, both 3.0.0 and latest master, and I cannot see that. Maybe this helps someone to debug this.

**Comment by parafin** [comment]
This is a longstanding bug, present also on Linux: https://redmine.darktable.org/issues/11738

I've tried to re-produce it on macOS, but couldn't. When iPhone is locked, it's not present in device list. Once it's unlocked, it gets scanned successfully. If I re-plug it and press "scan for devices" darktable hangs for some time, then duplicate appears in the list. But I can't re-produce periodical hangs (and debug log output is different), so I think it's another issue. I think darktable doesn't re-scan devices automatically, so I'm not sure where periodical hangs can come from.

How did you install darktable?

**Comment by parafin** [comment]
See also https://redmine.darktable.org/issues/10624

**Comment by Firstyear** [comment]
I used "brew cask install darktable" to install.

**Comment by parafin** [comment]
Which means libgphoto was also built by brew. Maybe it's an issue there... Have you tried reproducing this issue with official DMG package?

In any case it's bad that device scanning is synchronous operation blocking the GUI, it should be re-designed somehow.

**Comment by Firstyear** [comment]
IIRC the brew cask install is coming from the official DMG, it's not compiled? 

Anyway, I agree, the device scanning is in the main ui thread, so it should be re-done somehow :)

**Comment by parafin** [comment]
Ah, didn't know that. Well, let's keep this ticket open.

**Comment by grudgingly** [comment]
I have pretty much the same issue (Darktable's "frame rate" slows to 1 every few seconds) with the 3.0.1 release on Arch Linux with an Android phone.

**Comment by CalvinBroadhurst** [comment]
Just worked out that this, or very similar, is what has been causing me problems recently.
Ubuntu 18.04
Darktable 3.0.1
USB connected Android tablet (Samsung Tab S) (was connected but not even powered up, just charging)

I could start Darktable fine and use it for a short time but then it would freeze. Tried reinstalling etc with no luck. Eventually came across this issue and out of curiosity unplugged the tablet. Since then no problems at all.
