### ISSUE TITLE
if Filmic is designed to replace base curve, then Base curve shouldn't be in the default settings... right?

### ISSUE THREAD

**Issue by magicgoose** [darktable-org/darktable#4255]
**Is your feature request related to a problem? Please describe.**
As I read in the recent changelogs:
> A new module 'filmic RGB' which, like the previous 'filmic', **is designed to replace 'base curve',** 'shadows and highlights' and other global tone-mapping modules.

If base curve is considered as something that needs **replacement**, does it make sense to not include it in the default presets? Because it isn't a best practice anymore?  
(currently, when I open some raw files without any existing settings, they get started with base curve included)

**Describe the solution you'd like**
Some sensible values should be chosen as default for Filmic, and used in default settings as replacement to Base curve.  
(if you agree with the idea, I can try to contribute a preset that works okay for my camera at least... I know there's a lot of cameras, so some of them probably will never get default settings update, but it can be done for some of them at least)

**Alternatives**
...the alternative is to do nothing, I guess

**Additional context**
https://github.com/darktable-org/darktable/releases/tag/release-3.0.0

**Comment by TurboGit** [comment]
Right ! And this is possible already, see preferences where you can disable the base curve.

**Comment by magicgoose** [comment]
I know it's possible, I'm talking about default settings.
