### ISSUE TITLE
improve consistency handling of drawn masks

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#4257]
**Describe the bug**
dealing with masks has different options in different cases (path drawn by brush, closed path):
- scale the whole mask (by scrolling if created by closed path tool)
- increase/decrease feather radius ( shift+ scroll in former versions
- increase/decrease opacity (ctrl+scroll in former versions)
- increase hardness (scroll if path was created by brush tool)

**Expected behavior**
- a reliable way to scale masks (path drawn by brush as well as closed path)
- changing hardness isnt indicated like changing opacity
 
**Platform (please complete the following information):**
 - Darktable Version: darktable 3.1.0+584~g14aea9450
 - OS: OSX

**Comment by MStraeten** [comment]
Not fixed or triaged yet

**Comment by johnny-bit** [comment]
Hey! I think I fixed that in https://github.com/darktable-org/darktable/pull/7596 :) Can you check and close if so? And if not - what's missing?

**Comment by MStraeten** [comment]
closed path/circle/elipse:
- scroll: size
- shift scroll: feather size
- ctrl scroll: opacity

brush:
- scroll: hardness
- shift scroll: feather size (even it's named size instead of feather size
- ctrl scroll: opacity

there's no way to change the scale the brush stroke - so it's not a naming issue. Pretty sure that might be "works as designed" ...

**Comment by johnny-bit** [comment]
now shift+scroll changes brush size (thickness) post-planting the brush stroke. you'd call that feather size?

there's FR for changing brush size instead of "as a whoile" but on the nodes in #6622

There's no way to "scale" brush stroke (dunno how that could work, after all you CAN scale path)...

so what you're proposing would change brush tool a bit to match what circle tool does in terms of scalling central element and feathering?

**Comment by MStraeten** [comment]
in current master implementation the combination of changing size (shift+scroll) and hardness (scroll) for brush masks is similar to feather (shift+scroll) for closed path masks. 
If there’s no way to make brush stroke masks scalable (like scroll for closed paths) then this obviously  makes sense since it gives more control how to deal with brush behaviour (width as well as feathering). So the inconsistency is acceptable in this case.
#6622 is a further step - it's intention is to make brush stroke width and feathering customizable for each node (similar to the ability to change the feather size for closed paths by moving the node of the feather outline)

**Comment by johnny-bit** [comment]
So... Would you still want to pursue fixing the inconsistency or is it acceptable enough given current ui fixes + possible improvements in form of #6622 so this issue could be closed?

**Comment by MStraeten** [comment]
Let’s start with #6622, i'd prioritize this since this would give more benefits ...
