### ISSUE TITLE
Segfault in _upgrade_library_schema_step

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#4258]
**Describe the bug**

Darktable crashes while attempting to upgrade library db schema from 20 to 21. It starts correctly after deleting `library.db` file. I use my own build of Darktable with gcc 9.2.0. If necessary I can rebuild it with debug symbols on.

**To Reproduce**
1. Start `darktable`
2. Click on `upgrade database`

**Platform (please complete the following information):**
 - Darktable Version: 14aea945016ae29962443636224cc3436e9d7e57
 - OS: Gentoo Linux
 - OpenCL - disabled
 - Mesa-20.0.0_rc2, AMD Radeon Fury

**Backtrace
[darktable_bt_6Y0RF0.txt](https://github.com/darktable-org/darktable/files/4176984/darktable_bt_6Y0RF0.txt)

**Comment by TurboGit** [comment]
Could you make the library.db available ?

**Comment by tomaszg7** [comment]
http://tomaszg.pl/darktable/library.db.gz

**Comment by TurboGit** [comment]
Should be fixed a very stupid error on my side ! Can you test again ?

**Comment by tomaszg7** [comment]
Seems to work!

I get some assert fails, but I don't know if they are related, just pasting here for reference.
```
(darktable:13252): GLib-CRITICAL **: 16:34:39.639: g_strlcpy: assertion 'src != NULL' failed

(darktable:13252): GLib-GObject-CRITICAL **: 16:34:42.474: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed

(darktable:13252): Gtk-CRITICAL **: 16:34:42.474: gtk_widget_get_has_tooltip: assertion 'GTK_IS_WIDGET (widget)' failed
```

**Comment by TurboGit** [comment]
The:
> g_strlcpy: assertion 'src != NULL'

is because you have a null operation in history for image 4192.

This means that your db is broken for this image. You may want to reinitialize the history stack. Note that 4192 contains a single entry in history db (the one with NULL operation).

**Comment by tomaszg7** [comment]
Thanks, I'll probably just delete whole db, all relevant info is in any case in sidecar files.
