### ISSUE TITLE
darktable 3.0 crash when trying to delete a "virgin" duplicate from darkroom

### ISSUE THREAD

**Issue by pahl34** [darktable-org/darktable#4260]
**Edit:** Only now I saw that there is already issue #4061 ("Deleting duplicate crashed DT)- my entry might be a duplication of that one. However, as I cannot judge myself on a technical level whether it is the same root cause, I will still submit this - feel free to close as duplicate though in case it turns out to be the same problem.

I had a photo (jpeg) loaded in darkroom which I had already done some minor editing on in an earlier session (this time, after loading the photo, I had not yet done any more editing).
In order to quickly compare with the unedited version, I created a new duplicate without any editing ('virgin duplicate').
I used this to compare by left-clicking and releasing several times on the duplicate instance in duplicate manager on the left side of darkroom.

Afterwards I removed the duplicate by clicking on the 'x' right next to it.
The dialog asking whether this picture should be sent to trash popped up and I confirmed.
Afterwards I could see the "skull" symbol instead of the delted duplicate that gets shown for files that are not found any more on the hard drive for a short moment. Then, maybe a second later, another popup appeared stating that darktable had crashed and the backtrace log would be written.
After confirming this popup, darktable was closed.

I am running darktable 3.0 under Windows 10 Home Edition.

The log file is attached to this bug entry.

If it should help, I would also be okay with sharing that particular picture file and the sidecar file.

[darktable_bt_LBI7F0.txt](https://github.com/darktable-org/darktable/files/4177051/darktable_bt_LBI7F0.txt)

**Comment by Mark-64** [comment]
This should have been fixed in 3.0.1
