### ISSUE TITLE
seg fault with darktable-generate-cache

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#4263]
```
[...]
image 991/53007 (1,87%) (id:2094)
image 992/53007 (1,87%) (id:2095)
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (77) image 2095 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] base module set as not used watermark (77) image 2095 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorout gamma module gamma (2) is before colorout (65) image 2095 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorout gamma module colorout (65) is after gamma (2) image 2095 (dt_dev_read_history_no_image end)
[dt_ioppr_transform_image_colorspace] module gamma must be between input color profile and output color profile
Segmentation fault
```

gbd is installed but the created log file is empty.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+585~gd7809c3a6-dirty
 - OS: Debian 10
 - Opencl activated for darktable. I don't know for darktable-generate-cache
 - NVIDIA Corporation GP107 [GeForce GTX 1050 Ti]

**Other info.**
i get the same seg fault with darktable when I open the corresponding folder, same message but no log file created. lighttable doesn't finish its display.
If I disable opencl before the doing the same I get this log file:
[darktable_bt_6CU9F0.txt](https://github.com/darktable-org/darktable/files/4177818/darktable_bt_6CU9F0.txt)

Seems to fail on image 2096:

![image](https://user-images.githubusercontent.com/23012047/74110403-0c68cc80-4b6b-11ea-8d07-bbf5ff812265.png)

Doesn't fail with a former a 2.7 database.

**Comment by TurboGit** [comment]
You version string does not exists in the repository, the sha-1 does not exists and the 585 should be:

release-3.1.0-585-gebfdd064e

**Comment by phweyland** [comment]
> You version string does not exists in the repository

Right, that was my lut3d-3dl branch.

With my current master  (3.1.0+584~g14aea9450) I have the same issue.

**Comment by phweyland** [comment]
Currently dt crashes only when opening image 2095. This gives me the chance to override its stack with another one. 
Once done, darktable-generate-cache can continue.
BTW I have tons of :
```
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 2708 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule flip clipping module flip (20) is after clipping (16) image 2708 (dt_dev_read_history_no_image end)
```

**Comment by TurboGit** [comment]
Ok, I reopen then.

**Comment by TurboGit** [comment]
> > You version string does not exists in the repository
> 
> Right, that was my lut3d-3dl branch.
> 
> With my current master (3.1.0+584~g14aea9450) I have the same issue.
> [darktable_bt_MA17F0.txt](https://github.com/darktable-org/darktable/files/4180633/darktable_bt_MA17F0.txt)

What was the DB history and module_order entries for 2095 ?

**Comment by phweyland** [comment]
history:
![image](https://user-images.githubusercontent.com/23012047/74152625-77f37e00-4bed-11ea-96dd-d66dcf826cb8.png)

mdoule_order:
flip,0,gamma,0,rawprepare,0,invert,0,temperature,0,highlights,0,cacorrect,0,hotpixels,0,rawdenoise,0,demosaic,0,mask_manager,0,denoiseprofile,0,tonemap,0,exposure,0,spots,0,retouch,0,lens,0,ashift,0,liquify,0,rotatepixels,0,scalepixels,0,clipping,0,toneequal,0,graduatednd,0,basecurve,0,bilateral,0,profile_gamma,0,hazeremoval,0,colorin,0,basicadj,0,colorreconstruct,0,colorchecker,0,defringe,0,equalizer,0,vibrance,0,colorbalance,0,colorize,0,colortransfer,0,colormapping,0,bloom,0,nlmeans,0,globaltonemap,0,shadhi,0,atrous,0,bilat,0,colorzones,0,lowlight,0,monochrome,0,filmic,0,filmicrgb,0,colisa,0,zonesystem,0,tonecurve,0,levels,0,rgblevels,0,rgbcurve,0,relight,0,colorcorrection,0,sharpen,0,lowpass,0,highpass,0,grain,0,lut3d,0,colorcontrast,0,colorout,0,channelmixer,0,soften,0,vignette,0,splittoning,0,velvia,0,clahe,0,finalscale,0,overexposed,0,rawoverexposed,0,dither,0,borders,0,watermark,0

xmp:
[20180616_Cassel_030.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/4180901/20180616_Cassel_030.NEF.xmp.txt)

**Comment by TurboGit** [comment]
Not sure if it is the reason but 2095 seems to have a broken history, you should not have gamma and rawprepare with the same num value.

**Comment by TurboGit** [comment]
BTW, even all the rawprepare should have different num value.

**Comment by phweyland** [comment]
That's the only broken image out of 50.000. This is not an issue for me. 
If you think this is not worth more work, please close the issue.

**Comment by TurboGit** [comment]
Ok, let's close this. Probably a broken history.
