### ISSUE TITLE
NIKON Z 50

### ISSUE THREAD

**Issue by jcmt2k** [darktable-org/darktable#4264]
I can not open a RAW file in Darktable

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
That camera is only supported i in darktable git master, not in any stable release yet.
