### ISSUE TITLE
Darktable 3.0 Flatpak themes broken

### ISSUE THREAD

**Issue by hcw70** [darktable-org/darktable#4269]
**Describe the bug**
If changing themes in the 3.0 flatpak version to something other than the default theme, most themes show empty squares instead of the texts, so GUI becomes unusable. 

**To Reproduce**
Go to preferences and change theme to i.e. "darktable-icons-darker".

**Screenshots**
See screenshot

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Ubuntu 19.10 
 - OpenCL activated
 - Which graphics card and driver version: NVidia GTX960M, Version 435.21

![Bildschirmfoto vom 2020-02-10 11-10-30](https://user-images.githubusercontent.com/1888459/74140957-59de4b80-4bf6-11ea-9354-d69b9cf77cb9.png)

**Comment by rabauke** [comment]
This issue should be reported to https://github.com/flathub/org.darktable.Darktable, where it might get more attention.

**Comment by hcw70** [comment]
Ok will report there.

**Comment by hcw70** [comment]
Reported at https://github.com/flathub/org.darktable.Darktable/issues/50
