### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by yraen69** [darktable-org/darktable#4270]
Please make these kinds of boxes text input, I would really like to speed up my workflow by being able to click into the colour temperature box and typing with the keypad 5200 and press enter! Using the sliders or keyboard is so clunky and the mouse is extremely inaccurate.

![Text_Input](https://user-images.githubusercontent.com/17959135/74149171-1e696e80-4c42-11ea-850d-bba9565adfe1.PNG)

**Comment by elstoc** [comment]
Right click on the slider then type the number and hit enter.
