### ISSUE TITLE
[3.0.0] white balance adjustment not shown in light table view

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#4278]
**Describe the bug**
When you edit the white balance of a RAW, and you switch back to light table view, the preview will not show the new white balance. I also tried to exit darktable and run darktable-generate-cache

**Platform:**
 - Darktable Version: 3.0.0 from Fedora repository
 - OS: Fedora 31
 - OpenCL activated
 - amdgpu in kernel 5.4.8-200.fc31.x86_64

**Additional context**
 - Can you reproduce with another Darktable version?
I cannot try
 - Can you reproduce with a RAW or Jpeg or both?
I tried only with RAW files

**Comment by ptilopteri** [comment]
I would guess you have configured dt to use the included jpg preview and it still is as it never changes, you do not actually edit the raw where the jpg is contained.
Change the preference,
  GUI options -> (lighttable) don't use embedded preview JPEG bu half-size raw
ADD CHECK TO TURN IT ON.

**Comment by ptilopteri** [comment]
@Germano0 if this solves your problem, please close this issue

**Comment by parafin** [comment]
Might be that logic that chooses whether to use embedded thumbnail doesn't consider changing white balance as modification (since wb already exists in default history), which is wrong. Workaround is indeed to change that option in preferences.

**Comment by johnny-bit** [comment]
I think this is set of problems that are fixed by recent PRs of @phweyland, like #4322 among others. All tagged for 3.2 release.

**Comment by johnny-bit** [comment]
Works great in master and was most likelly fixed with #4322
