### ISSUE TITLE
Cannot find Chinese in the interface language list

### ISSUE THREAD

**Issue by timothyparez** [darktable-org/darktable#4283]
**Describe the bug**
Using version 3.0.0 on Windows or Ubuntu I cannot find `Chinese` in the  
interface language list.

**To Reproduce**
1. Start Darktable (On Windows or Ubuntu)  
2. Open the `Darktable Preferences` dialog   
3. Click the `Interface language` combobox  

**Expected behavior**
See Chinese in the list as it is mentioned on the website and there are    
even pull requests with updates to the Chinese translations.  

**Screenshots**

![image](https://user-images.githubusercontent.com/2060470/74398058-5266ae80-4e51-11ea-889a-9d6fc32e8bdd.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.0.0
 - OS: Windows 10, Ubuntu 19.10
 - OpenCL Activated
 - GeForce GTX 1060 (432.00), GeForce MX250

**Additional Info**
 - If Chinese language support was removed because it is incomplete  
   that's great but how do I enable the incomplete version anyway  
   so that perhaps we can assist in translating it.

**Comment by MStraeten** [comment]
it seems it's just incomplete - there's no chinese po file in the darktable 3.0.x branch ...

**Comment by TurboGit** [comment]
Indeed deactivated because too many untranslated messages:

> 1574 translated messages, 643 fuzzy translations, 914 untranslated messages.

To have it back you need to build yourself the master (unstable) branch of darktable.
