### ISSUE TITLE
In Retouch, heal/clone using brush has reduced opacity

### ISSUE THREAD

**Issue by timstanbrook** [darktable-org/darktable#4293]
**Describe the bug**
Using retouch module, if the retouch area is drawn using the brush, the cloned part is not copied properly to the destination area. It works ok if area is drawn using circle, ellipse or path.

**To Reproduce**
In darkroom:
- Open retouch module
- Select clone
- Select brush
- Draw line in image using brush tool
- Right click to exit drawing mode
- Drag 'from' line to different part of image
- Source image is copied to destination area but with reduced saturation or brightness, as if opacity of clone is not 100%.

Same happens with heal, although not always so obvious since healing function can affect colour or brightness.

**Expected behavior**
Clone and heal using brush mode should work the same as circle, ellipse or path, with source image copied across accurately.

**Screenshots**
Circle and irregular shape, bottom and middle were cloned using circle and path respectively.
Line at top  was cloned using brush. Clone done with brush is not copied across accurately, as if mask opacity is about 75%, although it is set to 100%. The other two are correct.

![Screenshot from 2020-02-14 20-48-54](https://user-images.githubusercontent.com/61063374/74566545-9fd73e80-4f6b-11ea-97a1-5c76ea627521.png)
![Screenshot from 2020-02-14 20-49-05](https://user-images.githubusercontent.com/61063374/74566547-a06fd500-4f6b-11ea-91bb-d0af9b6d24a0.png)
![Screenshot from 2020-02-14 20-49-19](https://user-images.githubusercontent.com/61063374/74566550-a1086b80-4f6b-11ea-95fe-12f58e673097.png)

**Platform (please complete the following information):**
 - Darktable Version: V3.0.0
 - OS: Ubuntu 18.04

**Comment by elstoc** [comment]
It's not clear from your screenshots what the opacity of the brush shape is. If you hover over the brush (as you have for the ellipse), it should display in the top bar. Don't forget this is different to the opacity of the *mask*, which displays in the module. You could also try turning the mask view on to see if it really is an opacity thing (black circle in grey square towards the bottom of the module). If the opacity is the issue the brush should be a lighter shade of yellow.

An xmp file might help too.

**Comment by TurboGit** [comment]
Will be fixed in 3.0.1 this issue has already been reported many many times !
