### ISSUE TITLE
PATCH: CMakeLists.txt cannot derive dt version from a git "worktree add" workdir

### ISSUE THREAD

**Issue by mandree** [darktable-org/darktable#4294]
**Describe the bug**
If darktable is built from Git and specifically from a working directory obtained with "git worktree add", darktable does not properly derive its version, and states "unknown version" instead.

**To Reproduce**
1. clone from git, and cd into its directory
2. `git worktree add ../try.git BRANCH` # where BRANCH needs to be a valid branch other than the one chcked out
3. `cd ../try.git`
4. `cmake -GNinja`
5. `ninja`
6. `src/darktable --version`
```
$ src/darktable --version
this is darktable unknown-version
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org
```

**Expected behavior**
Version derived properly

**Platform (please complete the following information):**
Fedora Linux 31, Darktable Git master as of 02f4f1e52, CL/GFX irrelevant

This patch should be fit for `git am` and fixes the issue for me:
[0001-Make-compatible-with-git-worktrees.patch.txt](https://github.com/darktable-org/darktable/files/4208253/0001-Make-compatible-with-git-worktrees.patch.txt)

**Additional info**
The cause is that in git worktrees, .git is only a file `gitdir: /path/to/repository`, not a directory, so the CMakeLists.txt doesn't accept it for "git checkout".

**Comment by TurboGit** [comment]
Looks correct to me. Thanks.

**Comment by TurboGit** [comment]
Merged.

**Comment by mandree** [comment]
should this be merged/cherry-picked to other active branches, too?

**Comment by TurboGit** [comment]
This is mostly useful for devs, so really I don't plan to have this in other branches.
