### ISSUE TITLE
Assigning representative image of group not working

### ISSUE THREAD

**Issue by timstanbrook** [darktable-org/darktable#4295]
**Describe the bug**
From user guide "Grouping": _"The interesting case is when the toolbar G is turned on. Now you can expand grouped images by clicking on the G in the thumbnail frame and collapse the group again with another click."_ This doesn't work, clicking on G in the thumbnail of collapsed group has no effect. 

From user guide "Grouping": _"Once a group is expanded you can change the representative of the group by clicking its G. This will be the image that is shown when the group is collapsed."_. When a group is expanded (which can only be done with the top toolbar G button), there is no G shown in the thumbnail frame. So it is not possible to assign the representative image for the group. The collapsed group always shows the first image as representative.

**Screenshots**

First screenshot shows collapsed group
![Screenshot from 2020-02-15 13-13-06](https://user-images.githubusercontent.com/61063374/74588559-65b27f00-4ff5-11ea-968a-7a69b273f359.png)
Second screenshot, expanded group (using top toolbar G button)
![Screenshot from 2020-02-15 13-15-10](https://user-images.githubusercontent.com/61063374/74588571-72cf6e00-4ff5-11ea-9660-5fa76aff2649.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Ubunutu 18.04

**Comment by AlicVB** [comment]
Already reported (don't remember when). I'll be fixed in my upcoming lighttable rewrite.

**Comment by AlicVB** [comment]
should be fixed in master
