### ISSUE TITLE
Adding file name to image infos line messes with window size

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#4297]
**Describe the bug**
When I add $FILE_NAME to image infos line in darkroom, darktable expands window size to let the file name fit in.
In small displays like mine (1366 x 768), darktable window goes beyond the screen size, and doesn't allow shrinking.

**To Reproduce**
1. Get a small screen computer like 1366 x 768
2. Add $FILE_NAME to the image infos line
3. Open an image file with a big file name
4. Enter darkroom.

**Expected behavior**
darktable window expands beyond the screen limits.
If you drag this window to the right and try to resize it laterally, it doesn't allow.

**Screenshots**
With a big file name
![Screenshot from 2020-02-15 13-08-18](https://user-images.githubusercontent.com/46730249/74591321-ca6dd980-4ff5-11ea-94cb-79cf184bebd9.png)

After removing $FILE_NAME from the image infos line
![Screenshot from 2020-02-15 13-09-05](https://user-images.githubusercontent.com/46730249/74591309-b629dc80-4ff5-11ea-961d-0f780ff74945.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0~git590
 - OS: ubuntu 18.04

**Additional context**
I've been facing this issue for some time now, and I was never been able to understand what was happening until today, when I did a local copy and the file name got bigger than normal.
Ideally, the infos line should get croped to keep the window size unchanged.

**Comment by AlicVB** [comment]
confirmed, see PR #4336 for a possible fix.
Thanks for reporting
