### ISSUE TITLE
Lightroom like lighttable

### ISSUE THREAD

**Issue by borissmidt** [darktable-org/darktable#4304]
**Is your feature request related to a problem? Please describe.**
I have been using lightroom and darktable in parallel for some time to compare them. I generally prefer darktables darkroom since the processing is much more rich, i.e. parametric masks, different kinds of denoise and the history stack. 

The lighttable for rating is  a bit clunky. The if you go to preview modus, (alt-w) and you exit this modus then you loose the place where you where at. There is no easy way to compare photos in this modus.

So my feature request would be to have somekind of 'viewing' modes. One that is just the current normal one, another one is full screen preview with a smaller 'gallery' on the bottom and an XY compariison. 

I know i can open a buttom film roll in the preview modus but then the interaction between the current selected image and the arrow just isn't correct. i.e. i double click on an image then it becomes the preview, but when i use the arrow it then continues form the image before i doulbe clicked an image.

If i leave the preview modus then i don't know where i was at.

I could add some screenshots if required, i had a look at the darktable code but my C/gtk expecience just doesn't cut it to make such a big change.

**Comment by Nilvus** [comment]
That's call culling mode and it already exist since darktable 3.0. Please see this article describing new features of darktable 3.0 and especially how to use culling mode with possibility to compare images, from 2 to 4 with paning and zooming options, and more images without panning and zooming ; https://www.darktable.org/2019/12/darktable-30/. And to have a smaller 'gallery', you have filmstrip.

**Comment by borissmidt** [comment]
Oh cool, i found it even tough it was a bit hidden, The only thing i notice is that is is quite slow since i preview on a 4k screen. Is it possible to force precalculate all photos in a film roll?

I already have my cache size at 4GB.

**Comment by Nilvus** [comment]
> Oh cool, i found it even tough it was a bit hidden, The only thing i notice is that is is quite slow since i preview on a 4k screen. Is it possible to force precalculate all photos in a film roll?
> 
> I already have my cache size at 4GB.

How to "precalculate" is also written on the article. And you could also check some options about images cache on preferences, core tab.

Reading this article will help you seeing how many great features (and how to use them), darktable 3.0 brings. And think about closing this issue. Thanks.
