### ISSUE TITLE
filmicrgb: lost "target power transfer function" slider and grey output image

### ISSUE THREAD

**Issue by burrima** [darktable-org/darktable#4306]
**Describe the bug**
While using the filmicrgb module all of a sudden the image turned gray and the "target power transfer function" slider lost its text markings (see screenshot). It is also not possible anymore to change the slider value. Right-clicking does not show the curved line (usually used to fine-tune the settings, don't remember the correct name).

**To Reproduce**
Option A:
Use attached NEF and xmp files.

Option B:
Play around with the color pickers in the "scene" tab of the filmicrgb module. Click as wild around as you can and also click on the different gray/black/white sliders from time to time. Issue usually arises in seconds up to a minute or so (race condition?).

I observed it with opencl switched off, but not sure if that has an influence since loading the xmp also makes the problem show up even when opencl is enabled.

**Expected behavior**
Clearly, the settings chosen do not make a lot of sense (they were generated by the color pickers, but this is not scope of this bug). Bad settings are expected to produce unpleasant output. But for sure not the UI to lose the slider functionality.

**Screenshots**
![Screenshot from 2020-02-16 17-55-07](https://user-images.githubusercontent.com/60112136/74608948-aee1fc00-50e5-11ea-8aa4-02f434df92a7.png)

**Platform (please complete the following information):**
 - Darktable Version: master 5b603860aac8ed3910e2f92a518495abf3f184b4
 - OS: Ubuntu 18.04
 - OpenCL deactivated (but xmp shows same behavior with opencl enabled)
 - NVidia GeForce GTX 1060 3GB, nvidia driver 340.107

**Additional context**
- Compressing the history has no influence.
- Switching all modules off (except filmicrgb) has no influence.
- Enabling/disabling filmic has no influence.
- Copy/pasting the whole history stack to another image reproduces the same issue on the other image.
- screenshot shows softproof on but disabling it has no effect (bit darker gray but no effect on filmic)

NEF file: https://burrima.ch/dl/DS5_3973.NEF
XMP file: [DS5_3973_01.NEF.zip](https://github.com/darktable-org/darktable/files/4210299/DS5_3973_01.NEF.zip)

**Comment by burrima** [comment]
Maybe related to #4153? I also see a black image on my other system - Lenovo ThinkPad T490 inside an Ubuntu 18.04 virtual machine.

When loading the xmp with `darktable -d nan`, I get this output:

````
[dev_pixelpipe] module `raw black/white point' min: (0.000938) max: (1.057842) [full]
[dev_pixelpipe] module `demosaic' min: (-0.089725; -0.081798; -0.079258) max: (1.225846; 1.246555; 1.259992) [full]
[dev_pixelpipe] module `input color profile' min: (-70.141052; -277.009338; -142.152985) max: (107.856674; 84.908844; 189.529922) [full]
[dev_pixelpipe] module `filmic rgb' outputs NaNs! [full]
[dev_pixelpipe] module `filmic rgb' min: (340282346638528859811704183484516925440.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000) [full]
[dev_pixelpipe] module `output color profile' outputs NaNs! [full]
[dev_pixelpipe] module `output color profile' min: (340282346638528859811704183484516925440.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000) [full]
[dev_pixelpipe] module `raw black/white point' min: (0.001542) max: (1.057842) [preview]
[dev_pixelpipe] module `demosaic' min: (-0.107641; 0.000000; -0.057649) max: (1.123095; 1.057842; 1.135556) [preview]
[dev_pixelpipe] module `input color profile' min: (1.983736; -281.866241; -65.965256) max: (103.379364; 37.075012; 208.588440) [preview]
[dev_pixelpipe] module `filmic rgb' outputs NaNs! [preview]
[dev_pixelpipe] module `filmic rgb' min: (340282346638528859811704183484516925440.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000) [preview]
[dev_pixelpipe] module `output color profile' outputs NaNs! [preview]
[dev_pixelpipe] module `output color profile' min: (340282346638528859811704183484516925440.000000; 0.000000; 0.000000) max: (0.000000; 0.000000; 0.000000) [preview]
````

**Comment by burrima** [comment]
The slider is messed up because in `gui_update()` the method `dt_bauhaus_slider_set_soft()` is called with an output_power of -nan.

**Comment by aurelienpierre** [comment]
Did #4800 fix it ?

**Comment by burrima** [comment]
I'll check tomorrow and I'll let you know

**Comment by burrima** [comment]
Can't reproduce it anymore with #4800 , but also the sliders feel much more responsive. So, maybe I just cannot click fast enough anymore. Anyway, since I can't reproduce it, I would suggest to close the issue and re-open if needed.
