### ISSUE TITLE
Rejected image jumps in front of the first image taken at the same time

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#4307]
**Describe the bug**
When two images have the same date and time, 2020-02-16 15:15, sorting by

 time and not file name and rejecting the second one makes it jump in front of the first one. When also rejecting the first one, the second one jumps back.

**To Reproduce**
1. Sort by date in lighttable or darkroom
2. Two raw files taken at the same time, File1 has been captured 15:15 and File2 has been captured 15:15
3. Reject File2.
4. The order of the files are now File2 and File1
5. By rejecting also File1 the order is now File1 and File2 as it should be.

**Expected behavior**
In darktable 2 the images didn't move around in front of each other.

**Screenshots**

![1](https://user-images.githubusercontent.com/34200649/74612976-9506e000-510a-11ea-9202-dcbeec6beb3f.jpg)
![2](https://user-images.githubusercontent.com/34200649/74612978-9801d080-510a-11ea-9d55-94987f8ed6d6.jpg)
![3](https://user-images.githubusercontent.com/34200649/74612979-9a642a80-510a-11ea-9436-da68a6af62d0.jpg)

**Platform (please complete the following information):**
- 3.1.0~git663.f475769ed
 - Ubuntu 18.04
 - OpenCL activated

**Comment by progo** [comment]
I am observing the same behavior too, darktable 3.0.0.
