### ISSUE TITLE
Fujifilm X-T30 noise profiles

### ISSUE THREAD

**Issue by romanj85** [darktable-org/darktable#4308]
Hi,

Here is a noise profile for the Fujifilm X-T30: [darktable-noiseprofile-20200216.tar.gz](https://github.com/darktable-org/darktable/files/4211067/darktable-noiseprofile-20200216.tar.gz)

I followed the instructions at https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/.

From my testing it seems to work quite nicely. Please check it and if you would want, I can make antoher photos and the noise profiles again, otherwise please include it in darktable!

Thank you & best regards,
Roman

**Comment by TurboGit** [comment]
Now merged. Thanks.
