### ISSUE TITLE
Data race in compute_log_histogram in toneequal.c

### ISSUE THREAD

**Issue by mcv100** [darktable-org/darktable#4309]
**Describe the bug**
I was trying out and messing about with the tone equalizer and I found the behavior of the automatic mask exposure and contrast compensation very unpredictable. For instance, the histogram bar in the masking tab often spans to zero (-8 EV), even if the histogram clearly has no data around there.

**Debugging**
I built a custom version of Darktable, so that I could debug _compute_log_histogram_ and _histogram_deciles_ in _toneequal.c_. I found out that the total sum of the histogram is almost always lower than _num_elem_, which should definitely not happen (some pixels are not counted in the histogram). This leads to _last_pos_ being set to 0 if less than 90% of pixels are counted, giving rise to unpredictable behavior. 

The culprit can be found in the _compute_log_histogram_ function:

https://github.com/darktable-org/darktable/blob/8230fd80e13efa80027e58f667524286eadc707f/src/iop/toneequal.c#L1267-L1281

This for loop should not be parallelized, at least not in the way it is here. This will clearly lead to data race faults in incrementing _histogram_ in the threads (see e.g. https://stackoverflow.com/questions/26998183/how-do-i-deal-with-a-data-race-in-openmp). Commenting out the pragma fixes the problem in my testing.

**Possible fixes**
The easy fix is removing the omp pragma for this for loop of course. However, one may try to keep the code at least partially parallellized for performance. Perhaps have all threads work on their own version of _histogram_ with the _reduction_ clause?

**Comment by TurboGit** [comment]
I'll fix that. Thanks.

**Comment by mcv100** [comment]
Although this was tagged 3.0.1, as it stands, this fix (and less important, my improvement #4319) was not merged into 3.0.1. 

So still the exposure and contrast boost behave very funky. Not really a problem for me as I'm on master, but could be annoying for others.
