### ISSUE TITLE
[ToneEqualizer 3.1.x] Caused DT crash with backtrace.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4310]
[darktable_bt_K2G0F0.txt](https://github.com/darktable-org/darktable/files/4212035/darktable_bt_K2G0F0.txt)

**Describe the bug**
Crash in DT after crop and rotate followed by toneequalizer enabling.

this is darktable 3.1.0+663~gf475769ed reporting an exception:

-------------------

Error occurred on Monday, February 17, 2020 at 11:20:14.

darktable.exe caused an Access Violation at location 0000000065F45DAC in module libtoneequal.dll Reading from location 0000000018E68000.

AddrPC           Params
0000000065F45DAC 0000000005EBF9B0 0000000064942F28 0000000000000000  libtoneequal.dll!apply_exposure._omp_fn.0  [F:/msys64/home/chill/darktable/src/iop/toneequal.c @ 806]

   804:     for(size_t j = 0; j < out_width; ++j)
   805:       for(size_t c = 0; c < ch; ++c)
\>  806:         out[(i * out_width + j) * ch + c] = in[((i + offset_y) * in_width + (j + offset_x)) * ch + c] *
   807:                                             correction[(i + offset_y) * in_width + (j + offset_x)];
   808: }

**Expected behavior**

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+663~gf475769ed 
 - OS: Windows 10 
 - OpenCL activated
 - 

**Additional context**
I have had a hanper image edit in the current release and has toneequalizer related. Had to kill DT and restart it.
Constantly getting stuck in working label.
Moving the sliders fast on the tome equalizer can result in hang.
Brand new images never processed before while this has happened.

**Comment by Dave22152** [comment]
[darktable_bt_BE7HF0.txt](https://github.com/darktable-org/darktable/files/4214223/darktable_bt_BE7HF0.txt)


I am having a similar issue, where DT crashes after invoking the Tone Equalizer.

Describe the Bug:
darktable.exe caused an Access Violation at location 0000000065F4591C in module libtoneequal.dll Reading from location 000000001C3ED000.

Platform:
Darktable 3.0.0
OS: Windows 10
OpenCL not activated

Additional Context:
Computer seems to get bogged down shortly after invoking the Tone Equalizer, running slower and struggling through processing until DT crashes.

**Comment by TurboGit** [comment]
@Dave22152 : No maybe not same as you are using 3.0 and we had fixed a crash in master which is used by OP.

**Comment by Dave22152** [comment]
Pascal, thanks for the quick response. Perhaps not the same, but the behavior is similar and it’s a repeatable and frequent occurrence for me. 

As best as I know, I am using the latest version. What should I do at this point?  Would you like me to submit this as a new issue?

Thanks again,
Dave G.

**Comment by TurboGit** [comment]
@Dave22152 : Nothing to do for now, this will be just noise as there is chance that the issue you have is already fixed. So only if you can reproduce with current master you can create a new issue.

**Comment by TurboGit** [comment]
@chhil : Any change you could debug that? We already had some out-of-bound index and this looks like another instance. It would be good to know which index if out-of-bound in the code reported in line 806.

**Comment by Dave22152** [comment]
Ok, thanks. I do appreciate the quick response.

**Comment by chhil** [comment]
@TurboGit 
Unfortunately I can't debug it (not very capable of debugging in C/C++.

One additional thing I can add, moving sliders or cursors in modules like historgram, exposure,levels etc causes the dreaded working label getting stuck in darktable. I ahve also noticed whilst one cannot edit further (GUI remains responsive but eventually fails) export always seems to work. 
A single image edit takes a few process kills.

**Comment by Nilvus** [comment]
@chhil and @Dave22152 : could you precise which amount of RAM and Swap you have ? Which processor ? And which settings you have on core tab in preferences dialog window (settings about memory and threads) ?

**Comment by Dave22152** [comment]
Nicolas,

 

My system has 8GB of RAM, with an AMD A8-7410 APU with AMD Radeon R5 graphics.  If I understand your question correctly, my virtual memory is 12,288 MB.

 

Within Darktable:

Memory to use for thumbnail cache: 252

Enable disk backend for full preview cache: checked

Enable disk backend for full preview cache: not checked

Number of background threads: 8

Host memory limit for titling: 1511

Minimum memory for single buffer in titling: 16

Activate OpenCL support: not checked

OpenCL scheduling profile: default

 

Note that I have OpenCL disabled, because it causes my system to hang, forcing me to manually reboot…

 

Let me know if you need any other information

 

Dave G.

**Comment by chhil** [comment]
@Nilvus 

I am on a win 10 system.
32 GB Ram
Processor: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz, 2401 Mhz, 4 Core(s), 8 Logical Processor(s)

Dual low end graphic cards.
GPU 1: AMD FirePro M5100 : 2GB
GPU 2: Intel(R) HD Graphics 4600 : 1GB

Open CL **turned off**.

DT Core options
![image](https://user-images.githubusercontent.com/1119439/74896848-50ee3680-53bb-11ea-9588-64b92c3ad4f2.png)

Opencl test output
[opencl_test.txt](https://github.com/darktable-org/darktable/files/4228573/opencl_test.txt)

Intel Graphics card openl details 
![image](https://user-images.githubusercontent.com/1119439/74897399-fce45180-53bc-11ea-9300-bbf5e90ac868.png)

Amd Grahics card opencl details
![image](https://user-images.githubusercontent.com/1119439/74897538-65333300-53bd-11ea-9331-aa5e42e177cb.png)

**Comment by aurelienpierre** [comment]
> 804: for(size_t j = 0; j < out_width; ++j)
> 805: for(size_t c = 0; c < ch; ++c)
> > 806: out[(i * out_width + j) * ch + c] = in[((i + offset_y) * in_width + (j + offset_x)) * ch + c] *
> 807: correction[(i + offset_y) * in_width + (j + offset_x)];
> 808: }

That part should be rewritten anyway to use the (back)transforms and mask distortion IOP methods. I still have to figure out how.

**Comment by Nilvus** [comment]
> Host memory limit for titling: 1511

I suggest you to increase that a lot (about 6 or even 8 Go here would be good regardless your total amount of memory : RAM and Swap).

Anyway, for both of you that not RAM related. I have had some crash previously with a too small Swap (I only have 8Go of RAM).

**Comment by Dave22152** [comment]
Thanks Nicolas, I made that change. Would this help in system stability, speed, or both?

Also, I should mention than I’m having a problem with my PC freezing up when I have OpenCL enabled. I have to reboot and no backtrace is generated. Any recommendations, or should I submit a separate issue?

Thanks again!

Dave G.

**Comment by chhil** [comment]
No longer crashing, and I am on darktable-3.1.0+1026~g42e13e52b-win64
