### ISSUE TITLE
Mask crash DT

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#4312]
The creation of a mask crash darktable (Segmentation fault)
darktable 3.1.0+665~g8230fd80e, ubuntu studio 18.10, opencl on

**Comment by johnny-bit** [comment]
I can't confirm with same ver :/

Can you describe reproduction steps and attach RAW+XMP files exhibiting this behaviour?

**Comment by dim162** [comment]
I rework old images (done with Dt 2.6) with Dt 3.1 & i build a new database before, but i kept the old XMP. I work on duplicate. With the new raw, the mask crash sometimes even often, but here it's systematic when i create a mask through the manager or an instance/module. I give the historic (dtstyle) too.
[100EOS5D.zip](https://github.com/darktable-org/darktable/files/4213654/100EOS5D.zip)

**Comment by jade-nl** [comment]
I am able to reproduce your crash using the development version with the image provided in the zip file. I just the needed the image, no need for the xmp or the dtstyle file.

First thing I noticed: I do see the fully edited version (31 steps), this doesn't happen when using stable. The latter reverts to the 8 basic modules and I get the following error:

*[_dev_read_masks_history] _MG_9446.CR2 (imgid `174'): mask version mtory is 6, dt 4.*


Here's how I replicated the crash:

Starting with a fresh darktable (development version):
* load the image in darkroom view
* exposure module -> new instance
* select draw+parametric
* draw a line around the skin area
* when finishing (right click) dt crashes.

I've tried to catch it by using gdb, but darktable doesn't crash when using *gdb darktable etc*, but just hangs. Only way to stop is a kill -9 <pid>, which leaves you with no gdb data....

My setup:
* darktable version:
&nbsp;&nbsp;&nbsp;&nbsp;Stable 3.0.0
&nbsp;&nbsp;&nbsp;&nbsp;Development 3.1.0+685
* OS     : Linux - kernel 4.19.0-8-amd64
* Distro : Debian Buster (rel. 10.3)
* Graphics card   : NVIDIA GF104 [GeForce GTX 460] (rev a1)
* Graphics driver : NVIDIA x86_64 Kernel Module 390.116
* OpenCL activated : No
* Xorg : 7.7+19
* GTK+ : 3.24.5-1

**Comment by jade-nl** [comment]
**Update:**

I was able to use gdb and it started creating a very,very big text file, the same line over and over again. Killed the process after line 50000 (17MB file)

[gdb.txt](https://github.com/darktable-org/darktable/files/4221471/gdb.txt)

Steps as described above, instead of using kill -9 <pid> I used the little x on the window. Waited a while and it closed.

gdb steps take:
```
(gdb) run

(gdb) set pagination off
(gdb) set logging file gdb.txt
(gdb) set logging on
(gdb) thread apply all bt full
ctrl-c ctrl-c
(gdb)  next
(gdb)  next

```

**Comment by Nilvus** [comment]
@dim162 : could you precise which amount of RAM and Swap you have ? And which settings you have on core tab in preferences dialog window (settings about memory and threads) ?

**Comment by dim162** [comment]
It's a ryzen 7 2700x (8cores) + 32gb ram + gtx 1050ti (4gb), swap 2x4gb,
memory thumbnail cache 8000mb, background threads 8, host memory limit
16000mb, memory single buffer 24mb, ubuntu 18.10 studio on M2.1 ssd 250gb

Le mer. 19 févr. 2020 à 19:22, Nicolas Auffray <notifications@github.com> a
écrit :

**Comment by Nilvus** [comment]
> It's a ryzen 7 2700x (8cores) + 32gb ram + gtx 1050ti (4gb), swap 2x4gb, memory thumbnail cache 8000mb, background threads 8, host memory limit 16000mb, memory single buffer 24mb, ubuntu 18.10 studio on M2.1 ssd 250gb 

Ok, so that's exclude memory amount or settings origin.

**Comment by aurelienpierre** [comment]
> [_dev_read_masks_history] _MG_9446.CR2 (imgid `174'): mask version mtory is 6, dt 4.

That is typical of an image that has been edited with a newer darktable version, but then reopened with an older one. Mask version should be 6 for dt 3.1/master branch.

**Comment by jade-nl** [comment]
*slightly off-topic*

@aurelienpierre 
> That is typical of an image that has been edited with a newer darktable version, but then reopened with an older one.

Correct. I loaded  dim162's image which he edited in 3.1, as a test, in dt 3.0.

> Usually, it happens when git doesn't pull correctly, so I suggest you remove [....]

I don't think I understand this advise: I see this, as I now understand correct, behaviour in the terminal when using dt 3.0.0  This one is compiled from the official [tarball](https://github.com/darktable-org/darktable/releases/tag/release-3.0.0) (bottom of the page). I don't think I need to recompile anything. I do believe your advise would need to be followed if I see this behaviour in dt 3.1.X Right?

If not please elaborate.
