### ISSUE TITLE
About the mask's use

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#4314]
*I use a lot of masks & new instances... After 4 or 5 of them, it's difficult to follow which one is which one on the image without showing the mask (which began to be slow to display when i have a lot of mask...even with powerfull cpu+gpu)  , & moreover, in a new instance's mask, it's not possible to watch which mask is used, also when i work on a mask, the mask manager scroll up. So to remember which mask & instance are alloted to part of the image, i keep notes on PostIts. My dream: the possibility to rename instance & mask. 
*The brush mask act like the path mask witout all the brush mask's problems. To draw a mask with the brush, i use the tablet's stylet not the mouse. If i want to correct the brush stroke, i have to play with the path, & with the stylet,  it's not playable (handles are too small, too much réactive & the need of the mouse scroll)... So i have to leave the stylet to use the mouse... Fingers's gym!  A brush mask which stays a brush stroke, even during the stroke's correction (a negative paint) & shortcuts to simulate mouse scroll when moving the stylet on the mask, will be great. When the mask brush's stroke becomes a path, it's is in the stroke's middle, that's not revealing the real brush mask use, which is not only a path, but a whole surface. So i think that the mask brush's stroke need to be define by 2 paths near his border, parallel to his way, until that the brush's stroke close a surface.

**Comment by TurboGit** [comment]
> My dream: the possibility to rename instance & mask.

Your dream is already the reality. Please read the manual, this is so since some years now.

**Comment by dim162** [comment]
I can rename the mask but it appears only in the mask manager... It helps a
lot! And the module/instance?!


Le lun. 17 févr. 2020 à 15:08, Pascal Obry <notifications@github.com> a
écrit :
