### ISSUE TITLE
Nikon D7500 and Lumix LX100 Color matrix

### ISSUE THREAD

**Issue by kwazel** [darktable-org/darktable#4327]
Hej
I made a color profile as good as I can for the Nikon D7500. Because I currently do not have a big-brand flash I used my YN-465. I think the results are so much better (especially red for Nikon) than the standard color matrix, that I would like to contribute this result to Darktable already. Please let me know if I can/should do something different.
The matrix and the files used to create it can be found on https://github.com/kwazel/ICC_Profiles

**Comment by LebedevRI** [comment]
I don't know the state of dealing with custom camera color matrixes.
