### ISSUE TITLE
When opening a DNG file, darktable takes the embedded raw and not the linear 16 bit demosaiced raw content. 

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#4334]
**Is your feature request related to a problem? Please describe.**
When opening a DNG file which contains an embedded Raw file beside of the demosaiced Linear 16 bit RAW, DT seems to take the embedded raw file. 

**Describe the solution you'd like**
There should be an option to tell Darktable which content of the DNG file to open.

**Context**
Link to Fuji Raw/DNG file in here: 
https://theblog.adobe.com/enhance-details/

**Comment by parafin** [comment]
I don't think we should implement support for such corner cases. Using RAW makes sense for RAW-developer. Just export to TIFF if you want to use demosaiced image.

**Comment by GrahamByrnes** [comment]
In particular, the demosaiced linear tiff (which is what it is) inside the dng is not a definitive object: different choices of demosaic algorithm are available in dt which result in different outcomes. Choosing the version that happened first, possibly by historical accident, appears to be limiting. If you want to preserve the treatment already used, you could either select an algorithm that is the best match, or export it to tiff from the package that applied the special sauce (Capture 1? Lightroom?).

**Comment by aurelienpierre** [comment]
darktable is a raw software. We take raw in input when available.
