### ISSUE TITLE
misplaced modules in new iop order for png images 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#4345]
**Describe the bug**
found for an png used for editing:
```
[dt_ioppr_transform_image_colorspace_cl] module temperature must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module temperature must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module denoiseprofile must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module denoiseprofile must be between input color profile and output color profile
```
also after resetting module order to 3.0

**To Reproduce**
1. import a png created by an export of a raw file (without edits)
2. enable white balance, denoise etc.
3. set module order to defaul current order = v3.0 
4. back to lighttable , back to darkroom
5. see console output
[20191229-IMG_7599_02.png.xmp.txt](https://github.com/darktable-org/darktable/files/4237501/20191229-IMG_7599_02.png.xmp.txt)

**Expected behavior**
it just works

**Platform (please complete the following information):**
 - Darktable Version: 
```
this is darktable 3.1.0+650~g5d7f02ca0
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
```
 - OS: OSX

**Comment by TurboGit** [comment]
The messages were wrong, but the order and develop process ok. This is now fixed. Thanks.
