### ISSUE TITLE
darktable removes image completely in groupped mode

### ISSUE THREAD

**Issue by dmitryash** [darktable-org/darktable#4367]
**Describe the bug**

I found that deletion of duplicate if images are grouped leads to removal of whole image (inc. CR2 and all XMP files). This is important because I suppose that an user expect that only one copy (duplicate) of image is removed because left pane allows a removal of selected copy. The user may lose his image by accident.

**To Reproduce**

  1. Open darktable and open any image for editing
  2. Create a virgin copy of image on the left pane
  3. Switch to lightable
  4. Enable grouping of images ("G" button - Collapse groupped images) so that both copies are shown as one image now
  5. Open the same image in darkroom and try to delete a created on step 2 copy of image on left pane
  6. Click "yes"
  8. See that there is no image at all! No CR2, no both XMP files at all.

**Expected behavior**

Successful removal of *one* selected duplicate of image.

**Platform (please complete the following information):**
 - Darktable Version: 2.6.3
 - OS: openSUSE Leap 15.1

It also looks illogical that darktable removes image completely if I requested deletion of only one copy. This is really unexpected and a user can miss photo.

**Comment by johnny-bit** [comment]
Huh...
I tried to reproduce it on 3.1.0+697~ and it's a bit weird. I followed your step-by-step instruction and in 3.1.0 the darktable asks to delete 2 files when clicking "x" by created virgin copy. if I click yes then it actually doesn't delete raw, but deletes wrong xmp - i deletes 1st xmp, leaving behind the virgin duplicate xmp.

So - there are still some issues, but aren't as severe as in 2.6.3

Can you check if your problem is replicable on 3.0.0?

**Comment by dmitryash** [comment]
I'll need to compile by myself probably.

**Comment by johnny-bit** [comment]
for 3.0.0 you don't need to recompile - just get an official package. for "master" branch you have to ;) just keep backups.

**Comment by dmitryash** [comment]
> Huh...
> I tried to reproduce it on 3.1.0+697~ and it's a bit weird. I followed your step-by-step instruction and in 3.1.0 the darktable asks to delete 2 files when clicking "x" by created virgin copy. if I click yes then it actually doesn't delete raw, but deletes wrong xmp - i deletes 1st xmp, leaving behind the virgin duplicate xmp.
> 
> So - there are still some issues, but aren't as severe as in 2.6.3
> 
> Can you check if your problem is replicable on 3.0.0?

Tried latest commit 8887c1b055108e5d6e644d3843a84a2f19ca4513 and there are three issues:

  1. Darktable asks to delete 2 files in stead of one
  2. Incorrect xmp (duplicate) is removed
  3. Darktable still crashes (#4366)

**Comment by dmitryash** [comment]
However original CR2 file is not lost - that's much better.
