### ISSUE TITLE
Pixel pipe ordering for monochrome images

### ISSUE THREAD

**Issue by cribari** [darktable-org/darktable#4371]
**Is your feature request related to a problem? Please describe.**

Up until Darktable 2.6 the color correction module came after the monochrome module in the pixel pipe. The former is used by many users to cool or warm black and white images converted using the latter. However, in Darktable 3.0, color correction comes before monochrome in the pixel pipe and has no effect on B&W images converted using the monochrome module unless one manually reorders the pixel pipe so that color correction comes (as it used to do) after monochrome.

Since I mostly do B&W photography and I cool a tad my images using color correction, currently, I am having to manually reorder the pixel pipe for every image so that color correction comes after monochrome. 

**Describe the solution you'd like**

Color correction after monochrome in the pixel pipe. 

**Alternatives**

I do realize that users can make the B&W conversion using channel mixer and that color correction comes after channel mixer in the pixel pipe. However, many users prefer to use the monochrome module because small fine tuning adjustments to color hue and color lightness can be made using the color zones module and such adjustments affect the monochrome conversion. 

**Additional context**

For those who do a lot of B&W photography, it's important (IHMO) for color zones to come before the monochrome conversion and for color correction to come after it in the pixel pipe.

**Comment by GrahamByrnes** [comment]
First, there is a major re-write coming that will allow re-ordering.

Second, anything you can do with colour zones, you can also do inside the channel mixer, assuming you ignore the presets and choose your own mixture combination for the gray channel. That leaves you with the colour correction module after the B&W conversion. More than 95% of my photography is B&W and this works just fine for me.

That said, we all like to stick with what works... so perhaps you need to consider building a development version. Otherwise, you may have to wait a while for the flexible-order version.

**Comment by cribari** [comment]
@GrahamByrnes Thank you for your feedback. 

I am not sure that anything one can do with color zones one can also do inside the channel mixer. When using channel mixer one can perform very adjustments to color hue and color lightness prior to monochrome conversion. For instance, one can lighten only skin tones and darken only a certain range of blues (e.g., only light blue). I do have my own channel preset, but I find the use of colors zones -> monochrome -> color correction (in that order) to be more flexible. 

As for the color correction module, I believe it is quite useful to warm or cool B&W images. In order for that to work, however, it must come after monochrome in the pixel pipe (as it used to do). 

The ability to automatically reorder the modules in the pixel pipe will certainly solve my problem. Nonetheless, if the following change in the default ordering is harmless I believe it would benefit many users: color zones before monochrome and color correction after monochrome in the default pixel pipe. 

Again, thank you!

**Comment by cribari** [comment]
What is the Darktable devs decision on my feature request? Do they agree with it? Will it be implemented? Thank you.

**Comment by jenshannoschwalm** [comment]
Please note there are better ways to achieve what you desire.

You can change the pipeline order manually as you know. You can now define a module order preset and use that for you monochromes. Or you can "Copy&paste" module parameters & order ...

That would be the way ...
