### ISSUE TITLE
reopen image with mask doubles the masks

### ISSUE THREAD

**Issue by cimatosa** [darktable-org/darktable#4375]
If I draw a new mask on a fresh image and afterwards reopen the image the list of available shapes has doubled. Doing the step of reopening again causes again a doubling, the original shape appears 4 times. And so on.

 - Darktable Version: 3.1.0+745~gc044acf54
 - OS: Debian Linux
 - no OpenCL

I did a `git reset --hard` and `git pull` on the master branch as suggested in Issue #4312.

**Comment by johnny-bit** [comment]
Can confirm with current master.

Reproduction steps that work on RAWs, jpegs etc:

1. Open any image (can be fresh, can have edits, it doesn't matter) in darkroom
2. draw a mask. any mask will do. in oder to see the problem, open up mask manager.
3. leave darkroom.
4. open the same image in darkroom - see that number of masks is now 2
5. repeat steps 3&4 - each time number of masks shown doubles so 1->2->4->8->16->...

Additional note - moving ANY of those created masks moves all of them unless 1 of them is deleted, then all are back to original place

I've tested it a bit more and it's even worse... Here are steps to execute:
1. open fresh image (just needs no mask to work)
2. create mask
3. leave darkroom
5. enter darkroom and see that the mask is ther with it's twin
6. remove both masks
7. leave darkroom
8. enter darkroom and see that you now have 4 masks

the only way to get rid of duplicated masks is to clear history.

Additional fun:
1. create mask, name it "test1" or whatever recognizeable.
2. leave darkroom
3. enter darkroom
4. you now have 2x "test1"
5. rename 2nd one to "test2" and see that it's "test1" that got renamed

Additional fun:
6. leave darkroom, enter darkroom and see the makss named "test2", "test1", "test2", "test1"
7. rename 3rd to "test3"
8. leave darkroom, reenter darkroom and you'll see weirdness.

Another weird set of tests to do:
1. open fresh image
2. create 2 clearly distinct masks
3. leave and re-enter darkroom, you now have 4 masks. select first one to rename. see that the rename box is above 3rd mask. 

hmm... actually the rename box is always above 3rd mask if you try to rename 1st, 2nd & 3rd mask regardless whether those are mask you've actually drawn or are duplicated. for all others the rename box is drawn at the right place...

Generally - masks management is borked ATM... @TurboGit - can you please label this as a bug that needs attention?

**Comment by TurboGit** [comment]
Would be nice to check if this reproduce on 3.0.x branch. Also if someone has some spare cycle it would be nice to bisect to find the first wrong commit. Thanks.

**Comment by johnny-bit** [comment]
The problem is NOT reproductible with version `3.0.0+372~gef1c5bf74`
Therefore it is problem on current master only.

**Comment by TurboGit** [comment]
Ok, thanks for testing the release branch.

**Comment by johnny-bit** [comment]
During bisecting I sumbled upon problem with sqlite errors regarding history hash generation causing me to miss some steps...
However I managed to narrow down problem commits (duplicate masks) to follwing hashes:
```
$ git bisect bad
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
0651c9f965bfb3aa2a8e6a5cabe7089412bcfeb4
67a108319c4251f75ec19457f40c4d4aac91b44f
We cannot bisect more!
```
0651c9f965bfb3aa2a8e6a5cabe7089412bcfeb4
67a108319c4251f75ec19457f40c4d4aac91b44f

What's weird they don't deal with masks... those are all @phweyland's

I haven't checked UI problems only duplications. I'll try bisect again for pinpoint accuracy about masks duplications.

**Comment by TurboGit** [comment]
@phweyland : Can you have a quick look now that there is bisect data?

**Comment by johnny-bit** [comment]
Ok, so not wanting to edit more (some github errors like yesterday?):

`3.1.0+722~g67a108319` - BAD
`3.1.0+721~g0651c9f96` - Produces error in assert `x == SQLITE_OK`
`3.1.0+719~gd355d98bf` - GOOD

That's the closest bisect I can get.

**Comment by phweyland** [comment]
> table main.history_hash has no column named current_hash

I don't how, but it seems the db has no current_hash column. 
I remember having changed the name of the columns during development.
I don't know this is possible, but it seems the migration of your db did occur before the last renaming.

Can you check that your db is aligned with this:

![image](https://user-images.githubusercontent.com/23012047/75564554-1aec2a80-5a2b-11ea-8954-7781906009e1.png)

If this is not the case you have to migrate again a db before my first commit on this subject.

**Comment by phweyland** [comment]
commit 0651c9f965bfb3aa2a8e6a5cabe7089412bcfeb4
this commit rename the columns' names.

**Comment by phweyland** [comment]
the first commit of this PR is commit 6f61d3aa860ddc3d70b3bb60702ce6a1cc76d5e1

**Comment by phweyland** [comment]
I've just migrated an old db with the current master with no issue.

**Comment by TurboGit** [comment]
The duplicate masks are displayed where? Not in the iop module.

**Comment by TurboGit** [comment]
I see, this is in the masks manager, is that what you are reporting?

@phweyland : I can reproduce with current master it seems that the mask manager is getting crazy !!!

**Comment by johnny-bit** [comment]
@phweyland - plz ignore that `current_hash` thing.
plz focus on this steps:

1. Open any image (can be fresh, can have edits, it doesn't matter) in darkroom
2. draw a mask. any mask will do. in oder to see the problem, open up mask manager.
3. leave darkroom.
4. open the same image in darkroom - see that number of masks is now 2
5. repeat steps 3&4 - each time number of masks shown doubles so 1->2->4->8->16->...

Before commit 0651c9f96 it doesn't happen (c68c258af is last known good). after commit 67a108319 the issue with masks is present.

Can you look at changes done in those 2 commits (0651c9f96 and 67a108319) and see what affects masks?

**Comment by phweyland** [comment]
Just done it with new and image without xmp. This doesn't happen (only one mask)
With another image with xmp, -> dt crashes

I'll try to do what you request. But I've to leave soon and I'll be back only on Monday normally.

**Comment by phweyland** [comment]
@johnny-bit Have you check the table history_hash ?

**Comment by johnny-bit** [comment]
@phweyland - do you want me to check whether mask manager gets crazy at that specific commit that I can't check due to missing column?

No probl.

As for db - I check on completelly empty db (so each is generated at start for bisect check). I'll have to alter db manually then.

**Comment by TurboGit** [comment]
@phweyland : The only piece of code that could introduce the bug is you new  _dev_write_history() which add history items AND masks too.

**Comment by TurboGit** [comment]
This has been introduced in 67a108319c425 the first bad commit.

**Comment by phweyland** [comment]
> Before commit [0651c9f](https://github.com/darktable-org/darktable/commit/0651c9f965bfb3aa2a8e6a5cabe7089412bcfeb4) it doesn't happen ([c68c258](https://github.com/darktable-org/darktable/commit/c68c258af31542b2a527fc869588d4dc61418edd) is last known good).

commit [0651c9f] is not good in itself... I see some added columns in module_order which, hopefully are not there in the last commit.

What I moved around and added in some places is this:
`    dt_ioppr_write_iop_order_list(dev->iop_order_list, imgid);`
to be sure history was written before calculating hashes.
Is there some reason to make this duplicate the masks ?

**Comment by phweyland** [comment]
> @phweyland - do you want me to check whether mask manager gets crazy at that specific commit that I can't check due to missing column?

No, just to be sure we are in sane position.

>  The only piece of code that could introduce the bug is you new _dev_write_history() which add history items AND masks too.

Ok, let's me have a look

**Comment by TurboGit** [comment]
The only call to dt_dev_write_history_item() was in develop.c before your commit and before this call we have:
```
  DT_DEBUG_SQLITE3_PREPARE_V2(dt_database_get(darktable.db), "DELETE FROM main.history WHERE imgid = ?1", -1,
                              &stmt, NULL);
  DT_DEBUG_SQLITE3_BIND_INT(stmt, 1, imgid);
  sqlite3_step(stmt);
  sqlite3_finalize(stmt);

  DT_DEBUG_SQLITE3_PREPARE_V2(dt_database_get(darktable.db), "DELETE FROM main.masks_history WHERE imgid = ?1", -1,
                              &stmt, NULL);
  DT_DEBUG_SQLITE3_BIND_INT(stmt, 1, imgid);
  sqlite3_step(stmt);
  sqlite3_finalize(stmt);
```

**Comment by TurboGit** [comment]
That is, removing current history AND mask. So I suggest the removal above is put in a separate routine which can be called from your new routine just before writing history items.

This may work I think.

**Comment by johnny-bit** [comment]
I checked commit 0651c9f and @TurboGit is right:
```
67a108319c4251f75ec19457f40c4d4aac91b44f is the first bad commit
commit 67a108319c4251f75ec19457f40c4d4aac91b44f
Author: phweyland <philippe.weyland@laposte.net>
Date:   Fri Feb 21 22:22:07 2020 -0300

    init history_hash table with altered / not altered status
    collection / history and
    dt_image_altered() connected to history_hash (same source)

 src/common/collection.c | 13 +++++++++--
 src/common/database.c   | 21 +++++++++++++++--
 src/common/exif.cc      |  2 +-
 src/common/history.c    | 55 ++++++++++++++++++++++++++++++++++++---------
 src/common/history.h    | 15 +++++++------
 src/common/image.c      | 33 +++++----------------------
 src/develop/develop.c   | 60 +++++++++++++++++++++++++++++++++++--------------
 src/libs/collect.c      | 18 ++++++++-------
 src/views/darkroom.c    |  1 -
 9 files changed, 142 insertions(+), 76 deletions(-)
```

Commit 0651c9f doesn't do crazy masks (it was missing current_hash column, that's why it failed on me)
Commit 67a1083 introduces crazy mask behaviour.

**Comment by TurboGit** [comment]
But I'm even wondering if your new _dev_write_history() is even needed.

**Comment by TurboGit** [comment]
This is called in routine reading history, I doubt we need to write back the exact thing we just read?

**Comment by phweyland** [comment]
> That is, removing current history AND mask. So I suggest the removal above is put in a separate routine which can be called from your new routine just before writing history items.

Understood. I do that now.

**Comment by TurboGit** [comment]
Please be sure to test removing `_dev_write_history()`, this may even be a better fix.

**Comment by TurboGit** [comment]
Looks like this call is needed otherwise the altered status is flagged as soon as you enter and leave darkroom.

**Comment by phweyland** [comment]
That works. Thanks and sorry for the inconvenience ! I issue the PR

**Comment by TurboGit** [comment]
Ot maybe just call dt_dev_write_history_ext() instead of your routine ?

**Comment by phweyland** [comment]
> Ot maybe just call dt_dev_write_history_ext() instead of your routine ?

Passing some more parameters I could do it, but before updating hashes we need to know which ones to be updated.
So I think it's safer to do it as you suggested first.

**Comment by johnny-bit** [comment]
I can confirm that #4395 fixes this issue.

@cimatosa - can you too confirm? there are some errors in mask manager gui, but unrelated to this particular issue.

**Comment by cimatosa** [comment]
Hey Folks, my first bug report ever on a community project. I'm very happy how quickly the problem was resolved. I can indeed confirm that #4395 fixes the problem.

I was about to take a look myself at the code, but your were way faster, Thanks.
