### ISSUE TITLE
[Latest git version] Compilation error

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#4381]
The latest git version demands `-Wno-error` to compile:
```
/media-gfx/darktable-9999/work/darktable-9999/src/views/knight.c
/var/tmp/portage/media-gfx/darktable-9999/work/darktable-9999/src/views/knight.c: In function «_event_loop»:
/var/tmp/portage/media-gfx/darktable-9999/work/darktable-9999/src/views/knight.c:951:10: error: «res», probably is used uninitialized [-Werror=maybe-uninitialized]
  951 |   return res;
      |          ^~~

```

**Comment by rabauke** [comment]
This is a false positive warning. Which compiler and which compiler version are you using?

**Comment by kanyck** [comment]
That's obviously an option)))
Using gcc-9.2.0 under Gentoo. Not so many Gentoo users out there, so the environment setup may be involved. If you think the code is okay, then ebuild probably has to be modified.

**Comment by johnny-bit** [comment]
> This is a false positive warning.

This actually isn't _false positive_. Message is `probably is used uninitialized`. Which (to compiler) is true.

The code in question has `res` undefined at beginning, then it's value is defined in `switch` with no default. My solution would be to:

* initialize res with default `FALSE`
* put `knight` module into optional compile.

I don't know (yet) how to do 2nd option so I went with first and it silences that warning.

**Comment by rabauke** [comment]
> This actually isn't _false positive_. Message is `probably is used uninitialized`. Which (to compiler) is true.

It's actually not only to the compiler true. The problem is that in C an enum may attain a value that is different from the values given in the enum definition. Here is an illustration:

    #include <stdio.h>

    typedef enum { head = 0 , tail = 1} coin;

    void test(coin c) {
        int i;
        switch(c) {
        case head:
            i = 42;
            break;
        case tail:
            i = 7;
            break;
        default:
            printf("i has not been initialized\n");
        }
    }
    
    int main() {
        coin c = (coin)(-1);
        test(c);
        return 0;
    }

The program will print _i has not been initialized_ although it is tested for all values of the enum type.

**Comment by johnny-bit** [comment]
Ah, so the switch should also have default case... and I'd still love to add conditional compilation of `knight` view...
