### ISSUE TITLE
Holding camera.

### ISSUE THREAD

**Issue by KasheyV** [darktable-org/darktable#4382]
After taking a picture with darktable Nikon (d750, d800) stuck into PC mode, did not responce on camera button and block possibility to take an image from camera. Would be nice to have a possibility to abort that PC mode and came back to camera shooting.

**Comment by johans3** [comment]
if your camera has no build in screen to preview pictures, then get another camera model. I use Canon, can't talk for your camera model.. 
Darktable switches to import mode if it detects plugged devices, and this is a normal behavior. Earlier versions of this importer didn't work reliably ( at least on Mac) , but version Dt 3 improved greatly over this. 
On the other hand, it's not a bad practice to shoot a row of pictures and import these only then for revision, instead to go micro steps. Takes exercise to get good pictures so you save time instead to check all times and lose yourself in speculations if a picture is good or bad

**Comment by dterrahe** [comment]
Is this about darktable tethering mode? There is very little information here that anyone could usefully respond to with suggestions or a fix. Please provide more information or close this issue please.

**Comment by johnny-bit** [comment]
Since the time of this report we had some improvements to tethering mode, especially for nikon cameras.

Closing this for now. If there's still an issue - please comment with more info or open a new issue :)
