### ISSUE TITLE
Single mouse click in Film roll - to switch pictures

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#4386]
**Is your feature request related to a problem? Please describe.**

I assume, Photographers work with volumes of pictures to edit and check, after awhile you get tired to double-click on the filmroll, just for a simple switch to another picture. 
Clicking in the filmroll is not destroying anything to justify a double click, so i do wonder why a double click is set as default behavior.

**Describe the solution you'd like**

I request a preference to change the double-mouse click to a single mouse click, to switch to another picture in the film roll

**Alternatives**

Meanwhile, I assigned the shortcut numpad keys 1 (back) and 2 (next) to switch through pictures but would like to have also the opportunity to switch with my mouse using a single-click only. We use the mouse often whatever we do on our computer, it is pretty intuitive to use mouse aside shortcuts.

**Comment by TurboGit** [comment]
This is how the rewrite of lighttable works. See #4370
