### ISSUE TITLE
Heal tool / clone tool - source spot is projected outside the canvas

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#4388]
**Describe the bug**

Darktable version 3.0.0 introduced a bug with the heal/clone tool. The source to copy is projected outside the canvas, far away from the origin to patch and that bug pops up all times, at least to me.

**To Reproduce**

1. Pick the healing brush and the path tool
2. draw a line
3. press right click to see your path
4. very often, the source is being projected outside of the canvas. Please see video under "Screenshots" below.

**Expected behavior**

Better if the source to patch our original spot is not that far away from its origin, as usually.

**Screenshots**

https://www.youtube.com/watch?v=bWCLRYiNPn8
please watch from minute 19:45 on.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: MacOs 10.14.6
 - OpenCL: no
 - AMD Radeon HD 7970 3 GB

**Comment by johans3** [comment]
I noticed this bug appears if you add many retouch /heal shapes in the black layer, shape doesn't matter. Many means more than a dozen but the bug appears also earlier.

**Comment by elstoc** [comment]
IMO the better workflow is to set your source before you start drawing or placing the shape. Shift-Click sets the source patch (for a freeformat shape this is the source of the start of the path, for circle/ellipse it's the centre). 

AFAIK darktable just remembers the relative position of the source with respect to the target from the last time you set source and doesn't try to do anything more intelligent than that.

**Comment by johans3** [comment]
> IMO the better workflow is to set your source before you start drawing or placing the shape. Shift-Click sets the source patch (for a freeformat shape this is the source of the start of the path, for circle/ellipse it's the centre).
> 
> AFAIK darktable just remembers the relative position of the source with respect to the target from the last time you set source and doesn't try to do anything more intelligent than that.

Usually the cross to sample the source is placed immediately outside the shape of the retouch tool. 
But what do you do if the sample cross appears outside the canvas by default?

**Comment by elstoc** [comment]
I'm suggesting you _place the cross yourself_ by holding down shift and clicking the mouse where you want the source cross to be. Then you click on your destination. You don't need to let darktable do this for you.

If you want to move/alter anything that's outside the image, you can use ctrl-scroll to zoom out - this will allow you to see the borders around the image and any shape points that have found there way outside of the image.

**Comment by johans3** [comment]
> I'm suggesting you _place the cross yourself_ by holding down shift and clicking the mouse where you want the source cross to be. Then you click on your destination. You don't need to let darktable do this for you.

Usually I don't even see the source cross. So how can I move the cross to sample a spot when I've no idea where the sample cross is? After drawing a shape I'm able to see where and how outside the canvas the sample is

> If you want to move/alter anything that's outside the image, you can use ctrl-scroll to zoom out - this will allow you to see the borders around the image and any shape points that have found there way outside of the image.

Yep, I need to zoom out that way all times too me out where the sample cross is

**Comment by elstoc** [comment]
I think you're missing the point. You need to set the source position yourself _before you place the destination shape_ onto the image. You appear to be placing your shape and then going hunting for the source cross. 

So the workflow should be

1. Open the retouch module
2. Choose which shape you want to use
3. _First_ place your mouse cursor where you want the source to be and _shift-click to set the source position_
4. _Then_ move your mouse to where you want the target to be and _click to place or start drawing your shape_

**Comment by elstoc** [comment]
For subsequent shapes darktable remembers where you last placed your source relative to your destination so if you're happy that the relative positions don't need to change you don't need to repeat step 3 but this is entirely up to you (darktable won't try to be clever and work out what you want to do). IMO darktable is working correctly and this is all as designed.

**Comment by johans3** [comment]
@elstoc 
I follow you and agree with you, shift - click is working and helps me to get back to work instead to write bug reports. 
:) 

Still, the bug causing displaced source position exists and won't disappear this way. I've posted a link where you can see this bug, which appears only after some time of retouch-editing.

**Comment by elstoc** [comment]
I see that now. I see that Bruce is changing scales when placing shapes so that might have some impact. Retouch does some odd hacking around with masks that I haven't got my head around yet. For now I suppose the workaround is to always do step 3 in my posted workflow.
