### ISSUE TITLE
[Windows Build Failure] Current Windows' Build fails

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4391]
**The last one I built successfully was darktable-3.1.0+719~g273ee42db-win64**

The current that fails has a  Version string: 3.1.0+760~g8c9952098

[build_error.txt](https://github.com/darktable-org/darktable/files/4265268/build_error.txt)

[ 14%] Building C object src/CMakeFiles/lib_darktable.dir/common/camera_control.c.obj
F:/msys64/home/chill/darktable/src/common/camera_control.c: In function '_camctl_recursive_get_previews':
F:/msys64/home/chill/darktable/src/common/camera_control.c:1032:21: error: passing argument 7 of 'gp_camera_file_read' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1032 |                     &chunksize, c->gpcontext) == GP_OK)
      |                     ^~~~~~~~~~
      |                     |
      |                     long unsigned int *
In file included from F:/msys64/mingw64/include/gphoto2/gphoto2-library.h:29,
                 from F:/msys64/mingw64/include/gphoto2/gphoto2.h:51,
                 from F:/msys64/home/chill/darktable/src/common/camera_control.h:30,
                 from F:/msys64/home/chill/darktable/src/common/camera_control.c:22:
F:/msys64/mingw64/include/gphoto2/gphoto2-camera.h:451:48: note: expected 'uint64_t *' {aka 'long long unsigned int *'} but argument is of type 'long unsigned int *'
  451 |          uint64_t offset, char *buf, uint64_t *size,
      |                                      ~~~~~~~~~~^~~~
F:/msys64/home/chill/darktable/src/common/camera_control.c:1048:21: error: passing argument 7 of 'gp_camera_file_read' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1048 |                     &chunksize, c->gpcontext) == GP_OK)
      |                     ^~~~~~~~~~
      |                     |
      |                     long unsigned int *
In file included from F:/msys64/mingw64/include/gphoto2/gphoto2-library.h:29,
                 from F:/msys64/mingw64/include/gphoto2/gphoto2.h:51,
                 from F:/msys64/home/chill/darktable/src/common/camera_control.h:30,
                 from F:/msys64/home/chill/darktable/src/common/camera_control.c:22:
F:/msys64/mingw64/include/gphoto2/gphoto2-camera.h:451:48: note: expected 'uint64_t *' {aka 'long long unsigned int *'} but argument is of type 'long unsigned int *'
  451 |          uint64_t offset, char *buf, uint64_t *size,
      |                                      ~~~~~~~~~~^~~~
F:/msys64/home/chill/darktable/src/common/camera_control.c:1092:19: error: passing argument 7 of 'gp_camera_file_read' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1092 |                   &chunksize, c->gpcontext) == GP_OK)
      |                   ^~~~~~~~~~
      |                   |
      |                   long unsigned int *
In file included from F:/msys64/mingw64/include/gphoto2/gphoto2-library.h:29,
                 from F:/msys64/mingw64/include/gphoto2/gphoto2.h:51,
                 from F:/msys64/home/chill/darktable/src/common/camera_control.h:30,
                 from F:/msys64/home/chill/darktable/src/common/camera_control.c:22:
F:/msys64/mingw64/include/gphoto2/gphoto2-camera.h:451:48: note: expected 'uint64_t *' {aka 'long long unsigned int *'} but argument is of type 'long unsigned int *'
  451 |          uint64_t offset, char *buf, uint64_t *size,
      |                                      ~~~~~~~~~~^~~~
cc1.exe: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:1681: src/CMakeFiles/lib_darktable.dir/common/camera_control.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1286: src/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by chhil** [comment]
I am attempting a clean build now (previously I just updated the code and did  builds). Will close issue if build succeeds.

**Comment by chhil** [comment]
A clean build didn't fix it either.

@jenshannoschwalm

**Comment by jenshannoschwalm** [comment]
Hi, thanks for reporting; could you check by changing all `long unsigned int chunksize` to `size_t chunksize` in file src/common/camera_control.c and function _camctl_recursive_get_previews please?
(Lines 1027, 1043, 1087)

**Comment by phrrk** [comment]
Hi,
I can confirm that those edits overcome the build issue with camera_control.c on Windows.

**Comment by chhil** [comment]
Thank you. It builds fine now.

**Comment by parafin** [comment]
fix isn't correct, see #4402

**Comment by jenshannoschwalm** [comment]
My stupidity! Should be fixed now via #4406

**Comment by parafin** [comment]
@Mstraeten, can you test?

**Comment by phrrk** [comment]
ok with windows

**Comment by MStraeten** [comment]
Ok for osx

**Comment by jenshannoschwalm** [comment]
@chhil Why not closing this issue?

**Comment by chhil** [comment]
@jenshannoschwalm had closed it 5 days ago and it was somehow reopened :)

![image](https://user-images.githubusercontent.com/1119439/75988671-f22ad000-5f17-11ea-85c0-962c1927264d.png)
