### ISSUE TITLE
copy history does not copy the module order

### ISSUE THREAD

**Issue by cimatosa** [darktable-org/darktable#4398]
When copying the history of an image with non-default module ordering (pressing ctrl+shift and dragging modules around) to another image the module order is not copied. Instead the default order is used. I believe this should not be the case.
In addition, even when the module order is default, after collapsing the history stack (on the left side of the darktable) if still has different ordering, although the images looks the same. That seems inconsistent to me.

To Reproduce:
1) open an fresh image
2) make a duplicate
3) do some editing including module reordering
4) copy and paste the edits to the duplicate
5) the module order is not the same

 - Darktable Version: github master (8887c1b)
 - OS: Debian Linus
 - no OpenCL

**Comment by TurboGit** [comment]
How do you copy ? Is that a copy all ? If so that's expected. The "module order" can be copied only doing a partial copy and selecting explicitly the "module order" which is the first entry in the list.

**Comment by cimatosa** [comment]
i use ctrl+c to copy and ctrl+v to paste. I would expect, and also like for a convenient workflow, that the module order will be applied to the target image as well.

**Comment by cimatosa** [comment]
it sees to make a difference whether ctrl+c is used in the lighttable or the darktable.

Using ctrl+c in the light table and then paste in the lighttable I can toggle the module order, that's right. However, using the film roll in the darktable behaves different. Since I don't get the selection choice, which is fine, I would assume that everything is copied, so also the module order.

**Comment by Nilvus** [comment]
> i use ctrl+c to copy and ctrl+v to paste. I would expect, and also like for a convenient workflow, that the module order will be applied to the target image as well.

To choose quickly modules to apply, just add shift key to these shortcuts.
