### ISSUE TITLE
Issue with gradient in a drawn mask [Olympus ORF and FUJI ARW]

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4401]
**Describe the bug**
I try to place a drawn mask as a gradient and after placing it, I want to rotate it a bit.

Once I release the left mouse button (and I do hold the mouse steady), the gradient **jump-rotates clockwise for approx 5°** or so. Is very hard to place 

I see this happen on Olympus' ORF files (in my case EM-5 II but also on [this one](https://discuss.pixls.us/t/playraw-mairi-further/3515) ) and Fuji (X-30). Nikon's NEF seems to be w/o this problem. 

**To Reproduce**
1. Open a ORF RAW file, like [the one in this thread](https://discuss.pixls.us/t/playraw-mairi-further/3515)
2. Make sure, you have history stack compressed
3. Add some modules (lens correction, haze removal, filmic)
4. Add e.g. exposure, drawn mask gradient fill, roate it a bit and realease the mouse button
5. Observe the position of the gradient

**Expected behavior**
As it was before, after releasing the mouse button, the gradient shall just stay where it is at that moment (yes I tried to drag the mouse cursor more far, in order to get less sensitive, to no avail)

**Platform (please complete the following information):**
 - Darktable Version: **3.1.0+769~g1ef4476cf** started for me around +748 or so
 - OS: [**Gentoo** Linux]
 - OpenCL activated **yes and no**, both effected
 - 2x nvidia **GTX 160OC** with nividia-drivers-**440.59**

**Additional context**
 - Can you reproduce with another Darktable version --> **3.0.0 is clean**
 - Can you reproduce with a RAW or Jpeg or both? --> **RAW only**
 - Are the steps above reproduce with a fresh edit (removing history)? --> **particularly fresh edits**. Older edits, where just an gradient getting added, may "survive", means behave well.
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
--> **gcc-9.2.0** CFLAGS="-march=native -O3 -mtune=native -pipe"
 - Is the issue still present using an empty/new config-dir  --> **Yes**

**Comment by jade-nl** [comment]
I can confirm this behaviour.

Using the modules and RAW's mentioned I see this "jumping" gradient. It also happens with Fujifilm, Pentax, Panasonic and Sony. I do not see this behaviour with Canon or Nikon camera's.

You don't even have to turn the gradient. The moment you let go after placing it it jumps to a different angle, which is only seen with the aforementioned RAW's.

**HOWEVER**

Tried with different modules than mentioned above. Turned on in this order:
   - chromatic aberrations,
   - denoise profiled,
   - defringe,
   - monochrome module to test the gradient.

With this combo **none** of the camera's I tested with show this behaviour....

I do know it is not filmic rgb specific: If I remove that module from OP's set I **do get** the same behaviour: A jumping gradient.

Tested with the following camera's/types:
* Canon EOS 7D mark II
* Fujifilm Finepix hs20exr
* Nikon D750
* Pentax K-5 IIs
* Panasonic DC-LX100M2
* Sony ILCE 7RM4

Platform information:
* darktable version: Development 3.1.0+769
* OS     : Linux - kernel 4.19.0-8-amd64
* Distro : Debian Buster (rel. 10.3)
* Processor : Intel(R) Core(TM) i7 CPU 950  @ 3.07GHz 4 Core(s)
* Memory : 12 GB (6 x 2048 MB) + 12 GB Swap
* Graphics card   : NVIDIA GF104 [GeForce GTX 460] (rev a1)
* Graphics driver : NVIDIA x86_64 Kernel Module 390.116
* OpenCL activated : No
* Xorg : 7.7+19
* GTK+ : 3.24.5-1

**Comment by AxelG-DE** [comment]
I confirm the **"HOWEVER"** part
The same picture, I cleared the history stack again and then:
- lense correction (auto apply)
- very low strengths denoiseprofiled (auto apply)
- crop and rotate (auto apply to 3:2)
- WB
- shadows and highlights
- contrast equalizer 
- vibrance
- levels
- another denoise for the brightened sky with gradient **and here we go, it jumps again**

**Comment by elstoc** [comment]
Same here but as soon as I switch off lens correction all is well.

**Comment by jade-nl** [comment]
I just redid my own set of modules which did not show this behaviour and added the lens correction module: Problem shows up.

I also tested @AxelG-DE's set without the lens correction: Problem disappears.

Seems to be that the lens correction module is the problem.

**Comment by AxelG-DE** [comment]
I confirm the lens correction impact. I thought, I tried with empty history stack, but maybe got trapped by auto-apply (which is really necessary for MFT as they have severely stronger "natural" distortions...

**Comment by elstoc** [comment]
The gradient mask has changed for 3.1 - to add the ability to curve it - so that might be what introduced the issue.

**Comment by AxelG-DE** [comment]
interferences, yes.....

**Comment by elstoc** [comment]
See https://discuss.pixls.us/t/darktable-3-0-masking-inconsistencies-bugs/16217/25. Issue also experienced with crop and rotate module when used with keystone correction.

**Comment by jade-nl** [comment]
Based on a _do-I-see-a-trend_ hunch I tested this with the *perspective correction* and the *liquify* modules and these also shows this behaviour.

So at the moment these three modules introduce this behaviour:
* lens correction
* perspective correction
* crop and rotate
* liquify
I'm not a developer and might lack the technical terms but all of these modules move/rearrange the subject pixels from one point in the "pixel-matrix" to another and fill/remove empty/already occupied spots.

**Comment by ohms-law** [comment]
Just like to add, that I encountered that problem on dt stable 3.0.1 from the OBS repo under Ubuntu 18.04.4 on a RW2 file (Pana LX100II). lensfun is updated via lensfun-update-data
Lens correction warps the gradient on an exposure module and makes fine adjustments very difficult to almost impossible.

**Comment by elstoc** [comment]
Looking at the code I see there's a note in masks.c: `TODO: new ones have wrong rotation`.

**Comment by elstoc** [comment]
In terms of lens correction 'warping' the gradient the same happens if you try to draw a path: a straight line doesn't come out straight because it's warped by the lens correction module, so if you use lens correction (and any other modules that warp the image) it's not possible to draw a mask with a straight line (or at least with a consistent line).

The act of placing a new gradient path seems to result in a much larger angle change than the act of adjusting the rotation of an existing gradient path because they use different methods to obtain the rotation angle.

The gradient path code tries to use a comparison of two straight line vectors before and after distortion via intervening modules to adjust the module rotation (gradient.c line 285, 364, 369). But while this method can handle a plain rotation, it can't manage to deal with modules that distort the image (the assumption that the vectors connecting the points are straight breaks down). The effect is very noticable if you do a keystone correction in the crop/rotate module.

**Comment by AxelG-DE** [comment]
@elstoc Thank you very much!

**Comment by elstoc** [comment]
No problem
