### ISSUE TITLE
thumbnailing while import only for visible images

### ISSUE THREAD

**Issue by tlo8640** [darktable-org/darktable#4403]
**Describe the bug**
trying to import photos from a network drive. import runs fine. and photos are visible in darktable.
after import darktable will be cosed and network drive is unmounted.
after starting darktable agail, thumbnails of imported photos are only created of photos, wich were visible in lighttable. other images don't have thumbnails , only the *skull* is visible.

**To Reproduce**
1. import photos (more than normally visible on lighttable) from network drive
2. Close darktable, umount network drive
3. start darktable again, try to view all imported images
4. See no thumbnails

**Expected behavior**
I exptected, that (after an import) all imported images have an thumbnail, so that I can browse all (ever imported images) without mounted network drive, where the original images are located.

Did I understand something wrong with thumbnail Creating?
Are "special" Settings in Preferences needed?
My expactation was, that I can use the thumbnail for working "offline", sorting and searching an such things without connected network drive, where the originals alr located.
A possibility to do at least browsing through "Previews" is really important (for me= and should be possible for all ever imported images.
Any hints howto get this working are very welcome

**Platform (please complete the following information):**
 - Darktable Version: 3
 - OS: Macos Catalina (10.15.3)
 - OpenGL is activated
 - onboard Intel iris pro or AMD Radeon, depends on power supply

**Comment by ptilopteri** [comment]
You actually expect dt to exhibit thumbnails for images which dt cannot access, nor can you edit them?

**Comment by Nilvus** [comment]
> Any hints howto get this working are very welcome

Connect your network drive...

**Comment by parafin** [comment]
This is not a bug. Use /Applications/darktable.app/Contents/MacOS/darktable-generate-cache or "local copies" feature.

**Comment by tlo8640** [comment]
Hello,
impressive, very fast replys.
Thank you anybody

@ptilopteri 
I expected to have (during the import created) thumbnails for viewing images, imported in dt, in the case, originals are not available (disconnected network drives, you are "on the road" and your originals are on your nas @home)

@Nilvus 
a kind of funny, but there are situations, where it isn't possible and you want to show someone som eimages in your library or you are looking for an image in your library....

@parafin 
Thank you. I know this tool and already used it. But I thought, there is a possibility, which I haven't found, to do this during image import.
