### ISSUE TITLE
Applying a color label (or something else) on few images make darktable stuck

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4409]
**Describe the bug**
As the title said. I test that and can reproduce with color labels but that could happen when you apply anything in lighttable on multiple images

**To Reproduce**
1. Go to 'lighttable'
2. Select multiples images
3. Apply a color label on them (I do it with shortcut)
4. darktable stucks and I have to force quit. I think is not really totally stuck but it taking quite a long time to apply these. It was instantaneous just few days ago, so probably a recent commit. Maybe #4271 PR (@TurboGit) ?

I have tested on both actual master and on #4370 PR from @AlicVB and I have the same issue. 

**Expected behavior**
Have those simple things applied instantly like before to avoid any freeze.

**Comment by TurboGit** [comment]
I cannot reproduce !

Tested first with 5 images selected, then with 38. Using F2 or 3 or whatever to add stars and/or color labels, all went fine.

I have even tested adding three color labels F2, F3, F4 and doing then three undo ctrl-z... Again all fine, no stuck dt !

Thinking.... Is your image local or on a removed drive ?

**Comment by AlicVB** [comment]
I can't reproduce too. Does -d all block on something special ?

**Comment by TurboGit** [comment]
Just tested with off-line pictures and I still don't reproduce the freeze... Very strange !

**Comment by Nilvus** [comment]
Thanks for both you to test that. All my images are local (SSD drive) and it only happens when I apply that for more than 5 images (as I remember, the lowest should be 7 images at least).

When I wait some times (time depending on images selected) without force quit, darktable come back. But it's quite long even with few images. If you can't reproduce, maybe it's related to something else I change recently (maybe the kernel update). Will try ASAP with previous kernel.

@AlicVB: I don't test with -d actually. Will see, if another kernel use doesn't change this.

**Comment by Nilvus** [comment]
@AlicVB and @TurboGit: thanks again for your tests and replies. I have tested (by now with the same kernel) and darktable doesn't stuck anymore. The only thing I do since yesterday, after 2 long days of processing many photos (about 600 images), was to removing all cache images then regenerating them, and shutdown my computer for the night. It's now ok.

So the problem seems to be more a cache problem than anything else. By now, I close this issue.
