### ISSUE TITLE
Erroneous Haar wavelet coefficients in noise profile estimation

### ISSUE THREAD

**Issue by rsebbe** [darktable-org/darktable#4411]
While evaluating some of our noise measurement process here, I wanted to compare with DT's output, and I noticed a difference. After reviewing the code, it looks like there are erroneous coefficients in the Haar wavelet transform here:

https://github.com/darktable-org/darktable/blob/4b5bbba6c79407f2eda3eba5effeb86693fa6376/tools/noise/noiseprofile.c#L238

https://github.com/darktable-org/darktable/blob/4b5bbba6c79407f2eda3eba5effeb86693fa6376/tools/noise/noiseprofile.c#L252

For Haar transform to preserve variance, it needs to be orthonormal which is why I believe they should be `sqrt(0.5)` instead of `0.5` (as originally defined), both horizontal & vertical passes. DT's computed noise standard deviation is twice smaller than the one I get here. Also, this could affect submitted camera noise profiles (unless this is compensated elsewhere).

**Comment by aurelienpierre** [comment]
ping @rawfiner and @hanatos

**Comment by rawfiner** [comment]
Issue related to #2313
