### ISSUE TITLE
Version 3.0.0,  lighttable 'max size' image export off by 1 pixel

### ISSUE THREAD

**Issue by DaveBlack** [darktable-org/darktable#4412]
**Describe the bug**
lighttable 'max size' image export off by 1 pixel

**To Reproduce**
1. Open a high resolution image
2. Using lighttable 'max size' field (either), enter a setting such as 1000 
3. Click 'export' button
4. Exported image is 999 pixels

**Expected behavior**
Following above steps, exported image should be 1000 pixels

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0 (flatpack)
 - OS: Linux Mint 19.3 Cinnamon

**Additional context**
 - Darktable Version: 2.6.x 'max size' works as expected
 - Jpeg tested
 - Fresh image import, no previous image history
 - Flatpak version used
 - Issue is still present using an empty/new config-dir

**Padding**
Also (maybe OS related), adding extra padding between text, entry fields, and buttons may help improve readability? Can be opened as separate issue if preferred.

Before
![1 padding before](https://user-images.githubusercontent.com/13056699/75723726-c075f700-5cd4-11ea-8f3f-5e9a2140ed89.png)

After (GIMP mock-up)
![2 padding after (GIMP mock-up)](https://user-images.githubusercontent.com/13056699/75723795-e4d1d380-5cd4-11ea-9d5b-3c5527539bc7.png)

In closing...
Thank you developers for your time, and all your hard work.

**Comment by jade-nl** [comment]
Duplicate of this, closed, issue: [#3757](https://github.com/darktable-org/darktable/issues/3757)

**Comment by johnny-bit** [comment]
Which is fixed in 3.0.x and 3.1.0 branches :) so - plz wait for 3.0.1 release which fixes your problem. (except padding in module UI)

**Comment by Nilvus** [comment]
@DaveBlack: as your main issue is a duplicate one and already fixed one (think about searching before posting to help developer community), think about closing this one and create a new one with the padding issue. I indeed never take care of that. When you create this specific padding, think of ping me with my nickname. I will see that.

**Comment by Nilvus** [comment]
@DaveBlack: forget last reply. It was simple and quick to fix it so it's done ! See PR mentioned above. Should be in next 3.0.1.

**Comment by DaveBlack** [comment]
Thanks all for your replies, and Nilvus for implementing a padding fix.
BTW, carefully read bug report header info. first, performing a preliminary search for `lighttable max size`, and just `max size` didn't return helpful results.
