### ISSUE TITLE
DT has created few huge xmp files causing DT to stall

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#4418]
During the "normal" opetation DT has created few huge xmp files and correspondingly huge db entries that cause DT to stall.

**To Reproduce**
Can't reall tell, sorry. The usage seemed to be as usual. But at some moment DT begins to hang up on some pics. Investigation show enormous size of the xmp files.
So far I found two of them:
https://github.com/kanyck/files/blob/master/20200301_0003.NEF.xmp
https://github.com/kanyck/files/blob/master/20200227_0032.NEF.xmp

**Platform (please complete the following information):**
 - Darktable Version: happened on 3.1.0+556~ga2070508b-dirty
 - OS: Gentoo Linux
 - OpenCL on

**Comment by phweyland** [comment]
I've a look at your first xmp. It is full of mask records.
The history_hash [commit ](https://github.com/darktable-org/darktable/commit/73ebc255f9b00be83ee0186180b3ea8f5c585553) has introduced an issue duplicating endlessly the image masks (visible in mask module). 
This has been fixed with "fix double mask issue" [commit](https://github.com/darktable-org/darktable/commit/8887c1b055108e5d6e644d3843a84a2f19ca4513)

Please check if this could solve your current issue.

**Comment by johnny-bit** [comment]
You have dirty tree with over 200 commits ago. Current master is (I think) `3.1.0+784~gaf6852e14`
Try with current master, please.

**Comment by kanyck** [comment]
>This has been fixed... Please check
Yeah, I purged it manually to be able to continue. Will check how the latest git version behaves. Hopefully it's fixed. 

@johnny-bit  Have updated this morning. It's probably reasonable to have intermediate "stabilization releases" or some "cleaner" tree snapshots to avoid reports like this. Otherwise the choice is quite narrow: latest release (3.0.0) or a dirty tree. Maybe it's reasonable to keep two parallel trees "development" and "stabilization" like linux kernel devs do.

**Comment by johnny-bit** [comment]
Depends on what you want. [3.0.x tree](https://github.com/darktable-org/darktable/tree/darktable-3.0.x) is rather stable. Master is more of a development work ;)

**Comment by kanyck** [comment]
@johnny-bit 
Looked into the ebuild. It actually pulls the sources from 
`https://github.com/darktable-org/${PN}.git`
where ${PN}=darktable. AFAIU it's master. Probably @parafin may want to add ebuild for darktable-3.0.9999 or something like it to make pre-release branch available for installation via standard Gentoo tools. Thanks!
