### ISSUE TITLE
history copy effect when applied on a different camera model image

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#4419]
**Describe the bug**
In darkroom, copying (ctrl-c/ctrl-v on filmstrip) dev from a D750 raw over a D200 one screws the raw black/white point module (output).
No problem however when I copy over a raw from the same model.

**Expected behavior**
I would say the modules which are machine specific should not be copied.
If not possible a warning message ?

**Screenshots**

first image D200->D750, third one D750->D200.
![image](https://user-images.githubusercontent.com/23012047/75891981-59109200-5e0f-11ea-86ac-4478dc545a78.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+745~gc044acf54
 - OS: debian 10
 - Open cl activated or not

Please let me know if more information is needed.

**Comment by TurboGit** [comment]
Yes, you need to copy only part of the modules when copy/paste from different images as otherwise you are include into the copy some modules (raw point, whitebalance... ) that are only valid for images from the same camera.

**Comment by phweyland** [comment]
> you need to copy only part of the modules when copy/paste from different images

OK. This is possible in lighttable. In darkroom is there a mean to do that ?

**Comment by TurboGit** [comment]
Yes, using the filmstrip. I do that all the time.

**Comment by phweyland** [comment]
> using the filmstrip. I do that all the time.

Me too.
I've missed something. Ctrl-C Ctrl-V copies everything and doesn't give the option to select the modules ..

**Comment by TurboGit** [comment]
Yes Philippe you've been missing an important feature :)

Do check ctrl-shift-c and/or ctrl-shift-v :)

**Comment by phweyland** [comment]
I may miss another important feature Pascal.
if I select one module with ctrl-shift-c, and copy it on another image (ctrl-v or ctrl-shift-v), I'm loosing all but mandatory modules of the destination image. I would like to be able to add the copied module to the destination image...
