### ISSUE TITLE
3d lut cube files fail to apply with error - cube lut lines number is not correct

### ISSUE THREAD

**Issue by mproffitt** [darktable-org/darktable#4420]
I have been seeing this error using lut files provided with (or generated by) Davinci Resolve whereby the LUT file will not apply.

The issue appears to be due to the use of integers or doubles within the LUT .cube file where the lut code within darktable is expecting floating point?

Converting the integers/doubles to floats in the .cube files allows darktable to recognise and apply the look correctly.

This can be validated with the LUTs available from https://smallhd.com/blogs/community/movie-looks-download which use the integer `1` instead of `1.000000`, or any of the luts provided with Davinci Resolve 16 (free version) which uses 10 decimal places per entry instead of 6.

Darktable version:
```
$ darktable --version
this is darktable 3.0.0
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
```

**Comment by phweyland** [comment]
Could you please provide some luts with 10 decimals ?

**Comment by phweyland** [comment]
I cannot reproduce the issue with 1 instead of 1.00000. 
The luts from the site you provide work well for me (some of them have some 1). The corresponding code has not changed since 3.0.0 I believe...

**Comment by mproffitt** [comment]
So this is one of the luts which come with the free version of DR16
[Blackmagic 4.6K Film to Rec709 v3.cube.txt](https://github.com/darktable-org/darktable/files/4288467/Blackmagic.4.6K.Film.to.Rec709.v3.cube.txt)

So with regards to the 1 vs 1.000000: This might have been a red-herring as after re-downloading them myself and applying, those files work fine

**Comment by phweyland** [comment]
> So this is one of the luts which come with the free version of DR16
> [Blackmagic 4.6K Film to Rec709 v3.cube.txt](https://github.com/darktable-org/darktable/files/4288467/Blackmagic.4.6K.Film.to.Rec709.v3.cube.txt)

OK, this one is problematic. I'll look at it.

**Comment by phweyland** [comment]
LUT_3D_INPUT_RANGE 0.0000000000 1.0000000000

is not in cube specification v1.0. I don't know if there is a newer one. However I can skip non standard text. I'll prepare a PR for that.

**Comment by TurboGit** [comment]
Fixed.
