### ISSUE TITLE
Sidecar (.xmp file) corrupted after cropping module issue

### ISSUE THREAD

**Issue by TouchPadDancer** [darktable-org/darktable#4425]
I was editing a Sony RAW (ARW) file with the crop module. Image displayed became very dim - as if the entire image was outside the crop markers, but there were no handles visible to re-size the crop boundaries.

In Lightable view the image was displayed as a gradient (not the image thumbnail).

Opened an closed DT a few times, got the error every time this file was selected.

Cleared error by renaming original .ARW file and .ARW.xmp file and re-importing .ARW file.

Backtrace and 'broken' .xmp files attached.

[DSC02476.ARW.xmp-junked.zip](https://github.com/darktable-org/darktable/files/4295320/DSC02476.ARW.xmp-junked.zip)
. 

[darktable_bt_M6XGH0.txt](https://github.com/darktable-org/darktable/files/4295217/darktable_bt_M6XGH0.txt)

**Comment by LebedevRI** [comment]
FWIW the observed image is consistent with incorrect crop being specified in the `rawprepare` module - there's almost always some garbage pixel columns on the rightmost sensor side

**Comment by TurboGit** [comment]
Missing version information.

**Comment by TouchPadDancer** [comment]
Windows 10 Pro - build 1809. DT is 3.0.0. Any other version information you need?
