### ISSUE TITLE
changes don't show in lighttable view

### ISSUE THREAD

**Issue by whatstefansees** [darktable-org/darktable#4429]
I run 3.1.0~git781.1cc2c5176 under ubuntu Budgie 18.04

Since the last update ighttable doesn't show the actual changes anymore. Every image in lighttable looks like untreated (embedded JPG). You only see the work done to the photo when you go into darkroom mode.

**Comment by phweyland** [comment]
As you use ubuntu 18.04 you  have an old sqlite version.
In that case, if you launch dt from console, you should get sqlite errors.
Also, you should not have the altered symbol over thumbnails.
That could have an effect on the detection of changes as well.

If that's the case the PR #4428 should solve this.

**Comment by phweyland** [comment]
@TurboGit 
This incident makes me think again about a mipmap hash. Currently the only detection it has is between not altered (can use embedded jpeg) or altered. In this second case the thumbnail is always calculated (new change or not). Should be recalculated only if there is a new change. Here we could make the detection more accurate using a thumbnail_hash and compare it to current_hash.

**Comment by whatstefansees** [comment]
> As you use ubuntu 18.04 you have an old sqlite version.
> In that case, if you launch dt from console, you should get sqlite errors.
> Also, you should not have the altered symbol over thumbnails.
> That could have an effect on the detection of changes as well.
> 
> If that's the case the PR #4428 should solve this.

Do you suggest that the majority of dt users should upgrade their sqlite version?

**Comment by phweyland** [comment]
> Do you suggest that the majority of dt users should upgrade their sqlite version?

I don't think that I have said that ...

**Comment by whatstefansees** [comment]
>  if you launch dt from console, you should get sqlite errors.

OK, I id as you suggested, opened a terminal, launched darktable and it started flawlessly - with the bug described here above. no error message, no message of any type in the terminal, not even after closing dt.

It's not like I can't use dt anymore - but it's not as good as before ;o)

**Comment by phweyland** [comment]
> > if you launch dt from console, you should get sqlite errors.
> 
> OK, I id as you suggested, opened a terminal, launched darktable and it started flawlessly - with the bug described here above. no error message, no message of any type in the terminal,

Even going back and forth between lighttable and darkroom?

**Comment by TurboGit** [comment]
> Do you suggest that the majority of dt users should upgrade their sqlite version?

That's probably a good advice, using a 2 years old version isn't a good solution. At some point maintaining compatibility with old libraries cost us a lot.

**Comment by TurboGit** [comment]
> @TurboGit
> This incident makes me think again about a mipmap hash. Currently the only detection it has is between not altered (can use embedded jpeg) or altered. In this second case the thumbnail is always calculated (new change or not). Should be recalculated only if there is a new change. Here we could make the detection more accurate using a thumbnail_hash and compare it to current_hash.

Agreed !

**Comment by whatstefansees** [comment]
Even going back and forth between lighttable and darkroom?

yes - no changes

**Comment by whatstefansees** [comment]
sqlite is not installed on my PC

```
stefan@homeboy:~$ man sqlite
Kein Handbucheintrag für sqlite vorhanden
stefan@homeboy:~$ sqlite

Der Befehl 'sqlite' wurde nicht gefunden, kann aber installiert werden mit:

sudo apt install sqlite

stefan@homeboy:~$ 
```

**Comment by phweyland** [comment]
> sqlite is not installed on my PC

Thanks for looking at it.

On [pixls.us](https://discuss.pixls.us/t/how-are-you-installing-darktable-on-linux/16880/47?u=phweyland) you have said that dt 3.0.1 was ok, right ? 
Somehow the issue should have been solved.

**Comment by whatstefansees** [comment]
Yes, I circumnavigated the problem by installing a different version of darktable. The stable branch does NOT have the issue.

nightly 3.10-781 and 811 both show the embedded jpg and not a thumbnail of the picture as treated/changed

**Comment by johnny-bit** [comment]
The issues for not showing changes were ironed out and I haven't beeen able to replicate (although i do have rather recent sqlite3 version). Closing now. Please comment if you still have issue on most recent release/current master.
