### ISSUE TITLE
multi instances of modules handling in styles changed

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#4433]
**Describe the bug**
in earlier versions (i need to check several former build to find when exactly it changed) applying a style with a module having an instance name resulted in a new instance of the module if there was an instance of the module already in the history stack.
So it was easy to define styles eg.  appling either sharpening, clarity, skinsmoothening or whatever with contrast equalizer with an instance name. When some of them were applied, several instances with the appropiate instance names were created. 
Now the later overwrites the former.  

**To Reproduce**
1. activate contrast equalizer, drag up the right side of the curve
2. set instance name "right"
3. create a style from history just selecting the contrast equalizer 
4. reset contrast equalizer, drag up the left side of the curve
5. rename instance to "left"
6. create a new style as in step 3
7. apply style from step 3 
--> the instance name changes, the right side of the curve is dragged up
8. apply style from step 6 
--> the instance name changes, the left side of the curve is dragged up

**Expected behavior**
if there isnt a module instance having the same instance name, applying a style with an module having a different instance name should create a further instance instead of overwriting an existing

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.1.0+796~g3375f4f83
 - OS: OSX

**Comment by TurboGit** [comment]
This is most probably due to my work on the new iop-order support. So it has probably happened after Feb 26th. Would be nice to double check this though.

**Comment by MStraeten** [comment]
my latest build without the issue ist from Feb. 23. my next build on Feb 29 has the bug

**Comment by TurboGit** [comment]
BTW, do you confirm that we have the same issue with copy/paste of modules?

**Comment by johnny-bit** [comment]
Bisect the issue! maybe you can pinpoint the change responsible?

**Comment by TurboGit** [comment]
No need to bisect this is clear to me and I have been able to reproduce... And a fix is to come in a moment :)
