### ISSUE TITLE
Very different export when using Haze remove tool

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [darktable-org/darktable#4435]
Hi, I'm having issues ADDING haze with the Haze Remove tool, as it can be seen by the screenshots, the exported image is very different:

WITH HAZE REMOVE TOOL

Left is Darkroom preview, right is exported image:
![ERRO_HAZE](https://user-images.githubusercontent.com/47254894/76151996-7ce70880-6099-11ea-8d84-e38d5152f169.jpg)

WITHOU HAZE REMOVE TOOL

Left is Darkroom preview, right is exported image:
![NO_HAZE](https://user-images.githubusercontent.com/47254894/76152012-a011b800-6099-11ea-9992-99b5a69cb856.jpg)

EXPORT CONFIG:

![export](https://user-images.githubusercontent.com/47254894/76152025-bcadf000-6099-11ea-88ed-7844c78d1eed.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.0 (LATEST OFFICIAL RELEASE)
 - OS: WINDOWS 10
 - OpenCL activated
 - GTX 1060 6Gb Driver: 441.66

**Comment by groutr** [comment]
I can't reproduce your exact issue, something definitely seems off when using haze removal.

[![20140606-100335-06.jpg](https://i.postimg.cc/gjj4PSPc/20140606-100335-06.jpg)](https://postimg.cc/1VxDGKtb)

[![Screenshot-20200311-121701.png](https://i.postimg.cc/7Zw9HZ4Q/Screenshot-20200311-121701.png)](https://postimg.cc/vc2fXMcW)

Darktable: git master (3.1.0.r810.gdd6c2930e)
OS: Archlinux
OpenCL activated (NEO) Intel HD 530
(OpenCL disabled produces the same export)

**Comment by aurelienpierre** [comment]
Haze removal is scale-dependent. Meaning if you export your image at screen size or at full size, the results won't be the same. This is not linked to the programmatic implementation (aka software/code), it's linked to the base algorithm (aka theory/maths). 

Unless you can prove that 2 images exported at same resolution (or export at screen preview resolution) don't give the same output result, this will be a `wont-fix`.

**Comment by ItaloCunhaBueno** [comment]
Thanks for the clarification Aurelien. I guess I'll have to find another way to get same result.

**Comment by aurelienpierre** [comment]
You can either preview haze removal zoomed at 100% (and ensure high quality export is enabled, when you save the file) or use the bloom module instead.

**Comment by ItaloCunhaBueno** [comment]
I was able to get a similar look with Lowpass module in Average blend mode:


![_MG_0670_04](https://user-images.githubusercontent.com/47254894/76474973-2bfa4b80-63dc-11ea-9f34-f97620c09731.jpg)

Thank's for your support.
PS: looking forward for the new film grain module your suggested.

**Comment by kofa73** [comment]
@aurelienpierre 
> Unless you can prove that 2 images exported at same resolution (or export at screen preview resolution) don't give the same output result, this will be a `wont-fix`.

Please see
https://github.com/darktable-org/darktable/issues/10283

Darktable 100% preview (2 relevant parts):
![Screenshot_20220705_225856-darktable-100percent](https://user-images.githubusercontent.com/3177739/177417010-a48fa074-f847-4f8e-8de8-33985a872c4b.png)
![image](https://user-images.githubusercontent.com/3177739/177417578-7a22d7b5-d8cb-49f5-adf3-4bd8777636da.png)

Full-size export - if I understand correctly, this should match the 100% preview:
![Trentino_estate_2021_0459-original-size](https://user-images.githubusercontent.com/3177739/177417064-816f1f8c-7e1f-4b40-94cb-fca53b036b2f.jpg)

Exported at 0.999x scale, high quality resampling = true
![Trentino_estate_2021_0459-resized-factor-0 999-HQ](https://user-images.githubusercontent.com/3177739/177417140-661b41ba-06ce-4d50-b869-f7b8870a166f.jpg)

Exported at 0.999x scale, high quality resampling = false
![Trentino_estate_2021_0459-resized-factor-0 999-LQ](https://user-images.githubusercontent.com/3177739/177417208-0e54b14d-4c33-4ed3-a8ab-94c10857ae7c.jpg)

4.1.0+25~g7c689e4a7

Might the comment I quoted at https://github.com/darktable-org/darktable/issues/10283#issuecomment-1033711288 have something to do with LQ being closest to the darkroom preview?

**Comment by litoj** [comment]
I see this never got fixed. @aurelienpierre Maybe I don't understand the situation, but from what has been posted here it would seem @kofa73 also posted images proving this is an issue even at the same resolution viewpoint.

I ran into a different effect caused by higher haze removal setting - it seems to completely throw off the colors: (100% preview, 100%-sized export)

![Image](https://github.com/user-attachments/assets/1405ed92-2ae7-43e6-b2ce-208eb2cc3c28)

When I reopen darktable, until the moment I change some settings, the preview looks like the export, but after I touch anything, it looks as I would expect it to look again (but the export stays broken). - DT 5.0.1

[broken sample.zip](https://github.com/user-attachments/files/19408790/broken.sample.zip)

**Comment by kofa73** [comment]
The issue has been closed; Aurélien is no longer an active darktable developer. 
The issue has not been forgotten, but is very hard to fix.
See, for example:
https://github.com/darktable-org/darktable/issues/18384
https://github.com/darktable-org/darktable/issues/18378
They have also been closed, but then the change had to be rolled back for performance reasons. It will have to be fixed later. The currently open issue is:
https://github.com/darktable-org/darktable/issues/18501
