### ISSUE TITLE
Signature invalid error in 3.0.0.0-1.1 packages

### ISSUE THREAD

**Issue by bobhy** [darktable-org/darktable#4437]
**Describe the bug**
Running Ubuntu 19.10, was running darktable 3.0.0 OK.

I'm proceeding to try install from source, but this would be good to fix...

**To Reproduce**
1. install via apt
```bash
$ sudo apt update
... clip ...
Hit:9 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_19.10  InRelease
... clip ...
Err:9 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_19.10  InRelease
  The following signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
... clip ...
Fetched 862 kB in 1s (581 kB/s)              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_19.10  InRelease: The following signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_19.10/InRelease  The following signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Similar error if I download from:  `https://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_19.10/amd64/darktable_3.0.0-1.1_amd64.deb`

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0.0 via OBS PPA
 - OS: ubuntu 19.10

**Comment by aurelienpierre** [comment]
The darktable team provides the source code, your problem is linked to a particular package from a particular repository. We have no control over that repository, you should contact the maintainers of such repo. (Is it @darix's repo ?)

**Comment by laurenweinstein1** [comment]
And this is still broken. And still very annoying. Does anybody have a way to reach the maintainer of the distribution? Multiple people have asked me about this, and they assume it is a problem in the hands of the darktable team. It's not a good look, anyway.

**Comment by darix** [comment]
you just need to reimport the key of the repository. it is long fixed.

**Comment by KiwiCraft77** [comment]
@milasudril Works great, since I am using Ubuntu 22.04 I had to change the xUbuntu_20.04 in the link to xUbuntu_22.04, so here is the command for Ubuntu 22.04 `curl -fsSL https://download.opensuse.org/repositories/graphics:darktable:stable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics_darktable_stable.gpg > /dev/null`
