### ISSUE TITLE
[FR] helpful UX additions in lighttable view

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#4441]
**Is your feature request related to a problem? Please describe.**
Currently lighttable has 2 problems as identified by user:

1. After clicking `?` the whole lighttable area is one big 'X' with contextual help
2. when hovering over image in file manager mode, there's no tooltip

**Describe the solution you'd like**

For problem 1:
In lighttable view depending on mode selected the `?` mode should link to https://darktable.gitlab.io/doc/en/lighttable_chapter.html#lighttable_overview or specific section

For problem 2:
Hovering over thumbnail in lighttable in filemanager view should bring tooltip with helpful info (after usual tooltip delay).
I think the layout of tooltip should be:
```
if(! extended_thumbnail_overlay){
[image name]
[exposure time] [aperture] [focal length] [ISO]
}
[dbl click] open image in darkroom
[W] preview image
[H] more shortcuts
```

**Alternatives**
I'm wondering what shortcuts to show in tooltip for images.

Plus I do agree that in lightroom view the rightclick is underutilized (however falling into popup menu trap is not advisable)

**Additional context**

This came from thread on reddit: https://www.reddit.com/r/DarkTable/comments/feev60/darktable_user_base_survey/

**Comment by johnny-bit** [comment]
Pinging @AlicVB because this may have a good place in #4370

**Comment by Nilvus** [comment]
@johnny-bit and @AlicVB: maybe it could also be useful to add an "escape" shortcut when clicking on this icon. I have sometimes (rarely) click on this icon instead of the just side one, and no possibility to cancel that except clicking and see browser opening...

**Comment by johnny-bit** [comment]
Huh... Interesting but I agree that hardwiring `Esc` to that would be beneficial. I just click anywhere because then it shows dialog "do you want to open web browser to" and I click "No" :)

**Comment by AlicVB** [comment]
> Pinging @AlicVB because this may have a good place in #4370

Well, I'm reluctant to add more in #4370 , considering the already huge size of the PR. Otherwise, I fear that @TurboGit will try to kill me ;)

Apart from that, I've already think about the tooltip part, and the ideal imo would be a pref entry like what we do for the darkroom infoline.
And I've try to have a look at the ? part too.

But again, I prefer that we do that after #4370 if possible...

**Comment by johnny-bit** [comment]
OK, so about tooltip: I think the file line should be the same as infoline (is that configureable?) on the thumbnail itself, espeically if extended info on thumbnail is disabled ;)

I understand this is not a part of #4370 but might be a fine addition later on ;)

**Comment by GLLM** [comment]
Customizable hover tooltip is a great feature !! 
Thanks a lot @johnny-bit , this makes lighttable much more enjoyable !
