### ISSUE TITLE
negadoctor build failure

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4442]
Windows 10, current master
minGW64 

[ 76%] Building C object src/iop/CMakeFiles/negadoctor.dir/introspection_negadoctor.c.obj
In file included from C:/msys64/home/Graham/darktable/build/src/iop/introspection_negadoctor.c:5:
C:/msys64/home/Graham/darktable/src/iop/negadoctor.c:81:1: error: optimization attribute on 'powf' follows definition but the attribute doesn't match [-Werror=attributes]
   81 | extern float powf(const float x, const float y);
      | ^~~~~~
In file included from C:/msys64/home/Graham/darktable/src/common/darktable.h:61,
                 from C:/msys64/home/Graham/darktable/src/control/control.h:21,
                 from C:/msys64/home/Graham/darktable/src/bauhaus/bauhaus.h:22,
                 from C:/msys64/home/Graham/darktable/src/iop/negadoctor.c:22,
                 from C:/msys64/home/Graham/darktable/build/src/iop/introspection_negadoctor.c:5:
C:/msys64/mingw64/x86_64-w64-mingw32/include/math.h:886:22: note: previous definition of 'powf' was here
  886 |   __CRT_INLINE float powf(float _X,float _Y) { return ((float)pow((double)_X,(double)_Y)); }
      |                      ^~~~
In file included from C:/msys64/home/Graham/darktable/build/src/iop/introspection_negadoctor.c:5:
C:/msys64/home/Graham/darktable/src/iop/negadoctor.c: In function 'process':
C:/msys64/home/Graham/darktable/src/iop/negadoctor.c:259:6: note: the ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
  259 | void process(struct dt_iop_module_t *const self, dt_dev_pixelpipe_iop_t *const piece,
      |      ^~~~~~~

**Comment by aurelienpierre** [comment]
Did ad36572 not fix it ?

**Comment by GrahamByrnes** [comment]
Oh, an hour ago :-)
Will go re-launch the script...

**Comment by aurelienpierre** [comment]
darktable, best user support on Sundays evenings ;-)
