### ISSUE TITLE
Olympus OMD M1 Mark 3

### ISSUE THREAD

**Issue by Chasverizon** [darktable-org/darktable#4443]
Uploaded Creative Commons Color Card Raw image to raw.pixls.us
thank you

**Comment by tuomaskjj** [comment]
I've uploaded additional samples, CC0, of the HiRes shots, 50 and 80 Mpix, to raw.pixls.us with the accompanying ORI-files.
Using the latest Adobe DNG converter, 12.2, I've obtained the attached black- and white levels and color matrix. The black level seems to be different in different shots, however. Not sure if that is important.
[e-m1mkiii_levels_cmatrix.txt](https://github.com/darktable-org/darktable/files/4343975/e-m1mkiii_levels_cmatrix.txt)

**Comment by LebedevRI** [comment]
@tuomaskjj thank you for the samples!
