### ISSUE TITLE
Color zones default process mode is strong instead of smooth

### ISSUE THREAD

**Issue by jpenala** [darktable-org/darktable#4449]
**Describe the bug**
darktable 3.0.1 patch notes state the default color zones processing mode was reverted to smooth, but instead it still is strong. 

**To Reproduce**
1. Fire up darktable 3.0.1 (to be sure wipe /.config/darktable so any of your presets are reset)
2. Import image
3. Activate color zones and observe the default process mode is strong 

**Expected behavior**
Color zones default process mode is smooth.

**Platform (please complete the following information):**
 - darktable 3.0.1
 - Fedora Workstation 32 GNOME DE
 - OpenCL on
 - Radeon RX560, open source amdgpu driver + OCL bits from amdgpu-pro driver

**Additional context**
Possible offending commit: f5c60707d9fe168195af3f9ed43053af0da21f0b

**Comment by TurboGit** [comment]
I tend to agree !

**Comment by TurboGit** [comment]
Fixed.

**Comment by jpenala** [comment]
Thank you and everyone involved in making this great open source software! Closing the issue now.
