### ISSUE TITLE
Use physically-realistic stochastic film grain synthesis

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#4451]
Improve current seemingly-hacky film grain module with a Monte-Carlo method to produce gaussian noise at varying radii.

This can also be used as a dithering filter.

## Reference:

* https://hal.archives-ouvertes.fr/hal-01494123/file/film_grain_gaussian_texture.pdf
* https://hal.archives-ouvertes.fr/hal-01520260/file/Film_grain_synthesis_computer_graphics_forum.pdf
* https://www.ipol.im/pub/art/2017/192/article.pdf
* https://github.com/alasdairnewson/film_grain_rendering

**Comment by elstoc** [comment]
I think the goal is more physically realistic film grain. The precise implementation is probably up to whoever decides to take on the dev.

As I mentioned in IRC you might want to contact the user who made this post on pixls.us, who may already be working on something similar: https://discuss.pixls.us/t/embrace-the-noise/17248/15 or may be able to contribute some ideas if not.

**Comment by elstoc** [comment]
I tried running the program provided by https://github.com/alasdairnewson/film_grain_rendering on a 1920x1280px greyscale image and it ran for 20 hours without completion. This is similar to the experience I've had running monte carlo simulations in the past and does not seem practical for interactive editing.

I think we might need a different approach.

**Comment by heitorPB** [comment]
Have you tried the GPU version?
https://github.com/alasdairnewson/film_grain_rendering_gpu

**Comment by elstoc** [comment]
No, but really anything we do has to work semi-reasonably on CPU as well.

**Comment by heitorPB** [comment]
On Sun, 05 Dec 2021 08:48:43 -0800
Chris Elston ***@***.***> wrote:

> No, but really anything we do has to work semi-reasonably on CPU as
> well.
> 

That makes sense.

Are there any parameters that we can tune for a "low quality, but takes
10 min on an old CPU"?

**Comment by elstoc** [comment]
probably could try with fewer iterations and lower resolution input image but can we really expect to gain factors of 1000+ in speed?

**Comment by heitorPB** [comment]
On Sun, 05 Dec 2021 09:01:51 -0800
Chris Elston ***@***.***> wrote:

> probably could try with fewer iterations and lower resolution input
> image but can we really expect to gain factors of 1000+ in speed?
> 

I just checked the default number of MC simulations (iterations?) is
800. If we reduce that by a factor of 20, and use openMP, that _could_
give a ~100x speedup, right?

**Comment by elstoc** [comment]
The GPU version runs in 18 seconds for B&W with 1600 iterations so I guess maybe something was wrong on the CPU version.

**Comment by pedrorrodriguez** [comment]
> The GPU version runs in 18 seconds for B&W with 1600 iterations so I guess maybe something was wrong on the CPU version.
> 
> For example...
> 
> input: ![2021-11-08-11 17 31 0](https://user-images.githubusercontent.com/9555491/144756694-299ffb3d-3f59-4684-bb72-a15e09d0eb25.png)
> 
> output of `film_grain_rendering_main 2021-11-08-11.17.31.0.png out.tiff -NmonteCarlo 1600 -color 0` (converted to png):
> 
> ![out](https://user-images.githubusercontent.com/9555491/144756755-d4d4ab17-c1f7-4ab3-9874-41080e63299a.png)
> 
> Took 22 seconds

The results look beautiful. I wish this would come to darktable, although, if it is so resource intensive, it sounds like it might be more suited for vkdt.
Anyhow, when I try to run the program I get:

Error at src/film_grain_rendering.cu : 557 
Error type : the launch timed out and was terminated
Segmentation fault (memory data registered)

Am I doing something wrong?

I downloaded it from github.
I cd'd into the directory. 
Ran make -f makefile. 
Then I did ./bin/film_grain_rendering_main ~/Download/test.png ~/Desktop/test-grain.png -NmonteCarlo 200 -color 1

**Comment by heitorPB** [comment]
This [post in the forums](https://discuss.pixls.us/t/embrace-the-noise/17248/15) also mentions another way to have more "realistic" film grains.

**Comment by elstoc** [comment]
well yes but the guy who posted it didn't seem to ever follow up with actual code
