### ISSUE TITLE
Some Spanish translations were missed on release 3.0.1

### ISSUE THREAD

**Issue by EdgarLux** [darktable-org/darktable#4454]
**Description of the issue**
Some translations already done were missed on the new release 3.0.1. Probably due they didn't synchronize from master before the release.

**Screenshots**
![Captura de pantalla -2020-03-10 20-40-57](https://user-images.githubusercontent.com/47407674/76382259-09225580-6350-11ea-802a-88397fe0220a.png)
![Captura de pantalla -2020-03-10 20-42-44](https://user-images.githubusercontent.com/47407674/76382280-1b03f880-6350-11ea-8b2b-bdf8b20664a8.png)
![Captura de pantalla -2020-03-10 20-42-11](https://user-images.githubusercontent.com/47407674/76382353-5acae000-6350-11ea-98de-c041e998184f.jpg)

**Comment by TurboGit** [comment]
Yes, hopefully this will be synchronize for 3.0.2.

**Comment by EdgarLux** [comment]
> Yes, hopefully this will be synchronize for 3.0.2.

Thanks a lot.
