### ISSUE TITLE
Outdated video list at https://www.darktable.org/resources/

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#4455]
**Describe the bug**
https://www.darktable.org/resources/ lists 'Robert Hutton’s darktable screencast playlist' as 'Screencasts recorded using the latest development versions of darktable'; however, his youtube playlist https://www.youtube.com/playlist?list=PLmvlUro_Up1NBX7VK8UUuyWo1B468zEA0 has not been updated since 2016.

**To Reproduce**
Open the resources page and check the youtube list.

**Expected behavior**
Rober Hutton's videos appear under a different section, something like 'Screencasts recorded using an older version of darktable'.
Other relevant videos, e.g. Boris Hajdukovic's 'Editing moments with darktable' (
https://www.youtube.com/watch?v=vnkphET6pYk&list=PLmZmCIhOC2Frt6Wq3gc0-egOy_P1sXjau
) are included.

**Screenshots**
N/A

**Platform (please complete the following information):**
- Darktable Version: 3.0

**Additional context**
N/A

**Comment by ptilopteri** [comment]
The video is producted by Robert Hutton, not by or developed by dt, *appreciations* Mr. Hutton.

A better approach would be do close this issue and directly contact your benefactor, Robert Hutton.

**Comment by ptilopteri** [comment]
s/your benefactor/your's and our benefactor/

I really missed that ...

**Comment by Nilvus** [comment]
Yes, think about closing this issue. And all issues about darktable.org websites have to be posted on the Github of the website (so not here). The website Github is here: https://github.com/darktable-org/dtorg

**Comment by kofa73** [comment]
> The video is producted by Robert Hutton, not by or developed by dt, _appreciations_ Mr. Hutton.
> 
> A better approach would be do close this issue and directly contact your benefactor, Robert Hutton.

I'll close this ticket and maybe re-open it on the docs' site. However, if you give it a second read, you'll see that I didn't want to nudge Robert Hutton to create new videos, or ask darktable devs to do so; I only noted that since it's no longer true that his videos are made using the current development version, they should be moved to an 'older, but still useful' category.
