### ISSUE TITLE
[FR] make color picker "invalid input area" switch to "default area"

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#4471]
**Is your feature request related to a problem? Please describe.**

This comes on legs of #3631 
Here's the scenario:

- User selects any (even miniscule) area inside image - Currently OK
- User selects area starting outside image, but ending inside image - consider starting point at image area border and end as indicated by user - currently for this OK
- User selects area starting inside image, but extends outside image area - consider starting point inside and end at image area border - currently OK
- User starts area outside image area and ends outside image area at no point crossing image area - currently this causes a very thin area on the border of image to be used

**Describe the solution you'd like**

User starts area outside image area and ends outside image area at no point crossing image area - consider this as invalid area and reset color picker area to default area

**Alternatives**

It doesn't even have to be full area drawn outside of image to be considered invalid input and reset to default area, A simple click outside image area could also be seen as invalid input and reset color picker area to default.

There are some other possiblilities - I don't know whether right-click is utilized for color pickers but if it isn't, a right click inside or outside image area could reset color picker area...

TBH - it could be both ways - invalid input resets area AND some kind of shortcut to reset color picker area.
**Additional context**

Checkout issue #3631 starting from [my comment](https://github.com/darktable-org/darktable/issues/3631#issuecomment-598881811)
This FR could also be good(er) alternative to solve #4466 
This should IMHO be considered an additional case for PR #4431 

Looking for more input on this FR

Pinging @jenshannoschwalm and @jade-nl just to notify them ;)

**Comment by GrahamByrnes** [comment]
I think this is just an issue of helping the module to not encourage errors. Ideally, I'd like the cursor to be held prisoner on the image: ie once you click on the picker-arrow, further clicks are ignored unless they are on the image... or on the arrow again to cancel.

That might be a pita to implement.

I think your proposed solution is the best, otherwise. The first alternative has the disadvantage that if you're trying to make a rectangle that runs right to the edge of the image, you might require eye-surgeon skills to avoid an invalid click. Repeat it several times with a return to default and I could imagine my blood pressure rising...

**Comment by jenshannoschwalm** [comment]
That's all pretty easy to implement except the "be held prisoner on the image", that would be hell to do in a portable way.

Right mouse button click as a request to fall back to default as a new feature?

The scenario you describe as a blood pressure rising condition is what i also want to avoid.

**Comment by johnny-bit** [comment]
> "be held prisoner on the image", that would be hell to do in a portable way.

Yup, that would also be a bit "weird"



> Right mouse button click as a request to fall back to default as a new feature?

Don't have to be... That's why I'd imagine another key would be interesting... or maybe right click on picker button?



> The first alternative has the disadvantage that if you're trying to make a rectangle that runs right to the edge of the image, you might require eye-surgeon skills to avoid an invalid click.

Hmmm... If you start outside image say top-left corner and finish outside, on bottom right - then it should imo cover whole area of image
If you start outside image but end within image bounds (even paper thin area if ignoring my proposal in #4466) then it should allow you to do so.

I think a visual indication would be in place eg - the area rectangle being drawn only happens if area is "valid", this would help guide the picker area... Would that be difficult to implement?

btw: @jenshannoschwalm - wishing you and everybody in medical fields the best! You all are doing great job all over the world!

**Comment by johnny-bit** [comment]
Fixed by #4495
