### ISSUE TITLE
Image export fails on Windows platform

### ISSUE THREAD

**Issue by alexander-stepanenko** [darktable-org/darktable#4473]
**Describe the bug**

[darktable_bt_QADIH0.txt](https://github.com/darktable-org/darktable/files/4333362/darktable_bt_QADIH0.txt)

Export fails with the run-time error on Windows 20 Home 1909 Build 18363.720
It seems like the problem began after installing the updates:
March 12, 2020—KB4551762 (OS Builds 18362.720 and 18363.720)
March 10, 2020—KB4540673 (OS Builds 18362.719 and 18363.719)

At least right after the installation everything worked fine. No any changes to the system except of the Microsoft updates were done.

**To Reproduce**

1. Try to export any file and get the message "An unhandled exception occured"

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by TurboGit** [comment]
which dt version ? exporting on which format ? which size ? ...

please create a new issue with precise context.
