### ISSUE TITLE
performance issues in sql calls in exif.cc

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#4474]
**Describe the bug**
with darktable -d all i find sql calls delaying the processing: 

```
98.417393 [noiseprofile] looking for maker `Canon', model `EOS 5D Mark IV'
98.417416 [noiseprofile] found 13 makers
98.417420 [noiseprofile] found `Canon' as `Canon'
98.417423 [noiseprofile] found 68 models
98.417473 [noiseprofile] found EOS 5D Mark IV
98.417476 [noiseprofile] found 29 profiles
206.721234 [sql] /Users/martinstraeten/src/darktable_debug/src/common/exif.cc:3272, function dt_exif_xmp_read_data(): prepare "SELECT filename, flags, raw_parameters,        longitude, latitude, altitude, history_end, datetime_taken FROM main.images WHERE id = ?1"
```
after compress history:
```
902.907139 [sql] /Users/martinstraeten/src/darktable_debug/src/common/image.c:251, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"
1001.389837 [sql] /Users/martinstraeten/src/darktable_debug/src/common/exif.cc:3272, function dt_exif_xmp_read_data(): prepare "SELECT filename, flags, raw_parameters,        longitude, latitude, altitude, history_end, datetime_taken FROM main.images WHERE id = ?1"
```
There're further sql calls with much delays, but not that massive
```
1001.390720 [sql] /Users/martinstraeten/src/darktable_debug/src/common/exif.cc:3046, function dt_set_xmp_dt_history(): prepare "SELECT imgid, formid, form, name, version, points, points_count, source, num FROM main.masks_history WHERE imgid = ?1 ORDER BY num"
1050.140279 [sql] /Users/martinstraeten/src/darktable_debug/src/common/exif.cc:3100, function dt_set_xmp_dt_history(): prepare "SELECT module, operation, op_params, enabled, blendop_params,        blendop_version, multi_priority, multi_name, num FROM main.history WHERE imgid = ?1 ORDER BY num"
```

**To Reproduce**

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.1.0+822~g8c615963c
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
 - OS: OSX

**Comment by TurboGit** [comment]
It is not necessary an SQL delay (I have been confused during a debug session) but possibly something else happening between both calls that are not related to SQL. One possible culprit is the thumbnail generation.

**Comment by johnny-bit** [comment]
The problem is that timings arent spewed everywhere. `database.c` and related calls use bunch of logging infra and thus are easier to catch than others, which also causes to believe that long process between 2 calls to database is actually database fault.
