### ISSUE TITLE
Unhandled exception when exporting images on Windows

### ISSUE THREAD

**Issue by alexander-stepanenko** [darktable-org/darktable#4475]
**Describe the bug**

Export from darktable 3.0.1 fails with the run-time error on Windows 20 Home 1909 Build 18363.720

Export fails when exporting to the file or email. Failure affects every format.
Exporting was being attempted from Sony A73 ARW format.

It seems like the problem began after installing the updates:
March 12, 2020—KB4551762 (OS Builds 18362.720 and 18363.720)
March 10, 2020—KB4540673 (OS Builds 18362.719 and 18363.719)

At least right after the installation everything worked fine. No any changes to the system except of the Microsoft updates were done.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

Darktable: 3.0.1
OS: Windows 10 Home 1909 Build 18363.720

**Additional context**

The failure doesn't depend on the history availability. New untouched images fail with the same symptoms as those ones with the history.
I wasn't able to downgrade back to 3.0 to test.
I failed to uninstall latest Windows security updates as well.
Attaching the log file generated by darktable.
[darktable_bt_QADIH0.txt](https://github.com/darktable-org/darktable/files/4333919/darktable_bt_QADIH0.txt)

**Comment by alexander-stepanenko** [comment]
Exporting from console using darktable-cli works like a charm, btw

**Comment by Oddalchemist** [comment]
Unhandled exception when exporting images on Windows 7 to mi file on disc.

**Comment by johnny-bit** [comment]
@alexander-stepanenko - this looks like a memory issue... Does version 3.0.2 or 3.2.1 (or better yet - 3.4) work for you?

@Oddalchemist  - Please create new issue. Make sure you include ALL info necessary and make sure you're on newest release (3.2.1 has couple of known bugs, 3.4 has them fixed).

**Comment by alexander-stepanenko** [comment]
@johnny-bit 3.2.1 didn't fix the problem but changed it. Now there's now an error message during the export and even files are generated, but they don't contain the image

**Comment by johnny-bit** [comment]
OK, so...

Can you try with empty config dir? (`C:\Users\[username]\AppData\Local\darktable` - backup it somewhere then remove) and create fresh new image (no history, no xmp file, just vanilla edit) and then export? If there's an error then please upload it here for analysis.

Additionaly we'll need following info:
YOur current darktable version (3.2.1)
Your current windows version
whether or not you have antivirus that might interfere with darktable (we've got false positive reports couple months back)
The CPU you have
The GPU (graphic card(s))
The amount of ram available

**Comment by alexander-stepanenko** [comment]
Huh! Deleting the config dir did actually the thing! Now when I export an image using the GUI it's generated without any issues and properly save it. I tried both vanilla edit and already edited image with an existing XMP file - works like a charm! 

Do you think the easiest way now is to configure darktable from scratch and import all my images back again?

I assume that all extra info you requested doesn't make much sense any more, but just in case:

YOur current darktable version (3.2.1)
Your current windows version: Windows 10 Home 20H2 Build 19042.685
whether or not you have antivirus that might interfere with darktable (we've got false positive reports couple months back): Avast Free edition
The CPU you have: it is Dell XPS 13 9360 with  i7-8550U @ 1.80 GHz / 2.00 GHz
The GPU (graphic card(s)): Embedded UHD Graphics 620 (8GB memory allocated)
The amount of ram available: 16 GB

**Comment by johnny-bit** [comment]
> Do you think the easiest way now is to configure darktable from scratch and import all my images back again?

Pretty much, yes. Personally I only re-import if i need it. In case of damaged db/configs I don't really mind. After all all the images I've worked on are either already exported and "done" or i can go back (re-import) if I need them ;)

Since deleting config helped - please close this issue :) Also - there's a christmas present coming: darktable 3.4 is near :)

**Comment by alexander-stepanenko** [comment]
@johnny-bit 3.4 must be a dope! Can't help but checking the darktable website twice a day :)
Thanks a lot for helping with this annoying issue

**Comment by alexander-stepanenko** [comment]
The issue has been resolved in 3.2.1 but you may need to delete you config dir: 
C:\Users\[username]\AppData\Local\darktable
and re-import your files
