### ISSUE TITLE
add color to the temperature bar ?

### ISSUE THREAD

**Issue by senpai49** [darktable-org/darktable#4479]
![Barre des températures_dt](https://user-images.githubusercontent.com/45768233/76707718-f0b88f00-66f1-11ea-846b-95a89e3924dc.JPG)
![Barre des températures](https://user-images.githubusercontent.com/45768233/76707719-f1e9bc00-66f1-11ea-889c-294e79cb2aa0.JPG)

**Is your feature request related to a problem? Please describe.**

**Additional context**

**Comment by junkyardsparkle** [comment]
This is being worked on in #4360.

**Comment by johnny-bit** [comment]
I'm working on it (and couple other things for white balance module)

**Comment by senpai49** [comment]
thank you for the information

**Comment by johnny-bit** [comment]
This is being worked on. Can i please get a [wip] state here? :)
