### ISSUE TITLE
Sony RX100M4: weird artifact on right side of raw image

### ISSUE THREAD

**Issue by elman22** [darktable-org/darktable#4480]
**Describe the bug**
When I open a raw image from Sony RX100M4, on every image I see strange artifacts on right side of the picture. 

Here are some observations:
- Turning OpenCL on/off has no effect. Artifacts are always visible.
- Opening the same image in RawTherapee shows no artifacts (so it's not malfunctioning camera).
- If image is shot vertical, then artifacts are on bottom side.
- When I zoom image and view different part of the image, artifacts do not show (meaning it's part of the image, not part of the viewport).
- Artifact is visible in darkroom when editing and also in lighttable in sticky preview.
- Exported image also has this artifact.
- If I use lens correction, artifacts disappear, but I guess it's because the image is cropped.

**To Reproduce**
I can provide raw file, if requested.

**Screenshots**
First one is Darktable, other one is RawTherapee. Also notice how differently the blue color is handled. Maybe it has something to do with the artifact?
![darktable](https://user-images.githubusercontent.com/9151352/76710986-223e5400-670c-11ea-91ca-0956fddde1da.png)
![rawtherapee](https://user-images.githubusercontent.com/9151352/76710987-25394480-670c-11ea-98e3-29197f61120b.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Manjaro Linux
 - OpenCL activated
 - nVidia proprietary 430.64 (I have experienced the problem also with earlier versions of nVidia driver)

**Additional context**
- JPEG doesn't have this problem, but most likely because lens correction was already applied.
- Also tried on different computer with Darktable 3.0.0 and the result was the same. This computer doesn't have nVidia, but Intel HD 630.

**Comment by LebedevRI** [comment]
The sample in question is needed.

**Comment by elman22** [comment]
Zipped file DSC01783.ARW
[DSC01783.zip](https://github.com/darktable-org/darktable/files/4335164/DSC01783.zip)

**Comment by LebedevRI** [comment]
Thank you for the bugreport.
Indeed, somehow in initial camera support integration i missed this.
