### ISSUE TITLE
Add noise profile for Olympus OM-D E-M5 Mark III

### ISSUE THREAD

**Issue by olupton** [darktable-org/darktable#4481]
This is my first attempt at contributing a noise profile, so any feedback is appreciated!

I was guided by the instructions here: https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/. The results are here: [darktable-noiseprofile-20200315.tar.gz](https://github.com/darktable-org/darktable/files/4335380/darktable-noiseprofile-20200315.tar.gz). I haven't used the new profiles extensively, but they looked sensible on the example images I checked.

In order for darktable to actually use the profile when I load a raw image from this camera I had to modify `presets.json`. The `"model"` field had been populated with `E-M5MarkIII` (which is the value in `Exif.Image.Model`); I had to change it to `E-M5 Mark III`.

**Comment by olupton** [comment]
This issue is still current. #4582 shows I am not the only interested user!

**Comment by rawfiner** [comment]
Thank you for the noise profile, sorry about the delay!
I kept yours as you made profiles for all the intermediate ISO, while #4582 does not have them.
