### ISSUE TITLE
Dt 3.1.0 module rename & pipeline position's shortcut

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#4482]
Dt 3.1.0+822~ga06f8db58, nvidia + opencl on, ubuntu studio 18.10

Thanks a lot for the possibilities to rename modules on the right column, it will ease my work. I can't move the modules with ctrl+shift+L.click, in the pipeline. Is there another combination keys?

**Comment by johnny-bit** [comment]
Pinging @elstoc as it may be caused because #4464 overrode ctrl+shift+click
I don't have yet time to bisect this but it may be the cause.

**Comment by TurboGit** [comment]
Sure, most probably this. Let me have a look, should be easy to fix.

**Comment by elstoc** [comment]
Yep, probably just need to move the logic after the ctrl-shift check.
