### ISSUE TITLE
Add an option to toggle bottom and top bar without the timeline (and so on)

### ISSUE THREAD

**Issue by lapineige** [darktable-org/darktable#4484]
**Is your feature request related to a problem? Please describe.**
Since version 3.0.1, when we toggle the bottom or top "bar", we have to circle thought 3 modes (off/small bar/big bar) to activate or deactivate it.
Personally this makes me very frustrated and less productive, as I have to click 3 times instead of two, as I don't use (very often) the bottom image list/timeline, and as it changes a lot the size of the picture and as a result my perception of the image. The same goes for the top bar, I only use the small one when I change the settings, the rest of the time I have to click twice to get back to the lightroom for instance, and that's annoying and frustrating.

(I'm sorry I don't know the name of those "bars"/"ribbons"/"panels", so it's hard to describe)

**Describe the solution you'd like**
Add an option to change this behaviour, for those who would like to revert it to the "on/off" behaviour (I suppose the current solution would be the default).

Thank you

**Comment by Nilvus** [comment]
@AlicVB: we have discussed that some time ago when you changed your behavior and your argument was good. Anyway, it will be good to have this but I know you have lot of work to do with culling mode and others things to continue from your lighttable rewriting.

**Comment by AlicVB** [comment]
Let's see the good side of the current situation : I'll have a *lot* of free time in the next weeks !
I'll have a look at this !

**Comment by Nilvus** [comment]
> Let's see the good side of the current situation : I'll have a _lot_ of free time in the next weeks !
> I'll have a look at this !

I have thought of that as you are like me, living in France ;-) And now that your lighttable rewrite is merged, I will take some time this week to work on CSS also. My plan were on start to spend a lot of time hiking on the mountains but will no more be possible (not so near me as it's possible now since government announcement yesterday).

**Comment by AlicVB** [comment]
should be fixed in PR #4526

**Comment by lapineige** [comment]
I don't understand what the PR does (what is "accels" ?), but it sounds good :D

**Comment by AlicVB** [comment]
accels == shortcuts

**Comment by lapineige** [comment]
Ok thanks. So there will be no way to switch back to the previous behavior, but we will be able to add shortcuts to toggle individual part instead ?

**Comment by AlicVB** [comment]
if you speak about the click on the little arrows, no that won't produce the previous behavior.
But now you'll be able to very precisely toggle all panels with shortcuts. I think I've covered all possibility with that PR.

**Comment by lapineige** [comment]
Ok. To me it's not as comfortable as before, but at least it solves the issue. Thanks for your reactivity :)

**Comment by lapineige** [comment]
Is this PR included in 3.0.2 ? I don't find it in the release notes, nor in the UI (maybe I didn't understand correctly what it does ?). I supposed it would be as it was integrated into master a while before 3.0.2 release, but I'm not aware of the way new commits are handled.

**Comment by Nilvus** [comment]
Not all commits between minor releases are set to the next minor release. Some things are set for next major one. You could see for which milestone on the PR (here for 3.2). So you will have to be patient for that one.

The choice depend on lot of things like the importance of the change or if it's related to another major change, for example.

**Comment by lapineige** [comment]
Oh yeah I missed the milestone item !
Thanks for explaining this :)

I'll wait then :)
