### ISSUE TITLE
[FR] configureable suffix for "unique" filename on export

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#4485]
**Is your feature request related to a problem? Please describe.**

This steemed from conversation on #4477, but in relation to non-duplicate uses for export.

Currently when doing export again using "unique" mode instead of "overwrite", person doing export with default settings would get "filename_export#.ext" file as a result.

**Describe the solution you'd like**

As is case with XMP files, duplicates etc, the file suffix can mean bunch of things. I postulate to introduce configurable suffix for filename uniqueness. Make it by default to be current solution. 

**Alternatives**

Of course user can always choose different dir for exports etc, however I find myself sometimes exporting same file after minor adjustments and would like to preserve the fact that it's another export. Also it woudl be great to combine it with duplicate names functionality.

**Additional context**

See the discussion in #4477 and connected issue #4115

pinging @elstoc

**Comment by elstoc** [comment]
I can think of three main ways you could add uniqueness to an exported file

- an incremented number $(INTEGER)
- current datetime $(DATETIME)
- an incremented letter $(A_Z)

If you could incorporate that into a custom template that would probably do it. For example I would probably prefer to append something like " (export 2)" to the second export of a file. In that case I would define a template ` (export $(INTEGER))`.

**Comment by todd-prior** [comment]
![image](https://user-images.githubusercontent.com/44409419/76877798-4dc75880-684a-11ea-9650-8cbb49a27478.png)
I mentioned this approach in the other thread, ie like using an approach like contructing a filter in the collections module...this is a bit like what ON1 does as shown in the screenshot ....picture better than words...

**Comment by johnny-bit** [comment]
hmmm... that's interesing... A "name builder" in export module... and "in case of conflict add to name to guarantee uniqueness" builder? :)

**Comment by elstoc** [comment]
IMO the existing method of building names using variables is fine - I like its flexibility. If we could extend it to remove delimiters if variables are empty and to add an additional 'unique' pattern for naming subsequent exports it'd be perfect. The gui sort of builder might be fine as an alternative but that sort of thing tends to be less flexible. For example, you can use bash-like substitution in the existing export, which might be more difficult to define in a gui builder.

Perhaps the gui builder could be used to generate a format string in the existing box from a popup window? That way people could use either method, maybe starting with the gui name builder and then tweaking the format string manually.

**Comment by johnny-bit** [comment]
> IMO the existing method of building names using variables is fine - I like its flexibility

Mee too! I like it, but I'm not a fan of `Filename__-_..jpg` in case some vars are empty ;)

> If we could extend it to remove delimiters if variables are empty and to add an additional 'unique' pattern for naming subsequent exports it'd be perfect.

AMEN!

> Perhaps the gui builder could be used to generate a format string in the existing box from a popup window?

That would be kinda cool. Currently there's a HUUUGE tooltip on it + code completion. If that could be thrown into popup builder (bauhaus style) and then (I know this would be super-dreamy complicated but we're talking FR that would be cool to have in 3.6) maybe updatable example? Even better if based on currently selected file?

Cool thing with GUI stuff being "you can do this and much more" instead of "you can only do what you see here" is for many it'd be a great stepping stone instead of obstruction.

**Comment by todd-prior** [comment]
That’s what I was thinking that you would still have the box and string as it is working now and defined it could just be constructed in a way that is used to make a collections filter….

**Comment by elstoc** [comment]
For the 'delimiters when variables are empty' issue, we probably need (as a minimum) two new additions to the export module:

- a tick box "remove delimiters before empty variables" 
- a text entry box (greyed out if the tick box is unticked) where you can define a list of delimiting characters (understanding that they will only be considered delimiters where they are present between two variables or bash substitutions - i.e. not where those characters are returned by a variable)

For the 'managing conflicts' issue we'd need a text box where the format string could be entered.  That should also be hidden or greyed out if 'overwrite' is selected.

The export module is already pretty big so we might want to consider if there's a way to stop it growing too much more or even to shrink it down a bit. 

Also, these changes might be better split into two PRs - the first to manage the main issues and the second to put a gui on it.

**Comment by phweyland** [comment]
> For the 'delimiters when variables are empty' issue, we probably need (as a minimum) two new additions to the export module:
> 
>     * a tick box "remove delimiters before empty variables"
> 
>     * a text entry box (greyed out if the tick box is unticked) where you can define a list of delimiting characters (understanding that they will only be considered delimiters where they are present between two variables or bash substitutions - i.e. not where those characters are returned by a variable)



This is not an export module feature. That's a variable expansion feature. This expansion is used not only in export module but also in export_metadata and watermark.

Variable expansion has no specific UI, except its syntax. Then something should be added there (syntax) to turn this possible.

I think this deserve a PR in itself (not to mix too many topics in the same box).

**Comment by elstoc** [comment]
> I think this deserves a PR in itself

I agree - it is a different issue than the one mentioned here. Should I raise a separate feature request incident?

**Comment by johnny-bit** [comment]
> Should I raise a separate feature request incident?

yes!
