### ISSUE TITLE
Glitches about lighttable rewrite: list them all here !

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4487]
Thanks to the awesome and big work of @AlicVB merged this day, we now have a far better and faster lighttable. This change also some thing from how users see them (a little). I will work this week on CSS part to improve it.

So, I suggest to all of you add posts here to precise UI glitches about this part here.

Please be the more precise as possible: which part (if screen capture, not a too big one but just the part to fix) you see. Precise also with which of the actual four themes you see that. I will begin (I don't check things a lot by now) with the first issue I will fix in the second post.

For what I've seen by now, I think issues will not be a lot !

@TurboGit or @aurelienpierre or @AlicVB. One of you could assign this issue to me and necessary labels? Thanks.

**Comment by Nilvus** [comment]
First issue:

On darktable-grey theme: text over thumbnails is not really readable (not to adjust color).

**Comment by AlicVB** [comment]
More than that : as said (or not, don't remember) I've absolutely not done anything for theme other that the base one.
The idea was to first have a clean base theme, which will be easier to tweak after.

Again, thanks for taking care of this part, and ping me here or directly by mail if you need anything !

**Comment by Nilvus** [comment]
> More than that : as said (or not, don't remember) I've absolutely not done anything for theme other that the base one.
> The idea was to first have a clean base theme, which will be easier to tweak after.

I confirm that you precise that on your PR.

**Comment by AxelG-DE** [comment]
I donno this is a CSS clitch, actually I don't think so, but this is suddenly the max view I can get in lighttable view and I must say I do not like it so much (it was covering the full area before, w/o that DIA-Frame)....

![Screenshot_20200319_205402](https://user-images.githubusercontent.com/49004103/77109208-ce8d7c80-6a23-11ea-9f12-fe66dc13408c.png)

**Comment by AlicVB** [comment]
That's intended. The idea is to keep a coherent design between mode. You are still in filemanager mode, and it's how image are display here.
Better use (sticky)full preview if you want the image with the framing background. Note that now, you can show all panels in full preview mode if you need them.

(and yes, not configurable via css)

**Comment by AxelG-DE** [comment]
I am medium happy as I used this view in the past regularly. But I don't wanna be against, as we gonna see, what new things might bring good in the future and I will get used to alt+W :-)

**Comment by Nilvus** [comment]
> I am medium happy as I used this view in the past regularly. But I don't wanna be against, as we gonna see, what new things might bring good in the future and I will get used to alt+W :-)

This full preview is quite better and having a more consistent behavior on same view is better. You will see that on full preview mode you can move on images with mouse wheel or left and right arrows !

**Comment by AxelG-DE** [comment]
Forgive me, when I say this, but other than @Nilvus above said, I have the strong feeling, the lighttable got way slower in scrolling even I just did a fresh darktable-generate-cache on 3.1.0-972-g9dfdcc8c6

**Comment by AxelG-DE** [comment]
I must step back a little. Also darkroom got much slower, so there must be something else
I got similar experiance in the past, when nvidia-drivers got installed for a diff. kernel version, but that is not the case atm

**Comment by Nilvus** [comment]
> Forgive me, when I say this, but other than @Nilvus above said, I have the strong feeling, the lighttable got way slower in scrolling even I just did a fresh darktable-generate-cache on 3.1.0-972-g9dfdcc8c6

Please avoid other things that CSS issues here. That will not help me to !

**Comment by AxelG-DE** [comment]
sorry I shut up

**Comment by Nilvus** [comment]
Another issue posting by a user on french darktable Matrix channel:
- in filemanager, select just one image to show, go at the end and scroll (quite infinite scroll possible). I'm not sure but will test if moving undershoot/overshoot could help here or not (@AlicVB: what's your idea on that?).

**Comment by Nilvus** [comment]
@AlicVB: another annoying glitch issue (that I can't fix with CSS). Go on a lighttable filemanager view without any image (for example rejected filter without of course any rejected image on it). Go then to preferences and change theme with different colors of course. See that lighttable background is not updated and text seems to loose antialiasing and sometimes not aligned correctly. I also had two times (second time tonight) a removed image (after rejecting it) remains partially visible on background on same view without any more image. So probably same refreshing issue. Hope it's clear.

**Comment by jenshannoschwalm** [comment]
> Go on a lighttable filemanager view without any image

Confirmed. It's even easier to trigger, just resize the darktable window and the text is overwritten and not replaced.
![Bildschirmfoto von 2020-03-20 07-20-55](https://user-images.githubusercontent.com/50982232/77140930-71bdb080-6a7b-11ea-9465-00c57c5e841e.png)

**Comment by TurboGit** [comment]
This one is for @AlicVB:
- ensure scrollbar in darkrrom is enabled
- open darkroom and hide the filmstrip
- go back to lighttable
- select 4 thumbs per row, the idea is to have big thumbs to easily reproduce
- zoom in image by scrolling
- type `ctrl-f` to enable filmstrip

The filmstrip is displaying large thumbs (same size as lightttable). See screenshot:
![Capture d’écran de 2020-03-21 15-50-30](https://user-images.githubusercontent.com/467069/77229092-04e60b80-6b8c-11ea-9bd5-57c7e4d3a3f8.png)

- if you scroll into the filmstrip the display goes back to normal, so probably just missing a redraw

**Comment by Nilvus** [comment]
@AlicVB: I think you could assign this to you now. It seems there's no more CSS glitches and some glitches listed here remaining could not be fixed by CSS.

**Comment by AlicVB** [comment]
Ok, I've fixed issues reported here in PR #4520 : 
- @Nilvus : the zoom==1 scrolldown
- @TurboGit : the filmstrip redraw if darkroom scrollbars are on

@jenshannoschwalm : I've seen that you've fixed the empty collection window. Thanks a lot !

**Comment by Nilvus** [comment]
> Ok, I've fixed issues reported here in PR #4520 :
> 
>     * @Nilvus : the zoom==1 scrolldown
> 
>     * @TurboGit : the filmstrip redraw if darkroom scrollbars are on
> 
> 
> @jenshannoschwalm : I've seen that you've fixed the empty collection window. Thanks a lot !

Oh, thanks @AlicVB. So maybe it's better now to close this issue as all listed glitches here seems to be fixed. If necessary, that could be reopen or new issues created.

**Comment by AlicVB** [comment]
yes, better closing and open new issue(s). It will easier to follow !
