### ISSUE TITLE
Add E-M1 Mark III noise profile

### ISSUE THREAD

**Issue by tuomaskjj** [darktable-org/darktable#4490]
Noise profiles for Olympus E-M1 Mark III. Support for the camera added from #4443 
Tested with couple high ISO pictures, 3200 and 6400, and seem to work well.
[darktable-noiseprofile-20200312.tar.gz](https://github.com/darktable-org/darktable/files/4344451/darktable-noiseprofile-20200312.tar.gz)

**Comment by TurboGit** [comment]
Thanks merged.
