### ISSUE TITLE
FR: variable expansion to remove delimiters when variables are empty

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4493]
**Is your feature request related to a problem? Please describe.**
When using multiple variables to control the file name of exported files, if any of the variables are empty the resulting filename includes multiple delimiters. For example, `$(FILE_NAME)_$(EMPTY_VARIABLE)` will have a trailing underscore - it will show `$(FILE_NAME)_`.

**Describe the solution you'd like**
A configurable way to flag certain characters as delimiters and ensure that they are removed if the following variable or substitution string is empty.

This probably requires, as a minimum, the following new preference options:

- a tick box "remove delimiters before empty variables" 
- a text entry box where you can define a list of delimiting characters (understanding that they will only be considered delimiters where they are present between two variables or bash substitutions - i.e. not where those characters are returned by a variable)

This request stems from discussions in https://github.com/darktable-org/darktable/issues/4485 and https://github.com/darktable-org/darktable/pull/4477

**Comment by parafin** [comment]
bash has the following syntax which can help:
```
${parameter+alt_value}, ${parameter:+alt_value}
If parameter set, use alt_value, else use null string.
```

**Comment by elstoc** [comment]
Wow thanks @parafin, and this works in darktable too. So if I use `$(FILE_NAME)$(TITLE+_$(TITLE))` it outputs `$(FILE_NAME)` if title is empty and `$(FILE_NAME)_$(TITLE)` if it isn't.  Perhaps this FR isn't needed after all.

**Comment by elstoc** [comment]
Only caveat is you can't nest these things very well. For example, in #4477 we have been discussing the possibility of appending `_$(SHORT_DESCRIPTION)` if it's populated, or `_$(VERSION)` if it's not and there is at least one duplicate, or nothing if neither of these are true. I don't think you can nest deeply enough to achieve this.

**Comment by parafin** [comment]
You can imagine some rule, which will be impossible to implement with your suggestion too;) Removing separators is quite specific logic and not very pretty IMHO.

**Comment by elstoc** [comment]
You may be right. 

On 18 March 2020 14:34:19 GMT+00:00, parafin <notifications@github.com> wrote:
>You can imagine some rule, which will be impossible to implement with
>your suggestion too;) Removing separators is quite specific logic and
>not very pretty IMHO.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/darktable-org/darktable/issues/4493#issuecomment-600658079

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by parafin** [comment]
This string probably does what you want: `$(FILE_NAME)$(SHORT_DESCRIPTION+_$(SHORT_DESCRIPTION))$(SHORT_DESCRIPTION-_$(VERSION))`

**Comment by phweyland** [comment]
What about a duplicate module variable $(DUP_SUFFIX) which provides directly the needed value ?

- null if the there is no duplicate
- equivalent of $(SHORT_DESCRIPTION-$(VERSION)) otherwise ?

The initial @parafin suggestion should work:

`$(DUP_SUFFIX+_$(DUP_SUFFIX))`

**Comment by parafin** [comment]
Ah, OK, I missed the requirement of adding nothing if no duplicates. How can this situation can be detected? Is VERSION variable empty then? If not, how does your original proposal helps here?

**Comment by elstoc** [comment]
I would solve that very specific naming convention for those that want to use it. I was just looking for something that kept some flexibility and was therefore more generic, in case someone did want to use, say, $(TITLE) in a similar naming convention. If we did implement the new variable we also need to handle where there's no duplicate but there is a name. The duplicate module still displays even if there's only one version and someone might enter a name they still want to use (this is my normal use case).

**Comment by elstoc** [comment]
> Is VERSION variable empty then

No. I had proposed a new variable $(VERSION_IF_MULTI) that would return the same as $(VERSION) but only if there was at least one duplicate

**Comment by elstoc** [comment]
Sorry I feel like I'm now spamming lots of incidents and PRs with similar discussions.

**Comment by phweyland** [comment]
> $(VERSION_IF_MULTI)

The suggestion above does the same plus include the potential presence of the name

**Comment by elstoc** [comment]
It does now you edited it!

**Comment by phweyland** [comment]
> It does now you edited it!

Correct, I'd missed the name :(

**Comment by phweyland** [comment]
To offer all the possibilities to the user we could have both
- $(VERSION_IF_MULTI) (maybe to rename it $(DUP_VERSION))
- $(DUP_SUFFIX)

**Comment by parafin** [comment]
Is this really needed? Why not have suffix for all images, even without duplicates, if user wants to have it? It's not like there is a way to change export module settings for existing dt installations, so most people won't use this variable anyway.

**Comment by phweyland** [comment]
> Why not have suffix for all images,

If the user starts to use duplicate he will face the export naming issues.
The idea here is to have a basic naming rule which complies with all cases, without changing what already works.

**Comment by parafin** [comment]
Another idea is to set SHORT_DESCRIPTION by default to something like dup$(VERSION) when user creates a new duplicate. So it will be empty for original image and contain something for duplicates.

**Comment by parafin** [comment]
> > Why not have suffix for all images,
> 
> If the user starts to use duplicate he will face the export naming issues.
> The idea here is to have a basic naming rule which complies with all cases, without changing what already works.

So the idea is to change default export module naming setting? As I said, it won't be applied to existing installations anyway.

**Comment by phweyland** [comment]
> As I said, it won't be applied to existing installations anyway.

Could you explain ?

**Comment by elstoc** [comment]
> So it will be empty for original image and contain something for duplicates.

I have many images where I created a duplicate then deleted the original - so I have only one version, but it's v1, not v0.

**Comment by phweyland** [comment]
> As I said, it won't be applied to existing installations anyway.

Ok, I see the case of existing user export presets. Seems difficult to update them.
Otherwise the default preset should apply, shouldn't it ?

Then if we want to fix the duplicate module naming issue we would have to include the corresponding rules in $(FILE_NAME). The only point is that we don't give a lot of flexibility to the user...

**Comment by parafin** [comment]
IMHO dt has enough configuration options already. They seem to multiply uncontrollably. How many users actually complained about duplicate naming issue and support exactly this solution to the problem? IMHO existing DT variable functionality is enough.

**Comment by elstoc** [comment]
I'd still much rather give the user components for them to build their own solution than a pre-built solution that won't be applicable to a lot of people, hence my trying to just give them fairly simple new data items that they can build into their own rules. 

We have to accept some limitations and perhaps the idea of a single variable with 'a description or a version number but only if there are multiple images with an optional delimiter' is just too specific to be of use to most. I still think (and sorry for repeating myself) that a single new metadata item plus the version number (and perhaps also `$VERSION_IF_MULTI`) will be fine for the vast majority, especially with the added substitution option that @parafin has suggested.

**Comment by phweyland** [comment]
I understand the complexity @parafin concern. Endless options turn the maintenance more difficult. But as is, duplicate module is a bit incomplete and at least it's worth to have tried to fix it.

At this point I guess we agree we don't need to change the expansion process, do we ?

**Comment by elstoc** [comment]
I agree. To summarize, the following syntax resolves my issue:

`$(VARIABLE+_$(VARIABLE))`

Which returns `_$(VARIABLE)` _only if the variable is populated_
