### ISSUE TITLE
Image information not readable depending on chosen theme.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#4498]
**Describe the bug**

Depending on the chosen theme when using mouse hover on an image the image information isn't readable.

The following theme's are unaffected: darktable, darktable-elegant-darker and darktable-icons-darker.

The rest of the lighter theme's are affected.

**To Reproduce**

1. select a theme
2. hover over an image
3. (try to) read image info
4. select another theme goto step 2

**Expected behavior**

Image information to be readable.

**Screenshots**
This is the darktable default theme, highlighted image has a readable info overlay:
![sc darktable default theme](https://user-images.githubusercontent.com/56407344/77078303-afc4c100-69f6-11ea-9170-332a323803e5.png)

This is the darktable-elegant-grey theme:
![sc darktable elegant grey](https://user-images.githubusercontent.com/56407344/77078339-bce1b000-69f6-11ea-8708-124ba050ba52.png)

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.1.0+967
 - OS: Linux / Debian 10.3

**Comment by AlicVB** [comment]
yes, please have a look at #4487

**Comment by jade-nl** [comment]
Missed that one. Sorry!

**Comment by Nilvus** [comment]
> Missed that one. Sorry!

Yet, I've written a title quite clear !

**Comment by jade-nl** [comment]
> Yet, I've written a title quite clear !

Is it wise to assume that a non-developer knows this issue is actually css related......

I made a mistake, I apologized. This doesn't invite developers to rub in in some more.

**Comment by Nilvus** [comment]
> Is it wise to assume that a non-developer knows this issue is actually css related......
> 
> I made a mistake, I apologized. This doesn't invite developers to rub in in some more.

You're right, I didn't think of that. So I made a mistake too, sorry.
