### ISSUE TITLE
[lighttable] copy history stack, missing "select parts to copy" window

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4500]
**Describe the bug**

when I am in lighttable view, want to copy a history stack from one pic to another, the "select parts to copy" do not show up anymore.
One can still do "copy all" and "paste..." and the "select parts to paste" window still comes

**To Reproduce**

**Expected behavior**

As before, the "select parts to copy" should come again (and ideally have the default modules deactivated, but I guess that is an add. FR)

Platform (please complete the following information):

    Darktable Version: 3.1.0+972~g9dfdcc8c6
    OS: [Gentoo Linux]
    OpenCL activated yes and no, both effected
    2x nvidia GTX 160OC with nividia-drivers-440.59

Additional context

    Can you reproduce with another Darktable version --> t.g.d
    Can you reproduce with a RAW or Jpeg or both? --> RAW only
    Are the steps above reproduce with a fresh edit (removing history)? --> yes
    Did you compile Darktable yourself? If so which compiler was used, with what options?
    --> gcc-9.2.0 CFLAGS="-march=native -O3 -mtune=native -pipe"
    Is the issue still present using an empty/new config-dir --> Yes

**Comment by Nilvus** [comment]
Indeed, I can reproduce. Shift+Ctrl+C shortcut works fine but clicking on the copy... button in development module doesn't works anymore. @AlicVB!
