### ISSUE TITLE
[filemanager2] Double-click on thumbnail doesn't open in darkroom

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#4502]
**Describe the bug**
In the new filemanager mode of lighttable, double-clicking on a thumbnail no longer opens the file in darkroom mode, but instead displays a transient warning: "no image selected!"; using the "d" keyboard shortcut works fine.

**To Reproduce**
See above.

**Expected behavior**
See above.

**Platform (please complete the following information):**
 - Darktable Version: master at 9dfdcc8c6819ac46af65780d5cebadebcd8fc17b
 - OS: Linux, gtk 3.24.12

**Comment by Nilvus** [comment]
I can't reproduce that on 64d5ee2d1b282aeee5adc4764adc20b847038029 (just 3 commits before). I have tested many images and double-click works on my side. I'm using Linux Ubuntu 20.04 (last update) with Gtk 3.24.14.

**Comment by junkyardsparkle** [comment]
Ok, if nobody else can reproduce, I'll assume it's just a local issue. I might have time to look into it deeper later.

**Comment by AlicVB** [comment]
I can't reproduce too :( anything special on your side ?

**Comment by junkyardsparkle** [comment]
> anything special on your side ?

Well, environment is a not-quite-current snapshot of Slackware -current, so... probably. ;)

I'll close this until I have a better idea of the cause. Nice work on the filemanager otherwise!

**Comment by junkyardsparkle** [comment]
Reopening this, since it was just reported on the list by somebody else: https://www.mail-archive.com/darktable-user@lists.darktable.org/msg09108.html

**Comment by s5k6** [comment]
I see this too, on an up-to-date Arch Linux, and with

    $ darktable --version
    this is darktable 3.1.0+1283~g36b8d524a
    copyright (c) 2009-2020 johannes hanika
    darktable-dev@lists.darktable.org

    compile options:
      bit depth is 64 bit
      normal build
      SSE2 optimized codepath enabled
      OpenMP support enabled
      OpenCL support enabled
      Lua support enabled, API version 5.0.2
      Colord support disabled
      gPhoto2 support enabled
      GraphicsMagick support enabled
      OpenEXR support enabled

**Comment by AlicVB** [comment]
@junkyardsparkle @s5k6 : right, so let's try to do remote debugging...
- Do you reproduce this every time ?
- What is your desktop and your gtk version ?
- Are one of you able to copy/paste some lines in the code and recompile ?

**Comment by junkyardsparkle** [comment]
> Do you reproduce this every time ?

In the short time I was using it, yes, including with a fresh config.

> What is your desktop and your gtk version ?

No desktop, just fluxbox window manager, gtk version given above.

> Are one of you able to copy/paste some lines in the code and recompile ?

Yes, I have some time I can spend on this today, but I'll need more caffeine first. ;)

**Comment by AlicVB** [comment]
Great, so can you 
1. test that you can reproduce the bug.
2. add the line detailed above.
3. test to see if that solve the bug or not

The change to apply is "simply" adding the line :  
`dt_control_set_mouse_over_id(thumb->imgid);` in `src/dtgtk/thumbnail.c` just before the line n°388
the content of the "if" will be : 
```
  {
    dt_control_set_mouse_over_id(thumb->imgid);
    dt_control_signal_raise(darktable.signals, DT_SIGNAL_VIEWMANAGER_THUMBTABLE_ACTIVATE, thumb->imgid);
  }
```
Thank you very much

**Comment by junkyardsparkle** [comment]
Confirmed bug is still there in master-3.1.0+1295~g1329f2bb built today, tested with clean config... I'll build and test the patched version momentarily.

**Comment by junkyardsparkle** [comment]
...aaaand confirmed that adding the line results in normal double-click behavior. Note that the line you describe as 388 is actually 369 in current master. :-)

**Comment by AlicVB** [comment]
oops, sorry for the line number. I've forgot that I was in my culling rewrite branch.
Anyway, thank you very much for the tests. I'll propose a PR soon.

**Comment by junkyardsparkle** [comment]
@AlicVB Thanks for the fix, I'm enjoying the new lighttable experience now. :-)
