### ISSUE TITLE
A problem with adding brush or free path mask 

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#4508]
There is a problem with adding brush or free path mask in retouch module or free path mask in spot removal module.

Open retouch module for the first time for an image. Select free path or brush. Click on the image canvas. Nothing happens. If a circle or ellipse is added first, free path or brush can be added also. Spot removal module behaves the same with free path mask.

Darktable git master, latest commit is 773393c98e0017992694244123c75b13d9f14175
Linux Mint 19.3 x64 Mate
OpenCL enabled
Radeon 580 graphics card

Peter Harde replied to the mail on the problem:
After updating to dt 3.1.0+963, I can confirm the behaviour (at least) for retouch and spot removal. I tried several other modules (about 10), they do not show this issue. After playing around with retouch, switching between free path and circle, I found this error messages in
console :

**** BUG *****
**In pixman_region32_init_rect: Invalid rectangle passed**
**Set a breakpoint on '_pixman_log_error' to debug*

**Comment by johnny-bit** [comment]
This is (most likely) fixed in current master. I haven't been able to reproduce the issue on 3.2.1, 3.4.0 nor current master.

Next time such bug pops up, we really need that breakpoint from pixman :/
