### ISSUE TITLE
lighttable excessive processing

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4512]
On darktable master (3.1.0+991~g773393c98) installed on ArchLinux. Issue occurs both with and without OpenCL.

I have a single image in a collection. When I open darktable with `darktable -d all`, lighttable opens and shows the following in the terminal:

```
1.265126 [lighttable] expose took 0.0000 sec
1.279970 [lighttable] expose took 0.0000 sec
1.504386 [lighttable] expose took 0.0000 sec
1.953287 [lighttable] expose took 0.0000 sec
```

If I double-click on the image to enter the darkroom and then double-click again to re-enter the lighttable, the same log message appears **708 times**.

**Comment by TurboGit** [comment]
Probably related to your rework @AlicVB .

**Comment by AlicVB** [comment]
That's ok, it's just a "blank" operation : expose is triggered, but nothing is done for filemanager. See the timings.
I'll have a look to remove the msg in this cases
