### ISSUE TITLE
Culling mode: reject image goes on last selected ones not last shown ones

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4515]
**Describe the bug**
Since lighttable rework, culling mode have a different behavior. Now, rejected an image (with all except rejected ones filter) make the selection come back to first selected ones and not last ones seen (except rejected one of course)

**To Reproduce**
1. Having a set of images to see on culling mode (at least 5 ones to be sure understanding the behavior)
2. Select first one and go to culling mode with 2 images seen each time
3. Go for example to image 4 and reject the image. The image disappear
4. See that selection come back to images selected (here image 1 and 2) instead of images 2 and 3 like before. So need to go back to last shown images manually to continue selection (quite annoying).

**Expected behavior**
As before, don't reset to selected ones on culling mode but just last shown images, by respecting of course filter selection.
@AlicVB: Of course, as I know you will rewrite culling mode, this is for your to-do list! One more thing!

**Comment by Nilvus** [comment]
@AlicVB: just find that's not only in culling mode but also on preview mode (Alt+W). Just select an image on lighttable then go on preview mode and move on another image, reject the image (with filter all except rejected ones activated before of course). See that you come back on the first selected image instead of just last shown one. Quite annoying as I use preview and culling mode quite often to select images I will keep and those I will put on trash.

**Comment by Nilvus** [comment]
@AlicVB: hope you could propose a PR after actual thumb overlays work. Really annoying when sorting images to come back on first selected image each time. So just as a reminder. Thanks!

**Comment by AlicVB** [comment]
@Nilvus : I must admit I've pause the culling rewrite to focus on more little and less difficult things. I should have more free time in the next 2 weeks, and it's on top of my todos !

**Comment by Nilvus** [comment]
> @Nilvus : I must admit I've pause the culling rewrite to focus on more little and less difficult things. I should have more free time in the next 2 weeks, and it's on top of my todos !

I understand, thanks. Just take in account that's not only on culling mode. Even on preview mode, it's the same.

**Comment by rawfiner** [comment]
@Nilvus encountered the same problem, but I have a workaround (though not very easy to explain, let me know if that is not clear):
move the mouse out of dt's window so that no picture in the bottom list appears "hovered". Once no picture in the bottom list looks "hovered", the behavior is normal.

**Comment by Nilvus** [comment]
> @Nilvus encountered the same problem, but I have a workaround (though not very easy to explain, let me know if that is not clear):
> move the mouse out of dt's window so that no picture in the bottom list appears "hovered". Once no picture in the bottom list looks "hovered", the behavior is normal.

Not sure to understand how you can reject an image if no image is hovered that way?

**Comment by rawfiner** [comment]
> Not sure to understand how you can reject an image if no image is hovered that way?

I used culling with only one image shown at the same time, and used the shortcut 'R' for rejecting
