### ISSUE TITLE
Single image import without xmp and empty collection fails to open properly

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#4516]
**Describe the bug**

Upon opening fresh darktable (no configs, empty db, no images open previously) and trying to import single image (that should get then opened in darkroom) a message is shown: "error loading file `filename`". After returning to lighttable, selecting collection and then doubleclicking on image it opens properly.

**To Reproduce**

1. have empty everything and make sure the pic you're about to export doesn't have xmp (no xmp file seems important)
2. Go to lighttable -> import
3. Click on `image...`
4. select image to import and click `open`
5. See error "error loading file `filename`"
6. see that it isn't opened in darkroom

**Expected behavior**

Upon importing single file the file should be opened in darkroom. Upon returning to lighttable it should be present there.

**Screenshots**

empty lightroom:
![Zrzut ekranu z 2020-03-21 17-48-41](https://user-images.githubusercontent.com/10687765/77231602-67470800-6b9c-11ea-95db-c603e447cefd.png)

error right after importing single image:
![Zrzut ekranu z 2020-03-21 17-48-51](https://user-images.githubusercontent.com/10687765/77231603-68783500-6b9c-11ea-8c2e-d26543ca243e.png)

however imported image IS present:
![Zrzut ekranu z 2020-03-21 17-49-47](https://user-images.githubusercontent.com/10687765/77231604-6910cb80-6b9c-11ea-9e53-eb1ee4c237d1.png)

error present even in non-empty collection when there's no xmp for single file:
![Zrzut ekranu z 2020-03-21 17-58-35](https://user-images.githubusercontent.com/10687765/77231842-b93c5d80-6b9d-11ea-825b-55b0399773a3.png)

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.1.0+999~gc250dda10
 - OS: Linux
 - OpenCL: NO

**Additional context**

 - Can you reproduce with another Darktable version?
doesn't reproduce before lighttable rewrite merge

 - Can you reproduce with a RAW or Jpeg or both?
*BOTH*

 - Are the steps above reproduce with a fresh edit (removing history)?
The error happens _only_ when there's no XMP for the file

 - Did you compile Darktable yourself? If so which compiler was used, with what options?

YES!
```sh
./build.sh --disable-opencl --disable-game --install --build-type Debug
```
 - Is the issue still present using an empty/new config-dir

YES!

** `darktable -d all` output **
This is present in logs just after clicking `open` in import dialog:
```
11,942244 [sql] /home/johnny/darktable_repos/upstream/darktable/src/libs/collect.c:1572, function list_view(): prepare "SELECT folder, film_rolls_id, COUNT(*) AS count FROM main.images AS mi JOIN (SELECT id AS film_rolls_id, folder       FROM main.film_rolls)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC"
11,942835 [sql] /home/johnny/darktable_repos/upstream/darktable/src/libs/tools/timeline.c:624, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' ORDER BY db.datetime_taken ASC LIMIT 1"
11,942961 [sql] /home/johnny/darktable_repos/upstream/darktable/src/libs/tools/timeline.c:645, function _time_read_bounds_from_collection(): prepare "SELECT db.datetime_taken FROM main.images AS db, memory.collected_images AS col WHERE db.id=col.imgid AND LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '0001:01:01 00:00:00' ORDER BY db.datetime_taken DESC LIMIT 1"
11,943186 [sql] /home/johnny/darktable_repos/upstream/darktable/src/libs/duplicate.c:301, function _lib_duplicate_init_callback(): prepare "SELECT i.version, i.id, m.value FROM images AS i LEFT JOIN meta_data AS m ON m.id = i.id AND m.key = ?3 WHERE film_id = ?1 AND filename = ?2 ORDER BY i.version"
12,079664 [sql] /home/johnny/darktable_repos/upstream/darktable/src/libs/tools/timeline.c:742, function _block_get_at_zoom(): prepare "SELECT db.datetime_taken, col.imgid FROM main.images AS db LEFT JOIN memory.collected_images AS col ON db.id=col.imgid WHERE LENGTH(db.datetime_taken) = 19 AND db.datetime_taken > '2018:01:01 00:00:00' ORDER BY db.datetime_taken ASC"
12,086154 [lighttable] expose took 0,0000 sec
12,146942 [lighttable] expose took 0,0000 sec
15,136823 [lighttable] expose took 0,0000 sec
15,184980 [lighttable] expose took 0,0000 sec
16,944527 [lighttable] expose took 0,0000 sec
```

**Comment by GrahamByrnes** [comment]
Can confirm on W10 without the empty dir, but:
- fails as above from file manager view
- opens from culling view (image appears in DR, as usual)
- if you delete an image from culling view, the selection seems to be empty... can't bring up any of the images that are still present on the filmstrip
- if you apply a style in file manager, apparently nothing happens, but when you go to the culling view, you find that the style has been applied.

**Comment by johnny-bit** [comment]
Ping @AlicVB bacause - lighttable :grin:

**Comment by johnny-bit** [comment]
Wrong ping. Sorry @AlicVB !!! it's not lighttable issue!

pinging @elstoc !

I've bisected the problem and according to tests:
```
773393c98e0017992694244123c75b13d9f14175 is the first bad commit
commit 773393c98e0017992694244123c75b13d9f14175
Author: elstoc <elstoc@users.noreply.github.com>
Date:   Fri Mar 20 22:23:08 2020 +0000

    bugfix: remove extra duplicate version on import (#4393)

 src/common/image.c | 57 +++++++++++++++++++++++++++++++++++++++++++++++++++---
 src/common/image.h |  4 ++--
 2 files changed, 56 insertions(+), 5 deletions(-)
```
So the problem is caused by incorrect logic introduced in 773393c98e0017992694244123c75b13d9f14175

I need to check it.

**Comment by GrahamByrnes** [comment]
It seems to me that the conversion of dt_image_read_duplicates() to return an int is correct, and the checking for a returned null is correct.

So it must be in here, no?

//no sidecar files were loaded
    //the dummy record now represents v0
    DT_DEBUG_SQLITE3_PREPARE_V2
      (dt_database_get(darktable.db),
       "UPDATE main.images SET version = 0, max_version = 0 WHERE film_id = ?1 AND filename = ?2 AND version = -1",
       -1, &stmt, NULL);
    DT_DEBUG_SQLITE3_BIND_INT(stmt, 1, film_id);
    DT_DEBUG_SQLITE3_BIND_TEXT(stmt, 2, imgfname, -1, SQLITE_STATIC);
    sqlite3_step(stmt);
    sqlite3_finalize(stmt);
    
    id=0;

**Comment by elstoc** [comment]
Yes it's a regression of a bug I found during testing, that I reintroduced after code review.  However, there's another issue on importing folders that might be with the lighttable rewrite, so it might take a bit of investigation.

**Comment by GrahamByrnes** [comment]
Other than the one @TurboGit patched this morning at the top of collection.c ?

**Comment by elstoc** [comment]
Yes.

**Comment by GrahamByrnes** [comment]
There is this line in the definition of dt_control_signal_raise() (line 231 control/signal.c)

GValue *instance_and_params = calloc(1 + signal_description->n_params, sizeof(GValue));

Naive question: does passing id=0; risk screwing this up, since it still needs to save save the version_0 ?

**Comment by elstoc** [comment]
Ignore `id=0`. I'm fixing that.
