### ISSUE TITLE
[lighttable] slow when view=1 and runs crazy once you reach the end

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4518]
**Describe the bug**

In general I think lighttable filemanager view got slow in scrolling once you use zoom=1 even I used "generate-cache" recently.

More severe: if I reach the end of my collection, I get just a grey screen with "file on disk" for a short moment". See screenshot below.

When I use ctrl+mousewheel to change zoom factor, darktable fully crashes with attached "trace" (sorry I do compile with "Release" and I do have no gdb activated)

[dt.crash_20200321.log.zip](https://github.com/darktable-org/darktable/files/4363524/dt.crash_20200321.log.zip)

**To Reproduce**
1. Go to 'lighttable'
2. set 'zoom=1'
3. Scroll down to the end

**Expected behavior**

show last picture in row
do not crash if ctrl+mousewheel

**Screenshots**

![grafik](https://user-images.githubusercontent.com/49004103/77232670-bee87200-6ba2-11ea-8fd9-00f616d418e0.png)

**Platform (please complete the following information):**
 - Darktable Version: OS: [Gentoo Linux]
 - OpenCL activated yes and no, both effected
 - 2x nvidia GTX 160OC with nividia-drivers-440.59

**Additional context**

 - Can you reproduce with another Darktable version --> currently only 3.1 running on my system
 - Can you reproduce with a RAW or Jpeg or both? --> RAW only
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
    --> gcc-9.2.0 CFLAGS="-march=native -O3 -mtune=native -pipe"
-  Is the issue still present using an empty/new config-dir --> Yes

**Comment by jade-nl** [comment]
I can only partially recreate this behaviour.

1 Go to 'lighttable'
2 set 'zoom=1'
3 Scroll down to the end using the scrollbar (no problems yet)
4 Scroll back a bit using the mousewheel with pointer inside the image
5 Scroll to end again using mousewheel (pointer still inside the image area).
6 Window turn grey and seems to be locked for the the mousewheel. You can use the slider but all stays grey.
7 Double click on the folder being used in *collect images*: All is good again

So I cannot get it to crash but something strange is going on here.

* darktable version: Development 3.1.0+1000
* OS     : Linux - kernel 4.19.0-8-amd64
* Distro : Debian Buster (rel. 10.3)
* Processor : Intel(R) Core(TM) i7 CPU 950  @ 3.07GHz 4 Core(s)
* Memory : 12 GB (6 x 2048 MB) + 12 GB Swap
* Graphics card   : NVIDIA GF104 [GeForce GTX 460] (rev a1)
* Graphics driver : NVIDIA x86_64 Kernel Module 390.116
* OpenCL activated : No
* Xorg : 7.7+19
* GTK+ : 3.24.5-1

**Comment by AlicVB** [comment]
Confirmed. I'm on it. Thanks for the report

**Comment by AxelG-DE** [comment]
sorry for newbie question. 
I see commit 24c0a93. AFAIK that is not merged yet, right? How to see, when it is active? I am merely used to the PRs, where one can see the "merged"

**Comment by jade-nl** [comment]
This has been merged into master (between 3.1.0-1000 and 1005)

Rebuild and checked after I got the closed mail: It now works nicely on my side.

BTW:
* 09fdf5018 fix regression with importing single image
*   bf665f939 Merge pull request #4520 from AlicVB/fm2_glitchs    <---------
|\  
| * e5a08224f copy_history lib : fix copy parts button
| * 24c0a93a0 thumb : fix scroll down with zoom == 1       <-----------
| * d404a2524 filmstrip : refresh if scrollbars in darkroom
* | d930b4f7f Update CSS on @ AlicVB lighttable rewrite
|/  
* c250dda10 metadata update - add internal and optional metadata - add tooltips and fix some incoherences

**Comment by AxelG-DE** [comment]
TNX,
by the time I asked, it was still on +1000 hence not that , info in git log. I would have seen it there :)

I am at +1007 now and also confirm, no more grey screen and no more crash when I ctrl+mousewheel.

Only the speed issue remains...
