### ISSUE TITLE
Add Panasonic DC-GF9 noise profile

### ISSUE THREAD

**Issue by felberch** [darktable-org/darktable#4525]
For noise profiles, please also attach the entire archive with `.pdf` plots.

I was guided by the instructions here: https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/. 

I recognized that the darktable scenes the camera model name different than the noise profile generator. Darktable recognizes the camera as DC-GF9 while noise profile generator sees it as DC-GX800.
I renamed it in the preset.json tested it and replaced it in the attached tar.gz.

[darktable-noiseprofile-20200320.tar.gz](https://github.com/darktable-org/darktable/files/4364997/darktable-noiseprofile-20200320.tar.gz)

If it is more easy for you if i merge it directly to noiseprofiles.json let me know.

Thy
Christian

**Comment by rawfiner** [comment]
Thanks for the noise profile and sorry for the long delay!
