### ISSUE TITLE
Darktable does not properly filter similar camera models

### ISSUE THREAD

**Issue by twchambers** [darktable-org/darktable#4527]
I shoot with both a Canon 7D mki and mkii.
When I try to filter my images by camera, this does not work as expected.
Selecting "Canon EOS 7D Mark II" in the filter menu filters the images from this camera as expected.
Selecting "Canon EOS 7D" shows all imaged from **both** the 7D and 7Dii.

I am using darktable 3.0.1 on Fedora 31.
The bug has been present in all darktable versions as far as I am aware; at least 1 year ago when I reported this issue on redmine: https://redmine.darktable.org/issues/12556

**Comment by twchambers** [comment]
Issue is still present in 3.0.2

**Comment by twchambers** [comment]
Issue is still present in 3.2.1

**Comment by ptilopteri** [comment]
have you tried adding a second parameter
  sort for Canon EOS 7D 
  exclude Canon EOS 7D Mark II

seems search would be somewhat difficult otherwise since string "Canon EOS 7D" appears in both names.

**Comment by twchambers** [comment]
I have, though I find needing to do so counter intuitive.
The "collector" recognises them as two different cameras from the exif data, and if I wanted to see results from both of them, then I would use the wildcard operator.
I know it isn't an exact parallel, but to me, it would be like filtering images taken at ISO 1000 and getting images that are ISO 100 too.
