### ISSUE TITLE
"Plain paper" message shown at startup

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#4528]
**Describe the bug**
At startup (not always but very often) I have the log message "Plain paper" shown on screen.
I think that it's related to my recent changes in log drawing.

But to debug and fix, I need to find where that log message comes from, and I didn't manage... I though of `print.c` but I didn't find anything useful...
If someone know which `dt_control_log` call can display this msg, I would be grateful...

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: xubuntu 19.10
 - OpenCL both

**Comment by Nilvus** [comment]
Will not help probably but yes I've just seen that on a darktable startup (in light view). In french, it's translated ('Papier ordinaire'. I've just search 2 times (on github file and with poedit) and can't find 'Papier ordinaire' or even the only word 'ordinaire' on fr.po file.

So, could it be from an external library? Gtk one?

**Comment by AlicVB** [comment]
Same as you, unsuccessful search...
In fact I think the message may come from be cups or whatever. But even in that case it has to be shown by `dt_control_log`, and I've not seen a place in `print.c` where we show a message without some prefix or suffix...

**Comment by elstoc** [comment]
If it's an option in a combobox it's probably caused by #4468, which adds a toast whenever a combobox setting is changed via `dt_bauhaus_combobox_set`. We're gonna be chasing these down for a while I suspect. The solution will be similar to that in #4507.

**Comment by elstoc** [comment]
I can't reproduce myself (I don't print from darktable) but I'd say a good candidate would be line 518 of `libs/print_settings.c`.

**Comment by jenshannoschwalm** [comment]
here it prints (null)

**Comment by jenshannoschwalm** [comment]
Indeed it's the printer telling about the media found in dt printer options.
For cups-pdf this is null, otherwise what#s been selected.

**Comment by AlicVB** [comment]
oh... you means its not my fault ? quite unusual this times ;)
Anyway, I'll have a look, I didn't think of automatic combobox msg...

**Comment by elstoc** [comment]
@AlicVB: There's another one that appears when you change the display profiles in the lighttable but I can't pin down where it's coming from - none of the calls to `dt_bauhaus_combobox_set` in `views/lighttable.c` seem to be causing it (or at least the fix from #4507 isn't disabling the toast). If you have any suggestions I'd be grateful.

**Comment by elstoc** [comment]
@dterrahe, @TurboGit. Is there any reason we couldn't introduce a new function in `bauhaus.c` for the keyboard shortcuts to use, say `dt_bauhaus_combobox_set_notify`, that calls `dt_bauhaus_combobox_set` and then pops up the toast? It feels like chasing down all these popup messages is going to take an age. I've just seen another one when changing masking mode.

**Comment by houz** [comment]
I reverted the commit that put the message into bauhaus. That doesn't belong there. See 8e9f682252ab56a705eceaca17f21bf5bd3b7eb7

**Comment by elstoc** [comment]
Fine with me. Thanks @houz.

**Comment by Nilvus** [comment]
So this issue could be closed @AlicVB

**Comment by AlicVB** [comment]
closing, thanks
