### ISSUE TITLE
Zoomable lighttable misses the plot...

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4529]
Selection in clone & file manager seems to be much better now!

However, there is maybe a new issue:
If i select the last image in a short-ish film role then swith to zoom, it appears partly off the side of the viewing area. Zooming out makes it disappear completely, as though the zoom centre was placed one screen to right of the one I'm looking at.

If I select the first image, it seems to work ok (I guess, I haven't much used zoom view in the past).

dt3.1.0 1014, Windows 10

**Comment by Nilvus** [comment]
Can't reproduce this on commit 62144b042ed974f4f4c58a4e2c1874037a9b989a, if I correctly understand your issue.
Could you precise which commit you precisely have ? Some number after a g letter on darktable about. You precise 1014 but as I know we don't have 1014 commits since 3.0.0 as I know. I use a quite recent commit (the second-to-last one) and I only have 1007. So by now, if I'm not wrong, we are 1008 commits (not 1014).

**Comment by GrahamByrnes** [comment]
Last commit I have is  https://github.com/darktable-org/darktable/commit/09fdf5018c717077d794908b030dca14198e300b

(Sorry, that was inelegant, I need to get on top of pasting links).
The version number may not be helpful because I have some foreign code, so again sorry if that is a distraction... but it was new behavior after the merges from Alice and from Elstoc this morning.

I had already tested Elstoc's commit in advance last night, so the change in behaviour happened with Alice's commit this morning.

**Comment by Nilvus** [comment]
You mean @AlicVB (better than Alice and good to ping him so) but maybe precise more the issue and/or posting a screen capture could help. I've tried again and can't reproduce. I suppose you mean selecting last image on lighttable view (filemanager mode) with a filmroll of some images, then zoom on this last image? And then you have an issue?

**Comment by GrahamByrnes** [comment]
Ok, here we go :-)

Start with first image selected in culling, all is well
![March22scr1](https://user-images.githubusercontent.com/58031430/77253121-b6eb0980-6c58-11ea-9a17-5d63169628fa.jpg)

Then go to zoom, kind of strange:
![March22scr2](https://user-images.githubusercontent.com/58031430/77253150-d6823200-6c58-11ea-9ba6-85bab01231ae.jpg)

Now try last image, in culling:
![March22scr3](https://user-images.githubusercontent.com/58031430/77253207-1e08be00-6c59-11ea-917b-da946056831d.jpg)

And zoom:
![March22scr4](https://user-images.githubusercontent.com/58031430/77253275-4395c780-6c59-11ea-8a06-17b41bfcfb8e.jpg)

Not so strange this time, it doesn't seem completely reproducible. Here we go back to culling, look what has happened in the filmstrip:
![March22scr5](https://user-images.githubusercontent.com/58031430/77253306-7fc92800-6c59-11ea-9f00-625a39d91b0e.jpg)

Fiddle about some more, back to zoom:
![March22scr6](https://user-images.githubusercontent.com/58031430/77253319-9a9b9c80-6c59-11ea-93a0-170e119fa0df.jpg)

Back to culling, and the filmstrip has disappeared:
![March22scr7](https://user-images.githubusercontent.com/58031430/77253341-bd2db580-6c59-11ea-9f40-50411d40c9aa.jpg)

Back into zoom, use it to zoom out, image disappears and won't return...
![March22scr8](https://user-images.githubusercontent.com/58031430/77253353-d7679380-6c59-11ea-9f8f-a1af65d2316c.jpg)

**Comment by GrahamByrnes** [comment]
Oh, this one impressed me! Note that I could always reset everything by going back to the darkroom.
![March22scr9](https://user-images.githubusercontent.com/58031430/77253458-b05d9180-6c5a-11ea-86e6-e20805b11d2a.jpg)

**Comment by Nilvus** [comment]
Better, thanks. That was really not was I had understood (but seems I read to quickly the tile...). Zoom is for me preview mode (with Alt+w), quite differen of zoomable mode. I've tried with some images and few times and really can't reproduce again. But zoomable mode is also a "movable film" mode. So having sometimes images not on the wanted place is maybe normal (you could move them and zoom on them with your mouse) but what you show seems strange (I don't use this mode). Anyway, culling mode has not be rewrited again by @AlicVB. It is on his todo list. Did you try on a clean master (so without your specific adds)?

I will let now someone else using this mode (or knowing the code) add more things if needing. About filmstrip,

**Comment by Nilvus** [comment]
Edit: after testing that and reset my views to what I use, I have had a similar issue. Last image of a filmroll was selecting on culling mode (on start 1 images only like you). I came back to two images (my habituel set) and when quitting culling mode with shortcut, it came back to last view (zoomable mode) and no image shown (nor scrollbar). In fact, images where just outside the view but need to change mode again (to filemanager) then come back to zoomable view and images were shown.

@AlicVB: this maybe means that reset position on zoomable mode miss?

**Comment by GrahamByrnes** [comment]
No, at the moment it's such a struggle to get a stable version that I don't want to start building standard modes alongside my user mode... on W10 it's about 90 minutes to build each :-O

So we'll see if others reproduce. The other changes I've been using for weeks, just waiting for my co-author to finish them... but I understand the need to be conservative.

**Comment by AlicVB** [comment]
@GrahamByrnes : seeing your screenshots (5-6-7-9), you seems to have a serious problem of refreshing... What surprise me is that it seems to happen in filmstrip and in zoomable...
As I can't reproduce the refreshing issue, can you test 2 things for me ?
- try changing scrollbars settings in pref. Does it change anything (to the refresh problem)
- try to launch dt with` -d lighttable` when you have refreshing problem, do you see the msg "reload thumbs from db." in the console ? if yes, can you copy-paste it her ?

Otherwise, there's an issue in zoomable if you hide all the images by zooming in/out with mouse scroll : if all images disappear from screen, there's no way to find them anymore (apart from exiting/reentering) I'll have a look

**Comment by GrahamByrnes** [comment]
Second thing first... here is a sequence of reload commands

[RefreshTerminalMars22.txt](https://github.com/darktable-org/darktable/files/4365811/RefreshTerminalMars22.txt)

**Comment by GrahamByrnes** [comment]
I switched to no scroll bars... nothing seemed to change. There was a loooong freez at one moment as I tried to switch back to zoom table, but it got there in the end. Another console entry in case it's useful:

104,401054 [exiv2 dt_exif_get_thumbnail] couldn't find thumbnail for C:\Users\Graham\Pictures\OldPhotos\Gamut_Test_File_Flat.tif106,193751 [exiv2 dt_exif_get_thumbnail] couldn't find thumbnail for C:\Users\Graham\Pictures\OldPhotos\Gamut_Test_File_Flat.tif125,946671 reload thumbs from db. force=1 w=1200 h=882 zoom=3 rows=3 size=400 offset=1 centering=0...
125,948665 done in 0,0020 sec 0 thumbs reloaded

**Comment by AlicVB** [comment]
You can have a look at PR #4550 
I'm not sure it fix all the issues you describe here, but at least some part of it.

**Comment by GrahamByrnes** [comment]
It seems #4550 and some earlier changes have fixed this. Thanks!
