### ISSUE TITLE
color picker not resizable

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#4531]
In dt with 64d5ee2d1b282aeee5adc4764adc20b847038029, the area color picker size cannot be changed/edited and stays as the default (whole image covered). Affects global picker, white balance and modules pickers (filmic, color balance, negadoctor). Reverting that commit solves the issue.

I'm on HiDPI screen with screen PPD = 2 and DPI set to default.

**Comment by jenshannoschwalm** [comment]
Ooh, shit happens. I missed that and will fix asap.

**Comment by aurelienpierre** [comment]
Thanks !
