### ISSUE TITLE
wrong basecurve and sharpening applied (perhaps related to #4089)

### ISSUE THREAD

**Issue by Macchiato17** [darktable-org/darktable#4535]
**Describe the bug**
When I freshly import a new RAW file created with a Nikon D7500, the "Nikon like" basecurve is auto applied instead of the "Nikon D7500" basecurve. Also the sharpen module is applied, even if this is set inactive in core options.

Core options settings:
[  ] auto-apply basecurve
[x] auto-apply per camera basecurve presets
[  ] auto-apply sharpen

Even if I disable all three options there, both the "Nikon like" basecurve and sharpen is applied to the freshly imported RAW (and I also did the application restart after changing any of those options). I also removed user-specific basecurve presets.

As another test, I defined a user-preset to apply the "Nikon D7500" basecurve for Nikon D7500. In the preset I entered 
"[x] auto-apply this preset to matching images" and 
"[x] only show this preset for matching images", as well as 
"model=D7500", 
"maker=Nikon", 
"lens=%"
but also after creating this user-preset (I also did an application restart after that) darktable didn't manage to apply the right basecurve.

**To Reproduce**
    remove all darktable entities in the side-car xmp files of the RAW file
    start darktable
    open a new RAW image in darkroom view -> basecurve and sharpen is applied
    remove the imported picture again, quit darktable, restore the xmp file again
    restart darktable -> same problem again

**Expected behavior**
Apply the correct basecurve to the RAW.

**Platform**
    OS: Windows 10 professional x64
    Version: 3.0.1

**Comment by jenshannoschwalm** [comment]
Should be fixed in master now.

**Comment by Macchiato17** [comment]
Looks better now. Still the included basecurve NIKON D7500 is not automatically applied in my case. Perhaps due to case-sensitivity or differences in the EXIF meta data. But when I create a copy of the profile and change the make / model settings as described before, auto-apply now works fine for this profile => solved from my point of view.
