### ISSUE TITLE
Misbehavior of FilmStrip rating in darkroom with viewing filter to a certain number of stars 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4539]
**Describe the bug**
Need to fine tune clicking of stars on filmstrip so that it detects its for stars and does not display the image in the main view.
Also it needs to honor the view filter for images.

**To Reproduce**

1. Rate some of your images to say 2 stars from any view.
2. Change filter view to display only with 2 star ratings in darkroom.
3. Now in filmstrip say you are at image 3 and its active and displayed in the main window.
4. Scroll to another image and click stars on it and change it to 1 star.
5. Due to the click the image gets displayed but disappears from the filmstrip as the filter is set to view only 2 star images. 

**Platform (please complete the following information):**
 - Darktable Version:darktable-3.1.0+1026~g42e13e52b-win64
 - OS: WIN 10

**Comment by chhil** [comment]
Workaround is to hover over a pic and use the keyboard to change rating.

**Comment by TurboGit** [comment]
Indeed, in this scenario we need to display another image. Questions:
- what was done in 3.0 ?
- what is happening when there is no more images (all set to 1 star) given the filter ?

**Comment by chhil** [comment]
3.0 had the double click on filmstrip to display and single click on ratings' area on a specific star to change ratings so the behavior was defined for the clicks, now on single click there are 2 behaviors.

**Comment by AlicVB** [comment]
confirmed. rating with mouse shouldn't change the active image.
I'll have a look asap

**Comment by AlicVB** [comment]
should be fixed in PR #4547
