### ISSUE TITLE
lighttable zoomed view while moving among photos

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#4541]
Github port of Redmine darktable ticket: https://redmine.darktable.org/issues/12593

As every darktable user knows, lighttable is a powerful tool to select best photos, especially when you shoot burst of photos.
By the way I would like to propose an improvement.
There are very often burst of photos that changes only for a very little detail, so to quickly classify them and choose the better photo, you should be able to comfortable see that little detail zoomed.
So it could be very useful to have a zoomed view in lighttable: I mean, you should be able to **keep** a zoomed view of a **portion** of the image, while moving between different shoots, so you can appreciate the difference between them.

An example of use case is: in shoots that contains people, someone could have a bad facial expression in one shoot (eyes almost closed), but in next photos his expression could be better. Actually to be able to zoom the detail of photos you must everytime switch to darkroom, action that is slower because the machine renders the photo at full details. The same if you move among photos while in darkroom mode.

**Comment by TurboGit** [comment]
You already have this with the culling view. Looks like you've completely missed that :)

**Comment by Germano0** [comment]
Ouch, let me check!

**Comment by Germano0** [comment]
Excellent work guys, I close this ticket
