### ISSUE TITLE
Introduce toggle to turn off stars rating in filmstrip preview (darkroom)

### ISSUE THREAD

**Issue by david-we** [darktable-org/darktable#4545]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i click on a image in filmstrip and suddenly the image is gone.The reason is that i accidentally hit the star rating. for example 2 stars which is beyond my stars filter of 4 stars and the image disappears. Mode is Darkroom. 

**Describe the solution you'd like**
add a toggle in configuration where you can disable the rating by mouseclick. One could still rate the image by keyboard!

**Alternatives**
a toggle in cofiguration where you can switch off star preview in darkroom completely. 

**Additional context**
it is really really annoying when you recognize later that an image which you can still remember, is gone and then when you look it up in lighttable it has suddenly 0 stars. one can accidently delete great images with this behaviour... 

greetings from Austria, 
Dave

**Comment by johnny-bit** [comment]
does `ctrl+z` (undo) reverse the effect of rating?

also - which darktable version are you using?

**Comment by AlicVB** [comment]
I agree with you here. and even if I rarely "mis-click" I never change the rating with with mouse because of the precision required to click on the right star.

For me, the main question is if we should add a pref for that or just make the stars readonly in filmstrip ?
And if we add a pref entry what should be the default behavior ?

Let's see what other think about that...

**Comment by johnny-bit** [comment]
Ohhh it was for filmstrip! damn... I think then since filmstrip is usually _tiny_ the overlay should be readonly (with tooltips being possible)

**Comment by Nilvus** [comment]
We should be careful to not have too many settings. I also think readonly mode on filmstrip is the better choice. But only readonly for mouse actions. Setting stars with shortcut on filmstrip could remains available.

**Comment by david-we** [comment]
> does `ctrl+z` (undo) reverse the effect of rating?
no 
> also - which darktable version are you using?
3.1.0~git759.bf2f465ac

i think readonly and rating with the keyboard would be a good solution. I understand the point that too many settings is also a problem.

**Comment by AlicVB** [comment]
OK, considering the relatively small or straightforward amount of change, I've implemented it with an hidden pref (not present in pref dialog, but still editable in darktablerc)
See PR #4549

**Comment by bschwehn** [comment]
FWIW, fixing the undo in darkroom mode might be as simple as changing line 38 in undo.h from

DT_UNDO_DEVELOP = DT_UNDO_HISTORY | DT_UNDO_MASK | DT_UNDO_TAGS,

to

DT_UNDO_DEVELOP = DT_UNDO_RATINGS | DT_UNDO_HISTORY | DT_UNDO_MASK | DT_UNDO_TAGS,

Works as far as I can tell, but I don't know the code well enough to understand if that may cause some unintended side effects
