### ISSUE TITLE
Crashes on folder import containing a corrupted cr2 file

### ISSUE THREAD

**Issue by angryziber** [darktable-org/darktable#4546]
**Describe the bug**
Import folder, choose it, start import - crash in a few seconds.

**Expected behavior**
No crash, new images appear

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1
 - OS: Ubuntu 19.10
 - Intel video hw

Attaching backtrace file

**Comment by angryziber** [comment]
[darktable_bt_TSF3H0.txt](https://github.com/darktable-org/darktable/files/4377368/darktable_bt_TSF3H0.txt)

**Comment by angryziber** [comment]
Trying copying files out of the folder and found a possibly corrupted file that causes the crash.
My expectation would be that darktable would report an error with the file instead of crashing.

Here is one of such files:
https://stash.codeborne.com/corrupted.cr2

**Comment by Nilvus** [comment]
It's quite difficult to recognize a corrupted file (many parts could be corrupted) so I doubt it's possible to do for all type of corrupted files. Anyway, if you want to ask that, it would be easier to close that issue and create more a feature request to ask if adding an error report when corrupted file is possible or not. You could point to that issue and links on this one (or modify title and description here).

**Comment by angryziber** [comment]
Dcraw reports that file cannot be parsed and exits without crashing... Is
crashing a problem of rawspeed? The issue is it's really hard to find the
problematic file if you have a full folder that you cannot import. I did
find these files by processing all of them using dcraw once I understood
that it's a problem with files at all... It's not obvious

**Comment by parafin** [comment]
Crash seems to be in libjpeg, not in rawspeed.
