### ISSUE TITLE
[Feature] Lighttable : make the Collect module resizable

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4551]
** Context **
I have a 27" 4k monitor
In _lighttable_, the only module I really use it the _Collect images_ one.

I use it with 4 filter boxes, that I display all the time.
I only browse in my collection with the Folders filter, which is the one I use most.

** Problem **
The screen estate available for the _Collect images_ module is way too small.
It can only display 7.5 lines for the lower part, which is the one showing my folder tree.
And below it are thousands of pixel rows, unusable for anything I'd use.

** Requirement**
Make the box used for the filter browsing and selection resizable so that it can be used to display much more information (in my case many more line of my folder tree)

If technically it is not possible, then just make it bigger

![image](https://user-images.githubusercontent.com/3989573/77573760-71854100-6ed1-11ea-9272-592db104528f.png)

Would anyone use this ?

Thanks
GLLM

I have not found any similar issue.

**Comment by AlicVB** [comment]
I remember to have seen something like that recently...
after a search in PRs, I confirm that in master, you can use ctrl+scroll to change the size of the collect module :)

**Comment by GLLM** [comment]
Ouch !  Sorry for the unnecessary noise !
I have to admit that the number of my own FR or issues closed by you @AlicVB are skyrocketing ... 
Sorry for that :-(

It's indeed working on 3.1.0~git1031.8e4d22171 ...
