### ISSUE TITLE
Application of a Style is not clearcut

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#4556]
I would expect applying a style would be well-defined in terms of what it does to the image but it seems to depend on what modules you have just been using.

The manual says a style is about "storing a history stack as a style, and applying it to other images".

**To Reproduce**
Have a style and check what it contains.
Edit an image and use a module not in the style.
In Lightable, apply the style to the image.
Go back into Darktable and note the module you just used is now applied to the image.

**Expected behaviour**
When you apply a style, nothing outside of the style contents should be applied.

**Screenshots**
![Screenshot from 2020-03-26 12-42-56](https://user-images.githubusercontent.com/16868433/77648047-67aa1f00-6f5f-11ea-9b91-db2215ea0acb.png)
I found Perspective was applied to my image even though it is not part of my style as the above image shows.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1+dirty
 - OS: Ubuntu 18.04
 -  none

**Comment by elstoc** [comment]
I assume that the perspective correction module had already been applied to the image before you selected the style?

If that's the case then it sounds like what you want is a 'mode' drop-down like in the history stack module, so you can choose to either append or overwrite the history stack of the target image. 

Seems like a good idea. In the meantime a workaround would be to compress history stack before applying the style.

**Comment by RawConvert** [comment]
Re. "what you want is a 'mode' drop-down like in the history stack module, so you can choose to either append or overwrite the history stack of the target image"

For myself I'd be happy if it applied the style and switched off any modules not covered by the style.  Some might want to choose between append/overwrite.  I guess the bottom line is it needs to be clearly defined.

**Comment by elstoc** [comment]
Sorry yes I was combining 'what you want' with maintaining existing functionality, which others might prefer.

**Comment by MStraeten** [comment]
If you want to apply just a style then you can drop history first. Then only the modules in the style are applied to the image.
But a lot of styles are used as optional add on, for example the T3MUJINPACK film styles. It simply doesn’t make sense to drop history as a standard when applying a style because there isnt a way to reconstruct the former applied modules.

**Comment by RawConvert** [comment]
Ok, perhaps the manual could be updated to point out that the style is "additive"

**Comment by elstoc** [comment]
I still think it might be a good idea as long as it's optional as with the history stack module.

**Comment by RawConvert** [comment]
Perhaps I'm misunderstanding, but what happens if your style says Exposure=0.5 but your stack already has Exposure enabled at 1.0, which one wins?

**Comment by elstoc** [comment]
AFAIK the style just adds things to the top of your history stack so if you added the style after setting the exposure, the style wins, because it's higher in the stack. Same as with pasting using the history stack module in append mode.

**Comment by ptilopteri** [comment]
wouldn't one expect them to be additive rather than overwriting?
a style containing exposure +0.5 applied *after* increasing exposure +0.2 should result in an exposure of +0.7

or the style should have been applied before other edits.

styles should have consistency

**Comment by elstoc** [comment]
Easily said for the exposure module. How do you 'add' with, for example, Crop & Rotate?

**Comment by ptilopteri** [comment]
last instance has to win 

logic dictates result is that of least supprise

**Comment by MStraeten** [comment]
You can name the instance of a module when defining styles, then these are applied as additional instances. Since the style can contain masks a simple combining the values of a module might not be sufficient

**Comment by RawConvert** [comment]
> style just adds things to the top of your history stack
This is well-defined and easy to understand, so good.  Just did a very quick test and it does indeed seem to be what happens.

So as far as I'm concerned, the only outstanding action is to update the dt manual, I think it should say the style is added to the top of the stack.

Naming module instances in a style sounds quite sophisticated, presumably this should be added to the manual also, no point in having features in dt if they're almost invisible!  (Had a quick look at "edit" function, can't see anything about naming instances)

**Comment by RawConvert** [comment]
I messed up the quote above and my comment is in grey.

**Comment by RawConvert** [comment]
And I meant to say, how is it recorded that the manual needs updating, won't get forgotten etc?

**Comment by elstoc** [comment]
Hopefully once the transition to markdown is complete, it should be easier to submit updates to the manual, then you can submit a pull request.

**Comment by MStraeten** [comment]
from the manual:
https://darktable.gitlab.io/doc/en/multiple_instances.html last two sentences decribes naming
and https://darktable.gitlab.io/doc/en/history_stack.html section "mode" describes the handling of multiple instances during copy/paste

**Comment by RawConvert** [comment]
Thanks @MStraeten , that's helpful.
