### ISSUE TITLE
Changing selected module subset also changes active module group

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#4570]
Say I select a module group and find it does not contain the module I am looking for in the currently selected subset. I would then select another subset, behind "more modules". Now the module group has switched away from where I was so I have to select the group I was looking at again.

1. In darkroom, bottom right, behind "more modules" in the dropdown select "subset: default modules"
2. Select the "effects group" (top right)
3. The list of active modules is empty
4. Select "more modules"/"subset: all modules"
5. Notice that the group has now switched to "tone group"
6. Click on "effects group" again
7. Now I can see the modules I was looking for.

Step 6. should not be needed.

@GrahamByrnes Apologies for not mentioning versions. This is on:
3.0.1/Windows 10
Current (2020/03/30) master 3.1.0-11b0691/Debian
Another recent master on Windows 10

**Comment by GrahamByrnes** [comment]
Hi,
It would help if you could specify the version of dt you are using, and the OS details.
There has been recent work on this.
Cheers,
Graham
