### ISSUE TITLE
Unable to open Darktable on Windows after install

### ISSUE THREAD

**Issue by michaelg94** [darktable-org/darktable#4573]
Hi, I have tried to install Darktable on Windows 10 but after I install I am unable to open up the program. Instead I get an error message and am pointed towards the backtrace attached. Please can someone help? I have tried downloading again but get the same problem. Thank you!
[darktable_bt_TGGFI0.txt](https://github.com/darktable-org/darktable/files/4403572/darktable_bt_TGGFI0.txt)

**Comment by Nilvus** [comment]
Seems to be related to OpenCL and AMD graphics cards you should have as it refers to amdocl64.dll. So check your graphics driver and update it if new driver is available.

Even if darktable is better with OpenCL, just try to launch darktable by adding --disable-opencl flag (you add it just after the launch program line by right-clicking on the icon then properties.

**Comment by michaelg94** [comment]
Many thanks for your quick response. I have updated the graphics card driver and it now appears to be working. Thanks again.

**Comment by Nilvus** [comment]
So, think of closing this issue to help developers see which remains to work on.
