### ISSUE TITLE
Minor issue : code cleanup probably since removing of flickr, facebook, google... export options

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4574]
**Describe the bug**
Just a minor issue and maybe some code cleanup. I've just compiled last master and see that libflickcurl library is still searched by building script. Maybe some cleanup needs to be done on building script and probably for other removed solutions, like Facebook and Google Photos...

See line on the beginning of compiling darktable (on Linux here):
```
Could NOT find FLICKCURL (missing: FLICKCURL_LIBRARY FLICKCURL_INCLUDE_DIR) 
CMake Warning at cmake/modules/LibFindMacros.cmake:263 (message):
  WARNING: MISSING PACKAGE
```

**Comment by TurboGit** [comment]
Thanks! Should be fixed now.
