### ISSUE TITLE
Olympus E-M5 Mark 3 noise profile

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#4582]
I'm attaching noise profile generated by Pixls.us user Florian Prestel in this thread:
https://discuss.pixls.us/t/darktable-support-for-olympus-e-m5-miii/17188/

[darktable-noiseprofile-20200330.tar.gz](https://github.com/darktable-org/darktable/files/4408212/darktable-noiseprofile-20200330.tar.gz)

//EDIT: it seems that we already have profile, but not integrated: #4481

**Comment by rawfiner** [comment]
Thank you for the noise profile, sorry about the delay!
I kept olupton's profile, as it is more complete (all the intermediate and extended ISO)

**Comment by johnny-bit** [comment]
Good :) I can close this issue then :)
solved via #5142
