### ISSUE TITLE
Base curve removed after jpg export

### ISSUE THREAD

**Issue by Grizzly1701** [darktable-org/darktable#4583]
**Describe the bug**
Darktable removes the base curve after I exported a jpg of the .NEF file. It removes the base curve from the xmp file. If I export  a file I use for example "nikon alternative".  The picture (jpg) looks also like it has this base curve. If I then  reopen the folder in darktable (for example if I reopen it after I  edited another collection) and go on a RAW file in darktable it doesn't  show the base curve in the history anymore and the picture looks grey  and flat (because there's no base curve anymore).

**To Reproduce**
1. Open Folder with RAW files
2. Select a RAW file and delete history in "lighttable"
3. Export it as jpg (maybe works with other file formats too)
4. Reload the folder by clicking folder in the import section and choosing the folder in the popup 
5. Double click on the RAW file in lighttable to get into darkroom
--> Base curve is not in the history anymore, image seems flat, base curve module shows no base curve anymore

**Expected behavior**
Base curve is still applied after reopening the folder in darktable and going into darkroom

**Screenshots**
Before exporting (it uses the base curve that I set as preset):
 https://ibb.co/H2hkYLL
Right after exporting the jpg and reopening the folder with darktable, going into darkroom: base curve is not there anymore:
 https://ibb.co/WcxTd7M

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1
 - OS: Windows 10 
GTX 1070 

**Additional context**
It does not happen in following cases:
If I add the base curve manually in the darkroom with the module (and not by clicking "discard history" in lighttable")
If I go into darkroom again (doubleclicking on the .NEF file) before reloading the folder in darktable

**Comment by TurboGit** [comment]
Looks like it is expected. You export without dev history. The xmp is created without any history and so when you reload the basecurve is not present. I see nothing wrong.

**Comment by Grizzly1701** [comment]
Wrong. If I delete the history it deletes every step that I made on my own. But the base curve is something that darktable applies on its own and should be still there after an export. This is clearly a bug.

**Comment by Grizzly1701** [comment]
Pls reopen the issue.

**Comment by Nilvus** [comment]
> Wrong. If I delete the history it deletes every step that I made on my own. But the base curve is something that darktable applies on its own and should be still there after an export as it is also there before export after deleting the history. This is clearly a bug.

It's not anymore. You could even disable permanently base curve (filmic RVB replaced it for most users now) and even sharpen on preferences dialog. So that's why on XMP, we can't now consider base curve as a default module, even if on default start, base curve is automatically applied. It's no more considered as a default module like, for example, black and white point or white balance.

**Comment by Grizzly1701** [comment]
Sure, you can disable it or enable it. The point I tried to explain is it suddenly disappears after a jpg export. This makes no sense. Why would darktable apply it (because I set it as a preset or it was set as a preset by default in darktable) when importing a folder but then remove it after you exported it?

**Comment by Nilvus** [comment]
So maybe share on your new issue a RAW/XMP with that problem could help. I don't know but even when reading your new issue, I find your issue not clear. For example, why reimporting an already existing folder?
I can test with a RAW/XMP with base curve provided but no more as I don't use anymore base curve now as I find filmic RVB really more powerful and have better rendering with that module than base curve now.

**Comment by Grizzly1701** [comment]
Ok sure. Thx for trying to understand my problem! 
For answering your question of reimporting: If I edit something of an other folder and then want to go back to my first folder I need to reopen it in darktable. Or how am I able to open the folder otherwise?

**Comment by Nilvus** [comment]
> Ok sure. Thx for trying to understand my problem!
> For answering your question of reimporting: If I edit something of an other folder and then want to go back to my first folder I need to reopen it in darktable. Or how am I able to open the folder otherwise?

The real problem is here. Importing a folder create lines on database to link to the folder. You then use collections on lighttable to select which folder, filmroll or whatever is on the menu filter of this module to select your images. I suggest you to check the manual on how using lighttable and filter collections. Manual is available on darktable.org.
