### ISSUE TITLE
Base Curve gets removed after export

### ISSUE THREAD

**Issue by Grizzly1701** [darktable-org/darktable#4586]
**Describe the bug**
Darktable removes the base curve (that is automatically added by default when importing a folder) after exporting an unedited RAW file.

**To Reproduce**
1. Open Folder with RAW files (darktable automatically adds 8 steps, including base curve)
3. Export it as jpg (maybe works with other file formats too)
4. Reload the folder by clicking folder in the import section and choosing the folder in the popup
5. Double click on the RAW file in lighttable to get into darkroom
    --> Base curve is not in the history anymore, image seems flat, base curve module shows no base curve anymore (only 7 steps in history)

**Expected behavior**
Base curve is still applied after reopening the folder in darktable and going into darkroom

**Screenshots**
Before exporting (it uses the base curve that is automatically applied if you import a folder with RAW files):
https://ibb.co/H2hkYLL
Right after exporting the jpg and reopening the folder with darktable, going into darkroom: base curve is not there anymore:
https://ibb.co/WcxTd7M

**Platform (please complete the following information):**

    Darktable Version: 3.0.1
    OS: Windows 10
    GTX 1070

Additional context
It does not happen in following cases:
If I add the base curve manually (for example if I change something from the default setting in the basecurve module).
If I go into darkroom again (doubleclicking on the .NEF file) before reloading the folder in darktable.

**Attachements**

[DSC_0510_Before_Export.zip](https://github.com/darktable-org/darktable/files/4414221/DSC_0510_Before_Export.zip)
I had to delete the .NEF file in the second zip because it was too big for github (you need to copy the .NEF file from the zip above into the folder of the second zip to be able to open it in darktable)
[DSC_0510_After_Export.zip](https://github.com/darktable-org/darktable/files/4414266/DSC_0510_After_Export.zip)

**Comment by Nilvus** [comment]
As said, it's not a bug but a normal behavior. Base curve use as changed. I copy here my answer on your first duplicate issue about this here:

> But the base curve is something that darktable applies on its own and should be still there after an export as it is also there before export after deleting the history. 

It's not anymore. You could even disable permanently base curve (filmic RVB replaced it for most users now) and even sharpen on preferences dialog. So that's why on XMP, we can't now consider base curve as a default module, even if on default start, base curve is automatically applied. It's no more considered as a default module like, for example, black and white point or white balance.

You could check article release to describe changes on darktable 3.0 here: https://www.darktable.org/2019/12/darktable-30/

**Comment by Nilvus** [comment]
Just tried 3 times (one with base curve automatically applied by activating it on preferences dialog) and really can't reproduce. On what you answer on your first issue, I begin to really think you don't use correctly import options and lighttable. And so, I see no real issue (that darktable team can solve on code) here.

**Comment by Grizzly1701** [comment]
As mentioned it only works if it's applied automatically and you don't open the .NEF file in mode "darkroom" after exporting before reopening the folder. 
What do you mean by correct import options?

**Comment by Nilvus** [comment]
I never said correct import options, I said that you probably don't use them correctly. Once images are imported, there's no more need to import them again. You just have to search them on lighttable with filter collections.
And as I've said, I've tried with base curve automatically applied. Sorry but I can't do more here.

**Comment by jenshannoschwalm** [comment]
Of course reimporting is **not** what you should do :-)

I think this may in fact be the same problem as described in #4089. I will dig deeper and **if** there is a problem will do a pr.

**Comment by Grizzly1701** [comment]
@Nilvus ok got this wrong. So I just reload them with the tool "collect images"(?) 

Still it's a bug because if I import a folder the second time when I edited the RAWs manually it has still the same history as left before closing the folder. Same goes for the case of not exporting any picture: it remains applied. Why should it then behave differently when no modules are manually applied?
There's no good reason to delete the history (and change the order of "gamma", "orientation" etc. as you can see on the pictures I uploaded) after reimporting.

@jenshannoschwalm seems like it is similar to this yes!

**Comment by ptilopteri** [comment]
@Grizzly1701 Instead of importing the image(s) again, try setting dt to "look for updated xmp files on startup" and write the updated xmp files to the database.

**Comment by ptilopteri** [comment]
@Grizzly1701 the option is in the config, "core options" -> xmp

**Comment by Grizzly1701** [comment]
Here's a video of the bug as you couldn't recreate it @Nilvus : https://youtu.be/GFaFrRnF9lQ

**Comment by jenshannoschwalm** [comment]
Thanks for the video, it took some watchings to get what you really do and after that could reproduce. I understand what's going on -- hold on for the pr.

**Comment by jenshannoschwalm** [comment]
I think this is fixed in current master now. Please close issue or report ...

**Comment by Grizzly1701** [comment]
@jenshannoschwalm I'm not used to Github at all so I will just trust you and close this issue as my goal to get the developers to see my problem is achieved :) 

I assume that the change will come to a "normal" update one day isn't it?

**Comment by jenshannoschwalm** [comment]
I am not sure about this stuff coming soon into 3.0.2, @TurboGit keeps integrating what he thinks is right. It will be in 3.2 for sure, maybe you should find a way to use the current master branch on windows too. Keep going :-)

**Comment by Grizzly1701** [comment]
Maybe I should then :) have to look for tutorials then haha 

Thanks for all the help!
