### ISSUE TITLE
Move User Manual into its own repository

### ISSUE THREAD

**Issue by paperdigits** [darktable-org/darktable#4588]
We should move the user manual into its own repository so that others can be given commit access, hopefully boosting contributions to the user manual. The original idea is from @houz 

I'd be happy to be the point man on this repo.

**Comment by TurboGit** [comment]
I don't agree with that. It mean more work for more people. We need to tag and create branches in another repo for each release. And in any project I have worked on, if the documentation is not with the main project it gets slowly forgotten and get less attention.

**Comment by Nilvus** [comment]
I agree with @TurboGit especially on last sentence: "if the documentation is not with the main projet, it gets slowly forgotten and get less attention." Just see the website: it's especially @TurboGit who update the site when a new darktable is release. Many people think of this main repository but not others. And main repository of course doesn't give commit access but it remains possible to propose pull requests. I only work on CSS parts (and had contribute a little on manual, especially french translation) and as it's few commits, pull requests are ok, it also let other people correct and help improving manual parts proposed.

**Comment by Nilvus** [comment]
This is more needed to help on making translation easier and faster: #4177

**Comment by parafin** [comment]
While I agree, that splitting documentation generally tend to cause it to be forgotten, but in darktable's case it lags behind already, so this argument IMHO doesn't hold well here. To me creating a new repository looks like a good idea to try. You can always merge documentation back into the main one.

**Comment by TurboGit** [comment]
Well people not cloning current repository to update the documentation won't clone another one just because that's another one. I don't see the point. As @Nilvus as stated, the best option currently is to see #4177 come to reality.

**Comment by paperdigits** [comment]
I'm working on #4177 already; it is a tremendous amount of work. First part of it should be done this week.

**Comment by houz** [comment]
Here is how I see it: having the manual in its own repo has the benefit that the barrier to actually build it and thus contribute is reduced. currently you need a fully working dev environment to compile dt just to be able to build the manual. That is insane. And the manual is ignored by many devs anyway, no matter in what repo it lives. Also, in general we don't release the manual together with the sources, but it takes quite some extra time until it is updated. That leads to the situation that we tag a state as released that is not really the final manual. 
Having a usermanual repo also allows to give out commit rights more freely.
So I see no point in having the manual inside the main repo but several advantages of having it separated.

**Comment by TurboGit** [comment]
I still don't agree. I do care about the documentation, when I see documentation PR I ask some native people that have proposed to do proofreading to review. This is because when I'm on the GitHub repo I do see the PR, I certainly won't like having to have another GitHub page open to check if PR are there and comment if necessary.

**Comment by paperdigits** [comment]
But you don't have to be the only one reviewing and merging...

**Comment by TurboGit** [comment]
Sure, if you mean no one will look at the PR fine! :)

I do want to look at them, as I currently drive the project I find very important to keep in touch with the documentation work. And I suppose this is true for all Devs.

**Comment by paperdigits** [comment]
> Sure, if you mean no one will look at the PR fine! :)

I said this in the original post on this thread:
> I'd be happy to be the point man on this repo.

**Comment by paperdigits** [comment]
Seems like there is no interest in this.
