### ISSUE TITLE
Sony Alpha 6100 (ILCE 6100)

### ISSUE THREAD

**Issue by laugmanuel** [darktable-org/darktable#4589]
I've uploaded a RAW sample of the Sony Alpha 6100 to RPU.

The camera itself only supports compressed RAW (as far as I know) so there is only one sample uploaded. If you need more samples please let me know and I will shoot and upload some more.

**Comment by LebedevRI** [comment]
Thank you for contributing the sample!

**Comment by laugmanuel** [comment]
I was just wondering: do you need more samples with different aspect ratios, different exposure, ...?

**Comment by LebedevRI** [comment]
No, for Sony i think a single sample is all we need.

**Comment by parafin** [comment]
12983c77ff03508287cd659da4923dba1d56bcfc was forgotten when cherry-picking for 3.0 branch

**Comment by TurboGit** [comment]
@parafin : I've just cherry-picked it, there was no milestone set for this PR, this explain why it was forgotten.
