### ISSUE TITLE
Favorites get lost once you pick different preset from "more modules" module and wont display the favorites even when you go back to the preset where favorites were selected.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4590]
darktable-3.1.0+1065~gebe78b139-win64

Be in the all modules preset 
![image](https://user-images.githubusercontent.com/1119439/78146676-1b277d80-7450-11ea-9629-cb183f4979fe.png)

Mark some modules as favorites.
Select a different preset.
Favorites disappear.
Select the all modules preset again, preset and favorites are no longer there.

Either favorites need to be across the board of any preset select or at least the favorites should be per preset.

**Comment by Nilvus** [comment]
Presets are the displayed modules on all tabs, so that include favorites. That way it's possible to create presets with different favorites (and same for other tabs) you want. So that's the normal behavior. So if you want to use different presets, saving a preset with your favorites is recommended.

**Comment by chhil** [comment]
Thanks for the pointer, @Nilvus
