### ISSUE TITLE
Pentax k-70 not present in the lens correction module

### ISSUE THREAD

**Issue by mivoligo** [darktable-org/darktable#4594]
**Describe the bug**
I use Pentax k-70. In the lens correction this camera is not listed but according to lensfun database ( https://wilson.bronger.org/lensfun_coverage.html ) it should be.

**To Reproduce**
1. Start darktable
2. Open a picture made with Pentax k-70
3. Open lens correction module

**Expected behavior**
Pentax k-70 should be recognized by darktable or at least listed in the lens correction module

**Screenshots**
![Zrzut ekranu z 2020-04-02 11-51-43](https://user-images.githubusercontent.com/1629120/78241507-65544180-74d8-11ea-841a-a715aa817eb6.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1~git4.1cc474d20
 - OS: Ubuntu 18.04

**Additional context**

**Comment by parafin** [comment]
Run lensfun-update-data

**Comment by mivoligo** [comment]
Thanks. I got this: 
```
michal@T3500:~$ lensfun-update-data

Command 'lensfun-update-data' not found, but can be installed with:

sudo apt install liblensfun-bin

```
After installing `liblensfun-bin` it worked. Maybe darktable should have that package as a dependency?

**Comment by parafin** [comment]
Maybe, but that's a question for the distribution you're using, so this is not a right place to report it.

**Comment by mivoligo** [comment]
I've got it from the PPA ( https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable ) linked from darktable website. Not sure if my distribution is responsible for that.

**Comment by parafin** [comment]
And you can see a bugzilla link on that page, where you should report issues. Just because darktable project links some external website, doesn't mean it takes responsibility for supporting them;)

**Comment by mivoligo** [comment]
Sorry, I should've spotted that. Thanks anyway :)
