### ISSUE TITLE
Panasonic DMC-FZ45 camera support

### ISSUE THREAD

**Issue by aefkha** [darktable-org/darktable#4596]
**Describe the bug**

I'm posting here but this could be a rawspeed issue:
- I checked that panasonic DMC-FZ45 camera is supported from https://www.darktable.org/resources/camera-support/
- when importing the raw file, darktable reports "file has unknown format"; it shows in lightable though
- when opening in darkroom, dt gets stuck and displays "loading image xxxxx.RW2" indefinitely
- dt does not crash though because you can come back to lightable

**To Reproduce**

- simply reproduce the above description of the bug

**Screenshots**

- I can post some if necessary

**Platform (please complete the following information):**
 - Darktable Version:  3.0.1 stable
 - OS:  ubuntu 18.04
 -  yes (bug present when deactivated)
 -  RX480 / none (integrated GPU on another machine)

**Additional context**
 - Can you reproduce with another Darktable version?
not tried
 - Can you reproduce with a RAW or Jpeg or both?
RAW only, jpeg from the camera is fine
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
no, from OBS repos
 - Is the issue still present using an empty/new config-dir
yes

**Comment by LebedevRI** [comment]
That's because for that camera we only support 4:3 crop mode, while you've got 3:2 there.
Please contribute the full sample set from that camera (all 4(?) aspect ratios)
to http://raw.pixls.us/, and i'll fix this up.

**Comment by aefkha** [comment]
Thanks for the quick answer.
The 4 ratios are now uploaded to pixls.us, although pictures do not appear in the list

**Comment by LebedevRI** [comment]
Thanks, validated those samples. Will take a look.
