### ISSUE TITLE
Allow n>3 in $(CATEGORYn(category)) variable

### ISSUE THREAD

**Issue by EC1000** [darktable-org/darktable#4597]
**Is your feature request related to a problem? Please describe.**
In the export module, it is possible to use the (very nice and nifty) `$(CATEGORYn(category))` variable, which returns the tag name of level n [0,3] of selected category (or tag). 

It is then possible to use up to 4 levels of tags under a category (0 = one level under "category", to 3 = four levels under "category"), but not more. 

**Describe the solution you'd like**
It would be nice to be able to define n>3. 

To take on example with the classic "Places" category, one could use: 
_Places_|Continent|Country|State|City|Zipcode|Street Name|House Number

and then export in "Xmp.iptc.Location=6, 5, 4 3, 1" to have "House Number, Street Name, Zipcode City, Country"
(replace numbers above by the full `$(CATEGORYn(Places))` variable)

**Alternatives**
You can split your tags in two categories, like: 
_Places_|Continent|Country|State|City
_Address_|City|Zipcode|Street Name|House Number

I also did try $(CATEGORYn($(CATEGORYn(category)))) but it does not work! :)

**Comment by EC1000** [comment]
As a side note, while redacting this message, I notice a small error on the manual. There is a additional `$` after `n` that sould not be there: 

> `$(CATEGORYn$(category))` : tag name of level n [0,3] of selected category (or tag)'
https://darktable.gitlab.io/doc/en/export_selected.html

**Comment by phweyland** [comment]
> It would be nice to be able to define n>3.

Should be relatively easy to extend this to 9. :)

> I notice a small error on the manual. There is a additional `$` after `n` that should not be there:

Thanks for mentioning it.

I'll look at this.

**Comment by EC1000** [comment]
That was quick! Thanks :)
