### ISSUE TITLE
Access violation when trying to re-using a gradient 

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4606]
This arose while debugging the preview_downsampling code, but it seems to be present also in fresh code, on fresh images...

To reproduce: open dt, take an image into darkroom. Add a couple of masks (I used a circle and a gradient, with some curvature). Exit darkroom. Take a different image in, exit again.

Now take the first image back into darkroom. Open the mask manager, click on the last displayed shape.

For me that causes a crash. Access violation in an innocent looking if in views/darkroom.c, L609:
`if(dev->form_visible && dev->gui_module->enabled)`

dt3.1.0+1076 / Win 10.

[darktable_bt_EC8PI0.txt](https://github.com/darktable-org/darktable/files/4431447/darktable_bt_EC8PI0.txt)

**Comment by GrahamByrnes** [comment]
PS this has been haunting me for a few days until I pinned down the aplly-leave-return sequence, so I think it pre-dates @elstoc's work on gradients...

**Comment by elstoc** [comment]
Could this be related to https://github.com/darktable-org/darktable/issues/2657?

**Comment by GrahamByrnes** [comment]
I don't think so... there are no sliders involved, just clicking on the shape will do it. But who knows?

**Comment by elstoc** [comment]
Ok. I can't reproduce this on ArchLinux.

**Comment by GrahamByrnes** [comment]
This seems peculiar, trying to provoke an error of some sort? Or just to ensure outside the image?
views/view.c L 499

`if(pointery > vm->current_view->height)
    {
      px = 10000.0;
      py = -1.0;
    }`

**Comment by GrahamByrnes** [comment]
You might have to open whitebalance as well.

Anyway, there is this code:

     `const int pwidth = (dev->pipe->output_backbuf_width<<closeup) / darktable.gui->ppd;
      const int pheight = (dev->pipe->output_backbuf_height<<closeup) / darktable.gui->ppd;

      const float hbar = (self->width - pwidth) * .5f;
      const float tbar = (self->height - pheight) * .5f;
      cairo_save(cri);
      cairo_rectangle(cri, hbar, tbar, (double)pwidth, (double)pheight);`

To me, this looks like a bit of a mess: division of ints -> int;
implicit cast of float * int -> float;
then cast everything to double before using it.

At least some of this is potentially compiler dependent... is there a darktable protocol for this?
@turbogit ?
I remamber someone went hunting for mixed precision arithmetic...

**Comment by GrahamByrnes** [comment]
So a super-conservative re-write seems to have fixed the crashes... which are possibly Win specific...

**Comment by TurboGit** [comment]
Right, avoiding int / int seems a good idea. Maybe casting everything to float or double.

@GrahamByrnes : what is your conservative rewrite ?

**Comment by GrahamByrnes** [comment]
I didn't know if it was the inline casting of the const int, or the int/int
(supposed to be ok in gcc), so I just did everything in auto double.
Writing from my tablet now...

There is identical code a bit higher up that seems to work, but it seems
random.

Is it worth experimenting tomorrow, or should I just send something that
works?

**Comment by GrahamByrnes** [comment]
Addressed by #4640
