### ISSUE TITLE
DT3.0.1: collection selection does not work after a while

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#4607]
Hello, after several searches using collection filters (using tags...) result does not fit anymore:does not correspond to selected search criteria=>I get get all pictures, no pictures.... Difficult to reproduce but happens quite often when I use entensively different filters after several search. 
When problem happens:
-Exit from DT and open it back again: same problem.
-Reinstall of DT and open it back again: same problem.
-To solve I empty collection filter field and then reset the module. Then it works back again.
I am not the only one to have seen it in Windows (info from french forum of DT). What could I do to help solve the issue?
Thanks!
I use Windows 10
I think problem existed already in DT 2.6 and 3.0 but I am not sure.

**Comment by phweyland** [comment]
I can reproduce some related issues.
I'll look at this.

**Comment by andreilabato** [comment]
https://forums.darktable.fr/showthread.php?tid=4712
