### ISSUE TITLE
Make color picker color values copyable as Hex values.

### ISSUE THREAD

**Issue by borissmidt** [darktable-org/darktable#4611]
**Is your feature request related to a problem? Please describe.**
You can easily select a color using the color picker. But then it gives you RGB values as 0-255 values. While most tools like css prefer the  hex format like `#RRGGBB`.  

Currently i have to manually calculate the code to a hex code and then type it over.
The value should be copy able for easy usage. Then you could also add the value to a different image so you can compare the values. 

Maybe other color spaces might be useful like HSL. 

**Describe the solution you'd like**
Add a right mouse action to copy the color as HEX code. 
Add an option to show RGB in the hex format '#FFBE82' like.
Add an option to paste an RGB color into the color picker to compare.

(sorry for the imperative tense i'm too used to the git commit message structure).

By the way i really like darktable 3.0.1 it seems a bit faster and more stable.

**Comment by dterrahe** [comment]
@borissmidt if you are satisfied with the partial solution implemented in #4665 please close this issue. Thanks!

**Comment by borissmidt** [comment]
Hey yes it is good, Thank you for the effort! hex codes are so much easier.
