### ISSUE TITLE
Allow multiline text for at least metadata description field

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#4615]
**Is your feature request related to a problem? Please describe.**
The **description** field is limited to a single line. Most online photo sharing sites allowing multiline descriptions for the images and my old workflow was to provide my full text description in the Lightroom image description field. This was very comfortable because the description was exported into JPG files and sites like Flickr or 500px extracing the description during upload. This is still possible with Darktable 3.0.1 but limited to a single line.

**Describe the solution you'd like**
Change the metadata **description** field to a multiline control. I assume the information is stored as TEXT column in SQLite, so no database change is required because TEXT already handles multiline input fine. Maybe extra work is required for JPG and EXIF/IPTC export.
The initial size should be at least 3 lines height and expand if you enter more lines.

**Alternatives**
My Canon 5D3 allows multiline input for the Copyrights metadata field. During import in Darktable, this information is mapped to the metadata **rights** field. Because of the line breaks in the source, this is rendered with the unicode placeholder 0D0A icon. That's not a big thing but maybe it's a good idea to allow multiline for every field except of the **title** field.

**Comment by phweyland** [comment]
multiline metadata is possible since #4194 (dt 3.2).

If the character \n is ok I'm not sure about \r\n ... Could you share such an image to check if that works as well ? And why not an xmp file if you have?

**Comment by cytrinox** [comment]
@phweyland Cool, wasn't aware this is already changed an merged into master. Thank you for the patch.
Attached is a example image + XMP (by Lightroom) with multiline copyright.
[dt_copyright.zip](https://github.com/darktable-org/darktable/files/4434393/dt_copyright.zip)

**Comment by phweyland** [comment]
Thanks. It seems that works.
![image](https://user-images.githubusercontent.com/23012047/78563539-84f9ab80-77f1-11ea-8931-ca60bb8357b3.png)

Your xmp file shows this (`&#xA;` ? but we probably don't care at this stage.):
```
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Daniel Vogelbacher&#xA;www.chaospixel.com</rdf:li>
    </rdf:Alt>
   </dc:rights>
```

While exiv2 extracts the info from CR2 with normal CRLF:

Exif.Image.Copyright                         Ascii      38  Daniel Vogelbacher
www.chaospixel.com
Exif.Image.ExifTag                           Long        1  446

**Comment by cytrinox** [comment]
Yes, exactly what I was looking for :-)
Also like the notes field, it is very useful for me.
I close this one and waiting for v3.2.
