### ISSUE TITLE
WB presets for Nikon D850

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#4620]
[WB2.zip](https://github.com/darktable-org/darktable/files/4434477/WB2.zip)

**Comment by s7habo** [comment]
How to send tar.bz2 file here?

**Comment by s7habo** [comment]
[WB2.zip](https://github.com/darktable-org/darktable/files/4434475/WB2.zip)

:smile:

**Comment by johnny-bit** [comment]
I'll deal with those tomorrow :)

Thanks!

**Comment by johnny-bit** [comment]
Hey @s7habo - presets are ready, just please tell me what Firmware version do you have on your D850 :)

**Comment by s7habo** [comment]
C 1.03
LD 2.017
