### ISSUE TITLE
lt edited status icon not refreshed when discarding history

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#4624]
**Describe the bug**

The edited icon is not properly refreshed when discarding history.

**To Reproduce**

- on one image, discard history
- got to darkrroom
- activate a module, say graduated filter
- move back to lighttable

All ok, the thumbs has the modified/edited icon activated.

- discard history again, the thumbs is still displaying the edited icon. 

**Expected behavior**

The edited icon should be removed after discarding history.

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: Linux

**Additional context**

This is only a refresh issue, if you scroll the lighttable to move the thumbs out of the current view and scroll back to display it, the edited icon is not displayed anymore.

**Comment by phweyland** [comment]
I'll look at this.

**Comment by johnny-bit** [comment]
Well - this seems to work flawlessly on 3.4.0 and current master :) Let's close this, ok?
