### ISSUE TITLE
fails to open jpg image from cl

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4628]
darktable fails to open jpg image when invoked directly from command line,
  darktable <image>
image exists in library.db

openSUSE Tumbleweed 20200402
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable 3.1.0~gitgit1113.fd94083a3-2712
OpenCL on 
i7 12-core 36GB

same result from dt from local git build and from openSUSE obs build at
 https://download.opensuse.org/repositories/graphics:/darktable:/master/openSUSE_Tumbleweed/x86_64/

following command line output:

darktable /paka/xhome/Pictures/2018/holidays/dec.2018.trip.work/181205_085304.jpg
Hello World !  darktable LUA speaking :^)
[_ioppr_check_rules] found rule colorin colorout module colorout (69) is before colorin (77) image 308360 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorin colorout module colorin (77) is after colorout (69) image 308360 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorin colorout module colorout (69) is before colorin (77) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule colorin colorout module colorin (77) is after colorout (69) image 0 (dt_dev_pop_history_items_ext begin)
[_ioppr_check_rules] found rule colorin colorout module colorout (69) is before colorin (77) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule colorin colorout module colorin (77) is after colorout (69) image 0 (dt_dev_pop_history_items_ext end)
[_ioppr_check_rules] found rule colorin colorout module colorout (69) is before colorin (77) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule colorin colorout module colorin (77) is after colorout (69) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule colorin colorout module colorout (69) is before colorin (77) image 0 (dt_dev_modules_update_multishow)
[_ioppr_check_rules] found rule colorin colorout module colorin (77) is after colorout (69) image 0 (dt_dev_modules_update_multishow)
ERROR in lualib, couldn't find a position for `Tagging addon', this should never happen
[_ioppr_check_rules] found rule colorin colorout module colorout (69) is before colorin (77) image 308360 (dt_dev_read_history_no_image end)
[_ioppr_check_rules] found rule colorin colorout module colorin (77) is after colorout (69) image 308360 (dt_dev_read_history_no_image end)
[image_cache_allocate] failed to open image 4294967295 from database: no more rows available

image 181205_085304.jpg and accompanying xmp attached
![181205_085304](https://user-images.githubusercontent.com/32614680/78605781-2d2b6680-782a-11ea-9beb-99e2e28054a4.jpg)

[181205_085304.jpg.xmp.txt](https://github.com/darktable-org/darktable/files/4440832/181205_085304.jpg.xmp.txt)

**Comment by ptilopteri** [comment]
The issue should have noted the problem is when darktable is invoked with the library.db being :memory:

darktable --library :memory: /<path>/181205_085304.jpg

**Comment by ptilopteri** [comment]
still not addressed

**Comment by johnny-bit** [comment]
Hey - have you tried doing the same without lua? (as in - compile without lua support) or even disable lua totally?

**Comment by ptilopteri** [comment]
No, but I have since removed the xmp sidecar files for affected images, imported and reworked the images and do not have a copy of the previous, failing xmp files.

Since I cannot test or recreate the failing conditions, will close the issue.

thankyou
