### ISSUE TITLE
Build logical folder structure - Import workflow 

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#4633]
**Is your feature request related to a problem? Please describe.**
Currently Dt doesn't offer an import workflow whatsoever

**Describe the solution you'd like**
On my machine, I've a script processing my  pictures, downloaded from memory card, in as follows :

1) first i download the pictures i like, from my camera memory card to the standard 'home/pictures/' folder
2) by pressing the download button, a script is triggered, creating a folder with the name of my camera (e. G. 'Canon600D') in 'home/pictures/' by analyzing the camera producer in the metadata of the first image of my downloaded images
3) the script continues and creates a sub-folder, named 'date - time' 
4) all downloaded pictures in 'home/pictures/' are being moved to the sub folder created in step 3)

**Alternatives**
I'd like Dt build this folder structure for me, after confirming with 'import', from the 'import pictures from device' dialog, instead to rely on external scripts.

**Comment by parafin** [comment]
Use a separate tool like Rapid Photo Downloader.

**Comment by johans3** [comment]
I'm fine with my script and offerd this fool proof simple idea to the community. 
It wouldn't be a problem to add this kind of code 
Because of that I wrote, "I'd like" - I'm ok. 
Pity for you if you teach immediately useful ideas which are convenient after usage.

**Comment by parafin** [comment]
It was discussed multiple times, there's a already a good solution, no need to reimplement it inside darktable.
