### ISSUE TITLE
Feature Request for preference option 'expand a single left side module at a time'

### ISSUE THREAD

**Issue by StefanDieke** [darktable-org/darktable#4637]
**Is your feature request related to a problem? Please describe.**

It's not a problem but a request for a convenience feature to which would be in line with existing features in darktable. 

In the darkroom it's now possible to use hotkeys to toggle the visibility of the modules on the left hand side, like 'snapshots', 'history' etc. 

**Describe the solution you'd like**

It would be nice if there would be Gui options in the preferences to 
- 'expand a single left side module at a time'
- 'scroll to left side module when expanded/collapsed '
like these options exist for the (right side) darkroom modules and the lighttable modules.

**Comment by Nilvus** [comment]
>     * 'expand a single left side module at a time'
> 
>     * 'scroll to left side module when expanded/collapsed '
>       like these options exist for the (right side) darkroom modules and the lighttable modules.

Which version do you use? This already possible on actual darktable 3! Just check preferences (first tab). The related setting applied on all panels (left and right) and scrolling is normally there when needed.

**Comment by elstoc** [comment]
Not for me on latest master. I have 'expand a single darkroom module at a time' ticked and the setting only affects the iop modules (right-hand-side). I'm not sure I'd want that affecting the left-hand-side ones as well (since I like to have history and snapshot open at once).

However, the 'expand single lighttable module at a time' preference affects both the lighttable and the left-hand-side of the darkroom (because it just generically affects lib modules). I suspect you have both settings checked.

**Comment by Nilvus** [comment]
@elstoc: never said anything else but yes my answer was too concise here. Of course darkroom left side is related to lighttable setting. And it's good as it is, so I see nothing to change/improve here. Like you I use snapshot and history together quite often. I even don't see how to use snapshot efficiently without history module also expanded.

**Comment by elstoc** [comment]
I tend to agree - I have the darkroom option on (single module) and the lighttable one off (multi module) and it works fine for me - though the preference description is confusing since it refers only to the lighttable.

**Comment by StefanDieke** [comment]
I'm on 3.1.0+1083~gecd1346e3. 
There I can expand multiple left side modules at the same time although I have 'expand single darkroom module at a time' checked in preferences. 
Scrolling seems to work though. 

I think it would be preferable to be able to set the 'expand' option seperately for the modules on the left and for those on the right.

Propably I just fail to see its application, but what's the purpose of scrolling to a module when collapsing it? I normally collapse a module when I'm currently not interested in its output. Then why focus on something which I'm not interested in?

I get the snaphsot / history argument. So when 'single' would be selected 'snapshot' should open 'history' aswell.
But while 'snapshot' doesn't make a lot of sense without 'history', 'history' works nicely without 'snapshot'. And there are 5 more modules which don't need a second on expanded to make sense.

**Comment by StefanDieke** [comment]
Hmm. 'scroll to ...' setting in the lighttable section seems to affect the left side modules in darkroom, while the 'expand' setting in this section doesn't seem to have an effect on the left side modules in darkroom.

**Comment by elstoc** [comment]
You can do that by setting the 'lighttable' option. Essentially darktable code has 'image operations' (iop) modules (rhs of darkroom) and 'library' (lib) modules (all the others, including the lighttable ones) and the two (darkroom/lighttable) expand options work on the 'iop'/'lib' modules respectively.

Are you saying that you'd want to be able to have multiple modules open at once in the lighttable but only one in the left-hand-side of the darkroom? Because that you can't do at the moment.

**Comment by StefanDieke** [comment]
Well, in my version the lighttable expand option doesn't affect the lhs modules in darkroom.
The new option to assign hotkeys to expand/collapse the lhs modules in darkroom is a big improvement for me, since I can make the relevant module visible by a single keystroke instead of placing the the mousepointer and dragging or scrolling.  
History keeps growing, image information takes a lot of space, and mask manager is an important tool. But 1080 pixels is the limit. And - snapshot being the exception - I only need the information of one of these modules at a time. If all the others are collapses, chances are extremely high that the relevant part of the selected module is displayed on one keystroke. If more than one is expanded, then the need to move the mouse and scroll to reach the relevant parts is pretty likely.

**Comment by elstoc** [comment]
> in my version the lighttable expand option doesn't affect the lhs modules in darkroom

Very odd - it definitely does on mine (ArchLinux latest master). What version/OS are you using.

**Comment by StefanDieke** [comment]
Ha! It collapses the old module if I select a new one with the mouse, but not if I use the hotkey to expand it! Then the old one stays expanded. If I click another one with the mouse, all except the newly selected one are closed.
I'm on DT3.1.0+1083~gecd1346e3, also on Arch Linux.

**Comment by elstoc** [comment]
Ok that should be an easy fix. I'll look at it today

**Comment by elstoc** [comment]
Issue with the keyboard shortcuts should be resolved by #4647

**Comment by elstoc** [comment]
Keyboard shortcut issue is now resolved in master.

**Comment by StefanDieke** [comment]
Excellent! Works like a charm! Thanks a lot!

**Comment by elstoc** [comment]
Are you happy that this resolves your issue, or was your request more specifically for separating the 'lighttable' and 'darkroom left-hand-side' settings?

I didn't mark the PR as resolving your issue because I wasn't sure, but if it has, please can you close.

**Comment by StefanDieke** [comment]
It now does everything I was looking for! So thank you again!
But maybe separating the display settings for 'lighttable' and 'darkroom' would be a good idea, though,  even if it is the same modules which are used in the two different environments. But  that's just a thought. 
I close this issue as it was solved.
