### ISSUE TITLE
Blurry previews in culling mode

### ISSUE THREAD

**Issue by Artefact2** [darktable-org/darktable#4650]
Using the culling view sometimes uses blurry pictures for images that have been edited in darkroom mode. If I zoom to 100%, the issue disappears after waiting for both images to render correctly, but the issue reappears when I zoom back.

Steps to reproduce:
* Make a duplicate of any picture
* Edit both copies in darkroom
* Go back to lighttable, select the two copies, open the culling view with dynamic zoom
* What you see is not what you saw in darkroom (much lower res?)

Screenshots:
The darkroom view, with a sharp preview:
![](https://lutim.l4p1n.ch/f0jcqdi6/2n0zGYGw.jpg)
Now the culling view, with blurry previews:
![](https://lutim.l4p1n.ch/YVfXspJ8/iGLR9vL3.jpg)

~~~
% uname -sr
Linux 5.5.13-arch2-1
% darktable --version
this is darktable 3.1.0+1083~gecd1346e3
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
~~~

**Comment by elstoc** [comment]
Probably a similar thing to the issues discussed in #4638 (speed optimisations when creating preview images)

**Comment by aurelienpierre** [comment]
This is caused by Cairo downsampling filter.

**Comment by elstoc** [comment]
Is it different to the issue with the duplicate module?

**Comment by Nilvus** [comment]
@Artefact2: culling has been completely rewrited by @AlicVB since your issue. You don't precise version you use but if you can, could you test last master to see if it's ok? If yes, think of closing this issue.

**Comment by Artefact2** [comment]
Thanks. Fixed as of today's master.
