### ISSUE TITLE
Images opened with sRGB instead of embedded input color profile

### ISSUE THREAD

**Issue by Dannny1** [darktable-org/darktable#4651]
**Describe the bug**
Currently images are opened with sRGB instead of embedded input color profile.

**To Reproduce**
Open e.g. tiff file exported with linear prophoto rgb profile, and see input color profile module.

**Expected behavior**
Please revert the behaviour as was in 3.0, where embedded icc profile was default.

**Platform (please complete the following information):**
 - Darktable Version: master and 3.0.1
 - OS: Windows Linux

**Additional context**
More info e.g. in this pixls.us topic:
https://discuss.pixls.us/t/jpegs-in-adobergb-too-little-saturated/15785/24
Issue seen on windows and linux, with and without cleaning cache/config, present in master at least since january and in 3.0.1.

**Comment by jenshannoschwalm** [comment]
Fixed via #4745

**Comment by Dannny1** [comment]
It works now. :) Thank you very much.
