### ISSUE TITLE
Retouch module doesn't work

### ISSUE THREAD

**Issue by lterlecki** [darktable-org/darktable#4655]
**Describe the bug**
Since >2.6.2 (in 2.6.2 it works perfectly) the retouch module won't work.

**To Reproduce**

1. Go to "Darkroom"
2. Click on "correction group"
3. Scroll down to "Retouch" 
4. Add one shape on image
5. Wait a moment for preview
6. Nothing changed

**Expected behavior**
In 2.6.2 Retouch module can seriously remove items from image. It should replace left circle content by right circle content.

**Screenshots**
![Zrzut ekranu z 2020-04-09 12-06-30](https://user-images.githubusercontent.com/22658233/78884808-d0af8d80-7a5b-11ea-8f1e-8e3c9536d502.png)

**Platform (tested also on 3.0.1):
 - Darktable Version: 3.1.0~git1133.5827c0dce
 - compile options:
    bit depth is 64 bit
    normal build
    SSE2 optimized codepath enabled
    OpenMP support enabled
    OpenCL support enabled
    Lua support enabled, API version 5.0.2
    Colord support enabled
    gPhoto2 support enabled
    GraphicsMagick support enabled
    OpenEXR support enabled
 - OS: Linux Mint 19.3 Tricia (Ubuntu 18.04 LTS Bionic Beaver)
 - OpenCL disabled
 - VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller; Kernel driver in use: i915

**Additional context**
 - Can you reproduce with another Darktable version?
   - Yes, on 3.0.1
 - Can you reproduce with a RAW or Jpeg or both?
   - Jpeg never tried, I'm working on RAW
 - Are the steps above reproduce with a fresh edit (removing history)?
   - Doesn't matter, fresh file behaviour the same way
 - Attach an XMP if this is necessary
   - Isn't necessary
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
   - Downloaded from your repo, compile options in "Platform" part
 - Is the issue still present using an empty/new config-dir
   - Yes, it does.

  Some debug output just from 1 shape retouch operation (from screenshot):
`39,177181 [sql] /usr/src/packages/BUILD/src/common/tags.c:207, function dt_tag_new(): prepare "SELECT id FROM data.tags WHERE name = ?1"
39,177279 [sql] /usr/src/packages/BUILD/src/common/tags.c:1036, function dt_is_tag_attached(): prepare "SELECT imgid FROM main.tagged_images WHERE imgid = ?1 AND tagid = ?2"
39,197198 [add_job_res] 0 | 39,197230 develop process image | queue: 0 | priority: 039,197239 
39,197338 [add_job_res] 1 | 39,197349 develop process preview | queue: 0 | priority: 039,197357 
39,197444 [run_job+] 01 295818739,949421 39,197489 develop process preview | queue: 0 | priority: 039,197560 
39,197722 [pixelpipe_process] [preview] using device -1
[memory] before pixelpipe process
39,197446 [run_job+] 00 295818739,949423 39,197795 develop process image | queue: 0 | priority: 039,197813 
39,197862 [dev] took 0,000 secs (0,000 CPU) to load the image.
39,197967 [pixelpipe_process] [full] using device -1
[memory] max address space (vmpeak):     2930160 kB
[memory] cur address space (vmsize):     2617780 kB
[memory] max used memory   (vmhwm ):      842912 kB
[memory] cur used memory   (vmrss ):      547248 kB
pixelpipe cacheline 0 used 0 by 0
[memory] before pixelpipe process
[memory] max address space (vmpeak):     2930160 kB
[memory] cur address space (vmsize):     2617780 kB
[memory] max used memory   (vmhwm ):      842912 kB
[memory] cur used memory   (vmrss ):      547248 kB
pixelpipe cacheline 1 used 3 by 10669269824441183099
pixelpipe cacheline 2 used 2 by 8584467859591704996
pixelpipe cacheline 3 used -4 by 7495567559522110720
pixelpipe cacheline 4 used 4 by 15950002393841738024
cache hit rate so far: 0,016
pixelpipe cacheline 0 used 3 by 2039552046086886952
pixelpipe cacheline 1 used -5 by 14034069124634074867
pixelpipe cacheline 2 used 2 by 11222671038306708919
pixelpipe cacheline 3 used 4 by 16528635113338444347
pixelpipe cacheline 4 used 1 by 6536320418790265043
cache hit rate so far: 0,022
39,218873 [masks circle #7] circle area took 0,0004 sec
39,218959 [masks circle #7] circle area took 0,0004 sec
39,219042 [masks circle #7] circle draw took 0,0000 sec
39,219734 [masks circle #7] circle draw took 0,0008 sec
39,220135 [masks circle #7] circle transform took 0,0010 sec
39,220214 [masks circle #7] circle fill took 0,0000 sec
39,234807 [masks circle #7] circle transform took 0,0150 sec
39,235695 [masks circle #7] circle fill took 0,0008 sec
39,419475 [dev_pixelpipe] took 0,221 secs (0,501 CPU) processed `retouch' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `retouch' min: (0,000509; 0,000000; -0,009553) max: (1,214109; 1,014342; 1,028655) [preview]
39,481097 [dev_pixelpipe] took 0,015 secs (0,045 CPU) processed `input color profile' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `input color profile' min: (3,230635; -26,865467; -54,455120) max: (103,615654; 71,659775; 97,944069) [preview]
image colorspace transform Lab-->RGB took 0,010 secs (0,036 CPU) [basicadj ]
39,620200 [dev_pixelpipe] took 0,091 secs (0,282 CPU) processed `basic adjustments' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `basic adjustments' min: (-0,012524; -0,031669; -0,053319) max: (1,717394; 1,374469; 1,356609) [preview]
39,688086 [dev_pixelpipe] took 0,008 secs (0,028 CPU) processed `base curve' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `base curve' min: (-0,012524; -0,029214; -0,092259) max: (1,777217; 1,075861; 1,497746) [preview]
image colorspace transform RGB-->Lab took 0,022 secs (0,076 CPU) [bilat ]
39,778282 [dev_pixelpipe] took 0,574 secs (1,402 CPU) processed `retouch' on CPU, blended on CPU [full]
[dev_pixelpipe] module `retouch' min: (-0,003600; -0,014923; -0,004436) max: (1,419384; 1,235574; 1,370288) [full]
39,818338 [dev_pixelpipe] took 0,011 secs (0,026 CPU) processed `input color profile' on CPU, blended on CPU [full]
[dev_pixelpipe] module `input color profile' min: (-2,347997; -49,436172; -48,394531) max: (109,215797; 101,269348; 91,639832) [full]
image colorspace transform Lab-->RGB took 0,011 secs (0,031 CPU) [basicadj ]
39,907817 [dev_pixelpipe] took 0,056 secs (0,154 CPU) processed `basic adjustments' on CPU, blended on CPU [full]
[dev_pixelpipe] module `basic adjustments' min: (-0,018467; -0,063175; -0,044035) max: (1,911606; 1,688271; 1,877094) [full]
39,947523 [dev_pixelpipe] took 0,004 secs (0,016 CPU) processed `base curve' on CPU, blended on CPU [full]
[dev_pixelpipe] module `base curve' min: (-0,018412; -0,080616; -0,078727) max: (1,841727; 1,201308; 1,826116) [full]
image colorspace transform RGB-->Lab took 0,008 secs (0,033 CPU) [bilat ]
41,171257 [dev_pixelpipe] took 1,192 secs (1,846 CPU) processed `local contrast' on CPU, blended on CPU [full]
[dev_pixelpipe] module `local contrast' min: (-12,950886; -66,565628; -62,339680) max: (109,217087; 127,771721; 235,446716) [full]
41,218158 [dev_pixelpipe] took 0,008 secs (0,029 CPU) processed `color correction' on CPU, blended on CPU [full]
41,252316 [dev_pixelpipe] took 1,509 secs (2,646 CPU) processed `local contrast' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `color correction' min: (-12,950886; -66,476418; -61,078701) max: (109,217087; 128,012253; 239,988815) [full]
image colorspace transform Lab-->RGB took 0,010 secs (0,031 CPU) [velvia ]
41,276810 [dev_pixelpipe] took 0,021 secs (0,070 CPU) processed `velvia' on CPU, blended on CPU [full]
[dev_pixelpipe] module `local contrast' min: (-13,867400; -42,100430; -67,456917) max: (106,550072; 99,009636; 207,324844) [preview]
41,301506 [dev_pixelpipe] took 0,007 secs (0,015 CPU) processed `color correction' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `velvia' min: (0,000000; 0,000000; 0,000000) max: (1,000000; 1,000000; 1,000000) [full]
image colorspace transform RGB-->Lab took 0,016 secs (0,046 CPU) [vibrance ]
41,323780 [dev_pixelpipe] took 0,022 secs (0,067 CPU) processed `vibrance' on CPU, blended on CPU [full]
[dev_pixelpipe] module `color correction' min: (-13,867400; -41,793621; -66,375366) max: (106,550072; 99,311096; 209,788879) [preview]
image colorspace transform Lab-->RGB took 0,009 secs (0,037 CPU) [velvia ]
[dev_pixelpipe] module `vibrance' min: (0,000000; -48,480198; -62,626667) max: (99,999474; 129,131348; 132,872711) [full]
41,376137 [dev_pixelpipe] took 0,020 secs (0,076 CPU) processed `output color profile' on CPU, blended on CPU [full]
41,377781 [dev_pixelpipe] took 0,032 secs (0,121 CPU) processed `velvia' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `output color profile' min: (0,000000; 0,000000; 0,000000) max: (1,249996; 1,017159; 1,030987) [full]
41,408025 [dev_pixelpipe] took 0,007 secs (0,027 CPU) processed `display encoding' on CPU, blended on CPU [full]
41,408604 [dev_process_image] pixel pipeline processing took 2,211 secs (4,372 CPU)
[dev_pixelpipe] module `velvia' min: (0,000000; 0,000000; 0,000000) max: (1,000000; 1,000000; 1,000000) [preview]
image colorspace transform RGB-->Lab took 0,022 secs (0,070 CPU) [vibrance ]
41,454150 [dev_pixelpipe] took 0,032 secs (0,099 CPU) processed `vibrance' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `vibrance' min: (0,000000; -47,844482; -58,917618) max: (99,999474; 109,335266; 123,080185) [preview]
41,525100 [dev_pixelpipe] took 0,030 secs (0,089 CPU) processed `output color profile' on CPU, blended on CPU [preview]
41,549608 [pixelpipe_process] [full] using device -1
[memory] before pixelpipe process
[memory] max address space (vmpeak):     2930160 kB
[memory] cur address space (vmsize):     2615740 kB
[memory] max used memory   (vmhwm ):      842912 kB
[memory] cur used memory   (vmrss ):      547432 kB
pixelpipe cacheline 0 used 3 by 12564194342336316924
pixelpipe cacheline 1 used 2 by 6605100620542508899
pixelpipe cacheline 2 used 1 by 8374731650595476999
pixelpipe cacheline 3 used -5 by 11380626240100191527
pixelpipe cacheline 4 used 4 by 5366271136789537404
cache hit rate so far: 0,030
41,551757 [dev_pixelpipe] took 0,001 secs (0,006 CPU) initing base buffer [full]
41,552791 [dev_pixelpipe] took 0,001 secs (0,002 CPU) processed `raw black/white point' on CPU, blended on CPU [full]
[dev_pixelpipe] module `raw black/white point' min: (-0,004904) max: (1,000075) [full]
41,564660 [dev_pixelpipe] took 0,001 secs (0,002 CPU) processed `white balance' on CPU, blended on CPU [full]
[dev_pixelpipe] module `output color profile' min: (0,000000; 0,000000; 0,000000) max: (1,228045; 1,006518; 1,025081) [preview]
41,579491 [dev_pixelpipe] took 0,010 secs (0,040 CPU) processed `display encoding' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `white balance' min: (-0,010684) max: (2,178875) [full]
41,589936 [dev_pixelpipe] took 0,002 secs (0,005 CPU) processed `highlight reconstruction' on CPU, blended on CPU [full]
[dev_pixelpipe] module `highlight reconstruction' min: (-0,010684) max: (1,000000) [full]
image colorspace transform RGB-->RGB took 0,077 secs (0,235 CPU) [final histogram]
final histogram took 0,016 secs (0,060 CPU)
41,674350 [dev_process_preview] pixel pipeline processing took 2,477 secs (5,099 CPU)
41,674426 [run_job-] 01 295818742,426403 41,674444 develop process preview | queue: 0 | priority: 041,674454 
41,681012 [add_job_res] 1 | 41,681290 develop process preview | queue: 0 | priority: 041,681511 
41,681750 [run_job+] 01 295818742,433727 41,681773 develop process preview | queue: 0 | priority: 041,681785 
41,712692 [dev_pixelpipe] took 0,107 secs (0,337 CPU) processed `demosaic' on CPU, blended on CPU [full]
[dev_pixelpipe] module `demosaic' min: (-0,006722; 0,000000; -0,001965) max: (1,318464; 1,125622; 1,253737) [full]
41,832730 [pixelpipe_process] [preview] using device -1
[memory] before pixelpipe process
[memory] max address space (vmpeak):     2930160 kB
[memory] cur address space (vmsize):     2625492 kB
[memory] max used memory   (vmhwm ):      842912 kB
[memory] cur used memory   (vmrss ):      557172 kB
pixelpipe cacheline 0 used 0 by 0
pixelpipe cacheline 1 used 2 by 2574745132448644720
pixelpipe cacheline 2 used -4 by 1072400215790823764
pixelpipe cacheline 3 used 3 by 16279874568973106223
pixelpipe cacheline 4 used 4 by 15950002393841738024
cache hit rate so far: 0,027
41,848219 [masks circle #7] circle area took 0,0001 sec
41,848286 [masks circle #7] circle draw took 0,0000 sec
41,849323 [masks circle #7] circle transform took 0,0010 sec
41,849404 [masks circle #7] circle fill took 0,0000 sec
41,987218 [dev_pixelpipe] took 0,235 secs (0,800 CPU) processed `lens correction' on CPU, blended on CPU [full]
42,020083 [dev_pixelpipe] took 0,187 secs (0,584 CPU) processed `retouch' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `lens correction' min: (-0,003859; 0,000000; -0,003873) max: (1,382308; 1,237879; 1,380720) [full]
[dev_pixelpipe] module `retouch' min: (0,000509; 0,000000; -0,009553) max: (1,214109; 1,014342; 1,028655) [preview]
42,097096 [dev_pixelpipe] took 0,014 secs (0,050 CPU) processed `input color profile' on CPU, blended on CPU [preview]
42,109226 [dev_pixelpipe] took 0,086 secs (0,285 CPU) processed `crop and rotate' on CPU, blended on CPU [full]
[dev_pixelpipe] module `crop and rotate' min: (-0,003600; -0,014923; -0,004436) max: (1,419384; 1,235574; 1,370288) [full]
[dev_pixelpipe] module `input color profile' min: (3,230635; -26,865467; -54,455120) max: (103,615654; 71,659775; 97,944069) [preview]
42,141784 [masks circle #7] circle area took 0,0004 sec
42,142422 [masks circle #7] circle draw took 0,0006 sec
image colorspace transform Lab-->RGB took 0,013 secs (0,043 CPU) [basicadj ]
42,160446 [masks circle #7] circle transform took 0,0180 sec
42,161502 [masks circle #7] circle fill took 0,0010 sec
42,200035 [dev_pixelpipe] took 0,064 secs (0,227 CPU) processed `basic adjustments' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `basic adjustments' min: (-0,012524; -0,031669; -0,053319) max: (1,717394; 1,374469; 1,356609) [preview]
42,261845 [dev_pixelpipe] took 0,015 secs (0,041 CPU) processed `base curve' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `base curve' min: (-0,012524; -0,029214; -0,092259) max: (1,777217; 1,075861; 1,497746) [preview]
image colorspace transform RGB-->Lab took 0,016 secs (0,042 CPU) [bilat ]
42,429213 [dev_pixelpipe] took 0,297 secs (0,789 CPU) processed `retouch' on CPU, blended on CPU [full]
[dev_pixelpipe] module `retouch' min: (-0,003600; -0,014923; -0,004436) max: (1,419384; 1,235574; 1,370288) [full]
42,471550 [dev_pixelpipe] took 0,008 secs (0,017 CPU) processed `input color profile' on CPU, blended on CPU [full]
[dev_pixelpipe] module `input color profile' min: (-2,347997; -49,436172; -48,394531) max: (109,215797; 101,269348; 91,639832) [full]
image colorspace transform Lab-->RGB took 0,011 secs (0,042 CPU) [basicadj ]
42,562660 [dev_pixelpipe] took 0,052 secs (0,145 CPU) processed `basic adjustments' on CPU, blended on CPU [full]
[dev_pixelpipe] module `basic adjustments' min: (-0,018467; -0,063175; -0,044035) max: (1,911606; 1,688271; 1,877094) [full]
42,606427 [dev_pixelpipe] took 0,008 secs (0,017 CPU) processed `base curve' on CPU, blended on CPU [full]
[dev_pixelpipe] module `base curve' min: (-0,018412; -0,080616; -0,078727) max: (1,841727; 1,201308; 1,826116) [full]
image colorspace transform RGB-->Lab took 0,010 secs (0,030 CPU) [bilat ]
43,643027 [dev_pixelpipe] took 1,334 secs (2,220 CPU) processed `local contrast' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `local contrast' min: (-13,867400; -42,100430; -67,456917) max: (106,550072; 99,009636; 207,324844) [preview]
43,714379 [dev_pixelpipe] took 0,012 secs (0,033 CPU) processed `color correction' on CPU, blended on CPU [preview]
43,739845 [dev_pixelpipe] took 1,100 secs (1,899 CPU) processed `local contrast' on CPU, blended on CPU [full]
[dev_pixelpipe] module `color correction' min: (-13,867400; -41,793621; -66,375366) max: (106,550072; 99,311096; 209,788879) [preview]
[dev_pixelpipe] module `local contrast' min: (-12,950886; -66,565628; -62,339680) max: (109,217087; 127,771721; 235,446716) [full]
43,776229 [dev_pixelpipe] took 0,011 secs (0,030 CPU) processed `color correction' on CPU, blended on CPU [full]
image colorspace transform Lab-->RGB took 0,017 secs (0,042 CPU) [velvia ]
43,794292 [dev_pixelpipe] took 0,034 secs (0,097 CPU) processed `velvia' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `color correction' min: (-12,950886; -66,476418; -61,078701) max: (109,217087; 128,012253; 239,988815) [full]
image colorspace transform Lab-->RGB took 0,008 secs (0,029 CPU) [velvia ]
43,822675 [dev_pixelpipe] took 0,019 secs (0,065 CPU) processed `velvia' on CPU, blended on CPU [full]
[dev_pixelpipe] module `velvia' min: (0,000000; 0,000000; 0,000000) max: (1,000000; 1,000000; 1,000000) [preview]
[dev_pixelpipe] module `velvia' min: (0,000000; 0,000000; 0,000000) max: (1,000000; 1,000000; 1,000000) [full]
image colorspace transform RGB-->Lab took 0,013 secs (0,034 CPU) [vibrance ]
image colorspace transform RGB-->Lab took 0,033 secs (0,109 CPU) [vibrance ]
43,880954 [dev_pixelpipe] took 0,020 secs (0,058 CPU) processed `vibrance' on CPU, blended on CPU [full]
43,888407 [dev_pixelpipe] took 0,041 secs (0,137 CPU) processed `vibrance' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `vibrance' min: (0,000000; -48,480198; -62,626667) max: (99,999474; 129,131348; 132,872711) [full]
43,924561 [dev_pixelpipe] took 0,017 secs (0,057 CPU) processed `output color profile' on CPU, blended on CPU [full]
[dev_pixelpipe] module `vibrance' min: (0,000000; -47,844482; -58,917618) max: (99,999474; 109,335266; 123,080185) [preview]
43,958027 [dev_pixelpipe] took 0,023 secs (0,076 CPU) processed `output color profile' on CPU, blended on CPU [preview]
[dev_pixelpipe] module `output color profile' min: (0,000000; 0,000000; 0,000000) max: (1,249996; 1,017159; 1,030987) [full]
43,971939 [dev_pixelpipe] took 0,012 secs (0,033 CPU) processed `display encoding' on CPU, blended on CPU [full]
43,972589 [dev_process_image] pixel pipeline processing took 2,423 secs (5,512 CPU)
43,972661 [run_job-] 00 295818744,724638 43,972683 develop process image | queue: 0 | priority: 043,972696 
[dev_pixelpipe] module `output color profile' min: (0,000000; 0,000000; 0,000000) max: (1,228045; 1,006518; 1,025081) [preview]
44,012034 [dev_pixelpipe] took 0,010 secs (0,038 CPU) processed `display encoding' on CPU, blended on CPU [preview]
image colorspace transform RGB-->RGB took 0,041 secs (0,138 CPU) [final histogram]
final histogram took 0,006 secs (0,011 CPU)
44,060519 [dev_process_preview] pixel pipeline processing took 2,379 secs (5,322 CPU)
44,060590 [run_job-] 01 295818744,812566 44,060608 develop process preview | queue: 0 | priority: 044,060619`

**Comment by elstoc** [comment]
Did you try ctrl-scroll to change the shape opacity?  There have been some issues with default opacity being set to zero somehow.

**Comment by lterlecki** [comment]
@elstoc 
Yes, i've tried just before i've send a issue.

**Comment by elstoc** [comment]
Ok thanks. I can't reproduce this on current master.

**Comment by lterlecki** [comment]
@elstoc here you have a video: https://youtu.be/CATr29CoN98

**Comment by elstoc** [comment]
As I suspected - your shape opacity is set to zero. Look at the top bar. 

Before you place your shape onto the image, hold ctrl and scroll up until that number changes to 100%.

That will change your default opacity and fix your issue for all subsequently-placed shapes.

**Comment by lterlecki** [comment]
Oh, i see now. That's different behaviour. Ok than, thank you a lot and you've localized the problem! The main problem is between chair and keyboard ;)
