### ISSUE TITLE
Drawn & Parametric Masks in exclusive mode does not work anymore? 

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#4661]
**Describe the bug**
mask do not work as desribed in that tuto: https://darktable.fr/2018/05/darktable-tuto-n5-masques-dessines-et-parametriques-en-mode-exclusif/#comment-28681
When I select sky with a parametric mask first and then create a drawn mask to remove ground parts to keep only sky, when I set drawing to positive as parametric, and use masks exclude, it does not match: I do not remove from intial selection what I select with drawing

**To Reproduce**
1. take a picture with ground and sky.
2. go to exposure module for instance (same problem with all modules)
3. click on parametric and drawing mask 
4. In L channel, select a part of sky and tune settings to select sky 
![DTmasque3](https://user-images.githubusercontent.com/44755276/78932719-51947680-7aa8-11ea-814f-cc4dd57fba54.png)
5. then click on drawing mask and draw to remove remaining select parts in ground
6. set polarity of drawn mask to positive the the selection is wrong: no effect of my drawing
![DTmasque4](https://user-images.githubusercontent.com/44755276/78933438-9836a080-7aa9-11ea-860d-7b9c4beed93d.png)

**Expected behavior**
I expect using these process (described in french in tuto) to remove from parametric intial selection, selected parts that I set with drawing.

**Screenshots**
![DTmasque3](https://user-images.githubusercontent.com/44755276/78932719-51947680-7aa8-11ea-814f-cc4dd57fba54.png)
![DTmasque4](https://user-images.githubusercontent.com/44755276/78933438-9836a080-7aa9-11ea-860d-7b9c4beed93d.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.0.1 
 - OS:  Windows10 
 - OpenCL activated  
 - Which graphics card

**Additional context**
 - Can you reproduce with another Darktable version? not tried
 - Can you reproduce with a RAW or Jpeg or both? Yes as linked to mask cross modules
 - Are the steps above reproduce with a fresh edit (removing history)? Yes

**Comment by elstoc** [comment]
Works ok for me on latest master. Have you checked your shape opacity setting? It should be shown in the top bar when you hover over the drawn mask.

**Comment by andreilabato** [comment]
I am glad if there is no issue but I do not understand the behavior in 3.0.1. the mask opacity  over drawn mask area is set as default:100% (see my screen shot). I do not understand how to set selectively the opacity of shape mask. Please can you show it on my screen shot of function you are talking about? Thanks.

**Comment by elstoc** [comment]
I'm not necessarily saying there's no issue, just that I can't see the opacity of your shape in your screenshots so I can't be sure.

I'm not 100% sure what the mask opacity in the right-hand-side of the screen represents but that's not the opacity of the shape. It should be shown in the top bar when you hover over the shape.

**Comment by andreilabato** [comment]
As far as I understood, mask opacity in the right-hand-side of the screen represents the overall opacity of resulting mask (drawn+parametric).
I do not understand "top bar when you hover over the shape": when I over the mask with mouse, discontaneous line appears of shape mask, but I cannot see opacity you are talking about wherever in screen:
![DTmasque6](https://user-images.githubusercontent.com/44755276/78982044-914b7480-7b21-11ea-8314-6d9413c71db5.png)
with this combined masks it should unselect hairs, fingers, bridge...
![DTmasque7](https://user-images.githubusercontent.com/44755276/78982120-b4762400-7b21-11ea-9999-e0b5f242c809.png)

**Comment by elstoc** [comment]
You may have the top bar hidden. ``ctrl-shift-t`` should unhide it (you may have to do this a couple of times). Top bar should look like this when you hover:

![Screenshot_2020-04-10_11-35-06](https://user-images.githubusercontent.com/9555491/78984915-5fd1a980-7b1f-11ea-8051-570a00f28fbe.png)

**Comment by andreilabato** [comment]
THANKS! I caught it. Opacity was intially to 44%. 
![DTmasque8](https://user-images.githubusercontent.com/44755276/78986356-67974b00-7b2b-11ea-9844-487c35913970.png)
I moved it to 100% and now things that should disappear did:
![DTmasque9](https://user-images.githubusercontent.com/44755276/78986392-75e56700-7b2b-11ea-8ee8-195a7996a40a.png)

**Comment by elstoc** [comment]
Excellent. If you want to make that change permanent you can either modify your darktablerc file (there's an opacity setting in there - change it to 1 while out of darktable) or you can create a new shape and ctrl-scroll-up before you place it on the image. That will alter your default opacity.

**Comment by elstoc** [comment]
Please can you close the issue if you're happy it's resolved.
