### ISSUE TITLE
French translation issues (tagging module) 

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4663]
**Dans la boîte de dialogue "créer un mot-clé"**

"sans catégorie" est à remplacer par "catégorie" (label anglais : category)

**Par ailleurs  :** 

#3597 est toujours d'actualité.

**Configuration :**
 - Darktable Version: 3.0.1
 - Windows 8.1

Merci d'avance.

**Comment by TurboGit** [comment]
Fixed ! Thanks.
