### ISSUE TITLE
[Feature] Lighttable : sticky/non-sticky preview : information customization

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4666]
_Disclaimer : there's normaly a high probatility that I get slammed (with kindness I mean) by AlicVB because it already exists or was already requested ... despite my searches with multiple keywords in github or the docs, or because I missed an existing pull request or similar issue :)_

I use the sticky preview a lot (a little less the non sticky), because for a preview (i.e browsing through pics with no retouching purpose), it is quite fast therefore handy !

When doing so, the information displayed at the top left corner are hardcoded and cannot be customized the way the information line or the tooltip can !

![image](https://user-images.githubusercontent.com/3989573/78976024-a7ebce80-7b15-11ea-8aa1-d3ec1af2a08e.png)

None of my customization work on this part :
![image](https://user-images.githubusercontent.com/3989573/78976103-c94cba80-7b15-11ea-8fb7-4e5a70c23b29.png)

It would be great that this could be either customized or if it could use the same info line as the tooltip !

Thanks
GLLM

**Comment by AlicVB** [comment]
No, it's not already possible :)
... but I plan to do that in my currently under (slow) progress culling/preview rewrite (in the same spirit as the filemanager)

**Comment by GLLM** [comment]
When/if you do so, please enable the $(NL) : it's great for tooltips :-)

**Comment by AlicVB** [comment]
This is done in master

**Comment by GLLM** [comment]
Thank you very much ! Using it as I type :)

**Comment by GLLM** [comment]
@AlicVB : I noticed that the <i> and <b> do not work, is it expected ?
They do in tooltips.

**Comment by AlicVB** [comment]
@GLLM : yes it's expected, as I forget it :P I'll take care !

**Comment by AlicVB** [comment]
@GLLM : PR done here : #4968
