### ISSUE TITLE
Gradient re-use issue still present.

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4668]
So after a week away with msys2 problems, I was surprised to find the same problem survives.

Here is a minimal reproduction set:

Import an image with no xmp
Take it into darkroom
Exposure -> drawn mask -> gradient
Crop & rotate: crop in both directions, offset a little
Mask manager, click on the saved gradient, see segmentation error.
Same point in the code as before, even though the following lines are now gone...

dt3.1.0+1133 & Win 10.
Note the code is announced as dirty because I had to turn off maps to get it to build.
[darktable_bt_87DZI0.txt](https://github.com/darktable-org/darktable/files/4460829/darktable_bt_87DZI0.txt)

**Comment by GrahamByrnes** [comment]
gdb back-trace is not so helpful?

[Thread 12584.0x30b4 exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006f2cd45e in expose (self=0x802aa40, cri=0x84f4410, width=1184,
    height=878, pointerx=-283, pointery=420)
    at C:/msys64/home/Graham/darktable2/src/views/darkroom.c:609
609         if(dev->form_visible && dev->gui_module->enabled)
(gdb) bt
#0  0x000000006f2cd45e in expose (self=0x802aa40, cri=0x84f4410, width=1184,
    height=878, pointerx=-283, pointery=420)
    at C:/msys64/home/Graham/darktable2/src/views/darkroom.c:609
#1  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by GrahamByrnes** [comment]
It seems I can stop the crashes by commenting out the reference to `dev->gui_module->enabled` in the infamous line 609 of darkroom.c
I went looking for an `enabled` element of the struct but failed to find one... the only use of `dev->gui_module->enabled` appears to be in darkroom.c at lines 548 & 609. I presume it's meant to store the "on/off" button of the module, but it would seem not to be doing that.

Yes, just grepping the code, but for the moment I'm doing what I know how to do :-(
@jenshannoschwalm do you know anything about how this is supposed to work/where to look?

**Comment by jenshannoschwalm** [comment]
No. I will dig into that during the next days. Ok?

**Comment by GrahamByrnes** [comment]
That'd be great, thanks.

**Comment by jenshannoschwalm** [comment]
Hi @GrahamByrnes i think i got it :-) I will do the pr but could you confirm this fix to be working correctly?
Please change L. 609 (you know where :-)
Try it to be 
`if(dev->gui_module && dev->form_visible && dev->gui_module->enabled)`

The `dev->gui_module` needs to be here too (found while reading the source), testing here works fine.

**Comment by GrahamByrnes** [comment]
Compiling during breakfast then :-)
