### ISSUE TITLE
darktable|changed tag can not be deleted anymore since 3.0.1

### ISSUE THREAD

**Issue by scorpi11** [darktable-org/darktable#4677]
The following works in 3.0.0:

1. Import a picture

2. make some changes to it in the darkroom

3. go to lighttable

4. open the tag module

5. click on the checkmark to show internal tags to see the "darktable|changed" tag

6. double-click on "darktable|changed" to delete it

7. the tag is now deleted

Or:

6. export the image

7. open the tag module -> darktable|changed tag is gone

With 3.0.1, this does not work anymore. The darktable|changed tag can neither be deleted by exporting the image, deleting it in the tag module nor using darktable.tags.detach in a lua script.

Testing some intermediate versions between 3.0.0 and 3.0.1 reveals that:

bee4517bf457067e35a9e40c430728a6bacaacaa is fine
9c1508c9781b60697400ee4adea43cdb6aa14c8e is broken

@phweyland the commits that likely introduce the issue were yours, so I was told to ping you.

**Comment by johnny-bit** [comment]
Just a quick note from conv on IRC:

@scorpi11 wants to have a way to tell if the image was changed since last export. Probably doesn't need `darktable|changed` tag verbatim.

**Comment by phweyland** [comment]
> @phweyland the commits that likely introduce the issue were yours, so I was told to ping you.

Thanks, I'll look at this

**Comment by phweyland** [comment]
I've found the bug(s). However to fix properly some code after new lighttable is involved.
So I'll issue a first PR with a quick and not too dirty fix, applicable on top of 3.0.1 (for 3.0.2) and another one, more complete for 3.2.
