### ISSUE TITLE
Hypersensitive scrolling speed in new lighttable

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#4686]
**Describe the bug**

Scrolling thru photos with my laptop's touchpad in the lighttable happens at "warp 9" velocity (extremely fast, scrolling thru 1000 photos happens in the blink of an eye).  I'll barely move my fingers an inch and have already scrolled past thousands of photos in my library.  All of the other places that I can scroll in darktable, scrolling happens at normal velocities. No other application on my system shows this hypersensitive scrolling behavior. I don't remember this behavior with the lighttable before the rewrite.

**To Reproduce**

**Expected behavior**

I expect the scrolling sensitivity to be consistent. Furthermore, I expect the ligthtable to scroll at the same normal velocities as the rest of darktable.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master (31667efdabf51de27125654e682bbc7b9c0c8b8c)
 - OS: archlinux
 - OpenCL: yes (intel 530 with neo)

**Comment by AlicVB** [comment]
by any chance, do you have a mouse somewhere to confirm that this doesn't happen with mouse ?

If it doesn't, then this has something to do with how touchpads work... Currently, I don't have any laptop here, and will not be able to get one in the next weeks (stuck at home like many others)
So I'll need help from some other devs...

**Comment by groutr** [comment]
@AlicVB I'll see if I can test with a mouse.
