### ISSUE TITLE
Low light region is crushed

### ISSUE THREAD

**Issue by baongoc124** [darktable-org/darktable#4691]
**Describe the bug & How to reproduce**

Open any image in darktable (already reset any settings by removing ~/.config/darktable), low light region is crushed to black.

**Expected behavior**

It should be a gradient but it's crushed like in the example image below.

**Screenshots**

https://imgur.com/a/6y7kM6T
The grayscale image is taken from here https://www.darktable.org/2013/12/of-histograms-and-waveforms/

**Platform (please complete the following information):**
Darktable 3.0.1 & git version
OS: Archlinux
No OpenCL
Intel GPU, driver: xf86-video-intel 1:2.99.917+899+gf66d3954-1

**Additional context**
 - Can you reproduce with another Darktable version?
I can reproduce it with git version but not on other Linux computer.

 - Can you reproduce with a RAW or Jpeg or both?
Both.

 - Are the steps above reproduce with a fresh edit (removing history)?
Yes.

 - Is the issue still present using an empty/new config-dir
Yes.

**Comment by GrahamByrnes** [comment]
Is this how it looks in dt, or after exporting? It looks like the result of viewing a 16-bit AdobeRGB image in an 8-bit sRGB image viewer.
It may not be that, but you could try exporting it in 8-bit sRGB and seeing if the problem persists.

**Comment by baongoc124** [comment]
@GrahamByrnes  as shown in the screenshot, the problem is how it looks in darktable.
Image after exporting is fine though.

(The original image is sRGB and I tried to export in sRGB.)

**Comment by GrahamByrnes** [comment]
So it appears to be an error of interpreting the ICC for the imported image. If you use some other image software to generate different versions of the image to be imported with specific encodings, that might help understand. especially since sRGB is often implied, rather than specifically encoded.
My experience with this kind of problem was after exporting from dt and trying to read into a different program to manage printing... but that wass a windows specific issue.

**Comment by baongoc124** [comment]
I converted the image to Adobe RGB and loaded it into darktable again. Still the same issue.

**Comment by GrahamByrnes** [comment]
I downloaded the png "as is" and imported it to dt... worked fine for me, both inside dt and outside.
I suspect you have a screen set-up issue... outside my competence, sorry. 

![testpng](https://user-images.githubusercontent.com/58031430/79337933-b62b5780-7f26-11ea-8ed9-5110813cf823.jpg)

**Comment by baongoc124** [comment]
@GrahamByrnes thank you for helping anyway. It's weird because it only happens to darktable. I tried with/without display color profile and still same problem.

**Comment by baongoc124** [comment]
@GrahamByrnes  Hi, so after a while, I tried random things, and my darktable is back to normal. I'm not even sure what the cause is so that still bothers me. But well, I'm happy because it's working now. 

I guess the reason could be because recently I updated xiccd in my computer...

Anyway, thank you for helping. I will close the issue then.
