### ISSUE TITLE
Mask UI inconsistency

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4695]
This is what is left of a segmentation fault that @jenshannoschwalm managed to fix in PR4678.

It eventually became clear that fixing the crash was complicated by choices made in creating the user interface. It all boils down to ctrl-scroll (changes opacity) apparently following different rules to shift-scroll (changes feathering radius) and scroll (changes shape in some way).

It's not clear which is correct.

It arises when you place some mask shapes on an image, leave the image to eg lighttable, then return to darkroom and click on a shape in mask manager.

If I suppose that a shape already placed on the image, and used to modify eg exposure, should only allow changes when a) the exposure module is open and b) the "drawn mask" submodule is open and c) the "show and modify masks" button is pressed.... then the opacity is the only parameter that behaves correctly.

If otoh I believe that clicking on a shape in mask manager should reconnect me with the shape I placed in an earlier session and allow me to edit it... then I have that freedom for the other parameters (placement, shape, feathering), while opacity refuses to shift.

So if you feel brave... :-)

(Win 10, dt3.1.0+1133 for me, but reproduced under Linux).

**Comment by johnny-bit** [comment]
No longer reproducible on 3.2.1, 3.4.0 or current master...

I put multiple masks with multiple modules on couple images, returned to ligttable, then back to editing, then using mask manager (with all processing modules closed) selected each mask shape and played with it. No problem observed...

Closing in hopes it's fixed :stuck_out_tongue_closed_eyes:
