### ISSUE TITLE
Issue DT_SIGNAL_COLLECTION_CHANGED signal - imgs list not freed

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#4713]
I've found this bug getting a segment error after this sequence:

```
GList *imgs = dt_view_get_images_to_act_on();
[...]
dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_RELOAD, imgs);
g_list_free(imgs);
```

dt_collection_update_query() in turn makes:

```
dt_control_signal_raise(darktable.signals, DT_SIGNAL_COLLECTION_CHANGED, query_change, list, next);
```
where list = imgs.

This images list is sent to several consumers. So what is the best way to free imgs being sure that all consumers are done ?

EDIT: there are a lot of places where imgs from dt_view_get_images_to_act_on() are not freed in particular in thumbtable.c, copy_history.c, rating.c and colorlabels.c.

Current master.

**Comment by phweyland** [comment]
It seems that only thumbtable uses the image list.

So a (quick and dirty) fix would be:
* in dt_collection_update_query() make a copy of the list and free it in thumbtable.c _dt_collection_changed_callback() after usage.
* properly free the list after call to dt_collection_update_query() in all places.

Any better idea ?

**Comment by parafin** [comment]
See https://github.com/darktable-org/darktable/blob/f7ba44aacdceba115f393afed60189e96e841a85/src/control/signal.c#L84 - there is a function _collection_changed_destroy_callback that already frees that list.

**Comment by parafin** [comment]
So you shouldn't g_list_free(imgs). Is it your new code, or is it existing code? If former please close this issue.

**Comment by phweyland** [comment]
> - there is a function _collection_changed_destroy_callback that already frees that list.

Excellent. I hadn't seen that.

> So you shouldn't g_list_free(imgs). Is it your new code, or is it existing code in dt master? If former please close this issue.

OK, I'll do. But it deserves at least a comment in collection.h to inform this list is not to be freed, doesn't it ?

**Comment by johnny-bit** [comment]
> OK, I'll do. But it deserves at least a comment in collection.h to inform this list is not to be freed, doesn't it ?

IMO More comments more better as long as they stay on topic and are updated with new code :)
