### ISSUE TITLE
add finetuned white balance presets for Nikon Z6

### ISSUE THREAD

**Issue by st-binder** [darktable-org/darktable#4714]
patch to  master branch:
[add-finetuned-wb-presets-for-nikon-z6.zip](https://github.com/darktable-org/darktable/files/4469826/add-finetuned-wb-presets-for-nikon-z6.zip)

**Comment by johnny-bit** [comment]
Can you do PR instead of Patch please? it's easier to merge that way.

**Comment by st-binder** [comment]
pull request has been provided
