### ISSUE TITLE
Map - add selected images from filmstrip to map works only for the first image

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#4716]
Select several images in filmstrip, and drag them to map.
Only the first images is set on map, instead of all selected.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: debian 10

**Comment by AlicVB** [comment]
confirmed. and this is not my fault. iirc it was already the case before.
I think that a good starting point is : https://github.com/darktable-org/darktable/blob/f7ba44aacdceba115f393afed60189e96e841a85/src/dtgtk/thumbtable.c#L1165

**Comment by phweyland** [comment]
> confirmed. and this is not my fault. iirc it was already the case before.

Please don't worry. The goal is to make it work again (at some point this did work :)).

I'll look at this link you've given above. If I can I'll fix it.
