### ISSUE TITLE
An Unhandled exception occured 

### ISSUE THREAD

**Issue by EMAR31** [darktable-org/darktable#4718]
[Bonjour,
Dans la Chambre Noire, une erreur grave arrive régulièrement lorsque j'active la roulette de ma souris pour augmenter ou diminuer le zoom sur une image raw. Le dernier module activé et modifié est le module Égaliseur de ton ou le module Zones de couleurs.
Darktable "plante" et je perds quelquefois toutes mes dernières modifications.

**Platform (please complete the following information):**
 -  Darktable Version: 3.0.1
 -  OS: Windows10
 - OpenCL activated
 - NVIDIA GEForce GTX 950M pilote 23.21.13.8873]
![Capture](https://user-images.githubusercontent.com/63604014/79141081-5fecd600-7db9-11ea-9498-4f8597f972e1.JPG)

[darktable_bt_I670I0.txt](https://github.com/darktable-org/darktable/files/4470671/darktable_bt_I670I0.txt)
[darktable_bt_GYXBJ0.txt](https://github.com/darktable-org/darktable/files/4470674/darktable_bt_GYXBJ0.txt)
[darktable_bt_P07ZI0.txt](https://github.com/darktable-org/darktable/files/4470675/darktable_bt_P07ZI0.txt)

En vous remerciant de votre réponse
Cordialement

**Comment by GrahamByrnes** [comment]
Je regrette qu'il y ait des erreurs qui persistaient en 3.0.1, surtout sur la compatibilité de tone equaliser et d'autres modules. Elles ont été corrigé depuis. Donc il y a un choix, soit de construire une nouvelle version de 3.1.0 (qui n'est pas toujours stable), soit d'aller juste en 3.0.2...

**Comment by EMAR31** [comment]
Il semble qu'avec la nouvelle version 3.0.2 le système soit plus stable.
Merci
