### ISSUE TITLE
Re 4313 which is now closed...lighttable correctly identifies altered image but displays the opposite..

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#4722]
@phweyland   This may be fixed already and  I can provide more details if necessary. I am using version 3.1.0+810~gdd6c2930e on WIndows.

I recently went on FB to help someone trying to identify unedited images...in working through the example i started with a folder with no edits took the screen shot and made 1 edit and repeated to show the person the change...all is good in the collections criteria and they updated correctly but lighttable displays the opposite set ie unaltered when altered is selected and altered when  basic is selected...this may have been fixed or not sure if anyone reported this behaviour??

I can provide more details if this is something that needs attention...Screenshots show it pretty well

![image](https://user-images.githubusercontent.com/44409419/79153948-bc8dc800-7d9c-11ea-9d68-49767713ed60.png)
![image](https://user-images.githubusercontent.com/44409419/79153979-ca434d80-7d9c-11ea-918f-a9c08c997362.png)

**Comment by phweyland** [comment]
dt 3.0.x altered information suffer various issues, see issue #4313.
The fix comes with history hash starting PR #4322, for dt 3.2.
Meanwhile ... I don't know what could help, sorry.

**Comment by todd-prior** [comment]
NP its predictable and actually it was all the extensive work that you guys were doing that made me stay put...may build a new version soon..Thanks for your answer...
 
Todd
 
Sent from 
Mail for Windows 10
 

From: Philippe
Sent: April 13, 2020 9:39 PM
To: darktable-org/darktable
Cc: Prior,Todd; 
Author
Subject: Re: [darktable-org/darktable] Re 4313 which is now closed...lighttable correctly identifies altered image but displays the opposite.. (#4722)

 



dt 3.0.x altered information suffer various issues, see issue 
#4313.
The fix comes with history hash starting PR 
#4322, for dt 3.2.
Meanwhile ... I don't know what could help, sorry.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by johnny-bit** [comment]
Fixed with #4322
