### ISSUE TITLE
Crash on opening CR2 from EOS 450d

### ISSUE THREAD

**Issue by PanTheRiceMan** [darktable-org/darktable#4730]
**Describe the bug**

When I try to open any CR2 file from my EOS 450d in darktable, it crashes. I am using the Windows version.

**To Reproduce**

Open A CR2 file with open pictures or from the windows explorer context. 

**Platform (please complete the following information):**
 - Darktable Version:  3.0.1
 - OS:  Windows 10 x64
 -  OpenCL activated
 -  Nvidia 436.48

**Report**

> this is darktable 3.0.1 reporting an exception:
> 
> -------------------
> 
> Error occurred on Wednesday, April 15, 2020 at 11:08:01.
> 
> darktable.exe caused an Access Violation at location 000000006362AE8E in module libdarktable.dll Writing to location 000000000000042C.
> 
> AddrPC           Params
> 000000006362AE8E 000000001F12DC20 000000000061E610 000000001AC4E680  libdarktable.dll!dt_image_import_internal  [D:/build/darktable/src/common/image.c @ 1289]
> 00000000192E37E4 000000000061E998 000000001DF5C9C0 3FF0000000000000  libimport.dll!_lib_import_single_image_callback  [D:/build/darktable/src/libs/import.c @ 824]
> 0000000067F06E66 0000000000CC0020 00000000FFFFFFFF 0000000000000000  libgobject-2.0-0.dll!g_closure_invoke
> 0000000067F24713 000000001DFF7500 00000000677479E3 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
> 0000000067F24B48 000000000061EE98 00000000679A53CA 0000000003765390  libgobject-2.0-0.dll!g_signal_emit
> 0000000067747A82 0000000000000003 000003329E3D600F 0000000003765301  libgtk-3-0.dll!gtk_button_clicked
> 0000000067747AD6 000000001AC4C130 000000006C276488 0000000000000000  libgtk-3-0.dll!gtk_button_clicked
> 0000000067F06E66 0000001C00000000 0000000D00000011 000000000000000D  libgobject-2.0-0.dll!g_closure_invoke
> 0000000067F24713 000000001DFF7500 0000000000000008 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
> 0000000067F24B48 0000000000000000 0000000000000001 0000000000000002  libgobject-2.0-0.dll!g_signal_emit
> 0000000067745DC6 0000000000000000 00000000FFFFFFFF 0000000000000000  libgtk-3-0.dll!gtk_builder_get_application
> 0000000067F06E66 0000000000000000 0000000000830080 000000001A372000  libgobject-2.0-0.dll!g_closure_invoke
> 0000000067F24713 000000001DFEDE00 000000001F2DBF80 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
> 0000000067F24B48 000000001AC4C130 00007FF8AC8BFC11 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
> 000000006780FD6D 0000000000000000 00000000649E5B0D 0000000000000001  libgtk-3-0.dll!gtk_gesture_long_press_new
> 0000000067F097CE 000000000467C000 000000000323E0A0 0000000000000000  libgobject-2.0-0.dll!g_cclosure_marshal_VOID__BOXEDv
> 0000000067F06E66 000000000061F7E0 00000000000000A0 0000000000000001  libgobject-2.0-0.dll!g_closure_invoke
> 0000000067F24713 000000001DFEDE00 000000180000008B 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
> 0000000067F24B48 0000000000000001 0000000000000000 000000001DFF7410  libgobject-2.0-0.dll!g_signal_emit
> 000000006780CD59 000000000323E140 000000000323E820 0000000000000002  libgtk-3-0.dll!gtk_glade_catalog_init
> 000000006780E2F3 0000000000000021 0000000000000000 00008C6F1CB5AEEC  libgtk-3-0.dll!gtk_gesture_handles_sequence
> 00000000678113B5 000000001DFEDE00 000000000323E820 0000000000000002  libgtk-3-0.dll!gtk_gesture_rotate_get_angle_delta
> 00000000677D7D1D 0000000000000001 00000000000000A0 000000000000006C  libgtk-3-0.dll!gtk_event_controller_handle_event
> 000000006799F4FC 000000001AC80DA0 00000077649456D6 0000000000000000  libgtk-3-0.dll!gtk_requisition_free
> 0000000067702D05 0000000000000001 0000000000000000 000000001F2DAF80  libgtk-3-0.dll!0x2d05
> 0000000067F06E66 0000000000000000 0000000000000000 0000000004EF2530  libgobject-2.0-0.dll!g_closure_invoke
> 0000000067F23C09 000000001DFF7500 000000000323E0A0 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
> 0000000067F24B48 0000000004632400 0000000000000008 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
> 00000000679A0F5F 0000000000000000 000000000323E0A0 0000000004632400  libgtk-3-0.dll!gtk_requisition_copy
> 00000000678596A7 0000000000000000 00000000649456D6 0000000000000000  libgtk-3-0.dll!gtk_lock_button_set_permission
> 000000006785BA1B 000000000061FB70 00000000032D4D00 0000000000000000  libgtk-3-0.dll!gtk_main_do_event
> 000000006C1CF0AA 0000000000000043 00000000649F4500 0000000003283040  libgdk-3-0.dll!gdk_event_free
> 000000006C204D9F 000000000061FB68 0000000000000000 0000000003281DA0  libgdk-3-0.dll!gdk_win32_drag_context_get_type
> 00000000649F7BA3 0000000000000002 000000001E1DAF50 000000001E1DAF50  libglib-2.0-0.dll!g_main_context_dispatch
> 00000000649F7DD8 0000000000000001 00000000032713E0 0000000003273B20  libglib-2.0-0.dll!g_main_context_dispatch
> 00000000649F8254 0000000000000000 0000000000000000 00000000638FABA0  libglib-2.0-0.dll!g_main_loop_run
> 000000006785AAAD 0000000000000000 0000000000402CD0 0000000003273A00  libgtk-3-0.dll!gtk_main
> 000000006373217C 00007FF800000001 00000000032713E0 00007FF800000001  libdarktable.dll!dt_gui_gtk_run  [D:/build/darktable/src/gui/gtk.c @ 1350]
> 00000000004030AC 00000000004016A0 0000000000000010 0000000000000000  darktable.exe!main  [D:/build/darktable/src/main.c @ 93]
> 00000000004015F8 000000000000005A 0000000000000000 0000000000408600  darktable.exe!wmain  [D:/build/darktable/src/win/main_wrapper.h @ 15]
> 00000000004013EE 0000000000000000 0000000000000000 0000000000000000  darktable.exe!__tmainCRTStartup  [D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 334]
> 000000000040153B 0000000000000000 0000000000000000 0000000000000000  darktable.exe!mainCRTStartup  [D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 223]
> 00007FF8AAB77BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
> 00007FF8AC8ECED1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
> 
> darktable.exe	3.0.1.0
> ntdll.dll   	10.0.18362.719
> KERNEL32.DLL	10.0.18362.329
> KERNELBASE.dll	10.0.18362.719
> apphelp.dll 	10.0.18362.1
> msvcrt.dll  	7.0.18362.1
> libintl-8.dll	0.19.8.0
> libdarktable.dll
> ADVAPI32.dll	10.0.18362.329
> sechost.dll 	10.0.18362.693
> libglib-2.0-0.dll	2.64.0.0
> RPCRT4.dll  	10.0.18362.628
> GDI32.dll   	10.0.18362.1
> ole32.dll   	10.0.18362.693
> win32u.dll  	10.0.18362.719
> combase.dll 	10.0.18362.693
> gdi32full.dll	10.0.18362.719
> msvcp_win.dll	10.0.18362.387
> ucrtbase.dll	10.0.18362.387
> bcryptPrimitives.dll	10.0.18362.295
> USER32.dll  	10.0.18362.719
> PSAPI.DLL   	10.0.18362.1
> SHELL32.dll 	10.0.18362.719
> libiconv-2.dll	1.16.0.0
> cfgmgr32.dll	10.0.18362.387
> libwinpthread-1.dll	1.0.0.0
> shcore.dll  	10.0.18362.1
> windows.storage.dll	10.0.18362.719
> libgcc_s_seh-1.dll
> profapi.dll 	10.0.18362.693
> powrprof.dll	10.0.18362.1
> UMPDC.dll
> libstdc++-6.dll
> libcairo-2.dll
> libcurl-4.dll
> shlwapi.dll 	10.0.18362.1
> exchndl.dll 	0.9.2.0
> kernel.appcore.dll	10.0.18362.1
> libexiv2.dll
> cryptsp.dll 	10.0.18362.1
> WS2_32.dll  	10.0.18362.387
> libgdk-3-0.dll	3.24.14.0
> CRYPT32.dll 	10.0.18362.592
> libgdk_pixbuf-2.0-0.dll	2.40.0.0
> IMM32.dll   	10.0.18362.387
> MSASN1.dll  	10.0.18362.1
> SETUPAPI.dll	10.0.18362.1
> WLDAP32.dll 	10.0.18362.449
> bcrypt.dll  	10.0.18362.267
> libgmodule-2.0-0.dll	2.64.0.0
> libgobject-2.0-0.dll	2.64.0.0
> libgphoto2-6.dll
> libgphoto2_port-12.dll
> libGraphicsMagick-3.dll
> libgtk-3-0.dll	3.24.14.0
> libjpeg-8.dll
> libIlmImf-2_4.dll
> libjson-glib-1.0-0.dll
> liblcms2-2.dll
> lua53.dll
> libpango-1.0-0.dll	1.43.0.0
> libpng16-16.dll
> libpugixml.dll
> libpangocairo-1.0-0.dll	1.43.0.0
> libsoup-2.4-1.dll
> libsqlite3-0.dll
> libtiff-5.dll
> libxml2-2.dll
> zlib1.dll
> libfontconfig-1.dll
> comdlg32.dll	10.0.18362.693
> MSIMG32.dll 	10.0.18362.719
> libfreetype-6.dll	2.10.1.0
> libpixman-1-0.dll
> mgwhelp.dll 	0.9.2.0
> VERSION.dll 	10.0.18362.1
> libpcre-1.dll
> dwmapi.dll  	10.0.18362.267
> gdiplus.dll 	10.0.18362.720
> libbrotlidec.dll
> libidn2-0.dll
> libnghttp2-14.dll
> libcairo-gobject-2.dll
> WINMM.dll   	10.0.18362.1
> libepoxy-0.dll
> libpsl-5.dll
> libpangowin32-1.0-0.dll	1.43.0.0
> libssh2-1.dll
> libssl-1_1-x64.dll	1.1.1.4
> libexif-12.dll
> libsystre-0.dll
> libffi-6.dll
> libbz2-1.dll
> libHalf-2_4.dll
> libIlmThread-2_4.dll
> libthai-0.dll
> libpangoft2-1.0-0.dll	1.43.0.0
> liblzma-5.dll	5.2.4.0
> libzstd.dll
> COMCTL32.dll	6.10.18362.720
> libatk-1.0-0.dll	2.34.1.0
> WINSPOOL.DRV	10.0.18362.693
> libharfbuzz-0.dll
> dbghelp.dll 	10.0.18362.1
> WINMMBASE.dll	10.0.18362.1
> USP10.dll   	10.0.18362.476
> libtre-5.dll
> libdatrie-1.dll
> PROPSYS.dll 	7.0.18362.267
> libgraphite2.dll
> IPHLPAPI.DLL	10.0.18362.1
> OLEAUT32.dll	10.0.18362.693
> dbgcore.DLL 	10.0.18362.1
> libgomp-1.dll
> libopenjp2-7.dll
> libgio-2.0-0.dll	2.64.0.0
> librsvg-2-2.dll
> libsecret-1-0.dll
> libexpat-1.dll
> libltdl-7.dll
> libfribidi-0.dll
> libIex-2_4.dll
> libcrypto-1_1-x64.dll	1.1.1.4
> libImath-2_4.dll
> libbrotlicommon.dll
> DNSAPI.dll  	10.0.18362.267
> NSI.dll     	10.0.18362.449
> libgcrypt-20.dll	1.8.5.54720
> libunistring-2.dll	0.9.10.0
> libcroco-0.6-3.dll
> CRYPTBASE.DLL	10.0.18362.1
> libgpg-error-0.dll	1.37.0.0
> rsaenh.dll  	10.0.18362.1
> uxtheme.dll 	10.0.18362.449
> clbcatq.dll 	2001.12.10941.16384
> mswsock.dll 	10.0.18362.1
> MSCTF.dll   	10.0.18362.693
> DEVOBJ.dll  	10.0.18362.387
> WINTRUST.dll	10.0.18362.387
> winhttp.dll 	10.0.18362.693
> IconCodecService.dll	10.0.18362.1
> WindowsCodecs.dll	10.0.18362.719
> libpixbufloader-png.dll
> mscms.dll   	10.0.18362.267
> USERENV.dll 	10.0.18362.387
> ColorAdapterClient.dll	10.0.18362.267
> icm32.dll   	10.0.18362.267
> TextInputFramework.dll	10.0.18362.693
> CoreUIComponents.dll	10.0.18362.207
> CoreMessaging.dll	10.0.18362.1
> ntmarta.dll 	10.0.18362.1
> wintypes.dll	10.0.18362.693
> iertutil.dll	11.0.18362.693
> OpenCL.dll  	2.2.1.0
> IntelOpenCL64.dll	26.20.100.7262
> dxgi.dll    	10.0.18362.693
> dxcore.dll  	10.0.18362.1
> intelocl64.dll	7.6.0.814
> task_executor64.dll	7.6.0.814
> cpu_device64.dll	7.6.0.814
> igdrcl64.dll	23.20.100.7262
> igdgmm64.dll	26.20.100.7262
> igdfcl64.dll	26.20.100.7262
> igc64.dll   	26.20.100.7262
> nvopencl64.dll	26.21.14.3648
> nvapi64.dll 	26.21.14.3648
> nvcompiler.dll	26.21.14.3648
> nvptxJitCompiler.dll	26.21.14.3648
> libdarkroom.dll
> libknight.dll
> liblighttable.dll
> libmap.dll
> libosmgpsmap-1.0-1.dll
> libslideshow.dll
> libtethering.dll
> libcopy.dll
> libexr.dll
> libj2k.dll
> libjpeg.dll
> libpdf.dll
> libpfm.dll
> libpng.dll
> libppm.dll
> libtiff.dll
> libwebp.dll
> libwebp-7.dll
> libdisk.dll
> libemail.dll
> libgallery.dll
> liblatex.dll
> libpiwigo.dll
> libashift.dll
> libatrous.dll
> libbasecurve.dll
> libbasicadj.dll
> libbilat.dll
> libbilateral.dll
> libbloom.dll
> libborders.dll
> libcacorrect.dll
> libchannelmixer.dll
> libclahe.dll
> libclipping.dll
> libcolisa.dll
> libcolorbalance.dll
> libcolorchecker.dll
> libcolorcontrast.dll
> libcolorcorrection.dll
> libcolorin.dll
> libcolorize.dll
> libcolormapping.dll
> libcolorout.dll
> libcolorreconstruct.dll
> libcolortransfer.dll
> libcolorzones.dll
> libdefringe.dll
> libdemosaic.dll
> libdenoiseprofile.dll
> libdither.dll
> libequalizer.dll
> libexposure.dll
> libfilmic.dll
> libfilmicrgb.dll
> libfinalscale.dll
> libflip.dll
> libgamma.dll
> libglobaltonemap.dll
> libgraduatednd.dll
> libgrain.dll
> libhazeremoval.dll
> libhighlights.dll
> libhighpass.dll
> libhotpixels.dll
> libinvert.dll
> liblens.dll
> liblensfun.dll
> liblevels.dll
> libliquify.dll
> liblowlight.dll
> liblowpass.dll
> liblut3d.dll
> libmask_manager.dll
> libmonochrome.dll
> libnlmeans.dll
> liboverexposed.dll
> libprofile_gamma.dll
> librawdenoise.dll
> librawoverexposed.dll
> librawprepare.dll
> librelight.dll
> libretouch.dll
> librgbcurve.dll
> librgblevels.dll
> librotatepixels.dll
> libscalepixels.dll
> libshadhi.dll
> libsharpen.dll
> libsoften.dll
> libsplittoning.dll
> libspots.dll
> libtemperature.dll
> libtonecurve.dll
> libtoneequal.dll
> libtonemap.dll
> libvelvia.dll
> libvibrance.dll
> libvignette.dll
> libwatermark.dll
> libzonesystem.dll
> libbackgroundjobs.dll
> libcamera.dll
> libcollect.dll
> libcolorlabels.dll
> libcolorpicker.dll
> libcopy_history.dll
> libdarktable_label.dll
> libduplicate.dll
> libexport.dll
> libfilmstrip.dll
> libfilter.dll
> libgeotagging.dll
> libglobal_toolbox.dll
> libhinter.dll
> libhistogram.dll
> libhistory.dll
> libimage.dll
> libimage_infos.dll
> libimport.dll
> liblighttable_mode.dll
> liblive_view.dll
> liblocation.dll
> libmap_settings.dll
> libmasks.dll
> libmetadata.dll
> libmetadata_view.dll
> libmodulegroups.dll
> libmodulelist.dll
> libmodule_toolbox.dll
> libnavigation.dll
> libratings.dll
> librecentcollect.dll
> libselect.dll
> libsession.dll
> libsnapshots.dll
> libstyles.dll
> libtagging.dll
> libtimeline.dll
> libviewswitcher.dll
> libview_toolbox.dll
> libpixbufloader-svg.dll
> rasadhlp.dll	10.0.18362.1
> fwpuclnt.dll	10.0.18362.207
> explorerframe.dll	10.0.18362.418
> libpixbufloader-jpeg.dll
> 
> Windows 10.0.18363
> DrMingw 0.9.2
> 
>

**Comment by johnny-bit** [comment]
There are couple things possbile...

First - can you attach a sample file that causes this behaviour? 
Second - can you try with "known good" file, eg https://raw.pixls.us/getfile.php/1353/nice/Canon%20-%20EOS%20450D%20-%20RAW%20(3:2).CR2 (sample from pixls.us)

Can you re-try with open-cl disabled?

**Comment by PanTheRiceMan** [comment]
I tried the known good file. Same behaviour.
With or without Open CL, still same error.

![darktable_error_cr2](https://user-images.githubusercontent.com/37249993/79462535-e5f66000-7ff7-11ea-8e8a-603e645985b1.PNG)

I don't think the image of the error helps a lot but here it is anyway.

**Comment by johnny-bit** [comment]
What other formats/cameras have you tried?

does known-good file from other generation of camera (eg 500D: https://raw.pixls.us/getfile.php/911/nice/Canon%20-%20EOS%20500D%20-%20RAW%20(3:2).CR2) work?

can you try different raws from raw.pixls.us and see if they work (esp canon and nikon ones)?

**Comment by mrleemon** [comment]
I can open CR2 files from a Canon 450D camera with no problems.

I'm using:

- Darktable Version: 3.0.1
- OS: Windows 10 x64
- OpenCL activated
- Nvidia 441.66

**Comment by PanTheRiceMan** [comment]
I suspected as much. I found out my version also does not open 8 bit tiff files. Maybe there is another issue. I'll try the driver first.

**Comment by johnny-bit** [comment]
If you've managed to fix your issue - please close this ticket :)

**Comment by PanTheRiceMan** [comment]
Sorry, I did not but I found out it is not a issue with the raw files specifically. Tiffs don't load either.
