### ISSUE TITLE
High contrast mode for spot visualisation

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#4734]
**Is your feature request related to a problem? Please describe.**
When working with the spot removal module, it would be very useful if you can switch into a spot visualisation mode with high contrast to detect spots.

Here is an example (regular view).

![shot_normal](https://user-images.githubusercontent.com/509535/79384685-a1bb7f00-7f67-11ea-96e2-99fa53cae761.png)
And as contrast-enhanced view:
![shot_contrast](https://user-images.githubusercontent.com/509535/79384708-ada74100-7f67-11ea-95a7-6a8d519aaafd.png)

This would help to easily identify dust and other spots. It may be also useful for the Retouch module, but there exists already something similar.

I opened this FR because Aurélien told me in IRC that this is "super easy".

This feature is also available on some other raw converters. It's called "Visualize Spots" and is adjustable by a silder which changes the contrast details.

**Comment by aurelienpierre** [comment]
The code to do that is a Laplacian filter. Put that into a loop :

```
out[(i * roi_out->width + j) * ch + c] = threshold * fabsf(in[((i - 1) * roi_out->width + j) * ch + c] + in[((i + 1) * roi_out->width + j) * ch + c] + in[(i* roi_out->width + j - 1) * ch + c] + in[(i* roi_out->width + j + 1) * ch + c] - 4.f * in[(i * roi_out->width + j) * ch + c]);
```
