### ISSUE TITLE
DT 3.0.1 hangs when importing an updated XMP file on startup.

### ISSUE THREAD

**Issue by rafalkrupinski** [darktable-org/darktable#4739]
**Describe the bug**

Darktable hangs when importing an updated XMP file on startup.

**To Reproduce**
1. have a photo with a sidecar file
1. enable the option ```core options -> look for update xml files on startup```
1. exit DT
1. change the sidecar file in a way that produces a valid xmp file (I restored a backup of XMP file)
1. start DT
1. on the modal window select the file and load the updated xml file
1. the cursor changes to busy and UI gets unresponsive, DT takes 33% CPU

**Expected behavior**
The modal windows should close and the updated sidecar should be applied to the picture.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1
 - OS: MacOS
 - yes
 - Intel Iris Plus Graphics 650 1536 MB graphics

**Additional context**
Importing a sidecar from lightable history stack module works fine.
The XMP file was created with DT 3.0.1

**Comment by Spindel** [comment]
Still happens in 3.0.2.

**Comment by Spindel** [comment]
Seems fixed in 3.3.0 nightly

**Comment by Nilvus** [comment]
I close as it is probably fixed now. If you can reproduce with actual master or future 3.6, we could consider reopening, depending on infos provided.
