### ISSUE TITLE
Autel Robotics XB015

### ISSUE THREAD

**Issue by crusty11b** [darktable-org/darktable#4746]
Hello. I have submitted a DNG file to https://raw.pixls.us/ with the file name of MAX_0001.DNG. It is from the Autel Robotics EVO drone.

When I attempt to open these images through darktable, I am shown an image of a skull and the image does not open. I have attempted to open these images through GIMP 2.10.10 with the Darktable extension, as well as through Darktable stand alone.

Please add support for this camera. Thank you.

**Comment by LebedevRI** [comment]
Works fine in darktable built from git master.

**Comment by crusty11b** [comment]
I just installed the latest version from the darktable website. I am using the windows version. Is there something I am missing?

**Comment by parafin** [comment]
git master is unreleased version.

**Comment by crusty11b** [comment]
Gotcha..... Is there an ETA for it's release? Is there a beta release? Does it only work on Linux? Could I get a response that is more than one sentence long?

**Comment by LebedevRI** [comment]
> I just installed the latest version from the darktable website.

Which is 3.0.x, correct?

> ...

I'm not really involved with dt releases, so i can't really answer those questions, sorry.

**Comment by crusty11b** [comment]
> > I just installed the latest version from the darktable website.
> 
> Which is 3.0.x, correct?
Yes. I am running version 3.0.1

**Comment by parafin** [comment]
Try 3.0.2 which just got released: https://github.com/darktable-org/darktable/releases/tag/release-3.0.2

If it doesn't work, check forums, probably someone is doing Windows builds of git master: https://discuss.pixls.us/c/software/darktable/19

git master will be released in around half a year from now most likely. You could try building it yourself from the sources of course.

Finally I want to note that this bug tracker is not a support forum, really these questions should be directed to any other of commutation channels - IRC, mailing list, forum.

**Comment by crusty11b** [comment]
Thanks for the feedback. I'll try 3.0.2.


I started this thread because I can open raw images from my other cameras, but not the drone, so it is indeed a request for camera support.
