### ISSUE TITLE
lighttable: can't change border around image in CSS

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4748]
Pull request #4660 introduced the ability to set the thumbnail margins by entering the margin percentage using a pixel value in css as follows:

```
#thumb_image
{
  border: none;
  margin : 4px; /* not real pixels, but percentage of the thumb size */
}
```
However, when I modify that 4px to 20px in darktable.css it has no effect on the lighttable.

Clean build of darktable master on ArchLinux (7dc9f8f)

**Comment by elstoc** [comment]
Ah. It works fine if I modify 
```
.dt_thumbnails_2 #thumb_image
{
  margin : 2px;
}
```
But the initial ``#thumb_image`` section does nothing

**Comment by Nilvus** [comment]
> Ah. It works fine if I modify
> 
> ```
> .dt_thumbnails_2 #thumb_image
> {
>   margin : 2px;
> }
> ```
> 
> But the initial `#thumb_image` section does nothing

Thanks for testing and pointing that. I will try to see that when working on CSS this week-end. Stay tuned.

@AlicVB: if it's only CSS issue as it seems to be, could you assign this to me and add the adapted labels? Thanks.

**Comment by Nilvus** [comment]
> Ah. It works fine if I modify
> 
> ```
> .dt_thumbnails_2 #thumb_image
> {
>   margin : 2px;
> }
> ```
> 
> But the initial `#thumb_image` section does nothing

Ok, make some testing and checking. The initial margin line on #thumb_image just because .dt_thumbnails_2 #thumb_image one is after and making same thing so it just overrides the margin line of first #thumb_image section.

On what I test, removing .dt_thumbnails_2 section you mention is the best thing to do and having 3px instead of 4px on first section. I think it's a better compromise. I think it's the better thing to do.

@AlicVB and @elstoc: is it ok for you if I change that that way?

I've tested why you want to put 20px of margin @elstoc and I now understand. That's make thumbnails like old physicals slides. That's just make the image quite too small.

**Comment by elstoc** [comment]
@Nilvus I just put 20px to test it and that makes it very obvious that it's changed. My original motivation was that the previous 4% margin was a bit big for me and I wanted to reduce it to 1%.

As long as I can control the margin I don't mind what initial value you set it to (since I'll probably override it anyway)

**Comment by AlicVB** [comment]
> Ah. It works fine if I modify
> 
> ```
> .dt_thumbnails_2 #thumb_image
> {
>   margin : 2px;
> }
> ```
> 
> But the initial `#thumb_image` section does nothing

Ok, I understand now, you want to modify margins for big thumbnails, right ? So indeed, you need to overwrite that part.

> On what I test, removing .dt_thumbnails_2 section you mention is the best thing to do and having 3px instead of 4px on first section. I think it's a better compromise. I think it's the better thing to do.

Not sure : the .dt_thumbnail_2 margins was here to reduce them for large images, where, they can become quite big as they are dependent of the thumb size.

**Comment by elstoc** [comment]
Yes I was just confused because the css tweak I made got outdated quite quickly!

**Comment by Nilvus** [comment]
> Not sure : the .dt_thumbnail_2 margins was here to reduce them for large images, where, they can become quite big as they are dependent of the thumb size.
> .dt_thumbnails_??? is a new css class to add the ability to put different css in function of the category of size of the image. The categories of sizes are the same as for the overlays choices.

@AlicVB: I could let it but I made quite some tests and check on all new modes with Gtk Inspector tool and .dt_thumbnail_2 is always there on all modes and as an identifier of #thumb_image. And this section override all #thumb_image. So letting it make the margin on #thumb_image just unuseful. I understand what you want but on what I see, check and test, the .dt_thumbnail_2 section is applied on all images, on all modes, so over #thumb_image.

**Comment by AlicVB** [comment]
> I understand what you want but on what I see, check and test, the .dt_thumbnail_2 section is applied on all images, on all modes, so over #thumb_image.

So it's a bug. I'll have a look...

**Comment by Nilvus** [comment]
@elstoc: if you could just check my last commit of #4762 and if changing margin is ok for you on it, it would be good (before the PR is merged if possible). And if ok for you, this issue could probably be closed.

**Comment by elstoc** [comment]
@Nilvus, I'm assuming that I should be updating ``#thumb_image`` for small thumbnails and ``.dt_thumbnails2 #thumb_image`` for the larger ones?

If so it seems to work fine.

**Comment by Nilvus** [comment]
@elstoc: yep, you're right!
