### ISSUE TITLE
CMake error compiling Darktable 3.0.2.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#4752]
**Describe the bug**

When compiling Darktable 3.0.2 from the release source code using the `build.sh` script, the build fails with the following errors:
```
CMake Error at data/kernels/CMakeLists.txt:34 (foreach):
  Unknown argument:

    /usr/local/src/darktable/darktable-3.0.2/data/kernels/atrous.cl



CMake Error at data/kernels/CMakeLists.txt:35 (testcompile_opencl_kernel):
  testcompile_opencl_kernel Macro invoked with incorrect arguments for macro
  named: testcompile_opencl_kernel


CMake Error at data/kernels/CMakeLists.txt:36 (endforeach):
  endforeach An ENDFOREACH command was found outside of a proper FOREACH
  ENDFOREACH structure.  Or its arguments did not match the opening FOREACH
  command.
```

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Fedora 31

**Comment by TurboGit** [comment]
Which compiler ? CMake version ?

**Comment by schwerdf** [comment]
CMake: 3.17.0-1.fc31
Compiler: gcc 9.3.1

**Comment by boson-at** [comment]
try ./build.sh --disable-opencl

**Comment by schwerdf** [comment]
`build.sh --disable-opencl` eliminated the error.

**Comment by st-binder** [comment]
It is the same error I reported for building darktable version 3.0.1 on archlinux. This happens with all newer CMake versions but there is a fix in the master branch: 
"The issue you're describing isn't distro-specific. It was fixed in 767d48e0f60e7f858e8b31a88dd8cc1258e7ee9e but the fix didn't make it into 3.0.1 AFAIK" 
This fix works for the dartable-3.0.x branch too.

**Comment by parafin** [comment]
you probably just have to disable TESTBUILD_OPENCL_PROGRAMS, not whole OpenCL support

**Comment by Foxboron** [comment]
Pulled the patch for the `3.0.2` update in the Arch Linux package, https://github.com/Foxboron/archlinux-pkgbuilds/commit/e8ace452f630e3bc9ffd8eb9a7d2ddf265684236

**Comment by ptilopteri** [comment]
cleaning the darktable build env completely solved for me on openSUSE

**Comment by waxhead** [comment]
I've had the same issue recently, how do you completely clean the build environment?  rm build/* ?

**Comment by waxhead** [comment]
I deleted the build directory and ran build again.  Getting errors still.  I've attached the CMakeError.log if it helps.


[CMakeError.log](https://github.com/darktable-org/darktable/files/4498110/CMakeError.log)
[CMakeOutput.log](https://github.com/darktable-org/darktable/files/4498111/CMakeOutput.log)

**Comment by waxhead** [comment]
My issue was resolved with submodule update:

```
git submodule init
git  submodule update
```
Still get the same CMake errors/warnings:
```
-- Found LibXml2: /usr/lib/libxml2.so (found suitable version "2.9.10", minimum required is "2.6") 
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (LibSoup2).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPkgConfig.cmake:45 (find_package_handle_standard_args)
  cmake/modules/FindLibSoup2.cmake:45 (INCLUDE)
  src/CMakeLists.txt:288 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

But compiling works fine.

**Comment by lesnake** [comment]
I also had the issue on ubuntu 20.04.
I did nothing special but giving a prefix to build.sh

The patch found here : https://svnweb.freebsd.org/ports/head/graphics/darktable/files/patch-data_kernels_CMakeLists.txt?view=markup&pathrev=534788
Solved the issue.

```
cmake --version
cmake version 3.17.0
gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
```

**Comment by johnny-bit** [comment]
CMakeLists.txt file fixed in master and uses correct foreach syntax.
