### ISSUE TITLE
Darktable on macOS crashes when displaying grayscale JPEGs.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#4753]
Whenever I try to import or display a JPEG with a grayscale colorspace (example attached below),  Darktable on macOS crashes with the following console output:
```
3.271525 [lighttable] expose took 0.0074 sec
darktable(614,0x7000087a8000) malloc: Incorrect checksum for freed object 0x7f960653c9d8: probably modified after being freed.
Corrupt value: 0x1512121211111113
darktable(614,0x7000087a8000) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
The same versions of Darktable on Linux have no issues reading or displaying the same files.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0, 3.0.1, 3.0.2
 - OS: macOS 10.14

Example grayscale JPEG:
![Grayscale](https://user-images.githubusercontent.com/3303477/79629869-6c9f6000-8112-11ea-956a-7fff259fdeb3.jpg)

**Comment by parafin** [comment]
Does it produce a crash report? If so, please post it here.

**Comment by MStraeten** [comment]
Seems to be similar to #3920

**Comment by parafin** [comment]
Indeed I think it's a duplicate. Closing this one.
