### ISSUE TITLE
Can't compile last master: xml2po missing stop compiling

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4754]
**Describe the bug**
Error asking for xml2po to compile that stop compiling.
Before, this was just an simple info to inform that manual will not be compiled but compiling darktable was ok.

**To Reproduce**
Here the script I always use (I compile darktable very often without any problem before, with xml2po not installed) with these lines:
```
#!/bin/sh

cd /home/nilvus/Projets/darktable
rm -rf build /opt/darktable
git pull
git submodule update
./build.sh --prefix /opt/darktable --build-type Release --install

exit 0
```

**Expected behavior**
Have possibility to compile darktable without having xml2po.
And probably as xml2po is a file from a quite old package (gnome-doc-utils) find another option or file if possible to compile usermanual. By now, gnome-doc-utils is no more available on Ubuntu 20.04, so xml2po is no more possible to install by default on this last release.

**Screenshots**
![Capture-20200418132659-780x551](https://user-images.githubusercontent.com/45535283/79636758-50370e00-817a-11ea-8ed9-ca8371388fa7.png)

**Comment by TurboGit** [comment]
I think you need a:
$ git submodule init

Before update.

Le sam. 18 avr. 2020 à 13:41, Nicolas Auffray <notifications@github.com> a
écrit :

**Comment by Nilvus** [comment]
> I think you need a: $ git submodule init Before update. Le sam. 18 avr. 2020 à 13:41, Nicolas Auffray

Indeed, that works now. Needed to do that 2 times to work (don't understand why). So probably needed because of last recent add of libxcf support. Thanks.

Anyway, it remains the fact that darktable use an obsolete program: xml2po.
