### ISSUE TITLE
A quite annoying bug: cancel a rejected image is no more possible

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4760]
**Describe the bug**
On last master, cancel a rejected image is no more possible.

**To Reproduce**
Provide detailed steps that can reproduce the behavior, such as:
1. On lighttable, just select an image (with shortcut or clicking on the cross)
2. Select the same rejected image and try to cancel last action by clicking again on the red cross or with 'r' shortcut.
=> image still rejected...

**Expected behavior**
Have possibility to cancel a rejected image.

**Comment by phweyland** [comment]
However ctrl-z does work, right ?

**Comment by Nilvus** [comment]
> However ctrl-z does work, right ?

Yes.

**Comment by Nilvus** [comment]
I've just found another related behavior. If i select only rejected images to display (so with few rejected ones) on lighttable and then go to preview mode with Alt+w and try to cancel the rejected image, the image disappear (like before when cancelling a rejected image was possible). But If quit the preview mode, the image is still rejected and always on rejected filter mode.

**Comment by progo** [comment]
I once made a remark on the IRC channel about the combined behavior of rejection and the setting "rating an image twice will not reset the rating to zero".

I want that behavior where I can reject an image multiple times and it'll stay rejected. I want to be looking at the images, not the stars or rejectedness when I'm culling through the shots. 

One could tie the behavior to that settings value. Someone who doesn't care about zero-star ratings can enable the  setting and experience idempotent ratings/rejections, whereas someone who desires it can set it to FALSE.

**Comment by Nilvus** [comment]
> I once made a remark on the IRC channel about the combined behavior of rejection and the setting "rating an image twice will not reset the rating to zero".
> 
> I want that behavior where I can reject an image multiple times and it'll stay rejected. I want to be looking at the images, not the stars or rejectedness when I'm culling through the shots.
> 
> One could tie the behavior to that settings value. Someone who doesn't care about zero-star ratings can enable the setting and experience idempotent ratings/rejections, whereas someone who desires it can set it to FALSE.

I personally never read IRC. Then, it's a bug report here, not a feature request. So I find your answer not related here. Of course, you talk about reject one. I want to keep the possibility to cancel rejected images. I use that to select images I want to keep and a second time, I come back to rejected images to show if I don't reject an image that finally I want to keep.

If you want another behavior (ok, if we have the possibility to keep the current known behavior) but please post a separate feature request to help following what to do. By now, the goal is to correct actual bug not to change it.

**Comment by progo** [comment]
> I personally never read IRC. Then, it's a bug report here, not a feature request. So I find your answer not related here. 

Fair enough. I'll make a ticket that contains my little lamentation.

**Comment by TurboGit** [comment]
> I once made a remark on the IRC channel

I don't read IRC and it is out of hope to have anything serious done on such channel. Even if I do follow it from time to time, what would be the probability that I'll be connected at the same time as you and see your message? Not counting that we all live in different timezone. The best and favored way to report issues is in the GitHub issue tracker. Thanks.

**Comment by TurboGit** [comment]
I'll assign this to me to fix.

**Comment by TurboGit** [comment]
Actually nothing to fix. The reject button was already working like this in 2.6. It is not a toggle, if you reject an image to restore it either `ctrl-z` or click on any star. So @Nilvus  what is the bug really ? Or is that a new feature request ?

**Comment by TurboGit** [comment]
Or maybe you when un-rejecting an image you want it to get the number of stars as set at import time?

**Comment by Nilvus** [comment]
@TurboGit: no, I just want to cancel a rejected image just by clicking again on the red cross. That was working on all previous release like that, from 2.4.x to master just several days ago. I've seen that nothing has been changed recently, except working on overlays/lighttable, so probably from that. The behavior is really not the same.

Just few days ago, on master, and to be sure I'm clear, when having an image rejected (so with the red cross, just clicking on this red cross, remove the red cross and put back the image as a not rejected state. Images tested doesn't have stars applied. I don't apply stars before having selected images I want to reject.

And as said on last post, darktable react if using filter as if image was not anymore rejected but stays on rejected state anyway (try preview mode when on rejected only filter mode on lighttable.

I've also check the xmp and rating stay at -1 state. When clicking red cross is should come back to 0 state.

Last thing, this day on devel mailing list, a user point that same issue.

**Comment by TurboGit** [comment]
> That was working on all previous release like that, from 2.4.x to master just several days ago.

I just tried on 2.6 and it was not working for me.

Anyway, see #4779.

**Comment by TurboGit** [comment]
I think I have fixed both issues in my PR.

**Comment by Nilvus** [comment]
> I just tried on 2.6 and it was not working for me.
> 
> Anyway, see #4779.

Maybe but I really always cancel reject images by clicking again on the cross, and that was working. So if it was not there (and another user point same thing as said), that's quite  really strange. Or maybe it was just something like old gtk widget (before last overlays rework by @AlicVB) as something to do that clicking on red cross could activate left star? That sounds strange but why not...

I've just tested on 69746a9c25f1ead82d6dea571702929ce8deffed commit and I can cancel a rejected image by clicking on the red cross. So I confirm it was working just few days ago. It's since this commit that this possibility has been broken.

Will test your PR ASAP. Thanks

**Comment by Nilvus** [comment]
I check before testing your PR which commit change that behavior.

**Comment by AlicVB** [comment]
@Nilvus : I think it's a typo from 3ee54369557fcefe8cec1ceb6bbe8b27b5ef9c22. I'll test that tomorrow if @TurboGit don't do it before ;)

**Comment by phweyland** [comment]
The toggle stuff is made in dt_ratings_apply_on_image() and controlled by the setting "rating_one_double_tap"

**Comment by AlicVB** [comment]
@phweyland : yes I know, I just think that at `ratings.c:168` we need to use `new_rating` and not `rating`. That's why I think it's a typo (sadly, I'm working on other cpu hungry things currently and can't test/build)

**Comment by phweyland** [comment]
> I just think that at ratings.c:168 we need to use new_rating and not rating.

Yes, you are right ! I may have messed that .... 

> That's why I think it's a typo (sadly, I'm working on other cpu hungry things currently and can't test/build)

I'll do the change.

**Comment by Nilvus** [comment]
@TurboGit, @AlicVB and @phweyland: thanks for your time and work to help solve this issue.
