### ISSUE TITLE
'windows' OS not listed in german manual

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#4766]
Just found out that windows is missing in the list of supportes operating systems in the manual (lines 354,355 in de.po).
Tried to fix it in github, but the file is too big for the editor in the github website and I don't have any idea how to update this file.

**Comment by johnny-bit** [comment]
user manual got removed from tree. now usermanual project lives in https://github.com/darktable-org/dtdocs with translation workflow being worked on.
