### ISSUE TITLE
Blend Mode Difference doesn't appear to be working.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4767]
darktable-3.1.0+1171~gac96b9100-win64
I used to make changes to sharpness using contrast equalizer and used to use the blend mode difference to see the impact of the change. I currently am seeing a lot of impact but not much or anything in the difference blend mode.

**Comment by johnny-bit** [comment]
Cannot replicate. Difference mode always worked for me... I even tried with 3.2.1 - same thing. Difference mode works perfectly fine.

I'll close to not pollute issue space if you don't mind. If you still have problems with difference mode, just comment and I'll reopen.
