### ISSUE TITLE
Imported folder and double clicking new image just crashes DT

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4773]
darktable-3.1.0+1266~g737735db9-win64

Imported pictures from an already imported folder as I added new one.

After import, double clicking on a new image just makes DT disappear.

Previously seen this when memory allocated is not freed corectly.

**Comment by phweyland** [comment]
I've tried with or without xmp but I cannot reproduce this.
debian 10 - dt 3.1.0+1272~g870c57446

**Comment by chhil** [comment]
dartable.exe -d all output attached (crashes every time, currently unusable). Building the latest , will check if that works, but seeing the changes , I very much doubt it.
Prior to this dev build the other ones had issues with freezing and have previously opened other tickets.

[darktable-log.txt](https://github.com/darktable-org/darktable/files/4507399/darktable-log.txt)

**Comment by chhil** [comment]
Someone with windows should look into this issue.

darktable-3.1.0+1275~g3b45ba4f2-win64
Clean install (no db etc). Imported images with xmps. Double click an imported image, window disappears and no backtrace.
Clean install (no db etc). Imported images without xmps. Double click an imported image, window disappears and no backtrace.

Going back to the last stable version I had on windows. Can use dt again.
darktable-3.1.0+1171~gac96b9100-win64

**Comment by ptilopteri** [comment]
@chhil 
I suppose it is not possible to *only* import the single added photo

crash is still inexcusable but perhaps better workflow.

**Comment by chhil** [comment]
@ptilopteri I added a comment just at the same time as you. It doesn't matter , any image will cause it to crash.

**Comment by chhil** [comment]
https://github.com/darktable-org/darktable/issues/4786

@dtorop Could you take a look at it?

**Comment by phweyland** [comment]
Just built master under windows 10. It crashes also when I edit whatever image.
no backtrace.

**Comment by Mark-64** [comment]
see #4786

**Comment by chhil** [comment]
@phweyland , if possible, could you just look at the instances of g_free and free in 
https://github.com/darktable-org/darktable/commit/737735db94617468392fd76d109741a1a530e034

(histogram diff is large and will need to be clicked to see the free(..)

**Comment by jenshannoschwalm** [comment]
which free are you referencing? The diff has 2 correct g_free ...

**Comment by chhil** [comment]
Built and installed darktable-3.1.0+1275~g3b45ba4f2-win64

Did not fix it for me, still crashes :(

**Comment by chhil** [comment]
Did a fresh clean build darktable-3.1.0+1281~g3d20b4720-win64

The problem does not exist anymore.
