### ISSUE TITLE
Ecrasement du Pré-réglage Profil de couleur d'entrée

### ISSUE THREAD

**Issue by EMAR31** [darktable-org/darktable#4777]
Bonjour,
J'ai créé plusieurs pré-réglages dans darktable. Lorsque je crée un clone de mon image et que j'ouvre la chambre noire pour ce clone, j'ai systématiquement deux instances pour le module Profil de couleur d'entrée qui s'appliquent : la première est celle de mon pré-réglage (profil d'entrée RVB Rec2020 linéaire) et la seconde cellei du système à l'installation de DT (profil d'entrée RVB Rec709 linéaire). Pour récupérer mon pré-réglage, je dois activer Réinitialiser les paramètres sur cette seconde instance.
C'est dommage d'avoir un pré-réglage et de devoir corriger sur chaque photo.
C'est le seul pré-réglage qui cause ce problème.  Et je n'ai qu'un pré-réglage pour ce module.
Je souhaite ne voir qu'une seule instance du module avec les valeurs de mon pré-réglage (profil d'entrée RVB Rec2020 linéaire).
En vous remerciant de votre réponse
Cordialement
![Pb-profil entree](https://user-images.githubusercontent.com/63604014/79752608-e606a080-8314-11ea-9e11-de409a133f34.jpg)
![Capture](https://user-images.githubusercontent.com/63604014/79752622-eacb5480-8314-11ea-88df-ba706af0db62.JPG)

Platform :

    Darktable Version: 3.0.2
    OS: Windows10
    OpenCL activated
    NVIDIA GEForce GTX 950M pilote 23.21.13.8873]

**Comment by Nilvus** [comment]
Salut, J'ai eu ce problème et ça ne venait pas du code darktable mais d'un réglage oublié. Déjà, vérifie  quel profil ton pré-réglage par défaut affiche. J'irais même plus loin : supprime-le et recrée ton profil par défaut (avec application automatique avec toutes tes images) avec le profil que tu veux.

Si tu as un simple problème de ce genre (souvent lié à un pré-réglage, commence par le forum darktable.fr). Si c'est un vrai bug (je sais pas toujours simple de savoir si ça en est un ou non ; dans le doute commence par le forum et on te dira si ça vaut le coup de poster sur Github).

Après, je sais qu'Aurélien a précisé que c'était possible de poster ici en français. Mais idéalement, utiliser le site web deepl pour la traduction automatique en anglais et la poster ici serait un plus (si c'est un vrai bug) et on peut corriger/aider si besoin.

**Comment by EMAR31** [comment]
Bonjour,
Mon pré-réglage par défaut affiche profil d'entrée RVB Rec2020 linéaire. C'est ce qui est restauré quand je clique Paramètres par défaut sur la ligne RVB Rec709 linéaire. J'ai supprimé et recréé le paramétrage RVB Rec2020 linéaire (avec application automatique sur toutes images RAW) . Dans l'écran des pré-réglages, il est seul (voir copie d'écran dans ma demande.) J'ai toujours le même pb avec la version DT 3.0.2  sur de nouvelles collections importées ainsi que sur des clones.
Je ne vois pas dans quel fichier DT se trouve ce paramétrage automatique Profil d'entrée RVB Rec709 linéaire. Donc je ne peux même pas le supprimer. Je n'ai pas de répertoire DT IN ou OUT.
**Quant au forum darktable.fr,  j'y ai posé en 1er ma demande !** J'ai même eu la réponse d'Alain Wasniewski : "Je constate le même (dys?)fonctionnement. J'étais persuadé que par défaut de profil de travail était RVB Rec 2020 linéaire, comme conseillé par Aurélien, et je n'avais pas vérifié.
Or, par défaut, c'est Rec 709 chez moi. Pour pallier ce problème, j'ai donc classiquement créé un pré-réglage 2020 auto qui s"applique à toutes les photos importées, et qui apparait en plus du Rec 709 dans l'historique. Si je compresse l'historique, il ne reste qu'un seul profil d'entrée, le Rec 709.
Si je clique sur "réinitialiser les paramètres", le 2020 est alors pris en compte sur le seul profil présent dans l'historique."
Et vous avez répondu (Nicoauffray)  : "C'est peut-être lié aussi à un bug connu (mais qui n'affecte pas tout le monde, tout le temps à priori) où certains presets ne sont pas appliqués correctement. Un correctif vient d'être proposé et ne devrait pas tarder à arriver en version de développement."
C'était sur la version DT 3.0.1. Je constate sur la nouvelle version le même pb. 
Donc je ne comprends pas pourquoi ma demande sur Github n'est pas valide.
Je ferai attention à l'avenir pour traduire mes éventuelles demandes en anglais. Trop tard pour celle que j'ai ouverte il y a quelques jours (bug récurrent sur zoom d'image).
Cordialement

**Comment by EMAR31** [comment]
Bonjour,
Mon pré-réglage par défaut affiche profil d'entrée RVB Rec2020 linéaire. 
C'est ce qui est restauré quand je clique Paramètres par défaut sur la 
ligne RVB Rec709 linéaire. J'ai supprimé et recréé le paramétrage RVB 
Rec2020 linéaire (avec application automatique sur toutes images RAW) . 
Dans l'écran des pré-réglages, il est seul (voir copie d'écran dans ma 
demande.) J'ai toujours le même pb avec la version DT 3.0.2 sur de 
nouvelles collections importées ainsi que sur des clones.
Je ne vois pas dans quel fichier DT se trouve ce paramétrage automatique 
Profil d'entrée RVB Rec709 linéaire. Donc je ne peux même pas le 
supprimer. Je n'ai pas de répertoire DT IN ou OUT.
*Quant au forum darktable.fr, j'y ai posé en 1er ma demande !* J'ai même 
eu la réponse d'Alain Wasniewski : "Je constate le même 
(dys?)fonctionnement. J'étais persuadé que par défaut de profil de 
travail était RVB Rec 2020 linéaire, comme conseillé par Aurélien, et je 
n'avais pas vérifié.
Or, par défaut, c'est Rec 709 chez moi. Pour pallier ce problème, j'ai 
donc classiquement créé un pré-réglage 2020 auto qui s"applique à toutes 
les photos importées, et qui apparait en plus du Rec 709 dans 
l'historique. Si je compresse l'historique, il ne reste qu'un seul 
profil d'entrée, le Rec 709.
Si je clique sur "réinitialiser les paramètres", le 2020 est alors pris 
en compte sur le seul profil présent dans l'historique."
Et vous avez répondu (Nicoauffray) : "C'est peut-être lié aussi à un bug 
connu (mais qui n'affecte pas tout le monde, tout le temps à priori) où 
certains presets ne sont pas appliqués correctement. Un correctif vient 
d'être proposé et ne devrait pas tarder à arriver en version de 
développement."
C'était sur la version DT 3.0.1. Je constate sur la nouvelle version le 
même pb.
Donc je ne comprends pas pourquoi ma demande sur Github n'est pas valide.
Je ferai attention à l'avenir pour traduire mes éventuelles demandes en 
anglais. Trop tard pour celle que j'ai ouverte il y a quelques jours 
(bug récurrent sur zoom d'image).
Cordialement
Élisabeth Mari

Le 03/05/2020 à 21:58, Nicolas Auffray a écrit :

**Comment by Nilvus** [comment]
Je n'ai jamais dit que la demande n'était pas valable. Quand à ce qui a été mis sur le forum, navré mais je ne retiens pas tous les sujets que je vois et réponses que j'y mets. Si j'avais précisé qu'un correctif était prévu (je ne me souviens pas quand c'était), c'est qu'il était déjà là et a sûrement été diffusé. Après, ça ne veut pas dire qu'il a été intégré en 3.0.2.

Par ailleurs, si je reprends le sujet, Alain a précisé avoir résolu le problème de cette manière :+1: 
"Si je clique sur "réinitialiser les paramètres", le 2020 est alors pris en compte sur le seul profil présent dans l'historique."

Réinitialiser les paramètres est le bouton correspondant sur le module profil couleur d'entrée. D'après lui, ça résout le problème pour les images suivantes. En attendant.

Et je confirme que ce bug est normalement corrigé mais non intégré en 3.0.2 : #4745

@TurboGit: on est en français ici (voir vidéo sur les hautes lumières d'Aurélien !) mais, sauf erreur de ma part, c'est la PR #4745 qui corrige ce module. Peux-tu me confirmer que je ne fais pas d'erreur ? Si ok, je suggère que cette PR soit ajoutée à la branche 3.0.x pour intégration en 3.0.3 'il y en a une plutôt que d'attendre la version majeure à la fin de l'année. Qu'en pense-tu ?

**Comment by TurboGit** [comment]
@Nilvus : Oui presque certain que le fix est #4745. Il n'est pas dans la branche, je viens de l'intégrer (pas simple car en conflit, j'espère ne pas avoir fait de bêtise!) donc ce problème sera corrigé en 3.0.3.

**Comment by TurboGit** [comment]
For reference commit is : 5ac2260e3527491d225870371d44fba2e8bf6d3c

And I'm now closing.

**Comment by bm10440** [comment]
On my 2 computers, with the same configuration, the issue is linked to a **.XMP** file in the directory of the picture. This  **.XMP** file has been created by Photoshop, and is not a darktable file.
For instance, files are DSCF4140.RAF and DSCF4140.xmp.
I there was a darktable file, it would be named DSCF4140.RAF.xmp
When I remove this file, there is no problem left.
I don't use any darktable .xmp file, using the library.db
For more explanations, see https://forums.darktable.fr/showthread.php?tid=5345, answer from bm10.
Regards
Bruno
Environment : W10, darktable 3.8
