### ISSUE TITLE
Snapshot is activated on a newly open in DR photo, showing the previous photo edit with the split screen on

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4780]
The Snapshot feature goes crazy if you dont reset it then switch picture !

I think its a regression.

1 Open a picture
2 process it
3 use the Snapshot feature, compare the before and after
4 exit Darkroom BUT DONT quit the Snapshot mode (dont reset it, still have the split feature open)
5. Go edit another picture
VOILA : Issue : the new picture opens with a split screen (which you can slide) showing half the previously edited photo, half the new one.
The snapshot history of the new photo also shows the last edited photo snapshot !

![image](https://user-images.githubusercontent.com/3989573/79794249-3c460480-8352-11ea-983c-9929e08ce624.png)

I hope the test case if clear enough.
I do reproduce consistently on any pics.

If I go back to the initially edited photo and reset the snapshot or reset it when in the newly edited picture : everything gets back to normal.

I tested with JPEG pictures ... (never had this issue before darktable_3.1.0~git1232.291c34822_amd64.deb ... I dont try every version tbh)

Linux Ubuntu 19.10
Darktable 3.1.0~git1266.737735db9
OpenCL : yes
Intel Core i7 7700k + 32GB RAM + NVidia GFX 1070 using NVidia Linux-x86_64 430.50 drivers

GLLM

**Comment by elstoc** [comment]
I don't see this as a problem - afaik snapshots has always been like this. It's certainly like this in 3.0.x. The snapshot module is very useful for comparing edits of different images (or more often duplicate versions of the same image) - in fact it's the only reasonable quality way to do this (the duplicate module has aliasing issues).

> If I go back to the initially edited photo and reset the snapshot or reset it when in the newly edited picture : everything gets back to normal.

You don't even have to do that. Just reset module parameters or switch the snapshot off.

**Comment by GLLM** [comment]
Hi @elstoc 
I find it counter intuitive (not trying to start a fight with AurelienPierre on intuitivity :-D) ... but let's say it's not counter-intruitive, i.e. expected and easy to understand !

Then I'd like to object that I'm really not sure how the user may understand his retouch history
![image](https://user-images.githubusercontent.com/3989573/79948571-642d8900-8474-11ea-9a4b-be192b9cec6d.png)

As it mixed elements from the picture he is currently editing (expected) and others from the edit he was performing beforehand (in red on the screenshot).
At least, having an indication it relates to another pic would be helping :

![image](https://user-images.githubusercontent.com/3989573/79948785-cb4b3d80-8474-11ea-8768-6358d2601de5.png)


JUst my 2 cents.

**Comment by elstoc** [comment]
> I find it counter intuitive

I don't disagree with you here, but it is _useful_, so I don't really want it to be removed.

> At least, having an indication it relates to another pic would be helping

Agree with this, though I'm not sure it's worth explicitly putting the image name in the description (mainly because the primary use case for this is different edits on duplicates of the same raw - which would both have the same name). Perhaps some simple visual indicator that it's not a snapshot of the current image.

**Comment by spaceChRiS** [comment]
> Agree with this, though I'm not sure it's worth explicitly putting the image name in the description (mainly because the primary use case for this is different edits on duplicates of the same raw - which would both have the same name). Perhaps some simple visual indicator that it's not a snapshot of the current image.

Maybe together with a hover message that reveals the origin of the snapshot, e.g. path+filename+version string or version number, but skipping the first two if it is the same raw but different version?

**Comment by elstoc** [comment]
It would be good to have some sort of visual indication on the snapshot module gui as well. Perhaps an asterisk would be enough?

**Comment by GLLM** [comment]
I think
* the asterisk on the module
and
*more details (path/filename/version) as a tooltip when hovering over the snaphot would be a great balance !

cheers !
