### ISSUE TITLE
Export different than lighttable and darkroom

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [darktable-org/darktable#4783]
So, I'm trying to remove some "objects" from a image with Retouch module and everything seems ok, but when the image is exported, the "objects" reappears:

Without retouch:

![image](https://user-images.githubusercontent.com/47254894/79811913-b2943800-834d-11ea-9b62-684922c74d38.png)

With Retouch:

![image](https://user-images.githubusercontent.com/47254894/79811939-c93a8f00-834d-11ea-94c7-5ec418e4c756.png)

And here's the exported result:

![_MG_9329](https://user-images.githubusercontent.com/47254894/79812083-36e6bb00-834e-11ea-9fc6-6017dff68acc.jpg)

OS: Windows 10
DT: 3.1.0+1238~gc2f39615d-dirty
GTX1060, OpenCL enabled

Here's the raw and xmp:
https://drive.google.com/file/d/1FlkpTfsOIniC5AWMCcfSP_S5P3xi9G2h/view?usp=sharing

**Comment by TurboGit** [comment]
The same issue happens in the dr if zooming. I suppose this is scale dependent. The area in the top-right is set on a specific scale in the module. This looks wrong to me, I suppose you want this healing to be do on main image. Also for such a large area with string light it does not seems like the heal tool is the best. Using the clone one gives better result. Here is my XMP,  it still needs some work on the area to smooth things (keep your XMP safe, this is only having retouch):

[_MG_9329_01.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/4514493/_MG_9329_01.CR2.xmp.txt)


Anyway, not a dt issue, a limitation sure but not a bug.

**Comment by ItaloCunhaBueno** [comment]
Thank you for verifying. this is not the first time I report an "issue" that in the end was related to divergences in the preview scale and not a bug.
I would sugest to add an indicator of some sort in modules that have such behavior, possibly an icon along it's module name?

Thanks again.

**Comment by ItaloCunhaBueno** [comment]
Closed as it it's not a "bug" but a scale perception issue
