### ISSUE TITLE
finished Slideshow keeps CPU active

### ISSUE THREAD

**Issue by ohms-law** [darktable-org/darktable#4784]
With the last picture of the slideshow, CPU load remains at a certain increased level even though the slideshow has stopped. That CPU load remains where it is even when you return to lighttable.

To reproduce open Ksysguard, top or similar tools and watch the darktable process.

1. lighttable at idle -> basically no CPU load
2. start slideshow -> increased CPU load
3. last picture of slideshow -> CPU load almost constant and higher than 1.
4. return to lighttable -> CPU load remains like 3. or fluctuates lightly but not like idle

The amount of remaining CPU load is less pronounced on my desktop machine (AMD 2700X residual CPU load approx 25%) in comparison to my older notebook (older I7 residual CPU load 68-76%).
  
Happens on 2 different machines running 3.0.1 (one Ubuntu 18.04.4 dt from OBS and one Tumbleweed  from TW Repo)

**Comment by TurboGit** [comment]
Should be fixed now.
