### ISSUE TITLE
dt 3.0.1, strange module instance behavior (preset after drawn mask)

### ISSUE THREAD

**Issue by fraf0** [darktable-org/darktable#4785]
Hi,

I think I have found a bug in dt 3.0.1 with select a preset after having add a drawn mask.
I found it with color zone module but I'm able to reproduce it also with others (like sharpen, using a personal preset).

Here the way to reproduce (I make it twice, removing the file and deleting the xmp between try):
0. Working on and CR2 raw file (Canon 6D Mark II)
1. Select color zone module
2. Add a drawn mask (path) and drawn it.
3. Invert the mask (at path level): I think this is out of interest.
4. Select the preset "black and white film": This action reset the "mask" parameter for the module (I think this was not the case with older version).
5. Re-select "drawn mask", at this moment, no drawn mask is used by the module.
6. In the "drawn mask" list, the path drawn at step 2 is in the list and associated with the actual module (see attached screenshot with place spotted by red lines).
At this moment, I can re-select the path and use the module as usual.

![Screenshot - all screen](https://user-images.githubusercontent.com/15234442/79864519-e321b380-83d9-11ea-8b76-fc439301dd54.png)

If I redo the same steps, (add a drawn mask and after select a preset) 

dt seems to create a new instance each time. This is visible in the "mask manager" zone (see second screenshot).

![Screenshot - mask manager](https://user-images.githubusercontent.com/15234442/79864527-e87efe00-83d9-11ea-81f9-0fb5a9823820.png)

Here the xmp associate file:
[_MG_2771.CR2.xmp.zip](https://github.com/darktable-org/darktable/files/4509860/_MG_2771.CR2.xmp.zip)

 - Darktable Version: 3.0.1
 - OS: Linux Debian 10

$ darktable --version
this is darktable 3.0.1
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
$ 

00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

I hope to having correctly inform you, do not hesitate to ask more information or trace.
regards, Fabrice.

**Comment by johnny-bit** [comment]
So... I wanted to check it and...

in steps 1-4: it is "normal" that preset kills masking - there's a FR #7586 that would deal with problem of masking in presets if implemented.
in steps 5-6: indeed this seems to create new group in mask manager since effectively adding preset resets module without really reseting it...

Ultimately I think that mask work in scope of 7586 would deal with both mentioned problems, so I'm going to preemptively close this issue. (also - devs might be hesitant to look at it since it mentions dt 3.0.1 and we're a bit over a month away from 3.6 release :) )
