### ISSUE TITLE
PR #4768 (RGB parade) crashes DT when entering darkroom under Windows 10

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4786]
Commit 737735db94617468392fd76d109741a1a530e034 from PR #4768 makes DT crash when opening any image in darkroom under Windows 10.
attached the backtrace log
[gdb.txt](https://github.com/darktable-org/darktable/files/4510010/gdb.txt)

**Comment by GrahamByrnes** [comment]
Ah, not just me... I was about to blame it on inkscape...

**Comment by GrahamByrnes** [comment]
Works :-)

**Comment by Mark-64** [comment]
fixed
