### ISSUE TITLE
groups are going crazy

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#4791]
**Describe the bug**

The group collapsing / expanding can go crazy

**To Reproduce**
1. Go to lighttable
2. Select a collection with 3 pictures
3. Select the 3 pictures and group them
4. Activate the grouped view (big G on top-right of lt)
5. Click on the G of the group leader (should be first pict num = group num) , all ok the image are 
ungrouped
6. Click again on the G of the group leader (should be first pict num = group num) , all ok the image are grouped (repeat 5 & 6 all is ok)
7. Click on G if needed to ungroup the 3 images
8. Now, click on G of second image, it changes the group leader and only 2 images are grouped, see that group number is changed in "image information".
9. It seems impossible at this stage to have all 3 images grouped together except by toggling off the grouped view and enabling it back. 

**Expected behavior**

Do nothing when clicking on G of non group leader ?
Or as of today change the group leader, but ensure the collapsing occurs properly ?

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian
 - 
 - 

**Additional context**

**Comment by TurboGit** [comment]
@AlicVB : probably a side effect the lt rewrite.

**Comment by phweyland** [comment]
Trying the scenario I get something a bit different but still faulty at the end.

Until 4 I'm following and it's ok.
5, click on G of the leader expands the group but images are still grouped (doesn't ungroup)
6, click on G of the leader collapses the group (doesn't group the images)
7, => expands the group (doesn't ungroup)
8, click on the second image just changes the group leader for that image keeping the group of 3.
9, click again on G of the second image, the third one collapses while exiting the group and the first one still in the group doesn't collapse anymore.

**Comment by phweyland** [comment]
My understanding is the following.
When one clicks on G to change the current leader, the new groupid is set on the images of the group but not on the thumbnails.
The second click on G of the same image (collapse) makes the other thumbnails of the group disappear.
The third click on G (expand) recreates the previously missing thumbnails with the right groupid but the leader thumbnail has still the old one. This messes up the display of group borders.

If that's correct, dt_grouping_change_representative() should be followed by the update of the thumbnails' groupid.
Does that make sense ?
