### ISSUE TITLE
Super tiny font for lua print messages

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4794]
DT git master on Windows 10, HiDPI display.
Recently the GUI messages made with dt.print() in lua scripts are displayed with super small font.
Until few weeks ago it was normal.
Might be a problem of the new LT or CSS.

To reproduce: 

- put in your luarc file `require "examples/hello_world"` 
- launch Darktable
- see the tiny font

![Cattura25](https://user-images.githubusercontent.com/43290988/80026381-5b739c00-84e2-11ea-82be-6b48dae5f5b7.JPG)

**Comment by Nilvus** [comment]
Indeed, that the log message (so not only lua but loading image, working..., etc. messages). CSS part used for this is at the end of darktable.css file. I didn't see that font size was static, not a good thing.

As I have lodpi screen and not a so big screen and small fonts on the UI like you, and before posting a CSS fix (already done on my side and quite simple), could you just test what you have if you change font-size on #log-msg tag from 14px to 1em?

**Comment by Mark-64** [comment]
It looks OK with the change, thanks!

**Comment by Nilvus** [comment]
Thanks for your feedback. I will soon post a PR but with other things to do like actual preferences rework and a new issue about red reject icon posted by @TurboGit
