### ISSUE TITLE
New created instance of the module in "active modules" tab not shown because deactivated by default

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#4796]
**Describe the bug**

If you reorganize the modules in the "active modules" tab and create a new instance there, new instance is not displayed because it is disabled by default. 

You need to go to the tab where the new instance was created and enable it there to be displayed in the "active modules" tab. 

**To Reproduce**

1. Go to "active modules" tab.
2. Select an active module and click on "new instance" from the menu.  New instance of the module is not shown in the "active modules" tab and there is no indicator that a new instance was created.
3. Go to the tab where this module is normally located. There you will find a new instance that is shown as disabled. 
4. Activate it.
5. Go back to "active modules" tab. New instance of the module is now shown there.

**Expected behavior**

If you create a new instance, this implies that you are done with old one and want to continue working with new one. Accordingly, it would make sense to make the new instance active by default.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master (3.1.0~git1282.615016be4)
 - OS: Kubuntu 18.04
 - OpenCL activated
 - GeForce GTX 1070, 

**Additional context**

**Comment by jade-nl** [comment]
I can reproduce this issue using:

* darktable version: 3.1.0+1309
* OS               : Linux - kernel 5.4.0-0.bpo.4-amd64
* Distro           : Debian Buster (rel. 10.3)

I also checked the latest stable version and that one **works as expected**: New instance is immediately shown and activated in the active module tab
* darktable version: 3.0.2

**Comment by johnny-bit** [comment]
The issue is still present on current master (3.1.0+1795~g0c7527f8c)

I tried to isolate the issue at first but it's problematic. First - the `dt_iop_gui_duplicate` doesn't seem to be changed that much to cause module not to be enabled after duplication... So the issue comes from another part of code.

**Comment by johnny-bit** [comment]
I've bisected the issue, it's caused by:
fc92a41e28e140dc42bf951d674d4194468af1f7 is the first bad commit
```
commit fc92a41e28e140dc42bf951d674d4194468af1f7
Author: elstoc <elstoc@users.noreply.github.com>
Date:   Sat Mar 21 10:05:17 2020 +0000

    prevent toast message appearing when creating new module instance (#4507)

 src/develop/imageop.c | 3 +++
 1 file changed, 3 insertions(+)
```

I'll fix that in a jiffy
