### ISSUE TITLE
Tagging module : "attached tags view" minor issue

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4810]
Hello there

First of all thank you for the work. DT is evolving rapidly in many aspects. Among these I'm particularly sensitive to the work done on tagging and metadata.

**Context**

"attached tags view" displays the attached tags of selected images (if no image mouse hovered) **or** those of the hovered image. [Source : [DT manual](https://darktable.gitlab.io/doc/en/tagging.html)]

**The issue:**
Indicators are displayed at the left  of the tags when an image is hovered.

**Expected behavior**
No indicator should be displayed when hovered image tags are displayed. If any it should be the check-mark since the tag is attached to all (=1) hovered images.

Furthemore, **no indicator at all** when hovering an image would make things **much more clear** about if the display is of selected or hovered image(s)

**Platform**
 - Darktable 3.0.2 on Windows 8.1

Thank you for listening

**Comment by phweyland** [comment]
> Indicators are displayed at the left of the tags when an image is hovered.

I cannot reproduce this.

**Comment by phweyland** [comment]
I've removed the indicator in attached view when hovered image or unique selected one.

**Comment by sjjh** [comment]
@phweyland can this get closed as well? Might you? :)

**Comment by phweyland** [comment]
yes, this one can be closed too.
