### ISSUE TITLE
Tagging module : "attached tags view" minor improvement request

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4811]
Hi everybody

When severals images are selected and no one mouse  hovered :  

if a given tag is applied to  one image only please add (1) at its right (for the sake of consistency with the other tags and with the dictionnary view)

Thank you for listening

DT 3.0.2 on windows 8.1

**Comment by phweyland** [comment]
I did hide the number if 1. Probably a mistake.

**Comment by phweyland** [comment]
In attached view, I skip the 1 because it doesn't bring any information.
It is also coherent with attached symbol not shown when hovered image or unique selected one.

**Comment by johnny-bit** [comment]
I do agree with phweyland here... please comment if you have a solid workflow where that info would be worthwhile to have, I'll then re-open and we can discuss how to best approach requested changes.
