### ISSUE TITLE
Tagging module : creating tag with "text entry" improvement request

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4812]
Hello,

Please allow user to create tag by the mean of  the "text entry" **even if no image is selected**.
This is the fastest way of creating one and as it is it is quite frustrating !

Thank you for listening

DT 3.0.2 on windows  8.1

**Comment by phweyland** [comment]
I agree this frustrating.

**Comment by phweyland** [comment]
Done

**Comment by TurboGit** [comment]
Closing now.
