### ISSUE TITLE
Tagging module request : more consistency within tag creation

### ISSUE THREAD

**Issue by GwenaelQ** [darktable-org/darktable#4813]
Hello,

**Context** 
Pipe caracter is used to create hierarchical tags

**Issue**
Creating a tag with a pipe (that is to say a "path") is allowed within entry zone.
The same is not allowed with  the "create tag" command of dictionary view  !

**Expected behavior**
Both ways should be equivalent and allow the creation of a hierarchical tag

Thank you for listening. Keep the good work.

DT 3.0.2 on windows 8.1

**Comment by phweyland** [comment]
> Creating a tag with a pipe (that is to say a "path") is allowed within entry zone.
> The same is not allowed with the "create tag" command of dictionary view !

"entry zone" defines a full tag (with its full path).
"create tag" creates a tag on top of an existing one.
They cannot be equivalent.

This said, I agree that "create tag" could include a subpath (on top of the current one) and then allow the pipe character.

**Comment by phweyland** [comment]
Done

**Comment by sjjh** [comment]
@phweyland  this issue can be closed, can't it? Might you? :)

**Comment by phweyland** [comment]
> this issue can be closed, can't it? Might you? :)

yes, agreed.
