### ISSUE TITLE
Panasonic DC-FZ10002

### ISSUE THREAD

**Issue by mbollmann** [darktable-org/darktable#4824]
A CC0 sample has already been provided on raw.pixls.us by someone else.

Note that unlike other Panasonic cameras, the DC-FZ10002 does **not** crop RAW images in different aspect ratios. I've verified this myself, as I saw that there is only a 3:2 file on raw.pixls.us and wanted to provide the other aspect ratios, but even when I shot pictures in different crops, the RAW files all came out in 3:2 ratio.

**Comment by mbollmann** [comment]
I got this to work locally by cloning the values from the DMC-FZ1000 (which Panasonic claims to have the same sensor) and my camera's RAW files appear fine now when opening them.

Would you like me to open PRs here and for rawspeed? Or should I rather double-check the values against the sample file in raw.pixls.us?

**Comment by LebedevRI** [comment]
> Would you like me to open PRs here and for rawspeed?

Feel free to, yes. At worst i'll just fine-tune them after merging.

**Comment by LebedevRI** [comment]
Thanks, those look good, will wrap up a few more camera support issues and push tomorrow.

**Comment by gaetrua** [comment]
Hi, i've just uploaded all crop formats to pixl.us fro this camera
