### ISSUE TITLE
"private" status is not respected for parent tags

### ISSUE THREAD

**Issue by EC1000** [darktable-org/darktable#4826]
**Describe the bug**
Parent tags that have a different "private" status compare to their child tag are incorrectly exported / not exported. 

**To Reproduce**
Set two hierarchical tags like "tag1" and "tag1|tag2". Apply "tag1|tag2" to an image. 
1. If you set "tag1" as private and "tag2" as public (=private option unticked), the exported image will have both "tag1" and "tag2": "tag1" is exported even it is set as private. 
2. If you set "tag1" as public and "tag2" as private, the exported image will have no tag, even though "tag1" is set as public.  

(in both cases, let unticked "private tags" and "omit hierarchy" in metadata configuration in export module)

**Expected behavior**
I would expect the "private" status to be respected both for child and parent tags. With the examples above, it would mean having in the exported file: 
1. only "tag2"
2. only "tag1"

I supposed the algorithm first check if the (child) tag is private or not, and then export the tag and its parent tags. I think the condition should be check for parent tags separetly. 

**Platform**
 - Darktable Version: 3.0.1 (I have not had the possibility to upgrade to 3.0.2 yet; I did search for similar issue to check if this behavior was already change but I did not find any)
 - OS: Linux Mint 19.1

**Comment by EC1000** [comment]
For case 1, a possible partial workaround is to set "tag1" as a category. Then it will not be exported (I say partial workaround, because then you cannot export it even if you choose to export private tags).

**Comment by phweyland** [comment]
> * If you set "tag1" as private and "tag2" as public (=private option unticked), the exported image will have both "tag1" and "tag2": "tag1" is exported even it is set as private.
> 
> * If you set "tag1" as public and "tag2" as private, the exported image will have no tag, even though "tag1" is set as public.

Thanks for reporting. I can reproduce this. I'll look at it.



> because then you cannot export it even if you choose to export private tags

Correct, categories are never exported.

**Comment by EC1000** [comment]
> Correct, categories are never exported.

It's a good thing! I was just stating the limit if this possible workaround (and not at all criticizing the behavior of categories).

Thanks again for all your great work on tags :)
