### ISSUE TITLE
Just a question, really...

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4830]
As part of my failed attempt to make preview_downsampling work, I butted up against this bit of code in iop/clipping.c

```
static inline void backtransform(float *x, float *o, const float *m, const float t_h, const float t_v)
{
  x[1] /= (1.0f + x[0] * t_h);
  x[0] /= (1.0f + x[1] * t_v);
  mul_mat_vec_2(m, x, o);
}

static inline void transform(float *x, float *o, const float *m, const float t_h, const float t_v)
{
  mul_mat_vec_2(m, x, o);
  o[1] *= (1.0f + o[0] * t_h);
  o[0] *= (1.0f + o[1] * t_v);
}
```
clipping applies affine geometry transformations: ie the generic transformation that I'd expect is

- subtract an offset (change of zero coordinate)
- apply a 2-D matrix rotation around the zero point
- possibly add an offset, to return to a different reference zero-point.

In the above code, `mul_mat_vec_2(m, x, o);` is simply a matrix multiplier, where in column-vector format it calculates o=mx. You could imagine that t_h and t_v would be "translation_horizontal" etc.

But the `transform` and `backtransform`  functions are weird. First, they look symmetric, but aren't, since the x[1] in the 2nd line has already been modified in the first line. Second, the backtransform is not an inverse to transform.

Since these are applied to the "points" vector passed to the dt_transform function in develop.c, they probably explain why you can easily end up with non linear transformations, ie where the border radius of a circle mask appears inside the "inner" radius. Yet they work (when_preview_downsampling=1), and if you change them for a simple translation, there are misalignment problems. They look vaguely like projective geometry transforms (but aren't).

So does anyone understand what they do?

**Comment by TurboGit** [comment]
I see what you mean and I would have the same question. To me the lines:
```
  x[1] /= (1.0f + x[0] * t_h);
  x[0] /= (1.0f + x[1] * t_v);
```
Look at first suspicious.

I would have expected something like:
```
  const float x0 = x[0];
  const float x1 = x[1];
  x[1] /= (1.0f + x0 * t_h);
  x[0] /= (1.0f + x1 * t_v);
```

And likewise in transform for o. Did you tried that ?

But without understanding properly how this works it can do more harm :)

**Comment by GrahamByrnes** [comment]
That would fix the asymmetry... but it would still be a big change to the 2D map. It seems likely it would change things.

So it would still be an issue of making random changes and hoping that they don't break things: even when they obviously do change things in the current "degenerate case" where preview_downsampling=1.

Who wrote this code? I suspect that to make any sensible headway, it would be necessary to fully understand how it works. The most disheartening thing was finding that changes manifested in completely unexpected ways, so any change could seemingly break anything :-(
It seems to me it should either be left alone, or the entire mask system re-written: a big project with the need to shut down the continuous adding of new features, and without an immediate short-term gain,

**Comment by TurboGit** [comment]
@GrahamByrnes : Of course, I was not proposing to fix that randomly, I just want to know if you had tested this and if it works better for you down-sampling project. Also not that the transform / backtransform are not going to break any past edits if I'm not mistaken, this is only used at runtime to properly adapt masks to deformations done by some iop like lens, liquify, crop&rotate, etc.

**Comment by TurboGit** [comment]
To answer your other question, the code has been created here:

4a94569932531c9e3badb630c96ca7b51c94d3ef

By Jérémy Rosen and this seems to indeed introduce a problem using a modified value, previous implementation had a single transformation (horizontal or vertical):

```
 static void
-backtransform(float *x, float *o, const float *m, const float t, const int k)
+backtransform(float *x, float *o, const float *m, const float t_h, const float t_v)
 {
-  if      (k == 0) x[0] /= (1.0f + x[1]*t);
-  else if (k == 1) x[1] /= (1.0f + x[0]*t);
+  x[1] /= (1.0f + x[0]*t_h);
+  x[0] /= (1.0f + x[1]*t_v);
   mul_mat_vec_2(m, x, o);
 }
 
 static void
-transform(float *x, float *o, const float *m, const float t, const int k)
+transform(float *x, float *o, const float *m, const float t_h, const float t_v)
 {
   float rt[] = { m[0], -m[1], -m[2], m[3]};
   mul_mat_vec_2(rt, x, o);
-  if     (k == 0) o[0] *= (1.0f + o[1]*t);
-  else if(k == 1) o[1] *= (1.0f + o[0]*t);
+  o[1] *= (1.0f + o[0]*t_h);
+  o[0] *= (1.0f + o[1]*t_v);
 }
```

**Comment by GrahamByrnes** [comment]
Oh... yes, if `t_h * t_v ==0` then it makes more sense: one line is an identity map, the other is something more like an approximate quadratic-hyperbolic transform (I think.... it's a long time since I did that stuff).

Supposing t_h>0 and t_v=0, then you get the round trip
x -> x -> x
y -> y/(1 + x t_h) -> y

That's still a weird thing to do to pixel addresses, but you do get back home!

Ok, I might have another look and see if I can work out what this is about... forget about preview_downsampling for the moment.

Do you remember any issues about weird behaviour of masks in conjuction with crop & rotate? As a place to look for a possible test...

**Comment by TurboGit** [comment]
> Do you remember any issues about weird behaviour of masks in conjuction with crop & rotate?

No and did some tests right now and all seems fine even when changing the order of crop&rotate to be before or after the iop with masks (I did test with exposure).

**Comment by GrahamByrnes** [comment]
Given the matrix in the transform functions, it should always be possible to use only one axis by rotating the coordinates first. In which case the only issue is that function is too general! I noticed in Jérémy's code the comment that "only one of t_v & t_h should be used"

So the problem was that in some cases the "points" in dt_transfom_plus & dt_backtransfom_plus were being used to transform radii... I'm not sure if I picked that up from @bastibe or I invented it myself. That would be fine under the supposition that the transform was linear... it isn't for crop & rotate, but is for most everything else. The extra code we put in there was explicitly linear and worked provided the points were loaded onto the pixel pipe at a stage where there was no affine shift before the linear deformation... although may have broken down when the zoom_scale was changed, either by clipping in crop & rotate, or zooming the image.

The challenge really was coordinating 
1. the cursor, 
2. the points passed back and forth through the pipe to define the changed pixel values
3. the preview of the points, a) before and b) after clicking on the image,
4. the relationship of the preview to the clone generated in masks.c for retouch etc

At various stages I managed to get 1, 2, and 3b sorted, and 3a so badly wrong that I couldn't see it on screen.

**Comment by bastibe** [comment]
That would explain the behaviors I was seeing, too. Radii were indeed a major pain to get working. And I do expect that some of my corrections only worked because they canceled each other out at convenient times.

(Speaking of preview_downsampling, however, I think we were going down the wrong path. Instead of using the deceptive preview_downsampling variables, we should have changed to resolution of the preview itself. It is already "downsampled", and obviously everything works with respect to its size. I *think* a different preview size would not upset anything.)

**Comment by GrahamByrnes** [comment]
@bastibe Interesting idea, even if I was just starting to begin to understand preview_downsampling... lol.
