### ISSUE TITLE
lighttable not updated when empty

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#4834]
**Describe the bug**

lighttable not updated when empty

**To Reproduce**
1. Select a collection
2. Select any filter in the top-left of the lighttable containing no images (5 stars for example)
3. As expected the lighttable is empty
4. With the mouse scroll change the filter value there will be no image displayed
5. Set a filter where you know there is some iimages (nothing displayed)
6. Click on the lighttable view, it forces a refresh and the thumbs are now displayed

What is strange is that the lighttable is refreshed correctly when changing some thumbs are displayed while change filter value.

**Expected behavior**

The lightttable is always refreshed.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Linux
 - 
 - 

**Additional context**

This is most probably due to latest lt rewrite from @AlicVB

**Comment by TurboGit** [comment]
@AlicVB : I have tried to find the fix, but it seems harder than I though. I really don't see where the refresh is missing when the lt is empty :(

**Comment by AlicVB** [comment]
@TurboGit : don't worry, I'll have a look tomorrow !

**Comment by TurboGit** [comment]
@AlicVB : I'm sure you'll be able to fix, but I'm not happy to not have been able to understand what was going on :) I'll look at your fix ! Thanks.

**Comment by TurboGit** [comment]
Hum... I'm embarrassed now... It looks like all is working fine now :( Don't know what was happening yesterday night....

**Comment by TurboGit** [comment]
Am I doomed :( ???? Now I can again reproduce this behavior... @AlicVB : can you try on your side ?

**Comment by AlicVB** [comment]
ok, I can reproduce. I needed to just scroll in the combobox without opening it (yes you write it in your step by step, maybe I need glasses...)
I'm looking at that now.

By the way, are you aware that if you set filter to >= ***** you get rejected images ? (I can try to fix it and open an issue otherwise if you want)

**Comment by TurboGit** [comment]
> By the way, are you aware that if you set filter to >= ***** you get rejected images ?

Ah no did not see that, I'll fix.

**Comment by AlicVB** [comment]
@TurboGit : just fix this issue. It was just a missing redraw : as empty window is draw in lighttable.c expose fct, we need to ensure the redrawing of the center widget...

For the issue about stars, I'm in current master. I'll have a look more deeply...

**Comment by TurboGit** [comment]
@AlicVB : Don't loose your time on the issue with stars I'm on it.
