### ISSUE TITLE
darktable-gen-noiseprofile errors

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#4837]
darktable-gen-noiseprofile stop on Phase One IIQ raw, with the errors: 

>  ===> Profile image for "Phase - P65+ - 50 ISO"
--> Converting /home/dim/Desktop/denoise/Capture28600.IIQ (ISO 50)

(darktable-cli:3328): Gtk-WARNING **: 09:30:07.585: gtk_disable_setlocale() must be called before gtk_init()
sqlite3 error: /usr/src/packages/BUILD/src/common/exif.cc:3299, function read_xmp_timestamps(), query "UPDATE main.images SET  WHERE id = 1": near "WHERE": syntax error
[exif] error writing timestamps entry for image 1
[exif]   near "WHERE": syntax error
[exif] error reading history from '/usr/lib/darktable/tools/profiling-shot.xmp'
error: can't open xmp file  /usr/lib/darktable/tools/profiling-shot.xmp

-----------------------
darktable 3.1.0~git1346.532efbf17 (download.opensuse.org)
Ubuntu studio 19.10, gtx1050ti, nvidia 435.21, opencl:on

[terminal-darktablegennoiseprofile-ful.txt](https://github.com/darktable-org/darktable/files/4545387/terminal-darktablegennoiseprofile-ful.txt)

[profiling-shot.xmp.txt](https://github.com/darktable-org/darktable/files/4545408/profiling-shot.xmp.txt)

**Comment by rawfiner** [comment]
maybe a permission issue for /usr/lib/darktable/tools/profiling-shot.xmp ?
I can't reproduce with current master
