### ISSUE TITLE
error loading sidecar file

### ISSUE THREAD

**Issue by Twin1811** [darktable-org/darktable#4841]
Hi. There is an issue loading a sidecar file which was created with another darktable version on another operating system. The sidecar file was generated on Mac OS 10.13.3 with darktable version 3.0.2 The sidecar file was loaded on a Ubuntu 18.04.4 LTS with darktable version 2.6.2 There is an error reported when the sidecar file is loaded. I could not find information about sidecar incompatabilities. Regards, Thomas

**Comment by elstoc** [comment]
I wouldn't expect sidecar files generated from v3.0.2 to be compatible with v2.6.2, though it should work fine the other way.
