### ISSUE TITLE
 basic adjustments module

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#4842]
Add power function for brightness operation and an option to roll-off the highlights for the contrast slider

**Comment by AlicVB** [comment]
Is there any reasons why you can't use dedicated modules for that ?
because imho, basic adjustments should stay really basic.
Not to say that this module has some real pipe ordering problem... I've an old PR to solve that...

**Comment by age1988** [comment]
> basic adjustments should stay really basic
That's true but the contrast slider push the values above 1,  for this reason there's need to use another module to recover the highlights.
The brightness slider shifts too much the black point.

I think the basic adjustment module with this two suggestion could be used for a fast and easier workflow

**Comment by dterrahe** [comment]
The _basic adjustments module_ was superseded by the configurable _basic widgets group_.
