### ISSUE TITLE
lighttable: A filter with ">= ★" also shows rejected files

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#4847]
**Describe the bug**

If I select ">= ★" (one star) as the filter, it also shows rejected images in the lighttable (no star at all)

![one_star_rejected](https://user-images.githubusercontent.com/545480/80513397-459d2580-897f-11ea-9f1a-655fc63549d1.png)

**Comment by TurboGit** [comment]
Which version ? I think I had fixed that yesterday.

**Comment by TurboGit** [comment]
And I cannot reproduce !

**Comment by TurboGit** [comment]
See #4834 where AlicVB could also reproduce, but I can't.... That's a really strange issue.

**Comment by TurboGit** [comment]
I think I know what is going on... The previous flags has not been migrated... Let me check.

**Comment by TurboGit** [comment]
This is now fixed, beware that the image rejected since Apr 22nd will not be rejected anymore.
