### ISSUE TITLE
Improved database lock error message

### ISSUE THREAD

**Issue by jpverrue** [darktable-org/darktable#4848]
Very regularly (about once a week), we have on our forum dedicated to darktable, a question about database lock files. More precisely this question is asked after the user has seen the small window that contains these few laconic sentences :
    darktable - error locking database
    an error has occured while trying to open the database from
    home/my-name/.config/darktable/data.db
    the database lock file contains a pid that seems to be alive in your system: 12345
    close darktable
and that this situation persists even after rebooting, without him/her understanding what he/she has to do to solve this minor problem.
To help those who are stuck on this message, I suggest to complete it in order to provide the users, first the explanations on the origin of the problem, then the actions to take to solve it simply.
Here is the text of the message as I imagined it :
                                                        >---------------------------<
darktable cannot be started because the database is locked.

At startup, the database failed to open because at least one of the two files in the database is locked.

The lock is mainly caused by one of the two following causes:
- Another occurrence of darktable has already opened this database file and locked it for its benefit.
- A previous occurrence of darktable ended abnormally and therefore could not close one or both files in the database properly.

How to solve this problem?
1 - Search in your environment if another darktable occurrence is active. If so, use there or close it. The lock indicates that the process number of this occurrence is : %d
2 - If you can't find this other occurrence, try closing your session and reopening it or shutting down your computer. This will delete all running programs and thus close the database correctly.
3 - If these two actions are not enough, it means that at least one of the two lock files remains, and that they are no longer attached to any occurrence of darktable. It is then necessary to delete it (or them). The opening mechanism signals the presence of the %s file in the %s folder. The two files are named data.db.lock and library.db.lock respectively.
Caution! Don't delete these files without first checking that there is no other occurrence of darktable, otherwise you could generate serious inconsistencies in your database.

As soon as you have identified and removed the cause of the lock, darktable will boot without any problem.
                                                      >---------------------------<
I can take care of that modification.

**Comment by Nilvus** [comment]
Hi jp, I agree with that, these too frequent questions about that without any searching are really bothering us, so it's a really great idea.

**Comment by TurboGit** [comment]
You still want to keep the full path-name somewhere as one common question is where are those file located. Apart from that, I agree.

**Comment by jpverrue** [comment]
@TurboGit In the message I just split the pathname in two parts: first the file name, then the path (...the presence of the %s file in the %s folder...). I did this to make it speak even to the most novice. I don't quite understand what you mean? Should we keep the whole pathname? Or should it be saved somewhere? Is that what you mean?

**Comment by Nilvus** [comment]
PR merged, so could be closed. And thanks @jpverrue for that. Hope will help having less message (but will be for next release to see effects.
