### ISSUE TITLE
show accels window doesn't display key-combinations I have configured

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4854]
openSUSE Tumbleweed 20200425
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable 3.1.0~git1346.532efbf17-2885.1.x86_64
OpenCL on 
i7 12-core 36GB

I have "duplicate image" configured to <insert> key
(gtk_accel_path "<Darktable>/modules/image/duplicate" "Insert")
(gtk_accel_path "<Darktable>/modules/filmstrip/duplicate image" "Insert")

works in lighttable, but not in darkroom.  It did in the past.

show accels window <H> only displays the default key-set
  <Darktable>/views/thumbtable/duplicate image virgin" "<Primary><Shift>d")
  <Darktable>/modules/image/duplicate" "<Primary>d")

which is incorrect

**Comment by AlicVB** [comment]
You're right, it's not correct, some leftover of my previous work... I'll have a look

**Comment by dterrahe** [comment]
@AlicVB was this addressed?

**Comment by johnny-bit** [comment]
Does #8078 "fix" this then by totally re-doing input system? :)

**Comment by ptilopteri** [comment]
yes it does, tks
closing issue
