### ISSUE TITLE
Canon EOS 90D

### ISSUE THREAD

**Issue by didmac** [darktable-org/darktable#4860]
Bonjour, juste savoir ouvrir mes fichiers .CR3 de mon nouveau boitier Canon EOS 90D dans darktable

merci beaucoup pour votre travail

Didier Heinen

**Comment by LebedevRI** [comment]
Please use english.
Duplicate of #4259.

**Comment by didmac** [comment]
Hi, just know how to open my .CR3 files of my new Canon EOS 90D in darktable.

thank you very much for your work

Didier Heinen
