### ISSUE TITLE
Category Tag In XMP-dc Subject in XMP sidecar file.

### ISSUE THREAD

**Issue by citizen2947294** [darktable-org/darktable#4861]
**Describe the bug**
In the manual, it says "A tag set as “category” is not exported in “XMP-dc Subject”. However it is exported in “XMP-lr Hierarchical Subject” as this XMP metadata holds the organization of your tags." However, I am seeing tags which are set as "category" in the XMP-dc Subjection section of the sidecar files. This doesn't seem to be correct. Am I correct? E.g., a section of a sample sidecar pertaining to the XMP tags (tag place was created through the right click menu with category checked):

```
   <dc:subject>
    <rdf:Bag>
     <rdf:li>Green Street</rdf:li>
     <rdf:li>place</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <lr:hierarchicalSubject>
    <rdf:Bag>
     <rdf:li>place|Green Street</rdf:li>
    </rdf:Bag>
   </lr:hierarchicalSubject>
```

**To Reproduce**
1. Create a tag with category check.
2. Create another tag inside it.
3. Check the sidecar.

**Expected behavior**
```
   <dc:subject>
    <rdf:Bag>
     <rdf:li>Green Street</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <lr:hierarchicalSubject>
    <rdf:Bag>
     <rdf:li>place|Green Street</rdf:li>
    </rdf:Bag>
   </lr:hierarchicalSubject>
```

**Platform:**
 - Darktable Version: 3.0.2
 - OS: Debian Buster

**Comment by phweyland** [comment]
> In the manual, it says "A tag set as “category” is not exported in “XMP-dc Subject”. However it is exported in “XMP-lr Hierarchical Subject” as this XMP metadata holds the organization of your tags." However, I am seeing tags which are set as "category" in the XMP-dc Subjection section of the sidecar files.

This text applies on exported tags (with exported images), and not xmp files.
The xmp file is a companion of your image and mirrors the database information. The only action you can manage here is with the configuration "omit hierarchy in the simple tag list".

So, not a bug.

**Comment by phweyland** [comment]
@elstoc I should have detected this earlier, sorry. "omit hierarchy in the simple tag list" should be put with xmp settings.

**Comment by citizen2947294** [comment]
I did realize that text applies to exported tags for exported images ('A tag set as “category” is not _exported_'). Is it not desirable to have parity between exported images and sidecars (and the database) in this regard? I also know about the "omit hierarchy in the simple tag list" checkbox and that is not what I'm trying to achieve here. Also, when importing images, how will the categories be distinguished as category without using the tag import button? They're not. When I import these images with their sidecar files into darktable with no tags defined in the tagger, these are not correctly distinguished as categories. The category attribute of a tag is not stored in the sidecar. That's why I asked if I was correct but I can elaborate. Is there a mechanism in the XMP-dc Subject and XMP-lr Hierarchical Subject tags to do this or is it beyond the scope of these XMP fields?

I also notice the private tag attribute is not exported, in the sidecars or the tag export, so it cannot be imported later and is only stored in the database.

**Comment by phweyland** [comment]
> Is it not desirable to have parity between exported images and sidecars (and the database) in this regard?

No, as said above xmp mirrors the database, means that it must be possible to rebuild the image data in database from xmp.




> Also, when importing images, how will the categories be distinguished as category without using the tag import button? They're not. 

> The category attribute of a tag is not stored in the sidecar.

> I also notice the private tag attribute is not exported,

That is absolutely correct. Private and category are attributes of tags, not of images. 
The tag dictionary is imported and exported independently for images.

**Comment by citizen2947294** [comment]
So should tag category and privacy be encoded into the sidecar? My re-imported images are not bringing this information in.

Also, again, I don't see tag privacy encoded in the tag dictionary export and it doesn't get imported either.

**Comment by citizen2947294** [comment]
Side-note, not-so-side-note: Let's not forget all the awesome stuff you all have done with this amazing application. I'm blown away with all the new features in version 3, especially with tagging, a personal favorite of mine. Thank you!!!

**Comment by phweyland** [comment]
> So should tag category and privacy be encoded into the sidecar? My re-imported images are not bringing this information in.
> 
> Also, again, I don't see tag privacy encoded in the tag dictionary export and it doesn't get imported either

I would say no. What should be imported if 2 images say the opposite ? Private ? not private ? category ? Or not ? :)
If you don't rely on the backup of your database, i.e. you are more confident with xmp files, I would suggest to save also time to time your tag dictionary (category, private, synonyms).

>  Let's not forget all the awesome stuff you all have done with this amazing application. I'm blown away with all the new features in version 3, especially with tagging, a personal favorite of mine. Thank you!!!

Thank you ! :)

**Comment by citizen2947294** [comment]
I'm looking at this again. "omit hierarchy in the simple tag list" does achieve what I was looking for for the sidecar files.
