### ISSUE TITLE
Photo not displaying - Digital snow display instead

### ISSUE THREAD

**Issue by ikoo2mi** [darktable-org/darktable#4867]
Hi everyone,

I am using Darktable 3.0.2 on windows and recently some photos don't appear normally in the lighttable - we just can see kind of TV snow. Then in the dark room a photo that was appearing normally just becomes "snow" after applying some change.

I tried to "clean" my library and re-import my photos but the problem remains. It seems that all my change are still ok, but the display is affected.

Hope I can find a solution.

Thanks in advance for any support from the community.

Best,

![Capture DT](https://user-images.githubusercontent.com/64572567/80672069-d259f780-8ad5-11ea-992a-cd8bf6920e7c.PNG)
![Capture DT2](https://user-images.githubusercontent.com/64572567/80672078-d9810580-8ad5-11ea-8fb0-8b01a3732689.PNG)

**Comment by paperdigits** [comment]
What camera? Can you share a problem raw file? Can you provide the standard bug report information?

**Comment by johnny-bit** [comment]
Lack of required info = closed. If you provide all necessary info the issue will be reopened and investigated.
