### ISSUE TITLE
Lua tab disappeared in the new options dialog

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4868]
In the new options dialog with vertical tabs, the "lua options" is no longer present (was last tab in the old layout).
Lua scripts work and Options->Shortcuts-> lua is there, but "lua option" just disappeared.

![Cattura30](https://user-images.githubusercontent.com/43290988/80675233-44214980-8ab4-11ea-9ab6-ece44a2c63a0.JPG)

DT 3.1 git master on Windows 10

**Comment by elstoc** [comment]
I'll take a look

**Comment by elstoc** [comment]
I think I've fixed it but I don't use lua so none of these options ever appeared for me. Please could you do a quick test before I submit a PR. Changes are here: https://github.com/elstoc/darktable/tree/luapref

**Comment by Mark-64** [comment]
@elstoc: Yes it works now

**Comment by elstoc** [comment]
Excellent thanks for testing @Mark-64
