### ISSUE TITLE
DT 3.0.2 - Crop and Rotate module can get into a non-functional state

### ISSUE THREAD

**Issue by pahl34** [darktable-org/darktable#4869]
Version: darktable v3.0.2
OS: Windows 10

It can happen that the **crop and rotate** module gets into a state where it is not properly usable any more. In this case, neither the direct cropping in the image using the control overlay (main tab), nor the margins tab will work. Also, neither the control overlay is displayed in this state, nor is the selected guide (e.g. "rules of thirds", which normally enables dashed lines being shown as an overlay to the image).
The only thing that still works is the angle slider. After using it to set the rotation to another value, the cropping also is enabled again.

Disabling and enabling the module completely does not resolve the problem. Collapsing and then extending the module also usually does not resolve it either - however it was observed that seemingly after longer waiting times in between the collapsing and extending, this sometimes resolves the issue.

Unfortunately, even after playing around for half an hour or so, I could not figure out a way to safely reproduce this behavior. In fact, for me it was only reproducible on one specific group of images (a RAW file and its duplicates). For other files I could not reproduce it, using the same steps, so I cannot rule out that some specific edit I did on the problematic image might have caused this.

**Side note:** I noticed that in general if another duplicate of the same image is loaded while the crop and rotate module is already extended in the right panel, then the controls will not appear after loading of the image has finished, but it is always required to collapse and then extend the crop and rotate module. This might be a separate issue on its own (not sure whether this is 'as designed' behavior) but it might also be related to the issue described here.

Due to failing to find the exact steps to reproduce, I can only try to describe what I did as precisely as possible and hope that somebody with more background knowledge (e.g. knowing the code behind this module) will be able to figure it out.

1. RAW file with two duplicates (thus, there exist images A (original), B and C (duplicates)) - various edits (on all three) had already been done in an earlier session. Among other edits, image A had a change of roation done using the crop and rotate module.
2. Created a third 'virgin' duplicate D.
3. Deactivated the Base Curve on D
4. Applied the style "Filmic Natural (dt 3.0+)" to D, downloaded from [https://dtstyle.net/](https://dtstyle.net/).
5. In lighttable, copied (only) the crop and rotate setting mentioned in 1. from A to D:
5.1 Select A
5.2 In the history stack module, "Copy" --> Deselect all --> Select only 'crop and rotate'
5.3 Select D
5.4 History stack module, "Paste" --> Ok
6. Double click D to load it inot darkroom.
7. The error was present - crop and rotate would not work (as described above).

If it helps I can provide the image and sidecar files, or create a darktable dump (if this is possible - I would need instructions for this). Feel free to ask for whatever might help.

**Comment by ptilopteri** [comment]
fwiw: I have seen same or very very similar on openSUSE Tumbleweed master builds for several years.  And I have not been able to recreate conditions to repeat the problem and have never been able to successfully change the crop w/o restarting dt.

So iianm, the issue is not new but as obscure as hen's teeth.

**Comment by elstoc** [comment]
In my experience a lot of these sort of issues tend to occur when opening new images and/or when switching between images in the darkroom. Crop & Rotate is an oddity in that it requires the module to have been allocated gui focus in order for it to function. Sometimes the module can be open without it having focus (for example immediately after you've double-clicked on the image to commit a crop). If it's not open, merely activating it will not necessarily give it focus. Sometimes this is a good thing, sometimes not.

When opening a new image or changing images, darkroom looks up the last module that had gui focus and assigns that module focus again, which can sometimes lead to crop&rotate displaying grid lines immediately on opening an image. I'm not sure whether the better (or at least more consistent) behaviour when changing/loading images might be that no module has gui focus and no module is expanded (when changing images this would mean all modules revert to their collapsed state). I'm not sure whether this would be popular though.

I did change one thing in master, though (#4517) - this will ensure that, when using keyboard shortcuts, if you collapse the module it loses focus and if you expand it will gain focus. But yes, a number of issues still remain.

**Comment by johnny-bit** [comment]
I *think* #4901 fixed this issue more or less... crap and rot is sP*eC*i**al** module that has some... weird corners for some reason... If you manage to come up with concrete way to reproduce issue that we can then trace then please open up a new issue :)
