### ISSUE TITLE
Infos line not properly refreshed

### ISSUE THREAD

**Issue by pasta-farian** [darktable-org/darktable#4872]
**Describe the bug**

I have $(STARS) in my infos line. If I change the rating I won't see the new rating in the infos line until I switch to a different pic and come back to the original one.

**To Reproduce**

1. In preferences -> GUI options -> pattern for image infos line:  add "$(STARS)"
2. go to darkroom view
3. Change rating of current picture

**Expected behavior**

You should see the number of starts changing in the infos line as you change the rating.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1
 - OS: Ubuntu 18.04.4
 -  "not available on this system"
 -  Intel® HD Graphics 530

**Additional context**

**Comment by paperdigits** [comment]
Can you try the latest release 3.0.2 and see if the problem is resolved?

**Comment by pasta-farian** [comment]
Problem still present in 3.0.2.

**Comment by johnny-bit** [comment]
The isue is present even in 3.5.0+2258 :) I think the infos line just needs to react to more events if there are dynamic elements in it.

**Comment by AndDiSa** [comment]
This fix creates a crash on duplicating or deleting an image within the duplication manager:
[  974.433070] Code: Bad RIP value.
[ 1235.707128] traps: darktable[18860] trap stack segment ip:7f1444167554 sp:7ffedb5a54c0 error:0 in libimage_infos.so[7f1444167000+1000]

**Comment by johnny-bit** [comment]
@AndDiSa - thanks, but can you create new issue? That way it's more visible than either comment on commit or on closed issue

**Comment by AlicVB** [comment]
@AndDiSa : I've seen this, no need to create a new issue. PR #9005 should fix it.
Thanks for the report !
