### ISSUE TITLE
Sony RX100 VII noise profile

### ISSUE THREAD

**Issue by emaimx** [darktable-org/darktable#4873]
I made a noise profile for the Sony DSC-RX100VII. 
[darktable-noiseprofile-20200430.tar.gz](https://github.com/darktable-org/darktable/files/4559795/darktable-noiseprofile-20200430.tar.gz)

I had an issue with my 8000 ISO picture. The tool was registering it as not under-exposed. The picture is exposed as the rest of the set, and I did try to replace it with others (up to -2EV), but they were also registered as not under-exposed. Higher ISO pictures (10000 ISO and 12800 ISO) were fine. In the end I disabled the check to get the profile.

**Comment by TurboGit** [comment]
Merged, thanks.
