### ISSUE TITLE
accels window doesn't follow cursor or doesn't scroll with cursor.

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4876]
openSUSE Tumbleweed 20200428
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1383.0e7305a3d-2912.1.x86_64
OpenCL on
i7 12-core 36GB

the accels window screen <H> does not scroll with cursor movement. 

makes it very difficult to see on laptop screen using mouse pad.

**Comment by elstoc** [comment]
Do you mean the window you get when you press 'h' to view the assigned accel keys for the current view?

**Comment by ptilopteri** [comment]
yes, on my laptop with no mouse, very difficult to see the entire list as it doesn't fit screen size. 
1366x768  :(

**Comment by elstoc** [comment]
If I change my screen resolution to match yours I can view the remainder of the window by scrolling with my scroll wheel (while still holding 'H' to keep the window open). Does that work for you?

**Comment by ptilopteri** [comment]
but there is no "mouse wheel"/"scroll wheel" on my laptop mousepad :(

**Comment by elstoc** [comment]
Ah. Not sure what can be done about that.

**Comment by ptilopteri** [comment]
make the display center on the mouse pointer ....

**Comment by johnny-bit** [comment]
@ptilopteri - i have no idea how can laptop pad not have scroll, it's such a basic functionality. maybe you need to use two-finger scroll?

another possible option: press H, while pressing H press ALT. release H. Release alt. now accels window is permanent. in top right corner you should have button allowing you to window accels window. press it. now you should be able to navigate accels window no problem.

**Comment by ptilopteri** [comment]
> @ptilopteri - i have no idea how can laptop pad not have scroll, it's such a basic functionality. maybe you need to use two-finger scroll?

yes, the laptop does have 2-finger scroll, but it apparently will not work in dt while holding the "H" key depressed.  With a mouse attached there is no problem scrolling that screen.

> another possible option: press H, while pressing H press ALT. release H. Release alt. now accels window is permanent. in top right corner you should have button allowing you to window accels window. press it. now you should be able to navigate accels window no problem.

yes, that does work.

I still believe that displaying the hot keys screen should be possible using the mouse pad, is this not a bug?

**Comment by johnny-bit** [comment]
I just checked on my laptop and i can scroll no problem while having "h" pressed (Dell Inspiron, libinput driving everything)

**Comment by ptilopteri** [comment]
Has not been fixed

**Comment by dterrahe** [comment]
From @johnny-bit 's comment, it seems that this should work, even on a laptop touchpad. Can you confirm that your touchpad driver generates scroll events when any keys are pressed? If not, it would look like a driver issue and dt can't be expected to work around all of those. A workaround was suggested for you. Please consider closing this issue as it is unlikely to be addressed. Thank you.
