### ISSUE TITLE
X-T100 Noise Profiles

### ISSUE THREAD

**Issue by rmkar** [darktable-org/darktable#4879]
I found these noise profiles for the X-T100 that another user made and posted on redmine. I think this thread may have fallen through the cracks while moving everything to GitHub. 
[Direct link to tarball](https://redmine.darktable.org/attachments/4547/darktable-noiseprofile-20191001.tar.gz) 
[Original post](https://redmine.darktable.org/issues/12711)

**Comment by TurboGit** [comment]
Merged, thanks!
