### ISSUE TITLE
Delayed reaction on mouse wheel spin on sliders

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#4880]
**Describe the bug**

Background info:
I use a Logitech MX Master 2S mouse. <-- has a scrollwheel without ticks=free spinning

When I use this function e.g. mouse-hover on WB slider and spin the wheel, 
- currently the slider will stay at the initial place, 
- no screenupdate and 
- only when the spinning speed got way slower or 
-- I stop the wheel, the GUI gets updated, 
-- means the slider jumps on 0sec flat to that new position and you see the WB change on the pic

**Expected behavior**

smooth GUI reaction and screenupdate as it was

Edit 1 (added _not_)
#4820 might _not_  be related

**bisect results**
I besected from dt-3.1.0+5-gcd01ccf7a
I did my best to judge well, but I confess, this bisect result makes no sense to me 
(in between I was forced to skip two times, as I could not build that version)

```
d6a9dad030fb06565ebf73b260f8da71fcfc534c is the first bad commit
commit d6a9dad030fb06565ebf73b260f8da71fcfc534c
Author: phweyland <philippe.weyland@laposte.net>
Date:   Wed Apr 8 10:31:56 2020 -0300

    fix $(EXIF_EXPOSURE) issue on watermark

 src/iop/watermark.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```
--> is there any file from .git folder might help ?

@phweyland may I ping you here, even with my total noob understanding, I cannot imagine, what that commit above should have to do with it

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: **Gentoo Linux**
 - OpenCL: **on and off, both show error**
 - GPU 0 Nvidia GTX1060 OC 
 - GPU 1 Nvidia RTX2070 Super
 - nvidia-drivers-440.82

**Additional context**
 - Are the steps above reproduce with a fresh edit (removing history)? **yes** (more obvious if expensive modules are activated)
 - Did you compile Darktable yourself? If so which compiler was used, with what options? 
**gcc 9.3.0 | -march=native -O3 -mtune=native -pipe**
 - Is the issue still present using an empty/new config-dir **yes**

**Comment by phweyland** [comment]
You mentioned the type of mouse... have you noticed a different behavior with another type ?

**Comment by AxelG-DE** [comment]
Hihihi
I don't have another one, which has this kind of function. With click you will never be able to spin that fast :-)

I can just say, 
- it once worked well
- the PC does recognize the spinning speed, as I can rev to max in terminal or firefox
- it really feels, there is a kind of limiter, where the max speed of ticks has a cap value, because once the wheel gets slower the reaction comes back.

...please get me right! I am not playing for fun, how fast I can spin the wheel. It is really the normal workflow, that I kick the wheel for WB adjustment. Just for this issue, I checked a bit harder, how far can I go, in order to describe better :)

**Comment by AxelG-DE** [comment]
I tried to bisect this again and find only bullshit because it is floatingly getting worse and worse...

When you e.g. try 2.7.0+1525~g21ac343cd, you can see, it is way more fluent and swift compared to todays current master...

I am willing to support in analysis, but need guidance, what to do next.

@phweyland sorry I bothered you
@parafin do you have an idea, what I could do to figure out?

I am on and off whether #4820 is related or not...........

Sorry for again being a perf PITA

**Comment by phweyland** [comment]
> sorry I bothered you

You don't. I'm just worry because the use case you have described above works perfectly for me. 

Could you share an xmp for which you have this issue especially visible (same for  #4820 ) ?

**Comment by parafin** [comment]
No idea here. sorry.

**Comment by AxelG-DE** [comment]
@phweyland sorry somehow I overlooked your wish for an xmp...

I just tested again, the issue is still there, for both caes, this one and #4820 

(tooo big to zip in here, as inclued the RAW)
https://fromsmash.com/Mouse-delay 

The xmp-only is here:
[6402.xmp.zip](https://github.com/darktable-org/darktable/files/4809322/6402.xmp.zip)

**Comment by AxelG-DE** [comment]
@aurelienpierre id that bot a bit over nervous? Issue from May 1st get no-issue-activity already 21st June? (9 days ago today)

**Comment by AxelG-DE** [comment]
Cannot test atm :-/

**Comment by dterrahe** [comment]
I assume this is still an issue for you?

**Comment by jenshannoschwalm** [comment]
Very likely fixed on 4.4 so closing this for now.

**Comment by AxelG-DE** [comment]
sorry, that I reply with huge delays. Life is still in my way (and I wonder, when would it stop and things come to normal)

If I go very extreme, I can make color calibration still behave as described here, but that is unrealistic brutal. For normal usage, I can confirm after a few quick tests, that it works as expected now.

**Comment by jenshannoschwalm** [comment]
Thanks for confirming :-) Haven't seen you here for a long time ?

**Comment by AxelG-DE** [comment]
@jenshannoschwalm 
yeah health status of me, my wife and other troubles keep me away unfortunately. I do IRC but also very limited...
(sorry for OT)

**Comment by jenshannoschwalm** [comment]
Ich wünsche euch einfach alles Gute!
