### ISSUE TITLE
Culling mode: easy way to get to 100% zoom with mouse

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#4882]
**Is your feature request related to a problem? Please describe.**

The culling mode is great to compare several pictures. It's the perfect tool to select the right shot for macrophotography where I often have tens of pictures of the same thing and only a few sharp enough. But for this use-case, culling is only really relevant with a 100% zoom. For now, I have two minor user-experience glitches:

* The middle-click shortcut in darkroom to get to 100% is great, but not available in culling mode. AFAIK, the middle-click is not mapped to any action on culling mode, so it would make sense to get the same behavior as in darkroom.

* The zoom level is not displayed anywhere, so if I control-scroll to get to 100%, I don't get a visual feedback when I reach 100%. Usually zooming is a bit slow and therefore I can't distinguish "I did control-scroll and nothing happened because my computer is being slow" and "I reached 100%". But I have to admin that I didn't think of any good place to display the zoom level properly (displaying it on top of the image would be distracting, displaying it elsewhere would be misleading since the zoom level can be per image). Perhaps displaying the zoom level of the picture where the mouse is in the message area on top of the screen, below "X images out of Y in current collection are selected" would make sense.

**Describe the solution you'd like**

* Same middle-click behavior in culling mode as in darkroom

* Perhaps, display the zoom level somewhere

**Alternatives**

There are `<Darktable>/views/lighttable/preview zoom 100%` and `<Darktable>/views/lighttable/preview zoom fit` keyboard shortcuts that allow getting to 100% and back to "fit" zoom with the keyboard. Almost as good, but not as convenient as the middle-click behavior to me.

**Comment by AlicVB** [comment]
yes middle-click as already been mentioned and I forget it (I never manage to do middle-click without scrolling) for the zoom indicator, I'll think to that, there's maybe a place in the new overlay block...

**Comment by AlicVB** [comment]
@moy : I've integrated your too points in the culling/preview rewrite here : #4864 It should land in master once all the small glitches are fixed and that will be for 3.2...
Thanks for reporting
