### ISSUE TITLE
Ctrl+scroll on module cursors

### ISSUE THREAD

**Issue by manu-p** [darktable-org/darktable#4899]
Hi, 
When the miscellaneous pref "mouse wheel scrolls modules side panel by default" is not ticked you may use your mouse wheel to interact with some modules cursors just scrolling, Shift scrolling and Ctrl scrolling over a cursor while the pointer is hovering it. 
And that's very fine!

Now, for some reason you may prefer having this pref option ticked so that your mouse wheel interact only with the side panel and then you have to Ctrl + Alt + mouse wheel over the cursors to adjust them the way you want. This is well documented, that's OK.

Right, but what about the fine tuning you had with Ctrl + scroll before? 

"Ctrl + Alt + mouse wheel" replaces "mouse wheel", but it seems there's no combination to replace "Ctrl + mouse wheel" for fine tuning, such as for instance "Ctrl + Shift + mouse wheel" (or even Ctrl+Alt+Shift...).

Would it be possible to implement something in that way?

**Comment by manu-p** [comment]
Any plan to implement some fine tuning when the miscellaneous pref "mouse wheel scrolls modules side panel by default" is ticked?

**Comment by RawConvert** [comment]
If ctrl+wheel and shift+wheel action can be tidied up cheaply, that would seem good, not least to avoid others coming across this anomaly, wasting time raising it, etc.

**Comment by RawConvert** [comment]
Following discussion on #5740 and thinking about testing...
Just to check proposed scope of this issue:  a) it applies to all modules in darktable
b) it doesn't apply to any lighttable ones (not that I can see any items it might apply to at present)
c) it will be CTRL+wheel for fine adjustment  and  ALT+wheel for coarse
d) Fine adjustment behaviour will be exactly the same as currently when not scrolling modules
e) Ditto coarse adjustment
f) It therefore follows certain oddities with current behaviour will be out of scope.  For example, adjusting the Y value of a tone curve point: Wheel alone gives .1 increments, ctrl+wheel gives I think .01 but only 1 dp is shown, so it's not immediately obvious what the fine control is doing. E.g. with the Exposure slider, coarse adjustment is the same as normal (.02 increment).

**Comment by dterrahe** [comment]
@RawConvert have you tested if #5755 fulfills your requirements? It would be helpful if you mentioned your feedback there, so somebody with powers to merge could take it into account.

In c) I assume you mean SHIFT+wheel for coarse?

**Comment by RawConvert** [comment]
in c) yes sorry, shift+wheel.  I've amended my post above.
Re. testing, I didn't know you wanted me to test 5755.  I don't know my way round github too well so you'll have to be very clear when anything is ready to test.  I'll need a nudge.  I'll need to know what branch to compile, e.g. this bit:  "git checkout xxxxxxxxx"
and I'll need to know which Issues I am to test within the resulting build.

**Comment by RawConvert** [comment]
@dterrahe , have you seen my comment above?, do you want me to test 5755 etc.  Is it in Master or somewhere else?....

**Comment by dterrahe** [comment]
A pull request usually proposes a change in a personal fork for inclusion in the main repository by someone who doesn't have write access there. So this is not yet on the official master. Github will show you which fork and branch the pull request originates from (dterrahe/darktable:fix-ctrl-shift-scroll) in this case, and how to either checkout the whole branch or only merge the individual pr.

**Comment by RawConvert** [comment]
@dterrahe , as I said previously, you need to be clear what I need to do to build this.  The above is helpful but only to a certain extent.  Regarding checking out the whole of "dterrahe/darktable:fix-ctrl-shift-scroll" versus doing just the PR, you know best what's in there, so **please advise which way to go**.  I haven't time for learning about github!  So I'm assuming (possibly incorrectly) that I just need a tweak to my normal build process, and therefore need you to say how to adapt the following commands:-

...
git clone https://github.com/darktable-org/darktable.git   etc.
git checkout release-3.2.1
git submodule init
git submodule update
./build.sh
...

Thanks

**Comment by dterrahe** [comment]
@TurboGit when you have time, would you kindly have a look at #5755 and consider it for merging? There are a few bugs linked to it that, as @RawConvert points out, could be wasting other people's time as well. Many thanks in advance!

**Comment by TurboGit** [comment]
Now merged, thanks for the heads-up !

**Comment by dterrahe** [comment]
Thank you!
