### ISSUE TITLE
An unhandled exception occured

### ISSUE THREAD

**Issue by EMAR31** [darktable-org/darktable#4902]
Bonjour,
Dans la Chambre Noire, une erreur grave arrive régulièrement lorsque j'active la roulette de ma souris pour augmenter ou diminuer le zoom sur une image raw. 
Darktable "plante" et je perds toutes mes dernières modifications.
J'avais ce problème dans la version précédente. Il persiste dans la version 3.0.2

![Capture](https://user-images.githubusercontent.com/63604014/80911103-7c36bf80-8d34-11ea-8f87-cfb1e59088d7.JPG)

Platform :
    Darktable Version: 3.0.2
    OS: Windows10
    OpenCL activated
    NVIDIA GEForce GTX 950M pilote 23.21.13.8873]
[darktable_bt_1FM1J0.txt](https://github.com/darktable-org/darktable/files/4569949/darktable_bt_1FM1J0.txt)
[darktable_bt_ZOD2J0.txt](https://github.com/darktable-org/darktable/files/4569951/darktable_bt_ZOD2J0.txt)
[darktable_bt_APVVJ0.txt](https://github.com/darktable-org/darktable/files/4569953/darktable_bt_APVVJ0.txt)
[darktable_bt_AKHJJ0.txt](https://github.com/darktable-org/darktable/files/4569956/darktable_bt_AKHJJ0.txt)

**Comment by paperdigits** [comment]
If you turn off openCL, can you still reproduce the issue?

**Comment by EMAR31** [comment]
Thank you for your response.
I will uncheck the option and confirm whether it is OK or not.
Sincerely

Le 13/05/2020 à 07:44, Mica a écrit :

**Comment by johnny-bit** [comment]
3/4 logs mention toneequalizer error. Since toneequalizer came a long way since the report (and reporter haven't confirmed whether it is OK or not) i'm gonna close tis issue. EMAR31 - if you still have crashes please create a new report on newest darktable (actually - wait till 3.6 release. It'll be awesome!)
