### ISSUE TITLE
Filmstrip selection in darkroom never gets reset

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#4905]
In thumbtable, one can select multiple images clicking with the usual CTRL / SHIFT modifiers.
Clicking on an image outside the current selection, gets the selection reset.
In filmstrip inside darkroom one can still select multiple images with CTRL / SHIFT + click. I am not sure what is the purpose of that, maybe actions on multiple images are possible in darkroom through keyboard shortcuts. 
However clicking on an image outside selection, the selection is not reset, the clicked image is open in the center instead.
In practice, the selection can only grow, which is odd.

![Cattura35](https://user-images.githubusercontent.com/43290988/80923449-2a1d8a80-8d84-11ea-9b79-7c4518254607.JPG)

DT git master on Windows 10

**Comment by AlicVB** [comment]
this is "by-design". You can use alt-click to get same behavior than click in filemanager (this will need to be written in the manual). The reason behind is that we try to not modify the selection except if user explicitly want it, especially in mode like filmstrip where "normal" click is used to switch to another image.
And yes it's possible to use selection in darkroom : you can for example copy the history of current image and paste it to the selected images...

I'm closing as it's not a real bug... Anyway thanks for the report
