### ISSUE TITLE
selection of current image is lost between lighttable and darkroom

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#4916]
Selection has lost consistency between lighttable and darkroom.
To reproduce: 
Select an image in lighttable. 
Enter darkroom mode ("D").
Select other image with single click (I haven't checked for double click, maybe too).
Return to lighttable with "L".

The selection returns to the image, selected in lighttable, not in darkroom.  

That is a dataloss issue - the actions are applied to the wrong image (user is sure the selected one is the last one selected).

Darktable from git master of 2020.05.05.
Linux Mint 19.3 Mate x64.
OpenCL is active,  Radeon RX580.

**Comment by AlicVB** [comment]
yes, it's also discussed in #4914 I'll have a look§. Thanks for the report
