### ISSUE TITLE
An "old" new iop order resolved issue still there when copying development and cancel it

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4919]
**Describe the bug**
This is a bug that has been solved about the new iop order. Seems that it is not solved completely.
I have it only, has before, when having 2 instances of same modules (here contrast local). @TurboGit: seems this is for you even if I know you wouldn't like seeing this one come back!

**To Reproduce**
1. Have an image developed with 2 instances of same module (on my side, images were only having 2 instances of local contrast module)
2. Go to lighttable (this issue seems to be only in lighttable mode, I can't reproduce it in darkroom)
3. Copy the development of this image
4. Paste this on another image (I only tested on images that already have development as I have automatic presets), regardless of the copy/paste mode selected (same issue with both ones)
5. Press Ctrl+z to cancel the paste

The image is "broken" and display like that:

![2020-05-05_19-27](https://user-images.githubusercontent.com/45535283/81097067-a391b600-8f07-11ea-9449-3b575b01ffd0.png)

**Expected behavior**
When press Ctrl+z to cancel, just go to previous history and have correct image displayed regardless of previous history.

**Platform (please complete the following information):**
 - Master (recent one, compiled 2 days ago)
 - OS: Ubuntu 20.04
 - No OpenCL on my side

**Comment by TurboGit** [comment]
>     1. Have an image developed with 2 instances of same module (on my side, images were only having 2 instances of local contrast module)

Done with current master too ?

Indeed, I was expecting those issues to be behind us :)

**Comment by Nilvus** [comment]
> > ```
> > 1. Have an image developed with 2 instances of same module (on my side, images were only having 2 instances of local contrast module)
> > ```
> 
> Done with current master too ?

Unfortunately yes. I only test that with images taken this last few days...

**Comment by TurboGit** [comment]
I can only reproduce if I Ctrl-C and paste 2 times Ctrl-V on another image. Then Ctrl-Z breaks the edit.

**Comment by TurboGit** [comment]
And indeed I can reproduce only from lighttable.

**Comment by Nilvus** [comment]
> I can only reproduce if I Ctrl-C and paste 2 times Ctrl-V on another image. Then Ctrl-Z breaks the edit.

I use indeed shortcuts but normally not 2 times Ctrl+V. But maybe, as I made that fast...

**Comment by TurboGit** [comment]
Should be fixed now. Can you test again to be sure there is no other cases ?

**Comment by Nilvus** [comment]
> Should be fixed now. Can you test again to be sure there is no other cases ?

Make some tests and Ctrl+z/Ctrl+y works great. Thanks for the fix. We now will hope this is the last iop order issue fixed and there's no more similar ones.

**Comment by TurboGit** [comment]
Thanks for testing !

Yes, crossing fingers :)
