### ISSUE TITLE
Feature Request: display camera EV (+1, -1 etc.)

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#4923]
**Is your feature request related to a problem? Please describe.**
My _problem_: Sometimes I shot ETTR with a camera setting of +1 EV. It would be good to see that +1 EV in darktable as a starting point, like in other software, i.e. RawTherapee

**Describe the solution you'd like**
Have the camera EV status read from the EXIF and displayed under _image information_

**Alternatives**
Can't think of any.

**Additional context**
Nope.

Example: RawTherapee displaying-2.00EV

![Screenshot 2020-05-06 15 38 27](https://user-images.githubusercontent.com/3244771/81149089-1ce4e380-8fb0-11ea-83fe-127ea61f31bc.png)

**Comment by elstoc** [comment]
Isn't this already there, under "exposure bias"?

**Comment by Nilvus** [comment]
I confirm it's already exist on exposure bias. But @4044ever doesn't precise which version of darktable he use. So this is already present in master and will be there on next major release, 3.2. So please be patient and close this issue as it has been implemented.

@4044ever: see #4592 (find by just adding exposure bias on pull request search field ; always a good idea to what has been done).

**Comment by 4044ever** [comment]
Whoops, I am using 3.0.2 on Windows. Good to know that EV Bias is already in the pipeline! I rest my case.

**Comment by Nilvus** [comment]
@4044ever: good but you forgot to close your issue. Think of closing this one to let developers know which one remains to follow/work on.

**Comment by Nilvus** [comment]
@TurboGit: this one could be closed.

**Comment by 4044ever** [comment]
Closed, as it's already in the pipeline.
