### ISSUE TITLE
problem updating lighttable

### ISSUE THREAD

**Issue by LViatour** [darktable-org/darktable#4929]
@alicvb

**Describe the bug**

when creating an HDR in the light table, the HDR is not visible. You have to change the display order to see it in the lighttable

**To Reproduce**

1. select multiple raw
2. clic to create HDR
3. the thumbnail of the DNG created is not visible in the light table

**Expected behavior**
Normally the new DNG HDR should appear in front of the raw files selected for HDR

**Platform (please complete the following information):**
-3.1.0~git1412.d999cc8a7
-Ubuntu 20.04 
-open CL yes
-Nvidia drive 440.64
-->

**Comment by Mark-64** [comment]
It seems similar to #4889, I will have a look.

**Comment by jenshannoschwalm** [comment]
I think creating the hdr file just "creates" it. This does not imply to **import** it ...

**Comment by Mark-64** [comment]
Just forcing a refresh in thumbtable, for example changing the visualization order or group/ungroup, makes the DNG appear, so definitely the HDR is imported, only the view is not refreshed, like in #4889

**Comment by Mark-64** [comment]
PR created

**Comment by Mark-64** [comment]
Fixed, via b26f24717c63c0271151346d73973e171daecee5, please close
