### ISSUE TITLE
Fujifilm X-Pro3

### ISSUE THREAD

**Issue by cribari** [darktable-org/darktable#4935]
**Describe the bug**
When I open a Fujifilm X-Pro3 RAW file in Darktable, I see the following message: 
"`Fujifilm X-Pro3' color matrix not found!"

**To Reproduce**
In January, I submitted Fujifilm X-Pro3 RAW files to https://raw.pixls.us/ . To reproduce the issue, you may get such files and open them in Darktable. 

**Expected behavior**
The camera color matrix should be identified. 

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2-2
 - OS: Arch Linux
 - OpenCL: no
 - Graphics card: Intel 

**Additional context**
On January 22, I opened a ticket asking for Fujifilm X-Pro3 support in Darktable; see 

https://github.com/darktable-org/darktable/issues/4175

The issue was closed on February 22.

**Comment by paperdigits** [comment]
This doesn't work because you're using a stable build, and the support for that camera was added after the release date. 

If you know how, you can make your Arch package build with the master version of rawspeed, and support for your camera should be there. I believe there is also a "master" branch package for Arch, but beware there is no going backward once you switch to using the master build.

**Comment by coffeeandspaceships** [comment]
Looks like this was added to the rawspeed submodule in commit https://github.com/darktable-org/darktable/commit/9ebc6f6c8959930417cdf4ae77674a58208c31b9

That means your submission will be included in darktable 3.2, I think.

**Comment by cribari** [comment]
The problem persists with Darktable 3.2.0. When I open a Fujifilm X-Pro3 RAW file I see the message: "`Fujifilm X-Pro3' color matrix not found!" .

**Comment by LebedevRI** [comment]
Works for me with those two raws present on RPU.
Can you please upload the specific raw you have issues somewhere?

**Comment by cribari** [comment]
> Works for me with those two raws present on RPU.
> Can you please upload the specific raw you have issues somewhere?

Here are the links for the two RAW files (which were produced by me using a Fujifilm X-Pro3 camera): 

https://www.dropbox.com/s/eldehd9p0iua6un/_DSF2384.RAF?dl=0

https://www.dropbox.com/s/ihtcr6wkvzhhy4z/_DSF2385.RAF?dl=0

Here is a screenshot: 

https://www.dropbox.com/s/l4p4flqzclw2p7g/Screenshot_20200810_100503.png?dl=0

**Comment by LebedevRI** [comment]
> Here is a screenshot:
> 
> https://www.dropbox.com/s/l4p4flqzclw2p7g/Screenshot_20200810_100503.png?dl=0

That is dt-3.0.2

**Comment by cribari** [comment]
> That is dt-3.0.2

I incorrectly assumed that the Darktable version in the Arch repository was 3.2.0. It was my mistake, and I apologize. Sorry.
