### ISSUE TITLE
Fujifilm X-T4

### ISSUE THREAD

**Issue by frli8848** [darktable-org/darktable#4943]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by frli8848** [comment]
I have uploaded Fujifilm X-T4 (.RAF) RAW file to https://raw.pixls.us/

I also tried a hack by just duplicating the (similar) X-T3 settings in the files:
<pre>
data/noiseprofiles.json
src/external/adobe_coeff.c
src/external/rawspeed/data/cameras.xml
src/external/wb_presets.c
</pre> 
which made Darktable at least open the X-T4 files (the X-T4 images looks a bit de-saturated though). I have attached a patch 
[darktable-3.0.2-xt3-xt4.patch.gz](https://github.com/darktable-org/darktable/files/4597687/darktable-3.0.2-xt3-xt4.patch.gz)

**Comment by LebedevRI** [comment]
Thank you for contributing samples, but we need moar of them.

As per https://www.imaging-resource.com/PRODS/fuji-x-t4/fuji-x-t4A.HTM
> The X-T4, as expected, offers both RAW and JPEG image recording, including both 14-bit uncompressed and lossless compressed RAW formats.

So there are likely 3 raw modes. We need a sample for each one.
And please ideally all three new raw images should be of the same static scene,
if possible.

**Comment by frli8848** [comment]
OK. I Will check which RAW modes that are available in the current fw.

**Comment by frli8848** [comment]
I have now uploaded three .RAF files (on a X-rite colorchecker classic):
1) uncompressed
2) Compressed lossless
3) Compressed

**Comment by LebedevRI** [comment]
Thank you!

**Comment by LebedevRI** [comment]
Note: the new "compressed lossless" format is not supported as of presently.

**Comment by frli8848** [comment]
Hm OK, I use the  "compressed lossless"  with my hack above and it seems to work fine.

And, while I was debugging this I found this blog entry:

https://encrypted.pcode.nl/blog/2010/06/28/darktable-camera-color-profiling/

Is it still relevant?

**Comment by LebedevRI** [comment]
> Hm OK, I use the "compressed lossless" with my hack above and it seems to work fine.

I think you mean plain old "compressed", not new "compressed lossless".

**Comment by frli8848** [comment]
No I have set the camera to:
<pre>
RAW RECORDING -> LOSSLESS COMPRESSED
</pre>
but now when checking this again I can see that I cannot open files with the setting:
<pre>
RAW RECORDING -> COMPRESSED
</pre>
Perhaps this is a FW bug and that I in reality use non-lossless compressed ones?

**Comment by LebedevRI** [comment]
Ah, interesting, then likely i'm simply misremembering.

**Comment by frli8848** [comment]
Here is the file sizes on the three formats:
<pre>
$ ls -lah DSCF0266.RAF
-rwxrwxrwx 1 fl fl 55M May  8 11:18 DSCF0266.RAF

$ ls -lah DSCF0267.RAF
-rwxrwxrwx 1 fl fl 27M May  8 11:18 DSCF0267.RAF

$ ls -lah DSCF0268.RAF
-rwxrwxrwx 1 fl fl 26M May  8 11:19 DSCF0268.RAF
</pre>
and it is the last one that I cannot open so it looks like it really is the (lossy) "COMPRESSED" ones that is not supported. Just let me know if I should test something else?

**Comment by LebedevRI** [comment]
> Just let me know if I should test something else?

Thank you, nothing else.

**Comment by gribouilleuse** [comment]
Thank you @frli8848 and @LebedevRI for this integration. Now the branch master is compiled, my X-T4 is happy ;)

**Comment by frli8848** [comment]
@LebedevRI How did you compute the color matrix in the file src/external/adobe_coeff.c? This is, how is the values show below computed?
<pre>
-snip-

     { "Fujifilm X-T1", { 8458,-2451,-855,-4597,12447,2407,-1475,2482,6526 } },
     { "Fujifilm X-T2", { 11434,-4948,-1210,-3746,12042,1903,-666,1479,5235 } },
     { "Fujifilm X-T3", { 16393,-7740,-1436,-4238,12131,2371,-633,1424,6553 } },
     { "Fujifilm X-T4", { 13426,-6334,-1177,-4244,12136,2371,-580,1303,5980 } },
     { "Fujifilm XF1", { 13509,-6199,-1254,-4430,12733,1865,-331,1441,5022 } },

-snip-
</pre>

**Comment by parafin** [comment]
It's documented at the top of that file.

**Comment by frli8848** [comment]
Thanks! So this is just taken from the Exif header. I have tried to follow this post:

https://encrypted.pcode.nl/blog/2010/06/28/darktable-camera-color-profiling/

using a X-Rite ColorChecker Classic but the info looks a bit outdated (from 2010). Is there any measurements involved when adding support for a new camera or is all data (except noise profiles) taken from Exif data?

**Comment by Potatof** [comment]
It would be a good idea to modify the supported formats page by indicating "Compressed" instead of "lossy RAFs"!
https://www.darktable.org/resources/camera-support/
