### ISSUE TITLE
Improvements suggested for star icon and it's overlay popup

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4946]
**Is your feature request related to a problem? Please describe.**
We now have a great overlay popover menu when clicking star icon. But there's 2 things to improve:
- star icon is clickable, even on modes where this is not useful and not applicable (preview and culling modes)
- the size feature (with setting on preferences window) is not really clear (I myself didn't really understand what it is and settings avalaible).

**Describe the solution you'd like**
- For 1st one: "simply" deactivate the icon on culling and previews mode. So having the icon on grey and not clickable with a tooltip which precise that this option is not useful on this mode.
- For 2nd one: having a more precise tooltip on preferences window (with possible settings) and on star icon (or at least title of the popover where size is precise.

We could also add the idea (to be discussed and precise) by @TurboGit on #4864 from @AlicVB to add the size with star icon. For that idea, I'm not for the square icon (star is good but maybe there's a better one to think about and to add the size numbre). By remember that this size has to be as quickly as possible clear for the user. Not the case by now.

**Comment by AlicVB** [comment]
>     * star icon is clickable, even on modes where this is not useful and not applicable (preview and culling modes)

in culling, preview, darkroom, etc... this is tied to filmstrip, like it was before. I admit this is not clear at all but I'm not sure how to solve that... Maybe at least we can add a text in the popup label ?



>     * the size feature (with setting on preferences window) is not really clear (I myself didn't really understand what it is and settings avalaible).

I wanted to add the size values in the popup label, but I forgot it along the way...

What I can propose for the popup label is a text like : 
`overlay mode for size 2 (250px -> 800px) (filmstrip)`
I just wonder if this won't be too long, esp. once translated

**Comment by Nilvus** [comment]
> in culling, preview, darkroom, etc... this is tied to filmstrip, like it was before. I admit this is not clear at all but I'm not sure how to solve that... Maybe at least we can add a text in the popup label ?

Not needed. I never use filmstrip on these modes and only use it on darkroom so didn't think of that. text popup label is in reality clear about that as it talks about thumbnails. So you could forget what I ask here about the star icon.

> > ```
> > * the size feature (with setting on preferences window) is not really clear (I myself didn't really understand what it is and settings avalaible).
> > ```
> 
> I wanted to add the size values in the popup label, but I forgot it along the way...

> What I can propose for the popup label is a text like :
> `overlay mode for size 2 (250px -> 800px) (filmstrip)`
> I just wonder if this won't be too long, esp. once translated

Not the best thing I think. Sizes (so 2 (250px -> 800px) for your example) are probably better on preferences textview tooltip. What it's not clear (now that I finally understand what these sizes means is to help user understand sizes are related to thumbnails sizes. And I'm not sure 1, 2 numbers are really meaningful. Why not simply change that to something like:

`overlay mode for _x_px -> _y_px thumbnail width (view)`

where view is the name of the view (filmstrip, lighttable...)
