### ISSUE TITLE
Add delete to duplicate manager for unduplicated files

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#4950]
It would be nice to be able to delete from the darkroom without having yet another keyboard short-cut I can't remember, or more buttons.

At present, if I create a duplicate image, each has a little "X" to delete inside the duplicate manager. It disappears once only one version is left.

Why not keep it? It would be a very lightweight way to add the delete function.

**Comment by ptilopteri** [comment]
there already exists a "delete function",
grep -i delete ~/.config/darktable/key*

keyboardrc:(gtk_accel_path "<Darktable>/modules/image/delete from disk" "Delete")
keyboardrc:(gtk_accel_path "<Darktable>/modules/image/delete from disk or send to trash" "Delete")
keyboardrc_default:(gtk_accel_path "<Darktable>/modules/image/remove from collection" "Delete")
keyboardrc_default:(gtk_accel_path "<Darktable>/modules/image/delete from disk or send to trash" "")

and there is still the "X" superimposed over each image configurable with the "STAR" drop-down

and what/where is "duplicate manager"?

**Comment by GrahamByrnes** [comment]
"... without having yet another keyboard short-cut ..."

The duplicate manager is a panel on the left in darkroom view, titled: "duplicate manager".

**Comment by ptilopteri** [comment]
errr, ok, was looking where I would expect to see, lighttable.  Doesn't seem appropriate to locate that in darkroom view.

and about "... without having yet another keyboard short-cut ...", that shortcut has been in dt maybe as long as I have used it, >9 years if memory serves.
