### ISSUE TITLE
darktable-cli crashes (3.1.0+1480)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#4954]
**Describe the bug**
When running darktable-cli it crashes and produces a backtrace.

**To Reproduce**

1. Install latest development version (3.1.0+1480)
2. Run darktabl-cli file.raw file.raw.xmp out.jpg
3. see it crash and burn....

**Expected behavior**
Not to crash.

**Platform (please complete the following information):**
* darktable-cli : 3.1.0+1480
* OS               : Linux - kernel 5.4.0-0.bpo.4-amd64
* Distro           : Debian Buster (rel. 10.3)
* Graphics card    : GeForce RTX 2060 SUPER
* Graphics driver  : 440.82
* OpenCL installed : Yes (nvidia-opencl-common   440.82-1~bpo10+1)
* OpenCL activated : Yes and No (tried both)
* GTK+             : 3.24.5-1

**Additional context**
Talked about this with houz on IRC, installed libgtk-3-0-dbgsym, made it crash again and gave bt to him (is also linked here)
Houz said to put the following in the bug report:

_[19:49:05 ]<houz> please file a bug report and mention that init() may not do gui stuff_

Backtrace: https://pastebin.com/HUBN2Uq8

**Comment by TurboGit** [comment]
Fixed. Thanks for the report.
