### ISSUE TITLE
LUT changes appear only in the pilot display, not on main editing screen (Intel 4400 on Windows 10)

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#4958]
**Describe the bug**
When I apply a LUT3D (cube/png) I can see the change in the pilot display (top left) but not in the main editing screen

**To Reproduce**
I can not reproduce this problem on other PC that I run. Only one has this issue (i3, 4***, Intel 4400)
I tried different dt (3.0.2/3.0.0/rc0-2)

**Expected behavior**
LUT will display in in the editing screen

**Screenshots**
https://i.imgur.com/1ROqQe9.png
https://drive.google.com/file/d/1uuZeNi9_Cm2ITkTqMnX98nwWJW3fqOha/view (same)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2 (tried all 3.* incl. rc*)
 - OS: Windows 10-64
 - OpenCL 1.2
 - tried: 10.18.15.4248 + 20.19.15.5126 (latest)

**Additional context**
I have the problem only with the 4400 PC, others work fine.
I have the problem with all dt 3.* versions
Effects all, RAW, JPG, TIFF
Happens also with fresh installed dt (user + iNetCache wiped clean)
 - Is the issue still present using an empty/new config-dir: yes.

Additional:
While the editing screen is **not** displaying the LUT generally, the correct LUT will appear for a fraction of a Second then I resize the editing screen. Also, some minor artifacts will with the (I presume) correct LUT will show.

When I switch off openCL in prefs. LUT is working normally.

OpenCL on the PC was testet with other software and is working.

**Comment by phweyland** [comment]
Is that the same case as described on pixls.us [here](https://discuss.pixls.us/t/darktable-style-vs-lut/17908) ?

**Comment by 4044ever** [comment]
Yes, some, with a few logs. Still tapping in the dark.

**Comment by coffeeandspaceships** [comment]
This is weird. OpenCL is blacklisted for Intel IGA in this build for Windows 10. Did you remove OpenCL from the blacklist and build locally?

**Comment by 4044ever** [comment]
> This is weird. OpenCL is blacklisted for Intel IGA in this build for Windows 10. Did you remove OpenCL from the blacklist and build locally?

No, I just installed from the *.EXE package.

Are you implying that darktable will not run with OpenCL on a 4400 no matter what? 

(that means on the portable darktable I would need to switch OpenCL ON/OFF depending where I work on. A bit tricky because on the laptop the "_close_" button in preferences is below the screen and pref window does not scroll ;-) )

**Comment by coffeeandspaceships** [comment]
I'm afraid that is what I am implying. BUT all is not lost:
Intel® HD Graphics 4400 looks like it's Haswell / 4th Gen CPU vintage. Luckily for you, 4th gen is the oldest supported, according to the Intel documentation:
https://software.intel.com/content/www/us/en/develop/articles/getting-started-with-compute-offload-to-intelr-graphics-technology.html

I have raised an issue (with some buy-in from maintainers!) to de-blacklist Intel GPU support on "good enough" hardware. Please comment there if you're happy to be an early tester (once I have put together a build, and some meaningful ways of testing!)

In the meantime, this means if you build dt yourself locally, you can just comment out the Neo blacklisting in the .h, and you'll have the support you need, even on the 3.0.2 codebase.

**Comment by coffeeandspaceships** [comment]
Meanwhile back to *this* issue - does that mean there is a related defect whereby you can *appear* to have enabled OpenCL but actually nothing is offloaded and there is no convenient means to tell either way in the UX?

**Comment by 4044ever** [comment]
The word "build" gave me an idea. I copied a `/darktable/` folder from a PC where it worked to my USB drive. That worked the first time, but not again. But, I have no idea why, the USB version I had before worked fine. The C: driver version still has the LUT problem. 

Since I just use the USB darktable anyway the issue is sort of solved.

I will complete remove the C: drive darktable and just use the USB one. 

Last words: This wasn't a general darktable bug, just something related to my setup.

**Comment by coffeeandspaceships** [comment]
It may functionally work but it won't be offloading to the IGA.

Would you mind trying [this build ](https://github.com/coffeeandspaceships/darktable/releases) on the slower of the two machines you're using, to see if you get offloading and if it's any faster in practical use than just using CPU?

**Comment by 4044ever** [comment]
This was totally stupid, sorry for that - the problem is still there - I disabled OpenCL, then of course LUT will work. With OpenCL clicked it isn't working. 

How do I build for Windows? I usually d/l the EXE installer and transfer the folder to my USB drive.

**Comment by coffeeandspaceships** [comment]
Can you please comment on https://github.com/darktable-org/darktable/issues/5054 with a summary of your findings so far? 

In the first comment on that issue you will see a link to a debug package I have built. Please make sure you use the 3.0.2 link. Note it's not a supported build.

If you are certain that the problem with LUT is triggered by enabling OpenCL you should re-open this issue anyway because that is a defect anyway and needs fixing. :)

**Comment by 4044ever** [comment]
I am going to test darktable-3.0.2+1.g905d25d6d-win64.exe tonight.

**Comment by 4044ever** [comment]
> Can you please comment on #5054 with a summary of your findings so far?

 Running 3.0.2+1.g905d25d6d-dirty

Same as the standard 3.0.2, no change.

**Comment by TurboGit** [comment]
This version does not exists : 905d25d6d, I don't know where you got it.

**Comment by coffeeandspaceships** [comment]
> This version does not exists : 905d25d6d, I don't know where you got it.

It's a TEST build from my fork. That's why I asked @4044ever to comment over on #5054.

But, aside from that, for THIS issue 4958, when 4044ever uses the 3.0.2 shipped release it seems that he has a problem when the OpenCL UI toggle is enabled, and the problem stops when it is disabled. That should not be happening because his chipset is blacklisted; so how is the UI toggle enabling it? Or is something completely pathological happening?
