### ISSUE TITLE
metadata export: export all values of $(CATEGORYn(category)) when there are several tags at level n

### ISSUE THREAD

**Issue by EC1000** [darktable-org/darktable#4964]
**Is your feature request related to a problem? Please describe.**
The variable `$(CATEGORYn(category))` gives some great possibilities to use tags in other fields using "metadata export" in export module (examples in the [manual](https://darktable.gitlab.io/doc/en/export_selected.html)). 

When several tags (at the same level) are defined under a category, only one value is exported from `$(CATEGORYn(category))`. 
For example, if you have an image with tags "People|Bob" and "People|John", and define a formula `Xmp.iptcExt.PersonInImage=$(CATEGORY0(People))`, the exported file will only have "John" in the `Xmp.iptcExt.PersonInImage` field but not "Bob".  

**Describe the solution you'd like**
I think it would make sense to export all tags of level `n` when several tags are defined.

There are probably different technical cases depending on the type of the target field: 
- For the example above, `Xmp.iptcExt.PersonInImage` is a XmpBag type, like tags when they are exported in `dc:subject`, so it could follow the same structure: 
```
<dc:subject> 
    <rdf:Bag> 
        <rdf:li>Bob</rdf:li> 
        <rdf:li>John</rdf:li>
    </rdf:Bag> 
</dc:subject>
<iptcExt:PersonInImage> 
    <rdf:Bag> 
        <rdf:li>Bob</rdf:li> 
        <rdf:li>John</rdf:li>
    </rdf:Bag> 
</iptcExt:PersonInImage>
```
- When the target field is not a list but a text, it raises the question of how it should be done (maybe something like `TextField=tag1, tag2, tag3` if it is possible)

**Alternatives**

**Additional context**
darktable 3.0.2

**Comment by EC1000** [comment]
It is obviously a low priority (it will only affect you if you use one of those "target fields" in another software), but since I noticed it doing some tests, I thought it would be worth reporting it.

**Comment by phweyland** [comment]
> I think it would make sense to export all tags of level `n` when several tags are defined.

I don't know if there is an easy solution, but that makes sense indeed...

**Comment by phweyland** [comment]
The above fix resolves your issue but opens other questions...

If the structure is the following:
```
people|Smith|Bob
people|Smith|Ann
people|Durkin|John
people|Durkin|Peter
```


If only Bob is tagged on the image.

`Xmp.iptcExt.PersonInImage=$(CATEGORY1(People))  $(CATEGORY0(People)) `

gives: `Bob Smith`

But if Bob and John are tagged on the same image.

that gives: `Smith, Bob Durkin, John`

Maybe for another PR ... :)

**Comment by EC1000** [comment]
@phweyland  Thanks for the (once again) very quick change !

> that gives: `Smith, Bob Durkin, John`

Ahah, ok, I'll try not to set up something like this! It gives funny results indeed in this case (though I understand -- more or less -- why it's logical with the current algorithm)
