### ISSUE TITLE
lens correction with Olympus E-M1 Mark III and zoom lens causes artefacts

### ISSUE THREAD

**Issue by igmerti** [darktable-org/darktable#4966]
**Describe the bug**
Lens correction causes in some situations artefacts at the corners/borders.
This happens only with Olympus E-M1 Mark III and zoom lenses at maximum focal length,
e.g. M.Zuiko_12-40mm_f2.8 at 40 mm or M.Zuiko_40-150mm_f2.8 at 150 mm.
Using another camera (i.e. Olympus E-M10 Mark III) or not the maximum focal length or a prime lens (e.g. M.Zuiko_75mm_f1.8) causes no problems.

**To Reproduce**
Just use the automatic mode of module lens correction.

**Expected behavior**
No artefacts should be visible, like for other focal lenghts.

**Screenshots**
![lens-correction-150mm](https://user-images.githubusercontent.com/57727594/81478672-2031d680-921f-11ea-94d3-201b65f802cc.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Windows 10 (version 1909)
 - OpenCL is activated
 - GeForce GTX 1060 6GB (driver 445.75)

**Additional context**
Using RawTherapee causes no problems.

**Comment by TurboGit** [comment]
This is expected on some lens. You just need to crop after the image has been deformed.

**Comment by parafin** [comment]
Isn't there an automatic crop option in lens correction? Does it fail?
