### ISSUE TITLE
Input field for offset in geotagging panel is reset

### ISSUE THREAD

**Issue by googol42** [darktable-org/darktable#4969]
**Describe the bug**
When I try to change the offset when geotagging my images the offset I choose is not accepted by the gui. I also started darktable with `darktable --configdir /tmp/darktable-config/` to ensure that there is no problem with my config.

**To Reproduce**
1. Start darktable
2. go the the lighttable
3. Open the "geotagging" panel
4. change the offset, e. g. to +01:00:00

**Expected behavior**
The valid offset should be accepted and not be reset by the gui.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2.
 - OS: Archlinux, Linux  5.6.10-arch1-1

**Additional context**
 - Is the issue still present using an empty/new config-dir: **yes**

**Comment by phweyland** [comment]
I cannot reproduce this with current master.

**Comment by googol42** [comment]
What information do you need from me to trace this down?

**Comment by phweyland** [comment]
I'm short in ideas, sorry. That's a very simple use case. I don't see where it can get wrong.

> change the offset, e. g. to +01:00:00

Saying that means that you succeed in typing the new value in, correct ?
Do you press enter ? What do you do after that ? 
When does the new value disappear ?

**Comment by googol42** [comment]
I just figured out what's wrong. The field does not accept the "Tab" key event (which is should, as this is normal gui behaviour). Using "Enter" works :D

**Comment by googol42** [comment]
What information do you need? I think the problem is clear, tabbing out of the field is treated as "aborting" the input, which is unusual behaviour.

**Comment by johnny-bit** [comment]
If we were to change behaviour of "Tab" key for that field, what would you like the behaviour to be? Tab out of input control (or essentially do nothing) or apply values? the problem with Tab key is that it's used in darktable and represents also "show/hide sidepanels".

**Comment by googol42** [comment]
I expect that "Tab" on an input field accepts the values entered.

Examples where darktable already behaves like this:
1. Go the the export module ("export selected"). Change the path, then press ""tab". Result: changed path is accepted and the field doesn't have focus anymore. Or change the max size/dimensions.
1. Or go to the "collect images" module. Select "Tag", write something in the field. Press "Tab". Result: input is accepted.

I considers this standard UI behaviour.
