### ISSUE TITLE
Recursivly add father tags when tagging images

### ISSUE THREAD

**Issue by googol42** [darktable-org/darktable#4970]
**Is your feature request related to a problem? Please describe.**
Tagging images is great. Let us assume you have a tag called "Nature". But you like to take picture of let us say "Flowers". But you consider flowers also nature. So you structure your tags like
- Nature
- Nature|Flowers

When Tagging your images I find it cumbersome and error prone to add both (and possible even more tags, e. g. I could have "Nature|Plants|Flowers") tags to the flower images. *At the end of the day I want flowers to be include in "Nature", but still want flowers to be sub tagged.*

**Describe the solution you'd like**
*Edit: See [this comment](https://github.com/darktable-org/darktable/issues/4970#issuecomment-626305616).*

~It would be great if there would be an option on the tag which (when enabled) add the tag itself to images which are tagged with one of the sub tags.~

~So I would enable the "automatically add tag to all subtags" option on the "Nature" tag. When I manually tag an image as "Nature|Something Else|Flower" the following tags are added automatically:~

- ~Nature~
- ~Nature|Something Else~

~Things to consider 1: Does this option exist for sub tags? What should happen when I edit the tag "Nature|Something Else" when "Nature" has this option enabled? → This Option should only be activatable on root tags.~

~Things to consider 2: When I have "Nature|Plants|Flowers" and I remove the "Nature|Plants|Flowers" tag from an image, the image should still be tagged with "Nature|Plants" and "Nature". Depending on the implemenation this could play a role...~

**Alternatives**
~One could solve this the other way around. Add an option to the child tags to be automatically included in parent tags.~

**Comment by googol42** [comment]
I realised that there is even a better solution: Just change darktables behaviour, that sub tags are included in father tags (optional with a global checkbox to turn this on/off).

This is IMO better, because the GUI behaviour matches with the resulting tags in the images (when exporting). We avoid clash of semantics. The semantic when exporting an image tagged "Nature|Something|Flower" is that all three tags are added separately. Also this solution is much easier to use. Less clutter.

**Comment by phweyland** [comment]
When you tag an image with the last level tag, your image potentially holds all the tags of the path.
1. in collect module you can select any level of tag and collect the images tagged with descendants (ctrl-click or shift-click),
2. at export time, you can ask to omit or export all the hierarchy

See the manual.

**Comment by googol42** [comment]
I did not find this in the manual :-( btw, I like your manual ;-)
