### ISSUE TITLE
Can't save metadata to actual JPEG file anymore (not XMP sidecar)

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4975]
Hello,

I think it's a bug but I'm not 100% certain as I cannot find anything in the doc about it.
I have the feeling I was able to do this before, but cannot confirm

I use DT to add some descriptions & titles to my JPEG files.
I'd like those be be saved in the actual JPEG files, and not only in the XMP sidecar.

I've tried every menu I could to save metadata, refresh exif (merge & overwrite), sync local copy ... to no avail !

Am I missing something or is something indeed broken ?
Shouldn't there be an option to do so ?

Using
Kubuntu 20.04
KDE Plasma 5.18.4
Darktable 3.1.0~git1495.022c2f1f0
QT 5.12.8
Intel Core i7-7700k + 32GB RAM + SSD + NVidia GFX 1070

Thanks
GLLM

**Comment by Nilvus** [comment]
@GLLM: on all menus you've tried, did you tried and set options in export module (spinbutton just on the right of export button)? You should see a metadata line to select.

**Comment by GLLM** [comment]
HI @Nilvus !
Thanks for your swift reply.

I'm not exporting file ... just working on my pictures' library ;)
Trying to impact the original JPEG file's IPTC/EXIF.

Thanks

**Comment by jenshannoschwalm** [comment]
DT will and should **never** change the original files :-)

**Comment by GLLM** [comment]
@jenshannoschwalm : thanks for your swift and clear reply !

Though I'm going to have to use yet another tool to update my JPEG so that the description & title are now withing the file's IPTC ... 
IPTC fields are meant to be changed by the user (but not the actual image data bits, I agree)
