### ISSUE TITLE
[Feature] Enable the Folders in Collect images to show only the selected folder or the selected folder + its subfolders

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#4976]
Hello !

I only browse my pictures by folders, using the Folders option in the collect module.
All my folders do contain :
* my pictures : containing the actual pictures + my assembled pano and HDR pictures
* a pano_part folder, which contains the component of panoramas
* a HDR_part folder, which contains the component of HDR pictures

Whenever Is select a folder, I see all pictures from both the main folder I selected + the pano_part subfolder + the HDR_part subfolder.
Therefore, I see the component of my HDR/pano + the actual assembled pictures at once !

I'd like to have an option to see only the selected  folder and none of its subfolders.
I think this should be a setting as some people may still want to have the current behavior.

I tried using this setting but it has no effect

![image](https://user-images.githubusercontent.com/3989573/81496400-ca5d3d00-92b7-11ea-8927-72c88c80c373.png)

Using
Darktable 3.1.0~git1495.022c2f1f0
on
* Kubuntu 20.04
* KDE Plasma 5.18.4
* QT 5.12.8
* Intel Core i7-7700k + 32GB RAM + SSD + NVidia GFX 1070

Thank you !!

GLLM

**Comment by ptilopteri** [comment]
You already have this capability using "Collect Images"
and the drop-down menu "narrow down search"

I cannot make a screen-shot for you as dt is taking focus
and will not accept outside key strokes

**Comment by ptilopteri** [comment]
here is a screenshot
![Screenshot_20200510_101904-1](https://user-images.githubusercontent.com/32614680/81501797-3a63c700-92a8-11ea-871f-f92aec910791.png)

**Comment by GLLM** [comment]
Hi @ptilopteri !
Thank you for taking the time to reply !
I found what you mention ... but ... i cannot change the folder I'm browsing until I clear the additional criteria added by the Narrow down this search.

So, indeed, it kinda works, but requires many clicks to be activated then deactivated ...
Could probably be more straightforward :)

Thanks for the hint though !
GLLM

**Comment by phweyland** [comment]
> but ... i cannot change the folder I'm browsing until I clear the additional criteria added by the Narrow down this search.

Are you sure ?
I just click inside the first entry box, and the folder tree or film roll list is back, and I can select another one.

**Comment by GLLM** [comment]
@phweyland 
Yup, I do confirm, the folder filter is not showing the rest of the folder tree once I did click on narrow this search.

So, as I browse thanks to folders (to get my folder tree which is sorted the way I like), I need to remove the narrow this search criteria, change folder, then set back the narrow this search.
I'll retry later today, but I'm not sure I missed anything... or what is expected is maybe not user-friendly enough ;-)

Désolé !

**Comment by Nilvus** [comment]
@GLLM: I'm following @phweyland but it's totally possible. You click on the narrow then what @phweyland show above. Then you go on second filter, choose your filter (HDR or whatever you want). You could even add a third/fourth criteria the same way. Then you just click on the first entry (not on the arrow) and you will see all your folders. I do that quite frequently without any problems. You can even go back to other filter and just update them with combobox and entry (or even by changing to exclude or include, etc. with the narrow).

**Comment by GLLM** [comment]
Hi @Nilvus 
thanks for your reply.
I think indeed your last sentence get what I meant.

My collect module permanently has the following 4 filters :
![image](https://user-images.githubusercontent.com/3989573/81864604-28ff1100-956d-11ea-8c08-de37a7adce2d.png)
I saved it as a preset (4 filters) and I always load it (or make sure it is loaded) as soon as I open darktable.
* Folder is my #1 filter, it's the first and always the first I use. I only browse my pics using this one.
* Then I have 3 filters I do use more or less frequently : color tags (frequently), camera, lens.

What I see is that : I set a folder as my first criteria ... it's a folder with subfolders ... but I dont want to see those subfolders
thenmy other criteria are all using the parent folders : the camera/lens/color tag will by default be applicable to all folders : selected + subfolders ... I can easily see it with the number of photos per color tag.

Not sur eif this is clear !

Is it ?

**Comment by GLLM** [comment]
Example :
* photo_folder_1
   L> subfolder_1a
* photo_folder_2
    L> subfolder_2a
    L> subfolder_2b

if my first filter us set on photo_folder_2, any other criteria will be applied on photo_folder_2 + it's 2 subfolders !

As a matter of fact, I dont want my criteria 2, 3 and 4 to see photos from subfolders 2a and 2b.

**Comment by quovadit** [comment]
I would also love to have this feature, to chose whether subfolders are included or not.

With 2 subfolders I now have to define 3 criteria (top folder excluding subfolder1 excluding subfolder2)

For tags there is a very similar function:
- Normal Click: Show only current tag-level (without sub-hierarchy)
- Shift-Click: Also include sub-hierarchy
- Ctrl-Click: Only show sub-hierarchy

Would it be possible to implement the same logic for folders + subfolders?

**Comment by phweyland** [comment]
> For tags there is a very similar function:
> 
>     * Normal Click: Show only current tag-level (without sub-hierarchy)
> 
>     * Shift-Click: Also include sub-hierarchy
> 
>     * Ctrl-Click: Only show sub-hierarchy
> 
> 
> Would it be possible to implement the same logic for folders + subfolders?

Yes,... however the normal click shows all images by default. I'm not sure all people would like to change. 

We could have this:
* Normal click : all including subfolders (as today)
* Shift-click: only current folder (we would loose the new shortcut to filmroll, which may not be a big deal)
* Crtl-click: only subfolders

But this is not consistent across the collect module.

Opinion(s) ?

**Comment by GLLM** [comment]
Hi all,

I'm wondering why having a setting or option to define the folder behavior with regards to subfolder inclusion/non-inclusion is out of the realm of possibilities ?
This could be in the settings section or in the collect module when in folder mode ...
But having work several hours with travel pictures folders, it's quite a nightmare when you have a tree organized as mine

TripName (contains all standard photos + merged panos + merged HDR)
   L  Panorama_partials
   L HDR_partials
   L Timelapse_pics
   L Someone_else_pics

I expect to see only the main photos when select in TripName folder, but I get the Pano_partials, the HDR_partials, the Timelapse_originals as well as my wife's selected pics in my selection ...
needless to say, it's a nightmare ... especially with my naming conventions ...

Thanks
GLLM

**Comment by quovadit** [comment]
Of course it would be possible to add another checkbox in the new collect-module-preferences, whether to include subfolders.

But I am not sure, whether this is the best solution, because for me it's no one-time-decision but it depends on the current situation, if I want to include all subfolders or not.

So it would be easier to use Shift-click (like for tags)

Are there other opinions?

**Comment by GLLM** [comment]
Hi @quovadit !
thanks for your reply ... shift+click would be a working solution indeed.
Thanks
GLLM
