### ISSUE TITLE
crop & rotate shows as having focus when changes committed

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4982]
#4927 introduced a change to make the currently in-focus module have a different appearance. 

When you double-click on the image to commit changes in the crop & rotate module, the module loses focus (calls ``dt_iop_request_focus(NULL)``). However, the indicator still suggests that the module has focus.

Ideally all calls to ``dt_iop_request_focus`` should ensure that the indicator is set/unset appropriately.

**Comment by jenshannoschwalm** [comment]
The button is not redrawn...
