### ISSUE TITLE
[Denoise bilateral filter] Image becomes unusable with black and grey lines

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4984]
"c:\Program Files\darktable\bin\darktable.exe" --version
this is darktable 3.1.0+1512~gba0fbe0d4
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

Was performing denoise bilateral and the image displayed when it was zoomed in 100%
![image](https://user-images.githubusercontent.com/1119439/81519637-93dafd00-935f-11ea-9098-9bc012867bc3.png)

Image when fit to screen
![image](https://user-images.githubusercontent.com/1119439/81519700-c38a0500-935f-11ea-96b4-4893bef7864d.png)

Restarted dt. Image shows up as black. Turn off denoise bilateral and the image is restored.

Image+xmp download
https://www.dropbox.com/s/ovp8rw9xw4jdc9m/P1079996.RW2.zip?dl=0

**Comment by chhil** [comment]
Opencl on/off does not make a difference.

**Comment by jenshannoschwalm** [comment]
can't reproduce on current fedora32 master

**Comment by chhil** [comment]
@jenshannoschwalm Did you try it with the image I uploaded?

**Comment by jenshannoschwalm** [comment]
No until right now :-) I just tried, looks pretty much "overdeveloped" with lots of halos seen at pixel level at the feather edges but **nothing** as you reported...

**Comment by Nilvus** [comment]
Yes you use some modules not recommended to use together. lens correction often have chromatic aberrations fix so use them together is often correct a thing already corrected. And I would not use basic adjustments if you use the trio exposure/color balance/filmicrgb.

**Comment by chhil** [comment]
Happened again with minimal modules.
darktable-3.1.0+1703~g989d68d45-win64


![image](https://user-images.githubusercontent.com/1119439/82443678-817b6480-9abf-11ea-9552-f2d083fa4252.png)

**Comment by chhil** [comment]
After above if I enable local contrast it turns black.

![image](https://user-images.githubusercontent.com/1119439/82443783-b25b9980-9abf-11ea-87e6-5f1c947de396.png)

**Comment by rawfiner** [comment]
Maybe related to #5222

**Comment by Darker** [comment]
Still occurs in 3.2.1
![image](https://user-images.githubusercontent.com/5508988/90035075-adbf0f80-dcc1-11ea-87a4-42a3fcffb856.png)

**Comment by Darker** [comment]
This did not occur before I updated Dartable, so it is not an issue that is unavoidable.

**Comment by esq4** [comment]
The error is still present.

Darktable Version: master
OS: Windows 7

![image](https://user-images.githubusercontent.com/15331117/98409691-e34b7d00-20a5-11eb-9252-223f7b3aefb8.png)

**Comment by esq4** [comment]
From darktable-log.txt (always different, but similar):

```
[dev_pixelpipe] module `raw black/white point' min: (-0.000131) max: (1.032108) [full]
[dev_pixelpipe] module `demosaic' min: (-0.023733; -0.026667; -0.012243) max: (0.942230; 1.127922; 1.059968) [full]
[dev_pixelpipe] module `denoise (bilateral filter)' min: (-0.023733; -0.026667; -0.012243) max: (0.942230; 1.127922; 1.059968) [full]
[dev_pixelpipe] module `input color profile' min: (0.000000; -77.116287; -169.276138) max: (101.932358; 164.440979; 166.465897) [full]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.960159; 1.135357; 1.048174) [full]
[dev_pixelpipe] module `raw black/white point' min: (0.006801) max: (1.032108) [preview]
[dev_pixelpipe] module `demosaic' min: (-0.048702; 0.000000; -0.086761) max: (0.863916; 1.032108; 1.014714) [preview]
[dev_pixelpipe] module `denoise (bilateral filter)' min: (-0.048702; 0.000000; -0.086761) max: (0.861693; 1.032109; 1.014583) [preview]
[dev_pixelpipe] module `input color profile' min: (12.733230; -85.559799; -84.779137) max: (101.047806; 31.167774; 160.604843) [preview]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.900580; 1.118914; 1.000007) [preview]
[dev_pixelpipe] module `denoise (bilateral filter)' outputs NaNs! [full]
[dev_pixelpipe] module `denoise (bilateral filter)' outputs non-finite floats! [full]
[dev_pixelpipe] module `denoise (bilateral filter)' min: (-116068989341470006189908769941160460288.000000; -338074322399436924362671589920516079616.000000; -75628384681181829084608126322816843776.000000) max: (99006665792518084091643444137440575488.000000; 1.127922; 1.059968) [full]
[dev_pixelpipe] module `input color profile' min: (0.000000; -141.965561; -185.749725) max: (105.852364; 312.531799; 182.504074) [full]
[dev_pixelpipe] module `denoise (bilateral filter)' outputs NaNs! [preview]
[dev_pixelpipe] module `denoise (bilateral filter)' min: (-0.048702; 0.000000; -0.086761) max: (0.861878; 1.032109; 4.049309) [preview]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (1.205226; 1.173729; 1.175671) [full]
[dev_pixelpipe] module `input color profile' min: (0.000000; -93.514862; -124.688019) max: (101.047806; 121.765930; 160.104950) [preview]
[dev_pixelpipe] module `output color profile' min: (0.000000; 0.000000; 0.000000) max: (0.939161; 1.118927; 1.024086) [preview]
```

**Comment by johnny-bit** [comment]
This issue is peculiar to reproduce but is reproducible as evidenced by multiple duplicates: #5797, #6065 (that one has xmp file), #6410 and most recently #7141...

pinging @ralfbrown since it might be down to threading/mem access.

**Comment by jenshannoschwalm** [comment]
@chhil and @esq4 you both seem to be able to reproduce. Could you test by using this `src/iop/bilataral.cc` instead of the one in master? (after removing the .txt :-)

It's just a wild idea so no pr yet ...

[bilateral.cc.txt](https://github.com/darktable-org/darktable/files/5977697/bilateral.cc.txt)

**Comment by ralfbrown** [comment]
Unless I missed something, all you've done is replace roi_{in,out}->{width,height} with dedicated variables.  While that's worthwhile all by itself, I don't see how that would affect the output image unless it works around a code-generation bug.

BTW, roi_in and roi_out will always be the same in the current darktable architecture -- the module would have to have a `modify_roi_in` and/or `modify_roi_out` function which adjusts one or the other for them to differ.

**Comment by jenshannoschwalm** [comment]
No @ralfbrown you got it :-) I just had a look at all the code and there were just two things that could go wrong, divide by zero if wrong parameters would be somehow passed or if in/out regions would differ. From my understanding this should not happen too.

**But** it could lead to copy-out-of-bounds errors. The artefacts observed on several screenshot don't convince me of a race condition, (also i would have absolutely no clue where/why). For me the screenshots more look like random data or not initialized memory. Also in multithreaded systems out-of-bounds could lead to such stripes...

One more, i was also worried about crashes reported in one of the close issues and if i remember correctly you were not able to completely fix/understand. Unfortunately i couldn't find crash logs or any dt runs via gdb that could give a better understanding (could also out of bounds copy ...)

So there is a check now that would at least tell about region-size conflicts at, introducing const width / height is probably good anyway.

BTW could you reproduce by any chance possibly even in a reproducible way?

**Comment by chhil** [comment]
> @chhil and @esq4 you both seem to be able to reproduce. Could you test by using this `src/iop/bilataral.cc` instead of the one in master? (after removing the .txt :-)
> 
> It's just a wild idea so no pr yet ...
> 
> [bilateral.cc.txt](https://github.com/darktable-org/darktable/files/5977697/bilateral.cc.txt)

I will try to build with the updated file later today. Though I have purged my images and db's, so maybe reproducing it won't be possible.
