### ISSUE TITLE
Import Lightroom catalog from lrcat file

### ISSUE THREAD

**Issue by ahangarha** [darktable-org/darktable#4986]
**Is your feature request related to a problem? Please describe.**
The issue is that I have been using lightroom till few years ago. That time I used to same catalog in unified format in lightroom catalog (`lrcat`). I didn't save anything in XMP files.

**Describe the solution you'd like**
As lrcat is a sqlite database and is easily readable, it should be easy to read it and fetch relevant data from it and accordingly make XMP files for each photos.

**Alternatives**
This process can be done separately out of Darktable as well. so that the lrcat file be read and converted into XMP files. So that, in next Darktable execution, it gets the data.

**Comment by TurboGit** [comment]
The XMP is a stable format whereas the .lrcat is a SQLIte database and could change format at anytime. Maintaining this would be a big work. What we could have is a Python script (maintained by anyone) to create "fake" XMP out of the .lrcat for  the initial import in dt. The only "easy" part would be to retrieve the keywords. It won't be possible to create XMP or modify the darktable DB for modules as the params are streamed in binary format and I'm not sure the current introspection support supports that.

**Comment by ahangarha** [comment]
This also sounds good. At least it can be a start.

Can you share any specific guide in which I can find structure of both formats?

**Comment by TurboGit** [comment]
For darktable:
`echo ".schema" | sqlite3 ~/.config/darktable/library.db`

Same command for lr, but IIRC the schema is far more complex to understand.

**Comment by ahangarha** [comment]
I might work on it. If so, I might need your help and guidance if you can.

**Comment by TurboGit** [comment]
Sure, as inspiration you may have a look at:
`tools/migrate_capture_one_pro.sql`

But it is old, I have never used it and don't even know if it was working at some point or not.

**Comment by vrnhgd** [comment]
I would also find this useful - have ~20k photos that I'm trying to move over but can't be bothered to export the xmp files manually. Have been working on something similarly in a private repo. Happy to open source it if there's enough demand.

**Comment by ahangarha** [comment]
Would be great if you can release it as Free Software

**Comment by vrnhgd** [comment]
sorry for the delay, was sorting out some licensing questions/concerns from my primary employer. My progress is likely going to be slow, but you can find any tools that I put together for my personal use in [darktable-compat](https://github.com/vrnhgd/darktable-compat).

If there's enough interest in merging this into core darktable would be happy to merge this in at some point, but for now I'd like to keep it as separate to reduce complexity and to avoid indicating widespread support.
