### ISSUE TITLE
culling / selection inconsistencies

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#4987]
**Describe the bug**
Selections between Ctrl-X and X not consistent.

**To Reproduce**

1. Go to lighttable
2. Select two images say A & B
3. Over on a third one, say C
4. Do a `Ctrl+X`, both A & B are displayed, OK
5. Do not move mouse, stay over C
6. Do a X, then C and following pictures are displayed, OK
7. Still not moving, do again a Ctrl+X, and we get the same images displayed as in step 6

**Expected behavior**

In step 7 I would have expected to have A & B displayed as in step 4.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Linux

**Additional context**
- Not related to #4980

**Comment by Nilvus** [comment]
But seems to be related to this issue: #4965
