### ISSUE TITLE
Import and automatic grouping is broken

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#4988]
There is the long pending #3998 issue.

**Describe the bug**
While importing images from a camera or a card the filenames are not kept as they are but are manipulated via `dt_import_session_filename`. This makes sure
1) we have a valid filename **not** existing already
2) it uses `pattern = _import_session_filename_pattern();` to generate a new and unique filename.

The changed filename is not known within `dt_image_import` and as this looks for filenames when automatically grouping this fails in one of two ways
1) In most cases there won't be no groups for jpg&raw as the default pattern includes a counter and the stored filenames are not alike any longer
2) If you do another import later we have a new counter and xx.jpg and xx.raw might not be related at all.

How can this be resolved?
A) For tethering imports we should keep the current way. For imports from camera or card we should ignore the pattern and stay with the old filenames
B) Make 'keep the filename' as default for the pattern
C) Go the hard way and keep a relation between old & new filename somehow and do the grouping using that information.

I am working on this and would propose A but what is the correct way?

**Expected behavior**
automatic grouping should be reliable

**All platforms**

**Comment by GrahamByrnes** [comment]
If I understand, 

- at present both the path _and_ the filename are modified to create a unique name;
- you propose to keep the unique path, but use out-of-camera file names
- it then seems improbable that there will be two filenames coming from the same camera or card that end up with the same complete address.

That seems reasonable: my camera rolls over the image counter every 10,000 images, but even if I was shooting small jpgs on a huge card, the clash would already have occured in the camera; if I loaded a separate card, that would create a new job code.

Is it possible that a direct download from the camera which was loaded with two cards could cause a problem, if it ignored the directory structure on the cards? That seems unlikely, but it's not something I've tried.

Meanwhile, you keep the pattern for tethered sessions, in case someone rifles off 10,000 photos in a single session...
