### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by robertpaul69** [darktable-org/darktable#4992]
Darktable 3.02 windows 10

bug when I reduce a raw picture from 100 % to normal size,  in 'chambre noire'
file with message here 
[darktable_bt_3GYJK0.txt](https://github.com/darktable-org/darktable/files/4609451/darktable_bt_3GYJK0.txt)

**Comment by johnny-bit** [comment]
I see the issue is in toneequalizer module (or rather, that's what reported here)

Can you attach RAW and XMP file and provide step-by-step reproduction of the issue?

Also - can you change title of issue? "error message" isn't very telling, it could be "error when zooming out in darkroom"
