### ISSUE TITLE
Noise profiles for Pentax K-1 Mark II

### ISSUE THREAD

**Issue by gribouilleuse** [darktable-org/darktable#4994]
Hello, 
I have found this noise profiles for Pentax K-1 Mark II on another different git repository :  https://github.com/derekkite/k1mark2darktable 

After few months of test i'm pretty ok with this profiles. It's possible to add them to darktable ?

Sorry i'm not a regular user of github, i don't want to make a mistake ...

**Comment by mazhe** [comment]
Argh, I was about to just submit mine. I tried both the cardboard with holes and the screen methods, but found I prefered the results using the cardboard method:

https://github.com/mazhe/darktable-noiseprofile-k1mk2

Curves are included, I did not do intermediary ISO steps bellow ISO 52100 as interpolated results seemed good enough...

**Comment by gribouilleuse** [comment]
Aw sorry i have posted same question on french forum (https://forums.darktable.fr/showthread.php?tid=4301) on december but i haven't a satifiyng response so i have tried here. I did not know someones was work on this.

Your work is clearly more explained and i can try to test your preset if you want ?

---- 

Et comme tu es français je recommence en français vu que mon anglais est pas terrible ;)

Je suis désolée j'ai posé la question en décembre sur forum Darktable-FR mais je n'ai pas eu de réponses satisfaisante à ce point là du coup j'ai retenté ici sans savoir que tu travaillais la dessus.

Ton travail m'a l'air plus détaillé et mieux expliqué, tu veux que je teste tes presets ?

**Comment by TurboGit** [comment]
> After few months of test i'm pretty ok with this profiles. It's possible to add them to darktable ?

No we cannot as we need the curves to ensure the profile is good.

**Comment by TurboGit** [comment]
> Your work is clearly more explained and i can try to test your preset if you want ?

Yes please, would be nice if you could test then just do a PR referencing this issue as I'll have a look at the curves. Thanks!

**Comment by mazhe** [comment]
> Aw sorry i have posted same question on french forum (https://forums.darktable.fr/showthread.php?tid=4301) on december but i haven't a satifiyng response so i have tried here. I did not know someones was work on this.
> 
> Your work is clearly more explained and i can try to test your preset if you want ?
> 
> Et comme tu es français je recommence en français vu que mon anglais est pas terrible ;)
> 
> Je suis désolée j'ai posé la question en décembre sur forum Darktable-FR mais je n'ai pas eu de réponses satisfaisante à ce point là du coup j'ai retenté ici sans savoir que tu travaillais la dessus.
> 
> Ton travail m'a l'air plus détaillé et mieux expliqué, tu veux que je teste tes presets ?

Pas de soucis, j'ai gardé ces tests privés le temps d'essayer de les améliorer, mais d'autres testeurs seraient bienvenus :)

**Comment by johnny-bit** [comment]
@TurboGit - Matthieu's repo seems to have all the curves necessary...

@mazhe - can you post here the archive generated by noise profiles generator? It would be easier for maintainers to use (probably) :)

**Comment by mazhe** [comment]
Sure, here they are:

https://github.com/mazhe/darktable-noiseprofile-k1mk2/raw/master/darktable-noiseprofile-20200102.tar.gz

(wow time flies so fast)

**Comment by rawfiner** [comment]
Thanks!
