### ISSUE TITLE
xmp:Rating value changes from "-1" to "6"

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#5010]
Hi.

When importing an image with XMP file, the parameter 'xmp:Rating="- 1"' is replaced by 'xmp:Rating="6"'.

To reproduce:
Mark image to reject.
Remove it from collection.
Import this image.

Platform:
Darktable Version: build from master branch (commit 0d2f67e31e97e25312ae08ac8f46fb9e5f6ee101)
OS: Debian 10

**Comment by esq4** [comment]
_0aefb0157 ("Introduce a rejected flag per image and use it.", 2020-04-21)_
Maybe i found a commit that created this problem.

**Comment by TurboGit** [comment]
I'll have a look, but if the problem exists I'm the culprit no question about that :)

**Comment by esq4** [comment]
It seems that the same value is written to the db.

**Comment by TurboGit** [comment]
Now fixed. Fell free to test again and report. Thanks.

**Comment by esq4** [comment]
It seems to work as before :)
Thanks.
