### ISSUE TITLE
"Left" and "Right" accepted as shortcut for darkroom view in preferences, but have no effect

### ISSUE THREAD

**Issue by pasta-farian** [darktable-org/darktable#5011]
**Describe the bug**

In preferences/shortcuts/views/darkroom I can set "Image back" shortcut to "Left" and "Image forward" shortcut to "Right", but then "Left" and "Right" keys do nothing when I'm in darkroom view. Strangely, if I go again to preferences/shortcuts/views/darkroom and change  "Image back"/" "Image forward" to their original setting, DT no longer accepts "Left" or "Right" as a shortcut (with no message), until I restart the app. 

**To Reproduce**

1. Start with a freshly launched DT instance
2. Go to preferences/shortcuts/views/darkroom
3. Double-click on "Image back" and press your Left arrow key. The shortcut will be seemingly accepted.
4. Go to darkroom view and try to use the Left arrow key to go to the previous image. It won't work.
5. Go again to preferences/shortcuts/views/darkroom
6. Now Double-click on "Image forward" and press your Right arrow key. The shortcut will not change to Right arrow (the original one will remain).
7. Restart DT and repeat step 6. Now the shortcut will change to "Right", but still won't work.

**Expected behavior**

In step 4 above, the Left arrow key should take me to the previous image.
In step 6 above, either the shortcut should be accepted or I should get a message that I may not assign it.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Ubuntu 
- OpenCL: "not available on this system" 
- Graphics: Intel HD Graphics 530

**Additional context**

**Comment by elstoc** [comment]
The difficulty with using 'left' and 'right' for those actions is that these are also keys used in the darkroom to move the image around and to change sliders and comboboxes once they have keyboard focus. I'd advise using a different shortcut for now but I agree that it would be a good idea to prevent those keys (at least when used without a modifier) from being assigned in the shortcut preferences window.

**Comment by elstoc** [comment]
An alternative (better?) might be to add the movement functionality in darkroom as explicit shortcuts in the darkroom view, rather than hard-coding the arrow keys (hidden in the code). Then perhaps you could reassign them as you like (they'd show up in preferences as conflicts).

**Comment by dterrahe** [comment]
> Current darkroom functionality allows you to use Ctrl or Alt modifiers to pan the darkroom view a by lesser or greater amount. Using standard keyboard shortcuts would either lose this functionality or require 12 separate shortcuts to be created.

For #8078 I'm envisioning a fallback system that would allow a generic adjustment to be applied to a set of key mappings when (for example) it is used in combination with a modifier key. So you would just map the 4 arrow keys and two fallbacks, alt and ctrl, and be able to use all 12 combinations. You could even map both the normal and numpad arrows to the same action (and WASD as well if you are a gamer) and have the ctrl/alt fallbacks apply to all of them.

But I'm also considering treating arrows (and pgup/pgdown) as special cases because, as you point out, they have specific meaning in the context of sliders as well. It may mean that they will get mapped to an intermediate action object and that both the sliders and the central area subscribe to events from this object.

**Comment by Nilvus** [comment]
@pasta-farian: as #8078 has just been merged and should allow what you ask for in this issue, I close it. This will be now for darktable 3.8 which will be released for Christmas. If you know how to install master (development version) of darktable, you could test it. Feel free to ask to reopen or open a new issue if you succeed to test this new input system manager and couldn't do what you want.
