### ISSUE TITLE
Allow local copies to reside in user-chosen folder

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#5012]
**Is your feature request related to a problem? Please describe.**

The local copies feature in darktable copies files to ~/.cache/darktable.  Space on my /home partition is limited, and I would like to point this to a larger, different volume. I could use symbolic links, but I think it would be cleaner if darktable exposed some way to set the path to put local copies.

**Describe the solution you'd like**

A setting, either in the GUI, or via darktablerc where I can set the path to put local copies. Making the default ~/.cache/darktable is good.

**Alternatives**

I've considered using a symbolic link. This might be tricky on Windows systems.

**Additional context**

**Comment by Thanimal** [comment]
I also would like to see this feature

**Comment by elstoc** [comment]
You might be able to do this by running darktable with `darktable --cachedir <cache directory`. This would put your thumbnail cache in that location as well, which might be what you want anyway.

**Comment by davve2** [comment]
If the option to change this path on startup already exists as suggested by @elstoc  ( with darktable --cachedir <cache directory>.) It should be very easy to allow a config file or a field to select the cache directory. I think it us a nice feature to add. Perhaps this could be managed by a feature to access a config file where all paths are defined, that could have many user cases. Think of how it works in for example sublime text.

**Comment by TurboGit** [comment]
This would open a can of worms. If the location is configurable, a change of location will means that some pictures will be tagged as local copied in the database but not found on disk. This will break the synchronization back when the main location is available and possible will break more things... All in all certainly not easy to support safely.
