### ISSUE TITLE
Image seeing overlay block infos in print view when coming from map one

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5020]
**Describe the bug**
Seeing an image on print mode is shown in hover overlay block infos like in preview or culling mode regardless of overlay mode choosen... if you come from map view. @AlicVB 

**Expected behavior**
Print view is not a place where overlay mode is needed and wanted as we want to see the image we will print only. So no overlay mode could be seen like when you come from lighttable or darkroom view.

**Platform (please complete the following information):**
 - Darktable Version: Master (a100547dff0a22b4f453452018be1e7232670db1)

**Comment by AlicVB** [comment]
should be fixed in #5024
