### ISSUE TITLE
Double click to reset slider is inconsistent in filmic rgb

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#5029]
**Describe the bug**

Filmic rgb doesn't appear to reset values correctly.

**To Reproduce**
1. Open a photo in darktable
2. Activate filmic rgb
3. double click on any slider. When I double click on the middle grey luminance slider, the value "resets" to 3.41%. When I click on the "Reset parameters" button at the top of the module, the value resets to 9.23%.
The white relative luminance resets to 3.29EV from 3.45EV
Black relative exposure resets to -10.23EV from -10.55EV
dynamic range scaling resets to -30% from 0%

The only sliders that reset correctly are shadows/highlights balance and the sliders on the display tab. This is reproducible 100% of the time on my machine with any photo.
No other modules that I had active seem to have this issue.

**Expected behavior**

I expected the double click to not change the default value of the module (ie, it should remain at the same value that the global reset button uses).

**Platform (please complete the following information):**
 - Darktable Version:  3.1.0+1584~gf91b84212
 - OS: archlinux

**Comment by dterrahe** [comment]
Thanks for reporting this and sorry for introducing the problem in the first place. #5113 fixes it for me.

**Comment by groutr** [comment]
@dterrahe Thanks for the fix!
