### ISSUE TITLE
"Cube lut out of range" on export leads to random failed exporting and freeze up

### ISSUE THREAD

**Issue by PhilBaz** [darktable-org/darktable#5032]
The issue is described at end of the thread...copied here

https://discuss.pixls.us/t/cube-lut-lines-number-not-correct-error/17413/14

On exporting images using .cube lut made with 3d lut creator (50 in this bunch), i get an error. Then only a few of the images actually export, and the border of the DT window starts flashing and I get a could not export file error. A few times DT had to be restarted. After trying a number of times still can’t get them all to export without the process mysteriously stopping. I try again and some of the files export, it doesn’t seem to choke on a particular image. Just seems to randomly stop working.

**Comment by johnny-bit** [comment]
@phweyland asked you to provide more info in https://discuss.pixls.us/t/cube-lut-lines-number-not-correct-error/17413/27?u=johnny-bit

Please provide it. Here's the most relevant part:

> About the export, there is another issue (as you say that the images look good on the screen). Do you have any meaningful message ? Can you try to launch dt from the console the option -d all, capture the log into a file and share it ?

**Comment by johnny-bit** [comment]
understood: unclear. Devs have not enough info to start working on the issue. closing.

Please provide the info devs asked about and I'll reopen the issue so the investigation can restart.
