### ISSUE TITLE
Please add keyboard shortcut for add colorpicker - live sample.

### ISSUE THREAD

**Issue by PhilBaz** [darktable-org/darktable#5033]
Please add a keyboard shortcut for add color picker - live sample. Would be nice not to have to mouse back everytime. 

Also, keeping color pickers between different photos is absolutely brilliant!!! Please never change that!

**Comment by elstoc** [comment]
Should be pretty easy. I'll take a look.

**Comment by elstoc** [comment]
Actually, no need - it's already there (shortcuts>modules>color picker>add sample)

**Comment by PhilBaz** [comment]
Ahhh, sorry I was looking here....

https://www.darktable.org/usermanual/en/shortcuts.html

What's the shortcut please?....hahah

**Comment by PhilBaz** [comment]
nevermind.....found it! thank you!

**Comment by PhilBaz** [comment]
yep works like a charm! thanks.

**Comment by elstoc** [comment]
Excellent. Could you close the issue please.

**Comment by PhilBaz** [comment]
Of course....thank you for tolerating my incompetence. Appreciate your effort!

**Comment by elstoc** [comment]
No problem I'm still discovering new stuff myself.
