### ISSUE TITLE
Please allow exporting multiple from darkroom with ctrl+e - only current exports

### ISSUE THREAD

**Issue by PhilBaz** [darktable-org/darktable#5034]
Please allow exporting multiple from darkroom with ctrl+e - only current exports. Not all selected.

**Comment by TurboGit** [comment]
That's expected and won't be changed. In darkrroom you export the currently edited image. For exporting multiple pictures go to lighttable.

**Comment by chhil** [comment]
@TurboGit It would be nice if darkroom allowed exporting multiples when duplicates are created.

**Comment by PhilBaz** [comment]
> That's expected and won't be changed. In darkrroom you export the currently edited image. For exporting multiple pictures go to lighttable.

Okay, but if I can see the images I want to export in the darkroom then that just adds extra steps, and so a bit of hassle, especially if I just have to return to darktable to keep working....or I can keep working and then try to remember which images I want to export. Hassle either way, no?

**Comment by spaceChRiS** [comment]
I am using colour labels to indicate that a picture is ready, green in my case. You can then filter for images that have green label and unexported state in the collect module on lighttable.

I think it is reasonable to not allow export of multiple files from darkroom as this would occupy a lot of computing power/memory over a long time, and darkroom would probably miss some of the resources during this time and react slow and sluggish.
