### ISSUE TITLE
graduated density module line jump

### ISSUE THREAD

**Issue by derpafist** [darktable-org/darktable#5036]
I noticed this with version 3 and 3.0.2. When you have the angle in the graduated density module set to 90°, you cannot drag the border line where you want it to be.  You drag, let go and it will jump to the other side of the image, mirrored at the centre of the image. This does not happen, when the angle is set to -90°.

**Comment by TurboGit** [comment]
This is fixed in current master and will be part of next major release.

**Comment by elstoc** [comment]
@TurboGit are you sure? I can replicate this behaviour in current master.

**Comment by TurboGit** [comment]
Maybe not, I had fixed some jumps but there may some remaining issues...

**Comment by TurboGit** [comment]
Should be fixed now.

**Comment by elstoc** [comment]
Looks better now, though there is still a minor issue that if you set the rotation to 90 degrees, move the line to one side of the image, and change the rotation to -90, the line still moves to the opposite side of the screen. Same thing when you change the other way too.

**Comment by TurboGit** [comment]
@elstoc : This is expected, the same is done when switch from 0 to 180.

**Comment by elstoc** [comment]
Fair enough. It's not really a problem.

**Comment by TurboGit** [comment]
No, at this stage it is clearly a feature, but there is no more bugs.
