### ISSUE TITLE
lighttable thumnail display not updated on successive imports

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5038]
openSUSE Tumbleweed 20200511
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1589.5c657aea2
OpenCL on 
i7 12-core 36GB

When performing a second import immediately after the first, the lighttable display is not updated to the new imported photos with view set to "all".  Changing from "all" to anything else and back refreshes the display and displays the newly imported photos.

This condition as existed for > two weeks.

**Comment by AlicVB** [comment]
hmmm... not sure to understand (again... sorry)
when I import a folder, collect module is automatically set to show the imported folder only. So I can't see previously imported images. And I'm not sure what you mean by setting view to "all"... In the filtering toolbar ?

**Comment by ptilopteri** [comment]
I import a group of photos and work them, then import a new group of photos, the new group is not displayed, just blank spaces on lighttable.

Previously, the new import thumbnails displayed on lighttable.

Agree that *only* the new import should be visible on lighttable.

the lighttable display is not being refreshed with the new images

**Comment by AlicVB** [comment]
So I can't reproduce with the following steps : 
1. fresh config and library
2. import a folder
3. wait the folder finished to be imported
4. import another folder

After step 4, all image from the last imported folder are shown...

Can you please test again with fresh master (yours seems to be a little behind and everything is going fast in lighttable area this days)
If you reproduce the problem, can you precise if you have added some extra steps to mines and which ones.
Thanks a lot !

**Comment by ptilopteri** [comment]
I was version current when I filed the problem.

present darktable 3.1.0~git1619.7528a618f
does not exhibit the bug/failed refresh.

tks, will close
