### ISSUE TITLE
On/Off button for modules out of sync

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#5047]
darktable 3.1.0+1599~g7600fb842
OS: Manjaro latest
openCL on
Nvidia GTX-1660.

Take any module, for instance _white balance_.
At start /by default/ it is ON.
Toggle the ON/OFF indicator. Now the indicator goes to OFF, but the module is _not_ turned off.
Hoover the mouse above the indicator, and help text says "white balance is switched on" (but it is not).
Now toggle the ON/OFF indicator. The indicator goes to ON, but the module now turns OFF.
The indicator and module are now out of sync.

The same out-of-sync problem seems to exist for every module.

**Comment by elstoc** [comment]
That's my mistake. Will fix now

**Comment by AxelG-DE** [comment]
I donno if it is related, but from time to time, I have to click two or more times on tone-equalizer on/off button to make it switch on.
@elstoc do I need to file a new issue for such?

**Comment by elstoc** [comment]
You mean after the fix provided in #5050? Did you observe the issue before #5041 was merged?

**Comment by AxelG-DE** [comment]
tbh I did not test before, I would have to checkout at an earlier stage and test, but this has to wait after business hours :-)

**Comment by AxelG-DE** [comment]
I could not wait. I tested. 3.1.0+1580~g62e9ba5de is without that behaviour, means on/off reacts instantly

**Comment by elstoc** [comment]
And to clarify you're getting the issue _after_ #5050?

**Comment by AxelG-DE** [comment]
Yes!
but if the question is, where exactly in between, that would mean I would checkout each step or bisect :-) Definitely needs to wait now :)
From your questions I feel the trend clearly goes to "new issue"

**Comment by elstoc** [comment]
Yes please raise a new issue.

**Comment by AxelG-DE** [comment]
I will

**Comment by elstoc** [comment]
@AxelG-DE I can't reproduce your issue but I've pushed a simplified version which might resolve it (https://github.com/elstoc/darktable/tree/ioptoggle2). Please can you test.

**Comment by AxelG-DE** [comment]
@elstoc 
sorry I issued the Bug report after this. I oversaw the notification of this reply :blush: 
Indeed I will test
