### ISSUE TITLE
Color tag does not get updated in darkroom's filmstrip

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5051]
**Describe the bug**

Other than in the past, the color tag in the filmstrip does not get updated upon pressing F1 to F5. Only after clicking into filmstrip, the update appears

@AlicVB  might be this something for you? :)

**To Reproduce**
1. Go to darkroom
2. Press e.g. F2
3. See in Filmstrip, no update of the red dot

**Expected behavior**

As in the past, red dot should appear/disappear right away

**Screenshots**

If wanted, I can provide a screencast, but cannot (yet) illustrate, the F1 button got pressed

**Platform (please complete the following information):**
 - Darktable Version: **3.1.0+1599~g7600fb842**
 - OS:  ***Gentoo***
 - OpenCL activated or no? **yes**
 - Which graphics card and driver version --> **RTX2070super x11-drivers/nvidia-drivers-440.82-r3**

**Additional context**

**Comment by AlicVB** [comment]
confirmed. that's a refreshing problem. I'll take care.
Thanks for the report
