### ISSUE TITLE
Support for OpenCL on recent Intel IGA under Windows 10 with Intel NEO drivers

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#5054]
**Is your feature request related to a problem? Please describe.**
OpenCL support for Intel chipsets is blacklisted in dt version 3.0.2. However, it is believed that the original reasons for the blacklisting have been mitigated either through fixes in darktable (notably, issues with cache invalidation) or through the improving quality of Intel's libraries, support, and silicon in the domain. (Note: author has no professional connection with Intel!)

Following a review of the historical reasons for blacklisting (see summary below) it has been proposed that whitelisting recent versions of the Intel libraries and a selection of Intel chipsets from Gen 6/Kaby Lake onwards is sensible.

**Describe the solution you'd like**

- [x] Make a Windows build from current master available for this testing purpose. 
- The 3.0.2 equivalent build: [v0.1.0-exp%2Bg905d25d6d](https://github.com/coffeeandspaceships/darktable/releases/tag/v0.1.0-exp%2Bg905d25d6d) is intended to be identical to release except for the de-blacklisting of Neo. 
- The "recent master" binary [v0.1.0-exp%2Bgc6e676570](https://github.com/coffeeandspaceships/darktable/releases/tag/v0.1.0-exp%2Bgc6e676570) will be rebuilt from time to time, but with no formal version control. The exact build will depend on when I last rebased my branches.

- [ ] Volunteers to test various use cases with this build - see below.
- Thanks already to @ariznaf.
- [ ] Investigate repurposing @TurboGit module integration/regression tests https://github.com/darktable-org/darktable/pull/4818. The same principle can be used to compare CPU and GPU output. (suggestion by @johnny-bit)
-  The tests were not targeted for a Windows environment so there is platform support work required.
- [ ] Build a consensus on what is supportable (I am happy to own support triage)
- [ ] Agree target release
- [ ] Implement any additional blacklist/whitelist logic required
- [ ] Profit?!?!

- [ ] Edit https://www.darktable.org/usermanual/en/darktable_and_opencl_system.html to include Intel on Windows (and indeed Windows!)

The target driver for this issue is [Intel Compute Runtime](https://github.com/intel/compute-runtime). 

**Testing**
I will maintain a testing summary in a [Wiki page on my fork.](https://github.com/coffeeandspaceships/darktable/wiki/OpenCL-on-Windows)

Specific cases TBC, but there is a darktable-cltest available.

**Constraints**
- The two libraries blacklisted in current master, "beignet" and "pocl" shall remain blacklisted.
- Darktable requires OpenCL v1.2. NEO support is at 2.1 at the time of writing and it is assumed 1.2 shall remain supported.
- There are as-is guards implemented in dt to defend against egregious implementation issues; for instance a sanity-check at startup to ensure offload to GPU is actually faster than CPU.

**Alternatives**
As discussed above, beignet and pocl are not considered fit for this purpose.

**Additional context**
- NEO is both shorthand for "Intel Compute Runtime" and the name of the Intel development initiative.
- Intel IGA performance and driver quality moved forward considerably with Skylake.
- The NEO initiative appears to have good momentum and is also based right here on github.
- The Intel driver/library build for Windows is built from the same source code as Linux support; support for OpenCL on Intel under Linux was re-enabled over a year ago. 

**History**
- The original commits to blacklist Neo (https://github.com/darktable-org/darktable/commit/4788b382c8278fab0840866db761c40ef6612dcf and https://github.com/darktable-org/darktable/commit/394b66eec61b9a8edc3cf654921f9bc378a8de09) appear to have been in response to [Redmine bug 12541](https://redmine.darktable.org/issues/12541). However it was identified later in the same discussion that you have to regenerate the opencl kernels sometimes after updating the Neo drivers, and that was the likely root cause. 
- https://github.com/darktable-org/darktable/pull/2033 was successfully merged to address this need, making the reason for blacklisting given in 12541 invalid.
- PR 2797  https://github.com/darktable-org/darktable/pull/2797 was created based on the reasoning above. The outcome was that Intel NEO was REMOVED from the blacklist, but only for Linux. The Windows support position was left unclear - hence I am raising this issue, after establishing the way forward in discussion under PR2797.
- @ariznaf reports that OpenCL on Intel works reliably in Capture One.

**Comment by coffeeandspaceships** [comment]
darktable-cltest output on my build system attached
Edited several photos - perfectly stable

[MINGW64_NT-10.0-18363 3.0.7-338.x86_64.txt](https://github.com/darktable-org/darktable/files/4631760/MINGW64_NT-10.0-18363.3.0.7-338.x86_64.txt)

**Comment by johnny-bit** [comment]
Recently @TurboGit created integration testing which helps detect issues created in modules during code update and discrepancies between CPU-only and gpu, however same can be used to test whether opencl output is consistent with known-good state. That could provide basis for deciding if blacklist/whitelisting of some GPU/driver combo is in order.

**Comment by coffeeandspaceships** [comment]
I just found evidence that GPU offload on Windows SPECIFICALLY is supported and that support definitively includes 6th Gen (Skylake), which is very helpful as that is my testing platform.
https://software.intel.com/en-us/forums/intel-c-compiler/topic/624954

And here is the official support statement, which means we can set a constraint that Haswell/4th Gen is the earliest generation supported, and that it must be an IGA that is 4200+ or better. (I would still like to focus during early testing on Skylake/6th or newer however, as I'm a lot more confident that this is usefully performant.)
https://software.intel.com/content/www/us/en/develop/articles/getting-started-with-compute-offload-to-intelr-graphics-technology.html

**Comment by coffeeandspaceships** [comment]
Also in the interests of quality, on my fork I have moved the Appveyor config to the root of the repository and it triggers a build successfully. Compile completes but there is some sort of assembly problem with lensfun. I have no idea what the formal status of Appveyor support is at the moment, so if anyone wants to take a look please shout. For now I can build and package on my local system and find somewhere to host the installer.

Will need to build master AND 3.0.2 / current release, in order to fix any defects in 3.0.2 that we find (there are a number of reported suspicious LUT issues) and check for regressions introduced between 3.0.2 and master.

**Comment by coffeeandspaceships** [comment]
Release for test is now up [on my fork](https://github.com/coffeeandspaceships/darktable/releases).

**Comment by coffeeandspaceships** [comment]
The new comparison tests (understandably) don't work immediately in a minimal MSYS64 environment. My environment is good enough to build dt but there is a whole stack of dependencies needed to run @TurboGit 's use of OpenCV within the "deltae" python script.

I'm stuck in dependency hell with python 3.8 and opencv 4.3 both of which are a little bit too new for the pip ecosystem.

I will try and fix that sometime, but for now I'll change the tests so that they generate the output images using my OpenCL build of dt, but then don't run the comparisons; I'll then run the comparisons in a stable Linux environment somewhere.

**Comment by ariznaf** [comment]
Hi, coffeeandspaceships.

I will try to install your fork as soon as I can.
Do I need to remove official 3.0.2 version?
Is it secure to open the same database?

And finally, which are the test we are expected to conduct?
just darktable-cltest ?

**Comment by coffeeandspaceships** [comment]
Thanks for trying it out. That looks like it is working! My version is built from a recent branch of master so it should not be considered production. 

To formally test it we have not yet agreed how that should be done, and the module tests that were suggested don't work in a Windows environment out of the box. So either I'll get those working, or we'll agree some other way to test. 

Informally - just use it, and see if you observe any better performance compared to the standard 3.0.2 release.

**Comment by ariznaf** [comment]
OK, that was more or less what I had understood from your messages (sorry, I am not English speaker and not always understand well).

Yes it seems to be working (at least it runs).

May you address me to an article explaining how to use other database than the default in darktable?

It is trying to convert the database schema, as it seems 3.1 uses a differente schema.

**Comment by coffeeandspaceships** [comment]
> OK, that was more or less what I had understood from your messages (sorry, I am not English speaker and not always understand well).
I will create a clear summary in the Wiki on my fork.

> It is trying to convert the database schema, as it seems 3.1 uses a differente schema.
I have now created a testing release based on 3.0.2 - [here](https://github.com/coffeeandspaceships/darktable/releases/tag/v0.1.0-exp%2Bg905d25d6d). You should be able to switch between this version and true production with no issues now.
> well, even when I have used a different install directory from darktable 3.0, it seems that the new darktable 3.1 version has replaced the old one, so I cannot run 3.0.2 any more.

I will add a warning to the test instructions, and apologies for not making it clear.
 
> There seems to be many improvements in the 3.1 version. I will report if I see improvements in speed (but I cannot measure it against 3.0.2 version).

Yes - I am using the latest build for my daily use because it is improved in so many ways. BUT it is not a supported release so I would just like to remind everyone this TEST is not supported yet.

> I have not used any LUT transformation, yet, I don't use LUTs in my daily processing. It seems that LUT color processing was one of the problems that drove to opencl NEO being blacklisted.

Yes this makes me think we should have some formal LUT tests, for two reasons. a) A number of the LUT discussions seem to blame OpenCL (one of them even on nVidia!) and then it turned out to be a different root cause. b) It's a heavyweight process so it will really exercise the code properly.

> I will do the testing when a test process is stablished for windows.
Thank you. I will create a repeatable test process when I have dealt with the impediments around carrying out formal release testing under Windows. Unfortunately I think that is going to take some time - will track progress in the checklist at the start of this issue.

**Comment by ariznaf** [comment]
Thanks a lot for all de work

**Comment by coffeeandspaceships** [comment]
Will keep a summary of test preparation work on the Wiki. I have now split this out from the detailed results so it's easy to see progress on either or both.
https://github.com/coffeeandspaceships/darktable/wiki/OpenCL-on-Windows

**Comment by coffeeandspaceships** [comment]
https://github.com/darktable-org/darktable/issues/4749 looks like it may be another case where release 3.0.2 is unstable with OpenCL enabled in the UI, even though it should not be enabled in the underlying behaviour.

**Comment by ariznaf** [comment]
@coffeeandspaceships How is this item going on?

Is there any executable that I can download to do test performance ?

I am using your DT 3.02  with openCL for intel active with no issues.

**Comment by coffeeandspaceships** [comment]
I am waiting for 3.2 release and will discuss with maintainers whether we can look at this for 3.4.

**Comment by ariznaf** [comment]
Hi, @coffeeandspaceships 
I have upgraded to darktable 3.2 (as I wanted some of the new features and the filmic v4 module).

It is great, but of course I have lost hardware accelerated graphics with the Intel integrated graphics card.

Have you recompiled 3.2 with intel cards enabled?

I have checked your fork, but it does not mention v 3.2

**Comment by dterrahe** [comment]
What is the current status of this issue under 3.4/3.4.1?

**Comment by ariznaf** [comment]
There is no official support for HAG under intel cards in 3.4.

You need to recompile the software enabling it, it seems that there is not an installable version that supports it.

I have a new ndivia board that works correctly under opencl.
It would be great to get intel support.

**Comment by MCian42** [comment]
I found the solution on this post : https://www.photo.buet.us/post/darktable-can-t-activate-opencl
I works great for me.
Darktable 3.4.0, Windows 10 20H2, Intel Core i9 9900K, GPU UHD630 driver Intel version 27.20.100.9316 (Feb 18th, 2021)

**Comment by Schedulaar** [comment]
This is still an issue for me. I bought a new laptop with a 11th Gen Intel® Core™ i7-1165G7 and opencl support is not available on my laptop for darktable.

**Comment by ariznaf** [comment]
Well I have it woking in may computer, with an AMD graphics card and the integrated graphics in my i7 processor which I use for rendering miniatures ando other minor tasks in darktable.

The new releases let you use the intel drivers if you tell it to do so.

**Comment by MCian42** [comment]
Hi all 
this works for me (intel Core i9) :
https://www.photo.buet.eu/post/darktable-is-opencl-enabled
https://www.photo.buet.eu/post/darktable-can-t-activate-opencl

**Comment by Nilvus** [comment]
> This is still an issue for me. I bought a new laptop with a 11th Gen Intel® Core™ i7-1165G7 and opencl support is not available on my laptop for darktable.

Which OS do you use? Do you install Intel Neo drivers?

**Comment by Schedulaar** [comment]
> Which OS do you use? Do you install Intel Neo drivers?

I use both Windows 11 and Kubuntu 20.04. On both OSs the box OpenCL is grayed out until I disable the driver check in the dartkablerc as hinted by @MCian42 .

**Comment by ariznaf** [comment]
I have recently upgraded to windows 11 and opencl works too for intel graphics.
I have installed the oficial last drivers from intel for the integrated graphics board.

Of course you need to activate opengl in darktable for blacklisted board (disble the black list) as wat commented previously.
