### ISSUE TITLE
Sort order is misaligned.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#5058]
**Describe the bug**
In lighttable view, using the *sort by* option the chosen order and the order shown are out of sync/scrambled.

**To Reproduce**
1. Colour code a few random shots
2. Select *sort by -> **color label***  (nothing happens)
3. Select *sort by -> **title*** (images are sorted by color label)

**Expected behavior**
Sort order to be as advertised

**Platform (please complete the following information):**
* darktable version: Development 3.1.0+1604
* OS               : Linux - kernel 5.4.0-0.bpo.4-amd64
* Distro           : Debian Buster (rel. 10.4)

**Comment by jade-nl** [comment]
Just did some more testing and the *sort by -> **rating*** is also misaligned.

1. Rate a few random shots
2. Select *sort by -> **rating*** (nothing happens)
3. Select *sort by -> **full path*** (images are sorted by rating)

**Comment by AlicVB** [comment]
@jpverrue : I think you forgot to add your awesome new sort orders to the filter combobox (in lib/tools/filters.c)

**Comment by jpverrue** [comment]
Oh, yes! I completely forgot them here. I'm correcting it right now!

**Comment by jpverrue** [comment]
Yes, the filters are offset by 4 rows (4, like the 4 new timestamps...). However I think that it is not in libs/tools/filter.c that there is a problem, but in src/common/collection.c. In the dt_collection_update_query() function maybe. At the moment, I don't see anything...

**Comment by AlicVB** [comment]
Well, in filter.c, when one change the combobox, we pass the combobox selected index to collection.c and there, this index is used as a sorting enum value. So the list in the combobox filter need to match the list of the enum. Or we need to do some mapping in filter.c before we pass the values to collection...
(Sorry to not be more precise, I haven't dt code under this eyes just now)

**Comment by jpverrue** [comment]
You're right, it was indeed in filter.c. I did the correction in a local branch. Should I do a PR before pushing or the other way around: push then do the PR? (I'm very wrong with Git!

**Comment by jade-nl** [comment]
Noticed the merge.
Tested it:
All fixed!

Thanks @jpverrue  for the speedy action.
