### ISSUE TITLE
Focus Peaking highlights in lighttable misaligned

### ISSUE THREAD

**Issue by InchoateImages** [darktable-org/darktable#5059]
**Describe the bug**
In lighttable view, turning on Focus Peaking (Ctrl-Shift F) displays focus regions of images but they are not aligned with the displayed image. It looks as though the highlighted focus points come from the un-edited image, not the displayed version of the image. So cropping, rotation, and lens correction seem to displace the focus points from their correct position.

Note that focus highlights in the darkroom view seem to be ok.

**To Reproduce**
1. Open a folder of edited photos in lighttable
2. Turn on focus peaking (Ctrl-Shift F)
3. Observe the alignment of the focus highlights with respect to the image features.

**Expected behavior**
I would expect that the focus highlights would be at least approximately aligned with the underlying image. They are not.

**Screenshots**
![Focus-Peaking-Error](https://user-images.githubusercontent.com/65105194/82017493-22899b80-9638-11ea-8efc-e4f51f479366.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0~git1604.1f74b4108
 - OS: Kubuntu 19.10
 - OpenCL activated: yes
 - Nvidia GTX 960M

**Comment by jade-nl** [comment]
Confirmed.

* darktable version: 3.1.0+1604
* OS               : Linux - kernel 5.4.0-0.bpo.4-amd64
* Distro           : Debian Buster (rel. 10.4)
* OpenCL installed : Yes (nvidia-opencl-common   440.82-1~bpo10+1)
* OpenCL activated : Yes
* GTK+             : 3.24.5-1

**Comment by TurboGit** [comment]
Confirmed too! @aurelienpierre ?

**Comment by jenshannoschwalm** [comment]
It's also in the new culling mode...

**Comment by aurelienpierre** [comment]
Yeah it's an issue with DPI scaling of thumbnails since the rewrite of the lighttable. I had a fix half-working, I need to finish that too.
