### ISSUE TITLE
control log message window does not have rounded corners

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5060]
**Describe the bug**

control log message window does not have rounded corners

**To Reproduce**
1. Go to lighttable
2. Click on Ctrl+E (export)
4. See error log message has no rounded corners

**Expected behavior**

The log message window with slightly rounded corners was looking better to me. I suppose this was a missing part in latest CSS rewrite. 

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/82025543-c81d2900-9691-11ea-8d1a-c1f7b362262e.png)

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian

**Comment by TurboGit** [comment]
@Nilvus : I suppose this is for you. What do you think ?

**Comment by Nilvus** [comment]
Shit, forgot that log messages.
Will be simple to fix that (as I know exactly how I broke that...). I've tested on my last CSS rework this log message on darkroom and there's no background on that view. I will also check background color to have a consistent one with new toast message and theme. Could you assign this to me.

**Comment by TurboGit** [comment]
Assigned to you. Thanks.
