### ISSUE TITLE
Darktable crashes after using "Color Lookup table" module

### ISSUE THREAD

**Issue by hcw70** [darktable-org/darktable#5061]
**Describe the bug**
After adding /enabling the "Color Lookup table" module and doing some edits there,
darktable hangs (unresponsive).
After killing / restarting, the given image was vanished from the library.
It cant be imported, a "Import file" for that hangs again.

**To Reproduce**
Try opening the attached XMP file (you may need to associate this to another raw file to reproduce).
It should hang trying to open the file.

**Expected behavior**
No hangs. Simply opening with edits.

**Platform (please complete the following information):**
 - Darktable Version:darktable	org.darktable.Darktable	3.0.2	stable	flathub	system

 - OS: Ubuntu Linux 19.10.
 - OpenCL activated 
 - NVidia GtX 960M

**Additional context**
See attached XMP file
[2020-05-14 20-33-16 (B,Radius8,Smoothing4).dng.zip](https://github.com/darktable-org/darktable/files/4633285/2020-05-14.20-33-16.B.Radius8.Smoothing4.dng.zip)

**Comment by paperdigits** [comment]
Can you try with OpenCL disabled and see if the result is the same?

**Comment by hcw70** [comment]
Hmm. Looks like currently not reproducible any longer....

**Comment by johnny-bit** [comment]
No log, not reproducible on neither 3.4 nor 3.5
