### ISSUE TITLE
Make tools for drawn masks toggle-able as in the retouch module

### ISSUE THREAD

**Issue by StefanDieke** [darktable-org/darktable#5078]
**Is your feature request related to a problem? Please describe.**

Drawn masks often requiere more than on brush stroke (or circle, elipse or path). It would be nice if these tools could be toggled on and off so that they remain active until they are turned off. When making use of pressure sensitivity when working with a tablet it happens that you lose contact easily. Which, in the current mode, means that you first have to activate the tool again which disrupts the flow of drawing. It's also an issue when using the mouse when you want to draw more than a single part mask. Keeping one tool active until it's deselected or another tool is selected seems to be pretty standard for all kind of graphic programs (eg. GIMP, inkscape etc.) so people are used to this behaviour.

**Describe the solution you'd like**

The retouch module shows my prefered behaviour for the drawing tools. If possible please copy the behaviour of the drawing tools from the retouch module to drawn masks in general.

**Comment by elstoc** [comment]
See the above PR. I think for blend masks the default mode should be single creation so this works in the opposite way to the retouch/spot masks (which default to continuous creation).

**Comment by StefanDieke** [comment]
Unfortunately ctrl+click doesn't change anything for me. I add one shape to the mask, then the mode is automatically switched to 'show and edit'. 
It would be nice to have the option to add shapes first and edit them later. No need to make this the default behaviour. Maybe a checkbox in the settings would be nice to switch the default behaviour according to the individual editing style.

**Comment by elstoc** [comment]
You're testing my PR and not master? You're ctrk-clicking on the add shape icon?

**Comment by StefanDieke** [comment]
Stupid me. Couldn't make sense of PR. How do I install/add your PR?

**Comment by elstoc** [comment]
Assuming you're happy building from source, I think you can create a separate clone straight from my commit (https://github.com/elstoc/darktable/commit/dfd2510d2a340baf4006214709121a087503e57a) and build that using the instructions on the main github page.

**Comment by StefanDieke** [comment]
Hah! Your PR works like a charm! Thank you so much for the solution! And for being that quick! And being patient with me!

**Comment by elstoc** [comment]
> Thank you so much for the solution! And for being that quick!

No problem (full disclosure: I saw your post on the facebook group this morning so it was half finished before you posted the issue!)

I think closing the bug now might be a bit premature though, since my PR hasn't been merged into master yet
