### ISSUE TITLE
Shortcuts for numpad are partially ignored

### ISSUE THREAD

**Issue by StefanDieke** [darktable-org/darktable#5079]
**Describe the bug**

The numpad keys seem to have a default assignment. 
It is possible to reassign some of the numpad keys in  preferences -> shortcuts -> views -> darkroom without any warning of a conflict or that the new assingment will overwrite an old one. 
While the assignment seems to be saved (since the new assignment is shown in the list) it is not applied. The default assignment is still active. 
Other keys don't even copy the new assignment to the list. 
It seems as if some shortcuts accept some bindings while others don't. 
It's confusing.

**To Reproduce**

Go to 'preferences -> shortcuts -> views -> darkroom' and set 
'decrease brush hardness' to 'KP End' by pressing '1' on the numpad, 
'decrease brush opacity' to 'KP Left' by pressing '4' on the numpad, 
'decrease brush size' to 'KP Home' by pressing '7' on the numpad, 
'increase brush hardness' to 'KP Down' by pressing '2' on the numpad, 
'increase brush opacity' to 'KP Begin' by pressing '5' on the numpad,  
'increase brush size' to 'KP Up' by pressing '8' on the numpad. 

Go to the darkroom, select any module, activate drawn mask and pick the brush tool. Move the pointer over the image and alter the brush size using 7 and 8 on the numpad, the opacity with 4 and 5 and the hardness with 1 and 2 and watch the changes in the brush as well as the sliders in the module on the right.
Some assignments work as expected. Some keys affect the sliders, and some don't seem to do anything at all. 

**Expected behavior**

The expected behaviour would be that pressing the keys trigger the shortcuts to which they are assigned. 

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+1574~g4312cb8f1-dirty
 - OS: Manjaro Linux 
 - OpenCL activated 
 - 

**Additional context**

**Comment by StefanDieke** [comment]
It seems as if it's the arrow keys (2,4,6,8) of the numpad which are ignored for shortcuts
.

**Comment by elstoc** [comment]
See comments in #5011. The arrow keys have hard-coded assignments in the darkroom. These _could_ be changed so that they are adjustable shortcuts (meaning they could be reassigned).

**Comment by StefanDieke** [comment]
I checked the comments in #5011 and agree with what you say there. 
Anyway, in my eyes it should possible to assign the numpad keys seperate from the normal arrow keys. Especially since the numpad is next to the normal arrow keys, having them assigned to the same functionality seems pretty limiting. I place my keyboard on the left, the graphics tablet on the right hand side, using the stylus with the right hand, the keyboard with the left hand. So assigning the numpad to some stylus related functionality would be really nice.

**Comment by dterrahe** [comment]
@StefanDieke there's probably a reason why this doesn't work for you, but I just wanted to point out for any other listeners that my _solution_ to this problem is to switch Num-Lock on and then map the resulting KP_1 etc keys. Gtk _shows_ these as just "1", "2" etc, but if you look inside keyboardrc you'll see that the actual key mapped is specific to the numeric keypad and separate from the normal 0-9 keys (that have default mappings to set ratings).

**Comment by Nilvus** [comment]
@StefanDieke: #8078 has just been merged and add a whole new way to set shortcut. A simple way with a new button to set a shortcut quite anywhere. This new button is behind main preferences one. Could you test in actual master this new feature and test if it is now ok for you. If it's ok, please consider closing this issue. If not, maybe precise why and how you test that. This new feature is @dterrahe big work.

**Comment by johnny-bit** [comment]
Tested with InputNG, works. Do keep in mind that numpad keys depend on num-lock status.
