### ISSUE TITLE
Parametric masks - odd interpretation of parameters

### ISSUE THREAD

**Issue by StefanDieke** [darktable-org/darktable#5083]
**Describe the bug**

The parametric masks show an odd behaviour. Or I simply don't get the idea of the parameters right. 
The top left field in the chart is red (255 0 0). When applying a parametric mask only in the R channel, I would assume this field would be part of the selection as long as the right slider on the input channel is on 255 - no matter where the left slider is.  
But that's not the case. With the left slider R159 the red field is part of the selection, while the left slider at R160 and above makes the 255 0 0 field drops out of the selection. 
![Screenshot_rgb-mask-off](https://user-images.githubusercontent.com/34355483/82118926-92a03a80-977a-11ea-8e65-edcfcd9fc2ed.png)
![Screenshot_rgb-mask-R159](https://user-images.githubusercontent.com/34355483/82118929-96cc5800-977a-11ea-926e-2373940519f1.png)
![Screenshot_rgb-mask-R160](https://user-images.githubusercontent.com/34355483/82118935-99c74880-977a-11ea-97db-c5a9eee5b8ea.png)
When moving the right slider to the left, also 159/160 seems to be the border. 

On the other hand the cyan field ( not-red, 0 255 255 ) at bottom left remains part of the selection until the left slider of the parametric mask regarding the red channel is moved from 95 to 96. Cyan being not-red, shouldn't it already drop out of the selection at a value of 1? 

**To Reproduce**

Please  open the chart below in the darkroom. Go to a RGB module (eg RGB-curves), select 'parametric mask'. Turn 'display mask' on. Select the red channel. Move the left bottom slider of the input channel slowly to the right and watch the red (top left) field. Stop moving the slider when the left top field turns from yellow to grey, indicating that it dropped out from the selection.
 
![rgbcmy_gradients](https://user-images.githubusercontent.com/34355483/82119206-f297e080-977c-11ea-889d-621a830c91c0.png)

**Expected behavior**

I would expect the 255 0 0 red field to remain inside the selection no matter what value is selected for the left slider in the red channel. A 200 0 0 red should be part of the selection as long as the left slider is below 200 and the right slider is above two hundred. 
If the left slider is above 0 all colours which have a red value of 0 in rgb should drop out.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+1574~g4312cb8f1-dirty
 - OS: Manjaro Linux
 - OpenCL activated 
 - 

**Additional context**

**Comment by MStraeten** [comment]
do you expect this? left sliders on 254 right sliders on 255?
<img width="895" alt="Bildschirmfoto 2020-05-16 um 17 06 27" src="https://user-images.githubusercontent.com/39386816/82123095-bc1b8f00-9797-11ea-89d5-2ebe07863b5d.png">

**Comment by StefanDieke** [comment]
Yes, that is what I would expect. 255 0 0 being selected when the sliders are 254-255.

**Comment by MStraeten** [comment]
At which position of the Pixel Pipe you're using the mask? the input slider of parametric mask evaluates the values after the predecessor in the pipe while the color picker on the left side gives the value at the end of the pipe.  
i assume you're after "input color profile" and there you're switching over into "linear rec 2020 rgb". At the end of the pipe "output color profile" brings it back into "srgb". 
While you're between input and output colorspace "255" represents the upper bound of a much wider colorspace.
You can see the differences here: https://pixls-discuss.s3.dualstack.us-east-1.amazonaws.com/original/3X/e/8/e83a07b64287d18af78cf5c53808d878c50f0221.png

so it’s not really an issue - there's just no "one number fits it all" value for the endpoint of the slider (it correct when you're in srgb color space)...

**Comment by StefanDieke** [comment]
Thanks a lot for the clearification! You are absolutely right with your assumptions! Obviously I don't understand enough about color spaces so I don't mess around with these settings but leave it with the defaults. 
The max value of 255 triggered my expectation that the masks would refer to RGB color space. 
Just out of interest, has the value of 255 an actual meaning of "max" in those wider color spaces or is it a way to express 100% but with finer steps?

**Comment by MStraeten** [comment]
you can use 255 steps to control the full range of the color space. Other sliders are using a percentage scale - i think it’s a remembrance of older 8bit days ;)

**Comment by StefanDieke** [comment]
As long as we don't fall back to a single sepia channel ... ;-)
