### ISSUE TITLE
Notice provided on every import: "EXIF TAG not found in"

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5084]
openSUSE Tumbleweed 20200513
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1630.a9c0365f4-3031.1.x86_64
OpenCL on 
i7 12-core 36GB

On every import I see "EXIF TAG not found in"

shouldn't this information be suppressed for raw images?
doesn't affect operation but is somewhat disconcerting as if the import
was not successful.

**Comment by phweyland** [comment]
I don't find any corresponding message in dt code ("not found in").
Can it be a rawspeed message (used to open raw files) ?

**Comment by jenshannoschwalm** [comment]
Isn't this an exiv2 message?

**Comment by phweyland** [comment]
> Isn't this an exiv2 message?

Yes, can be too. The full message may help to know ...

**Comment by ptilopteri** [comment]
It is displayed on dt lighttable view during import

attached image
![Screenshot_20200516_220114](https://user-images.githubusercontent.com/32614680/82134055-31e82080-97c1-11ea-8282-eb7e19f89807.png)

**Comment by jenshannoschwalm** [comment]
Can you see the same while re-reading exif data via selected_image->metadata->refresh_exif?

I can't see this in any image import here. Could you share a wrong-doing image?

**Comment by ptilopteri** [comment]
@jenshannoschwalm 
> Can you see the same while re-reading exif data via selected_image->metadata->refresh_exif?

No, not on a single selected image or on a group of selected images.

> I can't see this in any image import here. Could you share a wrong-doing image?

I do not see it on single image imports, only when importing an entire directory.

this group of photos will display the "EXIF TAG not found in" notice
  http://wahoo.no-ip.org/~paka/exif.data.display

**Comment by phweyland** [comment]
With your set of images I don't get the message importing the full directory by import folder and import images (all) as well.
Debian 10 - current master  - libexiv2-14/stable 0.25-4 amd64

**Comment by ptilopteri** [comment]
found my problem, local lua script.  Corrected.

tks, sorry for bother.

closing
