### ISSUE TITLE
Focus Peaking  followed by ctrl+shift+w offsets the peaking in the zoomed image.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#5094]
Current Windows build darktable-3.1.0+1660~gd5e9e177e-win64

Culling mode on.
**ctrl+shift+f** to get focus peaking.
I believe the peaking is offsetted here too.

![image](https://user-images.githubusercontent.com/1119439/82136154-3136a500-9828-11ea-9039-fcc208f93fe9.png)

**ctrl+w** on an image 
Observe peaking is no longer where it should be, its offsetted by the zoom
![image](https://user-images.githubusercontent.com/1119439/82136105-9f2e9c80-9827-11ea-984e-2a4db92f6612.png)

**Comment by MStraeten** [comment]
what is the difference to #5059?

**Comment by chhil** [comment]
No difference. My bad for opening a duplicate issue.
