### ISSUE TITLE
failed to decompress thumbnail for xyz error (3.1.0+1660)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#5099]
**Describe the bug**
These errors started showing up in the console:

```
[mipmap_cache] failed to decompress thumbnail for image 894 from `/home/jade/.cache/dt.dvlp//mipmaps-eea6e81b6163ae69e3e92eaf47c8809278995a6a.d/1/894.jpg'!
[mipmap_cache] failed to decompress thumbnail for image 912 from `/home/jade/.cache/dt.dvlp//mipmaps-eea6e81b6163ae69e3e92eaf47c8809278995a6a.d/1/912.jpg'!
```
Initially just a few but after a while too many to copy/paste here....

**To Reproduce**

0. start darktable from a terminal
1. Open lighttable view
2. Select a screenful of images
3. Select *discard history* from the *history stack* module
4. Exit darktable
5. Start darktable
6. The first errors should now be visible.

**Scenario 2**

0. start darktable from a terminal
1. Open lighttable view
2. Select all images
3. Select *discard history* from the *history stack* module
4. Exit darktable
5. Start darktable
6. Start scrolling up (or down) the page
7. Many, many errors in terminal.

Non of the mentioned files are present:

```
$ ls -l /home/jade/.cache/dt.dvlp//mipmaps-eea6e81b6163ae69e3e92eaf47c8809278995a6a.d/1/998.jpg
ls: cannot access '/home/jade/.cache/dt.dvlp//mipmaps-eea6e81b6163ae69e3e92eaf47c8809278995a6a.d/1/998.jpg': No such file or directory
```

**Expected behavior**
Not to see errors.

**Platform (please complete the following information):**

* darktable version: 3.1.0+1660
* OS               : Linux - kernel 5.4.0-0.bpo.4-amd64
* Distro           : Debian Buster (rel. 10.4)
* OpenCL installed : Yes (nvidia-opencl-common   440.82-1~bpo10+1)
* OpenCL activated : Yes
* GTK+             : 3.24.5-1

**Additional context**
I do believe that this was introduced with this commit (using git bisect):

https://github.com/darktable-org/darktable/pull/5022

Tried removing the caches -> Same result,
Tried cleaning the databases (using scripts from *share/darktable/tools*) -> Same result.
Tried tweaking the db fragmentation threshold -> Same result.

**Comment by jenshannoschwalm** [comment]
Thanks, indeed and my bad :-( fixing pr following

**Comment by jade-nl** [comment]
@jenshannoschwalm : Thanks!
