### ISSUE TITLE
PR #5101 seems buggy

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5104]
**Describe the bug**

After building 3.1.0-1670-g92a7e6aeb suddenly the sort combo box is invisible on 2* and higher selections.
Going back to 3.1.0-1669-g772403c60 everything works as normal

@phweyland could you pls. have an eye on it? :)

**To Reproduce**

**Expected behavior**

Combo box should be displayed and react on 2* and higher (at least) as before

**Screenshots**

![grafik](https://user-images.githubusercontent.com/49004103/82158918-2e20d080-988b-11ea-8cc9-10d0eaf7b1d8.png)

**Comment by phweyland** [comment]
I've tested without *** filter. If you remove it does that still fail ?

**Comment by phweyland** [comment]
My bad. I hope this time the fix is ok ...

**Comment by AxelG-DE** [comment]
No worries and thanks for fast reaction 
#5109 solved it, so I am closing
