### ISSUE TITLE
rejecting twice unrejects an image even if "rating an image one star twice will not zero out the rating" is set

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5115]
I am running the latest master and am working on new databases.
I have checked the option "rating an image one star twice will not zero out the rating". Now I import an image and click 'r' to reject the image. Now I click 'r' again, the image is un-rejected. 
I expect that the image still is rejected because the option "rating an image one star twice will not zero out the rating" is checked.

**Comment by AlicVB** [comment]
as the name says, "rating an image one star twice will not zero out the rating" is for 1 star click not reject...
Now maybe we can change that and extend it to reject also... @TurboGit ?

**Comment by ptilopteri** [comment]
openSUSE Tumbleweed 20200516
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1673.cc8c24f53-3054.1.x86_64
OpenCL on 
i7 12-core 36GB

current master action is toggle when r for "reject" is keyed and the same when the x on the thumbnail is keyed as has been for several years and is expected action.

do not see the described problem with "reject".

**Comment by codingdave** [comment]
@AlicVB the text is misleading because it also works for 2 stars, 3 stars,... So we cannot take the literal meaning of the label. Instead we should aim for consistency. And the stars and reject are in the same unit system.

@ptilopteri it is inconsistent and such a bug. If you want to toggle keep the setting unchecked.

**Comment by GrahamByrnes** [comment]
Strictly, I don't see a contradiction between a setting for stars, and a setting for the reject button. I can see there is a similarity of intent but... for me, personally, I'm fine with that.

**Comment by TurboGit** [comment]
reject is not really a rating. The rating is 0 to 5 stars. We can probably argue hours on this and at the end we will have different views by different people. 

The one star case is to be able to have a rating of 0 and a rating of 0 is different that reject which is supposed to be -1 in XMP.

@AlicVB 
> Now maybe we can change that and extend it to reject also... @TurboGit ?

No we cannot as rejecting twice an image is design to restore the previous rating.

**Comment by codingdave** [comment]
I did not know that and I tested that and I can confirm that it works as you say @TurboGit. Anyhow I propose to change that by a setting because I think the use-case is not making much sense: Why would you want to get back the rating from before rejecting? If you rejected you probably dislike the image. So restoring with less stars is much better if you ask me. Usually a user who is sure it is not a 3 and so rejects the image and then realizes it is not so bad after all would not give it a 3 again but rather a 2, 1, or 0 (but we dont know because we dont know the workflow). 

Since we don't want to change the old behavior for people who like it I suggest that we extend the settings by another checkbox that switches between the current behavior and my expectation. What do you think? Is this a valid feature request that I could file in?

**Comment by TurboGit** [comment]
> is not making much sense: Why would you want to get back the rating from before rejecting?

To undo a mistake even after quitting dt.

> If you rejected you probably dislike the image. 

And you never make mistake ? I sometime reject an image because I thought another version was better but after looking more it was not the case.

> Why would you want to get back the rating from before rejecting?

So let me ask, why would you want to reject an already rejected image and have a no-op ?

**Comment by codingdave** [comment]
This is a very good question: what is my usecase. And honestly I don't remember what triggered me. It might just be that I felt it inconsistent but I dont know my userstory any more. 

I come to the conclusion to agree that there is no reason to change the current behavior even if it feels inconsistent and surprising.
Thanks for clearing me up!

**Comment by codingdave** [comment]
@TurboGit I slept over it and got back my usecase: Given some images, just some of them are rejected, now a selection is done including the rejected and unrejected images. If you press `r` the previously rejected ones are unrejected again. 
I dont consider this correct and such would say this is a bug.
This is different to the star ratings behavior with the checkbox set on and such feels inconsistent.

For me this validates again the request to have setting to change the reject behavior.

**Comment by TurboGit** [comment]
Please open a new issue for this. Really, I don't know what to do in this case!

**Comment by ptilopteri** [comment]
I consider that an abnormal workflow and expectation.  

One would normally reject images to not have them within the
selection as rejection is exclusion, ie: images one excludes from their workflow

**Comment by codingdave** [comment]
Thanks, I will create a new feature request and describe the workflow in
there.

For me this is a valid use case because it happened on my side. You can set
up the filter in such a way that you see all images, also the rejected
ones. This is actually also necessary to invert the rejection as pobry
explained it's use case. Or the other way around: whenever the one use case
is valid, mine is valid, too.

ptilopteri <notifications@github.com> schrieb am Di., 19. Mai 2020, 13:40:
