### ISSUE TITLE
[lighttable] some oddity for history stack stack, copy...

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5118]
**Describe the bug**

When trying to copy history stack with the function in lighttable "copy..." and potentially set 'select none' the tickboxes are totally invisible at the moment.

@Nilvus I learned today, this _might_ be one for you :)

**Expected behavior**

either tick-boxes are visible or clicking the name also activates the relevant entry

BTW: maybe need another BR, but the "always-on", actually do not need to be shown in this dialog at all. As they are redundant, I always have to untick 'em....

**Screenshots**

former view
![Screenshot_20200518_204330](https://user-images.githubusercontent.com/49004103/82249569-4dcafe00-994a-11ea-9a82-cd740df26646.png)

current view all ticks on:
![Screenshot_20200518_204552](https://user-images.githubusercontent.com/49004103/82249602-61766480-994a-11ea-92df-22e89848e643.png)

And last but not least, finally the oddity (all ticks off)
![Screenshot_20200518_204610b](https://user-images.githubusercontent.com/49004103/82249697-8e2a7c00-994a-11ea-9828-974e4fd2634d.png)

**Comment by Nilvus** [comment]
Good catch. I was sure something was forgotten on my last complete rework. Good catch, will see that.

**Comment by TurboGit** [comment]
Arggg!!!!! I didn't check the copy/paste dialog :(

**Comment by AxelG-DE** [comment]
> BTW: maybe need another BR, but the "always-on", actually do not need to be shown in this dialog at all. As they are redundant, I always have to untick 'em....

For that one, do I need to file a separate issue?
Is really annoying, every copy I need to unselect the "always on modules". Not doing so is messing up the history stack
![grafik](https://user-images.githubusercontent.com/49004103/82359590-5da91780-9a08-11ea-96e8-0d90daedb89c.png)

**Comment by parafin** [comment]
But you may have changed settings in these modules...

**Comment by AxelG-DE** [comment]
not that I know of :-). For 12, 13, 14 I am very sure even

**Comment by Nilvus** [comment]
@AxelG-DE: your always-on is not a bug. Sometimes it's necessary to copy/paste, sometimes not. So yes, they need to be shown. Always-on module also have settings. And history can be easily compress, with 'c' shortcut on darkroom, button on development module in lighttable and compress history stack button in darkroom. And you have on development modules 2 modes to select how your copy/paste will be added (on the history on over it). So not an issue/BR and not related to your other one and so CSS...

**Comment by Nilvus** [comment]
Oh, it's not a bug as said but that could be a Feature Request: add a button (for example) on those dialogs to unselect/select always on modules (or something like that).

**Comment by AxelG-DE** [comment]
@Nilvus 
Understand and (almost) accept all your points :)
- Compress history stack still keeps things messed a bit as input/ouput color profile for instance will be in the middle of the history stack
- copy into it, could be work around
- let's see, when does it annoy me as much I will issue a FR :)

**Comment by Nilvus** [comment]
>     * Compress history stack still keeps things messed a bit as input/ouput color profile for instance will be in the middle of the history stack

You seem to not have understand completely what the history is. The history is not the pipeline, so not he order of how modules are applied in the pipeline. The history is the order that you have done and applied. 2 different things, so the input/output could  be at any place. The pipeline order could be seen on the left actives tab in modules.

**Comment by AxelG-DE** [comment]
Darned, I forgot to mention, **I do know the difference** and expected this comment, which let me appear not reasonable *blush*

So, yes, that is clear to me, still prefer the basic modules (WB somehow exception) on bottom of history stack, as I, from time to time, go through it step by step.

But no worries, we don't need to "make an Elefant out of a fly" :-)
