### ISSUE TITLE
Darktable crashes when trying to open and edit RAF within GIMP

### ISSUE THREAD

**Issue by PiFlUn** [darktable-org/darktable#5120]
**Describe the bug**
This is one of the strangest bugs I ever witnessed. When I open GIMP and then within GIMP try to open and edit a RAW-file there are 2 options:
- Darktable crashes after the first alt+tab or
- Darktable crashes after the first step of editing.
Now here comes the interesting part: Running GIMP and DT separetely is not an issue as long as DT is not in a full-sized window, even stranger, I have FIXED the problem by starting GIMP with the RAW-file as argument after rebooting my pc! I do not know whether the fix was the rebooting of the pc or feeding the file directly to GIMP, as it was the first thing that I have tried after reboot.

**To Reproduce**
1. Get a fresh installation of Darktable and GIMP.
2. Run GIMP without arguments.
3. Open any RAW-file within GIMP.
4. alt+tab or try to edit anything in the darkroom.

**Expected behavior**

Darktable not crashing.

**Platform (please complete the following information):**
- Darktable Version: 3.0.2 (installed from Arch Linux User Repository) 
- GIMP Version 2.10 (installed from Arch Linux Repository)
- OS: Manjaro / Arch Linux

**Comment by paperdigits** [comment]
How is GIMP opening darktable?

**Comment by PiFlUn** [comment]
Automatically - if I try to open a RAW-file in GIMP via "Open..." then Darktable fires up.

**Comment by asapelkin** [comment]
+1, i met this strange bug too.

**Comment by PiFlUn** [comment]
KDE 5.18.5.

**Comment by wpferguson** [comment]
Tried to reproduce with dt 3.4.0 and gimp 2.10 and could not.

@PiFlUn, @asapelkin are you still having issues?

**Comment by johnny-bit** [comment]
seems to work for me on current master (basically 3.6 release) + gimp 2.10.24

@PiFlUn & @asapelkin - please check on your end with newest gimp and darktable. it should work. If not - please comment and we'll re-open to investigate further.
