### ISSUE TITLE
Fujifilm X-T4 Noise Profiles (ISO160-12800)

### ISSUE THREAD

**Issue by JonHrovath** [darktable-org/darktable#5121]
I went through and followed the instructions for how to create ISO noise profiles and tested it locally with my X-T4.  From a quick look, it seems to work well.  Attached is the tarball that the script generated.  

Side note trying to generate this. I'm running version 3.0.2 with my main image library, but for testing the X-T4, I have been running off of the latest master build.  While attempting to generate these noise profiles, I found that it was simply stopping the process with no error message since the default 'darktable-cli' was attempting to open my standard 3.0.2 version which doesn't have X-T4 support and I guess failing.  Once I dug into the code to see what it was attempting to do, I changed my PATH to point to my 'master' build of darktable (darktable-unsafe is what I named it) and set that to /opt/darktable-unsafe/bin and then re-ran the noise profile generating script.  That seemed to do the trick and everything ran smoothly after that.  Not sure the best way to document having to do that for a new camera setup or running multiple versions. 

Anyway, I hope this helps the project, since I know it will help me once this gets into the master build.  If anything else is needed, please let me know and I'll try and get back on it.  If RAW files are needed from the X-T4, I can provide whatever.  
[darktable-noiseprofile-20200518.tar.gz](https://github.com/darktable-org/darktable/files/4647925/darktable-noiseprofile-20200518.tar.gz)

**Comment by rawfiner** [comment]
Could you provide profiles for extended iso as well please (iso 80, 100, 125, 25600 and 51200)?

**Comment by JonHrovath** [comment]
Sure thing.  I should have thought of that.  I wasn't sure if those were just regular ISO's gained up in software or not.  I'll get to it in the next 12 hours (once it gets dark where I'm at) and attach a new tarball.

**Comment by rawfiner** [comment]
Thanks :-)

**Comment by JonHrovath** [comment]
I've re-run the noise profile generator with ISO's 80, 100, 125, 25600 and 51200 along with all of the regular ISO's and verified that they are all showing up in darktable when I load them in.  Hopefully I did everything correct this time.  If there is anything else, please let me know.  Thanks.

[darktable-noiseprofile-20200519.tar.gz](https://github.com/darktable-org/darktable/files/4654453/darktable-noiseprofile-20200519.tar.gz)
