### ISSUE TITLE
Initial size of patches in liquify after changing to small image

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#5123]
**Describe the bug**

Open a raw image in liquify, something around 24MPx. Create a warp-patch that is around 2/3 or larger than the height or width of your image. Now close that image and open a small tif of say 400x600Px, go into liquify and press the point tool.

I see an initial warp circle that completely covers the image and has inaccessible control points.

It seems that this is just a parameterisation problem: if you go to `develop/masks/circle.c` you find there is a `dt_conf_get_sanitize` which shrinks previously saved parameters from `darktablerc` down to something compatible with the current display. However this is liquify.c, which is a whole world of its own.

I'll probably try to fix this in the next couple of days, but thought it would be good to get my diagnosis confirmed (or rejected).

Windows 10, cmake, dt310+1680, no openCL.

**Comment by GrahamByrnes** [comment]
BTW, this will probably need to be fiwed soon too:

```
float dt_liquify_ui_widths [] =
{
  // value in 1/96 inch (that is: in pixels on a standard 96 dpi screen)
    2.0, // DT_LIQUIFY_UI_WIDTH_THINLINE
    3.0, // DT_LIQUIFY_UI_WIDTH_THICKLINE
    3.0, // DT_LIQUIFY_UI_WIDTH_DOUBLELINE
    9.0, // DT_LIQUIFY_UI_WIDTH_GIZMO
    7.0, // DT_LIQUIFY_UI_WIDTH_GIZMO_SMALL
  100.0, // DT_LIQUIFY_UI_WIDTH_DEFAULT_RADIUS,
   50.0, // DT_LIQUIFY_UI_WIDTH_DEFAULT_STRENGTH,
    4.0  // DT_LIQUIFY_UI_WIDTH_MIN_DRAG
};
```

**Comment by TurboGit** [comment]
To me your analysis is correct!
