### ISSUE TITLE
dubplicate manager does not show stars anymore after c5f2e533bf7ca8dc157850d86be9ae0a5beeea1d

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5127]
**Describe the bug**

The duplicate manager does not show the stars anymore, as it previously was.

**Bisect**
```
c5f2e533bf7ca8dc157850d86be9ae0a5beeea1d is the first bad commit
commit c5f2e533bf7ca8dc157850d86be9ae0a5beeea1d
Author: AlicVB <dev@lnaa.fr>
Date:   Mon Apr 13 22:07:30 2020 +0200

    thumb : more precise overlays finetuning

 data/darktableconfig.xml.in     |  75 +++++++++++++++--
 data/themes/darktable.css       |  94 +++++++++++++++------
 src/dtgtk/thumbnail.c           | 180 ++++++++++++++++++++++++++++------------
 src/dtgtk/thumbnail.h           |  17 +++-
 src/dtgtk/thumbtable.c          | 120 +++++++++++++++++++++++++--
 src/dtgtk/thumbtable.h          |   5 ++
 src/libs/duplicate.c            |   2 +-
 src/libs/tools/darktable.c      |   1 +
 src/libs/tools/global_toolbox.c | 107 ++++++++++++++++++------
 9 files changed, 485 insertions(+), 116 deletions(-)
```
@AlicVB I donno of my bisect makes sense for you, but at least would appreciate your input :)

**Expected behavior**

as it was

**Screenshots**

It was:
![Screenshot_20200519_195206](https://user-images.githubusercontent.com/49004103/82361712-82eb5500-9a0b-11ea-903a-40e8d1b5933d.png)

Now it is:
![Screenshot_20200519_194918](https://user-images.githubusercontent.com/49004103/82361741-8da5ea00-9a0b-11ea-8265-8d7e83a10f31.png)

**Platform (please complete the following information):**
 - Darktable Version:  current master
 - OS:  Gentoo
 - OpenCL activated or no? --> yes

**Additional context**
 - Can you reproduce with another Darktable version? --> bisected
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
-- gcc 9.0.3
-- CMAKE_BUILD_TYPE="Release"
-- CFLAGS="-march=native -O2 -mtune=native -pipe"
 - Is the issue still present using an empty/new config-dir --> yes

**Comment by Nilvus** [comment]
@AlicVB: as I see, it's probably CSS issue. I see star and have all needed tags but no hover/display effect. Indeed, I've removed the #thumb_main alone (without mode before #thumb_main to solve some other issues) but seems that on duplicate manager, there's no specific class style for this mode.
I think the best safe way would add a specific tag on duplicate manager thumbnail. As thumbnail on duplicate manager are displayed same mode than new overlay always mode, I would suggest to apply the `.dt_overlays_always`. Adding that CSS identifier would apply directly CSS already set, without even changing anything on CSS. But I don't know how to do that. Could you test that?

**Comment by AxelG-DE** [comment]
works, thanks :-)
