### ISSUE TITLE
crash in libdarktable.dylib`dt_exif_xmp_read on reimport of directory

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#5128]
after integrating a pull request (#4940) into my current master build darktable crashes when reimporting the same directory. 

lldb output:
```
2020-05-19 19:55:55.777140+0200 darktable[18488:4973869] flock failed to lock maps file: errno = 35
2020-05-19 19:55:55.777428+0200 darktable[18488:4973869] flock failed to lock maps file: errno = 35
Process 18488 stopped
* thread #7, name = 'worker 1', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100163f3e libdarktable.dylib`dt_exif_xmp_read + 16766
libdarktable.dylib`dt_exif_xmp_read:
->  0x100163f3e <+16766>: ud2
    0x100163f40 <+16768>: movq   0x2bc1d1(%rip), %rax      ; (void *)0x00007fff99c89660: __stderrp
    0x100163f47 <+16775>: movq   %rax, %r14
    0x100163f4a <+16778>: movq   (%rax), %rdi
Target 0: (darktable) stopped.
```
the crash occurs on reimporting a xmp file generated with a build before integrating the pull request

**To Reproduce**
1. get current master
2. build darktable
3. clean .config/darktable and remove any xmp files from your test import directory
4. start darktable, import the test directory with a raw file
5. xmp file is created 
[20190223-IMG_3616.CR2 Kopie.xmp.initial.txt](https://github.com/darktable-org/darktable/files/4652479/20190223-IMG_3616.CR2.Kopie.xmp.initial.txt)
6. get pr #4940 
7. build darktable
8. run darktable and reimport the directory
--> crash

```
Thread 8 Crashed:: worker 5
0   libdarktable.dylib            	0x0000000105e30f3e dt_exif_xmp_read + 16766
1   libdarktable.dylib            	0x0000000105e60634 _image_read_duplicates + 196
2   libdarktable.dylib            	0x0000000105e5c140 dt_image_import_internal + 992
3   libdarktable.dylib            	0x0000000105ec55be dt_film_import1_run + 1198
4   libdarktable.dylib            	0x0000000105ebe005 dt_control_job_execute + 261
5   libdarktable.dylib            	0x0000000105ebe98e dt_control_work + 958
6   libsystem_pthread.dylib       	0x00007fff73373109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff7336eb8b thread_start + 15
```

i don't have and idea why this occurs since none of the features of #4940 are used at this time and a couple of other pull requests can be integrated without this crash. 

**Platform (please complete the following information):**
 - Darktable Version: `darktable 3.1.0+1700~g3c3ea3119a` (initial)
`darktable 3.1.0+1720~gea0d6fa6a0` (with pr #4940)
 - OSX

**Comment by aurelienpierre** [comment]
Not sure if merging a WIP PR is a good metric to start investigating core bugs though. I have changed the parameters structure quite a few times in that PR, so it could be just that.

**Comment by MStraeten** [comment]
i wondered why there's an crash where the new module isn’t used (processing an xmp file) since i cleaned my build directory (make clean and  rm -rf * ) before each build and the installation directories before install there shouldn’t be surviving stuff from former builds.

**Comment by coffeeandspaceships** [comment]
I can tell you why any build from 4958 will fail - they are builds for Windows, not MacOS. Did you mention that issue by mistake?

**Comment by MStraeten** [comment]
thanks, that was a typo - btw: 4958 isn’t a pull request so it's not affecting the code base
