### ISSUE TITLE
lighttable: flashing borders around images randomly (ish)

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5144]
When I exit the darkroom back to the lighttable (file manager), the image I've just edited and the last image in the collection both have a slowly flashing white border around them for a few seconds:

![Screenshot_2020-05-20_21-41-51](https://user-images.githubusercontent.com/9555491/82495337-da102900-9ae2-11ea-9e11-890d327e24a6.png)

It seems that the last image in the collection only flashes if I've edited it in the current session.

In fact, testing further, if I edit every image in turn starting from the last, each time I re-enter the lightroom all of the previously edited images have the same flashing white border, and when I reach the first image in the collection, every image in the collection has the same white border. 

![Screenshot_2020-05-20_21-46-02](https://user-images.githubusercontent.com/9555491/82495740-789c8a00-9ae3-11ea-8716-3d08752629b2.png)

The same doesn't happen if I edit the images in a different order.

Does this border have a purpose / intended behaviour?

@AlicVB?

Issue on 3.1.0+1703~g989d68d45 with and without OpenCL.

**Comment by Nilvus** [comment]
@elstoc: this show last actives images and it's an intended behavior. You could see (change for you want) how those borders works on thumbtable CSS part on keyframes lastactive and .dt_last_active tags.

**Comment by elstoc** [comment]
That would be fine if it were only showing around one image but it doesn't work consistently at the moment.

**Comment by Nilvus** [comment]
> That would be fine if it were only showing around one image but it doesn't work consistently at the moment.
> 
> Edit: sorry I see you were only answering my last question. I'll look at the code you suggested!

Yes. But for other part of my message, it's indeed good to limit images where this is applied. So your PR about that is just welcomed.
