### ISSUE TITLE
[Tone Equalizer] crash after ad path mask misbehavior in soften

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#5145]
darktable 3.1.0+1703~g989d68d45

This backtrace was generated when I was applying a mask using on the soften module using "add path".
As I was dropping points for the mask at one point (see image) the image which was fit to screen started zooming in, its as if the mask was trying to help to put points on the image by zooming and moving the image around.

Image that automatically zoomed in and moved around making it difficult to put points.
![image](https://user-images.githubusercontent.com/1119439/82521097-5fc3c100-9b43-11ea-8a10-2cc50273e658.png)

Then DT crashed.

this is darktable 3.1.0+1703~g989d68d45 reporting an exception:

-------------------

Error occurred on Thursday, May 21, 2020 at 09:08:46.
```

darktable.exe caused an Access Violation at location 0000000065F45539 in module libtoneequal.dll Reading from location 0000000060A01000.

AddrPC           Params
0000000065F45539 000000000645FBF0 0000000064942F28 0000000000000000  libtoneequal.dll!apply_exposure._omp_fn.0  [F:/msys64/home/chill/darktable/src/iop/toneequal.c @ 807]
   805:       for(size_t c = 0; c < ch; ++c)
   806:         out[(i * out_width + j) * ch + c] = (c == 3) ? in[((i + offset_y) * in_width + (j + offset_x)) * ch + 3]  // pass-through alpha mask
>  807:                                                      : in[((i + offset_y) * in_width + (j + offset_x)) * ch + c] *
   808:                                                        correction[(i + offset_y) * in_width + (j + offset_x)];
   809: }
000000000019EAA0 00000000284A6D40 0000000000000000 0000000000000000  libgomp-1.dll!omp_in_final
0000000064945092 000000002522E0E0 0000000000000000 00000000284A6D40  libwinpthread-1.dll!pthread_create_wrapper
00007FFC60B3B04A 00007FFC60B906D0 00000000284A6D40 0000000000000000  msvcrt.dll!_beginthreadex
00007FFC60B3B11C 0000000000000000 0000000000000000 0000000000000000  msvcrt.dll!_endthreadex
00007FFC61F47BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFC629ACE51 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
```

On restarting this is what it opened up into, soften module.
You can see the history on the side if its helpful

![image](https://user-images.githubusercontent.com/1119439/82521250-c2b55800-9b43-11ea-8e3b-97cbdfe23c24.png)

**Comment by aurelienpierre** [comment]
I wonder if I shouldn't remove the padding in tone EQ at all. It triggers too many errors and slowdowns the app. However, without that padding, the zoomed-in and zoomed-out previews will not get exactly the same tone correction at the view edges.

@rawfiner thoughts ?

**Comment by rawfiner** [comment]
Maybe padding can be removed without too much problems by considering image borders as mirrors in the algorithm, instead of clipping the coordinates?
Anyway, if we can remove padding without too much drawbacks I am all in favor of this, as it will definitely make computations at 100% zoom level faster.

**Comment by rawfiner** [comment]
Another option is to recompose a larger image by mixing preview and the image from the full pipeline, run the guided filter on this and then crop the image, but this may give some issues too as preview is not 100% accurate

**Comment by aurelienpierre** [comment]
That's what local laplacian used to do, but it produced lots of inconsistent cache states because cache invalidation was brittle (also that requires to synchronize 2 different pipelines). So I removed the clever caching for 3.0.1.
