### ISSUE TITLE
tiling failed for module 'demosaic'. output might be garbled.

### ISSUE THREAD

**Issue by ieure** [darktable-org/darktable#5146]
**Describe the bug**

I have two images which Darktable won't open, giving the error message:

> tiling failed for module 'demosaic'. output might be garbled.

They show as blank squares in the strip at the bottom, and show that error when opened.

I never enabled the demosaic module, and it's missing the control to disable it.

**To Reproduce**

I don't really know what I did to cause it, so I don't know how to reproduce.  I could provide the CR2 and xmp files, if that would help.

**Expected behavior**

The image should open.  Failing that, it should give me a better error message, ideally with something actionable.  I don't know what tiling is or why it would fail, and I never used the module it mentions.  It is a mystery.

**Screenshots**
![darktable-tiling-failed](https://user-images.githubusercontent.com/35252/82523686-cd3f0580-9ae1-11ea-9751-36a2296aef08.png)

**Platform (please complete the following information):**
 - Darktable Version: 2.6.0
 - OS: Debian 10.4 "buster"
 - I'm not sure how to tell if OpenCL is enabled.  `clinfo` says "Number of platforms 0", so I'm guessing it's not.
 - Intel HD Graphics 530.  Kernel modesetting driver.

**Comment by TurboGit** [comment]
>     * Darktable Version: 2.6.0

Please upgrade and come back if the issue is still present.
