### ISSUE TITLE
single star rating no longer acts a toggle, requires zero star rating to clear

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5151]
openSUSE Tumbleweed 20200519
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1712.47cdebc80-3075.1.x86_64
OpenCL on 
i7 12-core 36GB

historic action, toggle single star rating with keyboard or mouse no longer works on single image or a selection of images.  Requires zero rating to remove single star rating even with the configuration unset, "rating an image one star twice will not zero out the rating".

**Comment by Nilvus** [comment]
double click still works for me.

**Comment by ptilopteri** [comment]
Just tried again with new build of 47cdebc80 (1712) and the toggle action using the mouse works on a single image when only one image is selected or when several images are selected.  Prior, it worked on the entire selection, not just the image under the mouse pointer.

Also using the number (pad) the numeral "one" toggled "all" the selection on/off depending on current state.  Now the numeral one sets one star rating on the entire selection and additional use of the numeral one does nothing, no toggle.  Using zero is required to remove the one star rating and no toggle is performed.  Historically using the mouse or the numeral one would toggle the single star rating.

double click on a "single" image sets and unsets single star rating for that "single" image and does nothing to the other selected images.

actions performed on a selection of images should apply to the entire selection.  Isn't that the purpose of making a selection of images rather than a group?

**Comment by ptilopteri** [comment]
Just noticed, the "R" (reject) toggles reject for a selection of images but mouse clicking on the circled "X" no longer does and should.

Again, actions performed on a selection of images should apply to the entire selection.

**Comment by konig12** [comment]
I am seeing this issue in 3.2.1 as well.

**Comment by konig12** [comment]
First up: I have not contributed to darktable before, so I apologize in advance if what follows does not make sense or is out of line.

This one seemed like a simple enough issue, so I decided to take a look myself. It appears that this probably broke with the re-write of the thumtable (8a3bf52). It seems that in the process of that change the rating accel keys changed from calling dt_ratings_apply to dt_ratings_apply_on_list. This change seemed reasonable to me, so I tried updating dt_ratings_apply_on_image (formerly dt_ratings_apply) as shown below. This did fix the rating toggle issue, though I am uncertain as to what else it may have broken. There are also other ways this could be handled, such as by bringing the one star toggle logic into dt_ratings_apply_on_list. I figured I would share the progress here in the hope that someone who knows more about what is going on could shepherd this through or help me do so.

--- a/src/common/ratings.c
+++ b/src/common/ratings.c
@@ -124,6 +124,12 @@ void dt_ratings_apply_on_list(const GList *img, const int rating, const gboolean
   GList *imgs = g_list_copy((GList *)img);
   if(imgs)
   {
+    if(g_list_next(imgs) == NULL)
+    {
+      dt_ratings_apply_on_image(GPOINTER_TO_INT(imgs->data), rating, true, undo_on, true);
+      return;
+    }
+
     GList *undo = NULL;
     if(undo_on) dt_undo_start_group(darktable.undo, DT_UNDO_RATINGS);

**Comment by ralfbrown** [comment]
On current 3.5.0 master, typing "1" repeatedly toggles the one-star rating for all selected images or the image under the cursor if it's on a non-selected image.  Clicking the first star at bottom left toggles for all selected images; clicking the first star on an image toggles for just that image, but clicking on any of the other stars also only affects the clicked-on image.

@ptilopteri @konig12 are either of you still experiencing trouble toggling the one-star rating?

**Comment by johnny-bit** [comment]
I think it works correctly now - for mouse-based star-rating of group of images, there are buttons at the bottom, shortcuts work, the preference for non-zeroing out rating on double "1" star rating works for all 3 - shortcuts, star icons and buttons at the bottom.

Closing this now since I think all the mentioned issues here are "working". Please comment if I'm wrong and I'll reopen ASAP so we can iron out all remaining problems.
