### ISSUE TITLE
selected group in module group not visible

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5158]
**Describe the bug**

Selected group in module group not visible

**To Reproduce**
1. Go to darkroot
2. Change group in module group 
4. See that the icon is highlighted but no change in background, this makes it hard to see the currently selected group (especially for the tone and color group).

**Expected behavior**
The background change color.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian

**Additional context**

**Comment by TurboGit** [comment]
@Nilvus : This is probably for you !

**Comment by Nilvus** [comment]
Oh shit. Too much cleanup on last PR. I forgot to check that one.
