### ISSUE TITLE
DarkTable 3.0.2 crashes on windows when trying to open the Tether Module

### ISSUE THREAD

**Issue by pxlphoto** [darktable-org/darktable#5161]
I have installed DarkTable on a Windows System (further data in the attached Backtrace).
I used Zadig to install the WinUSB driver for my FujiFilm X-T3 and since then, DarkTable started crashing everytime I tried to open it with the camera on. If I open DarkTable with the camera off it simply refuses to recognize on switching on.
I've tried also with previous versions (till 3.0) but with no luck. Version prior to 3.0 simply do not start.
If there's anything I can do to provide further information or do tests, let me know.

[darktable_bt_938XK0.txt](https://github.com/darktable-org/darktable/files/4667831/darktable_bt_938XK0.txt)

**Comment by eyedear** [comment]
I have compile from source on a windows 10 Machine. i am getting an error during tethering. 
I am using Olympus OM-D E-M1 Mark 2 and OM-D E-M1 Mark 2 both also crashes. zadig driver has been install. i am attaching the back trace log here

hope this help

[darktable_bt_99R7K0.txt](https://github.com/darktable-org/darktable/files/4693499/darktable_bt_99R7K0.txt)
[darktable_bt_P4TRK0.txt](https://github.com/darktable-org/darktable/files/4693500/darktable_bt_P4TRK0.txt)

**Comment by Nilvus** [comment]
This issue is all and 3.6 will be out in about 2 weeks. Some things had been fixed and this should be fixed in actual master (future 3.6). I so close this. Feel free to reopen or ask for it if you can reproduce with darktable 3.6 when it will be out (early july).
