### ISSUE TITLE
Redraw lighttable probably missing after import images from card or camera

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5166]
1. Import new images from card or camera
2. When import is over, see new film roll created (or see already existing film roll if images imported on existing one) and number of images displayed and seems selected but no images displayed on lighttable main view (only the grey background is shown).

I have imported 4 times images this way since a week and all times I reproduce this (minor) issue.

=> Images should be displayed just after import.

=> Clicking after that on the collection and see images displayed. So probably just a missing redraw after importing images from SD card or camera. @AlicVB: maybe for you?

I rarely use import image or from folder ones so not test them.

Tested on last darktable master on Ubuntu 20.04.

**Comment by ptilopteri** [comment]
Probably same as #4933 and #5038 
or very similar

**Comment by Nilvus** [comment]
Not the same I think but similar maybe.
