### ISSUE TITLE
Map-scaling on hidpi displays

### ISSUE THREAD

**Issue by nilsholle** [darktable-org/darktable#5172]
**Describe the bug**
The map is not scaled correctly on hidpi screens.

**To Reproduce**
1. Use a 4K monitor with scaling.
2. Open the map.
3. Get some magnifying glass because you can't read anything.

**Expected behavior**
Fonts in the map should be readable-

**Screenshots**
![Screenshot_20200523_120001](https://user-images.githubusercontent.com/9198471/82727890-8cb3d780-9ced-11ea-8bfa-c0da193f985a.jpg)

**Platform:**
 - Darktable Version: 3.0.1
 - OS: Kubuntu 2.0.4 on X.org (1.5 scaling)
 - OpenCL activated
 - Nvidia 440.64 driver

I haven't checked other setups yet (Windows, Mac, Linux with Wayland, ...).
I can't check with KDE/Gnome on Wayland because of the Nvidia card.

Can anyone reproduce this on different systems?

**Comment by Nilvus** [comment]
This part is not managed directly by darktable. darktable just show osm-gps-map Gtk widget. So this will need an update to that Gtk widget. Unfortunately, it seems that this widget has not been updated since a year. See there: https://github.com/nzjrs/osm-gps-map

**Comment by Nilvus** [comment]
@TurboGit: to be closed?

**Comment by TurboGit** [comment]
Yes, I don't even see the issue. Scrolling will zoom in or out!
