### ISSUE TITLE
Defect on image after applying  lens correction.

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#5178]
**Describe the bug**
Thin black and white stripes appear on image at the edges after applying lens correction. In the example, this is  edge at bottom right and top right.

**To Reproduce**
1. Go to DR
2. Use "lens correction"
3. See stripes

**Screenshots**
![20200523__DSC7045](https://user-images.githubusercontent.com/15331117/82737571-24500f00-9d5c-11ea-879a-5a5d82af9684.jpg)

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian 10
 - OpenCL activated
 - graphics card GeForce GTX 1050 Ti, driver version 440.82-1~bpo10+1

**Comment by jade-nl** [comment]
I cannot reproduce this.

Which Camera and Lens combo gave this result?
Have you tried other combo's?

I tried using using these, without your result:

* Nikon D750 + Nikkor 24-85mm f/3.5-4.5G ED VR
* Sony ILCE-7m2 + Sony FE 35mm f/1.8 ZA
* Panasonic DC-LX100m2 (fixed lens)

My setup:

* darktable version: _Dev. 3.1.0+1741_ and also _Stable 3.0.2_
* OS               : Linux - kernel 5.4.0-0.bpo.4-amd64
* Distro           : Debian Buster (rel. 10.4)
* Graphics card    : GeForce RTX 2060 SUPER
* OpenCL installed : Yes (nvidia-opencl-common   440.82-1~bpo10+1)
* OpenCL activated : Yes
* GTK+             : 3.24.5-1

**Comment by esq4** [comment]
> Have you tried other combo's?

I tried with Nikon D7200, OLYMPUS C740UZ, Canon PowerShot A1200.

**Comment by parafin** [comment]
which lensfun version is used?

**Comment by jade-nl** [comment]
If have 2 shots in my test collection made with a Nikon D7200 with these lenses:
* Nikon AF-S Nikkor 50mm f/1.4G
* Nikon AF-S DX Nikkor 18-55mm f/3.5-5.6G VR II

Both don't have any problem when using the lens correction module.

I tried compressing the history stack and using the lens correction first and doing a bunch of edits first and then applying the lens correction. Both work nicely.

Have you tried the following:
* Starting fresh (move the config dir to a sfe place)
* Deactivating opencl
* updating your lensfun package

**Comment by esq4** [comment]
@jade-nl Thank you, refresh darktablerc helped.
