### ISSUE TITLE
[lighttable] oddity with alt+w

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5180]
**Describe the bug**

First of all the issue I describe here is not consistent. Sometimes it is there, sometimes it works (in the same session) as it should be.

For timelapse purpose, I edit on pic per series (approx 300-600 pics) and copy the history stack over the other pics.

When I go to lighttable and press alt+w, I see something, which might be the embedded jpeg. But not on all pics of the series. (hence it is not a matter of switching on 'half raw' in the settings, I tried, it does not help). 

Most obvious is the crop and rotate is missing, as I croped to 16:9 but the suspicious ones are 3:2 and pretty flat

The same thing applies to culling. Below screenshots, the pics look like are unedited, but they are edited

Again. Even I cannot reliably reproduce. Please do not discard or disregard my report, just because you maybe cannot reproduce.

**Expected behavior**

show the edited photo

**Screenshots**

Edited shot
![Screenshot_20200523_215621](https://user-images.githubusercontent.com/49004103/82739504-5bb0c280-9d40-11ea-9e3a-7f11799b945f.png)

View in lighttable 
![Screenshot_20200523_215606](https://user-images.githubusercontent.com/49004103/82739508-6408fd80-9d40-11ea-9903-6f1b53cdae43.png)

alt+w view 
![Screenshot_20200523_215429](https://user-images.githubusercontent.com/49004103/82739511-6c613880-9d40-11ea-9dd1-f8cc5c88d3a3.png)

culling view (the pics all have the same history stack, even it looks different!)
![Screenshot_20200523_214526](https://user-images.githubusercontent.com/49004103/82739519-7daa4500-9d40-11ea-8fdc-7820cf750e1e.png)

@AlicVB may I ask you to have a look into this and advice me, what I could do more to provide evidences?

**Platform (please complete the following information):**
* darktable version : 3.1.0+1736~ga6fc3dc68
* OS                : Linux - kernel 5.6.11-gentoo
* Distro            : Gentoo Base System release 2.6
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.82-r3
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.16
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by AlicVB** [comment]
hmm... looks like the cache is not generated or we have a problem with the history altered flag...
What you can do to help debugging : 
- rename the cache directory and relaunch dt : are the images still problematic ?
- How are you applying the change to your images : in darkroom individualy, by copy-pasting history, ...
- Last, can you try to launch dt with` -d cache` and look for messages like `[cache] generate mip 5 for image ???? from scratch` where `????` is the id of the problematic image. I'm especially interested of the message when you enter culling, or after some darkroom change

**Comment by AxelG-DE** [comment]
- /opt/darktable/bin/darktable-generate-cache -m 6 is what I have just ran, as I was afraid of the same things
- I edit one pic, then go to lighttable, pic the edited pic, chose history stack / copy. Unselect from botton those always on modules I do no not need and select all other pics and "paste all"
- For "Last", gimme some minutes

**Comment by AxelG-DE** [comment]
@AlicVB 
I did relaunche with renamed cache and the effect is still the same

One image-ID is 113316

So for "Last", the output is (I started dt two times and ammended the log with >> , so don't wonder about timestamp  (and yes, I went forward backward between lighttable filemanager, alt+w there and back to darkroom, and also into cullung, where the pic was still problematic):

```
$ cat dt.cache-debugging.txt | grep 113316
1,814108 [mipmap_cache] grab mip 1 for image 113316 from disk cache
8,211510 [mipmap_cache] grab mip 5 for image 113316 from disk cache
11,440914 [mipmap_cache] grab mip 0 for image 113316 from disk cache
1,803034 [mipmap_cache] grab mip 1 for image 113316 from disk cache
4,892607 [mipmap_cache] grab mip 0 for image 113316 from disk cache
9,687365 [mipmap_cache] grab mip 5 for image 113316 from disk cache
18,650889 [mipmap_cache] generate mip 3 for image 113316 from embedded jpeg

```
[dt.cache-debugging.txt.zip](https://github.com/darktable-org/darktable/files/4672478/dt.cache-debugging.txt.zip)

**Comment by phweyland** [comment]
I don't know if that can help, but just be aware that mipmap knows it has to regenerate the cache when the mipmap hash is not anymore the current hash. Would there be any recently added history operations which wouldn't update the current hash ?

**Comment by AxelG-DE** [comment]
@phweyland 
Thanks for your comment. Especially for your "BTW", what could I do about it? I thought I paste the history-stack and that's about it. Wrong?

**Comment by phweyland** [comment]
> @phweyland
> Thanks for your comment. Especially for your "BTW", what could I do about it? I thought I paste the history-stack and that's about it. Wrong?

Nothing wrong. If you allow overlayed information we could see if images are altered or not, and consequently, if we can find some coherence about the issue you observe.
The rest of my comment was not for you, sorry, but for others developers who could know about potentiel changes.

**Comment by AxelG-DE** [comment]
I have that altered sign only on mouse hover. Currently looking around in the settings and somehow too blind to find it *ashamed*

**Comment by AxelG-DE** [comment]
I think a very helpful screenshot. one can see the altered pucs already from aspect ration, but not all show the altered symbol...

![Screenshot_20200524_155135](https://user-images.githubusercontent.com/49004103/82755848-a250fc00-9dd6-11ea-8842-9120c5f204f8.png)

**Comment by phweyland** [comment]
... strange really

**Comment by phweyland** [comment]
About the altered status, you have also the collect entry "history" which may show ... yet another story...

**Comment by AxelG-DE** [comment]
sorry, I didn't get you. but would that be better discussed on IRC?

**Comment by Nilvus** [comment]
@AxelG-DE: I discover your issue and just an idea. What's happen to an image with no altered icon (and so your dark ones here) if you go on darkroom and just go back on lighttable? Don't make any thing on darkroom, just open it and go back. Then check if the image state has changed (altered icon appeared and history stack applied). It's maybe a sort of refresh issue after your copy/paste history stack on a lot of images...

Just an idea!

**Comment by phweyland** [comment]
> if you go on darkroom and just go back on lighttable? Don't make any thing on darkroom, just open it and go back. Then check if the image state has changed

If that happens this is sad. I've introduced the mipmap hash just to avoid to recalculate the image if no change has been made ... :(

**Comment by AxelG-DE** [comment]
@Nilvus during fiddling around I did that several times. It does not update the situation. I understand that is good news and bad news at the same time :-/

**Comment by AxelG-DE** [comment]
**update 2nd June 2020**

today the situation looks more stable to me, than view days ago, because: 
- all pics I have updated with copy history stack, they do not show the altered symbol
- compressing the history stack in lighttable helps, the altered symbol shows up, but still the unaltered pic is schown in lighttable (no matter the zoom factor or alt-w)
- in darkroom, is the same. Thumbnails are shown unaltered unless you "touched"

Installed dt version       : 3.1.0-1865-g05c4c39a5

I see this issue related to #5285 and #5287

**Comment by AxelG-DE** [comment]
Avoid autoclosure

**Comment by AxelG-DE** [comment]
Currently don't see that issue anymore
