### ISSUE TITLE
Darktable 3.0.2 cannot open - Windows 10

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#5182]
I was not able to find a similar report, so help is appreciated

**Describe the bug**
Upon opening Darktable 3.0.2, I receive an unhandled exception error and a popup stating "the database lock file contains a pid that seems to be alive in your system: 11236".  Prior to that, I was using 3.0.1 and received a different popup stating there was a configuration change that would change settings, and I opted not to make the changes.  DT failed to open after that under both 3.0.1 and 3.0.2

Backtrace:
this is darktable 3.0.2 reporting an exception:

-------------------

Error occurred on Saturday, May 23, 2020 at 21:19:38.

darktable.exe caused an Access Violation at location 0000000063671C6C in module libdarktable.dll Reading from location 0000000000000000.

AddrPC           Params
0000000063671C6C 0000000000000000 0000000000000001 0000000000000001  libdarktable.dll!dt_selection_new
00000000635E6254 00007FFB00000002 0000000000EED8E0 00007FFB00000001  libdarktable.dll!dt_init
0000000000403099 00000000004016B0 0000000000000010 0000000000000000  darktable.exe!0x3099
0000000000401608 000000000000005A 0000000000000001 0000000000408610  darktable.exe!0x1608
00000000004013FE 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x13fe
000000000040154B 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x154b
00007FFB2C0F7BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFB2D18CE51 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.0.2.0
ntdll.dll   	10.0.18362.815
KERNEL32.DLL	10.0.18362.778
KERNELBASE.dll	10.0.18362.815
msvcrt.dll  	7.0.18362.1
libglib-2.0-0.dll	2.64.2.0
ADVAPI32.dll	10.0.18362.752
sechost.dll 	10.0.18362.693
RPCRT4.dll  	10.0.18362.628
ole32.dll   	10.0.18362.693
combase.dll 	10.0.18362.815
ucrtbase.dll	10.0.18362.815
libintl-8.dll	0.19.8.0
bcryptPrimitives.dll	10.0.18362.836
GDI32.dll   	10.0.18362.1
libdarktable.dll
win32u.dll  	10.0.18362.836
PSAPI.DLL   	10.0.18362.1
gdi32full.dll	10.0.18362.836
SHELL32.dll 	10.0.18362.815
msvcp_win.dll	10.0.18362.815
cfgmgr32.dll	10.0.18362.387
shcore.dll  	10.0.18362.836
USER32.dll  	10.0.18362.836
windows.storage.dll	10.0.18362.836
WS2_32.dll  	10.0.18362.387
profapi.dll 	10.0.18362.693
powrprof.dll	10.0.18362.1
UMPDC.dll
shlwapi.dll 	10.0.18362.1
kernel.appcore.dll	10.0.18362.1
cryptsp.dll 	10.0.18362.1
libiconv-2.dll	1.16.0.0
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libstdc++-6.dll
libgcc_s_seh-1.dll
libcairo-2.dll
exchndl.dll 	0.9.2.0
libcurl-4.dll
CRYPT32.dll 	10.0.18362.592
MSASN1.dll  	10.0.18362.1
WLDAP32.dll 	10.0.18362.449
libexiv2.dll
libgdk-3-0.dll	3.24.14.0
libgdk_pixbuf-2.0-0.dll	2.40.0.0
IMM32.dll   	10.0.18362.387
SETUPAPI.dll	10.0.18362.1
bcrypt.dll  	10.0.18362.267
libgmodule-2.0-0.dll	2.64.2.0
libgobject-2.0-0.dll	2.64.2.0
libgphoto2_port-12.dll
libgphoto2-6.dll
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.14.0
libIlmImf-2_4.dll
libjpeg-8.dll
comdlg32.dll	10.0.18362.815
libjson-glib-1.0-0.dll
liblcms2-2.dll
lua53.dll
libpango-1.0-0.dll	1.43.0.0
libpangocairo-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
zlib1.dll
libfontconfig-1.dll
libfreetype-6.dll	2.10.1.0
MSIMG32.dll 	10.0.18362.836
mgwhelp.dll 	0.9.2.0
libpixman-1-0.dll
VERSION.dll 	10.0.18362.1
libbrotlidec.dll
libidn2-0.dll
libnghttp2-14.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.6
libpsl-5.dll
dwmapi.dll  	10.0.18362.267
gdiplus.dll 	10.0.18362.836
WINMM.dll   	10.0.18362.1
libcairo-gobject-2.dll
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.43.0.0
libsystre-0.dll
libexif-12.dll
libbz2-1.dll
libHalf-2_4.dll
libIlmThread-2_4.dll
COMCTL32.dll	6.10.18362.836
WINSPOOL.DRV	10.0.18362.693
libatk-1.0-0.dll	2.36.0.0
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.43.0.0
libthai-0.dll
libzstd.dll
liblzma-5.dll	5.2.5.0
dbghelp.dll 	10.0.18362.1
WINMMBASE.dll	10.0.18362.1
USP10.dll   	10.0.18362.476
libtre-5.dll
IPHLPAPI.DLL	10.0.18362.1
PROPSYS.dll 	7.0.18362.815
OLEAUT32.dll	10.0.18362.836
libgraphite2.dll
libdatrie-1.dll
dbgcore.DLL 	10.0.18362.1
libgomp-1.dll
libopenjp2-7.dll
librsvg-2-2.dll
libsecret-1-0.dll
libexpat-1.dll
libcrypto-1_1-x64.dll	1.1.1.6
libgio-2.0-0.dll	2.64.2.0
libfribidi-0.dll
libffi-7.dll
libltdl-7.dll
libIex-2_4.dll
libImath-2_4.dll
libunistring-2.dll	0.9.10.0
libbrotlicommon.dll
libgcrypt-20.dll	1.8.5.54720
USERENV.dll 	10.0.18362.387
DNSAPI.dll  	10.0.18362.815
NSI.dll     	10.0.18362.449
CRYPTBASE.DLL	10.0.18362.1
libgpg-error-0.dll	1.37.0.0
rsaenh.dll  	10.0.18362.1
uxtheme.dll 	10.0.18362.449
clbcatq.dll 	2001.12.10941.16384
mswsock.dll 	10.0.18362.815
MSCTF.dll   	10.0.18362.752
DEVOBJ.dll  	10.0.18362.387
WINTRUST.dll	10.0.18362.387
TextInputFramework.dll	10.0.18362.693
CoreMessaging.dll	10.0.18362.836
CoreUIComponents.dll	10.0.18362.207
ntmarta.dll 	10.0.18362.1
wintypes.dll	10.0.18362.836
Oleacc.dll  	7.2.18362.1
iertutil.dll	11.0.18362.815

Windows 10.0.18363
DrMingw 0.9.2

**To Reproduce**
1. Open DT
2. Error messages appear, and DT fails to open

**Screenshots**
See attached
![darktable screenshot error](https://user-images.githubusercontent.com/61152378/82743931-083e7480-9d40-11ea-97eb-b07bc4fa6e23.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Windows 10
 - AMD A8-7410 APU with AMD Radeon R5 Graphics, 8GB RAM, 64 bit OS and x64 based processor

**Additional context**
Occurred with 3.0.1 and 3.0.2.  Downloaded from Darktable.org

Your help is greatly appreciated.

**Comment by ptilopteri** [comment]
It may be as simple and finding and removing the lock file.  I do not have windows and have no idea where the lock file is.  >>probably<< under appdata

**Comment by coffeeandspaceships** [comment]
Yup, looks like things you would expect to find in .config  on Linux are here in Windows:
```C:\Users\<username>\AppData\Local\darktable```

Have a look in there and see there are any .lock files? If so, make sure darktable is NOT running, and remove them. They will be regenerated automatically and they do not contain user data.

**Comment by Dave22152** [comment]
I removed the lock file as you both recommended, and still no luck.  I followed the advice on another forum and completely removed all traced of DT from my Appdata and then reinstalled, which did the trick.  Fortunately, I was able to restore most of my styles and tags from backups, so I'm good to go at this point.  I'll close the issue at this point. Thanks for your help!
