### ISSUE TITLE
Expose vendor-specific dynamic range metadata to user

### ISSUE THREAD

**Issue by dericke** [darktable-org/darktable#5183]
**Is your feature request related to a problem? Please describe.**
Major camera manufacturers each have their own solutions for boosting the apparent dynamic range of an image, typically by underexposing the image and then compensating with in-camera processing. Nikon calls this Active D-Lighting, Fujifilm simply calls it Dynamic Range, and Sony calls it Dynamic Range Optimizer. When the image is captured in raw format, the vendor's own raw processing software will typically read the setting from the metadata and apply the same adjustments that the camera would have, rendering a properly-exposed image. When viewing these same raw files in a 3rd party developer, such as darktable, these adjustments are not applied, and the developed image will appear underexposed by default.

**Describe the solution you'd like**
exiv2 supports the related metadata tags for Nikon, Fujifilm, and Sony's solutions. darktable could therefore read these metadata tags and expose them to the user, who could then use the tag to either automatically or manually apply a correction for the underexposure. 

I think the most important place to expose these tags would be in the "auto apply this preset to matching images" dialog, under **Preferences**>**presets** . The user could then decide how they want to utilize this metadata tag, for example by auto-applying a flat +1 or +2 stops of exposure, or perhaps a preset with the shadows and highlights module.

Secondarily, I would like to see these tags displayed in the "image information" pane, to inform manual editing.

**Alternatives**
The user could use a second program to display the tag's value and use it to inform their editing in darktable. However, switching between two programs is not convenient, and does not allow compensation to be automatically applied in the same way that 1st party-software would do.

I also considered that perhaps darktable could try to replicate the process these various 1st-party raw developers apply, but that seems like more development time and less user control than exposing the tags to the user and allowing the user to decide what to do with the information.

**Comment by parafin** [comment]
Main alternative is not to use these modes, but manually do exposure compensation when needed;) Relying on some magic camera firmware option is conflicting with the idea of doing raw image processing IMHO.

**Comment by dericke** [comment]
@parafin, in a raw workflow, these modes function as automatic exposure compensation. There's nothing about that more "magic" or in conflict with raw image processing than autofocus or evaluative matrix metering.

Let's say that I use manual exposure compensation instead of automatic exposure compensation, as you suggest. That metadata tag also does not appear in the "auto apply this preset to matching images" dialog, so I still can't auto-apply a preset to such underexposed images.

**Comment by aurelienpierre** [comment]
Fixed with scene-referred workflow in master.
