### ISSUE TITLE
module group bar lost? (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by HannuEKN** [darktable-org/darktable#5187]
$ darktable --version
this is darktable 3.0.1
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

---
Somehow the module GROUP selection bar (just above module search)  has disappeared, screenshot and darktablerc available on dropbox:
https://www.dropbox.com/sh/n2njfdgah5cnsz8/AACIBOVVfv3_BNmECBOlpZYya?dl=0

As I remove darktablerc a new one is created, and the bar appears, but all my new settings are lost.

**Comment by ptilopteri** [comment]
do a diff for your darktablerc when the bar shows the darktablerc where it does not show and see if you can just edit the rd-file instead of replacing it.  Something is telling the bar to not be visible, need to determine what that is.

**Comment by elstoc** [comment]
Go to the preferences dialog and there should be an option under "GUI options" > "darkroom" > "show search module text entry". Set this to either "show both" or "show groups"

**Comment by Nilvus** [comment]
As this is probably solved in preferences dialog window, think of closing the issue to help developers see which issues remains to work on.

**Comment by HannuEKN** [comment]
It was the setting, 
BUT I do not find it intuitive and clear that THIS setting is the one to change.
