### ISSUE TITLE
"paste" and "paste all" remain grayed out, not active

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5188]
openSUSE Tumbleweed 20200520
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1749.593f29a92-3096.1.x86_64
OpenCL on 
i7 12-core 36GB

after copying any or all of the history stack, "paste" and "paste all" do not indicate active state, remain light gray but mouse clicking on either performs expect action as do the hot keys

**Comment by Nilvus** [comment]
Confirm but only when copy with shortcuts. Using buttons to copy and paste and paste all buttons become active. @elstoc: maybe it's not from your work but as I remember you recently update some things on shortcuts...

**Comment by elstoc** [comment]
I'm not 100% certain how to reproduce the issue but there are problems with the default copy shortcut (among others) on the history stack module. It appears that ctrl+c (amongst others) is set up twice, for both "modules>history stack>copy all" and for "views>thumbtable>copy history".

If I try to change the ctrl+c shortcut in the history stack, to the same (ctrl+c) shortcut, it shows as a conflict.

 @AlicVB?
