### ISSUE TITLE
Don't save a special view for color assessment mode

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#5200]
When toggling on/off the ISO 12646 mode (color assessment mode) in darkroom, the collapsed state of GUI panels but also their width (since we can dynamically resize them) is kept in memory, for each view mode (default darkroom or darkroom in color assessment mode).

As a result, when toggling the color mode, the whole GUI moves and shrinks/dilate. This behaviour is confusing for several users who would prefer to keep the whole GUI as-is (or, at least, keep the current width of the sidebars), and only add or remove the white frame.

The current proposal is to make color assessment only a sub-option of darkroom and not a whole view state. Panels should be preserved and managed apart.

**Comment by Egocentrix** [comment]
I hadn't noticed it is a different view (I don't mess with the GUI that much), but I agree with you. It makes more sense to treat the colour assessment in the same way as the overexposure and gamut warnings. Their buttons are in the same bar as well.

**Comment by aurelienpierre** [comment]
> I know I'm not really involved with development, but I am a heavy dt user. If my feedback is out of place here please let me know and I will not do it again :)

It's fine, don't apologize :grin:
