### ISSUE TITLE
Noise profile for the Olympus Tough TG-6

### ISSUE THREAD

**Issue by sboukortt** [darktable-org/darktable#5209]
The fit for very high ISO settings (≥ 6400, the camera calls them “extended”) looks a bit strange for red and blue. Is it something that I can do much about?

[darktable-noiseprofile-20200526.tar.gz](https://github.com/darktable-org/darktable/files/4684679/darktable-noiseprofile-20200526.tar.gz)

**Comment by hellbuster** [comment]
I tested the profile and it seems good. I didn't test with extended ISO images, but I could if needed.

**Comment by hellbuster** [comment]
I took the liberty of opening a Pull Request #5397 with these profiles.

**Comment by TurboGit** [comment]
Merged.
