### ISSUE TITLE
Darktable crashes on launch in Windows 10 x64

### ISSUE THREAD

**Issue by scyg** [darktable-org/darktable#5220]
**Describe the bug**
Darktable crashes when launching in Windows 10 64-bit.

**To Reproduce**
1. Click on Darktable shortcut on desktop or Darktable icon in C:/Program Files/darktable/bin
2. Receive "Error!" dialog: "An unhandled exception occurred. Backtrace will be written to: <path> after you click the OK button. If you report this issue, please share this backtrace with the developers."

**Expected behavior**
Application should launch

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.0.2-win64
 - OS: Windows 10
 - OpenCL not installed
 - AMD Radeon R7200 series

**Additional context**
Contents of backtrace file:

this is darktable 3.0.2 reporting an exception:

-------------------

Error occurred on Thursday, May 28, 2020 at 12:40:45.

darktable.exe caused an Access Violation at location 00007FFF0FFF0819 in module igdrclneo64.dll Reading from location 0000000000000020.

AddrPC           Params
00007FFF0FFF0819 000000000061E838 00007FFF101ACD00 0000000000000001  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FFF0FFDC4A7 00000000001AEB40 0000000000000001 0000000000000001  igdrclneo64.dll!0x7fff0001c4a7
00007FFF1002CEDA 00003DA03A81C8A0 0000000000000000 0000000000000000  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FFF0FFDD10E 00000000001AEB20 0000000000000000 0000000000000000  igdrclneo64.dll!clGetPlatformIDs
00007FFF0FFE41E9 00000000001AEB40 00007FFF0FFE3C80 00000000001AEB20  igdrclneo64.dll!clEnqueueTask
00007FFF27C632B5 00007FFF32F5F360 0000000000000000 0000000000000000  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FFF27C2C85B 00007FFF27C248A9 00007FFF32F6A9E8 000000000061EF72  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FFF32F51158 000000000061EF20 0000000000000000 00007FFF27C20000  OpenCL.dll!0x7fff00001158
00007FFF32F5353B 0000000000000000 0000000000000000 0000000000000001  OpenCL.dll!clWaitForEvents
00007FFF4192B05F 0000000004BB9AB0 0000000000000000 000000000061F4D4  ntdll.dll!RtlRunOnceExecuteOnce
00007FFF3EFB20BB 0000000000000002 0000000000000014 0000000004BB9AB0  KERNELBASE.dll!InitOnceExecuteOnce
00007FFF32F52E4C 0000000000000300 0000000004BB9AB0 0000000004BE7F20  OpenCL.dll!clGetPlatformIDs
000000006366A5BD 000000000061F8A0 0000000000000000 0000000000000000  libdarktable.dll!dt_opencl_init
00000000635E62D0 00007FFF00000001 00000000035ED700 00007FFF00000001  libdarktable.dll!dt_init
0000000000403099 00000000004016B0 0000000000000010 0000000000000000  darktable.exe!0x3099
0000000000401608 000000000000005A 0000000000000000 0000000000408610  darktable.exe!0x1608
00000000004013FE 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x13fe
000000000040154B 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x154b
00007FFF3FBB7BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFF4198CE51 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.0.2.0
ntdll.dll   	10.0.18362.815
KERNEL32.DLL	10.0.18362.778
KERNELBASE.dll	10.0.18362.815
msvcrt.dll  	7.0.18362.1
libintl-8.dll	0.19.8.0
libdarktable.dll
ADVAPI32.dll	10.0.18362.752
GDI32.dll   	10.0.18362.1
sechost.dll 	10.0.18362.693
win32u.dll  	10.0.18362.836
RPCRT4.dll  	10.0.18362.628
gdi32full.dll	10.0.18362.836
libiconv-2.dll	1.16.0.0
msvcp_win.dll	10.0.18362.815
ucrtbase.dll	10.0.18362.815
USER32.dll  	10.0.18362.836
ole32.dll   	10.0.18362.693
combase.dll 	10.0.18362.815
bcryptPrimitives.dll	10.0.18362.836
PSAPI.DLL   	10.0.18362.1
SHELL32.dll 	10.0.18362.815
libwinpthread-1.dll	1.0.0.0
cfgmgr32.dll	10.0.18362.387
shcore.dll  	10.0.18362.836
windows.storage.dll	10.0.18362.836
profapi.dll 	10.0.18362.693
powrprof.dll	10.0.18362.1
UMPDC.dll
shlwapi.dll 	10.0.18362.1
kernel.appcore.dll	10.0.18362.1
cryptsp.dll 	10.0.18362.1
libgcc_s_seh-1.dll
libstdc++-6.dll
libcairo-2.dll
libcurl-4.dll
exchndl.dll 	0.9.2.0
CRYPT32.dll 	10.0.18362.592
libexiv2.dll
libgdk-3-0.dll	3.24.14.0
WS2_32.dll  	10.0.18362.387
MSASN1.dll  	10.0.18362.1
IMM32.dll   	10.0.18362.387
WLDAP32.dll 	10.0.18362.449
SETUPAPI.dll	10.0.18362.1
libgdk_pixbuf-2.0-0.dll	2.40.0.0
bcrypt.dll  	10.0.18362.267
libgmodule-2.0-0.dll	2.64.2.0
libgobject-2.0-0.dll	2.64.2.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.14.0
libIlmImf-2_4.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
lua53.dll
libpango-1.0-0.dll	1.43.0.0
comdlg32.dll	10.0.18362.815
libpangocairo-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
libsoup-2.4-1.dll
libtiff-5.dll
libsqlite3-0.dll
libxml2-2.dll
zlib1.dll
libfontconfig-1.dll
MSIMG32.dll 	10.0.18362.836
libpixman-1-0.dll
libfreetype-6.dll	2.10.1.0
mgwhelp.dll 	0.9.2.0
VERSION.dll 	10.0.18362.1
dwmapi.dll  	10.0.18362.267
libnghttp2-14.dll
libpsl-5.dll
libidn2-0.dll
libglib-2.0-0.dll	2.64.2.0
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.6
libcairo-gobject-2.dll
WINMM.dll   	10.0.18362.1
gdiplus.dll 	10.0.18362.836
libbrotlidec.dll
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.43.0.0
libexif-12.dll
libsystre-0.dll
libbz2-1.dll
libHalf-2_4.dll
libIlmThread-2_4.dll
libthai-0.dll
COMCTL32.dll	6.10.18362.836
libpangoft2-1.0-0.dll	1.43.0.0
libatk-1.0-0.dll	2.36.0.0
WINSPOOL.DRV	10.0.18362.693
libharfbuzz-0.dll
liblzma-5.dll	5.2.5.0
libzstd.dll
dbghelp.dll 	10.0.18362.1
libpcre-1.dll
winmmbase.dll	10.0.18362.1
libtre-5.dll
USP10.dll   	10.0.18362.476
libdatrie-1.dll
PROPSYS.dll 	7.0.18362.815
libgraphite2.dll
OLEAUT32.dll	10.0.18362.836
IPHLPAPI.DLL	10.0.18362.1
dbgcore.DLL 	10.0.18362.1
libgomp-1.dll
libgio-2.0-0.dll	2.64.2.0
libopenjp2-7.dll
librsvg-2-2.dll
libsecret-1-0.dll
libexpat-1.dll
libcrypto-1_1-x64.dll	1.1.1.6
libfribidi-0.dll
libffi-7.dll
libltdl-7.dll
libIex-2_4.dll
libImath-2_4.dll
libunistring-2.dll	0.9.10.0
libbrotlicommon.dll
libgcrypt-20.dll	1.8.5.54720
DNSAPI.dll  	10.0.18362.815
NSI.dll     	10.0.18362.449
USERENV.dll 	10.0.18362.387
CRYPTBASE.DLL	10.0.18362.1
libgpg-error-0.dll	1.37.0.0
rsaenh.dll  	10.0.18362.1
uxtheme.dll 	10.0.18362.449
clbcatq.dll 	2001.12.10941.16384
mswsock.dll 	10.0.18362.815
MSCTF.dll   	10.0.18362.752
DEVOBJ.dll  	10.0.18362.387
WINTRUST.dll	10.0.18362.387
OpenCL.dll  	2.2.1.0
dxcore.dll  	10.0.18362.1
IntelOpenCL64.dll	23.20.16.4973
dxgi.dll    	10.0.18362.815
igdrclneo64.dll
TextInputFramework.dll	10.0.18362.693
CoreUIComponents.dll	10.0.18362.207
CoreMessaging.dll	10.0.18362.836
ntmarta.dll 	10.0.18362.1
wintypes.dll	10.0.18362.836
iertutil.dll	11.0.18362.815

Windows 10.0.18362
DrMingw 0.9.2

**Comment by parafin** [comment]
This is a bug in OpenCL drivers for your GPU. Try updating drivers for your video card maybe.

**Comment by coffeeandspaceships** [comment]
igdrclneo64 is part of the *Intel* driver stack.

Things to try: update the Intel NEO drivers to latest. Even though in theory you are not using the Intel IGA, because you have the discrete AMD, this crash is definitely in the Intel code. 

Possibility one: Maybe there's some weird way Windows manages handover between the two adapters, in which case updating the NEO drivers should make this go away.

Possibility two: Try disabling the Intel IGA completely. I would disable it in Device Manager first, so Windows shouldn't even try; and then on reboot disable it in the BIOS as well. (If you try this the other way around, Windows won't know that the IGA will be there so you won't be able to *explicitly* disable it.

To give you some hope, I have Intel only and I have been absolutely thrashing both 3.0.2 and master, testing some other issues here, and Darktable has not crashed for me once in a month.

**Comment by coffeeandspaceships** [comment]
Possibility three: Even though you have OpenCL disabled, the support for it is loading, and then sitting there unused; and because it hasn't been exercised it is attempting to set up then use Intel as a fallthrough situation, instead of working out that a) there is an AMD discrete adapter and b) neither adapter will be used because you have disabled OpenCL anyway.

**Comment by scyg** [comment]
Problem disappeared without any intervention from me, or an update from Darktable. Probably a gremlin.
