### ISSUE TITLE
Lens detection for Tamron 70-300 on Sony A57 not working

### ISSUE THREAD

**Issue by AJSheppardUK** [darktable-org/darktable#5224]
**Describe the bug**

The Tamron 70-300 DI Macro 1:2 lens is not being detected properly on a Sony A57 camera. In the lens correction tool the camera is picked up correctly but the lens is detected as (195) and a manual selction is required to choose the right lens

**To Reproduce**

1. Open RAW file taken with Tamron 70-300 DI Macro 1:2 lens on Sony A57
2. Open the Lens Correction module
3. The correct camera is shown but (195) is shown in the lens dropdown box.

**Expected behavior**

The lens should be auto detected as it is supported by lensfun.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Kubuntu 20.04
 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment]
Hi!

Have you followed https://github.com/darktable-org/darktable#why-is-my-lens-not-detectedcorrected-in-darkroom- ?
Do you have recent enough version of exiv2?

**Comment by MStraeten** [comment]
i had an issue with my sigma 35 mm that wasn’t properly detected after a firmware update. 
i got an hint from Robin Mills on a local workaround to correct the identification. see:
https://github.com/Exiv2/exiv2/issues/1192#issuecomment-622020760

**Comment by AJSheppardUK** [comment]
Thanks both. I have already used the lensfun update to get my DJI Mavic to pick up correctly so I know that is up to date (this is a fresh install of Kubuntu 20.04). Does that also update exiv2? 

I've noticed that I get exactly the same problem in the current version of Adobe Lightroom (Windows 10) as in it is just listed as (195) but the lens is listed if I look for it manually so something is a bit strange. Both the camera and lens have been around for at least 7 years so It's weird this combination hasn't flagged up before so it could be dodgy hardware my end.

I will see if I can edit the .exiv2 file as per MStraeten's suggestion.

**Comment by AxelG-DE** [comment]
@AJSheppardUK this happens, when the ID of the lens is used more than once.

I have the same on my Tamron 70-200/2.8 G2
I presetted it, incl. auto apply. This does it for me...

**Comment by matt-maguire** [comment]
Added an explanation about the .exiv2 file to the darktable User Portal wiki page:
https://github.com/darktable-org/darktable/wiki/User's-portal

**Comment by Nilvus** [comment]
Related to exiv2 and fix proposed in comments. I close.
