### ISSUE TITLE
export size not correct

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5228]
**Describe the bug**
An attempt to fix this issue has been made in #5022. But this has introduced a regression.

**To Reproduce**
$ cd src/tests/integration
$ darktable-cli --width 2048 --height 2048 --hq true images/mire1.cr2 0001-exposure/exposure.xmp output.png
$ exiv2 output.png | grep -i "Image size"
Image size      : 2049 x 1365

**Expected behavior**

Reverting : c12e3d3 and d881b85

The export size is correct and 2048 x 1364

$ exiv2 output.png | grep -i "Image size"
Image size      : 2048 x 1364

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux

**Additional context**

We should either revert commits c12e3d3 and d881b85 or have a fix for 3.2.

**Comment by jenshannoschwalm** [comment]
I'll fix this very soon

**Comment by TurboGit** [comment]
Thanks, I have assigned this to you.
