### ISSUE TITLE
blendop icons very small

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5235]
When using drawn/parametric masks, the icons that appear in the panel at the bottom of the module seem too small (mainly the shapes icons and the show mask icons at the bottom):

![Screenshot_2020-05-30_10-04-08](https://user-images.githubusercontent.com/9555491/83324408-005d6380-a25d-11ea-9b9e-94f6651a1ae2.png)

Compare this with similar icons in the Retouch Module:

![Screenshot_2020-05-30_10-04-33](https://user-images.githubusercontent.com/9555491/83324415-0c492580-a25d-11ea-993a-ded5f7513eca.png)

@Mark-64, @Nilvus ?

**Comment by Mark-64** [comment]
Yes, thank you for pointing out.
We are working on the GUI buttons and there might be some glitches.
Fix is in #5223

**Comment by elstoc** [comment]
Ok thanks. That's what I'd assumed.

**Comment by Nilvus** [comment]
Let me time to test actual PR and propose my PR (I have less time actually). That was (like few other things) fixed on my side since few days. I'm just waiting to test @Mark-64 and @AlicVB to adapt CSS to their PR. Anyway, thanks @Mark-64 for fixing that too.

**Comment by Mark-64** [comment]
@elstoc It should be fixed now, can you please do a test?

**Comment by elstoc** [comment]
Looks fine now. Thanks @Mark-64.
