### ISSUE TITLE
FR: Make histogram resizeable (and moveable?)

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5237]
While I would never want to get rid of the histogram entirely, it does take up a fair bit of vertical screen real-estate in the darkroom, especially when also using some of the more complex iop modules with blendop masks. It would be great to have the ability to reduce the height of the histogram and/or be able to move it to the left-hand side panel.

**Comment by groutr** [comment]
Being able to move it above or below the navigator would be awesome.

**Comment by elstoc** [comment]
The thing is that the widgets at the top-left and top-right are both fixed there. If you put both the histogram and the navigator at the top-left, I'm not sure how easy it would be to control the order or whether it would really be desirable, given how much vertical space you'd take up. With the navigator hidden it certainly makes more sense. I suppose you could have a choice about which module occupies the top slot on each side and then choose to hide one or both using the existing shortcuts.

So you'd have a preference, say "position of histogram and navigation modules" with options

- histogram on left, navigation on right
- navigation on left, histogram on right

That's probably pretty easy to implement. The resizing might be harder (or at least I haven't yet worked out how to do it). The histogram position would also affect the tethering view.

**Comment by Nilvus** [comment]
It's good to let the choice if that is implemented yes. And keep actual behavior of course (I prefer the way it is actually).

**Comment by elstoc** [comment]
> I prefer the way it is actually

Yes I think I agree, having played with the alternative for a while. Often you're adjusting a module while keeping one eye on the histogram, which is difficult when they're on opposite sides of the screen. Still would be nice to be able to adjust the height.
