### ISSUE TITLE
CTRL++  shortcut on windows and MacOS behavior

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#5238]
Currently on windows and MacOS. the CTRL++ shortcut can only be invoke when you press CTRL+ SHIFT+ +. I think the reason is because the + sign is actually the shift of =. I think to make it more universal it should be change to CTRL+=. that way both CTRL+- and CTRL+= does not require a shift

what you all think. thanks again for the amazing software

**Comment by elstoc** [comment]
I'm not sure that's necessarily consistent on other keyboard layouts and certainly for those with a numeric keypad. Nothing stopping you from setting up your shortcuts that way yourself though (I do the same).

**Comment by eyedear** [comment]
what I mean is that if a user coming from adobe products, affinity will find that that the shortcut as written on the shortcut pages showing ctrl++ does not work while ctrl+- works. If its too hard then its ok will have to assign custom shortcuts. noted and thanks

**Comment by elstoc** [comment]
It's not that it's too hard to do, just that either way will probably please some people and annoy others. And the current use of plus and minus seems the more logical default. I blame whoever came up with a keyboard layout that requires shift for plus but not for minus.

**Comment by eyedear** [comment]
haha you are right. then i will change it myself on my local machine as the key combination is use on almost everything from browser to other image editing software. thanks
