### ISSUE TITLE
Scrolling modules AND values with the mouse wheel

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5242]
It's really useful to be able to scroll the modules in darktable with the mouse wheel.  But then I can't adjust values with it.  It would be nice to do both by e.g. pressing CTRL whilst wheeling a value.

**Comment by elstoc** [comment]
Unfortunately CTRL is already used as a modifier for sliders (to scroll by a smaller amount than normal) as is SHIFT (to scroll by a larger amount than normal). You can still scroll the modules if you hover over the scroll bar though.

**Comment by elstoc** [comment]
It turns out (I'm only just now reading the tooltips for some of these options myself but it is stated there) you can use CTRL+ALT+scroll to scroll the modules if you have "mouse wheels scrolls side panel by default" unchecked, and CTRL+ALT+scroll to change values if it's checked.

**Comment by johnny-bit** [comment]
So - this can be closed as the feature @RawConvert requested already exists :)

**Comment by RawConvert** [comment]
Ah!  I was just about to suggest ALT.  So fine, thanks, it's covered.

But a further twist... if ctrl+alt+wheel works, why do shift+wheel and ctrl+wheel not work!

I'll leave overnight and close tomorrow if no further points.

**Comment by johnny-bit** [comment]
Reporting from 3.0.2 & current master:
ctrl + wheel on slider WORKS: adjustment is done in TINY amount
shift + wheel on slider WORKS: adjustment is done in HUGE amount

Check on your side but that's how this supposed to work :)
It's not in shortcuts window with mouse accels though :/ just need to learn about it by either manual or tips :)

**Comment by RawConvert** [comment]
Agree those work fine if you're not scrolling the modules.
But if scrolling modules, they don't work on my build (master).  ctrl+wheel continues to scroll the modules.  shift+wheel does nothing at all.
?! :)

**Comment by RawConvert** [comment]
and of course ctrl+alt+wheel works fine.

**Comment by elstoc** [comment]
@RawConvert: See #4899 which is basically the same issue as your last comment. Are you happy to close this as a duplicate?

**Comment by RawConvert** [comment]
@johnny-bit , you didn't reply.
@elstoc , yes fine.

**Comment by RawConvert** [comment]
closing
