### ISSUE TITLE
rotated, mirrored cloning

### ISSUE THREAD

**Issue by Jopp-gh** [darktable-org/darktable#5245]
**Is your feature request related to a problem? Please describe.**

Cloning is not easy if we have only a limited amount of sources to pick from, and a bigger area to cover / repair

**Describe the solution you'd like**

my idea is, to manipulate the output of the cloned source to be more flexible:
- mirroring the source input along the x/y axis, 
- rotating of the source input

In this way, we avoid to see "repetitive patterns" when we have to pick multiple times from the same source
The only problem which i see is, light and shadows may influence the cloned object, and the cloned object might look fake. But, if our cloned output needs only a slight rotation, the end result should look acceptable, imo.

**Alternatives**

**Comment by MStraeten** [comment]
Just to lower expectations: Retouch is already a very performance hungry operation if it’s used for more than a few corrections. I really appreciate having such  available in one application, but maybe this https://discuss.pixls.us/t/wiring-darktable-with-krita-nsfw/14938 is a better way to deal with it
