### ISSUE TITLE
5d mark iv not recognized? / found? in lens correctoin module

### ISSUE THREAD

**Issue by mheieis** [darktable-org/darktable#5248]
Lens correction does not find Canon 5D mark iv.
The manual selection list does not have mark iv as a option.

**To Reproduce**
Using a raw CR2 image taken with a mark iv; select "Lens Correction" -->

**Expected behavior**
Canon mark iv is selected

**Screenshots**
see attached image info and lens correction module screen shots

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Fedora 32
 - OpenCL = no
-on board intel

**Additional context**
installed from fedora 32 distribution
correct lens is selected

**Comment by MStraeten** [comment]
at least on osx and windows the 5D mk IV is recognized as "EOS 5D Mark IV" 
did you check, if exiv2 is able to recognize the cam?
`exiv2 -pa --grep model/i <cr2 file>`
should return something like
```
Exif.Image.Model                             Ascii      21  Canon EOS 5D Mark IV
Exif.Canon.ModelID                           Long        1  EOS 5D Mark IV
Exif.Canon.LensModel                         Ascii      74  35mm F1.4 DG HSM | Art 012
Exif.Photo.LensModel                         Ascii      27  35mm F1.4 DG HSM | Art 012
```

**Comment by johnny-bit** [comment]
See https://github.com/darktable-org/darktable/blob/master/README.md#why-is-my-lens-not-detectedcorrected-in-darkroom- and make sure you have new enough exiv2. It'll work 😃 and once it does, close this issue please🙏

**Comment by mheieis** [comment]
> at least on osx and windows the 5D mk IV is recognized as "EOS 5D Mark IV"
> did you check, if exiv2 is able to recognize the cam?
> `exiv2 -pa --grep model/i <cr2 file>`
> should return something like
> 
> ```
> Exif.Image.Model                             Ascii      21  Canon EOS 5D Mark IV
> Exif.Canon.ModelID                           Long        1  EOS 5D Mark IV
> Exif.Canon.LensModel                         Ascii      74  35mm F1.4 DG HSM | Art 012
> Exif.Photo.LensModel                         Ascii      27  35mm F1.4 DG HSM | Art 012
> ```

Yes, darktable and exiv2 show that mark iv is recognised.
Executed lensfun-update-data after doing a "dnf install lensfun*"

Now works as expected.
