### ISSUE TITLE
Lighttable temporarily losing images

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5250]
I imported a **folder** containing 9 raws and their SOOC jpegs, but only the raws, by means of that setting in prefs. (This may be irrelevant)
I worked on 5.
I notice that when I go from darktable to lighttable, the raws prior to the one I've just been editing are not shown.  That is, if I was working on the 3rd one, the first 2 are gone.
I can then re-import the folder and now have 9 again, including my edits. But picking on another one to edit, then back to lighttable, it's the same - the ones displayed prior to the just-edited one are missing.
In lighttable at the top of the screen, it says viewing **all** and sorted by **filename**.
I'm afraid I can't show screen grabs or upload raws as they are private.

dt   3.1.0+1837~gee49c4778-dirty   built 30/5/2020    Ubuntu 18.04

**Comment by elstoc** [comment]
I think this might be a duplicate of #4957. They are shown but you need to scroll up. It's because the one you've just edited is moved to the top-left of the lighttable view.

**Comment by RawConvert** [comment]
Yes, dup, closing.
