### ISSUE TITLE
History is not correct

### ISSUE THREAD

**Issue by jrickards** [darktable-org/darktable#5255]
**Is your feature request related to a problem? Please describe.**

When I open a new file in Word out Photoshop, I'm sure there are many things that happen automatically in the background that I can't change but they don't appear in the history. Darktable now has a few things in the history that were not things I did. History should be just what I did (and that includes presets that I configured to run automatically). It should also allow me to fully delete the history, it doesn't. I have no problem having these things in the pipeline bit they shouldn't be in the history.

**Describe the solution you'd like**

Remove these things from the history but keep them in the pipeline.

**Alternatives**

**Additional context**

**Comment by jenshannoschwalm** [comment]
This has been discussed intensively by many before, there is no chance for this because it's better this way. History is "what has been done" and not "what did I do" 😊

**Comment by Nilvus** [comment]
And you can see what's not from you with icons (see icon in original one for example, it's the default "background" modules). Most users like to see what darktable do on the background.
I suggest you to read the 3.0 article in darktable.org article to understand more some choices in the 3.0.
