### ISSUE TITLE
Move option buttons back to the left

### ISSUE THREAD

**Issue by jrickards** [darktable-org/darktable#5256]
**Is your feature request related to a problem? Please describe.**

I liked that the on/off, new instance, reset and preset buttons were all on the left of each module but now, the last three are on the right, I don't like that.

**Describe the solution you'd like**

Move those three back to the left side as in 2.6.

**Alternatives**

**Additional context**

**Comment by jenshannoschwalm** [comment]
A design decision...

**Comment by elstoc** [comment]
I prefer the 3.x layout.
