### ISSUE TITLE
Darktable zooming in slowly on Mac

### ISSUE THREAD

**Issue by lilo83** [darktable-org/darktable#5258]
Hello,

I have a problem with slowly working DT on Mac. Zooming in a photo (RAW) takes over 40s. When I launch DT (Macintosh HD/Applications/darktable/Contents/MacOS/darktable) a terminal opens where a few critical are (please see attached photo).

Applying other functions like levels or color balance works quicker.

**To Reproduce**
After opening dt and choosing a photo from lightable I zoom in and this takes a long time.

**Expected behavior**
I expected the zoom in function to work quicker.

**Screenshots**
<img width="565" alt="Zrzut ekranu 2020-05-30 o 13 52 22" src="https://user-images.githubusercontent.com/66208424/83353952-4f3af400-a356-11ea-989a-3a8c74e0017d.png">

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.0.2
 - MacBook Pro 13' 2019 
   OS: MacOS Catalina 10.15.5
   16 GB 2133 MHz LPDDR3
   2,4 GHz Quatro-Intel Core i5
   Intel Iris Plus Graphics 655 1536  MB
 - OpenCL activated in DT.
**Additional context**
 - I have installed the dmg file from official site. I have also tried to install from MacPorts.
 - The issue concerns RAW files, not JPEG.
 - Is the issue still present using an empty/new config-dir: I don't know how to do this.

I would appreciate some help. I tried to provide detailed information. Let me know if you need more..

**Comment by johnny-bit** [comment]
run darktable from console with `-d perf` option. Also - have you tried disabling opencl? in rare cases, bare cpu is quicker than OpenCL

**Comment by lilo83** [comment]
@johnny-bit Thank you really much for your comment. I have tried to use dt with and without OpenCL - it didn't make a big difference. 

After entering the localisation Macintosh HD/Applications/darktable/Contents/MacOS/ and using the command open darktable -d perf , I get the following information:
<img width="609" alt="Zrzut ekranu 2020-05-31 o 19 23 34" src="https://user-images.githubusercontent.com/66208424/83358495-3fcaa380-a374-11ea-92f2-20994ce4449c.png">

Do I get it right that I cannot use the option -d ? Is there any other way?

**Comment by johnny-bit** [comment]
Just to note: I haven't even been near mac this year ;)

anyway - try to open darktable in terminal (i'm sure it's possible) using:
`darktable -d perf`
and for comparison:
`darktable -d perf --disable-opencl`

**Comment by parafin** [comment]
Use `/Applications/darktable/Contents/MacOS/darktable` instead of `darktable` or `open darktable`

**Comment by lilo83** [comment]
@johnny-bit and @parafin many thanks you for your tips - this was helpful. 

I used /Applications/darktable.app/Contents/MacOS/darktable -d perf and it worked. I noticed that during the zoom in process the modules Denoise - profiled (`odszumianie (profilowane)'), Tone equalizer (`korektor tonów') and Haze removal (`usuwanie zamglenia') took the most time (please see attached pdf file). So basically, it should be enough to turn off these modules while zooming in or out and use them in the end of photo editing. I'm sorry that I didn't mention in the beginning that I've got these modules turned on but I didn't pay attention to this and I didn't expect they can have such an impact..

Should these above mentioned modules take this long? Do the criticals have something to do with that?

[Darktable debuge.pdf](https://github.com/darktable-org/darktable/files/4712696/Darktable.debuge.pdf)

**Comment by johnny-bit** [comment]
Tak, this combo is especially bad performance wise on zoom. When I was
power starved I did 100% zoom for denoise profiled alone and make sure I
don't use zoom with tone equalizer. Tone equalizer + denoise profiled is
deadly on zoom 😅

pon., 1 cze 2020, 19:50 użytkownik lilo83 <notifications@github.com>
napisał:

**Comment by MStraeten** [comment]
these and also the retouch module are performance consuming tasks. But while retouch or denoise-profiled can be applied at the end of the editing process, tone equalizer should better stay enabled since later modules depends on its output.
To avoid waiting time i ususally do a basic exposure correction first, then some spot removal with retouch and disable the retouch module afterwards. So it’s quite responsive ... and for tweaking denoise settings you can disable tone equalizer first.

**Comment by lilo83** [comment]
@johnny-bit @MStraeten Thank you guys really much for these comments! That explains everything to me. I'm going to follow your tips.. dziękuje :D

Just out of curiosity - what do those criticals shown in my print screens above mean?

**Comment by parafin** [comment]
nobody knows, but they don't seem to create any problems

**Comment by lilo83** [comment]
@parafin Ok, great, thank you for information. Thank you all guys. I'm closing the issue now
