### ISSUE TITLE
exiftool and xsltproc missing from list of dependencies

### ISSUE THREAD

**Issue by susca** [darktable-org/darktable#5261]
**Is your feature request related to a problem? Please describe.**
Yes, a minor problem: when executing build.sh, it warns about exiftool and xsltproc missing. These are not mentioned in the README or [website](https://www.darktable.org/install/)

**Describe the solution you'd like**
Add exiftool and xsltproc to the installation instructions.

**Alternatives**
X

**Additional context**
I am compiling the master branch.

**Comment by susca** [comment]
intltool is also missing from the list of requirements.

**Comment by susca** [comment]
also, it would be helpful to specify that the development packages ("*-dev") are needed.

**Comment by susca** [comment]
libopenexr-dev libwebp-dev libavifile-0.7-dev liblensfun-dev also missing in the requirements.

**Comment by parafin** [comment]
exiftool? What's the error regarding exiftool? I don't think it's used for anything, libexiv2 is a dependency instead.

**Comment by susca** [comment]
@parafin thanks for replying :)

Here is the complete output from the first attampt to run `build.sh`.

```
$ ./build.sh --prefix /home/steffen/.local/
Darktable build script

Building directory:  /home/steffen/opt/darktable/build
Installation prefix: /home/steffen/.local/
Build type:          RelWithDebInfo
Build generator:     Unix Makefiles
Build tasks:         4


-- The CXX compiler identification is GNU 9.2.1
-- The C compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenMP_C: -fopenmp (found suitable version "4.5", minimum required is "4.5") 
-- Found OpenMP_CXX: -fopenmp (found suitable version "4.5", minimum required is "4.5") 
-- Found OpenMP: TRUE (found suitable version "4.5", minimum required is "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Looking for __get_cpuid
-- Looking for __get_cpuid - found
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST - Success
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS - Success
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS - Failed
-- Performing Test IS_SUPPORTED_PLATFORM
-- Performing Test IS_SUPPORTED_PLATFORM - Success
-- Is the target platform supported: 1
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found little endian system. Good.
-- Performing Test _MSSE2
-- Performing Test _MSSE2 - Success
-- Building SSE2-optimized codepaths: ON
-- Performing Test C_COMPILER_UNDERSTANDS_-Wall
-- Performing Test C_COMPILER_UNDERSTANDS_-Wall - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wall
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wall - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat-security
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat-security - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat-security
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat-security - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wshadow
-- Performing Test C_COMPILER_UNDERSTANDS_-Wshadow - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wshadow
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wshadow - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wtype-limits
-- Performing Test C_COMPILER_UNDERSTANDS_-Wtype-limits - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wtype-limits
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wtype-limits - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wvla
-- Performing Test C_COMPILER_UNDERSTANDS_-Wvla - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wvla
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wvla - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wold-style-declaration
-- Performing Test C_COMPILER_UNDERSTANDS_-Wold-style-declaration - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wold-style-declaration
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wold-style-declaration - Failed
-- Performing Test C_COMPILER_UNDERSTANDS_-Wthread-safety
-- Performing Test C_COMPILER_UNDERSTANDS_-Wthread-safety - Failed
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wthread-safety
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wthread-safety - Failed
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-format-truncation
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-format-truncation - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-format-truncation
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-format-truncation - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Success
-- Looking for external programs
-- Found perl
-- Missing intltool-merge
-- Found desktop-file-validate
CMake Warning at CMakeLists.txt:291 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "10".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-7/cmake/LLVMConfig.cmake, version: 7.0.1
    /usr/lib/llvm-8/cmake/LLVMConfig.cmake, version: 8.0.1

Call Stack (most recent call first):
  CMakeLists.txt:299 (find_llvm)


CMake Warning at CMakeLists.txt:291 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "9".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-7/cmake/LLVMConfig.cmake, version: 7.0.1
    /usr/lib/llvm-8/cmake/LLVMConfig.cmake, version: 8.0.1

Call Stack (most recent call first):
  CMakeLists.txt:299 (find_llvm)


-- Found LLVM 8.0.1
-- Found clang compiler - /usr/bin/clang-8
-- Found clang opencl-c.h header in /usr/lib/llvm-8/lib/clang/8.0.1/include
-- Will be able to test-compile OpenCL programs. Nice.
-- Found jsonschema
-- Missing xsltproc
-- Found saxon-xslt
-- Found xmllint
-- Missing exiftool
CMake Error at CMakeLists.txt:388 (message):
  Some external programs couldn't be found


-- Configuring incomplete, errors occurred!
See also "/home/steffen/opt/darktable/build/CMakeFiles/CMakeOutput.log".
See also "/home/steffen/opt/darktable/build/CMakeFiles/CMakeError.log".
```

**Comment by susca** [comment]
_Sorry for kind of hijacking my own issue.... I am just listing the problems I find while trying to build, I hope it helps to refine the documentation and/or build process._

Next Problem is libavif, which has to be downloaded from github and built by hand (on ubuntu 20.04, that is).

Wouldn't it make sense to include it into the submodules?

**Comment by susca** [comment]
adding to the list: librsvg2-dev and libpugixml-dev

**Comment by ralfbrown** [comment]
Note that libavif is an optional dependency -- the only result of leaving it out is that you can't work with AVIF files, which are still very rare since their specification was only finalized in February 2019.

**Comment by coffeeandspaceships** [comment]
Note in your output there, the `CMake Error at CMakeLists.txt:388 (message):
  Some external programs couldn't be found` is actually triggered by the missing `intltool-merge`, not the missing `exiftool`.  It just appears to be `exiftool` that is the problem because of the way the CMake output is structured in sections. I had the same issue and it confused me for a long time.

@parafin I think `exiftool` is there to support an "extract whitebalance tool" which can be found under `tools` in the source tree [extract_wb.py](https://github.com/darktable-org/darktable/blob/f42aeff27d8846545087166abba931c6b25f03c3/tools/extract_wb.py).

**Comment by coffeeandspaceships** [comment]
It will be good to check all the available documentation against your full list when you've finished, but I have a question. You say "exiftool and xsltproc are missing from the documentation", but [doc/README.md](https://github.com/darktable-org/darktable/blob/master/doc/README.md) mentions those two libraries. Can you please list which documentation sources you checked in order to try and work out the list of dependencies, so that we can make sure we update them all, or consolidate them into once place?

Regarding -dev - that is needed for Debian-like distributions, but for example pacman on Arch Linux (and Windows MSYS!) does not require the seperate -dev packages, because there is no such concept.

**Comment by parafin** [comment]
Yep, Debian users should know that when compiling something from sources you need -dev packages for all dependencies. Not all distributions have this concept.

As for exiftool - I wonder if it makes sense to move the check to script itself and install it regardless of existence of exiftool in the system. After all it's not a build-time dependency, but runtime.

**Comment by johnny-bit** [comment]
You clearly have some kind of bare-bones system :)

Anyway - for building always *dev versions are required.

> Next Problem is libavif, which has to be downloaded from github and built by hand (on ubuntu 20.04, that is).

Nope, once libavif is picked by distros there's no reason to have it bundled and it's optional dependency.

Anyway, the reason your build fails is because your system is mising one of: perl, intltool-merge, xsltproc or saxon-xslt and build is complaining about it here:
```
-- Missing intltool-merge
```

I think having fatals direcly in place where required package is missing would lower the number of false-positive errors, what do you think @parafin ? here the exiftool was thought to be culprit, while it's only used by extract_wb, curve tool helper and dngmeta.rb and only used in build for extract_wb_from_images.sh which is VERY optional and only if installing tools.

**Comment by susca** [comment]
> It will be good to check all the available documentation against your full list when you've finished, 

will do...

> but I have a question. You say "exiftool and xsltproc are missing from the documentation", but [doc/README.md](https://github.com/darktable-org/darktable/blob/master/doc/README.md) mentions those two libraries. Can you please list which documentation sources you checked in order to try and work out the list of dependencies, so that we can make sure we update them all, or consolidate them into once place?

my bad, I only checked [README.md](https://github.com/darktable-org/darktable/blob/master/README.md) and the [website install instructions](https://www.darktable.org/install/). Maybe it would be good to mention doc/README.md in these resources (for people with short attention spans like myself).

> 
> Regarding -dev - that is needed for Debian-like distributions, but for example pacman on Arch Linux (and Windows MSYS!) does not require the seperate -dev packages, because there is no such concept.

ok. I also use arch on a different computer, but I use Ubuntu on the one where I edit fotos. I guess it does not make sense to give such detailed instructions for every distro....

**Comment by susca** [comment]
> Yep, Debian users should know that when compiling something from sources you need -dev packages for all dependencies. Not all distributions have this concept.

I agree.

**Comment by susca** [comment]
> You clearly have some kind of bare-bones system :)

Actually not.... It's a Xubuntu installation from a year ago or so, which I upgraded to 20.04. I use it for mostly Python development. I do compile some of the programs I use regularly (e.g. emacs), so the "compile and build" infrastructure is in place....

> Anyway - for building always *dev versions are required.

Yes, wasn't a big problem for me, and I guess everybody who decides to compile from source also knows it or learns it quickly.


> Nope, once libavif is picked by distros there's no reason to have it bundled and it's optional dependency.

if that is the case anytime soon, then all is good, I had problems compiling it :(
But I learned that it is optional anyway...
> 
> Anyway, the reason your build fails is because your system is mising one of: perl, intltool-merge, xsltproc or saxon-xslt and build is complaining about it here:

I installed intltool, which solved for me. there is no intltool-merge on Ubuntu.

**Comment by coffeeandspaceships** [comment]
Susca said:
> my bad, I only checked README.md and the website install instructions. Maybe it would be good to mention doc/README.md in these resources (for people with short attention spans like myself).
* It's definitely bad to have this information split in two places in the source tree, and that is something I can fix with a PR.
* I don't know who maintains the website install instructions or where it is mastered - guys?
* I am not sure how the Wiki hosted on github fits in.

johnny-git said:
> I think having fatals directly in place where required package is missing would lower the number of false-positive errors

Agree. There are also a few things missing from the list I think - OpenCL doesn't have good explicit messages yet OpenMP does, so that seems like it should be easy to add.

Extra point to note: sometimes clang dependencies are different to gcc dependencies on the same platform, and the features are different between the two (although I *think* the extra clang goodies are only of interest to devs.)

**Comment by parafin** [comment]
The only build-time requirement for OpenCL are OpenCL headers, which are missing only if you forget to checkout all submodules (or when some distro removes them from the tarball). So I'm not sure what explicit message you want. Are you talking about test-compilation of OpenCL kernels? This is optional, and error message doesn't say that it's fatal or that OpenCL is disabled. Not sure why so many people trips on it, but I guess it can be re-formulated somehow.

**Comment by johnny-bit** [comment]
Closing as no longer problematic - neither exiftool nor xsltproc are requirements, just optional dependencies :grin:
