### ISSUE TITLE
ReadLink error on purge_from_cache.sh (and library not found)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5271]
**Describe the bug**
I can't launch purge_from_cache script and can't find why. It always says that:

```
/opt/darktable/share/darktable/tools/purge_from_cache.sh: ligne 95: ReadLink : command not found
error: library db '' doesn't exist
```
I have this error even if add no option or if I add the -l (or --library) argument with full path to my library.db file (that is in my default .confid/darktable folder).

I also try to rename ReadLink to readlink. That only remove the ReadLink command not found error. I precise that I have coreutils installed, so readlink command on /bin folder. On a Terminal, launching simply readlink is possible.

I'm on Ubuntu 20.04.

**Comment by parafin** [comment]
PR fixing that was created just before you posted the bug: #5270

**Comment by Nilvus** [comment]
Thanks for pointing that PR @parafin. Indeed that fix this issue.
