### ISSUE TITLE
image not altered when rotated

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#5274]
This may be related to #5269, but I'm not sure it's the same issue...

**Describe the bug**
With fresh raw files and "use embedded jpeg" pref, when you just rotate the image to the left or right, this doesn't refresh the thumbnails.

After some test and code reading, this doesn't comes from the lighttable rewrite for once ! If you launch dt with `-d cache`, you can see that the thumbnail of the rotated image if recreated... from the embedded jpeg !
That's due to the fact that the image is not considered as altered : `dt_image_altered` return `FALSE` if the image has just been rotated...
And the code in `mipmap_cache.c` in the function `_init_8` use this check to determine if we can load the image from the embedded jpeg or if we need to load it from scratch.

I remember that there has been some recent change on this area, so I think this comes from here. Maybe we should have 2 check : one for the user perspective and one for internal use ?

**To Reproduce**
1. open a collection with "fresh" images
2. select one landscape image
3. click on the "rotate to the left" button (always in lighttable)
=> see that the thumbnail doesn't change and doesn't have the "altered" icon either. Even if you change the thumb size.

**Expected behavior**
the thumbnail should be rotated

**Platform (please complete the following information):**
 - Darktable Version: master at 3.1.0+1861~g0750cbd1a
 - OS: ubuntu 20.04
 - OpenCL : same with or without

**Comment by TurboGit** [comment]
Could just be a refresh issue as when I rotate a second time left or right the altered status is set. Do you confirm ?

**Comment by TurboGit** [comment]
@phweyland : probably something related to your recent work on altered status. can you have a look ?

**Comment by AlicVB** [comment]
> Could just be a refresh issue as when I rotate a second time left or right the altered status is set. Do you confirm ?

I've though that at first, but the refresh is triggered and the thumbnail is regenerated... but from embedded jpeg and not from the pipe. And last point : exiting reentering the collection doesn't fix the issue...

**Comment by phweyland** [comment]
> @phweyland : probably something related to your recent work on altered status. can you have a look ?

I'll do.

**Comment by phweyland** [comment]
As @AlicVB describes we are in the case where the embedded jpeg is used, or, when the thumbnail is not a developed one. That's a case I haven't looked at.
However the rotated flag is a changed and should be stored in the historic, and the mipmap hash updated as well. Then dt_image_altered should return TRUE...
