### ISSUE TITLE
keyboard shortcut rerorg broken

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5280]
**Describe the bug**

Keyboard shortcut reorg broken

**To Reproduce**

1. Go to "preferences" dialog
2. See error

```
error: translation mismatch: `views/lighttable/toggle culling zoom mode' vs. `'
error: translation mismatch: `views/lighttable/toggle culling dynamic mode' vs. `'
error: translation mismatch: `views/lighttable/toggle culling mode' vs. `'
error: translation mismatch: `views/tethering/switch histogram type' vs. `'
error: translation mismatch: `views/darkroom/histogram/switch histogram type' vs. `'
error: translation mismatch: `views/tethering/switch histogram mode' vs. `'
error: translation mismatch: `views/darkroom/histogram/switch histogram mode' vs. `'
error: translation mismatch: `views/tethering/cycle histogram modes' vs. `'
error: translation mismatch: `views/darkroom/histogram/cycle histogram modes' vs. `'
error: translation mismatch: `views/tethering/hide histogram' vs. `'
error: translation mismatch: `views/darkroom/histogram/hide histogram' vs. `'
error: translation mismatch: `views/darkroom/hide navigation thumbnail' vs. `'
```

Also we must be sure the strings are translatable.

**Expected behavior**
No error.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian

**Additional context**

**Comment by elstoc** [comment]
@TurboGit do I just have to wrap the paths in ``NC_("accel", "<path>")``? Not something I have a great deal of experience with (and might have trouble testing because I use English).

**Comment by TurboGit** [comment]
For the translation part I can have a look. But the error also reproduce when dt is launch in English.

**Comment by elstoc** [comment]
Ok I think I've seen something like that before. I'll take a look.
