### ISSUE TITLE
thiner sliders

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5284]
**Is your feature request related to a problem? Please describe.**

This has been bothering me since a long time and I have been in many time asking me if thinner sliders would not be better.

As we are doing a lot of redesign I'm raising this for discussion.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/467069/83524888-86d7a680-a4e4-11ea-991c-e22c277b1537.png)

The 3 sliders above for exposure, threashold and black white line could certainly be a bit thinner without loosing precision but visually more appealing.

**Comment by aurelienpierre** [comment]
Problem is with coloured slider, thinner would make them less legible. Aesthetics is something I care about after ergonomics.

**Comment by aurelienpierre** [comment]
Also, if you look at screenshots in https://github.com/darktable-org/darktable/pull/4360, there seems to be some discrepancies depending on displays (I supposed, linked to DPI scaling and such).

**Comment by johnny-bit** [comment]
We do have "gradientslider" for coloured sliders, however that one sufers from lack of features, bauhaus popups and possible 4-point slidign instead of 1 so it's super powerfull but needs loads of work to be on-par feature-wise with normal slider...

that ebing said, I think I've seen nice work of @Mark-64 regarding gradientslider, making it more dpi-independent, maybe the same can be done for sliders? and see how it'll affect them?

**Comment by Mark-64** [comment]
Normal sliders are quite DPI-independent already

Ubuntu
![Screenshot from 2020-06-02 21-06-37](https://user-images.githubusercontent.com/43290988/83560249-36793c80-a516-11ea-8c91-424ef45c729b.png)

Windows
![Cattura4](https://user-images.githubusercontent.com/43290988/83560279-45f88580-a516-11ea-9b0e-ef18944d0645.JPG)

However I agree that they would look nicer if thinner, maybe with a different marker, circular or square. see for example Capture One which is my benchmark when coming to the GUI:
![Cattura5](https://user-images.githubusercontent.com/43290988/83560478-9ec81e00-a516-11ea-852c-0707febd12bb.JPG)

Also, I would love to see other type of widgets to manipulate colors, not only sliders, see Capture One again for Color Balance
![Cattura6](https://user-images.githubusercontent.com/43290988/83560678-e51d7d00-a516-11ea-9baa-4eeaaffe8bc3.JPG)
3 wheels = 9 sliders, much more compact
I guess to realize that in Gtk+ would take a lot of work, does anyone know some resources on the net to find example to maybe adapt ?

**Comment by Nilvus** [comment]
I agree with @aurelienpierre here as ergonomics is more important than aesthetics things. Anyway, I think we could considerate color sliders different than default ones, so we could maybe make them thinner (only not colored ones). But not so thin like Capture one screenshot posted above.

@Mark-64: I'm not for square or circular things. Actual arrows are great as they are and do not have to be change, only slider could be make thinner. A sort of intermediate thing between actual size and Capture one seen on screenshot. To remains the UI ergonomics, I think the arrow should not be reduced, so the arrow would be more visible with the line thinner. But the most important thing to update on bauhaus slider would be the possibility to set arrow and popover (when right click on it) background changed by CSS. Actually is not the case the way it is written. But as discussed already on that with @aurelienpierre last year, that would mean a complete bauhaus rework. So if this is reworked, I think it would be better to let more time to discussed that, so would be for 3.4, not 3.2.

I dislike wheels from Capture One. It's too much and add some distraction on the UI. I see them as just a sort of popup visual effect to please the user, but I'm not sure they are so much practical. I hope to not see that in darktable.

**Comment by TurboGit** [comment]
Just a precision, when I say thinner I was thinking about 1px or 2px less for the slider. Just to make it less prominent. At least we could try this... What is the CSS incantation for this ? I can test and attach a screenshot here ?

**Comment by TurboGit** [comment]
And I don't want the handle (triangle) to be smaller, just the line which I would diminish on top for it to come a bit below the top of the triangle.

**Comment by Nilvus** [comment]
> Just a precision, when I say thinner I was thinking about 1px or 2px less for the slider. Just to make it less prominent. At least we could try this... What is the CSS incantation for this ? I can test and attach a screenshot here ?

It's bauhaus-slider for those widgets but on few tests I made, it can't be changed with CSS. Would need a Gtk rework.

**Comment by elstoc** [comment]
@TurboGit I think you want to play around with the values at the bottom of ``dt_bauhaus_load_theme`` in ``bauhaus/bauhaus.c`` along with the functions called from ``dt_bauhaus_draw``

**Comment by Mark-64** [comment]
I like that, but why not making color slider different and thicker than the others? I don't think they have to be necessarily equal.
The bar in color sliders gives to the user an additional information which needs some minimum size to be perceived, especially for people who have some degree of color blindness like me.

@Nilvus You might not like C1, but it's a matter of fact that color wheels, in various shapes, are a sort of standard for color correction and grading especially for video. Take DaVinci Resolve for example (BlackMagic also produces HW devices with color wheels) and also in open source SW, like PiTiVi or Blender.
After all, we took the way of ASL-CDL for color manipulation, which is the standard for video.

**Comment by Nilvus** [comment]
> to this
> 
> ![Screenshot_2020-06-02_23-45-17](https://user-images.githubusercontent.com/9555491/83577217-98906c80-a52b-11ea-8ee7-7e2260dfb472.png)
> 
> I think that's an improvement. Coloured sliders still look fine too:
> 
> ![Screenshot_2020-06-02_23-54-32](https://user-images.githubusercontent.com/9555491/83577592-7e0ac300-a52c-11ea-9f7a-ca39475d979d.png)

Seems great like that. Will test on my side.

**Comment by johnny-bit** [comment]
Huh, looks fine by me. And i LOVE colored sliders. no problem in this design change for me then :)

**Comment by TurboGit** [comment]
I would love to see the line a bit below. I suppose it would look better if the base of the line was aligned with the base of the triangle. The height of the slider is fine otherwise.

**Comment by Nilvus** [comment]
> I would love to see the line a bit below. I suppose it would look better if the base of the line was aligned with the base of the triangle. The height of the slider is fine otherwise.

Yes, that would be better but I would suggest to just let 1 pixel outside the slider at the base of the triangle.

**Comment by elstoc** [comment]
How about this...

![Screenshot_2020-06-03_16-47-20](https://user-images.githubusercontent.com/9555491/83658288-efdd1e00-a5b9-11ea-85c5-afe8b30ec1ce.png)

I've also changed the width of the line on the hollow triangle as well as the width of the darker grey outer line, which looked a bit too wide for my tastes.

**Comment by TurboGit** [comment]
Lot nicer to me! Really nice, I really want this for 3.2 ;)

**Comment by Nilvus** [comment]
Good work @elstoc. Like that too. This just would need to be tested on Hidpi and lodpi system and with different font sizes to check. Waiting for the PR.

**Comment by elstoc** [comment]
Ok I'll submit a PR.
