### ISSUE TITLE
apply style does not set altetred icon

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5285]
**Describe the bug**
apply style does not set altetred icon

**To Reproduce**

1. Go to lighttable
2. Click on any style
4. See error, style applied, thumb refresh but altered icon not set

**Expected behavior**
Altered icon should be set

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian

**Comment by TurboGit** [comment]
@phweyland : if you can have a look it would be nice. thanks.

**Comment by phweyland** [comment]
> @phweyland : if you can have a look it would be nice. thanks.

I'll do.

**Comment by AxelG-DE** [comment]
I hope this connection I made, makes sense for you guys

**Comment by AlicVB** [comment]
@phweyland : so it's for me :)
