### ISSUE TITLE
cannot edit style

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5286]
**Describe the bug**
Cannot edit a style, whatever we select do is not updated into the selected style

**To Reproduce**
1. Go to lighttable, select a developed image
2. Click on a style
3. Then [edit] on the styles module
4. Select some module to add to style
5. Click on [save] in the dialog

The style is not changed, set mouse over or apply it to check.

**Expected behavior**
The new selected module should be included into the style.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Additional context**

**Comment by Nilvus** [comment]
I indeed see that issue yesterday night.

**Comment by TurboGit** [comment]
I found another issue to fix, the update of module order when editing style is not implemented.
