### ISSUE TITLE
history on altered icon not updated

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5287]
**Describe the bug**
The list of history module in the altered icon tooltip is not updated in some context.

**To Reproduce**
1. Go to lighttable
2. Select an image
3. Go to darkroom
4. Activate some modules
5. Back to lighttable using L key
6. Go over the altered icon with the mouse
7. History is displayed but no containing the newly activated modules

**Expected behavior**

The tooltip should be up to date.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Additional context**

**Comment by TurboGit** [comment]
@AlicVB : probably for you this one ?

**Comment by AxelG-DE** [comment]
I hope this connection I made, makes sense for you guys
