### ISSUE TITLE
Spin-button field in prefs don't get saved immediatelly on prefs-close

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#5294]
**Describe the bug**

When entering value in spin button inputs (eg lighttable -> number of folder levels to show in lists) value isn't saved when clicking "x" or exiting via "esc" key

**To Reproduce**

Obviously value should be saved :wink: 

**Screenshots**

unfortunatelly performing screenshots is problematic as "changed" or some other event is fired before screenshot is completed.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+1703 (others up to current master are affected)
 - OS: Gentoo Linux
 
**Additional context**

 - Can you reproduce with another Darktable version? Yes, pretty much since new prefs window. With old prefs window it seems that clicking "close" button allowed spinbutton to trigger changed event. clicking on "X" however still produces same result
 - Did you compile Darktable yourself? If so which compiler was used, with what options? Yes, typical build.sh
 - Is the issue still present using an empty/new config-dir? yes :)

This stems from discussion in #5293 and I hope @elstoc'll be able to chime in here :)

**Comment by elstoc** [comment]
I suspect it's an issue as you say with the spin button not registering the value as changed until you tab away from it or otherwise click elsewhere in the dialog. I'm not sure what to do about it.

**Comment by Nilvus** [comment]
Entering values just need to apply them (so pressing enter do the work).

**Comment by johnny-bit** [comment]
> I'm not sure what to do about it.

Handle a bunch of signals? :stuck_out_tongue_closed_eyes: I think handling key_release should work for valid value if possible.

**Comment by chhil** [comment]
> I suspect it's an issue as you say with the spin button not registering the value as changed until you tab away from it or otherwise click elsewhere in the dialog. I'm not sure what to do about it.

A similar thing happens in the export, where you set dimensions. If you just change the dimension and update the preset it doesn't work. You have to get to a different control to save it.

**Comment by GrahamByrnes** [comment]
A sort of tangential question: is there a signal raised by changes to prefs?

Obviously there shouldn't be where dt writes changes to the db, but when the user opens it and changes things? It would be useful to me to know if such a thing exists :-)

**Comment by AlicVB** [comment]
@GrahamByrnes : yes, there's `DT_SIGNAL_PREFERENCES_CHANGE` though I'm not sure exactly when it's raised. When user close the pref window, I think...
