### ISSUE TITLE
Glitch issue on vertical images in overlay_hover and overlay_hover_extended modes

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5300]
**Describe the bug**

See below (extension name issue and no space on the bottom for stars icons) when hovering images:

hover mode:
![2020-06-03_21-42](https://user-images.githubusercontent.com/45535283/83682011-95f14e00-a5e3-11ea-9218-07108c81ffd5.png)

hover_extended mode:
![2020-06-03_21-47](https://user-images.githubusercontent.com/45535283/83682223-ec5e8c80-a5e3-11ea-88e3-ee2d25ed891d.png)

On both modes hover overlay and hover extended overlay. This issue probably appear from #5268. @aurelienpierre or @AlicVB: this one probably for one of you.

**Expected behavior**
Extension image should not be overwritten by image and star should remains below the image not hover it.

**Comment by Nilvus** [comment]
Same would be if audio/group ones. So need to be sure top and bottom margins are the same on all overlays mode, even if nothing shown.

**Comment by AlicVB** [comment]
> Extension image should not be overwritten by image

That's an "historical" reason : the extension was part of the background. I don't care too much about it's position, so we can make it work like all other icons... @aurelienpierre : any thought ?



> star should remains below the image not hover it.

Nope, that's "by design" : I've added the "always_*" mode which reserve the space need for the overlays. In hover_* mode, we use the maximum space for the thumbnail and we draw overlays over the thumbnail on mouse over (note that there was a semi-transparent background at some point, but I remove it because it was too ugly for lot of people)

 

> So need to be sure top and bottom margins are at least added when hovering or better let them set.

Not sure to like the idea either : that would means a "jumpy" gui when the mouse move between thumbs (not to speak that it would require some rescaling of the thumbnail at each mouse_over_id change and that's exactly what I've tried to avoid with this rewrite)

**Comment by elstoc** [comment]
> Nope, that's "by design"

Yes don't change that! I'm using CSS tweaks to make the 'hover' mode overlays look like that all the time. I want maximum image size and to be able to see star/colour ratings for all my images (like in 3.0.x).

**Comment by Nilvus** [comment]
Ok, I understand about stars, except that they can't be over the image on classic hover mode (first image above) just because the stars will be quickly not visible. But indeed, you're right for the second image and hover_extended mode. My bad here!

So remains just 2 things:

- Top margin should remain the same to be sure all icons and ext name are not hidden by the image or override the image in all mode and hover effect here.
- Just be sure stars are not on the image on hover only mode (first image above)

**Comment by elstoc** [comment]
> Ok, I understand about stars, except that they can't be over the image on classic hover mode (first image above)

> Just be sure stars are not on the image on hover only mode (first image above)

That's exactly what I'm arguing against. In classic hover mode the stars/colour ratings should be over the image (in portrait images) when you hover with your mouse (and in my case, even when not hovered). Otherwise you have to reserve space for them which will most of the time go unused. In that case you might as well have the overlays permanently displayed, for which there's already an option.

I know nobody wants another preference setting, but perhaps there's a place here for a global preference to either reserve space for overlays or have them appear over the image.

**Comment by Nilvus** [comment]
@elstoc: I understand the idea to let space but you forget one important thing, the visibility of icons on images in that mode (only that hover mode, so mode 2 on the popover list). I already see users come back here and post an issue because the stars will not be visible... And of course it will not be possible to set color regardless of image colors... On extended modes, it's ok, not on this only hover mode.

**Comment by Nilvus** [comment]
> This is how I have my overlays permanently via CSS. The reject and colour icons only appear if they are set.

Yes, all that is possible with CSS but we have different modes and for different reasons. And some modes are there to have infos hover images, but not all. But you're free to have what you want on your side. Anyway, you can't have any setting that will make icons visible as it should on all images. About not so visible stars, I see the selected image on your example.

When those modes were written just few days ago, what I pointed here was not there and nobody cry about that. Only hover mode is not made to have stars hover image. I insist. I'm quite sure we will have people complain about stars not visible (and you seem to do not take that in account but for a default mode on a software, it's something important). And I will not break nor accept to break CSS for that (as it will not be possible to satisfy all possibilities and make modes inconsistent between them).

> By all means try to make the icons more visible when they're over images but I still want them appearing over the images.
> 
> I could probably do the same thing with the second hover mode but again, you might as well use the permanent mode if you're always going to reserve space to the overlays.

I really don't understand anything you said here.

**Comment by AlicVB** [comment]
Hmm.. rereading what you say, I really thing we are all speaking of the same things, but with different opinions :(

The fact that the overlay `overlay on mouse hover` (2nd choice in the list) doesn't reserve space (on top and bottom) is done on purpose.
It handle the case where the user want to have maximum space for the thumbnails without loosing the ability to see and change the rating of an image if needed. This is exactly what was handle by default overlay before the recent overlays work.
Thought I agree on 1 point, it would be better to have by default a semi-transparent background like for the `extended overlay on mouse hover` mode to avoid the readability issue (that was my first idea...)

Anyway, imho the main interest of such a mode is to have bigger thumbnails. If we force a blank space under each thumbs, this mode become quite useless...

**Comment by AlicVB** [comment]
We can also have another approach, little more complex but more versatile : 
we can separate overlays option in three independent parts : 
- type of overlays : none/normal/extended/block
- visibility : mouse hover/permanent/timeout
- reserved space : yes/no

That way, we can cover all the possibility and a little more. For gtk code, it won't need too much change, but that may require some work for css (again)
Note that this solution will also require a lot of testing as we will have way more possibilities...

**Comment by Nilvus** [comment]
> Hmm.. rereading what you say, I really thing we are all speaking of the same things, but with different opinions :(

Not so much different opinions. I totally agree and like the idea to let most space as possible to the image and it, at first, the purpose of first mode. My purpose here is only about the downside of visibility (seems to be forget on your last answers...).

The only downside on overlay on mouse hover mode (forget the extended one, that was my mistake) is visibility of infos inside the thumbnails. Past few weeks, we spent time on improve the UI, polish it and this is not polished. If we let that as it is, we wiil soon (at least after 3.2 release) have users complains about that.

We can't let extension name and icons on top right overriden by the image. We can't have stars that could be hard to show depending of the bottom color of the image. And we can't count on CSS color only for that as all images (and so color) are different and infinite.

Apart of that, most other software doesn't override images. But we can of course make that different.

So, we need to find a better way with all that. I don't want to see issues after 3.2 release about that.

**Comment by elstoc** [comment]
You still might want the ability to possibly have different overlays on hover. How about instead if you had 

- type of overlays without hover
- type of overlays on hover
- reserved space

So in my case I might want normal overlays permanently displayed and then extended overlays on hover.

**Comment by Nilvus** [comment]
> We can also have another approach, little more complex but more versatile :
> we can separate overlays option in three independent parts :
> 
>     * type of overlays : none/normal/extended/block
> 
>     * visibility : mouse hover/permanent/timeout
> 
>     * reserved space : yes/no

> That way, we can cover all the possibility and a little more. For gtk code, it won't need too much change, but that may require some work for css (again)
> Note that this solution will also require a lot of testing as we will have way more possibilities...

Too complex for that and will probably create more possible issues than it is actually. We need to avoid to override the UI and make that too complex and hard to maintain (and understand).

Again, the only goal is to be sure infos shown are visible as let as much space as possible for the image. And remember that the first mode (no overlay) remains the best for the image at it's best.

So about the 2 issues:

- top margin with extension name and icons on top right on overlay on mouse hover and extended one
- stars on overlay on mouse hover

I see at the moment 2 things to try:

- Adjust image only when hovering to add icons as they should on top and stars on bottom, so without override. That means most space for the image by default and just less on hover effect only. I think most of the time we hover the image to show infos so let them more space is consistent to the mode and idea behind. And when not hovering, come back to image on most space.

For me, it could be a good compromise but need to see in real if the effect is good (or not). And I'm not sure it can be done only with CSS.

- Other possibility that I will try: see if I can find another way with CSS (yes, that's not precise but I don't have more actually).

**Comment by AlicVB** [comment]
@Nilvus : I completely agree for the visibility part, and especially for the the stars line. That's why I propose to add a semi-transparent background between the image and the stars, like the one we have to the extended on hover mode.
For the top icons, imho, they are less useful and we can forget the case where they are difficult to read (they are even removed for culling/preview) but ultimately we can image a background too



> Adjust image only when hovering to add icons as they should on top and stars on bottom, so without override. That means most space for the image by default and just less on hover effect only. I think most of the time we hover the image to show infos so let them more space is consistent to the mode and idea behind. And when not hovering, come back to image on most space.

I'm not in favour of this as it will have 2 big drawbacks : 
- we will get back cpu workload on mouse hover (resizing of the thumbnail)
- the ui will appears "jumpy" when you move the mouse inside the central view, esp. if you go from left panel to the right one quite quickly. Another drawback of jumpy ui, is that user (at least me) lose their marks quite quickly... That was the case at some point for some darkroom modules and it was horrible...

**Comment by Nilvus** [comment]
>     * type of overlays without hover

It's called always and always extended overlays (so exist)

>     * type of overlays on hover

Both modes we are talking about and one with visibility issue I talk about.

>     * reserved space

That exist on some modes.

> So in my case I might want normal overlays permanently displayed and then extended overlays on hover.

Wa need to be careful to not have too much modes. Some users will want another way and then another way, etc. We need to be careful to not override the UI.

**Comment by AlicVB** [comment]
>     * The issue is not on reject icons and colorlabels which are outside the image

not with square image ;)

>     * do you think it could be easily possible to add a "box" where stars are inside and set background for that box and only the hover mode to not break other modes

I propose to use the same widget as the one use for extended_hover, but without the text, of course
you can try it with adding `.dt_overlays_hover #thumb_main:hover #thumb_bottom` to the list where we apply `background-image: linear-gradient(0deg, rgba(220, 220, 220, 0.8) 0%, rgba(220, 220, 220, 0.8) 95%,rgba(220, 220, 220, 0) 100%);`

**Comment by AlicVB** [comment]
There's a little point where we can improve things, thought : 
don't you think it's possible to align the gradient color to the background one ? I can have a try for default theme, but I'm unsure for derivative ones...

**Comment by AlicVB** [comment]
> Could you confirm also if the idea to hide extension name and top icons on hover and hover_extended modes only is ok for you?

it's not the best, but I don't have any other proposal for now. I've done a quick mockup of using a second background on top like what we'll do on bottom, but that was "sandwich" like... very strange imho

**Comment by Nilvus** [comment]
@AlicVB: I have a problem that I don't understand. You seem to have a top margin on your last image and that's good on overlay on mouse hover mode. I don't have one even if I try same settings as other modes but that's because of the thumb_bottom_label that is inside a box. I've try to set margins on star and even on reject, star and colorlabels. Gtk Inspector tool that it's set but no margin shown and that's not good without same margin as other modes when we have text. Any idea?
![2020-06-04_23-38](https://user-images.githubusercontent.com/45535283/83812853-83971300-a6bc-11ea-96a1-41fe878f98ca.png)

**Comment by Nilvus** [comment]
An accident but maybe I found a way to not need a top margin and maybe have a quite better compromise (need to push and improve) but maybe a better one:

![2020-06-04_23-43](https://user-images.githubusercontent.com/45535283/83813302-5d25a780-a6bd-11ea-9968-64b7486c3af9.png)

**Comment by elstoc** [comment]
I do like the gradual fade-out at the top. As you know, though, I want to see the stars, reject and colour labels permanently (where they're set) so I won't specifically be using the 'hover' modes, except perhaps to set the star rating. 

What you've put is fine for if you're just hovering but I'd want something where I can see as much of the image as possible, even behind the stars, so that background should be as transparent as you can get away with and still easily make out the stars.

I suspect that I'll end up writing my own CSS in the end though (because the requirements for permanent overlays and hover will be different) so perhaps don't pay too much attention to me.

**Comment by AlicVB** [comment]
> An accident but maybe I found a way to not need a top margin and maybe have a quite better compromise:
> 
> ![2020-06-04_23-43](https://user-images.githubusercontent.com/45535283/83813302-5d25a780-a6bd-11ea-9968-64b7486c3af9.png)
> 
> @elstoc and @AlicVB: your view on that last one (need to be tested more, just a good accident I think).

Sorry, I forgot to answer... Yes I quite like this proposal. That said, I know why you can't have the margin : that's because the gradient use already all the margin size. So either we need to remove the gradient for a basic semi transparent background-color, either I can make the top margin greater (should be done in gtk)...
That said, I repeat, your last solution seems visually better to me...

**Comment by Nilvus** [comment]
> Sorry, I forgot to answer... Yes I quite like this proposal. That said, I know why you can't have the margin : that's because the gradient use already all the margin size. So either we need to remove the gradient for a basic semi transparent background-color, either I can make the top margin greater (should be done in gtk)...
> That said, I repeat, your last solution seems visually better to me...

So if I understand you correctly here, we have 2 solutions here:
- Or let a possibility to have gradient background at the bottom (like my last proposal) and no possibility to fix correctly the top icons and ext name issues
- Or we made a basic semi transparent background only and it could be possible to fix top margin view

If I understand well, I would be to continue by hiding top infos and use my last proposal. But, maybe a third way could be possible (and tried):

- I see that top icons on the right are shown above the image but not extension name that is shown below the image (so end of ext name is hidden). If it's possible to just put ext name above the image like top right icons), I could try something similar to my last background proposal and see if it could be another possibility. And if it doesn't work, we could come back with what I made by now, so hide top infos.

**Comment by AlicVB** [comment]
>     * I see that top icons on the right are shown above the image but not extension name that is shown below the image (so end of ext name is hidden). If it's possible to just put ext name above the image like top right icons), I could try something similar to my last background proposal and see if it could be another possibility. And if it doesn't work, we could come back with what I made by now, so hide top infos.

it will require to add some new widgets (for the background) but it's possible. That said, I've done a quick mockup and I'm not convince it's a good idea : the effect was... strange "sandwich" like...
So I'm in favor to hide the top icons and use your last proposal with gradient background for the bottom.

**Comment by Nilvus** [comment]
> So I'm in favor to hide the top icons and use your last proposal with gradient background for the bottom.

The strange "sandwich" was a possible side-effect, so forget that one and let's go for my last proposal to hide top icons with gradient background. I could now finish that. Good.

**Comment by Nilvus** [comment]
Closed as solved by #5303 PR
