### ISSUE TITLE
User Manual: Chapter 1

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5301]
### What is this Issue For?
The user manual is one of those things that never really gets a lot of love. It gets the occasional update when big new features go in but most of these are incremental and often fairly basic  Some sections of the manual need reorganisation. Many (most) are missing new features. As we get more developers contributing more changes, this is only going to get worse.

I'd like to propose that we take the manual chapter-by-chapter (perhaps splitting some of the more complex chapters further) and for each chapter have an issue that we can use to discuss any changes that are needed and perhaps allocate out some or all of that chapter to a volunteer to edit.

I have some ideas for starters but I hope that this will get a bit of momentum going and others will contribute. I'll try to keep this first post up-to-date with people's ideas and when it starts looking good we'll try and get the changes made.

If it works I may even raise another issue for Chapter 2!

#### General Features
Wow that's a long list of bullets. I feel like I'm watching a PowerPoint presentation. Perhaps we could choose a few of the important ones or even just start with a very basic end-to-end description of the program, like a much more basic version of section 1.3 (basic workflow). Perhaps also things like who it's for, the kind of learning investment you'll need to make, where to find other resources.

#### 1.1 Program invocation
If we're wondering why people don't read the manual it's because it starts with very technical sections like this. Could I suggest just a brief description here (if we include it at all in this section), with the details of all the options moved to a much later section (appendix?), or even with just a reference to the man page, which seems to contain much the same detail.

#### 1.2 User Interface
Not sure I've much of an issue with this section right now but I'm sure I'll think of something!

#### 1.3 Basic Workflow
This is where we grab people's attention and really help them get their head around darktable but some of it's a bit dated (especially given many of the recent linear RGB changes). I would suggest that @aurelienpierre has done much of the hard work for us and something much more useful could be knocked up based on his articles and how to guides on pixls.us.

Now time to see if I'm just talking to myself. What changes would **you** like to see?

**Comment by paperdigits** [comment]
I don't know about Chapter 1, but we should for sure have a high-level "I AM NOOB, HELP!" section.

**Comment by Nilvus** [comment]
@elstoc: as you wrote a whole new manual in dtdocs, is that issue needs to remains open?

**Comment by elstoc** [comment]
No. This one can be closed now
