### ISSUE TITLE
Filmic V4 - middle grey slider missing on second instance

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5307]
I created a second instance of filmic V4 and used as mask the raster masks option, selecting a mask I had created for the exposure module.  This resulted in the middle grey slider not being shown.  I think all other sliders were present.  If I created the mask directly, e.g. painted one, then the slider was present.

dt 2.5.0+5240~g92d9da966-dirty   Aurelien's environment.    ubuntu 18.04   

[_5D_02278.CR2 no-middle-grey.txt](https://github.com/darktable-org/darktable/files/4730459/_5D_02278.CR2.no-middle-grey.txt)

XMP causing this is attached but renamed to .TXT (.XMP not uploadable)

**Comment by TurboGit** [comment]
You need to activate the middle-grey sliders from last tab (new v4 does not propose grey by default).

**Comment by RawConvert** [comment]
Ah, sorry, I forgot about the Option tab, I haven't used it recently due to having a Style. A mystery how it was present with the painted mask above though.
