### ISSUE TITLE
[FR] add lightness range to pixelpipe data

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#5337]
**Is your feature request related to a problem? Please describe.**

As mentioned in the comments on #5324, raising exposure with the exposure iop leads to downstream issues with parametric masks and the bilateral filter, and potentially other operations using luminance (whether from Lab colorspace or computing some function of R/G/B values).

**Describe the solution you'd like**

I believe these issues can all be addressed by passing one additional value down the pixelpipe, presumably in the dt_dev_pixelpipe_t passed to iops as "piece".  This value would be a scale factor which indicates the brightest possible pixel, 1.0 at the start of the pixel pipe, and adjusted appropriately by exposure, filmic, and the two tone mapping iops (e.g. +1 EV changes it to 2.0).  Operations which rely on luminance in some fashion could then rescale values appropriately -- "255" as presented to the user in a parametric mask would always refer to the brighest possible, regardless of exposure compensation or tone mapping earlier in the pixel pipe.  The operation of the bilateral filter would then also no longer vary if brightness is increased.

**Alternatives**

Each iop that assumes 100% as maximal luminance could compute the current image's maximum pixel value, but that will result in effects varying depending on the content of the image, and can result in different outputs if the operation is tiled.  It also wastes time recomputing the scaling factor.

Parametric masks could work without scaling, but would require the user to be able to set values greater than 100%.  There is no hard upper bound on how high a value the user might need to set to encompass the entire lightness range, *requiring* settings higher than 100% would be confusing for non-technical users, and not scaling is more likely to require modifying the parametric mask if the exposure is changed earlier in the pipe.

**Comment by aurelienpierre** [comment]
You can't loosely scale Lab to normalize it and expect the color space to hold. It is possible in some carefully choosen situations, but not in general.

Having Lab values above 100% should not prevent local filters to work though, what is the exact issue ? Is it active clamping in code ?

**Comment by parafin** [comment]
We already have processed_maximum[] (https://github.com/darktable-org/darktable/blob/master/src/develop/format.h#L59), isn't it enough?

Changing how parametric masks work must be done carefully in order not to break compatibility with old history stacks.

**Comment by ralfbrown** [comment]
@parafin: processed_maximum does look like exactly what I was proposing, though right now only exposure updates it AFAICT.  It should probably also be updated by channel mixer (for any channels with total weight > 1), color balance, global tonemapping, filmic, and a few others.  And we may want to consider having it start at some value greater than 1 when loading an HDR image.

Backwards compatibility on the parametric masks should be pretty easy: bump the version number on the blendop parameters and apply the scaling of the blending ranges only for the new version and higher.

@aurelienpierre: I get that you're on a crusade to eliminate Lab and move everyone to scene-referred, but you'll get less pushback from people if they don't lose existing capabilities in the process.  Right now, if I use exposure to adapt my D7200's 6.25% metering to filmic's desired 18.45% instead of setting filmic's mid-gray slider to 6.25%, parametric masking becomes pretty much useless for any modules in between.  Since exposure needs to scale all values by a factor of three, it becomes impossible for parametric masks to have any control over values above 1/3 of max in the R, G, B, g, L, and V channels (and probably a and b as well, if the RGB->Lab conversion just does a matrix transform).

As far as clamping, the bilateral filter (used by seven iops plus the 'get structure' operation in perspective correction) clamps luminance to 100% internally when generating its blurred mask, so all pixels >= 100% get treated equally.  Shadows and highlights clamps when using the bilateral filter, and lowpass has a flag on whether or not to clamp, but slows down considerably if not and there are a lot of pixels > 100% (as it then performs two calls to powf() instead of using precomputed tables).

**Comment by aurelienpierre** [comment]
I'm not on a cruisade to move people to scene-referred, but some filters make no sense in Lab. Namely, frequency filters.

There is no reason to clamp bilateral filter to 100%. It's excessive precaution. Similarly, there is no reason to clamp most blending modes to 100%. That's where energy should be invested. I know @hlecleme had a project to unclip mask API, not sure where it is. Did you try to simply remove the clamping in bilateral ?

Then, nothing prevents parametrics blending **controls** to move past 100%, it's simply control scaling in GUI. Don't mistake controller and model. 

But scaling pixels in Lab won't preserve the color in general. Scaling doesn't have the same meaning in non-linear spaces than in linear RGB. That's why scene-referred workflow is superior : you can indeed scale, rescale and unscale with no problem.

**Comment by ralfbrown** [comment]
Bilateral filter clamping is actually an implementation issue -- it uses a fixed size 3D grid (size determined by the filter parameters), such that L>100 would fall outside the grid and hence trash memory.  We can address that by knowing just how high L goes -- it would in fact be just one extra line of code in each iop using the filter if it weren't necessary to retain backward compatibility.  It also uses only the L channel, so it should work just fine on a linear brightness value of some kind if you want to get rid of Lab, but it still needs to know the possible range of that brightness value to avoid clamping.  The tonemap iop uses a simple weighted sum of RGB as its brightness value for a different implementation of the bilateral filter which may not clamp (at least it doesn't explicitly do so) but is also much slower.

And control scaling for the blending UI is in fact what I'm suggesting (the *displayed* range of the controls stays invariant but goes past 100% internally), but to implement the scaling you need to know what the scale **is**....  Keeping the controls such that a fixed value stays the same relative fraction of the possible maximum allows for presets that are independent of earlier processing in the pipeline and means that users don't (necessarily) have to fiddle with the blending if they go back and change global exposure in one of the numerous possible ways.  E.g. if I have a parametric mask for highlights, I can increase exposure and compress the highlights more with filmic without changing the mask parameters, while if the control values are absolute I've just moved a bunch of non-highlight pixels into the range affected by the mask.

**Comment by ralfbrown** [comment]
Closing because the new 'boost' slider in blending provides the equivalent of the second alternative I mentioned originally.
