### ISSUE TITLE
[FR] Auto-apply Filmic RGB

### ISSUE THREAD

**Issue by ItaloCunhaBueno** [darktable-org/darktable#5343]
Would be nice to have an option in menu to auto apply Filmic RGB to newly imported images, just like basecurve

**Comment by parafin** [comment]
You can create an auto-applied preset yourself: https://darktable.gitlab.io/doc/en/presets.html
Also PR #5324 will add the option you want.

**Comment by ItaloCunhaBueno** [comment]
> You can create an auto-applied preset yourself: https://darktable.gitlab.io/doc/en/presets.html
> Also PR #5324 will add the option you want.

That's great, thanks a lot.
