### ISSUE TITLE
crash on reimporting xmp file

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#5351]
reimporting a directory with existing xmp files results in a crash:
```
Process 41701 stopped
* thread #7, name = 'worker 0', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100166403 libdarktable.dylib`dt_exif_xmp_read + 16659
libdarktable.dylib`dt_exif_xmp_read:
->  0x100166403 <+16659>: ud2
    0x100166405 <+16661>: movq   0x2d0d0c(%rip), %rax      ; (void *)0x00007fff9962c660: __stderrp
    0x10016640c <+16668>: movq   %rax, %r14
    0x10016640f <+16671>: movq   (%rax), %rdi
Target 0: (darktable) stopped.
```

**To Reproduce**
1. new build current master, delete ./config/darktable directory
2. test directory with just raw files 
3. start darktable (default settings enables writing of xmps), import test directory
4. exit darktable so xmps are written to direcroty
5. restart darktable
6. reimport test directory 
--> crash

also reproducible when importing just the xmp via "load sidecar file ..."
also reproducible after deleting ./config/daktable and importing the directory with existing xmps

test raws: 
https://mega.nz/file/nCAXzI4Y#IikcBEwmKgJgkYgl0CDGES88qwa9h9cOlSaL6jwF1zE https://mega.nz/file/mX5A1aJQ#WC0_NW1AOYN-TQhlB__JbvFFDhEqpRxSyUnLqQ9Zy9g)

crash log: 
[crashlog.txt](https://github.com/darktable-org/darktable/files/4747586/crashlog.txt)
darktable -d all output:
[darktabe_d_all.txt](https://github.com/darktable-org/darktable/files/4747620/darktabe_d_all.txt)

xmps:
[20190223-IMG_3616.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/4747588/20190223-IMG_3616.CR2.xmp.txt)
[20200530-IMG_8649.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/4747589/20200530-IMG_8649.CR2.xmp.txt)

**Platform (please complete the following information):**
 - Darktable Version: 
```
darktable 3.1.0+2003~g2ee22dac3f
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```
 - OS: OSX

**Comment by MStraeten** [comment]
wasn't able to reproduce it after an update of macports and a full cleanup of my build enviroment (rm -rf * in the build directory etc.pp) ...
it seems to pop up infrequently but then reproducible until a full cleanup of the build enviroment

**Comment by phweyland** [comment]
I've tried your procedure on the current master and it works for me. I can re-import the 2 images in both cases:
- with your xmp files
- with the xmp files created at the first import.

debian 10.
