### ISSUE TITLE
Noise profile for Olympus M5 mark III for review

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#5357]
Please review my noise profile.
I can not tell by the graphs if they are correct. Please tell me if it is good enough or if I should improve these. 

This noise profile is for all the ISO settings in 1/3 steps of the Olympus M5 mark III. No interpolation necessary.
Camera is from november 2019. Firmware is the most recent update.

**Also please tell me if more pictures per ISO make sense** (is it averaged out), or not. 

[darktable-noiseprofile-20200608.tar.gz](https://github.com/darktable-org/darktable/files/4748657/darktable-noiseprofile-20200608.tar.gz)

**Comment by rawfiner** [comment]
Thanks for the noise profile.
We actually already have one for this camera

**Comment by rekcodocker** [comment]
Thanks for the feedback. 
Can noise profiles be averaged for better quality?

**Comment by rawfiner** [comment]
They could be averaged if they are integrated at the same time, but as soon as a profile is integrated, we should not modify it anymore for backward compatibility reasons

**Comment by hatsunearu** [comment]
Nominate to close this issue?

**Comment by johnny-bit** [comment]
> We actually already have one for this camera

so

> Nominate to close this issue?

yes :)
