### ISSUE TITLE
NTFS volume mount point is not visible in import dialog

### ISSUE THREAD

**Issue by moledzki** [darktable-org/darktable#5358]
**Describe the bug**
[NTFS volume mount point ](https://en.wikipedia.org/wiki/NTFS_volume_mount_point) directory is not visible in import dialog window. It prevents me to import photos located in this directory.

**To Reproduce**
1. Mount NTFS partition with photos to Pictures/Test folder
2. Try to import Pictures/Test folder
3. Pictures/Test folder is not visible in import dialog.

**Expected behavior**
Pictures/Test folder should be visible in import dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/5674840/84116257-c5fb7f80-aa2f-11ea-82ae-c7bdc752da89.png)
![image](https://user-images.githubusercontent.com/5674840/84116312-da3f7c80-aa2f-11ea-8f2d-bf9a180f9cb8.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Windows 10
 - OpenCL not activated
 - GF 9600GT

**Comment by parafin** [comment]
It looks like a link, not a mount point...

**Comment by parafin** [comment]
In any case I guess it's a bug report for GTK.

**Comment by moledzki** [comment]
It looks like a link, but it is NTFS mount point.

**Comment by 13aumi** [comment]
Hi folks, I would like to affirm, that Darktable does not show an NTFS partition in the Import dialog.
I am using Ubuntu 20.04 and Darktable 3.0.1. The NTFS partition is correctly mounted (I can read/write files on it). However, Darktable does not show that partition in the Import dialog.

**Comment by ptilopteri** [comment]
I am able to import from ntfs partitions via cifs and sshfs.  Do not have a directly connected drive to check.

But, as dt runs on windows, I cannot fathom dt not being able to access ntfs partitions.

**Comment by parafin** [comment]
@13aumi, this sounds totally unrelated. You can just browse to whenever drive is mounted in import directory/files dialog.

**Comment by coffeeandspaceships** [comment]
> But, as dt runs on windows, I cannot fathom dt not being able to access ntfs partitions.

I cannot fathom how an application in userland on Linux could even care what type of filesystem it is, unless there is some explicit check for NTFS for some weird reason. A mounted filesystem is a filesystem. GTK will access it through the API to list and open files. That's all!

In Linux (mostly Ubuntu) I used Darktable on mounted NTFS (native), mounted NTFS (fuse), and even mounted HFS+ from an external disk I also used with a Mac.

@moledzki can you please show us the output of `findmnt <your mount point>` ?

**Comment by 13aumi** [comment]
In fact, I couldn't see that partition in the import dialog but itwas not related to NTFS itself. Sorry, if my post was totally unrelated.

After some research I was able to solve my problem using the following command:
`sudo snap connect darktable:removable-media`

**Comment by moledzki** [comment]
> @moledzki can you please show us the output of `findmnt <your mount point>` ?

This problem occurred on Windows.

**Comment by johnny-bit** [comment]
@moledzki - can you check if similar problem happens in any other gtk-based application on windows, eg GIMP? it looks like it's a windows-only problem for gtk, since the dialog in your screenshot is controlled by gtk...

(which might not be an issue if we could switch import now to native dialog for selection)

**Comment by moledzki** [comment]
The same problem happens in GIMP.

**Comment by johnny-bit** [comment]
then there's nothing darktable can do about it. You'd have to open up a new issue regarding gtk problem on windows with https://gitlab.gnome.org/GNOME/gtk

Additionally with 3.6 darktable will have different way of handling import dialog so it MIGHT work.

Please open issue with GTK and post link here.

**Comment by moledzki** [comment]
OK, bug has been submitted to GTK project: https://gitlab.gnome.org/GNOME/gtk/-/issues/3972

**Comment by johnny-bit** [comment]
Thanks! Since we (as in darktable devs) can't really do much about it - would you mind closing the issue?
