### ISSUE TITLE
Pixelfed storage

### ISSUE THREAD

**Issue by sanpii** [darktable-org/darktable#5360]
Hello,

[Pixelfed](https://pixelfed.org/) is a federated photo sharing software. 

**Describe the solution you'd like**
It would be nice to have a storage module to export photo to a pixelfed instance.

**Alternatives**
The API is the same as [mastodon](https://docs.joinmastodon.org/methods/apps/) (a federated social networking), it’s probably a better idea to add a mastodon module.

**Additional context**
- [Pixelfed API documentation](https://docs.pixelfed.org/technical-documentation/api-v1.html);
- [Mastodon API documentation](https://docs.joinmastodon.org/methods/apps/).

**Comment by aurelienpierre** [comment]
External storage is not supported in core anymore but through Lua extensions : https://github.com/darktable-org/lua-scripts. The reason is it's easier to update Lua extensions, possibly between releases, in case the API changes unexpectedly.
