### ISSUE TITLE
Mouse Wheel Support in "modules" section

### ISSUE THREAD

**Issue by zyxtaxbo** [darktable-org/darktable#5363]
**Is your feature request related to a problem? Please describe.**

e.g. when You develop images and You use a lot of different modules, You need to scroll to see all the available options. Unfortunately in this section using the mouse wheel is not supported for scrolling.

**Describe the solution you'd like**
I would like to use the mouse wheel or trackpad gestures for scrolling and not for setting values.

**Comment by johnny-bit** [comment]
It is already possible.

hold ctrl+alt when scrolling and it'll scroll nicelly and allow you to also use scroll to adjust values.

if you go to preferences there's 'mouse wheel scrolls modules side panel by default' option which does exactly what you wish.

Try it and close this issue if this solves your problem please :)

**Comment by elstoc** [comment]
or hover your mouse over the scrollbar and scroll that

**Comment by zyxtaxbo** [comment]
> It is already possible.
> 
> hold ctrl+alt when scrolling and it'll scroll nicelly and allow you to also use scroll to adjust values.
> 
> if you go to preferences there's 'mouse wheel scrolls modules side panel by default' option which does exactly what you wish.
> 
> Try it and close this issue if this solves your problem please :)

Thanks for Your advice.
Work, except with module "tagging". ctrl+alt+mouse wheel let grow the sections, where tags are listed.
