### ISSUE TITLE
smarte size adjustment in "spot removal" module

### ISSUE THREAD

**Issue by zyxtaxbo** [darktable-org/darktable#5364]
**Is your feature request related to a problem? Please describe.**
in "spot removal" module You can repair defects or hide dust in Your image.
Depending on the size of the defect, You can adjust the size of the "spot" by just using the mouse wheel. 
Unfortunately, if You work on very small defects like dust on a shiny surface, You can indeed make the spot size very small, but the transition with around the spot stays the same.
This can lead to a situation, where You create copies of Your original defect. 

**Describe the solution you'd like**
make the width of the transition zone adjustable or variable. 
Maybe a good algorithm would be:
if ( width_spot < 50px) return witdh_trans = 2 x width_spot ;
return witdh_trans = 100px;

**Comment by TurboGit** [comment]
No, don't use shift-scroll... **read the manua**l ! If you don't know how this works there is certainly many things you'll be missing and you will fill the tracker of issue report for nothing and loose our time. Thanks!

**Comment by zyxtaxbo** [comment]
Ok, rtfm, my bad.

But it seems, that shift+scroll does not work in the windows version (macos is ok).
