### ISSUE TITLE
darktable-cltest hangs after 'sharpen-mix'

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#5379]
Manjaro/KDE latest
Ryzen 3900X 
GTX-1660-Ti
I just fetched darktable 3.1.0+2050~g02678f4d9
and performed `rm -rf /home/claesl/.c*/darktable`
followed by `darktable-cmstest` It worked as expected.
But next command `darktable-cltest` hangs after
`0,756178 [opencl_create_kernel] successfully loaded kernel `sharpen_mix' (234) for device 0
`

`darktable-cltest -d all > urk.txt `
also hangs, but produces this text
[urk.txt](https://github.com/darktable-org/darktable/files/4758118/urk.txt)

Looks like this problem has popped up today..

**Comment by wpferguson** [comment]
I think this is probably fixed by #5393 and is the same as #5385.

**Comment by ClaesGitHub** [comment]
Thank you!
Seems to be fixed in 3.1.0+2076
