### ISSUE TITLE
Performance regression using image selections.

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#5381]
**Describe the bug**
I suspect a severe performance regression with image selections in current master

I didn't do measurements so far and have no data to compare against but since 3.0 selecting a large number of images and handling them seems to be much slower.

**To Reproduce**
1. Select a larger number of images, let's say 1000 somehow. This already seems to be much slower than it used to be.
2. Now delete history of the selected images. This takes "ages" now and the machine seems to be locked. Just a sidenote, after such an operation the database always wants to be maintained.

I worked on history compression and removing a while ago and never stumbled across this. (Here i gave the new filmic mode a try and what it offers for a fresh import.) Until 3.0.x it maybe took a few secs to remove history of 1500 images out of 6000 on my machine here, now it took more than 15 minutes. 

A first guess would be thumbnail redrawing is triggered by a signal **much** too often, database vs drawing interfering. @AlicVB @TurboGit  - any ideas about this? There have been many things done here with the new lighttable code, i didn't follow them in detail ... 

**Expected behavior**
Being fast and responsive.

**Platform (please complete the following information):**
current dt master 09.06.2020
fefora 32
Intel 7700, 32GBram
nvidia 5GB graphics, cl activated or not doesn't matter.

**Comment by jenshannoschwalm** [comment]
> Blocking signals during a massive changes is indeed a good idea.

Yes.
But this leads me to questions:
1. How can we block signals temporarily in a safe way?
2. Shouldn't we have a global mask `dt_ignore_signals` that is checked by `dt_control_signal_raise` and also could be tested by the specific callbacks?

**Comment by TurboGit** [comment]
@jenshannoschwalm : currently if my memory is correct we do disconnect the signals making problem, do the mass-job and the reconnect the signals.

Your proposals 2 seems a possible solution maybe cleaner, fact is that I don't know what could be the consequence of killing all signals. For example in a batch action on images we have probably many signals sent for the thumbs like updating metadata and updating the mipmap. If we kill both signals whereas only the metadata was really needed, won't we miss all update of the thumbs ?

So this solution may be opening a can of worms :)

**Comment by AlicVB** [comment]
well, as @TurboGit says, blocking signal may not be the thing to do, as I'm not sure which side effects this can have...

Maybe the best way is to ensure that no signal is called during such jobs. For example, for deletion, this is `DT_SIGNAL_IMAGE_INFO_CHANGED` which is called for each image, and indeed trigger a redraw.
Ensuring that this don't happen should be quite easy, just need to test all actions...

**Comment by johnny-bit** [comment]
This is smart thing to do! When I worked on multi-styles I've noticed that there's not even a bit of info shown to user that things are going or that things have ended... so I added dt_control_log call just to notify on end... I feel like there are several places like that, specifically in lighttable modules, where action can work on many images but are done in image-by-image loop which rises all kinds of signals per image...
I also like dt's jobs concept and the fact that those are underutilized in some situations (apply styles could be a job if there's plenty of images to apply and user selected couple styles ;)) I didn't touch those when doing multi styles because it's too big for me ATM...

Sorry for causing all this performance trouble with my little "disable/enable + couple other functionalities" PRs and unfortunatelly all I can help with would be testing solutions of more experienced devs ;(

**Comment by jenshannoschwalm** [comment]
I did some more testing my first positive surprise after blocking signals via ++darktable.gui->reset did **not** show any improvements, so it seems not to be related to signals pressure on redrawing.

But there is in fact a database problem. I added some debug printf and the time fore history deletion is not linear to the number of images but exponential.

```
Starting deleting history
 1 0,000000 0,000000 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 2 0,019507 0,019507 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 3 0,018325 0,037832 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
 7 0,018220 0,110841 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 8 0,018185 0,129026 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 9 0,018222 0,147248 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 10 0,018264 0,165512 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 done all, took 0,183779 0,000003 
Finished deleting history after 0,183816, collection update took 0,020493, redraw center took 0,020499

Starting deleting history
 1 0,000000 0,000000 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 2 0,085495 0,085495 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 3 0,083644 0,169139 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
 192 0,081970 15,882097 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 193 0,083087 15,965184 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 194 0,082970 16,048154 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 195 0,082597 16,130751 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 done all, took 16,213224 0,000002 
Finished deleting history after 16,213241, collection update took 0,056425, redraw center took 0,056429
```
Per image history removal there is a line above showing
1. index,
2. time-to-remove history for this image
3. overall time to remove

So when removing 10 histories it takes ~0.02s per image, when removing ~200 it's almost ~0.1s!!!

**Comment by johnny-bit** [comment]
It's DB issue alright... in cases like large deletes therre should be a single transaction open throughout the process. Even selects if there are some would benefit from transactions: https://stackoverflow.com/questions/7349189/optimizing-select-with-transaction-under-sqlite-3

**Comment by jenshannoschwalm** [comment]
Ok, but still i think the code used to be much faster. And why exponential?

maybe there is an index missing?

I am not speaking sqlite3 code well so can't be of help here.

**Comment by AlicVB** [comment]
@jenshannoschwalm : just to know, what make you think that it's a database problem ?

**Comment by AlicVB** [comment]
hmm... from my test, with discard history, the main problem is from the `DT_SIGNAL_TAG_CHANGED` signal which is called by `dt_tag_detach_by_string` 2 times by images.

For 200 images, I pass from 2.8 s to 0.6 s by just commenting the signal raise... Now I need to understand why this was needed in this case and replace it.

Surprisingly, removing `DT_SIGNAL_DEVELOP_MIPMAP_UPDATED` is unnoticeable (around 0.01 s for 200 images)

**Comment by jenshannoschwalm** [comment]
> just to know, what make you think that it's a database problem ?

I was under the impression i could block signals via `++darktable.gui->reset` and wrapped the `dt_history_delete_on_list` in delete_button_click/copy_history.c and found no performance difference. Unfortunately this assumption was wrong. (Only gui signals?)

I tested again with your scenario (commenting `DT_SIGNAL_TAG_CHANGED`) and indeed it's as fast as it used to be :-) Also the exponential performance is gone :-)


> Now I need to understand why this was needed in this case and replace it

Don't we have it to possibly recalculate the collection? If so, can't we just raise the signal once after bulk job?

**Comment by AlicVB** [comment]
> Don't we have it to possibly recalculate the collection? If so, can't we just raise the signal once after bulk job?

yes, seems so.
I've started to add a boolean to say if we want the signal to be raised or not, but that's quite complex, as it implies a very long chain of parent call. and we need to do that for other tagging fct too...

I wonder if we shouldn't add some param. somewhere to say "don't recompute collection now". That won't solve the root problem, but that will avoid to add too many complexity in the code (and that can be reused more easily for other actions if needed.)

**Comment by jenshannoschwalm** [comment]
It might sound more like a quick hack but `dt_tag_detach_by_string` is used just in two places i could find. Why not remove the signal raising in there and put it specifically where it's needed?

**Comment by AlicVB** [comment]
yes, I follow this way now. disabling the collection recompute wasn't really useful in fact.

I'll now try to audit other calls to `DT_SIGNAL_TAG_CHANGED` to avoid them to be called in loops

**Comment by johnny-bit** [comment]
On related note - would it be much work to add `-d signal` to allow for signal debugging and seeing if something gets called too much? :)

**Comment by johnny-bit** [comment]
As it turns out - rather not so much... see #5433 :)

**Comment by jenshannoschwalm** [comment]
Fully read through #5412 and tested, for me absolutely fine so closing this right now.
