### ISSUE TITLE
History stack strangeness

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5396]
Using the new 'scene-referred' defaults, I open a virgin image and the following are the contents of my history stack. For ease I'll refer to the modules by their number in the stack:

![Screenshot_2020-06-10_21-51-38](https://user-images.githubusercontent.com/9555491/84317492-c3e70d00-ab64-11ea-876c-f57389611be0.png)

The following is my active modules list:

![Screenshot_2020-06-10_21-51-57](https://user-images.githubusercontent.com/9555491/84317522-d103fc00-ab64-11ea-922b-c0a103e611bf.png)

If I click any item from 1-8 in the list, my active modules list excludes sharpen but otherwise does not change and nor does the preview image. If I click item 9, the sharpen module appears and if I click item 10, again, nothing changes.

I'd say that the history should have the entirely mandatory modules first (1, 3, 5, 7, 8), followed by the 'always applied' (2, 10) then the workflow modules (4, 6) and finally sharpen (9). Also, given that highlight reconstruction is 'always applied' that should probably appear as well (in the 'always applied' list.

Then clicking through 0 (original) and the first five (mandatory) modules should leave the image unchanged (as if you'd selected the fifth mandatory module) and all the others should progressively apply the modules in turn. 

3.1.0+2023~geb85207f2 on Arch Linux

**Comment by elstoc** [comment]
I've done a bit of investigation on this and a few things occur to me.

1. The issue around highlight reconstruction not appearing is in _def_add_default_modules (it's checking whether module->default_enabled == 1 and the "==1 is superfluous")
2. The issues around module order can also probably be resolved within that same function by just adding to the history in a more controlled order
3. The issues around the history not changing is probably more about how the 'on by default' modules work. Sharpen achieves this by having an automatically enabled preset that is applied (I assume) by _dev_auto_apply_presets, whereas the others (highlight reconstruction, filmicrgb, exposure, white balance) work by setting module->default_enabled. I suspect that using presets is probably the better way as it seems to mean that the history stack works more predictably.

**Comment by elstoc** [comment]
Another related issue, if I disable filmic, sharpen and exposure manually the history stack module still indicates filmic and exposure as active (white rather than grey), again, due to point 3 in my previous comment:

![Screenshot_2020-06-11_17-00-12](https://user-images.githubusercontent.com/9555491/84409223-0bbd7100-ac05-11ea-8423-a22017244fbe.png)

Same thing happens if I disable orientation, highlight reconstruction and white balance but not with sharpen because that auto-applies via a preference.

**Comment by TurboGit** [comment]
@elstoc :IIRC this is by design, you are probably using the "scene referred" mode and so exposure and filmicrgb where auto-applied. But the button is correctly set grey (deactivated) modules.

**Comment by elstoc** [comment]
My general point is that the 'user-optional' modules (sharpen, base curve, exposure, filmic) should be auto-applied at the end of the stack via a preset, meaning that clicking back through the history stack should disable those modules. Either that or (and I don't really prefer this option) all of the 'auto' sections of the history stack should be un-clickable.

Either way there should really be a consistent way to auto apply non-mandatory modules and to remove them with a clean history stack. I used to be able to click on 'original' to be able to see the 'unprocessed' raw (ok including white balance, orientation and highlight reconstruction) and I can't do this any more - 'original' now always includes filmic and exposure. Clicking through the first 10 items in the history stack and not seeing any change (except for sharpen) is really odd and even odder if you start compressing the stack.

Given that white balance (and arguably orientation) are usually required for a viewable image, it makes some sense that this is auto-included in the 'original image', but it should really be possible to disable the rest by clicking through the stack - certainly filmic and exposure.

**Comment by elstoc** [comment]
The other way to do it would be to just switch on the workflow-related modules (and sharpen) in _dev_auto_apply_presets, meaning they would only be auto-re-enabled when clearing the history.
