### ISSUE TITLE
Image asymmetry in crop & rotate

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#5404]
**Images in crop & rotate are slightly off set to the lower right**

When you open crop & rotate to crop an image, you see a thin black border at the upper & left edges only. This is very fine if preview_downsampling=1.0, but quite noticeable at 0.25

**Expected behavior**
Symmetric image with uniform black border (I guess).

This originally relates to #5306  opened by @TurboGit  which has given birth to two PR's to refine the aspect ratio. They removed the bit of grey in between the image and the black border, but neither fixed the asymmetry.

This morning I localised the problem to this code in iop/clipping.c at L2523 (+/-):

  ```
 cairo_set_fill_rule(cr, CAIRO_FILL_RULE_EVEN_ODD);
    cairo_rectangle(cr, g->clip_max_x * wd - upleftborder, g->clip_max_y * ht - upleftborder, 
                    g->clip_max_w * wd + lowrightborder, g->clip_max_h * ht + lowrightborder);  /* *** */
    cairo_rectangle(cr, g->clip_x * wd, g->clip_y * ht, g->clip_w * wd, g->clip_h * ht);
    cairo_fill(cr);
```
In the original code, both `upleftborder` and `lowrightborder` are `1.0f`.

Strangeness: if both are equal, ie to 1.0 or 2.0, the images slides to the lower right, and there is a border of 1 or 2 pixels at the upper left only. But if `upleftborder=1.0f` and `lowrightborder=2.0f`, there is a nice even border.

So can anyone enlighten me as to what is going on here, rather than me doing an uninformed hack? I'm suspecting something about matrix indices mapping into cairo, but I don't understand well enough.

**Comment by jenshannoschwalm** [comment]
I think the intention was to draw an rectangle with 2 pixels width. So if you start drawing it ad x-1/y-1 you should increase width & height by 2 ???

**Comment by GrahamByrnes** [comment]
Looking at the code, it appears to try for 1px all the way around, ie -1 on the top & left, +1 at the bottom & right. But that's not what happens. If I set -2 & +2, it becomes -4 & zero. And it scales with prev_downsample, so it's not really the screen resolution...

I've just proposed a fix in PR #5410... but it's a bit of a blind hack :-(

**Comment by jenshannoschwalm** [comment]
The linewidth of the rect is modified by `cairo_scale(cr, zoom_scale, zoom_scale);`

> it appears to try for 1px all the way around

really? the second rectangle is just inside the first, but the first is slightly too small i think...

Also there might be some cairo clipping defined in cr before calling  gui_post_expose that might make the lines seem smaller on one of the sides.

**Comment by GrahamByrnes** [comment]
Is it about line width or the fill?

My understanding was that in creating the two nested rectangles than using 
`cairo_set_fill_rule(cr, CAIRO_FILL_RULE_EVEN_ODD);`
it was filling the space inbetween, so the line width didn't matter.

**Comment by jenshannoschwalm** [comment]
You are right maybe. I am not sure really. I thought the width of the lines would affect the filled size but the docs are not precise about this and i personally didn't crosscheck. Anyway the flowers are yours :-)

**Comment by GrahamByrnes** [comment]
> I think the intention was to draw an rectangle with 2 pixels width. So if you start drawing it ad x-1/y-1 you should increase width & height by 2 ???

Is that what it's doing?

It uses crop_x * wd, crop_w * wd for the inner rectangle, and crop_x * wd - 1.0, crop_w * wd + 1.0 for the outer. So unless the origin is shifting itself after the first declaration? That would explain it,... except that the inner rectangle is declared after the outer... so no :-(

**Comment by GrahamByrnes** [comment]
> I think the intention was to draw an rectangle with 2 pixels width.

I think this is what led you astray: `crop_w = crop_h = 1, crop_x = crop_y = 0`

So it's actually two rectangles that enclose the entire image, one inside the other.

**Comment by GrahamByrnes** [comment]
Done in #5410
