### ISSUE TITLE
Zoom in shortcut key does not work as intended

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#5406]
Could some one try the default Zoom In (^+) Shortcut key. it does not do any thing. Tested on Windows, Mac and Ubuntu. Zoom out (^-) works as intended

**Comment by elstoc** [comment]
Try remapping it in the preferences window. There have been some fixes in this area recently that might have impacted any manually mapped shortcuts.

**Comment by eyedear** [comment]
I am currently using 3.1.0+2031 remapping to another shortcut works no issue. but the defaults of ^+ does not work in order for the ^+ to work you need to press <CTRL>+<SHIFT>++ then it works on all platform.

**Comment by elstoc** [comment]
For me the default shortcut of CTRL and PLUS actually requires me to press CTRL+SHIFT+PLUS because the shift modifier is required to access the plus character. I've remapped to CTRL+EQUALS which feels more natural for me.

**Comment by eyedear** [comment]
generally all other software such as photoshop, affinity photo, apple photos or any browsers they would show CTRL+PLUS as the shortcut key that would require you to press CTRL+PLUS and not CTRL+SHIFT+PLUS as its now in darktable. which would confuse new users. same goes for the new keymaped to ALT+PLUS which is assign to Zoom Max a new user will try to press ALT+PLUS but that does not zoom max. I think it should be mapped to ALT+EQUALS as much as I hate that

**Comment by elstoc** [comment]
As I've said on another issue, I blame whoever came up with the idiot keyboard layout that has plus requiring a shift modifier but minus not. Problem is that though they are displaying CTRL+PLUS as the shortcut on the other software they're really kidding you because the actual shortcut they're applying is CTRL+EQUALS. I don't have an issue with using CTRL+EQUALS (I've said I use it myself) but we'd have to display it that way in the shortcuts window (which takes its display directly from the actual shortcut mapping) and people would say 'why isn't it CTRL+PLUS'?

**Comment by ptilopteri** [comment]
you must remember that the frequently used number group/pad has a "+" which does not require the <SHIFT> keypress.

**Comment by eyedear** [comment]
I get what you are saying. The thing is the first time I use darktable I just naturally press CTRL+PLUS And CTRL+MINUS to try out the zoom in and out. CTRL-minus works but CTRL-plus does not. So it does not work out of the box. After finding the shortcut list which says CTRL+plus is zoom in my natural instict would be why it does not work. I press the right key but darktable does not react. I might be wrong about this so it would be great if others has an opinion. If it’s change to CTRL+equals the user would still look down on the keyboard and press CTRL+equals which to them is CTRL+plus. This would be good too that means they will know they can assign ctrl+shift+plus to some other thing. Oh ya I tried CTRL+numpadplus it does nothing too. If you assign CTRL+numpadplus it will show as CTRL++ but the shortcut will only work  CTRL+numpadplus. It does not work on CTRL+plus. I know it’s messed up. I do hope more would chime in their opinions.

**Comment by dterrahe** [comment]
> I do hope more would chime in their opinions.

On my keyboard it is very clear that to get a "+" I need to hold shift and press the combined =+ key. So if the shortcut is shown as ctrl-+, I would expect to have to hold ctrl & shift & =+

You may find that on here, often the example of Photoshop will be interpreted as proof of how _not_ to do things. And in this particular case I would not disagree.

> I blame whoever came up with the idiot keyboard layout that has plus requiring a shift modifier but minus not.

This.

Just my opinion, as requested.

**Comment by eyedear** [comment]
anyway its fine with me. I have change to zoom in to = , zoom out  to - , zoom min to _ and zoom max to +. its more logical and to group the zoom controls in one area that can be use when you don't have a mouse. i think very little people use these anyway.  Thanks anyway for the explanation.

**Comment by eyedear** [comment]
anyway its fine with me. I have change to zoom in to = , zoom out  to - , zoom min to _ and zoom max to +. its more logical and to group the zoom controls in one area that can be use when you don't have a mouse. i think very little people use these anyway.
