### ISSUE TITLE
Filmic v4 and exposure auto-applied on old edits

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#5416]
I tried to open old pictures edited with darktable 2.0. No change made, just re-opening old edits in darkroom. Filmic RGB and exposure get auto-applied even with no reset. They should be applied only if the modules are reset or the history is flushed/reset. 

Not sure yet what the best way is, to avoid savage auto-apply without request.

EDIT: that seems to overlap with many users who said, with 3.0, that they had base curve auto-applied by default even when the auto-apply preference was disabled, and we were unable to reproduce. Something fishy is going on in `reload_defaults()`

**Comment by elstoc** [comment]
I'm pretty sure this is to do with how the modules are being auto-applied and is probably resolved by #5414.

**Comment by elstoc** [comment]
@aurelienpierre I suspect this issue can be closed now.

**Comment by elstoc** [comment]
Basecurve probably needs to be changed to use a similar method to create and auto-apply the preset as sharpen and exposure now do.

**Comment by aurelienpierre** [comment]
Ok, fixed with #5414. Thanks @elstoc
