### ISSUE TITLE
performance regression with filmic / perspective correction

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5423]
**Describe the bug**
When FilmicRGB is activated there is a huge performance lost when trying to select the crop with "original format". It is so slow that moving the area is almost impossible.

**To Reproduce**
1. Go to darkroom
2. Activate FilmicRGB (let default settings) 
3. Activate "perspective correction" module
4. Fix perspective
5. Select "original format" in "automatic cropping"
6. Try moving the area

**Expected behavior**
Fast and responsive GUI even when FilmicRGB is activated.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Comment by TurboGit** [comment]
First bad commit is:

```
b24000e6f139d0bb241715f811096c920fbb33bc is the first bad commit
commit b24000e6f139d0bb241715f811096c920fbb33bc
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
Date:   Sun Jun 7 01:50:08 2020 +0200

    auto-enable filmic on scene-referred workflow and adjust defaults

 src/common/image.c  | 18 ++++++++++++++++++
 src/common/image.h  |  2 ++
 src/iop/filmicrgb.c | 33 +++++++++++++++++++++++++++++----
 3 files changed, 49 insertions(+), 4 deletions(-)
```

**Comment by jenshannoschwalm** [comment]
1. I always found the automatic cropping very unreliable - not saying "not working".
2. If i understand the code correctly the correction module tries to do an cpu-expensive approximation using the full pipeline so i guess this make the calculation so much slower.

**Comment by TurboGit** [comment]
But why only when filmicrgb activated ? I have activated the three more CPU intensive modules working on noise and the perspective correction cropping is still responsive.

**Comment by TurboGit** [comment]
I found the culprit, it is the call:

`dt_image_get_exposure_bias(&module->dev->image_storage);`

in reload_defaults().

I suppose we need to cache this value somehow.

**Comment by johnny-bit** [comment]
in `reload_defaults` some other thing might be worked on too, the value of `dt_conf_get_string` is `g_strdup` and needs matching call to `g_free` ;)

and other than this I though that reload_defaults wasn't called constantly during moving of crop frame? if it is so then bunch of modules do heavy lifting in reload_defaults I think...

**Comment by jenshannoschwalm** [comment]
@johnny-bit i also would have suspected string handling to be the performance limiter here.

**Comment by johnny-bit** [comment]
In #4360 I've done strings reads relatively infrequently ;) for exposure bias value caching, the're signal raised on active image change which can re-set that value if needed and would be enough for caching and re-computing stuff, right?

**Comment by TurboGit** [comment]
In fact I was wrong, reload_defauls() is called once anyway.

The issue seems to come from the white point source value, reverting just this part makes the perspective_correction fast (well manageable) again:

```
diff --git a/src/iop/filmicrgb.c b/src/iop/filmicrgb.c
index c7f7be3ba..a54baadc4 100644
--- a/src/iop/filmicrgb.c
+++ b/src/iop/filmicrgb.c
@@ -2475,7 +2475,7 @@ void reload_defaults(dt_iop_module_t *module)
     = (dt_iop_filmicrgb_params_t){
                                  .grey_point_source   = 18.45,  // source grey
                                  .black_point_source  = -8.00f, // source black
-                                 .white_point_source  = 4.00f,  // source white
+                                 .white_point_source  = 5.45f,  // source white
                                  .reconstruct_threshold = -1.0f,
                                  .reconstruct_feather   = 3.0f,
                                  .reconstruct_bloom_vs_details = 100.0f,
```

@aurelienpierre : Any idea about that ? An iterative algo somewhere ? The spline estimator maybe ?

**Comment by aurelienpierre** [comment]
Whaaaaat ? The computation is exactly the same no matter the white value. Could this be linked to the highlights reconstruction ? What happens if you set the highlights threshold to an insanely high value ?

**Comment by TurboGit** [comment]
Ok, setting threshold to 6 and the "perspective correction" is fast again.

Now, the question is how to fix that ?

**Comment by aurelienpierre** [comment]
Ok so the slow-down is due to the reconstruction. I guess it will be fixed with OpenCL, or with disabling reconstruction by default, which may not be safe in general.

**Comment by TurboGit** [comment]
@aurelienpierre @jenshannoschwalm @johnny-bit : see #5430.
