### ISSUE TITLE
[performance] gaussian blur slowdown when tiling

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#5428]
**Describe the bug**

When tiling kicks in, gaussian blur slows down dramatically.  While a little bit of slowdown is to be expected (and is seen with other operations), Shadows and Highlights using gaussian blur with a radius of 100 slows down by a factor of two or more compared to when it runs without tiling.

**To Reproduce**

1. Download the bench.SRW image and .xmp from https://discuss.pixls.us/t/darktable-speed-in-general-and-when-using-two-monitors/12002
2. Run darktable-cli bench.SRW out.jpg --core -d perf -t 2 --conf host_memory_limit=8192
3. Observe the time for shadows and highlights
4. Run darktable-cli bench.SRW out.jpg --core -d perf -t 2 --conf host_memory_limit=512
5. Compare the much slower time for s&h versus the only fractionally longer times for other tiled iops such as demosaic, lens correction, global tonemap, local contrast

**Expected behavior**

There should only be a modest slowdown from tiling, as is the case with most iops.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by rabauke** [comment]
Running the Gaussian blur with large blur radius in tiling-mode is a bad idea. Tiles must overlap. Overlap leads to some computational overhead. The overlap equals the kernel size, which is proportional to the blur radius. 

Therefore, it is to be expected that the Gaussian blur in tiling mode becomes slow when the blur radius is of the order of the tile size.

Parallelizing the two-dimensional Gaussian blur via a tiling approach seems not very reasonable to me. A two-dimensional Gaussian blur is calculated via a one-dimensional blur along each column first followed by a one-dimensional blur along each row. The row/column-wise calculation of the one-dimensional blur operations are inherently independent and can be calculated in parallel.

**Comment by ralfbrown** [comment]
The existing code does already parallelize the row-wise and then the column-wise passes, but the gaussian blur is just a subroutine called by the iop as one of multiple actions.  The problem is that when the iop declares that it needs more memory than is available, the tiling doesn't support multiple passes with specified geometries.

In looking at the code, it is possible to mitigate things by reducing the declared memory requirements.  The blur code uses a full-size temporary buffer, where a buffer holding a single row would suffice with a modest change to the code.  But tiling_callback has to declare the even larger memory requirements (*two* full-size buffers) of the OpenCL code path if that was compiled in.  With some way to figure out whether the specific call about to be made will use CPU or GPU, we could return the smaller value if on CPU and reduce the number of tiles used.
