### ISSUE TITLE
[performance] contrast equalizer slowdown with tiling

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#5429]
When tiling kicks in, contrast equalizer slows down dramatically.  While a little bit of slowdown is to be expected (and is seen with other operations), the contrast equalizer slows down by a factor of three or more compared to when it runs without tiling.

**To Reproduce**

1. Download the bench.SRW image and .xmp from https://discuss.pixls.us/t/darktable-speed-in-general-and-when-using-two-monitors/12002
2. Run darktable-cli bench.SRW out.jpg --core -d perf -t 2 --conf host_memory_limit=8192
3. Observe the time for constrast equalizer
4. Run darktable-cli bench.SRW out.jpg --core -d perf -t 2 --conf host_memory_limit=512
5. Compare the much slower time for c.e. versus the only fractionally longer times for other tiled iops such as demosaic, lens correction, global tonemap, local contrast

**Expected behavior**

There should be only a modest slowdown from tiling, as is the case for most iops.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: git master 3.1.0+2116
 - OS: Linux
 - no OpenCL

**Additional context**

**Comment by rawfiner** [comment]
Problem is, as contrast equalizer has quite a lot of scales, a pixel in the coarsest scale is constructed using lots of pixels of the original image, requiring large tiling overlap.
I don't really know what could be done about that

**Comment by ralfbrown** [comment]
Yeah, tiling overlap might make it impossible to speed up, but I posted these two performance issues as much for an eventual reminder to myself to revisit this as for any other reason.

**Comment by aurelienpierre** [comment]
I don't see the issue here. Tiling is a trick to reduce memory footprint, but it increases computational complexity and messes-up I/O by accessing memory in a non-contiguous way. Slow-down seems normal to me, especially on an heavily I/O-bounded operation.

**Comment by TurboGit** [comment]
Speaking about tiling... What about removing this ? We do not support 32bit OS. All 64bit OS have certainly lot of memory (those days 8Gb is the minimum) so what the point of keeping all the complexity introduced by this tiling support ?

**Comment by aurelienpierre** [comment]
We unofficially support 32 bits since some guys make dt work on Raspberry Pi. I wouldn't invest time into actively maintaining 32 bits support, but it would be a shame to actively destroy it too. I vote for status quo and this one.

**Comment by TurboGit** [comment]
Ok, didn't know it was still supported on 32bit Raspberry Pi. Note that 64bit version of Raspberry Pi exists. But maybe it is too early to remove this support, status quo is fine by me.

**Comment by ralfbrown** [comment]
Don't forget that GPUs typically have rather less RAM than the computer they are in, so there will be more pressure for tiling with OpenCL.  Some of the IOPs use upwards of 128 bytes per pixel for their processing (in addition to the input and output buffers).  Try working on a 100 megapixel image and you'll need more RAM than many people have even today.

Also, tiling can actually result in a speedup -- if the tiles are small enough to fit in L1/L2 cache.  That's what gave the scalability improvement at high thread counts on my final code for denoise(nlmeans) -- processing tiles of 72x60 pixels so that everything runs out of cache and the cores aren't competing against each other for bandwidth to main memory.

**Comment by aurelienpierre** [comment]
You won't be able to have tiles as small as 60px with non-decimated wavelets, that's for sure. It's the whole algo you will need to rewrite, and that will change the output image slightly.

**Comment by ralfbrown** [comment]
Will be mostly fixed by #7485.  For any given amount of available memory, that PR will reduce the impact of tiling simply by using fewer but larger tiles than are possible with the current code.
