### ISSUE TITLE
FR: More Consistent Automatic Modules

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5434]
This Feature Request is to discuss how automatic modules are handled within darktable and how those modules interact with the history stack. The intention is to agree how to handle the different types of automatic modules in a consistent way. It follows on from some of the issues mentioned in #5396

**Forced On Modules**

Certain modules are mandatory and cannot be switched off. For example, for raw files the following are included in this category:

- raw black/white point
- demosaic
- input color profile
- output color profile
- display encoding

These modules can be identified by the fact that ``(module->default_enabled && module->hide_enable_button)`` is TRUE.

**Enabled By Default Modules**

Some modules are highly recommended for the production of a reasonable image and so are always switched on by default. While these modules can be switched off they cannot be removed from the history stack. This is odd and leads to some of the issues mentioned in #5396. For example:

- white balance
- highlight reconstruction
- orientation

Such modules can be identified by the fact that ``(module->default_enabled && !module->hide_enable_button)`` is TRUE.

**Modules Enabled via Preset / Preference**

These are modules that are enabled via a preference setting (scene- or display-referred workflow modules or sharpen) or via an automatically-applied user preset. These modules are only auto-applied when editing a new image or clearing the history stack. They may be manually disabled and removed from the history stack entirely.

**So What's the Problem?**

I've partially resolved some of the issues in #5414. As part of that PR, the history stack initialisation procedure was fixed such that the above categories of module are applied to the history stack in order (with the Forced On modules at the bottom). So this discussion starts with the assumption that you've loaded a fresh image with the history stack applied in that order.

_1. Selecting Auto-Generated Items on the History Stack_

The normal behaviour expected of the history stack is that if you click on a number in the stack, all of the modules referenced below it are applied (switched on) and all of the modules above it are not (switched off). However this is not true of the modules in the first two categories above. For example take the following default history stack:

![Screenshot_2020-06-12_16-38-11](https://user-images.githubusercontent.com/9555491/84520221-20fcd300-accb-11ea-8f9a-4be2ea64d546.png)

If I select any item from 0 to 7 the preview image does not change and the active modules list also does not change. While this makes sense for the 'Forced On' modules (0-5), it really doesn't make sense for the others, since they can be switched off manually. Orientation is a bit of an outlier here as it remains on throughout the whole stack but for some reason (probably because it's auto-set from the image) is added at the end.

_2. Removing Items from the History Stack_

Any module that can be manually switched off should be able to also be removed from the history stack. However, this is not possible for the modules in the second group (Enabled by Default). You can disable them but if you try to remove them from the stack they pop back in (enabled).

**Proposal**

Firstly, it should not be possible to click any of the 'Forced On' modules in the stack, except for either the first or possibly the last one (for the purposes of discarding the stack). They should be forced to the beginning of the stack (even for existing edits if possible) and should not ever move from there. 

Second, the 'Enabled by Default' modules should work the same way as the 'Enabled by Preset/Preference' modules, though by default they should be added to the stack before any preset/preference modules. As with preset/preference modules they should only be forced back onto the stack if the stack is fully discarded (by selecting the last module in the 'forced on' part of the stack and compressing).

**Comment by phweyland** [comment]
I think there is no conflict, just to keep in mind:
Related to the current `history` status, you mention two cases corresponding to the `basic` value: `forced on` and `enabled by default`.

**Comment by elstoc** [comment]
@phweyland I'm not sure I understand what you're saying here.

**Comment by phweyland** [comment]
In collect/history you have 3 cases, basic, auto applied and altered. 
Your suggestion opens 2 sub cases for basic. I don't think we should split also the history cases.
So just for info (and staying coherent).

**Comment by parafin** [comment]
If first modules can't be clicked on history compression mustn't take them into consideration. Meaning these first steps should be unmodifiable and any parameter changes must be a separate history entry even after compression.

**Comment by elstoc** [comment]
@parafin good point. I keep forgetting that while these modules are mandatory that doesn't mean they can't be changed - just that they can't be disabled. 

Perhaps better then to keep the order fixed only when the image is loaded or history discarded as I've done in #5414. To be honest my main problem is that the 'Enabled by Default' modules can't be removed from the history (and that if they're removed and automatically re-added they get prepended to the history instead of added back to the top of the stack, which would seem more natural).

**Comment by elstoc** [comment]
The remainder of the fixes I tried for this caused more issues than they solved and were reverted. I'm not sure this is worth investing more time in so closing for now.
