### ISSUE TITLE
lua lock with darktable cli

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5436]
**Describe the bug**
darktable-cli dead lock since last lua changes 

**To Reproduce**
Compile dt master:
$ cd src/tests/integration
$ darktable-cli images/mire1.cr2 0000-nop/nop.xmp out.png

**Expected behavior**
No lock :)

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian
 - 
 - 

**Additional context**

**Comment by TurboGit** [comment]
@wpferguson : Can you have a look at this ? TIA

**Comment by wpferguson** [comment]
checking...

**Comment by wpferguson** [comment]
It's the darktable.preferences.register.  I'll just wrap the whole function with darktable.configuration.has_gui.  Give me a few minutes...
