### ISSUE TITLE
collection not refreshed when changing tags

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5447]
**Describe the bug**
Removing a tag when the collection is set to display pictures with this tag does not remove the picture from the collection.

**To Reproduce**
1. Go to lighttable
2. Click on collect, select tags
3. Click on a tag to display a collection of pictures with this tag
4. Select one of the picture and detach the corresponding tag
5. See, the picture is still displayed in the collection

**Expected behavior**
As for color labels, I expect the picture to be removed from the collection.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Additional context**

**Comment by johnny-bit** [comment]
This bug was present before changes in #5412 so the only possibility for it to happen is that collection does not listen to tag-changed signal :) should be an easy fix.

**Comment by TurboGit** [comment]
I let you look at this, thanks!

**Comment by johnny-bit** [comment]
Me and my loud mouth... (and here's where #5433 would also come in handy ;) ) tag change is listened to, only change isn't used to apply collection recalculation, just label count recalculation :/ I'm trying to be as uninvasive as possible with change required.
