### ISSUE TITLE
Lighttable thumbnails are not refreshed when history is compressed

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#5455]
1. In lighttable, select an image
3. hover the "changed" icon, note the modules (especially if some are duplicated)
2. click history stack -> compress history
3. hover the "changed" icon, the history stack has not changed in the list.

**Comment by jenshannoschwalm** [comment]
Yes. It comes down to `dt_image_altered` not returning a correct flag.

This comes down to `dt_history_hash_get_status(const int32_t imgid)`.

I played around here and in fact i saw non-updated lists even modules definitely had been changed.

**Comment by TurboGit** [comment]
Maybe just a refresh issue as the history is indeed compressed properly. I suppose that this is another instance of a missing refresh in the new lighttable rewrite. @AlicVB maybe you can have a look at this?

**Comment by TurboGit** [comment]
@AlicVB : I have a proposed fix here #5457
