### ISSUE TITLE
Issue on entering metadata or tag info.

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#5460]
**Describe the bug**
Mouse hovering on images makes lose the focus on metadata and tag entries. The result is always unexpected when one is writing ...

**To Reproduce**
Select an entry in metadata, start writing something.
If the mouse moves and hovers an image the written text disappears and is lost.
Worse, if the mouse move happens unexpectedly and one continues to write, dt executes the action corresponding to the entered shortcuts (instead of writing the text).

**Expected behavior**
As long as another image (EDIT or another field) is not selected (clicked on), there is no reason for losing the current text, and to have the risk to break something.

**Additional context**
darktable 3.1.0+2137~g3b19bdfa2
OS debian 10

**Comment by phweyland** [comment]
@AlicVB, I need your lights ...
it seems to be easy to control the module action when hovering signal while editing, but I don't see what the module (the widget) can do if it loses the focus.
When hovering an image, is there anything which grabs the focus ? If yes, would it be possible to avoid it ?

**Comment by johnny-bit** [comment]
single alphanum keys might not work since those will be grabbed by input field. I don't know if any other usecase would need a re-grab of focus... Now the problem to note is this is intended behaviour or side-effect.

**Comment by phweyland** [comment]
> single alphanum keys might not work since those will be grabbed by input field.

That's the desired behavior indeed when editing a field. Shortcut are deactivated during edition and this working correctly, as long the field keeps the focus. The problem starts when the focus is lost inadvertently.
