### ISSUE TITLE
[denoise (profiled); Y0 U0V0] bug in curve tool

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5466]
**Describe the bug**

when activating wavelets with Y0U0V0, in the curve, I can change Y0 even it is set to color channels U0V0, please see screencast below

Only in the first attempt, when you change more than once between Y0 and U0V0, the bug disappears

@rawfiner am I missing something?

**To Reproduce**

**Expected behavior**

in U0V0 the color curve (orange) should be accessible right away.

**Screencast**
[dt_Y0U0V0_20200614-2020-06-14_12.26.31.mp4.zip](https://github.com/darktable-org/darktable/files/4776250/dt_Y0U0V0_20200614-2020-06-14_12.26.31.mp4.zip)

**Platform (please complete the following information):**
* darktable version : 3.1.0+2144~g198b3e0dc
* OS                : Linux - kernel 5.6.15-gentoo
* Distro            : Gentoo Base System release 2.6
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.82-r3
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.16
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by jade-nl** [comment]
This isn't a general issue and only shows up in special cases.

This issue does not show up the first time you use wavelets on an image. It only shows this behaviour after:

- Select an image and discard history,
- Open it in darkroom view,
- Open and activate (or reset) denoise (profiled),
- Select mode -> wavelets (Y0 tab is selected by default)
- Select the U0V0 tab,
- Turn off and collapse denoise (profiled) module,
- Reset denoise (profiled),
- Open denoise (profiled),
- Select mode -> wavelets:

At this point the U0V0 tab is highlighted and the operation is done on the Y0 tab.

This is only true for this specific image at this time. To show this:

- Leave darkroom,
- Select a different image and open it in darkroom,
- If it isn't still open from the previous session: Open (or reset) denoise (profiled)

The correct (Y0) tab is highlighted for this image.

**Comment by AxelG-DE** [comment]
That means, we have different experiences.

As you can see from my video, I do not need to go such complicated path.

**Comment by jade-nl** [comment]
Your video starts with the image already loaded in darkroom and without us knowing what you might have already done (or not) in that session.

Are you able to get this issue after loading a fresh image in darkroom, turn on denoise and selecting wavelets?

If that is the case: I cannot reproduce your issue that way.

**Comment by rawfiner** [comment]
Thanks for the bug report, I can reproduce. Working on a fix.

**Comment by AxelG-DE** [comment]
I was on the way to create a new video, replying to Jade_NL's suspicious, from beginning with empty history stack...:)
I will be happy to support, just let me know, what is needed.

**Comment by rawfiner** [comment]
Could you check that the bug is fixed also on your side by #5471 please? :-)

**Comment by AxelG-DE** [comment]
Indeed I will. 

Just it will be tomorrow evening, as I will have to be back to office tomorrow

**Comment by jade-nl** [comment]
> Could you check that the bug is fixed [...]

Fixed.

Focus/highlight stays on the correct tab no matter how you approach it.

**Comment by AxelG-DE** [comment]
Sorry for being late. 

I also confirm, it fixed the issue, no more wrong tab hightlighted. or false reactions.

Thank you @rawfiner for the very fast and competent reaction!
