### ISSUE TITLE
Olympus Pen E-PL 10

### ISSUE THREAD

**Issue by schaeferpp** [darktable-org/darktable#5472]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by schaeferpp** [comment]
If I can help supporting this camera by providing more photos, please let me know.

**Comment by LebedevRI** [comment]
Thank you for contribution.
It would be good to have a more bright sample, ideally something closer to daylight landscape.

**Comment by schaeferpp** [comment]
@LebedevRI I just submitted another image. Is this better?

**Comment by LebedevRI** [comment]
Thank you, i think so.

**Comment by schaeferpp** [comment]
I just realized that rawtherapee is already able to process images in this format. I not sure if this information helps in integrating the camera to darktable as well.

**Comment by LebedevRI** [comment]
Sorry for the delay, i should be doing this more proactively :/

**Comment by schaeferpp** [comment]
I'm very grateful for you implementing E-PL10 support at all.
Thank you for your time!
