### ISSUE TITLE
Darktable is unusable with a trackpad.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#5474]
**Describe the bug**
When using a trackpad to scroll in the latest Git master revision, the scrolling moves so fast that it is impossible to use (just a twitch of the finger can change the light table zoom from 1 to 25 or scroll halfway through a large collection of images).
As I recall, this same problem was encountered a few years ago and was resolved by disabling the use of smooth scrolling altogether, treating trackpads the same as regular scroll wheels.

**Platform (please complete the following information):**
 - Darktable Version: master revision 7c22327
 - OS: Fedora 32

**Comment by Nilvus** [comment]
I confirm this behavior, scrolling is really not possible with trackpad. @AlicVB: should this be related to your recent lighttable rework?

**Comment by AlicVB** [comment]
@Nilvus : yes, certainly. Sadly I've no idea what is doing a trackpad different from a mouse... Do you have one ? if yes, we can eventually can do another interactive debugging session if you have time...

**Comment by parafin** [comment]
https://github.com/darktable-org/darktable/blob/7ffecde96a2ae164fc5d60a4cd1c07456ad43f1f/src/gui/gtk.c#L499 - these functions might be of interest.

**Comment by AlicVB** [comment]
yes, I've seen them already... but thanks anyway !

**Comment by Nilvus** [comment]
> @Nilvus : yes, certainly. Sadly I've no idea what is doing a trackpad different from a mouse... Do you have one ? if yes, we can eventually can do another interactive debugging session if you have time...

Yes I have. A debugging session is possible tomorrow evening or thursday one.

**Comment by Nilvus** [comment]
@AlicVB: just a thing I just test. filter collections is really smooth with trackpad. Maybe something to check on that side to compare.

**Comment by MStraeten** [comment]
then i'm glad to be on a macbook - there the trackpad works fine ;) But in fact scrolling in lighttable is very sensitive but also with my mouse or graphic tablet or by dragging the slider

**Comment by Nilvus** [comment]
> then i'm glad to be on a macbook - there the trackpad works fine ;) But in fact scrolling in lighttable is very sensitive but also with my mouse or graphic tablet or by dragging the slider

Hmm, I'm on a Macbook pro (on Linux) and scroll is smooth with my wheel mouse but not with trackpad on lighttable filemanager (or zoomable one) but smooth with wheel mouse AND trackpad on filter collections.

**Comment by nils-werner** [comment]
I still have this problem on an old MacBook Air running Darktable 4.0 under Arch Linux and Gnome 3.
