### ISSUE TITLE
Improve collection sources with grouping

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#5478]
**Is your feature request related to a problem? Please describe.**

It's quite difficult to collect images due to the extremely long list of sources in the lighttable's collect module, especially when the one I use most, "tag" feels like it's arbitrarily placed way down the list in the dropdown.

**Describe the solution you'd like**

Within the past release version or two (I don't remember exactly when), blend modes were grouped and organized. It would be wonderful if the collect module's source dropdown were also grouped and organized.

**Additional context**

Here's what the collect menu currently looks like:
![collect](https://user-images.githubusercontent.com/10246/84665789-8bf31780-af20-11ea-82e3-095d0551a0b5.png)

Here's the blend mode dropdown from the darkroom, serving as an inspiration of what it could be like:
![Screenshot from 2020-06-15 15-36-02](https://user-images.githubusercontent.com/10246/84665873-a75e2280-af20-11ea-8f74-b4841141b043.png)

**Comment by garrett** [comment]
I'd suggest something like this as a starting point:

---

## base

- film roll
- folders
- tag

## time

- date taken
- datetime taken
- import timestamp
- change timestamp
- export timestamp
- print timestamp

## technical

- camera
- lens
- aperture
- exposure
- focal length
- iso
- aspect ratio

## metadata

- title
- description
- creator
- publisher
- rights
- notes
- color label
- geotagging

## darktable

- filename
- version name
- grouping
- local copy
- history
- module
- module order

**Comment by garrett** [comment]
The suggestion above is a quick attempt, where I tried to group items so they're easier to find. They're mainly in the order that they're most likely to be commonly used.

Base could be called something else, but it's basically the typical types of info that someone uses to find images. Tag is included here as it's extremely common to use tags to find images. (Alternatively, it could be at the top of the metadata group and the metadata group could be reodered to be before or after time, I suppose. That would still be better than what we currently have)

Time is self-explanatory. 

Technical is a bunch of camera-assigned metadata referring to the hardware (camera + lens) and how it is used.

Metadata is the metadata that someone actively adds to the images when they're in darktable.

The darktable group is darktable-specific info at the bottom (plus filename, which is kind of an implementation detail in the way darktable is used).

**Comment by Nilvus** [comment]
I do not check carefully your suggestion list but I agree that would be good to have groups now, just as masks. As you say, that will help finding a filter more quickly now the list is quite long.

**Comment by TurboGit** [comment]
I fully agree !

**Comment by Egocentrix** [comment]
I really like this idea! Three remarks/nitpicking:
- 'tag' is a metadata field
- I'm not sure I would call 'file name' a darktable thing. I would put it with 'folder' and 'film roll'. Maybe 'File' would be a good category name for that?
- In the Pixls-thread it was mentioned that 'technical' could maybe be called 'capture details' or 'camera settings'

**Comment by garrett** [comment]
Yeah, it does need some polishing. One of the goals was to try to get tag up near the top — it's a common way to select images (even if it's added metadata). Same for folders and film rolls.

I'm happy with any grouping that makes logical sense and prioritizes the ways most people start collecting images. In my case, it's by tag (as I have tagged my two decades work of photos extensively), but I know a lot of people don't tag as much as I do and instead use dates, "film rolls", or folders (usually sorted by dates and/or "film rolls" anyway). And even if we primarily use one of those, we're often enough using one of those other main methods of narrowing down images anyway.

I've revised my comment above with the grouping, taking @TurboGit's and @Egocentrix's comments into account.

**Comment by Nilvus** [comment]
Much better order and categories now. Personally, I would make capture details before time but that just personal, probably many others would see the opposite, so it's good as it is.

I hope that the implementation would allow to also adjust with CSS to make categories titles as bold. It's unfortunately not possible to do for masks as it is specific bauhaus widget who don't allow that. Having titles visually different help to see categories and visually go quickly to good part.

**Comment by Egocentrix** [comment]
> One of the goals was to try to get tag up near the top — it's a common way to select images (even if it's added metadata). Same for folders and film rolls.

Personally I wouldn't mind not having tag at the top, even though I use it often. I have a preset set up for the collect module, that selects by file name, tag and color label (in 'narrow down' mode, so I can use either of them).

**Comment by TurboGit** [comment]
I'll try to work on that.

**Comment by TurboGit** [comment]
Implemented and merged.
