### ISSUE TITLE
Issue on colorlabels: size change after setting it when changing the view

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5484]
**Describe the bug**
Set a colorlabel on a thumbnail, the size is ok, just move the view to hide related thumbnail. Go back and see how big colorlabels become (and so margins not respected).

Another way to see that is using culling or preview mode: set a colorlabel or more and then go on that view to others images (be sure that image set is no more visible) and go back to those colors.

@AlicVB: sorry for that but probably another one for you. Could this be related to your last PR about margins in overlays? I don't remember that was there before.

**Comment by Nilvus** [comment]
Just some screenshots:

On filemanager, setting color labels (size and margins are good):
![2020-06-15_22-21](https://user-images.githubusercontent.com/45535283/84702425-e1e2b200-af56-11ea-8b78-f1eeef801c9a.png)

Scroll to hide the image then come back (size and margins are not good):
![2020-06-15_22-22](https://user-images.githubusercontent.com/45535283/84702464-f030ce00-af56-11ea-911d-faa32bbfbe8c.png)

In culling (would be same on preview), setting color labels (all is good):
![2020-06-15_22-22_1](https://user-images.githubusercontent.com/45535283/84702485-fc1c9000-af56-11ea-9233-7313a742af21.png)

Change images viewed and come back to show again the image (size and margins are not good):
![2020-06-15_22-23](https://user-images.githubusercontent.com/45535283/84702511-0ccd0600-af57-11ea-89b4-508cba607a9c.png)

**Comment by AlicVB** [comment]
> sorry for that but probably another one for you

ahah I don't trust you. I know that you are laughing in secret :P 

That said, I'll have a look. Thanks for all your tests !
