### ISSUE TITLE
Enable date corrections beyond 100 hours or absolute date entry

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#5485]
**Is your feature request related to a problem? Please describe.**

It seems that the datetime of an image is now stored in the xmp, at least I can find a parameter “exif:DateTimeOriginal”. Now it would make sense to do corrections beyond the 100 hours limit of the geotagging module. My use case would be setting the right date of scanned images/slides/negatives.

**Describe the solution you'd like**

An absolute date entry would be perfect, another solution would be to add an optional year/month field to the correction in the geotagging module, e.g. [+-]?[[[[YY:]dd:]hh:]mm:]ss.

**Alternatives**

Probably it is possible to alter the xmp file directly from lua and force a reimport of the file, but I don't understand the api good enough to judge the feasibility.

I did test manually changing the date string and reimporting, and it seems like it works well.

**Additional context**

Allowing partial dates in the xmp (and entry field) such as “2020-03” would be great for my use case as well, as scanned negatives from the 80's are hard to date exactly to the second they were taken.

**Comment by wpferguson** [comment]
Why not a lua script to change the image timestamp directly in darktable instead?

**Comment by spaceChRiS** [comment]
@wpferguson, thanks for looking into that. Yes, maybe this would be the way to go. What I cannot assess yet is the side effects this will cause, and the last time I checked the lua api, such a task was beyond my skill level, besides not being a programmer such that most programming tasks are beyond my skill level.

Regarding side effects, the interaction with the correction in the geotagging module is not clear. I wonder if the geotagging correction alters the datetime AND adds a correction info, such that the original date can be computed from the xmp,

Another question would be about having incomplete/partial dates. Do you have an idea if this is possible?

**Comment by wpferguson** [comment]
The geotagging module just changes the datetime_taken field for the image
in the database.  The correction info is not computed.  The original
datetime_taken can be pulled from the image itself using exiv2.

As far as setting a datetime with partial information, the field itself is
a character field so that it should be possible to just zero out anything
missing, i.e. 00/00/2015 00:00:00 for an image taken sometime in 20015.

I think I have a script somewhere that I wrote to adjust time, that I could
use to build something.

**Comment by wpferguson** [comment]
I found my adjust_time script.  Let me see if I can hack it into a solution

**Comment by wpferguson** [comment]
@spaceChRiS try this and see if it does what you need.  If you have the lua scripts installed, just unzip this and drop it in the contrib directory.  Require it in your luarc or enable it with script_manager.  It creates an "image time" module in lighttable.
[image_time.zip](https://github.com/darktable-org/darktable/files/4810084/image_time.zip)

**Comment by spaceChRiS** [comment]
Besides the little additions I mentioned in your PR, this is already perfect. The only issue I now have is that there are more and more modules cluttering my lighttable :wink:.

I'll leave the feature request open until the PR is merged. Thank you again so much, this makes things possible I did only dream of some days before.

**Comment by wpferguson** [comment]
@spaceChRiS image_time.lua has been merged, so you can probably close this.  As for too many modules cluttering your llighttable, use script_manager to manage the scripts and only turn it on when you need it, then turn it off when you're done.  It wont go away immediately, but it wont be there the next time you start darktable.
