### ISSUE TITLE
Grain and Soften order

### ISSUE THREAD

**Issue by brigling** [darktable-org/darktable#5488]
Grain and soften are applied to the image in the wrong order. This is my opinion but it just makes so much sense to me that I should be able to use the soften tool to enhance the depth of field and then add grain afterwards to correct the hyper smooth effect of softening.

As it is right now the soften effect completely overrides the grain effect when soften is set to 100% mix. I don't think that is correct.

**To Reproduce**
Add lots of soften effect to the image with mix at 100%

Then add as much grain as you want and see how it has no effect to the image.

_

Darktable version 3.1.0~git98.d9cbb3d08

P.S. Taking a moment to express my utmost gratitude to the incredibly fantastic work of the developers of Darktable. I use it almost every day and I love it to bits!
Thanks.

**Comment by rgo** [comment]
If you want to try the effect of changing the order, you can do it by changing the order of the modules via shift+ctrl+drag module and drop.

You can use it as a workaround.

Reference in documentation: https://darktable.gitlab.io/doc/en/darkroom_concepts.html#pixelpipe

**Comment by aurelienpierre** [comment]
For depth of field reduction (because the depth of field is the sharp area, so you don't increase it by adding blur), you should use the low-pass filter instead. It will solve both of your issues : module order, and it is closer to a physical lens blur (although it's still not exactly that).
