### ISSUE TITLE
Logarithm "base" for basecurve?

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#5491]
**The tonecurve allows a choice of scale for the log version, basecurve does not. Should we add it?**

First, let's be clear: what is called the "base" of the logarithm isn't really.  An exponent can be 2^x, e^x, 3^x, 10^x or any value you want, and the base is 2, e, 3 or 10. The corresponding log_a, a=2, e, 3 etc is the inverse. In all cases, log_a(x) -> -infinity as x->0.

What is called the "base" b appears as in the function as log(x(b-1)+1)/log(b).... if you exponentiate this you get exp((b-1)(x-1)). So it's an ordinary log with a variable scale, which happens to also change the base. If it was exp(log(b) x)... it's neither one nor the other, really.

That said, it's very useful: calculate the derivative at x=0 & x=1 and take their ratio, you get what could be called the acceleration of the mapping: 1/(b+1). So make b big and there is a lot of magnification of the scale at the left (dark) side of the histogram, if b approaches 0, there is none (in the limit with appropriate scaling, it's linear).

So one style proposition:

- Add some comments that the base isn't the base, to avoid future confusion;

and two functional propositions:

- Add the adjustable scale slider to basecurve;
- Extend the scale (currently from 2 - 64) to 0 - 64 and get rid of the linear vs log choice: just label the ends "linear" and "log".

What do you think?

**Comment by TurboGit** [comment]
My thinking was that this is really not needed, but my current thinking is that it is a good idea.

Why I changed my mind ?

Base curve was said to be deprecated, but with the new pixel workflows (scene-referred and display-referred) put in place we have saying clearly that we want to support both workflows. So at this stage I don't see why we should say to users that basecurve is not to be used.

So, I'll classify this as an enhancement request (for the style proposition and the functional part).

**Comment by GrahamByrnes** [comment]
Yes, I think there is a case to be made for a "lightweight" processing option that doesn't get involved in reconstruction when it's not needed.

**Comment by TurboGit** [comment]
Closing as now implemented.
