### ISSUE TITLE
auto-apply per camera basecurve presets don't work

### ISSUE THREAD

**Issue by JacoTux** [darktable-org/darktable#5492]
**the bug :**
when opening new images in the darkroom the base curve is activated although in my preferences in the "processing" tab the checkbox to apply the preset base curve is not activated.
For some time now it seems.

**Platform :**
 - Darktable Version:  3.1.0+2245
 - OS: Manjaro Linux Xfce

**Comment by elstoc** [comment]
What is the 'auto-apply pixel workflow defaults' preference set to?

**Comment by JacoTux** [comment]
Thanks for thinking about it.
The 'auto-apply pixel workflow defaults' preference was set to "display-referred"
Of course he must be on "scene-referred" for filmic
