### ISSUE TITLE
filmic rgb: added noise is distracting when zoomed out

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5493]
Using the 'add noise in highlights' functionality of filmic rgb v4, the added noise is realtively subtle when zoomed in:

![Screenshot_2020-06-16_11-51-30](https://user-images.githubusercontent.com/9555491/84765862-c237a200-afc7-11ea-862e-720ec3696544.png)

But more obvious and distracting when zoomed out:

![Screenshot_2020-06-16_11-50-33](https://user-images.githubusercontent.com/9555491/84765778-a16f4c80-afc7-11ea-8786-0d2c38e562be.png)

Ideally zoomed-out mode should have smaller observable texture than zoomed-in mode (i.e. it should look like you zoomed out!)

**Comment by aurelienpierre** [comment]
That's the joy of scale-dependent filters… Nothing I can do here, except force a 1:1 preview and rescale after the noise is applied, which is going to be slow. Same problem applies to denoising modules too.

**Comment by elstoc** [comment]
I suppose the only thing you could do is disable it when fully zoomed out. I assume that if you forced 1:1 and rescaled the texture probably wouldn't be that noticeable in most scenarios anyway.

**Comment by aurelienpierre** [comment]
It's no better to entirely disable it too, since it will distract the user in the opposite way and might even lead them to exaggerate the noise amount in this view. In addition, what you see in zoomed-out view is true to the export in non-"high quality" mode.

**Comment by aurelienpierre** [comment]
Also, I just thought about it, but noise is additive, so it's not a linear but an affine transform, and `downscale(image + noise) ≠ downscale(image) + downscale(noise)` since 2D interpolations are at least quadratic (even the ill-named bilinear).

**Comment by rawfiner** [comment]
When downsampling at 50%, bilinear interpolation averages 4 pixels, which should divide noise variance by 4.
I think noise variance parameter should be changed according to the scale using that property: even if not perfect, this will probably give more accurate preview

**Comment by aurelienpierre** [comment]
Hmm what about Lanczos and cubic methods ?

**Comment by rawfiner** [comment]
More complicated with Lanczos and cubic, I don't know

**Comment by aurelienpierre** [comment]
That smells like Taylor expansions, 3/8 of something and magic coeffs all along.
