### ISSUE TITLE
Little things broken with #5335

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5499]
@dterrahe: 2 minor issues shown, probably related to your recent PR #5335.

- On contrast module, detail line on both modes have the default pointer (white point below slider) not aligned on the left. By default, should be aligned on the left (to 0%) as other ones.
![2020-06-16_19-30](https://user-images.githubusercontent.com/45535283/84807639-d69b8f00-b007-11ea-9d74-513c6d30aae0.png)

- On filmic rvb, go to look tab. See contrast slider. Before it was set with 3 digits after point, so for example 1.360 instead of 1.36. It's better for that setting as before. But more of that (maybe related), it was possible to increase/decrease by 0.01 only with mouse wheel. Now it increase/decrease by 0.05. Not suitable for that setting. And if using mouse wheel with Ctrl shortcut, it's only possible to increase by 0.01 but not to decrease.

**Expected behavior**

Just as before, default pointer on detail in contrast module aligned on the left of the slider
And for filmic rvb, possibility to increase/decrease by 0.01 directly with mouse wheel and so having 3 digits after point instead of 2.

**Comment by dterrahe** [comment]
Thanks @Nilvus for the detailed comments. It is very easy to tailor stepsizes and number of digits, so I can add these no sweat. Have you gone over all modules you care most about or shall I wait and include these in a slightly bigger patch?

There definitely other cases where the granularity changed. Sometimes I intentionally didn't replicate the original settings because I wanted confirmation that they were really sensible, rather than just copied through without thought from a different setting. The number of digits sometimes looked crazy for example (for the order of magnitude of the parameter).

**Comment by Nilvus** [comment]
> Thanks @Nilvus for the detailed comments. It is very easy to tailor stepsizes and number of digits, so I can add these no sweat. Have you gone over all modules you care most about or shall I wait and include these in a slightly bigger patch?

I have quickly gone over modules I care about the most and don't see by now anything else.

> There definitely other cases where the granularity changed. Sometimes I intentionally didn't replicate the original settings because I wanted confirmation that they were really sensible, rather than just copied through without thought from a different setting. The number of digits sometimes looked crazy for example (for the order of magnitude of the parameter).

Probably. For contrast I rarely use the third digit but that could sometimes help on this slider.

**Another thing:** on local contrast, detail string seems to not be translated anymore. I use french translation and we lost (as you can see on screenshot) accent on the e of the string. I update and check fr.po and no more detail string alone on it.

**Comment by dterrahe** [comment]
There may indeed be some issues with strings being marked for translation at the moment; working on it https://github.com/darktable-org/darktable/pull/5498

Thanks for the careful testing. Much appreciated!

**Comment by hgmarty** [comment]
Hello,

I have compiled tonight the latest master version of the 3.1 2162.
I have keyboard shortcuts to manage the usual modules as color balance with contrast. The shortcuts are reversed with the + key which decreases the contrast and - which increases it. Same behaviour when I have changed with other touches.

On the other hand, on color balance where I am sure but also on the others, it seems that the step of change is higher, I would say multiplied by two. For example, before saturation with one click went from 100 to 100.5 but now to 101.

Thank you.
Have a nice evening.

**Comment by AxelG-DE** [comment]
>     * On filmic rvb, go to look tab. See contrast slider. Before it was set with 3 digits after point, so for example 1.360 instead of 1.36. It's better for that setting as before. But more of that (maybe related), it was possible to increase/decrease by 0.01 only with mouse wheel. Now it increase/decrease by 0.05. Not suitable for that setting. And if using mouse wheel with Ctrl shortcut, it's only possible to increase by 0.01 but not to decrease.

Darned; why did I not find that :cry:

**Comment by TurboGit** [comment]
@dterrahe  : Another little thing (maybe related).

On the shadi module (local contrast), the slider highlights and shadows have wrong increment.

- using scroll gives + or - 50% (it was 1%)
- using shift-scroll gives + or -  more than 200% - don't know it goes from min to max (was 10%)
- using ctrl-scroll gives + or - 10% (it was not working)

On the details slider a ctrl or scroll seems ok, but ctrl-scroll does nothing.

**Comment by TurboGit** [comment]
With #5505 the simple scroll now move the slider by 100%

**Comment by dterrahe** [comment]
@TurboGit you mean bilat? Fixing it now. Easy.

That module is a bit funky because two sets of sliders link to the same params field. So the "sensible" defaults are based on "the other one". Meant to adjust for this (thought I had, sorry).

**Comment by AxelG-DE** [comment]
Actually several modules appear odd when using mouse-wheel (incl color balance, demosaic and others). 

Sorry I did not test this at all, just dragging or typing the numbers to exceed the limits...

**Comment by dterrahe** [comment]
@AxelG-DE please provide specific instances. Not just where different from previous, but where now _bad_. Many thanks. These are easy to fix so I'm collecting a bunch in one PR.

**Comment by Nilvus** [comment]
> Actually several modules appear odd when using mouse-wheel (incl color balance, demosaic and others).

Could you be more precise by what you mean with odd? color balance works as expected (so as before) with mouse-wheel. I mainly use mouse-wheel to set them. I see no issue on those modules.

**Comment by AxelG-DE** [comment]
>Could you be more precise by what you mean with odd?

just one excample, unfortuantely there are more:
- input saturation: normal scroll increments by 1%
- shift-scroll increments by 10%
- ctrl-scroll **no reaction**
(where contrast fulcrum works as expected)

**Comment by TurboGit** [comment]
Fixed, closing.
