### ISSUE TITLE
add. exposure instances should have default bias=off, EV=0 currently it is EV=1

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5502]
**Describe the bug**

We got a little regression through the introspection for exposure

**To Reproduce**

**Expected behavior**

any additional instances of exposure should be bias=off, EV=0 

**Bisect**

```
169bbb36908be2f623bbd0763231fc6e9aba1a1c is the first bad commit
commit 169bbb36908be2f623bbd0763231fc6e9aba1a1c
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Mon Jun 1 10:01:48 2020 +0100

    [exposure.c] introspection, refactoring, janitorial

 src/iop/exposure.c | 282 +++++++++++++++++++----------------------------------
 1 file changed, 100 insertions(+), 182 deletions(-)
```

So @dterrahe I suppose this one is for you :-)

**Comment by elstoc** [comment]
Reverts changes made in #5414

**Comment by elstoc** [comment]
@TurboGit I think similar changes have been reverted in filmicrgb as well. Might be worth spot-checking the whole of that PR

**Comment by TurboGit** [comment]
@elstoc : yes I was expecting glitches like this, the review could not detect such cases. field testing will help detecting and fixing all those issues hopefully. @dterrahe I'm letting you looking at this one. Thanks.

**Comment by dterrahe** [comment]
@elstoc I believe in the exposure module the whole reload_defaults can now be removed, since the code that was dependent on the loaded image and the "scene-referred" setting was already removed pre-merge of #5335 and the defaults are automatically picked up from introspection:
```
  float exposure; // $MIN: -18.0 $MAX: 18.0 $DEFAULT: 0.0
  int compensate_exposure_bias; // $DEFAULT: FALSE
```
Let me know if I'm missing something.

**Comment by elstoc** [comment]
I'll take your word for it. If you've removed it and it works with introspection then I'm happy.

**Comment by dterrahe** [comment]
> I'll take your word for it. If you've removed it and it works with introspection then I'm happy.

Don't do that!! Test!

;-)

**Comment by elstoc** [comment]
Done - feedback on the PR

**Comment by TurboGit** [comment]
Fixed, closing.
