### ISSUE TITLE
Duplicate manager seems to be broken

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#5504]
**Describe the bug**
Duplicate manager seems to be broken since ~2days

**To Reproduce**
Open an image with duplicates in darkroom, removing a duplicate or adding is possible, selecting another makes via double-left-click makes dt hang. Also just pressing left button doesn't show the comparing image any longer. 

**Expected behavior**
As before until ~ 2days.

**Screenshots**

**Platform**
 Darktable Version: 3.1.0 - 2263, Fedora 32, nvidia graphics, opencl does not matter.
 

**Additional context**
Have been testing this 2 days ago to understand the pixel shifting stuff and this worked fine.

**Comment by AlicVB** [comment]
I can't reproduce here, everything seems to work fine...
does switching images with filmstrip still works for you ?

**Comment by elstoc** [comment]
I get the same on 3.1.0+2244~gc167ee8dc

**Comment by jenshannoschwalm** [comment]
Filmstrip is ok

**Comment by jenshannoschwalm** [comment]
> I get the same ...

Same issue or "can't reproduce"?

**Comment by elstoc** [comment]
Same issue. Also just rebuilt and I get the same issue on 3.1.0+2266~g2690129b8

**Comment by jenshannoschwalm** [comment]
fwiw, here seems to hang in ` _lib_duplicate_thumb_press_callback` in `dt_image_get_final_size(dev->image_storage.id, &d->cur_final_width, &d->cur_final_height);` ...

**Comment by AxelG-DE** [comment]
quick-test, cannot reproduce, means it works as normal...

**Comment by elstoc** [comment]
I know some of the recent fixes were around High DPI screens working correctly. I have a standard 1080p monitor. Could that be a contributing factor?

**Comment by Mark-64** [comment]
Confirmed. double clicking on a duplicate results in DT hanging in windows, crash in Ubuntu, with message
```darktable: /home/marco/develop/darktable/src/common/dtpthread.h:268: dt_pthread_rwlock_tryrdlock_with_caller: Assertion `!(res && pthread_equal(rwlock->writer, pthread_self()))' failed.```
