### ISSUE TITLE
Highlight Reconstruction artifacts

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#5509]
**Describe the bug**
Highlight reconstruction in the "reconstruct color" mode results in severe artifacts.

**To Reproduce**
1. Go to any photo that has clipped highlights
2. Click on Highlight reconstruction and "reconstruct color"
3. Observe artifacts. (best seen at 100%)
Every photo I've tested with clipped highlights shows the issue.

**Expected behavior**
I expect no artifacts.

**Screenshots**
[![dt-hl-color.png](https://i.postimg.cc/L40mvQH8/dt-hl-color.png)](https://postimg.cc/s17FgcQk)

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+2267~gfbe79528f
 - OS: arch
 - Yes but artifacts show with it disabled too.
 - Intel NEO lastest version.

**Comment by MStraeten** [comment]
If you expect no artifacts then you should select "recontruct LCh" first. Depending on the clipping channels a reconstruction in color can be impossible. 
If this doesnt help, then you might try to lower the clipping threshold or the raw whitepoint - but then you lose the information of the channel not clipped.

**Comment by aurelienpierre** [comment]
This is a limitation of the algorithm used, not a software problem. There is nothing we can fix in the program that doesn't require to rewrite the maths first and use a different algorithm.
