### ISSUE TITLE
new lighttable keep highlighted thumb in one case

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5511]
**Describe the bug**
Keep a selection when hovering above empty spaces in lighttable and this happens only the first time a collection is opened.

**To Reproduce**
1. Go to lighttable
2. Select a collection that is not too long and so let some empty space into the lighttable thumbtable
3. From collect module move over a picture and hover down in the lighttable until the mouse is above an empty space (no thumb)
4. See error, the last thumb hovered before going to empty space is still highlighted
5. Move back over a thumb
6. Go down to empty space the last thumb is not highlighted

So this issue happens only the first time.

**Expected behavior**
Thumbs should never be highlighted when hovering on empty space.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Additional context**

**Comment by TurboGit** [comment]
@AlicVB : one glitch that has bothered me for some time but I found a reproducer now.

**Comment by AlicVB** [comment]
@TurboGit : just tested, and I fear it's a gtk bug...
Basically we have a container : `thumbtable`, which contains childs : `thumbnails`.
if the mouse leave a child for it's container, gtk should raise an "enter" event for the container (with some special `event->details`)
But, that doesn't works if at first you enter the container directly on a child : without hovering a "blank" area of the container !

I'll have a look at how we can get around this bug... I begin to be tired of all those gtk glitch !
