### ISSUE TITLE
[Bug] darkroom infoline variable $(LABELS_ICONS) is not working properly

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#5523]
Hi !
I was playing with $(LABELS_ICONS) in Darkroom infoline () and I have found a bug with it : i.e. the dots are not in color or even not appearing .

If I place the variable at the end of my info line, I see 2 dotes but they are black (missing color)
![image](https://user-images.githubusercontent.com/3989573/84928749-31e48480-b0cf-11ea-84db-4e96f3c3f7af.png)

In addition, if the variable is placed in the middle of the infoline, I do not even see the (black) dots :+1: 
![image](https://user-images.githubusercontent.com/3989573/84928797-40cb3700-b0cf-11ea-8bce-84fcd3b90f9b.png)

If it helps, here is my infoline code (all the other variable work fine)

`<b>💾 $(FILE_NAME).$(FILE_EXTENSION)</b> • $(MAX_WIDTH) x $(MAX_HEIGHT) • 📅 $(EXIF_DAY)/$(EXIF_MONTH)/$(EXIF_YEAR) - $(EXIF_HOUR):$(EXIF_MINUTES):$(EXIF_SECONDS) • <i>$(DESCRIPTION)</i> • 📷 $(MODEL) + $(LENS) : $(EXIF_EXPOSURE) s • f/$(EXIF_APERTURE) • $(EXIF_ISO) ISO @ $(EXIF_FOCAL_LENGTH) mm • $(RATING_ICONS) • $(LABELS_ICONS) • 🏷️ : $(TAGS) • 🛰️ : $(LATITUDE) $(LONGITUDE) • ⛰️ : $(ELEVATION)m`

dt 3.1.0~git2270.f42aeca9a
Linux Kubuntu 20.04
Intel Core i7 7700K + 32GB RAM + NVidia GFX 1070

Thanks
GLLM

**Comment by AlicVB** [comment]
I don't reproduce with current master.

Some questions : 
1. Are you sure that the image has color labels ? (just in case)
2. does it works in tooltips patterns or overlays patterns ?
3. What is your theme ? Does it change anything with other themes
4. Dos you have Roboto fonts installed ?

**Comment by GLLM** [comment]
hi @AlicVB !
1. yes, I'm sure ... the first and second screenshot were taken on the same pics ... the 1st screenshot appropriately shows 2 bullets ... yet they are black (expected blue & green)
2. I did not initially tested. Here are the results :
* tooltips in lighttable : it works but the bullets are black
![image](https://user-images.githubusercontent.com/3989573/84942932-eab4be80-b0e3-11ea-9c16-e2d0de500db9.png)
 
* overlay on Preview (extended one is used I think) : I see the bullets yet they are black (it work wherever I place the variable in the infoline)
![image](https://user-images.githubusercontent.com/3989573/84943137-38c9c200-b0e4-11ea-8a2d-d8a95c9bee5b.png)
I also see, in preview, that when I stop hovering my pics, the black bullets are still visible, but should not ... not a glitch ... it's repeatable on any pic with color tag that I check in Preview
![image](https://user-images.githubusercontent.com/3989573/84943265-66af0680-b0e4-11ea-9aaa-d8f30b0dd97b.png)

3. My theme is darktable-icons. I just tested with another one : I see the icons in the second case ... but they are also black ... in my usual theme, I now see them !
![image](https://user-images.githubusercontent.com/3989573/84942301-e045f500-b0e2-11ea-9948-c84677d24484.png)

4. I do have Roboto fonts on my Kubuntu 20.04 system
![image](https://user-images.githubusercontent.com/3989573/84942221-c3a9bd00-b0e2-11ea-95be-c94a618dd649.png)

Addendum : as you may see here, @johnny-bit also reproduced... so i'm puzzled ...
https://github.com/darktable-org/darktable/pull/5347#issuecomment-645429164 

Thanks
GLLM

**Comment by johnny-bit** [comment]
I can replicate in very bad way (tm), for testing I set respective default infos line as:
* extended overlay: `$(FILE_NAME).$(FILE_EXTENSION)$(NL)$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH)mm • $(EXIF_ISO) ISO $(SIDECAR_TXT) [$(LABELS_ICONS)]`
tooltip: `<b>$(FILE_NAME).$(FILE_EXTENSION)</b>$(NL)$(EXIF_DAY)/$(EXIF_MONTH)/$(EXIF_YEAR) $(EXIF_HOUR):$(EXIF_MINUTE):$(EXIF_SECOND)$(NL)$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • $(EXIF_ISO) ISO [$(LABELS_ICONS)]`
* infos line: `$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • $(EXIF_ISO) ISO [$(LABELS_ICONS)]`

As you see, image has required colors:
![Zrzut ekranu z 2020-06-17 22-02-07](https://user-images.githubusercontent.com/10687765/84945225-50ef1080-b0e7-11ea-91f6-031ae09c7a09.png)


If interface language is english, everything works flawlessly:
![Zrzut ekranu z 2020-06-17 22-07-51](https://user-images.githubusercontent.com/10687765/84945244-58161e80-b0e7-11ea-920c-1da140e70832.png)

if interface language is polish, the icons aren't even there:
![Zrzut ekranu z 2020-06-17 22-07-18](https://user-images.githubusercontent.com/10687765/84945257-5c423c00-b0e7-11ea-82d3-fe19642b96d3.png)


No change in prefs or dt version between screenshots except for interface language.

**Comment by GLLM** [comment]
FWIW : my OS is in english, the same goes for dt !

**Comment by AxelG-DE** [comment]
maybe it is, when sys-lang and dt-lang are same?

**Comment by johnny-bit** [comment]
> maybe it is, when sys-lang and dt-lang are same?
I checked different languages - no other lang than English works with labels... I need to try and switch lang of OS and how that affects labels.

**Comment by AlicVB** [comment]
That's the key : the language. A stupid copy-paste error in the code.
PR #5540 fix that
Thanks for the report !

**Comment by johnny-bit** [comment]
@GLLM - Can you try instead pasting `<span foreground="#ee0000">⚫ </span>` in your infos line verbatim and see if it works? for me it works very nicelly, I wonder if there's something else since PR#5540 fixes the way problem manifest for me but I don't know if it would be same for you.

**Comment by GLLM** [comment]
Hey @AlicVB, @johnny-bit,

Thanks for taking the time to investigate & try to fix !

I tested in 3.1.0~git2304.9b64fa299, it's still KO ! :-(
* In darkroom and lightable preview : it still see black bullet !
![image](https://user-images.githubusercontent.com/3989573/85059656-51011600-b1a4-11ea-9285-da3b5787f645.png)
![image](https://user-images.githubusercontent.com/3989573/85060033-d71d5c80-b1a4-11ea-841c-279905218709.png)


* Be it in darkroom infoline or in the extended tooltip (in preview), span foreground="#ee0000">⚫ </span> does display a black bullet !
![image](https://user-images.githubusercontent.com/3989573/85059611-33cc4780-b1a4-11ea-9a43-4d5d97f4b6a4.png)
![image](https://user-images.githubusercontent.com/3989573/85059748-6fffa800-b1a4-11ea-934d-007cf68849ad.png)
![image](https://user-images.githubusercontent.com/3989573/85059822-90c7fd80-b1a4-11ea-8238-85d246833244.png)

FWIW : my OS & dt language are both english

Thanks
GLLM

**Comment by AlicVB** [comment]
@GLLM : there's definitely something strange with your install/config. You seems to have colored "font-chars" but when you specifically specify some color, it's not taken in account.
Some question : 
1. what is your theme ?
2. have you Roboto fonts installed ?
3. Does it happen with roboto fonts and a darktable-elegant-* theme ?

**Comment by GLLM** [comment]
@AlicVB 

My dt theme is darktable-icons
![image](https://user-images.githubusercontent.com/3989573/85062367-a8a18080-b1a8-11ea-9e56-16aa30ec32d0.png)

With darktable-elegant-dark, I have the same issue : black bullets !
Even with <span foreground="#ee0000">⚫ </span>

I do have Roboto fonts on my Kubuntu 20.04 system

**Comment by johnny-bit** [comment]
Huh, that mountain directed me somewhere: this seems to be noto-color-emoji font!

wchich means - no color what so freaking ever for that. it's like trying to colour a PNG picture. For that particular nasty hack that is colored emoji, one hast to use emoji color code. 

So...

**Comment by AlicVB** [comment]
>  just to be on the same page, those bullets are supposed to be colored with the color tag's color, right ??

exactly.

Like @johnny-bit I really think that it has something to do with your font. In fact I've never seen a font that "colored" emoji like that. I suppose that in this case the bullet is considered as a black emoji and the markup color is bypassed or something like that.
Do you have the possibility to test with a more "classical" font ?

**Comment by johnny-bit** [comment]
I've tested it and it's naaasty. #5550 is the only way around it IMO, no way to detect if emoji font used will work with span color or will work with utf color... so in case you see "black dots" in place of color labels, use `LABELS_COLORICONS`. Why not simply use `LABELS_COLORICONS`? well, if your emojifont is BW and uses dithering/werido effect it looks NASTY :)

so it's a workaround for those using color emoji fonts, which include noto-color-emoji, twemoji-color-font & probably others

**Comment by AxelG-DE** [comment]
Just for completeness (late as always) #5540 fixed it for me (but I am on roboto)

**Comment by johnny-bit** [comment]
So... ultimatelly it falls to - use `LABELS_ICONS` if you don't have color emoji font or use `LABELS_COLORICONS` if you have one.

**Comment by GLLM** [comment]
Indeed, I use Noto font in my Kubuntu 20.04
![image](https://user-images.githubusercontent.com/3989573/85069229-10a99400-b1b4-11ea-8aa9-9cadacfbbe6d.png)

Changed all system font to Roboto, it didn't change anything ... I need to log out and log back into plasma just in case ... which is a no-go atm.

**Comment by johnny-bit** [comment]
Well, it won't help. For some reason emoji fonts "take over" some ranges of UTF characters and changing fonts mean nothing. ultimatelly you can unistall color emoji but that brings bad experience with emoji overall (unless you like symbola bw emoji)

**Comment by GLLM** [comment]
Mmmmhhh, I see.
I'll change my fonts back to what I had set up. Thanks

**Comment by johnny-bit** [comment]
try now and share you screenshot! :)

**Comment by GLLM** [comment]
It's working fine now with the fix !
![image](https://user-images.githubusercontent.com/3989573/85116618-e55b8f00-b21d-11ea-978f-38c0a2acfa12.png)

Thanks all for your help !
GLLM

**Comment by aurelienpierre** [comment]
And now darktable looks like a teenage Instagram account \o/[/not_helping]

**Comment by GLLM** [comment]
@aurelienpierre : you mean my (GLLM) infoline does so ;)
