### ISSUE TITLE
Shortcuts in color balance

### ISSUE THREAD

**Issue by hgmarty** [darktable-org/darktable#5524]
Hello,

I have assigned the touch of keyboard : 

* b to contrast \- (color balance)
* n to contrast \+ (same module)

And since last day and now (I have compiled the last version 2290), the shortcuts are inversed. When I pressed b, it increases the contrast and if n, it decreases the contrast. 

Thank you

I put alias @dterrahe. Nicoauffray told me, and now I'm a newbie to know that..

**Comment by Nilvus** [comment]
@hgmarty: nicoauffray is my nickname only for darktable.fr. Here I'm known as @Nilvus!

@dterrahe, this seems to be related to your last introspection work.

I would add that step on exposure sliders had also change. Default step was 0.02, now it's 0.10. 0.02 was better for fine-tuning quickly exposure. Or at worst, 0.05 would be better than 0.10.

**Comment by dterrahe** [comment]
I'm testing the solution for side effects. Will try to get ready tomorrow.

**Comment by hgmarty** [comment]
In the same spirit of slider :

in color balance

* saturation (input and output). Default step is 0.5 and now is 1
* for contrast pivot and contrast, it's the same

Thank you @dterrahe 

Sorry @Nilvus for once, I hadn't mixed up and game over for me

**Comment by dterrahe** [comment]
Regarding step size, the default now is 1/100th of max(-min,max). For mouse users, fine tuning adjustments can be achieved by holding the ctrl key while scrolling. Unfortunately that modifier is not supported for (dynamic) shortcut keys.

@TurboGit started an initial discussion about standardising  step sizes. It might be good to include this in the general review of the input layer.

**Comment by Nilvus** [comment]
> Regarding step size, the default now is 1/100th of max(-min,max). For mouse users, fine tuning adjustments can be achieved by holding the ctrl key while scrolling. Unfortunately that modifier is not supported for (dynamic) shortcut keys.
> 
> @TurboGit started an initial discussion about standardising step sizes. It might be good to include this in the general review of the input layer.

Why not. I know and use often Ctrl key but sometimes it's faster to not have too high step. Anyway, where's that initial discussion from @TurboGit and where to include this in general review? Didn't find it.

**Comment by TurboGit** [comment]
@Nilvus : it was here:
https://github.com/darktable-org/darktable/pull/5506#issuecomment-645190579

**Comment by Nilvus** [comment]
> @Nilvus : it was here:
> [#5506 (comment)](https://github.com/darktable-org/darktable/pull/5506#issuecomment-645190579)

Thanks. Anyway, I would really see at least a default 0.05 step with mouse wheel on exposure main slider and not the new one 0.10.
