### ISSUE TITLE
Lighttable (file manager) mode → Scrolling by keys

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#5535]
Linux x64, master snapshot:

It looks that scrolling by up and down keys was broken recently (no more than couple days). To reproduce it just click on random image in file manager mode and try using up/down keys to scroll. It does nothing.

**Comment by elstoc** [comment]
I think this might be related to #5468. I find that if I click on a metadata editor field (say, title), then click on a thumbnail in the file manager, and then use the arrow keys, the keyboard focus returns to a different field (in this case, publisher) in the metadata editor.

**Comment by elstoc** [comment]
In ``thumbtable.c`` replacing ``gtk_window_set_focus(GTK_WINDOW(dt_ui_main_window(darktable.gui->ui)), NULL);`` with ``gtk_widget_grab_focus(dt_ui_center(darktable.gui->ui))`` seems to resolve the specific issue described here.

**Comment by elstoc** [comment]
I'll submit a PR to resolve

**Comment by elstoc** [comment]
#5537 resolves the additional issue (where the metadata entry fields don't lose focus when you collapse the module or expand another)
