### ISSUE TITLE
Inconsistent use of "show mask" in GUI

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#5542]
The icon show mask is displayed in different ways across the GUI

1) In blend gui
OFF ![blend_off](https://user-images.githubusercontent.com/43290988/85022940-534b7c00-b174-11ea-85f2-14c7b61c20a5.JPG) ![blend_on](https://user-images.githubusercontent.com/43290988/85022945-56466c80-b174-11ea-811a-67ae04d1a77a.JPG) ON

2) in tone equalizer and filmic rgb
OFF ![toneq_off](https://user-images.githubusercontent.com/43290988/85023052-7ece6680-b174-11ea-83cc-05c24657b7f5.JPG) ![toneq_on](https://user-images.githubusercontent.com/43290988/85023066-81c95700-b174-11ea-8c06-308b62f6d2c9.JPG) ON

3) in color zones and retouch
OFF ![cz_off](https://user-images.githubusercontent.com/43290988/85023138-a02f5280-b174-11ea-9550-c37569fed5fe.JPG) ![cz_on](https://user-images.githubusercontent.com/43290988/85023143-a291ac80-b174-11ea-9d20-f93a99ab66e5.JPG) ON

This is also because in 1) and 2) is used `dt_bauhaus_combobox_new()` , while in 3) `dtgtk_togglebutton_new()`.
`dtgtk_togglebutton_new()` is the one we should use IMO, and it's also the one which is themable and respond to mouse hover.

By the way, also the cairo icon does not allow transparency and should be changed. This is to me the correct version, which is included in #5497 
OFF ![retouch_off](https://user-images.githubusercontent.com/43290988/85024170-05d00e80-b176-11ea-9623-a6424b76c7b9.JPG) ![retouch_on](https://user-images.githubusercontent.com/43290988/85024176-08326880-b176-11ea-86ad-a9f8e4c32683.JPG) ON

**Comment by aurelienpierre** [comment]
Not sure if it's inconsistent, Tone EQ and filmic show a grey mask.

**Comment by Mark-64** [comment]
A mask is a mask, the color shown is just a representation, the user can also change it, I guess

**Comment by aurelienpierre** [comment]
Yes but the yellow icon comes from the original masking color, which was yellow, but can now be whatever.

Also, the reason `dtgtk_togglebutton_new()` is not used is we can't associate a text label to the button. `dt_bauhaus_combobox_new()` + `qquad_add` is a hack to get both.

**Comment by Nilvus** [comment]
Removing yellow color make sense. Just a thing remaining for me anyway, icons mask with dt_bauhaus_combobox doesn't allow hover effect. The hover effect is a good signal to see something to do there. That makes buttons "dynamic" and not "static" but I understand the goal to needed text. So if hover effect is not possible in that case, we could do that way.

**Comment by aurelienpierre** [comment]
Hover effect should be handled by adding a Gtk state flag on the qquad icon, in `bauhaus.c`, on `mouse_move` event.

**Comment by Nilvus** [comment]
> Hover effect should be handled by adding a Gtk state flag on the qquad icon, in `bauhaus.c`, on `mouse_move` event.

So, would be good to add that. That will make those buttons better and consistent between them.

**Comment by Mark-64** [comment]
Can't 
`dt_bauhaus_combobox_new()` + `qquad_add` 
be replaced by 
`gtk_label_new()` + `dtgtk_togglebutton_new()`
?

**Comment by aurelienpierre** [comment]
No, you would need to define a Gtk grid to put them on the same line, in different columns, because otherwise Gtk will put one widget per line. But then, aligning the Gtk columns to match the qquad width, taking into account CSS rules, font size and DPI scaling, will be a nightmare and consistency will not be ensured.

So, in all that clusterfuck, nasty hack is the least painful path.
