### ISSUE TITLE
historical style different between light table and dark room

### ISSUE THREAD

**Issue by LViatour** [darktable-org/darktable#5551]
**Describe the bug**

I created a style based on an online tutorial to Boris Hajdukovic here:
https://www.youtube.com/watch?v=-fXO3Bo2NOA

Here is the link to download the style:
http://luc.lucnix.be/Jardin-DRC.dtstyle

The particularity of the style is that it uses several instances of local contrast.

If I apply the style via the light table by keyboard shortcut or by clicking on apply the style no problem.

If I am in the darkroom, if I apply the style via a keyboard shortcut or by clicking on the style, the style does not work correctly, in the history parameters certain settings are doubled

**To Reproduce**

**Expected behavior**

activate the style via a keyboard shortcut in the light table or in the dark room must have the same result and the same history

**Platform (please complete the following information):**
 - Darktable Version: 
3.1.0~git2304.9b64fa299]
 - OS: 
Linux Ubuntu 20.04
 - 
Yes
 - 
Nvidia drive 440

**Comment by Cobert0** [comment]
@dterrahe
when apply a style on with several "local contrast" module in darkroom, duplication of these modules are in history and process.
(only on original picture)
It seems since commit 0576a4cbcd5e74b37531eac458451829e495d03d refactoring bilat.c 
no more dt_dev_add_history_item?

**Comment by dterrahe** [comment]
> It seems since commit [0576a4c](https://github.com/darktable-org/darktable/commit/0576a4cbcd5e74b37531eac458451829e495d03d) refactoring bilat.c
> no more dt_dev_add_history_item?

dt_dev_add_history_item is now called in process_changed_value in src/develop/imageop_gui.c for each slider/combo change, so there should be no change in behavior from before with that commit.

@LViatour is this a "recent" bug? i.e. do you think it was introduced by the commit referred to by @Cobert0 or did it exist before (for example; did it already exist in 3.0.2)?

**Comment by LViatour** [comment]
@dterrahe,
a few days before my report there was no bug, but I don't know how to be more precise.

**Comment by dterrahe** [comment]
This happens when applying a style with multiple instances of bilat for the first time after entering darkroom. Initially I had trouble reproducing, because starting with an image with multiple instances, removing them and then reapplying the style does not trigger this bug. You have to leave and reenter darkroom first.
