### ISSUE TITLE
Missing Nikon lens model

### ISSUE THREAD

**Issue by karvox** [darktable-org/darktable#5554]
Darktable doesn't find **Nikon AF-S DX Nikkor 55-200mm f/4-5.6G ED VR II** lens. On **Lens correction** module just only exists **Nikkor 55-200mm f/4-5.6G DX ED** without VR II in database.

**Examples**

![lens1](https://user-images.githubusercontent.com/7475131/85100349-51b2a000-b1d6-11ea-9a94-368767f832d4.jpg)
![lens2](https://user-images.githubusercontent.com/7475131/85100350-524b3680-b1d6-11ea-9dc3-73d002b17154.jpg)

**Comment by johnny-bit** [comment]
have you tried https://github.com/darktable-org/darktable#why-is-my-lens-not-detectedcorrected-in-darkroom- ?

Actually I checked https://wilson.bronger.org/lensfun_coverage.html and it lacks your lens, so best bet for you would be to follow https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction and ultimatelly https://pixls.us/articles/create-lens-calibration-data-for-lensfun/ 

This is in no way darktable bug :)

**Comment by karvox** [comment]
Thanks.
