### ISSUE TITLE
filmic v4: default pixelpipe order introduces possibility of unwanted color noise

### ISSUE THREAD

**Issue by mtvoid** [darktable-org/darktable#5555]
**Describe the bug**
If the input image to the filmic module is desaturated, with the "add noise in highlights" feature of filmic v4 enabled, color noise is reintroduced in the highlights of an otherwise monochrome image. This will happen if desaturation is achieved using modules like "color balance" or "channel mixer", which are applied before filmic in the default module order. Using modules applied after filmic in the default order like "monochrome" or "color zones" to desaturate the image will not produce this issue. This perhaps is not exactly a bug in filmic, but a result of the default module order, which can lead to an unwanted side effect of filmic introducing color noise when processing black & white images. A workaround is to customize the module order to ensure that desaturation is applied after the filmic module.

**To Reproduce**
Using the color balance module, set output saturation to 0 % to make the image monochrome. Enable filmic, ensuring that there are image areas containing strong highlight data. To better see the effect, increase the value for "add noise in highlights" in the options tab. The result will be an image desaturated everywhere except the highlights, which will show color noise.

**Expected behavior**
The image should contain only luma noise, not chroma noise, if there is no chroma noise in the underlying image. 

**Platform:**
 - Darktable Version: 3.1.0 master branch
 - OS: Ubuntu 20.04

**Comment by elstoc** [comment]
what happens if you move the grey/colorful details slider all the way to the left (in the reconstruct tab)?

**Comment by aurelienpierre** [comment]
2 options here:
- increase the number of high-quality reconstruction iterations, in option tabs,
- desaturate the image, in filmic look tab

**Comment by mtvoid** [comment]
> what happens if you move the grey/colorful details slider all the way to the left (in the reconstruct tab)?

Moving it to the left side does seem to eliminate the color noise, yes. But the initial source of the random color noise is definitely the "add noise in highlights" feature. If that is set to 0, then the highlight reconstruction settings maintain the monochromaticity of the image, and do not reintroduce color into a black and white input image.
