### ISSUE TITLE
Severe issue when setting GUI controls and text DPI

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5557]
**Describe the bug**
GUI controls and text DPI main issue as UI become unreadable with just a little setting (to 1) and applied without restart in a way but not when revert back. @aurelienpierre: this one for you!

**To Reproduce**
1. Go to 'preferences window'
2. Set 1 setting in GUI controls and text DPI issue
3. Close preferences window
4. See screenshot below that setting is applied (without restart) and that window is just not readable (hard to reset setting ; fortunately, - button remains visible to go back to -1.0)
5. But as setting 1 to that field is applied directly after closing preferences window, set back to -1.0 is not and need restart (as tooltip explain).

My default OS font size used is 11px on Gnome and lodpi screen

**Screenshots**

![2020-06-19_11-05](https://user-images.githubusercontent.com/45535283/85115950-d45e4e00-b21c-11ea-809f-17fc374ba672.jpg)

**Comment by aurelienpierre** [comment]
DPI settings should usually be in the 72-320 range, with default to 96 DPI. Your screenshot shows that the setting is correctly applied, it's the setting itself that is faulty. Not sure if the program should take over user setting. 

It's a kind of Airbus vs. Boeing situation (Boeing having autopilot superseding manual flight commands, Airbus having manual flight commands superseding autopilot).

**Comment by parafin** [comment]
Maybe sane-check that font size will be bigger than 1 pixel with specified settings and don't apply them otherwise?

**Comment by aurelienpierre** [comment]
Sanity check should ensure font size is bigger than `some legible value`. Problem is I have no clue what legible is on every OS.

**Comment by Nilvus** [comment]
I know that, that's just to show that some limits needs to be set. I've just tested that by applying, like a newbie, what is describe on tooltip. It's just say that increase setting to have magnificent UI. so no way for a default user to know that. Some security needed here (at worst tooltip describing the range to set, probably same for GUI thumbs too). And of course, limit range directly on field would be better.

**Comment by aurelienpierre** [comment]
But then -1.0 is a valid input too.
