### ISSUE TITLE
Crop & Rotate: Bottom border moves when resizing

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5558]
When resizing a crop by dragging on any of the top handles (top, top-left, top-right) the bottom border of the image also moves up fractionally. This doesn't happen when dragging on the left, right, bottom, bottom-left or bottom-right handles. Edit: this only happens when I have an aspect ratio set (not when using freehand).

Also, perhaps related (?), very occasionally the crop and rotate module seems to get into a state where merely moving the mouse over the box (without holding any buttons down) causes the crop box to slowly move upwards. The set of circumstances required to reproduce this are seemingly random though.

3.1.0+2325~gd10cb25c3 on ArchLinux with and without openCL

**Comment by elstoc** [comment]
Magic crop-box movement when moving the mouse is illustrated in the attached video. It seems that once I've found the right crop size it happens consistently. Could it be some sort of rounding error?

[issue5558.zip](https://github.com/darktable-org/darktable/files/4805173/issue5558.zip)

**Comment by AxelG-DE** [comment]
I reproduce, see Screencast, attached
[dt_spooky-Magic_20200619-2020-06-19_17.00.37.mp4.zip](https://github.com/darktable-org/darktable/files/4805260/dt_spooky-Magic_20200619-2020-06-19_17.00.37.mp4.zip)

**Comment by AxelG-DE** [comment]
I bisected the bottom-line move up thingie...
```
aac258ae28db0b8b9bc14a29d206186b7133be96 is the first bad commit
commit aac258ae28db0b8b9bc14a29d206186b7133be96
Author: GrahamByrnes <58031430+GrahamByrnes@users.noreply.github.com>
Date:   Tue Jun 9 22:33:39 2020 +0200

    Allows more precise aspect ratios in crop & rotate

 src/iop/clipping.c | 33 +++++++++++++++++++++++++--------
 1 file changed, 25 insertions(+), 8 deletions(-)
```

@GrahamByrnes could you do us a favour to also look into this? :)

**Comment by GrahamByrnes** [comment]
Ooh, look at that... lol. Ok, will go have a look.
Can I just say in advance "What a fcckn nightmare" to save me saying it later?
Ta.

**Comment by elstoc** [comment]
Confirmed. Both issues are present in https://github.com/darktable-org/darktable/commit/aac258ae28db0b8b9bc14a29d206186b7133be96 but not in https://github.com/darktable-org/darktable/commit/a79a1feb157870a5f5b85bb21d67d211338b1210 (the prior commit)

**Comment by elstoc** [comment]
> Can I just say in advance "What a fcckn nightmare"

I feel your pain. Crop&rotate is a nightmare.

**Comment by GrahamByrnes** [comment]
I'm running something else at the moment, so could you tell me: does this happen when "original image" is set? Or does it have to be one of the other ratios?

**Comment by elstoc** [comment]
Yes. Also happens with original image as the aspect ratio.

**Comment by elstoc** [comment]
Although I'm not sure about using ``!g_strcmp0(text,"original image")`` don't you need to explicitly check it's ``== 0``?

**Comment by elstoc** [comment]
I can definitely reproduce the 'bottom moving when cropping the top' issue on original image but the 'magic movement' issue only seems to happen with other ratios

**Comment by GrahamByrnes** [comment]
Could be... but I don't understand why it should be different. Which doesn't mean a lot :-)

For the moment I haven't found the magic choice of numbers and hand waving, so this could be complicated.

According to GLib,
```
Returns
an integer less than, equal to, or greater than zero, if str1 is <, == or > than str2 .
```
So the only real issue would be if it was comparing two NULL pointers... which is impossible since one is an explicit string.

**Comment by elstoc** [comment]
Sorry I deleted my previous comment as on reflection I think your code for that comparison is fine.

**Comment by GrahamByrnes** [comment]
It's kind of weird, since the only part of the code I thought to have modified was for the exact image case. That's where the exact aspect ratio is imported. For the others it should behave like the old code... except it doesn't :-(

**Comment by elstoc** [comment]
I also get some odd crop ratios in the combobox occasionally

![Screenshot_2020-06-19_17-16-49](https://user-images.githubusercontent.com/9555491/85155552-cb876f80-b250-11ea-99a8-d2529608e818.png)

Don't forget this code has been tweaked a couple of times since that PR so the effects might be subtly different now (when I was testing I had to tweak the image size to reproduce the 'magic' bug after your subsequent correction PR)

**Comment by GrahamByrnes** [comment]
There certainly could be an issue with rounding: the whole point was to fix an issue where the rounded ratio of the downsampled preview image was at least a pixel or two off from the image to be pasted in. So the idea was that for "original image" you should be able to select the original image.

Oh, just saw your latest... hmmm.

**Comment by elstoc** [comment]
> PS what preview_downsampling are you using?

"original"

**Comment by GrahamByrnes** [comment]
I can get the "bottom edge moving" thing... although you can just pull it back down.

**Comment by GrahamByrnes** [comment]
Got shut out :-(

I'm wondering about those MAX(ceiling(....) ,0) changes, which were really aimed at fixing a preceding problem... since the guts of my changes don't apply when a ratio other than "original" is selected...

**Comment by elstoc** [comment]
Yes that's about all that's left really isn't it.

**Comment by GrahamByrnes** [comment]
That's it.

**Comment by elstoc** [comment]
Thanks I'll test it soon

**Comment by AxelG-DE** [comment]
can be closed, I guess?

**Comment by elstoc** [comment]
Yes. Thanks all.
