### ISSUE TITLE
Retouch & Spot removal → No access to controls

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#5560]
Linux, 64 bit, current master:

Steps to reproduce: Move to the right bottom part of the image in darkroom mode and try using spot removal or retouch tools. Place mouse pointer in a way so "+" goes beyond right corner of the image and click. See attached image (red line is way you should place mouse pointer).

![retouch and spot removal](https://user-images.githubusercontent.com/65483426/85122686-a3d3df80-b22f-11ea-8f68-b4edb089b7c8.png)

Problem: Now this control is not available to user, always try placing "+" control in image area.

**Comment by elstoc** [comment]
ctrl+scroll allows you to zoom out further and access any control points placed outside of the image boundaries.

**Comment by timur-davletshin** [comment]
@elstoc but usability... just try placing that "+" in image area whenever it is possible.

**Comment by elstoc** [comment]
The better workflow IMO is to place the + (source area) yourself before you place the target shape using shift+click. Better that you do it than darktable try to be clever (because it will probably get it wrong).

**Comment by johnny-bit** [comment]
The best (IMO) workaround for this would be implementation of FR #6307
