### ISSUE TITLE
$(EXIF_EXPOSURE) and exported file name

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#5561]
**Describe the bug**
$(EXIF_EXPOSURE) is giving me 0,0.TIF when exported to TIF. It should be 1/1600.TIF instead.

`/$(FILE_FOLDER)/Darktable/$(FILE_NAME)-ISO$(EXIF_ISO)-f$(EXIF_APERTURE)-Shutterspeed$(EXIF_EXPOSURE) `
gives me:
IMG_4132-ISO100-f4,0-Shutterspeed0,0.tif

In darkroom it works as it should.

**To Reproduce**
https://discuss.pixls.us/t/darktable-exported-file-name/18839/

**Screenshots**
![darktable-exposure](https://user-images.githubusercontent.com/34200649/85123379-75063b00-b228-11ea-8469-6e54283b201d.jpg)

**Platform (please complete the following information):**
 - 3.1.0~git1960.9499f8eec
 - Ubuntu 18.04
 - OpenCL activated and not activated

**Comment by aurelienpierre** [comment]
Having `/` in file name is forbidden since it encodes a directory path.

**Comment by TurboGit** [comment]
You may want to try:

`..-Shutterspeed$(EXIF_EXPOSURE/\//_)`

**Comment by TurboGit** [comment]
See for full description of variables replacement:
https://darktable.gitlab.io/doc/en/export_selected.html

**Comment by jade-nl** [comment]
..... ore represent it in decimal form in this case?

It, EXIF_EXPOSURE, is shown in the list when constructing a filename, I would expect dt to be able to convert 1/125 as 0.008

Could still a bit messy with the dot but it could be a way around the forwrd slash.

**Comment by TurboGit** [comment]
> ..... or represent it in decimal form in this case?

Won't be very clear having 0.04 or 0.0015625 :)

**Comment by jade-nl** [comment]
@TurboGit : I fully agree with that sentiment.

But the variable is in the list of, legitimate, filename building blocks. Either remove it from that list or do the unclear" thing :-)

**Comment by TurboGit** [comment]
> Either remove it from that list or do the "unclear" thing :-)

Don't understand, what should be done ? It is legitimate to display 1/640, this cannot be used for filename and so I have propose the pattern that will work in this context.

**Comment by jade-nl** [comment]
> [...] so I have propose the pattern that will work in this context.
Proposed as in: Users need to do this themself  or as in the developers are going to change the entry in the list that is shown? Ie: $(EXIF_EXPOSURE/\//_) vs $(EXIF_EXPOSURE)

I assume you meant the first, but the second would be the better solution.

How many users would realize that certain characters are special for their specific OS and need to be changed and if they realize this how many of those know about the substitution command you mention earlier.

**Comment by TurboGit** [comment]
Not sure maybe there is a way to get the context at the time the variable is created and know if it is for an export job or not... The issue here is really change / to whatever else only when this is needed.

**Comment by AlicVB** [comment]
> Not sure maybe there is a way to get the context at the time the variable is created and know if it is for an export job or not...

yes there is. It's already used for some other variable which have special chars, etc... So if I understand well, we need to replace / by _ in case of export job, right ?

I can take care if you want.

**Comment by TurboGit** [comment]
@AlicVB : Yes, replacing / by _ is one solution.

**Comment by jade-nl** [comment]
@AlicVB : That sounds like a very acceptable solution.

**Comment by AlicVB** [comment]
I've just read the code, and that's "by design". See here : https://github.com/darktable-org/darktable/blob/e585d29bab2f6937f012a6bde90fe74ddcef7322/src/common/variables.c#L209
In case of an export job, we use the floating point notation, to avoid the problematic / char

So it's normal that the substitution doesn't work !

**Comment by PeterWem** [comment]
Thanks!
