### ISSUE TITLE
Group Deleteng RAW+JPEG warns about 2 files but deletes only 1 file per time.

### ISSUE THREAD

**Issue by XAndrey** [darktable-org/darktable#5564]
**Describe the bug**
I need to delete a group of paired files: raw+jpg at one click. And when i click delete i see warning: you about delete **2** files? I answer "Yes". And darktable deletes only raw. Jpg isn't deleted. So i must hit "delete" another time. I get message "You about delete 1 file" - "Yes" - and only here i get deleted 2 files.

**To Reproduce**
1. Go to 'lighttable' with raw's and jpg's
2. Click on 'set Group mode "On"'
3. Select a raw file grouped with jpg file.
4. Click selected image[s] - delete

**Expected behavior**
I see a warning about "deleteng 2 files" - click "Yes" - and have deleted **both** raw and jpg files. Not only raw!

**Screenshots**
![1](https://user-images.githubusercontent.com/20306883/85125956-332fc180-b235-11ea-8335-5017a700d71f.jpg)
![2](https://user-images.githubusercontent.com/20306883/85125960-3460ee80-b235-11ea-9a5c-ec03cc065e36.jpg)
![3](https://user-images.githubusercontent.com/20306883/85125966-362ab200-b235-11ea-948a-274658eecacf.jpg)
![4](https://user-images.githubusercontent.com/20306883/85125975-388d0c00-b235-11ea-85a5-f6c84881bc2d.jpg)
![5](https://user-images.githubusercontent.com/20306883/85125982-39be3900-b235-11ea-88ac-638d60169537.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Windows 7, Linux mint 19.2 with Darktable 3.0.1
 - OpenCL activated
 - Which graphics card and driver version - NVidia GTX 1050

**Additional context**
 - Can you reproduce with another Darktable version? - Yes, it was in 2.6.x, 3.0.1
 - Can you reproduce with a RAW or Jpeg or both? - the issue in both files as a pair
 - Did you compile Darktable yourself? If so which compiler was used, with what options? - no, downloaded from offsite exe.
 - Is the issue still present using an empty/new config-dir - yes, always

**Comment by RawConvert** [comment]
Maybe related to #4558 and #5895.

**Comment by Solarer** [comment]
Since I don't shoot JPEG+RAW I cannot test if the problem occurs only if the filetype is different. But when I group 2 RAW images with different filename, I can delete the whole group in one go. 

Can someone try to reproduce with RAW+JPEG pictures? I am on ```3.5.0+1967~g4024d7d73```.
@XAndrey  Maybe this has been fixed since 3.0.1
