### ISSUE TITLE
hard to select the right group size in lighttable 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5565]
**Is your feature request related to a problem? Please describe.**

I found it hard to find the proper group sizes for the thumbs in the lighttable.

In the following picture we have the actual size (here size 1):

![image](https://user-images.githubusercontent.com/467069/85137326-4a74ac00-b241-11ea-8e25-5deca6c3addd.png)

But we do not know where we are in the actual group.

**Describe the solution you'd like**

What I'd like is to display in parentheses after the size (above 1) the actual thumb side on the lighttable. From there it is possible to see the sizes where it makes sense to have only information when flying over or permanent and actually setup the groups in the preference.

Today the only solution is to do that by trial errors and is cumbersome.

**Comment by TurboGit** [comment]
@AlicVB : what's your take on this one ?

**Comment by AlicVB** [comment]
yes, why not. That won't solve all the problems but it'll be difficult to show the actual size and the size range in a clear and concise way...

I'll have a look.
