### ISSUE TITLE
"Import Image" window crashes and freezes darktable.

### ISSUE THREAD

**Issue by JacoTux** [darktable-org/darktable#5571]
the bug
When trying to import image under Manjaro Linux and dt 3.1.0+2331 the "Import Image" window crashes and freezes darktable.
I downgraded dt to the 3.1.0+2309 release to get back to normal behavior.

**Comment by phweyland** [comment]
I've tried to reproduce on 3.1.0+2331~g26a903a65. without xmp, with xmp and with modified xmp. The 3 cases work for me on debian 10.
Could you share a bit more information ? Settings ? ...

**Comment by JacoTux** [comment]
It is when importing a new image, so without xmp.
The import window is transparent.
![Capture d’écran_2020-06-20_01-12-42](https://user-images.githubusercontent.com/65790625/85185339-e0392700-b293-11ea-8af6-1ae76dace2c8.png)

**Comment by phweyland** [comment]
I see you have different cameras. Is it the same scenario with each camera ?
For me it works with nef and cr2 files.

**Comment by johnny-bit** [comment]
Can you try running darktable with `-d all`? also - once it hangs, can you do `killall -SIGSEGV darktable` to generate detailed backtrace? Is problem related only to specifix fujifilm files?

**Comment by JacoTux** [comment]
> I see you have different cameras. Is it the same scenario with each camera ?
It's not a file extension problem. I can't join any directory or files.
This morning with dt 3.1.0+2336 at first use the window "import image" was not transparent.
But no tree structure and visible files.
![Capture d’écran_2020-06-20_12-56-34](https://user-images.githubusercontent.com/65790625/85200339-e9a7ab00-b2f6-11ea-981f-a9ca4d6e22b1.png)

**Comment by JacoTux** [comment]
I can't find the backtrace /tmp/darktable_bt_X9GFM0.txt ! ! !
I got this at the end of the "darktable-d all" process.
`an error occurred while trying to execute gdb. please check if gdb is installed on your system.
backtrace written to /tmp/darktable_bt_X9GFM0.txt
Erreur de segmentation (core dumped)
`
I've got to go.
I'll try again later.

**Comment by JacoTux** [comment]
I had a missing dependency for gdb.
It's okay. I was able to generate the backtrace file.
[https://pastebin.com/m2CPM4qe](url)

**Comment by JacoTux** [comment]
Arhhhhh.

I also keep a copy of my ~/.config/darktable/ from time to time by going back to a previous version, everything works fine.
Currently with 3.1.0+2340~gcfb884133

So my problem was local... nothing to do with a dt bug.
