### ISSUE TITLE
hue2rgb and friends do weird stuff

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#5579]
**Maybe a bug... **

The code makes no sense to me, but I'm not really sure what these functions are supposed to do, so...

There is a function `hue2rgb`  called by `hsl2rgb`  at lines 1091 - 1191 of `common/colorspaces.c`.

The particular issue is this, at the start of  `hue2rgb`:

```
if(hue < 0.0)
    hue += 1.0;
 else if(hue > 1.0)
    hue -= 1.0;
```
So this has a saw-tooth non-monotonic response to input... it is somewhat protected by the CLIP command in channelmixer.c, except that has a typo which is being preserved for historical reasons, so it can in principle receive values between -4 and +5 (I think).

This may be related to #5578...

**Comment by ralfbrown** [comment]
The H in HSL/HSV space is circular, and often expressed in degrees (like an angle); here 1.0 clearly represents 360 degrees.  Since it's circular, 361 degrees is the same as 1 degree.  That code is constraining things to 0-360 degrees, provided you're within -360 to +720.

**Comment by GrahamByrnes** [comment]
Oh, yes, of course I (ahem) knew that. Just forgot for a bit.
Hence @aurelienpierre's proposal to do stuff with Euler angles.

Which raises the question of how the three sliders map rgb to hue? I need to go look.
Might as well close this, thanks for help :-)
