### ISSUE TITLE
TIFF import → Warnings

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#5580]
Export any image to TIFF and import it back to dt. See console output with lots of "[tiff_open] warning: TIFFReadDirectory: Unknown field with tag XXXXX (0xXXXX) encountered".

**Comment by jade-nl** [comment]
These warnings have been around for a long time. I checked all stable version as far back as 2.6.3 and the latest development version and they all show the same behaviour:

- TIFF's exported from darktable, either 8,16 or 32 bit, show these messages when imported back into darktable.
- TIFF's created by GIMP or XnView do  _not_ show these messages when imported into darktable.

I only tried with GIMP and XnView to convert into TIFF so I'm not 100% sure if dt is the sole culprit.

**Comment by jenshannoschwalm** [comment]
Dt exports tags not implemented in libtiff.

Don't think it's an issue.

**Comment by johnny-bit** [comment]
PR #7350 fixes the issue, Please test the PR if you can!

**Comment by jade-nl** [comment]
> PR #7350 fixes the issue, Please test the PR if you can!

Nope, not fixed.

Tiffs created with darktable still show these messages and tiffs that are not created by darktable do not show these messages.

I did try creating a new tiff via darktable: Same result (Actually I got one extra error: 

_[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "Copyright" does not end in null byte_

**Comment by johnny-bit** [comment]
Yeah, the PR isn't merged ;) that's why I said "please test the PR" :wink:

**Comment by jade-nl** [comment]
Merged your branch, build and ran it: This is fixed on my side.

Thanks!

**Comment by johnny-bit** [comment]
PLZ comment on PR too! :)
