### ISSUE TITLE
Random tooltips position display

### ISSUE THREAD

**Issue by sergei18500** [darktable-org/darktable#5586]
Random tooltips position display.
Hello,
This is my first post, so bear with me, thank you...

**Describe the bug**

Since I've been using darktable (about 1 year) I've always noticed 'random' tooltip displays.
I haven't found any post that relates these behaviors so either I'm the only one or ????

**To Reproduce**

1) often enough, the tooltip is not displayed. You have to 'exit' the mouse pointer from the area (or icon) that should display the tooltip and come back to it.

I don't know how to reproduce it systematically.

2) the positioning of the tooltip is 'random'.
To reproduce this second problem :

ex1)
go into the darkroom,
display all modules,
position yourself on the colorize module (for example), look at the position of the tooltip.
go back and forth from top to bottom on the neighbouring modules ( above, below )
look at the very variable tooltip position which seems to be related to the previously displayed module tooltip position !!!!

ex2)
It is the same if you move on the zones 'of the 3 small lines' allowing to create (or choose a preset) or create a new instance. This phenomenon occurs when you move from a module with the 2 options to a module which has only the preset option. ( the tooltip is shifted ).

Ex3)
still in the darkroom:
Go to the icon 'display only active modules', the tooltip appears.
Move over the icon on the right, the tooltip appears.
(I mean move without the mouse getting out of the 'gray band' of icons)
Move again to the next icon, and the tooltip will appear 'base module' completely shifted to the left, at the beginning of the previous tooltip.

These explanations help to highlight erratic displays of the tooltips that I couldn't explain.
It's more of an 'aesthetic' problem than anything else, if a developer goes through that.

Translated from French with www.DeepL.com/Translator 

**Platform (please complete the following information):**

UBUNTU 20.04 - master 3.1.0 git2338 (I regularly upload to the opensuse.org repository.)

**Comment by parafin** [comment]
Sounds like a GTK issue, so upstream bug IMHO.

**Comment by Nilvus** [comment]
It's not a darktable issue but yes a GTK one. This has already discussed recently on that issue: #5382 and only workaround (quite partial) found was to add a shortcut to enable/disable tooltips (Shift+t).

So, unfortunately, think about closing this one.

**Comment by sergei18500** [comment]
Thank you for the information. I'll follow up on the issue #5382.
