### ISSUE TITLE
Thumbnail images not showing in lighttable

### ISSUE THREAD

**Issue by Travellerr-1** [darktable-org/darktable#5593]
a. To be clear, I am a complete noob with darktable, so if this is something apalling obvious please forgive me.
b. My problem: in lighttable mode the thumbnail display and sometimes the main display are blank gray. I cannot see the images. Any suggestions? tia.
![screenshot- 2020-06-21 at 18 53 24](https://user-images.githubusercontent.com/67227344/85224292-64ee8700-b3f3-11ea-8133-095ddb6385d1.jpg)

**Comment by hatsunearu** [comment]
Look at "collect images"--are you sure you didn't narrow down the search too much? Try pressing the inverted triangle in the "time" row and clearing it. You set a time based filter, and if you haven't taken and imported anything in 2020 October (which I just realize now hasn't happened yet lol), nothing will show up and that is normal. 

You probably triggered it by accidentally dragging on the time bar graph in the lower left.

**Comment by Nilvus** [comment]
@TurboGit or @aurelienpierre: to be closed as it's not an issue and help is done.

**Comment by TurboGit** [comment]
Closing!
