### ISSUE TITLE
In lighttable "selected images" feature like "remove" applied to a single image only when in culling view

### ISSUE THREAD

**Issue by james-h-dt** [darktable-org/darktable#5594]
**Describe the bug**

In lighttable, "selected images" feature like "remove" are applied to a single image only, rather than the selected images set. Is seen in culling view and not seen in filemanager view.

**To Reproduce**

1. Rename ~/.config/darktable folder
2. Use Import & import a folder of images
3. In lighttable, select culling view
4. Adjust culling slider to show 1 image 
5. Use mouse to shift-select 3 images from filmstrip view. Note header shows "3 images of [x] in current colection is selected"
6. Open "selected images" panel.
7. Try applying a feature from selected images, e.g. Images > remove (or  Metadata > Copy, then Paste.)
8. Feature is applied to 1 of the selected images.

**Expected behavior**

1. With Images > remove, a dialogue pops up saying "Do you really want to remove 3 image from the collection?"
2. The selected 3 images are removed.

**NB**: This is similar to how Light Room works, so would be helpful for people migrating from Light Room

**Actual behaviour**
1. With Images > remove, a dialogue pops up saying "Do you really want to remove 1 image from the collection?"
2. Only 1 of the selected 3 images are removed.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2 
 - OS: Ubuntu 18.04 
 - No OpenCL 
 - Graphics: Integrated Intel 

**Additional context**

- Bug discussed via dt IRC with AxelG & confirmed against current master branch.

**Comment by Nilvus** [comment]
I don't see as a bug. Culling mode is also a compare modes. I often use to compare a set of images (so selected ones sometimes) to check which images I kept or not. Culling mode is not a mode to set a lot of images, that has always been the case. So really not a bug. A feature request at worst.

As you say, that doesn't appear on file manager, because what you want is the purpose of filemanager, not culling mode.

And last but not least, darktable IS NOT Lightroom and will not be a clone of Lightroom. They don't have same philosophy and don't have to. Switching from a software to another is mainly a personal choice.

**Comment by Nilvus** [comment]
> I don't see that as a bug. Culling mode is also a compare modes. I often use to compare a set of images (so selected ones sometimes) to check which images I kept or not. Culling mode is not a mode to set a lot of images, that has always been the case. So really not a bug. A feature request at worst.
> 
> As you say, that doesn't appear on file manager, because what you want is the purpose of filemanager, not culling mode.
> 
> And last but not least, darktable IS NOT Lightroom and will not be a clone of Lightroom. They don't have same philosophy and don't have to. Switching from a software to another is mainly a personal choice.

**Comment by Nilvus** [comment]
@AlicVB: your view on that?

**Comment by james-h-dt** [comment]
Yes, I also use culling mode to check which images I'd like to keep. I often use 1-image culling view as a quick way to check if an image is sharp enough to keep. Or if the following sequence of images are worth keeping. 

An example use case would be something like:

- I am culling a set of images
- I am in 1-image view (as I'm checking for sharpness)
- I decide the current image plus its following sequence are not worth keeping
- I try to quickly select the sequence & remove.

Current dt behaviour would slow the workflow. 

The default behaviour had me scratching my head for some time. It is somewhat counter-intuitive for a novice darktable user like myself.

(BTW - My comment re. Light Room was not intended to suggest darktable should be a LR clone. It was intended to support take-up of darktable by new users, who might otherwise be discouraged.)

**Comment by AlicVB** [comment]
that's done on purpose.
In culling mode (same applied for full preview) the main use case of selection is to limit the images to browse. So we can't do what you want.

Now I've a good news for you : you can do exactly what you want by showing and using the filmstrip !

**Comment by james-h-dt** [comment]
There may be a misunderstanding. I am using filmstrip:

5. Use mouse to shift-select 3 images **from filmstrip view**. Note header shows "3 images of [x] in current colection is selected"

**Comment by Nilvus** [comment]
> Yes, I also use culling mode to check which images I'd like to keep. I often use 1-image culling view as a quick way to check if an image is sharp enough to keep. Or if the following sequence of images are worth keeping.

Why using culling for just one image? Preview mode (with alt+w for persistent preview, w for quick preview) is made for that.

> Current dt behaviour would slow the workflow.

If you don't know, like any software, the way to use it, you're right. But I can guarantee that if you use the good mode with the good way (same with other software like Lightroom), it's just the opposite.

> The default behaviour had me scratching my head for some time. It is somewhat counter-intuitive for a novice darktable user like myself.

On what you describe, it's just because you don't use it the good way (1 image in culling is for me not a good way for example).

> (BTW - My comment re. Light Room was not intended to suggest darktable should be a LR clone. It was intended to support take-up of darktable by new users, who might otherwise be discouraged.)

I had understand that. Anyway, anyone switching to a software than another need to learn some new things and lost some habits to adapt them to the new software. So, as I said, darktable doesn't follow Lightroom (and never be I hope).

**Comment by Nilvus** [comment]
> There may be a misunderstanding. I am using filmstrip:
> 
>     1. Use mouse to shift-select 3 images **from filmstrip view**. Note header shows "3 images of [x] in current colection is selected"

There's no misunderstanding (and I can talk for @AlicVB here) as it's possible to do what you want on filmstrip. Just be sure to be on filmstrip part in the bottom and not on culling part to do what you want. You could also hide/show filmstrip as you want (Ctrl+f) as panels (too many shortcuts to describe them). The purpose of using culling for just act on images, one image at the time, and use filmstrip for a set of selected images is simply that this is in reality more powerful as it allow the possibility to quickly switching between act on one image or more selected ones.

So, the only thing I see and this is normal for a novice darktable user like yourself, is you just need to learn new way to do, those implemented in darktable. You could read (or read again) darktable 3.0 article in darktable.org blog, that describe some things about that.

**Comment by AlicVB** [comment]
Maybe you use the button in the left panel to remove images. In this case, you're right, this won't work, as dt can't consider that you are in the filmstrip, but in culling.
So you have to put your pointer on the selection inside the filmstrip and use the shortcut key to do what you want.

But, as said by @Nilvus I really think that full preview will be more adapted to your workflow : 
You browse your images with filmemanager, make your selection here, which will be easier than with the tiny filmstrip, then you show the full preview of one of your image, exit the full preview and do what you want (keep or reject)

**Comment by AxelG-DE** [comment]
I vote for blocking view=1 when in culling mode, should switch to view=2, as I also agree, view=1 in culling is somehow against the culling philosophy

**Comment by TurboGit** [comment]
Indeed forcing >= 2 images in culling mode seems the way to go.

**Comment by james-h-dt** [comment]
AlicV - I wasn't using the left panel button. I was using the buttons inside "selected images" module in the right panel, after selecting multiple images in filmstrip. This works fine in other modes & is only a problem in culling mode. 

AlicV - You mention using shortcut keys while the mouse pointer is hovering inside filmstrip view. I'll take a look at this. If this works, then it is a handy workaround. As a user I also suggest this is somewhat obscure and counter-intuitive. Darktable has a good UI which is generally pretty intuitive & does not rely on keyboard shortcuts, which is great for bringing new people in.  

I see AxelG has commented; for info, AxelG & I were chatting about this over IRC. AxelG kindly reproduced the problem in master branch & suggested I post the problem here.  

With the comments re. blocking view=1 in culling view; this would certainly avoid the problem I've raised. However, it would also break the useful use case of wanting to step through large-as-practical images, while still selecting multiple images from the filmstrip for bulk operation.

**Comment by AxelG-DE** [comment]
>AxelG kindly reproduced the problem in master branch & suggested I post the problem here.

I also told you right away, that view=1 is against logic of culling. 

Culling is for culling only. All other file management thingies, file manager to be used :-) 

@AlicVB funny thing is, when view is e.g. 3, you actually can do, what james-h wants, even on more and wider spread pics than that current selection

**Comment by Nilvus** [comment]
> AlicV - I wasn't using the left panel button. I was using the buttons inside "selected images" module in the right panel, after selecting multiple images in filmstrip. This works fine in other modes & is only a problem in culling mode.

He of course means right panel. And again, it's not the purpose of culling mode.

> I see AxelG has commented; for info, AxelG & I were chatting about this over IRC. AxelG kindly reproduced the problem in master branch & suggested I post the problem here.

Anyway, it's not a problem as it is intended. 

> With the comments re. blocking view=1 in culling view; this would certainly avoid the problem I've raised. However, it would also break the useful use case of wanting to step through large-as-practical images, while still selecting multiple images from the filmstrip for bulk operation.

Preview is right away for that. You could even hide or show panels around (like in culling view), so by hidding them you could have what you want there.

It's possible to do powerfully and quickly all you want. You just need to change (and learn) some little things and you will love darktable way there.

Last things, many many things could be done with mouse or shortcuts. But like in many software, some things could be more powerful and fast by learning and using some shortcuts. An shortcut help is possible by simply press 'h' key (or Alt+h for persistent view). Content of this help is dynamically updated to the current view.
