### ISSUE TITLE
lossing current edited picture in darkrrom when flying over the filmstrip

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5598]
With the end of the lock-down here in France I had restarted doing some pictures and so edited some pictures instead of testing all PR :) Fact is that this put you in another perspective... And I found an annoying feature, even a regression compared to previous version.

**Describe the bug**
Lossing current edited picture in darkrrom when flying over the filmstrip.

**To Reproduce**
1. Go to darkrroom
2. See that the current edited picture is highlighted in the filmstrip, fine.
3. Move to filmstrip, the highlighted picture is the one under the mouse, fine too.
4. But the currently edited picture is not highlighted.

**Expected behavior**
We really need to see the current edited picture as this is the only way to copy some edit from another picture and pasting into the current edit.

And no, sometimes it is difficult to see the current edit when the filmstrip contains a series of similar pictures (burst shooting or picture taken with different speed or aperture).

How this could be done ?
1. Either always keep current edited picture highlighted
2. Have some specific color in around the thumb
3. Make it highlighted but with a different color
4. Instead of a plain grey background have some stripes on it

I'm leaning toward 3, but maybe a better solution could be found.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Comment by TurboGit** [comment]
@AlicVB : Probably for you, let me know what you think about this. TIA.

**Comment by TurboGit** [comment]
Forget one important information, the difficulty to see the currently edited picture is when there is a selection in the filmstrip as the selected and the currently edited thumb have all the same background color.

**Comment by AlicVB** [comment]
@Nilvus : this one is for you :-P

In fact, there's already something to distinguish the image : it's represented by a small border around the image in the thumbnail. So maybe we need to show it more obviously.
So I think it's css only (play with `#thumb_main:active` I think)

**Comment by Nilvus** [comment]
@AlicVB and @TurboGit: yes, I'm already on. Reading that, I was quite sure it's CSS related and just check indeed that exactly active state which is broken.

So is one of you could assign this to me instead of @AlicVB. Will fix that tonight, should be quick.

**Comment by TurboGit** [comment]
@Nilvus : Thanks, assigned to you.

@AlicVB : Thanks for the quick reply.
