### ISSUE TITLE
FR: Allow middle mouse button click on filmstrip

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#5601]
In darkroom one can use the filmstrip at the bottom to change pictures. When selecting a picture by clicking on it, the strip moves to put that picture in the center, if needed. Therefore I find it most convenient to keep my mouse in the center and use the scroll wheel to move the strip, so that when I click, the strip doesn't need to move/jump.

However, clicking with the middle button/scroll wheel doesn't do anything, so I need to keep moving my finger between the middle and the left mouse button.

It would be convenient if on the filmstrip the middle mouse button would act the same way as the left mouse button.

I've tried to figure out where the middle button gets ignored, but it doesn't seem to be in thumbnail.c::_event_main_release ...

**Comment by AlicVB** [comment]
if you want to try, I think you need to adapt `event->button == 1` in `thumbtable.c:955`

**Comment by dterrahe** [comment]
That's it. Changing that to event->button <= 2 achieves the effect I'm after.

I believe middle-button click isn't assigned to anything at the moment, so this would be a harmless change unless we want to reserve it for something else in future. But I can't think of any other logical function. Except maybe expand/collapse group? Or is that already under something else?

**Comment by AlicVB** [comment]
no, it's not used for anything else in thumbtable. It's just used in culling for quick zoom.

Maybe you can limit the scope to this change to filmstrip only, so it can be used in the future for something else, esp. in zoomable ?

Can I let you do the PR ?

**Comment by dterrahe** [comment]
I changed my mind on this. Let's keep it available for possible future use.
