### ISSUE TITLE
FR: In collection provide a way to require exact string match

### ISSUE THREAD

**Issue by dterrahe** [darktable-org/darktable#5602]
In the collection module, it seems that a rule/search on a string field is always interpreted as a _substring_ search. It would be useful to have a way to force an exact match on a string field, for example by entering the value in square brackets or by adding a "$" (end-of-line) character behind it. And this should then be the default if an item is selected from the list of available values for a field, which also would help making this feature discoverable for manual input too.

At one point I had a Sony A7 (officially "Sony ILCE-7") and then later upgraded to an A7II ("Sony ILCE-7M2"). When I select the "camera" field in the collection module, both cameras show up in the list with the correct number of pictures available. When I click on the _7M2_ item, I indeed get the correct selection. But when I click on the A7, I get a selection that contains both, because the starting substring is identical. I don't think there is currently a way to narrow the selection to an exact match.

If this functionality already exists, then this would turn into a change request for the documentation of the collection module.

**Comment by GrahamByrnes** [comment]
I wondered about this at a certain stage with regard to auto-apply in basecurve. The issue I'd imagine is if many people know the "official" name of their camera: looking down the list, there were several versions of names for different Pentax.

Otoh, those people are less likely to be using special search strings...

**Comment by dterrahe** [comment]
I think in preset auto-apply an exact match is required but you can specify wildcards (%).

In collection, there is an implicit wildcard at the end. Which makes sense if you manually start to type in the text box, so I'm not suggesting to remove that option. But it should be possible somehow to require an exact match. And then that should be requested when I click on a particular item in the list.

**Comment by hatsunearu** [comment]
I think I can get this feature working; it feels intuitive to me that when I double click the options I see under "camera", it should select that and only that.
I'm thinking stuff encased in quotes should count as an exact text search. Does that sound right to you too?
I'm not sure what should happen if you search:
> "ILCE-7"
Should it match with "Sony ILCE-7"? Technically it shouldn't, but maybe not. Maybe make it semi-intelligent like being space (0x20) aware? Or should this feature be activated primarily by double clicking the collections options, automatically copy-pasting the correct string.

Not sure how to handle cases where someone types:
> "Sony ILCE-7" foobar
how should foobar be handled? I think if you had comma-separated quote lists it should do an OR of those terms too.

**Comment by dterrahe** [comment]
Thanks for looking at this!

If OR functionality (via comma) were to be added, it should work for all fields.

Brackets [] are used for date ranges  and I guess could also be used for string ranges (but not as useful).

So using quotes to give exact match would make sense. To be useful, "ILCE-7" should match nothing, because otherwise I'll have the same substring problem I have now. Only "Sony ILCE-7" should match an A7 and "Sony ILCE-7M2" the A7II.

And yes, doubling clicking a string item should put its full text in the search box enclosed by quotes.

**Comment by hatsunearu** [comment]
> And yes, doubling clicking a string item should put its full text in the search box enclosed by quotes.

Great, I will start work tomorrow :D 

>If OR functionality (via comma) were to be added, it should work for all fields.

What do you mean all fields? Do you mean everywhere where filtering is used?

**Comment by dterrahe** [comment]
> > And yes, doubling clicking a string item should put its full text in the search box enclosed by quotes.
> 
> Great, I will start work tomorrow :D

Don't misinterpret me as having any authority! I only have an opinion. You might want to get buy-in from @TurboGit and others before you start.
 
> > If OR functionality (via comma) were to be added, it should work for all fields.
> 
> What do you mean all fields? Do you mean everywhere where filtering is used?

I mean all fields that are available in the collection module. Not just strings, also values and dates. Which is probably what you meant anyway? But I wanted to clarify since this FR is only about strings.

And then, if OR is supported, it should work with multi-select in the list (i.e. selecting more than one item by holding CTRL); clicking on items A, C and F in the list should put A, C, F in the search box. Or "A", "C", "F" in case of strings.

And I guess a range select in the list (using shift) should put [A,F] in the search box.

But now you'd be building a full SQL query tool...

BTW I'm just noticing that the item lists sometimes already allow multi-select (all number and date fields (?), for example focal length) but I don't notice any effect if you select more than one item. It doesn't work for string fields.

**Comment by hatsunearu** [comment]
> BTW I'm just noticing that the item lists sometimes already allow multi-select (all number and date fields (?), for example focal length) but I don't notice any effect if you select more than one item. It doesn't work for string fields.

Whack. Hopefully that means there is some common code I can shuffle around.

> I mean all fields that are available in the collection module. Not just strings, also values and dates. Which is probably what you meant anyway? But I wanted to clarify since this FR is only about strings.

Gotcha, though the UI might be a liiiitle difficult... I'll see what I can do. Also I definitely don't feel like creating a really comprehensive SQL tool lol

Also, I'm worried that the quote mark will interfere with legitimate uses of the quote mark, for instance what happens if there is a lens that has a quote mark in its name? I haven't heard of any but if anyone knows one, let me know. My guess is that some lenses might show its focal length/diameter/whatever in inches or something...

**Comment by dterrahe** [comment]
> Also, I'm worried that the quote mark will interfere with legitimate uses of the quote mark, for instance what happens if there is a lens that has a quote mark in its name? I haven't heard of any but if anyone knows one, let me know. My guess is that some lenses might show its focal length/diameter/whatever in inches or something...

So now you have to support the escape character: \" is a real quote.

But I think focal length etc are numeric values, not strings?

**Comment by hatsunearu** [comment]
Well, lens names are usually strings AFAIK. And those might have some weird name like foobarnon 5" f/2.8 or something.

I should sleep, but I'll figure something out. Probably escape strings.

**Comment by ptilopteri** [comment]
> In the collection module, it seems that a rule/search on a string field is always interpreted as a _substring_ search. It would be useful to have a way to force an exact match on a string field, for example by entering the value in square brackets or by adding a "$" (end-of-line) character behind it. And this should then be the default if an item is selected from the list of available values for a field, which also would help making this feature discoverable for manual input too.
> 
> At one point I had a Sony A7 (officially "Sony ILCE-7") and then later upgraded to an A7II ("Sony ILCE-7M2"). When I select the "camera" field in the collection module, both cameras show up in the list with the correct number of pictures available. When I click on the _7M2_ item, I indeed get the correct selection. But when I click on the A7, I get a selection that contains both, because the starting substring is identical. I don't think there is currently a way to narrow the selection to an exact match.
> 
> If this functionality already exists, then this would turn into a change request for the documentation of the collection module.

If one searches for "ILCE-7", certainly "Sony ILCE-7" matches.  Exclusion should only be affected when "ILCE-7" fails to match, *unless* a *field* was specified rather than a *string* such as *camera* and "Sony ILCE-7" was specified as the camera name rather than "ILCE-7".  But specifying "Sony ILCE-7" *would* exclude "ILCE-7"  

Anything else is illogical.

**Comment by dterrahe** [comment]
> If one searches for "ILCE-7", certainly "Sony ILCE-7" matches. Exclusion should only be affected when "ILCE-7" fails to match, _unless_ a _field_ was specified rather than a _string_ such as _camera_ and "Sony ILCE-7" was specified as the camera name rather than "ILCE-7". But specifying "Sony ILCE-7" _would_ exclude "ILCE-7"
> 
> Anything else is illogical.

I'm not sure I understand what you are saying.

My problem is _not_ with "Sony ILCE-7" matching. My problem is with "Sony ILCE-7M2" _also_ matching. So there is no way to get _only_ "Sony ILCE-7".

**Comment by ptilopteri** [comment]
> I'm not sure I understand what you are saying.
> 
> My problem is _not_ with "Sony ILCE-7" matching. My problem is with "Sony ILCE-7M2" _also_ matching. So there is no way to get _only_ "Sony ILCE-7".

If you are defining/limiting your collection using string match, w/o character limiting, there is no way to do a substing match.  If you are limiting your collection using *camera*, the two mentioned strings should be exclusive, as the provided camera name and the shorter string will not match as the camera names are different.

The defined camera name must match and as such "Sony ILCE-7" would exclude "Sony ILCE-7M2"

Limiting your collection using only "string" would fail but using "camera" would not.

Sorry, dt is busy atm and I cannot check the exact field name for "camera".

**Comment by dterrahe** [comment]
> The defined camera name must match and as such "Sony ILCE-7" would exclude "Sony ILCE-7M2"

Are you saying this _should_ be the case, or that this currently _is_ the case. It definitely does _not_work the way you describe in a recent master.

**Comment by hatsunearu** [comment]
I think I'll just make it so that if you put quotes around something like `"Sony ILCE-7"`, it tries to exact-match that.

**Comment by hatsunearu** [comment]
Huh, so I implemented exact match search, but I'm finding some weird behavior regarding shift-click on numerical parameters in collections. It doesn't seem to do anything. Am I the only one seeing this?

**Comment by dterrahe** [comment]
Like what I mentioned last paragraph here https://github.com/darktable-org/darktable/issues/5602#issuecomment-648706863 ?

**Comment by hatsunearu** [comment]
Yeah. Also the code seems way harder than I thought, might take a while to implement. If anyone else wants to jump in, please let me know and I can hand off the baton. Feel free to work on top of my fork branch...

**Comment by AlicVB** [comment]
not sure why you have closed the issue... I would say that it's a valid request. iirc it has even been done by @phweyland in its new "search" filter...
