### ISSUE TITLE
gradient in split-toning balance slider seems inverted 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5606]
**Describe the bug**
Gradient in split-toning balance slider seems inverted 

**To Reproduce**
1. Go to darkroom
2. Open split-toning, let default
3. Move balance slider to the right (more red) the image becomes more green

**Expected behavior**
The balance slider should be more intuitive, I'm pretty sure this is a regression.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian
 - 
 - 

**Additional context**

**Comment by pitbuster** [comment]
@TurboGit I think this broke with this commit: https://github.com/darktable-org/darktable/commit/97062483ecd99eb7a9a1e752ad5d0ee785603a01

When I fixed the reversed balance slider I mapped the paremeter to 1 - slider_value to avoid having to migrate the parameters (in the balance_callback function), but with the introspection refactor that mapping seems to be lost.

**Comment by TurboGit** [comment]
@pitbuster : But in fact here it is the gradient (display) that is inverted. Should be easy to fix.
