### ISSUE TITLE
Image Information Display

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#5609]
**Describe the bug**
When the import, change, export, and print timestamps got added to the database they were inserted into the metadata.c code where it seemed to make the most sense, according to the code comments.  However, the data displays in the order that it's declared, so the timestamp information is displayed while image information such as exposure, ISO, timestamp, height, width... are pushed out of the viewport.

![image_info](https://user-images.githubusercontent.com/1634891/85347056-7011e780-b4c5-11ea-9801-00a26336c375.jpg)

**To Reproduce**
1. Open darktable
2. Hover over an image

**Platform (please complete the following information):**
 - Darktable Version: git master
 

**Additional context**
This is simple enough to fix, but I thought that I would open an issue in case anyone else had ideas about the information displayed and the order.

My plan is to move the timestamps to the bottom, unless someone has a better idea of where to place them.

**Comment by phweyland** [comment]
> When the import, change, export, and print timestamps got added to the database they were inserted into the metadata.c code where it seemed to make the most sense, according to the code comments.

Sorry, I don't understand this. There is no time stamp in metadata.c.
Could you elaborate a bit more please ?

**Comment by wpferguson** [comment]
I'm sorry, didn't double check after I typed. It's in src/libs/metadata_view.c

```
/* initialize the labels text */
static void _lib_metatdata_view_init_labels()
{
  /* internal */
  _md_labels[md_internal_filmroll] = _("filmroll");
  _md_labels[md_internal_imgid] = _("image id");
  _md_labels[md_internal_groupid] = _("group id");
  _md_labels[md_internal_filename] = _("filename");
  _md_labels[md_internal_version] = _("version");
  _md_labels[md_internal_fullpath] = _("full path");
  _md_labels[md_internal_local_copy] = _("local copy");
  _md_labels[md_internal_import_timestamp] = _("import timestamp");
  _md_labels[md_internal_change_timestamp] = _("change timestamp");
  _md_labels[md_internal_export_timestamp] = _("export timestamp");
  _md_labels[md_internal_print_timestamp] = _("print timestamp");
#if SHOW_FLAGS
  _md_labels[md_internal_flags] = _("flags");
#endif

  /* exif */
  _md_labels[md_exif_model] = _("model");
  _md_labels[md_exif_maker] = _("maker");
  _md_labels[md_exif_lens] = _("lens");
  _md_labels[md_exif_aperture] = _("aperture");
  _md_labels[md_exif_exposure] = _("exposure");
  _md_labels[md_exif_exposure_bias] = _("exposure bias");
  _md_labels[md_exif_focal_length] = _("focal length");
  _md_labels[md_exif_focus_distance] = _("focus distance");
  _md_labels[md_exif_iso] = _("ISO");
  _md_labels[md_exif_datetime] = _("datetime");
  _md_labels[md_exif_width] = _("width");
  _md_labels[md_exif_height] = _("height");

  _md_labels[md_width] = _("export width");
  _md_labels[md_height] = _("export height");

```

**Comment by phweyland** [comment]
> It's in src/libs/metadata_view.c

Understood. Thank you.

**Comment by phweyland** [comment]
Can be related to #5478 too.

**Comment by TurboGit** [comment]
I'm not sure to understand the issue and to me the timestamps seems to fit well close to the filename & local copy status. I'm not clear why moving them to the bottom would fix something. Can you clarify ?

**Comment by wpferguson** [comment]
If I'm a user and I'm looking at image information, then I am more interested in seeing the exif information than the timestamps.  The filename, filmroll, local copy, version and path are necessary too.  The timestamps aren't important to me as a user and they certainly are not more important than the exif information.  So if we use the paradigm of most important information first, then the timestamps should move down in the information stack.

The imageid is important to me when I'm developing, because I go to the database and look up the image if I have a question.  Flags could probably go away too.  I can read them, but I don't really think most users care.

The other thing I think of is moving from 3.0.2 to 3.2.  If the user is using image information in 3.0.2 and moves to 3.2 the timestamps will push some of the exif information out of the viewport and the user will have to scroll to see the all of the exif information.  Then if they want to see the filename, they'll have to scroll back up.  I think the change will cause some grief.

Perhaps we need to look at image information from 2 perspectives, user and developer and group the information accordingly with user on top.

**Comment by phweyland** [comment]
I agree with the statement "more useful on top" and time stamps are less useful there than in collect module probably.
But, ... everyone has his own important data. I think the real good answer is to let the user configure the data he wants to see (and (maybe) in which order). There are bunch of lines I never look at.

**Comment by wpferguson** [comment]
`But, ... everyone has his own important data. I think the real good answer is to let the user configure the data he wants to see (and (maybe) in which order). There are bunch of lines I never look at.`

I agree.  I like having the imageid available but I could also see where most users could care less.  Where do we go from here?  Another setting?

**Comment by AxelG-DE** [comment]
I'd suggest not to use a setting, which can be forgotten, but structured and foldable (where a rotating triangle indicates that there is folded info/content).

My aim is to have it maximum intuitive, which a setting IMHO is not :)

**Comment by AxelG-DE** [comment]
prevent auto-closure

**Comment by twchambers** [comment]
I'd just like to voice my support for this feature. To be able to reorder and enable/disable unused information would be ideal.
Currently I have to scroll to see my most helpful exif tags as for some reason the image information panel remains a fixed haieght and does not into available space on my screen.

**Comment by quovadit** [comment]
It would be great, if the user could reorder/disable the attributes!
The 'presets'-burger of the 'image information' module would be a very intuitive way to customize the list in place (see screenshot)
![customize-image-information](https://user-images.githubusercontent.com/5677563/97308283-fe75eb80-1860-11eb-8ba2-d6b1be0f8f70.png)

Please don't introduce folding, because I want to see the relevant information quickly when hovering over an image

**Comment by davidmorning** [comment]
I'd love to see Quovadit's proposal. Found this ticket looking for a solution to exactly this issue, there's a bunch of information in there which I wouldn't need and it'd be fantastic to be able to hide them or prioritise the information I would use

**Comment by phweyland** [comment]
Should come. See #7294.
