### ISSUE TITLE
filmic - highlight mask remains enabled when module closed

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#5610]
**Describe the bug**

If the highlight reconstruction mask is turned on when filmic is closed or loses focus, it remains enabled

**To Reproduce**
1. Open filmic rgb
2. Select "reconstruction" tab
3. Click on the mask icon
4. Click on the module title to close it
5. Observe that the mask display is still active

**Expected behavior**
The mask should turn off and display should return to normal as with other modules which have a mask display such as retouch and color zones.

**Platform (please complete the following information):**
 - Darktable Version: git master 3.1.0+2423
 - OS: Mageia Linux 7.1
 - no OpenCL
 - GCC 8.4, clang 8.0

**Comment by TurboGit** [comment]
Same for tonecurve. This is most certainly related to the recent introspection change.

@dterrahe : Can you have a look too ?

**Comment by elstoc** [comment]
@TurboGit it's not related to introspection. I'm running a version at +449 and it has the same issue. I've submitted PRs to address this issue in both filmicrgb and tone equalizer.
