### ISSUE TITLE
[Bug] Tone equalizer advanced mode zooms but does not adjust light !

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#5611]
Hi all

I have a picture.
* I double click to edit it
* Directly open Tone Equalizer > Advanced
* Activate it and hover onto a zone
* Mouse scroll to adjust light

It zooms on the picture but does not do anything else.

dt 3.1.0~git2352.28952665e
Kubuntu 20.04 w/ KDE 5.18.5 + Qt 5.12.8
Intel core i7 7700k + 32GB RAM + NVidia GFX 1070

Am I the only one ?
I restarted several times, it works properly on the first one then ... but ends up doing the same again.
I wonder if it may be related to me going from preview directly to darktable using a keyboard shortcut ...

Thanks
GLLM

**Comment by elstoc** [comment]
I can't reproduce this on +2353 on ArchLinux using the steps suggested.

**Comment by johnny-bit** [comment]
Not reproducible for me neither on 3.2.1 nor current master :)

If you are still able to reproduce, please comment and I'll reopen so we can investigate further!

**Comment by GLLM** [comment]
Not reproduced on darktable_3.4.0-1.1_amd64
Sorry for letting this open this long !

**Comment by urgv** [comment]
I'm seeing this issue on Darktable 3.6.0 on Pop OS 21.10.

**Comment by johnny-bit** [comment]
try 3.8.0 - lotta changes since. If you still have issues plz open new bug report with detailz
