### ISSUE TITLE
FAO Mica: FAQ contribution content

### ISSUE THREAD

**Issue by james-h-dt** [darktable-org/darktable#5617]
My first contribution. Following mica[m]'s guidance, this guthub issue contains a text file, with some suggested additional content for the darktable FAQ. 

It covers:

- how to make a darktable backup 
- how to purge the database for inconsistencies.

It's provided in plain text. I can rework as markup. Just let me know the darktable markup standard.

Here is a link to a google doc, showing how the content could look with markup: [link](https://docs.google.com/document/d/1b465jTLi3xyVYoE0sXZlZJa7_mFvxLKMeotSZEdkh60/edit?usp=sharing)

[darktable FAQ contributions 2020-06-22.txt](https://github.com/darktable-org/darktable/files/4819218/darktable.FAQ.contributions.2020-06-22.txt)

**Comment by rabauke** [comment]
I think this is not to right place for reporting this. 

The content of your google doc write up might be a useful contribution to the dt [faq](https://www.darktable.org/about/faq/). There is a special git repository for the dt web page, see 

- https://github.com/darktable-org/dtorg/ and in particular
- https://github.com/darktable-org/dtorg/blob/master/content/pages/about/faq.md

You should edit the faq.md and open a pull request. You might ask for further advice if you are not familiar with git and the pull request work flow.

**Comment by elstoc** [comment]
@paperdigits requested on IRC for this to be raised here

**Comment by paperdigits** [comment]
Yes I did request this here. We should decide where it belongs, then I'll put it there.

**Comment by Nilvus** [comment]
@paperdigits: I suggest to put this FAQ in the new dtdocs manual, at the end. And if ok, close this issue when done.

**Comment by paperdigits** [comment]
I've opened https://github.com/darktable-org/dtdocs/issues/200 so this issue can be closed.
