### ISSUE TITLE
introspection issue with translation

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5619]
**Describe the bug**
There is at least one issue with the current translation.

I don't understand what is wrong and how to fix that.

**To Reproduce**
1. Go to module "color zones", see that channel cannot be translated

**Expected behavior**
String should be translatable.

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/85417874-6beed400-b570-11ea-964a-00416851403e.png)

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Debian

**Additional context**

In colorzone we have:

```
typedef struct dt_iop_colorzones_params_t
{
  dt_iop_colorzones_channel_t channel; // $DEFAULT: DT_IOP_COLORZONES_h $DESCIPTION: "select by"

```

So the channel string should be "select by", but this is not what we see on the module. Maybe related?

**Comment by TurboGit** [comment]
@dterrahe : most probably for you :) TIA.

**Comment by dterrahe** [comment]
Typo in DESCIPTION ... sorry

**Comment by TurboGit** [comment]
Stupid me ! I read that maybe 10 times and did not see the typo :(
