### ISSUE TITLE
local contrast: error when changing mode

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5620]
If I open and enable the local contrast module, its mode defaults to 'local laplacian filter':

![Screenshot_2020-06-23_16-22-47](https://user-images.githubusercontent.com/9555491/85423087-30eba100-b56e-11ea-887e-973dd6a0c81f.png)

If I change the mode to 'bilateral grid', all looks fine:

![Screenshot_2020-06-23_16-22-56](https://user-images.githubusercontent.com/9555491/85423143-42cd4400-b56e-11ea-9e77-c915d1e20f59.png)

However, if I then change back to 'local laplacian filter' I get the following:

![Screenshot_2020-06-23_16-23-06](https://user-images.githubusercontent.com/9555491/85423230-5bd5f500-b56e-11ea-8c02-84832a9ec817.png)

3.1.0+2354~g2272cc4aa on ArchLinux. Issue occurs both with and without OpenCL.

**Comment by dterrahe** [comment]
This module is funky in that two sets of sliders are linked to the same field. I realise I need to do some extra refreshing when switching mode; PR coming up.

Realising I can improve the logic a little as well; don't need to reset everything on each "mode" switch, as was happening before and I had intended to just copy.

**Comment by dterrahe** [comment]
_Also_ now realising, that if a (dynamic) shortcut is used to change a slider that is currently hidden (because in the wrong mode) funky stuff happens. This is not a regression; just tested that it happens in 3.0.2 as well.

So I'll need to switch modes if a hidden slider is value-changed.
