### ISSUE TITLE
Mono over-ride

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#5621]
**Dumb printer refuses to load mono tif**

My printer refuses to load a tif which isn't in RGB mode, even if set to "Print in Black and White"

**A manual over-ride on the mono-mode tif output**

It shouldn't be so, but that seems the simplest solution...

@jenshannoschwalm I think this is your work that I'm asking you to desecrate?

**Comment by parafin** [comment]
Are you talking about printing directly in dt or manually after exporting a tif file?

**Comment by GrahamByrnes** [comment]
I'm using a windows machine, printing only happens externally :-(

**Comment by jenshannoschwalm** [comment]
We already have so many options ... what about a hidden option? But why is your printer so dumb :-) Or is it the printer driver? Tiff's should be possible with just one channel.

**Comment by GrahamByrnes** [comment]
I'd be fine with that... although other may have the same issue

Good question re the printer. Canon does not support open source and generally expect that the user will print directly from PS or LR. Quite recently, they wrote a wrapper for the plug-in driver which allows printing tiff's etc on the pro-1000 and up.

Yep, 1200€ printer...

Thing is, they seem to have given the job to someone on work experience: it looks very pretty, but if you choose "centre" it centres the image around a random point that hangs most of the image off the side of the paper. It seems to work best when the image size is chosen way bigger than the paper on the long axis, then it can manage to centre within that... but every time I change paper size it's a nightmare. Basically it appears to be a very poor implementation of ghostscript. I thought about installing printFab, but 
- on Windows and up to A2, 200€
- it doesn't help anyway, since you still need something to launch the image, and MS have thoughtfully removed all basic print software that does simple stuff like allow margin setting. Insane, yes.

Yes, move away from Windows. Soon.

Anyway, today was the first time I tried to feed it a mono tiff, and it simply didn't open. No error message, just ignored me. After a little while I remembered the mono toast and Hanno's work, went "uh huh", added a tiny amount of split-toning and re-exported, and all was well.

I just checked and there was a new version of the driver/wrapper/disaster that came out late March, I shall try it now...

**Comment by jenshannoschwalm** [comment]
Ok. For the few of us that go for b&w dt should be trouble free. Any other opinion
1. Hidden option with default to 3 channels
2. Hidden option with default mono
3. Add a checkbox in tiff export dialog.

Feel free to select :-) First 5 votes count :-)

**Comment by GrahamByrnes** [comment]
3, 1, 2.

(I checked the new version, same old sh...)

**Comment by hatsunearu** [comment]
If you set the 3 channel mono option, would it just set RGB to the single luminance channel as if it were B/W? Or do you do some color matrix BS? Could cause some issues.

**Comment by GrahamByrnes** [comment]
As it worked previously, 3-channel mono is 3 identical channels. The test for a mono image is R=G=B at every pixel.

**Comment by jenshannoschwalm** [comment]
Will pr tonight

**Comment by johnny-bit** [comment]
I vote 3,1,2 :D
