### ISSUE TITLE
crop & rotate: "original image" setting not retained

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5629]
If i choose "original image" in the crop & rotate aspect drop-down, this is replaced with a ratio and the "original image" setting is not retained. For example in the following I have simply enabled crop & rotate, selected "original image" and committed my changes:

![Screenshot_2020-06-24_20-03-31](https://user-images.githubusercontent.com/9555491/85616576-de85af80-b655-11ea-919f-bcf9a739eec9.png)

**Comment by TurboGit** [comment]
I have tried hard to reproduce this issue, but I cannot ! In no circumstance I was able to get a wrong ratio in the aspect box. The text stays "original image" for me. So, this may already fixed (in #5637) or there is a very specific context to reproduce ?
