### ISSUE TITLE
progress bar label padding is awkward, needs CSS fix

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#5631]
**Describe the bug**
The progress bar looks visually awkward. It could use some padding, particular on the left side.

**To Reproduce**
1. Go to lighttable view
2. Select a few images, preferably ones which will be slow to process, so that the progress bar will stay visible
3. Type control-e to start export
4. During export, a progress bar should appear in the bottom left of the window.

**Expected behavior**
The margins/padding of the label should be more pleasing.

**Screenshots**
![image](https://user-images.githubusercontent.com/2311860/85642797-725c7900-b660-11ea-8e53-5ff0924cecda.png)

Left/bottom of screenshot are flush with left/bottom of darktable window. The scrollbar-looking thing at the bottom is actually the progress bar.

**Platform (please complete the following information):**
- Darktable Version: master 851d72a1922a57c2d0b53574e62ee4f3fc582b98
- OS: Debian bullseye/sid
- OpenCL activated: yes
- Nvidia GP104GLM [Quadro P4000 Mobile] (rev a1), OpenGL version string: 4.6.0 NVIDIA 440.82

**Additional context**
- I've tried this with the export and print progress bar. Presumably they are all fairly awkward.
- I'm not sure why there is a vertical line in the cancel "X" in the screenshot.

**Comment by dtorop** [comment]
@Nilvus That all makes sense. The thing which surprised me was the flush left text into the window. Everything else in the UI is now so visually considered, that this stands out. And yes, perhaps the button appearance, as you note, could be improved.

The vertical line in the X must be a bug here, or a screenshot glitch. I can't reproduce it.

And yes, I've no worries about the progress bar being mistaken for a scroll bar. It's clear when seeing this in darktable. I wanted to note it as in the static screenshot it starts to look like some sort of bottom scrollbar.

**Comment by Nilvus** [comment]
> @Nilvus That all makes sense. The thing which surprised me was the flush left text into the window. Everything else in the UI is now so visually considered, that this stands out. And yes, perhaps the button appearance, as you note, could be improved.

As i work on most CSS things, when I export (not often) or print (nearly never), I rarely look at that so didn't notice that. But all details count, so I will fix that.

**Comment by dtorop** [comment]
> As i work on most CSS things, when I export (not often) or print (nearly never), I rarely look at that so didn't notice that. But all details count, so I will fix that.

Yes, that makes sense. The background jobs run fast enough that I rarely look either. I finally exported some images last night with significant stacks of iops (especially as filmic v4 doesn't yet have the OpenCL optimizations and its highlight reconstruction can require a lot of work). Hence it's the first time I had time in a while to pay attention to the progress bar.

I think the other place that the progress bar shows up and that people see it is when importing images. This has been broken for me for a while (darktable UI becomes unresponsive on import). I haven't gotten around to seeing if that's a real bug, but I'll check on this as well, as long as it is on my mind.

**Comment by Nilvus** [comment]
What do you think of that proposal? Space added on left is only 4px because with text with more length like that example in french, that adding more will quickly hide some text depending on width panel. I remove border for cross button, which feel better for me now and finally for some other buttons like prefs, star or reset, preset, etc.

![2020-06-25_17-35](https://user-images.githubusercontent.com/45535283/85751312-c1f77f00-b70a-11ea-8828-dce444567816.png)

**Comment by Nilvus** [comment]
I also set the progress bar a little whiter than before.

**Comment by dtorop** [comment]
Yes, it looks great. When I look at it, I don't even think about it, which is a definition of good design, yes? In most cases the progress bar will be subliminal, hence minimal is good...

**Comment by Nilvus** [comment]
For something like that, something you don't even think about it is for me, yes, a good design. But subliminal progress bar, let me think that we can change more that part. 2 mockups:

![2020-06-25_18-04_1](https://user-images.githubusercontent.com/45535283/85755813-8eb6ef00-b70e-11ea-97b5-99f33094f895.png)

![2020-06-25_18-04](https://user-images.githubusercontent.com/45535283/85755829-91b1df80-b70e-11ea-8858-929d4ced2a3f.png)

In other themes, contrast between colors will be the same. My personal choice would be for second one. What do you think of those (in regard of actual one of course)?

**Comment by Nilvus** [comment]
Finally this one should be better:

![2020-06-25_18-11](https://user-images.githubusercontent.com/45535283/85756595-40eeb680-b70f-11ea-87b2-99495c774f98.png)

What do you think of last ones? Which one I push as a PR? Last one is my personal choice.

**Comment by dtorop** [comment]
> Last one is my personal choice.

Yes, I agree. The progress bar color makes a lot of sense on that one.

**Comment by Nilvus** [comment]
@dtorop: see #5635

**Comment by dtorop** [comment]
@Nilvus The PR looks great. Very much appreciated here.
