### ISSUE TITLE
UI freeze on importing images

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#5636]
**Describe the bug**
UI can freeze when importing many images, or when many images are imported into a large library.

**To Reproduce**
1. Create a large image library:
```sh
mkdir /tmp/img_test
cd /tmp/img_test
wget 'https://raw.pixls.us/getfile.php/2783/nice/Fujifilm%20-%20X-T3%20-%2014bit%20compressed%20(3:2).RAF'
mkdir many_images
for i in `seq 100`; do mkdir many_images/$i; for f in `seq 100`; do ln -s ../../Fujifilm\ -\ X-T3\ -\ 14bit\ compressed\ \(3:2\).RAF many_images/$i/dup_$f.RAF; done; done
```
2. Run darktable with a clean db/install
```
darktable --configdir /tmp/img_test/conf --cachedir /tmp/img_test/cache --library :memory:
```
3. ctrl-shift-i to open import dialog
4. select (but do not double-click) the "many_images" folder
4. expand "import options" and enable "import folders recursively"
5. click "open"
6. darktable will display an "importing 10000 images" progress bar at approx. 1% then become unresponsive until the images are imported

**Expected behavior**
Darktable should import images with a responsive UI (progress bar updates, widgets responsive, and images appearing in the lighttable center view and "collect images" if that is expanded).

**Platform (please complete the following information):**

 - Darktable Version: da0d15763481616691d019598306b360faf97acb
 - OS: Debian bullseye/sid, Gnome 3.36.3
 - OpenCL activated: yes
 - Nvidia GP104GLM [Quadro P4000 Mobile] (rev a1), OpenGL version string: 4.6.0 NVIDIA 440.82

**Additional context**
- I've noticed unresponsive UI during import through several recent darktable versions -- I think this is a longstanding bug.
- UI is responsive for importing small #'s of files, especially to a fresh DB.
- UI is unresponsive when importing files to a large extant library -- this is the situation which I was trying to replicate, and spurred this bug report. I haven't yet figured out a way to replicate this with a clean install, but figure that the above steps produce a related bug. In the case of my setup (large library), the UI becomes unresponsive before the import file chooser is closed.
- If file chooser widget is stuck open, inserting a `sleep(1);` in `dt_film_import1_run()` in src/control/jobs/film_jobs.c before the call to `dt_film_import1()` will let the file chooser close, as `_lib_import_folder_callback()` is able to complete before things seize up.
- I'm unclear if there is a critical # of images/folders after which import jobs become unresponsive.
- Sometimes the UI starts responsive, then freezes up, or freezes up immediately if the mouse/cursor is moving?

**Comment by jenshannoschwalm** [comment]
Can't reproduce here on current fedora and nvidia graphics.

Although the code section you mentioned looks good. I guess the unresponsiveness is related to locking the database while importing for every image and that code does not have any suggestion for the os to switch thread (g_sleep). I will have a look ...

**Comment by dtorop** [comment]
@jenshannoschwalm Thank you for trying to replicating and taking a look. That makes sense about DB locking and the active thread somehow grabbing all the resources (whether via sqlite or even some sort of run-away GList).

I wish I could make a reproducible report, as otherwise we're just left looking at the code and extrapolating -- and running the risk that this is external, e.g. a GTK bug, or some quirk of my setup here.

Looking at the code: dt_image_import_internal() is doing some filesystem and DB work, and dealing with the image cache and tags. And then on every image a DT_SIGNAL_IMAGE_IMPORT is causing some collection work (_dt_collection_recount_callback_1()). Then this raises DT_SIGNAL_COLLECTION_CHANGED, which propagates out to cause updates in these libs: export, tagging, metadata, recentcollect, timeline, duplicate, select, styles, image, copy_history, as well as other parts of the code: map, thumbtable, thumbnail.

It's possible that for importing many images (or importing some images into a large DB) that this produces some sort of thread logjam. What's nice about the current setup is that -- if it works -- every image imported causes a response in the entire UI, and there's a nice sense of the flow of the import. But there could be another flow, where the DB work is done en masse for all imported images, and DT_SIGNAL_IMAGE_IMPORT can inform its recipients that a number of images have been imported.

**Comment by jenshannoschwalm** [comment]
> That makes sense about DB locking and the active thread somehow grabbing all the resources (whether via sqlite or even some sort of run-away GList).

I don't think this is the perfect question :-)

The main "stopper" while importing is related to ensuring a **correct** history, there are many places where the database is modified without full safety via transactions :-( So we have protecting pre-image-mutexes (See #3201 and #3181 to get into this stuff). So while importing large sets of images we might end up in "masses of images" fighting for the mutex ownership and leaving the UI behind. BTW what kind of cpu do you have and how many threads do you allow?

A second point - i didn't look into yet - the directory you are importing, is is deeply nested? This **could** be an issue if the algo behaves bad. 

At least there was not a single import-safety related bug report since introducing those mutexes :-) atm i work on something else but will definitely look into this asap, your suggestion to do the gui a favour seems to be a good starting point.

**Comment by dtorop** [comment]
> So while importing large sets of images we might end up in "masses of images" fighting for the mutex ownership and leaving the UI behind.

That all makes sense. I'm glad you've been thinking/working this through.

> what kind of cpu do you have and how many threads do you allow

Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz. The conf `worker_threads` is 8 (default for this system).

> the directory you are importing, is is deeply nested

The test in this bug report is 100 directories, each containing 100 images. I see this problem here in my DB when importing a single, non-nested folder with 100+ images.

My memory is that this started going awry for me a few years ago, before your mutex work. Either some other code change caused the problem, or I just reached a critical DB complexity...

**Comment by johnny-bit** [comment]
Hey, Since #8080 landed and a bit more speedups happened (and i don't remember if @jenshannoschwalm had a time to look into threading stuff since demosaicers is still ongoing project) - what's the status here? I do think that current master is super snappy compared to what I remember of 3.0, 3.2.1 or even 3.4 releases in terms of importing large(ish) collections.

**Comment by jenshannoschwalm** [comment]
I reall think this can be closed. I checked and am sure it's not directly related to the mutexes protecting an image to be opened. #8080 has been speeding up a lot.

What i can still observe is, setting far too large values in the background threads - lets say to 16 - results in 16 images locked and processed by many cores at the same time and having to mod the database. That certainly is **very** bad. That's exactly what #8955 is about.

**Comment by johnny-bit** [comment]
@dtorop - what do you think?

**Comment by dtorop** [comment]
I think we're good! I don't know if there was one fix-it commit, but all the various work, included @ralfbrown work, seems to have solved this here.
