### ISSUE TITLE
untranslated UI string in dithering module

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#5641]
**Describe the bug**
The label for the drop box in the dithering module always is "dither type". This string seems not to take part in the usual translation process. As far as I can tell this is not an issue of missing translation in po files.

**To Reproduce**
Start dt with a non-English locale and open the dithering module.

**Expected behavior**
A proper translation for "dither type" (used to be "Methode" in German).

**Platform (please complete the following information):**
 - Darktable Version: git master

**Additional context**
Presumably this issue had been introduced via #5335, may be related to #5499 .

**Comment by dterrahe** [comment]
Thanks for reporting.

The parameter should have a $DESCRIPTION specified, as in:
  dt_iop_dither_type_t dither_type; // $DEFAULT: DITHER_FSAUTO $DESCRIPTION: "method"

@TurboGit I will prepare a PR.

**Comment by TurboGit** [comment]
Fixed now.
