### ISSUE TITLE
"Range based" color picker sometimes causes odd results

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5653]
**Describe the bug**

I am talking about this tool:
![Screenshot_20200628_144804](https://user-images.githubusercontent.com/49004103/85947997-76cdae00-b94e-11ea-8814-a56b0888afb1.png)

Which in general is brilliant...

what sometimes happens is, partially or even worse completely, the things inside the range are NOT masked or not included in the mask (here I wanted to reduce the little bit too bright 'fenders', that area is not clipped!) :
![Screenshot_20200628_143750](https://user-images.githubusercontent.com/49004103/85948043-b4cad200-b94e-11ea-83b9-3124aa68c550.png)

**To Reproduce**

**Expected behavior**

slected range shall be 100% represented in the mask

**Platform (please complete the following information):**
 - Darktable Version: Current master, I went back down to 2.7.0+1699 and the same behaviour is still there

**Additional context**
* darktable version : 3.1.0+2383~gc9ca6258d
* OS                : Linux - kernel 5.7.6-gentoo
* Distro            : Gentoo Base System release 2.6
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r1
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.16
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by AxelG-DE** [comment]
Ping

**Comment by AxelG-DE** [comment]
Hello together,

I still think, the "set range" color picker is doing things pretty wrong and it is annoying me regularly, in particular when I use it for hue...

In this sample I used the L-Channel, but I simply do not expect an area inside the range, which is not part of the mask
![Screenshot_20201030_162837](https://user-images.githubusercontent.com/49004103/98450575-04f84300-213e-11eb-9741-a93c5ac009f3.png)

What I show in the following two pics, at least to me shows, "set range" is kinda sick and not supporting me (any more, I remember, when it came up, I considered it brilliant)
![Screenshot_20201107_211743](https://user-images.githubusercontent.com/49004103/98450695-07a76800-213f-11eb-971c-22ecd79a7201.png)
![Screenshot_20201107_211756](https://user-images.githubusercontent.com/49004103/98450697-09712b80-213f-11eb-9108-d05bf0192078.png)

I would like to ping some devs here, as I just could imagine, you guys have the competences. So please do not chase me outa room, if that behaviour is deprecated. Just let me know...
@TurboGit because you just managed one of my mask issues :-)
@dterrahe @elstoc just acc. to my observations of your skills :)

Thanks in advance

**Comment by AxelG-DE** [comment]
today bumped into a more obvious case:
See that the upper triangle on the lighter side is at 99 instead of 100
![Screenshot_20201122_083340](https://user-images.githubusercontent.com/49004103/99897926-ea75ac00-2c9d-11eb-8a4d-82fb9ead4bd5.png)

Manually set it to 100 somehow fixes it (but not that simple on hue)
![Screenshot_20201122_083358](https://user-images.githubusercontent.com/49004103/99897960-15f89680-2c9e-11eb-9ef7-eecaa6396b1c.png)

**Comment by AxelG-DE** [comment]
Ladies and Gentlemen,

I am happy that finally something happened. 

I hope nobody will be too disappointed, when I state, the situation improved a bit, but still unexpectedly I get almost 100% unmasked **inside** the range, which appears very odd to me.

![Screenshot_20210303_212123](https://user-images.githubusercontent.com/49004103/109867157-74062400-7c66-11eb-96cd-7581b814f8a6.png)

admittedly a bit gammut critical:
![Screenshot_20210303_212446](https://user-images.githubusercontent.com/49004103/109867555-ed057b80-7c66-11eb-9e1c-61a60946b6ae.png)

When I chase brightness, the situation did improve noticeably
![Screenshot_20210303_212915](https://user-images.githubusercontent.com/49004103/109868138-92b8ea80-7c67-11eb-9a15-90610bbbe9c2.png)


@TurboGit may I still kindly ask to reopen? :blush: 
@hlecleme any advices, what I could test, in order to support more?

**Comment by hlecleme** [comment]
@AxelG-DE for the first image, could you check if it is the same behavior as #7004? Thanks in advance :)
