### ISSUE TITLE
parametric mask: issues with color pickers and narrow side panel

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5654]
When the right hand side panel is expanded fully (so that all controls are visible) the parametric mask color pickers seem to work pretty well.

However, when the panel is narrower, such that some of the mask's channels (e.g. 'g R G B H S L') are not visible there are a number of strange side-effects. The issues seem to start just before the 'B' channel becomes hidden (when shrinking the panel width).

In the following example, I've just discarded history using the scene-referred defaults and then selected the parametric mask button:

![Screenshot_2020-06-28_14-31-44](https://user-images.githubusercontent.com/9555491/85949025-1fc6d980-b94c-11ea-9cce-85973bc677ec.png)

I select the left-hand-side color picker in 'point mode' and the following happens:

![Screenshot_2020-06-28_14-32-44](https://user-images.githubusercontent.com/9555491/85949045-438a1f80-b94c-11ea-9d96-a32233543ced.png)

Obviously this has done some very funky things to the image itself. However, the less obvious feature is that it's also subtly changed the display of the module itself.

This issue is more obvious if I compress the side panel still further to fully hide the blue channel selector. Before:

![Screenshot_2020-06-28_14-34-21](https://user-images.githubusercontent.com/9555491/85949078-84823400-b94c-11ea-8457-062effbbea8b.png)

After selecting the color picker:

![Screenshot_2020-06-28_14-35-07](https://user-images.githubusercontent.com/9555491/85949088-9532aa00-b94c-11ea-898a-3097bea53e23.png)

Now the Blue channel is suddenly visible. Selecting the picker should not do this.

I suspect these issues are related, hence raising them together in one issue.

Tested on 3.1.0+2376~g40f2f94e3 with ArchLinux. Both issues occur regardless of whether openCL is enabled.

**Comment by jade-nl** [comment]
Confirmed and not limited to the above actions.

I can see this happening when:

* right side panel is wide enough for all text/options to be seen,
* use (left) colour picker to pick an area,
* resize the right hand panel (smaller/bigger doesn't matter) **OR** move cursor outside full screen (to second monitor in my case).

I cannot provide a screenshot (going outside the darktable area creates the same distortion/effect)

**Platform**

* darktable : 3.1.0+2383~gc9ca6258d
* OpenCL installed : Yes (nvidia-opencl-common 440.82-1~bpo10+1)
* OpenCL activated : Yes
*Graphics card : GeForce RTX 2060 SUPER7979 MiB
*Graphics driver : nvidia (440.82)
* OS : Linux (kernel 5.4.0-0.bpo.4-amd64)
* Distro : Debian Buster (rel. 10.4)

**Additional context**

* Self compiled : Yes.
* Compilers : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake : 3.13.4
* Gtk : 3.24.5-1
* Glib : 2.58.3-2
* Sqlite : 3.27.2
* Optimization : None

**Comment by TurboGit** [comment]
Indeed, I can reproduce this one :( How is this possible ??? Why only when the side panel makes some icon non visible??

**Comment by elstoc** [comment]
I know! Both this and the other related issue are really strange. I'm still thinking that the in-module color picker is using the area/point selected by the parametric mask color picker by mistake.

**Comment by elstoc** [comment]
Resolved by #5657.
