### ISSUE TITLE
dt crashed whilst using filmic4

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5658]
dt 3.1.0+2017~ga6c18e1b7-dirty       Ubuntu 18.04
core i7     32Gb memory     no vid card
I was adjusting the white and black sliders in the Scene tab and dt just disappeared.
I'd invoked dt from a Terminal window, the contents are attached.  I can't find the backtrace, perhaps TMP files are deleted on shutdown?
[dt crash in filmic4 28Jun2020.txt](https://github.com/darktable-org/darktable/files/4842839/dt.crash.in.filmic4.28Jun2020.txt)

**Comment by hatsunearu** [comment]
Can you reproduce again, and maybe collect the core file as well? 

https://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-on-a-segmentation-fault

**Comment by RawConvert** [comment]
So do I do this -
1. Type/paste "limit coredumpsize unlimited" into my Terminal window
2. Then type/paste "$HOME/DT-Mast-9Jun20/bin/darktable --cachedir etc etc"
and will this put any dump in TMP?

dt crashes only infrequently.  I can't reproduce it, but if the procedure for getting a memory dump is not too messy, I'll run dt like that at least for a while.

**Comment by parafin** [comment]
Be advised that on Ubuntu it won't work - Ubuntu installs its own crash handler that intercepts core dumps. So better test with killall -sSEGV darktable first.

**Comment by RawConvert** [comment]
@parafin , so in Terminal, is that
killall -sSEGV darktable
then
$HOME/DT-Mast-9Jun20/bin/darktable --cachedir etc etc

Does the first need the whole path to the darktable executable?  I'm not knowledgable about linux, pls be explicit!
