### ISSUE TITLE
Incorrect re-import of almost fresh duplicates

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#5662]
**Describe the bug**
Reimport of minimally developed images fail

**To Reproduce**
1. Take a raw, discard history. Observe the the +/- icon in lighttable is not visible.
2. Open image in raw to do a first develop and apply presets. Please note that the +/- icon is still absent.
3. create a duplicate "with same history". Still no +/- icons, group is activated. The corresponding sidecars are  
[L1000451.DNG.txt](https://github.com/darktable-org/darktable/files/4846682/L1000451.DNG.txt)
[L1000451_01.DNG.txt](https://github.com/darktable-org/darktable/files/4846684/L1000451_01.DNG.txt)
and they both look ok for me.

4. Remove images and reimport, please note the error message on console `[exif] dt_exif_xmp_read for /nfs/BilderRaw/testraw2/L1000451_01.DNG.xmp, id 5526 found auto_presets_applied but there was no history`. The thumbnails looks wrong as no presets are applied so it's the original.
5. The sidecar after reimport is now of course wrong, 
[wrongL1000451_01.DNG.txt](https://github.com/darktable-org/darktable/files/4847016/wrongL1000451_01.DNG.txt)

**Expected behavior**
Import respecting information in sidecar.

**Platform:**
 - Darktable Version: git master 3.1.0+2392
 - OS: Fedora 32
 -  OpenCL does not matter
 -  intel 7700, nvidia quadro P2000

**Comment by jenshannoschwalm** [comment]
I did further testing, not sure yet about the underlying trigger but for sure when `read_history_v2` get's the data to be analysed the history items are not read/available.
@TurboGit i really geuss this is a release stopper, @elstoc i think you worked on duplicates history, any good guess?

**Comment by elstoc** [comment]
@jenshannoschwalm I think the only thing I've done that might relate to this is to fix an issue whereby sometimes an extra version of an image was being created by darktable when re-importing where the xmp version numbers don't start at 1 (fixing #4385 via #4571). I'm not sure that fix touches any of the things you're referring to.

**Comment by TurboGit** [comment]
I'll have a look at this.

**Comment by TurboGit** [comment]
Looks like the XMP of the duplicate gets cleared before it is read in exif.cc :(

**Comment by jenshannoschwalm** [comment]
It's not "cleared" i think but parts of it seem to be lost. Is it `read_metadata_threadsafe` ?

**Comment by jenshannoschwalm** [comment]
I am really surprised about this bug and how it was introduced. Here i can't import **any** sidecar defined duplicate at all any more.

**Comment by TurboGit** [comment]
I found the issue and I'm actually devising the best/safest possible fix for 3.2.

**Comment by TurboGit** [comment]
Should be fixed in #5676. Can you test on your side? TIA.

**Comment by TurboGit** [comment]
> I am really surprised about this bug and how it was introduced.

I did not track down the first commit introducing this, but yes it was a nasty bug !

**Comment by jenshannoschwalm** [comment]
@TurboGit , any reason to re-open?

**Comment by TurboGit** [comment]
Yes, seems like this issue is back on my side... Don't know why! Can you test again with master and report if buggy for you also with current master?

**Comment by phweyland** [comment]
If I understand properly the case, I think that avoiding to save xmp after reading exif doesn't sound correct.

>     2\. Open image in raw to do a first develop and apply presets. Please note that the +/- icon is still absent.

I do not understand this one. Applying any change, including presets, should trigger +/- icon. At least it does this on my side.

The issue seems related to auto-apply presets not yet applied. This is a burden everywhere !
So I think the real fix here should be to make dt resilient to xmp with auto_presets_applied without history.

**Comment by phweyland** [comment]
I've deleted my previous post. Sorry. Not sure there is any valid in there. 
One of my changes in #5704 screws this fix.
This change, related to DT_IMAGE_CACHE_RELAXED to DT_IMAGE_CACHE_SAFE, can be removed. But then there is another bug. "refresh exif" would refresh properly the metadata info but without saving them into xmp.

**Comment by jenshannoschwalm** [comment]
confirmed.

**Comment by phweyland** [comment]
Well, I've made the test to revert back DT_IMAGE_CACHE_SAFE to DT_IMAGE_CACHE_RELAXED on line 1194 of control_jobs.c. This does not solve anything...

**Comment by TurboGit** [comment]
My fix was fragile anyway. It was a try to have a very small fix for 3.2 but it looks like this does not fly!

We have many signals and some are writing the XMP possibly BEFORE the import is finished and so the needed imported XMP is read. The safest solution would be to copy the XMP in a temp file as soon as the name is known and then use this for initializing the duplicate. I may try this... Or maybe you have a better and safest solution ?

**Comment by TurboGit** [comment]
Found some time to look at this, see #5710. Seems simple and safe for 3.2. The change in _image_duplicate_with_version() was really what I had in mind when working on my first fix. So that's basically and extension of the previous fix.

@jenshannoschwalm : can you test on your side ? TIA.
