### ISSUE TITLE
duplicate of an image can have version number of 0

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#5674]
**Describe the bug**
It is possible to duplicate an image such that the version of the duplicate is 0.

**To Reproduce**
1. Select a freshly imported image
2. Go to darkroom view
3. Expand "duplicate manager"
4. Click "create a duplicate with same history stack"
5. Expand "image information" -- verify that you are now editing a duplicate with version 1
6. Click "create a duplicate with same history stack"
6. You are now editing a third duplicate. In "image information" the version is 0.

**Expected behavior**
The version of the second duplicate should be 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/2311860/86165637-9517e300-bae1-11ea-82da-77c44ef3517b.png)

**Platform:**
 - Darktable Version: master aef614f0e3caa8bfff91559b7a50df24e4e7357d
 - OS: Debian bullseye/sid, Gnome 3.36.3
 - OpenCL: yes
 - Nvidia GP104GLM [Quadro P4000 Mobile] (rev a1), OpenGL version string: 4.6.0 NVIDIA 440.82

**Additional context**
 - Have reproduced with a CR2 and a JPEG
 - Have reproduced with an empty/new config-dir
 - This bug has been present at least for the past few weeks

**Comment by elstoc** [comment]
I think this is just an issue with the image information module not updating correctly. I get this issue but if I exit darktable and reopen, the version number is correct.

**Comment by dtorop** [comment]
> I think this is just an issue with the image information module not updating correctly. I get this issue but if I exit darktable and reopen, the version number is correct.

Yes, I see that now as well. This is something I could look at fixing, but if there are others who have spent more time with that code, I'm also happy to hand it off.

**Comment by elstoc** [comment]
I'd just go for it if I were you.

**Comment by dtorop** [comment]
>  think this is just an issue with the image information module not updating correctly.

A helpful clue! It looks to be a cache issue. I'm working on a PR.

**Comment by elstoc** [comment]
That's what I thought. I've seen something like this before when working on import.

**Comment by dtorop** [comment]
I appreciate it...

I noticed a couple other odd things:
- The change timestamp was being unset on the original image, not the changed image. I'll fix this.
- When a newly exported image is loaded, it has no change timestamp. But when that image is duplicated "with same history stack", the change timestamp of the duplicate is automatically set when the original's history stack is pasted on. Hence it's possible to end up with two images, the original of which has no change timestamp, but a duplicate which does. This seems to me cosmetic & a corner case not worth fixing.
