### ISSUE TITLE
Tone Equalizer Mask slider labels reversed

### ISSUE THREAD

**Issue by pitbuster** [darktable-org/darktable#5675]
I noticed that the slider labels for **mask contrast compensation** and **mask exposure compensation** are reversed from what I recall, but the tooltips and the functionality is right (that is, If I move the top slider I change the exposure compensation, not the contrast)

![image](https://user-images.githubusercontent.com/650365/86170021-84b73680-bae8-11ea-80a9-a5241f91c0f6.png)

I am using the latest git version in Arch Linux.

**Comment by elstoc** [comment]
@dterrahe I think this might be another introspection issue

**Comment by TurboGit** [comment]
Fixed.
