### ISSUE TITLE
Circled arrow on crop-rotate menu aspect line no longer rotates image

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5682]
the icon displaying a circled arrow at the right end of the aspect line in the crop-rotate module no longer does a 90° rotation.

openSUSE Tumbleweed 20200628
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.1.0~git2405.08c1dcd75
OpenCL on 
i7 12-core 36GB

**Comment by elstoc** [comment]
This icon has never rotated the _image_ just the crop guides. 

I can't see the issue on 3.1.0+2405~g08c1dcd75 on ArchLinux. 

What aspect ratio are you using? Could you provide some more details of how to reproduce?

**Comment by ptilopteri** [comment]
> This icon has never rotated the _image_ just the crop guides.

Then I am mistaken and old memory has failed me :(

> I can't see the issue on 3.1.0+2405~g08c1dcd75 on ArchLinux.

same version compiled from git on openSUSE Tumbleweed.
 
> What aspect ratio are you using? Could you provide some more details of how to reproduce?

freehand or original 

I remember <right><click> on icon and being able to affect 90° left or right

if my memory is wrong, I will or you can close this issue.

**Comment by elstoc** [comment]
The orientation module allows you to rotate the image 90 degrees left/right - perhaps that's what you're thinking of. With the crop&rotate module you can flip the image (mirror) using the 'flip' drop-down. You can rotate the image but you'd need to use the 'angle' slider' to do that.

The icon by the aspect drop-down should only change the orientation of the crop guides (portrait->landscape) and I wouldn't expect it to work for freehand - it should work for 'original' though.

Alas I don't have the power to close bugs but if you're happy with my explanation please close it yourself.

**Comment by ptilopteri** [comment]
must be misrememberedddd, closing
