### ISSUE TITLE
tone equalizer → add keyboard/mouse hints

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#5686]
Add keyboard/mouse hints (just like other modules do) on top of the image for tone equalizer module.

**Comment by hatsunearu** [comment]
What are the examples of "other modules"?

**Comment by timur-davletshin** [comment]
> What are the examples of "other modules"?

retouch after your click any instrument.

**Comment by hatsunearu** [comment]
I'm working on implementation. Any recommendations for what the text should be?

**Comment by timur-davletshin** [comment]
scroll to adjust exposure by 0.25 EV, shift+scroll by 1 EV, ctrl+scroll by 0.1 EV, press A while scrolling to zoom

**Comment by timur-davletshin** [comment]
https://youtu.be/UuB9khJIrDI?t=3255 — comes from here, btw.

**Comment by hatsunearu** [comment]
![image](https://user-images.githubusercontent.com/2360468/86405751-de9e3480-bc7f-11ea-8fde-66f56b70c326.png)
How does this look to you?

**Comment by timur-davletshin** [comment]
Looks fine to me. 
"scroll over image to ..." — check other strings, probably they need to be fixed too.

**Comment by timur-davletshin** [comment]
"scroll over image to ..." — I'm fine with both, but IMHO they should be unified.
