### ISSUE TITLE
Duplicating an image/.XMP results in an SQL error

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5696]
I was trying the duplicate facility.  I think I clicked on "create duplicate with same stack" in darktable.  It created the filename_01.CR2.xmp and there was no obvious problem in dt gui, but the Terminal window had this -

paulssd2@shovel2:~$ $HOME/DT-Mast-9Jun20/bin/darktable --cachedir $HOME/.cache/darktable-9jun --configdir $HOME/.config/darktable-9jun

[export_job] exported to `/mnt/b3fa3123-84fd-4cfc-97a8-567e75014d9a/Data/CR2 Store/2020_05_20-Queens-Road-walk-TIDIED/_5D_02396-soldier1-V1-S-sRGB.jpg'

sqlite3 error: /home/paulssd2/DT-Mast-9Jun20/darktable-code/src/common/image.c:868, function dt_image_duplicate_with_version(), query "INSERT INTO main.tagged_images (imgid, tagid, position)  SELECT ?1, tagid,         (SELECT (IFNULL(MAX(position),0) & 0xFFFFFFFF00000000)         FROM main.tagged_images)         + (ROW_NUMBER() OVER (ORDER BY imgid) << 32) FROM main.tagged_images AS ti WHERE imgid = ?2": near "OVER": syntax error

sqlite3 error: /home/paulssd2/DT-Mast-9Jun20/darktable-code/src/common/image.c:869, function dt_image_duplicate_with_version(): near "OVER": syntax error

sqlite3 error: /home/paulssd2/DT-Mast-9Jun20/darktable-code/src/common/image.c:870, function dt_image_duplicate_with_version(): near "OVER": syntax error

[export_job] exported to `/mnt/b3fa3123-84fd-4cfc-97a8-567e75014d9a/Data/CR2 Store/2020_05_20-Queens-Road-walk-TIDIED/_5D_02396-soldier2dark-V1-S-sRGB.jpg'

Blank lines added for clarity.

dt 3.1.0+2017~ga6c18e1b7-dirty       Ubuntu 18.04      i7  32Gb    no vid card

**Comment by phweyland** [comment]
This is an SQL version issue (ubuntu 18 one is a bit old).

**Comment by jenshannoschwalm** [comment]
Shouldn't we have a version dependency for sqlite in that case?

**Comment by phweyland** [comment]
> Shouldn't we have a version dependency for sqlite in that case?

sure, we should. I have already made some fallback treatment for history hash.  Should be done also here... Looking at it.

**Comment by RawConvert** [comment]
Not well up on this, not sure what fallback treatment is.  Is Ubuntu 18 not supported anymore?  That would seem a shame!

**Comment by phweyland** [comment]
> not sure what fallback treatment is

if I remember well Ubuntu 18 has sqlite 3.15. This is also the minimum to build dt.
However some interesting sql functions are missing. To support Ubuntu 18, it is necessary to provide some code which simulate those functions with sqlite 3.15 (what I've called fallback treatment). 
This said I'm not sure to succeed in doing that... In that case the minimum sqlite version could become 3.24.

**Comment by RawConvert** [comment]
Thanks for the info, I see, and wish you success!
Is there a "policy" around how long dt works with any given Ubuntu version?  (I think I read somewhere Ubuntu is by far the most used flavour of linux)
