### ISSUE TITLE
Support for Panasonic Lumix S1H

### ISSUE THREAD

**Issue by houz** [darktable-org/darktable#5698]
Hi,

it would be terrific if you could add support for the S1H to rawspeed. If you need any sample shots just tell me.

**Comment by LebedevRI** [comment]
As discussed in IRC, a brighter sample will be great, otherwise the crop might end up being wrong.

**Comment by houz** [comment]
I added 6 samples (one for each aspect ratio mode).

**Comment by LebedevRI** [comment]
Thank you for the contribution.

**Comment by LebedevRI** [comment]
Thanks. I don't feel like updating rs submodule just yet, so for the moment you'll need to ensure that you checkout `develop` branch of in `src/external/rawspeed` submodule.
