### ISSUE TITLE
Can't use lua plugin because ~/.config/darktable/luarc file gets moved to ~/.config/darktable/luarc.old

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#5700]
I can't use the dtMediaWiki plugin because the luarc file is backed up whenever I start darktable.

Steps to reproduce:
```
[trougnouf@d]: ~>$ ls .config/darktable/luarc*
.config/darktable/luarc  .config/darktable/luarc.old
[trougnouf@d]: ~>$ cat .config/darktable/luarc
require "contrib/dtMediaWiki/dtMediaWiki"
[trougnouf@d]: ~>$ darktable -d lua
7.445196 LUA ERROR : cannot open /home/trougnouf/.config/darktable/luarc: No such file or directory
[trougnouf@d]: ~>$ ls .config/darktable/luarc*
.config/darktable/luarc.old
```
Noticed with darktable 3.1.0+2422~gfe371fc65

**Comment by trougnouf** [comment]
I can safely add dtMediaWiki to the luarc file after I run the new script manager. Not sure if this is desired behavior and whether/how I should update the dtMediaWiki documentation and/or repository. @wpferguson

**Comment by wpferguson** [comment]
@trougnouf have you been building from source for awhile and this just now happened, or is this the first time you've built from source in awhile?

Are your lua scripts installed in ~/.config/darktable/lua ?

The way it's supposed to work, :-), is:

a check is done for the ~/.config/darktable/lua directory.  If it doesn't exist, then I back up the luarc file, build the widgets, show the module, etc.

If the ~/.config/darktable/lua directory is there, then I do nothing.  And, it doesn't actually have to be a directory.  My is a link to where I have the scripts installed.

All that being said, I'm not sure why I thought I had to backup the luarc file that early in the script.  I'll move it down to where I'm actually doing the script install.  That way if you select "don't show again" then it wont mess up what you already have installed.

Another question.  Does script_manager automatically pick up contrib/dtMediaWiki/dtMediaWiki?  It should show up under contrib if it does.

**Comment by wpferguson** [comment]
@trougnouf one more thing.  In the source tree the code is located in data/luarc.  If you've already built and installed, you can make changes to this file, then just re-run the install step to update it, if you want to do any debugging.

**Comment by wpferguson** [comment]
@trougnouf here is the updated data/luarc file.  Test it and see if it fixes the problem.  Thanks
[luarc.zip](https://github.com/darktable-org/darktable/files/4873425/luarc.zip)

**Comment by trougnouf** [comment]
Thank you @wpferguson !
The new /usr/share/darktable/luarc you provided does fix the overwritten local luarc, thank you !
The local luarc is overwritten once I run the script manager, but I guess that's normal.

dtMediaWiki is not picked up by the script manager. I think that's because I have it installed in /usr/share/darktable/lua/contrib/dtMediaWiki/dtMediaWiki.lua
Would it make sense to also detect plugins which are installed in the standard installation directory?
I install them systemwide on Arch with AUR / the package manager, I guess it doesn't make much sense to keep https://aur.archlinux.org/packages/darktable-lua-scripts-git/ since there is now a built-in plugin manager, but other plugins like https://aur.archlinux.org/packages/darktable-plugin-dtmediawiki-git/ are still most easily installed/updated that way.

**Comment by wpferguson** [comment]
When the script installer was renaming the luarc file, was there a lua directory, or was it named something else?  I'm trying to figure out why your lua scripts weren't detected.

I tried to set up the scripts installer so that if you already had an existing lua directory, it wouldn't run.  If it did run, because I didn't detect anything named lua in the config directory, then it still gives the option to just not show it again so it doesn't do anything and doesn't come back.  This option is for people that already have script installations that work for them, or people that just aren't interested in the scripts.  

If the user chooses to install the scripts, then the luarc file gets created, but I try and back up any existing luarc file just in case.

I don't have a good way to install scripts from outside sources.  script_manager has a provision for a download directory, stemming from the problem of dynamically updating stack objects.  That limitation has been fixed, but I haven't revisited script_manager and tried a better solution.  I should probably do that before 3.2 comes out :-D

**Comment by wpferguson** [comment]
@trougnouf I just added dtMediaWiki to contrib.  script_manager picked it up.  I managed to start it, but it hung darktable.  I'm guessing the hang was because the preferences weren't initialized.  The second time I started darktable, with dtMediaWiki enabled, it didn't hang.

I also got an entry for the mediawikiapi lilbary.    If it was in a lib subdirectory under the dtMediaWiki subdirectory script_manager would just ignore it.

**Comment by wpferguson** [comment]
I looked at the AUR packages and read the PKGBUILD instructions.  The scripts are being installed in /usr/share/darktable/lua, which is why I didn't detect them.

**Comment by trougnouf** [comment]
I didn't have a ~/.config/darktable/lua/ directory prior to running the script_manager, just a ~/.config/darktable/luarc file and a /usr/share/darktable/lua/ directory, the latter is installed through the PKGBUILD as you mentioned.

Would it make sense (and be a straightforward addition to your script) to check the system lua directory as well as the user lua directory for existing plugins and allow enabling/disabling those too?

**Comment by wpferguson** [comment]
In my opinion the (prefix dir)/share/darktable/lua directory should be kept for darktable extensions to the API such as darktable/debug and user scripts shouldn't be mixed in.  The darktable-lua-scripts package was a solution for an easier way to install the scripts, but it depends on darktable being installed in /usr.  If darktable is installed anywhere else, i.e. /opt, then the package doesn't solve help.  

When 3.2 is released, there will b an easy solution for getting the scripts that works no matter where your darktable is installed.  At that point, you could maintain the darktable-lua-scripts package for awhile and then deprecate it.

That still leaves the problem of dtMediaWiki.  First let me apologize.  Last year was a very rough one for me in real life, so I wasn't able to spend much time on the lua scripts pull requests.  In late December the situation was finally resolved and I had time for other things.  And now I must apologize again.  I thought I had commented on the code, but I just looked and didn't find any comments.  So, I will look at the PR and comment on the code and we'll see if we can get this PR merged.

I've thought about a way  to install other repositories/scripts with script_manager.  git is pretty forgiving about having extra files and extra directories, as long as you don't disturb any files under it's control.  So, using my dt-extra-lua-scripts repository for an example, script_manager could provide an interface that would take a directory name (wpferguson) and a repository (https://github.com/wpferguson/extra-dt-lua-scripts), create the directory in the lua-scripts directory then clone the repository into it.  This would add a wpferguson category with the extra scripts under it.

**Comment by trougnouf** [comment]
No worry, I look forward to a more convenient solution (like the last one you last mentioned) but I'm not expecting any kind of fast support.
The current way to install dtmediawiki (git clone or PKGBUILD then edit luarc) works with your fix, and it's served the ⩽handful of users well.
Thank you for your work.
