### ISSUE TITLE
duplicate module: size/position issues when images have different crops

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5701]
With a fresh install and after deleting my cache, I'm using the duplicate module (for the first time in this session) with two duplicate images that have different crops. The normal darkroom preview:

![Screenshot_2020-07-04_22-03-03](https://user-images.githubusercontent.com/9555491/86520969-70ee3600-be42-11ea-92eb-dbd7dabc9448.png)

Clicking on the duplicate image:

![Screenshot_2020-07-04_22-03-20](https://user-images.githubusercontent.com/9555491/86520977-882d2380-be42-11ea-8f4f-4a56265641d5.png)

I had a similar issue before (#5664) that only seemed to occur when I showed then hid the right hand side panel.

The deciding factor here seems to be that the two images have a different crop. If I start with the image that has the larger crop loaded in the darkroom it works fine but not the other way around. I would expect both images to fill the available width or height.

**Comment by elstoc** [comment]
Looks to me like there's an inbuilt assumption in ``gui_post_expose`` that the duplicate will have the same dimensions as the current previewed image.

**Comment by AlicVB** [comment]
confirmed.
In fact, it comes from the fact that in case of images with different ratios, the duplicate will always be shown in "zoom to fit" size, regardless of the zoom/position of the current image.
But we have somehow "half-forgot" this case in last change...

I'll have a look
