### ISSUE TITLE
Scrolbar in Lighttable cannot be moved by mouse

### ISSUE THREAD

**Issue by themightyoarfish** [darktable-org/darktable#5716]
**Version**: 2.4.2-1

**Describe the bug**
The scrollbar at the right, which moves when mouse-wheel scrolling through the images, cannot be moved with the mouse by grabbing the slider. This makes traversing large libraries impossibly slow.

**To Reproduce**
* Go to Lighttable
* Attempt to grab slider of scrollbar (very small on 4k display)
* Observe as the drawer opens/closes, but scrollbar slider is not affected

**Expected behavior**
Scrollbar slider is grabbable and can be positioned with the mouse.

**Screenshots**

![Screenshot from 2020-07-07 09-30-30@2x](https://user-images.githubusercontent.com/11613312/86737394-8cb92e00-c034-11ea-9bbe-3af51937b4e0.png)

**Platform (please complete the following information):**
 - Darktable Version: 2.4.2-1
 - OS: elementaryOS Hera (based on Ubuntu Bionic)
 - OpenCL: Yes
 - RTX 2070 Super (435.21)

**Comment by AlicVB** [comment]
version 2.4 is quite old and not maintained anymore. You may want to install 3.0 or wait a little bit and install 3.2 once it's out, in august.

tested in current master (which will be 3.2 soon) and everything works well, so I'm closing...
