### ISSUE TITLE
white balance: temperature/tint adjustment interlock

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#5725]
**Describe the bug**
For certain temperature/tint combinations in the white balance module, adjusting temperature will alter the tint slider. Successive temperature adjustments can cause tint to wander.

**To Reproduce**
1. Open an image in darkroom view
2. Set tint to 1
3. Set temperature to 4000K
4. Tint will jump to 0.983, temperature to 3901K
5. Scroll temperature slider to bring temperature up by units of 10
6. When temperature passes 3960K, temperature will jump to 4072K, tint to 1.001
7. Control-click on temperature slider and move the fine-control adjustment back and forth across the 39xxK -> 40xxK gap
8. The tint will progressively increase/decrease

**Expected behavior**
Tint should remain invariant when temperature is altered.

**Platform (please complete the following information):**
- Darktable Version: 536df44ad9215c45d222cd40f65e80f009a4f9d9
- OS: Debian bullseye/sid, Gnome 3.36.3
- OpenCL activated: yes
- Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
- Nvidia GP104GLM [Quadro P4000 Mobile] (rev a1), OpenGL version string: 4.6.0 NVIDIA 440.82

**Additional context**
- 42284087d0db3e4521d43a628c8f78b44c963806 added a call to set the preset to "user modified" in both tint_callback() and temp_callback() in iop/temperature.c. This results in a call to gui_update_from_coeffs() which recalculates temp/tint via temperature_to_XYZ() which may have a discontinuity at 4000K. A solution may be to not call gui_update_from_coeffs() in apply_preset() when the new preset is "user modified".
- I can reproduce this either a raw file or a JPEG
- I can reproduce this with a fresh edit (no history)
- I can reproduce this with empty/new config dir

**Comment by johnny-bit** [comment]
It's most likelly caused by switch from "blackbody radiation" formula to "daylight" formula of planckian locus approximation.

**Comment by TurboGit** [comment]
Cannot reproduce with current master. Probably fixed as part of the rework of the temperature module.
