### ISSUE TITLE
Do not clear "Search module" field when "new instance" is selected

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#5727]
**Is your feature request related to a problem? Please describe.**

I am always frustrated when the "Search module" field is cleared at a time when it still ought to be active.

I very often use the "Search module" field to quickly find a module.
Example: I enter  _equ_ and two modules are presented: 
_contrast equalizer_ and _tone equalizer_ (= correct; _equ_ is still shown in the search field = correct).

I do something in the _contrast equalizer_, and would like to invoke a second _contrast equalizer_. Now the _Search module_ field is cleared, and I have to enter _equ_ again to locate it.

**Describe the solution you'd like**

It is very good that the search field is cleared in other cases, but _not_ when a new instance is selected.

**Alternatives**

**Additional context**

**Comment by AxelG-DE** [comment]
Dear Claes, 

I am on current master and cannot confirm your situation. The search field did not get cleared (I exactly followed your way) and even if so, I just used contrast equalizer, from that module i can invoke a second instance from the leftmost button on the top right corner of the module.

![image](https://user-images.githubusercontent.com/49004103/87243975-be6a3480-c43a-11ea-9e29-3a7ae885de7d.png)

**Comment by ClaesGitHub** [comment]
Moin!

Please let me re-phrase the description of the problem (which still exists; I am using latest dev/git-version):
_Start position_
![a1](https://user-images.githubusercontent.com/19223977/87245079-c928c780-c442-11ea-8023-ddb7c068a17b.png)
I have entered _equ_ in the _search module_ field.
contrast equalizer and tone equalizer are shown. That is correct.

I click on the left-most button at upper right, and select new instance.
![a2](https://user-images.githubusercontent.com/19223977/87245200-ced2dd00-c443-11ea-95bc-229db51434a2.png)
Now the _search module_ field is cleared, and the equalizer modules are not shown any longer. I consider this as _not correct_ behaviour.

I have to manually enter _equ_ into the search module again, to be able to see/use the now two contrast equalizer modules. 
![a3](https://user-images.githubusercontent.com/19223977/87245288-85cf5880-c444-11ea-922c-7f877d0cca15.png)

**Comment by ClaesGitHub** [comment]
(sorry, clicked wrong button))

**Comment by AxelG-DE** [comment]
Dear Claes,

my apologies, seems I have replied too early.

I confirm your case. After really activating the next instance, the search field is cleared and the module disappeared (as I came from another group). I also consider this unfortunate :)

Cheers
 Axel

**Comment by ClaesGitHub** [comment]
Problem still exists in present git-master version,
i.e. darktable 3.3.0+25~gf25df97b6
