### ISSUE TITLE
fuji X-T4 "sports finder mode" produces unicolor (green, pink) borders

### ISSUE THREAD

**Issue by marco44** [darktable-org/darktable#5729]
This happens with git darktable from a few minutes ago.

I don't really know what happens in this mode, it seems resolution is reduced to get higher performance, but the raw is not very well understood. Documentation says the image should be 4992 × 3328 pixels, darktable seems to think it's 6384x3348 . I presume the borders are these zones, it certainly looks like it.

I've put the RAW (and an XMP just to be sure) showing this here : https://marco44.duckdns.org/XT4_sports_mode.tar.gz

Please tell me what I can provide more. I think this should apply to XT3 too, as it also has this mode.

On a side note, it seems there is also something wrong on "normal" XT4 files, the last line of the produced jpeg has a green tint. If needed, I can open another issue, and provide another raw for this. It shows in the darkroom too...

Regards

**Comment by ClaesGitHub** [comment]
There is a discussion on pixls.us about this:
https://discuss.pixls.us/t/fujifilm-x-t3-raf-file-cropped/16754

**Comment by marco44** [comment]
Well, yes, this bug still exists in 3.2.1, thanks, robot ! :)

**Comment by jmg-duarte** [comment]
Hello everyone, when exporting I'm running into the same issue. The camera is a Fuji X100F.
This happens with and without borders, always on the picture edge.

## With borders
![image](https://user-images.githubusercontent.com/15343819/90318013-4903ef00-df25-11ea-83cc-7ff5f6d17556.png)

## Without borders
![image](https://user-images.githubusercontent.com/15343819/90318020-5620de00-df25-11ea-837e-efb80c5d5649.png)

**Comment by jmg-duarte** [comment]
Something else I just found is that the exported image is around 30 pixels larger, both on width and height.

**Comment by jmg-duarte** [comment]
And furthermore, this does not happen on Windows 10.
The version use was always 3.2.1 in Linux as well as Windows.
I can provide the `.raf` picture if necessary.

**Comment by johnny-bit** [comment]
@marco44 - One of the issues you've mentioned (green line at the bottom) might be related (a bit) to https://github.com/darktable-org/darktable/issues/8644

However in order to support "sports" mode, i think you'd have to submit raw files to raw.pixls.us and open a camera support issue that documents the fact that while camera IS supported, the sports mode requires different crop... Which might be problematic.

**Comment by kmilos** [comment]
@Ishiido Please upload the sport mode X-T5 sample to https://raw.pixls.us/

**Comment by Ishiido** [comment]
I did. Thanks!

**Comment by kmilos** [comment]
Thanks for the sample. @LebedevRI According to the manual, the "sport finder mode" introduces a ~1.29x crop on a few of these models, which seems to affect the readout of the sensor.

**Comment by LebedevRI** [comment]
Validated, thanks.

**Comment by kmilos** [comment]
Yep, another one of these "wish we had used vendor crop from metadata" cases:

![image](https://github.com/darktable-org/darktable/assets/4973094/e8ae1dc1-8026-41b7-8bc1-93238e0725c5)
