### ISSUE TITLE
Please add a repo for openSUSE Leap 15.2 on OBS.

### ISSUE THREAD

**Issue by silentcreek** [darktable-org/darktable#5731]
On openSUSE Leap 15.1, I used the darktable stable release packages from OBS: 
https://download.opensuse.org/repositories/graphics:/darktable/openSUSE_Leap_15.1/

Unfortunately, there's no repository for the new 15.2 release yet. Could you add it, please?

Thanks!

**Comment by ptilopteri** [comment]
The darktable developers do not maintain distribution packages.  You need to contact the obs maintainer for darktable and ask him to add a 15.2 repo.

Not sure but appears from email addrs in changelog that 
  Andreas Schneider <asn@cryptomilk.org>
is current maintainer, note: "appears"

I currently build from source but for master.  It is not hard.

**Comment by silentcreek** [comment]
Thanks for the clarification. I was under the impression that this repo was maintained by the darktable project because on the website in the section about OBS it says:

> For master **we** build for the following distributions because of missing required packages in older distributions: [...]

(and after the list of distributions, it lists the release channels)

I will give it a shot and contact Andreas Schneider then.
