### ISSUE TITLE
File number and infos should appear on the slides by default

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#5734]
As said in the title, this is not only confusing, but hard to see which file number is which, which star is rated and such.

Please put option to show this without mouse hover.

![Untitled](https://user-images.githubusercontent.com/2467520/87209815-97651300-c313-11ea-9101-c298cb6494cc.jpg)

**Comment by maboleth** [comment]
Sorry, stars can be shown, but I was unable to set file number and photo details to be shown without overlay.

**Comment by ptilopteri** [comment]
You have failed to supply the requested information when opening this issue so I do not know what version of dt or operating system you use, but:

There is an option in dt master to display:
  "permanent extended overlays"  
that includes the file name

It is in the "Star" icon in the group at upper right above the image thumbnails.
I am not sure what you refer to by "file number"

If this satisfies your "issue", please consider closing this report.

**Comment by Nilvus** [comment]
To complete @ptilopteri, when posting an issue, please consider all what Is asked (darktable release, OS you use, etc.). As I can see (not easy on your screenshot), you use 3.0.2. On next release, 3.2, coming in a month, there will be different overlays options options. So all this will be fix.

So as your issue is fixed and there will be no new update to 3.0.x release, please close this issue.

**Comment by Nilvus** [comment]
Last thing, consider that all the UI will be drastically improved on next 3.2 release. So for UI glitches you can see, just wait to test 3.2 when it will be released.

**Comment by maboleth** [comment]
Alright guys, thanks. Sorry for my incomplete post, I was writing it late in the night.

Yes, I'm using 3.o.2, Arch linux. I still didn't find that "permanent extended overlays" what ptilopteri said, but oh well, can't wait for 3.2! By file name I thought about well - file name, e.g. _V0315.CR2. 

So far that Star, "permanent extended overlay" only displays star ratings and NOT file info or file name. That's displayed when I hover files with a mouse. I'm glad this will be fixed in 3..2.

**Comment by Nilvus** [comment]
> Alright guys, thanks. Sorry for my incomplete post, I was writing it late in the night.
> 
> Yes, I'm using 3.o.2, Arch linux. I still didn't find that "permanent extended overlays" what ptilopteri said, but oh well, can't wait for 3.2! By file name I thought about well - file name, e.g. _V0315.CR2.

It's in dt master as @ptilopteri, and so will be in next 3.2. So you can't find that on 3.0.2.

**Comment by Nilvus** [comment]
> So far that Star, "permanent extended overlay" only displays star ratings and NOT file info or file name. That's displayed when I hover files with a mouse. I'm glad this will be fixed in 3..2.

On master (and so next 3.2), you have seven overlays modes, displaying infos in different ways. Just test them all to see which on suit more what you like.
