### ISSUE TITLE
extract_wb.py tool crashes on Windows

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#5743]
**Describe the bug**

The extract_wb.py tool does not run on native Windows Python (mingw-w64 nor Anaconda), while it works w/ the POSIX emulation layer (msys2 Python, and probably Cygwin).

**To Reproduce**
Run e.g. `python extract_wb.py _DSC0001.NEF` from a native Windows shell (e.g. Anaconda or mingw-w64).

**Expected behavior**
White balance preset is printed on stdout

**Screenshots**
```
Traceback (most recent call last):
  File "C:/msys64/home/kmilos/darktable/tools/extract_wb.py", line 115, in <module>
    proc = subprocess.check_output(command, universal_newlines=True)
  File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:/msys64/mingw64/lib/python3.8/subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Platform (please complete the following information):**
 - Darktable Version: N/A
 - OS: Windows 10

**Comment by johnny-bit** [comment]
Currently extract_wb.py requires `exiftool` available on PATH and named exactly `exiftool`. so even if you have exiftool on windows, it's most likelly to be named `exiftool.exe` and results in `FileNotFound` error.

as I don't have windows the "fix" might be simple, but I have no way of testing it.

**Comment by kmilos** [comment]
Don't think that's it - I've installed exiftool inside msys2 as a perl package:

```
$ which exiftool
/usr/bin/site_perl/exiftool
```

**Comment by johnny-bit** [comment]
before line 115 in extract_wb.py insert
```python
print(command)
```

now you say you installed it in msys2, but have you installed it in a way that would be visible for native windows python? because you've said that the tool works under msys2 but doesn't for native windows python.

**Comment by kmilos** [comment]
I think I got it now: the msys2 shell and python w/ exiftool installed as perl module just work like any POSIX system; although the native mingw64 bash sees the perl variant of the exiftool and I can run it from that shell, when the [native mingw64 python spawns a subprocess it uses the native CreateProcess() Windows API](https://docs.python.org/3/library/subprocess.html#popen-constructor) which a) doesn't inherit the environment of the mingw64 bash (it's starts a new Windows process), and b) is certainly not able to interpret any perl scripts either...

Installing exiftool.exe in e.g. C:\Windows works for both native mingw64 python and Anaconda python now.
