### ISSUE TITLE
Add toggle button for focus peaking

### ISSUE THREAD

**Issue by Egocentrix** [darktable-org/darktable#5748]
Currently the focus peaking mode is accessible with ctrl+shift+f by default. I have read some stories from people who have accidentally enabled it and don't know what has happened, and I think the lack of a visual cue that a certain mode has been enabled would help a lot.

The point of this issue is not to complain and it certainly shouldn't be high priority, it is not a problem for me personally, but to discuss whether this would improve darktable's usability.

My suggestion for a position is in the top bar, next to the overlay/group/settings icons, because those controls affect images in both the filmstrip and the lighttable. The bottom bar controls only affect the selected image (afaik) so putting a button there would be confusing I think.

**Comment by johnny-bit** [comment]
While that's a great idea, what icon could represent "focus peaking"?

**Comment by Egocentrix** [comment]
First thing that comes to mind is something like this that I stole off Flaticon: 
![image](https://user-images.githubusercontent.com/22617209/87454650-8f9fba00-c604-11ea-8685-c428dcee3830.png)

The problem that I have with that is that it implies that the button shows what _the camera tried to focus on_, not what _is actually in focus_. So yeah, I'll brainstorm a bit, and I'm very open to suggestions.

**Comment by aurelienpierre** [comment]
Right, I slacked on this one. I like the stigmometer (edit2).

**Comment by aurelienpierre** [comment]
On it, it's a coffee break project.

**Comment by Egocentrix** [comment]
> stigmometer
Hah, I learned a new word today!
