### ISSUE TITLE
Implement Library switching into the GUI

### ISSUE THREAD

**Issue by derchr** [darktable-org/darktable#5749]
**Is your feature request related to a problem? Please describe.**
By default, all photos get added to the same library. But there are many cases when a strict separation of catalogues/librarys is required. I think about a work and private library or something similar. In my case it's a library for normal photos and a completely separate library for all astrophotography.

**Describe the solution you'd like**
Separating catalogues is completely possible: just start darktable with the library flag and choose your second library:
`darktable --library <path_to_lib>` 
But this is not an option for the non-techie user. This user wants some kind of button "change library" or something like this. Also I had to dig though documentation to find out that switching librarys like this is even possible. The program should tell the user in any way that there is such an option.

**Alternatives**
I had no idea for a alternative solution. Feel free to discuss your alternative solution in the comments.

**Additional context**
Lightroom has a similar feature, but it handles catalogues a little bit differently in contrast to darktable.

**Comment by johnny-bit** [comment]
This got duplicated by #8613 but the newer one got more traction. In order to keep the effort _focused_ I'll close this one. Please watch #8613 instead.
