### ISSUE TITLE
Lua buttons don't ellipsize label

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#5759]
**Describe the bug**
Lua buttons don't ellipsize text when the containing panel is sized smaller.  Once the white space is compressed, the buttons are at a fixed width and the panel adds horizontal scrollbars.  The button behavior is not consistent with non lua buttons in the panels.

**To Reproduce**
Start darktable with script manager enabled.
Open script manager.
Size the panel until the script manager buttons are covered.  Notice other modules are covered too.  Notice the button labels did not ellipsize
Close the script manager module.  Notice other modules are now visible.

**Expected behavior**
Button labels should ellipsize when the panel size shrinks enough to intrude on the button label.

**Platform (please complete the following information):**
 - Darktable Version: all
 - OS: all

**Additional context**
This is probably the root cause of #5747

**Comment by junkyardsparkle** [comment]
Maybe not only button labels... I had a similar issue with a Lua module I use for adding manual lens information; there are two entry fields, each only needs to hold a few digits (f-number and focal length), but putting them together in a horizontal box increased the minimum panel width beyond what I wanted to use (the dreaded horizontal scrollbar). I ended up just removing the box and letting them stack vertically as a workaround, but might be nice if there was a maximum string length attribute for entry widgets.
