### ISSUE TITLE
Darktable 3.0.x: opencl broken with llvm-10 and clang-10

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#5761]
**Describe the bug**
Since some time ago Debian Sid has transitioned to llvm-10 and clang-10 which now also include opencl support. Apparently the opencl support code in darktable 3.0.x in some way behaves wrong when opencl support uses llvm-10 and clang-10. This is also the case for the darktable-3.0.2 prebuild in Debian repository. It is possible this is a Debian Sid related problem in which case I have reported the same issue upstream. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965178

**To Reproduce**
Have opencl support configured and start darktable

**Expected behavior**
darktable starts

**Screenshots**
$ darktable
: CommandLine Error: Option 'polly' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**
/opt/darktable-3-current/bin/darktable --version
this is darktable 3.0.2+9~g5ac2260e3
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.2
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled

cmake configure file:
-- The CXX compiler identification is GNU 9.3.0
-- The C compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenMP_C: -fopenmp (found suitable version "4.5", minimum required is "4.0") 
-- Found OpenMP_CXX: -fopenmp (found suitable version "4.5", minimum required is "4.0") 
-- Found OpenMP: TRUE (found suitable version "4.5", minimum required is "4.0")  
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST
-- Performing Test HAVE_OMP_FIRSTPRIVATE_WITH_CONST - Success
-- Performing Test IS_SUPPORTED_PLATFORM
-- Performing Test IS_SUPPORTED_PLATFORM - Success
-- Is the target platform supported: 1
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found little endian system. Good.
-- Performing Test _MSSE2
-- Performing Test _MSSE2 - Success
-- Building SSE2-optimized codepaths: ON
-- Performing Test C_COMPILER_UNDERSTANDS_-Wall
-- Performing Test C_COMPILER_UNDERSTANDS_-Wall - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wall
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wall - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat-security
-- Performing Test C_COMPILER_UNDERSTANDS_-Wformat-security - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat-security
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wformat-security - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wshadow
-- Performing Test C_COMPILER_UNDERSTANDS_-Wshadow - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wshadow
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wshadow - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wtype-limits
-- Performing Test C_COMPILER_UNDERSTANDS_-Wtype-limits - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wtype-limits
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wtype-limits - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wvla
-- Performing Test C_COMPILER_UNDERSTANDS_-Wvla - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wvla
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wvla - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wold-style-declaration
-- Performing Test C_COMPILER_UNDERSTANDS_-Wold-style-declaration - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wold-style-declaration
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wold-style-declaration - Failed
-- Performing Test C_COMPILER_UNDERSTANDS_-Wthread-safety
-- Performing Test C_COMPILER_UNDERSTANDS_-Wthread-safety - Failed
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wthread-safety
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wthread-safety - Failed
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-unknown-pragmas - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=varargs - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-format-truncation
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-format-truncation - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-format-truncation
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-format-truncation - Success
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Success
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Success
-- Looking for external programs
-- Found perl
-- Found intltool-merge
-- Found desktop-file-validate
-- Found LLVM 10.0.1
-- Found clang compiler - /usr/bin/clang-10
-- Found clang opencl-c.h header in /usr/lib/llvm-10/lib/clang/10.0.1/include
-- Will be able to test-compile OpenCL programs. Nice.
-- Found jsonschema
-- Found xsltproc
-- Found xmllint
-- All external programs found
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found msgfmt to convert .po file. Translation enabled
-- Performing Test RAWSPEED_CXX_DEBUG_INFO_FOR_AUTO_IS_SUPPORTED
-- Performing Test RAWSPEED_CXX_DEBUG_INFO_FOR_AUTO_IS_SUPPORTED - Success
-- Checking for -march=native support
-- Performing Test MARCHNATIVE
-- Performing Test MARCHNATIVE - Success
-- Checking for -march=native support - works
-- Checking for -std=c++14 support
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Checking for -std=c++14 support - works
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WALL
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WALL - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WEXTRA
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WCAST_QUAL
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WCAST_QUAL - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WEXTRA_SEMI
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WEXTRA_SEMI - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WFORMAT_2
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WFORMAT_2 - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WMISSING_PROTOTYPES
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WMISSING_PROTOTYPES - Failed
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WOLD_STYLE_CASTS
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WOLD_STYLE_CASTS - Failed
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WPOINTER_ARITH
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WPOINTER_ARITH - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WSTRICT_PROTOTYPES
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WSTRICT_PROTOTYPES - Failed
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WTRADITIONAL
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WTRADITIONAL - Failed
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WVLA
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WVLA - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WMISSING_FORMAT_ATTRIBUTE
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WMISSING_FORMAT_ATTRIBUTE - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WSUGGEST_ATTRIBUTE_FORMAT
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WSUGGEST_ATTRIBUTE_FORMAT - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WNO_UNUSED_PARAMETER
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WNO_UNUSED_PARAMETER - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WSTACK_USAGE_4096
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WSTACK_USAGE_4096 - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WFRAME_LARGER_THAN_4096
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WFRAME_LARGER_THAN_4096 - Success
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WLARGER_THAN_32768
-- Performing Test RAWSPEED_HAVE_CXX_FLAG_WLARGER_THAN_32768 - Success
-- Looking for OpenMP
-- Found OpenMP_C: -fopenmp (found suitable version "4.5", minimum required is "4.0") 
-- Found OpenMP_CXX: -fopenmp (found suitable version "4.5", minimum required is "4.0") 
-- Looking for OpenMP - found (system)
-- Looking for pugixml
-- Found Pugixml 1.10
-- Looking for pugixml - found (system)
-- Looking for JPEG
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Looking for JPEG - found
-- Looking for jpeg_mem_src
-- Looking for jpeg_mem_src - found
-- Looking for ZLIB
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.11") 
-- Looking for C++ include zlib.h
-- Looking for C++ include zlib.h - found
-- Check size of uLongf
-- Check size of uLongf - done
-- Looking for Z_OK
-- Looking for Z_OK - found
-- Checking prototype uncompress for HAVE_ZLIB_UNCOMPRESS_PROTOTYPE - True
-- Checking prototype zError for HAVE_ZLIB_ZERROR_PROTOTYPE - True
-- Looking for uncompress
-- Looking for uncompress - found
-- Looking for zError
-- Looking for zError - found
-- Looking for ZLIB - found (system)
-- Looking for malloc
-- Looking for malloc - found
-- Looking for free
-- Looking for free - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Performing Test HAVE_CXX_THREAD_LOCAL
-- Performing Test HAVE_CXX_THREAD_LOCAL - Success
-- Found XMLLINT: /usr/bin/xmllint  
-- The following features have been enabled:

 * OpenMP-based threading, used for parallelization of the library
 * XML reading, used for loading of data/cameras.xml
 * Lossy JPEG decoding, used for DNG Lossy JPEG compression decoding
 * ZLIB decoding, used for DNG Deflate compression decoding

-- The following OPTIONAL packages have been found:

 * LLVM (required version >= 10)
 * Gettext
 * XMLLINT, command line XML tool, <http://xmlsoft.org/>
   Used for validation of data/cameras.xml

-- The following RECOMMENDED packages have been found:

 * JPEG, free library for handling the JPEG image data format, implements a JPEG codec
   Used for decoding DNG Lossy JPEG compression
 * ZLIB (required version >= 1.2.11), software library used for data compression
   Used for decoding DNG Deflate compression

-- The following REQUIRED packages have been found:

 * OpenMP (required version >= 4.0), Open Multi-Processing, <https://www.openmp.org/>
   Used for parallelization of the library
 * Pugixml (required version >= 1.8), Light-weight, simple and fast XML parser, <http://pugixml.org/>
   Used for loading of data/cameras.xml

-- Performing Test COMPILER_SUPPORTS_C99
-- Performing Test COMPILER_SUPPORTS_C99 - Success
-- Performing Test COMPILER_SUPPORTS_C11
-- Performing Test COMPILER_SUPPORTS_C11 - Success
-- Checking for -std=c++14 support
-- Checking for -std=c++14 support - works
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Glib 2.64.4
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.20
-- Found GTK3: /usr/include/gtk-3.0;/usr/include/at-spi2-atk/2.0;/usr/include/at-spi-2.0;/usr/include/dbus-1.0;/usr/lib/x86_64-linux-gnu/dbus-1.0/include;/usr/include/gtk-3.0;/usr/include/gio-unix-2.0;/usr/include/cairo;/usr/include/pango-1.0;/usr/include/fribidi;/usr/include/harfbuzz;/usr/include/atk-1.0;/usr/include/cairo;/usr/include/pixman-1;/usr/include/uuid;/usr/include/freetype2;/usr/include/libpng16;/usr/include/gdk-pixbuf-2.0;/usr/include/libmount;/usr/include/blkid;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include (Required is at least version "3.22") 
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found suitable version "2.9.10", minimum required is "2.6") 
-- Checking for one of the modules 'libsoup-2.4;libsoup2'
-- Checking for one of the modules 'libsoup-2.2;libsoup2'
-- Found GPHOTO2: /usr/lib/x86_64-linux-gnu/libgphoto2.so  
-- Found OPENEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so;/usr/lib/x86_64-linux-gnu/libImath.so;/usr/lib/x86_64-linux-gnu/libIex.so;/usr/lib/x86_64-linux-gnu/libIlmThread.so  
-- Found WEBP: /usr/lib/x86_64-linux-gnu/libwebp.so (Required is at least version "0.3.0") 
-- Found LENSFUN: /usr/lib/x86_64-linux-gnu/liblensfun.so  
-- Found GIO 
-- Found GThread: /usr/lib/x86_64-linux-gnu/libgthread-2.0.so  
-- Found GModule: /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so  
-- Found PANGOCAIRO: /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  
-- Found RSVG2: /usr/lib/x86_64-linux-gnu/librsvg-2.so  
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.10") 
-- Found Sqlite3 3.32.3
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.68.0")  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.1.0") 
-- Found LCMS2: /usr/lib/x86_64-linux-gnu/liblcms2.so  
-- Found JsonGlib 
-- Found EXIV2: /usr/lib/x86_64-linux-gnu/libexiv2.so  
-- Found FLICKCURL: /usr/lib/x86_64-linux-gnu/libflickcurl.so  
-- Found OpenJPEG 
-- Checking for module 'iso-codes'
--   Found iso-codes, version 4.5.0
-- Found LIBSECRET: /usr/include/libsecret-1;/usr/include/libmount;/usr/include/blkid;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include  
-- Found GraphicsMagick 
-- GMIC not found
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
-- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Success
-- Does the compiler support __builtin_cpu_supports(): 1
-- Performing Test HAVE_TLS
-- Performing Test HAVE_TLS - Success
-- Checking for one of the modules 'lua53;lua5.3;lua-5.3;lua'
-- Lua support: Enabled
-- Found Pugixml 1.10
-- Map mode: enabled
-- Found Cups: /usr/lib/x86_64-linux-gnu/libcups.so (found version "2.3.3") 
-- Print mode: enabled
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found suitable version "7.68.0", minimum required is "7.56")  
-- Found recent CURL version to build piwigo.
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- building darktable-cmstest with colord support. nice.
-- 
-- Found Java: /usr/lib/jvm/default-java/bin/java (found version "11.0.7") found components: Runtime 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mir/git/darktable/build

**Comment by parafin** [comment]
This is a problem with opencl driver and has nothing to do with darktable. darktable doesn't care which llvm is used by opencl (llvm is used only for test compilation of opencl kernels and in no way required for opencl support or used in runtime).

**Comment by mir07** [comment]
I have solved the problem. Many thanks for your help.

Solution:
apt purge nvidia-opencl-common libnvidia-compiler
nvidia-opencl-icd:amd64 ocl-icd-opencl-dev:amd64
ocl-icd-opencl-dev:amd64 opencl-c-headers opencl-clhpp-headers

apt install nvidia-opencl-common nvidia-opencl-icd
