### ISSUE TITLE
crop & rotate hangs when aspect is rotated

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#5763]
**Describe the bug**
when rotating aspect in crop dialog darktable hangs
 
**To Reproduce**
open mire1.cr2
1. open in darkroom and select crop&rotate
2. switch aspect to "35:45" (by right click and typing)
--> [mire1.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/4938555/mire1.cr2.xmp.txt)
3. click on rotate aspect icon
4. darktable hangs

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+2468~gbbc31c18b
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
 - OS: OSX

**Comment by elstoc** [comment]
Reproduced on ArchLinux 3.1.0+2444~g536df44ad. Appears to work fine if you select an aspect ratio from the drop-down but not so much if you key one directly.

**Comment by TurboGit** [comment]
I cannot reproduce on master!

**Comment by MStraeten** [comment]
just built current master on osx - found it reproducible if the image is rotated into portrait mode before crop&rotate

**Comment by MStraeten** [comment]
further findings: selecting the aspect 8,5:11 from the dropDown list is fine, after entering 8,5:11 manually negative values are displayed:
![aspect-negative values](https://user-images.githubusercontent.com/39386816/87860170-9fd4d380-c93b-11ea-8cf0-41a0f7b690f9.jpg)
and darktable hangs on leaving the module

**Comment by MStraeten** [comment]
some stuff from the debugger:
```
Process 48837 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x000000012275afb5 libclipping.so`aspect_presets_changed(combo=0x000000010dc1cb10, self=0x000000010b68aa00) at clipping.c:1734:17 [opt]
   1731	      while(nn != dd)
   1732	      {
   1733	        if(nn % 2 == 0) nn /= 2;
-> 1734	        else if(dd % 2 == 0) dd /= 2;
   1735	        else if(nn > dd) nn = (nn - dd) / 2;
   1736	        else dd = (dd - nn) / 2;
   1737	      }
Target 0: (darktable) stopped.
```
```
(lldb) frame variable
(GtkWidget *) combo = 0x000000010dc1cb10
(dt_iop_module_t *) self = 0x000000010b68aa00
(dt_iop_clipping_params_t *) p = 0x00000001233efdd0
(dt_iop_clipping_gui_data_t *) g = <variable not available>

(int) d = 8
(int) which = <variable not available>

(int) n = -11
(const char *) text = <variable not available>

(int) act = <variable not available>

(int) i = <variable not available>

(GList *) iter = <variable not available>

(const char *) c = <variable not available>

(const char *) end = <variable not available>

(int) nn = -11
(int) e = 0
(int) dd = 10

```
(some steps later) 

```
(lldb) frame variable
(GtkWidget *) combo = 0x000000010dc1cb10
(dt_iop_module_t *) self = 0x000000010b68aa00
(dt_iop_clipping_params_t *) p = 0x00000001233efdd0
(dt_iop_clipping_gui_data_t *) g = <variable not available>

(int) d = 8
(int) which = <variable not available>

(int) n = -11
(const char *) text = <variable not available>

(int) act = <variable not available>

(int) i = <variable not available>

(GList *) iter = <variable not available>

(const char *) c = <variable not available>

(const char *) end = <variable not available>

(int) nn = -11
(int) e = 0
(int) dd = 5
(lldb)
```

**Comment by pitbuster** [comment]
From https://github.com/darktable-org/darktable/blob/84ea0a3ee727f05a5e5dbe994d27cf75d7c2ba01/src/iop/clipping.c#L1638, when you enter a ratio manually in "a:b" format, it expects to have a and b as integers.

**Comment by MStraeten** [comment]
Same if 35:45 is entered. When 8.5 or 8,5 is entered only the integer part is used

**Comment by MStraeten** [comment]
further side of the bug:
if the ratio is defined in darktablerc by `plugins/darkroom/clipping/extra_aspect_ratios/3.5x4.5=35:45` and then assigned, it's fine. If the line is deleted from darktablerc darktable hangs when processing crop&rotate again.
So it seems there's an issue on dealing with manual aspect ratios

**Comment by TurboGit** [comment]
@MStraeten : A nasty one, I have finally be able to reproduce, can you double check that #5771 fixes this issue?

@elstoc : You also have reproduced, so if you can test this on your side it would be nice.

**Comment by MStraeten** [comment]
ok it doesn’t longer hang, but there's a new issue (only for manual aspects):
after selecting a manual aspect ratio i can rotate it by clicking the icon --> ok.
when i leave the module and enter it again, i'm not able to rotate it. 
and the ratio is displayed as a negative value

**Comment by aurelienpierre** [comment]
There is a fishy way to deal internally with orientation, with a proper orientation variable AND with the sign of the vertical aspect ratio. I think this module will need a complete rewrite anyway.

**Comment by elstoc** [comment]
Agreed.

**Comment by TurboGit** [comment]
@MStraeten @elstoc : can you test with #5773 ? Should fix the latest issue... Hopefully this will be "ok" for 3.2! Thanks.

**Comment by elstoc** [comment]
Looks good to me. It's a shame that the ratio looks so silly when you manually key in a float (e.g. 1.29 is the same as 9:7 but when you type 1.29 directly it comes out as, for example, 169083:131072) but that's a separate issue.

Latest commit seems to have fixed all of the issues I had with the #5771.

**Comment by MStraeten** [comment]
fixed, thanks

**Comment by MStraeten** [comment]
Closed since already fixed and merged
