### ISSUE TITLE
scrollbar doesn't reset to the top position after attaching a tag

### ISSUE THREAD

**Issue by mox601** [darktable-org/darktable#5768]
**Is your feature request related to a problem? Please describe.**
When attaching one of the tags in the tagging module with suggestion, after I double click, the tag is removed from the list and the scrollbar is reset to the top. 
In this way, I need to re-scroll down to attach a tags that was next to previous one. 

In a tagging window with lots of tags (let's say ~20)
1. Scroll down to tag 7
2. Double click on tag 7
3. Tag 7 is removed from the list of tags
4. The scroll bar resets to the top
5. I need to scroll down again to attach tag 8

Before clicking on 7
<img width="263" alt="Screenshot 2020-07-19 at 12 36 57" src="https://user-images.githubusercontent.com/11626/88314228-e39d5380-cd14-11ea-859b-190274b7128a.png">

After clicking on 7
<img width="259" alt="Screenshot 2020-07-19 at 12 37 08" src="https://user-images.githubusercontent.com/11626/88314251-eac46180-cd14-11ea-80fe-3e9993a83957.png">

**Describe the solution you'd like**
In my opinion, the scroll bar shouldn't move to the top after attaching a tag. In this way it would be easier to consecutively attach adjacent tags 18 and 19. 
It would be also more consistent with the tagging module without suggestion, where the tag is not removed and the scrollbar is not reset to the top position. 

**Details**
OS: mac OS Catalina 10.15.5 (19F101)
darktable version: 3.0.2

PS: Thanks for developing Darktable!

**Comment by Nilvus** [comment]
When you create, some useful infos are asked, let's say for example, which OS you use and which darktable version you use (precise one). Just tested for example on last master (so next 3.2) and I can't reproduce.

**Comment by phweyland** [comment]
From your screenshot I can see you use the suggestion view. That means that after attaching your tag, dt recalculates the most probable tags from database. There is no way to predict where should be the cursor afterwards.
You may want to try the list view (+ disabled) or the tree view. In both cases the current tag doesn't disappear and the cursor stays in place.

**Comment by mox601** [comment]
You're right! Thanks for helping and sorry for the noise!
