### ISSUE TITLE
Crop & Rotate: Float / Ratio differences

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5774]
If I key 129:100 into the Crop & Rotate module, the aspect is displayed as follows:

![Screenshot_2020-07-19_21-12-24](https://user-images.githubusercontent.com/9555491/87884188-8fd4f680-ca04-11ea-896f-88c293e27215.png)

However, if I key 1.29 (the same thing) this results in a much different ratio:

![Screenshot_2020-07-19_21-13-14](https://user-images.githubusercontent.com/9555491/87884201-ac712e80-ca04-11ea-9f86-0781ab904373.png)

I would expect both of these actions to result in the aspect ratio displayed in the first screenshot

**Comment by TurboGit** [comment]
I'll try to fix this for 3.2 if not too difficult.

**Comment by elstoc** [comment]
Shouldn't be too hard since we have the number as a string already. Remove the decimal point by multiplying by factors of ten. There's already a function to simplify the resulting ratio.

**Comment by MStraeten** [comment]
the second scenario seems to be a result of an invalid entry. a format x:y is expected. even the decimal ratio is properly detected the simplifying function needs input in the x:y format

**Comment by TurboGit** [comment]
I have a fix. Will PR later.

**Comment by elstoc** [comment]
A decimal is allowed. It's just processed to a silly ratio because it's first converted to a float. It should be simple to convert any decimal (say 1.29 or 1.12345) into a ratio (129:100 or 112345:100000) and then run the simplification.

**Comment by TurboGit** [comment]
See #5777 for a fix. Again, so close from the release, I'll appreciate a test of this before merging. Thanks.
