### ISSUE TITLE
[FR] Introduce opening/closing darktable splashscreen

### ISSUE THREAD

**Issue by johnny-bit** [darktable-org/darktable#5782]
**Is your feature request related to a problem? Please describe.**

On my system, due to it's age, lack of ssd and so on opening up darktable takes roughly 3-5 seconds during which "nothing happens". Simirally when closing darktable, between main window "disappearing" on clicking "X" or via ctrl+q and actual exit there's delay of 0.5 - 2s.

**Describe the solution you'd like**

GIMP has nice opening splashscreen that informs user that the app is actually being launched, just has a bunch of setup to do. Similarly, some IDEs on closing have brief window appearing and explaining that stuff is being saved/optimized/compilled etc. If we could have something like that it would be great!

**Alternatives**

Obviously alternative could be something like showing up empty window on start and then update it to actual content, simirally on closing window could be slowly teared down with each interface freed... However that would probably look "broken" to some, similarly to "flash of unstyled content" problem with CSS on slow-performing sites.

**Additional context**

This came to mind when working on #5124 as "closing" experience on macos by iconifying main window is bad and not having clear indication of app still working while closing is a bit bad too.

**Comment by Nilvus** [comment]
Why not but Gimp splashscreen si not a way to go for me. Splashscreen is visually nice, but just too big.

**Comment by Nilvus** [comment]
Alternatives are not good way to. Splash screen is ok for me but a not too big one.

**Comment by darkelectron** [comment]
> Splash screen is ok for me but a not too big one.

Maybe something close to libreoffice's splash.
