### ISSUE TITLE
Style not applied first time through after launching dt

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#5788]
Launch dt, do Import | Image to open one raw file, hence darktable opens. Go back to lightroom, select the raw, double click a Style in the Styles module, dt says it's applied it, but the thumbnail hasn't changed, and going into darktable confirms the style has not been applied.
Go back to lighttable, apply style again same way, this time it is applied ok.

Ubuntu 18.04   dt 3.1.0+2440~g673f25287-dirty

**Comment by RawConvert** [comment]
Just tested with dt 3.2.1 release, appears fixed, thanks.

**Comment by ptilopteri** [comment]
@RawConvert 
consider closing issues you feel are corrected
