### ISSUE TITLE
Windows installer erroneously requires accepting the GPL

### ISSUE THREAD

**Issue by chris-morgan** [darktable-org/darktable#5792]
[From the text of the GPLv3:](https://www.gnu.org/licenses/gpl-3.0.en.html)

> 9. Acceptance Not Required for Having Copies.
>
> You are not required to accept this License in order to receive or run a copy of the Program. Ancillary propagation of a covered work occurring solely as a consequence of using peer-to-peer transmission to receive a copy likewise does not require acceptance. However, nothing other than this License grants you permission to propagate or modify any covered work. These actions infringe copyright if you do not accept this License. Therefore, by modifying or propagating a covered work, you indicate your acceptance of this License to do so.

And from clause 10:

> You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License.

Yet the Windows installer requires GPL acceptance, which would be such a restriction:

<img width=499 height=388 alt="Screenshot of the license agreement page of the darktable installer" src=https://user-images.githubusercontent.com/392868/88288111-ebf38f80-cd10-11ea-96d4-4a2708ced67d.png>

For reference, here’s what Inkscape did before its recent 1.0 release (which redid the installer and moved to Wix):

![Screenshot of the license agreement page of the Inkscape installer](https://user-images.githubusercontent.com/392868/65207439-f59ade00-dad4-11e9-9365-364b2536bd5f.png)

This was achieved with this NSIS code:

```nsis
!define MUI_LICENSEPAGE_BUTTON "$(^NextBtn)"
!define MUI_LICENSEPAGE_TEXT_BOTTOM "$(LICENSE_BOTTOM_TEXT)"
```

And in English.nsh:

```nsis
${LangFileString} LICENSE_BOTTOM_TEXT "$(^Name) is released under the GNU General Public License (GPL). The license is provided here for information purposes only. $_CLICK"
```

I figure this should transfer pretty well. I think cmake/modules/NSIS.template.in is the place. Not sure about the localised string though. I haven’t looked at all deeply.

**Comment by johnny-bit** [comment]
Hey,

does https://github.com/darktable-org/darktable/pull/9192 work for you?

**Comment by chris-morgan** [comment]
Looks good to me.

(As a matter of fact, I filed similar reports in a couple of other places and one pointed out that the [GPL FAQs say installers requiring accepting the GPL is OK](https://www.gnu.org/licenses/gpl-faq.html#ClickThrough), which I was unaware of. I disagree with them on the point, for the reasons stated in this issue, but since it’s FSF itself that is saying it I won’t be filing any more issues like this anywhere. But in any case, it’s certainly better to explicitly not require it.)
