### ISSUE TITLE
Bilateral denoise causes black areas in the picture

### ISSUE THREAD

**Issue by infjb** [darktable-org/darktable#5797]
Bilateral denoise causes more or less random black areas in the picture. The black areas differ in the darkroom view and the exported picture. They do not show up in the light table view.

The black areas are sometimes round an sometimes square or a mixture. They sometimes change when you zoom in or out of the picture.

It happens with version 3.1.0+2454~gf005c5235 on windows, compiled on windows using mingw64.

**Comment by parafin** [comment]
Does it happen with OpenCL enabled? If so, which GPU and is it reproducible with OpenCL disabled?

**Comment by infjb** [comment]
It happens with OpenCL enabled and disabled. And switching the filter off and on changes the pattern of the black areas.

**Comment by infjb** [comment]
The bilateral denoise worked fine in version  3.1.0+1031~g8e4d22171.

**Comment by chhil** [comment]
Its an old issue...

https://github.com/darktable-org/darktable/issues/4984

**Comment by parafin** [comment]
Closing as duplicate then.
