### ISSUE TITLE
EXIF_HOUR variable get wrong time zone when importing

### ISSUE THREAD

**Issue by mikaelstaldal** [darktable-org/darktable#5802]
When I use the EXIF_HOUR variable in File Naming Pattern in Session Options, the filename after import from camera is one hour ahead of what I see in the Image Information panel in Darktable.

My main time zone is CET+1, but currently CEST+2 (daylight saving time). My camera is configured with this.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Unbutu Linux 18.04

**Comment by phweyland** [comment]
> When I use the EXIF_HOUR variable in File Naming Pattern in Session Options, the filename after import from camera is one hour ahead of what I see in the Image Information panel in Darktable.

Do you see the same discrepancy in dt image information ?

I haven't found any exif summer time flag in exiv2 exif tags. So I assume the time delivered by the camera ("Exif.Image.DateTimeOriginal") should be the season corrected one.

**Comment by mikaelstaldal** [comment]
> Do you see the same discrepancy in dt image information ?

Not sure what your mean with _dt image information_, given that it should be different from the Image Information panel i Darktable.

**Comment by mikaelstaldal** [comment]
The time shown in Image Information panel i Darktable is correct, but the EXIF_HOUR variable is wrong (one hour ahead for me).

I suspect that either time zone or DST is applied wrongly on EXIF_HOUR.

**Comment by phweyland** [comment]
I've looked at the code. The source information for datetime in image information and for the variable $(EXIF_HOUR) is the same. I'm afraid I cannot explain the discrepancy you get.
Could you share the xmp of an image showing this defect ? I'll try to reproduce your issue.

**Comment by mikaelstaldal** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:darktable="http://darktable.sf.net/"
   exif:DateTimeOriginal="2020:08:02 13:50:54"
   xmp:Rating="5"
   xmpMM:DerivedFrom="20200802_145054.ARW"
   darktable:xmp_version="3"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="10"
   darktable:iop_order_version="5">
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Mikael Ståldal</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">binary comment</rdf:li>
    </rdf:Alt>
   </dc:description>
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="000000000000000008000000000000002003200320032003ac3f0000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="1.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="1"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="000019400000803f0000da3f0000c07f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="3.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="2"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="8.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="3"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="0c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="28.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="4"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="69.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="5"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="77.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="6"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="16.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="7"
      darktable:operation="bilat"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="010000000000003f0000003f0000803e0000003f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="53.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="8"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="9a991341cdcc28c1cdcc5c40000000009a999341000000000000c842295cbf40000034426666a63f0000a0400000404103000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="45.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
     <rdf:li
      darktable:num="9"
      darktable:operation="lens"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="3b000000000000009241803f52b82e405c8f1e410000804000007a44010000004453432d52583130304d354100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004453432d525831303020494949202620636f6d70617469626c65730000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f01000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:iop_order="13.0000000000000"
      darktable:blendop_version="9"
      darktable:blendop_params="00000000180000000000c84200000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f00000000000000000000803f0000803f0000000000000000000000000000000000000000000000000000000000000000"/>
    </rdf:Seq>
   </darktable:history>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>

**Comment by phweyland** [comment]
I'm afraid I need the raw file too.
dt reads my raw image file datetime instead of exif:DateTimeOriginal="2020:08:02 13:50:54"
in your xmp, which is normal, sorry.
Would you mind to share a faulty raw file and the associated xmp ?

**Comment by mikaelstaldal** [comment]
https://www.dropbox.com/s/b62ayyk007ykzps/20200802_145054.ARW?dl=0
https://www.dropbox.com/s/lfdcdha12obkkdz/20200802_145054.ARW.xmp?dl=0

**Comment by phweyland** [comment]
All good for me:

![image](https://user-images.githubusercontent.com/23012047/89222889-2fb98500-d5ac-11ea-8494-e53d73858df1.png)

**Comment by mikaelstaldal** [comment]
It is correct for me also when _exporting_. The problem occurs when _importing_.

**Comment by phweyland** [comment]
> It is correct for me also when _exporting_. The problem occurs when _importing_.

Ooops. Let me check again.

**Comment by phweyland** [comment]
Sorry, I'm not used to rename files when importing. 
I think the option only works when you import with "scan for devices". Is that correct ?
Then dt should follow the settings:
![image](https://user-images.githubusercontent.com/23012047/89453072-0d06a800-d735-11ea-9a77-27b4f9eb63f1.png)
If it is still correct, what is the string you use ?

**Comment by mikaelstaldal** [comment]
So you get one hour less, I get one hour more. Most likely a time zone issue.

**Comment by phweyland** [comment]
> So you get one hour less, I get one hour more. Most likely a time zone issue.

Could you share the string you use to build the filename please ?

**Comment by phweyland** [comment]
> Ok, I've reproduced the issue. I get 12 for $(EXIF_HOUR) in the imported name (instead of 13 as on the screenshot above).

My mistake. it was not your file. with your file I get 13 too with that string:
`$(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)-$(EXIF_HOUR):$(EXIF_MINUTE):$(EXIF_SECOND)_$(SEQUENCE).$(FILE_EXTENSION)`

Back to the correct behavior, isn't ?

![image](https://user-images.githubusercontent.com/23012047/89455928-7a1c3c80-d739-11ea-9c2a-65e25bbe0355.png)

**Comment by phweyland** [comment]
Here is the result of exiv2 against your file.
All the datetime values are coherent (2020:08:02 13:50:54) and I don't see any time zone info.

[20200802_145054.ARW.txt](https://github.com/darktable-org/darktable/files/5030822/20200802_145054.ARW.txt)

**Comment by mikaelstaldal** [comment]
I use this file naming pattern: `$(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)_$(EXIF_HOUR)$(EXIF_MINUTE)$(EXIF_SECOND).$(FILE_EXTENSION)`

**Comment by mikaelstaldal** [comment]
Yes, I use import from camera, from a "Mass Storage Camera".

**Comment by mikaelstaldal** [comment]
Is your computer set to CEST time zone?

**Comment by phweyland** [comment]
> Is your computer set to CEST time zone?

Brazilia time zone

**Comment by mikaelstaldal** [comment]
Do you have Daylight Savings Time? I do at the moment.

**Comment by phweyland** [comment]
> Do you have Daylight Savings Time?

No, winter time currently.
It is not normal that the current local time influences image taken time...
I'll try to find out this.

**Comment by phweyland** [comment]
I've followed the full import process. the variable expansion is the same as for exportation.

Maybe there is a difference in the way to process this.
I've copied your arw file to one of my camera memory card and connected this memory card to my computer.
Then I use the "import from camera" entry, select the arw image and click on import.
In that process I don't see how the computer time zone could interfere.




> Yes, I use import from camera, from a "Mass Storage Camera".

That's where I've a doubt. What is "Mass Storage Camera" ?

**Comment by mikaelstaldal** [comment]
Darktable says "Mass Storage Camera" when I connect my camera. I guess it means that it doesn't recognize my particular camera model (and cannot do tethering), and access my camera as a generic USB storage (or maybe PTP/MTP, not sure).

**Comment by ptilopteri** [comment]
it  means MPT rather than PTP

**Comment by phweyland** [comment]
![image](https://user-images.githubusercontent.com/23012047/89568529-d6df2c00-d7f9-11ea-9f36-137125284e98.png)

moving to ETC I get the issue on import time. export time still ok.

I think the guilty is sscanf(), used to decode the datetime, which may be locale dependent.
Other parts of code seem to use strftime(). 
Still some work to check that and ... not to create another issue.

**Comment by mikaelstaldal** [comment]
I can confirm that this bug is fixed.
