### ISSUE TITLE
documentation: font / dpi preferences

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5815]
**Which new feature or section need to be documented/updated**
Font and DPI setting in preferences.

**Comment by Nilvus** [comment]
@aurelienpierre and @elstoc: I don't know if you have planned or even began to work on preferences part of the manual. But if not, I've just began that work. I will also add infos for #5816.

**Comment by elstoc** [comment]
@Nilvus I have drafted some stuff on hackmd (https://hackmd.io/rvdBcDCaQrCoGVlZd3M-RQ) but I've not really got the time to get my head around the xml markup right now.

**Comment by Nilvus** [comment]
Thanks @elstoc. I completely rewrite actually preferences section, with a file per tab. If it's ok for you, I will add some of your work. I see for shortcuts and, of course, will not change them. You make great work on it. I'm just updating all remaining things for this section.
