### ISSUE TITLE
documentation: downsampling support

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#5818]
**Which new feature or section need to be documented/updated**
Added in 3.2 and should be documented.

**Comment by TurboGit** [comment]
@GrahamByrnes : Can you look at this? You can send the text as-is and I will integrate it if you don't feel like messing with the docbook files. TIA.

**Comment by GrahamByrnes** [comment]
I guess... is there something already written, ir am I starting from scratch?
If the former, where do I click to see it, if not, how long?
Cheers, G

**Comment by TurboGit** [comment]
I think we just want an addition into the darkrrom's preference description here:

https://darktable.gitlab.io/doc/en/preferences_chapter.html#gui_options_darkroom

I don't think we want to go into all the details as this is really only about user's documentation.

**Comment by GrahamByrnes** [comment]
PREVIEW DOWNSAMPLING

This reduces the resolution of the preview window at the upper-left of the screen. Consequently, calculations for re-drawing this window are reduced to 1/4, 1/9 or 1/16 of the main window. Sometimes coordinates for handles are borrowed from the preview, so it may rarely be useful to return to full scale.

**Comment by TurboGit** [comment]
Thanks, PR sent with some other updated.
