### ISSUE TITLE
libavif version requirement reversed

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5825]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by ptilopteri** [comment]
master build required /usr/lib64/libavif.so.4.0.1
changed to require /usr/lib64/libavif.so.5.0.0
and now again wants /usr/lib64/libavif.so.4.0.1

a simlink from /usr/lib64/libavif.so.5.0.0 to /usr/lib64/libavif.so.4.0.1
and /usr/lib64/libavif.so.5 to /usr/lib64/libavif.so.4
will satisfy this and complete the build

but why the reversion to a lessor version which has been replaced?

**Comment by parafin** [comment]
No idea what are you doing. Please describe how are you building dt and what are the exact error messages you get. Most likely it's some local build failure.

**Comment by ptilopteri** [comment]
ran: sudo cmake --build "./build" --target install -- -j12 && sudo -u paka /opt/darktable/bin/darktable --version

received:
-- Up-to-date: /opt/darktable/share/darktable/tools/extract_wb_from_images.sh
/opt/darktable/bin/darktable: error while loading shared libraries: libavif.so.4: cannot open shared object file: No such file or directory

libavif.so.5 exists.  adding simlink allowed build to complete.

late last week I had to upgrade to libavif5 in order to build, now libavif4 is required ????

**Comment by parafin** [comment]
Please do a build from empty build directory.

**Comment by ptilopteri** [comment]
ok, cleaned build directory
removed symlinks for /usr/lib64/libavif.so.4
cloned
submodule init/update
build
make 

successful, tks
will close
