### ISSUE TITLE
New crop guide seems impossible to move completely to edges

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#5830]
**Describe the bug**
With the recent changes to the "crop and rotate" module, it now appears to sometimes (always?) be impossible to select all the way to the right/bottom edges of the available image pixels. Previously, this would sometimes be the case for *one* edge, when using a 4:3 ratio on a "four-thirds" type sensor for instance, due to the the original presented area not being exactly a 4:3 aspect ratio. Now, however, it seems impossible to pull the guide *all the way to the actual edge* even in cases where it should be possible.

**To Reproduce**
Select an image with sufficient edge detail to make unintentional cropping easily visible. Set aspect to "freehand", then attempt to fully select *the entire displayed rectangle* and apply the crop. Observe that you have lost edge area which was visible in the rectangle you were attempting to fully select. If the module is re-activated so that the guides appear again, they will have moved to the place where the crop was actually done, rather than appearing where they were placed.

**Expected behavior**
Moving an edge of the guide as far as possible towards the edge of the displayed image rectangle should retain all of the displayed image area when the crop is applied.

**Screenshots**
I don't have screenshots prepared, but I can try to add some if they're actually needed.

**Platform (please complete the following information):**
darktable master 3.1.0+2486 on Linux with Nvidia OpenCL enabled

**Comment by junkyardsparkle** [comment]
@GrahamByrnes Any thoughts on this?

**Comment by GrahamByrnes** [comment]
Hi, I haven't been in here for a while... I have a version that makes me happy, so I thought I'd work for my employer a bit :-)
So when you say "recent"?

There have been a few iterates of moving the limits on the crop boundaries relative to the edge of the image, but I haven't been involved in that. Maybe if you did a bisect to pin down the date of the change?

**Comment by junkyardsparkle** [comment]
> There have been a few iterates of moving the limits on the crop boundaries relative to the edge of the image, but I haven't been involved in that.

Ah, sorry, I just looked back through the file history a bit. Before doing a full bisect I was hoping for confirmation that somebody elss can reproduce this and would consider it a bug... but I'll try to find the specific commit when I have some time later.

**Comment by junkyardsparkle** [comment]
Ok, during the course of trying to bisect this I eventually realized that *no* version has this issue using a fresh config. I have no idea what thing within the config/database could cause something like this; closing, sorry for the noise.
