### ISSUE TITLE
Darktable 3.0.2 loses OpenCL support after sleep/wake

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#5834]
I'm using Nvidia card 1060, latest proprietary drivers, AMD cpu, Arch Linux with Gnome. Everything is latest.

To reproduce it goes like this.

1. System reboot, login everything works.
2. Starting Darktable 3.0.2 - OpenCL enabled, working.
3. Pressing sleep button, system is going to sleep mode.
4. After wake, checking Darktable it still says OpenCL enabled.
5. Closing down Darktable and starting it again and the message displayed in Core settings is - not available.

It won't be available until next machine restart.

**Comment by elstoc** [comment]
I don't know about this issue specifically (I would suspect it's an upstream issue with Nvidia), though there is something similar mentioned on the Arch Linux wiki: https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Poor_performance_after_resuming_from_suspend

**Comment by parafin** [comment]
Yeah... This is not a support forum, but bug tracker, and this is definitely not a bug in darktable.

**Comment by maboleth** [comment]
Well, fair enough, but two things:

1. Poor performance tip in Arch wiki doesn't help, quite the contrary - it makes my OpenCL permanently disabled.
2. OpenCL DOES work after suspend, it's just that DT is not able to use it if I restart DT in the same session.

Remember, if DT wasn't closed during and after suspend, it WILL still use OpenCL. But NOT after I close DT and start it again. Until next reboot.

**Comment by maboleth** [comment]
Also if I suspend my machine like 2-3x without DT being on during suspend, DT WILL use OpenCL when I start it.

It's just that having DT open during/after suspend makes it problematic if I'm about to restart DT in the same session.

Not sure if I described it right, I'm in the hurry. Sorry.

**Comment by thugcee** [comment]
>     2. OpenCL DOES work after suspend, it's just that DT is not able to use it if I restart DT in the same session.

@maboleth, kill DT (and any other process using OpenCL) and do `sudo rmmod nvidia_uvm && sudo modprobe nvidia_uvm` - this solves the problem. Start DT again.

The new problem is that in DT 3.4, when one suspends a computer with DT in darkroom mode and then, after resume, try to quit DT (with broken OpenCL) the process becomes unkillable (even with SIGKILL) and consuming 100% of 1 CPU core. Reboot of operating system is needed to get rid of it. Super annoying.

When DT is suspended in lightroom mode, after resume it is possible to quit, reload `nvidia_uvm` and start it again to have working OpenCL.

**Comment by GLLM** [comment]
Thanks @thugcee for the "sudo rmmod nvidia_uvm && sudo modprobe nvidia_uvm" tip ... 

Mu Kubuntu 20.10 going to sleep several times a day and making OpenCL unavailable only for darktable made me crazy ... I had to reboot everytime I wanted to get OpenCL in dt ...
