### ISSUE TITLE
thumbnail not updated when rating changed by lua

### ISSUE THREAD

**Issue by s5k6** [darktable-org/darktable#5835]
**Describe the bug**

Thumbnails in lighttable seem not to be updated, when the image rating is changed by a lua script.
This has been working in the past though.

**To Reproduce**

Use the following Lua script, and bind the settings/shortcuts/lua/foo to a key, say backspace.  Select an image.  Set the image rating to 5.  Press backspace.  The rating will be changed, but that's not visible in the thumbnail.  Trigger a redraw of the thumbnail, e.g., by scrolling it out of view and back, or collapsing/expanding sidebars.  The redrawn thumbnail will show the new rating.

```
local dt = require "darktable"

local function foo()

    print("________________________________________")

    print("--- action images ---")
    print("count:", #dt.gui.action_images)
    for _, i in pairs(dt.gui.action_images) do
        print(i.id, i)
        i.rating = 1
    end

    --[[
    print("--- collection ---")
    print("count:", #dt.collection)
    for _, i in pairs(dt.collection) do
        print(i.id, i)
    end
    --]]
end

dt.register_event("shortcut", function(_, _) foo() end, "foo")

-- see https://www.darktable.org/usermanual/en/lua_chapter.html

print("Loaded Lua module `demo`")
```

**Expected behavior**

The thumbnail should be updated immediately when the rating isch changed.  This was the case in earlier versions.

**Platform (please complete the following information):**
 - Darktable Version: release-3.1.0-2511-g4226ac17c
 - OS: Arch Linux
 - OpenCL activated
 - Nvidia GeForce GTX 1060

**Comment by wpferguson** [comment]
Tested and verified.  Looks like I fixed one thing and broke another.  @AlicVB, any recommendation about which rating function(s) I should use to ensure the thumbnail updates?

**Comment by jenshannoschwalm** [comment]
> Tested and verified

Are you sure about this? I have not yet used lua or know the code but from the source it just sets a new rating for the image. I don't think this should update the thumbnail, just the thumbnail overlay and the collection. Right?

**Comment by wpferguson** [comment]
Correct, just the overlay and collection need updated.  I believe that the thumbnail probably got updated too, based on the code.  A write lock was obtained on the image and released after the rating was changed.  I believe releasing the write lock forced the thumbnail, overlay, and collection to update.  It appears that the new thumbtable code is doing the update a little different, so today's project is to try and figure out how that is happening and then bring the lua code into sync with that.

**Comment by phweyland** [comment]
>  I believe releasing the write lock forced the thumbnail, overlay, and collection to update.

If I'm not mistaken "DT_IMAGE_CACHE_SAFE" forces only to write the xmp file.

In libs/image.c there this code to ensure correct UI refresh:
```
      dt_collection_update_query(darktable.collection, DT_COLLECTION_CHANGE_RELOAD,
                                 g_list_copy((GList *)imgs));
      dt_control_queue_redraw_center();
```
Something similar may be needed in lua/image.c

**Comment by wpferguson** [comment]
I found that and it solves the update problem.  I also need to add it to
the colorlabels, because they aren't updating either.
