### ISSUE TITLE
WB Presets for Sony ILCE-7RM4

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/darktable#5837]
[darktable-whitebalance-20200730.tar.gz](https://github.com/darktable-org/darktable/files/4999310/darktable-whitebalance-20200730.tar.gz)

**Comment by johnny-bit** [comment]
Looks great! Associated PR didn't autoclose this issue, would you mind closing it manually, please?

**Comment by matt-maguire** [comment]
ILCE-7RM4 WB preset changes accepted and merged.
