### ISSUE TITLE
XT-3 lens correction profile unavailable in Linux

### ISSUE THREAD

**Issue by Kallestofeles** [darktable-org/darktable#5841]
**Describe the bug**
In Windows, the lens correction profile is available and automatically detected for Fujifilm XT-3 camera. On Linux however, the profile does not seem to exist. XT-2 profile does exist and it corrects the image really well so far even when using XT-3 for the photos.

**To Reproduce**
1. Install Darktable on any Linux distribution (Tested this on Arch linux)
2. Open Darktable and start editing an image
3. Enable lens correction plugin
4. Search for Fujifilm, XT-3 profile

**Expected behavior**
XT-3 profile should be present both on Windows and Linux just like the XT-2 profile is.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Arch linux (rolling)

**Additional context**
 - Can you reproduce with another Darktable version? Yes, earlier versions also do not have the profile
 - Can you reproduce with a RAW or Jpeg or both? Yes, both, all images
 - Are the steps above reproduce with a fresh edit (removing history)? Yes
 - Did you compile Darktable yourself? If so which compiler was used, with what options? No - the following package was used: https://www.archlinux.org/packages/community/x86_64/darktable/
 - Is the issue still present using an empty/new config-dir - Yes

Maybe I am missing something, but I honestly do not have any ideas where to look for the profiles which do not appear in the program.
Thank you in advance for the help or feedback!

Best regards,
Kalle

**Comment by pitbuster** [comment]
Try `lensfun-update-data` to update the lens correction database. Windows releases bundle an updated version of the database, but Linux doesn't (as it uses the system lensfun library).

**Comment by Kallestofeles** [comment]
Thank you @pitbuster that solved it! I shall keep that in mind. :heart:
