### ISSUE TITLE
mingw64 compilation failed

### ISSUE THREAD

**Issue by yoohoxiao** [darktable-org/darktable#5850]
I get an error when compiling with msys2.

[ 93%] Generating de/darktable-cmstest.pod
Unknown format type: pod.
List of valid formats:
  - asciidoc: AsciiDoc format.
  - dia: uncompressed Dia diagrams.
  - docbook: DocBook XML.
  - guide: Gentoo Linux's XML documentation format.
  - ini: INI format.
  - kernelhelp: Help messages of each kernel compilation option.
  - latex: LaTeX format.
  - man: Good old manual page format.
  - pod: Perl Online Documentation format.
  - rubydoc: Ruby Documentation (RD) format.
  - sgml: either DebianDoc or DocBook DTD.
  - texinfo: The info page format.
  - tex: generic TeX documents (see also latex).
  - text: simple text document.
  - wml: WML documents.
  - xhtml: XHTML documents.
  - xml: generic XML documents (see also docbook).
  - yaml: YAML documents.
make[2]: *** [doc/man/CMakeFiles/manpage-de-darktable-cmstest.1.dir/build.make:8

**Comment by johnny-bit** [comment]
Weird, isn't it? the error is "unknown format type: pod" but in list of valid format there's: "pod: Perl Online Documentation format."

As a workaround you can remove po4a package from msys2 which would cause building of manual to be simply skipped and will allow you to compile everything else.

**Comment by jenshannoschwalm** [comment]
Don't know why yet but also on fedora 32 i can't generate the manual since a few days ago.

**Comment by TurboGit** [comment]
@jenshannoschwalm : I have a fix that I will push very soon.

**Comment by jenshannoschwalm** [comment]
Thanks for telling, was just going to look into it.

**Comment by matt-maguire** [comment]
I had a similar issue on my manjaro linux system after doing a system upgrade, the problem was that I didn't have the Pod::Parser module installed. I think this might be the same issue as #6009.

**Comment by johnny-bit** [comment]
Does the issue persist? Since ~20th august the Pod::parser package is in msys2 and should be available to use, so there should be no po4a problems in compiling dt on windows.
