### ISSUE TITLE
FR: Collect images with multiple versions (duplicates)

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5854]
When multiple versions (duplicates) of an image exist it is currently possible (in the collect module) to filter either "group leaders" (the first version of every image) or "group followers" (subsequent versions where duplicates exist). However there does not appear to be an option to show all versions of duplicated images (i.e. show all "group followers" plus "group leaders" where an associated group follower exists).

Please can we have a new collection filter, perhaps under the existing 'grouping' option, called, say, "grouped images" which filter like this.

**Comment by johnny-bit** [comment]
I took it for a spin and this is interesting how it works

- `group leaders` shows all images that are not followers inluding the images that do not have group at all
- `group followers` shows all images that are followers without group leader

I think that `group leaders` should exclude images not having a group. Maybe the ideal setup for grouping would be:

- `lead or single images` - being equivalent with current group leaders
- `group leaders` - images that are in group and are leaders
- `grouped` - images that are in group
- `group followers` - images that are in group and are not group leaders

What do you think?
