### ISSUE TITLE
lighttable: column position lost when navigating with arrow keys

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5858]
In the lighttable file manager view, click any image that is **not** in column 1 to give it focus. Say, an image in column 2.

Press the up arrow key until you reach the top row. Each time you move up, the highlighted image changes and the view scrolls as needed (all as expected). In this example, when the top row is reached, the image in row 1 column 2 is highlighted.

Press the up arrow one last time and _no image_ is highlighted.

After this point, pressing the down key causes focus to be given to row 2 column 1. If instead you press the right arrow key, focus is given to row 1 column 2.

It looks like on the final press of the up arrow key the fist image becomes the one selected (row 1 column 1) but there is no visual indication of this.

I would expect that on the final press of the up arrow the screen should remain unchanged (row 1 column 2 should remain highlighted). This is what happens when the bottom row of the lighttable is reached.

Issue found on current master and 3.2.x branch.

**Comment by TurboGit** [comment]
Will be in 3;2.
