### ISSUE TITLE
DT 3.3.0 cannot copy history in lightable culling view.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#5862]
darktable-3.3.0+2~gc94b5fda3-win64

Edit an image.
Be in lightable culling mode.
Select by clicking the edited image. Notice cursor and the enabled buttons for history stack on the right.

![image](https://user-images.githubusercontent.com/1119439/89139275-cdd12f00-d55b-11ea-8785-9c1f446e9996.png)

Now try going to the history stack copy button.
You can't select it. As soon the cursor moves outside the selected image the image loses focus and the copy button is disabled.
![image](https://user-images.githubusercontent.com/1119439/89139204-9f535400-d55b-11ea-9fe3-f77c60660cdc.png)

**Comment by Nilvus** [comment]
Issue had been fixed.
