### ISSUE TITLE
darktable 3.3.0: cannot set white balance to 4000K, it results in 3901K

### ISSUE THREAD

**Issue by bd23843** [darktable-org/darktable#5863]
git rev. cb17b3bfa91538d8ee4e5f9721312915cd3f066a on ubuntu 20.04, opencl on/off makes no difference.

There is a white balance range around 4000k that cannot be set in this version. No matter if I use the slider or enter the value numerically, it is not possible to get 4000k, darktable changes value to 3901K . The tint is also automagically modified.

There is no message on terminal indicating a problem.

**Comment by johnny-bit** [comment]
That's not a problem, that's just "a feature" of how "temp" is calculated. you see: everything above 4000K is "daylight" reference, while anything below is technically "blackbody" reference. however there's an overlap at roughly 3900-4000K where coeficients calculated with daylight reference may match those with blackbody reference and vice versa. You still have the same range of creative freedom, nothing really changes, the actual values that mean anything are r/g/b coefficients and temp/tint is just for your convinience. sort of "visual sugar"

As for the "fix" it is planned to be included soon enough, see #5726 which fixes this issue

**Comment by johnny-bit** [comment]
fixed in #5726, not a problem with modern color calibration workflow...
