### ISSUE TITLE
Crashing at startup on W10x64

### ISSUE THREAD

**Issue by apphead** [darktable-org/darktable#5870]
Trying to use darktable V3.0.2 (virgin installation) in conjuction with latest Hugin on a W10x64 workstation, the log file is below.
[darktable_bt_39XYO0.txt](https://github.com/darktable-org/darktable/files/5025162/darktable_bt_39XYO0.txt)

The message I get from Hugin is this:

Executing: C:\Program Files\darktable\bin\darktable-cli.exe --verbose "C:\Users\[xyz]\Desktop\Pano\Office\IMG_20200804_173645_0.dng" "C:/Users/[xyz]/Desktop/Pano/Office/IMG_20200804_173645_0.tif" --core --conf plugins/imageio/format/tiff/bpp=16
[defaults] found a 64-bit system with 50150628 kb ram and 8 cores (0 atom based)
[defaults] setting very high quality defaults

(darktable-cli.exe:32824): Gtk-WARNING **: 18:07:34.672: gtk_disable_setlocale() must be called before gtk_init()

**Things I tried to no avail:**
- Reinstalled darktable in c:/darktable instead of c:/Program Files/darktable
- disabled opencl with startup flag (but that does not help with Hugin as I don't know how to add flag when process is invoked in Hugin
- Tried both GPUs Intel HD Graphics 630 and Nvidia Quadro M1200 (using NVIDIA Control Panel)
- Updated Nvidia drivers to 451.77

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Windows 10 64-bit
 - OpenCL activated: yes an no

Any help would be appreciated!

**Comment by jdrch** [comment]
Same problem here. Fresh install of the app. Uninstalling.

**Comment by jdrch** [comment]
FWIW the same crash occurs as far back as 2.6.3, and it's even worse back then. At least in 3.0.2 you actually get a window.

Clearly Darktable has light years to go before it's functional on Windows. In the meantime, small reminder that digiKam works just fine.

**Comment by apphead** [comment]
I managed to get it running by setting opencl=FALSE in darktablerc. I'm
currently also testing RawTherapee which has a powerful GUI application
that comes with the postprocessor.

jdrch <notifications@github.com> schrieb am Fr., 7. Aug. 2020, 02:15:

**Comment by jdrch** [comment]
I got it working on a different machine, but the UI is perhaps the oddest I've encountered in a very long time. I'll stick to digiKam.

**Comment by johnny-bit** [comment]
Yeah, windows opencl driver issue - see https://github.com/darktable-org/darktable/issues/5988#issuecomment-674581664 for causes and workaround possible here: https://github.com/darktable-org/darktable/issues/6492#issuecomment-706512073
