### ISSUE TITLE
Lighttable thumbs disappear when last thumb selected and reentered from darkroom

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#5871]
**Describe the bug**
All thumbs disappear in lighttable when reentering from darkroom. It only happens when the very last thumbnail is selected in a collection. If any other thumb is selected, expected behavior results. If I use the timeline selector in the bottom pane, I can make a selection that make thumbs appear again.

**To Reproduce**
1. Go to a collection and select the last thumb and enter darkroom
2. Hit "l" to return to lighttable.
3. All thumbnails have disappeared and the widget is no longer scrollable by the mousewheel. Grabbing the scrollbar with the mouse reveals an empty lighttable.

**Expected behavior**
I expect the thumbs to still be there when returning to lighttable.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+13~ga4325917f
 - OS: archlinux
 - OpenCL: Intel Skylake

**Comment by elstoc** [comment]
I can't reproduce this on ArchLinux 3.3.0+14~gfd54c5bc3. What mode is lighttable in? Can you try on one of the earlier commits, perhaps before my two recent lighttable fixes (so perhaps try commit https://github.com/darktable-org/darktable/commit/10be7dc47211f570a74e33e4fdc51eb5ca90c4cf)

**Comment by Egocentrix** [comment]
I managed to reproduce this on dt 3.2.1 (Manjaro, no OpenCL). Lighttable is in 'file manager' mode. I can consistently reproduce it by selecting the last image in the collection, but only if the last image was also in the rightmost column. If the collection ends in one of the middle columns it does not happen.
Have not tested it yet on 3.2.0, but I suspect this has something to do with your fix.

Also: scrolling was not possible, but everything came back when I changed the zoom level of the lighttable.

**Comment by elstoc** [comment]
> Have not tested it yet on 3.2.0, but I suspect this has something to do with your fix.

Sounds like a reasonable assumption

**Comment by elstoc** [comment]
And yes I reproduce it with that scenario

**Comment by elstoc** [comment]
I hate to say it but I think this might be a worse issue than #5861 was trying to fix. Pinging @TurboGit as this might be a critical issue for the release.

**Comment by groutr** [comment]
Just caught up on the progress of this issue. Is there anything further that I need to provide/test?

**Comment by elstoc** [comment]
@groutr it would be good if you are able to test my PR #5872.

**Comment by groutr** [comment]
A similar issue, but with the zoomable lighttable.
1. Switch to zoomable light table view.
2. Zoom out all the way.
3. Select a thumb, enter darkroom, and press "l"
4. Observe that all thumbs before the selected thumb disappear until I move the view.

**Comment by groutr** [comment]
@elstoc I did some testing on your PR, both with my own test case and with the info added by @Egocentrix (by adjusting the number of thumbs per row to place the last thumb in different columns). I can confirm that your PR seems to fix this particular issue with the file manager mode.

**Comment by elstoc** [comment]
Thanks for testing @groutr. I think the issue with the zoomable lighttable sounds different. It's not a mode I use so I don't know the correct behaviour (though what you describe obviously sounds wrong). However this PR and the two fixes that preceded it are all limited to the filemanager mode, so I don't know if this issue could be related.

Are you able to retest this on https://github.com/darktable-org/darktable/commit/10be7dc47211f570a74e33e4fdc51eb5ca90c4cf and/or on latest master?

**Comment by groutr** [comment]
@elstoc The zoomable lighttable view issue appears on the latest master and on your branch. Because I was able to reproduce it in both builds, I opened a new issue. I don't think its related because it isn't column specific like issue was.
