### ISSUE TITLE
Darktable crashes at start up

### ISSUE THREAD

**Issue by cribari** [darktable-org/darktable#5875]
**Describe the bug**
I run Arch Linux and after upgrading Darktable (from the Arch repository) to version 2:3.0.2-7 I can't start the program. 

**To Reproduce**
1. Install Darktable 3.0.2.  
2. Try start the program. 

**Expected behavior**
The program should start. 

**Screenshots**
I have no screenshots since the program does not start. The error messages are at https://pastebin.com/1D7ws9bU 

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Arch Linux
 - OpenCL not activated
 - Intel graphics card
- Hardware: LG Gram laptop (Intel GPU)

**Additional context**

The error messages are at https://pastebin.com/1D7ws9bU 

OBS. 1) I edited the bug report to correct the version number; 2) After removing intel-compute-runtime, as suggested by @johnny-bit , I was able to start the program.

**Comment by johnny-bit** [comment]
Your version is not "2.3.0" it's "3.0.2".

You mention that "OpenCL is not activated" but the crash comes from libigdrcl.so which is Intel's openCL lib. Your options include either removing intel-compute-runtime (or something similar) or trying newest version.

**Comment by johnny-bit** [comment]
You might want to close this bug and instead raise one with Arch linux against intel-compute-runtime, since intel-compute-runtime is outside of darktable's control.
