### ISSUE TITLE
Noise profile Ricoh GR II

### ISSUE THREAD

**Issue by FedeGST** [darktable-org/darktable#5876]
Hello!

I just created some noise profiles for the Ricoh GR II.

**Note:** the "maker" in the generated profile is "Ricoh", but exiv2 and darktable say that it is "RICOH IMAGING COMPANY, LTD." instead. When I tried to open the original json file, the denoise module did not find a match. After I manually edited the maker field to say "RICOH IMAGING bla bla..." it did find the match and the profiles worked correctly. (I am having the same issue also with the lens correction module.)

I suspect that the older models of Ricoh cameras have "Ricoh" as a maker, while the newer ones have "RICOH IMAGING COMPANY, LTD." (the latter seems to also include the new Pentax cameras). It might be worth adding both versions to the noiseprofile.json.

[darktable-noiseprofile-20200806.tar.gz](https://github.com/darktable-org/darktable/files/5037720/darktable-noiseprofile-20200806.tar.gz)

**Comment by da-phil** [comment]
This was merged in https://github.com/darktable-org/darktable/pull/6419 to master.
Hence the issue can be closed.
CC: @TurboGit

**Comment by TurboGit** [comment]
Closing, thanks !
