### ISSUE TITLE
Trash does not work on NFS mounts

### ISSUE THREAD

**Issue by hannonq** [darktable-org/darktable#5894]
**Describe the bug**

On Linux, I have all of my photos stored on a NFS mount on my local network.
When I click "Trash" on Lighttable, I get the expected prompt `"Do you really want to send X selected image to trash?"`.
Now, my NFS doesn't have a trash system enabled, so when I click "yes", the photo is deleted from my collection but not physically deleted from the folder.

When doing the same process using Darktable 3.0.1 running on MacOs, I get a second prompt saying 
`"Could not send <filename> to trash. <filename> couldn't be moved to trash because the volume <volume name> doesn't have one."
`
And then I get the option to physically delete the file, skipping the trash altogether. That's indeed what I want.

But this second prompt doesn't come up when running Darktable 3.0.2 on Linux.

Note that trashing photos that are stored locally on my laptop works fine. It only doesn't work on my nfs mount. At first I thought this could be a permission problem, but since the .xmp files are created just fine, and I can also export files from Lighttable to my nfs folders, I assume that the problem is not permission related.

**To Reproduce**
1. Install Darktable 3.0.2 via Flatpak on Linux (in my case, PopOs 20.04)
2. Import photos from a NFS mount
3. Click on "trash" in the Lighttable view
4. Notice that the photo is not physically deleted from file system, only from DT library.

**Expected behavior**

Photos should be physically deleted from file system.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2, installed via Flatpak
 - OS: PopOS 20.04
 - OpenCL activated
 - GeForce GTX 1650 Ti, NVIDIA-SMI 440.100  Driver Version: 440.100

**Additional context**
My NFS folder is mounted as following in my fstab:
`<IP address>:/volume1/nasfiles /media/NAS nfs _netdev,rw,hard,intr,nofail,rsize=8192,wsize=8192,timeo=14 0 0`

Any ideas if this is a Darktable bug or Flatpak problem?
Thanks!

**Comment by parafin** [comment]
It may be a glib bug, but not likely a darktable bug, since you say that it works on macOS.

**Comment by coffeeandspaceships** [comment]
It's likely related to this glib issue with trash handling on *anything* that isn't a native-local filesystem. Even screws up things like external USB disks. Issue has been open for a year. https://gitlab.gnome.org/GNOME/glib/-/issues/1722

**Comment by hannonq** [comment]
Ok, that sucks.
But thanks for pointing me to where the problem is.

Since it's not a Darktable problem, I'll close this issue.
If I find a way to fix/work around it, I'll post the solution here.
