### ISSUE TITLE
Migration from 3.0.2 to 3.2.1 detect many XMP change

### ISSUE THREAD

**Issue by pahervin** [darktable-org/darktable#5908]
As a french guy, I first describe the issue in french, then I translate in my improvable english. The french version is the reference.

**Description de l'anomalie**
J'ai mis à jour mon installation de DT à la version 3.0.2, il y 5 jours (05/08/2020). Aujourd'hui, j'ai effectué la mise vers la version 3.2.1.
Au premier lancement, DT-3.2.1 détecte qu'un grand nombre de fichiers XMP sont plus récents que les données des BdD.

**Reproduction de l'anomalie**
1. Partir d'une session récente de DT-3.0.2 : aucun changement n'est intervenu dans aucun fichier XMP depuis la cloture de la sesssion.
2. Télécharger et mettre à jour l'installation de DT vers la version 3.2.1.
3. Lancer DT-3.2.1 pour le première fois.
4. Accepter la migration des schémas des bases de données (data.db et library.db). La migration s'effectue sans information de progression.
5. Vérifier que la migration des BdD a créé des sauvegarde de la version précédante.
6. Attendre que DT affiche une première fenêtre, sans information de progression.
7. DT-3.2.1 détecte que des fichiers XMP sont plus récents que les données de la base et affiche la boite de dialogue correspondante. Il n'y a pas de décompte de fichiers, mais tous les fichiers XMP semblent impactés.
8. Cocher la case 'Tous les fichiers', et demander la mise de la base à partir des fichiers XMP (environ 6500).
9. Attendre sans indication de progression.
10. La mise à jour plante (voir le fichie de backtrace joint).
11. Relancer DT-3.2.1
12. DT détecte à nouveau des changements de fichiers XMP, mais beaucoup moins nombreux.
13. Demander à nouveau la mise à jour des bases de données à partir des fichiers XMP.
14. DT-3.2.1 démarre sans autre erreur apparente, mais l'état des bases de données est pré-occupant.
15. Fermer la session DT sans effectuer aucun changment (pas un seul clic dans l'interface)
16. Les fichiers XMP semblent ne pas avoir été modifié par la mise à jour (vérification de la date de plusieurs fichiers)

**Comportement attendu**
1. La détection des changements dans les fichiers XMP semble improblable.
2. La mise à jour des BdD à partir d'un grand nombre de fichiers XMP doit s'effectuer sans erreur.

Now in my improvable english
-------------------------------
**Describe the bug**
I upgraded my dartable to 3.0.2 version 5 days ago. I upgraded to 3.2.1 version today.
At the first launch dt-3.2.1 detects that many XMP files are more recent than the library data.
The databases updates crashes.

**To Reproduce**
[darktable_bt_BFKCP0.txt](https://github.com/darktable-org/darktable/files/5050960/darktable_bt_BFKCP0.txt)

1. Start from a recent session of dt-3.0.2 : no change within the XMP files. Everything was up to date before the upgrade.
2. Download and upgrade to dt-3.2.1.
3. First launch of dt-3.2.1.
4. Accept databases schema migration (data.db and library.db) and wait without any progess information.
5. Check databases backup (data.db-pre-3.2.1 and library.db-pre-3.2.1).
6. Wait for dt display without any progress information.
7. dt-3.2.1 display the dialog box about XMP files changes. There is no files count but likely all my XMP where listed in the dialog box. 
8. Check the 'All files' checkbox and request the databases update from XMP files (about 6500).
9. Wait without any progress information
10.  The update crashes (see joined backtrace)
11. Second launch of dt-3.2.1
12. The dialog box about the XMP files changes is displayed again. There are much less XMP files listed.
13. Request again for databases update from XMP files.
14. dt-3.2.1 starts without any other issue, but the database status is worring.
15. Close dt without any change.
16. The XMP files remain unchanged (I checked some file modification date)

**Expected behavior**
1. The XMP file changes detection seem unlikely.
2. The databases update from XMP files must run with any count of files.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL not activated
 - Graphic card : Intel UHD Graphics 620

**Additional context**
- I am quite experimented software engineer. I can answer to quite touchy questions about computing to help to identifiy the issue.
- I am used to share my XMP files with other softwares (ex. digikam) for tags editing. I am used to the databases update from the XMP files. It is my first crash on this feature since DT-2.4.
- What about my databases ? How can I fixe my DT databases, and continue to use it safely ? How can I check them ? Do I switch by to DT-3.0.2 ?

**Comment by Mark-64** [comment]
I guess this is related to #5847, which is a know issue in 3.2

**Comment by phweyland** [comment]
> darktable_bt_BFKCP0.txt

This indicates that the crash occurs in dt_exif_xmp_read(). Should be interesting to get more a more detailed log, if possible ...



> * Check the 'All files' checkbox and request the databases update from XMP files (about 6500).
> 
> * Wait without any progress information
> 
> * The update crashes (see joined backtrace)


Normally if your previous db is up to date you don't need to ask to update db from xmp. That would avoid this disagreement.
The synchronization, if necessary, could be done with the previous dt version, before migration to 3.2.1.



>     16\. The XMP files remain unchanged (I checked some file modification date)

This confirm my previous point.

Only the xmp file timestamp is synchronized with write_timestamp in db. 

#5869 should solve the disagreements  but the timestamp difference is still suspect for me.
With new timestamps introduction, some generalization may have affected write_timestamp. Maybe @jpverrue could help to understand this.

**Comment by pahervin** [comment]
> 
> 
> I guess this is related to #5847, which is a known issue in 3.2

Yes, it is related to #5847.
But this issue is mainly about the crash. The great count of XMP files seems to be issue origin.
Whatever the files count, DT must update.
I dont know the processing within DT, but it is often good to chunk the updates. By the way the intermediate states will give progress informations.

**Comment by Nilvus** [comment]
@pahervin: some things have been fixed and improved about XMP this last months, and so in actual master. It will be so in future 3.6 release (due in about 2 weeks).

I close this issue as it's probably fixed. I suggest you to update and if needed test again with 3.6 when it will be released. Feel free then to reopen (or ask for it) if you still reproduce (and update title so!). Thanks.
