### ISSUE TITLE
30% of pictures getting one start at import

### ISSUE THREAD

**Issue by rvalle** [darktable-org/darktable#5911]
**Describe the bug**

Images rated 1 stat after folder import

**To Reproduce**

1. Go to settings/general: select recursive traversal...
2. Go to import, folder: select a folder with a tree and photos
3. Import
4. Select filter by 1 start or more
5. many of the just imported pictures appear rated.

**Expected behavior**

All photos should be imported, they have not been rated yet. filtering by 1 start or more should show no images.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:3.0.1
 - OS: Ubuntu 20

**Additional context**

I am new to darkatable, I am importing my photo library. They are mostly JPGs from Android Phones.

I don't understand why but 30% of the imported pictures are imported with 1 star already.

The photos have been organized into directories with exiftool.  These are the exif information of a picture that got one start rating: https://pastebin.com/b8d1vgAP

**Comment by Nilvus** [comment]
darktable 3.2.1 has just been released this day. Maybe updating to it and test with him. A lot of things have changed, especially in lighttable and some on import things. You can compile that new version or wait a little to see darktable 3.2.1 soon available on Opensuse repository.

**Comment by ptilopteri** [comment]
@rvalle 
there is an option in the configuration to set import rating but it defaults to one star unless changed.  
fwiw: I have my import set to 0 stars.

**Comment by rvalle** [comment]
@ptilopteri thanks!

That was it. 

It didn't even crossed my mind that such a setting would exist, let alone that its default value was one star. 

I think it should default to 0. 

Perhaps would be better to ask on each individual import as in some particular case it might be required. 

However, for this kind of thing, I miss lightroom functionality "last import" that allowed me to display just the photos imported and then applying a new rate would be one click away.

**Comment by ptilopteri** [comment]
@rvalle 
you really, really, should take a look at the documentation as you look for features already
available.

and consider closing this issue as it is not an issue.

**Comment by rvalle** [comment]
... doing it right now. Thanks for the suggestion.
Its my first day with Darktable and I am actually loving it.
But yes, documentation is a must.
