### ISSUE TITLE
Cant open darkroom

### ISSUE THREAD

**Issue by AntonioBermejo** [darktable-org/darktable#5912]
Hi guys:
I'm completely new on this program 
I tried today to install two different versions and both with the same problem( maybe config problem, I don't know)
The program works until I try to open a raw file in the darkroom in this moment the program get frozen.. any idea why?? 
Thanks

**Comment by Nilvus** [comment]
Hi,
With so much information, it will be hard to help. You didn't precise many infos asked when posting an issue:
which OS? Which darktable release? Which type of RAW? Which camera so behind? Is it only on a freshly imported RAW or an edited one? Is it on a new freshly installed darktable and new configured one? Did this work before? If yes, could you describe what could had changed? And as you precise it, which config do you use? Processor, RAM, graphics card? Did you try with or without OpenCL?

**Comment by AntonioBermejo** [comment]
I was the OpenCL thanks sorry but I'm very new in this( 2 hours)

**Comment by Nilvus** [comment]
If it solved (if I understand your answer), think about closing this issue.
