### ISSUE TITLE
Importing .ARW files causes a crash

### ISSUE THREAD

**Issue by ajtech** [darktable-org/darktable#5915]
**Describe the bug**

After downloading darktable on windows 10, I immediately uploaded some Raw Sony picture. First one at a time and then a whole folder. The program would crash a second later
[darktable_bt_AIC7O0.txt](https://github.com/darktable-org/darktable/files/5053717/darktable_bt_AIC7O0.txt)
[darktable_bt_F918O0.txt](https://github.com/darktable-org/darktable/files/5053722/darktable_bt_F918O0.txt)

**To Reproduce**

I tried uploading .ARW photos that worked fine in windows photo viewer with and without there included xmp data file.

**Platform (please complete the following information):**
 - Darktable Version:  downloaded from the website today august 10
 - OS:  Windows 10
 - 
 -  AMD processor and card

**Comment by Mark-64** [comment]
I have a Sony camera and I have no such issue with ARW files.
Which camera model do you have ? Can you post a sample file ?
