### ISSUE TITLE
[3.2.1] Lighttable: moving among images causes annoying blinks/flickering

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#5916]
In lighttable with both
- culling, zoom 1, fixed zoom
- file manager view, zoom level 1;

while using mouse scroll wheel, to switch among images, you get a kind of flash effect during the transition. I mean, when you change image, for a fraction of second you see one of the images stretched on the whole area, I mean, one of the images is shown outside its natural borders. You can easily see this if you are moving among photos that have the same aspect ratio.
To better understand please see this video and make sure to select 1080P 60 FPS Youtube option.
https://youtu.be/CHbfP2I83sg

Another variant of this is when you also have your mouse pointer over the image, in addition to the previously described flash, you will get also a flash from the background colour appearing while switching among photos
To better understand please see this video and make sure to select 1080P 60 FPS Youtube option.
https://youtu.be/F0VxA66yk2U

So in both scenarios, when you move among various images you get a very annoying flashing effect. If you cannot easily manage to reproduce the effect, trying scrolling the mouse wheel faster.
Please note that I already let the system create all previews of photos in the active collection.

**Platform (please complete the following information):**
 - Darktable Version:3.2.1
 - OS: Fedora 32
 - It happens with OpenCL and without OpenCL. I have the feeling that with OpenCL it happens more often but I am not sure
 - Radeon RX480. When using OpenCL [1], the driver is amdgpu-pro-20.10-1048554, when not using OpenCL the driver is amdgpu included in kernel 5.7.11-200.fc32.x86_64

**Additional context**
 - Can you reproduce with another Darktable version?
I don't remember it was happening with 3.0.x
 - Can you reproduce with a RAW or Jpeg or both?
Both

[1]: Started with command `$ OPENCL_VENDOR_PATH=/home/caterpillar/amdgpu-pro-20.10-1048554-rhel-8.1/etc/OpenCL/vendors/  LD_LIBRARY_PATH=/home/caterpillar/amdgpu-pro-20.10-1048554-rhel-8.1/opt/amdgpu-pro/lib64/ darktable`

**Comment by maboleth** [comment]
I can confirm this.

Sadly, in my case, DT 3.0.2 had much better Zoomable mode than the current one. It just worked, going from small to big, images persisted and were shown instantly.

Now, when they said they reworked this thing from scratch, as of now, it's for the worse. Images either flicker as you described, don't show when going to darkroom mode and back or take couple of seconds to load. Or the worst, they don't show at all if the screen isn't positioned good enough during scrolling for them to show.

Sorry to say but it's a mess. :-/

**Comment by maboleth** [comment]
Here's my screencast to see how bad this is during scrolling.

Notice that NO image is shown during scrolling, only when I moved a bit, the images reappeared.


[screencast.zip](https://github.com/darktable-org/darktable/files/5053898/screencast.zip)

**Comment by ptilopteri** [comment]
@maboleth 
appears to me to just be the highlighting of the active image
you will notice that the background color of the image changes as you mouse over it.

this is a "feature" in dt.

**Comment by maboleth** [comment]
@ptilopteri Sorry, are you commenting on my screencast or the post above?

If it's about the screencast, those images I listed SHOULD BE displayed, I shouldn't be able to stare at the gray background with only overlays shown.

**Comment by ptilopteri** [comment]
@maboleth 
have you given the cache time to catch up with the display?  When accessing a large collection or on a slow system there is a delay displaying thumbnails until the cache provides them.

**Comment by maboleth** [comment]
@ptilopteri 

My system is based on Nvidia 1060 GPU with 6gb ddr5, AMD Ryzen 3700x, 32gb RAM and M2 ssd drive. Needless to say it's blazingly fast, everything is more or less an instant load.

Further, DT 3.0.2 had absolutely no problems showing ANY image of ANY size or collection.

**Comment by Germano0** [comment]
I heavily edited first post to add video samples and improve description

**Comment by mir07** [comment]
Could it be related to my issue somehow? https://github.com/darktable-org/darktable/issues/5922

**Comment by AlicVB** [comment]
@Germano0 : Thanks for your videos, I can reproduce at least the first bug and confirm your findings. I'll have a look to fix that asap !

**Comment by Germano0** [comment]
@AlicVB thank you for your work on darktable!

**Comment by AlicVB** [comment]
@Germano0 : I reopen the issue, because my fix doesn't fix the problem completely. Especially it doesn't fix the background problem, neither the zoom=1 issue.
I'll try to fix this soon, but that may require a little more time, as I fear that it will need some refactoring in the code...
