### ISSUE TITLE
Darktable 3.2.1 Segfaults

### ISSUE THREAD

**Issue by solloron1** [darktable-org/darktable#5917]
**Describe the bug**

When trying to launch darktable it segfaults and generates a crash report

**To Reproduce**

**Expected behavior**

The application launches

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Arch Linux Kernel 5.7
 - Tried with both
 - Intel HD Graphics 5500

**Additional context**

[darktable_bt_KGJ9O0.txt](https://github.com/darktable-org/darktable/files/5054558/darktable_bt_KGJ9O0.txt)

**Comment by solloron1** [comment]
Downgrading clang allows me to load darktable again.

clang 9.0.1 was the culprit.

**Comment by ptilopteri** [comment]
consider closing the issue

**Comment by johnny-bit** [comment]
I have clang 9.0.1 and haven't noticed any issue... 

I'd rather think it's similar to #5864

**Comment by pitbuster** [comment]
It seems the same as this https://github.com/darktable-org/darktable/issues/5842

**Comment by johnny-bit** [comment]
Closing - clang fault detected ;)
