### ISSUE TITLE
Incorrect lens identification

### ISSUE THREAD

**Issue by drt102** [darktable-org/darktable#5919]
I have a Sigma 60-600mm F4.5-6.3 DG OS HSM lens which is incorrectly identified by Darktable (all versions including latest 3.2.1 release) as a Sigma 18-35mm f/1.8 DC HSM | A. To check what is in a Canon RAW file from my 5D Mk III, I downloaded the latest Windows binary of Exiv2 (v0.27.3) and this gave the following output:

Exif.CanonCs.LensType                        Short       1  Sigma 14-24mm f/2.8 DG HSM | A
Exif.CanonCs.Lens                            Short       3  60.0 - 600.0 mm
Exif.CanonCs.MaxAperture                     Short       1  F6.2
Exif.CanonCs.MinAperture                     Short       1  F31

but also later in the output:
Exif.Canon.LensModel                         Ascii      74  60-600mm F4.5-6.3 DG OS HSM | Sports 018

and:
Exif.Photo.LensSpecification                 Rational    4  60/1 600/1 0/1 0/1
Exif.Photo.LensModel                         Ascii      41  60-600mm F4.5-6.3 DG OS HSM | Sports 018

What is really confusing is that none of this corresponds with the lens identified by Darktable.

Which fields from the RAW file, pulled out by I am assuming Exiv2, does Darktable use?

**Comment by MStraeten** [comment]
Have a look at https://github.com/Exiv2/exiv2/issues/1192#issuecomment-622020760

**Comment by matt-maguire** [comment]
Added this information to the User Portal page in the darktable wiki:
https://github.com/darktable-org/darktable/wiki/User's-portal

**Comment by Nilvus** [comment]
Related to exiv2 and fix proposed in comments. I close.
