### ISSUE TITLE
crop&rotate aspect selection in 3.2.1 does not work properly

### ISSUE THREAD

**Issue by negyvenot** [darktable-org/darktable#5921]
**Describe the bug**

selecting any aspect other than freehand or square in darktable 3.2.1 does not work properly anymore. The chosen aspect is selected but for the opposite orientation.

**To Reproduce**

1. Go to crop and rotate
2. Click on the aspect dropdown
3. Scroll down to original image and select
4. See error: on a landscape image a portrait crop window is shown, and vica versa

**Expected behavior**

A proper crop window (i.e the full image selected with the original image size)

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Debian 10.5

**Additional context**

- other users confirmed the error on darktable-users list

**Comment by maboleth** [comment]
Can confirm this.

So far DT 3.2 is so buggy it's like beta or alpha. Totally not usable for a working professional environment.

**Comment by Mark-64** [comment]
Confirmed on DT 3.2.1 Windows 10

**Comment by TurboGit** [comment]
I cannot reproduce, what is the sequence of operation to reproduce?

**Comment by TurboGit** [comment]
I see it reproduces only after having selected "freehand". Workaround is simple, in this case click on the icon to rotate the crop area.

**Comment by TurboGit** [comment]
> My only hope is that devs will see these usability bugs and quirks and act asap.

Or you can do it, or at least start sending helping comments!

**Comment by Mark-64** [comment]
> I cannot reproduce, what is the sequence of operation to reproduce?

It's kind of weird, when you first go into crop&rotate it works fine, but in my case if you reset the module and then select an aspect ratio from dropdown it swaps widht and height

**Comment by maboleth** [comment]
> > My only hope is that devs will see these usability bugs and quirks and act asap.
> 
> Or you can do it, or at least start sending helping comments!

Sorry if I sounded pissed. But I have been using v3.2 no more than 2mins and ran into numerous bugs and quirks. As soon as I loaded my images in the lightable that is. There were so many bells and whistles in 3.2 patch notes, my hopes were very high. But so far, I'm back to 3.0.2 on my production PC. It simply is faster to use and just works.

As for this bug, not sure if your workaround is 'simple' or fast enough. If I understood you right that is. When I click on the rotate icon, while the aspect does return to horizontal, it's not the size of the image but smaller... I have to raise and change at least 2 sides to finally get what I wanted. Multiply that to 100 images that need aspect cropping per session and time wasted is very high.

**Comment by TurboGit** [comment]
@elstoc : I think this issue may be due to 2919f88a073588d3c157e2d64ce29d9d86c28e27. Can you have a look? TIA.

**Comment by elstoc** [comment]
> Now I see you put this in 3.4 milestone... so this bug will stay until december? Ouch.

The best way to ensure that bugs are identified and fixed before a release is to help us with the testing. The github README has instructions as to how you can build your own copy from git master and keep it separate from your working copy.

**Comment by esperlu** [comment]
Nice patch. Thanks
