### ISSUE TITLE
Unhandled exception in 3.2.1 on Windows 10

### ISSUE THREAD

**Issue by Yo55arian** [darktable-org/darktable#5923]
Hi, I've experienced a crash when using the tone curve module. I was able to repeat the crash another time when I tried stepping through my processing steps again. I've attached both of the backtrace files.

I'm using:
- Windows 10
- darktable 3.2.1

[darktable_bt_V4MOP0.txt](https://github.com/darktable-org/darktable/files/5058466/darktable_bt_V4MOP0.txt)
[darktable_bt_W2Q8O0.txt](https://github.com/darktable-org/darktable/files/5058468/darktable_bt_W2Q8O0.txt)

**Comment by Mark-64** [comment]
From the backtrace errors seem to be in tone equalizer. I can't reproduce on Windows using tone curve.
since you have a repeatable crash, can you provide a sample image and xmp or detailed steps ?
Thanks

**Comment by Yo55arian** [comment]
Github won't let me upload RAF or XMP files so have dropped them onto Google Drive. I've used tone equalizer in the workflow but the crash triggered when I was using the tone curve. Hope that helps track it down.

[https://drive.google.com/drive/folders/1EWjNEY-J0CP53bej5rb5ep3SSkGG0Mq0?usp=sharing](https://drive.google.com/drive/folders/1EWjNEY-J0CP53bej5rb5ep3SSkGG0Mq0?usp=sharing)

**Comment by Mark-64** [comment]
Nope, I still can't reproduce.
When I open you files, DT complains it doesn't find a 3D LUT file that are using, but apart from that, no error fiddling with tone curve or tone equalizer

**Comment by Yo55arian** [comment]
I just had a try with another image file to check I could trigger the issue again, here are my steps in order that led to the problem:

1. Tone equalizer adjusted
2. RGB levels adjusted
3. Tone curve adjusted (with a parameter and brush mask added)
4. Error triggered on shadow and highlights then being turned on

After trying this a few more times, it seems that the error hits when you activate a module after the tone curve (maybe tone equalizer needs to be activated first?). It doesn't happen all the time. I'll have another look tomorrow and see if I can hone it down more.

Here's another backtrace in case it's useful.
[darktable_bt_8NF9O0.txt](https://github.com/darktable-org/darktable/files/5059587/darktable_bt_8NF9O0.txt)

**Comment by Moranana** [comment]
Hello, I'm unsure if I should open a new issue for this - it seems like I get the same type of crash as OP. (Windows 10, darktable 3.2.1.). I have attached the backtraces below and the NEF and XMPs on Dropbox - I think the _01 is the one in which the crash occurs.

[darktable_bt_P2V4O0.txt](https://github.com/darktable-org/darktable/files/5070698/darktable_bt_P2V4O0.txt)
[darktable_bt_V4MOP0.txt](https://github.com/darktable-org/darktable/files/5070699/darktable_bt_V4MOP0.txt)
https://www.dropbox.com/sh/l9gkw8ltbrypjah/AAAsLR01nhTkouEdBBPJL0M-a?dl=0

**Comment by coffeeandspaceships** [comment]
I think this may well be something common in Darktable triggering the problem, because the two people reporting problems above are on DIFFERENT vendors (nVidia and AMD.)

@Mark-64 What GPU do you have?

**Comment by johnny-bit** [comment]
No longer reproducible on Windows with darktable 3.4.1.1 - I think fix for such crashes got included in 3.4 release cycle.
