### ISSUE TITLE
Backspace while drawing a mask switches to previous image of filmstrip

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5932]
**Describe the bug**
When during creating a mask the backspace key is pressed the previous image is loaded and the mask is lost.

**To Reproduce**
1. Have at least 2 images
2. select not the first one in darktable
3. draw a mask using the path tool
4. press backspace

**Expected behavior**
Creating a path can be quite time consuming. All actions that unintentionally abort the mask creation (so without confirmation dialog) are highly questionable and most likely not in the interest of the user.

**Platform (please complete the following information):**
- Manjaro
- Darktable master (3.4+)

**Additional information**
I might add that the reason for me to press backspace was that I wanted to get rid of the last point added to the path. Even though there might be a key doing that job or not the behavior is not nice because work is just lost. And this is what users are getting upset about (Usability).

**Comment by parafin** [comment]
So how should backspace be handled? Don't do anything? Or switch to previous image but save the mask?

**Comment by codingdave** [comment]
Valid question. 
1. Ignore backspace: Backspace might be an intended action and stopping the user from doing it is not nice (but I have no clue what backspace usually does)
2. Switch to previous image and save the mask: In a typical workflow creating the mask is the first, not the last action. So we can assume the edit is in an incomplete state. The user will get back to that image and continue either by using that mask or finishing it. Now, how easy is it to continue a mask that was started already? I dont think it is very easy. 

Alternative:
3. Ask the user for confirmation that he will loose the mask

**Comment by chhil** [comment]
Maybe the backspace action should be based on the current area/window in focus.

**Comment by codingdave** [comment]
I was looking for all the meanings of backspace on a default config. Looks like backspace is only used for views>darkroom>image back. So I think this bug can be rephrased to **Turn off "image back" during an operation** and the only operation I have yet identified is creating a mask. There might be others, though. 

Since we now have the understanding that this is a general pattern I am happy to say I would like to have solution 1 implemented: Whenever an operation is ongoing the "image back" key is turned off.

**Comment by johnny-bit** [comment]
I'd say that #5943 is superset of this and this can be closed in favour of #5943, agreed?
