### ISSUE TITLE
Windows 10: switching from lighttable to darkroom and back again causes visual chaos

### ISSUE THREAD

**Issue by tuurke63** [darktable-org/darktable#5934]
**Describe the bug**

 When you switch from lighttable to darkroom and back again, the large image which was edited in the darkroom stays visible as an unwanted "background" behind the thumbnails in the lighttable. 

**To Reproduce**
-Double-click  an image in the lighttable to edit it in the darkroom.
-Go back to the lighttable
-The icons of the light table are "on top of" the previously edited image and the lighttable becomes confusing to work with.

**Expected behavior**
-The icons in the light table should be on an even background.

**Screenshots**
See attachment.
![2020-08-12 10_45_57-darktable](https://user-images.githubusercontent.com/36470533/89995298-995f2080-dc89-11ea-9ea3-e7e963e2a25e.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1, installed from official setup.
 - OS: Windows 10 x64 prof.
- Graphics: Nvidia Quadro T2000 driver v. 26.21.14.4145 and Intel UHD graphics 630, driver v. 26.20.100.7985
- OpenCL? No idea if activated.

**Comment by TurboGit** [comment]
We will certainly need more information. For sure this is not expected and I bet no one has seen that (you can't miss this issue!) up to now otherwise it would have been reported and fixed.

Maybe Windows 10 specific ? Or due to some specific graphic card, driver?

Let's see if someone else has the same issue, it would be good to know on which setup/machine.

**Comment by tuurke63** [comment]
The machine is a Dell Precision 5540, 32 GB Ram, cpu=Core i9-9880H (8 cores + hyperthreading).

I think I may have something reproducible:

**I start darktable with the "--library" parameter.** 

This is because I use Darktable mainly for holiday photos and I really don't want one huge database containing all pictures, I prefer to have one library per "project".  So each of my picture folders contains a small homemade batch script (darktable.cmd) that launches Darktable and tells it to use the library db of that particular folder.  The script contains only one line:

"%programfiles%\darktable\bin\darktable.exe" --library "%~dp0library.db"


I have just discovered that when I launch Darktable the "normal" way, without specifying any library, the lighttable behaves normal. But I really want to have the possibility to work with multiple libraries ....

**Comment by mir07** [comment]
Same issue as in this bug: https://github.com/darktable-org/darktable/issues/5922

**Comment by TurboGit** [comment]
And #5922 is fixed/closed, so closing also this one.
