### ISSUE TITLE
dt3.2.1 after invert, basecurve gui color picker does not work as expected

### ISSUE THREAD

**Issue by negyvenot** [darktable-org/darktable#5935]
**Describe the bug**

The gui color picker in the base curve module picks wrong values after inverting an image. In fact it seems to pick the values for the original uninverted image. (Use case: I "scan" my analog film negatives with a dslr, and invert and tune them in dt)

**To Reproduce**

1. open a raw file which contains a shot of a negative film slide
2. optionally white balance so the film base color is white
3. apply the invert module using the picker. select an area where the film base color is visible
4. goto rgb curves, select rgb independent channels
5. go to the red channel
6. pick a dark spot on the image
7. see that the vertical bar is placed on the far right completely off of the histogram. (Hint: the vertical bar is placed so it shows the R value for the image BEFORE the inversion)

**Expected behavior**

Do the exact same procedure in dt3.0.2 and see that the vertical bar is placed at the expected position

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Debian 10.5

**Additional context**

**Comment by negyvenot** [comment]
I cannot reproduce the problem properly anymore. I must have done something wrong.

**Comment by Nilvus** [comment]
So please think about closing this issue. That will help developers to see remaining issues.

**Comment by negyvenot** [comment]
closing as cannot reproduce
