### ISSUE TITLE
Crash (segfault) during export from Nikon NEF to JPG

### ISSUE THREAD

**Issue by Darker** [darktable-org/darktable#5937]
**Describe the bug**
This is a crash report.

**To Reproduce**
Reproduced by exporting multiple pictures from NEF to JPEG. Happens every time. Is not caused by a specific picture, the crash occurs at different picture every time.

Crash always occurs in libbilateral.dll `D:/build/darktable/src/iop/Permutohedral.h`, however the line differs between crashes.

**Platform (please complete the following information):**
Windows 10 64bit, NVIDIA GeForce GTX 1060 3GB, AMD FX-6300

**Crash report:**

[darktable_bt_6J0LP0.txt](https://github.com/darktable-org/darktable/files/5062422/darktable_bt_6J0LP0.txt)
[darktable_bt_WCOEP0.txt](https://github.com/darktable-org/darktable/files/5062423/darktable_bt_WCOEP0.txt)

**Comment by Darker** [comment]
Note that it was possible to export all pictures by starting darktable again and continuing export from where it last crashed. I blame the C-style code in `Permutohedral.h`

**Comment by jenshannoschwalm** [comment]
Please note you are using a very old dt version! Please update and close this issue before reporting bugs for 3.2

**Comment by Darker** [comment]
Old version.
