### ISSUE TITLE
PR #5691 breaks soft limits for saturation in Color Balance

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#5939]
DT 3.3 in Ubuntu 20.04
After #5691, shadows/midtones/highlights saturation sliders in Color Balance have all a soft max of 5%, while they should be 5% / 20% / 25%

**Comment by dterrahe** [comment]
Sorry, missed the change in saturation limit. Will submit an easy fix shortly (although chasing a bug report on OSX now).
