### ISSUE TITLE
[3.2.1] Lighttable culling no longer retains zoom when advancing to next image

### ISSUE THREAD

**Issue by matt-hoskins** [darktable-org/darktable#5941]
Under 3.1.x in culling if you zoomed in on a pair of images (fixed zoom) it would match the zoom on both. If you then scrolled to compare another pair of images then the zoom level (and offset of zoom) was retained. I found this particularly useful if I was interested in looking at a burst of 5+ images and comparing the detail in a small area (e.g. with animals in motion to spot where focus on the eye was good out of a sequence).

In 3.2.1 if I have a pair showing and zoom in then it zooms in the pair, but if I then scroll on to the next then although it retains the zoom on the one out of the pair still showing, on the newly shown one the zoom is reset to "fit".

I suspect this is a bug rather than intended!

(I'm running under Mint linux using the deb from http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04/ )

**Comment by matt-hoskins** [comment]
Perhaps this "simplify" work is what got rid of it? It looks like there was a notion of global zoom (table->full_zoom) which got removed...
https://github.com/darktable-org/darktable/commit/d3df45b10aa7cde79b5d5e9a3e9d248164f347ff

It'd be a real shame if that feature is gone for good as it is really annoying now to have to zoom and pan afresh as I advance through a burst set to check an area of interest (plus unless I move on two images, it starts to mess with the already zoomed in previous image). I can't load the whole burst set and zoom in to compare at once - culling is limited to 4 for zoom it seems, and my screen is only HD res so I prefer to stick with two side by side and just advance through).

I'm going to revert back to 3.1.0 for now

**Comment by mfg92** [comment]
The preview mode (W or  ALT + W) in dt 3.2.1 has a similar problem (it is a problem at least in my opinion): When zooming (CTRL + mouse wheel) into one image and then switching to another image (using the mouse wheel) the scale is resetted. In dt 3.0.x the scale was retained when switching images in the preview. I used this to compare the sharpness of similar photos.
So in my opinion the behavior should be like in dt 3.0.x. If the change was intended, then it would be great if:
- there would be a setting to get the old behavior or
- a modifier key to keep the scale when switching images

**Comment by AlicVB** [comment]
Completely forgot to implement that. I'll have a look.
