### ISSUE TITLE
Latest dev version 99c3ea862 fails to compile on Windows

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#5942]
**Describe the bug**
On Mingw the latest dev version fails to build. The build stops at an error
```
make[2]: *** No rule to make target 'C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/libgomp.dll.a', needed by 'src/libdarktable.dll'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:2272: src/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

**To Reproduce**
1. Update Mingw to latest versions (gcc-10.2)
2. Build

**Expected behavior**
I have `/mingw64/lib/gcc/x86_64-w64-mingw32/10.2.0/libgomp.dll.a` available and I would have excpected that a newer version would have been used.

**Platform (please complete the following information):**
 - Darktable Version: 3.3-99c3ea8
 - OS: Win10-64

**Additional context**
Builds ok, on my Virtual Ubuntu 20.04

**Comment by johnny-bit** [comment]
make sure your build and destination dirs are empty. sometimes cmake cache can introduce such problems.

**Comment by juhavlintula** [comment]
Thank you, that was the problem. Recreating build directory helped.
