### ISSUE TITLE
Turn off "image back" during an operation

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5943]
**Is your feature request related to a problem? Please describe.**
https://github.com/darktable-org/darktable/issues/5932
Creating a mask and unintentionally triggering "image back" will end up losing the mask and all the work spent on it.

**Describe the solution you'd like**
Detection of what is an operation (e.g. creating a mask) and turning off certain features (starting with "image back" for this feature request) that would end up in losing the work spent on the operation.

**Comment by junkyardsparkle** [comment]
Isn't "image forward" just as dangerous as "image back" in this regard?

**Comment by codingdave** [comment]
Sounds like. Are there any other features that should be listed here?

**Comment by johnny-bit** [comment]
I'd recommend: turn off actions that might interfere with ongoing operation unless that action is explicit cancel of operation

eg: when drawing a path or dragging a brush - no image switching. There are hardly any other actions that are so sensitive.
