### ISSUE TITLE
Upgrade from 3.0.2 to 3.2.1 destroys order of modules

### ISSUE THREAD

**Issue by A-Herold** [darktable-org/darktable#5945]
**Describe the bug**

My workflow in 3.0.2

I'm using parametric masks very early in my workflow. This way the definition of the mask does not depend on global changes I am applying later. If I would do it in opposite order, I would constantly need to adjust the parametric mask, which is very time consuming and inconvinient. I'm very happy with my workflow, and I'm glad that I can do this with darktable.
The following screenshot shows the (constructed) example. The module "tone curve parametric mask" is below "shadow and highlights“: 
https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=Bildschirmfoto+2020-08-13+um+07.11.05.png
And here is the same situation with highlighted mask: 
https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=Bildschirmfoto+2020-08-13+um+07.11.28.png

Upgrade to 3.2.1

After upgrade to 3.2.1 the order of modules was very different from what I saw in 3.0.2. For me that means, that the parametric masks of hundreds of images are not the same as in 3.0.2. Finally that means, that the processing of some hundred images is destroyed now.
Here is the screenshot of the example image after upgrade to 3.2.1. Module "shadow and highlights" is now below "tone curve parametric mask", which destroys the parametric mask of this module:
https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=Bildschirmfoto+2020-08-13+um+07.16.33.png
The same with highlighted mask: 
https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=Bildschirmfoto+2020-08-13+um+07.16.52.png
After changing the module order to "legacy" it became worse. Now are two other modules before "tone curve parametric mask“: 
https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=Bildschirmfoto+2020-08-13+um+07.17.26.png
And again, the same with highlighted mask: 
https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=Bildschirmfoto+2020-08-13+um+07.17.47.png

These are the hints I got and I have already tested:

* changed setting of Preferences/processing/auto apply pixel workflow
* changed module order from custom to legacy

**To Reproduce**

1. Edit an image 3.0.2: activate and move "tone curve" below "shadows and highlights". Activate "shadows and highlights".
2. Upgrade from 3.0.2 to 3.2.1
3. Check order of modules. Should be the same as before.

**Expected behavior**

Order of modules should not change when upgrading from 3.0.2 to 3.2.1.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 
 - OS: Mac OS X 
 - 
 - 

**Additional context**

**Comment by Nilvus** [comment]
@pahervin: some things have been fixed about XMP/database updates in actual master. So many bugfixes had been made about many things including upgrades since.

I close this issue as it's probably fixed. I suggest you to update and if needed test again with 3.6 when it will be released. Feel free then to reopen (or ask for it) if you still reproduce (and update title so!). Thanks.
