### ISSUE TITLE
Darktable 3.2.1 Installing Issues

### ISSUE THREAD

**Issue by cerlienkus** [darktable-org/darktable#5946]
**Describe the bug**

Hello everyone.
I'm having building issues compiling version 3.2.1 from the official tar.xf file I've downloaded.
After launching, the build shell ends with configuration errors.
I'm providing the build shell output, the CMakeError.log and the CMakeOutput.log.
Can someone help me finding what I'm missing in my system?

Thanks in advance
Maurizio 

**To Reproduce**

**Expected behavior**

**Screenshots**

This is the log after the shell execution:

[log_20200813.txt](https://github.com/darktable-org/darktable/files/5068105/log_20200813.txt)

these are the CMakeError and the CMakeOutput logs:

[CMakeError.log](https://github.com/darktable-org/darktable/files/5068119/CMakeError.log)
[CMakeOutput.log](https://github.com/darktable-org/darktable/files/5068121/CMakeOutput.log)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 
 - OS: Ubuntu 18.04 Virtualized (Host machine is Windows 10 and VM Player is VirtualBox 6.1) 

 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment]
Main problem: `No xslt interpreter found` (i wonder why cmake didn't yell "Some external programs couldn't be found")

In order to fix your problem, you should install eitehr `xsltproc` or `saxon-xslt`. I think those are listed in dependencies?

**Comment by cerlienkus** [comment]
Hello,
this afternoon I've checked into the Ubuntu Sofware Centre and found out that today they updated the versioning from 3.0.1 to 3.2.1, so I've downloaded and installed it from there.
Thanks

**Comment by cerlienkus** [comment]
Hello,
This afternoon I've checked into the Ubuntu Software Centre and found out that today they updated the versioning. So I've downloaded and installed it from there.
Thanks for your help!
