### ISSUE TITLE
avif export not working (Flatpak)

### ISSUE THREAD

**Issue by nilsholle** [darktable-org/darktable#5950]
**Describe the bug**
The following error is produced when trying to export to an avif file using the latest Flatpak from Flathub:

[dt_exif_xmp_attach_export] /var/home/.../darktable_exported/IMG_8021_01.avif: caught exiv2 exception '/var/home/.../darktable_exported/IMG_8021_01.avif: Failed to open the data source: Datei oder Verzeichnis nicht gefunden (errno = 2)'
[imageio_storage_disk] could not export to file: `/var/home/.../darktable_exported/IMG_8021_01.avif'!

JPEG export works perfectly fine.

**To Reproduce**
1. Select image
2. Try to export to .avif

**Expected behavior**
Export should work.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 (Flatpak)
 - OS: Fedora Silverblue 32
 - OpenCL not activated
 - Intel Graphics

**Comment by KristijanZic** [comment]
I can reproduce the issue on my machine.

**Comment by ptilopteri** [comment]
fwiw: it is probably a problem with flatpak packaging as it does work with the proper version of libavif on linux as built from git and as packaged for openSUSE Tumbleweed.  flatpak may not include or include the proper version of libavif or may refer to your system's libavif which may or may not meet dt's requirements.

note that the dt dev's do not provide packaged versions.

have you tried the version for your distribution?  
  https://www.darktable.org/install/

**Comment by nilsholle** [comment]
I agree that this seems to be a problem with the flatpak packaging. However, flatpaks are self-contained and platform independent. The darktable flatpak must not depend on the system's libavif.

> have you tried the version for your distribution?
This is now how Fedora Silverblue (which may become Fedora Workstation in the future) works. In Silverblue, the operating system is fully read-only and applications are supposed to be installed using flatpak.

**Comment by nilsholle** [comment]
> note that the dt dev's do not provide packaged versions.

I see that this might be the wrong place for this issue. I will open one for https://github.com/flathub/org.darktable.Darktable.

**Comment by nilsholle** [comment]
New issue is here: https://github.com/flathub/org.darktable.Darktable/issues/64

I will close this one.

**Comment by hfiguiere** [comment]
libavif in the flatpak was built without encoding codec support. This is now fixed (as soon as the Flatpak build is published in a few hours)
