### ISSUE TITLE
Brush tool

### ISSUE THREAD

**Issue by komodo666** [darktable-org/darktable#5952]
Hello, if it's possible I'd like to have some brush tool like in LR where you can selectively brush with some opacity multiple times over one area to build up the density of the mask.

I don't now if it's clear what i mean. When i want to do Dodge and Burn it's easy way in LR. But it's not in DT. 

In LR I can make multiple low opacity brushes over and over and it will do desired effect.

As you can see I am not the only one who misses this feature.

https://www.dpreview.com/news/4037697648/open-source-raw-processor-darktable-updated-to-version-3-2?comment=1442022859

https://www.mail-archive.com/darktable-user@lists.darktable.org/msg09522.html

Thank you

**Comment by MStraeten** [comment]
you can do this in darktable simply with drawn masks in brush mode:
https://darktable.gitlab.io/doc/en/blending.html#drawn_mask

> Brush size, hardness and opacity can be changed by scrolling, shift+scrolling, and Ctrl+scrolling, respectively, either before you start drawing or at any time during the operation. Likewise you can use keys [ | ] to decrease/increase brush size, { | } to decrease/increase hardness, and < | > to decrease/increase opacity.

it's worth to RTFM ;)

**Comment by elstoc** [comment]
> multiple times over one area to build up the density of the mask

You can do this with drawn masks but it's a bit cumbersome with vector masks. I think what @komodo666 is requesting is the ability to paint a raster mask with several low opacity brush strokes.

**Comment by komodo666** [comment]
> > multiple times over one area to build up the density of the mask
> 
> I think what @komodo666 is requesting is the ability to paint a raster mask with several low opacity brush strokes.
> 
> Probably a duplicate of #4459.

Yes, that's exactly what i mean. And I think that drawn mask with brush in DT does not have this option.

**Comment by elstoc** [comment]
If you think #4459 is asking for the same thing you are, please can you close this as a duplicate and perhaps add a comment to that request instead.

**Comment by MStraeten** [comment]
instead of thinking, the drawn mask by ba brush doesn’t have this option - just try it. It might not be exactly the same but might be worth a try ;)

**Comment by elstoc** [comment]
It's things like the ability to paint a bit then erase a bit, then paint a bit more, all with low-opacity brush strokes that build up gradually, without having to create 100s of path masks. Artistic stuff. It's really hard with vectors.

**Comment by MStraeten** [comment]
Thats true and i personally would like to have this feature too, but i doubt this will be there in a short term since this is a major change also in dealing with pixel data in sidecar files. 
So it’s worth to make the best from existing tools until there’s an alternative ( see #4459)

**Comment by komodo666** [comment]
Ok. I'm glad we now understand what the purpose of this issue is.
So I will close this as a duplicate and wait to see if in the future this feature appears in DT :-)
