### ISSUE TITLE
with display filtered to "All except rejected", rejecting an image in darkroom does not advance to next image

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5968]
openSUSE Tumbleweed 20200813
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git152.6930e52c6
OpenCL off

When I have the current display filtered to show "all except rejected" and work a group of images in darkroom and find the current image unacceptable, tagging it as "rejected" always advanced to the next image in the group.  Currently this is not happening.

Previous and I know not when it changed, when rejecting an image it would disappear from the display and the next image in the goup would appear.  A behaviour which I liked and desire.

**Comment by junkyardsparkle** [comment]
IIRC this changed when the new lighttable was added. I also found the previous behavior to be convenient. When moving forward through images in darkroom view, I don't find it to be a big deal to hit the spacebar to advance after rejecting, however - if I happen to want to go *backwards* from a still-displayed image which has just been rejected, using the backspace key, the progress is to the next image in a forward direction, exactly as when using spacebar. I find that behavior particularly annoying/confusing.

**Comment by AlicVB** [comment]
This is done by design and as already been discussed before (I don't remember the issue number)

@junkyardsparkle : not sure to understand your last point : you say that when you hit previous key, it show the next image ?

**Comment by ptilopteri** [comment]
So when working in darkroom mode with "all except rejected" and one rejects an image, they have no knowledge that the rejection succeeded because the image is still there, no screen flash, no longer the image disappears (which should happen).

I guess I missed the "discussion" and it surely was not in this context.  And when the rejection is applied in lighttable mode, the image disappears but the selection is not advanced.

this "selection" action, lack of selection, is not intuitive and not what one would expect despite "prior discussion".

**Comment by junkyardsparkle** [comment]
> you say that when you hit previous key, it show the next image ?

Yes, in the specific situation described in this issue: when still viewing an image in darkroom view after it has been rejected, when the "view" filter is set to "all except rejected". It works normally otherwise. This happens when using XFCE desktop, so it isn't one of those weird fluxbox bugs. ;-)

The behavior when rejecting the last image in a film roll is that you end up on the *first* image when using the shortcut for either "next" or "previous", which is also disorienting, but IIRC that also happened immediately upon rejecting the last image in older versions, so not really a new issue.

**Comment by ptilopteri** [comment]
But with "all except rejected" after rejecting an image, the next should be displayed w/o any other keyboard or mouse action.  I do recall "next/previous" jumping to the first image in the set

**Comment by AlicVB** [comment]
@junkyardsparkle : so that's a bug. I'll have a look
@ptilopteri : as said, this has changed on purpose. I understand your point, but on the other hand, darkroom is not designed to do culling...

**Comment by ptilopteri** [comment]
@AlicVB : it is not about culling but expected and continuing past behaviour.  And it breaks workflow by not being able to know your actions, rejection, are effected.
And I do utilizing culling, before I edit any photos.

**Comment by AlicVB** [comment]
> it is not about culling but expected and continuing past behaviour

well, not really, you just need to press another key ;)



> And it breaks workflow by not being able to know your actions, rejection, are effected.

fully agree here, but not only for this very specific cases : this is the same if you rate images to something different... Maybe adding a log message ? Can you please open a feature request so the idea is not loose ?

**Comment by ptilopteri** [comment]
I will open a "feature" request citing this bug/issue report.

But this is not a feature request but reporting the absence of a feature that was present and has been lost, ie: it is a bug./issue!

One should never be able to work on an image that is not "selected"!

See #6037

**Comment by ptilopteri** [comment]
tks, will test when it is available, 
otherwise, I don't know how to get it until git is updated

**Comment by ptilopteri** [comment]
fwiw: current g9a884bf04 git master works in culling mode as it should/did in darkroom mode.
rejecting an image with filter "all except rejected" disappears the rejected image and makes next image active.  I don't know that "selected" is proper description.

**Comment by edio** [comment]
> rejecting an image with filter "all except rejected" disappears the rejected image and makes next image active. I don't know that "selected" is proper description.

I do not see this behavior on 3.2.1. After rejecting the next image is not selected. Pressing space selects the first image in the filmroll
