### ISSUE TITLE
working image does not remain selected when switching from darkroom to lighttable

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5971]
openSUSE Tumbleweed 20200813
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git154.412452a19
OpenCL off

when I switch from darkroom view to lighttable, the active image is surrounded by a white edge but is not selected.  Switching back to darkroom requires reselecting the image that was active.  Previously this worked, but not now.

**Comment by AlicVB** [comment]
@ptilopteri : if your image is selected when entering darkroom, then it should be selected when switching back to lightable.
Otherwise, we have been very careful to not void user selection in "filmstrip" modes (culling, darkroom, etc...) So we effectively don't automatically select active image...

**Comment by ptilopteri** [comment]
but prior to the lighttable rewrite (I believe this is when the change effected), I could leave darkroom mode and return to same image.  But not now.  And on cannot enter darkroom w/o having an image selected.  And that selected image always changed as one proceeded through the collection within darkroom mode.  When leaving darkroom to lighttable, the last image in darkroom was "selected" and one could return to darkroom "to the same image".

one cannot do that anymore!  and should be able.

**Comment by AlicVB** [comment]
@ptilopteri : not sure to understand exactly what you mean (sorry for my English)
Do you mean that the following steps doesn't work for you ?
1. select 1 image
2. enter darkroom with this image (1+2 can be achieve by double-click)
3. in darkroom eventually switch to other images
4. go back in lightable
5. the last darkroom image should be selected

**Comment by ptilopteri** [comment]
Yes, but not always, sometimes the last image in darkroom is still selected.  

But if I have view set to "all except rejected" and I reject the current image in darkroom and move to lighttable, there is never a selected image.

One particular instance using keyboard to toggle from lighttable to darkroom with an image under the mouse pointer, when one returns to lighttable mode no matter if last image in darkroom is same or different, there is no selected image in lighttable

**Comment by AlicVB** [comment]
> But if I have view set to "all except rejected" and I reject the current image in darkroom and move to lighttable, there is never a selected image.

that's ok, as you can select an image not in collection anymore... This is of course related to the fact that you don't agree with how dt work in darkroom, see #5042 for the initial discussion about that point.



> One particular instance using keyboard to toggle from lighttable to darkroom with an image under the mouse pointer, when one returns to lighttable mode no matter if last image in darkroom is same or different, there is no selected image in lighttable

but in that case, you don't enter darkroom with a selected image, right ? So it's ok too.
Note that iirc you have a key accel to select the image with keyboard.

**Comment by ptilopteri** [comment]
How can you enter darkroom mode w/o a "selected" image.
This does not make sense.  And historically was never possible.

darktable will even complain and refuse to enter darkroom mode if you open a new collection and try to switch to darkroom w/o a selected image.

**Comment by AlicVB** [comment]
> How can you enter darkroom mode w/o a "selected" image.
> This does not make sense. And historically was never possible.

Try pressing "d" with the image you want to open "hovered" either with the mouse pointer on it, either by using navigation keys...
That feature is here for a long time too

**Comment by ptilopteri** [comment]
but "hovered" is not the same as selected.  A selected image is "selected" and if you move the mouse off the thumbnail area of lighttable view, it remains "selected" whereas a "hovered" image is no longer.

fwiw: I reconfigured "d" to delete and "x" to toggle lighttable<-->darkroom view many years ago.

**Comment by AlicVB** [comment]
I know the difference between hovered and selected ;)
It was just to answer your statement that it wasn't possible to enter darkroom without a selection. It is possible : deselect all images, hover one and press "d" (or "x" in your case)

**Comment by ptilopteri** [comment]
Sorry for delayed response.

I believe that for the most optimal work-flow that the image displayed in darkroom "must" become "selected" and if multiple images had been selected before entering dr, the next selected image should appear after rejection rather then the next image in the collection.

A "hovered" image if opened in dr should become "the" selected image and when leaving dr the last displayed image should be shown as the current "selected" image.

Currently if I select the first image of a collection, or any image, and move the dr and advance thru the collection, the displayed image in dr becomes the "selected" image and remains so when leaving dr.  If I select multiple images in lighttable and change to dr,  when I leave dr the selection is multiple images as selected previously.  This is inconsistent.  If one wants to retain the identity of the selected images prior to entering darkroom, he can color tag the selected images before entering darkroom or reduce the selection via "collect images".

tks for fixing #5968

**Comment by ptilopteri** [comment]
still relevant

**Comment by ptilopteri** [comment]
Sorry for delayed response.

I believe that for the most optimal work-flow that the image displayed in darkroom "must" become "selected" and if multiple images had been selected before entering dr, the next selected image should appear after rejection rather then the next image in the collection.

A "hovered" image if opened in dr should become "the" selected image and when leaving dr the last displayed image should be shown as the current "selected" image.

Currently if I select the first image of a collection, or any image, and move the dr and advance thru the collection, the displayed image in dr becomes the "selected" image and remains so when leaving dr.  If I select multiple images in lighttable and change to dr,  when I leave dr the selection is multiple images as selected previously.  This is inconsistent.  If one wants to retain the identity of the selected images prior to entering darkroom, he can color tag the selected images before entering darkroom or reduce the selection via "collect images".

tks for fixing #5968

**Comment by AlicVB** [comment]
@ptilopteri : please... there's no need to copy-paste your previous msg, it just add noise to the discussion...

I'm sorry but we are going round into circle in this issue. I've perfectly understand your problem and arguments but I'm sorry to say that I disagree with you : "real" user selection (1 image selection is not considered as real) should not be void in user back.

The above discussion hasn't be unsuccessful though, as we have found some glitches and possible enhancements (which are now merged in stable and master)

I'll let it open, just in case some dev comes with a genius idea to conciliate both points of view ;)

**Comment by ptilopteri** [comment]
it is still not possible or fails to keep last selected item, selected.
