### ISSUE TITLE
FR: darkroom - single button to discard history

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#5972]
Currently in the darkroom it is possible to discard history by selecting the 'original' entry and compressing the history stack.

It would be nice to have a one-button way to do this (it's perhaps not always obvious to new users).

I would suggest either a separate button immediately below 'compress history stack' or to use the 'reset parameters' button on the module header. I'd say the latter seems more consistent with the rest of the UI and has the advantage of not taking any extra screen space. Also a button beneath 'compress' could be pressed by accident.

Also now that selecting 'original image' has the effect of showing the image without white balance (due to #5449) it might be less jarring than the previous method.

**Comment by junkyardsparkle** [comment]
> Also a button beneath 'compress' could be pressed by accident.

Yes, the good thing about the existing inconvenient method is that it's difficult to do accidentally. Any new methods should probably also be difficult to do accidentally (I use a keyboard shortcut for this).

> Also now that selecting 'original image' has the effect of showing the image without white balance

I would call that "educational" rather than "jarring". ;-)

**Comment by johnny-bit** [comment]
Not to say this is in any way wrong but... why? Currently you can do one-click from lighttable and you can do 2 clicks in darkroom, both having clear use-cases. Having discard history option in darkroom UI would need either confirmation dialog (making it 2 step) or very clear message like "history discarded, press [shortcut] to undo" in order to avoid missclicks...

So... having said that - what would be the use-case and scenario here?

**Comment by elstoc** [comment]
> Not to say this is in any way wrong but... why?

Mainly to make it a bit more friendly/obvious for new users I suppose. As I say the current method isn't entirely obvious. 

> would need either confirmation dialog (making it 2 step)

You could use the 'ask before erasing images from disk / discarding history stack' preference to control whether to show a confirmation dialog so it could be switched off.

Questions like this are why I raised a FR rather than PR. If it's not wanted that's fine. But the 'reset parameters' method seems like a no-impact alternative that's perhaps a little more obvious.

**Comment by johnny-bit** [comment]
Yeah, that makes sense... Asking before discarding stack and having that as "reset params" for history module is decent no-impact and obvious way to implement that (and makes sense, since you use reset module params to clear snapshots too)

**Comment by johnny-bit** [comment]
@elstoc  - #6013 ?
