### ISSUE TITLE
macOS failure to open DT on primary user accout

### ISSUE THREAD

**Issue by a7hybnj2** [darktable-org/darktable#5976]
**Describe the bug**

I installed DT with `brew cask install darktable` I then tried to run it using my primary admin user account and I got the `downloaded from the internet, are you sure?` dialog which I hit `open` and then the DT icon bounced in my dock for a minute or so and stopped, when the icon stops there isn't a dot underneath the icon like other running apps have (see screenshot). It never opened any windows. When I `ps aux | grep darktable` there is `/Applications/darktable.app/Contents/MacOSdarktable`.

Now here is the odd part: When I switched to a new admin account and opened DT it opened pretty quickly and without issue.

Some things I have tried:  
I made sure the permissions on `~/.config` were correct.  
I copied the `workingUsers/.config/darktable` to non-working users config location and `chown -R $USER:staff` on it.  
I uninstalled via `brew` and installed via the downloaded .dmg

**Expected behavior**

I expect it to open on both user accounts. I am guessing it is some conflicting package but I cannot find anything and `console` doesn't show anything obvious.

**Screenshots**

<img width="218" alt="Screen Shot 2020-08-15 at 11 19 19 PM" src="https://user-images.githubusercontent.com/36831279/90325782-01de2400-df4e-11ea-9bd8-03ea9ec7fdbf.png">

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  macOS 10.15.6 (Catalina)
 -  AMD Radeon Pro 5500M 8 GB, Intel UHD Graphics 630 1536 MB

**Additional context**
DT has never been installed on this computer before.

**Comment by a7hybnj2** [comment]
Good news: I started my mac in safe mode `hold shift` during boot. And it appears DT is working fine. So, now I just have to enable each thing 1x1 and see what causes the issue.

**Comment by a7hybnj2** [comment]
I found it! I had a bad install of `dbus` that was loading via launchctl. I have no idea really what is going on but I removed dbus and unloaded the plist and darktable started right up.

**Comment by parafin** [comment]
Yes, dbus is known to break stuff on macOS, seems it's not configured correctly by default.
