### ISSUE TITLE
Icons crippled in file chooser

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#5981]
**Describe the bug**

whenever i open the file chooser (e.g. by importing new pictures or directories) i get crippled icons, please see attachment

**Screenshots**

![Bildschirmfoto 2020-08-16 um 14 43 44](https://user-images.githubusercontent.com/48620536/90334762-372b5600-dfd0-11ea-8540-c8f969848fcf.jpg)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Mac 10.14.6
 - OpenCL:  no
 - AMD Radeon HD 7970

**Additional context**

This bug appeared in version 3.0 if i remember well, but i am not sure. Anyway, this error popped up at some point, older versions of DT did not have this issue.

**Comment by parafin** [comment]
yeah, they look strange

**Comment by johnny-bit** [comment]
The weirdo icoms come from cairo/gtk problems on mac and are outside of darktable's scope... (IMO) opening a bug with gtk would be a good idea if you may. Also trying other gtk-based apps (such as GIMP) could help you see if the probelm is present across multiple gtk apps.
