### ISSUE TITLE
documentation: avif support

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#5982]
**Which new feature or section need to be documented/updated**

Document exporting images as AVIF

**Comment by cryptomilk** [comment]
I can't assign it to myself ...

**Comment by TurboGit** [comment]
I have assigned it to you. Thanks

**Comment by cryptomilk** [comment]
.

**Comment by TurboGit** [comment]
@cryptomilk : Any news about this ?

**Comment by cryptomilk** [comment]
https://elstoc.github.io/dtdocs/module-reference/utility-modules/lighttable/export-selected/

**Comment by cryptomilk** [comment]
If you search for tiff or jpg/jpeg you don't find any documentation beside the supported file formats and some hints.

**Comment by TurboGit** [comment]
Indeed, so nothing to do. Thanks for checking.
