### ISSUE TITLE
Lighttable - Filtering for "All except rejected" and rejecting an image by pressing R doesn't select the newly display image

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#5983]
**Describe the bug**
In the lighttable view, while in culling mode, filtering for "All except rejected" and then rejecting an image by pressing `R` correctly hides the reject image and shows the next image in the filmstrip. But it doesn't select that next image.

Pressing `R` again un-rejects the previous.

When moving the mouse after pressing `R`, the newly displayed image is selected.

This is very annoying  when rejecting images in a burst shot where you have 10 images or so but only 1 worth keeping.

**To Reproduce**

Consider images A, B, C

1. Open the lighttable
1. Set the view to `All except rejected`
1. Select image **A**
1. Press the `R` key to reject it
1. image **A** is rejected and hidden. The image **B** is displayed but not selected.
1. Press the `R` key
1. The image **A** is un-rejected and shown in the filmstrip. Image **B** is now selected.
1. Press the `R` key
1. Image **B** is rejected and hidden, image **C** is displayed but not selected.
1. Press the `R` key
1. image **B** is un-rejected and shown in the filmstrip. Image **C** is now selected.

**Expected behavior**

1. Open the lighttable
1. Set the view to `All except rejected`
1. Select image **A**
1. Press the `R` key to reject it
1. image **A** is rejected and hidden. The image **B** is displayed **and selected.**
1. Press the `R` key
1. Image **B** is rejected and hidden, image **C** is displayed **and selected**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 (from Flatpack)
 - OS: Linux Mint 19.3 (Tricia)
 - OpenCL not available

**Comment by jobec** [comment]
Maybe related to #5968  and  #5971  ?

**Comment by konig12** [comment]
I am hitting this issue as well with 3.2.1 in Arch linux. The reproduction steps above are pretty much exactly what I'm doing.

**Comment by MeisterKaos** [comment]
Following the reproduction steps on 3.2.1 Windows version, step 4 results in a grey screen (no image displayed) and a filmstrip-jump back to the beginning of the collection. See #6000

**Comment by AlicVB** [comment]
@jobec : should be fixed in PR #6145
