### ISSUE TITLE
Lighttable - Culling - Keyboard actions take effect on hovered over image in filmstrip instead of the displayed image

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#5984]
**Describe the bug**

When in the lighttable in culling mode, keyboard actions are unexpectedly applied to hovered over images in the filmstrip, instead of the image being displayed.

While this might be intuitive in the filemanager or zoomable light table mode, it's (for me atleast) unexpected behavior while culling and displaying a single image.
Even when displaying multiple images while culling, the keyboard actions should not take action on filmstrip images.

**To Reproduce**

1. Open the lighttable in culling mode
1. Move the mouse out of the displayed image and over a random image in the filmstrip
1. Press `R`
1. The hovered over image is rejected instead of the expected, displayed image.

**Expected behavior**

The displayed / selected image is being rejected

**Platform (please complete the following information):**
- Darktable Version: 3.2.1 (from Flatpack)
- OS: Linux Mint 19.3 (Tricia)
- OpenCL not available

**Comment by Nilvus** [comment]
I don't see issue there. The problem is on point 2:
"Move the mouse out of the displayed image and over a random image in the filmstrip"

Why moving the mouse out? The behavior is the possibility to "unselect" displayed image by moving the cursor out. That's wanted. So, if you do that, it remainsfirst selected images. That's allows different possible actions. Just be sur to be hover the image before doing actions on it.

**Comment by jobec** [comment]
Well, that is very confusing behavior. I know for sure that darktable lost many many users that gave it a try and ditched it because of such quirks and tought: my god... open source ... 🤦 
I know for sure I almost did (but then saw the price of lightroom...)

Just check the amount of issues open related to that (like #4558 and all linked ones). Those are only from people that find their way to github and care enough to actually open an issue about it.

**Comment by AlicVB** [comment]
discussion in #6025
