### ISSUE TITLE
Lighttable - Zoomlevel in overlay while culling is incorrect.

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#5986]
**Describe the bug**

When using ctrl+scroll to zoom in to an image in the culling mode of lighttable, the zoom level in the overlay on top of the image is wrong. The percentage is totally unrelated to, for example, the 100% when middle clicking in the darkroom view.

**To Reproduce**

ctrl+scroll an image while culling, look at zoom percentage in the overlay.

**Expected behavior**

Match the percentage with the actual zoom level of the image.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Linux Mint 19.4

**Comment by maboleth** [comment]
Umm... I can't reproduce this. Seems totally normal and working as expected.

**Comment by Nilvus** [comment]
Me too. Zoom level is ok and works as expected. No issue.

**Comment by jobec** [comment]
100% in darkroom
![darkroom-100pct](https://user-images.githubusercontent.com/16192496/90508112-615b5000-e157-11ea-82f2-925a92c2af5c.png)

100% in lighttable
![lighttable-100pct](https://user-images.githubusercontent.com/16192496/90508119-64eed700-e157-11ea-96cb-e2ad2ab9d9ca.png)

**Comment by parafin** [comment]
Is it High-DPI screen by any chance? Maybe 100% in darkroom is 1:1 pixels, while in lighttable it's 1:1 pixels taking scaling into account?

**Comment by jobec** [comment]
This is on a standard full HD laptop display.

I do notice that the percentage is different when I do the same action on my QHD monitor.
I'll do some more tests.

**Comment by jobec** [comment]
On my 27" QHD monitor it's absolutely wrong. It shows 19% while you can already see the individual pixels.

![QHD-monitor](https://user-images.githubusercontent.com/16192496/90546883-fb88bb80-e18a-11ea-906a-bfe053d015fe.png)

**Comment by jobec** [comment]
I can't get my head around it.
I deleted all `darktable` folders I could find in my home folder. Resetting all settings and imports.
Now the percentage is different, but still completely wrong.

![QHD-monitor-2](https://user-images.githubusercontent.com/16192496/90548048-ad74b780-e18c-11ea-9753-53f9c28cdcfa.png)
