### ISSUE TITLE
Lighttable - While culling, sending multiple selected images to trash only takes action on one image

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#5987]
**Describe the bug**

While in culling mode, if you select all images (like all rejected ones), be it by pressing ctrl+A or clicking "select all" on the right panel, you can only delete one image. Although all of them show as selected, the popup asks confirmation for only 1 image.

This bug is not there in the file manager or zoomable light table modes.

**To Reproduce**

1. Go to lighttable and set it to culling
1. Ctrl+A to select all images
1. In the right panel, select "selected image(s)" and click "trash"
1. The confirmation popup only asks to confirm for 1 image

**Expected behavior**

The selected action is done on all selected images.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Linux Mint 19.4

**Comment by RawConvert** [comment]
hi @jobec , whilst I haven't consciously used culling mode myself, this issue looks very similar to #4558 .  I have been advocating it gets fixed but some do not see it as a bug!

**Comment by jobec** [comment]
it looks like, in general, that the entire "what's selected" and what's being acted on logic in darktable is just totally different from what you commonly see in other software. Like my other 2 recent issues.

#5984 #5983

While the remark in the issue you link to has so truth in it (this is the darktable way). These kind of user experience quirks limit the adoption of it and count towards it learning curve.

**Comment by ptilopteri** [comment]
No, it is not.  There was major work to the lighttable view recently which apparently made some unintended changes.  I hope it will be resolved satisfactory fairly soon.  I have utilized dt for quite some years and the current action are very unexpected.

**Comment by AlicVB** [comment]
well, if I understand well he issue, it works as it should : 
in mode where you have filmstrip and "active" images (images that are shown in the centered view), actions are done only on those images. We certainly don't want to apply actions outside current images ! and... 
- those modes are not designed for doing batch actions.
- filmstrip can be hidden (and is hidden is most cases)
- many of those modes rely on selection for other things...

although there's some discussions to get another "image--act-on algo in #6025 I doubt that it'll change what you describe here. As said, it would be quite dangerous to apply actions to other images that the "active" ones...

anyway, I'm closing, as this discussion should better happen in #6025

**Comment by jobec** [comment]
Well, then it shouldn't be possible to do a ctrl+a and select all images in the filmstrip. Giving the impression you can select them.

If that behavior is gone, you won't make the link between "I selected all images there" and "My 'trash' actions acts on those selected images'

**Comment by AlicVB** [comment]
> Well, then it shouldn't be possible to do a ctrl+a

hmm... maybe you're right....
