### ISSUE TITLE
bug when I start Dartable

### ISSUE THREAD

**Issue by Cab74** [darktable-org/darktable#5988]
[darktable_bt_UC7OP0.txt](https://github.com/darktable-org/darktable/files/5080972/darktable_bt_UC7OP0.txt)

**Describe the bug**
Error message when I start Darktable : report enclosed

**To Reproduce**

Bug each time I double click on darktable.exe

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS:  Windows 10

**Comment by johnny-bit** [comment]
The fault is in your OpenCL drivers, namely intel ones. This means you have an integrated GPU which needs driver update and/or to be completely removed.

Several other people dealt with this problem, such as: 
- https://community.amd.com/thread/240586
- https://www.magix.info/us/forum/error-igdrcl64-dll--1219011/
- https://forums.tomshardware.com/threads/blackscreen-after-instaling-new-gpu.3542003/

this is NOT a darktable bug, but an error in `igdrcl64.dll` library from external driver. Please consider closing this bug report as it's not darktable's fault :)

**Comment by Cab74** [comment]
thanks for you answer, I have solved my oprncl issue by installing previous graphic card pilot,

thanks !
