### ISSUE TITLE
Ability to read embeded metaata and develop settings in DNG files

### ISSUE THREAD

**Issue by mikaelstaldal** [darktable-org/darktable#5992]
Currently, Darktable is able to import (some) metadata and develop settings from Adobe Lightroom from Lightroom's XMP files.

However, Lightroom refuses to create XMP files for DNG images, instead it embeds the metadata and develop settings into the DNG files.

It would be nice of Darktable could import the metadata and develop settings embedded in DNG files

**Comment by Timvrakas** [comment]
Bumping this. I have lots of photos in DNG, with embedded metadata. If I take an image in ARW (Sony), perform a crop and edit in Lightroom, and export as DNG, I'm left with a DNG file that has the Crop and edit data embedded. If I move to a new LR instance, the image will import and have the same crop/edit.

However, I can't get Darktable to interpret the metadata in the image. It does not respect the crop or edits. I don't need 100% fidelity on the DNG render, but I was hoping at least crop/exposure would migrate.

Am I missing something, or is this feature in the works?

**Comment by johnny-bit** [comment]
> Am I missing something, or is this feature in the works?

This is a feature request. Somebody would have to develop said feature. I closed your request #9960 since it duplicated this FR.

**Comment by orthorhombic** [comment]
Just came across this in my quest to load files from my old Lightroom catalog. Pulling XMP data from the DNG would be a nice feature. 

However, it also seems like there might be a bug here related to handling of the XMP data from the dng file even when extracted into a separate sidecar file, as alluded to by #9960 linked above. This occurs in Darktable 4.0.1 on Ubuntu 22.04.

Should this be a new bug ticket? Or might this be an improvement which comes from moving away from the deprecated "crop and rotate" module?




### How I reproduced:

Darktable will only attempt to load these develop settings from a sidecar file such as `filename.xmp` corresponding to `filename.dng`. This makes sense. So, I pulled the XMP data directly from a dng, into the appropriate filename and tested with both of the following commands:

```bash
exiftool -tagsfromfile filename.dng -XMP:all -o filename.xmp
exiftool -xmp -b -w xmp filename.dng
``` 

After doing so and loading the image into darktable, it attempts to load the parameters and fails. Hovering over the darkroom "crop and rotate module" under the history, I see the following:

```
angle 0 -> .2.8872
left 0 -> nan
top 0 -> nan
right 1 -> nan
bottom 1 -> nan
automatic_cropping on -> off
ratio_n -1 -> -2
ratio_d -1 -> -2
```

Following the instructions from #9960, I added the following tiff lines to one of the xmp files:
```
xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
tiff:ImageWidth="5792"
tiff:ImageLength="3804"
```
After doing so and loading the image into darktable, it attempts to load the parameters and fails. Hovering over the crop and rotate module in history, I see roughly the following, regardless of the values I put in for the tiff dimensions (as long as it isn't empty or 0):

```
angle 0 -> .2.8872
left 0 -> 0.0912
top 0 -> 0.1628
right 1 -> 0.8323
bottom 1 -> 0.8750
automatic_cropping on -> off
ratio_n -1 -> -2
ratio_d -1 -> -2
```

**Comment by LucaZulberti** [comment]
🆙
It would be nice to have

**Comment by hencrice** [comment]
This feature would be nice so that I don't have to back up multiple files.
