### ISSUE TITLE
Weird artefacts in highlights with filmic

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#5994]
Darktable 3.2.1, 64-bit Linux (Ubuntu), self-compiled.

**Observed behaviour:**
1. Import http://tech.kovacs-telekes.org/files/filmic-2020-08-16/gradient.png into darktable, along with its history http://tech.kovacs-telekes.org/files/filmic-2020-08-16/gradient.png.xmp
2. Make small adjustments to exposure
3. In the highlight portion of the displayed image, the bars are not homogeneous (I checked in Gimp where I generated the image, and I think they are). The pattern in the bars changes, sometimes some squares become darker while others lighter, sometimes vice versa.
Example screenshots:
![sample1](http://tech.kovacs-telekes.org/files/filmic-2020-08-16/Screenshot_20200816_211817.png)
![sample2](http://tech.kovacs-telekes.org/files/filmic-2020-08-16/Screenshot_20200816_211846.png)

Admittedly, the artefacts only appear with extreme processing settings; however, I'd still expect the mapping to affect all pixels in a bar the same way, which is not the case.

I selected one of the bars in Gimp, and Colors/Info/Colorcube analysis reported that it had a single colour (as it should, as I had used the Blur/Pixelize to create it from a gradient).

I tried to reproduce this with other modules that could affect contrast (to see if filmic is simply showing the affect of some image irregularities or ones introduced by a previous processing step), but was unable to do so.

**Expectation:**
Vertical bars are uniform (unless affected by the 'add noise in highlights' setting, but I set it to 0 and, according to 'display highlight recounstruction mask', no area of the chart is affected by reconstruction).

**Comment by ralfbrown** [comment]
Confirmed with git master.  Affected by the desaturation code, as setting Preserve Chrominance to No yields strong color casts in the areas where the luminance behaves non-monotonically when adjusting exposure.  Moving filmic's middle tones saturation slider also produces nonmonotonic behavior when Preserve Chrominance is No.

**Comment by johnny-bit** [comment]
Checked in `3.5.0+2484~g3fb45f9a4`

with v5 settings the problem is no longer present (using safe curves fro highlight and shadows) without preserve chrominance and no saturation boost. And areas are uniformly gray :)

Would you like to consider closing the issue?

**Comment by kofa73** [comment]
Confirmed, not reproducible with the settings listed above.
