### ISSUE TITLE
Rating issues in dt 3.2.1 

### ISSUE THREAD

**Issue by MeisterKaos** [darktable-org/darktable#6000]
**Describe the bug**
Rating or rejecting images in the lighttable view does not behave as expected from previous version 3.0 on my Windows system. I assume those issues are somehow connected, thus I'll describe them in one report: 
1. Despite having de-selected the option 'rating an image one star twice will not zero out the rating', the rating is not zeroed out when pressing 1 on the keyboard in lighttable view.
2. When rejecting an image while in single image view in either file manager or culling, the first image of the selection is displayed (instead of the next).

**To Reproduce**
1. Make sure 'rating an image one star twice will not zero out the rating' is de-selected in lighttable options.
2. Open a collection with several images in lighttable which are all rated 1-Star (default).
3. Select view >= 1Star. Set the display mode to 'culling' with 1 image displayed at a time.
4. For any image in the selection press '1' key to remove rating from the image: This has no effect.
5. Go to the 3rd (or any later) image in the selection and press 'r' key to reject the image: The image is properly rejected but the 1st image of the selection is displayed.

**Expected behavior**
- Rating should be zeroed out when pressing '1'.
- When rejecting an image, the next image should be displayed (when rejecting image 3, image 4 should be displayed)

The intended workflow (that worked before 3.2.1) would be to use 1-image culling or file manager to quickly go through a large collection of images and reject the bad ones, unstar the uninteresting ones and up-rate the special ones. If the view always jumps back to the first image this workflow does not make any sense any more.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL activated

**Additional information:**
- In culling with 2 images displayed, the 'r' rejection does not lead to a jump to the start.
- When undoing a rejection in 'rejected only' view with culling mode (for 1 or 2 images displayed), the culling view has no selection (grey display) and the strip also jumps back to the beginning but no image is selected. When changing to 'file manager' in this state, the view is empty and it is not even possible to select a new image. 
- For 3 or more images displayed the rejection never jumps.

**Comment by maboleth** [comment]
I have tested this and cannot confirm your findings.

However, rating an image one star twice will not zero out the rating option - does not work, whatever the mode, they will never zero out the ratings.

Everything else works as should.

Arch Linux, darktable git version.

**Comment by MeisterKaos** [comment]
I don't have a linux machine to test this. But I reproduced it on two differenten Windows 10 systems. Can anyone else using the windows version try this?

**Comment by l0f4r0** [comment]
Same behavior here. Rating twice doesn't remove the whole rating, even with option "rating an image one star twice will not zero out the rating" deactivated. No matter how many stars there are initially.

Darktable 3.2.1 on Debian 10 (Xfce 4.12.5).

**Comment by TurboGit** [comment]
This is fixed on master.
