### ISSUE TITLE
Broken links on the wiki

### ISSUE THREAD

**Issue by FSchiltz** [darktable-org/darktable#6002]
**Describe the bug**
The links to https://redmine.darktable.org/ in the developper wiki is throwing a 502 bad gateway error

**To Reproduce**
1. Go to https://redmine.darktable.org/
2. See error

**Expected behavior**
A link to the doc about how to build darktable

**Platform (please complete the following information):**
 - Darktable Version: N/A
 - OS: Windows 10

**Comment by ptilopteri** [comment]
@FSchiltz 
the link is broken because darktable has moved from redmine to github

**Comment by FSchiltz** [comment]
So the bug is that the github wiki is out of date because it still point to redmine.darktable.org

**Comment by greymont** [comment]
The CONTRIBUTING.md text references
https://redmine.darktable.org/projects/darktable/wiki/Coding_Style
but that link also produces a 502 Bad Gateway error.

**Comment by FSchiltz** [comment]
i'll gladly help to fix it but I don't know where the data are to move them to github
