### ISSUE TITLE
SegFault with OpenCL Intel NEO driver installed

### ISSUE THREAD

**Issue by sbolten** [darktable-org/darktable#6003]
**Description of problem**
Running a laptop with two graphic cards (1. GeForce RTX 2060 / 2. Intel Corporation UHD Graphics 630).
Opencl with Nvidia only is working properly. When using the NEO intel driver (intel-compute-runtime) darktable fails with a segfault. As soon as the intel driver is uninstalled the segfault disappears.
The combo of Nvidia+Intel both providing opencl was working properly about a month ago.

**Steps to reproduce**
1. install Intel NEO drivers (intel-compute-runtime under arch)
2. start darktable-cltest
3. Last line indicates an error

```
...
backtrace written to /tmp/darktable_bt_RUOMP0.txt
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Expected behavior**
darktable should recognize the Intel display card as a second opencl card

**Screenshots**
n/a

**Platform **
 - Darktable Version: 3.2.1
 - OS: arch linux (5.8.1-arch1-1)
 - OpenCL is activated
 - Graphics card 1/driver: GeForce RTX 2060 / nvidia 450.57
 - Graphics card 2/driver: Intel Corporation UHD Graphics 630 (Mobile) / intel-compute-runtime 20.30.17454-1

**Additional context**
 - Happend with dt 3.1.x as well
 - Happens also on a fresh install of dt
 - Darktable version taken vom arch repo

[dt-intel-compute-runtime.txt](https://github.com/darktable-org/darktable/files/5084835/dt-intel-compute-runtime.txt)
[darktable_bt_RUOMP0.txt](https://github.com/darktable-org/darktable/files/5084858/darktable_bt_RUOMP0.txt)

**Comment by parafin** [comment]
Report it to Intel...

**Comment by sbolten** [comment]
> Report it to Intel...

Thank you for the quick "reply". It did not really help unfortunately.
Asking myself why it worked weeks ago. Roled the intel driver back to older version - still no luck.
Anyway - seems like DT does not want to support Intel for whatever reason.

**Comment by parafin** [comment]
This it the only helpful thing you will get in darktable's bug tracker for this issue, since it is a bug in OpenCL driver. Or do you expect darktable developers to fix bugs in other software? Also, if you looked you would have found that this have already been reported several times (see #5988, #5875).

**Comment by sbolten** [comment]
Thx.

For my reference:

On arch:
- install downgrader package
- downgrader intel-graphics-compiler
- downgarde to version: 1.0.4361

All fine.

**Comment by ArchangeGabriel** [comment]
Issue has been solved with latest intel-compute-runtime on Arch.

@parafin Sorry for the noise this caused on your bugtracker, as I’ve seen a lot of such reports there while looking for the original thread to report that news.
