### ISSUE TITLE
[3.2.1] Parametric masks - Eyedropper mark disappears on slider action

### ISSUE THREAD

**Issue by pal-sovany** [darktable-org/darktable#6007]
After upgrading to version 3.2.1, the eyedropper marker disappears on parametric mask sliders when the slider is moved.
Version 3.0.x did not have this issue.

**Steps to reproduce:**

1. Open an image in Darkroom 
2. Activate a module
3. Select parametric mask and select a channel
4. Activate the eyedropper tool and select an arbitrary point. A marker appears on the Input and Output sliders, representing the value of the selected point on the channel.
5. Grab a slider and start moving it. The marker disappears and the eyedropper tool deactivates.

See the attached screencast:
[Screencast from 2020-08-17 20:12:21.zip](https://github.com/darktable-org/darktable/files/5086124/Screencast.from.2020-08-17.20.12.21.zip)

**Platform:**
Darktable: v3.2.1
OS: Ubuntu 20.04.1 LTS (64bit)
GNOME: 3.36.3
Windowing system: X11
Kernel version: 5.4.0-42-generic

**Comment by elstoc** [comment]
Reproduced on 3.2.1 ArchLinux

**Comment by johnny-bit** [comment]
Issue present on current master as well. I think it has something to do with colour pickles work... pinging @dterrahe :)

**Comment by dterrahe** [comment]
Hm, this should have been resolved by #5634 (post 3.2.1), so up-to-date master should not behave like this anymore. I'll check when I get home.

**Comment by johnny-bit** [comment]
Sorry for the noise, indeed "current master" doesn't have this issue (fixed by #5634). I've ran wrong version, sorry.

@pal-sovany - can you try actual current master? the issue is solved there (at least for me).

**Comment by elstoc** [comment]
Ah sorry I haven't updated master in a bit. I thought you had fixed it somewhere @dterrahe

**Comment by elstoc** [comment]
Yes I can confirm fixed in current master. @pal-sovany please can you close this issue.

**Comment by pal-sovany** [comment]
@elstoc @johnny-bit @dterrahe Thanks for checking, I'll close it :)
