### ISSUE TITLE
Pod::Parser module removed in Perl 5.32 hence language support issues

### ISSUE THREAD

**Issue by phrrk** [darktable-org/darktable#6009]
**Describe the bug**

In perl 5.32 the module Pod::Parser has been removed from the base system, which results in build failure if po4a is installed and language support is expected.   This means that this module needs to be installed separately (cpan or otherwise) and thus the build instructions for all OS's need to be modified slightly.  For windows/msys there is currently no pacman package and I had to do a force install (tests failed) with cpan.  From comments I have seen elsewhere for other OS's packages exist. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  git master
 - OS:  all
 -  n/a
 -  n/a

**Additional context**

**Comment by kmilos** [comment]
See also comment that this module is superseded by Pod::Simple here: https://rt.cpan.org/Public/Bug/Display.html?id=125860#txn-1890324

**Comment by phrrk** [comment]
The issue lies with po4a

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962243

so I guess we have to await its conversion to Pod::Simple

**Comment by peterbud** [comment]
On MSYS2 I was able to build 3.2.1 by downgrading to perl 5.30, and downgrading perl-XML-Parser as well.

**Comment by parafin** [comment]
I build macOS package without having po4a. Judging from cmake output it is required for translation of user manual and manpages. I think user manual release process is due for overhaul and in any case it doesn't make sense to build it for each package separately. Manpages are more of an issue, but are they included in Windows package? How user would read them? I don't include manpages in macOS package.

So it's an issue, but not a big one IMHO.

**Comment by phrrk** [comment]
The approach taken by @parafin seems to me to be very sensible.  Yes, the man pages are included in the windows package, but as you say are unreadable outside the msys2 set up, whilst few will build the user manual themselves.  I am inclined to close this issue unless anyone thinks I should keep it open

**Comment by kmilos** [comment]
@peterbud The standalone perl-Pod-Parser package is now available in msys2 for perl 5.32 (https://github.com/msys2/MSYS2-packages/pull/2112)
