### ISSUE TITLE
Keyboard mapping crash darktable

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#6014]
Windows 10
darktable 3.2.1
OpenCL actived
multiple GPUs
(GTX 1080TI 11GB & GTX 1070 8GB)
NVIDIA DRIVER Version 411.66

1. Open global preferences window.
2. Select shortcuts tab
3.Type: "discard" into search combo box
4. Double click to remap "discard" in history stack
5. Map backspace key or any other key combination

In Lighttable select any image with a previous modification to discard history.
Press the mapped key
Accept (yes) the confirmation dialog box.

darktable got an error and close

-->log. darktable_bt_GRXMP0.txt

this is darktable 3.2.1 reporting an exception:

-------------------

Error occurred on Wednesday, August 19, 2020 at 02:26:31.

darktable.exe caused an Access Violation at location 00000000649F6430 in module libglib-2.0-0.dll Reading from location 000000000000000B.

AddrPC           Params
00000000649F6430 0000000000000001 00000000251A0EC0 0000000000000001  libglib-2.0-0.dll!g_list_length
000000006362A4F9 0000000000000100 0000000000000002 0000000000000004  libdarktable.dll!dt_history_delete_on_list
000000006C5C180E 0000000000000038 0000000000610000 0000000000000004  libcopy_history.dll!0x180e
0000000067F06DD6 0000000001CD0000 00007FFC15FA5971 0000000000000002  libgobject-2.0-0.dll!g_closure_invoke
0000000067F1E65B 000000002129AF80 00000000677492C3 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
0000000067F1E7A8 000000000061F070 0000000067F0894D 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
0000000063758E0A 000000002CB421A8 0000000000000000 0000000000000008  libdarktable.dll!find_accel_internal
0000000067703960 000000002CB50C10 0000000001CD0000 000000002CB50C00  libgtk-3-0.dll!0x3960
0000000067F06B99 0000000000000053 0000000000000000 0000000200000000  libgobject-2.0-0.dll!g_closure_invoke
0000000067F18A09 000000002069BF80 0000000000001369 000000002071EE60  libgobject-2.0-0.dll!g_signal_handler_disconnect
0000000067F1E014 000000002071EE60 0000000001CD0000 0000000000001369  libgobject-2.0-0.dll!g_signal_emit_valist
0000000067F1E7A8 00000000252642C0 0000000000000432 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
000000006771B19A 0000000000000010 0000000000000010 0000000067D3859B  libgtk-3-0.dll!gtk_accel_group_activate
000000006771C8BE 0000000000000048 0000000067F24826 000000000061F46C  libgtk-3-0.dll!gtk_accel_groups_activate
00000000679D8A53 000000000061F760 0000000067F29A46 0000000000000000  libgtk-3-0.dll!gtk_window_activate_key
00000000679D8D23 0000000000000000 000000000061F7A0 000000000061F7A0  libgtk-3-0.dll!gtk_window_activate_key
0000000067702D4A 0000000000000000 0000000000000000 0000000000000002  libgtk-3-0.dll!0x2d4a
0000000067F06B99 0000000000000001 000000000061F6B0 0000000020936CC0  libgobject-2.0-0.dll!g_closure_invoke
0000000067F18468 0000000004AFAEF0 0000000000000000 0000000020803D50  libgobject-2.0-0.dll!g_signal_handler_disconnect
0000000067F1E014 0000000020803D50 0000000000000000 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
0000000067F1E7A8 0000000020803D50 0000000067F260E6 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00000000679B3005 0000000000000000 0000000067F0B35C 0000000000000000  libgtk-3-0.dll!gtk_requisition_copy
00000000678611E1 0000000000000000 0000002F00000058 00007FFC133C10C4  libgtk-3-0.dll!gtk_lock_button_set_permission
0000000067863148 0000000000000000 000000006C206400 0000000000000001  libgtk-3-0.dll!gtk_main_do_event
000000006C1CF5BA 000000000061FAF0 0000000004AA3FC0 00007FFC13F813B0  libgdk-3-0.dll!gdk_event_free
000000006C20643F 000000000061FBA0 0000000000000000 0000000001BDC2F0  libgdk-3-0.dll!gdk_win32_drag_context_get_type
00000000649F7414 0000000000000002 00000000251E3F70 00000000251E3F70  libglib-2.0-0.dll!g_clear_list
00000000649FA4E6 0000000000000001 0000000001BCDA40 0000000001BD5120  libglib-2.0-0.dll!g_main_context_check
00000000649FAA0C 0000000000000000 0000000000000000 000000006393B0A0  libglib-2.0-0.dll!g_main_loop_run
000000006786202D 0000000000000000 0000000000402720 0000000001BD4670  libgtk-3-0.dll!gtk_main
00000000637612CC 00007FFC00000001 0000000001BCDA40 00007FFC00000001  libdarktable.dll!dt_gui_gtk_run
0000000000402AAC 0000000000000010 0000000000000001 0000000000000000  darktable.exe!0x2aac
00000000004015C5 000000000000005A 0000000000000000 00000000004070A0  darktable.exe!0x15c5
00000000004013E4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x13e4
0000000000401516 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x1516
00007FFC14228364 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFC15FD5E91 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.2.1.0
ntdll.dll   	10.0.14393.0
KERNEL32.DLL	10.0.14393.0
KERNELBASE.dll	10.0.14393.0
msvcrt.dll  	7.0.14393.0
libglib-2.0-0.dll	2.64.3.0
libintl-8.dll	0.19.8.0
libdarktable.dll
ADVAPI32.dll	10.0.14393.0
GDI32.dll   	10.0.14393.0
ole32.dll   	10.0.14393.0
sechost.dll 	10.0.14393.0
gdi32full.dll	10.0.14393.0
RPCRT4.dll  	10.0.14393.0
combase.dll 	10.0.14393.0
ucrtbase.dll	10.0.14393.0
USER32.dll  	10.0.14393.0
win32u.dll  	10.0.14393.0
bcryptPrimitives.dll	10.0.14393.0
PSAPI.DLL   	10.0.14393.0
SHELL32.dll 	10.0.14393.0
libiconv-2.dll	1.16.0.0
cfgmgr32.dll	10.0.14393.0
windows.storage.dll	10.0.14393.0
libwinpthread-1.dll	1.0.0.0
powrprof.dll	10.0.14393.0
libgcc_s_seh-1.dll
shlwapi.dll 	10.0.14393.0
libstdc++-6.dll
libgomp-1.dll
libcairo-2.dll
kernel.appcore.dll	10.0.14393.0
libcurl-4.dll
CRYPT32.dll 	10.0.14393.0
shcore.dll  	10.0.14393.0
exchndl.dll 	0.9.2.0
libexiv2.dll
WS2_32.dll  	10.0.14393.0
MSASN1.dll  	10.0.14393.0
libgdk-3-0.dll	3.24.20.0
profapi.dll 	10.0.14393.0
WLDAP32.dll 	10.0.14393.0
IMM32.dll   	10.0.14393.0
libgdk_pixbuf-2.0-0.dll	2.40.0.0
SETUPAPI.dll	10.0.14393.0
libgio-2.0-0.dll	2.64.3.0
libgmodule-2.0-0.dll	2.64.3.0
libgobject-2.0-0.dll	2.64.3.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.20.0
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
lua53.dll
libopenjp2-7.dll
libpango-1.0-0.dll	1.43.0.0
libpangocairo-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
librsvg-2-2.dll
comdlg32.dll	10.0.14393.0
libsecret-1-0.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
zlib1.dll
libssp-0.dll
MSIMG32.dll 	10.0.14393.0
libfontconfig-1.dll
libfreetype-6.dll	2.10.2.0
libpixman-1-0.dll
mgwhelp.dll 	0.9.2.0
VERSION.dll 	10.0.14393.0
libexpat-1.dll
dwmapi.dll  	10.0.14393.0
libbrotlidec.dll
libcrypto-1_1-x64.dll	1.1.1.7
libidn2-0.dll
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.7
libpcre-1.dll
libcairo-gobject-2.dll
WINMM.dll   	10.0.14393.0
libepoxy-0.dll
libfribidi-0.dll
gdiplus.dll 	10.0.14393.0
libpangowin32-1.0-0.dll	1.43.0.0
libffi-7.dll
libexif-12.dll
libltdl-7.dll
DNSAPI.dll  	10.0.14393.0
NSI.dll     	10.0.14393.0
IPHLPAPI.DLL	10.0.14393.0
libsystre-0.dll
libbz2-1.dll
libHalf-2_5.dll
libIex-2_5.dll
libImath-2_5.dll
libIlmThread-2_5.dll
libpangoft2-1.0-0.dll	1.43.0.0
libthai-0.dll
COMCTL32.dll	6.10.14393.0
WINSPOOL.DRV	10.0.14393.0
libatk-1.0-0.dll	2.36.0.0
libharfbuzz-0.dll
libgcrypt-20.dll	1.8.5.54720
liblzma-5.dll	5.2.5.0
libzstd.dll
dbghelp.dll 	10.0.14321.1024
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
USERENV.dll 	10.0.14393.0
WINMMBASE.dll	10.0.14393.0
USP10.dll   	10.0.14393.0
libtre-5.dll
libdatrie-1.dll
bcrypt.dll  	10.0.14393.0
libgraphite2.dll
libgpg-error-0.dll	1.38.0.0
dbgcore.DLL 	10.0.14321.1024
CRYPTBASE.DLL	10.0.14393.0
CRYPTSP.dll 	10.0.14393.0
rsaenh.dll  	10.0.14393.0
uxtheme.dll 	10.0.14393.0
OLEAUT32.dll	10.0.14393.0
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.14393.0
mswsock.dll 	10.0.14393.0
MSCTF.dll   	10.0.14393.0
DEVOBJ.dll  	10.0.14393.0
WINTRUST.dll	10.0.14393.0
Wintab32.dll	1.0.5.7
WTSAPI32.dll	10.0.14393.0
Wacom_Tablet.dll	6.3.5.3
IconCodecService.dll	10.0.14393.0
WindowsCodecs.dll	10.0.14393.0
OpenCL.dll  	2.2.2.0
nvopencl64.dll	26.21.14.4166
nvapi64.dll 	26.21.14.4166
dxgi.dll    	10.0.14393.0
nvcompiler.dll	26.21.14.4166
winhttp.dll 	10.0.14393.0
ondemandconnroutehelper.dll	10.0.14393.0
libpixbufloader-png.dll
mscms.dll   	10.0.14393.0
icm32.dll   	10.0.14393.0
msxml6.dll  	6.30.14393.0
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libwebp-7.dll
libxcf.dll
libdisk.dll
libemail.dll
libgallery.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libborders.dll
libcacorrect.dll
libchannelmixer.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libmask_manager.dll
libmonochrome.dll
libnegadoctor.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
libioporder.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmodulegroups.dll
libmodulelist.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
libpixbufloader-svg.dll
ActXPrxy.dll	10.0.14393.0

Windows 10.0.14393
DrMingw 0.9.2

**Comment by elstoc** [comment]
Reproduced on ArchLinux also.
