### ISSUE TITLE
lighttable scrollbar disappeared after installing 3.2.1

### ISSUE THREAD

**Issue by wpkc** [darktable-org/darktable#6026]
After updating to version 3.2.1 on Windows 10, scrollbar on lighttable is disabled. 

**To Reproduce**
1. Install darktable version 3.2.1 as upgrade or as new installation.
2. If current folder does not have more images that can be displayed on screen in lighttable, either adjust row size until a scrollbar is needed, or import a folder with enough images that a scrollbar is needed in lighttable.
3. No scrollbar is displayed in lighttable center view.

**Expected behavior**
Scrollbar should be displayed.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10, 64-bit, Version	10.0.18363 Build 18363
 - OpenCL activated
 - Intel(R) HD Graphics 5500, Driver Version 20.19.15.4703

**Additional context**
* Uninstalling darktable, and deleting its folder in {Current_User}\AppData\Local\darktable, and reinstalling the program did not fix the issue.
* I finally found Preferences=>lighttable=>"show scrollbars for central view" in the program settings and it had been cleared.
* Check marking that option and restarting darktable brought the scrollbar back.

**Suggested behavior**
* Upgrading darktable should never disable the scrollbar if it was enabled before.
* New installs should always have the lighttable central view scrollbar enabled..

**Comment by johnny-bit** [comment]
Hey @elstoc - I think it was in preferences rework where option was split. Previously by default it was "lighttable" so `lighttable/ui/scrollbars` should default to true and `darkroom/ui/scrollbars` default to false.
