### ISSUE TITLE
indicate the success of rejecting an image in darkroom when "all except rejected" filter is active

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6037]
Reference #5968 

Please return the indication of success when rejecting an image in darkroom when the view filter is set to "all except rejected".

ideally should advance to next image in selection and set that image as selected.

One should NEVER be able to perform work on an image that is not "selected"!

**Comment by junkyardsparkle** [comment]
I guess the most obvious thing would be to use a transient console message, but... considering that this is a change from past (and possibly expected) behavior when performing this action, I would tentatively propose instead to use an image overlay that persists for as long as the image is still displayed, just to make very clear its "limbo" status with respect to the current view filter setting... unless this is a bad idea for some reason I'm not thinking of.

**Comment by ptilopteri** [comment]
Expected behavior and historical behavior is to advance to the next image in the collection ready to edit.

**Comment by ptilopteri** [comment]
would be better if image disappeared from view (view is set to "all expect rejected") and advance to next image in collection for edit.

then there is no need for a "transient console msg" and operation will be as it was in the past and will be understood.

**Comment by ptilopteri** [comment]
ping, still a problem
