### ISSUE TITLE
Map: Can not change location of an image because map view jumps to old location

### ISSUE THREAD

**Issue by mfg92** [darktable-org/darktable#6045]
**Describe the bug**
It is not possible to set the GPS location of an image in _map_ view if the image already has a location somewhere else on the map assigned. The problem is that as soon as one clicks on the image to start a drag&drop the map view jumps to the old location of the image.

**To Reproduce**
1. Go to _map_ view
2. Click on an image and use drag&drop to assign a location (lets call it A) to it
3. Move the map to somewhere else, A should be out of view now
4.  Click on the previous image and use drag&drop to assign a new location (lets call it B) to it

Step 4 will not work in dt 3.2.1. As soon as one clicks on the image, the map view jumps to location A, so location B is out of reach and can therefore not be assigned.

**Expected behavior**
In step 4 the view should not jump to location A if the click is part of a drag&drop.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL activated

**Comment by phweyland** [comment]
Looking at this.
