### ISSUE TITLE
Map: Selecting multiple images at once in the filmstrip is broken

### ISSUE THREAD

**Issue by mfg92** [darktable-org/darktable#6046]
**Describe the bug**
1. Using SHIFT to select multiple neighboring images is not possible any more in dt 3.2.1.
2. Using CTRL to select multiple (neighboring or not) images works as expected but it is not possible to unselect all by clicking (without CTRL) on an image. To unselect all images all selected images have to be CTRL+clicked one after another.

To assign the the same GPS location to multiple images I used CTRL+click and SHIFT+click to select multiple images before dragging them on the map. Selecting multiple images in dt 3.0.x worked like selecting mutliple files in a file manager (like Windows Explorer or GNOMEs Nautilus).

**Expected behavior**
Let's assume the map filmstrip looks like this: A B C D E F
If one clicks on image B, B should be marked as selected. If one then clicks on D while pressing SHIFT, B, C and D should be marked as selected. If one clicks on F while pressing CTRL B, C, D and F should be marked as selected. If one the clicks on any of the images without pressing CTRL or SHIFT, only the image on which one clicked should be marked as selected.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL activated

**Comment by ptilopteri** [comment]
@mfg92 
please consider closing this issue if it is no longer applicable.
