### ISSUE TITLE
Zoomable mode changes position after some file actions (paste/discard history etc.)

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6061]
@AlicVB If you can check this out please. This is the only bug/glitch that remained, as Zoomable mode is now flawlessly working on my end.

However, under certain conditions like paste settings or discarding history, sometimes it moves the selected image away from the view.

In this video note that after copy/pasting the settings (with ctrl-c and ctrl-v) from one image to another, the bottom row of images disappeared. The same can happen with discard history as well.

[Bottom row disappeared](http://cvrkutanje.net/disappear.webm)

This bug is much more annoying. Here, after I discard the history, the entire row/image changes position. These two videos are similar, but involving different images.

[glitch 1](http://cvrkutanje.net/glitch.webm)

[glitch 2](http://cvrkutanje.net/glitch2.webm)

**Steps to reproduce:**
1. Open zoomable mode, show more images at once
2. Try to discard history or paste settings to images
3. Sometimes the image you pasted on will change place 
OR
4. the bottom row of images will disappear.
 
**Additional info:**
- Happens in zoomable mode only.
- Arch linux, DT GIT version.

**Comment by maboleth** [comment]
To the list of triggers I can also add ratings - adding colors or stars can also make the grid moving and your rated image going away from the screen or to the sides.

**Comment by maboleth** [comment]
One more thing I discovered - the appearance of this bug is related to the zoom level.

For example:

- Zoomable table is set to 5. Try to rate image, grid moves. Then, try to rate other images on the same level - nothing happens, all is normal.
- Change zoom position to e.g. +/-6 or more, do the same and the grid will move. 
- This glitch will happen only once on each zoom level (from 2 - 25).

**Comment by AlicVB** [comment]
@maboleth : can you check and confirm that PR #6126 fix your issue ? Thanks

**Comment by maboleth** [comment]
This is closed, but not fixed, as stated in #6126

**Comment by AlicVB** [comment]
@maboleth : I was focused on the image disappearing, sorry for having skipped the rest... PR #6143 should fix the erratic move too. Thanks for all your tests on this mode !

**Comment by maboleth** [comment]
> @maboleth : I was focused on the image disappearing, sorry for having skipped the rest... PR #6143 should fix the erratic move too. Thanks for all your tests on this mode !

@AlicVB 
You're welcome! Consider it fixed. :)
