### ISSUE TITLE
Lighttable becomes empty when selecting desdencing sorting by rating

### ISSUE THREAD

**Issue by svillar** [darktable-org/darktable#6062]
The lighttable matrix of pictures becomes empty (gray) in the following scenario

**Steps to reproduce**
1. Go to lighttable
2. Select sorting by rating
3. Click on the button right next to the "sort by" combo so that it selects descending order
4. No pictures are shown

**Expected behavior**
Pictures are shown in descending order by rating

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Debian
 - OpenCL activated
 - NVIDIA 390.318

**Comment by svillar** [comment]
> @svillar : I know what happen. It's a side effect of a bug in how offset where computed. This should have been fixed recently in master.

Cool, thanks. Looking forward to 3.2.2 :smile:

**Comment by maboleth** [comment]
Understood! Glad it wasn't related to sorting issues Zoomtable had. Thanks.

**Comment by AlicVB** [comment]
great another one to close :)
