### ISSUE TITLE
Module order is always in `legacy` mode

### ISSUE THREAD

**Issue by svillar** [darktable-org/darktable#6063]
**Describe the bug**
Module order is always in `legacy` mode. I'm trying with unprocessed RAW photos (just taken) and with no configured styles. The only automatic preset I have is the sharpening one but I have also tried without that preset.

The workflow is `scene-referred`

**To Reproduce**
1. Open any photo in darkroom
2. Check the module order
3. Always says `legacy`

**Expected behavior**
`v3.0` should be shown by default

**Platform (please complete the following information):**
 - Darktable Version:3.2.1
 - OS: Debian GNU/Linux
 - OpenCL on
 - NVIDIA 390.138

**Comment by svillar** [comment]
> No problems with this in GIT MASTER version. So it's either fixed (will be included in 3.4) or works for me.

I've built git master. I have started it with `--configdir DIR1 --cachedir DIR2` set to newly created dirs so no options were reused from my local config. I have imported a couple of fresh never edited messages. And the problem is still there.

**Comment by maboleth** [comment]
> > No problems with this in GIT MASTER version. So it's either fixed (will be included in 3.4) or works for me.
> 
> I've built git master. I have started it with `--configdir DIR1 --cachedir DIR2` set to newly created dirs so no options were reused from my local config. I have imported a couple of fresh never edited messages. And the problem is still there.

Not sure what to say. I have imported fresh files just to test this and all had v3 by default. Using Canon CR2 RAW files.

**Comment by RawConvert** [comment]
I'm also getting this problem on dt 3.3.0+306~g08519422c-dirty  with Ubuntu 18.04 (and Canon raw), built yesterday 23Aug.
Didn't notice until I saw this issue but had a hell of struggle last night with some highlights; perhaps that was just me...
Anyway: Picked a raw; discarded history; deleted it in lighttable; deleted the XMP from the source folder; into darktable; current order = legacy.  (Then changed to v3.0 order; back to lighttable; back to darktable; order now ok, 3.0)

**Comment by RawConvert** [comment]
Two further points -
1. In the sequence above I of course had to import the raw (after deleting the xmp).
2.   *** N.B. ***  The above was done with "scene-referred" set in the preferences.  I was also getting base curve switched on.  Then I changed workflow defaults to "none", re-launched dt, and repeated the test.  This time module order was 3.0 and no base curve.

**Comment by svillar** [comment]
I've tried again because I realized that I was not removing the sidecar files before reimporting the image. If I do that then the v3.0 is indeed selected both with git master and also with 3.2.1, so I am not sure what's causing the issue...

**Comment by RawConvert** [comment]
@svillar , and you're definitely on scene-referred in preferences?

**Comment by svillar** [comment]
> @svillar , and you're definitely on scene-referred in preferences?

Yeah, completely sure. It works if I delete the sidecar files and reimport them again.

**Comment by svillar** [comment]
@RawConvert note that I had to do two things:

1. remove images from the collection
1. remove the sidecar (XMP) files

only doing one of them does not fix the issue, which means that the module order for each picture should be stored in the dt database as well.

**Comment by RawConvert** [comment]
@svillar , I did those two things.
I've just repeated the test to double check, and....   it's now behaving fine!  I can't really explain that.  Perhaps it's a subtle bug to recreate, or maybe I got confused and when I thought I was set on scene ref, I was actually on display ref.  I definitely saw base curve on and see there is an issue about that and scene ref. (6081/6077).
Anyway please don't keep this issue open on my account.
