### ISSUE TITLE
Color label applied to whole filmstrip

### ISSUE THREAD

**Issue by parishcm** [darktable-org/darktable#6064]
Darktable 3.2.1, Windows 10. When in Darkroom mode, hitting `F1` while the mouse is on the image assigns the `red` label to just that image. However, if hovering the mouse over the thumbnail, hitting `F1` assigns or unassigns `red` to ALL images.

**Comment by matt-maguire** [comment]
I wasn't able to reproduce this at all, not on Windows 10 DT 3.2.1 nor on linux.

When you say "hovering the mouse over the thumbnail, hitting F1 assigns or unassigns red to ALL images":
- Are you talking about in darkroom mode, or back in lighttable mode?
- what you you mean by "thumbnail"? Are you talking about an image in the filmstrip at the bottom of darkroom, the preview at the top left of darkroom, or a thumbnail on the lighttable?
- when you say assigns red to ALL images, do you mean just the images displayed in the filmstrip or the filtered images on the lighttable? Or maybe all images in the collection? or in the whole DB?

Is there any other information you can give us on how to demonstrate this issue?

**Comment by AlicVB** [comment]
I suppose this happen if all your images in filmstrip are selected, right ? If so, it's the normal behavior...

**Comment by Solarer** [comment]
Just looked into it.
In the darkroom, select a number of pictures. If you press F1, you will only rate the picture you are looking at. If you hover your mouse over any UNselected picture in the filmstrip, you will rate that hovered picture instead.

But if you hover your mouse over any of the selected pictures, the rating will be applied to all pictures in that selection - not just the one that was hovered as one would expect. In fact, the rating is not added but inverted - so pictures in that group which had a red color label previously, are not labeled anymore.

**Comment by ralfbrown** [comment]
Working as designed, though as you noted with the issue you linked, there has been discussion of whether that *should* be the behavior.
Applying something to the entire selection is incredibly useful for pasting some or all of the current image's history to other images in the collection.

**Comment by johnny-bit** [comment]
Closing as "works as designed" and let's continue the discussion in #6025 to make the design more "obvious" with no guessing on "why did the dt apply rating to what i din't want to apply to"
