### ISSUE TITLE
Denoise bilateral filter error

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#6065]
Windows 10
darktable 3.2.1
OpenCL actived
multiple GPUs
(GTX 1080TI 11GB & GTX 1070 8GB)
NVIDIA DRIVER Version 411.66

1. Open an image in darkroom
2. Activate denoise (bilateral filter) module
3. Error: strange aleatory strips over image.
<img width="1920" alt="denoise bilateral filter01" src="https://user-images.githubusercontent.com/67672868/92589627-d0185e80-f268-11ea-8e7d-48d384300edb.PNG">

**Comment by neronadd** [comment]
Hello,




> Windows 10
> darktable 3.2.1
> OpenCL actived
> multiple GPUs
> (GTX 1080TI 11GB & GTX 1070 8GB)
> NVIDIA DRIVER Version 411.66
> 
> 1. Open an image in darkroom
> 2. Activate denoise (bilateral filter) module
> 3. Error: strange aleatory strips over image.
> 
> <img alt="denoise bilateral filter01" width="1920" src="https://user-images.githubusercontent.com/67672868/90969077-40319100-e4c2-11ea-8d07-6de5d4a33dbb.PNG">

I have same issue.

**Comment by chhil** [comment]
Same issue from May 11.
https://github.com/darktable-org/darktable/issues/4984

**Comment by caxon** [comment]
I'm also getting this issue windows w. 3.2.1. Notably, when zooming or panning, the artifacts change. Has anyone found a workaround or fix?
