### ISSUE TITLE
Seg fault, dump enclosed

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#6067]
I just fetched and compiled
darktable-git 3.3.0+299-ge60fcf210

When trying to run
`darktable-cli bench.SRW test.jpg --core -d perf -d opencl`
it segfaults and produces this report
[darktable_bt_3J50P0.txt](https://github.com/darktable-org/darktable/files/5113729/darktable_bt_3J50P0.txt)

Manjaro/KDE, latest
Kernel 5.8.1-3
CPU Ryzen 3900X
GTX-1660Ti

**Comment by johnny-bit** [comment]
Cannot replicate on current master (`3.3.0+307~gb360212f1`)

can you share benchmarking raw+xmp or even scripts?

The break seems to occur in thread wait for pipe processing.

In the mean time - can you replicate problem (using same param, different images or forced different devices)?

**Comment by ClaesGitHub** [comment]
Since last time, I have tried the following:
- another raw+xmp = segfault
- older kernel = segfault
- present git version (3.3.0+322-gb009789524) = segfault  (dump enclosed)

raw + xmp + command line enclosed (aSeqFault.zip).

[darktable_bt_WKV0P0.txt](https://github.com/darktable-org/darktable/files/5119358/darktable_bt_WKV0P0.txt)
[aSegFault.zip](https://github.com/darktable-org/darktable/files/5119387/aSegFault.zip)

**Comment by johnny-bit** [comment]
Judging from backtrace alone the error is "near impossible!" Can you reproduce with pure 3.2.1?

I've checked on my system and here are console outputs:
[dt_cli_3.2.1.txt](https://github.com/darktable-org/darktable/files/5119805/dt_cli_3.2.1.txt) (nice clean dt 3.2.1, gentoo package)
[dt_cli_3.3.0+307.txt](https://github.com/darktable-org/darktable/files/5119806/dt_cli_3.3.0%2B307.txt) (3.3.0+307  recent)
[dt_cli_3.3.0+325.txt](https://github.com/darktable-org/darktable/files/5119807/dt_cli_3.3.0%2B325.txt) (3.3.0+325, current master)
[dt_cli_3.3.0+325_recompiled_ocl_kernels.txt](https://github.com/darktable-org/darktable/files/5119808/dt_cli_3.3.0%2B325_recompiled_ocl_kernels.txt) (as above + recompiled ocl kernels)

I can't reproduce, your segfault seems highly unlikelly... I wonder if there's some driver issue in your case.

my linux kernel is 5.4.28 and my nvidia driver is 450.57 with 1060 GTX card.

**Comment by ClaesGitHub** [comment]
@johnny-bit 
Thank you, you put me into the right direction. Problem now solved.

Pure 3.2.1/Manjaro -> segfault.
Pure 3.2.1/Win 10 -> OK!
3.3.0+348/Manjaro -> segfault

It turned out to be some Nvidia/openCL drivers that had not been automatically compiled with the new kernel, and the new Nvidia drivers. After a forced re-compile, everything now works.

Manjaro/KDE. Present kernel 5.8.1-3. Nvidia 450.57 with 1660 GFX. CPU Ryzen 3900X.
