### ISSUE TITLE
Different exposures shown in '100%' and 'fit screen' views when processing a .ORF file

### ISSUE THREAD

**Issue by luisfl** [darktable-org/darktable#6072]
**Describe the bug**

When I ask a RAW processed image (Olympus .ORF file) to be viewed at 100%, it shows much lighter shadows than the 100% view. The shadows go darker and darker as I zoom out. 

More: if I save the processed RAW as TIFF and open it in Darktable, the TIFF file shows the same black shadows in 100% view and fit-screen view.

This is the [ORF file](http://luis.impa.br/photo/lixo/maria-preta-de-bico-azulado_PNI-200808-B_46492.orf)
This is the [XMP file](http://luis.impa.br/photo/lixo/maria-preta-de-bico-azulado_PNI-200808-B_46492.orf.xmp)

**To Reproduce**
1. Open the attached .orf with the .orf.xmp.
2. Look at the blacks in the abdomen of the bird with a 'fit screen' view
3. Zoom in in the abdomen. As you go up to 100%, you will see it lighten up.
4. The saved .TIFF file does not have this problem.

**Expected behavior**
Same exposure, even if more detailed.

**Screenshots**
![TBmIM](https://user-images.githubusercontent.com/15525268/90980058-72c5a300-e52f-11ea-8720-53f49367c1ad.jpg)

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.2.1-1.fc32.x86_64
 - OS: Fedora 32 fully updated
 - OpenCL enabled
 compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by maboleth** [comment]
It's not different, it's just a bit more detailed rendering at 100% since there are more details. We are walking on edge there already with 100% black abdomen with only tiny bit of detail.

Rising the black level improves this so much and there's no difference between 100% and fit. The belly is not black anymore.
Further, exporting using sRGB further lowers your latitude than your working profile.

**Comment by luisfl** [comment]
> It's not different, it's just a bit more detailed rendering at 100% since it's much bigger. We are walking on edge there already with 100% black abdomen with only tiny bit of detail.
> 
> Rising the black level improves this so much, feathers are now appearing and there's no difference between 100% and fit - the belly is not black anymore.
> Further, exporting using sRGB further lowers your latitude than your working profile.

I do not agree, at all. This is not that problem. Saving the image as a 16bit TIFF should not render the abdomen with lots of fine detail and not even close to be black almost completely detailess and black. I do astrophotography where you open an almost totally black looking 16bit image and rescue all detail where you was not even able to see it. Here is far from it, yet the detail is gone.

I have used Darktable for some years after switching to RawTherapee, and old darkktable versions did not show this problem. Unfortunately this is the first version of Darktable that I use since a long time, so I have no idea when this problem began.

**Comment by luisfl** [comment]
Adding 5 new screenshots below.

In the first row, you see the same file processed in RawTherapee. The screenshot on the left is the file being processed right after saving it as 16bit TIFF. On the right, the TIFF file opened in RawTherapee: exact same result.
In the second row, the same experiment, now with DarkTable: completely different results.
In the third row, the RawTherapee 16bit TIFF opened in Darktable looks exactly with the same exposure as the one opened in RawTherapee. As it should. If I save this file in Darktable and open it again, I get the same exposure, as it should.

So it seems that DarkTable overexposes the 100% view of the RAW file, showing something different that will be saved. If you zoom out the view, the image gets darker and darker, until you fit the screen with it, and this is the exposure that will be saved, not the 100% one.

The screenshots:

![Untitled](https://user-images.githubusercontent.com/15525268/90984871-4d945d00-e54e-11ea-814c-76ebe75bf722.jpg)

**Comment by TurboGit** [comment]
TIFF ? What kind of TIIF ? Compressed ? Same level of compression ? Not compressed ? Which sizes in pixels ? If not using the same export, you cannot expect the same result. At the end what is the size of the RawTherapee TIFF and the size of the darktable one ?

**Comment by luisfl** [comment]
Both programs saving with either uncompressed TIFFs, or 100% quality JPGs: same problem. That is not the issue (and cannot be).

Why the doubts? It's pretty straightforward. Are you not being able reproduce the problem?

Posted this in StackOverflow today and got some upvotes already, so probably others are seeing the same problem.

**Comment by TurboGit** [comment]
> Why the doubts?

Because I don't know you and don't read your mind. We have seen lot of stupid reports which just make us lose our time trying to understand what is going on. Your report missed many information and your message don't even make me willing to help you.

**Comment by luisfl** [comment]
Stupid me, I thought I was helping Darktable.
As I wrote, I use RawTherapee.

Good Luck.
