### ISSUE TITLE
exif: asking add new LensModel tag

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#6074]
I am asking to add a new LensModel tag when exporting as a possible solution to the "Missing lens model in EXIF data #4922" issue. How it's done in Photoshop Lightroom.
The value can be taken from the parameter "lens" from "image information".
![2020-08-23 23-43-18](https://user-images.githubusercontent.com/15331117/90983903-cd94e400-e59b-11ea-813c-118b10956ae2.png)

**Comment by esq4** [comment]
![2020-08-23 23-43-18](https://user-images.githubusercontent.com/15331117/90983892-c1a92200-e59b-11ea-88b4-7589af0e9b33.png)

**Comment by phweyland** [comment]
> I am asking to add a new LensModel tag when exporting

Not sure to understand properly this.


Exporting your images you can configure / set the tags you wants.
Related to lens model exiv2 recognizes these ones:


![image](https://user-images.githubusercontent.com/23012047/90986936-327d1980-e55d-11ea-8a57-3f8e208a3b97.png)

Adding one of them to exported tags, you can at least manually set the value you want.

If your lens is only recognized as number (lens id) like in:

**Comment by phweyland** [comment]
> I am asking to add a new LensModel tag when exporting

Not sure to understand properly this. In your example the lens model is not missing in image information ... So Exif.Photo.LensModel should be exported by default (and equal to $(LENS)).


Exporting your images you can configure / set the tags you wants.
Related to lens model exiv2 recognizes these ones:


![image](https://user-images.githubusercontent.com/23012047/90986936-327d1980-e55d-11ea-8a57-3f8e208a3b97.png)

Adding one of them to exported tags, you can at least manually set the value you want.

If your lens is only recognized as number (lens id) like in: 

![image](https://user-images.githubusercontent.com/23012047/90987232-bafcb980-e55f-11ea-8fc0-674239770c02.png)

A substitution like:
Exif.Photo.LensModel <= $(LENS/201/Tamron the model you want)
should work too.

Does that answer your issue ?

**Comment by esq4** [comment]
Yes, this is an acceptable solution. Thank.

**Comment by esq4** [comment]
Can you add this to the FAQ?
