### ISSUE TITLE
[DT dev 3.3.0+xxx] Base curve always gets enabled when scene referred is set up in processing preferences.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6081]
In all likelihood its due to the bug reported https://github.com/darktable-org/darktable/issues/5275 and the db has been the same over upgrades in my current dev 3.3.X using scene referred where base curve should not be enabled on imported files, still enables base curve.

If it gets fixed well and good, else can someone provide me a script to remove that auto apply base curve from the db(I don't want to start with new databases) ?
I have attached the files from the config folder (remove the txt extension to get the zip file and the files are in it).
[config_folder.zip.txt](https://github.com/darktable-org/darktable/files/5115355/config_folder.zip.txt)

this is darktable 3.3.0+299~ge60fcf210

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by svillar** [comment]
Isn't this a dup og issue #6077 ?

**Comment by johnny-bit** [comment]
Dunno - it's possible it's different than yours since #5275 mentions non-removable auto applied basecurve preset.

**Comment by Nilvus** [comment]
I have read some users on french darktable forums who forget to restart darktable and so still have basecurve applied. Just in case, did you restart darktable after updating those settings? Of course, settings will applied only on new imported or altered images (by resetting auto-applied presets/history).

**Comment by chhil** [comment]
Has been restarted, system rebooted quite a few times. All images are new imports. It's extremely likely due to the previous issue referenced in the bug report, hence the db has been provided which probably overrides the settings of the preference to not enable basecurve.

**Comment by chhil** [comment]
The work around https://github.com/darktable-org/darktable/issues/5275#issuecomment-679970128 fixes it for me.
