### ISSUE TITLE
copy paste in lightable crashes darktable

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#6082]
**Describe the bug**

When I copy history from one image within lighttable - usually ctrl shift c and paste in another - often I experience crashes. For some reason I believe that is related to demozaic - amaze module. And more specifically if the targeted image is already processed and has already demozaic amaze enabled within it.

**To Reproduce**

**Expected behavior**

should not crash

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  Pop os 20.04
 -  yes
 -  Nvidia RTX 2070

**Additional context**

[darktable_bt_RIKWP0.txt](https://github.com/darktable-org/darktable/files/5116297/darktable_bt_RIKWP0.txt)

I am sorry if the information is not sufficient... it is my first reporting here.

**Comment by johnny-bit** [comment]
The issue is known and already fixed in current master, for example check #6004

If you can't use master version, then you'll need to wait for future release with fix. There's a workaround: you've got to make sure that no selection change is done with copy/paste, so use buttons on the side.

Since the issue is fixed in current master, please consider closing the issue.

**Comment by maboleth** [comment]
Yes, I had that bug, fixed in git-master version.

You can copy-paste (ctrl-c, ctrl-v), just try not to use the SHIFT and to pick what to paste and what not. That can crash it.
If you can, use git version, until the fix goes live to 3.2.2 or 3.4.

**Comment by vancouverbluesea** [comment]
Thank you! I will implement the workaround.

**Comment by ptilopteri** [comment]
@vancouverbluesea 
If this satisfies you, consider closing the issue.
thankyou

**Comment by vancouverbluesea** [comment]
@ptilopteri
Thank you, sorry - new here and learning...
