### ISSUE TITLE
lighttable - selecting using keyboard - "enter" does not fully work when in zoom mode - pressing W

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#6086]
**Describe the bug**

When browsing lighttable - if we enter in full screen mode or zoom mode by pressing "W" then use arrow keys to navigate to another image and press enter to select it - the selection does not stick when we move the mouse.

**To Reproduce**

**Expected behavior**

the image should be selected - even when we move the mouse it should remain selected. 

**Screenshots**

The image is soft selected - we can see it but as soon as we move the mouse (and most of the cases we must) the image becomes deselected. The feature used to work in the past.
will enclose video

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  Pop os 20.04
 -  yes
 -  Nvidia RTX 2070

**Additional context**

https://www.dropbox.com/s/mjmd9xk02sgwj2m/2020-08-24%2016-52-57.mkv?dl=0

**Comment by ptilopteri** [comment]
selection follows the mouse, the image under the mouse pointer is active.

**Comment by vancouverbluesea** [comment]
![image](https://user-images.githubusercontent.com/69771189/91110492-da184b80-e632-11ea-88c4-ceabdac31f72.png)
darkest grey (like image 1 and 4) not selected
middle grey (like image 2) selected - this is what I am after to happen when pressing enter. Once an image is selected we can ctrl click on another image or shift click then we select multiples and can rate or color label multiple images. We can see that "enter" as a selection tool works when W is not pressed but it won't work when W is pressed.
light grey (like image 3) responds to mouse movement - this is highlighted (but not selected). When the image is highlighted - we can do something with this image alone - colour label, star rating etc.

**Comment by AlicVB** [comment]
ok, after some tests, I think I got it : it's a refreshing problem : in fact your image is correctly selected, but its background color in filemanager is not updated...
I'll have a look and try to fix that soon
