### ISSUE TITLE
3.3.0-xxx Copy-Paste history in filmstrip followed by addition of new Contrast equalizer + mask makes the images go black

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6088]
In the process of editing an image.

Copied the history from another image and pasted it in the filmstrip.
Then added a new instance of contrast equalizer.
Selected path to draw a path inside the eye.
The preview image and filmstrip image go black.

I have also experienced main image going black with the mask drawn visible.

![image](https://user-images.githubusercontent.com/1119439/91113353-079cdd80-e6a3-11ea-9ee6-47da54068d9a.png)

The xmp of the image the history was copied from is attached. Do take a note of the numbering on it as there were duplicates created in duplicate manager and eventually duplicates were removed leaving one file with final edit for it.
[P1081226_02.RW2.xmp.txt](https://github.com/darktable-org/darktable/files/5120918/P1081226_02.RW2.xmp.txt)

![image](https://user-images.githubusercontent.com/1119439/91112677-62cdd080-e6a1-11ea-9fe0-82095d9ff285.png)

this is darktable 3.3.0+307~gb360212f1
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by johnny-bit** [comment]
I've tried to replicate the issue, but it has contrived set of steps and I couldn't get to replicatint the problem at all...

So I'll need to ask - do you still have the problem and are able to reproduce or can we close this?

**Comment by chhil** [comment]
I haven't seen this happen on the current master.
