### ISSUE TITLE
Grey theme: improve contrast, feedback request

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#6106]
**Is your feature request related to a problem? Please describe.**

I have read quite some feedback in different places about the contrast of grey theme. Of course, having an important contrast on a grey theme is not possible, not as we can on a dark one. But maybe, we could improve a little bit more the grey theme contrast.

As we can't change grey on the UI, or we will lost the goal of this theme (near a grey theme and having better contrast possible), the only way is to update text color.

**Describe the solution you'd like**

I have tested two solutions to improve it by updating those lines (could be tested in preferences):

```
    @define-color fg_color @grey_95;
    @define-color plugin_fg_color @fg_color;
    @define-color section_label @grey_85;
    @define-color plugin_label_color @grey_85;
    @define-color bauhaus_fg @fg_color;
```

```
    @define-color fg_color @grey_100;
    @define-color plugin_fg_color @fg_color;
    @define-color section_label @grey_90;
    @define-color plugin_label_color @grey_90;
    @define-color bauhaus_fg @fg_color;
```
As you can see, it's only about increasing to 5% to the white the text on first one, and 10% on second in regard of actual grey theme.

Don't ask me why but I always had difficulties to apply a grey_100 (so pure white) on main text in any theme. Maybe personal aesthetics considerations or feeling about the global aspect of the theme. That's why I don't increase it before. But with time, maybe one of those proposals would be better.

**Alternatives**
No alternative asked here, just the text and which white to choose.

I would like to have some feedback about those proposals and if we keep the white as it is on actual theme or update to first or second proposal here. @johnny-bit, @elstoc, @Mark-64, @aurelienpierre, @rawfiner and @TurboGit: your feedback is welcomed.

**Additional context**

**Comment by Mark-64** [comment]
I am not the most indicated person to give a feedback here, as I don't use the grey theme, but the dark one. I know the disadvantage, but I simply can't stand the low contrast.
The first proposal is slighlty more contrasted and the second even more. 
I would vote for the second, which doesn't mean I would start to use it ;-)

**Comment by elstoc** [comment]
Honestly I've never really had a problem with the contrast of the grey themes. I prefer the first, which is perhaps marginally better than the current theme. I think the second one is a bit too contrasty for me. It's all just a matter of taste though really.

**Comment by johnny-bit** [comment]
It's IMO good, depending on preferences of one checking. I've checked with fg_color to gray_100 and 95 one... I prefer the 95 one but then I don't have problem with low contrast ;) grey_100 looks a bit too harsh imo.

**Comment by rawfiner** [comment]
I prefer the actual theme, or something in between the actual theme and the first proposal like this (I find the module name of focused module too bright otherwise):
```
@define-color fg_color @grey_95;
@define-color plugin_fg_color @fg_color;
@define-color bauhaus_fg @fg_color;
```

**Comment by Nilvus** [comment]
Thanks for your comment. I agree that second one is too harsh. I like your proposal @rawfiner, much better. Will wait a little to see if other feedback coming but at this time your proposal seems the better choice.

**Comment by maboleth** [comment]
+1 from me too. It's much clearer what's ON.
