### ISSUE TITLE
[Dev 3.3.0-xxx] Changing rating in filmstrip removes the image from filmstrip but main view still has image

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6111]
View : Darkroom.
Images displayed based on filter (in my case >= 2 stars)
Select an image in filmstrip which gets displayed in the main view.
Mouse pointer is still on image in filmstrip.
Press 1 to change the star rating (changed from existing 2 to 1).
Image is removed from filmstrip.
Image is not removed from main view and next image is not displayed.

When image rating is changed, the next image in filmstrip is not given focus/selection which leads to the next image not being displayed and the rating changed image is still displayed in main view.

Probably a regression of https://github.com/darktable-org/darktable/issues/4539

this is darktable 3.3.0+372~g5a3e31361

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by parafin** [comment]
Is it desirable though? Loading another image in darkroom is time-consuming, so if you're changing ratings of several images in filmstrip it makes sense IMHO to delay switching the image until user explicitly asks for it. Also consider the case when last image was removed from the collection this way.

**Comment by chhil** [comment]
> Is it desirable though?
I would think it's a normal flow. Initial culling I decided the image would be worked upon and gave it 2 starts. But while editing in darkroom when I come to the image and decide its not worth editing it and want to remove it from the filtered start display criteria , so change the rating. If a rating change causes the image to disappear from a filmstrip, it should disappear from the main view and go to the next one. If a next one doesn't exist either go to the previous one or roll over to the first image.

**Comment by ptilopteri** [comment]
I agree with this workflow.  It is what one would expect to happen.  And it is how it happens in the culling view.

**Comment by AlicVB** [comment]
ok, @ptilopteri @chhil : I've found the previous issue where this has been debated in may. We were all 3 involved there, and nothing has really changed... So we are going into circles...
Please see #5042 for the different arguments...

I'll close this for this reason, and #5968 too once I'll have fixed the "annex" issues

**Comment by chhil** [comment]
So, the only way to know where you are in the filmstrip after an image disappears but is still visible in the darkroom view is to use the spacebar to move forward to the next image. Other than spacebar, if you are a mouse user you are basically lost which image is next unless you recall what the previous and next thumbnails in the filmstrip looked like because after disappearance there is no maker where you were.

I can live with this as I now know spacebar can be used to move to the next image, but in all honesty it's not user friendly.

**Comment by ptilopteri** [comment]
Definitely not and not as darktable's history has had it.
