### ISSUE TITLE
core dump exporting image from git master g5a3e31361

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6114]
openSUSE Tumbleweed 20200824
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git372.5a3e31361
OpenCL off 
i7 12-core 36GB

built from git clone

exporting image
  http://wahoo.no-ip.org/~paka/200825_205552_dse_0266.nef
  http://wahoo.no-ip.org/~paka/200825_205552_dse_0266.nef.xmp

get repeatable core dump

note:  the group contained 232 images and only above image causes core dump.  The rest exported successfully.

rebuilt with --asan
exporting image faulted:  free(): invalid pointer
   [1]+  Aborted                 (core dumped)  ~/darktable_repos/dbuild/bin/darktable --library :memory:

core dump:  http://wahoo.no-ip.org/~paka/core.darktable.20200827.lz4

ran in gdb
  gdb --args ./darktable_repos/dbuild/bin/darktable --library :memory:

gdb appears to hang, I finally <ctrl><c> and gdb prompt appears
command-line text to this point:  http://wahoo.no-ip.org/~paka/gdb.err.20200827.txt

tried "set pagination off" and gdb says:
  Couldn't get registers: No such process.

**Comment by ptilopteri** [comment]
@ralfbrown 
ping

**Comment by ptilopteri** [comment]
original gdb output w/o asan
  http://wahoo.no-ip.org/~paka/gdb.txt

**Comment by ptilopteri** [comment]
just tried to export sub image in darktable git g3ef3aa646 ** with asan **
gdb output:  http://wahoo.no-ip.org/~paka/gdb.0827.txt

same result, export failed

**Comment by TurboGit** [comment]
@ptilopteri : Looking at the bt and the corresponding code it may be an issue with memory allocation. How many threads have you defined in "cpu/gpu/memory" preference tab? Also you said you have 36Gb of RAM, right? Really 36 not 32 or 16 ?

**Comment by parafin** [comment]
I'm not sure that ASAN backtrace is related to export crash. I've found a potential problem for ASAN abort:
https://github.com/darktable-org/darktable/blob/3ef3aa6464e25c630d581d69fecb30028d50544c/src/libs/export.c#L499 better be changed to g_new0

**Comment by ralfbrown** [comment]
Crash confirmed here, the culprit is indeed denoise(profiled).  Interestingly, it only crashes with patch sizes 1 and 2, not 3 or 4.  Will take a closer look over the weekend.

**Comment by ptilopteri** [comment]
> What would be nice is to find the first commit having this issue. Can you do that?

with instruction :)

**Comment by ptilopteri** [comment]
> @ptilopteri : Looking at the bt and the corresponding code it may be an issue with memory allocation. How many threads have you defined in "cpu/gpu/memory" preference tab? Also you said you have 36Gb of RAM, right? Really 36 not 32 or 16 ?

yes, 36gb not 32 or 16

Info:      Processes: 567 
           Uptime: 15:21:41  up 5 days  6:11,  45 users,  load average: 0.45, 0.39, 0.44 
           Memory: 35.23 GiB used: 12.21 GiB (34.7%) Init: systemd v: 245 runlevel: 35 
           target: multi-user.target Compilers: gcc: 10.2.1 alt: 10/9 clang: 10.0.1 Shell: bash 
           v: 5.0.18 running in: xterm inxi: 3.1.00

**Comment by MStraeten** [comment]
> > What would be nice is to find the first commit having this issue. Can you do that?
> 
> with instruction :)
https://github.com/darktable-org/darktable/wiki#finding-bug-causes

**Comment by ralfbrown** [comment]
Despite being caused by a subtle conjuntion of two different problems, this one was pretty easy to find.  The error messages told me that the code was stomping on malloc housekeeping info at the start or end of an allocated block, and continued crashing when reducing the active threads told me it was the beginning.  One hardware watchpoint later and I had the offending instruction, after which the solution fell into place.
