### ISSUE TITLE
Navigation helpers for zoomable lighttable

### ISSUE THREAD

**Issue by l0f4r0** [darktable-org/darktable#6121]
**Is your feature request related to a problem? Please describe.**
It's sometimes difficult to take one's bearings in zoomable lighttable.

**Describe the solution you'd like**
Some markers/helpers/points of reference would be welcome: horizontal & vertical scrollbars, a rectangle showing the currently visible area (like in navigation panel)...

**Alternatives**
Zooming-out.

**Comment by Nilvus** [comment]
Zoomable lighttable is a sort of drag-and drop mode. To move photos, it's about maintaining clic and move the set of photos. Like you would do if you have a big paper of multiple photos to show one or the other in real darkroom. So scrollbars are not useful on this mode. But a rectangle showing the currently visible area could be a good idea. But where/how to add this on the UI without breaking consistency with other modes (where this will be not suitable) and avoid making the UI a mess? Quite hard.

Zooming-out is already possible, with mouse wheel or using number selector on footer toolbar.

**Comment by maboleth** [comment]
It's just getting used to. As @Nilvus said, it's not necessary for this mode to have any scrollbars.

Please close your issue if you're done.

**Comment by l0f4r0** [comment]
Actually, scrollbars suggestion was not only about moving the pictures set but also to work out where we are.
But it can be something else if there is a better suggestion like the "rectangle".

**Comment by Nilvus** [comment]
> Actually, scrollbars suggestion was not only about moving the pictures set but also to work out where we are.
Just zoom-out (your alternative proposal) and you could see where you are. Adding a rectangle, as I said, have a big risk to make the UI a mess.

**Comment by AlicVB** [comment]
Sadly scrollbars won't work well in this case as the grid can go far to the left/right/... so the "handle" part of the scrollbar will not really represent the grid position. (not to say that scrollbars are a nightmare to implement)

Your "rectangle" proposition can be a solution, but I see 2 main drawbacks : 
- as @Nilvus said : this won't be easy to implement with ui consistency
- When you have a very big collection (say ~1000 images) you will end up with a "column" of 30x180 px to represent the collection in your rectangle, which is quite small on the width side to see anything useful

I don't say it's not possible, just that it will not be straightforward to implement...

**Comment by dterrahe** [comment]
Can this be closed as a wont-fix? The focus seems more on filemanager than lighttable view anyway, unless this has changed recently?

**Comment by Nilvus** [comment]
I agree. @AlicVB: regarding your last comment, I would like your view on this issue and @dterrahe comment before closing it with won't fix label. Feel free to do it of course.

**Comment by AlicVB** [comment]
yep, it can maybe be implement one day, but currently, there's much more important things to do/fix...
