### ISSUE TITLE
Image attributes sorted in "Collect images" panel

### ISSUE THREAD

**Issue by l0f4r0** [darktable-org/darktable#6122]
**Describe the solution you'd like**
It would be nice that image attributes are sorted in alphabetical order in "Collect images" panel so we can identify them more quickly.
(They don't seem to be in any particular order currently)

**Alternatives**
Read all image attributes until we get the one we are looking for.

**Comment by johnny-bit** [comment]
Alphabetical sorting is the worst sorting in such cases. Current order is what can be described as "probably most used at the top"

What I would recommend is - pay attention to #5478 - it's IMO better idea.
(closing this issue if you agree is good idea too ;))

**Comment by l0f4r0** [comment]
Thanks for the pointer Hubert :)
Yeah, I think grouping would be nice as well indeed.

I understand the "probably most used at the top" order but I think it's a subjective topic here. What is most used by one user can be less used by another and vice versa (hence the "probably" I presume but it has limitations like Garrett in the other issue who uses "tag" mainly). It's difficult to chose in sb's place, that's why I've suggested alphabetical order that seems more neutral.

Ultimately, we could even imagine a dt global setting like "[ ] Order lists in alphabetical order instead of probably most-used" so final choice is let to the end-user.
