### ISSUE TITLE
Last image in collection cannot be rejected in darkroom view

### ISSUE THREAD

**Issue by MR-DOS** [darktable-org/darktable#6131]
**Description of the bug**

When darkroom view is used, it is impossible to reject the last image in collection. The only way to reject last image in collection is from lighttable view.

**To Reproduce**
1. Set up a collection with 2 or more images
2. Open the last image in darkroom view.
3. Try to reject the image.
4. Nothing happens!

**Expected behavior**

It should be possible to reject the last image of collection. Probably.

**Platform:**
 - Darktable Version: 3.0.1
 - OS: Ubuntu 20.04 amd64
 - No OpenCL due to old hardware
 - Intel i915 integrated GPU on i5-3360M, default Ubuntu driver

**Comment by maboleth** [comment]
Works in master git version and probably 3.2 

Please try to update DT to 3.2 and check this again.

**Comment by MR-DOS** [comment]
Thanks, I will try it once 3.2 comes to my system repository (I always break something when trying to switch several times between repositories or self-compiled SW).

**Comment by junkyardsparkle** [comment]
3.2 has a completely re-written lighttable, with some changes that impact how rejecting in darkroom view works, see #5968 for information about that before opening a new issue... meanwhile, this one can probably be closed as not relevant to current version.

(IIRC the behavior in 3.0.1 on the last image of a selection in darkroom was that it actually *did* get rejected, but there was no visible indication of it happening until you went back to lighttable view... but I may be remembering wrong.)

**Comment by junkyardsparkle** [comment]
@MR-DOS Can this be closed?

**Comment by johnny-bit** [comment]
Does not replicate on 3.2.1 nor on current master. Closing :)
