### ISSUE TITLE
Fujifilm XF10 noise profiles

### ISSUE THREAD

**Issue by simone-199** [darktable-org/darktable#6137]
Hi, 

following the guidelines described here [https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/](url), I have generated a noise profile for my Fujifilm XF10; it seems to work reasonably well. Here you find attached the tarball generated with Darktable for your consideration.

[darktable-noiseprofile-20200701.tar.gz](https://github.com/darktable-org/darktable/files/5145049/darktable-noiseprofile-20200701.tar.gz)

Thanks in advance.

Simone

**Comment by hatsunearu** [comment]
Looks like this deviates quite a lot from the ideal noise profiles, anyone know if this is good enough to be included?

**Comment by rawfiner** [comment]
Thanks the profile looks good, I'll integrate it.
The deviation at high iso is expected, there are deviations like this in the shadows on every profile I saw.

**Comment by rawfiner** [comment]
Thanks!
