### ISSUE TITLE
Panasonic DC-G95 Noise profile

### ISSUE THREAD

**Issue by GregChiavelli** [darktable-org/darktable#6138]
Hello,

Here's my generated noise profile for the Panasonic DC-G95. I made it following this tutorial : 
https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/

Tested on some pictures previously taken, and seems to work fine (especially for Milky Way photos, at least for my tastes).

I hope it may help.
[darktable-noiseprofile-20200829.tar.gz](https://github.com/darktable-org/darktable/files/5145123/darktable-noiseprofile-20200829.tar.gz)

**Comment by da-phil** [comment]
This was merged to master in https://github.com/darktable-org/darktable/pull/7311.
Hence the issue can be closed.
CC: @TurboGit

**Comment by johnny-bit** [comment]
We'll close it then!
