### ISSUE TITLE
Please sanity check configuration values on input

### ISSUE THREAD

**Issue by bremner** [darktable-org/darktable#6139]
I recently had a Debian bug [report] where the user somehow had an empty height setting for the histogram, and was mystified that their histogram didn't work. In order to avoid such problems (and bug reports) it would be nice if obviously nonsensical configuration values could be rejected. One idea that came up on IRC was clamping the numerical values to the ranges specified in the default `darktablerc`.

[report]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969137

**Comment by johnny-bit** [comment]
It should get min/max from `darktableconfig.xml` :) default darktablerc only has defaults.

**Comment by johnny-bit** [comment]
@bremner - check #6403 should imo cover all your needs :)
