### ISSUE TITLE
Metadata editor no longer has drop downs

### ISSUE THREAD

**Issue by steple** [darktable-org/darktable#6153]
**Describe the bug**
Metadata editor no longer has drop downs.  That makes it much harder to set metadata to be the same across multiple images on a per field basis.  That breaks my workflow - I have lots of images with the same metadata.  When adding new images, the easiest way to set the metadata is to select 1 existing image and then use the drop down to set the metadata (saves me from typing and makes sure metadata is the same).

**To Reproduce**
Select any 2 images with different metadata and have a look at the metadata editor.

**Expected behavior**
I would like to get the drop down back please.

**Screenshots**
Here is a screenshot of the drop down that used to exist:
![image](https://user-images.githubusercontent.com/9641413/91665214-bf1d5f80-eaa8-11ea-8725-d84e09b8710e.png)

**Platform (please complete the following information):**
Ubuntu 20
dt built from source

**Additional context**
This commit 'broke' it.
```
commit 9a2b523a91e213629af4e8516c60e08e22e00b1a
Author: phweyland <philippe.weyland@laposte.net>
Date:   Fri Jan 31 22:19:47 2020 +0100

    replace combox by textview - allow better control on multiline text

 data/themes/darktable.css |  13 ++
 src/libs/metadata.c       | 493 ++++++++++++++++++++++++++++++++--------------
 2 files changed, 354 insertions(+), 152 deletions(-)
```

**Comment by steple** [comment]
Is it possible to have both multiline text and drop downs?

**Comment by Nilvus** [comment]
Not sure? @phweyland?

**Comment by phweyland** [comment]
> Is it possible to have both multiline text and drop downs?

no, drop downs works with combobox, not with text box.



> that breaks my workflow - I have lots of images with the same metadata.

should not. right-click on the cell, and you get a popup with the list of metadata of the selection (when <leave unchanged>). That works the same way as drop down did.

**Comment by steple** [comment]
> should not. right-click on the cell, and you get a popup with the list of metadata of the selection (when ). That works the same way as drop down did.

Yes! Beautiful, thank you.
