### ISSUE TITLE
List or export short cuts

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#6156]
**Is your feature request related to a problem? Please describe.**

I really like the shortcuts in Darktable but with the number of them growing I have hard time keeping up - remembering what is there and also my own shortcuts.

**Describe the solution you'd like**

Darktable already has very good feature to search modules (within shortcut assignment) - for example search for "exposure" and the module is located so we can assign short cut.

I would really love to see search for custom shortcuts or search for all shortcuts and ideally save as text.

**Alternatives**

I tried exporting the shortcuts but the produced file has all the possible shortcuts and possible values (backup of shortcuts). It is very good as a backup. Sadly - I can't filter it in a nice way.

This is where the knowledge of coding is much appreciated and the lack of it sadly very noticeable.

**Additional context**

**Comment by johnny-bit** [comment]
Would pressing "H" help you there? it shows nice list of available shortcuts including your own!

**Comment by Nilvus** [comment]
What @johnny-bit describe show you shortcuts available on current view (so it's dynamic). The best reminder you could have. Think about reading (if you never do that) articles from new release in www.darktable.org/blog. I suggest you to read at least 3.0 and 3.2 ones. That will learn you lot of darktable features, and so will help you save lot of time by knowing more how to use it.

**Comment by vancouverbluesea** [comment]
@johnny-bit Thank you - this really helps. I am few months behind with the move to 3.x - had hardware limitations and now a few knowledge gaps... appreciate your help!
@Nilvus Thank you - I appreciate the guidance. The documents are very detailed and very beneficial!

**Comment by vancouverbluesea** [comment]
Thank you to all darktable developers - fantastic software!
