### ISSUE TITLE
Zoomable - thumbnails of the bottom row flickering

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6160]
@AlicVB 
I hope this is the last glitch in Zoomable that I discover. :D 

It happens when trying to rate images, the bottom row flickers (actually, thumbnails are centering themselves to the grid). 

The pre-condition for this to happen is to have thumbnails (the bigger the better) slightly or partly covered by the screen - so they are not shown in their full fit.

Like this:
![flicker](https://user-images.githubusercontent.com/2467520/91703265-33740380-eb7a-11ea-9df2-d6cb9ac7dce0.gif)

Steps:
- Zoomable mode showing many images at once (however, bigger thumbnails display it faster). Try several zoom levels.
- Be sure to select the thumbnails from the middle, not from the beginning.
- Have the bottom row of thumbnails partly covered by the screen.
- Try to rate any image on the screen.
- Notice flickering/centering of the bottom row.

Latest GIT master ver.

**Comment by AlicVB** [comment]
OK, I suppose that the main flickering present here (the thumbnail which change its position is no more present in current master (I've done a fix for that) But I'll have a look anyway to if it's not possible to avoid reload at all in this case...

**Comment by maboleth** [comment]
Man I wish I was the programming wiz like you guys... it's my unfulfilled dream, but I suck at math so complex programming skills was never an option. My max. was CSS & HTML with a bit of Javascript. I stare at your code like a sheep.

Yeah, this bug was fixed. :)
