### ISSUE TITLE
[regression] #5125 came back --> Color picker in white balance loses content if switcing to other mode like camera

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6165]
**Describe the bug**

@johnny-bit did the wonderful re-design of the white balance module, however a regression happened as #5125 came back

**To Reproduce**
pls see #5125

**Expected behavior**

as after #5137

**bisect**
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1443fff87122fe59e6302b9c67bf82161fa45d45
c5569b4a6d8ab5a349f8967ed40613e2bb965d34
b8d6720dd41bf2944e2c547ddcdff58024ef2227
e1372161b8aabf61d7d2cd323c67951a24934e69
2eeb206f79517121d823b3bc19c176d667adaef7
cad6f517b7df1a427c5250412f68821c01cf67cb
1b15f29408a9904387e124a3c36b4e6f4f3ab430
2481e8e073910e19555da56abd01e142b180606e
1f2ee768f744455718ba2aaf07fbcd8cbdaf300a
f144985ad890832fa01a48d6f95a2ed1194c19c5
833765d117d56dd1cff74d714ee1ecf1c5683a65
c236a81f3193dc27d26d45001ec6c5f158840887
13c78d93f9e8bd8912ca7d1d54314bd7fc6f36e6
f14bb1e945e3ce116ee5ecc0d7e9ee3e04ca3ed9
1b184750cd18918722c04be4778a694e2c8a7e73
f1132944c06f6d60ec0d576a1272bb0b9dbc2024
44784516104c46654107c1f9731186350f69cce1
6041e68c9849b5a368e87da7077b11c0242c6db6
3d98abc754c976dad43014c3ff3952ea080320e9
454c64cb6b7a52d3925bc19c350ae0090f0bd9ae
9726c902cbdf1f3699a299398bfa195ab5ff92c8
f67b72424c618a6e665bb3cac2e8c8f01d2cd599
442f5df8ff7ad1d5e42f89f4c6f8603ea08f2042
ebfe23fb7282e83e5a21619da434b730f5b71a25
3dc02d15b528a185b71fbd16b4720546aae02037
5ffa9483ece446dc081724af75bfdbeec35119c6
a4f5087ffa7800e656da50947b193b00e31395b7
d984f1566388334b9e0ce1de898396cdad016554
235c8744378dc102e27adc997b6b97eca6f023e7
6bb8a1a451c09f608d922bb23caa611c2abd6097
fecacbac367a52347b8136dd4533ca7ef978aa40
```
Keine binäre Suche mehr möglich! --> no more binary search possible (all did not build and had to be skipped and are from johnny_bit, sorry for that)

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 
* darktable version : 3.3.0+215~gfecacbac3
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

@dterrahe maybe you also have an idea?

**Comment by dterrahe** [comment]
I promised @johnny-bit I would pick up temperature.c now that he's finished with it and convert it to introspection framework (to also improve history tooltips). Hopefully I'll then also come across the cause of this.
