### ISSUE TITLE
preferences: no way to search for a particular shortcut

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6174]
The new preferences organization is a good work, thank you! Thanks to all the developers!

But I cannot find any way to look for a particular shortcut. If I want to know what action is activated by the R shortcut, I expect at least that looking for "r" finds, with all the occurrencies of the r letter in the descriptions, the R shortcut too. But it doesn't happen.

A better solution would be to have two search boxes, one for the text (as it is implemented now) and another for the shortcuts.

**Comment by paolobenve** [comment]
Does anyone think this enhancement is worth an attention?

**Comment by elstoc** [comment]
Not really. Press H in any view to list the shortcuts for the current view. If you want to find out what shortcut R allocates to in a particular darkroom view, attempt to reallocate it to another action in that view and you'll get a messagebox telling you what it's currently allocated to. If it's not allocated already, the reallocation will succeed.

**Comment by johnny-bit** [comment]
I honestly tried to implement it and I'd go with @elstoc on that - there's no point. The `H` key is great because it gives out contextual help every time. The reassociation of key prompt informs you "hold on, that key is used by this thing". Having yet another way to search for key is overbearing and packs interface.

**Comment by johnny-bit** [comment]
Well, #8078 offers waaaaay better search mechanisms and contextual help (and is "about to" land for 3.8 :) )IMO #8078 essentially fixes all standing issues with shortcuts (but as always is the case - may bring new ones ;) ). I removed no-activity label so in cae I forget to close it, the bot will remind me to check.

**Comment by johnny-bit** [comment]
Well... #8078 landed some time ago, the shortcut search in it is quite powerfull, additionally it adds hints to elements that it controls... It's great ;)

You can test it by trying @wpferguson's windows insider builds if you're using windows :) https://discuss.pixls.us/search?q=windows%20insider%20%23software%3Adarktable%20%40wpferguson%20tags%3Awindows%20order%3Alatest_topic
