### ISSUE TITLE
no way to recognize changed preferences

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6176]
An issue I have or may have, specially when upgrading to a new version, is that I have no way to know what preferences are not at the default value.

Many apps are used to format bold or italic (probably another way could be better) the preferences which have been changed.

I think this would be useful with shortcuts, too. They are organized in a tree-way, if a leaf isn't at the default, all the tree would be bold/italic/ecc. Also because of the _reset_ function: without a way to know what isn't already reset, that operation will produce fear in the user, fear to loose some shortcut he/she has set.

**Comment by TurboGit** [comment]
Would be nice to have indeed.

**Comment by difrkaguilar** [comment]
I think that per module, using the same **reset** button but with a change of color would be a nice and simple solution to that issue.
For instance: without touch anything the button is gray. At the moment users do a change in any slider the button change color. If users want to reset, touch the icon and everything back to default. The icon back to the initial stage.
Inside the modules if some parameter change should be an indicator like a little dot to show what parameter users have changed.
This is my idea. But maybe developers are creating something better to do it.
