### ISSUE TITLE
Can't build anymore on Ubuntu 20.04

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#6177]
Since a couple of days, I get a linking error when trying to build on Ubuntu:
```
...
Scanning dependencies of target collect
Scanning dependencies of target location
[ 48%] Building C object src/libs/CMakeFiles/collect.dir/collect.c.o
[ 48%] Building C object src/libs/CMakeFiles/location.dir/location.c.o
/usr/bin/ld: libdarktable.so: undefined reference to `dt_atomic_get_int'
/usr/bin/ld: libdarktable.so: undefined reference to `dt_atomic_set_int'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/darktable.dir/build.make:173: src/darktable] Error 1
make[1]: *** [CMakeFiles/Makefile2:2324: src/CMakeFiles/darktable.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Linking C shared module libimage_infos.so
[ 50%] Linking C shared module libfilmstrip.so
[ 50%] Linking C shared module libprint.so
[ 50%] Linking C shared module libmap.so
...
```
Investigating a bit, I though it could be a missing `#include "common/atomic.h"` in develop.h, but nope.

Any clue ? Thanks.

**Comment by Mark-64** [comment]
Culprit seems to be f88183fc60dcff01edf471a13dbd2cdb6d4d22ba.
There is definitely a missing include

**Comment by Nilvus** [comment]
I can't reproduce that. Just compiled last master and it's all good. I'm on Ubuntu 20.04 too.

**Comment by TurboGit** [comment]
I would remove previous build and rebuild from scratch:
```

$ rm -fr build
$ ./build.sh
```

**Comment by Mark-64** [comment]
Weird.
build.sh does work, but if I build manually 
`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/darktable/ ..` 
it fails, while its works instead with 
`-DCMAKE_BUILD_TYPE=Release` 
or 
`-DCMAKE_BUILD_TYPE=RelWithDebInfo`

The result is that I can't build with Eclipse IDE in Debug mode

**Comment by johnny-bit** [comment]
Debug release not recommended. RelWithDebInfo has enough data for debug session.

**Comment by parafin** [comment]
Even if Debug build is not recommended, it still should be buildable, shouldn't it?

@Mark-64, so does adding an include help or not? It should IMHO.
