### ISSUE TITLE
filmicrgb: issues with scene-referred default preset

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6200]
#6097 attempted to stop the change in workflow requiring a restart.

However replacing the auto-apply of the filmicrgb with a default preset does not achieve the same as the original intent for this module.

A simple demonstration with scene-referred workflow (after a restart to simplify the scenario)

1. Discard the history stack of an image (with no in-camera exposure bias set) and load it in the darkroom
2. Click the 'preset' menu on filmicrgb (it does not show the "scene-referred default" in bold so it is not selected)
3. Manually select the "scene-referred default" preset or click 'reset parameters'
4. Examine the history stack: the latest entry is filmicrgb and it shows that the hardness has changed from its default

If you attempt reset parameters on an image with an in-camera exposure bias the white and black relative exposures also change. If you select the 'default' preset on the same image only the hardness changes. The former (what happens when you reset parameters) is how it should work by default.

When I moved exposure to a using a preset for scene-referred workflow I intentionally did not do the same with filmicrgb because the default settings for this module include adjustments based on the exposure bias from the image's Exif data. As far as I'm aware, this cannot be reflected in a preset.

**Comment by elstoc** [comment]
@TurboGit as this is your PR I wanted to raise an issue to discuss rather than just issuing a straight 'revert'

**Comment by johnny-bit** [comment]
This is sorta my fault as I haven't tested #6097 deep enough, just that "it works(tm)".

**Comment by TurboGit** [comment]
See #6203. There is no way to have a preset here indeed :( Too bad, but that's a fact.

**Comment by AxelG-DE** [comment]
Thank you guys
tested and seems to work

**Comment by AxelG-DE** [comment]
I appreciated the hardness increase :-)
