### ISSUE TITLE
Iop Order Issue w/ 2x Profiled Denoise (after 3.2.1 upgrade)

### ISSUE THREAD

**Issue by Spectre5** [darktable-org/darktable#6207]
**Describe the bug**
Some pictures that I edited in a previous version of darktable are now clobbered in 3.2.1.  I have not looked at all photos, but all of the ones I looked at closely (in darkroom) have two instances of the denoise module.  The images are now just lines or grids of totally random colors.  If I open the file and select the first instance of denoise in the history stack, then it shows the image fine, but when I select the second instance, it is back to a garbage image.  I have tried to remove the images and re-import them (with xmp), but this did not solve the issue.  I'm not certain what version of darktable I originally edited this image in.  Furthermore, I do not see the second instance of the denoise module shown in darkroom (in applied modules on the right panel).

**To Reproduce**
Load image with the accompanying xmp file.

**Expected behavior**
Image is the same as when I first edited it.

**Screenshots**
Notice that there is no second "denoise" shown on the right side panel (activated modules):
![screenshot](https://user-images.githubusercontent.com/31610422/92297314-efbf2800-eef2-11ea-8957-148a02d33cec.png)

When I select the first denoise instance, it seems fine:
![first_denoise](https://user-images.githubusercontent.com/31610422/92297323-06657f00-eef3-11ea-8172-c80f7bf5dcc2.png)

But selecting the second makes it bad again:
![second_denoise](https://user-images.githubusercontent.com/31610422/92297328-0f565080-eef3-11ea-9314-a1a19e7a5f45.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Ubuntu 18.04.5 LTS
 - OpenCL activated: Yes (problem persists when disabled too)
 - GeForce GTX 650 Ti BOOST/PCIe/SSE2 with "nvidia-driver-450 (open source)".  I've tried a few others without success.

**Additional context**
Darktable is installed from http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_18.04/
I've attached an example xmp file.  XMP file upload appear to not be supported for github upload, so I've added a ".txt" extension to the xmp file.
[IMG_6793.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/5177513/IMG_6793.CR2.xmp.txt)

**Comment by Spectre5** [comment]
I started darktable from the command line to see if I get any errors printed there.  The following was shown when I opened the image in darkroom, which certainly appear to be relevant.  I have no touched this file in some time and it certainly did export fine when I first worked it (I checked my exported jpg again and it is fine).  I think after upgrading to 3.0.1 I did select all files in my entire library and selected "write xmp" just to be sure that I had current xmp files for all photos in the library.  I'd assume that wouldn't mess anything up...

```
$ darktable
cannot get iop-order for denoiseprofile instance 1
[dt_ioppr_check_iop_order] history module not used but enabled!! denoiseprofile 1(2147483647) image 14150 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] history module not used but enabled!! denoiseprofile 1(2147483647) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] history module not used but enabled!! denoiseprofile 1(2147483647) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] history module not used but enabled!! denoiseprofile 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! denoiseprofile 1(2147483647) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] history module not used but enabled!! denoiseprofile 1(2147483647) image 0 (dt_dev_modules_update_multishow)
```

**Comment by TurboGit** [comment]
Looks like an IOP order issue. I suppose that you don't have this issue with new edits, right?

This is a know issue, previous edit from 2019 (from Sept to Nov IIRC) may have a broken history. The solution is to reset the IOP order. See module order in dt 3.2.1 in the bottom of darkrroom's right panel.

**Comment by Spectre5** [comment]
Right, I have not seen this issue with any new edits.

Unfortunately, resetting the IOP order doesn't seem to help here.  It is set to "v3.0" and I tried resetting it (stays as v3.0) as well as selecting "legacy" from the drop down, but in all cases the image still does not display correctly.  I also tried closing and restarting DT after making those changes, just to be sure.

**Comment by TurboGit** [comment]
Ok, so the only solution would be to reset the edit and start over.

**Comment by Spectre5** [comment]
Is there any way to edit the xmp file to fix it?  I could write a script to do that if it will fix it.  I have probably 1000-2000 images with this issue if your time frame is right.

**Comment by Spectre5** [comment]
Based on reading some of the code to understand some of the IOP, I've found something that *appears* to fix the issue for this 1 XMP file.  If I remove this image from darktable, edit the xmp as indicated below, then re-import it, it appears to load correctly.  With this seeming to work, I have two questions that I hope someone (a dev) can help with:

1. Does this seem reasonable?  Perhaps this was caused from when I selected all images in the library (in DT 3.0.2) and used "write sidecard files" as I do have images affected that are *not* from edits during the dates @TurboGit indicated.  I also never used DT 3 before 3.0.2.  I did know there were issues with some release candidates for 3.0.0 which is why I did not upgrade until later.  So any edits I made during those dates were with DT 2.X.  Perhaps "write sidecard files" messed up some previous xmp files.  Just guessing here.
2. Can someone recommend an automatic way to detect which XMP files would need this fix applied.  I'm sure I wouldn't want to make this change to all edits, but I need some way to know which ones have my root issue so i can edit only those xmp files.  Then I will delete my entire library and import all images with xmp sidecars.

To make the supplied xmp file work, I changed "xmp_version" to "2" and I removed the line with "iop_order_version" in it (or, equivalently, make "iop_order_version" equal to "1" in that case).

```
   darktable:xmp_version="4"
   darktable:iop_order_version="2"
```

My thought process was that I wanted to select the "else" clause within this block of code so that the DT_IOP_ORDER_LEGACY is used, since I know this edit was from long enough ago that the legacy order would be used (pre DT 3.0).  In fact, this edit was originally done in DT 2.6.X.  Using "xmp_version" of 2 does not work, even though that also uses this legacy order for the "iop_order_list".

```
    else if(version == 3)
    {
      iop_order_version = DT_IOP_ORDER_LEGACY;

      if((pos = xmpData.findKey(Exiv2::XmpKey("Xmp.darktable.iop_order_version"))) != xmpData.end())
      {
        iop_order_version = pos->toLong() == 2 ? DT_IOP_ORDER_LEGACY : DT_IOP_ORDER_V30;
        iop_order_list = dt_ioppr_get_iop_order_list_version(iop_order_version);
      }
      else
        iop_order_list = dt_ioppr_get_iop_order_list_version(DT_IOP_ORDER_LEGACY);
    }
```

**Comment by Spectre5** [comment]
Also note that when this edited xmp file is read into DT 3.2.1, it is edited by DT to set "xmp_version" back to "4", "iop_order_version" to "1", and then it created a new line for "iop_order_list".  So after re-import, the file contains:

```
   darktable:xmp_version="4"
   darktable:iop_order_version="1"
   darktable:iop_order_list="rawprepare,0,invert,0,temperature,0,highlights,0,cacorrect,0,hotpixels,0,rawdenoise,0,demosaic,0,mask_manager,0,denoiseprofile,1,denoiseprofile,0,tonemap,0,exposure,0,spots,0,retouch,0,lens,0,ashift,0,liquify,0,rotatepixels,0,scalepixels,0,flip,0,clipping,0,toneequal,0,graduatednd,0,basecurve,0,bilateral,0,profile_gamma,0,hazeremoval,0,colorin,0,negadoctor,0,basicadj,0,colorreconstruct,0,colorchecker,0,defringe,0,equalizer,0,vibrance,0,colorbalance,0,colorize,0,colortransfer,0,colormapping,0,bloom,0,nlmeans,0,globaltonemap,0,shadhi,0,atrous,0,bilat,0,colorzones,0,lowlight,0,monochrome,0,filmic,0,filmicrgb,0,colisa,0,zonesystem,0,tonecurve,0,levels,0,rgblevels,0,rgbcurve,0,relight,0,colorcorrection,0,sharpen,0,lowpass,0,highpass,0,grain,0,lut3d,0,colorcontrast,0,colorout,0,channelmixer,0,soften,0,vignette,0,splittoning,0,velvia,0,clahe,0,finalscale,0,overexposed,0,rawoverexposed,0,dither,0,borders,0,watermark,0,gamma,0"
```

**Comment by Spectre5** [comment]
Pinging @jenshannoschwalm since I've seen him active on a number of past iop issues.

**Comment by jenshannoschwalm** [comment]
I can only recommend @TurboGit s suggestion

> Ok, so the only solution would be to reset the edit and start over.

To make it short; there could be
1) **non resolvable** issues in 2.6 developments because of rounding errors for iop-order written to sidecars with improper precision. It really took a while to fully understand those problems. Basically after adding removing iops you could end up with illegal iop order. So -- unfortunately no safe afterwards fix
2) **could be fixed** from 3.x versions from about one year ago. But i know of no safe method and thus no scripting way to analyse.

**Comment by Spectre5** [comment]
Ok, I'll keep poking around for other ideas.  Unfortunately it appears that nearly all files in my entire library are affected!  I went back to some of my earliest edits and those images are also ruined.  One was done with DT 2.2.1 (Based on jpeg exif tag).  The solution indicated above did not work for it, but removing "iop_order_verison" from the xmp and changing "xmp_version" to "1" did work for it!  I may try a solution of reading DT exif tag from jpg images and "mapping" certain versions of DT to certain "xmp_version" numbers.  But before I do that, is there a risk?  I understand you guys have said there could be non-resolvable issues, but if doing this solution makes the picture now appear correct in darkroom, does that mean this solution worked?  Or do you think there would still be some sort of underlying issue that will creep up again?  I'd be sad to lose my entire library of edits

**Comment by jenshannoschwalm** [comment]
I looked again at the sidecar you sent earlier. There might be something there that could be fixed.

I will have a look at it if you can share some a few of your raw files and corresponding xmp

BUT; it is a **very** bad idea to manually change the iop_version or other ways! It would be the best to not touch or reopen those images in dt.

After sharing on your side and checks on my side i will come back to you ...

**Comment by TurboGit** [comment]
@Spectre5 : I want to at least clarify something (I saw your message the in mailing list). You said that you've used 2.2, 3.0 and then 3.2.1.

My question is : have you used any dev version built yourself or downloaded from somewhere ?

The bug I was talking about was only in a dev version for 3 or 4 months. So I really want to understand what is going on there.

BTW, I hope you have backup of your .xmp!

**Comment by MStraeten** [comment]
workaround to conserve the edit:
there are two instances of denoise(profiled) in the history stack but only one visible in the active module list.
You can try to save the history stack as a style and then apply this style after dropping the history stack. Then both instances are back.

**Comment by Spectre5** [comment]
Hello @jenshannoschwalm, I've uploaded some examples CR2 files with matching XMP as well as the exported JPG to dropbox [here](https://www.dropbox.com/sh/vhp14nykw2ox1xr/AABs4qlL5WfEo2ty1EtH1rMfa?dl=0)  The issue spans all edits of my files in DT 2.X and I've provided examples for multiple versions that I found in my library.  I also provided 1 example for DT 3.0.2 which of course does not have the issue, but provided just for reference.

@TurboGit - I've never used a development version and I've never compiled darktable myself.  I've only used installations from repositories.  I used to use Pascal's PPA, but when he stopped updating it I think the suggested repository was the opensuse one I indicated in my OP.  I have backups of my xmp files, but only after I installed DT 3.0.2 and hit "write sidecard files".  They are from before opening DT 3.2.1.

**Comment by Spectre5** [comment]
Thanks for the suggestion @MStraeten, I will try to test it out too

**Comment by Spectre5** [comment]
@MStraeten, I tried this on one pictures and although it made it once again show the real image, it did not include the 2 instances of profiled denoise.  Note that only 1 instance shows in the active modules because of the iop order issue.  Normally (in older DT versions), both would appear there.  And my "fix" (hack of editing the xmp) does keep both instances of the profiled denoise when re-imported.

**Comment by TurboGit** [comment]
Well, first IINM the XMP **IMG_6793.CR2.xmp.txt** you posted above is already broken by 3.2.1. Do you have the same XMP before 3.2.1 migration ?

**Comment by Spectre5** [comment]
The xmp files I linked a couple posts above to dropbox are from pre-3.2.1.  As for the xmp in the OP, here is the same one before I ever opened it in 3.2.1.
[IMG_6793.pre3.2.1.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/5178442/IMG_6793.pre3.2.1.CR2.xmp.txt)

**Comment by TurboGit** [comment]
Thanks, be sure to keep your .xmp ! It looks like a genuine bug in dt :( I need to debug this to see where it fails!

Setting iop_order_version to 2 in the XMP and reloading the image seems to workaround the issue. But this should not be needed.

**Comment by Haribo-66** [comment]
I normally used 4 versions of watermarks, adding different labels to quite a few hundrets of photos. All of them look damaged in a simular way.

I tried searching with the new used modul feature to collect them. 
My problem is that the search does not distimguish between a single working watermark and all the additional watermarks. 

I think finding all the renamed moduls individually could help here a lot.
