### ISSUE TITLE
Chroma noise removal request for Denoise module

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6214]
Denoise module is doing its job wonderfully for my Canon 5d iv camera. It finds corresponding ISO and applies required settings automatically.

However, many times I want to remove chroma noise only, without messing any of the detail - luminance. I toyed with the settings and the best I've found was to lower the Patch size to 0 to recover some of the detail. But still it destroys some fine detail in the process.

My request would be to have the slider for the chroma noise only.

**Comment by parafin** [comment]
There are blending modes for that.

**Comment by maboleth** [comment]
Omg, how did I miss that! Sorry. And thanks a lot! :-)
