### ISSUE TITLE
undefined reference to 'dt_atomic_...' when I build dt for Debug

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#6216]
When I try to build dt for debugging with the command
`~/darktable/build$ bash ../build.sh --prefix /opt/darktable --build-type Debug`

I get error
```
/usr/bin/ld: libdarktable.so: undefined reference to `dt_atomic_get_int'
/usr/bin/ld: libdarktable.so: undefined reference to `dt_atomic_set_int'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/darktable.dir/build.make:171: src/darktable] Error 1
make[1]: *** [CMakeFiles/Makefile2:1588: src/CMakeFiles/darktable.dir/all] Error 2
```
When I use _"--build-type Release"_ no errors occur.

- Darktable Version: master
- OS: Debian 10

**Comment by MStraeten** [comment]
Debug is not recommended, better use build type RELWITHDEBINFO
That should also be usable for debugging
See https://github.com/darktable-org/darktable/issues/6177

**Comment by parafin** [comment]
Yeah, it should have been already fixed. Which commit are you on?

**Comment by esq4** [comment]
0e89fa0d047ca8d08c616c82e66a274bc350a71b

**Comment by parafin** [comment]
Is it reproducible when doing the build from empty build directory? Please post the full log of cmake and make runs.

**Comment by esq4** [comment]
Yes, build directory is empty.
[build.log](https://github.com/darktable-org/darktable/files/5178537/build.log)

**Comment by parafin** [comment]
OK, I can reproduce.

**Comment by parafin** [comment]
Fix pushed.
