### ISSUE TITLE
xmp "lr" property not recognized calling exiv2

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#6222]
Not critical but long lasting issue.

In export metadata config the "Xmp.lr.hierarchicalSubject" tag should be listed in: 
![image](https://user-images.githubusercontent.com/23012047/92327117-d242a900-f02d-11ea-868a-e60f52a01209.png)

The code which extracts the list of known tags is there:
https://github.com/darktable-org/darktable/blob/4f01984998bc9c0a042a5205d0b769501eb44603/src/common/exif.cc#L149

I've opened an issue on [Exiv2](https://github.com/Exiv2/exiv2/issues/1206) but that's work fine on their side, whatever the exiv2 version. That's why I'm opening the issue on dt side now.
Thanks for the support of Robin @clanmills.

**Comment by clanmills** [comment]
Are you looking for the Xmp.lr.BlaBlaBlackSheep tags?  Can you attach your file, please, so I can see if they are present?  

The API what we discussed: `Exiv2::XmpProperties::propertyList(prefix);` is telling you that the namespace prefix `lr` is known to Exiv2.  However your file may, or may not, use the `lr` prefix.  For example:

```
618 rmills@rmillsmbp:~/temp $ curl -LO --silent https://clanmills.com/Stonehenge.jpg
619 rmills@rmillsmbp:~/temp $ exiv2 -px Stonehenge.jpg 
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
620 rmills@rmillsmbp:~/temp $ exiv2 -M'set Xmp.lr.RockNRoll is here to stay' Stonehenge.jpg 
621 rmills@rmillsmbp:~/temp $ exiv2 -px Stonehenge.jpg 
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
Xmp.lr.RockNRoll                             XmpText    15  is here to stay
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
622 rmills@rmillsmbp:~/temp $ exiv2 -M"set Xmp.lr.NextLine it'll go down in history" Stonehenge.jpg 
623 rmills@rmillsmbp:~/temp $ exiv2 -px Stonehenge.jpg 
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmp.ModifyDate                           XmpText    25  2015-07-16T20:25:28+01:00
Xmp.lr.RockNRoll                             XmpText    15  is here to stay
Xmp.lr.NextLine                              XmpText    24  it'll go down in history
Xmp.dc.description                           LangAlt     1  lang="x-default" Classic View
624 rmills@rmillsmbp:~/temp $ 
```

**Comment by phweyland** [comment]
@clanmills sorry I'm a bit lost here. 
We use `Exiv2::XmpProperties::propertyList(prefix);` to get and display all the tags known by exiv2 (or all existing exiv2 tags as described  on [metadata exiv2 page](https://www.exiv2.org/metadata.html)) as shown on the screenshot. This routine works for all prefixes but the lr one.

This is not related to the tags existing in a given image.

**Comment by clanmills** [comment]
And I'm lost as well because `Exiv2::XmpProperties::propertyList("lr")` is working correctly in Exiv2.  https://github.com/Exiv2/exiv2/issues/1206#issuecomment-687611178

I'm very happy to work with you to resolve this.  Would you like to screen share on Zoom and together we will get this fixed.

**Comment by phweyland** [comment]
> Would you like to screen share on Zoom and together we will get this fixed.

Yes we can try. You call me at philippe.weyland at laposte.net.

**Comment by clanmills** [comment]
Robin Mills is inviting you to a scheduled Zoom meeting.

Topic: Exiv2 Debugging Session
Time: Sep 6, 2020 20:30 London

Join Zoom Meeting
https://us02web.zoom.us/j/9129667335?pwd=cjFvWHNnMlpwOExYSE44dHFrdWtyZz09

Meeting ID: 912 966 7335
Passcode: 2ngkdc

If this is not suitable, please propose an alternative.  I'm available 7 days of the week 07.00-21.00 BST (UTC+1).

**Comment by clanmills** [comment]
Thank You for meeting on Zoom.  I understand your issue and have reopened https://github.com/Exiv2/exiv2/issues/1206 where I will document the progress of my investigation.

**Comment by phweyland** [comment]
Thanks You Robin for your help !

**Comment by clanmills** [comment]
I have documented the cause and remedy in the darktable code.
https://github.com/Exiv2/exiv2/issues/1206#issuecomment-688488556

I'm surprised by this issue and will investigate how/why Exiv2 appears to have modified its behaviour.
