### ISSUE TITLE
Reordering modules with style incompatible with multiple module instances

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#6229]
DT 3.3 git master
When applying a style which changes order of modules to a pipeline with more than one instance of some modules, weird things happen to the central preview.

To reproduce:

1. open an unedited image in darkroom
2. enable a module, do some adjustments and move it in a different place in the pipeline. For example, enable RGB curves and put it after Filmic RGB.
3. save a style out of the pipeline, including RGB curves and modules order
4. now reset the history (or open a different image)
5. create a second instance of a module, for example Exposure, with some adjustments
6. apply the style created in step 3

Observe the central preview image going crazy. Also the second instance of Exposure module disappears from the GUI, I guess an invalid .xmp is created.

![Screenshot from 2020-09-07 12-37-12](https://user-images.githubusercontent.com/43290988/92379083-2077ab00-f107-11ea-8cb5-d6aebed2be88.jpg)

**Comment by TurboGit** [comment]
Another nice one due to iop-order! I suspect the iop-order list from the style replaces the one from the image and then we lose the entry for the multi-instances in the target image. Thanks a lot for reporting !

**Comment by TurboGit** [comment]
Should be fixed in master. Can you test it and report ? TIA.

**Comment by Mark-64** [comment]
Tested and it's fixed, thank you.
