### ISSUE TITLE
toggle-last-snapshot accel has significant latency

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#6235]
**Describe the bug**
When using snapshots, I often set them to overlay the entire central view, then click on the button(s) for a fast A/B comparison. Clicking works very fast, and the speed is especially helpful when the differences are subtle, or when making a large number of comparisons while looking at different areas of the image each time. When I finally created a keyboard shortcut for the recently added "toggle last snapshot" accel, I found that it doesn't work as quickly as the button clicks, having a lag of perhaps 150ms on my (not terribly slow) hardware. It doesn't make the feature *useless*, but it does make it less useful.

**To Reproduce**
Bind a keyboard shortcut to this accel, then compare the latency to using a click on the buttons.

**Expected behavior**
The "hoped for" behavior would be a fast toggle, as similar to the clicking behavior as possible.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 and current master
 - OS: Linux

**Additional context**
My guess, looking at `snapshots.c`, is that this is due to `gtk_widget_activate` being called *before* `_lib_snapshots_toggled_callback` in `_lib_snapshots_toggle_last`; I don't know what the correct fix for this would be, but I think there are some smart people here with experience in balancing widget responsiveness vs. preview responsiveness who can probably figure it out. :-)

**Comment by elstoc** [comment]
That call to `_lib_snapshots_toggled_callback` seems superfluous. Could you retry with #6239 please?

**Comment by junkyardsparkle** [comment]
@elstoc Yes, that eliminates the lag, but since I don't really understand the reasons for the way it was done originally, I won't try to even guess about "correctness". :-)

**Comment by elstoc** [comment]
It was my code originally but I'm not certain about the 'correct' way either (apart from the obviously superfluous function call) - since the previous method obviously 'worked'. I don't know why the other change I've made reduces the latency but it does and that's good enough for me :)

**Comment by junkyardsparkle** [comment]
Then it's good enough for me, thanks... now I have that stupid song from Goonies stuck in my head...
