### ISSUE TITLE
Selecting other image in film strip does not update expander status button

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#6243]
**Describe the bug**
If you change the image via filmstrip the module expander button is not correctly updated.

**To reproduce**
To reproduce use the instructions in #5291 that lead to @TurboGit fixing the colorin and demosaic iops.

Watch out for the expander icons, after switching from jpg to the raw. The buttons for rawprepare, demosaic and more are wrong.

**Expected behavior**
Showing correct button status

**Screenshots**
![Bildschirmfoto von 2020-09-08 19-46-30](https://user-images.githubusercontent.com/50982232/92510743-974a9c00-f20c-11ea-9449-8ef753dfad4b.png)

**Additional context**
Current master 846af25 on fedora

**Comment by TurboGit** [comment]
> module expander button is not correctly updated.

What do you mean? On my side I have the button changed from deactivated (for demosaic & wb) for jpeg to activated for RAW for example.

**Comment by jenshannoschwalm** [comment]
After opening the raw directly it looks like this
![Bildschirmfoto von 2020-09-08 20-44-06](https://user-images.githubusercontent.com/50982232/92515636-39ba4d80-f214-11ea-99d4-5cf566744d4b.png)

If i open the jpeg and switch to one of the raws without history it's like this
![Bildschirmfoto von 2020-09-08 20-44-39](https://user-images.githubusercontent.com/50982232/92515740-5eaec080-f214-11ea-9b36-44cac76c9827.png)

**Comment by TurboGit** [comment]
I can reproduce but for this you need to enter the darkroom by selecting a jpeg otherwise all is working as expected.

**Comment by TurboGit** [comment]
Fixed !

**Comment by jenshannoschwalm** [comment]
Thanks
