### ISSUE TITLE
dt 3.2.1 on Windows 10 crashes in TONE EQUALIZER while zooming in and out to 100 % or 200 % in the darkroom

### ISSUE THREAD

**Issue by cabuy** [darktable-org/darktable#6244]
I am new to dt since end of June 2020.  Under dt 3.2.1 on Windows 10, I encounter every now and then (say once a week) a crash when zooming in or under mask editing while zooming in. In all cases the module stack is rather large (20 plus modules: am still in learning/experimental phase). Usually I cannot reproduce the crash and will move on with my work by restarting dt. However this time I have a raw file (.raf) and a xmp on which I can reproduce the problem.

**To Reproduce**
While viewing the picture in the darkroom and scrolling the mousewheel to zoom in to 100% and zoom out.  If repeated a few times during say 3 minutes it will crash (aka an unhandled exception occurred) and produce a .txt file.

**Expected behavior**
Zooming in and out should continue to work.

**Screenshot**
Attached.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10 Pro 64 bit build 19041.450
 - OpenCL activated YES
 - NVIDIA GeForce RTX 2080 Max-Q  Nvidia Studio Driver 452.06 

**Additional context**
To reproduce it some patience is required. While viewing the picture in the darkroom and scrolling the mousewheel to zoom in to 100% and zoom out.  If repeated a few times during say 3 minutes it will crash (aka an unhandled exception occurred) and produce a .txt file.
I have attached a screen shot, a few written .txt files, the raw file and the xmp  (the 2 latter are zipped) on which I can reproduce it.
I will keep the raw and xmp available in my installation to help with further info if needed.

Thanks for helping out.
Marc.

[DSCF2191.zip](https://github.com/darktable-org/darktable/files/5190503/DSCF2191.zip)
[darktable_bt_TOEEQ0.txt](https://github.com/darktable-org/darktable/files/5190488/darktable_bt_TOEEQ0.txt)
![Aantekening 2020-09-08 205023](https://user-images.githubusercontent.com/70954013/92517369-d67dea80-f216-11ea-8ee2-589f685ec79b.jpg)
[darktable_bt_TKUUQ0.txt](https://github.com/darktable-org/darktable/files/5190489/darktable_bt_TKUUQ0.txt)

**Comment by Mark-64** [comment]
Can't reproduce in Windows 10, DT 3.3 git master.
I have done at least 50 time zoom in and out, no crash.
Maybe the crash happens only when a specific module is enable ? Can you please try to isolate the problem better, so we can fix it ?
Thank you in advance

**Comment by cabuy** [comment]
Thank you Mark for trying to help me out.  I assume that you have tested this using the raw/xmp included in the attached zip file.  Also as you possibly have noted in the 3 attached text files it always fails on the same issue: "Access Violation at location 0000000065F45691 in module libtoneequal.dll Reading from location XXXXXXXXXXXXXX."  Not sure if that may help you any further.

Also, may I ask you whether you observe slow response time when zooming in and out on this raw/xmp combination ?  It's perhaps related to this issue. 

Now in trying to isolate or solve the problem, I was so far only successful on this particular raw/xmp.  But  when I added one more module in this xmp stack, I couldn't resimulate it any further.  (currently I hold a duplicate of this photo with the xmp whereby I can simulate this).

Oh yes, I am grateful that you try to help .  If I encounter  the problem again on another photo, I will try to capture details again and further isolate, and update this thread. 

Thank you,
Marc.

**Comment by cabuy** [comment]
The crash problem is still around, but as said before infrequently.  Most recently it crashed when I was drawing a mask in 100% preview mode.  I could not reproduce it. So I think this must be an issue due to racing conditions.  That's a guess.
I now have upgraded the BIOS/firmware and the Nvidia driver (hence the opencl library). I'll wait and see.

**Comment by cabuy** [comment]
The crash problem is still around.  I changed the subject title because all crash traces gathered so far indicate that it happens in the TONE EQUALIZER module.  See attached files mentioning "Access Violation at location 0000000065F45691 in module libtoneequal.dll". As the problem couldn't be simulated I just add someold and new crash traces.
[darktable_bt_GFBVT0.txt](https://github.com/darktable-org/darktable/files/5533520/darktable_bt_GFBVT0.txt)
[darktable_bt_6SYVT0.txt](https://github.com/darktable-org/darktable/files/5533521/darktable_bt_6SYVT0.txt)
[darktable_bt_3YZNT0.txt](https://github.com/darktable-org/darktable/files/5533522/darktable_bt_3YZNT0.txt)
[darktable_bt_TOEEQ0.txt](https://github.com/darktable-org/darktable/files/5533523/darktable_bt_TOEEQ0.txt)
[darktable_bt_BJZTQ0.txt](https://github.com/darktable-org/darktable/files/5533524/darktable_bt_BJZTQ0.txt)
[darktable_bt_TKUUQ0.txt](https://github.com/darktable-org/darktable/files/5533526/darktable_bt_TKUUQ0.txt)

**Comment by fvollmer** [comment]
I think I have the same issue:
[darktable_bt_CT5ZV0.txt](https://github.com/darktable-org/darktable/files/5726629/darktable_bt_CT5ZV0.txt)
[darktable_bt_UEZJW0.txt](https://github.com/darktable-org/darktable/files/5726630/darktable_bt_UEZJW0.txt)

I had it happen a few times with big panoramas and the tone equalizer module while zooming, but it is hard to reproduce.

Darktable 3.2.1
Windows 10 20H2 19042.685
OpenCL enabled
NVIDIA GTX 660Ti, 445.87 Driver

**Comment by cabuy** [comment]
Thanks for reporting. I am not alone anymore now with that issue.  Since it
is so hard to reproduce, I guess it's a racing condition. I understand that
the tone equalizer is cpu-bound and not using the gpu. I have the issue on
a laptop/workstation with a i9-9880 processor. What's your cpu ? (Our gpu's
are different. Mine is a RTX 2080 Max-Q.)
Marc

Op ma 21 dec. 2020 22:39 schreef fvollmer <notifications@github.com>:

**Comment by fvollmer** [comment]
i5-2500K, but I can't imagine that this memory access error would depend on the cpu :)

**Comment by NextTherapist** [comment]
Have you tried to except darktable.exe from Windows Defender like in this thread?
https://discuss.pixls.us/t/darktable-3-4-0-windows-64-bit-crashes-on-startup/22401

**Comment by fvollmer** [comment]
I would be very surprised if a memory access problem is related to the windows defender. The only reason I could imagine would a race condition isn't triggered by luck.
Do you

**Comment by fvollmer** [comment]
I would be very surprised if a memory access violation is related to the windows defender. The only reason I could imagine would be some race condition that isn't triggered due to luck if the defender is disabled (some timing stuff).

@NextTherapist Do you have any reason to believe that there is connection or is this just a short at the dark?

**Comment by johnny-bit** [comment]
@fvollmer - I've seen mem access violations and code execution violations due to antivir doing stupid stuff with memory.

Anyway - It looks like the problem *was* a weird access to memory in thread created by autothreading a loop. I think most of tone equalizer bugs were stomped out in 3.4 release, so... Can you give a try with 3.4 release and see if problem persists?

**Comment by fvollmer** [comment]
I already installed 3.4 and will give you feedback if I see another crash with the tone equalizer

**Comment by johnny-bit** [comment]
No feedback - no crash? Plz ping if crash - will reopen :)

**Comment by cabuy** [comment]
Looks ok, big thank you to all !!!

Marc.

PS have tested and did not occur on some of the images where it occurred
intermittently before

Op di 18 mei 2021 22:25 schreef Hubert Kowalski ***@***.***>:
