### ISSUE TITLE
Coredump, double free detected in tcache 2, master d6338aaf2

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6246]
openSUSE Tumbleweed 20200907
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git589.d63318aaf2
OpenCL loaded but not available

imported ~500 images, applying tag to about half selected
get coredump:
    [xmp_import] creating tag: Second Half
    free(): double free detected in tcache 2
    Aborted (core dumped)

coredump attached
err, too large, see:
  http://wahoo.no-ip.org/~paka/core.darktable.1000.a651b386468741b9b24b66be5d32f8a4.1168.1599620702000000000000.lz4.

**Comment by ptilopteri** [comment]
no editing had been performed, only import and assign tags

**Comment by ptilopteri** [comment]
sorry bout perms, changed, core dump should now be readable.

**Comment by ptilopteri** [comment]
and another core dump while culling images
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

correct permissions this time

http://wahoo.no-ip.org/~paka/core.darktable.1000.a651b386468741b9b24b66be5d32f8a4.10432.1599622522000000000000.lz4

**Comment by ptilopteri** [comment]
and another core dump while reopening dt

http://wahoo.no-ip.org/~paka/core.darktable.1000.a651b386468741b9b24b66be5d32f8a4.10432.1599622522000000000000.lz4


[xcb] Unknown sequence number while dequeuing request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
darktable: xcb_io.c:178: dequeue_pending_request: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)


this time was running same dt version but opensuse build
others I built locally

**Comment by TurboGit** [comment]
> darktable-3.3.0~git589.d63318aaf2

This does not seem to match a version in master! Can you clarify the build procedure ?

**Comment by ptilopteri** [comment]
sure, as I have been doing for several months:

rm -rf ./build
git pull --rebase --recurse-submodules
./build.sh --enable-opencl --install --build-type RelWithDebInfo --prefix ~/darktable_repos/

**Comment by ptilopteri** [comment]
just built 22d3179a6
trying

**Comment by ptilopteri** [comment]
another core dump while culling images
build 22d3179
core dump: http://wahoo.no-ip.org/~paka/core.darktable.1000.a35bfdcd81da421087ea70d95b8d46ea.29067.1599653028000000000000.lz4

**Comment by ptilopteri** [comment]
additional info:
malloc(): smallbin double linked list corrupted
Aborted (core dumped)

**Comment by ptilopteri** [comment]
reopened dt after crash, importing same collection

[xmp_import] creating tag: 0908a.ahs
[xmp_import] creating tag: First Half
[xmp_import] creating tag: Second Half
corrupted double-linked list
Aborted (core dumped)

core dump: http://wahoo.no-ip.org/~paka/core.darktable.1000.a35bfdcd81da421087ea70d95b8d46ea.3018.1599653606000000000000.lz4

restarting under gdb 
will report

**Comment by ptilopteri** [comment]
faulted with:  double free or corruption (fasttop)

gdb dump at:  http://wahoo.no-ip.org/~paka/dt.22d3179a6.gdb.txt

**Comment by parafin** [comment]
I see lua in the backtrace, does the issue happen if you compile without lua?

**Comment by ptilopteri** [comment]
donno...  Never built w/o lua, but currently running w/o problem (so far) in gdb with luarc moved away.

will advise 

tks

**Comment by ptilopteri** [comment]
ok running in gdb w/o luarc
no core dump but after a while it did hang, became non-responsive and would not update it's display

gdb dump here:  http://wahoo.no-ip.org/~paka/dt.22d3179.1.gdb.txt

began another instance in gdb

**Comment by TurboGit** [comment]
@ptilopteri : to me all this seems (not 100% sure) non necessary since you are the only one to have this issue so I would suggest:
- check the memory of the machine (very unlikely the issue is there but we never know)
- reduce the number of threads used by dt

To me your issue could possibly be a memory corruption. I understand it should not crash, but if detecting a failing malloc() is not too hard recovering from such an error is almost impossible.

**Comment by ptilopteri** [comment]
@TurboGit 
Just checked memory several days ago and found no problems
running with luarc moved improves it much.

one oddity noticed.
I usually run in plasma5/kde5 but even with luarc, dt seems to run
ok in icewm.  I could also try in twm or awesome or i3?
Does that make any sense?

tks, will close this issue and reopen or start a new one should I not solve it or you have
no other suggestions/thoughts?

**Comment by parafin** [comment]
I think there are 2 separate issues - memory corruption by lua and that last hang you caught. Hang looks like a deadlock in cache code. Both would be quite hard to debug IMHO.

**Comment by ptilopteri** [comment]
@parafin you are suggesting to close?

**Comment by jenshannoschwalm** [comment]
> xcb] Unknown sequence number while dequeuing request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
darktable: xcb_io.c:178: dequeue_pending_request: Assertion `!xcb_xlib_threads_sequence_lost' failed.

I think you are using X via nvidia, those messages could also be very well related to a wrongly installed nvidia driver.

**Comment by parafin** [comment]
> @parafin you are suggesting to close?

I'm suggesting to split, because there are 2 or 3 different issues here.

**Comment by wpferguson** [comment]
I've seen this

```
free(): double free detected in tcache 2
Aborted (core dumped)
```

and this

```
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

```

several times within the last week on daily builds from git master.  My case was several heavy edits with lots of retouch, liquify, and contrast_equalizer.  I also saw another one that said 

`BUG place a breakpoint at ...`

I'll try and recreate them and look at the dumps.

**Comment by wpferguson** [comment]
And I also get this one 

`corrupted double-linked list`

I have my lighttable set up in file manager mode with 5 thumbnails across.  If I scroll a 672 image collection approximately 9 rows at a time each second sooner or later I will get this and it says it core dumped, but I can't find it anywhere.

I've also seen just a hang.  With 5 thumbnails across I get about 3.25 rows at a time displayed on screen.  After one scroll the thumbnails were displaying from cache and in the second row it just stopped and hung.  No errors in the console.

This film roll had been previously imported and the cache was already generated.

**Comment by wpferguson** [comment]
Tried culling the same set of files.  Got `corrupted double-linked list`.  Again, console message says generating a core dump but none found.  This was approximagely 460 images through the collection.

Recompiled from git master with build-type Debug.  Tried culling again picking up where I left off.  Looked at ~20 images and got `malloc(): smallbin double linked list corrupted`.  Once again it said dumping core but didn't.

Debug trace showed 
```

SQL Collection for 1st:0 and 2nd:6: SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/bill/Pictures/darktable33/Seniors/Miranda'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version LIMIT ?1, ?2

SQL Collection for 1st:0 and 2nd:6: SELECT DISTINCT mi.id FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/bill/Pictures/darktable33/Seniors/Miranda'))) ORDER BY filename, CASE WHEN flags & 8 = 8 THEN -1 ELSE flags & 7 END DESC, version

266.390122 LUA DEBUG : dt_lua_async_call_alien_internal called from _metadata_view_update_values 714
266.390216 LUA DEBUG : thread 0x562b2f7e4140 waiting from alien_job_dispatch:310
266.390269 LUA DEBUG : thread 0x562b2f7e4140 taken from alien_job_dispatch:310
266.390371 LUA DEBUG : dt_lua_async_call_alien_internal called from on_mouse_over_image_changed 323
266.390587 LUA DEBUG : thread 0x562b2f7e4140 waiting from run_async_thread:157
266.390668 LUA DEBUG : gtk_wrap called from lua_update_metadata 921
266.390709 LUA DEBUG : thread 0x562b30694cf0 released from gtk_wrap:663
266.390765 LUA DEBUG : thread 0x562b2f7e4140 taken from run_async_thread:157
266.390790 LUA DEBUG : thread 0x562b2f7e4140 released from alien_job_dispatch:350
266.390804 LUA DEBUG : thread 0x562b2c5cb460 waiting from dt_lua_gtk_wrap_callback:640
266.390883 LUA DEBUG : thread 0x562b2c5cb460 taken from dt_lua_gtk_wrap_callback:640
266.390850 LUA DEBUG : thread 0x562b2f7e4140 waiting from alien_job_dispatch:310
266.390935 LUA DEBUG : thread 0x562b2c5cb460 released from dt_lua_gtk_wrap_callback:647
266.390991 LUA DEBUG : thread 0x562b30694cf0 waiting from gtk_wrap:673
266.391043 LUA DEBUG : thread 0x562b2f7e4140 taken from alien_job_dispatch:310
266.391224 LUA DEBUG : thread 0x562b2f7e4140 waiting from run_async_thread:157
266.391266 LUA DEBUG : thread 0x562b2f58f2d0 released from run_async_thread_main:146
266.391342 LUA DEBUG : thread 0x562b30694cf0 taken from gtk_wrap:673
266.391367 LUA DEBUG : gtk_wrap return for call from from lua_update_metadata 921
266.391391 LUA DEBUG : thread 0x562b30694cf0 released from run_async_thread_main:146
266.391449 LUA DEBUG : thread 0x562b2f7e4140 taken from run_async_thread:157
266.391478 LUA DEBUG : thread 0x562b2f7e4140 released from alien_job_dispatch:350
266.918885 LUA DEBUG : dt_lua_async_call_alien_internal called from _metadata_view_update_values 714
266.918948 LUA DEBUG : thread 0x562b2f7e4140 waiting from alien_job_dispatch:310
266.918961 LUA DEBUG : dt_lua_async_call_alien_internal called from on_mouse_over_image_changed 323
266.918962 LUA DEBUG : thread 0x562b2f7e4140 taken from alien_job_dispatch:310
266.919242 LUA DEBUG : gtk_wrap called from dt_lua_init_widget 315
266.919253 LUA DEBUG : thread 0x562b2f7e4140 released from gtk_wrap:663
266.919291 LUA DEBUG : thread 0x562b2c5cb460 waiting from dt_lua_gtk_wrap_callback:640
266.919302 LUA DEBUG : thread 0x562b2c5cb460 taken from dt_lua_gtk_wrap_callback:640
266.919322 LUA DEBUG : thread 0x562b2c5cb460 released from dt_lua_gtk_wrap_callback:647
266.919325 LUA DEBUG : thread 0x562b2f7e4140 waiting from gtk_wrap:673
266.919344 LUA DEBUG : thread 0x562b2f7e4140 taken from gtk_wrap:673
266.919349 LUA DEBUG : gtk_wrap return for call from from dt_lua_init_widget 315
266.919410 LUA DEBUG : thread 0x562b2f7e4140 waiting from run_async_thread:157
266.919448 LUA DEBUG : gtk_wrap called from lua_update_metadata 921
266.919461 LUA DEBUG : thread 0x562b2f58f2d0 released from gtk_wrap:663
266.919477 LUA DEBUG : thread 0x562b2f7e4140 taken from run_async_thread:157
266.919487 LUA DEBUG : thread 0x562b2f7e4140 released from alien_job_dispatch:350
266.919500 LUA DEBUG : thread 0x562b2f7e4140 waiting from alien_job_dispatch:310
266.919509 LUA DEBUG : thread 0x562b2f7e4140 taken from alien_job_dispatch:310
266.919567 LUA DEBUG : thread 0x562b2f7e4140 waiting from run_async_thread:157
266.919584 LUA DEBUG : thread 0x562b2fb1cf70 released from run_async_thread_main:146
266.919594 LUA DEBUG : thread 0x562b2c5cb460 waiting from dt_lua_gtk_wrap_callback:640
266.919621 LUA DEBUG : thread 0x562b2f7e4140 taken from run_async_thread:157
266.919636 LUA DEBUG : thread 0x562b2f7e4140 released from alien_job_dispatch:350
266.919648 LUA DEBUG : thread 0x562b2c5cb460 taken from dt_lua_gtk_wrap_callback:640
266.919662 LUA DEBUG : thread 0x562b2c5cb460 released from dt_lua_gtk_wrap_callback:647
266.919667 LUA DEBUG : thread 0x562b2f58f2d0 waiting from gtk_wrap:673
266.919676 LUA DEBUG : thread 0x562b2f58f2d0 taken from gtk_wrap:673
266.919681 LUA DEBUG : gtk_wrap return for call from from lua_update_metadata 921
266.919686 LUA DEBUG : thread 0x562b2f58f2d0 released from run_async_thread_main:146
267.552612 LUA DEBUG : dt_lua_async_call_alien_internal called from _metadata_view_update_values 714
267.552643 LUA DEBUG : thread 0x562b2f7e4140 waiting from alien_job_dispatch:310
267.552656 LUA DEBUG : thread 0x562b2f7e4140 taken from alien_job_dispatch:310
267.552690 LUA DEBUG : dt_lua_async_call_alien_internal called from on_mouse_over_image_changed 323
267.552774 LUA DEBUG : thread 0x562b2f7e4140 waiting from run_async_thread:157
267.552814 LUA DEBUG : gtk_wrap called from lua_update_metadata 921
267.552829 LUA DEBUG : thread 0x562b2fb1cf70 released from gtk_wrap:663
267.552846 LUA DEBUG : thread 0x562b2f7e4140 taken from run_async_thread:157
267.552853 LUA DEBUG : thread 0x562b2f7e4140 released from alien_job_dispatch:350
267.552865 LUA DEBUG : thread 0x562b2f7e4140 waiting from alien_job_dispatch:310
267.552871 LUA DEBUG : thread 0x562b2c5cb460 waiting from dt_lua_gtk_wrap_callback:640
267.552872 LUA DEBUG : thread 0x562b2f7e4140 taken from alien_job_dispatch:310
267.552942 LUA DEBUG : thread 0x562b2f7e4140 waiting from run_async_thread:157
267.552999 LUA DEBUG : thread 0x562b2fb1ce30 released from run_async_thread_main:146
267.553026 LUA DEBUG : thread 0x562b2c5cb460 taken from dt_lua_gtk_wrap_callback:640
267.553048 LUA DEBUG : thread 0x562b2c5cb460 released from dt_lua_gtk_wrap_callback:647
267.553051 LUA DEBUG : thread 0x562b2fb1cf70 waiting from gtk_wrap:673
267.553068 LUA DEBUG : thread 0x562b2f7e4140 taken from run_async_thread:157
267.553082 LUA DEBUG : thread 0x562b2f7e4140 released from alien_job_dispatch:350
267.553096 LUA DEBUG : thread 0x562b2fb1cf70 taken from gtk_wrap:673
267.553102 LUA DEBUG : gtk_wrap return for call from from lua_update_metadata 921
267.553108 LUA DEBUG : thread 0x562b2fb1cf70 released from run_async_thread_main:146
malloc(): smallbin double linked list corrupted
/home/bill/bin/darktable33: line 1: 17477 Aborted                 (core dumped) /opt/darktable33/bin/darktable -d lua --cachedir $HOME/.cache/darktable33 --configdir $HOME/.config/darktable33 $@
```

**Comment by wpferguson** [comment]
Compiled with lua disabled and now most of the debug messages are SQL Collection...  The only others were pixelpipe messages for thumbnails that had to be developed to display the correct thumbnails.  So, it appears that the problem has to do with libs/metadata_view.c in lua_update_metadata().

**Comment by ptilopteri** [comment]
@wpferguson 
> And I also get this one
> 
> `corrupted double-linked list`
> 
> I have my lighttable set up in file manager mode with 5 thumbnails across. If I scroll a 672 image collection approximately 9 rows at a time each second sooner or later I will get this and it says it core dumped, but I can't find it anywhere.

on linux usually
  /var/lib/systemd/coredump/

**Comment by wpferguson** [comment]
I tried a git bisect on the corrupted double-linked list . The commit I came up with is 926b45b1d6a417f1a2f8920878f9a2b517083a1f by @jenshannoschwalm.  

My method for reproducing the error is to open a collection of several hundred images.  Scroll to the bottom of the collection, then back to the top.  Start culling and go through 50-100 images.  Go back to file manager mode, the scroll through the collection some more.  Exit darktable and the error should appear in the console.  Sometimes it takes a couple of tries to make it happen.

**Comment by TurboGit** [comment]
@jenshannoschwalm : could this be because we are freeing data in bayer that is used later in xtrans:

  ```
g->demosaic_method_bayer = dt_bauhaus_combobox_from_params(self, "demosaicing_method");
  for(int i=0;i<6;i++) dt_bauhaus_combobox_remove_at(g->demosaic_method_bayer, 5);
  gtk_widget_set_tooltip_text(g->demosaic_method_bayer, _("demosaicing raw data method"));

  g->demosaic_method_xtrans = dt_bauhaus_combobox_from_params(self, "demosaicing_method");
  for(int i=0;i<5;i++) dt_bauhaus_combobox_remove_at(g->demosaic_method_xtrans, 0);
  gtk_widget_set_tooltip_text(g->demosaic_method_xtrans, _("demosaicing raw data method"));
```

The dt_bauhaus_combobox_remove_at() not only remove the link of the linked-list **but also free the data**.

**Comment by jenshannoschwalm** [comment]
Not sure, can't test because i'm at work :-)

It would be an older bug i guess, the xxx_remove_at frees the data as was done before. I am not sure from memory though, do we have the complete combobox while changing image from strip or alike or do we need sort of test? I tested yesterday (before @wpferguson reproducer) and couldn't trigger a crash.

Would look into this in detail tonght.

**Comment by jenshannoschwalm** [comment]
Just a short look while having a coffee break; I think the above code sections are correct as we create two comboboxes and strip off parts not needed for the specified and don't touch the other.

Not sure about dt_bauhaus_combobox_from_params and the update_gui and default reloads yet.

**Comment by wpferguson** [comment]
A little more information since I saw x-trans mentioned.  All my images are CR2 from a 7D and a 7D Mark II.

**Comment by jenshannoschwalm** [comment]
Aah, thanks. I was just going to ask. Still trying to crash...

**Comment by wpferguson** [comment]
@ptilopteri I tried running with a clean environment, i.e. moved the config directory to .old and darktable create a new one.  I haven't been able to recreate the crash since.

**Comment by ptilopteri** [comment]
I am considering closing.  I have not been able to repeat any of it.  Just worked a collection >500 raw with not a single hickup thru export, with lua enabled.

If no one comments to the contrary, will close in a couple of days.

tks everyone.

**Comment by MartinScharnke** [comment]
@ptilopteri please don't close. This is exactly what I've been having for some weeks. Check out [https://github.com/darktable-org/darktable/issues/5963](url). I've had multiple different crashes, but dynamic memory allocation or deallocation was central to all of them. I still get these crashes when I use my mouse wheel to quickly scroll through pics.

**Comment by MartinScharnke** [comment]
Also issue [https://github.com/darktable-org/darktable/issues/5997](url)
