### ISSUE TITLE
darktable does not start due to an exiv2 issue (development/master)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#6249]
**Describe the bug**
Not able to start darktable, it immediately stops with the following message:

> terminate called after throwing an instance of 'Exiv2::BasicError<char>'
>   what():  No namespace info available for XMP prefix `exifEX'
> Aborted

**To Reproduce**
1. Start darktable from a terminal

**Expected behavior**
darktable starts as expected.

**Additional context**
A bisect tells me this:

> d6338aaf2f06df8b0fe07d52bd792897510d42e2 is the first bad commit
> commit d6338aaf2f06df8b0fe07d52bd792897510d42e2
> Author: phweyland <philippe.weyland@laposte.net>
> Date:   Mon Sep 7 16:25:44 2020 -0300
> 
>     don't register lightroom and exifEX to exiv2 at init time if already known
> 
> :040000 040000 3e3587b7d0a634483b8e250186046f06f2bec8ae e3e40b16538a0b9fc9315ac9932c8cf8dbd961df M      src
> 

Makes sense,  this being a exif/exiv2 merged thingy.

Pinging @phweyland

**Comment by parafin** [comment]
What version of exiv2 do you have?

**Comment by parafin** [comment]
But I'm guessing that commit should catch exceptions instead of checking return code.

**Comment by jade-nl** [comment]
> What version of exiv2 do you have?

$ exiv2 --version
exiv2 0.25 001900 (64 bit build)
Copyright (C) 2004-2015 Andreas Huggel.


Forgot to add some info:

**Platform**
* darktable        : 3.3.0+592 g22d3179a6
* OpenCL installed : Yes (nvidia-opencl-common 440.100-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER7979 MiB
* Graphics driver  : nvidia (440.100)
* OS               : Linux (kernel 5.7.10-1)
* Distro           : Debian Buster (rel. 10.5)
* Xorg             : 7.7+19

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by pphotography** [comment]
I can confirm this on Xubuntu 18.04 using master 3.3.0~git592.22d3179a6

Command 'exiv2 --version' tells me that exiv2 was not found but could be installed with 'sudo apt install exiv2' (Used darktable before and it was running)

Installing exiv2 did not change anything. found a crash dump in /var/crash
[_usr_bin_darktable.1000.crash.txt](https://github.com/darktable-org/darktable/files/5196645/_usr_bin_darktable.1000.crash.txt)

**Comment by chrik5** [comment]
Same issue with Debian 10, latest dt master build and stock exiv2 v0.25.

**Comment by hgmarty** [comment]
Same result with this commit. Previous commit doesn't have this error.

@pphotography to compil in debian, it's the lib libexiv2-dev i have installed, not exiv2. I have done the same thing, install exiv2 to see the result, but like you.

**Comment by phweyland** [comment]
> But I'm guessing that commit should catch exceptions instead of checking return code.

Possible. I'll look at this.

**Comment by jade-nl** [comment]
The *exiv2 list of tags* are those different from the "normal" tags?

If they are: Never used them, not in stable and/or development. Don't even know what they are supposed to be for or why I need to care about them to be honest.

**Comment by phweyland** [comment]
> The exiv2 list of tags are those different from the "normal" tags?

The little + bottom right on your screenshot should list all the tags known by exiv2. 

> As you can see I'm not sure what it is you are asking.

no pb, it's just to try to understand the context of the failure.

**Comment by jade-nl** [comment]
> The little + bottom right on your screenshot should list all the tags known by exiv2.

Ah, I get you now. Yes There is a very long list with entries there. Here's part of it:

![Screenshot_2020-09-09_20-33-27](https://user-images.githubusercontent.com/56407344/92639310-23bb9400-f2cb-11ea-9010-eb36fb17affb.png)

This has not changed recently. I do recall looking at those and adding deleting them (just playing around).

**Comment by phweyland** [comment]
Thanks for trying. I was expecting you did not get the list. Strange.
Hoping the fix just provided works. Do you have any change to test it ?
Thanks

**Comment by jade-nl** [comment]
#6251 Works like a charm.

Thanks!

**Comment by phweyland** [comment]
Thanks @parafin !

**Comment by jade-nl** [comment]
Thanks parafin :-)
