### ISSUE TITLE
FR: bauhaus slider popup

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6255]
Where a bauhaus slider is located near the bottom of the screen, the right-click popup is not entirely visible. This is particularly noticeable in the overexposed/clipping indicator setting

![Screenshot_2020-09-09_23-31-58](https://user-images.githubusercontent.com/9555491/92661601-de13c100-f2f4-11ea-8924-e3542b13a8e7.png)

but also occurs in iop modules

![Screenshot_2020-09-09_23-32-39](https://user-images.githubusercontent.com/9555491/92661617-e966ec80-f2f4-11ea-9eb9-5464844f61dc.png)

It would be great if darktable could detect this situation and have the popup appear above the slider instead of below it.

**Comment by Nilvus** [comment]
Bauhaus are something that just need to be completely reworked (and CSS editable). This could be related to #2077

**Comment by Nilvus** [comment]
@elstoc, just as a reminder for another bauhaus issue you posted some months ago (and still there!).

**Comment by elstoc** [comment]
yeah - not one I know how to resolve though.

**Comment by dterrahe** [comment]
The code that was added in #11378 to deal with a similar issue for combos could be put outside the switch to also apply to sliders.
https://github.com/darktable-org/darktable/blob/c31d6a5b2f08ea4f3a6de209d774322c79e7c28d/src/bauhaus/bauhaus.c#L423-L444
But it looks like there are some subtle interactions (in adjusted and saved mouse location) that need to be taken care of and with the testing involved and dealing with feedback, this is not something I care enough about to take on.
