### ISSUE TITLE
Errors when building on MacOS Mojave

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/darktable#6258]
When following the build instructions for MacOSX:
https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt

an empty "build" directory is created inside the clone of the darktable repository, and from within that empty build directory, the following command is run:
`cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp -DBINARY_PACKAGE_BUILD=ON -DRAWSPEED_ENABLE_LTO=ON -DBUILD_CURVE_TOOLS=ON -DBUILD_NOISE_TOOLS=ON`

If we then start building wit hthe "make" command, the build aborts halfway through with the error message:
```
Scanning dependencies of target filter
[ 50%] Building C object src/libs/CMakeFiles/filter.dir/tools/filter.c.o
/Users/mmaguire/src/darktable-dev/src/libs/tools/filter.c:205:68: error: implicit conversion from enumeration type 'const dt_collection_filter_t'
      (aka 'const enum dt_collection_filter_t') to different enumeration type 'dt_collection_sort_t' (aka 'enum dt_collection_sort_t') [-Werror,-Wenum-conversion]
  gtk_combo_box_set_active(GTK_COMBO_BOX(widget),_filter_get_items(sort));
                                                 ~~~~~~~~~~~~~~~~~ ^~~~
/Users/mmaguire/src/darktable-dev/src/libs/tools/filter.c:418:72: error: implicit conversion from enumeration type 'const dt_collection_filter_t'
      (aka 'const enum dt_collection_filter_t') to different enumeration type 'dt_collection_sort_t' (aka 'enum dt_collection_sort_t') [-Werror,-Wenum-conversion]
    gtk_combo_box_set_active(GTK_COMBO_BOX(d->sort), _filter_get_items(sort));
                                                     ~~~~~~~~~~~~~~~~~ ^~~~
/Users/mmaguire/src/darktable-dev/src/libs/tools/filter.c:437:72: error: implicit conversion from enumeration type 'const dt_collection_filter_t'
      (aka 'const enum dt_collection_filter_t') to different enumeration type 'dt_collection_sort_t' (aka 'enum dt_collection_sort_t') [-Werror,-Wenum-conversion]
    gtk_combo_box_set_active(GTK_COMBO_BOX(d->sort), _filter_get_items(sort));
                                                     ~~~~~~~~~~~~~~~~~ ^~~~
3 errors generated.
make[2]: *** [src/libs/CMakeFiles/filter.dir/tools/filter.c.o] Error 1
make[1]: *** [src/libs/CMakeFiles/filter.dir/all] Error 2
make: *** [all] Error 2
M-C02X70PHJGH6:build mmaguire$
```

If I run again from inside that build directory the cmake command (doesn't matter if I run a "make clean" first or not):
`cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp -DBINARY_PACKAGE_BUILD=ON -DRAWSPEED_ENABLE_LTO=ON -DBUILD_CURVE_TOOLS=ON -DBUILD_NOISE_TOOLS=ON`

then this time the build completes normally, without those error messages being displayed. Not entirely sure what is going on there. Note that this is separate to the error mentioned in PR #6256 which occurs regardless whether the cmake command is run once or twice.

**Describe the bug**
darktable won't build successfully on macOS Mojave with XCode 10.3 unless the cmake makefile generation command is run twice from within the build directory.

**To Reproduce**
Follow the steps as per the official build instructions:
https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt

**Expected behavior**
Build should complete normally after running the cmake makefile generation command only once.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0+3115~g53fdc47b7-dirty (it's dirty because I have in place PR #6256)
 - OS: Mojave 10.14.6
 - XCode: 10.3
- MacPorts: 2.6.3 (built from clean /opt/local directory as per the given build instructions)

**Additional context**
I also get this same behaviour when building darktable 3.2.1 (in that case PR #6256 is not needed).
Note that I only started observing this issue after I deleted and reinstalled XCode and macports, prior to that I had no issues at all building darktable 3.2.1 on this machine. Not quite sure what is going on here...

[build_transcript.txt](https://github.com/darktable-org/darktable/files/5199212/build_transcript.txt)

**Comment by parafin** [comment]
Mystic stuff. Could you re-run the sequence, but use `make VERBOSE=1` build command this time?

On related note - you can upgrade XCode to 11.3.1: https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_12.x_(since_SwiftUI_framework)
That's what I'm running on same macOS version as you and don't encounter this problem.

**Comment by parafin** [comment]
But the compilation error itself is most definitely correct, even if it isn't triggered all the time. This commit introduced the faulty code: 92a7e6aeb2e66be90d2d54b596c4758bae4207a2, pinging @phweyland

**Comment by matt-maguire** [comment]
Here is the transcript with "make VERBOSE=1" (first round fails, second time round succeeds).

Concerning Xcode 11, I did try using that at one point in the past, but I think there was a bug in the linker that led me to fall back to 10.3. I can't remember the details, so once we've finished investigating with Xcode 10.3, I'll look at upgrading to Xcode 11 again.

[verbose_build.txt.gz](https://github.com/darktable-org/darktable/files/5199795/verbose_build.txt.gz)

**Comment by matt-maguire** [comment]
(oh, BTW, the verbose build was done with vanilla darktable 3.2.1, just to remove that other PR from confusing things)

**Comment by parafin** [comment]
A quick warning about Xcode 11.3.1 - macports rsync port fails to build with it, so I use binary package from macports (set `buildfromsource never` just for installing rsync).

**Comment by parafin** [comment]
Concerning the difference in two make runs, I see that flags passed to compiler are different between them, second one has added the following: `-w -flto=thin -fstrict-vtable-pointers -fopenmp-version=45 -D_DARWIN_C_SOURCE -Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wthread-safety -Wno-unknown-pragmas -Wno-error=varargs -Wno-error=address-of-packed-member`. `-D_DARWIN_C_SOURCE -Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wthread-safety -Wno-unknown-pragmas -Wno-error=varargs -Wno-error=address-of-packed-member` is just duplicates, which leaves us with `-w -flto=thin -fstrict-vtable-pointers -fopenmp-version=45`. I suspect these are CFLAGS from rawspeed, which enables LTO (and duplicates some CFLAGS while doing so too). So it's a bug in darktable or rawspeed cmake files. I'll look into it.

So there are 2 issues:

1. bug in cmake files - I will check this
2. bug in filter.c - @phweyland, please check your 92a7e6a commit

**Comment by parafin** [comment]
See darktable-org/rawspeed#240 for cmake issue, so let's keep this bug for the second (filter.c) part.

**Comment by phweyland** [comment]
>     2\. bug in filter.c - @phweyland, please check your [92a7e6a](https://github.com/darktable-org/darktable/commit/92a7e6aeb2e66be90d2d54b596c4758bae4207a2) commit

I'll look at this
