### ISSUE TITLE
Can't start DT anymore on Win10 after upgrade to 3.2.1

### ISSUE THREAD

**Issue by mimijojo** [darktable-org/darktable#6259]
[darktable_bt_5AURQ0.txt](https://github.com/darktable-org/darktable/files/5199647/darktable_bt_5AURQ0.txt)
[darktable_bt_UVBXQ0.txt](https://github.com/darktable-org/darktable/files/5199648/darktable_bt_UVBXQ0.txt)
[darktable_bt_IQPGQ0.txt](https://github.com/darktable-org/darktable/files/5199650/darktable_bt_IQPGQ0.txt)

When trying to start DT in Win10 after upgrade to 3.2.1, I get an unhandled exception error.  Retrying a few times doesn't help.

Please find attached the three darktable_bt files generate when trying to start.

Please find below the detailed system information of my laptopn

System Information report written at: 09/10/20 08:53:42
System Name: B32059
[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Pro	
Version	10.0.18363 Build 18363	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	B32059	
System Manufacturer	HP	
System Model	HP EliteBook 735 G5	
System Type	x64-based PC	
System SKU	2HB38AV	
Processor	AMD Ryzen 3 PRO 2300U w/ Radeon Vega Mobile Gfx, 2000 Mhz, 4 Core(s), 4 Logical Processor(s)	
BIOS Version/Date	HP Q81 Ver. 01.06.01, 26/02/2019	
SMBIOS Version	3.1	
Embedded Controller Version	8.75	
BIOS Mode	UEFI	
BaseBoard Manufacturer	HP	
BaseBoard Product	83DA	
BaseBoard Version	KBC Version 08.4B.00	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\WINDOWS	
System Directory	C:\WINDOWS\system32	
Boot Device	\Device\HarddiskVolume1	
Locale	Belgium	
Hardware Abstraction Layer	Version = "10.0.18362.752"	
User Name	APDOMAIN\jacobsm	
Time Zone	Romance Daylight Time	
Installed Physical Memory (RAM)	16,0 GB	
Total Physical Memory	14,9 GB	
Available Physical Memory	7,62 GB	
Total Virtual Memory	17,8 GB	
Available Virtual Memory	9,01 GB	
Page File Space	2,88 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	Off	
Virtualization-based security	Not enabled	
Device Encryption Support	Elevation Required to View	
Hyper-V - VM Monitor Mode Extensions	Yes	
Hyper-V - Second Level Address Translation Extensions	Yes	
Hyper-V - Virtualization Enabled in Firmware	Yes	
Hyper-V - Data Execution Protection	Yes

**Comment by parafin** [comment]
That's a problem with your OpenCL (GPU) drivers. Try upgrading them or running dt with --disable-opencl option. Not a darktable bug, so closing. Search for other similar bug reports to get more details.

**Comment by mimijojo** [comment]
Thanks for quick clarification !
