### ISSUE TITLE
Nikon D3400 White balance presets

### ISSUE THREAD

**Issue by mneilson** [darktable-org/darktable#6270]
Fully finetuned white balance presets for Nikon D3400
[darktable-whitebalance-20200911.tar.gz](https://github.com/darktable-org/darktable/files/5211380/darktable-whitebalance-20200911.tar.gz)

**Comment by matt-maguire** [comment]
So there are a couple of problems:
- for Daylight Flourescent, we have 2 images at finetune value of "1", but none for 3 or 4.
- for Sodium Vapour Fluorescent, we have doubled up images with finetune 5 & 6, but have no images for fine tune value 10, 11, or 12
- Similarly for Flash, we have doubled up images with finetune 5 & 6, but have no images for fine tune value 10, 11, or 12

Do you think you could supply the extract finformation for those missing images? While it possible we could interpolate the missing Daylight Fluorescent values, it's better to have actual finetune values from the camera. The other two would require extrapolation, so we would really want to have those missing finetune values (or at a minimum, the values for finetune 12).

**Comment by mneilson** [comment]
Sorry about that! I redid the series (a little more carefully) for those three presets. Hopefully this will fix the issue.
[new_series.tar.gz](https://github.com/darktable-org/darktable/files/5212020/new_series.tar.gz)

**Comment by matt-maguire** [comment]
Very nice job. It can get confusing when juggling so many files, easy to make mistakes, but it all looks good now. I've opened a PR to get this incorporated into the next release. Thanks for having carried out that tedious work!
