### ISSUE TITLE
Error on Startup - Unhandled Exception Error

### ISSUE THREAD

**Issue by kchadek** [darktable-org/darktable#6273]
**Describe the bug**

Windows 10 using 3.2.1 - Upon startup, error message pops up multiple time. Clicking ok shuts down program. Tried uninstalling and reinstalling and same error. Backtrace file attached. 

**Screenshots**

![Capture](https://user-images.githubusercontent.com/52056711/92985224-3faf6900-f476-11ea-984e-e83beeb6d3e8.JPG)
[darktable_bt_9H5LQ0.txt](https://github.com/darktable-org/darktable/files/5212069/darktable_bt_9H5LQ0.txt)

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  Windows 10
 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment]
Can you move darktable data folder and start fresh?

**Comment by kchadek** [comment]
Worked - deleted data folder and reinstalled. Thank you!

**Comment by johnny-bit** [comment]
Seems like you had local problem😅 consider closing the issue🙏

sob., 12 wrz 2020, 20:12 użytkownik kchadek <notifications@github.com>
napisał:
