### ISSUE TITLE
Filmstrip in darkroom won't show all thumbnails coming from lighttable/filemanager when fully zoomed in.

### ISSUE THREAD

**Issue by andabata** [darktable-org/darktable#6280]
When switching from lighttable/filemanager when fully zoomed in, it doesn't show all thumbnails in the filmstrip in darkroom. They do show at any other zoomlevel. They do show when using culling or zoomable at any zoomlevel.

darktable version: 3.3.0+611~ga1b77392c-dirty
platform: debian sid

It worked fine in: darktable 3.3.0+262~g64b00d9b5-dirty

http://shell.kees.nl/dt/filmstripbug.mkv

**Comment by esq4** [comment]
3.3.0+774~ge7e73d31d work fine

**Comment by andabata** [comment]
Humm. intresting, just did a pull and i'm still on 
darktable 3.3.0+646~g5a9679d71-dirty (still got the same issues)
@esq4 Are you a using a different brance ?

**Comment by johnny-bit** [comment]
I confirm the bug on current master. If the zoom level is set to 1, the filmstrip when going to darkroom is filled by empty images except for the actual image and it's "next"

**Comment by AxelG-DE** [comment]
I have the same issue, even my zoom-level was set to 3

**Comment by TurboGit** [comment]
Probably @AlicVB can help here ?

**Comment by AlicVB** [comment]
I'll try to have a look tomorrow...
