### ISSUE TITLE
WB Presets for Sony ILCE-7RM4 with finetuning

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/darktable#6283]
Attached is the WB preset info for Sony ILCE-7RM4 that covers the full range of finetune settings.
[darktable-whitebalance-20200913.tar.gz](https://github.com/darktable-org/darktable/files/5213420/darktable-whitebalance-20200913.tar.gz)

**Comment by matt-maguire** [comment]
The original file attached to this ticket was generated with a Sony 24-105mm f4 G-lens attached to the camera -- this seems to introduce a lens-specific "correction factor" into the whitebalance coefficients. Therefore, I regenerated the sample images using no lens at all on the camera.
[darktable-whitebalance-20200913-nolens.tar.gz](https://github.com/darktable-org/darktable/files/5213798/darktable-whitebalance-20200913-nolens.tar.gz)

**Comment by ptilopteri** [comment]
If the camera out wb changes with each lense, will not any wb preset be specific *only*
for that lense and generating w/o a lense would not be good for *any* lense?

**Comment by parafin** [comment]
It doesn't change with each lens obviously (and as reported by @matt-maguire), but for some of them, for which there are specific correction in camera firmware. So there are generic presets (no lens ensures that generic are chosen) and specific for lenses (which we do not care about).

**Comment by matt-maguire** [comment]
I collected some more data points for the different lenses I have, looking at the Daylight (unadjusted) and the 6000K presets, and summarised in a spreadsheet:
https://docs.google.com/spreadsheets/d/1xL084gHYDlhh4srEDauIzxbIrlJ8tC25qK6kqrUA8AM/edit?usp=sharing

In summary:
- having no lens and having the 35mm f/1.8 prime gives identical results
- the 16-35mm f/2.8 GM and the 70-200 f/2.8 GM with x1.4 TC give identical results to each other
- The 16-35mm f/2.8 GM and the 24-105mm f/4 have identical R coefficients, but the B coefficients vary slghtly
- The other lenses (85mm f/1.8, 100-400 f/4.5-5.6 GM, 70-200 f/2.8 GM with no TC) all have their own unique coefficients.

I don't have any other Sony body to compare with, but I would suppose most of the alpha series would behave similarly. To treat this properly, we'd probably need a database similar to lensfun, which deals with WB presets for camera body and lens combos. But in practice, it seems the differences between the lenses are of a similar magnitude to adjusting the finetune slider by one notch or less, so we are not talking about a huge effect here.
