### ISSUE TITLE
Windows Alt+Code character entry doesn't work

### ISSUE THREAD

**Issue by strandloper** [darktable-org/darktable#6288]
**Describe the bug**
While entering tags I attempted to enter an e with diaresis (ë) character using the standard Windows mechanism of typing Alt+0235 on the numpad. No character was entered and I had to resort to Copy and Paste from the Character Map app. After trying several other Alt+Code combinations it is apparent that this is not supported. As this has been a standard entry mechanism on Windows for as long as I can remember I would consider it a bug.

**To Reproduce**
1. Go to the lighttable tagging module
2. Click on the enter tag name field and type some characters
3. Type Alt+0235 (using the numeric keypad) and expect the 'ë' character to appear
4. Observe that no character is entered
5. Go to the lighttable metadata editor module
6. Click on any metadata property field
7. Attempt Alt+Code character entry and observe that it does not work.

**Expected behavior**
On Windows a standard keyboard entry mode involves holding down the Alt key while entering a four digit character code, resulting in the character being entered as if typed. This is expected to work anywhere on a Windows computer.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10 Version 2004 (OS Build 19041.508)
 - OpenCL activated
 - Intel HD Graphics 4600, driver version 20.19.15.4531

**Additional context**
 - Darktable installed with Windows installer from darktable.org

**Comment by matt-maguire** [comment]
darktable is based on the GTK library. The way you type unicode character in a GTK application is by either:
- holding "Ctrl-u", typing the unicode character code in hex, then release "Ctrl-u"
- type "Ctrl-u", release, type the unicode character in hex, and then hit "space" or "enter"

For your e-umlaut character, a decimal value of "235" corresponds to a hex code of "eb", so "Ctrl-u e b <space>" will enter a "ë".

**Comment by strandloper** [comment]
Thanks for that. So the feature exists, just in a slightly different way than standard on Windows, which I think is acceptable for a cross platform application.
