### ISSUE TITLE
documentation: [Windows build instructions] Reference version to download for SAXON

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6293]
Update this to reference which version should be downloaded. Currently SAXON is at version 10.

https://github.com/darktable-org/darktable/blob/1f9ec623abd4283df7bd6197486e89ddd6fb4e08/packaging/windows/BUILD.txt#L55

Later below saxon9he.jar is referenced. So, putting version 9 reference earlier would help people building on windows.
https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt#L85

**Comment by johnny-bit** [comment]
Usermanual in root got nuked, no longer needed, replaced with dtdocs and separate flow :)
