### ISSUE TITLE
Lost title when removing image and reimporting from sidecar

### ISSUE THREAD

**Issue by marco44** [darktable-org/darktable#6295]
I had to remove and reimport a directory, and lost all titles on the files. I don't know exactly what metadata is lost. Title is gone. Tags seem to be kept, number of stars too

To reproduce:
Remove an image from the collection
Import it again
Title is gone (from the XMP too)

This occurs on DT 3.2.1 archlinux. 

I didn't try downgrading DT yet to see when this appeared.

**Comment by ptilopteri** [comment]
I can confirm the title disappearance on git master fb177d9

**Comment by TurboGit** [comment]
@phweyland : Probably for you!

**Comment by TurboGit** [comment]
@marco44 @ptilopteri : can you double check that you have the title option ticked into the import dialog ? (bottom of dialog into the import options section).

**Comment by ptilopteri** [comment]
fwiw: The title is written to the xmp file.  But when subsequently (re)imported the xmp file is rewritten w/o the Title.

**Comment by ptilopteri** [comment]
@TurboGit I did not, but I did not have "apply metadata on import" selected so no alteration of xmp file aside time-stamp should happen.

**Comment by marco44** [comment]
Same here. Didn't tick anything

**Comment by TurboGit** [comment]
I cannot reproduce on my side when "apply metadata on import" is not selected but title is selected and this is the way it works.

"apply metadata on import" : means that you can apply some specific metadata as entered into the entry just below.

But to import them from XMP you want the "to be imported" to be ticked.

So to me there is no bug, just a misunderstanding.

**Comment by TurboGit** [comment]
BTW, see tooltip over the "to be imported".

This may be clarified in the documentation, if you have any text proposal sent it over and I'll integrate it.

**Comment by ptilopteri** [comment]
So if I apply a Title to a file in an active collection and it is saved in the xmp file and I remove the file from the collection.  The next time I open that collection, reimport, I can expect all the saved titles to be removed UNLESS I have apply metadata on import and the title option selected.

That is contrary to the other metadata, my creator, author and rights are no overwritten.  

Please reconsider.

**Comment by TurboGit** [comment]
@ptilopteri : That's not what I wrote and on my sides all metadata are properly handled. There is nothing specific to title.

**Comment by ptilopteri** [comment]
@TurboGit 
If I add a Title to an image while in darktable,not on import, I cannot expect it to endure?

**Comment by marco44** [comment]
Ok I tested as you suggested, @TurboGit , and it works alright. It's still a giant footgun, I think. I've always thought that importing a directory where there's a bunch of XMP would keep all the data in them by default, not destroy them. And I'm probably not the only one.

**Comment by phweyland** [comment]
We've already had some discussion about this. It seems that remains a bit confusing. :(

The first intention is to be able NOT to import what you don't want to have in the database, in particular, repetitive information like author, and so one, which are repeated endlessly in the database even if always the same. For those, metadata implementation is not optimum (while it's perfect for title, description or notes). I prefer to use tags (and category) to generate properly this kind of information (author, rights, ... see doc). 

These flags ("to be imported") are set by default. If the user doesn't reset them, all xmp metadata are imported in database as usual.

Any suggestion to make it less confusing is welcome.

**Comment by ptilopteri** [comment]
I suggest that data written to the xmp file remain there until deliberately by editing in dt or otherwise removed.  This is really prevalent when library is specified as :memory: and "write sidecars for each image" is configured on.

**Comment by marco44** [comment]
Weird, everything was unchecked here, and I don't think I ever unchecked it, but my configuration is like 5 years old. But you're right, I created a new config, it's all checked. Maybe just a big fat warning in the UI when anything is going to overwrite what's in the sidecar files ?
Like a sentence: "beware, if you already have xmp files, their contents may be overwritten by this setup", if anything is unchecked in the list ?

**Comment by phweyland** [comment]
Thanks for your comments.

> I suggest that data written to the xmp file remain there until deliberately by editing in dt or otherwise removed.

That's perfectly valid when the user edits metadata only in dt. When the user imports (or refresh xmp) from other apps that may be another story.

> This is really prevalent when library is specified as :memory: and "write sidecars for each image" is configured on.

The case "write sidecars for each image" is checked deserves to think about it.

Or an explicit configuration point like "Allow to configure metadata to be imported from xmp". If not checked everything is imported. When set unchecked the flags are "to be imported" are set checked letting the user change the option if necessary.


> Weird, everything was unchecked here, and I don't think I ever unchecked it

Weird indeed, I'm sorry. Pascal had also met this case. At this time the default flags were initialized in the gui, letting a breach for those who use darktable cli. Has been fixed then.




> I could recover everything,

I'm glad for that.



> Maybe just a big fat warning in the UI when anything is going to overwrite what's in the sidecar files ?

In case at least one metadata is unchecked we could have this message:
"you have some metadata with 'to be imported' flag unchecked. If the configuration 'write sidecars for each image' is checked these metadata will be lost."

**Comment by TurboGit** [comment]
@phweyland : I understand that current behavior has been made to sync xmp for people using two computers to edit and possible editing XMP with a third party program.

That being said, while importing new pictures from DT (not doing synch) I think we want the XMP content to always be taken as-is and fully imported. There is no entry in the DB for the pictures so the XMP should be fully respected.

How does that sound ?

**Comment by marco44** [comment]
I think both (the warning and the default of never discarding the XMP content) are good ideas, and not mutually exclusive :)

**Comment by phweyland** [comment]
> while importing new pictures from DT (not doing synch) I think we want the XMP content to always be taken as-is and fully imported.

When one imports images from camera there are only exif metadata. If there is xmp metadata they have been generated by some apps, including dt.

By default dt imports exif metadata (artist -> author, rights) and xmp metadata.
That's perfectly fine. But I think some people may want to filter data which have not been created by dt.

In that sense I agree with @ptilopteri proposal to always import everything when "write sidecars for each image" is checked. In that case the "to be imported" options would be hidden. Otherwise the user keeps the possibility to filter the external info he does want. 

Would that make sense ?

**Comment by TurboGit** [comment]
> Would that make sense ?

Sounds fine yes!

Just to be sure if "write sidecars for each image"  is set, when importing we do:
1. import exif data from RAW file
2. import (and possibly overwrite what has been imported in step 1) any metadata found in an XMP

Is that correct?

**Comment by phweyland** [comment]
> Just to be sure if "write sidecars for each image" is set, when importing we do:
> 

>     2. import (and possibly overwrite what has been imported in step 1) any metadata found in an XMP
> 
> 
> Is that correct?

Perfectly!

If not set, by default the behavior remains the same, except the user has the possibility to filter some information.

**Comment by TurboGit** [comment]
Ok, so this looks like a nice fix to have in 3.4 as this lost of metadata can be terrible.

**Comment by phweyland** [comment]
I'll do it.
