### ISSUE TITLE
[FR] Move or rotate images (canvas).

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#6307]
**Feature request.**
When I work with paths creating masks, sometimes I've to draw near borders and corners and it's not straight forward to place and move vectors.

**Solution.**
It's possible to have the option of move or rotate the image (canvas) thru the central zone to work better with paths at the borders and corners.

**Alternatives.**
With the mouse move the image without constraint to the borders.

**Additional context.**
![01](https://user-images.githubusercontent.com/67672868/93288576-224a0a00-f7aa-11ea-8273-fee3cc5a7674.png)
![02](https://user-images.githubusercontent.com/67672868/93288582-270ebe00-f7aa-11ea-8208-9fff161a6ae3.png)

**Comment by johnny-bit** [comment]
This issue is interesting and imo worth looking into. Suggested method of moving the canvas is interesting, but I see very tillte use in rotating the canvas.

I'm suggesting - similarly to allowing zoom to continue above 100% with <kbd>ctrl</kbd>+`scroll` how about - once you reach end of canvas - you can drag with <kbd>ctrl</kbd>+`drag` to grow border and therefore move canvas?

There's an interest in this functionality as evidenced by another issue - https://github.com/darktable-org/darktable/issues/5195

**Comment by difrkaguilar** [comment]
I think this would be a nice solution for a lot of people. The canvas should be an area without  constraint.

The option of use ctrl+drag to grow border and ctrl+shift+drag to rotate would be great.

**Comment by difrkaguilar** [comment]
Again. Very difficult to clone part of a photography with clone mask in retouch module. Sometimes is interesting after correct perspective make a clone of some elements of the image. But every time and object is in the border if the image is really difficult to clone, the handlers are out of reach
image at 100% the handlers are out an can't be manipulated.

![Screenshot_20210325_213206](https://user-images.githubusercontent.com/67672868/112566545-9565b600-8db5-11eb-848a-afa7a350ae53.jpeg)

image at 200% the same issue.

![Screenshot_20210325_213415](https://user-images.githubusercontent.com/67672868/112566624-ba5a2900-8db5-11eb-991a-0967b13db16d.jpeg)

the only way to see and work with handlers is at 63% or less

![Screenshot_20210325_213257](https://user-images.githubusercontent.com/67672868/112566772-fb523d80-8db5-11eb-9886-879a8db6b8b5.jpeg)

The ideal it would be at 100% drag the image to the center of the canvas to work with the handlers fine.

![mask](https://user-images.githubusercontent.com/67672868/112566904-348aad80-8db6-11eb-960e-170e02354a2b.jpg)

**Comment by difrkaguilar** [comment]
Is this feature request is my particular case or someone experiment the same issue working with images at the borders or corners?.

Is this feature request in some developers planning?

**Comment by johnny-bit** [comment]
Your FR is broad enough that it's interesting from development perspective and would/could alleviaete multiple issues regarding off-canvas controls.

It might be on some dev todo list, but we'll never know untill ther's either straight "i'll try it" talk or actual PR started, so IMO this needs to be kept open untill then.

**Comment by difrkaguilar** [comment]
I just saw RT have the desire behaviour, they split the canvas in four parts and the images can be moved to every side and up/down without problem. I know RT don't have the same code as darktable, but as @johnny-bit said in #9980 

> eg #6307 (implementing that would be awesome btw!)

Maybe in a near future ;-)

This FR is mainly focused to use with the retouch module.

**sample images**
![canvas01](https://user-images.githubusercontent.com/67672868/151286886-e45d60b7-c6f1-4795-a921-95d9ead4c62a.png)
![canvas02](https://user-images.githubusercontent.com/67672868/151286895-1c87e05f-3fa7-4ec2-95e0-97bb89ac820f.png)
![canvas03](https://user-images.githubusercontent.com/67672868/151286905-312b2a61-621f-40ba-a553-71b2fde1d42d.png)
![canvas04](https://user-images.githubusercontent.com/67672868/151286913-fb4731f2-428d-45a5-adf2-a0b64202795b.png)
![canvas05](https://user-images.githubusercontent.com/67672868/151286922-bc7e0b0f-f9bf-4b1c-a53f-d49eff12558f.png)
![canvas06](https://user-images.githubusercontent.com/67672868/151286929-c6aa25e2-a7f8-4639-9ad4-1fb408dda1d6.png)
![canvas07](https://user-images.githubusercontent.com/67672868/151286940-f3e100e3-c282-498f-ba31-2ae54d8cd9e4.png)
![canvas08](https://user-images.githubusercontent.com/67672868/151286953-329bba21-84b8-4de7-b495-c8233fd0d114.png)

**Comment by difrkaguilar** [comment]
Ping. :-)

**Comment by difrkaguilar** [comment]
4.6 maybe...

**Comment by ralfbrown** [comment]
Master now has a workaround using the new "enlarge canvas" module (#15465).  Enlarge with black on the appropriate side(s), do your retouching, then disable the enlarge module.  The fill color should be black to match behavior of retouch source regions extending outside the image.

**Comment by difrkaguilar** [comment]
> Enlarge with black on the appropriate side(s), do your retouching, then disable the enlarge module

Thanks a lot, this can be the solution to this issue. 👌👍
