### ISSUE TITLE
Lua API: changing image rating does not refresh rating in UI

### ISSUE THREAD

**Issue by arru** [darktable-org/darktable#6310]
**Describe the bug**

Writing to the `rating` attribute of an image object (`dt_lua_image_t`) does not update the UI accordingly. It does take effect, but only after some other UI action causes a refresh. 

This problem manifests itself in rating-filtered lighttable as well as thumbnail overlays, no matter whether the change is a new star rating or rejection.

**To Reproduce**
1. Run a script doing the following, while in the lighttable
2. Retrieve a dt_lua_image_t object ('image')
3. `image.rating = 3`

**Expected behavior**

The usual indicators (including rating-filtered lighttable as well as thumbnail overlays) should change accordingly, image might disappear if no longer covered by the rating condition, 3 stars displayed, etc. 

**Observed behavior**
No visible change. Star rating/rejection icon updated only after switching to darkroom and back.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Mac OSX 10.15.5
 - OpenCL enabled
 - AMD Radeon R9 M295X 4 GB

**Additional context**
Running official Mac OSX distribution of DarkTable.

**Comment by wpferguson** [comment]
Fixed in git master by #5856

**Comment by wpferguson** [comment]
@TurboGit this can be closed.  It's already fixed by #5856

**Comment by TurboGit** [comment]
Ok,, closing.
