### ISSUE TITLE
Tags not applying to all selected images in darkroom

### ISSUE THREAD

**Issue by KerryL** [darktable-org/darktable#6313]
I found this possibly related previous issue:  [https://github.com/darktable-org/darktable/issues/4576](https://github.com/darktable-org/darktable/issues/4576)

I'm using Darktable 3.2.1 on Ubuntu 18.04.

If I select images in the filmstrip, then apply a tag using Ctrl+T, tags are applied to all selected images or only the active image, depending on whether or not my mouse is hovering over a selected image on the filmstrip (described in the issue linked above as expected behavior - almost; more below).  If I'm using other methods to apply the tag (double-clicking on the tag in the dictionary, via right-click menu or by clicking the "Attach" button), the tag is only applied to the active image.

Note that the active image may or may not be in the set of selected images.

I find it unintuitive that tag behavior is different depending on where my mouse is.  This functionality is not described in the documentation, as far as I can tell (see:  [https://darktable.gitlab.io/doc/en/tagging.html](https://darktable.gitlab.io/doc/en/tagging.html)).  The documentation suggests that the tags should always be applied to all selected images (and never to the active image if it isn't selected).

The expected behavior as described in the issue above is:
```
* mouse outside filmstrip : tag applied to active image
* mouse inside filmstrip : tag applied to image hovered
```

The behavior I observe is:
```
* mouse outside filmstrip : tag applied to active image
* mouse inside filmstrip and over one of the selected images : tag applied to image hovered
* mouse inside filmstrip but not over one of the selected images : tag applied to active image
```

Based on intuition, the behavior I expect (and would prefer to see) is that tags are always applied to the selected images.

Otherwise, the behavior should at least be documented.

**Comment by ralfbrown** [comment]
I believe that this is working as designed, but see #6025 for discussion of whether it *should* work that way.

**Comment by johnny-bit** [comment]
Yeah, let's trim the issues down and continue discussion in #6025. I hope, as does Nilvus, that we'll be able to reach conclusion by the time for dt 3.8 ;)
