### ISSUE TITLE
Darktable lens correction module does not recognize lenses mounted with Nikon FTZ adapter on Nikon Z6

### ISSUE THREAD

**Issue by Aceler** [darktable-org/darktable#6317]
I have a Nikon 28-300 3.5-5.6 and Nikon 50/1.4G lenses. Both of them works perfectly with Darktable when mounted on Nikon D600. But lens correction module does not recognize any of these lenses if they are mounted on Nikon Z6 using Nikon FTZ adapter. Nikon 24-70/4S, mounted directly on mount Z, works as expected.

Exiv2 tool recognizes lens tags in NEF file.

NEF file can be found here:
https://yadi.sk/i/iFFZyBPCVfqcaQ

**Comment by junkyardsparkle** [comment]
Looks like exiv2 hasn't figured that set-up out yet. In the meantime, you can map the lens ID for those lenses locally as described here: http://web.archive.org/web/20190127023419/https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/

**Comment by Aceler** [comment]
Yes, that didn't work.

**Comment by hassec** [comment]
I raised this problem with exiv2 here: https://github.com/Exiv2/exiv2/issues/1433

**Comment by hassec** [comment]
@Aceler This is now merged into the exiv2 `0.27-maintenance` branch.      
Let me know if you still have any problems ;)

**Comment by johnny-bit** [comment]
Technically this bug can be closed. The data will be available for darktable's consumption, granted the user has newest exiv2 with either code backported to 0.27.3 release or after 0.27.4 release.

I'm closing this as upstream + fixed.

Thanks @hassec for working on it! exiv2 needs more help like yours :) (and darktable needs more testers and windows/osx devs) :)
