### ISSUE TITLE
"save theme tweaks" button usability issue

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6318]
in the preferences - general, the save theme tweaks button leaves the user disappointed, because nothing happens in the ui when the button is pressed, the button changes only when hovered.

Some color change must be set when the button is pressed.

**Comment by Nilvus** [comment]
That has changed (and will be for 3.4). It's now save and apply and that check automatically the modify theme checkbox just above css editor.

**Comment by johnny-bit** [comment]
Fixed in master as @Nilvus mentioned. You'll love release 3.4 :)
