### ISSUE TITLE
[TRIVIAL] Change ui/cairo_filter default to "good", so that lighttable thumbnails look reasonable

### ISSUE THREAD

**Issue by grudgingly** [darktable-org/darktable#6325]
New git build of Darktable yesterday, first time I've updated for a while, and I couldn't get over how terrible the lighttable thumbnails looked - at 5-to-a-row and up they were unusable, even at full-screen preview size they looked bad.

Went through and checked all the options in the GUI, checked the low_quality_thumbnails setting in darktablerc, compared the thumbnails to the various quality settings in Geeqie, figured out they were being scaled with nearest-neighbour, started grepping the source code and eventually found the ui/cairo_filter setting.

ui/cairo_filter defaults to "fast" and the only way to change it is to edit darktablerc.

**Describe the solution you'd like**

Set the default to "good". This would produce the same behaviour as previous Darktable versions.

**Comment by jenshannoschwalm** [comment]
Just letting it be "good" as default might not be so good. Especially on slower machines there is a large performance difference. Maybe either have this configurable in the config menu or make it automatically set depending on performance.

**Comment by parafin** [comment]
I've re-opened #5947, let's continue there.
