### ISSUE TITLE
Color Mapping Module broken...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#6328]
Running updated Windows 10. Responding to a query on facebook it was noted that after acquiring the source image and then the target image in the module that activating either of the sliders simple clears the color mapping information. This is noted for me on the current 3.2.1....will check later to see if this is still an issue on dev build but likely.....

**Comment by johnny-bit** [comment]
Fixed in #6387 - if you can please test.

**Comment by todd-prior** [comment]
Will do..thx..may not be until a bit later





Get Outlook for Android
