### ISSUE TITLE
Rejected image still selected although not visible

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#6333]
**Describe the bug**
I'm in lighttable and I am viewing 'all except rejected'. 
So when rejecting an image (A) it disappears because it gets filtered out, and that's exactly what I want to achieve.

But:
Although I am now seeing the next image (B), the rejected image (A) is still selected!
So if I now want to rate this next image (B) with for example 1 star, the rating is applied to the not-visible rejected image A.

**To Reproduce**
1. Go to lighttable
2. Choose 'all except rejected' in the view drop down
3. Use 'file manager' with only '1' image
4. So only the first image (A) is shown
4. Press 'r' on the keyboard to reject the currently visible image (A)
5. So image A is filtered out and image B is visible now
6. Press '1' on the keyboard to apply a one-star-rating to the currently visible image B
7. The star rating gets applied to image A although still only image B is visible

**Expected behavior**
If the currently selected image gets filtered out in the lighttable (e.g. by rejecting it) the next image (which is shown now instead) should get selected.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Ubuntu Linux 20.04.1 LTS
 - OpenCL: no
 - Graphic card driver: xserver-xorg-video-nouveau

**Comment by AlicVB** [comment]
yes, that bug is already fixed in git master.
