### ISSUE TITLE
Lighttable remains empty

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6341]
**Describe the bug**
After building and launching, the lighttable showed up with empty thumbnails, and never rebuilt / refreshed them.
If I start with an empty library + pristine config, and import a folder, the lighttable remains empty. If I directly import an image, I can edit it; switching back to the lighttable will show an empty thumbnail for that image.
Enabling -d all at the command line keeps logging lines like:
```
99.245167 [lighttable] expose took 0.0000 sec
99.245496 [add_job] 2 | 99.245508 load image 1 mip 1 | queue: 1 | priority: 099.245524 
99.245541 [add_job] found job already in queue: 99.245553 load image 1 mip 1 | queue: 1 | priority: 499.245566 
99.285647 [lighttable] expose took 0.0000 sec
99.285953 [add_job] 2 | 99.285967 load image 1 mip 1 | queue: 1 | priority: 099.285984 
99.286002 [add_job] found job already in queue: 99.286013 load image 1 mip 1 | queue: 1 | priority: 499.286025 
99.301980 [lighttable] expose took 0.0000 sec
99.302260 [add_job] 2 | 99.302272 load image 1 mip 1 | queue: 1 | priority: 099.302290 
99.302307 [add_job] found job already in queue: 99.302318 load image 1 mip 1 | queue: 1 | priority: 499.302331 
99.319273 [lighttable] expose took 0.0000 sec
99.319620 [add_job] 2 | 99.319633 load image 1 mip 1 | queue: 1 | priority: 099.319691 
99.319745 [add_job] found job already in queue: 99.319802 load image 1 mip 1 | queue: 1 | priority: 499.319852 
99.352068 [lighttable] expose took 0.0000 sec
99.352432 [add_job] 2 | 99.352446 load image 1 mip 1 | queue: 1 | priority: 099.352457 
99.352466 [add_job] found job already in queue: 99.352474 load image 1 mip 1 | queue: 1 | priority: 499.352483 
99.398324 [run_job-] 03 309986179.228324 99.398383 update connected cameras | queue: 4 | priority: 099.398398 
99.424259 [db maintenance] checking for maintenance, due to rule: 'on close'.
```
until I close darktable.

**To Reproduce**
1. launch b2995917 (b6bbd0d56 works fine)
2. if you already have images in your DB, the lighttable will remain empty (nothing more to do)
3. otherwise, import a folder or an image
4. if you imported an image, return to the lighttable

**Expected behavior**
Lighttable shows thumbnails

**Screenshots**
![image](https://user-images.githubusercontent.com/3177739/93708298-4ce2ec80-fb35-11ea-9885-8307897ea9d2.png)

**Platform (please complete the following information):**
Version: from git, b2995917
OS: Ubuntu 20.04, 64-bit
OpenCL: N/A (same behaviour with ON and OFF); Nvidia 1060, 440.100-0ubuntu0.20.04.1

**Comment by TouchPadDancer** [comment]
I'm seeing the same. Upgraded to 3.2.1 and all previous imported files and newly imported files do not show in lighttable view. I can import a single RAW (.ARW Sony 7II) file and it shows in develop, but is gone when I go back to lighttable.

I'm on Win 10 Pro 1909.

**Comment by johnny-bit** [comment]
@kofa73 - since you know which commit worked and which didn't work for you you could help via bisection the issue: https://github.com/darktable-org/darktable/wiki#finding-bug-causes

However I tried to replicate the issue to no avail. Current master (3.3.0+792~g435335440) works fine for me using both virgin config+lib and my ongoing dev config + lib.

**Comment by kofa73** [comment]
04ceab is the culprit; 55864b is fine. Quite weird, I know.

**Comment by johnny-bit** [comment]
0.o How on earth could 04ceab be the culprit if it doesn't even touch lighttable code 0.o

But indeed dual-code + 4GB ram seems like ancient machine that probably doesn't like loads of threads :/ However the mentioned commits are not in 3.2.1 so @TouchPadDancer has probably different issue (or similar, just manifests differently).

It MIGHT be a threading/ram problem thoug so Hanno's code might not be the culprit here, but instead allows problem to surface.

**Comment by kofa73** [comment]
I just did a bisect, and then confirmed that that's the 1st version that does not work (on my machine).
```
$ grep -i mem darktablerc 
cache_memory=536870912
host_memory_limit=500
opencl_memory_headroom=400
opencl_memory_requirement=768
opencl_use_pinned_memory=false
plugins/lighttable/preview/max_in_memory_images=4
$ grep -i thread darktablerc 
worker_threads=1
$ grep -i perf darktablerc 
performance_configuration_version_completed=1
```

**Comment by jenshannoschwalm** [comment]
Can't test right now, just an idea. The gphoto code uses a background thread so if only one thread is allowed the updating thumbs might be blocked.

**Comment by kofa73** [comment]
`worker_threads=2` allows the lighttable to be shown; however, darktable constantly consumes 10-20% CPU (it only has 2 photos in the DB, and is sitting in the background, showing the lighttable). It keeps logging:
```
16.741880 [camera_control] 0 cameras connected
17.269481 [camera_control] loaded 49 port drivers.
17.371136 [camera_control] 0 cameras connected
17.890457 [camera_control] loaded 49 port drivers.
17.981588 [camera_control] 0 cameras connected
18.501493 [camera_control] loaded 49 port drivers.
18.588415 [camera_control] 0 cameras connected
```

**Comment by TurboGit** [comment]
Ok, so this seems it confirms @jenshannoschwalm idea ! The fact that dt keep looking for a camera is ok, we may want to make this test less often and maybe lower the thread priority if it makes sense.

**Comment by kofa73** [comment]
I never use darktable to import from a camera. Is it possible (even at compile time) to disable this feature?
Also, it seems like that thread does way more than it should (e.g. does it really have to load the 'port drivers' every time, or would it possible to load them once, and re-use them?

**Comment by jenshannoschwalm** [comment]
OK. Will find a better solution...

**Comment by TurboGit** [comment]
Ok first fix is to not allow worker_thread below 2 anyway. I'll fix that.

**Comment by johnny-bit** [comment]
> Is it possible (even at compile time) to disable this feature?

You can compile darktable with gphoto2 disabled. that way you are losing tethering + import from camera. But it should be fine to do so.

> OK. Will find a better solution...

Well, the current one is IMO great and works perfectly well. As Pascal said, it might be a good idea to tweak it's timeout (current is 0.5s I think, maybe 5s would be "good enough"?) and lowering priority.

Another idea I could think of would be to use dbus connection and wait for camera notification, but that might be an overkill.
