### ISSUE TITLE
[ChannelMixer] Dev 3.3.0+xxx , converting to B/q using presets leaves color in the image

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6342]
See the image, it has blue all over the place top left. Had to enable monochrome to get rid of the color left being by channel mixer.
![image](https://user-images.githubusercontent.com/1119439/93708493-4879fc00-fb54-11ea-8ff9-d0c58a28417b.png)

Win 10.
this is darktable 3.3.0+772~g460863d3f

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by MStraeten** [comment]
Please add the xmp - so it might be easier to reproduce. 
Activating channelmixer with a monochrome preset results in a greyscale image with my current master build for osx

**Comment by chhil** [comment]
The xmp is attached. 2 xmps since a duplicate was created in DT for processing image differently.
[DSCF0087_01.RAF.xmp.txt](https://github.com/darktable-org/darktable/files/5253047/DSCF0087_01.RAF.xmp.txt)
[DSCF0087.RAF.xmp.txt](https://github.com/darktable-org/darktable/files/5253049/DSCF0087.RAF.xmp.txt)
The RAF raw file and XMP can be found at the dropbox link.

https://www.dropbox.com/s/2utdf93qkx3gamf/RAF_XMP.zip.txt?dl=0

**Comment by junkyardsparkle** [comment]
It looks like the blue goes away if you set color preservation mode to "none" in the curves module. It's kind of weird to have the "basic adjustments" module boosting the saturation right after using channel mixer to desaturate the image, though... ;-)

**Comment by chhil** [comment]
> It's kind of weird to have the "basic adjustments" module boosting the saturation right after using channel mixer to desaturate the image, though... ;-)
I agree. I believe before I decided to make it b/w I was playing with the modules to get me a good color image.

> The existence of the blue in the first place seems to be the color shifts applied in the "color balance" module, which is also after the channel mixer in the pipe. 
As above, one needs to go about disabling modules based on pipe order, if I decide to use channel mixer at the end?
That sounds counter intuitive.

**Comment by chhil** [comment]
> It's kind of weird to have the "basic adjustments" module boosting the saturation right after using channel mixer to desaturate the image, though... ;-)
I agree. I believe before I decided to make it b/w I was playing with the modules to get me a good color image.

> The existence of the blue in the first place seems to be the color shifts applied in the "color balance" module, which is also after the channel mixer in the pipe. 
As above, one needs to go about disabling modules based on pipe order, if I decide to use channel mixer at the end?
That sounds counter intuitive.

**Comment by junkyardsparkle** [comment]
You can do anything you want, in any order you want, but for the final image to be monochrome, you need to make sure that whichever module you use to produce the monochrome image isn't followed in the pipe by modules which produce chromatic shifts (as color balance does in this case). This isn't a bug, it's just how the pipe works. Using the "active modules" button/tab is a good way to see the ordering of everything that you have enabled.
