### ISSUE TITLE
[locallaplacian] DT 3.3.0+xxx crashes regularly 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6344]
I have attached the backtraces. As to when it happened, I can't recall as the app crashes pretty regularly for me.

darktable 3.3.0+772~g460863d3f Win10.

These 2 were generated in a time interval of 20 minutes. Their contents are different so I assume the problems are different.
[darktable_bt_R461Q0.txt](https://github.com/darktable-org/darktable/files/5253080/darktable_bt_R461Q0.txt)
[darktable_bt_4KTYQ0.txt](https://github.com/darktable-org/darktable/files/5253081/darktable_bt_4KTYQ0.txt)

**Comment by chhil** [comment]
The 1Q0 file above gets generated when I am darkroom with an image in the main view and then scrolling through the filmstrip when it eventually crashes.
This is the current stack trace and its reproducible.  DT has become very slow in this version.
[darktable_bt_GZXFR0.txt](https://github.com/darktable-org/darktable/files/5253354/darktable_bt_GZXFR0.txt)

**Comment by chhil** [comment]
This is the same error in the YQ0 debug log attached earlier.

```
AddrPC           Params
00007FFE10D149EC 0000000000000002 0000000000000000 0000000000000000  msvcrt.dll!memmove
000000006363E074 00000000052F5F00 0000000064942F28 0000000000000000  libdarktable.dll!pad_by_replication._omp_fn.0  [F:/msys64/home/chill/darktable/src/common/locallaplacian.c @ 146]
   144:   for(int j=0;j<padding;j++)
   145:   {
>  146:     memcpy(buf + w*j, buf+padding*w, sizeof(float)*w);
   147:     memcpy(buf + w*(h-padding+j), buf+w*(h-padding-1), sizeof(float)*w);
   148:   }
```

**Comment by johnny-bit** [comment]
There were couple of fixes to locallaplacian.c code, one which might've helped regarding lighttable segfaults is https://github.com/darktable-org/darktable/commit/4da8b8716aacc1376794a977ffb9bdefbd17b69d and others are regarding correct memory allocation for sizes.

Have the issue got fixed for you in current master?

if not - can you post sample fixe + xmp that can replicate the issue?

**Comment by johnny-bit** [comment]
Let's say "it's fixed" - i haven't seen any new crash or mention of crash in locallaplacian + we're on 3.7 roll so 3.3 is ancient history.

If you still have issue on current master - please say so and post an reproducer.
