### ISSUE TITLE
Panasonic Lumix DC-S5

### ISSUE THREAD

**Issue by JosefR** [darktable-org/darktable#6351]
The S5 seems to use the same sensor as the S1 and S1H, so maybe this is a quick change. 

I just uploaded samples for normal and high resolution modes. Please note that all crop modes and also the different quality modes "L", "M" and "S" output a full size 24MP RAW file of the same size (~36MB). If you still need the different versions, just let me know and I will upload them.

**Comment by LebedevRI** [comment]
> I just uploaded samples for normal and high resolution modes.

Thank you for the contribution, samples validated.

**Comment by komeo128** [comment]
Hello, DT cannot open my RAWs, I have the Lumix S5, I have to wait for an update. Thank you. PS: I'm French, sorry for such a bad translation.
![DT](https://user-images.githubusercontent.com/71792778/94067990-e7218980-fdee-11ea-9c3d-fecec803f427.jpg)

**Comment by JosefR** [comment]
> Hello, DT cannot open my RAWs, I have the Lumix S5, I have to wait for an update. 

You can work around that for the moment just by chaning the "model" tag in the exif meta data of the raw file to "DC-S1" or "DC-S1H" for example with exiftool:
    exiftool -model="DC-S1H" filename.RW2

**Comment by komeo128** [comment]
Thanks I will try

**Comment by parafin** [comment]
Backup your files before doing this. Firstly because you will want to revert to original version after support is added to darktable and secondly modifying raw files is never a good idea.

**Comment by komeo128** [comment]
In the meantime I use Silkypix

**Comment by komeo128** [comment]
Hello. How to know where to be warned when DT will be updated and will take into account the S5. Thank you

**Comment by JosefR** [comment]
@komeo128 
You can subscribe to this issue and qill be informed when it is closed. 

@LebedevRI 
Would it be OK, if I send a pull request for using the color matrix from the Lumix S1H? This is working for me: https://github.com/JosefR/darktable/commit/e9c48c40498b981c1a36a5d24adf16d2df2c736b

**Comment by LebedevRI** [comment]
Sorry, i should handle backlog of camera support, got sidetracked too much.

> using the color matrix from the Lumix S1H

I don't know if that was fixed or not, but basically not, because when a proper color matrix appears,
all the previously edited pictures will retroaspectively change/regress.

**Comment by LebedevRI** [comment]
I just re-checked, and the most recent Adobe DNG Converter (12.4, from August) still doesn't support that camera.
So until it does, we don't have a color matrix, and are therefore stuck.

**Comment by komeo128** [comment]
Hello. There is now a version 13 Adobe DNG Converter which supports the DC S5.

**Comment by JosefR** [comment]
@komeo128 
Thanks for the hint. I did just run it and get the follwing output from exif:
```
exiv2 -pt _LS50356.dng | grep BlackLevel
Error: Failed to read Panasonic IFD Makernote header.
Exif.SubImage1.BlackLevelRepeatDim           Short       2  2 2
Exif.SubImage1.BlackLevel                    Rational    4  130560/256 130560/256 130560/256 130560/256

exiv2 -pt _LS50356.dng | grep WhiteLevel
Error: Failed to read Panasonic IFD Makernote header.
Exif.SubImage1.WhiteLevel                    Short       1  16380

exiv2 -pt _LS50356.dng 2>/dev/null | grep CalibrationIlluminant2
Exif.Image.CalibrationIlluminant2            Short       1  21

exiv2 -pt _LS50356.dng 2>/dev/null | grep ColorMatrix2
Exif.Image.ColorMatrix2                      SRational   9  9744/10000 -3905/10000 -779/10000 -4899/10000 12807/10000 2324/10000 -798/10000 1630/10000 5827/10000
```
They are using the same color matrix as for thew S1

#6658 would add the color matrix

**Comment by LebedevRI** [comment]
I won't be able to add support for 96MP raws, right away anyways, they have some new decompressor.

**Comment by JosefR** [comment]
@LebedevRI 
Thanks!

**Comment by komeo128** [comment]
You did the job. Thank you.

**Comment by komeo128** [comment]
Should I uninstall and reinstall DT.

**Comment by ptilopteri** [comment]
that would be a very abnormal requirement for the linux distro's which I am 
familiar.  An update would be normal, but if 3.2.1, aiui, there will be nothing
to update.  Master is continually updated or use what you have that you said
is working and wait for the xmas upgrade.

**Comment by komeo128** [comment]
I am under windows, I still cannot open my files directly, I use DNG.

**Comment by ptilopteri** [comment]
I believe the change is to lensfun-data, not any darktable file.  If that
is fact, you need to update lensfun-data .  And I am not familiar with 
how to update lensfun-data on windows.  You will need to research 
that yourself (hint google/duck-duck/bong/...) or wait for someone here 
with the knowledge to impart.
ps: if it is indeed related directly to lensfun-data, the xmas issue of 
darktable will not help you.
