### ISSUE TITLE
Unable to Open DT 3.2.1 on Windows 

### ISSUE THREAD

**Issue by pritlakhani** [darktable-org/darktable#6354]
Unable to open DT on Windows. DT was working normally and after unexpected crash DT will not open. I tried uninstalling-reinstalling. Also, tried reinstalling graphic driver in case of driver issues. CMD/black windows for DT will open for a second and disappears. 

Windows 10 home
Intel I7-7700HQ - 2.8 GHz
Ram 16 gb
Tried disabling OpenCl support. 

Works perfectly when opened using GIMP.

**Comment by chhil** [comment]
Try backing up your config folder by renaming it and try starting it again. 

Rename darktable to something like darktablebak.

C:\Users\<your user name>\AppData\Local\darktable

**Comment by johnny-bit** [comment]
Good :) Please consider closing the issue :)
