### ISSUE TITLE
convert dartable-colorchecker csv files to .cube or other standard lut format

### ISSUE THREAD

**Issue by norayr** [darktable-org/darktable#6358]
**Is your feature request related to a problem? Please describe.**

when working with darktable-chart tool, like described [here](https://pixls.us/articles/profiling-a-camera-with-darktable-chart/) one gets .csv file of unknown format.
as i found out in the irc room, they look like list of CIE L * a * b parameters for various colour patches.
it is possible to get .dstyle files to use with darktable, but i'd prefer to get standard lut format files, like .cube to be able to use those with tools like ffmpeg.

**Describe the solution you'd like**

get the .cube (or other widespread standard format) files from or instead the .csv & .dstyle files.

**Alternatives**

documenting that .csv format would allow to may be write a .csv -> .cube converter to the developers who understand the field good enough.

**Comment by johnny-bit** [comment]
With darktable-chart you can create csv that can be used to create .dstyle. From style then you can use `exportLUT`  lua script from [darktable-org/lua-scripts](https://github.com/darktable-org/lua-scripts) repo that will create haldCLUT png file. that file can be converted to cube (i think :) )

It's not straightforward but as you see it is possible. Does this solve your problem?

**Comment by matt-maguire** [comment]
Otherwise I suggest to look at the ArgyllCMS tools to build an ICC LUT-based profile from the colour chart. To build a decent LUT though, a 24-patch color checker isn't really going to cut it, that's really only good for building a matrix profile.

http://www.argyllcms.com/doc/Scenarios.html#PS1

**Comment by junkyardsparkle** [comment]
A tool like darktable-chart, which is built around CIE L*a*b probably isn't the right tool for generating LUTs to be used in other color spaces. That said, you could always push a HaldCLUT through darktable using the generated style...

**Comment by norayr** [comment]
oh, exporting a lut from dstyle suits me perfectly!

**Comment by norayr** [comment]
okay i got darktable and lua working, but i don't understand if i have to run the exportLUT script from console, or it somehow will work from inside the darktable.

i have enabled it in ~/.config/luarc as
```
require "contrib/exportLUT"
```

i have enabled script manager from tools directory and it is shown in darktable gui, i added print statement in luarc and i see that print statement in the console output.

how should i use exportLUT?

**Comment by johnny-bit** [comment]
It's not a console tool. Check lua scripts repo for more info. And close
this issue.

czw., 24 wrz 2020, 23:26 użytkownik Norayr Chilingarian <
notifications@github.com> napisał:

**Comment by norayr** [comment]
ok sorry. i checked the repo. closing. and thank you.
