### ISSUE TITLE
[filmic] color picker in scene tab seems forget the drawn area 

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6360]
**Describe the bug**

Using filmic V4, in the scene tab, the color picker seems only to work once unless redrawing/resetting the rectangle area.

**To Reproduce**
1. Chose a picture, with slight over exposure
2. Click on color picker for "whilte relative exposure" or "black relative exposure"
3. Reset parameters of filmic (e.g. you are not satisfied with result)
4. re-do step (2)
5. see error filmic remains on the std. parameters unless you redraw the area for the eye dropper

**Expected behavior**

Same than e.g. white balance, comming back to the picker, it should re-evaluate the selected area and react accordingly

**Additional context**
* darktable version : 3.3.0+820~g5586a71a0
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

@dterrahe 
may I ping you here, as you have successfully solved #6165 and to me as a user it feels similar?

**Comment by dterrahe** [comment]
Thanks for reporting @AxelG-DE. I will have a look later/tomorrow 

Just to help me isolate the problem; does this only occur with the pickers in filmic that you mention? Do "all" other pickers work correctly or is this maybe a more general problem?

**Comment by AxelG-DE** [comment]
> Just to help me isolate the problem; does this only occur with the pickers in filmic that you mention? Do "all" other pickers work correctly or is this maybe a more general problem?

I did not try "all" but some. I can't remember, which one worked correctly, but just now I found another one, wich behaves the same wrong (in my opinion). It is _contrast fulcrum_ in _color balance_

Seems I have to systematically search after that, unless you come up with some responsible code, which then could be found by "search and replace" all over the code :-) (just these days extremely busy with job and other things :-/ )

**Comment by dterrahe** [comment]
@ralfbrown bisect leads to this: 6f34f2e11d560fc7b0d3f52c702e9b96db66e95f
Likely this just aggravated the problem; it could have happened with a smaller pixel pipe cache as well.
Color picker depends on the pipe to send it a signal on each calculation. When re-enabling the picker, I could just use the cached previous result, which would make it pass simple tests, but of course it would just contain stale data.

Looking at the changes in #5576  suggested maybe adding a call to dt_iop_refresh_center in _iop_color_picker_callback_button_press would work, but it didn't make a difference. Is there another way to invalidate/force recalculation of the pipe for a particular module?

Otherwise maybe a simple extra check within the pipe whether a colorpicker is active on the module to be skipped might be sufficient to fix this. At potential the cost of subsequent unnecessary recalcs; we only need the first one, and after any picker selection changes (which seems to get triggered correctly). I don't understand the pipe enough to not break it, so please would you have a look?

**Comment by TurboGit** [comment]
The exposure threshold picker works and seems very similar... Maybe something wrong with filmic module....

**Comment by dterrahe** [comment]
As AxelG reported, the colorbalance one also fails. I investigated; color_picker_proxy doesn't always receive the signal it needs. I then spent some fun time bisecting...

So no, this is not a problem limited to filmic. It makes sense that if we expect to receive a signal while the pipe is being processed then taking shortcuts and skipping part of the pipe breaks things. Colorpickers will randomly work/not work depending on the location in the pipe. Given that bisect led me to a commit that simply adjusts the depth of  the cache, it makes sense to assume that there were other cases previously where the cache was already deep enough to trigger the problem. I don't think we need to hunt for those. Exposure was just lucky. Maybe adding more additional modules would make it fail too.

Should be fixable. As I wrote, _not_ fastpathing when there's a color picker active might work, but might not be most efficient. And I'm definitely not knowledgeable enough about the pipe to start messing with it myself.

**Comment by TurboGit** [comment]
A tough one, looks like a hash is not properly reset/invalidated in the cache.

**Comment by TurboGit** [comment]
What I have learned so far... The hash calculation seems ok but the pipe is not properly synchronized with the color picker. That is, when you click on the pipe, the area is drawn and the hash is calculated (using the module params + the 4 box corners) but using the not yet adjusted params after having received the sample from the picker.

So the hash is calculated and stored, it will be reused (the whole point of the cache) when clicking again on the picker.... But as this did not store into the cache the new adjusted pixels nothing happen the second time.

We would probably need to avoid adjusting the cache until the params have been received and used by the module.

But at this stage I'm not even sure how to do that, my knowledge on the pipe does not go at this level of details and I'm not sure to be able to have a fix without @ralfbrown help!

**Comment by ralfbrown** [comment]
I don't really know pipe or cache very well either, though it was clear to me when tweaking the cache size that the cache could use a full overhaul (no fixed number of entries, but based on available memory; ensure that the input to the most-recently changed iop is cached, even if it's not the one with GUI focus; take into account that a bunch of iops can now change their output without changing parameters when displaying masks, etc.).

**Comment by TurboGit** [comment]
@AxelG-DE : can you check PR #6765. It fixes this issue but I'd like confirmation on your side. Also, it would be nice if you could check some other color picker to ensure they are picking the right color. So close of a release, changing part of the pipe makes me nervous! TIA.

**Comment by AxelG-DE** [comment]
Seems I was too slow again, sorry for that, I was busy...
I will check now anyways

**Comment by AxelG-DE** [comment]
Tested!
works
I found a little bit comparable behaviour in colorbalance, now also gone

Thanks!
