### ISSUE TITLE
[xmp_write] failed to serialize xmp data

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6366]
openSUSE Tumbleweed 20200919
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git820.5586a71a0
OpenCL loaded but not available
i7 12-core 36GB

Is there possibly a race condition when opening a collection?
I see the following command line output nearly always when opening a
collection:

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_203310_aaa_5171.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_204328_aaa_5202.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

Closed and reopened the same collection:

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_201751_aaa_5062.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_202216_aaa_5109.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/Second
/Half/200915_211836_aaa_5282.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_203127_aaa_5161.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_203514_aaa_5176.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_203515_aaa_5177.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

[dt_exif_xmp_write]
/mnt/nfs/photos/2020/soccer/AvonHSVarsity/2020.0915a.FranklinCentralHS/First
/Half/200915_204029_dse_1011.nef.xmp: caught exiv2 exception
/'[xmp_write] failed to serialize xmp data'

So appears whatever happening  is somewhat random or doesn't present an
apparent pattern.  But appears related to the above collection being on an
nfs connected storage (above) and not a "local" drive.  Or perhaps size of
collection as the nfs collection is >300 images and I do not have a local
collection available of >20 images.

using:  darktable --library :memory: <file><location>/*
with "write sidecar files"

maybe a timing issue opening xmp files over nfs...

**Comment by ptilopteri** [comment]
and the issue is not caused by a invalid character in "exif.comments" 
as different files are quoted in the error msgs and they do not repeat
on subsequent imports.

The only thing I find repeatable atm is they files residing on nfs storage

**Comment by ptilopteri** [comment]
I no longer see these notices, so closing

**Comment by kofa73** [comment]
I have them on local storage:
```text
[dt_exif_xmp_write] /home/kofa/Pictures/import/2024-09-29-Goncruszka-koncert/2024-09-29-16-40-20-P1040771.RW2.xmp: caught exiv2 exception '[xmp_write] failed to serialize xmp data'
```
4.9.0+693~gf302ac54ea, Ubuntu 24.04, exiv2 0.27.6-1build1
