### ISSUE TITLE
Building documentation on Windows

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#6377]
**Describe the bug**
The build files don't recognize installed saxon package when installed according to the [instructions](https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt).

**To Reproduce**
Install saxon package as instructed. When creating the build files, there are warnings
```
-- No saxon XSLT processor and/or no docbook saxon extension library found.
Xslt processor saxon not found. HTML usermanual will be built with xsltproc;
expect usermanual with inconsistent screenshot and image dimensions.
```
and
```
-- The following OPTIONAL packages have not been found:
 * Saxon
```
When I renamed the `saxon-he-10.2.jar` to `saxon.jar` and changed the `SAXON_INSTALL_DIR` to `~/java/saxon` saxon was recognized. 

**Expected behavior**
Saxon recognized

**Platform (please complete the following information):**
 - Darktable Version: 3.3 current maste
 - OS: Win10/64

**Additional context**

**Comment by johnny-bit** [comment]
Fortunately in-source usermanual got nuked and now we're focusing on https://github.com/darktable-org/dtdocs (plus build instructions for usermanual got removed).
