### ISSUE TITLE
Possible invisible bug: argument order swapping in pixelpipe_hb.c

### ISSUE THREAD

**Issue by GrahamByrnes** [darktable-org/darktable#6388]
If you look in src/develop/pixelpipe_hb.c at line 1871, you find 

`      if (pixelpipe_process_on_CPU(pipe, dev, input, input_format, **&roi_in**, output, out_format, roi_out,
                                   module, piece, &tiling, &pixelpipe_flow))'

followed a couple of lines later for those without opencl by

'    if (pixelpipe_process_on_CPU(pipe, dev, input, **&roi_in**, input_format, output, out_format, roi_out,
                                 module, piece, &tiling, &pixelpipe_flow))`

Note that the order of &roi_in and input_format has been swapped.

Now here's the weird thing: I'm using a W10 PC with no opencl, so in fact I should see only the incorrect call.
Whereas the error only occured when physically removing the opencl code.

The function declaration at line 979 agrees with the order: pipe, dev, input, input_format, roi_in, output, output_format, *roi_out....

I'd suggest swapping the order of arguments at L1876, but I can't explain why I wasn't seeing this with all the code in place?

**Comment by TurboGit** [comment]
Indeed, and this is detected when compiling with OpenCL disabled:
`./build.sh --disable-opencl`

I'll fix.

**Comment by TurboGit** [comment]
Now fixed, plus another issue compiling with --disable-opencl

Thanks.
