### ISSUE TITLE
Mask selected via Mask manger has no way to get deselected/removed from image other than opening and closing a module

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6391]
DT 3.3.0+842 Windows dev build.

![image](https://user-images.githubusercontent.com/1119439/94401697-9dd39000-0188-11eb-8699-f9a1c78228ee.png)

There needs to be an easier way from mask manager like the cursor button in modules to show or hide mask selected mask or some option on right clicking it.

**Comment by TurboGit** [comment]
Please read the manual. Do a righ-click on mask manager.

**Comment by chhil** [comment]
@TurboGit 
I assume you meant right click on the shape or group inside the mask manager. It was already tried, maybe you misunderstood the problem. The right click does not have the ability to hide the mask from the current image, that's what the issue is reporting.

![image](https://user-images.githubusercontent.com/1119439/94420332-a4223600-01a1-11eb-958c-2e1f0cc1a0d5.png)

**Comment by TurboGit** [comment]
Maybe I miss understood, you were looking for a way to delete a mask... click on the mask ('path #2) NOT in the group and you'll be able to delete.

Now I don't understand "hide the mask from the current image", what do you mean by hide here?

**Comment by chhil** [comment]
No, not looking for a way to delete either.
I clicked a path in the mask manager, this resulted in the mask becoming active on the image. Now how do I remove that visible mask from the image (I don't want to delete the mask, just don't want it displayed).

**Comment by TurboGit** [comment]
Just click anywhere in the mask manager where there is no mask and you should be done.
