### ISSUE TITLE
Mask once selected in a module via drawn mask previously used shapes dropdown cannot be removed

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6392]
I don't have a mask and I am about to select a mask (as seen my no mask used).

![image](https://user-images.githubusercontent.com/1119439/94402006-11759d00-0189-11eb-8beb-65d9763c646f.png)

After selecting one I decide not to use the mask, but there is no get rid of the selected mask (except resetting the module, but then the parameters I have tweaked will get reset too).
![image](https://user-images.githubusercontent.com/1119439/94402157-48e44980-0189-11eb-8428-e9d90231aaef.png)

I think it gets worse as that selected mask remains even when you change to parametric+drawn mask instead of giving me a newly initialized instance to select or draw mask + parametric.
![image](https://user-images.githubusercontent.com/1119439/94402384-9bbe0100-0189-11eb-9df7-7116ec7fbdf0.png)

The no mask used as a selection should be available as a selection in the dropdown.

**Comment by RawConvert** [comment]
I pretty much agree.  If you make a mistake with a drawn stroke, I can see no way to remove the last stroke, and no way to remove all the drawn items, without losing the parametric and other module settings.  Maybe if Ctrl+Z removed the last operation?

**Comment by MStraeten** [comment]
you can display the drawn mask with the icon rihgt to "1 shape use" and remove it with right mouseclick on the mask

**Comment by RawConvert** [comment]
Thanks, that's great!, I didn't think to try a right click.

**Comment by chhil** [comment]
Thats fine when you have one mask. The workaround doesn't scale, if I select a group mask that has a few masks then selecting individual masks and deleting them does not seem to be an appropriate solution.

**Comment by ralfbrown** [comment]
You can remove an entire group with the mask manager.  Right click on the appropriate "grp XXXX" and select "delete this shape" to remove the entire group and every shape in it.

**Comment by johnny-bit** [comment]
I think the established "right click -> delete shape" and "use mask manager for more complex tasks" is good approach.

The documentation in https://darktable-org.github.io/dtdocs/darkroom/masking-and-blending/masks/drawn/ makes it quite clear.

the more complex problem where user shared wrong group can be worked around with mask manager so...

**Comment by johnny-bit** [comment]
Yeah... I think current flow is good enough IMO :) Closing... but if you disagree feel free to comment and I'll reopen.
