### ISSUE TITLE
Reducing GUI preferences

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#6397]
**Removing possibly misleading preferences settings**
We have currently two settings in preferences, one is the the hidden `ui/cairo_filter`, the other one is `screen_ppd_overwrite`. Both are related to performance of the computer. The "GUI thumbs and preview" does not make real sense except being at the environment setting or a fraction of that, increasing it does **not** lead to better visual impression and costs performance.

**Suggestion**
Before implementing i would like to get feedback on this idea:

1) When starting dt we could look for a really slow machine and in such a case would switch to cairo_fast and ppd to be 0.5 of the native setting. (This would enhance lighttable/culling views a lot performancewise). The performance test could be "cpu <=2 cores" 
2) Have a switch on/off (default off) "Override automatic performance setting", if on we would use ppd==native and cairo_good. The tooltip would explain.

**Comment by johnny-bit** [comment]
1. Good idea!
2. I don't follow... seems like you mean "Override automatic performance setting" would be prefferable for users with slow cpu who got hit with cairo_fast in point 1?

**Comment by jenshannoschwalm** [comment]
Yeah. Something like that.

The GUI thumbs ppd setting is something misleading. It should **only** be done, to override the default if the system does not detect a proper value, basically only one or two make sense.

Try setting it to 0.5. If you take the tooltip seriously, you would expect just better performance. in fact the whole gtk stuff is blurred as it is later upscaled. Also increasing the value does not increase visual quality at all.

If we want that performance gain by using smaller thumbs we would need more tricks ...

So - at least we should allow this to be one or two.
