### ISSUE TITLE
Processing RAW astronomical images result in poor quality

### ISSUE THREAD

**Issue by 4VRDriver** [darktable-org/darktable#6399]
**Describe the bug**
Astronomical images don't look very good in Darktable (in Lighttable and in Darkroom).
Also when they get exported, there are many artifacts around all the stars. (Which are of course overexposed)

**To Reproduce**
Load up a long exposure astronomical image in Darktable.

**Expected behavior**
Good processing/preview of the image like on my screenshot on the right side.

**Screenshots**
Notice that this is the same raw image, opened in Darktable and on the right opened in Gwenview.
![Poor_quality](https://user-images.githubusercontent.com/44267643/94473405-71416780-01cc-11eb-8f32-b8370f1d810b.jpg)
Gwenview (and almost all other programs I have tried) does a good job at displaying my image.
Darktable on the other hand has serious artifacts around bright stars.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Arch Linux
 - OpenCL activated or no? No
 - Radeon RX Vega
 - Canon 700D CR2 RAW file

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both?
When I export the image to jpg using Gwenview and open it in Darktable,
all colors will look as expected without any artifacts

**Comment by jenshannoschwalm** [comment]
BTW you should make the raw and xmp files available for other people to reproduce :-)

This looks like an effect of filmic-rgb. Try disabling it or possibly you could reduce the middle-tones-saturation to 0. If this is the problem you might want to create your own style for astro images...

**Comment by 4VRDriver** [comment]
Thank you for your fast response.

I did not apply any effects to the image in Darktable. I just imported it into the software and it looks this way.
It's not just this pic, almost all my astronomy raw images do have these artifacts around the stars.

I had trouble to remove all the exif metadata from the raw file, that's because I did not attach it. At least I managed to get my name out of there, so here is a link to the example file: https://www.swisstransfer.com/d/ec6dc08e-3b52-4adb-8155-0d70373462b2

**Comment by junkyardsparkle** [comment]
By "artifacts" do you mean the lack of noise reduction? In your preview, the Gwenview version shows more artifacts, from noise reduction and probably JPEG compression (Doesn't Gwenview just show the embedded JPEG preview for RAW files?).

**Comment by jenshannoschwalm** [comment]
It's not about "effects". In dt some processing modules are automatically activated.

**Comment by 4VRDriver** [comment]
> By "artifacts" do you mean the lack of noise reduction?

I meant the region around the stars (eg. the brightest one). In darktable it looks weird and in Gwenview it looks ok.
The intensity of a star should look approximately like a point spread function.

Left is darktable, right is the JPG.
![comp](https://user-images.githubusercontent.com/44267643/94536238-d2a41d80-0242-11eb-940c-6c1801a9e46e.png)


> It's not about "effects". In dt some processing modules are automatically activated.

The automatically applied sharpening effect had introduced some of the distortions of the PSF, so I had to tune it down a little.

I even double checked this on a friends computer, and even Lightroom has problems in that region.

I will assume that this is not an issue, so I'm going to close this.

> Doesn't Gwenview just show the embedded JPEG preview for RAW files?

I think yes, so this is my mistake.

Thank you both for your help!
