### ISSUE TITLE
Unable to zoom in darkroom

### ISSUE THREAD

**Issue by SamuelKo1607** [darktable-org/darktable#6410]
Hi, I'm new here, I was unable to find a bug of similar description, so I report it :-)

**Describe the bug**
When I try to apply "denoise (bilateral filter)" image shows wierd artifacts

**To Reproduce**
1. open imported .arw picture in darkroom
2. apply some adjustments or don't - doesn't matter 
3. apply "denoise (bilateral filter)" (now artifacts occur)
4. zoom in to change the artifacts pattern

**Expected behavior**
application of the module

**Screenshots**
![Snímka](https://user-images.githubusercontent.com/72103265/94606678-1c205700-029b-11eb-90d7-8bf60e8dfd7a.PNG)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Win 10
 - OpenCL activation doesn't matter
 - GeForce GTX 1650 Mobile, driver 451.67

**Additional context**
Happens only to my sony .arw files, .jpgs are fine.

Thank you for your time!
Samuel

**Comment by johnny-bit** [comment]
Probably very related to  #6065

**Comment by MStraeten** [comment]
Why the title ‚unable to zoom‘ - you‘re describing a bug when using denoise (bilateral)

**Comment by SamuelKo1607** [comment]
Thanks guys. Yeah, the title might be misleading, the point was that the issue usually gets much worse after zooming in. I have rewritten the post a bit after setting the title. Anyway, the issue is virtually identical to #6065 so I close this one.
