### ISSUE TITLE
RAW images are way too dark when imported

### ISSUE THREAD

**Issue by gempain** [darktable-org/darktable#6415]
**Describe the bug**
I've just imported some photos into a fresh install of 3.2.1. I shot those photos both in JPEG and RAW on a Nikon camera. The default import profile seems incorrect, or I may be doing something wrong.

**To Reproduce**
1. Import [these](https://drive.google.com/drive/folders/1tlVgje-q5Dx4k4HuhosNpGOY26gW33sa?usp=sharing) images.
2. Open the RAW image in the darkroom, it's all dark (no joke)

**Expected behavior**
I knew that the RAW image would look different than the JPEG, but I wasn't expecting something this dark.

**Screenshots**
Here's how the RAW image looks:
![Screen Shot 2020-09-30 at 15 02 49](https://user-images.githubusercontent.com/13135149/94695915-c7cab500-0336-11eb-817d-0ff329591cc6.png)

You can see the drastic difference between JPEG and RAW images:
![Screen Shot 2020-09-30 at 14 48 13](https://user-images.githubusercontent.com/13135149/94688429-e4162400-032d-11eb-8851-e413cc4445c7.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 installed via homebrew
 - OS: OS X 10.15.3
 - No idea what OpenCL is, so probably whatever the default is
 - Intel Iris Pro 1536 MB

**Additional context**

Keep up the great work !

**Comment by junkyardsparkle** [comment]
Assuming you actually meant 3.2.1 for darktable version, see #6411 etc...

**Comment by gempain** [comment]
@junkyardsparkle correct 3.2.1 (edited my post to fix the typo). #6411 seems related, but my Nikon camera is configured to shoot in Adobe RGB, which is properly selected as the **Input Color Profile**. I may be misunderstanding something here :/

**Comment by junkyardsparkle** [comment]
The selection of Adobe RGB in the camera only applies to JPEGs. It doesn't apply to RAW files, which are by definition are in the color space defined by physical sensor properties (which the "standard" input color profile attempts to approximate). Note that applying the "standard" matrix doesn't make the output look like the JPEG. The basecurve module tries to get closer to this, and the filmic module can do the same in a more flexible way... but that's another topic altogether. :-)

**Comment by parafin** [comment]
closed another duplicate... Please search the issues before posting a new one.

**Comment by gempain** [comment]
@junkyardsparkle thanks for the explanation, standard is a lot better, I'll improve from here.
@parafin greatest apologies, I should have searched for duplicates here (Google is bad at indexing GH issues).
