### ISSUE TITLE
FR: auto-set rotate angle based on exif RollAngle

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#6423]
**Is your feature request related to a problem? Please describe.**
I'm getting a camera which does not display the rotation meter along with the histogram (Nikon Z6). Rotation wouldn't be an issue if it were automatically corrected based on the EXIF data. Many cameras offer a RollAngle exif tag that can be used for this purpose.

**Describe the solution you'd like**

The crop and rotate module could be automatically activated with the angle based on exif data. This could be set as an optional auto-apply setting like sharpen or base-curve.

**Additional context**

I cannot find the RollAngle tag in a sample Nikon Z6 shot nor in my Fujifilm X-T1 but I believe they would be part of the many undocumented tags, so I will first focus on getting those parsed in exiftool.

The Nikon D850 is a camera which does have the RollAngle tag correctly parsed in exifinfo. Sample images which could be used to develop this FR can be found on https://raw.pixls.us/#repo or https://www.photographyblog.com/previews/nikon_d850_photos

**Comment by johnny-bit** [comment]
For us to be able to use it, those tags would need to be exposed not by exiftool but by exiv2 library, so first step would need to be to ask in exiv2 :+1: once that is done, we can think about having it, however crash and rot is finnicky module to work with

**Comment by ptilopteri** [comment]
This would be a *great* enhancement.
note:  the Nikon D500 also includes "roll angle" in exif data

**Comment by trougnouf** [comment]
Thank you ! I've opened a FR on https://github.com/Exiv2/exiv2/issues/1334

**Comment by jenshannoschwalm** [comment]
May be a Lua script would be better because exif2 is not implementing camera specific tags quick.

Also it would require changes in dt internals to correct automatically.
