### ISSUE TITLE
Misrepresentation of lighttable thumbnails of pictures processed in DT 3.2.1

### ISSUE THREAD

**Issue by mimijojo** [darktable-org/darktable#6440]
I've reinstalled DT 3.2.1 on my newly rebuilt Linux Mint 20 Cinnamon.

After reimporting my 60.000 picture into DT, some thumbnails in lighttable are getting displayed 2/3 black (cfr attached screenshot below).  This issue disappears when zooming to 7 pictures per line or more in "file manager" mode, to 8 pictures in "zoomable light table" mode and remains in all zoom levels in "culling" mode.

This only happens to pictures processed in DT 3.2.1.  Thumbnails of pictures processed with previous DT are OK.  Processing "darktable-generate-cache" doesn't help.  Also compressing the history stack of the affected pictures doesn't help.

Cfr attached xmp files of a picture affected (_IMG_9579.CR2) and a picture not affected (_IMG_9578.CR2) of the same film roll.

Darktable version :
this is darktable 3.2.1
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

System info :
System:    Kernel: 5.4.0-48-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Dell product: OptiPlex 780 v: N/A serial: <filter> Chassis: 
           type: 15 serial: <filter> 
           Mobo: Dell model: 03NVJ6 v: A01 serial: <filter> BIOS: Dell v: A03 date: 02/13/2010 
CPU:       Topology: Dual Core model: Intel Core2 Duo E7500 bits: 64 type: MCP arch: Penryn rev: A 
           L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 ssse3 vmx bogomips: 11703 
           Speed: 2254 MHz min/max: N/A Core speeds (MHz): 1: 2254 2: 2294 
Graphics:  Device-1: NVIDIA GT218 [GeForce 210] vendor: ASUSTeK driver: nvidia v: 340.108 
           bus ID: 01:00.0 chip ID: 10de:0a65 
           Display: x11 server: X.Org 1.20.8 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce 210/PCIe/SSE2 v: 3.3.0 NVIDIA 340.108 direct render: Yes 
Audio:     Device-1: Intel 82801JD/DO HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 chip ID: 8086:3a6e 
           Device-2: NVIDIA High Definition Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 01:00.1 chip ID: 10de:0be3 
           Device-3: Logitech Webcam C300 type: USB driver: snd-usb-audio,uvcvideo bus ID: 1-3:4 
           chip ID: 046d:0805 
           Sound Server: ALSA v: k5.4.0-48-generic 
Network:   Device-1: Intel 82567LM-3 Gigabit Network vendor: Dell driver: e1000e v: 3.2.6-k 
           port: ece0 bus ID: 00:19.0 chip ID: 8086:10de 
           IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 298.09 GiB used: 21.51 GiB (7.2%) 
           ID-1: /dev/sda vendor: Western Digital model: WD3200AAKS-75L9A0 size: 298.09 GiB 
           speed: 3.0 Gb/s serial: <filter> 
RAID:      Hardware-1: Intel SATA Controller [RAID mode] driver: ahci v: 3.0 bus ID: 00:1f.2 
           chip ID: 8086.2822 
Partition: ID-1: / size: 287.12 GiB used: 21.51 GiB (7.5%) fs: ext4 dev: /dev/sda6 
Sensors:   System Temperatures: cpu: 35.0 C mobo: N/A gpu: nvidia temp: 54 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb https: //dl.winehq.org/wine-builds/ubuntu/ focal main
           Active apt repos in: /etc/apt/sources.list.d/eid.list 
           1: deb http: //files.eid.belgium.be/debian ulyana main
           2: deb http: //files2.eid.belgium.be/debian ulyana main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http: //dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/jtaylor-keepass-focal.list 
           1: deb http: //ppa.launchpad.net/jtaylor/keepass/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //mirrors.evowise.com/linuxmint/packages ulyana main upstream import backport
           2: deb http: //ftp.belnet.be/ubuntu focal main restricted universe multiverse
           3: deb http: //ftp.belnet.be/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //ftp.belnet.be/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 224 Uptime: 27m Memory: 7.65 GiB used: 3.15 GiB (41.2%) Init: systemd v: 245 
           runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38

**Comment by mimijojo** [comment]
[_IMG_9579.CR2_IMG_9578.CR2xmp.tar.gz](https://github.com/darktable-org/darktable/files/5322816/_IMG_9579.CR2_IMG_9578.CR2xmp.tar.gz)
![Lighttable](https://user-images.githubusercontent.com/34460742/95009976-31dca600-0626-11eb-9f22-3f208766fc69.png)

**Comment by mimijojo** [comment]
I also found that deactivating the left panel, displays some thumbnails 2/3 black and reactivating them redisplays them back to normal image.  cfr screenshots to illustrate 

PS : Same behaviour with the right panel.

![Left panel OFF - Thumbnails display not OK](https://user-images.githubusercontent.com/34460742/96353614-08b02100-10ce-11eb-9b28-8568a2af24c5.png)
![Left panel ON - Thumbnails diplay almost OK](https://user-images.githubusercontent.com/34460742/96353615-0948b780-10ce-11eb-8329-62bd9f20d343.png)

**Comment by junkyardsparkle** [comment]
>  Processing "darktable-generate-cache" doesn't help

Did you delete your existing cache before running this? IIRC it doesn't overwrite existing thumbnails, only generates missing ones.

**Comment by mimijojo** [comment]
I also found that deactivating the left panel, displays some thumbnails 2/3 black and reactivating them redisplays them back to normal image.  cfr screenshots to illustrate 

PS : Same behaviour with the right panel.

![Left panel OFF - Thumbnails display not OK](https://user-images.githubusercontent.com/34460742/96353614-08b02100-10ce-11eb-9b28-8568a2af24c5.png)
![Left panel ON - Thumbnails diplay almost OK](https://user-images.githubusercontent.com/34460742/96353615-0948b780-10ce-11eb-8329-62bd9f20d343.png)

Follow doesn't help :
1) Deleting the cache folder (/home/mimijojo/.cache/darktable/mipmaps-d6154ee20a6b59d5e8dca640fb36bdca617253cb.d/4)
2) Running darktable-generate-cache displays following :
mimijojo@mimijojo-OptiPlex-780:~$ darktable-generate-cache
creating complete lighttable thumbnail cache
creating cache directories
creating cache directory '/home/mimijojo/.cache/darktable/mipmaps-d6154ee20a6b59d5e8dca640fb36bdca617253cb.d/0'
creating cache directory '/home/mimijojo/.cache/darktable/mipmaps-d6154ee20a6b59d5e8dca640fb36bdca617253cb.d/1'
creating cache directory '/home/mimijojo/.cache/darktable/mipmaps-d6154ee20a6b59d5e8dca640fb36bdca617253cb.d/2'
image 1/61953 (0,00%) (id:1)
image 2/61953 (0,00%) (id:2)
...
image 61952/61953 (100,00%) (id:62506)
image 61953/61953 (100,00%) (id:62507)
done
mimijojo@mimijojo-OptiPlex-780:~$ 
3) This didn't recreate the deleted folder (/home/mimijojo/.cache/darktable/mipmaps-d6154ee20a6b59d5e8dca640fb36bdca617253cb.d/4).  I think thumbnails got distributed to the "1", "2" and "3" folders.
4) Opening a "corrupt" thumbnails with an image browser displays the same "corrupt" images.
5) Previewing in lighttable (with "W") still shows the same "corrupt" thumbnails.  (This also recreated the "4" folder, that now contains 4 files (only !))

**Comment by mimijojo** [comment]
Next test:
1) I installed Darktable in Flatpak
2) I imported some folders of (affected RAW) pictures).
3) I exported attached style (that is causing issue) from my local Darktable and imported it into my Flatpak DT.
4) I applied this style to the imported pictures and the result is the same, the "bigger" thumbnails of some of the pictures are also corrupted (2/3 black) here in Flatpak.

Any clue ?

**Comment by mimijojo** [comment]
Yes I did.
Deleting the cache folder
(mipmaps-d6154ee20a6b59d5e8dca640fb36bdca617253cb.d) doesn't help.
The "bigger" thumbnails in lighttable (=< 3 pics per line and "W" screen
preview) of some edited pictures remain "corrupted" (2/3 black, 1/3 image).
Discarding the history of those affected pictures fixes the issue of those
pictures.  Issue pops up again when editing these pics again.
Performing the same tests in Darktable on Flatpak doesn't help, it faces
the same issue.
I'm on Linux Mint 20 Cinnamon, DT 3.2.1 on my previous LM 19.3 on my same
hardware with the same pictures didn't have this issue.

I've to edit a few hundreds of pics, I'm stuck. :-(

Any clue or workarounds ?

**Comment by junkyardsparkle** [comment]
So does the problem happen only when applying that style? There are some modules in the style that shouldn't usually be in a style, due to being image-specific (raw black/white levels, etc), so you might want to recreate that with only processing modules included

Aside from that, since the issue seems related to thumbnail size, does changing the setting "lighttable>high quality thumbnail processing from size" to "always" or "never" have an effect?

**Comment by mimijojo** [comment]
Unfortunately changing this "lighttable>high quality thumbnail processing
from size" parameter from "720p" to "always" or "never" (and restarting DT)
doesn't have an effect.

It's no style issue. I have the same when editing files manually.  (The
style is very straight forward, it makes use of local contrast, basic
adjustments and white balance module.

**Comment by junkyardsparkle** [comment]
> The style is very straight forward, it makes use of local contrast, basic adjustments and white balance module.

The style you attached contains much more than that, you might want to take another look. :-)

Beyond that, unless somebody can reproduce this, I'm out of ideas. If you can't reproduce the behavior importing images into a clean configuration, then there's an old setting or something being auto-applied that's causing the problem.

**Comment by mimijojo** [comment]
The style contains more modules indeed, but besides those 3, they have been added automatically by creating the style.

It's like DT 3.2.1 (both Flatpak and https://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04/amd64/darktable_3.2.1-1.1_amd64.deb) are using common libraries causing this issue on LM20 and not on LM19.3, but this goes beyond my technical knowledge.

**Comment by junkyardsparkle** [comment]
> The style contains more modules indeed, but besides those 3, they have been added automatically by creating the style.

Maybe so, but some of them really shouldn't have been... see for example #6502

Library-wise, somebody else might have a better guess. If the corruption was happening during display rendering rather than creation of the thumbs, I would suspect cairo, but it sounds like that isn't the case.

**Comment by mimijojo** [comment]
Found the cause : Combining "local contrast" with the "basic adjustments"
module is causing the issue.
Not combining these two modules avoids this issue.
Hopefully this can be debugged as was often using this combination
previously (on LM 19.3)

**Comment by junkyardsparkle** [comment]
Well, I can't reproduce it myself, and nobody else seems to be reporting it, so...

 - Does it happen without OpenCL enabled?
 - Does it happen if you start with a clean config, import a picture, and activate those modules?

Here's a "cleaned up" dtstyle with only those two modules included from the dtstyle you posted:

[6440-test-1.dtstyle.txt](https://github.com/darktable-org/darktable/files/5405405/6440-test-1.dtstyle.txt)

**Comment by mimijojo** [comment]
- Checking or unchecking "Activating OpenCL support" (and restarting DT) doesn't change anything.  It doesn't fix the issue.
- The style you shared doesn't fix the issue either.
- Discarding the history stack always fixes the issue.
- Please also notice on above screenshots that issue does not occur on all pictures where I'm using these two modules.  But for sure not using the "basic adjustments" avoids the issue  I've just been editing 200 hundred pictures successfully not making use of it.
- What do you mean by the clean setup ?  The issue started on my fresh LM 20 config.  I immediately installed 3.2.1 and the issue started immediately when importing my pictures edited previously on my LM19.3 setup with DT 3.2.1, on the same hardware.

**Comment by junkyardsparkle** [comment]
>  What do you mean by the clean setup ?

Just temporarily renaming your .config/darktable directory, so that launching darktable creates a fresh configuration. If the problem can't be reproduced there, then you know there's something weird in your config. If the problem *can* be reproduced there, then there's a much better chance that somebody else will be able to reproduce/debug the issue.

> for sure not using the "basic adjustments" avoids the issue

Well, that module probably doesn't get much love, so I guess it's a likely place for odd bugs to be lurking... if you confirm that you can get it to produce the issue with a completely fresh configuration, I'll try to break it when I get a chance...

**Comment by mimijojo** [comment]
I renamed .config/darktable, reopened DT and imported folders of affected pictures, but no change unfortunately. The "big" thumbnails (<=3 pics per line) and the preview (W) of the same pictures are again corrupt.
I can't systematically reproduce the issue using local contrast and basic adjustments module (ie. on some pics it's OK, on others not), but for sure, not using the basic adjustments module avoids the issue.

**Comment by mimijojo** [comment]
I don't get the issue with Darktable on snap :

**Comment by mimijojo** [comment]
Unfortunately the issue remains in new Darktable release 3.4.0.
Removing and reimporting (of some) pictures still result in thumbnails partially black.

**Comment by johnny-bit** [comment]
Reimporting images with xmp files to them applies same processing. I tried the cleaned up style posted by @junkyardsparkle which you said that it can be used to replicate the issue and I couldn't.

This probably means that there's some weird effect happening where one combines basic adjustments, local contrast and specific params of image...

**Comment by mimijojo** [comment]
I'm really stuck.  When trying to select the best photos of the last year on Lighttable, many thumbnails are still corrupt.  This makes things very difficult to select the best pictures. cfr screenshot.
Anyone any hint to help me out ?

![Screenshot from 2021-01-06 09-29-58](https://user-images.githubusercontent.com/34460742/103747117-70f20d00-5002-11eb-953b-7df3f7e5aee0.png)

**Comment by chhil** [comment]
Try the commandline cache generate for all images.

**Comment by mimijojo** [comment]
Unfortuantly regenerating the thumbnail cache script doesn't help.

To summarize  the issue :
- The issue started when reimporting my picture library (>60K pictures) in DT 3.2.1 on my newly rebuilt Linux Mint 20 Cinnamon. (I used to run on LM 19.3 before with no issue)
- Deleting again the Darktable pictures database and re-importing the pics from scratch doesn't help.
- "Dummy" editing the affected pictures or compressing the history stack doesn't fix the thumbnails.
- Upgrading to recent DT 3.4.0 didn't fix the issue.
- Issue is likely to occur more frequently on pictures processed basic adjustments and/or local contrast module. The issue doesn't occur on pictures not processed (manually).
- Current workaround : The issue does not occur when importing the same affected pictures (with their xmp files) on my Windows 10 PC with DT 3.4.0

Does someone have and hint ?

**Comment by mimijojo** [comment]
I've submitted this issue to NVIDIA support team.  They couldn't find an issue on my config.

They gave the following hints :

_Looks fine. The only issue i see is that you’re using a very old geforce 210 with the legacy 340 driver which has been out of support for a year now. So it’s exactly the same driver you used in your previous install.
Only issues I can think of are

    newer darktable raised the requirements on OpenCL/video memory
    newer desktop environment uses more video memory so there’s not enough left for some darktables operation.
    Maybe try manipulating opencl_memory_headroom
    https://discuss.pixls.us/t/darktable-and-opencl-updated/6117_

Maybe this rings a bell with some DT developers ? (Even if I'm not sure the issue related with my GPU at all.)

**Comment by TurboGit** [comment]
`opencl_memory_headroom` has been increased from 300MB to 400MB on Wed Dec 18 2019. Try setting it back to 300.

**Comment by mimijojo** [comment]
Pascal, you made my day !!!  The issue is finally fixed. Updating this
opencl_memory_headroom parameter solved it indeed.  I tested it by removing
5000 pictures, reimported them and ran darktable-generate-cache. The
thumbnails are normal again.   Thanks a lot !
