### ISSUE TITLE
Request for keyboard shortcuts in color balance

### ISSUE THREAD

**Issue by hgmarty** [darktable-org/darktable#6441]
Hello,

when I develop a photo, I use mainly the shortcuts (filmic, expo, color balance with saturation and contraste). So i can do the work without almost touching the mouse, I love it.

Now, I use the factors in color balance but there isn't shortcuts with that elements. Are there any plans to add them in the future ? 

I'm not talking about the colors and their saturation. The shortcuts would be too many except in the case of dynamics shortcuts.

Have a good day
Thanks

**Comment by elstoc** [comment]
I'll take a look at this

**Comment by hgmarty** [comment]
With delay, thanks to you
