### ISSUE TITLE
Seg fault when trying to view 1 image(s) fullscreen in culling after selecting files in zoomable mode

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6442]
@AlicVB Can you please look at this. Latest DT git, arch linux.

Steps to reproduce:

1. In lighttable (zoomable mode) select 2 or more images you want to inspect. - **This is very important. Without previously selecting the images there will be NO crashing/seg fault.**
2. Choose "culling mode".
3. Two images will be shown side by side.
4. Try to pick 1 image fixed zoom to show one image on the screen.
5. Either instantly or after you show 2nd image (using mouse scroll wheel), DT will seg fault.

I started dt with -d lighttable and as soon as dt freezes with 1 image, it displays reload thumbs from database like mad. I attached the file.

[darktablebug.txt](https://github.com/darktable-org/darktable/files/5322917/darktablebug.txt)

I also have core dumps but they are very large (225mb).

gdb says
`Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a2083c in printf_positional () from /usr/lib/libc.so.6
`

**Comment by ptilopteri** [comment]
fwiw:  I do not have the problem.

openSUSE Tumbleweed 20201002
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git922.24a8060de
OpenCL loaded but not available
i7 12-core 36GB

retry with empty luarc

**Comment by maboleth** [comment]
You can switch these two images back and forth when 1 fixed zoom is selected (1 image is on the screen)?

**Comment by ptilopteri** [comment]
no, now I do get a seg fault.  Can test in gdb if needed

**Comment by maboleth** [comment]
Great, if you can please do.

**Comment by ptilopteri** [comment]
here is two gdb back traces but they may be faulty as gdb never returns
to command line prompt, need to <ctrl><c> to get prompt

http://wahoo.no-ip.org/~paka/dt.24a8060de.txt
http://wahoo.no-ip.org/~pakadt.24a8060de.1.txt

ran dt both times until it hangs

**Comment by ptilopteri** [comment]
is the coredump needed?

**Comment by ptilopteri** [comment]
http://wahoo.no-ip.org/~pakadt.24a8060de.1.txt

is incorrect

this works
http://wahoo.no-ip.org/~paka/dt.24a8060de.1.txt

**Comment by ptilopteri** [comment]
note: I just built ga30e42977 and no longer see the problem ???

**Comment by maboleth** [comment]
Nope, I still get the crashes.

The problem seems to be related to zoomable mode. 
For example, if I select 2 images in File manager and then go to Culling mode - I can switch between these two images without any problems.

However, if I select those images in zoomable and then go to culling - DT hangs and crashes, while trying to review them back and forth.

**Comment by maboleth** [comment]
Also, worth noting, if I have "view all" filter activated, DT will hang and not crash, while doing above mentioned scenario. 
But if I filter out, to display only those with 5 stars, it will crash.

Could this possibly be related to the database and some leftover from zoomable mode (since I get no crashes going from the File Manager -> Culling).

**Comment by ptilopteri** [comment]
there was an issue earlier about the zoomable mode.  Perhaps it will lend some
information.
sorry, I do no recall the # but it was in the last several months.

I do not use the zoomable filemanager and have yet to see any use for it.
I wish I could remove it from the menu.

**Comment by maboleth** [comment]
> there was an issue earlier about the zoomable mode. Perhaps it will lend some
> information.
> sorry, I do no recall the # but it was in the last several months.
> 
> I do not use the zoomable filemanager and have yet to see any use for it.
> I wish I could remove it from the menu.

I have reported many issues with Zoomable mode, but all of them have been fixed. This is the new one I think, not even sure it's related to Zoomable, so far it happens in Culling. Zoomable mode is my preferred choice for light table browsing though. :)

Anyway, you did get the crashes today, so this could be linked as the same issue. We'll see.

**Comment by AlicVB** [comment]
@maboleth : I've finally managed to reproduce (with one image directly and without filmstrip). I think that PR #6589 should fix it.

**Comment by maboleth** [comment]
Thanks a lot, will test it asap!
