### ISSUE TITLE
Export stilldoes not work in v3.2.1

### ISSUE THREAD

**Issue by Dabola** [darktable-org/darktable#6443]
Hello!

I also face problem to save the edited RAW file to disk as jpg.  As described by user **wpkc** here: 
https://github.com/darktable-org/darktable/issues/6027

As he describes it:
_Install darktable version 3.2.1 as upgrade or as new installation on Windows 10 Home.
    • Set "target storage" to "file on disk"
    • Set "on conflict" to either "overwrite" or "create unique filename"
    • Select an image to export.
    • Try to use any valid absolute path, any valid named variable, any valid directory separator ( /, \\ ), or use browser to select a valid destination for you.
    • Try to export the selected image.
    • Export always fails with error message of: can not export to file 'your valid Windows path and filename here'! (text inside single quotes is a valid, accessible, path and filename on the device running darktable, of co_

On my new laptop win10 Pro 64–1909 (Intel i7-9750H and 16GB) I installed Darktable 3.2.1. a few days ago.  With minimal experience with DT I succeeded to edit some RAWs and save jpeg’s to the disk at the beginning.  But yesterday I faced the same problem as described above.   I have not even had time to install any antivirus.  Just Privatefirewall 7.0.  

Error message:     “could not export to file ‘C:\Users\MyName\Documents\Picture\K10N\IMGP0057.jpg’!
Same settings as **wpkc** .

But when I tried to select ‘send as email’ instead of ‘file on disk’ then I succeeded and the file was saved by default to   C:\Users\MyName \AppData\Local\Temp

I tried this because others have found this temporary solution:
https://www.reddit.com/r/DarkTable/comments/dfawvq/could_not_export_file_error_when_exporting_files/

When I rightclick the folder it looks like is open for saving as an ordinary document folder.    
Anything you want me to try before reinstalling DT?

**Comment by ptilopteri** [comment]
try opening a second instance of your file manager and copying another jpg image into the target directory, 
  C:\Users\MyName\Documents\Picture\K10N\IMGP0057.jpg

an no quotes

**Comment by Dabola** [comment]
I already had a camera made jpg in the target directory with the same name as the RAW file.  First I thought this might be the cause and therefore I renamed IMGP0057.jpg to IMGP0057_ORIG.jpg.   I have already transfered the file from  ...\AppData\Local\Temp\ folder to ..\Documents\Picture\K10N\ but still error message.

Perhaps it has something with the fact that I tried to change the settings in "target storage" from ....\K10n\\$(FILE_NAME)   to **...\K10n\\$(FILE_NAME)-OLD**    I tried this at the beginning.   Then I also got an error message that I don't remember the details of.  Anyhow, I removed the end, **-OLD**  but still no success.  (It was then I renamed the  original jpg file in the target directory).   

Now the code looks like this: C:\\Users\\_MyName_ \\Documents\\Billete\\K10n\\$(FILE_NAME)

**Comment by johnny-bit** [comment]
It's Due to some windows protection shenenigans - either some antivir, anti malware or plethora of other "security" products that we have no control of nor a way to get around them. Every such "bug" isn't actionable for us. Best bet is for users to contact their "security" software providers and mark the blocking action against darktable as a false positive.
