### ISSUE TITLE
git 864bd74a8 segfaults when switching to darkroom mode

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6449]
openSUSE Tumbleweed 20201002
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0 git 864bd74a8
OpenCL loaded but not available
i7 12-core 36GB

git faa8e11b2 does not

backtrace:  http://wahoo.no-ip.org/~paka/darktable_bt_PVVQR0.txt

**Comment by ptilopteri** [comment]
e2abfeb0c also seg faults

**Comment by johnny-bit** [comment]
```
#6  0x00007f8200dd2732 in favorite_renderer_function (col=<optimized out>, renderer=0x7f81c4006c70, model=<optimized out>, iter=<optimized out>, user_data=<optimized out>) at /data/dt-build/darktable/src/libs/modulelist.c:143
```

file `modulelist.c` is gone after merging of #5683 

Cleaning build dir should help here.

**Comment by ptilopteri** [comment]
closed, dirty build environment
