### ISSUE TITLE
No decode delegate for this image format `JPG'  using darktable-gen-noiseprofile ??? 

### ISSUE THREAD

**Issue by igorfed** [darktable-org/darktable#6452]
Hello,

I try to run the `darktable-gen-noiseprofile` accordingly this description [https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/](url). 
In same directory I put several RAW images `*.CR2`, which is  `/media/igofed/94149AC7149AAC2C/DATA/noisemodel$. `
All images captured in different ISO (from 100 to 6400). 

After run the command `/opt/darktable/libexec/darktable/tools/darktable-gen-noiseprofile -d $(pwd)` I got error in image convertion from `CR2` to `iso100_t4-thumb.jpg` See below.

What did i do wrong?

Thank you.

The message i got:
`igofed@igofed-HP-Z4-G4-Workstation:/media/igofed/94149AC7149AAC2C/DATA/noisemodel$ /opt/darktable/libexec/darktable/tools/darktable-gen-noiseprofile -d $(pwd)===> Check for required tools
--> Check for images handling tools availability
--> Check for images export tools availability
--> Check for profiling tools availability
--> Check for tethering tools availability
--> Check for pdf tools availability

===> Check profiling directory

===> List profiling input RAW images
--> Found ISO 1000 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso1000_t6.CR2
--> Found ISO 100 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso100_t4.CR2
--> Found ISO 1250 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso1250_t8.CR2
--> Found ISO 125 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso125_t4.CR2
--> Found ISO 1600 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso1600_t10.CR2
--> Found ISO 160 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso160_t4.CR2
--> Found ISO 2000 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso2000_t13.CR2
--> Found ISO 200 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso200_t4.CR2
--> Found ISO 2500 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso2500_t15.CR2
--> Found ISO 250 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso250_t4.CR2
--> Found ISO 3200 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso3200_t20.CR2
--> Found ISO 320 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso320_t4.CR2
--> Found ISO 4000 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso4000_t25.CR2
--> Found ISO 400 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso400_t5.CR2
--> Found ISO 5000 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso5000_t30.CR2
--> Found ISO 500 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso500_t5.CR2
--> Found ISO 6400 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso6400_t40.CR2
--> Found ISO 640 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso640_t5.CR2
--> Found ISO 800 image: /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso800_t5.CR2

The script will use existing input RAW images for the profiling. No more
shot will be taken.

===> Checking profiling RAW images correctness + Jpeg export
--> ISO 100:
    /media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso100_t4.CR2
**convert: no decode delegate for this image format `JPG' @ error/constitute.c/ReadImage/562.
convert: no images defined `/media/igofed/94149AC7149AAC2C/DATA/noisemodel/iso100_t4-thumb.jpg' @ error/convert.c/ConvertImageCommand/3285.**
`

**Comment by parafin** [comment]
How did you install ImageMagick? convert tool from that package seems to be missing support for JPEG.

**Comment by igorfed** [comment]
Hi, I found my problem. I reinstall ImageMagick. Now it works well. Thank you.
