### ISSUE TITLE
GLib-CRITICAL notices 

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6457]
openSUSE Tumbleweed 20201002
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable-3.3.0~git995.6b4d0ae65
OpenCL loaded but not available
i7 12-core 36GB

when starting dt from cl, I see frequent reports:
"(darktable:30880): GLib-CRITICAL **: 12:14:36.504: g_str_has_prefix: assertion 'str != NULL' failed"

gdb coredump at:
  http://wahoo.no-ip.org/~paka/core.gdb.1000.a25cdaffc55543c3a733c91cc85090d2.8849.1601921748000000.lz4

**Comment by ptilopteri** [comment]
update
just built 70992c11 and no longer get the GLib notice, but get:
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

**Comment by ptilopteri** [comment]
no longer exists

**Comment by Thanatomanic** [comment]
I have the same reports on Windows when I run and close darktable from CLI. Current master build with MinGW64, https://github.com/darktable-org/darktable/commit/f6465132ab80a65c287868e25ac96b2861762464.

**Comment by parafin** [comment]
Make sure that you clean both your build and install dirs.

**Comment by Thanatomanic** [comment]
@parafin I have just make a clean installation (`/opt/darktable/` removed, and `rm -rf *` in the build directory before going through the instructions [here](https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt) but the messages remain. I even completely emptied my database.

**Comment by ptilopteri** [comment]
change directory and start dt
or change dir and change back and start dt

**Comment by ptilopteri** [comment]
I believe an env var is not being correctly set or reset ???

**Comment by ptilopteri** [comment]
cd ~/ ;darktable

and see if they are still there.  I believe there is feed-back from gtk when starting an app from its build directory.

**Comment by ptilopteri** [comment]
today the critical notices disappeared for me.  thanks
