### ISSUE TITLE
documentation: how to close automatic optimization

### ISSUE THREAD

**Issue by hwdef** [darktable-org/darktable#6458]
**Which new feature or section need to be documented/updated**

When I import a photo and click on the darkroom, I find a record of ten operations in the history, but I didn't perform any of these operations. This happens in every photo.

Is this an automatic optimization of the photo? I would like to know how to disable this feature.

Thanks !

![image](https://user-images.githubusercontent.com/13084946/95124414-f953de00-0785-11eb-9a26-ef7bd1baba66.png)

**Comment by Nilvus** [comment]
I suggest you to read release articles on darktable.org/blog. For your questions, see 3.0 article (https://www.darktable.org/2019/12/darktable-30/) and search history part on the article (read other parts will certainly learn you some useful things about darktable. Reading those articles (and searching on the manual after) would save you lot of time by learning more quickly how to use darktable.

Those modules are just what is needed to show the image. Many software hide that and darktable used to also. After a lot of discussions, darktable team choose to display them for transparency and let the user know what darktable do. Full rounded icon means that can be disabled at all (just necessary to show a minimum of the image). Others could but for some is not recommanded (especially white balance!). More info on the article cited above.

Base curve is a basic curve to interpret your specific camera color. It can be change by changing default workflow on preferences settings to none or replace it by filmic. More infos on workflow in 3.2 article in darktable.org/blog.

As it's not an issue and can't/won't be disabled, think about closing the issue.

**Comment by hwdef** [comment]
@Nilvus
 
Thanks !
