### ISSUE TITLE
Build on Windows fails 3.3.0+996

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#6459]
**Describe the bug**
Build on Windows fails
```
...
Scanning dependencies of target generate_authors_h
[ 54%] Generating authors.h for about dialog.
%1 is not a valid Win32 application
make[2]: *** [src/libs/CMakeFiles/generate_authors_h.dir/build.make:85: src/libs/tools/darktable_authors.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:3520: src/libs/CMakeFiles/generate_authors_h.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

**To Reproduce**
1. `make --build .`
2. See error

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+996
 - OS: Windows10

**Additional context**
I removed build directory and recreated it, but it didn't help.

**Comment by chhil** [comment]
Reproducible
Version string: 3.3.0+997~gf6465132a
Updating 7340b7b55..24a8060de

Probably related to changes made on Oct 5 : ad1760b715161b26a7bfd746ba697f324b4c7b74 or 7f84b15744b06cfc7b94ae770d484722b49ed0e7

**Comment by TurboGit** [comment]
Can one of you try this patch:

```
diff --git a/src/libs/CMakeLists.txt b/src/libs/CMakeLists.txt
index 9565d07c6..b696899fa 100644
--- a/src/libs/CMakeLists.txt
+++ b/src/libs/CMakeLists.txt
@@ -9,7 +9,7 @@ add_custom_command(
   DEPENDS ${CMAKE_SOURCE_DIR}/AUTHORS ${CMAKE_SOURCE_DIR}/tools/authors_h.sh
   OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
   COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_CURRENT_BINARY_DIR}/tools/
-  COMMAND ${CMAKE_COMMAND} -E env LANG=C LC_ALL=C ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
+  COMMAND ${CMAKE_COMMAND} -E env LANG=C LC_ALL=C bash ${CMAKE_SOURCE_DIR}/tools/authors_h.sh ${CMAKE_SOURCE_DIR}/AUTHORS ${CMAKE_CURRENT_BINARY_DIR}/tools/darktable_authors.h
   COMMENT "Generating authors.h for about dialog."
```

(basically add bash before the command). TIA

**Comment by Thanatomanic** [comment]
Does not seem to generate an error anymore.

**Comment by amousset** [comment]
Do you have correct credits field in the "About" window?

**Comment by Thanatomanic** [comment]
Yes, if it's supposed to be a long scrollable list of people:

![image](https://user-images.githubusercontent.com/6567747/95244134-dff87380-0811-11eb-89d0-6416975fc61a.png)

**Comment by amousset** [comment]
That's it, thanks!

**Comment by chhil** [comment]
@TurboGit 

Mine still doesn't build after cleaning the output folder. 

The F:\msys64\home\xxxx\darktable\src\libs\CMakeLists.txtcmakelist.txt looks correct
![image](https://user-images.githubusercontent.com/1119439/95288384-c55fe200-0885-11eb-81f6-48a2960cf884.png)

**Comment by juhavlintula** [comment]
I don't have any issues with the build. Did you clear your build directory? I did `rm -r build` before rebuilding.

**Comment by chhil** [comment]
Without bash I get the error OP has shared.

> F:/msys64/home/chill/darktable/tools/authors_h.sh

Definitely exists.


```
$ which bash
/usr/bin/bash

```
The error complains about `/bin/bash`

**Comment by chhil** [comment]
> I don't have any issues with the build. Did you clear your build directory? I did `rm -r build` before rebuilding.

Yes I did a clean build.

**Comment by ptilopteri** [comment]
> Without bash I get the error OP has shared.
> 
> > F:/msys64/home/chill/darktable/tools/authors_h.sh
> 
> Definitely exists.
> 
> ```
> $ which bash
> /usr/bin/bash
> ```
> 
> The error complains about `/bin/bash`

you should have a link
  08:12 crash:~ > which bash
  /usr/bin/bash
  08:12 crash:~ > ls -la /bin/bash 
  /bin/bash -> ../usr/bin/bash

**Comment by chhil** [comment]
@ptilopteri 
This is what I see. 

```
$ ls -la /bin/bash
-rwxr-xr-x 1 chill chill 1971272 Oct 30  2018 /bin/bash
```

**Comment by ptilopteri** [comment]
@chhil 
On linux(s) there is a link as described.  Create the link on your system
and try again to build.

**Comment by ptilopteri** [comment]
@chhil ps: you will no see the link using
  ls -la /bin/bash

you must use
  ls -la /usr/bin/bash

**Comment by chhil** [comment]
@ptilopteri


```
$ ls -la /usr/bin/bash
-rwxr-xr-x 1 chill chill 1971272 Oct 30  2018 /usr/bin/bash
```

**Comment by chhil** [comment]
@TurboGit 
For what it's worth, with the a new msys install and setting up the build environment from scratch does not build and get the error I mentioned earlier.

For it to build I had to use `/usr/bin/bash` where you had used `bash`.

Eventually I did manage to build.

This is what the about dialog looked like. It did not feel different from the previos build I had. The font/style does seem to have a problem, I see red/blue fringing, which happens on certain themes DT uses. Maybe it should use the theme for the text. 
![image](https://user-images.githubusercontent.com/1119439/95648172-d2cdd400-0af2-11eb-92fb-265fa85e7b7b.png)

For more details on current build issues refer to https://github.com/darktable-org/darktable/issues/6487

**Comment by parafin** [comment]
fringing is called sub-pixel font rendering. This is not something to be controlled from darktable, it should be a system setting. I'm not sure how it works in case of Windows, but on Linux it can be controlled through fontconfig.

**Comment by chhil** [comment]
I don't see the fringing anywhere on my system, except in this about box. It used to be there in darktable themes, but the css and font changes has fixed it.

**Comment by phrrk** [comment]
Like @chhil I have had to explicitly give the full path /bin/bash in  ...darktable\src\libs\CMakeLists.txt, i.e it seems that under MSYS2 full path is required in order for 'bin' to be found.  I don't see any fringing on my system where I am using drarktable-elegant-grey theme.
