### ISSUE TITLE
Crash whn pasting settings

### ISSUE THREAD

**Issue by bluemoon1945** [darktable-org/darktable#6462]
**Describe the bug**
DT 3.2.1 crashes 50% of the time when pasting some settings in LightTable using ctrl-shift-v

**To Reproduce**
1.     in Darkroom, ctrl-shift-c
2.     Select a combination of items (one or many, for exemple, “filmic”)
3.     press OK
4.     Go back to LightTable
5.     select a set of images (I have always experimented the problem with more than one)
6.     press ctrl-shift-v : “select parts to paste” window appears
7.     press OK
8.     DT crashes at this point 50% of the time. Sometimes, the "select parts to paste" window stays on the screen a couple of seconds more than the darktable main window ( !!)
9.     when DT is restarted (lock files removed first), the pasting will have been applied to all the images selected.

**Expected behavior**
DT should not crash after having applied the settings to the selected images

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: here is detailed info about my computer :+1: 
[code]
Snaphot created on: 20200715_1357
System:    Host: <filter> Kernel: 4.19.0-11-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-4.19.0-11-amd64 root=UUID=<filter> ro 
           quiet splash 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.2_x64 patito feo May 31  2020 base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Desktop System: Dell product: XPS 8300 v: N/A serial: <filter> Chassis: type: 3 serial: <filter> 
           Mobo: Dell model: 0Y2MRG v: A01 serial: <filter> BIOS: Dell v: A06 date: 10/17/2011 
CPU:       Topology: Quad Core model: Intel Core i7-2600 bits: 64 type: MT MCP arch: Sandy Bridge family: 6 
           model-id: 2A (42) stepping: 7 microcode: 2F L2 cache: 8192 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 54276 
           Speed: 1597 MHz min/max: 1600/3800 MHz Core speeds (MHz): 1: 1629 2: 1596 3: 1596 4: 1596 5: 1596 6: 1596 
           7: 1669 8: 1600 
           Vulnerabilities: Type: itlb_multihit status: KVM: Split huge pages 
           Type: l1tf mitigation: PTE Inversion; VMX: conditional cache flushes, SMT vulnerable 
           Type: mds mitigation: Clear CPU buffers; SMT vulnerable 
           Type: meltdown mitigation: PTI 
           Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 
           mitigation: Full generic retpoline, IBPB: conditional, IBRS_FW, STIBP: conditional, RSB filling 
           Type: srbds status: Not affected 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Turks XT [Radeon HD 6670/7670] vendor: Dell driver: radeon 
           v: kernel bus ID: 01:00.0 chip ID: 1002:6758 
           Display: x11 server: X.Org 1.20.4 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 2048x1080~60Hz 
           OpenGL: renderer: AMD TURKS (DRM 2.50.0 / 4.19.0-11-amd64 LLVM 7.0.1) v: 3.3 Mesa 18.3.6 compat-v: 3.1 
           direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Dell XPS 8300 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1c20 
           Device-2: AMD Turks HDMI Audio [Radeon HD 6500/6600 / 6700M Series] vendor: Dell driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 chip ID: 1002:aa90 
           Sound Server: ALSA v: k4.19.0-11-amd64 
Network:   Device-1: Broadcom Limited BCM4313 802.11bgn Wireless Network Adapter 
           vendor: Dell Inspiron M5010 / XPS 8300 driver: wl v: kernel port: e000 bus ID: 02:00.0 chip ID: 14e4:4727 
           IF: wlan0 state: dormant mac: <filter> 
           Device-2: Intel 82574L Gigabit Network driver: e1000e v: 3.2.6-k port: d000 bus ID: 03:00.0 
           chip ID: 8086:10d3 
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 3.64 TiB used: 1.20 TiB (32.9%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB block size: physical: 512 B 
           logical: 512 B speed: 6.0 Gb/s serial: <filter> rev: 3B6Q scheme: MBR 
           ID-2: /dev/sdb vendor: Western Digital model: WD20EZRX-00D8PB0 size: 1.82 TiB block size: 
           physical: 4096 B logical: 512 B speed: 3.0 Gb/s rotation: 5400 rpm serial: <filter> rev: 0A80 scheme: MBR 
           ID-3: /dev/sdc vendor: Samsung model: SSD 850 EVO 1TB size: 931.51 GiB block size: physical: 512 B 
           logical: 512 B speed: 3.0 Gb/s serial: <filter> rev: 3B6Q scheme: MBR 
Partition: ID-1: / raw size: 49.35 GiB size: 48.32 GiB (97.92%) used: 16.29 GiB (33.7%) fs: ext4 dev: /dev/sdb7 
           ID-2: /home raw size: 647.07 GiB size: 635.92 GiB (98.28%) used: 240.50 GiB (37.8%) fs: ext4 
           dev: /dev/sda5 
Sensors:   System Temperatures: cpu: 37.0 C mobo: N/A gpu: radeon temp: 43 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list 
           1: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ buster main
           Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
           1: deb http://deb.debian.org/debian buster-updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/debian.list 
           1: deb http://deb.debian.org/debian buster main contrib non-free
           2: deb http://deb.debian.org/debian-security buster/updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/mx.list 
           1: deb http://mirrors.rit.edu/mxlinux/mx-packages/mx/repo/ buster main non-free
           Active apt repos in: /etc/apt/sources.list.d/nordvpn.list 
           1: deb https://repo.nordvpn.com/deb/nordvpn/debian stable main
           No active apt repos in: /etc/apt/sources.list.d/various.list 
           Active apt repos in: /etc/apt/sources.list.d/vivaldi.list 
           1: deb http://repo.vivaldi.com/stable/deb/ stable main
Info:      Processes: 292 Uptime: 4d 7h 32m Memory: 31.40 GiB used: 3.41 GiB (10.9%) Init: SysVinit v: 2.93 
           runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in running in: quick-system-in 
           inxi: 3.0.36 
[/code]

**Additional context**

 - Can you reproduce with another Darktable version? i have not tried
 - Can you reproduce with a RAW or Jpeg or both? I am only using RAW (NEF exclusively)
 - Are the steps above reproduce with a fresh edit (removing history)? yes
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? If so which compiler was used, with what options? no
 - Is the issue still present using an empty/new config-dir : ?
-->

**Comment by johnny-bit** [comment]
Already fixed in current master, see #6004 and please close this issue :)
