### ISSUE TITLE
Echec import

### ISSUE THREAD

**Issue by capish** [darktable-org/darktable#6463]
Version 3.2.1 sous windows 10 
lors de l'import d'une photo : celle ci arrive directement dans la chambre noire. 
Impossible d'importer un dossier, on me peut importer qu'une image à la fois
Après modifications, l'image n'apparait pas dans la table lumineuse lors de l'export. 
L'export fonctionne

**Comment by capish** [comment]
après vérification, l'export de fonctionne pas.
Donc darktable inutilisable

**Comment by capish** [comment]
après vérification, l'export ne fonctionne pas : les images ne s'affichent pas dans la table lumineuse
Conclusion : darktable initilisable

**Comment by TurboGit** [comment]
Yes sure darktable is not meant to be used ! I love those kind of comments :)

**Comment by capish** [comment]
Bonjour
Version Windows 3.2.1
Quand l'impôt des dossiers ne fonctionne pas c'est un bug mineur à investiguer. 
Quand un travail est perdu à l'export, c'est un bug bloquant qui ne permet pas d'utiliser darktable jusqu'à la résolution du pb
Cordialement 


⁣Télécharger BlueMail pour Android ​

Le 9 oct. 2020 à 16:07, à 16:07, Pascal Obry <notifications@github.com> a écrit:

**Comment by TurboGit** [comment]
Do you really think that dt has such bugs making it unusable ? Do you think you are the only one to use dt ? Can you tell me how other people on Windows are working with dt ? So please, first check your computer or possibly the forums about Windows issues, most common is OpenCL.

**Comment by TurboGit** [comment]
And BTW, this forum is English only !

**Comment by capish** [comment]
My PC has not changed for a year.
Version 3.0.1 worked perfectly.
If you don't think losing a job is blocking, you have to explain to me what
it is.

Le ven. 9 oct. 2020 à 17:12, Pascal Obry <notifications@github.com> a
écrit :

**Comment by chhil** [comment]
Why don't you try backing up the config folder (rename it) and start DT and try doing what is failing for you.

**Comment by TurboGit** [comment]
> If you don't think losing a job is blocking, you have to explain to me what it is.

That's not what I said. Anyway this is closed for good.
