### ISSUE TITLE
Second pixel output size is lost, becomes zero

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#6464]
dt 3.3.0+584~g5424fa2e3-dirty    Ubuntu 18.04

I've been noticing for a while that sometimes the second of the two output pixel dimensions in lighttable is zero, rather than the value I used previously.  The first value does not suffer in this way.

I'm able to reproduce this as follows -
1. Invoke dt via terminal window - $HOME/DT-Mast-8Sep20/bin/darktable --cachedir $HOME/.cache/darktable-8sep --configdir $HOME/.config/darktable-8sep
2. See second value is zero.  Set it to 3600.
3. Close dt by clicking the "x" top right.
4. Invoke dt as (1)
5. See zero again.

**Comment by junkyardsparkle** [comment]
Confirmed, and I should emphasize for anybody trying to bisect this that it appears to be intermittent (which is why it seemed to be mysteriously "fixed" by correcting a minor formatting error).

@RawConvert Any idea how long ago you first noticed this?

**Comment by junkyardsparkle** [comment]
I just noticed another weird behavior with those fields: after applying a preset with non-zero values for width and height, then quitting darktable, the values aren't written to darktablerc (witch I've been keeping a watch on related to this issue).

Further, after applying such a preset, looking again at the preset menu doesn't show it as currently selected, but instead offers to update it as if it had been changed, despite not having touched any controls (somewhat like with outdated presets). If I then perform the "update", then open a different preset, then return to the first one, it now has new values for width and height: the ones which were in the fields before originally selecting the preset.

So... there's definitely some weirdness going on with these inputs... but I've already proven I'm not smart enough to figure it out. ;-)

**Comment by RawConvert** [comment]
Perhaps this is also part of the problem....?
https://discuss.pixls.us/t/export-width-height-with-zero-value/19479

**Comment by junkyardsparkle** [comment]
@RawConvert Does ac58d22a1e9836459f895c93401c04608a758504 seem to have fixed this for you?

**Comment by RawConvert** [comment]
I've built Master today (hope that's the right repository) and so far the issue is fixed.  As it's intermittent, I'll look out for it over the next few days.  Thanks for fixing.

**Comment by TurboGit** [comment]
So closing.
