### ISSUE TITLE
Module order in the new presets / manage presets / manage modules layout section.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#6475]
I just noticed the new and improved *presets* -> *manage preset* -> *manage modules layout*, which is a very nice improvement indeed!

I do have a request though:

**Is your feature request related to a problem? Please describe.**

Saying it is a problem is going a bit far but I find it somewhat annoying that the module order shown in the groups are completely random.

**Describe the solution you'd like**

Being able to choose between the _pipeline order_ or _alphabetically_ would be nice.

If only one can be implemented: The _pipeline order_, as is the current order in 3.2.1, would be be my choice.

Anyway: thanks for the all the work and effort that's being put into darktable. Much appreciated!

**Comment by AlicVB** [comment]
yes, I just noticed that too, normally, added modules should be shown in pipe order (but alphabetically in the list of modules to add)
I'll have a look soon

**Comment by jade-nl** [comment]
> I'll have a look soon

Nothing of real importance is being touched, so take it easy if you need to (X-Mas is still far away).

> [...] should be shown in pipe order [...] alphabetically in the list of modules [...]

That's a perfect combination of my suggested _choose between_ option!

**Comment by AxelG-DE** [comment]
May I go a bit further with my wish...?

Inside of module groups the modules should be orderabel freely without effect to pixle pipe (to suit the workflow) . Only when reordering inside pixlepipe tab should effect the pixlepipe

**Comment by AlicVB** [comment]
@AxelG-DE : If I understand correctly what you want, I don't think it's a good idea...
- Main reason is that it will -with no doubt- confuse a little more newcomers who will think that they can decide of the gui order of the modules
- It will add lot of complexity in the code for very little benefit
- this tool is designed to be used for configuration purpose only and may not be changed very often, so presenting module in the *current* pipe order should be enough...

**Comment by jade-nl** [comment]
@AxelG-DE : Like @AlicVB I don't think this is a good idea either.

AlicVB's idea from a few post back (favourites shown in pipe order and the separate  groups to choose from in  alphabetically order) is the best one and should be implemented. My initial idea of making this more flexible isn't a good idea after all.

All this is just a visual representation and doesn't influence the actual pipe in any way (just like the history order is visual only), and it should be as clear as possible to use (for newbies and seasoned veterans alike).

**Comment by AxelG-DE** [comment]
I'm afraid, we have a misunderstanding here and maybe I did not explain well...

What I did (quite soon after New module order got populated), 
- made my own, editable copy and set the additional modules I wanted
- re-sorted them inside the groups acc. to how regularly I use them

Finally I found, that this re-ordering got represented in the most left group of active modules (pixlepipe), which I consider wrong or at least unfortunate...

**Comment by jade-nl** [comment]
You now completely lost me and I feel this is outside the scope of this request.

> made my own, editable copy and set the additional modules I wanted
Check.

> re-sorted them inside the groups acc. to how regularly I use them
Resorted them? How? At the moment (3.3.0+1110~g6e5775ae0) all the groups and favourite lists are sorted reverse alphabetically and individual modules cannot be moved up/down. If you add another module it is also (re)sorted this way.

> re-ordering got represented in the most left group of active modules (pixlepipe),
The favourite group (left most) does not set the real pixelpipe order in any way or form.
Assuming AlicVB implements his idea it will only be a visual representation of the pixelpipe order (and I'm also assuming that this will be the default v3.0 order and not a self created one).

My original request was to set a sensible default order to all of the groups (including the left most favourite one) because at the time I filed this request it was completely random. AlicVB came up with the afore mentioned, static, solution. Which I fully agree with.

**Comment by jenshannoschwalm** [comment]
This scene of misunderstandings is exactly what has to be avoided :-)

Personally i think that there should be absolutely **no** way to change pixelpipe ordering in any sort of grouping.

Changing the order in the pixelpipe is only possible in the "active" group showing all modules.

If we really want any sort of "visual representation ordering" (and i definitely would not favour it because it leads to wrong assumptions) this would be ok for me **only if there is a clear visual** difference in representation of the "modules name", maybe italics, faded or something like that.

**Comment by jade-nl** [comment]
> This scene of misunderstandings is exactly what has to be avoided :-)
> 
> Personally i think that there should be absolutely no way to change pixelpipe ordering in any sort of grouping.
> 
> Changing the order in the pixelpipe is only possible in the "active" group showing all modules.

Yes, agree and yes.

Just in case:
![2020-10-14_14-57](https://user-images.githubusercontent.com/56407344/95992287-518d7e80-0e1d-11eb-8160-2188f1ad999b.jpg)

- Within the green part you can reorder the pipeline and thus alter its functionality.
- Within the blue part you manage what is shown in the green part.

My request is about ordering the blue part :-)

**Comment by elstoc** [comment]
> Changing the order in the pixelpipe is only possible in the "active" group showing all modules.

I don't agree with only being able to reorder in the "active" group - quite often I like to change my module order before I do any editing at all and at that point my "active" group is pretty sparse and consists mostly of modules that can't be moved.

The only way to reorder in an entirely predictable and controllable way is to have *all* modules shown (both active and inactive). Anything other than that and the resulting order is highly dependent on what modules are currently shown. However, that would end up being a list containing loads of modules I'll never use or care about.

A half-way-house would be to have a toggle mode where you could see "all modules that exist in any currently shown group" - i.e. a complete list of all of the modules that you care about in your current workflow. IMO this would be more useful than the 'second click on a group to show *all* modules'

**Comment by AxelG-DE** [comment]
1) sorry that I have somehow invaded the issue from @jade-nl, just at the end of the day I think we want all somehow the same or things are very closely linked

2) I fully agree with the wish of @jade-nl for sorting inside of the manage module layouts. 

3) Still I think, my "on-top-wish" goes in the same and right direction.

I try to reply chronologically...

**from jade_nl**
> > re-sorted them inside the groups acc. to how regularly I use them
> 
> Resorted them? How? At the moment (3.3.0+1110~g6e5775ae0) all the groups and favourite lists are sorted reverse alphabetically and individual modules cannot be moved up/down. If you add another module it is also (re)sorted this way.

Sorry, disagree on this. I'm still on (3.3.0-1079-geaeb64d2f) and with ctrl+shift I can move e.g. exposure on top of the technical group AND it is then also changed in the pipeline and I strongly think this is no any good.

**Initial _"active modules"_ group or tab**
see filmic, contrast equalizer, input color profile, exposure...
![Screenshot_20201014_184921](https://user-images.githubusercontent.com/49004103/96021265-7ac70280-0e4f-11eb-8bdd-7f8fde865096.png)

**Initial _"technical"_ group**
see filmic, defringe, input color profile, exposure...
![Screenshot_20201014_184959](https://user-images.githubusercontent.com/49004103/96021275-7dc1f300-0e4f-11eb-807c-46e6726ad36a.png)

**CHANGED _"technical"_ group**
see exposure, filmic, defringe ... (this is for demonstrating purpose here)
![Screenshot_20201014_185044](https://user-images.githubusercontent.com/49004103/96021393-a34efc80-0e4f-11eb-801f-7e05c40091f0.png)

**CHANGED _"technical"_ group**
see exposure, filmic ... I did not change in here, just moved from technical to active tab!
I think this is not good
![Screenshot_20201014_185107](https://user-images.githubusercontent.com/49004103/96021405-a8ac4700-0e4f-11eb-9109-518998e0c844.png)


> > re-ordering got represented in the most left group of active modules (pixlepipe),
> 
> The favourite group (left most) does not set the real pixelpipe order in any way or form.

Sorry, left most is the _active_ group (with the "ON" Icon) **not** _favourite_ (with the "star" Icon). Bearing that in mind, I think my message is still consistent :-)
![Screenshot_20201014_191012](https://user-images.githubusercontent.com/49004103/96025683-c54b7d80-0e55-11eb-885b-0c899e26b7b1.png)

**from  jenshannoschwalm**
> Personally i think that there should be absolutely **no** way to change pixelpipe ordering in any sort of grouping.
- I fully agree to the term **pixelpipe ordering**
- But I would like to re-order the modules inside the group according to my needs (without effect to the pixlepipe). **That is what I want**
- There are some modules I use **every time**, like _filmic_ and _exposure_ and there are modules I use rarely like _haze removal_ or _hot pixels_

**from jade_nl**
![Screenshot_20201014_191012](https://user-images.githubusercontent.com/49004103/96026590-fb3d3180-0e56-11eb-93b7-b1fa8a8e9c12.png)
>     * Within the green part you can reorder the pipeline and thus alter its functionality.
Me beeing a smartass :-)
Your green part shows the _favourite_ group. Above you said, this will not be re-orderable and will not alter the functionality, but here you say exactly this. Actually I am afraid (I have not tested this bit) that even in the _favourite group_ you can re-arrange the modules and alter the functionality.
**So I hope we can agree, only and only the _active group_ ![Screenshot_20201014_195738](https://user-images.githubusercontent.com/49004103/96027060-9e8e4680-0e57-11eb-8979-e36b75a9d6fb.png) shall have the functionality to change the pixlepipe**

**Comment by jade-nl** [comment]
Can we keep this on topic please.

This request/issue is **not** about reordering the pixelpipe!

**Comment by elstoc** [comment]
> added modules should be shown in pipe order (but alphabetically in the list of modules to add)

^ that

**Comment by jade-nl** [comment]
@AlicVB : Just in case you are still following all this. The solution posted and suggested by you in post #2 is what we are after.

I say 'we' because we had a little chat on IRC and agreed that that is the correct solution to this feature request. 

The rest of the conversation in this thread might be interesting and/or legitimate but not in the context of this request.

**Comment by AlicVB** [comment]
yes, I'm following :) I've not changed my mind too, so I'll fix this issue as mentioned in post 2. Sadly, it'll have to wait next week, I'm really short in free-time atm !

**Comment by AlicVB** [comment]
@jade-nl : I've finally manage to propose a fix : if you can test PR #6535

**Comment by jade-nl** [comment]
This doesn't solve the problem.

If I start darktable, open an image and go to the manage modules layout section I see this:

![1st open](https://user-images.githubusercontent.com/56407344/96164237-790e4500-0f0a-11eb-8ea7-afd43a057e44.png)

No notable order in the groups.

If I close that window and then immediately open it again I see this:

![2nd open](https://user-images.githubusercontent.com/56407344/96164274-85929d80-0f0a-11eb-85d5-881cc0522aea.png)

Groups are now reverse alphabetically ordered.

They stay in the last state until I restart darktable again.

**Comment by jade-nl** [comment]
Hold on just a sec. Might have had a mishap on my side....

**Comment by AlicVB** [comment]
@jade-nl : can you test again, I've added a new commit in the PR, there was another different problem when showing the "add new module" popup which completely screw the module listing... I hope this really fix the issue now

**Comment by jade-nl** [comment]
Just had a weird CPU1 L3 cache memory timeout error on my box :-)

I'll do a full reboot, a little check and then fetch and retest your latest commit. Back in 15 or so.

**Comment by jade-nl** [comment]
Latest one looks good. Did some add/delete test and the order shown is stable. Groups now show pixelpipe order and the add menu shows them alphabetically (by section).

One very small cosmetic "issue": When you add a module to a group this happens (see bottom colour group):

![2020-10-15_19-48](https://user-images.githubusercontent.com/56407344/96167360-cf7d8280-0f0e-11eb-946d-9004c0593aa0.png)

Shifting focus from screen 1 to screen 2 or overlaying dt with another program and switching back fixes this. Not sure if this is dt or xfce on my side of things.

Anyway: My request was fixed. Thanks!
