### ISSUE TITLE
crash when going in Darkroom

### ISSUE THREAD

**Issue by meplan** [darktable-org/darktable#6476]
**Describe the bug**

When double clicking on a photo to enter in darkroom, darktable crash ; I try different photo (raw & jpeg)

**To Reproduce**

Launch darktable ; double click on a photo=>crash ; see attach file: [dtdebug.txt](https://github.com/darktable-org/darktable/files/5345623/dtdebug.txt) 

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1030~g33db38fef 
 - OS:  Fedora 32 with kernel 5.8.13-200.fc32.x86_64 
 - same behavior with/wo OpenCL 
 -  NVIDIA Quadro T1000 - driver nvidia-450.66 

**Additional context**

**Comment by johnny-bit** [comment]
Clean your build and install environment. +1030 doesn't have "modulelist.c" file that is atop your dtdebug log.

**Comment by meplan** [comment]
Ok thank you very ; i have cleaned build dir but forgotten install one. Now that works.
