### ISSUE TITLE
Culling mode zooms to the top left corner of image

### ISSUE THREAD

**Issue by expipiplus1** [darktable-org/darktable#6481]
**Describe the bug**

- Open an image in darkroom mode
- Zoom the image by scrolling the mouse wheel
- Observe that the image is zoomed centering on the mouse
- Open an image in lighttable mode
- Zoom the image by scrolling the mouse wheel with the `CTRL` button pressed
- Observe that the image zooms to the top left corner

I would expect the zooming functionality to behave identically.

**Platform (please complete the following information):**

darktable from `7631e70a8437f9e73f60b56f51801d0a36c1a076`

```
$ darktable --version
this is darktable unknown-version
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

- OS: NixOS
- OpenCL: enabled
- GPU: Nvidia 2080Ti
- Driver Version: 450.66

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both?
  - Have only tried RAW (Sony AWR format)
 - Are the steps above reproduce with a fresh edit (removing history)?
  - Yes
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
  - gcc 9.3.0 `    `-DBUILD_USERMANUAL=False`

**Comment by AlicVB** [comment]
Yes, this is a known limitation of culling mode with multiple images shown. I've not took the time to develop that atm, and it's quite tricky considering that the images can have very different zoom, sizes and positions.
So this is more a feature request than an issue.

**Comment by expipiplus1** [comment]
Sounds like multiple images visible in culling mode is complex! 

Not sure whether to open a separate issue: Switching between images in culling mode while zoomed seems to shift the viewport southeast a little bit each time.
