### ISSUE TITLE
Incorrect image information when mouse is not over image in lighttable mode

### ISSUE THREAD

**Issue by expipiplus1** [darktable-org/darktable#6482]
**Describe the bug**

- Open an image collection
- Enter culling mode (This seems to happen elsewhere in lighttable mode, but is most visible here)
- Navigate to an image towards the end of the collection
- Move the mouse over the image in the center
- observe that the image information on the left panel is correct
- Move the mouse over the image information panel (or anywhere but the center image)
- Observe that the image information is now from a different image

I would expect the image information to refer to the image on display

Notice the incorrect metadata displayed in the second image (when the mouse (invisible in the screenshot) is hovering over the "image information" panel):

![image](https://user-images.githubusercontent.com/857308/95536424-9f6d4580-0a1d-11eb-81c9-38c6e437b952.png)

![image](https://user-images.githubusercontent.com/857308/95536445-aa27da80-0a1d-11eb-8adc-db5de0deded5.png)

**Platform (please complete the following information):**

darktable from `7631e70a8437f9e73f60b56f51801d0a36c1a076`

```
$ darktable --version
this is darktable unknown-version
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

- OS: NixOS
- OpenCL: enabled
- GPU: Nvidia 2080Ti
- Driver Version: 450.66

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both?
  - Have only tried RAW (Sony AWR format)
 - Are the steps above reproduce with a fresh edit (removing history)?
  - Yes
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
  - gcc 9.3.0 `    `-DBUILD_USERMANUAL=False`

**Comment by TurboGit** [comment]
Ok, when there is a single picture displayed in culling mode, but when there is two or three... Which one should be displayed in image information ? Currently the last selected image is always displayed in image information except if the mouse is over another one.

**Comment by expipiplus1** [comment]
But isn't choosing from the n images currently visible in the culling window as arbitrary as choosing from the n images currently selected?

I've not been using darktable for very long, so I could certainly be mistaken in understanding that there isn't a *primus inter pares* image in the current selection!

**Comment by AlicVB** [comment]
imho, we shouldn't change information lib content if mouse hover id becomes invalid. That way if cursor leave the main screen, we show the information of the last hovered image. Switching to the last selected image can be confusing , especially because this image can very well be out of screen.
I'll have a look when I find some time

**Comment by expipiplus1** [comment]
Sounds good. Would it be possible to spell out what would happen with no images selected and the cursor leaves the middle image?
