### ISSUE TITLE
Image Information panel requires scrolling, when empty space is available below

### ISSUE THREAD

**Issue by expipiplus1** [darktable-org/darktable#6484]
**Describe the bug**

The "Image Information" panel does not expand to fill the window, this makes it necessary to scroll in that panel, when the blank space below could be used to display more info. I suspect this happens with other panels, although I've only noticed it for image information.

**To Reproduce**

- Open an image in lighttable mode
- Resize the darktable window so that there is empty space below the "image information" panel
- Observe that the panel does not expand to make use of this empty space.

**Screenshots**

Notice that ISO is not immediately visible, but if the panel were to use the space below it, this important value would be visible without scrolling:

![image](https://user-images.githubusercontent.com/857308/95546350-f3cef000-0a32-11eb-8ae0-772da4b4f366.png)

**Platform (please complete the following information):**

darktable from `7631e70a8437f9e73f60b56f51801d0a36c1a076`

```
$ darktable --version
this is darktable unknown-version
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

- OS: NixOS
- OpenCL: enabled
- GPU: Nvidia 2080Ti
- Driver Version: 450.66

**Additional context**

 - Can you reproduce with a RAW or Jpeg or both?
  - Have only tried RAW (Sony AWR format)
 - Are the steps above reproduce with a fresh edit (removing history)?
  - Yes
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
  - gcc 9.3.0 `    `-DBUILD_USERMANUAL=False`

**Comment by TurboGit** [comment]
In 3.4 you'll be able to change the default size of most if not all scrolled windows.

**Comment by expipiplus1** [comment]
Great, thanks!

**Comment by dterrahe** [comment]
The "image information"/"metadata" module was already resizeable (it will just be slightly improved in 3.4);
if you hold ctrl while scrolling up/down with the mouse wheel while hovering above the module, it'll shrink/expand. So my guess is you inadvertently shrank it at some point.

in 3.4 this will consistently work across all modules (this is pr #6408).

**Comment by expipiplus1** [comment]
Super, thanks!
