### ISSUE TITLE
Windows build instructions older lensfun referenced is not available for download

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6485]
I am setting up my build system and going through instructions.

https://github.com/darktable-org/darktable/blob/87cb564d593e973eb03bae6894e1efa278b323ad/packaging/windows/BUILD.txt#L31

File is no longer available from http://repo.msys2.org/mingw/x86_64/

Does this impact my windows build?

**Comment by parafin** [comment]
I see that only lensfun 0.3.95 is available, which is incompatible with 0.3.2 and will break some old edits. Packagers should stop using an alpha release, and lensfun really should do a proper release already.

**Comment by chhil** [comment]
I can live with old edits breaking. So from a build perspective its fine.

**Comment by kmilos** [comment]
See https://www.msys2.org/news/#2020-10-08-main-repo-pruned

As a temporary workaround, it should still be around on some mirrors...

**Comment by phrrk** [comment]
the MSYS2 release version is now reverted (after some difficulties) to version 0.3.2 see:

https://packages.msys2.org/base/mingw-w64-lensfun

So in future there is no need for a workaround.  I will put in a PR shortly for changes to  BUILD.txt,  but there are also changes needed for the Saxon related part which is broken - try building darktable-usermanual-html.

**Comment by kmilos** [comment]
> I will put in a PR shortly for changes to BUILD.txt

Great, I see it now finally hit the msys2 repo... Please also update .ci/ci-script-windows.sh

**Comment by chhil** [comment]
Closing this.

The older version was made available in the [msys repo](http://repo.msys2.org/mingw/x86_64/)

![image](https://user-images.githubusercontent.com/1119439/99928405-f8473200-2d6e-11eb-9345-84f4e9705d03.png)
