### ISSUE TITLE
Histogram doesn't display toggle buttons, clicking does not affect exposure

### ISSUE THREAD

**Issue by TempletonTheRat** [darktable-org/darktable#6490]
### **Describe the bug**
Hovering over histogram does not display the toggle buttons (RGB, curve) or exposure data (aperture, etc.) as described in manual. Left-click + drag on either side does not change exposure. 
It does display all 4 graphs and reacts to changes I make in modules. On hover, it also displays the tooltip with instructions. It is also resizable by ctrl-scrolling.

### **To Reproduce**
Not applicable.

### **Expected behavior**
As described in manual: 
- Clickable square buttons in histogram that toggle colours displayed 
- Clickable curve button that toggles between linear, logarithmic and waveform
- Ability to change exposure with left-click + drag
- Image info display

**Screenshots**
![Screen Shot 2020-10-09 at 6 00 21 PM](https://user-images.githubusercontent.com/72586921/95635172-afa31600-0a59-11eb-9031-61d9c478487a.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: MacOs 10.15.7 Catalina
 - OpenCL activated or no? No (but I get same result when activated)
 - Which graphics card and driver version: Intel Iris Plus Graphics 640 1536 MB

### **Additional context**
 - RAW and Jpeg give same result
 - Installed from DMG

**Comment by johnny-bit** [comment]
Histogram code got gtkified in https://github.com/darktable-org/darktable/pull/7922 which means the issue should no longer be present in current master (and certainly the situation got better in 3.4.1) Closing for now. If you have problems with 3.6 (which will be released in less than a month) then please open a new report.
