### ISSUE TITLE
Darktable 3.2.1 crash after launching

### ISSUE THREAD

**Issue by aurel2222** [darktable-org/darktable#6492]
First of all : congrat to all the team working on this incredible project. I really admire your work. Thanks for this open source project.

**Describe the bug**
Darktable was installed once. I
I imported a picture from an external HDD
it worked 2 days perfectly.

I disconnected the hdd and run it again. It worked but crashed. Then I double click on darktable icon, then quickly a black windows is opening then closing immediately. Then a message saying a crash report was sent.

I tried : 
-to uninstall/reinstall it : failed, same behavior
- relaunch the pc + relauch : failed
- to reconnect the hard drive : success it worked (even if i lost the picture imported, no matter).

**Expected behavior**
Darktable should open or Darktable should say it can't find the hdd (if it was the cause).

**Additional context**
Here is the report made :

this is darktable 3.2.1 reporting an exception:

-------------------

Error occurred on Friday, October 9, 2020 at 19:56:22.

darktable.exe caused an Integer division by zero at location 00007FFF3C26FB99 in module igdrcl64.dll.

AddrPC           Params
00007FFF3C26FB99 0000000000000002 0000000000000048 0000000006E8C2C0  igdrcl64.dll!GTPin_Init
00007FFF3C2EB89A 00000000091D2750 00000000FFFFFFFF 000051C7F0A69429  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C294B1E 0000000000000000 0000000000000000 0000000006E8C2C0  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C17B161 0000000000000011 000000000000001F 0000000000000000  igdrcl64.dll!GTPin_Init
00007FFF3C296532 00000000094DE370 00000000094DE370 0000000000000000  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C2969B1 0000000000000000 0000000008E49E78 00000000007E36D0  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C183E23 000000000000000C 00007FFF3C330BEB 0000000000000000  igdrcl64.dll!GTPin_Init
00007FFF3C295A5C 0000000000000000 00007FFF3C313067 00007FFF3C3E7810  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C29596E 0000000008E49A60 0000000000000000 0000000008E49A60  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C2956C2 0000000008E49A60 0000000000000000 0000000000000000  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C2A2475 0000000008E49A60 0000000008E49A60 0000000000000000  igdrcl64.dll!clGetGLContextInfoKHR
00007FFF3C1909C6 000000000061EA88 000051C7F0A69889 0000000000000000  igdrcl64.dll!GTPin_Init
00007FFF3C190889 0000000006E8C2C0 0000000000000000 0000000006E8C2C0  igdrcl64.dll!GTPin_Init
00007FFF3C19076B 0000000000000000 0000000006E8C2C0 0000000006E8C2C0  igdrcl64.dll!GTPin_Init
00007FFF3C14E20D 0000000000000000 0000000000000000 00000000007E36D0  igdrcl64.dll!clGetPlatformIDs
00007FFF3C162BBE 0000000000805160 0000000000805160 00007FFF766FA8E8  igdrcl64.dll!clEnqueueTask
00007FFF766E10FC 0000000000000000 00007FFF00000000 0000000000805160  OpenCL.dll!0x7fff000010fc
00007FFF766E3979 00007FFF766FA8E8 0000000000000000 00000000046D9D30  OpenCL.dll!clWaitForEvents
00007FFF7FECB05F 00000000046D8670 0000000000000000 000000000061F4E4  ntdll.dll!RtlRunOnceExecuteOnce
00007FFF7DAFCB6B 0000000000000002 0000000000000014 00000000046D8670  KERNELBASE.dll!InitOnceExecuteOnce
00007FFF766E2E4C 0000000000000300 00000000046D8670 000000000484D6B0  OpenCL.dll!clGetPlatformIDs
000000006366FFCD 000000000061F8A0 0000000000000000 0000000000000000  libdarktable.dll!dt_opencl_init
00000000635E84D1 00007FFF00000001 00000000017FD9F0 00007FFF00000001  libdarktable.dll!dt_init
0000000000402A79 0000000000401670 0000000000000010 0000000000000000  darktable.exe!0x2a79
00000000004015C5 000000000000005A 0000000000000000 00000000004070A0  darktable.exe!0x15c5
00000000004013E4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x13e4
0000000000401516 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x1516
00007FFF7FCE7BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFF7FF2CE51 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.2.1.0
ntdll.dll   	10.0.18362.1049
aswhook.dll 	20.7.5568.0
KERNEL32.DLL	10.0.18362.1082
KERNELBASE.dll	10.0.18362.1049
msvcrt.dll  	7.0.18362.1
libglib-2.0-0.dll	2.64.3.0
ADVAPI32.dll	10.0.18362.752
sechost.dll 	10.0.18362.959
RPCRT4.dll  	10.0.18362.1082
ole32.dll   	10.0.18362.1082
combase.dll 	10.0.18362.1082
ucrtbase.dll	10.0.18362.815
bcryptPrimitives.dll	10.0.18362.836
GDI32.dll   	10.0.18362.1
win32u.dll  	10.0.18362.1082
gdi32full.dll	10.0.18362.1082
msvcp_win.dll	10.0.18362.815
USER32.dll  	10.0.18362.997
SHELL32.dll 	10.0.18362.1049
cfgmgr32.dll	10.0.18362.387
shcore.dll  	10.0.18362.959
windows.storage.dll	10.0.18362.1082
profapi.dll 	10.0.18362.693
powrprof.dll	10.0.18362.1
UMPDC.dll
shlwapi.dll 	10.0.18362.1
kernel.appcore.dll	10.0.18362.1
cryptsp.dll 	10.0.18362.1
WS2_32.dll  	10.0.18362.387
libintl-8.dll	0.19.8.0
libdarktable.dll
PSAPI.DLL   	10.0.18362.1
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libiconv-2.dll	1.16.0.0
libgcc_s_seh-1.dll
libstdc++-6.dll
libgomp-1.dll
libcairo-2.dll
libcurl-4.dll
CRYPT32.dll 	10.0.18362.592
MSASN1.dll  	10.0.18362.1
WLDAP32.dll 	10.0.18362.449
exchndl.dll 	0.9.2.0
libexiv2.dll
libgdk-3-0.dll	3.24.20.0
IMM32.dll   	10.0.18362.387
SETUPAPI.dll	10.0.18362.1
bcrypt.dll  	10.0.18362.267
libgdk_pixbuf-2.0-0.dll	2.40.0.0
libgio-2.0-0.dll	2.64.3.0
libgmodule-2.0-0.dll	2.64.3.0
libgobject-2.0-0.dll	2.64.3.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.20.0
comdlg32.dll	10.0.18362.900
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
lua53.dll
libopenjp2-7.dll
libpango-1.0-0.dll	1.43.0.0
libpangocairo-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
librsvg-2-2.dll
libsecret-1-0.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
zlib1.dll
MSIMG32.dll 	10.0.18362.1082
libssp-0.dll
libfontconfig-1.dll
libfreetype-6.dll	2.10.2.0
libpixman-1-0.dll
libbrotlidec.dll
libcrypto-1_1-x64.dll	1.1.1.7
libidn2-0.dll
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.7
mgwhelp.dll 	0.9.2.0
VERSION.dll 	10.0.18362.1
libexpat-1.dll
dwmapi.dll  	10.0.18362.267
WINMM.dll   	10.0.18362.1
libcairo-gobject-2.dll
libepoxy-0.dll
libfribidi-0.dll
libpangowin32-1.0-0.dll	1.43.0.0
gdiplus.dll 	10.0.18362.1082
DNSAPI.dll  	10.0.18362.1082
NSI.dll     	10.0.18362.449
IPHLPAPI.DLL	10.0.18362.1
libffi-7.dll
libexif-12.dll
libltdl-7.dll
libsystre-0.dll
libbz2-1.dll
COMCTL32.dll	6.10.18362.1082
WINSPOOL.DRV	10.0.18362.693
libatk-1.0-0.dll	2.36.0.0
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.43.0.0
libHalf-2_5.dll
libIex-2_5.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libthai-0.dll
USERENV.dll 	10.0.18362.387
libgcrypt-20.dll	1.8.5.54720
liblzma-5.dll	5.2.5.0
libzstd.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
dbghelp.dll 	10.0.18362.1049
WINMMBASE.dll	10.0.18362.1
USP10.dll   	10.0.18362.476
libtre-5.dll
PROPSYS.dll 	7.0.18362.815
OLEAUT32.dll	10.0.18362.959
libgraphite2.dll
libdatrie-1.dll
libgpg-error-0.dll	1.38.0.0
CRYPTBASE.DLL	10.0.18362.1
dbgcore.DLL 	10.0.18362.1
rsaenh.dll  	10.0.18362.1
uxtheme.dll 	10.0.18362.449
nViewH64.dll	6.14.10.14977
ntmarta.dll 	10.0.18362.1
clbcatq.dll 	2001.12.10941.16384
mswsock.dll 	10.0.18362.815
MSCTF.dll   	10.0.18362.1082
DEVOBJ.dll  	10.0.18362.387
WINTRUST.dll	10.0.18362.1049
OpenCL.dll  	2.2.5.0
dxcore.dll  	10.0.18362.1
dxgi.dll    	10.0.18362.1049
nvopencl64.dll	26.21.14.4270
nvapi64.dll 	26.21.14.4270
igdrcl64.dll	23.20.100.8142
igdgmm64.dll	26.20.100.8142
igdfcl64.dll	26.20.100.8142
igc64.dll   	26.20.100.8142
igdrcl64.dll	23.20.100.7986
igdgmm64.dll	26.20.100.7986
TextInputFramework.dll	10.0.18362.693
CoreUIComponents.dll	10.0.18362.207
CoreMessaging.dll	10.0.18362.1049
wintypes.dll	10.0.18362.1082
OneCoreCommonProxyStub.dll	10.0.18362.1
ActXPrxy.dll	10.0.18362.329
OneCoreUAPCommonProxyStub.dll	10.0.18362.1082
iertutil.dll	11.0.18362.1049

Windows 10.0.18362
DrMingw 0.9.2

-->

**Comment by parafin** [comment]
That's a bug in OpenCL drivers for your videocard. There were a lot of this kind of reports, please search the bug tracker. You can disable OpenCL using --disable-opencl command line option.
