### ISSUE TITLE
Have the possibility to import photos from hard drive with the same rules than from an camera.

### ISSUE THREAD

**Issue by junior76fr67** [darktable-org/darktable#6493]
**Is your feature request related to a problem?**
I'm anew user of DT. I have to import thousands photos from my hard drive . These photos are currently stored in folder by camera model (I know, it was a bad idea).

The "camera import module" of DT has all the functionalities to import my photos in the good folder, with the good name, ...

The problem, I can use with module ONLY when the pictures are in my camera, NOT when the pictures are in the hard drive.

**Describe the solution you'd like**
My point of view. 2 solutions possible

1 - Add one option in the setting tabs of "Import" to apply the "Session option" when you do an import from the menu "Pictures" or "Folder".

2 - Allowed to see the hard drive like an Camera with an option on the setting tabs of "Import".

Bonus : Add on option in the  "Import" setting tab to delete the copied photos.

**Alternatives**
Use an external tool, but in this case I lost some DT features (Metadata, ...).

**Additional context**
Perhaps that this feature is close of the request #6363

**Comment by ptilopteri** [comment]
you failed to provide any information relative to your system/environment or version of dt as requested.

two options currently available.

(1)
using a filemanager, move the files to another location, then import those files
again.  When finished, use the script provided,
  purge_non_existing_images.sh
to remove any images in your db which are no longer where they were imported.

(2)
use darktable to relocate subject files
darktable will take care of changing the location within the db

If this satisfies your issue, please close it.

**Comment by junior76fr67** [comment]
I was definitively not clear.  ;-)

First, Mint 20, DarkTable v3.2.1.

If I want just move the photos from one directories to another, the 2 solutions purpose work.

My need is that during the importation, the "base directory naming pattern", the "sub directory naming pattern" and "file naming pattern" define in the "Import preferences" are applied. It's ONLY the case if you import files/directories from a camera BUT it's not applied when I use the menu "image..." or "folder..."

I hope that it's more clear now. Thank you for your help.

**Comment by ptilopteri** [comment]
sorry then, I do not use those "patterns", but use a filemanager
and inport directly from a card reader to a pre-determined on disk
structure and use exiv2 to rename the files according to image date and
time (using a bash script).

**Comment by ptilopteri** [comment]
I can make a suggestion, Rapid Photo Downloader
  https://www.omgubuntu.co.uk/2017/04/rapid-photo-downloader-linux-0-9
many use it.

Note that darktable's forte is processing raw images to display rather than
file management.  Many times for the associated needs applications with 
singular focus provide better remedies. 

And I believe this is one of those cases

**Comment by jenshannoschwalm** [comment]
If you look around the list of open issues (btw you can search for them here ...) you will find this has been proposed and discussed not only once :-)
The point probably is: most of the people writing dt code don't care about this too much or are in more or less strong opposition to such an extension and would rather suggest something like @ptilopteri.

**Comment by junior76fr67** [comment]
I understand your point of view but as you told, lot of user which would like use only DT for the complete workflow. It's shame because the functionality is already implemented, just limited to the "device import" (it seems to be linked to GPhoto usage).

I installed Rapid-Photo-Downloader as recommanded. I can rename the photo and choose the directory name almost like in DT.

My photos are in a NAS with a Samba sharing. RPD cannot access to this folder (DT can access in these folders).  I will create a NFS sharing which should, I hope, solve this limit.

**Comment by jenshannoschwalm** [comment]
> the functionality is already implemented

It looks like that on the GUI. Internal details are much more tricky. I think almost all of dt dev know about this feature request. But it needs time and resources to do it especially if we want to have all the features currently available for the "import".

It's the problem of all free software, someone has to do it :-) In spare time btw :-)

I personally have it on my "likely i will do it later" list, atm working on improving black&white images workflow as i use that daily. Just leave this open and hope for the best.

**Comment by junior76fr67** [comment]
OK, I cross my finger !!!!  Thank you.

If I had the skills to do this, I could create a to do list but I'm a very poor programmer (just a little bit VBA in Excel)

**Comment by mlaverdiere** [comment]
I ran into the same problem (need), i.e. to import photos from an external drive, wanting to rename them as if I were importing them from a camera card. I know I can use RPD, but it's not as straightforward (integrated) as doing it directly within dt and it doesn't provide the same features. Hope a dev will some day find interest/time to work on this... Thanks.

**Comment by junior76fr67** [comment]
Hello mlaverdiere,

thank you for your support.  I hope that the expert will solve this issue.

Regards.

**Comment by bbinet** [comment]
I also had the same need which I've addressed by creating the following lua script:
https://github.com/bbinet/darktable-lua-scripts/blob/master/normalize-import.lua

**Comment by bbinet** [comment]
Note that it doesn't use the same rules as the import from camera, but you can update the lua script by hand so that it matches your import requirements.
