### ISSUE TITLE
Built-in auto-presets always get suffix "%" making them match e.g. camera models in a lax way

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#6494]
**Describe the bug**

I noticed that my photos taken with Canon 6d mark 2 often have heavy colorful noise in blacks. (even with ISO 100). The problem seems to be tied to basecurve. Darktable was automatically applying "Canon EOS 6D" preset. It is probably version for the first version of the camera, not mark 2. Now, starting clear instance of Darktable has these profiles not marked for automatic application, I must have had these settings persist from older versions. My problem is easily solved by disabling all specialized presets in options.

However, it seems that there should be a way to match camera models in a strict way, so that "Canon EOS 6D" string would not match "Canon EOS 6D Mark II". Users of both cameras might want to apply different presets to their photos. Of course the same thing might affect other cameras with similar names.

**To Reproduce**
1. Enable "auto-enable per camera basecurve presets"
2. Open a photo made with e.g. "Canon EOS 6D Mark II"
3. Notice that the preset for "Canon EOS 6D" was applied

**Platform (please complete the following information):**
 - Darktable Version: current git head - c3b436ebbcd503709be71c65083b6c3e43e61402
 - OS: Gentoo Linux
 - OpenCL activated - ROCm 3.8.0
 - AMD Fury, AMDGPU driver, Mesa 20.2.0

**Comment by junkyardsparkle** [comment]
I'm not seeing this behavior. If I create an auto-preset for model "E-M5" it matches only for that model, but not "E-M5 Mark II". Are you sure you're not including a "%" wildcard element at the end of your matching string?

**Comment by tomaszg7** [comment]
I didn't try to create any auto-presets manually. I only observed the behaviour of the existing Darktable profiles. Darktable adds "%" at the end of automatically generated presets.

**Comment by junkyardsparkle** [comment]
Yes, there are probably multiple issues with the matching of the built-in base curves (I know the Olympus matching needs updating). If that's the primary focus of this issue, you might want to edit the title, as well as the steps to reproduce. As it's written, it sounds like you're having issues with the use of matching in general. :-)

**Comment by tomaszg7** [comment]
You're right, I updated the description.

**Comment by tomaszg7** [comment]
The issue is still there.

**Comment by johnny-bit** [comment]
Indeed... So what's needed is in your opinion strict camera match, right?

**Comment by tomaszg7** [comment]
Yeah. The problem lies in `dt_gui_presets_update_mml()` function in `src/gui/presets.c`. It automatically pads model and maker entries with %. Sometimes it may make sense (e.g. if maker is "Canon", we might want to match "Canon Corporation" if some camera sets it). The best way would be probably to explicitly specify in all presets what is expected to happen. However a simple rule of thumb could be that maker should be matched with %%, and model in exact way (unless empty). Too bad that any change in this respect can break some profile for someone...

BTW. Looking at the code of `dt_gui_presets_update_mml()` it looks to me it would look more elegant and simpler if instead of sequence of `snprintf`s one would introduce % signs directly into SQL request a few lines above.

**Comment by johnny-bit** [comment]
PRs welcome ;) I completelly agree that maker may be matched with "%" but model with strict match.

**Comment by tomaszg7** [comment]
I pushed two commits fixing that https://github.com/tomaszg7/darktable/commit/8a2eab0841f3e5283212fa345a6a9ed570a52ceb https://github.com/tomaszg7/darktable/commit/323b77d87befb8a47747dc8b7a5059e914b8fa14

The code needs two if's to take care of empty values of model or lens. It could be avoided by editing all the presets and replacing empty strings with `%` but I think that would not be reasonable. I also tried to update all the presets which seem to expect lax matching, i.e. `E-M` becomes `%E-M%` (as there doesn't seem to be a camera called just E-M). 

Looking at this I stumbled upon weird thing introduced in https://github.com/darktable-org/darktable/commit/fe1d86b10583163d2936e676bed7c51f193cd385. Strings for maker and model are suffixed with extra spaces but the raw files I found have no such spaces in exif (I checked on raw.pixls.us). Looks to me that this preset was never really applied. However I didn't want to fix it as apparently no one used it and it could be broken.

If you think the code is ok, I'll create PR.

**Comment by johnny-bit** [comment]
The code looks totally fine IMO. And you're right about that Olympus preset. If it's inapplicable then we should either remove or make it applicable, which ever you like.

**Comment by tomaszg7** [comment]
Ok, done. However I really don't know what to do with Olympus preset. I checked it only on one raw from the repo. Maybe there are some cases when it works. I would be reluctant to touch it without feedback from original author or some other user of this camera.

**Comment by johnny-bit** [comment]
Fixed in  #7333 and merged manually to master and 3.4.1 :)
