### ISSUE TITLE
lens correction: Lists too long, (many) camera types and/or lenses cannot be seen/selected.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#6504]
**Describe the bug**
When doing a Play Raw I came across a lens that wasn't picked up automatically and wanted to set it by hand.

I noticed that the camera and lens lists are too long and (many of) the camera's and lenses at the bottom are not reachable. Using the arrow-down key you can get to them but you are working completely blind.

Just in case: I do not have a small screen (2560X1440).

**To Reproduce**
Here's one example
1. Open an image in darkroom
2. Activate/open *lens correction*
3. Click on the camera chooser and select Nikon
5. Highlight one of the types (do not click)
6. Use arrow down, see the arrow disappear at the bottom of the screen (keep holding the arrow down key) and after a while it reappears at the top.
7. If you, for example, choose a Nikon D3100, the same is true for the lens list (more obvious).

Am not able to provide a screen shot (list disappears when focus is removed).

**Expected behavior**
Being able to choose one of all the available camera types and/or lenses.

**Platform**
* darktable        : Both 3.2.1 and latest master (3.3.0+1077 gca4370430)
* OpenCL installed : Yes (nvidia-opencl-common 450.66-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER7979 MiB
* Graphics driver  : nvidia (450.66)
* OS               : Linux (kernel 5.7.10-1)
* Distro           : Debian Buster (rel. 10.6)
* Xorg             : 7.7+19

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by Nilvus** [comment]
I can't reproduce. When having long list, I always see arrows when lens/camera are hidden. And I have a smaller resolution (1920x1200).

For screenshots, I suggest you to use the best screenshot software: flameshot. Just open its launcher, set a delay and then go to what you want to capture before the end of the delay.

What I have on my side if I choose Nikon for example:

![2020-10-11_17-22](https://user-images.githubusercontent.com/45535283/95682631-94b1dc80-0be6-11eb-8fbd-738f6713c383.png)

**Comment by jade-nl** [comment]
I see that you have a nice arrow up/down boundary on the top/bottom and I'm assuming that the list slides up/down between them. I do not have that. Here's what I see:

![2020-10-11_17-39](https://user-images.githubusercontent.com/56407344/95683034-4269bf00-0bd8-11eb-97b1-2d76176d87c8.png)

There's nothing above or below what is shown (there is: the  physical edge of my screen)

The two things that I can come up with why I don't have what is shown in your image:

- Xfce 4 (4.12.1) doesn't support this?
- GTK+ version 3.24.5?

There's supposedly a bug in that specific GTK version. I vaguely remember rawtherapee warning me about this when building from source. There's as of yet no backported newer version for Debian Buster though.

Can you confirm/deny any or both of the above points?

BTW: flameshot: Neat! Thank you for that one.

**Comment by Nilvus** [comment]
I use Gnome 3.38 and Gtk+ 3.24.23. And I remember something about some older 3.24 version like yours. I think your issue is more a Gtk one and need to update Gtk+ to solve it.

**Comment by jade-nl** [comment]
OK. Very likely not darktable related.

Closing this issue for now and will wait and see what happens if/when Debian has a newer version available.

**Comment by dterrahe** [comment]
Just to eliminate possible contributing factors; you don't use multi-monitors? I've seen issues like that using gtk on screens of different sizes.

**Comment by jade-nl** [comment]
I do use 2 monitors: different sizes and brands.

My main monitor, which is primarily used for my editing (being DT, RT or GIMP) is a 2560x1440 99.9% sRGB. The other one is an old, "cheap" 1920x1080.

I do not make use of the second, smaller, screen when editing. Ever.

**Comment by dterrahe** [comment]
Similar to the setup i sometimes use (laptop+monitor). Can confuse gtk.

**Comment by sbij** [comment]
I have the same problem, with same GTK 3.24.5 version, but I have found a workaround on my Darktable to be able to scroll with this version:

when having your cursor on the camera brand name (for example canon, nikon, etc. not moving your cursor to the specific camera models), press right arrow key, it will make the list of camera models scrollable
