### ISSUE TITLE
Green channel clipped to zero in parts of my image

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#6507]
**Describe the bug**

In some parts of an image I'm editing, the colors look quite different then in Capture NX-D or Lightroom and the color picker shows that the values for green is zero. This also caused very weird things to happen in the filmic rgb module with preserve chrominance set to no.

RAW file can be downloaded here:  https://www.dropbox.com/s/g7rgsxkp6kkih7i/DSC_2713.NEF?dl=0

**To Reproduce**

1. Open the image and disable things like filmic or base curve so the image is nearly untouched.
2. Put a color picker on parts of the image
3. See that green is 0, while in lightroom or CaptureNX-D there is a value > 0 (above 50% even).

**Expected behavior**
Have green data 😄 

**Screenshots**

### Darktable

![afbeelding](https://user-images.githubusercontent.com/16192496/95689436-043cc180-0c11-11eb-8892-540442282105.png)

### Capture NX-D

![afbeelding](https://user-images.githubusercontent.com/16192496/95689519-9f359b80-0c11-11eb-932e-9d25ecd3d83f.png)

### Lightroom

![afbeelding](https://user-images.githubusercontent.com/16192496/95689567-eb80db80-0c11-11eb-9cac-db44deeec5e7.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - No openCL

**Comment by junkyardsparkle** [comment]
You're comparing a flat, linear image in darktable to images with "camera-like" curves applied in the other software. :-)

**Comment by jobec** [comment]
Even when I apply the nikon D750 basecurve, there is no green in there.

**Comment by junkyardsparkle** [comment]
Can you check the input color profile and make sure it isn't set to sRGB? There's a bug in the last release that can cause this to happen when also loading JPEGs alongside RAW files.

**Comment by jobec** [comment]
The input color profile is set to "enhanced color matrix" and "linear Rec2020 RGB"

**Comment by junkyardsparkle** [comment]
Ok, I downloaded the file... some pretty extreme out-of-gamut colors going on there! This is an example of a case where using the "gamut clipping" feature of the input color profile makes sense. If you try setting that to linear Rec 709 it should help with that. Using ProPhoto for the working profile can help a little bit, too. I would also investigate using the "standard" vs "enhanced" matrix, since some of the "enhanced" ones are better than others (but this probably isn't the picture to evaluate that with).

At any rate, rest assured that your green channel isn't being "clipped to zero" by darktable; it will show up again when the extreme saturation has been tamed.

**Comment by jobec** [comment]
What's so different then with Lightroom, Capture NX-D or even the in-camera JPEG processor, that they handle this without fiddling around with settings?

**Comment by junkyardsparkle** [comment]
> I have the feeling sometimes that I would like a line by line debugger hooked up to darktable to see at what step exactly my images go fubar.

History stack? ;-)

In short (because it's late here) darktable generally doesn't try to make very many decisions for you. It tends to expose options to users where some software may simply hide them. If you decide that gamut clipping is a better default for your purposes, you can always create an auto-applied preset where it's enabled.

**Comment by TurboGit** [comment]
> What's so different then with Lightroom, Capture NX-D or even the in-camera JPEG processor, that they handle this without fiddling around with settings?

Those software are doing things over your back and no one knows what they are doing so it is hard to comment. In dt everything is exposed and very little (or maybe nothing) is done automagicaly.

**Comment by TurboGit** [comment]
On the pictures you sent one can see that dt has stronger colors. I remember that Lr (when I was using it) did always seems to desaturate the pictures. As @junkyardsparkle you have a strong out of gamut, maybe desaturating would help ?

**Comment by TurboGit** [comment]
Also you take the "min" in the color picker. It means some (and possibly one one) pixel are clipped to 0.

**Comment by jobec** [comment]
> Those software are doing things over your back and no one knows what they are doing so it is hard to comment. In dt everything is exposed and very little (or maybe nothing) is done automagicaly.

Yes, and that is exactly what I like about darktable. Lightroom and it's couple of automagic sliders gives me the shivers. But I lose many hours each time figuring out what exactly I need to do to just get a decent baseline for my image. While in lightroom you just pick one and go from there. And it every time gives a predictable baseline.

And while darktable indeed doesn't do much things automagically, it still has certain defaults for certain settings. And I have the impression those defaults don't always match with what people initially expect them to do. Or maybe it's just me who keeps bumping into the extremes and corner cases with my pictures... 😝 Anyway, I tried to build basic base style to use on all of my images, but I never manage to make it work for all of them. 25% or so of my pictures I need to resolve things I perceive as "weirdness".

**Comment by jobec** [comment]
> Also you take the "min" in the color picker. It means some (and possibly one one) pixel are clipped to 0.

Yes, bit it are "point" color pickers, not area. It also doesn't matter where you click, in that region, it's always 0 for the green channel.

**Comment by TurboGit** [comment]
> It also doesn't matter where you click, in that region, it's always 0 for the green channel.

I cannot agree with tha since my testing shows that I have a mean of 9 on this region on my side. Also adding Filmicrgb with a lowered saturation give me a green channel of around 100 in this area.

**Comment by jobec** [comment]
Let me do some more tests this evening. There's clearly a concept somewhere that I'm not getting.

**Comment by jobec** [comment]
Yes, it seems like adding filmic with the default settings brings back the green to a value > 0.

But so does changing the histogram profile. And now I'm confused even more. Depending on the profile I chose for the histogram the histogram becomes totally different (hence the name of the setting) but, the color shown in the color picker also changes. But the displayed picture does not.
What should it be set to, to display the color and the histogram of what I'm actually seeing? I don't get why I would want the histogram and color picker to show my anything but what's on the screen 🤷‍♂️

**Comment by junkyardsparkle** [comment]
> What should it be set to, to display the color and the histogram of what I'm actually seeing?

Display profile.

> I don't get why I would want the histogram and color picker to show my anything else then what's on the screen 

Well, somebody using live view tethering might want information related to capturing rather than to editing, for instance...

**Comment by jobec** [comment]
I'm not entirely convinced that this isn't a bug (or at least a default behavior that could be improved), but I'll close it anyway.

**Comment by junkyardsparkle** [comment]
Well, did we at least establish that your green data isn't being discarded? You could open a Feature Request issue to specifically discuss the default handling of extreme gamuts, if that's what you still consider to be an issue. You have a pretty good test image there. :-)
