### ISSUE TITLE
Culling issue on launching

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#6511]
**Describe the bug**

On a precise process in launching culling mode, darktable freeze.

**To Reproduce**
1. Have 3 separated images to compare (with 2 images displayed only in culling mode)
2. Select the image 1 and 2 (on reproducible issue I had, image 2 is just the next image of image 1 in lighttable main view)
3. Click on X to go in culling mode. All good.
4. Quit culling mode and then select image 2 and image 3 (on my reproducible issue image 3 is on next line as the 2 others ones).
5. See that darktable freeze.

**Expected behavior**
No freeze when changing selection and go back to culling mode.

 - Darktable Version: master (compiled 11th octobre evening)
 - OS: Ubuntu 20.10 beta

@AlicVB: if any help to debug is needed, it would be a pleasure to help again.

**Comment by maboleth** [comment]
Can this be somehow related to #6442 ?

**Comment by Nilvus** [comment]
Maybe!

**Comment by AlicVB** [comment]
@Nilvus : I've managed to reproduce :) PR #6589 should fix the problem
