### ISSUE TITLE
Darktable crashes when going from darktable to lighttable after changing the modules list

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#6514]
**Describe the bug**

Darktable crashes after I add a module in one of the groups of "manage module layouts", when I return to lighttable. All development done is gone. I can reproduce this consistently.

**To Reproduce**

0. Make an editable layout; default_1 as a duplicate of default.
1. Double click on a photo
2. Go to "manage module layouts"
3. Click on default_1, add a module to the effects group
4. close the "manage module layouts" window, double click on the image to return to lighttable.
5. Hangup, sometimes a corrupted view in lighttable, segmentation fault

**Expected behavior**
Browsing images in lighttable, thumbnail updates, development is saved

**Screenshots**
![Screenshot from 2020-10-12 18-47-46](https://user-images.githubusercontent.com/6899116/95771671-c183f380-0cbb-11eb-8397-a4d95cd2ff9a.png)

**Platform (please complete the following information):**
 - Darktable Version: a1f80bf30bec45be7e7545898ee911f54a7509ed
 - OS: Arch Linux
 - OpenCL activated
 - GPUs: GeForce GTX 1070 w/ 455.28, Radeon RX Vega 56 (DRM 3.38.0; 5.8.14-arch1-1, LLVM 10.0.1)

**Additional context**

Installed from https://aur.archlinux.org/packages/darktable-git/

[dtdbg.log](https://github.com/darktable-org/darktable/files/5366398/dtdbg.log)

**Comment by trougnouf** [comment]
Possibly related to #6495 . @kofa73 can you check if this reproduces your crash consistently ?

**Comment by AxelG-DE** [comment]
Could you bisect this?
How to do is described somewhere in the dt docs, me I watched YouTube, is easy...

**Comment by trougnouf** [comment]
Bisect is meant to find the culprit commit right ? I've already identified it as 1d3d2dca2ce74b6daa0576d7bdb8e2b4c09c8586 , hence I'm using the previous commit for stable use.

**Comment by AlicVB** [comment]
@trougnouf : can you test PR #6535 ? it should fix the issue... thanks
