### ISSUE TITLE
Strange characters on overlays

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6515]
Latest master git, when image is hovered in the light table, as seen on the image:

![Screenshot from 2020-10-12 19-18-44](https://user-images.githubusercontent.com/2467520/95774109-145faa00-0cc0-11eb-80fa-8999c944fd1a.png)

**Comment by elstoc** [comment]
What do you have in `preferences -> lighttable -> pattern for the thumbnail tooltip` and does the issue go away if you double-click this setting to reset it to default?

**Comment by maboleth** [comment]
Ugh, sorry, I have probably changed it without knowing, I will close it.

**Comment by TurboGit** [comment]
> Ugh, sorry, I have probably changed it without knowing, I will close it.

No you didn't, it was a transient bug I had introduced some days ago which is now fixed.

**Comment by maboleth** [comment]
> > Ugh, sorry, I have probably changed it without knowing, I will close it.
> 
> No you didn't, it was a transient bug I had introduced some days ago which is now fixed.

Thanks for keeping my sanity, Pascal. :D Though thought my daughter did it when she was waving across the keyboard.
