### ISSUE TITLE
module layouts scrollable list glitch in Windows

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#6519]
About the new manage module layout dialog, there is a graphic glitch in Windows 10 HiDPI. It doesn't happen in Ubuntu
When adding a new module to a module group in a layour, the scrollable list shows the modules name aligned to the right.
However, the label overlaps with the scrollbar and labels are clipped.

![Cattura](https://user-images.githubusercontent.com/43290988/95864434-aa99db80-0d65-11eb-92cd-09e1e8d4b011.JPG)

**Comment by Nilvus** [comment]
That's strange. On Linux and actual master, I even don't have scrollbar. And I need to scroll down/up to display all modules.

**Comment by Mark-64** [comment]
No longer valid, as the design has changed and now it works ok.
closing
