### ISSUE TITLE
dt_opencl_lock_device() doesn't take into account DT_DEV_PIXELPIPE_FAST

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#6523]
**Describe the bug**
With multiple GPU where priority is set to device other than 0, the first full/image processing takes into account the user-defined priority, but subsequent calls with `DT_DEV_PIXELPIPE_FAST` being added, `pipetype` is then not listed in the `switch` statement of `dt_opencl_lock_device()`

**To Reproduce**
- On a system with multiple OpenCL devices, set priority of Full/Image to prioritize device 1
- When an image is opened in darkroom the first time, device 1 is used correctly for full rendering
- However, subsequent full renderings will use device 0 instead.

**Expected behavior**
- device 1 should be used for every full rendering instead

**Platform:**
 - Darktable Version: 3.3.0+1078~g849c134e8
 - OS: Ubuntu 20.04
 - OpenCL with two devices (IGP as device 0, GTX 1050Ti as device 1)
- `opencl_device_priority=+1/!1,*/+1/*/*`

**Additional context**
I confirmed the problem by adding an additional case, and it fixed the correct use of priority in subsequent renderings. I think we just need to update the `switch` statement to take into account `DT_DEV_PIXELPIPE_FAST` (not sure about the remaining cases).

`
> switch(pipetype)
> {
>   case DT_DEV_PIXELPIPE_FULL:
>   case (DT_DEV_PIXELPIPE_FULL | DT_DEV_PIXELPIPE_FAST):`

**Comment by AxelG-DE** [comment]
I do not have proper competence for root cause analysis or fix. 

However, I also said I the past, priority setting is not obeyed in case of multiple GPU (since quite some time)

**Comment by hqhoang** [comment]
> However, I also said I the past, priority setting is not obeyed in case of multiple GPU (since quite some time)

Sorry, should have mentioned that I have user-defined priority with scheduling set to "default". User-defined priority was working correctly before recent changes (PIXELPIPE_FAST?)

My darktablerc has these lines:

```
opencl_checksum=OFF
opencl_device_priority=+1/+0/+1/+*/+*
opencl_scheduling_profile=default
```

**Comment by AxelG-DE** [comment]
Me2

**Comment by hqhoang** [comment]
not sure which commit fixed it, but I cannot reproduce the problem with the latest master anymore.
