### ISSUE TITLE
Quirky tethering with darktable 3.2.1 with Sony Alpha 7 III

### ISSUE THREAD

**Issue by derlunz** [darktable-org/darktable#6524]
**Describe the bug**
I've tried to tether my Sony Alpha 7 III on a PC running Ubuntu 20.04 using darktable 3.2.1 from opensuse PPA, as well as from snap. Per default tethering is unavailable. When starting darktable using `strace darktable`, however,  tethering works fine.
When using darktable 3.0.1, as provided by Ubuntu package repository tethering works fine.

**Steps To Reproduce**
1. Connect camera to PC via USB. Camera is in USB Auto, USB Multi LUN mode.
2. Open darktable 
3. Darktable _does not show_ the 'Tethering' button on the top right area.
4. Close darktable
5. Open Terminal
6. Start darktable using `strace darktable`
7. Darktable _shows_ the 'Tethering' button on the top right area.
8. Tethering works as expected.

**Expected behavior**
Tethering with my (properly configured and connected) Sony Alpha 7 III should be available when opening darktable using a launcher or entering the `darktable` command in a terminal.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 (via opensuse PPA and snap)
 - OS: Ubuntu 20.04.1
 - Graphics: Nvidia GTX1060, Driver: nvidia 455.23.04-0ubuntu0~0.20.04.1
 - gphoto2: 2.5.23
 - libgphoto2: 2.5.25
 - libgphoto2_port: 0.12.0

**Additional context**
 -  [darktable-3.0.1-tether-ok.version.txt](https://github.com/darktable-org/darktable/files/5377963/darktable-3.0.1-tether-ok.version.txt) provided in Ubuntu package repositorys works as expected.
- [darktable-3.2.1-tether-quirky.version.txt](https://github.com/darktable-org/darktable/files/5377965/darktable-3.2.1-tether-quirky.version.txt) tethering only works, when started with `strace darktable`
- [gphoto2.version.txt](https://github.com/darktable-org/darktable/files/5377966/gphoto2.version.txt)
 - The issue prevails, when the configuration directory `.config/darktable` is removed

**Comment by TurboGit** [comment]
A lot of work has been done in this area for the coming 3.4 and hopefully this will be fixed.
