### ISSUE TITLE
Need Portable version for  windows platform

### ISSUE THREAD

**Issue by jiabaoyu** [darktable-org/darktable#6527]
Since DarkTable 2.4.4, there's no ZIP version for windows platform. For guys who has several machines in office and/or home studio syncing all the application configuration with cloud storage is pretty popular. I wonder why there's no portable versions anymore?
BTW, you're doing very good jobs! Thanks for you guys making such fantastic app!

**Comment by TurboGit** [comment]
Are you volunteering to do it ? The missing man power is the only reason ! Remember that dt is made by volunteers on their free time and there not much dev on Windows, so a zip which is certainly not a high priority has little chance to be done.

**Comment by jiabaoyu** [comment]
> Are you volunteering to do it ? The missing man power is the only reason ! Remember that dt is made by volunteers on their free time and there not much dev on Windows, so a zip which is certainly not a high priority has little chance to be done.

Sry, Im no dev guy. If It's not that hard, with some instructions, I could try to help :)
