### ISSUE TITLE
[duplicate manager] does not copy white balance

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6528]
**Describe the bug**

Duplicate does not copy white balance setting any more 

**To Reproduce**
1. Go to darkroom
2. chose a picture with custom set white balance
3. click on duplicate in _duplicate manager_

**Expected behavior**
exact copy of the pixle pipe

**bisect**

bisect gave me:
```
73d835900957d32a02040d3c1ba0750847bb2064 is the first bad commit
commit 73d835900957d32a02040d3c1ba0750847bb2064
Author: Pascal Obry <pascal@obry.net>
Date:   Tue Oct 13 23:11:43 2020 +0200

    Add some more IOP_FLAGS_UNSAFE_COPY flags.
    
    Continued work for #6502.

 src/iop/flip.c         | 3 ++-
 src/iop/lens.cc        | 3 ++-
 src/iop/rotatepixels.c | 3 ++-
 src/iop/scalepixels.c  | 3 ++-
 src/iop/temperature.c  | 2 +-
 5 files changed, 9 insertions(+), 5 deletions(-)
```

@TurboGit may I ping you directly here :)

**Platform & Additional context**
* darktable version : 3.3.0+1085~g7a637e6f6
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by TurboGit** [comment]
Looks like this is for me :)

**Comment by AxelG-DE** [comment]
Actually it does copy the WB but changes to "as shot". When you then go into WB and click on _user modified_ it will give you the stored value

**Comment by AxelG-DE** [comment]
Works thanks!
