### ISSUE TITLE
export with max size: previous instead of actual value is applied when using presets

### ISSUE THREAD

**Issue by rkowalke** [darktable-org/darktable#6531]
**Describe the bug**
Selecting a preset in the export module does not apply the associated max (pixel) size values as shown in the input fields. Instead the previously user-entered value is applied (although not shown in the input fields).

**To Reproduce**
1. Define two presets in the export module
2. Preset A: max pixel size 0 x 0 (unlimited)
3. Preset B: max pixel size 100 x 100 
4. Export an image using preset A: it has a false size of 100 x 100 
5. Export an image using preset B: it has a size of 100 x 100
6. Change max pixel size to 200 x 200 in the UI only (**do not save it**)
7. Select one of the other presets A or B and export an image: it has a size of 200 x 200

**Expected behavior**
The pixel size should be consistent between UI input field and exported size. Presets values should be applied immediately when selecting another preset.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1085~g7a637e6f6 (current master)
 - OS: Linux tulkas 5.8.11-1-MANJARO
 - OpenCL activated YES
 - GeForce GTX 750 Ti

**Additional context**
- Although the pixel sizes are visibly updated in the UI, their values are *not* applied on the exported image.
- The size of the exported image is always the values of the last time that the user changed in the UI input fields 
- Restarting darktable does not help
- As a workaround you can overwrite the values in the UI after switching the preset. This will trigger an update of the internal state and export size will be correct

***OpenCL***
0.437046 [opencl_init] OpenCL successfully initialized.
0.437047 [opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
0.437049 [opencl_init]          0       'GeForce GTX 750 Ti'
0.437051 [opencl_init] FINALLY: opencl is AVAILABLE on this system.
0.437052 [opencl_init] initial status of opencl enabled flag is ON.
0.437250 [opencl_priorities] these are your device priorities:
0.437252 [opencl_priorities]            image   preview export  thumbs  preview2
0.437256 [opencl_priorities]            0       0       0       0       0
0.437260 [opencl_priorities] show if opencl use is mandatory for a given pixelpipe:
0.437262 [opencl_priorities]            image   preview export  thumbs  preview2
0.437266 [opencl_priorities]            1       1       1       1       1

***Export using preset A***
194,533728 [pixelpipe_process] [export] using device 0
194,688696 [opencl_resampling] resampling plan cannot efficiently be run on the GPU - fall back to CPU.
194,688732 [opencl_resampling] couldn't enqueue kernel! -999
194,748411 [opencl_demosaic] couldn't enqueue kernel! -999
194,748425 [opencl_pixelpipe] could not run module 'demosaic' on gpu. falling back to cpu path
[export_job] exported to `/home/rene/Bilder/Export/test/A.jpg'

***Export using preset B***
315,086467 [pixelpipe_process] [export] using device 0
315,244542 [opencl_resampling] resampling plan cannot efficiently be run on the GPU - fall back to CPU.
315,244589 [opencl_resampling] couldn't enqueue kernel! -999
315,304346 [opencl_demosaic] couldn't enqueue kernel! -999
315,304379 [opencl_pixelpipe] could not run module 'demosaic' on gpu. falling back to cpu path
[export_job] exported to `/home/rene/Bilder/Export/test/B.jpg'

***Export using preset A AND overwriting size values***
1094,625018 [pixelpipe_process] [export] using device 0
1095,031773 [default_process_tiling_cl_ptp] use tiling on module 'denoiseprofile' for image with full size 6055 x 4035
1095,031807 [default_process_tiling_cl_ptp] (2 x 1) tiles with max dimensions 5204 x 4035 and overlap 10
1095,031810 [default_process_tiling_cl_ptp] tile (0, 0) with 5204 x 4035 at origin [0, 0]
1101,843440 [default_process_tiling_cl_ptp] tile (1, 0) with 871 x 4035 at origin [5184, 0]
1102,936507 [default_process_tiling_cl_roi] use tiling on module 'lens' for image with full input size 6055 x 4035
1102,936521 [default_process_tiling_cl_roi] (2 x 1) tiles with max input dimensions 3851 x 4039
1102,937786 [default_process_tiling_cl_roi] tile (0, 0) with 3036 x 4035 at origin [3, 1]
1103,283547 [default_process_tiling_cl_roi] tile (1, 0) with 3038 x 4035 at origin [3020, 1]
1103,822989 [default_process_tiling_cl_ptp] use tiling on module 'atrous' for image with full size 6063 x 4039
1103,823002 [default_process_tiling_cl_ptp] (5 x 1) tiles with max dimensions 2360 x 4039 and overlap 512
1103,823005 [default_process_tiling_cl_ptp] tile (0, 0) with 2360 x 4039 at origin [0, 0]
1104,248769 [default_process_tiling_cl_ptp] tile (1, 0) with 2360 x 4039 at origin [1336, 0]
1104,657689 [default_process_tiling_cl_ptp] tile (2, 0) with 2360 x 4039 at origin [2672, 0]
1105,066246 [default_process_tiling_cl_ptp] tile (3, 0) with 2055 x 4039 at origin [4008, 0]
[export_job] exported to `/home/rene/Bilder/Export/test/A.jpg'

**Comment by TurboGit** [comment]
Fixed ! Thanks for reporting.
