### ISSUE TITLE
unable to build current git - whereami.c missing

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#6534]
**Describe the bug**
Downloaded latest git (3a42bcc8e).  Failed to build with the error below.

**To Reproduce**
1. ./build.sh --prefix <wherever>
2. Error produced

```
-- Configuring done
CMake Error at src/external/CMakeLists.txt:5 (add_library):
  Cannot find source file:

    /home/bill/src/darktable/darktable/src/external/whereami/src/whereami.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "whereami".
CMake Error: CMake can not determine linker language for target: whereami
-- Generating done

```
**Expected behavior**
build should succeed

**Platform (please complete the following information):**
 - Darktable Version: git master
 - OS: Ubuntu 18.04

**Additional context**
Checked out the previous commit, 7a637e6f6, and it built fine.

**Comment by parafin** [comment]
git submodule init
git submodule update

**Comment by wpferguson** [comment]
Thanks @parafin 

My build script did a submodule update and NOW it also does an init.  Perhaps something in the commit message about adding a new submodule would prevent confusion and noise.
