### ISSUE TITLE
CI: please build one variant with USE_LUA=false

### ISSUE THREAD

**Issue by mandree** [darktable-org/darktable#6539]
**Describe the bug**

https://github.com/darktable-org/darktable/pull/6538 reported a regression in a "have LUA disabled" build.
This slipped through the cracks and the build was passing in spite of a gboolean vs. stdbool.h type confusion, new code was using = true and = false initialization assignment.

Some debugging on IRC @RobbieAB and I figured that lua.h pulls in stdbool.h. Disabling Lua on my Fedora 31 x86_64 build, I could also fail the build.

Can we set up CI in a way that it goes without Lua and would catch commits such as the failure inducing 92b1798?

**To Reproduce**
1. check out 569b31911e09bb1005aeab35b4b8b0cb50f4c5a4
2. disable USE_LUA in ccmake
3. build
4. see build fail:
```
 ../src/control/jobs/control_jobs.c: In function 'dt_control_monochrome_images_job_run':
 ../src/control/jobs/control_jobs.c:606:26: error: 'false' undeclared (first use in this function)
   606 |       gboolean changed = false;
       |                          ^~~~~

```

**Expected behavior**

On commits such as 92b1798 that introduce stdbool.h "true" and "false" in lower case in assignments to a gboolean typed variable, CI should flag the build as failing.

**Screenshots**

**Platform (please complete the following information):**
mostly irrelevant, darktable 569b31911e09bb1005aeab35b4b8b0cb50f4c5a4 (master branch).

**Comment by parafin** [comment]
I think this is fixed now, closing.
