### ISSUE TITLE
[duplicate manager] does not copy masks

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6541]
**Describe the bug**

Duplicate does not copy the drawn mask (not necessarily the kind I show below but with this I bisected)

**To Reproduce**
1. Go to darktroom
2. chose a picture with drawn mask (in my case contrast equalizer)
3. click on duplicate in _duplicate manager_

**Expected behavior**

exact copy of pixlepipe

**Screenshots**

![Screenshot_20201015_230605](https://user-images.githubusercontent.com/49004103/96186285-8132a880-0f3b-11eb-83f9-5702c331a22d.png)

**bisect** 
bisect gave me:
```
879fc1d68b6f8e0f228942eb1569624c7053361b is the first bad commit
commit 879fc1d68b6f8e0f228942eb1569624c7053361b
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Oct 15 19:24:56 2020 +0200

    Filtered modules must be done only when doing a copy and not duplicate.
    
    When a duplicate is created we want all modules to be copied. In this
    case we do copy all modules, this implementation is using a new boolean
    flag full_copy. At the same time partial field is removed as not used.
    
    Fixes #6528.

 src/common/history.c            | 83 ++++++++++++++++++++++++++---------------
 src/common/history.h            |  4 +-
 src/common/image.c              |  2 +-
 src/common/styles.c             |  3 +-
 src/control/jobs/control_jobs.c |  2 +-
 src/dtgtk/thumbtable.c          |  2 +-
 src/libs/duplicate.c            |  2 +-
 7 files changed, 61 insertions(+), 37 deletions(-)
```
@TurboGit sorry Pascal, seems is you again :) and just related to what I pushed in #6528  (in German language we say "throw out the baby with emptying the bath tub") :laughing: 

**Platform**
* darktable version : 3.3.0+1086~g3f1390c19
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by TurboGit** [comment]
Will look at this tomorrow, this is very strange as I have specifically tested this scenario...

**Comment by AxelG-DE** [comment]
The photo in question has module order "legacy" as it is from 2019, maybe that helps something?
XMP needed?

**Comment by TurboGit** [comment]
No, thanks should be fixed. It was a use of a released memory chunk. That's probably why it would have been working while I was testing. Can you double check all is fine on your side now? TIA.

**Comment by AxelG-DE** [comment]
Tested, works!
Thanks a lot!
