### ISSUE TITLE
Missing icon in about dialog window since 15th october

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#6552]
Just a simple one: missing icon in about dialog windows. This is since 15th october. Commit ac58d22a1e9836459f895c93401c04608a758504 is good and commit 3165deaed7022f68a2d1c2b0d867583f4183b0a9 don't have that icon. The issue is somewhere between those commits (can't compile them without adding fix added on last cited commit.

@AlicVB and @TurboGit: most updates are from you, so maybe you will see quickly how to fix that.

**Comment by maboleth** [comment]
What icon nivus? When I open About I can see DT's rainbow aperture logo?

**Comment by AlicVB** [comment]
Yes, I've seen that, but thought it was a problem on my side...
@maboleth : it's the main app icon...

I don't think it's my fault, but I'll try to find time to bisect more precisely in the evenning

**Comment by TurboGit** [comment]
I bet it is the CMake rework to run from build directory.

**Comment by TurboGit** [comment]
So this commit : 3a42bcc8ea0a54d040fce3f1cce3725bf5abec60

**Comment by Nilvus** [comment]
Thanks for your answer and finding the issue @TurboGit. But I don't understand what you mean by "CMake rework to run from build directory" as I always remove the build directory before compile again. Do we have to do a local thing to fix it or this need a fix in darktable code?

**Comment by TurboGit** [comment]
The PR has changed lot of cmake code to be able to run darktable binaries from where it is built. (build/bin...). This requires lot of tweaking for looking at the data (in build/share...) and so all support files (as the icon) may be affected. That's why I have suspected this work to have introduced the regression. But I haven't tested... Maybe someone will confirm.

**Comment by TurboGit** [comment]
@codingdave : Maybe one for you... Can you have a look ?

**Comment by codingdave** [comment]
@Nilvus / @AlicVB  can you please explain better what is missing? Maybe add a screenshot? I don't see a regression, I might not know what to expect.

Thank you in advance.

**Comment by Nilvus** [comment]
@codingdave, see below darktable logo missing and warning icon instead (red one):

![2020-10-18_18-14](https://user-images.githubusercontent.com/45535283/96373584-cdfdc580-116d-11eb-9111-d3f91c91a6d5.png)

**Comment by codingdave** [comment]
@Nilvus which OS?

**Comment by codingdave** [comment]
And how do you open that window?

**Comment by codingdave** [comment]
latest master, I click on the dt icon top left to open the info window

![grafik](https://user-images.githubusercontent.com/3075641/96373700-7dd33300-116e-11eb-980f-8bbdd379b6bd.png)

**Comment by Nilvus** [comment]
On Linux Ubuntu 20.10 (beta, last update). It's the about dialog so I just click as you just describe. See my first post: on a commit before 15th october, I have it but no more now.

**Comment by codingdave** [comment]
what is your desktop environment system @Nilvus ? Waht is yours @AlicVB ?
Since I am also running Linux and have no issues, same as @elstoc, I have no clue what the issue might be. Any ideas?

**Comment by Nilvus** [comment]
I don't know what issue that could be. My desktop environment is Gnome 3.38

**Comment by elstoc** [comment]
@Nilvus please could you provide a before/after screenshot just so we're all 100% clear what we're talking about here

**Comment by Nilvus** [comment]
@elstoc: the before/after is already there. After is my screenshot without darktable logo icon and before @codingdave screenshot with the logo.

**Comment by elstoc** [comment]
@Nilvus sorry there was a flurry of activity and I didn't read far enough back.

**Comment by Nilvus** [comment]
No problem. Thanks for helping.

**Comment by Nilvus** [comment]
To precise: I have the darktable icon logo with commit c0951131cc7abd51266d05b85d4443fc33199ca0 and no more since your commit 3a42bcc8ea0a54d040fce3f1cce3725bf5abec60, @codingdave. And it seems that the issue is only on some system.

**Comment by codingdave** [comment]
@Nilvus thanks for adding that information. So you also have that issue when you switch to english. Did you test `3a42bcc` specifically or, like stated in the first comment above
> The issue is somewhere between those commits (can't compile them without adding fix added on last cited commit.

Also, how do you start dt? From the build/bin/ directory? Or from /path/to/installed/bin/darktable?
Please start dt from the command line and run it with `darktable -d dev`

**Comment by Nilvus** [comment]
Yes, I also have that issue when I switch in english. I even just test to switch Gnome in english and test your commit 3a42bcc and previous commit. I have the icon on previous commit yours and no icon with your commit, so in french and in english (in darktable and/or Gnome), same issue.

I start dt from /opt/darktable/bin/darktable

See below with -d dev:

![2020-10-18_19-44](https://user-images.githubusercontent.com/45535283/96375670-a103df80-117a-11eb-8f31-e0f3cf531d17.png)

**Comment by codingdave** [comment]
@Nilvus please ls `/opt/darktable/share/darktable/pixmaps`

**Comment by codingdave** [comment]
@Nilvus also is anything written on the console that looks suspicious when opening the info window?

**Comment by Nilvus** [comment]
![2020-10-18_19-50](https://user-images.githubusercontent.com/45535283/96375757-2f786100-117b-11eb-9e1b-3fbd509845c5.png)

Nothing on terminal when launching the info window (screenshot with -d dev include launching darktable and opening the info window)

**Comment by AlicVB** [comment]
For, it's the same as @Nilvus . gtk 3.24 and xfce 4.14
I can add that my xfce panel which show me all open windows doesn't show darktable icon for dt...
Just ask if you want more infos !

**Comment by parafin** [comment]
These icons are in /opt/darktable/share/icons, not pixmaps. Please show ls -R /opt/darktable/share/icons

**Comment by parafin** [comment]
The problem is with XDG_DATA_DIRS - it should be /opt/darktable/share, not /opt/darktable/share/darktable. There is even a comment that wrong XDG_DATA_DIRS has this effect. Only people who install into non-system location (e.g. /opt/darktable) are affected.

**Comment by parafin** [comment]
@codingdave, you made DARKTABLE_SHAREDIR the same as DARKTABLE_DATADIR, while the weren't before. Only DARKTABLE_DATADIR has /darktable suffix at the end.

**Comment by Nilvus** [comment]
@parafin: reading your last 2 comments, It seems that showing ls -R /opt/darktable/share/icons is no more necessary.

**Comment by parafin** [comment]
I've looked at the part that installs the icons and it hasn't been changed by that commit, so I think icons are there.

**Comment by Nilvus** [comment]
> I've looked at the part that installs the icons and it hasn't been changed by that commit, so I think icons are there.

And you're right, icons are there.

**Comment by codingdave** [comment]
Thanks @parafin, so if I understand you correctly this will do?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0503deb83..4386d2ed8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -48,12 +48,13 @@ include(FeatureSummary)
 get_filename_component(CMAKE_INSTALL_BINDIR_ABS "${CMAKE_INSTALL_FULL_BINDIR}" REALPATH "${CMAKE_INSTALL_PREFIX}")
 # get relative pathes specific to the system
 file(RELATIVE_PATH REL_BIN_TO_LIBDIR    ${CMAKE_INSTALL_FULL_BINDIR} "${CMAKE_INSTALL_FULL_LIBDIR}/darktable")
-file(RELATIVE_PATH REL_BIN_TO_DATADIR   ${CMAKE_INSTALL_FULL_BINDIR} "${CMAKE_INSTALL_FULL_DATADIR}/darktable")
+file(RELATIVE_PATH REL_BIN_TO_SHAREDIR  ${CMAKE_INSTALL_FULL_BINDIR} "${CMAKE_INSTALL_FULL_DATADIR}")
 file(RELATIVE_PATH REL_BIN_TO_LOCALEDIR ${CMAKE_INSTALL_FULL_BINDIR} "${CMAKE_INSTALL_FULL_LOCALEDIR}")
+set(REL_BIN_TO_DATADIR  "${REL_BIN_TO_SHAREDIR}/darktable")
 set(DARKTABLE_BINDIR    "${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}")
 set(DARKTABLE_LIBDIR    "${DARKTABLE_BINDIR}/${REL_BIN_TO_LIBDIR}")
-set(DARKTABLE_DATADIR   "${DARKTABLE_BINDIR}/${REL_BIN_TO_DATADIR}") # DATAROOTDIR == DATADIR == SHAREDIR # darktablerc, themes, icons, ... Cannot use ${CMAKE_BINDIR}/data because not everything resides there. Like icons (pixmaps)
-set(DARKTABLE_SHAREDIR  "${DARKTABLE_DATADIR}") # DATAROOTDIR == DATADIR == SHAREDIR
+set(DARKTABLE_SHAREDIR  "${DARKTABLE_BINDIR}/${REL_BIN_TO_SHAREDIR}")
+set(DARKTABLE_DATADIR   "${DARKTABLE_BINDIR}/${REL_BIN_TO_DATADIR}") # DATAROOTDIR == DATADIR # darktablerc, themes, icons, ... Cannot use ${CMAKE_BINDIR}/data because not everything resides there. Like icons (pixmaps)
 set(DARKTABLE_LOCALEDIR "${DARKTABLE_BINDIR}/${REL_BIN_TO_LOCALEDIR}")
```

**Comment by codingdave** [comment]
@Nilvus, @AlicVB, can you please test that?
