### ISSUE TITLE
Module list shown when no group is selected does not depend on the preset

### ISSUE THREAD

**Issue by hlecleme** [darktable-org/darktable#6555]
With darktable 3.2.1, when unselecting the active group (such that no group is selected), the modules that are visible are those that are active or favorite. It looks like it is somewhat different with revision 722508b1cfd9c8f30cbab499481bf64e9152f3f9 of master: with all presets the same module list is shown. Is this the expected (new) behavior?

**To Reproduce**
1. Start `darktable --conf plugins/darkroom/workflow=none` with an empty config directory
2. Import a raw image and open it with darkroom
3. Select the "Scene referred" preset (of the module groups)
4. Click on the "base" tab and see that "filmic rgb" is present in the list of modules (but not enabled)
5. Click on the "show only active modules tab": it shows all the enabled modules
6. Click on the "show only active modules tab" again: it becomes unselected and it shows the "base curve" module but not the "filmic rgb" module.

**Expected behavior**
Only the enabled modules and the modules selected by the preset should be shown: e.g. "base curve" should not be visible, and "filmic rgb" should be.

**Platform**
 - Darktable Version: 722508b1cfd9c8f30cbab499481bf64e9152f3f9, local build with CMAKE_BUILD_TYPE=RelWithDebInfo, gcc 7.5.0
 - OS: Ubuntu 18.04
 - Same behavior with and without OpenCL

**First analysis**
In function `_lib_modulegroups_update_iop_visibility` of `libs/modulegroups.c` with `d->current == DT_MODULEGROUP_NONE`, the `module->so->state` is used to determine whether to show the module. The `module->so->state` is initialized from the `plugins/darkroom/%s/visible` and `plugins/darkroom/%s/favorite` configuration parameters in function `dt_iop_load_module_by_so` of `develop/imageop.c` and it seems that no calls to `dt_iop_gui_set_state` or `dt_iop_so_gui_set_state` to update the module state are done when selecting a new module group preset. The "base curve" is shown because it is "DEFAULT_VISIBLE" in `src/iop/CMakeLists.txt`.

**Comment by AlicVB** [comment]
@hlecleme : can you test PR #6560 ? it should fix the issue.
Thanks for the report

**Comment by dterrahe** [comment]
Thanks!

That fixes it for me; I expected clicking on the  "show only active modules" tab twice to show _all_ modules, which it does now.

From the bug report above, I think that @hlecleme expects a shorter list, namely only the selection from the preset (plus enabled) but across all groups.

I think both are reasonable expectations...

**Comment by AlicVB** [comment]
@dterrahe : it should behaves now as before (3.2.1) : show all modules *present in defined groups* plus the enabled ones.
example : the list should be shorter with "minimal" preset than with "all modules" one.

This isn't what you have ?

**Comment by hlecleme** [comment]
PR #6560 works for me.
Thanks for the quick fix!

@dterrahe Indeed, I expected a list of modules limited to those selected by the preset and that is what the fix is giving. E.g. with the "Scene referred" preset I don't see "base curve" in the list.

**Comment by dterrahe** [comment]
Ah, yes. I assumed that "default" would be shorter than "all modules", but it is just a different grouping. With minimal it is indeed shorter.

Works for me, thanks!
