### ISSUE TITLE
map markers shown even if no photo in darktable

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6557]
I have no photo in darktable 3.2.1, and, unexpectedly, going to the map view some marker is shown on map.

![nofoto](https://user-images.githubusercontent.com/1417508/96338087-00cf8d00-108c-11eb-9854-74cd6a5caf32.png)

I recognize that the markers refer to some preview photo I have edited and then removed from the lighttable.

There is no way to make them desappear.

**Comment by ptilopteri** [comment]
I am guessing but it appears you have images in your library that
do not exist in the location the library contains.  There are several 
scripts distributed with the darktable package, one that probably will
solve your concerns,
    /usr/share/darktable/tools/purge_non_existing_images.sh

if you are on windows, I do not know the location of this script.

if this solves your concerns, please close the issue.
