### ISSUE TITLE
Print multiples files/formats on a sheet of paper.

### ISSUE THREAD

**Issue by elperepat** [darktable-org/darktable#6562]
**Is your feature request related to a problem? Please describe.**
I do school photo shoots.
Parents like to choose different photos formats and also often want to choose more than one photo from the shoot.
When I print, I want to reduce my costs, so I try to place as much photos as I can on a sheet of paper.

**Describe the solution you'd like**
My workflow in lightroom is:
* Select paper size
* Place images frames of the correct sizes on that sheet. Add additional sheet if needed to fit all images ordered by a client. You can rotate the frames to fit even more on the page.
* Drag/drop images from the filmstrip to the correct frames on the sheet. If the frame was rotated, the image is rotated to fit. If the aspect ratio of the frame isn't the one of the image, you can drag the image in the frame to crop correctly. All copies of that image/format crop are re-cropped automatically.
* Print!

**Alternatives**
You can export the images in gimp and place them on a canvas. Scaling is complicated, as is cropping. I would prefer to do all this in a single program. In darkroom, it would be easy to change my mind and choose an other image. Just drag/drop a new one in a frame.

**Additional context**
https://i.ytimg.com/vi/9u4ybk_8mKs/maxresdefault.jpg
https://youtu.be/RgAJc7U6uFA?t=361

**Comment by matt-maguire** [comment]
Digikam allows you to print multiple photos on a page, it could be worth looking at using that to manage your exported photos.

**Comment by elperepat** [comment]
Yes for multiple photos, but it doesn't seem possible to mix multiple sizes on same page.

**Comment by matt-maguire** [comment]
The requirement to place different size images on the same page wasn't quite clear to me. This would require some sort of layout editor I guess?

**Comment by elperepat** [comment]
Have you checked the youtube video in **Additional context**? This is what I'd like: Easy, on the fly and sort of a preview of the sheet as it will get printed.

I do like lightroom, but I want to ditch windows completely and this issue is kind of the last snag keeping me from doing so.

**Comment by TurboGit** [comment]
Would be a nice project ! But will need quite a bit of investment on darktable development as I don't feel this to be an easy one :) But certainly if such project is started I'll be ready to answer questions and help integrating this.

**Comment by TurboGit** [comment]
And of course all this must be done in the print module.

**Comment by TurboGit** [comment]
This has been implemented in 3.8.
