### ISSUE TITLE
Windows build fails with current master (96726f7cc

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#6563]
**Describe the bug**
Windows build fails
```
...
CMake Error at src/external/CMakeLists.txt:5 (add_library):
  Cannot find source file:

    C:/msys64/home/lintujuh/darktable/src/external/whereami/src/whereami.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/external/CMakeLists.txt:5 (add_library):
  No SOURCES given to target: whereami


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**To Reproduce**
1. Clear build directory
2. Execute `cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/darktable ../.`
3. See error

**Platform (please complete the following information):**
 - Darktable Version: Git master
 - OS: Windows 10

**Additional context**
I did `git clean -d -f -x ; git pull --rebase --recurse-submodules`; still the same ### error)

**Comment by ptilopteri** [comment]
you need to do:
    git submodule init ;git submodule update

**Comment by ptilopteri** [comment]
andi if that solves your issue, please close this issue.

**Comment by juhavlintula** [comment]
Thank you! That fixed it.
