### ISSUE TITLE
[masks] crash while adjusting brush mask control point

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#6567]
**Describe the bug**

Created a brush in retouch, and was adjusting its control points to straighten out the line when darktable crashed.  This has happened several times this weekend, both with a late-August version and this morning's git master (3.3.0+1130~g96726f7cc), but it's intermittent.

**To Reproduce**
Open the retouch iop and add a brush, trying for a long straight line but with a jittery mouse (I was using a touchpad).  Remove some extraneous interior control points with right clicks, then drag one of the two end control points.  If no crash, create another brush and repeat.  darktable will probably crash within five or six tries.

**Expected behavior**

The shape should be modified without crashing darktable.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1130~g96726f7cc
 - OS: Mageia Linux
 - no OpenCL

**Additional context**
Backtrace says the crash was in develop/masks/brush.c, line 1952.  The code there is
```
   dt_masks_point_brush_t *point
        = (dt_masks_point_brush_t *)g_list_nth_data(form->points, gui->feather_dragging); 

    int p1x, p1y, p2x, p2y;
    _brush_feather_to_ctrl(point->corner[0] * darktable.develop->preview_pipe->iwidth, 
                           point->corner[1] * darktable.develop->preview_pipe->iheight, pts[0], pts[1], &p1x,  
                           &p1y, &p2x, &p2y, TRUE); 
```
and I was able to verify that the crash resulted from the g_list_nth_data returning NULL, which then led to a null-dereference when trying to read point->corner.

git blame says that this code has been present since 2014, but I didn't find any other reports of brush-related crashes.

**Comment by TurboGit** [comment]
Tried 5 times, no crash :( Can you reproduce this also with some other modules ? Brush on exposure module for example ?

**Comment by TurboGit** [comment]
Maybe your are using a very specific set of actions ? Do you move segments ? Do you change the size of the feather ? Any other precision to help reproduce ? I could just clamp the value to ensure feather_dragging is not above the number of element in the list (form->points) as a defensive code to avoid the crash.

**Comment by wpferguson** [comment]
I managed to recreate it.  I drew a line with lots of movement, then deleted a few nodes, moved the end, over and over.  3rd or 4th time it crashed.  develop/masks/brush.c:1953

[darktable_bt_8UZJS0.txt](https://github.com/darktable-org/darktable/files/5398329/darktable_bt_8UZJS0.txt)


git 96726f7cc

**Comment by TurboGit** [comment]
What I don't understand is that it crashes into the feather dragging code which is the control point to change the orientation of the spline. But in the procedure you report this is no done...

**Comment by ralfbrown** [comment]
Just verified why it's being called: unlike interior points, moving an end point changes the orientation of the spline control point with respect to the nodal point.  The line segment between node and spline control seems to always be kept exactly perpendicular to the direct line between the end node and the next node.  Which makes sense since we don't want weird bends at the ends.

**Comment by TurboGit** [comment]
Yes, got a crash too with this reproducer... Thanks a lot!

**Comment by TurboGit** [comment]
Simpler:
- draw a brush line (any module)
- select last point, move it
- delete an inner node
- grab and move first point

**Comment by TurboGit** [comment]
Should be fixed.

**Comment by ralfbrown** [comment]
Haven't been able to provoke a crash with the revised version, so I agree that it's fixed.
