### ISSUE TITLE
Ignoring "allow upscaling" (?)

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#6568]
If "allow upscaling"  set to “yes” darktable not performing an upscaling step in case the user defined maximum width and height exceed the original dimensions. The exported image's dimensions not exceeding the original ones (after or without cropping). 

Is this how it should be and something I did not understand?

**Comment by TurboGit** [comment]
No, it is not supposed to work this way. The image should have at the end the size request by user even if it is originally smaller.

**Comment by TurboGit** [comment]
And this works on my side ! Can you double check ?

**Comment by esq4** [comment]
I checked it again. Addition: one of the dimensions must be 0.

**Comment by esq4** [comment]
Found where, but did not figure out how to fix it.
```
  if(dt_dev_distort_backtransform_plus(&dev, &pipe, 0.f, DT_DEV_TRANSFORM_DIR_ALL, origin, 1))
  {
    if((width == 0) && exact_size)
      width = pipe.processed_width;
    if((height == 0) && exact_size)
      height = pipe.processed_height;

>     scale = fmin(width >  0 ? fmin((double)width / (double)pipe.processed_width, max_scale) : max_scale,
>                  height > 0 ? fmin((double)height / (double)pipe.processed_height, max_scale) : max_scale);

```

**Comment by TurboGit** [comment]
That's not a bug then. A 0 means 'image size' so '0 x 100000' even with upscale = TRUE won't create a image having a width of 100000.

**Comment by esq4** [comment]
I understood the math. I don't understand the logic of the UI.
For example, I want to limit the width of an image. So what difference does it make if it is larger or smaller than the original? Why is it enough to set one size for cropping, and both are necessary for enlargement? Not unambiguous ...
Maybe it makes sense to make these settings the same for both cases?

**Comment by esq4** [comment]
It may be better to give the combination "larger_maximum_size x 0" the same meaning as "smaller_maximum_size x 0" and not to force the user to do unnecessary work?

**Comment by TurboGit** [comment]
>  Why is it enough to set one size for cropping, and both are necessary for enlargement? Not unambiguous ...

I get your point and agree, if we can do better let's go for it.

**Comment by parafin** [comment]
Right now 0 basically mean "original picture size" if I understand correctly the logic. It can be re-defined to mean "other export dimension * picture aspect ratio", then it will work for enlargement too without breaking no-upscale case. 0x0 though still has to be defined as a special case of "original picture size".

**Comment by esq4** [comment]
```
  if(dt_dev_distort_backtransform_plus(&dev, &pipe, 0.f, DT_DEV_TRANSFORM_DIR_ALL, origin, 1))
  {
>    if((width == 0) && exact_size)
>      width = pipe.processed_width;
>    if((height == 0) && exact_size)
>      height = pipe.processed_height;

    scale = fmin(width >  0 ? fmin((double)width / (double)pipe.processed_width, max_scale) : max_scale,
                 height > 0 ? fmin((double)height / (double)pipe.processed_height, max_scale) : max_scale);
```

I didn't understand the purpose of marked substitutions, but after removing them, everything that I could guess to test works.
