### ISSUE TITLE
Unhandled error execption prevents restarting Datktable (opens and closes after displaying unhandled error popup)

### ISSUE THREAD

**Issue by Pol1968** [darktable-org/darktable#6571]
Not sure about what the issue is, but it seems to me it occured after I hit several times the space bar to move to next photo in the dark table while I was on the last pic.
Error popup showed and Darktable closed.
Since then popup systematically shows at start time and Darktable crashes.

Darktable version : 3.2.1
OS ; Windows 10 family, version 1909, build 18363.1082
[darktable_bt_WZQPS0.txt](https://github.com/darktable-org/darktable/files/5398029/darktable_bt_WZQPS0.txt)
[darktable_bt_Q7ZAS0.txt](https://github.com/darktable-org/darktable/files/5398030/darktable_bt_Q7ZAS0.txt)

**Comment by TurboGit** [comment]
Not enough information in backtrace. If enabled try disabling OpenCL.

**Comment by johnny-bit** [comment]
Try with empty config directory. It looks as if you have one file with damaged pixelpipe params in db/xmp and darktable crashes while trying to open it.

**Comment by johnny-bit** [comment]
understood: unclear, no new info. closing.

please post the information we asked about and I'll re-open the issue for further investigation.
