### ISSUE TITLE
How are userdefined shortcuts supposed to work?

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6573]
How are userdefined shortcuts supposed to work?

I have setup the following
![image](https://user-images.githubusercontent.com/1119439/96415895-dbb65800-120c-11eb-9052-096fd0fab5a9.png)

The idea is one preset for export applies a style which removes frames.

So I created a shortcut Ctrl+M to show me the menu to select any preset.
I created a shortcut specific to the no frame preset so that I can export somehow using the preset.

I press the shortcuts in darkroom (when I am on an image that I want to export) and lightable (by selecting an image) but not seeing the preset change or ask me for a selection. 

Pretty sure I don't understand how to invoke the shortcuts.

Also can we have the ability to have more than 2 keystrokes for shortcut? My initial idea was to use CTRL+E + <another letter> for export related shortcuts, but it takes the first 3.

**Comment by chhil** [comment]
Can someone respond to this?

**Comment by matt-maguire** [comment]
Looks to me like using a shortcut to "show preset menu" is broken, so I'd say this is a bug.

**Comment by matt-maguire** [comment]
I just verified that the PR #6598 does indeed fix the ability to call up preset menus via shortcut key.

**Comment by junkyardsparkle** [comment]
> As far as I understand it this is a Gtk limitation and is fairly standard, though I agree it would be nice to be able to use those sorts of combinations.

Back in the day, this wouldn't have worked well with the way keyboards scanned for keypresses; there are some character keys that didn't register if certain other ones were already being pressed. Gaming keyboards are specifically designed to not have this issue, but it may still affect many keyboards currently in use.

**Comment by chhil** [comment]
Thank you all for looking into this and fixing it.

**Comment by chhil** [comment]
@elstoc 
Just tried this out.

For the export shortcuts set up in the OP (**ctrl+m**: show preset menu and **alt +n**: set preset to a specific one, I can only use them from lightable. In darkroom those shortcuts don't work.

So I am in darkroom, edited a pic and plan to export image. I want to either change the preset using the preset popup or setting the exact value using another shortcut. My use case is to export the image using 2 different export presets. If short cuts were to work, I wouldn't need to go to lighttable every time. 

Just as ctrl+e works in both lightable and darkroom, my short cuts only work in lightroom.

Is this expected behavior?

**Comment by elstoc** [comment]
> Is this expected behavior?

If a module isn't present in the darkroom view you can't use its shortcuts in that view. `Ctrl+E` is an exception for the export module only. So yes, this is expected behaviour.

**Comment by chhil** [comment]
@elstoc 
It would be nice if the non gui ones would work from any view. So preset popup is understandable, but changing a preset through a short cut should be allowed to make a user's life easy.

Are shortcuts unique across the system or are they supposed to be unique across the 4 categories?
![image](https://user-images.githubusercontent.com/1119439/96978632-31a43c00-153c-11eb-92eb-a22a055ae24c.png)


Another thing I noticed; you cannot reset a shortcut.
I define a shortcut
![image](https://user-images.githubusercontent.com/1119439/96978765-5b5d6300-153c-11eb-877f-eb3e4321ac63.png)

I double click it to reset.  The text become press key combination to remap.
No image here as the image taking shortcut gets registered :).

Then I focus on another entry and the rest value gets displayed again.
![image](https://user-images.githubusercontent.com/1119439/96978890-7d56e580-153c-11eb-8edc-550cb6eaf712.png)



One more thing I noticed while taking a snapshot after resetting the entry using shortcut keys for the snapshot app Win+shift+S
The keys get translated to Meta+L 
![image](https://user-images.githubusercontent.com/1119439/96982192-71b7ee80-153d-11eb-8913-3b485baa7dff.png)

**Comment by elstoc** [comment]
> It would be nice if the non gui ones would work from any view

You can raise a separate feature request but it might not be possible

> Are shortcuts unique across the system or are they supposed to be unique across the 4 categories?

They are unique to each view. If a module exists across multiple views, then the keyboard shortcut will work on all of those views and you will not be able to allocate the same shortcut to any other operation on any of those views.

> Another thing I noticed; you cannot reset a shortcut.

Don't double-click. Just single click and press backspace.

> resetting the entry using shortcut keys for the snapshot app Win+shift+S The keys get translated to Meta+L

I'm not sure you can use the Windows key as a modifier.

**Comment by chhil** [comment]
> You can raise a separate feature request but it might not be possible
I will create an NFR and see where it goes.

>Don't double-click. Just single click and press backspace.
Aah, this behavior is different from the regular double click to reset to default value. But there is functionality of a double click that causes it to reset the string but on losing focus it comes back. So it does try to reset, but full functionality is not there.

> I'm not sure you can use the Windows key (otherwise known as the Meta key) as a modifier.
Maybe document it somewhere if it's not there already.

**Comment by junkyardsparkle** [comment]
> Don't double-click. Just single click and press backspace.

Neat. I never managed to figure that out, either

> I'm not sure you can use the Windows key (otherwise known as the Meta key) as a modifier.

If you really need to for some reason, you can map it directly in keyboardrc (on my Linux system `<Super>` works), but there are fairly good reasons not to use this modifier as an accel within applications in most desktop environments. The idea with not allowing it via the GUI by default is probably to encourage this convention, I guess. There's some discussion around this [here](https://phabricator.kde.org/T11520).
