### ISSUE TITLE
Bug when I try to open a Raw file with extension .orf

### ISSUE THREAD

**Issue by GTREPAT** [darktable-org/darktable#6580]
**Describe the bug**

** To Reproduce**

[PA040011.zip](https://github.com/darktable-org/darktable/files/5404498/PA040011.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/73139372/96508406-d2ec7300-125a-11eb-9089-dce1ba4af684.png)

**Platform (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by matt-maguire** [comment]
This camera model is not currently supported in darktable. There is a sample image on raw-pixls.us that can be used to add this support.

**Comment by junkyardsparkle** [comment]
Duplicates #6569
