### ISSUE TITLE
documentation: basic adjustments

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#6583]
I just notice that basic adjustments module has currently no entry in the docs... With the "classic" documentation, we should imo mention the limitations of this module and why.

**Comment by elstoc** [comment]
While the two documentation projects are running in parallel, you could take some content from dtdocs if you like. 

https://elstoc.github.io/dtdocs/module-reference/processing-modules/basic-adjustments/

**Comment by johnny-bit** [comment]
With "classic" documentation going bye bye with #7335 there's no point in keeping this issue open, right?

**Comment by elstoc** [comment]
Right

**Comment by TurboGit** [comment]
Right !

**Comment by johnny-bit** [comment]
Right...
