### ISSUE TITLE
Unexpected crash at opening

### ISSUE THREAD

**Issue by photomn** [darktable-org/darktable#6585]
Hello,
whenever I try to open darktable on my laptop it crashes. I try to open it from the Start menu and it doesn't start and I try to open a raw file (CR2) or an XML but it crashes. 
I have no screenshot, as the program doesn't start at all.
Here are the specs of my system:
Darktable version 3.2.1
OS: Windows 10 Home 64bit
I don't know if OpenCL is activated or not
CPU: Intel Celeron n4000 1.10
GPU: Intel UHD 600
I tried to open an old version of darktable but it didn't work. I also tried to delete data.db.lock and library.db.lock.
Here below there's the bug report.
[darktable_bt_QOEMS0.txt](https://github.com/darktable-org/darktable/files/5409946/darktable_bt_QOEMS0.txt)
Hope someone can help me, as the program is great and I already use it on OSX without problem (3.0.1).
Thanks

**Comment by parafin** [comment]
It's a bug in video drivers, you should disable OpenCL. It was reported multiple times, so search the list of issues to get more information. Closing as duplicate.
