### ISSUE TITLE
Automatic exposure control targeting exposure value (e.g. 18%)

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6588]
Darktable currently provides two ways to support exposure adjustments based on the image contents:
- manual exposure, where one can provide a clipping percentage;
- automatic exposure, where the user inputs the desired exposure value (such as -4EV) and a percentile to target.

Neither of those modes is very useful with the scene-referred workflow, requiring one to set exposure correctly for mid-grey.

**Describe the solution you'd like**
It'd be nice to have a picker that could be used to select an area of the screen, and automatically adjust exposure to set it at 18% (e.g. the clear sky is often quoted as a potential metering target, one example is https://cinematography.com/index.php?/topic/71737-exposing-sky-with-incidental-light-meter-on-film/). Even better, if an additional slider could be used to specify the target exposure (e.g. in 1/3 EV steps), one could place scene elements at pre-determined  brightness levels (light skin is often said to be around +2/3 - 1 EV above mid-grey (see e.g. https://www.canon.com.hk/en/club/article/itemDetail.do?itemId=10400 or https://petapixel.com/2012/06/06/use-your-hand-as-a-makeshift-gray-card-for-estimating-exposure/); though as only 18% is kept in place by filmic, this may be less useful). 

**Alternatives**
Currently, one can create a live sample patch in LAB / mean mode, adjust exposure manually to set it to 50%.

**Comment by mbaz** [comment]
As a new darktable user, I was thinking along these lines, but with a different interface. The interface I came up would work like this:

* included in the exposure module
* similar to the clipping indicators (red/blue colors as an overlay on the image), but showing the pixels that are at 18%
* maybe with a slider for the range (e.g. to see pixels between, say, 17% and 18%).

I think such an interface would be very helpful to "anchor" the midpoint in the photograph, and would produce optimal input for subsequent Filmic RGB processing.
