### ISSUE TITLE
contrast equalizer messing with muted tones after applying preset.

### ISSUE THREAD

**Issue by ThijmenGeurtsen** [darktable-org/darktable#6597]
**Describe the bug**
If a preset makes the tones muted in an image, the contrast equalizer will ignore this and make the under exposed parts black.

**To Reproduce**
1. Create a preset with a tone curve that makes black tones muted.
2. Apply the preset to a new image.
3. Open the image 
4. Enable contrast equalizer and set it to coarse, clarity or bloom.

**Expected behaviour**
I would like to see that the contrast equalizer doesn't ignore the muted tone and makes the image black in spots which are underexposed with the image after I applied a preset which makes the tones muted.

**Platform (please complete the following information):**
Tested on: Windows 10 and linux mint both run on the newest version of darktable.

**Comment by MStraeten** [comment]
Works as designed: 
tone curve comes later in the pixel pipe than contrast equalizer (its above it in the right side module list). So it simply doesn’t know about changes that will be applied later in the pipe.
Have a look at https://elstoc.github.io/dtdocs/darkroom/processing-modules-and-pixelpipe/
You can move the contrast equalizer module ctrl+shift+drag above tone curve

**Comment by johnny-bit** [comment]
Works as intended. Also - you can read new manual in https://www.darktable.org/usermanual/en/ :)
