### ISSUE TITLE
buttons in preferences dialog shortcuts section misses some margin

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6600]
**Describe the bug**
buttons in preferences dialog shortcuts section misses some margin

**To Reproduce**
- Open preferences
- See bottom right the buttons are all grouped

**Expected behavior**
Would be better to have some margin

**Screenshots**
![image](https://user-images.githubusercontent.com/467069/96846458-3b517500-1452-11eb-85ad-7f40d8e65e87.png)

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/debian

**Comment by TurboGit** [comment]
@Nilvus : Would you mind to have a look ? We are probably missing a little CSS rule. TIA.

**Comment by Nilvus** [comment]
This issue has been introduced by #6437 PR. PR #6607 fixes it.
