### ISSUE TITLE
Tone Equalizer with eigf causes weird artifacts when zoomed in and sometimes crashes when zooming out

### ISSUE THREAD

**Issue by Nipsi** [darktable-org/darktable#6605]
**Describe the bug**

When using the new eigf masking option of the tone equalizer, everything works fine when completely zoomed out. While zooming in (seems to be at zoom >30%) the image looks completely streaky, like one giant artifact, however with retained colors (see screenshot). Zooming back out or deactivating tone equalizer while zoomed in reverts to the normal image, however sometimes (rarely) darktable segfaults upon zooming out or deactivating tone equalizer.
Switching to the mask view in tone equalizer while being zoomed into the picture shows a normal mask.

Exporting the file appears to work fine, the exported JPG looks normal.

**To Reproduce**
1. Open fresh file
2. activate tone equalizer with eigf (I do not even have to change any settings)
3. Zoom into the image (appears to start if zoomed to more than 30%)
4. Image is one big artifact
5. zooming back out or deactivating tone equalizer sometimes (not always) segfaults with error message:
```
munmap_chunk(): invalid pointer
[1]    161243 abort (core dumped)  darktable
```
6. Switching on the mask view while zoomed in shows the proper mask

**Expected behavior**
No artifacts and no crashes...

**Screenshots**
Zoomed out:
![Zoomed out](https://user-images.githubusercontent.com/8134686/96874448-6948b080-1476-11eb-91d2-13ac11c0d61f.png)
Zoomed in:
![Zoomed in with artifacts](https://user-images.githubusercontent.com/8134686/96874461-6cdc3780-1476-11eb-8b0f-5824ba30c437.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0~git1181.7cc1296fd
 - OS: Pop.OS 20.04 (Kernel 5.4.0-7642-generic)
 - OpenCL activated or not, makes no difference
 - Intel i5-6200U, Intel HD Graphics 520

**Additional context**
I tried this on multiple olympus raw files, it always happened.
Also happens on JPG files

**Comment by s7habo** [comment]
I can confirm it:

With Tone Equalizer:

![TE1](https://user-images.githubusercontent.com/38165484/96889649-19261a00-1487-11eb-8b32-eac202a2f688.jpg)

Tone Equalizer disabled:

![TE2](https://user-images.githubusercontent.com/38165484/96889781-3b1f9c80-1487-11eb-9039-071a24fc6fc8.jpg)


Platform: 

Darktable Version: 3.3.0~git1181.7cc1296fd
Kubuntu Linux 18.04
OpenCL activated or not, makes no difference
GC: Nvidia GeForce GTX 1070

**Comment by kofa73** [comment]
I got this no matter which 'preserve details' setting is used.

**Comment by TurboGit** [comment]
I confirm, there is a jumping when zooming in the image, probably related to the issue at hand.

**Comment by aurelienpierre** [comment]
I don't reproduce.

**Comment by aurelienpierre** [comment]
Could you try to see if https://github.com/darktable-org/darktable/pull/5544/ fixes it ?

**Comment by AxelG-DE** [comment]
I do reproduce on ORF and NEF

![Screenshot_20201022_191820](https://user-images.githubusercontent.com/49004103/96909655-9a3cdb80-149e-11eb-9863-adebb669abf2.png)

I will try #5544 and come back later

**Comment by kofa73** [comment]
The first crash occurred when I was zooming in the darkroom. I was not running under gdb at that time.

With gdb, I was able to reproduce the corruption, but it did not crash -- I zoomed in and out, moved around, dozens of times. However, when I left the darkroom, I got the following crash report, and managed to produce a stack trace with `bt full`. Whether it's the same issue or not, I cannot tell:
```
free(): invalid size
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "darktable" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 140737488344052, 93823560581120, 140737488344256, 140736884392136, 140737488344240, 18, 140737233450096, 141, 18, 8, 0, 140737488344448, 4092873481, 93825041254760, 140737488344408}}
        pid = <optimised out>
        tid = <optimised out>
#1  0x00007ffff7a0e859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0x5, sa_sigaction = 0x5}, sa_mask = {__val = {0, 4294967296, 140737350016232, 140737488345008, 140737354037927, 0, 0, 0, 1, 93825041404416, 0, 0, 17605478716978730240, 386183668082672511, 223174255726, 188978549688}}, sa_flags = 40885, sa_restorer = 0x0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff7a793ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7ba3285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7fffffffd700, reg_save_area = 0x7fffffffd690}}
        fd = <optimised out>
        list = <optimised out>
        nlist = <optimised out>
        cp = <optimised out>
#3  0x00007ffff7a8147c in malloc_printerr (str=str@entry=0x7ffff7ba14c6 "free(): invalid size") at malloc.c:5347
#4  0x00007ffff7a82cbc in _int_free (av=<optimised out>, p=0x7fff81ea7000, have_lock=0) at malloc.c:4177
        size = 4479772872143013608
        fb = <optimised out>
        nextchunk = <optimised out>
        nextsize = <optimised out>
        nextinuse = <optimised out>
        prevsize = <optimised out>
        bck = <optimised out>
        fwd = <optimised out>
        __PRETTY_FUNCTION__ = "_int_free"
#5  0x00007fffc02dc291 in cleanup_pipe (self=<optimised out>, pipe=<optimised out>, piece=0x7fffd40243b0) at /home/kofa/darktable/src/iop/colisa.c:288
#6  0x00007ffff7dbc667 in dt_dev_pixelpipe_cleanup_nodes (pipe=0x5555582f2800) at /home/kofa/darktable/src/develop/pixelpipe_hb.c:262
        piece = 0x7fffd40243b0
        nodes = 
          0x5555585c90e0 = {0x7fffd40243b0, 0x7fffd4024730, 0x7fffd4024c50, 0x7fffd4024fd0, 0x7fffd4025390, 0x7fffd40268b0, 0x7fffd4026c50, 0x7fffd4026ff0, 0x7fffd4027390, 0x7fffd4027710, 0x7fffd4027a90, 0x7fffd4027e30, 0x7fffd40281d0, 0x7fffd40287c0, 0x7fffd4028b60, 0x7fffd4028f00, 0x7fffd4029350, 0x7fffd40296f0, 0x7fffd4039a90, 0x7fffd4039e30, 0x7fffd403a1d0, 0x7fffd403a550, 0x7fffd403b120, 0x7fffd403b6b0, 0x7fffd403ba50, 0x7fffd403bdf0, 0x7fffd403c170, 0x7fffd403c4f0, 0x7fffd403c8a0, 0x7fffd403cc20, 0x7fffd403d250}
#7  0x00007fffdc0378d7 in leave (self=<optimised out>) at /home/kofa/darktable/src/views/darkroom.c:3060
        __FUNCTION__ = "leave"
        dev = 0x555557b18810
#8  0x00007ffff7e75171 in dt_view_manager_switch_by_view (vm=0x5555584c2b30, nv=nv@entry=0x5555583a4d20) at /home/kofa/darktable/src/views/view.c:354
        old_view = 0x5555584c2e00
        new_view = 0x5555583a4d20
        __FUNCTION__ = "dt_view_manager_switch_by_view"
#9  0x00007ffff7d3e362 in _dt_ctl_switch_mode_to_by_view (user_data=0x5555583a4d20) at /home/kofa/darktable/src/control/control.c:354
        view = 0x5555583a4d20
#10 0x00007ffff775f085 in g_main_context_invoke_full () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fffa0311a5c in _switch_view (view=<optimised out>) at /home/kofa/darktable/src/libs/tools/viewswitcher.c:278
        view = <optimised out>
#12 _lib_viewswitcher_button_press_callback (w=<optimised out>, ev=<optimised out>, user_data=<optimised out>) at /home/kofa/darktable/src/libs/tools/viewswitcher.c:278
        view = <optimised out>
#13 0x00007ffff73404fb in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff6a79802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff6a8d814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff6a9845d in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6a990d3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff72eac23 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff71a6128 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff71a83db in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff6e90f79 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#22 0x00007ffff6ec4106 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#23 0x00007ffff775dfbd in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff775e240 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff775e533 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff71a737d in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff7e16db1 in dt_gui_gtk_run (gui=<optimised out>) at /home/kofa/darktable/src/gui/gtk.c:1548
        widget = <optimised out>
        allocation = {x = 0, y = 0, width = 568, height = 468}
#28 0x00005555555550d6 in main (argc=<optimised out>, argv=<optimised out>) at /home/kofa/darktable/src/main.c:93
```

**Comment by AxelG-DE** [comment]
I confirm I also made it crash once, but no output on my side. As I am not feeling well, I will not dive deeper at that point of time, sorry...

**Comment by jade-nl** [comment]
I can reproduce and incorporated #5544 on normal latest mater.

- Cannot reproduce with #5544 incorporated.

**Comment by MStraeten** [comment]
osx: could reproduce with current master but not with current master & pr #5544

**Comment by rawfiner** [comment]
I can reproduce as well, and #5544 fixes it for me. Sorry I don't have much more time tonight to investigate more. I can spend more time on it tomorrow if needed
