### ISSUE TITLE
Node responsiveness problem with liquify nodes

### ISSUE THREAD

**Issue by rgo** [darktable-org/darktable#6614]
**Describe the bug**
When I try to handle a node to modify the affected area or change the point mode without zoom in (image fit to screen), I can select them or modify the mode easily, as expected.

If I zoom in, then I can't select point nodes or change the radius with the arrow. If I move the cursor over the node, it sometimes gets highlighted, other times not, sometimes I can't select it to remove... its behaviour is erratic.

**To Reproduce**

1. Go to 'Liquify'
2. Click on 'Add a node'
3. Zoom out
4. Modify its radius
5. Zoom in
6. Try to modify the radius, modify the strength, ...

**Expected behavior**
Node handlers should work zoomed in and out.

**Platform (please complete the following information):**
 - Darktable Version: darktable_3.3.0~git1186.3f494bbfd (today's version from master - OBS)
 - OS: Ubuntu 20.04
 - OpenCL enabled
 - Radeon RX580

**Additional context**
Not sure if related, but I've seen the same effect with gradient mask handlers (zoomed out works as well but it's impossible to handle "the arrow" to rotate the gradient zoomed in).

If it's related, I can reword the issue title else I can open a new issue.

Thanks!

**Comment by TurboGit** [comment]
Do you have review down-sampling set ? If so, what the value ? Can you reproduce if set to "original" ?

**Comment by TurboGit** [comment]
Can you test #6616 ?

**Comment by rgo** [comment]
@TurboGit Thanks! I can't check it right now. I'll tell you down-sampling value and test it tomorrow evening.

**Comment by rgo** [comment]
@TurboGit Yes, I've down-sampling set:

![image](https://user-images.githubusercontent.com/47124/97119270-60bed700-170f-11eb-8735-c4a5f44c9cd3.png)

I'm going to test the fix right now.

**Comment by rgo** [comment]
Tested and it works, thank you very much @TurboGit

**Comment by TurboGit** [comment]
I found some other issues related to the actual zoom level and/or the down-sampling setting. All fixed now.
