### ISSUE TITLE
Sony A6300 some ARW cannot be loaded

### ISSUE THREAD

**Issue by oxanagig** [darktable-org/darktable#6619]
Hello,

I have imported the raw photo from Sony A6300 camera and most of the photos are displayed correctly, however, a few cannot be loaded as shown below
![image](https://user-images.githubusercontent.com/7388733/97058957-0d4c5d80-1544-11eb-9b19-b9af300425c7.png)

I have checked the photo using Exiftool, and couldn't spot any corruption to the file, and it was displayed correctly in Windows 10 built-in photo app. 

I have attached a loadable photo and a none-loadable photo for reference.
loadable: https://1drv.ms/u/s!AufIT2bq1Tn5g5cpt6ht_sKaDdyJSA?e=6wckjN
none-loadable: https://1drv.ms/u/s!AufIT2bq1Tn5g5covqtT02kraFaeOQ?e=fSzF2F

**Platform:**
 - Darktable Version:3.2.1
 - OS: Windows 10
 - OpenCL activated
Radeon RX 570 with

**Comment by junkyardsparkle** [comment]
Confirmed also broken in current master. Console output from rawspeed:

> [rawspeed] (none-loadable.ARW) void rawspeed::SonyArw2Decompressor::decompress() const, line 140: Too many errors encountered. Giving up. First Error:
> void rawspeed::SonyArw2Decompressor::decompressRow(int) const, line 85: ARW2 invariant failed, same pixel is both min and max

@LebedevRI ?

**Comment by LebedevRI** [comment]
I'm reasonably sure that means those files are corrupt, bitrot.
Do you perhaps happen to have those particular files available in some backup, and if so, is their hash sum different?

**Comment by junkyardsparkle** [comment]
Indeed, output from dcraw shows a few rows of garbage along the bottom edge... but the image could probably be salvaged to a TIFF file for further processing this way, if there are no uncorrupted backups available.

**Comment by oxanagig** [comment]
I just used Get-FileHash for both the file on my hard drive and the original file that is still on the SD card.

**File copied on my hard drive**
PS C:\Users\xiang\Downloads> Get-FileHash C:\Users\xiang\Downloads\none-loadable.ARW

Algorithm       Hash                                                                   
---------       ----                                                                   -
SHA256          CBE59608BC95E0DE67A7E0670DB306FD20967935EBD817F3A9ED3E062510005C       


**File on SD card:**

PS F:\> Get-FileHash F:\DCIM\100MSDCF\DSC00577.ARW

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          CBE59608BC95E0DE67A7E0670DB306FD20967935EBD817F3A9ED3E062510005C

So it seems like the photo was corrupted on the SD card in the first place.

Any repair tool that you recommend on Windows OS?

**Comment by LebedevRI** [comment]
> **File on SD card:**

Are you accessing it the same way you downloaded the image the first time?
Can you try doing that with different cardreader maybe?

> So it seems like the photo was corrupted on the SD card in the first place.

Hm, that is not what i expected, but that happens sometimes..

**Comment by LebedevRI** [comment]
I'm just going to close this..
