### ISSUE TITLE
Allow shortcut keys to work across views

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6621]
**Is your feature request related to a problem? Please describe.**
I want to export images from darkroom view but want to select different export presets. As an example, I have various file output paths ,max width presets and a preset with a style that removes framing.
I have shortcuts defined to show export preset popup menu and shortcuts for individual presets.
Currently the shortcuts are not global so I need to go to lighttable and select various presets and export.
This may interfere with the current unique shortcuts across views.

**Describe the solution you'd like**
Allow shortcuts that don't have gui preset popups to work across views. So, if I want to change a certain preset for lighttable export I should not have to leave darkroom to adjust presets to the one I want.

**Alternatives**
One can always go to lighttable and use the short cut but that to and fro between views is not really a good workflow when shortcuts are available.

**Comment by parafin** [comment]
It's probably quite hard to implement, because libs from another view don't have a defined state IMHO, so allowing to trigger actions in them will just lead to a lot of crashes. Much easier request would be to add export lib to darkroom view.

**Comment by chhil** [comment]
Export in darktoom view would work too, same functionality as in lightable but without preset module popup shortcut as the module is available in the lighttable view.

**Comment by chhil** [comment]
Bump

**Comment by johnny-bit** [comment]
@chhil - you may want to change tittle of the issue and main description ;)

essentially - @parafin has good idea: it's a FR for bringing export module into darkroom, so you could export directly from darkroom.
