### ISSUE TITLE
Brush Masks : Ability to create / edit brush radius at control points

### ISSUE THREAD

**Issue by Praveen-Rai** [darktable-org/darktable#6622]
**Is your feature request related to a problem? Please describe.**
Right now the brush size can only be set before the beginning of a stroke. This often leads to multiple brush strokes to cover up the area. In general editing a mask is already sluggish, therefore if we can control the radius at different control points it would be much easier to work with brush mask.

**Comment by elstoc** [comment]
Sounds like the path tool would be better for this use case.

**Comment by Praveen-Rai** [comment]
@elstoc Path tool could be tedious and too heavy for certain cases. For instance lets [this Photo](https://www.pexels.com/photo/woman-sitting-on-wheelchair-4064336/) by Marcus Aurelius from Pexels as reference. In this image if one has to manipulate the overhead ducts, or the wheels, its much easier to use Brush tool, rather than path. 

Another example would be [this Photo](https://www.pexels.com/photo/grayscale-photo-of-concrete-pillars-5319719/) by ROMAN ODINTSOV from Pexels. In this image too Brush tool would be better to select the pillars.

In general, if a shape is long and a mid curve can be drawn, then brush tool is the best to use. Since, that way you define just one curve, and rest is calculated by sweeping a circle along that path. If you were to use path for it, you'll have to define all its boundaries, which makes it a tedious to draw, and as there are more points it seems to be a bit heavier to manipulate.

**Comment by Praveen-Rai** [comment]
Infact a lot of times, people tend to use brush instead of path tool to paint areas. Coz, that's easier to do. But for darktable that isn't a great idea, since it will stores the entire path drawn, which looks likes a messed up doddle, intersecting and overlapping a lot of times, in such scenario Path would be the right choice. I was wondering if we can simplify such paths to make it easier to store and edit later. Or may be we offer to generate path from brush strokes.

**Comment by johnny-bit** [comment]
Actually adjusting brush radius is possible during drawing via either scroll during drawing or via pressure sensitivity check via graphics tablet.

What we're lacking is "just" adjusting brush size in edit mode.

@TurboGit - what do you think? adding eg scroll modifier if brush node point is selected?

**Comment by TurboGit** [comment]
Yes, this is indeed a missed feature and something that will be nice to see supported. A scroll modifier seems the way to go to me, but we have also the hardness on each nodes that we probably also want to adjust. So that makes things a bit more complicated. In the pref we have ways to select which part of the brush is controlled when using a pad (either the hardness or size), so having a way to to that after drawing for people not having a pad will be really nice.

**Comment by TurboGit** [comment]
@johnny-bit : I have marked this for 3.8, let's see if this issue is picked-up by some devs.

**Comment by AlicVB** [comment]
fyi, we have started some work with @aurelienpierre on a sort of "drawn masks toolbar" which would solve this issue... but that's a big work !
Maybe @dterrahe work on key accels #8078 would also allow to define specific shortcuts ??? (not sure it's for phase 1)

**Comment by dterrahe** [comment]
Isn't this issue asking to be able to edit the size of individual control points (or vertices) rather than the whole brush (which is already possible)? The same modifiers (shift+scroll) could work, but depending on which part of the brush is active (where the mouse is hovering) the size adjustment should be applied to just that part.

8078 isn't really touching drawing "shortcuts"/modifiers (yet). Although if #9015 is using bauhaus widgets, they could get shortcuts.

**Comment by johnny-bit** [comment]
> Isn't this issue asking to be able to edit the size of individual control points (or vertices)

It's exactly that!

**Comment by TurboGit** [comment]
@Praveen-Rai : see #11507, after 1.5 year... better later than never :)

**Comment by Praveen-Rai** [comment]
That's a great news !! Thank you so much for contributing this feature. I am excited to try my hands on it, and I am sure other users too will love & benefit from this feature addition. It would be really helpful if you can just put a short writeup about how the feature is implemented, How users can select nodes and change their sizes. You also mentioned about "Pad Preferences" earlier in this issue, does that gets impacted too or have we added any preferences / shortcut related to this feature addition ?

**Comment by TurboGit** [comment]
No new preference. The feature is easy to use. If you hover over the form the whole brush will get resized or the hardness adjusted as before. But if you hover over a node (dot in the brush path) only the hovered node will get its size or hardness adjusted.

**Comment by TurboGit** [comment]
Of course this will get documented in the manual at some point.
