### ISSUE TITLE
Read float TIFFs as HDR

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#6623]
**Describe the solution you'd like**

Currently (dt 3.3.0) it seems HDR mode upon read is set solely by file extension and covers only PFM/RGBE/OpenEXR/AVIF: https://github.com/darktable-org/darktable/blob/a181aab7c9d9c9fadafae19057362389883efbcc/src/common/imageio.c#L523

However, dt also supports reading 16/32-bit floating point TIFFs, and those could contain HDR images as well.

**Comment by kmilos** [comment]
OTOH, it looks like it might be set anyway by https://github.com/darktable-org/darktable/commit/a8fb94a5c17f3210228bd8f5f06a5b635310d316 no?

**Comment by kmilos** [comment]
For example, [this half float TIFF](https://discuss.pixls.us/t/16-bit-float-export-looks-weird-in-other-applications-but-32-bit-float-is-fine/20185/21) imports in  3.3.0+1188~ga181aab7c without indication of HDR mode anywhere, in contrast to OpenEXR or AVIF samples:

![image](https://user-images.githubusercontent.com/4973094/97084623-a8af0280-1618-11eb-9f4e-904579237edf.png)

**Comment by kmilos** [comment]
Ok, I now see that it's supposedly set only when `PhotometricInterpretation` is `LinearRaw` for float TIFFs (i.e. DNGs only)...

Any special reason to exclude float TIFFs that are encoded differently? AVIFs for example are nonlinearly encoded in general and are still considered "HDR"....

**Comment by jenshannoschwalm** [comment]
No special reason. Anyway "HDR" is not a technical term that can be derived from analysing photo data.

**Comment by kmilos** [comment]
> Anyway "HDR" is not a technical term that can be derived from analysing photo data.

Not universally, agreed. Which then begs the question, what is this tag/mode for, and why is then selected by file extension only? I understand RGBE and OpenEXR files are "most likely" to have HDR content, but AVIF container is general and can encode all sorts of gamut and DR, and so does TIFF...

**Comment by aurelienpierre** [comment]
Fixed by ce13a3c134ef6b487133aebae3ca86acd3d72b95

**Comment by kmilos** [comment]
We support 16-bit float TIFFs too..
