### ISSUE TITLE
Segmentation fault because of obsolete modules

### ISSUE THREAD

**Issue by w-oertl** [darktable-org/darktable#6626]
Two old, obsolete module files have caused DT to fail upon startup with a segmentation fault: lens.so and modulelist.so.
Deleting them fixed the issue. This was not obvious, though. The older timestamps of the .so files were an indication.

I suggest that upon installation (e. g. ninja install), such old files are deleted or at least warned about.

**Comment by parafin** [comment]
I think instead dt should just ignore such modules. E.g. introduce some version number that gets compiled in all modules and libdarktable and check that it matches when opening the module. Then we can just increment it whenever a breaking change is introduced (e.g. removal or rename of the module).

**Comment by w-oertl** [comment]
Simply put the dt version into each compiled module and check it on loading. It must match the dt version. No need to introduce a per-module API version, I think.

**Comment by parafin** [comment]
Not per-module, global. Using dt version will somewhat break the modularity of dt - if user uses some out-of-tree iops, he will need to recompile them each time he updates and rebuilds dt (I'm thinking about master builds). I think there will be a push-back for this approach, so IMHO only breaking changes need to increment the version.

**Comment by w-oertl** [comment]
I wasn't aware of out-of-tree modules; in this case an approach as you suggest is superior. So it only needs to be implemented by someone ;-)
