### ISSUE TITLE
Retouch online help unavailable through DT clicking "?" and clicking retouch module

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6629]
version 3.3.0+1188
The following URL is not available 
https://darktable.gitlab.io/doc/en/effects_group.html#retouch

![image](https://user-images.githubusercontent.com/1119439/97098079-f4a48a80-169e-11eb-8668-09d83d32252e.png)

Actually, none of the help is available.

**Comment by TurboGit** [comment]
Yes, we have updated dt online help to match the coming 3.4 manual. Until then some links are broken.
