### ISSUE TITLE
Print Module : Do not take into account the specific options of the printer driver (Borderless printing)

### ISSUE THREAD

**Issue by japamax** [darktable-org/darktable#6634]
System : Archlinux
Desktop : Kde 5.20.1
Printer : Epson R2000
Driver  : epson-inkjet-printer 1.0.0-1lsb3.2
Option : Paper Settings Borderless On

The impression still with margins (3 mm) even if you put negatives margins (-3 mm) in darktable.

**Comment by mzannoni** [comment]
I got the same issue with a Canon iP8570.

System: Ubuntu 20.04
Printer: Canon iP8750
Driver: cnijfilter-ip8700series_4.10-1_amd64.deb (provided by Canon)

Already talked about this in details here: https://discuss.pixls.us/t/cant-print-borderless-with-darktable/22558

As stated, the printer works well with all the other software. darktable seems not to be able to use the driver properly.
Maybe not all the options are correctly interpreted? For instance, some of the options available (when you print from GIMP for instance) are not present.

One option in particular, is used by the driver to set specifically the "borderlessness":
![image](https://user-images.githubusercontent.com/29273478/104426867-d013cc80-5582-11eb-9770-a145e3f5bc09.png)
It is called: "Amount of Extension". Canon says it defines how close to the boarder should be printed and they recommend to put 2 (on a 1 to 4 range). Maybe darktable puts this at a different value?
Anyhow, this settings (as well as other advanced settings, like printing quality) are not exposed in the print module.

**Comment by palto42** [comment]
I came across the borderless printing issue today and wonder if there is a solution. Tested with Darktable 3.6.0, maybe the PR #10335 will fix it in next release?

**Comment by TurboGit** [comment]
On GNU/Linux and using Turboprint I think I have fixed this issue in the upcoming 3.8 release.

If not using Turboprint or from another OS I cannot help. This will need debugging from another dev.

**Comment by palto42** [comment]
@TurboGit  thanks for confirming that the PR is fixing the issue at least for your setup using Turboprint.
I compiled the latest version from master branch and tested it on my Solus Linux. I can see the changes in the Draktable print dialog which no displays a borderless preview. But with the standard cups driverless printing, which offered a borderless paper option, the result has still a small border. Assume that this is a problem with the driver.

**Comment by TurboGit** [comment]
@palto42 : Or another issue in darktable, all is possible this borderless mode drives me crazy.

**Comment by ralfbrown** [comment]
How small is "small"?  If it's less than a millimeter, that's due to mechanical inaccuracies in the printer and/or paper sizing (which is why drivers that offer borderless printing usually also have an expansion option to enlarge the printed image by 1-3% and ensure full coverage of the paper).
