### ISSUE TITLE
flag selected thumb (triangle on top) visible on lighttable

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6637]
**Describe the bug**
flag selected thumb (triangle on top) visible on lighttable

**To Reproduce**
1. Go to lighttable
2. Click X to enter the culling mode
3. Click X to leave the culling mode
4. Fly over the 2 thumbs which where displayed in culling view (to refresh the display)
5. You'll see the little triangle on top

This triangle should only be displayed on the filmstrip.

**Expected behavior**
no triangle visible on lightatble

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/97112241-74ecdf00-16e3-11eb-9b9e-e57c986c0da6.png)

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS:GNU/Debian

**Comment by TurboGit** [comment]
@AlicVB : I have assigned this issue to you, probably a recent issue as I don't remember having seen that before.

**Comment by TurboGit** [comment]
@AlicVB : do you think you'll have time to look at this one for 3.4 ? Probably an easy one for you as you know well this part of code. TIA.

**Comment by AlicVB** [comment]
@TurboGit : really sorry to have missed this one... I should have more time now...
Sadly I can't reproduce, Do you reproduce each time ?

Note that I know where to look in the code, so hopefully I'll manage to fix it blindly ;)

**Comment by AlicVB** [comment]
oh... just found : you need filmstrip to be invisible in culling... and the problem certainly comes from my commit f358ed4762eb28a6648ac293d6063f13b6dd4645
I'll have a look !
