### ISSUE TITLE
Default colors make darktable look like it can't do proper color management

### ISSUE THREAD

**Issue by grubernd** [darktable-org/darktable#6643]
"preserve highlights" = "lumanince" is the cuplrit.
"none" makes images look realistic and more like a proper color management workflow.

New users will open darktable, look at their images, say "ugh" and uninstall. If that is the intention I rest my case.

How can I help to make darktable look good for newbies?

**Comment by TurboGit** [comment]
> say "ugh" and uninstall. If that is the intention I rest my case.

That's expected with people that don't want to learn and want the software to

**Comment by TurboGit** [comment]
This has already been discussed and the luminance setting is the one that gives better results in more cases. Please looks at the corresponding thread where discussion happened with some heat! I don't want to see this again so closing this.

Note that people that don't want to learn are indeed better to look for another software than darktable.

**Comment by grubernd** [comment]
I have not found such a thread. Can you please give me a hint?

> Note that people that don't want to learn are indeed better to look for another software than darktable.

Wow, I almost don't even know what to say to that.

That is pretty much the worst elitist welcome message I have gotten in a long time. Does the darktable team not want someone with 20+ years of colormanagement and 15+ years of RAW converter beta testing experience as a willing contributor? Or are you just having a bad day?

**Comment by jenshannoschwalm** [comment]
Hi, this is not a matter of having a bad day. I think all dt devs try to find compromises acceptable for newbies. But this is an issue tracker and you seem to talk about nothing we want re-iterated again because at some point we have to agree on a point after discussing all arguments.

And - dt might be different than software you are used to - so why don't you just take it as it is now, give dt a good try and come back if there really is an issue?

**Comment by matt-maguire** [comment]
For more information on the "color science" of the filmic module, please refer to the description of the "preserve chrominance" option in the following article:
https://elstoc.github.io/dtdocs/module-reference/processing-modules/filmic-rgb/#options
