### ISSUE TITLE
Crash on import folder

### ISSUE THREAD

**Issue by muenznej** [darktable-org/darktable#6645]
**Describe the bug**

Since 3.2.1 i have a problem that causes some folders to crash darktable upon import. these folders are permanently causing this issue :/ 
Since I have no further explaination i ll just add some logs and a screenshot.

**To Reproduce**

![1](https://user-images.githubusercontent.com/26899110/97225026-544f8280-17d2-11eb-9562-517ffbbbe2bb.JPG)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 8.1 64 
 - yes 
 - ![image](https://user-images.githubusercontent.com/26899110/97225164-924ca680-17d2-11eb-9a35-aff3acadbcac.png)

**Additional context**

LOGS:
[darktable_bt_G1U1S0.txt](https://github.com/darktable-org/darktable/files/5441356/darktable_bt_G1U1S0.txt)
[darktable_bt_LM0WS0.txt](https://github.com/darktable-org/darktable/files/5441357/darktable_bt_LM0WS0.txt)
[darktable_bt_LU5FT0.txt](https://github.com/darktable-org/darktable/files/5441358/darktable_bt_LU5FT0.txt)
[darktable_bt_NZ64S0.txt](https://github.com/darktable-org/darktable/files/5441359/darktable_bt_NZ64S0.txt)
[darktable_bt_PQ5ET0.txt](https://github.com/darktable-org/darktable/files/5441360/darktable_bt_PQ5ET0.txt)
[darktable_bt_QEBVS0.txt](https://github.com/darktable-org/darktable/files/5441361/darktable_bt_QEBVS0.txt)
[darktable_bt_Z5RDT0.txt](https://github.com/darktable-org/darktable/files/5441362/darktable_bt_Z5RDT0.txt)
[darktable_bt_2ND5S0.txt](https://github.com/darktable-org/darktable/files/5441363/darktable_bt_2ND5S0.txt)
[darktable_bt_85E8S0.txt](https://github.com/darktable-org/darktable/files/5441364/darktable_bt_85E8S0.txt)
[darktable_bt_DEO6S0.txt](https://github.com/darktable-org/darktable/files/5441365/darktable_bt_DEO6S0.txt)

**Comment by kofa73** [comment]
I'd be nice to know if you already have XMP files in those folders; if yes, can you reproduce the crash if you move the XMPs somewhere else?
If it does **not** crash with the XMPs moved, it means some of the XMPs contain settings causing the crash.
- 'Remove' the imported images from darktable (or use the in-memory database, see below) and remove the newly generated XMPs (which just contain default settings)
- Restore some of the original XMPS (e.g. half of them)
- Try the import again.
- If it crashes: retry the procedure, but with only half of the XMPs from the previous step; retry, and repeat this halving until you find an XMP that causes the crash. Then post that here (along with the raw image)
- If it doesn't crash, try with the other half of the (original, processed) XMPs from the previous step.

You may want to use the in-memory database for these imports, so after a crash you start with a clean database and don't have to keep removing imported images (which may be left behind if the import crashes). Use the `--library :memory:` command-line option for that.

**Comment by muenznej** [comment]
Thanks for the quick reply,
> I'd be nice to know if you already have XMP files in those folders; if yes, can you reproduce the crash if you move the XMPs somewhere else?
> If it does **not** crash with the XMPs moved, it means some of the XMPs contain settings causing the crash.
I removed the XMPs to another folder, and it did NOT crash.

**Comment by pahl34** [comment]
**darktable 3.2.1
Windows 10**

I experienced a darktable crash as well today when importing a folder (small amount of images in my case).
There had not been xmp files in that folder before.
However, a second attempt to import that folder worked fine after restarting darktable.

I also found #6660 which might be a duplicate?

[darktable_bt_AS9QT0.txt](https://github.com/darktable-org/darktable/files/5540409/darktable_bt_AS9QT0.txt)

**Comment by muenznej** [comment]
After some time trying to live with this problem I gave up and switched to linux.

Most interestingly it happens as well. It crashes, but without a notice and i cannot find the log file.
Since i tried both systems i can only imageine this to be connected to the external HDD where most of my photographs are located. Its a really severe problem, since it happens very often... :(

**Comment by kofa73** [comment]
That log file is basically empty.

**Comment by muenznej** [comment]
thats correct, but i did not write this log file by hand... should i add some prose? :man_shrugging:

**Comment by ptilopteri** [comment]
definitely, it will assist in closing this issue!

**Comment by kofa73** [comment]
@muenznej I didn't blame you for it being empty; I just noted that the file won't be useful.

**Comment by muenznej** [comment]
@ptilopteri and @kofa73 cmon guys, i just did my best to help and provide information. I have the impression that you do not find my input constructive, but please recall what you just wrote...thats not constructive.
There is a segfault issue that multiple people report and that is not related to windows or linux. I think it should be taken seriously since it makes DT hardly useable for some ppl (including me). And that is a shame because its such a good software besides these bugs...

**Comment by chhil** [comment]
1. Can you point to a different config folder and start dt from commandline with the confugdir parameter with a path or just rename your config folder start dt and try importing with and without xmps?

2. If possible share your image folder and one of us can try importing and see where we get to ?

**Comment by muenznej** [comment]
Thanks for your reply, i will try to do so later, when i figured out how to use these commands and where the config is located.

**Comment by muenznej** [comment]
ok, so i made a empty config directory and so far no crashes. I ll stay with this "config" and maybe crasehs appear in the future. i ll update you guys

**Comment by johnny-bit** [comment]
How's the stability now? Have new configs resulted in no new problems? (Please colose the issue if so...)

**Comment by muenznej** [comment]
Hi, although i couldnt test it excessivly i did not have any crashes so far.

i ll close this for now, until i can reproduce crashes specifically
thanks for your workaround and help
