### ISSUE TITLE
a style's menu in import

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#6649]
Many thumbnails in my lighttable are not "readable" by default. After import, i apply a tweaked style for each different source.
I use presets only for basics & definitives tunings. I always work in scene-refered, but for thumbnails, i use tone curve which are more in the average of a pictures's series. After a more precise tuning (in scene-refered), the tuned images's thumbnails pop out clearly in the lighttable.

Is it imaginable to apply a style at the import, & have a style's menu in the import module?

**Alternatives**

**Additional context**

**Comment by johnny-bit** [comment]
Quite honestly this idea might come handy for future GTK4 import redesign... So import module could have import metadata widget options and similarly to lightroom apply style on import... Might be interesting...

**Comment by johnny-bit** [comment]
@phweyland - after your work on import module - what do you think about this feature request?

**Comment by phweyland** [comment]
>  after your work on import module - what do you think about this feature request?

This work was about ui. No problem for adding features on this side.
I'd thought about applying tags presets but I haven't seen any request for that...

Of course applying styles makes a lot of sense but that may have more potential impacts than applying metadata. 
In particular, that will interfere with history (see collect / history), history_hash, default modules, development on the fly, ... we may have to create a specific history state (not default anymore but not developed yet ...).

@turbogit, what do you think ?

**Comment by johnny-bit** [comment]
I'd say that if a preset was applied on import then the image IS developed/changed. same as selecting virgin image in lighttable and applying a style to it.

**Comment by johnny-bit** [comment]
Actually I found myself in a situation where i'd like to have a "apply style on import" thingie in import module... Ideally it'd work the same as if I would've imported images, selected all and applied style to them...
