### ISSUE TITLE
dead-links as a rule in collect image

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#6650]
To remove dead-links, i use `purge_non_existing_images.sh` but before removing it, i want to inspect it.

Is it possible to have a rule, to regroup dead-links, in the collect image module?

**Alternatives**

**Additional context**

**Comment by TurboGit** [comment]
I don't think this is appropriate for dt to do this, better use a Lua script for this. Note also that an image is flagged as non existing if stored on an external safe (RAID) drive which is not mounted.

**Comment by dim162** [comment]
The correct use of an external safe drive is to store images, it's not a working drive... It's unsafe & slow. There are still 2 places to sort images, it will be the third... It becomes messy!

**Comment by TurboGit** [comment]
> It's unsafe & slow

?? That's certainly not unsafe. I do edit first on my main computer (fast laptop) and move the pictures into an external fast RAID storage on lan. And I can tell you it is not slow either. So fast enough for reworking pictures if needed and lot safer!

> There are still 2 places to sort images, it will be the third... It becomes messy!

You have to explain... I have a single location with all my images. Don't understand what you are doing.

**Comment by dim162** [comment]
I don't understand why you talked about the external safe drive, at your first post... Do you transfer your images from your laptop, to the safe drive?! It's really risky! 
It's no so fast than a ssd M2.1 on a ryzen 9 (overclocked) with 2 graphic cards, one is a rtx quadro. 
I don't speak about location! At the top, i can sort image with some criteria... time & so on, in the collect image, i can sort images with rules, a lua script will be a third place, to sort image only for one criteria. I don't want to delete it, a script still exist, i just want to examine it, before delete it

**Comment by TurboGit** [comment]
> Do you transfer your images from your laptop, to the safe drive?! It's really risky!

Risky to transfer to a raid driver! I think I have read enough.
