### ISSUE TITLE
Support Sony SEL18135 lense correction

### ISSUE THREAD

**Issue by bes1002t** [darktable-org/darktable#6652]
I bought the SEL18135 for travel purposes. At 18mm there are a strong black distortions and usually I could fix this for other lenses using Darktables lense correction. But unfortunately there is no lense correction for the SEL18135 in Darktable so far.

As workaround it is possible to use the lense correction for SEL1650, but I don't know whether this is the best we could get out of Darktable, or whether a dedicated correction for SEL18135 would be better.

**Comment by matt-maguire** [comment]
The lens corrections are handled by the lensfun library. It does support the SEL18135, so if you don't see it in darktable it means your lensfun database is out of date.

It can be updated with the command:
```
$ lensfun-update-data
```

**Comment by bes1002t** [comment]
@matt-maguire thanks for that hint, now it works! :)
