### ISSUE TITLE
Feature request: Benchmark

### ISSUE THREAD

**Issue by 4044ever** [darktable-org/darktable#6654]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add function

**Alternatives**
n/a

**Additional context**

Feature request: Benchmark function

IMHO it makes great sense for darktable and helps users with what hardware brings speed improvements, and which not. It's also much easier to compare the different O/S - and what O/S tweaks work, or tweaks that do not help performance.

Affinity Photo will have a benchmark function in the beta (1.9) version. Image below. 

![Screenshot 2020-10-13 11 08 30](https://user-images.githubusercontent.com/3244771/97306529-92fc4000-1899-11eb-9d59-9cff8e6df1f6.png)

**Comment by ralfbrown** [comment]
We already have most of the pieces to write an external script to do benchmarking.  Have the script run darktable-cli on a benchmark image and .xmp with -d perf a few times, parse out and average the timings, then display them.  To get a linearly comparable overall rating, divide 3600 by the average total time (I'd suggest image-load time plus pixpipe time, to omit program startup time while not underestimating actual time during batch exports).  That results in a number indicating how many images can be exported per hour.

I put together a sidecar file that contains nearly every iop available in current git master (except invert, negadoctor, and 3d clut), and some of them twice to exercise different algorithms.  Using the 10MP mire1.cr2 integration-test image, this takes 6.5 seconds for the pixelpipe on a Threadripper 3970X without OpenCL.
```
  darktable-cli mire1.cr2 bench.xmp --core -d perf
```



[bench-all-iops-3.3.0.xmp.txt](https://github.com/darktable-org/darktable/files/5469200/bench-all-iops-3.3.0.xmp.txt)

**Comment by 4044ever** [comment]
So it's not included in 3.4.0
Hope the next release can have something with GUI similar to Affinity 1.9Beta. 

They create quite an interesting discussion:  https://forum.affinity.serif.com/index.php?/topic/124022-benchmark-1900-results/

**Comment by ralfbrown** [comment]
It came after the feature freeze for 3.4.   GUI only if someone else writes one - I have neither the time, interest, nor expertise to implement a GUI.

**Comment by johnny-bit** [comment]
IMO GUI is NOT needed for benchmark.

**Comment by 4044ever** [comment]
> IMO GUI is NOT needed for benchmark.

Most darktable modules aren't needed. Good to have options though. 

Have a look at the Affinity forum how it's done well. With darktable it's wild guessing and hoping that your hardware performs. With a GUI everybody can contribute.
