### ISSUE TITLE
Tone Eq UI....lots of blank space at the bottom of the module between sliders and mask button bar....

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#6662]
Current Dev version has excessive empty space in the Tone eq module that requires substantial scrolling to get to the mask buttons to adjust opacity or blend mode....Likely a simple fix..

This occurs on WIndows 10 with a recent build I think 1285??  I can update with detail if this is not obvious to others or is not showing on Linux builds....

**Comment by elstoc** [comment]
Could you provide a screenshot please. Bear in mind that the tone equalizer is split into tabs and it's size is determined by the tab that is most packed with widgets (in this case most likely the 'masking' tab), so I would expect some empty space probably in the advanced tab.

**Comment by todd-prior** [comment]
@elstoc Hey Chris I think its a scaling issue. I did now realize if you widen the pane that it scales the whole box. I just thought it got wider to spread things out...Likely fine for many modules but it gives the Tone Eq a large dead space because of the way it scales with both x and y rather than just y...
![image](https://user-images.githubusercontent.com/44409419/97442063-d093b400-18ff-11eb-9e8e-07b0ed2a6e76.png)

**Comment by elstoc** [comment]
Yes - it's because of the scaling of the graph view on the advanced tab. So probably working as expected.

**Comment by todd-prior** [comment]
When you resize the panel the only thing that grows in the module is the mask PP bar , the font and the sliders stay the same size so really having the module expand in the y direction adds useless space. I tried to reproduce in a few other modules but it doesnt happen the mask bar stays in place without the padding...

**Comment by elstoc** [comment]
It's not useless - it's to keep the graph view square

**Comment by todd-prior** [comment]
Okay but doesn't  happen with filmic or other modules....
![image](https://user-images.githubusercontent.com/44409419/97443170-156c1a80-1901-11eb-90e1-473ad9ac4000.png)

vs expanded  

![image](https://user-images.githubusercontent.com/44409419/97443253-36cd0680-1901-11eb-8900-d7d58fdd59a6.png)

**Comment by elstoc** [comment]
That's because the graph is not inside a tab but above the tabbed part of the interface.

**Comment by todd-prior** [comment]
Well its a bit more I think there is a padding issue in the layout...as the display button for the tone eq mask ends up moving down and it should stay up under the sliders. The filmic graph seems to maintain its proportions without pushing elements of the module down like that so again...np but I think there is a small niggle in there and it required you to scroll up and down to turn the mask off and on if you are expanded....I just noticed it...not complaining or anything...

**Comment by elstoc** [comment]
I see your point re the mask display button. I can probably fix that easily

**Comment by todd-prior** [comment]
Sorry likely me being ambiguous....its like scaling puts a bunch of carriage returns in between the exposure mask line and the mask adjustments.....the rest of the elements in the module box seem to behave as expected......again sorry not to have a better explanation

**Comment by elstoc** [comment]
Actually not that easy to fix now I look at it, because the exposure mask button is separate from (beneath) the tabbed view so that it remains available for all tabs.

**Comment by todd-prior** [comment]
Doesnt seem to do it in the advanced tab only the other two??

**Comment by elstoc** [comment]
Because the graph is able to automatically resize to fit the available space. None of the controls on the other tabs are able to expand vertically.

**Comment by todd-prior** [comment]
I see
