### ISSUE TITLE
Allow category flag for every tag

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#6665]
**Problem**
Currently the 'category' flag can only be set for tags with directly applied images (non-italic tags).
Every tag which is used as hierarchy-level, and there are therefor no images applied to it directly, is automatically set as 'category', and this can't be changed.

**Solution**
- Initially the category flag is set automatically (following the current logic)
- Additionally the user can overrule this setting when editing any tag
-- a hierarchy-only-tag can manually be set as non-category
-- a normal tag can manually be set as category (current behaviour)

**Alternatives**
The alternative, I am using now, is to have one dummy image which I tag with all category-tags I want to uncategorize.
This way, these tags are automatically set as non-category.

Because unused tags are deleted automatically this is quite strange, because depending on the existance of one image the logic for all images is different.

**Example**
One of my tag hierarchies is Place|<country>|<city>|<area>
'Place' is of course a category, but 'country' should be a normal tag included on export, because it is an additional information.
So I want to define the country as non-category without having to double tag the image with country + country|city

**Screenshot of current situation**

![tag-category](https://user-images.githubusercontent.com/5677563/97444083-0babdc80-192c-11eb-81d9-4e02a786c04e.png)

**Comment by phweyland** [comment]
I'm afraid I don't understand your problem.
I've myself a places category followed by 3 or 4 levels of details. On of course I only tag my images with the last level (the more accurate one).


> The alternative, I am using now, is to have one dummy image which I tag with all category-tags I want to uncategorize

The tags which are automatically in italic do not exist. They just support the (visual) hierarchy. I don't understand the need to uncategorize them.


> Every tag which is used as hierarchy-level, and there are therefor no images applied to it directly, is automatically set as 'category', and this can't be changed.

This seems incorrect. Or I don't understand.

**Comment by quovadit** [comment]
My tag hierarchy is Place|AT|Wien

As I 'omit hierarchy in simple tag list', the only tag which is being exported is 'Wien'.
But as the country AT is also an information I want to use in my web-gallery, I also want to have the tag 'AT' exported.

If there is any image where I apply the tag 'Place|AT' (without Wien), and then re-export the image with 'Place|AT|Wien', then the tags 'AT' and 'Wien' are exported, which is my expected behaviour.

So I would like to be able to remove the 'category' flag from 'AT|Wien' without having to apply the tag 'AT|Wien' to one random image.

I hope it is clearer now...

**Comment by phweyland** [comment]
> I would like to be able to remove the 'category' flag from 'AT|Wien' without having to apply the tag 'AT|Wien' to one random image.

I don't understand what it is about ... Could show a snapshot of your tags in list mode (not suggestions) ?

There are 2 types of categories:
1. if you create the tags at each level, like:
```
place
place|AT
place|AT|Wien
```
You can set each of them as category or not, and attach them all to an image (category or not)
2. but if you have only one tag like
`place|AT|Wien`
place and AT do not exist as tags and are then considered as categories.
As they don't exist you cannot change their type...

Categories are never exported as simple tags but can be exported as hierarchical tags.
If you need to export AT as simple tag, the tag place|AT must exist.

**Comment by quovadit** [comment]
I now understand, that technically the tag place|AT does not exist if I only apply the tag place|AT|Wien
So I understand why it is not possible to uncategorize this not-existing tag.

But from a user-perspective, I don't understand, why it is possible to change the name of the not-existing-tag 'AT', but it is not possible to define it as no-category:

![tag-category-nok](https://user-images.githubusercontent.com/5677563/98447735-75e03080-2127-11eb-90d3-2959ce55d827.png)
_(screenshot: current situation)_


.


So my expected behaviour would be:
* if I edit a tag-hierarchy which does not exist as a tag (e.g. 'AT'), the checkbox 'category' is visible and checked 
(to show that this is considered as category)
* if I uncheck the checkbox 'category' the tag 'place|AT' is created automatically
* the system prevents the accidental deletion of this tag
  * the lua script 'delete_unused_tags' does not delete auto-generated tags
  * auto-generated tags are not shown in list-mode

**Comment by phweyland** [comment]
> I don't understand, why it is possible to change the name of the not-existing-tag 'AT', but it is not possible to define it as no-category:

Because in that case it is part of the path.
if you have the tags
```
place|AT|Wien
place|AT|Graz
```
you may want to change AT by something else like Austria:
```
place|Austria|Wien
place|Austria|Graz
```

>     * if I edit a tag-hierarchy which does not exist as a tag (e.g. 'AT'), the checkbox 'category' is visible and checked
>       (to show that this is considered as category)
>     * if I uncheck the checkbox 'category' the tag 'place|AT' is created automatically

That is a good idea indeed !
Meanwhile you can do the same editing the tag place|AT. This tag automatically becomes the father of Wien, Graz, ...



> the system prevents the accidental deletion of this tag
> 
>     * the lua script 'delete_unused_tags' does not delete auto-generated tags
> 
>     * auto-generated tags are not shown in list-mode

I haven't used lua for a while, but this doesn't sound a idea for me.

**Comment by wpferguson** [comment]
> Problem
Currently the 'category' flag can only be set for tags with directly applied images (non-italic tags).
Every tag which is used as hierarchy-level, and there are therefor no images applied to it directly, is automatically set as 'category', and this can't be changed.

I've read through this and the PR's and I still don't understand what you are trying to do.  You've stated the above is the problem, but not why it's a problem.  I don't understand why you want Place|AT in your list of tags with no images assigned.  What is the use case for this?  Is it a placeholder for the next time you have a location in Place|AT?  You don't need to do that.  You can create Place|AT|<somewhere>, Place|AT|<somewhere else>, Place|AT|<..> and they will all display under Place->AT in the hierarchical view. 

I've looked at #8270 and #8227 and I understand the changes, but I'm not sure what problem we are solving.  If I tag an image with Place|AT|Wein, export it, then check the tags (with omit hierarchy) I get AT, Place, Wein when I check with exiftool.  

Is the problem with the exported tags?

Is the problem with the way tags are displayed in the user interface?

Is the problem something else I don't understand?

Is the problem that you want to tag Place|AT|<all the ones I listed above> and be able to select by Place|AT ?

Reading all the the issues and PR's it seems that there was problem and you figured a way to work around it, but now the work around has problems and that seems to be what is being addressed.  Perhaps we need to go back to the root problem and see if there isn't a better solution to it.

**Comment by quovadit** [comment]
@wpferguson : thanks for taking the time to take a detailed look at this topic.

The concrete problem with the current limitation is the following:

I like hierarchical tags in darktable (place|AT|Wien), but I need simple tags on export.

Currently there are two options:
- default: export all parts separately (place, AT, Wien)
- omit hierarchy: export only the last part (Wien)

What I want to achieve is to export all value-parts, but no categories (AT, Wien)

So I need a way to tell darktable, that in this case not only Wien is a value, but also AT, and only 'place' is the category.

Earlier there have been only two levels in hierarchy, so it was clear: the first level is the category, the second one is the value.
Now you can have multiple hierarchies, and darktable assumes that all except the last level are categories.
That's not true in all cases, so I created this PR.

I hope it's clearer now, sorry for the confusion

**Comment by phweyland** [comment]
I'm just confused with the @quovadit's post above.
#6665 & #8227 are just misinterpretation and confusion. It's better to forget.
#8270 brings a quick way to create a tag on a node (meaningful only on tag tree view) where this is not yet a tag. Quite simple and nothing new.
[# 326](https://github.com/darktable-org/lua-scripts/issues/326) is a need which deserves to be discussed.
