### ISSUE TITLE
PFM imports as linear but sRGB is shown for colorin module

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#6666]
**To Reproduce**
1. Download PFM and EXR samples at http://www.pauldebevec.com/Research/HDR/PFM/
2. Import the EXR sample and verify the input profile is "embedded matrix" 
3. Import the PFM sample and verify the input profile shown is "sRGB"
4. Re-select/re-activate the "sRGB" input color profile
5. The image tone changes dramatically
6. Select "linear Rec709 RGB" input color profile instead
7. The image is restored to the initially imported state (and matches the EXR)

**Expected behavior**
colorin should show the actual profile that was used after import (i.e. "linear (709)" fallback in the PFM case?)

**Platform (please complete the following information):**
 - darktable version: 3.3.0+1248~g479426b49
 - OS: Windows 10

**Comment by kmilos** [comment]
Still the case after all the gui init accel changes in 3.3.0+1330~gdcc2032de

**Comment by kmilos** [comment]
This was OK btw in 3.2.1, colorin shows linear 709 on import...

**Comment by aurelienpierre** [comment]
Notice that PFM is a technical exchange format, as far as I know, it doesn't store any metadata, so the color profile is not inside it and needs to be set by user.

**Comment by kmilos** [comment]
Oh, no argument there! Not expecting wonders with no metadata around ;)

The bug is that the linear 709 fallback (perfectly valid starting point) is used by the pipe to provide the initial render (set around [here](https://github.com/darktable-org/darktable/blob/024988292eb32d1ef2ea354ac1d9fd51f23e6e55/src/iop/colorin.c#L1600) I presume?), but colorin GUI combobox was out of sync and reflecting sRGB...

Btw, I tested your #7029, seems unrelated to this after all (log is attatched.)

[debug_pfm_import.zip](https://github.com/darktable-org/darktable/files/5592976/debug_pfm_import.zip)

**Comment by kmilos** [comment]
Re the proposed fix (I'll test and feedback in a bit): there's really no better way of keeping the pipe and the GUI in sync? I see quite a few strcmp(ext, ...) around there (not just PFM related), it just doesn't feel "nice"...

**Comment by aurelienpierre** [comment]
No I don't see another way, we will have to test every file extension, one way or another.

**Comment by kmilos** [comment]
Ok, merci
