### ISSUE TITLE
Wrong Film roll sorting order 

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#6668]
**Describe the bug**
The sorting order of film rolls does not match the sorting order of folders if 'recent to older' is set.

**To Reproduce**
1. preferences: sort film rolls by: folder
2. preferences: sort collection recent to older: true
3. Collect by folders --> 2020 on top of the list (OK)
4. Collect by film roll --> 2020 on bottom of the list (NOK)

**Expected behavior**
If 'sort by folder' is selected, the sorting order of film rolls should match the sorting order of folders.
So if 'recent to older' is set, the newest film rolls (2020...) should be on top.

**Screenshots**
![sort-filmrolls](https://user-images.githubusercontent.com/5677563/97504317-eee8c680-1976-11eb-85d9-8e3185cd2c45.png)

**Platform:**
Darktable Version: 3.2.1
OS: Linux Mint 20 Cinnamon
OpenCL activated
NVIDIA Driver Version: 450.80.02

**Comment by elstoc** [comment]
I think the tooltip on that option (sort recent to older) is quite explicit that it's designed to work for folders and dates/times only - i.e. not for film rolls. The only thing you can choose for the film roll sorting is whether to sort by "id" (the date a film roll was first imported) or by "folder name", using the "sort film rolls by" option.

So this is working as designed.

**Comment by quovadit** [comment]
That's true, 'recent to older' affects the folder-sorting.
But as 'sort film rolls by folder' is selected, the film-roll sorting should match the folder-sorting.

![sorting-setting](https://user-images.githubusercontent.com/5677563/97633349-46993780-1a34-11eb-9bf3-d64ba58d683c.jpg)

**Comment by elstoc** [comment]
My fix would be to clarify the tooltip. Sorry.

**Comment by quovadit** [comment]
That would be very sad, because I don't use film-rolls only because of this sort-order.
This is quite annoying, because 'film-roll' is the default and pops up on every new query.

Would it be easier to make the default search-criteria customizable (e.g. folders instead of film-rolls)?

**Comment by elstoc** [comment]
You could create a preset

**Comment by junkyardsparkle** [comment]
It's a little bit odd that "sort film rolls by" has a dropdown list for only two options... why not add another one for reverse alphanumeric? Of course, we should also clarify that the options refer to alphanumeric sorting and not the setting in the other  preference.

**Comment by elstoc** [comment]
> why not add another one for reverse alphanumeric

I never really understood why the 'reverse' control wasn't part of the collect module itself. Perhaps it's troublesome for the hierarchical displays?

**Comment by quovadit** [comment]
After the discussion here and in pull request #6709 I am now convinced that the sorting-order should not be set in preferences  but in the collect module itself.

So here is another suggestion:
![sort-popup](https://user-images.githubusercontent.com/5677563/98292306-ced78980-1fac-11eb-9e59-6bd474f0d30b.png)


I still don't think there should be an always-visible-sorting-button, because
- other functions in the collect-module are way more important
- there is limited space
- the sorting function is not relevant for all kind of collections

So like Adobe Lightroom or MS Excel I would place the sorting function to the burger-menu ☰

And I think the sorting option should be only visible if it makes sense (folders, filmrolls, dates), because
- I don't see the usecase, where it would be helpful to sort ISO or aperture descending
- I don't know any tool where you can sort lists other than folder or date
- it would be unexpected that ISO is sorted descending after setting filmrolls to be sorted descending

Finally the type of sorting for filmrolls (id/folder) could also be set in this menu.

Looking forward to your comments!

**Comment by elstoc** [comment]
> I would place the sorting function to the burger-menu ☰

I'm not sure. This is a pretty standard menu thoughout darktable. It is called the 'presets' menu because it's for presets. I'm not convinced we should start putting other stuff in there.

**Comment by TurboGit** [comment]
I'm not convinced, the preset menu is for preset.

For the sort by id or folder we can keep the preference.

For the sort alphabetically we need the same kind of UI interaction for such action already used in dt, that is an arrow on a toggle button that show the actual sorting.

**Comment by elstoc** [comment]
> an arrow on a toggle button that show the actual sorting

It is hard to see a nice place to put it on the collect module's UI, where it wouldn't be confused with the use of the same icon both in the combobox and to the right of the entry box.

**Comment by TurboGit** [comment]
Agreed, not easy... maybe adding an entry in the combo on the right:

![image](https://user-images.githubusercontent.com/467069/98298857-f6cbea80-1fb6-11eb-8223-9b884bf97873.png)

**Comment by TurboGit** [comment]
Adding an option (after a separator) under `"exclude images"` ?

**Comment by elstoc** [comment]
It's less bad than the presets menu

**Comment by quovadit** [comment]
if it is added to this combo, I think the sort order has to be stored separately for every property, as it is defined in the context of one property.

This would also solve the problem, that sorting date descending affects ISO as well.

**Comment by TurboGit** [comment]
Ok, why not.

**Comment by quovadit** [comment]
![sort-popup-2](https://user-images.githubusercontent.com/5677563/98301173-a5255f00-1fba-11eb-9fec-3c611aeb5a28.png)

**Comment by TurboGit** [comment]
@quovadit : Yes, that looks the best way we can handle this.

**Comment by elstoc** [comment]
Though if you have two options they should be radio buttons and not tick boxes.

**Comment by TurboGit** [comment]
@elstoc : Yes, of course you are correct !

**Comment by quovadit** [comment]
Meanwhile there is a separate preference dialog in the collect-module (see  #7530)

So what would be the best way to define the sorting order (ascending/descending) now?

a) as suggested in PR #6797 : 
![sort-a](https://user-images.githubusercontent.com/5677563/103540718-77fe0b80-4e9a-11eb-8bd5-0cbc53090389.png)

b) in  the burger-menu ☰ (like the new preferences):
![sort-b](https://user-images.githubusercontent.com/5677563/103542377-1f7c3d80-4e9d-11eb-8f99-c7e7b9d17940.png)

c) in the new preferences dialog:
![sort-c](https://user-images.githubusercontent.com/5677563/103544792-e9d95380-4ea0-11eb-801b-9995cd660dd5.png)

**Comment by TurboGit** [comment]
It should be in the preference dialog to me.

**Comment by GLLM** [comment]
Ohhh, how I wish the issue #4976 would have been solved by this one ... with an additional tiny tickbox "include subfolders" ;)
@quovadit it will not be, am I right ?

Thanks

**Comment by quovadit** [comment]
this issue is just about sorting, so let's discuss the subfolders at #4976

**Comment by phweyland** [comment]
First I agree that film-roll and folder should behave the same way.

But going just a bit further, film-roll is nothing more (or less) than the flat view of the hierarchical folders. 
If you ask me, I would just add a preference to choose between the flat view and the hierarchical view and I would remove the per id film_roll sorting.

**Comment by elstoc** [comment]
> remove the per id film_roll sorting

I agree - I never understood the logic behind this change

**Comment by quovadit** [comment]
It's true that film roll is a flat folder view.

But I would definitely not remove the per id film_roll sorting, because it makes sense, that by default the last import is always on top, even if my folders do not start with a date.

And I like the idea of film-roll as 'basic element for organizing images in darktable' (as dtdocs calls it).
It doesn't matter where your images are located, the film roll name is just the name of the parent folder.

If your folder-names start with a date, you can change the setting to 'sort by folder', so that film-rolls are always sorted chronologically, even if you import an older photo-session.

**Comment by johnny-bit** [comment]
In my "normal" library my folders are named by date and topic. In my "dev test" library, it's haphazard, so softing by film roll id is great. And in day-to-day "normal" flow I import images after every photoshoot so usually film id sorting = date sorting. So I would vote to not remove per id sorting.

**Comment by elstoc** [comment]
Thanks both for explaining some use cases - at least now I can see a point to it :)
