### ISSUE TITLE
Sony Alpha 7c, ILCE-7C

### ISSUE THREAD

**Issue by lothar-klein** [darktable-org/darktable#6669]
Could not find support for the new camera "Sony Alpha 7c", also known as  "ILCE-7C".
I have uploaded two sample raw files (compressed and uncompressed).

**Comment by LebedevRI** [comment]
Thank you for the contribution!

**Comment by frantic1048** [comment]
Encountering same issue here after upgrading my old camera, uploaded one sample raw file (compressed, with Adobe RGB color mode).

If there's any missing info about the camera, please let me know and I will provide as much as I can. :)

**Comment by frantic1048** [comment]
Just submitted my patches ( darktable-org/darktable#6776, darktable-org/rawspeed#250 ) to make darktable support SONY ILCE-7C.

I used `dngmeta.sh` (followed instruction in `adobe_coeff.c`) on DNG file converted with Adobe DNG Converter 13.0 (Macintosh) to retrieve the metadata in PR above.

I mostly referenced patches around  #3070 `Sony ILCE-7RM4 camera support`, and don't know if there's any further work to resolve this issue. :thingking:

BTW I use Arch, I have built the patched darktable package based on darktable `3.2.1` tag.  I could provide a pre-built package for Arch guys who are interested in the patches. However, I could not ensure it is working correctly before reviewing by darktable developers. It just "looks" working with ILCE-7C's raw file.

![2020-11-08-013753_3840x2111_scrot png](https://user-images.githubusercontent.com/3102803/98448864-3d157b00-216a-11eb-81dd-617437eb8253.jpg)

**Comment by LebedevRI** [comment]
Thanks!

**Comment by JonDum** [comment]
Hello! I built and tested `master` at `650c353` and while I can now open RAWs from my ILCE-7C, when I try to activate the lens corrections module, Darktable does not detect that it was taken from this camera (nor can I find ILCE-7C in the camera selection list). Also, when I activate the profiled denoise module, I get a "mega airbrushed" scene. This denoiser works perfectly with my A7 iii so I'm guessing that the profile for denoising just isn't linked correctly?

How can I best help in fixing this?

**Comment by frantic1048** [comment]
@JonDum Some info I found which may help:

- lens correction: lensfun/lensfun#1325, merged just a few days ago, we could try `lensfun` with at latest `master` branch to see if lens correction works.
- noise profile: darktable-org/darktable#7217

**Comment by sbradl** [comment]
@JonDum updating you lensfun database should be enough to enable lens detection

**Comment by julian-alarcon** [comment]
Documentation should be updated https://www.darktable.org/resources/camera-support/
