### ISSUE TITLE
[darkroom] snapshot and contrast equalizer very unresponsive {bisected}

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6672]
**Describe the bug**

Snapshot tool and contrast equalizer are very unresponsive when on 200% zoom
(not only snapshot also the whole response in the UI seems effected)

Snapshot is for demonstration purpose only

I am working "scene referred"

(it is not a pixlepipe re-fire issue, I have observed the output of darktable -d all, no reaction there)

**To Reproduce**
1. Go to darkroom and zoomm to 200% (me using middle mouse button twice)
2. make a snapshot
3. change to a duplicate (and modify a bit, to see the differences of the two, e.g. exposure or WB)
4. move slider
5. see error

**Expected behavior**

responsive as it was

**bisect**
bisect gave me:
```
cfc0e5b990faeea41669521a0c4e7f75ec31d3dc is the first bad commit
commit cfc0e5b990faeea41669521a0c4e7f75ec31d3dc
Author: Pascal Obry <pascal@obry.net>
Date:   Tue Oct 27 23:18:27 2020 +0100

    Use CAIRO_FILTER_BEST as default filter for darkroom.
    
    Tis patch introduce a filter level for the darkroom. It is set
    to best by default and will be set to good in performance mode
    for slow computer.
    
    Fix darkroom very smothed picture when zooming at 1600% on
    default setting.
    
    Part of #6425.

 src/gui/gtk.c        | 2 ++
 src/gui/gtk.h        | 1 +
 src/views/darkroom.c | 8 ++++----
 3 files changed, 7 insertions(+), 4 deletions(-)
```

@TurboGit may I ping you here?

**Platform (please complete the following information):**
* darktable version : 3.3.0+1248~g479426b49
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
 - Are the steps above reproduce with a fresh edit (removing history)? **YES**
 - Is the issue still present using an empty/new config-dir 1 **YES**
- with or w/o opencl **still persistent**

**Comment by AxelG-DE** [comment]
In 3.3.0-1259-gcf2ba393b the effect seemed to be disappeared

**Comment by TurboGit** [comment]
Yes, probably fixed by my commit pushed today.
