### ISSUE TITLE
Denoise Profiled extremely slow

### ISSUE THREAD

**Issue by stakaz** [darktable-org/darktable#6674]
Hello, I have a problem wit the Denoise Profiled Performance. It takes extremely long to calculate it, especially in zoomed mode. The "local means" seams to be faster than the wavlets but both cases are incredibly slow.

Here are some numbers:

```plain
1455.007278 [dev_pixelpipe] took 6.603 secs (36.096 CPU) processed `denoise (profiled)' on CPU, blended on CPU [full]
1486.736498 [dev_pixelpipe] took 31.729 secs (162.544 CPU) processed `denoise (profiled) non-local means' on CPU, blended on CPU [full]
1486.768810 [dev_pixelpipe] took 0.032 secs (0.147 CPU) processed `exposure' on CPU, blended on CPU [full]
1486.822564 [dev_pixelpipe] took 0.054 secs (0.224 CPU) processed `base curve' on CPU, blended on CPU [full]
1486.871324 [dev_pixelpipe] took 0.049 secs (0.213 CPU) processed `input color profile' on CPU, blended on CPU [full]
1488.079812 [dev_pixelpipe] took 1.208 secs (6.899 CPU) processed `color look up table profile' on CPU, blended on CPU [full]
1488.154034 [dev_pixelpipe] took 0.074 secs (0.175 CPU) processed `vibrance' on CPU, blended on CPU [full]
1489.022808 [dev_pixelpipe] took 0.869 secs (2.552 CPU) processed `local contrast' on CPU, blended on CPU [full]
1489.112896 [dev_pixelpipe] took 0.090 secs (0.534 CPU) processed `tone curve profile' on CPU, blended on CPU [full]
1489.181327 [dev_pixelpipe] took 0.068 secs (0.336 CPU) processed `output color profile' on CPU, blended on CPU [full]
1489.216430 [dev_pixelpipe] took 0.035 secs (0.194 CPU) processed `display encoding' on CPU, blended on CPU [full]
```
But it can go up to 100 secs.

I use the Arch Linux package with DT 3.2.1

My system is fast but without a dedicated graphics card:
- i7-10510U CPU (4 cores with up to 8 threads)
- 16 GB Ram
- Intel UHD 620 Graphics Card
- 4k display
- no OpenCL

I wonder if it is a normal behavior or not?

**Comment by Nilvus** [comment]
Denoise profile is powerful but slow. It's normal and should be improved in next release. Having powerful denoising need time, especially with no OpenCL card. Time also depends on denoise settings. The more you try to reduce the noise, the more CPU is needed, and time depending on CPU.

Think about closing this issue. @rawfiner works to improve that as much as possible. And of course, trying to improve speed AND keeping quality of the module (and improve it if possible).

**Comment by MStraeten** [comment]
workaround for it: set denoise (profiled) once and then disable the module until you finished editing - so darktable keeps quite responsible while editing. it makes sense to disable tone equalizer while setting denoise (profiled) this is also performance consuming (will be better with 3.4) especially when zoomed in.

**Comment by stakaz** [comment]
Well, thanks for the quick replies. I was wondering because the last time I used darktable about two years ago on a much slower machine, I cannot remember having this issue.

I understand that it is a calculation consuming algorithm but I wonder about **how much** slower it is compared to the other.

Of course the workaround with disabling would be an option. Just curious, if something else slows down this particular algorithm in my cdase.

**Comment by Nilvus** [comment]
It's just because denoise profile module as known a huge set of improvements in noise reduction at the cost of important power needed.  You could test a version of that module 2 years ago and that one and you will see that you have new options and a much much better noise reduction. And that improvement make that module the better one for noise reduction, but yes at the cost of being slower. Anyway, 3.4 should improve speed.

**Comment by Nilvus** [comment]
Please close think about closing that issue as there's no issue.

**Comment by stakaz** [comment]
Thanks, that sounds promising and makes sense. Will close now.

**Comment by rawfiner** [comment]
speed has indeed been improved (not by me, by ralfbrown :-) )
Still, it is quite strange you get such bad speed in darkroom.
Is toneequalizer enabled? If so, it is a known issue: #3081 (which is fixed in master :-))
If toneequalizer is not used, could you test again without any other modules (only the ones that cannot be disabled)?

**Comment by stakaz** [comment]
Hello @rawfiner, you are right, I have installed the git version from AUR and now much better timing are observed:

```plain
6017.139511 [dev_pixelpipe] took 0.002 secs (0.006 CPU) initing base buffer [full]
6017.146177 [dev_pixelpipe] took 0.007 secs (0.018 CPU) processed `raw black/white point' on CPU, blended on CPU [full]
6017.148334 [dev_pixelpipe] took 0.002 secs (0.009 CPU) processed `white balance' on CPU, blended on CPU [full]
6017.150445 [dev_pixelpipe] took 0.002 secs (0.013 CPU) processed `highlight reconstruction' on CPU, blended on CPU [full]
6017.192293 [dev_pixelpipe] took 0.042 secs (0.244 CPU) processed `demosaic' on CPU, blended on CPU [full]
6020.068478 [dev_pixelpipe] took 2.876 secs (21.441 CPU) processed `denoise (profiled)' on CPU, blended on CPU [full]
6020.080594 [dev_pixelpipe] took 0.012 secs (0.090 CPU) processed `input color profile' on CPU, blended on CPU [full]
6020.276507 [dev_pixelpipe] took 0.196 secs (1.541 CPU) processed `color look up table' on CPU, blended on CPU [full]
6020.311662 [dev_pixelpipe] took 0.035 secs (0.251 CPU) processed `tone curve' on CPU, blended on CPU [full]
6020.331007 [dev_pixelpipe] took 0.019 secs (0.140 CPU) processed `output color profile' on CPU, blended on CPU [full]
6020.344857 [dev_pixelpipe] took 0.014 secs (0.105 CPU) processed `display encoding' on CPU, blended on CPU [full]
6020.352696 [dev_process_image] pixel pipeline processing took 3.215 secs (23.863 CPU)
```

But with 3.2.1 I actually cannot tell you anymore whether the I had a tone equalizer enabled or not.

Thanks for the hints.
