### ISSUE TITLE
Simple filter by color label next to star rating

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#6675]
**Problem**
I love using color labels as alternative to Adobe Lightrooms 'quick selection'
But: it is quite complicated to filter by color labels using the 'collect images' module

**Solution**
I want to be able to filter by color labels with one click (similar to rawTherapee).

![color-filter](https://user-images.githubusercontent.com/5677563/97576493-876e5d80-19ee-11eb-9358-975d0603c2dd.png)

Underneath the thumbnails there already are the color labels next to the star rating.
So it would be consistent to add the color filter above the thumbnails next to the star rating as well.

Because darktable allows more than one color label for 1 image, it's not just on/off, but more sophisticated:
- using a drop-down you can switch between intersection (∩) or union (∪)
- more than one color can be selected, according to the drop-down only images with all or one of them are shown
- clicking on a empty color ring fills the circle and activates this color as filtered
- clicking on the filled circle adds a cross (x) and excludes all images with this color
- clicking on the cross resets the filter again
- the grey circle shows only images without any color label (the same as crossing all other colors)
- crossing the grey circle shows all images with any color (the same as filling all other colors with union)

**Alternatives**
- The current alternative is to narrow down the search in the 'collect images' module (5 clicks instead of 1).
- Another alternative would be, to implement the 'quick selection' functionality

**Comment by wpferguson** [comment]
You can also use sort by and sort by color labels

**Comment by quovadit** [comment]
yes that's true, but it's a very limited alternative.
I use colors to hide specific images, or to only show defined images, e.g. for efficient culling.
Both is not possible with sorting.

**Comment by wpferguson** [comment]
> I use colors to hide specific images, or to only show defined images, e.g. for efficient culling.

So what do you use stars for?  Using stars you can hide specific images, or show only defined images.

**Comment by quovadit** [comment]
I use stars for my permanent rating, so it's the result of my cullilng.
Color labels are just temporary helpers during the culling process.

**Comment by pahl34** [comment]
I support this idea, also missed this kind of filter quite regularly. Got kind of used to using the collect module instead, but I think it would be nice to have this.

**Comment by carobinario** [comment]
>  I want to be able to filter by color labels with one click (similar to rawTherapee).

Nice enhancement. I hope developers add this feature to the next version.

**Comment by kapalex** [comment]
+1 on this one, feel it is missing

**Comment by Solarer** [comment]
Yes, the filtering feels a bit incomplete not being able to do this.

**Comment by kvaps** [comment]
I was surprised when didn't found this opportunity, it should be very useful feature

**Comment by icebearsoft** [comment]
I miss the possibility to select by color tags too. Without such possibility the dolor tags are useless. I use stars for rating and I would like to use colors for another type of classification.

**Comment by johnny-bit** [comment]
Selecting by color tag is possible via collections (collect images):

![Zrzut ekranu z 2021-06-05 06-47-53](https://user-images.githubusercontent.com/10687765/120880322-2634eb00-c5ca-11eb-9216-d9e3c781befe.png)

having to move that to filter location might not be a bad idea ;)

**Comment by schuster-rainer** [comment]
It's also a very common use case in got used to in lightroom. So having  darktable have that filter would be amazing, as a workaround I'll try this collections thing. But it won't do the trick exactly, because i just want to filter the current folder of picuters not all my collections. Filters are a temporary tool for quick and easy finding. Collections is more something permanent. I probably also would use filters just as a temporary tool for organizing images from one collection for quick access and rather remove them afterwards instead using them for permanent/long living collections.

**Comment by johnny-bit** [comment]
you can combine collections into a single filter that has say your filmroll, with images with `red` label and tagged like you want and having more than 3 stars... Collections are more powerful than filters and are not that permanent ;)

however convinience filters like that are nice.

**Comment by icebearsoft** [comment]
Yes but I still have problems even with filmrolls because they have the name of the last part of path to the folder and I still see the filmrolls and thumbnails even if the folder no longer exists on the disk and I do not know how to get rid of them. If I see the images in lightable, I know with which images I work.

**Comment by dbrgn** [comment]
Please keep it open, issue bot. This feature would be useful.

**Comment by fromagek** [comment]
I would like this feature as well!

**Comment by elstoc** [comment]
+1 for this

**Comment by lnicola** [comment]
> Selecting by color tag is possible via collections (collect images):

I'd like to search by color inside the current film roll, so that doesn't seem like a great workaround.

**Comment by ptilopteri** [comment]
the "current film roll" IS a COLLECTION.  You just need to add another selection parameter
to the current collection.  You have the ability readily available to do what you want, just not
in the particular manner you want.

another dedicated search parameter is just more clutter.

**Comment by elstoc** [comment]
> You just need to add another selection parameter

So you're ok if we get rid of the rating filter as well?

**Comment by ptilopteri** [comment]
no, 
perhaps I misunderstand

**Comment by elstoc** [comment]
ratings and color labels are essentially used for similar purposes: categorising of images _within a collection_. So having quick filters for combinations of ratings/color labels in the top bar makes perfect sense to me. Adding an extra criteria to the collections module is too much effort for something I want to be able to alter quickly.

**Comment by kvaps** [comment]
this is still actual request

**Comment by phweyland** [comment]
Making a try:
![image](https://user-images.githubusercontent.com/23012047/147610790-57ed2d31-0128-42ab-8e4e-ce2c0a42ab91.png)

**Comment by elstoc** [comment]
Is it confusing to allow both inclusive and exclusive filters here? I'd have thought that a simple toggle for each colour would be sufficient.

**Comment by elstoc** [comment]
I'm fine with this in principle but I find the combination of inclusive, exclusive fileters and union/intersect a bit confusing to read.

I know it's less functional than requested but just simple inclusive toggles might be better, leaving more complicated combinations to the collections module.

**Comment by Solarer** [comment]
Also add one button for "unlabeled". That should cover most cases

**Comment by quovadit** [comment]
> I find the combination of inclusive, exclusive filters and union/intersect a bit confusing to read [...]
> leaving more complicated combinations to the collections module

I don't think we should move all complex combinations to the collections module.

I often use filters to 'show red label' or 'hide green label', so it would be great to have both with 1 or 2 clicks!

It's true that you can create very complex combinations with inclusive/exclusive and union/intersect, but why should this be a reason not to allow it?

Even the existing star-rating filter allows weird usecases:
- '≠ 3' shows 1,2,4,5 - why would I want to do that?
- '> 3' is also weird, why not use >=4?
- even '> 5' is possible, which of course always is empty  

Of course we could add tooltips:
- colors:
click once to show (●), click twice to hide (X)
- toggle:
intersection (∩): only images having ALL selected colors
union (∪): all images with at least ONE selected color

An alternative would be to hide with ctrl-click (instead of two clicks).

And to avoid clutter we could hide the toggle until at least two colors are selected.

**Comment by icebearsoft** [comment]
Of course, in principle it can be implemented in such a complex way thet nobody will understand what is selected by the current combination. Such complexity will not be useful. Make it as simple as possible.

**Comment by quovadit** [comment]
I think with my last two suggestions (ctrl-click to exclude, and hide union-toggle by default), it is extremely easy to understand:
- I click on red, and only images with a red label are shown
- I click on green, now two colors are highlighted, the number of images is reduced, so it's clear that I just narrowed down my filter. In addition the toggle union/intersect appears, so I see, that I can change the type of combination of these two colors I just selected
- The tooltip of the toggle explains what it does, so I can change the intersection to a union
- the tooltip of the colors tells me, that I can also ctrl-click on a color to hide it

I really don't see, why this should not be understandable.

Maybe we need a possibility to reset the color-filter-combinations to default, if I played too much and got lost (e.g. X analog to the text-filter).

In general: I love dt because of its powerfulness, so I don't think that the main goal should be to make it as simple as possible, but as useful as possible.

**Comment by elstoc** [comment]
> I don't think that the main goal should be to make it as simple as possible, but as useful as possible.

The thing is that the collections module already does these useful things. IMO the colour selection at the top of the screen _should_ be simple.

**Comment by quovadit** [comment]
so what about keeping ctrl-click to hide, but dropping the union/intersect toggle?

**Comment by TurboGit** [comment]
This is looking too complex to me but maybe I'll be convinced that it is not :) Fact is that we can already do that with the collection module so we are duplicating features here. The collection is design to select a set of images and the filters on top of the lighttable is there to organize this set (ordering) and filtering based on stars rating to concentrate on part of the set.

Adding operator, selection on color labels, text filter there is adding quite a bit of complexity to me.

**Comment by quovadit** [comment]
of course it's a duplication of features, that's the whole content of this issue.

Users who just want a simple filter will only click on the color-labels to show them.

Only expert users who know what they are doing (because they've read tooltips / dtdocs) will also ctrl-click to hide specific colors.

On the other hand we could simplify the rating-filter, and reduce the first drop-down to a toggle ' >= '  /  ' = '

**Comment by TurboGit** [comment]
> On the other hand we could simplify the rating-filter, and reduce the first drop-down to a toggle ' >= ' / ' = '

We also need the `rejected` & `non rejected` selection.

**Comment by quovadit** [comment]
> We also need the `rejected` & `non rejected` selection.

yes, of course, also  'unstarred only' is very useful.

But now we have two drop-downs, and the first drop-down with 6 operators could be reduced to a toggle with 2 options.

**Comment by Solarer** [comment]
Simplifying the rating filter is probably a good idea :stuck_out_tongue: 

Regarding the color filter, usually I want to see all of only one color or all unlabeled images. Rarely I want to see pictures with color A and pictures with color B at the same time but I don't know if I ever had a use case where I wanted to see only pictures that had A and B label combined.

I could see it work as following:
- One button per color label + "1 button for unlabeled pictures"
- each button can be active/inactive (simple mouse click)
- if all buttons are active show all pictures
- if all buttons are inactive also show all pictures (?)
- otherwise show only pictures that have one of the active buttons (non-exclusive or)
- have one button or key combination to enable/disable all buttons at once for resetting filtering

**Comment by quovadit** [comment]
@Solarer : so you are describing the union-mode. For me the intersection-mode would be much more useful.

It seems, that there are lots of different usecases, so it's not easy to find one simple solution for everyone.

The simplest possible solution would be to only allow the selection of one color at once, so there is no need to decide union/intersect.

But of course this would massively limit the functionality.

So I still think that the hidden complexity would be the best solution (toggle not visible if only one label selected, hide with ctrl-click)

**Comment by johnny-bit** [comment]
It's better to have hidden complexity than deliberately limit useful functionality IMHO.

**Comment by AlicVB** [comment]
As I've done for the "search entry" PR, I'd like to point that I don't think we are going to the right direction with all this... I already see valid requests about adding other fields to this "filter" bar (what about "developed images, images types, ...) @phweyland has recently raised the -valid too- point that presets would be good, we have request for multiple sorting too...
this filter module tend to become a very "heavy" thing, imho just because the collect module is not user friendly, hard to use and needs lot of "clicks" to achieve simple tasks...

tbh, I've already start to work on this in draft #10733 so I'm not exactly neutral here ;)

**Comment by Solarer** [comment]
@quovadit sorry, maybe I missread your suggestion a little bit. I sounded a bit complex because each button has 3 states. 
If we add the modifier to choose between union and intersect (as per your proposal) but reduce the number of button states to 2 (show / do not show) does that not cover all use cases?

**Comment by Solarer** [comment]
@quovadit sorry, I missread your suggestion a little bit. I sounded a bit complex because each button has 3 states and I thought all cases could be covered with 2. But you are right, if I want to see pictures AB but not ABC I must disable C explicitly.

Sounds good to me now

**Comment by phweyland** [comment]
> It's better to have hidden complexity than deliberately limit useful functionality

👍 +1

**Comment by phweyland** [comment]
Hiding complexity.
By default:
![image](https://user-images.githubusercontent.com/23012047/147762074-d5a45b08-0524-437d-bf05-3f845c62035a.png)
With one selection:
![image](https://user-images.githubusercontent.com/23012047/147762274-4944fbcb-8fc5-45ba-ab04-66b7edc9df88.png)
With two selections:
![image](https://user-images.githubusercontent.com/23012047/147762375-b0845ab5-3de9-4882-bb56-f71e6047ada0.png)
Using Ctrl-click:
![image](https://user-images.githubusercontent.com/23012047/147762441-68b50678-0265-479a-ae6c-d67c9ee67c6b.png)

**Comment by icebearsoft** [comment]
This looks perfect.

**Comment by AlicVB** [comment]
@phweyland : you realize that you have been appointed to help me for the "friendly widgets" part of my PR #10733 right ? :D
