### ISSUE TITLE
strange effect with "updated xmp sidecar files found" 

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#6678]
Found a strange effect in Linux (localized). 

The collection path contains non-ascii characters. In darktable "preferences -> storage -> look for updated xmp files on startup" is checked. 

If "english" is set in "preferences -> general -> interface language", then the "updated xmp sidecar files found" dialog box will not open. If you select ANY other language, then this dialog opens properly.

p.s. This may be related to commit dd18f18 "crawler: Hopefully better fix for #4133"

Darktable Version: master
OS: Debian 10

**Comment by johnny-bit** [comment]
I've checked the issue on `3.7.0+1~g05bdc45ac` and indeed the issue IS present - the updated XMPs are NOT being found on Linux when folder contains utf8 chars :/ however this works on Windows...
