### ISSUE TITLE
user-defined default presets

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6682]
Auto-apply presets are great but it would be really useful to have them automatically reapply if resetting a module's parameters or going back in the history stack.

As a suggested solution for this, for both iop and lib modules, allow the user to define a preset named "default" which, if present, will be applied by default for new images or reapplied automatically when the user clicks on the 'reset parameters' button.

**Comment by junkyardsparkle** [comment]
I've pondered this question once in a while during certain workflows. The thing is, implementing it this way would mean that there are multiple ways to activate the user-default, but no way to activate the module defaults if you want to... so this feature could only really be used in cases where you won't ever want to activate default-default. I'm not sure how often that would be the case for me, but I'll try to collect some thoughts about that during my next sessions.

Out of curiosity, is there a particular module/workflow itch that you're scratching here? :-)

**Comment by elstoc** [comment]
I do still use shadows & highlights occasionally and I have the sliders default to zero. I know it's just a couple of clicks to get it back again using a preset but I'm all for slick workflows. I have a similar default sharpening preset with the contrast equalizer.

I'd be happy with an alternative method, such as Ctrl+click on the reset button to reapply any auto presets. Actually thinking about it that might be better.

**Comment by junkyardsparkle** [comment]
> I'd be happy with an alternative method, such as Ctrl+click on the reset button to reapply any auto presets. Actually thinking about it that might be better.

That makes more sense to me. It would give something like the functionality of nuking history, but for a single module.
