### ISSUE TITLE
metadata export: $(CATEGORYn(category)) includes multiple copies of level n if there are tags in level n+1

### ISSUE THREAD

**Issue by guille2306** [darktable-org/darktable#6683]
**Describe the bug**
When using the $(CATEGORYn(category)) variable on the "edit metadata exportation", multiple copies of the n-level tag are exported if there are also n+1-level tags attached to the image (one per extra n+1 tag).

**To Reproduce**
- Create the following tag tree:
```
location
  |- Argentina
     |- Bariloche
     |- Rosario
```
- Attach to an image the tags "Argentina" and "Bariloche"
- Define the following mapping on the "edit metadata exportation" dialog:
```
Xmp.photoshop.Country -> $(CATEGORY0(location))
```
- Export the image

The "Country" field in the resulting image gets populated with "Argentina,Argentina"

**Expected behavior**
The "Country" field in the resulting image should be "Argentina" (only one)

**Platform:**
 - Darktable Version: 3.2.1
 - OS: Kubuntu 20.04.1 LTS with KDE backports, up-to-date

**Additional context**
- Removing the "Bariloche" tag results in a single "Argentina" in the export field
- Conversely, attaching both "Bariloche" and "Rosario" results in three copies of "Argentina" in the export field
- I compared old exports from the same image, and this behavior was not present on version 3.0.2 under Kubuntu 19.10 (namely, a single "Argentina" was exported even if "Bariloche" was also attached)
- I suspect of PR #4983, but I can't check it

**Comment by phweyland** [comment]
Makes sense. I'll look at this.

**Comment by phweyland** [comment]
Should be fixed.
But you would simplify your life attaching only the leave (and not the tags of the path, less work) and you would not have found this bug :)
Thanks for reporting.

**Comment by guille2306** [comment]
Thanks!
