### ISSUE TITLE
Missing data in 'image information'

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#6686]
When using a DNG format file that was produced by a Huawei camera-phone I note that both the aperture and the speed information is not available in the 'image information'. I questioned this problem over the dt-forum and have confirmation from an other that this appears to be the same problem on other (Android) cameras.-->
When the DNG file is exported to a JPG file all of the image information including the aperture and speed are correctly written to the EXIF file in the JPG.
I am running the daily git ... Manjaro .. Arch ... XFCE

**Comment by kmilos** [comment]
I guess this is because dt checks for those (and possibly some other Exif tags) only in the [Exif.Photo IFD, while DNGs only contain Exif.Image](https://discuss.pixls.us/t/failed-to-create-lensfun-profile-for-oneplus-6/20902/2)?

**Comment by kmilos** [comment]
Yep, almost everything is pulled only from Exif.Photo [here](https://github.com/darktable-org/darktable/blob/665fc4d2ffd3e55d2fa7a9f1661b2d139d9a11c0/src/common/exif.cc#L722).

Focal length info is curious though, as it uses [Exiv2's own accessor](https://exiv2.org/doc/namespaceExiv2.html#af7758be6d5c4a9a3d8d1cd784d3d0660), no idea though if that one checks all possible IFDs...

**Comment by kmilos** [comment]
Turns out the [Exiv2 accessors do the right thing](https://github.com/Exiv2/exiv2/blob/master/src/easyaccess.cpp).

**Comment by kmilos** [comment]
One has to remove the DNG files from the collection and re-import them unfortunately, I don't know any other way of triggering metadata re-read...

**Comment by davidvj** [comment]
The test that I made was with a re-imported image. Renamed and without 
sidecar.

**Comment by kmilos** [comment]
Bit does it have this patch applied, or you just built clean master?

**Comment by kmilos** [comment]
Here's a demo of master vs PR:

![image](https://user-images.githubusercontent.com/4973094/101049711-0de50480-3584-11eb-9dbf-d0973d44480e.png) ![image](https://user-images.githubusercontent.com/4973094/101050557-cf037e80-3584-11eb-9ea5-515c49b075e0.png)
