### ISSUE TITLE
Darktable crashing on opening an image

### ISSUE THREAD

**Issue by waxhead** [darktable-org/darktable#6696]
**Describe the bug**

Latest git pull, 665fc4d2ffd3e55d2fa7a9f1661b2d139d9a11c0, compiled and starts fine.

Compile command fairly simple:

```
./build.sh --prefix /home/pete/dt --install --sudo
```
On opening an image dt crashes.  The crash dump is attached.

**To Reproduce**

1. Start DT from the command line ./bin/darktable
2. Double click on an image.

**Platform (please complete the following information):**
 - Darktable Version: latest git pull.
 - OS: Linux eeyore 5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64 GNU/Linux
 - OpenCL is not enable.
 
[darktable_bt_GQ00S0.txt](https://github.com/darktable-org/darktable/files/5469975/darktable_bt_GQ00S0.txt)

**Comment by parafin** [comment]
Clean your install directory.
