### ISSUE TITLE
FR: Extra fields in the Image Information module

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#6697]
Hi all.
It has occurred to me that the Width and Height values in the Image Information panel only display pre-cropped values.
Would it be possible to add 2 new fields ("Cropped width" and "Cropped height"?) to reflect the full size of the image after the Crop/Rotate module has done its thing?
Working on multi-image panoramas, where I've NOT used autocrop (in Hugin), I have lots of black pixels around the edges. I do this knowing that I'll crop the image to a particular aspect ratio in darktable later in the workflow. This FR would be most helpful in such circumstances.
Cheers.

**Comment by junkyardsparkle** [comment]
Just a thought: maybe putting the cropped dimensions in parenthesis after the "raw" ones would save some space as opposed to adding more fields.

**Comment by brucewilliamsphotography** [comment]
Good call!

Cheers,
Bruce Williams.

**Comment by johnny-bit** [comment]
Isn't #7279 essentially the same as this one?

This one asks for "cropped width" + "cropped height"
that one asks for "max width" + "max height"
and currently displayed is "sensor width" + "sensor height"

**Comment by japamax** [comment]
Would it be possible to add 2 new fields : 
"ratio" : ratio of final image
"aspect" : corresponding to ratio image square, 3:2 16:10 etc ...
It will usefull in the lighttable tab for export, for thumbnail info or thumbnail tooltip

**Comment by ralfbrown** [comment]
Current master has "export width" and "export height" which reflect the post-cropping size.  I believe this addresses the original request.
However, I noticed that if the cropping is performed by the perspective correction module, the export size shown in the canvas size.

**Comment by johnny-bit** [comment]
I think current "export width/height" covers this FR. Closing. Gotta focus on #7279  now :)
