### ISSUE TITLE
Misleading preference name: 'prefer performance over quality'

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6704]
This is just a suggestion, I don't think using the template makes sense.
'performance mode' has been renamed (I guess in order to make it more descriptive) to 'prefer performance over quality'. While the tooltip still describes that this only affects previews and thumbnails, I think the new name is misleading (it implies that the end result will be affected). I suggest to rename this to 'quick rendering for previews' (omitting 'thumbnails' for brevity).

Also, it may make sense to create a 'performance' category in settings, since now 'performance mode' and 'reduce resolution for preview image', 'demosaicing for zoomed out darkroom mode' and 'high quality thumb processing from size' are located on different tabs. Perhaps the caching-related settings (which are memory/time and disk space/time trade-offs) could also be moved to this 'performance' page. After all, when one tries to tune performance, it'd be way easier to find the settings on a common page than checking several pages for performance-related options.

**Comment by Nilvus** [comment]
> This is just a suggestion, I don't think using the template makes sense.
> 'performance mode' has been renamed (I guess in order to make it more descriptive) to 'prefer performance over quality'. While the tooltip still describes that this only affects previews and thumbnails, I think the new name is misleading (it implies that the end result will be affected). I suggest to rename this to 'quick rendering for previews' (omitting 'thumbnails' for brevity).

The result IS affected so new text is good. This mode is intended for slow computers to, has written, prefer performance over quality. So the new name is not misleading, is it just what is. So I think we need to keep it as it is. And it has been discussed just the past days.

> Also, it may make sense to create a 'performance' category in settings, since now 'performance mode' and 'reduce resolution for preview image', 'demosaicing for zoomed out darkroom mode' and 'high quality thumb processing from size' are located on different tabs. Perhaps the caching-related settings (which are memory/time and disk space/time trade-offs) could also be moved to this 'performance' page. After all, when one tries to tune performance, it'd be way easier to find the settings on a common page than checking several pages for performance-related options.

I agree, and I think we already have performance tab. Actually, it is written as CPU/GPU/Memory. but those settings are related to performance. So maybe, that tab could be renamed performance and split in two sections: CPU/GPU/Memory and rendering with settings you point to.  @elstoc, @jenshannoschwalm and @TurboGit: what do you think about that?

**Comment by elstoc** [comment]
> that tab could be renamed performance and split in two sections: CPU/GPU/Memory and rendering

I don't have a problem with that.

**Comment by kofa73** [comment]
For me, the result is the exported file. According to the tooltip, the setting only affects previews and thumbnails, not output (exported) quality. But if it has been discussed and accepted, the I'm sorry about the noise.

**Comment by jenshannoschwalm** [comment]
You have a point here, although I don't think reordering the preferences would be the big point. 

I think we have far too much preferences settings tuning performance. Maybe we can drop some...

**Comment by Nilvus** [comment]
@kofa73 and @jenshannoschwalm: same as #6706, do you mind if we close this one and add that to #7050 discussion?

**Comment by jenshannoschwalm** [comment]
Fine for me

**Comment by kofa73** [comment]
Then let's close this.
