### ISSUE TITLE
Suggestion: search feature in preferences

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6706]
Many programs that have complex settings (e.g. Firefox, Chrome, Eclipse, IntelliJ IDEA...) allow searching for names of settings to help users quickly find the relevant ones. It'd be nice to have this in darktable, too; a similar feature, to locate modules, has already been introduced in darkroom.

**Comment by jenshannoschwalm** [comment]
I we would have to search for a preference setting... We simply have too many. :-)

**Comment by Nilvus** [comment]
@kofa73: a search feature could be great. But as @jenshannoschwalm said, I think we had too many settings. For 3.6, main preferences will have less settings as some specific modules ones had been moved on modules (in the "hamburger" menu of the module). That allows 2 things:

- quickly find module specific one on the module
- have less settings in main preferences and so find all them quickly

By the way, it's still a WIP and @7050 is all about one. So do you mind if we close this issue and discuss about preferences in #7050 (search feature could be an add... or not, depending on the way we continue to go on)?

**Comment by kofa73** [comment]
Sure, let's close this.
