### ISSUE TITLE
Handling TIFFTAG_DATETIME in TIFF export

### ISSUE THREAD

**Issue by lock042** [darktable-org/darktable#6714]
Could it be possible to export the datetime in the TIFFTAG_DATETIME field? This could be very useful in astrophotography (for example to handle comet timelapse)

Cheers,

**Comment by kmilos** [comment]
I have this tag written in my TIFF exports, here's an excerpt of output from `exiftool -a -u -g1 -s -H`:

```
     ...
---- IFD0 ----
     ...
0x0131 Software                        : darktable 3.2.1
0x0132 ModifyDate                      : 2020:08:21 10:21:29
     ...
```

**Comment by kmilos** [comment]
Yep, different behaviour if the input file doesn't carry that much metadata. Here's the tags I get on PFM import (so no input metadata whatsoever):

```
---- IFD0 ----
0x00fe SubfileType                     : Single page of multi-page image
0x0100 ImageWidth                      : 512
0x0101 ImageHeight                     : 768
0x0102 BitsPerSample                   : 16 16 16
0x0103 Compression                     : Adobe Deflate
0x0106 PhotometricInterpretation       : RGB
0x010a FillOrder                       : Normal
0x010d DocumentName                    : memorial.tif
0x0111 StripOffsets                    : (Binary data 5750 bytes, use -b option to extract)
0x0112 Orientation                     : Horizontal (normal)
0x0115 SamplesPerPixel                 : 3
0x0116 RowsPerStrip                    : 1
0x0117 StripByteCounts                 : (Binary data 3839 bytes, use -b option to extract)
0x011a XResolution                     : 300
0x011b YResolution                     : 300
0x011c PlanarConfiguration             : Chunky
0x011d PageName                        : image
0x0128 ResolutionUnit                  : inches
0x0129 PageNumber                      : 0 1
0x013d Predictor                       : Horizontal differencing
0x0153 SampleFormat                    : Unsigned; Unsigned; Unsigned
```

Really looks like a baseline TIFF, and DateTime is not mandatory.

**Comment by lock042** [comment]
Oh yes, this is not mandatory TIFF tag.

**Comment by lock042** [comment]
But I think I'm wrong. I think that Darktable is doing great.
Sorry for that.

**Comment by kmilos** [comment]
I wouldn't dismiss this so quickly. As demonstrated, it actually might be useful to write some more tags (e.g. `DateTime` & `Software` at least?) [when there is no Exif in the input](https://github.com/darktable-org/darktable/blob/67adcd2ebe40e6478eed65e2c35ed2709e0b5eb8/src/imageio/format/tiff.c#L327).

Perhaps reopen and change subject to a feature request for some future dt version?
