### ISSUE TITLE
Refactor auto-preset code

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6716]
#6687 introduced a new way to reapply automatic presets by Ctrl+clicking on the iop module reset button. In doing so it duplicated quite a bit of code from `_dev_auto_apply_presets()` in `develop/develop.c` into `apply_preset()` in `gui/presets.c`.

This would be better with some refactoring, but this is probably better delayed until after version 3.4.

**Comment by junkyardsparkle** [comment]
It's a nice feature. Would updating the tooltip prior to the refactoring be feasible?

**Comment by elstoc** [comment]
See #6720.
