### ISSUE TITLE
DT 3.3.0-xxx Crop on duplicate not working

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6717]
Steps..
History copying set to overwrite mode.
Ctrl+c copy history from an image on filmstrip in darkroom.
This history has a 5:4 crop in it.

Paste this history on another image (this image had no history other than the defaults).
The crop needed to be changed as it was cropped too much into the image.
So, select the crop module, and cursor over the 5:4 crop, the grid gets displayed.

Now while this grid is displayed, create a duplicate.
[edit] You will see the original copied crop has disappeared.
With duplicate selected.
Go to the crop module, and mouse over or select any crop ratio, grid will not get displayed.
The crop guides are set to rules of third as was in the original where history was copied from.

There doesn't seem to be any way to get the grid back for cropping on the duplicate or the original.

Always reproducible in my setup.

This occurs on the windows and linux versions.

**Comment by matt-maguire** [comment]
Similar issue on recent master.

Looks to me that when you select the duplicate, the focus is in the duplicate manager, and even if you change the aspect or guides setting on the crop module, the focus is not returned to the crop module. If you click on the "crop and rotate" title, the module will collapse, and if you click again on the title, the module expands, but now the focus is in the crop module, and it behaves normally.

There's probably some subtle thing going on here that's not quite right, maybe one of the gui devs can comment.

**Comment by chhil** [comment]
Thanks Matt.

I have also managed to get the crop not to work on the original as a fresh image. Something weird because even after getting rid of the duplicate, resetting history of original, crop grids don't show when tried for the first time on the history reset image.

**Comment by johnny-bit** [comment]
I couldn't reproduce on 3.4.1, 3.6 and now on `3.7.0+1~g05bdc45ac` so I think it's mostly if not completely fixed :)
