### ISSUE TITLE
Apply style on export behaves differently than apply style on lighttable

### ISSUE THREAD

**Issue by chrisaga** [darktable-org/darktable#6722]
**Describe the bug**
When you apply a style in "add mode" onto a photo in the Light Table it behaves like an automation of what you could have done manually in the Dark Room. Fore instance if you already have a watermark applied and you add a style with a different watermark, the result is the new watermark only. The watermark module is not duplicated in the workflow. It's executed once and only once with the new parameters. *(Add style use case)*

When you apply the same style in the export module, the result is two watermarks applied: the original one plus the new one coming from the style. It looks like all the pipeline is executed as defined, and the style is executed after; almost as if you had duplicated the watermark module in the Dark Room (but probably with a different module order in the pipeline). *(Export use case)*

**To Reproduce**

1. Go to 'Dark Room'
2. Add a watermark on the bottom right of the frame
3. Go back to 'Light Table'
4. Define a style *WM1* with your watermark
5. Go to 'Dark Room' again
6. Move your watermark on the top left of the frame
7. Go back to 'Light Table'
8. In the export module add your 'WM1' style and export.
9. **Open the exported file and verify you can see two watermarks on it**
10. Apply the same *WM1* style permanently on you photo
11. Press `W` key for preview (or whatever shortcut you have set for preview)
12. **Verify that you can see only one watermark coming from the *WM1* style**

**Expected behavior**

I would expect that the *Export use case* would work like the *Add style use case* because: 
1. Order of the modules in the pipeline is important and not respected in the *Export use case*
2. With this behavior, we cannot temporarily modify what is in the development pipeline when exporting files, only add some treatments. 

**Screenshots**

Not needed

**Platform (please complete the following information):**
 - Darktable Version: [3.2.1]
 - OS: [ Ubuntu 20.04 with KDE 5 ]
 - OpenCL not activated
 - Graphics card : Cape Verde XT [Radeon HD 7770/8760 / R7 250X]

**Additional context**
I suspect it is not new but I hadn't investigated that much until now. I should explain why we cannot deactivate a module using a style at development time, which I had noticed at least since Darktable v3.

**Comment by hqhoang** [comment]
This is not a bug. I'm been using darktable for years, and got confused just like @chrisaga as I used to the previous behavior. 

However, the past behavior was a bug: in "replace history" mode, it basically deleted the whole history stack of the image, and applied only the style, which I can't think of any use case for.

The current behavior is correct, and explained clearly in the manual.

> **mode**
>     When applying a style during export this option defines whether the history stack items of that style replace the original history stack of the image or are appended to it. Technically speaking, in append mode history stack items of the style will constitute separate instances of the respective modules on top of any existing ones (see also multiple instances). As a consequence the original history stack will remain in effect with the new items being applied in addition. This way you can apply an overall adjustment (e.g. exposure) to a number of exported images while respecting the settings of each individual image.

@chrisaga: I think you just need to change the mode from "append history" to "replace history" to achieve what you want (and how it used to work). It won't replace the whole history stack like it used to, but instead replacing only items of matching modules.

**Comment by chrisaga** [comment]
@hqhoang thanks for your interest and your explanations.

You are right. the "replace history" mode does what I want. This behavior is completely different from the previous one which was, as you pointed it out, a complete replacement of the history stack. I never used it since this was not my use case.
I didn't get that the "replace history" mode changed and the documentation is not very explicit about it, so I didn't investigate it.

I guess I can close this issue now
