### ISSUE TITLE
[filmic rgb] slight UI update wish

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6727]
**Is your feature request related to a problem? Please describe.**

I like the new look of filmic rgb very much:

However, working on the sliders and then want to change a tab, I feel, my eyes missing a bit guidance. W/o the axis labeling, that area close to the tabs was a bit more "clean" and hence easier to catch. Again, I like the additional info, just think we could improve a little

_current look_
![Screenshot_20201102_181403](https://user-images.githubusercontent.com/49004103/97898877-c840dc00-1d38-11eb-99d5-cd6a893b8cb7.png)

**Describe the solution you'd like**

My unprofessional illustration of my idea is shown below
I know, it will effect the total module height with respect to the other tabs, which I did not cover here in that sample, just think, this might be bearable

_proposed updated look_
![Screenshot_20201102_181403_C](https://user-images.githubusercontent.com/49004103/97900251-b3fdde80-1d3a-11eb-8b81-0a7dd9785b12.png)

**Alternatives**

I am open to better ideas.

**Additional context**

@aurelienpierre this is your baby. What do you think? 
@dterrahe as you are sometimes UI-engineering as well, I would also appreciate your opinion

**Comment by Nilvus** [comment]
Hi,

I'm UI-engineering too, especially for all things that could be done with CSS. I agree that a little bit more space there would be good, but something between actual UI and your proposal. I will check that and see if this can easily be done with CSS. I'm quite sure this will be no problem for @aurelienpierre.

**Comment by Nilvus** [comment]
@AxelG-DE: quite simple to do. Could you add that in CSS editor in preferences window and save and apply:

`.dt_module_focus #iop-plugin-ui-main notebook
{
  margin-top: 0.5em;
}`

Let me know if this good for you. For me, it's indeed better than actual look without adding too much height on the module.
Just note that this will not be the final code as this line will break notebook in all modules. For example in color zones, this will add a not useful space. This is just for you to check if that space is ok for you. I tested 1em and it's just too much.

**Comment by AxelG-DE** [comment]
@Nilvus 

sorry if I overlooked you :-)

I really lack the competence, which part of the UI design should be done with CSS and which part comes from the origin of the code...

I tested your tweek, it works and I must say, here and for my personal taste, 1em is just to my liking. Maybe it is important to know, my screen I run dt on has the resolution 2560x1440

**Comment by matt-maguire** [comment]
just a general remark, you probably don't want to be running with the axes switched on day-to-day. Once you understand what the axes represent (x-axis is the scene dynamic range between the black and white point sliders, and y-axis is always the display output 0-100%), it is probably better to switch them off so you have more real-estate for the curve itself.

**Comment by Nilvus** [comment]
> @Nilvus
> 
> sorry if I overlooked you :-)

No problem ;-)

> I really lack the competence, which part of the UI design should be done with CSS and which part comes from the origin of the code...
> 
> I tested your tweek, it works and I must say, here and for my personal taste, 1em is just to my liking. Maybe it is important to know, my screen I run dt on has the resolution 2560x1440

1em for default UI is too much for me. em means emphasize and so related to font size, not resolution. If you want to keep 1em for you, just use my CSS code but with just an add to let that apply only on notebook following a widget like in filmic (widget is the graph) and avoid having that applied in other modules:

`.dt_module_focus #iop-plugin-ui-main widget + notebook { margin-top: 0.5em; }`

That will be my PR to fix that.

**Comment by Nilvus** [comment]
@AxelG-DE: sorry just a mistake on my line that would work only when filmic has the focus. To let that fix works all the time, here the good final line to use:

`#iop-plugin-ui-main notebook { margin-top: 0.5em; }`

**Comment by Nilvus** [comment]
@AxelG-DE: sorry just a mistake on my line that would work only when filmic has the focus. To let that fix works all the time, here the good final line to use:

`#iop-plugin-ui-main widget + notebook { margin-top: 0.5em; }`

**Comment by junkyardsparkle** [comment]
> em means emphasize

Well... ok, but just for historical perspective: 

https://en.wikipedia.org/wiki/Em_(typography)  :grin:

**Comment by AxelG-DE** [comment]
> "EV scene" label could be reasonably moved above the graph, since the tab space issue seems really only related to this bit of text?

If one moves EV Scene, next the axis labels would be (too) close to the tabs, with same effect.

**Comment by Nilvus** [comment]
> > em means emphasize
> 
> Well... ok, but just for historical perspective:
> 
> https://en.wikipedia.org/wiki/Em_(typography) grin
> 
> EDIT: Looking at the mock-up pictures, I wonder if the "EV scene" label could be reasonably moved above the graph, since the tab space issue seems really only related to this bit of text?

Thanks for the historical perspective. 

About "Ev scene" label, I agree with you and seen that by working on this issue. Unefortunately, it's inside a widget so can't be changed with CSS. It's in Gtk code, so not for me.

**Comment by AxelG-DE** [comment]
> it is probably better to switch them off so you have more real-estate for the curve itself.

I didn't reach that far to click on that boxed A :-D
Thanks for the hint.
