### ISSUE TITLE
DT 3.3.0-xxx import of 8/16 bit tiff crashes DT on startup

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6731]
Backtrace attached.
Current master.
[darktable_bt_A1D2T0.txt](https://github.com/darktable-org/darktable/files/5479972/darktable_bt_A1D2T0.txt)

Image file.
https://www.dropbox.com/s/2d1sgr18rmdp362/P1023262.tif?dl=0

**Comment by chhil** [comment]
```

libdarktable.dll!dt_view_manager_switch_by_view  [C:/msys64/home/chill/darktable/src/views/view.c @ 415]
   413: 
   414:       /* add module to its container */
>  415:       dt_ui_container_add_widget(darktable.gui->ui, plugin->container(plugin), w);
   416:     }
   417:   }
000000006367B2C1 0000000002F04BA0 0000000000000000 0000000000000000  libdarktable.dll!_dt_ctl_switch_mode_to  [C:/msys64/home/chill/darktable/src/control/control.c @ 346]
   344:   const char *mode = (const char*)user_data;
   345:   _dt_ctl_switch_mode_prepare();
>  346:   dt_view_manager_switch(darktable.view_manager, mode);
   347:   return FALSE;
   348: }
00007FF83583C006 000000007119A0C0 000000006367C0C8 000000000061E6E0  libglib-2.0-0.dll!g_main_context_invoke_full
00007FF83583C19A 00000000111DB5F0 000000000061E650 0000000000000000  libglib-2.0-0.dll!g_main_context_invoke
0000000013892257 0000000000000000 00007FF800000000 0000000000CC0020  libimport.dll!_lib_import_single_image_callback  [C:/msys64/home/chill/darktable/src/libs/import.c @ 636]
   634:       {
   635:         dt_control_set_mouse_over_id(id);
>  636:         dt_ctl_switch_mode_to("darkroom");
   637:       }
   638:     }

```

**Comment by TurboGit** [comment]
Just delete you **install** and build directory and build again.

**Comment by chhil** [comment]
@TurboGit Please reopen this issue.
Did a clean window (removed build directory content)  build crashed on import of tif file.
Build used darktable-3.3.0+1347~g9bba79445-win64

Backtrace
[darktable_bt_FKWJT0.txt](https://github.com/darktable-org/darktable/files/5480637/darktable_bt_FKWJT0.txt)

Works on ubuntu 20 build.

**Comment by chhil** [comment]
I generally build and install DT which overwrites the existing install.

So I backed up the install its failing on by renaming the dir and installing a brand new DT.

The brand new DT worked fine.
The older upgraded backed up one doesn't work, so I did a file compare and saw a whole bunch of files that are not present in the current install.
This is the bin folder which shows the additional files in the older upgraded install, timestamps varying from 2019 to OCt this year. 
![image](https://user-images.githubusercontent.com/1119439/97978821-254d9800-1df4-11eb-832e-5f600f0203ce.png)


Similarly under lib folder
![image](https://user-images.githubusercontent.com/1119439/97978995-6fcf1480-1df4-11eb-8d68-53cd693b06e7.png)


I am going to assume that there is some conflict with the dlls being picked up by DT causing it to crash.

**Comment by TurboGit** [comment]
> Did a clean window (removed build directory content) build crashed on import of tif file.

I wrote :: clean the **install** & **build** directory. You still had moduleist module in the install dir and this module has been removed recently.

**Comment by chhil** [comment]
Ok. My mistake. 

Will people who upgrade run into this  issue with the future planned release ?
