### ISSUE TITLE
Make customizable slider/controller containers to combine quick access to different modules

### ISSUE THREAD

**Issue by stakaz** [darktable-org/darktable#6732]
**Is your feature request related to a problem? Please describe.**

No, it is not related to a problem. 

**Describe the solution you'd like**

Hello, I just wonder if it would be a good idea to be able to put together controls from different modules into some kind of containers which that could be used as a quick-tools palette to adjust parameters of different modules.

Let me explain the idea:

I have read the documentation and have seen that using "Basic Adjustments" Module is not recommended with RGB workflow. As far as I can see it more or less gives settings control which are otherwise distributed across different modules.

How would it be if instead of being a separate module, "Basic Adjustments" would be a composition of sliders from different modules. There could be a turn on/off button and a link to the original module alongside the slider or whatever. But otherwise it would only adjust the slider in the modules they belong to and auto-enable these modules when adjusted.

In this way one could benefit from the simplicity of the module without loosing the "correct" pipe-order and without "repeating" the functionality.

While "Basic Adjustments" is my best example, I can imagine that being able to collect different sliders to one place would be useful for many different workflows.

A second example is "Color Balance" which has a plenty of sliders but what if I just want to set saturation?

If I understand it correct, the GUI is styled with CSS so probably it is flexible enough to do stuff like this?

**Alternatives**

There are of course other ideas which would bring us to a similar effect.

1. Add a favorite tab with sliders, not modules and presets/customization for it.
2. Allow to hide sliders in modules into a second tab (split into primary/secondary parameters on per user basis).

**Additional context**

**Comment by dterrahe** [comment]
This idea has been floated a few times in different forms and I think it is a good one. It just requires a lot of under the hood work to make this possible. There is progress towards enabling this kind of approach (and other improvements of the input system). But it is unlikely to happen in the short term.

CSS only affects the looks of widgets, not their positioning or functioning. Some of the most-used widgets in dt, sliders and comboboxes, cannot be styled with CSS at all yet.

**Comment by stakaz** [comment]
Thanks for the reply. 

Yes, I can imagine that it is not as easy as placing some elements on a web page. 
I can only imagine that it could be better to use such an approach in the future if a new composed module is about to be build. 

If there is another issue which addresses the same thing, you can link to it and close this one. But I have not found any on my first attempt.

**Comment by dterrahe** [comment]
This is part of #5063. Not so obvious :-)

**Comment by AlicVB** [comment]
If I've understand correctly, this is exactly what I propose in PR #3648 
It's fully functional (well, I just need to rebase), but I just wait for some other devs work in order to avoid to many change for the users in the near future. feature freeze for 3.4 is almost here, so I think it will be for the next release...

**Comment by stakaz** [comment]
Yes, exactly. Sorry for not being able to find it myself.  I will close this one now.
