### ISSUE TITLE
CTRL+W  (preview with focus detection) seems to be offset top left for windows build

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6737]
When I do a ctrl+w in lighttable the red focus boxes appear top left. Which clearly is not the focus area. I wonder if the placement of these boxes has got affected with some of the dpi changes or image display resolution changes.

![image](https://user-images.githubusercontent.com/1119439/97994975-f2170300-1e0b-11eb-9edc-d19d668f715e.png)

On todays master build for windows.

Same image ctrl+w
On windows 
![image](https://user-images.githubusercontent.com/1119439/97996301-964d7980-1e0d-11eb-9dde-c92daddd8321.png)

On linux
![image](https://user-images.githubusercontent.com/1119439/97996383-ae24fd80-1e0d-11eb-984a-be625ba3793d.png)

**Comment by TurboGit** [comment]
Oh yes, most probably another ppd issue/ Good catch before the release...

**Comment by jenshannoschwalm** [comment]
I am back home and can take care of it ...

**Comment by jenshannoschwalm** [comment]
Just to make sure; this is **only** valid for windows builds? Also let me know whether this is valid only in "prefer performance ..." mode? On Hires screen?

**Comment by TurboGit** [comment]
No, I can reproduce on windows and this is only visible when downsampling is set to something else than original.

**Comment by chhil** [comment]
My linux build runs on wsl for windows. The focus appears to be correct on it.

My windows build seems to have the shift problem.

"prefer performance mode over quality" is checked for both windows and linux.

I don't have a hires screen.

**Comment by chhil** [comment]
I made the change locally and built a dirty version of DT. Did not fix the issue.

``

$ git diff
diff --git a/src/common/focus.h b/src/common/focus.h
index 3f6772e7d..52fc654cc 100644
--- a/src/common/focus.h
+++ b/src/common/focus.h
@@ -294,8 +294,8 @@ static void dt_focus_draw_clusters(cairo_t *cr, int width, int height, int imgid
     if(ht * scale <= height) fy = 0;
   }

-  cairo_translate(cr, -wd / 2.0f + fx / scale, -ht / 2.0f + fy / scale);
-
+
+cairo_translate(cr, -wd / 2.0f + fx / scale * darktable.gui->ppd_thb, -ht / 2.0f + fy / scale * darktable.gui->ppd_thb);
   cairo_rectangle(cr, 0, 0, wd, ht);
   cairo_clip(cr);

```

**Comment by chhil** [comment]
Closed #6741
