### ISSUE TITLE
Windows - Intel display driver update 27.20.100.8682 causes crash at startup

### ISSUE THREAD

**Issue by WimvK** [darktable-org/darktable#6740]
**Describe the bug**

Since today 11-03-2020 Darktable 3.2.1 on Windows crashed on startup (see crash report file). Starting Darktable with option --disable-opencl it opens normally (see also bug #6585) but in a basic layout without themes. 
**To Reproduce**

The bug occurred after Windows Update installed Intel display driver version 27.20.100.8682. After reversing the driver update to version 27.20.100.7989 by choosing a Windows restore point (not the fastest way to do this ;)) Darktable behaved normally. I used the [Windows Update troubleshooter](https://support.microsoft.com/en-us/help/3073930/how-to-temporarily-prevent-a-driver-update-from-reinstalling-in-window) to block further driver updates.

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10 version 1909
 - opencl not available on Intel graphics
 - Intel(R) HD Graphics 530 (i5 6500) 27.20.100.8682
[darktable_bt_R4RJT0.txt](https://github.com/darktable-org/darktable/files/5482385/darktable_bt_R4RJT0.txt)

**Additional context**

**Comment by parafin** [comment]
So you already debugged that it's a video driver issue, what do you want darktable project to do? The only thing I see to do here is to blacklist this driver (not even try to use OpenCL), but it's impossible to maintain a list of specific versions that fail and disabling it altogether for Intel isn't desired by most (was reversed some time ago). I suggest you close this bug report.

**Comment by WimvK** [comment]
Dear parafin,

My primary reason for reporting this bug is that other users on Windows may also run into it, and I also suggested a (temporary) solution they may use. In fact I opened a Github account to post it. I am not a programmer, but I hope to contribute a tiny bit to making a great application even better.

As for the use of OpenCL on Intel (HD Graphics 530), on my Windows machine this is not available for processing the image (greyed out in preferences), so I was a bit surprised that it seemed to be the cause of the crashes. Is it used to render the GUI, because starting Darktable with --disable-opencl sort of breaks the GUI, while on an earlier build (3.1.0+2292~g9b6e6c70f) it didn't? I guess this is a Windows build specific issue, and may not be relevant to the core development of Darktable. On your suggestion I closed the bug report.

By the way, a big thank you to you and all the other developers contributing to such a great app!

**Comment by parafin** [comment]
--disable-opencl shouldn't affect how GUI works, so probably that version of Intel video driver is broken in more ways than one. The crash happens during enumeration of OpenCL devices, so even if it's not suitable for darktable, it can still cause the crash. Come to think about it it also means that we can't blacklist it. The difference in behaviour between darktable versions is more peculiar, probably it is cause by update of one of the dependencies (e.g. GTK). The point being we can't do anything about this... As for keeping a record of which versions of Intel drivers don't and do work, maybe it's better be kept in some pixl.us darktable forum thread and keep github bug tracker for issues that darktable developers can actually fix...

**Comment by parafin** [comment]
If you have a screenshot of GUI looking wrong with --disable-opencl - upload it here, maybe someone will have an idea what is happening.

**Comment by WimvK** [comment]
![Schermopname (15)](https://user-images.githubusercontent.com/73897242/98027373-de1fd100-1e0c-11eb-852a-cb8beb0aac47.jpg)

**Comment by WimvK** [comment]
The broken GUI was caused by starting the app from a batch file on a different (Data) volume as a standard user. From the console or with administrator rights it starts up properly.
