### ISSUE TITLE
Windows 10 unhandled exception: darktable.exe caused an Integer division by zero at location 00007FFA4EFBFB99 in module igdrcl64.dll

### ISSUE THREAD

**Issue by greybeard-jsy** [darktable-org/darktable#6749]
**Describe the bug**
Today when I tried to start darktable I got an error saying that there was an unhandled exception. The backtrace file is attached below.
[darktable_bt_ZAUIT0.txt](https://github.com/darktable-org/darktable/files/5490602/darktable_bt_ZAUIT0.txt)

I posted the issue on the unofficial darktable Facebook group and got some feedback that it may be due to an OpenCL issue.

I have noticed that there is a new folder in the directory C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_2cec8fd58a80e6ea which contains the file igdrcl64.dll version 27.20.100.8682 (the same file is referenced in the backtrace file). The date on the folder is 03/11/2020 (yesterday).

It may be relevant that I did a Windows 10 update yesterday. 

**To Reproduce**
Darktable consistently fails if started from Windows GUI or the command prompt. The only way to start darktable is using the command line: darktable --disable-opencl.

**Expected behavior**
I expected darktable to start as usual (it worked fine yesterday).

**Screenshots**
 Screenshot from starting darktable with OpenCL test binary (command line:> darktable-cltest)
![20201104-Opencl_test](https://user-images.githubusercontent.com/73966400/98168968-5062e500-1ee3-11eb-9649-9a7cd120a526.JPG)

Backtrace file from this test:
[darktable_bt_I2UUT0.txt](https://github.com/darktable-org/darktable/files/5490598/darktable_bt_I2UUT0.txt)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10 64 bit
 - OpenCL IS activated
 - NVIDIA GeForce 1070 with Max Q design - 8GB dedicated memory
 - processor = Intel Core i7-7700HQ cpu @ 2.80 GHz with 32GB RAM

**Additional context**

 - I have tried the following, but still darktable crashes on start up (I never see the GUI open)
1. uninstall darktable and re-install - same result
2. delete all files from darktable configuration folder - same result.
3. uninstall Windows update that was done on 3 November - same result (though as noted above, there is a new driverstore folder dated 3 November 2020 containing a new version of  igdrcl64.dll - this has remained after the Windows update was removed).
4. Before today, darktable has run consistently well.

**Comment by parafin** [comment]
duplicate and not a darktable bug (video driver issue).
