### ISSUE TITLE
0 Ratings are not imported from xmp files

### ISSUE THREAD

**Issue by konig12** [darktable-org/darktable#6752]
**Describe the bug**
When importing images into darktable, either individually or with the Import -> Folder option, 0 ratings in the xmp sidecar files are ignored. The default rating of 1 is assigned in all cases.

**To Reproduce**
Tested on a build from master as of 11/4 with an empty preferences directory:
- Import a directory of images
- Rate the images with a combination of 0 and 2 stars
- Write sidecar files for the images
- Remove all images from the collection
- Import the directory again
Note that the 0 rating images now have a rating of 1

**Expected behavior**
The imported images should have the same ratings that were given at the time the xmp files were written

**Platform (please complete the following information):**
 - Darktable Version: 2.7.0 from master.
 - compiled with default options in GCC

**Additional context**
- I can reproduce this starting in 3.2.1

**Comment by phweyland** [comment]
Are other ratings correctly taken in account?
Can you share one of the xmp file?
Thanks

**Comment by konig12** [comment]
Yes, other ratings (including reject/-1) are taken into account. I am not sure how to attach, so I will paste the xmp content here. The image for this XMP imports with a rating of 1 (the default).

XMP content:
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:darktable="http://darktable.sf.net/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
   exif:DateTimeOriginal="2017:12:02 12:14:07"
   xmp:Rating="0"
   xmpMM:DerivedFrom="IMG_8477_01.jpg"
   darktable:import_timestamp="1604723246"
   darktable:change_timestamp="-1"
   darktable:export_timestamp="-1"
   darktable:print_timestamp="-1"
   darktable:xmp_version="4"
   darktable:raw_params="0"
   darktable:auto_presets_applied="0"
   darktable:history_end="0"
   darktable:iop_order_version="1">
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq/>
   </darktable:history>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>AC</rdf:li>
    </rdf:Seq>
   </dc:creator>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>

**Comment by phweyland** [comment]
I've looked at the code and that's how it works I'm afraid.
0 is considered as default and replaced by default value from preferences.

I think the logic is wrong. The default value should be applied when there is no rating in xmp.
@TurboGit, any thougth ?

As a work around you can set the "initial default rating" in preferences to 0.

**Comment by konig12** [comment]
Yes, I discovered that workaround as well. This still causes issues for me as I have folders with many 0 rating and a few "empty rating" (new) files.

I am also pretty sure this is a regression. I did not see this behavior before upgrading to 2.2.
