### ISSUE TITLE
[DT 3.3.0-XXX] Tag cannot be cleared from the textbox that was used to enter using the "x" button.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6753]
To reproduce : 
There are no existing tags in the system (except the ones DT creates internally).
Adding a new tag.
Enter text in text box under the attached button.
Hit enter.
Tag gets created.
The created tag is still present in the user entry text box.
Now try and hit the "x" to remove the tag that was typed for creation. It does not get cleared. However you can backspace and clear it.

![image](https://user-images.githubusercontent.com/1119439/98065041-ab5ff200-1e79-11eb-8bfd-0fbb54998d64.png)

**Comment by phweyland** [comment]
I'll look at this.

**Comment by phweyland** [comment]
> The created tag is still present in the user entry text box.

I cannot reproduce this.

**Comment by darkelectron** [comment]
I was able to reproduce, I'm on version: 3.3.0+1383~g2c80626a7

Another weird one(seems to happen right after the above mentioned), with no existing styles:

1. enter tag name in text entry (e.g "street")
2. click on new button or hit ENTER key
3. click 'x' to clear entry - text is not cleared
4. clear text by hitting backspace
5. enter partial characters from previous entered tag(e.g "st") then something else("abc")
6.  click on new button or hit ENTER key, the "st" will persist.

Repeat from step 3 for other only changing in step 5.

![2020-11-08-03-44-21](https://user-images.githubusercontent.com/51426724/98455153-b90cc480-2164-11eb-881f-48f3592ee6b7.png)

Creating tag with different name clears the text entry.
