### ISSUE TITLE
Selecting Images to tag while folder of images is being imported does not work

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6754]
Importing 1100+ images with existing xmps.
This process takes time and while import is happening, I try to select images that have been imported to start tagging. 
Click an image for selection, move the mouse to double click a tag for attachment, but as soon as I move the mouse the image gets deselected. The click on an image or ctrl+click to select multiple images does not work at during import.

After import is complete, I get back control to select images.
Current DT master build on windows.

**Comment by Nilvus** [comment]
@chhil: this had been fixed (or at least hugely improved) in actual master. I so close this one. Feel free to reopen after testing again on actual master if needed with new infos.
