### ISSUE TITLE
Replace osm-gps-map Gtk widget

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6763]
Issues #6196 and #5172 depend on osm-gps-map Gtk widget, which isn't mantained any more.

Looking for another widget for composing the map?

**Comment by johnny-bit** [comment]
Unfortunately for that we have to have a replacement widget that's present in distros packaging systems. osm-gps-map widget is... What's the viable alternative?

**Comment by paolobenve** [comment]
https://wiki.openstreetmap.org/wiki/Libchamplain ?

**Comment by Nilvus** [comment]
This library doesn't seems a lot more active than osm-gps-map. Just some minor update 2 times this summer and nothing more.

**Comment by johnny-bit** [comment]
Well... Not really - libchamplain depends on already unmaintained cogl (which is the basis for it's functioning). This dependence causes it to be not rewriteable. It's successor, libshumate, depends on gtk4, which is not yet avail... so both are not viable alternatives ;(

**Comment by Nilvus** [comment]
Just see that the maintainer of osm-gps-map search a new maintainer. So if you know someone who could and want to maintain osm-gps-map, it will be good for darktable too. See here: https://github.com/nzjrs/osm-gps-map/issues/71#issuecomment-691966608

**Comment by johnny-bit** [comment]
osm-gps-map widget just got a new release - 1.2.0.

New maintainer and more contributors are still needed but for now the situation isn't as dire as it was couple months ago.

**Comment by johnny-bit** [comment]
Since I'm pretty much maintaining osm-gps-map and replacement widgets are either EOLd or not-ready-yet I'm closing tis issue. We can re-open this discussion once libshumate is prod-ready.
