### ISSUE TITLE
Release tarball missing Swedish language.

### ISSUE THREAD

**Issue by et-8** [darktable-org/darktable#6764]
**Describe the bug**
Release tarballs should include Swedish language (sv) since version 2.4.0

**To Reproduce**
A Gentoo linux install with USE flag "nls" and L10N set to "sv".
emerge darktable

**Expected behavior**
GUI in Swedish.
Release notes says that Darktable support Swedish language since version 2.4.0 .

**Platform (please complete the following information):**
 - Darktable Version:  3.0.2 (The Stable version on Gentoo.)
 - OS: Gentoo Linux

**Additional context**
Gentoo will add support for Swedish, as well as other languagues that both are
currently and might in the future be present in the Darktable Git repository,
once upstream has deemed them mature enough to be included in release tarballs.

I will make a PR with updates to the Swedish .po file.

**Comment by TurboGit** [comment]
Only almost fully complete translation are included otherwise the translation is removed from the release. We do not want an half translated interface, this will be a very bad user experience.

> I will make a PR with updates to the Swedish .po file.

Great ! Looking forward to it.
