### ISSUE TITLE
commit made all images black

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#6766]
Commit cfa1abfdb09207a2f87d9e753390797195b2ff29 made all images black in both darkroom and lighttable. The output is 

[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 ,
it will be replaced with linear rec2020
[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 ,
it will be replaced with linear rec2020
[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 ,
it will be replaced with linear rec2020
[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 ,
it will be replaced with linear rec2020
[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 ,
it will be replaced with linear rec2020
[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 ,
it will be replaced with linear rec2020 

Images use self-made profile for Sony A99. There were no problems with the profile before.

The system is Linux Mint 20 Mate x64.

With respect,
Alexander Rabtchevich

**Comment by ptilopteri** [comment]
it is not peculiar to Sony A99.  I have same on g53603424b for Nikon nef's
built on openSUSE Tumbleweed

**Comment by jimOnAir** [comment]
I have the same problem with Sony A850, Sony A6000 raw files with standard profiles.

**Comment by aurelienpierre** [comment]
Error found, fix incoming
