### ISSUE TITLE
Lua 5.4 not accepted in CMakeLists.txt

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#6768]
**Describe the bug**
Latest Fedora 33 has Lua 5.4 but not 5.3 so building master does not allow to use external Lua.

**Expected behavior**
Don't know whether there is some problem to use the fix lua version

@phweyland you probably know how to handle this

**Comment by TurboGit** [comment]
@wpferguson : may know better about Lua and if 5.4 is expected to work in current dt.

**Comment by wpferguson** [comment]
Unfortunately Fedora 33 is the only distribution AFAIK that is using lua 5.4.  Everyone else is on 5.3.  I've built darktable with 5.4 internally, but I haven't done enough testing to be confident with it.

There are a couple possible workarounds.  
  1. Use the internal lua (set option(DONT_USE_INTERNAL_LUA "Never fall back to the intree copy of lua" OFF) in DefineOptions.cmake)
  2. Get the 5.3 lua rpms from Fedora 32 and use those.

Moving to 5.4 is a work in progress.  See #5906.

**Comment by jenshannoschwalm** [comment]
Aah, i read that issue but forgot it :-( Closing this but #5906 should be marked as something that maybe has to be fixed for release.
