### ISSUE TITLE
SVG Sgunature instable

### ISSUE THREAD

**Issue by nk8020** [darktable-org/darktable#6771]
Description: 
                   I've SVG signature (produced in Inkscape, and cropped snugly)
                   I've 4 preset locations - R/L Landscape & R/L Portrait

                   I export photos using a fix size (maximum = minimum = 2500 pixels) 

Problem:    Signatures are mangled/ smeared/ partial in exported file. It takes from 2 to 8 tries to get the photo with the original
                  & complete signature

To reproduce the problem:
                 Signature was placed R/L bottom corner with margin (Again - using presets for Right & Left positioning)
Upon exporting - It might come OK, but might get mangled. Habitually - it gets this way for Portrait photos and not Landscape.

My platform:
                  OS: Win 10 x64
                  Darktable ver. 3.2.1
                  The SVG was produced using Abbyline font
                  OpenCL activated
                  Graphics card: GTX970

Additional info: This bug was discovered when processing JPG to JPG, but appears also when processing RAW and exporting at 
                          the end to JPG.

**Comment by Nilvus** [comment]
@nk8020: could you test again with darktable 3.6.0.1 released few days ago? Since 3.2.1 a lot of bug had been fixed. Maybe yours is fixed. Please report here if 3.6.0.1 fixed your issue or not. If your issue is fixed, think about closing this issue. Thanks.
