### ISSUE TITLE
Ninja build system can not generate version_gen.c file

### ISSUE THREAD

**Issue by Biswa96** [darktable-org/darktable#6778]
* Platform: Windows 10 Pro
* Build Environment: MSYS2/MINGW64
* Compiler: GCC 10.2.0 x86_64-w64-mingw32
* Things I did:
  - **Shallow** clone this repository with `--depth=1`. 
  - Generate Ninja file with the following CMake command and build it:

```sh
cd darktable; mkdir bin; cd bin
MSYS2_ARG_CONV_EXCL="-DCMAKE_INSTALL_PREFIX=" \
${MINGW_PREFIX}/bin/cmake \
    -G "Ninja" \
    -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
    -DBINARY_PACKAGE_BUILD=ON \
    -DBUILD_MSYS2_INSTALL=ON \
    -DUSE_AVIF=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    ../
cmake --build ./
```
* Error output: 

```sh
[121/691] Building C object bin/CMakeFiles/lib_darktable.dir/version_gen.c.obj
FAILED: bin/CMakeFiles/lib_darktable.dir/version_gen.c.obj
C:\msys64\mingw64\bin\cc.exe ...something... bin/CMakeFiles/lib_darktable.dir/version_gen.c.obj -MF bin\CMakeFiles\lib_darktable.dir\version_gen.c.obj.d -o bin/CMakeFiles/lib_darktable.dir/version_gen.c.obj -c bin/version_gen.c
cc.exe: error: bin/version_gen.c: No such file or directory
cc.exe: fatal error: no input files
compilation terminated.
[123/691] Generating authors.h for about dialog.
ninja: build stopped: subcommand failed.
```

I would happy to provide any further information, if required.

**Comment by parafin** [comment]
Please provide full output of all commands starting with git clone.

**Comment by kmilos** [comment]
Just a data point: master builds just fine for me on mingw64, but I don't do a shallow clone, and I use 'MSYS Makefiles' generator.

Btw, you can remove `-DUSE_AVIF=OFF` now, there is the needed libavif 0.8.2 in the ming64 pacman repo...

**Comment by Biswa96** [comment]
Thanks @kmilos. The issue is in Ninja program. Perl scripts fails when CMake is using with Ninja generator. 'MSYS Makefiles' works file. So, the issue is not related to darktable. Closing...

**Comment by dterrahe** [comment]
It would still be good to have the code work under both generators. vscode defaults to ninja and without this problem would potentially provide many additional users who could more easily help debugging under windows.

**Comment by parafin** [comment]
Let's reopen this.

Does ninja build work on Linux?

**Comment by dterrahe** [comment]
> Does ninja build work on Linux?

Yes, it does; I'm using vscode under Debian as well.

**Comment by parafin** [comment]
Well, then the info I requested (from Windows) is a good start for debugging this.

**Comment by johnny-bit** [comment]
Ninja works on linux, I however had multiple problems using it on windows when building CI pipes, because files generated by ninja insisted on trying to use wrong shell to execute external dependencies (like intltool-merge) (see https://github.com/msys2/setup-msys2/issues/84)

Our build instructions for windows mention that supported generator is MSYS Makefiles:
https://github.com/darktable-org/darktable/blob/24aed82ccff99d66b5c637f13512f2b542376344/packaging/windows/BUILD.txt#L96

This is (IMO) Ninja/cmake problem, not darktable.

**Comment by dterrahe** [comment]
@johnny-bit you are not wrong. So consider this (and all the previous attempts) a feature request.

I think I tried to get to get the debugger in vscode to work with MSYS Makefiles in the past, but it was a hassle and can't remember the outcome. Definitely the build/debug cycle was easier when using ninja, when I _did_ get that to work, but that got broken again, so... I haven't done any serious work in Windows after that.

Even if nobody has any intend to address this issue, leaving the bug open means the next user running into the problem will get less frustrated by it. Alternatively, a small note in the build instructions that ninja def will not work/we are aware of unsolved issues could serve same purpose.

**Comment by parafin** [comment]
Maybe there is some cmake magic or command line parameters that could help, even if it's not a dt issue... Let's leave this open.

**Comment by Biswa96** [comment]
I have set up a temporary GitHub Actions to build darktable in MSYS2/MINGW64 with CMake and Ninja. See the GitHub Actions output for verbose details. Link https://github.com/Biswa96/darktable-ninja-test

**Comment by parafin** [comment]
cmd.exe is hardcoded in ninja cmake generator. How does one start msys executables from cmd.exe?

**Comment by lazka** [comment]
>  How does one start msys executables from cmd.exe?

These are just normal text files with a shebang from what I understand, nothing msys specific. One thing worth trying would be to call perl with the script instead of the script (I see your cmake file already looks for perl).

**Comment by parafin** [comment]
Ah, right, this is a script, that's why it fails. The problem is that intltool-merge is an external tool, so it would be wrong to hard-code calling perl in dt cmake code.

It would help if there was some wrapper on Windows that could handle both scripts with shebangs and binary executables... I'm guessing calling something like `bash -c ""` could do it, hoping that correct bash gets executed (but we already do so, see #6487). But it's ugly to do it for all platforms, probably some cmake hack can be created to prepend it to commands when ninja on Windows is used... Dunno...

**Comment by lazka** [comment]
> The problem is that intltool-merge is an external tool, so it would be wrong to hard-code calling perl in dt cmake code.

It's more or less unmaintained for years and imo deprecated in favor of gettext, so I doubt anything changes there.

**Comment by parafin** [comment]
It's not a universal solution to the ninja problem anyway, there might be other issues like this.

**Comment by johnny-bit** [comment]
Well... `intltool-merge` is used only in creating 2 files - `darktable.desktop` (which on windows is most likely not needed) and `darktable.appdata.xml` which is application metadata info if i'm not mistaken... both could be ommited on windows. Also migration to gettext looks like something "doable" (i can find something like https://wiki.gnome.org/MigratingFromIntltoolToGettext dunno if it's applicable here)

I don't think we want to depend on unmaintained libs if we can avoid it, but at the same time @parafin is right that it's not an universal solution... We need a clear way for ninja do do good thing by default.

**Comment by dterrahe** [comment]
> It's more or less unmaintained for years and imo deprecated in favor of gettext, so I doubt anything changes there.

moving to xgettext also would have the advantage that we could define an NQ_ equivalent to NC_. This would allow the use of "context|message" style context specifiers, which makes it easier to pass an occasional context specific translation down a line of function calls without having to add the context parameter explicitly everywhere (and using NULL 99.6% of the time). I used this once in 5adb238df3690eb737b3eeed14815aca28413434 but had to resort to a bit of a trick to mark it correctly for translation.

**Comment by lazka** [comment]
I've tried patching things in MSYS2 to make it work with ninja, just to see if that is the only issue, and ended up with: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-darktable/ninja-build-fixes.patch

**Comment by Biswa96** [comment]
Thanks for solving this issue ❤️

**Comment by johnny-bit** [comment]
@Biswa96 - @lazka solved it, I just copied it and adjusted a bit :)

**Comment by johnny-bit** [comment]
And now more universal solution landed (that's better that `{perl_BIN}`) so this is totally done :)
