### ISSUE TITLE
Integration test 0035-multiple-modules fails due to version-dependent output

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#6784]
0035-multiple-modules/multiple-modules.xmp includes a watermark containing the darktable version string.  This causes the integration test to fail unless run with a build of the exact version used to produce expected.png.

Test 0035-multiple-modules
      Image mire1.cr2
      Max  dE         94.0427
      Mean dE         0.0981
      Count above max 12374

Suggested fix: change the stamp used by watermark to one of the other predefined stamps.

**Comment by TurboGit** [comment]
This should be fixed now. The watermark & lens have been removed from this test.

**Comment by johnny-bit** [comment]
Thanks!
