### ISSUE TITLE
Noise profile for the Canon EOS 2000D (AKA Rebel T7)

### ISSUE THREAD

**Issue by BCMM** [darktable-org/darktable#6787]
This is the first time I've tried to build a noise profile, so I hope this is submitted correctly.
I've tested this on a very noisy photo and it definitely produces better results than the generic Poissonian profile.

[darktable-noiseprofile-20201107.tar.gz](https://github.com/darktable-org/darktable/files/5506215/darktable-noiseprofile-20201107.tar.gz)

**Comment by rawfiner** [comment]
Thanks!
