### ISSUE TITLE
Duplicate preview is ill-zoomed

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#6790]
In darkroom, if you have several editing duplicates, you can hold your click on one of them thumbnails, and the preview of the duplicate will overlay the current edit.

Currently, the size of the duplicate doesn't match the size of the current preview, it seems there is a wrong zoom factor and the duplicate is magnified compared to the original.

I'm on High DPI screen, at 4K and pixel factor of 2 (1 px GUI -> 2 px device).

**Comment by elstoc** [comment]
Apart from the previously-discussed pixel shifting/squashing it looks ok on my 1080p monitor

**Comment by jenshannoschwalm** [comment]
Probably one more ppd_thb related problem, will take care of it
