### ISSUE TITLE
Pick an English language

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6791]
darktable currently uses an adhoc mix of British and American English. For example color rather than colour, but favourites rather than favorites. The spelling of grey/gray is inconsistent.

Please can we choose one and perhaps state it explicitly somewhere.

| American | British | Usage |
| :--- | :--- | :--- |
| color | colour | One use of "colour" in channelmixerrgb |
| favorites | favourites | British spelling used in older versions - seems to be American spelling now |
| gray | grey | Inconsistently used - British spelling seems more common |

**Comment by aurelienpierre** [comment]
Could you make up a tab of EN_UK vs. EN_US words ? I myself speak EN_Netflix and have no idea what word belongs to what dialect.

**Comment by elstoc** [comment]
Well I've listed a few of the known ones above but it's probably a case of spotting them when I spot them. For now I'd like to start of by just deciding which one we favor/favour. I'm assuming since "color" (American spelling) is used everywhere it's probably less work to choose American English (much as it pains me).

**Comment by TurboGit** [comment]
I would vote for en_US by default and have an English translation.

**Comment by johnny-bit** [comment]
Side-note: people in Europe (so probably majority of darktable devs) learn English with British spelling, so that's most likely why many words are spelled using British way. "Color" on the other hand is caused by multitude of libraries and loads of colour science is done in US, so loads of "incorrect" spelling :)

**Comment by junkyardsparkle** [comment]
> Could you make up a tab of EN_UK vs. EN_US words ?

As a native West Coast U.S. english speaker, the variatant that seems most "exotic" to me is the use of "s" rather than "z" for words like "colorize". The "our" vs. "or" is similar, but maybe slightly easier to ignore, at least for my brain. I think those are the primary distinctions. Things like "grey" vs. "gray", on the other hand, feel to me like they have less "national flavor" (are there many other words following this substitution?). All purely subjective. :-)

**Comment by dterrahe** [comment]
> I would vote for en_US by default and have an English translation.

Time for another github poll?

**Comment by Nilvus** [comment]
Having a consistent english would indeed be good. When we will be agree for which english to use, I think we will need to create a Wiki page in this Github with the list to words to use (list that could grown and, to ease reading, with categories). That page would be the page to check if needed to be sure we use a good english and of course with the regard of native english speakers like you @elstoc.

**Comment by elstoc** [comment]
I've started a list in the OP. Grey/gray is the most inconsistent of the ones I've looked for so far.

**Comment by dterrahe** [comment]
Once a language is decided on, would we expect problems with a bunch of search and replaces from the root directory? (Including the po files to limit the need for translations)

**Comment by TurboGit** [comment]
No it should be possible to automatically change the po files to avoid any translation invalidation.

**Comment by TurboGit** [comment]
So you love polls :

<p><a href="https://api.gh-polls.com/poll/01EPPGJ3ZHGK4ZQVR5RX382S06/dt%20should%20use%20American%20English/vote"><img src="https://api.gh-polls.com/poll/01EPPGJ3ZHGK4ZQVR5RX382S06/dt%20should%20use%20American%20English" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EPPGJ3ZHGK4ZQVR5RX382S06/dt%20should%20use%20British%20English/vote"><img src="https://api.gh-polls.com/poll/01EPPGJ3ZHGK4ZQVR5RX382S06/dt%20should%20use%20British%20English" alt=""></a>
<a href="https://api.gh-polls.com/poll/01EPPGJ3ZHGK4ZQVR5RX382S06/I%20don&#39;t%20really%20care/vote"><img src="https://api.gh-polls.com/poll/01EPPGJ3ZHGK4ZQVR5RX382S06/I%20don&#39;t%20really%20care" alt=""></a></p>

**Comment by junkyardsparkle** [comment]
> I've started a list in the OP. Grey/gray is the most inconsistent of the ones I've looked for so far.

I grepped numerous instances of "initialise" and "normalise", but they appear to be in comments rather than GUI strings, which I'm assuming is outside the scope of this issue...

**Comment by johnny-bit** [comment]
I think that after merging of #8554, #9202, #9216 and others it seems to me that american english is clear winner despite poll in https://github.com/darktable-org/darktable/issues/6791#issuecomment-723990454 being perfectly balanced as all things should be.

I added mention of american english spelling in https://github.com/darktable-org/darktable/wiki/Developer's-guide#coding-style and so it seems that this issue can be closed...

@elstoc - what's your view here?

**Comment by elstoc** [comment]
Yeah let's close it
