### ISSUE TITLE
Many text strings no longer translated in color calibration module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#6807]
**Describe the bug**
Many text I translated yesterday are no longer there in last commit of darktable master. I don't understand why as I don't see any changes in channelmixerrgb.c file that could explain that. It could be 49bc358db87406992c77bcfdfa5dfa5600efa5c3 but seems that it was already merge before my PR (but maybe my rebase was before ; it worked on my side when posting my PR).

@TurboGit or @aurelienpierre: you should have ideas about why and how to solve that.

**To Reproduce**
Just check color calibration module in french and see that many text are no more translated, like gamut compression, normalize channels, clip negative RGB values and many more.
When code source files will be fixed, you could pick my translation work from that PR: https://github.com/darktable-org/darktable/pull/6786/files

**Comment by TurboGit** [comment]
Maybe due to the introspection. I'll have a look.

**Comment by TurboGit** [comment]
Fixed, indeed due to introspection the generated introspection file was not added into the list of files to take into account for translation. Fix was easy!

**Comment by Nilvus** [comment]
Oh, ok. Indeed so simple... Thanks
