### ISSUE TITLE
New 'neutral' exposure instance above input colour profile causes extreme overexposure

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6810]
**Describe the bug**
A newly created, neutral instance of the 'exposure' module, when Ctrl+dragged above 'input colour profile', causes gross overexposure (sometimes turning the image completely white).
Resetting the module resolves the overexposure.
Setting any exposure value, then returning to 0 change also fixes it.
As to _why_ someone would place an instance of 'exposure' above 'input colour profile', see https://discuss.pixls.us/t/camera-spectral-sensitivity-data-camspec/20354/4

**To Reproduce**
An example is at https://tech.kovacs-telekes.org/files/2020-11-09-exposure-issue/
1. Open a raw image; I used the scene-based workflow ![](https://tech.kovacs-telekes.org/files/2020-11-09-exposure-issue/Screenshot_20201109_131137.png)
2. Click on the multi-instance menu of 'exposure' and create a new instance ![](https://tech.kovacs-telekes.org/files/2020-11-09-exposure-issue/Screenshot_20201109_131217.png)
3. Ctrl+drag it above 'input colour profile'; the image turns very bright/white ![](https://tech.kovacs-telekes.org/files/2020-11-09-exposure-issue/Screenshot_20201109_131238.png)
4. Make a small adjustment to the exposure in the new module; the image turns back to normal ![](https://tech.kovacs-telekes.org/files/2020-11-09-exposure-issue/Screenshot_20201109_131344.png)
5. Reset the module; the image is normal ![](https://tech.kovacs-telekes.org/files/2020-11-09-exposure-issue/Screenshot_20201109_131350.png)

**Expected behavior**
Exposure module in neutral setting should not affect the image

**Screenshots**
See above

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1441~g010eec647
 - OS: Kubuntu 20.10
 - OpenCL: reproduced with and without

**Additional context**
I have not bisected this, but as I updated daily and did not have the issue yesterday, my guess would be that it has to do with the new channelmixerrgb changes -> @aurelienpierre

**Comment by aurelienpierre** [comment]
Reproduced. It's nothing to do with channelmixer, most likely problems of color profiles initialization.

**Comment by kofa73** [comment]
That was quick, thanks! :-)
