### ISSUE TITLE
Strange black border lines on top of some thumbnails in lighttable

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6815]
I'm almost sure this bug was reported before, but I couldn't find it anywhere...

Anyway, some thumbnails in Zoomable mode have strange arrow-like borders on top.

They appear and disappear only on certain zoom levels and when not many images are shown in the film strip.

![Untitled](https://user-images.githubusercontent.com/2467520/98571429-d18bf480-22b4-11eb-8ba4-42772cb12bcd.jpg)

Latest master ver.

**Comment by TurboGit** [comment]
Reported and now fixed, please be sure to update your version.

**Comment by maboleth** [comment]
> Reported and now fixed, please be sure to update your version.

Err... I did update. But it's there for me, not fixed. 

Version 3.3.0+1460~g265c4e3be-dirty

**Comment by ptilopteri** [comment]
remove your build environment and the output directories, 
and rebuild

**Comment by AlicVB** [comment]
and if this doesn't solve it, I'll need some more infos...
you speak about zoomable and filmstrip, but they can't be shown together, so I'm a little lost :)

**Comment by maboleth** [comment]
> remove your build environment and the output directories,
> and rebuild

I just did. Deleted everything and installed from scratch. Same. :(


> and if this doesn't solve it, I'll need some more infos...
> you speak about zoomable and filmstrip, but they can't be shown together, so I'm a little lost :)

Sorry about that. I thought about film roll, not strip. In that roll I have 5 files and they display these "features" above when zooming in with a mouse.

**Comment by AlicVB** [comment]
ok, I reproduce, it's exactly the same bug as with filemanager some days ago. I'll take care !

**Comment by AlicVB** [comment]
err... no in fact the issue is solved for zoomable too (I was not in the right branch...) sorry for the error !

So I'll definitely need more infos and especially : 
1. exact steps to reproduce
2. does it happen with all filmroll ?

**Comment by maboleth** [comment]
1. You got to start darktable in zoomable mode. **Starting or selecting file manager or culling then going back to zoomable mode fixes this bug!**
2. Play with the zoom levels with middle mouse button. Notice top arrow border appearing, esp. on the first row of images.

3. Yes, in all filmrolls, regardless of the size. This bug is zoomable mode only - other modes actually fixes it for that session (until DT closes).

**Comment by AlicVB** [comment]
hmm... really strange... I just try several times your exact steps : 
1. start dt and choose zoomable mode
2. quit and restart dt
3. play with mouse scroll to zoom in out like a mad => no arrows :(

and what is even more strange is that the arrow should only appears if the thumbnail widget is in the "active images" list, which is only populate if you enter culling, preview, darkroom, ... (the previous bug was due to this list not freed correctly on the return to lighttable)
and here, the list should never be populated :(

I fear that I (or some other dev) will need to be able to reproduce in order to fix...

**Comment by maboleth** [comment]
Well, not sure If I got you right, but zoomable mode also populates those? or not?

Here's the screen capture. On my end, as soon as I start zooming in/our, those lines appear.

cvrkutanje.net/zoomb.mkv

**Comment by AlicVB** [comment]
no, zoomable doesn't populate active image list (at least it shouldn't)
Thanks for the video. it confirm that we are speaking from the same thing. I'll retry again to reproduce

**Comment by maboleth** [comment]
No more lines for me after the latest update, where DT crashed after entering zoomable mode. Seems fixed!
