### ISSUE TITLE
pref dialog long to close, trigger system alert

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#6820]
**Describe the bug**
Closing pref dialog with "standard" close btn sometimes takes ages (normal, we have to save all the stuff inside), which trigger system alert "this window doesn't respond, do you want to kill it" (rough translation)

**To Reproduce**
open pref dialog, and close it (no need to change anything)

**Expected behavior**
no alert :) 

**Platform (please complete the following information):**
 - Darktable Version: 3072c53cc7314db1936bb9735f235de1b25fffd4
 - OS: linux with xfce (it's certainly xfce which trigger the alert)

**Additional context**
Maybe we can intercept the closing event, discard it (to please the system) and then destroy the window manually once everything is correctly saved  ? (I've done a quick try without succes)

Even better, we could display some waiting message (but this will certainly need more work)

Note : we can see that as an upstream problem from xfce, but I'm not sure that closing window with long delay is fine either (and the system alert is really handful in most cases)

**Comment by parafin** [comment]
How long are we talking here? Why it’s so slow?..

**Comment by AlicVB** [comment]
it takes about 5-6 seconds... No idea why it's so slow. I suppose it's due to pref saving, but I've no real idea how this part of dt works...

**Comment by Nilvus** [comment]
I sometimes have that too, but it's not recent. Not sure it's only because of pref saving. When I was working on CSS, I have that quite often when just changing CSS theme or when applying some CSS settings in CSS editor (even sometimes when it was a simple tweak with one line).

**Comment by jenshannoschwalm** [comment]
Database backup?

**Comment by TurboGit** [comment]
> it takes about 5-6 seconds... No idea why it's so slow. I suppose it's due to pref saving

Hum in 6 seconds standard computers could write some Gb of data on disk. So it must have something else...

**Comment by TurboGit** [comment]
> Database backup?

This is not done when changing preferences.

**Comment by elstoc** [comment]
I'm running Linux with the XFCE and I haven't noticed any such issues

**Comment by parafin** [comment]
It would be good to monitor CPU and disk utilisation during these 5 seconds. It may give some pointers on what is happening. Also check your dmesg and "-d all' output of darktable. Maybe there are some issues reported there.

**Comment by AlicVB** [comment]
oops, I'm ashamed :( 

thanks to @Nilvus comment, I've spotted the culprit : it's the gtk inspector ! In fact I've completely forgot it, as it has now become a tool like the others, launched automatically with my debug script...

So nothing to do with dt, and certainly normal considering the number of widgets of the prefs dialog...
Really sorry for the noise !

**Comment by Nilvus** [comment]
> oops, I'm ashamed :(
> 
> thanks to @Nilvus comment, I've spotted the culprit : it's the gtk inspector ! In fact I've completely forgot it, as it has now become a tool like the others, launched automatically with my debug script...
> 
> So nothing to do with dt, and certainly normal considering the number of widgets of the prefs dialog...
> Really sorry for the noise !

Glad to have helped and now reading your comment, I confirm that indeed that happen only when Gtk inspector tool is launched.
