### ISSUE TITLE
segmentation fault by the highpass module

### ISSUE THREAD

**Issue by ubal2** [darktable-org/darktable#6821]
**Describe the bug**
when I activate the highpass module, a "segmentation fault" occurs.

**To Reproduce**
1.  activate the highpass module

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0~git1449.721d63433
 - OS: Debian: buster
 -  OpenCL enabled
 - 

**Additional context**

**Comment by TurboGit** [comment]
Fixed today.
