### ISSUE TITLE
[Win DT 3.3.0-1463] Gradient mask does not retain changed position

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6824]
Windows Build: master 5bfa1f2ed
On a module (in my case exposure 1)
Drawn mask -> Pick gradient.
Gradient gets displayed on the image.
Move mouse onto image. Left click to rotate gradient. Rotated it 90 degrees to make it point left.
Leave mouse.
Gradient reverts to original position pointing downwards.

**Comment by chhil** [comment]
Bump.

**Comment by TurboGit** [comment]
I cannot reproduce.

**Comment by chhil** [comment]
See if this helps you reproduce what I am seeing.
Select gradient in any module.

As soon as the gradient is drawn moving mouse to image (mouse is currently where the vertical down pointing line is).
![image](https://user-images.githubusercontent.com/1119439/98931153-b06d1300-2503-11eb-976a-91010528207e.png)

Move mouse around to place where you want the gradient.
![image](https://user-images.githubusercontent.com/1119439/98931285-d397c280-2503-11eb-99a1-66d68f1b8ebd.png)

Now left click and keep pressed and move mouse to rotate gradient.
![image](https://user-images.githubusercontent.com/1119439/98931349-e90cec80-2503-11eb-90c5-e62f6bdc7009.png)

Leave the pressed mouse and gradient returns to pointing down.
![image](https://user-images.githubusercontent.com/1119439/98931467-12c61380-2504-11eb-9da7-2001af20d16b.png)

**Comment by TurboGit** [comment]
Ok, reproduced, the key is to left click and keep pressed to rotate. Thanks for the reproducer.

**Comment by TurboGit** [comment]
Ok can you test #6873 ? It was quite difficult to understand and find the way to fix issue !

**Comment by chhil** [comment]
Got the latest master, got the gradient.c from your branch and updated the local file. 
Works as expected.
Thank you.

Closed with fix #6873
