### ISSUE TITLE
better blending mode widget layout

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6826]
**Is your feature request related to a problem? Please describe.**
better blending mode widget layout

**Describe the solution you'd like**
the current button (last on the right) is smaller than others, I'm sure we can do better, see:

![image](https://user-images.githubusercontent.com/467069/98645082-b8755900-2331-11eb-8b4d-688a04179bc8.png)

**Comment by TurboGit** [comment]
@Nilvus : I'm sure you can do better. TIA.

**Comment by elstoc** [comment]
Seems to be a similar issue with the menu button on the module groups

**Comment by Nilvus** [comment]
> Seems to be a similar issue with the menu button on the module groups. The following CSS seems to resolve both issues:
> 
> ```
> #blending-tabs #dt-button { min-width: 1.5em; }
> #modules-tabs #dt-button { min-width: 1.5em; }
> ```

Thanks @elstoc. I just find that a little too big. 1.3em seems better. If it's ok for you, I could post a PR with that code in CSS in good place.

**Comment by Nilvus** [comment]
I have something I think a little better. Will propose a PR. And thanks again @elstoc: you proposal helps.

**Comment by elstoc** [comment]
> I just find that a little too big. 1.3em seems better. If it's ok for you

That's fine - that was just the first thing I tried.
