### ISSUE TITLE
Remove ellipsizing on parametric mask channels

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6827]
Most parametric mask channels are one or two characters and it doesn't really make sense to ellipsize them when shrinking panels. For example:

![Screenshot_2020-11-10_08-31-25](https://user-images.githubusercontent.com/9555491/98649142-2704e780-232f-11eb-8a3f-717460c41b4c.png)

There is already an existing control that allows you to cycle through them with arrow buttons and that should be sufficient

**Comment by dterrahe** [comment]
I'll add a strlen check in dt_ui_notebook_page
