### ISSUE TITLE
color calibration : color picker error 

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6831]
**Describe the bug**
Each time the color picker is selected a bunch of errors are reported on the console.

```
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
```

**To Reproduce**
1. Go to darkroom
2. Activate new module color calibration
3. Select color picker on the CAT tab
4. See error on the console:

**Expected behavior**
No error on the console.

**Platform (please complete the following information):**
 - Darktable Version: current master
 - OS: GNU/Linux Debian

**Comment by TurboGit** [comment]
@aurelienpierre : On for you, I have now found the reproducer for this error. TIA.

**Comment by aurelienpierre** [comment]
That's for any color picker actually. Need to investigate but there should be no RGB conversion for color pickers at this place in the pipe, we already are in RGB.

**Comment by aurelienpierre** [comment]
It also seems to be a false positive, since the values read by the color pickers are accurate (picking a white surface in channelmixerrgb results in proper white balance, filmic correctly reads the max RGB, etc.)

**Comment by TurboGit** [comment]
The problem with the picker is that the picker_cst (colorspace) is never set except for the blend gui.

See the call to dt_iop_color_picker_set_cst() is not done in any module except colorzone where the picker works as expected.

Question, what default should the picker be initialized to ? I suppose it should be using the default working colorspace of the module, right ? So maybe we could initialize it with module->default_colorspace() ? What do you think ?

**Comment by TurboGit** [comment]
@aurelienpierre : see #6837 for a proposed fix.
