### ISSUE TITLE
Color calibration can't handle dng files.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#6840]
**Describe the bug**
When using a dng file and if you press *reset params* on the white balance module while in the modern chromatic adaption workflow the image is completely messed up.

Only way to recover from this is to go back to the legacy workflow, discard the history and go back to the modern workflow. I have not found a way to restore the original image while in the modern workflow.

**To Reproduce**

1. Load a dng file
I used this one from pixls: https://discuss.pixls.us/t/playraw-is-this-dng-ok/14871)

![1 loaded](https://user-images.githubusercontent.com/56407344/98714602-fea5d900-2380-11eb-879e-7fdc6015496a.png)

2. Activate color calibration:

![2 calibration on](https://user-images.githubusercontent.com/56407344/98714667-17ae8a00-2381-11eb-8f8d-b71b02c68c72.png)

3. Press white balance *reset params*:

![3 reset wb](https://user-images.githubusercontent.com/56407344/98714720-285f0000-2381-11eb-9f48-48d1a76f7db0.png)

**Expected behavior**
Keep a decent image after pressing reset params or be able to reset 

**Platform**
* darktable        : 3.3.0+1484 gd64d8b0ad
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.6)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by jade-nl** [comment]
I just noticed this in lighttable:
![screen](https://user-images.githubusercontent.com/56407344/98716336-4fb6cc80-2383-11eb-8dbe-fafd1b52202c.png)
The other 2 images, also DNG files, I did not touch!

**Comment by jade-nl** [comment]
Could it be that the (variable) value calculated by using the *camera reference* button is the culprit?

It was already noted/established that the maths behind that white balance module button does not come close to a D65 value when it encounters a DNG file ([4360](https://github.com/darktable-org/darktable/pull/4360#issuecomment-677665668))

If the output of the maths used should come close to 6504 (CIE Standard Illuminant D65) could this be solved by using this, fixed, value instead of the variable output of the maths used?

**Comment by aurelienpierre** [comment]
Reproduced and understood, fix incoming.

The DNG case, where matrix is embedded, is simply not handled.

**Comment by aurelienpierre** [comment]
See https://github.com/darktable-org/darktable/pull/6836 for a fix. I have only reverted the behaviour to original for DNG (aka the input matrix is embedded and darktable can't find it). 

We still need to improve DNG handling in darktable, so far the modern CAT will not apply to them and the white balance module is only loading presets for them, not fetching the real numbers. Plus, the WB can be achieved in DNG by using DNG profiles, which basically profile the camera sensor for 2 illuminants (A and D65) with a LUT for each one, so the WB is actually achieved by interpolation between the LUTs at profile level.

**Comment by jade-nl** [comment]
After integrating your personal cat-workflow branch mentioned in #6836 I am not able to (forcefully) recreate the above issue.

Closing this one.
