### ISSUE TITLE
Color calibration: Strange result when using AI (both of them)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#6841]
**Describe the bug**
When using the AI options, bot the *image edges* and *image surfaces* the resulting image is monochrome with a splash of purple in it.

**To Reproduce**
0. Be in the modern workflow
1. Load image
I used this one from pixls: https://discuss.pixls.us/t/play-raw-a-cats-portrait/11122
![1 cat loaded wb](https://user-images.githubusercontent.com/56407344/98715662-601a7780-2382-11eb-9f64-4d980ae4ef28.png)
ALSO: Do have a look at the white balance module and what it (doesn't) show. Happened more often, but not consistent.
2. In the *color calibration* module use either of the AI options.
![2 cat after ai edges](https://user-images.githubusercontent.com/56407344/98715856-99eb7e00-2382-11eb-974d-f09bd510355e.png)
ALSO: CCT Invalid?

**Expected behavior**
A decent colour calibrated image

**Platform**
* darktable        : 3.3.0+1484 gd64d8b0ad
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : 
* Graphics driver  : nvidia ()
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.6)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by elstoc** [comment]
The WB module losing its controls is expected - it's set to D65 and you can't change it because you've chosen to do white balancing in the color calibration module ("modern"). I reproduce your issues with the AI modes though

**Comment by jade-nl** [comment]
> The WB module losing its controls is expected

Then it should be consistently off (or on) when in *modern* workflow mode.

**Comment by elstoc** [comment]
No I think you have to discard history for it to fully take to modernity.

**Comment by jade-nl** [comment]
LOL compatibility out of the window :-))

I can confirm that discarding the history stack will resolve the empty vs filled white balance issue.

But that isn't the main/important one here, the AI problem is.

**Comment by AxelG-DE** [comment]
on my laptop even worse
fresh edit, modern workflow
![Screenshot_20201110_230550](https://user-images.githubusercontent.com/49004103/98739421-9a4b3f80-23a9-11eb-8cb2-a8b001fa57c1.png)

using intel on-cpu opencl

* darktable version : 3.3.0+1248~g479426b49
* OS                : Linux - kernel 5.7.10-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by AxelG-DE** [comment]
it seems related to that pic, I tried others (incl ARW) with o.k. reaults

**Comment by elstoc** [comment]
I've seen similar things with a NEF from another playraw and CR2 images of my own

**Comment by jade-nl** [comment]
@AxelG-DE : The reason your result is much worse compared to mine has to do with the pixel workflow that is being used.

My default is *none* and if I switch to *scene referred* I get a result that looks like yours.

**Comment by AxelG-DE** [comment]
Then I think, there might be an interaction with filmic even.

Wondering, what @aurelienpierre thinks about that.

Cheers from therealoffice :-)

**Comment by aurelienpierre** [comment]
And that's the moment when people realize that AI is nice when it works, and completely shit otherwise.

Just use the color picker, which takes the average RGB in the picture, as the old WB does, when this happens. I have no fix to propose here, it's just that the picture doesn't match the assumptions on which the AI algos are based (grey edges).

**Comment by elstoc** [comment]
> And that's the moment when people realize that AI is nice when it works, and completely shit otherwise.

Fair enough, but I haven't really found anything it works on yet.

**Comment by jade-nl** [comment]
If this AI part is so finicky, should it be part of the finale release? This all depends on the hit/miss ratio, I'm sure, but people do expect automation to work most of the time.

**Comment by AxelG-DE** [comment]
> > And that's the moment when people realize that AI is nice when it works, and completely shit otherwise.
> 
> Fair enough, but I haven't really found anything it works on yet.

Also for me fair enough, I just think we need user guidance (e.g. kinda popup)

I have some examples from "play raw" which worked on my laptop, so it I'd not 100% odd ;-)

**Comment by aurelienpierre** [comment]
It seems to have some regression after the introspection change in channelmixerrgb. The auto detection fails on images where it used to work. I will check.

**Comment by jade-nl** [comment]
The obviously wrong result is indeed fixed.

Results might still be sketchy. Try *AI detect from edges* on the example I used. This, however, is in the realm of how the underlying algorithm might not work in certain situations (or: YMMV). Not a bug in my opinion.

**Comment by aurelienpierre** [comment]
Any edge detection or enhancement algo, all over image processing, will be sensitive to noise. So AI detect from edges will not be suited for high ISO.
