### ISSUE TITLE
keep parametric mask setting when changing new blending mode

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6843]
**Is your feature request related to a problem? Please describe.**

Keep parametric mask setting when changing new blending mode

**Describe the solution you'd like**

When editing a picture I had started setting a parametric mask. I wanted to see if I could do better or at least the difference when using the "RGB (display)" blending mode, back to "RGB (scene)" mode I discovered that my settings were lost.

It would be really nice to keep the setting of widgets in all modes even if only the current one is used.

**Comment by TurboGit** [comment]
@hlecleme ; do you think something like this would be possible ?

**Comment by hlecleme** [comment]
There are the following options that could make it work (most probably not exhaustive as I don't know all the parts of darktable):

- Update the blend parameters to store the mask settings for all blending modes. I do not like this as it will add/duplicate more data in the parameters, it's another change in the parameters version, and could cause confusion of not finding the last modified settings when selecting a previous item in the history. The only advantage I see would be to keep all the parameters when compressing the history stack.

- Keep the whole set of settings in the GUI parameters (`dt_iop_gui_blend_data_t`). Disadvantage: it is only kept in memory during the editing session. Going back to lighttable and then to darkroom will loose the settings.

- Iterate over the history to locate the last edit with the selected blending mode, but I don't know if we may do this in the GUI? This would have the advantage of also keeping the information across editing sessions, but it will loose the settings when compressing the history. When the blending mode is switched to another one, the module would need to store the change as a separate item (not the case at the moment).

**Comment by TurboGit** [comment]
My preference is for option 2. Not too complex and it seems ok to keep only during the editing session.
