### ISSUE TITLE
control line notice: [_transform_matrix] invalid conversion from 2 to -1 [dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6847]
starting dt from control line,
  /bin/darktable --library :memory:

I see a lot of the following and do not know if they indicate a
problem:

[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1

openSUSE Tumbleweed 20201108
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable 3.3.0+1486~g132b636fe
OpenCL loaded & running
i7 12-core 36GB
kernel 5.9.1-1-default
darktable built locally

**Comment by chhil** [comment]
probably related to https://github.com/darktable-org/darktable/issues/6831

**Comment by TurboGit** [comment]
Yes, and fix is here : #6837 I'll merge it today.

**Comment by ptilopteri** [comment]
tks
