### ISSUE TITLE
Cannot update star rating by clicking on stars in duplicate manager but can use numeric keys to set them.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6864]
3.3.0+1520~g26b4e09d4

The title describes the issue.

**Comment by Nilvus** [comment]
Clicking on stars in duplicate manager has been disabled some weeks ago. It's not recent and that has been disabled just because thumbnails are to small. It's not the best place to set stars. So it's not a bug, it's the wanted behavior.

**Comment by chhil** [comment]
Maybe disable the changing iof ratings using the number keys  too , to be consistent?

**Comment by Nilvus** [comment]
> Maybe disable the changing iof ratings using the number keys too , to be consistent?

Having it enabled or disabled with shortcut doesn't really change anything. Most will not use it and few could like to have it. So I think it's not something important.
