### ISSUE TITLE
map: d&d on the map does not work

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#6866]
**Describe the bug**
drag and drop from filmstrip to map to geolocalize on image does not work anymore

Probably due to recent work on map view.

**Expected behavior**
Image should be placed on the map and geolocalised.

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux

**Comment by TurboGit** [comment]
@phweyland : On for you I think, TIA.

**Comment by phweyland** [comment]
I look at it.
