### ISSUE TITLE
Compressing history that has multiple exposure modules and copying on new image pixelates it

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6868]
3.3.0+1520~g26b4e09d4 on Ubuntu 20 run on windows using WSL (windows subsystem for Linux).

Compressed history stack of edited image1.
Cleared history of edited image2 by compressing to **original**.
Copied history (ctrl+c) of image1 from filmstrip.
Pasted history on image2.

![image](https://user-images.githubusercontent.com/1119439/98928851-4bfc8480-2500-11eb-801a-0a15da86259c.png)

There were 2 exposures modules. If I disable exposure1, the image becomes alright.

**Comment by dterrahe** [comment]
Is this a recent regression or was this "always" broken?

**Comment by chhil** [comment]
I haven't seen this before but then I haven't tried the steps I indicated before. Plus, multiple exposure module is something I have started using on a lot more images recently. Sorry can't be more helpful.

**Comment by TurboGit** [comment]
I cannot reproduce with current master. Maybe some missing steps in the procedure to reproduce ?

**Comment by chhil** [comment]
I will try and get a better reproducer later today.

**Comment by chhil** [comment]
Since I did not want to ruin the edit on the image that was corrupted previously, this is what I did to reproduce.


In duplicate manager created a duplicate using the original button.

Copied the history of image 1.
![image](https://user-images.githubusercontent.com/1119439/98961184-49fbeb00-252b-11eb-9848-c31fc957fc45.png)

Pasted the history on image 2.
Did not run into a problem yet (unlike original post).
So I compressed history of image2 to original.
Pasted the previously copied history.
The image got corrupted.

Now going to another image and back to this image via filmstrip, get the image back from corrupted to a proper pasted one.

I don't have opencl enabled.

**Comment by elstoc** [comment]
The previous issue was about darktable trying to interact with modules outside of the current pipe (with iop_order = INT_MAX). Could this be something similar? Trying to merge the copied modules with ones that are no longer active.

**Comment by chhil** [comment]
I am still seeing this on current master.

**Comment by johnny-bit** [comment]
This should be fixed on master with recent https://github.com/darktable-org/darktable/pull/7511 being merged. Please test and report back! If the issue is fixed, please close :)

**Comment by chhil** [comment]
Can't reproduce. Closing.
