### ISSUE TITLE
Duplicate Manager Image click misbehavior. 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6872]
Current master.
Make a duplicate of an image.
Short Click the one that is not active, image does not become active. 
Click and keep mouse pressed, the image is displayed in the main view for as long as moused was kept pressed.
Double click on the image to get the image to become active and displayed.

Is this the expected behavior?

**Comment by AlicVB** [comment]
yes it is.
single press is to allow a quick compare between duplicate
