### ISSUE TITLE
Map view "show all" does not work

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#6876]
**Describe the bug**
The map view always indicates the current location only on the map even if there are several locations on the visible map and "show all" has been toggled in the "locations" module.

**To Reproduce**
- Go to map view and create several locations within the visible map.
- Toggle "show all"

**Expected behavior**
- All locations are indicated by an ellipsis or rectangular shape.

**Platform (please complete the following information):**
 - Darktable Version: Git master
 - OS: Linux, Ubuntu 20.04, 64-bit, AMD64

**Additional context**
I started to debug this and found that the code for drawing all locations is actually executed as I would expect. More precisely, the function `_draw_location` in

```c
  if(dt_conf_get_bool("plugins/map/showalllocations"))
  {
    lib->loc.others = dt_map_location_get_locations_on_map(lat0, lat1, lon0, lon1);
    for(GList *other = lib->loc.others; other; other = g_list_next(other))
    {
      dt_location_draw_t *d = (dt_location_draw_t *)other->data;
      d->location = NULL;
      if(lib->loc.main.id != d->id)
      {
        d->location = (void *)_draw_location(lib, d->data.shape, d->data.lat, d->data.lon,
                                             d->data.delta1, d->data.delta2 * d->data.ratio,
                                             FALSE);
      }
    }
```
in `map.c` is called several times, which equals the number of defined locations. The locations, however, are not visible. Possibly, Cairo draws on an invisible canvas.

Side note: The button "show all" works as a toggle button, which is unusual for the darktable UI. A checkbox might be more appropriate.

**Comment by TurboGit** [comment]
No, I suppose this is because the location is not fully on the current map area. For a location to be visible ts entirety must fit on the view.

**Comment by rabauke** [comment]
@TurboGit I am sure that at least two (ore more) of the defined locations where fully on the current map area.

**Comment by TurboGit** [comment]
@rabauke : so we'll need a step by step to reproduce as all works as expected on my side, maybe a special layout...

**Comment by TurboGit** [comment]
Maybe @phweyland will have more luck that me to reproduce.

**Comment by phweyland** [comment]
@rabauke is the issue permanent or sporadic ?

> Possibly, Cairo draws on an invisible canvas

I may have missed something here. What do you mean by canvas ?

dt sends the pixbuf to osmgpsmap which actually draws the image on the map. There is no difference between the main shape and the other shapes, except the thickness of the line. Which is your screen definition (mine is poor, 1650x1050) ?

**Comment by phweyland** [comment]
Any other info about the main issue ?

**Comment by johnny-bit** [comment]
@rabauke - pinging here... do you still observe the issue or is it fixed for you? Also - there was a recent release of osm-gps-map which should fix additional issues (which reminds me - I need to do new release)
