### ISSUE TITLE
EXIF data incomplete for DNG formats

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#6886]
I am currently shooting DNG+JPG and notice that while the JPG sidecar file shows **Exposure**, **Exposure-Bias** and **Aperture** the sidecar file for the DNG does not show this information.
The absence of these 3 pieces of information is a major deficiency for the increasing number of people working with the DNG format.
DigiKam does show these 3 missing items.

**Comment by kmilos** [comment]
Please stop opening duplicate issues. You have already reported this as #6686 and #6817 already.

A fix has been proposed, so instead of spamming the developers and wasting time on bug triage, please help test it.
