### ISSUE TITLE
Nikon Z6 ii 

### ISSUE THREAD

**Issue by sparkynikonz6ii** [darktable-org/darktable#6898]
This might be due to it being a new camera. But I have the Nikon Z6ii,  using raw files, I've tried all of them 12 bit, 14 bit, compresses, non compressed etc.  I get the same result when I try to open the in darktable.  

![image](https://user-images.githubusercontent.com/74437771/99134596-6f046280-25ec-11eb-8989-0beedacd6eba.png)

Same message all files,  I can open them in other editors no issue.  Has anyone ran into this? 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  Windows 10
 -   yes
 -  

**Additional context**

**Comment by LebedevRI** [comment]
Please contribute full sample set to https://raw.pixls.us/:
* 14bit Lossless compressed
* 12bit Lossless compressed
* 14bit Compressed
* 12bit Compressed
* 14bit Uncompressed
* 12bit Uncompressed

**Comment by caretakerscurse** [comment]
I have uploaded the requested files. If you need anything else please let me know.

**Comment by LebedevRI** [comment]
Thank you. It's great that the images are consistent (have the same content)
However, as it is stated on that page, ideally the images should be of something like daylight landscape,
with low ISO. The reason being, the provided images are noisy, and the edges of image are all dark/unilluminated,
which means it's not really possible to check that the right crop is used, and no garbage pixels remain.

**Comment by caretakerscurse** [comment]
Sorry I missed that. It's overcast currently but I can grab a shot of some trees. Would that still be ok?

**Comment by caretakerscurse** [comment]
Uploaded, I might have messed up the comments on two of them so just in case... 
299,300,301 are 14bit.
302,303,304 are 12bit.
and the order is: Lossless Compressed, Compressed, Uncompressed.

Sorry again for the trouble.

**Comment by LebedevRI** [comment]
Thank you for the samples, those seem good!

**Comment by caretakerscurse** [comment]
Good to hear, if there is anything else you need I'm happy to help.

**Comment by sparkynikonz6ii** [comment]
Thanks Caretakerscure,  for sending files, just getting back to this.

**Comment by sparkynikonz6ii** [comment]
I was watching a Youtube video about the Z6ii, in the comments someone asked about support for the raw files in Adobe Light room, someone in the comments section said they got theirs to work by editing with exif data.  They used a mac command line to change the model tag to Nikon Z6.  I use windows, so I thought I would try it by right clicking on a raw file, properties, details tab, and deleted the _2 after the camera model.  The files now open in dark table that I make that change too. 


![image](https://user-images.githubusercontent.com/74437771/99531601-fba67c00-2970-11eb-950a-caee3120d1e7.png)

with edit

![image](https://user-images.githubusercontent.com/74437771/99531656-11b43c80-2971-11eb-893f-9e9bcb98eb46.png)


Hope this helps.

**Comment by TapTac13** [comment]
Hey everyone, 
sorry, but I just want to ask, if there is any success in implementing the Nikon Z6ii in Darktable? 

The solution wich "sparkynikonz6ii" provided, worked for me. 
But you need first install the Codec from Nikons official site and yeah it´s a work around, but it dosen´t feel right. :( 

So if there are any Updates to the actual status of progress, i´m really glad to hear about it. 

Thank you &
with kind regards
TapTac

**Comment by LebedevRI** [comment]
Last time i checked adobe dng converter does not support that camera => we can't get "canonical" color matrix for that camera.

**Comment by kmilos** [comment]
> Last time i checked adobe dng converter does not support that camera

I think the 13.1 released a couple of days ago does (and Z 7 II): https://helpx.adobe.com/camera-raw/kb/camera-raw-plug-supported-cameras.html

**Comment by LebedevRI** [comment]
I saw that, unfortunately they seem to have forgotten to include the actual software.exe into the installer.

**Comment by kmilos** [comment]
That's a shame...

Just an idea: maybe it's ok to take leap of faith and copy Z 6 and Z 7 values (supposedly the sensors didn't change; there is precedent in Sony 7C recently), and risk sub-optimal colours rather than face eager 3.4 users with the no-go screen...?

**Comment by LebedevRI** [comment]
Not only do we risk that the colors will be suboptimal, once we get the proper matrix,
all the previously edited images silently degrade, since the color matrix changes.
(Unless of course `colorin` now stores the matrix used?)

**Comment by sparkynikonz6ii** [comment]
I've been using Lightroom with my Z6ii,  since the update the colors do
seem more vibrant than in Darktable edits.  I've got limited experience
with both though.

**Comment by kmilos** [comment]
You're probably right, better play safe... Z 5 and D750 were supposed to use the same sensor by some reviewers, but adobe coeffs are different, so it's probably not in reality.

P.S. How was A7C validated out of curiosity, since it also appears only in 13.1 as well?

**Comment by LebedevRI** [comment]
> P.S. How was A7C validated out of curiosity, since it also appears only in 13.1 as well?

Pretty sure it was supported by previous version already.
Perhaps then is was preliminary supported only.

**Comment by sparkynikonz6ii** [comment]
I have successfully opened a nef file from my z6ii in photoshop, once
inside there it allows it to be exported as a DNG, is that what you need to
get the matrix?

**Comment by TapTac13** [comment]
I´m sorry to bother you again, but how is the actual state of progress? 

Is there anything I could do, to support you? 

I own an Nikon Z6 II, probably by providing data or something, or research something. 
It makes me really sad that i´m not able to edit my pictures in Darktable. 

The workaround from sparkynikonz6ii provides sadly a bad representation of the colors. So it is for me not really useable. 

Thanks for everything!

**Comment by LebedevRI** [comment]
We are still missing color matrix.
While Adobe DNG Converter 13.1 is claimed to support the camera,
it's installer lacks the actual DNG Converter executable, somehow.

**Comment by sparkynikonz6ii** [comment]
So do you need a raw photo converted to DNG? I can try to make one tonight
when I get home.

**Comment by TapTac13** [comment]
I Installed the Adobe DNG Converter and tried to convert two raw files to DNG. It worked without a problem. 

I Used the pre-configuration from the Converter.  
Just activated the "implement original" selection box.

Compatibility: Camera Raw 12.4 and newer
JPEG-Preview: middle
Used lossless compression
Keep the number of image pixels
Implement original  

If it helps, I could try to converted some Files with same content, just tell me what you need and I try to provide it to you.
