### ISSUE TITLE
Module Search and Unpublished Aliases

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#6902]
Module search in the darkroom was previously an index search on module names. It was clear from the filtered set of modules how the search term and the matched modules were related.

With the introduction of module aliases this is no longer the case: if I start typing "sa" for example, I get a load of modules, only one of which has the letters "sa" in the module name. This will cause confusion and the problem is that the module aliases are purely internal and unpublished - I have no way to know that the modules have been matched on the word "saturation". 

One possibility would be to turn the search box into a combobox with an entry, so that the matching aliases/keywords are shown in the combobox below (or above) while typing. The user may then use the arrow keys and `Enter` or the mouse to select a matching keyword but the currently typed term will continue to filter the list. As an extra bonus, if there is only a single match when the user selects an item with mouse/enter, that module can be automatically expanded.

**Comment by parafin** [comment]
Maybe add a way to search only for name match? E.g. by prefixing the input with " character.

**Comment by elstoc** [comment]
I would like a way to restrict to only module name search but would like to be able to permanently enable that mode (though I can see the usefulness of aliases) but this is more about being able to make alias searches clearer for the end user.

**Comment by elstoc** [comment]
Also, an aside here, "alias" is really not the right word. This is a keyword or tag search - "saturation" is not an _alias_ of "filmic".

**Comment by parafin** [comment]
Agreed about alias not being an alias.

So maybe search field should have 2 modes - fuzzy (include tags in the search) and strict (with fuzzy being default) and a toggle next to it to select the mode (do not hide it into preferences). And I guess these tags need to be discoverable in GUI somehow after all, I raised that question in original PR that introduced aliases. But we need an idea where to display them.

**Comment by elstoc** [comment]
> I guess these tags need to be discoverable in GUI

Agreed. I'd say tooltips but them tooltips are already getting mighty big.

**Comment by sjjh** [comment]
Suggestion on how to improve/display it: Show the tag that had a hit as part of the search on the right hand side next to the module title. Alter the font (e.g. darker font color and using _italic_) to reduce the contrast a little to show that it is not part of the title (maybe not using _italic_ and only changing the font color would work as well, but the difference to the title is then not too big if the search term highlight uses the same font color as the title). I suggest to use the same color for the tag that is used for the module buttons if in preferences the option "show right-side buttons in processing module headers" is set to "dim". Showing the tag containing the search term hit improves the UX by making it explicit why a module is included in the search results.
To further improve the UX I suggest to additionally highlight (both in title and tag) the search term hit, e.g. by using a brighter font color (using **bold** could work as well, but lead to moving the words a little while typing which might look like a UI bug). Through highlighting, the user can even faster spot why a module was included in the search results.

Open questions:
* when to hide the tag again (suggestion: after the search input looses the focus)?
* if a search hit occurs in title and tag (or in more than one tag): display tag in addition to title (display all tags with search hit) or just display the first term in which a hit occurred (seems sensible/more consistent/more transparent to show all occurrences, but this might lead to showing many (similar) terms without additional value)?
* how to ellipse title plus tag if both together don't fit in column width as they're too long (currently the title is truncated and three dots get appended; this won't work if the search hit is in the last letters of the title/tag)?

A small mock-up how the solution could look like (please don't pay attention to the wording, no idea if the tags are realistic :) ):

![mockup_alias_search_highlight](https://user-images.githubusercontent.com/2787214/103139060-acbed580-46d8-11eb-9170-47af20ae4f1a.png)

**Note:** I agree that the term _alias_ is not really fitting. I'm nevertheless not too happy with calling the term _tag_ or _keyword_ as this might lead to confusion with the tags and keywords used to tag images. I cannot come up with a better term spontaneously though. :)
