### ISSUE TITLE
[color calibration] Custom negative value and then a module rest does not reset slider

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6906]
The sliders started by being all on the left. Just as a test I set slider1 to -0.5 by right clicking and entering the value.
![image](https://user-images.githubusercontent.com/1119439/99146194-f52bb200-269b-11eb-90a4-520748a4355c.png)

Then reset the module, slider1 is 0 now but position is not far left.

![image](https://user-images.githubusercontent.com/1119439/99146156-7e8eb480-269b-11eb-95c8-28fc0b73b177.png)

The slider treats the new position as 0 now. No way to reset it to 0 and keep it far left.

**Comment by chhil** [comment]
The slider has permanently moved, open another image use the module and its still midway.

**Comment by parafin** [comment]
I think this is not specific to color calibration, that's just how soft boundaries work. I don't remember if there is a way to reset the slider. But is it a big problem? Or it's confusing, because other sliders kept their boundaries? Maybe they should extend the range at the same time?..

**Comment by chhil** [comment]
Its odd because now one slider with 0 is midway and others are on the left.

**Comment by elstoc** [comment]
The existing soft boundaries are -1 to +1. Entering a number between these values should not adjust the UI.

**Comment by chhil** [comment]
I just installed a fresh version which rest the values to slider left at 0.

**Comment by aurelienpierre** [comment]
Closing then.

> Edit: I didn't notice that the soft boundaries for grey are changed so this is expected behaviour, but odd (and I preferred the -1 to +1 bounds).

But then, user complained that the -1 to +1 bound allowed himself to input bad settings. So, now the module is children-proof.

**Comment by chhil** [comment]
Other than installing a new DT, can someone tell me how to reset the slider where 0 is to the far left. 

Sometimes I may want to go negative based on perception of the image, then I don't want to be stuck with sliders where one is 0 in the middle and others are 0 towards to left end.

**Comment by aurelienpierre** [comment]
It's simply not possible and probably not desirable usually. Apart from the unbalancing in GUI, if you entered some custom value out of the usual bounds of the slider, usually you may want to still play in the range [custom bound; default max].

**Comment by parafin** [comment]
I think there are 2 questions:

1. How to reset slider bounds to original limits after extending them? Does re-entering the darkroom helps?
2. Can slider bounds of linked settings extend at the same time, so that their values could be compared visually?
