### ISSUE TITLE
[color calibration] Whitebalance warning

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6908]
Working on a jpeg.

I used white balance to get to what I wanted the image to be at. It was not enabled when I started the edit.

Now I want the image to be turned b/.w so I go to color calibration and turn it to b/w.

The white balance now shows its applied twice. Color calibration show warning. I understand color calibration does white balance.

![image](https://user-images.githubusercontent.com/1119439/99147319-0c6f9d00-26a6-11eb-849c-00a1450e81b4.png)

Now I turn off white balance and the color calibration warning is still there.

![image](https://user-images.githubusercontent.com/1119439/99147356-640e0880-26a6-11eb-8017-e6d1549d4359.png)

I in all likelihood am not using this correctly. With raws I don't recall running into these warnings as white balance is always enabled. Maybe its related to https://github.com/darktable-org/darktable/issues/6900

**Comment by chhil** [comment]
The white balance CCT 5973 invalid was generated when I used the dropper to set the white balance.

**Comment by aurelienpierre** [comment]
Read the tooltip over the warning message.

**Comment by aurelienpierre** [comment]
Not a bug : https://darktable-org.github.io/dtdocs/module-reference/processing-modules/color-calibration/#cat-warnings
