### ISSUE TITLE
Noise profile for CANON EOS 1Dx MkII

### ISSUE THREAD

**Issue by MenfinGIT** [darktable-org/darktable#6917]
Here is the noise profile that I made today, I hope this is submitted correctly.
I've tested this on a several noisy photo (between 100 and 20000 ISO) and it produces very good results.

[darktable-noiseprofile-20201114.tar.gz](https://github.com/darktable-org/darktable/files/5541516/darktable-noiseprofile-20201114.tar.gz)

**Comment by rawfiner** [comment]
Thanks!
