### ISSUE TITLE
OSX big sur: opencl no longer working

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#6918]
./bin/darktable-cltest fails with message:
` [opencl_init] could not find opencl runtime library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL'`

the directory /System/Library/Frameworks/OpenCL.framework/Versions/Current/ doesn't contain OpenCL

```
ls -la /System/Library/Frameworks/OpenCL.framework/Versions/Current/
total 0
drwxr-xr-x   6 root  wheel   192  1 Jan  2020 .
drwxr-xr-x   4 root  wheel   128  1 Jan  2020 ..
drwxr-xr-x  14 root  wheel   448  1 Jan  2020 Libraries
drwxr-xr-x  36 root  wheel  1152  1 Jan  2020 Resources
drwxr-xr-x   3 root  wheel    96  1 Jan  2020 _CodeSignature
drwxr-xr-x   3 root  wheel    96  1 Jan  2020 lib
```
**Platform (please complete the following information):**
 - Darktable Version: darktable 3.3.0+1613~gc8f2d6cd9
 - OS: OSX Big Sur

**Comment by johnny-bit** [comment]
Does osx big suck even have open coal? Didn't apple deprecated it?

**Comment by parafin** [comment]
Indeed Apple deprecated OpenCL, but I guess has not fully removed it yet, since framework directory is actually still present. Though they broke something, so let's find out what changed. @MStraeten, could you post an output of `ls -lRA /System/Library/Frameworks/OpenCL.framework/` command?

**Comment by MStraeten** [comment]
```
martinstraeten@Martins-MacBook-Pro build % ls -lRA /System/Library/Frameworks/OpenCL.framework/
total 0
lrwxr-xr-x  1 root  wheel   26  1 Jan  2020 Libraries -> Versions/Current/Libraries
lrwxr-xr-x  1 root  wheel   26  1 Jan  2020 Resources -> Versions/Current/Resources
drwxr-xr-x  4 root  wheel  128  1 Jan  2020 Versions

/System/Library/Frameworks/OpenCL.framework//Versions:
total 0
drwxr-xr-x  6 root  wheel  192  1 Jan  2020 A
lrwxr-xr-x  1 root  wheel    1  1 Jan  2020 Current -> A

/System/Library/Frameworks/OpenCL.framework//Versions/A:
total 0
drwxr-xr-x  14 root  wheel   448  1 Jan  2020 Libraries
drwxr-xr-x  36 root  wheel  1152  1 Jan  2020 Resources
drwxr-xr-x   3 root  wheel    96  1 Jan  2020 _CodeSignature
drwxr-xr-x   3 root  wheel    96  1 Jan  2020 lib

/System/Library/Frameworks/OpenCL.framework//Versions/A/Libraries:
total 12144
drwxr-xr-x   2 root  wheel       64  1 Jan  2020 3425AMD
-rwxr-xr-x   1 root  wheel  3417040  1 Jan  2020 AMDil.dylib
-rwxr-xr-x   1 root  wheel   967744  1 Jan  2020 IGIL.dylib
drwxr-xr-x  30 root  wheel      960  1 Jan  2020 ImageFormats
-rwxr-xr-x   1 root  wheel   803776  1 Jan  2020 NVPTX.dylib
-rwxr-xr-x   1 root  wheel   728720  1 Jan  2020 Vectorizer.dylib
-rwxr-xr-x   1 root  wheel   394464  1 Jan  2020 libCLVMAMDilPlugin.dylib
-rwxr-xr-x   1 root  wheel   224384  1 Jan  2020 libCLVMCPUPlugin.dylib
-rwxr-xr-x   1 root  wheel   114800  1 Jan  2020 libCLVMIGCPlugin.dylib
-rwxr-xr-x   1 root  wheel   174400  1 Jan  2020 libCLVMIGILPlugin.dylib
-rwxr-xr-x   1 root  wheel   129376  1 Jan  2020 libCLVMNVPTXPlugin.dylib
-rwxr-xr-x   1 root  wheel  8154352  1 Jan  2020 openclc

/System/Library/Frameworks/OpenCL.framework//Versions/A/Libraries/3425AMD:

/System/Library/Frameworks/OpenCL.framework//Versions/A/Libraries/ImageFormats:
total 28192
-rwxr-xr-x  1 root  wheel  1052608  1 Jan  2020 float_i.dylib
-rwxr-xr-x  1 root  wheel  1088048  1 Jan  2020 float_rgba.dylib
-rwxr-xr-x  1 root  wheel  1277168  1 Jan  2020 float_rgbx.dylib
-rwxr-xr-x  1 root  wheel  1162624  1 Jan  2020 float_rgx.dylib
-rwxr-xr-x  1 root  wheel  1127136  1 Jan  2020 float_rx.dylib
-rwxr-xr-x  1 root  wheel  1652688  1 Jan  2020 half_i.dylib
-rwxr-xr-x  1 root  wheel  2649872  1 Jan  2020 half_rgba.dylib
-rwxr-xr-x  1 root  wheel  2741088  1 Jan  2020 half_rgbx.dylib
-rwxr-xr-x  1 root  wheel  1365776  1 Jan  2020 sfixed14_rgba.dylib
-rwxr-xr-x  1 root  wheel  1202320  1 Jan  2020 sint16_rgba.dylib
-rwxr-xr-x  1 root  wheel  1086768  1 Jan  2020 sint32_rgba.dylib
-rwxr-xr-x  1 root  wheel  1185040  1 Jan  2020 sint8_rgba.dylib
-rwxr-xr-x  1 root  wheel  1351792  1 Jan  2020 snorm16_rgba.dylib
-rwxr-xr-x  1 root  wheel  1334464  1 Jan  2020 snorm8_rgba.dylib
-rwxr-xr-x  1 root  wheel  1185888  1 Jan  2020 uint16_rgba.dylib
-rwxr-xr-x  1 root  wheel  1533584  1 Jan  2020 uint32_rgba.dylib
-rwxr-xr-x  1 root  wheel  1188832  1 Jan  2020 uint8_rgba.dylib
-rwxr-xr-x  1 root  wheel  1252768  1 Jan  2020 unorm16_rgba.dylib
-rwxr-xr-x  1 root  wheel  1425168  1 Jan  2020 unorm16_rgbx.dylib
-rwxr-xr-x  1 root  wheel  1309200  1 Jan  2020 unorm8_1rgb.dylib
-rwxr-xr-x  1 root  wheel  1118560  1 Jan  2020 unorm8_a.dylib
-rwxr-xr-x  1 root  wheel  1279680  1 Jan  2020 unorm8_argb.dylib
-rwxr-xr-x  1 root  wheel  1326640  1 Jan  2020 unorm8_bgr1.dylib
-rwxr-xr-x  1 root  wheel  1273680  1 Jan  2020 unorm8_bgra.dylib
-rwxr-xr-x  1 root  wheel  1067808  1 Jan  2020 unorm8_i.dylib
-rwxr-xr-x  1 root  wheel  1261728  1 Jan  2020 unorm8_rgba.dylib
-rwxr-xr-x  1 root  wheel  1466016  1 Jan  2020 unorm8_rgbx.dylib
-rwxr-xr-x  1 root  wheel  1281328  1 Jan  2020 unorm8_rgx.dylib

/System/Library/Frameworks/OpenCL.framework//Versions/A/Resources:
total 82608
drwxr-xr-x  4 root  wheel      128  1 Jan  2020 BridgeSupport
-rw-r--r--  1 root  wheel     1432  1 Jan  2020 Info.plist
-rw-r--r--  1 root  wheel  3284068  1 Jan  2020 cl_kernel.amd.dbl.fmath.pch
-rw-r--r--  1 root  wheel  3284004  1 Jan  2020 cl_kernel.amd.dbl.pch
-rw-r--r--  1 root  wheel  2778820  1 Jan  2020 cl_kernel.amd.fmath.pch
-rw-r--r--  1 root  wheel  2778756  1 Jan  2020 cl_kernel.amd.pch
-rw-r--r--  1 root  wheel  3284336  1 Jan  2020 cl_kernel.amd64.dbl.fmath.pch
-rw-r--r--  1 root  wheel  3284272  1 Jan  2020 cl_kernel.amd64.dbl.pch
-rw-r--r--  1 root  wheel  2779084  1 Jan  2020 cl_kernel.amd64.fmath.pch
-rw-r--r--  1 root  wheel  2779024  1 Jan  2020 cl_kernel.amd64.pch
-rw-r--r--  1 root  wheel  2810536  1 Jan  2020 cl_kernel.igil32.fmath.pch
-rw-r--r--  1 root  wheel  2810472  1 Jan  2020 cl_kernel.igil32.pch
-rw-r--r--  1 root  wheel  2810772  1 Jan  2020 cl_kernel.igil64.fmath.pch
-rw-r--r--  1 root  wheel  2810708  1 Jan  2020 cl_kernel.igil64.pch
-rw-r--r--  1 root  wheel  3350652  1 Jan  2020 cl_kernel.x86_64.fmath.pch
-rw-r--r--  1 root  wheel  3350588  1 Jan  2020 cl_kernel.x86_64.pch
-rw-r--r--  1 root  wheel  2659024  1 Jan  2020 runtime.amdil.bc
-rw-r--r--  1 root  wheel  2547568  1 Jan  2020 runtime.amdil64_ci.bc
-rw-r--r--  1 root  wheel  2432272  1 Jan  2020 runtime.amdil64_gfx10.bc
-rw-r--r--  1 root  wheel  2432480  1 Jan  2020 runtime.amdil64_gfx9.bc
-rw-r--r--  1 root  wheel  2528064  1 Jan  2020 runtime.amdil64_si.bc
-rw-r--r--  1 root  wheel  2542816  1 Jan  2020 runtime.amdil_ci.bc
-rw-r--r--  1 root  wheel  2427440  1 Jan  2020 runtime.amdil_gfx10.bc
-rw-r--r--  1 root  wheel  2427648  1 Jan  2020 runtime.amdil_gfx9.bc
-rw-r--r--  1 root  wheel  2526784  1 Jan  2020 runtime.amdil_si.bc
-rw-r--r--  1 root  wheel  5712752  1 Jan  2020 runtime.cligc64.bc
-rw-r--r--  1 root  wheel  2553520  1 Jan  2020 runtime.igil32.bc
-rw-r--r--  1 root  wheel  2556432  1 Jan  2020 runtime.igil64.bc
-rw-r--r--  1 root  wheel  2626420  1 Jan  2020 runtime.nvptx.sm2x.bc
-rw-r--r--  1 root  wheel  2619872  1 Jan  2020 runtime.nvptx.sm3x.bc
-rw-r--r--  1 root  wheel  2619872  1 Jan  2020 runtime.nvptx.sm5x.bc
-rw-r--r--  1 root  wheel  2619872  1 Jan  2020 runtime.nvptx.sm6x.bc
-rw-r--r--  1 root  wheel  3489104  1 Jan  2020 runtime.x86_64.bc
-rw-r--r--  1 root  wheel      503  1 Jan  2020 version.plist

/System/Library/Frameworks/OpenCL.framework//Versions/A/Resources/BridgeSupport:
total 48
-rw-r--r--  1 root  wheel  56798  1 Jan  2020 OpenCL.arm64e.bridgesupport
-rw-r--r--  1 root  wheel  56820  1 Jan  2020 OpenCL.bridgesupport

/System/Library/Frameworks/OpenCL.framework//Versions/A/_CodeSignature:
total 8
-rw-r--r--  1 root  wheel  1383  1 Jan  2020 CodeResources

/System/Library/Frameworks/OpenCL.framework//Versions/A/lib:
total 0
drwxr-xr-x  3 root  wheel  96  1 Jan  2020 clang

/System/Library/Frameworks/OpenCL.framework//Versions/A/lib/clang:
total 0
drwxr-xr-x  3 root  wheel  96  1 Jan  2020 3.2

/System/Library/Frameworks/OpenCL.framework//Versions/A/lib/clang/3.2:
total 0
drwxr-xr-x  4 root  wheel  128  1 Jan  2020 include

/System/Library/Frameworks/OpenCL.framework//Versions/A/lib/clang/3.2/include:
total 112
-rw-r--r--  1 root  wheel  374888  1 Jan  2020 cl_kernel.h
-rw-r--r--  1 root  wheel    6537  1 Jan  2020 cl_kernel_shared.h
```

the OpenCL file present in Catalina or earlier is no longer available there ...

found a comment on this in https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes:

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

**Comment by MStraeten** [comment]
found a working solution - darktable-cltest builds the kernels:
in dlopencl.c, adding libraries mentioned in /System/Library/dyld/dyld_shared_cache_x86_64.map in line 34:

```
#elif defined(__APPLE__)
static const char *ocllib[] = { "/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL", "/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib", "/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcl2module.dylib", NULL };
```

**Comment by parafin** [comment]
That's strange path for opencl library, it doesn't match Apple framework specification, I suspect some other should be used instead. Can you attach that map file, so that I could see the whole list? Are you sure it contains the list of all system libraries?..

Could you please try the following 2 paths for OpenCL library?
/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
/System/Library/Frameworks/OpenCL.framework/OpenCL

You can do it without modification of source code, just set opencl_library setting to the path in darktablerc.

**Comment by MStraeten** [comment]
modifying path didn't work since "OpenCL" is undefined (in catalina there's a file named OpenCL in the framework directory) - i tried several variants. Then i got a hint where to search for the dynamic link cache ... all trial and error until  worked ;)

[dyld_shared_cache_x86_64.map.zip](https://github.com/darktable-org/darktable/files/5542616/dyld_shared_cache_x86_64.map.zip)

**Comment by parafin** [comment]
I'm not sure what do you mean by undefined. Have you tried the exact 2 paths from my previous comment?

**Comment by parafin** [comment]
/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL is present in the map file you attached, and it's one of the options I'm asking to check. It looks correct.

**Comment by MStraeten** [comment]
`static const char *ocllib[] = { "/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL", NULL };`
results in:
```
0.032090 [opencl_init] could not find opencl runtime library '/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL'
0.032099 [opencl_init] no working opencl library found. Continue with opencl disabled
```

**Comment by parafin** [comment]
This doesn't make sense... But those 2 libraries you are using instead doesn't sound right at all. I'm not comfortable using them.

**Comment by MStraeten** [comment]
setting  opencl_library in darktablerc to /System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib is necessary
/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcl2module.dylib is found but results in `0.025574 [opencl_init] could not load all required symbols from library`

**Comment by parafin** [comment]
Can you show output of darktable-cltest when using libcldcpuengine.dylib? There's also /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/3425AMD/libcl2module.dylib - can you try it too?

**Comment by MStraeten** [comment]
0.026709 [opencl_init] found opencl runtime library '/System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/3425AMD/libcl2module.dylib'
0.026774 [opencl_init] could not load all required symbols from library

**Comment by MStraeten** [comment]
just using /System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib results in:

```
martinstraeten@Martins-MacBook-Pro build % ./bin/darktable-cltest
0.024028 [opencl_init] opencl related configuration options:
0.024052 [opencl_init]
0.024055 [opencl_init] opencl: 1
0.024057 [opencl_init] opencl_scheduling_profile: 'default'
0.024059 [opencl_init] opencl_library: '/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib'
0.024062 [opencl_init] opencl_memory_requirement: 768
0.024065 [opencl_init] opencl_memory_headroom: 400
0.024067 [opencl_init] opencl_device_priority: '1,0,*/0,1,*/1,0,*/0,*/*'
0.024070 [opencl_init] opencl_mandatory_timeout: 200
0.024072 [opencl_init] opencl_size_roundup: 16
0.024073 [opencl_init] opencl_async_pixelpipe: 1
0.024075 [opencl_init] opencl_synch_cache: active module
0.024077 [opencl_init] opencl_number_event_handles: 100
0.024080 [opencl_init] opencl_micro_nap: 1000
0.024081 [opencl_init] opencl_use_pinned_memory: 0
0.024083 [opencl_init] opencl_use_cpu_devices: 0
0.024084 [opencl_init] opencl_avoid_atomics: 0
0.024086 [opencl_init]
0.024720 [opencl_init] found opencl runtime library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib'
0.030321 [opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib' found on your system and loaded
0.030327 [opencl_init] found 1 platform
0.046954 [opencl_init] found 3 devices
...
```
everything is fine then

**Comment by parafin** [comment]
Using some random library from the framework still doesn't sound right to me, especially when it has "cpu" in the name. Could you try compiling and running the following test program:
```
#include <dlfcn.h>
#include <stdio.h>

void test(const char* path)
{
	printf("Trying %s...\n", path);
	if(dlopen(path, RTLD_LAZY | RTLD_LOCAL))
	{
		printf("success\n");
	}
	else
	{
		printf("error: %s\n", dlerror());
	}
}

int main()
{
	test("/System/Library/Frameworks/OpenCL.framework/OpenCL");
	test("/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL");
	test("/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL");
	test("/some/random/path/to.framework/to");
	return 0;
}
```
Save to `cltest.c`, compile with `cc cltest.c -o cltest`, run with `./cltest`.

**Comment by MStraeten** [comment]
```
martinstraeten@Martins-MacBook-Pro tmp % ./cltest
Trying /System/Library/Frameworks/OpenCL.framework/OpenCL...
success
Trying /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL...
success
Trying /System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL...
success
Trying /some/random/path/to.framework/to...
error: dlopen(/some/random/path/to.framework/to, 5): image not found
```

**Comment by parafin** [comment]
Then I guess it's a glib problem. Please try run the following code to confirm:
```
#include <dlfcn.h>
#include <stdio.h>
#include <gmodule.h>

void test(const char* path)
{
	printf("Trying dlopen(%s)...\n", path);
	if(dlopen(path, RTLD_LAZY | RTLD_LOCAL))
	{
		printf("success\n");
	}
	else
	{
		printf("error: %s\n", dlerror());
	}
	printf("Trying g_module_open(%s)...\n", path);
	if(g_module_open(path, G_MODULE_BIND_LAZY | G_MODULE_BIND_LOCAL))
	{
		printf("success\n");
	}
	else
	{
		printf("error: %s\n", g_module_error());
	}
}

int main()
{
	test("/System/Library/Frameworks/OpenCL.framework/OpenCL");
	test("/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL");
	test("/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL");
	test("/some/random/path/to.framework/to");
	return 0;
}
```
Compile with
```
cc `pkg-config --libs --cflags gmodule-2.0` cltest.c -o cltest
```

**Comment by MStraeten** [comment]
```
martinstraeten@Martins-MacBook-Pro tmp % vi cltest.c
martinstraeten@Martins-MacBook-Pro tmp % cc `pkg-config --libs --cflags gmodule-2.0` cltest.c -o cltest
martinstraeten@Martins-MacBook-Pro tmp % ./cltest
Trying dlopen(/System/Library/Frameworks/OpenCL.framework/OpenCL)...
success
Trying g_module_open(/System/Library/Frameworks/OpenCL.framework/OpenCL)...
error: dlopen(/System/Library/Frameworks/OpenCL.framework/OpenCL.so, 1): image not found
Trying dlopen(/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL)...
success
Trying g_module_open(/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL)...
error: dlopen(/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL.so, 1): image not found
Trying dlopen(/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL)...
success
Trying g_module_open(/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL)...
error: dlopen(/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL.so, 1): image not found
Trying dlopen(/some/random/path/to.framework/to)...
error: dlopen(/some/random/path/to.framework/to, 5): image not found
Trying g_module_open(/some/random/path/to.framework/to)...
error: dlopen(/some/random/path/to.framework/to.so, 1): image not found
```

**Comment by parafin** [comment]
So definitely glib to blame - I guess it checks file existence before trying (and auto-adds .so when sees that file doesn't exist). I guess I'll workaround by using dlopen directly.

**Comment by MStraeten** [comment]
ok, thanks. I close the pr.
Then at least for those using darktable 3.2.1 on Big Sur setting 
`opencl_library=/System/Library/Frameworks/OpenCL.framework/Versions/Current/Libraries/libcldcpuengine.dylib` in darktablerc seems to be a working solution ...

**Comment by parafin** [comment]
Yeah, the fix is for upcoming DT release, and setting opencl_library is a functional workaround for the time being.

**Comment by parafin** [comment]
@MStraeten, can you test #6935?

**Comment by homer3018** [comment]
>ok, thanks. I close the pr. ...

@MStraeten funny that I don’t seem to have this `libcldcpuengine.dylib`...

**Comment by parafin** [comment]
It's probably possible to have another workaround - install XCode, which includes Big Sur SDK, in which, I think, there should be full OpenCL framework, and you then point opencl_library setting to it instead. It's just a thought, anyway this is already fixed in master.

**Comment by MStraeten** [comment]
i checked this, but this didn't help ... big sur sdk is also part of commandline tools.

**Comment by MStraeten** [comment]
> @homer3018: funny that I don’t seem to have this `libcldcpuengine.dylib`...

You’re right - the file isn't where you'd expect it to be, but it seems to be in the dyld cache file. it's just mentioned in the map file...

**Comment by Herve5** [comment]
> found a working solution - darktable-cltest builds the kernels:
> in dlopencl.c, adding libraries mentioned in /System/Library/dyld/dyld_shared_cache_x86_64.map in line 34:
>  (...)

Thank you!
Do you think this would work too with Darktable on Linux, where we are locked on the 5.8 kernel because the 5.9 doesn't activate OpenCL?

**Comment by parafin** [comment]
no

**Comment by ptilopteri** [comment]
perhaps you are not "locked" on the 5.8 kernel.  

I have a somewhat aged G04/NVIDIA GF106 [GeForce GTS 450] and
am using 5.9.8-2-default with " nvidia v: 390.138" on openSUSE Tumbleweed
and have OpenCL active.

I can share the driver(s) if you are able to use them.
http://wahoo.no-ip.org/~paka/
I can also obtain them for G05 series

**Comment by Herve5** [comment]
Thank you parafin, ptilopteri!
(I am really impressed by the reactivity here!)
Actually, NVidia went aware of the issue some weeks ago, and then published updated packages which deal with everything on 5.9, save OpenCL. 
Indeed I'm not sure it comes from the NVidia drivers now, but the situation is beyond my (poor) understanding capacity. 
I heard the kernel refuses to load something that hasn't the right status (open vs closed maybe) but this is the kind of detail really too difficult for me, average end-user :-(

**Comment by ptilopteri** [comment]
the nvidia install is simple 

darktable-cltest

0.051355 [opencl_init] opencl related configuration options:
0.051406 [opencl_init]
0.051413 [opencl_init] opencl: 1
0.051418 [opencl_init] opencl_scheduling_profile: 'default'
0.051423 [opencl_init] opencl_library: ''
0.051429 [opencl_init] opencl_memory_requirement: 768
0.051435 [opencl_init] opencl_memory_headroom: 400
0.051440 [opencl_init] opencl_device_priority: '*/!0,*/*/*'
0.051447 [opencl_init] opencl_mandatory_timeout: 200
0.051455 [opencl_init] opencl_size_roundup: 16
0.051461 [opencl_init] opencl_async_pixelpipe: 0
0.051465 [opencl_init] opencl_synch_cache: active module
0.051470 [opencl_init] opencl_number_event_handles: 25
0.051476 [opencl_init] opencl_micro_nap: 1000
0.051481 [opencl_init] opencl_use_pinned_memory: 0
0.051486 [opencl_init] opencl_use_cpu_devices: 0
0.051490 [opencl_init] opencl_avoid_atomics: 0
0.051494 [opencl_init]
0.051785 [opencl_init] found opencl runtime library 'libOpenCL'
0.051828 [opencl_init] opencl library 'libOpenCL' found on your system and loaded
0.063958 [opencl_init] found 1 platform
0.063989 [opencl_init] found 1 device
0.064157 [opencl_init] device 0 `GeForce GTS 450' has sm_20 support.
0.064230 [opencl_init] device 0 `GeForce GTS 450' supports image sizes of 16384 x 16384
0.064239 [opencl_init] device 0 `GeForce GTS 450' allows GPU memory allocations of up to 239MB
[opencl_init] device 0: GeForce GTS 450
     GLOBAL_MEM_SIZE:          960MB
     MAX_WORK_GROUP_SIZE:      1024
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 64 ]
     DRIVER_VERSION:           390.138
     DEVICE_VERSION:           OpenCL 1.1 CUDA
0.102445 [opencl_init] options for OpenCL compiler: -w  -DNVIDIA_SM_20=1 -DNVIDIA=1 -I"/data/dt-build/darktable_repos/share/darktable/kernels"
0.102597 [opencl_init] compiling program `demosaic_ppg.cl' ..
0.103022 [opencl_load_program] loaded cached binary program from file '/home/paka/.cache/darktable/cached_kernels_for_GeForceGTS450_390138/demosaic_ppg.cl.bin' MD5: 'c83455d7494e9b4e552dc0310cac3691'
0.103035 [opencl_load_program] successfully loaded program from '/data/dt-build/darktable_repos/share/darktable/kernels/demosaic_ppg.cl' MD5: 'c83455d7494e9b4e552dc0310cac3691'
0.106326 [opencl_build_program] successfully built program
0.106346 [opencl_build_program] BUILD STATUS: 0
0.106351 BUILD LOG:
0.106354

**Comment by Herve5** [comment]
but my trouble is, after
`0.072168 [opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded`
contrary to kernel 5.8 that works, when on kernels 5.9 I get
```
2.998737 [opencl_init] could not get platforms: -1001
2.998750 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
```

**Comment by Spectre5** [comment]
Looks like we've hijacked this thread a little bit (talking Linux now instead of OS X), but I get the same output as @Herve5 using Ubuntu 20.04.  DT shows that opencl is not available and running `darktable-cltest` gives me the -1001 error as well:

```
$ darktable-cltest
0.034188 [opencl_init] opencl related configuration options:
0.034204 [opencl_init] 
0.034208 [opencl_init] opencl: 1
0.034211 [opencl_init] opencl_scheduling_profile: 'very fast GPU'
0.034214 [opencl_init] opencl_library: ''
0.034217 [opencl_init] opencl_memory_requirement: 768
0.034221 [opencl_init] opencl_memory_headroom: 400
0.034224 [opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
0.034228 [opencl_init] opencl_mandatory_timeout: 200
0.034231 [opencl_init] opencl_size_roundup: 16
0.034234 [opencl_init] opencl_async_pixelpipe: 0
0.034237 [opencl_init] opencl_synch_cache: active module
0.034240 [opencl_init] opencl_number_event_handles: 25
0.034245 [opencl_init] opencl_micro_nap: 1000
0.034248 [opencl_init] opencl_use_pinned_memory: 0
0.034250 [opencl_init] opencl_use_cpu_devices: 0
0.034253 [opencl_init] opencl_avoid_atomics: 0
0.034256 [opencl_init] 
0.034422 [opencl_init] could not find opencl runtime library 'libOpenCL'
0.034475 [opencl_init] could not find opencl runtime library 'libOpenCL.so'
0.034611 [opencl_init] found opencl runtime library 'libOpenCL.so.1'
0.034630 [opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
0.059389 [opencl_init] could not get platforms: -1001
0.059409 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.059415 [opencl_init] initial status of opencl enabled flag is OFF.
```

**Comment by matt-maguire** [comment]
You need to update your video card drivers to ones compatible with linux 5.9. (eg. if you use nvidia GPU, you may need driver 455.45.01).

**Comment by Spectre5** [comment]
Awesome, that worked, thanks!  I was on 450 before, now 455 works with opencl.
