### ISSUE TITLE
Add rating to collect images filter options

### ISSUE THREAD

**Issue by stakaz** [darktable-org/darktable#6919]
**Is your feature request related to a problem? Please describe.**

Yes, there is no possibility to add `rating` to the search criteria in the `collect images` module.

**Describe the solution you'd like**

It would be very helpful to have the rating as one option to narrow down the search.
By this I mean, independently of the quick search filter in the top panel. 
As one can save the searches in the `collect images`, it then would be possible to integrate the rating in such saves.
E.g. I would like to have a search on rating and file type to delete RAW files of images with ratings below 4.

**Alternatives**

I can always do a combination of collect images and quick filter but this needs more attention each time I want to use it.

**Comment by alxgoldstn** [comment]
Very confusing that DT doesn't have this. Can we add this please?
