### ISSUE TITLE
Export followed by cancelling followed by export does not start export immediately.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6923]
I selected 17 images for export.

1 got exported and second was being exported.
Realized I had incorrectly turned "allow upscaling" and "high quality resampling" to yes.
Turned the 2 setting to no.
Used the cross to cancel the export.

The images were still selected so I did the ctrl+e to export.

The label at the bottom left that shows exporting status, just said exporting instead of the "exporting x/y to file disk".

After some time it did start exporting. 
What I feel is happening the cancelling of export is not immediate and there is some clean up going on before it can export again.

This can be misleading where the user expects the export to start immediately. 
I tried the export various times and cancelling out as I did not see anything happening. One time I waited long enough to let the export kick in.

Can the cancel followed by export be made user friendly indicating to the use export will begin shortly or something to that nature. 
Or when the cancelling is in progress, display cancel in progress in the export label and a new export label with the export progress.

**Comment by Nilvus** [comment]
@chhil: could you test again with darktable 3.6.0.1 released few days ago? Since 3.2.1 a lot of bug had been fixed. Maybe yours is fixed. Please report here if 3.6.0.1 fixed your issue or not. If your issue is fixed, think about closing this issue. Thanks.
