### ISSUE TITLE
modules on/off not respected when module is on and expanded. Clicking on/off collapses module instead of switching it off. 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6924]
3.3.0+1613~gc8f2d6cd9

Pasted history from image1 to kosher image2.

Realized the crop needed to be fixed in image2.

Clicked the enabled crop module to expand it.

Then without changing the crop clicked the module on/off to turn it off (the mouse was specifically on the in/off and it was highlighted), but it treats the click as module collapse.

**Comment by chhil** [comment]
The module on/off selected to turn off, but it just collapses it.

![image](https://user-images.githubusercontent.com/1119439/99180058-1dbdb580-2749-11eb-9b27-7b0054ea0fe3.png)

**Comment by elstoc** [comment]
Do you have the "expand the module when it is activated, and collapse it when disabled" preference checked?

**Comment by chhil** [comment]
> Do you have the "expand the module when it is activated, and collapse it when disabled" preference checked?

Yes

**Comment by chhil** [comment]
When the preference is turned off, the module off works but as expected does not collapse.
