### ISSUE TITLE
White balance: Wrong output vs settings combo + green image using as shot button (legacy)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#6926]
**Describe the bug**
When I open a fresh image in darkroom and look at the white balance module I see that the *white balance settings* are set to *user modified*, clicking on *as shot* icon makes the image green.

This is done while *chromatic adaption* set to *legacy*, on a fresh image and no further editing/resetting done.

**To Reproduce**
1. Set *auto apply chromatic adaption defaults* to *legacy*
2. Open an image in darkroom
3. Expand the white balance module
4. Default is set to *user modified* -> which is incorrect
5. click on *as shot* -> Image turns green

**Expected behaviour**
1. The modules shows that the camera value is taken as default
2. Buttons react "as expected" when clicking them

**Screenshots**
When freshly opened:
![screen1](https://user-images.githubusercontent.com/56407344/99183685-8bf87d00-2735-11eb-804f-39d2759f0f13.png)

After clicking on *as shot*:
![screen2](https://user-images.githubusercontent.com/56407344/99183689-96b31200-2735-11eb-8ddf-ef93153c5969.png)

**Platform**
* darktable        : 3.3.0+1617 ge1d2411d8
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.6)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 / clang 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by rabauke** [comment]
Just observed the same issue. Additional information: 

- Click on _as shot_  sets all RGB coefficients to 1.
- Default values that are set when the white balance module is opened/activated for the 1st time depend on the image (possibly on the camera white balance settings).

**Comment by AxelG-DE** [comment]
I confirm the issue.
I will bisect

**Comment by TurboGit** [comment]
Should be fixed in master.

**Comment by jade-nl** [comment]
It is fixed. Thanks.
