### ISSUE TITLE
image colorspace problem in master

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6938]
openSUSE Tumbleweed 20201114
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable 3.3.0+1639~ga70022f88
OpenCL on
i7 12-core 36GB
kernel 5.9.1-2-default

when opening jpg files from samsung galaxy 10+ from
control line:
  darktable --library :memory: /home/paka/Pictures/2020/S10+PhoneCamera/

get follwoing as thumbnails are displayed:

[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 0 to 2
[_transform_matrix] invalid conversion from 0 to 2

**Comment by TurboGit** [comment]
Can you double check that there is no white-balance module applied?

**Comment by ptilopteri** [comment]
fresh single jpg imported provides:

[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 0 to 2
[_transform_matrix] invalid conversion from 0 to 2
[dt_ioppr_transform_image_colorspace] invalid conversion from 0 to 2
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 0 to 2
[dt_ioppr_transform_image_colorspace] invalid conversion from 0 to 2


attached xmp file

[IMG_20201115_172246.jpg.xmp.txt]
(https://github.com/darktable-org/darktable/files/5546708/IMG_20201115_172246.jpg.xmp.txt)

appears no white-balance auto applied, and I did not apply one.
tks

**Comment by aurelienpierre** [comment]
fixed by #7029 it seems

**Comment by ptilopteri** [comment]
tks, I no longer see the notices
