### ISSUE TITLE
Export of images has grey square blotches.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6939]
Opencl off.
3.3.0+1639~ga70022f88 (WSL linux)

Export settings
![image](https://user-images.githubusercontent.com/1119439/99209640-a12ee380-27e9-11eb-9dad-211a56ab0935.png)

See the top left , its speculated (grey squares). Also see the region 1/3 from left along the border of the dark to light transition.This is the jpeg exported on linux
![image](https://user-images.githubusercontent.com/1119439/99209680-b9066780-27e9-11eb-83d9-c4b7d0baa84c.png)

This is the exported image on windows. Its less speculated.
![image](https://user-images.githubusercontent.com/1119439/99210016-a8a2bc80-27ea-11eb-919e-8a6b17d2237b.png)

This is what the image looks like in darktable view.
![image](https://user-images.githubusercontent.com/1119439/99209828-1dc1c200-27ea-11eb-8f1c-88f34d1a91d3.png)

**Comment by chhil** [comment]
xmp, raw and exported jpegs provided [here](https://www.dropbox.com/sh/rhyqgsp42p3hec7/AAC-hVNjB95KdWolb5EcN5NHa?dl=0)

**Comment by aurelienpierre** [comment]
What you have here are hot pixels. Enabling the hot pixels module reports 254 hot pixels with default threshold. Adjust the threshold until grey squares disappear.
