### ISSUE TITLE
Copying just crop to an image through history clears (grey square) the image

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6940]
3.3.0-1639 
Opencl off.

Copy history set to append mode.
Copy just a custom 16:9 crop from one image1  using ctrl+shift+c (selecting only crop) to another not edited image2.

Image blanks out, sometimes its grey somtimes its black.

![image](https://user-images.githubusercontent.com/1119439/99231630-e3224e80-2816-11eb-99af-c9e5c41c278c.png)

If I click on history just below crop the image is displayed correctly.

![image](https://user-images.githubusercontent.com/1119439/99231705-f9c8a580-2816-11eb-8e23-444192142b99.png)

**Comment by chhil** [comment]
Same version on windows it doesn't happen.

After playing around a lot with this style of copying got a segmentation fault.
The backtrace file created with 0 size.
Deleted the lock files and starting DT

Now scrolling up and down to extremes in lightroom does a segmentation fault.

**Comment by chhil** [comment]
Removed the .config folder started fresh.

Imported folder with existing edited images with their xmps.

Scrolling up and down , changing the number of images  that can be displayed in a row while images are being drawn eventually seg faults in darkroom view.

Backtrace file generated but 0 size.

It seems be related to drawing the images in the main view while scroll changes or number of images in a row changes.

**Comment by johnny-bit** [comment]
> Copy just a custom 16:9 crop from one image1 using ctrl+shift+c (selecting only crop) to another **not edited** image2.

Fixed in #7511

the not edited part was crucial here. Finally fixed in #7511 by @TurboGit :D 

I think this can be safely closed unless you manage to reproduce issue with most recent master :)
