### ISSUE TITLE
Duplicate images displayed incorrectly from the cache in lighttable

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6946]
3.3.0+1652~gf4d6d9920 (wsl Ubuntu 20)

I clear the config folder, start afresh.
Reimport some folders that I am working on.

Occasionally I will see images grouped together (duplicates created previously) but are no way the same as in this case.
![image](https://user-images.githubusercontent.com/1119439/99269848-76c24200-284c-11eb-8dd6-59fc26d923fb.png)
The second image (the bed one) here is not even imported, so it's being read from the cache and incorrectly being paired with the girl going down the steps..
Now when I double click the incorrect image it gets fixed.

![image](https://user-images.githubusercontent.com/1119439/99271737-fa7c2e80-284c-11eb-99a1-ef2987a870ff.png)

This has been happening for some time now (on windows too), just decided to open an issue.

**Comment by wpferguson** [comment]
Are you running more than one version of darktable and not specifying separate cache directories?  I run multiple versions of darktable and didn't specify separate cache directories when I first did it, and had similar problems.

**Comment by chhil** [comment]
I run multiple versions, one on windows and one on linux on the same machine but the config folders are different.

**Comment by wpferguson** [comment]
I run multiple versions on linux, so I specify a separate cachedir like so:
`/opt/darktable33/bin/darktable --cachedir $HOME/.cache/darktable33 --configdir $HOME/.config/darktable33 $@`
to make sure they don't interfere with each other.

**Comment by TurboGit** [comment]
If you use the same thumb cache that's expected.

**Comment by chhil** [comment]
I assume these are the caches we are talking about.

![image](https://user-images.githubusercontent.com/1119439/99296648-198ab880-286d-11eb-970a-e8db30aca30d.png)

My caches are in unique paths.
Left one is for DT running on wsl ubuntu and right one is the windows one.
