### ISSUE TITLE
Seg fault current master

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#6950]
**Describe the bug**

on fresh config, just imported few images.

```
Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
0x00007fffb19dc206 in _lib_modulegroups_update_iop_visibility (
    self=0x5555570cb470) at /home/ph/git/dt/src/libs/modulegroups.c:588
588	          gtk_widget_set_visible(d->deprecated, !strcmp(gr->name, _("deprecated")));
```

**Platform (please complete the following information):**
 - Darktable Version: 2.5.0+7985~gc8f2d6cd9
 - OS: Debian bullseye
 - OpenCL : no
 - AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx × 4

**Comment by TurboGit** [comment]
Fixed yesterday ! Please update your sources Philippe.

**Comment by phweyland** [comment]
Sorry for the noise... :(
