### ISSUE TITLE
DT crashes if we assing and use shortcut for "modules history stack discard"

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#6952]
**Describe the bug**

If we are to assign a shortcut for modules - history stack - discard - when we are to use it - DT will give the confirmation message if we want to discard history for 1 image - once I click yes - the window freezes and DT crashes.

**To Reproduce**

1. Go to assign shortcuts
2. Assign a shortcut under modules - history stack - discard (I tied ctrl shift alt back space or ctrl shift alt |) each time DT froze and crash

**Expected behavior**

after the confirmation window - DT should continue working

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS:  Linux - PopOS 20.04
 -  yes
 -  Nvidia RTX 2070

**Additional context**

[darktable_bt_9KHNU0.txt](https://github.com/darktable-org/darktable/files/5549493/darktable_bt_9KHNU0.txt)

**Comment by aurelienpierre** [comment]
please retry with current master

**Comment by johnny-bit** [comment]
Fixed by @elstoc in #6022 - cannot replicate issue with discard history shortcut on master post that PR merge. issue is replicable on 3.2.1. Release 3.4 won't have this problem.
