### ISSUE TITLE
Build warning: "Could not find a configuration file for package "LLVM" that is compatible   with requested version "11"."

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6955]
Linux build : Should I be concerned?

```

CMake Warning at CMakeLists.txt:303 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11".

  The following configuration files were considered but not accepted:

    /usr/lib/llvm-10/cmake/LLVMConfig.cmake, version: 10.0.0
    /lib/llvm-10/cmake/LLVMConfig.cmake, version: 10.0.0

Call Stack (most recent call first):
  CMakeLists.txt:311 (find_llvm)


-- Found LLVM 10.0.0
-- Found clang compiler - /usr/bin/clang-10
-- Found clang opencl-c.h header in /usr/lib/llvm-10/lib/clang/10.0.0/include
-- Will be able to test-compile OpenCL programs. Nice.
-- Found jsonschema
-- Found xsltproc
-- Found xmllint
-- Found exiftool
-- All external programs found
-- Found msgfmt to convert .po file. Translation enabled
-- The following OPTIONAL packages have been found:

 * LLVM (required version >= 10)
 * Gettext
```

https://github.com/darktable-org/darktable/blob/master/CMakeLists.txt#L301-L308

I am not a Linux person, had set up the environment using the instructions for ubuntu from the darktable resources online.

To get rid of the warning, I went to https://apt.llvm.org/  and ran the following with `sudo`.

`bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"`

This got rid of the warning.

```
-- The following OPTIONAL packages have been found:

 * LLVM (required version >= 11)
 * Gettext
 * XMLLINT, command line XML tool, <http://xmlsoft.org/>
   Used for validation of data/cameras.xml
```

Assuming this is the correct way to do it, if any documentation needs to be updated please do so.

**Comment by parafin** [comment]
LLVM is not needed for the build (or any feature), it's a tool for developers. I'm not sure how it works, but you can just ignore these warnings. It's definitely a very bad idea to suggest users to run scripts downloaded from the Internet, especially with sudo.
