### ISSUE TITLE
Lua-5.4 not detected

### ISSUE THREAD

**Issue by meplan** [darktable-org/darktable#6958]
compilation script complains about Lua53 (required version >= 5.3) not found whereas Lua-5.4 is installed

**Describe the bug**

Darktable 3.3.0+16880 using build.sh script on Fedora 33.
The build.sh script says that Lua53 is not found and require lua version > 5.3 but I have lua-5.4.1-1.fc33.x86_64 (+libs and devel) installed. Did I miss something? 
Thanks
Olivier

**Comment by parafin** [comment]
lua 5.3 is required. Enable DONT_USE_INTERNAL_LUA=OFF to use bundled with dt version. Where does it say for you that >=5.3 is required? Maybe you misread the messages?

**Comment by meplan** [comment]
ok thank you for your answer ; the message is really : 
-- The following OPTIONAL packages have not been found:
 * Lua53 (required version >= 5.3)

**Comment by parafin** [comment]
Also see #5906 for lua 5.4 support progress.

**Comment by parafin** [comment]
> ok thank you for your answer ; the message is really :
> -- The following OPTIONAL packages have not been found:
> 
> * Lua53 (required version >= 5.3)

Yeah, it's automatically generated message, I've taken a look and there is no straightforward way for it to be explicit that 5.4 is too new. But the fact that package is called Lua53 should be a hint;)

Anyway, closing, since nothing to be done here.
