### ISSUE TITLE
Tagging in Darkroom not allowed if tag module in lighttable is in treeview

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6960]
Current master.
3.3.0+1680~g838418e38

Trying to use  **`ctrl+t`**  to tag an image in `darkroom` view.

![image](https://user-images.githubusercontent.com/1119439/99368468-2e089880-28e1-11eb-82a7-44b28250a40d.png)

Why the does the list view v tree view matter?

**Comment by chhil** [comment]
There is a secondary issue.

Once you change to list view in lightable tagging.

Do a ctrl+t in darkroom to pop up the text input area, you click lightroom. The tag entry box is still on the screen.

![image](https://user-images.githubusercontent.com/1119439/99369901-0286ad80-28e3-11eb-8937-5fe61ee61b4c.png)

**Comment by phweyland** [comment]
> Why the does the list view v tree view matter?

in case of ctrl-t (lighttable as well) completion doesn't work on when on treeview.

**Comment by phweyland** [comment]
> > Why the does the list view v tree view matter?
> 
> in case of ctrl-t (lighttable as well) completion doesn't work when on treeview.

When I've introduced the tree view, I've let the completion as it was. There should be a way to make it work in that case. I'll look at it.

**Comment by phweyland** [comment]
I confirm completion doesn't work with tree view (as is):

![image](https://user-images.githubusercontent.com/23012047/99540217-01f72100-298e-11eb-8995-003b7a032c43.png)

If I'm not mistaken there is no simple solution.
Completion shows (as above) a model filter inherited from current treeview. If it is list store it shows a list, if it is a tree store it shows a tree. The tree display is ok when the user wants to filter the tree view of his tags. But it's not good as a completion feature.


> Once you change to list view in lightable tagging.
> 
> Do a ctrl+t in darkroom to pop up the text input area, you click lightroom. The tag entry box is still on the screen.

I cannot reproduce this (neither darkroom > lighttable nor lighttable -> darkroom).

I'm afraid that's all I can do for the time being ...

**Comment by chhil** [comment]
When I do a ctrl+t , in darkroom, I dont see the tree structure you see.

![image](https://user-images.githubusercontent.com/1119439/99609444-f0695400-2a35-11eb-9822-6ea4a1ad3e27.png)
Even when I type a letter, the completion kicks in.
![image](https://user-images.githubusercontent.com/1119439/99609508-0d058c00-2a36-11eb-8d23-aa8bf8e1bd2e.png)

Disable completion checkbox being unchecked in preferences
![image](https://user-images.githubusercontent.com/1119439/99609615-48a05600-2a36-11eb-9c1c-7e3bca8c3adf.png)

When I go to lightable view 
![image](https://user-images.githubusercontent.com/1119439/99609742-7f766c00-2a36-11eb-9056-6118bd522b42.png)


In both lightable and darkroom the check/uncheck does not change the way the way tag entry area looks on ctrl+t (have restarted dt after changing check box).
Running current master.

**Comment by phweyland** [comment]
> When I do a ctrl+t , in darkroom, I dont see the tree structure you see.

Correct, instead you get the message to switch to list view.
In list view you get completion proposal in list view. The one I've shown is what you would get if we let ctrl-t work with tree view.



> Disable completion checkbox being unchecked in preferences

By default, completion proposal list is enable for tagging entry. For a user who attaches tags thanks to that list that's perfect.
But entry can also be used to filter your list or tree of tags. In that case the proposal list covers the tagging module and doesn't let you see it. That's the purpose of that configuration flag, removing the proposal list and let you see the tag dictionary.
It has no effect on ctrl-t feature.

**Comment by chhil** [comment]
My only gripe is that a view (MVC) and the model are not independent.

**Comment by phweyland** [comment]
> My only gripe is that a view (MVC) and the model are not independent.

What do you suggest then ?

**Comment by chhil** [comment]
I don't know the internals, but the data probably exists in some data structure and used to populate the list and tree views, maybe use that same data structure to assist creation of new tags or search existing ones to display them and populate the main storage where all tags are stored.

**Comment by phweyland** [comment]
There is a way but I don't find great. Copy the tree store to a list store and  base the completion on it.

**Comment by chhil** [comment]
I leave the implementation to your expertise to make the best decision.
