### ISSUE TITLE
dt crashing when attempting to go to darkroom

### ISSUE THREAD

**Issue by hossamelgabarty** [darktable-org/darktable#6966]
**Describe the bug**
darktable (compiled from master) is crashing once I try to open any photo in the darkroom.
Cleaning or uninstalling and starting clean does not help.

**To Reproduce**
1. Open darktable
2. Select a photo
3. double click or press d

**Platform (please complete the following information):**
 - Darktable Version: compiled from 838418e38..1e01289b8  master
 - OS: Opensuse Tumbleweed
 - no opencl
- backtrace attached
[darktable_bt_UV2KU0.txt](https://github.com/darktable-org/darktable/files/5554541/darktable_bt_UV2KU0.txt)

Output to console:
[defaults] found a 64-bit system with 7822612 kb ram and 4 cores (0 atom based)
[defaults] setting high quality defaults
[imageio_load_module] `/usr/local/lib64/darktable/plugins/imageio/storage/libfacebook.so' is compiled for another version of dt (module 20 (opt) != dt 22 (opt)) !
[imageio_load_module] failed to open storage `facebook': (null)
[imageio_load_module] `/usr/local/lib64/darktable/plugins/imageio/storage/libgooglephoto.so' is compiled for another version of dt (module 20 (opt) != dt 22 (opt)) !
[imageio_load_module] failed to open storage `googlephoto': (null)
[imageio_load_module] `/usr/local/lib64/darktable/plugins/imageio/storage/libflickr.so' is compiled for another version of dt (module 20 (opt) != dt 22 (opt)) !
[imageio_load_module] failed to open storage `flickr': (null)

(darktable:2440): GdkPixbuf-CRITICAL **: 16:39:35.983: gdk_pixbuf_new_from_data: assertion 'data != NULL' failed

(darktable:2440): GdkPixbuf-CRITICAL **: 16:39:35.983: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(darktable:2440): GdkPixbuf-CRITICAL **: 16:39:35.984: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed
backtrace written to /tmp/darktable_bt_UV2KU0.txt
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...

**Comment by TurboGit** [comment]
Please clean-up you built and install directory you are having long removed plug-ins (facebook here which seems crashing your dt).
