### ISSUE TITLE
Crash: divide by zero while selecting deleted photos

### ISSUE THREAD

**Issue by breischl** [darktable-org/darktable#6969]
**Describe the bug**
I managed to crash darktable just now. I had deleted several images from the filesystem, but they were still showing in the lighttable view, with the "file missing" preview image that kinda looks like a space invader. So I was selecting all of them (using ctrl+left mouse click), with the intention to delete them. After perhaps 5 or so I got the crash. However I have not been able to repro the crash. I reopened darktable and was able to select and delete all 13 images with no problems.

**To Reproduce**
Unable to repro locally

**Expected behavior**
Don't crash

**Screenshots**

**Platform (please complete the following information):**
Darktable v3.2.1 on Windows 10 Home 64-bit, OS build 19041.630.
Files are on a removable USB drive, if that matters.

[darktable_bt_RDAAU0.txt](https://github.com/darktable-org/darktable/files/5560845/darktable_bt_RDAAU0.txt)

**Comment by TurboGit** [comment]
No reproducer, the Windows backtrace is useless there is nothing more we can do. Closing.
