### ISSUE TITLE
export button is disable

### ISSUE THREAD

**Issue by ChrisLejeune44** [darktable-org/darktable#6978]
I open Darktable.
I go to the darkroom.
I make some actions on my image.
I come back to the lighttable.
I can't export the image, the button is disable.
When i restart Darktable the export button is enable.

The problem appears since my windows is updated.
The version of windows 19041.630

**Comment by TurboGit** [comment]
Since I do not read crystal ball, can you tell me about the dt version ?

**Comment by TurboGit** [comment]
> The problem appears since my windows is updated.

So maybe report to Microsoft :)

**Comment by ChrisLejeune44** [comment]
It's the last version of Darktable 3.2.1

**Comment by ChrisLejeune44** [comment]
I can try to report to Microsoft :-))), but i have the same problem with others buttons of Darktable. The contextual menu of "ordre des modules" and "plus de modules" in the darkroom is also disable.

**Comment by johnny-bit** [comment]
Make sure image is select. It does button enable.

**Comment by aurelienpierre** [comment]
The export button is greyed out when no image is selected, to notify user that clicking it would have no effect.
