### ISSUE TITLE
Copying 16:9  crop from landscape image to portrait image loses it 16:9 aspect ration

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6979]
Current master 3.3.0+1698~g64cb5814e

Cropping 16:9 on landscape image.
![image](https://user-images.githubusercontent.com/1119439/99614827-4cd17100-2a40-11eb-8001-1d5a85931f47.png)

Copying history (in this case I am only selecting crop to be copied as an example).

Going to apply copied crop on this portrait image.
![image](https://user-images.githubusercontent.com/1119439/99614929-886c3b00-2a40-11eb-949c-ba4ad1e8d00f.png)

After pasting the copied history (only crop)
Pasting crop on a portrait image 

![image](https://user-images.githubusercontent.com/1119439/99615036-b9e50680-2a40-11eb-8fde-64e7a575da43.png)

Above you will see crop is showing 16.9. The module was already in the open state.
Also, it does not look like 16:9.

Now reselect 16:9 and the crop rearrange itself as the pasted one was not correct.
![image](https://user-images.githubusercontent.com/1119439/99615138-e3059700-2a40-11eb-85da-25123bd80a1a.png)

So, when pasting, should the crop readjust to 16:9 to fit the image appropriately?

**Comment by Nilvus** [comment]
Could you test that again in actual master and confirm if you still reproduce or not? If not, of course, consider so closing this issue. Thanks.

**Comment by johnny-bit** [comment]
Well, I can reproduce on `3.7.0+1~g05bdc45ac`:
1. just need to have one landscape and one portrait image. Use crop+rotate module for that (probably will affect crop too but haven't tested it)
2. Copy 16:9 crop from landscape to portrait and you'll se almost square crop.
3. open c&r module - it'll rearrange crop to be portrait 16:9 crop.

I'd say this is someththing to think about in c&r module revision for @AlicVB :)
