### ISSUE TITLE
White balance issue - Sony ILCE-6600

### ISSUE THREAD

**Issue by PimPolacko** [darktable-org/darktable#6983]
[darktable-whitebalance-20201119.tar.gz](https://github.com/darktable-org/darktable/files/5567410/darktable-whitebalance-20201119.tar.gz)

As stated in the wiki for the white balance presets, you can find the extracted white balance data in the properly finetuned manner for the Sony A6600 (ILCE-6600) attached.

**Comment by johnny-bit** [comment]
Thanks! It seems that sony ilce 6600 has similar half-step finetuning as nikon does so I'll have to add it to `extract_wb.py` :)

**Comment by PimPolacko** [comment]
Happy I could help. Thanks for your work

**Comment by chhil** [comment]
Based on a user in the DT facebook page, having whitebalance issue, I imported a a6600 raw file from the web and got the following in the shell that started DT (master).

```
[color calibration] white balance error
[white balance] double application of white balance
```
