### ISSUE TITLE
seg fault in latest DT build

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#6984]
Cannot start DT at all.

Latest master git.
[darktable_bt_VSU6T0.txt](https://github.com/darktable-org/darktable/files/5567785/darktable_bt_VSU6T0.txt)

Backtrace included.

Operating System: Arch Linux
KDE Plasma Version: 5.20.3
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.1
Kernel Version: 5.9.9-arch1-1
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31,4 GiB of RAM
Graphics Processor: GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by TurboGit** [comment]
Sadly this backtrace is useless ! No enough information in it for have a slight idea of what could be wrong.

Is that reproducible ?

**Comment by maboleth** [comment]
I'm testing it further.

 When I delete dt in /.config there's no crash. Investigating .

**Comment by maboleth** [comment]
Got it.

The cause was dartablerc file. Probably some leftover from the previous version. Generating new settings file makes all ok.

**Comment by maboleth** [comment]
Ugh not the case.

As soon as I changed viewing mode to "zoomable" and closed DT, it crashed again.

I attached my dartablerc file that is crashing my DT.
[darktablerc.zip](https://github.com/darktable-org/darktable/files/5567940/darktablerc.zip)

**Comment by maboleth** [comment]
Apparently zoomable mode is crashing my DT.

1. Go to DT
2. Select zoomable mode
3. Close DT
4. Start DT - seg fault.

**Comment by TurboGit** [comment]
Oh yes, as soon as you select zoomable mode we got a crash ! Urgent to fix I suppose :)

**Comment by TurboGit** [comment]
Should be fixed. Thanks for reporting.

**Comment by maboleth** [comment]
Can confirm. 
No problem, keep up the good work. :)

Intentional or not, this also fixed #6815 bug for me! I tested it with my old darktablerc file and no lines anymore!

Thumbs up!

**Comment by TurboGit** [comment]
Good to hear that I killed two bugs in one shot :)
