### ISSUE TITLE
Make all presets consistent by fixing modulegroups order

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#6990]
Related to modulegroups presets. In all modules the preset order have been improved to first display users preset, then after a separator, display default darktable presets. This is not implemented in modulegroups presets. I consider that as an issue as it's not consistent.

@AlicVB: this one as a reminder to something to fix in modulegroups. I think this should be fixed for 3.4, for consistency reasons.

**Comment by AlicVB** [comment]
ok, I've just investigate a little bit and in fact, this new disposition has only be done for iop modules not libs...
I agree it should be the same for consistency reasons.

I'll have a look !

**Comment by AlicVB** [comment]
@Nilvus : see PR #7003 ... if you have time, can you give your opinion of the question there ? thanks in advance
