### ISSUE TITLE
darkroom: filmstrip single-click changes image

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7000]
It is no longer possible to easily select a range of images in the filmstrip in darkroom because single-click now seems to change the active image. It appears to have been like this for some time so I'm raising an issue here to ask whether it is intentional.

IMO double-click should change the active image and single click should be retained for selection purposes.

**Comment by AxelG-DE** [comment]
Like said on IRC, I actually like it this way, as it is easier to jump between pics than double click, but I accept aim for consistency of meaning of double and single click.

@AlicVB, was that you, who changed it or is my memory offset?

**Comment by elstoc** [comment]
Problem is when you want to select a range excluding the current image, for example if I want to copy the history stack of the current images to a range of others, without changing the image.

**Comment by Nilvus** [comment]
@elstoc: I had answered that a different way some time ago in issue #5495. You will see the answer from @AlicVB

**Comment by elstoc** [comment]
Ok thanks @Nilvus

**Comment by AxelG-DE** [comment]
Actually that addresses elstoc's comment well, but only partially his issue with single and double click, if I am not mistaken

**Comment by elstoc** [comment]
Well it says to use `Alt+click` to select an image without changing the image being processed and then you can use `Shift+click` and `Ctrl+click` to extend the selection. So it answers the question. I still don't think it seems right though.

**Comment by Nilvus** [comment]
I understand the choice but I also think it's not the best way, as I said on #5495 issue. Now, I have take the habit to work with that but I would not be against a more intuitive behavior.

**Comment by Nilvus** [comment]
@elstoc: I think this is totally related to your #6025 issue and maybe we could just keep #6025 open? Do you mind if we close this issue?

**Comment by elstoc** [comment]
No this is a different issue. The other is about how to identify which images are selected. This one is about the fact that selection works differently on the filmstrip to everywhere else (i.e. single click just selects in the lightroom whereas single click actually changes the image in darkroom). I'd prefer to keep them separate.
