### ISSUE TITLE
Raspberry Pi HQ Camera Noise Profile / White Balance Presets

### ISSUE THREAD

**Issue by dustinkerstein** [darktable-org/darktable#7006]
I just added a feature request to support the new Raspberry Pi HQ camera's RAW format - #6998, and have also taken the noise profile photos based on - https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable

Attached is the entire archive created by `darktable-gen-noiseprofile` and both the original hybrid JPEG/RAW and the DNG's used to create the archive can be found [here](https://www.dropbox.com/sh/abytlr1103gl1vs/AADbWS1IMt_GkSHNmrnCtkyda?dl=0).

The DNG's were created by [PyDNG](https://github.com/schoolpost/PyDNG). Let me know if it'd be better to wait for official support of the Pi's hybrid JPEG/RAW format before running the noise profile.

Note that ISO 800 on the Pi HQ seems to behave strangely. It's very close in gain to ISO 400 - so close that I had to use nearly the same shutter speed to match levels. So it's possible the ISO 800 example should be excluded from any official presets. I'll leave that up to you. Thanks!

[darktable-noiseprofile-20201121.tar.gz](https://github.com/darktable-org/darktable/files/5578110/darktable-noiseprofile-20201121.tar.gz)

**Comment by rawfiner** [comment]
Looks nice, thank you!
