### ISSUE TITLE
'working' message should give more detail

### ISSUE THREAD

**Issue by Xepo** [darktable-org/darktable#7011]
I turned on some very high denoise settings, forgot about it, then every operation (including zooming) on that image was very very slow.  It just said 'working' for a long time.  I thought the slowdown was related to moving my library to an external drive so spent a while trying to figure out what was happening to my network.

**Describe the solution you'd like**
The 'working' message should include what it's working on.  If the many second pause said 'working (denoise)' then I would've known exactly what the problem was.  Instead, I didn't find the problem until I ran with [-d perf].

**Alternatives**
I don't love the alternatives but just for completeness:
1. Some way of reviewing what took the most time in the recent processing
2. Maybe some special pop-up message on modules that are especially slow.
3. Always on -d perf?  maybe with some way to make it more discoverable.

**Comment by parafin** [comment]
Having module name in working message is useless - it will change too often to be readable and may even not be related to reality in case of OpenCL processing. Working in darkroom means processing pipe is running, maybe it can be changed to "processing..." or something.
Maybe adding a module that displays perf stats in the darkroom might be useful for debugging, though it should be hidden by default I guess.

**Comment by Xepo** [comment]
I agree that in lots of cases it’ll be useless. But when the ‘working’ is taking forever it seems like it’s be pretty useful. For example, last night perf debug showed that denoise module was taking 9 seconds.

Has a couple other minor advantages: 
1. It’ll make the user feel like progress is happening. 
2. It’ll teach the users that the modules they turn on has a speed effect on every operation they do (I wouldn’t have thought it’d have an effect on zooming, which is why I thought something weird may be going on)
—-
I don’t think switching to ‘processing’ would help much. Seems equivalent to ‘working’ to me.

**Comment by Nilvus** [comment]
Time taken by modules depends a lot on computer performance. I've had with my previous more than 6 years computer some seconds for many process. Since september and my new  computer with a powerful CPU and a powerful OpenCL GPU card and more memory, I rarely have more than 2 or 3 seconds for heavy and most of the times, it's less than a second. So adding the module on such powerful computer would be hard to see and read.
