### ISSUE TITLE
ChannelMixer visible on new imports

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7012]
DT : 3.3.0+1729~gc81f80f3d
Did something change where deprecated modules get displayed on new imports? 
e.g. channelmixer. Previous builds IRC, channel mixer would not get displayed.

![image](https://user-images.githubusercontent.com/1119439/99897187-721ee300-2cbd-11eb-95f1-d7bd9047e109.png)

![image](https://user-images.githubusercontent.com/1119439/99897169-48fe5280-2cbd-11eb-9d73-8906cb1aa51a.png)

**Comment by AlicVB** [comment]
ok, the key to reproduce is to click twice on a group icon to be in the "show all" state.
PR #7016 should fix it.
Thanks for the report
