### ISSUE TITLE
localcontrast listed twice in Manage Module Layouts

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#7014]
When managing module layouts and selecting "modules: default", the module "local contrast" is listed twice under the group "effects":

![m1](https://user-images.githubusercontent.com/12815378/99903720-1724c600-2c94-11eb-8f09-1e060c78f878.png)

However, only one instance (the second one) appears when in darkroom:

![m2](https://user-images.githubusercontent.com/12815378/99903743-5bb06180-2c94-11eb-8add-6a21f3fccf4c.png)

dt: 3.3.0~git1730.3ec69185a
os: Linux

**Comment by AlicVB** [comment]
good catch ! this should be fixed in PR #7016 
thanks for the report
