### ISSUE TITLE
[denoise (profiled)]  change default to wavelet-auto

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7018]
**Is your feature request related to a problem? Please describe.**

As discussed previously on IRC with @rawfiner:
Today the default of denoise (profiled) is non-local-means (NLM).

**Describe the solution you'd like**

The module denoise (profiled) has such brilliant results when using in wavelet-auto mode, that I would appreciate, this could be the new default.

**Alternatives**

quicky is an auto applied preset in "switch-off" state. Still there are scenarios, where the default remains the default (accels, midi-board, reset)

**Additional context**

**Comment by ptilopteri** [comment]
or that the "default" become configurable in some manner

**Comment by wpferguson** [comment]
> or that the "default" become configurable in some manner

I think denoising his highly subjective and there isn't a default that will satisfy everyone.  However, if the user could choose a preset or create settings that they like, then define a preset called "default" using those settings, the module could check for a preset called default when it's turned on and apply it if it exists.  If no preset named "default" exists, then we are right back to square one, what should the default be?

In my case, I use combination of styles and presets.  For low noise images, I use NLM presets.  For high noise I use styles with 2 instances of denoise(profiled).  The first instance is wavelets to do a chroma only (Y0 pulled to the bottom) and then a second instance denoise(profiled) to tame the luma noise down a little.

**Comment by matt-maguire** [comment]
I like @wpferguson ’s suggestion

**Comment by AxelG-DE** [comment]
> I like @wpferguson ’s suggestion

Me too, most flexible. That would be a cool amendment to all modules if they specially react on a preset called "default"

**Comment by todd-prior** [comment]
That's too funny I suggested this exact thing ie the default option maybe as long ago as 18 months....glad it's maybe now a good idea. I think its much easier than creating creating auto apply presets which was the suggested solution at the time...

**Comment by AxelG-DE** [comment]
> I think its much easier than creating creating auto apply presets which was the suggested solution at the time...

And this time again. Kinda...

**Comment by elstoc** [comment]
The easiest solution is to create a preset in disabled state. I do this for a bunch of modules already. Set up the module how you want, disable it and then create your preset as normal. The enabled/disabled status is saved as part of the preset. Then just enable it where you like in your workflow.

**Comment by todd-prior** [comment]
So Chris i went in made a change to local contrast..bilinear and some extreme settings. Saved it as auto apply but disabled. From your logic it should be auto applied to all images when I open them but disabled??  Then I can just enable if I like??

I may have not understood things but doing this does not work for me at this point...I may have missed something

**Comment by elstoc** [comment]
@todd-prior it should be applied to images when you discard history or (in master) Ctrl+click on the reset button

**Comment by todd-prior** [comment]
That got it...I just opened DT with memory and loaded random images in my downloads folder. Thought for a min it was because they were PNG files but it must be that DT had seen them, ie maybe there were xmp files there. I often drop an image or two in there to play with when trying to help somebody or to test something....compressing the history stack was the trick...any thought about making it a double click...I hate the control clicks have to stop and locate the key. I find this most annoying now with the color picker. To select a range you have to go find the control key...I thought the two droppers were quicker...or not sure why we don't maybe just use a single click on the image to set a point and click with a hold and drag when you create the point to make a range selection ....any way thanks for the tips

**Comment by elstoc** [comment]
> any thought about making it a double click

Generally double-clicks are a pain because you have to stop the event handler responding to the first click (i.e. before it knows if there even is a second click). Ctrl+click and Shift+click seem to be pretty standard in darktable (probably for that reason) so I think they will stay for now.

**Comment by todd-prior** [comment]
Ya this one is less of a pain…the color picker is the one that bugs me as a I have to look away to locate the key …it just seemed easier before….

**Comment by johnny-bit** [comment]
Can we revisit this for 3.8? disabled autopreset is fine but i'd still opt for changing default from NLM to wavelets auto. Just for the benefit of new users ;)

**Comment by elstoc** [comment]
Agreed. I've pretty much abandoned NLM now.

**Comment by johnny-bit** [comment]
@rawfiner - what do you think?

**Comment by rawfiner** [comment]
I don't mind. We can change to wavelets if you think it is better. I guess we should also rescale strength a bit in Y0U0V0 mode so that a strength of 1 gives a good result

**Comment by elstoc** [comment]
Yes or change the soft limits.

**Comment by rawfiner** [comment]
@elstoc my point was to have a strength high enough as default for Y0U0V0 mode, the sliders already have soft bounds

**Comment by elstoc** [comment]
I was saying that I often take the strength beyond the soft bounds (so it needs a few clicks and my keyboard to increase it) but I agree that the default is often too low.

**Comment by rawfiner** [comment]
Ok good point

**Comment by johnny-bit** [comment]
I'd still like to have default mode of denoise profiled changed to wavelets auto, please :)

**Comment by rawfiner** [comment]
I finally took the time to do this! Sorry for the long wait!
