### ISSUE TITLE
[FR] Update directory of files in database.

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#7019]
## Use case

2 use cases:

1. photos are stored on an external storage (NAS, harddrive). For some reason, at some point, the OS starts mounting them from another path (some distros mount from `/mnt`, some from `/media`, Ubuntu mounted in `/media` before 14.04 and changed to `/media/$USER` after 16.04).
2. users import their `~./config/darktable` from another computer. Then, all the pathes references might be wrong.

Both cases lead to orphaned image collections, not because the images are missing, but because their pathes have changed compared to what the database stored and their link are then broken.

## Fix

For now, this can be fixed from command line with SQLite:

```
$ sqlite3 ~/.config/darktable/library.db
$ update film_rolls set folder=replace( folder, '/OLD_PATH', '/NEW_PATH' ) where folder like "%OLD_PATH%";
```

## Proposal

Add a lighttable GUI button that:

1. allows to select a collection of images in lighttable and change their path in database,
2. allows to select all images in database that match a certain path, and change that path in bulk.

Yes there are Lua scripts to do that, but not everyone has Lua-enabled builds, especially not the Windows users IIRC.

**Comment by parafin** [comment]
You can do it via context menu in folders collect view.

**Comment by johnny-bit** [comment]
It looks like it would be beneficial to have similar context menu in film roll view of collect module. 
Also - the name "search filmroll" of context menu is a bit counterintuitive... but i wouldn't know how to express "set new filmroll path" in less words ;)

**Comment by wpferguson** [comment]
> Yes there are Lua scripts to do that, but not everyone has Lua-enabled builds, especially not the Windows users IIRC.

The windows builds have the internal lua interpreter enabled.

**Comment by vithom** [comment]
Hello,
I added the possibility to do it for filmrolls as well, in this pull request
https://github.com/darktable-org/darktable/pull/7182

I agree that "search filmroll" is not the best wording and I propose **"relocate filmroll"**. If you agree I can update the pull request with this wording.

**Comment by parafin** [comment]
relocate filmroll is IMHO worse, since it implies that files will be moved, not just DB entries updated. "look for files" or "search for directory" maybe?

**Comment by stacksmith** [comment]
This is a bigger issue, actually.  There is no integration with the current state of the filesystem.  While I emphatically agree with the team's decision to stay away from active file management and in general 'do no harm' principle, it is a huge problem.  When 'used as directed' with an outside file manager, any changes to the file structure, especially renaming and deletion of path components, movement of files, etc. pretty much breaks the system.  
Editing the database by hand with some scripts is really not a solution.  If we have a lighttable, we need to deal with this somehow.

**Otherwise, ditch the light table altogether, and work on individual files.**

**Comment by wpferguson** [comment]
> When 'used as directed' with an outside file manager

Where is this directed?  Using an outside file manager makes a mess of darktable's idea of where the images are.  You can add, copy, move and delete images all from within darktable, keeping the database in sync.  With the addition of a lua script you can move hierarchies of files around the file system, all while keeping the database in sync.  What you can't do is rename a path, at least until #7182.

**Comment by stacksmith** [comment]
https://www.darktable.org/about/faq/#faq-rename-files

**Comment by stacksmith** [comment]
Here is an idea: for each image and directory, keep its inode in the database.  If a databased picture-label cannot be opened, try to follow the inode to the new filename (if the name was changed).  If it was trashed, delete the database entry.

**Comment by wpferguson** [comment]
> Just make sure to first remove the files from darktable’s library (sic), then rename them and re-import them afterwards.

And actually, you can move them then when you start darktable it shows the skulls.  Select all the skulls and remove them, then go import the files from wherever you moved them to.  Keep the xmp files with them and your edits are applied when you import.

**Comment by wpferguson** [comment]
> Here is an idea: for each image and directory, keep its inode in the database.

Windows doesn't use inodes

**Comment by stacksmith** [comment]
Yet another reason to not use (and support) winders.
