### ISSUE TITLE
No more possible to save a removed name applied in a module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#7025]
**Describe the bug**

It's possible to rename a module, but it's no more possible to remove a name added. Or to be precise, remove text is not saved.

**To Reproduce**
1. Go to 'darkroom'
2. Click on 'multi-instance' button, for example in exposure module
3. Click on rename and then apply a name to it
4. Go back to lighttable and return then to darkroom
5. See that name is applied. All good for now
6. Click again on  'multi-instance' button, then to rename
7. Delete name applied and press enter
8. See name disappear.
9. Go back to lighttable and then return to darkroom
10. See the issue: name is still there.

**Expected behavior**

Deleted name saved.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1745~gb05f8555a
 - OS: Ubuntu 20.10 / Gnome 3.38

**Comment by Nilvus** [comment]
Just an add: instead of removing name, pressing space make the name disappear. Go back to lighttable then return to darkroom and by renaming, I see space pressed saved. That confirm that if a character is press, name is saved but completely empty one not.

**Comment by vithom** [comment]
Hello,

Problem is in `static gboolean _rename_module_key_press(...)` in *imageop.c:1008*

If *name* is empty, the `strcmp()` function returns 0, so it never gets into the if bloc where the `g_strlcpy()` backup the new string.
I will propose a code to correct that.

**Comment by vithom** [comment]
I also see one other thing:
If the name become very long when edited, the entry widget forces the side panel to extense, like this.
![Capture d’écran de 2020-11-23 23-59-57](https://user-images.githubusercontent.com/74423292/100025348-e4d8ad00-2de8-11eb-9054-92c39fe0c380.png)
Wouldn't it better if the entry have a fixed size and that the text inside scrolls to avoid an extension of the side panel ?

**Comment by Nilvus** [comment]
I hope that a user would rarely use a so long text, but yes, I agree that a fixed size with scrollbar if longer would be better.

I don't know if that could be done but the best would be to fix size dynamically to panel width and available space by respecting margins of course. Just be careful because we now have quite few possibilities to display right-side buttons (see darkroom tab and "show right-side buttons..." line.

**Comment by vithom** [comment]
@Nilvus: What do you think about my proposal ?

**Comment by vithom** [comment]
Ok thanks. I will fix the issue first and make some trials after.

**Comment by dterrahe** [comment]
> Wouldn't it better if the entry have a fixed size and that the text inside scrolls to avoid an extension of the side panel ?

This is only _while_ editing the name, so apart from it being not pretty if you enter such a big name (which is not a very good idea anyway, because it will get ellipsized as soon as you press enter) and you having to use the scroll bar at the bottom, it is not a really big problem. Trying to fix this means managing the minimum width of the entry based on the width of the panel (and the other components on that line) which adds quite a bit of complexity and risk of misbehavior. Which is why I decided not to fight gtk to get this perfect...

**Comment by Nilvus** [comment]
Thanks @dterrahe for that clarification. So, @vithom, no need to change that part (we don't need to add complexity for that), and just need to fix that issue. Thanks.

**Comment by vithom** [comment]
Ok, get it.
I will continue to fix that as soon as I can (next week I hope).
