### ISSUE TITLE
Exporting in lighttable culling view does not export all selected pictures

### ISSUE THREAD

**Issue by sylock** [darktable-org/darktable#7027]
I'm using Darktable 3.2.1-2 from Ubuntu.

### How to reproduce
* View Lighttable
* Select Culling view
* Select all pictures (ctrl-a)
* Click on the export module
* It exports only the 2 displayed pictures on the screen instead of all selected one

### Workaround
Switch to "File Manager" view, select all (ctrl-a), export.

**Comment by Nilvus** [comment]
Culling one is to display some images to compare. It is not done for that and having the possibility to only act on displayed images is wanted and a normal behavior. If you want to export more images than displayed, your workaround is just the way to go. It's not an issue. Remember too that you could also display more images in culling view. Option is in the bottom bar.

**Comment by AlicVB** [comment]
As @Nilvus said, it's not how culling, preview, darkroom, etc... works. You speak about export, but it's the same for rating, colorlabels, ... and that's done on purpose
