### ISSUE TITLE
Change default format for the group leader for RAW + JPEG groups on import or for a whole selection

### ISSUE THREAD

**Issue by stakaz** [darktable-org/darktable#7030]
**Is your feature request related to a problem? Please describe.**

I need a quick possibility to change the default group leader for RAW + JPEG groups to JPEG.
I am usually satisfied with the camera build-in JPEG output but would like to keep the RAW just for special cases and (possible) later use). 

**Describe the solution you'd like**

As such it would be great if one could just tell darktable which format it should prefer as leader on import. 

If this is to difficult, than a script or tool to do it automatically after choosing a collection would also be great.

**Alternatives**

Not really, manually setting group leader to JPEG on each image is not an option for a whole collection. 

**Additional context**

I have found this issue from 2004: https://github.com/darktable-org/darktable/pull/518

Maybe there is a script for it somewhere but I cannot find it?

**Comment by AlicVB** [comment]
AFAICT, there's everything in place in lua to do what you want... you "just" need to write the script
you may want to use :
- `darktable.gui.selection` to get selected images as a table of `dt_lua_image_t`
- `dt_lua_image_t.get_group_members` to get all members of a group
- `dt_lua_image_t.make_group_leader` to set the right image as group leader

**Comment by stakaz** [comment]
Thanks, yeah, I kind of thought that the functionality on the scripting site is there, but I wanted to know whether such a script already exists somewhere.

Probably at some point I would have the time to give it a try but right now I cannot jump on a new programming language.

**Comment by wpferguson** [comment]
The collection of contributed and official darktable lua scripts is at the [Lua Scripts Repository](https://github.com/darktable-org/lua-scripts) .  And no, there is not a script to do this.

**Comment by wpferguson** [comment]
Here's a lua script that does what you want.  If you have the [lua-scripts](https://github.com/darktable-org/lua-scripts) installed, you can drop it in the contrib directory and then enable using script_manager or require it in your luarc file.  If you don't have the lua-scripts installed, then comment out the lines that have du (2 and 7) in them. In lua a comment starts with --.

It creates a module in lighttable just under the selected images module.  You select the groups (just one image in the group), select what type of image is to be group leader, then click the execute button.  You'll probably have to expand and collapse the groups to get the new group leader to show up.

Test it out and let me know...

[change_group_leader.zip](https://github.com/darktable-org/darktable/files/5594445/change_group_leader.zip)

**Comment by janzhen** [comment]
@wpferguson Thank you for you script. I have the same issue, and google lead me here. Your script works well, and I just made a little change in line 44, because my Fujifilm X-T2 jpeg files have upper case suffix.

Why doesn't this script be put into [lua-scripts](https://github.com/darktable-org/lua-scripts)? It's so useful for people mostly use camera builtin jpeg.

```lua
-      if string.match(img.filename, "jpg$") then
+      if string.match(string.lower(img.filename), "jpg$") then
```

**Comment by mateimm** [comment]
My darktable is installed on Linux using Flatpak. How would I install it on a flatpak? Thanks.

**Comment by wpferguson** [comment]
Find where the flatpak installs your configuration directory.  In that
directory is a lua subdirectory.  You can add the script there.
