### ISSUE TITLE
Exported 32bit tif file does not look like the raw edit 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7031]
Tif Export settings (32 bits)
![image](https://user-images.githubusercontent.com/1119439/99945545-d06dc380-2d9a-11eb-82db-5911e2727ed2.png)

![image](https://user-images.githubusercontent.com/1119439/99945318-6ead5980-2d9a-11eb-9a12-401dd78529bf.png)

Tif export setting 16 bits matches the edit.
The 8 bit jpeg file export matches.

Using current master.

**Comment by kmilos** [comment]
I've seen this as well on Windows, it depends on the app you use to open the floating point TIFF.

**Comment by chhil** [comment]
Thank you. You are correct, it looks fine in gimp and importing it into darktable.

**Comment by kmilos** [comment]
It is as if some Windows apps decide to ignore the embedded profile and decide they're dealing with linear data always when they see floating point TIFF...
