### ISSUE TITLE
Gradient in drawn mask rotates backwards when image is flipped

### ISSUE THREAD

**Issue by paolodepetrillo** [darktable-org/darktable#7035]
**Describe the bug**
When an image is flipped on one axis, a gradient in a drawn mask rotates backwards.

**To Reproduce**
Open an image, enable crop and rotate module, set flip to either horizontal or vertical. (Problem does not occur with 'both')
In any other module, add a drawn mask and add a gradient.
Rotate the gradient by dragging the gray circle.
The gradient rotates by the angle that it was dragged, but in the opposite direction.

**Expected behavior**
Gradient rotates in the direction it was dragged.

**Platform (please complete the following information):**
Latest master branch 3.3.0+1764~g5eff51079 compiled from source on Arch Linux.

**Additional context**
The ellipse in a drawn mask can also be rotated but is not affected by this issue.

**Comment by paolodepetrillo** [comment]
This seems to fix the problem, copied a line from ellipse.c to gradient.c.

[issue_7035.diff.txt](https://github.com/darktable-org/darktable/files/5587034/issue_7035.diff.txt)

**Comment by TurboGit** [comment]
This fixes the issue indeed when the gradient is already in the picture. But when creating a new one, as soon as one right-click to place it in the image it gets rotated.

**Comment by TurboGit** [comment]
I had already fixed part of the issue, see 51f313bc94855895880b5dbdd3fc40cbe87ccc71. Would you mind to continue having a look at this to find a proper fix ?

**Comment by paolodepetrillo** [comment]
I see the problem with creation now, I hadn't realized it was possible to rotate the gradient while creating it. I will try to fix it.

**Comment by paolodepetrillo** [comment]
This is tricky.. the current, buggy behavior is that: if you pick two points A and B within the image content, and place a gradient by clicking at A and dragging to B, the gradient will have the same rotation angle and look the same relative to the image content, regardless of the flip and / or freehand rotation.
But I think the desired behavior is that if you place a gradient by clicking at a point within the preview window and dragging to another point within the preview window, the same gradient should always be created within the preview window regardless of the flip and / or freehand rotation. So if you place a gradient by clicking at the lower left corner and dragging up to the upper right corner, this should always result in a gradient where the upper left half of the image is in the mask and the lower right half of the image is not in the mask.

When the image is flipped on only one axis the 'handedness' of the coordinate system is changed. In this case the gradient is placed pointing 180 degrees away from the correct direction. By trial and error I came up with a simple workaround that checks if dt_dev_distort_backtransform is performing a flip by checking the angle between two vectors that should be 90 degrees apart, and flips the gradient angle 180 degrees if they are. I'm really not sure if this is the right way to fix the problem, if it really works in all cases or if there is a much simpler solution that I've missed. But as far as I can tell this does always work for any combination of flip and / or freehand rotation.
[issue_7035_1.diff.txt](https://github.com/darktable-org/darktable/files/5599583/issue_7035_1.diff.txt)

**Comment by TurboGit** [comment]
Looks good to me now! Thanks will merge. Can you give me you name + e-mail for the commit ? If you don't want I can understand but I'll be obliged to commit on my name a work that you've done. If you prefer just send me a git format-patch.

**Comment by paolodepetrillo** [comment]
Patch file is attached.

[0001-Fix-gradient-rotation-angle-when-image-is-flipped.patch.txt](https://github.com/darktable-org/darktable/files/5603906/0001-Fix-gradient-rotation-angle-when-image-is-flipped.patch.txt)

**Comment by TurboGit** [comment]
Thanks, merged.
