### ISSUE TITLE
Wrongfully disabling always-on modules via shortcuts and possibly more issues

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#7037]
**We can enable or disable** any module via a user defined shortcut even if it is always-on or should be off for a specified image. The results are non-predictable, crashes included.

One example has been reported in #6992 (at least the issue of a disabled always-on module got a safety check) 

**To Reproduce**
Go to the preferences->shortcuts section, select the demosaic module and define a shortcut to enable it.
Go to darkroom using a raw image and press as you just defined before. Observe the module-status icon changing. (you can't change that by a mouse-click of course.)

**Expected behavior**
Difficult to describe, there might be many issues around.
1. There might be modules that must be off but are switched on. 
2. We could have switches or sliders hidden on purpose in that module that are not properly checked in commit_parameters so could lead to non-obvious changes or faults.

How to solve? I am not a friend of all these shortcuts and have personally not used any of them so far so i have not looked into or worked on that code at all. Problem (1) and the one reported in #6992 might want a flag in the module header to prohibit any on/off switching. Problem(2) seems very difficult to me.

**Platform (please complete the following information):**
 Current git master

**Additional context**
Valid for all OS, CL enabled or not.

**Comment by elstoc** [comment]
The shortcut issue is fairly simple and is resolved in #7038. There might conceivably be modules that sometimes have an enable button and sometimes do not, so I've left it so that the user can still define a shortcut. It just won't do anything.

**Comment by elstoc** [comment]
I didn't flag the PR as resolving this issue because I wasn't clear if there was something else you wanted to do here in addition

**Comment by jenshannoschwalm** [comment]
Is it also possible to disable a shortcut for non-visible widgets? (For example in demosaic we have the 'edge threshold' slider that is not used in other demosaicers.)

**Comment by elstoc** [comment]
Probably, but that would be more involved and would have to be done on a case-by-case basis.

**Comment by jenshannoschwalm** [comment]
I found very simple ways to trigger such conditions

1. Open a raw in darkroom - Ctrl-C to copy history -- open a jpeg in darkroom -- Ctrl-V pasting rawdenoise and demosaic to the jpegs history.

2. As above also in lightroom

At least the is no crashing any more
