### ISSUE TITLE
[White balance] For jpegs it's not enabled and clicking on set white balance as shot does not enable it. 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7041]
Current master.

When I open an imported jpeg the white balance is not enabled. The **`set white balance as shot`** (camera icon) is highlighted, clicking it does nothing and module is not enabled.

![image](https://user-images.githubusercontent.com/1119439/100051822-abcd2680-2e42-11eb-836a-6946dd477957.png)

When I click the **`bulb`** it gets enabled.

![image](https://user-images.githubusercontent.com/1119439/100053255-a6bda680-2e45-11eb-8dcd-9d33efe8f527.png)

**Comment by MStraeten** [comment]
What do you expect? white balance deactivated is identical to 'as shot' so you don't change anything when clicking on it. So no need to enable the module. Clicking on 'camera reference' changes the setting even it is identical to 'as shot' for jpegs. 
The module is enabled on a change not by comparing values ...

**Comment by chhil** [comment]
It's being used so it should be enabled?

**Comment by parafin** [comment]
Is your feature request to enable module as soon as anything is clicked in it (not even changed)?

**Comment by chhil** [comment]
It's actually a bug report and not a feature request.

If the white balance is being used by the pipeline then it should be enabled.

**Comment by parafin** [comment]
It's not being used, WB is already applied to JPEG data. Closing then.
