### ISSUE TITLE
[Color Calibration] Histogram set for one color channel shifts when R/G/B sliders are moved

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7043]
Why does red histogram vary when blue and green sliders are moved?

1. All sliders are to the left, the histogram has only the red channel enabled for viewing. 

![image](https://user-images.githubusercontent.com/1119439/100053470-1f246780-2e46-11eb-9319-0a0119380dfb.png)

2. Move the red slider, the red histogram moves.
![image](https://user-images.githubusercontent.com/1119439/100053576-57c44100-2e46-11eb-8c9c-e45f07cca7f5.png)

3. Move the green slider, the red histogram moves.
![image](https://user-images.githubusercontent.com/1119439/100053646-7d514a80-2e46-11eb-824b-58a8a6e8df99.png)

4.Move the blue slider, the red histogram moves.
![image](https://user-images.githubusercontent.com/1119439/100054079-5c3d2980-2e47-11eb-8068-183874b6048f.png)

5. CAT is set up for bypass. Based on the channel mixing [documentation](https://darktable-org.github.io/dtdocs/module-reference/processing-modules/color-calibration/) ... **`but it is also possible to mix channels in the RGB working space of the pipeline by setting the adaptation to “none (bypass)”`**
![image](https://user-images.githubusercontent.com/1119439/100054048-4e87a400-2e47-11eb-9831-b68a4f2839de.png)

I am having difficulty understanding how the grey tab works. I am fully aware I am not competent enough to understand color spaces being used in this module (previously I was told XYZ is being used and they are equivalent to RGB).

Currently I go for a monochrome image simply based on perception of the image by moving sliders as I can't pin down the behavior of the sliders.

**Comment by elstoc** [comment]
You're not understanding how the grey tab works here. "Grey" means that on output all RGB components are equal (i.e. grey). When you shift *any* of the input sliders you are changing the output of all R,G and B components *equally* based on the input RGB components.

**Comment by chhil** [comment]
Ok will move to pixls
