### ISSUE TITLE
[Color Calibration] Normalize channels provides no feedback in sliders for the changes it makes behind the scenes.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7044]
From the [documentation](https://darktable-org.github.io/dtdocs/module-reference/processing-modules/color-calibration/)
```
normalize channels
Select this checkbox to normalize the coefficients to try to preserve the overall brightness of this channel in the final image as compared to the input image.
```

Should the any sliders move when normalize is clicked after the sliders have been moved?
Or constantly see feedback on sliders when its enabled to start with and it hits the point when it needs to normalize?
I can see the histogram readjust.
My assumption is that it makes sure the sum of the values of the slider add up to 1 when they are more than 1.

**Comment by elstoc** [comment]
I'm not sure what that would add. I think it's probably fine without.

**Comment by aurelienpierre** [comment]
not a bug, params are normalized in background
