### ISSUE TITLE
DT importing old edits with xmps causing hang possibly due to history in xmp missing items

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7060]
DT current master

Managed to get DT freeze on me.

1. imported 20K images. Using recurve folders. Import completed. These were DT edited files or simply files that were previously imported in DT and not edited ( i.e. had xmps).
2. closed DT.
3. Ran darktable-generate-cache 
4. I had cache generator stuck and had to ctrl+c out of it.
```
[rawspeed] (P1115149.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115149.RW2".
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
image 13420/14309 (93.79%) (id:13425)
^C
```
5. Checked for file and xmp they were there. I have shared them [here](https://www.dropbox.com/s/qu3j46ye3dwc760/P1115149.zip?dl=0)
6. Opened DT and went to the collection to see what it looked like.
![image](https://user-images.githubusercontent.com/1119439/100178214-7b948f00-2ef9-11eb-8738-60baddcd84cb.png)
7. The image is there but the tiles following it **never** get filled up. Which would mean the cache file has not been generated.
8. Double clicking on the first grey tile after last image displayed freezes DT.
9. Shell had the following output. Note the file is different. I had clicked P1115150 but its complaining about P1115154, which is probably because DT was trying to generate the cache file of what's in the view and fails on that.
```
mchhil@DESKTOP-MKCA8HN:~/darktable$ /opt/darktable/bin/darktable
[rawspeed] (P1115154.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115154.RW2".
```
10. CTRL+C out of DT in the shell.
11. I run the cache generator to confirm and I get P1115154 having a problem 
```
image 13424/14309 (93.82%) (id:13429)
[rawspeed] (P1115154.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115154.RW2".
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
image 13425/14309 (93.82%) (id:13430)
```
12. I open DT again to see the 5154 file
![image](https://user-images.githubusercontent.com/1119439/100178789-aaf7cb80-2efa-11eb-9577-d138445888ce.png)
13. Closed DT, removed xmp for the 5154 file and reimported it back in, worked fine.
The Original xmp and the newly generted ones can be found [here](https://www.dropbox.com/s/pdj74ouayw5mpfv/P1115154.zip?dl=0)
**They are quite different and is most likely the cause as some history steps were not there in the old edit (rawprepare,demosaic.temperature and highlights). This may be the problem.**

I am not sure where the problem is. Its most likely during recursive import.
Also cache generator getting stuck and having to ctrl+c out of it is not good.

**Comment by chhil** [comment]
May be related to 
https://github.com/darktable-org/darktable/issues/6992
https://github.com/darktable-org/darktable/pull/7015

**Comment by parafin** [comment]
Are you completely sure that "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115149.RW2" and "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115154.RW2" exist? What if you try to run the following command in the terminal (do copy-paste):
```
ls "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115149.RW2" "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115154.RW2"
```
Are there any disk/FS errors in `dmesg` output?

**Comment by chhil** [comment]
They definitely exist, I have reimported them back in from the location without the xmp and it works fine. Its the old xmp files that are creating these problems.

![image](https://user-images.githubusercontent.com/1119439/100212848-dea31780-2f33-11eb-8594-4e9abb1a4c78.png)

> Are there any disk/FS errors in dmesg output?

I don't know what this is, but I have provided whatever warning were there on the shell.
No disk errors per se.

I am running wsl Ubuntu 20.

**Comment by parafin** [comment]
No idea then why rawspeed complains that it can't read them and how it can be related to XMP files.

**Comment by jenshannoschwalm** [comment]
Any special file attributes? R/W? Ownership?

**Comment by chhil** [comment]
Removing the xmp (that has missing information, old DT did not have some history steps that are probably mandatory) and importing it creates a new xmp with more history thats needed for it being processed. The files are provided https://www.dropbox.com/s/pdj74ouayw5mpfv/P1115154.zip?dl=0  with original xmp that causes it to fail.

No special attributes as far as I can tell.

**Comment by chhil** [comment]
The xmp diff between working and not working.

![image](https://user-images.githubusercontent.com/1119439/100219129-a30c4b80-2f3b-11eb-8be6-f814f37e7216.png)

**Comment by chhil** [comment]
In my vscode debugger... you can see the mip map cache trying to open the file. You can see some of the variables in the image too.


```
libstdc++.so.6!__cxa_throw (Unknown Source:0)
libdarktable.so!rawspeed::ThrowException<rawspeed::FileIOException>(const char * fmt) (\usr\include\c++\9\array:234)
libdarktable.so!rawspeed::FileReader::readFile(rawspeed::FileReader * const this) (\home\mchhil\darktable\src\external\rawspeed\src\librawspeed\io\FileReader.cpp:52)
libdarktable.so!dt_imageio_open_rawspeed(dt_image_t * img, const char * filename, dt_mipmap_buffer_t * mbuf) (\home\mchhil\darktable\src\common\imageio_rawspeed.cc:130)
libdarktable.so!dt_imageio_open(dt_image_t * img, const char * filename, dt_mipmap_buffer_t * buf) (\home\mchhil\darktable\src\common\imageio.c:1183)
libdarktable.so!dt_mipmap_cache_get_with_caller(dt_mipmap_cache_t * cache, dt_mipmap_buffer_t * buf, const uint32_t imgid, const dt_mipmap_size_t mip, const dt_mipmap_get_flags_t flags, const char mode, const char * file, int line) (\home\mchhil\darktable\src\common\mipmap_cache.c:784)
libdarktable.so!_dt_dev_load_raw(const uint32_t imgid, dt_develop_t * dev) (\home\mchhil\darktable\src\develop\develop.c:655)
libdarktable.so!dt_dev_load_image(dt_develop_t * dev, const uint32_t imgid) (\home\mchhil\darktable\src\develop\develop.c:709)
libdarktable.so!dt_imageio_export_with_flags(const int32_t imgid, const char * filename, dt_imageio_module_format_t * format, dt_imageio_module_data_t * format_params, const gboolean ignore_exif, const gboolean display_byteorder, const gboolean high_quality, const gboolean upscale, const gboolean thumbnail_export, const char * filter, const gboolean copy_metadata, const gboolean export_masks, dt_colorspaces_color_profile_type_t icc_type, const gchar * icc_filename, dt_iop_color_intent_t icc_intent, dt_imageio_module_storage_t * storage, dt_imageio_module_data_t * storage_params, int num, int total, dt_export_metadata_t * metadata) (\home\mchhil\darktable\src\common\imageio.c:663)
libdarktable.so!_init_8(const dt_mipmap_size_t size, const uint32_t imgid, dt_colorspaces_color_profile_type_t * color_space, float * iscale, uint32_t * height, uint32_t * width, uint8_t * buf) (\home\mchhil\darktable\src\common\mipmap_cache.c:1255)
libdarktable.so!dt_mipmap_cache_get_with_caller(dt_mipmap_cache_t * cache, dt_mipmap_buffer_t * buf, const uint32_t imgid, const dt_mipmap_size_t mip, const dt_mipmap_get_flags_t flags, const char mode, const char * file, int line) (\home\mchhil\darktable\src\common\mipmap_cache.c:822)
generate_thumbnail_cache(const int32_t max_imgid, const int32_t min_imgid, const dt_mipmap_size_t max_mip, const dt_mipmap_size_t min_mip) (\home\mchhil\darktable\src\generate-cache\main.c:112)
main(int argc, char ** arg) (\home\mchhil\darktable\src\generate-cache\main.c:254)
```

![image](https://user-images.githubusercontent.com/1119439/100224276-9fc88e00-2f42-11eb-9cb3-f904c874bea5.png)

**Comment by chhil** [comment]
So it looks like the image failed import because of the xmp. Has a skull in this case something got written to mip cache.
The image was never edited previously , just was imported on a DT from Oct 4 2019  (based on xmp creation time on file).
Output on shell has 
```
[rawspeed] (P1115188.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Spider/P1115188.RW2".
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[exiv2 dt_exif_get_thumbnail] /mnt/f/Temp/delete/Lumix/Spider/P1115188.RW2: /mnt/f/Temp/delete/Lumix/Spider/P1115188.RW2: Failed to open the data source: Permission denied (errno = 13)
```
I reimported the image with its existing xmp and DT froze.
Killed DT.
Renamed xmp to become unavailable and imported the image.
![image](https://user-images.githubusercontent.com/1119439/100225912-f040eb00-2f44-11eb-84e6-fd1427e1789b.png)
Image imports fine.
Original xmp and new one differ
![image](https://user-images.githubusercontent.com/1119439/100226202-66dde880-2f45-11eb-9f26-9ac06405a235.png)

**Comment by parafin** [comment]
Now there's permission denied error. I really think it has nothing to do with XMP file, but there's some intermittent access error to that file which is unrelated to dt.

**Comment by parafin** [comment]
I'm not sure if this is going to work in WSL, but please show the output of "dmesg" command (redirect it to file and upload the file).

**Comment by chhil** [comment]
I don't think WSL is the issue. I have been using DT on it for some time now.

Currently nothing DT related is running. I don't know what dmesg does or when it needs to be run. I am not a linux person.

It just output one line so just sharing it directly.
mchhil@DESKTOP-MKCA8HN:~/darktable$ dmesg
[    0.015772]  Microsoft 4.4.0-18362.1049-Microsoft 4.4.35

**Comment by chhil** [comment]
> Now there's permission denied error. I really think it has nothing to do with XMP file, but there's some intermittent access error to that file which is unrelated to dt.

You can close it if it seems irrelevant. 
I can work around it by removing the xmp's and reimporting them. Its reproducible and for every file it cannot read. It was at 90 something percent last time I ran the cache with few files which created a problem.

**Comment by chhil** [comment]
Tried the same image with original xmp on my older windows build. Cannot reproduce. Closing for now.

If I find something relevant, will share, in the interim I will just work around the problem I am having.
