### ISSUE TITLE
darktable crash

### ISSUE THREAD

**Issue by tariu** [darktable-org/darktable#7061]
backtrace: [darktable_bt_US8NU0.txt](https://github.com/darktable-org/darktable/files/5594332/darktable_bt_US8NU0.txt)

**Comment by MStraeten** [comment]
you are aware of https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title= ?
please give at least a minimum of information what you did, where it crashed  and what’s your system configuration.
No one will spend time to analyze a backtrace if you didn’t find it relevant enough to spend some time giving some information how to reproduce ...

**Comment by parafin** [comment]
Please create a new bug with compete information as pointed out by @MStraeten.
