### ISSUE TITLE
copy and paste edit stack: white balance is not pasted

### ISSUE THREAD

**Issue by cimatosa** [darktable-org/darktable#7063]
**Describe the bug**
when copying the history of the edits (pressing ctrl+c) and applying it to another image (pressing ctrl+v), manually set values of the white balance are not applied. I noticed that in the lighttable as well as the darkroom. 

**To Reproduce**
1. set the value of the white balance manually
2. copy stack
3. paste stack to another image

**Expected behavior**
I would expect that the white balance is also applied, and it has been like that in earlier versions of DT. This behavior is particularly desired when processing image taken for exposure blendings.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1787~g24e7212c1-dirty (current master 24e7212c1887e5601e6c3dc56da5f52ca2260d93)
 - OS: Linux

**Comment by johnny-bit** [comment]
This was recently changed as many users could shoot themselves in foot by not understanding what copy wb does or that it can't copy between different camera models.

First reported by me here: #6564
There's ongoing discussion in #6586 

@TurboGit - This needs consideration maybe do include WB in "safe copy" list?

**Comment by chhil** [comment]
If you need to work around this, use ctrl+shift+c, in the pop up dialog with history select the unchecked whitebalance. Then paste.

**Comment by TurboGit** [comment]
Well we have decided to keep the Ctrl+C very safe and for copying modules as needed one can use Ctrl+Shift+C. Not a bad compromise to me.

**Comment by cimatosa** [comment]
Thanks for such quick answers. Indeed, I was not aware of the Ctrl+Shift+c option. It certainly works. And i do agree that whether or not the WB should be included is a matter of debate.

I'm happy and will close this issue.

Thx again

**Comment by bobobo1618** [comment]
Could this potentially be made configurable? This is a massive pain point for me. I need to copy adjustments one-by-one from a bunch of ARW files to _the same_ files but in DNG format. Since I have to do it one-by-one, Ctrl+Shift+C doesn't work well for me.

**Comment by johnny-bit** [comment]
@bobobo1618 - please issue an FR for that - this issue is now closed. Or alternatively post to https://github.com/darktable-org/darktable/issues/6586 FR with propositions and suggestions so it could be reopened
