### ISSUE TITLE
regression : color picker error on console

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#7067]
**Describe the bug**
color picker issue error on console, this was fixed and it is back

**To Reproduce**

1. Go to 'darkroom'
2. Click on the color picker and select a point or area on image
3. See error

```
[_transform_matrix] invalid conversion from 1 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 1 to -1
[_transform_matrix] invalid conversion from 2 to -1
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to -1
```

**Expected behavior**
no error on console

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux

**Comment by TurboGit** [comment]
@aurelienpierre : would you mind having a look at this one ? maybe a recent regression due to the recent rework you did ? 

It seems that  `dt_iop_colorspace_type_t _transform_for_picker(dt_iop_module_t *self)` returns `iop_cs_NONE`.

**Comment by TurboGit** [comment]
This is because the error come from calling `_transform_for_picker(dt_iop_module_t *self)` for module `colorout` which request the actual colorspace for the picker by calling `dt_iop_color_picker_get_active_cst`, and this returns `iop_cs_NONE` for the global colorpicker.

```
dt_iop_colorspace_type_t dt_iop_color_picker_get_active_cst(dt_iop_module_t *module)
{
  if(module->picker)
    return module->picker->picker_cst;
  else
    return iop_cs_NONE;
}
```

**Comment by TurboGit** [comment]
Now the question is to know what colorspace the global colorpicker (so `colorout`) should be using. I'm sure you know that @aurelienpierre .

**Comment by aurelienpierre** [comment]
I'm not sure to understand where and how this function is called, but if it's called after colorout, we are in display RGB space (non-linear). But the global color picker already does some conversion to histogram color space, so I'm not sure what default is to be used there.

**Comment by TurboGit** [comment]
It is called from pixelpipe_hb.c around line 1068. The first call triggering this is  `dt_ioppr_transform_image_colorspace`.

```
 // Lab color picking for module
  if(_request_color_pick(pipe, dev, module))
  {
    // ensure that we are using the right color space
    dt_iop_colorspace_type_t picker_cst = _transform_for_picker(module);
    dt_ioppr_transform_image_colorspace(module, input, input, roi_in->width, roi_in->height,
                                        input_format->cst, picker_cst, &input_format->cst,
                                        dt_ioppr_get_pipe_work_profile_info(pipe));
    dt_ioppr_transform_image_colorspace(module, *output, *output, roi_out->width, roi_out->height,
                                        pipe->dsc.cst, picker_cst, &pipe->dsc.cst,
                                        dt_ioppr_get_pipe_work_profile_info(pipe));
    ...
```

**Comment by TurboGit** [comment]
> but if it's called after colorout,

It is called for `colorout`. In the code above `module` is `colorout`.

**Comment by aurelienpierre** [comment]
The trick thing about colorout is we enter Lab and exit display RGB, and internally we are in XYZ. So we need to know exactly where we sample the image.

**Comment by TurboGit** [comment]
> where we sample the image.

Nowhere, well I'm speaking about the global color picker. So the question is where it is? I expect it to sample in colorout and use the display profile ? No ?

**Comment by aurelienpierre** [comment]
I need to have a closer look at what the global color picker is doing, I don't know that part very well. But it's critical to know at what stage in the pipe it samples pixels, because that will tell us the colorspace in use.

Also I fear the RGB conversion thing is wrong. If we have the Lab value read by the color picker, since Lab is a reference color space (not tied to any display medium), it's just a matter of converting the picked Lab to whatever color space we want from Lab -> XYZ -> any profiled RGB. I don't see why we need to convert the actual pixels to RGB.

**Comment by TurboGit** [comment]
Ok, thanks I'll assigned this to you.

**Comment by TurboGit** [comment]
See #7076 for a fix.

**Comment by hlecleme** [comment]
@TurboGit Perhaps an alternative work-around would be to completely skip the execution of the “module picker” for the colorout module:

```
diff --git a/src/develop/pixelpipe_hb.c b/src/develop/pixelpipe_hb.c
index 6e9a6a60c..5e17db1c1 100644
--- a/src/develop/pixelpipe_hb.c
+++ b/src/develop/pixelpipe_hb.c
@@ -978,6 +978,7 @@ static gboolean _request_color_pick(dt_dev_pixelpipe_t *pipe, dt_develop_t *dev,
   return dev->gui_attached && pipe == dev->preview_pipe
       &&                           // pick from preview pipe to get pixels outside the viewport
       module == dev->gui_module && // only modules with focus can pick
+      strcmp(module->op, "colorout") != 0 && // colorout module is only used for the global color picker
       module->request_color_pick != DT_REQUEST_COLORPICK_OFF; // and they want to pick ;)
 }
 
```

**Comment by TurboGit** [comment]
Would that work ? Worth trying for sure...

**Comment by TurboGit** [comment]
@hlecleme : New version proposed, looks like skipping in this case works fine. I have also found an issue in colorchecker where the picker was completely bogus. We probably want to review all pickers, I have done a first pass and it seems the others are working.

**Comment by TurboGit** [comment]
@hlecleme : Can you review ? You know well this part I think. TIA.
