### ISSUE TITLE
darktable should not open in culling view mode

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#7079]
just had a bit of a scare, opened 0415cd9 from cl with lib :memory: and a directory.  dt opened to gray 
reopened
had closed dt in culling view and it reopened that way
had to open dt w/o a directory specified and change to lighttable view, then everything was ok
dt *should* not open in culling view! PERIOD  
there is no compelling reason to open in culling mode.

openSUSE Tumbleweed 20201124
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable 3.3.0+1810~gaa88a77c8
OpenCL on
i7 12-core 36GB
kernel 5.9.8-2-default

**Comment by ptilopteri** [comment]
not explained as I intended, revision follows:

just had a bit of a scare, opened 0415cd9 from cl with lib :memory: and a directory. dt opened to gray
screen, then segfaulted 
had closed dt in culling view and it reopened that way
had to open dt w/o a directory specified and change to lighttable view, then everything was ok
dt should not open in culling view! PERIOD
there is no compelling reason to open in culling mode.

OR dt should read the directory specified on control line

BUT w/o a directory specified dt *should* not open in culling view

**Comment by AlicVB** [comment]
I'm not sure how to interpret the tonality your messages, but well...
1. I don't see why we shouldn't open dt in culling mode. I can see some situations where it can be handy for the workflow (continue an interrupted culling session for example) and even more when dt is opened with a directory in command-line
2. The only issue here is the segfault, but I don't reproduce...

So I'm closing for now. For the segfault, if you can reproduce with latest master, can you open another issue, with exacts steps and a backtrace if possible ?
Thanks !

**Comment by ptilopteri** [comment]
tonality was not intended hostel, just emphasis

I opened dt from control line with --library :memory: /<directory>/
switched to cullingview

inadvertently closed dt

on reopening dt with same cl 
I get a gray screen as it opens the same view as it left, culling
but it does not display an image, any image, and no keystroke will
change what is displayed, <ctrl><shift><t> or <ctrl><shift><b> or
<tab>, or <ctrl><shift><l> .... 

I just performed the same sequence and after some time (control line 
output    
   http://wahoo.no-ip.org/~paka/d88a1c6ab.segfault.txt
it finally aborted, core dumped, "Segmentation Fault".

core dump: (large file)
  http://wahoo.no-ip.org/~paka/d88a1c6ab.core.dump.lz4

please re-open this issue #7079

**Comment by AlicVB** [comment]
hm... not sure to understand all the files here, but in your backtrace, I see some mentions to lua. To see if that comes from here, can you backup and remove all lua stuff from your config dir ?
Thanks !

**Comment by ptilopteri** [comment]
closed darktable in culling view mode

moved ~/.config/darktable/lua and ~/.config/darktable/luarc 
out of ~/.config/darktable

opened darktable --library :memory: /home/<user>/Pictures/2020/
sig fault

note: no fault when opening *only* any one directory below 2020/
but do get seg fault when all *except* any one directory below 2020/

tks

**Comment by ptilopteri** [comment]
plus
I no longer believe that one should not be able to open dt in 
culling view mode, but
need to solve why it seg faults with this particular sequence.

tks

**Comment by AlicVB** [comment]
> note: no fault when opening _only_ any one directory below 2020/
> but do get seg fault when all _except_ any one directory below 2020/

sorry, I'm quite bad in English and don't understand what you mean here, can you rexplain it, maybe with some examples ? thanks a lot !



> but
> need to solve why it seg faults with this particular sequence.

completely agree ! whatever the features are, we shouldn't segfault...

**Comment by ptilopteri** [comment]
*** always loading with dt from cl with --lib :memory: /<directory/ ***
*** with dt in culling view mode ***

/home/<user>/Pictures/2020/soccer/
/home/<user>/Pictures/2020/candids/
/home/<user>/Pictures/2020/holidays/
/home/<user>/Pictures/2020/parks/
/home/<user>/Pictures/2020/work/
/home/<user>/Pictures/2020/other/

/home/<user>/Pictures/2020/
causes seg fault

entire group od directories omitting /home/<user>/Pictures/2020/other

ie: /home/<user>/Pictures/2020/soccer /home/<user>/Pictures/2020/candids/ /home/<user>/Pictures/2020/holidays/ /home/<user>/Pictures/2020/parks/ /home/<user>/Pictures/2020/work/

seg faults

and loading the group omitting any of the other directories 
seg faults 

loading *only* /home/<user>/Pictures/2020/soccer
or *only* /home/<user>/Pictures/2020/other
does not seg fault

**Comment by ptilopteri** [comment]
one other thing I noticed that may or may not be of interest,
I get no thumbnails displayed when opening
/home/<user>/Pictures/2020/

but do if I open /home/<user>/Pictures/2020/<any.directory>

import is set to recursive at 5 levels
I only have two levels, /home/<user>/Pictures/2020/, and
the level immediately below /home/<user>/Pictures/2020/

**Comment by AlicVB** [comment]
ok, got it, I even manage to reproduce the crash with a meaningful backtrace :)
I'll try to fix that...

**Comment by AlicVB** [comment]
ok, PR #7346 should fix it

The fact that no thumbnail is shown is the normal behavior as dt seems to consider that opening with a specific directory in cl open *only* this specific directory (and if the dir doesn't have images...)

**Comment by ptilopteri** [comment]
tks for the fix, will test when it is published

but the directory *does* contain images.

**Comment by AlicVB** [comment]
you mean that you have valid images directly under /home//Pictures/2020/ ? (not in a subdir) In this case here it show them...
To be sure they are imported :
- quit dt not in culling mode (to avoid the crash) 
- launch dt with ` --library : memory: /home//Pictures/2020/`
- go to lighttable - filemanager
- reset the collect module
- does it show the images which are directly under /home//Pictures/2020/ in the list ?

thanks !

**Comment by ptilopteri** [comment]
> you mean that you have valid images directly under /home//Pictures/2020/ ? (not in a subdir) In this case here it show them...

no, it does not show them

> To be sure they are imported :

the import was    /home/<user>/Pictures/2020/
and there are valid images withing /home/<user>/Pictures/2020/
and there are more directories there also

 tks

**Comment by ptilopteri** [comment]
tks, that works for me, although the directory(ies) specified
on the control line are *very* slow to load ??? 

tks
