### ISSUE TITLE
Add X-Trans image for the integration test suite

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#7086]
>  it would be good to have an X-Trans image for the integration test suite

Sure would be nice to have one in the images directory. Do you have one to share ? I don't have an X-Trans camera, but I'm sure we can find a free sample somewhere. Let me know.

_Originally posted by @TurboGit in https://github.com/darktable-org/darktable/issues/7084#issuecomment-734499401_

Looking through raw.pixls.us as suggested by johnny-bit, I would recommend one of the following if we would like to keep the file size modest:
XQ2: https://raw.pixls.us/data/Fujifilm/XQ2/DSCF4186.RAF (19 MB)
X-T2: https://raw.pixls.us/data/Fujifilm/X-T2/20170114_174341_TFW04727.RAF (22 MB)

The former is a picture of a boat on a lake on a nearly cloudless day, so it's rather lacking in reds and greens.

The latter is a shot of a photographic target with stepped gray scales and color "spectra", but it's **substantially** underexposed.

A couple of the others I downloaded are even less suitable.

I haven't looked through the models with bigger sensors, but if you're OK with a 30-45MB image file, I can see if there's something better for exercising image processing.

**Comment by ralfbrown** [comment]
Found a sample with a ColorChecker in it: https://raw.pixls.us/data/Fujifilm/X-T4/DSCF0267.RAF  (27 MB)

**Comment by TurboGit** [comment]
@ralfbrown : Perfect I was looking for an image with a color checker in it too. The latest is perfect.

Do you want me to integrate it ?

I would place the image into the `integration/images` directory under the name `mire1-xtrans.raf`.

**Comment by chhil** [comment]
If this helps....used my x100v
https://www.dropbox.com/s/noo9tkkhz6rrppq/DSCF0783.RAF?dl=0

**Comment by ralfbrown** [comment]
@chhil That would be good, but the color checker is underexposed (the bright sky fooled the meter).

@TurboGit I'll leave it up to you to decide on the image and integrate it.

**Comment by chhil** [comment]
Ping me if you still need one and I can take another one tomorrow morning (my time).

**Comment by TurboGit** [comment]
X-Trans tests image now integrated. I have taken the first with color checker where the exposition is ok.
