### ISSUE TITLE
Collapsing new group causes jump to first image in collection

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#7088]
**Describe the bug**
In lighttable view collapse grouped images.  Open an image and create a duplicate.  Return to lighttable and click the icon to collapse the group.  The collection jumps to the first image.

**To Reproduce**
1. Open a collection in lighttable
2. Set grouped images to collapse
3. Scroll down a page or two in the collection
4. Open an image and create a duplicate.
5. Return to lighttable
6. Click the group icon on the image to collapse the group
7. The collection jumps to the first image in the collection.
-->

**Expected behavior**
The group should collapse and the following images should move 1 place closer to the top

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1846~g877ba6e66
 - OS: Ubuntu 18.04
 - OpenCL: yes
 - Nvidia 970M - 455.38

**Comment by TurboGit** [comment]
This looks like an issue for @AlicVB !

**Comment by AlicVB** [comment]
PR #7096  should fix this issue. Thanks for the report !

**Comment by wpferguson** [comment]
Tested #7096.  Works fine.  Thanks @AlicVB .
