### ISSUE TITLE
Optimization affecting reproducibility of integration tests

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#7099]
Here's a strange one that came up while double-checking some on-going refactoring:
  rm -rf build; ./build.sh --build-type Release; ./run.sh 0028-highpass-overlay
         maxDE=0.0000
  rm -rf build; ./build.sh --build-type RelWithDebInfo; ./run.sh 0028-highpass-overlay
        maxDE=1.0819

I went back and forth a couple of times with the same results.  Building with RelWithDebInfo changes 56 widely-scattered pixels by 1lsb.

Presumably, there's some optimization performed for Release which isn't being performed for RelWithDebInfo that changes evaluation order and hence accumulation of rounding errors.

dt 3.3.0+1874~g0b53b80c3
GCC 8.4.0
Linux kernel 5.7.19
AMD Threadripper 3970X, 64GB

**Comment by johnny-bit** [comment]
Yeah, that's true. What's also "weird" is that it also affects both repeatability and stability of tests themselves. Eg. trying to run tests designed for CI (0035) on LLVM 10 build with release flag, the whole thing segfaults... That's why I haven't added that to current CI runs :/
