### ISSUE TITLE
Pasting a history stack with mode=Append overwrites instead of appending (some) edits

### ISSUE THREAD

**Issue by bedahr** [darktable-org/darktable#7105]
**Describe the bug**
When pasting a "History Stack" to another image, there's two modes: 1) "append" and 2) "overwrite".
The "append" mode, however, does not solely append edits, it does overwrite those edits in the target image done in a module that is being pasted.
For example, if the stack to be pasted includes modifications in the "Retouch" module and the target image already has modifications in the "Retouch" module, those changes will be overwritten by pasting the history stack, even if mode is set to "append".

This, I believe, is actually expected behavior (and not a bad one in many cases) but I'm filing this as a bug instead of a feature request because the name "append", especially when the other option is "overwrite", is perhaps a bit misleading for this behavior.

**Suggested Resolution**
I think it'd be great to rebrand the current behavior as "Update and add" and to add a new option called "append" that really just appends the edits.
So if one copies a "Retouch" module and pastes it on another image that already has a "Retouch" module set up using mode="append", Darktable would paste the new module as "Retouch 1", leaving the original one untouched.

**To Reproduce**
1. Open two images A and B.
2. On image B, open the "contrast brightness and saturation" module and change saturation = +1
3. On image A, open the "contrast brightness and saturation" module and change contrast = +1
4. Copy all edits from image A and paste them on image B with mode=append.

**Expected behavior**
Expected image B to have saturation +1 and contrast +1.
However, image B will only have contrast +1, the saturation setting is lost.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: macOS 10.15.6

**Comment by MStraeten** [comment]
copy paste append adds modules to the history stack in opposite to clean the history stack first. 
see manual 2.3.8: "In simple terms the “overwrite” mode deletes the previous history stack, whereas “append” will concatenate the two history stacks."
concatenation doesn’t include instantiation so if the first instance of a module in image A is pasted to the history stack of image B, which also contains a first instance of this module then the last occurrence  of the module in history stack counts. If you copied two instances of the module from image A ther'll be also two instances copied to image B (but the first instance keeps overlaying the older historic layer of the first instance.)

**Comment by parafin** [comment]
Creating a new instance for each pasted module won't produce expected results for some of the operations. I don't think it can be solved in general way.

**Comment by bedahr** [comment]
@MStraeten Thanks for explaining the implementation. That makes sense to me now.

@parafin I can think of some modules where the results may be sometimes unwanted (Crop & Rotate, for example), but I think my main thinking here is that there's a really straightforward way to go and fix those clashes when they happen.
So let's say there is a module where applying it twice is certainly never what the user would want; If we still create a new instance in a new, strict appending mode, the user can simply turn off the old module. That's easy to do in the UX and something most users are probably familiar with. It's much harder to do the opposite.
As an example, I was retouching the model in a recent shoot a bit and after a while I noticed a detail in the background I wanted to edit out. I used the spot remove tool to do so and wanted to mass apply that to other shots of the series. However, that didn't work as some of them already had a used instance of spot removal. The best workaround I found was to go into every picture I already edited and Duplicate the Spot Removal instance that I knew would get overwritten before pasting the history stack element. It worked, but it's not very obvious / convenient.

**Comment by parafin** [comment]
The problem when there is no general solution is that details has to be worked out, and it may not be possible to define a solution that will fit all use-cases. There are a lot of these types of discussion already with existing functionality, adding one more topic to argue about probably won't be a top priority for dt developers;)
Another problem is that if different iops will be pasted in different way it will be confusing. At least current behaviour is somewhat consistent once you understand the concept of history stack.

So it's definitely not a bug, but a feature request, and before doing any actual coding someone has to come up with a description of how it should work, meaning going over all existing (including obsolete) iops and determining whether replace or new instance will make sense. Then it could be defined as an additional third mode of paste operation.

**Comment by bedahr** [comment]
Fair enough. I think there may be a feature request and a UX issue here. The feature request is for a mode of "true" appending of all changes and I totally see that that's non-trivial.
The UX issue is that the current mode being called "append" could be a bit confusing since from a pure user standpoint it does overwrite edits instead of "just" appending them. Thanks @MStraeten's comment I now understand that "append" is an accurate description of the implementation but I think that it may be better to focus the user-facing naming on the effect instead of the implementation.

From an organizational point I conflated both the UX discussion and the feature request in this single Github issue and I now think that this is probably not the most actionable way forward.
Where should we go from here: It seems that there's already discussions about the feature request I was proposing in other places (is there an issue I could read up on?  I'd love to follow along Should we discuss the UX element of the issue here or is there a better place..?

**Comment by parafin** [comment]
I was talking about the issues like https://github.com/darktable-org/darktable/issues/7063 - also concerning copy-paste BTW.

I would suggest to split UX concerns to a separate issue. But it is a bit late for upcoming major release, because we are nearing string freeze. So any changes to the text in the interface will have to go to the next one (minor or major).
