### ISSUE TITLE
Darktable 3.3.0.1876 : Invalid 3D LUT message on some valid 3D LUT

### ISSUE THREAD

**Issue by japamax** [darktable-org/darktable#7106]
[F-Log_LUT_E_Ver.1.17.zip](https://github.com/darktable-org/darktable/files/5610422/F-Log_LUT_E_Ver.1.17.zip)
[OPEN - Fuji Film LUTs Pro.zip](https://github.com/darktable-org/darktable/files/5610424/OPEN.-.Fuji.Film.LUTs.Pro.zip)

**Describe the bug**
When you want to use these 3D LUTs,  an INVALID error occurs in the name combo : INVALID >> 3D LUT 's name
I replace some CRLF with LF but nothing changed.
I added a title when the 3D LUT didn't have one but nothing changed.

**To Reproduce**
Choose any 3D LUT from attached files.

**Expected behavior**
All attached 3D LUTs seems valid but you can't use them in Darktable

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0.1876
 - OS: Archlinux

**Comment by phweyland** [comment]
I've tried your 3D LUTs and they work for me.
This error "INVALID >>" occurs when the lut file is not accessible any more.
To access a lut file, dt uses the 3D lut folder (in configuration) and the path inside this folder. This later is kept with image parameters. If in between you change the 3D lut folder dt cannot find the file any more.

So could you try to set back the 3d lut folder as it was when you first used these 3D lut files ?

**Comment by japamax** [comment]
Okay, you're right. My 3D LUT root has changed in the Darktable parameters and it's not the root but a subdirectory of the root. A false manipulation on my part.

I changed the root and everything works.
Problem closed
