### ISSUE TITLE
tethering support

### ISSUE THREAD

**Issue by oelki9** [darktable-org/darktable#7107]
My camera is not recognized by darktable 3.2.1 under Ubuntu 20.04 LTE and only the buttons "image..." and "folder..." are available for selection. A "scan for devices" button is not shown.

What I did so far:

uwe@tux:~$ sudo apt install gphoto2
uwe@tux:~$ env LANG=C gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Sony ILCE-7M2 (Control)        usb:001,011
uwe@tux:~$ env LANG=C gphoto2 --port usb: --abilities
Abilities for camera             : Sony ILCE-7M2 (Control)                     
Serial port support              : no
USB support                      : yes
Capture choices                  :
                                 : Image
                                 : Preview
                                 : Trigger Capture
Configuration support            : yes
Delete selected files on camera  : yes
Delete all files on camera       : no
File preview (thumbnail) support : yes
File upload support              : yes
uwe@tux:~$ env LANG=C gphoto2 --port usb: --capture-image-and-download
New file is in location /capt0000.jpg on the camera                            
File capt0000.jpg exists. Overwrite? [y|n] y
Saving file as capt0000.jpg
Deleting file /capt0000.jpg on the camera
New file is in location /capt0001.arw on the camera                            
File capt0001.arw exists. Overwrite? [y|n] y
Saving file as capt0001.arw
Deleting file /capt0001.arw on the camera
uwe@tux:~$ env LANG=C gphoto2 --port usb: --capture-tethered
Waiting for events from camera. Press Ctrl-C to abort.                         
UNKNOWN PTP Property 5004 changed
UNKNOWN PTP Property 5004 changed
UNKNOWN PTP Property d21d changed
UNKNOWN PTP Property d21d changed
UNKNOWN PTP Property 5005 changed
UNKNOWN PTP Event c201, Param1 ffffc001
File capt0000.jpg exists. Overwrite? [y|n] y                                   
Saving file as capt0000.jpg
File capt0001.arw exists. Overwrite? [y|n] y                                   
Saving file as capt0001.arw
CAPTURECOMPLETE
CAPTURECOMPLETE
UNKNOWN PTP Property d21d changed
UNKNOWN PTP Property 5005 changed
UNKNOWN PTP Property d21d changed
UNKNOWN PTP Event c202, Param1 ffffc001
UNKNOWN PTP Property d21d changed
# all tests with gphoto2 run w/o problems
uwe@tux:~$ darktable -d camctl 2>1 >camctl.log
# the camctl.log is empty

Do you have any hint for me?

**Comment by Nilvus** [comment]
Seems to not be a darktable issue. Check that page to see that your camera is not supported by gphoto library for tethering mode: http://gphoto.org/doc/remote/

**Comment by oelki9** [comment]
After new install, everything seems to be fine.

Thx
