### ISSUE TITLE
Slideshow does not start

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#7113]
**Describe the bug**
Slideshow does not start

**To Reproduce**
1. Open lighttable and select first image
2. Press 's' to start slideshow
3. The whole screen gets grey and a tooltip says 'waiting to start slideshow' 
4. after 5 seconds the lighttable is shown again and the tooltip disappears

**Expected behavior**
Images are shown in slideshow

**Screenshots**
![slideshow](https://user-images.githubusercontent.com/5677563/100519881-f6c8a000-319a-11eb-91c0-7534a2aedb7d.png)

**Platform:**
 - Darktable Version: 3.3.0+1853~g05949edcf (current master)
 - OS: Manjaro Linux / gnome
 - OpenCL: not available
 - graphics card: video-hybrid-intel-nvidia-455xx-prime

**Additional context**
- works with 3.2.1
- debug-output while slideshow tries to start:
```
pixelpipe cacheline 0 used 0 by 18446744073709551615 (18446744073709551615)
pixelpipe cacheline 1 used 0 by 18446744073709551615 (18446744073709551615)
cache hit rate so far: -nan
```

**Comment by johnny-bit** [comment]
I can confirm the problem on 3.3.0+1877 and I have same debugging output:
```
pixelpipe cacheline 0 used 0 by 18446744073709551615 (18446744073709551615)
pixelpipe cacheline 1 used 0 by 18446744073709551615 (18446744073709551615)
cache hit rate so far: -nan
```

**Comment by TurboGit** [comment]
A recent regression as I have been working on the slideshow not so long ago. I'll have a look in the coming days if now one has fixed that before.

**Comment by johnny-bit** [comment]
Can you remember how long ago? That would aid in bisecting.

**Comment by TurboGit** [comment]
Yes, my last work on slideshow was on Nov 5th, see last commit:

```
commit fc3ea54b5ad993eda7d764bb0b89ba8ac25d6cfb
Author: Pascal Obry <pascal@obry.net>
Date:   Thu Nov 5 19:42:00 2020 +0100

    Allow to hide/show the borders controls on the slideshow.
```

**Comment by johnny-bit** [comment]
Interestingly enough the slideshow does not work on fc3ea54b5ad993eda7d764bb0b89ba8ac25d6cfb and i do have 

```
pixelpipe cacheline 0 used 0 by 18446744073709551615 (18446744073709551615)
pixelpipe cacheline 1 used 0 by 18446744073709551615 (18446744073709551615)
cache hit rate so far: -nan
```

in  #6757 Alic mentions that for him it didn't work at first? dunno.

**Comment by AlicVB** [comment]
hmm... it's strange, because, what didn't work at first was just the shortcut, not the slideshow...

**Comment by AlicVB** [comment]
OK, I've found problem : if you start with shortcut => doesn't works with menu => OK
This will need some investigation as, at first sight, both solutions ends at the same point...

**Comment by quovadit** [comment]
after re-adding the 4 removed lines in src/views/slideshow.c it works again without problems:

```
{
  return 0;
}

int key_pressed(dt_view_t *self, guint key, guint state)
```

**Comment by johnny-bit** [comment]
Yea - starting slideshow via shortcut makes it no workee. Starting via view menu is fine.

**Comment by AlicVB** [comment]
@quovadit : good catch !
Thanks to your pointer, I've the fix. I'll propose a PR soon

**Comment by quovadit** [comment]
quite interesting: hide/show borders with 'b' did work before 6757 without problems but does only work once after 6757

**Comment by AlicVB** [comment]
@quovadit : a different bug, but I'll fix too

**Comment by AxelG-DE** [comment]
Just now I was digging into this as well. 
* I found prior to this, the slideshow is already broken. 
  * It can start, but it will not proceed to show (always stick on the same pic)

I went back to 3.1.0+1111~g9742e1065  and fresh --configdir. Still the same.
Indeed that should be a new issue, however, I never know, by when somebody has the fingers anyway in it at the right place.

Tonight I do run out of time for further bisecting, as I did not dig out yet, where is a working commit.
As I have some urgent obligations... @quovadit do you have the mood, to dive into this for bisecting?

**Comment by quovadit** [comment]
yes I can have a look, but I don't know what the desired behavior is.
After pressing Space the slideshow starts, this is the same in 3.2.1 and master
I thought that's ok...

**Comment by AlicVB** [comment]
@quovadit : PR #7115 should fix both issues you describe
@AxelG-DE : not sure to understand the problem... is it the same problem described here ? does PR #7115 solve it ?

**Comment by quovadit** [comment]
slideshow can be started with 's' --> OK
pressing 'b' stops slideshow when switching to the next image (or if 'b' is pressed again) --> NOK

**Comment by AxelG-DE** [comment]
> yes I can have a look, but I don't know what the desired behavior is.
> After pressing Space the slideshow starts, this is the same in 3.2.1 and master
> I thought that's ok...

My bad! :-/
I expected the slightshow start to revolve just after entering it, not need to be triggered with space....

I will edit my post (once I know, how to cross out with markdown)

**Comment by AxelG-DE** [comment]
> @AxelG-DE : not sure to understand the problem... is it the same problem described here ? does PR #7115 solve it ?

Marked my comment with <del>, as I misjudged the desired function, sorry for the noise

**Comment by quovadit** [comment]
As the behavior of the slideshow is quite strange in general since at least 2.7 we should focus on the initial problem for now.
So even if pressing 'b' still stops the slideshow, PR #7115 solves this issue #7113.

**Comment by quovadit** [comment]
for info: I have now described a preferred behavior of the slideshow as a new feature-request: #7118

**Comment by AlicVB** [comment]
@quovadit : arghhh you say that 'b' stop the slideshow ? I don't even know how that's possible code wise...
To be sure : 
- this doesn't exit the slideshow, right ? this just just prevent the automatic switch to next image ?
- have you reset shortcuts to defaults or redefine the "b" shortcut, as explained ?

**Comment by quovadit** [comment]
it does not exit immediately, but after 5 seconds it exits the slideshow instead of switching to the next image
I did not reset shortcuts, because the shortcut b works - it toggles the border-controls

**Comment by AlicVB** [comment]
yep, but the problem is that what is defined by default is 'B' in upper case, although when you type it, it 'b' in lower case. That doesn't cause problem for "classic" shortcut path (show/hide borders) but that break any comparison between the key released value and the shortcut value...
