### ISSUE TITLE
colorspace problem for monochromes

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#7116]
**Describe the bug**
Opening a true monochrome image in darkroom gives these messages on the console
```
[_transform_matrix] invalid conversion from 0 to 2
[dt_ioppr_transform_image_colorspace] invalid conversion from 0 to 2
[_transform_matrix] invalid conversion from 0 to 2
[dt_ioppr_transform_image_colorspace] invalid conversion from 0 to 2
```

**Expected behavior**
Does not hurt as nothing seems to be broken but at least this one is new since @aurelienpierre s overhaul if this code.

**Platform (please complete the following information):**
dt current master

**Comment by jade-nl** [comment]
Seen these messages before in a roughly(?) similar context: #7080 

That one also shows a message in the GUI, but like yours nothing seems to be really affected.
