### ISSUE TITLE
Scroll issue in duplicate manager in darkroom

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#7120]
**Describe the bug**

We have a little issue in duplicate manager in darkroom on scrollbar.

**To Reproduce**

- create some clones to let appear a scrollbar in that module
- then scroll with mouse wheel by having the cursor over scrollbar. See that scrollbar doesn't stay where you want and come back to the top

To precise, scroll by having the cursor over the module and not scrollbar and scrollbar behavior is ok. I test in some other parts of darktable and seems that only duplicate manager have that issue. I tested with that PR and that issue is reproducible too, as in master.

**Platform (please complete the following information):**
 - Darktable Version: last master
 - OS:  Ubuntu 20.10 with Gnome 3.38.1

**Comment by Nilvus** [comment]
This issue is from a darktable french user. I can reproduce that issue on my side but he precise that he also have that issue if it's mouse cursor is over the module and not over scrollbar as I don't have the issue on my side if my cursor is not over scrollbar. He also use a recent master. Strange!

**Comment by dterrahe** [comment]
#6408 makes scrolling use whole item moves (with the intention of not showing half a duplicate at the top and half a duplicate at the bottom). The gtk scrollbars allow setting step sizes, but they are either ignored or automatically reset, so they cannot be used to achieve this behavior (or at least I didn't manage to). Rather, I overwrote the handling of scrolling in the list itself. And this then fights what the scrollbar insists on doing. I spent quite a bit of time on this and don't have fresh ideas, so would suggest not holding the mouse over the scrollbar while using the scrollwheel. But maybe somebody else would like to have a look at https://github.com/darktable-org/darktable/blob/e75d96d7bb2736f650d95f35581ca8c7ee3b8f52/src/gui/gtk.c#L3152-L3183

It directly uses event->delta_y, so likely needs the same dt_gui_get_scroll_unit_deltas solution as #7108

**Comment by Nilvus** [comment]
Thanks @dterrahe. I personally rarely adds so many clones to have that behavior and already not move cursor over scrollbar. To help you on that maybe, just let know that this behavior is not on other modules with scrollbar and possibility to change module height with ctrl+mouse wheel like all modules in lighttable with that possible behavior: filter collections, keywords, image information... Maybe something on the code there could help for duplicate manager.
