### ISSUE TITLE
filmicrgb and tiling

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#7125]
I noticed this a while back but never got around to mentioning it.

filmicrgb declares itself tilable in flags(), but has no tiling_callback().  So the tiler uses the default_tiling_callback(), which says that memory requirements are only the input and output buffers and there's no overlap.  But from looking at the code, filmicrgb would need to declare that its memory requirements are 7.75 (or even higher) instead of 2.0 (representing in+out buffers), and that it needs a huge overlap.  That means filmicrgb will run out of memory long before the tiler decides to fragment the image.

@aurelienpierre I suspect this is a remnant from before you added highlight reconstruction, and that your preferred solution would be simply dropping IOP_FLAGS_ALLOW_TILING.

**Comment by aurelienpierre** [comment]
Oops, indeed, filmic was tilable as-is before color reconstruction. Will fix.
