### ISSUE TITLE
Slideshow stops when pressing F11

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#7128]
**Describe the bug**
Slideshow stops when pressing F11

**To Reproduce**
1. Start slideshow by pressing 's'
2. Press F11 to switch to fullscreen-mode
3. Slideshow stops

**Expected behavior**
- Slideshow should not stop when pressing F11
- the toast-message 
  - 'end of images. press any key to return to lighttable mode' should be changed to 
  - 'end of images. press ESC to return to lighttable mode'

**Platform**
 - Darktable Version: 3.3.0+1912~g7cbc1371c
 - OS: Manjaro Linux / gnome

**Additional context**
- similar to #7115 (pressing 'b' now works fine)

**Comment by AlicVB** [comment]
hmm... we can solve that like for 'b' but we can't handle all global shortcuts. There would be too many : we can for example add panels hide/show, shortcuts help window, ...
So the only solution I see is - as you propose- to use a special shortcut for exiting. Sadly ESC is already used to exit fullscreen

@TurboGit : I don't know what to do ...

**Comment by quovadit** [comment]
I understand, that there is no quick-fix to handle all shortcuts (for example 'tab' does not work neither).
But F11 is a key-function for a slideshow, so I think this has to work.
The clean solution would be #7118 but for now I would suggest just another 'hack' for F11 like for 'b'

**Comment by TurboGit** [comment]
The slideshow has been design to handle some keys and exit for everything else. So I suppose for F11 we have to special case it like 'b' for borders. There is probably very few key accels that make sense in the slideshow view as there is nothing displayed except the full screen pictures.

**Comment by quovadit** [comment]
@TurboGit : There are some other keys used in the slideshow: +/- to change interval, tab to show/hide sidepanes
Can they also be fixed for 3.4?

**Comment by elstoc** [comment]
For +/- it looks like they were intended to be the +/- on the numeric keypad where available, so it might be working as intended (I can't test having no such keyboard).

**Comment by TurboGit** [comment]
Fixed.

**Comment by quovadit** [comment]
thanks a lot for the extremely quick fix!
