### ISSUE TITLE
Segfault while rearranging module

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7131]
Current master 3.3.0+1914~gf5765768a
WSL Ubuntu

Opened an old edit to redit.
Turned off [revious framing.
Had just finished retouching and needed to crop.
Wanted to move the retouch before crop in the pipeline so that retouch doesn't get screwed up while cropping.
Pressed ctrl+shift followed by click mistakenly for retouch and that enabled the edit box.
Kind of froze for some seconds and then I just clicked around and DT crashed. 

![image](https://user-images.githubusercontent.com/1119439/100561295-80cd5180-32de-11eb-916d-54580989911d.png)

Backtrace attached.

[darktable_bt_IYSPU0.txt](https://github.com/darktable-org/darktable/files/5613394/darktable_bt_IYSPU0.txt)

**Comment by TurboGit** [comment]
I had that one time too and was not able to reproduce. Still cannot reproduce, can you on you side ? Any step by step reproducer ?

**Comment by chhil** [comment]
All the steps I did are listed. I will try and see if it can be consistently reproduced. It's tough because the xmp is overwritten after I restarted and edited it further.

**Comment by chhil** [comment]
I tried ...

Onlly way to get the module to get to rename was ctrl key followed by click which I followed by ctrl+click, but can't crash it any more :(

**Comment by TurboGit** [comment]
> Onlly way to get the module to get to rename was ctrl key followed by click which I followed by ctrl+click, but can't crash it any more :(

That's also my case :( There is something wrong for sure, but I cannot find a reproducer!

**Comment by chhil** [comment]
One weird thing that I can recollect, framing was turned off (initially it was on).
History showed framing on.
Lighttable showed image with frame.
Darkroom showed no frame. 
I had to compress history to get it look correctly with framing off.
Then the edits that led to a crash.

I speculate if its related to framing.

**Comment by chhil** [comment]
It happened again.

Wanted to move retouch down.

Ctrl+click
Got retouch rename enabled.
The tooltip popped up.
Tried to drag it down.
Froze and died.

**Comment by chhil** [comment]
@TurboGit 
Managed to have it die when debugging...

![image](https://user-images.githubusercontent.com/1119439/100616577-4ea00c00-333f-11eb-981c-b44d7f735d9f.png)


```
libdarkroom.so!_on_drag_motion(GtkWidget * widget, GdkDragContext * dc, gint x, gint y, guint time, gpointer user_data) (\home\mchhil\darktable\src\views\darkroom.c:2671)
libgtk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libgobject-2.0.so.0!g_signal_emit_valist (Unknown Source:0)
libgobject-2.0.so.0!g_signal_emit_by_name (Unknown Source:0)
libgtk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libgtk-3.so.0!gtk_main_do_event (Unknown Source:0)
libgdk-3.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libglib-2.0.so.0!g_main_context_dispatch (Unknown Source:0)
libglib-2.0.so.0![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libglib-2.0.so.0!g_main_loop_run (Unknown Source:0)
libgtk-3.so.0!gtk_main (Unknown Source:0)
libdarktable.so!dt_gui_gtk_run(dt_gui_gtk_t * gui) (\home\mchhil\darktable\src\gui\gtk.c:1554)
main(int argc, char ** argv) (\home\mchhil\darktable\src\main.c:93)
```

**Comment by chhil** [comment]
100% reproducible.

Start DT  (I used debugger)
Opens in lighttable.
Double click on image.
You are in darkroom.
In darkroom, first thing to do is try moving a module, and it will segfault.

**Comment by chhil** [comment]
Reproducible on windows too. I had stated earlier it did not happen. The above steps makes it reproducible.

**Comment by TurboGit** [comment]
> 100% reproducible.
> 
> Start DT (I used debugger)
> Opens in lighttable.
> Double click on image.
> You are in darkroom.
> In darkroom, first thing to do is try moving a module, and it will segfault.

This works for me !

**Comment by chhil** [comment]
> This works for me !

So you can reproduce or you cant?

**Comment by TurboGit** [comment]
I can't reproduce.

**Comment by TurboGit** [comment]
> Managed to have it die when debugging...

At the line 2671 in your debugger what is the value for container variable. If it is null I can at least issue a defensive code.

**Comment by chhil** [comment]
![image](https://user-images.githubusercontent.com/1119439/100640337-4efad000-335c-11eb-96f8-67c510049db3.png)

**Comment by chhil** [comment]
Filtered collection for all the tiff files I have and tried on a few, all crashed DT.

Selected a tiff, double clicked on tiff in lighttable.

Darkroom displayed the following for 
enabled modules
![image](https://user-images.githubusercontent.com/1119439/100698431-6bc7ef80-33be-11eb-8d1f-7fc99b5245aa.png)
Initial history
![image](https://user-images.githubusercontent.com/1119439/100698482-8e5a0880-33be-11eb-9de2-27ecf9de23c5.png)
Selected white balance, initial white balance module contents.
![image](https://user-images.githubusercontent.com/1119439/100698507-a6318c80-33be-11eb-83fc-3b67cc6f75c5.png)
Selected eyedropper and this was how the screen looked like before it crashed.
![image](https://user-images.githubusercontent.com/1119439/100698545-bf3a3d80-33be-11eb-9739-430015cb9942.png)

**Comment by chhil** [comment]
If it helps reproducing....

![DTCrash](https://user-images.githubusercontent.com/1119439/100832351-b19fb900-348d-11eb-89e3-0c2e83af9db9.gif)

**Comment by TurboGit** [comment]
Yes it helped ! In fact to reproduce you must drag outside of the panel ! Should now be fixed in master. Thanks for tracking this down.

**Comment by chhil** [comment]
Works for me with currnt master. Thank you.
