### ISSUE TITLE
Segfault while editing tiff file

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7133]
Current master 3.3.0+1914~gf5765768a

WSL Ubuntu.

Tiff , no edit previously.

History.
![image](https://user-images.githubusercontent.com/1119439/100565170-fb02d380-32e8-11eb-819e-30d34950ac6f.png)

Select white balance dropper.
![image](https://user-images.githubusercontent.com/1119439/100564909-45378500-32e8-11eb-92cf-66bbbdcf2142.png)

Segfault

[darktable_bt_RNU4U0.txt](https://github.com/darktable-org/darktable/files/5613629/darktable_bt_RNU4U0.txt)

Repeatable.

**Comment by chhil** [comment]
Works on the same DT version on windows.

**Comment by chhil** [comment]
Debugging in vscode

```
libdarktable.so!_box_size(const int * const box) (\home\mchhil\darktable\src\common\color_picker.c:175)
libdarktable.so!color_picker_helper_4ch(const float * const pixel, const dt_iop_roi_t * roi, const int * const box, float * const picked_color, float * const picked_color_min, float * const picked_color_max, const dt_iop_colorspace_type_t cst_to, const dt_iop_order_iccprofile_info_t * const profile, const dt_iop_buffer_dsc_t * dsc) (\home\mchhil\darktable\src\common\color_picker.c:181)
libdarktable.so!dt_color_picker_helper(const dt_iop_buffer_dsc_t * dsc, const float * const pixel, const dt_iop_roi_t * roi, const int * const box, float * const picked_color, float * const picked_color_min, float * const picked_color_max, const dt_iop_colorspace_type_t image_cst, const dt_iop_colorspace_type_t picker_cst, const dt_iop_order_iccprofile_info_t * const profile) (\home\mchhil\darktable\src\common\color_picker.c:456)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
libdarktable.so!pixelpipe_picker(dt_iop_module_t * module, dt_iop_buffer_dsc_t * dsc, const float * pixel, const dt_iop_roi_t * roi, float * picked_color, float * picked_color_min, float * picked_color_max, const dt_iop_colorspace_type_t image_cst, dt_pixelpipe_picker_source_t picker_source) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:646)
libdarktable.so!pixelpipe_process_on_CPU(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, float * input, dt_iop_buffer_dsc_t * input_format, const dt_iop_roi_t * roi_in, void ** output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, dt_iop_module_t * module, dt_dev_pixelpipe_iop_t * piece, dt_pixelpipe_flow_t * pixelpipe_flow) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1129)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1987)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1329)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1329)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1329)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
libdarktable.so!dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t * pipe, dt_develop_t * dev, void ** output, void ** cl_mem_output, dt_iop_buffer_dsc_t ** out_format, const dt_iop_roi_t * roi_out, GList * modules, int pos) (\home\mchhil\darktable\src\develop\pixelpipe_hb.c:1201)
```

**Comment by jade-nl** [comment]
Confirmed.

**Platform**
* darktable        : 3.3.0+1921 ge75d96d7b
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.6)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0 - clang 10.0.1 - LLVM 10.0.1
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None


Segfault report: [darktable_bt_JPSRU0.txt](https://github.com/darktable-org/darktable/files/5615583/darktable_bt_JPSRU0.txt)

**Comment by TurboGit** [comment]
Any TIFF ? I cannot reproduce !

**Comment by jade-nl** [comment]
I grabbed the first tiff that I came across.

There are so many preferences nowadays, maybe that is of influence here. The 2 major prefs I can come up with and might be relevant are:

- Pixel workflow (*None* in my case),
- Chromatic adaprion (*legacy* in my case).

Just to make sure I tried 3 other tiffs as well: They all segfault.

Here's one more backtrace: [darktable_bt_MFOVU0.txt](https://github.com/darktable-org/darktable/files/5615867/darktable_bt_MFOVU0.txt)

**Comment by TurboGit** [comment]
@aurelienpierre : probably one for you and this may be a regression due to your recent work on color profile, fact is that the white balance module issue lot of error on the console when used on a jpeg or tiff. I have not been able to crash but the reported errors are worrying enough:

```
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
cst 2   pickcst 0
[dt_unreachable_codepath] {unreachable} /home/obry/dev/builds/darktable/build/src/src/common/color_picker.c:467 (dt_color_picker_helper) - we should not be here. please report this to the developers.[dt_ioppr_transform_image_colorspace_cl] 
```

@hlecleme : could also be a regression due to your recent change on color profile blending. ?

**Comment by chhil** [comment]
Tiff and xmp available in dropbox.
https://www.dropbox.com/sh/r3f4nuu8rcg49w0/AAAG1AhetmzF6-MiqxIqjx0qa?dl=0

**Comment by chhil** [comment]
My preferences are different from @jade-nl 
![image](https://user-images.githubusercontent.com/1119439/100611846-fca7b800-3337-11eb-84f7-907e40be13a9.png)

**Comment by maboleth** [comment]
I opened several tiffs on my end, did all sorts of inputs and failed to produce a seg fault.

**Comment by maboleth** [comment]
Also tried your own example with an .xmp file without any segs. 

The file opens normally and can be edited without problems.

**Comment by ptilopteri** [comment]
fwiw: I did not have any problems either, openSUSE Tumbleweed

**Comment by jade-nl** [comment]
@maboleth and @ptilopteri 

Just to make sure: Neither of you mention using the *white balance dropper tool* on the opened tiff file, which is what makes dt crash. Opening and doing other stuff works nicely.

Did either of you actually try just that that?

**Comment by ptilopteri** [comment]
@jade-nl 
I just did w/o a problem.
83d345998

**Comment by maboleth** [comment]
> @maboleth and @ptilopteri
> 
> Just to make sure: Neither of you mention using the _white balance dropper tool_ on the opened tiff file, which is what makes dt crash. Opening and doing other stuff works nicely.
> 
> Did either of you actually try doing just that that?

Oh yes, using white balance d. tool makes it crash.

**Comment by TurboGit** [comment]
Can you test #7143 ?

**Comment by maboleth** [comment]
> Can you test #7143 ?

If that's included in the latest master build, it still crashes for me.

**Comment by ptilopteri** [comment]
while not faulting, I do get some odd control-line output:

[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "ImageDescription" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "Make" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "Model" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "Artist" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
[tiff_open] warning: TIFFFetchNormalTag: ASCII value for tag "ImageDescription" contains null byte in value; value incorrectly truncated during reading due to implementation limitations

and

[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0

and 

[dt_unreachable_codepath] {unreachable} /data/dt-build/darktable/src/common/color_picker.c:464 (dt_color_picker_helper) - we should not be here. please report this to the developers.[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0

**Comment by chhil** [comment]
> Can you test #7143 ?

Crashes.

May help with debugging.
White balance always starts with camera icon selected.
Then use the dropper.
Crashes.
Reopen white balance and now it starts as user defined icon set.
Use dropper and it crashes.

**Comment by chhil** [comment]
> [dt_unreachable_codepath] {unreachable} /home/obry/dev/builds/darktable/build/src/src/common/color_picker.c:467 (dt_color_picker_helper) - we should not be here. please report this to the developers.[dt_ioppr_transform_image_colorspace_cl] 

This gets output because  dt_unreachable_codepath() is executed in color_picker.c due to variables having values

`picker_cst = iop_cs_RAW`
`dsc->filters=0`

```
void dt_color_picker_helper(const dt_iop_buffer_dsc_t *dsc, const float *const pixel, const dt_iop_roi_t *roi,
                            const int *const box, float *const picked_color, float *const picked_color_min,
                            float *const picked_color_max, const dt_iop_colorspace_type_t image_cst,
                            const dt_iop_colorspace_type_t picker_cst,
                            const dt_iop_order_iccprofile_info_t *const profile)

{
  if((dsc->channels == 4u) && ((image_cst == picker_cst) || (picker_cst == iop_cs_NONE)))
    color_picker_helper_4ch(dsc, pixel, roi, box, picked_color, picked_color_min, picked_color_max, picker_cst, profile);
  else if(dsc->channels == 4u && image_cst == iop_cs_Lab && picker_cst == iop_cs_LCh)
    color_picker_helper_4ch(dsc, pixel, roi, box, picked_color, picked_color_min, picked_color_max, picker_cst, profile);
  else if(dsc->channels == 4u && image_cst == iop_cs_rgb && (picker_cst == iop_cs_HSL || picker_cst == iop_cs_JzCzhz))
    color_picker_helper_4ch(dsc, pixel, roi, box, picked_color, picked_color_min, picked_color_max, picker_cst, profile);
  else if(dsc->channels == 1u && dsc->filters != 0u && dsc->filters != 9u)
    color_picker_helper_bayer(dsc, pixel, roi, box, picked_color, picked_color_min, picked_color_max);
  else if(dsc->channels == 1u && dsc->filters == 9u)
    color_picker_helper_xtrans(dsc, pixel, roi, box, picked_color, picked_color_min, picked_color_max);
  else
    dt_unreachable_codepath();
}
```

**Comment by chhil** [comment]
Filtered collection on filename for all tif's. None of them were edited previously, just imported with xmps from a long time ago.

Picked a few tifs and DT crashed everytime.

On double clicking a tif in lighttable :
initial active modules
![image](https://user-images.githubusercontent.com/1119439/100698766-4687b100-33bf-11eb-9742-2aeb3688eadb.png)

initial history
![image](https://user-images.githubusercontent.com/1119439/100698784-530c0980-33bf-11eb-9e39-cb4f95ca2f1e.png)

initial white balance
![image](https://user-images.githubusercontent.com/1119439/100698798-5dc69e80-33bf-11eb-9435-2c2280151359.png)

Now on changing from camera to eyedropper
![image](https://user-images.githubusercontent.com/1119439/100698831-759e2280-33bf-11eb-9c04-79f4f884f20e.png)


DT crashes in a few seconds.

**Comment by chhil** [comment]
> picker_cst = iop_cs_RAW

If I change this value to iop_cs_rgb (just trying to prevent it from getting to the `dt_unreachable_codepath();`)  in  color_picker , it doesn't crash.

**Comment by chhil** [comment]
No more DT crash.

**Comment by TurboGit** [comment]
So that was probably  #7143

**Comment by chhil** [comment]
Yes, clearly anything for picker_cst other than  raw works as it doesn't reach the  unreachable codepath method call.

**Comment by maboleth** [comment]
Works now.
