### ISSUE TITLE
Tags with difference in case (upper and lower) are treated as the same when displaying images but show up differently in the collection filtered by tag  

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7155]
Current master 3.3.0+1942~g67e9d442b

While tagging, I incorrectly created a tag name with different case (**i**nspired... vs **I**nspired...).

So, images+xmp with the uppercase **I**nspired were imported into DT which already had a tag with lowercase **i**nspired

While tagging I cannot select the uppercase **I**nspired (not that I want to select it but it's not available for selection when I do a ctrl+t)

![image](https://user-images.githubusercontent.com/1119439/100825047-39c99280-347d-11eb-86a9-7f598faf1cf4.png)

I see that the collect images with a tag filter shows both (**i**nspired and **I**nspired) of them , but the images being displayed by selecting each of those tags are the sum of both the tags (65 images with tag **i**nspired and 3 images with tag **I**nspired, displays 68 images).

![image](https://user-images.githubusercontent.com/1119439/100824392-14885480-347c-11eb-9a9f-3346bdb37fea.png)

The images displayed should be consistent with what was clicked in the collection->tag
If DT needs to be case insensitive then tags should be normalized to being case insensitive and imports should detect changed case and fix it to be alike.
Ctrl+T currently does not display the 2 cases for a tag present, if it needs to be case insensitive then both all should be displayed.

I also don't understand when tags show up under uncategorized as well as a separate node.
![image](https://user-images.githubusercontent.com/1119439/100825839-f839e700-347e-11eb-935d-844fe33891d7.png)
 

Not here to force a design decision, just stating observations, but whatever design decision is taken, do it consistently.

**Comment by phweyland** [comment]
Ctrl-T seems to work for me, I can select the upper or lower case word:

![image](https://user-images.githubusercontent.com/23012047/101192983-a342d000-363a-11eb-9453-252b5434b156.png)

I confirm the discrepancy between collect view and the displayed images. I'll look at it.

**Comment by phweyland** [comment]
Somebody has added the option "*" in collect for tag ...
This seems to be redundant with "%" and with nothing (because as folders the query adds the character "%").
Could the author explain the reason of this ?

**Comment by TurboGit** [comment]
@phweyland : see issue #6663 and PR #6903 for the motivations.

**Comment by phweyland** [comment]
>  see issue #6663 and PR #6903 for the motivations.

Got it! Thanks
