### ISSUE TITLE
Orientation isn't applied via Ctr+C - Ctrl+V.

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#7157]
If an image hase orientation module enabled, it cannot be copied and applied via Ctr+C - Ctrl+V.

Git master at 3eb2253b956aadfaad885919138174c28b4af3d0 . Linux Mint 20 Mate x64.

With respect,
Alexander Rabtchevich

**Comment by chhil** [comment]
Some modules impact the destination image incorrectly so by default they are not copied now.

![image](https://user-images.githubusercontent.com/1119439/100860358-6c43b180-34b6-11eb-89f5-24c7ef1006f4.png)

You can however do a *`ctrl+shift+c`* and select them to be copied.

**Comment by BigSerpent** [comment]
And how can the orientation corrupt any image?

**Comment by TurboGit** [comment]
Not only corrupted but we have made Ctrl+C copying only **always safe iop** to copy.
