### ISSUE TITLE
Full-size preview unusable to evaluate sharpness

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#7158]
**Describe the bug**
It seems that full-size preview is created by upscaling a low-resolution image: depending on the 'prefer performance over quality' setting, it is either blurry or blocky.
This seems to only occur if with setting `plugins/lighttable/low_quality_thumbnails=TRUE`. I don't know where it can be set on the UI.

**To Reproduce**
1. Develop an image in darktable.
2. Check image zoomed out:
![Screenshot_20201202_064637](https://user-images.githubusercontent.com/3177739/100833478-54ded700-346a-11eb-96a5-4ad08f158efc.png)
3. Check image zoomed in:
![Screenshot_20201202_064702](https://user-images.githubusercontent.com/3177739/100833506-63c58980-346a-11eb-9f8d-5926d4783ca2.png)
4. Return to lighttable
5. Select the same image
6. Press Alt+W
![Screenshot_20201202_065016](https://user-images.githubusercontent.com/3177739/100833697-c3bc3000-346a-11eb-9284-162a0afdc6f7.png)
7. Ctrl+scroll to zoom in
![Screenshot_20201202_065033](https://user-images.githubusercontent.com/3177739/100833743-d6cf0000-346a-11eb-9676-ef1b496e919d.png)
8. Press Alt+W to exit preview
9. Change setting 'prefer performance over quality' to true
10. Press Alt+W to display the preview, then Ctrl+scroll to 100%
![Screenshot_20201201_184404](https://user-images.githubusercontent.com/3177739/100833834-0a118f00-346b-11eb-863d-7dafd11e3b56.png)

**Expected behavior**
Preview (especially if scaled to 100%) has the same quality as darkroom -- otherwise what's the point of being able to zoom to 100%, if sharpness cannot be evaluated?

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1931~g4d0071658
 - OS: Ubuntu 20.10 with KDE
 - OpenCL activated or no? --> OpenCL en/disabled does not change the outcome

**Additional context**
Happens with all my Nikon D7000 raw files. Similar issues are also reported here (with DNG from a Canon camera, I think): https://discuss.pixls.us/t/why-arent-we-utilizing-embedded-previews-more-in-darktable/21291/63

**Comment by kofa73** [comment]
When zooming in, darktable's console output mentions *thumbnail*. The following are all the log lines generated during zoom-in, with command-line `darktable -d opencl -d perf`:
```
1008.196543 [dev] took 0.128 secs (0.147 CPU) to load the image.
1008.372116 [dev] took 0.000 secs (0.000 CPU) to load the image.
1008.558050 [export] creating pixelpipe took 0.094 secs (0.103 CPU)
1008.558128 [pixelpipe_process] [thumbnail] using device 0
1008.561297 [dev_pixelpipe] took 0.003 secs (0.003 CPU) initing base buffer [thumbnail]
1008.582930 [dev_pixelpipe] took 0.022 secs (0.003 CPU) processed `raw black/white point' on GPU, blended on GPU [thumbnail]
1008.587488 [dev_pixelpipe] took 0.005 secs (0.001 CPU) processed `white balance' on GPU, blended on GPU [thumbnail]
1008.591178 [dev_pixelpipe] took 0.004 secs (0.001 CPU) processed `highlight reconstruction' on GPU, blended on GPU [thumbnail]
1008.610085 [dev_pixelpipe] took 0.019 secs (0.012 CPU) processed `hot pixels' on CPU, blended on CPU [thumbnail]
1008.932610 [dev_pixelpipe] took 0.322 secs (0.467 CPU) processed `demosaic' on CPU, blended on CPU [thumbnail]
1009.080125 [dev_pixelpipe] took 0.147 secs (0.119 CPU) processed `lens correction' on GPU, blended on GPU [thumbnail]
1009.082155 [dev_pixelpipe] took 0.002 secs (0.001 CPU) processed `exposure' on GPU, blended on GPU [thumbnail]
1009.086918 [dev_pixelpipe] took 0.005 secs (0.003 CPU) processed `input color profile' on GPU, blended on GPU [thumbnail]
image colorspace transform Lab-->RGB took 0.045 secs (0.050 CPU) [channelmixerrgb ]
1009.491912 [dev_pixelpipe] took 0.405 secs (0.645 CPU) processed `color calibration' on CPU, blended on CPU [thumbnail]
image colorspace transform RGB-->Lab took 0.031 secs (0.057 CPU) [defringe ]
1009.950823 [dev_pixelpipe] took 0.459 secs (0.815 CPU) processed `defringe' on CPU, blended on CPU [thumbnail]
image colorspace transform Lab-->RGB took 0.005 secs (0.002 GPU) [filmicrgb ]
1009.974639 [dev_pixelpipe] took 0.024 secs (0.011 CPU) processed `filmic rgb' on GPU, blended on GPU [thumbnail]
image colorspace transform RGB-->Lab took 0.004 secs (0.004 GPU) [colorout ]
1009.984749 [dev_pixelpipe] took 0.010 secs (0.009 CPU) processed `output color profile' on GPU, blended on GPU [thumbnail]
1010.026830 [dev_pixelpipe] took 0.042 secs (0.065 CPU) processed `display encoding' on CPU, blended on CPU [thumbnail]
1010.026863 [opencl_profiling] profiling device 0 ('GeForce GTX 1060 6GB'):
1010.026875 [opencl_profiling] spent  0.0185 seconds in [Write Image (from host to device)]
1010.026883 [opencl_profiling] spent  0.0001 seconds in rawprepare_1f
1010.026889 [opencl_profiling] spent  0.0001 seconds in whitebalance_1f
1010.026896 [opencl_profiling] spent  0.0002 seconds in highlights_1f_lch_bayer
1010.026902 [opencl_profiling] spent  0.0460 seconds in [Read Image (from device to host)]
1010.026908 [opencl_profiling] spent  0.0255 seconds in [Write Buffer (from host to device)]
1010.026914 [opencl_profiling] spent  0.0004 seconds in lens_vignette
1010.026919 [opencl_profiling] spent  0.0020 seconds in lens_distort_lanczos3
1010.026926 [opencl_profiling] spent  0.0003 seconds in exposure
1010.026932 [opencl_profiling] spent  0.0004 seconds in colorin_unbound
1010.026937 [opencl_profiling] spent  0.0006 seconds in [Copy Image (on device)]
1010.026943 [opencl_profiling] spent  0.0003 seconds in colorspaces_transform_lab_to_rgb_matrix
1010.026949 [opencl_profiling] spent  0.0002 seconds in filmic_mask_clipped_pixels
1010.026955 [opencl_profiling] spent  0.0003 seconds in filmicrgb_chroma
1010.026961 [opencl_profiling] spent  0.0003 seconds in colorspaces_transform_rgb_matrix_to_lab
1010.026966 [opencl_profiling] spent  0.0007 seconds in colorout
1010.026972 [opencl_profiling] spent  0.0957 seconds totally in command queue (with 0 events missing)
1010.026994 [dev_process_thumbnail] pixel pipeline processing took 1.469 secs (2.155 CPU)
```

**Comment by TurboGit** [comment]
> It seems that full-size preview is created by upscaling a low-resolution image: depending on the 'prefer performance over quality' setting, it is either blurry or blocky.

Reviewing the code I agree this is what is happening and that's actually expected after all. You asked for performance over quality, you have a lesser quality. Seems expected after all.

**Comment by kofa73** [comment]
The setting does not influence everything (e.g. exports). Its exact scope cannot be judged easily.

Since it makes no sense to view the _full preview_ at 100% zoom that upsampled form a low-resolution image, if possible, one of the following would be a better solution:
- ignore the setting in the lighttable _full preview_ completely;
- ignore it at 100% zoom
- display a warning saying this preview is not representative of image quality because of the setting being active.

An update to the documentation may be in order, too.

The tooltip says 'if switched on, _thumbnails_ and _previews_ are rendered at lower quality but 4 times faster'. Unfortunately, _preview_ is a term that's used for multiple things.

I thought the setting only affected the preview in the _darkroom_ ('On the top left hand side the navigation panel displays a full _preview_ of your image with a rectangle showing the currently visible zoom area in the central panel.' Regarding the histogram: 'For the purposes of speed, the scopes are calculated from the image _preview._ This is the image which is displayed in the navigation panel, rather than the higher quality developed image which is displayed in the center view. The _preview_ is calculated at a lower resolution and may use shortcuts to bypass time-consuming image processing steps.').

Also, when speaking about the _lighttable,_ only _'full preview'_ is mentioned; the usage of the word _'full'_ suggested to me it was always a _full-size, fully processed_ image.
Truth be told, _full_ is also used in the description of the _darkroom,_ 'the navigation panel displays a _full preview_ of your image with a rectangle showing the currently visible zoom area', but there it's obviously a small image, and _full_ only means that you get an overview of the whole image. 
In the lighttable, thumbnails already show the 'full' (whole) image, so it never occurred to me that _full_ there was not used for _full-size_ or _fully-processed_.

**Comment by AlicVB** [comment]
here's where the setting is initialized in the code : https://github.com/darktable-org/darktable/blob/3b9113709775247e87feadd8f2cc8a2027598af2/data/darktableconfig.xml.in#L879-L885
So, in fact, this is not the "prefer performance over quality" setting
You can also notice that the problem is not upscaling but the method to compute the image in the pipe.

Now you seems to want some different settings, depending of the size of the image (bad quality for small thumbnails but high quality for big images) that could eventually be done at some point, but it's not implemented yet

**Comment by kofa73** [comment]
@AlicVB Yes, correct. I was too tired and got confused.
So, it seems there are two settings at play:
- `plugins/lighttable/low_quality_thumbnails` causes darktable to create a low-res thumbnail (and preview)
- 'prefer performance over quality' (is that `ui/performance`?), which only affects whether the upscaled image will be soft or blocky.

It'd be nice to document the consequences of enabling `low_quality_thumbnails` (it's not in the manual, and not many people will read `darktableconfig.xml.in` or the generated file `darktablerc.html` -- I didn't know about them, so didn't read them, either). I understand that most people (given that `low_quality_thumbnails` is not exposed on the UI) would not encounter this issue -- I probably only have it because of my old machine with slow CPU and low RAM. I don't know when I added it (or how it got into my config).

More options add to the confusion:
- `plugins/lighttable/thumbnail_hq_min_level`, [documented as](https://github.com/darktable-org/darktable/blob/3b9113709775247e87feadd8f2cc8a2027598af2/data/darktableconfig.xml.in#L886-L904) 'if the thumbnail size is greater than this value, it will be processed using the _full quality rendering path_ (better but slower)' - I have this at the default value, 720p, but it seems `low_quality_thumbnails` takes precedence.
- `never_use_embedded_thumb` (don't use embedded preview JPEG but **half-size raw**): _Check this option to not use the embedded JPEG from the raw file but process the raw data. This is slower. (default off)._ So, to generate the thumbnail, either the JPG is used, or a half-size raw (combining RGBG instead of demosaicing, I guess). Does then `plugins/lighttable/low_quality_thumbnails` reduce it further? Or does `never_use_embedded_thumb` affect lighttable thumbnails, but not previews, while `low_quality_thumbnails` affects both thumbnails and previews?
