### ISSUE TITLE
embedded jpeg not used for zommed preview

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#7162]
**Describe the bug**
With setting "use embedded jpeg, when zooming inside a full preview image we always recreate the image with the full pipe, even if the full preview image is large enough.

I have traced the origin of the problem, but sadly, I've not the solution...

As soon as you zoom inside a full preview (same for culling)
1. this start in `dtgtk/thumbnail.c:1712` : we need to know the final size of the image to get the zoom limits
2. this call `common/image.c:602`
3. this call `develop/develop.c:724`
4. this call `develop/develop.c:2027`
5. this call `develop/develop.c:1993` (somewhere after)
6. this call `common/history.c:1413` and remove flag `DT_HISTORY_HASH_BASIC` in favor of `DT_HISTORY_HASH_AUTO`

At this point, as we test for `DT_HISTORY_HASH_BASIC` to load the embedded preview or not (`common/mipmap_cache.c:1157`) we switch to the full pipe instead...

So I'm not sure what to do... taking account of auto applied presets to get the final imagesize seems legitimate, as some can have presets that change the final size. On the other hand, if we go that way, we should never load embedded previews...

The simplest solution would be to revert to testing `DT_HISTORY_HASH_BASIC` or `DT_HISTORY_HASH_AUTO` in mipmap_cache, but I'm not sure of the problems it can cause...
@phweyland : git blame says you are the one that have changed that, so you may have some hint...

**Platform (please complete the following information):**
 - Darktable Version: latest master https://github.com/darktable-org/darktable/commit/30e1b5e74f88803ba3576cfcbfacf990ec02e68b
 - OS: xubuntu 20.04
 - OPENCL : no matters

**Comment by parafin** [comment]
Do we really care for this feature (using embedded jpegs)?..

**Comment by Nilvus** [comment]
> Do we really care for this feature (using embedded jpegs)?..

I think yes, we need to take care of that. I've had for example used a long time an old laptop (a 2013 Macbook pro used on Linux) and zoomed preview was slow with full pipe recomputed to display processed raw.
Personally, I now don't care about that one since september where I buy a new powerful computer but having the possibility to see/compare images with embedded jpg for users who still have an old computer is a good thing.

**Comment by AlicVB** [comment]
yes, it's really faster.
On the other hand, I have remove that pref on my "stable" build because of the difference between embedded jpeg and dt rendering. That avoid too many surprises... (but I have a quite decent computer)
