### ISSUE TITLE
Fails to build with Perl 5.32

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#7163]
**Describe the bug**

After the release of perl 5.32 Darktable can no longer be build on distros using this version of Perl since darktable uses Pod::Parser for building documentation which has been removed from Perl 5.32.
See detailed explanation and a patch for Darktable 3.2.1 on the FreeBSD bug tracker here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248541

**Comment by parafin** [comment]
If I read the linked bug report correctly it was just about adding a missing build dependency. So what do you want to be changed in darktable itself? Amend some documentation about build process or what?

**Comment by mir07** [comment]
> If I read the linked bug report correctly it was just about adding a missing build dependency. So what do you want to be changed in darktable itself? Amend some documentation about build process or what?

Since the build scripts is part of Darktable itself and if the fix is a matter of a missing build dependency I would expect that the build script (CMakeLists.txt) would be fixed so that it checks for the installed version of Perl and add the needed dependencies for Perl < 5.32 and Perl >= 5.32.

**Comment by parafin** [comment]
Build script doesn’t install dependencies, but sure, it should probably check them. Though it won’t change much - building will just fail at a different place (earlier) - configuring instead of compilation. So it’s a very minor issue IMHO.

**Comment by mir07** [comment]
You completely missed the point and it sounds like you are in over your head.

**Comment by ptilopteri** [comment]
and that will undoubtedly get all of the developers up onto the edge
of their chairs looking for a solution.

perhaps you should close this issue.

**Comment by mir07** [comment]
1) Perl 5.32 is the current stable Perl 5 version
2) All non-frozen Linux distribution is now Perl 5.32 based
So your claim is that unbuildable on any current Linux distribution is of no concern to the developers?

**Comment by ptilopteri** [comment]
#1 perl-5.32.0 here
#2 ok
I don't believe I made any claim about build status, but did comment about 
your assessment of parafin's abilities.

fwiw: I currently build locally master several times a day with little or 
no problem on several boxes using the build parameters provided on
darktable.org, which would belie your statement about the current ability 
to build dt..

but I do not build 3.2.1.
and 3.2.1 will be upgraded/updated very shortly to 3.4

take a deep breath, be happy

**Comment by parafin** [comment]
How it's not buildable if you only need to install textproc/p5-Pod-Parser? Dependency installation isn't handled by cmake (CMakeLists.txt), so I think it's you who is in over your head. Just saying.

**Comment by chhil** [comment]
I am currently on WSL Ubuntu
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

Uses Perl v5.30.0 hence don't see any build issues (I don't build docs either). 

Maybe just a blurb somewhere that DT requires a certain verion of Perl to build (or to build documentation if the case may be) and a version check that fails more gracefully if the prerequisite is not met.

**Comment by parafin** [comment]
It works with perl-5.32.

**Comment by mir07** [comment]
For others reading this: To be able to build on current Debian you need to install libpod-parser-perl.

**Comment by parafin** [comment]
So it probably should be added to the documentation about building the dt from sources (not sure where it is currently). And maybe someone will implement a check for that in cmake, though I don't see any interested developers to do it.

**Comment by TurboGit** [comment]
I have added this in our wiki: https://github.com/darktable-org/darktable/wiki/Building-darktable
