### ISSUE TITLE
Tooltips not shown

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#7164]
**Describe the bug**
The text fields in the "collect images" module should show some tool tips, which are not visible in current git master.

**To Reproduce**
Mouse hover over the text fields, see screenshots.

**Expected behavior**
Visible tool tips with some user help about valid search parameters.

**Screenshots**

Expected behavior as  in 3.0.1:

![dt_3 0 1](https://user-images.githubusercontent.com/1159508/100924449-eee16680-34e0-11eb-8c8f-98096b3ddf7d.png)

Actual behavior in current git master: 

![no_tooltip](https://user-images.githubusercontent.com/1159508/100924458-f274ed80-34e0-11eb-995a-f2b1a3c10466.png)

**Platform (please complete the following information):**
 - Darktable Version: git master
 - OS: Ubuntu x64

**Comment by ptilopteri** [comment]
3b9113709 compiled on openSUSE Tumbleweed
and I see the tool tips.  there is a short cut to toggle on/off
have you tried it
<shift><t>

**Comment by rabauke** [comment]
Thanks for this hint. Obviously I hit Shit+T accidentally. Not a bug.
