### ISSUE TITLE
Yes/No dialog on delete image one cannot tell which button has focus and hence using enter key is unsafe.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7169]
When you hit delete key on an image (say the first one in the top left of window) in lighttable a no/yes dialog box pops up.

![image](https://user-images.githubusercontent.com/1119439/100970969-10cbff00-355c-11eb-871c-c2b5cdbb7bc8.png)

There is no way to see which option will be selected when one hits the enter.

On hitting enter one realizes the *`no`* was the one where the focus was on. 

Now when the yes/no dialog pops up and one uses the right arrow key, we still cannot see which button the focus is on. In this case it was on yes, and hitting entered deleted it. Using the mouse would be safest.

Is this a css related issue? I use the darktable-icon theme provided by DT.

I also changed it to the darktable-grey-icon theme but still which button had focus was not visible.

WSL Ubuntu 20, current master.
Same visual behavior on windows.

**Comment by elstoc** [comment]
@Nilvus: This looks like a simple CSS change.

```
messagedialog .default { background-color: red; }
```

![Screenshot_2020-12-03_09-04-48](https://user-images.githubusercontent.com/9555491/100987618-a6f52a80-3546-11eb-8d76-9ee93fb67f3a.png)

**Comment by Nilvus** [comment]
Interesting, I indeed never thought there was a button with focus on those pop-ups. But I never used keyboard for that. As they have a focus, of course, this need to be shown. Thanks @elstoc for pinging me and make my work easier with the CSS tag ;-)! The good color will be a color consistent with existing selected colors (a sort of clear grey). Will propose this day a PR to fix that.

Thanks @chhil for posting that issue. Another improvement to the UI to come!
