### ISSUE TITLE
All white balance presets for Canon EOS Rebel SL2 / 200D

### ISSUE THREAD

**Issue by hodapp512** [darktable-org/darktable#7175]
I am using the camera marketed as Canon EOS Rebel SL2.
I used the "Finetuned (properly)" instructions from [here](https://github.com/darktable-org/darktable/wiki/White-balance-presets).
[darktable-whitebalance-20201203.tar.gz](https://github.com/darktable-org/darktable/files/5637855/darktable-whitebalance-20201203.tar.gz)

**Comment by johnny-bit** [comment]
Hi!

Files `IMG_2922.CR2`...`IMG_2940.CR2` specify WB as "Auto (ambience priority)" so those can be ignored :)
