### ISSUE TITLE
Not possible to define areas to be retouched

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#7181]
**Describe the bug**
Unable to add shapes in Retouch.

**To Reproduce**
1. Open Retouch module
2. Select Circle
3. Circle appears in the middle of the screen (same with ellipse)
4. When you move your mouse it doesn't follow it. When you click a point on the screen (either left or right) the circle moves there, but it never define the area that should be retouched.

**Expected behavior**
The shape follows the cursor and attaches to the point what is clicked.

**Screenshots**
–

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0-1962
 - OS: Win10

<Edit>

**Additional information**
Also, it's not possible to create a drawn mask in other modules (noticed in Color calibration).

**Comment by ralfbrown** [comment]
Works just fine here (both Retouch and shapes in Color calibration).  Linux, dt 3.3.0+1963.
Maybe this is something Windows-specific?

**Comment by chhil** [comment]
Cannot reproduce on current master for linux and windows.

**Comment by juhavlintula** [comment]
Works also on 1962 after I restarted dt. Sorry for wasted effort as I was too fast to submit a bug report.
