### ISSUE TITLE
darktable loops when assigning invalid xmp

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#7185]
if a invalid xmp file (e.g. a simple text file) is assigned to an image using history stack -> load sidecar file

**To Reproduce**
1. Select image
2. load invalid xmp file via "history stack" --> load sidecar file ... 
3. confirm error message
4. darktable never returns ...
-->

darktable -d all keeps printing:
```
142.467069 [camera_control] loaded 11 port drivers.
142.556936 [camera_control] 0 cameras connected
146.655600 [camera_control] loaded 11 port drivers.
146.754695 [camera_control] 0 cameras connected
150.850751 [camera_control] loaded 11 port drivers.
150.939672 [camera_control] 0 cameras connected
155.026715 [camera_control] loaded 11 port drivers.
155.121596 [camera_control] 0 cameras connected
159.215657 [camera_control] loaded 11 port drivers.
159.308337 [camera_control] 0 cameras connected
163.414473 [camera_control] loaded 11 port drivers.
163.517245 [camera_control] 0 cameras connected
```

**Platform (please complete the following information):**
 - Darktable Version: this is darktable 3.3.0+1966~g191815f9b
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
 - OS: OSX 11.0.1

**Comment by TurboGit** [comment]
> darktable -d all keeps printing:

This is ok, there is a busy loop looking for new card inserted or camera being connected. This is because of the reword of the import module.

**Comment by MStraeten** [comment]
I can’t imagine an endless loop to be ok. The only way to terminate darktable is killing the process...
I‘d rather expect it simply returns to a state where the user can take over control and continue using darktable.

**Comment by parafin** [comment]
-d all output doesn't indicate a problem, but a problem still exists

**Comment by MStraeten** [comment]
The output is repeated until darktable is killed - maybe it’s an indication where the loop occurs ...

**Comment by parafin** [comment]
I doubt it, since it is repeated during normal operation too. Something else is stuck IMHO.

**Comment by jenshannoschwalm** [comment]
It's a backtread which is terminated in a controlled way whe terminating dt.

**Comment by TurboGit** [comment]
Should be fixed.
