### ISSUE TITLE
From fit to screen to 50% does not work for one image.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7186]
Current master. WSL Ubuntu.

Image is cropped heavily.

Its fit to screen currently.
Try to change it to zoom in 50%,. You will notice that its "working..." but does not change to 50% and the box where 50% should show still shows fit to screen

Now if I zoom in using 100%, it goes to 100% and then I can then zoom to 50% though the image show as fit to screen as you can't see scrollbars.

![Zoom](https://user-images.githubusercontent.com/1119439/101155684-7b109c80-364d-11eb-87b2-610be669b54b.gif)

**Comment by TurboGit** [comment]
Works for me ! Maybe with the crop your 50% is equivalent to fit to screen ?

**Comment by chhil** [comment]
I thought that could be the case  when going from 100 % to 50% displayed the image without scrollbars and that's how it would look in fit to screen. 

But look at the image top left, it's the cropped image so it should ideally be able to do 50% of the displayed image or any percentage ?

**Comment by johnny-bit** [comment]
I've tried and cannot confirm... Do you have issue with one particular image out of many or is it somehow replicable in specific circumstances?

**Comment by chhil** [comment]
This was one image with a sizeable crop. Currently cannot reproduce. Closing.
