### ISSUE TITLE
hide_header_buttons/active errors

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7190]
When choosing "active" from the darkroom preference "show right-side buttons in processing module headers" and entering the darkroom, the header buttons are initially shown for _all_ modules. They are automatically re-hidden after you've hovered the mouse over them once.

[header_btns.zip](https://github.com/darktable-org/darktable/files/5645272/header_btns.zip)

darktable 3.3.0+1977~gde6f4f817

ArchLinux

**Comment by elstoc** [comment]
Ping @dterrahe.

**Comment by dterrahe** [comment]
a5829cf6c13b986d9c30f0ae50301cda66092628, cherrypicked from #7199, fixed this. The rest of that PR is just some additional refactoring cleanup but not required to close this. @elstoc maybe consider closing this bug manually if you're happy? Thanks!

**Comment by elstoc** [comment]
ok thanks
