### ISSUE TITLE
Export String no longer works...string variables seem to be ignored

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#7196]
Running a recent build on Win 10  DT-0b53b80-dirty

The following "bash" string has always worked to export jpg edits to a parallel folder. Raw files are in parent folder DT_Photos and exported edited files are in DT_PhotoEdits.  The subfolder structure is mirrored date-event. This string normally exports to the exact same sub folder as the original but in the "Edits" root folder.  "$(FILE_FOLDER/otos/otoEdits)/$(FILE_NAME)-edited"

Now it seems to ignore that string and save it in the original folder with the raw file??

Not sure if this is more widespread but I thought I would report incase it was....

**Comment by johnny-bit** [comment]
Tried to replicate - On linux it works flawlessly.

**Comment by johnny-bit** [comment]
I've finally checked on win10...

WORKS! 

Works flawlessly on dt 3.4.1.1 on win10 update 21h1

**Comment by johnny-bit** [comment]
screenshot proof:

![Zrzut ekranu (6)](https://user-images.githubusercontent.com/10687765/122389188-f8a85400-cf70-11eb-895c-e619f0a22a80.png)

if you don't mind - closing :)
