### ISSUE TITLE
[idea] speedup thumbnail generation

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#7204]
If we don't want to use the embedded preview, which are not really accurate, the thumbnail generation is not so bad actually, but I think that there's room for improvements. the dream goal would be to get something so quick, that embedded preview wouldn't be necessary anymore !
here are some random ideas to speed-up the process. I can do some, but some other are out of my capacities...
Keep in mind that I only speak about "virgin" images here.

### Enhance what is already in place
1. we already have `plugins/lighttable/low_quality_thumbnails` but this is applied for all size. We can imagine to do same things than `plugins/lighttable/thumbnail_hq_min_level`. maybe even only use this pref to do both things.
2. apparently we create and initialize all the pipe for each thumbnail generation. We can maybe save some time if we reuse them, like we do in darkroom when switching to another image.

### Create thumb at import
1. we could add an option to create the thumbnail when we do the import.
2. this doesn't have to create *all* thumbs, but just one at a settable size. The lower ones can be compute from this one (really quick) and the greater ones will be compute like before
3. I know the commandline tool to generate thumbnails, but I see this as a complement. Not to speak about beginners (even more if they are not on linux)...
4. this could be done once all the image infos are imported or at the same time (maybe we can save some time doing all in one step)

### optimize pipe
1. for most of us, thumbnails don't require the same quality processing as big images (all this should be desactivated for those who want high qual thumbnails)
2. maybe we can skip some iop for thumbnails (I have in mind highlight reconstruction, sharpen, ...)
3. maybe some mandatory iop can have some special processing or settings to speed up the process ? (here, I'll let @aurelienpierre or other give their opinion, I'm not sure it's feasible)

Don't hesitate to share your thought. Maybe this won't be possible, but maybe we can enhance things in this area ;)

**Comment by johnny-bit** [comment]
You say "virgin" images, but I think "processed" images would benefit from "better" thumbnail generation ;) see https://github.com/darktable-org/darktable/issues/4192 :)

**Comment by Nilvus** [comment]
I agree that thumbnail generation should be improved.

I'm on to allow (a setting should be added to allow the user in new parameters in import module) generate a main thumbnail at import. All in one step.

About existing processed ones, it's a good idea to skip some iop for thumbnails and I would add denoise ones to skip. But we can't skip any modules for 100% preview as generally if we want to show it at 100% is to see final rendering better.
