### ISSUE TITLE
It's not possible to choose the 3D lut folder

### ISSUE THREAD

**Issue by amagius** [darktable-org/darktable#7206]
Hi!
The guide says: _Before using the module you must define the folder where you have stored the LUTs you like. This folder can have sub-folders. This is done selecting the correct 3D lut root folder in Configuration/Core options/Miscellaneous._
The image below shows that there is no possibility to choose the folder.
I have installed darktable 3.2.1 windows 10 64bit
How can I solve? Thanks
Excuse my english
![No choice folder 3D Lut](https://user-images.githubusercontent.com/75548811/101267183-62d87480-3756-11eb-9c47-652bfa2e4a26.jpg)

**Comment by elstoc** [comment]
I'm not sure which guide you're looking at but the current draft user manual (https://darktable-org.github.io/dtdocs/module-reference/processing-modules/lut-3d/) has the correct location. It's in preferences > processing.

The preferences layout was rewritten in darktable 3.2 but the official user manual hasn't yet caught up.

**Comment by amagius** [comment]
Found!
Applied the path in preferences > processing, restart darktable. **It works!**
The guide I looked at was this (https://www.darktable.org/2019/05/New%20module-lut3d/)
Thank you very much elstoc.
Merry Christmas

**Comment by Nilvus** [comment]
@amagius: so think about closing that issue to help us know which issues remains to work on. Manual in darktable.org is quite old and will be updated with the 3.4 coming in Christmas.

**Comment by Nilvus** [comment]
Last thing, the article you point is not the manual. And as you can see, capture screen is not the same. Preferences have been completely reworked for 3.2.1 this year. The article is dated on 2019, so capture screen is from older preferences.

**Comment by amagius** [comment]
Thanks for the info. 
For my problem the solution has been found. I close the issue.

**Comment by miguehm** [comment]
I've definided my Lut 3D root folder on preferences > processing (I'm using .cube files), restart darktable and it does not work
I'm using dark table 4.6.0 installed via flatpak on archcraft 6.5.9-arch2-1

**Comment by miguehm** [comment]
I've defined my root folder Lut 3D in preferences > processing (I'm using .cube files), I restart darktable and it doesn't work
I'm using dark table 4.6.0 installed via flatpak on archcraft 6.5.9-arch2-1
