### ISSUE TITLE
Some Canon mRAW files much darker right after import than after 'discard history'

### ISSUE THREAD

**Issue by slimjim800** [darktable-org/darktable#7207]
**Describe the bug**

Some (and it seems to me, not all) of the mRAW files I've been working with from my Canon 70D appear unusually dark on import, but they appear to have a more normal brightness profile after editing the original, duplicating, and then choosing to 'clear history' on the duplicate. 

**Screenshots**
Here is an image that I imported, worked on, and duplicated. You see it here back at the stage in the history stack where no edits have been made. It is very dark.
![dt-dark](https://user-images.githubusercontent.com/75549667/101267884-d022e000-372b-11eb-97e9-790f248bd658.png)

Here is the same source file as before, duplicated in lighttable, and without edits. It is visibly brighter than how it appeared directly after import (notice that both images are shown after exactly 7 steps in the history stack)
![dt-after-duplicating-discarding](https://user-images.githubusercontent.com/75549667/101267885-d618c100-372b-11eb-8f18-3cd21188b00e.png)

**Expected behavior**

I would expect the rendering shown in the second image to be more typical

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Fedora Workstation 32
 - OpenCL is not active (I haven't even installed OpenCL drivers for my AMD card)
 - SW acquired from Fedora package manager

**Additional context**
I have not seen this on any JPG images thus far. I do not know yet if this happens on full size RAW or on images from other cameras.

Please let me know if I can provide any other information!

**Comment by slimjim800** [comment]
I've been able to correlate the "dark image" appearance with the "input profile" being set to "sRGB" instead of "standard color matrix" on some of these Canon RAW files. I have never deliberately made any modifications to any item in the "input color profile" module.

I do not know why some of these images are set to sRGB. I'm happy to answer any more questions that would support troubleshooting and of course I'll report back with any further findings.

**Comment by johnny-bit** [comment]
This is known bug, fixed in master. Bug happens sometimes, usually when switching from jpeg to raw. In less than 20 days we'll have new release. If you can't test current master, then you can wait for new release :)

**Comment by slimjim800** [comment]
Thank you kindly for the response! I'll be looking forward to the new release :)
