### ISSUE TITLE
Shortcuts for brightness in lowpass module doubled

### ISSUE THREAD

**Issue by vertama** [darktable-org/darktable#7212]
Shortcut settings in preferences are doubled for lowpass -> brightness.

**To Reproduce**
1. Go to 'darktable preferencess'
2. Click on 'shortcuts' tab
3. Expand 'processing modules' -> 'lowpass' -> 'brightness'
4. See two lines for all settings.

**Expected behavior**
Only one line for each settings like other modules.

**Screenshots**
https://imgur.com/83nmo0G

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1883
 - OS: Ubuntu Linux 20.04.1

**Comment by Nilvus** [comment]
I don't have that on 3.3.0+1993~ga5829cf6c. All is good in those shortcuts. As you can see, you are 110 commits late. I suggest you to update your master.

**Comment by vertama** [comment]
That was it, it's fixed on 1993. Thanks.
