### ISSUE TITLE
Problems with orientation module and history

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#7213]
**Describe the bug**
After compressing history stack, a new step for orientation will be added, so that two steps of orientation appear in the stack. Clicking again on compress history stack removes the first step of orientation. But in a new edit (leaving darkroom an loading the picture again into darkroom) a second step will be added again, after pressing compress history stack.

The reason for this is, that the module orientation will be switched off, after loading the picture in the darkroom.

**To Reproduce**
- load an fresh image into darkroom  -> orientation appears in the history as step 9, but the module is inactive!
- press "compress history stack" -> orientation will be activated (why?) and appears as step 1 (why?) and as step 10.
- press "compress history stack" again -> orientation at step 1 will be removed. The module is still active.
- leave the darkroom an enter it again for the same picture. -> orientation appears in the history as step 9, but the module is inactive!
- change module order from legacy to v3.0 -> orientation will be activated and appears as step 1 (why?) and as step 10. Step 10 becomes the active Step in the history and step 11 (base curve) is not executed.

**Expected behavior**
After loading an image into the darkroom in which the orientation module was not activated, the module must not appear in the history or has to be deactivated the last occurrence.
If the orientation module has more than one occurrence, the **first** press of compress history will remove all occurrences before the last one.

**Platform (please complete the following information):**
 - Darktable Version: current git version: 3.3.0+1993-ga5829cf6c-dirty
 - OS: Linux Ubuntu 18.04.5
 - OpenCL activated

**Additional context**
Any picture can be used to reproduce the bug. JPGs too. Version 3.2.1 works as expected.

**Comment by TurboGit** [comment]
I can reproduce, indeed step for a fresh edit it should be activated.
