### ISSUE TITLE
Noise profiles for Sony A7C.

### ISSUE THREAD

**Issue by sbradl** [darktable-org/darktable#7217]
The A7C has the same sensor as the A7III. On my system I just copied the entry in the json file and tried the denoising. Looks perfect to me. Maybe you can add this to the source.

[A7C-noise-profile-copy-from-A7III.txt](https://github.com/darktable-org/darktable/files/5648821/A7C-noise-profile-copy-from-A7III.txt)

**Comment by JonDum** [comment]
@sbradl I tried adding this entry to `/Applications/darktable.app/Contents/Resources/share/darktable/noiseprofiles.json` on 3.4.0 release on MacOS and had bad (e.g. mega smoothed) results with the `denoise (profiled)` plugin.

Did I do something wrong? Is that the right spot to add it?

**Comment by sbradl** [comment]
@JonDum Not sure if this is the right spot. I start darktable via command line like this:
`darktable --noiseprofiles noiseprofiles.json`

When you enable the denoise module, does it tell you that it found a matching profile?

**Comment by JonDum** [comment]
@sbradl I ran 
```
/Applications/darktable.app/Contents/MacOS/darktable --noiseprofiles /Applications/darktable.app/Contents/Resources/share/darktable/noiseprofiles.json
``` 

which revealed this error:

```
[noiseprofile] error: '/Applications/darktable.app/Contents/Resources/share/darktable/noiseprofiles.json' is not a valid noiseprofile file. run with -d control for details
``` 
in the stdout.

Turns out I had a rogue character messing up my JSON and fixing that made the profiles show up!

Thanks for the help.

For any less techy people coming across this thread:

Here's the full noiseprofiles file (from v3.4.0) that you can drop in to get support.

[noiseprofiles.json.zip](https://github.com/darktable-org/darktable/files/5745457/noiseprofiles.json.zip)

For MacOS you would copy this too `/Applications/darktable.app/Contents/Resources/share/darktable/noiseprofiles.json`.

**Comment by sbradl** [comment]
@JonDum glad it works now 

But beware I am not 100% sure the profiles are correct. I just thought that if the sensors are the same then the profiles could be reused. But even if the sensors are the same the curcuits around it are maybe not which could lead to a different noise behaviour.
For me it looks fine though

**Comment by rawfiner** [comment]
Even though the sensors are the same, I prefer not copying profiles from one camera to another. I don't know how the firmware of the camera has changed between cameras, and that may affect the amount of noise, and thus the profiles.

**Comment by sbradl** [comment]
No problem. I will just use the copied profiles until someone creates new profiles. I cannot do it because I don't have a printer

**Comment by agoode** [comment]
It looks like the raw samples are on raw.pixls.us for ILCE-7C.

Does anything else need to be done to get this profile into the distribution? I have this camera so I can help if necessary. Thanks!

**Comment by rawfiner** [comment]
@agoode the samples on raw.pixls.us are not sufficient to create noise profiles
You can follow this guide to create the profile:
https://pixls.us/articles/how-to-create-camera-noise-profiles-for-darktable/
Thanks!

**Comment by rawfiner** [comment]
Wait... actually we already have the noise profile for the ILCE-7C since 94310d65eabd0ae9cad54716854ea4dbb03e3f20
So closing the issue :-)
