### ISSUE TITLE
Buttons lose alignment/size when imported style name text is extra-long in lighttable view

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7230]
Current master

Imported styles from dtstyle.

1. Some style names are pretty long causing the buttons to lose alignment and position and cannot drag left marging after a point to display all content. The image below is after dragging left margin to whatever maximum is allowable for the right pane. 

![image](https://user-images.githubusercontent.com/1119439/101444436-831a5600-3945-11eb-9017-6d153b4f2f9c.png)

2. Selecting all styles can only be done by selecting a style and then doing a shift+down arrow, no ctrl+a available to select all.

3. On selecting all and then clicking the remove button does not remove styles that have a pipe "|" character in them to display its tree structure. The subtree needs to be deleted for them to be removed.

4. Removal of styles does not fix the allignment issue until DT is restarted.

**Comment by dterrahe** [comment]
This will be fixed by #7140 (which ellipsizes the tree) when it gets merged for 3.4.1

That is purely a cosmetic fix though; if there internal issues with the tree (memory "leaks" or monotonic growth) then that might still need to be addressed. If that is the case would you please file a separate bug (or rephrase this one; but I think this one is good so people can see this has been flagged and worked on).

**Comment by chhil** [comment]
People who already have styles will not be happy seeing this as buttons and text on them are no longer visible and need to rely on tooltips to determine what it is.

I don't use styles so it's not a big deal for me currently.

However, the delete of styles that are tree style may need to be looked at independently

**Comment by dterrahe** [comment]
> People who already have styles with long names will not be happy

Are you referring to the current situation (which will be in 3.4; people will have to use the scroll bar at the bottom) or to the fix in #7140 (which will be in 3.4.1)?

**Comment by chhil** [comment]
Current situation in master where users will need to use the horizontal scroll bar at the bottom. 

I am not aware of the functionality of the fix in 3.4.1 as it's not in master.

**Comment by dterrahe** [comment]
Is this a new regression compared to 3.2 though? I was under the impression that it has behaved like this for a long time.

It is unfortunate that the fix came too late to be included in 3.4, but at this point there is just too much risk that something will accidentally gets broken much worse than this and that we'd have to scramble to get a last minute bugfix release out.

> I am not aware of the functionality of the fix in 3.4.1 as it's not in master.

We'd love for testers like you to try out PRs and give feedback/suggestions _before_ they land in master ;-) (don't worry; I understand it is more hassle/work. But once you figured out how to do it, it is not that hard. And you could even compile it into your own "master" and have fixes before anyone else has. If you are willing to live with the little extra risk...)

**Comment by chhil** [comment]
> Is this a new regression compared to 3.2 though? I was under the impression that it has behaved like this for a long time.

I don't have the version, but I can't recall it ever behaving this way that the scrollbar was needed. I will try 3.2 out on windows and get back.

> We'd love for testers like you to try out PRs and give feedback/suggestions before they land in master ;-) (don't worry; I understand it is more hassle/work. But once you figured out how to do it, it is not that hard. And you could even compile it into your own "master" and have fixes before anyone else has. If you are willing to live with the little extra risk...)

I occasionally have got stuff tested which don't get int master especially stuf I have reported by making changes locally or lately using the dev's pull branch. Not very comfortable, but getting a hold of it. I live on the daily master branch, but if I can assist otherwise I would be more than willing to try.

**Comment by chhil** [comment]
In 3.2.1 styles had its own scrollbar, so it's a regression.

![image](https://user-images.githubusercontent.com/1119439/101473648-149ebd80-3970-11eb-8422-7bdf5782001d.png)

**Comment by dterrahe** [comment]
@TurboGit would you consider at this very late stage just cherry picking the line
`g_object_set(renderer, "ellipsize", PANGO_ELLIPSIZE_MIDDLE, (gchar *)0);`
in styles.c from #7140?

If you want I'll submit a separate PR.

**Comment by TurboGit** [comment]
@dterrahe : no problem this is a bug fix and we still have 1 week for them. I'll do that.

**Comment by TurboGit** [comment]
Done.

**Comment by chhil** [comment]
Current master kind off solves the problem with button alignment by not determining the width of widest string in style and style itself is not scrollable as it was before. It's not a showstopper from my perspective, just documenting it here.

Don't want these 2 to fall through the cracks....
1.Selecting all styles can only be done by selecting a style and then doing a shift+down arrow, no ctrl+a available to select all.
2.On selecting all and then clicking the remove button does not remove styles that have a pipe "|" character in them to display its tree structure. The subtree needs to be deleted for them to be removed.

**Comment by dterrahe** [comment]
@chhil I'd suggest either renaming the bug (and rephrasing the first comment) or closing this and opening a new one. That will make it easier for someone to find and pick this up post 3.4.

Many thanks for all your testing and reporting work.

**Comment by chhil** [comment]
Created a new issue for the 2 points.

**Comment by dterrahe** [comment]
So then you can close this one, right?

**Comment by chhil** [comment]
I thought something autocloses these once the change shows up in the issue.

**Comment by dterrahe** [comment]
No worries. The difference here is that only part of the PR was cherry picked for 3.4 (the bugfix part). The rest of the PR will stay open for some non-essential cleanup work...

Thanks for closing.
