### ISSUE TITLE
Module imageio/format/avif.c message strings not prepared for translations

### ISSUE THREAD

**Issue by matjazjeran** [darktable-org/darktable#7233]
**Describe the bug**
When using darktable in lighttable and selecting menu »export selected« and settng file format to AVIF (8/10/12-bit) the descriptions in hover are not translatable in other languages than English.
The missing messages for translations are (not sure if this is a complete list):
- color information stored in an image, higher is better
- Saving as grayscale will reduce the size for black % white images
- tile an image into segments.
- the compression for the image
- the quality of an image, less quality means fewer details
These messages are also missing in the .pot file

**To Reproduce**
1. Set gui language of darktable to some non-English language.
2. Restart darktable
3. In lighttable use menu "export selected"
4. Set destination format to AVIF
5. Move mouse to message equivalent of »bit depth« and see hover information still in English

**Expected behavior**
These messages should appear in the selected gui language.

**Screenshots**
![DT](https://user-images.githubusercontent.com/56273441/101478588-32105f00-3951-11eb-854b-3207b5e8d3f7.png)
DT.png

**Platform (please complete the following information):**
- Darktable Version:3.3.0+1993~ga5829cf6c
- OS: Fedora 33
- Graphics: 3.0 Mesa 20.2.3

**Additional context**
I suspect that the file imageio/format/avif.c and related files may cause the problem.

**Comment by parafin** [comment]
src/imageio/format/avif.c is missing from po/POTFILES.in. Someone should really automate generation of that file...
