### ISSUE TITLE
Thumbs → Busy message

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#7234]
What: Image thumbs, lighttable mode
When: Busy loading thumbnails or checking file availability on the actual storage drive (thumbnail are stored locally, files could be anywhere).
Problem: Text message is non informative (multiple copies of the same message) and doesn't always fit actual thumbnail. E.g. smaller thumbnail size.

Use one message or even one spinner indicating loading of all visible thumbnails. There is no need for message in every thumbnail.

Committed at this point https://github.com/darktable-org/darktable/commit/de6f4f8173a0a517b5044b8846ca04402dfe84c8

**Comment by Nilvus** [comment]
I personally prefer to see that text on all affected thumbnails as it is actually. When copy/paste a history (for example) on a set of images, it's good to see that text on each thumbnail to better check the image where darktable is working on and when it's over. So, I really think there's a need for that message in every affected thumbnail like it is actually. Furthermore, the text is only displayed when working on an image and so for a really short time and only if loading delay (to display it). See #7179.

Spinning could be a good idea but I'm afraid that it could also be hard to see on small thumbnails.

**Comment by timur-davletshin** [comment]
> Spinning could be a good idea but I'm afraid that it could also be hard to see on small thumbnails.

Spinner fits nicely into 16x16 px, I wonder how many readable letters will fit that :)

**Comment by AlicVB** [comment]
@timur-davletshin : I've done a quick fix for small thumbnails in PR #7239
Of course there will always be size where ... doesn't fit, like in your 16x16 px example, but honestly, at this size, you can't even see anything, so imho we can forget this case (not to speak that the delay to show such small thumb will be extremely small...)

For your spinner proposal, I've no idea if that would fit well in dt... personally I don't like "moving" things, but I may be alone ;)

**Comment by timur-davletshin** [comment]
@AlicVB I hope those three dots will make into 3.4 without need for urgent translation files update :)

**Comment by timur-davletshin** [comment]
> personally I don't like "moving" things, but I may be alone ;)

metoo, but good old text only terminal style spinner could be another option...
