### ISSUE TITLE
Three dt3.2.1 sidecars crash dt3.3

### ISSUE THREAD

**Issue by billmartz** [darktable-org/darktable#7240]
**Describe the bug**
Opening the xmps at [https://discuss.pixls.us/t/play-raw-morning-light/11113](url) three of them crashed dt3.3, even though they can be opened in dt3.2.1. 

I just installed darktable-3.3.0+2033~g29bb7ed6f-win64.exe from [https://discuss.pixls.us/t/darktable-3-3-windows-build/20639/31](url).

I also set up a second installation on another drive, opened by a bat file. That install is set up not to write sidecar files; I use it to examine xmp development by others. Using it, I had the three xmps crash. As I was preparing this, I tried opening the xmps with the first installation on C. They opened, so I tried them again on the second install, and they opened. Then I tried some other xmps, and some failed on each install. So the problem is sort of a moving target. Below are the original xmps and backtraces.

RAW: [https://pixls-discuss.s3.dualstack.us-east-1.amazonaws.com/original/3X/d/b/db9f507e253d78b636c1882c170a2b8c217199c8.NEF](url)

xmp 1: msd, the first one: [https://pixls-discuss.s3.dualstack.us-east-1.amazonaws.com/original/3X/b/8/b8d84222b8ef6bd8c25ba92f9197f5437251f2a7.xmp](url)
Backtrace: 
[darktable_bt_S6PTU0.txt](https://github.com/darktable-org/darktable/files/5661747/darktable_bt_S6PTU0.txt)

xmp 2: Timur: [https://pixls-discuss.s3.dualstack.us-east-1.amazonaws.com/original/3X/a/8/a8369509af01ea315c12cf039bfa7a22c53d82dd.xmp](url)
Backtrace: 
[darktable_bt_FIS9U0.txt](https://github.com/darktable-org/darktable/files/5661751/darktable_bt_FIS9U0.txt)

xmp 3: black_daveth: [https://discuss.pixls.us/uploads/short-url/1IKBT7jbKL7JC2457nq7PFUX7vW.xmp](url)
Backtrace: 
[darktable_bt_YXGVU0.txt](https://github.com/darktable-org/darktable/files/5661754/darktable_bt_YXGVU0.txt)

**Platform (please complete the following information):**
 - Darktable Version: darktable-3.3.0+2033~g29bb7ed6f-win64.exe
 - OS: Windows 10 Pro
 - OpenCL activated.
 - NVIDIA GeForce GTX 1070 Driver version: 457.30

I have dt3.2.1 installed also, and all the problems xmps opened in it.

**Comment by ralfbrown** [comment]
I don't think it's the sidecars as such, I think you may just have wound up with a crashy version (hence the randomness on which sidecars have a problem).  All three backtraces show the crash in gtk_widget_queue_draw, which was involved in a fix on Sunday for a crashing problem where the patch caused a spin loop, which in turn was fixed a couple of commits after the version you have yesterday.
See #7215 and #7232.
