### ISSUE TITLE
Opening DT with memory option for --library creates blank duplicate XMP files *.jpg.xmp ignores existing xmp files

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#7242]
I always use the memory option for my library when testing a new build. This recent one ignores the existing xmp files and creates a set of xmp files with a blank history stack as *.jpg.xmp files. Not sure why. I have my setting active to check for existing/updated xmp files so its is like they are being ignored and new ones are created. Not sure if this maybe just affects edits from a certain period??  Running on WIndows 10
![image](https://user-images.githubusercontent.com/44409419/101562400-5beb7500-3995-11eb-93da-bcb155f887df.png)
 you can see the type of files it creates ie 1K blank history stacks and this is what is read in to lighttable....

![image](https://user-images.githubusercontent.com/44409419/101562492-86d5c900-3995-11eb-9b6b-e547c9ab3673.png)

**Comment by chhil** [comment]
>  This recent one ignores the existing xmp files

Where did the P*.xmp come from?

DT always creates its xmps as ImageName.ext.xmp. Since it does not recognize existing xmps as a valid name it will create new ones.

**Comment by todd-prior** [comment]
These were old edits from 6 months ago I believe??
