### ISSUE TITLE
Abandon lighttable

### ISSUE THREAD

**Issue by stacksmith** [darktable-org/darktable#7243]
**Summary: It is broken, and you don't want to do file management anyway**.

Darktable is unaware of external changes to the file system.  Deleting, renaming, or moving a file results in stale information and picture labels polluting views.  Deleting or renaming a folder in a file manager leaves the lighttable view permanently broken (short of patching the database manually, or wiping the database and staring over)... An yet the recommendation is to use an outside file manager to do just that - manage files.

Darktable wisely avoids file management tasks, and emphatically proclaiming that it will never, ever do so.  **That is great!**  But in that case, why is lighttable there - a half-assed solution for image management?  Just don't do any file management at all.  Stick to the strengths, as stand-alone programs - import, image processing, export. 

What's wrong with invoking the darkroom/printer module on a single file, and relegating file/image management elsewhere?  It works for all kinds of software - text editors, compilers, image editors and cad systems.  In fact, that is the unix way.  Why are you forcing me to use a substandard GUI file selector to process an image?

Imposing file/image management is obnoxious.  I avoid programs like Calibre (a fine program for manipulating epubs, except it insists on managing my library), and all music players that want to 'catalog and manage' my music collection.  I don't care for your ideas about how to tag and categorize my media (while not allowing me to rename and move files).   If you want to database and cache it, make it totally transparent and invisible (that means no stale picture labels or skulls).  If you can't, just give up - you are not up to the task (or perhaps the task is stupid in the first place).  And as you stated, you don't want to deal with it anyway!

And if you really like it for some reason, a separate lighttable gui can be put together, invoking the darkroom system as needed...  Although there are better solutions out there, including stupid file managers (which at least support drag and drop and don't break when a folder is renamed).

Thank you for considering this obvious idea.

P.S.
If you still think that lighttable is a good idea, for f****s sake, instead of drawing a skull, just fix the f*****g database when a file or a directory is missing!  I have Apple ][ software that is easier to use than this.

**Comment by ralfbrown** [comment]
If you want to use an external file manager and skip the lighttable view, you can.

Just define the command the file manager should invoke as "darktable %f" (or however you tell it to substitute the selected file's name).  If given a single file's name on the command line, dt will go straight to darkroom mode with that image opened.  If given multiple files or one or more folder names, it opens those in lighttable view.

Add "--library :memory:" and it won't even add the image to its permanent database.  Hide the filmstrip, and you can pretend that darktable can only work on one file at a time.

**Comment by stacksmith** [comment]
That sounds good!  I will try it tomorrow.
Thanks - going through lighttable feels like wearing a straight-jacket.

**Comment by TurboGit** [comment]
@stacksmith : I'm really fed up with those kind of comments ! No it is not broken, you are trying to use it in a way it was not designed for. Try doing a Paris Dakar with a Ferrary F1 ... Are Ferrary F1 cars broken ?

It sounds like you are the canonical way of using dt, this is also an insult to all people using it since years without problem. Does that mean that all other people are dumb ?

Frankly, please think a bit before writing. TIA.

**Comment by stacksmith** [comment]
@TuboGit : It depends on how you define broken.  The FAQ states that I should use an external file manager, then I see a bunch of skulls where my images were.  I can't remove them - I have to delete a hidden database file - or use magic scripts to restore the database.  Broken.
I would not drive a Ferrary to do Paris Dakar or anything else.   I think people who buy expensive cars are kind of dumb or are having some sort of a crisis.  Many other people are dumb.  Look at the US election, for an example.

I thought before writing.  I propose at least a deeper separation of lighttable, a really embarrassing part of darktable - one that causes people to use other solutions.  If you want to defend it - I will not stand in your way.l

**Comment by TurboGit** [comment]
Which FAQ ? The FAQ is wrong period. dt (as Lr BTW) cannot be used if someone change things outside of the UI. The only kind of supported solution is to remove the image from dt, mess whatever the user think it is necessary to do and re-import in dt.

Now if this does not fit your workflow you better be looking for another software but please stop complaining.

**Comment by stacksmith** [comment]
https://www.darktable.org/about/faq/#faq-rename-files
**How do I rename files on my hard disk?**
Use your file manager (or the command line). You already know how to do that. We have image editing code to write so we don’t spend time to rewrite a file manager. Just make sure to first remove the files from darktable’s library (**sic**), then rename them and re-import them afterwards.
**Will you add file manager capabilities in the future?**
No.

Who is complaining?  I am suggesting and constructively pointing out why lighttable should be gone.

**Comment by pitbuster** [comment]
> Just make sure to first remove the files from darktable’s library, then rename them and re-import them afterwards. 
The FAQ literally says that you should remove things from the collection before moving things.

> I can't remove them - I have to delete a hidden database file and start over - or use magic scripts to restore the database.
What? There is a **remove** button in the light table that also works on skulls.

Learn to understand what you read and to write bug reports before whining like an entitled customer.

**Comment by stacksmith** [comment]
pitbuster, your skill in interpersonal communication is simply inspiring.  In case you missed my sarcasm, I am basically calling you an ***hole.

**Comment by TurboGit** [comment]
@stacksmith : and for sure you are not inspiring at all! please go playing somewhere else. thanks.
