### ISSUE TITLE
Undo an applied style on an edited image removes all edits and is at initial state

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7245]
Current master.

1. Existing history
![image](https://user-images.githubusercontent.com/1119439/101593396-d6f47000-3a15-11eb-8aa1-eca019e69ed3.png)

2. Apply imported style.
3. Appended history after style applied.
![image](https://user-images.githubusercontent.com/1119439/101593462-ef648a80-3a15-11eb-9ad7-ea14a6d08b90.png)

4. ctrl+z to undo style.
5. History after undo
![image](https://user-images.githubusercontent.com/1119439/101593519-0a36ff00-3a16-11eb-9fcb-feb0b6467a22.png)

6. Image has gone back to initial unedited state.

**Comment by TurboGit** [comment]
When the style is applied in the darkroom indeed ! From lighttable all seems ok.

**Comment by TurboGit** [comment]
Should be fixed, please double check all is well on your side. Thanks for reporting, another bug killed for 3.4 !

**Comment by chhil** [comment]
Works fine on current master. Thanks.
