### ISSUE TITLE
Applying style with deprecated channelmixer allows channelmixer to get enabled

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7246]
Current master

Deprecated channel mixer not available on new imports or edits, (correct behavior)
![image](https://user-images.githubusercontent.com/1119439/101594888-6bf86880-3a18-11eb-8488-cfbc57e1a64c.png)

Style that uses current deprecated module channelmixer enables the module in the pipeline
![image](https://user-images.githubusercontent.com/1119439/101595069-cb567880-3a18-11eb-9751-9d2681ad7157.png)

History after applying style
![image](https://user-images.githubusercontent.com/1119439/101595193-fa6cea00-3a18-11eb-8354-0dd947f6701a.png)

Don't know what the right behavior should be. 
Should style fail/warn when applied (some validation needs to be done before application), or style fail/warn when it was imported or exists. Maybe an upgrade option checks styles for deprecated modules and takes some appropriate action.
There are a few more scenarios like if channel mixer already exists then allow.

**Comment by parafin** [comment]
This is intended behavior. Though module itself I think should get “deprecated” warning somewhere (e.g. in the name)

**Comment by chhil** [comment]
Not sure what you mean. The deprecated warning is there
![image](https://user-images.githubusercontent.com/1119439/101599875-846c8100-3a20-11eb-8c74-cfea924afb65.png)

I just feel, deprecated modules will not die if I choose to have a style of deprecated modules and enable them by tricking DT by applying such styles.

**Comment by johnny-bit** [comment]
This is INTENDED behaviour. Applying a style using old module, editing an old edit etc all enable old depracated module. You see the warning? Yes - that's IT. Nothing more to it.

The depreciation is intentional to make sure new users and new usages use new stuff, but we wouldn't like if we tried to edit old stuff or use old, tried styles and the program would bail on us.

**Comment by chhil** [comment]
I understand the use case for deprecated modules. The point I was trying to make is don't allow new edits to use deprecated modules in styles.

**Comment by johnny-bit** [comment]
The deprecated modules are discouraged to be used in new edits - not forbidden. Using a style with deprecated module is perfectly valid usecase.
