### ISSUE TITLE
Copy History of a b/w image with channelmixer as part of edit and paste it onto an image which does not turn B/W 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7249]
Current master.

Old edit with channel mixer that has converted the image to b/w.
CTRL+C to copy history.
History copy  mode is in overwrite mode.
ctrl+v on an image edited in DT with channelmixer deprecated.

Image does not turn b/w as channelmixer is not pasted.

**Comment by TurboGit** [comment]
You need Ctrl+Shft+C to copy deprecated modules I suppose.

**Comment by chhil** [comment]
`Ctrl+Shft+C` works. 

The problem is that one doesn't need to change any checkboxes with ctrl+shift+c.
Implies, behaviors  `ctrl+shift+c` != `ctrl+c` when no checkboxes are changed.

**Comment by johnny-bit** [comment]
well.. in 3.4 release the "copy" became actually "safe copy" and "copy parts" became "copy whatever you want"

> The problem is that one doesn't need to change any checkboxes with ctrl+shift+c.

I've checked and it looks like the all not-safe modules are deselected. However deprecated modules are not deselected. Let's change that ;) 

see #7520
