### ISSUE TITLE
Drop darkroom image cache after leaving this mode.

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#7251]
1. Loaded this raw image in darkroom mode https://discuss.pixls.us/t/a-study-in-blue/21706 , tried to zoom in. Quit to lighttable mode.
2. Loaded (right panel → load from sidecar file...) this history file https://discuss.pixls.us/uploads/short-url/fZFJ3qCmpP7SUuDdCI5wvzZCnXe.xmp
3. Notice thumbnail is updated accordingly
4. Open image in darkroom mode. Notice old image is shown before darktable updates.
6. Zoom in with. Old image in shown again before dt recalculates.

Linux, 64 bit, latest master, no OpenCL.

**Comment by jenshannoschwalm** [comment]
Don't understand, what is the issue? Isn't this as is it is supposed to do - you did some editing and the thumb refreshes later?

**Comment by timur-davletshin** [comment]
@jenshannoschwalm I don't think that darkroom image cache should be stored after leaving it to lighttable mode. Not even saying that image cache does not reflect changes made to history stack.
