### ISSUE TITLE
Lens Correction: Allow "incompatible" camera-lens-combination

### ISSUE THREAD

**Issue by DasCapschen** [darktable-org/darktable#7252]
**Is your feature request related to a problem? Please describe.**

I am using a Tamron A-mount lens on a Sony Alpha 7 ii (E-mount) through an adapter. 
When using the lens correction module, the lens is not identified, because it is not correctly written to exif metadata. 
Darktable does not allow me to select my lens though, because it filters the lenses by camera.
So I have to select an A-mount Sony camera like the Alpha 77. (which already introduces some correction effects though!)
Then I can select my lens, but as soon as I change the camera back to the Sony Alpha 7 ii, the module stops working, because it realised this is an "incompatible" combination.

**Describe the solution you'd like**

I would like to be able to manually select a lens which is "incompatible" with the selected camera model, because it might have been used through an adapter. 
The module should continue working if I select such an "incompatible" combination.

**Comment by parafin** [comment]
lensfun expert is required here. I think it has a notion of "adapters", which probably has to be added to DB somehow for it to work. I don't think it's something darktable limits you with...

**Comment by dterrahe** [comment]
This would be one of the advantages of lensfun 2 (i.e. the incompatible release 0.3.95) where you can specify adapters separately. In lensfun 1, you'll have to edit the file containing your camera specification and add extra mounts.

In your case in share\lensfun\version_1\mil-sony.xml in the `<model>ILCE-7M2</model>` section, you'd add `<mount>Sony Alpha</mount>`

This will get overwritten with each update.

**Comment by DasCapschen** [comment]
Thank you, that worked! 👍🏻 

Btw, you said lensfun 2 (version 0.3.95) is incompatible... I have that version installed on my system (Arch Linux) and it seems to work fine with darktable. Well except that I can't specify the adapter.
I haven't looked at the code, so I don't know how these parts interact, this was a question purely from a user standpoint, so I'm not sure if that's what you meant with incompatible release... 😅

**Comment by parafin** [comment]
It seems to work, but results it produces are incompatible with older version, and there are other bugs. It really shouldn’t be packaged in any distro.

**Comment by parafin** [comment]
Concerning this issue, should we close it then? This is an upstream (lensfun) problem.
