### ISSUE TITLE
Copy paste history in overwrite mode followed by undo does not bring original image back to pre paste stage.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7256]
Current master.

History Stack -> Mode -> Overwrite.

Open an image (image1) in darkroom.
Do a simple edit like a crop or anything.
See step added to history.
Now copy history image (image2)(I did a ctrl_shift+c and did not change any checkboxes)
ctrl+v on image 1.
See changes are applied and history shows the changes and the crop initially done on image1 is no longer there (since in overwrite mode).
Now do a ctrl+z to undo this history paste.
Image1 goes back to intial state without the crop that was applied to it.

Expected behavior: ctrl+z should only undo the pasted history step and bring the original image back to the cropped state.

How to reproduce...
![CTRLZHistory1](https://user-images.githubusercontent.com/1119439/101707859-17a1c700-3ab2-11eb-9133-0526721ac734.gif)

**Comment by chhil** [comment]
Bump

**Comment by TurboGit** [comment]
Should be fixed by #7269. Can you double check all is fine on your side with this PR ? (it is not merged on master).

**Comment by chhil** [comment]
I have manually merged your changes into the master that I pull for my builds.

Will get back to you with result.

**Comment by chhil** [comment]
@TurboGit 
Works as required. can be merged into master.
