### ISSUE TITLE
Segmentation fault opening any raw image

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#7258]
**Describe the bug**
Opening 'any' (Nikon D7000 and Panasonic LX7) raw image, with a pristine history, results in crash. Log: https://tech.kovacs-telekes.org/files/darktable_bt_4Q0PV0.txt

**To Reproduce**
1. Open any raw image

**Expected behavior**
No crash

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+2060~gb3fce5e47
 - OS: Ubuntu 20.10, 64-bit
 - OpenCL activated or no: crash occurs with and without OpenCL

**Additional context**
 - Can you reproduce with another Darktable version?: no, worked fine yesterday evening with 3.3.0+2048~g13646619c

**Comment by Mark-64** [comment]
Confirmed here on Windows 10, trying to bisect commits

**Comment by Mark-64** [comment]
From a quick bisect, it seems the culprit is commit #7167 
With it, starting with an empty database, DT crashes for me importing any folder 
![immagine](https://user-images.githubusercontent.com/43290988/101831380-1b772d00-3b36-11eb-83fd-cad0d033bc6c.png)

Backtrace look like this
[darktable_bt_8OHMV0.txt](https://github.com/darktable-org/darktable/files/5675682/darktable_bt_8OHMV0.txt)

**Comment by TurboGit** [comment]
@kofa73 @Mark-64 : can you test #7268 ?

**Comment by kofa73** [comment]
@Mark-64 : weird, I have no issues with:
**commit 1364661**9cdc05569a0789e985747e5d66c002e02
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
**Date:   Tue Dec 8 22:19:41 2020 +0100**

    Revert "Merge branch 'censorize' into HEAD"
    
    This reverts commit 0925b5fac2bf26f3e76e6dc4eb9327a2a87e19c7, reversing
    changes made to 8a795003d326bb198b2d15d4fd21ff628ab7394e.

And you found it's there since
**commit 1522dc5**d1e294ed644e097548d3f164eec3ea6c8
Author: Ralf Brown <ralfbrown@users.noreply.github.com>
**Date:   Sat Dec 5 04:24:18 2020 -0500**

    [performance] filmicrgb reconstruction speedup, part 2 (#7167)

@TurboGit : #7268 works. Weird.

**Comment by kofa73** [comment]
@Mark-64 @TurboGit I do not get the crash with 1522dc5d1, either.

**Comment by kofa73** [comment]
Started with 'good' 13646619c, 'bad' b3fce5
```
kofa@eagle:~/darktable$ git bisect bad
509caf7d199340b125dcbe95d72f9af3c1b3e2db is the first bad commit
commit 509caf7d199340b125dcbe95d72f9af3c1b3e2db
Author: Pascal Obry <pascal@obry.net>
Date:   Wed Dec 9 10:38:28 2020 +0100

    dt_iop_gui_update: call even if no gui_data.
    
    The module may anyway do something and we want to update the
    header status/icon anyway.
    
    This fix a bug on strange behavior for flip module which does
    not have a gui_data.
    
    Fixes #7213.

 src/develop/imageop.c | 19 ++++++++-----------
 1 file changed, 8 insertions(+), 11 deletions(-)
```

**Comment by Mark-64** [comment]
@kofa73 Crash for me occurs opening old edits, or (re)importing folders containing old edits, so please do some checks importing some of your folders starting from an empty database in a test configuration before concluding there are no issues with a given commit.
I just tested commit 13646619cdc05569a0789e985747e5d66c002e02 and it does have crashes for me.
The last stable build I have in my system is darktable-3.3.0+1977~gde6f4f8173a-win64.exe, which is by coincidence just before the suspect commit

**Comment by kofa73** [comment]
Maybe we have two different issues -- see bisect above.

**Comment by Mark-64** [comment]
Most likely. Tried in Ubuntu 20.04 and I do not get crashes at all, even with the current master.
So my issue is Windows specific.
@TurboGit should I open a different bug report ?

**Comment by TurboGit** [comment]
@Mark-64 : Yes please open a separate report as this one will be closed when the PR is merged.

**Comment by Mark-64** [comment]
I will, but please note that the PR is reverting the commit which I found, although it seems to fix @kofa73 issue as well, for some strange reason

**Comment by kofa73** [comment]
Cannot reproduce with c06b55abd.

**Comment by TurboGit** [comment]
@Mark-64 : I see that @kofa73 has closed the issue as no more reproducible, is that your case too ?

If not, can you please test with  #7274 and see if it helps. TIA.
