### ISSUE TITLE
lighttable - collect images: boolean OR in search for multiple file names (separated via comma) is not isolated from rest of search query

### ISSUE THREAD

**Issue by boxleits** [darktable-org/darktable#7267]
Hi,

**Description:**
when searching for multiple file names in lighttable's collect images, further search restrictions (e.g. year) apply to the last specified filename only.
I had a look at the code and found the following:
The multi file search gets translated to a boolean term that concatenates the single filename constraints via OR.
https://github.com/darktable-org/darktable/blob/f301babb9a8d33683759b9ecd06f20b19fe10226/src/common/collection.c#L1715-L1727
But the concatenated term is not isolated. I did not try it out, but i guess applying simple brackets at beginning and end of the concatenated term should do the trick.

**Steps to reproduce:**
To reproduce the issue, you need four files of which two respectively have an identical name in two different folders on the file system. The files must differ in at least one metadate, e.g. the year of date taken. lets say, we have the following four files (with folder path as year of date taken):
2019/name1, 2019/name2, 2020/name1, 2020/name2
When we now import those four files and apply a file name constraint "name1,name2" and a year constraint for 2020, we get files 2019/name1, 2020/name1 and 2020/name2 as result.

**Expected result**
Darktable should apply all filters to all filenames equally.
In the example from above: the expected search result would be 2020/name1 and 2020/name2 only

**Platform (please complete the following information):**
Darktable Version: 3.2.1
OS: Windows and Linux

Regards
Fred

**Comment by johnny-bit** [comment]
Seems like a likely problem... Can you try doing a PR to fix this? Contributions are very welcome :smiley: 

Pinging @sams96 to look at possible issue with #3221 :) - it would be great to have it fixed! thanks!
