### ISSUE TITLE
Lut3d/gmic issues with windows

### ISSUE THREAD

**Issue by phrrk** [darktable-org/darktable#7275]
**Describe the bug**
Since issue #6936 was identified and the fix #6976 applied (along with renaming the 2 relevant opencv library files) the Lut3d module has, for me, remained unavailable when darktable is built as a package using

`cmake --build . --target package
`
and installing the executable thus created.  In the log file from a debug run there is the following relevant error

``[iop_load_module] failed to open operation 'lut3d': 'C:\Program Files\darktable\lib\darktable/plugins\liblut3d.dll': The specified module could not be found.``

Note the forward slash where it should be a backslash, and that  
`C:\Program Files\darktable\lib\darktable\plugins\liblut3d.dll`
does exist.
If I instead build and install in /opt/darktable everything is fine and Lut3d is available.

**Expected behavior**

Lut3d module should be available

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  latest git master
 - OS:  Windows 10
 -  with or without OpenCL
 

**Additional context**

**Comment by todd-prior** [comment]
Was this fixed I have this exact same issue and I built it today on a fresh MYS2 install went through carefully and added all dependencies??
