### ISSUE TITLE
Reporting of width/height

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#7279]
Not sure if you call this a FR or a bug report, but here goes:

In the information panel, width and height information are returned for the dimensions of the original image.
However, when an image is shot in portrait orientation, the width and height values still assume a landscape orientation.
In other words, for my 24MP images, width is reported as 6048 and height is reported as 4024, even though darktable has correctly interpreted the image as having being shot in a portrait orientation.

Seems to me that if dt can read from the EXIF metadata that the image was shot in portrait orientation, then it should also be smart enough to report the width and height values in an inverted format. i.e. width = 4024 and height i= 6048.

Any arguments for or against?

**Comment by ptilopteri** [comment]
I can confirm the same improper readings for portrait images in my D500, D7200 and D850

**Comment by jenshannoschwalm** [comment]
No arguments :-) It should better be called "sensor info"

**Comment by johnny-bit** [comment]
Isn't #6697 essentially the same as this one?

that one asks for "cropped width" + "cropped height"
this one asks for "max width" + "max height"
and currently displayed is "sensor width" + "sensor height"
