### ISSUE TITLE
Nikon Z7 II camera support

### ISSUE THREAD

**Issue by Druttan** [darktable-org/darktable#7282]
I have uploaded raw samples from z7 II to raw.pixls.us and would like camera support in darktable.

**Comment by LebedevRI** [comment]
Thank you for contributing the samples!

**Comment by Druttan** [comment]
You are welcome, glad that I can contribute with some small thing to
Darktable.
Kind regards // Kristina

Den lör 12 dec. 2020 kl 14:45 skrev Roman Lebedev <notifications@github.com

**Comment by oxpa** [comment]
As far as I know, Z7 II NEF are the same as Z7. If I change a string in NEF file with vim or sed - it then works fine in darktable.

**Comment by LebedevRI** [comment]
> As far as I know, Z7 II NEF are the same as Z7. If I change a string in NEF file with vim or sed - it then works fine in darktable.

Be sure to have backups

**Comment by oxpa** [comment]
I just shoot nef+jpeg till there is an update for darktable ;) Thank you!

**Comment by Druttan** [comment]
Hello again
Thank you for the information, shooting in nef+jpeg already.
Thanks // Kristina

Den tors 17 dec. 2020 kl 21:59 skrev A compound of Fe and O <
notifications@github.com>:

**Comment by mrubli** [comment]
For those needing a quick way to process their Z7 II files in Darktable 3.4.1 [ExifTool](https://exiftool.org) works great for this:

```
$ exiftool -Model *.NEF
======== DSC_2037.NEF
Camera Model Name               : NIKON Z 7_2
======== DSC_2252.NEF
Camera Model Name               : NIKON Z 7_2
======== DSC_2325.NEF
Camera Model Name               : NIKON Z 7_2
    3 image files read

$ exiftool -Model="NIKON Z 7" *.NEF
    3 image files updated

$ exiftool -Model *.NEF
======== DSC_2037.NEF
Camera Model Name               : NIKON Z 7
======== DSC_2252.NEF
Camera Model Name               : NIKON Z 7
======== DSC_2325.NEF
Camera Model Name               : NIKON Z 7
    3 image files read
```

ExifTool does create backups of the files it edits but it's still a good idea to first back up the raw files to a save place. (The `-overwrite_original` option stops ExifTool from creating backup files if you already have another backup.)

I found this works even on files that have already been imported into Darktable but deleting and reimporting is definitely the safer choice.

**Comment by Druttan** [comment]
Thank you very mush!
// Kristina

Den ons 10 mars 2021 kl 16:54 skrev mrubli <notifications@github.com>:
