### ISSUE TITLE
Fujifilm X-S10

### ISSUE THREAD

**Issue by dbrgn** [darktable-org/darktable#7284]
When opening RAW images from the Fujifilm X-S10, the files can be previewed in Lighttable, but not edited in Darkroom:

> darktable could not load `DSCF0045_Uncompressed.RAF`, switching to lighttable now.

![2020-12-12-163457_1141x399_scrot](https://user-images.githubusercontent.com/105168/101988111-0e724f00-3c98-11eb-9da6-d635e22b2078.png)

This happens with uncompressed and compressed RAW files, both with lossless and lossy compression.

It also happens both in Darktable 3.2.1 and on current master (3.3.0+2079~g19b17c9cc).

RAW sample images have been uploaded to https://raw.pixls.us/ by someone else already in November. I can also provide additional samples if desired.

Some support for the X-S10 was already added by @floemker:

- [color matrix](https://github.com/darktable-org/darktable/commit/ea543654fc339cb9f1397287f15c879760bc0994)
- [noise profile](https://github.com/darktable-org/darktable/commit/7a375e0b55f4985113af9dfb7c7063dd931f49f4)

...so I'm not sure whether X-S10 support is supposed to be working already on master, or not yet.

Thanks!

**Comment by floemker** [comment]
A rawspeed update is currently missing. X-S10 support is already in the
development branch of rawspeed, but not yet in the stable branch.

**Comment by dbrgn** [comment]
Thanks @floemker for the update and for your contributions!

I have this photo in 3 variations:

![2020-12-12-165503_554x380_scrot](https://user-images.githubusercontent.com/105168/101988587-d0c2f580-3c9a-11eb-8ec2-187757ebfef2.png)

After updating the rawspeed submodule to the latest `develop` branch, I can open the uncompressed and the lossless files. The lossless file looks good, but for some reason the uncompressed file looks very dark:

![2020-12-12-165629_1776x1186_scrot](https://user-images.githubusercontent.com/105168/101988623-010a9400-3c9b-11eb-923d-d85744df02dd.png)

*(Insert bad pun about dark photos and the software being called "darktable" here...)*

The file with lossy compression cannot be opened at all.

If I can help in any way, let me know!

**Comment by floemker** [comment]
Lossy compressed is not supported by rawspeed. See e.g.
https://github.com/darktable-org/rawspeed/issues/255
I assume somebody needs to figure out the compression algorithm and
needs to write a decoder for that.

For the dark image: Did you look at the exposure module? Depending on mode
darktable compensates for in camera exposure compensation, and that can
result in a dark image.

**Comment by floemker** [comment]
The input color profile settings should be the same in both cases. And they are for me
with uncompressed / compressed images I just took. My settings in both cases are
"standard color matrix", "linear Rec2020 RGB", and "off".

**Comment by dbrgn** [comment]
Weird, I cannot reproduce the issue anymore... Must have been some problem with my local configuration?

Anyways, so the X-S10 seems to be supported on master as soon as `rawspeed` is updated! :tada:

**Comment by drazde** [comment]
I have the same problem (with darktable 3.4). I don't have a Fujifilm X-S10 but some raw for samples.
How can I understand if this files are compressed (so unsupported still now)?

I try with _exiv2_ and _exiftool_ but I don't see anything about this
