### ISSUE TITLE
Segfault when starting darktable with single CR2 file as argument

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#7285]
**Describe the bug**
Migrated today to latest darktable master 3.3.0~git2079.19b17c9cc. During debugging a problem(?) with the new CC module, I've hit another problem. When I start darktable from command line with a single file, darktable crashes.
I could open darktable without arguments and it runs fine.

**To Reproduce**
darktable /var/artwork/photos/_MG_8932.CR2 (or any other file...)

**Expected behavior**
No Segfault.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0~git2079.19b17c9cc.
 - OS: Debian Bullseye
 - OpenCL: yes
 - PNY Nvidia Quadro 450.80.02-1

Binary package was obtained from https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

[darktable_bt_POVIV0.txt](https://github.com/darktable-org/darktable/files/5683323/darktable_bt_POVIV0.txt)

**Comment by ralfbrown** [comment]
Works fine here.  The crash is in a function related to the image cache.  Have you tried clearing out the cache directory?

**Comment by cytrinox** [comment]
@ralfbrown still happens if I move ~/.cache/darktable away.

**Comment by johnny-bit** [comment]
@cytrinox - run with `-d all`, that way we'll know more about what happens.

**Comment by cytrinox** [comment]
Log with full debugging:
[darktable_bt_CP6BV0.txt](https://github.com/darktable-org/darktable/files/5685226/darktable_bt_CP6BV0.txt)

**Comment by johnny-bit** [comment]
well, again - this is just backtrace from gdb... can you provide console output when running darktable like `darktable -d all /var/artwork/photos/_MG_8932.CR2` ?

**Comment by cytrinox** [comment]
Ops, thought this was the full log.
Here is stderr+stdout: 
[full.txt](https://github.com/darktable-org/darktable/files/5685292/full.txt)

**Comment by johnny-bit** [comment]
Interestingly enough I cannot reproduce neither on current master nor on 3.2.1, be it with clean or unclean configs and dbs...

@cytrinox - can you try with empty config dir and no lua scripts installed?

**Comment by TurboGit** [comment]
Looks like it is related to some Lua script indeed.

**Comment by cytrinox** [comment]
Updated my lua directory to the latest lua repository. Works now.
Thanks for the hint!
