### ISSUE TITLE
Lighttable → Image information update

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#7291]
1. Import any image to your database.
2. Click that image in lighttable mode and see respective image information.
3. Remove that image from the database via selected image[s] → remove.
4. Notice, image information is not updated and shows information about the image which is no longer in the database.

**Comment by Nilvus** [comment]
I agree, would be better to empty image information when removing an image.
Probably a refresh missing. @AlicVB: as it's related to lighttable, maybe you have idea or a simple fix to that?

**Comment by AlicVB** [comment]
I think that this is quite the same problem than #6482 Not exactly the same symptoms, but same issue codewise...
I'll try to have a look, but this will be for 3.4.1, I won't have time to do that cleanly before ! (and this is not really a blocking issue imho)

**Comment by AlicVB** [comment]
oops, completely forgot this one :(
PR #9067 should fix it
