### ISSUE TITLE
Duplicating a style creates a style without any modules

### ISSUE THREAD

**Issue by hodapp512** [darktable-org/darktable#7304]
Please let me know if any more info is needed.

**To Reproduce**
1. Go to Lightroom -> Styles
2. Click on an existing style (which contains module items) and select "edit..."
3. Select modules
4. Edit style name to some new name
5. Check "duplicate style"
6. Save
7. Look at new style, but it has none of the checked module items

**Expected behavior**
On step 7, the checked module items should be present in the new style.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL activated
 - GeForce MX150 24.21.13.9872

**Comment by hodapp512** [comment]
I think an even better fix would be to add a "duplicate" button in the styles pane instead of this checkbox on the edit pop-up window.

**Comment by TurboGit** [comment]
Cannot reproduce on current master, so probably fixed.
