### ISSUE TITLE
color picker: The positioning of live samples changes after cropping

### ISSUE THREAD

**Issue by msdm** [darktable-org/darktable#7306]
**Describe the bug**
After cropping the photo (via crop and rotate iop), the locations of previously added live samples change in the color picker, and as a result, they sample wrong areas. It seems that the positioning is relative to the current photo while it must always be relative to the original photo regardless of cropping.

**To Reproduce**
1. Open a photo in darkroom view
2. Add some live samples
3. Crop aggressively from only one corner of the photo with the crop and rotate iop
4. Check the locations (and the shown colors) of the live samples by either mouse-hovering or enabling "display samples areas on image"

**Expected behavior**
Cropping should not change the sampled areas/points

**Screenshots**
Before cropping:
![Screenshot from 2020-12-13 22-03-23](https://user-images.githubusercontent.com/8253237/102020563-3d1f2100-3d8f-11eb-8508-b7bfca01e2c8.png)

After cropping:
![Screenshot from 2020-12-13 22-04-30](https://user-images.githubusercontent.com/8253237/102020571-414b3e80-3d8f-11eb-895c-c3aac6e2354c.png)

**Platform (please complete the following information):**
 - Darktable Version: git-master
 - OS: Ubuntu 20.04
 - OpenCL activated
 - Nvidia Graphics

**Comment by MStraeten** [comment]
That's no bug, thats a feature: this allows getting the color of the same spot in subsequent shots of a scene (e.g. if there's a white balance reference or something else at the same place)

**Comment by msdm** [comment]
> this allows getting the color of the same spot in subsequent shots of a scene

Do you mean after cropping each shot differently? What would be its use-case?

**Comment by MStraeten** [comment]
reference point is at the same place, so the best exposure can be found quickly - no former cropping if the sequence was taken with a fixed position of the reference. There might be further usecases - at least the color picker in darktable never behaved different...

**Comment by dterrahe** [comment]
Although an adjustment for cropping might be somewhat easy to implement, taking into account keystone/perspective/lens corrections, rotations of non-90 degree multiples and liquifications would not be. And it would not be as obvious that there is no intention to correct for any of these if there were a correction for cropping. So arguably the behavior would be less predictable/worse if this was changed.
