### ISSUE TITLE
OSX: UI lagging on crop&rotate when waveform histogram enabled

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#7307]
to change the crop borders or move the crop frame around via drag%drop it’s necessary to wait for finalizing waveform histogram processing (about 1-2 sec) after click&hold before being able to drag the cropping border/corner or frame.

to reproduce enable waveform histogram, 
activate crop&rotate
click&hold a corner
a) drag immediately --> nothing happens
b) be patient then drag --> works as expected 

![image](https://user-images.githubusercontent.com/39386816/102021812-e0b60480-3d82-11eb-9133-5290008a2128.png)
on click&hold on the corner darktable -d perf gives following output (nothing moved yet):
```
815,149989 [dev] took 0,000 secs (0,000 CPU) to load the image.
815,172917 [dev_process_image] pixel pipeline processing took 0,023 secs (0,038 CPU)
815,183386 [dev_pixelpipe] took 0,033 secs (0,058 CPU) processed `Ausgabekodierung' on CPU, blended on CPU [preview/fast]
image colorspace transform RGB-->RGB took 0,012 secs (0,103 CPU) [final histogram]
final histogram waveform took 1,683 secs (19,767 CPU)
image colorspace transform RGB-->RGB took 0,000 secs (0,002 CPU) [waveform gamma]
image colorspace transform RGB-->RGB took 0,000 secs (0,002 CPU) [waveform gamma]
816,882705 [dev_process_preview] pixel pipeline processing took 1,733 secs (19,944 CPU)
image colorspace transform RGB-->RGB took 0,000 secs (0,002 CPU) [waveform gamma]
scope draw took 1,632 secs (18,825 CPU)
```
standard histogram is way faster: 
```
196,027675 [dev] took 0,000 secs (0,000 CPU) to load the image.
196,030728 [dev_pixelpipe] took 0,003 secs (0,024 CPU) processed `Ausgabekodierung' on CPU, blended on CPU [preview/fast]
196,034357 [dev_process_image] pixel pipeline processing took 0,007 secs (0,051 CPU)
image colorspace transform RGB-->RGB took 0,014 secs (0,109 CPU) [final histogram]
final histogram took 0,001 secs (0,012 CPU)
196,050546 [dev_process_preview] pixel pipeline processing took 0,023 secs (0,154 CPU)
scope draw took 0,006 secs (0,031 CPU)

```
histogram profile is srgb (websafe)
restrict histogram to selection option in color picker is not checked

Is it necessary to do this histogram calculation here? 

**Platform (please complete the following information):**
 - Darktable Version:this is darktable 3.3.0+2038~g0ba18ac8b
compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
 - OS: OSX
 -with/without OpenCL activated

**Comment by ralfbrown** [comment]
No problem on Linux - checked both 3.3.0+2028 from a week ago and today's 3.3.0+2092 on a 24MP image.  The slowest I saw for "final histogram waveform" was 0.004 secs (0.122 CPU), and slowest for "scope draw" was 0.005/0.117.

**Comment by MStraeten** [comment]
seems to be specific to osx - also not reproducible with my windows build

**Comment by MStraeten** [comment]
even quite strange: it's just this context where "final histogram waveform" is that slow. In other modules where it is logged, it’s quite faster.

**Comment by dtorop** [comment]
This is strange! It's helpful to have the "-d perf" data:

```
final histogram waveform took 1,683 secs (19,767 CPU)
```

That would suggest that the trouble is in `_lib_histogram_process_waveform()`

https://github.com/darktable-org/darktable/blob/ecc48ae7acc737257a3cace28724303b88e024b2/src/libs/histogram.c#L189-L249

This did get a total rewrite in v3.4. But I'm stumped as to what would be making this take so much time, particularly the huge amount of CPU time. The most alarming thing is that it appears to be OS X specific, and that #7429 is also an OS X bug.

@MStraeten, some queries:

- Is there something unusual about the raw file which you're working on? Is it particularly huge or an unusual format?
- Are you seeing the same terrible output as is reported in #7429? Or is it just slow?
- Do you have the ability to recompile on OS X and tweak the code? If so, a first step would be to comment out the bulk of `_lib_histogram_process_waveform()` and see if this increases execution speed. Another step would be to the OpenMP pragma and see what changes.

I'm curious if there's a way to turn disable OpenMP from the command line or environment for OS X...?

**Comment by dtorop** [comment]
One other question for @MStraeten: I'm assuming you see this slowdown both from waveform and RGB parade. Is this true?

I'm alas working a bit in the dark here, not having ready access to an OS X machine, either for testing or to compile...

**Comment by dtorop** [comment]
Ah, just saw https://discuss.pixls.us/t/current-osx-build/13213. Clearly, @MStraeten is more than able to compile dt on OSX!

**Comment by parafin** [comment]
> I'm curious if there's a way to turn disable OpenMP from the command line or environment for OS X...?

How do you mean disable? macOS doesn't differ here from Linux I think, so same environment variables and dt cmd options setting number of OpenMP threads should work.

**Comment by MStraeten** [comment]
i retested it with current build and deleted .config/darktable. 
times for a 30MP image.
its lagging for parade and plain waveform as well:
waveform parade:
```
final histogram waveform took 1,729 secs (19,295 CPU)
final histogram waveform took 1,720 secs (18,700 CPU)
final histogram waveform took 1,708 secs (18,625 CPU)

```
waveform:
```
final histogram waveform took 1,741 secs (18,874 CPU)
final histogram waveform took 1,715 secs (18,825 CPU)
final histogram waveform took 1,785 secs (18,957 CPU)
```
this can be mitigated when changing previewsize to 1/2 or less `final histogram waveform took 0,138 secs (1,445 CPU)`
plain histogram is ways faster: `final histogram took 0,001 secs (0,013 CPU)` full preview size and `final histogram took 0,000 secs (0,002 CPU)`  previewsize 1/2

**Comment by MStraeten** [comment]
played a bit around:
disabling parallelization speeds up a lot 
from `final histogram waveform took 1,824 secs (20,052 CPU)` to final `histogram waveform took 0,044 secs (0,379 CPU)`

and it also get rid of the mess in #7429 

did this in _lib_histogram_process_waveform
```
 #if defined(_OPENMP) && !defined(__APPLE__)
#pragma omp parallel for simd default(none) \
  dt_omp_firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  dt_omp_sharedconst(wf_linear) \
  aligned(input, wf_linear:64) \
  schedule(simd:static, bin_width)
#endif
```

**Comment by johnny-bit** [comment]
This receives my "what the hell Apple???" seal of coding mess.

**Comment by MStraeten** [comment]
building with -DCMAKE_BUILD_TYPE=Debug don’t change the behaviour so it seems to be different from #7426

**Comment by dtorop** [comment]
Yes, this is shocking! I wasn't following #7349, #7361, #7426 but I guess the pieces are all fitting together.

@MStraeten: What happens if you remove SIMD? That is, write the OpenMP clause as:

```c
#ifdef _OPENMP
#pragma omp parallel for default(none) \
  dt_omp_firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  dt_omp_sharedconst(wf_linear) \
  aligned(input, wf_linear:64) \
  schedule(static, bin_width)
#endif
```

The surmise is that if `dt_histogram_worker()` is not causing trouble, and uses OpenMP (as do many other bits of dt), that there must be something particular to this OpenMP invocation causing the trouble.

Here is the OpenMP for regular histogram:

https://github.com/darktable-org/darktable/blob/cbbef679f39ab044ecfaa343fe589b6c4446e056/src/common/histogram.c#L323-L328

Where this falls down is that the liquify code causing trouble doesn't use SIMD, and that I think that recent versions of the waveform code did.

**Comment by MStraeten** [comment]
just removing SIMD  results in an compiler error:
```
/Users/martinstraeten/src/darktable_debug/src/libs/histogram.c:224:3: fatal error: unexpected OpenMP clause 'aligned' in directive
      '#pragma omp parallel for'
  aligned(input, wf_linear:64) \
  ^
1 error generated.
```

**Comment by MStraeten** [comment]
there are a couple of warnings about omp around while compiling ([omp-related-compiler-messages.txt](https://github.com/darktable-org/darktable/files/5744386/omp-related-compiler-messages.txt))
for histogram.c:
[ 52%] Building C object lib/darktable/plugins/lighttable/CMakeFiles/histogram.dir/histogram.c.o
```
/Users/martinstraeten/src/darktable_debug/src/libs/histogram.c:221:1: warning: loop not vectorized: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation
      ordering [-Wpass-failed=transform-warning]
#pragma omp parallel for simd default(none) \
^
/Users/martinstraeten/src/darktable_debug/src/libs/histogram.c:552:1: warning: loop not vectorized: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation
      ordering [-Wpass-failed=transform-warning]
#pragma omp parallel for simd default(none) \
^
2 warnings generated.
```

**Comment by dtorop** [comment]
> just removing SIMD results in an compiler error:

Apologies. This version should compile:

```c
#ifdef _OPENMP
#pragma omp parallel default(none) \
  dt_omp_firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  dt_omp_sharedconst(wf_linear)
#endif
```

But the compile warnings you sent are very instructive. There's a lot of them! At first glance, they all include the use of the dt_omp_firstprivate() macro. Could this be the problem? Not sure. To test, could remove the macros:

```c
#ifdef _OPENMP
#pragma omp parallel default(none) \
  firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  shared(wf_linear)
#endif
```

Or maybe it's simply that every use of OpenMP uses that macro at this point...

There's also https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp maybe a lead?

**Comment by MStraeten** [comment]
```
#ifdef _OPENMP
#pragma omp parallel default(none) \
  dt_omp_firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  dt_omp_sharedconst(wf_linear)
#endif
```
compiles, the lagging is mitigated (but `final histogram waveform took` value is doubled compared to disable this by  `#if defined(_OPENMP) && !defined(__APPLE__)`) but the histogram keeps being weird.

removing the macros doesn't change the behaviour - same message while compiling

here's the build command for histogram:
[build-commands-histogram.txt](https://github.com/darktable-org/darktable/files/5746544/build-commands-histogram.txt)

**Comment by dtorop** [comment]
> compiles, the lagging is mitigated (but `final histogram waveform took` value is doubled compared to disable this by `#if defined(_OPENMP) && !defined(__APPLE__)`) but the histogram keeps being weird.
> 
> removing the macros doesn't change the behaviour - same message while compiling

Hmmm... So it seems like either:

a) some sort of build bug (though I can't see anything obviously weird in attached build command)
b) a compiler bug!
c) a runtime OpenMP dependency isn't present or is mis-versioned
d) there's code in darktable which is incorrect but allowed by non-OSX systems

Certainly #7518 seems good so that there is a workable 3.4.1 for OS X. Longer term, either some serious debugging, more selective quick-and-dirty fixes, or making a general macro to easily disable OpenMP case-by-case on OS X.

**Comment by johnny-bit** [comment]
#7518 seemed to supposedly close this issue too... Maybe let's concentrate on unbreaking Apple's OpenMP mess in #7426?

**Comment by dtorop** [comment]
Here's a theory:

The waveform is processed by binning together image columns to produce one waveform column. For a 3:2 image, "landscape" bins will be 4 rows wide, "portrait" bins will be 3 rows wide.

The binning loop uses `schedule(simd:static, bin_width)` to try to make sure that only one thread processes each bin. This lets each bin accumulate separately without having to worry about locking or atomic operations. From OpenMP docs:

> When the simd modifier is specified and the loop is associated with a SIMD construct, the chunk_size for all chunks except the first and last chunks is new_chunk_size=ceil(chunk_size/simd_width)∗simd_width where simd_width is an implementation-defined value.

This suggests that schedule() doesn't provide any guarantee of protecting bins from overlapping writes.

I doubt this is the real problem, but at least it means that the waveform OpenMP code, as it is now, may not be compiled/executed in a way that reflects its intent.
