### ISSUE TITLE
platform-appropriate command key shortcuts do not work on macOS

### ISSUE THREAD

**Issue by sneak** [darktable-org/darktable#7332]
**Describe the bug**

The keyboard shortcuts on macOS appear to be using 'control' instead of the platform-appropriate 'command'.

**To Reproduce**

Make an edit.  Command-Z is a no-op.  Control-Z appears to undo.

**Expected behavior**

Command-Z should undo.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: macOS

**Comment by MStraeten** [comment]
Duplicate to https://github.com/darktable-org/darktable/issues/4384
no bug, works as designed.
