### ISSUE TITLE
[darkroom duplicate manager] weird comparison behaviour when zoomed 200%

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7340]
**Describe the bug**

When zommed to 200% in darkroom and then try to click in duplicate manager on a different version, suddenly a weird border boarder appears. at full view or 100% it is all good

**To Reproduce**
see my screencast please
[check-duplicate-in-200percent_20201216-2020-12-16_18.49.10.zip](https://github.com/darktable-org/darktable/files/5705037/check-duplicate-in-200percent_20201216-2020-12-16_18.49.10.zip)

**Expected behavior**

same as in full view or 100% zoom

**Platform (please complete the following information):**
* darktable version : 3.5.0~ (I see that behaviour on master for quite some time)
* OS                : Linux - kernel 5.8.18-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-455.45.01-r1
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**

 - Can you reproduce with another Darktable version? **several versions in git master**
 - Can you reproduce with a RAW or Jpeg or both? **use RAW only**
 - Are the steps above reproduce with a fresh edit (removing history)? **yes**
 - Is the issue still present using an empty/new config-dir **yes**

**Comment by AlicVB** [comment]
Confirmed, hopefully this won't be too hard to fix as the duplicate still appear at the right place with the right size... I'll have a look

**Comment by AlicVB** [comment]
Ok, finally not so easy :( #7344 fix the issue, although not in the ideal way (see comment on the PR)
