### ISSUE TITLE
z 7II white balance

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#7348]
z 7II white balance. I didn't include Natural light auto Approx. 4500–8000 K.
[darktable-whitebalance-20201218.tar.gz](https://github.com/darktable-org/darktable/files/5714616/darktable-whitebalance-20201218.tar.gz)

**Comment by johnny-bit** [comment]
We don't have Z7II support yet. You have to wait untill #7282 is closed :)

**Comment by PeterWem** [comment]
It is from the same camera ^^

**Comment by johnny-bit** [comment]
As promissed: #7282 is closed and so #7755 can happen :)
