### ISSUE TITLE
History stack is lost on the source image when a style is applied in overwrite mode.

### ISSUE THREAD

**Issue by majobu** [darktable-org/darktable#7352]
History stack is lost on the source image when a style is applied in overwrite mode. Changes on crop and roate module lost on source and destination

**To Reproduce**

1. make some edits to an image in darkroom and crop/rotate
2. leave darkroom
3. select edited image
4. expand "Style" menu
5. select overwrite mode in "Style menu
6. select "create duplicate"
7. double click a style

**Expected behavior**
The source image should remain as it was left in the darkroom. The duplicate should keep the applied style

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+5~g650c353cf
 - OS: Arch Linux - Kernel 5.9.14-arch1-1
 - OpenCL activated
 - Nvidia Geforce RTX 2060 Mobile 
   (lspci: 01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] (rev a1)) 

 - Can you reproduce with a RAW or Jpeg or both? Only tested on RAW
 - Are the steps above reproduce with a fresh edit (removing history)? Yes

**Comment by johnny-bit** [comment]
Your title doesn't really match what's going on exactly when trying to replicate... imo the title should be "Applying style with `create duplicate` in overwrite mode discards history on image"

Here's how it looks what's happening:
1. The target image has history discarded
2. the new virgin clone is made
3. the style is applied to virgin clone

evidently the 1st point shouldn't happen...
