### ISSUE TITLE
Inverting a raster mask causes the whole image to be changed by the module

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#7359]
dt 3.3.0+2085~gab91bf320-dirty    Ubuntu 18.04     No GPU

You have a module with a mask, and higher up the pipe another module is using it as a raster mask.  So far ok.  You now invert the raster mask in the higher-up module and notice that switching that module on and off causes the whole image to change, not just the part covered by the inverted mask.

This can be seen using the raw in the pixls.us item below and the attached XMP file (uploaded as .txt). Invert the mask in color correction to see the problem.

Please ignore the rest of the explanation in this post as it is wrong!

----------------------------------------------------
You have a module with a mask set up and all seems fine.  Then at a later stage in editing, the module is affecting the whole image.  You click on the mask button and the yellow mask looks fine.  But it still is being ignored.  (This is not the scenario where re-using a raster mask and you've turned the "source module" off)

This is very confusing and quite time-wasting.

Bill Martz discovered that a workaround is to duplicate the module here - https://discuss.pixls.us/t/deliberately-difficult-gamut-colors-in-macro-shot-of-hex-nut/20357/110
However I've been trying this and whilst it works initially, the duplicate can subsequently suffer the same problem.

In another image, I fixed one instance of the problem and then it happened in a different module later on.

This all leads to frustration.

The issue can be reproduced by taking the raw file in the above pixls post and loading this xmp which has been renamed to .txt -
[DSC08363-Nut-S-sRGB-freshDownload.txt](https://github.com/darktable-org/darktable/files/5719242/DSC08363-Nut-S-sRGB-freshDownload.txt)
Note that colour balance 1 mask excludes the nut but it is still altered by the module.

**Comment by ralfbrown** [comment]
You are re-using the `color balance 1` mask in `color correction`.  After turning off `color correction` (or setting it to not use a mask), toggling `color balance 1` no longer affects the nut.

OTOH, toggling the polarity of the raster mask in `color correction` changes the entire image whether or not `color balance 1` is active, so it looks like `color correction` may not actually be getting the raster mask (switching it to use the mask from `color balance 2` does show the expected behavior).

dt 3.3.0+2136

**Comment by RawConvert** [comment]
Thanks @ralfbrown , I am very embarrassed!  I reckoned to have checked it wasn't the "source module off" situation...
You'll see I've re-worded this issue to reflect what you have found, which I also get.

One difference though, I get both nut and background changing when using raster color bal 2 in color correction and with a plus sign next to it.  With a minus sign, it's working as I'd expect.

**Comment by ralfbrown** [comment]
Hadn't checked toggling the polarity on the cb2 mask.  I see the same as you when setting the raster mask to cb2 and then toggling cb2, whether the mask is positive or inverted.

**Comment by billmartz** [comment]
The effect of toggling the raster mask in color correction is not expected, my guess, because if you use a path in more than one module and toggle it in the second use, it does not affect the first use.

**Comment by RawConvert** [comment]
Just re-tested in dt 3.5.0+1966~g12d7a9967-dirty
Problem is still present
