### ISSUE TITLE
WB Canon EOS D30 (Raw files)

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#7366]
I tried to generate the WB with extract_wb_from_images.sh. Channel multipliers were not included this time. Is it possible to extract them from the raw files at all?
[D30.zip](https://github.com/darktable-org/darktable/files/5720078/D30.zip)

**Comment by johnny-bit** [comment]
Wow, that's nice old piece of DSLR :)

Unfortunately in RAWs you pasted... Well, while there MIGHT be wb data, it certainly is not in a format that's recognizable. All I can see is eg that file CRW_6972.CRW has "daylight" white balance, but in no tags is there recognizable WB coeffs data. Maybe there's something in `Canon Color Info 2` tag, but it has waaay too much datapoints.

So ultimately IMO there's no way to generate WB profiles from raws using extract_wb* scripts... however... you can always import all images into darktable and then read coeffs in wb using "as shot" (if you manually specify preset WB as shot will have that wb coeffs) and then created wb presets by hand.

**Comment by PeterWem** [comment]
With dcraw -v I got the following for all files:

multipliers 2.093285 1.000000 1.055975 1.000000

That is the same as in darktable (camera - neutral). Works great for daylight.

**Comment by johnny-bit** [comment]
This is problematic bacause the `CRW_6972.CRW` is "Daylight" and `CRW_6973.CRW` is "Cloudy". darktable correctly identifies multipliers in "as shot" mode for those files.

If you wish I can produce "handmade" wb presets for that camera then, but I'd need you to shoot color target for me then. So - similar setup as the files you've sent, just shoot color target please :)

**Comment by PeterWem** [comment]
Thanks! Should I buy X-Rite Color Checker Passport 2 or from Wolf Faust?

**Comment by johnny-bit** [comment]
any Datacolor SpyderCHECKR family or X-Rite Color Checker family is fine. 

If you don't have one and plan to use one I recommend Datacolor Spyder ones - i have SpyderCHECKR 24 and plan to get 48 one (passport). X-Rite ones here are like 2x the cost of Datacolor ones ;)

But don't get one just for this shot - if you don't have color checker and just want to use it one time to get EOS D30 WB it's better if you simply do a shot of anything non-moving so i can check if multipliers are ok ;) or just rent color checker for 1 day (it's like $2 here, or even free if you shoot the checker with your own equipment inside the rent shop studio)

**Comment by PeterWem** [comment]
A spydercheckr it will be.

**Comment by PeterWem** [comment]
Does this work?
[D30-Spydercheckr.zip](https://github.com/darktable-org/darktable/files/5743117/D30-Spydercheckr.zip)

**Comment by johnny-bit** [comment]
First glance looks OK. I'll try to see whether I can get anything out of there.

**Comment by PeterWem** [comment]
It seems LibRaw corrected wrong white balance from D30 this year. I will check tonight if I can find it again.

**Comment by LebedevRI** [comment]
As far as i can tell, rawspeed is currently always reading the `auto wb` temperature, not the `selected temperature`.
So i won't look into that any further
