### ISSUE TITLE
Segmentation fault at startup when mesa > 20.3.0

### ISSUE THREAD

**Issue by Lougavulin** [darktable-org/darktable#7377]
Hello,

When launch Darktable, no window appears and it does a segmentation fault error.
I tried both 3.2.1 or 3.0.2 Darktable versions.
With the backtrace, I found out it was Mesa and 20.3.1 version.
So I tried with 20.3.0, still segfault.
It work with Mesa 20.2.3.

 - Darktable Version: **3.2.1 and 3.0.2**
 - OS: **Slackware -current (to date)**
 - **OpenCL activated**
 - **HD Graphics 520**

I do build Darktable myself
```
cmake \
      -DCMAKE_C_FLAGS:STRING="-O2 -fPIC" \
      -DCMAKE_CXX_FLAGS:STRING="-O2 -fPIC" \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DMAN_INSTALL_DIR=/usr/man \
      -DDONT_USE_INTERNAL_LUA=Off \
      -DUSE_LIBSECRET=On \
      -DBINARY_PACKAGE_BUILD=1 \
      -Wno-dev \
      -DCMAKE_BUILD_TYPE=Release ..
```
I rebuilt it with 
`      -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`
for debug trace and gdb. Gdb.txt is attached.
[gdb.txt](https://github.com/darktable-org/darktable/files/5721459/gdb.txt)
The config dir does not change a thing, but I remove it between each test.

**Comment by Lougavulin** [comment]
I forgot the gdb.txt is for Darktable 3.2.1 with Mesa 20.3.1.

**Comment by parafin** [comment]
And what do you expect darktable to do about this? It's a crash in mesa, so it's their bug...

**Comment by Lougavulin** [comment]
OK, sorry.
I was wondering if it was useful.

**Comment by johnny-bit** [comment]
Maybe it was caused by this? https://www.phoronix.com/scan.php?page=news_item&px=Mesa-20.3-OpenCL-1.2-Clover

A very good idea: please file a bug on mesa gitlab and link here for posterity!
