### ISSUE TITLE
Building 3.4 fails on debian unstable using liblensfun2

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#7380]
**Describe the bug**

Building
Scanning dependencies of target ashift
In file included from /home/mir/git/darktable/build/lib/darktable/plugins/introspection_lens.cc:85:
/home/mir/git/darktable/src/iop/lens.cc: In function ‘lfModifier* get_modifier(int*, int, int, const dt_iop_lensfun_data_t*, int)’:
/home/mir/git/darktable/src/iop/lens.cc:347:60: error: no matching function for call to ‘lfModifier::lfModifier(const float&, int&, int&, lfPixelFormat, const int&)’
  347 |   mod = new lfModifier(d->crop, w, h, LF_PF_F32, d->inverse);
      |                                                            ^
compilation terminated due to -Wfatal-errors.
[ 86%] Built target colortransfer
make[2]: *** [lib/darktable/plugins/CMakeFiles/lens.dir/build.make:88: lib/darktable/plugins/CMakeFiles/lens.dir/introspection_lens.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5460: lib/darktable/plugins/CMakeFiles/lens.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**To Reproduce**

./build.sh --prefix /opt/darktable-3.4.x --build-type Release

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4 from git branch 3.4.x
 - OS: Debian Unstable
 - 
 - 

**Additional context**

**Comment by mir07** [comment]
Forgot:
dpkg -s liblensfun2
Package: liblensfun2
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 4709
Maintainer: zap@homelink.ru
Architecture: amd64
Version: 0.3.95.0
Depends: libglib2.0-0 (>= 2.0.0)
Description: lensfun built using CMake

**Comment by parafin** [comment]
Do not use 0.3.95, it's broken. As far as I understand you just have to use liblensfun1 instead of liblensfun2.

**Comment by johnny-bit** [comment]
use `liblensfun1`

**Comment by mikhailnov** [comment]
The same error is with current git master of liblensfun 0.3.95+ and liblensfun 0.2.x

**Comment by mikhailnov** [comment]
Commit https://github.com/lensfun/lensfun/commit/b135e05d729d66c5e595d350d78e6a7bbcab31da in liblensfun git master changed the API which darktable does not support. v0.3.95 must be supported in draktable.

**Comment by johnny-bit** [comment]
@mikhailnov - darktable has a goal of backward compatibility, meaning if you open your old edits made with older lensfun in new darktable build with new lensfun, the exported result (without touching anyching) should be roughly the same.
With 0.3.95 we've learned that it doesn't preserve edits and exhibits weird behaviour so for now its support is a bit shelved. This means issue https://github.com/lensfun/lensfun/issues/945 has to be solved. And once https://github.com/lensfun/lensfun/issues/1033 is fixed and api stable enough then sure, why not.

For that matter - darktable needs windows & osx devs and lensfun needs moar devs. Helping lensfun, helps darktable.
