### ISSUE TITLE
Scroll wheel action not recognized in some conditions

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#7382]
**Describe the bug**
Being in darkroom the scroll wheel action to zoom in/out might not been recognized.  

**To Reproduce**
1. Open image in darkroom
2. Make sure the tone equalizer module is **not** expanded
3. Apply a preset from the equalizer like `contrast tone curve...`

You can now observe two things:
1. The module knob is still active as
![Bildschirmfoto von 2020-12-21 07-21-14](https://user-images.githubusercontent.com/50982232/102745853-4004ad80-435d-11eb-8d25-9ff1740e30ff.png)
2. Scroll wheel can't zoom any more

**Expected behavior**
Probably applying a preset should not keep the module in active state, so the title of this issue might be misleading but might
be the most obvious problem observed.

**Platform**
dt master, OS and CL don't matter

**Comment by TurboGit** [comment]
Looks like an issue only in the tone equalizer. I'm wondering if this is not due to recent changes on accels handling.

**Comment by jenshannoschwalm** [comment]
Probably you are right. But I don't know where to fix, wouldn't it be better to fix 'keep module active'?

**Comment by TurboGit** [comment]
No, we want this module to be active when doing a **reset** or applying a **preset**. This idea is that as soon a module is used it must be active.

**Comment by TurboGit** [comment]
Should be fixed, the fix is queued for 3.4.1. Can you test on your side an report ? TIA.
