### ISSUE TITLE
Something weird going on in Retouch module in 3.3.0 build 2078

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#7383]
Hi Devs,
I've done a very short screen capture which I've put on youtube (as an unlisted video), which will show you exactly what weirdness is happening.
https://youtu.be/tQGZQDiDftU
Basically, the area containing the dirt to be cloned out is not being mapped properly.
Linux Mint 19.3, Cinnamon. GTX1050Ti graphics card.

**Comment by TurboGit** [comment]
Really strange indeed! I cannot reproduce locally even after playing with symmetry in crop&rotate and/or orientation module.

Do you reproduce that in all images?

**Comment by brucewilliamsphotography** [comment]
Pascal, sadly, yes!

**Comment by TurboGit** [comment]
Bruce, really strange that I cannot reproduce :( Is that using new edits (freshly imported images) ? What if you reset history and start again ? You built dt yourself ? If so, qhat says` git describe`  ?

**Comment by chhil** [comment]
Seeing its reported for  3.3.0 ....Didn't stuff get fixed in master where the offset of stuff being calculated was off?  It was related to PPD.

**Comment by TurboGit** [comment]
@chhil : you may be right, I don't know what 3.3.0 build 2078 is exactly. Bruce can you give us the sha1 of the last commit used to build this version of dt ?

**Comment by chhil** [comment]
I have a darktable-3.3.0+2033~g29bb7ed6f-win64 built on Dec 8.

**Comment by johnny-bit** [comment]
I honestly cannot replicate. works on 3.2.1 AND 3.5.0+65~g5ab3fa3af

**Comment by brucewilliamsphotography** [comment]
Guys, don't lose any sleep over this one. It's obviously something unique to my machine, and I'm currently on 2 weeks annual leave and will, in the next 12 hours or so, completely reformat this machine and install Mint 20 (something I've been wanting to do for 6 months!).
Once I'm back up and running, I'll grab 3.4 (if I can work out how again!) and we'll see how things look then. I suspect I have a lot of legacy crap on this system from various tinkerings over the last couple of years.
I won't close the thread in case someone wants to say more, but Pascal, feel free to close it if you deem that prudent.

**Comment by brucewilliamsphotography** [comment]
One last comment....
Just pulled down 3.3.0+2236~g3cca160f9 and the issue seems to be resolved.
As you were...
