### ISSUE TITLE
Drawn masks are not working

### ISSUE THREAD

**Issue by mtszsobczak** [darktable-org/darktable#7384]
**Describe the bug**
I am building latest versions of darktable and since couple of months Drawn masks are not working. I've searched issues and no one has the same problem, so this is probably something with my build, but I don't know how to 'reset' it. Probably I've built broken version of darktable and it left that way :(. I removed build cache, but it didn't help.

**To Reproduce**
1. Go to Drawn masks submenu
2. Add circle 
3. Display masks
4. You can see there is nothing selected (see screenshots)

**Expected behavior**
Drawn masks should select specified image area.

**Screenshots**
Drawn:
![image](https://user-images.githubusercontent.com/9355059/102764547-984aa800-437b-11eb-9c76-bf1aebcb4eaa.png)

Param:
![image](https://user-images.githubusercontent.com/9355059/102764577-a4366a00-437b-11eb-8d0f-2a80fb832f9a.png)

Drawn+Param:
![image](https://user-images.githubusercontent.com/9355059/102764634-bd3f1b00-437b-11eb-88d5-df3e921fd385.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+91~g95258fb40-dirty
 - OS: Ubuntu 20.04.1
 - OpenCL not activated
 - Intel i5 4xxx integrated gpu

**Additional context**
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
 ```
./build.sh --prefix /opt/darktable --build-type Release
sudo cmake --build "/home/mateusz/projects/darktable/build" --target install -- -j4
```

**Comment by johnny-bit** [comment]
remove darktablerc. My guess is that you have opacity=0 for drawn masks by default + you have hidden top bar where that opacity value is shown.

**Comment by mtszsobczak** [comment]
I removed rc file and I don't see a difference, I can see the opacity below blend mode (it can also be seen on above pictures), is there some other opacity that I don't see?
In the past, around all the changes to light table and cooling mode, some windows did appear and disappear between builds :D, so it might be the case that something is hidden.

**Comment by chhil** [comment]
![image](https://user-images.githubusercontent.com/1119439/102790980-539b2d00-43cc-11eb-81a4-87495a2808d1.png)

**Comment by chhil** [comment]
With 100% opacity

![image](https://user-images.githubusercontent.com/1119439/102791469-0ff4f300-43cd-11eb-9f58-fe5b8eee209d.png)


With 5% opacity you cant see the parametric intersection.
![image](https://user-images.githubusercontent.com/1119439/102791540-2bf89480-43cd-11eb-8706-ed89ad0435c4.png)

**Comment by mtszsobczak** [comment]
Thanks! It was the shape opacity! I totally missed that information on top.
