### ISSUE TITLE
Haze module and other modules that rely on dt_box_* cause image deterioration or crash when enabled 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7391]
WSL Ubuntu 20.04.1 LTS
Master : darktable 3.5.0+111~g3cca160f9

Compressed history to original.
Activate Haze module.
Image goes black.

![Haze](https://user-images.githubusercontent.com/1119439/102849237-bc21f280-443c-11eb-87d9-6b7ffd2033dd.gif)

Any image that was previously edited and has an active haze module in it, it goes black. Disabling it returns it to normalcy.

Problem is most visible with haze, but can cause problems/crashes with tone equalizer, bloom, soften, highpass and anything relying on dt_box_.

**Comment by chhil** [comment]
The distance slider is the problem. Varying it causes it image to go black.

**Comment by chhil** [comment]
Another problem with it is, if I compress history to everything below haze (remove haze from history), the haze module gets removed from history but is still active as seen in the image

![image](https://user-images.githubusercontent.com/1119439/102852259-df9c6b80-4443-11eb-95f7-18edabc29e85.png)

**Comment by jenshannoschwalm** [comment]
confirmed on todays master (fedora 33, opencl on) although here the first thing that goes wrong is the preview window.

**Comment by jenshannoschwalm** [comment]
One more detail, if i disable opencl the main darkroom image is wrong, so in my opinion there is clearly something wrong with cpu path. @ralfbrown this might be something for you?

**Comment by chhil** [comment]
I don't have opencl in my environment so definitely computations related to CPU path.

**Comment by MStraeten** [comment]
bisecting on osx (with darktable --disable-opencl) gave:
```
9d639026137d82f612c980b4d8ee9734333d98f0 is the first bad commit
commit 9d639026137d82f612c980b4d8ee9734333d98f0
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Sun Dec 6 20:58:12 2020 -0500

    improve vectorizability of dt_box_mean

 src/common/box_filters.c | 342 +++++++++++++++++++++++++++++++++--------------
 1 file changed, 241 insertions(+), 101 deletions(-)
```

**Comment by TurboGit** [comment]
@MStraeten : Thanks for the bisect. This patch has only been scheduled for 3.6 so plenty of time to fix.

@ralfbrown : Thanks for looking at this.

**Comment by TurboGit** [comment]
BTW, the PR was #7376.

**Comment by TurboGit** [comment]
And integration test 0026 is indeed failing too.

**Comment by ralfbrown** [comment]
Is that on LLVM-based builds?  GCC8 is fine on 0026; while it has a 1.7 dE, master without the PR had the same dE already.

We may have another case where the compiler needs to be worked around (like the time a few weeks ago where MStraeten replaced clamping with MIN/MAX macros instead of fminf/fmaxf to avoid a similar problem).

**Comment by cryptomilk** [comment]
I'm hitting this with gcc 10.2.1

**Comment by TurboGit** [comment]
Yes, me too: gcc (Debian 10.2.1-1) 10.2.1 20201207

```
Test 0026-haze-removal
      Image mire1.cr2
      CPU & GPU version differ by 2.79306e+06 pixels
      Max  dE         115.8949
      Mean dE         78.2222
      Count above max 2791475
  FAILS: image visually changed
         see diff.png for visual difference
         (2.79312e+06 pixels changed)


Total test 1
Errors     1
```

**Comment by cryptomilk** [comment]
The OpenCL codepath works for me.

**Comment by ralfbrown** [comment]
I guess I'll be upgrading my PC to the beta of my distro's next release, which includes GCC 10.2, next week....

**Comment by jenshannoschwalm** [comment]
Also on gcc -O3 march=native . I would just like to remind - i got hit by this while working on rcd - fmaxf vectorizes fine winth -O3. I don't know the code but are we sure we take care of properly testing for NaNs? If those are passed as cairo colors ...

**Comment by ralfbrown** [comment]
An easy way to check whether NaNs are being sent down the pipe would be running a debug build on the image+sidecar - it will print to stdout the min/max values in the buffer for each iop, and a warning if there are NaNs.

**Comment by chhil** [comment]
There is also the history issue associated to this and noted in comment
https://github.com/darktable-org/darktable/issues/7391#issuecomment-749345689

**Comment by johnny-bit** [comment]
@chhil - I have 2 things to ask you :)
1. can you change title of this issue (and description) to say that the problem is most visible with haze, but can cause problems/crashes with tone equalizer, bloom, soften, highpass and anything relying on dt_box_*?
2. With history issue - please check if you have same problem (meaning module not in history stays active) with modules not affected by dt_box_* problem? If so - please open separate issue for this.

**Comment by TurboGit** [comment]
The issue is in box_min_1ch() as replacing with the previous implementation from branch darktable-3.4.x fix the issue.

Since the same change has been made in box_max_1ch() we also probably want to check it.

**Comment by TurboGit** [comment]
Found the issue, looks like a stupid cut&paste, a PR is to come.

**Comment by chhil** [comment]
@johnny-bit 
I have fixed the issue and description text.

I will wait for the fix on 1 and open a new ticket if the history problem persists.

**Comment by chhil** [comment]
I can confirm the change made by @TurboGit  works, no more regression. Manually added the change to code , built and tested.
Thank you.

**Comment by TurboGit** [comment]
@chhil : Thanks for testing, I'll merge now.
