### ISSUE TITLE
Nightly PKG #49 Error opening file; can't install

### ISSUE THREAD

**Issue by billmartz** [darktable-org/darktable#7392]
**Describe the bug**

I downloaded darktable.3cca160f97bbf1adab252831202d57594922728b.win64.zip.zip from the Nightly PKG #6490 at https://github.com/darktable-org/darktable/actions/runs/436970645. I unzipped it and ran it. I immediately received the message shown below.

**Screenshots**

![image](https://user-images.githubusercontent.com/46618108/102858303-07fe7880-43f8-11eb-9d9a-fcbc39742995.png)

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: Windows 10 Pro
 - OpenCL activated
 - Nvidia GeForce GTX 1070 Game Ready Drive version 457.30

**Additional context**

**Comment by chhil** [comment]
Could you check if DT is not running in the background as an orphan via task manager (ctrl+shift+esc)?

**Comment by billmartz** [comment]
Yes it was. I thought I closed it. When I discovered it, the install went on without incident, but when I tried to open it I got this message:

![image](https://user-images.githubusercontent.com/46618108/102863909-46e4fc00-4401-11eb-9f7b-9cbb8877a961.png)

Reinstalling did not help.

**Comment by johnny-bit** [comment]
Nightly pkgs for windows are broken atm. we're working on it.
So this is essentially duplicate of #6856 

The release 3.4 is coming in just 2 days and that will work no prob :)

**Comment by billmartz** [comment]
Thank you both for your help.
