### ISSUE TITLE
Master windows build:  cannot find -lICU_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7394]
From git://github.com/darktable-org/darktable
   58298da86..3cca160f9  master          -> origin/master

```
...
...

- The following OPTIONAL packages have not been found:

 * libavif (required version >= 0.8.2)

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ICU_LIBRARY (ADVANCED)
    linked by target "lib_darktable" in directory C:/msys64/home/chill/darktable/src

....
...
...
[ 17%] Linking C shared library libdarktable.dll
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lICU_LIBRARY-NOTFOUND
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lICU_LIBRARY-NOTFOUND
collect2.exe: error: ld returned 1 exit status
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:2980: bin/libdarktable.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:2251: bin/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

**Comment by chhil** [comment]
Probably related to https://github.com/darktable-org/darktable/pull/7388

**Comment by chhil** [comment]
Is the version that msys has sufficient?

$ pacman -S mingw-w64-x86_64-icu
warning: mingw-w64-x86_64-icu-67.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-icu-67.1-1

Total Installed Size:  106.49 MiB
Net Upgrade Size:        0.00 MiB

**Comment by parafin** [comment]
I'm guessing FindICU.cmake fails on Windows - it finds icu package but fails to find libraries. Maybe pkgconfig supplied in Windows package is corrupted somehow or missing some info.

**Comment by chhil** [comment]
Did a git pull and tried building again and it built fine.
