### ISSUE TITLE
Copy part of history resetting and switching of exposure as well as color calibration

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7395]
**Describe the bug**

After creating a duplicate in lighttable, discard the history stack on that duplicate, copy the "crop&rotate", I found that exposure module as well as color calibration module are switched off and reset

....................
[Edit2]
I admit it is **likely related to "mode = overwrite"** in history-stack module but confusing is, the **duplicate module in darkroom** actually also **reacts on that mode without notice** (I found that "issue" in duplicate firstly) but that might be another issue

....................

**To Reproduce**
pleasae see my screencast
https://user-images.githubusercontent.com/49004103/102874752-2ccc0d80-4443-11eb-9b30-470ef9aeb536.mp4

[Edit1] if needed, I can put step-by-step description later, just now I am in a hurry, sorry.

**Expected behavior**

no inadvertent resetting of modules after copy

@AlicVB 
may I ping you here, as I have the feeling(!) you may know, what is going on?

**Platform (please complete the following information):**
* darktable version : 3.5.0+111~g3cca160f9
* OS                : Linux - kernel 5.10.2-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-455.45.01-r1
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by TurboGit** [comment]
Isn't this the expected behavior ? I don't see all settings on the screen cast, but copying a single module and pasting in overwrite mode seems to work as expected. You have the default mandatory module and the copied module. Or maybe this is something I missed ? The screencast is not easy to see as the font are very very small.

**Comment by AxelG-DE** [comment]
You are not the first one, knocking my forehead for this overwrite, hence I better close 😊
