### ISSUE TITLE
changed Processing of Lut3d module

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#7398]
commit fed438bc8984482a5cc23b0eb94d65e1609e76c5
Author: Aurélien PIERRE <aurelien@aurelienpierre.com>
Date:   Wed Nov 18 14:06:06 2020 +0100

    optimize in-pipe color spaces conversion for OpenCL

    fix the order of matrices multiplication

 data/kernels/colorspace.cl  |  6 ++----
 data/kernels/colorspaces.cl | 30 +++++++++++++++---------------
 src/common/iop_profile.c    | 19 ++++++++++++++++++-

changes the behaviour of Lut3d module:

before
![before](https://user-images.githubusercontent.com/39386816/102787470-69dfc380-43a1-11eb-8f17-6ead3e15c85e.jpg)

after
![after](https://user-images.githubusercontent.com/39386816/102787484-6fd5a480-43a1-11eb-8bb9-3cedc889c637.jpg)

used LUT:
![Apple Spectacular Cold](https://user-images.githubusercontent.com/39386816/102787670-ba572100-43a1-11eb-840a-e44c2ea56e0a.png)

on osx* with/without opencl enabled

xmp:
[mire1.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/5724879/mire1.cr2.xmp.txt)

_Originally posted by @MStraeten in https://github.com/darktable-org/darktable/issues/6968#issuecomment-749007562_

* this is darktable 3.5.0+124~g11abb2455
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by johnny-bit** [comment]
@aurelienpierre / @phweyland for this one?

**Comment by phweyland** [comment]
Don't know why, but I can just confirm (with the same lut):
before fed438b

![image](https://user-images.githubusercontent.com/23012047/103151433-e5a08e00-475c-11eb-9abc-dd9506b0a293.png)
 
on  fed438b
![image](https://user-images.githubusercontent.com/23012047/103151455-fb15b800-475c-11eb-9794-82c0d9bd1f86.png)

**Comment by phweyland** [comment]
In common/iop_profile.c
line 462, reverting the change (inverting the in and out matrix) I get back the previous lut behavior without opencl.
line 1528, inverting the in and out matrix, I get back the previous lut behavior with opencl

There may be a good reason for having made this change, using the natural natural direction from(in) -> to(out) makes things work.

**Comment by phweyland** [comment]
Seems that lut3d is the only module using dt_ioppr_transform_image_colorspace_rgb() for a process matter. All the other usages are related to color picker, histogram or other overexpose...

**Comment by phweyland** [comment]
@aurelienpierre do you want me to make lut3d work back or do you prefer to do it yourself for the potential side effects ?

**Comment by aurelienpierre** [comment]
Just seeing this, go for it @phweyland, it's just a matter of inverting the 2 matrices, there should not be side effects (anyway, the RGB -> RGB transform is not used elsewhere). I always get mixed between what's in or out matrix, so in my own code I explicitely name matrices XYZ_to_RGB or RGB_to_XYZ, it's easier to follow in later code.
