### ISSUE TITLE
Crash when opening Darktable on a very recent build (right after upgrading from 3.2.1)

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#7401]
Hello 

I was using 3.2.1 and upgraded to darktable_3.5.0~git126.56289d236_amd64.

I have a crash right on start, while thumbnails are  being drawn in lighttable. 
I obviously had no such issue before upgrading.

Ran darkatable -d all. It ended like this
```
[dev_pixelpipe] module `retouch' min: (-0,096381; -0,092769; -0,125991) max: (1,108104; 1,103785; 1,136561) [thumbnail]
8,038539 [add_job] 16 | 8,038563 load image 53844 mip 2 | queue: 1 | priority: 08,038566 
8,038586 [add_job] found job already in queue: 8,038591 load image 53844 mip 2 | queue: 1 | priority: 48,038596 
8,042221 [dt_view_image_get_surface]  id 53889, dots 264x264, mip 674x450, surf 264x176
double free or corruption (!prev)
/home/darktable_launch_DEBUG.sh: line 2: 379620 Aborted                 (core dumped) darktable -d all
```
**Not sure where to find the core. Anyone can help & indicate what info I shall provide?**

Any time I restart dt, it still crashes.
Same _double free or corruption (!prev)_ & _(core dumped)_ messages, but at another point in the pixelpipe.

And after n attempts, I got a different one
```
[dev_pixelpipe] module `exposure' min: (0,000000; -0,035288; -0,122893) max: (1,039529; 1,060360; 1,069174) [thumbnail]
6,408981 [sql] /usr/src/packages/BUILD/src/common/image.c:310, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
6,409147 [sql] /usr/src/packages/BUILD/src/common/image.c:395, function dt_image_path_append_version(): prepare "SELECT version FROM main.images WHERE id = ?1"
free(): invalid next size (normal)
```

Edit :
* I cannot find the ID of a maybe-guilty image.
* Not sure if this very issue has already been disclosed. Sorry if it has, could not find the issue in that case.
* Using the .deb file available here : https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable (always used this source, never had any issue)

Using
Kubuntu 20.10
KDE Plasma 5.19.5
QT 5.14.2
OpenCL supposedly on !
Intel Core i7-7700k + 32GB RAM + SSD + NVidia GFX 1070

Thank you !!

GLLM

**Comment by johnny-bit** [comment]
Can you run in either gdb or valgrind to produce backtrace?

**Comment by johnny-bit** [comment]
Also this might be a duplicate of #7391 and related - if the issue is fixed by current master fixes please mention that here and close the issue :)

**Comment by GLLM** [comment]
Just tested with darktable_3.5.0~git139.ca5a21527_amd64.deb : it still crashes.

I guess what you asked me (valgrind/gdb) requires I compile dt ? ... there's a first to everything :-)

**Comment by TurboGit** [comment]
@GLLM : Can you test #7416 ?

**Comment by GLLM** [comment]
@TurboGit Of course ! I will, as soon as a .deb is available in the site with the master binaries I use (see above) ;) It should not be long ...


I somehow managed to run dt in gdb (I'm wayyyy in over my head ... I'm not a dev, just a power user)
I managed to get this ...

(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7905864 in __GI_abort () at abort.c:79
#2  0x00007ffff7968af6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7a90128 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff797146c in malloc_printerr (str=str@entry=0x7ffff7a92640 "double free or corruption (!prev)") at malloc.c:5389
#4  0x00007ffff797333c in _int_free (av=0x7fffc0000020, p=0x7fffc00a6bb0, have_lock=<optimized out>) at malloc.c:4350
#5  0x00007fffc4945caf in  () at /usr/lib/x86_64-linux-gnu/darktable/plugins/libtoneequal.so
#6  0x00007fffc49658f1 in  () at /usr/lib/x86_64-linux-gnu/darktable/plugins/libtoneequal.so

And something tells me this, as such, is not useful .... as I dont see any function from libtoneequal wich yields the crash ...
Or am I wrong ?

**Comment by TurboGit** [comment]
Oh, you do not build from sources ? This is not yet on master. Please check the PR #7416 to see when it is merged.

**Comment by GLLM** [comment]
I will !
I'm not a dev but I can manage that : checking if the fix is merged, where, and make sure the .deb I use is using the build containing it.

**Comment by TurboGit** [comment]
@GLLM: the PR is now merged, so your can test as soon as a .deb is available. TIA.

**Comment by GLLM** [comment]
@TurboGit : yay ! no more crash @ darktable_3.5.0~git147.c50d2af91 :+1: 

Thanks you and @johnny-bit !!
