### ISSUE TITLE
Darktable 3.2.1 Linux x64: Mangled or Non-existent EXIF Data Export.

### ISSUE THREAD

**Issue by 0leron** [darktable-org/darktable#7403]
Darktable reads EXIF data from (Pentax) RAW files, but either does not export the data as expected, or corrupts it in some manner. Jpegs exported from DT do not yield EXIF data readable by Geeqie, GIMP, EXIF, or DeviantArt.com's upload script. The identical operation in RawTherapee passes EXIF data that can be read by all the above. 

**To Reproduce**
Simply export a RAW file to jpeg . The data is never passed.

**Expected behavior**
EXIF data from the RAW file, including ISO, shutter speed, etc, is passed to the jpeg in readable form to all apps that can read EXIF data.

**Comment by johnny-bit** [comment]
In export module in lighttable, next to `export` buton there's :gear: button. click on it and configure which data should be exported.

Check https://darktable-org.github.io/dtdocs/module-reference/utility-modules/lighttable/export-selected/ section https://darktable-org.github.io/dtdocs/module-reference/utility-modules/lighttable/export-selected/#including-metadata-in-the-exported-image

https://darktable-org.github.io/dtdocs/ is a great resource.

If this solves your problem, please close the issue :)

**Comment by 0leron** [comment]
Oopsie. Thanks =)
