### ISSUE TITLE
Panasomic Lumix G9

### ISSUE THREAD

**Issue by RafaelLinux** [darktable-org/darktable#7408]
When Darktable open a G9 RAW file, default adjustment are arbitrary, giving a image absolutely different to JPEG embedded image. User must adjust ALWAYS parameters to start on a similar to JPG image. 

You can compare screenshots attached:
- Darktable showing default adjustments compared to how it should be showed
- Digikam showing the embedded JPG from RAW (the most accurate image 

I think that some default adjustements should be applied to G9 RAW images when user open them, like with my GX8 or Sony RAW images!!! If I can help in some way, please, let me know.

Thank you

With my previous Panasonic GX8, default adjustment applied by Darktable was pretty accurate. 
![imagen](https://user-images.githubusercontent.com/13048959/102953827-76176e00-44d2-11eb-9f3b-3c73f710e0c3.png)
![imagen](https://user-images.githubusercontent.com/13048959/102954514-e7a3ec00-44d3-11eb-961a-d80a6d593fc6.png)

**Comment by chhil** [comment]
You haven't mentioned what version you are on. 

It depends on how you have setup your preferences. 
There is a setting to
1. See images in your filmstrip as the embedded jpeg or raw. 
2. There is a setting to pricess Yor image the old way using display eferred that applies a basecurve to try and match your sooc jpeg. 

Whichever version you are on if you want the image to be preprocessed, you need turn on our camera specific basecurve.

**Comment by johnny-bit** [comment]
Lumix G9 is already supported by darktable.

The way darktable processes image depends on your setting and matching OOC JPEG isn't a priority. The priority is allowing you maximum control.

There are 2 ways in which you can process image: display refered and scene refered. Display refered uses basecurve and tries mimic ooc jpeg. Scene refered uses filmic and allows more control over resulting image.

Have a look here: https://darktable-org.github.io/dtdocs/overview/workflow/edit-overview/

Whole https://darktable-org.github.io/dtdocs/ is a goldmine.
Also https://discuss.pixls.us/t/darktable-3-0-for-dummies-in-3-modules/15849 (whole pixls.us is goldmine of info)
And then videos by Aurelien Pierre on youtube...

As for how deep camera support goes: https://github.com/darktable-org/darktable/wiki/Camera-support
