### ISSUE TITLE
[FR] duplicate manager (darkroom) should replicate mode-switch from history stack (lighttable)

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7409]
**Is your feature request related to a problem? Please describe.**

The duplicate manager in darkroom *silently* follows the mode-setting (append or overwrite) of the history stack module in lighttable. 
That can get very confusing.

**Describe the solution you'd like**

The duplicate manager in darkroom should replicate that mode-setting, means have a switch as well (actually switching the same setting)

**Alternatives**

The duplicate manager in darkroom could have an independent  mode-setting

**Comment by chhil** [comment]
This history append / overwrite mode needs to be more accessible in darkroom.

If you are constantly copying history and pasting history in darkroom via the filmstrip one doesn't want to go to lightable view and change append/overwrite settings to be used in darkroom view. Had mentioned this in some issue which I can't find right now.

**Comment by MStraeten** [comment]
You can simply bring the mousepointer over the source image in the filmstrip (it’s highlighted then and it doesn’t need to be shown in main edit area), use ctrl+c or ctrl+shift+c  to copy
Then bring the mousepointer to the target image in the filmstrip or the. Ain edit window if the displayed image is your target and press ctrl+v or ctrl+shift+v

**Comment by chhil** [comment]
That does not remove the dependency on the append/overwrite mode that's set up in lightable view. You can copy or selectively copy, followed by a paste or selectively paste, but you have no control on what happens to the existing history of the target image unless you remember the mode (append/overwrite) you had once setup for history.

**Comment by parafin** [comment]
Do we have a shortcut for "discard history"? If so, I would vote for using append mode always in darkroom, because overwrite can be replicated by doing discard first.

**Comment by AxelG-DE** [comment]
I would be fine with the proposal of @parafin, as long no silent "carry over" from setting in lighttable's history-stack module

**Comment by AxelG-DE** [comment]
ping
