### ISSUE TITLE
Crash when applying a style from darkroom if one of the styles has no description

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#7425]
**Describe the bug**
If you have one or more styles and one of them has no description, then clicking the "quick access for applying any of your styles" icon in darkroom crashes Darktable.

**To Reproduce**
* Make a style without description
* Go to darkroom
* Click the ![image](https://user-images.githubusercontent.com/16192496/103089310-e6ff7880-45ed-11eb-894d-04abfa9add59.png) icon.

**Platform (please complete the following information):**
 - Darktable Version: 3.4 and also 3.2.1
 - OS: Windows 10
 - OpenCL not active

**Workaround**

Add a description to each and every style

### Traceback:
[darktable_bt_JV28V0.txt](https://github.com/darktable-org/darktable/files/5739569/darktable_bt_JV28V0.txt)

**Comment by johnny-bit** [comment]
No longer reproducible with current master
