### ISSUE TITLE
OSX: Waveform histogram looks strange in darktable 3.4

### ISSUE THREAD

**Issue by ykhrol** [darktable-org/darktable#7429]
**Describe the bug**

Since I've updated to 3.4 waveform histogram looks incorrect on MacOS Catalina 10.15.7. It uses strange colors (yellow, brown, dark blue) and it is dense and opaque (see screenshots below).

**To Reproduce**

1. Open darkroom 
2. Set histogram mode to waveform.

**Expected behavior**

I expected waveform histogram to look similar to 3.2.1. 

I've checked the manual and it contains screenshots of waveform as it was before (see image below).
I've also watched some [youtube tutorials](https://www.youtube.com/watch?v=lFv5ifVjedQ&ab_channel=BorisHajdukovic) and waveform looked fine in it. AFAIR author is on some Linux OS. Hence I _assume_ it is MacOS specific

**Screenshots**

***Strange waveform histogram***
![image](https://user-images.githubusercontent.com/1930906/103098513-0c0ae000-461c-11eb-86a3-b6fce0e2c634.png)
![image](https://user-images.githubusercontent.com/1930906/103098536-25139100-461c-11eb-97a1-04a7cc64a181.png)

***Regular histogram of the same image looks fine***
![image](https://user-images.githubusercontent.com/1930906/103098498-00b7b480-461c-11eb-8ce4-40ee23d9cab0.png)

***Expected (from darktable manual)***
![image](https://user-images.githubusercontent.com/1930906/103098394-a6b6ef00-461b-11eb-9c60-24a8456572fe.png)
![image](https://user-images.githubusercontent.com/1930906/103098403-ad456680-461b-11eb-8d82-cac2296c8fa7.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4 (seen it on 3.3 and 3.5 dev builds as well)
 - OS: MacOS Catalina 10.15.7 on MacBookPro15,1
 - OpenCL activated 

**Additional context**

- Tried cleaning up the ```~/.config/darktable``` folder. Settings were reset to defaults. Issue persisted.
- Regular histogram view looks correct.
- Dev builds I used was from [pixls.us](https://discuss.pixls.us/t/current-osx-build/13213/179)

**Comment by ykhrol** [comment]
hey @MStraeten 
seems like you've faced with some performance issues with waveform histogram enabled on OSX darktable-org/darktable#7307
does the histogram itself look like it was before? 
wonder if you see anything like I've got (see screenshots above)?

**Comment by MStraeten** [comment]
There were several commits targeting histogram - and the current behaviour is the result ;) but that doesn’t correlate to the performance issue since the performance is ok in other modules

**Comment by ykhrol** [comment]
thanks, Martin! 
sorry I wasn't clear in my request to you. I don't think the histogram problem is related to the issue you've experienced. I just found you as a darktable user on OSX who was recently using the waveform histogram view and was wondering if you are experiencing the same behavior. to confirm it isn't local to my setup

**Comment by johnny-bit** [comment]
@dtorop this one might be up your alley :)

**Comment by dtorop** [comment]
@johnny-bit Thank you for pointing me to this. Almost certainly this results from code which I changed. The only hope would be that it's up my alley to fix this. I'm also worried that this and #7307 both appear to be specific to OS X.

The histogram drawing code in v3.4 is substantially different than in v3.2. One guess is that the code now does something undefined in Cairo which works everywhere but on OS X. An example would be something wrong with an alpha channel.

I don't see anything obviously wrong in the code -- excepting that it looks possible to rewrite the first loop in `_lib_histogram_draw_waveform_channel()`:

```diff
-    for(int k = 0; k < 3; k++)
+    for(int k = 0; k < 4; k++)
      wf_display[p+k] = src * primaries_linear[ch][k];
-    wf_display[p+3] = src;
```

if `primaries_linear[:][3]` is set to 1.0f rather than 0.0f.

In combination with #7307 this makes me wonder if there's a bad OpenMP interaction on OS X.

Another suspect would be that waveform now uses profile code from iop_profile.c as a shortcut for fast gamma processing. Could this produce an unforeseen consequence for OS X? All the iop_profile code *should* just be CPU math, nothing OS-specific, but this is a big change.

Questions for @ykhrol:

- Is this only with waveform histogram or both with waveform and RGB parade?
- Do you feel comfortable recompiling the code? I'm not even sure what to suggest changing, though, at this point. (I don't have a good OS X setup here, alas.)
- Are you seeing the slowdowns in waveform as reported in #7307?

I'm a bit at a loss here, but clearly there's something wrong, and there must be a way to fix it!

**Comment by ykhrol** [comment]
Hey @dtorop 
- Both waveform and RGB parade affected (see screenshots in the issue)
- I can give it a try some time later. But last time I tried to compile from source, I failed due to some conflicting packets on macports and homebrew I use to setup work env. 
- Yeap, crop&rotate is sluggish and takes significant time "working" while histogram is in waveform mode, though works fine with regular histogram

**Comment by MStraeten** [comment]
histogram for the same picture (just opened with two builds and plain new \~/.config/darktable without any css tweaks) 
build darktable 3.3.0+1216~gd770bf524 (Oct. 25)
<img width="359" alt="Bildschirmfoto 2020-12-26 um 11 56 05" src="https://user-images.githubusercontent.com/39386816/103150479-ecd39600-4774-11eb-994b-f48cc53f5c75.png">
current 3.4.x:
<img width="355" alt="Bildschirmfoto 2020-12-26 um 11 57 44" src="https://user-images.githubusercontent.com/39386816/103150489-fbba4880-4774-11eb-9026-299d4d62639e.png">

**Comment by MStraeten** [comment]
seems to be a side effect of paralleization. see https://github.com/darktable-org/darktable/issues/7307#issuecomment-751350032

**Comment by dtorop** [comment]
> seems to be a side effect of paralleization. see [#7307 (comment)](https://github.com/darktable-org/darktable/issues/7307#issuecomment-751350032)

Good news --- I think. Except that now we have this worse muddle of OS X compiler giving us weird code. Is it worth doing something like disassembling the code which OS X clang generates??

**Comment by dtorop** [comment]
I can replicate this on a Linux machine:

![image](https://user-images.githubusercontent.com/2311860/103255735-7a231000-4958-11eb-9a9a-7854ef3d4cd7.png)

This is by using:

```c
#ifdef _OPENMP
#pragma omp parallel default(none) \
  firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  shared(wf_linear)
#endif
```

for the loop in _lib_histogram_process_waveform(). I'm using a slightly stale checkout of "master" (c35c38b34ee8f3ab91e20b37363f1f7c30b65603).

If I remove the OpenMP code altogether for the loop, I see something better:

![image](https://user-images.githubusercontent.com/2311860/103255813-ca9a6d80-4958-11eb-9615-548b521500ce.png)

The same goes if I use the OpenMP which is in v3.4.0:

```c
#ifdef _OPENMP
#pragma omp parallel for simd default(none) \
  dt_omp_firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  dt_omp_sharedconst(wf_linear) \
  aligned(input, wf_linear:64) \
  schedule(simd:static, bin_width)
#endif
```
or in master 722e29653c481f6973b7650d069a1a77de3e07ad:

```c
#if defined(_OPENMP) && !defined(__APPLE__)
#pragma omp parallel for simd default(none)                             \
  dt_omp_firstprivate(input, width, height, wf_width, bin_width, _height, scale) \
  dt_omp_sharedconst(wf_linear) \
  aligned(input, wf_linear:64) \
  schedule(simd:static, bin_width)
#endif
```

I'll look into this more.

**Comment by dtorop** [comment]
Ummm... I should note that my test code which causes this on Linux is `#pragma omp parallel default(none)` and should be `#pragma omp parallel for default(none)`. Adding the "for" fixes things. I'm not sure if this elucidates the OS X bug or not.
