### ISSUE TITLE
Install error on Windows 10

### ISSUE THREAD

**Issue by nfbastro** [darktable-org/darktable#7430]
Install seems to go fine. But error box appears when trying to start.
"An unwanted exception occurred"
Report entered below.

![image](https://user-images.githubusercontent.com/76566772/103100485-c1b83d80-45e0-11eb-97b5-f448869a1a79.png)

Bug report.
this is darktable 3.2.1 reporting an exception:

-------------------

Error occurred on Thursday, December 24, 2020 at 11:55:00.

darktable.exe caused an Access Violation at location 00007FF9F7B8EE5F in module igdrclneo64.dll Reading from location 0000000000000038.

AddrPC           Params
00007FF9F7B8EE5F 00000000000A5020 000000000061E400 0000000000000000  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF9F7B8F0E5 0000000008BFE5A0 000000000061E440 000000000061E469  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF9F7A0CF7F 0000000000000000 0000000000000000 0000000000000000  igdrclneo64.dll!0x7ff90001cf7f
00007FF9F7A0CEEF 0000000005F324F0 0000000005F32580 0000000000000000  igdrclneo64.dll!0x7ff90001ceef
00007FF9F7B670D0 00000000001233A0 00000000001230F0 0000000000000000  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF9F7B66E48 0000000000000000 00000000000003F0 0000000005F324F0  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF9F7B66F3C 00007FF9F7E69480 0000000005F324F0 000000000893BAE0  igdrclneo64.dll!clGetGLContextInfoKHR
00007FF9F7A0C33B 000000000893B9F0 00007FF9F7E69480 000000000893B9F0  igdrclneo64.dll!0x7ff90001c33b
00007FF9F7A230C5 000000000009ADC0 000000000893B9F0 0000000000000001  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FF9F7A5D564 0000000000000001 0000000000000001 000000000893B9F0  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FF9F7A5CF3D 00004B4F2BE24DC5 0000000000000000 0000000000000000  igdrclneo64.dll!clGetKernelSubGroupInfoKHR
00007FF9F7A0D10E 00000000092DC990 0000000000000000 0000000000000000  igdrclneo64.dll!clGetPlatformIDs
00007FF9F7A141E9 00000000092DC9B0 00007FF9F7A13C80 00000000092DC990  igdrclneo64.dll!clEnqueueTask
00007FF9F84132B5 00007FFA22713C10 0000000000000000 0000000000000000  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FF9F83DC85B 00007FF9F83D48A9 00007FFA22733948 000000000061EE60  IntelOpenCL64.dll!clEnqueueWriteBufferRect
00007FFA226C118D 0000000000102C40 0000000000000000 00007FF9F83D0000  OpenCL.dll!0x7ffa0000118d
00007FFA226C71B8 00007FFA22733948 0000000004C6FEF0 0000000000000001  OpenCL.dll!clWaitForEvents
00007FFA4FB9AC00 0000000004AC72D0 0000000000000000 000000000061F4E4  ntdll.dll!RtlRunOnceExecuteOnce
00007FFA4D3DE88B 0000000000000000 0000000000000014 0000000004C6FFF6  KERNELBASE.dll!InitOnceExecuteOnce
00007FFA226C5B9C 0000000000000300 0000000004AC72D0 0000000004C3FB60  OpenCL.dll!clGetPlatformIDs
000000006366FFCD 000000000061F8A0 0000000000000000 0000000000000000  libdarktable.dll!dt_opencl_init
00000000635E84D1 00007FFA00000001 0000000001E0DB20 00007FFA00000001  libdarktable.dll!dt_init
0000000000402A79 0000000000401670 0000000000000010 0000000000000000  darktable.exe!0x2a79
00000000004015C5 000000000000005A 0000000000000000 00000000004070A0  darktable.exe!0x15c5
00000000004013E4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x13e4
0000000000401516 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x1516
00007FFA4E1F7034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFA4FBDD0D1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.2.1.0
ntdll.dll   	10.0.19041.662
KERNEL32.DLL	10.0.19041.662
KERNELBASE.dll	10.0.19041.662
msvcrt.dll  	7.0.19041.546
libdarktable.dll
libglib-2.0-0.dll	2.64.3.0
libintl-8.dll	0.19.8.0
GDI32.dll   	10.0.19041.685
ADVAPI32.dll	10.0.19041.610
sechost.dll 	10.0.19041.662
win32u.dll  	10.0.19041.662
RPCRT4.dll  	10.0.19041.662
gdi32full.dll	10.0.19041.685
libiconv-2.dll	1.16.0.0
ole32.dll   	10.0.19041.546
msvcp_win.dll	10.0.19041.546
ucrtbase.dll	10.0.19041.546
combase.dll 	10.0.19041.662
USER32.dll  	10.0.19041.685
SHELL32.dll 	10.0.19041.662
PSAPI.DLL   	10.0.19041.546
WS2_32.dll  	10.0.19041.546
libwinpthread-1.dll	1.0.0.0
libstdc++-6.dll
libgcc_s_seh-1.dll
libcairo-2.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.546
exchndl.dll 	0.9.2.0
WLDAP32.dll 	10.0.19041.546
libexiv2.dll
libgdk-3-0.dll	3.24.20.0
IMM32.dll   	10.0.19041.546
libgdk_pixbuf-2.0-0.dll	2.40.0.0
SETUPAPI.dll	10.0.19041.546
cfgmgr32.dll	10.0.19041.546
bcrypt.dll  	10.0.19041.662
libgobject-2.0-0.dll	2.64.3.0
libgphoto2-6.dll
libgmodule-2.0-0.dll	2.64.3.0
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libIlmImf-2_5.dll
libgtk-3-0.dll	3.24.20.0
libjson-glib-1.0-0.dll
libjpeg-8.dll
liblcms2-2.dll
lua53.dll
libpangocairo-1.0-0.dll	1.43.0.0
libpango-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpugixml.dll
libpcre-1.dll
libsoup-2.4-1.dll
comdlg32.dll	10.0.19041.662
libsqlite3-0.dll
shcore.dll  	10.0.19041.662
SHLWAPI.dll 	10.0.19041.546
libxml2-2.dll
MSIMG32.dll 	10.0.19041.546
libfontconfig-1.dll
libssp-0.dll
libfreetype-6.dll	2.10.2.0
mgwhelp.dll 	0.9.2.0
libpixman-1-0.dll
VERSION.dll 	10.0.19041.546
libexpat-1.dll
libbrotlidec.dll
libidn2-0.dll
libpsl-5.dll
libnghttp2-14.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.7
dwmapi.dll  	10.0.19041.546
gdiplus.dll 	10.0.19041.685
WINMM.dll   	10.0.19041.546
libcairo-gobject-2.dll
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.43.0.0
libexif-12.dll
libsystre-0.dll
libHalf-2_5.dll
libbz2-1.dll
libIlmThread-2_5.dll
libIex-2_5.dll
libImath-2_5.dll
libpangoft2-1.0-0.dll	1.43.0.0
libthai-0.dll
COMCTL32.dll	6.10.19041.488
WINSPOOL.DRV	10.0.19041.546
liblzma-5.dll	5.2.5.0
libharfbuzz-0.dll
dbghelp.dll 	10.0.19041.488
USP10.dll   	10.0.19041.546
libtre-5.dll
libgraphite2.dll
dbgcore.DLL 	10.0.19041.546
libgio-2.0-0.dll	2.64.3.0
libsecret-1-0.dll
libgomp-1.dll
libopenjp2-7.dll
libtiff-5.dll
libcrypto-1_1-x64.dll	1.1.1.7
zlib1.dll
libltdl-7.dll
libffi-7.dll
libfribidi-0.dll
librsvg-2-2.dll
libunistring-2.dll	0.9.10.0
DNSAPI.dll  	10.0.19041.610
IPHLPAPI.DLL	10.0.19041.546
libgcrypt-20.dll	1.8.5.54720
libzstd.dll
libdatrie-1.dll
libatk-1.0-0.dll	2.36.0.0
USERENV.dll 	10.0.19041.572
CRYPTBASE.DLL	10.0.19041.546
libbrotlicommon.dll
libgpg-error-0.dll	1.38.0.0
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.546
bcryptPrimitives.dll	10.0.19041.662
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.662
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.610
OLEAUT32.dll	10.0.19041.546
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.546
profapi.dll 	10.0.19041.546
mswsock.dll 	10.0.19041.546
MSCTF.dll   	10.0.19041.662
DEVOBJ.dll  	10.0.19041.546
WINTRUST.dll	10.0.19041.662
MSASN1.dll  	10.0.19041.546
Wintab32.dll	1.0.5.8
MPR.dll     	10.0.19041.546
HID.DLL     	10.0.19041.546
WTSAPI32.dll	10.0.19041.546
OpenCL.dll  	2.2.8.0
AppXDeploymentClient.dll	10.0.19041.662
dxgi.dll    	10.0.19041.546
igdrcl64.dll	23.20.100.9021
igdgmm64.dll	27.20.100.9021
dxcore.dll  	10.0.19041.546
igdfcl64.dll	27.20.100.9021
igc64.dll   	27.20.100.9021
IntelOpenCL64.dll	23.20.16.4973
igdrclneo64.dll
TextShaping.dll
textinputframework.dll	10.0.19041.662
CoreMessaging.dll	10.0.19041.610
CoreUIComponents.dll	10.0.19041.546
ntmarta.dll 	10.0.19041.546
wintypes.dll	10.0.19041.662
Oleacc.dll  	7.2.19041.546
SpTip.dll   	10.0.19041.1
SpeechUXPS.DLL	10.0.19041.1

Windows 10.0.19041
DrMingw 0.9.2

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment]
Issue is wit your OpenCL driver - Intel neo. Either update or remove it and the problem will be gone. Please fill an issue with driver maker - Intel.
