### ISSUE TITLE
Copy paste bug in common/exif.cc

### ISSUE THREAD

**Issue by qarmin** [darktable-org/darktable#7444]
https://github.com/darktable-org/darktable/blob/c50d2af91496cc88f1df40d91afe23c4beb61181/src/common/exif.cc#L2228-L2230

**Comment by johnny-bit** [comment]
Well... Couple lines above there's similar code for newer version of pugixml:

https://github.com/darktable-org/darktable/blob/545b7e804166094b28b81308455e2e4f1baca76e/src/common/exif.cc#L2203-L2205

However judging by the comment in place this code is referenced you might be right...

https://github.com/darktable-org/darktable/blob/545b7e804166094b28b81308455e2e4f1baca76e/src/common/exif.cc#L2854-L2856

**Comment by houz** [comment]
That looks like a copy&paste error indeed, the other lines next to it reference `Seq`. Good find.
