### ISSUE TITLE
v 3.4 image export works only for the first image you export

### ISSUE THREAD

**Issue by gpiroddi** [darktable-org/darktable#7446]
It is possible to export only 1 image

**To Reproduce**
1.Start  Darktable
2.Select an image in lignttable
3.Export
4.The image is exported correctly with message 'Export completed..."
5.Select another image
6.Export
7.Message "Exporting..."
8.No message of export completed
9.The image is not exported
10. Close Darktable
11. Start Darktable
12. Message "Darktable cannot be started because the database is locked..."
13. Follow instruction killing the process, deleting data.db.lock and library.db.lock
14. Start Darktable
15. repeat steps 2 to 13... same behavior
16. Start Datktable
17. do not export any image
18. Close darktable
19. Start again: works
-->

**Expected behavior**
steps 5 and 6 should always result in a correct export
step 10 should not leave the process running

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

 -  NO
 - 

**Additional context**

**Comment by sjjh** [comment]
@gpiroddi I cannot confirm (Ubuntu 20.04). I can export two (or more) pictures one by one without successfully. You can start darktable from a terminal to see if you get any error messages there.

**Comment by gpiroddi** [comment]
> @gpiroddi I cannot confirm (Ubuntu 20.04). I can export two (or more) pictures one by one without successfully. You can start darktable from a terminal to see if you get any error messages there.

HI @sjjh 
Starting from a terminal I only get the message related to the first successful export. Other export attempts do not work and there is no message on the terminal.
On the other hand closing darktable does not leave any running task.

**Comment by sjjh** [comment]
You can get more information with
```
-d {all,cache,camctl,camsupport,control,dev,fswatch,imageio,input,
               ioporder,lighttable,lua,masks,memory,nan,opencl,params,perf,
               pwstorage,print,signal,sql,undo}
```
(see man page). Maybe something helpful is included there, but I'm not having too much experience...
Otherwise I suggest to ask on the darktable-user mailing list or the pixls.us forum, maybe someone there has an idea on how to debug the issue further.

**Comment by johnny-bit** [comment]
my go-to recommendation is "start darktable with `-d all` and let's go from there.

**Comment by gpiroddi** [comment]
Hi both,
Thanks for suggesting me to post my problem in pixls.us forum.
I think the issue is in the combination of filters I have used. I have reworked the same pictures with different filters and everything is fine. soon or later I will discover the guillty filter :)

Giovanni
