### ISSUE TITLE
Zigzag patterns under highlight color recon.

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#7447]
I tried to use some heavyweight highlight color reconstruction in tandem with Filmic RGB and I got this

![Screenshot_20201225_130107](https://user-images.githubusercontent.com/2467520/103134460-9e10f800-46b1-11eb-8a4d-20db9bb4b79d.png)

It happens only when using color recon. mode in Highlight recon. module. It can be seen even without filmic RGB applied, but it's less noticeable.

Why those zig-zag patterns appear?

**Comment by maboleth** [comment]
Almost like a maze pattern:
![Screenshot_20201225_130949](https://user-images.githubusercontent.com/2467520/103134607-b9c8ce00-46b2-11eb-95ff-3167bc7ec5d4.png)

**Comment by johnny-bit** [comment]
Are you sure it's not mazing artefacts from demosaic algos?

**Comment by maboleth** [comment]
> Are you sure it's not mazing artefacts from demosaic algos?

Now that you said it, I tried it and yes, it seems to be affected by demosaic module. BUT unless using VNG4, no method eliminates this maze pattern.

If it's just the way things work on certain occasions, I will close this bug report, but thought maybe you guys needed to look at this for something under the hood.

So, only VNG4 method makes this sort of disappear, others don't work.

**Comment by maboleth** [comment]
Alright just checked DT's help file and it literally says this:

_"VNG4 produces the softest results of the three algorithms, but if you see “maze” artifacts with the other algorithms, try using VNG4 to eliminate them."_

So yeah, it's a feature issue so I will close this report as it's how the things work.

**Comment by johnny-bit** [comment]
There's also https://github.com/darktable-org/darktable/pull/7337 which you can watch :) it's for new RCD demosaicer.

**Comment by jenshannoschwalm** [comment]
I couldn't find it mentioned in this issue but to analys the demosaicer you have the image zoomed to 100% or more?

Color reconstruction in filmicrgb is sometimes tricky ... Or sometimes even more with 'preserve chrominance', have you checked with being OFF?

**Comment by maboleth** [comment]
> I couldn't find it mentioned in this issue but to analys the demosaicer you have the image zoomed to 100% or more?
> 
> Color reconstruction in filmicrgb is sometimes tricky ... Or sometimes even more with 'preserve chrominance', have you checked with being OFF?

1. Yes, I always check my images at 100%. It was at 100%.
2. FilmicRGB amplifies this to be very noticeable, but isn't causing the problem by itself. Tweaking the settings change how much these zigzag pattern show, but it's there regardless.

I have two options about this issue: either to use Highlight Reconstruction in luminace module or to change demosaic to VNG4.

**Comment by jenshannoschwalm** [comment]
Ok. Most likely this mazing can also be seen in the 'passing' demosaicers like monochrome or photosite. Is it possible to share the image? I would be interested very much to analyse myself too. I guess the cloth structure is behind the problem ...

**Comment by maboleth** [comment]
Alright, I included the xmp file too.
http://www.cvrkutanje.net/raw-for-test.zip

**Comment by jenshannoschwalm** [comment]
Thanks. Yeah, that maze is introduced by highlights reconstruction in overexposed areas only. As this module in the pipeline is before demosaicing it's wrong output is wrong input for **all** demosaicers. As the 'mazing' has a very high frequency this is not so obvious using VNG4. 

Personally i have this module disabled by preset here as it introduces such artefacts ... i also think this is better when using filmicrgb as that takes care of overexposing quite well.

Anyway, it's nothing we can do at the demosaicers.

**Comment by maboleth** [comment]
> Thanks. Yeah, that maze is introduced by highlights reconstruction in overexposed areas only. As this module in the pipeline is before demosaicing it's wrong output is wrong input for **all** demosaicers. As the 'mazing' has a very high frequency this is not so obvious using VNG4.
> 
> Personally i have this module disabled by preset here as it introduces such artefacts ... i also think this is better when using filmicrgb as that takes care of overexposing quite well.
> 
> Anyway, it's nothing we can do at the demosaicers.

Thanks, you're right, it still persists even in VNG4 but is manageable. Best is not to use highlight recovery module or to use luminance mode. I try to use filmicrgb as much as possible, but sometimes color recovery in Highlight module does a nice at coloring washed areas.
