### ISSUE TITLE
Sometimes filmstrip is showing only half of a thumbnail & other issues

### ISSUE THREAD

**Issue by maboleth** [darktable-org/darktable#7448]
Not sure why it happens, but sometimes when I select the image in LT and go to darkroom filmstrip doesn't show full thumbnail

![Screenshot_20201225_135919](https://user-images.githubusercontent.com/2467520/103135580-8d648000-46b9-11eb-9914-c6849c37f8f4.png)

I have also noticed that sometimes thumbnails in lighttable shows unedited image, without the latest changes.

Latest master version, arch linux.

**Comment by maboleth** [comment]
There's definitely some issue with thumbnails/filmstrip.
After deleting some files, the rest of thumbnails isn't displayed anymore in the filmstrip.

![Screenshot_20201225_150431](https://user-images.githubusercontent.com/2467520/103136678-ab82ae00-46c2-11eb-93d4-089c54ed3eaf.png)

@AlicVB Can you offer some hint here please?

**Comment by maboleth** [comment]
Hm, I turned off OpenCL support and the thumbnails reappeared.

I never had this problem before, OpenCl always worked flawlessly in DT. 

Can OpenCl guy help here?

I'm using AMD 5500 Radeon, Latest Mesa drivers overall, but OpenCl part is Amd proprietary due to Mesa not having Image size feature yet.

**Comment by Nilvus** [comment]
I never see that (and I use master) on my side. And I'm using Linux too (Ubuntu 20.10) but a Nvidia card. So maybe something related to drivers. On my side, Mesa drivers are on 20.2 release.

**Comment by maboleth** [comment]
> I never see that (and I use master) on my side. And I'm using Linux too (Ubuntu 20.10) but a Nvidia card. So maybe something related to drivers. On my side, Mesa drivers are on 20.2 release.

Well yes, I made a mistake of including two issues in one report, but I thought they were somehow connected.

But two things:

1. Small/broken thumbnail still happens even without OpenCL enabled.
2. I wasn't seeing this before in DT, even with the same Mesa drivers.

**Comment by AlicVB** [comment]
@maboleth : I've fixed what you described here recently (the "small" thumb, like cropped to something really tiny) So I'm closing. Don't hesitate to ask if the issue remain in master !
