### ISSUE TITLE
exposure : clipping threshold

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#7453]
**Describe the bug**
exposure : clipping threshold seems ineffective

**To Reproduce**
1. Go to 'darkroom'
2. Select 'exposure' module
3. Play with 'clipping threshod', nothing seems to happen

**Expected behavior**
This slider should do something ? Is that me ?

**Platform (please complete the following information):**
 - Darktable Version: 3.2, 3.4 & master
 - OS: GNU/Linux

**Additional context**
I'm not sure to have used this before, so maybe there is a misunderstanding about what it is about but I found really strange that nothing seems to happen when moving this slider.

**Comment by maboleth** [comment]
Well it does say you have to activate color picker to activate.

So after you select the region with the picker it does work.

**Comment by ralfbrown** [comment]
That's correct, it controls the autolevels-like process used with the color picker to set the exposure compensation.

**Comment by TurboGit** [comment]
Indeed, closing as there is no issue.

**Comment by TurboGit** [comment]
Thanks.
