### ISSUE TITLE
Difficult mask rotation on flipped image

### ISSUE THREAD

**Issue by FabianInostroza** [darktable-org/darktable#7459]
**Describe the bug**
If I try to use a mask on a image that has been flipped then rotating that mask is very imprecise, when I release the left mouse button the rotation is not what I expect.

**To Reproduce**
1. Load an image
2. Flip it (I tried vertical flip)
3. Go to exposure module and add a gradient mask
4. Try rotating the mask

**Expected behavior**
The mask is rotated correctly

**Screenshots**
Watch the video in: https://drive.google.com/file/d/1Dh3cq-CSsDO4mN2EJ7BRp63_zB6MjGTW/view?usp=sharing

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Debian testing
 - OpenCL not activated

**Comment by paolodepetrillo** [comment]
This should be fixed in version 3.4.0.  (Issue #7035 )

**Comment by johnny-bit** [comment]
Tried on 3.4.0 and current master - it's already fixed :)

Please try on 3.4 and report back if you still have issues and I'll reopen :)
