### ISSUE TITLE
Mac - Moving, zooming or modifying a parameter is extremely slow to refresh the image

### ISSUE THREAD

**Issue by muzius** [darktable-org/darktable#7463]
**Environment :**
iMac (27’ Retina 5K, 2015)
Processor 4 GHz i7
Ram 24 Gb
AMD Radeon R9 M390 2 Gb
macOS 11.1 before, 10.x : no différence
Darktable 3.2.1, 3.4.0, 3.4.1
Canon EOS 70D CR2 raw images (20-30 Mb)

**Steps to reproduce :**
In the darktable tab
if you move, zoom or change a parameter it takes at least 10 secondes to refresh an image and working is displayed
80% of the resources of the 8 CPU and the GPU are used to do the job.

**tests performed without improvements :**
- deleted Users/me/.config/darktable and Application/darktable folders and org.darktable.plist file before reinstallation
- .dmg and Homebrew installations
- OpenCL is working, worth when disable it. One environnement is available
`0.100343 [opencl_init]		0	'AMD Radeon R9 M390 Compute Engine'`
- Inside a Ubuntu VM on the same computer, Darktable is fast 1-2 seconds to refresh a image (not an option, the virtual machine cannot use the whole screen)

I was hoping the new version would fix the problem but no difference. The software is totally unusable under these conditions.

Thanks for this great software.

**Comment by caiux** [comment]
Same problem here on macbook pro, macbook air and iMac 21.5", all with macos 10.15.7 with or without OpenCL support. The only workaround I found was to descrease the resolution of the preview image to 1/3 or 1/4. It was already present in version 3.3.0+2096~g528512d78, compiled by myself, but not on previous versions of the 3.3.0 series I tried, e.g. 3.3.0+1519~g91b0be1b8.

**Comment by muzius** [comment]
The slowness is due to the denoise (profiled) module.
