### ISSUE TITLE
RfC: deprecate spot removal in 3.6?

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#7473]
Given that retouch is a complete superset of spot removal (even when limited to just the cloning tool, since spot removal doesn't include a brush), should spot removal be deprecated in the next release?

The only counter-argument I can think of is that the spot removal UI is less intimidating to newcomers.

**Comment by Nilvus** [comment]
I'm on for deprecate that module. Even the counter-argument is not sufficient as what does spot removal is possible exactly the same way in retouch module (with just quite some more options).

**Comment by TurboGit** [comment]
I'm for too. The only argument to keep spot removal would be its simplicity compared to Retouch but this would require to add the heal tool in it. Today I always use Retouch because the standard spot removal is harder to use.

**Comment by ralfbrown** [comment]
Addressed by #8712.
