### ISSUE TITLE
FR: Search/Sort by image orientation

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#7479]
Currently (as best as I can tell), there is no option to search or sort your images based on the orientation (portrait vs landscape).
Would this be simple enough to include?
The reason I ask is that I have a lot of old digital images (2004-2010) which for some reason, do not present the correct orientation information to darktable. And as a result, they all appear upside down in the lighttable view!
But interestingly, it ONLY affects images shot in a portrait orientation!
Having the option to sort by orientation would make it much quicker to find and correct these images.
And surely, other people would find a use for this sort option as well?

Currently running 3.4 (but this has been an issue for as long as I've been using darktable.. since 2.6 I think) on Linux Mint 20.

**Comment by TurboGit** [comment]
This is possible using the collect aspect ratio filter.

**Comment by johnny-bit** [comment]
It might be something for dtdocs, but anything with aspect ratio < 1 is portrait ;) Or maybe easy preset in collect module?

**Comment by TurboGit** [comment]
I have added presets for square/portrait/landscape images. PR is coming.

**Comment by TurboGit** [comment]
See #7487

**Comment by Nilvus** [comment]
Closing as it has been fixed by #7517
