### ISSUE TITLE
FR: Reset buttons for each TAB in Colour Calibration module

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#7480]
Aurélien,
Loving the new Colour Calibration module!
But given the number of adjustable parameters within it, I wonder if it would make sense to offer a Reset button for each tab*?
That way, if you start experimenting with radical parameters on one tab, you could click reset on just that tab, and not lose whatever modifications you have on other tabs (say, on the CAT tab).
Just a thought.

* Davinci Resolve (video NLE) offers this across its various colour tools, and it is a very handy feature!

**Comment by RawConvert** [comment]
? Or a way to toggle the R, G, B tabs all together, ie channel mixer,  between their settings and just "diagonal 1's".  And reset to diagonal 1's in one quick operation.
