### ISSUE TITLE
Crop and Rotate appears to be broken

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#7481]
darktable version ..... 3.5.0+207~gcbbef679f
When the crop and rotate module is closed/changed/opened the image immediately turns black.
A series of images that were edited yesterday are all showing the same problem if I try to change the format and when I use the c&r on a new image the problem is also seen.
Manjaro/Arch .. XFCE

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by AxelG-DE** [comment]
Also in conjunction with #7471 I tried this one here with 
- 3.5.0-185-ga6dc34f33
- 3.5.0-208-g3548ffb78

Both behave normal here.  But two clitches with crop&rotate make me keep eyes open

@davidvj could you please complete Platfrom and Additional context. They are there for a reason. Thanks! :)

**Comment by johnny-bit** [comment]
Cannot replicate on 3.4.0 or on 3.5.0+185 (and current master too)...

Additionally your report doesn't follow recommended pattern, there's no info whether you have opencl or not, there's no screenshots nor sample xmp files...

Please update your darktable to +208 (or newer. current master) and if problem persist please fill report completely providing as much data as possible and comment that you've done so. Until then I'm closing report as not actionable.
