### ISSUE TITLE
--datadir Do not work on DT 3.4.0 with WIN10

### ISSUE THREAD

**Issue by Jean-Marc68** [darktable-org/darktable#7482]
Hello. I think there's a bug with DT 3.4.0 on Win10 when --datadir is used. Why do I think that ?
Because I work on DT from my tower but time to time also from my laptop, the directories containing database, styles, etc. are on an external drive. 
To just have to connect the disk to the chosen computer and I find everything as it should, immediately, and any modification that I made on one workstation is repercuted on the other, I use --datadir and configdir. That was working till DT 3.2.1.
However, in this new version 3.4.0, the use of --datadir causes problem (for the --configdir everything is fine). 
When I use only --configdir everything is OK. But when I use --datadir, the visual is wrong (stars stay empty, visual not change when theme is changing, ...)
I maded a little video to let you see what's happening by me.

https://user-images.githubusercontent.com/510402/103162696-ba03bf00-47c1-11eb-864e-cdce8677c9ba.mp4

**Comment by Nilvus** [comment]
@Jean-Marc68: do you test that with 3.4.1.1 and reproduce on it? darktable 3.6 will be out in a week so If you still reproduce it on 3.4.1.1, please test also with 3.6 when possible and come back here to precise if this issue is fixed or not. If fixed, think about closing it. Thanks!

**Comment by Jean-Marc68** [comment]
Hi,
I'm with DT 3.4.1.1 on Win10 and the problem is still the same. If datadir is on my portable SSD, no stars are shown and no theme is avalable.
I'll try on 3.6 when it will be downloadable.
Thanks,JM    Le dimanche 27 juin 2021, 09 h 25 min 42 s HAE, Nicolas Auffray ***@***.***> a écrit :  
 
 


@Jean-Marc68: do you test that with 3.4.1.1 and reproduce on it? darktable 3.6 will be out in a week so If you still reproduce it on 3.4.1.1, please test also with 3.6 when possible and come back here to precise if this issue is fixed or not. If fixed, think about closing it. Thanks!

**Comment by Jean-Marc68** [comment]
Bonjour Nicolas,
I just installed DT 3.6.0. Unfortunately if I put "--datadir" with my external SSD path, I still not have styles nor stars. Everything is correct without "--datadir" in the pgm path.

JM
    Le dimanche 27 juin 2021, 09 h 25 min 42 s HAE, Nicolas Auffray ***@***.***> a écrit :  
 
 


@Jean-Marc68: do you test that with 3.4.1.1 and reproduce on it? darktable 3.6 will be out in a week so If you still reproduce it on 3.4.1.1, please test also with 3.6 when possible and come back here to precise if this issue is fixed or not. If fixed, think about closing it. Thanks!

**Comment by jenshannoschwalm** [comment]
Fell free to reopen if still valid on dt 4.4
