### ISSUE TITLE
Filmstrip and darkroom images turn black when switching modules on and off

### ISSUE THREAD

**Issue by tduell** [darktable-org/darktable#7483]
**Describe the bug**

A build of release-3.5.0-207-gcbbef679f has inverted colour issues.
I have had difficulty finding a pattern of operations that can repeatedly reproduce the effect I'm seeing, so can only describe a couple of examples and hope that it provides enough clues to the source of the issue.

**To Reproduce**

Starting this build ( release-3.5.0-207-gcbbef679f) and selecting a folder with images previously processed in a build of release-3.5.0-169-gecc48ae7a.
Example 1
---------
(1) I select an image which has the following modules 'ON',
'Sharpen', 'Shadows and Highlights','Haze Removal' 'Crop & Rotate','White balance'
(2) I then switch 'Crop & Rotate' 'OFF', the main image darkens but histogram remains unchanged.
(3) I then switch 'Crop & Rotate' 'ON, 'Haze Removal' 'OFF' and the filmstrip image goes black.
(4) I then switch 'Haze Removal' 'ON' and film strip image displayed correctly.
(5) I then switch 'Sharpen' 'OFF' and 'Haze removal' 'OFF' then switch 'Sharpen' 'ON' the main darkroom image turns black.

Example 2
---------
(1) I select an image which initially displays correctly with a build of release-3.5.0-169-gecc48ae7a, with modules 'Sharpen', 'Shadows and Highlights', 'Crop & Rotate', and 'White Balance' 'ON'.
(2) Switch 'Sharpen' 'OFF' and 'Shadows and Highlights' 'OFF' main image and filmstrip image displayed OK.
(3) Switch 'Sharpen' and 'Shadows and Highlights' 'ON' and main darkroom image goes black, filmstrip image OK.

**Expected behavior**

Switching modules ON and OFF should leave main darkroom image and filmstrip image displayed correctly.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  release-3.5.0-207-gcbbef679f
 - OS:  Linux Fedora 33
 -  No.
 -  Nvidia GTX 750Ti and nouveou driver

**Additional context**

I have only tried with a build of release-3.5.0-169-gecc48ae7a and that behaves as I expect it should.
I have only tried using RAW.
I have not reproduced with a fresh edit.
I compiled these versions of darktable, as I have for almost daily for the past few years. It is built using rpmbuild using Germano Massullo's rpm spec file. This spec specifies both GCC and Clang are required, I have not confirmed which compiler is in fact being used, but the build spec has been without error and not changed for some time

**Comment by TurboGit** [comment]
> (2) I then switch 'Crop & Rotate' 'OFF', the main image darkens but histogram remains unchanged.

You have a broken build. This step should not darken the image and I cannot reproduce.

**Comment by TurboGit** [comment]
So you'll need to investigate on your side and provide more context or a RAW + xmp to reproduce.

**Comment by tduell** [comment]
> You have a broken build. This step should not darken the image and I cannot reproduce.

OK. Thanks.
A build of release-3.5.0-218-ga34246950 isn't showing the reported issues.
