### ISSUE TITLE
dt 3.4 Windows 10 translation error with special characters

### ISSUE THREAD

**Issue by borjeJ** [darktable-org/darktable#7489]
Hello

In darktable 3.4 for Windows I found that if I have a special character in the path leading to the configdirectory the character is not translated correctly. This causes darktable to terminate. The log file can look like this:

========================================
version: darktable 3.4.0
start: 2020:12:25 09:42:49

darktable.configdir: directory ‘C:\Users\B├Ârje\AppData\Local\darktable’ fails to open.’

=====================================================================

The directory after Users should read Börje. This is something that worked fine in dt 3.2 but with 3.3 this failed. 
The chachdirectory is also affected by this problem.

**Comment by johnny-bit** [comment]
Hi @borjeJ ! I haven't noticed your report earlier, so yours would be "main" report... Instead more analysis happened in #7512...

that being said your IS earlier and has clear cut reason in it :) the cause (IMO) is PR #5086, Pinging @codingdave here.

**Comment by codingdave** [comment]
Can anyone having this issue please start darktable from the console providing the `-d dev` switch?

    C:\Program\Path\To\darktable.exe -d dev

(Update the path accordingly).
Please paste the complete, unmodified output.

**Comment by andreilabato** [comment]
result is empty: 
C:\Program Files\darktable\bin>darktable.exe -d dev
C:\Program Files\darktable\bin>

**Comment by borjeJ** [comment]
Hello

:::This is the output from running dt from command line. Ie nothing.

C:\Program\darktable\bin>darktable -d dev

C:\Program\darktable\bin>

::: This is the entry in the darktable-log file

========================================
version: darktable 3.4.0
start: 2020:12:28 15:52:38

0.000000 application_directory: C:\Program\darktable\bin
0.000999 darktable.datadir: C:\Program\darktable\share\darktable
0.000999 darktable.plugindir: C:\Program\darktable\lib\darktable
0.001996 darktable.localedir: C:\Program\darktable\share\locale
darktable.configdir: directory 'C:\Users\Börje\AppData\Local\darktable' fails to open.'

::: You can verify that the configdir does exist. 

C:\Users\Börje\AppData\Local\darktable>dir
 Volume in drive C is Windows
 Volume Serial Number is 12B3-17E9

 Directory of C:\Users\Börje\AppData\Local\darktable

2020-12-28  15:51    <DIR>          .
2020-12-28  15:51    <DIR>          ..
2020-12-25  10:17    <DIR>          contrib
2020-12-27  13:22            35 475 darktablerc
2020-10-04  09:14            58 824 darktablerc.old
2020-10-11  08:29            56 215 darktablerc.old1
2020-12-27  11:26           950 272 data.db
2019-11-28  20:21           385 024 data.db-pre-3.0.0
2020-03-11  09:15           495 616 data.db-pre-3.0.1
2020-04-18  07:36           548 864 data.db-pre-3.0.2
2020-06-18  15:34           614 400 data.db-pre-3.1.0
2020-08-10  09:40           851 968 data.db-pre-3.2.1
2020-12-25  19:31           884 736 data.db-pre-3.4.0
2019-10-28  08:36           122 531 keyboardrc
2020-12-27  11:26           232 128 keyboardrc_default
2019-12-07  14:47        49 512 448 library - kopia.db
2020-12-27  11:39       103 153 664 library.db
2019-11-28  20:21        48 168 960 library.db-pre-3.0.0
2020-03-11  09:15        79 233 024 library.db-pre-3.0.1
2020-04-18  07:36        83 263 488 library.db-pre-3.0.2
2020-06-18  15:34        83 263 488 library.db-pre-3.1.0
2020-08-10  09:40        88 244 224 library.db-pre-3.2.1
2020-12-25  19:31       102 858 752 library.db-pre-3.4.0
2018-12-23  22:03        14 614 528 libraryold.dat
2020-02-06  11:01                64 luarc
2019-01-23  09:20               125 luarc.txt
2020-12-25  10:17    <DIR>          styles
2020-12-25  09:33           249 151 Uninstall.exe
2020-12-25  23:18                35 user.css
              25 File(s)    657 798 004 bytes
               4 Dir(s)  91 708 403 712 bytes free

C:\Users\Börje\AppData\Local\darktable>

::: In my case I moved the configdir and the cachedir to a path outside \Users\Börje and now it works just fine.

**Comment by eulejd** [comment]
I have the same problem with my user-directory which is called "Jürgen". When starting darktable it flashes for a second, then nothing happens. Meanwhile I've reinstalled 3.2.1. which works without problems.
What can I do (except renaming my user-directory)?
Thanks for help

**Comment by johnny-bit** [comment]
you could create new dir without special characters and point darktable at it via commandline... or for time being keep using 3.2.1 untill new release with fix to this problem is released.

**Comment by eulejd** [comment]
Thank you for your quick answer. I will wait.

**Comment by andreilabato** [comment]
> you could create new dir without special characters and point darktable at it via commandline... => what is the command line to be used with this new folder? 
>or for time being keep using 3.2.1 untill new release with fix to this problem is released.=> would it be a patch soon released or waiting a version (6 month delay)?

**Comment by johnny-bit** [comment]
> what is the command line to be used with this new folder?

add to darktable shortcut `--config-dir [new dir]

> would it be a patch soon released or waiting a version (6 month delay)?

That depends on when will the issue here be fixed... but release 3.4.1 IS planned, just needs to accomodate enough fixes to justify release ;)

**Comment by andreilabato** [comment]
I copied my C:\Users\username\AppData\Local\darktable folder in C:\. Then following command line does not work (same behaviour as previsouly):
C:\Program Files\darktable\bin>darktable --configdir C:\darktable --library C:\darktable\library.db

**Comment by borjeJ** [comment]
I changed my commandline to
darktable --configdir d:\darktable --cachedir d:\darktable-log

This works for me, You have to include the cachdir

**Comment by andreilabato** [comment]
works fine now. Thks!

**Comment by rattkin** [comment]
What I did to make it work:
Create a directory junction link to the user profile folder.
```
mklink /j c:\darktableTmpProfileLink "c:\Users\Jan Müller"
```
I want to keep my library in my user profile, where it is backed up.

Then specify the new path to the user profile + cache directory apparently must be set as well
```
"C:\Program Files\darktable\bin\darktable.exe" --configdir c:\darktableTmpProfileLink --cachedir c:\tmp\darktableCache
```

**Comment by codingdave** [comment]
@rattkin, @andreilabato, @borjeJ, @eulejd, is anyone of you able to compile #7721 and give feedback about success/issues?
Also to know your OS language and codepage would be nice to know. You can just open a powershell and type

    dhcp
    [CultureInfo]::InstalledUICulture
    [CultureInfo]::CurrentCulture
    [CultureInfo]::CurrentUICulture

Thank you in advance.

**Comment by rattkin** [comment]
Much obliged!
```
PS C:\Users\Jan Müller> dhcp
dhcp : The term 'dhcp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dhcp
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (dhcp:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Jan Müller> [CultureInfo]::InstalledUICulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)


PS C:\Users\Jan Müller> [CultureInfo]::CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)


PS C:\Users\Jan Müller> [CultureInfo]::CurrentUICulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

**Comment by codingdave** [comment]
Sorry there is a typo: chcp instead of dhcp

**Comment by borjeJ** [comment]
Hi

This is the output from PowerShell

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> chcp
Active code page: 850
PS C:\WINDOWS\system32> [CultureInfo]::InstalledUICulture

LCID             Name             DisplayName
----             ----             -----------
1053             sv-SE            Svenska (Sverige)


PS C:\WINDOWS\system32> [CultureInfo]::CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
1053             sv-SE            Svenska (Sverige)


PS C:\WINDOWS\system32> [CultureInfo]::CurrentUICulture

LCID             Name             DisplayName
----             ----             -----------
1053             sv-SE            Svenska (Sverige)


PS C:\WINDOWS\system32>

Sorry to say I do not have a compiler on my system.

**Comment by andreilabato** [comment]
OS language should be french

C:\Users\andré>chcp
Page de codes active : 850
Sorry to say 
- other commands do not work.
- I do not have a compiler on my system.
Thanks ;-)
