### ISSUE TITLE
3.4 version is totally buggy for us

### ISSUE THREAD

**Issue by petercfischer** [darktable-org/darktable#7491]
we are having insurmountable problems [extremely frustrated and stressed] getting your program to run in its new iteration...we've been a user for years [but with the revised database the older versions we have will also not install either] . 

very very very frustrated.. in fact after all these years invested in this software will soon turf the program entirely, if we can't get some help here...just getting in contact with our [as we don't have a phone] is an ordeal...

please get someone with a pulse to contact us to get this started...if that request is beyond your protocols then just let us know you are not prepared to help us and we're gone...

we even got on your mailing list...we don't need that much incoming stuff...

we do need some help getting you 3.4 iteration to work properly on our W10 box...have been a loyal user with lot's of time and tears invested to this point... over that time we've had our speed bumps but this one takes the cake...

when getting a'hold of you leads to this much wasted time [hours not only involving repeated uninstall\reinstall for us] the frustration has us seriously question the validity of your program in our photo workflow --- as we have over 25 other editor which share one common attribute:  they work!!!

trust me most of the time we are just calm cool and collected... but this has really got us in a twist...

we download directly from your site...first time and again, with uninstalls in between...general rule of thumb is each new iteration opened just one image (not necessarily the same one), then when any other was selected the program just froze up... crashed out...

we simply cannot get 3.4 to open any of our images, even from a completely different drive [ie. a remote drive connected the computer in question as opposed to sourcing the image from the local computer drive]...attempts to install older versions of the program subsequently also failed - but then don't even load, only show up as resident on the drive.

there is one exception: we have DT designated to open our GIMP neh files, which it does automatically performing any edits we want and auto sends the outcome back over to GIMP

if this is so,  what is the fix ?  as we don't care if our old edits are unavailable to us, we can't even open the image.  furthermore the new iteration doesn't even show us the option to have a second screen attached to the work in progress

essentially the whole thing is one buggy mess!  the last iterations [version 3.2; 3.2.1]refused to show the histogram on our system, as opposed to this first install cycle when this bug was  miraculously correct without our interference in the first initialization of the first download cycle - which gave us hope for an hour or so as we attempted to follow bruce williams tuts to understand the functionality of the new install: then all the bad behaviour and freeze up. 

we have uninstalled using the uninstall routine which comes with the program as well as using 'control panel' between downloads & reinstalls...by now we are afraid this whole exercise may have corrupted our drive. so far all other programs functions without errors. 

similar past experience with other programs required us to reformat and reinstall everything\all software as a consequence of a similar experience which ended up corrupting our drive.  
we will not continue this exercise if we are in any danger of repeating that experience as it was very time consuming and costly.

we have many working programs, more than 2 dozen, so the risk is greater than the reward presently appears.  we await your suggested solutions. 
 
--
peter fischer
petercfischer@gmail.com

**Comment by MStraeten** [comment]
please give some indications how the behavior can be reproduced, otherwise no one will be able to help ...
BTW: this template is helpful https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by phrrk** [comment]
I would suggest that you start off by clearing out all info from previous installs.  To do this go into the folder

`C:\Users\[your username]\AppData\local\darktable`

and rename the files `data.db library.db` and `darktablerc`.  Now start darktable and import a few images as a test. These should be images that do not have a corresponding .xmp file  in the same folder.  Now test.  If things are ok you could now try importing some previously imported images which do have .xmp files in the same folder and test again.

**Comment by AxelG-DE** [comment]
@petercfischer 
instead of opening a new issue with not much more info, please rephrase your issue here, merely utilizing the template you find in a fresh issue.

Goint thru that way rather than ranting typically gives help in quite short time

**Comment by TurboGit** [comment]
There is zero information to help you there. BTW, who is"we" or "us" that you are referring to? What platform?  OpenCL ? Intel? Anti virus?

And note that you may be frustrated but darktable works for many of us.

**Comment by kofa73** [comment]
You never have to reformat and reinstall everything to clean up a darktable installation. If you want to get rid of it, or start with a clean slate, you can delete the configuration and database, and remove the application.
To get back to 3.2.1: you're always advised to make a backup of the darktable databases and configuration before upgrading. Thankfully, darktable creates a backup before upgrading the database files.
Look for library.db-pre-3.4.0 and data.db-pre-3.4.0; they should be in the same directory where the (now upgraded) database files are (I think on Windows that would be C:\Users\[username]\AppData\Local\darktable).

**Comment by johnny-bit** [comment]
We've received some actionable reports of windows-exclusive problems that are being worked on now. I assume that your troubles might be related to one of those, so it might be closed as a duplicate. Please look for release 3.4.1 which should address problems found with release 3.4.

As for future issue reports - please provide minimum data required to analyze your issue following [bug report template](https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=) including all the info mentioned by template.
