### ISSUE TITLE
3.4.0: Masking tool turns a few degrees counter clockwise when the mouse button is released

### ISSUE THREAD

**Issue by gscholz** [darktable-org/darktable#7494]
**Describe the bug**

The gradient handle in the masking tool turns a few degrees counter clockwise when the mouse button is released. So it is not possible to turn the handle precisely to its final position.

**To Reproduce**

1. Go to the exposure tool (for example, other modules work as well).
2. Select "drawn mask" button
3. Press "add gradient" button
4. Place gradient somewhere on your image
5. Select handle/dot at the end of the arrow to turn the orientation of the gradient.
6. Turn gradient and release mouse button.
7. Turn handle does not stay at the selected position but moves some degrees counter clock wise.

**Expected behavior**

The handle should not turn automatically some degrees to displace the gradient orientation

**Screenshots**

See attachment:
![darktable-3 4 0-bug](https://user-images.githubusercontent.com/288568/103171099-b61b7f80-4849-11eb-9baf-22585f7fd7a4.png)

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 
Darktable Version: 3.4.0
Os: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Open CL: No

**Additional context**

This error was not present in 3.2.1 and other older versions

**Comment by elstoc** [comment]
I fixed a similar issue to this quite a while ago (https://github.com/darktable-org/darktable/pull/4598) but it seems that fix has been gradually reverted by subsequent fixes for other issues.

**Comment by AxelG-DE** [comment]
A quick-hack is to switch off the lens correction (or liquify) if used and re-set to on afterwards.

**Comment by gscholz** [comment]
Thanks for this hint. Yes I can confirm the error disappears when lens correction is disabled. So this is an issue regarding coordinate translation if the image is distorted.

**Comment by elstoc** [comment]
Still an issue in current master.
