### ISSUE TITLE
Artifacts in retouch for line in brush mode 

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#7496]
commit https://github.com/darktable-org/darktable/commit/208f62c8b1aeb75e98ce9aeba8d8f064150a98e7
introduced changes that results in artifacts in module retouch for cloned brush (with&without opencl enabled)

![artifacts_retouch](https://user-images.githubusercontent.com/39386816/103171310-92f1cf80-484b-11eb-8b38-7416e9eb4f08.jpg)

[mire1.cr2.xmp.txt](https://github.com/darktable-org/darktable/files/5744572/mire1.cr2.xmp.txt)

even weird in a bigger history stack:
![retouch](https://user-images.githubusercontent.com/39386816/103171607-e533f000-484d-11eb-8d29-5c62187c19b5.jpg)

**To Reproduce**
1. clone an area via brush
2. zoom in/out 

**Platform (please complete the following information):**
 - Darktable Version: current master (`git checkout 208f62c8b1aeb75e98ce9aeba8d8f064150a98e7`)
 - OS: OSX

@johnny-bit: i wasnt able to reproduce this with a win10 build, so maybe another candidate for your "what the hell Apple???" medal ;)

**Comment by johnny-bit** [comment]
Well... Tried on linux on `this is darktable 3.5.0+209~g1a86bd451` and... no error.

There's literally nothing in that commit that (i think) could've had caused an issue. in retouch all i did was change `dt_alloc_align(64, sizeof(float)...)` to `dt_alloc_align_float(...)` and all `dt_alloc_aling_float` does is call `dt_alloc_align(64, pixels * sizeof(float))` so I doubt it can have any signifficance. (well it also returns with assumption that floats are aligned, which they should well be...)

I'll give this "what the hell Apple???" badge and ask @ralfbrown to comment ;)

**Comment by ralfbrown** [comment]
The visual glitch was obviously due to a missing zeroing of the stamp that gets built for the cloned data.  Looking at src/develop/brush.c, I see that the dt_alloc_align_float is followed by a memset -- which fails to multiply the number of pixels by sizeof(float)....

**Comment by johnny-bit** [comment]
Thx... PR incoming...

**Comment by johnny-bit** [comment]
PR Done. Plz check #7499 :)

**Comment by MStraeten** [comment]
fixed, thanks
