### ISSUE TITLE
Collect Images via date-taken/date-time-taken crashes darktable

### ISSUE THREAD

**Issue by dsisco2** [darktable-org/darktable#7502]
In collect images I can choose any selection method (e. g. tag, film roll, camera) except date taken and date-time taken.  Those two give me a quick flash of years and then shut down darktable.  The error log (dmesg) reports:

[85368.824011] darktable[22464]: segfault at 0 ip 0000000000000000 sp 00007ffd2df38628 error 14 in nvidiactl[200000000+100000]
[85368.824021] Code: Bad RIP value.

Running darktable 3.4.0 installed via software installer (same thing happened on 3.2.1)
Ubuntu Studio 20.04.1 LTS focal on a homebuilt system with an ASRock B450 Pro4 MB and a AMD Ryzen 5 2600 CPU and a GeForce GTX 650 GPU
NVIDIA drivers: Using NVIDIA driver metapackage from nvidia-driver-440 (open source)

I have run fsck with no errors.

Darktable -d opencl results in:
#40 0x00007f6bcc872c41 in dt_gui_gtk_run (gui=<optimized out>) at ./src/gui/gtk.c:1549
        widget = <optimized out>
        allocation = {x = 0, y = 0, width = 568, height = 468}
#41 0x000055d8d3ded0d6 in main (argc=<optimized out>, argv=<optimized out>) at ./src/main.c:93
[Inferior 1 (process 23549) detached]
backtrace written to /tmp/darktable_bt_TYTIW0.txt
Segmentation fault (core dumped)

/tmp/darktable_bt_TYTIW0.txt  should be enclosed (if I did it right).

I suspect some configuration is faulty, but I'm not sufficiently experienced in darktable to determine what is wrong.

[darktable_bt_TYTIW0.txt](https://github.com/darktable-org/darktable/files/5745103/darktable_bt_TYTIW0.txt)

**Comment by TurboGit** [comment]
Cannot reproduce.

**Comment by wpferguson** [comment]
Is it possible that you have images in the database that don't have date time information?

**Comment by phweyland** [comment]
> Is it possible that you have images in the database that don't have date time information?

I would vote :+1: as at least one returned date is NULL (backtrace).

**Comment by phweyland** [comment]
I confirm. Nullifying the date field, give me the same crash. I'll issue a fix.
