### ISSUE TITLE
Import from camera does not appear in wndows 10

### ISSUE THREAD

**Issue by salkalero** [darktable-org/darktable#7507]
**Describe the bug**
In windows 10 the option to "import from camera" does not appear when I connect the camera

**To Reproduce**
Connect the camera.
Active Darktable.
In the import module, the option to import from camera does not appear
-->

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: windows 10
 - 
 - 

**Additional context**

**Comment by MStraeten** [comment]
did it work with 3.2.1? if not, have look at https://www.darktable.org/about/faq/#faq-tethering

**Comment by salkalero** [comment]
It happens to me since version 3.2.
I thought that the update would solve it, but it is not.
Thanks, I'll look at it

**Comment by salkalero** [comment]
Hello, I have tried to change the driver, even to try with all the drivers that this program had available, but I am still in the same situation.

**Comment by vrnhgd** [comment]
@salkalero what make/model camera are you using?

If Nikon, there are some gaps in coverage which should be addressed by #7083.

If not Nikon, you should be able to run DT with debug logging enabled for tethering... maybe this will help people help you.

**Comment by salkalero** [comment]
Hi.
I have a pentax, but another colleague has tried it with an Olympus and the same thing happens.
I'll try what you tell me thank you.

**Comment by difrkaguilar** [comment]
The same issue happen to me.
I'm using darktable 3.4.0 with Open CL enabled
And my camera is a FUJIFILM X-H1

**Comment by jenshannoschwalm** [comment]
I guess this is the issue mentioned in dt mailing list. In short: **only** devices correctly detected by libgphoto2 appear with a button. That can be cameras or sd cards.  

Not appearing devices could be related to twese propblems:

1. Not all cameras are supported by libgphoto2 so it might be a problem there.
2. The automatic camera detection relies on libgphoto2, if the device is already in use somehow, libgphoto2 would not be able to handle this. I remember issues with windows usb drivers servind any sd-card connectors.

I don't know about the libgphoto2 support on windows in general and i confess i never use windows so can't really be of immediate help here.

**Comment by johnny-bit** [comment]
Another thing to note is: if camera is "taken" by anything else and not "freed" before darktable process can detect and claim camera for darktable, the button won't appear too.

**Comment by jenshannoschwalm** [comment]
You can start dt via a command line using the camcontrol debug option

**Comment by salkalero** [comment]
> I guess this is the issue mentioned in dt mailing list. In short: **only** devices correctly detected by libgphoto2 appear with a button. That can be cameras or sd cards.
> 
> Not appearing devices could be related to twese propblems:
> 
>     1. Not all cameras are supported by libgphoto2 so it might be a problem there.
> 
>     2. The automatic camera detection relies on libgphoto2, if the device is already in use somehow, libgphoto2 would not be able to handle this. I remember issues with windows usb drivers servind any sd-card connectors.
> 
> 
> I don't know about the libgphoto2 support on windows in general and i confess i never use windows so can't really be of immediate help here.

I think the thing has to go that way. I tried to install the drivers with zading, but I had no positive response, I even tried with every driver that zading offered me, but nothing at all.
Unfortunately I chose to completely disassemble windows, so I can no longer do tests on the console, but I know that the same thing happened to other colleagues, if any of them decide to check what happens in the console, I will share that information.
Thank you

**Comment by salkalero** [comment]
> Another thing to note is: if camera is "taken" by anything else and not "freed" before darktable process can detect and claim camera for darktable, the button won't appear too.

I do not know very well how to solve that, I have tried opening DT and then connecting the SD and vice versa as well, I can do little more since I decided to use windows, since I barely used it, only for games, but now with steam already I do not need it. But I emphasize that it is a problem that happens to other colleagues.
thanks

**Comment by jenshannoschwalm** [comment]
> Another thing to note is: if camera is "taken" by anything else and not "freed" before darktable process can detect and claim camera for darktable, the button won't appear too.

That's exactly what is happening (so gphoto2 can't use that device) but it completely out of darktable's control.

>  But I emphasize that it is a problem that happens to other colleagues

I am well aware of this, it seems to depend on the driver you use - at least i remember such reports. I am not sure whether the real problem is gphoto2 or the win device driver though. Unfortunately there are only very few people developing on windows around here, most of us avoid it :-)

If there is someone interested in working on this i would help along as i have been working on the dt/gphoto2 side for some issues....

**Comment by johnny-bit** [comment]
I wonder if popping something like "camera detected, but in use by other app, plz unmount if you want darktable to use it" in import module would be good to differentiate between "darktable can't detect camera" and "camera is detected but not available"

**Comment by jenshannoschwalm** [comment]
You have suggested something like that before when i did the pr for automatic camera detection. The code for checking is already in there, so far it's just seen on the console.

And i don't know whether this really works a) on windows and b) on a camera supporting tethering.

Using linux and just sd-cards doesn't help as there is no "taking over" and i don't have access to any camera that can tether.

If i remember correctly you have a tethering camera and could check that code section...

**Comment by Nilvus** [comment]
As import module had been completely rewritten for darktable 3.6, this issue is no longer relevant. The new import dialog window should fix that. Just wait a week to see darktable 3.6 out and see the great new way to import images.
