### ISSUE TITLE
White balance presets for Olympus E-M10 Mark IV

### ISSUE THREAD

**Issue by wombalton** [darktable-org/darktable#7516]
I did the fine tuned white balance preset as instructed in the wiki for the Olympus OM-D E-M10 Mark IV
[darktable-whitebalance-20201228.tar.gz](https://github.com/darktable-org/darktable/files/5748152/darktable-whitebalance-20201228.tar.gz)

**Comment by johnny-bit** [comment]
Thanks! Presets look fine :) added in PR#7584 :)
