### ISSUE TITLE
[Liquify/mask edit] control points get activated from quite large distance to mouse pointer

### ISSUE THREAD

**Issue by thugcee** [darktable-org/darktable#7519]
**Describe the bug**

The bug causes that I can't edit liquify deformation matrix with control points closer to themselves than about 140 pixels.

If I remember correctly I have this problem since some commit where performance fixes for HiDPI screens have been introduced. As I googled for it many times, it looked that nobody else have it. I hoped that it will be accidentally fixed in v3.4 but it's still there (for me at least).

**To Reproduce**
Open an image, activate Liquify IOP, add any small shape, then try to refine it (move control points).

It's not easy to describe it precisely in one sentence :):
- it looks like there is some minimum distance when a control point (`center` - a dot, `direction` - a triangle, `radius` - a dot) gets focus and is available for dragging by mouse;
- this distance is measured in image pixels, not screen, and in my case it is about 140! <- I have no idea where it came from;
- when a `direction` control point is more than 140 px from `center` and `radius` it behaves normally - gets focus when mouse is  close to it (still it looks like the threshold is in image pixels, so on large zoom the control gets activated from a significant distance)
- when a `direction` CP is less than 140px from one of `center` or `radius` dots, then it gets activated from 140px distance.
- `center` and `radius` CP always get activated from 140px (or less).

**Expected behavior**

Control points are activated when mouse pointer is over them (over the shape of a control point).

**Platform (please complete the following information):**
 - Darktable Version: 3.4 compiled from source code
 - OS: Ubuntu 20.04
 - OpenCL activated
 - NVIDIA 450

**Additional context**
Starting DT with deleted `~/.config/darktable/darktablerc` doesn't solve the problem.

**Comment by johnny-bit** [comment]
There were quite some changes to masks (and therefore to liquify too) handling code. Currently I cannot replicate the issue on `3.5.0+2526`. Can you check current master compiled from source? I hope that your issue is fixed :)

**Comment by TurboGit** [comment]
I suppose so yes, I have reviewed all masks and fixed a number of issue detecting which control gets activated. Closing.
