### ISSUE TITLE
Panasonic DC-S1R

### ISSUE THREAD

**Issue by NFecDe** [darktable-org/darktable#7522]
For noise profiles, please also attach the entire archive with `.pdf` plots.
[darktable-noiseprofile-20201228.tar.gz](https://github.com/darktable-org/darktable/files/5748585/darktable-noiseprofile-20201228.tar.gz)

Would be great if you can add the noise profile I created for the Panasonic Lumix S1R. Thanks!

**Comment by rawfiner** [comment]
Thanks!
