### ISSUE TITLE
Remove the need for ctrl click to create an area using the color picker....

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#7525]
Just a comment and I am not sure that others will agree or feel it is worth the effort. I suspect it was an attempt to simplify the color picker by removing the second selection picker and forcing the user to use ctrl to create an area however I just find this a more clumsy way to select that option. I have to look away and find the ctrl key and then look back and click the small picker icon. 

Would it be hard to a) insert a preference setting that would allow area as the default and not point. Essentially if you don't draw anything after you click you would have a point anyway. or b) recode so that after selecting the picker within the color picker module that you would single click on the image to leave a point or click hold and begin to draw to create an area selection??  Either of these methods would be easier IMO than having to introduce a ctrl click to create an area. Even using the old way you didn't have to slow down just select which picker mode from the small picker icon and go....its a small thing but I think it gets used a lot certainly I do and so using it in one of the two ways above that I suggested would seem more fluid to me....again its coming from my viewpoint and others may disagree.......

**Comment by Nilvus** [comment]
@todd-prior: I don't use shortcuts for that but if you could test actual master, probably new shortcut manager from @dterrahe should help doing what you want (see #8078 PR). This had been merged, so I suggest you to test. Please think about considering closing this issue if this new feature fix it or amend it to adapt to this new way to create/manage shortcut (maybe better close this one and create a new as the way shortcuts are managed is a lot different and more powerful).

**Comment by todd-prior** [comment]
Seems crazy complicated but I will take a look. It still looks like it involves working with enhancing and multiplying what you can do with keys and my FR was to bring back the second pipette icon for the color checker so if you wanted a point you selected the first one or if you wanted an area you selected that one . You could do it all with a single mouse gesture and not take your eyes off the display to locate the ctrl key and then relocate the pipette while holding the ctrl key to then click the icon for a color picker…..I think the old way was better but it’s a small thing and I am not likely to get this sort of change introduced I am sure. UI’s are personal but for me the two pipettes are smoother than the current setup…

**Comment by dterrahe** [comment]
Would right-click for area work for you?

**Comment by todd-prior** [comment]
Any mouse action would be great but I can get by so don’t worry unless that would be easy. Basically I think with the pipette activated a single click and release should define a spot and if you click hold and draw then you have a region. I am not sure if this would be any less difficult to implement but to me this just seems to be the natural way that you would use a tool like that and then no extra functions needed….

**Comment by dterrahe** [comment]
The thing is, at the moment if you use the "spot" color picker, you can drag it around and the reading continuously updates, without having to click everywhere. With your suggestion that would stop working. There will be _somebody_ who uses it that way and they will be disappointed by such a change...

Also, it would require more fundamental changes to the code whereas right-click is very trivial.

**Comment by todd-prior** [comment]
Thanks for the explanation. Never occurred to me as I target spots…that’s good to know….the mouse action would be nice so a right click would be smoother….I thought the old two pipettes was fine too…clear choice of selection..

Thanks

**Comment by todd-prior** [comment]
Just had a second thought could it not still work that way if people just held the mouse key down but did not release it..then free to move around the image??

In any case I am good as is …better with a mouse action added including right click but happy to work as is if need be as well.. Thanks for your feedback…

Todd
