### ISSUE TITLE
Darkroom Filmstrip - elegant-dark theme: yellow color labels are invisible on the currently selected photo

### ISSUE THREAD

**Issue by arigit** [darktable-org/darktable#7529]
**Description & how to reproduce**

Using the latest DT3.4, theme: darktable-elegant-dark. 

Open any photo in the darkroom and set it with a Yellow color label (press F2). The Yellow color label (small yellow circle) is added to the photo however it's invisible in the GUI. Moving forward in the filmstrip to the next photo will allow you to see that the yellow label was added.

The same problem happens also in the Lighttable, but in this case it happens only when hovering with the mouse on any picture that has a yellow label - the background color to show the "hovering selection" is such that the yellow color can't be seen.

Here is a graphical expample of the problem as seen in the Darkroom Filmstrip:

![image](https://user-images.githubusercontent.com/652673/103249650-41763d00-493e-11eb-9d68-de6dee89175b.png)

All three photos in the snippet have a Yellow label, but this can't be seen in the currently selected photo.

To prevent or mitigate this problem, I suggest using a darker grey background just behind the Overlay line in the filmstrip even for the currently selected photo. This background could perhaps be a little lighter than the grey color used for non-selected photos in the filmstrip.
This same concept could apply to the Lighttable "mouse hovering selection" that suffers from the same problem.

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Ubuntu 20.04
 - OpenCL: active
 - Which graphics card and driver version: nvidia, GTX1650; X11; 450.80.02

**Comment by MStraeten** [comment]
You may change this for your installation via css in preferences dialog

**Comment by Nilvus** [comment]
> All three photos in the snippet have a Yellow label, but this can't be seen in the currently selected photo.

I see it in your screenshot, so can't be seen is not true. But you're right, it's not good as it is. Anyway, it will probably be hard to find a good compromise. I have changed selected color due to some users complained that selected thumbnail was not visible (it was but for some users, they consider that was hard to see). So finding a good compromise between yellow color and having a visible thumbnail is not easy. And that's a really minor UI issue.

**Comment by parafin** [comment]
Maybe change yellow color? To be more orangy/darker.

**Comment by Nilvus** [comment]
> Maybe change yellow color? To be more orangy/darker.

I have thought about that. I will try, but users are used to actual color, so I will try something near actual one or maybe a mix of that. Thanks for your idea!

**Comment by arigit** [comment]
@Nilvus & all, thanks for barging in. My screen is calibrated (color munki) and my eyes may be getting older :), not sure if that can explain it but I can tell I am unable to see whether the yellow label is there in the middle thumbnail in the snippet above. I know it should be there :)

@MStraeten great idea, I wouldn't mind making the label a little orangy. I need a little help with what property needs changing though, any pointer on this would be great!

Perhaps making the labels a little more prominent and giving them a darker border or outline could help as well.

**Comment by johnny-bit** [comment]
That would require color label colors to be set via css ;) currently it's (i think) hardcoded.

**Comment by TurboGit** [comment]
Yes I think so too. Let's move all color label colors into CSS first then. @johnny-bit : Do you want to look at this ?

**Comment by johnny-bit** [comment]
> Do you want to look at this ?

Nope :P Too complex for me ;) dtorop did colors for histogram in css tho...

**Comment by TurboGit** [comment]
Ok, I'll have a look then.

**Comment by TurboGit** [comment]
Done, all color labels are set in CSS now. @Nilvus : You can now work on the final part. TIA.

**Comment by Nilvus** [comment]
Ok, thanks. Will see that tonight.

**Comment by Nilvus** [comment]
@arigit. Is this rendering better for you?

![image](https://user-images.githubusercontent.com/45535283/103317115-d6566480-4a2a-11eb-9d74-be8f4f8574c0.png)

Just remember that it's hard to find a good compromise between all themes and all states (hover, selected, not selected...).

**Comment by Nilvus** [comment]
For those of you with last master, that could be test with that CSS code:

@define-color colorlabel_yellow rgb(240,190,0);

We are nearest orange than yellow.

**Comment by arigit** [comment]
Thanks for the fast response! 
@Nilvus the change does fix the Hover state (which is really important because it's used in the Darkroom for for the currently-edited image) - thanks! 

I have to say though that it also makes it somewhat hard to see the Selected state (in my calibrated setup at least) 

Arguably visibility of the color label is most important for "non-selected" AND for "hover" states, because,
  * non-selected is most important when in the lighttable
  * "hover" is most important in the darkroom (the currently edited picture thumbnail is shown in "hover" state) and when I am editing, For those using labels it's common to set/change labels while editing so it's important to be able to see those labels

So this change to "yellow-orange" is definitely an improvement, since the "Selected" state visibility is not as important.

For a bullet-proof solution that works in all modes with all themes, perhaps it would be ideal to add a "circle outline" around each color label using the same color (for the circle outline) as used for the outline of the "stars" and the "X" overlays. That color is guaranteed to have good visibility otherwise becuase all visibility of all other components of the overlay depend on it.

Or alternatively, allowing themes to define the color of the labels for each of the three states so theme developers can do some adjustments as needed. A third approach could be to have uniform (the same) background behind the overlays regardless of state. Just random thoughts - I can see this probably requires heavy lifting.

The new color setting definitely helps!

**Comment by Nilvus** [comment]
> I have to say though that it also makes it somewhat hard to see the Selected state (in my calibrated setup at least)

I'm quite surprised and maybe it's just the screenshot. It's perfectly visible on my computer (calibrated too) and not less visible than yellow. The color is between red one and yellow one.
 
> So this change to "yellow-orange" is definitely an improvement, since the "Selected" state visibility is not as important.

Good to read that.

> For a bullet-proof solution that works in all modes with all themes, perhaps it would be ideal to add a "circle outline" around each color label using the same color (for the circle outline) as used for the outline of the "stars" and the "X" overlays. That color is guaranteed to have good visibility otherwise becuase all visibility of all other components of the overlay depend on it.

Just no way for that. I had thought about that, but that would make the UI awful (it's not the same for colorlabels the way they are than X and stars) on that part. And is it necessary to add distracting things for just one color in one state?

> Or alternatively, allowing themes to define the color of the labels for each of the three states so theme developers can do some adjustments as needed. A third approach could be to have uniform (the same) background behind the overlays regardless of state. Just random thoughts - I can see this probably requires heavy lifting.

That was my first idea and I heavily test it yesterday, by setting different backgrounds and even different ones regarding of each state. And that's just break the UI consistency and become bad design. The idea seems good but when doing it...

Anyway, I didn't try to adjust a little the color depending on state. Will test that but not sure it will be good. Having a colorlabel changing its color could be worse for a lot of users.

**Comment by arigit** [comment]
> I'm quite surprised and maybe it's just the screenshot. It's perfectly visible on my computer (calibrated too) and not less visible than yellow. The color is between red one and yellow one.

It's quite possible, I did notice that taking screen snippets and pasting them on emails seems to break color management (the pasted image does not look the same it was on the desktop). I will reconfirm this once the merge gets into a nightly release in OBS or flatpak

> Anyway, I didn't try to adjust a little the color depending on state. Will test that but not sure it will be good. Having a colorlabel changing its color could be worse for a lot of users.

Totally understood. A middle ground: perphaps just just making the color for each state themable via CSS, and defaulting to the same orangy color in all states (for elegant-dark)? that way people that don't make heavy use of color labels won't notice at all, and people affected can add a one-liner in the CSS tweaking panel in the configuration?

**Comment by arigit** [comment]
> I'm quite surprised and maybe it's just the screenshot. It's perfectly visible on my computer (calibrated too) and not less visible than yellow. The color is between red one and yellow one.

It is quite possible, I did notice that pasting screen snippets on emails seems to break color management (the pasted image does not look the same it was on the desktop). I will reconfirm this once the merge gets into a nightly release in OBS or flatpak

> Anyway, I didn't try to adjust a little the color depending on state. Will test that but not sure it will be good. Having a colorlabel changing its color could be worse for a lot of users.

Totally understood. A potential middle ground: what about just making the color for each state themable via CSS, and defaulting to the same new orangy color in all states (for elegant-dark)? that way people that don't make heavy use of color labels won't notice at all, and people affected can add a one-liner in the CSS tweaking panel in the configuration?

**Comment by Nilvus** [comment]
I have improved the contrast in selected state with a more orange color. Should be good now and will be for 3.4.1.
