### ISSUE TITLE
NEF files from Nikon CoolscanV  scanner not readable

### ISSUE THREAD

**Issue by cdalphin** [darktable-org/darktable#7533]
Hi.
Darktable is not able to read .NEF files created by my scanner NiKON CoolScan V.
These files are not corrupted. They are readable by Adobe DNG converter and Camera Raw
See screenshots attached
![screenshot-01](https://user-images.githubusercontent.com/36600213/103274062-02d59680-49c1-11eb-920a-3fbfebabe66e.jpg)
![screenshot-02](https://user-images.githubusercontent.com/36600213/103274064-036e2d00-49c1-11eb-8b03-bc1ad1c3baf8.jpg)

Regards
Claude

**Comment by MStraeten** [comment]
See: https://github.com/darktable-org/darktable/wiki/Camera-support

**Comment by phrrk** [comment]
This is being worked on.  See #7129

**Comment by johnny-bit** [comment]
@cdalphin - Please follow https://github.com/darktable-org/darktable/wiki/Camera-support especially make sure you've sent a sample file to raw.pixls.us and please open a new issue using [new camera support issue](https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E)

Thanks!

**Comment by johnny-bit** [comment]
Closing in favour of https://github.com/darktable-org/darktable/issues/7649 :) Thanks for creating new issue!
