### ISSUE TITLE
History problem detected

### ISSUE THREAD

**Issue by A-Herold** [darktable-org/darktable#7534]
[2002_002_23.original.tif.xmp.gz](https://github.com/darktable-org/darktable/files/5751958/2002_002_23.original.tif.xmp.gz)
[2002_004_10.original.tif.xmp.gz](https://github.com/darktable-org/darktable/files/5750490/2002_004_10.original.tif.xmp.gz)

**Bug description**
While opening a file in darktable, the following message was displayed: "history problem detected, please report via the issue tracker including the xmp file". 

[Link to Image 2002_004_10](https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=2002_004_10.original.tif)
[Link to Image 2002_002_23](https://www.dropbox.com/sh/orbifgwd23sgzw8/AAC3SjlwjRe-LvLhX7U5UZBaa?dl=0&preview=2002_002_23.original.tif)

Added a second example. It seems, that all images, that I had imported around the same time, are having history problems.

Some new information appeared, while generating the cache manually. The image was edited in darktable 3.2.1, it was not touched in darktable 3.4.0. In 3.2.1 there were no messages, when generating the cache.
`image 10068/31392 (32.07%) (id:36605)
[dt_ioppr_set_pipe_input_profile_info] unsupported input profile 9 , it will be replaced with linear rec2020
[dt_ioppr_set_pipe_input_profile_info] unsupported input profile 12 , it will be replaced with linear rec2020
[dt_dev_pixelpipe_synch] found enabled demosaic in history for non-raw `2002_004_10.original.tif`, id: 36605
[dt_ioppr_set_pipe_input_profile_info] unsupported input profile 12 , it will be replaced with linear rec2020
[dt_ioppr_transform_image_colorspace_cl] invalid conversion from 2 to 0
[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
`

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0 (from offical DMG image)
 - OS: MacOS 11.1
 - OpenCL activated
 - Intel(R) Iris(TM) Graphics 6100

**Comment by johnny-bit** [comment]
Please zip up both those files and attach the archive directly in github to issue. dropbox might not be best hosting if issue takes time to investigate ;)

**Comment by A-Herold** [comment]
The upload limit is at 10MB, but my TIF file has a size of about 140MB. Even compression does not help much.

**Comment by A-Herold** [comment]
found enabled demosaic in history for non-raw 2002_004_10.original.tif
This message helped me to isolate the problem. At the moment, I don't have any idea how demosaic became part of the pipeline. But I found a way to get rid of it: I copied the history without demosaic to a new copy of the image. This solved the "history problem detected" message. But there is still one problem remaining:
id: 36605 [dt_ioppr_set_pipe_input_profile_info] unsupported input profile 12 , it will be replaced with linear rec2020
This message will not disappear, even if the history was discarded and the image was imported with a new name.
My TIF-images have embedded custom scanner profiles and I need them to work properly. Until now I had no problems with them.

**Comment by TurboGit** [comment]
> I don't have any idea how demosaic became part of the pipeline. 

copy/paste of history from another image ?

**Comment by A-Herold** [comment]
> copy/paste of history from another image ?

Sorry for the unclear wording. Exactly it did the following:
* selected image -> duplicate
* defect image: history stack -> copy parts ... -> disable demosaic -> Ok
* duplicated defect image: history stack -> paste parts ... -> Ok

**Comment by komodo666** [comment]
I have the same problem.

At first I thought that the problem is on images that was previously edited, but as I can see it appears at least for me, randomly.

Some images are ok and some not.
