### ISSUE TITLE
Dutch translation darktable 3.4 - attachment with missing translations

### ISSUE THREAD

**Issue by kevinvermassen** [darktable-org/darktable#7537]
In darktable 3.4 the Dutch translation is missing. I downloaded the git and edited the nl.po file, added the missing translations and corrected most errors. The 2 remaining errors aren't really an error because of the Dutch grammar.

The nl.po and nl.mo files are attached to this message in a zip.
[dutch translation.tar.gz](https://github.com/darktable-org/darktable/files/5750588/dutch.translation.tar.gz)

**Comment by MRIG** [comment]
Kevin, I'm very glad to see you translating the missing strings. I haven't been able to keep up translating. Nine years of translating. See someone to take it over, makes me happy!!!Good Luck. Ik ben je dankbaar en wens je veel wijsheid en plezier met het vertalen. Groeten Ger Siemerink.
