### ISSUE TITLE
The histogram profile is not working properly in 3.4.0

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#7542]
**Describe the bug**
I set all screen profiles in Darktable to "sRGB (web-save)".
With version 3.4.0 I noticed that the histograms no longer fit.
When I move darktable window to another screen, the histogram changes. That shouldn't be because the same color space is used everywhere.

**To Reproduce**
Set all Profiles to sRGB.
Move the darktable-window to another screen.

**Expected behavior**
The histogram does not change because there is no need to calculate from sRGB to sRGB.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Ubuntu 18.04
 - OpenCL activated

**Additional context**
I think the problem is here:
pixelpipe_hb.c line 2173
```
        darktable.lib->proxy.histogram.process(darktable.lib->proxy.histogram.module, buf,
                                                 roi_out->width, roi_out->height,
                                                 DT_COLORSPACE_DISPLAY, "");
```
pixelpipe_hb.c lines 2181
   ```
     darktable.lib->proxy.histogram.process(darktable.lib->proxy.histogram.module, input,
                                               roi_in.width, roi_in.height,
                                               DT_COLORSPACE_DISPLAY, "");
```

darktable.lib->proxy.histogram.process calls dt_lib_histogram_process in libs/histogram.c.
In this function, the conversion takes place if the display profile differs from the histogram profile. That's right, but the DT_COLORSPACE_DISPLAY value is not the display profile. Here the correct profile should be read from the settings.

**Comment by flannelhead** [comment]
Here's already a PR that should fix this:
https://github.com/darktable-org/darktable/pull/7531

**Comment by johnny-bit** [comment]
The PR is merged so (hopefully) closing.
