### ISSUE TITLE
[defringe] (200% zoom), reduce edge detection --> dt crash

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7553]
**Describe the bug**

In current master, changing Edge detection in defringe module make dt crash. No coredump :-(
[EDIT1] Good news: dt 2.4.0 does not crash

On terminal I see: ("Abgebrochen" means aborted)

```
$ darktable
malloc(): unaligned tcache chunk detectedmalloc(): unaligned tcache chunk detected

Abgebrochen
```
In a second try I just got a Segfault
```
$ darktable --configdir /tmp/2
Speicherzugriffsfehler
```
[EDIT2] during bisecting I got now for the first time another console message:
```
$ darktable

(darktable:12613): Gtk-WARNING **: 03:59:17.011: Failed to set text '\xc3\xfe\u0014' from markup due to error parsing markup: Error on line 1 char 26: Document ended unexpectedly with elements still open ? ?markup? was the last element opened

(darktable:12613): Pango-CRITICAL **: 03:59:22.538: pango_attr_list_unref: assertion 'list->ref_count > 0' failed
malloc(): unaligned tcache chunk detected
Abgebrochen
```

**To Reproduce**
1. Go to Darkroom (it crashes faster when zoomed in)
2. activate defringe module
3. Reduce edgedetection down to 0.5 and go back up

**Expected behavior**

no crash

**bisect**

I will try to bisect and ammend the issue here
[EDIT3] bisect gave me:

```
3c27a9457b08c30eb6baf40bc86c0d3afc968dc2 is the first bad commit
commit 3c27a9457b08c30eb6baf40bc86c0d3afc968dc2
Author: Ralf Brown <ralfbrown@users.noreply.github.com>
Date:   Mon Dec 28 11:21:01 2020 -0500

    add function to verify piece->colors and set module's trouble flag if… (#7478)

 src/develop/imageop.c     | 30 ++++++++++++++++++++++++++++++
 src/develop/imageop.h     |  7 +++++++
 src/iop/bloom.c           |  4 +++-
 src/iop/channelmixerrgb.c |  5 +++++
 src/iop/colorcontrast.c   |  8 ++++++--
 src/iop/colorcorrection.c |  5 ++++-
 src/iop/colormapping.c    |  4 +++-
 src/iop/colorout.c        |  5 ++++-
 src/iop/defringe.c        |  5 +++--
 src/iop/denoiseprofile.c  |  4 +++-
 src/iop/nlmeans.c         |  4 +++-
 src/iop/rgbcurve.c        |  4 +++-
 src/iop/soften.c          |  8 ++++++--
 src/iop/splittoning.c     |  5 ++++-
 src/iop/tonecurve.c       |  5 ++++-
 src/iop/useless.c         | 17 +++++++++++++++++
 src/iop/vibrance.c        |  5 ++++-
 17 files changed, 109 insertions(+), 16 deletions(-)
```

@ralfbrown: I'd like to ping you on this one. :)

**Platform (please complete the following information):**

* darktable version : 3.5.0+244~g6b58bc079
* OS                : Linux - kernel 5.10.2-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-460.27.04
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelwithDebInfo"

**Additional context**

 - Are the steps above reproduce with a fresh edit (removing history)? **yes**
 - Is the issue still present using an empty/new config-dir **yes**

**Comment by ralfbrown** [comment]
The malloc error message is characteristic of a buffer overrun, or less commonly a race condition on free/alloc.  Since there was a related issue yesterday with a race condition in the new function added by that commit, does applying #7546 resolve the problem?

**Comment by AxelG-DE** [comment]
@ralfbrown I didn't know, you're familiar with German language :-) I will keep on filing German bug reports *kidding*

I confirm #7546 solves the defringe crashes (and I assume others, which I have had just before I figured, defringe is that obvious to crash)

**Comment by AxelG-DE** [comment]
I donno this side info is helpful: 
- just updated to 3.5.0-250-gee17c5dcc (so #7546 not yet in)
- crash comes way much later (before was almost immediately, now I really need to slide forth and back several times)
