### ISSUE TITLE
Core dump : munmap_chunk(): invalid pointer in second instance of Color Calibration

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7555]
WSL Ubuntu 20.04
Current master

Created a new instance of color calibration module (instance 1). Was playing around in the grey tab by varying the  RGB sliders. DT window disappeared.
Had the following in the shell that started DT.

(darktable:17378): Gtk-WARNING **: 12:28:11.777: Failed to set text '\xd0;\u0004\xbcK\u007f' from markup due to error parsing markup: Error on line 1 char 27: Invalid UTF-8 encoded text in name — not valid “\xd0;\u0004\xbcK\u007f”
Segmentation fault (core dumped)

Log file created but empty.

Ran dt again and did the same test again and was reproducible.

This time I got the following on the console.
```
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
This time no log file created, not even a file with the version in it.

**Comment by johnny-bit** [comment]
Most likely duplicate of #7528 

If so - please close this issue and continue in #7528

**Comment by chhil** [comment]
Closing duplicate

**Comment by chhil** [comment]
Current master don't have the issue anymore.
