### ISSUE TITLE
Color Calibration new instance will create one without bypass being set.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7556]
Current master.
WSL Ubuntu 20.04
This one is timing related and can't reproduce.

While a raw image is preparing to open in darkroom main view (image not visible yet nut modules are visible), if I create a new instance of color calibration it does not create one with bypass but seemed to duplicate the instance. 

If the image was already open and I try creating a new instance, it correctly creates the new one with bypass

**Comment by johnny-bit** [comment]
I'm not fast enough to reproduce on my system, even with CPU path. And i have CPU from 2011 :/

The ONLY thing i could think of in this situation is to disable inputs/actions till image is fully loaded but that might have unintended consequences

**Comment by johnny-bit** [comment]
Cannot reproduce at all. Please comment if you can reproduce. Perhaps it's some race issue but for that we'd need to investigate locking mechanisms...
