### ISSUE TITLE
RCD demosaicing has grid-like artifacts in preview

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#7558]
The RCD demosaicer introduces grid-like artifects on the display in the current `master` branch. To reproduce:
1. Load an image
2. Optionally reset the processing history to scene-referred defaults
3. Select RCD as demosaicing method
4. Zoom to 100% or more
5. Observe white grid, as below

![image](https://user-images.githubusercontent.com/6567747/103347095-44844100-4a96-11eb-96f2-e53d96f4cafa.png)

Darktable `master` branch (3.5.0+250~gee17c5dcc), self-compiled without errors in MSYS2 on Windows 10. OpenCL is active but disabling has no influence. Graphics card is GeForce RTX 2070 Super.

The grid artifacts are not present when exporting.

**Comment by AxelG-DE** [comment]
I am at 3.5.0-251-gce4fc2d20 and cannot reproduce
Can you please amend the additional infos you have deleted (see fresh template, the last two sections) TNX

**Comment by jenshannoschwalm** [comment]
Unfortunately i can't test on windows. What you observe are likely borders of the rcd tiling.
Questions:
1. Does the grid change / disappear if you change the darktable window size?
2. Is this with all images? I guess so ...
3. At the lower section of the screenshot the grid is not visible, is this consistent?

**Comment by Thanatomanic** [comment]
@AxelG-DE I believe there is no further information I can supply, not unless you have specific information you are interested in. There are very few commits since this feature was introduced yesterday in https://github.com/darktable-org/darktable/commit/fed21e2b67b2d7b19def692fc637c93b46a98feb.

@jenshannoschwalm 
1. The grid changes when resizing. Sometimes showing more, sometimes less.
2. Yes, I have tested this so far with ~5 various Bayered files of very different camera brands.
3. The lower part of the grid also shows as you can see below.

![image](https://user-images.githubusercontent.com/6567747/103358283-883a7300-4ab5-11eb-9459-a812796b943b.png)

**Comment by heckflosse** [comment]
@Thanatomanic Can you reproduce the issue when running dt on only one core?

**Comment by jenshannoschwalm** [comment]
One more check please: Is this also happening if you switch on smoothing?

**Comment by Thanatomanic** [comment]
@heckflosse I just compiled using USE_OPENMP=False set, effectively bypassing any form of multithreading. OpenCL is still disabled as well. I also set the 'number of background threads' in the settings to 1 (lowest value). The grid-like patterns remain visible in the preview.
@jenshannoschwalm Yes, it also happens when I turn on smoothing.

Is this behavior not reproducible on your side(s)?

**Comment by heckflosse** [comment]
@Thanatomanic 
> Is this behavior not reproducible on your side(s)?

Don't know, as I don't use darktable.

**Comment by jenshannoschwalm** [comment]
No it's not reproducible here. I will have to think on how to test...

**Comment by heckflosse** [comment]
@jenshannoschwalm As it only happens in preview, maybe try to resize the dt window to get a different size of the preview?

**Comment by jenshannoschwalm** [comment]
Here und on other Linux machines this is no issue whatever the image and window size is...

**Comment by johnny-bit** [comment]
Try as I might and I can't reproduce on linux with relwithdebinfo build on gcc9.3

11 questions to @Thanatomanic : 
1. What compiler (and version) do you use to compile?
2. what build type (release or relwithdebinfo)?
3. what ram config do you have (since it really looks like tilling artefacts)

the "windows" part is interesting too... if it's "windows-only" problem it'll be very weird

**Comment by Thanatomanic** [comment]
@johnny-bit 
I compile in an up-to-date MSYS2 environment with gcc, only release builds so far, but I'll create a relwithdebinfo build momentarily.

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev5, Built by MSYS2 project)
```

To compile single threaded I run this from a `build` directory:
```
$ cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./Release -DBINARY_PACKAGE_BUILD=ON -DUSE_OPENMP=False ../.
$ cmake --build . --target install -j7
```

The configuration shows no errors. Some potentially relevant versioning info: OpenMP 4.5, ZLIB 1.2.11, GTK 3.24.33, Glib 2.66.3.
I have 24 GB DDR3 RAM installed (3 strips of 8 GB PC3-10700 Corsair memory, two of which are in dual channel mode, and one in single channel).

For further information: removing my darktablerc configuration file does not help to remove the grid pattern. In other words: it's not a weird custom setting.

**Comment by Thanatomanic** [comment]
FWIW, there are a few tests that fail during configuration. Maybe they are of relevance, however, the rest of darktable or other software that I compile in similar ways show no problems:
```
-- Looking for execinfo.h
-- Looking for execinfo.h - not found
(...)
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_READERS - Failed
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS
-- Performing Test HAVE_THREAD_RWLOCK_ARCH_T_NR_READERS - Failed
(...)
-- Performing Test C_COMPILER_UNDERSTANDS_-Wthread-safety
-- Performing Test C_COMPILER_UNDERSTANDS_-Wthread-safety - Failed
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wthread-safety
-- Performing Test CXX_COMPILER_UNDERSTANDS_-Wthread-safety - Failed
```

Regarding the `-Wthread-safety` mentions, my compiler _does_ recognize `pthread.h` and the configuration script reports `Found Threads: TRUE`. I have not seen threading issues in other multi-threaded applications (such as RawTherapee).

**Comment by johnny-bit** [comment]
That makes me wonder... It shouldn't tile then with so much ram...

Another question: does RCD on RawTherapee exhibit same problems or not (RCD code and operations from RawTherapee and darktable should be very very very close)

**Comment by jenshannoschwalm** [comment]
Rt is perfectly stable for long. The tiling is rcd-internal for performance reasons. I will look into this.

**Comment by jenshannoschwalm** [comment]
I have never seen such an issue on Linux BTW.

**Comment by heckflosse** [comment]
@Thanatomanic Could you try with a RCD_TILESIZE of 214 (that's what RT uses)?

https://github.com/darktable-org/darktable/blob/master/src/iop/rcd_demosaic.c#L46

**Comment by Thanatomanic** [comment]
> Another question: does RCD on RawTherapee exhibit same problems or not (RCD code and operations from RawTherapee and darktable should be very very very close)

No, I do not see this behavior in RawTherapee.

I have now made a RelWithDebInfo build and still can make the grid artifacts appear. However, they seem to appear less often and more intermittent. I have made a quick screencast to show the effects: https://filebin.net/duvg1gvv1m0fva1t
When you do not move the image after switching demosaicer, the gridlines sometimes do not show up. After moving, pretty much always. During testing I also had a run where I could not reproduce when maximized, but the grid lines immediately appeared after switching to windowed mode... Very curious.

@heckflosse I will compile with the requested tilesize and report back.

**Comment by Thanatomanic** [comment]
@heckflosse Unfortunately, changing the tilesize only makes the grid pattern bigger

![image](https://user-images.githubusercontent.com/6567747/103455498-f8333e00-4ced-11eb-9348-496e8a2bfe36.png)

**Comment by heckflosse** [comment]
@Thanatomanic I just built darktable on my windows machine. Unfortunately I can not reproduce the issue :-(

**Comment by heckflosse** [comment]
I can reproduce the grid lines while panning
![grafik](https://user-images.githubusercontent.com/13733487/103460834-bfa95980-4d19-11eb-8151-799b33f2f90f.png)

**Comment by heckflosse** [comment]
And now also after panning...
![grafik](https://user-images.githubusercontent.com/13733487/103460968-0c416480-4d1b-11eb-89c4-093258744c69.png)

**Comment by heckflosse** [comment]
One difference between RT and dt implementation is, that RT callocs some tile buffers, while dt mallocs them...

**Comment by johnny-bit** [comment]
Hmmm... That MIGHT leave some garbage in buffers... callocing buffers would cover both: malloc + memset buffer to zero ;)

**Comment by heckflosse** [comment]
This fixes the issue in my windows build
```diff
diff --git a/src/iop/rcd_demosaic.c b/src/iop/rcd_demosaic.c
index 3419c6154..9ef04e8ab 100644
--- a/src/iop/rcd_demosaic.c
+++ b/src/iop/rcd_demosaic.c
@@ -315,8 +315,11 @@ static void rcd_demosaic(dt_dev_pixelpipe_iop_t *piece, float *const restrict ou
 #endif
   { 
     float *const VH_Dir = dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE);
+    memset(VH_Dir, 0, RCD_TILESIZE * RCD_TILESIZE * sizeof(*VH_Dir));
     float *const PQ_Dir = dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE / 2);
+    memset(PQ_Dir, 0, (RCD_TILESIZE * RCD_TILESIZE / 2) * sizeof(*PQ_Dir));
     float *const cfa =    dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE);
+    memset(cfa, 0, RCD_TILESIZE * RCD_TILESIZE * sizeof(*cfa));
     float (*const rgb)[RCD_TILESIZE * RCD_TILESIZE] = (void *)dt_alloc_align_float((size_t)3 * RCD_TILESIZE * RCD_TILESIZE);
 
     // No overlapping use so re-use same buffer; also note we use divide-by-2 index for lower mem pressure

```

**Comment by johnny-bit** [comment]
It (IMO) should be then

 ```diff
 diff --git a/src/iop/rcd_demosaic.c b/src/iop/rcd_demosaic.c
 index 3419c6154..9ef04e8ab 100644
 --- a/src/iop/rcd_demosaic.c
 +++ b/src/iop/rcd_demosaic.c
 @@ -315,8 +315,11 @@ static void rcd_demosaic(dt_dev_pixelpipe_iop_t *piece, float *const restrict ou
  #endif
    { 
      float *const VH_Dir = dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE);
 +    memset(VH_Dir, 0, sizeof(float) * RCD_TILESIZE * RCD_TILESIZE);
      float *const PQ_Dir = dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE / 2);
 +    memset(PQ_Dir, 0, sizeof(float) * (RCD_TILESIZE * RCD_TILESIZE / 2));
      float *const cfa =    dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE);
 +    memset(cfa, 0, sizeof(float) * RCD_TILESIZE * RCD_TILESIZE);
      float (*const rgb)[RCD_TILESIZE * RCD_TILESIZE] = (void *)dt_alloc_align_float((size_t)3 * RCD_TILESIZE * RCD_TILESIZE);
  
      // No overlapping use so re-use same buffer; also note we use divide-by-2 index for lower mem pressure
 ```

Mostly due to `size_t` shenenigans.

Would you like to make a PR? Your first in darktable :wink: !

**Comment by heckflosse** [comment]
> Would you like to make a PR? Your first in darktable

No, let's wait for confirmation from @Thanatomanic. Then Hanno can make the pr ;-)

**Comment by johnny-bit** [comment]
(BTW - darktable's ca correct could use fixes the one in RawTherapee received ;))

**Comment by heckflosse** [comment]
@johnny-bit Isn't `sizeof(*VH_Dir)` more flexible than `sizeof(float)` ?

**Comment by heckflosse** [comment]
> darktable's ca correct could use fixes the one in RawTherapee received

I talked about that with Hanno, but first the raw ca correction in dt needs to work fine in preview mode imho. Maybe I'm wrong, but last time I talked with hanatos about raw ca correction in dt (on LGM Saarbrücken), he said, it does not work well in dt preview mode because it does not play well with the roi concept in dt. Current raw ca correction implementation in RT needs to process the full raw data.

**Comment by johnny-bit** [comment]
Same difference really... Point is to make sure that something returning `size_t` is first or first elem is casted to `size_t` so we don't get things like https://github.com/darktable-org/darktable/issues/3298 (see https://github.com/darktable-org/darktable/pull/7419) :wink: 

 ```diff
 diff --git a/src/iop/rcd_demosaic.c b/src/iop/rcd_demosaic.c
 index 3419c6154..9ef04e8ab 100644
 --- a/src/iop/rcd_demosaic.c
 +++ b/src/iop/rcd_demosaic.c
 @@ -315,8 +315,11 @@ static void rcd_demosaic(dt_dev_pixelpipe_iop_t *piece, float *const restrict ou
  #endif
    { 
      float *const VH_Dir = dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE);
 +    memset(VH_Dir, 0, sizeof(*VH_Dir) * RCD_TILESIZE * RCD_TILESIZE);
      float *const PQ_Dir = dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE / 2);
 +    memset(PQ_Dir, 0, sizeof(*PQ_Dir) * (RCD_TILESIZE * RCD_TILESIZE / 2));
      float *const cfa =    dt_alloc_align_float((size_t) RCD_TILESIZE * RCD_TILESIZE);
 +    memset(cfa, 0, sizeof(*cfa) * RCD_TILESIZE * RCD_TILESIZE);
      float (*const rgb)[RCD_TILESIZE * RCD_TILESIZE] = (void *)dt_alloc_align_float((size_t)3 * RCD_TILESIZE * RCD_TILESIZE);
  
      // No overlapping use so re-use same buffer; also note we use divide-by-2 index for lower mem pressure
 ```

**Comment by jenshannoschwalm** [comment]
@heckflosse Thanks Ingo for that catch. Although - i confess i don't fully understand why that is necessary. Do we need the alpha channel to be zero for windows gtk?

About the ca correction, we really **need** to tackle that, for me the current dt solution is non-functional. Is on my "to do list" if no one else steps in...

**Comment by heckflosse** [comment]
@jenshannoschwalm 

> Although - i confess i don't fully understand why that is necessary.

Well, it's a while ago I implemented the tiled rcd processing (more than two years). Usually, if I use calloc instead of malloc, it's for a reason. But being it so long ago, I can't remember the reason :-(

**Comment by heckflosse** [comment]
> About the ca correction, we really need to tackle that, for me the current dt solution is non-functional.

I agree. I will support you or/and other dt devs on improving raw ca correction in dt.

**Comment by heckflosse** [comment]
> Do we need the alpha channel to be zero for windows gtk?

Don't think so. RT code has no alpha channel.

**Comment by Thanatomanic** [comment]
I can confirm the fix as well. Thank you for the quick response.

**Comment by jenshannoschwalm** [comment]
Thanks for confirming.
