### ISSUE TITLE
[Issue Template] proposal for rewrite

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7566]
Seeing some issues of the recent days, I would like to **propose** an **update** of the current **issue template**.

One might think, it could be shortened, but I hope, my motivation prevails
- Developers want to be treated with respect. Fair enough. So should we respect the reporters. Hence I removed lot of threatening tone (still issues can be closed anyway with relevant flag, if needed)
- Changed a bit to a more friendly tone (I hope)
- Give a bit more clear guidance in the template, how to make a good report (not everyone read the wiki)
- Normal users are potentially not familiar with the commenting function here, hence I restructured a bit
- Professional reporters will just skip no matter how long/short

I hope you guys like it...
@TurboGit: I think, this one if for you :-)

---------------------------------------------------------------------------------------------------------
```
<!-- IMPORTANT
Make sure that this bug has not already been opened or closed by searching the issues on GitHub.

Be aware, developers spend their spare time to help. 
Would you like to be somewhat foreced to guess, what is meant? 
Therefore please help to be as accurate and concise as possible!

Your report is very much appreciated and help may come very fast!

So please fill in most of the items below and provide detailed information.

Further information, howto report an issue:
https://github.com/darktable-org/darktable/wiki#reporting-bugs
-->

**Describe the bug/issue**
<!-- A clear and concise description of what the bug/issue is. -->


**To Reproduce**
<!-- Please provide detailed steps that can reproduce the behavior, such as, but not limited to: -->
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error


**Expected behavior**
<!-- A clear and concise description of what you expect to happen. -->


**Screenshots**
<!-- If applicable, add screenshots to help explain your issue. -->

**Screencast**
<!-- If applicable, add screencast in mp4 format <=10MB of size to help explain your issue. -->


**Bisect**
<!-- 
If you are capable to bisect this issue, that would be a huge contribution and appreciated help!

Actually it is rather simple and provides a clear report at the end
HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes

A YouTube tutorial for bisect: https://www.youtube.com/watch?v=D7JJnLFOn4A
 -->

<!-- If bisect is available, please paste the output below (maybe marked as "code" for easy reading) -->


**Platform (please complete the following information):**
<!-- From below list, please fill as much as possible. -->

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
<!-- 
Please add any other context about the problem here, for example: 
Kindly delete not-applicable lines, to be easier legible
-->

 - Can you reproduce with another Darktable version? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproduce with a fresh edit (removing history)? **yes/no**
 - Attach an XMP if this is necessary
 - Is the issue still present using an empty/new config-dir (e.g. start dt with --configdir "/tmp")


<!-- (Recommendation for frequent reporters: collect your commands and build a script for next time) -->
```

**Comment by parafin** [comment]
I read bug reports in my mail client most of the time and all these comments are quite annoying - users quite often keep them or make a mess when it's impossible to distinguish the template from actual data. I would prefer all these instruction to be in wiki and issue template just having one comment: "Read this before posting <link>". While the rest of the template should form a structure, which I don't think needs comments. Really, is it useful to clarify that "describe the bug" means "description of what the bug is"? It's just noise IMHO.

**Comment by AxelG-DE** [comment]
> While the rest of the template should form a structure, which I don't think needs comments. Really, is it useful to clarify that "describe the bug" means "description of what the bug is"? It's just noise IMHO.

Basically I agree with you. 
I didn't want to drift too far away from today's status, as I do not know @TurboGit well enough, how much he would support a more drastic change. If that is welcome, I also opt for it.

**Comment by parafin** [comment]
Yeah, let's hear some more opinions first.

**Comment by TurboGit** [comment]
I agree with having less comments. I would even remove:
> So please fill in most of the items below and provide detailed information.

As we already have "Therefore please help to be as accurate and concise as possible!"

In many cases we anyway ask for more information depending on the context. But I feel that the proposal here describe the most asked questions.

**Comment by johnny-bit** [comment]
How about... not having comments at all, instead all comments be super concise instructions... eg instead of:

```
**Screenshots**
<!-- If applicable, add screenshots to help explain your issue. -->
```
Have something like
```
**Screenshots**
Screenshots showing the issue go here. If screenshots aren't applicable - remove this section
```
or even
```
**Screenshots**
Remove this section if it isn't applicable (eg no screenshots).
```


Ultimately it needs to help users produce best bug reports... And maybe comments aren't obvious really. Glaring things like left over "remove this section" would be (IMO) a bit better ;)

**Comment by TurboGit** [comment]
Yes, would work for me.

**Comment by AxelG-DE** [comment]
o.k.
I rework the proposal accordingly

**Comment by AxelG-DE** [comment]
So, here we go...
I still did not get feedback from our language wizard Chris :-) but whatever he recommends, might be implemented later as well :-)

- So, no more comments. 
- The advices I have packed in _Italic_ (aiming a bit optical structure, in case guys do not delete), so I hope this version now fits your expectation:

```
**Introduction**
_pleease delete when done/understood_

Make sure that this bug has not already been opened or closed by searching the issues on GitHub.

Be aware, developers spend their spare time to help. 
Would you like to be somewhat foreced to guess, what is meant? 
Therefore please help to be as accurate and concise as possible!

Your report is very much appreciated and help may come very fast!

Further information, howto report an issue:
https://github.com/darktable-org/darktable/wiki#reporting-bugs

---------------------------------------------------------------


**Describe the bug/issue**



**To Reproduce**
_Please amend or remove, what is/isn't applicable_
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error


**Expected behavior**


**Screenshots**
_Please remove, if not applicable (e.g. no screenshots)_

**Screencast**
_Please remove, if not applicable (e.g. no screencast)_


**Bisect**
_Please remove, if you do not know, what bisect is, or if you do, but not applicable_

_A biscet is huge contribution and appreciated help_
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_




**Platform**
_Please fill as much as possible inccluding "unknown" and remove those lines, which are clearly not applicable_

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please fill as much as possible inccluding "unknown" and remove those lines, which are clearly not applicable__

 - Can you reproduce with another Darktable version? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproduce with a fresh edit (removing history)? **yes/no**
 - Attach an XMP if this is necessary
 - Is the issue still present using an empty/new config-dir (e.g. start dt with --configdir "/tmp")? **yes/no**
```

**Comment by AxelG-DE** [comment]
I got valuable input from Chris.
Today is family time, so I may update this evening or tomorrow :blush:

**Comment by AxelG-DE** [comment]
Above proposal finally updated.
@TurboGit would you take a look and decide to take over, pls?

**Comment by johnny-bit** [comment]
OK... Imo looks fine :)

**Comment by jenshannoschwalm** [comment]
I think in the introduction it should be "if understood" or what exactly is the meaning of that sentence?

**Comment by AxelG-DE** [comment]
> I think in the introduction it should be "if understood" or what exactly is the meaning of that sentence?

Darned Germanism :-(
Thanks :-)
Done!

**Comment by AxelG-DE** [comment]
pity this did not get the necessary acknowledgement :-(

**Comment by johnny-bit** [comment]
Sorry. Busy times. Thanks for reminding! Done the PR in #8537

Again - sorry for not picking it up earlier!

**Comment by AxelG-DE** [comment]
> Sorry. Busy times. Thanks for reminding! Done the PR in #8357
> 
> Again - sorry for not picking it up earlier!

No need to apologise, you where not assigned to do so, neither we aligned that way :-)
