### ISSUE TITLE
darktable does not start in Windows if the user is written in Cyrillic

### ISSUE THREAD

**Issue by VolnaJ** [darktable-org/darktable#7568]
darktable version 3.4.0
windows 8.1
_______
darktable does not start in Windows if the user is written in Cyrillic 
C:\Users\[Cyrillic_username]\AppData\Local\darktable\ - folder is empty, darktable does not start
If you use a user profile with an English name on this PC, the program starts normally.

**Comment by Nilvus** [comment]
It's about special character. Your issue is a duplicate of #7489. Think about closing this issue and follow discussion on that last issue.

**Comment by johnny-bit** [comment]
Duplicate of #7489
