### ISSUE TITLE
Tamron 17-35 mm identified as Canon 28 mm prime lens and Tamron 24-70 mm as Sigma lens

### ISSUE THREAD

**Issue by KiAchim** [darktable-org/darktable#7570]
**Describe the bug**
Darktable identfies lenses of imported images in Canon RAW format wrong.
A Tamron SP AF 17-35mm f/2,8-4 DI LD Asph. is identified as Canon EF 28mm f/2.8 IS USM
A Tamron SP 24-70mm F/2.8 Di VC USD is identified as Sigma 24-70mm f/2.8 IF EX DG HSM
It is NOT a matter of the lensfun data base. Lens correction module offers both lenses in the drop down menus.

**To Reproduce**
1. Import 20201121-_MG_0719.CR2 and 20201129-_MG_0759.CR2
   (-> https://wandafish.ocloud.de/index.php/s/ECxTkkKiMZYrJzs)
2. Open image information module
3. Check lens

**Expected behavior**
lens = Tamron SP AF 17-35mm f/2,8-4 DI LD Asph. for 20201121-_MG_0719.CR2
lens = Tamron SP 24-70mm F/2.8 Di VC USD for 20201121-_MG_0759.CR2

**Screenshots**
not necessary

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0, downloaded from https://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_18.04/amd64/darktable_3.4.0-1.1_amd64.deb
 - OS: 
System:    Host: UX490UA Kernel: 5.4.0-48-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
**Additional context**
 - Problem existing since 2.3.1
 - Steps above do reproduce with an empty/new config-dir
 - Steps above reproduce with a 3.4.0 flatpak installation

**Comment by parafin** [comment]
> It is NOT a matter of the lensfun data base. Lens correction module offers both lenses in the drop down menus.

It's a matter of exiv2 guessing a lens name. There is a way to correct its behaviour with ~/.exiv2 file.

**Comment by Wishmaster-de** [comment]
Interesting.
When i call
exiv2 ./20201121-_MG_0719.CR2 -pt |egrep 'LensModel|LensType' 
on the terminal i get
Exif.CanonCs.LensType                        Short       1  Canon EF 28mm f/2.8 IS USM
Exif.Canon.LensModel                         Ascii      74  TAMRON 17-35mm F/2.8-4 Di OSD A037
Exif.Photo.LensModel                         Ascii      35  TAMRON 17-35mm F/2.8-4 Di OSD A037

The LensType is what @KiAchim gets. Which of both elements LensType or LensModel will be taken in account in darktable?  
Why is that?
When i look into my FujiFilm raw files i only see an Exif.Photo.LensModel entry. I never had problems with my lenses on darktable.

**Comment by johnny-bit** [comment]
It's combination of Camera manufacturers not documenting their RAW formats, lens identification not being too much documented too, bunch of guesswork of volunteers and multiple lenses sharing similar IDs.

I think we (I mean people like @AxelG-De who have waaay more experience with exiv2 workarounds) and exiv2 foks should just document various problems in lens identification and how to work around those

**Comment by KiAchim** [comment]
> > It is NOT a matter of the lensfun data base. Lens correction module offers both lenses in the drop down menus.
> 
> It's a matter of exiv2 guessing a lens name. There is a way to correct its behaviour with ~/.exiv2 file.

Yes, @johnny-bit, I know that and I have put an .exiv2 into my home folder as found in various posts. 
[canon]
1=Tamron 24-70 mm just to try
74=TAMRON 17-35mm F/2.8-4 Di OSD A037
35=Tamron 17-35 mm just to try
It didn't change the behaviour. 
So, my question would be:
   where do I have to put which .exiv with what content in order to make it work?

(When I extract Lens information as you did, I get 
achim@UX490UA:~/Schreibtisch/tmp/test$ exiv2 /home/achim/Bilder/freshimport6/20201121-_MG_0719.CR2 -pt |egrep 'LensModel|LensType'
Exif.CanonCs.LensType                        Short       1  Canon EF 28mm f/2.8 IS USM
Exif.Canon.LensModel                         Ascii      74  TAMRON 17-35mm F/2.8-4 Di OSD A037
Exif.Photo.LensModel                         Ascii      35  TAMRON 17-35mm F/2.8-4 Di OSD A037
achim@UX490UA:~/Schreibtisch/tmp/test$ exiv2 /home/achim/Bilder/freshimport6/20201121-_MG_0759.CR2 -pt |egrep 'LensModel|LensType'
/home/achim/Bilder/freshimport6/20201121-_MG_0759.CR2: Failed to open the file
achim@UX490UA:~/Schreibtisch/tmp/test$ exiv2 /home/achim/Bilder/freshimport6/20201129-_MG_0759.CR2 -pt |egrep 'LensModel|LensType'
Exif.CanonCs.LensType                        Short       1  Sigma 24-70mm f/2.8 IF EX DG HSM
Exif.Canon.LensModel                         Ascii      74  24-70mm
Exif.Photo.LensModel                         Ascii       8  24-70mm)

**Comment by AxelG-DE** [comment]
Hello @KiAchim,

I did not check yet by my self, whether you did all above steps correct. For this moment I just assume "yes".

Then there is one more step to do: 
- you need to remove (not delete/trash) the pictures in question from your data base.
- To do so, go to lighttable, select the pictures in doubt and click remove (don't worry your edits, xmp will not be deleted, provided you have those stored and not deselected via preferences)
![grafik](https://user-images.githubusercontent.com/49004103/103411578-0c9dfc00-4b71-11eb-983b-9a4e7ef3042b.png)
- subsequently import your folder(s) again
- if everything correct, now your lens should be recognized

if that still does not work, we need some forth and back communication. For that I'd like to invite you to IRC (https://webchat.freenode.net/#darktable there you will find me and others at similar Nick name (mostly). In my case I just ommited the -DE)

I parallel I will try for my self with your above data.

**Comment by AxelG-DE** [comment]
@KiAchim 
1) you have had one "wrong" perception, about which number should be implemented
2) it is tricky, to actually find exactly the name you need, so lensfun will finally really take it.

What I did:
```
exiftool -G -n -Lens* 20201121-_MG_0719.CR2
[MakerNotes]    Lens Type                       : 502
[MakerNotes]    Lens Drive No AF                : 1
[EXIF]          Lens Info                       : 17 35 0 0
[EXIF]          Lens Model                      : TAMRON 17-35mm F/2.8-4 Di OSD A037
[EXIF]          Lens Serial Number              : 0000000000
[Composite]     Lens                            : 17
[Composite]     Lens ID                         : 502
[Composite]     Lens                            : 25.8246126830532
```
and

```
exiftool -G -n -Lens* 20201129-_MG_0759.CR2
[MakerNotes]    Lens Type                       : 137
[MakerNotes]    Lens Drive No AF                : 1
[EXIF]          Lens Info                       : 24 70 0 0
[EXIF]          Lens Model                      : 24-70mm
[EXIF]          Lens Serial Number              : 0000000000
[Composite]     Lens                            : 24
[Composite]     Lens ID                         : 137
[Composite]     Lens                            : 36.4582767290162
```

From that I took the Lens ID 502 and 137 (you picked the byte length information from exiv2 -pa)

and finally I have this in my exiv2 wich **works with your files**! (after I reimported)
```
[canon]
137=Tamron SP 24-70mm F/2.8 Di VC USD
502=TAMRON 17-35mm F/2.8-4 Di LD Aspherical (IF)
```

**Comment by KiAchim** [comment]
Great,  @AxelG-de, thank you so much for your effort and investigation.
It still doesn't want to work, which must be a matter of location of the .exiv2 file then.
I'll try joining the IRC.

**Comment by AxelG-DE** [comment]
> Great, @AxelG-DE, thank you so much for your effort and investigation.
> It still doesn't want to work, which must be a matter of location of the .exiv2 file then.
> I'll try joining the IRC.

I saw you on IRC, just I was AFK for some time
let us continue on IRC tho
:)
