### ISSUE TITLE
Importing RAWs add "binary comment" to description metadata

### ISSUE THREAD

**Issue by battata** [darktable-org/darktable#7579]
**Describe the bug**

When importing RAWs to darktable 3.4, a description metadata is added with the content "binary comment".
I'm importing NEF RAWs from a Nikon camera, I tried changing comments off and comments on with a blank field, issue persists.

**Expected behavior**

A clear description metadata

**Screenshots**

![captura](https://user-images.githubusercontent.com/24719702/103415894-f25d2180-4b62-11eb-8d94-58e025bdc530.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Ubuntu 20.10

**Additional context**
<!-- Add any other context about the problem here, for example:
Sample NEF:

[sample.zip](https://github.com/darktable-org/darktable/files/5757601/sample.zip)

**Comment by phweyland** [comment]
I cannot reproduce this.
Could you share a screen shot of the import parameter (metadata, ...) ?
Is the preference "write sidecar file for each image" set ?

> I tried changing comments off and comments on with a blank field

What does that mean ?

**Comment by battata** [comment]
> I tried changing comments off and comments on with a blank field
> 
> What does that mean ?

Sorry, that's the in camera setting

> Could you share a screen shot of the import parameter (metadata, ...) ?

![Captura de pantalla de 2020-12-31 13-56-34](https://user-images.githubusercontent.com/24719702/103419055-1e32d400-4b70-11eb-9051-abf20ff035ec.png)

![Captura de pantalla de 2020-12-31 13-58-10](https://user-images.githubusercontent.com/24719702/103419084-41f61a00-4b70-11eb-9e01-e217c2d571a2.png)

> Is the preference "write sidecar file for each image" set ?

Yes


Sample NEF
https://drive.google.com/file/d/1Ctv1aETL0TKggSUETkKucgRqoMa-Nsq0/view?usp=sharing

**Comment by ptilopteri** [comment]
you are not applying metadata ie: publisher
because you have not selected "apply metadata on import"
but you may add metadata after import using the metadata
editor present in lighttable view on the right panel

**Comment by TurboGit** [comment]
I have this also with some files.

**Comment by phweyland** [comment]
I've tried your file.
Without "write sidecar file for each image" that works fine.
But when set, the second time I import (meaning that the xmp has been written) I get the issue.
I'll look at this.

**Comment by phweyland** [comment]
This comes from your NEF:
```
$ exiv2 -PE sample.NEF
Exif.Photo.UserComment                       Undefined  44  charset=Ascii binary comment

I'm wondering what we should do in that case ...
```

**Comment by johnny-bit** [comment]
Is it literally a "binary comment" or can any value be dumped and analyzed?

if it's literally a "binary comment" then... special case it to empty string?

**Comment by phweyland** [comment]
> Is it literally a "binary comment" or can any value be dumped and analyzed?
> 
> if it's literally a "binary comment" then... special case it to empty string?

Currently exiv2 returns the text : `charset=Ascii binary comment`.
Exif.Photo.UserComment supports 2 bytes coding and should be retrieved through the comment() method.
With this method I get  `binary comment`, which is, I believe, the actual text provided by the camera.

I'll review the fields of this type to treat properly the format, but that won't remove the `binary comment`


@battata , do you have any setting on your camera where you set something meaningful for this field, (you have already set properly the author :smiley: ) ?

**Comment by phweyland** [comment]
> if it's literally a "binary comment" then... special case it to empty string?

I've found in exiv2 code the case `binary comment` for invalid comment; I'll skip this.

**Comment by cyrillelauzon** [comment]
For what it's worth, I'm having the same issue on darktable 3.4.0 on windows with canon CR2 files.

No matter what I write to the description field, it reverts back to binary comment when I select another image in the lightable and then come back to the image I edited the description field. Same if I edit the description field and save a metadata editor preset. Upon saving the preset, the description field reverts back to binary comment.

PS (I write metadata to sidecar files, I tried unchecking the setting and restarted darktable, and it has no effect)

**Comment by phweyland** [comment]
> No matter what I write to the description field, it reverts back to binary comment when I select another image in the lightable and then come back to the image that I edited the description field.

I cannot reproduce this... when I overwrite (with the current master) the description field, my change is maintained whatever "write sidecar file for each image" setting.
Hopefully the fix above should get rid of this fake value.
How do work the other fields ?

**Comment by cyrillelauzon** [comment]
Actually, I cannot modify any value in the metadata panel (title, author, notes etc) unless I save them in a new preset and then apply the said preset to the image.

**Comment by ptilopteri** [comment]
odd that, works for me on master, 88d81cbfa
using the metadata panel editor

**Comment by phweyland** [comment]
> Actually, I cannot modify any value in the metadata panel (title, author, notes etc) unless I save them in a new preset and then apply the said preset to the image.

This is worth opening a specific issue for this ! Could you do it please ?

**Comment by cyrillelauzon** [comment]
I'm on it, thanks!!

**Comment by cyrillelauzon** [comment]
Here is the new issue #7598
