### ISSUE TITLE
Leica D-LUX 7

### ISSUE THREAD

**Issue by carminecare** [darktable-org/darktable#7588]
Itry to open raw pics from my Leica D-LUX 7 but I have the error you can see in picture attached
Thanks

![Schermata 2021-01-01 alle 00 30 47](https://user-images.githubusercontent.com/76827223/103431246-87950000-4bcd-11eb-881a-0945d6aa325c.png)

**Comment by johnny-bit** [comment]
Have you seen https://github.com/darktable-org/darktable/wiki/Camera-support ? Have you sent sample raw files to raw.pixls.us?

**Comment by jenshannoschwalm** [comment]
@johnny-bit please close as merged in rawspeed

**Comment by johnny-bit** [comment]
I think @LebedevRI closes such issues when switching connected rawspeed submodule in commit.
