### ISSUE TITLE
SIGSEGV when starting slideshow

### ISSUE THREAD

**Issue by vrnhgd** [darktable-org/darktable#7590]
### Overview
Starting slideshow results in a segmentation fault after initially rendering the empty screen.

Debugger suggests this is happening in `write_image` in `view/slideshow.c`. Specifically `memcpy(data->buf.buf, in, sizeof(uint32_t) * datai->width * datai->height);`.

### To Reproduce
1. clean checkout DT master branch
2. build using CMake 3.17.5 (`cmake --build ./build --target darktable -j8`)
3. run darktable executable (`. ./build/bin/darktable`)
4. click on 'Slideshow' in the top right
5. await crash

### Expected Behavior
I actually have never used the slideshow before and was just exploring... not sure what should happen but I have a feeling segfault isn't intentional.

### Screenshots
[Relevant blank screen](https://user-images.githubusercontent.com/10472668/103432595-8ead1580-4baf-11eb-8e16-74d288145354.png)

### Platform
- Darktable Version: HEAD
- OS: Ubuntu Focal Fossa 20.04.1
- OpenCL: not sure
- GPU: AMD Radeon HD 6970
- GPU Driver: built-in open-source

### Additional Context
- Can you reproduce with another Darktable version?
Haven't tried yet, in progress
- Are the steps above reproduce with a fresh edit (removing history)? 
Yes
- Did you compile Darktable yourself? If so which compiler was used, with what options?
Yes, process as described above.

**Comment by vrnhgd** [comment]
Note that I didn't actually select any images for the slideshow. This might be user error but error messages aren't clear. 

[log output](https://github.com/darktable-org/darktable/files/5758594/darktable_bt_FFUYV0.txt) from one of the runs.

Will do some more digging on my own but figured I'd document in case anybody else has the same issue.

**Comment by vrnhgd** [comment]
it seems this occurs when calling `write_image` after the last image in the slideshow. Perhaps somebody with more experience with the slideshow module can opine on the expected/intended behavior at the end of a slide show

**Comment by johnny-bit** [comment]
Slideshow should exit after last image IMO...

**Comment by johnny-bit** [comment]
OK, so I checked - at the last image darktable should say "no mor images pres any key to return to lighttable" and after keypress - return to lighttable. I tried replicating the issue and for me - slideshow works...

**Comment by vrnhgd** [comment]
hmm interesting. Thanks @johnny-bit. I'll keep this open and see if I can pin down a better repro. I still need to test this on a clean install from stable version

**Comment by johnny-bit** [comment]
Now that I think about it... I think that this and #8595 might be connected - both are sigsegv in slideshow with hard reproducer.
