### ISSUE TITLE
Importer for Lightroom XMP sidecars should allow only getting metadata

### ISSUE THREAD

**Issue by bakubo** [darktable-org/darktable#7595]
**Is your feature request related to a problem? Please describe.**

The importer that handles XMP sidecars from Lightroom should have an option to at a minimum select either importing the metadata (keywords (tags), star ratings, color labels, etc.), importing the editing instructions, or both.  It properly imports the metadata and, I think, most people want that.  It, naturally, is impossible to do a good job trying to emulate Lightroom editing so I don't want that.  Particularly since it is very difficult to get rid of it for tens of thousands of files because discard history has a problem.  See my discard history bug report: **Discard history does not remove Lightroom emulated steps #7594**

[https://github.com/darktable-org/darktable/issues/7594](url)

This issue (and related Lightroom XMP import issues) was discussed in this thread:

[https://discuss.pixls.us/t/importing-lightroom-xmp-sidecars/20668](url)

Here is a 2013 article written by the developer Pascal Obry about importing Lightroom XMP files along with image files into darktable:

[https://www.darktable.org/2013/02/importing-lightroom-development/](url)

The 3.4 manual info about importing Lightroom XMP files:

[https://www.darktable.org/usermanual/en/overview/sidecar-files/sidecar-import/](url)

**Describe the solution you'd like**

An option to select either importing the metadata, importing the editing instructions, or both.

**Alternatives**

As a workaround I tried discard history, but it has a bug and will not remove steps added to try and emulate Lightroom editing.  See my bug report above.

**Additional context**

**Comment by bakubo** [comment]
How do I "check if the master branch has fixed it"?

**Comment by ptilopteri** [comment]
@bakubo you would have to run a new version of the master branch and check

since you are talking about lightroom, and didn't provide the requested system information, 
I assume you are running windows.  you will need to compile or otherwise obtain a version of
master compiled after your report and try it for yourself

**Comment by bakubo** [comment]
This bug applies to all versions (Linux, Windows, Mac).  I am on Win10.

**Comment by bakubo** [comment]
The new 3.4.1.1 for Windows includes a bug fix for something related to Lightroom XMP files.  The download page is here:

[https://github.com/darktable-org/darktable/releases/tag/release-3.4.1](url)

One of the bugs fixed just says this:

**Fix Lr metadata import, this is done only if no other XMP present.**

I do not know exactly what that means though.  Is it the issue reported here or is it something different?

**Comment by mikaelstaldal** [comment]
Even better would be if you could choose exactly which development steps to import. I would probably only want to import crop&rotate.
