### ISSUE TITLE
Lighttable: cannot modify metadata in the Metadata editor

### ISSUE THREAD

**Issue by cyrillelauzon** [darktable-org/darktable#7598]
On darktable 3.4.0, Windows version, Canon CR2 files

When on my system I modify any value in the metadata panel (title, author, notes, description etc), the values reverts back to the content of the currently applied preset upon selecting another image in the lightroom view.

The only way to change a value for me is:
-Enter a new value in any field
-Save the current value to a preset (new or modify existing preset both work)
-Apply the preset to the current image

(Note the write to xmp sidecar option is checked in the storage options. I tried to uncheck it and restart darktable with no effects on the encountered behaviour)

**Comment by phweyland** [comment]
> -Enter a new value in any field

Sorry, that's obvious, but it's better to be sure.
Do you hit `enter` at the end ? Or `apply` button ?
Is there any image selected ?

**Comment by phweyland** [comment]
> (Note the write to xmp sidecar option is checked in the storage options. I tried to uncheck it and restart darktable with no effects on the encountered behaviour)

Only restart dt, is not enough. To make sure the saved xmp file doesn't interfere you should delete it or rename it.

**Comment by cyrillelauzon** [comment]
> Sorry, that's obvious, but it's better to be sure.
> Do you hit `enter` at the end ? Or `apply` button ?
> Is there any image selected ?

Those are productive questions thanks!
-There is an image selected. The problems appears when selecting another image and then going back to the first image where the metadata was edited.

That being said:
- When I hit enter for each indivudual values, the new values are saved properly
- When I press on apply without hitting enter for each individual values, the value is not saved.

> Only restart dt, is not enough. To make sure the saved xmp file doesn't interfere you should delete it or rename it.
I will investigate and report back

**Comment by cyrillelauzon** [comment]
ohhh My bad, I did not press on apply.
Thanks for asking obvious questions, I shall be more methodical next time

However, an open question. Shouldnt it auto-apply when entering values and the selected images in lightable?

**Comment by phweyland** [comment]
> However, an open question. Shouldnt it auto-apply when entering values and changing the selected images in lightable?

Well, this is questionable of course, but the idea is that is you don't finish your work (escape to cancel, enter or tab to go to the following entry, it is not to be applied (mistake, ...)...

**Comment by cyrillelauzon** [comment]
>Well, this is questionable of course, but the idea is that is you don't finish your work (escape to cancel, enter or tab to go to the following entry, it is not to be applied (mistake, ...)...

A very sound reason

Just an observation. At the moment, when applying a metadata preset, it does not need to be applied and is saved automatically when changing images. That may be why I assumed it would be the same behaviour when entering values in the individual fields and not needing to press apply.

**Comment by phweyland** [comment]
> when applying a metadata preset, it does not need to be applied and is saved automatically when changing images.

Yes, this action is auto-complete. And this is consistent with all other plugins.
BTW, I've lost myself some entries for the same reasons as yourself, but the software cannot guess (always) our intentions...

**Comment by cyrillelauzon** [comment]
Yes, it's best to leave the current behavior as is. 

Thanks for your time!

**Comment by phweyland** [comment]
> Thanks for your time!

You're welcome.
If it's ok for you, please close this issue.
