### ISSUE TITLE
Unable to use Collect Images

### ISSUE THREAD

**Issue by grahamhjones** [darktable-org/darktable#7600]
Darktable V3.4

When I click on the dropdown in Collect Images in the Lighttable view, an expanded list is shown in a box. The main list of items is on the left and the subitems on the right. The last line of which is "module order" from "Darktable". If I try to scroll down the list to get to tags for example, the scrolling behaves incorrectly. The last line as above is repeated as it scroll upwards in the box and then the box size reduces. If I try to scroll again, the last line rolls up and again the window gets smaller until it closes itself.

This happens everytime I use the menu, I am unable to select images using different criteria.

**Comment by phweyland** [comment]
> If I try to scroll down the list to get to tags for example, the scrolling behaves incorrectly.

For me the full list appears, then there is no need to scroll to reach any of the options, including tags. I have just to click on it.

**Comment by grahamhjones** [comment]
There is an element of user error here - sorry.

I now realise that the whole of the possible selection options are shown when the dropdown is clicked and I can select an image by its tag.

However, if one scrolls in this box, the above behaviour is exhibited.

**Comment by phweyland** [comment]
> However, if one scrolls in this box, the above behaviour is exhibited.

If I scroll, the full options list move up or down (very slowly), but I haven't the behavior you describe.

**Comment by johnny-bit** [comment]
This is actually a GTK issue that *we* can't really fix. Similar behaviour can happen for any GTK-based app and it's combo boxes. I sorta "got used to it".

See https://gitlab.gnome.org/GNOME/gtk/-/issues

and If I understand correctly, this is what's happening: https://gitlab.gnome.org/GNOME/gtk/-/issues/2793
