### ISSUE TITLE
Backtraces created during darktable crash on Windows (may) have incomplete information

### ISSUE THREAD

**Issue by pahl34** [darktable-org/darktable#7602]
**Describe the bug**
Backtraces created in case of a darktable crash on Windows at least sometimes (maybe always) lack information that usually should be included.

*Note:* Unfortunately, I don't know details about the backtraces and what info they should exactly contain. This issue came up in discussion of #7445 so I just wanted to rise attention to this, hoping that there might be a way of improvement.

In case of (meanwhile fixed) issue #7445, a backtrace created on Windows 10 was not helpful, while on Linux a useful backtrace was created for the exact same kind of crash:

[darktable_bt_7445_LINUX.txt](https://github.com/darktable-org/darktable/files/5759109/darktable_bt_7445_LINUX.txt)
[darktable_bt_7445_WIN.txt](https://github.com/darktable-org/darktable/files/5759110/darktable_bt_7445_WIN.txt)

I am aware that Windows development is not in focus of the darktable project and that this might simply be a disadvantage of Windows. However, if it was possible to improve the value of Windows backtraces, this could speed up bug analysis in case the person reporting is not able to reproduce on Linux. Especially with sporadic issues, the usefulness of a backtrace could be crucial for analysis.

**To Reproduce**
1. Install darktable 3.4 on Windows 10.
2. Follow the steps to Reproduce in #7445. 
3. Open the backtrace file and try to find useful information in there.

**Expected behavior**
Backtraces created on Windows should be as helpful as on Linux (if technically possible).

**Platform (please complete the following information):**
 - Darktable Version: 3.4, but probably a general problem
 - OS: Windows 10

**Comment by MStraeten** [comment]
are you sure, darktable is the correct project to adress it?  
the darktable developers aren't responsible for the msys/mingw build system and also not for windows itself.

**Comment by johnny-bit** [comment]
It's more complex than that... That would require windows builds to be built not as "Release" but "RelWithDebInfo" and on top of that hopefuly attach gdb & debugging symbols for libraries.

So - part of msys2 would have to have installed gdb + debugging symbols and darktable package would have to be built with sub-optimal RelWithDebInfo type... Which would make installer probably 2-3x times as big, the runtimes of darktable itself would increase and while generated report would be a bit more useful I doubt it's much of a benefit...

The only IMO sensibe point for that would be building nightly builds to have debugging info and invite users to test nightly builds - that would mean the issues would have chance to be caught earlier with essentially "testers", but making builds work on gh ci is pain :disappointed: 

Lastly - I need to echo what @MStraeten said: we need more windows/osx devs. That would be far more beneficial than better backtraces ;)

**Comment by pahl34** [comment]
I understand, thanks for the explanations!
I was not sure whether this is a darktable issue, nor was I meaning to say someone is responsible. I had just hoped there was a reasonable way to improve the situation regarding the win backtraces.

@johnny-bit: Should we then close this issue?

**Comment by johnny-bit** [comment]
> Should we then close this issue?

Hmm... Yes... But we do need Win/OSX devs & users advanced enough to self-build master and test PRs
