### ISSUE TITLE
Feature request: Lighttable right click in top bar for list of module presets same as darkroom view

### ISSUE THREAD

**Issue by cyrillelauzon** [darktable-org/darktable#7603]
A small detail

In the lighttable, It would be great if to apply a module preset, we could right click on any module's top bar in consistence with the darkroom behavior. The preset menu would then appear just the same as in the darkroom view.

Although it only affects 4 modules in the lightroom, it would be a convienent shortcut, speed up navigation a bit and be consistent accross all of the application.

**Comment by ptilopteri** [comment]
and if one has more than one preset for a module ???

**Comment by cyrillelauzon** [comment]
>and if one has more than one preset for a module ???

In effect what I'm proposing is the exact same behaviour as when clicking on the hamburger for a module in the Lighttable. But instead it could be accessible by right clicking on the top bar of a module in the lighttable.

It is a nitpick, but this way of doing is already implemented in the darktable view and I think it would be nice if it would be the same in the lighttable view.
