### ISSUE TITLE
resize filmstrip in darkroom does not resize thumbs

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#7604]
**Describe the bug**
resize filmstrip in darkroom does not resize thumbs

**To Reproduce**
1. Go to 'darkroom'
2. Drag filmstrip separator and see thumbs not resized

**Expected behavior**
thumbs should be resized

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: GNU/Linux

**Comment by AlicVB** [comment]
hmmm... I do see a glitch where the current thumb doesn't rescale correctly. In fact it seems to be rescaled but crop to the old size...
But the other are resized correctly here...

**Comment by AlicVB** [comment]
@TurboGit : I've fixed the "current thumbnail" issue in PR #7608 ... and wait for more info for the other thumbs ;)
