### ISSUE TITLE
Crash during retouch

### ISSUE THREAD

**Issue by Minh-Ly** [darktable-org/darktable#7609]
**Describe the bug**
I was using the module Retouch with drawn masks (path) in blurring mode when darktable crashed. 

Backtrace: 
[darktable_bt_CXVAW0.txt](https://github.com/darktable-org/darktable/files/5759369/darktable_bt_CXVAW0.txt)

**Platform (please complete the following information):**
 - Darktable Version: darktable master at 9ad96451823cb0e55cc4c1ce09d47c281c47a35d
 - OS:  windows 10
 - OpenCL ON
 - NVidia 940MX, Driver 460.89

**Comment by johnny-bit** [comment]
What were you doing at the point of crash? removing or adding a path node? seems like there's something problematic in way the list of points is handled.

**Comment by Minh-Ly** [comment]
Doesn't happen with latest master anymore.

**Comment by johnny-bit** [comment]
I'm gonna say it's "once in a blue moon" kind of problem. There's another report with similar problem https://github.com/darktable-org/darktable/issues/3318

So IMO this error is not fixed and there's non-zero chance that it'll happen.

btw: your backtrace contains loads of valuable info... I'll try to cook something to avoit problem in the future
