### ISSUE TITLE
3Dlut root folder cannot be set or changed

### ISSUE THREAD

**Issue by JozsefTaborita** [darktable-org/darktable#7611]
**Describe the bug**

1. preferences
2. processing
3. Folder select doesn't work
![image](https://user-images.githubusercontent.com/36929104/103445892-9b963b80-4c79-11eb-9a8d-4f5ecdc53e4d.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version:  3.4.0 Flatpak
 - OS:  Manjaro Linux
 - 
 - 

**Additional context**

**Comment by phweyland** [comment]
I cannot reproduce this.

>     3. Folder select doesn't work

What does happen ?
Could you elaborate a bit more ?

**Comment by wpferguson** [comment]
It's a flatpak so it runs in a sandbox.  You have to change the permissions on the flatpak to access the file system.  It's not a darktable bug.  It's a flatpak "feature".

**Comment by johnny-bit** [comment]
Please see https://davejansen.com/give-full-filesystem-access-to-flatpak-installed-applications/

currently darktable does not maintain it's own flatpak and does not use "portals" functionality (in many places) so we can't really help here. I wonder if flatpak can be "made" to allow access...
