### ISSUE TITLE
Removing module from module group causes crash

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#7619]
**Describe the bug**
Create a new module group, then realize you made a mistake and don't want a certain module in the group.  Click the X to remove it and darktable crashes.  Backtrace identifies line 1854 in src/libs/modulegroups.c

**To Reproduce**

**Expected behavior**

Module gets removed.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: current git
 - OS: Ubuntu 18.04
 - OpenCL activated
 - Nvidia 970M nvidia driver 455.38

**Additional context**

You can remove a complete module group, just not a single module.

**Comment by johnny-bit** [comment]
Please check and test #7629 - that should fix it :D

**Comment by wpferguson** [comment]
@johnny-bit Thanks!
