### ISSUE TITLE
Panasonic DC-GF10 (DC-GX880 DC-GF90)

### ISSUE THREAD

**Issue by elizeusdsantos** [darktable-org/darktable#7623]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
So for which camera is the actual support request?
Notably, there are sample coverage issues for the referenced cameras, there are no samples for DC-GF90 at all,
and samples DC-GF10 should ideally be replaced with a new set (where all images have the same content)

**Comment by elizeusdsantos** [comment]
@LebedevRI its all the same camera. GF10 in Asia, GX800 in Europe (I think) and GX880 in USA

**Comment by elizeusdsantos** [comment]
@LebedevRI

Released in 2018:
GX880(EU), GF10(Asia), GF90(Japan)

Identical spec model but released in 2017.
GX800(EU), GF9 (Asia + Japan), GX850(USA)
