### ISSUE TITLE
[FEATURE] parametric mask by edge detection

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7628]
**Is your feature request related to a problem? Please describe.**

I ever whish to have a parametric mask, which can detect the sharpness, so that I can quickly and easily mask (or invert ! ), what is inside the DOF (not only for sharpening, but other things might want to do, like blending, darkening or desaturating what is outside DOF or what ever)

Example: The leaves/needles in this picture:
![Screenshot_20210102_161609Ö_small](https://user-images.githubusercontent.com/49004103/103460743-1cf0db00-4d19-11eb-96b7-67210ef25fbb.png)

**Describe the solution you'd like**

Like I said above, a parametric mask, that can detect the edges. I think some part of the algo is already existing whith what we have in ctrl+shift+F for focus detection

**Alternatives**

Indeed one can fiddle a lot with hue and chroma or what ever, but that is opposite from fast and finally not really suitable:
(I admit I did not play very long, but that fiddling is already beyond my patience [L,C and h also been used])

You can see/guess things which are sharp are outside the mask and dull parts are in the mask. Not nice....

![Screenshot_20210102_162828](https://user-images.githubusercontent.com/49004103/103460777-5d505900-4d19-11eb-80b3-f75b9b511e71.png)

**Comment by johnny-bit** [comment]
Hmmm...

Can you explain how that differs from https://github.com/darktable-org/darktable/issues/2670 or https://github.com/darktable-org/darktable/issues/2671? Maybe it's more of a choice of finetuning guided filter for feathering?

**Comment by AxelG-DE** [comment]
I understand, #2670 and #2671 are kinda drawn masks, what I am aiming is a parametric mask which will be adjusted with those four nodes, just like we see them here in the example of b-channel.

I have no clue and no glue, what is meant with (sorry being unqualified :-P)
>Maybe it's more of a choice of finetuning guided filter for feathering?

I remember an IRC conversation, where @aurelienpierre was firstly not very pro, rather con. After @rawfiner outlined some ideas, I got the feeling, it is not impossible and actually deemed to be useful

**Comment by AxelG-DE** [comment]
Ping 😊

**Comment by AxelG-DE** [comment]
Ping2

**Comment by jenshannoschwalm** [comment]
Hi @AxelG-DE , i started working on something pretty close what you want/need. The underlying algorithm is implemented and used already in the dual demosaicers, could you have a look (RCD + VNG4) and give a feedback please?

**Comment by AxelG-DE** [comment]
> Hi @AxelG-DE , i started working on something pretty close what you want/need. The underlying algorithm is implemented and used already in the dual demosaicers, could you have a look (RCD + VNG4) and give a feedback please?

Dear Hanno,
I did not play around with (RCD + VNG4) blending mask and dual threshold, but just now yes. And I must say WOW. Yes, this is what might come very handy, once  we find something like this in the masking (need all the other masking functions indeed, like feathering, blur, inverse, etc. etc.)
Cannot wait for it :-)

**Comment by jenshannoschwalm** [comment]
Thanks for the feedback. I am currently thinking of how to implement it the "best dt way", probably (the first step) as another parametric mask as you suggested. I will give you a note if there is something to test ...

**Comment by heckflosse** [comment]
Happy to see, that my Contrast Threshold mask from RT seems to find its way into dt code ;-)

**Comment by jenshannoschwalm** [comment]
Yes Ingo, the gui side as an additional parameter for parametric mask is implemented. Now some days visiting my fresh granddaughter. After a few days off I  will know how to do the rest. First time touching that code so a lot of source reading...

**Comment by johnny-bit** [comment]
Oh shut up bot! work is ongoing in #8597

**Comment by jenshannoschwalm** [comment]
@AxelG-DE i think you could close this issue for now as we have the details mask in master now.

Just to let you know, for 3.8 i will continue work on something like this and maybe we can discuss it further then ...

**Comment by AxelG-DE** [comment]
Yes definitely and thanks a lot
