### ISSUE TITLE
High CPU usage when toolbar context menu open in darkroom

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#7631]
**Describe the bug**

When a right-click context menu of a toolbar item is opened in darkroom, darktable's CPU usage increases considerably (normally under 5%, increases to over 70% on my PC).

**To Reproduce**

1. Open any raw image with no previous edits
2. Observe darktable's current CPU usage
3. Right click on one of the darkroom lower toolbar items to bring up the context menu
4. Observe darktable's CPU usage again, should be increased

**Expected behavior**

CPU usage does not noticeably increase when the context menu is open.

**Screenshots**

Normal CPU usage when context menu is not open
![cpu_usage_normal](https://user-images.githubusercontent.com/5001906/103461811-c3dd7300-4d29-11eb-84e4-b6b456abdf2c.png)

High CPU usage when context menu is open
![cpu_usage_high](https://user-images.githubusercontent.com/5001906/103461844-f0918a80-4d29-11eb-9681-635fa02dabc2.png)

**Platform (please complete the following information):**
 - Darktable Version: master 0b8b63a49b09062f45d400d71232918b4ae67927 
 - OS: Arch Linux (x86_64) 
 - Reproduces with both OpenCL on and off 
 - Intel HD Graphics 520, Mesa 20.3.2

**Comment by johnny-bit** [comment]
Cannot replicate at all - 3.2.1, 3.4.0 and current master (5e274f321) not even a blimp on CPU and mine's decade old xeon...

Can you open darktable in profiler and see what spins up your CPU?

**Comment by flannelhead** [comment]
I'll be happy to try it out. Would you be able to recommend a profiler? So far I built with `RelWithDebInfo` and ran `perf top -p $(pidof /usr/bin/darktable)` - then opened the context menu. A lot of time seems to be then spent in `libpixman-1.so` (for which I don't have debug symbols). Not sure if that is meaningful yet.

**Comment by johnny-bit** [comment]
gprof / gperftools / valgring with cachegring and then analyze with kcachegrind... loads of options...

TBH I'd say that it MAY be some problem on your end since there hardly are any busyspins in darktable's context menu code...

**Comment by flannelhead** [comment]
Profiled with valgrind + callgrind. When the CPU spins, there seem to be a lot of calls to cairo + pixman emitted from the main loop. Might be something triggering unnecessary redraws.

I noticed that the color picker toolbox on the left hand side drawer has to be opened to reproduce this (there are no active color pickers though). Opening any of the other toolboxes on the left doesn't affect the behaviour.

**Comment by johnny-bit** [comment]
OK, so you are right: In order to replicate the problem, the color picker has to be opened. The problem isn't stemming from darktable signals, so the question is why cairo/pixmal spin... and whether it's color picker module problem or right-click modules in general :/

pinging @dterrahe due to huge overhaul he did on colorpicker...

**Comment by dterrahe** [comment]
Interesting one. I can't immediately think of how I would have broken it, but besides the colorpicker rewrite another suspect is the ctrl-scroll resizing refactor, which uses the "draw" signal to resize the lib module. But I just tried switching that off and it doesn't help, so it seems to not cause this issue.

I guess this is one of those cases where a bisect would be helpful. @flannelhead / @johnny-bit is this a recent problem? Can it be replicated on 3.2.1 _with_ an open colorpicker? (unclear from the trail above whether that was tried).

**Comment by johnny-bit** [comment]
same problem on 3.2.1, just tried.

**Comment by dterrahe** [comment]
Possibly something deep in the pipe processing then. The scary stuff. It doesn't really make sense that just opening the colorpicker module would trigger extra processing (even without a picker active or current samples being displayed). That possibly can be optimised to _only_ occur when one of these conditions _requires_ the processing, but that would be papering over the (probably unnecessary?) inefficiencies that an open menu seems to cause. I have no concrete suggestions how to get to the bottom of this :-/

**Comment by jenshannoschwalm** [comment]
I think this might be due to the darkroom expose function ...

https://github.com/darktable-org/darktable/blob/a88b30f1beba2b692c5163c404cfb8a3dac16d3b/src/views/darkroom.c#L506-L512

**Comment by flannelhead** [comment]
Commenting out https://github.com/darktable-org/darktable/blob/8b296ed1b6bb096355bac3fda35a21bc9268e849/src/libs/colorpicker.c#L230
resolves the high CPU usage but obviously the label isn't updated then. Pretty weird.

**Comment by dterrahe** [comment]
I started to suspect my semi failed experiment with font scaling in _label_size_allocate_callback (in colorpicker.c) but removing that doesn't seem to solve the issue. And anyway, that postdated 3.2.1

**Comment by flannelhead** [comment]
@dterrahe good point, I tried that too and got the same result.

Replacing that line with
```
  const gchar *old_text = gtk_label_get_text(GTK_LABEL(sample->output_label));
  if(g_strcmp0(text, old_text)) gtk_label_set_text(GTK_LABEL(sample->output_label), text);
```
also resolves the issue (don't update the text if there's nothing to update) but it's kind of a band-aid.

**Comment by dterrahe** [comment]
A band-aid may be the only solution and I don't find this one particularly inelegant at all; it is an efficiency gain anyway, even if jumping through all the hoops that a full update does didn't cause problems. I would have suggested having the if also switch off the gtk_widget_queue_draw on the color patch in the next line, because that would be unchanged too if the values are unchanged, so
```
  if(g_strcmp0(gtk_label_get_text(GTK_LABEL(sample->output_label)), text))
  {
    gtk_label_set_text(GTK_LABEL(sample->output_label), text);
    gtk_widget_queue_draw(sample->color_patch);
  }
```
except that there is the dummy label option (4, "◎"), which complicates things...

I suspect that a call to gtk_widget_queue_resize within gtk_label_set_text (or .._set_label or _set_markup; they all have the same problem) triggers an infinite loop. What is strange, is that this loop only happens when the pop-up menu is showing. How would a resize within the side panel (that doesn't propagate outside it) impact the menu. Mystery...

**Comment by flannelhead** [comment]
@dterrahe if you have a suitable patch already in mind (e.g. what you wrote in the comment), please feel free to open a PR.

Further information: I noticed that if you decrease the window size enough that the popup menu partially occludes the histogram, there are also a plenty of redraws of the histogram generated.

**Comment by dterrahe** [comment]
Ok, will do. Need to submit another small fix for colour picker too.

**Comment by dterrahe** [comment]
The other small fix was actually not as trivial as I assumed (or even a fix) so I submitted just this with a few other cleanups.

GTK_DEBUG=resize,geometry did show me that there's a lot of other funny stuff going on with widget updates/resizes that I don't fully understand. Which makes me wonder how much potential there is to make the gui behave more smoothly...

**Comment by johnny-bit** [comment]
> Which makes me wonder how much potential there is to make the gui behave more smoothly...

A LOT ;)

**Comment by dterrahe** [comment]
Specifically what I mean is by preventing unnecessary resizes by gtk (rather than the stuff that we ourselves do inefficiently; in theory we can see that we are doing that, but the things behind the scenes... it is fun using gtk inspector to count the number of signals fired. :-)
