### ISSUE TITLE
darktable doesn't remove all XMP metadata in exported image

### ISSUE THREAD

**Issue by allmyfavoriteusernamesaretaken** [darktable-org/darktable#7637]
**Describe the bug**
I disable all metadata on image export (see screenshot 1), but when I open the exported JPEG e.g. in Gimp, there are still some XMP metadata elements left (see screenshot 3).

I am aware that there is some metadata (as shown in screenshot 4 from the same JPEG image), which cannot be removed, but the data in screenshot 3 (maybe except _Xmp.tiff.Orientation_) should not be there.

**To Reproduce**
1. Disable the inclusion of metadata in exported JPEG file according to screenshot 1.
2. Export any image with metadata to a JPEG file according to screenshot 2.
3. Open exported JPEG in Gimp and view metadata (Image -> Metadata -> View Metadata, view XMP tab)

**Expected behavior**
Only compulsory metadata like in screenshot 4 should be included, but no _Xmp.exif.DateTimeOriginal_, _Xmp.xmp.Rating_ or _Xmp.xmpMM.DerivedFrom_.

**Screenshots**

Screenshot 1:
![image](https://user-images.githubusercontent.com/19348894/103466833-05c9e180-4d49-11eb-959f-410a1d12559f.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/19348894/103466900-b932d600-4d49-11eb-96ea-749d83225968.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/19348894/103467027-f9468880-4d4a-11eb-8e78-3ab7d91d38b3.png)

Screenshot 4:
![image](https://user-images.githubusercontent.com/19348894/103467030-04011d80-4d4b-11eb-86fb-143c66a02688.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Xubuntu 20.04
 - Gimp Version: 2.10.22

**Additional context**

**Comment by phweyland** [comment]
I get something similar to you:

```
$ exiv2 -PEXI 003.jpg
Xmp.xmp.CreateDate                           XmpText    22  2020-02-29T15:31:01.67
Xmp.xmp.CreatorTool                          XmpText    24  NIKON D750 Ver.1.02     
Xmp.xmp.Rating                               XmpText     1  1
Xmp.exif.DateTimeOriginal                    XmpText    19  2020:02:29 15:31:01
Xmp.xmpMM.DerivedFrom                        XmpText     7  003.NEF
```

> Only compulsory metadata like in screenshot 4 should be included,

I'm not aware of compulsory metadata. I'll search about this. If you have any reference to norms or rules, please share them. 

>  but no _Xmp.exif.DateTimeOriginal_, _Xmp.xmp.Rating_ or _Xmp.xmpMM.DerivedFrom_.

Agreed, I'll look at this.

**Comment by allmyfavoriteusernamesaretaken** [comment]
> I'm not aware of compulsory metadata. I'll search about this. If you have any reference to norms or rules, please share them.

I have by no means knowledge about that topic but I thought that the image dimensions in pixels would always be present in the EXIF data, but that might be a mistake on my side.

**Comment by phweyland** [comment]
> > I'm not aware of compulsory metadata. I'll search about this. If you have any reference to norms or rules, please share them.
> 
> I have by no means knowledge about that topic but I thought that the image dimensions in pixels would always be present in the EXIF data, but that might be a mistake on my side.

I haven't found any information about this. Of course if something is found we'll try to follow the standard.

**Comment by kmilos** [comment]
Re mandatory metadata, I guess it depends on what export format you use, and how it stores the metadata.

Mandatory tags for Exif are in the tablespec: http://www.cipa.jp/std/documents/download_e.html?DC-008-Translation-2019-E

For example, if you export to TIFF, you could also fully omit the Exif IFD in theory, but you still have mandatory tags required by the baseline [TIFF 6.0 spec](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf), or if you so wish [TIFF-EP](http://www.barrypearson.co.uk/top2009/downloads/TAG2000-22_DIS12234-2.pdf) with its mandatory tags (which sort-of [overlaps with Exif](https://en.wikipedia.org/wiki/TIFF/EP#Differences_from_TIFF_and_Exif), but stores the tags in the image IFD rather than a dedicated IFD)...

**Comment by phweyland** [comment]
Thanks for the links.
I had seen but haven't been able to see a better usage of that compared to what we have.
dt follows these rules and doesn't remove any of these tags,
except if the user requests it (exif tag not checked for export).

In theory we could have another flag, saying to remove only the non mandatory... only theory, isn't it ?
