### ISSUE TITLE
Allow setting of image title when exporting images to piwigo

### ISSUE THREAD

**Issue by allmyfavoriteusernamesaretaken** [darktable-org/darktable#7638]
**Is your feature request related to a problem? Please describe.**
When exporting images from darktable directly to piwigo, these images later appear in piwigo with the name _darktable.XXXXXX_ where _XXXXXX_ is an alphanumeric identifier according to the regular expression _[0-9A-Z]{6}_. As piwigo takes this identifier as image name which is shown to the viewer it would be better if we could specify a more meaningful image name directly in darktable.

**Describe the solution you'd like**
darktable should have a text entry in the _export selected_ module for piwigo where the user can specify the image name, maybe also using variables, e.g. _$(TITLE) $(SEQUENCE)_.

**Alternatives**
If no text entry box can be added, maybe darktable could use the name of the film roll containing the image and use this film roll name together with a sequence number as image name.

**Additional context**

**Comment by phweyland** [comment]
There is some work to get something strong here...
As a workaround I export to files, with the necessary iptc metadata, and then use the update album piwigo plugin to load my images (limited to 20 by 20) but that works smoothly for me.

**Comment by allmyfavoriteusernamesaretaken** [comment]
Hi and thanks for commenting. I also export to files and import these files then to piwigo, but this title issue is the only thing that holds me back from using the direct export to piwigo. Like this I could speed up a bit my workflow.

It would also be absolutely great if the title allowed even using piwigo's extended description. Like this even language tags could be used, e.g. _Title[lang=ES]Título[/lang]_, something that's not possible with file names as the forward slash is not allowed in file names (at least on an UNIX-like OS).

**Comment by phweyland** [comment]
> It would also be absolutely great if the title allowed also using piwigo's extended description. Like this even language tags could be used, e.g. _Title[lang=ES]Título[/lang]_, something that's not possible with file names as the forward slash is not allowed in file names (at least on an UNIX-like OS).

Not sure to understand this, but you can definitively use these markers in metadata, title, description, etc ...
To get them in piwigo I export like this (see in particular the iptc metadata which are understandable by piwigo):

![image](https://user-images.githubusercontent.com/23012047/104368857-6a303200-54fb-11eb-807c-09db196cc7a0.png)

**Comment by allmyfavoriteusernamesaretaken** [comment]
In piwigo I can use extended descriptions to assign a title in different languages to an image:

![image](https://user-images.githubusercontent.com/19348894/104493674-ab951000-55d5-11eb-9608-68e71faadfc0.png)

If I import images from files into piwigo, piwigo takes by default the file name as image title, e.g. _Boxers.jpg_ converts into the image title _Boxers_. Theoretically, I could name a file _Boxers[lang=DE]Boxer[/lang][lang=ES]Boxeadores[/lang].jpg_ to already give an image title in several languages so that I don't have to add later manually all translations in piwigo by hand. But: the forward slash cannot be used on UNIX-like systems in file names, so this option is out. If I could use such a format in the direct upload from darktable to piwigo, this would allow me to skip the part of always adjusting the image titles manually.

**Comment by phweyland** [comment]
> If I import images from files into piwigo, piwigo takes by default the file name as image title, e.g. _Boxers.jpg_ converts into the image title _Boxers_.

Right.


> Theoretically, I could name a file _Boxers[lang=DE]Boxer[/lang][lang=ES]Boxeadores[/lang].jpg_

If that's the title you want you don't need to rename the file.

`Iptc.Application2.ObjectName` is understood by piwigo as the title of the image.
Then having `Boxers[lang=DE]Boxer[/lang][lang=ES]Boxeadores[/lang]` is the metadata `title` and, at export time, putting this in `Iptc.Application2.ObjectName` as above you should get what you want.

Maybe some tweak should be made in piwigo local files editor plugin / local configuration. See piwigo metadata doc.

**Comment by allmyfavoriteusernamesaretaken** [comment]
Thanks a lot, I wasn't aware of this feature.

In case someone in the future with the same problem finds this thread: piwigo doesn't interpret the IPTC data out of the box, it needs to be enabled. In my case I add the following data to the photo:

![image](https://user-images.githubusercontent.com/19348894/104652209-0ce1df80-56b9-11eb-8063-184b1398a299.png)

This translates into the following metadata embedded into the image (can be checked with the piwigo plug-in _Read metadata_):

```
2#005 = Title
2#080 = Creator
2#120 = Description
```

To make piwigo use this IPTC data the following lines need to be added to _local/config/config.inc.php_ (preferably using the piwigo plug-in _LocalFiles Editor_):

```
$conf['use_iptc'] = true;

$conf['use_iptc_mapping'] = array(
'name'    => '2#005',
'author'  => '2#080',
'comment' => '2#120'
);
```
More information about piwigo and metadata can be found in [https://piwigo.org/doc/doku.php?id=user_documentation:metadata](url)
