### ISSUE TITLE
.dng files scanned from plustek 8200 not opening

### ISSUE THREAD

**Issue by santanacarballo** [darktable-org/darktable#7643]
I have many Digital negatives scanned with a Plustek 8200 that they open in soft like RAW image viewer, but Darktable is unable to read them. They get imported, but lightable doesn't show the images, neither does the darktable, even when checked on exiv2
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment]
@santanacarballo  - Please follow https://github.com/darktable-org/darktable/wiki/Camera-support especially make sure you've sent a sample file to raw.pixls.us and please open a new issue using [new camera support issue](https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E)

Thanks!

**Comment by jenshannoschwalm** [comment]
I guess they have be scanned with "VueScan"? There have been issues before with plustek scanners and this soft, we really need an example file to check, it might be not a "new camera" problem but instead an example how bad some software treats DNG files ...

**Comment by johnny-bit** [comment]
"new camera" requires sending sample files :)

**Comment by santanacarballo** [comment]
> I guess they have be scanned with "VueScan"? There have been issues before with plustek scanners and this soft, we really need an example file to check, it might be not a "new camera" problem but instead an example how bad some software treats DNG files ...

Thanks a lot for your input guys!, I'll be opening a new camera support issue with samples, the software was actually SilverFast Plus 8.8, it came with the scanner by default. I'm completely new to GitHub, although I'm quite sure is about how the soft treated the dng file because once I used Adobe DNG converter, DT imported the new files without any issue.

**Comment by johnny-bit** [comment]
Make sure you send samples to https://raw.pixls.us/ :)

**Comment by johnny-bit** [comment]
Thanks! Closing in favour of #7662 :)
