### ISSUE TITLE
Tagging tree view markers do not update for untagged images/no selection

### ISSUE THREAD

**Issue by grudgingly** [darktable-org/darktable#7646]
In lighttable the tagging module in tree view does not clear the markers when an untagged image is selected, or when the selection is cleared.

**To Reproduce**
1. In lighttable view, collect together a mix of images with and without tags
2. Expand the tagging module and select the tree view
3. Select a tagged image, or a selection of images including tagged images.
3a. The tagging module will show ticks/dash markers as appropriate.
4. Change the selection so it does not include tagged images (either unselect the tagged images, click on an untagged image, or click 'select none').
4a. The ticks/dash markers will still show in the tagging module.

(Selecting list and then tree view again will clear the markers.)

**Expected behavior**
The ticks/dash markers should be cleared when no tagged images are selected.

**Platform:**
 - Darktable Version: 3.4.0-2 distro release
 - OS: Arch Linux

**Comment by phweyland** [comment]
I can reproduce this. I'll look at it.

**Comment by phweyland** [comment]
Thanks for reporting !
