### ISSUE TITLE
Basic Adjustment Crop align 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7647]
Current master.

In the Basic adjustments enhancements is the tooltip for crop and rotate to draw straight line leads to confusion.
So if I read the tooltip and follow instructions nothing happens.

One can only drag/draw a line once the angle is changed, which gets the crop grid and then do alignment. That would mean misalign it first by angle change and then align it.

![image](https://user-images.githubusercontent.com/1119439/103470868-5fa8c680-4d9e-11eb-81fe-6831755acf11.png)

**Comment by AlicVB** [comment]
good catch. I'll have a look !

**Comment by johnny-bit** [comment]
@AlicVB - crap & rot is _special_ module. I wanted to "tackle" this by simply putting "right-click" stuff in module hinter, similarly to #7596 and have angle slider tooltip simply say "set rotation angle" or something like that :) i wouldn't go all out with basic adjustments group and try to emulate all that module does ;)

**Comment by AlicVB** [comment]
@johnny-bit : of course... in fact the main problem isn't really the tooltip, but, as you say, to not allow all the mouse actions via basics widgets. Otherwise I fear that this will very quickly ends with weird issues or inconsistencies...

**Comment by AlicVB** [comment]
PR #7663 disable "on canvas" controls for basics widgets and add a warning in the tooltip.

@johnny-bit : I've not follow your suggestion about the tooltip because I think that such info in the tooltip may be useful for discovery. I'm not saying that hinter msg wouldn't be good too, but more as a complement.
