### ISSUE TITLE
darktable-tools-noise depends on graphicsmagick (imagemagick fork) whereas darkable depends on imagemagick

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#7651]
**Describe the bug**
This has been already mentioned in the ["How to create camera noise profiles for darktable" article on discuss.pixls.us](https://discuss.pixls.us/t/how-to-create-camera-noise-profiles-for-darktable/7428/99).

When installing `darktable` on Ubuntu 18.04 / 20.04,` imagemagick` is used as dependency [see also DefineOptions.cmake#L13](https://github.com/darktable-org/darktable/blob/master/DefineOptions.cmake#L13). 
However when installing the `darktable-tools-noise` the forked alternative `graphicsmagick-imagemagick` is required for installation and leads to `imagemagick` to be uninstalled, see 

 ```bash
The following NEW packages will be installed:
  darktable-tools-noise graphicsmagick{a} graphicsmagick-imagemagick-compat{ab} 
0 packages upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 680 kB of archives. After unpacking 5.396 kB will be used.
The following packages have unmet dependencies:
 graphicsmagick-imagemagick-compat : Conflicts: imagemagick but it is not going to be installed
                                     Conflicts: imagemagick:i386 but it is not going to be installed
The following actions will resolve these dependencies:

     Remove the following packages:                                                           
1)     imagemagick-6.q16 [8:6.9.10.23+dfsg-2.1ubuntu11.2 (focal-security, focal-updates, now)]
```

The culprit here lies in [`tools/noise/subr.sh` in line 487 & 494](https://github.com/darktable-org/darktable/blob/master/tools/noise/subr.sh#L487) in which very a very imagemagick specifc command is used to detect whether the noise calibration images are neither over- nor under-exposed. This command however is not compatible with `graphicsmagick-imagemagick`.
It gives the following error output during a noise profile generation run:
```
convert convert: Unrecognized channel type (-channel).
/usr/lib/darktable/tools/subr.sh: line 488: [: : integer expression expected
convert convert: Unrecognized channel type (-channel).
/usr/lib/darktable/tools/subr.sh: line 495: [: : integer expression expected
```

**Expected behavior**
Because the darktables C code seems to be compatible to both imagemagick and graphicsmagick APIs I'd assume the same for the scripts which use the CLI interface of the aforementioned tool.
I'd expect the script to use CLI calls which are either compatible with both tools, or just have a code path for both tools.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1 and 3.4.0
 - OS: Ubuntu 18.04 / 20.04

**Comment by johnny-bit** [comment]
darktable can use imagemagic 7 or graphicsmagick. the noisetools clearly use imagemagick. Person making `darktable-tools-noise` package probably didn't set dependencies right.

**Comment by da-phil** [comment]
Jup, that's what I assumed too. I already started to look into the imagemagick commands and try to find an equivalent command for graphicsmagick and then we could maybe have code paths for either tool, because the way the CLI tools work is deviating quite a lot these days.
I would appreciate support from imagemagick / graphicsmagick experts though as this stuff is quite foreign to me and quite a hassle to figure out how to assemble those CLI calls :smile: 
It actually wouldn't surprise me that the C APIs also have deviated substantially. Does darktable still build using graphicsmagick?

**Comment by da-phil** [comment]
I just found out that all debian packages depend on graphicsmagick instead of imagemagick, see `control` file of [OBS packages](https://build.opensuse.org/package/show/graphics:darktable/darktable):

```
Source: darktable
Section: graphics
Priority: optional
Maintainer: Debian PhotoTools Maintainers <pkg-phototools-devel@lists.alioth.debian.org>
Uploaders: David Bremner <bremner@debian.org>
Build-Depends: cmake,
               debhelper (>= 10),
               intltool,
               iso-codes,
               libcairo2-dev,
               libcolord-dev,
               libcolord-gtk-dev,
               libcups2-dev,
               libcurl4-gnutls-dev | libcurl-dev,
               libexiv2-dev,
               libflickcurl-dev,
               libglib2.0-dev,
               libgphoto2-dev,
               libgraphicsmagick1-dev,
               libgtk-3-dev (>= 3.22),
               libjpeg-dev,
               libjson-glib-dev,
               liblcms2-dev,
               liblensfun-dev,
               liblua5.3-dev,
               libopenexr-dev,
               libopenjp2-7-dev,
               libosmgpsmap-1.0-dev,
               libpng-dev,
               libpugixml-dev,
               librsvg2-dev,
               libsecret-1-dev,
               libsoup2.4-dev,
               libsqlite3-dev,
               libtiff-dev,
               libwebp-dev,
               xsltproc
Standards-Version: 4.1.2
Homepage: http://www.darktable.org/
Vcs-Git: https://salsa.debian.org/debian-phototools-team/darktable.git
Vcs-Browser: https://salsa.debian.org/debian-phototools-team/darktable

Package: darktable
Architecture: any-amd64 any-arm64
Depends: ${shlibs:Depends}, ${misc:Depends}, libjs-prototype, libjs-scriptaculous, fonts-roboto, iso-codes
Replaces: darktable-plugins-legacy (<< 0.9), darktable-plugins-experimental (<< 1.0~)
Breaks: darktable-plugins-legacy (<< 0.9), darktable-plugins-experimental (<< 1.0~)
Description: virtual lighttable and darkroom for photographers
 Darktable manages your digital negatives in a database and lets you view
 them  through a zoomable lighttable. it also enables you to develop raw
 images and enhance them.
 .
 It tries to fill the gap between the many excellent existing free
 raw converters and image management tools (such as ufraw or f-spot).
 The user interface is built around efficient caching of image metadata and
 mipmaps, all stored in a database. the user will always be able to interact,
 even if the full resolution image is not yet loaded.
 .
 All editing is fully non-destructive and only operates on cached image
 buffers for display. the full image is only converted during export. The
 frontend is written in gtk+/cairo, the database uses sqlite3, raw image
 loading is done using rawspeed, high-dynamic range, and standard image formats
 such as jpeg are also supported. The core operates completely on floating
 point values, so darktable can not only be used for photography but also for
 scientifically acquired images or output of renderers (high dynamic range).

Package: darktable-tools-basecurve
Architecture: any-amd64 any-arm64
Priority: optional
Depends: darktable, ${shlibs:Depends}, ${misc:Depends}, dcraw, exiftool, graphicsmagick-imagemagick-compat
Description: The basecurve tool from tools/basecurve/
 darktable is a virtual lighttable and darkroom for photographers: it manages
 digital negatives in a database and can show them through a zoomable
 lighttable. It also enables developing raw images and enhance them.
 .
 This package provides the basecurve tool from tools/basecurve/.
 Another option to solve the same problem might be the darktable-chart module
 from the darktable package.

Package: darktable-tools-noise
Architecture: any-amd64 any-arm64
Priority: optional
Depends: darktable, ${shlibs:Depends}, ${misc:Depends}, dcraw, exiftool, graphicsmagick-imagemagick-compat
Description: Noise profiling tools to support new camerasNoise profiling tools to support new cameras
 darktable is a virtual lighttable and darkroom for photographers: it manages
 digital negatives in a database and can show them through a zoomable
 lighttable. It also enables developing raw images and enhance them.
 .
 This package provides the noise profiling tools to add support for new cameras.
```

**Comment by johnny-bit** [comment]
Generally - darktable itself can work with either graphicsmagic or imagemagick (i've checked when I've done CMYK ignoring code) tools seem to work nicely with imagemagick...

So... imo the default dep for darktable could be switched from graphicsmagick to imagemagick

**Comment by da-phil** [comment]
If it's not a big issue to support the C APIs of both frameworks I wouldn't mind fixing this script to make it compatible with both frameworks ;)
I already reached out to the graphicsmagick forum for getting assistance, because after almost 1h ouf fiddling around with the graphicsmagick CLI tools I'm still way in the dark :stuck_out_tongue_closed_eyes:

**Comment by da-phil** [comment]
I just found out that the computation of [those ImageMagick commands](https://github.com/darktable-org/darktable/blob/4f8915dc3a73f8211ea16f5f94ce48df2861d71f/tools/noise/subr.sh#L483-L499) is bogus!

Let's write out the commands for checking for over/underexposing and test them on the following picture:
https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png
I also measured the related values in gimp and in a python script (see at the end) using pillow / PIL by creating a histogram and essentially applying the same operations as in gimp.


* Overexposed?
Find the percentage of pixels which are over 99% intensity level
`convert "$ImageFile" -define registry:temporary-path=/tmp -channel RGB -threshold 99% -separate -append -format "%[mean]" info: | cut -f1 -d.`
* Underexposed?
Find the percentage of pixels which are below 1% intensity level, in this case the image is just inverted and the same operation is applied again
`convert "$ImageFile" -define registry:temporary-path=/tmp -channel RGB -threshold 99% -separate -append -format "%[mean]" info: | cut -f1 -d.`

Here is a screenshot with the results, in gimp we have in the left histogram the percentile of pixels which have luminosity values of 0-2 and on the right histogram the luminosity values between 252-255.
And in the terminal below I show the results of the ImageMagick commands and my python script.

Those values (213 for overexposed and 329 for underexposed pixels) are neither percentile values, nor pixel counts and hence they are not fit for the comparison in the script, because they are compared against 80, which means that we make sure that not more than 80% of the pixels are in the dark luminosity section and also not more than 80% are within the bright luminostiy section.

![Screenshot-Exposure-Check](https://user-images.githubusercontent.com/810285/103949627-d5fd4e00-513b-11eb-8f91-12b6abd72aca.png)


Does this make sense? Maybe the CLI of ImageMagick changed behavior some time ago? I've been sitting and trying to understand IM for hours now, but without much success :sweat_smile: 

Instead of the ImageMagick / GraphicsMagick pain we could also just use the script I wrote, it just adds the widely available packages `python3-pillow` and `python3-numpy` as a dependency.

```python
from PIL import Image
import numpy as np
import sys

if len(sys.argv) < 1:
    print("you have to provide an image file as argument.")
    sys.exit(-1)

image_file = sys.argv[1]

bright_luminosity_range = [0.99, 1.0]
dark_luminosity_range = [0.0, 0.01]

bright_luminosity_range_bins = (np.asarray(bright_luminosity_range) * 255).astype(int)
dark_luminosity_range_bins = (np.asarray(dark_luminosity_range) * 255).astype(int)
print(f"bright_luminosity_range_bins: {bright_luminosity_range_bins}")
print(f"dark_luminosity_range_bins:   {dark_luminosity_range_bins}")

image_gray = Image.open(image_file).convert("L") # convert into luminosity
total_pixels = image_gray.size[0] * image_gray.size[1]
hist = image_gray.histogram()

bright_luminosity_count = np.sum(hist[bright_luminosity_range_bins[0]:bright_luminosity_range_bins[1]+1])
bright_luminosity_percentage = 100 * bright_luminosity_count / total_pixels
dark_luminosity_count = np.sum(hist[dark_luminosity_range_bins[0]:dark_luminosity_range_bins[1]+1])
dark_luminosity_percentage = 100 * dark_luminosity_count / total_pixels
print(f"{bright_luminosity_count:d} ({bright_luminosity_percentage:.2f}%) pixels fall into bright luminosity section")
print(f"{dark_luminosity_count:d} ({dark_luminosity_percentage:.2f}%) pixels fall into dark luminosity section")
```

**Comment by da-phil** [comment]
For imagemagick the actual correct commands would be
* Check for over-exposing: `convert $ImageFile   -threshold '99%'  -format "%[fx:100*mean]" info:`
* Check for under-exposing: `convert $ImageFile -negate  -threshold '99%'  -format "%[fx:100*mean]" info:`

see
![Screenshot-Exposure-Check2](https://user-images.githubusercontent.com/810285/103958450-51b3c680-514d-11eb-94b2-0cd4e1dd2d4a.png)

Those give me the correct values, also for other pictures.

Now back to the question how to solve it for GM :stuck_out_tongue_closed_eyes:

**Comment by da-phil** [comment]
It looks like I don't understand the output of the original `imagemagick` command and the magic value 80, if they refer to the pixel count or the percentile of pixels (which is in the over/under exposed area).
I understand the motivation though, that those checks want to make sure that we have sufficient over & underexposed areas in the images.

Maybe @dumbbell can help here, I saw that he wrote those lines ;)

**Comment by rawfiner** [comment]
In my opinion, those checks are not really necessary as we have histograms. If they are too much trouble and if their computation is also erroneous, I think maybe we can get rid of them, or replace them using another formula

**Comment by da-phil** [comment]
> In my opinion, those checks are not really necessary as we have histograms. If they are too much trouble and if their computation is also erroneous, I think maybe we can get rid of them, or replace them using another formula

I fully agree, those calculations look quite fragile / random.
In order to enable autonomy of DT users to provide noise profiles, I'd like to simplify the process as far as possible. It's already in a quite good shape, except this dependency mess with IM / GM and the quite random exposure suitability checks.

In my examples above I calculated the percentile of pixels which fall into the darkest 1% luminosity levels and the brightest 1% luminosity levels. So there are two parameters to tune here: 
* luminosity thresholds for dark underexposed / bright overexposed areas
* percentile of pixels which has to fall into those areas

I'd appreciate if anybody with experience, maybe you, @cryptomilk, @hanatos  or @dumbbell could help out here, then I'd like to improve the noise profiling process in a way that the user get's immediate feedback if their test pictures fulfil the criteria to potentially give good noise profile estimates.

**Comment by Oo12LI** [comment]
Hello,

this issue seems to still be present on (k)ubuntu 21.10 and darktable 3.6.1, impossible to install both imagemagick and darktable-tools-noise on my system : 

`/usr/lib/darktable/tools/darktable-gen-noiseprofile -d $(pwd)
===> Check for required tools
--> Check for images handling tools availability
--> Check for images export tools availability
ImageMagick is required to check input images correctness. Please
install this package and re-run this script.

NOTE: You may have to remove GraphicsMagick-related packages before.
--> Check for profiling tools availability
--> Check for tethering tools availability
--> Check for pdf tools availability
`
and
`sudo apt-get install imagemagick
[sudo] Mot de passe de XXX : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Les paquets supplémentaires suivants seront installés : 
  imagemagick-6.q16
Paquets suggérés :
  imagemagick-doc autotrace enscript grads hp2xx html2ps povray radiance ufraw-batch
Les paquets suivants seront ENLEVÉS :
  darktable-tools-basecurve darktable-tools-noise graphicsmagick-imagemagick-compat
Les NOUVEAUX paquets suivants seront installés :
  imagemagick imagemagick-6.q16
0 mis à jour, 2 nouvellement installés, 3 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/237 ko dans les archives.
Après cette opération, 494 ko d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] n
Annulation.
`

As this tool allow to support new camera for noise correction, is there any workaround to generate noise profiles ? 

regards,

**Comment by da-phil** [comment]
Yeah, nobody (incl. me) had time to clean up this dependency mess and nobody seems to be using the noise tools.
I could look into the issue again during the christmas vacation days.

**Comment by Oo12LI** [comment]
I understand, thanks for the answer !

In the meantime by reading carefully your first post, I used the workaround indicated in this discussion [https://discuss.pixls.us/t/how-to-create-camera-noise-profiles-for-darktable/7428/99](url) which worked for me.  

I understand that I shall pay more attention to the image used to generate the noise profile (both over and under exposed areas) as the verification is not done by the tool. I will give a few try and upload the result for LUMIX S5 in the bug tracker. As far as I'm concerned, no urge at all to fix this point :).

Last question if no one use this tool and send the profiles, how are newer cameras supported ?

Thanks for the information given here and on pixls.us !

**Comment by da-phil** [comment]
> Last question if no one use this tool and send the profiles, how are newer cameras supported ?

I guess that's the only way it can work if you've installed DT via a package management system.
But I assume that most people using the tools are also building DT from source and hence don't feel the dependency pain caused by the package management (at least for debian / ubuntu). 

The fact that this issue is still open tells us that this issue is not resolved yet and I didn't have time to look at it again during the past weeks :see_no_evil:
I hope I'll find some time soon, otherwise feel free to help to close this issue.

**Comment by paolobenve** [comment]
@da-phil thank you for you work in order to get rid of this bug. I'm heavily interested in it, because a month ago I tried to elaborate the noise profiles for Canon G5 X m2 and I cannot.

**Comment by da-phil** [comment]
After the problem got attention again, I sat down for a while and want to present a possible solution, maybe @rawfiner might be interested in.
I was really puzzled by this bogus number "80" in the current script version [here](https://github.com/darktable-org/darktable/blob/master/tools/noise/subr.sh#L489) & [there](https://github.com/darktable-org/darktable/blob/master/tools/noise/subr.sh#L496), but I finally learned that the calculated number is the percentile of pixels above the given RGB value threshold (99%) expressed as uint16, then 80 converts to 100% * 80. / (2^16) = 0.122%. Still quite a random but small percentile for checking against sufficient under- and overexposed pixels.
I found a command which works across imagemagick & graphicsmagick with a minor deviation. This is the one which gives me the percent of pixels which falls in the 5% brightest luminosity values and I cross-checked with the luminosity histogram in gimp:
* graphicsmagick: `convert $ImageFile -threshold '95%' -process analyze= -format "%[BrightnessMean]" info:-  | awk '{print int(100 * $1 / 65536)}'`
* imagemagick: `convert $ImageFile -threshold '95%' -process analyze= -format "%[mean]" info:-  | awk '{print int(100 * $1 / 65536)}'`
The number `65536` is the uint16 max value, which is used in both imagemagick & graphicsmagick to express this not normalized percentage.

Those are the results 
* shadows:
![shadows](https://user-images.githubusercontent.com/810285/153046553-911386a5-8723-41d2-9740-f78baf3959d2.png)

* highlights
![highlights](https://user-images.githubusercontent.com/810285/153046585-468f5323-0b46-4aef-b576-4b1af9f7cd2c.png)

With this I'm going to prepare a PR with updates to the script to be used with both imagemagick & graphicsmagick.

**Comment by da-phil** [comment]
> @da-phil thank you for you work in order to get rid of this bug. I'm heavily interested in it, because a month ago I tried to elaborate the noise profiles for Canon G5 X m2 and I cannot.

@paolobenve feel free to upload your calibration pictures, e.g. [at filebin](https://filebin.net/) and post them here or over at the [noise calibration thread @ pixels.us](https://discuss.pixls.us/t/how-to-create-camera-noise-profiles-for-darktable/7428/100).

**Comment by rawfiner** [comment]
Sounds good :-)
Thanks for looking into this!

**Comment by paolobenve** [comment]
> @paolobenve feel free to upload your calibration pictures

@da-phil My internet connection is a pay-por-mb, I cannot

**Comment by paolobenve** [comment]
it doesn't work, see #11328
