### ISSUE TITLE
filmic RGB + color calibration + lens correction = „burnouts“ in editor view in the darkroom

### ISSUE THREAD

**Issue by StefanDieke** [darktable-org/darktable#7654]
I‘m on DT 3.5.0+383~g1dc662d9f

Eventually the picture in the darkroom shows blue burnout spots, when applying ‚lens correction‘ AND ‚filmic RGB‘ AND ‚color calibration‘.  The effect only occurs if all three modules are active. Switching any of these modules off makes the spots vanish. 

I tried several cameras and lenses in ‚lens correction‘ and in all the reasonable combinations (Olympus lens on olympus body, canon lens on canon body) the spots remained. In obscure combinations (Canon lens on smartphone) they vanish. 

In ‚filmic RGB‘ at least threshold and transition affect the effect. 

In color calibration all sliders seem to have some effect on the burnouts. 
![DT-burnouts](https://user-images.githubusercontent.com/34355483/103479637-67349380-4dcf-11eb-8017-6cbea30396fa.png)
![DT-burnouts2](https://user-images.githubusercontent.com/34355483/103479674-a1059a00-4dcf-11eb-84d2-51c259b56d77.png)

**Comment by ralfbrown** [comment]
Can't reproduce, trying setting lens correction to a bunch of Olympus lenses, so you'll need to provide a sidecar and image.   Please also provide the other information requested in the bug-report template.

lens + filmic + calibration is now my default, so I've edited a bunch of Nikon photos without seeing this issue.

**Comment by TurboGit** [comment]
Please can you provide more information ? OS ? On all images ? Only on this one ? Do not expect us to guess, as much information you can give on the reproducibility will definitely help.

**Comment by StefanDieke** [comment]
I'm sorry for providing incomplete information.
Camera is a Sony A7M3; Lens: Tamron, E 28-75 F2.8

Operating System: Manjaro Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.77.0
Qt Version: 5.15.2
Kernel Version: 5.10.2-2-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 7.8 GiB of RAM
Graphics Processor: Radeon RX 570 Series

I can introduce the burnouts in the 'lens correction' module, playing around with the scale slider. Once the burnouts appear, they can be amplified by moving 'threshold' and 'transition' in filmic rgb -> reconstruction.
I played around with some CR2 files from old Canon camera and couldn't reproduce the effect. So it may be related to the Sony files.

![DT-burnouts3](https://user-images.githubusercontent.com/34355483/103487614-ff01a400-4e06-11eb-9860-6cf81e013006.png)

A raw file and corresponding sidecar file are here: https://drive.google.com/drive/folders/1U7It1yMsdR-kcHDjGEcK2z3D2P3cvhpU?usp=sharing

**Comment by da-phil** [comment]
I tried with the provided RAW and sidecar file, played around with lens correction, filmic and color calibration, but could not reprocude the effect.
I'm on 
* 3.5.0+427~ga13d6c80a (compiled from master)
* OpenCL active
* Ubuntu 20.04

Maybe it was already fixed on master?

**Comment by matt-maguire** [comment]
We've seen similar effects like this in #6315, and discussed in pixls.us:
https://discuss.pixls.us/t/is-this-a-3-2-darktable-bug/20247/12

**Comment by StefanDieke** [comment]
I just tried again with a fresh clone from git, following the the instructions for the git version here: https://www.darktable.org/install/
So now I'm on DT 3.5.0+428~g62545c68e.
The effect can still be reproduced. 
Is there any other information I can provide to find out the origin of the problem?

**Comment by StefanDieke** [comment]
I'll check out the discussion at pixls and try if there are any things mentioned which affect the effect on my machine 
Thank you all for your help so far!

**Comment by StefanDieke** [comment]
In this case 'demosaic' - as suggested on the discussion - has nothing to with the effect. No matter which method I use, the effect remains. 
While switching 'color ballance' on/off affects the effect in some way, it doesn't seem to be its origin, since the effect is still there when 'color ballance' is switched of. 
Switching 'filmic rgb' or 'color callibration' off makes the effect disappear. When both are 'on', the effect appears.

**Comment by jenshannoschwalm** [comment]
Tested your image and can't reproduce any issue...

**Comment by StefanDieke** [comment]
Facepalm! I think I found the reason for the effect. In short:

**Though shallst not uncheck 'clip negative RGB from gamut' in 'color calibration'!!!**

Sorry for the trouble!
