### ISSUE TITLE
darktable-elegant themes in Windows: font problem in menus

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7659]
This is a Windows specific issue, it does not happen in Linux.
When selecting darktable-elegant themes, bold font is not rendered correctly in menus. For example

![Cattura6](https://user-images.githubusercontent.com/43290988/103481977-6e16d280-4dde-11eb-98e5-538b53ff93a1.JPG)

unlike the default darktable theme

![Cattura7](https://user-images.githubusercontent.com/43290988/103481999-88e94700-4dde-11eb-8fe0-7738c2221a1f.JPG)

so one can't see which menu item is activated. It affects blend mode menus, as well as presets, and maybe others

Investigating, I have found the following:

- from css we have
```
...
menu,
menu *
...
{
    font-family: "Roboto Light", "Roboto",                  /* best case scenario */
                 "Segoe UI Light", "Segoe UI",              /* Windows 10 default */
                 "SF Pro Display Light", "SF Pro Display",  /* Mac OS X default */
                 "Ubuntu Light", "Ubuntu",                  /* Ubuntu default */
                 "Cantarell",                               /* Gnome default */
                 sans-serif;                                /* default default */
}
```

I have the Roboto font family installed, so the selected font is Roboto Light, otherwise it would be Segoe UI Light. 
In bleng_gui.c the menu font is modified with markup: 

```
mi = gtk_menu_item_new_with_label(_("RGB (display)"));
    if(module_blend_cst == DEVELOP_BLEND_CS_RGB_DISPLAY)
    {
      markup = g_markup_printf_escaped("<span weight=\"bold\">%s</span>", _("RGB (display)"));
      gtk_label_set_markup(GTK_LABEL(gtk_bin_get_child(GTK_BIN(mi))), markup);
      g_free(markup);
    }
```

So the system is asked to render Roboto Light (or Segoe UI Light, same story) in bold. That font face does not exist of course, but while in Linux the bold font is syntesized (faked) by the backend, in Windows the markup is simply disregarded and normal font is rendered.

So one possible fix would be to modify the darktable-elegant css like follows:

```
*,
#lib-plugin-ui,
#iop-plugin-ui,
#bauhaus-popup,
#modules-tabs,
#left,
#right,
combobox,
combobox *,
togglebutton,
togglebutton *,
notebook,
notebook *,
notebook tab,
notebook tab *,
table,
table *,
row,
row *,
frame,
frame *,
alignment,
entry,
entry *,
dialog,
dialog *,
colorswatch,
colorswatch *,
stack,
stack *,
scrollbar,
scrollbar *,
eventbox,
eventbox *,
scale,
scale *,
button,
button *,
treeview,
treeview *,
separator,
eventbox,
eventbox *,
box,
box *
{
    font-family: "Roboto Light", "Roboto",                  /* best case scenario */
                 "Segoe UI Light", "Segoe UI",              /* Windows 10 default */
                 "SF Pro Display Light", "SF Pro Display",  /* Mac OS X default */
                 "Ubuntu Light", "Ubuntu",                  /* Ubuntu default */
                 "Cantarell",                               /* Gnome default */
                 sans-serif;                                /* default default */
}

menu,
menu *
{
    font-family: "Roboto",                  /* best case scenario */
                 "Segoe UI",              /* Windows 10 default */
                 "SF Pro Display Light", "SF Pro Display",  /* Mac OS X default */
                 "Ubuntu Light", "Ubuntu",                  /* Ubuntu default */
                 "Cantarell",                               /* Gnome default */
                 sans-serif;                                /* default default */
}
```

forcing menu items to use the regular Roboto (or Segoe UI) font. That way the bold font is rendered correclty (and better as it is not syntesized):

![Cattura8](https://user-images.githubusercontent.com/43290988/103482391-f72f0900-4de0-11eb-9d1d-3de88c14ab29.JPG)

It doesn't look bad to me, but @Nilvus do you see a better way ?

**Comment by johnny-bit** [comment]
hmm... silly idea, might be worth it:

try changing `"<span weight=\"bold\">%s</span>"` to `<b>%s</b>` - maybe it's soemething with rendering?

**Comment by Nilvus** [comment]
I agree with @johnny-bit: this is not a good idea. Your change will also change rendering in other OS. On what you change, it's so seems that bold in not applied correctly if Roboto or Segoe Light, in Windows. So, probably something else to change (and maybe not in CSS).

**Comment by Nilvus** [comment]
To precise: bold font use is in Roboto, Roboto light are light (so not bold) fonts. So, it's seems again the way fonts are used with CSS in Windows on Gtk library. So, your solution is more a workaround than a fix. So not the good way. See Roboto font package and how it is: https://fonts.google.com/specimen/Roboto

**Comment by Mark-64** [comment]
@johnny-bit already tried. The font-weight Pango markup is totally ignored when applied to a non regular typeface, i.e it works on Roboto, it does not on Roboto Light. Same for Segoe UI and Segoe UI Light. Tried also specifying weight with a number, no luck.
font-style works instead, for example italic, I guess because Roboto Light Italic does exist as specific typeface, it does not require syntesis.

@Nilvus 
> Your change will also change rendering in other OS

Yeah, but it's a minor change and I guess supporting multiple OS could require some compromises at times, or?
And what about using italic instead of bold for the active menu item? That is rendered correctly

Otherwise the workaround is putting this custom css in preferences
```
menu,
menu *
{
    font-family: "Roboto";
}
```
but it's not nice.
I could open an issue in Pango, but I doubt this will even be considered a bug, rather than a misuse of markup, let alone being fixed.

**Comment by johnny-bit** [comment]
It isn't misuse of pango, that's for sure.

**Comment by Nilvus** [comment]
> Yeah, but it's a minor change and I guess supporting multiple OS could require some compromises at times, or?
> And what about using italic instead of bold for the active menu item? That is rendered correctly
> 
> Otherwise the workaround is putting this custom css in preferences
> 
> ```
> menu,
> menu *
> {
>     font-family: "Roboto";
> }
> ```
> 
> but it's not nice.

Hmm, Windows seems to have many more issues and too many specific ones. Making compromises to deal with issues that are not really darktable issue is not something I like. Sometimes (I have to admit that it is often!), I'm asking myself if porting darktable to Windows was a good idea;

Anyway, said that, Windows is here and we have to deal with it. Your comment make me thinking of something that could be a compromise but I will test it before confirm it that could be ok in Linux. And that would be just put Roboto font instead of light in menu like your last workaround in darktable.css. We make some tests.

**Comment by Nilvus** [comment]
Finally, I'm back to my first answer: a bad idea. That make all menu text not good for me. But, maybe if we can improve how it oculd be set by CSS, I could propose a better choice. So, is actual bold text in blend gui could have a specific CSS tag and even remove hardcoded span bold tag and set bold with CSS? And if yes, is someone could propose the code? I could then improve how to set specifically bold text, without touching other text in menus.

**Comment by Mark-64** [comment]
> I'm asking myself if porting darktable to Windows was a good idea;

Come on, these are small things, you devs are making darktable great and I am proud to be contributing a little. Since 2.6, DT is taking giant steps when coming to Windows GUI; already now it looks super good and it supports HiDPI worderfully, unlike most other FOSS SW (RawTherapee and GIMP for example).
Some small annoyances are unavoidable (by the way, take a look to #6519, I got no answers there), MAC is no less problematic.

In the meantime you test I will open an issue in Pango.

**Comment by Mark-64** [comment]
> So, is actual bold text in blend gui could have a specific CSS tag and even remove hardcoded span bold tag and set bold with CSS? And if yes, is someone could propose the code?

I can try

**Comment by Mark-64** [comment]
done a draft PR, please review it

**Comment by Mark-64** [comment]
Opened [this](https://gitlab.gnome.org/GNOME/pango/-/issues/525) bug report in Pango.
Finger crossed, but I don't hold my breath...

**Comment by Nilvus** [comment]
> Opened [this](https://gitlab.gnome.org/GNOME/pango/-/issues/525) bug report in Pango.
> Finger crossed, but I don't hold my breath...

Good thing and good to check. Anyway, for darktable, your draft PR is ok and solve the issue for us, without breaking anything in Linux (so probably ok too for MacOS).
