### ISSUE TITLE
Overexposed IOP doesn't handle non-matrix histogram profile

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#7660]
**Describe the bug**

The `overexposed` IOP doesn't have handling for non-matrix profiles (i.e. requiring LCMS2 to handle them). This causes false indications (e.g. whole image is shown as clipped) when such a profile is chosen as the histogram profile. `overexposed` calculates pixel luminances silently assuming that the profile is a valid matrix profile, see e.g. https://github.com/darktable-org/darktable/blob/7fa55231b65960884a23721395f9ea03327606db/src/iop/overexposed.c#L321

**To Reproduce**

1. Copy the attached profile to `~/.config/darktable/color/out` (change the `.txt` ending to `.icc`)
2. Open Darktable
3. Open a raw image in darkroom
4. Enable clipping indicator in luminance mode
5. Change histogram profile to the attached profile (`HP E242 ...`)
6. Clipping indicator will change, showing most of the image as clipped (at least for me)

**Expected behavior**

Clipping indicators should remain approximately the same as with another profile.

There could be a couple of other ways to handle this (if it doesn't make sense at all to use a non-matrix profile as the histogram profile):

* If user selects a non-matrix profile as the histogram profile, warn that the clipping indicators won't be shown for certain modes. Don't paint them at all (or even disable the clipping indicator, not allowing to switch it on)
* Remove non-matrix profiles from the histogram profile list

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: master ccc28cf6021444d2cca47cbeb95584f1b8a3d5a7 
 - OS: Arch Linux x86_64 
 - OpenCL: doesn't matter whether enabled 
 - Intel HD Graphics 520, Mesa 20.3.2 

**Additional context**

ICC profile for reproduction: 
[HP E242 #2 2019-09-18 18-43 D6500 2.2 F-S XYZLUT+MTX.zip](https://github.com/darktable-org/darktable/files/5761819/HP.E242.2.2019-09-18.18-43.D6500.2.2.F-S.XYZLUT%2BMTX.zip)

This is a display profile generated by DisplayCal. I don't intend using such a profile as the histogram profile (might be a bad idea) but happened to stumble upon this while debugging another issue. There could be valid use cases for a non-matrix profile as the histogram profile.

**Comment by aurelienpierre** [comment]
LUT profiles are bad, they are of no use for internal working spaces and using LCMS will slow-down the whole process by a lot (we are talking 15 ms for internal path vs. 250 ms for LMCS).

Overexposure is not profile-dependent, it's luminance based, so there is no need for fancy color spaces and their fancy profiles here.

**Comment by flannelhead** [comment]
Yes, I agree about that part. It doesn't make much sense to support LUT profiles in `overexposed`. However it would be good to have an indication about LUT being unsupported if one selects such a profile as the histogram profile and enables overexposed. At present `overexposed` will show some bogus indication in such a situation. Perhaps image pass-through and a control log message would do in this case?
