### ISSUE TITLE
AVIF produces non accurate results

### ISSUE THREAD

**Issue by LuckyBastard73** [darktable-org/darktable#7661]
When using the AVIF export option the resulting images are way to saturated and contrasty.
Im my case I use **_sRGB_** as colorspace (default).
My system is Windows 10 x64 20H2.
Resulting images where displayed in Chrome, Firefox and IrfanView (using the AV1 file extension from Windows).

The same happens when **_avifenc_** is called with:
_avifenc.exe --cicp 2/2/1 **-r full**  in.png out.avif_ (as -r full seems to be default it can be omitted)

The correct result is generated by using:
_avifenc.exe --cicp 2/2/1 **-r limited**  in.png out.avif_

I would suggest to create a parameter in the GUI to select full or limited range.

Results from the same image as JPEG and AVIF: [Google Drive](https://drive.google.com/drive/folders/1LP6qbl68TCIRT0lZW7CuBeubDkvd-NLX)

BTW: GIMP shows the same behaviour

**Comment by kmilos** [comment]
The linked JPEG and AVIF look identical for me (in terms of color and tonal range) on Windows 10 - I tried in both Chrome and paint.NET (I have the AVIF plug-in installed from the store).

Could it be that your problem is on the decoding end (decoder is buggy and doesn't support full range), rather than the encoding?

**Comment by LuckyBastard73** [comment]
You are right that in **_Chrome_** the two images look the same in respect to contrast and saturation.
**_Firefox_** and **_IrfanView_** as well as the old Windows image viewer (that is hidden in the latest Windows 10 updates) show a diffrent result. Windows Paint also show different results.
When I open the AVIF in Darktable it looks completely different (way too bright and washed out).

I tried all settings in the NVIDIA driver: RGB (with 0-255 and 16-235), YCbCr444, YCbCr422

Will make some tests later using a Intel integrated graphics UHD630.
Maybe the differnce results from decoding to a GPU surface in one case and to classic RAM in the other case.

**Comment by kmilos** [comment]
> When I open the AVIF in Darktable it looks completely different (way too bright and washed out).

Try re-selecting sRGB manually as input profile?

**Comment by kmilos** [comment]
So the only dt bug here is that the embedded ICC sRGB input profile is not applied correctly for AVIFs on read, seems gamma is applied twice...

**Comment by LuckyBastard73** [comment]
Maybe you can explain why an image encoded with avifenc with range limited (-r limited) renders correctly in all applications.
I have added samples from a Lightroom development JPEG and PNG that was encoded with avifenc. As you can see from there that
- IrfanView
- Paint
- Firefox
- Chrome
produce the same result.

I am sure that the issue is not just a question of gamma. 
I really like the AVIF format but the acceptance will depend a lot on the preception of "normal" users. 
If they experience a difference the format will not succeed.

**Comment by kmilos** [comment]
> Maybe you can explain why an image encoded with avifenc with range limited (-r limited) renders correctly in all applications.

Perhaps most of them are "broken" (not compliant) and just assume limited color range?

> I have added samples (also on Google Drive) from a Lightroom development JPEG and PNG that was encoded with avifenc.

And if you develop JPEG/PNG with dt and externally encode to AVIF with avifenc -r limited everything is fine, right? So why do you bring up Lightroom?

> I am sure that the issue is not just a question of gamma (histograms differ too much).

I said the only real dt issue here is with input profile being incorrect when trying to load back the AVIF that dt itself exported, not that it explains your 3rd party app difference.

What you're seeing in 3rd party apps is not related to gamma indeed, but [difference in YUV->RGB matrices for full vs limited ranges](http://avisynth.nl/index.php/Color_conversions). I guess quite a few of them didn't bother implementing both options.

> I really like the AVIF format but the acceptance will depend a lot on the preception of "normal" users.
> If they experience a difference the format will not succeed.

Sure. Still not a dt problem per se IMHO.

**Comment by LuckyBastard73** [comment]
So the conclusio as I understand all this is that on the side of Darktable everything is fine when exporting to AVIF.

**Comment by parafin** [comment]
The question maybe is whether limited/full range selection should be exposed as a setting somewhere in darktable. And what should be the default. Limited may be more compatible choice (but I'm sure some app out there assumes full range always, so there's no 100% guarantee), but full makes much more sense given the history of where limited range comes from.

**Comment by kmilos** [comment]
> So the conclusio as I understand all this is that on the side of Darktable everything is fine when exporting to AVIF.

I can do `avifdec IMG_20200916_082626.avif test.jpg` and get the same color and contrast as the directly exported IMG_20200916_082626.jpg even in the old Windows viewer, so I would say the dt export is just fine, the problem is during the decoding elsewhere.

Btw, the JPEG spec also prescribes full range RGB->YUV conversion in order to maximise the utilization of available levels of quantization, so there is no good reason for using anything else for AVIF either.

> Limited may be more compatible choice (but I'm sure some app out there assumes full range always, so there's no 100% guarantee)

This. Let 3rd party apps clean up their act.

I would recommend renaming this issues to the real bug of re-importing AVIF to dt w/ incorrect input profile application.

**Comment by AndrewKeYanzhe** [comment]
Hi @kmilos @parafin could you confirm that darktable still exports AVIF images in full range, as of 2025?

I also support the choice of full range, although it is a bit hard to find documentation on this issue.

**Comment by kmilos** [comment]
The source code is the only relevant reference:

https://github.com/darktable-org/darktable/blob/a21d93ac91f6fc2e79eb3a14877d4b73cf1f87a7/src/imageio/format/avif.c#L390-L404

**Comment by AndrewKeYanzhe** [comment]
Thank you, the link is very helpful and also gave me some information on chroma 444 and 422 sub sampling.
