### ISSUE TITLE
[crash] click on mask group / shape of a deleted module within mask manager crashes DT

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#7673]
**Describe the bug**
Steps to reproduce:
* open a random RAW file (in my case Olympus E-M1 mk2 / Sony A7mk3 files)
* create a new exposure module
* create a new drawn mask with in the newly created exposure module
* delete newly created exposure module
* go to mask manager and click on left-over mask group from deleted exposure module
* booooom, DT crashes

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0 / git master
 - OS: Ubuntu 20.04
 - OpenCL activated
 - Intel Corporation UHD Graphics 620 (on laptop)

**Additional context**
See [gdb backtrace](https://github.com/darktable-org/darktable/files/5764185/darktable_bt_MIYRW0.txt)

Because I'm currently working on an improvement with the mask manager anyway (see https://github.com/darktable-org/darktable/pull/7667), I'll analyse the bug and try to fix it.

**Comment by TurboGit** [comment]
I cannot reproduce this on current master.

**Comment by da-phil** [comment]
@TurboGit can you reproduce it on 3.4.0?

**Comment by da-phil** [comment]
I already found the culprit, a NULL pointer dereference here in line 915:
https://github.com/darktable-org/darktable/blob/3e30462e8450545fc5d137de742e4a4351d897ac/src/libs/masks.c#L914-L915
In my "crash-case" `module->blend_data` is NULL because it refers to a module which has been deleted.

**Comment by TurboGit** [comment]
I'll try, if we need this for 3.4 branch you probably want to have a single commit for this specific fix that I can cherry-picked on the release branch.

**Comment by da-phil** [comment]
I'll try to work on a fix, but I still don't understand all the code and program-flow completely, as I only started studying the code yesterday :sweat_smile: 
So I'll need your or somebody elses guidance regarding the fix.

So what happens if a module gets deleted, shouldn't be the whole pointer to the module be set to NULL, so that the existing check is enough:
https://github.com/darktable-org/darktable/blob/3e30462e8450545fc5d137de742e4a4351d897ac/src/libs/masks.c#L911-L912

As a hotfix, I could just add one more condition to this check to also make sure `module->blend_data` is not NULL.

**Comment by da-phil** [comment]
@TurboGit I created a hotfix here: https://github.com/darktable-org/darktable/pull/7674

I can not reproduce the crash anymore after applying this modification.

**Comment by TurboGit** [comment]
Still cannot reproduce on 3.4.
