### ISSUE TITLE
lighttable flickers with mini-image in preview mode

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#7685]
**Describe the bug**
Moving through images in preview mode results in a very rapid flicker of a tiny  crop of the image, then the full image shows up.

**To Reproduce**
1. Start darktable
2. Import a folder of images
3. Be sure that are in lighttable view in file manager mode
4. Select the first image
5. Press and hold W (or press shift-W)
6. Press right arrow to move through the images
7. A crop of the upcoming image appears, then the full image appears a moment later.

**Expected behavior** (best case)
- If the image is available in the cache at the needed size, it is displayed.
- If the cached image needs to be generated, the highest lower resolution mipmap available will be displayed, scaled to the needed size. The best resolution mipmap will be displayed once it is generated.

**Screenshots**
Here is a screenshot of a "mini" image of a solid green 6000x6000px rectangle (mini image is 46x46 pixels):

![image](https://user-images.githubusercontent.com/2311860/103576274-e47c0900-4ea0-11eb-9efd-c6eeca7757f5.png)

Here is a "mini" image of a raw file of a 4416x2944 photograph (mini-image is 74x46 pixels):

![image](https://user-images.githubusercontent.com/2311860/103577032-0f1a9180-4ea2-11eb-93b2-a5064847a7d8.png)

**Platform (please complete the following information):**
 - Darktable Version: 56a44ff605b86372493cbe738f9536d0ffec1c19 (master)
 - OS: Debian Linux
 - OpenCL: yes
 - Nvidia Quadra P4000, display driver v455.45.01

**Additional context**
- I've tested this with raw files and 6000x6000 pixel PNGs
- The result seems to be approximately the aspect ratio of the source image, but is cropped
- Can reproduce with a clean install
- The problem can go away once the cache is "warm"
- Flicker does not occur when moving between images in lighttable at max zoom
- Regardless of this bug, I've wondered for a while if, when a fallback lower-res image is displayed in lighttable, whether it should be scaled up to the size of the eventual adequate-res mipmap. I believe that currently it is displayed 1:1 which creates flicker.

**Comment by AlicVB** [comment]
>     * Regardless of this bug, I've wondered for a while if, when a fallback lower-res image is displayed in lighttable, whether it should be scaled up to the size of the eventual adequate-res mipmap

That should be the case in current master (not in 3.4) but apparently I've missed some cases ;)
I'll try to reproduce and take care !

**Comment by dtorop** [comment]
> That should be the case in current master (not in 3.4)

That's great! I haven't been following the latest commits, glad it's getting more attention.

> I've missed some cases ;)

Glad so much else has sorted out! The whole lighttable is feeling really solid these days.

**Comment by dtorop** [comment]
@AlicVB I spent a moment looking at this, and continue to be puzzled. Following up on the observation of @xfh in #7696, the 40x40 initial size of the thumbnail seems to be related. For example, if I change:

```diff
modified   src/dtgtk/culling.c
@@ -1135,7 +1135,7 @@ static gboolean _thumbs_recreate_list_at(dt_culling_t *table, const int offset)
     else
     {
       // we create a completly new thumb
-      dt_thumbnail_t *thumb = dt_thumbnail_new(40, 40, nid, nrow, table->overlays, TRUE, table->show_tooltips);
+      dt_thumbnail_t *thumb = dt_thumbnail_new(400, 400, nid, nrow, table->overlays, TRUE, table->show_tooltips);
       thumb->display_focus = table->focus;
       thumb->sel_mode = DT_THUMBNAIL_SEL_MODE_DISABLED;
       double aspect_ratio = sqlite3_column_double(stmt, 2);
```

Then the flickering "mini" thumbnail is correspondingly larger.

If I remove drawing of scaled (`DT_VIEW_SURFACE_SMALLER`) thumbnails, then there is no mini-thumbnail:

```diff
modified   src/dtgtk/thumbnail.c
@@ -566,7 +566,7 @@ static gboolean _event_image_draw(GtkWidget *widget, cairo_t *cr, gpointer user_
     }
   }
 
-  _thumb_draw_image(thumb, cr);
+  if(res == DT_VIEW_SURFACE_OK) _thumb_draw_image(thumb, cr);
 
   return TRUE;
 }
```

I'm curious what the problem turns out to be!

**Comment by dtorop** [comment]
> If I remove drawing of scaled (`DT_VIEW_SURFACE_SMALLER`) thumbnails, then there is no mini-thumbnail

Actually I take back even that note. I think the mini-thumbnail can still appear, perhaps having to do if the image is in the cache.

**Comment by AlicVB** [comment]
I'm on it from yesterday and that's really tricky. Hopefully I can do the PR later in the evening...

**Comment by dtorop** [comment]
That's great... I quite agree about really tricky!

**Comment by AlicVB** [comment]
@dtorop : PR #7719 should fix it... all that for such small change...
