### ISSUE TITLE
Images turn green randomly

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#7686]
**Describe the bug**
Sometimes the image in darkroom view and/or in the small preview in darkroom turn greenish, like all "unwhitebalanced" (see the attached snow covered park and sidewalk). The problem is that this is sporadic, and I haven't been able to systematically reproduce the issue; most often it appears in _crop and rotate_ module.

**To Reproduce**
I'm working in Scene referred and Modern color management.
1. Open an image
2. Click on crop and rotate
3. Make adjustments
4. See the image to turn green (sometimes)
5. The image can turn to correct colors automatically or after re-using crop and rotate or using other modules; also if I return to lighttable and reopen the image it has correct colors even if I had closed it "green".

**Screenshots**
![image](https://user-images.githubusercontent.com/18402158/103576473-deefe480-4edb-11eb-9f82-52db63b97ffc.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+409
 - OS: Win10
 - Same problem both with OpenCL or not (note: didn't restart dt, only disabled in the settings and reopened the image)

**Additional context**
 - Cannot you reproduce with 3.4.0, and didn't notice with 3.5.0+324, but cannot anymore confirm.
 - The problem exists both for fresh edits and re-edits
 - Compiler: gcc.exe (Rev6, Built by MSYS2 project) 10.2.0 with default build options
 - All the exported JPEGs are "green" even if the thumbnail or the last darkroom view was with correct colors

What I could do to pinpoint the problem? Exporting seems to be the only place where the problem is consistent.

**Comment by juhavlintula** [comment]
I have managed to pinpoint the problem to _denoise (profiled)_ when using wavelets.

**To reproduce**
1. Open an image
2. Turn denoise (profiled) on
3. Select wavelets auto
4. Close darkroom
5. Export the image

**Additional information**
Using non-local means auto works normally.

If I turn OpenCL off, and I have the denoise module on the top of my history stack, the image turns green also in the darkroom view. If I have OpenCL enabled, the darkroom image looks normal, but the exported JPG is green.

On Ubuntu 20.10 without OpenCL, the image looks normal in darkroom and is exported correctly.

**Comment by johnny-bit** [comment]
This is very weird... You say it happens ONLY on windows? Can you share sample RAWs + XMP files?

@rawfiner - can you take a look?

**Comment by rawfiner** [comment]
I didn't manage to reproduce yet unfortunately, but I am on linux and I don't have a windows to test

**Comment by juhavlintula** [comment]
You can find the RAW and XMP in [my Google Drive](https://drive.google.com/drive/folders/1Axv7yaSPtdnKEf68VHvISaObA7KqR-cm?usp=sharing).

**Comment by juhavlintula** [comment]
Just speculating, could this be a compiler optimizer issue? How do I tweak the build commands to build with less optimization?

**Comment by rawfiner** [comment]
still cannot reproduce even with the raw and xmp
maybe could be a compiler optimization issue, I don't know at all at this point...

**Comment by TurboGit** [comment]
> If I turn OpenCL off, and I have the denoise module on the top of my history stack, the image turns green also in the darkroom view.

This sounds suspicious! What do you mean by "if on top of my history stack" ? Does that mean that if it is not at the top it works ? History stack on the left of the darkroom ? The position of the module in this module should have zero influence on the rendering of the image as it changes just nothing. So please can you clarify ?

**Comment by juhavlintula** [comment]
Sorry, my bad. I know that the history stack and pixelpipe are two different things. Adding details that are irrelevant, only confuse people.

Without OpenCL when denoise (profiled) is active both the preview image and the main image in darkroom view are green. This didn't change when I randomly deactivated/activated the modules (i.e. changed the place of the denoise (profiled) in history stack).

With OpenCL I did the same thing and the preview was green, but the main image was correct. When I deactivated/activated crop and rotate, the preview was correct and the main image turned green. And after that, when I continued, toggling the modules both turned and remained green.

**Comment by juhavlintula** [comment]
I could try to build a version, where I have disabled the compiler optimizations. How can I do it? Is it enough if I touch `denoiseprofile.c`?

**Comment by johnny-bit** [comment]
@juhavlintula - it seems that the work picked up in #7814. Can you check there and continue there? (Sometimes 2 issues happen and one gets picked and other not, usually it's just luck ;) )

**Comment by juhavlintula** [comment]
No problem. I'm not jealous.

**Comment by johnny-bit** [comment]
Thanks! I just hope the bug will be fixed and part of 3.4.1 for windows :)

**Comment by TurboGit** [comment]
> Thanks! I just hope the bug will be fixed and part of 3.4.1 for windows :)

Maybe I'm confused, but the bug do not affect 3.4.x branch, right?

**Comment by johnny-bit** [comment]
Uhh.. I might've been confused too :/ I thought report said 3.4 not 3.5 (since it's windows) and I assumed that ralfbrown's work (which "caused" problems on windws) was merged pre-3.4 and made it into 3.4 :/
