### ISSUE TITLE
[feature] remember last folder to copy or move to in lighttable selected images module

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#7688]
**Is your feature request related to a problem? Please describe.**
lighttable, module: selected image[s].
When using the `move...` or `copy...` buttons darktable file dialog _always_ starts with the root of the home directory of the current user

**Describe the solution you'd like**
remember the last folder an image has been copied/moved to and start from there

**Alternatives**
add a _recent_ functionality to display the last folders used to copy or move images to

**Comment by johnny-bit** [comment]
If you compile darktable and can test - please test PR #7986 and whether it fixes the issue the way you want :)

**Comment by bilddateien** [comment]
> If you compile darktable and can test - please test PR #7986 and whether it fixes the issue the way you want :)

just tried, but `make` says
```
[ 16%] Built target rawspeed
[ 16%] Building CXX object bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o
~/github/darktable-org/darktable/src/common/exif.cc: In function ‘int dt_exif_xmp_attach_export(int, const char*, void*)’:
~/github/darktable-org/darktable/src/common/exif.cc:4009:29: error: ‘kerTooLargeJpegSegment’ is not a member of ‘Exiv2’
       if(e.code() == Exiv2::kerTooLargeJpegSegment)
                             ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:368: bin/CMakeFiles/lib_darktable.dir/common/exif.cc.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1592: bin/CMakeFiles/lib_darktable.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
```

**Comment by johnny-bit** [comment]
@bilddateien - that problem is duplicate of https://github.com/darktable-org/darktable/issues/7991, already being worked on, don't worry will be fixed soon :)

**Comment by bilddateien** [comment]
ok, thanks - will check then ...

**Comment by bilddateien** [comment]
just built (worked!) and tested (also works as expected with move and copy images)
Thank you!
