### ISSUE TITLE
Color Balance RGB saturation slider producing artifacts in highlights

### ISSUE THREAD

**Issue by pitbuster** [darktable-org/darktable#7689]
Raising the Highlights Saturation slider on the Master tab is producing weird colors on highlights

![image](https://user-images.githubusercontent.com/650365/103584060-a9d59900-4ebf-11eb-9f87-8689648ddce0.png)

Funnily, if Filmic RGB is enabled, the weird colors go away (thanks to the highlights desaturation, I assume).

 - Darktable Version: master with the input matrix multiplication order fix applied
 - OS: Arch Linux

**Comment by aurelienpierre** [comment]
If you have clipped highlights, given that the 3 RGB channels don't clip at the same rate, you get false colors in these regions, and pushing saturation will only make them worse. 

Do you expect some color boost over invalid colors to make those colors better-looking ?

**Comment by pitbuster** [comment]
> If you have clipped highlights, given that the 3 RGB channels don't clip at the same rate, you get false colors in these regions, and pushing saturation will only make them worse.

Ah, that makes sense.

> Do you expect some color boost over invalid colors to make those colors better-looking?
I think I expected that the saturation would be less sensitive in the highlights, but that would probably over-complicate things.


Given that the colors go away and I only noticed because of exporting a TIFF for raster manipulation before doing tonemapping, so I would probably wouldn't retouch those highlights anyway, I will close this.

**Comment by aurelienpierre** [comment]
I just tested on some synthetic HDR image, and there is indeed a problem with the color science, in the white point chromatic adaptation. I need to check the matrices for color conversions.
