### ISSUE TITLE
Cannot remove tag that gets created when you apply a style.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7699]
Current master.

Cannot remove tag that gets created when you apply a style.

I applied a style, did not like it, compressed history to remove it.

Then saw the style in the tag tree for the image, its read only, cannot detach. 

Need the ability to detach any and all tags be it style apply or dt created tags.

**Comment by johnny-bit** [comment]
So best way would be - change tag parent for style tag from `darktable|` to something like `dtstyle|` and problem's gone ;)

**Comment by johnny-bit** [comment]
Done in #7715

As @phweyland said: `darktable|%` tags should stay and be non-detachable by user. They represent things inside darktable and no point in user ever messing with them. However... `darktable|style|%` is kinda special case...
