### ISSUE TITLE
[import options are missing] seems 15a9a4d6 broke it

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7702]
**Describe the bug/issue**
In current master the import options are missing, such like "ignore jpg, import metadata, subdir" etc.

**To Reproduce**

1. Go to lighttable
2. Click on import/folder
3. See error

**Expected behavior**
import options should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/49004103/103694509-5b95c800-4f9b-11eb-8190-36a599599ef1.png)

**Which commit intruduced the error**

```
15a9a4d6e2e7d053443bb77c9dc54cdef68161b7 is the first bad commit
commit 15a9a4d6e2e7d053443bb77c9dc54cdef68161b7
Author: phweyland <philippe.weyland@laposte.net>
Date:   Mon Dec 28 16:37:52 2020 -0300

    import: add set preferences to preset menu + presets

 data/darktableconfig.xml.in    |   8 +-
 src/common/metadata.c          |  12 ++
 src/common/metadata.h          |   3 +
 src/gui/camera_import_dialog.c |  24 ----
 src/gui/preferences.c          | 258 ----------------------------------
 src/gui/preferences.h          |   5 -
 src/gui/preferences_dialogs.h  |   3 +-
 src/libs/import.c              | 308 ++++++++++++++++++++++++++++++-----------
 tools/generate_prefs.xsl       |  12 +-
 9 files changed, 263 insertions(+), 370 deletions(-)
```
@phweyland may I ping you here

**Platform**
* darktable version : 3.5.0+447~g374f7b377
* OS                : Linux - kernel 5.10.2-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-460.27.04
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"

**Additional context**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by ptilopteri** [comment]
no, the options, including ignore jpg, are in the preferences drop-down on the import module.  
moved from the gear-wheel preferences

**Comment by elstoc** [comment]
There were two things, the options in the global preferences dialog and those in the import file chooser dialog. Was it intended to remove both? I would have hoped that the preferences were saved defaults and the import options allowed you to override those defaults on a one-time per-import basis (but I suspect it probably didn't work that way).

**Comment by phweyland** [comment]
> @phweyland may I ping you here

Of course. @ptilopteri has already answered.  

> Was it intended to remove both?

As discussed in #7050, a part of the goal was to remove them from global preferences.


> the import options allowed you to override those defaults on a one-time per-import basis

This did not work like that (that was only a duplication of settings).
I hope you have got better now as you can save different presets in import module.

**Comment by elstoc** [comment]
> I hope you have got better now as you can save different presets in import module.

Given that, as you say, it was actually just a duplication of preferences, I agree it's better this way. I had a hunch it might have been intentional.

**Comment by AxelG-DE** [comment]
Interestingly nobody mentioned #7435

I actually understood #7050 exactly the other way around (bring prefs into module) 

Despite potential technical reasons I do not like the current solution. But maybe that is just me :'(
