### ISSUE TITLE
darktable 3.4.0 crashes when in culling view (ctrl+x) the last remaining image is deselected (ctrl+left click)

### ISSUE THREAD

**Issue by robertoswald** [darktable-org/darktable#7703]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
  -

**Comment by johnny-bit** [comment]
Duplicate of #7445

**Comment by johnny-bit** [comment]
Fixed in #7569 will be in 3.4.1, plz wait patiently :)
