### ISSUE TITLE
documentation: Developer Portal

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#7718]
The other day when we were discussing color usage in the UI we talked about how the UI was supposed to appear. IIRC there used to be a document on redmine.darktable.org in the wiki discussing the UI look and feel along with other docs such as coding standards.

I've noticed that the wiki here is now labeled as the Developer's Portal.  Do those documents need to migrate from the redmine wiki to the github wiki?  And perhaps a little touch up?  I'm also thinking we've had several people that spent a lot of time theming darktable who probably have a real good idea of what the UI should look and feel like.  If we can capture their knowledge, that would be a good thing.

I'm not sure we need another doc site, the github wiki will probably work fine (and if not, the docs are in markdown so it wont be too big an issue to transfer them), but I think we need to capture/migrate the old knowledge before it's lost.

**Comment by johnny-bit** [comment]
IMO? Github wiki should be enough for now to start. dev docs have nasty habit of getting out of date ;)

**Comment by wpferguson** [comment]
@johnny-bit I agree.  I just wanted to make sure we captured anything we wanted from redmine.darktable.org, since it doesn't seem to be accessible from the web anymore.

> dev docs have nasty habit of getting out of date ;)

because on the developer priority list documentation comes after code, test, have a beer, pat yourself on the back.  If you spend too much time doing the last two, then you can't remember what you were going to write and your arm is too sore to do it anyway :)

**Comment by johnny-bit** [comment]
>  I just wanted to make sure we captured anything we wanted from redmine.darktable.org, since it doesn't seem to be accessible from the web anymore.

I'm not sure... I know I ported SOME data, but it was mostly about whitebalance when I done that... It is not impossible that the data isn't captured and data would have to be ported and/or rewritten with spellchecking, copy-editing etc...

(last working snapshot for me in web archive is https://web.archive.org/web/20170623170524/https://redmine.darktable.org/projects/darktable/wiki)

**Comment by wpferguson** [comment]
Thanks for the link.  I looked over the GUI guideline document.  It could do with a little touch up...  :)
