### ISSUE TITLE
[masks] mask group is collapsed upon adding a new element to it

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#7723]
**Describe the bug**
When mask group has been created and opened in the mask manger, adding another drawn mask element from a module leads to collapsing the group, which is unnecessary and annoying when you want to still have an overview of a mask group.
@TurboGit brought this up in https://github.com/darktable-org/darktable/pull/7667#issuecomment-755472127

**Expected behavior**
Mask groups in the mask manager shall not collapse when a new element is added.

I'll have a look at it in the next few days.

**Comment by johnny-bit** [comment]
Hey @da-phil - had you had a time to look into this? Would be great to have it fixed :)

**Comment by da-phil** [comment]
> Hey @da-phil - had you had a time to look into this? Would be great to have it fixed :)

Oh, I didn't notice this annoyance for quite a while,  but indeed would be great to have it fixed.
I'm currently in the middle of a messy move, but in 2-3 weeks I'll have time to look into it.

**Comment by johnny-bit** [comment]
That would be absolutely awesome!

if you don't mind I'll asign you to the issue then and once you finish your move and settle in and have some time to look at it, it'll be waiting for you :)

**Comment by TurboGit** [comment]
I've assigned this to me and will fix before the release.

**Comment by da-phil** [comment]
thanks a lot for taking this one @TurboGit 🙏 
I didn't forget it, but I'm currently so stretched at work, so that the least thing I wanna do is coding all-night-long after work 🤓
