### ISSUE TITLE
Basic adjustments list: color pickers don't work

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7730]
DT git master on Windows 10
When adding sliders with associate color picker to the new basic adjustments list
![immagine](https://user-images.githubusercontent.com/43290988/103888843-acb1d300-50e5-11eb-9a08-392c529bed3a.png)
the color pickers don't work. trying to use one of the wil result in making also the global color picker non functional, even when going back and forth to lightable or even restarting DT. 
Only going to the full module and using the color picker from there unlocks the global color picker

**Comment by AlicVB** [comment]
OK, I know how to fix the global picker problem. I now need to find a way to solve the problems with pickers in basics widgets themselves... Will push a PR once it's ready !
