### ISSUE TITLE
channelmixerrgb freezes darktable when recomputing profile

### ISSUE THREAD

**Issue by flannelhead** [darktable-org/darktable#7732]
**Describe the bug**

Darktable freezes when "recompute the profile" in channelmixerrgb is clicked several times. The preview displays "working..." and the GUI is unresponsive.

**To Reproduce**

1. Open any raw image in darkroom with scene referred workflow defaults and modern chromatic adaptation
2. Open the color checker calibration section of channelmixerrgb
3. Press "recompute the profile" several times (requires probably 10-30 times for me)
4. Darktable freezes

**Expected behavior**

Darktable doesn't freeze.

**Platform (please complete the following information):**
 - Darktable Version: 32dd67ac731a688019e1c80f5b6c33c05a4524fc 
 - OS: Arch Linux x86_64 
 - Both OpenCL activated and deactivated, seems to be a bit easier to reproduce when deactivated 
 - Intel HD Graphics 520, Mesa 20.3.2, Intel Compute Runtime 20.48.18558

**Comment by da-phil** [comment]
I can't reproduce this issue on current master, however I found another weird effect: 
click on "recompute the profile", then on "check the output delta E"  and notice how the histogram changes although there shouldn't have been done any operation on the image (yet). You can click between those buttons in an alternating fashion and everytime the histogram changes shape slightly.

**Comment by aurelienpierre** [comment]
There is no way to trigger a new computation without triggering a new image pipe run, so changes to preview are normal.

**Comment by da-phil** [comment]
> There is no way to trigger a new computation without triggering a new image pipe run, so changes to preview are normal.

Of course the image pipeline runs after a slider change / button press, however my question is: why does the histogram change after clicking on "recompute the profile" or "check the output delta E", because my expectation is that no change is applied to the image (yet). Is my assumption wrong?

**Comment by aurelienpierre** [comment]
> why does the histogram change after clicking on "recompute the profile" or "check the output delta E", because my expectation is that no change is applied to the image (yet) when clicking on those buttons, before applying the color profile. Is my assumption wrong?

The image changes because, in these modes, the module doesn't output an image, so the rest of the pipe gets a black frame in input. But because of caching, and because parameters did not change (so the cache is not invalidated), the image is preserved in GUI but the histogram does God-knows-what.

**Comment by da-phil** [comment]
> but the histogram does God-knows-what.

And that's exactly what surprises me, because the image is preserved :smiley: 
Maybe I'll create a new issue, because it's off-topic for this issue.

**Comment by flannelhead** [comment]
@da-phil : https://github.com/darktable-org/darktable/pull/7908 contains a fix for the histogram shifting issue.

**Comment by da-phil** [comment]
> @da-phil : #7908 contains a fix for the histogram shifting issue.

Awesome, thanks for fixing that too ;)

**Comment by da-phil** [comment]
@flannelhead  but now I'm curious whether you can reproduce this freeze when you click the "recompute" button very often. Was this also a threading issue, which was fixed by your previous PRs?

**Comment by flannelhead** [comment]
@da-phil indeed I can't any longer reproduce this on master. Both https://github.com/darktable-org/darktable/pull/7923 and https://github.com/darktable-org/darktable/pull/7924 were at play here as far as I could debug it. https://github.com/darktable-org/darktable/pull/7924 is going to be replaced by a more elegant solution in https://github.com/darktable-org/darktable/pull/7966 - with that applied on master, this is also not reproducible. Thus closing the issue. :)
