### ISSUE TITLE
basic adjustments GUI: put only one gear wheel per module

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7745]
In the new basic adjustments, when putting more than one slider for a module, there are multiple "go to the full version" gear wheels.

![immagine](https://user-images.githubusercontent.com/43290988/103983966-90b23e00-5186-11eb-9b25-c781078db9e1.png)

I believe they are unnecessary and clutter the GUI for no reason. I would like to see just one, maybe next to the module name.

**Comment by Mark-64** [comment]
just playing with the code, it would be nice to have the gear wheel together with the on/off button

![immagine](https://user-images.githubusercontent.com/43290988/104010890-89525b00-51ad-11eb-844e-1f984aa2ea35.png)

but there might be no on/off button (see the color calibration in the above example) so perhaps together with the module name?

**Comment by johnny-bit** [comment]
Your proposition IMO looks bad. I'd prefer to either have gear icons everywhere or gear icon with 1st control from module and loads of whitespace on righthand side of the module.

**Comment by Mark-64** [comment]
Do you mean like this (just a mockup) ?

![immagine](https://user-images.githubusercontent.com/43290988/104016818-5319d900-51b7-11eb-82fc-96d846f6bad5.png)

My proposal is this
![immagine](https://user-images.githubusercontent.com/43290988/104017046-b4da4300-51b7-11eb-9be4-fd6e767e54ee.png)


IMO this would help to associate the wheel to the whole module and not to the specific slider, but not a big deal

**Comment by Mark-64** [comment]
... and perhaps instead of the gear wheel this tab would deserve a new icon that suggests a link, for example like this

![immagine](https://user-images.githubusercontent.com/43290988/104017865-2bc40b80-51b9-11eb-8c2a-18ccd168770d.png)

**Comment by TurboGit** [comment]
Yes, I'd vote for this last icon !

**Comment by Mark-64** [comment]
If there is a consensus on the proposal I can propose a PR, but would wait for #7739 to be merged first

**Comment by johnny-bit** [comment]
The icon instead of gear - good idea.
layout-wise:
"go to full module" next to on/off button or 1st module slider - bad
"go to full module" in module name header header - good... 
btw - when the header came in? It gives maybe a bit too much white space... meh.

**Comment by TurboGit** [comment]
Yes, a single icon as last proposal from @Mark-64  seems the best.

**Comment by Mark-64** [comment]
This is how it looks like. Do you like it?
Do you prefer the line below the module name to continue also underneath the new link icon?

![immagine](https://user-images.githubusercontent.com/43290988/104042884-51620c80-51db-11eb-9977-416631150eec.png)

**Comment by johnny-bit** [comment]
Works for me either way. The icon line thickness (and overal style) has to match current ones and it'll be fine :)

**Comment by TurboGit** [comment]
Yes, looks fine to me. As @johnny-bit line should match the thickness but I suppose this is just a mock-up ?

**Comment by TurboGit** [comment]
Also the icon seems a bit too high (not centered with the module name). But again if a mock-up not problem, all this will be solved with the actual code.

**Comment by AlicVB** [comment]
Great ! I vote too for larger thickness, but this new icon is definitely better.

Some things to take into account : 
- maybe we should make all the module name line clickable and point to the full module.
- currently, there's an hidden pref : `plugins/darkroom/modulegroups_basics_sections_labels` to show or not the module name label. So either we need to take that in account and in case it's false show the new icon at each line end like now, either we decide to remove that pref completely (I'm not against it)

**Comment by Mark-64** [comment]
This is the actual code, not a mockup. 
Alignments and line thickness are the standard ones, of course I can put some padding and thicken the line, I will try to optimize.

**Comment by TurboGit** [comment]
I would keep the icon and always use it to jump to module. The current module name in darkrroom are only used to unfold/fold the module, better keep consistency to me.

**Comment by TurboGit** [comment]
> This is the actual code, not a mockup.

Oh great !
