### ISSUE TITLE
Crash when no more images in "view" in lighttable.

### ISSUE THREAD

**Issue by cldershem** [darktable-org/darktable#7757]
**Describe the bug**
When darktable has no more images in a selected "view" in lighttable the entire application will crash.

**To Reproduce**
1. Select a film roll
    - in this example the roll has 3 images that are all unstarred
2. Click the "view" dropdown and select "unstarred only"
3. Staring the first and second image work as expected
4. Upon starring the 4th image, darktable will crash.

This can also happen when doing a "narrow down search" in "collect images" if you select a parameter that has nothing for darktable to show (because of the preselected "view" options).

**Expected behavior**
I expect darktable not to crash and to display "there are no images to display in this view with the selected parameters".

**Screenshots**
n/a

**Platform (please complete the following information):**
this is darktable 3.4.0
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

- Dell XPS 13 7390
- Intel(R) UHD Graphics
- Ubuntu 20.04.1 LTS

**Additional context**

If unable to reproduce I can give extra information if you give me instructions on what you need.

**Comment by johnny-bit** [comment]
You haven't posted backtrace, but I think your issue is essentially a duplicate of #7445 and thus fixed by #7569 therefore fixed in master and will be a part of 3.4.1

If the issue matches what's described in PR and connected issues - please close this issue. Or post bactrace so I can judge.

Just a note: beased on your reproduction steps I cant reproduce issue on current master.

**Comment by cldershem** [comment]
@johnny-bit That does sound as if it's likely the same issue. I searched, but didn't think to search closed issues, whoops.

Thank you.
