### ISSUE TITLE
history and copy all in light table with over write enabled does not copy all modules/settings to destination image.

### ISSUE THREAD

**Issue by mheieis** [darktable-org/darktable#7759]
In lighttable, 

history and copy all with over write enabled does not copy all modules or their settings to destination image.

easiest to demonstrate is rotation.

image 1 -> rotate
history->copy all->paste all with over write. 
image 2 -> 
history->paste all

result->image 2 after paste is not rotated.

I've have noticed this occurs as with many other modules as well, where the paste is incomplete.

**Platform (please complete the following information):**
 - Darktable Version: 
version 3.4.0
 - OS: 
Fedora 33 KDE
 - 
opencl is enabled and functioning
 - 
AMD RX480

version is installed from fedora repo.

**Comment by TurboGit** [comment]
See #7761.
