### ISSUE TITLE
filemanager: infinite redraw due to scrollbar toggling

### ISSUE THREAD

**Issue by xfh** [darktable-org/darktable#7760]
**Describe the bug**
There is an edge case of filemanager redrawing when all images fit almost into the current view. The view keeps redrawing all the time, adding and then removing the vertical scrollbar.

**To Reproduce**
1. Open Filemanager with a small collection (or create some duplicates).
2. Resize the darktable window, such that the last row almost fits into the window (tricky part - in my case that happened by chance). one px more or less can make the difference.

**Expected behavior**
The view should stabilise

**Screenshots**
https://user-images.githubusercontent.com/9366771/104052646-4ebae380-51ea-11eb-9d78-e77ed57cd504.mp4

**Platform:**
 - Darktable Version: 3.5.0+450~g9dba5363
 - OS: Gentoo Linux
 - OpenCL does not have an inmpact
 - Intel UHD Graphics 620

**Comment by AlicVB** [comment]
I reproduce and know exactly where it comes from : When we draw the thumbtable we setup scrollbars if needed, which in turn can show or hide scrollbars, which change the thumbtable size, which redraw the thumbtable, which setup scrollbars. So if we are in the case where with the full width (no scrollbars) the thumbtable height if greater than the available space AND with the width minus scrollbar the thumbtable height is lower than available space (no scrollbars needed) we enter infinite loop...

Currently I'm not sure how to fix that cleanly, but at least I know the why ;)
