### ISSUE TITLE
 history and copy all with over write enabled does not copy all modules or their settings to destination image.

### ISSUE THREAD

**Issue by mheieis** [darktable-org/darktable#7761]
**Descriton:**
In lighttable, 

history and copy all with over write enabled does not copy all modules or their settings to destination image.

**How to replicate problem:**

easiest to demonstrate is rotation.

image 1 -> rotate
history->copy all->paste all with over write. 
image 2 -> 
history->paste all

**Expected Result:**

result->image 2 after paste is not rotated.

I've have noticed this occurs as with many other modules as well, where the paste is incomplete.

**Platform (please complete the following information):**
 - Darktable Version:  version 3.4.0
 - OS:  Fedora 33 KDE
 -  yes, opencl is enabled and functioning
 -  AMD RX480

version is installed from fedora repo.

**Comment by johnny-bit** [comment]
This is intended behaviour and it was explained in release notes, due to reports of inverse - sometimes pasting those modules produced VERY bad results.

use copy (or paste) parts to select all modules you want to copy.

**Comment by mheieis** [comment]
Hmm. Are rotate and
          white balance considered not safe modules to copy?
    
    On 2021-01-08 2:33 p.m., Hubert
      Kowalski wrote:
    
    
      
      This is intended behaviour and it was explained in release
        notes, due to reports of inverse - sometimes pasting those
        modules produced VERY bad results.
      use copy (or paste) parts to select all modules you want to
        copy.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/darktable-org/darktable/issues/7761#issuecomment-757031525",
"url": "https://github.com/darktable-org/darktable/issues/7761#issuecomment-757031525",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by johnny-bit** [comment]
Yes.

If you paste white balance on image from different camera (or on jpeg produced by same camera as raw) you'll get VERY nasty result.
Rotation depends on initial rotation of image so pasting it can have unpredictable results (eg my portrait shots are sometimes done holding grip up and sometimes grip down, so if I pasted one from other I could get 180 deg rotation)

**Comment by mheieis** [comment]
images are all from
          the same camera and shot sequence. rotation was reset before
          paste. orientation of destination images are the same degrees.
    
    On 2021-01-08 2:40 p.m., Hubert
      Kowalski wrote:
    
    
      
      Yes.
      If you paste white balance on image from different camera (or
        on jpeg produced by same camera as raw) you'll get VERY nasty
        result.
        Rotation depends on initial rotation of image so pasting it can
        have unpredictable results (eg my portrait shots are sometimes
        done holding grip up and sometimes grip down, so if I pasted one
        from other I could get 180 deg rotation)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/darktable-org/darktable/issues/7761#issuecomment-757033800",
"url": "https://github.com/darktable-org/darktable/issues/7761#issuecomment-757033800",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TurboGit** [comment]
> images are all from the same camera and shot sequence. rotation was reset before paste. orientation of destination images are the same degrees.

Fine, do copy-parts and select them. No big deal. The default is safe and will remain safe in all conditions.

**Comment by mheieis** [comment]
Then why have "copy"
          at all if it's not clear what modules won't be copied or that
          expected settings are not copied?
    
    On 2021-01-08 2:44 p.m., Pascal Obry
      wrote:
    
    
      
      
        images are all from the same camera and shot sequence.
          rotation was reset before paste. orientation of destination
          images are the same degrees.
      
      Fine, do copy-parts and select them. No big deal. The default
        is safe and will remain safe in all conditions.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/darktable-org/darktable/issues/7761#issuecomment-757035117",
"url": "https://github.com/darktable-org/darktable/issues/7761#issuecomment-757035117",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TurboGit** [comment]
Please read the doc.
