### ISSUE TITLE
HDR wrong tone

### ISSUE THREAD

**Issue by dani230** [darktable-org/darktable#7770]
**Describe the bug**

I have three groups of photos (three RAW photos in each group), and the same thing happens when I create the HDR photo (a photo with a green/blue tone).
my camera is a Canon T3

**To Reproduce**
1. Select three RAW photos with different exposure but "acceptable white balance"
2. Click on 'Create HDR'

**Expected behavior**
A photo with a acceptable white balance

**Screenshots**
![Screenshot_20210109_144859](https://user-images.githubusercontent.com/46791184/104107585-554d6780-528b-11eb-8f64-9d5605ea5cee.png)

Output
![Screenshot_20210109_144925](https://user-images.githubusercontent.com/46791184/104107588-5f6f6600-528b-11eb-8c8f-e3b40e4760d2.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS:  Opensuse Tumbleweed
 -  NO
 - 

**Additional context**
 Add any other context about the problem here, for example:
 - Can you reproduce with another Darktable version?     I don't know
 - Can you reproduce with a RAW or Jpeg or both?             RAW
 - Are the steps above reproduce with a fresh edit (removing history)? YES
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? If so which compiler was used, with what options? NO
 - Is the issue still present using an empty/new config-dir

**Comment by johnny-bit** [comment]
This is known downside. merged HDRs don't have original white balance info. You have to copy values from one of the images and then it'll be fine.

**Comment by johnny-bit** [comment]
The issue had been fixed, most likely by #8241

I can't replicate on 3.6 (which is due for public release in ~6 days). If you do manage to reproduce - please comment and I'll reopen for fuller investigation.
