### ISSUE TITLE
failed to open image 133743 from database: no more rows available

### ISSUE THREAD

**Issue by Haribo-66** [darktable-org/darktable#7781]
**Describe the bug**
darktable stops responding and the cmd view / log shows the following error messages:

[image_cache_allocate]   failed to open image 133740 from database: no more rows available
[image_cache_allocate] failed to open   image 133743 from database: no more rows available

only choise is ctrl-c

**To Reproduce**
1. Trying to go to 'any for example any 'tag' related selection loading the full database BUT prior to entereing any tag name'
2. could be any other full database view, prior to entering anything to search for 
2. darktable stops responding
3. See error messages

**Expected behavior**
finish entering collection information to search for

**Screenshots**

![01102021_182544](https://user-images.githubusercontent.com/53818783/104130527-7f795500-5371-11eb-9622-0fbeb97323a2.jpg)

**Platform**
 - Darktable Version: 3.4.0
 - OS: Windows 10
 - OpenCL activated
 - Nvidia GeForce 1050 Ti drive version 461.09

**Additional context**
looking at the images table of my library the screenshot confirms the two missing image IDs, but i do have image IDs going up to > 150.000 !!
No idea regarding the error text '... No more rows available' as it is not true

**Comment by johnny-bit** [comment]
I think it's incorrect cleaning in your DB that causes problems. The images are removed but some things still hold references to them :/

can you check your library and data dbs whether they call those IDs and remove offending rows?

**Comment by HansBull** [comment]
what is the result of  `SELECT imgid from tagged_images WHERE imgid IN (133740, 133743)` ?

**Comment by Haribo-66** [comment]
> If you could do a
> `SELECT imgid from tagged_images WHERE imgid IN (133740, 133743)`
> what is the result ?

the result is nothing or empty!
I found multiple group_IDs having these 2 image ID values?

**Comment by HansBull** [comment]
Please make a copy of your current library.db and then try
`DELETE FROM images WHERE group_id NOT IN (SELECT id from images)`

**Comment by Haribo-66** [comment]
I tried the first one, problem solved!
Thank you HansBull

**Comment by chhil** [comment]
Should this be closed?

There is most likely a problem somewhere that deletes rows without deleting the references.

**Comment by HansBull** [comment]
It's a inconsistency in the database. Might also be problem that a previous version had. Adding foreign keys as in pull 7783 should solve this.

**Comment by chhil** [comment]
3.5.0+662~gace7b26fc

`[image_cache_allocate] failed to open image 15667 from database: no more rows available`

Probably related to https://github.com/darktable-org/darktable/issues/7864
