### ISSUE TITLE
Segfault while playing with exposure module

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#7782]
**Describe the bug**
While playing with the exposure module (exposure slider) DT crashed with a segfault.

Active modules:
* 2 exposure modules
* retouch (cloning out stuff)
* filmic
* sharpen
* lens correction
* haze removal
* color balance
* color calibration
* color zones

Here is the backtrace: [darktable_bt_49LOW0.txt](https://github.com/darktable-org/darktable/files/5793088/darktable_bt_49LOW0.txt)
It looks like a possible threading / race issue.

**To Reproduce**
It's hard, I couldn't reprocude again.
I think I managed to get such a segfault also from other modules, just fiddling around with sliders, it happens if changes to the pixel pipeline happen frequently.
It might be also related to https://github.com/darktable-org/darktable/issues/7732

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+544~gec8829143-dirty 
 - OS: Ubuntu 20.04
 - OpenCL activated: yes

**Comment by flannelhead** [comment]
I noticed this too, and could reproduce it many times by just playing with the exposure slider long enough. Probably it depends on which IOPs there are in the pipeline.

There are a couple of fixes to potential race conditions:
https://github.com/darktable-org/darktable/pull/7923
https://github.com/darktable-org/darktable/pull/7924

With these applied, I haven't been able to reproduce this so far.

**Comment by da-phil** [comment]
> I noticed this too, and could reproduce it many times by just playing with the exposure slider long enough. Probably it depends on which IOPs there are in the pipeline.
> 
> There are a couple of fixes to potential race conditions:
> #7923
> #7924
> 
> With these applied, I haven't been able to reproduce this so far.

This sounds pretty good, I'll try out current master, cherry-pick the changes from your 2nd PR and play around to make it segfault again :+1:

**Comment by Mark-64** [comment]
Does anyone still have this issue?

**Comment by da-phil** [comment]
I didn't do much work in DT lately, but didn't encounter this segfault anymore.

**Comment by da-phil** [comment]
This segfault might have been fixed by either #7923 and/or #7924
