### ISSUE TITLE
Wayland regression in 3.4.0: multi-functional pop-ups opens in top-left corner of the screen

### ISSUE THREAD

**Issue by Aceler** [darktable-org/darktable#7784]
**Describe the bug**

This is a Linux-specific issue.
When pressing right-mouse button on a slider, a multi-functional pop-up (so-called leaf) appears.
Under X11, and under Darktable prior to 3.4.0, it appears on top of the slider.
Under Wayland in Darktable 3.4.0 it always appears in a top-left corner of the screen.

Also, the UI become unresponsive for a short period of time after it disappears.

Maybe it is also affect this bug: https://github.com/darktable-org/darktable/issues/5013

**To Reproduce**

Right-click on any slider.

**Expected behavior**

The leaf should appear on top of the slider. Leaf should disappear on any other click immediately whithout locking the whole UI.

**Screenshots**

![Снимок экрана от 2021-01-10 23-16-55](https://user-images.githubusercontent.com/5177608/104134342-f9bdcf80-5399-11eb-929e-421472b3d38b.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Ubuntu Linux 20.04LTS 
 - Both
 - AMD RX 570, Open Source driver, but also appears on Intel. 

**Additional context**

In Darktable 3.2.1, leaf was shown where it is supposed to be, but UI freezes after that for a short period.

I think these two bugs are connected, but can't be sure.

**Comment by parafin** [comment]
I don't think any darktable developers are using Wayland, and basically its usage together with darktable is discouraged. I'm not saying that Wayland is bad, this is probably a GTK bug here, but without someone volunteering to maintain Wayland support in darktable I don't see things changing any time soon...

**Comment by johnny-bit** [comment]
The bug doesn't manifest itself neither on X server nor on Windows nor OSX. It might be a gtk bug or a wayland bug...

AFAIK the way the "leaf" is displayed haven't changed at all between 3.2.1 and 3.4

**Comment by Aceler** [comment]
As far as I can say, the multi-functional "leaf" is not a standard GTK widget, so there is no hope for GTK devs will fix that also :-)

Wayland have a color calibration protocol since last year, yet I am not sure whether Darktable use it or not.

So, let this bug report stays here until one of the developers decide that wayland is worth looking into?

**Comment by johnny-bit** [comment]
As a fun note then: the code to show popup is same for "leaf" as well as comboboxes and haven't been changed in years (except some tweaks). It uses native `gtk_window_move` and `gtk_widget_set_size_request` so it's worth noting that. Later today I'll try on my laptop on wayland but last time I checked it worked. As I said - it might be either gtk or wayland bug too, so I encourage you to file a bug in gtk and/or wayland :)

**Comment by dtorop** [comment]
I did some work a few years ago on getting widgets to work with Wayland. I believe that I fixed a few of them (#1456, #1472) but never touched the "leaf". I think it's worth doing, not only because Wayland may be "the future", but because really ad hoc implementations of these below the GTK-level will cause trouble outside of Linux desktop.

> As a fun note then: the code to show popup is same for "leaf" as well as comboboxes and haven't been changed in years (except some tweaks). It uses native gtk_window_move and gtk_widget_set_size_request so it's worth noting that.

And further (perhaps off topic from this issue), these popups are invisible if you're screen sharing (at least when tested via Zoom), which can be a problem is some cases (e.g. teaching darktable remotely). Another reason to work within the GUI toolkit.

**Comment by parafin** [comment]
> And further (perhaps off topic from this issue), these popups are invisible if you're screen sharing (at least when tested via Zoom), which can be a problem is some cases (e.g. teaching darktable remotely). Another reason to work within the GUI toolkit.

I suppose you mean when sharing just one window? Sharing the whole screen (or part of it) should just capture what's seen, shouldn't it?

**Comment by dtorop** [comment]
> I suppose you mean when sharing just one window? Sharing the whole screen (or part of it) should just capture what's seen, shouldn't it?

I think that's right. I'll need to test. Regardless, it's not ideal behavior, as the popups have the appearance of being part of the main darktable window, but from the window manager's POV are not...

**Comment by aurelienpierre** [comment]
Wayland not supported, Wayland bad, Wayland for people using only terminal and text editors.

**Comment by Aceler** [comment]
> As a fun note then: the code to show popup is same for "leaf" as well as comboboxes and haven't been changed in years (except some tweaks). It uses native `gtk_window_move` and `gtk_widget_set_size_request` so it's worth noting that. Later today I'll try on my laptop on wayland but last time I checked it worked. As I said - it might be either gtk or wayland bug too, so I encourage you to file a bug in gtk and/or wayland :)

By the way, every time I open up a "leaf", I got this message in a console:

```
Gdk-Message: 12:58:50.274: Window 0x563c56cd8680 is a temporary window without parent, application will not be able to position it on screen.

(darktable:37027): Gdk-WARNING **: 12:58:50.274: Couldn't map as window 0x563c56cd8680 as popup because it doesn't have a parent
```

I am no programmer, but this is looks like simple "forgot to set parent window for pop-up" to me.
