### ISSUE TITLE
[masks] drawn mask, path cannot be removed anymore and also opacity says 0% where it is actually 100%

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#7785]
**Describe the bug/issue**
Current Master:
An applied drawn path cannot be removed anymore with right mouse click. At the same time, the mask opacity in Toas Message says 0% where actually it is 100%

[edit] not only path is affected, also gradient, I assume all...

**To Reproduce**
_Please amend or remove, what is/isn't applicable_
1. Go to Exposure
2. Create a drawn path and 
3. make mask indicator visible
4. Try to adjust opacity by ctrl+scroll and try to remove the mask with right click
5. see error

**Expected behavior**
former behaviour e.g. of 3.4.0

**Screenshots**
![Screenshot_20210110_224349](https://user-images.githubusercontent.com/49004103/104136754-5fa95780-5398-11eb-81ab-6e1624069400.png)

**Which commit intruduced the error**
```
4f8915dc3a73f8211ea16f5f94ce48df2861d71f is the first bad commit
commit 4f8915dc3a73f8211ea16f5f94ce48df2861d71f
Author: Philipp Lutz <philipp.lutz@gmx.de>
Date:   Sun Jan 3 23:44:39 2021 +0100

    [masks/imageio] track module name changes in mask manager
    
    Additionally refactor masks.c to reduce code duplication

 src/develop/imageop.c     |  2 +-
 src/develop/masks.h       |  2 ++
 src/develop/masks/masks.c | 73 +++++++++++++++++++++++++++--------------------
 3 files changed, 45 insertions(+), 32 deletions(-)
```
@da-phil may I ping you here!?

**Platform**
* darktable version : 3.5.0+543~g54e7e09eb
* OS                : Linux - kernel 5.10.2-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-460.27.04
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"     

**Additional context**
 - Can you reproduce with another Darktable version(s)? **bisected, so several versions**
 - Can you reproduce with a RAW or Jpeg or both? **RAW**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**
 - [edit] opencl on/off does not matter
 - (edit] complete empty history stack does not matter

**Comment by johnny-bit** [comment]
@da-phil - PLZ check this report!

**Comment by TurboGit** [comment]
Worth noting that circle, ellipse and brush are not affected.

**Comment by da-phil** [comment]
Ups, will check it out later in the afternoon, sorry guys.

**Comment by AxelG-DE** [comment]
> Worth noting that circle, ellipse and brush are not affected.

Are you saying, you checked circle, ellipse and brush, Pascal? 

I did not check those yet. Too late last night ;) 

Also one more info @da-phil, which I merely communicated on IRC: only first Path is affected, when you draw a 2nd,that one works as expectd

**Comment by TurboGit** [comment]
Yes, I have checked them it they work fine

**Comment by TurboGit** [comment]
And yes only the first shape is affected, first path broken following gradient or path OK.

**Comment by TurboGit** [comment]
But of course I was wrong :) This is because when I tested first the circle, ellipse and path I already had another form!

So to be clear: this happens only for the first form created and for all kind : circle, ellipse, brush, path, gradient.

So that's a regular pattern, probably easier to track down.

**Comment by da-phil** [comment]
I already have an idea what happened, it was rather caused by the code refactoring, not the actual fix in my commit.

On 11 January 2021 13:59:09 CET, Pascal Obry <notifications@github.com> wrote:
>But of course I was wrong :) This is because when I tested first the
>circle, ellipse and path I already had another form!
>
>So to be clear: this happens only for the first form created and for
>all kind : circle, ellipse, brush, path, gradient.
>
>So that's a regular pattern, probably easier to track down.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/darktable-org/darktable/issues/7785#issuecomment-757935712

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da-phil** [comment]
I created a fix here:
https://github.com/darktable-org/darktable/issues/7785

Please have a look.
