### ISSUE TITLE
Culling mode, permanent overlays enabled, does not show overlays.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7786]
Current Master , WSL Ubuntu.

Culling mode,  permanent overlays enabled , does not show overlays.

![image](https://user-images.githubusercontent.com/1119439/104145888-bb063480-53ee-11eb-9d6c-f309569c7e00.png)

**Comment by AlicVB** [comment]
That's ok, you have set permanent overlays for thumbnails (filmstrip or filemanager) (first section)
but you have set block overlays for culling (second section)
