### ISSUE TITLE
Culling view image shows cropped view

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7787]
Current master 3.5.0+543~g54e7e09eb

Culling view image seems to crop few pixels from the edges of the displayed image. Noticeable when one zooms into the image.

Notice the bottom right edge, one foot is visible.
![image](https://user-images.githubusercontent.com/1119439/104146548-26510600-53f1-11eb-83d0-8a2ef3c22172.png)

Zoomed in.
![image](https://user-images.githubusercontent.com/1119439/104146587-3668e580-53f1-11eb-8be1-945d1e35d2ba.png)

**Comment by AlicVB** [comment]
hmmm... I don't reproduce...
Considering, your two screenshots, I would say that the 2 images are not computed from same source (see details and tone). This would explain the crop difference : dt raw development tend to use larger sizes than the camera do. So dt developed raw are often greater in size than embedded jpeg...

This is possible in 2 cases : 
- you have set the "use embedded jpeg" pref to an intermediate size
- you always use embedded jpeg and your camera don't store a full res jpeg inside the raw file (the size of the embedded jpeg depend on camera models)

**Comment by chhil** [comment]
@AlicVB 

> you have set the "use embedded jpeg" pref to an intermediate size
No, its not using embedded jpegs

> you always use embedded jpeg and your camera don't store a full res jpeg inside the raw file (the size of the embedded jpeg depend on camera models)

This I don't know, but its probably not true based on...

I have culling with 6 images displayed at a time. When I reduce this to less than 3 the images is show correctly. So, this leads me to believe that in order to fit images some math is being done on image sizes for redraw leading to pixels being lost.

Culling with 2, alright.
![image](https://user-images.githubusercontent.com/1119439/104257677-fe6eaa80-54a3-11eb-8e6c-bdefe16a3db1.png)

Culling with 3 and onwards, problem starts showing up.
![image](https://user-images.githubusercontent.com/1119439/104257733-19d9b580-54a4-11eb-9bee-6afcc8c2a12e.png)

**Comment by AlicVB** [comment]
I still don't reproduce :(
What I can propose to you for testing to be sure it's not a jpeg vs raw problem : 
1. set pref "thumb use raw file instead of embedded preview" to "always"
2. close dt
3. rename darktable cache folder (so you have a backup)
4. test again your issue...

**Comment by chhil** [comment]
> set pref "thumb use raw file instead of embedded preview" to "always"

It was jpeg earlier and then changed to raw. But as described in another ticket, the preference does not invalidate the cache. 
Setting is currently at "thumb use raw file instead of embedded preview" to "always" while this issue has occurred.

**After performing the test the images appear correct.**

So, the reason I feel this has happened the preference was at jpeg and the cache file got generated (either when DT was running or due to the command line cache file generator that I use often). Cache got a jpeg cached and gets used.
Preference got changed later to use raws.


Now the concern is during zooming in, the image appears non cropped so at some point in time it switches to the raw file based on image size not present in the cache? 

I feel the cache files should smartly get regenerated or inform the user that the cache is outdated and hint at steps to perform to get it back in synch.

My understanding is that the command line cache generator simply skips the files that have already been generated and only generates new cached files for images not present. 
I assume it uses the preference jpeg or raw to create these cache files.
Other than deleting the cache files, how does one update the files for images?

**Comment by chhil** [comment]
In all likelihood this is related to https://github.com/darktable-org/darktable/issues/7788

**Comment by AlicVB** [comment]
perfect... well not really perfect, but we have found the origin of the issue, and indeed it's the same as #7788 
just some infos for the record : 
- the cache is "just" a list of jpeg images, sorted by size, with the name related to the image id. nothing more. It's simple fast, ... but we have no way to know where the cached image comes from (in our case, from the embedded jpeg or from the raw)
- the cached images are created when dt need them, at the size dt need them (in fact we have 8 sizes steps)
- there's currently no way to remove the cache, except from deleting manually the files.
- the cached image is invalidated (removed from disk) when the image change in darkroom. Then dt recreate the cached image when needed

**Comment by chhil** [comment]
@AlicVB 

When I moved the cache I now see collections with strikethrough and skulls.

Should this be the intended behavior when cache gets removed?

![image](https://user-images.githubusercontent.com/1119439/104547831-7a5c2480-5655-11eb-9089-28a91654eeef.png)

**Comment by chhil** [comment]
Please ignore previous comment.

I got thrown off with some images visible and some skulls. 
Root cause was my external drive has got dismounted.
Sorry for the noise.
