### ISSUE TITLE
Culling mode display raw is not being honored and embedded jpeg is being displayed.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7788]
Curren master.

Culling mode/Filemanager

Current master.

Have raw + jpeg for images.

Camera was set to process jpegs using in built monochrome style.

Seeing both raw and jpegs in monochrome, expecting raw to be in color but it seems embedded jpeg is being used to display.

Not sure if the images are treated as thumbnails in file manger or culling mode.

![image](https://user-images.githubusercontent.com/1119439/104148884-1853b300-53fa-11eb-977e-a893b93b43b0.png)

**Comment by chhil** [comment]
There seems to be a refresh issue. After changing the preference to display raws and then changing views or something when I came back to culling it did start showing raws.

**Comment by TurboGit** [comment]
Could be a refresh issue indeed, if you have just changed the preference I suppose we want to invalidate all the current thumbs. @AlicVB, you'll probably have a clear idea about what is going on here.

**Comment by AlicVB** [comment]
indeed, it's a refreshing issue. Currently, we don't invalidate cache on prefs change.
The question is : do we really want it ? that would mean recreating the cache on each pref change... not great, imho, esp. considering the time that can take the "recaching"...
What I would prefer : 
- adding somewhere (in the pref dialog ?) a way to destroy the cache (ideally by size)
- adding a msg if one of the prefs has changed to warn user that this won't affect already created thumbs and he has to destroy the cache explicitly

**Comment by Nilvus** [comment]
> What I would prefer :
> 
>     * adding somewhere (in the pref dialog ?) a way to destroy the cache (ideally by size)
> 
>     * adding a msg if one of the prefs has changed to warn user that this won't affect already created thumbs and he has to destroy the cache explicitly

Or simply a mix: when changing the pref, display a popup to choose between destroy the cache or not (with a clear message of the effects), a popup like we have to confirm some actions like remove an empty folder.

**Comment by chhil** [comment]
The filmstrip also does not honor the showing of embedded raw. 

Though the preference is for lighttable so is filmstrip needs to honor it too.

The red boxes are the raw that should show up in color. The preference has been set and DT been restarted many times so its not a refresh issue.
![image](https://user-images.githubusercontent.com/1119439/104400913-30057580-5579-11eb-9f56-ea74dc54f60d.png)


When I double click a raw, the image in main window is color and the filmstrip image changes to color too. It shows the raw image now.

Also when does DT decide to show B&W in the filmstrips image overlay for raw files?
![image](https://user-images.githubusercontent.com/1119439/104401024-62af6e00-5579-11eb-9547-bda53515119c.png)

**Comment by chhil** [comment]
> do we really want it ? that would mean recreating the cache on each pref change

The preference change is not going to happen often. If it can be triggered on this very particular change that would be great or perhaps have a message to restart DT.

**Comment by AlicVB** [comment]
@chhil : the cached images are not invalidated when restarting dt. they are only invalidated (removed from disk) when dt detect that something has changed on images pixels (some changes in darkroom for example)
