### ISSUE TITLE
Update help links to point to dtdocs user manual

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7792]
As we move from the old format user manual to dtdocs we need to decide how to manage versions between the two repositories and how the help links will need to change going forward.

This will be partly linked to the migration of darktable.org to Hugo and proper integration of the user manual into darktable.org (https://github.com/darktable-org/dtorg/pull/123). Ideally we should be able to version control the user manual in line with darktable itself and link the user to the appropriate version of the manual (https://github.com/darktable-org/dtdocs/issues/76) and will need to consider how the URL structure will work for translations of dtdocs (https://github.com/darktable-org/dtdocs/issues/84)

For now this is just a placeholder for discussion as many of these prerequisites are not yet finalised.

**Comment by TurboGit** [comment]
Sorry missed to reference my commit on this: f34b4bbb9a75ca87893484129a7f1808da68eb9a

Now it remains three missing links to be worked for the 3.6 release:
- censorize
- color balance rgb
- color calibration

**Comment by elstoc** [comment]
censorize and color calibration docs are done in dtdocs master. Color balance rgb is still TBC. I need to brush up on how this works right now and we're still waiting for some key people so that we can move darktable.org to new infrastructure and finalise the location of the documentation. You can see the general URL for translations by looking at the various links [here](https://darktable-org.github.io/dtdocs/) and the languages we've set up [here](https://github.com/darktable-org/dtdocs/blob/master/config.yaml).

Ideally we can set up the last part of the URLs now (from the language part of the URL to the page) and then we've just got one place to set up the base URL once that's decided/in place. Ideally we'll have a different base URL for development and stable as discussed.

**Comment by TurboGit** [comment]
@elstoc : Just to be sure we are on the same ground...

Take censorize as an example, I can use this URL path:

`module-reference/processing-modules/censorize/`

And even if currently it won't be reachable as only in dev version it will be ok as soon as the release is done. That is, the URL path won't change at all.

For the translation we'll re-discus when ready as 3.6 won't use translated documentation for the internal help system.

**Comment by elstoc** [comment]
Regarding censorize yes that should be fine.

If it's possible to detect whether darktable is a dev or a release version, you could change it now so that dev automatically points to https://darktable-org.github.io/dtdocs/ and release points to the darktable.org version (for now). Then you can test help links in master.

**Comment by TurboGit** [comment]
Ok, and I'll do a PR for supporting version number soon.

**Comment by TurboGit** [comment]
@elstoc : I suppose all work for 3.6 is done, we should probably reschedule this for 3.8. Right ?

**Comment by elstoc** [comment]
should be. Just need to update darktable.org

**Comment by TurboGit** [comment]
Noted. Will work on that soon.

**Comment by TurboGit** [comment]
@elstoc : Should I enable back all translation or only some? The question really is if a language is not yet supported/translated would it be redirected to English pages?

**Comment by elstoc** [comment]
That's a good question - @paperdigits might be able to advise about redirects, though when we move dtorg to the new infrastructure we will probably have more control over this at the server level. It's also possible that some of the language strings might differ between darktable and dtdocs so we might need a "translation". See [here](https://github.com/darktable-org/dtdocs/blob/master/config.yaml) for details of the supported languages. 

Right now it looks like German, Spanish and Ukrainian will all be fully translated in time for 3.6.1.

**Comment by elstoc** [comment]
You've probably noticed that the dtdocs urls are now on docs.darktable.org so we'll have to change this again for 3.8 (there are redirects in place for 3.6).

**Comment by TurboGit** [comment]
This is now done, so closing.
