### ISSUE TITLE
Importing a keywords text file with special characters gets wrong

### ISSUE THREAD

**Issue by Jean-PierreCatusse** [darktable-org/darktable#7794]
Hi, 
When importing a keywords text file in LR format without special characters used in French for instance (é, à, ç), result is perfect and hierarchy is fine.
But when the keywords contain a national character, the keyword is not imported properly, with a mouse over you will read a duplicate of previous keyword in list.

Example: importing the following:
Animaux
{tab}canard
{tab}éléphant
{tab}lion
where {tab} is the tab character,
you will get in list moving mouse over:
Animaux
     canard
     canard
     lion
Please note that when renaming you can enter éléphant with national characters and it works. No issue when typing, issue when importing.
 - Darktable Version: 3.5.0
 - OS: Windows10 uptodate

Note: as a new joiner, congratulation to this outstanding software and to all developers.
Thank you.

**Comment by johnny-bit** [comment]
Can you attach sample keywords file with such characters? Prefferably mix of normal and special ones :)

**Comment by phweyland** [comment]
With your files I can reproduce the issue. Thanks. I'll look at it.

**Comment by phweyland** [comment]
Better like that isn't it ?

![image](https://user-images.githubusercontent.com/23012047/104762883-dc935300-5743-11eb-930c-a0846af2d604.png)

I've just converted your file from ansi to utf8 coding.

It should be possible to do the conversion in dt itself ...

**Comment by Jean-PierreCatusse** [comment]
Hi, trying to convert my txt file I sent that contains correct character 'é' to Unicode utf8 on my Windows 10 laptop, 'é' is replaced by this dirty � and for sure when I try to import the txt file with dirty conversion, I got dirty character �.
By the way this import into DT generates duplicate hierarchy Sports, as shown in the attached screenshot. The correct one is on top, the imported at the bottom.
[Keywords-sports-UTF8.txt](https://github.com/darktable-org/darktable/files/5822393/Keywords-sports-UTF8.txt)
![image](https://user-images.githubusercontent.com/77279454/104766138-563e3780-576a-11eb-9057-b4831413cda2.png)
Last, when you say should be possible, please confirm you mean this could be an improvement in future release, as I do not see this feature in 3.4.0?

**Comment by phweyland** [comment]
> Last, when you say should be possible, please confirm you mean this could be an improvement in future release, as I do not see this feature in 3.4.0?

Yes, that's not available for the time being and I only hope I could find the way to do it (=> 3.6).

For the time being, as far as I know, the import tags works well with lightroom tags when the file is utf8 (and not ANSI). Notepad++ can do the conversion for you.

> By the way this import into DT generates duplicate hierarchy Sports

Please solve the coding first. Then we'll see... you know the expression "sheet in sheet out" ? :smiley: 

> Keywords-sports-UTF8.txt

It seems to be UTF-8-BOM, and buggy as you describe.

**Comment by Jean-PierreCatusse** [comment]
Many thanks, it works well now and all explanations are clear.
We all just need to keep in mind that the text file must be coded using UTF8. As most of text editors can't show you the code used (NotePad, WordPas, MS Word...) you can see correct characters even if the code is not UTF8. So using Notepad++, the active code is shown. And if this is not UTF8, convert it into UTF8 using the same menu 'Encoding' then save. File will be ready to go ;) 
Maybe looking at the free code of Notepad++ could be a good step when implementing this code conversion in DT?
Thank you
