### ISSUE TITLE
unexpected GUI behaviour when searching for module while in basics tab

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7797]
DT git master

Normally when starting to search for modules, it will only display the list of modules matching the search string:

![immagine](https://user-images.githubusercontent.com/43290988/104218025-6e494a80-543c-11eb-8ebd-de454e7c104f.png)

However, doing the same thing starting from the basics tab, will produce a different output, the list of matching modules, plus the basics widgets:

![immagine](https://user-images.githubusercontent.com/43290988/104218224-b7999a00-543c-11eb-80da-7d71ff5348b1.png)

I guess this is not the wanted behaviour

**Comment by Mark-64** [comment]
In `/libs/modulegroups.c`

the search box callback...

```
static void _text_entry_changed_callback(GtkEntry *entry, dt_lib_module_t *self)
{
  _lib_modulegroups_update_iop_visibility(self);
}
```

the called function starts hiding the basics tab

```
static void _lib_modulegroups_update_iop_visibility(dt_lib_module_t *self)
{
  dt_lib_modulegroups_t *d = (dt_lib_modulegroups_t *)self->data;

  // we hide eventual basic panel
  if(d->current == DT_MODULEGROUP_BASICS && !d->basics_show) d->current = DT_MODULEGROUP_ACTIVE_PIPE;
  _basics_hide(self);

```
then it perform the search to show the matching modules.
However it ends with

 ```
 // we show eventual basic panel
  if(d->current == DT_MODULEGROUP_BASICS) _basics_show(self);
}
```

so the basics tab is shown again

**Comment by Mark-64** [comment]
replacing the last code in previous comment with 

```
  // we show eventual basic panel
  if(d->current == DT_MODULEGROUP_BASICS && !(text_entered && text_entered[0] != '\0')) _basics_show(self);
}
```
solves the issue.
@AlicVB can I propose a fix ?

**Comment by AlicVB** [comment]
of course you can, that would be great !
