### ISSUE TITLE
Nikon Z 7 II noise profile

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/darktable#7798]
I got the following error with one thumbnail:

_tar: Z72_1867-thumb.jpg: Function ”stat” failed: missing file_

I hope the thumbnail isn't vital.

[darktable-noiseprofile-20210111.tar.gz](https://github.com/darktable-org/darktable/files/5797968/darktable-noiseprofile-20210111.tar.gz)

**Comment by PeterWem** [comment]
I did run one more time and this time only the file 1867.NEF. No problem this time. Below is the noise profile for only ISO 16000.
[1867-darktable-noiseprofile-20210111.tar.gz](https://github.com/darktable-org/darktable/files/5797990/1867-darktable-noiseprofile-20210111.tar.gz)

**Comment by rawfiner** [comment]
Looks nice, thank you!
