### ISSUE TITLE
Noise profiles for Olympus E-M10 Mark IV

### ISSUE THREAD

**Issue by wombalton** [darktable-org/darktable#7799]
Thanks to Peter (https://discuss.pixls.us/t/how-to-create-camera-noise-profiles-for-darktable/7428/12) I got my noise profiles for my Olympus E-M10 Mark IV

I had to modify the `presets.json` slightly to fit the naming of the camera and ditch the bad pictures (PC310114, PC310137, PC310138).

Original photos can be found here:  https://www.dropbox.com/sh/dathd465uerfmp8/AAAiHY3tsDnuxhqpApJgrECka?dl=0

I tested these profiles, they work well for me.
[darktable-noiseprofile-20210109.tar.gz](https://github.com/darktable-org/darktable/files/5798260/darktable-noiseprofile-20210109.tar.gz)

**Comment by wombalton** [comment]
Is someone working on this? I would love to see these noiseprofiles in the official release.
Anything else I can do?

**Comment by pitbuster** [comment]
Hi @wombalton, I opened a pull request with the profile you provided: #8694
