### ISSUE TITLE
Star rating symbols not emphasized enough

### ISSUE THREAD

**Issue by greymont** [darktable-org/darktable#7804]
When rating images the star rating symbols appear differently in different contexts. In most contexts, the selected star symbols have a dark interior and grey outline which makes them appear small when displayed on a grey or white background. They especially appear smaller than the unselected symbols. This is best seen in the attached screenshots.

**Expected behavior**
I would like the selected star symbols in all contexts to be all dark with no outline, similar to the screenshot where I say they appear OK.

**Screenshots**
This screenshot from lighttable view shows selected stars appear smaller than unselected stars next to them. 
![stars looking smaller when set in lighttable](https://user-images.githubusercontent.com/505195/104247620-27585680-5436-11eb-9b7f-b70dede2fb93.PNG)

This screenshot from filmstrip shows ratings for the current image has similar look.
![stars looking smaller when set in filmstrip](https://user-images.githubusercontent.com/505195/104247709-4c4cc980-5436-11eb-969a-a7e36c758e56.PNG)

This screenshot from filmstrip while hovering over a not-current image also shows the problem.
![stars looking smaller when set in filmstrip when hovering](https://user-images.githubusercontent.com/505195/104247877-8c13b100-5436-11eb-892a-42be46e1292d.PNG)

This screenshot of the selected image in lighttable looks OK to me. This is what I think the selected stars should look like in all the above contexts. 
![stars looking OK when set in lighttable if selected](https://user-images.githubusercontent.com/505195/104247969-acdc0680-5436-11eb-9de6-b5bf9c5a9361.PNG)

darktable 3.4 running on Windows 10 with OpenCL on nVidia Quadro K1200 using nVidia driver

Thanks for considering this issue!

**Comment by homer3018** [comment]
I tend to agree here. 
One suggestion would be to have the border always in dark grey, starred star would be filled with dark grey, and unstarred star would be fill with light grey like the background. The last screenshot illustrates this behaviour.
It might be best to do these kind of customization inside the custom CSS rules from the preference window ? Not everybody might agree with us here.
What do you guys think ?

**Comment by elstoc** [comment]
@Nilvus what's your opinion on this one?

**Comment by parafin** [comment]
Light border doesn't serve its purpose here - border should have a contrast with background, not disappear in it...

Another thought - why display inactive stars at all when not hovering over the image? I think if image is rated 3 stars, then 3 stars should only be rendered, unless you are trying to change the value (meaning hovering over the image), then additional 2 deselected stars should appear. Just implementing this will already mostly solve this bug.

**Comment by AlicVB** [comment]
Although I think that this can be enhanced, we have to keep in mind that using contrast between borders and background ensure that the stars will stay readable on every background (you can set the star to be shown on top of the image)
@parafin : I quite like your idea, "empty" stars could be hidden or at least with a small opacity if the mouse doesn't hover the image...

**Comment by Nilvus** [comment]
Thanks all for your feedback. I've asked @greymont to post this issue after his email on darktable dev list to better discussed that. Indeed, stars effect could be improved. I like your ideas but it's better to test that and see what's good and not. Maybe border could be removed but by being sure stars remains readable in all background as @AlicVB says.

And I like your idea @parafin to not display inactive stars in some state. But to test to be sure it will not disturb in any way rate images. Will make some tests in the week and propose a PR to test/discuss.

**Comment by homer3018** [comment]
I also like very much the idea of hiding the additional stars not used and maybe only display them on hover.
As @Nilvus mentioned this is the kind of thing that is better grasped once tested, just to see if it works or not.
Thanks :)

**Comment by Nilvus** [comment]
I just tested @parafin idea and I'm not sure finally if it is a good idea. When removing border in inactive stars, it's ok for me when we have at least one star rated in image but not good if there's no image at all. We have some overlays options with stars not shown at all and for a new user or something who never rate any image, that could be disturbing. Anyway, I will think and search if something a little more discrete than actually could be a good compromise.

See screenshots of first tries (and see active ones without border now. Flat style and indeed better for me too):

![2021-01-15_20-11](https://user-images.githubusercontent.com/45535283/104768699-5dffdb00-576e-11eb-8358-46d3fdd19902.png)

**Comment by Nilvus** [comment]
For inactive stars, I so suggest just more discrete ones. Something like this:

![2021-01-15_20-17](https://user-images.githubusercontent.com/45535283/104768965-cea6f780-576e-11eb-928c-e348d1e7aafd.png)

Or this one:

![2021-01-15_20-17_1](https://user-images.githubusercontent.com/45535283/104768981-d8305f80-576e-11eb-82b2-a87cc3826ec4.png)

**Comment by Nilvus** [comment]
It could be between those. If you want to test, just put that css code in preferences:
```

#thumb_star
{
  color: shade(@thumbnail_font_color, 1.6);
}
```
This code is for 2nd previous screenshot. 1st one is with 1.8 instead of 1.6. 1.7 could also be good and so between those 2 screenshots.

What's your view on that? Do I let hover and selected state are they are actually in master or do you see something to change too on those states?

**Comment by TurboGit** [comment]
I would vote for the last proposal as the inactive stars are barely visible on the previous.

**Comment by TurboGit** [comment]
And yes I agree that no star at all remove the "hint" that there is something to select/change at this location.

**Comment by greymont** [comment]
Thank you, guys! This is a big improvement.



BTW, it also inspires me to help the project out. I will probably start with documentation improvements.



Doug C.





---- On Fri, 15 Jan 2021 14:48:49 -0500 Nicolas Auffray <notifications@github.com> wrote ----

      I would vote for the last proposal as the inactive stars are barely visible on the previous.

That's my choice. To https://github.com/ALL, I've finally also make font color a little more lighter (so, that update to 1.4 instead of 1.6, with thumbnail_font_color in define lines update to 0.05. All is better. I've also updated hover effect and I'm on something which should be much better. Will propose tonight a draft PR to test. Stay tuned guys!

**Comment by Nilvus** [comment]
> Thank you, guys! This is a big improvement. BTW, it also inspires me to help the project out. I will probably start with documentation improvements. Doug C.

All help is much appreciated, and documentation needs work. There's a big recent projet for this there: https://github.com/darktable-org/dtdocs ; and same for lua doc: https://github.com/darktable-org/luadocs

**Comment by Nilvus** [comment]
To @ALL, see PR (to test): #7869
