### ISSUE TITLE
Saturation in Basic adjustment disabled when color balance module has multiple instances.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7808]
When one has multiple color balance modules, basic adjustment tab disables saturation.

It would be good to mimic key board shortcut functionality that would impact the appropriate module instance.

![image](https://user-images.githubusercontent.com/1119439/104274068-07707380-54c6-11eb-833c-9e8d17520e25.png)

**Comment by elstoc** [comment]
I think this is a designed limitation of the basic adjustments module, since it's supposed to be for basic use only - if you're doing more advanced stuff like multi-instance you should use those instances instead. @AlicVB can you confirm?

**Comment by AlicVB** [comment]
Yes exactly, basics widgets should stay... basic. So all advanced features (masks, multi-instances, on canvas changes...) are excluded by design... You should use the "full" modules for this cases. The tooltip is updated for this case to explain why the widget is disabled.
