### ISSUE TITLE
Display active modules shows disabled modules.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7809]
Current Master

I have display active modules only.

Now if I disable modules from this list, these should no longer be visible in the list. (denoise and rgb curve are still visible in the image).

![image](https://user-images.githubusercontent.com/1119439/104289894-ac4b7a80-54df-11eb-9ba5-f8ff96062476.png)

**Comment by elstoc** [comment]
This is how it's designed to work, to allow you to temporarily disable a module without having to hunt through the interface to re-enable it. If you click away from the active modules group and then back again, it will disappear.
