### ISSUE TITLE
Custom sort needs a dynamic title- Lighttable

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#7821]
**Is your feature request related to a problem? Please describe.**

The filter option **custom sort** in lighttable is very handy and variable. But its generic name is meaningless

**Describe the solution you'd like**

If i go to "collect images", (Left hand column in Lighttable) and choose e.g. history, i want to see "history" replace the generic "custom sort" title for the "sort by" option. I do not know if Dt is able to change dynamically popup menu entries, but this is my request.
This change would clarify what kind of sort filter is effectively active and connects logically and visually with the "collect images" dock menu. I had to check online to find out how to configure "custom sort" to my liking

**Alternatives**

**Additional context**

**Comment by phweyland** [comment]
I don't really understand the request.

"custom sort" means you can drag and drop visible images to set your proper order.
If you change the collection the visible images (and their specific order) may have disappear, none sorted images got appeared...

The "custom sort" is useful for your work in progress collection. If you change the collection it may not be meaningful anymore.

The only collection which remembers the selected order (including the custom one) is the tag at first level of collect. For each tag you can define a specific order. This order is saved and given back when you select again this tag.

Does that answer any of your doubts / requirements ?

**Comment by johnny-bit** [comment]
Custom sort (or sorting modes to that) seems to not have description in dtdocs... could be interesting addtionion

Consider filling a request with https://github.com/darktable-org/dtdocs :)

As Philipe said - custom sort is custom sort, not some other thing so no reason for it to have "dynamic name" :)

**Comment by johans3** [comment]
phweyland, you did not understand me. 
"Custom sort" sorts image based on the criteria you set in the menu "collect images". IF my criteria is defined by the criteria "history" from "collect images" then the "Custom sort" is no more generic, but sorted by history. I do not bother to move pictures manually

**Comment by parafin** [comment]
That’s not what custom sort is about, just maybe some strange artifact of implementation. As already said custom sort is custom sort, rearranged by user.

**Comment by johans3** [comment]
with the overabundance of pictures nowadays sorting by hand is like cleaning a swimming pool with a tooth-brush. Sorry for the joke, but custom sort is more sophisticated and i am glad that DT offers this smart confort

**Comment by phweyland** [comment]
> phweyland, you did not understand me.

I still does not understand ... :(
