### ISSUE TITLE
Where should lua css be saved?

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#7823]
lua widgets now have names so they can be styled with CSS.  The question is where do we put the CSS?  Since the user CSS overrides go into configdir/user.css I'm thinking that the lua script generated css could go into configdir/lua.css.  This way we keep it separate from the themes, and we don't clutter up the user CSS overrides.

The other question is should it be persistent or not?

Thoughts?

**Comment by Nilvus** [comment]
Do we really need that? If they can be styled with CSS, this could be added in actual css editor, so in user.css. This is done for that: that each user could customize as he wants the UI.
