### ISSUE TITLE
DT 3.4.0: No exif or iptc metadata available in jpg created from raw using dt 3.4.0

### ISSUE THREAD

**Issue by rainer042** [darktable-org/darktable#7828]
**Describe the bug**
I  created a fresh jpg from a Nikon D750 Raw file using darktable 3.4.  Using exiftool as well as exiv2 I discovered that much of the metadata contained in the raw .nef file was not available in the jpg. Esspecially this is true for basis exif information that is missing completely in the generated jpg. There is for example no lens information in the generated file:

$ exiv2 -p a dsc_3519.nef
Exif.Image.NewSubfileType                    Long        1  Thumbnail/Preview image
Exif.Image.ImageWidth                        Long        1  160
Exif.Image.ImageLength                       Long        1  120
Exif.Image.BitsPerSample                     Short       3  8 8 8
Exif.Image.Compression                       Short       1  Uncompressed
Exif.Image.PhotometricInterpretation         Short       1  RGB
Exif.Image.Make                              Ascii      18  NIKON CORPORATION
Exif.Image.Model                             Ascii      11  NIKON D750
...
...
$ exiv2 -p a dsc_3519.nef | wc -l
213

$ exiv2 -p a dsc_3519_0.jpg        # only xmp tags are printed no exif ones
Xmp.exif.DateTimeOriginal                    XmpText    19  2020:08:17 19:53:46
Xmp.xmp.CreateDate                           XmpText    22  2020-08-17T19:53:46.61
Xmp.xmp.CreatorTool                          XmpText    24  NIKON D750 Ver.1.13     
Xmp.xmp.Rating                               XmpText     1  0
Xmp.xmpMM.DerivedFrom                        XmpText    12  dsc_3519.nef

$ exiv2 -p a dsc_3519.jpg | wc -l
5

In Lighttable I can however see metadata for  eg. Camera and Lens and many more. So darktable is able to decode the metadata of the raw image but seems to be unable to write them into the jpg it creates.

**To Reproduce**
Easiest way: Create a jpg from a raw and compare the amount of metadata that is contained in the raw and in the generated jpg, simply by counting the lines of metadata output of exiv2 -pa <name>. 

**Expected behavior**
All important metadata contained in the raw file should be also contained in the jpg. IPTC metadata configured in DTs metadataeditor (like Author) should also be contained in the jpg but are not.

**Platform (please complete the following information):**
 - Darktable Version:3.4
 - OS:  openSuSE Leap 15.2
 - OpenCL activated: yes
 -  GeForce GTX 1060 6GB
 -  nvidia-gfxG05-kmp-default-460.32.03_k5.3.18_lp152.19-lp152.33.1.x86_64, ..

Thanks
Rainer

**Comment by parafin** [comment]
https://www.darktable.org/usermanual/en/module-reference/utility-modules/lighttable/export-selected/#including-metadata-in-the-exported-image

**Comment by rainer042** [comment]
Thanks for the hint. This really was the "bug". I always seem to have overlooked this settings button. I tried to find something in the global settings, but without success, I now know why :-)  
I do not know if it is the default to deactivate all tags as it was the case for me. Since I did not deactivate all tags manually I guess that this is the default. If so then perhaps it would make sense to change the default because I guess most folks do want to have tags in their photos. 

Thanks
Rainer

**Comment by parafin** [comment]
Yeah, let's hear someone who knows what the defaults should be and why it was chosen like that.

**Comment by rainer042** [comment]
I could observe by photos processed with darktable of the last year that this effect (no exif in jpg) started for me  in October 2020, before all metadata were available afterwards they were no longer available. So probably with version 3.2.1 that was available in August 2020 someone was heard, who knew what the defaults should be ....

**Comment by phweyland** [comment]
The default settings are these ones:
![image](https://user-images.githubusercontent.com/23012047/104631942-bc985c80-567b-11eb-988c-a23fef9b1105.png)

**Comment by parafin** [comment]
So maybe some of the upgrade paths causes different defaults?..
I'm not sure if there's a bug.

**Comment by phweyland** [comment]
> So maybe some of the upgrade paths causes different defaults?..
> I'm not sure if there's a bug.

If the user has not changed anything in its darktablerc file, yes, there was probably a glitch in the upgrade path.
Difficult to know when and where...

> this effect (no exif in jpg) started for me in October 2020

What are the version steps you could have run at this time ?

**Comment by rainer042** [comment]
> > So maybe some of the upgrade paths causes different defaults?..
> > I'm not sure if there's a bug.
> 
> If the user has not changed anything in its darktablerc file, yes, there was probably a glitch in the upgrade path.
> Difficult to know when and where...
> 
> > this effect (no exif in jpg) started for me in October 2020
> 
> What are the version steps you could have run at this time ?

Thanks for investigating this issue. "No exif " is according to what you showed above not a new default  for darktable. This could have explained my jpgs without exif data. But since exporting exif and other metadata is the default , I also think that some minor issue has caused the problem for me. Else I would expect more people to report a similar problem. 

The version I was running in October was 3.2.1 which I could lookup in system-backups where the oldest are from October 2020. However I cannot say which version I was using before. So perhaps the problem started in the upgrade from  vers < 3.2.1  to  3.2.1.

Since the solution was very simple (simply activate the settings), I only had to re-export the raw files in question and the problem is solved now. So if there are no other people with a similar problem description its not worth while to try to find out why and how exactly this happend. 

Thanks a lot Rainer
