### ISSUE TITLE
Translation issue in new parameters of import module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#7848]
**Describe the bug**

I've updated pot an fr.po file to update translation but I don't have lines to translate new parameters in import module. I have been able to only translate parameters expander line (that is included) but some lines seems to not be available to translation.

See screenshot below to which lines can't be translated (they remain in english as other lines are in french).

![2021-01-14_21-55](https://user-images.githubusercontent.com/45535283/104648558-97bfdb80-56b3-11eb-99cc-bd70b2c8b4dd.png)

@phweyland and @TurboGit: you probably will quickly find the issue!

Issue on last master of course!

**Comment by phweyland** [comment]
As the context has changed (preferences => module itself), texts have been redefined. Translation needs to be updated.

**Comment by Nilvus** [comment]
> As the context has changed (preferences => module itself), texts have been redefined. Translation needs to be updated.

That's not the issue. I have updated translation (pot and fr file as I said). But @TurboGit says in Matrix/Elements (french chat) that he is tracking it and seems to not be easy to fix.

**Comment by phweyland** [comment]
> (pot and fr file as I said)

Ooops. Sorry, I've jumped to quickly to the end ... :/

**Comment by TurboGit** [comment]
@phweyland : I'm on it, not easy but the solution is coming.

**Comment by phweyland** [comment]
> I'm on it, not easy but the solution is coming.

Please tell if I can help...

**Comment by phweyland** [comment]
BTW, when I was testing, before changing the labels, I've noticed the first text, and only this one, was not properly translated in French. Some html like text was displayed instead...
