### ISSUE TITLE
Collect images module can only fit and show one collection label.

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/darktable#7853]
Collect images module in light table doesn't have enough vertical space. It can only fit one collection label in that space. That vertical space should be expanded like it is on the 3.4.0

![darktable_bug](https://user-images.githubusercontent.com/10299892/104651362-d3f53b00-56b7-11eb-9b36-027b2b2618bf.png)

DT version: 3.5.0
OS: Ubuntu 20.04

**Comment by parafin** [comment]
Ctrl+scroll will enlarge it.
Judging by amount of reports like that I suspect there is some issue with config migration/defaults, I doubt that people do Ctrl-scroll by accident...

**Comment by KristijanZic** [comment]
Yeah, it an upgrade but not on 3.4.0. This issue came up on the master branch. Your suggestion fixes it for me but I guess the default spacing should be fixed before it hits stable because then everybody will be affected.
