### ISSUE TITLE
Problem importing and removing an image 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7856]
Current master 3.5.0+650~g05a925f70
I have a file, which was previously imported and displaying fine.

Now it was showing a skull. So I imported the file again got an error toast "unknown format".

Then I tried removing  it , but could not.

![CannotRemove](https://user-images.githubusercontent.com/1119439/104682866-bc4f9e00-571b-11eb-91b1-f22dd2dcfdd3.gif)

This was what got printed on the terminal.

```
(darktable:16590): GLib-GObject-WARNING **: 10:05:43.881: invalid unclassed pointer in cast to 'GtkDarktableExpander'

** (darktable:16590): CRITICAL **: 10:05:43.881: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed
[temperature] failed to read camera white balance information from `P1115024.RW2'!
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[temperature] failed to read camera white balance information from `P1115024.RW2'!
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[temperature] failed to read camera white balance information from `P1115024.RW2'!
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[xmp_import] creating tag: 111_PANA\P1115008.MP4
```
Additionally I am not even sure what "[xmp_import] creating tag: 111_PANA\P1115008.MP4" is doing in there. The file exists in the folder.
Then I tried importing it again, this time it imported with a toast message : failed to read camera white balance information. But it got imported.

Something weird is happening. Images should not have a skull, they are present.

**Comment by johnny-bit** [comment]
Just to make sure - is this related to your issue from other bug report where the permissions for files were essentially nothhing and you had to recursively apply 777 permissions (btw, don't ever do that, non-executable files should have at most 666)

**Comment by chhil** [comment]
Yes its related to the other one. I saw what permissions the other files had and changed it to that. Remember I am on a window machine running WSL ubuntu.

**Comment by johnny-bit** [comment]
I couldn't reproduce the issue on neither 3.4, nor 3.6 nor 3.7... The only thing that comes to mind is that permission issues. But wsl is really weird. Either try native windows builds or go native linux. emulation layers add another layer of complexity :/
