### ISSUE TITLE
How to get rid of stacking of `removed images` messages in lighttable when they removal of images or collections take long or fail ?

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7857]
Current master 3.5.0+650~g05a925f70

How to get rid of `removed images`  messages in lighttable?
The list keeps growing and makes the collect images smaller and smaller :)

[EDIT]
It appears that some removals can take time or even fail causing the removals to stack up and make light table unresponsive. 
There are entries in the terminal when "removed images" start stacking up....
```
[image_cache_allocate] failed to open image 15667 from database: no more rows available
[image_cache_allocate] failed to open image 8694 from database: no more rows available
```
![image](https://user-images.githubusercontent.com/1119439/104684049-2c5f2380-571e-11eb-9615-b38fa6db7101.png)

Workaround: Restarting DT

**Comment by johnny-bit** [comment]
@wpferguson I think this one is for you ;)

seems like a lua thing.

**Comment by chhil** [comment]
I was removing images using the delete key and removing collections by right click and remove.

**Comment by wpferguson** [comment]
@johnny-bit my first thought was how did someone write into the module.  My next thought is that these are jobs created when @chhil starts removing images and they either didn't finish, or the job didn't clean up after itself.  I think if scripts_installer gets minimized, the removing images wii still be there.  I'll see if I can recreate

**Comment by wpferguson** [comment]
I can't recreate.  When I select and image and click the delete button, I get the message and the confirmation dialog.  I click Yes to remove the image from the collection and the message goes away.  Just tried the right click to remove a collection and that worked fine also.  I used 3.5.0+651~gc8b74d4e7 to test with.

**Comment by chhil** [comment]
If it helps, all the collections I removed had a lot of images in them. These collections had a strikethrough across them as the folder was no longer on the hard drive.

**Comment by chhil** [comment]
![Remove Images](https://user-images.githubusercontent.com/1119439/104796311-267b4800-57db-11eb-8de6-d2b3d1a6fc73.gif)


During the remove process, at some point the images in the main window show up with "working..." probably means its stuck somewhere. Now when I double click any collection, all images show up as working. I double click any of the working images, it opens up in darkroom correctly.

**Comment by chhil** [comment]
Everytime the "removed image" is stuck , there is an entry in the terminal

```
[image_cache_allocate] failed to open image 15667 from database: no more rows available
[image_cache_allocate] failed to open image 8694 from database: no more rows available
```
Basically it could not delete an image due to inconsistency in the db.  The db has not been manipulated manually for images to lose references.

Current install was clean, no db existed. Imported recursively 20K + images. Now removing the jpegs from the exported folder.

I think the db state probably gets screwed up when DT hangs or misbehaves and `ctrl+c` is used in the terminal to kill it.

**Comment by wpferguson** [comment]
Looking at the code, for every image that you try to remove from the database, darktable checks to make sure it is safe to do so by checking the disk for the image and the xmp file.  If you are trying to delete lots of images that don't exist on disk then the database may simply get overwhelmed by the sheer amount of requests and the fact that it is IO bound checking the disk for non-existent files.  I would recommend letting one job finish before starting another.  There is also a script in /usr/share/darktable/tools called purge_non_existing_images.sh to clean out non-existent images from the database.

**Comment by chhil** [comment]
That was the initial case, the second case (where screencast was attached) was with all images existed but then there were issues with references in the DB as far as I can tell.

I can surely remember to follow the recommendations but from a general user perspective I think it's a big ask and the software needs to handle it better. It probably gets worse when you see the app no behaving and kill it and probably leaving it in a worse state.

**Comment by chhil** [comment]
Just an FYI 
To use purge shell scripts...
Had to install sqlite3 for my ubuntu 20.04

Shell scripts are located in my DT install location ...
`/opt/darktable/share/darktable/tools/`

**Comment by wpferguson** [comment]
> I can surely remember to follow the recommendations but from a general user perspective I think it's a big ask and the software needs to handle it better.

Do you want to close this issue, and open another about removing images taking a long time, or appearing non-responsive, or some other wording that describes the issue more clearly?  Or perhaps limiting the user to 1 remove job at a time so they don't overwhelm the system or the database?

**Comment by chhil** [comment]
I have updated this ticket itself with more information.
