### ISSUE TITLE
File import dialog freeze issue

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7858]
Current master  3.5.0+648~ga52059e5c

I regularly am getting this in generate cache.
```
...
...
image 13085/18264 (71.64%) (id:13305)
image 13086/18264 (71.65%) (id:13306)
image 13087/18264 (71.65%) (id:13307)
[rawspeed] (P1115027.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2".
[temperature] failed to read camera white balance information from `P1115027.RW2'!
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[exiv2 dt_exif_get_thumbnail] /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2: /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2: Failed to open the data source: Permission denied (errno = 13)
image 13088/18264 (71.66%) (id:13308)
^C
```

Then I go into DT find the image and double click it... and it remains in working.... (probably can't genertae cache file due to a failure message for whitebalance.
![image](https://user-images.githubusercontent.com/1119439/104703787-c4203a00-573d-11eb-8bc5-60eb4fcdd300.png)

I try to reimport image
![image](https://user-images.githubusercontent.com/1119439/104704025-20835980-573e-11eb-81c0-d181f0def26a.png)

It freezes on the screen above.

Terminal has

```
[rawspeed] (P1115027.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2".
[temperature] failed to read camera white balance information from `P1115027.RW2'!
[exiv2 dt_exif_get_thumbnail] /mnt/f/Temp/delete/Lumix/Kumbharwada/P1177006.RW2: /mnt/f/Temp/delete/Lumix/Kumbharwada/P1177006.RW2: Failed to open the data source: Permission denied (errno = 13)
[exiv2 dt_exif_get_thumbnail] /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2: /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2: Failed to open the data source: Permission denied (errno = 13)
```
The file very much exists and I can ls to it and see it in the import dialog of dt
I have to kill dt.

Now I cannot use the import dialog as it appears frozen and opens to the place, I last opened it.

There is a file highligthed , I can clcik another file but the highlight doesn't move.
If I open another window on top of dt and remove it, the file that I had clicked gets highlighted but its still frozen.
Currently I can no longer import images.

I can cancel out of the import dialog and use other dt functionality.

**Comment by parafin** [comment]
Please show the output of the following commands:
```
ls -l /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2
dd if=/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2 of=/dev/null
```

**Comment by chhil** [comment]
```
mchhil@DESKTOP-MKCA8HN:~/.config/darktable$ ls -l /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2
---------- 1 mchhil mchhil 24273920 Aug 25  2019 /mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2

```
Do the permissions look ok?

```
mchhil@DESKTOP-MKCA8HN:~/.config/darktable$ dd if=/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115027.RW2 of=/dev/null
47410+0 records in
47410+0 records out
24273920 bytes (24 MB, 23 MiB) copied, 0.591678 s, 41.0 MB/s
```

**Comment by parafin** [comment]
No, they do not, there are no permissions on this file. Though dd works, so it's interesting. What FS is that? Please show the output of `mount|grep /mnt/f` command.

**Comment by chhil** [comment]
I am on WSL1, Ubuntu
```
mchhil@DESKTOP-MKCA8HN:/mnt/c/Users/chill$ mount|grep /mnt/f
F:\ on /mnt/f type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
```

I changed did a chmod 777 for the files and generate cache continues fine, but the freeze problem persists.

**Comment by chhil** [comment]
Freeze screencapture.
I did a recursive chmod 777 for my images folder to make sure that wasn't the problem.


![Freeze](https://user-images.githubusercontent.com/1119439/104708622-f59c0400-5743-11eb-8244-aeffcb13bd4a.gif)

**Comment by parafin** [comment]
I suggest to try native Windows darktable build to see if it's reproducible.

**Comment by chhil** [comment]
I will try it out later. It just takes a long time to build :).

Its not just the import, even the preference dialog freezes.

**Comment by chhil** [comment]
Freeze happens even  when config folders are removed.

**Comment by johnny-bit** [comment]
The file opening issue is weird, I thought that imageio does check for file readability beforehand...

That being said dialogs shouldn't freeze at all. Do you experience freezes in WSL in other gtk-based apps?

**Comment by chhil** [comment]
I don't use WSL linux for any other app, its solely for DT.

I got fed up with it and cleaned out everything and reimporting 21K images. Absolute kosher system the dialog did not freeze but I also did change one more thing, changed my xserver. SO don't know exactly what was the proble,.

Once reimport completes I will retry my tests.

I did rebuild the current windoes build and upgraded , did not face any issue on it.

**Comment by chhil** [comment]
@parafin 
Every image that shows it cannot be read has the following in the db (0,null, or empty strings)

e.g. 
```
[rawspeed] (P1115020.RW2) std::unique_ptr<const rawspeed::Buffer> rawspeed::FileReader::readFile(), line 52: Could not open file "/mnt/f/Temp/delete/Lumix/Kumbharwada/P1115020.RW2".
[dt_imageio_export_with_flags] mipmap allocation for `unused' failed
```

![image](https://user-images.githubusercontent.com/1119439/104874816-cf5fa980-5979-11eb-902c-19497e002500.png)

I have freshly imported all images into the db with their xmps.

**Comment by Nilvus** [comment]
> I did rebuild the current windoes build and upgraded , did not face any issue on it.

So is your issue fixed with last master? If yes, this issue could so be closed.
