### ISSUE TITLE
how should lib module reset buttons work?

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7859]
A lot of the lib modules have active reset buttons but it's not always clear what they do and they often don't appear to do anything. This is in contrast to iop modules where they should always restore default module parameters for that instance so do have consistent behaviour.

The following lib modules have reset buttons that don't seem to have any visual effect on the modules when clicked:

- image information
- selected image[s]
- history stack (lighttable)
- export selected

The tagging module only seems to clear a single field, whereas the styles module prompts to delete all user styles.

Some other modules could perhaps have reset buttons added to them

- import now has a lot of parameters in it, so maybe the reset button could reset them to default
- geotagging could perhaps have a reset button that resets the time offset to 0
- duplicate manager could have a button that removes all duplicates except the current edit (with a warning message)
- mask manager reset button could clear all unused masks

Anyway it would be nice to have some consistent behaviour or to at least know what the intended behaviour for libs is so that we can document it properly. Ideally the behaviour could be defined as a tooltip on the buttons, since it's so different between modules.

**Comment by johnny-bit** [comment]
> selected image[s]

Well, that does "something", namely: clears currently copied image id info, thus "clears copy/paste" buffer...

however `select` module reset could just clear selection.

> export selected

the reset resets all the settings (or most of them) to their default state, so it's actually useful.

> image information

The reset clears custom configuration of metadata info and resets it to standard

> history stack (lighttable)

That indeed does nothing (or rather calls _update(self) but that's the same really ;) )

> import now has a lot of parameters in it, so maybe the reset button could reset them to default

:+1: 

> geotagging could perhaps have a reset button that resets the time offset to 0

That is intesting module that need a bit of love, but yea :+1: 

> duplicate manager could have a button that removes all duplicates except the current edit (with a warning message)

Yeah, that would be cool! :+1:

> mask manager reset button could clear all unused masks

:+1:

**Comment by phweyland** [comment]
> metadata

Does nothing so far.
Proposal: set default visible and private metadata flags.

note: there is a button "clear" which clears the metadata values for the selected images

**Comment by elstoc** [comment]
> Proposal: set default visible and private metadata flags

I'm wary of buttons that are disconnected from their actions. I'd prefer that the reset button was disabled than that it silently altered settings in a sub-window. To be honest disabling the reset button might be a better option for most lib modules.

**Comment by phweyland** [comment]
> > Proposal: set default visible and private metadata flags
> 
> I'm wary of buttons that are disconnected from their actions.

I'm wondering what you mean by "disconnected"...


Maybe going in the same direction ... 
All reset buttons reset the presets effects (and of course corresponding manual parameters changes). I think this valid for both lighttable and darkroom.
We may should stick on this. 

If we follow this any presets preferences should have its own reset button on pref dialog and :

- metadata_view => disable reset button
- metadata editor => disable reset button (as there is the clear button) or remove clear button and reset button replace it.

**Comment by elstoc** [comment]
> I'm wondering what you mean by "disconnected"...

I mean that if you click reset and it changes something it should have immediate obvious visual effects (to guard against accidental clicking) and be easily reversible. If the reset button is changing something which isn't currently visible (with the metadata editor the reset settings are in a separate hidden screen) it's easy for an accidental click on the button to go unnoticed. In the "import" module, if the parameters part of the module is collapsed, clicking on reset might also change things without the user noticing.

In iop modules an accidental click on "reset" is usually noticeable (at least because if affects the image and inserts an entry into the history stack) and reversible (with ctrl+z, or by clicking the previous history stack entry). With lib modules you could accidentally lose a whole bunch of settings with no easy way back. The answer (depending on the module) might be to disable the reset button or for clicking on the reset button to pop up a messagebox saying exactly what it does and make the user confirm or cancel.

A separate button (separate from the reset button) would be the best solution if we're only going to reset some things.

**Comment by phweyland** [comment]
From my view:

Reset means default presets. Everywhere I have presets I should (could) have the reset button.
This is consistent between darkroom and lighttable.

What is not in presets (like preferences of metadata editor) should have a specific way to get their default values.

**Comment by johnny-bit** [comment]
For me reset means "reset settings affected", so eg in selected images reset clears copied image id simply because there's no other way to do it... ( i wonder if removing the image would also remove it from copy... I think not ;) )

**Comment by TurboGit** [comment]
> Reset means default presets. Everywhere I have presets I should (could) have the reset button.
> This is consistent between darkroom and lighttable.

Same here. The "reset" should aim at restoring the dialog as it is when starting a fresh install.
