### ISSUE TITLE
dng corrupted image metadata

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#7860]
**Describe the bug**
I am getting multiple errors of the following everytime i am in Lighttable 

[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8797.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8796.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8785.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8795.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8783.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8787.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8794.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8793.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8792.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8784.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8791.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8790.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8788.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8789.dng: corrupted image metadata
[exiv2 dt_exif_get_thumbnail] F:\Pictures\2011\2011-02\2011-02-25\IMG_8786.dng: corrupted image metadata

The DNG files are converted in lightroom with a lossy compression

Darktable is still running but the errors show ups in the MSYS command line window

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+648~ga52059e5c
 - OS: WIndows 10 Home 64 bit 2004
 - OpenCL activated 
 - Nvidia GTX1060

**Comment by phweyland** [comment]
Seems to be an exiv2 error code. 
You may try to use the exiv2 tool to verify your dng files. 
If you don't find the root cause, you may want to post the issue on exiv2 github.

**Comment by eyedear** [comment]
thanks you are right sorry for the noob question
