### ISSUE TITLE
Exif from Export Does Not Show Lens Model + Lens Serial

### ISSUE THREAD

**Issue by trcgno48** [darktable-org/darktable#7861]
**Describe the bug**
Lens model is not in the Exif after exporting in JPEG. Lens Model and Serial are in the Exif if the JPEG is straight-out-of-camera. The issue happens even when the Lens Model is displayed in the Image Information section of the left pane of Darktable.

**To Reproduce**
1. Export in JPEG after doing the changes in Lighttable.
2. Check the Exif of the export and check if the Lens Model + Lens Serial sections are present.
3. Optional: Upload to Flickr and check if the concerned are listed.

**Expected behavior**
Lens Model and Lens Serial should be displayed in the Exif of the processed file in JPEG.

**Screenshots**
![image](https://user-images.githubusercontent.com/77479325/104716632-12a8f500-578d-11eb-9657-cdf874395761.png)

![image](https://user-images.githubusercontent.com/77479325/104717654-80a1ec00-578e-11eb-9f05-87e41e01100b.png)
.
**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Ubuntu 20.04.1
 - OpenCL activated
 - NVIDIA 1650 Super

**Additional context**

 - This was present even with Darktable 3.0.1 and 3.2.0, which I have tried as well
 - This is only observed in the exported JPEG
 - The issue persists even with a fresh history.
 - I noticed that on Flickr, those whose Lens Types are displayed use Exiftool as the XMPtoolkit, whereas if the XMPtoolkit is XMP Core 4.4.0-Exiv2, which my Darktable 3.4.0 uses, the Lens Model is not displayed. I am not sure if these are related, though.
 - Exiftool as XMPtoolkit
![image](https://user-images.githubusercontent.com/77479325/104717373-16894700-578e-11eb-83f0-ee94a76ecefc.png)
 - XMP Core 4.4.0-Exiv2 as the XMPtoolkit
![image](https://user-images.githubusercontent.com/77479325/104717557-5c460f80-578e-11eb-9e51-4a8757e8ef2f.png)

**Comment by phweyland** [comment]
Lens model may be a tricky subject...
dt makes its best to display valid information about lenses but doesn't change the exif information.
As a workaround you can use the export metadata option to fill in exif metadata with $(VARIABLES).

> Lens Model and Lens Serial should be displayed in the Exif of the processed file in JPEG.

Can you show the exif data of the corresponding raw file ?

**Comment by trcgno48** [comment]
Here are the screenshots of the RAW exif using exiftool as exif doesn't display the exif of the .RW2 file:
![image](https://user-images.githubusercontent.com/77479325/104726628-cf548380-5798-11eb-8327-9d7b1cc79973.png)
![image](https://user-images.githubusercontent.com/77479325/104726670-e4c9ad80-5798-11eb-8673-9b4547f3b7a5.png)
![image](https://user-images.githubusercontent.com/77479325/104726745-075bc680-5799-11eb-8217-8efcf7747df0.png)
![image](https://user-images.githubusercontent.com/77479325/104726789-19d60000-5799-11eb-8fd1-5fbcff0dd0a3.png)
![image](https://user-images.githubusercontent.com/77479325/104726834-32461a80-5799-11eb-98ab-12046e874109.png)
![image](https://user-images.githubusercontent.com/77479325/104726901-50ac1600-5799-11eb-9133-51916df0eb9c.png)

I just noticed that the exif using the exif command displays very lean details whereas when I used exiftool to view the exif of the JPEG, it displays the whole lot. Cheers.

**Comment by johnny-bit** [comment]
Metadata reading capabilities in darktable depend on Exiv2, anlong with lens recognition. Check your exiv2 version and ty to print ALL tags using exiv2

**Comment by trcgno48** [comment]
> Metadata reading capabilities in darktable depend on Exiv2, anlong with lens recognition. Check your exiv2 version and ty to print ALL tags using exiv2

My Exiv2 version is 0.27.2

Here are the screenshots of the Exiv2 printout of the same file:
![image](https://user-images.githubusercontent.com/77479325/104730285-a1723d80-579e-11eb-8191-860401bc28d9.png)
![image](https://user-images.githubusercontent.com/77479325/104730307-ae8f2c80-579e-11eb-8bda-ddfe400aabc0.png)
![image](https://user-images.githubusercontent.com/77479325/104730334-bb138500-579e-11eb-9b56-98aa61a50bcc.png)
![image](https://user-images.githubusercontent.com/77479325/104730407-df6f6180-579e-11eb-81c9-8373b8769e9f.png)

The Lens Model and Serial are displayed on this printout. I am not sure what I am missing. Cheers.

**Comment by johnny-bit** [comment]
side node: screenshots of terminal windows are... not optimal solution to sharing data. Next time please either copy contents into text file and attach text file or put text in issue as code (see https://guides.github.com/features/mastering-markdown/ on how to do it)

**Comment by trcgno48** [comment]
Apologies, @johnny-bit. That was my midnight laziness.

Here is the Exif output using the syntax `exiv2 -PExgnycv P1100372.jpg`

C1 | C2 | C3 | C4 | C5 | C6
---|-----|------|------|-----|---------------------------------
0x010f | Image    |    Make        |                Ascii     | 10 | Panasonic
0x0110 | Image  |      Model           |            Ascii    |   8 | DMC-GM5
0x0112 | Image  |      Orientation|                 Short    |   1 | 1
0x011a  |Image      |  XResolution     |            SRational  | 1 | 300/1
0x011b |Image   |     YResolution        |         SRational   |1 | 300/1
0x0128 |Image    |    ResolutionUnit      |        Short   |    1 | 2
0x0131 |Image    |    Software        |            Ascii   |   16 | darktable 3.4.0
0x0132 |Image    |    DateTime           |         Ascii    |  20  |2021:01:16 01:24:34
0x4746 |Image     |   Rating           |           SLong    |   1|  1
0x4749 |Image  |      RatingPercent         |      SLong      | 1  |20
0x8298 |Image    |    Copyright     |              Ascii   |    0
0x8769 |Image     |   ExifTag             |        Long   |     1 | 476
0x829a |Photo   |     ExposureTime         |       Rational  |  1 | 10/2500
0x829d |Photo    |    FNumber            |         Rational   | 1  |17/10
0x8822 |Photo       | ExposureProgram          |   Short    |   1  |3
0x8827 |Photo   |     ISOSpeedRatings     |        Short     |  1  |200
0x8830 |Photo      |  SensitivityType  |           Short   |    1  |1
0x9000 |Photo    |    ExifVersion        |         Undefined |  4  |48 50 51 48
0x9003| Photo     |   DateTimeOriginal          |  Ascii  |    20 | 2021:01:08 12:20:33
0x9004 |Photo      |  DateTimeDigitized    |       Ascii  |    20  |2021:01:08 12:20:33
0x9204 |Photo  |      ExposureBiasValue  |         SRational  | 1  |0/100
0x9205 |Photo     |   MaxApertureValue      |      Rational   | 1  |392/256
0x9207 |Photo   |     MeteringMode      |          Short |      1 | 5
0x9208 |Photo      |  LightSource          |       Short   |    1 | 0
0x9209 |Photo   |     Flash           |            Short     |  1 | 16
0x920a |Photo    |    FocalLength     |            Rational   | 1 | 250/10
0x927c |Photo   |     MakerNote              |     Undefined| 12316  |(Binary value suppressed)
0x0001 |MakerNote  |  Offset        |              Long   |     1 | 898
0x0002 |MakerNote  |  ByteOrder      |             Ascii   |    3 | II
0x0001 |Panasonic |   Quality          |           Short  |     1 | 7
0x0002 |Panasonic  |  FirmwareVersion     |        Undefined |  4 | 0 1 1 0
0x0003 |Panasonic  |  WhiteBalance        |        Short     |  1 | 1
0x0007 |Panasonic  |  FocusMode            |       Short      | 1 | 8
0x000f |Panasonic   | AFMode         |             Byte     |   2 | 0 23
0x001a |Panasonic   | ImageStabilization    |      Short    |   1  3
0x001c |Panasonic   | Macro           |            Short      | 1 | 2
0x001f |Panasonic  |  ShootingMode    |            Short    |   1 | 7
0x0020 |Panasonic   | Audio             |          Short  |     1 | 2
0x0021 |Panasonic   | DataDump              |      Undefined |8200  |(Binary value suppressed)
0x0024| Panasonic  |  FlashBias         |          Short     |  1 | 0
0x0025 |Panasonic|    InternalSerialNumber      |  Undefined | 16  |88 48 52 49 53 48 53 49 51 48 48 49 53 0 0 0
0x0026 |Panasonic |   ExifVersion           |      Undefined  | 4  |48 52 48 56
0x0029 |Panasonic   | TimeSincePowerOn        |    Long   |     1  |2118
0x002a |Panasonic  |  BurstMode         |          Short |      1 | 0
0x002b |Panasonic   | SequenceNumber     |         Long      |  1  |0
0x002e |Panasonic  |  SelfTimer           |        Short  |     1 | 1
0x0030 |Panasonic    |Rotation                |    Short     |  1 | 1
0x0031 |Panasonic  |  AFAssistLamp         |       Short     |  1 | 4
0x0033 |Panasonic |   BabyAge1              |      Ascii  |    20 | 9999:99:99 00:00:00
0x0035 |Panasonic   | ConversionLens        |      Short   |    1 | 1
0x0036 |Panasonic  |  TravelDay          |         Short    |   1 | 65535
0x003a |Panasonic|    WorldTimeLocation       |   Short    |   1  |1
0x003b |Panasonic   | TextStamp1       |           Short  |     1|  1
0x003c |Panasonic   | ProgramISO           |       Short  |     1  |65535
0x003d |Panasonic   | AdvancedSceneType    |       Short   |    1 | 1
0x003e |Panasonic  |  TextStamp2             |     Short    |   1  |1
0x003f |Panasonic|    FacesDetected           |    Short     |  1 | 0
0x0044 |Panasonic |   ColorTempKelvin     |        Short   |    1  |5000
0x0045 |Panasonic   | BracketSettings     |        Short   |    1 | 0
0x0046 |Panasonic   | WBAdjustAB          |        Short    |   1  |0
0x0047 |Panasonic   | WBAdjustGM       |           Short  |     1 | 0
0x0048 |Panasonic   | FlashCurtain        |        Short       |1|  0
0x0049 |Panasonic  |  LongShutterNoiseReduction |  Short     |  1|  2
0x004b| Panasonic |   ImageWidth            |      Long       | 1 | 4592
0x004c |Panasonic  |  ImageHeight           |      Long      |  1  |3448
0x004d |Panasonic  |  AFPointPosition       |      Rational  |  2|  128/256 171/256
0x004e |Panasonic   | FaceDetInfo         |        Undefined | 42  |0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0051 |Panasonic   | LensType           |         Ascii   |   34  |LUMIX G 25/F1.7
0x0052 |Panasonic   | LensSerialNumber     |       Ascii    |  14 | 09EX4101536D
0x0053 |Panasonic  |  AccessoryType          |     Ascii    |  34 | NO-ACCESSORY
0x0054 |Panasonic  |  AccessorySerialNumber    |   Ascii    |  14  |0000000
0x0060 |Panasonic  |  LensFirmwareVersion    |     Undefined |  4  |0 1 1 0
0x0061 |Panasonic  |  FaceRecInfo        |         Undefined |148 | (Binary value suppressed)
0x0065 |Panasonic    |Title                 |      Undefined  |64  |0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0066 |Panasonic  |  BabyName            |        Undefined  |64 | 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0067 |Panasonic |   Location          |          Undefined | 64  |0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0069 |Panasonic  |  Country              |       Undefined  |72 | 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x006b |Panasonic    |State           |            Undefined | 72 | 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x006d |Panasonic   | City          |              Undefined | 72|  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x006f |Panasonic |   Landmark               |     Undefined |128|  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0070 |Panasonic   | IntelligentResolution   |    Byte   |     1 | 3
0x0077 |Panasonic   | BurstSheed       |           Short     |  1 | 0
0x0079 |Panasonic |   IntelligentDRange     |      Short    |   1  |0
0x007c |Panasonic  |  ClearRetouch           |     Short     |  1 | 0
0x0080 |Panasonic |   City2                |       Undefined | 72 | 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0x0089 |Panasonic  |  PhotoStyle      |            Short   |    1 | 1
0x008a |Panasonic    |ShadingCompensation        | Short  |     1  |0
0x008c |Panasonic   | AccelerometerZ              |Short    |   1|  268
0x008d |Panasonic   | AccelerometerX    |         Short|       1  |65530
0x008e |Panasonic    |AccelerometerY          |    Short     |  1  |23
0x008f |Panasonic  |  CameraOrientation       |    Byte       | 1 | 0
0x0090 |Panasonic  |  RollAngle          |         Short   |    1|  3
0x0091 |Panasonic  |  PitchAngle            |      Short     |  1  |82
0x0093 |Panasonic   | SweepPanoramaDirection  |    Byte      |  1 | 0
0x0094 |Panasonic    |PanoramaFieldOfView     |    Short   |   1 | 0
0x0096 |Panasonic  |  TimerRecording |             Byte    |    1  |0
0x009d |Panasonic  |  InternalNDFilter       |     Rational    |1  |0/128
0x009e |Panasonic  |  HDR         |                Short   |    1 | 0
0x009f |Panasonic    |ShutterType        |         Short    |   1|  2
0x00a3 |Panasonic  |  ClearRetouchValue   |        Rational  |  1 | 0/0
0x00ab |Panasonic    |TouchAE          |           Short    |   1 | 0
0x8000 |Panasonic   | MakerNoteVersion    |        Undefined |  4  |48 49 52 56
0x8007 |Panasonic |   FlashFired      |            Short     |  1  |1
0x8008 |Panasonic  |  TextStamp3         |         Short      | 1 | 1
0x8009 |Panasonic   | TextStamp4          |        Short   |    1 | 1
0x8010 |Panasonic   | BabyAge2      |              Ascii   |   20 | 9999:99:99 00:00:00
0x9290 |Photo       | SubSecTime       |           Ascii    |   4  |650
0x9291 |Photo     |   SubSecTimeOriginal     |     Ascii   |    4  |650
0x9292 |Photo |       SubSecTimeDigitized         |Ascii     |  4  |650
0xa000 |Photo      |  FlashpixVersion         |    Undefined  | 4  |48 49 48 48
0xa001 |Photo    |    ColorSpace               |   Short     |  1 | 1
0xa002 |Photo      |  PixelXDimension      |       Long   |     1 | 4591
0xa003 |Photo      |  PixelYDimension          |   Long      |  1  |3447
0xa005 |Photo   |     InteroperabilityTag     |    Long    |    1  |13214
0x0001 |Iop      |    InteroperabilityIndex   |    Ascii    |   4  |R98
0x0002 |Iop        |  InteroperabilityVersion    |  4  |48 49 48 48
0xa217 |Photo |       SensingMethod               Short   |    1 | 2
0xa300 |Photo   |     FileSource            |      Undefined |  1 | 3
0xa402 |Photo    |    ExposureMode       |         Short   |    1  |0
0xa403 |Photo        |WhiteBalance  |              Short   |    1|  0
0xa405 |Photo  |      FocalLengthIn35mmFilm    |   Short  |     1  ||50
0x9003| Image  |      DateTimeOriginal     |       Ascii     | 20 | 2021:01:08 12:20:33

The lens model and serial are included but when `exif P1100372.jpg` is used, the output is:

XIF tags in 'P1100372.jpg' ('Intel' byte order):

Tag                 |Value
--------------------|----------------------------------------------------------
Manufacturer        |Panasonic
Model               |DMC-GM5
Orientation         |Top-left
X-Resolution        |300
Y-Resolution        |300
Resolution Unit     |Inch
Software            |darktable 3.4.0
Date and Time       |2021:01:16 01:24:34
Exposure Time       |1/250 sec.
F-Number            |f/1.7
Exposure Program    |Aperture priority
ISO Speed Ratings   |200
Exif Version        |Exif Version 2.3
Date and Time (Origi|2021:01:08 12:20:33
Date and Time (Digit|2021:01:08 12:20:33
Exposure Bias       |0.00 EV
Maximum Aperture Val|1.53 EV (f/1.7)
Metering Mode       |Pattern
Light Source        |Unknown
Flash               |Flash did not fire, compulsory flash mode
Focal Length        |25.0 mm
Maker Note          |12316 bytes undefined data
Sub-second Time     |650
Sub-second Time (Ori|650
Sub-second Time (Dig|650
FlashPixVersion     |FlashPix Version 1.0
Color Space         |sRGB
Pixel X Dimension   |4591
Pixel Y Dimension   |3447
Sensing Method      |One-chip color area sensor
File Source         |DSC
Exposure Mode       |Auto exposure
White Balance       |Auto white balance
Focal Length in 35mm|50
Interoperability Ind|R98
Interoperability Ver|0100

The latest output is similar to what is displayed on Flickr where the lens model and serial are not included:


    JFIFVersion - 1.02
    X-Resolution - 300 dpi
    Y-Resolution - 300 dpi
    Make - Panasonic
    Orientation - Horizontal (normal)
    Software - darktable 3.0.1
    Date and Time (Modified) - 2020:11:15 18:57:50
    YCbCr Positioning - Centered
    Rating - 5
    Rating Percent - 100
    ISO Speed - 200
    Sensitivity Type - Standard Output Sensitivity
    Exif Version - 0230
    Date and Time (Original) - 2020:10:06 10:56:20
    Date and Time (Digitized) - 2020:10:06 10:56:20
    Components Configuration - Y, Cb, Cr, -
    Exposure Bias - 0 EV
    Max Aperture Value - 1.7
    Metering Mode - Center-weighted average
    Light Source - Unknown
    Sub Sec Time - 472
    Sub Sec Time Original - 472
    Sub Sec Time Digitized - 472
    Flashpix Version - 0100
    Color Space - sRGB
    Sensing Method - One-chip color area
    File Source - Digital Camera
    Exposure Mode - Auto
    White Balance - Auto
    Focal Length (35mm format) - 51 mm
    Interop Index - R98 - DCF basic file (sRGB)
    Interop Version - 0100
    XMPToolkit - XMP Core 4.4.0-Exiv2
    Rating - 5

**Comment by phweyland** [comment]
see #6074

**Comment by phweyland** [comment]
@trcgno48 please share a sample of raw file please. I'll have a look at it.

**Comment by trcgno48** [comment]
> see #6074
I saw this thread before your post, as well as #4922. I just used 
![image](https://user-images.githubusercontent.com/77479325/104824864-9e6c6f80-58ba-11eb-8398-c0d2958c6a59.png)

I read about metadata when exporting on this article (https://www.darktable.org/usermanual/en/overview/workflow/export-metadata-upload/) and I am fine with that. I like the controllability with Darktable, anyway.

> @trcgno48 please share a sample of raw file please. I'll have a look at it.
#6074 solved this. Do you still want the raw file?

Also, I noticed that there is a difference between straight-out-of-camera (SooC) JPEGs that are accessed through WiFi from the camera vs from the SD card, where the ones sent through WiFi retains the lens model whereas the ones accessed directly through the SD card don't. I am guessing this may be an Ubuntu issue not a Darktable one?

**Comment by phweyland** [comment]
> Do you still want the raw file or can I close this issue?

If you are happy you can close the issue ! :smiley:

**Comment by trcgno48** [comment]
The answers are in #6074 and #4922. So I just entered: 
![image](https://user-images.githubusercontent.com/77479325/104828657-94556b80-58d0-11eb-9de2-37ac538ee464.png)

 We have to embrace the controllability with such a great software. Thanks @phweyland and @johnny-bit!
