### ISSUE TITLE
tête de mort et profil de couleur d'entrée

### ISSUE THREAD

**Issue by jicehem** [darktable-org/darktable#7868]
Hello,

Je suis sur Mac (Mac mini fin 2014, OS 10.14.6 et MBAir 2020 M1, Os 11.0.1 ).
Sur dt 3.2 et Mac Mini, je travaillais les images d’une collection (réunie par mots-clés). Après installation de dt 3.4, j’ai rouvert la même collection (sans aucun changement). Plusieurs images sont apparues avec la vignette tête de mort. Quitter/relancer n’y changeait rien.
J’ai dupliqué les fichiers natifs (1 jpg et 9 NEF, sans les xmp) dans un autre dossier. Je l’ai ouvert sur MBAir (avec dt 3.4). Pas de tête de mort. Mais dès que j’appliquait un style (dont balance des couleurs désaturées), toutes les images étaient très sous-exposées et en noir, blanc et vert. (voir captures d'écran)
![1 vignettes table lumineuse](https://user-images.githubusercontent.com/77507200/104769897-4aee0a80-5770-11eb-93b6-bd693e971e75.png)
![2 chambre noire après compression et retour original](https://user-images.githubusercontent.com/77507200/104769903-4de8fb00-5770-11eb-9726-e9aced21b50c.png)
![3 chambre noir après activation exposition + 10IL](https://user-images.githubusercontent.com/77507200/104769906-4de8fb00-5770-11eb-8020-0226af22c604.png)

Le profil de couleur d'entrée était sur "sRVB (ex JPG)"; j’ai choisi "matrice couleur standard" et l’image est redevenue normale. J’ai vérifié sur les autres images de la collection, celles ouvertes sans problème sont en profil de couleur d'entrée "sRVB (ex JPG) ».
J’ai changé les mots clés des xmp « tête de mort » pour les attribuer aux fichiers dupliqués. J’ai rouvert la collection sur Mac mini : 2 sur 10 reviennent en « tête de mort ».
Sur Dropbox, le NEF et les xmp d’un fichier s’ouvrant sur MBAir et pas sur MacMini  

Merci !

**Comment by jicehem** [comment]
Le lien Dropbox https://www.dropbox.com/sh/n68jyw7hdmjxai9/AADI4-ACLsm3NJui3XpkV1L5a?dl=0

**Comment by Nilvus** [comment]
@jicehem: je sais qu'Aurélien a dit dans une vidéo que cela pouvait être écrit en français mais en réalité, ça fera peu de personnes à regarder. La matrice sRVB est trop limitée, donc tu réduis déjà fortement le champ des possibles sur le travail couleur. Il est recommandé de ne pas utiliser cette matrice. Je te recommande de lire les articles sur darktable 3.0, 3.2 et 3.4. Tu trouveras les liens sur darktable.fr. Je t'invite également à consulter la page "darktable 3.0 : pas-à-pas" du menu "Apprendre" sur darktable.fr.

Au vu de ton message, de ce que j'en comprends, tu as résolu le problème en mettant matrice couleur standard, ce qui est dans 99% des cas le bon choix. Ensuite, sur ce même module, choisis le Rec2020 linéaire ou proPhoto en espace de travail, ira aussi dans 99% des cas.

Ce n'est qu'en profil de sortie, que tu choisis le sRVB (majoritairement pour sortie web/numérique). En réalité dans ce module, tu ajuste le profil selon le média de sortie.

Bref, je vais fermer ton rapport considérant que c'est résolu.

Pour la tête de mort, ça veut dire que darktable ne trouve pas l'image, donc il y a un soucis de lien dans la base de données vers où est l'image sur ton Mac mini donc. Tu as donc une différence de lien très probablement entre le Macbook air et le Mac mini.

Et donc ça n'est pas un bug et pas sa place ici. Je te conseille de poursuivre en postant ce qu'il te reste comme question ou demande d'aide sur le forum du site darktable.fr. Cherche déjà les sujets sur les têtes de mort dans le forum, il y en a un paquet qui t'aideront peut-être.

**Comment by Nilvus** [comment]
J'oubliais si un jour tu veux poster un rapport de bug (qui ne serait pas de l'utilisation pure du logiciel comme ici), je te conseille de le rédiger via le traducteur en ligne Deepl (https://www.deepl.com/translator) et de poster ici en anglais. Et si besoin, tu peux demander de l'aide d'abord sur le forum darktable pour t'assurer de ce que tu peux poster ou éventuellement qu'un de nous le fasse, pour comprendre ensuite les retours.
