### ISSUE TITLE
Tweak to process when setting up a new module group

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#7876]
This is based on dt 3.5.0+654~g616308c7b-dirty   with Ubuntu 18.04

Suppose you're setting up a new group and successively picking modules from the "dropdown" list.  Once you've added several, the window showing the group becomes full and you have to scroll down each time to get to the Plus button.  A suggestion is to display this window already scrolled to the bottom; or keep the Plus button separate i.e. always available regardless of scroll.

**Comment by Nilvus** [comment]
Or maybe just move + button on top of modules list. To be precise, just between group name and module list. @AlicVB: what's your view on that? Should be simple to do.
