### ISSUE TITLE
Canon 90D (not CR3 related)

### ISSUE THREAD

**Issue by daniel-lucio** [darktable-org/darktable#7877]
A question/request:

What needs to be done in order to let some modules such as objective-correction or noise-reduction-profile to support the 90D. Let's start working from a DNG.

What kind of information do you need?

**Comment by Nilvus** [comment]
About objective correction, darktable use lensfun library. See: https://lensfun.github.io/calibration/
About noises profiles and camera support in general in darktable, this page will help you: https://www.darktable.org/resources/camera-support/

**Comment by johnny-bit** [comment]
Check https://github.com/darktable-org/darktable/wiki/Camera-support

[noise profiling](https://github.com/darktable-org/darktable/wiki/Camera-support#noise-profiles) (imo) should work on original raws but meh, cr3 should work

For [lens correction](https://github.com/darktable-org/darktable/wiki/Camera-support#lens-correction) Follow the mentioned articles.

As of 2020-01-16 i see that EOS 90D is supported in https://wilson.bronger.org/lensfun_coverage.html so on your end it's just question of updating DB and if you have lens that isn't in db - follow the article :)

For WB coeffs - better wait for CR3 supprort and then you'll be able to follow https://github.com/darktable-org/darktable/wiki/White-balance-presets

Closing as this is just a question and not a new noise profile. Please open new issue with noise profile :)
