### ISSUE TITLE
Colour mapping

### ISSUE THREAD

**Issue by terrivincent** [darktable-org/darktable#7879]
I have recently downloaded Darktable 3.4.0 and I am using Windows 10.

Darktable crashes when I try to use the color mapping module.

I can "acquire as source" from one image, but when I choose a second image and select "acquire as target" the program crashes, without any warning.

I am keen to use this module, so I am hoping that this issue can be rectified.

**Comment by Mark-64** [comment]
Confirmed here with Win10 and DT 3.4.0 as well as git master

**Comment by Mark-64** [comment]
Bisect indicates c4aa8b8826ec4cffec26271654d44f272d962043 as the culprit.
@ralfbrown I'm sorry to give you more headache :-(

**Comment by ralfbrown** [comment]
And of course this won't replicate on my system either, or it would never have been submitted as a PR.   All the commit does is round up `data->n` to make `roundup(data->n)*sizeof(float)` a multiple of the cacheline size.  So what's the value of `allocsize` immediately after the call to `dt_alloc_perthread`?  It should be a multiple of 16 (and unless there's a way to set `data->n` higher than 16, that's exactly the value it should have).  Also double-check that the returned buffer pointer is not NULL.

**Comment by ralfbrown** [comment]
I was taking a closer look at the code, and realized that the aligned `weight_buf` was being released with a regular `free` -- which works fine on Linux, but is known to crash on Windows from a previous bug.  I won't be able to verify that the fix works, but PR incoming in 3,2.1,...
