### ISSUE TITLE
Allow Numeric entry and Individual parameter reset in Negadoctor

### ISSUE THREAD

**Issue by rexbron** [darktable-org/darktable#7882]
**Is your feature request related to a problem? Please describe.**

Often when making adjustments in the Negadoctor module, You may with to reset to default values of one adjustment without affecting the values of other adjustments, for example like the basemask Dmin values.

**Describe the solution you'd like**

Allow for direct numeric input of values as well as a reset to defaults for each slider.

**Comment by parafin** [comment]
https://www.darktable.org/usermanual/en/darkroom/interacting-with-modules/module-controls/
