### ISSUE TITLE
Darktable does't apply default modules on some DNG files

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/darktable#7886]
I get this strange behavior where Darktable doesn’t apply the defaults for scene linear workflow and I can’t use many modules like “hot pixels”, “chromatic aberrations” and a few others because Darktable says I’m not feeding it the raw image. I’m feeding it an hdr dng image creatied with 5 AEB images from a DJI Inspire 1_v2 drone. Shouldn’t it be recognised as raw?

This is a hdr raw image that I created a few years ago and I don’t have the original files anymore.
![Screenshot from 2021-01-16 17-47-38](https://user-images.githubusercontent.com/10299892/104817702-1e46fb00-5823-11eb-89d7-d3238632305e.png)

Here’s the dng file:
https://discuss.pixls.us/uploads/short-url/1KnqEtfVCIsLT8dJF6vWgIF20Qz.dng

**Comment by pitbuster** [comment]
I think that RAW here means data before demosaicing. Your DNG probably is already demosaiced, so those modules won't work.

The rest of the scene-referred workflow should worf fine, though, so not applying the defaults seems wrong.

**Comment by KristijanZic** [comment]
Yes, that has been pointed out to me here:
https://discuss.pixls.us/t/dng-hdr-images-not-recognised-as-raw-by-darktable/22758

I've renamed the issue to reflect just the default modules not being activated on opening with darkroom.

**Comment by jenshannoschwalm** [comment]
How can you expect a non-raw file (one without bayer data as one example) to enable modules that only work on such sensor data?

I guess the only module you **might** expect to be enabled here would be filmicrgb? But that wouldn't make sense imho as any non-raw should be expected to be developed already. 

DNF files are "containers", look at the data you can get via `exiv2 -pa xxx` in your image. You have 16bit float, linear-raw in Subimage1. Also your whitelevel in the file is 32768, don't know whether you developed the image that dark or the software you have been using did that without telling you but that is all out of dt's understanding.

I think it's not an issue at all ...

**Comment by KristijanZic** [comment]
Thanks for the info. Yeah, it's an old image from Lightroom.
