### ISSUE TITLE
ungroup button is clickable even when selected image is not part of a group

### ISSUE THREAD

**Issue by HansBull** [darktable-org/darktable#7888]
**Describe the bug**
ungroup button is clickable even when selected image is not part of a group. Leads to `dt_grouping_remove_from_group` being called, which in turn executes the query on grouping.c line 53, which returns no result, leading to `new_group_id` remaining -1, which leads to a obviously invalid query `UPDATE main.images SET group_id = -1 WHERE group_id = ?2 AND id != ?3` in line 68. The function will also return the invalid `new_group_id` value. 
It seems that such a invalid group id value will also be retrieved when `dt_grouping_remove_from_group` is called from `dt_image_remove` and the image is not grouped at all, and will then be set as `darktable.gui->expanded_group_id`.

**Expected behavior**
ungroup button should not be clickable when image is not part of a group. 

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+680~g895b98fe3
 - OS: Ubuntu 18.04.5

**Additional context**
I see `dt_grouping_add_to_group` does not modify the database. Is that intended behaviour?

**Comment by Nilvus** [comment]
@johnny-bit: maybe for you this one.

**Comment by johnny-bit** [comment]
I only done disable/enable on buttons whioch handling func had checkers... so I can add new checker there + gui update for buttons to make more sense, no prob :)

as for "additional context" problem - dunno, one needs to track that...

**Comment by johnny-bit** [comment]
expanded group being set to -1 is perfectly fine...

Check  #7897 :)

**Comment by HansBull** [comment]
Very promising.
