### ISSUE TITLE
Indicate in history the name of auto-applied preset

### ISSUE THREAD

**Issue by deanc** [darktable-org/darktable#7889]
**Is your feature request related to a problem? Please describe.**

When setting up presets which are automatically applied (e.g. based off camera model), it is not immediately clear upon viewing the history of the image, that the preset is applied. The only way to see this is to notice in your list of modules that the particular preset is active and then clicking the menu for that preset and the name of the preset is then in bold.

**Describe the solution you'd like**

I would suggest a simple change to the history stack to indicate which steps in the history were applied as a result of a preset. Change the item in the history view to the name of the preset (e.g. instead of showing `Exposure` show `X100F exposure fix` (my preset name).

Now:
```
3 Exposure
2 Demosaic
1 Raw black/white point
0 Original
```

Proposal:
```
3 X100f exposure fix
2 Demosaic
1 Raw black/white point
0 Original
```

**Alternatives**

You could group the automatically applied presets with a header "User-defined presets:" and then put the items below.

Now:
```
3 Exposure
2 Demosaic
1 Raw black/white point
0 Original
```

Proposal:
```
----
User defined presets:
3 X100f exposure fix
----
2 Demosaic
1 Raw black/white point
0 Original
```

**Comment by elstoc** [comment]
Perhaps something could be added to the tooltip? Not entirely sure I understand the introspection black magic that's is used for the tooltip.

**Comment by Nilvus** [comment]
I'm not for that, but as @elstoc, this could be added in the tooltip and why not an icon or character (like an asterisk) to quickly show which one is form a preset.

I use the name of camera for my automatic preset, so if we apply your idea as it is, I will see many "camera-name" in history and it will be hard to quickly show which module is behind.

**Comment by deanc** [comment]
@Nilvus this seems reasonable, also.

**Comment by wpferguson** [comment]
As long as we are doing what if, how about a tree view where the style is displayed, but can be expanded to see  the modules applied then collapsed to take up less space?

**Comment by Nilvus** [comment]
> As long as we are doing what if, how about a tree view where the style is displayed, but can be expanded to see the modules applied then collapsed to take up less space?

I'm afraid that this will anyway overload history. I think tooltip suggested by @elstoc remains the best way.

**Comment by deanc** [comment]
It is important there is at least some visual indicator (tooltip requires interaction). Exposure could be applied automatically by the camera profile, or by the user preset, or some prior edit the user forgot.

**Comment by ralfbrown** [comment]
Does #13149 address your request?  Modules are now labeled with the names of presets, so you can scan the history for the name of the preset, which will show up whether manually or automatically applied.

if so, please close this issue.
