### ISSUE TITLE
database 33 upgrade freezes

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#7891]
ae6065691b49c0090b2d05074514632ae0f41af0 is ok
bfa4cb27c98f5365e66a11d036c22bf0e51933b5 freezes on the database upgrade - no message

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS:  debian 10

**Comment by TurboGit** [comment]
It can takes time... This upgrade is moving good part of the db structure.

**Comment by phweyland** [comment]
Correct, 1'15".
Maybe deserves a warning ...

**Comment by TurboGit** [comment]
Probably so. I bet you have a lot of tag ? On my side my 90k images db it took 5s but I expected this to be CPU hungry.

**Comment by phweyland** [comment]
50.000 images
2.500 tags

**Comment by TurboGit** [comment]
1533 tags
172891 tagged_images entries (this is the important one I think)

**Comment by TurboGit** [comment]
Also I'm on a SSD.

**Comment by phweyland** [comment]
273.000 tagged_images entries
system + db on SDD
images on HDD

**Comment by HansBull** [comment]
Sorry to hear that.

**Comment by phweyland** [comment]
It is not a problem if one knows what does happen :smiley:

**Comment by ptilopteri** [comment]
I have same problem and ran "darktable -d all"

>190k images
beginning size of library.db    936312832

time darktable -d all
0.000066 application_directory: /usr/bin
0.000102 darktable.datadir: /usr/share/darktable
0.000117 darktable.plugindir: /usr/lib64/darktable
0.000128 darktable.localedir: /usr/share/locale
0.000164 darktable.configdir: /home/paka/.config/darktable
0.000183 darktable.cachedir: /home/paka/.cache/darktable
0.000194 darktable.sharedir: /usr/share
0.000206 darktable.tmpdir: /tmp
[memory] at startup
[memory] max address space (vmpeak):       94340 kB
[memory] cur address space (vmsize):       94308 kB
[memory] max used memory   (vmhwm ):       30700 kB
[memory] cur used memory   (vmrss ):       30700 kB
0.000261 new_xdg_data_dirs: (null)
WINDOW DECORATIONS RELOADED
WINDOW DECORATIONS RELOADED
0.424459 output profile `2-Color separation look (Red x Black)' color
space `Lab ' not supported for histogram profile
0.424472 output profile `2-Color separation look (Red x Green)' color
space `Lab ' not supported for histogram profile
0.424475 output profile `Invert lightness' color space `Lab ' not
supported for histogram profile
0.424477 output profile `Old picture' color space `Lab ' not supported for
histogram profile
0.444572 [init sql] library: /home/paka/.config/darktable/library.db,
data: /home/paka/.config/darktable/data.db
[init] can't copy back from images_old
[init]   FOREIGN KEY constraint failed
[init] database `library.db' couldn't be upgraded from version 30 to 33.
aborting
ERROR : cannot open database

real    15m57.042s
user    8m41.566s
sys     7m6.821s

**Comment by ptilopteri** [comment]
3.5.0-687-g9ade33f78

**Comment by TurboGit** [comment]
@ptilopteri : In a VM ? Looks like there is not enough memory space.

**Comment by ptilopteri** [comment]
no, but no swap.  guess I will have to add temporary file-swap space.  with 36gb memory, I have not had swap for several years now.

will try again after providing temporary swap space.

tks,

**Comment by HansBull** [comment]
@ptilopteri  Can you run in sqlitebrowser or similar a 
`SELECT id FROM images WHERE film_id NOT IN (SELECT id FROM film_rolls)`
?

**Comment by ptilopteri** [comment]
Execution finished without errors.
Result: 145 rows returned in 46ms
At line 1:
SELECT id FROM images WHERE film_id NOT IN (SELECT id FROM film_rolls)

**Comment by ptilopteri** [comment]
I have added 8gb temporary file based swap and trying to update library.db

**Comment by ptilopteri** [comment]
@HansBull did you intend me to run that before trying to upgrade the db?  as I had already
started before seeing your post, but after adding 8gb swap.

**Comment by HansBull** [comment]
no no memory is not the problem.
You have a inconsistency in your database: you have images with invalid film_ids, that is, images pointing to film rolls that do not exist any more. There are dozens of queries in darktable querying here and there folder names of film rolls, so sooner or later you would, in any case, encounter problems with those images.
Now the question is, how to deal with those corner cases? (which, @TurboGit  , has to go in the upgrade code to v.33)
1. adding a dummy film roll with a folder name like "INVALID_FILM_ROLL_PATH" and pointing those images to that path, just to keep them
2. deleting them

**Comment by HansBull** [comment]
@ptilopteri 
You could try the first variant. do a 
`INSERT INTO film_rolls (folder) VALUES("INVALID_FILM_ROLL_PATH")`
retrieve the dummy film id by
`SELECT id FROM film_rolls WHERE folder="INVALID_FILM_ROLL_PATH"`
note the value
do a 
`UPDATE images SET film_id=<that value> WHERE film_id NOT IN (SELECT id FROM film_rolls)`

**Comment by ptilopteri** [comment]
ok, will try that next.  this attempt failed

Execution finished without errors.
Result: query executed successfully. Took 34ms, 145 rows affected
At line 1:
UPDATE images SET film_id=2548 WHERE film_id NOT IN (SELECT id FROM film_rolls)

retrying update with resultant library.db
and I backed up first

**Comment by TurboGit** [comment]
First I'll reopen this issue.

**Comment by HansBull** [comment]
Tested with  c04751e7992fac78c3d389f7586e8ab8187e3689

**Comment by TurboGit** [comment]
> Now the question is, how to deal with those corner cases?

Add code in database.c to delete all images without a film_roll. If there is no film roll, there is no location for this image so no raw/jpg, no xmp reachable. In such a case users are seeing a skull and the response is delete them and reimport (or restore the folder if renamed/moved). But this is possible when we know the folder name, here is the information is lost, so yes removing seems the only viable solution to me.

**Comment by ptilopteri** [comment]
@HansBull 
completed apparently w/o error

tks
