### ISSUE TITLE
Additional metadata

### ISSUE THREAD

**Issue by JumpmanJunior** [darktable-org/darktable#7892]
**Is your feature request related to a problem? Please describe.**
In other software (e.g. Lightroom) much more metadata information is displayed for images. E.g. focus mode, exposure program, flash bias or metering mode. Darktable displays only a very limited amount of EXIF information like exposure or focal length. Especially no information form the EXIF maker notes is displayed. I like to see all these information so I can learn which settings work best with a specific camera in a specific situation.

**Describe the solution you'd like**
The best solution would be if I could define in the settings which information should be displayed in the "image information" section and below the images. Darktable uses Exiv2 which should have no problem in extracting these information. It is even already possible to select many of these information in the metadata exportation dialog, but unfortunately not for displaying them in darktable.

**Alternatives**
A simpler approach would be to add only some of the more useful but missing information in the image information section (like Lightroom does) without the possibility to individually configure them and choosing even the most obscure tag,

**Comment by paul-pw** [comment]
looks like someone already worked on this: #2819

**Comment by JumpmanJunior** [comment]
#2819 is indeed related but for a different use case and also much more complex. It is about a separate view for viewing and also editing metadata. This would not cover my use case where the additional metadata has to be displayed in the light table view so that I can e.g. quickly compare the data for the same picture I have taken several times with different settings. Switching to a different view would be almost as cumbersome as using different software to view the metadata.

**Comment by phweyland** [comment]
@wpferguson , some questions for you.
Lua could help to explore this subject.
As we have checked that lua can expand the list the of information displayed in image information module, we could try to find the way to display metadata information without the need to put everything in the image cache.
The steps I can see:
- read a metadata from blob (exif at least) if exists.
- create a variable $(VARIABLE) ??
- display in image information

What do you think ?
Apart the last step, is lua able today to execute the other steps ? What is missing ?

**Comment by wpferguson** [comment]
@phweyland we can do just about anything.  We can run exiftool or exiv2 against the image file and extract extra metadata and display it.  The only issue we might have is processing fast enough to keep up.

Here's a better example than the test script...
[hyperfocal.zip](https://github.com/darktable-org/darktable/files/5826612/hyperfocal.zip)

**Comment by phweyland** [comment]
> Here's a better example than the test script...
> [hyperfocal.zip](https://github.com/darktable-org/darktable/files/5826612/hyperfocal.zip)

Good starting point. That's a way.

If I provide a dt routine to retrieve whatever metadata, I guess to have also a lua API to access it, right ? Is that difficult to do ?

**Comment by wpferguson** [comment]
The issue with the above script is it only updates one piece of information, so if we duplicated it and changed the piece of information then for every additional piece of information we would add a run of exiftool, so it wont scale very well.  One way to get around that is to have a script that has a global variable that caches the exiftool result then multiple callbacks could access the global variable and just do a match for the piece of information they want.  The first callback could update the global variable since the callbacks run in the order they are registered.

> If I provide a dt routine to retrieve whatever metadata, I guess to have also a lua API to access it, right ? Is that difficult to do ?

If I was going to do it in core then I would probably catch the mouse-over-image-changed signal, then use exiv2 to read the file (since it's alreadly a library so you don't have to exec it), capture the output to a buffer, then use the lua api to extract the strings. To use the API you would have to establish a lua state, the load the lua standard libraries, push the match expression on the stack, push the buffer on the stack, push the string.match function on the stack, then pop the stack to do the match, then retrieve the result from the top of the stack.  Update the GUI and repeat.  Once you have the lua state set up and the libraries loaded the string matching/GUI updating could just be a loop.  Disclaimer: I've never done this so some of the details might not be correct. :)

**Comment by wpferguson** [comment]
I think this will work for the string match

```
lua_State *L = darktable.lua_state.state;
// you might need this, or they may already be loaded.  Uncomment if you get an error about 
// string.match not found
// luaL_openlibs(L);

lua_pcall(L, 0, 0, 0); // priming call, maybe needed, maybe not

lua_getglobal(L, "string.match");
lua_pushstring(L, buffer);
lua_pushstring(L, match_expression);
lua_pcall(L, 2, 1, 0); 
char *result = luaL_checkstring(L, -1); // get the result from the top of the stack
lua_pop(3); // pop the result and answer off of the stack, leaving string.match

```

**Comment by wpferguson** [comment]
In the meantime, @JumpmanJunior you can accomplish this using a lua script to extend darktable and add the additional metadata fields to the image information display

**Comment by phweyland** [comment]
@wpferguson Thanks to your example I've made work the same with exiv2. Cool !
I think exiv2 is more appropriate as dt use the same.

I'm now trying to set up a script able to read several parameters.
The idea, rustic, would be to set up a list of the metadata exiv2 keys at the beginning of the file.
The user could then update it as needed.
But I've forgotten everything about lua ... learning again :smiley:

**Comment by phweyland** [comment]
Maybe it would help add an index to register_info declaration to pass the index to callback...

**Comment by phweyland** [comment]
The exiv2 basic script:

```
local dt = require "darktable"
local df = require "lib/dtutils.file"

local exiv2 = df.check_if_bin_exists("exiv2")

if not exiv2 then
  dt.print("exiv2 not found")
  error("exiv2 not found, exiting...")
end

local content = ""

local function callback(image)
  local result = "-"
  
  local p = io.popen(exiv2 .. " -PEkt " .. image.path .. "/" .. image.filename)
  if p then
    local content = p:read("*all")
    local hfd = string.match(content, "Exif.Image.DateTimeOriginal%s+ (.-)\n")
    if hfd then
      result = hfd
    end
  end
  p:close()
  return result
end

dt.gui.libs.metadata_view.register_info(
  "color space", 
  callback
)

```

**Comment by wpferguson** [comment]
What we want is....

* a list of info (display name + exiv2 tag)
* that we can add to or remove from
* that we can display all, some, or none of in the image info display

So what we need...

* be able to add and update an item in the image info display - done
* be able to remove an item from the image info display - we need to create dt.gui.libs.metadata_view.destroy_info(name)
* gui to show selectable items to display
* ability to add and remove items from the list
* ability to update all the items in a reasonable amount of time (cache exiv2 output and feed multiple consumers)
* a way to figure out when to update the cache for all of the consumers (could hook mouse-over-image-changed and do it from that)

Does that pretty much sum it up?

I'll do the lua side if you take care of dt.gui.libs.metadata_view.destroy_info.  Hint: you can remove a value from the lua tables by setting the value to nil.  To test it you could use the script I sent you and add

```
dt.control.sleep(1000)
dt.gui.libs.metadata_view.destroy_info("hyperfocal distance")
```

**Comment by phweyland** [comment]
> Does that pretty much sum it up?

Sounds great.



>     * a way to figure out when to update the cache for all of the consumers (could hook mouse-over-image-changed and do it from that)

Can we detect that "image" has changed  ?

 

> I'll do the lua side if you take care of dt.gui.libs.metadata_view.destroy_info.

I'm not sure this is fair for you, but I'm happy to take this.

**Comment by phweyland** [comment]
even launching dt with -d lua, I don't get any of the dt.print() messages...

**Comment by wpferguson** [comment]
dt.print() goes to the UI, you want dt.print_log() or dt.print_error()

**Comment by wpferguson** [comment]
> Can we detect that "image" has changed ?

```
local function update_cache(evt, image)
  -- update the cache using exiv2
end

dt.register_event("mouse-over-image-changed", update_cache)
```

**Comment by phweyland** [comment]
> dt.print() goes to the UI, you want dt.print_log() or dt.print_error()

How things are simple when one knows ... :smiley: 

This script caches the exiv2 file and can be extended manually.
[exif_info.lua.txt](https://github.com/darktable-org/darktable/files/5832233/exif_info.lua.txt)

> gui to show selectable items to display

There is a list for metadata available in dt.
This list does appear in config export metadata (when one want ta add specific metatada (+)).
dt_exif_get_exiv2_taglist();
Just filter the ones starting by "Exif.".
Each element is a concatenated string => take the first element.
For the display name I thing we should stick with the standard exiv2 and display the last element of the key (at least at the beginning.

**Comment by phweyland** [comment]
Two points which came to me:
- the displayed name could be given by the user (not existing and unique)
- these selected metadata should be saved somewhere and given back at the next dt start.

**Comment by wpferguson** [comment]
It's done, it's late, and I'm going to bed....

User can specify name, saves and reloads on restart, including adding previously running metadata back into image information.  Need to write up some docs, then I'll send it to you

**Comment by phweyland** [comment]
Sounds great.
On my side I'm late. I want to take this opportunity to understand better the lua stack but it takes time ... Progressing.

**Comment by phweyland** [comment]
Case which would give an error: local copy (without access to original file ?).

**Comment by wpferguson** [comment]
Not sure, I'll try it....

For understanding the stack you can use the following:

 ```
 dt_lua_debug_stack_internal(L, __FUNCTION__, __LINE__);
  dt_lua_debug_table_internal(L, 1, __FUNCTION__, __LINE__);
```
the 1 in the table function is the position of the table on the stack.  debug stack prints out a list of whats on the stack and debug_table prints out what's in a table,

**Comment by phweyland** [comment]
Thanks, good to know !

**Comment by wpferguson** [comment]
Ran into a few bugs with the lua script, and maybe found a bug with the box widget... :frowning_face:

**Comment by wpferguson** [comment]
Not a box bug, brain bug...

**Comment by wpferguson** [comment]
@phweyland, here you go...  let me know if there are problems...
[metadata_manager.zip](https://github.com/darktable-org/darktable/files/5840500/metadata_manager.zip)

**Comment by JumpmanJunior** [comment]
I wanted to test this plugin but I get the error "exiv2 executable not found". I am using darktable on Windows, so exiv2 should be included, but probably has to be called differently in the script.

Two other suggestions:
Would it be possible to display a metadata tag selection like it is available in the metadata export dialog instead of the simple input field?
In addition to that it would be nice if you could assign multiple tags to one display name. There are many tags with the same meaning, e.g. Exif.Olympus.FlashBias, Exif.Olympus2.FlashBias, Exif.Panasonic.FlashBias, etc. but always only one can be present in an image. Or perhaps allowing wildcards for the tag selector.

**Comment by wpferguson** [comment]
Did you install exiv2?  The exiv2 that comes with darktable is included as
a library and compiled in.  The script requires the exiv2 executable that
is separate.  You can get it from https://www.exiv2.org/download.html

**Comment by JumpmanJunior** [comment]
I was assuming it is working with the integrated library. I have now downloaded exiv2 and put the exiv2.exe into the darktable bin directory. But it is still not working with the same error message. I also tried the directory where the luarc file is located. Do I have to put the file somewhere else? There is no Windows installer for exiv2.

**Comment by phweyland** [comment]
>  I have now downloaded exiv2 and put the exiv2.exe into the darktable bin directory.

Would I be wrong saying exiv2.exe should be in a PATH known by windows ?

**Comment by wpferguson** [comment]
You can put it at C:\Program Files\exiv2\exiv2.exe.  The program will find it there.

**Comment by wpferguson** [comment]
> In addition to that it would be nice if you could assign multiple tags to one display name. There are many tags with the same meaning, e.g. Exif.Olympus.FlashBias, Exif.Olympus2.FlashBias, Exif.Panasonic.FlashBias, etc. but always only one can be present in an image. Or perhaps allowing wildcards for the tag selector.

Changed the script to allow wildcards in the key so for example `Exif.*.FlashMode` (that's the one I tested) will work.

**Comment by JumpmanJunior** [comment]
I now did both recommendations: I moved exiv2.exe to C:\Program Files\exiv2\ and also added this directory to the Windows environment variable PATH. I am now able to execute exiv2 in cmd without being in a specific directory. But darktable (which was also restarted) still tells me "exiv2 executable not found".

**Comment by phweyland** [comment]
Huummm. Should not it be "exiv2.exe" on windows ?

**Comment by JumpmanJunior** [comment]
That's something I also tried without success. And in cmd I am also able to execute exiv2 without exe.

**Comment by wpferguson** [comment]
Are your scripts up to date?  check_if_bin_exists knows you are on windows and adds the .exe automatically.  It also should search your path and if it can't find it, it should search C:\Program Files\exiv2.  Open a command prompt and do the following:

C:\"Program Files\darktable\bin\darktable.exe" -d lua > log.txt

Post or send the log.txt and we'll see if that sheds any light.  If all else fails, you should be able to start tools/executable_manager, select exiv2 from the dropdown and then locate it in the file system.  You only have to do it once.  After that it's stored so that it's available later.

**Comment by JumpmanJunior** [comment]
I have installed the scripts this week. The [log.txt](https://github.com/darktable-org/darktable/files/5861302/log.txt) does not look very helpful to me. But using the executable_manager did the trick.

Unfortunately now there is a new problem:
```
Exif.Panasonic.FlashBias: Failed to open the file
Exiv2 exception in print action for file -:
Failed to read input data
```
In cmd I can open the file with exiv2 without problems.

Also I am using the metadata_manager version wpferguson  posted 4 days ago. Where can I get the new version with the wildcard support?

**Comment by wpferguson** [comment]
Here's the latest as of a minute ago.  Start darktable up, then delete all your metadata settings and recreate them since the settings have changed internally.

You can do wild card tags with Exif.*.<end of tag>, for example Exif.*.FlashMode

The logging level in the module is set to debug, so if you have a problem do a run saving to log.txt and I'll look at it.

**Comment by wpferguson** [comment]
@JumpmanJunior are you compiling darktable?  If so, are you generating the install target and installing it, or running it from inside the build environment?  If you are running from the build environment, the lua scripts aren't going to work correctly (specifically running external executables such as exiv2). The problem with running from the build environment is when the lua script tries to launch an executable it expects to talk to a windows shell, but instead it's talking to a bash shell and therefore the commands don't work as expected.

**Comment by JumpmanJunior** [comment]
With the newest version I do not get the "Failed to open the file" error message any more. But the selected metadata is still not appearing. I have attached the [log.txt](https://github.com/darktable-org/darktable/files/5863385/log.txt).

I am not compiling darktable myself. Darktable is installed with the official Windows installer.

If switching to a new photo or scrolling in the light table view a cmd window i appearing in front of darktable for a short period of time. I assume this is the execution of exiv2. Can this be done somehow in the background? The flashing cmd window is quite distracting.

**Comment by wpferguson** [comment]
The command window flashing is exiv2 running, and unfortunately windows insists on running all commands in a window.  I have an idea that might work to get around it, but it wouldn't happen until at least darktable 3.6.  The version of darktable I've been testing against is a development build.  I haven't tested against 3.4.  I'll try it and see what I get.
