### ISSUE TITLE
cannot set "by scale" in "export selected" 

### ISSUE THREAD

**Issue by ericscheidemantle-dreamworks** [darktable-org/darktable#7898]
I can select and export, setting the size using "in pixels/cm/in" but not set a scaling factor other than to "1" by middle mouse clicking.  The cursor does change into a text-entry style one (I-beam) but I cannot select, delete, type nor paste a value into the text field.

**To Reproduce**
1. With darktable open and in lighttable mode, select an image.
2. Expand the "export selected" module
3. Set the "set size" option to "by scale (for file)"
4. Try to modify the value

**Expected behavior**
I expect to be able to type in characters 0-9 plus a period for decimal values.

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: macOS High Sierra 10.13.6
 - 
- mac mini 6.2, Intel Core i7, Intel HD Graphics 4000

**Additional context**
- Occurs with JPG and RAW (NEF)
- Happens immediately after starting having done no editing.
- Happens with fresh import or older one.
- Occurs regardless of selected output format.

**Comment by kofa73** [comment]
With 3.5.0+655~g25887dd21 it works fine (the following are all accepted: 0.5 0,5 1/2). Kubuntu 20.10.

**Comment by MStraeten** [comment]
reproducible on osx with darktable 3.5.0+705~g76ea0bad0

**Comment by Nilvus** [comment]
Not reproducible on Linux. So if this work on Linux (like for @kofa73 and me) and not for both of you in OS X, so probably an OS X issue.

**Comment by ericscheidemantle-dreamworks** [comment]
Thanks, guys, for jumping on th.s

**Comment by johnny-bit** [comment]
Can you check if you can still reproduce? It should be normally working but OSX + gtk has it's own set of problems ;)

**Comment by MStraeten** [comment]
still reproducible in current master

**Comment by parafin** [comment]
I confirm. Also there's no text edit cursor when clicking on that widget (but mouse cursor does change, as noted in original report) compared to other working text entries. Looked at the code - no idea what's wrong. It behaves as if it is disabled...
