### ISSUE TITLE
Preset activates generic curve while camera model is available

### ISSUE THREAD

**Issue by jvangiel** [darktable-org/darktable#7913]
**Describe the bug**
Base curve is automatically activated when a new file is imported, however with wrong settings. My camera is a Nikon D800 and although this camera is available in de list of presets, the system selects the base curve "nikon like" instead of "Nikon D800"

**To Reproduce**
1. Import a picture (made with a Nikon D800) I tried to attach a picture, but RAW formats are 40+MB and Github doesn't accept files bigger than 10MB
2. Check the preset used in de module "base curve"

**Expected behavior**
When a more specific preset exists, the system should prefer that setting rather than the more generic setting
![Knipsel](https://user-images.githubusercontent.com/36278449/104854603-f1204880-5907-11eb-8248-6fb65fd044ad.PNG)

**Screenshots**
Find a screenshot of the preset and of the setting actual setting in de Base Curve.
![Basecurve](https://user-images.githubusercontent.com/36278449/104854617-0a28f980-5908-11eb-980a-d436eafa70a5.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10 Pro
 -  Yes
 - NVIDIA Quatro K610M, 25.21.14.2632

**Additional context**
 - Can you reproduce with another Darktable version?
 - Can you reproduce with a RAW or Jpeg or both? RAW
 - Are the steps above reproduce with a fresh edit (removing history)? Yes
 - Attach an XMP if this is necessary
[JVG_7996.NEF.zip](https://github.com/darktable-org/darktable/files/5826757/JVG_7996.NEF.zip)

 - Did you compile Darktable yourself? If so which compiler was used, with what options? No
 - Is the issue still present using an empty/new config-dir No idea how to clean Config.

**Comment by parafin** [comment]
edited the message, a lot of text was commented out, a good example why we should get rid of comments in the issue template

**Comment by parafin** [comment]
Check your processing preferences: https://www.darktable.org/usermanual/en/preferences-settings/processing/ - set "auto-apply per camera basecurve presets" to on and test with freshly imported image.

**Comment by jvangiel** [comment]
Thank you Parafin. This solved the problem.
