### ISSUE TITLE
Add OS and version in database/XMP

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#7920]
darktable assumptions have changed over the past and used to be hardcoded (for example, before 3.0, modules enabled by default and untouched by user didn't leave an entry in history). That triggers bad behaviours as the app moves on to a "path of fewest assumptions" and peculiarities should be handled.

I propose to add a DB entry as well as an XMP field to write explicitely with which version of darktable the image was originally created, then perhaps the last version used to modify it, as well as other technical information such as OS name and version. This way, we could trace the history of the file and handle it differently, in the code, depending on what's detected.

Of course, it's too late for most edits.

**Comment by criadoperez** [comment]
I think this is a great idea @aurelienpierre
