### ISSUE TITLE
Metadata editor: entries height is too high

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#7926]
**Describe the bug**
Entries height is too high in metadata editor. I've check all CSS and I see no margin or padding, so probably hardcoded. Seems to be recent. @phweyland: is this could be from some recent work on that area? Do you have an idea to fix that?

**To Reproduce**
Just click on metadata editor module to open it and see height of textview entries.

![2021-01-18_21-07](https://user-images.githubusercontent.com/45535283/104959331-49bc1800-59d2-11eb-953d-5bbd83e43764.png)

**Expected behavior**
Height should be by default the same as other entries in darktable.

**Platform (please complete the following information):**
 - Darktable Version: last master

**Comment by TurboGit** [comment]
Just a default maybe. You can set the height with ctrl-scroll and this will be saved across session.

**Comment by phweyland** [comment]
Hopefully Pascal is right ...

**Comment by Nilvus** [comment]
> Just a default maybe.

Euh, not sure to understand what you mean here. Or do you just mean that a default hardcoded height needs to be updated?

> You can set the height with ctrl-scroll and this will be saved across session.

I don't remember use it here, and certainly not on all entries but yes I reduce them all. Now, I see that some padding would be better inside (will propose that ASAP).

**Comment by Nilvus** [comment]
Forget last comment and sorry for the noise. Height is ok with an whole new config folder.
