### ISSUE TITLE
Leica D-Lux 7

### ISSUE THREAD

**Issue by GerardL32** [darktable-org/darktable#7931]
Hi,
I noticed that my camera (Leica D-Lux 7) is not yet supported by Darktable. I have uploaded a set of 4 RAW files (file type: RWL), uncompressed, of the same picture to the site https://discuss.pixls.us/t/raw-samples-wanted/5420.
I hope these files will help. If I did something wrong, please let me know what I should do to help you better.
Thank you very much for taking care of this issue.
Sincerely,
Gerard Lacoste

**Comment by LebedevRI** [comment]
Duplicate of #7588
