### ISSUE TITLE
corrupt files in darktable view

### ISSUE THREAD

**Issue by sladcolour** [darktable-org/darktable#7933]
**Describe the bug**

Hello,

I have a couple of corrupt files in my folder that I have imported into Darktable. I can see the icon in the lighttable view but it comes up as corrupted when I try and edit in darktable. Does anyone have any suggestions of how I can retrieve the RAW file?

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment]
If files are actually corrupted then we have nothing to work on. Darktable doesn't modify raws so it won't "heal them"

that being said - you need to provide those files for analysis for us to check them out if they are actually corrupted.

**Comment by sladcolour** [comment]
![IMG_0548](https://user-images.githubusercontent.com/77688081/105092278-f19c1900-5a98-11eb-97ae-939cbb65c8bd.JPG)

It's the RAW version of this file that is corrupt

**Comment by johnny-bit** [comment]
That's not the corrupted file, isn't it? There's no raw to be recovered from jpeg. Make sure the actual raw file is available for us to check. 

Additionally - we really need more info about the situation, you haven't even specifoed darktable version nor os...

**Comment by johnny-bit** [comment]
Well.. TBH - I doubt "corrupted" files are darktable's job, so I suggest to try https://discuss.pixls.us/ as that is a discussion forum which may help with all stuff digital imaging.
