### ISSUE TITLE
Problem exporting JPEGS

### ISSUE THREAD

**Issue by sladcolour** [darktable-org/darktable#7941]
Hi,
I am having trouble exporting JPEG files... I want the long side of both portraits and landscapes to be 30cm.
At the moment I am entering 30.01cm on long side with 150dpi but images are coming out at 300dpi and 15cm on long side. Not sure if this is quite the same thing, are my settings wrong?
Thanks in advance

**Comment by johnny-bit** [comment]
30cm in 150dpi = 15cm in 300dpi = 60cm in 75dpi = 7.5cm in 600dpi and image resolution stays the same :)

**Comment by sladcolour** [comment]
Thanks that's good to know.

Is there a way of achieving what I want (i.e. 30cm on long side & 150dpi) directly from Darkroom?

**Comment by ralfbrown** [comment]
https://www.webdesignerdepot.com/2010/02/the-myth-of-dpi/

**Comment by johnny-bit** [comment]
Well... Technically if you need to have "300dpi" said in your JPEG file, check out https://www.darktable.org/usermanual/en/module-reference/utility-modules/lighttable/export-selected/#including-metadata-in-the-exported-image and add exif tags XResolution and YResolution with formula "300".

**Comment by johnny-bit** [comment]
My bad...

Actually you can specify dpi using `metadata/resolution` in darktablerc

the fun part "could" be also setting that in export module...

**Comment by johnny-bit** [comment]
Turns out it was rather easy but rather hidden. #7946 would allow user to write dpi info into file.

**Comment by eslogan** [comment]
Hi, you can set the dpi value from GUI if you set export size in centimeters or inches.
