### ISSUE TITLE
Current Master Builds but wont run on Windows 10 Install

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#7950]
See attached log. I have deleted my entire darktable git  and re-cloned it. I did a fresh build from scratch from this. The issue of crashing on startup remains.
There seems to be a remnant as a result of trying a recent PR for the sigmoid module. I am not sure why it is still there or being called as I have refreshed everything. I have attempted to run DT  using no library ie memory for the database and in an alternate config directory which is empty so it should just create a new data.db and config files 
with no issues of interaction with a previous database. Perhaps someone has some insight on what might trigger this and where the reference to the now absent (removed) sigmoid module could be coming from...Any help appreciated.  

[darktable-log.txt](https://github.com/darktable-org/darktable/files/5850889/darktable-log.txt)

**Comment by Nilvus** [comment]
Just a thing you don't precise about having a really fresh install: did you also remove the install folder (ie where darktable is installed on your system)? I can't help more here as I don't use Windows but having something remnant with a fresh config folder and a fresh darktable git source, I don't see anything else.

**Comment by todd-prior** [comment]
> Just a thing you don't precise about having a really fresh install: did you also remove the install folder (ie where darktable is installed on your system)? I can't help more here as I don't use Windows but having something remnant with a fresh config folder and a fresh darktable git source, I don't see anything else.

Funny I was just coming online to close this ...I didn't think anything of importance was stored in the install directory. I thought the configdir was the most important and I had tried a completely fresh one. I did select the uninstall option that the Windows installer offers and but I was then using the same folder to install.   Well just as a last resort I tried to delete that folder use a completely new install folder and voila everything works again. I am curious as to what file in the install would have been the culprit but I don't need to worry about it...thanks had I not stumbled on to it you would have solved the issue.... thanks so much for your quick reply

**Comment by Nilvus** [comment]
> I am curious as to what file in the install would have been the culprit but I don't need to worry about it...thanks had I not stumbled on to it you would have solved the issue.... thanks so much for your quick reply

Probably a specific file used in the PR you test for sigmoid module, not used in master by now could cause the crash. A fresh new install folder is always recommended as if a file is removed, you will have issues like you had here. Good to read that this solve your issue.

**Comment by ralfbrown** [comment]
Processing modules are individual DLLs, and dt seems to load **all** of the DLLs in the folder containing them.
