### ISSUE TITLE
preserve color checker corner coordinates

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7953]
In color calibration, when using the feature "calibrate with a color checker" the four corners are reset to the initial state whenever the type of color checker is changed.

IMO it would be better to keep those constant, as the user might have selected the wrong type with Xrite pre/post 2014 or might change type by mistake.

**Comment by Mark-64** [comment]
...and if you agree on the change I could try to implement it

**Comment by aurelienpierre** [comment]
What happens when the picture ratio of the chart changes too ? Because that's what triggered the choice of always resetting.

**Comment by Mark-64** [comment]
Well, the idea is that setting corners first and then changing the chart type should produce the same effect as changing the chart type first and then manually re-adjusting corners, which is something the user can always do regardless of the chart aspect ratio, or am I wrong?
Also, I noticed that module reset button does not re-initialize corners and other parameters of the chart collapsible panel. Is that intentional because we want to keep chart parameters and only reset the channel mixer or everything should be reset instead?

**Comment by aurelienpierre** [comment]
> Well, the idea is that setting corners first and then changing the chart type should produce the same effect as changing the chart type first and then manually re-adjusting corners, which is something the user can always do regardless of the chart aspect ratio, or am I wrong?

Maybe. Anyway, it's only GUI code so that can be changed anytime in the future.

> Also, I noticed that module reset button does not re-initialize corners and other parameters of the chart collapsible panel. Is that intentional, because we want to keep chart parameters and only reset the channel mixer, or everything should be reset instead?

Yeah, I don't think resetting the parameters and resetting the profiling options should be tied together. If needed, a special reset button for profiling would be better.
