### ISSUE TITLE
Panasonic DC-G110

### ISSUE THREAD

**Issue by Typere** [darktable-org/darktable#7958]
Just uploaded 4 raw samples from my new camera (4:3, 3:2, 16:9 and 1:1) to raw.pixls.us with CC0 license.
It is not yet listed in the repository, but maybe this takes some time.
I would appreciate to see darktable supporting these raw files.

**Comment by LebedevRI** [comment]
Thank you for contributing the samples!

**Comment by LebedevRI** [comment]
My apologies for completely dragging this out :(
I seem to have completely dropped the ball on camera support for the last few months.
