### ISSUE TITLE
CMake: lensfun not found when using -DBUILD_MSYS2_INSTALL=ON

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7961]
In Windows, when using the option  -DBUILD_MSYS2_INSTALL=ON, the lensfun database folder under darktable/build/share/ is not created and therefore DT trows an error at runtime `[iop_lens]: could not load lensfun database` and the lens correection module does not work

**Comment by MStraeten** [comment]
thats ok, no need to copy lensfun there. to run darktable it's necessary to install it; it's documented in the instruction.
```
    Finally build and install darktable:
        $ mkdir build
        $ cd build
        $ cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/darktable ../.
        $ cmake --build .
        $ cmake --build . --target install

    After this darktable will be installed in /opt/darktable directory and can be started by typing /opt/darktable/bin/darktable.exe in MSYS2 MINGW64 terminal.

```
`cmake --build . --target install` collects the required stuff ...

**Comment by Mark-64** [comment]
Well, I guess I should have been more clear.
I have no problems in building ` --target install` and  `--taget package` under Windows.
However I am a contributor of the project and I am trying to help, within my limited knowledge, in testing, debugging and some small development. 
For that purpose  `-DBUILD_MSYS2_INSTALL=ON` is a very handy option to run the code in place (in a subfolder of the build folder) for testing without installing and especially avoiding to run Cmake's fixup_bundle utility which slows down the build process a lot under Windows.
