### ISSUE TITLE
some custom widget "icon flags" can be superceded by CSS

### ISSUE THREAD

**Issue by dtorop** [darktable-org/darktable#7968]
### Is your feature request related to a problem? Please describe.
Custom icons `GtkDarktableButton`, `GtkDarktableToggleButton`, `GtkDarktableThumbnailBtn`, `GtkDarktableIcon` take `icon_flags`:

https://github.com/darktable-org/darktable/blob/ad87231986fa519d2d30e49a8f6c11ab3e44d91c/src/dtgtk/paint.h#L26-L44

Some of these describe behavior which overlap with what is now theme-able via CSS. At first glance, some which could be implemented via CSS:

- `CPF_ACTIVE`
- `CPF_PRELIGHT`
- `CPF_IGNORE_FG_STATE`
- `CPF_BG_TRANSPARENT`
- `CPF_STYLE_FLAT`
- `CPF_STYLE_BOX`
- `CPF_DO_NOT_USE_BORDER`
- `CPF_CUSTOM_BG`
- `CPF_CUSTOM_FG`

In addition, the current code to implement these flags isn't always intutive:

https://github.com/darktable-org/darktable/blob/ad87231986fa519d2d30e49a8f6c11ab3e44d91c/src/dtgtk/togglebutton.c#L101-L115

A CSS implementation may be more clear, and allow for more interesting design choices.

#### Plan A (lower impact)
Keep these flags as is (e.g. API for custom widget creation is unchanged). In the widget draw code, set a CSS class depending on the icon flags. Write appropriate CSS for each class to make behavior equivalent to what we have now.

#### Plan B (higher impact)
Change the API for widget creation to drop these flags. Still use CSS classes to describe the various behaviors. Each `gui_init()` routine which creates widgets will need to set assign the appropriate class to each widget to get the right visual behavior. Will produce more verbose C init code with assumptions built in about varieties of display. CSS will be fairly succinct.

#### Plan C (CSS-centric)
Change the API for widget creation to drop these flags. Rely entirely on CSS selectors to assign the appropriate style to the widgets. May produce more verbose CSS, but all styling can be done without altering the C code. OTOH, if there are no clear CSS classes, this could lead to a variety of unharmonious widget styles.

### Alternatives
Leave things as is. Down side is that I think everyone gets confused about what `CPF_STYLE_FLAT` means, and there are still workarounds in CSS for limitations of current styling. But won't require a lot of working and mucking around in widget creation routines and CSS to build something which will be visually indistinguishable from what exists now.

It's also possible to start with Plan A (above) and move on to Plan B/C later, to do the work in stages.

### Additional context
This came up when thinking out how to style widgets for #7952.

I'd be happy to work on this, though I also think it's not a high priority -- more to clean up existing overlapping code and allow for more flexible styling choices in the future.

**Comment by Mark-64** [comment]
Yeah, last year I messed up quite a lot with buttons in DT, in order to improve the GUI aspect under Windows with HiDPI screens.
However the situation is still quite messy, as buttons are managed in three places:
```
button.c
togglebutton.c
thumbnail_btn.c
```
Dimensional properties (margins, padding), which were the ones causing inconsistency for HiDPI displays, have been already moved to css, so some paint flags like `CPF_DO_NOT_USE_BORDER` are not used anymore (but they still are in `thumbnail_btn.c`).
Other flags controlling the styling are still hadcoded in the code and moving those to css would be perhaps desirable, but it's a lot of work.

**Comment by dtorop** [comment]
@Mark-64 Good to know the background on this. It's a classic "technical debt" problem. As you write, lots of work to fix -- and risk of breaking things along the way...

One other angle of approach would be to go through the flags one by one (`CPF_DO_NOT_USE_BORDER` would then be a good one with which to start) and for each move all their functionality to CSS and then remove the flag.

>  However the situation is still quite messy, as buttons are managed in three places

I haven't looked deep into this, but it's a good observation. Not sure if this is a good thing or not!

**Comment by Nilvus** [comment]
> @Mark-64 Good to know the background on this. It's a classic "technical debt" problem. As you write, lots of work to fix -- and risk of breaking things along the way...
> 
> One other angle of approach would be to go through the flags one by one (`CPF_DO_NOT_USE_BORDER` would then be a good one with which to start) and for each move all their functionality to CSS and then remove the flag.

I'm on to have as many things as possible that can be set by CSS. Anyway, we maybe need to be careful. So as you suggest, go through them one by one is maybe the best way. We also need to be careful if all that changed, that we don't break anything in the UI but sure that we allow more easier tuning.

**Comment by dtorop** [comment]
> we maybe need to be careful

I think so. I think what will make this annoying work is that every widget which uses a particular flag will need to be examined before/after to make sure that it is still styled in the same way. It's probably worth the effort to get rid of two overlapping styling methods, but not a top priority.

**Comment by dtorop** [comment]
I'll work on this as time allows... Lower priority than other things, though...

**Comment by AlicVB** [comment]
I've not seen this one... but PR #11482 should fix this.
I've just kept the "state" flags (CPF_PRELIGHT, ...) as they are used in some cases inside paint routines. But everything else is now handled inside css...
