### ISSUE TITLE
DNG files generated by PixelShift2DNG are not recognized as valid RAW files

### ISSUE THREAD

**Issue by waldbaer59** [darktable-org/darktable#7970]
Pixel Shift RAW-files from Pentax (and Sony) are containers with a certain number of RAW shots in them (f.ex. 4 single RAW shots for a Pentax). Darktable cannot combine all these 4 to one picture with higher resolution. There is a software called "PixelShift2DNG" which combines all contained pictures and generates a DNG file with a single (resulting) shot in it. This can be processed further with a RAW converter. Unfortunately the resulting DNG is rejected by Darktable (which is the only program that complains; other converters accept it without any problem).

**To Reproduce**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - Arch Linux  5.10.9-arch1-1 #1 SMP PREEMPT
 -

**Comment by johnny-bit** [comment]
The created file most likely isn't "normal" in some way. Please follow [Raw Format Support](https://github.com/darktable-org/darktable/wiki/Camera-support#raw-format-support) guide. Without sample files we can neither see nor fix the issue.

**Comment by waldbaer59** [comment]
In the meantime I found out that files from the Pentax K-1 processed by PixelShift2DNG can be processed by Darktable flawlessly. So I think that the problem has to do with the K70 and it's files. Exiftool doesn't help here: it all seems okay. I can provide You sample files, but they cannot be attached her because of size. Would a dropbox link (or something other suitable) help?
Best regards
Stephan

**Comment by johnny-bit** [comment]
You have to upload them to raw.pixls.us and specify that those were created using pixelshift2dng software. I think you should upload both - working k1 ones and not working k70 ones.

@LebedevRI - would that be OK?

**Comment by LebedevRI** [comment]
Is there any correlation with the original file type?
I.e. do both DNG and PEF pixelshift raws from K1 work and don't work from k70?
