### ISSUE TITLE
Color Calibration, Color Mixer Mode. Green output Channel value of Zero causes image to got to black

### ISSUE THREAD

**Issue by vasto7** [darktable-org/darktable#7975]
![Screenshot (26)](https://user-images.githubusercontent.com/75090281/105613209-586a4c80-5d8f-11eb-9fb3-1be56f64a458.png)
![Screenshot (27)](https://user-images.githubusercontent.com/75090281/105613214-5bfdd380-5d8f-11eb-94af-3d57fc52d343.png)

**Describe the bug**

In the Color Calibration  Module, with Adaptations set to "None", In the Green Output channel, moving the Green Input slider to Zero or any none positive value causes the image to go black.  Additional combinations of negative Green Input and other combinations of Red Input and Blue input, also cause a black Image.  The behavior cannot be created in the Red or Blue Output channels no matter the combination of input sliders.

**To Reproduce**
1. Go to the Color Calibration Module.  
2. Set Adaptation to None. 
3. Click on the Green Output Channel.  
4. Set the Green Input slider to 0 or some negative value. 

**Expected behavior**

Expected behavior would be that the image change color (with zero green output), but not become black.

**Screenshots**

The first screen shot is with the input sliders in the default positions.  The 2nd slider is with the Green Input slider set to zero.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10
 - Yes
 - Radeon RX 5700

**Additional context**
I tried this on many files, and the behavior was consistent.

**Comment by johnny-bit** [comment]
The "bug" is fixed in current master with recent changes to Color Calibration. The fix is most likely to be present in 3.4.1.

**Comment by vasto7** [comment]
Thank you for the quick reply.
Regards.
