### ISSUE TITLE
Sony QX1 camera support

### ISSUE THREAD

**Issue by 0x53A** [darktable-org/darktable#7976]
The Sony QX1 is basically a Alpha 5000 sensor in a different body.

Lighttable shows a preview, but darktable then fails to open it with 

![image](https://user-images.githubusercontent.com/4236651/105614863-8ae66a80-5dcc-11eb-9f31-31303c5cd502.png)

![image](https://user-images.githubusercontent.com/4236651/105614848-70ac8c80-5dcc-11eb-9126-20335b2527dd.png)

I have uploaded one sample to https://raw.pixls.us. As far as I know there is no setting for compressed/uncompressed raw etc, but if you need further samples please just give me a note.

**Comment by LebedevRI** [comment]
Could you please contribute a more bright (something closer to daylight landscape) sample to RPU?

**Comment by 0x53A** [comment]
Its 11 PM here, so I'll upload an "outside" image tomorrow.

Thanks!

**Comment by 0x53A** [comment]
I went for a quick walk into the park yesterday, but it was a pretty gray day.

Would one of these be useable?

![image](https://user-images.githubusercontent.com/4236651/105675756-d478a780-5ee9-11eb-93e3-0c48c044ed3f.png)

Today it's even worse, cloudy and snowy.

**Comment by LebedevRI** [comment]
The last one (bottom right) i think.
Thank you!

**Comment by 0x53A** [comment]
alright, done.

**Comment by LebedevRI** [comment]
My apologies for completely dragging this out :(
I seem to have completely dropped the ball on camera support for the last few months.
