### ISSUE TITLE
Darkroom mode: Rejecting an image causes inconsistency between selected image and displayed image

### ISSUE THREAD

**Issue by Konzertheld** [darktable-org/darktable#7977]
**Describe the bug**
In darkroom mode, when "no rejected" filter is active, rejecting an image causes two problems:
1. when I click on the image in the main view and press R for reject, it is rejected and removed from the photo strip at the bottom and the focus of the photo strip is advanced to the next image but the displayed image is not changed (remains the photo I just rejected)
2. when I click on the active image in the strip and press R for reject, it is rejected and removed from the strip and **no** image is selected. The displayed image remains the one I just rejected as in the other case.
3. (when I reject an image by moving my mouse over its thumb in the strip and press R without clicking, everything works as expected: that image is rejected and after moving my mouse away, the selected and displayed image are not affected.)

**To Reproduce**
1. Go from lighttable to darkroom by double-clicking a single image
2. select "no rejected" filter
3. press R - in the initial state coming from lightroom, this will cause 1. from above

**Expected behavior**
I would expect the focus / selected image to advance to the next one as it already does and that photo to be loaded / displayed. I remember that this behaviour was present in earlier Darktable versions, that's why I consider this a bug.

**Additional findings**
In case 1, the focus of the next photo disappears when I Alt-Tab out of Darktable and back (for example, right after step 3 from the reproduction steps).

**Screenshots**
![darktable-focus](https://user-images.githubusercontent.com/505380/105619814-7919bd00-5df6-11eb-8739-f435502be556.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Manjaro Linux
 - OpenCL active
 - AMD Radeon RX 570

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? -> both
 - Are the steps above reproduce with a fresh edit (removing history)? -> yes, tried with a completely new folder that Darktable has never seen
 - Did you compile Darktable yourself? -> no
 - Is the issue still present using an empty/new config-dir -> yes

**Comment by AlicVB** [comment]
This is a design decision, discussed many times earlier.
To resume : 
1. darkroom isn't the place designed to do culling. Everything in this mode should be oriented towards developing.
2. removing the current image can cause more problem that it solves. Esp. one common problem is a wrong "R" press, which is easy considering the number of shortcuts one may have.
3. you still can go to next image by pressing space
4. rating change (including reject) with accels is notified by a msg to be sure the user is aware of it

**Comment by ptilopteri** [comment]
it has always to my memory been possible to "delete" images from within darkroom mode and I have utilized this "feature" greatly in the past eight or so years.

deleting the current image has and should advance selection and "active" image to the next image in the current working group/selection.

I have and do rely upon this workflow.

just saying

**Comment by Konzertheld** [comment]
@AlicVB I am aware of the previous tickets closed because of the design decision, though I never saw the original discussion. That's why I tried to outline problematic or wrong behaviour that exists in the current state.

I think some of the arguments do not work and I kindly ask you to read my thoughts so I can figure out if I still experience unintended behaviour.

1. Okay. That is the design decision I guess, so I will accept that.
2. I understand this point the way that the image should not be removed so I can revert rejecting it. This, however, does not work for me. If I press R, assumed accidentally, and then I press R again, the rejection is not reverted, instead, the next image is also rejected. This culminates when the image I rejected is the last one in the photo strip. Pressing R then will result in an empty photo strip and pressing R with the then empty photo strip actually reverts the rejection of the last photo - which it never does in other cases and which is not related to the photo actually shown.
3. That did not work for me when I  opened this issue, however, I deleted my darktable configuration folder and now it works.
4. No, it is not, for me (I think by accel you mean keyboard shortcut). I do not get any notification or any message displayed.

**Comment by AlicVB** [comment]
Aha... so point 2 and 4 bugs.
I can reproduce both (point 4 not always) so I should be able to fix them :)

**Comment by Konzertheld** [comment]
> Aha... so point 2 and 4 are bugs.
> I can reproduce both (point 4 not always) so I should be able to fix them :)

Thank you! :) Let me know if you need more information.

**Comment by AlicVB** [comment]
@Konzertheld : points 2 and 4 should be fixed in PR #7995 (both issues where due to the same thing in fact)
