### ISSUE TITLE
Crop & Rotate module re-activates itself / or: Crop & Rotate stays active as long as it is opened

### ISSUE THREAD

**Issue by Konzertheld** [darktable-org/darktable#7978]
**Describe the bug**
Deactivating the crop and rotate module does not disable it. The power button changes to off, but the title remains with that slightly lighter color that it has when a module is either activated or shown and the module is still active. The crop area selection does not disappear and the image is not cropped. Once I click into the image, the module is re-activated.

**To Reproduce**
1. Activate and expand the crop and rotate module by either clicking or using shortcuts
2. deactivate it by either clicking the power button or using the shortcut
3. You can still crop the image. In fact, you must. I noticed because in that state I can no longer move a zoomed image around because instead, the crop area is moved around.

**Expected behavior**
The module is deactivated and cropped to the selected area. The crop selection disappears.

**Additional notes**
- The faulty state disappears when the module is closed / hidden.
- I noticed that the part where the module title keeps its "highlighted" color also applies to other modules, but I could not reproduce the rest of the issue with the base curve module.

**Screenshots**
![crop-rotate](https://user-images.githubusercontent.com/505380/105620124-dd8a4b80-5df9-11eb-82f3-02994cf29176.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Manjaro Linux
 - OpenCL active
 - AMD Radeon RX 570

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? -> both
 - Are the steps above reproduce with a fresh edit (removing history)? -> yes, tried with a completely new folder that Darktable has never seen
 - Did you compile Darktable yourself? -> no
 - Is the issue still present using an empty/new config-dir -> yes

**Comment by ralfbrown** [comment]
C&R has behaved that way at least since I started using it with v1.4.  It's showing you the crop which _will be_ applied when turned on, just as base curve shows the curve which will be applied once it is turned on -- neither module resets its parameters just because you turned it off.  The difference is that C&R shows things on the main image rather than just inside the module.

**Comment by Konzertheld** [comment]
@ralfbrown, thank you for your reply. It does indeed make sense to view the availability of the crop area as the module showing its settings even if not active. I was pretty sure I did not have this behaviour in earlier versions but I cannot test. I have two remarks though and would like to hear thoughts on that.
1. I find it a bit unfortunate that the module activates itself once I use it in its half-active state. I tend to leave my modules opened in the sidebar because it doesn't hurt. In case of the C&R this means I cannot drag my photo around and I might accidentally crop it. I would like to see the crop area and crop handles disappear when the module is not active. This could be independent from the last cropped area being shown when the module is opened but inactive.
2. The behaviour of showing the crop area and handles seems to be somewhat inconsistent. When trying to figure out if my module behaved as expected, I wildly opened and closed and activated and deactivated it using shortcuts. It seems to get confused somewhen and begins to lose the crop area or not show the crop handles even if they were there before, leading to states as weird as "module active and opened but no crop handles shown". I'm going to try to reliably reproduce that but need sleep first.

**Comment by Nilvus** [comment]
@Konzertheld: this module is hard to maintain and will be replace to propose cleaner and better modules. A first part had been made and integrated in darktable 3.6 with a new crop module. Better use that module to crop than crop & rotate one. Other parts should be released in darktable 3.8. See that issue:  #8834

So I close this issue and suggest you to comment, if needed #8834. Thanks.
