### ISSUE TITLE
Mouse clicks in lighttable not selecting images

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#7985]
dt 3.5.0+812~g32048edb3-dirty   Ubuntu 18.04
Also other recent dt Master builds since 3.4

@AlicVB , raised as suggested following #7875

If I click an unselected image in lighttable, then it should become selected and the border should change. But it doesn't.

Various other selection mechanisms seem fine. Clicking "select all" works - all images light up. Similarly "select none" switches all off. Hovering over an image causes it to light up.  Double click invokes darktable.
If I select all then click in grey space i.e. not an image, then all are deselected, which is same as 3.4.

The 3.4 release does not have this click-select problem.

Pls note I build dt myself, I don't want anyone to waste time if this is something I've caused.  Here is the log of build 812 in case you want to check anything.  There are some errors in it, eg
`-- Performing Test C_COMPILER_UNDERSTANDS_-Wno-error=address-of-packed-member - Failed`
but stuff like this has been present for a long time.

From what I can see both "good" 3.4 and "bad" Master are using the same GTK, 3.22.30.

[DT build log 23Jan2021 B.txt](https://github.com/darktable-org/darktable/files/5862358/DT.build.log.23Jan2021.B.txt)

**Comment by johnny-bit** [comment]
Can't reproduce on 3.5.0+816~g6ecf808b9-dirty. selecting/deselectin etc via mouse clicks (and ctrl+click) etc work nicely.

**Comment by AlicVB** [comment]
I don't reproduce either...
some questions to be sure I've understood the issue : 
1. your are in lighttable filemanager mode
2. when you click on a thumbnail, it does nothing (no strange selection, or deselection)
3. when you hover thumb, their background are highlighted and in the metadata view panel, you have the right informations
4. when you double-click on an image, you open this image in darkroom
5. does the behavior change if you change the overlay type (star icon on the top toolbar)
6. is there some noticeable lag in the hover effect (background) when you move the mouse from a thumb to another
7. does click on stars in the overlay of the thumb works ?

That's all I can think about for instance... I'm not sure it will help me to solve this issue, but at least that will avoid evident problems...
I see you are compiling from source. If needed are you able to add some printf inside the code, to track down this ?
Thanks for your help !

**Comment by jbinpg** [comment]
I have seen this on my dt as well. If I click on the frame of the image, it is not selected. But if I click on the image itself, i.e. anywhere on the image but the border, it is selected. Has been like this for a long time. I just retrained myself to click on the middle of the image.

**Comment by RawConvert** [comment]
@AlicVB , interesting...!

    your are in lighttable filemanager mode
=> Yes
    when you click on a thumbnail, it does nothing (no strange selection, or deselection)
=> Correct
    when you hover thumb, their background are highlighted and in the metadata view panel, you have the right informations
=> Yes
    when you double-click on an image, you open this image in darkroom
=> Yes
    does the behaviour change if you change the overlay type (star icon on the top toolbar)
=> Aha! With the three permanent options, the image is now showing selected, i.e. working ok. But with the other options, bad.
    is there some noticeable lag in the hover effect (background) when you move the mouse from a thumb to another
=> Sometimes.  What happens is the mouse is over an image and it's lit up.  Move mouse to adjacent image and stop. New image never lights up. Now move mouse a little (same image).  It now lights up. So it's a bit like the mouse movement has been missed.
    does click on stars in the overlay of the thumb works ?
=> Yes

We could try some print commands perhaps, but hopefully the above might sort it!

Re. what @jbinpg says, yes just had a quick play and the fail-to-light-up is connected to whether mouse moving over border of image versus actual image within.

**Comment by AlicVB** [comment]
hmm...
@RawConvert : I *sort* of reproduce a bug, but not sure it's really yours : *sometimes* (seems to depends on mouse position) I can't select an image by clicking on it's border. But I always manage to do so if I click on the image itself... (afaiu, this is the case for @jbinpg ) are you in this situation too ?
Last, do you have some user defined css ?

**Comment by RawConvert** [comment]
oh fuck!  :)   Yes, selects ok if I click on the image itself.  Cripes, I must have got used to always clicking the border.  Just gone back to 3.4 - this does select just by clicking the border!  Also on Master the problem is not sometimes, it's always, my impression is that clicking the border never works.

**Comment by RawConvert** [comment]
And no CSS, wouldn't know how or why!

**Comment by AlicVB** [comment]
good news as I can reproduce then, and I *think* I know where it comes from... Down side is that I'll need to battle with gtk :)

**Comment by AlicVB** [comment]
@RawConvert : PR #7987 should fix it. Thanks for the report !

**Comment by Nilvus** [comment]
Was hard to understand where the issue was but glad to see it understood and fixed.

**Comment by RawConvert** [comment]
Yes, good result in the end!
