### ISSUE TITLE
centre image clicks not detected when color calibration active

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7990]
When the color calibration module is active (expanded and focused) it is no longer possible to switch back to lighttable by double-clicking on the centre image. It is also no longer possible to click and drag to pan a zoomed image.

Reproduced on current master (3.5.0+817~gba3ce374e) but not on v3.4. I suspect this is related to the color checker functionality.

**Comment by ralfbrown** [comment]
Confirmed.  It does look like mouse events are being intercepted for the color-checker overlay even when not displayed.

**Comment by Mark-64** [comment]
I have a possible fix, PR coming
