### ISSUE TITLE
Cannot open image Fujifilm X-T4 compressed RAW 

### ISSUE THREAD

**Issue by ultramango** [darktable-org/darktable#7997]
**Describe the bug**
While trying to open compressed RAW image using Fujifilm X-T4 there's a message that the raw couldn't be loaded.

**To Reproduce**
1. In camera set: in I.Q. (1) → RAW RECORDING → COMPRESSED.
2. Take a photo.
3. Import the image.
4. Open in Darktable.

**Expected behavior**
Image is opened correctly.

**Screenshots**
![Zaznaczenie_240](https://user-images.githubusercontent.com/3664139/105758662-c78e9f00-5f4f-11eb-8872-65df923908fc.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Arch Linux and Windows
 - OpenCL activated.
 - Graphics card: NVidia 1080, driver version: 460.32.03

**Additional context**
Support for Fujifilm X-T4 was added here: #4943 and should support compressed RAWs.

When I tried with other RAW formats (compressed lossless, uncompressed) images load correctly. Could there be a mistake in this comment: https://github.com/darktable-org/darktable/issues/4943#issuecomment-626617348 that "compressed" is not supported and not "compressed lossless"?

Example image that fails to load: https://www.dropbox.com/s/k79oc7w1622i2ly/20210125_0001.RAF?dl=0 (~25 MB, digital multimeter, serial numbers have been redacted)

Here's a log from console if that helps:
```
[rawspeed] (20210125_0001.RAF) rawspeed::FujiDecompressor::FujiDecompressor(const rawspeed::RawImage&, rawspeed::ByteStream), line 52: compressed RAF header check

(darktable:287515): GLib-GObject-WARNING **: 20:36:20.615: invalid unclassed pointer in cast to 'GtkDarktableExpander'

** (darktable:287515): CRITICAL **: 20:36:20.615: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed

(darktable:287515): GLib-GObject-WARNING **: 20:36:39.307: invalid unclassed pointer in cast to 'GtkDarktableExpander'

** (darktable:287515): CRITICAL **: 20:36:39.307: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed
[rawspeed] (20210125_0007.RAF) rawspeed::FujiDecompressor::FujiDecompressor(const rawspeed::RawImage&, rawspeed::ByteStream), line 52: compressed RAF header check
```

**Comment by johnny-bit** [comment]
Please follow https://github.com/darktable-org/darktable/wiki/Camera-support#raw-format-support and use new camera support.

make sure that the sample images for X-T4 RAW compressed files are on raw.pixls.us before opening new issue.

We need CC0 stamples to be able to test and asses compatibility problems at all times.

**Comment by ultramango** [comment]
Will do, thanks.

**Comment by kmilos** [comment]
Already on the list: https://github.com/darktable-org/rawspeed/issues/232

**Comment by johnny-bit** [comment]
Ah. thanks @kmilos !

@ultramango - there's no point to multiply issues. Once rawspeed gains support for lossly compressed fuji raws by miracle of coding, darktable gains that automagically. So I guess... be patient :) since other formats are supported in the mean time you should be able to use other formats your camera allows and use converter to convert lossly compressed to dngs that are supported in dt

Closing this. keep watch on rawspeed :)

**Comment by ultramango** [comment]
@johnny-bit : true (no ticket duplication). For the time being I'll just switch to lossless compression. Cheers.
