### ISSUE TITLE
Color reconstruction fails to be applied during export

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#8002]
**Describe the bug**

I had a photo which included a street lamp. I enabled `color reconstruction` module and disabled `highlight reconstruction`. It fixed the highlight quite well. However on exported image the correction was gone. It looked like the reconstruction module was turned off. Moreover re-opening the image in darktable I also didn't see modules effect. I had turn it off and on again for it to display correctly. It still didn't work with export though.

It is present both with OpenCL and CPU processing. Curiously both those pipelines produce slightly different results but that is probably caused by some other modules like `color correction` as I can see a slight change of tint between exported images.

**To Reproduce**
Regretfully, I can't reproduce it reliably. On another photo color reconstruction module was working as expected. Might again be some interaction of modules... I know it will be next to impossible to pinpoint the bug though.

**Screenshots**
![color](https://user-images.githubusercontent.com/16195733/105843274-c7d27d00-5fd7-11eb-8742-d4d369a93e63.jpg)

**Platform:**
 - Darktable Version: current HEAD: d50e30bf4cfb89383af419b06665a196d86a7df7
 - OS: Gentoo Linux
 - OpenCL activated
 - AMD Fury, amdgpu, ROCm 4

**Comment by tomaszg7** [comment]
The issue is still there.

**Comment by johnny-bit** [comment]
The biggest problem is:

> Regretfully, I can't reproduce it reliably. On another photo color reconstruction module was working as expected. Might again be some interaction of modules... I know it will be next to impossible to pinpoint the bug though.

So in order to actually pinpoint it we need both the image and xmp file.

**Comment by tomaszg7** [comment]
Here's the file: https://tomaszg.pl/dt/

**Comment by tomaszg7** [comment]
The issue is still there.

**Comment by Opendreas** [comment]
I have the same issue with one photo. I've changed a lot of settings but nothing seems to help.

Preview
![preview](https://user-images.githubusercontent.com/85139531/126212982-6edccd2c-a706-425e-bb34-b26c1acb0bb8.jpg)

Lighttable preview
![lighttable](https://user-images.githubusercontent.com/85139531/126213957-7c1d86a7-33b1-42ee-9f46-d71605853970.jpg)

Exported
![exported](https://user-images.githubusercontent.com/85139531/126212966-4b71444d-dbac-498f-8895-e2fda2ec3e5f.jpg)

KDE Neon
Darktable 3.6
OpenCL activated or deactivated

**Comment by johnny-bit** [comment]
@Opendreas - can you share both raw and xmp file? maybe even as playraw on discuss.pixls.us? it'd be better to play with the file, just as @tomaszg7 did (i'm still at loss at what's going on but more test data more better and maybe someone will pick the issue to fix it)

**Comment by Opendreas** [comment]
> @Opendreas - can you share both raw and xmp file? maybe even as playraw on discuss.pixls.us? it'd be better to play with the file, just as @tomaszg7 did (i'm still at loss at what's going on but more test data more better and maybe someone will pick the issue to fix it)

Here are both files
https://ufile.io/0q8ku36a
