### ISSUE TITLE
Watermark module spuriously turns on when cleaning up masks

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8003]
dt 3.4.0 xmas     Ubuntu 18.04

@ralfbrown recently explained how to get rid of orphaned masks clogging history by doing a right click in mask manager then "cleanup".  I noticed this bizarrely switches on Watermark!

To reproduce: load a single raw file, it goes to darktable.  Then click "quick access for applying any of your styles" (bottom left).
Choose style20 (this may be important).
Notice Watermark is off.
Go to mask manager, cleanup, see Watermark switch on.

Here is my Style20 (renamed to .TXT) -
[Style20.txt](https://github.com/darktable-org/darktable/files/5873764/Style20.txt)

**Comment by RawConvert** [comment]
Hello.......
In fact it looks like it turns on the module you were most recently using (but left turned off).
Happening just now with new Master build 3.5.0+947~gb47c0146e-dirty - turning on contrast equaliser.

**Comment by johnny-bit** [comment]
Huh. interesting - can reproduce using your style in `3.7.0+1~g05bdc45ac`

**Comment by RawConvert** [comment]
Phew, I'm not going mad!  Thanks for checking this out!
