### ISSUE TITLE
Extra space after the letter m on the titles in the Windows version of the keyboard shortcut window.

### ISSUE THREAD

**Issue by Neverest** [darktable-org/darktable#8006]
**Describe the bug**

In the windows version of darktable, if you go to the keyboard shortcut windows the titles that have an "m" have an extra space after that. Like, it says "m ouse actions" or "processing m odules" Seen it in the shortcut window of lightable, darkroom and map.

**To Reproduce**

1. Go to lightable/darkroom/map
2. Press the shortcut key window button (default is h)
3. See the titles that have an m like mouse actions, processing modules, utility modules

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/13340767/105885567-af666080-5fdf-11eb-9ae2-bbc5b50d7adb.png)

![image](https://user-images.githubusercontent.com/13340767/105886281-990cd480-5fe0-11eb-8577-0fcc3b7b10a0.png)

![image](https://user-images.githubusercontent.com/13340767/105886397-bfcb0b00-5fe0-11eb-98ad-5a56b0273cd1.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS:  Windows 10 64-bits
 -  OpenCL activated
 -  Nvidia Geforce GTX 1080 driver 27.21.14.5709

**Additional context**

**Comment by parafin** [comment]
It looks like a problem with font hinting. No idea how it's wired in Windows GTK.

**Comment by Nilvus** [comment]
@Neverest: could you precise which theme do you use? darktable default one or darktable-elegant-theme? Not sure here. And if darktable default one, what do you have if you change the font used by Windows? Is the space still there? As @parafin says, it's probably more an issue about font hinting and how it's rendered with Windows GTK. So probably not a darktable issue.

**Comment by Neverest** [comment]
> could you precise which theme do you use? darktable default one or darktable-elegant-theme?

Its the darktable default theme. I havent changed any font options in Windows overall. Maybe I changed the setting in darktable by mistake, but I dont see the dot signaling change. Here's my general tab settings:

![image](https://user-images.githubusercontent.com/13340767/106029107-2153ae00-60a3-11eb-9238-1ae08b9bba86.png)

**Comment by Mark-64** [comment]
I do not have the issue, with the same settings, nor with any other theme / font size combination.
@Neverest what happens if you select another theme, for example darktable-elegant-darker ?

**Comment by parafin** [comment]
Maybe some fonts need to be installed?..

**Comment by Mark-64** [comment]
it could be, although the default theme darktable.css uses only a plain sanf-serif, which should be present in every system, kind of.

I am more and more convinced that to get rid of those glitches, plus the weird font rendering pango issues in Win32 (see [https://gitlab.gnome.org/GNOME/pango/-/issues/525](url) for example) and reach GUI uniformity across OSs, we should bundle DT with a (FOSS) font set that is proven working in all cases.

**Comment by Neverest** [comment]
> 
> 
> I do not have the issue, with the same settings, nor with any other theme / font size combination.
> @Neverest what happens if you select another theme, for example darktable-elegant-darker ?

I tried darktable-elegant-darker, and it doesnt have the m problem, but I find it to be illegible:

![image](https://user-images.githubusercontent.com/13340767/106131749-74784000-6139-11eb-832e-2b2a68a945fa.png)

Tried to see it in darkroom with some old pic to see the UI:

![image](https://user-images.githubusercontent.com/13340767/106131983-bb663580-6139-11eb-89b8-2e29e5225457.png)

I also got the text get smaller and smaller every time I changed it. The tooltip was just a small rectangle with little ants lol. Couldn't replicate that again after restarting the program though.

This is on a 1920x1200 resolution just in case.

**Comment by Mark-64** [comment]
font hinting (a.k.a. ClearType in windows language) not correctly setup? 
Can you please type "clear type" in you Windows search box? An icon "Adjust ClearType Text control panel" should apper. Go through the few simple steps in the interactive procedure. That should improve the appearance of the fonts and eliminate jagged or blurry text.
If the text is too small, in darktable prefernces / general, you can try to deselect "use system font size" and manually set instead "font size in points" to you liking.

**Comment by Graycard** [comment]
I'm not seeing the problem at all on either of my Win 10 machines.

**Comment by Neverest** [comment]
> 
> 
> font hinting (a.k.a. ClearType in windows language) not correctly setup?
> Can you please type "clear type" in you Windows search box? An icon "Adjust ClearType Text control panel" should apper. Go through the few simple steps in the interactive procedure. That should improve the appearance of the fonts and eliminate jagged or blurry text.

Tried it, had no change in darktable.

> If the text is too small, in darktable prefernces / general, you can try to deselect "use system font size" and manually set instead "font size in points" to you liking.

Tried it, and it got better, but it still has that blurry look.

**Comment by Mark-64** [comment]
We have to check the installed fonts. Please do the following:

- open a command propt, by pressing `Win+R`, typing `cmd` and press `enter`
- type the command `dir c:\windows\fonts > fonts.txt`
- attach here the file `font.txt` created

**Comment by Neverest** [comment]
Here you go:

[fonts.txt](https://github.com/darktable-org/darktable/files/5890043/fonts.txt)

**Comment by Nilvus** [comment]
@Neverest to use elegant themes, you need to install Roboto fonts, that's why you have illegible text in elegant theme. See here: https://fonts.google.com/specimen/Roboto

**Comment by Mark-64** [comment]
It seems you miss some of the fonts I have.

1) for the default darktable.css theme, you need a good sans serif font. I have DejaVu and Liberation, you have none of the two. I suggest you install at least one of the two families (in .ttf format), better if both. You can find those for example from:
[https://dejavu-fonts.github.io/](url)
https://github.com/liberationfonts/liberation-fonts/releases

2) for the darktable-elegant themes @Nilvus is right, you get the best result installing Roboto, although I get almost as good results with the fallback SegoeUI family, which is installed by default in Windows and you do have of course. However the gtk3 font fallback feature in Windows is hit and miss, dependong on the version your darktable build is using. So I suggest to install Roboto

After that please report the result you get.

**Comment by Neverest** [comment]
Installed both dejavu- fonts and liberation-fonts. Seems the m problem on the default darktable theme is gone:

![image](https://user-images.githubusercontent.com/13340767/106270687-bc17ce00-6204-11eb-9a56-79a7bdba68c8.png)

And darktable-elegant-darker:

![image](https://user-images.githubusercontent.com/13340767/106270860-fb461f00-6204-11eb-9571-62af82f3d427.png)

![image](https://user-images.githubusercontent.com/13340767/106270900-0ac56800-6205-11eb-8db9-c8257ae1db5a.png)

Way better than what I was getting. Default seems to be a bit small, but I imagine that changing the font size will fix it for me. This one and the default theme use Deja Vu fonts right? I think I prefer the thicker ones from the default theme. Easier on my eyes, haha.

Don't know what version of GTK3 Windows 10 has, sorry.

**Comment by Mark-64** [comment]
Happy to hear it is going better.
The default theme "darktable" uses only a [sans serif](https://en.wikipedia.org/wiki/Sans-serif) font, and DejaVu or Liberation are two popular open source font sets which include a good looking sans serif.
darktable-elegant themes can use a variety of fonts, first choice being Roboto. And yes it is thinner. If you don't like it, then you don't need to install other fonts.

**Comment by Nilvus** [comment]
Glad to see that this issue is fixed. So I close it.
