### ISSUE TITLE
global color picker "restrict histogram to selection" doesnt affect waveform histogram

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#8008]
color picker checkbox "restrict histogram to selection" doesn't affect waveform histogram.
when standard histogram is active the histogram is reduced, but not if waveform (or vectorscope) histogram enabled

1. open image in darkroom
2. select an unicolor area with global color picker
3. enable checkbox "restrict histogram to selection" 
4. switch between standard and waveform histogram

**Expected behavior**
even waveform (and further) histogram mode should be supported

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.5.0+861~g5885bff7e-dirty 
 - OS: osx

**Comment by parafin** [comment]
But in case of a waveform how should it work on x axis? Empty space outside of picker selection?

**Comment by MStraeten** [comment]
no, the waveform in its whole width should represent the picker area

**Comment by MStraeten** [comment]
maybe its not that critical for the waveform histogram but it will be relevant for the vectorscope mode - there just the information contained in the picker area should be used and properly scaled

**Comment by dtorop** [comment]
Yes, thank you for mentioning. It's on my list of things to do already, but good to have it marked by this "issue". I don't think it's a hard change to do.

As @MStraeten writes, I think this is especially relevant for vectorscope. There would be a couple possible solutions:
- As above, only display the part of the image in colorpicker area, and scale to that area.
- Continue to display the scope for the entire image, but delimit the data in the colorpicker. This could be by giving it a different color or density.

The second possibility could be interesting partially just to investigate a vectorscope plot and understand which parts of the image end up in which parts of the plot, without the scope changing beyond recognition.

@johnny-bit: I'm happy if this gets assigned to me...

**Comment by TurboGit** [comment]
> there just the information contained in the picker area should be used and properly scaled

Scaled on the x-axis ? This will be very confusing I think.

**Comment by MStraeten** [comment]
Yes, but theres a conflict in waveform mode between getting as much information of the picker area (scaling) and keeping the context (cutting away outside areas) but with lower resolution.
