### ISSUE TITLE
Color calibration adaptation setting visible when it has no effect

### ISSUE THREAD

**Issue by paolodepetrillo** [darktable-org/darktable#8011]
Problem occurs in latest from master 3.5.0+838~g82a13a17b.

In color calibration, when the illuminant is set to "as shot in camera", the adaptation is automatically set to either linear Bradford or CAT16 within check_if_close_to_daylight().

The problem is that the adaptation combobox remains visible and can be changed, but changing it has no effect. If it has no effect it should be hidden like the other controls that aren't relevant to the selected illuminant. Also, when switching from "as shot in camera" to custom, the adaptation combobox does not change to the adaptation that had been used automatically for "as shot in camera".

To reproduce:
Enable color calibration and set illuminant to "as shot in camera".
Change adaptation to any setting and observe no change in image.
Change adaptation to none or XYZ and then change illuminant to custom. Observe that the adaptation combobox does not change.

Expected behavior:
When illuminant is set to "as shot in camera" the adaptation combobox is hidden.
When illuminant is then set to custom, the adaptation combobox reappears and is set to either linear Bradford or CAT16, depending on what had been automatically set based on the camera WB.

**Comment by jbinpg** [comment]
If you have not already viewed Aurelien Pierre's latest tutorial on Color Calibration module, I suggest you check it out. Explains a lot of its ins and outs and why "as shot" is in there:

https://www.reddit.com/r/DarkTable/comments/k9ndwj/aur%C3%A9lien_pierres_latest_video_darktable_34_new/

**Comment by paolodepetrillo** [comment]
Thanks, I see how it's intended to be used now.

I think something has changed since that video was made, maybe a regression. The as shot option is explained at 46:00. The video shows the adaptation combobox being hidden when the illumimant is set to as shot in camera, and reappearing when the illuminant is changed back to daylight. This no longer happens in the latest from master.

The video also explains that it should be possible to restore the camera WB without changing anything in the other tabs by setting illumimant to as shot in camera and then setting it to a different illuminant. This partially works because it sets the other parameters, but it leaves the adaptation unchanged rather than changing it to the adaptation that was selected automatically according to the camera WB.

I do think this needs to be fixed somehow. As it's implemented right now, with a couple accidental clicks the module can be put in a state where what it is actually doing does not match what the GUI says it is doing: if the illuminant is set to as shot in camera and then the adaptation is set to None, then the module will continue to perform chromatic adaptation even though the GUI says it is disabled. This shouldn't ever be possible even in the case of user error.

**Comment by paolodepetrillo** [comment]
I think this is the problem:

In 3798a3d2 the GUI was modified to leave the adaptation combobox visible and not override the adaptation, when the illuminant is changed to as shot in camera, allowing the user to specify the illuminant.

However, in [commit_params() line 2529](https://github.com/darktable-org/darktable/blob/master/src/iop/channelmixerrgb.c#L2529), if the illuminant is set to as shot in camera, the adaptation setting gets overridden, ignoring the combobox setting.

**Comment by paolodepetrillo** [comment]
The fix depends on the desired behavior when applying a preset with "as shot in camera".

If the desired behavior is that the adaptation is set to whatever adaptation was saved with the preset, then just changing &(d->adaptation) to NULL on line 2529 should fix the problem.

But if the desired behavior is that applying the "as shot in camera" preset also sets the adaptation automatically to either Bradford or CAT16 depending on check_if_close_to_daylight, then the fix would be more complicated.

**Comment by paolodepetrillo** [comment]
Now that CAT16 is always used for 'as shot in camera' (change in 6b6665e) the question in the previous comment no longer matters.

**Comment by paolodepetrillo** [comment]
Fixed by #8162
