### ISSUE TITLE
Crash on culling dynamic mode

### ISSUE THREAD

**Issue by jcreixell** [darktable-org/darktable#8019]
**Describe the bug**
In culling dynamic mode, filtering in the lighttable view "all excepted rejected" and rejecting the last image of a selection of images (or simply just entering culling mode with a single selected image and rejecting it) causes the app to crash.

**To Reproduce**

1. Go to 'lightable'
2. Select view -> "all except rejected"
3. Click on a single image
4. Press ctrl+X to enter dynamic culling mode
5. Reject the image
6. Darktable crashes

**Expected behavior**
No images are shown in the culling mode. The app does not crash.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Manjaro Linux (Kernel 5.10.10-1-MANJARO)
 - OpenCL activated
 - Nvidia GTX 1060 6GB (linux510-nvidia 460.32.03-9)

**Additional context**

In some cases crashes happen even when the app is re-opened once I click anywhere in the lightable, until culling mode is exited. Once exited, everything seems to work again.

I managed to reproduce it as well in regular (non dynamic) culling mode, but I don't have concrete steps to reproduce it consistently.

Here is a core dump: https://gist.github.com/jcreixell/08e8b30a9b99cd6c1e836dba4e599391

**Comment by AlicVB** [comment]
yes, this has already been reported and fixed in master. The fix should land in next point release too (3.4.1)
