### ISSUE TITLE
Database upgrade from 21 to 30 fails due to missing REGEXP function

### ISSUE THREAD

**Issue by porst17** [darktable-org/darktable#8020]
**Describe the bug**
I recently installed Darktable 3.4.0 and it is asking for a library upgrade from version 21 to 30, which fails with the following error messages:

```
$ /Applications/darktable.app/Contents/MacOS/darktable -d all
0.003625 application_directory: /Applications/darktable.app/Contents/MacOS
0.003770 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
0.003824 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
0.003867 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
0.004276 darktable.configdir: /Users/stussak/.config/darktable
0.004310 darktable.cachedir: /Users/stussak/.cache/darktable
0.004359 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
0.004409 darktable.tmpdir: /private/var/folders/nf/zxffjktd01v1lncj_1v7xj000000gn/T
[memory] at startup
[memory] max address space (vmpeak):         unknown
[memory] cur address space (vmsize):      4586188 kB
[memory] max used memory   (vmhwm ):         unknown
[memory] cur used memory   (vmrss ):        16552 kB
0.004484 new_xdg_data_dirs: (null)

(process:84605): GLib-GObject-CRITICAL **: 19:02:10.840: g_object_set: assertion 'G_IS_OBJECT (object)' failed
0,141031 [init sql] library: /Users/stussak/.config/darktable/library.db, data: /Users/stussak/.config/darktable/data.db
[init] can't rename h to history
[init]   error in view film_rolls_mod: no such function: REGEXP
[init] database `library.db' couldn't be upgraded from version 21 to 30. aborting
ERROR : cannot open database
```

**To Reproduce**
Try to upgrade the database from Darktable v3.2.1 to v3.4.0.

**Expected behavior**
The library upgrade proceeds without errors.

**Screenshots**

**Platform (please complete the following information):**
- Darktable Version: 3.4.0
 - OS: macOS 10.14.6
 - OpenCL is activated
 - Radeon Pro 560X 4 GB, Intel UHD Graphics 630 1536 MB

**Additional context**
- I installed darktable via the Homebrew cask (`brew install --cask darktable`)

**Comment by parafin** [comment]
So homebrew installs official DMG I think, so it's very strange - I think a lot of people went through this upgrade and nobody reported this issue. No idea what's happening here, maybe someone with sqlite knowledge can chime in.

**Comment by johnny-bit** [comment]
Oof... We'll have a problem. From sqlite manual: 

> The REGEXP operator is a special syntax for the regexp() user function. No regexp() user function is defined by default and so use of the REGEXP operator will normally result in an error message. If an application-defined SQL function named "regexp" is added at run-time, then the "X REGEXP Y" operator will be implemented as a call to "regexp(Y,X)".

So we'll have to check if regexp is defined and if not define it...

**Comment by porst17** [comment]
Is there any temporary workaround for this issue? Darktable is currently unusable for me because it just won't start and I have like 700+ photos to import, filter and edit.

**Comment by parafin** [comment]
What's even more strange - there's no usage of REGEXP anywhere in darktable sources. The error message about it comes from sqlite when trying to execute "ALTER TABLE h RENAME TO history". No idea how it's connected to REGEXP of film_rolls table.

As for workaround - just start from fresh DB - backup ~/.config/darktable/library.db somewhere and then delete it.

**Comment by porst17** [comment]
I suppose `library.db` is just a regular SQLite database. I can take a look in the DB later today (evening) and post my findings.

**Comment by parafin** [comment]
Yes, it's a sqlite DB. And the commands that seem to fail can be found here:
https://github.com/darktable-org/darktable/blob/88067a4e808891306a8db35e909dabb5c57fa084/src/common/database.c#L1366

**Comment by porst17** [comment]
Ok, I did a very quick check on the DB:
```
$ sqlite3 library.db .dump | grep REGEXP
CREATE VIEW film_rolls_with_date AS SELECT *, substr(replace(folder,'/Users/stussak/Pictures/RAW/',''),1,10) as yyyymmdd, substr(replace(folder,'/Users/stussak/Pictures/RAW/',''),1,7) as yyyymm, substr(replace(folder,'/Users/stussak/Pictures/RAW/',''),1,4) as yyyy FROM film_rolls WHERE folder REGEXP 'RAW/[0-9]{4}-[0-9]{2}-[0-9]{2}';
```
Maybe that's a custom film roll filter I created some time ago. But I can't really tell without actually opening darktable with the non-working DB.

**Comment by parafin** [comment]
It looks like some manual modification of DB on your part, it would also explain why nobody else has this problem. Try dropping that VIEW from DB.

**Comment by porst17** [comment]
I dropped that view and another one from the DB and the conversion proceeded without further errors or warnings.

It might be the case that I created the two views quite some time ago (years) when I re-organized my local folder structure. It seems it didn't cause any trouble until last week when the DB conversion was necessary.

Thanks for helping me fix my own problems.
