### ISSUE TITLE
RGB Curve: Colour shifting when setting a point on the curve.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#8024]
**Describe the bug**
When using the RGB curve module in *RGB independent channels* mode it can produce an ugly, unwanted colour shift when setting a point after moving the curve.

The order does seem to be important: First move the curve, then set the point. If you turn this around all seems to be working as expected.

It also looks like this only happens when moving the curve from the bottom left corner inwards and _not_ when moving the curve from the top right inward. For the latter the effect might be too subtle to notice though.

This was brought to my attention by a user on pixls.us: [RGB Curve…. Bug? DT 3.4](https://discuss.pixls.us/t/rgb-curve-bug-dt-3-4/23087)

**To Reproduce**
1. Open any ~~RAW/JPEG/PNG~~ image (*edit: all image formats show this*),
2. Activate the *rgb curve* module,
3. Select *RGB independent channels*,
4. Select a channel (doesn't matter which, all have the same behaviour),
5. Move the bottom left point(!!) of the curve inward,
6. create a point on the line.

Colour shift is now visible.

**Expected behaviour**
No colour shifting.

**Screenshot/Video**
Here's a visualization of the described behaviour:

https://user-images.githubusercontent.com/56407344/106236086-080e4700-61f4-11eb-8e1a-4c52103c6516.mp4

**Version**
* darktable version : Both 3.5.0+854 gd1f0242fa   and   3.4.0 

**Platform**

* OS                : Linux (kernel 5.9.15-1) (the pixls.us user uses Windows 10)
* Distro            : Debian Buster (rel. 10.7)
* Graphics driver   : nvidia (460.32.03)
* OpenCL installed  : Yes (nvidia-opencl-common 460.32.03-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 0.27.99.0
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by TurboGit** [comment]
I can reproduce !

**Comment by TurboGit** [comment]
Some more data this happens also in linked channel. And this happens only when middle-grey option is selected.

**Comment by jade-nl** [comment]
> also in linked channel
Yes it does. I did not pull the bottom left line far enough inwards before setting the point.

I'm also presuming now that this also happens when the top right is pulled inwards, it just isn't visible (or very, very hard to see).

**Comment by jade-nl** [comment]
Sorry! Pressed the wrong button by mistake!

**Comment by TurboGit** [comment]
And I'm not so sure it is an issue, most probably a feature. Until you add a point there is no middle grey compensation as we have only a black and white points set.

**Comment by TurboGit** [comment]
I do agree that it is "surprising" behavior though.

**Comment by jade-nl** [comment]
???

So setting the line before adding points is a no-no? I find that strange to be honest.

If this is "as designed" this has to be put in the documentation.

**Comment by TurboGit** [comment]
Yes, every points are adjusted when grey-point compensation is active. So when you place a middle point is it adjusted and even if the curve stays the same the actual (x, y) for each point are not the same and do not correspond to the curve. This is true only after first point is set, after it is not more visible.

**Comment by TurboGit** [comment]
Yes, maybe this should not be set by default.

**Comment by da-phil** [comment]
I also noticed this behaviour during a s-curve contrast enhancement and as soon as I chose "RGB, independent channels" the colours changed although all channels still had the same s-curve applied. This doesn't feel an expected behaviour or even "feature" :thinking:

**Comment by aurelienpierre** [comment]
One day, I hope people understand that tone curves inherently suck.

Also, dt tries to extrapolate the curve for out-of-range values, so when you clip the bottom of your range like this, I have no idea what the extrapolation is doing, but I don't trust it.

What you do here is called an RGB offset, go color balance for this.

**Comment by jade-nl** [comment]
@aurelienpierre: Did you answer the issue/suspicions made by Pascal?

* Is the way it behaves out-of-the-box as designed
* If so: Why is *compensate middle grey* turned on by default
* Why isn't any of this mentioned in the docs

**Comment by jade-nl** [comment]
This is still relevant and no one has this up.

More specifically: TurboGit's ideas about this not being a bug but a feature hasn't been confirmed or discarded. So to repeat what's already been said before:

* Is this a bug?
* If this is a feature, why is compensate middle grey turned on by default?
* Should the documentation be updated either way?

**Comment by TurboGit** [comment]
>     * Is this a bug?

Clearly no. I have looked at the code. This is not saying that the behavior is nice but not a bug. Can we do better? Probably, my current thinking is that we should have the _compensate middle grey_ off by default.

Now I'm open to any better solution.

**Comment by TurboGit** [comment]
I have added the milestone 3.6 to take a decision (whatever it is) for next release.

**Comment by phweyland** [comment]
I would vote to remove the middle grey compensation.
Even the doc is elusive about this.
