### ISSUE TITLE
dual demosaic crashes in Windows

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8025]
Testing the new dual demosaicing feature, and we have the usual Windows-only issue related to parallelization.
With current git master DT crashes by selecting either RCD+VNG4 or Amaze+VNG4

![Cattura](https://user-images.githubusercontent.com/43290988/106242033-54af4d80-6207-11eb-8c2e-29cde024e0da.JPG)

Backtrace attached
[darktable_bt_6YQZX0.txt](https://github.com/darktable-org/darktable/files/5892105/darktable_bt_6YQZX0.txt)

@jenshannoschwalm can you please have a look? Also @ralfbrown, you solved several similar issues recently

**Comment by ralfbrown** [comment]
Definite weirdness going on if that line is accessing address -1 in that first loop in `blend_images()`.

Ditch the multiple incremental variable updates and index directly off of the base pointer.  Since you're processing every element of the 2d array, you can also collapse the loops, to yield something like
```
  for(size_t k = 0; k < (size_t)width * height; k++)
  {
      luminance[k] =lab_f((rgb_data[4*k] + rgb_data[4*k+1] + rgb_data[4*k+2]) / 3.0f);
  }
```
(keep things simple and let the compiler do the optimizations, such as common subexpression elimination on the `4*k` and converting division to multiplication by the reciprocal, instead of trying to force them)

Also try changing `schedule(simd:static)` to plain `schedule(static)`, as I've seen  some issues when using simd:static together with the `simd` directive on a parallel for.

**Comment by jenshannoschwalm** [comment]
@Mark-64 can you also observe similar crashes for RDC only?

**Comment by jenshannoschwalm** [comment]
@ralfbrown you are right about re-writing the loop code but how should that explain the -1 ???

**Comment by Mark-64** [comment]
> 
> 
> @Mark-64 can you also observe similar crashes for RDC only?

No crash with RCD only

**Comment by Mark-64** [comment]
Triend to understand the issue, I was playing with the code and noticed that if I replace the call to lab_f() with another random functions, say fabfs() there is no crash.
Then I thought maybe the problem is in the called function, so I tried to unroll it like this

```
static void blend_images(float *const restrict rgb_data, float *const restrict blend, float *const restrict tmp, const int width, const int height, const float threshold, const gboolean dual_mask)
{
  float *const luminance = blend; // re-use this as temporary data
  const float epsilon = 216.0f / 24389.0f;
  const float kappa = 24389.0f / 27.0f;

#ifdef _OPENMP
  #pragma omp parallel for simd default(none) \
  dt_omp_firstprivate(luminance, rgb_data, width, height) \
  schedule(simd:static) aligned(luminance, rgb_data : 64) 
#endif
  for(int row = 0; row < height; row++)
  {
    for(int col = 0, idx = row * width, oidx = idx * 4; col < width; col++, idx++, oidx += 4)
    {
      float x = (0.3333333f * (rgb_data[oidx] + rgb_data[oidx + 1] + rgb_data[oidx + 2]));
      luminance[idx] = (x > epsilon) ? cbrta_halleyf(cbrt_5f(x), x) : (kappa * x + 16.0f) / 116.0f;
    }
  }
```

but now I get a weird compiler error

```
../../src/common/colorspaces_inline_conversions.h:182:8: error: 'f.820' is used uninitialized in this function [-Werror=uninitialized]
  182 |   *p = *p / 3 + 709921077;
      |        ^~
```

what's going on ?

**Comment by jenshannoschwalm** [comment]
I don't know either right now, as @ralfbrown pointed out, the code is not as good as it could be but seems to be correct for me and would be very surprised about a compiler error.

Any wrong redefinition in a header file? What about `cbrta_halleyf` and `cbrt_5f` definitions?

**Comment by ralfbrown** [comment]
> but now I get a weird compiler error
> 
> ```
> ../../src/common/colorspaces_inline_conversions.h:182:8: error: 'f.820' is used uninitialized in this function [-Werror=uninitialized]
>   182 |   *p = *p / 3 + 709921077;
>       |        ^~
> ```
> 
> what's going on ?

That code is using type punning to manipulate the bits of the floating-point number directly.  Looks like the compiler created a temporary `f.820` in cbrt_5f after allocating `x` to a register.

Try changing its code to 
```
static inline float cbrt_5f(float f)
{
   union { float f ; uint32_t i; } floatint;
   floatint.f = f;
   floatint.i = floatint.i / 3 + 709921077;
   return floatint.f;
}
```
That's not only much clearer to read, it also gets rid of the type punning which often generates compiler warnings.

**Comment by parafin** [comment]
Keep in mind that union trick is not valid (meaning undefined behaviour) in C++, though I think all compilers do actually handle it as intended.

**Comment by Mark-64** [comment]
Rewriting `cbrt_5f()` as proposed and unrolling the call to `lab_f()` as in my previous post compiles and runs withouth crash.
So what's the conclusion here? Does the compiler go crazy with too many nested function calls in a parallel loop?
Please note that already in #7273 the solution found was to avoid a function call...

Should I propose a PR with the above (and also the code optimization proposed by @ralfbrown) or do you want me to investigate further?

**Comment by Mark-64** [comment]
Oops, just saw the PR by @jenshannoschwalm, will test it

**Comment by jenshannoschwalm** [comment]
I just "googled" for nested inline functions and **that** seems **not** to be supported by all compilers and might have a nesting depth limit too. Could be the reason for this or more bugs i guess.

**Comment by ralfbrown** [comment]
> Keep in mind that union trick is not valid (meaning undefined behaviour) in C++, though I think all compilers do actually handle it as intended.

It's probably technically undefined behavior (certainly implementation-defined) in plain C as well, because it depends on the exact bit layout of floats and ints.  But I'm not aware of any systems in the past 20+ years which _don't_ use IEEE 754-style floating point numbers with the same endianness as ints.

**Comment by ralfbrown** [comment]
What normally happens is that the compiler just stops inlining and issues an actual function call on hitting either the nesting limit or a size limit of some kind (AST nodes, bytes, whatever).

**Comment by jenshannoschwalm** [comment]
Yes, is that standard? Maybe the nesting limit is different on windows/linux or gcc/clang?

**Comment by ralfbrown** [comment]
No doubt the nesting limit differs, but that should only affect speed (due to having function call overhead or not).  Changing the behavior depending on nesting depth is a compiler bug.

**Comment by parafin** [comment]
> > Keep in mind that union trick is not valid (meaning undefined behaviour) in C++, though I think all compilers do actually handle it as intended.
> 
> It's probably technically undefined behavior (certainly implementation-defined) in plain C as well, because it depends on the exact bit layout of floats and ints. But I'm not aware of any systems in the past 20+ years which _don't_ use IEEE 754-style floating point numbers with the same endianness as ints.

I was talking about type aliasing - in C it's valid to reinterpret float as int using this union trick - in C++ it isn't. What you are talking about is another question - but it's called implementation-defined I think, it's not undefined behaviour per se.

**Comment by ralfbrown** [comment]
Right, in C++ the idiomatic way is `reinterpret_cast<int>`.

**Comment by parafin** [comment]
No, there's no reinterpret_cast<int> and reinterpret_cast<int*> is bounded by the same aliasing rules. memcpy or std::bit_cast from C++20 are required. See end of notes here: https://en.cppreference.com/w/cpp/language/reinterpret_cast

Not sure if this is relevant at all in this case - are those headers used in cpp files?

**Comment by ralfbrown** [comment]
> Not sure if this is relevant at all in this case - are those headers used in cpp files?

It looks like colorspaces_inline_conversions.h is indirectly included from exif.cc, but that doesn't use any of the affected functions.
