### ISSUE TITLE
[duplicate manager] dt crashes {bisected, backtrace available}

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#8028]
**Describe the bug/issue**
Changing between one pic's version with duplicate manager make dt to crash

**To Reproduce**
1. Go to darkroom and chose a pic, which has duplicates already
2. Click on another duplicated version to make it the active one
3. See error

**Expected behavior**
no crash

**Which commit intruduced the error**

```
42cf826d502f83e1d13b728b94fe0c6541544aad is the first bad commit
commit 42cf826d502f83e1d13b728b94fe0c6541544aad
Author: phweyland <philippe.weyland@laposte.net>
Date:   Mon Jan 25 12:35:59 2021 -0300

    import: add tags presets combobox
    
    - import_metadata: align tags ui on metadata
    - import_metadata: update comboboxes on any presets change
    - import_metadata: code cleaning
    - libs: add presets change signal (init, new, update, delete)
    - metadata: remove init presets signal (as done above)
    - tagging: fix bug on set_params (only new tags were added)
    - tags: make _tag_get_tags() answer for imgid = -1 as well

 data/darktableconfig.xml.in |   7 +
 data/themes/darktable.css   |   5 +
 src/common/metadata.h       |   3 +-
 src/common/tags.c           |  31 +++--
 src/control/signal.c        |   9 +-
 src/control/signal.h        |   3 +
 src/gui/import_metadata.c   | 304 +++++++++++++++++++++++++++++++-------------
 src/gui/import_metadata.h   |   1 +
 src/libs/import.c           |  54 +++++---
 src/libs/lib.c              |  13 +-
 src/libs/metadata.c         |   1 -
 src/libs/tagging.c          |  41 ++++--
 12 files changed, 337 insertions(+), 135 deletions(-)
```

Find backtrace here:
[darktable_bt_BMZYX0.txt.zip](https://github.com/darktable-org/darktable/files/5895640/darktable_bt_BMZYX0.txt.zip)

**Platform**
* darktable version : 3.5.0+857~g2bdeea380
* OS                : Linux - kernel 5.10.2-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-460.27.04
* OpenCL installed  : Yes (opencl-headers-2020.06.16)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.10
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CMAKE_FLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "RelWithDebInfo"

**Comment by TurboGit** [comment]
I cannot reproduce ! Are you sure this is 100% reproducible ?

**Comment by AxelG-DE** [comment]
- for me unfortunately yes
- just rebooted and is still the same
- nothing helpful in the backtrace?
- any signs my library.db might be the culprit?

**Comment by jade-nl** [comment]
I've also been trying to reproduce and can't get it to crash either (neither any error/warnings in the console).

Thought it was just me.

**Comment by TurboGit** [comment]
You may want to clean your install dir:

`/home/gerber/.local/darktable/lib/darktable/plugins/lighttable/libmidi.so`

This is not part of master.

**Comment by AxelG-DE** [comment]
weirdo
I bisected twice with same result, thought that is good enough for reproducing

**Comment by AxelG-DE** [comment]
> You may want to clean your install dir:
> 
> `/home/gerber/.local/darktable/lib/darktable/plugins/lighttable/libmidi.so`
> 
> This is not part of master.

I will try, but that was in during bisecting all the time. Is from #6830

**Comment by AxelG-DE** [comment]
BINGO
sorry for the noise
