### ISSUE TITLE
modern chromatic adaptation clashes with HDR DNG

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#8043]
The defaults settings for colorin.c, upon which the ones of temperature.c and channelmixerrgb.c depend for the white balance, always use the embedded color profile for DNG files. This was changed last december to properly support DNG files. Previously, if available, colorin.c would default to the standard matrix if available first.

When darktable creates an HDR by merging pictures, it doesn't embed the input profile in the resulting DNG. When opening the DNG, the white balance is off, as well as the input profile.

To do :
force the DNG merging to copy and embed the white balance coeffs and the input profile, from the source images, then deal with DNG in an uniform way.

**Comment by da-phil** [comment]
Oh, that's the behaviour I've been witnessing too for some time, I'm glad you already identified the problem ;)
