### ISSUE TITLE
Whitebalance presets for Fujifilm X100V

### ISSUE THREAD

**Issue by FXTC666** [darktable-org/darktable#8048]
Here are the properly finetuned whitebalance presets for the Fujifilm X100V.

Cheers Sven

[darktable-whitebalance-fujix100v.tar.gz](https://github.com/darktable-org/darktable/files/5899885/darktable-whitebalance-fujix100v.tar.gz)

**Comment by t3mujin** [comment]
Thanks, but there's an already submitted and merged patch pull request just for that: 
#8035  

Feel free to pull the latest sources and test it.

**Comment by FXTC666** [comment]
> Thanks, but there's an already submitted and merged patch pull request just for that:
> #8035
> 
> Feel free to pull the latest sources and test it.

Thanks for the info! I missed the submit, sorry. I have tested the whitebalance presets now, it works fine with the X100V!
