### ISSUE TITLE
"Corrupt" images when pasting styles

### ISSUE THREAD

**Issue by mvrvelous** [darktable-org/darktable#8049]
Hi! Big fan of darktable here. Having an issue with copying/pasting styles. I have searched already but couldn't find anything.

As you can see some images (first of selection, 2 in the middle and 1 on the right) are fine. But it happens 80% of the time. Especially when selecting a lot of images.

Any idea what the problem is? Switching modes, restarting darktable, disabling and enabling modules again, none of them work. If I play around with the modules the "corruption" changes.

It's 3.4. I'm on Windows 10 and these are all .cr2 files. I've had this problem with the 3.2 too.

![dt](https://user-images.githubusercontent.com/4885001/106392143-d4e4d700-63f0-11eb-9d28-558da7f454f0.jpg)

It really slows down my work, because I have to remove the styles and then paste it on each image, instead of once for all. And then it's still the question it won't "corrupt" the next time, and the next time, the next time and so on.

**Comment by ralfbrown** [comment]
Does your style include multiple instances of a module?  There was a recent fix to a problem where multi-instances caused that kind of corrupt processing.

If it's possible for you to install a "nightly" build or build dt yourself, can you try with the current development version?  (Be sure to back up your database first, as there have been changes to the db format and the released version won't be able to read the database anymore after you run dev.)

**Comment by mvrvelous** [comment]
> 
> 
> Does your style include multiple instances of a module? There was a recent fix to a problem where multi-instances caused that kind of corrupt processing.
> 
> If it's possible for you to install a "nightly" build or build dt yourself, can you try with the current development version? (Be sure to back up your database first, as there have been changes to the db format and the released version won't be able to read the database anymore after you run dev.)

Hmm yes I guess that's the problem. Still weird it doesn't happen to all images. I guess this could be closed then? Up to the moderators.

**Comment by Nilvus** [comment]
> Hmm yes I guess that's the problem. Still weird it doesn't happen to all images. I guess this could be closed then? Up to the moderators.

Yes, I will close it. About your issue, it's always when having multi-instances of a module. It results in an old bug (fixed) that corrupt the history recorded in xmp and let that strange view appear. The workaround to apply correctly your history is to clone the image with the history. The clone should display correctly your history. Then you could remove the original corrupted one.
