### ISSUE TITLE
darktable 3.6 Lua roadmap

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#8052]
This is the current plan for the Lua API for darktable 3.6.  It's based on 3.6  being released in December, so if that changes this will too.

* API changed to 6.2.0

* password storage and retrieval - added _darktable.password.save()_ and _darktable.password.get()_ to save and retrieve passwords using the darktable password storage back end.

* widget naming - widgets now have a name field, making it possible to style them using CSS

* _darktable.gui.libs.visibility_ is fixed so setting a lib to hidden (false) removes it from the user interface.

* preferences - added _darktable.preferences.destroy()_ to remove a preference.  Added _darktable.preferences.get_keys()_ to return a sorted table of all of the preferences for both darktable and lua.

* get image from database by image id - added _darktable.database.get_image()_ to retrieve an image by the image ID

* _darktable.gui.libs.metadata_view.destroy_info()_ - function added to remove field added by _darktable.gui.libs.metadata_view.register_info()_ from the image information display.  Thanks @phweyland

_**-> git master is currently here**_

**The next three API versions have script breaking changes.  Prior to submitting them the lua-scripts repository will be updated to check the API version and supply the proper arguments for the functions in any affected scripts.  API 6.1.0 compatibility will be maintained until darktable 3.8 (or 4.0 if there isn't a 3.8) is released.**

* API change to 6.2.1 - **SCRIPT BREAKING CHANGE**

* event naming - add a name field to _darktable.register_event()_ so that multiple events of the same type can differentiated and the desired one selected and accessed.

* event destruction - _added darktable.destroy_event()_ to remove an event.

* API change to 6.2.2 - **SCRIPT BREAKING CHANGE**

* add _selection-changed_ to the lua events so that scripts can respond when the selection changes

* selection naming - add a name field to _darktable.gui.libs.select.register_selection()_ so that the selection can be selected and manipulated after creation

* selection destruction - add _darktable.gui.libs.select.destroy_selection()_ to remove an selection button from the user interface.

* selection sensitivity - add _darktable.gui.libs.select.set_selection_sensitive()_ to set selection button sensitivity

* API change to 6.2.3 - **SCRIPT BREAKING CHANGE**

* action naming  - add a name field to _darktable.gui.libs.image.register_action()_ so that the action can be selected and manipulated after creation

* action destruction - add _darktable.gui.libs.image.destroy_action()_ to remove a lua created action button from the user interface.

* action sensitivity - add _darktable.gui.libs.image.set_action_sensitive()_ to set action button sensitivity

* API change to 6.2.4

* storage destruction - add _darktable.destroy_storage()_ to remove a lua created storage from the exporter

_**-> development is currently here**_

* API change to 6.2.5

* guide destruction - add _darktable.guides.destroy_guide()_ to remove a lua created guide from the crop and rotate module

* API change to 6.2.6

* lib destruction - _add darktable.destroy_lib()_ to remove a lua created lib from the user interface.

__At this point script_manager should be able to stop a script and remove it from the user interface instead of just marking it to not start the next time darktable is started. The script can also be restarted if desired.__

* API change to 6.3.0

* API test suite - Develop an API test suite to verify the API after code changes.  Ideally it will be automated and can be added to the CI tests.  It may or may not cause an API increment.  It's really needed for the move to Lua 5.4.

**Changing to Lua 5.4 may cause changes to the C API code.  So far no problems have been encountered.**

* API change to 6.4.0 - **POSSIBLE SCRIPT BREAKING CHANGE**

* Move to Lua 5.4 - At this point the target is June.  That will depend on creating the API test suite and whatever problems it finds.

* API change to 7.0.0 for darktable 3.6 release due to the multiple API breaking changes introduced

**Comment by TurboGit** [comment]
@wpferguson : What is the status of this? Should it be closed now ?

**Comment by wpferguson** [comment]
@TurboGit I will take care of this today.

**Comment by wpferguson** [comment]
Remaining open items have been moved to #9165
