### ISSUE TITLE
Seeing black (top) and pink(bottom) line at edges of the imported image.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8055]
Seeing black and pink line at edges of the imported raw image. 

Current master darktable 3.5.0+891~gc672080f5
WSL Ubuntu 20.04

![image](https://user-images.githubusercontent.com/1119439/106403862-97b33000-6456-11eb-8cf3-b9f481d60233.png)

**Comment by jenshannoschwalm** [comment]
@johnny-bit i think this has been fixed lately with the thumbnail size&alignment corrections in #9117 and other ps's related.

**Comment by johnny-bit** [comment]
I assume you're right

@chhil - i'm closing this now, but if the problems persist on current master then we'll need more details & samples for us to re-open and start investigating.
