### ISSUE TITLE
Focus peaking shows weird heat map in filmstrip thumbnail

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8057]
Current master  darktable 3.5.0+897~g88067a4e8
WSL Ubuntu
Focus peaking shows weird heat map in filmstrip thumbnail

![image](https://user-images.githubusercontent.com/1119439/106405713-2c209100-645d-11eb-9592-77f000b2a17d.png)

**Comment by ralfbrown** [comment]
Not seeing anything unusual here.

**Comment by chhil** [comment]
When scrolling happens and the images slide in from the right, some images get the yellow heat map. Which also disappear as scrolling continues.

**Comment by chhil** [comment]
![image](https://user-images.githubusercontent.com/1119439/106416782-39974480-6478-11eb-8fad-7785f3dbfb6c.png)

**Comment by ptilopteri** [comment]
looks like your cache is bad

**Comment by chhil** [comment]
I did a clean import of the same set of images on a windows dt install.


This is lighttable filemanager layout.
Something is surely off. In this case I have not run cache generate. On the linux system I did have the cache generate run so I do think the cache may not be the issue and the focus peaking has some issue.

![image](https://user-images.githubusercontent.com/1119439/106491554-fcb16900-64dc-11eb-9af8-0f0e8e93dcc8.png)

**Comment by ptilopteri** [comment]
why would focus peaking affect images (thumbnails) from cache?
I would surmise the cache is generated from the imported image prior 
to initiating "focus peaking"
note that the cache is generated by dt and it is not necessary to
*specifically* generate the cache, at least my experience on linux.
windows or mac may be completely different.

**Comment by mchhil** [comment]
I have shown examples on both unix and windows with clean environments, fresh imports.

Focus peaking is an overlay on the thumbnails, hence I feel the calculations are off there.

**Comment by aurelienpierre** [comment]
Focus peaking does frequency analysis. This is scale dependent and it's impossible to get the same output for different scales.

**Comment by ralfbrown** [comment]
#9541 is likely to have fixed this.  Please give current master a try.
