### ISSUE TITLE
Add a new preserve chrominance option for filmic, rgb curve and rgb levels

### ISSUE THREAD

**Issue by age1988** [darktable-org/darktable#8061]
The new option would be just a desaturation before filmic, curves or levels, followed by a re-saturation.

Basically it's  implemented already in this pull request [https://github.com/darktable-org/darktable/pull/7820/commits/588ff0d2e36aa96ed196c65fc84b6a633fcc4b30](url)
`

    // Desature a bit to get proper roll off to white in highlights
    // This is taken from the ACES RRT implementation
    const float luma = rgb_luma(in + k, work_profile);
    for(size_t c = 0; c < 3; c++)
       {
       const float desat = fmaxf(luma + 0.92f * (in[k + c] - luma), 0.0f);
        }

`
Good values for the desaturation are from 0.90f to 0.96f, 0.92 is a good compromise.

After the image has to be resaturated 
`

    // Resaturate the image
    
    const float luma = rgb_luma(in + k, work_profile);
    for(size_t c = 0; c < 3; c++)
       {
       const float desat = fmaxf(luma + (1.0f / 0.92f )* (in[k + c] - luma), 0.0f);
        }

`
Luma could be just the "intensity", luma=(r+g+b)/3

Why ?
It preserve very well colors
[https://discuss.pixls.us/t/new-sigmoid-scene-to-display-mapping/22635/45](url)
Original
![1a50b40e5b3ce2722603901021ddbe75e4519c69](https://user-images.githubusercontent.com/24456323/106513585-73496900-64d3-11eb-9c31-ba0bab522480.jpeg)

This method
![985d2db9521a038097430ce9e6cd9b184e233090](https://user-images.githubusercontent.com/24456323/106513628-82c8b200-64d3-11eb-9452-f354b8774a47.jpeg)

Actually filmic
![test_pattern008639_01](https://user-images.githubusercontent.com/24456323/106513687-8fe5a100-64d3-11eb-8c67-5d4b33ddb164.jpg)

again filmic with extreme desaturation
![DSC_8411](https://user-images.githubusercontent.com/24456323/106513791-b3105080-64d3-11eb-9f19-0b7dbc16fdfd.jpg)

the new method
![DSC_8411pf1](https://user-images.githubusercontent.com/24456323/106513881-d3400f80-64d3-11eb-9368-b9a7744bb1d3.jpg)

**Comment by Nilvus** [comment]
@aurelienpierre

**Comment by aurelienpierre** [comment]
I don't understand what I'm looking at.

1. The first reference image shows continuous color bands. How do we get rectangles appearing in all the outputs ? Where do they come from ? What are they supposed to represent ?
2. Synthetic charts of primaries at 100% and secondaries around the same don't model natural images well, unless you take pictures of light bulbs with color filters on them. So, while they can illustrate and help understanding what's going on inside the algo, they are not a design goal. Or provide me a RAW file with pixels where G = 1 while R = B = 0.
3. The desaturation algo is not hue-linear and applying hard-coded desaturation that users cannot bypass or change is wrong. It's just black magic that works until it doesn't.
4. There is suspicious rat-piss yellow on the highlights of the wood floor in the second picture that may indicate gamut escape.

**Comment by age1988** [comment]
The solution could be to expose the saturation parameter to the user.
This method is used in aces rrt and it's recommended in [itu bt.2446](https://www.itu.int/dms_pub/itu-r/opb/rep/R-REP-BT.2446-2019-PDF-E.pdf) at pag 18 and 21( with a crosstalk matrix and the inverse crosstalk matrix) 
Some benefits of this method are better hue preserving, less saturation when a color is darkened, less color noise when a color is brightened, overall very similar to pure rgb curve.
For these reasons I propose to use it for levels and (tone and base) curve too.


> applying hard-coded desaturation that users cannot bypass or change is wrong. It's just black magic that works until it doesn't.
There is suspicious rat-piss yellow on the highlights of the wood floor in the second picture that may indicate gamut escape.


It would be great to extend this philosophy to filmic too, it's a creative decision of the user to render a color full white or preserve the hue, now is forced to choose the full white highlights.

**Comment by aurelienpierre** [comment]
It's not better at hue preserving since there is no chromaticity check of any sort. Processing RGB channels separately is not hue-preserving. This is what ACES and the ITU BT 2446 norm suggest because it's computationaly efficient to render 30/60 fps on limited end-user hardware. We don't deal with the same limitations here.

That's another hacky way to solve a well defined problem : massage pixel energy while retaining color ratios.

**Comment by age1988** [comment]
Yes this only minimize the hue shift, however it looks really good and i think it is worth to give this method a try, at least like a variation over the simple rgb.

**Comment by aurelienpierre** [comment]
Closing. The proposed option is not chrominance-preserving but hacking its way into hiding some of the chrominance shi(f)t.
