### ISSUE TITLE
Serbian translation of Darktable

### ISSUE THREAD

**Issue by gpopac** [darktable-org/darktable#8064]
Hello,

I have just finished Serbian translation of Darktable, and you can find
it attached along this email. Note that we have both cyrilic and latin
translations. Just rename ".txt" to ".po" (github does not like po files).

PS. I am the coordinator of Gnome translations and have already
translated GIMP in my language.

Best,
Miloš

[sr.txt](https://github.com/darktable-org/darktable/files/5907078/sr.txt)
[sr@latin.txt](https://github.com/darktable-org/darktable/files/5907079/sr%40latin.txt)

**Comment by TurboGit** [comment]
@gpopac : Thanks ! One question, which translation should be integrated ? The Cyrillic one or the Latin-1 ?

**Comment by kmilos** [comment]
Both please

**Comment by TurboGit** [comment]
Ok, but then what are the Serbian code (file base name?) to be used. I suppose we can differentiate both using some kind of suffix ? sr_???.po ?

**Comment by kmilos** [comment]
As above, `sr.po` and `sr@latin.po`

**Comment by gpopac** [comment]
I am a bit late, but Miloš has already replied. Cyrilic = sr.po and Latin = sr@latin.po, and we need both of them.
