### ISSUE TITLE
double free or corruption (!pre) - tone equalizer with guided filter

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8066]
**Describe the bug**
DT crashes with "double free or corruption (!prev)" when loading a file and zooming in and out randomly while having the tone equalizer turned on and using the guided filter.
Sometimes it already crashes when loading a specific images.
Here is a backtrace: [backtrace.txt](https://github.com/darktable-org/darktable/files/5907575/backtrace.txt)

**Platform (please complete the following information):**
 - Darktable Version: lastest master (3.5.0+903~g641608706)
 - OS: Ubuntu 20.04
 - OpenCL activated: yes

I didn't have this crash with the last version I compiled some days ago, I need to check which version I used last time, where I didn't run into this crash.

**Comment by da-phil** [comment]
@ralfbrown wow, that was fast, the changes in your PR fixed the crash for me!

**Comment by ralfbrown** [comment]
It helps that I started working on the fix before you posted the bug report :-).
