### ISSUE TITLE
tone equalizer - weird artefacts and color shifts appear when zooming in

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8076]
**Describe the bug**
I get weird artefacts and colour shifts when zooming in and out, it's quite random. And it only happens when the tone equalizer is turned on using the "guided filter". The actual weird shapes come from the mask which is generated by the guided filter.

The following (scene referred) modules are active: 
<img src="https://user-images.githubusercontent.com/810285/106614971-4006e880-656c-11eb-920b-68586065071c.png" height="350px">

And this is how it could look like:
![Screenshot from 2021-02-02 21-46-45](https://user-images.githubusercontent.com/810285/106660382-34cdb000-65a0-11eb-91b6-7b89a064268f.png)

I also added a video, sorry for the zip, but unfortunately .webm as the one proper format for the web is not allowed with github :roll_eyes:
[Screencast from 02.02.2021 15:21:49.zip](https://github.com/darktable-org/darktable/files/5911816/Screencast.from.02.02.2021.15.21.49.zip)

This happens with OpenCL active/disabled (`--disable-opencl`), as well as SSE2 active/disabled (`--conf codepaths/sse2=false`).

**Steps to reproduce**
1. Choose a picture like https://discuss.pixls.us/t/that-day-at-route-1/23134
2. Download the following profile with a minimal set of active modules (sorry for the ZIP, github doesn't allow XML files): [DSC_0694.NEF.zip](https://github.com/darktable-org/darktable/files/5920220/DSC_0694.NEF.zip)

3. Zoom in at different positions in the picture and notice the weird artefacts

**Platform (please complete the following information):**
* Darktable Version: lastest master (3.5.0+913~g48425e51d-dirty)
* OS: Ubuntu 20.04

**Comment by jenshannoschwalm** [comment]
I can't see all the modules in your list, have you enabled "ca correction"? That would explain what you see and is something i am currently working on...

**Comment by da-phil** [comment]
> I can't see all the modules in your list, have you enabled "ca correction"? That would explain what you see and is something i am currently working on...

Sorry for the small thumbnail image of my active module, if you click on it, it will get enlarged, I just thought it would take up too much space in the issue description.

No, CA correction is not turned on, but "defringe" which however does not cause the artefacts.

I'll try out to disable module by module to find the culprit in the meantime!

**Comment by da-phil** [comment]
@jenshannoschwalm so apparently the culprit is the tone equalizer and this behaviour was introduced with a segfault fix in PR https://github.com/darktable-org/darktable/pull/8067 with commit https://github.com/darktable-org/darktable/commit/2765908eb7cc4afc874f18781e034ef764b5fab3

CC: @ralfbrown 

Can you reproduce this with tone equalizer activated?

**Comment by da-phil** [comment]
Magically @ralfbrown's PR (https://github.com/darktable-org/darktable/pull/8092) solved the issue :+1:
