### ISSUE TITLE
Pictures taken with my brand new Nikon Z 6_2 won't open in Darktables Darkroom

### ISSUE THREAD

**Issue by Gaddeart** [darktable-org/darktable#8077]
**Describe the bug**
I import a file (direct copied from my Nikon Z 6_2 to my Harddisc)  in Darktable.
The picture(s) are visible on the Lightdesk. The xmp-file(s) for each picture is created on the disk.
The picture-informations on the left side are correct.
Opening the picture in darkroom won't work.

**To Reproduce**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0-1.1
 - OS: Linux Ubuntu 20.04
 - OpenCL not activated
 Intel® HD Graphics 2500 (IVB GT1)

**Additional context**
I installed Darktable 3.4.0 because the problem was the same in the old version 3.2.0 (delivered with Ubuntu 20.04)
The problem is with every raw-file. Jpg-files are working fine, but the camera Nikon Z 6_2 is not in the list with the lens-correction.
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? No
![Screenshot_Lighttable](https://user-images.githubusercontent.com/78430612/106632032-9cbecf00-657d-11eb-80e5-a5509db71175.png)
![Screenshot_Darkroom](https://user-images.githubusercontent.com/78430612/106632061-a5170a00-657d-11eb-8901-b28989b57512.png)
![Screenshot_Darkroom_2](https://user-images.githubusercontent.com/78430612/106632086-a9dbbe00-657d-11eb-94b4-a7eced894a3a.png)

**Comment by Gaddeart** [comment]
Oh i forgot the xmp-file ...

here it is!
[Inhalt_xmp-file.pdf](https://github.com/darktable-org/darktable/files/5912832/Inhalt_xmp-file.pdf)

**Comment by ptilopteri** [comment]
doesn't appear the Z 6ii is supported yet.  all the needed
samples are no on https://raw.pixls.us/

so your raws are not going to work until the samples are
provided and worked.

**Comment by ptilopteri** [comment]
go to https://raw/pixls.us/
and read the front page

LebedevRI will check that the needed files are present 
and provide an update to darktable which will allow decoding 
your nef files for the Z 6ii

remember, this is opensource and he is volunteering his work,
but he is normally very prompt

**Comment by Nilvus** [comment]
@Gaddeart: your camera is really recent (released about 3 months ago only). darktable can support a new camera only if we have material to support it, like @ptilopteri answer to do: submit raws asked on suggested website to allow support. Then you could create an issue here to inform **LebedevRI** that all needed samples are posted. It will then could add new camera support. And so, include it in the next darktable release.

As by now we can't do anything more, I close this issue.

**Comment by Nilvus** [comment]
Just a thing I've just seen. Nikon Z6 II RAW support had been added in Rawspeed (so in darktable) just about a month ago. So should probably be in next darktable release, 3.4.1 (will be out in few days).
