### ISSUE TITLE
Crashes when exporting B&W DNG scans from epson scanner

### ISSUE THREAD

**Issue by juloverni** [darktable-org/darktable#8079]
Medium format B&W negatives developped using nega doctor in darktable. Program crashes when I try to export them, telling me "color matrix Epson PerfectionV600 not found" 
I'm very new to this sorry if this isn't the way to report a bug

[darktable_crash_02022021_exporting_dng_epsonscan.txt](https://github.com/darktable-org/darktable/files/5913940/darktable_crash_02022021_exporting_dng_epsonscan.txt)

**Comment by jenshannoschwalm** [comment]
Hi, unfortunately your report misses a lot of information. At least we need one of the files you have been developing. Most likely it is a problem of the scanner software writing bogus or not writing necessary dng data. I you share a file i would look into it ...

**Comment by jenshannoschwalm** [comment]
@johnny-bit please close. Is it ok to ping you for such boring work? :-) Just getting through a list of rather obscure issues to get some closed.

**Comment by johnny-bit** [comment]
Sure, I accepted janitorial position and so I can janitor it a bit :)
