### ISSUE TITLE
haze removal → inconsistent output

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#8083]
darktable 3.4 via OBS, 64 bit, Debian Stable, OpenCL disabled, filmic workflow by default

1. Open, let's say, this file https://discuss.pixls.us/t/that-day-at-route-1/23134
2. Go to haze removal tool, enable it.
3. Make "distance" parameter = 0.000 via slider.

"inconsistent output" message appears above bottom part of the image.

**Comment by ralfbrown** [comment]
Unable to replicate on current master.

The cause of the message is that haze removal needs access to the full image, so when you are zoomed in, the center view processing needs to wait on the preview image processing to complete up to the haze removal module to read some key parameters.  The message is output if that doesn't happen within a reasonable time (a few seconds).  I don't see any way that the `distance` parameter would affect processing time; does the message occur consistently?

**Comment by timur-davletshin** [comment]
After playing again I noticed that it is not 100% reproducible (~80-90%). It happens when I use distance slider. I don't do any zooming, just open fresh image and enable module. XMP file is in the attachment.

[DSC_0694.NEF.zip](https://github.com/darktable-org/darktable/files/5919152/DSC_0694.NEF.zip)

**Comment by JacoTux** [comment]
darktable 3.7.0+774, manjaro linux, OpenCL, with fimic worflow or not, raw from Fujifilm
This happens for me every time with distance slider or not, images opened with only default modules.
