### ISSUE TITLE
X100T detects as X-T100 in lens-correction module

### ISSUE THREAD

**Issue by 4kbt** [darktable-org/darktable#8087]
Hi!

RAW files from my X100T do not appear to be recognized correctly by the lens-correction module. The module *has* an X100T option, but it is not automatically selected.

See this screenshot: 

![image](https://user-images.githubusercontent.com/3980568/106770287-ac2c2f80-65f2-11eb-9316-b133716f6972.png)

At left, one can see the X100T information in the EXIF window (and the 33mm focal length, indicating that the TCL-100 teleconverter lens is installed). At right, the lens-correction module has detected it as X-T100 :).

**To Reproduce**
1. Make a RAW photograph with an X100T
2. Import photograph into darktable
3. Open the lens-corrections module
4. Observe that the auto-detection has not found an X100T with a 23 or 33 mm lens.
5. (Bonus) click through the dropdowns to find that the X100T *is* present in the installed lensfun library.

**Expected behavior**
The lens-correction module would auto-detect the X100T correctly.

**Platform (please complete the following information):**
Stock Debian testing.

$ darktable --version
this is darktable 3.4.0
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

The same issue exists on a Windows installation of Darktable 3.2.1 -- this has been a longstanding issue for me.

**Additional context**
An out-take RAW file is available here for verification/testing ( underexposure is intentional ;) ): https://drive.google.com/file/d/1wZlrUr0vcC01t6FPJdTU_Pny0nCdwOkc/view?usp=sharing

**Comment by Nilvus** [comment]
Seems to be more a lensfun issue (something maybe not precise correctly in lensfun database) or maybe exiv2. When using exiftool and exiv2 to check information of your RAW, no Lens info is reported. And lens correction module use lensfun to select good camera/Lens combo regarding of EXIF infos extracted by exiv2 library.

@johnny-bit: as you kinow all that probably better than me, could you confirm? I'm quite sure this issue is not directly darktable related.

**Comment by 4kbt** [comment]
Interesting -- if I run exiv2, I do get lens information. It correctly reports the 33.0 mm (teleconverter was installed) lens.

`$ exiv2 DSCF4139.RAF 
File name       : DSCF4139.RAF
File size       : 33601024 Bytes
MIME type       : image/x-fuji-raf
Image size      : 1920 x 1280
Camera make     : FUJIFILM
Camera model    : X100T
Image timestamp : 2021:01:29 09:02:03
Image number    : 
Exposure time   : 1/250 s
Aperture        : F4
Exposure bias   : -67/100 EV
Flash           : No, compulsory
Flash bias      : 
Focal length    : 33.0 mm
Subject distance: 
ISO speed       : 320
Exposure mode   : Manual
Metering mode   : Multi-segment
Macro mode      : Off
Image quality   : NORMAL 
Exif Resolution : 1920 x 1280
White balance   : Daylight
Thumbnail       : image/jpeg, 9197 Bytes
Copyright       :     
Exif comment    : 
`

If I run the same command against a RAW file in the standard 23.0 mm configuration, I also get a focal length returned properly.

`$ exiv2 DSCF4745.RAF 
File name       : DSCF4745.RAF
File size       : 33166336 Bytes
MIME type       : image/x-fuji-raf
Image size      : 1920 x 1280
Camera make     : FUJIFILM
Camera model    : X100T
Image timestamp : 2021:02:03 19:35:43
Image number    : 
Exposure time   : 1/125 s
Aperture        : F2
Exposure bias   : 0 EV
Flash           : No, compulsory
Flash bias      : 
Focal length    : 23.0 mm
Subject distance: 
ISO speed       : 1600
Exposure mode   : Manual
Metering mode   : Multi-segment
Macro mode      : Off
Image quality   : NORMAL 
Exif Resolution : 1920 x 1280
White balance   : Daylight
Thumbnail       : image/jpeg, 3594 Bytes
Copyright       :     
Exif comment    : 
`

**Comment by johnny-bit** [comment]
This needs to be tackled somewhere for lens correction module funzies. with probably warnings etc

**Comment by MStraeten** [comment]
with exiv2 no lens is identified:
`exiv2 -pa --grep lens/i ~/Downloads/DSCF4139.RAF`
so first it needs to be supported there

**Comment by 4kbt** [comment]
Looks like if I run
exiv2 -pa ~/Downloads/DSCF4139.RAF

I can see

Exif.Photo.FocalLength                       Rational    1  33.0 mm

mixed into the output (this image was made with the TCL-X100 converter
attached, hence 33mm instead of 23mm).  Is the trouble that the X100T
doesn't have traditional interchangeable lenses, so the EXIF reporting is
different?

**Comment by cribari** [comment]
The problem remains with darktable version 4.0, lensfun version 0.3.3 and exiv2 version 0.27.5-3 (under Arch Linux).
