### ISSUE TITLE
Version mismatch when opening a new image

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#8112]
**Describe the bug**
When I open an image in darkroom that doesn't have any history I get an error message `image.raw: Module 'colorin' version mismatch 7 != 1`.

**To Reproduce**
1. Create a copy of an image
2. Discard the history stack of the copy (or select an image that doesn't have history stack)
3. Open the image in darkroom

**Screenshots**
![image](https://user-images.githubusercontent.com/18402158/107116841-bf532f80-687e-11eb-9ed5-c7955fc94b1b.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+947~gb47c0146e
 - OS: Win10 and Ubuntu 20.10
 - OpenCL: no impact

**Comment by flannelhead** [comment]
The colorin module parameters version was bumped from 6 to 7 in https://github.com/darktable-org/darktable/pull/8037/commits/adc61a64273165c4ba18ecf05e7fab769db2c605

I'm not 100% sure but it seems I missed adding a migration path for the module parameters from older versions to version 7. Sorry for the inconvenience! Bumping the `new_version == 6` conditionals in colorin.c / `legacy_params` to `new_version == 7` could do the trick. I hope to be able to provide a fix tomorrow (unless someone else is quicker to do this).

**Comment by TurboGit** [comment]
Right :( There is migration path from 6 to 7 but the migration from older versions are not done.

@flannelhead : Can you have a look ? This is urgent as breaking old edits. TIA.

**Comment by flannelhead** [comment]
Hopefully https://github.com/darktable-org/darktable/pull/8129 fixes this.

Reading the original report I find it strange that a fresh image with no history stack triggers this. I wonder if there's something else to it...

**Comment by flannelhead** [comment]
@juhavlintula would you be able to provide a log of `stderr` output from a run of darktable where this issue has been reproduced? I can't reproduce it myself and would like to understand the issue further.

**Comment by juhavlintula** [comment]
I came to think that the issue might be caused by the image.xmp file. My DAM has tagged the RAWs and created the xmp sidecar file. When I opened an image that I hadn't tagged there was no error message.

Below is the sidecar file. 
```
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.6.0">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:xmp="http://ns.adobe.com/xap/1.0/"
            xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
            xmlns:exif="http://ns.adobe.com/exif/1.0/"
            xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
            xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"
            xmlns:aux="http://ns.adobe.com/exif/1.0/aux/"
            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
            xmlns:dc="http://purl.org/dc/elements/1.1/">
         <xmp:MetadataDate>2018-01-01T14:47:32+02:00</xmp:MetadataDate>
         <xmp:ModifyDate>2018-01-01T14:47:32+02:00</xmp:ModifyDate>
         <photoshop:DateCreated>2017-10-17T18:41:30+03:00</photoshop:DateCreated>
         <photoshop:SidecarForExtension>CR2</photoshop:SidecarForExtension>
         <photoshop:Country>France</photoshop:Country>
         <photoshop:State>Vaucluse</photoshop:State>
         <photoshop:City>Bédoin</photoshop:City>
         <photoshop:ICCProfile>sRGB IEC61966-2.1</photoshop:ICCProfile>
         <photoshop:SupplementalCategories>
            <rdf:Bag>
               <rdf:li>Landscape|Mountains</rdf:li>
               <rdf:li>People|Portrait</rdf:li>
            </rdf:Bag>
         </photoshop:SupplementalCategories>
         <exif:DateTimeOriginal>2017-10-17T18:41:30+03:00</exif:DateTimeOriginal>
         <exif:GPSLongitude>5,16.691422E</exif:GPSLongitude>
         <exif:GPSLatitude>44,10.412397N</exif:GPSLatitude>
         <Iptc4xmpCore:Location>Mont Ventoux</Iptc4xmpCore:Location>
         <Iptc4xmpExt:Event>
            <rdf:Alt>
               <rdf:li xml:lang="x-default">Syysloma|2017</rdf:li>
            </rdf:Alt>
         </Iptc4xmpExt:Event>
         <Iptc4xmpExt:PersonInImage>
            <rdf:Bag>
               <rdf:li>N|N</rdf:li>
            </rdf:Bag>
         </Iptc4xmpExt:PersonInImage>
         <aux:Lens>Canon EF-S18-55mm f/3.5-5.6 IS II</aux:Lens>
         <tiff:Orientation>1</tiff:Orientation>
         <tiff:Model>Canon EOS 600D</tiff:Model>
         <tiff:Make>Canon</tiff:Make>
         <dc:creator>
            <rdf:Seq>
               <rdf:li>Juha Lintula</rdf:li>
            </rdf:Seq>
         </dc:creator>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
       
<?xpacket end="w"?>
```

**Comment by flannelhead** [comment]
Thanks! I see now that probably having that XMP in place has triggered the Lightroom import code path for the image. That path initializes the `colorin` module params with version 1. I was wondering where that version was coming from (new fresh edits should assign the current params version which is 7), and probably this is the explanation.

**Comment by flannelhead** [comment]
After looking at it for a while, can't exactly see why this XMP would've triggered the Lightroom import path, but most likely the `colorin` version 1 originates from there.

@juhavlintula could you please confirm the issue is fixed now that https://github.com/darktable-org/darktable/pull/8129 fixes the issue? Thanks!

**Comment by juhavlintula** [comment]
Tested with 3.5.0+983 and the issue is fixed. I still get a message `input color profile has been imported`; what does that mean?

**Comment by flannelhead** [comment]
Good to hear! That message is definitely coming from the Lightroom import code; darktable has found a Lightroom XMP for the image and imports compatible settings from there.
