### ISSUE TITLE
Unexpected result from Color Calibration module

### ISSUE THREAD

**Issue by tatnguyennguyen** [darktable-org/darktable#8114]
**Describe the bug**

Color Calibration module produces weird result ?

**To Reproduce**
1. Load a white image to darktable
2. Turn on color calibration module
3. Set parameters as follow:
R : 0.75R + 0.25G + 0B
G: 0.25R + 0.5G +0.25B
B: 0R + 0G +1B

**Expected behavior**

What I expected is I can get the white image back, but I got a magenta image instead.
You can turn on and off this module to see the change in color

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: OpenSUSE 15.2
 - OpenCL activated: No

**Additional context**
I tried this with Rawtherapee and the result is as expected

**Comment by MStraeten** [comment]
not reproducible with current master.
there were some issues with colorcalibration in dt 3.4.0
so try with dt 3.4.1

**Comment by tatnguyennguyen** [comment]
> not reproducible with current master.
> there were some issues with colorcalibration in dt 3.4.0
> so try with dt 3.4.1

I just tried Darktable 3.4.1 and the Color Calibration module works very well. Thanks!
