### ISSUE TITLE
Unable to see fonts after changing theme in preferences

### ISSUE THREAD

**Issue by Latesil** [darktable-org/darktable#8116]
**Describe the bug**

Unable to see fonts after changing theme in preferences.

**To Reproduce**

1. Go to Settings.
2. Go to General.
3. Change theme to other than default

**Expected behavior**

Theme should be changed without any issues

**Screenshots**

![Screenshot from 2021-02-06 15-54-21](https://user-images.githubusercontent.com/18707489/107118796-1dd6d880-6894-11eb-9476-63b056ea2ece.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Fedora 33
 - No OpenCL\CUDA
 - Graphic Card: Intel HD Graphic 620

**Additional context**

I tested that in flatpak version from Flathub and from Fedora repos. Both versions have that issue.

**Comment by Mark-64** [comment]
For the darktable-elegant themes you need to install the font family "Roboto".
see here [https://fonts.google.com/specimen/Roboto?preview.text_type=custom](url)
