### ISSUE TITLE
FR: map view - temporarily hide images

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8123]
**Is your feature request related to a problem? Please describe.**
When manually geotagging images by dragging them onto the map, one frequently finds that one (or more) already-placed images obscure the point on the map where the next image should be placed.  This is a problem even when maximally zoomed and using clustering if there are multiple images located within say a block or two of each other.

**Describe the solution you'd like**
It would be nice to have a way of temporarily hiding already-placed images to have an unobstructed view of the map, by (for example) pressing the Alt key while dragging an image.  When the modifier key is released, the hidden images would be redrawn.

**Alternatives**
- Have a switchable mode which shows location pins instead of thumbnails.  That would obscure much less of the map.
- Automatically hide thumbnails within a certain radius of the current mouse location while dragging an image
- Always place images in a strict northeast-to-southwest order :-)

Location pins would be nice to have as an alternate display mode anyway, especially if hovering the mouse on one would show the thumbnail.

(#8106 reminded me to finally post this...)

**Comment by johnny-bit** [comment]
IMO this is good idea...

@phweyland - what's your opinion?

**Comment by phweyland** [comment]
> It would be nice to have a way of temporarily hiding already-placed images

Good idea indeed.

Key modifier may be tricky with drag and drop (we have also to compose with thumbtable drag and drop)...
Maybe an hotkey to hide / show the thumbs ...

> Always place images in a strict northeast-to-southwest order

If I can do something I would go southwest-to-northeast (to keep visible the pin and images number as far as possible). What is your idea behind this ?

> Location pins would be nice to have as an alternate display mode anyway, especially if hovering the mouse on one would show the thumbnail.

Another good idea I'm afraid. Pin + number ...

**Comment by ralfbrown** [comment]
It was meant as a joke....  The thumbnail obscures the portion of the map to the northeast of the pin position, so if you work your way to the SW while placing your images on the map, the prior images won't obscure the position for the next image.  Not exactly practical unless you were traveling in that direction while taking the pictures.

**Comment by phweyland** [comment]
Starting on this.
