### ISSUE TITLE
Shorcuts in color calibration (FR)

### ISSUE THREAD

**Issue by hgmarty** [darktable-org/darktable#8130]
Hello,

as shortcuts user, I miss it in this module.
If we talk about white balance, we have shortcuts in settings for :
* camera reference
* from image area
* ...

In color calibration, we have not this possibility and it is difficult to catch the algorithm with the dynamic shortcut.

Is it possible to have shortcut like the white balance with : 
* set white balance to detected from area
* (AI) detect from image surface...
* (AI) detect from image edges...

Thanks for your job
Have a good day

**Comment by Nilvus** [comment]
This work in progress about a whole new shortcuts system should fix all shortcuts feature requests like yours:  #8078

**Comment by hgmarty** [comment]
I have read this ant it's awesome.
You can close this issue (I don't think if I can)

**Comment by Nilvus** [comment]
Yes you can as you open it. The button is below comment editor.
