### ISSUE TITLE
$(LONGITUDE) uses N/S instead of E/W in thumbnail extended overlay text

### ISSUE THREAD

**Issue by mrubli** [darktable-org/darktable#8131]
**Describe the bug**

When the `$(LONGITUDE)` variable is expanded it uses N/S instead of E/W for positive/negative values:

![image](https://user-images.githubusercontent.com/29906522/107141043-2cd78c80-6961-11eb-863b-4c2d538d29cd.png)

The screenshot above was generated using this pattern:

```<b>$(FILE_NAME).$(FILE_EXTENSION)</b>$(NL)$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY) $(EXIF_HOUR):$(EXIF_MINUTE):$(EXIF_SECOND)$(NL)$(EXIF_EXPOSURE) • f/$(EXIF_APERTURE) • $(EXIF_FOCAL_LENGTH) mm • $(EXIF_ISO) ISO$(NL)$(LATITUDE), $(LONGITUDE)```

**To Reproduce**
1. Open preferences, section _lighttable_.
2. Change the _pattern for the thumbnail extended overlay text_ to something containing `$(LONGITUDE)`.
3. Go back to the lighttable
4. Hover over a photo that has location information (latitude/longitude in the image information)
5. Observe the error in the tooltip

**Expected behavior**
The longitude should read something like `E 121° 02.140'` instead of `N 121° 02.140'`.

**Platform**
 - Darktable Version: 3.4.0
 - OS: Debian GNU/Linux bullseye/sid

**Suggested fix**
I haven't tried this but from browsing in the source code the bug is likely here:
https://github.com/darktable-org/darktable/blob/master/src/common/variables.c#L231

```diff
diff --git a/src/common/variables.c b/src/common/variables.c
index 46f822c..2d74e5f 100644
--- a/src/common/variables.c
+++ b/src/common/variables.c
@@ -226,11 +226,11 @@ static char *get_base_value(dt_variables_params_t *params, char **variable)
   else if(has_prefix(variable, "LONGITUDE"))
   {
     if(dt_conf_get_bool("plugins/lighttable/metadata_view/pretty_location")
        && g_strcmp0(params->jobcode, "infos") == 0)
     {
-      result = dt_util_latitude_str(params->data->longitude);
+      result = dt_util_longitude_str(params->data->longitude);
     }
     else
     {
       gchar NS = params->data->longitude < 0 ? 'W' : 'E';
       result = g_strdup_printf("%c%010.6f", NS, fabs(params->data->longitude));
```

I'll be happy to test and submit a PR myself if necessary but since this seems like a rather straightforward fix someone who's already set up for darktable development is likely in a position to do so much more efficiently.

**Comment by Mark-64** [comment]
Indeed. Thank you for finding this, PR coming
