### ISSUE TITLE
NIKON D780 WB 

### ISSUE THREAD

**Issue by claenn** [darktable-org/darktable#8132]
half steps in 
direct sunlight, cloudy, shade, incandescent

[darktable-whitebalance-20210207.tar.gz](https://github.com/darktable-org/darktable/files/5938706/darktable-whitebalance-20210207.tar.gz)

**Comment by jcubic** [comment]
Does it have all numbers per Auto 4 version and incandescent light (7 versions), because I was about to upload my data after I've run the script.

**Comment by claenn** [comment]
none of the seven fluorescent settings included (from 1-sodium-vapor up to 7-high-temp-mercury-vapor).

**Comment by johnny-bit** [comment]
@jcubic - Auto WBs should be ignored by the script (and so it's not worth making them). the fluorescent ones however are worthwile.

You can use this issue to offload responsibilities ;) in @claenn's there;s no fluorescent ones so would be good to have those :)

**Comment by johnny-bit** [comment]
@jcubic - I'd still love to get finetuned fluorescent presets if possible. Can you upload those? That would make it a lovely set.

**Comment by jcubic** [comment]
I don't have that camera anymore, but I still have the files, I think that I use all possible combinations. Will need to check again how to upload the data.

**Comment by jcubic** [comment]
By any chance do you have any link to the article on how to extract WB data from the files?

**Comment by johnny-bit** [comment]
Sure!

https://github.com/darktable-org/darktable/wiki/White-balance-presets

you can do it with `extract_wb_from_images.sh` (and attach created archive so I'll convert it to PR) or use `extract_wb.py` and you can do the PR yourself :)

**Comment by jcubic** [comment]
Here is the file. I hope that I've created the file correctly.

[darktable-whitebalance-20210529.tar.gz](https://github.com/darktable-org/darktable/files/6564916/darktable-whitebalance-20210529.tar.gz)
