### ISSUE TITLE
Staus bar while importing

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#8137]
**Is your feature request related to a problem? Please describe.**

When I import a big folder of photos the UI hangs totally and the progress bar does not indicate that status of the import

**Describe the solution you'd like**

I would like a working status bar showing the progress of the imports

**Alternatives**

**Additional context**

**Comment by bengtfalke** [comment]
Version 3.4.1 of Darktable and Windows 10

**Comment by johnny-bit** [comment]
Duplicate of #7111 and will most likely be fixed by #8080
