### ISSUE TITLE
???cache got damaged [initially I thought, thru b249bbf1f or dd8a0c432]???

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#8153]
This is a dirty bug report, as I am not ready yet but asking here might open some minds and accelerate the investigation, I hope that is acceptable...

- I do run darktable-generate-cache -m6 regularly
- last two days on current master I found lighttable (zoom=3) is very slow in scrolling (see a lot "working"), which was not the case before
- starting darktable -d cache shows me, some cached files are found but some getting generated from scratch (CPU-load also climbs. OpenCl is working)
- Rebuilt ~/.cache/darktable completely and still the same
- [EDIT] I wondered (know I know better) whether commits b249bbf1f or dd8a0c432 are involved and what I could do better to analyse 

[EDIT]
- I flushed ~/.cache/darktable and started darktable-generate-cache -m6 again 
- and observe, in the mipmaps folder only subfolders 0-3 instead of 0-6 got created
- watch du shows me mainly 0-2 are getting filled and 3 somehow stuck at very low level

**Comment by AxelG-DE** [comment]
@TurboGit may I ask you for your opinion or advice?
When I find time I will checkout prior to those and check...

**Comment by TurboGit** [comment]
@AxelG-DE : The two commits you list cannot be the culprits. Maybe this is due to recent changes in a95b0a1a32a1b493ce98a23d4c8f78170efda3f9.

**Comment by TurboGit** [comment]
>     * watch du shows me mainly 0-2 are getting filled and 3 somehow stuck at very low level

I cannot confirm that. I have removed my cache and have look at image with zoom 25 to 1 and got maybe level cached:

```
$ du -h .
11M	./2
39M	./3
1.1M	./1
1.6M	./0
18M	./4
70M	.
```

**Comment by AxelG-DE** [comment]
> I cannot confirm that. I have removed my cache and have look at image with zoom 25 to 1 and got many levels cached:

Yes watching at them finally does create from scratch, that is exactly, what makes it slow. 
I have the feeling darktable-generate-cache is somehow broken

**Comment by AxelG-DE** [comment]
@TurboGit I figured out my self already, that your two commits are not the culprits by checking out at g4f0b66878 (just my related comment got stuck, now deleted)

> @AxelG-DE : The two commits you list cannot be the culprits. Maybe this is due to recent changes in [a95b0a1](https://github.com/darktable-org/darktable/commit/a95b0a1a32a1b493ce98a23d4c8f78170efda3f9).

I checked out at ga88b30f1b, which is before a95b0a1, but there I cannot run darktable-generate-cache -m6 easily as I would need to revert the library.db (not impossible but much more trouble)

@AlicVB may I kindly ask you to also have a look into here?

**Comment by AxelG-DE** [comment]
For a short trial I started  darktable-generate-cache -m7 and it seems that works more comprehensively, just due to time consumption (85k pics) I interrupted.

**Comment by AxelG-DE** [comment]
**I think I found it!**

maybe it was an old unwanted or now deprecated tolerance, which might have been eliminated recently...

all the time (and I talk about long time, as I use ctrl+r to recall old commands) I used **darktable-generate-cache -m6** but reading darktable-generate-cache -h, it says the option is called **-m 6** (notice the blank!!!).

So now I started the command with the blank and gen-cache is working hard instead of just running thru... I think this was it.

Let it run and I will check tomorrow or day after and likely cose by then...

**Comment by AxelG-DE** [comment]
**Bingo**, this was it...

seems some of the recent refactoring (if I may call it like this) caused a, potentially unhealthy, tolerance to be eliminated and now merely -m <0-8> is accepted (noctice the blank after "m"). 
By means:
- e.g. darktable-generate-cache -m 6 is **ok**
- whereas e.g. darktable-generate-cache -m6 is **is not ok**

**Comment by TurboGit** [comment]
Good to see this cleared out !
