### ISSUE TITLE
nightbuild version can't export photos to GIMP 2.10 due to broken lua API

### ISSUE THREAD

**Issue by oxpa** [darktable-org/darktable#8156]
I'm using darktable 3.5.0~git1005.3c08ff239-1 on ubuntu 20.04.

When I open a NEF file using Gimp 2.10 it launches darktable somehow like this:
```
darktable --library :memory: --luacmd "dofile('/usr/share/gimp/2.0/file-raw/file-darktable-export-on-exit.lua')" --conf plugins/lighttable/export/icctype=3 --conf lua/export_on_exit/export_filename=/tmp/gimp/2.10/gimp-temp-7384730.exr /DSC_3440.NEF
```
Gimp uses `darktable.register_event` to set up hook to export an image.
Documentation states that the second argument should be a function. And Gimp uses function as the second argument. But it gets following error:
```
3,383867 LUA ERROR : ...hare/gimp/2.0/file-raw/file-darktable-export-on-exit.lua:45: bad argument #2 to 'register_event' (string expected, got function)
```
So I believe the interface is broken and either Gimp should get a new lua script or darktable maintain API.
The latter seems more appropriate.

**Comment by parafin** [comment]
If you want stable API, you shouldn't use master builds. Lua API has versions and changes occasionally needing script updates. That's by design, see #8052 for more information. I'll let @wpferguson to give more details.

**Comment by oxpa** [comment]
I don't really want a stable API. I just report a problem I faced.
#8052 explains everything: the problem is expected behavior.

Thank you!

**Comment by wpferguson** [comment]
@parafin thanks for the ping.  In my plan I forgot about collateral damage.  @oxpa attached is a fixed version of the script.

[file-darktable-export-on-exit.lua.txt](https://github.com/darktable-org/darktable/files/5955103/file-darktable-export-on-exit.lua.txt)
