### ISSUE TITLE
Rename basic widgets, deprecate basic adjustments

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8168]
With the new all-powerful "basic widgets/basic adjustment" group, it doesn't much make sense to keep the "basic adjustments" iop module any more so I would like to suggest that we deprecate that module for v3.6.

Also, given that you can add pretty much any widget from any module to the "basic widgets" group, it doesn't really make sense to call it "basic" any more, since it's really quite powerful and, apart from multi-instance situations I can see it being used quite a lot.

So far I can only come up with "custom widget panel" but that seems a bit lame. Anyone have other ideas?

**Comment by elstoc** [comment]
Suggestion from @johnny-bit: "quick access panel" (+1 from me)

**Comment by johnny-bit** [comment]
If I remember correctly the only positive thing that basic adj has is better vibrance implementation. Ripping that out and into new module (vibrance rgb lol) would be net positive overall.

**Comment by Nilvus** [comment]
> With the new all-powerful "basic widgets/basic adjustment" group, it doesn't much make sense to keep the "basic adjustments" iop module any more so I would like to suggest that we deprecate that module for v3.6.
> 
> Also, given that you can add pretty much any widget from any module to the "basic widgets" group, it doesn't really make sense to call it "basic" any more, since it's really quite powerful and, apart from multi-instance situations I can see it being used quite a lot.

I just totally agree with that. basic adjustments was not the good way as the new one is a much better one.

I'm on to for @johnny-bit suggestion: "quick access panel"

**Comment by Mark-64** [comment]
> Ripping that out and into new module

or as a new option (v2 algorithm) into the existing vibrance module

**Comment by TurboGit** [comment]
Yes "quick access panel" looks good and indeed we need to take into account the enhanced vibrance somehow. I like @Mark-64 proposal.

**Comment by elstoc** [comment]
I'll issue a PR for the rename later, but not competent to mess around with iop stuff so someone else might have to tackle that.

**Comment by AlicVB** [comment]
- basic adjustment replacement was the initial goal of "basics widgets" so, yes, at some point we should deprecate the iop, and the sooner the better.
- I completely agree too for the name change.
- for vibrance, I'm not sure @Mark-64 solution is the best, apart if there's a way to "upgrade" old edits to the new algorithm. I suspect it's not possible, and in this case, creating a new iop and deprecating the older one would be better imo, as both module code will be simpler to maintain (dealing with 2 code paths for computation and ui can very quickly become a mess. See keystone/perspective in clipping.c for example)

**Comment by elstoc** [comment]
> apart if there's a way to "upgrade" old edits to the new algorithm

We already have two selectable algorithms in filmic with the ability to switch between them. Couldn't we do the same for vibrance?

**Comment by AlicVB** [comment]
> We already have two selectable algorithms in filmic with the ability to switch between them. Couldn't we do the same for vibrance?

you're right, doing that this way would be simpler. The problem is when we try to "deprecate inside iop". but if we propose the 2 algos, that's just a matter of selecting the new one by default, and the 2 code paths are completely separated :)

**Comment by elstoc** [comment]
Reopening because there are still aspects of this issue to be discussed/resolved.

**Comment by TurboGit** [comment]
Sure, and I'd like to volunteer to create the v2 implementation on the vibrance module. Assigning this issue to me.

**Comment by TurboGit** [comment]
Oh ! But current vibrance is a Lab module and so a better solution is probably to introduce a vibrancergb module!

**Comment by elstoc** [comment]
All aspects of this are complete now so closing
