### ISSUE TITLE
Strange behaviour trying to add modules to my group

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8173]
3.5.0+1011~gcf8280351-dirty   Ubuntu 18.04

I'm unable to add modules to my new "favourites" group.   Ok in dt 3.4 release.

To reproduce: Click "manage presets" to get screen below.
Click the plus sign below "new".
It displays a short horizontal black bar about 4mm long instead of showing the module list.  I can't even get a screen grab of this - it seems to be inhibiting it. Once I click elsewhere and the black bar is gone, I can do a screen grab ("Print Screen").
![Screenshot from 2021-02-10 11-38-35](https://user-images.githubusercontent.com/16868433/107506218-b1aaec00-6b95-11eb-95c5-dad32d41982f.png)

**Comment by elstoc** [comment]
I can confirm this. @AlicVB please can you take a look.

**Comment by Mark-64** [comment]
Fro bisect, culprit seems to be d8e4a0868a76006b3fbaf9cb1a729a0f5bd2ae9f

**Comment by MStraeten** [comment]
workaround: just use 'base' or one of the default column names to add the modules & rename it after adding the modules
