### ISSUE TITLE
DT crashes while importing

### ISSUE THREAD

**Issue by Lorenzoeffe** [darktable-org/darktable#8176]
Hi
While importing my photo archive (98300 files) DT crashed about a third of the way through the process.
The software returned the error that I attach.
PC:
AMD Ryzen 1800x
Corsair 32GB DDR4
SSD Samsung 870 Pro
Seagate Barracuda 4TB 7200rpm
Windows 10 Pro 20H2
![073](https://user-images.githubusercontent.com/50571973/107558855-9662cf80-6bdb-11eb-960a-44cf13f75e2c.jpg)
[darktable_bt_DQ2MY0.txt](https://github.com/darktable-org/darktable/files/5960814/darktable_bt_DQ2MY0.txt)

**Comment by Mark-64** [comment]
from backtrace, DT fails in `dt_exif_xmp_read()`. Some broken .xmp?
Is is the first time you import the picture or have you used DT before?
Con you try to import them in batches, not 98000+ all together and try to narrow down the problem?
Eventually, you might find a specific folder or file that causes the issue.

**Comment by Lorenzoeffe** [comment]
I have been using DT for 3 years and have worked with it hundreds of images (jpeg and raw) always saving the sidecar.
I have always done single folder imports and have also encountered problems in the past related to not reading the sidecar file, but never a crash.
This is the first time I'm trying a massive import.
I have tried to narrow it down, but it is complicated.
It would be very handy to include with future versions, the ability to ignore corrupted files, be they image files or sidecars.

**Comment by Nilvus** [comment]
@Lorenzoeffe: as import part had been completely rewritten for darktable 3.6, I close this one. Maybe you already install and use darktable 3.6. If you reproduce with darktable 3.6, just ask to reopen with a more precise step by step to reproduce. I have often imported a lot of photos at same time and never reproduce (with old and new import feature) but I'm on Linux. It could be a Windows specific one.
