### ISSUE TITLE
DT 3.4.1, Color Calibration Module causing program to crash when activating White Balance Picker

### ISSUE THREAD

**Issue by vasto7** [darktable-org/darktable#8182]
**Describe the bug**
When using the Color Calibration module, if the White Balance Picker is selected, the program crashes.  The behavior seems to be insensitive to all other setting within the Color Calibration module.  

**To Reproduce**
1. Open any file in DT. 
2. Open the Color Calibration Module
3. Select the White Balance Piker.
4. Watch the program crash.

**Expected behavior**
I expect to be able to use the Picker to select an area of the image to perform a white balance.

**Screenshots**
Screen is from moment before the program crashes.
![Screenshot (37)](https://user-images.githubusercontent.com/75090281/107581257-cc955480-6bc5-11eb-9c96-860218c99387.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1
 - OS: Windows 10 Pro
 - Open CL Activated
 - Radeon RX5700, Driver 20.12.1

**Additional context**
This behavior did not occur in DT 3.1.  It occurs during raw development in Scene referred workflow and even just using the module for a Jpeg.

**Comment by ralfbrown** [comment]
A hotfix for the Windows version was just released.  Please install 3.4.1-1.

**Comment by vasto7** [comment]
Sorry @ralfbrown , can't find this hotfix version.

**Comment by TurboGit** [comment]
@vasto7 : In the standard location https://github.com/darktable-org/darktable/releases/tag/release-3.4.1
