### ISSUE TITLE
Broken scrolling in "collect images" module's combo box.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#8186]
**Describe the bug**
When using a trackpad to scroll within the combo box in the "collect images" module, every option scrolled over is also, in turn, selected. This results in significant delays when thus scrolling, as well as the filling up of the "recently used collections" module with the filters scrolled over.

**To Reproduce**
1. (Optional) Load a database with a large number of images.
2. Select a collect option low down in the combo box (e.g., module order).
3. Reopen the combo box and try to select an option higher up in the box (e.g., film roll). This will require scrolling.
4. When Darktable is responsive again (with my database, this takes about a minute), note that the "recently used collections" box is completely full with every kind of collection filter between those selected in steps 2 and 3.

**Expected behavior**
That a new collection filter is selected only when an option in the combo box is _clicked on_, as was formerly the case; that the options in the combo box may be scrolled through in a timely manner.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1 and latest master (revision e29828a)
 - OS: Fedora 33

**Additional context**
Possibly related issues: #7864, #7969

**Comment by quovadit** [comment]
I have the same problem
 - OS: Manjaro Linux, Gnome 3.38.3
 - OpenCL not activated
 - Mesa Intel® HD Graphics 630 (KBL GT2)

**Comment by Nilvus** [comment]
You precise 2 issues here. The issue about scrolling after reopening combobox is not darktable one but a Gtk one (library used to display thing in the UI.

For the second one (recently used collections), this could be a darktable one. I will let someone else in darktable team that know that part better answer here.

**Comment by schwerdf** [comment]
The behavior with the "recently used collections" module is exactly what _should_ happen if every option in the combo box were clicked on, and I merely included it as a very obvious symptom of the actual problem.

**Comment by phweyland** [comment]
> The issue about scrolling after reopening combobox is not darktable one but a Gtk one (library used to display thing in the UI).

Not sure about this. The event "value-changed" is not a gtk one but a bauhaus one, which groups  "button-press-event",  "button-release-event", "scroll-event" and "key-press-event" preventing collect module to treat these events separately.

**Comment by Nilvus** [comment]
> > The issue about scrolling after reopening combobox is not darktable one but a Gtk one (library used to display thing in the UI).
> 
> Not sure about this. The event "value-changed" is not a gtk one but a bauhaus one, which groups "button-press-event", "button-release-event", "scroll-event" and "key-press-event" preventing collect module to treat these events separately.

I just remember similar scrolling issue with Gtk. But indeed, it could be something else.

**Comment by phweyland** [comment]
Thinking aloud...
The main reason for using bauhaus combobox is to have the ability to set up titles in the list. probably  some work to mirror this with gtk combobox...
On the other hand the bauhaus combobox is heavily used in dt and change the behavior may be tricky.

One possibility could be to add a property to the bauhaus combobox, like 'mute scrolling'.
By default no change compared to today. When set, "data-changed" would not be triggered for "scroll-event".
This would give the possibility to collect module not to recalculate the collection at each scrolling move, and just do it when the user actually selects an item.

Thoughts ?

**Comment by schwerdf** [comment]
I tinkered around with this a bit myself, and a modification equivalent to what was done in @phweyland's commit restores the scrolling to the expected behavior.

However, the underlying problem is not with the scrolling alone; it is that the collection recalculation should be taking place _only_ when the combo box closes, rather than at every "value-changed" signal. As mentioned in issue #7969, when there is any significant interval between the "value-changed" signal raised by a mouse click, and the consequent closure of the combo box, the UI displays visibly incorrect behavior.

**Comment by phweyland** [comment]
> However, the underlying problem is not with the scrolling alone; it is that the collection recalculation should be taking place _only_ when the combo box closes, rather than at every "value-changed" signal. As mentioned in issue #7969, when there is any significant interval between the "value-changed" signal raised by a mouse click, and the consequent closure of the combo box, the UI displays visibly incorrect behavior.

Agreed, #8196 doesn't resolve #7969. 
But this could be a bauhaus bug, "value-changed" is triggered twice but with different selected entries.... to be investigated .
"

**Comment by phweyland** [comment]
should cover both issues now. 
May need some better wording however.
