### ISSUE TITLE
Darktable 64bit for Windows crashes due to Windows Defender Antivirus

### ISSUE THREAD

**Issue by NextTherapist** [darktable-org/darktable#8188]
Even the newest Windows version (darktable-3.4.1.1-win64.exe, SHA256: 251453a776b7749b7f7701b7b58e6b9eba7747370c228bfa298f2053200d9fec) crashes/freezes in startup, when there is no exclusion for the darktable.exe file in Windows Defender Antivirus. The application window appears, but with no content, and a sandclock is shown.

First version I saw this behaviour was 3.2.1. My Windows is 10 64bit 20H2.

**Comment by ptilopteri** [comment]
sounds like the dev's for windows defender need to adjust for darktable,
or you need to continue to add exceptions.

windows defender needs to identify errant applications and should know that
darktable is not one.

**Comment by NextTherapist** [comment]
Sounds very unlikely to me. Windows devs should adjust Windows for every new version of darktable?
I guess access violations of darktable are responsible for the crashes.

**Comment by parafin** [comment]
What access violations? Do you have any specific information about what darktable executable is doing wrong? Because to us it looks like false positive by antivirus (darktable doesn't do anything it isn't supposed to do), which indeed can only be fixed by antivirus vendor. Nothing we can do here.

**Comment by Nilvus** [comment]
Windows Defender doesn't always allows not well known programs (for Microsoft) to be executed correctly without adding exclusions. So, sometimes you need to add exclusions. I don't any see any issue related to darktable. As you said, you don't have crash or freeze in startup if you add exclusion, so just add it.

I suggest you to read that doc from Microsoft support and especially unknow - unrecognized software part: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria

As Microsoft just said, it's impossible for any antivirus/antimalware programs to know all existing things or update to all upgrades made in all existing stuff!

I close this as it is something related to Windows Defender and just adding an exception on it.
