### ISSUE TITLE
Parametric Masks finer control

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#8194]
**Is your feature request related to a problem? Please describe.**
The parametric mask currently features 4 markers, 2 top, 2 bottom. The manual states, "The sequence of the markers always remains unchanged: they can touch one another but they cannot switch position." The problem is, not being able to switch position limits the potential of the tool.

**Describe the solution you'd like**
I would like the markers to be able to switch position, or at the least, for the top 2 markers to be able to switch position. For example, in g channel, the black top can be placed at value 100, while the white top can be placed at value 0, at the same time.

In other programs that allow it, I use this feature when making black or white to transparency gradients - it can be a nice way of adding contrast in only certain parts of the image (the black to transparency gradient on opposite side of light direction, the white to transparency gradient on same side as light direction). Used this way, it can also be a way to redo lighting in post. It would be great to be able to use darktable for this and not rely on other programs, and it would be possible using the graduated density filter, if the markers could switch position.

It would probably also require a styling change. Currently, both top markers are the same shade solid grey, while both bottom markers are the same shade with same border. This is not a problem when sliders can't switch, but if sliders can switch, it would be confusing which is which. Therefore the 'black' markers should be a dark/black shade, while the 'white' markers should be a light/white shade.

**Comment by elstoc** [comment]
I'm not entirely sure what you're trying to achieve here. Have you tried inverting the mask with the +/- button?

**Comment by parafin** [comment]
I guess the idea is to create a /\ curve that doesn't go up to 100%?

**Comment by SoupyGit** [comment]
Does this help?
Current mask allows this: /\
I would like this: X

Might be able to post some examples of what can be achieved in the coming days, but a bit under the weather, and busy, right now!

**Comment by SoupyGit** [comment]
OK, I have finally got around to doing a couple of picture examples.
The first raw is available here: https://discuss.pixls.us/t/playraw-tree-in-park/20938

Initial edit in DT (no graduated densities)
![tree-in-park-IMG_2464-dtnograd](https://user-images.githubusercontent.com/69561443/109918379-8df54480-7d02-11eb-822c-64eb6350b558.jpg)
:
Edit in DT + best attempt using graduated densities and parametric mask:
![tree-in-park-IMG_2464-dtgrad](https://user-images.githubusercontent.com/69561443/109918273-5e463c80-7d02-11eb-9e52-45ea201ed0e2.jpg)

[I tried to upload xmp but Github says "we don't support that file type"]

Initial edit in DT (no graduated densities), exported as 16bit tiff linear rec 2020, opened in PS where I added a very subtle light > transparency gradient, and a dark > transparency gradient, with a 'blend if' mask as per the screen shot.
![tree-in-park-IMG_2464_01-psgrad](https://user-images.githubusercontent.com/69561443/109918517-d280e000-7d02-11eb-85eb-2139c700aef5.jpg)

![tree-in-park-shadowsgrad](https://user-images.githubusercontent.com/69561443/109918533-d876c100-7d02-11eb-9660-144795094ea4.png)

This is a good test image for the cause, as the lighting is flat, and this technique allows to make the lighting a little more dynamic. We can see the PS edit allows for greater subtlety and naturalness than the darktable with graduated density, due to the finer control achievable in masks.

The second raw is available here: https://discuss.pixls.us/t/help-with-a-poorly-lit-portrait/20538

Initial edit in DT (no graduated densities):
![portrait-girl-red-DSC_2839-dtnograd](https://user-images.githubusercontent.com/69561443/109918867-6e125080-7d03-11eb-81b7-73a8028e8b1f.jpg)

Edit in DT with graduated densities:
![portrait-girl-red-DSC_2839-dtgrad](https://user-images.githubusercontent.com/69561443/109918894-79fe1280-7d03-11eb-87f2-74e8c7e2db47.jpg)

Initial edit in DT (no graduated densities), exported as 16bit tiff linear rec 2020, opened in PS where I added a light > transparency gradient, with a 'blend if' mask as per the screen shot, and a dark > transparency gradient.
![portrait-girl-red-DSC_2839-psgrad](https://user-images.githubusercontent.com/69561443/109919130-e2e58a80-7d03-11eb-82ff-abb93c6224e9.jpg)

![portrait-girl-red-highlightgrad](https://user-images.githubusercontent.com/69561443/109919440-60a99600-7d04-11eb-8216-9dd68229fc46.png)

Again we see the last version give a more subtle result. But the area I'd like you to pay particular attention to is the girls shirt - the texture and shadows. In the DT version it looks so much flatter. It is the masking options in PS that make texture like that possible.

**Comment by chhil** [comment]
>  [I tried to upload xmp but Github says "we don't support that file type"]

Rename the file to have a txt extension and then you can upload it.

**Comment by SoupyGit** [comment]
Ah, excellent. Here are the xmp's. These contain the gradients used in darktable. Just turn the gradients off to see how it looked without (as per initial edit, and version exported as tiff for PS).

[tree-in-park-IMG_2464.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/6083402/tree-in-park-IMG_2464.CR2.xmp.txt)
[portrait-girl-red-DSC_2839_02.nef.xmp.txt](https://github.com/darktable-org/darktable/files/6083404/portrait-girl-red-DSC_2839_02.nef.xmp.txt)
