### ISSUE TITLE
Selective white balance

### ISSUE THREAD

**Issue by MauDarktable** [darktable-org/darktable#8195]
**Describe the bug**
Hi all, I need to use Darktable white balance in a selective way but this module doesn't appear to be used with forms or parametric masks. There isn't the new instance option too.
Is there a way to make this possible?
I need to correct some artificial illumination in the foreground without change the illumination of the background but the module can't be "new instanced" to make this possible.
Any other colour module doesn't give me the same result.
Thanks a lot for your suggestion.

**To Reproduce**
Click on module and search for "New instance" option or for use the module with forms or parametric masks

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10 Professional
 - OpenCL activated? No

**Additional context**

**Comment by hgmarty** [comment]
Do you use the new "white balance" what is color calibration ? With this module, you can select a zone and make the white balance for that.

You can watch this [video](https://www.youtube.com/watch?v=U4CEN0JPcoM)

**Comment by MauDarktable** [comment]
Thanks hgmarty for your suggestion ma it isn't what I searching for.
So, for example, with another postproduction software... I open the image, i select the "White balance" module, I select the "Brush", paint with the brush on the image then move the temperature cursor to modify the paintbrushed area. Stop. It's so fast and so useful to correct some unwanted partial illumination on the shot. I want to be able to to this with Darktable if it's possible. For example I have a great sunset photo with some objects in the foreground light-painted with a led flashlight... the foreground light it's so cold and the sunset background it's warmer... I need this tool to fix this difference. Thank you so much.

**Comment by hgmarty** [comment]
For your example, you can use the color balance with blue in hightlights to fix warmer light and the complementary color (warm orange or yellow) in shadow to fix colder. It's easy. 
With the example you gave, it's more a color correction than white balance.

However, watch the video to understand this module.

**Comment by MauDarktable** [comment]
Thank you so much! With some options on this module I was able to reproduce the function that I need! Thanks!

**Comment by Nilvus** [comment]
So I think this could be close as it seems you find what you want. I doubt that White balance will change as color calibration allow much more things including what you ask here.
