### ISSUE TITLE
v3.4.1 Remove image/s from Map view

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#8201]
Not sure if this a long-standing issue that's not been reported, or if it's new to 3.4.1, but contrary to the manual which states that clicking an image (or shift+clicking a group) and dragging them back to the filmstrip will remove it/them from the map... does not work.
It appears to work, until you move/zoom your view, at which point, the images reappear.
Currently on Linux Mint 20, cinnamon DE.

**Comment by johnny-bit** [comment]
I need to check that but @phweyland - can you chime in here?

**Comment by phweyland** [comment]
I'd the impression to see that issue once, but I've been unable to reproduced it.
Is the issue stable in your case ?

With the current master and dt 3.4.0 everything works fine for me (debian sid).
I've tried to build 3.4.1 but I get a segfault at opening. :(

**Comment by brucewilliamsphotography** [comment]
Grrr. Well, that's just annoying. :)
I have, since logging this issue, shut down, restarted, and relaunched darktable, and what do ya know? It's working fine.
Sorry guys.
Close the issue.

**Comment by quovadit** [comment]
I can confirm that the bug exists in 3.4.0, but not always, and I have no idea how to reproduce it

**Comment by phweyland** [comment]
So please let this issue opened. Maybe somebody will find the guilty conditions...

**Comment by quovadit** [comment]
If the problem appears, you can see in the image information module that the coordinates are not removed after dragging it to the filmstrip. So you don't have to move/zoom to make the image re-appear on the map, even when leaving and re-entering the map-module the image is positioned on the map again :-(
This is even worse, because you think you have removed the coordinates, but they are still there...

**Comment by phweyland** [comment]
The problem is probably related to the initialization phase . 
The connection to thumbtable (filmstrip) drag and drop is made late but without any clear condition. Sometime this could fail. To be investigated.

**Comment by quovadit** [comment]
first way to reproduce the bug:
- clean config dir
- raw file without xmp file
- import raw file
- open map
- drag image to map
- drag image to filmstrip
- coordinates removed -> OK
- switch to lighttable
- open map again
- drag image to map
- drag image to filmstrip
- coordinates not removed -> NOK

**Comment by phweyland** [comment]
@quovadit Great !
You are right, the fact to go to lighttable and come back to map breaks the dnd.
Good catch. I'll try to debug that (unless you find the bug before ... :smiley: )

**Comment by phweyland** [comment]
Bug found. Thanks to you @quovadit !
