### ISSUE TITLE
Module-dependent shortcuts!

### ISSUE THREAD

**Issue by Xepo** [darktable-org/darktable#8202]
**Is your feature request related to a problem? Please describe.**
I'd love to use the keyboard more fully, but there's too much functionality throughout the app to give an independent key to each one, especially not in a memorable way.

**Describe the solution you'd like**
If you could set shortcuts that are only in-effect while a particular module is expanded, then you could use two-stage shortcuts, which would give you the ability to assign shortcuts to most functionality in the darktable, and hopefully memorable shortcuts.

For example, set a darktable-wide shortcut of <shift-F> to [Filmic RGB->Show], and module-specific shortcut of W to [white-relative exposure -> Edit].  Then no matter where you are in the darktable, you could hit shift-F, then W to start modifying white-relative exposure. 

I think this could be intuitive-enough that it may be worth setting up default shortcuts for most modules like this.  

**Alternatives**
The above is definitely my favorite implementation, but you could also achieve something similar by:
Allow mapping a key sequence to each shortcut. e.g. [shift-F then W] for the above.   If you go this approach, you could set up a Spacemacs like completion window.   The biggest downside here is that you're often adjusting many settings in one module.  It'd suck to have to hit, e.g. [shift-F W] to get white-relative exposure, then [shift-F B] to get black-relative exposure, then [shift-F D] for dynamic range.  

Oh, and thanks for a great piece of software!  This particular feature is by far my biggest personal gripe -- I just really dislike clicking to navigate through interfaces if I can help it.

**Comment by hgmarty** [comment]
See #8078
I think it will be amazing. It wiil have multiple shortcuts

**Comment by Nilvus** [comment]
As #8078 is a WIP about that, I close this one. #5063 issue is linked to #8078. @Xepo, so if needed you could add infos to #5063 issue.
