### ISSUE TITLE
Nikon Z6 II

### ISSUE THREAD

**Issue by Jacques0573** [darktable-org/darktable#8209]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by johnny-bit** [comment]
Duplicate of #8203 6898

**Comment by Jacques0573** [comment]
Bonjour,
Toutes les photos faites avec le Z6 _2 de Nikon en Nef (RAW) sont illisibles dans la chambre noire de darktable 3.41 alors que celles faites avec unD5600 Nikon sont lisibles.  Je penses donc que Darktable ne reconnait pas les Raw du Z6_2. J'aimerais vous envoyés mes photos faites en  compression sans perte puis en compression puis en pas de compression et enfin en 14 bits et 12 bits. Pourriez-vous m'indiquer en français la démarche à suivre.
Merci de votre compréhension.
Cordialement
Jacques Collomb
