### ISSUE TITLE
Error message about running darktable too large for screen

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#8223]
**Describe the bug**

If you try to start darktable a second time or the process is still running after some failure the databases are locked and a warning message will appear stating that
- databases are locked
- process no. xxx is still running

This is thousands of pixels wide and does not fit in a FHD-screen.

![error-message-dt-running-01](https://user-images.githubusercontent.com/46827407/107887937-f0c89c80-6f09-11eb-8589-61563990e922.png)
![error-message-dt-running-02](https://user-images.githubusercontent.com/46827407/107887935-f0300600-6f09-11eb-9b11-57193cd07b21.png)

**To Reproduce**

Most convinient: Have darktable running and starting it a second time

**Expected behavior**

Have linebreaks in the text of the error message so that the message window will be able to adjust to the screen width

**Screenshots**

see above

**Platform (please complete the following information):**
 System:    Host: Rechner Kernel: 4.19.0-14-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: Cinnamon 3.8.8 
           Distro: Debian GNU/Linux 10 (buster) 

darktable 3.4.1
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

obtained from OBS

**Additional context**

**Comment by Nilvus** [comment]
It's specific to Deutsch translation. If I test in english or french language, no issue like that one.

So you just need to update de.po and add break lines like it is in english with '\n'. If I'm not wrong, you already propose de.po update in the past. So you could certainly fix that. Or @MStraeten?

**Comment by ralfbrown** [comment]
Looks like an issue with the German translation of the text, which does not have hard linebreaks in the middle of paragraphs, unlike the English version.
Ping @rabauke .

**Comment by bilddateien** [comment]
OK, this is what I edited. Pls. check
[de.po.zip](https://github.com/darktable-org/darktable/files/5979882/de.po.zip)

**Comment by Nilvus** [comment]
> OK, this is what I edited. Pls. check
> [de.po.zip](https://github.com/darktable-org/darktable/files/5979882/de.po.zip)

Could you post a pull request?

**Comment by bilddateien** [comment]
That's what I'd like to do. But I have some issues with deviations between my fork and the dt repo - and there is a PR that was never merged and I don't find a way to delete this and so on ...
So I didn't want to create something that I'm not sure what happens.

Perhaps I will delete my fork completely and start from scratch ... one day - and then try again.

**Comment by Nilvus** [comment]
> That's what I'd like to do. But I have some issues with deviations between my fork and the dt repo - and there is a PR that was never merged and I don't find a way to delete this and so on ...
> So I didn't want to create something that I'm not sure what happens.
> 
> Perhaps I will delete my fork completely and start from scratch ... one day - and then try again.

You could simply use some commands :

`git branch -d branch-name` (to delete the branch related to your PR in your local clone folder ; use -D instead of -d to also delete branch in your fork)

And then, you could rebase your local master (be sure to not have any change on your side (or use git rebase for that). You could have some help about commands to use here: https://github.com/darktable-org/darktable/wiki/Hacking-on-darktable

If you want, for this time, I can post the pull request for you.

**Comment by MStraeten** [comment]
i can integrate this; it's quite similar to my current translation branch...

**Comment by Nilvus** [comment]
> i can integrate this; it's quite similar to my current translation branch...

So I let you that.

**Comment by bilddateien** [comment]
@MStraeten thanks for integrating.
@Nilvus: thanks for your help and sources. I'm simply an old hardware engineer and some of this stuff is not very obvious to me and I need peace and quiet to take a good look.
