### ISSUE TITLE
Color calibration color picker lead to crash

### ISSUE THREAD

**Issue by XAndrey** [darktable-org/darktable#8225]
**Describe the bug**

In v3.4.1 in color calibration module in mode adaptation=linear Bredford (ICC v4) when i choose color picker button "set white balance to detected from area" - darktable get crash at all. Bug log see in file.

**To Reproduce**

1. Go to darktable mode with .ORF raw picture
2. Click on "color calibration" module to get it on.
3. Choose mode adaptation=linear Bredford (ICC v4)
4. Click on "set white balance to detected from area"

**Expected behavior**

No crash. And i want to select area on picture to get white balance.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1
 - OS: Windows 7
 - OpenCL activated
 - Nvidia GTX 1060

**Additional context**

[darktable_bt_VG2UY0.txt](https://github.com/darktable-org/darktable/files/5978508/darktable_bt_VG2UY0.txt)

**Comment by ralfbrown** [comment]
Does this happen with other color pickers?  There was a hotfix for Windows to address this problem - please install 3.4.1-1.

**Comment by XAndrey** [comment]
No, other color picker works fine.

**Comment by XAndrey** [comment]
I can not install 3.4.1-1 because on link https://www.darktable.org/install/#windows is only 3.4.1 version.
Do you have compiled version 3.4.1-1 for windows?

**Comment by TurboGit** [comment]
Please install 3.4.1.1 which is available directly from GitHub.

**Comment by TurboGit** [comment]
I have proposed a PR to update the install page with links for 3.4.1. So closing now.
