### ISSUE TITLE
While importing 1000+ images the star to set up overlays does not stay open

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8234]
WSL Linux Ubuntu 20.4

DT 3.5.0+1098

While importing 1000+ images the star (toolbar) to set up overlays does not stay open. It's probably due to refresh of the main window that it opens and disappears and one cannot setup the overlay option. Once import is done it functions normally.

Talking about this toolbar.
![image](https://user-images.githubusercontent.com/1119439/107953557-4dd35980-6fc1-11eb-8327-d07bca01226f.png)

**Comment by Nilvus** [comment]
@AlicVB: this one probably for you

**Comment by AlicVB** [comment]
hmmm... I'll have a look later if there's a easy solution, but as said in another thread, there's probably lot of features that can have issues when used during an import...

**Comment by AlicVB** [comment]
ok, so in fact it's a pure gtk "issue".
What happend is that the overlay popup react as all gtk menu popup : if the focus is lost, the menu is closed. and each time you add a thumb widget, you put the focus on it, hence the popup is closing...

I'm not sure there's an easy solution for this. I let it open in case someone comes with a genius idea :)

**Comment by Nilvus** [comment]
@chhil: I add some labels but it would be good to have feedback from you if you still reproduce this issue in last master or not? Of course, if you don't reproduce it, think about closing it.

**Comment by chhil** [comment]
I am on the current release and no longer have means to build master. AliceVB knows what the issue is and if its not fixed it would still exist.
