### ISSUE TITLE
"scan for devices" is missing

### ISSUE THREAD

**Issue by johnmoelholt** [darktable-org/darktable#8242]
On Windows10 with darktable 3.4.1.1 i am missing the button "scan for devices" int he import section under lightable.
Also when attaching a camera to the system it does not show up.

![darktable-error](https://user-images.githubusercontent.com/79156490/108086234-723d3d80-7076-11eb-91ce-1d9d0d6b2855.PNG)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1.1
 - OS: Windows 10

**Comment by johnny-bit** [comment]
Please read the release log and the fine documentation. The devices are autoscanned now.

**Comment by johnmoelholt** [comment]
But the fine documentation stated 'When a camera is detected, it will show up in the device panel after pressing “scan for devices”'

**Comment by Nilvus** [comment]
> Also when attaching a camera to the system it does not show up.

So the issue is not in darktable. On what I understand the camera does not show up in your system, so the issue is related to your camera and your system. darktable could only scan devices recognized by your system.

**Comment by johnmoelholt** [comment]
Hi, no- the camera does show in the system (windows 10) but is not detected (shown) by darktable. It works fine with LightRoom classic or CaptureOne.

**Comment by TurboGit** [comment]
Try to un-mount from Windows to see if dt can access it.

**Comment by johnmoelholt** [comment]
Hi again - you cant unmount a camera in windows 10 (anymore) is it not treated as a usb drive.
