### ISSUE TITLE
Wrong selected images number

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#8249]
Number of images selected (on top of dt window) is not consistent with the selected images.
It is stuck whatever the images the user selects, even with ctrl-A.

Tested also on a fresh config.

It seems that dt_view_get_images_to_act_on() presents the same issue.

![image](https://user-images.githubusercontent.com/23012047/108222973-10351480-7118-11eb-8f35-cbf6c4c00c93.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+1108~ga281ab696
 - OS: debian sid

**Comment by phweyland** [comment]
bisect gives a31608fbd5a3559e68095c4e6f45ba52076af1be as the first bad commit.

Pinging @ralfbrown.

**Comment by ralfbrown** [comment]
Hmm, 8250 fixing this indicates that dt_collection_get_selected_count has side-effects beyond just returning the count.

**Comment by phweyland** [comment]
> Hmm, 8250 fixing this indicates that dt_collection_get_selected_count has side-effects beyond just returning the count.

No, just that the 1 here is the limit. Returns 1 image:
  GList *selected_imgids = dt_collection_get_selected(collection, 1);

A bit strange I agree...  :smile:
