### ISSUE TITLE
Selecting or Moving between images causes DT to crash.

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#8251]
DT
3.5.0+1010~g8e12e2d1a
Running on Win10 
Two different machines ..one intel one AMD

At random it seems but generally not too long after opening the software selecting an image to enter darkroom or while in darkroom hitting the spacebar or backspace to select a new image causes DT to crash.

Backtrace/debug  attached 
[darktable_bt_IFYYY0.txt](https://github.com/darktable-org/darktable/files/5997715/darktable_bt_IFYYY0.txt)
[darktable-log.txt](https://github.com/darktable-org/darktable/files/5997764/darktable-log.txt)

**Comment by Nilvus** [comment]
@todd-prior. If it's a random issue, it will be hard to see that fixed. I use intensively master and never had such issues. But I'm on Linux. Anyway, some developers use Windows and they probably would have seen that.

I close this one but feel free to reopen (or ask for it) with more information and a precise step by step way to reproduce, if you still have this issue in actual master.

**Comment by johnny-bit** [comment]
The issue should've been fixed in #8954
