### ISSUE TITLE
Canon EOS R5

### ISSUE THREAD

**Issue by TRipper76** [darktable-org/darktable#8257]
I would like to request support for the Canon EOS R5 camera.  I have already uploaded the RAW CR3 and C-RAW CR3 files.
The files were uploaded directly off the card right out of the camera. Full frame shot of an x-rite color checker.

Thanks,

**Comment by Nilvus** [comment]
CR3 support will be possible when exiv2 library will support container which is needed to decrypt Raw exif infos. This is expected soon. By now, we can't do anything in darktable.

**Comment by Nilvus** [comment]
And I close as this is duplicate of #5909
