### ISSUE TITLE
handling modules that were deprecated in v3.4

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8265]
Should we now remove modules that were deprecated in v3.4 from the deprecated modules group (i.e. make them fully hidden for new edits)?

How should we handle the documentation for them? We could remove the documentation entirely (which is perhaps overkill) or (my preferred approach) copy their documentation into a separate sub-section.

**Comment by TurboGit** [comment]
Not yet I would say, it was planed to have them 1 full year but now this is 6 months.

> How should we handle the documentation for them?

Good question. We could move them in a deprecated annex indeed. We may not want to remove the doc anyway as the modules will still be there for old edits.

**Comment by elstoc** [comment]
We need a 3.8 milestone :)

**Comment by TurboGit** [comment]
@elstoc : The PR is prepared for 3.8, pinging you to remove the corresponding documentation.

**Comment by elstoc** [comment]
I'm not sure how to approach the documentation. I'm reluctant to completely remove it, since the modules are still available for old edits.

**Comment by TurboGit** [comment]
Maybe moving then into an Appendix specific to all deprecated modules? But maybe we'll then need to do something for the internal dt help button...
