### ISSUE TITLE
Cored Dump 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8268]
WSL Ubuntu
DT 3.5.0+1135

Don't have steps , I was just trying to get to another app /window on my system and DT crashed.

Backtrace attached
[darktable_bt_QYJMY0.txt](https://github.com/darktable-org/darktable/files/6004086/darktable_bt_QYJMY0.txt)

**Comment by wpferguson** [comment]
Backtrace shows `in _display_module_trouble_message_callback (instance=<optimized out>, module=0x7fb02c1b1780, trouble_msg=0x0, trouble_tooltip=0x0, stderr_message=0x0) at /home/mchhil/darktable/src/views/darkroom.c:226`

Related/similar to #8262 and #8221

**Comment by johnny-bit** [comment]
@chhil - after fix that fixed #8262 and #8221 can you still crash darktable the same way with same backtrace? If not then I'd suggest closing the issue :)
