### ISSUE TITLE
Default image import steps in history

### ISSUE THREAD

**Issue by MauDarktable** [darktable-org/darktable#8275]
**Describe the bug**

Hi all, when import an image or folder on Darktable some develop steps are automatically applied by Darktable. Clicking on darkroom I can see about ten steps in my history. Is there a way to edit this default develop steps? For example, I want add the lens correction...
As I can see I'm able to create a new style but I can't understand if the style include values of develop modules or not... for example:
1. Import a RAW file.
2. Enable the lens correction module (for example for Nikkor 24-120mm), now it appear in my history as new step.
3. Save a new style.
My doubt is: if I apply this style to a RAW that has been shot with another lens, the style force Nikkor 24-120mm profile or adapt the module to the right lens? 
And which is the behavior of the style with other nine default modules? For example It apply the same value of white balance of the style or adapt it to the new shot?
Thank you so much!
I love Darktable and the community!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10 Pro

**Additional context**

**Comment by ptilopteri** [comment]
open the lens correction module and create a new
preset with the conditions selected that cover your desires.

if this satisfies your "issue".  please close this issue.

**Comment by MauDarktable** [comment]
Hi ptilopteri, thaks for your suggestion.
This is a workaround but I have to apply it manually file per file.
The default develop steps, instead, are applied to all imported files.
Another workaround is:

1. import
2. apply correction lens module to the first file
3. copy this step from history, select all other files and paste the step

Every two workaround need manual steps.
If I could edit the default steps I'll be able to add desired steps and they will be applied automatically at every import.
Thanks.

**Comment by ptilopteri** [comment]
if you make a preset for the lens correction module, you can
tailor it to fit your conditions and it will automagically be applied
on import for images matching the conditions you provide.  no 
added steps beside import.

**Comment by MauDarktable** [comment]
Perfect, You have blowed out my doubt! But still have to apply it file per file after import, right?
The workflow will be:

1. Import my files
2. Open one in darkroom
3. Activate the lens correction module
4. Repeat for every othe file

Right?

**Comment by ptilopteri** [comment]
there is no work-a-round for *new* images, only for those 
you have already worked.  

for worked images, you might try your described method for 
one image and then copy only that part of the "history stack"
in *append* mode, select the remaining images you want this applied
and paste to the history stack.
you would not need to work individual images in this manner.

and this is a common application, not a work-a-round.

have fun

and in the future, consider the mailing list for this type of "discussion" 
as it is not really an "issue"

and if satisfied, please close this "issue".
