### ISSUE TITLE
DJI FC6310 and FC6310S

### ISSUE THREAD

**Issue by gituser1102** [darktable-org/darktable#8287]
Past version 2.0.3 Darktable don't allow to edit DJI FC6310 and FC6310S DNG-files from camera. I only get a dark thumbnail and photo when trying to open those raw files. I do not have a newer version of Dt anymore, but maybe something to do with white balance, if I remember right. Version 2.0.3 opens those DJI FC6310 files although there is no lens correction. That can be done in Gimp afterwards. 

The camera has fixed 24mm lens and  1" Sony imaging sensor. Maybe the same sensor as in Sony RX100 III and later models.

**Comment by LebedevRI** [comment]
Seems to work for me with darktable master.
Please reopen if i'm wrong.

**Comment by gituser1102** [comment]
What dt version and what operating system you have. I am on Ubuntu 16.04 which is very stable and last time when I upgraded from dt 2.0.3, I could not open my dji files. Can not read white balance information was the error message. Oiva H.Lähetetty Huawei-matkapuhelimestani-------- Alkuperäinen viesti --------Aihe: Re: [darktable-org/darktable] DJI FC6310 and FC6310S (#8287)Lähettäjä: Roman Lebedev Vastaanottaja: darktable-org/darktable Kopio: gituser1102 ,Author 
Closed #8287.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/darktable-org/darktable/issues/8287#event-4355458315",
"url": "https://github.com/darktable-org/darktable/issues/8287#event-4355458315",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by parafin** [comment]
Latest release is 3.4.1, test with it.

**Comment by gituser1102** [comment]
Sorry, if I have been wrong. Ubuntu 16.04 is my system and latest Dt 
version cannot be used with it. 2.4.4 does not work with FC6310 
DNG-files. So, I have to use alternative raw editors.

Oiva H.



Roman Lebedev kirjoitti 2021-02-20 18:21:

**Comment by Nilvus** [comment]
> Sorry, if I have been wrong. Ubuntu 16.04 is my system and latest Dt version cannot be used with it. 2.4.4 does not work with FC6310 DNG-files. So, I have to use alternative raw editors. Oiva H. 

Or update Ubuntu. You will probably have similar issue with alternative software because Ubuntu 16.04 is just near 5 years old. Update it at least to 18.04 or even better 20.04. Then you could add this software repository to have last stable release of darktable: https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable
