### ISSUE TITLE
Windows 10 no import from SD-Card

### ISSUE THREAD

**Issue by iljarogoff** [darktable-org/darktable#8292]
**Describe the bug**
Trying to import from a SD-Card, but darktable not showing me an option to import. Only "File" or "Folder" are possible. SD-Card in my built-in Cardreader is recognised within Windows and can be accessed and read/written.

**To Reproduce**
Plugin the Card an nothing happens

**Expected behavior**
Additional import option should appear on lighttable module

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1.1
 - OS: Windows 10
 - OpenCL active
 - RTX3070

**Additional context**

**Comment by elstoc** [comment]
The additional option only appears if you are trying to download the images from a _connected camera_ not from a card reader. You will need to copy the files to your machine and edit them from there.

**Comment by jenshannoschwalm** [comment]
> SD-Card in my built-in Cardreader is recognised within Windows and can be accessed and read/written.

Writing so, you should be able to import via folder, you have to navigate to the path. Is that not possible?

**Comment by iljarogoff** [comment]
> 
> 
> > SD-Card in my built-in Cardreader is recognised within Windows and can be accessed and read/written.
> 
> Writing so, you should be able to import via folder, you have to navigate to the path. Is that not possible?

I could, but then, the files are not moved to my pictures folder. They remain on the sd-card and the sidecar files are written on the sd-card too

**Comment by jenshannoschwalm** [comment]
Right, it's just an import to the database and no copy.
