### ISSUE TITLE
Create Filenames using $(Sequence) > Only if Needed

### ISSUE THREAD

**Issue by mdrmike** [darktable-org/darktable#8299]
**Is your feature request related to a problem? Please describe.**
During [Darktable Import / Tethering](https://www.darktable.org/usermanual/en/preferences-settings/import/) the default file naming pattern is:  `$(YEAR)$(MONTH)$(DAY)_$(SEQUENCE).$(FILE_EXTENSION`

In addition to this, I like my files to include photo time, so my format string is:  
`$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)_$(EXIF_HOUR)_$(EXIF_MINUTE)_$(EXIF_SECOND)-$(SEQUENCE).$(FILE_EXTENSION)`

However, I don't want a `$(SEQUENCE)` added to the filename unless needed to generate a unique filename.  

Currently, darktable creates a unique sequenceID on every filename, which is unnecessary. It also makes reading long files names more difficult. Another benefit of having sequences added _only when necessary_ makes it easier to identify bracketed or bursts of photos.

**Describe the solution you'd like**

I'd like a pre-defined variable, perhaps something called `$(UNIQUE_SEQUENCE)` that I could use instead of `$(SEQUENCE)`, in order to accomplish this more flexible naming scheme. 

**Alternative Solution**

The darktable renaming pattern might be able to utilize a modifier instead of a new variable to indicate adding a sequence only when necessary to generate a unique filename. 

**Additional context**

I've used [exiftool](https://exiftool.org/exiftool_pod.html#Input-output-text-formatting) for years, and exiftool has this flexibility.

_Example:_ 
[exiftool -w FMT](https://exiftool.org/exiftool_pod.html#Input-output-text-formatting) includes a `count` variable (e.g. `%c` or `%C`) that is similar to Darktables' `$(Sequence)`.  Exiftool `%C` option adds a sequence(count) to EVERY file, just like Darktable currently works, but alternatively has a `%c` option _to ONLY add count AS NEEDED to create a unique filename._

Consider the following filenames to be imported:

_input filenames_
`DSC00001.CR2`   EXIF Create Date/Time:  2021-01-01   10:10:00 
`DSC00002.CR2`   EXIF Create Date/Time:  2021-01-01   10:10:03
`DSC00003.CR2`   EXIF Create Date/Time:  2021-01-01   10:10:04
`DSC00004.CR2`   EXIF Create Date/Time:  2021-01-01   10:10:04
`DSC00005.CR2`   EXIF Create Date/Time:  2021-01-01   10:10:04
`DSC00006.CR2`   EXIF Create Date/Time:  2021-01-01   10:10:07

`exiftool -dateFormat "%Y-%m-%d____%H_%M_%S" '-FileName<${DateTimeOriginal}%+C.%e'`

This exiftool command returns results similar to how Darktable works now. 
Note: by default exiftool does not add a sequence count to the first filename, but has the capability. I didn't show for simplicity.

_Output filenames_
> 2021-01-01____10_10_00.CR2
> 2021-01-01____10_10_03_1.CR2
> 2021-01-01____10_10_04_2.CR2
> 2021-01-01____10_10_04_3.CR2
> 2021-01-01____10_10_04_4.CR2
> 2021-01-01____10_10_07_5.CR2

`exiftool -dateFormat "%Y-%m-%d____%H_%M_%S" '-FileName<${DateTimeOriginal}%+c.%e'`
This exiftool command is similar to the option I'd like to see for Darktable:

_Output filenames_
> 2021-01-01____10_10_00.CR2
> 2021-01-01____10_10_03.CR2
> 2021-01-01____10_10_04.CR2
> 2021-01-01____10_10_04_1.CR2
> 2021-01-01____10_10_04_2.CR2
> 2021-01-01____10_10_07.CR2

**Comment by ptilopteri** [comment]
or just exclude $(Sequence) and have an option similar
to export, on conflict: "create unique filename".

which may already exist as I have not checked.

**Comment by todd-prior** [comment]
> or just exclude $(Sequence) and have an option similar
> to export, on conflict: "create unique filename".
> 
> which may already exist as I have not checked.

There is ...you can't configure it but if an identical name is encountered it will add a suffix with a number 1, 2 etc

**Comment by mdrmike** [comment]
@ptilopteri  Hmm... I'm not seeing it in preferences and I tested that idea before submitting request. Also, just retested and no luck? :crying_cat_face:  Maybe I did something wrong or I'm missing something?

**Here's what I tried:** 

1. Setup preferences (per above)
2. From lightroom, choose `import from camera` (memory card). And double checked settings.
3. Clicked image tab
4. Select a set of images; similar to the example I posted above which also contained a burst of four images within a two second time frame.
5. Import
6. Result: Only one image per second was created... other images with same exif-second timestamp I presume were overwritten or ignored.


![screenshot_20210302-175617](https://user-images.githubusercontent.com/259940/109742829-99226600-7b84-11eb-80f9-dbff111cb6b7.png)
![screenshot_20210302-180255](https://user-images.githubusercontent.com/259940/109742849-a0497400-7b84-11eb-90d2-23018dcb9310.png)
![screenshot_20210302-180525](https://user-images.githubusercontent.com/259940/109742872-a8a1af00-7b84-11eb-81ef-6ed5e53a952e.png)
![screenshot_20210302-181926](https://user-images.githubusercontent.com/259940/109742883-adfef980-7b84-11eb-871d-3e5f64d823ae.png)



Maybe you or @todd-prior point me in the right direction?  I'd prefer to control suffux, but don't actually care that much if it meets my basic needs.

**Comment by ptilopteri** [comment]
well, we are quite possibly trying to provide you with answers that relate
to different versions of darktable as you failed to provide the information 
requested when you filed this issue.

the configuration you show is not current to darktable master which I run.
it is somewhat difficult to GUESS the conditions you have.

**Comment by mdrmike** [comment]
@ptilopteri Oh wow ya, version would be helpful. Sorry! 

But are you saying you've tested `master` branch and it doesn't work this way?  Interesting.

I'm running current stable release of `darktable v3.4.1` installed on Ubuntu 18.04 via Flatpak per [darktable github readme](https://github.com/darktable-org/darktable#latest-release)

_Possibly worth noting, I still have an old darktable install via PPA `http://ppa.launchpad.net/pmjdebruijn/darktable-release/ubuntu` that I don't think I've run in a year ... but the v3.4.1 Flatpak version [should be sandboxed](https://docs.flatpak.org/en/latest/sandbox-permissions.html)—**(famous last words)**._ :grin:

**Comment by mdrmike** [comment]
I'm not going to install a dev version of darktable to fix this ... but I am interested if it's fixed in master branch? :eyes: 

FWIW, I removed both my old darktable PPA install as well as Flatpak install. Then rebooted.  Then I backed up & removed old darktable config. Finally, did a fresh install of `darktable 3.4.1` via PPA per [darktable github readme:](https://github.com/darktable-org/darktable#latest-release)
- [Install native packages and repositories for Linux](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable), picked Ubuntu distro icon and installed manually for Ubuntu 18.04


```
echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/graphics:darktable.list
curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics_darktable.gpg > /dev/null
sudo apt update
sudo apt install darktable
```

Darktable works as expected, but no difference from previous install. :smirk:

**Comment by pbrada** [comment]
I'd like to support the original request. 

Just checked on a fresh install of Darktable 3.6 on Linux (Mint 20.1), an attempt to import burst images (with same hour-minute-second timestamp) without $(SEQUENCE) in filename pattern results in only one image per second being imported plus a warning message "Couldn't expand to unique filename".  There is no preference to create unique filename on import.

FWIW, I use XnView to create unique filenames for burst images, similar reason as with exiftool mentioned by OP.

**Comment by TigerTim** [comment]
+1 for this feature request

**Comment by b1tt1** [comment]
I'd also be glad to see this feature implemented. I've used the same file naming based on year-month-day-hour-minute-second for years. I'm now moving from Lightroom to Darktable, and I was surprised to see this feature missing. Lightroom's import rename added a unique number after otherwise identical filenames, and that keeps the filenames generally shorter (unless you shoot bursts or bracket).

**Comment by quovadit** [comment]
as millisecond are available now, it would be great to expand this FR to MSEC / EXIF.MSEC 

This would solve my issue described in [10844](https://github.com/darktable-org/darktable/pull/10844#issuecomment-1024643685)

**Comment by solitone** [comment]
I'm on `darktable-4.0.1.1_arm64`. I confirm issue described by OP. 

I tested with filename pattern: `$(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)_$(EXIF_HOUR)$(EXIF_MINUTE)$(EXIF_SECOND)_$(SEQUENCE).$(FILE_EXTENSION)`, and all selected 198 images were imported.

Repeated the import test with filename pattern: `$(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)_$(EXIF_HOUR)$(EXIF_MINUTE)$(EXIF_SECOND).$(FILE_EXTENSION)`, and only 148 images out of 198 selected were imported. During import I got many warning messages like _couldn't expand to a unique filename for session, please check your import session settings_.

As other people said, I also think it would be nice if we didn't need to add a sequence number to every file, but just when needed--i.e. when date and time are not enough to generate a unique file name.

**Comment by briandipalma** [comment]
I worked around this by keeping `select only new pictures` ticked, `copy & import...` a directory, then rerunning the `copy & import...` with a manual sequence number added e.g.

`$(EXIF_YEAR)$(EXIF_MONTH)$(EXIF_DAY)-$(EXIF_HOUR)$(EXIF_MINUTE)$(EXIF_SECOND)-6.$(FILE_EXTENSION)`

just keep rerunning the import until your run out of pictures to import, you can see I had to increase up to `-6` manually. Really it should be done automatically but this isn't too bad as a workaround.
