### ISSUE TITLE
Opening old edit resulted in completely incorrect XMP with new modules being introduced.

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#8301]
I am not sure when I did the last edited these files. It was not too long ago ...maybe 6-8 weeks.
Opened them today to check on something and the previews were corrupt. I checked and the xmp files were completely misread and altered from the backup.

Version that made this change was 3.5_1158 on Windows 10...the original and the resulting file from opening in this build are attached...

[updated_P1040627.JPG.xmp.txt](https://github.com/darktable-org/darktable/files/6024559/updated_P1040627.JPG.xmp.txt)
[org P1040627.JPG.xmp.txt](https://github.com/darktable-org/darktable/files/6024560/org.P1040627.JPG.xmp.txt)

**Comment by TurboGit** [comment]
Really strange, between the original and new XMP there is lot of module added like negadoctor, channelmixerrgb, ashift, bilat, possibly some others. I can't believe that those modules have been added "automatically" even by a bug... looks very unlikely !

Did you have this issue with some others pictures ?

Can you reproduce by restoring the orginal XMP and reopening this picture ?

**Comment by todd-prior** [comment]
I was just going to do that now…….

Just opened a recent play raw of the girl in the bathing suit ..edited it a few days ago…I opened it today and the edit was okay but the retouch module was added 3x at the end of the stack with an instance of the mask manager in between each…there is nothing in the mask manager when you look in it so that is interesting.

I have noticed this in the past that sometimes the mask manager appears as the second or third line in the history stack when an older edit has been revisited.

I will revisit this original one that I have posted about…

I should add that I don’t use the database. I use the memory option. Not sure but I guess that creates a new temporary db each time and may lead to a routine that runs through all the imported xmp files in a way that it would not if I used the database???

**Comment by todd-prior** [comment]
[P1040631.JPG.xmp.210222130423.zip](https://github.com/darktable-org/darktable/files/6031070/P1040631.JPG.xmp.210222130423.zip)


It happened to one other image so in the end not too bad. I had a couple of duplicates for each so when I first looked I thought it might have hit the whole batch of images and there were 238 in the folder.

I will have to check if any other images had bilateral denoise...now surface blur I did see that conversion in the affected files but where all the channel mixer and negadoctor stuff comes from I have no idea.

I will keep a log and copies of any weird observations in xmp files. As I mentioned above and its not new I have seen but not really worried about the random appearance of the mask manager in xmp files when opening in a newer version of DT. If and when I note that I will share the info.

Thanks for your response.

**Comment by aquatix** [comment]
I have something similar, with edits that I did on one computer, not being applied on another, while importing the directory for the first time.

Multiple pictures are shown in the lighttable view for images that have multiple xmp's, but all images are reset to initial view, and the existing xmp's are overwritten as if they were written anew, causing all changes to be lost.
