### ISSUE TITLE
Collect images - No geotagging status proposed when associated with tag filter

### ISSUE THREAD

**Issue by Robert904** [darktable-org/darktable#8308]
**Describe the bug**
When trying to collect images in Lightable, if tag filter is selected, an additional geotagging filter do not propose the "tagged" and "not tagged" options.

When geotagging is associated with another type of filter (like Folder), proposing the same set of pictures, the options are present.

**To Reproduce**
1. In Lightable, go to "collect images"
2. Select "tag" filter, and select a specific existing tag
3. Select "Narrow down search"
4. Add a "geotagging" filter
No "tagged" or "not tagged" options are proposed in the list

**Expected behavior**
The geotagging filter should propose "tagged" and "not tagged" options

**Screenshots**
![image](https://user-images.githubusercontent.com/6376472/108883318-94e6cd80-7605-11eb-87b8-4ee38e88bbc7.png)

![image](https://user-images.githubusercontent.com/6376472/108883236-7bde1c80-7605-11eb-8e8c-20ed41e25130.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1.1
 - OS: Windows 10

**Additional context**
Same result with a clean newly created database and newly imported images

**Comment by quovadit** [comment]
I can confirm this bug with latest master

**Comment by phweyland** [comment]
@Robert904 Thanks for reporting.

**Comment by Robert904** [comment]
Tried on master, looks perfect, many thanks !
