### ISSUE TITLE
Regression: crash in undo

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8312]
**Describe the bug**

Undoing (Ctrl-Z) a shape deletion causes darktable to crash.

**To Reproduce**

1. Turn on drawn  masks for a module such as Exposure
2. Add two shapes (I used a circle and an ellipse)
3. Ensure that both shapes and the yellow blend mask are displayed
4. hover the mouse over one of the ellipse's control points
5. right-click to delete the ellipse
6. press Ctrl-Z to undo the deletion.  dt will now crash.

(It may be possible to further minimize the steps.)

**Expected behavior**
The shape should be restored.  This used to work.

**Platform (please complete the following information):**
 - Darktable Version: master 3.5.0
 - OS: Linux
 - no OpenCL
 - GCC 8.4

**Additional context**
Bisection indicates
```
7307aedb19ccccaf1f6bdeddbfbdf767f33e64d2 is the first bad commit                                                        
commit 7307aedb19ccccaf1f6bdeddbfbdf767f33e64d2
Author: Marco Carrarini <marco.carrarini@gmail.com>
Date:   Sun Feb 7 14:20:04 2021 +0100

    fix longitude string in tooltips
```
The strange thing is that this one-line change doesn't seem to have any relation whatsoever with the undo system.  But reverting this commit does eliminate the crash....  I haven't had time to trace what's going on in the function being called.

**Comment by Mark-64** [comment]
Confirmed in DT git master on Windows 10. I get this in the console:

`(darktable.exe:2716): GLib-GObject-WARNING **: 07:51:57.802: invalid cast from 'GtkDarktableToggleButton' to 'GtkDarktableButton'`

Also, if I build in debug mode I get no crash. something related to optimizations? In those cases bisect will not help much...

**Comment by ralfbrown** [comment]
Because I couldn't believe that that particular commit was the problem, I actually wound up doing the bisect three times from different starting points (closer in each time), and all three wound up on that exact commit as the first bad one despite using different commits along the way.  And as I said, reverting the commit on current master eliminates the crash.  So at  least compiling for Release is very consistent despite all other changes to the code.

I saw the GLib warning message both with and without crashes.

**Comment by Mark-64** [comment]
I think I found the issue, in history.c:659
```
dtgtk_button_set_active(DTGTK_BUTTON(bd->showmask),
                                hist->request_mask_display == DT_DEV_PIXELPIPE_DISPLAY_MASK);

```
should be 

```
gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(bd->showmask),
                                hist->request_mask_display == DT_DEV_PIXELPIPE_DISPLAY_MASK);
```

That eliminates the crash for me.
Please it, if it works I can do a PR

**Comment by ralfbrown** [comment]
Fix confirmed.
