### ISSUE TITLE
Tether doesn't work with Nikon D850, only skulls

### ISSUE THREAD

**Issue by bosnae** [darktable-org/darktable#8318]
Hello there,

I got me new laptop with Ryzen 7 4800H, 16gb DDRAM, SSD, about 4GB GPU, etc...
and of course I downloaded DarkTable to be able to use it on the new laptop.
But, doesn't work with either D600 or D850.

On old laptop I could connect both of them and shoot a while ago with old version, now with newest I cannot.
I am using latest downloadable version, and wold love to have opportunity to shoot tethered when possible.

Also, tried with Zadiag to change USB Driver, didn't work.
Other Tether software like qslrdashboard nikon, and can connect and shoot tethered.

I couldn't find the answer here on the GitHub board about.
So, if you fellas have any tips/tricks, plz let me know.l
I will appreciate it.
Thanks in advance.

**Comment by TurboGit** [comment]
I'm using a D850 and tested on Linux the tethering not long ago and it was working for me with 3.4 & current master.

Now I cannot guess which dt version you are using nor on which OS !

**Comment by bosnae** [comment]
Thanks for answering, and pointing, I need to write a bit better.
:)
I am using Win10, latest release and updates.
Now, I can import files, the cameras are recognized, and I can see tethering with camera, starting new session, etc...
but, as soon when I hit to take a photo, either in RAW or JPG, only I can see skulls, nothing else.

Now, on few Linux distro I have tried, before installing Ubuntu latest ver, it's working as soon when I install DarkTable and connect camera.
Without any issue Tethering works.
I know that DT have some issue with thethering under Win, but on this laptop for now I cannot install linux, and it's a pain to cary extra linux with old system (slower) with me.
:)

**Comment by TurboGit** [comment]
Ah Windows ! Answer is simple : As long as there is no little Windows dev working on dt there is no hope !

**Comment by bosnae** [comment]
If you need me to do something to reproduce this, or whatever I can do to help let me know.
I have Nikon D600  & D850, D300 for testing on Win 10 system.
Tested on Linux, works like a charm, right away.

**Comment by jenshannoschwalm** [comment]
Unfortunately we are / i am stuck right here. I worked on the gphoto2 code and by now understand quite well how that works. The windows usb device drivers somehow interfere with libgphoto but it's not understood yet what the exact problem is. There are a number of reported issues from the last years all pointing to this. We simply lack developing power on windows ...

**Comment by bosnae** [comment]
Hi Jens,
thanks for answering.
Like I wrote above, if it's anything I can help, to test, or to make some setting changes, let me know.
I am not coder, :) but if I can help with some other stuff with testing, I am here.
:)
Greetings from Heidelberg.

**Comment by bosnae** [comment]
Hello fellas,
any news on the issue with Tethering with Win10 and Nikon cameras?

Thanks.
