### ISSUE TITLE
DT 3.4.1- color calibration-CAT-"set white balance to detected from area"=>crashes DT

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#8319]
using DT3.4.1 on windows 10, test done on several RAW pictures, when click on button, DT 3.4.1 crashes.
sample of drawing is here
https://wetransfer.com/downloads/830834de0c1e5294117fe9d191ab373e20210224164907/8f3616d8797c729bb74bc8c703a8bd7220210224164907/3a4070

**Comment by Nilvus** [comment]
Please update darktable to 3.4.1.1 (https://github.com/darktable-org/darktable/releases/download/release-3.4.1/darktable-3.4.1.1-win64.exe) as a bug with many all picker in darktable 3.4.1 make darktable crash only in Windows. The 3.4.1.1 release (specific to Windows) fix it.
