### ISSUE TITLE
Crash caused in boxfilters

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8323]
**Describe the bug**
It's hard to reproduce, I guess I was just activating and deactivating an exposure module and then I received the obvious `double free or corruption (!prev)` line in the terminal I started DT in.

Here is the backtrace: 
[backtrace.txt](https://github.com/darktable-org/darktable/files/6038924/backtrace.txt)
And here the sidecar file: 
[P9141358.ORF.xmp.txt](https://github.com/darktable-org/darktable/files/6041867/P9141358.ORF.xmp.txt)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+1217~gb1f181e68 (current master)
 - OS: Ubuntu 20.04
 - OpenCL activated: yes

CC: @ralfbrown

**Comment by ralfbrown** [comment]
It's not the exposure module; toggling that is simply causing a recomputation.  There's a buffer overrun either in the box_min_1ch function where the free occurs, or possibly some time before it gets called (though I would expect the allocator to notice in that case).

It would help if you share the sidecar file from the image on which you had the crash.  Getting a backtrace from an executable compiled in debug mode would be helpful as well.

**Comment by Mark-64** [comment]
` box_min_1ch()` seems to be used only by haze removal.
Playing with it and exposure, I can't reproduce in Windows 10

**Comment by da-phil** [comment]
> It's not the exposure module; toggling that is simply causing a recomputation. There's a buffer overrun either in the box_min_1ch function where the free occurs, or possibly some time before it gets called (though I would expect the allocator to notice in that case).
> 
> It would help if you share the sidecar file from the image on which you had the crash. Getting a backtrace from an executable compiled in debug mode would be helpful as well.

Of course I'm aware it is not the exposure module, as already hinted in the title. 
I'm now building a debug binary in order to provide a more detailed backtrace, once I encounter the crash again :+1: 
I also updated my initial post with the sidecar file, if that helps.



> ` box_min_1ch()` seems to be used only by haze removal.
> Playing with it and exposure, I can't reproduce in Windows 10

Yes, as it can be seen in `#7` in the backtrace I provided, the problematic boxfilter call is invoked by the haze removal tool. 
I have another issue with the haze removal tool, which alters the colours strongly, although I'd exepect only changes to the luminosity, not the chromacity of the picture.

**Comment by ralfbrown** [comment]
> I have another issue with the haze removal tool, which alters the colours strongly, although I'd exepect only changes to the luminosity, not the chromacity of the picture.

Yeah, I've found it to so consistently leave a blue cast in shadows that I have a style which also adds an instance of Color Correction with the shadows pulled toward yellow....  I don't know whether that's a result of haze itself being blue-ish though.

I'll see whether I can figure anything out from the sidecar.

**Comment by Mark-64** [comment]
I applied your sidecar to an image of mine, but still not able to reproduce. The sidecar does not even have haze removal activated!

**Comment by da-phil** [comment]
> I applied your sidecar to an image of mine, but still not able to reproduce. The sidecar does not even have haze removal activated!

Oh, maybe I've disabled it for test purposes in the meantime :thinking: 
At least the backtrace clearly states that it has been active. I guess I can only try as much with the debug build and try to reproduce.



> > I have another issue with the haze removal tool, which alters the colours strongly, although I'd exepect only changes to the luminosity, not the chromacity of the picture.
> 
> Yeah, I've found it to so consistently leave a blue cast in shadows that I have a style which also adds an instance of Color Correction with the shadows pulled toward yellow.... I don't know whether that's a result of haze itself being blue-ish though.
> 
> I'll see whether I can figure anything out from the sidecar.

Exactly this blue cast is also present when I enable haze removal and I think this was not the same some months ago, it feels like a regression to me. Maybe it's worthwhile to create another issue for this issue.

Thanks for your continuous support ;)

**Comment by da-phil** [comment]
I've never experienced this specific crash again, hence closing the issue.
