### ISSUE TITLE
DT 3.4.1.1 Windows-version crashes while starting

### ISSUE THREAD

**Issue by silversurferarea** [darktable-org/darktable#8329]
My first post in github!

**Describe the bug**
Up to today morning the installed Windows-version 3.4.1.1 worked fine (since its install in January) and without any problems. The DT-start in the afternoon now crashes, when DT exe starts in the Win program starter menue. 

- no Win-updates processed, no changes in any WIN10-configuration
- virus scanner deactivated (Bitdefender)
- please find attached backtrace file:
[darktable_bt_1SYNZ0.txt](https://github.com/darktable-org/darktable/files/6044387/darktable_bt_1SYNZ0.txt)

**To Reproduce**
What happen:
After pressing start icon the DOS-prompt-windows lights up only for a milli-second, then further seconds later a crash dialog providing backtrace file location is showing, see attachment.

**Expected behavior**
DT should start as in the past done. From my side no changes of any WIN10 configurations.

**Screenshots**
see backtrace file attached

**Platform (please complete the following information):**
 - Darktable version: 3.4.1.1
 - OS: Windows10 20H2 Home build19042
 - No OpenCL activated
 - NVIDIA GTX 750TI
 - Ryzen 5 2600, 16GB RAM

**Additional context**
I did some steps for check:
 - remove current version from system , re-start WIN10, and re-install current version 3.4.1.1 --> no positive result
 - remove current version, delete program folder, delete db folder, re-start WIN10, re-install current version --> no solution
 - remove current version, delete program folder and db folder, re-start WIN10, install older version 3.4.0 (which worked fine in the past) --> no solution, same procedure with negative results when install 3.0.2
- install 3.4.1.1 in an additional program folder located on C: --> no solution

So my hope is, that the backtrace file provides more information regarding the cause/issue. 
Thank you very much in advance for your feedback. 

Best regards, Manfred

**Comment by Mark-64** [comment]
You say no OpenCL activated, but from backtrace it seems a problem related to OpenCL. 
You can try:
- update / reinstall your nVidia driver
- after installing DT, go to `C:\Users \<your-name>\AppData\Local\darktable` open the file darktablerc, secure there is the line `OpenCL=FALSE`. If it is set to `TRUE`, change it to `FALSE`

Please report the result

**Comment by silversurferarea** [comment]
Thank you for providing your steps. 

Today I´ve removed 3.4.1.1, updated the NVIDIA driver up to current version 461.72 and edited the darktablerc (located in folder C:\Program Files\darktable\share\darktable) as you described. 

The complete opencl-values of darktablerc as attached:
![opencl_entries_darktablerc](https://user-images.githubusercontent.com/79654353/109283314-ecac5100-781e-11eb-9951-5315a91097d8.jpg)

Then took a restart of WIN10, start DT --> no solution. A new backtrace file generated, please find attached. First issue seems a kernel problem?

NVIDIA driver information:
[NVIDIA System Information 02-26-2021 10-37-03.txt](https://github.com/darktable-org/darktable/files/6048749/NVIDIA.System.Information.02-26-2021.10-37-03.txt)

[darktablerc.txt](https://github.com/darktable-org/darktable/files/6048757/darktablerc.txt)

Additional information regarding WIN10 system. 
- AV1 support installed (from Win store)
- OpenGL and OpenCL-support installed (I never installed it manually, part of the WIN update 20H2?).

**Comment by parafin** [comment]
opencl=false is not enough, instead --disable-opencl option should be passed to darktable when starting. OpenCL implementation that causes the crash doesn't come from Nvidia, so updating Nvidia won't help, it is instead a Microsoft product: https://github.com/microsoft/OpenCLOn12. You probably can uninstall it somehow.

**Comment by parafin** [comment]
And in any case it's not a darktable bug.

**Comment by silversurferarea** [comment]
> 
> 
> opencl=false is not enough, instead --disable-opencl option should be passed to darktable when starting. OpenCL implementation that causes the crash doesn't come from Nvidia, so updating Nvidia won't help, it is instead a Microsoft product: https://github.com/microsoft/OpenCLOn12. You probably can uninstall it somehow.

It seems, the last tip from parafin (THANK YOU!) could be the solution; **DT 3.4.1.1 now starts**!

My steps iaw parafins tip:
- I´ve changed in the darktablerc file the value for opencl from =false into =disable.
![darktablerc_valuechange_opencl](https://user-images.githubusercontent.com/79654353/109304164-25a6ee80-783c-11eb-8671-1eee34b08fbf.jpg)

- A look in the WIN10 configuration - apps and features - provided an installed OpenCL-support package from Microsoft. I never installed it manually, but this package was installed and activated (part of WIN-update?) on my WIN system. This package I was able to uninstall.
![MS_OpenCL-support_package](https://user-images.githubusercontent.com/79654353/109304018-e5e00700-783b-11eb-8ecb-35fdc0e471ce.jpg)

- Another apps were uninstalled; the Microsoft HEIF support package and the AV1-support package. Not sure, that these apps are a problem for DT, it was installed before DT and DT ran well with this apps installed in the past.
- In an verification process I will re-install this last 2 app-packages step by step to verify the DT functionallity and will provide the results here in github.
