### ISSUE TITLE
Nikon Z2 2

### ISSUE THREAD

**Issue by Jacques0573** [darktable-org/darktable#8348]
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment]
Duplicate of #6898 / #7282.
These cameras are supported in dt master, i'm not sure what's the status for stable releases.

**Comment by johnny-bit** [comment]
Support for those cameras will be present in 3.6 release coming july.

**Comment by Jacques0573** [comment]
Merci pour la réponse

Le dim. 28 févr. 2021 à 21:49, Hubert Kowalski <notifications@github.com> a
écrit :
