### ISSUE TITLE
Some export dialog windows have different headerbar than other dialog windows

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#8353]
**Describe the bug**

By working on CSS, I just see that, at least, 2 dialog windows have a slightly different header bar than all other dialog windows:
- export one on shortcuts tab of preferences
- export in tags module

**To Reproduce**
Just click in export button in 2 cited ones to display header bar. Check it and compare to other dialog windows (import one, or even image and folder in import windows or preferences ones.

See good and default headerbar:

![2021-02-27_21-10](https://user-images.githubusercontent.com/45535283/109398990-ecec3f80-7937-11eb-954f-570e14ce060b.png)

And compare to ugly, wrongly set one in the 2 export dialog windows cited:

![2021-02-27_21-07](https://user-images.githubusercontent.com/45535283/109399001-04c3c380-7938-11eb-91af-c153f15783b7.png)

With Gtk Inspector tool, I see a difference in widget between all good dialog and those 2 export ones. In export ones, first box below headerbar has an id "horizontal" like in all other good the box id is "vertical".

See screenshot of Gtk inspector tool below, for wrongly export ones:
![2021-02-27_21-01](https://user-images.githubusercontent.com/45535283/109399071-6edc6880-7938-11eb-8acc-a88f6e4887f0.png)

Hope this will help to fix that as it's clearly a Gtk thing (not CSS one).

@elstoc and @phweyland: as you work on those parts as I remember, maybe you will quickly know how to fix that? Or, @dterrahe? Thanks.

**Expected behavior**
Have all dialog windows with same headerbar

**Platform (please complete the following information):**
 - Darktable Version: latest master
 - Ubuntu 20.10 with Gnome 3.38.3

**Comment by phweyland** [comment]
Strange, I don't get your layout (in particular the placement of the buttons) . Here what I have (the buttons are always in the bottom of the window):


![image](https://user-images.githubusercontent.com/23012047/109401599-59fad780-792e-11eb-9d0c-a246875ed143.png)

![image](https://user-images.githubusercontent.com/23012047/109401695-d8577980-792e-11eb-804e-97fac98032b0.png)


![image](https://user-images.githubusercontent.com/23012047/109401658-a7774480-792e-11eb-8956-510ac105eef2.png)

**Comment by Nilvus** [comment]
> Strange, I don't get your layout (in particular the placement of the buttons) . Here what I have (the buttons are always in the bottom of the window):
> 
> ![image](https://user-images.githubusercontent.com/23012047/109401599-59fad780-792e-11eb-9d0c-a246875ed143.png)
> 
> ![image](https://user-images.githubusercontent.com/23012047/109401695-d8577980-792e-11eb-804e-97fac98032b0.png)
> 
> ![image](https://user-images.githubusercontent.com/23012047/109401658-a7774480-792e-11eb-8956-510ac105eef2.png)

The layout is not the issue. What I have is just because of my Gnome theme, that put buttons in headerbar instead of bottom dialog window.

Tge issue is that those 2 export dialog windows are not built same way than other dialog window. See my comment about box set with horizontal id instead of all other set with vertical one.

**Comment by phweyland** [comment]
> Tge issue is that those 2 export dialog windows are not built same way than other dialog window. See my comment about box set with horizontal id instead of all other set with vertical one.

Why it would be an issue to use an horizontal box ?
BTW the tag export dialog is the standard file chooser dialog...

**Comment by phweyland** [comment]
I'm afraid that the Gnome theme which doesn't behave perfectly here ...

**Comment by Nilvus** [comment]
> > Tge issue is that those 2 export dialog windows are not built same way than other dialog window. See my comment about box set with horizontal id instead of all other set with vertical one.
> 
> Why it would be an issue to use an horizontal box ?
> BTW the tag export dialog is the standard file chooser dialog...

The issue is not to use a thing or not. The issue is that headerbar are not built same way between similar dialog windows. All dialog windows use this box with vertical id and that's only on those 2 ones that I have issue and they are the only one with the box with horizontal id. So I suppose something is not built same way for those 2 ones in Gtk code. And the issue is for me there. I don't know how to check and fix that but I'm quite sure those 2 dialog windows have a code that could be updated to match other dialog windows in darktable code. And so the Gnome theme doesn't behave perfectly, but it's a consequence, not the cause.

**Comment by Nilvus** [comment]
> I'm afraid that's the Gnome theme which doesn't behave perfectly here ...

It's only on those 2 dialogs windows that it doesn't behave perfectly. Nowhere else and in no other apps, even if buttons are in headerbar.

**Comment by Nilvus** [comment]
I've just understand why they are different: just because of field text to enter name that we have. I could maybe fix that with CSS by adding a tag in headerbar. Will check that. If you have any other key to help.

And just know that buttons in headerbar is the default behavior of Gnome apps, not related to a theme. See: https://developer.gnome.org/hig/stable/header-bars.html.en

**Comment by Nilvus** [comment]
Ok, forget all that. I've find how to deal with that with CSS. A fix is coming. Sorry for the noise and thanks anyway @phweyland for your time.
