### ISSUE TITLE
Custom ratios of crop in - GUI

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#8367]
**I know that custom crop ratios is available.** But! Editing the config files is not the most elegant way and is not trivial for most of users.

Why important is custom croping?
Firstly it's an basic future. We are using daily in press & print.
OK, most of photographer is not newspaper editor, but custom crop is very important in photo-printing too. Today the borderless prints is commonly used, just look a trending exhibition or a canvas on the wall of modern living room. You see frames? No.

Borderless prints need custom edge ratios. If we want a 60x40cm print with 5mm thickness we need minimum +2cm for each side (just try laminating a print...) so the total size is 64x44cm and aspect ratio is 64:44. The prints have wide variety of ratios depend on the thickness and type of materials. For egs. our club last exhibition made from 70x50cm prints what need 76:56 aspect ratio.

I think rewriting the rc with the actual ratios in every time is simple nonsense.
If its not too big request, please please add an user ergonomic option to the GUI. We crying for it many-many years ago. It's not incidental.

**Comment by ralfbrown** [comment]
You could also create a preset with the desired ratio and apply that.

**Comment by vsz1lu** [comment]
Yes, I do it at now, but it's not user friendly method. An input field on the GUI is far-far ergonomic - and trivial for all of the users.

**Comment by elstoc** [comment]
> I think rewriting the rc with the actual ratios in every time is simple nonsense.

You should only have to update darktablerc once, unless you reset your config, though perhaps the user manual could provide better instructions.

Might be worth mentioning in #6736.

**Comment by vsz1lu** [comment]
> > I think rewriting the rc with the actual ratios in every time is simple nonsense.
> 
> You should only have to update darktablerc once, unless you reset your config, though perhaps the user manual could provide better instructions?
> 
> Might be worth mentioning in #6736.

The main problem that this future is missing from the beginning however it's really basic option - I can't understand why not implemented in the very first beta a lot of years ago. And the new dpi controlled exporting it's a half-armed giant without real, gui adjusted custom crop.

**Comment by elstoc** [comment]
> I can't understand why not implemented in the very first beta a lot of years ago.

Devs implement features that they will find useful, mostly. Persuade a dev of its usefulness and it will get implemented. For me that would be a pretty niche feature. I usually use freehand crop, and I don't have an issue with adding lines of text to a file to get what I want. We could expose a text box in the preferences to allow the user to manually enter them but you'd still have to write the text in an appropriate format. 

I don't object to the idea but it doesn't feel (to me) as obviously vital as it does to you.

> But it looks like as a "secret" option. :)

If people don't read the user manual, lots of things will remain "secret". IMO both the ability to add custom ratios to the drop-down and the ability to key ratios manually are well documented.

**Comment by vsz1lu** [comment]
RTFM you're right, I can totally agree. The other side: the most of image editor softwares like Rawtherapy, GIMP etc. use self-evident method for setting the exact crop. darktable not.

**Comment by MStraeten** [comment]
simplest way is to add the info ("right click to enter a custom ratio") to the tooltip 
btw: exact crop ist quite a further set of entry fields ...

**Comment by mdrmike** [comment]
> simplest way is to add the info ("right click to enter a custom ratio") to the tooltip

However:  "right-click" on "aspect" field is no different than "left-click". The manual also refers to a combobox... suggesting an editable field. But its a non-editable dropdown on ubuntu. Hmm..?

No "field" to add ratio:
![screenshot_20210310-100933](https://user-images.githubusercontent.com/259940/110682029-59b0d680-818f-11eb-9737-edfafe5e5514.png)

---

Worse, following the section [ASPECT (main tab)—in the manual](https://darktable.gitlab.io/doc/en/modules.html#crop_and_rotate) and adding (this or something like it) `plugins/darkroom/clipping/extra_aspect_ratios/foo=1.91:1` to `$HOME/.config/darktable/darktablerc` results in nothing added to the list. Again. Hmm?  

#### System Info
- Darktable 3.4.1 
- ubuntu 18.04.5 
- libgtk-3.22.30
- PPA: per [README](https://github.com/darktable-org/darktable/blob/darktable-3.4.x/README.md#latest-release)

---

Is this known/expected on ubuntu 18.04 or a bug? possibly exclusive to my setup? idk. should I file as a bug. Don't mean to pile on

**Comment by elstoc** [comment]
> However: "right-click" on "aspect" field is no different than "left-click"

Yes you're right. **Click** on the aspect drop-down, type your desired ratio and press enter.

> The manual also refers to a combobox... suggesting an editable field.

You can click it and type to enter a value, though in Gtk the term combobox is generic and can also just mean a selectable drop-down list of options (without the ability to type anything).

> Worse, following the section ASPECT (main tab)—in the manual and adding (this or something like it) plugins/darkroom/clipping/extra_aspect_ratios/foo=1.91:1 to $HOME/.config/darktable/darktablerc results in nothing added to the list.

`plugins/darkroom/clipping/extra_aspect_ratios/foo=191:100` works fine for me. You have to use integers.

**Comment by mdrmike** [comment]
@elstoc  **Wow! Thanks! That works!** I've used darktable for 3+ years... that's "not obvious." (even after reading manual, nothing in the UX interface suggests to the user it'll take input in a drop down field).

I can't enter fractions, such as Instagram landscape: `1.91:1`  ... but whole number ratios such as `19:10` or `191:100` works. Thanks!

> Also please note that you have linked to the old version of the user manual. The user manual for darktable 3.4.1 is now [here](https://www.darktable.org/usermanual/en/) and for the current development version (the one I've just changed) [here](https://darktable-org.github.io/dtdocs/).

Thanks. Ya, I noticed the link to old manual and started to link to current manual, but info was correct. That URL link came from darktable clicking 1) the :question: in  Darktable interface, and 2) clicking "aspect" label in the interface.

![screenshot_20210310-115714b](https://user-images.githubusercontent.com/259940/110691396-f24c5400-8199-11eb-9201-56b85d9dfa9d.png)

**Comment by elstoc** [comment]
> That URL link came from darktable clicking 1) the question in Darktable interface

Yes we're in transition to a new manual at the moment. Those links should be updated for darktable 3.6.

**Comment by johnny-bit** [comment]
@AlicVB - I thought about "working" on this issue, since essentially the fix here would be to add another line in the tooltip that user can edit the ratio by simply entering value in `width:height` format or decimal... and maaaybe some hint in top bar... Would you like me to propose a PR or are you already deep into c&r rewrite and you'd rather take it?

**Comment by AlicVB** [comment]
yep, feel free to propose a PR, I'm quite busy these days...
Thought I'm not sure it's worth the pain to change things in c&r, better change it only in the new crop module ;)
Thanks !
