### ISSUE TITLE
"double CAT" not shown when changing image in darkroom

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8371]
**Describe the bug**
When a CAT is selected in two Color Calibration modules, the "double CAT" warning and the red triangle in module header is shown when opening the image from lighttable, but it is not when switching to the same image while in darkroom

**To Reproduce**

1. Start with a test folder with one image, create a duplicate
2. For the duplicate, create a second instance of color calibration and intentionally apply a second CAT. The red warning sign will appear
3. Go back to lighttable, open the second image, the red sign is shown correctly in the header of the second color calibration module
4. Now, while in darkroom, go back and forth between the first and the second image using the filmstrip
5. When switching to the second image, the red sign will flash briefly and then disappear
6. Also clicking the header to the second color calibration model to expand it will not show the warning. It takes clicking to the first module and back to the second to make the warning come back

**Expected behavior**
The warning is shown in the second module in all circumstances

**Screenshots**

When changing image in darkroom
![image](https://user-images.githubusercontent.com/43290988/109499659-7bc29e80-7a95-11eb-881c-b390915b40c2.png)

When opening from lighttable
![image](https://user-images.githubusercontent.com/43290988/109499722-909f3200-7a95-11eb-904b-6ccfbc4ede71.png)

**Platform (please complete the following information):**
 - Darktable Version: git master
 - OS: Both Windows 10 and Linux
 - OpenCL activated
 - nVidia 1060

**Comment by chhil** [comment]
The behavior I have seen...
(not duplicate based)
Depending on when you create a second instance, the second instance will get created as bypass and does not show the warning (this is the behavior that should prevail).
But when the pipeline is "working" and second instance is created, it's not created as bypass and the warning pops up.

**Comment by Mark-64** [comment]
Just to clarify, the issue has nothing to do with duplicates, it is exactly the same with different images. It is just the behavior of the double CAT warning is different when you open the image from lighttable vs when you change the image in darkroom

**Comment by elstoc** [comment]
Reproduced in current master but after a couple of hours fruitless hacking I'm nowhere near the cause or solution.

**Comment by Mark-64** [comment]
@elstoc same here, I couldn't  wrap my head around this issue, so far.
I noticed that the function `_iop_panel_label()`, which is the one adding the trouble sign is called many times (way too many, there is some duplication) by different functions.
from the call hierarchy here
```
_iop_panel_label(GtkWidget *, dt_iop_module_t *) : void
	_iop_gui_update_header(dt_iop_module_t *) : void
		dt_iop_gui_set_expander(dt_iop_module_t *) : void
			_add_module_expander(GList *, dt_iop_module_t *) : void
			dt_dev_change_image(dt_develop_t *, const int32_t) : void
			dt_dev_reload_history_items(dt_develop_t *) : void
			dt_iop_gui_duplicate(dt_iop_module_t *, gboolean) : dt_iop_module_t *
			enter(dt_view_t *) : void
		dt_iop_gui_update_header(dt_iop_module_t *) : void
			_display_module_trouble_message_callback(gpointer, dt_iop_module_t *, const char * const, const char * const) : void (2 matches)
			_iop_gui_rename_module(dt_iop_module_t *) : void
			_rename_module_key_press(GtkWidget *, GdkEventKey *, dt_iop_module_t *) : gboolean
			dt_dev_change_image(dt_develop_t *, const int32_t) : void
		dt_iop_reload_defaults(dt_iop_module_t *) : void
			_dt_dev_load_pipeline_defaults(dt_develop_t *) : void
			dt_dev_change_image(dt_develop_t *, const int32_t) : void
			dt_dev_reload_history_items(dt_develop_t *) : void
			dt_iop_gui_duplicate(dt_iop_module_t *, gboolean) : dt_iop_module_t *
			dt_iop_gui_reset_callback(GtkButton *, GdkEventButton *, dt_iop_module_t *) : void
			enter(dt_view_t *) : void
	_iop_gui_update_label(dt_iop_module_t *) : void
		dt_iop_gui_update(dt_iop_module_t *) : void
			_blendif_change_blend_colorspace(dt_iop_module_t *, dt_develop_blend_colorspace_t) : gboolean
			_blendif_hide_output_channels(GtkMenuItem *, dt_iop_module_t *) : void
			_blendif_show_output_channels(GtkMenuItem *, dt_iop_module_t *) : void
			apply_preset(const gchar *, dt_iop_module_t *) : void
			dt_dev_change_image(dt_develop_t *, const int32_t) : void
			dt_dev_pop_history_items(dt_develop_t *, int32_t) : void
			dt_iop_gui_duplicate(dt_iop_module_t *, gboolean) : dt_iop_module_t *
			dt_iop_gui_reset_callback(GtkButton *, GdkEventButton *, dt_iop_module_t *) : void
			dt_masks_iop_update(dt_iop_module_t *) : void
			expose(dt_view_t *, cairo_t *, int32_t, int32_t, int32_t, int32_t) : void
			preset_iop_module_callback(GtkAccelGroup *, GObject *, guint, GdkModifierType, gpointer) : gboolean
	dt_iop_gui_set_expander(dt_iop_module_t *) : void
		_add_module_expander(GList *, dt_iop_module_t *) : void
		dt_dev_change_image(dt_develop_t *, const int32_t) : void
		dt_dev_reload_history_items(dt_develop_t *) : void
		dt_iop_gui_duplicate(dt_iop_module_t *, gboolean) : dt_iop_module_t *
		enter(dt_view_t *) : void
```
you can see that it is called more times from` dt_dev_change_image()` than `enter()`, so I guess some of the excess calls are wrong.

**Comment by elstoc** [comment]
> `_iop_panel_label()`, which is the one adding the trouble sign is called many times [...] you can see that it is called more times from `dt_dev_change_image()` than `enter()`

I'd be careful about reading too much into this since `dt_dev_change_image` has to restore the UI back to default before loading the new image, so this perhaps causes some additional updates.

You can see the icon flicker on and off (specifically on-off-on-off) when you move images, and the double CAT error appears on stderr 3 times. If you enter via lighttable the same error appears 4 times (and you don't see the visual toggling).

**Comment by elstoc** [comment]
looks like when the pipe is being processed, the CAT warning is removed from both modules. Have added a call to `declare_cat_on_pipe()` in the `process()` code and everything seems to work now. Please can you test #8392 and confirm.
