### ISSUE TITLE
Real time vector mask feedbak preview.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8377]
**Is your feature request related to a problem? Please describe.**
Working with vector mask in darktable is great. But sometimes, mainly working in details is a little difficult positioning vectors in specific locations without lost the main picture and things like feather radius.

**Describe the solution you'd like**
Beside use the zoom at 200 and 400% it would be great have a real time feedback of the vector position in a zoom of 1600% or more to get detail. A little preview at the top left corner of the photography can be great.
A similar use of this preview is seen in tracking software.

Of course, this preview would be optional and can be enable or disable, even can be disabled by default.

![Feature Request](https://user-images.githubusercontent.com/67672868/109568110-76288100-7ab4-11eb-92bf-dd40e428b0b7.jpeg)

**Comment by TurboGit** [comment]
Do you know that you can zoom while editing nodes using key A + scroll ? (A or Q don't remember the default).
