### ISSUE TITLE
Color picker tool crash

### ISSUE THREAD

**Issue by pahervin** [darktable-org/darktable#8378]
A click on the color picker button crashes DT

1. Open an image in the darkroom
2. Open the exposure module
3. Open the parametric mask
4. Select a data chanel
5. Click on the zone color picker button
6. DT crashes

Same issue with the color calibration module

The zone color picker worked with the version 3.2.1

* darktable version : 3.4.1
* OS                : Win10
* Memory            : 8Gb
* Graphics card     : Intel UHD graphic 620 + Radeon 520
* OpenCL installed  : yes
* OpenCL activated  : both tried

**Comment by difrkaguilar** [comment]
I think darktable version 3.4.1.1 fix this issue.

**Comment by pahervin** [comment]
Actually the only released 3.4.1 version for Windows is the 3.4.1.1.
So this issue is about the version 3.4.1.1

**Comment by pahervin** [comment]
I did not notice the 3.4.1.1 version release.
The issue is fixed.
Thanks
