### ISSUE TITLE
Switching images without a "grayout" phase would facilitate visual comparisons of edits

### ISSUE THREAD

**Issue by grothesque** [darktable-org/darktable#8387]
**Is your feature request related to a problem? Please describe.**
In darktable 3.4.1, when switching images in the darkroom, the old preview image and histogram is grayed out while the new ones are being computed.  On a slow machine this "grayout" phase can take several seconds.

Switching between images could be made more useful for comparing different edits (of the same raw file, or of similar shots), if the preview and histogram would replaced instantaneously, without a blackout phase.  Comparing two similar images is much easier (at least for me, but I imagine that this must be universal), if the images are swtiched without a blackout phase.

I know that such comparisons can be achieved with snapshots, but this
- requires additional UI interaction,
- does not work for the histogram.

Is the "grayout" a conscious design choice?

**Describe the solution you'd like**
Darktable could stop erasing the old preview image and histogram only to replace them by the new ones once these are ready.

**Comment by MStraeten** [comment]
it’s simply the result of missing processing power (full pixel pipe and preview pixelpipe can be processed in sequence or parallel depending on your hardware). If you have an opencl capable gpu you can optimize how the processes are distributed to the individual processors. 
you also can reduce the size of the preview to speed up the processing.

**Comment by AlicVB** [comment]
> Is the "grayout" a conscious design choice?

yes it is... it's to cover your exact case : imagine what you would think if you have a "big" image next to the current one : you press "space" and... nothing ! dt seems "freezed" for about 10 s. (or way more if you have a big pano) before displaying the next image. Not good at all !
We have also tried to show a msg saying that dt is loading the next image, but that was not visually suffisient either...

In fact, for what you want, dt already has exactly what you want. It's called "culling" and it will switch to next image instantaneously but the way how it works can't be used for darkroom.

**Comment by Nilvus** [comment]
I would also add that we also had in the past the exact opposite issue about that by considering image and histogram of previous edit still there when switching as a sort of freeze. See for example this issue (related to histogram): https://github.com/darktable-org/darktable/issues/3763

And I confirm that is not the good way to compare images. You have culling mode and snapshots one. This won't be fix so, I close it.

**Comment by grothesque** [comment]
Thanks for the explanation.

For me, the currently shown message ("working ...") is enough to show that something is going on.  I know this, because before switching to darktable I was using Olympus Viewer in a VM: it is even slower and has many warts, but it does switch images seamlessly.

Since darktable is a program that requires a serious investment of time from any user, I would expect that few people would be surprised by such apparent "freezing".

> In fact, for what you want, dt already has exactly what you want. It's called "culling" and it will switch to next image instantaneously but the way how it works can't be used for darkroom.

Indeed, culling in single-image-mode does what I wanted except that it does not show a histogram.  Thanks for the hint!

**Comment by Nilvus** [comment]
> Indeed, culling in single-image-mode does what I wanted except that it does not show a histogram. Thanks for the hint!

Of course. But the better way to edit an image is at first with our eyes. The histogram is just a good help!

**Comment by grothesque** [comment]
Actually, culling mode behaves strangely for me in darktable 3.4.1.

For some images, it shows the edits that I just did in the darkroom (like adjusting exposure).  For other images, it stubbornly shows the embedded JPEG file, although I just adjusted the edit in the darkroom.

**Comment by AlicVB** [comment]
> For some images, it shows the edits that I just did in the darkroom (like adjusting exposure). For other images, it stubbornly shows the embedded JPEG file, although I just adjusted the edit in the darkroom.

then that's a bug. Can you open a new issue and document it so it's not lost ? Thanks !

btw, if you want to see images one by one, better use sticky preview. It's almost the same as culling with 1 image but with some more refined behavior on zooming for example.

**Comment by grothesque** [comment]
> then that's a bug. Can you open a new issue and document it so it's
> not lost ?  Thanks !

After restarting I do not see the issue anymore.  If I find a reliable
way to reproduce this problem I will open an issue for sure.

> btw, if you want to see images one by one, better use sticky
> preview. It's almost the same as culling with 1 image but with some
> more refined behavior on zooming for example.

Thanks, that’s even better than culling mode.

Actually, the problem that I brought up here could be solved in a better
way by caching results in RAM.  This could be extended to precompute the
next couple of images in the background (at idle priority).  In this
way, when switching to the next or previous image, there would be zero
waiting time.  This would improve UI responsiveness overall.

Has this already been considered?  (My quick search did not find
anything.)

I guess it’s a trade off between implementation complexity and UI
responsiveness.  Since such caching would speed up only switching
between images and not changes to parameters, it may not be worth the
additional complexity.

**Comment by Nilvus** [comment]
> Thanks, that’s even better than culling mode. Actually, the problem that I brought up here could be solved in a better way by caching results in RAM. This could be extended to precompute the next couple of images in the background (at idle priority). In this way, when switching to the next or previous image, there would be zero waiting time. This would improve UI responsiveness overall. Has this already been considered? (My quick search did not find anything.) I guess it’s a trade off between implementation complexity and UI responsiveness. Since such caching would speed up only switching between images and not changes to parameters, it may not be worth the additional complexity.

It's not only about RAM, but also to processor power (main processor or graphic one). Caching in RAM doesn't change the fact that the image need to be rendered (depending on editing made in darkroom). And this is made by the CPU or graphic card if OpenCL supported. So if the CPU or graphic card is not powerful, that will not be faster by only caching it in RAM.

**Comment by grothesque** [comment]
Well, it will be faster for *foreseeable* actions like switching to the next image, if there is enough idle time to precalculate (which should often be the case).  Such caching could be also useful for undo/redo, switching modules on and off repeatedly, playing with parameters.

**Comment by AlicVB** [comment]
it's  a little bit more complex...
To simplify, each image goes into a "pipe" where all modules processing are applied one by one. This produce the final result. There's 2 main sort of pipe : 
- the "export" pipe which produce at the end a image that can be saved. That's what is used for "export" (of course) but also for thumbnails (lighttable full preview is technically considered as a thumbnail)
- the "working" pipe, which is far more complex as it can compute only specific parts of the image, has clever caching system, ...

What you suggest, would mean to have 3 "working" pipe, synchronized to each other (for zoom & pan). I'm not sure if it's feasible, but for sure it would consume *lot* of memory and cpu/gpu. Considering we have already a specific mode dedicated for culling, I'm not sure it's worth the added complexity...

**Comment by grothesque** [comment]
I noticed that there must be some caching in the pixel pipeline, since changes to parameters compute faster as one progresses to modules towards the end of the pipeline.

Although the inner workings of darktable are complex, ultimately, for a given input, there is a given output that is visible on the screen. The input consists of the raw image, the edit (what is saved in the xmp file), as well as additional parameters like the zoom settings.  The output includes the center preview, the small preview in the top-left corner, and the histogram.  Instead of the actual preview pixmaps it may be preferable to store the raw ouput of the two pipes that you mention.  The memory it takes to store this output is on the order of a couple of MB per edit.

The idea I had is to establish a cache that stores the last N inputs together with their outputs.  It seems to me that this shouldn't be too complicated, since the internals of the pixel pipe do not play a role here.

Even on a low-end machine, this cache could easily contain dozens of entries.  This way, switching playing with a given parameter would become instantaneous once the previews have been computed at least once.

Still, perhaps it's not worth the effort, since if switching to uncached edits is too slow, no amount of caching will help.  And if switching to uncached edits is acceptably fast, there's not much point to bother with caching.
