### ISSUE TITLE
Mask manager redesign.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8391]
**Is your feature request related to a problem? Please describe.**
The mask manager is a good idea to get all the masks located in one place and have access to it at any time to link them with different modules. But in some cases it's not so intuitive to work with.

**Describe the solution you'd like**
I created a mockup just as an idea of how it has to be the mask manager. Of course this is a premature version and involve a lot of parameters to have in mind. It's a redesign of the mask manager, with active and inactive states, opacity changes, lock, show or hide masks, group and ungroup, and a lot more.

**Additional context**
![rect1122](https://user-images.githubusercontent.com/67672868/109928622-a37f5580-7c93-11eb-96c9-29bb2759e2f7.png)

**Comment by difrkaguilar** [comment]
An update version of the mask manager redesign is in the new feed
**UI Feature Request and other ideas.** #8453

**Comment by Nilvus** [comment]
> An update version of the mask manager redesign is in the new feed
> **UI Feature Request and other ideas.** #8453

So I close this one.
