### ISSUE TITLE
denoise (profiled) blend colour space

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#8396]
I’ve noticed that the default blend colour space of _denoise (profiled)_ module is _RGB (scene)_. However, the preset shipped with the module, _chroma only_, uses _RGB (display)_.

https://github.com/darktable-org/darktable/blob/master/src/iop/denoiseprofile.c#L651-L652

Should the module normally be used with _RGB display_? Or only in certain cases? Or is the preset wrong?

Issue opened after asking at https://discuss.pixls.us/t/darktable-denoise-profiled-blend-colour-space/23827

**Comment by rawfiner** [comment]
I agree. Preset should use scene as well
