### ISSUE TITLE
documentation: noise (profiled): confusing description of "adjust autoset parameters"

### ISSUE THREAD

**Issue by grothesque** [darktable-org/darktable#8399]
The relevant manual section says:

> In general, the value of this slider indicates the number of stops by which you had to increase the exposure. For example, if you had to push the exposure 2 stops above what you normally use, then set this slider to 2.

This confuses me to the point that I do not understand what this phrase is trying to say.

The default value of this setting is 1.  Taking the example of exposure pushed 2 stops above what one normally uses, I could understand if the slider had to be set to 4 (if its scale is linear), or to 3 (if it's log2).  

But 2?  That's consistent with square-root-of-linear, but if this parameter indeed works this way, the documentation should be more explicit.

**Comment by johnny-bit** [comment]
Please open up a documentation issue here: https://github.com/darktable-org/dtdocs/issues - it's the new location for usermanual problems.

**Comment by grothesque** [comment]
Thanks.  Done here: https://github.com/darktable-org/dtdocs/issues/235
