### ISSUE TITLE
Wrong numbers on collect module

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#8405]
Selecting one collect entry should show the corresponding number of images in lighttable.

This doesn't work for folder collection anymore. There are more than 50k images under the Photos hierarchy but 0 in Photos folder itself.

![image](https://user-images.githubusercontent.com/23012047/110175351-5eb50500-7de0-11eb-822f-ba62b5bb58ed.png)

* darktable version : 3.5.0+1322~g4daf571c6
* OS                : debian sid

**Comment by HansBull** [comment]
The query produced by `_dt_collection_compute_count` is `SELECT COUNT(DISTINCT mi.id) FROM (SELECT  id, group_id, film_id, filename, datetime_taken,   flags, version,  position, aspect_ratio,  maker, model, lens, aperture, exposure, focal_length,  iso, import_timestamp, change_timestamp,  export_timestamp, print_timestamp  FROM main.images AS mi  ) AS mi WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/user/Photos/path'))) AND (group_id = -1 OR id IN (SELECT id FROM (SELECT id, MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (1=1 AND (film_id IN (SELECT id FROM main.film_rolls WHERE folder LIKE '/home/user/Photos/path'))) GROUP BY group_id))) OR (id = -1) ORDER BY filename, group_id , mi.id-group_id != 0, version LIMIT ?1, ?2`

Adding a trailing `%` to the first occurence of '/home/user/Photos/path' would return the right number. But frankly, the whole query looks messy.

**Comment by phweyland** [comment]
> Adding a trailing `%` to the first occurence of '/home/user/Photos/path' would return the right number. 

It doesn't. 
- path% => 0 images
- path\*=> 54 images
- path|% = 54 images

**Comment by ralfbrown** [comment]
>     2. `OR (id = -1)` never happens

Don't forget the instances of `1=1 AND`.  I came across some of the code doing that in the past week; it's to avoid special-casing the first condition in the list.  That's understandable if there are lots of different paths in the code, but one could have simply chopped off the superfluous leading `AND` before returning the result that was built.  The `OR` may be a similar thing, though I came across "1=0" as the add-on of a false condition.  Also, there are places in the code where id=-1 gets passed to indicate the thumb being hovered over by the mouse.

> 
>     3. `ORDER BY...` is superflous for a count

At the risk of showing my limited understanding of SQL, what about the `LIMIT` for a count ?

**Comment by phweyland** [comment]
#7983 has introduced a new way to select the images on folders.
But the images counts have not been adapted to the new behavior.

**Comment by HansBull** [comment]
Wouldn't a simple `SELECT COUNT(DISTINCT mi.group_id) FROM main.images AS mi WHERE (flags & 256) != 256 AND film_id IN (SELECT id FROM film_rolls WHERE folder LIKE '/home/user/Photos%')` retrieve the correct number here? 
Or am I getting something wrong?

**Comment by phweyland** [comment]
6eb351e0ab488f39797afe7f94f0ef1c26a2bdcd and probably some others before have introduced another error.
To set properly the counts, the records insertion in the treeview must be reversal. 
The ordering choice has been applied before fulfilling the treeview, impacting the counts (when not a leaf) with one of the order. A proper implementation should have ordered the treeview afterwards (ordered model), or changed the feeding method.

**Comment by phweyland** [comment]
@HansBull , the collection.c queries are related to images gathering (not collect.c display). They are complex for sure and I don't know all their secrets, but I think that every piece has been thought carefully. 
Up to us not to break anything ...
