### ISSUE TITLE
[idea] workflow-dependent defaults for Quick Access panel

### ISSUE THREAD

**Issue by ralfbrown** [darktable-org/darktable#8423]
**Is your feature request related to a problem? Please describe.**
I realized that the White Balance temperature and tone sliders on the QA panel are irrelevant (and even harmful) when CAT defaults are set to modern.  Instead, the QA panel should have the Color Calibration temperature slider.  Similarly, when workflow auto-apply is set to scene-referred, it would be useful to have the Filmic white and black sliders on the panel, but they'd be irrelevant for display-referred.

**Describe the solution you'd like**
When switching auto-apply defaults, the contents of the quick-access panel should be adapted.  The complicating factor is that we don't want to mess up a user's carefully-set configuration.

Two possibilities:
1. (simpler) don't change the panel contents if the user has manually added/removed any of the widgets affected by the configuration change
2. (more work) ask the user whether to make the change, indicating what would be added/removed

**Comment by AlicVB** [comment]
Agree :) imho, we can just forget user defined presets and focus on default ones. Quick access is very new, and I'm even not sure it has landed in any stable version... (@TurboGit ?) so we can still break such little things :)

I'll have a look

**Comment by elstoc** [comment]
No it's not in a stable version yet - targeted for v3.6 in June

**Comment by AlicVB** [comment]
oh... I love that sort of work : everything is already in place :)
Well for the default presets.
For the user defined one, I'm really not sure it's a good idea : 
- workflow settings will most probably be changed once for all, and this sort of change will implies lot of other workflow adaptation anyway.
- we can't determine which widgets need to be changed or not (some power users may still need some temperature iop widgets even in "modern" mode...
- if we go that way, we should also check all auto-apply things...

maybe one solution can be to warn the user that changing this settings may imply to recheck all his presets/settings ?

**Comment by ralfbrown** [comment]
I can conceive of users who switch between different workflows for different jobs, but agree that most will switch only a few times initially before settling on a preferred workflow setting.

There are only a few specific widgets to switch around in the QAP, and all the rest can remain as-is.  Simply rewriting the entire list of widgets is of course easier to implement, but should come with the option for the user to decline the update.

**Comment by AlicVB** [comment]
> I can conceive of users who switch between different workflows for different jobs

yes, me too, but those users can be considered as advanced enough to know which widget to use or not, and anyway, they will certainly have different module groups presets !



> There are only a few specific widgets to switch around in the QAP, and all the rest can remain as-is. Simply rewriting the entire list of widgets is of course easier to implement, but should come with the option for the user to decline the update.

we already do that in thumbtable to reset thumbnail in case of pref change in how they should be generated. So it's doable. The main questions are : 
- which widget should be concerned exactly (all filmic/all basecurve. for temperature/channelmixerrgb we should be more precise)
- wouldn't power users be annoyed by the "question" each time (for those mentioned above)
- the changes won't be the same in the two ways : if you remove all filmic widgets when switching to display referred, you will not get them back if you switch back to scene referred...
- is it worth the pain ?

**Comment by elstoc** [comment]
Sounded like a good idea to start with but maybe it's becoming a bit too complex and we should just work within the existing module group presets (scene-referred/display-referred). Scene-referred should be easy but color calibration vs white balance less so, since we can't assume that scene referred == modern CA. Maybe removing temperature as a default widget is a better solution for that one, especially since we don't display the CAT warnings in the QAP.

**Comment by AlicVB** [comment]
@elstoc : not sure I understand exactly, but for all the "built-in" presets, the change is automatic and already in place : set modulegroup to "beginner" preset, then switch between "normal" and "modern", you'll see that the widgets in QAP follow your setting :)

**Comment by elstoc** [comment]
I never noticed that before - yes they do but only (for me) after a restart. Problem is that color calibration only offers a temperature slider if a daylight or black body illuminant is set and sometimes the QA panel shows a temperature slider that can't be altered or no slider at all.

Personally I prefer a basic set of widgets and for further adjustments to be up to the user, though I'd imagine most will change their workflow defaults once and be done with it.

**Comment by ralfbrown** [comment]
It sounds like the discussion is growing way beyond the scope I had in mind (just the QAP, not all of the module groups)....

**Comment by elstoc** [comment]
To be clear I'm just talking about the module groups _maintentance_ and _presets_, which are used to create presets for the QAP.

**Comment by AlicVB** [comment]
> Problem is that color calibration only offers a temperature slider if a daylight or black body illuminant is set and sometimes the QA panel shows a temperature slider that can't be altered or no slider at all.

do you mean that when opening a standard "new" raw file with mode "modern", there's cases where the temperature slider in channelmixerrgb is hidden/disable/... ? in that case, how the user can change the temperature ?



> It sounds like the discussion is growing way beyond the scope I had in mind (just the QAP, not all of the module groups)

I was just speaking about QAP, not the other parts... sorry if I wasn't clear enough. English writing is always hard for me ;)

**Comment by elstoc** [comment]
> do you mean that when opening a standard "new" raw file with mode "modern", there's cases where the temperature slider in channelmixerrgb is hidden/disable/... ? in that case, how the user can change the temperature ?

Yes. If the color calibration module detects an illuminant that is too far from black body, it offers hue/chroma sliders instead. I've seen this on new raws.

**Comment by AlicVB** [comment]
oh... and the question : what is the probability to face this situation ? if it's unusual, we can let things like that imho, otherwise I've absolutely no idea :( we can't remove the temperature slider from QAP without loosing it's first goal...

**Comment by elstoc** [comment]
> what is the probability to face this situation ?

No idea but with LED lighting i'd suspect it'll happen with a lot of indoor shots. @aurelienpierre?

**Comment by johnny-bit** [comment]
Let's revisit this for 3.8... And it seems like this should cover #9158

**Comment by ralfbrown** [comment]
Largely addressed by #9616.
