### ISSUE TITLE
lighttable collect images only shows 1 line entry in scroll window

### ISSUE THREAD

**Issue by llajtamasi** [darktable-org/darktable#8435]
**Introduction**
Selecting images in lighttable from the collect images panel.

**Describe the bug/issue**
In lighttable, the scroll window in in the collect images panel now only shows 1 entry at a time making it difficult to select the desired attribute while scrolling. This panel used to display several entries at a time.

**To Reproduce**
1. Go to lighttable
2. Click on any parameter (tag, title, film roll...)
3. Only one attribute line at a time is displayed.

**Expected behavior**
I expected to see several lines of attributes when the attribute tree is expanded or scrolled

**Screenshots**
![DTCollectImages](https://user-images.githubusercontent.com/73922395/110260276-964dc800-7fff-11eb-8347-dee4afc68de0.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.5.0+1374~g892f51765-dirty
* OS                : 5.8.0-44-generic SMP  x86_64 x86_64 x86_64 GNU/Linux
* Linux - Distro    : e.g. Ubuntu  20.10
* Memory            : 32G
* Graphics card     : nvidia GTX960
* Graphics driver   : nvidia 460.39
* OpenCL installed  :  yes
* OpenCL activated  :  yes

**Comment by ralfbrown** [comment]
The text box is resizable.  Hover your mouse on it and use Control-Scroll to resize.

**Comment by llajtamasi** [comment]
Thankyou ralfbrown. I looked everywhere for an explanation.
