### ISSUE TITLE
Grouped image is still displayed after changing collections

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#8436]
**Describe the bug/issue**
Playing with a play raw image and created multiple duplicates.  Click the collapse grouped images button at the top to collapse the group.  Clicked on the group button on the group leader image to to expand just that group.  Changed to a different collection by clicking in the recently used collections.  The group leader of the grouped images is displayed as the first image of the collection I changed to.  Got rid of the image by clicking the expand grouped images button at the top.

**To Reproduce**
1. Select an image and duplicate it to create a group.
2. Click the collapse grouped images button at the top of the lighttable
3. Click the group button on the group leader image to expand that group
4. Change to another collection
5. The group leader image is in the collection.  (Click the expand groups images button to make it go away)

**Expected behavior**
The group leader should not show up as part of the newly selected collection.

**Which commit intruduced the error**
Found this in git master.  Checked 3.4.0 and it also has the bug.   And, so does 3.2.1.

**Platform**
* darktable version :  3.5.0 regtests+ok~1299-g892f51765
* OS                : Linux - kernel 5.4.0
* Linux - Distro    : Ubuntu 18.4
* Memory            : 16GB
* Graphics card     : GeForce GTX 970M
* Graphics driver   : nvidia 460.39
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : 1.20.8
* Desktop           : Gnome
* GTK+              : 3.22.30
* gcc               : 7.5.0
* CMAKE_BUILD_TYPE  : build.sh default

**Additional context**

 - Can you reproduce with another darktable version(s)? **yes with version 3.4.0 and 3.2.1**

**Comment by AlicVB** [comment]
confirmed...
I'll have a look
