### ISSUE TITLE
Panasonic DC-G100

### ISSUE THREAD

**Issue by holzohr** [darktable-org/darktable#8440]
I uploaded 4 raw samples from my new camera (4:3, 3:2, 16:9, 1:1) to raw.pixls.us with CC0 license.
I would appreciate to see darktable supporting files from this camera.

**Comment by LebedevRI** [comment]
Thank you for contributing the samples!

**Comment by LebedevRI** [comment]
My apologies for completely dragging this out :(
I seem to have completely dropped the ball on camera support for the last few months.
