### ISSUE TITLE
Changing camera make & model in exif without breaking raw decoding

### ISSUE THREAD

**Issue by sams96** [darktable-org/darktable#8442]
I've just started working on a DSLR scanning setup for my film photos, and so far using darktable's tethering has been very convenient. But now I would like to change the exif data of my photos to match the data I've recorded for the film photos rather than the data for the photo I took of the film with my digital camera. I understand that some of the exif data needs to stay to properly decode the image, but when I change the `Make` and `Model` fields (I'm using exiftool for this) I get a camera not supported error from rawspeed, e.g.:

```
[rawspeed] (18302.arw) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 169: Camera 'Hasselblad' '501C', mode '' not supported, and not allowed to guess. Sorry.
```

I would like to be able to set these fields so I can catalogue my photos in darktable properly, but obviously it's quite important to be able to open them. I'm not really sure of any solutions here, would it be likely that allowing rawspeed to guess (perhaps with an option in the settings) would work well? Or perhaps we can put this information somewhere else?

I'd be happy to have a look into implementing a solution myself but like I said I'm not really sure where to start with solving it so any guidance would be appreciated.

Thanks

**Comment by phweyland** [comment]
> I can catalogue my photos in darktable properly

To be sure to understand properly. Does that mean you want to see make and models in image information ? In collection ? In exported images exif info (which could be less difficult as we already have mechanisms to override information at this stage) ? 

> I understand that some of the exif data needs to stay to properly decode the image

Unless a rawspeed expert says the opposite, I'm afraid that's true.
If so we have to work downstream... 
At first glance I can think about this:
- override the internal exif information. With possible conflict with "refresh exif", re-import, exif blob, ... this should be possible as we already do that with date/time and geotagging, at least with specific code.
- Without developing anything: the tag's category. You can see it in image information, and you can override the corresponding exif info at export time.
- An extension of tags (like locations). If some specific darktable tags (darktable|exif|make ?) are attached, dt would override internal value of the corresponding exif info... may not need any specific ui ... But I would not dream about generic code: everything is image cache is hand sewn (is that correct in English ?).

**Comment by wpferguson** [comment]
Perhaps create a set of user|exif|(maker|model|whatever|...) tags for the information you want to have.  Thanks to @phweyland you can tweak the image information display to show your tags in place of the darktable information.  You can sort and select on your tags with the collection module.

**Comment by parafin** [comment]
I don't think we want to support any workflow that involves modifying the original RAW file. So IMHO the described way to set Maker and Model should stay non-working in darktable, rawspeed shouldn't be modified for this.

**Comment by sams96** [comment]
I'd really like to have the exported images have the alternative exif data, and to be able to use collections with the alternative information.

**Comment by parafin** [comment]
See previous comments, that's already possible.

**Comment by phweyland** [comment]
One possible way.
If you don't have hundreds of camera you can quickly create a tag for each one like:
_camera_|_maker_|Nikon
and
_camera_|_model_|D700

Collecting the ones which are recognized by dt you can quickly tag them accordingly.
You do the same for those which are not recognized.

In image information you should have under "categories" something like:
maker: Nikon
model: D700

In collect module you use tag (like camera|maker|xxxx) to get your collections.

To export with jpg images, in presets/preferences, you add some formulas, selecting the exif tags you want to export and filling in them with a formula like $(CATEGORY0(camera|model)) or $(CATEGORY0(camera|maker))

Ping me if that doesn't work.

**Comment by sams96** [comment]
@phweyland thanks for the help, that's a great workaround for the issue. I'd still like a more integrated solution, particularly being able to use the standard camera filtering in the collections instead of duplicating this functionality in the tags and I'd be happy to look into implementing this myself if it's something that's wanted in darktable and I can get some suggestions on how we would want to achieve this.

**Comment by phweyland** [comment]
> if it's something that's wanted in darktable

I think that for some image information this can be useful but clearly not for those which are already managed by dt.

> I can get some suggestions

More a suggestion ...

In image information, double-click on filmroll opens the corresponding collection.
In the same way we can open a dialog when click-right/sub-menu or double-click on model or maker. 
This dialog would let the user change the model in the the image cache + write the cache into db.
As this is pure text and has no cascaded effect, this doesn't seem to be too complicated. 
Note: Attention must be paid to the PR which attempts to manage image information with multiple images selected.
Then we have to check if this information is usable (collection, export, ...) and not lost in an unexpected manner.
Of course a "refresh exif" would overwrite this but that sounds normal.

**Comment by wpferguson** [comment]
What modules depend on the exif data in order to process correctly?  I know that lens correction uses the lens and camera model data, but I'm not sure if any other modules do.

**Comment by phweyland** [comment]
>  I know that lens correction uses the lens and camera model data, but I'm not sure if any other modules do.

I didn't think about it but you are right. Model is used by dt. Not good for my last suggestion then...

![image](https://user-images.githubusercontent.com/23012047/111627709-1decc100-87ce-11eb-9281-e14bb30cd409.png)

**Comment by lhietal** [comment]
I think it is not usually a good idea to put information about film camera to standard Exif fields. These are probably assumed to describe the digital file. There are separate tags for time though. _DateTimeOriginal_ and _DateTimeDigitized_ [Exif Version 2.32, page 47](
https://web.archive.org/web/20190624045241if_/http://www.cipa.jp:80/std/documents/e/DC-008-Translation-2019-E.pdf ).

I tried to see if there was some existing schema to describe digitized photos but couldn't find anything. Perhaps XMP could have a custom namespace for this purpose.
