### ISSUE TITLE
spot removal → some of old edits lose it

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#8445]
Linux 64 bit, dt 3.4.1

1. Download raw file from https://discuss.pixls.us/t/play-raw-morning-light/11113
2. Download history from this edit https://discuss.pixls.us/t/play-raw-morning-light/11113/27 (you can try loading from both XMP and JPEG)
3. Notice how spot appears in the top part of the image. There is no spot in JPEG file, so it worked one day. Open original XMP file in text editor to check that spot information is there.

**Comment by TurboGit** [comment]
It is bug introduced long time ago that I have fixed last week. See #8373.

**Comment by TurboGit** [comment]
This was introduced in 2013 when the spot removal has been migrated to the common form support. All edits before this date, so done with dt < 1.2 were not properly upgraded.
