### ISSUE TITLE
Amaze demosaic → Star-like artifacts

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#8448]
Linux, 64 bit, dt 3.4.1

1. Raw file: https://discuss.pixls.us/t/noise-behavior-in-extreme-lowlight-raw-image/23930
2. XMP file: [IMG_6004.CR2.zip](https://github.com/darktable-org/darktable/files/6109843/IMG_6004.CR2.zip)

Result:

![amaze](https://user-images.githubusercontent.com/65483426/110501577-5d9b1500-810b-11eb-952c-dd95da45a396.png)

**Comment by jenshannoschwalm** [comment]
Known issue and fixed in master.

**Comment by timur-davletshin** [comment]
@jenshannoschwalm what was the issue number?

**Comment by jenshannoschwalm** [comment]
#2654 :-) An old one ...

**Comment by jenshannoschwalm** [comment]
@timur-davletshin please close as this is already fixed in master ...
