### ISSUE TITLE
[FR] UI Feature Request and other ideas.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8453]
Here I left some ideas related to the UI. I downloaded the bootstrap icon set from https://icons.getbootstrap.com/ used some of them and modified others to look like the darktable icons but really I don’t know if bootstrap icons can be used in darktable.

The first and second screenshots are an idea to remove the top bar with the logo on the left and the names (lighttable, darkroom, etc) on the right. I created an icon set for each (lighttable, darkroom, etc) that can be always visible or not if left panel is collapsed.
As the logo was removed, I think the most reasonable is to put it in a new tab named (about) in the global preferences.

![01](https://user-images.githubusercontent.com/67672868/111059799-a685fd00-846e-11eb-8c55-ac03794c76e3.png)

The same lighttable window with the panels collapsed.

![03](https://user-images.githubusercontent.com/67672868/111059819-bc93bd80-846e-11eb-8fef-85ffa2e2f774.png)

The Quick compare is to have in the darkroom an icon that based on display or scene-referred, compare the last step applied to an image with the previous one. An A and B comparison like using the snapshots module, but without have to create any snapshot. In that case, users don't have to create an snapshot every time to compare A and B, but can create snapshots in case they want to compare in depth different states.

![02](https://user-images.githubusercontent.com/67672868/111059823-c61d2580-846e-11eb-9927-cc2a6089fac2.png)

Taking advantage of the user experience, the export module with the progress bar, must be always at the same position in the lighttable and in the darkroom, not at the left in the lighttable, and at the right in the darkroom. With this idea, the export module must be on the right panel, at the bottom, and the same for the progress bar.

The same idea is for the star ratings and colors in both places, lighttable and darkroom, at the same position in darkroom too because is a visual indicator of the working image, users don’t have to go back to the lighttable to see the ratings or colors assigned to an image wile they are working in it.

![04](https://user-images.githubusercontent.com/67672868/111331763-9a08cc80-8647-11eb-9ee3-5573bc518abd.png)

![05](https://user-images.githubusercontent.com/67672868/111331794-a12fda80-8647-11eb-9e49-7ebcaf1e207a.png)

This is a representation of a module with a new set of icons based on bootstrap. 

![06](https://user-images.githubusercontent.com/67672868/111059878-1bf1cd80-846f-11eb-8044-52d20cf90113.png)

The mask manager is a good idea to get all the masks located in one place and have access to it at any time to link them with different modules. But in some cases it's not so intuitive to work with.

I created a mock-up just as an idea of how it has to be the mask manager. Of course this is a premature version and involve a lot of parameters to have in mind. It's a redesign of the mask manager, with active and inactive states, opacity changes, lock, show or hide masks, group and ungroup, and a lot more.

is a second attempt of the #8391  with some changes

![07](https://user-images.githubusercontent.com/67672868/111137091-c8f24600-8554-11eb-9c7c-63f18a2ec2fe.png)

Another proposal is the use of just one icon (circle or ellipse) to draw masks, with handlers around the shape.

![08](https://user-images.githubusercontent.com/67672868/111137113-cf80bd80-8554-11eb-80a3-3e3c35b5d489.png)

I used some bootstrap icons an change some of them to look more like darktable ones.

![08](https://user-images.githubusercontent.com/67672868/111059880-201deb00-846f-11eb-8c64-38c9eaa3c690.png)

All the screenshots are mock-ups, I left this for your appreciation and hoping for the best to this amazing software.

**Comment by s7habo** [comment]
Your suggestions for changes are very interesting! Would it be possible for you to show this presentation also in [https://discuss.pixls.us/](https://discuss.pixls.us/)?
Unlike Github, where mostly developers distribute, in this forum there are also many more users of darktable.

**Comment by difrkaguilar** [comment]
Thanks, i'll do it asap.

**Comment by dterrahe** [comment]
> export module with the progress bar, must be always at the same position in the lighttable and in the darkroom, not at the left in the lighttable, and at the right in the darkroom. With this idea, the export module must be on the right panel, at the bottom

I agree with your point about consistency, but the organisation of the darkroom is to have all the (many) processing modules on the right side, so having one exception for export would imho be confusing and take up valuable space. I'd rather move it to the left in lighttable.

The logic in lighttable then would be to have import/export and collections on the left and item selection and manipulation on the right. _Image information_ on the left is "just because more space" and _tagging_ would still be inconsistent between lighttable and darkroom, but it doesn't feel like it would lead to confusion to me.

**Comment by jandren** [comment]
Some lovely suggestions!

Really liked the handles of the masks, they are a bit cryptic in their current form and some extra visual help wouldn't hurt at all! Would it maybe be possible to show all possible handles at once in a good-looking and usable way. i.e. having handles for location, rotation, and scaling up all the time removing the need for knowing short cut for rotation?

The drawn + parametric mask looks kind of weird to me. Like the parametric mask is based on a spline. The triangle looks like an arrow that a spline is applied to a gradient in my eyes.

**Comment by Nilvus** [comment]
@difrkaguilar: thanks also for those mockups. I hope you don't mind if I close both your UI FR.

**Comment by difrkaguilar** [comment]
All good, I hope to be able to keep helping with some ideas as much as I can. Thank you very much for keeping me in mind.
