### ISSUE TITLE
crop and rotate module - add tooltip for shift and control keys

### ISSUE THREAD

**Issue by phil20099** [darktable-org/darktable#8456]
**Is your feature request related to a problem? Please describe.**

When using the tone equalizer module there are tips at the top of the screen as per the image below :

![image](https://user-images.githubusercontent.com/60315272/110615127-f9b83100-818a-11eb-8233-7884772d8776.png)

For the crop and rotate module is it possible to add tips for the shift and control keys as I can never remember which key to use as I don't use these often.

From the manual : _Constrain movement to the horizontal/vertical axis by holding Ctrl/Shift, respectively while dragging._

**Additional context**
I've check the current master build and it doesn't show any tool tips for crop and rotate.

**Comment by johnny-bit** [comment]
Fixed by #9611
