### ISSUE TITLE
Adobe DNG tone curve type aka Film-like

### ISSUE THREAD

**Issue by Eneen** [darktable-org/darktable#8466]
This curve type is part of Adobe DNG specs and is available in Lightroom and RawTherapee. It keeps constant hue while enhancing contrast that with standard RGB adjustment usually leads to shift yellows and blues. It also matches Lightroom look. It would be great addition for both tone and base curve modules as it is designed to work with one curve only.
From what I know it converts original and adjusted image into HSV and uses H from original and S V from adjusted.

Old RT manual says:
Film-Like. Basically, it uses Adobe’s method from their reference sample code. It is the same method that is used by the DCP’s tone curve

Some reading:
https://rawpedia.rawtherapee.com/Exposure#Film-Like

Source:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/curves.h
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/curves.cc

DNG sources:
https://github.com/aizvorski/dng_sdk/tree/master/source

Additional info:
RT has "clip out-of-gamut colors" switch that helps with hues on clipped highlights:
https://discuss.pixls.us/t/clip-out-of-gamut-colors-check-box/19866/11

**Comment by jandren** [comment]
This would be somewhere in the middle of preserve color == none and one of the constant RGB ratio options in the base curve and filmic.
None, changes luminance, saturation, and hue 
The other options are for constant RGB ratio which only changes luminance. Desaturation is also manually added in filmic but not in the base curve.
You should already be able to get similar results to what you ask for by using preserve color == luminance and then add/remove saturation as a function of luminance using color zones afterward. Not as easy, but maybe close enough for you now.

I have been thinking about a constant hue option when working on https://github.com/darktable-org/darktable/pull/7820
and I think it would be an interesting third option. That said, we can't reuse the code you link as those are assuming a finite input range for the HSV calculation and not the darktable infinite scene-referred approach.

**Comment by jandren** [comment]
Had another look at this and realized that it would actually fit without too much change. Added this as an option called "preserve hue" in the sigmoid branch mentioned above. Please try if you know how to compile!

**Comment by Eneen** [comment]
Hi! Thank you so much for looking into this. This code is also in blender under curves "filmlike" mode and works both in the compositor and the VSE.
I can't compile, any place I can get a build of this branch?
