### ISSUE TITLE
Module orientation it is expanded by default.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8472]
**Describe the bug/issue**
Every time I open an image to develop in the darkroom the module "orientation" is expanded by default.

**Expected behavior**
All modules are supposed to be collapsed by default.

**Screenshots**
![Screenshot_20210313_003257](https://user-images.githubusercontent.com/67672868/111020538-b204f580-8394-11eb-9118-9434edf3deb9.jpeg)

**Platform**
* darktable version : master branch darktable 3.5.0~git1394.57a72d1c2-1
* OS                : Linux - kernel 5.9
* Linux - Distro    :Ubuntu 20.10
* Memory            : 32GB
* Graphics card     : ASUS Nvidia GTX 1080Ti 11GB
* Graphics card     : GIGABYTE Nvidia GTX 1070 8GB
* Graphics driver   : 460.39
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : 
* Desktop           : Gnome
* GTK+              : 3.0
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.2.3
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by elstoc** [comment]
> All modules are supposed to be collapsed by default.

No. Whatever modules were expanded the last time you left the darkroom should be expanded when you reopen it, with the exception that if multiple instances of a module exist, only the base instance will be expanded.
