### ISSUE TITLE
Image information shows datetimes in US format

### ISSUE THREAD

**Issue by colin-adams** [darktable-org/darktable#8474]
**Describe the bug/issue**

In the image information panel in darkroon, all the datetime fields are displayed in mm/dd/yyyy ... format. The RAW files contain information in an ISO like format (year/month/day ....).
My locale settings are all GB.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to darkroom
2. Look at any datetime field
3. Note that it is displayed in US format

**Expected behavior**
Fields are displayed either according to the locale, or in the original format of the raw file

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.4.1
* OS                : e.g. Linux - kernel 5.10.21
* Linux - Distro    : e.g. Fedora
* Memory            : 32GB

**Comment by parafin** [comment]
Please show output of `locale` command and also try explicitly setting LC_TIME=en_GB.utf8.

**Comment by colin-adams** [comment]
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by elstoc** [comment]
Please see comment [here](https://discuss.pixls.us/t/format-of-datetime-in-image-information/23863/11). This is a text field and it output "as is" from the image metadata.

**Comment by colin-adams** [comment]
Setting LC_TIME=en_GB.utf8 explicitly displays in European format.
So is this a problem with the Fedora settings?

**Comment by colin-adams** [comment]
@elstoc I had already seen that comment. I don't understand what part is relevant.

**Comment by elstoc** [comment]
Yeah sorry deleted it after I looked at the actual darktable output. Sorry for the noise.

**Comment by colin-adams** [comment]
Explicitly coding LC_CTYPE="en_GB.UTF-8" (as in the locale output) also works.

So it would appear to me that the locale information is not being automatically added to the environment when darktable is invoked from the desktop.

**Comment by parafin** [comment]
You can check the environment of the process (darktable) using /proc FS.

**Comment by colin-adams** [comment]
Thanks.

So I tried:

cat /proc/29430/environ | grep LC_TIME

and got no output.

**Comment by colin-adams** [comment]
whereas if I do the same thing after explicitly adding LC_TIME... to the command line, it IS present - output is:

Binary file (standard input) matches

**Comment by colin-adams** [comment]
LANG IS present is in running environment. So Fedora must be setting that somewhere, but not LC_TIME. If I can find out where, I can edit that setting, I guess. Is that how it is supposed to work?

**Comment by parafin** [comment]
LANG should be enough actually, not sure why it isn't.

**Comment by colin-adams** [comment]
So I changed /etc/locale.conf to read:

LANG="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"

(previously only the first line was present). And re-booted.
This solves the problem for me.

Shall I close the ticket, or do you, @parafin, want to pursue this further?

**Comment by parafin** [comment]
I do not.
