### ISSUE TITLE
[Feature] New variables

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#8476]
Hello,

for my lighttable's overlay & tooltips, as well as my darktable's infoline, I'm make heavy use of variables.
I'd love to have the following variables available for :

- filesize (in MB)
- file width (given the current cropping if any, I guess)
- file height (given the current cropping if any, I guess)

I've checked in https://darktable.gitlab.io/doc/en/darktable_variables.html, they do not currently exist.

Is this something that would be feasible ?
Thanks
GLLM

**Comment by dterrahe** [comment]
To clarify, do you want these with regards to the input image (RAW) or the output image (which "given the current cropping if any, I guess" suggests). If the latter, this would depend on the active export settings, not just the pipe. And then the filesize would not be known until the export is performed. So I think that would be hard. To implement but also to interpret/understand.

**Comment by GLLM** [comment]
hey @dterrahe 
thanks for your reply :)

* in retrospective, the original/RAW file width & length would be fine :) I can amend my first post in this regard.
* filesize --> okay, understood, but isnt the current file size already known ? (be it RAW or JPEG) I'm looking for the original file size, not after the pipeline.

Is this clarifying things ? or at least my request, feasability apart ;)

GLLM
