### ISSUE TITLE
Add XMP data to AVIF exports

### ISSUE THREAD

**Issue by kmilos** [darktable-org/darktable#8480]
**Describe the solution you'd like**

The AVIF format supports XMP storage, and [dt claims support for it on export](https://github.com/darktable-org/darktable/blob/ce6386d56be4e1d7efd60e24ba9e28641492ba02/src/imageio/format/avif.c#L696), but [attatching XMP via exiv2 like it's done for other formats](https://github.com/darktable-org/darktable/blob/ce6386d56be4e1d7efd60e24ba9e28641492ba02/src/common/imageio.c#L1046) is currently not supported and silently fails.

OTOH, libavif can write XMP at the time of export using `avifImageSetMetadataXMP()` (we similarly use `avifImageSetMetadataExif()` already to write Exif directly instead of the exiv2 way), so there is not real reason dt could not support XMP export as well. 

What is the best way to manage this @cryptomilk ? Add XMP data to `write_image()` just like existing Exif and update the interface for all formats?

Edit: Now I see it might not be so simple as `dt_exif_xmp_attach_export()` does a bunch of other stuff... 

**Alternatives**

Contribute to AVIF write support in exiv2 before the 0.27.4 freeze in April, as read only support seems to be implemented so far ;)

**Comment by cryptomilk** [comment]
> What is the best way to manage this @cryptomilk ? Add XMP data to write_image() just like existing Exif and update the interface for all formats?

Yep ... patches welcome :-)
