### ISSUE TITLE
Samsung GX10/GX20 support (Pentax K10D/K20D clones)

### ISSUE THREAD

**Issue by jiemdev** [darktable-org/darktable#8483]
Hello,

I have old photos taken with a Samsung GX20, and there is no WB nor noise profile for this camera in darktable.
Unfortunately, I do not own more this camera to do the needed pictures.
However, Pentax's K10D and K20D profiles exists, and Samsung's GX10 and GX20 are clones of these Pentax cameras.
I tried to copy-paste the noise profile of Pentax K20D to a Samsung GX20 profile, and it seems working not badly.

Do you think it is acceptable to copy all the data concerning Pentax's K10D and K20D to Samsung's GX10 and GX20, allowing better support of these cameras? (that is, WB presets, noise profile and custom matrix)

Some info:
- Samsung's raws are DNG format.
- These bodies are issued from a Pentax/Samsung partnership, if I am not wrong the sensor is from Samsung and body design from Pentax.

Regards

**Comment by johnny-bit** [comment]
I think you can do that for Samsung GX20. Here's the proof:

https://github.com/darktable-org/darktable/blob/df1271bfb2063ee5f543f87495070660f8307608/src/external/adobe_coeff.c#L625

Please do a PR for those features, link to this as proof that it's identical and it'll be fine IMO.

**Comment by jiemdev** [comment]
Hello,

I just did the pull request.
I did for both GX10 and GX20.

To explain for the GX10:
- When I checked existing WB data for K10D and GX10 in wb_presets.c, they are identical.
- Checking DNG files from raw.pixls.us, Exif.Image.ColorMatrix2 are identical (Could you explain me how to pass from these values to the values in adobe_coeff.c?)

However, I saw someting unexpected when checking K2D vs G20 from DNG's of raw.pixls.us: in this case Exif.Image.ColorMatrix2 are different! Maybe it is a variable information?

Best

**Comment by jiemdev** [comment]
#8521 is the pull request

**Comment by johnny-bit** [comment]
values in `adobe_coeff.c` are extracted from Adobe DNG converter.
