### ISSUE TITLE
FR: polygon locations on map

### ISSUE THREAD

**Issue by quovadit** [darktable-org/darktable#8484]
**Is your feature request related to a problem? Please describe.**
Since 3.4 it's possible to create "dynamic tags" by drawing locations in the map module, which is fantastic! 
But unfortunately it's only possible to draw circle or rectangle shapes.
Therefor I am not able to draw Austria for example, so I still have to manually attach "normal" tags (place|AT)

![image](https://user-images.githubusercontent.com/5677563/111370856-02cc6500-8699-11eb-9ab6-cc8fa9a1f17e.png)

**Describe the solution you'd like**
I would love to draw locations as polygons.

**Additional context**
Has already been discussed in [pixls](https://discuss.pixls.us/t/new-features-on-map-view/23664/13)

**Comment by phweyland** [comment]
In that request I see two (at least) parts:
- generate the polygon. At first it could be done outside dt. In that case dt would have only to read the data. Otherwise the ui part of the polygon definition should be included...
- store the new location and detects included images.

**Comment by phweyland** [comment]
solved by #8568
