### ISSUE TITLE
regression: darktable "collapse grouped images" remembered but not applied on start-up, 3.5.0+1441~g2ec5c0cb4 since b78e61a0 (bisected)

### ISSUE THREAD

**Issue by mandree** [darktable-org/darktable#8487]
**Describe the bug/issue**
when darktable starts up for me in the lighttable view, the "collapse grouped images" button is highlighted as expected, but the groups are expended. 3.5.0+1441~g2ec5c0cb4

**To Reproduce**
* import a few images and group them, for instance, raw+jpeg companion pairs
* click the "collapse grouped images" and exit darktable
* restart darktable

**Expected behavior**
the groups should be collapsed (no JPEG should be in screenshot below), in line with the highlighted collapse-grouped button (four dots in a circle)

**Screenshots**
taken right after launching darktable
![grafik](https://user-images.githubusercontent.com/5079167/111443261-7d34cd80-8709-11eb-91b5-25e66ec2b4dc.png)

**Screencast**
none

**Which commit intruduced the error**
b78e61a0d0bd7fa7b7bd8b6d6251c96320c8cdcc is the first bad commit
commit b78e61a0d0bd7fa7b7bd8b6d6251c96320c8cdcc
Author: @AlicVB <dev@lnaa.fr>
Date:   Wed Mar 3 20:34:02 2021 +0100

    collect : speedup gui_init
    
    by only reloading collection is case of a "by module" rule

 src/libs/collect.c | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

**Platform**
* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : 
* Linux - Distro    : Fedora Linux 33 
* Memory            : 
* Graphics card     : nvidia 1060
* Graphics driver   : NVIDIA UNIX x86_64 Kernel Module  460.56  Tue Feb 23 23:31:36 UTC 2021
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
-

**Comment by AlicVB** [comment]
So this is my fault... I'll have a look !

**Comment by mandree** [comment]
This isn't about fault but since what change the error is happening and it stands to reason to assume that you might know what the change is about and you just need more test cases to get it completed.
