### ISSUE TITLE
Fuji RAF image (X-T10) causes darktable tiling issues and locks up with busy CPU, cannot export or exit (3.4.1 + Git master)

### ISSUE THREAD

**Issue by mandree** [darktable-org/darktable#8491]
**Describe the bug/issue**
I can provide a .RAF image and .RAF.xmp file that royally screws up darktable.

**To Reproduce**
1. Download specific image https://people.freebsd.org/~mandree/DSCF3401.RAF and https://people.freebsd.org/~mandree/DSCF3401.RAF.xmp - note I have removed camera serial data and some XMP tags
2. run darktable DSCF3401.RAF
3. you now see that there is a history stack with crop&rotate on top, and perspective correction below.
4. I see "tiling failed for module demosaic, output may be garbled". Occasionally, I see garbled output, more often, I see a black screen with overlay "working..."
5. running darktable -d all with redirection emits several issues with tiling.
6. note that if you pick pos. 11 in history stack (perspective correction) you'll receive a proper preview so it does not appear to be all broken
7. try exporting the image, it will never complete

**Expected behavior**
proper cropping of keystone/perspecive corrected image

**Screenshots**
on demand

**Screencast**
none

**Which commit intruduced the error**
unknown when this was introduced or what would be last good version. 3.4.1 behaves as above, 3.5.0+1441~g2ec5c0cb4
 does not open its application window at all.

**Platform**
* darktable version : 3.4.1 and 3.5.0+1441~g2ec5c0cb4
* OS                : Linux
* Linux - Distro    : Fedora Linux 32 and 33
* Memory            : 
* Graphics card     : nvidia
* Graphics driver   : nvidia UNIX binary drivers (various)
* OpenCL installed  : yes
* OpenCL activated  : yes, but darktable --disable-opencl behaves the same

**Comment by mandree** [comment]
[dt.log](https://github.com/darktable-org/darktable/files/6155965/dt.log)
output of `darktable -d all >& dt.all`

**Comment by jenshannoschwalm** [comment]
I can confirm this at least partly. Still don't understand if this is really a tiling issue or something else. You didn't report your CPU & GPU memory available. Could you enlighten me? :-)

**Comment by mandree** [comment]
@jenshannoschwalm  It's a Ryzen 5 3600 with 16 GB of RAM for the CPU and this is the darktable-cltest output WRT VGA, so 6 GB on the nvidia card:

```
0.242187 [opencl_init] found 1 device
0.242403 [opencl_init] device 0 `GeForce GTX 1660 SUPER' has sm_20 support.
0.242547 [opencl_init] device 0 `GeForce GTX 1660 SUPER' supports image sizes of 32768 x 32768
0.242548 [opencl_init] device 0 `GeForce GTX 1660 SUPER' allows GPU memory allocations of up to 1483MB
[opencl_init] device 0: GeForce GTX 1660 SUPER 
     GLOBAL_MEM_SIZE:          5935MB
     MAX_WORK_GROUP_SIZE:      1024
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 1024 1024 64 ]
     DRIVER_VERSION:           460.67
     DEVICE_VERSION:           OpenCL 1.2 CUDA
0.310423 [opencl_init] options for OpenCL compiler: -w  -DNVIDIA_SM_20=1 -DNVIDIA=1 -I"/usr/share/darktable/kernels"
```

**Comment by daniel-j-h** [comment]
I just ran into a similar issue in https://github.com/darktable-org/darktable/issues/8735 with a Fuji X-T20, and in there provide additional files to reproduce. Hope it helps :bow:

**Comment by mandree** [comment]
Issue persists in this is darktable 3.5.0+2425~gf3fc325d3

**Comment by AlicVB** [comment]
hmm... what is the idea here ? if it's "just" to add some safety checks to be sure to not commit/process 0x0 crops, that should be easy (and I'll try to do it)

But the main question is : do we know where it comes from ? Although I can see the problem with the xmp attached (directly crash dt for me), I can't manage to reproduce the issue by myself...

PR #9133 avoid dt to crash and make the cropping recoverable (eventually needs to fold/unfold crop & rotate module) but doesn't fix the root cause : how is it possible that we end with 0 crop size ?

**Comment by jenshannoschwalm** [comment]
i have no idea what the root cause could be. It might be no be reproducable at all as many things have changed in crop&rotate. I thought of a crop module with crops set to a region of the image non-overlappimg with the region calculated by one of the distorting modules. Does that make sense?

**Comment by mandree** [comment]
Generally, going along my "how to reproduce", darktable does not open at all when given the filename. AlicVB's patches make no difference.

With @AlicVB 's two commits from PR #9133 cherry-picked, and when opening the lighttable/file browser (`darktable .`), the crop & rotate module complains about invalid crop and continues.

It's a step forward, but appears to not yet be a complete solution for the images given here.

**Comment by jenshannoschwalm** [comment]
I don't understand this fully.
> darktable does not open at all when given the filename

does that mean you start dt from a shell with filename as parameter?

> the crop & rotate module complains about invalid crop and continues

So darktable gives a warning in the module header but behaves well? That would be exactly what can be done here atm.

**Comment by mandree** [comment]
> I don't understand this fully.
> 
> > darktable does not open at all when given the filename
> 
> does that mean you start dt from a shell with filename as parameter?

correct, `darktable DSCF3401.RAF` gives me a task bar entry but never opens its application window. Adding `-d all`, logging stops after logging a lot, printing [init] startup took 3,... and after enumerating paper formats and printer and camera_control "0 cameras connected".   I've saved the log.

If I pass in some Sony `_DSC1234.ARW`, darktable opens in the darkroom as expected.

> > the crop & rotate module complains about invalid crop and continues
> 
> So darktable gives a warning in the module header but behaves well? That would be exactly what can be done here atm.

Correct, and it uses a small crop in the upper left-hand corner of the image.

**Comment by jenshannoschwalm** [comment]
You have somehow generated a disfunctional state of the developed image, we don't know why as you probably have read. Can you remember what you did exactly in darkroom? Some styles applied? Anything "unusual"? Or even better, can you reproduce with a fresh edit to generate such a weird thing? THAT would really help a lot!

**Comment by mandree** [comment]
wasn't originally my doing, I will inquire from the friend

**Comment by AlicVB** [comment]
@mandree : to be sure to understand well : when you open dt with the problematic file as parameter, dt doesn't open. But if you open dt without parameters and then open the problematic image inside darkroom, it open correctly, show the warning and the small crop. Right ?

The second thing (warning + small crop is the intended behavior. But I have that in both cases here...

Can you try to rename your library.db, and open dt with the file as parameter, to see if there is still a problem or not ? Thanks !

**Comment by mandree** [comment]
> @mandree : to be sure to understand well : when you open dt with the problematic file as parameter, dt doesn't open. But if you open dt without parameters and then open the problematic image inside darkroom, it open correctly, show the warning and the small crop. Right ?

Correct.   

`darktable DSCF3401.RAF` hangs between completed initialization and opening the darkroom view.

`darktable .` starts and if I double-click the image from the overview, I can edit it in the darkroom view.

> The second thing (warning + small crop is the intended behavior. But I have that in both cases here...
> 
> Can you try to rename your library.db, and open dt with the file as parameter, to see if there is still a problem or not ? Thanks !

Done, same story. I've got a backtrace of all threads, attached below - not sure if it hangs generating a thumbnail with the strange crop (because the unpatched darktable master branch will also not generate the thumbnail in the bottom film strip, and overlay the text "working..." but never complete).

`cd /tmp/dd && rm -vrf data.db* lib.db* ~/.cache/darktable/ ; cp -vf ../orig/DSCF* . ; sleep 2 ; /opt/darktable/bin/darktable --library /tmp/dd/lib.db   --configdir /tmp/dd -d all DSCF3401.RAF >& dt.log`

and then I've grepped the print information out of the log with `grep -v '\[print\]'`

* [backtrace of all threads - gdb.threads.txt](https://github.com/darktable-org/darktable/files/6590223/gdb.threads.txt)
* [darktable -d all log except printing - dt.filtered.log](https://github.com/darktable-org/darktable/files/6590247/dt.filtered.log)

**Comment by jenshannoschwalm** [comment]
1. Do we need some history update after correcting the parameters?
2. There could be a problem with invalid thumbs. If dt crashes while generating a thumb that could leave it with a length of zero.

**Comment by AlicVB** [comment]
>     1. Do we need some history update after correcting the parameters?

Well, in fact, parameters are never touched directly,we just sanitized datas being passed to process_* fct or gui fct. So if parameters are changed that's mainly because because of the gui fct themself, which already take care of history.
So for me, that's not needed.



>     2\. There could be a problem with invalid thumbs. If dt crashes while generating a thumb that could leave it with a length of zero.

yes. I doubt that it's the case in @mandree  issue, but... @mandree : can you rename dt thumb cache, to be sure it doesn't comes from some bad thumbnail ? thanks !

**Comment by mandree** [comment]
@AlicVB I think I deleted the thumbs - see the `rm -vrf ~/.cache/darktable/` part in my command line from comment above https://github.com/darktable-org/darktable/issues/8491#issuecomment-853707455? Is not that sufficient to purge the thumbnail cache?

**Comment by mandree** [comment]
So, received feedback from the friend, she says that if memory serves (this is months old) she was grabbing the upper left corner, then lower right and finally moved the entire frame. She says she hasn't attempted a 0-sized crop.

**Comment by AlicVB** [comment]
@mandree : thanks for the tests (and sorry to have missed the commandline)

What surprise me is that I can't reproduce the dt crash you have when opening dt with the file as parameter... Here everything works well (with my PR)
Can you test (again) some things ?
- try to rename darktablerc file too (I don't think you handle that in your command)
- remove the -d all and see if you have some messages on the console (about cropping)

What surprise me a lot in your log is that you doesn't seems to load any image... So I wonder if the problem doesn't come from somewhere else...

**Comment by mandree** [comment]
Changed the command line to nuke darktablerc, too (and confirmed with strace that it's really trying to open `/tmp/dd/darktablerc`):

```
cd /tmp/dd && rm -vrf data.db* lib.db* darktablerc ~/.cache/darktable/ ; cp -vf ../orig/DSCF* . ; sleep 2 ;  /opt/darktable/bin/darktable --library /tmp/dd/lib.db   --configdir /tmp/dd  DSCF3401.RAF >& dt.log
```
yields:
```
[defaults] found a 64-bit system with 32884388 kb ram and 16 cores (0 atom based)
[defaults] setting very high quality defaults

```


```
cd /tmp/dd && rm -vrf data.db* lib.db* darktablerc ~/.cache/darktable/ ; cp -vf ../orig/DSCF* . ; sleep 2 ;  /opt/darktable/bin/darktable --library /tmp/dd/lib.db   --configdir /tmp/dd  . >& dt-dir.log
```
yields:
```
[defaults] found a 64-bit system with 32884388 kb ram and 16 cores (0 atom based)
[defaults] setting very high quality defaults
[Zuschneiden und Drehen] incorrect crop
[Zuschneiden und Drehen] incorrect crop

```

**Comment by mandree** [comment]
So, I figured the hang has something to do with LUA. Disabling everything Lua, and rebuilding darktable, resolves the hang when launching darktable as `darktable DSCF3401.RAF`. So...

**Comment by mandree** [comment]
Running `darktable -d lua DSCF3401.RAF` yields 
```
[defaults] found a 64-bit system with 32884388 kb ram and 16 cores (0 atom based)
[defaults] setting very high quality defaults
1,439066 LUA WARNING locking from the gui thread should be avoided
```

and running `darktable -d lua .` yields 
```
[defaults] found a 64-bit system with 32884388 kb ram and 16 cores (0 atom based)
[defaults] setting very high quality defaults
1,496476 LUA ERROR : cannot open /tmp/dd/luarc: Datei oder Verzeichnis nicht gefunden
```
where the latter translates to No such file or directory

**Comment by AlicVB** [comment]
GREAT !
Well, no so great to have something that hang ;) But at least it's not the same problem... because I was completely out of clue why you have that and not me...

@wpferguson : can I ping you here ?

**Comment by mandree** [comment]
Forcing _DEBUG through CFLAGS, and running `darktable -d lua DSCF3401.RAF` yields the following output then hangs.

```
1,255845 LUA DEBUG : dt_lua_async_call_internal called from dt_lua_init 185, nargs : 1
1,255885 LUA DEBUG : thread 0x1cb02c0 released from dt_lua_init:187
1,255934 LUA DEBUG : thread 0x5064de0 waiting from stacked_job_dispatch:212
1,255965 LUA DEBUG : thread 0x5064de0 taken from stacked_job_dispatch:212
1,256110 LUA DEBUG : thread 0x5064de0 waiting from run_async_thread:157
1,256890 LUA DEBUG : gtk_wrap called from register_pref 804
1,256909 LUA DEBUG : thread 0x5064e40 released from gtk_wrap:663
1,256938 LUA DEBUG : thread 0x5064de0 taken from run_async_thread:157
1,256949 LUA DEBUG : thread 0x5064de0 released from stacked_job_dispatch:216
1,304797 LUA DEBUG : dt_lua_async_call_alien_internal called from on_view_changed 58
1,304871 LUA DEBUG : thread 0x5064de0 waiting from alien_job_dispatch:310
1,304904 LUA DEBUG : thread 0x5064de0 taken from alien_job_dispatch:310
1,304969 LUA DEBUG : thread 0x5064de0 waiting from run_async_thread:157
1,305003 LUA DEBUG : thread 0x4091520 released from run_async_thread_main:146
1,305034 LUA DEBUG : thread 0x5064de0 taken from run_async_thread:157
1,305043 LUA DEBUG : thread 0x5064de0 released from alien_job_dispatch:350
1,320268 LUA DEBUG : dt_lua_async_call_alien_internal called from _image_selection_changed_callback 81
1,320345 LUA DEBUG : thread 0x5064de0 waiting from alien_job_dispatch:310
1,320375 LUA DEBUG : thread 0x5064de0 taken from alien_job_dispatch:310
1,320402 LUA DEBUG : thread 0x5064de0 waiting from run_async_thread:157
1,320461 LUA DEBUG : thread 0x4091520 released from run_async_thread_main:146
1,320498 1,320499 LUA DEBUG : thread 0x5064de0 taken from run_async_thread:157
1,320511 LUA DEBUG : thread 0x5064de0 released from alien_job_dispatch:350
LUA DEBUG : dt_lua_async_call_alien_internal called from _metadata_view_update_values 1009
1,320545 LUA DEBUG : thread 0x5064de0 waiting from alien_job_dispatch:310
1,320554 LUA DEBUG : thread 0x5064de0 taken from alien_job_dispatch:310
1,320568 LUA DEBUG : thread 0x5064de0 waiting from run_async_thread:157
1,320604 LUA DEBUG : gtk_wrap called from lua_update_metadata 1502
1,320613 LUA DEBUG : thread 0x4091520 released from gtk_wrap:663
1,320624 LUA DEBUG : thread 0x4091520 waiting from dt_lua_gtk_wrap_callback:640
1,320633 LUA DEBUG : thread 0x5064de0 taken from run_async_thread:157
1,320641 LUA DEBUG : thread 0x5064de0 released from alien_job_dispatch:350
1,320660 LUA DEBUG : thread 0x4091520 taken from dt_lua_gtk_wrap_callback:640
1,330292 LUA WARNING locking from the gui thread should be avoided
1,330301 LUA DEBUG : thread 0x1cb02c0 waiting from _image_import_internal:1636
```

**Comment by wpferguson** [comment]
@AlicVB I will look at this.  It might be an issue with invoking a lua script.  I'm guessing that one of the fujifilm scripts is running (or trying to) on the imported image.

**Comment by wpferguson** [comment]
@mandree are you running any lua scripts on import or against fuji images?

**Comment by wpferguson** [comment]
@mandree a better question is what lua scripts do you have running and what lua scripts are configured to start automatically?  When you start darktable with darktable <image> it opens in darkroom mode.  If you try and load a script that creates a module, it hangs.  All the scripts in the lua scripts repository check to make sure darktable is in lighttable before trying to install a module.

@AlicVB I think this is a lua issue.  I'll ping you if I find out otherwise.

@TurboGit can we add a section to the bug report template like:
* Do you use lua scripts?
* What lua scripts start automatically?
* What lua scripts were running when the bug occurred?

**Comment by TurboGit** [comment]
@wpferguson : what about #9150, ok with you ?

**Comment by wpferguson** [comment]
@AlicVB, @mandree It is something about this image.  I put it in a directory, without the xmp file, then opened darktable without any arguments.  When I try and import the folder, the thumbnail square appears with a working... and it just sits.

I tried with and without lua and it made no difference.

The image opens with shotwell and raw RawTherapee, so it appears that the image is not corrupt.

As a test I opened a play raw image shot on a fuji xt-10 from this post, https://discuss.pixls.us/t/how-to-fix-problem-when-using-color-zones-module-in-dt-3-4-1/23934.  If I try and open it from the command line it hangs.  But, I was able to import it along with a bunch of other play raw files.

If I take that image and put it in a directory with other images (i.e. the same play raw folder) it imports just fine.  Maybe some kind of initialization problem?  When other images are imported they initialize something that XT-10 files need?

It's not just that image.  I tried other RAF files and they all hang when being opened from the command line, even after being imported.

**Comment by wpferguson** [comment]
bisect gives d1a91ba39ff912186c0a09a16876879337742f3d

Resets metadata_view to "-"
    
    When no image is selected, when the cursor goes out of the image, the
    metadata view (image information) keeps the last image information.
    This change is about to reset information to "-" when mouse goes out of
    an image (with no selection) and when an selection is canceled.
    It works quite the same way than the buttons in the "selected image[s]"
    module are activated.

Maybe he forgot to see if there was a last image (in this case there isn't because each run starts with a fresh database and no xmp files).

**Comment by jenshannoschwalm** [comment]
I can't reproduce here, neither with or without opencl, have no lua scripts running.

**Comment by wpferguson** [comment]
I commented out the change, recompiled and tested and I can load the image from the command line.  @phweyland has made changes to that code since then, so a simple commenting out probably won't work :smile: 

@phweyland the problem is in metadata_view_update_values.  Maybe it is simply a timing issue caused by darktable opening straight to darkroom mode.

**Comment by mandree** [comment]
On my computer, there is no Lua script running in darktable that I know of beyond possibly luarc during initialization - I have the lua script installer in the bottom left corner of my lighttable.

I'd like to ask again about the `1,330292 LUA WARNING locking from the gui thread should be avoided` from my earlier comments https://github.com/darktable-org/darktable/issues/8491#issuecomment-854172261 and https://github.com/darktable-org/darktable/issues/8491#issuecomment-854187352  - is this somehow related?

**Comment by wpferguson** [comment]
@mandree it's not a lua script problem.  And it's not just an RAF problem.  Any time I try and open any image straight into darkroom mode it hangs.  

> I'd like to ask again about the 1,330292 LUA WARNING locking from the gui thread should be avoided

It's a warning, but in this case it's the only way to do it.  The issue is that Lua is single threaded and darktable is multi-threaded so when you lock from the gui, darktable becomes single threaded while the lock is held.

**Comment by mandree** [comment]
I can open Sony .ARW files from some cameras straight into darkroom mode without ill effect, files from other cameras cause lockups.

**Comment by wpferguson** [comment]
I have a directory of play raws I use for testing.  I just started trying to open random file types to see if it was just RAFs.  I crashed on the first CR2 I opened.

**Comment by wpferguson** [comment]
Found it.... 

Using the fprintf debugger I get

```
in _metadata_view_update_values
took the -1 branch
took the not darkroom branch, querying the database
finished database query and mouse_over_id = 0
count is 0,  going to fill_minuses
did the fill, now calling lua to update metadata
```
@phweyland I think if there isn't an image (i.e. count == 0) then we shouldn't call lua_update_metadata.  

I also have a question.  If we start darktable with an image as the argument, then it opens in darkroom mode.  So, why didn't the code take the darkroom branch?

**Comment by wpferguson** [comment]
@phweyland it's in lua_update_metadata.  It should handle a bad image id, so it's something with the logic.  I'll take it.

**Comment by phweyland** [comment]
Sorry, I'm a bit late on this.... 
>  I'll take it.

Thanks

**Comment by mandree** [comment]
Indeed, it seems 5f5e93b221c645df93f50b74dfccd08df6520cc0 has solved all these issues for me. Two items remain, the first was discussed and can't be solved easily, so accepted. Is the second one OK or reason for concern?

```
2,653209 LUA WARNING locking from the gui thread should be avoided
4,672417 LUA ERROR : duplicate index name _scripts_install for event type view-changed
```

**Comment by wpferguson** [comment]
@mandree 

> 4,672417 LUA ERROR : duplicate index name _scripts_install for event type view-changed

When you copied the system luarc file to your own luarc file this forced darktable to run it twice.  Delete your luarc file in your config directory.  If you want to use the lua scripts, then create a luarc file with the line

`require "tools/script_manager"`
