### ISSUE TITLE
git master cannot import xmp from 3.4.1

### ISSUE THREAD

**Issue by BigSerpent** [darktable-org/darktable#8494]
Hello
Some photos, edited on Windows with 3.4.1.1, cannot be imported without losing history into compiled Linux version from git master. 
The latest applied commit is 2ec5c0cb49f4ea6116c6ecaffc384fe390e4ad02

Linux is Mint Mate x64 20.1. 
The terminal output during import is:
[exif] dt_exif_xmp_read for /media/sasha/WD5_5/Photos/2021.03.04_NFK/DSC08893_01.ARW.xmp, id 519642 found auto_presets_applied but there was no history
[exif] dt_exif_xmp_read for /media/sasha/WD5_5/Photos/2021.03.04_NFK/DSC08893_02.ARW.xmp, id 519643 found auto_presets_applied but there was no history

I suspect the problem is connected with changed default modules order during editing, but it can be wrong.

**Comment by aquatix** [comment]
I have the same or a really similar issue. Attached a Canon 70D raw file with the xmp file created with DT 3.2.1 that is not imported with DT 3.5 master. 3.5 master sees that there are multiple xmp's (it creates duplicates in the thumbnail overview), but no history is applied.

[IMG_0974.zip](https://github.com/darktable-org/darktable/files/6180987/IMG_0974.zip)

**Comment by Mark-64** [comment]
Confirmed in DT git master on Windows 10

**Comment by TurboGit** [comment]
@aquatix : Don't understand, works for me and there is no history (expect default) in your XMP? Can you send a proper reproducer or better explanation.

**Comment by aquatix** [comment]
Rats, my bad, sent the wrong sidecar :(

Here is the one with the actual history: [IMG_0974_01.CR2.zip](https://github.com/darktable-org/darktable/files/6204636/IMG_0974_01.CR2.zip)

**Comment by aquatix** [comment]
So, I have the .CR2 and those two sidecar files in a directory, and import the directory in DarkTable master (3.5.xxx). DT sees two variants to the image (based on the XMP count), but both show up as if no changes have been made.

**Comment by TurboGit** [comment]
Please test #8548.

**Comment by BigSerpent** [comment]
Thanks, now it works for me.

**Comment by TurboGit** [comment]
Thanks for testing and confirming.
