### ISSUE TITLE
Improve module header mask indicator

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8498]
Hi devs, 
after my recent work on the module header mask indicators, there is still a corner case which bothers me, and I would like to ask your opinion on how to improve it.
Specifically, what to do with the mask indicator when the module is switched off.
Today, the mask indicator button is sensitive, but activating it doesn't do anything, the mask is not displayed and this can be confusing for the user IMO.
I see two possible options:
1) clicking the mask indicator activates the module and displays the mask, just like the "show mask" button in the expander would do
2) set the button to insensitive when the module is off

I see pros and cons in both, what do you like more ?
Thanks in advance.

**Comment by TurboGit** [comment]
I would go with 2. With solution 1 you click and activate mask & module, a second click will disable the mask but the module will still be displayed, so a third click would be needed to disable the module using the on/off button. I don't see this as a good UX. So better go with 1 for now.

Maybe others will have better proposal.

**Comment by elstoc** [comment]
I vote for option 2.

**Comment by difrkaguilar** [comment]
I think when the module is off the module must be insensitive, the on & off override the show mask icon action. For me option 2 is better.

**Comment by rgo** [comment]
I also vote for option 2.

**Comment by johnny-bit** [comment]
Option 2 please.

**Comment by Mark-64** [comment]
Ok, option 2 coming

**Comment by difrkaguilar** [comment]
In the retouch module the mask indicator icon don't appear working with shapes, the applied mask are only visible selecting display mask icon inside the panel.

![Screenshot_20210319_051931](https://user-images.githubusercontent.com/67672868/111759471-036d2300-8874-11eb-905f-ee93df76c553.jpeg)

the mask indicator icon in header only appear using parametric mask.

![Screenshot_20210319_052319](https://user-images.githubusercontent.com/67672868/111759647-331c2b00-8874-11eb-96df-7e913a7efc68.jpeg)

It´s the default behavior?

**Comment by elstoc** [comment]
The indicator is intended for blend masks only. Any other masks are specific to individual modules and are not included in this change.
