### ISSUE TITLE
Text not always aligned in import module (related to panel width)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#8506]
**Describe the bug/issue**

Text is not always aligned depending on panel width in import module. @phweyland: probably for you.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open "parameters" expander in import module (last master)
2. Reduce left panel width (the issue is shown with a reduced panel width) to see that text is not always aligned on the left.

It's probably related to ellipsizing here.

**Expected behavior**
Having text correctly aligned on the width, in all panel width.

**Screenshots**
![2021-03-18_23-45](https://user-images.githubusercontent.com/45535283/111707484-077d4e80-883c-11eb-8516-6834b666f26f.png)

**Platform**
* darktable version : last master

**Comment by phweyland** [comment]
As you see the difference of alignment is related to text (entry) or not text parameters.
Even if it possible to align everything I don't agree that will better.
Last I don't know how ellipsize an entry.

**Comment by Nilvus** [comment]
> As you see the difference of alignment is related to text (entry) or not text parameters.
> Even if it is possible to align everything I don't agree that will better.
> Last I don't know how ellipsize an entry.

That not what I see. I can see not aligned text in nearly all lines if I reduce/expand panel. And when I talk about ellipsize, I don't talk about entry but only labels text on the left. The alignment is broken when a line begin to be ellipsized. That the only darktable part where I see that.

**Comment by Nilvus** [comment]
Another example (you could see that on this screenshot lines not aligned on the left are not the same as first one):
![2021-03-19_21-31](https://user-images.githubusercontent.com/45535283/111839059-1e7e7800-88f2-11eb-88ef-565d992d1b0b.png)

**Comment by phweyland** [comment]
Got it.
When changing the width the ellipsized text start position is not stable. I can see that in other modules as well like map settings, but not in image information.
I'll try to find the difference.

**Comment by phweyland** [comment]
Fix coming.

**Comment by phweyland** [comment]
Good catch. Thanks!
