### ISSUE TITLE
Some text not translated (and an error in french translation) in import module

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#8507]
**Describe the bug/issue**
Some texts are not translatable in import module. 
**To Reproduce**
Just check that "parameters" expander is not translated in other languages nor present in last pot file. Some text is not translated too in new import session window. See screenshot below for other text.

**Screenshots**
![2021-03-19_00-05](https://user-images.githubusercontent.com/45535283/111708838-78256a80-883e-11eb-8aa0-a7187ce04670.png)

In screenshot above, see french mistake: in top window bar ("copier et imported" instead of "copier et importer"). See that some text are still in english in bottom window.

I've found how to translate expanders. See diff below but it remains other text that are in data/darktableconfig.xml.in and I don't know how to make them translatable. @phweyland or @TurboGit: is one of you could correct that? 

```
diff --git a/src/libs/import.c b/src/libs/import.c
index 28948797d..aa219ae51 100644
--- a/src/libs/import.c
+++ b/src/libs/import.c
@@ -943,7 +943,7 @@ static void _import_from_dialog_new(dt_lib_module_t* self)
     gtk_box_pack_start(GTK_BOX(import_patterns), GTK_WIDGET(grid), FALSE, FALSE, 0);
 
     // collapsible section
-    _expander_create(&d->from.exp, "naming rules", "ui_last/session_expander_import", "import_metadata");
+    _expander_create(&d->from.exp, _("naming rules"), "ui_last/session_expander_import", "import_metadata");
     gtk_box_pack_start(GTK_BOX(import_patterns), d->from.exp.expander, FALSE, FALSE, 0);
 
     // patterns
@@ -1163,7 +1163,7 @@ void gui_init(dt_lib_module_t *self)
 #endif
 
   // collapsible section
-  _expander_create(&d->exp, "parameters", "ui_last/expander_import", "import_metadata");

```

**Comment by phweyland** [comment]
I don't know how to fix the translation for darktableconfig.xnl.in texts.

**Comment by TurboGit** [comment]
Nothing to fix in fact, the translation was not done.... I'm a bit late at the moment. And some part was not properly translated, the title of the dialog was: **"copier et imported"** (part in French and part in English :)
