### ISSUE TITLE
Fuji X-S10 lossless compressed RAW files can not be opened

### ISSUE THREAD

**Issue by thomaswhite** [darktable-org/darktable#8512]
The thumbnails of lossless compressed row files from X-S10 can be seen in LIghttable bu when I try to open a file I have the following error: "Darktable could not open file xxxx.raf file"

* darktable version : e.g. 3.4.0
* OS                    : Ubuntu
* Linux - Distro    : Kubuntu 20.04
* Memory            :  64Gb
* Graphics card     :  GeForce GTX 1650 SUPER/PCIe/SSE2
* Graphics driver   :  nvidia-driver-460
* OpenCL installed  : OpenCL 1.2 CUDA 11.2.153
* OpenCL activated  :  YES
* Xorg              : 
* Desktop           :  KDE
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
I can not upload the raw file, because RAF files are not allowed to be attached.

**Comment by johnny-bit** [comment]
Please create new ticket using [camera support](https://github.com/darktable-org/darktable/issues/new?assignees=LebedevRI&labels=scope%3A+camera+support&template=new_camera_support.md&title=%3CEnter+your+camera+name+here%3E) template and make sure to upload RAF files to raw.pixls.us

**Comment by kmilos** [comment]
It's supported already, just didn't make in time to get released...

Please see https://discuss.pixls.us/t/support-for-fuji-x-s10/22223/6

**Comment by johnny-bit** [comment]
Thanks @kmilos !
