### ISSUE TITLE
Fuji X-S10

### ISSUE THREAD

**Issue by thomaswhite** [darktable-org/darktable#8513]
The thumbnails of lossless compressed row files from X-S10 can be seen in LIghttable bu when I try to open a file I have the following error: "Darktable could not open file xxxx.raf file"

**Comment by kmilos** [comment]
It's supported already, just didn't make in time to get released...

Please see https://discuss.pixls.us/t/support-for-fuji-x-s10/22223/6

**Comment by johnny-bit** [comment]
Thanks @kmilos !

**Comment by thomaswhite** [comment]
Thank you @kmilos
