### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by eherle** [darktable-org/darktable#8514]
**Describe the bug/issue**
All of sudden, my dt crashes at startup. I am using version 3.4.1.20210315 (= v3.4.1.1) on Windows 10. Never happened to me before, dt was always very stable on W10. I have reinstalled dt a couple of times and updated the graphics driver, but the result is still the same: crash. When I start dt with the --disable-opencl, then dt starts ok.

**To Reproduce**
1. Start dt in W10

**Expected behavior**
dt starts without problem and uses OpenCL

**Screenshots**
<img width="309" alt="NVIDIA_Share_wUq3sfMmL1" src="https://user-images.githubusercontent.com/80984246/111835501-5509c200-88f5-11eb-8059-d5bbf8bd7365.png">

**Which commit intruduced the error**
Sorry, this abracadabra to me...

**Platform**
Windows 10 Pro build 19042.867

* darktable version : 3.4.1.20210315 (3.4.1.1)
* OS                : Windows 10 Pro build 19042.867
* Memory            :  16 GB
* Graphics card     :  NVidia GeForce GTX 1050 Ti
* Graphics driver   :  NVidia 27.21.14.6192
* OpenCL installed  : yes
* OpenCL activated  :  yes
* Xorg              :  unknown
* Desktop           :  Windows
* GTK+              :  unknown
* gcc               :  unknown
* cflags            :  unknown
* CMAKE_BUILD_TYPE  :  unknown

**Error report**
[darktable_bt_YLMH00.txt](https://github.com/darktable-org/darktable/files/6173727/darktable_bt_YLMH00.txt)

**Comment by parafin** [comment]
Remove this Microsoft product from the system: https://github.com/microsoft/OpenCLOn12
This is a duplicate and not a dt bug, so closing.

**Comment by eherle** [comment]
Removed the OpenCL pack and now it is working again. Thanks!
