### ISSUE TITLE
ILCE-1 Noise Profile

### ISSUE THREAD

**Issue by 1900mcm** [darktable-org/darktable#8522]
[darktable-noiseprofile-20210320.tar.gz](https://github.com/darktable-org/darktable/files/6176334/darktable-noiseprofile-20210320.tar.gz)

I had to convert from Sony ARW to TIFF to get them processed by convert and the noiseprofile scripts.

**Comment by rawfiner** [comment]
Unfortunately the result after conversion to tiff is not usable.
Could you try again using the raw files? Maybe using the -C option may help

**Comment by 1900mcm** [comment]
sadly, convert fails ( i even re-shot using the uncompressed format. )

W

The script will use existing input RAW images for the profiling. No more
shot will be taken.

===> Summing up profiling RAW images + Jpeg export
--> ISO 50:
    /home/nnnnnnn/darktable_sony-ilce-1/_DSC8235.ARW
convert convert: Unable to open file (/home/nnnnnnnn/darktable_sony-ilce-1/_DSC8235-large.jpg) [No such file or directory].

**Comment by rawfiner** [comment]
convert is used on a jpg file, that is exported from the raw file by darktable-cli
Here it seems that the problem is not due to convert, but another problem, as it looks like the jpg is not created.
Could you try to do `darktable-cli _DSC8235.ARW _DSC8235-large.jpg` in the same folder to check that this step works, and that the resulting jpg image can be opened by convert?

**Comment by 1900mcm** [comment]
darktable-cli yielded:

RawSpeed:Unable to find camera in database: 'SONY' 'ILCE-1' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (DSC8235.ARW) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 169: Camera 'SONY' 'ILCE-1', mode '' not supported, and not allowed to guess. Sorry.
[dt_imageio_export_with_flags] mipmap allocation for `DSC8235-large.jpg' failed
[imageio_storage_disk] could not export to file: `DSC8235-large.jpg'!


So I added to the /usr/share/darktable/rawspeed/cameras.xml


 <Camera make="SONY" model="ILCE-1">
        <ID make="Sony" model="ILCE-1">Sony ILCE-1</ID>
                <CFA width="2" height="2">
                        <Color x="0" y="0">RED</Color>
                        <Color x="1" y="0">GREEN</Color>
                        <Color x="0" y="1">GREEN</Color>
                        <Color x="1" y="1">BLUE</Color>
                  </CFA>
                      <Crop x="0" y="0" width="-32" height="0"/>
                      <Sensor black="512" white="16383"/>
     </Camera>

This gave me 
darktable-cli DSC8235.ARW DSC8235-large.jpg
[colorin] `Sony ILCE-1' color matrix not found!
[colorin] `Sony ILCE-1' color matrix not found!
[export_job] exported to `DSC8235-large.jpg'

**Comment by johnny-bit** [comment]
@1900mcm - seems like you have to have custom build of darktable to pull that off ;)

use rawspeed data from https://github.com/darktable-org/rawspeed/pull/274
and make sure you have adobe_coeff.c after 05b0630a986518e8b73db6c9d013301b7fe728da

**Comment by 1900mcm** [comment]
[darktable-noiseprofile-20210524.tar.gz](https://github.com/darktable-org/darktable/files/6532416/darktable-noiseprofile-20210524.tar.gz)



New noise

**Comment by rawfiner** [comment]
Thanks!
