### ISSUE TITLE
Lighttable - no images are shown in collection of subfolders

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8524]
**Describe the bug/issue**
I'm used to use the folder-mode in lighttable and just browse my images as in my OS file browser because of the my image organization on my hard-drive.
As of version 3.4.1 I would always see all images within a certain position in the folder tree, if I go down on more level, the amount of images is further reduced etc., like in this screenshot:
![dt-3 4 1](https://user-images.githubusercontent.com/810285/111886533-8efac700-89ce-11eb-9d9a-405d6047ff6f.png)

Somewhere between version 3.4.1 and master I suddenly get an empty collection when I browse through my folder-tree, see
![dt-master](https://user-images.githubusercontent.com/810285/111886554-bc477500-89ce-11eb-9c2e-b2f009a4a2f5.png)
Moreover there is also no preview on how many images are found in any hierarchy in the folder-tree. 
Is this a bug or an intended behaviour? :sweat_smile: 

In the meantime I'll try to further bisect down to the commit which introduced this change.
* 52e856f2700d72a9f6199aa992c1857f9d8f1baf (from 2021-02-04): Function as in version 3.4.1 
* d8e4a0868a76006b3fbaf9cb1a729a0f5bd2ae9f (from 2021-02-08): Function as in version 3.4.1 
* 012b331ebb9be912b0388e5cbe21fb0f35dfefc6 (from 2021-02-12): Folders still have the count of images, but the collection window is empty
* db52fddb7ca7bf922b2c82684863a006680063e3 (from 2021-02-23): Same as above
* 6ee1d4edeae06931f62d41466e87d211e2545baf (from 2021-03-02):  Same as above

Looks like I found the "suspect": 86a13b6371df6c837c214699875ad38f55ab59b5
I guess I now have to understand better the scope of this change and will update the issue then.

**Update**:
I see that a SHIFT-click shows the images again, as it was motivated by the following issue: https://github.com/darktable-org/darktable/issues/4976

@quovadit did you document this behaviour anywhere already? At least I didn't find it :sweat_smile: 

One mystery left is the vanished image count number in braces next to the folder name. I didn't further bisect after 6ee1d4edeae06931f62d41466e87d211e2545baf (from 2021-03-02), where the numbers were still present...
As @phweyland has touched the collections a couple of times since this commit maybe he has some pointers?

**Comment by phweyland** [comment]
> 012b331 (from 2021-02-12): Folders still have the count of images, but the collection window is empty

This is not correct. You should have the same numbers of images on both sides.

> One mystery left is the vanished image count number in braces next to the folder name. I didn't further bisect after [6ee1d4e](https://github.com/darktable-org/darktable/commit/6ee1d4edeae06931f62d41466e87d211e2545baf) (from 2021-03-02), where the numbers were still present...

Except new bug, it's normal have the numbers aligned (#8422)

**Comment by quovadit** [comment]
> did you document this behaviour anywhere already? At least I didn't find it sweat_smile

The new behaviour is already documented thanks to elstoc:
https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/collect-images/#files

**Comment by da-phil** [comment]
> > did you document this behaviour anywhere already? At least I didn't find it sweat_smile
> 
> The new behaviour is already documented thanks to elstoc:
> https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/collect-images/#files

Oh, I simply overlooked it, it looks good, sorry for the dumb question then :smile: 

> > [012b331](https://github.com/darktable-org/darktable/commit/012b331ebb9be912b0388e5cbe21fb0f35dfefc6) (from 2021-02-12): Folders still have the count of images, but the collection window is empty
> 
> This is not correct. You should have the same numbers of images on both sides.
> 
> > One mystery left is the vanished image count number in braces next to the folder name. I didn't further bisect after [6ee1d4e](https://github.com/darktable-org/darktable/commit/6ee1d4edeae06931f62d41466e87d211e2545baf) (from 2021-03-02), where the numbers were still present...
> 
> Except new bug, it's normal have the numbers aligned (#8422)

I think the numbers between the dt 3.4.1 screenshot and the other one is due to using different library versions (was necessary because the library database changed several times in between). So this should be fine, I guess

But now I understand the desired behaviour: only the images which directly belong to a parent folder are counted as such, not the images from all sub-folder. I guess that's fine too, if you have folder structures like that. However I'd be still interested in the total amount of images in a parent folder, giving me the total sum of a parent folder.
Right now it looks like that:
![dt-master-with-files-in-parent-folder](https://user-images.githubusercontent.com/810285/111906865-1be76400-8a53-11eb-9969-3911ec0ebc3d.png)
If I didn't have any images in the parent folder the number next to the folder name would disappear:
![dt-master](https://user-images.githubusercontent.com/810285/111907100-22c2a680-8a54-11eb-993b-f128a550a305.png)

In terms of UI, this feels inconsistent and misleading, as in a tree-structure I'd expect it to do the maths for me and subsequently summing up images from the sub-sub-sub-folder all the way to the parent folder. 

The current behaviour and [documentation](https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/collect-images/#files) looks good to me, only the numbers next to the folder don't make sense for me.

What do you think about it?

**Comment by elstoc** [comment]
There should be some indication in the UI as to what is currently being displayed (how do I know whether I shift, ctrl, or double-clicked?) but I'm not aware of anything right now.

**Comment by elstoc** [comment]
I've added a new PR #8799 that should help make it clearer when changing folder/sub-folder filter criteria.

**Comment by da-phil** [comment]
> I've added a new PR #8799 that should help make it clearer when changing folder/sub-folder filter criteria.

Yup, that would already help ;)

What do you think about my proposal on not affecting the displayed count numbers in the folder tree by the respective click variation, but only the display in the top bar?
I'd like to keep the recursive sum over all contained images in the folder tree view.

**Comment by elstoc** [comment]
That PR is replaced now with one that just updates the tooltips to show the shift+click and ctrl+click behaviour (#8801, now merged). I would say that the numbers on the collect module should reflect what the single- or double-click action would show (the number of images just in that folder, not including sub-folders) and that the shift and ctrl modifiers should just change the lighttable display and header.

**Comment by da-phil** [comment]
Closing this one as I've got the feeling that only I seem to be interested in this behaviour :smile:
