### ISSUE TITLE
Lua import filters are not being called when importing images

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#8525]
**Describe the bug/issue**
Lua can add import filters to control what images are imported.  Tried the "prefer raw over jpeg" filter and both the raw and the jpeg got imported.  Added debugging statements to the filter and they never printed so it looks like the filter was never called.

**To Reproduce**
1. Have a folder of images with raws and jpgs (same basename, different extension)
2. Start the import_filter_manager lua script, then the import_filters lua script
3. In the import parameters drop down select the import filter drop down and select "prefer raw over jpeg"
4. Import the folder
5. Notice jpgs and raws are both imported

**Expected behavior**
Only raws should have been imported

***Which commit intruduced the error**
ee9ac742f1fa0ac7d5ca2e8c39743934652df6a0

**Additional context**
The lua filter was called from dt_film_import1() in src/control/jobs/film_jobs.c from dt_film_import in src/common/film.c which was called from src/libs/import.c.  It appears that the new import process orphaned all of that code, but lua still uses the dt_film_import to import a film roll from a script.

I've attached a version of import_filters with debugging messages.  Replace import_filters.lua in official/, start darktable with -d lua, start import_filter_manager, start import_filters.  Go to the import settings and enable "prefer raw over jpeg"

In 7ef0d44c545536b39e43ac3fa0782bcddc1da654 you'll see a line for every image plus a few more if there are raws and jpegs.

In ee9ac742f1fa0ac7d5ca2e8c39743934652df6a0 there is nothing.

**Comment by wpferguson** [comment]
@phweyland can you have a look?  Thanks

**Comment by phweyland** [comment]
> @phweyland can you have a look? Thanks

Sure,  I'll do.

**Comment by phweyland** [comment]
Got the problem:
the previous [folder...] import did not show the list the of images  to be selected for import as [import in-place] or [copy and import] do now, and applied the filter under the hood. While currently selected files are considered to be imported.

Possible solutions:
- Add the lua filter under the hood as it worked before.
- Move the lua filter combo box into import dialog, beside "ignore jpeg" and "recursive", and make it work as these last ones, on the fly.

The first solution is simpler but not consistent with the current behavior.
What do you think ?

**Comment by wpferguson** [comment]
I think under the hood is the right way to go.

Now I have some other thoughts/questions?

Is the new import faster than the src/control/jobs/film.c one?  I think it might be (at least it seems so to me).  What do we do with the old code in film.c?  The lua function darktable.films.new uses the film.c code and so does darktable.database.import.  Should we replace the import code in film.c with your new one?

Should the import code be in control_jobs or should it be in a separate file such as control/jobs/import.c?  Then film.c could call routines from import.c to do the import, though film.c can also call them wherever they are.  Just a thought.  They may be fine where they are.  I just noticed it last night when I was trying to trace how the import was happening.

**Comment by phweyland** [comment]
> Is the new import faster than the src/control/jobs/film.c one?
> Then film.c could call routines from import.c to do the import

The difference I can see is that the current process (in control_jobs.c) uses a predefined list of images while film.c still has to browse the files and apply the filters, including the lua one (BTW, it deletes the images list, recreates it even if no lua filter is activated. May deserve some love. Is there way to know if the lua filter is activated or not ?).
film.c calls also more frequently the SIGNAL_xxx.

> What do we do with the old code in film.c? 

If it useful or used it should be kept.
The new process ([import in-place...] is ui oriented (reacts to filters, shows thumbs on demand). On the other hand film.c is autonomous and works well in background.

> I think under the hood is the right way to go.

Not perfect but let's start with that.

**Comment by phweyland** [comment]
There are 2 points which would deserve some tenderness about this lua filter:
- delete/create the images list even without lua filter activated.
- sort the list by name. In case of [import in-place] this is not an issue. But could not be applied to [copy and import], because this may change the requested order.

**Comment by wpferguson** [comment]
> May deserve some love. Is there way to know if the lua filter is activated or not ?).

The filter sets an event handler to be called when the pre-import event is fired.  Right now (meaning I need/could/should write one) there isn't a method to check if an event has any handlers.  Even then I could only tell you if the event was active or not, not if there was a specific filter active (okay, thoughts started rattling around in my brain, so maybe I can figure out a way).

> On the other hand film.c is autonomous and works well in background.  

Which is where it would be called from if called from a script.  My only concern would be that the filter appears to work the same in both instances.

> But could not be applied to [copy and import], because this may change the requested order.

Does import order make a difference? Or, can copy and import do multiple directories at once?  I haven't tried copy and import.  Guess I need to.

> sort the list by name

The reason for the sort was so it was easy to detect paired raw and jpegs, since they share the same basename and different endings.  I guess it would depend on the filter and if it's order dependent.  I could always sort in lua, but it would be slow.

**Comment by phweyland** [comment]
> > But could not be applied to [copy and import], because this may change the requested order.
> 
> Does import order make a difference? Or, can copy and import do multiple directories at once? I haven't tried copy and import. Guess I need to.

As it uses the session renaming patterns, in particular sequence number, the order can matter.

**Comment by phweyland** [comment]
> > sort the list by name
> 
> The reason for the sort was so it was easy to detect paired raw and jpegs, since they share the same basename and different endings. I guess it would depend on the filter and if it's order dependent. I could always sort in lua, but it would be slow.

Thinking about it the process could be:
- copy the input list and sort it.
- generate the list of file to reject (lua)
- remove them from the input list.
- delete the reject list
...

**Comment by wpferguson** [comment]
The only problem is if there isn't a filter, then you would get back the same list and delete everything.

**Comment by wpferguson** [comment]
Does the import fire the post-import-film or post-import-image events?

**Comment by phweyland** [comment]
> The only problem is if there isn't a filter, then you would get back the same list and delete everything.

True ...

**Comment by wpferguson** [comment]
> Is there way to know if the lua filter is activated or not ?

You could check the preference `lua/import_filter_manager/active_filter` and see if it's set to something other than blank.

**Comment by wpferguson** [comment]
@phweyland we could change the filters to return a list of the images to remove and you could just skip the whole filter unless the preference is set

**Comment by wpferguson** [comment]
But, I'd have to remember to update film.c to handle the changed return list.

**Comment by phweyland** [comment]
> we could change the filters to return a list of the images to remove and you could just skip the whole filter unless the preference is set

I like the idea. In that case we could apply the filter also on [copy and import].


> But, I'd have to remember to update film.c to handle the changed return list.

I'll take care of this.
