### ISSUE TITLE
[Feature] Ability to customize the Image information module content

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#8527]
Hello !

The "Image information" module may be useful, but as of today, it displays a lot of lines/info, many of them not being necessarily useful for all users.

It would be great if the line shown in the Information module (LT & DR) could be customized.

Looks like the usual module menu could be used
![image](https://user-images.githubusercontent.com/3989573/111901626-9d31fd00-8a39-11eb-9685-76299d48c449.png)
so that there are some user custom made selection, as well as an hard-coded "Show all" to get the native/current behavior.

Here's yet another user desiderata ... that I realize has a dev/test cost ... Anyway, just logging this one...

Have a good day,
GLLM

**Comment by quovadit** [comment]
already implemented by phweyland (#7294)
will be in 3.6

**Comment by GLLM** [comment]
OK, great !

Sorry, I guess I did not see that PR being merged !
