### ISSUE TITLE
Switching module with applied mask off then on discards the mask

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#8528]
Cheking what module did not with snapshot but with switching the module off/on makes the mask ineffective. While it's still there it is not effectively applied. I can see it at least with the second module instance.

**To Reproduce**
1. Create second instance of Exposure module.
2. Create drawn mask (didn't check but suppose that the parametric mask is also appropriate)
3. Change the exposure (the image is changed according to the mask)
4. Switch this instance off (returning to previous look)
5. Switch the instance on again (exposure compensation is applied to whole image while the mask is technically in place but ineffective)

**Expected behavior**
On/off doesn't discard mask usage

* darktable version : 3.4.1
* OS                : linux 5.9.0-pf7
* Linux - Distro    : Gentoo

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support disabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by elstoc** [comment]
I can't reproduce this in 3.4.1 on ArchLinux.

**Comment by kanyck** [comment]
I checked it once more -- the issue is there. So it's maybe different CFLAGS involved. I think I need to rebuild dt with relaxed set of flags like `-O2 -pipe` and check again. I'll report if the problem is gone.

**Comment by kanyck** [comment]
Here it comes:
`-O2 -pipe` -> OK
`-O3 -pipe -march=native` -> fail (Ryzen 1)
`-O2 -pipe -march=native` -> OK 
`-O3 -pipe -march=native` -> OK again
my original CFLAGS set -> still OK
...which suggests that probably we see some kind of underfined behaviour bug which non-standard CFLAGS tend to disclose.
I've experienced random mask dropouts before, but because it was highly random I didn't report it. Now I seem to temporarily catch the pattern, but it still a "floating" kind of bug. Now it seems to work, but because I use prelink, I'm expecting this bug to show up again as soon as the libs are rearranged.
A side note: testing dt with optimization deeper than `-O2 -pipe ` seems to be quite useful to catch this kind of bugs. Dt up to 3.0 worked just fine with LTO, current versions don't -- which suggests that maybe there are some more hidden bugs in the code.

**Comment by Mark-64** [comment]
Yes, I've noticed this random bug when working on mask indicators in master and it drove me crazy trying to fix it, with no success. 
It actually prevented me to improve the behavior of the "show mask" button in the module expander because then the issue becomes reproducible 100% even in debug mode.
Initially I thought it was my code, but then I got convinced it was an underlying "sleeping" bug that my modification brought to surface.
This report is actually confirming my guess since it is there in 3.4.1.
In practice, `module->blend_params->mask_id` gets lost. It is ok when switching off the module and it becomes zero when switching it back on, but I could identify where it gets changed.  I even put breakpoints in debugger in all places where `mask_id` is changed, but none of them is hit.
If some dev with deeper knowledge of the pipeline is interested, I can tell a simple change in the code that makes the issue reproducible.

**Comment by dhoulder** [comment]
I've noticed this bug too. Was also present in 3.2.1 (on Xubunut 20.04, dt built from source with build.sh --prefix /opt/darktable --build-type Release )
It also appears in Aurélien Pierre's video demonstrating the color calibration module. See  https://youtu.be/U4CEN0JPcoM?t=4452 - bug appears at 1:15:26

**Comment by TurboGit** [comment]
We will really need a simple reproducer for this as I cannot reproduce and never had this. Maybe there is some very specific set of actions to do to reproduce.

**Comment by kanyck** [comment]
Obviously it needs some extra (unknown) conditions to be met. Under this conditions, it's steadily reproducible))) As I noted here-above, simple rebuilding may trigger it on/off. If it's triggered on, it is reproducible. Also, CFLAGS may be involved somehow, I don't think that directly, rather different code generation causes some rearrangements that trigger it. Looks like hanging pointer or alike, the bug may reside very far from masking code itself...

**Comment by Mark-64** [comment]
I am pushing a simple PR which makes the issue  100% reproducible for me, for testing purposes

**Comment by Mark-64** [comment]
I found a way to reproduce in master without the PR.

1. start with a fresh edit
2. in module exposure, change exposure substantially in order to have a visible effect
3. create a drawn mask to apply the change to a shape
4. click the "show mask" button (or the mask indicator) to show the mask
5. while the mask is visualized, turn off the module with the on/off button
6. click on another module to make exposure lose focus
7. turn the module exposure back on
8. see the mask is discarded, exposure is applied to the entire image

**Comment by TurboGit** [comment]
I can reproduce indeed ! Thanks a lot !

**Comment by TurboGit** [comment]
Makes me crazy :(

1. select exposure
2. add a circle mask
3. disable exposure
4. focus another widget and change a setting to force an entry in the history
5. enable expose => NO MORE MASK !!

In this simpler scenario there is no mask indicator in the loop. This was a red heading which lead me looking at the wrong part of the code. The issue seems that a disabled module loose its masks as soon as it is not the last gui module being used.

Fact is that the masks are not lost as appears in the mask manager and can be reset from the module blend combo. Something really fishy going on !

**Comment by TurboGit** [comment]
@Mark-64 : Do you confirm that this bug occurs only for the exposure module ?

**Comment by Mark-64** [comment]
No, it happens with other modules too, tried with color balance, color calibration and velvia.
With these it's even more weird. The mask gets lost and if I try to restore it with the blend combo, it doesn't get restored and the blend gui expander gets closed

**Comment by TurboGit** [comment]
For me I tried with "rgb curve" and cannot reproduce !

**Comment by TurboGit** [comment]
Even more weird :(

**Comment by TurboGit** [comment]
I cannot reproduce with velvia with my 5 steps reproducer above.

**Comment by TurboGit** [comment]
> I cannot reproduce with velvia with my 5 steps reproducer above.

EDIT: and cannot reproduce with your 8 steps procedure.

**Comment by Mark-64** [comment]
I spent a lot of time already trying to understand this!
The shapes are not lost, but `module->blend_params->mask_id` is put to zero somehow between step 3 and step 5 in your scenario.
I put breakpoints in all parts of the code where `module->blend_params->mask_id` is written, but none of them is reached!
I am now looking to the upper level struct `module->blend_params`. There are some cases where it gets allocated and written with memcpy and those parts are executed.

**Comment by TurboGit** [comment]
I cannot reproduce with 3.4 but the OP has this on 3.4.1. More and more looks like a memory corruption or indeed an undefined behavior due to optimization!

**Comment by jenshannoschwalm** [comment]
Sorry i cant test myself atm but are you sure this is correct?
`static void _dev_add_history_item_ext(dt_develop_t *dev, dt_iop_module_t *module, gboolean enable,
                                      gboolean new_item, gboolean no_image, gboolean include_masks)`


```
   if(include_masks)
      hist->forms = dt_masks_dup_forms_deep(dev->forms, NULL);
    else
      hist->forms = NULL;

```

The `dt_dev_add_history_item` and friends call this with 'include_masks == FALSE`

**Comment by Mark-64** [comment]
> Sorry i cant test myself atm but are you sure this is correct?

I am not sure this is a valid test but replacing all occurrencies of `include_masks` with `TRUE` inside that function, I still have the issue

**Comment by Mark-64** [comment]
> I cannot reproduce with 3.4 but the OP has this on 3.4.1. More and more looks like a memory corruption

I will try to go back to 3.4 and if that is good make a bisect

> or indeed an undefined behavior due to optimization!

But in that case why do I have the issue with Debug build which disables optimizations?

**Comment by parafin** [comment]
More likely this is a race condition.

**Comment by Mark-64** [comment]
> I will try to go back to 3.4 and if that is good make a bisect

I had to go back to 3.0.2 to find a release without this bug :-( 
Not sure bisect will be useful, but I will try

**Comment by Mark-64** [comment]
> Not sure bisect will be useful, but I will try

no way, I can't build so releases so old :-(

**Comment by bdemaistre** [comment]
I have quite a similar bug :
I set a module (for example a second instance of exposure) with a mask (for exemple a circle to compensate the corner fall-off  with A +2ev value). 
I saved this as a new style
When I use the style on another image the new instance of exposure is created but the mask is not there and the exposure is not changed !
When I click on the draw mask circle, the mask created on the first image appear and is applied with the exposure change (only then the +2ev set as exposure has some effect)

I tested the 8 steps and I have the same as Mark-64  : the exposure change is no more applied
However there is a difference : with the 8 steps the drawn mask is still listed in the exposure module.

I hope this may give some clue as to where is the problem
I use version 3.5.0~git1504.0b341ff95-1 on ubuntu20.10

**Comment by Mark-64** [comment]
> When I use the style on another image the new instance of exposure is created but the mask is not there and the exposure is not changed !
> When I click on the draw mask circle, the mask created on the first image appear and is applied with the exposure change (only then the +2ev set as exposure has some effect)

Yes the mask seems not to be copied in the style, but for me the exposure change is applied immediately to the whole image. I am not sure this is the same issue though. Perhaps you should open another report.
The mask code needs some review...

**Comment by TurboGit** [comment]
@Mark-64 : See #8543.
