### ISSUE TITLE
Additional history stacks ignored

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#8536]
**Describe the bug/issue**
When I import an image that has two sidecar files, the contents of the second file (FILE_01.RAW.xmp) are ignored and reset with standard and auto-applied modules. (I don't use darktable's DAM features and use :memory: as my database and always (re)import my images to lighttable.)

**To Reproduce**
1. Import an image that has two sidecar files
2. Notice that the edits on the second image are lost

**Expected behavior**
If I replace the main sidecar file with the second one and delete the second sidecar, I get the correct result, so the sidecar is not corrupted (see the second screenshot).

**Screenshots**
Image with two sidecars, notice the second one.
![image](https://user-images.githubusercontent.com/18402158/112049388-38b98f80-8b58-11eb-9559-d6e75e809db4.png)

The second version as it should be.
![image](https://user-images.githubusercontent.com/18402158/112049007-b335df80-8b57-11eb-983b-cd47d99d8b85.png)

**Which commit intruduced the error**
The second version was created with 3.5.0+1032 and I didn't notice any anomalies, but I'm not sure if I ever reimported the image.

**Platform**
* darktable version : e.g. 3.5.0+1488
* OS                : Ubuntu 20.10 & Windows 10/64
* database:	:memory:

**Additional information**
This can be the same issue as #8494, comment from @aquatix.

**Comment by Nilvus** [comment]
Seems to be yes. The issue was fixed 2 hours ago. So I close now as duplicate. I suggest so to update to last master and reopen if it's not solved (or ask me to reopen if you can't).

**Comment by juhavlintula** [comment]
Yes, it's fixed now.
