### ISSUE TITLE
Darkroom: scales slider in "retouch" modul not working with fluxbox window-manager

### ISSUE THREAD

**Issue by nostromo426** [darktable-org/darktable#8542]
**Describe the bug/issue**
In darktable 3.4.1 adding scales in the "retouch" module is not working with the fluxbox window manager.
Running darktable with the xfce4 IDE works fine.

**To Reproduce**
1 Start fluxbox (like e.g. version 1.3.5), launch darktable
2 Go to darkroom view
3 Select module "*retouch*"
4 Try adding scales in the "*wavelet decomposition*" by clicking and dragging the lower triangle in the lower slider

**Expected behavior**
The slider should be draggable to the right or left.

**Platform**
* darktable version : 3.4.1-1.1
* OS                : Linux - kernel 5.4.0-67-generic #75-Ubuntu SMP
* Linux - Distro    : Ubuntu 20.04LTS
* Xorg              : 1:7.7+19ubuntu14
* Desktop           : fluxbox 1.3.5-2build2
* GTK+              :  3.24.20-0ubuntu1

**Additional context**
This (to me) sounds similar to bug-reports [github:5638](https://github.com/darktable-org/darktable/issues/5638) and [redmine:12387](https://redmine.darktable.org/issues/12387).

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by nostromo426** [comment]
Found a work-around for me (accidentally): the mouse-wheel lets me add/remove scales and move the merge-slider.

**Comment by johnny-bit** [comment]
Have you filled the issue with fluxbox? It's imo pretty much out of scope of darktable to control external windowmanager behaviour.

Additional problem might be that wavelet decomp slider is custom ui element so it's less tested than say all the other sliders (including gradientsliders)

**Comment by johnny-bit** [comment]
This is IMO fluxbox issue. The code in question looks "OK", works on windows/mac and on most window managers. We can only do so much...

Closing. If found again - please link to fluxbox bug tracker.
