### ISSUE TITLE
Slideshow view should allow for image rotation/orientation change and rating via hotkeys

### ISSUE THREAD

**Issue by curiousercreative** [darktable-org/darktable#8551]
**Is your feature request related to a problem? Please describe.**
With a large set of images (perhaps scans) where orientation is commonly incorrect and images generally need culling, there's no view that allows for both rating and image rotation via hotkey.

**Describe the solution you'd like**
Adding the same `[` and `]` hotkeys along with the `0-5` and `R` hotkeys that are active on the darkroom view to the slideshow view would allow for culling. These hotkeys and the slideshow view are particularly helpful when viewing images in a social or collaborative way. For example, projected on a screen for a team or party or just viewing with my partner who I share a photo library with.

**Alternatives**
1. The "culling" subview of the lighttable view is also a great candidate for my workflow needs. Conveniently, the rating hotkeys already exist there, but the `[` and `]` hotkeys are unfortunately bound for other purposes.
2. The darkroom view conveniently has the `[` and `]` hotkeys, but navigating photos within the darkroom view appears to break that hotkey. Also, my attempts to remap the next and previous image (from space and backspace to left and right arrow) failed.

**Additional context**
I'm migrating from Apple Aperture and hoping that darktable can support existing workflows.

**Comment by Nilvus** [comment]
The slideshow need a complete rewrite. We just need a developer to work on.

See that related issue: #7118

**Comment by AlicVB** [comment]
You can affect a shortcuts to "utility modules/selected images/rotate selected images by ..." 
Then, for your workflow, you can view images with the "full preview layout" (last icon on bottom bar) and use this shortcuts to rotate your images, rating shortcuts also works in this mode...

I'm not sure it will works on slideshow, but imho, full preview is way better to achieve what you want (basically it's like slideshow, with auto-advance, but with way more features)

**Comment by curiousercreative** [comment]
@AlicVB I agree, since opening this issue I've found full preview to be more what I was looking for. I'll try that shortcut in full preview mode, thanks for the suggestion!

**Comment by TurboGit** [comment]
Yes, and I don't think we want to support more in slideshow. It is indeed just a slideshow so the proposal from @AlicVB  is the solution.

**Comment by curiousercreative** [comment]
@AlicVB that works brilliantly and applies to all lighttable views (as I had hoped it would)! I had previously attempted to accomplish this, but I had incorrectly added the shortcut key to various processing modules as they are the top search results within the shortcut key preferences view. Thanks a million!
