### ISSUE TITLE
Tethering Live View on 4k HDPI is to small

### ISSUE THREAD

**Issue by delightfuldude** [darktable-org/darktable#8553]
Hi!
Does anyone know how to make the live view in tethering mode full screen? On 4k displays it's very small:
![2021-03-26_11-09](https://user-images.githubusercontent.com/41424438/112616157-a8af6a80-8e23-11eb-933a-12cb86d3d6ef.png)
I'm on arch linux and darktable 3.4.1

**Comment by elstoc** [comment]
I'm not familiar with how this works but I would assume that the size of the preview is probably controlled by your camera and can't be amended.

**Comment by james-h-dt** [comment]
Hopefully there's a solution, as I've used tethering with the same camera under both darktable and Entangle. 

On a 4k monitor. darktable showed a similar small image as OP; Entangle showed a more-useful full-screen image.

**Comment by TurboGit** [comment]
Can one of you test the PR #8603 and report if it fixes the issue on 4k HiDPI screen ? TIA.

**Comment by james-h-dt** [comment]
Sure thing - although I've not done this with darktable. I guess I need to
download source & build? Can you point me in the right direction.

**Comment by elstoc** [comment]
@james-h-dt there's a guide on the project [README](https://github.com/darktable-org/darktable/blob/master/README.md)

**Comment by james-h-dt** [comment]
Thanks @elstoc for adding the detail re. pull request. I was scratching my head a bit at first.  

I'm seeing an unexpected blocker when setting up the build dependencies. From the darktable build guide, I need to run this:

```
sed -e '/^#\sdeb-src /s/^# *//;t;d' "/etc/apt/sources.list" \
| sudo tee /etc/apt/sources.list.d/darktable-sources-tmp.list > /dev/null \
  && (    sudo apt-get update \
       && sudo apt-get build-dep darktable \
  ); sudo rm /etc/apt/sources.list.d/darktable-sources-tmp.list
```

I get an error:

```
Err:13 https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04 ./ InRelease
  The following signatures were invalid: EXPKEYSIG DFA175A75104960E Emulators OBS Project <Emulators@build.opensuse.org>

W: GPG error: https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04 ./ InRelease: The following signatures were invalid: EXPKEYSIG DFA175A75104960E Emulators OBS Project <Emulators@build.opensuse.org>
E: The repository 'https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04 ./ InRelease' is not signed.
```

If I check the contents of darktable-sources-tmp.list:

```
sed -e '/^#\sdeb-src /s/^# *//;t;d' "/etc/apt/sources.list" \
| sudo tee /etc/apt/sources.list.d/darktable-sources-tmp.list > /dev/null \
  && (    sudo apt-get update \
       && sudo apt-get build-dep darktable \
  ); cat /etc/apt/sources.list.d/darktable-sources-tmp.list

deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic main restricted
deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic universe
deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic-updates universe
deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic multiverse
deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb-src http://gb.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb-src http://archive.canonical.com/ubuntu bionic partner
deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
deb-src http://security.ubuntu.com/ubuntu bionic-security universe
deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse
deb-src https://dl.winehq.org/wine-builds/ubuntu/ bionic main
deb-src https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./
```

Looks like there may be a conflict between darktable-sources-tmp.list and - at least for for Ubuntu 18.04 - the current state of deb-src https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/  ?

Any quick pointers to getting round this?
