### ISSUE TITLE
Liquify at the border of a crop should use pixels from area outside of the crop

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8560]
Hey folks :wave: here's something I observed learning about the liquify tool and trying to apply it to my workflow.

When I first crop and then fix smaller symmetry issues at the border of the crop with liquify, the liquify module fills in pixels at the  border of the crop with all black pixels and not with pixels from just outside of the crop.

It looks like the crop tool comes before the liquify tool in the pixel pipeline, and therefore probably no longer has access to the original image's pixels before the crop?

Is this on purpose or should the liquify tool consider the pixels outside of the crop when inpainting pixels at the borders?

**Comment by elstoc** [comment]
I have similar issues with retouch and spot removal. For now, you can manually move liquify if you need to access the cropped area but IMO we need to consider reordering the pipe to put those three modules after crop.

**Comment by johnny-bit** [comment]
This got fixed via introduction of simplified crop module (preent in current master AND part of 3.6 release) that comes in the pipe AFTER liquify. Now "big" crop&rotate is before to trim & rotate in non-creative ways (corrective) and then there's crop that allows for creative cropping.

If you don't mind I'd close this now :) But if you have any objections I'll reopen!
