### ISSUE TITLE
Liquify should be allowed to change the image's resolution

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8561]
Hey folks :wave: here's something I observed learning about the liquify tool and trying to apply it to my workflow.

Sometimes I have the use case that in order to get the crop I want, I need to liquify to extend my image e.g. to the right for let's say another 5% or so. At the moment when I use liquify at the border, the image's resolution stays the same and liquify only gets applied to the image's pixels.

In other tools, liquify allows the user to extend the image's dimensions at the border by automatically increasing the image's dimension and then inpainting liquify's output there. How can I achieve this with darktable?

It would be a great addition if liquify could extend the image's dimensions to help users get the crop they want, when they are a bit short at the borders.

Thoughts?

Note: another liquify border issue https://github.com/darktable-org/darktable/issues/8560 that is not directly related.

**Comment by johnny-bit** [comment]
Interesting idea... I think that currently only lens correction module can enlarge image dimmensions and inpaints border pixels up to image dimmensions.
