### ISSUE TITLE
manage module layouts: convert side menu to combobox

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#8562]
The manage module layouts screen often has module groups that disappear off the right-hand-side of the dialog.

I would like to suggest that the left-hand menu pane be converted to a combobox at the top of the dialog so that more horizontal space can be given over to the module group manipulation pane.

This could even be combined into the existing "preset name" entry field.

**Comment by AlicVB** [comment]
hmmm not sure on this one : 
1. There's more than just the preset names on the left pane
2. Currently, you can have ~4 column visible at the same time in right pane. That means 5 column in the end in the modulegroups. I'm not sure that more than 5 groups in modulegroups is so usual... Maybe we can extend a bit the default dialog width to show another column ?
3. I find the consistency with the pref dialog great :) (and yes, I've just seen that the select preset is not highlighted anymore. I'll fix that)

**Comment by elstoc** [comment]
I use quite a small font and, of the 7 pre-defined presets, three of them still disappear off the side of the screen, and the part-shown one at the end looks a little odd. It's a lot of information to fit onto the screen however we do it but I've not thought of a better idea yet. I agree there's probably not a nice solution, hence why I raised an issue instead of a PR - to prompt alternative suggestions.

> There's more than just the preset names on the left pane

There are buttons that could be moved to the top pane (beside the entry/combobox) if we wanted to

> Maybe we can extend a bit the default dialog width

IIRC when I redid the preferences window there were people with low-res laptop screens who thought it was already too big

**Comment by elstoc** [comment]
In fact if you duplicate an existing preset, they _all_ extend beyond the edge of the box, because you have to include the reorganisation controls.

Some possible ideas...

Do we need to see all of the groups on screen at the same time? Could we have the groups listed vertically and then click on each of them to reveal the contained modules/widgets? We could then get rid of the move left/right arrows and just use drag-and-drop to reorder. The only downside is that they are ordered horizontally in the darkroom (so the manage window doesn't use exactly the same representation). An alternative is to lay them out as tabs, as per the darkroom (similarly, click to reveal the modules) but just show the icon in the tab (right-click to change the icon or rename).

**Comment by AlicVB** [comment]
> An alternative is to lay them out as tabs, as per the darkroom (similarly, click to reveal the modules) but just show the icon in the tab (right-click to change the icon or rename).

I like the idea.
In fact no need to right click (that doesn't mean we can't add it) : we can just add 2 lines at the beginning of each tab : one for the tab name one for the thumb... To simplify even more the change, we can even keep the left/right arrows so we don't have to code tab drag-drop (that can be done in a second part)...



> Of course, we could implement the latter suggestions directly in the darkroom.

Not sure : I would prefer no to add too much of those direct things in darkroom...

I'm quite short in time atm. So I'm not sure that I'll be able to code that soon... If you have the time, don't hesitate !

**Comment by elstoc** [comment]
> If you have the time, don't hesitate !

Hmm. I might do. I've never coded anything this involved in Gtk before so might be an interesting challenge. I might do some initial playing and if I get anywhere I'll self-assign the issue.

**Comment by AlicVB** [comment]
Great !
Don't hesitate to ask for help :)
I'm sure you know that, but just in case, the base function where the gui is constructed is in `_manage_editor_load`

**Comment by elstoc** [comment]
Thanks. I have the bit between my teeth now :)

**Comment by elstoc** [comment]
This is done now. Closing.
