### ISSUE TITLE
Windows build: lua not found

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#8563]
Building dt git master in windows 10 on a fully updated MSYS2 installation.
Lua is indeed installed

```
$ pacman -Q | grep lua
mingw-w64-x86_64-lua 5.4.2-1
```

However cmake doesn't find it 

```
-- The following OPTIONAL packages have not been found:

 * Lua53 (required version >= 5.3)
```

**Comment by johnny-bit** [comment]
Dt requires 5.3.x not >= 5.3 :/

**Comment by Mark-64** [comment]
Ok, I downgraded manually to 5.3.5-1 and now cmake finds it.
However, I guess this is an issue, either we make dt build with 5.4 or update the build instructions

**Comment by wpferguson** [comment]
When I thought 3.6 was releasing in December, lua 5.4 was on the roadmap, https://github.com/darktable-org/darktable/issues/8052.  However, 3.6 is in June and I can't get there from here. The plan is to build a lua test framework on 5.3, then make the change to 5.4 and verify everything works using the test framework.  Alternative plan is to drop lua 5.4 in early in dt 3.7 and find bugs the hard way (crashing) while working on the test framework.

**Comment by Nilvus** [comment]
As #9299 will fix this and not linked, I close this to avoid forgetting it later.
