### ISSUE TITLE
Canon Rebel T7

### ISSUE THREAD

**Issue by SprinterChair** [darktable-org/darktable#8569]
Hi there! Some time over the last few months the lens correction module stopped recognizing my camera, the Canon Rebel T7. Additionally, I haven't been able to manually select a camera or lens in the module. I've tried my hardest to understand what is going on and how to fix it, but my best guess now after trying everything is that my camera is suddenly not supported? 

I just submitted a raw file to https://raw.pixls.us/ under CC0. I hope this helps!

**Comment by LebedevRI** [comment]
Lens support problem is an upstream lensfun issue.
Perhaps you need to run `lensfun-update-data`.

**Comment by SprinterChair** [comment]
I am on Windows 10, and the kind people over on the subreddit r/darktable have told me that this command cannot be run on Windows 10, I have also confirmed that this is the case. How else can I update the lensfun data?
