### ISSUE TITLE
numerical local ui preferences: doesn't grab focus

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#8575]
in local "int" preferences, entered number are grab by shortcuts (0->6).
But using the numerical keypad the numbers are properly entered.

**To Reproduce**

go to import module, try to change the initial rating using the keyboard numbers (not the numerical keypad).

**Expected behavior**

these numerical fields should grab the focus 

* darktable version : 3.5.0+1556~g5b4a9a8c4
* OS                : debian sid

**Comment by johnny-bit** [comment]
Is this still an issue? I cannot replicate on `3.5.0+2472~g9213e43cb`

**Comment by phweyland** [comment]
I cannot reproduce this any more as well ...

**Comment by johnny-bit** [comment]
Then if you don't mind let's close the issue :)
