### ISSUE TITLE
Nikon Z6 II

### ISSUE THREAD

**Issue by provanguard** [darktable-org/darktable#8576]
Samples are already present at https://raw.pixls.us for over 4 months
Current version of darkroom in darktable 3.4.1.1 fails to open any images from Nikon Z 6 II aka Z 6_2.
I don't own Z7 II, but if it is not supported yet, then it would be likely easy to add it together with Z 6 II.

**Comment by Nilvus** [comment]
There's already many closed issues about that. Support had been added in january (but not for 3.4.1) and so should be for 3.6.: https://github.com/darktable-org/darktable/commit/dcd4827bba877427ee53af16a6469ec050dc0db0

See all those issues (it's good to search before posting, thanks): https://github.com/darktable-org/darktable/issues?q=is%3Aissue+is%3Aclosed+Z6+

**Comment by provanguard** [comment]
Well, sorry for that. Where is 3.6 then, if support for Z6 II was added to it already in January?
How many years do you normally keep users waiting for support of their cameras?

**Comment by Nilvus** [comment]
> Well, sorry for that. Where is 3.6 then, if support for Z6 II was added to it already in January?
> How many years do you normally keep users waiting for support of their cameras?

3.6 will be for june and dakrtable is a free and open source software made by people in their free time, not a commercial software made by paid employees. If you want faster support, maybe use some commercial and pay for that...

**Comment by provanguard** [comment]
No offence, Sir. I do use paid software. 3 different ones even. I just ventured here to explore how things are around here in terms of new cameras support.
