### ISSUE TITLE
Allow more than 10 recently used collections in list

### ISSUE THREAD

**Issue by manu-p** [darktable-org/darktable#8581]
**Is your feature request related to a problem? Please describe.**

A list of 10 recently used collections may not be enough for some people. 
darktablerc shows a line like this:
`plugins/lighttable/recentcollect/num_items=10`

Changing num_items to a higher value has no effect, while to a lower one yes.

**Describe the solution you'd like**

In the lighttable preferences, allow to change this value to more than 10 (up to 20? more?) and take it into account to show the list of recently used collections.

**Comment by manu-p** [comment]
Are there any plan to add this feature in a future release?

**Comment by TurboGit** [comment]
There is an ongoing PR on this.
