### ISSUE TITLE
Provide guides outside of modules, not just for crop & rotate

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8582]
Hey folks :wave: 

when working on symmetry in images, guides and grids help tremendously. Unfortunately it seems like the guides and grids and tied to the crop & rotate module, and can not be used outside of this one module.

Here is an example use case: I want to use the liquify tool to subtly bring the shoulders on the same level. At the moment there is no way for a user to show guides with the liquify tool. What I end up doing is switching between liquify and crop & rotate (just for the grid guides), and then iterating manually until I'm somewhat happy with the result.

Is there a reason for the guides being tied to crop & rotate, or could a better way of handling guides be decoupled outside of the crop & rotate module, so users can e.g. always have them on, or use other modules with the guides, too?

Note: I've found https://github.com/darktable-org/darktable/issues/6736 which could be somewhat related.

**Comment by elstoc** [comment]
Yes I think discussing this in the broader context of #6736 would be good.
