### ISSUE TITLE
Make custom module groups easier to set up

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8587]
Hey folks :wave: 

I'm checking out the module groups and created my own group. In this group I want to put 10+ modules I usually use for a specific workflow, think: a module group for portrait workflows.

Right now this is a bit tedious for mainly two reasons
- the module names are right-aligned and the module name is then often cut off on the right side
- there is no way of searching for modules, instead I have to manually go through the list for every single module I want to add

See the screenshot below.

![dt-1](https://user-images.githubusercontent.com/527241/113042673-c1a97a00-919b-11eb-8163-97123e4ce5c8.jpg)

I would classify these problems as usability issues. In the end I could do what I wanted, but it was a tedious to do.

Can we improve here? Thoughts?

**Comment by elstoc** [comment]
Perhaps something like this...

![Screenshot_2021-03-30_21-43-13](https://user-images.githubusercontent.com/9555491/113054160-0257c200-91a1-11eb-8a50-ab313c97d057.png)

The menu on the right could then appear/adjust based on the chosen module group or quick access panel. It would essentially be the contents of the current right-click menu but in a scrollable box.

**Comment by dterrahe** [comment]
The menu of modules/widgets will eventually be ported to the structure of #8078 (again) so don't spend more than the minimum polishing time on that before 3.6, I would say. 

My "vision" always was that the "quick access" list would be a kind of special "shortcut" (just for iops). After #8078 we can probably add curves etc there as well. It would be fairly easy to double use the shortcuts dialog https://github.com/darktable-org/darktable/pull/8078#issuecomment-810890417 to have double left-click add a "normal" shortcut and double _right_ -click add the selected module/widget to the current quick access panel (or, modules only, group).
