### ISSUE TITLE
Please provide install package for Mac M1 (new ARM-based architecture) CPU.

### ISSUE THREAD

**Issue by kgflying** [darktable-org/darktable#8589]
**Is your feature request related to a problem? Please describe.**

On https://www.darktable.org/install/, currently, for mac OS, there is only 64bit install package. (dmg file)

So please provide install package for Mac M1 (new ARM-based architecture) CPU..

The new ARM-based architecture CPU is the default CPU on Macbook air and macbook pro 13 inch.

Thanks.

**Alternatives**

Rosetta may work. But very slow.

**Comment by parafin** [comment]
I may be able to look into that in April-May, but generally darktable project is really in need of someone volunteering to support macOS as a platform besides just me. There are people that contribute in that area too and I appreciate it, but I guess more commitment and involvement are required

**Comment by MStraeten** [comment]
M1 support requires macports to be providing the required ports for arm. Unless this is done there won’t be a m1 package. 
Have a look at #7564 - there‘re already some waiting to be able to build this

**Comment by 9527KGG** [comment]
Thanks. #7564 is little different. #7564 is about building the SRC, while this feature request is about install package (.dmg) file.

Anyway, thanks for helping

**Comment by MStraeten** [comment]
You won’t be able to provide a m1 package if you’re not able to build darktable from source ;)

**Comment by parafin** [comment]
I'm closing it in favour of #7564 - if we can build, there will be a package.
